/mnt/V8SourceCode/src/base/logging.cc File Reference
#include `src/base/logging.h`
#include <cctype>
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include `src/base/debug/stack_trace.h`
#include `src/base/platform/platform.h`
Classes
class anonymous_namespace{logging.cc}::FailureMessage
Namespaces
 v8
This file provides additional API on top of the default one for making API calls, which come from embedder C++ functions.
 v8::base
 v8::base::anonymous_namespace{logging.cc}
 anonymous_namespace{logging.cc}
Macros
#define CHAR_PRINT_CASE(ch)
#define DEFINE_PRINT_CHECK_OPERAND_CHAR(type)
#define DEFINE_MAKE_CHECK_OP_STRING(type)
Functions
void v8::base::anonymous_namespace{logging.cc}::DefaultDcheckHandler (const char *file, int line, const char *message)
std::string v8::base::anonymous_namespace{logging.cc}::PrettyPrintChar (int ch)
void v8::base::SetPrintStackTrace (void(*print_stack_trace)())
void v8::base::SetDcheckFunction (void(*dcheck_function)(const char *, int, const char *))
void v8::base::SetFatalFunction (void(*fatal_function)(const char *, int, const char *))
void v8::base::FatalOOM (OOMType type, const char *msg)
void V8_Fatal (const char *format,...)
void V8_Dcheck (const char *file, int line, const char *message)
Variables
void(* v8::base::anonymous_namespace{logging.cc}::g_print_stack_trace)() = nullptr
void(* v8::base::anonymous_namespace{logging.cc}::g_dcheck_function)(const char *, int, const char *) = DefaultDcheckHandler
void(* v8::base::anonymous_namespace{logging.cc}::g_fatal_function)(const char *, int, const char *) = nullptr
Macro Definition Documentation
CHAR_PRINT_CASE
#define CHAR_PRINT_CASE(ch)
Value:
  case ch: \
    oss << #ch; \
    break;
DEFINE_MAKE_CHECK_OP_STRING
#define DEFINE_MAKE_CHECK_OP_STRING(type)
Value:
  template std::string* MakeCheckOpString<type, type>(type, type, \
                                                      char const*); \
  template std::string PrintCheckOperand<type>(type);
Definition at line 126 of file logging.cc.
DEFINE_PRINT_CHECK_OPERAND_CHAR
#define DEFINE_PRINT_CHECK_OPERAND_CHAR(type)
Value:
  template <> \
  std::string PrintCheckOperand<type>(type ch) { \
    return PrettyPrintChar(ch); \
  } \
  template <> \
  std::string PrintCheckOperand<type*>(type * cstr) { \
    return PrintCheckOperand<void*>(cstr); \
  } \
  template <> \
  std::string PrintCheckOperand<const type*>(const type* cstr) { \
    return PrintCheckOperand<const void*>(cstr); \
  }
Definition at line 106 of file logging.cc.
Function Documentation
V8_Dcheck()
void V8_Dcheck (const char * file, int line, const char * message)
Definition at line 218 of file logging.cc.
                                                                {
  if (v8::base::DcheckFailuresAreIgnored()) {
    // In this mode, DCHECK failures don't lead to process termination.
    v8::base::OS::PrintError(
        "# Ignoring debug check failure in %s, line %d: %s\n", file, line,
        message);
    return;
  }
  v8::base::g_dcheck_function(file, line, message);
}
References v8::base::DcheckFailuresAreIgnored(), file(), and v8::base::anonymous_namespace{logging.cc}::g_dcheck_function.
Referenced by cppgc::internal::DCheckImpl().
V8_Fatal()
void V8_Fatal (const char * format, ...)
Definition at line 170 of file logging.cc.
                                       {
  const char* file = "";
  int line = 0;
#endif
  va_list arguments;
  va_start(arguments, format);
  // Format the error message into a stack object for later retrieveal by the
  // crash processor.
  FailureMessage message(format, arguments);
  va_end(arguments);
  if (v8::base::g_fatal_function != nullptr) {
    v8::base::g_fatal_function(file, line, message.message_);
  }
  fflush(stdout);
  fflush(stderr);
  // Print the formatted message to stdout without cropping the output.
  if (v8::base::ControlledCrashesAreHarmless()) {
    // In this case, instead of crashing the process will be terminated
    // normally by OS::Abort. Make this clear in the output printed to stderr.
    v8::base::OS::PrintError(
        "\n\n#\n# Safely terminating process due to error in %s, line %d\n# ",
        file, line);
    // Also prefix the error message (printed below). This has two purposes:
    // (1) it makes it clear that this error is deemed "safe" (2) it causes
    // fuzzers that pattern-match on stderr output to ignore these failures.
    v8::base::OS::PrintError("The following harmless error was encountered: ");
  } else {
    v8::base::OS::PrintError("\n\n#\n# Fatal error in %s, line %d\n# ", file,
                             line);
  }
  // Print the error message.
  va_start(arguments, format);
  v8::base::OS::VPrintError(format, arguments);
  va_end(arguments);
  // Print the message object's address to force stack allocation.
  v8::base::OS::PrintError("\n#\n#\n#\n#FailureMessage Object: %p", &message);
  if (v8::base::g_print_stack_trace) v8::base::g_print_stack_trace();
  fflush(stderr);
  v8::base::OS::Abort();
}
References v8::base::OS::Abort(), v8::base::ControlledCrashesAreHarmless(), file(), v8::base::format, v8::base::anonymous_namespace{logging.cc}::g_fatal_function, and v8::base::anonymous_namespace{logging.cc}::g_print_stack_trace.
Referenced by v8::base::anonymous_namespace{logging.cc}::DefaultDcheckHandler(), cppgc::internal::Fatal(), cppgc::internal::FatalImpl(), and cppgc::internal::FatalOutOfMemoryHandler::operator()().