/mnt/V8SourceCode/src/wasm/c-api.cc File Reference
#include `src/wasm/c-api.h`
#include <cstring>
#include <iomanip>
#include <iostream>
#include `include/libplatform/libplatform.h`
#include `include/v8-initialization.h`
#include `src/api/api-inl.h`
#include `src/builtins/builtins.h`
#include `src/compiler/wasm-compiler.h`
#include `src/flags/flags.h`
#include `src/objects/call-site-info-inl.h`
#include `src/objects/js-collection-inl.h`
#include `src/objects/managed-inl.h`
#include `src/wasm/leb-helper.h`
#include `src/wasm/module-instantiate.h`
#include `src/wasm/signature-hashing.h`
#include `src/wasm/wasm-arguments.h`
#include `src/wasm/wasm-constants.h`
#include `src/wasm/wasm-engine.h`
#include `src/wasm/wasm-objects.h`
#include `src/wasm/wasm-result.h`
#include `src/wasm/wasm-serialization.h`
#include `third_party/wasm-api/wasm.h`
Classes
struct wasm::ConfigImpl
struct wasm::implement< Config >
struct wasm::EngineImpl
struct wasm::implement< Engine >
struct wasm::ManagedData
struct wasm::implement< Store >
struct wasm::ValTypeImpl
struct wasm::implement< ValType >
struct wasm::ExternTypeImpl
struct wasm::implement< ExternType >
struct wasm::FuncTypeImpl
struct wasm::implement< FuncType >
struct wasm::GlobalTypeImpl
struct wasm::implement< GlobalType >
struct wasm::TableTypeImpl
struct wasm::implement< TableType >
struct wasm::MemoryTypeImpl
struct wasm::implement< MemoryType >
struct wasm::ImportTypeImpl
struct wasm::implement< ImportType >
struct wasm::ExportTypeImpl
struct wasm::implement< ExportType >
class wasm::RefImpl< Ref, JSType >
struct wasm::implement< Ref >
struct wasm::anonymous_namespace{c-api.cc}::FrameImpl
struct wasm::implement< Frame >
struct wasm::implement< Trap >
struct wasm::implement< Foreign >
struct wasm::implement< Module >
struct wasm::implement< Shared< Module > >
struct wasm::implement< Extern >
struct wasm::implement< Func >
struct wasm::FuncData
class wasm::anonymous_namespace{c-api.cc}::SignatureHelper
struct wasm::implement< Global >
struct wasm::implement< Table >
struct wasm::implement< Memory >
struct wasm::implement< Instance >
struct borrowed_vec< T >
struct borrowed_val
struct wasm_callback_env_t
Namespaces
 wasm
 wasm::anonymous_namespace{c-api.cc}
Macros
#define WASM_EXPORT
#define DUMP_COUNTERS 0
#define WASM_DEFINE_OWN(name, Name)
#define ASSERT_VEC_BASE_SIZE(name, Name, vec, ptr_or_none)
#define WASM_DEFINE_VEC_BASE(name, Name, vec, ptr_or_none)
#define WASM_DEFINE_VEC_PLAIN(name, Name)
#define WASM_DEFINE_VEC_OWN(name, Name)
#define WASM_DEFINE_TYPE(name, Name)
#define WASM_DEFINE_REF_BASE(name, Name)
#define WASM_DEFINE_REF(name, Name)
#define WASM_DEFINE_SHARABLE_REF(name, Name)
Typedefs
using wasm::anonymous_namespace{c-api.cc}::PtrComprCageAccessScope = i::PtrComprCageAccessScope
Functions
auto wasm::anonymous_namespace{c-api.cc}::ReadLebU64 (const byte_t **pos) -> uint64_t
template<typename T >
ValKind wasm::anonymous_namespace{c-api.cc}::V8ValueTypeToWasm (T v8_valtype) requires(std
i::wasm::ValueType wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8 (ValKind kind)
Name wasm::anonymous_namespace{c-api.cc}::GetNameFromWireBytes (const i::wasm::WireBytesRef &ref, v8::base::Vector< const uint8_t > wire_bytes)
own< FuncType > wasm::anonymous_namespace{c-api.cc}::FunctionSigToFuncType (const i::wasm::FunctionSig *sig)
own< ExternType > wasm::anonymous_namespace{c-api.cc}::GetImportExportType (const i::wasm::WasmModule *module, const i::wasm::ImportExportKindCode kind, const uint32_t index)
void wasm::WASM_UNIMPLEMENTED (const char *s)
BEGIN FILE wasm-v8.cc.
template<class T >
void wasm::ignore (T)
template<class C >
auto wasm::impl (C *x) -> typename implement< C >::type *
template<class C >
auto wasm::impl (const C *x) -> const typename implement< C >::type *
template<class C >
auto wasm::seal (typename implement< C >::type *x) -> C *
template<class C >
auto wasm::seal (const typename implement< C >::type *x) -> const C *
void wasm::CheckAndHandleInterrupts (i::Isolate *isolate)
i::DirectHandle< i::String > wasm::VecToString (i::Isolate *isolate, const vec< byte_t > &chars)
own< Instance > wasm::anonymous_namespace{c-api.cc}::GetInstance (StoreImpl *store, i::DirectHandle< i::WasmInstanceObject > instance)
own< Frame > wasm::anonymous_namespace{c-api.cc}::CreateFrameFromInternal (i::DirectHandle< i::FixedArray > frames, int index, i::Isolate *isolate, StoreImpl *store)
ownvec< ExportType > wasm::ExportsImpl (i::DirectHandle< i::WasmModuleObject > module_obj)
auto wasm::extern_to_v8 (const Extern *ex) -> i::DirectHandle< i::JSReceiver >
auto wasm::anonymous_namespace{c-api.cc}::make_func (Store *store_abs, std::shared_ptr< FuncData > data) -> own< Func >
own< Ref > wasm::anonymous_namespace{c-api.cc}::V8RefValueToWasm (StoreImpl *store, i::DirectHandle< i::Object > value)
i::DirectHandle< i::Object > wasm::anonymous_namespace{c-api.cc}::WasmRefToV8 (i::Isolate *isolate, const Ref *ref)
void wasm::anonymous_namespace{c-api.cc}::PrepareFunctionData (i::Isolate *isolate, i::DirectHandle< i::WasmExportedFunctionData > function_data, const i::wasm::CanonicalSig *sig)
void wasm::anonymous_namespace{c-api.cc}::PushArgs (const i::wasm::CanonicalSig *sig, const vec< Val > &args, i::wasm::CWasmArgumentsPacker *packer, StoreImpl *store)
void wasm::anonymous_namespace{c-api.cc}::PopArgs (const i::wasm::CanonicalSig *sig, vec< Val > &results, i::wasm::CWasmArgumentsPacker *packer, StoreImpl *store)
own< Trap > wasm::anonymous_namespace{c-api.cc}::CallWasmCapiFunction (i::Tagged< i::WasmCapiFunctionData > data, const vec< Val > &args, vec< Val > &results)
i::DirectHandle< i::JSReceiver > wasm::anonymous_namespace{c-api.cc}::GetProperException (i::Isolate *isolate, i::DirectHandle< i::Object > maybe_exception)
template<class T >
auto is_empty (T *p) -> bool
wasm_config_t * wasm_config_new ()
wasm_engine_t * wasm_engine_new ()
wasm_engine_t * wasm_engine_new_with_config (wasm_config_t *config)
wasm_store_t * wasm_store_new (wasm_engine_t *engine)
auto hide_mutability (wasm::Mutability mutability) -> wasm_mutability_t
auto reveal_mutability (wasm_mutability_t mutability) -> wasm::Mutability
auto hide_limits (const wasm::Limits &limits) -> const wasm_limits_t *
auto reveal_limits (wasm_limits_t limits) -> wasm::Limits
auto hide_valkind (wasm::ValKind kind) -> wasm_valkind_t
auto reveal_valkind (wasm_valkind_t kind) -> wasm::ValKind
auto hide_externkind (wasm::ExternKind kind) -> wasm_externkind_t
auto reveal_externkind (wasm_externkind_t kind) -> wasm::ExternKind
wasm_valtype_t * wasm_valtype_new (wasm_valkind_t k)
wasm_valkind_t wasm_valtype_kind (const wasm_valtype_t *t)
wasm_functype_t * wasm_functype_new (wasm_valtype_vec_t *params, wasm_valtype_vec_t *results)
const wasm_valtype_vec_t * wasm_functype_params (const wasm_functype_t *ft)
const wasm_valtype_vec_t * wasm_functype_results (const wasm_functype_t *ft)
wasm_globaltype_t * wasm_globaltype_new (wasm_valtype_t *content, wasm_mutability_t mutability)
const wasm_valtype_t * wasm_globaltype_content (const wasm_globaltype_t *gt)
wasm_mutability_t wasm_globaltype_mutability (const wasm_globaltype_t *gt)
wasm_tabletype_t * wasm_tabletype_new (wasm_valtype_t *element, const wasm_limits_t *limits)
const wasm_valtype_t * wasm_tabletype_element (const wasm_tabletype_t *tt)
const wasm_limits_t * wasm_tabletype_limits (const wasm_tabletype_t *tt)
wasm_memorytype_t * wasm_memorytype_new (const wasm_limits_t *limits)
const wasm_limits_t * wasm_memorytype_limits (const wasm_memorytype_t *mt)
wasm_externkind_t wasm_externtype_kind (const wasm_externtype_t *et)
wasm_externtype_t * wasm_functype_as_externtype (wasm_functype_t *ft)
wasm_externtype_t * wasm_globaltype_as_externtype (wasm_globaltype_t *gt)
wasm_externtype_t * wasm_tabletype_as_externtype (wasm_tabletype_t *tt)
wasm_externtype_t * wasm_memorytype_as_externtype (wasm_memorytype_t *mt)
const wasm_externtype_t * wasm_functype_as_externtype_const (const wasm_functype_t *ft)
const wasm_externtype_t * wasm_globaltype_as_externtype_const (const wasm_globaltype_t *gt)
const wasm_externtype_t * wasm_tabletype_as_externtype_const (const wasm_tabletype_t *tt)
const wasm_externtype_t * wasm_memorytype_as_externtype_const (const wasm_memorytype_t *mt)
wasm_functype_t * wasm_externtype_as_functype (wasm_externtype_t *et)
wasm_globaltype_t * wasm_externtype_as_globaltype (wasm_externtype_t *et)
wasm_tabletype_t * wasm_externtype_as_tabletype (wasm_externtype_t *et)
wasm_memorytype_t * wasm_externtype_as_memorytype (wasm_externtype_t *et)
const wasm_functype_t * wasm_externtype_as_functype_const (const wasm_externtype_t *et)
const wasm_globaltype_t * wasm_externtype_as_globaltype_const (const wasm_externtype_t *et)
const wasm_tabletype_t * wasm_externtype_as_tabletype_const (const wasm_externtype_t *et)
const wasm_memorytype_t * wasm_externtype_as_memorytype_const (const wasm_externtype_t *et)
wasm_importtype_t * wasm_importtype_new (wasm_name_t *module, wasm_name_t *name, wasm_externtype_t *type)
const wasm_name_t * wasm_importtype_module (const wasm_importtype_t *it)
const wasm_name_t * wasm_importtype_name (const wasm_importtype_t *it)
const wasm_externtype_t * wasm_importtype_type (const wasm_importtype_t *it)
wasm_exporttype_t * wasm_exporttype_new (wasm_name_t *name, wasm_externtype_t *type)
const wasm_name_t * wasm_exporttype_name (const wasm_exporttype_t *et)
const wasm_externtype_t * wasm_exporttype_type (const wasm_exporttype_t *et)
auto is_empty (wasm_val_t v) -> bool
auto hide_val (wasm::Val v) -> wasm_val_t
auto release_val (wasm::Val v) -> wasm_val_t
auto adopt_val (wasm_val_t v) -> wasm::Val
auto borrow_val (const wasm_val_t *v) -> borrowed_val
void wasm_val_vec_new (wasm_val_vec_t *out, size_t size, wasm_val_t const data[])
void wasm_val_vec_copy (wasm_val_vec_t *out, const wasm_val_vec_t *v)
void wasm_val_delete (wasm_val_t *v)
void wasm_val_copy (wasm_val_t *out, const wasm_val_t *v)
wasm_frame_t * wasm_frame_copy (const wasm_frame_t *frame)
wasm_instance_t * wasm_frame_instance (const wasm_frame_t *frame)
uint32_t wasm_frame_func_index (const wasm_frame_t *frame)
size_t wasm_frame_func_offset (const wasm_frame_t *frame)
size_t wasm_frame_module_offset (const wasm_frame_t *frame)
wasm_trap_t * wasm_trap_new (wasm_store_t *store, const wasm_message_t *message)
void wasm_trap_message (const wasm_trap_t *trap, wasm_message_t *out)
wasm_frame_t * wasm_trap_origin (const wasm_trap_t *trap)
void wasm_trap_trace (const wasm_trap_t *trap, wasm_frame_vec_t *out)
wasm_foreign_t * wasm_foreign_new (wasm_store_t *store)
bool wasm_module_validate (wasm_store_t *store, const wasm_byte_vec_t *binary)
wasm_module_t * wasm_module_new (wasm_store_t *store, const wasm_byte_vec_t *binary)
void wasm_module_imports (const wasm_module_t *module, wasm_importtype_vec_t *out)
void wasm_module_exports (const wasm_module_t *module, wasm_exporttype_vec_t *out)
void wasm_module_serialize (const wasm_module_t *module, wasm_byte_vec_t *out)
wasm_module_t * wasm_module_deserialize (wasm_store_t *store, const wasm_byte_vec_t *binary)
wasm_shared_module_t * wasm_module_share (const wasm_module_t *module)
wasm_module_t * wasm_module_obtain (wasm_store_t *store, const wasm_shared_module_t *shared)
auto wasm_callback (void *env, const wasm::vec< wasm::Val > &args, wasm::vec< wasm::Val > &results) -> wasm::own< wasm::Trap >
auto wasm_callback_with_env (void *env, const wasm::vec< wasm::Val > &args, wasm::vec< wasm::Val > &results) -> wasm::own< wasm::Trap >
void wasm_callback_env_finalizer (void *env)
wasm_func_t * wasm_func_new (wasm_store_t *store, const wasm_functype_t *type, wasm_func_callback_t callback)
wasm_func_t * wasm_func_new_with_env (wasm_store_t *store, const wasm_functype_t *type, wasm_func_callback_with_env_t callback, void *env, void(*finalizer)(void *))
wasm_functype_t * wasm_func_type (const wasm_func_t *func)
size_t wasm_func_param_arity (const wasm_func_t *func)
size_t wasm_func_result_arity (const wasm_func_t *func)
WASM_API_EXTERN wasm_trap_t * wasm_func_call (const wasm_func_t *func, const wasm_val_vec_t *args, wasm_val_vec_t *results)
wasm_global_t * wasm_global_new (wasm_store_t *store, const wasm_globaltype_t *type, const wasm_val_t *val)
wasm_globaltype_t * wasm_global_type (const wasm_global_t *global)
void wasm_global_get (const wasm_global_t *global, wasm_val_t *out)
void wasm_global_set (wasm_global_t *global, const wasm_val_t *val)
wasm_table_t * wasm_table_new (wasm_store_t *store, const wasm_tabletype_t *type, wasm_ref_t *ref)
wasm_tabletype_t * wasm_table_type (const wasm_table_t *table)
wasm_ref_t * wasm_table_get (const wasm_table_t *table, wasm_table_size_t index)
bool wasm_table_set (wasm_table_t *table, wasm_table_size_t index, wasm_ref_t *ref)
wasm_table_size_t wasm_table_size (const wasm_table_t *table)
bool wasm_table_grow (wasm_table_t *table, wasm_table_size_t delta, wasm_ref_t *ref)
wasm_memory_t * wasm_memory_new (wasm_store_t *store, const wasm_memorytype_t *type)
wasm_memorytype_t * wasm_memory_type (const wasm_memory_t *memory)
wasm_byte_t * wasm_memory_data (wasm_memory_t *memory)
size_t wasm_memory_data_size (const wasm_memory_t *memory)
wasm_memory_pages_t wasm_memory_size (const wasm_memory_t *memory)
bool wasm_memory_grow (wasm_memory_t *memory, wasm_memory_pages_t delta)
wasm_externkind_t wasm_extern_kind (const wasm_extern_t *external)
wasm_externtype_t * wasm_extern_type (const wasm_extern_t *external)
wasm_extern_t * wasm_func_as_extern (wasm_func_t *func)
wasm_extern_t * wasm_global_as_extern (wasm_global_t *global)
wasm_extern_t * wasm_table_as_extern (wasm_table_t *table)
wasm_extern_t * wasm_memory_as_extern (wasm_memory_t *memory)
const wasm_extern_t * wasm_func_as_extern_const (const wasm_func_t *func)
const wasm_extern_t * wasm_global_as_extern_const (const wasm_global_t *global)
const wasm_extern_t * wasm_table_as_extern_const (const wasm_table_t *table)
const wasm_extern_t * wasm_memory_as_extern_const (const wasm_memory_t *memory)
wasm_func_t * wasm_extern_as_func (wasm_extern_t *external)
wasm_global_t * wasm_extern_as_global (wasm_extern_t *external)
wasm_table_t * wasm_extern_as_table (wasm_extern_t *external)
wasm_memory_t * wasm_extern_as_memory (wasm_extern_t *external)
const wasm_func_t * wasm_extern_as_func_const (const wasm_extern_t *external)
const wasm_global_t * wasm_extern_as_global_const (const wasm_extern_t *external)
const wasm_table_t * wasm_extern_as_table_const (const wasm_extern_t *external)
const wasm_memory_t * wasm_extern_as_memory_const (const wasm_extern_t *external)
WASM_API_EXTERN wasm_instance_t * wasm_instance_new (wasm_store_t *store, const wasm_module_t *module, const wasm_extern_vec_t *imports, wasm_trap_t **trap)
void wasm_instance_exports (const wasm_instance_t *instance, wasm_extern_vec_t *out)
Variables
ValTypeImpl * wasm::valtype_i32 = new ValTypeImpl(ValKind::I32)
ValTypeImpl * wasm::valtype_i64 = new ValTypeImpl(ValKind::I64)
ValTypeImpl * wasm::valtype_f32 = new ValTypeImpl(ValKind::F32)
ValTypeImpl * wasm::valtype_f64 = new ValTypeImpl(ValKind::F64)
ValTypeImpl * wasm::valtype_externref = new ValTypeImpl(ValKind::EXTERNREF)
ValTypeImpl * wasm::valtype_funcref = new ValTypeImpl(ValKind::FUNCREF)
Macro Definition Documentation
ASSERT_VEC_BASE_SIZE
#define ASSERT_VEC_BASE_SIZE(name, Name, vec, ptr_or_none)
Value:
  static_assert(sizeof(wasm_##name##_vec_t) == sizeof(vec<Name>), \
                "C/C++ incompatibility"); \
  static_assert(\
      sizeof(wasm_##name##_t ptr_or_none) == sizeof(vec<Name>::elem_type), \
      "C/C++ incompatibility");
Definition at line 2536 of file c-api.cc.
DUMP_COUNTERS
#define DUMP_COUNTERS 0
Definition at line 85 of file c-api.cc.
WASM_DEFINE_OWN
#define WASM_DEFINE_OWN(name, Name)
Definition at line 2496 of file c-api.cc.
WASM_DEFINE_REF
#define WASM_DEFINE_REF(name, Name)
Value:
  WASM_DEFINE_REF_BASE(name, Name) \
                                                                           \
  wasm_ref_t* wasm_##name##_as_ref(wasm_##name##_t* r) { \
    return hide_ref(static_cast<wasm::Ref*>(reveal_##name(r))); \
  } \
  wasm_##name##_t* wasm_ref_as_##name(wasm_ref_t* r) { \
    return hide_##name(static_cast<Name*>(reveal_ref(r))); \
  } \
                                                                           \
  const wasm_ref_t* wasm_##name##_as_ref_const(const wasm_##name##_t* r) { \
    return hide_ref(static_cast<const wasm::Ref*>(reveal_##name(r))); \
  } \
  const wasm_##name##_t* wasm_ref_as_##name##_const(const wasm_ref_t* r) { \
    return hide_##name(static_cast<const Name*>(reveal_ref(r))); \
  }
Definition at line 2988 of file c-api.cc.
WASM_DEFINE_REF_BASE
#define WASM_DEFINE_REF_BASE(name, Name)
Value:
  WASM_DEFINE_OWN(name, Name) \
                                                                     \
  wasm_##name##_t* wasm_##name##_copy(const wasm_##name##_t* t) { \
    return release_##name(t->copy()); \
  } \
                                                                     \
  bool wasm_##name##_same(const wasm_##name##_t* t1, \
                          const wasm_##name##_t* t2) { \
    return t1->same(t2); \
  } \
                                                                     \
  void* wasm_##name##_get_host_info(const wasm_##name##_t* r) { \
    return r->get_host_info(); \
  } \
  void wasm_##name##_set_host_info(wasm_##name##_t* r, void* info) { \
    r->set_host_info(info); \
  } \
  void wasm_##name##_set_host_info_with_finalizer(\
      wasm_##name##_t* r, void* info, void (*finalizer)(void*)) { \
    r->set_host_info(info, finalizer); \
  }
Definition at line 2965 of file c-api.cc.
WASM_DEFINE_SHARABLE_REF
#define WASM_DEFINE_SHARABLE_REF(name, Name)
Value:
  WASM_DEFINE_REF(name, Name) \
  WASM_DEFINE_OWN(shared_##name, wasm::Shared<Name>)
Definition at line 3005 of file c-api.cc.
WASM_DEFINE_TYPE
#define WASM_DEFINE_TYPE(name, Name)
Value:
  WASM_DEFINE_OWN(name, Name) \
  WASM_DEFINE_VEC_OWN(name, Name) \
                                                       \
  WASM_API_EXTERN wasm_##name##_t* wasm_##name##_copy(\
      const wasm_##name##_t* t) { \
    return release_##name(t->copy()); \
  }
Definition at line 2741 of file c-api.cc.
WASM_DEFINE_VEC_BASE
#define WASM_DEFINE_VEC_BASE(name, Name, vec, ptr_or_none)
Definition at line 2544 of file c-api.cc.
WASM_DEFINE_VEC_OWN
#define WASM_DEFINE_VEC_OWN(name, Name)
Value:
  WASM_DEFINE_VEC_BASE(name, Name, wasm::ownvec, *) \
                                                                              \
  void wasm_##name##_vec_new(wasm_##name##_vec_t* out, size_t size, \
                             wasm_##name##_t* const data[]) { \
    auto v2 = wasm::ownvec<Name>::make_uninitialized(size); \
    for (size_t i = 0; i < v2.size(); ++i) { \
      v2[i] = adopt_##name(data[i]); \
    } \
    *out = release_##name##_vec(std::move(v2)); \
  } \
                                                                              \
  WASM_API_EXTERN void wasm_##name##_vec_copy(wasm_##name##_vec_t* out, \
                                              const wasm_##name##_vec_t* v) { \
    auto v2 = wasm::ownvec<Name>::make_uninitialized(v->size); \
    for (size_t i = 0; i < v2.size(); ++i) { \
      v2[i] = adopt_##name(wasm_##name##_copy(v->data[i])); \
    } \
    *out = release_##name##_vec(std::move(v2)); \
  }
Definition at line 2634 of file c-api.cc.
WASM_DEFINE_VEC_PLAIN
#define WASM_DEFINE_VEC_PLAIN(name, Name)
Value:
  WASM_DEFINE_VEC_BASE(name, Name, \
                       wasm::vec,) /* NOLINT(whitespace/parens) */ \
                                                                              \
  void wasm_##name##_vec_new(wasm_##name##_vec_t* out, size_t size, \
                             const wasm_##name##_t data[]) { \
    auto v2 = wasm::vec<Name>::make_uninitialized(size); \
    if (v2.size() != 0) { \
      memcpy(v2.get(), data, size * sizeof(wasm_##name##_t)); \
    } \
    *out = release_##name##_vec(std::move(v2)); \
  } \
                                                                              \
  WASM_API_EXTERN void wasm_##name##_vec_copy(wasm_##name##_vec_t* out, \
                                              const wasm_##name##_vec_t* v) { \
    wasm_##name##_vec_new(out, v->size, v->data); \
  }
Definition at line 2615 of file c-api.cc.
WASM_EXPORT
#define WASM_EXPORT
Definition at line 70 of file c-api.cc.
Function Documentation
adopt_val()
auto adopt_val (wasm_val_t v) -> wasm::Val [inline]
Definition at line 3069 of file c-api.cc.
                                               {
  switch (reveal_valkind(v.kind)) {
    case wasm::ValKind::I32:
      return wasm::Val(v.of.i32);
    case wasm::ValKind::I64:
      return wasm::Val(v.of.i64);
    case wasm::ValKind::F32:
      return wasm::Val(v.of.f32);
    case wasm::ValKind::F64:
      return wasm::Val(v.of.f64);
    case wasm::ValKind::EXTERNREF:
    case wasm::ValKind::FUNCREF:
      return wasm::Val(adopt_ref(v.of.ref));
    default:
      UNREACHABLE();
  }
}
References reveal_valkind(), and UNREACHABLE.
Referenced by wasm_val_vec_copy(), and wasm_val_vec_new().
borrow_val()
auto borrow_val (const wasm_val_t * v) -> borrowed_val [inline]
Definition at line 3096 of file c-api.cc.
                                                            {
  wasm::Val v2;
  switch (reveal_valkind(v->kind)) {
    case wasm::ValKind::I32:
      v2 = wasm::Val(v->of.i32);
      break;
    case wasm::ValKind::I64:
      v2 = wasm::Val(v->of.i64);
      break;
    case wasm::ValKind::F32:
      v2 = wasm::Val(v->of.f32);
      break;
    case wasm::ValKind::F64:
      v2 = wasm::Val(v->of.f64);
      break;
    case wasm::ValKind::EXTERNREF:
    case wasm::ValKind::FUNCREF:
      v2 = wasm::Val(adopt_ref(v->of.ref));
      break;
    default:
      UNREACHABLE();
  }
  return borrowed_val(std::move(v2));
}
References reveal_valkind(), and UNREACHABLE.
Referenced by wasm_global_new(), and wasm_global_set().
hide_externkind()
auto hide_externkind (wasm::ExternKind kind) -> wasm_externkind_t [inline]
Definition at line 2729 of file c-api.cc.
                         {
  return static_cast<wasm_externkind_t>(kind);
}
Referenced by wasm_extern_kind(), and wasm_externtype_kind().
hide_limits()
auto hide_limits (const wasm::Limits & limits) -> const wasm_limits_t* [inline]
Definition at line 2712 of file c-api.cc.
                            {
  return reinterpret_cast<const wasm_limits_t*>(&limits);
}
Referenced by wasm_memorytype_limits(), and wasm_tabletype_limits().
hide_mutability()
auto hide_mutability (wasm::Mutability mutability) -> wasm_mutability_t [inline]
Definition at line 2702 of file c-api.cc.
                         {
  return static_cast<wasm_mutability_t>(mutability);
}
Referenced by wasm_globaltype_mutability().
hide_val()
auto hide_val (wasm::Val v) -> wasm_val_t [inline]
Definition at line 3019 of file c-api.cc.
                                              {
  wasm_val_t v2 = {hide_valkind(v.kind()), {}};
  switch (v.kind()) {
    case wasm::ValKind::I32:
      v2.of.i32 = v.i32();
      break;
    case wasm::ValKind::I64:
      v2.of.i64 = v.i64();
      break;
    case wasm::ValKind::F32:
      v2.of.f32 = v.f32();
      break;
    case wasm::ValKind::F64:
      v2.of.f64 = v.f64();
      break;
    case wasm::ValKind::EXTERNREF:
    case wasm::ValKind::FUNCREF:
      v2.of.ref = hide_ref(v.ref());
      break;
    default:
      UNREACHABLE();
  }
  return v2;
}
References hide_valkind(), and UNREACHABLE.
hide_valkind()
auto hide_valkind (wasm::ValKind kind) -> wasm_valkind_t [inline]
Definition at line 2721 of file c-api.cc.
                                                                          {
  return static_cast<wasm_valkind_t>(kind);
}
Referenced by hide_val(), release_val(), and wasm_valtype_kind().
is_empty() [1/2]
template<class T >
auto is_empty (T * p) -> bool [inline]
Definition at line 2657 of file c-api.cc.
                                   {
  return !p;
}
is_empty() [2/2]
auto is_empty (wasm_val_t v) -> bool [inline]
Definition at line 3015 of file c-api.cc.
                                           {
  return !is_ref(reveal_valkind(v.kind)) || !v.of.ref;
}
References reveal_valkind().
release_val()
auto release_val (wasm::Val v) -> wasm_val_t [inline]
Definition at line 3044 of file c-api.cc.
                                                 {
  wasm_val_t v2 = {hide_valkind(v.kind()), {}};
  switch (v.kind()) {
    case wasm::ValKind::I32:
      v2.of.i32 = v.i32();
      break;
    case wasm::ValKind::I64:
      v2.of.i64 = v.i64();
      break;
    case wasm::ValKind::F32:
      v2.of.f32 = v.f32();
      break;
    case wasm::ValKind::F64:
      v2.of.f64 = v.f64();
      break;
    case wasm::ValKind::EXTERNREF:
    case wasm::ValKind::FUNCREF:
      v2.of.ref = release_ref(v.release_ref());
      break;
    default:
      UNREACHABLE();
  }
  return v2;
}
References hide_valkind(), and UNREACHABLE.
Referenced by wasm_global_get().
reveal_externkind()
auto reveal_externkind (wasm_externkind_t kind) -> wasm::ExternKind [inline]
Definition at line 2734 of file c-api.cc.
                      {
  return static_cast<wasm::ExternKind>(kind);
}
reveal_limits()
auto reveal_limits (wasm_limits_t limits) -> wasm::Limits [inline]
Definition at line 2717 of file c-api.cc.
                                                                           {
  return wasm::Limits(limits.min, limits.max);
}
Referenced by wasm_memorytype_new(), and wasm_tabletype_new().
reveal_mutability()
auto reveal_mutability (wasm_mutability_t mutability) -> wasm::Mutability [inline]
Definition at line 2707 of file c-api.cc.
                      {
  return static_cast<wasm::Mutability>(mutability);
}
Referenced by wasm_globaltype_new().
reveal_valkind()
auto reveal_valkind (wasm_valkind_t kind) -> wasm::ValKind [inline]
Definition at line 2725 of file c-api.cc.
                                                                            {
  return static_cast<wasm::ValKind>(kind);
}
Referenced by adopt_val(), borrow_val(), is_empty(), wasm_val_copy(), wasm_val_delete(), and wasm_valtype_new().
wasm_callback()
auto wasm_callback (void * env, const wasm::vec< wasm::Val > & args, wasm::vec< wasm::Val > & results) -> wasm::own<wasm::Trap>
Definition at line 3263 of file c-api.cc.
                                                                   {
  auto f = reinterpret_cast<wasm_func_callback_t>(env);
  return adopt_trap(f(hide_val_vec(args), hide_val_vec(results)));
}
References v8::base::args.
Referenced by wasm_func_new().
wasm_callback_env_finalizer()
void wasm_callback_env_finalizer (void * env)
Definition at line 3283 of file c-api.cc.
                                            {
  auto t = static_cast<wasm_callback_env_t*>(env);
  if (t->finalizer) t->finalizer(t->env);
  delete t;
}
References wasm_callback_env_t::finalizer.
Referenced by wasm_func_new_with_env().
wasm_callback_with_env()
auto wasm_callback_with_env (void * env, const wasm::vec< wasm::Val > & args, wasm::vec< wasm::Val > & results) -> wasm::own<wasm::Trap>
Definition at line 3275 of file c-api.cc.
                         {
  auto t = static_cast<wasm_callback_env_t*>(env);
  return adopt_trap(
      t->callback(t->env, hide_val_vec(args), hide_val_vec(results)));
}
References v8::base::args.
Referenced by wasm_func_new_with_env().
wasm_config_new()
wasm_config_t* wasm_config_new ()
Definition at line 2673 of file c-api.cc.
                                 {
  return release_config(wasm::Config::make());
}
wasm_engine_new()
wasm_engine_t* wasm_engine_new ()
Definition at line 2681 of file c-api.cc.
                                 {
  return release_engine(wasm::Engine::make());
}
wasm_engine_new_with_config()
wasm_engine_t* wasm_engine_new_with_config (wasm_config_t * config)
Definition at line 2685 of file c-api.cc.
                                                                  {
  return release_engine(wasm::Engine::make(adopt_config(config)));
}
wasm_exporttype_name()
const wasm_name_t* wasm_exporttype_name (const wasm_exporttype_t * et)
Definition at line 2952 of file c-api.cc.
                                                                     {
  return hide_byte_vec(et->name());
}
wasm_exporttype_new()
wasm_exporttype_t* wasm_exporttype_new (wasm_name_t * name, wasm_externtype_t * type)
Definition at line 2946 of file c-api.cc.
                                                                {
  return release_exporttype(
      wasm::ExportType::make(adopt_byte_vec(name), adopt_externtype(type)));
}
References name, and v8::internal::tracing::type.
wasm_exporttype_type()
const wasm_externtype_t* wasm_exporttype_type (const wasm_exporttype_t * et)
Definition at line 2956 of file c-api.cc.
                                                                           {
  return hide_externtype(et->type());
}
wasm_extern_as_func()
wasm_func_t* wasm_extern_as_func (wasm_extern_t * external)
Definition at line 3448 of file c-api.cc.
                                                          {
  return hide_func(external->func());
}
wasm_extern_as_func_const()
const wasm_func_t* wasm_extern_as_func_const (const wasm_extern_t * external)
Definition at line 3461 of file c-api.cc.
                                                                            {
  return hide_func(external->func());
}
wasm_extern_as_global()
wasm_global_t* wasm_extern_as_global (wasm_extern_t * external)
Definition at line 3451 of file c-api.cc.
                                                              {
  return hide_global(external->global());
}
wasm_extern_as_global_const()
const wasm_global_t* wasm_extern_as_global_const (const wasm_extern_t * external)
Definition at line 3464 of file c-api.cc.
                                   {
  return hide_global(external->global());
}
wasm_extern_as_memory()
wasm_memory_t* wasm_extern_as_memory (wasm_extern_t * external)
Definition at line 3457 of file c-api.cc.
                                                              {
  return hide_memory(external->memory());
}
wasm_extern_as_memory_const()
const wasm_memory_t* wasm_extern_as_memory_const (const wasm_extern_t * external)
Definition at line 3471 of file c-api.cc.
                                   {
  return hide_memory(external->memory());
}
wasm_extern_as_table()
wasm_table_t* wasm_extern_as_table (wasm_extern_t * external)
Definition at line 3454 of file c-api.cc.
                                                            {
  return hide_table(external->table());
}
wasm_extern_as_table_const()
const wasm_table_t* wasm_extern_as_table_const (const wasm_extern_t * external)
Definition at line 3468 of file c-api.cc.
                                                                              {
  return hide_table(external->table());
}
wasm_extern_kind()
wasm_externkind_t wasm_extern_kind (const wasm_extern_t * external)
Definition at line 3415 of file c-api.cc.
                                                                  {
  return hide_externkind(external->kind());
}
References hide_externkind().
wasm_extern_type()
wasm_externtype_t* wasm_extern_type (const wasm_extern_t * external)
Definition at line 3418 of file c-api.cc.
                                                                   {
  return release_externtype(external->type());
}
wasm_externtype_as_functype()
wasm_functype_t* wasm_externtype_as_functype (wasm_externtype_t * et)
Definition at line 2866 of file c-api.cc.
                                                                    {
  return et->kind() == wasm::ExternKind::FUNC
             ? hide_functype(
                   static_cast<wasm::FuncType*>(reveal_externtype(et)))
             : nullptr;
}
References FUNC.
wasm_externtype_as_functype_const()
const wasm_functype_t* wasm_externtype_as_functype_const (const wasm_externtype_t * et)
Definition at line 2891 of file c-api.cc.
                                 {
  return et->kind() == wasm::ExternKind::FUNC
             ? hide_functype(
                   static_cast<const wasm::FuncType*>(reveal_externtype(et)))
             : nullptr;
}
References FUNC.
wasm_externtype_as_globaltype()
wasm_globaltype_t* wasm_externtype_as_globaltype (wasm_externtype_t * et)
Definition at line 2872 of file c-api.cc.
                                                                        {
  return et->kind() == wasm::ExternKind::GLOBAL
             ? hide_globaltype(
                   static_cast<wasm::GlobalType*>(reveal_externtype(et)))
             : nullptr;
}
wasm_externtype_as_globaltype_const()
const wasm_globaltype_t* wasm_externtype_as_globaltype_const (const wasm_externtype_t * et)
Definition at line 2898 of file c-api.cc.
                                 {
  return et->kind() == wasm::ExternKind::GLOBAL
             ? hide_globaltype(
                   static_cast<const wasm::GlobalType*>(reveal_externtype(et)))
             : nullptr;
}
wasm_externtype_as_memorytype()
wasm_memorytype_t* wasm_externtype_as_memorytype (wasm_externtype_t * et)
Definition at line 2884 of file c-api.cc.
                                                                        {
  return et->kind() == wasm::ExternKind::MEMORY
             ? hide_memorytype(
                   static_cast<wasm::MemoryType*>(reveal_externtype(et)))
             : nullptr;
}
wasm_externtype_as_memorytype_const()
const wasm_memorytype_t* wasm_externtype_as_memorytype_const (const wasm_externtype_t * et)
Definition at line 2912 of file c-api.cc.
                                 {
  return et->kind() == wasm::ExternKind::MEMORY
             ? hide_memorytype(
                   static_cast<const wasm::MemoryType*>(reveal_externtype(et)))
             : nullptr;
}
wasm_externtype_as_tabletype()
wasm_tabletype_t* wasm_externtype_as_tabletype (wasm_externtype_t * et)
Definition at line 2878 of file c-api.cc.
                                                                      {
  return et->kind() == wasm::ExternKind::TABLE
             ? hide_tabletype(
                   static_cast<wasm::TableType*>(reveal_externtype(et)))
             : nullptr;
}
wasm_externtype_as_tabletype_const()
const wasm_tabletype_t* wasm_externtype_as_tabletype_const (const wasm_externtype_t * et)
Definition at line 2905 of file c-api.cc.
                                 {
  return et->kind() == wasm::ExternKind::TABLE
             ? hide_tabletype(
                   static_cast<const wasm::TableType*>(reveal_externtype(et)))
             : nullptr;
}
wasm_externtype_kind()
wasm_externkind_t wasm_externtype_kind (const wasm_externtype_t * et)
Definition at line 2832 of file c-api.cc.
                                                                    {
  return hide_externkind(et->kind());
}
References hide_externkind().
wasm_foreign_new()
wasm_foreign_t* wasm_foreign_new (wasm_store_t * store)
Definition at line 3209 of file c-api.cc.
                                                      {
  return release_foreign(wasm::Foreign::make(store));
}
References store().
wasm_frame_copy()
wasm_frame_t* wasm_frame_copy (const wasm_frame_t * frame)
Definition at line 3165 of file c-api.cc.
                                                         {
  return release_frame(frame->copy());
}
wasm_frame_func_index()
uint32_t wasm_frame_func_index (const wasm_frame_t * frame)
Definition at line 3172 of file c-api.cc.
                                                          {
  return reveal_frame(frame)->func_index();
}
wasm_frame_func_offset()
size_t wasm_frame_func_offset (const wasm_frame_t * frame)
Definition at line 3176 of file c-api.cc.
                                                         {
  return reveal_frame(frame)->func_offset();
}
wasm_frame_instance()
wasm_instance_t * wasm_frame_instance (const wasm_frame_t * frame)
Definition at line 3507 of file c-api.cc.
                                                                {
  return hide_instance(reveal_frame(frame)->instance());
}
wasm_frame_module_offset()
size_t wasm_frame_module_offset (const wasm_frame_t * frame)
Definition at line 3180 of file c-api.cc.
                                                           {
  return reveal_frame(frame)->module_offset();
}
wasm_func_as_extern()
wasm_extern_t* wasm_func_as_extern (wasm_func_t * func)
Definition at line 3422 of file c-api.cc.
                                                      {
  return hide_extern(static_cast<wasm::Extern*>(reveal_func(func)));
}
wasm_func_as_extern_const()
const wasm_extern_t* wasm_func_as_extern_const (const wasm_func_t * func)
Definition at line 3435 of file c-api.cc.
                                                                        {
  return hide_extern(static_cast<const wasm::Extern*>(reveal_func(func)));
}
wasm_func_call()
WASM_API_EXTERN wasm_trap_t* wasm_func_call (const wasm_func_t * func, const wasm_val_vec_t * args, wasm_val_vec_t * results)
Definition at line 3318 of file c-api.cc.
                                                                     {
  auto v8_results = adopt_val_vec(results);
  auto ret = release_trap(func->call(adopt_val_vec(args), v8_results));
  *results = release_val_vec(std::move(v8_results));
  return ret;
}
References v8::base::args.
wasm_func_new()
wasm_func_t* wasm_func_new (wasm_store_t * store, const wasm_functype_t * type, wasm_func_callback_t callback)
Definition at line 3291 of file c-api.cc.
                                                          {
  return release_func(wasm::Func::make(store, type, wasm_callback,
                                       reinterpret_cast<void*>(callback)));
}
References store(), v8::internal::tracing::type, and wasm_callback().
wasm_func_new_with_env()
wasm_func_t* wasm_func_new_with_env (wasm_store_t * store, const wasm_functype_t * type, wasm_func_callback_with_env_t callback, void * env, void(*)(void *) finalizer)
Definition at line 3297 of file c-api.cc.
                                                                         {
  auto env2 = new wasm_callback_env_t{callback, env, finalizer};
  return release_func(wasm::Func::make(store, type, wasm_callback_with_env,
                                       env2, wasm_callback_env_finalizer));
}
References store(), v8::internal::tracing::type, wasm_callback_env_finalizer(), and wasm_callback_with_env().
wasm_func_param_arity()
size_t wasm_func_param_arity (const wasm_func_t * func)
Definition at line 3310 of file c-api.cc.
                                                      {
  return func->param_arity();
}
wasm_func_result_arity()
size_t wasm_func_result_arity (const wasm_func_t * func)
Definition at line 3314 of file c-api.cc.
                                                       {
  return func->result_arity();
}
wasm_func_type()
wasm_functype_t* wasm_func_type (const wasm_func_t * func)
Definition at line 3306 of file c-api.cc.
                                                         {
  return release_functype(func->type());
}
wasm_functype_as_externtype()
wasm_externtype_t* wasm_functype_as_externtype (wasm_functype_t * ft)
Definition at line 2836 of file c-api.cc.
                                                                    {
  return hide_externtype(static_cast<wasm::ExternType*>(ft));
}
wasm_functype_as_externtype_const()
const wasm_externtype_t* wasm_functype_as_externtype_const (const wasm_functype_t * ft)
Definition at line 2849 of file c-api.cc.
                               {
  return hide_externtype(static_cast<const wasm::ExternType*>(ft));
}
wasm_functype_new()
wasm_functype_t* wasm_functype_new (wasm_valtype_vec_t * params, wasm_valtype_vec_t * results)
Definition at line 2766 of file c-api.cc.
                                                                {
  return release_functype(wasm::FuncType::make(adopt_valtype_vec(params),
                                               adopt_valtype_vec(results)));
}
wasm_functype_params()
const wasm_valtype_vec_t* wasm_functype_params (const wasm_functype_t * ft)
Definition at line 2772 of file c-api.cc.
                                                                          {
  return hide_valtype_vec(ft->params());
}
wasm_functype_results()
const wasm_valtype_vec_t* wasm_functype_results (const wasm_functype_t * ft)
Definition at line 2776 of file c-api.cc.
                                                                           {
  return hide_valtype_vec(ft->results());
}
wasm_global_as_extern()
wasm_extern_t* wasm_global_as_extern (wasm_global_t * global)
Definition at line 3425 of file c-api.cc.
                                                            {
  return hide_extern(static_cast<wasm::Extern*>(reveal_global(global)));
}
wasm_global_as_extern_const()
const wasm_extern_t* wasm_global_as_extern_const (const wasm_global_t * global)
Definition at line 3438 of file c-api.cc.
                                                                              {
  return hide_extern(static_cast<const wasm::Extern*>(reveal_global(global)));
}
wasm_global_get()
void wasm_global_get (const wasm_global_t * global, wasm_val_t * out)
Definition at line 3343 of file c-api.cc.
                                                                   {
  *out = release_val(global->get());
}
References release_val().
wasm_global_new()
wasm_global_t* wasm_global_new (wasm_store_t * store, const wasm_globaltype_t * type, const wasm_val_t * val)
Definition at line 3332 of file c-api.cc.
                                                      {
  auto val_ = borrow_val(val);
  return release_global(wasm::Global::make(store, type, val_.it));
}
References borrow_val(), store(), and v8::internal::tracing::type.
wasm_global_set()
void wasm_global_set (wasm_global_t * global, const wasm_val_t * val)
Definition at line 3347 of file c-api.cc.
                                                                   {
  auto val_ = borrow_val(val);
  global->set(val_.it);
}
References borrow_val().
wasm_global_type()
wasm_globaltype_t* wasm_global_type (const wasm_global_t * global)
Definition at line 3339 of file c-api.cc.
                                                                 {
  return release_globaltype(global->type());
}
wasm_globaltype_as_externtype()
wasm_externtype_t* wasm_globaltype_as_externtype (wasm_globaltype_t * gt)
Definition at line 2839 of file c-api.cc.
                                                                        {
  return hide_externtype(static_cast<wasm::ExternType*>(gt));
}
References v8::internal::gt.
wasm_globaltype_as_externtype_const()
const wasm_externtype_t* wasm_globaltype_as_externtype_const (const wasm_globaltype_t * gt)
Definition at line 2853 of file c-api.cc.
                                 {
  return hide_externtype(static_cast<const wasm::ExternType*>(gt));
}
References v8::internal::gt.
wasm_globaltype_content()
const wasm_valtype_t* wasm_globaltype_content (const wasm_globaltype_t * gt)
Definition at line 2790 of file c-api.cc.
                                                                           {
  return hide_valtype(gt->content());
}
References v8::internal::gt.
wasm_globaltype_mutability()
wasm_mutability_t wasm_globaltype_mutability (const wasm_globaltype_t * gt)
Definition at line 2794 of file c-api.cc.
                                                                          {
  return hide_mutability(gt->mutability());
}
References v8::internal::gt, and hide_mutability().
wasm_globaltype_new()
wasm_globaltype_t* wasm_globaltype_new (wasm_valtype_t * content, wasm_mutability_t mutability)
Definition at line 2784 of file c-api.cc.
                                                                     {
  return release_globaltype(wasm::GlobalType::make(
      adopt_valtype(content), reveal_mutability(mutability)));
}
References reveal_mutability().
wasm_importtype_module()
const wasm_name_t* wasm_importtype_module (const wasm_importtype_t * it)
Definition at line 2930 of file c-api.cc.
                                                                       {
  return hide_byte_vec(it->module());
}
wasm_importtype_name()
const wasm_name_t* wasm_importtype_name (const wasm_importtype_t * it)
Definition at line 2934 of file c-api.cc.
                                                                     {
  return hide_byte_vec(it->name());
}
wasm_importtype_new()
wasm_importtype_t* wasm_importtype_new (wasm_name_t * module, wasm_name_t * name, wasm_externtype_t * type)
Definition at line 2924 of file c-api.cc.
                                                                {
  return release_importtype(wasm::ImportType::make(
      adopt_byte_vec(module), adopt_byte_vec(name), adopt_externtype(type)));
}
References name, and v8::internal::tracing::type.
wasm_importtype_type()
const wasm_externtype_t* wasm_importtype_type (const wasm_importtype_t * it)
Definition at line 2938 of file c-api.cc.
                                                                           {
  return hide_externtype(it->type());
}
wasm_instance_exports()
void wasm_instance_exports (const wasm_instance_t * instance, wasm_extern_vec_t * out)
Definition at line 3502 of file c-api.cc.
                                                   {
  *out = release_extern_vec(instance->exports());
}
wasm_instance_new()
WASM_API_EXTERN wasm_instance_t* wasm_instance_new (wasm_store_t * store, const wasm_module_t * module, const wasm_extern_vec_t * imports, wasm_trap_t ** trap)
Definition at line 3480 of file c-api.cc.
                                                          {
  wasm::own<wasm::Trap> error;
  size_t size = 0;
  if (imports->data && imports->size > 0) {
    size = imports->size;
  }
  auto v8_imports = wasm::vec<wasm::Extern*>::make_uninitialized(size);
  for (size_t i = 0; i < v8_imports.size(); i++) {
    v8_imports[i] = reveal_extern(imports->data[i]);
  }
  wasm_instance_t* instance =
      release_instance(wasm::Instance::make(store, module, v8_imports, &error));
  if (trap) *trap = hide_trap(error.release());
  return instance;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, size(), and store().
wasm_memory_as_extern()
wasm_extern_t* wasm_memory_as_extern (wasm_memory_t * memory)
Definition at line 3431 of file c-api.cc.
                                                            {
  return hide_extern(static_cast<wasm::Extern*>(reveal_memory(memory)));
}
wasm_memory_as_extern_const()
const wasm_extern_t* wasm_memory_as_extern_const (const wasm_memory_t * memory)
Definition at line 3444 of file c-api.cc.
                                                                              {
  return hide_extern(static_cast<const wasm::Extern*>(reveal_memory(memory)));
}
wasm_memory_data()
wasm_byte_t* wasm_memory_data (wasm_memory_t * memory)
Definition at line 3396 of file c-api.cc.
{ return memory->data(); }
wasm_memory_data_size()
size_t wasm_memory_data_size (const wasm_memory_t * memory)
Definition at line 3398 of file c-api.cc.
                                                          {
  return memory->data_size();
}
wasm_memory_grow()
bool wasm_memory_grow (wasm_memory_t * memory, wasm_memory_pages_t delta)
Definition at line 3406 of file c-api.cc.
                                                                        {
  return memory->grow(delta);
}
wasm_memory_new()
wasm_memory_t* wasm_memory_new (wasm_store_t * store, const wasm_memorytype_t * type)
Definition at line 3387 of file c-api.cc.
                                                              {
  return release_memory(wasm::Memory::make(store, type));
}
References store(), and v8::internal::tracing::type.
wasm_memory_size()
wasm_memory_pages_t wasm_memory_size (const wasm_memory_t * memory)
Definition at line 3402 of file c-api.cc.
                                                                  {
  return memory->size();
}
wasm_memory_type()
wasm_memorytype_t* wasm_memory_type (const wasm_memory_t * memory)
Definition at line 3392 of file c-api.cc.
                                                                 {
  return release_memorytype(memory->type());
}
wasm_memorytype_as_externtype()
wasm_externtype_t* wasm_memorytype_as_externtype (wasm_memorytype_t * mt)
Definition at line 2845 of file c-api.cc.
                                                                        {
  return hide_externtype(static_cast<wasm::ExternType*>(mt));
}
wasm_memorytype_as_externtype_const()
const wasm_externtype_t* wasm_memorytype_as_externtype_const (const wasm_memorytype_t * mt)
Definition at line 2861 of file c-api.cc.
                                 {
  return hide_externtype(static_cast<const wasm::ExternType*>(mt));
}
wasm_memorytype_limits()
const wasm_limits_t* wasm_memorytype_limits (const wasm_memorytype_t * mt)
Definition at line 2824 of file c-api.cc.
                                                                         {
  return hide_limits(mt->limits());
}
References hide_limits().
wasm_memorytype_new()
wasm_memorytype_t* wasm_memorytype_new (const wasm_limits_t * limits)
Definition at line 2820 of file c-api.cc.
                                                                    {
  return release_memorytype(wasm::MemoryType::make(reveal_limits(*limits)));
}
References reveal_limits().
wasm_module_deserialize()
wasm_module_t* wasm_module_deserialize (wasm_store_t * store, const wasm_byte_vec_t * binary)
Definition at line 3242 of file c-api.cc.
                                                                      {
  auto binary_ = borrow_byte_vec(binary);
  return release_module(wasm::Module::deserialize(store, binary_.it));
}
References store().
wasm_module_exports()
void wasm_module_exports (const wasm_module_t * module, wasm_exporttype_vec_t * out)
Definition at line 3233 of file c-api.cc.
                                                     {
  *out = release_exporttype_vec(reveal_module(module)->exports());
}
wasm_module_imports()
void wasm_module_imports (const wasm_module_t * module, wasm_importtype_vec_t * out)
Definition at line 3228 of file c-api.cc.
                                                     {
  *out = release_importtype_vec(reveal_module(module)->imports());
}
wasm_module_new()
wasm_module_t* wasm_module_new (wasm_store_t * store, const wasm_byte_vec_t * binary)
Definition at line 3222 of file c-api.cc.
                                                              {
  auto binary_ = borrow_byte_vec(binary);
  return release_module(wasm::Module::make(store, binary_.it));
}
References store().
wasm_module_obtain()
wasm_module_t* wasm_module_obtain (wasm_store_t * store, const wasm_shared_module_t * shared)
Definition at line 3252 of file c-api.cc.
                                                                      {
  return release_module(wasm::Module::obtain(store, shared));
}
References store().
wasm_module_serialize()
void wasm_module_serialize (const wasm_module_t * module, wasm_byte_vec_t * out)
Definition at line 3238 of file c-api.cc.
                                                                              {
  *out = release_byte_vec(reveal_module(module)->serialize());
}
wasm_module_share()
wasm_shared_module_t* wasm_module_share (const wasm_module_t * module)
Definition at line 3248 of file c-api.cc.
                                                                     {
  return release_shared_module(reveal_module(module)->share());
}
wasm_module_validate()
bool wasm_module_validate (wasm_store_t * store, const wasm_byte_vec_t * binary)
Definition at line 3217 of file c-api.cc.
                                                                              {
  auto binary_ = borrow_byte_vec(binary);
  return wasm::Module::validate(store, binary_.it);
}
References store().
wasm_store_new()
wasm_store_t* wasm_store_new (wasm_engine_t * engine)
Definition at line 2693 of file c-api.cc.
                                                    {
  return release_store(wasm::Store::make(engine));
}
wasm_table_as_extern()
wasm_extern_t* wasm_table_as_extern (wasm_table_t * table)
Definition at line 3428 of file c-api.cc.
                                                         {
  return hide_extern(static_cast<wasm::Extern*>(reveal_table(table)));
}
wasm_table_as_extern_const()
const wasm_extern_t* wasm_table_as_extern_const (const wasm_table_t * table)
Definition at line 3441 of file c-api.cc.
                                                                           {
  return hide_extern(static_cast<const wasm::Extern*>(reveal_table(table)));
}
wasm_table_get()
wasm_ref_t* wasm_table_get (const wasm_table_t * table, wasm_table_size_t index)
Definition at line 3365 of file c-api.cc.
                                                                               {
  return release_ref(table->get(index));
}
References v8::internal::index.
wasm_table_grow()
bool wasm_table_grow (wasm_table_t * table, wasm_table_size_t delta, wasm_ref_t * ref)
Definition at line 3378 of file c-api.cc.
                                      {
  return table->grow(delta, ref);
}
wasm_table_new()
wasm_table_t* wasm_table_new (wasm_store_t * store, const wasm_tabletype_t * type, wasm_ref_t * ref)
Definition at line 3356 of file c-api.cc.
                                              {
  return release_table(wasm::Table::make(store, type, ref));
}
References store(), and v8::internal::tracing::type.
wasm_table_set()
bool wasm_table_set (wasm_table_t * table, wasm_table_size_t index, wasm_ref_t * ref)
Definition at line 3369 of file c-api.cc.
                                     {
  return table->set(index, ref);
}
References v8::internal::index.
wasm_table_size()
wasm_table_size_t wasm_table_size (const wasm_table_t * table)
Definition at line 3374 of file c-api.cc.
                                                             {
  return table->size();
}
wasm_table_type()
wasm_tabletype_t* wasm_table_type (const wasm_table_t * table)
Definition at line 3361 of file c-api.cc.
                                                             {
  return release_tabletype(table->type());
}
wasm_tabletype_as_externtype()
wasm_externtype_t* wasm_tabletype_as_externtype (wasm_tabletype_t * tt)
Definition at line 2842 of file c-api.cc.
                                                                      {
  return hide_externtype(static_cast<wasm::ExternType*>(tt));
}
wasm_tabletype_as_externtype_const()
const wasm_externtype_t* wasm_tabletype_as_externtype_const (const wasm_tabletype_t * tt)
Definition at line 2857 of file c-api.cc.
                                {
  return hide_externtype(static_cast<const wasm::ExternType*>(tt));
}
wasm_tabletype_element()
const wasm_valtype_t* wasm_tabletype_element (const wasm_tabletype_t * tt)
Definition at line 2808 of file c-api.cc.
                                                                         {
  return hide_valtype(tt->element());
}
wasm_tabletype_limits()
const wasm_limits_t* wasm_tabletype_limits (const wasm_tabletype_t * tt)
Definition at line 2812 of file c-api.cc.
                                                                       {
  return hide_limits(tt->limits());
}
References hide_limits().
wasm_tabletype_new()
wasm_tabletype_t* wasm_tabletype_new (wasm_valtype_t * element, const wasm_limits_t * limits)
Definition at line 2802 of file c-api.cc.
                                                                  {
  return release_tabletype(
      wasm::TableType::make(adopt_valtype(element), reveal_limits(*limits)));
}
References reveal_limits().
wasm_trap_message()
void wasm_trap_message (const wasm_trap_t * trap, wasm_message_t * out)
Definition at line 3193 of file c-api.cc.
                                                                     {
  *out = release_byte_vec(reveal_trap(trap)->message());
}
wasm_trap_new()
wasm_trap_t* wasm_trap_new (wasm_store_t * store, const wasm_message_t * message)
Definition at line 3188 of file c-api.cc.
                                                                               {
  auto message_ = borrow_byte_vec(message);
  return release_trap(wasm::Trap::make(store, message_.it));
}
References store().
wasm_trap_origin()
wasm_frame_t* wasm_trap_origin (const wasm_trap_t * trap)
Definition at line 3197 of file c-api.cc.
                                                        {
  return release_frame(reveal_trap(trap)->origin());
}
wasm_trap_trace()
void wasm_trap_trace (const wasm_trap_t * trap, wasm_frame_vec_t * out)
Definition at line 3201 of file c-api.cc.
                                                                     {
  *out = release_frame_vec(reveal_trap(trap)->trace());
}
wasm_val_copy()
void wasm_val_copy (wasm_val_t * out, const wasm_val_t * v)
Definition at line 3150 of file c-api.cc.
                                                         {
  *out = *v;
  if (is_ref(reveal_valkind(v->kind))) {
    out->of.ref = v->of.ref ? release_ref(v->of.ref->copy()) : nullptr;
  }
}
References reveal_valkind().
Referenced by wasm_val_vec_copy().
wasm_val_delete()
void wasm_val_delete (wasm_val_t * v)
Definition at line 3144 of file c-api.cc.
                                    {
  if (is_ref(reveal_valkind(v->kind))) {
    adopt_ref(v->of.ref);
  }
}
References reveal_valkind().
wasm_val_vec_copy()
void wasm_val_vec_copy (wasm_val_vec_t * out, const wasm_val_vec_t * v)
Definition at line 3134 of file c-api.cc.
                                                                     {
  auto v2 = wasm::vec<wasm::Val>::make_uninitialized(v->size);
  for (size_t i = 0; i < v2.size(); ++i) {
    wasm_val_t val;
    wasm_val_copy(&v->data[i], &val);
    v2[i] = adopt_val(val);
  }
  *out = release_val_vec(std::move(v2));
}
References adopt_val(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and wasm_val_copy().
wasm_val_vec_new()
void wasm_val_vec_new (wasm_val_vec_t * out, size_t size, wasm_val_t const data[])
Definition at line 3125 of file c-api.cc.
                                               {
  auto v2 = wasm::vec<wasm::Val>::make_uninitialized(size);
  for (size_t i = 0; i < v2.size(); ++i) {
    v2[i] = adopt_val(data[i]);
  }
  *out = release_val_vec(std::move(v2));
}
References adopt_val(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and size().
wasm_valtype_kind()
wasm_valkind_t wasm_valtype_kind (const wasm_valtype_t * t)
Definition at line 2758 of file c-api.cc.
                                                          {
  return hide_valkind(t->kind());
}
References hide_valkind().
wasm_valtype_new()
wasm_valtype_t* wasm_valtype_new (wasm_valkind_t k)
Definition at line 2754 of file c-api.cc.
                                                   {
  return release_valtype(wasm::ValType::make(reveal_valkind(k)));
}
References reveal_valkind().