v8::internal::TryStatement Class Reference
#include <ast.h>
Public Member Functions
Block * try_block () const
void set_try_block (Block *b)
Protected Member Functions
TryStatement (Block *try_block, int pos, NodeType type)
Private Attributes
Block * try_block_
Additional Inherited Members
Detailed Description
Definition at line 774 of file ast.h.
Constructor & Destructor Documentation
TryStatement()
v8::internal::TryStatement::TryStatement (Block * try_block, int pos, NodeType type) [inline], [protected]
Definition at line 780 of file ast.h.
      : Statement(pos, type), try_block_(try_block) {}
Member Function Documentation
set_try_block()
void v8::internal::TryStatement::set_try_block (Block * b) [inline]
Definition at line 777 of file ast.h.
{ try_block_ = b; }
References try_block_.
try_block()
Block* v8::internal::TryStatement::try_block () const [inline]
Definition at line 776 of file ast.h.
{ return try_block_; }
References try_block_.
Referenced by v8::internal::SourceRangeAstVisitor::MaybeRemoveContinuationRangeOfAsyncReturn(), v8::internal::SourceRangeAstVisitor::VisitTryCatchStatement(), and v8::internal::SourceRangeAstVisitor::VisitTryFinallyStatement().
Member Data Documentation
try_block_
Block* v8::internal::TryStatement::try_block_ [private]
Definition at line 784 of file ast.h.
Referenced by set_try_block(), and try_block().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h