v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext Class Reference
Public Member Functions
AllocationSiteCreationContext (Isolate *isolate)
Handle< AllocationSite > EnterNewScope ()
void ExitScope (DirectHandle< AllocationSite > scope_site, DirectHandle< JSObject > object)
Static Public Attributes
static const bool kCopying = false
Additional Inherited Members
Detailed Description
Definition at line 251 of file runtime-literals.cc.
Constructor & Destructor Documentation
AllocationSiteCreationContext()
v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::AllocationSiteCreationContext (Isolate * isolate) [inline], [explicit]
Definition at line 253 of file runtime-literals.cc.
      : AllocationSiteContext(isolate) {}
Member Function Documentation
EnterNewScope()
Handle<AllocationSite> v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::EnterNewScope () [inline]
Definition at line 256 of file runtime-literals.cc.
                                         {
    Handle<AllocationSite> scope_site;
    if (top().is_null()) {
      // We are creating the top level AllocationSite as opposed to a nested
      // AllocationSite.
      InitializeTraversal(isolate()->factory()->NewAllocationSite(true));
      scope_site = Handle<AllocationSite>(*top(), isolate());
      if (v8_flags.trace_creation_allocation_sites) {
        PrintF("*** Creating top level %s AllocationSite %p\n", "Fat",
               reinterpret_cast<void*>(scope_site->ptr()));
      }
    } else {
      DCHECK(!current().is_null());
      scope_site = isolate()->factory()->NewAllocationSite(false);
      if (v8_flags.trace_creation_allocation_sites) {
        PrintF(
            "*** Creating nested %s AllocationSite (top, current, new) (%p, "
            "%p, "
            "%p)\n",
            "Slim", reinterpret_cast<void*>(top()->ptr()),
            reinterpret_cast<void*>(current()->ptr()),
            reinterpret_cast<void*>(scope_site->ptr()));
      }
      current()->set_nested_site(*scope_site);
      update_current_site(*scope_site);
    }
    DCHECK(!scope_site.is_null());
    return scope_site;
  }
References v8::internal::DCHECK(), v8::internal::HandleBase::is_null(), v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::CreateLiteral().
ExitScope()
void v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::ExitScope (DirectHandle< AllocationSite > scope_site, DirectHandle< JSObject > object) [inline]
Definition at line 285 of file runtime-literals.cc.
                                                {
    if (object.is_null()) return;
    scope_site->set_boilerplate(*object, kReleaseStore);
    if (v8_flags.trace_creation_allocation_sites) {
      bool top_level =
          !scope_site.is_null() && top().is_identical_to(scope_site);
      if (top_level) {
        PrintF("*** Setting AllocationSite %p transition_info %p\n",
               reinterpret_cast<void*>(scope_site->ptr()),
               reinterpret_cast<void*>(object->ptr()));
      } else {
        PrintF("*** Setting AllocationSite (%p, %p) transition_info %p\n",
               reinterpret_cast<void*>(top()->ptr()),
               reinterpret_cast<void*>(scope_site->ptr()),
               reinterpret_cast<void*>(object->ptr()));
      }
    }
  }
References v8::internal::DirectHandle< T >::is_null(), v8::kReleaseStore, v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::CreateLiteral().
Member Data Documentation
kCopying
const bool v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::kCopying = false [static]
Definition at line 304 of file runtime-literals.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/runtime/runtime-literals.cc