v8::internal::maglev::StoreMap Class Reference
#include <maglev-ir.h>
Public Types
enum class Kind { kInitializing
, kInlinedAllocation
, kTransitioning
 }
Public Member Functions
StoreMap (uint64_t bitfield, compiler::MapRef map, Kind kind)
Input & object_input ()
compiler::MapRef map () const
Kind kind () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void ClearUnstableNodeAspects (KnownNodeAspects &)
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kObjectIndex = 0
Private Types
using Base = FixedInputNodeT< 1, StoreMap >
using KindField = NextBitField< Kind, 3 >
Private Attributes
const compiler::MapRef map_
Additional Inherited Members
Detailed Description
Definition at line 9066 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreMap::Base = FixedInputNodeT<1, StoreMap> [private]
Definition at line 9067 of file maglev-ir.h.
KindField
using v8::internal::maglev::StoreMap::KindField = NextBitField<Kind, 3> [private]
Definition at line 9097 of file maglev-ir.h.
Member Enumeration Documentation
Kind
enum v8::internal::maglev::StoreMap::Kind [strong]
Enumerator
kInitializing
kInlinedAllocation
kTransitioning
Definition at line 9070 of file maglev-ir.h.
                  {
    kInitializing,
    kInlinedAllocation,
    kTransitioning,
  };
Constructor & Destructor Documentation
StoreMap()
v8::internal::maglev::StoreMap::StoreMap (uint64_t bitfield, compiler::MapRef map, Kind kind) [inline], [explicit]
Definition at line 9075 of file maglev-ir.h.
      : Base(bitfield | KindField::encode(kind)), map_(map) {}
Member Function Documentation
ClearUnstableNodeAspects()
void v8::internal::maglev::StoreMap::ClearUnstableNodeAspects (KnownNodeAspects & known_node_aspects)
Definition at line 8499 of file maglev-ir.cc.
                                                                            {
  switch (kind()) {
    case Kind::kInitializing:
    case Kind::kInlinedAllocation:
      return;
    case Kind::kTransitioning: {
      if (NodeInfo* node_info =
              known_node_aspects.TryGetInfoFor(object_input().node())) {
        if (node_info->possible_maps_are_known() &&
            node_info->possible_maps().size() == 1) {
          compiler::MapRef old_map = node_info->possible_maps().at(0);
          auto MaybeAliases = [&](compiler::MapRef map) -> bool {
            return map.equals(old_map);
          };
          known_node_aspects.ClearUnstableMapsIfAny(MaybeAliases);
          if (v8_flags.trace_maglev_graph_building) {
            std::cout << " ! StoreMap: Clearing unstable map "
                      << Brief(*old_map.object()) << std::endl;
          }
          return;
        }
      }
      break;
    }
  }
  // TODO(olivf): Only invalidate nodes with the same type.
  known_node_aspects.ClearUnstableMaps();
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << " ! StoreMap: Clearing unstable maps" << std::endl;
  }
}
References v8::internal::maglev::KnownNodeAspects::ClearUnstableMaps(), v8::internal::maglev::KnownNodeAspects::ClearUnstableMapsIfAny(), kind(), kInitializing, kInlinedAllocation, kTransitioning, map(), v8::internal::compiler::MapRef::object(), object_input(), v8::internal::maglev::KnownNodeAspects::TryGetInfoFor(), and v8::internal::v8_flags.
GenerateCode()
void v8::internal::maglev::StoreMap::GenerateCode (MaglevAssembler * , const ProcessingState &)
kind()
Kind v8::internal::maglev::StoreMap::kind () const [inline]
Definition at line 9087 of file maglev-ir.h.
{ return KindField::decode(bitfield()); }
Referenced by ClearUnstableNodeAspects(), and PrintParams().
map()
compiler::MapRef v8::internal::maglev::StoreMap::map () const [inline]
Definition at line 9086 of file maglev-ir.h.
{ return map_; }
Referenced by ClearUnstableNodeAspects(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::StoreMap::MaxCallStackArgs () const
object_input()
Input& v8::internal::maglev::StoreMap::object_input () [inline]
Definition at line 9084 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by ClearUnstableNodeAspects(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreMap::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8254 of file maglev-ir.cc.
                                                                      {
  os << "(" << *map_.object() << ", " << kind() << ")";
}
References kind(), map_, and v8::internal::compiler::MapRef::object().
SetValueLocationConstraints()
void v8::internal::maglev::StoreMap::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreMap::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 9081 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::StoreMap::kObjectIndex = 0 [static], [constexpr]
Definition at line 9083 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreMap::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanWrite() | OpProperties::DeferredCall()
Definition at line 9078 of file maglev-ir.h.
map_
const compiler::MapRef v8::internal::maglev::StoreMap::map_ [private]
Definition at line 9098 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc