v8::internal::Label Class Reference
#include <label.h>
Public Types
enum Distance { kNear
, kFar
 }
Public Member Functions
Label ()=default
Label (const Label &)=delete
Label & operator= (const Label &)=delete
Label (Label &&) V8_NOEXCEPT=default
Label & operator= (Label &&) V8_NOEXCEPT=default
void Unuse ()
void UnuseNear ()
bool is_bound () const
bool is_unused () const
bool is_linked () const
bool is_near_linked () const
int pos () const
int near_link_pos () const
Private Member Functions
void bind_to (int pos)
void link_to (int pos, Distance distance=kFar)
Private Attributes
int pos_ = 0
int near_link_pos_ = 0
Friends
class Assembler
class Displacement
class RegExpBytecodeGenerator
Detailed Description
Definition at line 19 of file label.h.
Member Enumeration Documentation
Distance
enum v8::internal::Label::Distance
Enumerator
kNear
kFar
Definition at line 21 of file label.h.
                {
    kNear, // near jump: 8 bit displacement (signed)
    kFar // far jump: 32 bit displacement (signed)
  };
Constructor & Destructor Documentation
Label() [1/3]
v8::internal::Label::Label () [default]
Label() [2/3]
v8::internal::Label::Label (const Label &) [delete]
Label() [3/3]
v8::internal::Label::Label (Label &&) [default]
Member Function Documentation
bind_to()
void v8::internal::Label::bind_to (int pos) [inline], [private]
Definition at line 91 of file label.h.
                        {
    pos_ = -pos - 1;
    DCHECK(is_bound());
  }
References v8::internal::DCHECK(), is_bound(), pos(), and pos_.
is_bound()
bool v8::internal::Label::is_bound () const [inline]
Definition at line 64 of file label.h.
{ return pos_ < 0; }
References pos_.
Referenced by v8::internal::RegExpCompiler::AddWork(), v8::internal::RegExpCompiler::Assemble(), bind_to(), v8::internal::MacroAssembler::BranchFalseF(), v8::internal::MacroAssembler::BranchTrueF(), v8::internal::Assembler::dd(), v8::internal::Assembler::emit_code_relative_offset(), v8::internal::maglev::MaglevCodeGenerator::EmitMetadata(), v8::internal::RegExpNode::LimitVersions(), v8::internal::MacroAssembler::NeedExtraInstructionsOrRegisterBranch(), v8::internal::Operand::Operand(), v8::internal::DotPrinterImpl::PrintAttributes(), v8::internal::RegExpMacroAssemblerRISCV::PushBacktrack(), and v8::internal::Assembler::SizeOfCodeGeneratedSince().
is_linked()
bool v8::internal::Label::is_linked () const [inline]
Definition at line 66 of file label.h.
{ return pos_ > 0; }
References pos_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::CutOutRange(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GenerateBranches(), v8::internal::RegExpMacroAssemblerRISCV::GetCode(), link_to(), v8::internal::Assembler::LinkAndGetBranchInstructionOffsetTo(), v8::internal::MacroAssembler::NeedExtraInstructionsOrRegisterBranch(), operator=(), and v8::internal::RegExpBytecodeGenerator::~RegExpBytecodeGenerator().
is_near_linked()
bool v8::internal::Label::is_near_linked () const [inline]
Definition at line 67 of file label.h.
{ return near_link_pos_ > 0; }
References near_link_pos_.
Referenced by link_to(), and operator=().
is_unused()
bool v8::internal::Label::is_unused () const [inline]
Definition at line 65 of file label.h.
{ return pos_ == 0 && near_link_pos_ == 0; }
References near_link_pos_, and pos_.
Referenced by v8::internal::maglev::MaglevAssembler::GetDeoptLabel().
link_to()
void v8::internal::Label::link_to (int pos, Distance distance = kFar) [inline], [private]
Definition at line 95 of file label.h.
                                                  {
    if (distance == kNear) {
      near_link_pos_ = pos + 1;
      DCHECK(is_near_linked());
    } else {
      pos_ = pos + 1;
      DCHECK(is_linked());
    }
  }
References v8::internal::DCHECK(), is_linked(), is_near_linked(), kNear, near_link_pos_, pos(), and pos_.
near_link_pos()
int v8::internal::Label::near_link_pos () const [inline]
Definition at line 77 of file label.h.
{ return near_link_pos_ - 1; }
References near_link_pos_.
operator=() [1/2]
Label& v8::internal::Label::operator= (const Label &) [delete]
operator=() [2/2]
Label& v8::internal::Label::operator= (Label &&) [default]
References v8::internal::DCHECK(), is_linked(), and is_near_linked().
pos()
int v8::internal::Label::pos () const [inline]
Definition at line 71 of file label.h.
                  {
    if (pos_ < 0) return -pos_ - 1;
    if (pos_ > 0) return pos_ - 1;
    UNREACHABLE();
  }
References pos_, and v8::internal::UNREACHABLE().
Referenced by bind_to(), v8::internal::Assembler::dd(), v8::internal::Assembler::emit_code_relative_offset(), v8::internal::maglev::MaglevCodeGenerator::EmitMetadata(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), v8::internal::RegExpMacroAssemblerRISCV::GetCode(), link_to(), v8::internal::MacroAssembler::NeedExtraInstructionsOrRegisterBranch(), v8::internal::DotPrinterImpl::PrintAttributes(), v8::internal::RegExpMacroAssemblerRISCV::PushBacktrack(), and v8::internal::Assembler::SizeOfCodeGeneratedSince().
Unuse()
void v8::internal::Label::Unuse () [inline]
Definition at line 61 of file label.h.
{ pos_ = 0; }
References pos_.
Referenced by v8::internal::RegExpBytecodeGenerator::~RegExpBytecodeGenerator(), and v8::internal::RegExpMacroAssemblerRISCV::~RegExpMacroAssemblerRISCV().
UnuseNear()
void v8::internal::Label::UnuseNear () [inline]
Definition at line 62 of file label.h.
{ near_link_pos_ = 0; }
References near_link_pos_.
Friends And Related Function Documentation
Assembler
friend class Assembler [friend]
Definition at line 105 of file label.h.
Displacement
friend class Displacement [friend]
Definition at line 106 of file label.h.
RegExpBytecodeGenerator
friend class RegExpBytecodeGenerator [friend]
Definition at line 107 of file label.h.
Member Data Documentation
near_link_pos_
int v8::internal::Label::near_link_pos_ = 0 [private]
Definition at line 89 of file label.h.
Referenced by is_near_linked(), is_unused(), link_to(), near_link_pos(), and UnuseNear().
pos_
int v8::internal::Label::pos_ = 0 [private]
Definition at line 86 of file label.h.
Referenced by bind_to(), is_bound(), is_linked(), is_unused(), link_to(), pos(), and Unuse().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/label.h