v8::internal::AssemblerRISCVZicond Class Reference
#include <extension-riscv-zicond.h>
Public Member Functions
void czero_eqz (Register rd, Register rs1, Register rs2)
void czero_nez (Register rd, Register rs1, Register rs2)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-zicond.h.
Member Function Documentation
czero_eqz()
void v8::internal::AssemblerRISCVZicond::czero_eqz (Register rd, Register rs1, Register rs2)
Definition at line 15 of file extension-riscv-zicond.cc.
                                                                            {
  GenInstrALU_rr(0b0000111, 0b101, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by v8::internal::MacroAssembler::LoadZeroIfConditionZero().
czero_nez()
void v8::internal::AssemblerRISCVZicond::czero_nez (Register rd, Register rs1, Register rs2)
Definition at line 19 of file extension-riscv-zicond.cc.
                                                                            {
  GenInstrALU_rr(0b0000111, 0b111, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by v8::internal::MacroAssembler::LoadZeroIfConditionNotZero().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-zicond.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-zicond.cc