v8::internal::ArrayBufferSweeper::SweepingState Class Reference
Classes
class SweepingJob
Public Member Functions
SweepingState (Heap *heap, ArrayBufferList young, ArrayBufferList old, SweepingType type, TreatAllYoungAsPromoted treat_all_young_as_promoted, uint64_t trace_id)
~SweepingState ()
void SetDone ()
bool IsDone () const
void MergeTo (ArrayBufferSweeper *sweeper)
void StartBackgroundSweeping ()
void FinishSweeping ()
Private Types
enum class Status { kInProgress
, kDone
 }
Private Attributes
std::atomic< Status > status_ {Status::kInProgress}
ArrayBufferList new_young_ {ArrayBufferList::Age::kYoung}
ArrayBufferList new_old_ {ArrayBufferList::Age::kOld}
size_t freed_bytes_ {0}
const uint64_t initial_young_bytes_ {0}
const uint64_t initial_old_bytes_ {0}
uint64_t young_bytes_accounted_ {0}
uint64_t old_bytes_accounted_ {0}
std::unique_ptr< JobHandle > job_handle_
Detailed Description
Definition at line 89 of file array-buffer-sweeper.cc.
Member Enumeration Documentation
Status
enum v8::internal::ArrayBufferSweeper::SweepingState::Status [strong], [private]
Enumerator
kInProgress
kDone
Definition at line 90 of file array-buffer-sweeper.cc.
{ kInProgress, kDone };
Constructor & Destructor Documentation
SweepingState()
v8::internal::ArrayBufferSweeper::SweepingState::SweepingState (Heap * heap, ArrayBufferList young, ArrayBufferList old, ArrayBufferSweeper::SweepingType type, ArrayBufferSweeper::TreatAllYoungAsPromoted treat_all_young_as_promoted, uint64_t trace_id)
Definition at line 238 of file array-buffer-sweeper.cc.
    : initial_young_bytes_(young.bytes_),
      initial_old_bytes_(old.bytes_),
      job_handle_(V8::GetCurrentPlatform()->CreateJob(
          TaskPriority::kUserVisible,
          std::make_unique<SweepingJob>(
              heap, *this, std::move(young), std::move(old), type,
              treat_all_young_as_promoted, trace_id))) {}
References v8::kUserVisible.
 SweepingState()
v8::internal::ArrayBufferSweeper::SweepingState::~SweepingState () [inline]
Definition at line 98 of file array-buffer-sweeper.cc.
{ DCHECK(job_handle_ && !job_handle_->IsValid()); }
References v8::internal::DCHECK(), and job_handle_.
Member Function Documentation
FinishSweeping()
void v8::internal::ArrayBufferSweeper::SweepingState::FinishSweeping () [inline]
Definition at line 131 of file array-buffer-sweeper.cc.
                        {
    DCHECK(job_handle_ && job_handle_->IsValid());
    job_handle_->Join();
  }
References v8::internal::DCHECK(), and job_handle_.
IsDone()
bool v8::internal::ArrayBufferSweeper::SweepingState::IsDone () const [inline]
Definition at line 101 of file array-buffer-sweeper.cc.
                      {
    return status_.load(std::memory_order_relaxed) == Status::kDone;
  }
References kDone, and status_.
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::GetMaxConcurrency(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Sweep().
MergeTo()
void v8::internal::ArrayBufferSweeper::SweepingState::MergeTo (ArrayBufferSweeper * sweeper) [inline]
Definition at line 105 of file array-buffer-sweeper.cc.
                                            {
    // the worker may see a difference between `young/old_bytes_accounted_` and
    // `initial_young/old_bytes_` due to concurrent main thread adjustments
    // (resizing).
    sweeper->young_bytes_adjustment_while_sweeping_ +=
        initial_young_bytes_ - young_bytes_accounted_;
    sweeper->old_bytes_adjustment_while_sweeping_ +=
        initial_old_bytes_ - old_bytes_accounted_;
    DCHECK_GE(new_young_.bytes_ +
                  sweeper->young_bytes_adjustment_while_sweeping_ +
                  sweeper->young_.bytes_,
              0);
    DCHECK_GE(new_old_.bytes_ + sweeper->old_bytes_adjustment_while_sweeping_ +
                  sweeper->old_.bytes_,
              0);
    sweeper->young_.Append(new_young_);
    sweeper->old_.Append(new_old_);
    // Apply pending adjustments from resizing and detaching.
    sweeper->young_.bytes_ +=
        std::exchange(sweeper->young_bytes_adjustment_while_sweeping_, 0);
    sweeper->old_.bytes_ +=
        std::exchange(sweeper->old_bytes_adjustment_while_sweeping_, 0);
    sweeper->DecrementExternalMemoryCounters(freed_bytes_);
  }
References v8::internal::ArrayBufferList::Append(), v8::internal::ArrayBufferList::bytes_, DCHECK_GE, v8::internal::ArrayBufferSweeper::DecrementExternalMemoryCounters(), freed_bytes_, initial_old_bytes_, initial_young_bytes_, new_old_, new_young_, v8::internal::ArrayBufferSweeper::old_, old_bytes_accounted_, v8::internal::ArrayBufferSweeper::old_bytes_adjustment_while_sweeping_, v8::internal::ArrayBufferSweeper::young_, young_bytes_accounted_, and v8::internal::ArrayBufferSweeper::young_bytes_adjustment_while_sweeping_.
SetDone()
void v8::internal::ArrayBufferSweeper::SweepingState::SetDone () [inline]
Definition at line 100 of file array-buffer-sweeper.cc.
{ status_.store(Status::kDone, std::memory_order_relaxed); }
References kDone, and status_.
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Sweep().
StartBackgroundSweeping()
void v8::internal::ArrayBufferSweeper::SweepingState::StartBackgroundSweeping () [inline]
Definition at line 130 of file array-buffer-sweeper.cc.
{ job_handle_->NotifyConcurrencyIncrease(); }
References job_handle_.
Member Data Documentation
freed_bytes_
size_t v8::internal::ArrayBufferSweeper::SweepingState::freed_bytes_ {0} [private]
Definition at line 142 of file array-buffer-sweeper.cc.
Referenced by MergeTo().
initial_old_bytes_
const uint64_t v8::internal::ArrayBufferSweeper::SweepingState::initial_old_bytes_ {0} [private]
Definition at line 144 of file array-buffer-sweeper.cc.
Referenced by MergeTo().
initial_young_bytes_
const uint64_t v8::internal::ArrayBufferSweeper::SweepingState::initial_young_bytes_ {0} [private]
Definition at line 143 of file array-buffer-sweeper.cc.
Referenced by MergeTo().
job_handle_
std::unique_ptr<JobHandle> v8::internal::ArrayBufferSweeper::SweepingState::job_handle_ [private]
Definition at line 149 of file array-buffer-sweeper.cc.
Referenced by FinishSweeping(), StartBackgroundSweeping(), and ~SweepingState().
new_old_
ArrayBufferList v8::internal::ArrayBufferSweeper::SweepingState::new_old_ {ArrayBufferList::Age::kOld} [private]
Definition at line 141 of file array-buffer-sweeper.cc.
Referenced by MergeTo().
new_young_
ArrayBufferList v8::internal::ArrayBufferSweeper::SweepingState::new_young_ {ArrayBufferList::Age::kYoung} [private]
Definition at line 140 of file array-buffer-sweeper.cc.
Referenced by MergeTo().
old_bytes_accounted_
uint64_t v8::internal::ArrayBufferSweeper::SweepingState::old_bytes_accounted_ {0} [private]
Definition at line 148 of file array-buffer-sweeper.cc.
Referenced by MergeTo().
status_
std::atomic<Status> v8::internal::ArrayBufferSweeper::SweepingState::status_ {Status::kInProgress} [private]
Definition at line 139 of file array-buffer-sweeper.cc.
Referenced by IsDone(), and SetDone().
young_bytes_accounted_
uint64_t v8::internal::ArrayBufferSweeper::SweepingState::young_bytes_accounted_ {0} [private]
Definition at line 147 of file array-buffer-sweeper.cc.
Referenced by MergeTo().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/array-buffer-sweeper.cc