v8::internal::wasm::AsmJsOffsetInformation Class Reference
#include <wasm-module.h>
Public Member Functions
AsmJsOffsetInformation (base::Vector< const uint8_t > encoded_offsets)
~AsmJsOffsetInformation ()
int GetSourcePosition (int func_index, int byte_offset, bool is_at_number_conversion)
std::pair< int, int > GetFunctionOffsets (int func_index)
Private Member Functions
void EnsureDecodedOffsets ()
Private Attributes
base::Mutex mutex_
base::OwnedVector< const uint8_t > encoded_offsets_
std::unique_ptr< AsmJsOffsets > decoded_offsets_
Detailed Description
Definition at line 397 of file wasm-module.h.
Constructor & Destructor Documentation
AsmJsOffsetInformation()
v8::internal::wasm::AsmJsOffsetInformation::AsmJsOffsetInformation (base::Vector< const uint8_t > encoded_offsets) [explicit]
Definition at line 159 of file wasm-module.cc.
    : encoded_offsets_(base::OwnedCopyOf(encoded_offsets)) {}
 AsmJsOffsetInformation()
v8::internal::wasm::AsmJsOffsetInformation::~AsmJsOffsetInformation () [default]
Member Function Documentation
EnsureDecodedOffsets()
void v8::internal::wasm::AsmJsOffsetInformation::EnsureDecodedOffsets () [private]
Definition at line 205 of file wasm-module.cc.
                                                  {
  base::MutexGuard mutex_guard(&mutex_);
  DCHECK_EQ(encoded_offsets_ == nullptr, decoded_offsets_ != nullptr);
  if (decoded_offsets_) return;
  AsmJsOffsetsResult result =
      wasm::DecodeAsmJsOffsets(encoded_offsets_.as_vector());
  decoded_offsets_ = std::make_unique<AsmJsOffsets>(std::move(result).value());
  encoded_offsets_.ReleaseData();
}
References v8::base::OwnedVector< T >::as_vector(), DCHECK_EQ, v8::internal::wasm::DecodeAsmJsOffsets(), decoded_offsets_, encoded_offsets_, mutex_, v8::base::OwnedVector< T >::ReleaseData(), v8::base::internal::result, and v8::internal::value.
Referenced by GetFunctionOffsets(), and GetSourcePosition().
GetFunctionOffsets()
std::pair< int, int > v8::internal::wasm::AsmJsOffsetInformation::GetFunctionOffsets (int func_index)
Definition at line 193 of file wasm-module.cc.
                             {
  EnsureDecodedOffsets();
  DCHECK_LE(0, declared_func_index);
  DCHECK_GT(decoded_offsets_->functions.size(), declared_func_index);
  AsmJsOffsetFunctionEntries& function_info =
      decoded_offsets_->functions[declared_func_index];
  return {function_info.start_offset, function_info.end_offset};
}
References DCHECK_GT, DCHECK_LE, decoded_offsets_, v8::internal::wasm::AsmJsOffsetFunctionEntries::end_offset, EnsureDecodedOffsets(), and v8::internal::wasm::AsmJsOffsetFunctionEntries::start_offset.
GetSourcePosition()
int v8::internal::wasm::AsmJsOffsetInformation::GetSourcePosition (int func_index, int byte_offset, bool is_at_number_conversion)
Definition at line 165 of file wasm-module.cc.
                                                                            {
  EnsureDecodedOffsets();
  DCHECK_LE(0, declared_func_index);
  DCHECK_GT(decoded_offsets_->functions.size(), declared_func_index);
  std::vector<AsmJsOffsetEntry>& function_offsets =
      decoded_offsets_->functions[declared_func_index].entries;
  auto byte_offset_less = [](const AsmJsOffsetEntry& a,
                             const AsmJsOffsetEntry& b) {
    return a.byte_offset < b.byte_offset;
  };
  SLOW_DCHECK(std::is_sorted(function_offsets.begin(), function_offsets.end(),
                             byte_offset_less));
  // If there are no positions recorded, map offset 0 (for function entry) to
  // position 0.
  if (function_offsets.empty() && byte_offset == 0) return 0;
  auto it =
      std::lower_bound(function_offsets.begin(), function_offsets.end(),
                       AsmJsOffsetEntry{byte_offset, 0, 0}, byte_offset_less);
  DCHECK_NE(function_offsets.end(), it);
  DCHECK_EQ(byte_offset, it->byte_offset);
  return is_at_number_conversion ? it->source_position_number_conversion
                                 : it->source_position_call;
}
References v8::internal::wasm::AsmJsOffsetEntry::byte_offset, DCHECK_EQ, DCHECK_GT, DCHECK_LE, DCHECK_NE, decoded_offsets_, EnsureDecodedOffsets(), and SLOW_DCHECK.
Member Data Documentation
decoded_offsets_
std::unique_ptr<AsmJsOffsets> v8::internal::wasm::AsmJsOffsetInformation::decoded_offsets_ [private]
Definition at line 422 of file wasm-module.h.
Referenced by EnsureDecodedOffsets(), GetFunctionOffsets(), and GetSourcePosition().
encoded_offsets_
base::OwnedVector<const uint8_t> v8::internal::wasm::AsmJsOffsetInformation::encoded_offsets_ [private]
Definition at line 419 of file wasm-module.h.
Referenced by EnsureDecodedOffsets().
mutex_
base::Mutex v8::internal::wasm::AsmJsOffsetInformation::mutex_ [mutable], [private]
Definition at line 416 of file wasm-module.h.
Referenced by EnsureDecodedOffsets().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-module.h
/mnt/V8SourceCode/src/wasm/wasm-module.cc