v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob Class Reference
Public Member Functions
SweepingJob (Heap *heap, SweepingState &state, ArrayBufferList young, ArrayBufferList old, SweepingType type, TreatAllYoungAsPromoted treat_all_young_as_promoted, uint64_t trace_id)
~SweepingJob () override=default
SweepingJob (const SweepingJob &)=delete
SweepingJob & operator= (const SweepingJob &)=delete
void Run (JobDelegate *delegate) final
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Member Functions
void Sweep (JobDelegate *delegate)
bool SweepYoung (JobDelegate *delegate)
bool SweepFull (JobDelegate *delegate)
bool SweepListFull (JobDelegate *delegate, ArrayBufferList &list, ArrayBufferExtension::Age age)
Private Attributes
Heap *const heap_
SweepingState & state_
ArrayBufferList young_ {ArrayBufferList::Age::kYoung}
ArrayBufferList old_ {ArrayBufferList::Age::kOld}
const SweepingType type_
const TreatAllYoungAsPromoted treat_all_young_as_promoted_
const uint64_t trace_id_
Sweeper::LocalSweeper local_sweeper_
Detailed Description
Definition at line 152 of file array-buffer-sweeper.cc.
Constructor & Destructor Documentation
SweepingJob() [1/2]
v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepingJob (Heap * heap, SweepingState & state, ArrayBufferList young, ArrayBufferList old, SweepingType type, TreatAllYoungAsPromoted treat_all_young_as_promoted, uint64_t trace_id) [inline]
Definition at line 154 of file array-buffer-sweeper.cc.
      : heap_(heap),
        state_(state),
        young_(young),
        old_(old),
        type_(type),
        treat_all_young_as_promoted_(treat_all_young_as_promoted),
        trace_id_(trace_id),
        local_sweeper_(heap_->sweeper()) {}
 SweepingJob()
v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::~SweepingJob () [override], [default]
SweepingJob() [2/2]
v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepingJob (const SweepingJob &) [delete]
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 174 of file array-buffer-sweeper.cc.
                                                               {
    return state_.IsDone() ? 0 : 1;
  }
References v8::internal::ArrayBufferSweeper::SweepingState::IsDone(), and state_.
operator=()
SweepingJob& v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::operator= (const SweepingJob &) [delete]
Run()
void v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Run (JobDelegate * delegate) [final], [virtual]
Implements v8::JobTask.
Definition at line 197 of file array-buffer-sweeper.cc.
                           {
  // Set the current isolate such that trusted pointer tables etc are
  // available and the cage base is set correctly for multi-cage mode.
  SetCurrentIsolateScope isolate_scope(heap_->isolate());
  const ThreadKind thread_kind =
      delegate->IsJoiningThread() ? ThreadKind::kMain : ThreadKind::kBackground;
  if (treat_all_young_as_promoted_ == TreatAllYoungAsPromoted::kNo) {
    // Waiting for promoted page iteration is only needed when not all young
    // array buffers are promoted.
    GCTracer::Scope::ScopeId scope_id =
        type_ == SweepingType::kYoung
            ? thread_kind == ThreadKind::kMain
                  ? GCTracer::Scope::MINOR_MS_SWEEP
                  : GCTracer::Scope::MINOR_MS_BACKGROUND_SWEEPING
        : thread_kind == ThreadKind::kMain
            ? GCTracer::Scope::MC_SWEEP
            : GCTracer::Scope::MC_BACKGROUND_SWEEPING;
    TRACE_GC_EPOCH_WITH_FLOW(
        heap_->tracer(), scope_id, thread_kind,
        heap_->sweeper()->GetTraceIdForFlowEvent(scope_id),
        TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
    const bool finished =
        local_sweeper_.ContributeAndWaitForPromotedPagesIteration(delegate);
    DCHECK_IMPLIES(delegate->IsJoiningThread(), finished);
    if (!finished) return;
    DCHECK(!heap_->sweeper()->IsIteratingPromotedPages());
  }
  GCTracer::Scope::ScopeId scope_id =
      type_ == SweepingType::kYoung
          ? thread_kind == ThreadKind::kMain
                ? GCTracer::Scope::YOUNG_ARRAY_BUFFER_SWEEP
                : GCTracer::Scope::BACKGROUND_YOUNG_ARRAY_BUFFER_SWEEP
      : thread_kind == ThreadKind::kMain
          ? GCTracer::Scope::FULL_ARRAY_BUFFER_SWEEP
          : GCTracer::Scope::BACKGROUND_FULL_ARRAY_BUFFER_SWEEP;
  TRACE_GC_EPOCH_WITH_FLOW(heap_->tracer(), scope_id, thread_kind, trace_id_,
                           TRACE_EVENT_FLAG_FLOW_IN);
  Sweep(delegate);
}
References v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIteration(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Sweeper::GetTraceIdForFlowEvent(), heap_, v8::internal::Sweeper::IsIteratingPromotedPages(), v8::JobDelegate::IsJoiningThread(), v8::internal::Heap::isolate(), v8::internal::kBackground, v8::internal::kMain, v8::internal::ArrayBufferSweeper::kNo, v8::internal::ArrayBufferSweeper::kYoung, local_sweeper_, Sweep(), v8::internal::Heap::sweeper(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, trace_id_, v8::internal::Heap::tracer(), treat_all_young_as_promoted_, and type_.
Sweep()
void v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Sweep (JobDelegate * delegate) [private]
Definition at line 445 of file array-buffer-sweeper.cc.
                           {
  CHECK(!state_.IsDone());
  bool is_finished;
  switch (type_) {
    case SweepingType::kYoung:
      is_finished = SweepYoung(delegate);
      break;
    case SweepingType::kFull:
      is_finished = SweepFull(delegate);
      break;
  }
  if (is_finished) {
    state_.SetDone();
  } else {
    TRACE_GC_NOTE("ArrayBufferSweeper Preempted");
  }
}
References CHECK, v8::internal::ArrayBufferSweeper::SweepingState::IsDone(), v8::internal::ArrayBufferSweeper::kFull, v8::internal::ArrayBufferSweeper::kYoung, v8::internal::ArrayBufferSweeper::SweepingState::SetDone(), state_, SweepFull(), SweepYoung(), TRACE_GC_NOTE, and type_.
Referenced by Run().
SweepFull()
bool v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepFull (JobDelegate * delegate) [private]
Definition at line 464 of file array-buffer-sweeper.cc.
                           {
  DCHECK_EQ(SweepingType::kFull, type_);
  if (!SweepListFull(delegate, young_, ArrayBufferExtension::Age::kYoung))
    return false;
  return SweepListFull(delegate, old_, ArrayBufferExtension::Age::kOld);
}
References DCHECK_EQ, v8::internal::ArrayBufferSweeper::kFull, v8::internal::ArrayBufferExtension::kOld, v8::internal::ArrayBufferExtension::kYoung, v8::internal::ArrayBufferSweeper::old_, and v8::internal::ArrayBufferSweeper::young_.
Referenced by Sweep().
SweepListFull()
bool v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull (JobDelegate * delegate, ArrayBufferList & list, ArrayBufferExtension::Age age) [private]
Definition at line 472 of file array-buffer-sweeper.cc.
                                 {
  static constexpr size_t kYieldCheckInterval = 256;
  static_assert(base::bits::IsPowerOfTwo(kYieldCheckInterval),
                "kYieldCheckInterval must be power of 2");
  ArrayBufferExtension* current = list.head_;
  ArrayBufferList& new_old = state_.new_old_;
  size_t freed_bytes = 0;
  size_t accounted_bytes = 0;
  size_t swept_extensions = 0;
  while (current) {
    DCHECK_EQ(list.age_, current->age());
    if ((swept_extensions++ & (kYieldCheckInterval - 1)) == 0) {
      if (delegate->ShouldYield()) break;
    }
    ArrayBufferExtension* next = current->next();
    if (!current->IsMarked()) {
      freed_bytes += current->accounting_length();
      FinalizeAndDelete(current);
    } else {
      current->Unmark();
      accounted_bytes += new_old.Append(current);
    }
    current = next;
  }
  state_.freed_bytes_ += freed_bytes;
  if (age == ArrayBufferExtension::Age::kYoung) {
    state_.young_bytes_accounted_ += (freed_bytes + accounted_bytes);
  } else {
    state_.old_bytes_accounted_ += (freed_bytes + accounted_bytes);
  }
  list.head_ = current;
  return !current;
}
References v8::internal::ArrayBufferExtension::accounting_length(), v8::internal::ArrayBufferExtension::age(), v8::internal::ArrayBufferList::age_, v8::internal::ArrayBufferList::Append(), DCHECK_EQ, v8::internal::ArrayBufferSweeper::FinalizeAndDelete(), v8::internal::ArrayBufferList::head_, v8::internal::ArrayBufferExtension::IsMarked(), v8::base::bits::IsPowerOfTwo(), v8::internal::ArrayBufferExtension::kYoung, v8::internal::ArrayBufferExtension::next(), v8::JobDelegate::ShouldYield(), v8::internal::ArrayBufferSweeper::state_, and v8::internal::ArrayBufferExtension::Unmark().
SweepYoung()
bool v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung (JobDelegate * delegate) [private]
Definition at line 515 of file array-buffer-sweeper.cc.
                           {
  static constexpr size_t kYieldCheckInterval = 256;
  static_assert(base::bits::IsPowerOfTwo(kYieldCheckInterval),
                "kYieldCheckInterval must be power of 2");
  DCHECK_EQ(SweepingType::kYoung, type_);
  ArrayBufferExtension* current = young_.head_;
  ArrayBufferList& new_old = state_.new_old_;
  ArrayBufferList& new_young = state_.new_young_;
  size_t freed_bytes = 0;
  size_t accounted_bytes = 0;
  size_t swept_extensions = 0;
  while (current) {
    DCHECK_EQ(ArrayBufferExtension::Age::kYoung, current->age());
    if ((swept_extensions++ & (kYieldCheckInterval - 1)) == 0) {
      if (delegate->ShouldYield()) break;
    }
    ArrayBufferExtension* next = current->next();
    if (!current->IsYoungMarked()) {
      const size_t bytes = current->accounting_length();
      FinalizeAndDelete(current);
      if (bytes) freed_bytes += bytes;
    } else {
      if ((treat_all_young_as_promoted_ == TreatAllYoungAsPromoted::kYes) ||
          current->IsYoungPromoted()) {
        current->YoungUnmark();
        accounted_bytes += new_old.Append(current);
      } else {
        current->YoungUnmark();
        accounted_bytes += new_young.Append(current);
      }
    }
    current = next;
  }
  state_.freed_bytes_ += freed_bytes;
  // Update young/old_bytes_accounted_; the worker may see a difference between
  // this and `initial_young/old_bytes_` due to concurrent main thread
  // adjustments.
  state_.young_bytes_accounted_ += (freed_bytes + accounted_bytes);
  young_.head_ = current;
  return !current;
}
References v8::internal::ArrayBufferExtension::accounting_length(), v8::internal::ArrayBufferExtension::age(), v8::internal::ArrayBufferList::Append(), DCHECK_EQ, v8::internal::ArrayBufferSweeper::FinalizeAndDelete(), v8::internal::ArrayBufferList::head_, v8::base::bits::IsPowerOfTwo(), v8::internal::ArrayBufferExtension::IsYoungMarked(), v8::internal::ArrayBufferExtension::IsYoungPromoted(), v8::internal::ArrayBufferSweeper::kYes, v8::internal::ArrayBufferSweeper::kYoung, v8::internal::ArrayBufferExtension::kYoung, v8::internal::ArrayBufferExtension::next(), v8::JobDelegate::ShouldYield(), v8::internal::ArrayBufferSweeper::state_, v8::internal::ArrayBufferSweeper::young_, and v8::internal::ArrayBufferExtension::YoungUnmark().
Referenced by Sweep().
Member Data Documentation
heap_
Heap* const v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::heap_ [private]
Definition at line 187 of file array-buffer-sweeper.cc.
Referenced by Run().
local_sweeper_
Sweeper::LocalSweeper v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::local_sweeper_ [private]
Definition at line 194 of file array-buffer-sweeper.cc.
Referenced by Run().
old_
ArrayBufferList v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::old_ {ArrayBufferList::Age::kOld} [private]
Definition at line 190 of file array-buffer-sweeper.cc.
state_
SweepingState& v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::state_ [private]
Definition at line 188 of file array-buffer-sweeper.cc.
Referenced by GetMaxConcurrency(), and Sweep().
trace_id_
const uint64_t v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::trace_id_ [private]
Definition at line 193 of file array-buffer-sweeper.cc.
Referenced by Run().
treat_all_young_as_promoted_
const TreatAllYoungAsPromoted v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::treat_all_young_as_promoted_ [private]
Definition at line 192 of file array-buffer-sweeper.cc.
Referenced by Run().
type_
const SweepingType v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::type_ [private]
Definition at line 191 of file array-buffer-sweeper.cc.
Referenced by Run(), and Sweep().
young_
ArrayBufferList v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::young_ {ArrayBufferList::Age::kYoung} [private]
Definition at line 189 of file array-buffer-sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/array-buffer-sweeper.cc