v8::internal::compiler::CFGBuilder Class Reference
Public Member Functions
CFGBuilder (Zone *zone, Scheduler *scheduler)
void Run ()
void Run (BasicBlock *block, Node *exit)
Private Member Functions
void FixNode (BasicBlock *block, Node *node)
void Queue (Node *node)
void BuildBlocks (Node *node)
void ConnectBlocks (Node *node)
BasicBlock * BuildBlockForNode (Node *node)
void BuildBlocksForSuccessors (Node *node)
void CollectSuccessorBlocks (Node *node, BasicBlock **successor_blocks, size_t successor_cnt)
BasicBlock * FindPredecessorBlock (Node *node)
void ConnectCall (Node *call)
void ConnectBranch (Node *branch)
void ConnectSwitch (Node *sw)
void ConnectMerge (Node *merge)
void ConnectTailCall (Node *call)
void ConnectReturn (Node *ret)
void ConnectDeoptimize (Node *deopt)
void ConnectThrow (Node *thr)
void TraceConnect (Node *node, BasicBlock *block, BasicBlock *succ)
bool IsFinalMerge (Node *node)
bool IsSingleEntrySingleExitRegion (Node *entry, Node *exit) const
void ResetDataStructures ()
Private Attributes
Zone * zone_
Scheduler * scheduler_
Schedule * schedule_
NodeMarker< bool > queued_
ZoneQueue< Node * > queue_
NodeVector control_
Node * component_entry_
BasicBlock * component_start_
BasicBlock * component_end_
Friends
class ScheduleLateNodeVisitor
class Scheduler
Detailed Description
Definition at line 239 of file scheduler.cc.
Constructor & Destructor Documentation
CFGBuilder()
v8::internal::compiler::CFGBuilder::CFGBuilder (Zone * zone, Scheduler * scheduler) [inline]
Definition at line 241 of file scheduler.cc.
      : zone_(zone),
        scheduler_(scheduler),
        schedule_(scheduler->schedule_),
        queued_(scheduler->graph_, 2),
        queue_(zone),
        control_(zone),
        component_entry_(nullptr),
        component_start_(nullptr),
        component_end_(nullptr) {}
Member Function Documentation
BuildBlockForNode()
BasicBlock* v8::internal::compiler::CFGBuilder::BuildBlockForNode (Node * node) [inline], [private]
Definition at line 414 of file scheduler.cc.
                                            {
    BasicBlock* block = schedule_->block(node);
    if (block == nullptr) {
      block = schedule_->NewBasicBlock();
      TRACE("Create block id:%d for #%d:%s\n", block->id().ToInt(), node->id(),
            node->op()->mnemonic());
      FixNode(block, node);
    }
    return block;
  }
References v8::internal::compiler::Schedule::block(), FixNode(), v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Schedule::NewBasicBlock(), v8::internal::compiler::Node::op(), schedule_, v8::internal::compiler::BasicBlock::Id::ToInt(), and v8::internal::TRACE().
Referenced by BuildBlocks(), and BuildBlocksForSuccessors().
BuildBlocks()
void v8::internal::compiler::CFGBuilder::BuildBlocks (Node * node) [inline], [private]
Definition at line 330 of file scheduler.cc.
                               {
    switch (node->opcode()) {
      case IrOpcode::kEnd:
        FixNode(schedule_->end(), node);
        break;
      case IrOpcode::kStart:
        FixNode(schedule_->start(), node);
        break;
      case IrOpcode::kLoop:
      case IrOpcode::kMerge:
        BuildBlockForNode(node);
        break;
      case IrOpcode::kTerminate: {
        // Put Terminate in the loop to which it refers.
        Node* loop = NodeProperties::GetControlInput(node);
        BasicBlock* block = BuildBlockForNode(loop);
        FixNode(block, node);
        break;
      }
      case IrOpcode::kBranch:
      case IrOpcode::kSwitch:
        BuildBlocksForSuccessors(node);
        break;
#define BUILD_BLOCK_JS_CASE(Name, ...) case IrOpcode::k##Name:
        JS_OP_LIST(BUILD_BLOCK_JS_CASE)
// JS opcodes are just like calls => fall through.
#undef BUILD_BLOCK_JS_CASE
      case IrOpcode::kCall:
      case IrOpcode::kFastApiCall:
        if (NodeProperties::IsExceptionalCall(node)) {
          BuildBlocksForSuccessors(node);
        }
        break;
      default:
        break;
    }
  }
References BUILD_BLOCK_JS_CASE, BuildBlockForNode(), BuildBlocksForSuccessors(), v8::internal::compiler::Schedule::end(), FixNode(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), JS_OP_LIST, v8::internal::compiler::turboshaft::kBranch, v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::kStart, v8::internal::wasm::kSwitch, v8::internal::compiler::Node::opcode(), schedule_, and v8::internal::compiler::Schedule::start().
Referenced by Queue().
BuildBlocksForSuccessors()
void v8::internal::compiler::CFGBuilder::BuildBlocksForSuccessors (Node * node) [inline], [private]
Definition at line 425 of file scheduler.cc.
                                            {
    size_t const successor_cnt = node->op()->ControlOutputCount();
    Node** successors = zone_->AllocateArray<Node*>(successor_cnt);
    NodeProperties::CollectControlProjections(node, successors, successor_cnt);
    for (size_t index = 0; index < successor_cnt; ++index) {
      BuildBlockForNode(successors[index]);
    }
  }
References v8::internal::Zone::AllocateArray(), BuildBlockForNode(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::index, v8::internal::compiler::Node::op(), and zone_.
Referenced by BuildBlocks().
CollectSuccessorBlocks()
void v8::internal::compiler::CFGBuilder::CollectSuccessorBlocks (Node * node, BasicBlock ** successor_blocks, size_t successor_cnt) [inline], [private]
Definition at line 434 of file scheduler.cc.
                                                    {
    Node** successors = reinterpret_cast<Node**>(successor_blocks);
    NodeProperties::CollectControlProjections(node, successors, successor_cnt);
    for (size_t index = 0; index < successor_cnt; ++index) {
      successor_blocks[index] = schedule_->block(successors[index]);
    }
  }
References v8::internal::compiler::Schedule::block(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::index, and schedule_.
Referenced by ConnectBranch(), ConnectCall(), and ConnectSwitch().
ConnectBlocks()
void v8::internal::compiler::CFGBuilder::ConnectBlocks (Node * node) [inline], [private]
Definition at line 368 of file scheduler.cc.
                                 {
    switch (node->opcode()) {
      case IrOpcode::kLoop:
      case IrOpcode::kMerge:
        ConnectMerge(node);
        break;
      case IrOpcode::kBranch:
        scheduler_->UpdatePlacement(node, Scheduler::kFixed);
        ConnectBranch(node);
        break;
      case IrOpcode::kSwitch:
        scheduler_->UpdatePlacement(node, Scheduler::kFixed);
        ConnectSwitch(node);
        break;
      case IrOpcode::kDeoptimize:
        scheduler_->UpdatePlacement(node, Scheduler::kFixed);
        ConnectDeoptimize(node);
        break;
      case IrOpcode::kTailCall:
        scheduler_->UpdatePlacement(node, Scheduler::kFixed);
        ConnectTailCall(node);
        break;
      case IrOpcode::kReturn:
        scheduler_->UpdatePlacement(node, Scheduler::kFixed);
        ConnectReturn(node);
        break;
      case IrOpcode::kThrow:
        scheduler_->UpdatePlacement(node, Scheduler::kFixed);
        ConnectThrow(node);
        break;
#define CONNECT_BLOCK_JS_CASE(Name, ...) case IrOpcode::k##Name:
        JS_OP_LIST(CONNECT_BLOCK_JS_CASE)
// JS opcodes are just like calls => fall through.
#undef CONNECT_BLOCK_JS_CASE
      case IrOpcode::kCall:
      case IrOpcode::kFastApiCall:
        if (NodeProperties::IsExceptionalCall(node)) {
          scheduler_->UpdatePlacement(node, Scheduler::kFixed);
          ConnectCall(node);
        }
        break;
      default:
        break;
    }
  }
References CONNECT_BLOCK_JS_CASE, ConnectBranch(), ConnectCall(), ConnectDeoptimize(), ConnectMerge(), ConnectReturn(), ConnectSwitch(), ConnectTailCall(), ConnectThrow(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), JS_OP_LIST, v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::Scheduler::kFixed, v8::internal::wasm::kSwitch, v8::internal::wasm::kTailCall, v8::internal::compiler::Node::opcode(), scheduler_, and v8::internal::compiler::Scheduler::UpdatePlacement().
Referenced by Run().
ConnectBranch()
void v8::internal::compiler::CFGBuilder::ConnectBranch (Node * branch) [inline], [private]
Definition at line 468 of file scheduler.cc.
                                   {
    BasicBlock* successor_blocks[2];
    CollectSuccessorBlocks(branch, successor_blocks,
                           arraysize(successor_blocks));
    BranchHint hint_from_profile = BranchHint::kNone;
    if (const ProfileDataFromFile* profile_data = scheduler_->profile_data()) {
      hint_from_profile =
          profile_data->GetHint(successor_blocks[0]->id().ToSize(),
                                successor_blocks[1]->id().ToSize());
    }
    // Consider branch hints.
    switch (hint_from_profile) {
      case BranchHint::kNone:
        switch (BranchHintOf(branch->op())) {
          case BranchHint::kNone:
            break;
          case BranchHint::kTrue:
            successor_blocks[1]->set_deferred(true);
            break;
          case BranchHint::kFalse:
            successor_blocks[0]->set_deferred(true);
            break;
        }
        break;
      case BranchHint::kTrue:
        successor_blocks[1]->set_deferred(true);
        break;
      case BranchHint::kFalse:
        successor_blocks[0]->set_deferred(true);
        break;
    }
    if (branch == component_entry_) {
      TraceConnect(branch, component_start_, successor_blocks[0]);
      TraceConnect(branch, component_start_, successor_blocks[1]);
      schedule_->InsertBranch(component_start_, component_end_, branch,
                              successor_blocks[0], successor_blocks[1]);
    } else {
      Node* branch_control = NodeProperties::GetControlInput(branch);
      BasicBlock* branch_block = FindPredecessorBlock(branch_control);
      TraceConnect(branch, branch_block, successor_blocks[0]);
      TraceConnect(branch, branch_block, successor_blocks[1]);
      schedule_->AddBranch(branch_block, branch, successor_blocks[0],
                           successor_blocks[1]);
    }
  }
References v8::internal::compiler::Schedule::AddBranch(), arraysize, v8::internal::compiler::BranchHintOf(), CollectSuccessorBlocks(), component_end_, component_entry_, component_start_, FindPredecessorBlock(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Schedule::InsertBranch(), v8::internal::kFalse, v8::internal::kNone, v8::internal::kTrue, v8::internal::compiler::Node::op(), v8::internal::compiler::Scheduler::profile_data(), schedule_, scheduler_, v8::internal::compiler::BasicBlock::set_deferred(), and TraceConnect().
Referenced by ConnectBlocks().
ConnectCall()
void v8::internal::compiler::CFGBuilder::ConnectCall (Node * call) [inline], [private]
Definition at line 453 of file scheduler.cc.
                               {
    BasicBlock* successor_blocks[2];
    CollectSuccessorBlocks(call, successor_blocks, arraysize(successor_blocks));
    // Consider the exception continuation to be deferred.
    successor_blocks[1]->set_deferred(true);
    Node* call_control = NodeProperties::GetControlInput(call);
    BasicBlock* call_block = FindPredecessorBlock(call_control);
    TraceConnect(call, call_block, successor_blocks[0]);
    TraceConnect(call, call_block, successor_blocks[1]);
    schedule_->AddCall(call_block, call, successor_blocks[0],
                       successor_blocks[1]);
  }
References v8::internal::compiler::Schedule::AddCall(), arraysize, CollectSuccessorBlocks(), FindPredecessorBlock(), v8::internal::compiler::NodeProperties::GetControlInput(), schedule_, v8::internal::compiler::BasicBlock::set_deferred(), and TraceConnect().
Referenced by ConnectBlocks().
ConnectDeoptimize()
void v8::internal::compiler::CFGBuilder::ConnectDeoptimize (Node * deopt) [inline], [private]
Definition at line 574 of file scheduler.cc.
                                      {
    Node* deoptimize_control = NodeProperties::GetControlInput(deopt);
    BasicBlock* deoptimize_block = FindPredecessorBlock(deoptimize_control);
    TraceConnect(deopt, deoptimize_block, nullptr);
    schedule_->AddDeoptimize(deoptimize_block, deopt);
  }
References v8::internal::compiler::Schedule::AddDeoptimize(), FindPredecessorBlock(), v8::internal::compiler::NodeProperties::GetControlInput(), schedule_, and TraceConnect().
Referenced by ConnectBlocks().
ConnectMerge()
void v8::internal::compiler::CFGBuilder::ConnectMerge (Node * merge) [inline], [private]
Definition at line 545 of file scheduler.cc.
                                 {
    // Don't connect the special merge at the end to its predecessors.
    if (IsFinalMerge(merge)) return;
    BasicBlock* block = schedule_->block(merge);
    DCHECK_NOT_NULL(block);
    // For all of the merge's control inputs, add a goto at the end to the
    // merge's basic block.
    for (Node* const input : merge->inputs()) {
      BasicBlock* predecessor_block = FindPredecessorBlock(input);
      TraceConnect(merge, predecessor_block, block);
      schedule_->AddGoto(predecessor_block, block);
    }
  }
References v8::internal::compiler::Schedule::AddGoto(), v8::internal::compiler::Schedule::block(), DCHECK_NOT_NULL, FindPredecessorBlock(), v8::internal::compiler::Node::inputs(), IsFinalMerge(), schedule_, and TraceConnect().
Referenced by ConnectBlocks().
ConnectReturn()
void v8::internal::compiler::CFGBuilder::ConnectReturn (Node * ret) [inline], [private]
Definition at line 567 of file scheduler.cc.
                                {
    Node* return_control = NodeProperties::GetControlInput(ret);
    BasicBlock* return_block = FindPredecessorBlock(return_control);
    TraceConnect(ret, return_block, nullptr);
    schedule_->AddReturn(return_block, ret);
  }
References v8::internal::compiler::Schedule::AddReturn(), FindPredecessorBlock(), v8::internal::compiler::NodeProperties::GetControlInput(), schedule_, and TraceConnect().
Referenced by ConnectBlocks().
ConnectSwitch()
void v8::internal::compiler::CFGBuilder::ConnectSwitch (Node * sw) [inline], [private]
Definition at line 517 of file scheduler.cc.
                               {
    size_t const successor_count = sw->op()->ControlOutputCount();
    BasicBlock** successor_blocks =
        zone_->AllocateArray<BasicBlock*>(successor_count);
    CollectSuccessorBlocks(sw, successor_blocks, successor_count);
    if (sw == component_entry_) {
      for (size_t index = 0; index < successor_count; ++index) {
        TraceConnect(sw, component_start_, successor_blocks[index]);
      }
      schedule_->InsertSwitch(component_start_, component_end_, sw,
                              successor_blocks, successor_count);
    } else {
      Node* switch_control = NodeProperties::GetControlInput(sw);
      BasicBlock* switch_block = FindPredecessorBlock(switch_control);
      for (size_t index = 0; index < successor_count; ++index) {
        TraceConnect(sw, switch_block, successor_blocks[index]);
      }
      schedule_->AddSwitch(switch_block, sw, successor_blocks, successor_count);
    }
    for (size_t index = 0; index < successor_count; ++index) {
      if (BranchHintOf(successor_blocks[index]->front()->op()) ==
          BranchHint::kFalse) {
        successor_blocks[index]->set_deferred(true);
      }
    }
  }
References v8::internal::compiler::Schedule::AddSwitch(), v8::internal::Zone::AllocateArray(), v8::internal::compiler::BranchHintOf(), CollectSuccessorBlocks(), component_end_, component_entry_, component_start_, v8::internal::compiler::Operator::ControlOutputCount(), FindPredecessorBlock(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::index, v8::internal::compiler::Schedule::InsertSwitch(), v8::internal::kFalse, v8::internal::compiler::Node::op(), schedule_, v8::internal::compiler::BasicBlock::set_deferred(), TraceConnect(), and zone_.
Referenced by ConnectBlocks().
ConnectTailCall()
void v8::internal::compiler::CFGBuilder::ConnectTailCall (Node * call) [inline], [private]
Definition at line 560 of file scheduler.cc.
                                   {
    Node* call_control = NodeProperties::GetControlInput(call);
    BasicBlock* call_block = FindPredecessorBlock(call_control);
    TraceConnect(call, call_block, nullptr);
    schedule_->AddTailCall(call_block, call);
  }
References v8::internal::compiler::Schedule::AddTailCall(), FindPredecessorBlock(), v8::internal::compiler::NodeProperties::GetControlInput(), schedule_, and TraceConnect().
Referenced by ConnectBlocks().
ConnectThrow()
void v8::internal::compiler::CFGBuilder::ConnectThrow (Node * thr) [inline], [private]
Definition at line 581 of file scheduler.cc.
                               {
    Node* throw_control = NodeProperties::GetControlInput(thr);
    BasicBlock* throw_block = FindPredecessorBlock(throw_control);
    TraceConnect(thr, throw_block, nullptr);
    schedule_->AddThrow(throw_block, thr);
  }
References v8::internal::compiler::Schedule::AddThrow(), FindPredecessorBlock(), v8::internal::compiler::NodeProperties::GetControlInput(), schedule_, and TraceConnect().
Referenced by ConnectBlocks().
FindPredecessorBlock()
BasicBlock* v8::internal::compiler::CFGBuilder::FindPredecessorBlock (Node * node) [inline], [private]
Definition at line 443 of file scheduler.cc.
                                               {
    BasicBlock* predecessor_block = nullptr;
    while (true) {
      predecessor_block = schedule_->block(node);
      if (predecessor_block != nullptr) break;
      node = NodeProperties::GetControlInput(node);
    }
    return predecessor_block;
  }
References v8::internal::compiler::Schedule::block(), v8::internal::compiler::NodeProperties::GetControlInput(), and schedule_.
Referenced by ConnectBranch(), ConnectCall(), ConnectDeoptimize(), ConnectMerge(), ConnectReturn(), ConnectSwitch(), ConnectTailCall(), ConnectThrow(), and v8::internal::compiler::ScheduleLateNodeVisitor::FindPredecessorBlock().
FixNode()
void v8::internal::compiler::CFGBuilder::FixNode (BasicBlock * block, Node * node) [inline], [private]
Definition at line 315 of file scheduler.cc.
                                              {
    schedule_->AddNode(block, node);
    scheduler_->UpdatePlacement(node, Scheduler::kFixed);
  }
References v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::Scheduler::kFixed, schedule_, scheduler_, and v8::internal::compiler::Scheduler::UpdatePlacement().
Referenced by BuildBlockForNode(), and BuildBlocks().
IsFinalMerge()
bool v8::internal::compiler::CFGBuilder::IsFinalMerge (Node * node) [inline], [private]
Definition at line 599 of file scheduler.cc.
                                {
    return (node->opcode() == IrOpcode::kMerge &&
            node == scheduler_->graph_->end()->InputAt(0));
  }
References v8::internal::compiler::TFGraph::end(), v8::internal::compiler::Scheduler::graph_, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::opcode(), and scheduler_.
Referenced by ConnectMerge().
IsSingleEntrySingleExitRegion()
bool v8::internal::compiler::CFGBuilder::IsSingleEntrySingleExitRegion (Node * entry, Node * exit) const [inline], [private]
Definition at line 604 of file scheduler.cc.
                                                                    {
    size_t entry_class = scheduler_->equivalence_->ClassOf(entry);
    size_t exit_class = scheduler_->equivalence_->ClassOf(exit);
    return entry != exit && entry_class == exit_class;
  }
References v8::internal::compiler::ControlEquivalence::ClassOf(), v8::internal::compiler::Scheduler::equivalence_, and scheduler_.
Referenced by Run().
Queue()
void v8::internal::compiler::CFGBuilder::Queue (Node * node) [inline], [private]
Definition at line 320 of file scheduler.cc.
                         {
    // Mark the connected control nodes as they are queued.
    if (!queued_.Get(node)) {
      BuildBlocks(node);
      queue_.push(node);
      queued_.Set(node, true);
      control_.push_back(node);
    }
  }
References BuildBlocks(), control_, v8::internal::compiler::NodeMarker< State >::Get(), v8::internal::ZoneVector< T >::push_back(), queue_, queued_, and v8::internal::compiler::NodeMarker< State >::Set().
Referenced by Run().
ResetDataStructures()
void v8::internal::compiler::CFGBuilder::ResetDataStructures () [inline], [private]
Definition at line 610 of file scheduler.cc.
                             {
    control_.clear();
    DCHECK(queue_.empty());
    DCHECK(control_.empty());
  }
References v8::internal::ZoneVector< T >::clear(), control_, v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), and queue_.
Referenced by Run().
Run() [1/2]
void v8::internal::compiler::CFGBuilder::Run () [inline]
Definition at line 255 of file scheduler.cc.
             {
    ResetDataStructures();
    Queue(scheduler_->graph_->end());
    while (!queue_.empty()) { // Breadth-first backwards traversal.
      scheduler_->tick_counter_->TickAndMaybeEnterSafepoint();
      Node* node = queue_.front();
      queue_.pop();
      int max = NodeProperties::PastControlIndex(node);
      for (int i = NodeProperties::FirstControlIndex(node); i < max; i++) {
        Queue(node->InputAt(i));
      }
    }
    for (NodeVector::iterator i = control_.begin(); i != control_.end(); ++i) {
      ConnectBlocks(*i); // Connect block to its predecessor/successors.
    }
  }
References v8::internal::ZoneVector< T >::begin(), ConnectBlocks(), control_, v8::internal::compiler::TFGraph::end(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::NodeProperties::FirstControlIndex(), v8::internal::compiler::Scheduler::graph_, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeProperties::PastControlIndex(), Queue(), queue_, ResetDataStructures(), scheduler_, v8::internal::compiler::Scheduler::tick_counter_, and v8::internal::TickCounter::TickAndMaybeEnterSafepoint().
Referenced by v8::internal::compiler::Scheduler::BuildCFG(), and v8::internal::compiler::Scheduler::FuseFloatingControl().
Run() [2/2]
void v8::internal::compiler::CFGBuilder::Run (BasicBlock * block, Node * exit) [inline]
Definition at line 277 of file scheduler.cc.
                                          {
    ResetDataStructures();
    Queue(exit);
    component_entry_ = nullptr;
    component_start_ = block;
    component_end_ = schedule_->block(exit);
    scheduler_->equivalence_->Run(exit);
    while (!queue_.empty()) { // Breadth-first backwards traversal.
      scheduler_->tick_counter_->TickAndMaybeEnterSafepoint();
      Node* node = queue_.front();
      queue_.pop();
      // Use control dependence equivalence to find a canonical single-entry
      // single-exit region that makes up a minimal component to be scheduled.
      if (IsSingleEntrySingleExitRegion(node, exit)) {
        TRACE("Found SESE at #%d:%s\n", node->id(), node->op()->mnemonic());
        DCHECK(!component_entry_);
        component_entry_ = node;
        continue;
      }
      int max = NodeProperties::PastControlIndex(node);
      for (int i = NodeProperties::FirstControlIndex(node); i < max; i++) {
        Queue(node->InputAt(i));
      }
    }
    DCHECK(component_entry_);
    for (NodeVector::iterator i = control_.begin(); i != control_.end(); ++i) {
      ConnectBlocks(*i); // Connect block to its predecessor/successors.
    }
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::Schedule::block(), component_end_, component_entry_, component_start_, ConnectBlocks(), control_, v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::Scheduler::equivalence_, v8::internal::compiler::NodeProperties::FirstControlIndex(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::InputAt(), IsSingleEntrySingleExitRegion(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::NodeProperties::PastControlIndex(), Queue(), queue_, ResetDataStructures(), v8::internal::compiler::ControlEquivalence::Run(), schedule_, scheduler_, v8::internal::compiler::Scheduler::tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), and v8::internal::TRACE().
TraceConnect()
void v8::internal::compiler::CFGBuilder::TraceConnect (Node * node, BasicBlock * block, BasicBlock * succ) [inline], [private]
Definition at line 588 of file scheduler.cc.
                                                                     {
    DCHECK_NOT_NULL(block);
    if (succ == nullptr) {
      TRACE("Connect #%d:%s, id:%d -> end\n", node->id(),
            node->op()->mnemonic(), block->id().ToInt());
    } else {
      TRACE("Connect #%d:%s, id:%d -> id:%d\n", node->id(),
            node->op()->mnemonic(), block->id().ToInt(), succ->id().ToInt());
    }
  }
References DCHECK_NOT_NULL, v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::BasicBlock::Id::ToInt(), and v8::internal::TRACE().
Referenced by ConnectBranch(), ConnectCall(), ConnectDeoptimize(), ConnectMerge(), ConnectReturn(), ConnectSwitch(), ConnectTailCall(), and ConnectThrow().
Friends And Related Function Documentation
ScheduleLateNodeVisitor
friend class ScheduleLateNodeVisitor [friend]
Definition at line 312 of file scheduler.cc.
Scheduler
friend class Scheduler [friend]
Definition at line 313 of file scheduler.cc.
Member Data Documentation
component_end_
BasicBlock* v8::internal::compiler::CFGBuilder::component_end_ [private]
Definition at line 624 of file scheduler.cc.
Referenced by ConnectBranch(), ConnectSwitch(), and Run().
component_entry_
Node* v8::internal::compiler::CFGBuilder::component_entry_ [private]
Definition at line 622 of file scheduler.cc.
Referenced by ConnectBranch(), ConnectSwitch(), and Run().
component_start_
BasicBlock* v8::internal::compiler::CFGBuilder::component_start_ [private]
Definition at line 623 of file scheduler.cc.
Referenced by ConnectBranch(), ConnectSwitch(), and Run().
control_
NodeVector v8::internal::compiler::CFGBuilder::control_ [private]
Definition at line 621 of file scheduler.cc.
Referenced by v8::internal::compiler::Scheduler::FuseFloatingControl(), Queue(), ResetDataStructures(), and Run().
queue_
ZoneQueue<Node*> v8::internal::compiler::CFGBuilder::queue_ [private]
Definition at line 620 of file scheduler.cc.
Referenced by Queue(), ResetDataStructures(), and Run().
queued_
NodeMarker<bool> v8::internal::compiler::CFGBuilder::queued_ [private]
Definition at line 619 of file scheduler.cc.
Referenced by Queue().
schedule_
Schedule* v8::internal::compiler::CFGBuilder::schedule_ [private]
Definition at line 618 of file scheduler.cc.
Referenced by BuildBlockForNode(), BuildBlocks(), CollectSuccessorBlocks(), ConnectBranch(), ConnectCall(), ConnectDeoptimize(), ConnectMerge(), ConnectReturn(), ConnectSwitch(), ConnectTailCall(), ConnectThrow(), FindPredecessorBlock(), FixNode(), and Run().
scheduler_
Scheduler* v8::internal::compiler::CFGBuilder::scheduler_ [private]
Definition at line 617 of file scheduler.cc.
Referenced by ConnectBlocks(), ConnectBranch(), FixNode(), IsFinalMerge(), IsSingleEntrySingleExitRegion(), and Run().
zone_
Zone* v8::internal::compiler::CFGBuilder::zone_ [private]
Definition at line 616 of file scheduler.cc.
Referenced by BuildBlocksForSuccessors(), and ConnectSwitch().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/scheduler.cc