v8::internal::StackLimitCheck Class Reference
#include <isolate.h>
Public Member Functions
StackLimitCheck (Isolate *isolate)
bool HasOverflowed () const
bool JsHasOverflowed (uintptr_t gap=0) const
bool WasmHasOverflowed (uintptr_t gap=0) const
bool InterruptRequested ()
V8_EXPORT_PRIVATE bool HandleStackOverflowAndTerminationRequest ()
Static Public Member Functions
static bool HasOverflowed (LocalIsolate *local_isolate)
Private Attributes
Isolate *const isolate_
Detailed Description
Definition at line 3073 of file isolate.h.
Constructor & Destructor Documentation
StackLimitCheck()
v8::internal::StackLimitCheck::StackLimitCheck (Isolate * isolate) [inline], [explicit]
Definition at line 3075 of file isolate.h.
: isolate_(isolate) {}
Member Function Documentation
HandleStackOverflowAndTerminationRequest()
bool v8::internal::StackLimitCheck::HandleStackOverflowAndTerminationRequest ()
Definition at line 7408 of file isolate.cc.
                                                               {
  DCHECK(InterruptRequested());
  if (V8_UNLIKELY(HasOverflowed())) {
    isolate_->StackOverflow();
    return true;
  }
  if (V8_UNLIKELY(isolate_->stack_guard()->HasTerminationRequest())) {
    isolate_->TerminateExecution();
    return true;
  }
  return false;
}
References v8::internal::DCHECK(), HasOverflowed(), v8::internal::StackGuard::HasTerminationRequest(), InterruptRequested(), isolate_, v8::internal::Isolate::stack_guard(), v8::internal::Isolate::StackOverflow(), v8::internal::Isolate::TerminateExecution(), and V8_UNLIKELY.
HasOverflowed() [1/2]
bool v8::internal::StackLimitCheck::HasOverflowed () const [inline]
Definition at line 3078 of file isolate.h.
                             {
    StackGuard* stack_guard = isolate_->stack_guard();
    return GetCurrentStackPosition() < stack_guard->real_climit();
  }
References v8::internal::GetCurrentStackPosition(), isolate_, v8::internal::StackGuard::real_climit(), and v8::internal::Isolate::stack_guard().
Referenced by v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::Debug::HandleDebugBreak(), HandleStackOverflowAndTerminationRequest(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::JsonParser< Char >::ParseJsonArray(), v8::internal::JsonParser< Char >::ParseJsonObject(), v8::internal::compiler::JSHeapBroker::StackHasOverflowed(), v8::internal::JsonStringifier::StackPush(), v8::internal::StringReplaceOneCharWithString(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), and v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck().
HasOverflowed() [2/2]
bool v8::internal::StackLimitCheck::HasOverflowed (LocalIsolate * local_isolate) [static]
Definition at line 68 of file local-isolate.cc.
                                                               {
  return GetCurrentStackPosition() < local_isolate->stack_limit();
}
References v8::internal::GetCurrentStackPosition(), and v8::internal::LocalIsolate::stack_limit().
InterruptRequested()
bool v8::internal::StackLimitCheck::InterruptRequested () [inline]
Definition at line 3094 of file isolate.h.
                                      {
    StackGuard* stack_guard = isolate_->stack_guard();
    return GetCurrentStackPosition() < stack_guard->climit();
  }
References v8::internal::StackGuard::climit(), v8::internal::GetCurrentStackPosition(), isolate_, and v8::internal::Isolate::stack_guard().
Referenced by v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck(), wasm::CheckAndHandleInterrupts(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::FastJsonStringifier< Char >::HandleInterruptAndCheckCycle(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::HandleInterrupts(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::HandleInterrupts(), HandleStackOverflowAndTerminationRequest(), v8::internal::anonymous_namespace{isolate.cc}::BigIntPlatform::InterruptRequested(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::Serialize_(), v8::internal::JsonStringifier::SerializeFixedArrayWithInterruptCheck(), v8::internal::FastJsonStringifier< Char >::SerializeFixedArrayWithInterruptCheck(), and v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck().
JsHasOverflowed()
bool v8::internal::StackLimitCheck::JsHasOverflowed (uintptr_t gap = 0) const
Definition at line 7421 of file isolate.cc.
                                                         {
  StackGuard* stack_guard = isolate_->stack_guard();
#ifdef USE_SIMULATOR
  // The simulator uses a separate JS stack.
  Address jssp_address = Simulator::current(isolate_)->get_sp();
  uintptr_t jssp = static_cast<uintptr_t>(jssp_address);
  if (jssp - gap < stack_guard->real_jslimit()) return true;
#endif // USE_SIMULATOR
  return GetCurrentStackPosition() - gap < stack_guard->real_climit();
}
References v8::internal::GetCurrentStackPosition(), isolate_, v8::internal::StackGuard::real_climit(), and v8::internal::Isolate::stack_guard().
Referenced by v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::RegExpImpl::CompileIrregexp(), v8::internal::Compiler::CompileSharedWithBaseline(), v8::internal::Object::GetPropertyWithDefinedGetter(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::HandleInterrupts(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::HandleInterrupts(), v8::internal::Intl::NumberToLocaleString(), v8::internal::Debug::OnException(), and v8::internal::RUNTIME_FUNCTION().
WasmHasOverflowed()
bool v8::internal::StackLimitCheck::WasmHasOverflowed (uintptr_t gap = 0) const
Definition at line 7432 of file isolate.cc.
                                                           {
  StackGuard* stack_guard = isolate_->stack_guard();
  auto sp = isolate_->thread_local_top()->secondary_stack_sp_;
  auto limit = isolate_->thread_local_top()->secondary_stack_limit_;
  if (sp == 0) {
#ifdef USE_SIMULATOR
    // The simulator uses a separate JS stack.
    // Use it if code is executed on the central stack.
    Address jssp_address = Simulator::current(isolate_)->get_sp();
    uintptr_t jssp = static_cast<uintptr_t>(jssp_address);
    if (jssp - gap < stack_guard->real_jslimit()) return true;
#endif // USE_SIMULATOR
    sp = GetCurrentStackPosition();
    limit = stack_guard->real_climit();
  }
  return sp - gap < limit;
}
References v8::internal::GetCurrentStackPosition(), isolate_, v8::internal::StackGuard::real_climit(), v8::internal::ThreadLocalTop::secondary_stack_limit_, v8::internal::ThreadLocalTop::secondary_stack_sp_, v8::internal::Isolate::stack_guard(), and v8::internal::Isolate::thread_local_top().
Referenced by v8::internal::wasm::grow_stack(), and v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
isolate_
Isolate* const v8::internal::StackLimitCheck::isolate_ [private]
Definition at line 3105 of file isolate.h.
Referenced by HandleStackOverflowAndTerminationRequest(), HasOverflowed(), InterruptRequested(), JsHasOverflowed(), and WasmHasOverflowed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/isolate.h
/mnt/V8SourceCode/src/execution/isolate.cc
/mnt/V8SourceCode/src/execution/local-isolate.cc