v8::internal::ImportedFunctionEntry Class Reference
#include <wasm-objects.h>
Public Member Functions
ImportedFunctionEntry (DirectHandle< WasmTrustedInstanceData >, int index)
void SetWasmToWasm (Tagged< WasmTrustedInstanceData > target_instance_object, WasmCodePointer call_target, wasm::CanonicalTypeIndex sig_id)
V8_EXPORT_PRIVATE void SetWasmToWrapper (Isolate *, DirectHandle< JSReceiver > callable, std::shared_ptr< wasm::WasmImportWrapperHandle > wrapper_handle, wasm::Suspend suspend, const wasm::CanonicalSig *sig, wasm::CanonicalTypeIndex sig_id)
Tagged< JSReceiver > callable ()
Tagged< Object > maybe_callable ()
Tagged< Object > implicit_arg ()
WasmCodePointer target ()
Private Attributes
DirectHandle< WasmTrustedInstanceData > const instance_data_
int const index_
Detailed Description
Definition at line 123 of file wasm-objects.h.
Constructor & Destructor Documentation
ImportedFunctionEntry()
v8::internal::ImportedFunctionEntry::ImportedFunctionEntry (DirectHandle< WasmTrustedInstanceData > , int index) [inline]
Member Function Documentation
callable()
Tagged< JSReceiver > v8::internal::ImportedFunctionEntry::callable ()
Definition at line 1611 of file wasm-objects.cc.
                                                   {
  return Cast<JSReceiver>(Cast<WasmImportData>(implicit_arg())->callable());
}
References implicit_arg().
Referenced by v8::internal::wasm::ResolvedWasmImport::ComputeKind(), maybe_callable(), and SetWasmToWrapper().
implicit_arg()
Tagged< Object > v8::internal::ImportedFunctionEntry::implicit_arg ()
Definition at line 1615 of file wasm-objects.cc.
                                                   {
  return instance_data_->dispatch_table_for_imports()->implicit_arg(index_);
}
References index_, and instance_data_.
Referenced by callable(), v8::internal::wasm::WasmInterpreterRuntime::CallImportedFunction(), v8::internal::wasm::ResolvedWasmImport::ComputeKind(), and maybe_callable().
maybe_callable()
Tagged< Object > v8::internal::ImportedFunctionEntry::maybe_callable ()
Definition at line 1605 of file wasm-objects.cc.
                                                     {
  Tagged<Object> data = implicit_arg();
  if (!IsWasmImportData(data)) return Tagged<Object>();
  return Cast<JSReceiver>(Cast<WasmImportData>(data)->callable());
}
References callable(), implicit_arg(), and v8::internal::Tagged< Object >.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1().
SetWasmToWasm()
void v8::internal::ImportedFunctionEntry::SetWasmToWasm (Tagged< WasmTrustedInstanceData > target_instance_object, WasmCodePointer call_target, wasm::CanonicalTypeIndex sig_id)
Definition at line 1574 of file wasm-objects.cc.
  {
  TRACE_IFT("Import Wasm 0x%" PRIxPTR "[%d] = {instance_data=0x%" PRIxPTR
            ", target=0x%" PRIxPTR "}\n",
            instance_data_->ptr(), index_, target_instance_data.ptr(),
            wasm::GetProcessWideWasmCodePointerTable()
                ->GetEntrypointWithoutSignatureCheck(call_target));
  DisallowGarbageCollection no_gc;
  Tagged<WasmDispatchTable> dispatch_table =
      instance_data_->dispatch_table_for_imports();
  dispatch_table->SetForNonWrapper(index_, target_instance_data, call_target,
                                   sig_id,
#if V8_ENABLE_DRUMBRAKE
                                   WasmDispatchTable::kInvalidFunctionIndex,
#endif // V8_ENABLE_DRUMBRAKE
                                   WasmDispatchTable::kExistingEntry);
#if V8_ENABLE_DRUMBRAKE
  instance_data_->imported_function_indices()->set(index_,
                                                   exported_function_index);
#endif // V8_ENABLE_DRUMBRAKE
}
References v8::internal::wasm::WasmCodePointerTable::GetEntrypointWithoutSignatureCheck(), v8::internal::wasm::GetProcessWideWasmCodePointerTable(), index_, instance_data_, v8::internal::WasmDispatchTable::kExistingEntry, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and TRACE_IFT.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessImportedFunction().
SetWasmToWrapper()
void v8::internal::ImportedFunctionEntry::SetWasmToWrapper (Isolate * isolate, DirectHandle< JSReceiver > callable, std::shared_ptr< wasm::WasmImportWrapperHandle > wrapper_handle, wasm::Suspend suspend, const wasm::CanonicalSig * sig, wasm::CanonicalTypeIndex sig_id)
Definition at line 1517 of file wasm-objects.cc.
                                   {
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    // Ignores wrapper_handle.
    DirectHandle<WasmImportData> import_data =
        isolate->factory()->NewWasmImportData(callable, suspend, instance_data_,
                                              sig, false /*kShared*/);
    {
      DisallowGarbageCollection no_gc;
      instance_data_->dispatch_table_for_imports()->SetForWrapper(
          index_, *import_data, {}, sig_id, -1,
          WasmDispatchTable::kExistingEntry);
    }
    instance_data_->imported_function_indices()->set(index_, -1);
    return;
  }
#endif // V8_ENABLE_DRUMBRAKE
  TRACE_IFT("Import callable 0x%" PRIxPTR "[%d] = {callable=0x%" PRIxPTR
            ", target=%p}\n",
            instance_data_->ptr(), index_, callable->ptr(),
            wrapper_handle->has_code()
                ? nullptr
                : wrapper_handle->code().instructions().begin());
  if (wrapper_handle->has_code()) {
    DCHECK(wrapper_handle->code().kind() == wasm::WasmCode::kWasmToJsWrapper ||
           wrapper_handle->code().kind() == wasm::WasmCode::kWasmToCapiWrapper);
    DCHECK_EQ(wrapper_handle->code().signature_hash(), sig->signature_hash());
  }
  constexpr bool kShared = false;
  DirectHandle<WasmImportData> import_data =
      isolate->factory()->NewWasmImportData(callable, suspend, instance_data_,
                                            sig, kShared);
  if (!wrapper_handle->has_code()) {
    import_data->SetIndexInTableAsCallOrigin(
        instance_data_->dispatch_table_for_imports(), index_);
  }
  DisallowGarbageCollection no_gc;
  Tagged<WasmDispatchTable> dispatch_table =
      instance_data_->dispatch_table_for_imports();
  dispatch_table->SetForWrapper(index_, *import_data, std::move(wrapper_handle),
                                sig_id,
#if V8_ENABLE_DRUMBRAKE
                                WasmDispatchTable::kInvalidFunctionIndex,
#endif // V8_ENABLE_DRUMBRAKE
                                WasmDispatchTable::kNewEntry);
}
References callable(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), index_, instance_data_, v8::internal::WasmDispatchTable::kExistingEntry, v8::internal::WasmDispatchTable::kNewEntry, v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::wasm::WasmCode::kWasmToCapiWrapper, v8::internal::wasm::WasmCode::kWasmToJsWrapper, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::sig, TRACE_IFT, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessImportedFunction().
target()
WasmCodePointer v8::internal::ImportedFunctionEntry::target ()
Definition at line 1619 of file wasm-objects.cc.
                                              {
  return instance_data_->dispatch_table_for_imports()->target(index_);
}
References index_, and instance_data_.
Member Data Documentation
index_
int const v8::internal::ImportedFunctionEntry::index_ [private]
Definition at line 158 of file wasm-objects.h.
Referenced by implicit_arg(), SetWasmToWasm(), SetWasmToWrapper(), and target().
instance_data_
DirectHandle<WasmTrustedInstanceData> const v8::internal::ImportedFunctionEntry::instance_data_ [private]
Definition at line 157 of file wasm-objects.h.
Referenced by implicit_arg(), SetWasmToWasm(), SetWasmToWrapper(), and target().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc