v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreFixedArrayElementWithWriteBarrier (uint64_t bitfield)
Input & elements_input ()
Input & index_input ()
Input & value_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kElementsIndex = 0
static constexpr int kIndexIndex = 1
static constexpr int kValueIndex = 2
Private Types
using Base = FixedInputNodeT< 3, StoreFixedArrayElementWithWriteBarrier >
Additional Inherited Members
Detailed Description
Definition at line 8429 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::Base = FixedInputNodeT<3, StoreFixedArrayElementWithWriteBarrier> [private]
Definition at line 8431 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreFixedArrayElementWithWriteBarrier()
v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::StoreFixedArrayElementWithWriteBarrier (uint64_t bitfield) [inline], [explicit]
Definition at line 8434 of file maglev-ir.h.
      : Base(bitfield) {}
Member Function Documentation
elements_input()
Input& v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::elements_input () [inline]
Definition at line 8446 of file maglev-ir.h.
{ return input(kElementsIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::GenerateCode (MaglevAssembler * , const ProcessingState &)
index_input()
Input& v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::index_input () [inline]
Definition at line 8447 of file maglev-ir.h.
{ return input(kIndexIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::MaxCallStackArgs () const [inline]
Definition at line 8450 of file maglev-ir.h.
{ return 0; }
PrintParams()
void v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 8453 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::value_input () [inline]
Definition at line 8448 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kElementsIndex
constexpr int v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::kElementsIndex = 0 [static], [constexpr]
Definition at line 8443 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
kIndexIndex
constexpr int v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::kIndexIndex = 1 [static], [constexpr]
Definition at line 8444 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kInt32,
      ValueRepresentation::kTagged}
Definition at line 8439 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanWrite() | OpProperties::DeferredCall()
Definition at line 8437 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::kValueIndex = 2 [static], [constexpr]
Definition at line 8445 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h