v8::internal::compiler::FeedbackCellRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< FeedbackCell > object () const
ObjectRef value (JSHeapBroker *broker) const
OptionalFeedbackVectorRef feedback_vector (JSHeapBroker *broker) const
OptionalSharedFunctionInfoRef shared_function_info (JSHeapBroker *broker) const
Detailed Description
Definition at line 835 of file heap-refs.h.
Member Function Documentation
feedback_vector()
OptionalFeedbackVectorRef v8::internal::compiler::FeedbackCellRef::feedback_vector (JSHeapBroker * broker) const
Definition at line 2335 of file heap-refs.cc.
                                {
  ObjectRef contents = value(broker);
  if (!contents.IsFeedbackVector()) return {};
  return contents.AsFeedbackVector();
}
References broker(), and value().
Referenced by v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CanConsiderForInlining(), v8::internal::compiler::JSFunctionRef::feedback_vector(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), shared_function_info(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall().
object()
IndirectHandle<FeedbackCell> v8::internal::compiler::FeedbackCellRef::object () const
Referenced by v8::internal::maglev::FastCreateClosure::PrintParams(), v8::internal::maglev::CreateClosure::PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
shared_function_info()
OptionalSharedFunctionInfoRef v8::internal::compiler::FeedbackCellRef::shared_function_info (JSHeapBroker * broker) const
Definition at line 2342 of file heap-refs.cc.
                                {
  OptionalFeedbackVectorRef vector = feedback_vector(broker);
  if (!vector.has_value()) return {};
  return vector->shared_function_info(broker);
}
References broker(), and feedback_vector().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CanConsiderForInlining(), v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::JSInliner::DetermineCallTarget(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor().
value()
ObjectRef v8::internal::compiler::FeedbackCellRef::value (JSHeapBroker * broker) const
Definition at line 1787 of file heap-refs.cc.
                                                           {
  DCHECK(data_->should_access_heap());
  return MakeRefAssumeMemoryFence(broker, object()->value(kAcquireLoad));
}
References broker(), v8::internal::DCHECK(), v8::kAcquireLoad, and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::maglev::MaglevCompilationUnit::feedback_cell(), feedback_vector(), and v8::internal::compiler::JSCallReducer::ReduceJSCall().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc