v8::internal::DeclarationScope Class Reference
#include <scopes.h>
Classes
struct RareData
Public Member Functions
DeclarationScope (Zone *zone, Scope *outer_scope, ScopeType scope_type, FunctionKind function_kind=FunctionKind::kNormalFunction)
DeclarationScope (Zone *zone, ScopeType scope_type, AstValueFactory *ast_value_factory, Handle< ScopeInfo > scope_info)
DeclarationScope (Zone *zone, AstValueFactory *ast_value_factory, REPLMode repl_mode=REPLMode::kNo)
FunctionKind function_kind () const
void RecordSuperPropertyUsage ()
bool uses_super_property () const
void TakeUnresolvedReferencesFromParent ()
bool is_arrow_scope () const
void RecordDeclarationScopeEvalCall ()
bool sloppy_eval_can_extend_vars () const
bool was_lazily_parsed () const
Variable * LookupInModule (const AstRawString *name)
void DeserializeReceiver (AstValueFactory *ast_value_factory)
void set_zone (Zone *zone)
Declaration * CheckConflictingVarDeclarations (bool *allowed_catch_binding_var_redeclaration)
void set_has_checked_syntax (bool has_checked_syntax)
bool has_checked_syntax () const
bool ShouldEagerCompile () const
void set_should_eager_compile ()
void SetScriptScopeInfo (Handle< ScopeInfo > scope_info)
bool should_ban_arguments () const
void set_module_has_toplevel_await ()
void DeclareThis (AstValueFactory *ast_value_factory)
void DeclareArguments (AstValueFactory *ast_value_factory)
void DeclareDefaultFunctionVariables (AstValueFactory *ast_value_factory)
Variable * DeclareFunctionVar (const AstRawString *name, Scope *cache=nullptr)
Variable * DeclareGeneratorObjectVar (const AstRawString *name)
Variable * DeclareParameter (const AstRawString *name, VariableMode mode, bool is_optional, bool is_rest, AstValueFactory *ast_value_factory, int position)
void RecordParameter (bool is_rest)
Variable * DeclareDynamicGlobal (const AstRawString *name, VariableKind variable_kind, Scope *cache)
Variable * receiver ()
bool has_this_declaration () const
Variable * new_target_var ()
Variable * function_var () const
Variable * generator_object_var () const
Variable * parameter (int index) const
int num_parameters () const
Variable * rest_parameter () const
bool has_simple_parameters () const
void SetHasNonSimpleParameters ()
void MakeParametersNonSimple ()
CreateArgumentsType GetArgumentsType () const
Variable * arguments () const
Variable * this_function_var () const
void AddLocal (Variable *var)
void DeclareSloppyBlockFunction (SloppyBlockFunctionStatement *sloppy_block_function)
void HoistSloppyBlockFunctions (AstNodeFactory *factory)
void AnalyzePartially (Parser *parser, AstNodeFactory *ast_node_factory, bool maybe_in_arrowhead)
bool AllowsLazyCompilation () const
void ForceEagerCompilation ()
void AllocateLocals ()
void AllocateParameterLocals ()
void AllocateReceiver ()
void ResetAfterPreparsing (AstValueFactory *ast_value_factory, bool aborted)
bool is_skipped_function () const
void set_is_skipped_function (bool is_skipped_function)
bool has_inferred_function_name () const
void set_has_inferred_function_name (bool value)
void SavePreparseDataForDeclarationScope (Parser *parser)
void set_preparse_data_builder (PreparseDataBuilder *preparse_data_builder)
PreparseDataBuilder * preparse_data_builder () const
void set_has_this_reference ()
bool has_this_reference () const
void UsesThis ()
bool needs_private_name_context_chain_recalc () const
void RecordNeedsPrivateNameContextChainRecalc ()
void set_class_scope_has_private_brand (bool value)
bool class_scope_has_private_brand () const
template<typename IsolateT >
void AllocateScopeInfos (ParseInfo *parse_info, DirectHandle< Script > script, IsolateT *isolate)
Static Public Member Functions
static V8_WARN_UNUSED_RESULT bool Analyze (ParseInfo *info)
template<typename IsolateT >
static V8_EXPORT_PRIVATE void AllocateScopeInfos (ParseInfo *info, DirectHandle< Script > script, IsolateT *isolate)
Private Types
enum class RareVariable { kThisFunction = offsetof(RareData, this_function)
, kGeneratorObject = offsetof(RareData, generator_object)
 }
Private Member Functions
void AllocateParameter (Variable *var, int index)
bool AllocateVariables (ParseInfo *info)
void SetDefaults ()
void RecalcPrivateNameContextChain ()
RareData * EnsureRareData ()
Variable * GetRareVariable (RareVariable id) const
template<typename Predicate >
void NullifyRareVariableIf (RareVariable id, Predicate predicate)
Private Attributes
bool has_simple_parameters_: 1
bool force_eager_compilation_: 1
bool has_rest_: 1
bool has_arguments_parameter_: 1
bool uses_super_property_: 1
bool should_eager_compile_: 1
bool was_lazily_parsed_: 1
bool is_skipped_function_: 1
bool has_inferred_function_name_: 1
bool has_checked_syntax_: 1
bool has_this_reference_: 1
bool has_this_declaration_: 1
bool needs_private_name_context_chain_recalc_: 1
bool class_scope_has_private_brand_: 1
FunctionKind function_kind_
int num_parameters_ = 0
ZonePtrList< Variable > params_
base::ThreadedList< SloppyBlockFunctionStatement > sloppy_block_functions_
Variable * receiver_
Variable * function_
Variable * new_target_
Variable * arguments_
PreparseDataBuilder * preparse_data_builder_
RareData * rare_data_ = nullptr
Additional Inherited Members
Detailed Description
Definition at line 862 of file scopes.h.
Member Enumeration Documentation
RareVariable
enum v8::internal::DeclarationScope::RareVariable [strong], [private]
Enumerator
kThisFunction
kGeneratorObject
Definition at line 1320 of file scopes.h.
                          {
    kThisFunction = offsetof(RareData, this_function),
    kGeneratorObject = offsetof(RareData, generator_object),
  };
Constructor & Destructor Documentation
DeclarationScope() [1/3]
v8::internal::DeclarationScope::DeclarationScope (Zone * zone, Scope * outer_scope, ScopeType scope_type, FunctionKind function_kind = FunctionKind::kNormalFunction)
Definition at line 166 of file scopes.cc.
    : Scope(zone, outer_scope, scope_type),
      function_kind_(function_kind),
      params_(4, zone) {
  DCHECK(!is_script_scope());
  SetDefaults();
}
References v8::internal::DCHECK(), v8::internal::Scope::is_script_scope(), and SetDefaults().
DeclarationScope() [2/3]
v8::internal::DeclarationScope::DeclarationScope (Zone * zone, ScopeType scope_type, AstValueFactory * ast_value_factory, Handle< ScopeInfo > scope_info)
Definition at line 281 of file scopes.cc.
    : Scope(zone, scope_type, ast_value_factory, scope_info),
      function_kind_(scope_info->function_kind()),
      params_(0, zone) {
  DCHECK(!is_script_scope());
  SetDefaults();
  if (scope_info->SloppyEvalCanExtendVars()) {
    DCHECK(!is_eval_scope());
    sloppy_eval_can_extend_vars_ = true;
    is_dynamic_scope_ = true;
  }
  if (scope_info->ClassScopeHasPrivateBrand()) {
    DCHECK(IsClassConstructor(function_kind()));
    class_scope_has_private_brand_ = true;
  }
}
References class_scope_has_private_brand_, v8::internal::DCHECK(), function_kind(), v8::internal::Scope::is_dynamic_scope_, v8::internal::Scope::is_eval_scope(), v8::internal::Scope::is_script_scope(), v8::internal::IsClassConstructor(), v8::internal::Scope::scope_info(), SetDefaults(), and v8::internal::Scope::sloppy_eval_can_extend_vars_.
DeclarationScope() [3/3]
v8::internal::DeclarationScope::DeclarationScope (Zone * zone, AstValueFactory * ast_value_factory, REPLMode repl_mode = REPLMode::kNo)
Definition at line 152 of file scopes.cc.
    : Scope(zone, repl_mode == REPLMode::kYes ? REPL_MODE_SCOPE : SCRIPT_SCOPE),
      function_kind_(repl_mode == REPLMode::kYes
                         ? FunctionKind::kAsyncFunction
                         : FunctionKind::kNormalFunction),
      params_(4, zone) {
  DCHECK(is_script_scope());
  SetDefaults();
  receiver_ = DeclareDynamicGlobal(ast_value_factory->this_string(),
                                   THIS_VARIABLE, this);
}
References v8::internal::DCHECK(), DeclareDynamicGlobal(), v8::internal::Scope::is_script_scope(), v8::internal::kAsyncFunction, receiver_, SetDefaults(), and v8::internal::THIS_VARIABLE.
Member Function Documentation
AddLocal()
void v8::internal::DeclarationScope::AddLocal (Variable * var)
Definition at line 925 of file scopes.cc.
                                             {
  DCHECK(!already_resolved_);
  // Temporaries are only placed in ClosureScopes.
  DCHECK_EQ(GetClosureScope(), this);
  locals_.Add(var);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Scope::GetClosureScope(), and v8::internal::Scope::locals_.
Referenced by v8::internal::Scope::NewTemporary().
AllocateLocals()
void v8::internal::DeclarationScope::AllocateLocals () [inline]
Definition at line 2547 of file scopes.cc.
                                      {
  // For now, function_ must be allocated at the very end. If it gets
  // allocated in the context, it must be the last slot in the context,
  // because of the current ScopeInfo implementation (see
  // ScopeInfo::ScopeInfo(FunctionScope* scope) constructor).
  if (function_ != nullptr && MustAllocate(function_)) {
    AllocateNonParameterLocal(function_);
  } else {
    function_ = nullptr;
  }
  DCHECK(!has_rest_ || !MustAllocate(rest_parameter()) ||
         !rest_parameter()->IsUnallocated());
  if (new_target_ != nullptr && !MustAllocate(new_target_)) {
    new_target_ = nullptr;
  }
  NullifyRareVariableIf(RareVariable::kThisFunction, [=, this](Variable* var) {
    return !MustAllocate(var);
  });
}
References v8::internal::Scope::AllocateNonParameterLocal(), v8::internal::DCHECK(), and v8::internal::Scope::MustAllocate().
Referenced by v8::internal::Scope::AllocateNonParameterLocalsAndDeclaredGlobals().
AllocateParameter()
void v8::internal::DeclarationScope::AllocateParameter (Variable * var, int index) [inline], [private]
Definition at line 2488 of file scopes.cc.
                                                                 {
  if (!MustAllocate(var)) return;
  if (has_forced_context_allocation_for_parameters() ||
      MustAllocateInContext(var)) {
    DCHECK(var->IsUnallocated() || var->IsContextSlot());
    if (var->IsUnallocated()) AllocateHeapSlot(var);
  } else {
    DCHECK(var->IsUnallocated() || var->IsParameter());
    if (var->IsUnallocated()) {
      var->AllocateTo(VariableLocation::PARAMETER, index);
    }
  }
}
References v8::internal::Scope::AllocateHeapSlot(), v8::internal::Variable::AllocateTo(), v8::internal::DCHECK(), v8::internal::Scope::has_forced_context_allocation_for_parameters(), v8::internal::index, v8::internal::Variable::IsContextSlot(), v8::internal::Variable::IsParameter(), v8::internal::Variable::IsUnallocated(), v8::internal::Scope::MustAllocate(), v8::internal::Scope::MustAllocateInContext(), and v8::internal::PARAMETER.
AllocateParameterLocals()
void v8::internal::DeclarationScope::AllocateParameterLocals () [inline]
Definition at line 2445 of file scopes.cc.
                                               {
  DCHECK(is_function_scope());
  bool has_mapped_arguments = false;
  if (arguments_ != nullptr) {
    DCHECK(!is_arrow_scope());
    if (MustAllocate(arguments_) && !has_arguments_parameter_) {
      // 'arguments' is used and does not refer to a function
      // parameter of the same name. If the arguments object
      // aliases formal parameters, we conservatively allocate
      // them specially in the loop below.
      has_mapped_arguments =
          GetArgumentsType() == CreateArgumentsType::kMappedArguments;
    } else {
      // 'arguments' is unused. Tell the code generator that it does not need to
      // allocate the arguments object by nulling out arguments_.
      arguments_ = nullptr;
    }
  }
  // The same parameter may occur multiple times in the parameters_ list.
  // If it does, and if it is not copied into the context object, it must
  // receive the highest parameter index for that parameter; thus iteration
  // order is relevant!
  for (int i = num_parameters() - 1; i >= 0; --i) {
    Variable* var = params_[i];
    DCHECK_NOT_NULL(var);
    DCHECK(!has_rest_ || var != rest_parameter());
    DCHECK_EQ(this, var->scope());
    if (has_mapped_arguments) {
      var->set_is_used();
      var->SetMaybeAssigned();
      var->ForceContextAllocation();
    }
    AllocateParameter(var, i);
  }
  // If we have mapped arguments, do not use context cells.
  if (has_mapped_arguments) {
    has_context_cells_ = false;
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::Variable::ForceContextAllocation(), v8::internal::Scope::has_context_cells_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Scope::is_function_scope(), v8::internal::kMappedArguments, v8::internal::Scope::MustAllocate(), v8::internal::Variable::scope(), v8::internal::Variable::set_is_used(), and v8::internal::Variable::SetMaybeAssigned().
Referenced by v8::internal::Scope::AllocateVariablesRecursively().
AllocateReceiver()
void v8::internal::DeclarationScope::AllocateReceiver () [inline]
Definition at line 2502 of file scopes.cc.
                                        {
  if (!has_this_declaration()) return;
  DCHECK_NOT_NULL(receiver());
  DCHECK_EQ(receiver()->scope(), this);
  AllocateParameter(receiver(), -1);
}
References DCHECK_EQ, and DCHECK_NOT_NULL.
Referenced by v8::internal::Scope::AllocateVariablesRecursively().
AllocateScopeInfos() [1/2]
template<typename IsolateT >
static V8_EXPORT_PRIVATE void v8::internal::DeclarationScope::AllocateScopeInfos (ParseInfo * info, DirectHandle< Script > script, IsolateT * isolate) [static]
Referenced by v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs().
AllocateScopeInfos() [2/2]
template<typename IsolateT >
void v8::internal::DeclarationScope::AllocateScopeInfos (ParseInfo * parse_info, DirectHandle< Script > script, IsolateT * isolate)
Definition at line 2773 of file scopes.cc.
                                                             {
  DeclarationScope* scope = parse_info->literal()->scope();
  // No one else should have allocated a scope info for this scope yet.
  DCHECK(scope->scope_info_.is_null());
  MaybeHandle<ScopeInfo> outer_scope;
  if (scope->outer_scope_ != nullptr) {
    DCHECK((std::is_same_v<Isolate, v8::internal::Isolate>));
    outer_scope = scope->outer_scope_->scope_info_;
  }
  if (scope->needs_private_name_context_chain_recalc()) {
    scope->RecalcPrivateNameContextChain();
  }
  Tagged<WeakFixedArray> infos = script->infos();
  std::unordered_map<int, Handle<ScopeInfo>> scope_infos_to_reuse;
  if (v8_flags.reuse_scope_infos && infos->length() != 0) {
    Tagged<SharedFunctionInfo> parse_info_sfi =
        *parse_info->literal()->shared_function_info();
    Tagged<ScopeInfo> outer = parse_info_sfi->HasOuterScopeInfo()
                                  ? parse_info_sfi->GetOuterScopeInfo()
                                  : Tagged<ScopeInfo>();
    // Look at all inner functions whether they have scope infos that we should
    // reuse. Also look at the compiled function itself, and reuse its function
    // scope info if it exists.
    for (int i = parse_info->literal()->function_literal_id();
         i <= parse_info->max_info_id(); ++i) {
      Tagged<MaybeObject> maybe_info = infos->get(i);
      if (maybe_info.IsWeak()) {
        Tagged<Object> info = maybe_info.GetHeapObjectAssumeWeak();
        Tagged<ScopeInfo> scope_info;
        if (Is<SharedFunctionInfo>(info)) {
          Tagged<SharedFunctionInfo> sfi = Cast<SharedFunctionInfo>(info);
          if (!sfi->scope_info()->IsEmpty()) {
            scope_info = sfi->scope_info();
          } else if (sfi->HasOuterScopeInfo()) {
            scope_info = sfi->GetOuterScopeInfo();
          } else {
            continue;
          }
        } else {
          scope_info = Cast<ScopeInfo>(info);
        }
        while (true) {
          if (scope_info == outer) break;
          int id = scope_info->UniqueIdInScript();
          auto it = scope_infos_to_reuse.find(id);
          if (it != scope_infos_to_reuse.end()) {
            if (V8_LIKELY(*it->second == scope_info)) break;
            // TODO(crbug.com/401059828): remove once crashes are gone.
            int last_checked_field_index = 0;
            bool equal_scopes =
                it->second->Equals(scope_info, parse_info_sfi->live_edited(),
                                   &last_checked_field_index);
            std::unique_ptr<char[]> script_name_or_url;
            size_t script_name_or_url_length = 0;
            if (IsString(script->GetNameOrSourceURL())) {
              script_name_or_url = Cast<String>(script->GetNameOrSourceURL())
                                       ->ToCString(&script_name_or_url_length);
            }
            std::unique_ptr<char[]> script_source;
            size_t script_source_length = 0;
            std::unique_ptr<char[]> function_source;
            size_t function_source_length = 0;
            if (IsString(script->source())) {
              script_source = Cast<String>(script->source())
                                  ->ToCString(&script_source_length);
              function_source =
                  Cast<String>(script->source())
                      ->ToCString(parse_info_sfi->StartPosition(),
                                  parse_info_sfi->EndPosition() -
                                      parse_info_sfi->StartPosition(),
                                  &function_source_length);
            }
            std::vector<Address> data{
                scope_info->ptr(),
                it->second->ptr(),
                static_cast<Address>(equal_scopes),
                static_cast<Address>(last_checked_field_index),
                parse_info_sfi.ptr(),
                outer.ptr(),
                0xcafe0000,
                infos.ptr(),
                static_cast<Address>(
                    parse_info->literal()->function_literal_id()),
                static_cast<Address>(parse_info->max_info_id()),
                static_cast<Address>(i),
                0xcafe0001,
                info.ptr(),
                static_cast<Address>(id),
                outer_scope.is_null() ? 0
                                      : outer_scope.ToHandleChecked()->ptr(),
                0xcafe0002,
                scope_info->HasOuterScopeInfo()
                    ? scope_info->OuterScopeInfo().ptr()
                    : 0,
                it->second->HasOuterScopeInfo()
                    ? it->second->OuterScopeInfo().ptr()
                    : 0,
                0xcafe0003,
                script->ptr(),
                script->GetNameOrSourceURL().ptr(),
                static_cast<Address>(parse_info_sfi->StartPosition()),
                static_cast<Address>(parse_info_sfi->EndPosition()),
                0xcafe0004,
                script->source().ptr(),
                reinterpret_cast<Address>(script_source.get()),
                script_source_length,
                reinterpret_cast<Address>(script_source.get() +
                                          parse_info_sfi->StartPosition()),
                reinterpret_cast<Address>(script_source.get() +
                                          parse_info_sfi->EndPosition()),
                0xcafe0005,
                parse_info_sfi->Name().ptr(),
                reinterpret_cast<Address>(function_source.get()),
                function_source_length,
                reinterpret_cast<Address>(function_source.get() +
                                          function_source_length),
                0xcafe0006,
                script_name_or_url_length,
                reinterpret_cast<Address>(script_name_or_url.get()),
                reinterpret_cast<Address>(script_name_or_url.get() +
                                          script_name_or_url_length),
                0xcafeffff,
            };
            Isolate* main_thread_isolate =
                isolate->GetMainThreadIsolateUnsafe();
            StackTraceFailureMessage::StackTraceMode mode =
                std::is_same_v<IsolateT, Isolate>
                    ? StackTraceFailureMessage::kIncludeStackTrace
                    : StackTraceFailureMessage::kDontIncludeStackTrace;
            StackTraceFailureMessage message(main_thread_isolate, mode,
                                             &data[0], data.size());
            message.Print();
            if (equal_scopes) {
              // Proceed execution if the scopes are structurally equal.
              // isolate->PushStackTraceAndContinue(...);
              V8::GetCurrentPlatform()->DumpWithoutCrashing();
              break;
            }
            // The scopes are different, stop here.
            // isolate->PushStackTraceAndDie(...);
            base::OS::Abort();
          }
          scope_infos_to_reuse[id] = handle(scope_info, isolate);
          if (!scope_info->HasOuterScopeInfo()) break;
          scope_info = scope_info->OuterScopeInfo();
        }
      }
    }
  }
  scope->AllocateScopeInfosRecursively(isolate, outer_scope,
                                       scope_infos_to_reuse);
  // The debugger expects all shared function infos to contain a scope info.
  // Since the top-most scope will end up in a shared function info, make sure
  // it has one, even if it doesn't need a scope info.
  // TODO(yangguo): Remove this requirement.
  if (scope->scope_info_.is_null()) {
    scope->scope_info_ =
        ScopeInfo::Create(isolate, scope->zone(), scope, outer_scope);
  }
  // Ensuring that the outer script scope has a scope info avoids having
  // special case for native contexts vs other contexts.
  if (parse_info->script_scope() &&
      parse_info->script_scope()->scope_info_.is_null()) {
    parse_info->script_scope()->scope_info_ =
        isolate->factory()->empty_scope_info();
  }
}
References v8::base::OS::Abort(), v8::internal::Scope::AllocateScopeInfosRecursively(), v8::internal::ScopeInfo::Create(), v8::internal::DCHECK(), v8::Platform::DumpWithoutCrashing(), v8::internal::FunctionLiteral::function_literal_id(), v8::internal::V8::GetCurrentPlatform(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::Isolate::GetMainThreadIsolateUnsafe(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::internal::StackTraceFailureMessage::kDontIncludeStackTrace, v8::internal::StackTraceFailureMessage::kIncludeStackTrace, v8::internal::ParseInfo::literal(), v8::internal::ParseInfo::max_info_id(), mode(), needs_private_name_context_chain_recalc(), v8::internal::Scope::outer_scope(), v8::internal::Scope::outer_scope_, v8::internal::StackTraceFailureMessage::Print(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), RecalcPrivateNameContextChain(), v8::internal::FunctionLiteral::scope(), v8::internal::Scope::scope_info(), v8::internal::Scope::scope_info_, v8::internal::script, v8::internal::ParseInfo::script_scope(), v8::internal::FunctionLiteral::shared_function_info(), v8::internal::v8_flags, V8_LIKELY, and v8::internal::Scope::zone().
AllocateVariables()
bool v8::internal::DeclarationScope::AllocateVariables (ParseInfo * info) [private]
Definition at line 1383 of file scopes.cc.
                                                        {
  // Module variables must be allocated before variable resolution
  // to ensure that UpdateNeedsHoleCheck() can detect import variables.
  if (is_module_scope()) AsModuleScope()->AllocateModuleVariables();
  PrivateNameScopeIterator private_name_scope_iter(this);
  if (!private_name_scope_iter.Done() &&
      !private_name_scope_iter.GetScope()->ResolvePrivateNames(info)) {
    DCHECK(info->pending_error_handler()->has_pending_error());
    return false;
  }
  if (!ResolveVariablesRecursively(info->scope())) {
    DCHECK(info->pending_error_handler()->has_pending_error());
    return false;
  }
  // Don't allocate variables of preparsed scopes.
  if (!was_lazily_parsed()) AllocateVariablesRecursively();
  return true;
}
References v8::internal::ModuleScope::AllocateModuleVariables(), v8::internal::Scope::AllocateVariablesRecursively(), v8::internal::Scope::AsModuleScope(), v8::internal::DCHECK(), v8::internal::PrivateNameScopeIterator::Done(), v8::internal::PrivateNameScopeIterator::GetScope(), v8::internal::PendingCompilationErrorHandler::has_pending_error(), v8::internal::Scope::is_module_scope(), v8::internal::ParseInfo::pending_error_handler(), v8::internal::ClassScope::ResolvePrivateNames(), v8::internal::Scope::ResolveVariablesRecursively(), and v8::internal::ParseInfo::scope().
Referenced by Analyze().
AllowsLazyCompilation()
bool v8::internal::DeclarationScope::AllowsLazyCompilation () const
Definition at line 1449 of file scopes.cc.
                                                   {
  // Functions which force eager compilation and class member initializer
  // functions are not lazily compilable.
  return !force_eager_compilation_ &&
         !IsClassMembersInitializerFunction(function_kind());
}
References v8::internal::IsClassMembersInitializerFunction().
Referenced by v8::internal::FunctionLiteral::AllowsLazyCompilation().
Analyze()
bool v8::internal::DeclarationScope::Analyze (ParseInfo * info) [static]
Definition at line 710 of file scopes.cc.
                                              {
  RCS_SCOPE(info->runtime_call_stats(),
            RuntimeCallCounterId::kCompileScopeAnalysis,
            RuntimeCallStats::kThreadSpecific);
  DCHECK_NOT_NULL(info->literal());
  DeclarationScope* scope = info->literal()->scope();
  std::optional<AllowHandleDereference> allow_deref;
#ifdef DEBUG
  if (scope->outer_scope() && !scope->outer_scope()->scope_info_.is_null()) {
    allow_deref.emplace();
  }
#endif
  if (scope->is_eval_scope() && is_sloppy(scope->language_mode())) {
    AstNodeFactory factory(info->ast_value_factory(), info->zone());
    scope->HoistSloppyBlockFunctions(&factory);
    scope->RemoveDynamic();
  }
  // We are compiling one of four cases:
  // 1) top-level code,
  // 2) a function/eval/module on the top-level
  // 4) a class member initializer function scope
  // 3) 4 function/eval in a scope that was already resolved.
  DCHECK(scope->is_script_scope() || scope->outer_scope()->is_script_scope() ||
         scope->outer_scope()->already_resolved_);
  // The outer scope is never lazy.
  scope->set_should_eager_compile();
  if (scope->must_use_preparsed_scope_data_) {
    DCHECK_EQ(scope->scope_type_, ScopeType::FUNCTION_SCOPE);
    allow_deref.emplace();
    info->consumed_preparse_data()->RestoreScopeAllocationData(
        scope, info->ast_value_factory(), info->zone());
  }
  if (!scope->AllocateVariables(info)) return false;
  scope->RewriteReplGlobalVariables();
#ifdef DEBUG
  if (v8_flags.print_scopes) {
    PrintF("Global scope:\n");
    scope->Print();
  }
  scope->CheckScopePositions();
  scope->CheckZones();
#endif
  return true;
}
References AllocateVariables(), v8::internal::ParseInfo::ast_value_factory(), v8::internal::ParseInfo::consumed_preparse_data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::FUNCTION_SCOPE, HoistSloppyBlockFunctions(), v8::internal::Scope::is_eval_scope(), v8::internal::Scope::is_script_scope(), v8::internal::is_sloppy(), v8::internal::Scope::language_mode(), v8::internal::ParseInfo::literal(), v8::internal::Scope::must_use_preparsed_scope_data_, v8::internal::Scope::outer_scope(), v8::internal::PrintF(), RCS_SCOPE, v8::internal::Scope::RemoveDynamic(), v8::internal::ConsumedPreparseData::RestoreScopeAllocationData(), v8::internal::Scope::RewriteReplGlobalVariables(), v8::internal::ParseInfo::runtime_call_stats(), v8::internal::FunctionLiteral::scope(), v8::internal::Scope::scope_info_, v8::internal::Scope::scope_type_, set_should_eager_compile(), v8::internal::v8_flags, and v8::internal::ParseInfo::zone().
Referenced by v8::internal::Parser::PostProcessParseResult().
AnalyzePartially()
void v8::internal::DeclarationScope::AnalyzePartially (Parser * parser, AstNodeFactory * ast_node_factory, bool maybe_in_arrowhead)
Definition at line 1736 of file scopes.cc.
                                                                 {
  DCHECK(!force_eager_compilation_);
  UnresolvedList new_unresolved_list;
  // We don't need to do partial analysis for top level functions, since they
  // can only access values in the global scope, and we can't track assignments
  // for these since they're accessible across scripts.
  //
  // If the top level function has inner functions though, we do still want to
  // analyze those to save their preparse data.
  //
  // Additionally, functions in potential arrowheads _need_ to be analyzed, in
  // case they do end up being in an arrowhead and the arrow function needs to
  // know about context acceses. For example, in
  //
  // (a, b=function foo(){ a = 1 }) => { b(); return a}
  //
  // `function foo(){ a = 1 }` is "maybe_in_arrowhead" but still top-level when
  // parsed, and is re-scoped to the arrow function when that one is parsed. The
  // arrow function needs to know that `a` needs to be context allocated, so
  // that the call to `b()` correctly updates the `a` parameter.
  const bool is_top_level_function = outer_scope_->is_script_scope();
  const bool has_inner_functions = preparse_data_builder_ != nullptr &&
                                   preparse_data_builder_->HasInnerFunctions();
  if (maybe_in_arrowhead || !is_top_level_function || has_inner_functions) {
    // Try to resolve unresolved variables for this Scope and migrate those
    // which cannot be resolved inside. It doesn't make sense to try to resolve
    // them in the outer Scopes here, because they are incomplete.
    Scope::AnalyzePartially(this, ast_node_factory, &new_unresolved_list,
                            maybe_in_arrowhead);
    // Migrate function_ to the right Zone.
    if (function_ != nullptr) {
      function_ = ast_node_factory->CopyVariable(function_);
    }
    SavePreparseData(parser);
  }
#ifdef DEBUG
  if (v8_flags.print_scopes) {
    PrintF("Inner function scope:\n");
    Print();
  }
#endif
  ResetAfterPreparsing(ast_node_factory->ast_value_factory(), false);
  unresolved_list_ = std::move(new_unresolved_list);
}
References v8::internal::Scope::AnalyzePartially(), v8::internal::AstNodeFactory::ast_value_factory(), v8::internal::AstNodeFactory::CopyVariable(), v8::internal::DCHECK(), v8::internal::Scope::is_script_scope(), v8::internal::Scope::outer_scope_, v8::internal::Print(), v8::internal::PrintF(), v8::internal::Scope::SavePreparseData(), v8::internal::Scope::unresolved_list_, and v8::internal::v8_flags.
Referenced by v8::internal::Parser::SkipFunction().
arguments()
Variable* v8::internal::DeclarationScope::arguments () const [inline]
Definition at line 1120 of file scopes.h.
                              {
    DCHECK_IMPLIES(is_arrow_scope(), arguments_ == nullptr);
    return arguments_;
  }
References DCHECK_IMPLIES.
Referenced by v8::internal::ScopeIterator::VisitLocals(), and v8::internal::ScopeIterator::VisitLocalScope().
CheckConflictingVarDeclarations()
Declaration * v8::internal::DeclarationScope::CheckConflictingVarDeclarations (bool * allowed_catch_binding_var_redeclaration)
Definition at line 1289 of file scopes.cc.
                                                   {
  if (has_checked_syntax_) return nullptr;
  for (Declaration* decl : decls_) {
    // Lexical vs lexical conflicts within the same scope have already been
    // captured in Parser::Declare. The only conflicts we still need to check
    // are lexical vs nested var.
    if (decl->IsVariableDeclaration() &&
        decl->AsVariableDeclaration()->AsNested() != nullptr) {
      Scope* current = decl->AsVariableDeclaration()->AsNested()->scope();
      if (decl->var()->mode() != VariableMode::kVar &&
          decl->var()->mode() != VariableMode::kDynamic)
        continue;
      // Iterate through all scopes until the declaration scope.
      do {
        // There is a conflict if there exists a non-VAR binding.
        Variable* other_var = current->LookupLocal(decl->var()->raw_name());
        if (current->is_catch_scope()) {
          *allowed_catch_binding_var_redeclaration |= other_var != nullptr;
          current = current->outer_scope();
          continue;
        }
        if (other_var != nullptr) {
          DCHECK(IsLexicalVariableMode(other_var->mode()));
          return decl;
        }
        current = current->outer_scope();
      } while (current != this);
    }
  }
  if (V8_LIKELY(!is_eval_scope())) return nullptr;
  if (!is_sloppy(language_mode())) return nullptr;
  // Var declarations in sloppy eval are hoisted to the first non-eval
  // declaration scope. Check for conflicts between the eval scope that
  // declaration scope.
  Scope* end = outer_scope()->GetNonEvalDeclarationScope()->outer_scope();
  for (Declaration* decl : decls_) {
    if (IsLexicalVariableMode(decl->var()->mode())) continue;
    Scope* current = outer_scope_;
    // Iterate through all scopes until and including the declaration scope.
    do {
      // There is a conflict if there exists a non-VAR binding up to the
      // declaration scope in which this sloppy-eval runs.
      //
      // Use the current scope as the cache. We can't use the regular cache
      // since catch scope vars don't result in conflicts, but they will mask
      // variables for regular scope resolution. We have to make sure to not put
      // masked variables in the cache used for regular lookup.
      Variable* other_var =
          current->LookupInScopeOrScopeInfo(decl->var()->raw_name(), current);
      if (other_var != nullptr && !current->is_catch_scope()) {
        // If this is a VAR, then we know that it doesn't conflict with
        // anything, so we can't conflict with anything either. The one
        // exception is the binding variable in catch scopes, which is handled
        // by the if above.
        if (!IsLexicalVariableMode(other_var->mode())) break;
        return decl;
      }
      current = current->outer_scope();
    } while (current != end);
  }
  return nullptr;
}
References v8::internal::DCHECK(), v8::internal::Scope::decls_, v8::internal::compiler::end(), v8::internal::Scope::GetNonEvalDeclarationScope(), v8::internal::Scope::is_catch_scope(), v8::internal::Scope::is_eval_scope(), v8::internal::is_sloppy(), v8::internal::IsLexicalVariableMode(), v8::internal::kDynamic, v8::internal::kVar, v8::internal::Scope::language_mode(), v8::internal::Scope::LookupInScopeOrScopeInfo(), v8::internal::Scope::LookupLocal(), v8::internal::Variable::mode(), v8::internal::Scope::outer_scope(), v8::internal::Scope::outer_scope_, and V8_LIKELY.
class_scope_has_private_brand()
bool v8::internal::DeclarationScope::class_scope_has_private_brand () const [inline]
Definition at line 1238 of file scopes.h.
                                             {
    return class_scope_has_private_brand_;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::FunctionLiteral::class_scope_has_private_brand(), and v8::internal::ScopeInfo::Create().
DeclareArguments()
void v8::internal::DeclarationScope::DeclareArguments (AstValueFactory * ast_value_factory)
Definition at line 784 of file scopes.cc.
                                                                          {
  DCHECK(is_function_scope());
  DCHECK(!is_arrow_scope());
  // Because when arguments_ is not nullptr, we already declared
  // "arguments exotic object" to add it into parameters before
  // impl()->InsertShadowingVarBindingInitializers, so here
  // only declare "arguments exotic object" when arguments_
  // is nullptr
  if (arguments_ != nullptr) {
    return;
  }
  // Declare 'arguments' variable which exists in all non arrow functions. Note
  // that it might never be accessed, in which case it won't be allocated during
  // variable allocation.
  bool was_added = false;
  arguments_ =
      Declare(zone(), ast_value_factory->arguments_string(), VariableMode::kVar,
              NORMAL_VARIABLE, kCreatedInitialized, kNotAssigned, &was_added);
  // According to ES#sec-functiondeclarationinstantiation step 18
  // we should set argumentsObjectNeeded to false if has lexical
  // declared arguments only when hasParameterExpressions is false
  if (!was_added && IsLexicalVariableMode(arguments_->mode()) &&
      has_simple_parameters_) {
    // Check if there's lexically declared variable named arguments to avoid
    // redeclaration. See ES#sec-functiondeclarationinstantiation, step 20.
    arguments_ = nullptr;
  }
}
References arguments_, v8::internal::DCHECK(), v8::internal::Scope::Declare(), has_simple_parameters_, is_arrow_scope(), v8::internal::Scope::is_function_scope(), v8::internal::IsLexicalVariableMode(), v8::internal::kCreatedInitialized, v8::internal::kNotAssigned, v8::internal::kVar, v8::internal::Variable::mode(), v8::internal::NORMAL_VARIABLE, and v8::internal::Scope::zone().
Referenced by v8::internal::ParserBase< Impl >::ParseFunctionBody(), and v8::internal::PreParser::PreParseFunction().
DeclareDefaultFunctionVariables()
void v8::internal::DeclarationScope::DeclareDefaultFunctionVariables (AstValueFactory * ast_value_factory)
Definition at line 816 of file scopes.cc.
                                        {
  DCHECK(is_function_scope());
  DCHECK(!is_arrow_scope());
  DeclareThis(ast_value_factory);
  bool was_added;
  new_target_ = Declare(zone(), ast_value_factory->new_target_string(),
                        VariableMode::kConst, NORMAL_VARIABLE,
                        kCreatedInitialized, kNotAssigned, &was_added);
  DCHECK(was_added);
  if (IsConciseMethod(function_kind_) || IsClassConstructor(function_kind_) ||
      IsAccessorFunction(function_kind_)) {
    EnsureRareData()->this_function = Declare(
        zone(), ast_value_factory->this_function_string(), VariableMode::kConst,
        NORMAL_VARIABLE, kCreatedInitialized, kNotAssigned, &was_added);
    DCHECK(was_added);
  }
}
References v8::internal::DCHECK(), v8::internal::Scope::Declare(), DeclareThis(), EnsureRareData(), function_kind_, is_arrow_scope(), v8::internal::Scope::is_function_scope(), v8::internal::IsAccessorFunction(), v8::internal::IsClassConstructor(), v8::internal::IsConciseMethod(), v8::internal::kConst, v8::internal::kCreatedInitialized, v8::internal::kNotAssigned, new_target_, v8::internal::NORMAL_VARIABLE, v8::internal::DeclarationScope::RareData::this_function, and v8::internal::Scope::zone().
DeclareDynamicGlobal()
Variable * v8::internal::DeclarationScope::DeclareDynamicGlobal (const AstRawString * name, VariableKind variable_kind, Scope * cache)
Definition at line 1259 of file scopes.cc.
                                                               {
  DCHECK(is_script_scope());
  bool was_added;
  return cache->variables_.Declare(
      zone(), this, name, VariableMode::kDynamicGlobal, kind,
      kCreatedInitialized, kNotAssigned, IsStaticFlag::kNotStatic, &was_added);
  // TODO(neis): Mark variable as maybe-assigned?
}
References v8::internal::DCHECK(), v8::internal::VariableMap::Declare(), v8::internal::Scope::is_script_scope(), v8::internal::kCreatedInitialized, v8::internal::kDynamicGlobal, v8::internal::kNotAssigned, v8::internal::kNotStatic, v8::internal::name, v8::internal::Scope::variables_, and v8::internal::Scope::zone().
Referenced by DeclarationScope(), and v8::internal::Scope::Lookup().
DeclareFunctionVar()
Variable * v8::internal::DeclarationScope::DeclareFunctionVar (const AstRawString * name, Scope * cache = nullptr)
Definition at line 837 of file scopes.cc.
                                                             {
  DCHECK(is_function_scope());
  if (cache == nullptr) {
    DCHECK_NULL(function_);
    cache = this;
  } else if (function_ != nullptr) {
    return function_;
  }
  DCHECK(this->IsOuterScopeOf(cache));
  DCHECK_NULL(cache->variables_.Lookup(name));
  VariableKind kind = is_sloppy(language_mode()) ? SLOPPY_FUNCTION_NAME_VARIABLE
                                                 : NORMAL_VARIABLE;
  function_ = zone()->New<Variable>(this, name, VariableMode::kConst, kind,
                                    kCreatedInitialized);
  if (sloppy_eval_can_extend_vars()) {
    cache->NonLocal(name, VariableMode::kDynamic);
  } else {
    cache->variables_.Add(function_);
  }
  return function_;
}
References v8::internal::VariableMap::Add(), v8::internal::DCHECK(), DCHECK_NULL, function_, v8::internal::Scope::is_function_scope(), v8::internal::is_sloppy(), v8::internal::Scope::IsOuterScopeOf(), v8::internal::kConst, v8::internal::kCreatedInitialized, v8::internal::kDynamic, v8::internal::Scope::language_mode(), v8::internal::VariableMap::Lookup(), v8::internal::name, v8::internal::Zone::New(), v8::internal::Scope::NonLocal(), v8::internal::NORMAL_VARIABLE, sloppy_eval_can_extend_vars(), v8::internal::SLOPPY_FUNCTION_NAME_VARIABLE, v8::internal::Scope::variables_, and v8::internal::Scope::zone().
Referenced by v8::internal::Parser::DeclareFunctionNameVar(), v8::internal::PreParser::DeclareFunctionNameVar(), and v8::internal::Scope::LookupInScopeInfo().
DeclareGeneratorObjectVar()
Variable * v8::internal::DeclarationScope::DeclareGeneratorObjectVar (const AstRawString * name)
Definition at line 860 of file scopes.cc.
                              {
  DCHECK(is_function_scope() || is_module_scope() || is_repl_mode_scope());
  DCHECK_NULL(generator_object_var());
  Variable* result = EnsureRareData()->generator_object =
      NewTemporary(name, kNotAssigned);
  result->set_is_used();
  return result;
}
References v8::internal::DCHECK(), DCHECK_NULL, EnsureRareData(), v8::internal::DeclarationScope::RareData::generator_object, generator_object_var(), v8::internal::Scope::is_function_scope(), v8::internal::Scope::is_module_scope(), v8::internal::Scope::is_repl_mode_scope(), v8::internal::kNotAssigned, v8::internal::name, v8::internal::Scope::NewTemporary(), and v8::base::internal::result.
DeclareParameter()
Variable * v8::internal::DeclarationScope::DeclareParameter (const AstRawString * name, VariableMode mode, bool is_optional, bool is_rest, AstValueFactory * ast_value_factory, int position)
Definition at line 1037 of file scopes.cc.
                                                           {
  DCHECK(!already_resolved_);
  DCHECK(is_function_scope() || is_module_scope());
  DCHECK(!has_rest_);
  DCHECK(!is_optional || !is_rest);
  DCHECK(!is_being_lazily_parsed_);
  DCHECK(!was_lazily_parsed_);
  Variable* var;
  if (mode == VariableMode::kTemporary) {
    var = NewTemporary(name);
  } else {
    var = LookupLocal(name);
    DCHECK_EQ(mode, VariableMode::kVar);
    DCHECK(var->is_parameter());
  }
  has_rest_ = is_rest;
  var->set_initializer_position(position);
  params_.Add(var, zone());
  if (!is_rest) ++num_parameters_;
  if (name == ast_value_factory->arguments_string()) {
    has_arguments_parameter_ = true;
  }
  // Params are automatically marked as used to make sure that the debugger and
  // function.arguments sees them.
  // TODO(verwaest): Reevaluate whether we always need to do this, since
  // strict-mode function.arguments does not make the arguments available.
  var->set_is_used();
  return var;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Scope::is_function_scope(), v8::internal::Scope::is_module_scope(), v8::internal::Variable::is_parameter(), v8::internal::kTemporary, v8::internal::kVar, v8::internal::Scope::LookupLocal(), mode(), v8::internal::name, v8::internal::Scope::NewTemporary(), v8::internal::Variable::set_initializer_position(), v8::internal::Variable::set_is_used(), and v8::internal::Scope::zone().
Referenced by v8::internal::Parser::DeclareFormalParameters(), and v8::internal::Parser::MakeAutoAccessorSetter().
DeclareSloppyBlockFunction()
void v8::internal::DeclarationScope::DeclareSloppyBlockFunction (SloppyBlockFunctionStatement * sloppy_block_function)
Definition at line 599 of file scopes.cc.
                                                         {
  sloppy_block_functions_.Add(sloppy_block_function);
}
References sloppy_block_functions_.
Referenced by v8::internal::PreParser::DeclareFunction().
DeclareThis()
void v8::internal::DeclarationScope::DeclareThis (AstValueFactory * ast_value_factory)
Definition at line 763 of file scopes.cc.
                                                                     {
  DCHECK(has_this_declaration());
  bool derived_constructor = IsDerivedConstructor(function_kind_);
  receiver_ = zone()->New<Variable>(
      this, ast_value_factory->this_string(),
      derived_constructor ? VariableMode::kConst : VariableMode::kVar,
      THIS_VARIABLE,
      derived_constructor ? kNeedsInitialization : kCreatedInitialized,
      kNotAssigned);
  // Derived constructors have hole checks when calling super. Mark the 'this'
  // variable as having hole initialization forced so that TDZ elision analysis
  // applies and numbers the variable.
  if (derived_constructor) {
    receiver_->ForceHoleInitialization(
        Variable::kHasHoleCheckUseInUnknownScope);
  }
  locals_.Add(receiver_);
}
References v8::internal::DCHECK(), v8::internal::Variable::ForceHoleInitialization(), function_kind_, has_this_declaration(), v8::internal::IsDerivedConstructor(), v8::internal::kConst, v8::internal::kCreatedInitialized, v8::internal::Variable::kHasHoleCheckUseInUnknownScope, v8::internal::kNeedsInitialization, v8::internal::kNotAssigned, v8::internal::kVar, v8::internal::Scope::locals_, v8::internal::Zone::New(), receiver_, v8::internal::THIS_VARIABLE, and v8::internal::Scope::zone().
Referenced by DeclareDefaultFunctionVariables(), and v8::internal::ModuleScope::ModuleScope().
DeserializeReceiver()
void v8::internal::DeclarationScope::DeserializeReceiver (AstValueFactory * ast_value_factory)
Definition at line 1368 of file scopes.cc.
                                                                             {
  if (is_script_scope()) {
    DCHECK_NOT_NULL(receiver_);
    return;
  }
  DCHECK(has_this_declaration());
  DeclareThis(ast_value_factory);
  if (V8_UNLIKELY(is_debug_evaluate_scope())) {
    receiver_->AllocateTo(VariableLocation::LOOKUP, -1);
  } else {
    receiver_->AllocateTo(VariableLocation::CONTEXT,
                          scope_info_->ReceiverContextSlotIndex());
  }
}
References v8::internal::CONTEXT, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Scope::is_debug_evaluate_scope(), v8::internal::Scope::is_script_scope(), v8::internal::LOOKUP, v8::internal::Scope::scope_info_, and V8_UNLIKELY.
Referenced by v8::internal::Parser::DeserializeScopeChain().
EnsureRareData()
RareData* v8::internal::DeclarationScope::EnsureRareData () [inline], [private]
Definition at line 1325 of file scopes.h.
                                       {
    if (rare_data_ == nullptr) {
      rare_data_ = zone()->New<RareData>();
    }
    return rare_data_;
  }
References v8::internal::Zone::New().
Referenced by DeclareDefaultFunctionVariables(), and DeclareGeneratorObjectVar().
ForceEagerCompilation()
void v8::internal::DeclarationScope::ForceEagerCompilation () [inline]
Definition at line 1177 of file scopes.h.
                               {
    DCHECK_EQ(this, GetClosureScope());
    DeclarationScope* s;
    for (s = this; !s->is_script_scope();
         s = s->outer_scope()->GetClosureScope()) {
      s->force_eager_compilation_ = true;
    }
    s->force_eager_compilation_ = true;
  }
References DCHECK_EQ, force_eager_compilation_, v8::internal::Scope::is_script_scope(), and v8::internal::Scope::outer_scope().
function_kind()
FunctionKind v8::internal::DeclarationScope::function_kind () const [inline]
Definition at line 873 of file scopes.h.
{ return function_kind_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildThisVariableLoad(), v8::internal::ScopeInfo::Create(), v8::internal::Parser::CreateInitializerFunction(), DeclarationScope(), v8::internal::Scope::GetHomeObjectScope(), v8::internal::FunctionLiteral::kind(), v8::internal::ParserBase< Impl >::FunctionState::kind(), v8::internal::Scope::RecordEvalCall(), and v8::internal::PreparseDataBuilder::ScopeNeedsData().
function_var()
Variable* v8::internal::DeclarationScope::function_var () const [inline]
Definition at line 1057 of file scopes.h.
{ return function_; }
Referenced by v8::internal::Scope::ContextLocalCount(), v8::internal::ScopeInfo::Create(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::PreparseDataBuilder::SaveDataForScope(), and v8::internal::ScopeIterator::VisitLocals().
generator_object_var()
Variable* v8::internal::DeclarationScope::generator_object_var () const [inline]
Definition at line 1062 of file scopes.h.
                                         {
    DCHECK(is_function_scope() || is_module_scope() || is_repl_mode_scope());
    return GetRareVariable(RareVariable::kGeneratorObject);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateTopLevelRegisters(), v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), and DeclareGeneratorObjectVar().
GetArgumentsType()
CreateArgumentsType v8::internal::DeclarationScope::GetArgumentsType () const [inline]
Definition at line 1109 of file scopes.h.
                                               {
    DCHECK(is_function_scope());
    DCHECK(!is_arrow_scope());
    DCHECK_NOT_NULL(arguments_);
    return is_sloppy(language_mode()) && has_simple_parameters()
               ? CreateArgumentsType::kMappedArguments
               : CreateArgumentsType::kUnmappedArguments;
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::is_sloppy(), v8::internal::kMappedArguments, and v8::internal::kUnmappedArguments.
GetRareVariable()
Variable* v8::internal::DeclarationScope::GetRareVariable (RareVariable id) const [inline], [private]
Definition at line 1332 of file scopes.h.
                                                             {
    if (rare_data_ == nullptr) return nullptr;
    return *reinterpret_cast<Variable**>(
        reinterpret_cast<uint8_t*>(rare_data_) + static_cast<ptrdiff_t>(id));
  }
has_checked_syntax()
bool v8::internal::DeclarationScope::has_checked_syntax () const [inline]
Definition at line 979 of file scopes.h.
{ return has_checked_syntax_; }
has_inferred_function_name()
bool v8::internal::DeclarationScope::has_inferred_function_name () const [inline]
Definition at line 1202 of file scopes.h.
                                          {
    return has_inferred_function_name_;
  }
has_simple_parameters()
bool v8::internal::DeclarationScope::has_simple_parameters () const [inline]
Definition at line 1087 of file scopes.h.
{ return has_simple_parameters_; }
Referenced by v8::internal::ScopeInfo::Create(), v8::internal::Parser::DeclareArrowFunctionFormalParameters(), v8::internal::Scope::HasSimpleParameters(), v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), and v8::internal::PreParser::PreParseFunction().
has_this_declaration()
bool v8::internal::DeclarationScope::has_this_declaration () const [inline]
Definition at line 1050 of file scopes.h.
{ return has_this_declaration_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization(), v8::internal::ScopeIterator::ClosureScopeHasThisReference(), v8::internal::ScopeInfo::Create(), DeclareThis(), v8::internal::Scope::GetReceiverScope(), v8::internal::ScopeIterator::VisitLocals(), and v8::internal::ScopeIterator::VisitLocalScope().
has_this_reference()
bool v8::internal::DeclarationScope::has_this_reference () const [inline]
Definition at line 1224 of file scopes.h.
{ return has_this_reference_; }
HoistSloppyBlockFunctions()
void v8::internal::DeclarationScope::HoistSloppyBlockFunctions (AstNodeFactory * factory)
Definition at line 604 of file scopes.cc.
                                                                        {
  DCHECK(is_sloppy(language_mode()));
  DCHECK(is_function_scope() || is_eval_scope() || is_script_scope() ||
         (is_block_scope() && outer_scope()->is_function_scope()));
  DCHECK(HasSimpleParameters() || is_block_scope() || is_being_lazily_parsed_);
  DCHECK_EQ(factory == nullptr, is_being_lazily_parsed_);
  if (sloppy_block_functions_.is_empty()) return;
  // In case of complex parameters the current scope is the body scope and the
  // parameters are stored in the outer scope.
  Scope* parameter_scope = HasSimpleParameters() ? this : outer_scope_;
  DCHECK(parameter_scope->is_function_scope() || is_eval_scope() ||
         is_script_scope());
  DeclarationScope* decl_scope = GetNonEvalDeclarationScope();
  Scope* outer_scope = decl_scope->outer_scope();
  // For each variable which is used as a function declaration in a sloppy
  // block,
  for (SloppyBlockFunctionStatement* sloppy_block_function :
       sloppy_block_functions_) {
    const AstRawString* name = sloppy_block_function->name();
    // If the variable wouldn't conflict with a lexical declaration
    // or parameter,
    // Check if there's a conflict with a parameter.
    Variable* maybe_parameter = parameter_scope->LookupLocal(name);
    if (maybe_parameter != nullptr && maybe_parameter->is_parameter()) {
      continue;
    }
    // Check if there's a conflict with a lexical declaration
    Scope* query_scope = sloppy_block_function->scope()->outer_scope();
    bool should_hoist = true;
    // It is not sufficient to just do a Lookup on query_scope: for
    // example, that does not prevent hoisting of the function in
    // `{ let e; try {} catch (e) { function e(){} } }`
    //
    // Don't use a generic cache scope, as the cache scope would be the outer
    // scope and we terminate the iteration there anyway.
    do {
      Variable* var = query_scope->LookupInScopeOrScopeInfo(name, query_scope);
      if (var != nullptr && IsLexicalVariableMode(var->mode()) &&
          !var->is_sloppy_block_function()) {
        should_hoist = false;
        break;
      }
      query_scope = query_scope->outer_scope();
    } while (query_scope != outer_scope);
    if (!should_hoist) continue;
    if (factory) {
      DCHECK(!is_being_lazily_parsed_);
      int pos = sloppy_block_function->position();
      bool ok = true;
      bool was_added;
      auto declaration = factory->NewVariableDeclaration(pos);
      // Based on the preceding checks, it doesn't matter what we pass as
      // sloppy_mode_block_scope_function_redefinition.
      //
      // This synthesized var for Annex B functions-in-block (FiB) may be
      // declared multiple times for the same var scope, such as in the case of
      // shadowed functions-in-block like the following:
      //
      // {
      // function f() {}
      // { function f() {} }
      // }
      //
      // Redeclarations for vars do not create new bindings, but the
      // redeclarations' initializers are still run. That is, shadowed FiB will
      // result in multiple assignments to the same synthesized var.
      Variable* var = DeclareVariable(
          declaration, name, pos, VariableMode::kVar, NORMAL_VARIABLE,
          Variable::DefaultInitializationFlag(VariableMode::kVar), &was_added,
          nullptr, &ok);
      DCHECK(ok);
      VariableProxy* source =
          factory->NewVariableProxy(sloppy_block_function->var());
      VariableProxy* target = factory->NewVariableProxy(var);
      Assignment* assignment = factory->NewAssignment(
          sloppy_block_function->init(), target, source, pos);
      assignment->set_lookup_hoisting_mode(LookupHoistingMode::kLegacySloppy);
      Statement* statement = factory->NewExpressionStatement(assignment, pos);
      sloppy_block_function->set_statement(statement);
    } else {
      DCHECK(is_being_lazily_parsed_);
      bool was_added;
      Variable* var = DeclareVariableName(name, VariableMode::kVar, &was_added);
      if (sloppy_block_function->init() == Token::kAssign) {
        var->SetMaybeAssigned();
      }
    }
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Scope::DeclareVariable(), v8::internal::Scope::DeclareVariableName(), v8::internal::Variable::DefaultInitializationFlag(), v8::internal::Scope::GetNonEvalDeclarationScope(), v8::internal::Scope::HasSimpleParameters(), v8::internal::Scope::is_block_scope(), v8::internal::Scope::is_eval_scope(), v8::internal::Scope::is_function_scope(), v8::internal::Variable::is_parameter(), v8::internal::Scope::is_script_scope(), v8::internal::is_sloppy(), v8::internal::Variable::is_sloppy_block_function(), v8::internal::IsLexicalVariableMode(), v8::internal::kLegacySloppy, v8::internal::kVar, v8::internal::Scope::language_mode(), v8::internal::Scope::LookupInScopeOrScopeInfo(), v8::internal::Scope::LookupLocal(), v8::internal::Variable::mode(), v8::internal::name, v8::internal::AstNodeFactory::NewAssignment(), v8::internal::AstNodeFactory::NewExpressionStatement(), v8::internal::AstNodeFactory::NewVariableDeclaration(), v8::internal::AstNodeFactory::NewVariableProxy(), v8::internal::NORMAL_VARIABLE, v8::internal::Scope::outer_scope(), v8::internal::Scope::outer_scope_, v8::internal::Assignment::set_lookup_hoisting_mode(), v8::internal::Variable::SetMaybeAssigned(), sloppy_block_functions_, and v8::internal::this.
Referenced by Analyze(), v8::internal::Parser::InsertSloppyBlockFunctionVarBindings(), and v8::internal::PreParser::PreParseFunction().
is_arrow_scope()
bool v8::internal::DeclarationScope::is_arrow_scope () const [inline]
Definition at line 890 of file scopes.h.
                              {
    return is_function_scope() && IsArrowFunction(function_kind_);
  }
References v8::internal::IsArrowFunction().
Referenced by v8::internal::Scope::AnalyzePartially(), DeclareArguments(), DeclareDefaultFunctionVariables(), v8::internal::Scope::IsSkippableFunctionScope(), v8::internal::Scope::RecordEvalCall(), SetDefaults(), and v8::internal::ScopeIterator::VisitLocalScope().
is_skipped_function()
bool v8::internal::DeclarationScope::is_skipped_function () const [inline]
Definition at line 1197 of file scopes.h.
{ return is_skipped_function_; }
Referenced by v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
LookupInModule()
Variable* v8::internal::DeclarationScope::LookupInModule (const AstRawString * name) [inline]
Definition at line 943 of file scopes.h.
                                                     {
    DCHECK(is_module_scope());
    Variable* var = variables_.Lookup(name);
    DCHECK_NOT_NULL(var);
    return var;
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports().
MakeParametersNonSimple()
void v8::internal::DeclarationScope::MakeParametersNonSimple () [inline]
Definition at line 1099 of file scopes.h.
                                 {
    SetHasNonSimpleParameters();
    for (ZoneHashMap::Entry* p = variables_.Start(); p != nullptr;
         p = variables_.Next(p)) {
      Variable* var = reinterpret_cast<Variable*>(p->value);
      if (var->is_parameter()) var->MakeParameterNonSimple();
    }
  }
References v8::internal::Variable::is_parameter(), and v8::internal::Variable::MakeParameterNonSimple().
Referenced by v8::internal::Parser::DeclareFormalParameters().
needs_private_name_context_chain_recalc()
bool v8::internal::DeclarationScope::needs_private_name_context_chain_recalc () const [inline]
Definition at line 1230 of file scopes.h.
                                                       {
    return needs_private_name_context_chain_recalc_;
  }
Referenced by AllocateScopeInfos(), and v8::internal::PreparseDataBuilder::SaveDataForScope().
new_target_var()
Variable* v8::internal::DeclarationScope::new_target_var () [inline]
Definition at line 1053 of file scopes.h.
{ return new_target_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateTopLevelRegisters(), and v8::internal::ScopeInfo::Create().
NullifyRareVariableIf()
template<typename Predicate >
void v8::internal::DeclarationScope::NullifyRareVariableIf (RareVariable id, Predicate predicate) [inline], [private]
Definition at line 1341 of file scopes.h.
                                                                             {
    if (V8_LIKELY(rare_data_ == nullptr)) return;
    Variable** var = reinterpret_cast<Variable**>(
        reinterpret_cast<uint8_t*>(rare_data_) + static_cast<ptrdiff_t>(id));
    if (*var && predicate(*var)) *var = nullptr;
  }
References V8_LIKELY.
num_parameters()
int v8::internal::DeclarationScope::num_parameters () const [inline]
Definition at line 1080 of file scopes.h.
{ return num_parameters_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization(), v8::internal::ScopeInfo::Create(), v8::internal::UnoptimizedCompilationInfo::num_parameters(), v8::internal::UnoptimizedCompilationInfo::num_parameters_including_this(), and v8::internal::PreparseDataBuilder::SaveDataForSkippableFunction().
parameter()
Variable* v8::internal::DeclarationScope::parameter (int index) const [inline]
Definition at line 1069 of file scopes.h.
                                       {
    DCHECK(is_function_scope() || is_module_scope());
    DCHECK(!is_being_lazily_parsed_);
    return params_[index];
  }
References v8::internal::DCHECK(), and v8::internal::index.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization(), v8::internal::Parser::BuildParameterInitializationBlock(), and v8::internal::ScopeInfo::Create().
preparse_data_builder()
PreparseDataBuilder* v8::internal::DeclarationScope::preparse_data_builder () const [inline]
Definition at line 1219 of file scopes.h.
                                                     {
    return preparse_data_builder_;
  }
Referenced by v8::internal::Scope::IsSkippableFunctionScope().
RecalcPrivateNameContextChain()
void v8::internal::DeclarationScope::RecalcPrivateNameContextChain () [private]
Referenced by AllocateScopeInfos().
receiver()
Variable* v8::internal::DeclarationScope::receiver () [inline]
Definition at line 1044 of file scopes.h.
                       {
    DCHECK(has_this_declaration() || is_script_scope());
    DCHECK_NOT_NULL(receiver_);
    return receiver_;
  }
References v8::internal::DCHECK(), and DCHECK_NOT_NULL.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildThisVariableLoad(), v8::internal::ScopeInfo::Create(), v8::internal::ParserBase< Impl >::UseThis(), and v8::internal::ScopeIterator::VisitLocals().
RecordDeclarationScopeEvalCall()
void v8::internal::DeclarationScope::RecordDeclarationScopeEvalCall () [inline]
Definition at line 896 of file scopes.h.
                                        {
    calls_eval_ = true;
    // The caller already checked whether we're in sloppy mode.
    CHECK(is_sloppy(language_mode()));
    // Sloppy eval in script scopes can only introduce global variables anyway,
    // so we don't care that it calls sloppy eval.
    if (is_script_scope()) return;
    // Sloppy eval in an eval scope can only introduce variables into the outer
    // (non-eval) declaration scope, not into this eval scope.
    if (is_eval_scope()) {
#ifdef DEBUG
      // One of three things must be true:
      // 1. The outer non-eval declaration scope should already be marked as
      // being extendable by sloppy eval, by the current sloppy eval rather
      // than the inner one,
      // 2. The outer non-eval declaration scope is a script scope and thus
      // isn't extendable anyway, or
      // 3. This is a debug evaluate and all bets are off.
      DeclarationScope* outer_decl_scope = outer_scope()->GetDeclarationScope();
      while (outer_decl_scope->is_eval_scope()) {
        outer_decl_scope = outer_decl_scope->GetDeclarationScope();
      }
      if (V8_UNLIKELY(outer_decl_scope->is_debug_evaluate_scope())) {
        // Don't check anything.
        // TODO(9662): Figure out where variables declared by an eval inside a
        // debug-evaluate actually go.
      } else if (!outer_decl_scope->is_script_scope()) {
        DCHECK(outer_decl_scope->sloppy_eval_can_extend_vars_);
      }
#endif
      return;
    }
    is_dynamic_scope_ = true;
    sloppy_eval_can_extend_vars_ = true;
  }
References CHECK, v8::internal::DCHECK(), v8::internal::Scope::GetDeclarationScope(), v8::internal::Scope::is_debug_evaluate_scope(), v8::internal::Scope::is_eval_scope(), v8::internal::Scope::is_script_scope(), v8::internal::is_sloppy(), v8::internal::Scope::sloppy_eval_can_extend_vars_, and V8_UNLIKELY.
Referenced by v8::internal::Scope::RecordEvalCall().
RecordNeedsPrivateNameContextChainRecalc()
void v8::internal::DeclarationScope::RecordNeedsPrivateNameContextChainRecalc ()
Definition at line 2759 of file scopes.cc.
                                                                {
  DCHECK_EQ(GetClosureScope(), this);
  DeclarationScope* scope;
  for (scope = this; scope != nullptr;
       scope = scope->outer_scope() != nullptr
                   ? scope->outer_scope()->GetClosureScope()
                   : nullptr) {
    if (scope->needs_private_name_context_chain_recalc_) return;
    scope->needs_private_name_context_chain_recalc_ = true;
  }
}
References DCHECK_EQ, v8::internal::Scope::GetClosureScope(), needs_private_name_context_chain_recalc_, and v8::internal::Scope::outer_scope().
Referenced by v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), and v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
RecordParameter()
void v8::internal::DeclarationScope::RecordParameter (bool is_rest)
Definition at line 1071 of file scopes.cc.
                                                   {
  DCHECK(!already_resolved_);
  DCHECK(is_function_scope() || is_module_scope());
  DCHECK(is_being_lazily_parsed_);
  DCHECK(!has_rest_);
  has_rest_ = is_rest;
  if (!is_rest) ++num_parameters_;
}
References v8::internal::DCHECK(), v8::internal::Scope::is_function_scope(), and v8::internal::Scope::is_module_scope().
RecordSuperPropertyUsage()
void v8::internal::DeclarationScope::RecordSuperPropertyUsage () [inline]
Definition at line 876 of file scopes.h.
                                  {
    DCHECK(IsConciseMethod(function_kind()) ||
           IsAccessorFunction(function_kind()) ||
           IsClassConstructor(function_kind()));
    uses_super_property_ = true;
    Scope* home_object_scope = GetHomeObjectScope();
    DCHECK_NOT_NULL(home_object_scope);
    home_object_scope->set_needs_home_object();
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::IsAccessorFunction(), v8::internal::IsClassConstructor(), v8::internal::IsConciseMethod(), and v8::internal::Scope::set_needs_home_object().
Referenced by v8::internal::Scope::RecordEvalCall(), and v8::internal::Parser::SkipFunction().
ResetAfterPreparsing()
void v8::internal::DeclarationScope::ResetAfterPreparsing (AstValueFactory * ast_value_factory, bool aborted)
Definition at line 1665 of file scopes.cc.
                                                          {
  DCHECK(is_function_scope());
  // Reset all non-trivial members.
  params_.DropAndClear();
  num_parameters_ = 0;
  decls_.Clear();
  locals_.Clear();
  inner_scope_ = nullptr;
  unresolved_list_.Clear();
  sloppy_block_functions_.Clear();
  rare_data_ = nullptr;
  has_rest_ = false;
  function_ = nullptr;
  DCHECK_NE(zone(), ast_value_factory->single_parse_zone());
  // Make sure this scope and zone aren't used for allocation anymore.
  {
    // Get the zone, while variables_ is still valid
    Zone* zone = this->zone();
    variables_.Invalidate();
    zone->Reset();
  }
  if (aborted) {
    // Prepare scope for use in the outer zone.
    variables_ = VariableMap(ast_value_factory->single_parse_zone());
    if (!IsArrowFunction(function_kind_)) {
      has_simple_parameters_ = true;
      DeclareDefaultFunctionVariables(ast_value_factory);
    }
  }
#ifdef DEBUG
  needs_migration_ = false;
  is_being_lazily_parsed_ = false;
#endif
  was_lazily_parsed_ = !aborted;
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::Scope::decls_, v8::internal::Scope::inner_scope_, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Invalidate(), v8::internal::Scope::is_function_scope(), v8::internal::IsArrowFunction(), v8::internal::Scope::locals_, v8::internal::Zone::Reset(), v8::internal::AstValueFactory::single_parse_zone(), v8::internal::Scope::unresolved_list_, v8::internal::Scope::variables_, and v8::internal::Scope::zone().
Referenced by v8::internal::Parser::SkipFunction().
rest_parameter()
Variable* v8::internal::DeclarationScope::rest_parameter () const [inline]
Definition at line 1083 of file scopes.h.
                                   {
    return has_rest_ ? params_[params_.length() - 1] : nullptr;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBodyPrologue().
SavePreparseDataForDeclarationScope()
void v8::internal::DeclarationScope::SavePreparseDataForDeclarationScope (Parser * parser)
Definition at line 1731 of file scopes.cc.
                                                                         {
  if (preparse_data_builder_ == nullptr) return;
  preparse_data_builder_->SaveScopeAllocationData(this, parser);
}
set_class_scope_has_private_brand()
void v8::internal::DeclarationScope::set_class_scope_has_private_brand (bool value) [inline]
Definition at line 1235 of file scopes.h.
                                                     {
    class_scope_has_private_brand_ = value;
  }
References v8::internal::value.
Referenced by v8::internal::FunctionLiteral::set_class_scope_has_private_brand().
set_has_checked_syntax()
void v8::internal::DeclarationScope::set_has_checked_syntax (bool has_checked_syntax) [inline]
Definition at line 976 of file scopes.h.
                                                       {
    has_checked_syntax_ = has_checked_syntax;
  }
Referenced by v8::internal::Parser::DoParseFunction().
set_has_inferred_function_name()
void v8::internal::DeclarationScope::set_has_inferred_function_name (bool value) [inline]
Definition at line 1205 of file scopes.h.
                                                  {
    DCHECK(is_function_scope());
    has_inferred_function_name_ = value;
  }
References v8::internal::DCHECK(), and v8::internal::value.
Referenced by v8::internal::FunctionLiteral::set_raw_inferred_name().
set_has_this_reference()
void v8::internal::DeclarationScope::set_has_this_reference () [inline]
Definition at line 1223 of file scopes.h.
{ has_this_reference_ = true; }
Referenced by v8::internal::ParserBase< Impl >::UseThis().
set_is_skipped_function()
void v8::internal::DeclarationScope::set_is_skipped_function (bool is_skipped_function) [inline]
Definition at line 1198 of file scopes.h.
                                                         {
    is_skipped_function_ = is_skipped_function;
  }
Referenced by v8::internal::Parser::SkipFunction().
set_module_has_toplevel_await()
void v8::internal::DeclarationScope::set_module_has_toplevel_await () [inline]
Definition at line 1002 of file scopes.h.
                                       {
    DCHECK(IsModule(function_kind_));
    function_kind_ = FunctionKind::kModuleWithTopLevelAwait;
  }
References v8::internal::DCHECK(), v8::internal::IsModule(), and v8::internal::kModuleWithTopLevelAwait.
Referenced by v8::internal::Parser::DoParseProgram().
set_preparse_data_builder()
void v8::internal::DeclarationScope::set_preparse_data_builder (PreparseDataBuilder * preparse_data_builder) [inline]
Definition at line 1215 of file scopes.h.
                                                                             {
    preparse_data_builder_ = preparse_data_builder;
  }
Referenced by v8::internal::PreparseDataBuilder::DataGatheringScope::Start().
set_should_eager_compile()
void v8::internal::DeclarationScope::set_should_eager_compile ()
Definition at line 405 of file scopes.cc.
                                                {
  should_eager_compile_ = !was_lazily_parsed_;
}
References should_eager_compile_, and was_lazily_parsed_.
Referenced by Analyze(), and v8::internal::FunctionLiteral::SetShouldEagerCompile().
set_zone()
void v8::internal::DeclarationScope::set_zone (Zone * zone) [inline]
Definition at line 959 of file scopes.h.
                            {
#ifdef DEBUG
    needs_migration_ = true;
#endif
    // Migrate variables_' backing store to new zone.
    variables_ = VariableMap(variables_, zone);
  }
Referenced by v8::internal::Parser::SkipFunction().
SetDefaults()
void v8::internal::DeclarationScope::SetDefaults () [private]
Definition at line 321 of file scopes.cc.
                                   {
  is_declaration_scope_ = true;
  has_simple_parameters_ = true;
#if V8_ENABLE_WEBASSEMBLY
  is_asm_module_ = false;
#endif // V8_ENABLE_WEBASSEMBLY
  force_eager_compilation_ = false;
  has_arguments_parameter_ = false;
  uses_super_property_ = false;
  has_checked_syntax_ = false;
  has_this_reference_ = false;
  has_this_declaration_ =
      (is_function_scope() && !is_arrow_scope()) || is_module_scope();
  needs_private_name_context_chain_recalc_ = false;
  has_rest_ = false;
  receiver_ = nullptr;
  new_target_ = nullptr;
  function_ = nullptr;
  arguments_ = nullptr;
  rare_data_ = nullptr;
  should_eager_compile_ = false;
  was_lazily_parsed_ = false;
  is_skipped_function_ = false;
  preparse_data_builder_ = nullptr;
  class_scope_has_private_brand_ = false;
#ifdef DEBUG
  DeclarationScope* outer_declaration_scope =
      outer_scope_ ? outer_scope_->GetDeclarationScope() : nullptr;
  is_being_lazily_parsed_ =
      outer_declaration_scope ? outer_declaration_scope->is_being_lazily_parsed_
                              : false;
#endif
}
References arguments_, class_scope_has_private_brand_, force_eager_compilation_, function_, v8::internal::Scope::GetDeclarationScope(), has_arguments_parameter_, has_checked_syntax_, has_rest_, has_simple_parameters_, has_this_declaration_, has_this_reference_, is_arrow_scope(), v8::internal::Scope::is_declaration_scope_, v8::internal::Scope::is_function_scope(), v8::internal::Scope::is_module_scope(), is_skipped_function_, needs_private_name_context_chain_recalc_, new_target_, v8::internal::Scope::outer_scope_, preparse_data_builder_, rare_data_, receiver_, should_eager_compile_, uses_super_property_, and was_lazily_parsed_.
Referenced by DeclarationScope().
SetHasNonSimpleParameters()
void v8::internal::DeclarationScope::SetHasNonSimpleParameters () [inline]
Definition at line 1094 of file scopes.h.
                                   {
    DCHECK(is_function_scope());
    has_simple_parameters_ = false;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::PreParser::DeclareFormalParameters(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
SetScriptScopeInfo()
void v8::internal::DeclarationScope::SetScriptScopeInfo (Handle< ScopeInfo > scope_info) [inline]
Definition at line 987 of file scopes.h.
                                                        {
    DCHECK(is_script_scope());
    DCHECK(scope_info_.is_null());
    scope_info_ = scope_info;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Scope::DeserializeScopeChain(), and v8::internal::Scope::SetScriptScopeInfo().
should_ban_arguments()
bool v8::internal::DeclarationScope::should_ban_arguments () const [inline]
Definition at line 998 of file scopes.h.
                                    {
    return IsClassMembersInitializerFunction(function_kind());
  }
References v8::internal::IsClassMembersInitializerFunction().
Referenced by v8::internal::Scope::ShouldBanArguments().
ShouldEagerCompile()
bool v8::internal::DeclarationScope::ShouldEagerCompile () const [inline]
Definition at line 981 of file scopes.h.
                                  {
    return force_eager_compilation_ || should_eager_compile_;
  }
Referenced by v8::internal::FunctionLiteral::ShouldEagerCompile().
sloppy_eval_can_extend_vars()
bool v8::internal::DeclarationScope::sloppy_eval_can_extend_vars () const [inline]
Definition at line 937 of file scopes.h.
                                           {
    return sloppy_eval_can_extend_vars_;
  }
Referenced by v8::internal::Scope::AllocateVariablesRecursively(), v8::internal::ScopeInfo::Create(), DeclareFunctionVar(), v8::internal::Scope::Lookup(), v8::internal::Scope::LookupSloppyEval(), and v8::internal::PreparseDataBuilder::SaveDataForScope().
TakeUnresolvedReferencesFromParent()
void v8::internal::DeclarationScope::TakeUnresolvedReferencesFromParent ()
Definition at line 704 of file scopes.cc.
                                                          {
  DCHECK(outer_scope_->reparsing_for_class_initializer_);
  unresolved_list_.MoveTail(&outer_scope_->unresolved_list_,
                            outer_scope_->unresolved_list_.begin());
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), v8::internal::DCHECK(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::MoveTail(), v8::internal::Scope::outer_scope_, and v8::internal::Scope::unresolved_list_.
Referenced by v8::internal::Parser::ParseClassForMemberInitialization().
this_function_var()
Variable* v8::internal::DeclarationScope::this_function_var () const [inline]
Definition at line 1125 of file scopes.h.
                                      {
    Variable* this_function = GetRareVariable(RareVariable::kThisFunction);
    // This is only used in derived constructors atm.
    DCHECK(this_function == nullptr ||
           (is_function_scope() && (IsClassConstructor(function_kind()) ||
                                    IsConciseMethod(function_kind()) ||
                                    IsAccessorFunction(function_kind()))));
    return this_function;
  }
References v8::internal::DCHECK(), v8::internal::IsAccessorFunction(), v8::internal::IsClassConstructor(), and v8::internal::IsConciseMethod().
uses_super_property()
bool v8::internal::DeclarationScope::uses_super_property () const [inline]
Definition at line 886 of file scopes.h.
{ return uses_super_property_; }
Referenced by v8::internal::PreparseDataBuilder::SaveDataForSkippableFunction().
UsesThis()
void v8::internal::DeclarationScope::UsesThis () [inline]
Definition at line 1225 of file scopes.h.
                  {
    set_has_this_reference();
    GetReceiverScope()->receiver()->ForceContextAllocation();
  }
was_lazily_parsed()
bool v8::internal::DeclarationScope::was_lazily_parsed () const [inline]
Definition at line 941 of file scopes.h.
{ return was_lazily_parsed_; }
Referenced by v8::internal::Scope::SavePreparseData(), and v8::internal::anonymous_namespace{scopes.cc}::WasLazilyParsed().
Member Data Documentation
arguments_
Variable* v8::internal::DeclarationScope::arguments_ [private]
Definition at line 1306 of file scopes.h.
Referenced by DeclareArguments(), and SetDefaults().
class_scope_has_private_brand_
bool v8::internal::DeclarationScope::class_scope_has_private_brand_ [private]
Definition at line 1289 of file scopes.h.
Referenced by DeclarationScope(), and SetDefaults().
force_eager_compilation_
bool v8::internal::DeclarationScope::force_eager_compilation_ [private]
Definition at line 1270 of file scopes.h.
Referenced by ForceEagerCompilation(), and SetDefaults().
function_
Variable* v8::internal::DeclarationScope::function_ [private]
Definition at line 1302 of file scopes.h.
Referenced by DeclareFunctionVar(), and SetDefaults().
function_kind_
FunctionKind v8::internal::DeclarationScope::function_kind_ [private]
Definition at line 1291 of file scopes.h.
Referenced by DeclareDefaultFunctionVariables(), and DeclareThis().
has_arguments_parameter_
bool v8::internal::DeclarationScope::has_arguments_parameter_ [private]
Definition at line 1274 of file scopes.h.
Referenced by SetDefaults().
has_checked_syntax_
bool v8::internal::DeclarationScope::has_checked_syntax_ [private]
Definition at line 1285 of file scopes.h.
Referenced by SetDefaults().
has_inferred_function_name_
bool v8::internal::DeclarationScope::has_inferred_function_name_ [private]
Definition at line 1284 of file scopes.h.
has_rest_
bool v8::internal::DeclarationScope::has_rest_ [private]
Definition at line 1272 of file scopes.h.
Referenced by SetDefaults().
has_simple_parameters_
bool v8::internal::DeclarationScope::has_simple_parameters_ [private]
Definition at line 1265 of file scopes.h.
Referenced by DeclareArguments(), and SetDefaults().
has_this_declaration_
bool v8::internal::DeclarationScope::has_this_declaration_ [private]
Definition at line 1287 of file scopes.h.
Referenced by SetDefaults().
has_this_reference_
bool v8::internal::DeclarationScope::has_this_reference_ [private]
Definition at line 1286 of file scopes.h.
Referenced by SetDefaults().
is_skipped_function_
bool v8::internal::DeclarationScope::is_skipped_function_ [private]
Definition at line 1283 of file scopes.h.
Referenced by SetDefaults().
needs_private_name_context_chain_recalc_
bool v8::internal::DeclarationScope::needs_private_name_context_chain_recalc_ [private]
Definition at line 1288 of file scopes.h.
Referenced by RecordNeedsPrivateNameContextChainRecalc(), and SetDefaults().
new_target_
Variable* v8::internal::DeclarationScope::new_target_ [private]
Definition at line 1304 of file scopes.h.
Referenced by DeclareDefaultFunctionVariables(), and SetDefaults().
num_parameters_
int v8::internal::DeclarationScope::num_parameters_ = 0 [private]
Definition at line 1293 of file scopes.h.
params_
ZonePtrList<Variable> v8::internal::DeclarationScope::params_ [private]
Definition at line 1296 of file scopes.h.
preparse_data_builder_
PreparseDataBuilder* v8::internal::DeclarationScope::preparse_data_builder_ [private]
Definition at line 1309 of file scopes.h.
Referenced by SetDefaults().
rare_data_
RareData* v8::internal::DeclarationScope::rare_data_ = nullptr [private]
Definition at line 1348 of file scopes.h.
Referenced by SetDefaults().
receiver_
Variable* v8::internal::DeclarationScope::receiver_ [private]
Definition at line 1300 of file scopes.h.
Referenced by DeclarationScope(), DeclareThis(), and SetDefaults().
should_eager_compile_
bool v8::internal::DeclarationScope::should_eager_compile_ [private]
Definition at line 1277 of file scopes.h.
Referenced by set_should_eager_compile(), and SetDefaults().
sloppy_block_functions_
base::ThreadedList<SloppyBlockFunctionStatement> v8::internal::DeclarationScope::sloppy_block_functions_ [private]
Definition at line 1298 of file scopes.h.
Referenced by DeclareSloppyBlockFunction(), and HoistSloppyBlockFunctions().
uses_super_property_
bool v8::internal::DeclarationScope::uses_super_property_ [private]
Definition at line 1276 of file scopes.h.
Referenced by SetDefaults().
was_lazily_parsed_
bool v8::internal::DeclarationScope::was_lazily_parsed_ [private]
Definition at line 1279 of file scopes.h.
Referenced by set_should_eager_compile(), and SetDefaults().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/scopes.h
/mnt/V8SourceCode/src/ast/scopes.cc