v8::internal::SemiSpaceObjectIterator Class Reference
#include <new-spaces.h>
Public Member Functions
SemiSpaceObjectIterator (const SemiSpaceNewSpace *space)
Tagged< HeapObject > Next () final
Private Attributes
Address current_
Additional Inherited Members
Detailed Description
Definition at line 178 of file new-spaces.h.
Constructor & Destructor Documentation
SemiSpaceObjectIterator()
v8::internal::SemiSpaceObjectIterator::SemiSpaceObjectIterator (const SemiSpaceNewSpace * space) [inline], [explicit]
Definition at line 64 of file new-spaces-inl.h.
    : current_(space->first_allocatable_address()) {}
Member Function Documentation
Next()
Tagged< HeapObject > v8::internal::SemiSpaceObjectIterator::Next () [inline], [final], [virtual]
Implements v8::internal::ObjectIterator.
Definition at line 67 of file new-spaces-inl.h.
                                                 {
  if (!current_) return {};
  while (true) {
    if (PageMetadata::IsAlignedToPageSize(current_)) {
      PageMetadata* page = PageMetadata::FromAllocationAreaAddress(current_);
      page = page->next_page();
      if (page == nullptr) return {};
      current_ = page->area_start();
    }
    Tagged<HeapObject> object = HeapObject::FromAddress(current_);
    current_ += ALIGN_TO_ALLOCATION_ALIGNMENT(object->Size());
    if (!IsFreeSpaceOrFiller(object)) return object;
  }
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::MemoryChunkMetadata::area_start(), current_, v8::internal::HeapObject::FromAddress(), v8::internal::PageMetadata::FromAllocationAreaAddress(), v8::internal::PageMetadata::IsAlignedToPageSize(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), and v8::internal::PageMetadata::next_page().
Member Data Documentation
current_
Address v8::internal::SemiSpaceObjectIterator::current_ [private]
Definition at line 187 of file new-spaces.h.
Referenced by Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/new-spaces.h
/mnt/V8SourceCode/src/heap/new-spaces-inl.h