v8::internal::maglev::CompactInterpreterFrameState Class Reference
#include <maglev-interpreter-frame-state.h>
Public Member Functions
CompactInterpreterFrameState (const MaglevCompilationUnit &info, const compiler::BytecodeLivenessState *liveness)
CompactInterpreterFrameState (const MaglevCompilationUnit &info, const compiler::BytecodeLivenessState *liveness, const InterpreterFrameState &state)
CompactInterpreterFrameState (const CompactInterpreterFrameState &)=delete
CompactInterpreterFrameState (CompactInterpreterFrameState &&)=delete
CompactInterpreterFrameState & operator= (const CompactInterpreterFrameState &)=delete
CompactInterpreterFrameState & operator= (CompactInterpreterFrameState &&)=delete
template<typename Function >
void ForEachParameter (const MaglevCompilationUnit &info, Function &&f) const
template<typename Function >
void ForEachParameter (const MaglevCompilationUnit &info, Function &&f)
template<typename Function >
void ForEachLocal (const MaglevCompilationUnit &info, Function &&f) const
template<typename Function >
void ForEachLocal (const MaglevCompilationUnit &info, Function &&f)
template<typename Function >
void ForEachRegister (const MaglevCompilationUnit &info, Function &&f)
template<typename Function >
void ForEachRegister (const MaglevCompilationUnit &info, Function &&f) const
template<typename Function >
void ForEachValue (const MaglevCompilationUnit &info, Function &&f)
template<typename Function >
void ForEachValue (const MaglevCompilationUnit &info, Function &&f) const
const compiler::BytecodeLivenessState * liveness () const
ValueNode *& accumulator (const MaglevCompilationUnit &info)
ValueNode *& accumulator (const MaglevCompilationUnit &info) const
ValueNode *& context (const MaglevCompilationUnit &info)
ValueNode *& context (const MaglevCompilationUnit &info) const
ValueNode * GetValueOf (interpreter::Register reg, const MaglevCompilationUnit &info) const
size_t size (const MaglevCompilationUnit &info) const
const VirtualObjectList & virtual_objects () const
VirtualObjectList & virtual_objects ()
void set_virtual_objects (const VirtualObjectList &vos)
Static Private Member Functions
static size_t SizeFor (const MaglevCompilationUnit &info, const compiler::BytecodeLivenessState *liveness)
Private Attributes
ValueNode **const live_registers_and_accumulator_
const compiler::BytecodeLivenessState *const liveness_
VirtualObjectList virtual_objects_
Static Private Attributes
static const int context_register_count_ = 1
Detailed Description
Definition at line 683 of file maglev-interpreter-frame-state.h.
Constructor & Destructor Documentation
CompactInterpreterFrameState() [1/4]
v8::internal::maglev::CompactInterpreterFrameState::CompactInterpreterFrameState (const MaglevCompilationUnit & info, const compiler::BytecodeLivenessState * liveness) [inline]
Definition at line 685 of file maglev-interpreter-frame-state.h.
      : live_registers_and_accumulator_(
            info.zone()->AllocateArray<ValueNode*>(SizeFor(info, liveness))),
        liveness_(liveness),
        virtual_objects_() {}
CompactInterpreterFrameState() [2/4]
v8::internal::maglev::CompactInterpreterFrameState::CompactInterpreterFrameState (const MaglevCompilationUnit & info, const compiler::BytecodeLivenessState * liveness, const InterpreterFrameState & state) [inline]
Definition at line 692 of file maglev-interpreter-frame-state.h.
      : CompactInterpreterFrameState(info, liveness) {
    virtual_objects_ = state.virtual_objects();
    ForEachValue(info, [&](ValueNode*& entry, interpreter::Register reg) {
      entry = state.get(reg);
    });
  }
References ForEachValue(), v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::InterpreterFrameState::virtual_objects(), and virtual_objects_.
CompactInterpreterFrameState() [3/4]
v8::internal::maglev::CompactInterpreterFrameState::CompactInterpreterFrameState (const CompactInterpreterFrameState &) [delete]
CompactInterpreterFrameState() [4/4]
v8::internal::maglev::CompactInterpreterFrameState::CompactInterpreterFrameState (CompactInterpreterFrameState &&) [delete]
Member Function Documentation
accumulator() [1/2]
ValueNode*& v8::internal::maglev::CompactInterpreterFrameState::accumulator (const MaglevCompilationUnit & info) [inline]
Definition at line 779 of file maglev-interpreter-frame-state.h.
                                                             {
    DCHECK(liveness_->AccumulatorIsLive());
    return live_registers_and_accumulator_[size(info) - 1];
  }
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::DCHECK(), live_registers_and_accumulator_, liveness_, and size().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), ForEachValue(), GetValueOf(), and v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock().
accumulator() [2/2]
ValueNode*& v8::internal::maglev::CompactInterpreterFrameState::accumulator (const MaglevCompilationUnit & info) const [inline]
Definition at line 783 of file maglev-interpreter-frame-state.h.
                                                                   {
    DCHECK(liveness_->AccumulatorIsLive());
    return live_registers_and_accumulator_[size(info) - 1];
  }
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::DCHECK(), live_registers_and_accumulator_, liveness_, and size().
context() [1/2]
ValueNode*& v8::internal::maglev::CompactInterpreterFrameState::context (const MaglevCompilationUnit & info) [inline]
Definition at line 788 of file maglev-interpreter-frame-state.h.
                                                         {
    return live_registers_and_accumulator_[info.parameter_count()];
  }
References live_registers_and_accumulator_, and v8::internal::maglev::MaglevCompilationUnit::parameter_count().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), ForEachRegister(), GetValueOf(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), and v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop().
context() [2/2]
ValueNode*& v8::internal::maglev::CompactInterpreterFrameState::context (const MaglevCompilationUnit & info) const [inline]
Definition at line 791 of file maglev-interpreter-frame-state.h.
                                                               {
    return live_registers_and_accumulator_[info.parameter_count()];
  }
References live_registers_and_accumulator_, and v8::internal::maglev::MaglevCompilationUnit::parameter_count().
ForEachLocal() [1/2]
template<typename Function >
void v8::internal::maglev::CompactInterpreterFrameState::ForEachLocal (const MaglevCompilationUnit & info, Function && f) [inline]
Definition at line 737 of file maglev-interpreter-frame-state.h.
                                                                     {
    int live_reg = 0;
    for (int register_index : *liveness_) {
      interpreter::Register reg = interpreter::Register(register_index);
      f(live_registers_and_accumulator_[info.parameter_count() +
                                        context_register_count_ + live_reg++],
        reg);
    }
  }
References context_register_count_, live_registers_and_accumulator_, liveness_, v8::internal::maglev::MaglevCompilationUnit::parameter_count(), and v8::internal::ETWJITInterface::Register().
ForEachLocal() [2/2]
template<typename Function >
void v8::internal::maglev::CompactInterpreterFrameState::ForEachLocal (const MaglevCompilationUnit & info, Function && f) const [inline]
Definition at line 726 of file maglev-interpreter-frame-state.h.
                                                                           {
    int live_reg = 0;
    for (int register_index : *liveness_) {
      interpreter::Register reg = interpreter::Register(register_index);
      f(live_registers_and_accumulator_[info.parameter_count() +
                                        context_register_count_ + live_reg++],
        reg);
    }
  }
References context_register_count_, live_registers_and_accumulator_, liveness_, v8::internal::maglev::MaglevCompilationUnit::parameter_count(), and v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), ForEachRegister(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), and v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop().
ForEachParameter() [1/2]
template<typename Function >
void v8::internal::maglev::CompactInterpreterFrameState::ForEachParameter (const MaglevCompilationUnit & info, Function && f) [inline]
Definition at line 718 of file maglev-interpreter-frame-state.h.
                                                                         {
    for (int i = 0; i < info.parameter_count(); i++) {
      interpreter::Register reg = interpreter::Register::FromParameterIndex(i);
      f(live_registers_and_accumulator_[i], reg);
    }
  }
References v8::internal::interpreter::Register::FromParameterIndex(), live_registers_and_accumulator_, and v8::internal::maglev::MaglevCompilationUnit::parameter_count().
ForEachParameter() [2/2]
template<typename Function >
void v8::internal::maglev::CompactInterpreterFrameState::ForEachParameter (const MaglevCompilationUnit & info, Function && f) const [inline]
Definition at line 710 of file maglev-interpreter-frame-state.h.
                                                                               {
    for (int i = 0; i < info.parameter_count(); i++) {
      interpreter::Register reg = interpreter::Register::FromParameterIndex(i);
      f(live_registers_and_accumulator_[i], reg);
    }
  }
References v8::internal::interpreter::Register::FromParameterIndex(), live_registers_and_accumulator_, and v8::internal::maglev::MaglevCompilationUnit::parameter_count().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), ForEachRegister(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), and v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop().
ForEachRegister() [1/2]
template<typename Function >
void v8::internal::maglev::CompactInterpreterFrameState::ForEachRegister (const MaglevCompilationUnit & info, Function && f) [inline]
Definition at line 748 of file maglev-interpreter-frame-state.h.
                                                                        {
    ForEachParameter(info, f);
    f(context(info), interpreter::Register::current_context());
    ForEachLocal(info, f);
  }
References context(), v8::internal::interpreter::Register::current_context(), ForEachLocal(), and ForEachParameter().
Referenced by ForEachValue(), and v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock().
ForEachRegister() [2/2]
template<typename Function >
void v8::internal::maglev::CompactInterpreterFrameState::ForEachRegister (const MaglevCompilationUnit & info, Function && f) const [inline]
Definition at line 755 of file maglev-interpreter-frame-state.h.
                                                                              {
    ForEachParameter(info, f);
    f(context(info), interpreter::Register::current_context());
    ForEachLocal(info, f);
  }
References context(), v8::internal::interpreter::Register::current_context(), ForEachLocal(), and ForEachParameter().
ForEachValue() [1/2]
template<typename Function >
void v8::internal::maglev::CompactInterpreterFrameState::ForEachValue (const MaglevCompilationUnit & info, Function && f) [inline]
Definition at line 762 of file maglev-interpreter-frame-state.h.
                                                                     {
    ForEachRegister(info, f);
    if (liveness_->AccumulatorIsLive()) {
      f(accumulator(info), interpreter::Register::virtual_accumulator());
    }
  }
References accumulator(), v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), ForEachRegister(), liveness_, and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by CompactInterpreterFrameState(), v8::internal::maglev::InterpreterFrameState::CopyFrom(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergePhis(), v8::internal::maglev::MergePointInterpreterFrameState::New(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
ForEachValue() [2/2]
template<typename Function >
void v8::internal::maglev::CompactInterpreterFrameState::ForEachValue (const MaglevCompilationUnit & info, Function && f) const [inline]
Definition at line 770 of file maglev-interpreter-frame-state.h.
                                                                           {
    ForEachRegister(info, f);
    if (liveness_->AccumulatorIsLive()) {
      f(accumulator(info), interpreter::Register::virtual_accumulator());
    }
  }
References accumulator(), v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), ForEachRegister(), liveness_, and v8::internal::interpreter::Register::virtual_accumulator().
GetValueOf()
ValueNode* v8::internal::maglev::CompactInterpreterFrameState::GetValueOf (interpreter::Register reg, const MaglevCompilationUnit & info) const [inline]
Definition at line 795 of file maglev-interpreter-frame-state.h.
                                                                 {
    DCHECK(reg.is_valid());
    if (reg == interpreter::Register::current_context()) {
      return context(info);
    }
    if (reg == interpreter::Register::virtual_accumulator()) {
      return accumulator(info);
    }
    if (reg.is_parameter()) {
      DCHECK_LT(reg.ToParameterIndex(), info.parameter_count());
      return live_registers_and_accumulator_[reg.ToParameterIndex()];
    }
    int live_reg = 0;
    // TODO(victorgomes): See if we can do better than a linear search here.
    for (int register_index : *liveness_) {
      if (reg == interpreter::Register(register_index)) {
        return live_registers_and_accumulator_[info.parameter_count() +
                                               context_register_count_ +
                                               live_reg];
      }
      live_reg++;
    }
    // No value in this frame state.
    return nullptr;
  }
References accumulator(), context(), context_register_count_, v8::internal::interpreter::Register::current_context(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::interpreter::Register::is_parameter(), v8::internal::interpreter::Register::is_valid(), live_registers_and_accumulator_, liveness_, v8::internal::maglev::MaglevCompilationUnit::parameter_count(), v8::internal::interpreter::Register::ToParameterIndex(), and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
liveness()
const compiler::BytecodeLivenessState* v8::internal::maglev::CompactInterpreterFrameState::liveness () const [inline]
Definition at line 777 of file maglev-interpreter-frame-state.h.
{ return liveness_; }
References liveness_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), and SizeFor().
operator=() [1/2]
CompactInterpreterFrameState& v8::internal::maglev::CompactInterpreterFrameState::operator= (CompactInterpreterFrameState &&) [delete]
operator=() [2/2]
CompactInterpreterFrameState& v8::internal::maglev::CompactInterpreterFrameState::operator= (const CompactInterpreterFrameState &) [delete]
set_virtual_objects()
void v8::internal::maglev::CompactInterpreterFrameState::set_virtual_objects (const VirtualObjectList & vos) [inline]
Definition at line 828 of file maglev-interpreter-frame-state.h.
                                                         {
    virtual_objects_ = vos;
  }
References virtual_objects_.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::InitializeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), and v8::internal::maglev::MergePointInterpreterFrameState::set_virtual_objects().
size()
size_t v8::internal::maglev::CompactInterpreterFrameState::size (const MaglevCompilationUnit & info) const [inline]
Definition at line 822 of file maglev-interpreter-frame-state.h.
                                                       {
    return SizeFor(info, liveness_);
  }
References liveness_, and SizeFor().
Referenced by accumulator().
SizeFor()
static size_t v8::internal::maglev::CompactInterpreterFrameState::SizeFor (const MaglevCompilationUnit & info, const compiler::BytecodeLivenessState * liveness) [inline], [static], [private]
Definition at line 833 of file maglev-interpreter-frame-state.h.
                                                                       {
    return info.parameter_count() + context_register_count_ +
           liveness->live_value_count();
  }
References context_register_count_, v8::internal::compiler::BytecodeLivenessState::live_value_count(), liveness(), and v8::internal::maglev::MaglevCompilationUnit::parameter_count().
Referenced by size().
virtual_objects() [1/2]
VirtualObjectList& v8::internal::maglev::CompactInterpreterFrameState::virtual_objects () [inline]
Definition at line 827 of file maglev-interpreter-frame-state.h.
{ return virtual_objects_; }
References virtual_objects_.
virtual_objects() [2/2]
const VirtualObjectList& v8::internal::maglev::CompactInterpreterFrameState::virtual_objects () const [inline]
Definition at line 826 of file maglev-interpreter-frame-state.h.
{ return virtual_objects_; }
References virtual_objects_.
Referenced by v8::internal::maglev::InterpreterFrameState::CopyFrom(), v8::internal::maglev::DeoptFrame::GetVirtualObjects(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects(), and v8::internal::maglev::MergePointInterpreterFrameState::PrintVirtualObjects().
Member Data Documentation
context_register_count_
const int v8::internal::maglev::CompactInterpreterFrameState::context_register_count_ = 1 [static], [private]
Definition at line 841 of file maglev-interpreter-frame-state.h.
Referenced by ForEachLocal(), GetValueOf(), and SizeFor().
live_registers_and_accumulator_
ValueNode** const v8::internal::maglev::CompactInterpreterFrameState::live_registers_and_accumulator_ [private]
Definition at line 842 of file maglev-interpreter-frame-state.h.
Referenced by accumulator(), context(), ForEachLocal(), ForEachParameter(), and GetValueOf().
liveness_
const compiler::BytecodeLivenessState* const v8::internal::maglev::CompactInterpreterFrameState::liveness_ [private]
Definition at line 843 of file maglev-interpreter-frame-state.h.
Referenced by accumulator(), ForEachLocal(), ForEachValue(), GetValueOf(), liveness(), and size().
virtual_objects_
VirtualObjectList v8::internal::maglev::CompactInterpreterFrameState::virtual_objects_ [private]
Definition at line 844 of file maglev-interpreter-frame-state.h.
Referenced by CompactInterpreterFrameState(), set_virtual_objects(), and virtual_objects().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.h