v8::base::LeakyObject< T > Class Template Reference
#include <lazy-instance.h>
Public Member Functions
template<typename... Args>
LeakyObject (Args &&... args)
LeakyObject (const LeakyObject &)=delete
LeakyObject & operator= (const LeakyObject &)=delete
T * get ()
Private Attributes
char storage_ [sizeof(T)]
Detailed Description
template<typename T>
class v8::base::LeakyObject< T >
Definition at line 230 of file lazy-instance.h.
Constructor & Destructor Documentation
LeakyObject() [1/2]
template<typename T >
template<typename... Args>
v8::base::LeakyObject< T >::LeakyObject (Args &&... args) [inline], [explicit]
Definition at line 233 of file lazy-instance.h.
                                       {
    new (storage_) T(std::forward<Args>(args)...);
  }
References v8::base::args, v8::base::LeakyObject< T >::storage_, and T.
LeakyObject() [2/2]
template<typename T >
v8::base::LeakyObject< T >::LeakyObject (const LeakyObject< T > &) [delete]
Member Function Documentation
get()
template<typename T >
T* v8::base::LeakyObject< T >::get () [inline]
Definition at line 240 of file lazy-instance.h.
{ return reinterpret_cast<T*>(storage_); }
References v8::base::LeakyObject< T >::storage_.
Referenced by cppgc::internal::anonymous_namespace{platform.cc}::CreateAllocatorIfNeeded(), v8::internal::anonymous_namespace{profile-data-reader.cc}::EnsureInitProfileData(), v8::internal::CodeEntry::gc_entry(), v8::internal::GetPlatformVirtualAddressSpace(), cppgc::Platform::GetTracingController(), v8::internal::CodeEntry::idle_entry(), cppgc::internal::GlobalGCInfoTable::Initialize(), v8::internal::anonymous_namespace{allocation.cc}::PageAllocatorInitializer::PageAllocatorInitializer(), v8::internal::CodeEntry::program_entry(), v8::internal::CodeEntry::root_entry(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::CodeEntry::unresolved_entry().
operator=()
template<typename T >
LeakyObject& v8::base::LeakyObject< T >::operator= (const LeakyObject< T > &) [delete]
Member Data Documentation
storage_
template<typename T >
char v8::base::LeakyObject< T >::storage_[sizeof(T)] [private]
Definition at line 243 of file lazy-instance.h.
Referenced by v8::base::LeakyObject< T >::get(), and v8::base::LeakyObject< T >::LeakyObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/lazy-instance.h