unibrow::Utf16 Class Reference
#include <unicode.h>
Static Public Member Functions
static bool IsSurrogatePair (int lead, int trail)
static bool IsLeadSurrogate (int code)
static bool IsTrailSurrogate (int code)
static int CombineSurrogatePair (uchar lead, uchar trail)
static uint16_t LeadSurrogate (uint32_t char_code)
static uint16_t TrailSurrogate (uint32_t char_code)
static bool HasUnpairedSurrogate (const uint16_t *code_units, size_t length)
static void ReplaceUnpairedSurrogates (const uint16_t *source_code_units, uint16_t *dest_code_units, size_t length)
Static Public Attributes
static const int kNoPreviousCharacter = -1
static const uchar kMaxNonSurrogateCharCode = 0xffff
static const int kMaxExtraUtf8BytesForOneUtf16CodeUnit = 3
static const int kUtf8BytesToCodeASurrogate = 3
Detailed Description
Definition at line 100 of file unicode.h.
Member Function Documentation
CombineSurrogatePair()
static int unibrow::Utf16::CombineSurrogatePair (uchar lead, uchar trail) [inline], [static]
Definition at line 113 of file unicode.h.
                                                                  {
    return 0x10000 + ((lead & 0x3ff) << 10) + (trail & 0x3ff);
  }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTrailSurrogate(), v8::internal::Scanner::CombineSurrogatePair(), unibrow::Utf8::Encode(), v8::internal::anonymous_namespace{uri.cc}::EncodePair(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseUnicodeEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ReadNext(), and v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl().
HasUnpairedSurrogate()
bool unibrow::Utf16::HasUnpairedSurrogate (const uint16_t * code_units, size_t length) [inline], [static]
Definition at line 65 of file unicode-inl.h.
                                                                          {
  return !simdutf::validate_utf16(reinterpret_cast<const char16_t*>(code_units),
                                  length);
}
References v8::internal::length.
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::HasUnpairedSurrogate(), v8::internal::String::IsWellFormedUnicode(), v8::internal::Parser::ParseExportSpecifierName(), and v8::internal::RUNTIME_FUNCTION().
IsLeadSurrogate()
static bool unibrow::Utf16::IsLeadSurrogate (int code) [inline], [static]
Definition at line 106 of file unicode.h.
                                               {
    return (code & 0x1ffc00) == 0xd800;
  }
References code.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddLeadSurrogate(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTrailSurrogate(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddUnicodeCharacter(), v8::internal::RegExpGlobalExecRunner::AdvanceZeroLength(), v8::internal::anonymous_namespace{regexp.cc}::AtomExecRawImpl(), v8::internal::Scanner::CombineSurrogatePair(), unibrow::Utf8::Encode(), v8::internal::Uri::Encode(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::anonymous_namespace{unicode-decoder.cc}::DecoderTraits< Utf8Decoder >::IsInvalidSurrogatePair(), IsSurrogatePair(), unibrow::Utf8::Length(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseUnicodeEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ReadNext(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), and v8::anonymous_namespace{api.cc}::WriteUtf8Impl().
IsSurrogatePair()
static bool unibrow::Utf16::IsSurrogatePair (int lead, int trail) [inline], [static]
Definition at line 103 of file unicode.h.
                                                          {
    return IsLeadSurrogate(lead) && IsTrailSurrogate(trail);
  }
References IsLeadSurrogate(), and IsTrailSurrogate().
Referenced by unibrow::Utf8::Encode(), unibrow::Utf8::Length(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), and v8::anonymous_namespace{api.cc}::WriteUtf8Impl().
IsTrailSurrogate()
static bool unibrow::Utf16::IsTrailSurrogate (int code) [inline], [static]
Definition at line 109 of file unicode.h.
                                                {
    return (code & 0x1ffc00) == 0xdc00;
  }
References code.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTrailSurrogate(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddUnicodeCharacter(), v8::internal::RegExpGlobalExecRunner::AdvanceZeroLength(), v8::internal::anonymous_namespace{regexp.cc}::AtomExecRawImpl(), v8::internal::Scanner::CombineSurrogatePair(), unibrow::Utf8::Encode(), v8::internal::Uri::Encode(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::anonymous_namespace{unicode-decoder.cc}::DecoderTraits< Utf8Decoder >::IsInvalidSurrogatePair(), IsSurrogatePair(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseUnicodeEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ReadNext(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), and v8::anonymous_namespace{api.cc}::WriteUtf8Impl().
LeadSurrogate()
static uint16_t unibrow::Utf16::LeadSurrogate (uint32_t char_code) [inline], [static]
Definition at line 126 of file unicode.h.
                                                           {
    return 0xd800 + (((char_code - 0x10000) >> 10) & 0x3ff);
  }
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::LiteralBuffer::AddTwoByteChar(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddUnicodeCharacter(), v8::internal::BUILTIN(), v8::internal::Utf8DecoderBase< Decoder >::Decode(), v8::internal::anonymous_namespace{uri.cc}::DecodeOctets(), v8::internal::JsonParser< Char >::DecodeString(), v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::push_code_unit(), and v8::internal::RUNTIME_FUNCTION().
ReplaceUnpairedSurrogates()
void unibrow::Utf16::ReplaceUnpairedSurrogates (const uint16_t * source_code_units, uint16_t * dest_code_units, size_t length) [static]
Definition at line 241 of file unicode.cc.
                                                     {
  simdutf::to_well_formed_utf16(
      reinterpret_cast<const char16_t*>(source_code_units), length,
      reinterpret_cast<char16_t*>(dest_code_units));
}
References v8::internal::length.
Referenced by v8::internal::ReplaceUnpairedSurrogates(), and v8::internal::RUNTIME_FUNCTION().
TrailSurrogate()
static uint16_t unibrow::Utf16::TrailSurrogate (uint32_t char_code) [inline], [static]
Definition at line 129 of file unicode.h.
                                                            {
    return 0xdc00 + (char_code & 0x3ff);
  }
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::LiteralBuffer::AddTwoByteChar(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddUnicodeCharacter(), v8::internal::BUILTIN(), v8::internal::Utf8DecoderBase< Decoder >::Decode(), v8::internal::anonymous_namespace{uri.cc}::DecodeOctets(), v8::internal::JsonParser< Char >::DecodeString(), v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::push_code_unit(), and v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
kMaxExtraUtf8BytesForOneUtf16CodeUnit
const int unibrow::Utf16::kMaxExtraUtf8BytesForOneUtf16CodeUnit = 3 [static]
Definition at line 122 of file unicode.h.
Referenced by v8::anonymous_namespace{api.cc}::WriteUtf8Impl().
kMaxNonSurrogateCharCode
const uchar unibrow::Utf16::kMaxNonSurrogateCharCode = 0xffff [static]
Definition at line 116 of file unicode.h.
Referenced by v8::internal::LiteralBuffer::AddTwoByteChar(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddUnicodeCharacter(), v8::internal::BUILTIN(), v8::internal::Utf8DecoderBase< Decoder >::Decode(), v8::internal::anonymous_namespace{uri.cc}::DecodeOctets(), v8::internal::JsonParser< Char >::DecodeString(), v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::position(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::push_code_unit(), v8::internal::Scanner::PushBack(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::RewindByOneCodepoint(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonParser< Char >::ScanJsonString(), v8::internal::Utf8ExternalStreamingStream::SkipToPosition(), and v8::internal::Utf8DecoderBase< Utf8Decoder >::Utf8DecoderBase().
kNoPreviousCharacter
const int unibrow::Utf16::kNoPreviousCharacter = -1 [static]
Definition at line 102 of file unicode.h.
Referenced by v8::internal::StringCharacterStream::CountUtf8Bytes(), unibrow::Utf8::Encode(), v8::internal::anonymous_namespace{uri.cc}::EncodePair(), v8::internal::anonymous_namespace{uri.cc}::EncodeSingle(), unibrow::Utf8::Length(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), v8::String::Utf8Length(), v8::internal::String::Utf8Length(), v8::internal::StringCharacterStream::WriteUtf8Bytes(), and v8::anonymous_namespace{api.cc}::WriteUtf8Impl().
kUtf8BytesToCodeASurrogate
const int unibrow::Utf16::kUtf8BytesToCodeASurrogate = 3 [static]
Definition at line 125 of file unicode.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/unicode.h
/mnt/V8SourceCode/src/strings/unicode-inl.h
/mnt/V8SourceCode/src/strings/unicode.cc