v8::internal::PodArrayBase< T, Super > Class Template Reference
#include <fixed-array.h>
Public Member Functions
void copy_out (int index, T *result, int length)
void copy_in (int index, const T *buffer, int length)
bool matches (const T *buffer, int length)
bool matches (int offset, const T *buffer, int length)
T get (int index)
void set (int index, const T &value)
int length () const
Detailed Description
template<class T, class Super>
class v8::internal::PodArrayBase< T, Super >
Definition at line 896 of file fixed-array.h.
Member Function Documentation
copy_in()
template<class T , class Super >
void v8::internal::PodArrayBase< T, Super >::copy_in (int index, const T * buffer, int length) [inline]
Definition at line 902 of file fixed-array.h.
                                                       {
    MemCopy(&this->values()[index * sizeof(T)], buffer, length * sizeof(T));
  }
References v8::internal::FixedArray::index, v8::internal::length, and v8::internal::MemCopy().
copy_out()
template<class T , class Super >
void v8::internal::PodArrayBase< T, Super >::copy_out (int index, T * result, int length) [inline]
Definition at line 898 of file fixed-array.h.
                                                  {
    MemCopy(result, &this->values()[index * sizeof(T)], length * sizeof(T));
  }
References v8::internal::FixedArray::index, v8::internal::length, v8::internal::MemCopy(), and v8::base::internal::result.
get()
template<class T , class Super >
T v8::internal::PodArrayBase< T, Super >::get (int index) [inline]
Definition at line 918 of file fixed-array.h.
                   {
    T result;
    copy_out(index, &result, 1);
    return result;
  }
References v8::internal::FixedArray::index, and v8::base::internal::result.
length()
template<class T , class Super >
int v8::internal::PodArrayBase< T, Super >::length [inline]
Definition at line 878 of file fixed-array-inl.h.
                                         {
  return Super::length() / sizeof(T);
}
References v8::internal::length, and T.
matches() [1/2]
template<class T , class Super >
bool v8::internal::PodArrayBase< T, Super >::matches (const T * buffer, int length) [inline]
Definition at line 906 of file fixed-array.h.
                                            {
    DCHECK_LE(length, this->length());
    return memcmp(this->begin(), buffer, length * sizeof(T)) == 0;
  }
References v8::internal::compiler::begin(), DCHECK_LE, and v8::internal::length.
matches() [2/2]
template<class T , class Super >
bool v8::internal::PodArrayBase< T, Super >::matches (int offset, const T * buffer, int length) [inline]
Definition at line 911 of file fixed-array.h.
                                                        {
    DCHECK_LE(offset, this->length());
    DCHECK_LE(offset + length, this->length());
    return memcmp(this->begin() + sizeof(T) * offset, buffer,
                  length * sizeof(T)) == 0;
  }
References v8::internal::compiler::begin(), DCHECK_LE, and v8::internal::length.
set()
template<class T , class Super >
void v8::internal::PodArrayBase< T, Super >::set (int index, const T & value) [inline]
Definition at line 924 of file fixed-array.h.
{ copy_in(index, &value, 1); }
References v8::internal::FixedArray::index, and v8::internal::FixedArray::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h