v8::internal::DetachableVector< T > Class Template Reference
#include <detachable-vector.h>
Public Member Functions
DetachableVector ()=default
~DetachableVector ()
void push_back (const T &value)
void free ()
T & at (size_t i) const
T & back () const
T & front () const
void shrink_to_fit ()
Private Member Functions
T * data () const
void Resize (size_t new_capacity)
Additional Inherited Members
Detailed Description
template<typename T>
class v8::internal::DetachableVector< T >
Definition at line 49 of file detachable-vector.h.
Constructor & Destructor Documentation
DetachableVector()
template<typename T >
v8::internal::DetachableVector< T >::DetachableVector () [default]
 DetachableVector()
template<typename T >
v8::internal::DetachableVector< T >::~DetachableVector () [inline]
Definition at line 52 of file detachable-vector.h.
{ delete[] data(); }
References v8::internal::DetachableVector< T >::data().
Member Function Documentation
at()
template<typename T >
T& v8::internal::DetachableVector< T >::at (size_t i) const [inline]
Definition at line 72 of file detachable-vector.h.
                        {
    DCHECK_LT(i, size_);
    return data()[i];
  }
References v8::internal::DetachableVector< T >::data(), DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::DetachableVectorBase::size_.
Referenced by v8::internal::DetachableVector< T >::back(), and v8::internal::DetachableVector< T >::front().
back()
template<typename T >
T& v8::internal::DetachableVector< T >::back () const [inline]
Definition at line 76 of file detachable-vector.h.
{ return at(size_ - 1); }
References v8::internal::DetachableVector< T >::at(), and v8::internal::DetachableVectorBase::size_.
data()
template<typename T >
T* v8::internal::DetachableVector< T >::data () const [inline], [private]
Definition at line 87 of file detachable-vector.h.
{ return static_cast<T*>(data_); }
References v8::internal::DetachableVectorBase::data_.
Referenced by v8::internal::DetachableVector< T >::at(), v8::internal::DetachableVector< T >::free(), v8::internal::DetachableVector< T >::push_back(), v8::internal::DetachableVector< T >::Resize(), and v8::internal::DetachableVector< T >::~DetachableVector().
free()
template<typename T >
void v8::internal::DetachableVector< T >::free () [inline]
Definition at line 65 of file detachable-vector.h.
              {
    delete[] data();
    data_ = nullptr;
    capacity_ = 0;
    size_ = 0;
  }
References v8::internal::DetachableVectorBase::capacity_, v8::internal::DetachableVector< T >::data(), v8::internal::DetachableVectorBase::data_, and v8::internal::DetachableVectorBase::size_.
front()
template<typename T >
T& v8::internal::DetachableVector< T >::front () const [inline]
Definition at line 77 of file detachable-vector.h.
{ return at(0); }
References v8::internal::DetachableVector< T >::at().
push_back()
template<typename T >
void v8::internal::DetachableVector< T >::push_back (const T & value) [inline]
Definition at line 54 of file detachable-vector.h.
                                 {
    if (size_ == capacity_) {
      size_t new_capacity = std::max(kMinimumCapacity, 2 * capacity_);
      Resize(new_capacity);
    }
    data()[size_] = value;
    ++size_;
  }
References v8::internal::DetachableVectorBase::capacity_, v8::internal::DetachableVector< T >::data(), v8::internal::DetachableVectorBase::kMinimumCapacity, v8::internal::DetachableVector< T >::Resize(), v8::internal::DetachableVectorBase::size_, and v8::internal::value.
Resize()
template<typename T >
void v8::internal::DetachableVector< T >::Resize (size_t new_capacity) [inline], [private]
Definition at line 89 of file detachable-vector.h.
                                   {
    DCHECK_LE(size_, new_capacity);
    T* new_data_ = new T[new_capacity];
    std::copy(data(), data() + size_, new_data_);
    delete[] data();
    data_ = new_data_;
    capacity_ = new_capacity;
  }
References v8::internal::DetachableVectorBase::capacity_, v8::internal::DetachableVector< T >::data(), v8::internal::DetachableVectorBase::data_, DCHECK_LE, and v8::internal::DetachableVectorBase::size_.
Referenced by v8::internal::DetachableVector< T >::push_back(), and v8::internal::DetachableVector< T >::shrink_to_fit().
shrink_to_fit()
template<typename T >
void v8::internal::DetachableVector< T >::shrink_to_fit () [inline]
Definition at line 79 of file detachable-vector.h.
                       {
    size_t new_capacity = std::max(size_, kMinimumCapacity);
    if (new_capacity < capacity_ / 2) {
      Resize(new_capacity);
    }
  }
References v8::internal::DetachableVectorBase::capacity_, v8::internal::DetachableVectorBase::kMinimumCapacity, v8::internal::DetachableVector< T >::Resize(), and v8::internal::DetachableVectorBase::size_.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/detachable-vector.h