v8::internal::interpreter::BytecodeNode Class Reference
#include <bytecode-node.h>
Public Member Functions
BytecodeNode (Bytecode bytecode, BytecodeSourceInfo source_info=BytecodeSourceInfo())
BytecodeNode (Bytecode bytecode, uint32_t operand0, BytecodeSourceInfo source_info=BytecodeSourceInfo())
BytecodeNode (Bytecode bytecode, uint32_t operand0, uint32_t operand1, BytecodeSourceInfo source_info=BytecodeSourceInfo())
BytecodeNode (Bytecode bytecode, uint32_t operand0, uint32_t operand1, uint32_t operand2, BytecodeSourceInfo source_info=BytecodeSourceInfo())
BytecodeNode (Bytecode bytecode, uint32_t operand0, uint32_t operand1, uint32_t operand2, uint32_t operand3, BytecodeSourceInfo source_info=BytecodeSourceInfo())
BytecodeNode (Bytecode bytecode, uint32_t operand0, uint32_t operand1, uint32_t operand2, uint32_t operand3, uint32_t operand4, BytecodeSourceInfo source_info=BytecodeSourceInfo())
void Print (std::ostream &os) const
Bytecode bytecode () const
uint32_t operand (int i) const
const uint32_t * operands () const
void update_operand0 (uint32_t operand0)
int operand_count () const
OperandScale operand_scale () const
const BytecodeSourceInfo & source_info () const
void set_source_info (BytecodeSourceInfo source_info)
bool operator== (const BytecodeNode &other) const
bool operator!= (const BytecodeNode &other) const
Private Member Functions
BytecodeNode (Bytecode bytecode, int operand_count, OperandScale operand_scale, BytecodeSourceInfo source_info, uint32_t operand0=0, uint32_t operand1=0, uint32_t operand2=0, uint32_t operand3=0, uint32_t operand4=0)
void UpdateScaleForOperand (int operand_index, uint32_t operand)
void SetOperand (int operand_index, uint32_t operand)
Static Private Member Functions
template<Bytecode bytecode, ImplicitRegisterUse accum_use>
static BytecodeNode Create (BytecodeSourceInfo source_info)
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type>
static BytecodeNode Create (BytecodeSourceInfo source_info, uint32_t operand0)
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type, OperandType operand1_type>
static BytecodeNode Create (BytecodeSourceInfo source_info, uint32_t operand0, uint32_t operand1)
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type, OperandType operand1_type, OperandType operand2_type>
static BytecodeNode Create (BytecodeSourceInfo source_info, uint32_t operand0, uint32_t operand1, uint32_t operand2)
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type, OperandType operand1_type, OperandType operand2_type, OperandType operand3_type>
static BytecodeNode Create (BytecodeSourceInfo source_info, uint32_t operand0, uint32_t operand1, uint32_t operand2, uint32_t operand3)
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type, OperandType operand1_type, OperandType operand2_type, OperandType operand3_type, OperandType operand4_type>
static BytecodeNode Create (BytecodeSourceInfo source_info, uint32_t operand0, uint32_t operand1, uint32_t operand2, uint32_t operand3, uint32_t operand4)
template<OperandType operand_type>
static OperandScale ScaleForOperand (uint32_t operand)
Private Attributes
Bytecode bytecode_
uint32_t operands_ [Bytecodes::kMaxOperands]
int operand_count_
OperandScale operand_scale_
BytecodeSourceInfo source_info_
Friends
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
class BytecodeNodeBuilder
Detailed Description
Definition at line 18 of file bytecode-node.h.
Constructor & Destructor Documentation
BytecodeNode() [1/7]
v8::internal::interpreter::BytecodeNode::BytecodeNode (Bytecode bytecode, BytecodeSourceInfo source_info = BytecodeSourceInfo()) [inline]
Definition at line 20 of file bytecode-node.h.
      : bytecode_(bytecode),
        operand_count_(0),
        operand_scale_(OperandScale::kSingle),
        source_info_(source_info) {
    DCHECK_EQ(Bytecodes::NumberOfOperands(bytecode), operand_count());
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::NumberOfOperands().
BytecodeNode() [2/7]
v8::internal::interpreter::BytecodeNode::BytecodeNode (Bytecode bytecode, uint32_t operand0, BytecodeSourceInfo source_info = BytecodeSourceInfo()) [inline]
Definition at line 29 of file bytecode-node.h.
      : bytecode_(bytecode),
        operand_count_(1),
        operand_scale_(OperandScale::kSingle),
        source_info_(source_info) {
    DCHECK_EQ(Bytecodes::NumberOfOperands(bytecode), operand_count());
    SetOperand(0, operand0);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::NumberOfOperands().
BytecodeNode() [3/7]
v8::internal::interpreter::BytecodeNode::BytecodeNode (Bytecode bytecode, uint32_t operand0, uint32_t operand1, BytecodeSourceInfo source_info = BytecodeSourceInfo()) [inline]
Definition at line 39 of file bytecode-node.h.
      : bytecode_(bytecode),
        operand_count_(2),
        operand_scale_(OperandScale::kSingle),
        source_info_(source_info) {
    DCHECK_EQ(Bytecodes::NumberOfOperands(bytecode), operand_count());
    SetOperand(0, operand0);
    SetOperand(1, operand1);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::NumberOfOperands().
BytecodeNode() [4/7]
v8::internal::interpreter::BytecodeNode::BytecodeNode (Bytecode bytecode, uint32_t operand0, uint32_t operand1, uint32_t operand2, BytecodeSourceInfo source_info = BytecodeSourceInfo()) [inline]
Definition at line 51 of file bytecode-node.h.
      : bytecode_(bytecode),
        operand_count_(3),
        operand_scale_(OperandScale::kSingle),
        source_info_(source_info) {
    DCHECK_EQ(Bytecodes::NumberOfOperands(bytecode), operand_count());
    SetOperand(0, operand0);
    SetOperand(1, operand1);
    SetOperand(2, operand2);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::NumberOfOperands().
BytecodeNode() [5/7]
v8::internal::interpreter::BytecodeNode::BytecodeNode (Bytecode bytecode, uint32_t operand0, uint32_t operand1, uint32_t operand2, uint32_t operand3, BytecodeSourceInfo source_info = BytecodeSourceInfo()) [inline]
Definition at line 64 of file bytecode-node.h.
      : bytecode_(bytecode),
        operand_count_(4),
        operand_scale_(OperandScale::kSingle),
        source_info_(source_info) {
    DCHECK_EQ(Bytecodes::NumberOfOperands(bytecode), operand_count());
    SetOperand(0, operand0);
    SetOperand(1, operand1);
    SetOperand(2, operand2);
    SetOperand(3, operand3);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::NumberOfOperands().
BytecodeNode() [6/7]
v8::internal::interpreter::BytecodeNode::BytecodeNode (Bytecode bytecode, uint32_t operand0, uint32_t operand1, uint32_t operand2, uint32_t operand3, uint32_t operand4, BytecodeSourceInfo source_info = BytecodeSourceInfo()) [inline]
Definition at line 79 of file bytecode-node.h.
      : bytecode_(bytecode),
        operand_count_(5),
        operand_scale_(OperandScale::kSingle),
        source_info_(source_info) {
    DCHECK_EQ(Bytecodes::NumberOfOperands(bytecode), operand_count());
    SetOperand(0, operand0);
    SetOperand(1, operand1);
    SetOperand(2, operand2);
    SetOperand(3, operand3);
    SetOperand(4, operand4);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::NumberOfOperands().
BytecodeNode() [7/7]
v8::internal::interpreter::BytecodeNode::BytecodeNode (Bytecode bytecode, int operand_count, OperandScale operand_scale, BytecodeSourceInfo source_info, uint32_t operand0 = 0, uint32_t operand1 = 0, uint32_t operand2 = 0, uint32_t operand3 = 0, uint32_t operand4 = 0) [inline], [private]
Definition at line 133 of file bytecode-node.h.
      : bytecode_(bytecode),
        operand_count_(operand_count),
        operand_scale_(operand_scale),
        source_info_(source_info) {
    DCHECK_EQ(Bytecodes::NumberOfOperands(bytecode), operand_count);
    operands_[0] = operand0;
    operands_[1] = operand1;
    operands_[2] = operand2;
    operands_[3] = operand3;
    operands_[4] = operand4;
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::NumberOfOperands().
Member Function Documentation
bytecode()
Bytecode v8::internal::interpreter::BytecodeNode::bytecode () const [inline]
Definition at line 107 of file bytecode-node.h.
{ return bytecode_; }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode(), v8::internal::interpreter::BytecodeArrayWriter::EmitJump(), v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop(), v8::internal::interpreter::BytecodeArrayWriter::EmitSwitch(), operator==(), v8::internal::interpreter::BytecodeArrayWriter::WriteJump(), v8::internal::interpreter::BytecodeArrayWriter::WriteJumpLoop(), and v8::internal::interpreter::BytecodeArrayWriter::WriteSwitch().
Create() [1/6]
template<Bytecode bytecode, ImplicitRegisterUse accum_use>
static BytecodeNode v8::internal::interpreter::BytecodeNode::Create (BytecodeSourceInfo source_info) [inline], [static], [private]
Definition at line 151 of file bytecode-node.h.
                                                                       {
    return BytecodeNode(bytecode, 0, OperandScale::kSingle, source_info);
  }
Referenced by v8::internal::interpreter::BytecodeNodeBuilder< bytecode, implicit_register_use, operand_types >::Make().
Create() [2/6]
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type>
static BytecodeNode v8::internal::interpreter::BytecodeNode::Create (BytecodeSourceInfo source_info, uint32_t operand0) [inline], [static], [private]
Definition at line 157 of file bytecode-node.h.
                                                          {
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 0), operand0_type);
    OperandScale scale = OperandScale::kSingle;
    scale = std::max(scale, ScaleForOperand<operand0_type>(operand0));
    return BytecodeNode(bytecode, 1, scale, source_info, operand0);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::GetOperandType().
Create() [3/6]
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type, OperandType operand1_type>
static BytecodeNode v8::internal::interpreter::BytecodeNode::Create (BytecodeSourceInfo source_info, uint32_t operand0, uint32_t operand1) [inline], [static], [private]
Definition at line 167 of file bytecode-node.h.
                                                                             {
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 0), operand0_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 1), operand1_type);
    OperandScale scale = OperandScale::kSingle;
    scale = std::max(scale, ScaleForOperand<operand0_type>(operand0));
    scale = std::max(scale, ScaleForOperand<operand1_type>(operand1));
    return BytecodeNode(bytecode, 2, scale, source_info, operand0, operand1);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::GetOperandType().
Create() [4/6]
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type, OperandType operand1_type, OperandType operand2_type>
static BytecodeNode v8::internal::interpreter::BytecodeNode::Create (BytecodeSourceInfo source_info, uint32_t operand0, uint32_t operand1, uint32_t operand2) [inline], [static], [private]
Definition at line 180 of file bytecode-node.h.
                                                          {
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 0), operand0_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 1), operand1_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 2), operand2_type);
    OperandScale scale = OperandScale::kSingle;
    scale = std::max(scale, ScaleForOperand<operand0_type>(operand0));
    scale = std::max(scale, ScaleForOperand<operand1_type>(operand1));
    scale = std::max(scale, ScaleForOperand<operand2_type>(operand2));
    return BytecodeNode(bytecode, 3, scale, source_info, operand0, operand1,
                        operand2);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::GetOperandType().
Create() [5/6]
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type, OperandType operand1_type, OperandType operand2_type, OperandType operand3_type>
static BytecodeNode v8::internal::interpreter::BytecodeNode::Create (BytecodeSourceInfo source_info, uint32_t operand0, uint32_t operand1, uint32_t operand2, uint32_t operand3) [inline], [static], [private]
Definition at line 197 of file bytecode-node.h.
                                                                             {
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 0), operand0_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 1), operand1_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 2), operand2_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 3), operand3_type);
    OperandScale scale = OperandScale::kSingle;
    scale = std::max(scale, ScaleForOperand<operand0_type>(operand0));
    scale = std::max(scale, ScaleForOperand<operand1_type>(operand1));
    scale = std::max(scale, ScaleForOperand<operand2_type>(operand2));
    scale = std::max(scale, ScaleForOperand<operand3_type>(operand3));
    return BytecodeNode(bytecode, 4, scale, source_info, operand0, operand1,
                        operand2, operand3);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::GetOperandType().
Create() [6/6]
template<Bytecode bytecode, ImplicitRegisterUse accum_use, OperandType operand0_type, OperandType operand1_type, OperandType operand2_type, OperandType operand3_type, OperandType operand4_type>
static BytecodeNode v8::internal::interpreter::BytecodeNode::Create (BytecodeSourceInfo source_info, uint32_t operand0, uint32_t operand1, uint32_t operand2, uint32_t operand3, uint32_t operand4) [inline], [static], [private]
Definition at line 217 of file bytecode-node.h.
                                                          {
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 0), operand0_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 1), operand1_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 2), operand2_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 3), operand3_type);
    DCHECK_EQ(Bytecodes::GetOperandType(bytecode, 4), operand4_type);
    OperandScale scale = OperandScale::kSingle;
    scale = std::max(scale, ScaleForOperand<operand0_type>(operand0));
    scale = std::max(scale, ScaleForOperand<operand1_type>(operand1));
    scale = std::max(scale, ScaleForOperand<operand2_type>(operand2));
    scale = std::max(scale, ScaleForOperand<operand3_type>(operand3));
    scale = std::max(scale, ScaleForOperand<operand4_type>(operand4));
    return BytecodeNode(bytecode, 5, scale, source_info, operand0, operand1,
                        operand2, operand3, operand4);
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::GetOperandType().
operand()
uint32_t v8::internal::interpreter::BytecodeNode::operand (int i) const [inline]
Definition at line 109 of file bytecode-node.h.
                                {
    DCHECK_LT(i, operand_count());
    return operands_[i];
  }
References DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitJump(), v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop(), and operator==().
operand_count()
int v8::internal::interpreter::BytecodeNode::operand_count () const [inline]
Definition at line 117 of file bytecode-node.h.
{ return operand_count_; }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode(), operator==(), and Print().
operand_scale()
OperandScale v8::internal::interpreter::BytecodeNode::operand_scale () const [inline]
Definition at line 118 of file bytecode-node.h.
{ return operand_scale_; }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode(), v8::internal::interpreter::BytecodeArrayWriter::EmitJump(), v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop(), and v8::internal::interpreter::BytecodeArrayWriter::EmitSwitch().
operands()
const uint32_t* v8::internal::interpreter::BytecodeNode::operands () const [inline]
Definition at line 113 of file bytecode-node.h.
{ return operands_; }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode().
operator!=()
bool v8::internal::interpreter::BytecodeNode::operator!= (const BytecodeNode & other) const [inline]
Definition at line 126 of file bytecode-node.h.
{ return !(*this == other); }
operator==()
bool v8::internal::interpreter::BytecodeNode::operator== (const BytecodeNode & other) const
Definition at line 33 of file bytecode-node.cc.
                                                             {
  if (this == &other) {
    return true;
  } else if (this->bytecode() != other.bytecode() ||
             this->source_info() != other.source_info()) {
    return false;
  } else {
    for (int i = 0; i < this->operand_count(); ++i) {
      if (this->operand(i) != other.operand(i)) {
        return false;
      }
    }
  }
  return true;
}
References bytecode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, operand(), operand_count(), source_info(), and v8::internal::this.
Print()
void v8::internal::interpreter::BytecodeNode::Print (std::ostream & os) const
Definition at line 13 of file bytecode-node.cc.
                                             {
#ifdef DEBUG
  std::ios saved_state(nullptr);
  saved_state.copyfmt(os);
  os << Bytecodes::ToString(bytecode_);
  for (int i = 0; i < operand_count(); ++i) {
    os << ' ' << std::setw(8) << std::setfill('0') << std::hex << operands_[i];
  }
  os.copyfmt(saved_state);
  if (source_info_.is_valid()) {
    os << ' ' << source_info_;
  }
  os << '\n';
#else
  os << static_cast<const void*>(this);
#endif // DEBUG
}
References bytecode_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::BytecodeSourceInfo::is_valid(), operand_count(), operands_, source_info_, and v8::internal::interpreter::Bytecodes::ToString().
Referenced by v8::internal::interpreter::operator<<().
ScaleForOperand()
template<OperandType operand_type>
static OperandScale v8::internal::interpreter::BytecodeNode::ScaleForOperand (uint32_t operand) [inline], [static], [private]
Definition at line 237 of file bytecode-node.h.
                                                                  {
    if (BytecodeOperands::IsScalableUnsignedByte(operand_type)) {
      return Bytecodes::ScaleForUnsignedOperand(operand);
    } else if (BytecodeOperands::IsScalableSignedByte(operand_type)) {
      return Bytecodes::ScaleForSignedOperand(operand);
    } else {
      return OperandScale::kSingle;
    }
  }
References v8::internal::interpreter::BytecodeOperands::IsScalableSignedByte(), v8::internal::interpreter::BytecodeOperands::IsScalableUnsignedByte(), v8::internal::interpreter::Bytecodes::ScaleForSignedOperand(), and v8::internal::interpreter::Bytecodes::ScaleForUnsignedOperand().
set_source_info()
void v8::internal::interpreter::BytecodeNode::set_source_info (BytecodeSourceInfo source_info) [inline]
Definition at line 121 of file bytecode-node.h.
                                                       {
    source_info_ = source_info;
  }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo().
SetOperand()
void v8::internal::interpreter::BytecodeNode::SetOperand (int operand_index, uint32_t operand) [inline], [private]
Definition at line 258 of file bytecode-node.h.
                                                                 {
    operands_[operand_index] = operand;
    UpdateScaleForOperand(operand_index, operand);
  }
source_info()
const BytecodeSourceInfo& v8::internal::interpreter::BytecodeNode::source_info () const [inline]
Definition at line 120 of file bytecode-node.h.
{ return source_info_; }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo(), operator==(), v8::internal::interpreter::BytecodeArrayWriter::UpdateSourcePositionTable(), v8::internal::interpreter::BytecodeArrayWriter::WriteJump(), v8::internal::interpreter::BytecodeArrayWriter::WriteJumpLoop(), and v8::internal::interpreter::BytecodeArrayWriter::WriteSwitch().
update_operand0()
void v8::internal::interpreter::BytecodeNode::update_operand0 (uint32_t operand0) [inline]
Definition at line 115 of file bytecode-node.h.
{ SetOperand(0, operand0); }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitJump(), and v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop().
UpdateScaleForOperand()
void v8::internal::interpreter::BytecodeNode::UpdateScaleForOperand (int operand_index, uint32_t operand) [inline], [private]
Definition at line 247 of file bytecode-node.h.
                                                                            {
    if (Bytecodes::OperandIsScalableSignedByte(bytecode(), operand_index)) {
      operand_scale_ =
          std::max(operand_scale_, Bytecodes::ScaleForSignedOperand(operand));
    } else if (Bytecodes::OperandIsScalableUnsignedByte(bytecode(),
                                                        operand_index)) {
      operand_scale_ =
          std::max(operand_scale_, Bytecodes::ScaleForUnsignedOperand(operand));
    }
  }
References v8::internal::interpreter::Bytecodes::OperandIsScalableSignedByte(), v8::internal::interpreter::Bytecodes::OperandIsScalableUnsignedByte(), v8::internal::interpreter::Bytecodes::ScaleForSignedOperand(), and v8::internal::interpreter::Bytecodes::ScaleForUnsignedOperand().
Friends And Related Function Documentation
BytecodeNodeBuilder
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
friend class BytecodeNodeBuilder [friend]
Definition at line 131 of file bytecode-node.h.
Member Data Documentation
bytecode_
Bytecode v8::internal::interpreter::BytecodeNode::bytecode_ [private]
Definition at line 263 of file bytecode-node.h.
Referenced by Print().
operand_count_
int v8::internal::interpreter::BytecodeNode::operand_count_ [private]
Definition at line 265 of file bytecode-node.h.
operand_scale_
OperandScale v8::internal::interpreter::BytecodeNode::operand_scale_ [private]
Definition at line 266 of file bytecode-node.h.
operands_
uint32_t v8::internal::interpreter::BytecodeNode::operands_[Bytecodes::kMaxOperands] [private]
Definition at line 264 of file bytecode-node.h.
Referenced by Print().
source_info_
BytecodeSourceInfo v8::internal::interpreter::BytecodeNode::source_info_ [private]
Definition at line 267 of file bytecode-node.h.
Referenced by Print().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-node.h
/mnt/V8SourceCode/src/interpreter/bytecode-node.cc