v8::internal::AccessorPair Class Reference
#include <struct.h>
Public Member Functions
Tagged< Object > get (AccessorComponent component)
void set (AccessorComponent component, Tagged< Object > value)
void set (AccessorComponent component, Tagged< Object > value, ReleaseStoreTag tag)
Tagged< Object > getter () const
void set_getter (Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > getter (AcquireLoadTag) const
void set_getter (Tagged< Object > value, ReleaseStoreTag, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > setter () const
void set_setter (Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > setter (AcquireLoadTag) const
void set_setter (Tagged< Object > value, ReleaseStoreTag, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void SetComponents (Tagged< Object > getter, Tagged< Object > setter)
bool Equals (Tagged< Object > getter_value, Tagged< Object > setter_value)
Static Public Member Functions
static DirectHandle< AccessorPair > Copy (Isolate *isolate, DirectHandle< AccessorPair > pair)
static Handle< JSAny > GetComponent (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< AccessorPair > accessor_pair, AccessorComponent component)
Private Attributes
TaggedMember< Object > getter_
TaggedMember< Object > setter_
Friends
class CodeStubAssembler
class V8HeapExplorer
class TorqueGeneratedAccessorPairAsserts
Additional Inherited Members
Detailed Description
Definition at line 70 of file struct.h.
Member Function Documentation
Copy()
DirectHandle< AccessorPair > v8::internal::AccessorPair::Copy (Isolate * isolate, DirectHandle< AccessorPair > pair) [static]
Definition at line 4042 of file objects.cc.
                                                                               {
  DirectHandle<AccessorPair> copy = isolate->factory()->NewAccessorPair();
  DisallowGarbageCollection no_gc;
  Tagged<AccessorPair> raw_src = *pair;
  Tagged<AccessorPair> raw_copy = *copy;
  raw_copy->set_getter(raw_src->getter());
  raw_copy->set_setter(raw_src->setter());
  return copy;
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewAccessorPair(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::anonymous_namespace{runtime-classes.cc}::ShallowCopyDictionaryTemplate(), v8::internal::LookupIterator::TransitionToAccessorProperty(), and v8::internal::Map::TransitionToAccessorProperty().
Equals()
bool v8::internal::AccessorPair::Equals (Tagged< Object > getter_value, Tagged< Object > setter_value) [inline]
Definition at line 88 of file struct-inl.h.
                                                       {
  return (getter() == getter_value) && (setter() == setter_value);
}
References getter(), and setter().
get()
Tagged< Object > v8::internal::AccessorPair::get (AccessorComponent component) [inline]
Definition at line 36 of file struct-inl.h.
                                                            {
  return component == ACCESSOR_GETTER ? getter() : setter();
}
References v8::internal::ACCESSOR_GETTER, getter(), and setter().
GetComponent()
Handle< JSAny > v8::internal::AccessorPair::GetComponent (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< AccessorPair > accessor_pair, AccessorComponent component) [static]
Definition at line 4053 of file objects.cc.
                                                                           {
  Handle<Object> accessor(accessor_pair->get(component), isolate);
  if (IsFunctionTemplateInfo(*accessor)) {
    // TODO(v8:5962): pass the right name here: "get "/"set " + prop.
    Handle<JSFunction> function =
        ApiNatives::InstantiateFunction(isolate, native_context,
                                        Cast<FunctionTemplateInfo>(accessor))
            .ToHandleChecked();
    accessor_pair->set(component, *function, kReleaseStore);
    return function;
  }
  if (IsNull(*accessor, isolate)) {
    return isolate->factory()->undefined_value();
  }
  return Cast<JSAny>(accessor);
}
References v8::internal::Isolate::factory(), v8::internal::ApiNatives::InstantiateFunction(), v8::internal::IsNull(), v8::kReleaseStore, and v8::internal::native_context.
Referenced by v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Debug::InstallDebugBreakTrampoline(), v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::InstantiateAndVisitLazyAccessorPairs(), and v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor().
getter() [1/2]
Tagged< Object > v8::internal::AccessorPair::getter () const [inline]
Definition at line 57 of file struct-inl.h.
{ return getter_.load(); }
References getter_.
Referenced by Equals(), get(), and SetComponents().
getter() [2/2]
Tagged< Object > v8::internal::AccessorPair::getter (AcquireLoadTag) const [inline]
Definition at line 62 of file struct-inl.h.
                                                        {
  return getter_.Acquire_Load();
}
References getter_.
set() [1/2]
void v8::internal::AccessorPair::set (AccessorComponent component, Tagged< Object > value) [inline]
Definition at line 40 of file struct-inl.h.
                                                                        {
  if (component == ACCESSOR_GETTER) {
    set_getter(value);
  } else {
    set_setter(value);
  }
}
References v8::internal::ACCESSOR_GETTER, set_getter(), set_setter(), and v8::internal::value.
set() [2/2]
void v8::internal::AccessorPair::set (AccessorComponent component, Tagged< Object > value, ReleaseStoreTag tag) [inline]
Definition at line 48 of file struct-inl.h.
                                            {
  if (component == ACCESSOR_GETTER) {
    set_getter(value, tag);
  } else {
    set_setter(value, tag);
  }
}
References v8::internal::ACCESSOR_GETTER, set_getter(), set_setter(), and v8::internal::value.
set_getter() [1/2]
void v8::internal::AccessorPair::set_getter (Tagged< Object > value, ReleaseStoreTag , WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 65 of file struct-inl.h.
                                                     {
  getter_.Release_Store(this, value, mode);
}
References getter_, mode(), and v8::internal::value.
set_getter() [2/2]
void v8::internal::AccessorPair::set_getter (Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 58 of file struct-inl.h.
                                                                         {
  getter_.store(this, value, mode);
}
References getter_, mode(), and v8::internal::value.
Referenced by set(), and SetComponents().
set_setter() [1/2]
void v8::internal::AccessorPair::set_setter (Tagged< Object > value, ReleaseStoreTag , WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 78 of file struct-inl.h.
                                                     {
  setter_.Release_Store(this, value, mode);
}
References mode(), setter_, and v8::internal::value.
set_setter() [2/2]
void v8::internal::AccessorPair::set_setter (Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 71 of file struct-inl.h.
                                                                         {
  setter_.store(this, value, mode);
}
References mode(), setter_, and v8::internal::value.
Referenced by set(), and SetComponents().
SetComponents()
void v8::internal::AccessorPair::SetComponents (Tagged< Object > getter, Tagged< Object > setter) [inline]
Definition at line 83 of file struct-inl.h.
                                                                             {
  if (!IsNull(getter)) set_getter(getter);
  if (!IsNull(setter)) set_setter(setter);
}
References getter(), v8::internal::IsNull(), set_getter(), set_setter(), and setter().
setter() [1/2]
Tagged< Object > v8::internal::AccessorPair::setter () const [inline]
Definition at line 70 of file struct-inl.h.
{ return setter_.load(); }
References setter_.
Referenced by Equals(), get(), and SetComponents().
setter() [2/2]
Tagged< Object > v8::internal::AccessorPair::setter (AcquireLoadTag) const [inline]
Definition at line 75 of file struct-inl.h.
                                                        {
  return setter_.Acquire_Load();
}
References setter_.
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 109 of file struct.h.
TorqueGeneratedAccessorPairAsserts
friend class TorqueGeneratedAccessorPairAsserts [friend]
Definition at line 111 of file struct.h.
V8HeapExplorer
friend class V8HeapExplorer [friend]
Definition at line 110 of file struct.h.
Member Data Documentation
getter_
TaggedMember<Object> v8::internal::AccessorPair::getter_ [private]
Definition at line 113 of file struct.h.
Referenced by getter(), and set_getter().
setter_
TaggedMember<Object> v8::internal::AccessorPair::setter_ [private]
Definition at line 114 of file struct.h.
Referenced by set_setter(), and setter().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/struct.h
/mnt/V8SourceCode/src/objects/objects.cc
/mnt/V8SourceCode/src/objects/struct-inl.h