v8::internal::ArrayLiteral Class Reference
#include <ast.h>
Public Member Functions
const ZonePtrList< Expression > * values () const
const ArrayLiteralBoilerplateBuilder * builder () const
ArrayLiteralBoilerplateBuilder * builder ()
Private Member Functions
ArrayLiteral (Zone *zone, const ScopedPtrList< Expression > &values, int first_spread_index, int pos)
Private Attributes
friend Zone
ZonePtrList< Expression > values_
ArrayLiteralBoilerplateBuilder builder_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1466 of file ast.h.
Constructor & Destructor Documentation
ArrayLiteral()
v8::internal::ArrayLiteral::ArrayLiteral (Zone * zone, const ScopedPtrList< Expression > & values, int first_spread_index, int pos) [inline], [private]
Definition at line 1477 of file ast.h.
      : AggregateLiteral(pos, kArrayLiteral),
        values_(values.ToConstVector(), zone),
        builder_(&values_, first_spread_index) {}
Member Function Documentation
builder() [1/2]
ArrayLiteralBoilerplateBuilder* v8::internal::ArrayLiteral::builder () [inline]
Definition at line 1471 of file ast.h.
{ return &builder_; }
References builder_.
builder() [2/2]
const ArrayLiteralBoilerplateBuilder* v8::internal::ArrayLiteral::builder () const [inline]
Definition at line 1470 of file ast.h.
{ return &builder_; }
References builder_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), and v8::internal::LiteralBoilerplateBuilder::GetBoilerplateValue().
values()
const ZonePtrList<Expression>* v8::internal::ArrayLiteral::values () const [inline]
Definition at line 1468 of file ast.h.
{ return &values_; }
References values_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1474 of file ast.h.
Member Data Documentation
builder_
ArrayLiteralBoilerplateBuilder v8::internal::ArrayLiteral::builder_ [private]
Definition at line 1484 of file ast.h.
Referenced by builder().
values_
ZonePtrList<Expression> v8::internal::ArrayLiteral::values_ [private]
Definition at line 1483 of file ast.h.
Referenced by values().
Zone
friend v8::internal::ArrayLiteral::Zone [private]
Definition at line 1475 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h