v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap Class Reference
Public Member Functions
void AddInterestingLiteral (int script_id, FunctionLiteral *literal)
bool Lookup (Tagged< SharedFunctionInfo > sfi, FunctionData **data)
bool Lookup (DirectHandle< Script > script, FunctionLiteral *literal, FunctionData **data)
void Fill (Isolate *isolate)
Private Types
using FuncId = std::pair< int, int >
Private Member Functions
FuncId GetFuncId (int script_id, FunctionLiteral *literal)
FuncId GetFuncId (int script_id, Tagged< SharedFunctionInfo > sfi)
bool Lookup (FuncId id, FunctionData **data)
void VisitThread (Isolate *isolate, ThreadLocalTop *top) override
void VisitCurrentThread (Isolate *isolate)
Private Attributes
std::map< FuncId, FunctionData > map_
Additional Inherited Members
Detailed Description
Definition at line 585 of file liveedit.cc.
Member Typedef Documentation
FuncId
using v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::FuncId = std::pair<int, int> [private]
Definition at line 644 of file liveedit.cc.
Member Function Documentation
AddInterestingLiteral()
void v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::AddInterestingLiteral (int script_id, FunctionLiteral * literal) [inline]
Definition at line 587 of file liveedit.cc.
                                                                      {
    map_.emplace(GetFuncId(script_id, literal), FunctionData{literal});
  }
Fill()
void v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Fill (Isolate * isolate) [inline]
Definition at line 605 of file liveedit.cc.
                              {
    {
      HeapObjectIterator iterator(isolate->heap(),
                                  HeapObjectIterator::kFilterUnreachable);
      for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
           obj = iterator.Next()) {
        if (IsSharedFunctionInfo(obj)) {
          Tagged<SharedFunctionInfo> sfi = Cast<SharedFunctionInfo>(obj);
          FunctionData* data = nullptr;
          if (!Lookup(sfi, &data)) continue;
          data->shared = handle(sfi, isolate);
        } else if (IsJSFunction(obj)) {
          Tagged<JSFunction> js_function = Cast<JSFunction>(obj);
          Tagged<SharedFunctionInfo> sfi = js_function->shared();
          FunctionData* data = nullptr;
          if (!Lookup(sfi, &data)) continue;
          data->js_functions.emplace_back(js_function, isolate);
        } else if (IsJSGeneratorObject(obj)) {
          Tagged<JSGeneratorObject> gen = Cast<JSGeneratorObject>(obj);
          if (gen->is_closed()) continue;
          Tagged<SharedFunctionInfo> sfi = gen->function()->shared();
          FunctionData* data = nullptr;
          if (!Lookup(sfi, &data)) continue;
          data->running_generators.emplace_back(gen, isolate);
        }
      }
    }
    // Visit the current thread stack.
    VisitCurrentThread(isolate);
    // Visit the stacks of all archived threads.
    isolate->thread_manager()->IterateArchivedThreads(this);
  }
References v8::internal::handle(), v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::ThreadManager::IterateArchivedThreads(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionData::js_functions, v8::internal::HeapObjectIterator::kFilterUnreachable, v8::internal::HeapObjectIterator::Next(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionData::running_generators, v8::internal::anonymous_namespace{liveedit.cc}::FunctionData::shared, and v8::internal::Isolate::thread_manager().
GetFuncId() [1/2]
FuncId v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::GetFuncId (int script_id, FunctionLiteral * literal) [inline], [private]
Definition at line 646 of file liveedit.cc.
                                                            {
    int start_position = literal->start_position();
    if (literal->function_literal_id() == 0) {
      // This is the top-level script function literal, so special case its
      // start position
      DCHECK_EQ(start_position, 0);
      start_position = -1;
    }
    return FuncId(script_id, start_position);
  }
References DCHECK_EQ, v8::internal::FunctionLiteral::function_literal_id(), and v8::internal::FunctionLiteral::start_position().
GetFuncId() [2/2]
FuncId v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::GetFuncId (int script_id, Tagged< SharedFunctionInfo > sfi) [inline], [private]
Definition at line 657 of file liveedit.cc.
                                                                  {
    DCHECK_EQ(script_id, Cast<Script>(sfi->script())->id());
    int start_position = sfi->StartPosition();
    DCHECK_NE(start_position, -1);
    if (sfi->is_toplevel()) {
      // This is the top-level function, so special case its start position
      DCHECK_EQ(start_position, 0);
      start_position = -1;
    }
    return FuncId(script_id, start_position);
  }
References DCHECK_EQ, and DCHECK_NE.
Lookup() [1/3]
bool v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Lookup (DirectHandle< Script > script, FunctionLiteral * literal, FunctionData ** data) [inline]
Definition at line 600 of file liveedit.cc.
                                   {
    return Lookup(GetFuncId(script->id(), literal), data);
  }
References v8::internal::script.
Lookup() [2/3]
bool v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Lookup (FuncId id, FunctionData ** data) [inline], [private]
Definition at line 669 of file liveedit.cc.
                                              {
    auto it = map_.find(id);
    if (it == map_.end()) return false;
    *data = &it->second;
    return true;
  }
Lookup() [3/3]
bool v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Lookup (Tagged< SharedFunctionInfo > sfi, FunctionData ** data) [inline]
Definition at line 591 of file liveedit.cc.
                                                                   {
    int start_position = sfi->StartPosition();
    if (!IsScript(sfi->script()) || start_position == -1) {
      return false;
    }
    Tagged<Script> script = Cast<Script>(sfi->script());
    return Lookup(GetFuncId(script->id(), sfi), data);
  }
References v8::internal::script.
Referenced by v8::internal::anonymous_namespace{liveedit.cc}::CanPatchScript().
VisitCurrentThread()
void v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::VisitCurrentThread (Isolate * isolate) [inline], [private]
Definition at line 689 of file liveedit.cc.
                                            {
    // We allow live editing the function that's currently top-of-stack. But
    // only if no activation of that function is anywhere else on the stack.
    bool is_top = true;
    for (DebugStackTraceIterator it(isolate, /* index */ 0); !it.Done();
         it.Advance(), is_top = false) {
      auto sfi = it.GetSharedFunctionInfo();
      if (sfi.is_null()) continue;
      FunctionData* data = nullptr;
      if (!Lookup(*sfi, &data)) continue;
      // ON_TOP_ONLY will only be set on the first iteration (and if the frame
      // can be restarted). Further activations will change the ON_TOP_ONLY to
      // ON_STACK and prevent the live edit from happening.
      data->stack_position = is_top && it.CanBeRestarted()
                                 ? FunctionData::ON_TOP_ONLY
                                 : FunctionData::ON_STACK;
    }
  }
References v8::internal::DebugStackTraceIterator::Done(), and v8::internal::anonymous_namespace{liveedit.cc}::FunctionData::stack_position.
VisitThread()
void v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::VisitThread (Isolate * isolate, ThreadLocalTop * top) [inline], [override], [private], [virtual]
Implements v8::internal::ThreadVisitor.
Definition at line 676 of file liveedit.cc.
                                                                   {
    for (JavaScriptStackFrameIterator it(isolate, top); !it.done();
         it.Advance()) {
      std::vector<Handle<SharedFunctionInfo>> sfis;
      it.frame()->GetFunctions(&sfis);
      for (auto& sfi : sfis) {
        FunctionData* data = nullptr;
        if (!Lookup(*sfi, &data)) continue;
        data->stack_position = FunctionData::ON_STACK;
      }
    }
  }
References v8::internal::JavaScriptStackFrameIterator::done(), and v8::internal::anonymous_namespace{liveedit.cc}::FunctionData::stack_position.
Member Data Documentation
map_
std::map<FuncId, FunctionData> v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::map_ [private]
Definition at line 709 of file liveedit.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/liveedit.cc