v8::internal::compiler::turboshaft::BuiltinPipeline Class Reference
#include <pipelines.h>
Public Member Functions
BuiltinPipeline (PipelineData *data)
void OptimizeBuiltin ()
Detailed Description
Definition at line 521 of file pipelines.h.
Constructor & Destructor Documentation
BuiltinPipeline()
v8::internal::compiler::turboshaft::BuiltinPipeline::BuiltinPipeline (PipelineData * data) [inline], [explicit]
Definition at line 523 of file pipelines.h.
: Pipeline(data) {}
Member Function Documentation
OptimizeBuiltin()
void v8::internal::compiler::turboshaft::BuiltinPipeline::OptimizeBuiltin ()
Definition at line 153 of file pipelines.cc.
                                      {
  Tracing::Scope tracing_scope(data()->info());
  CHECK(Run<CsaEarlyMachineOptimizationPhase>());
  CHECK(Run<CsaLoadEliminationPhase>());
  CHECK(Run<CsaLateEscapeAnalysisPhase>());
  CHECK(Run<CsaBranchEliminationPhase>());
  if (data()->isolate()->builtins_effects_analyzer() != nullptr) {
    // Effect computations has to run before CsaMemoryOptimizationPhase, so that
    // Allocate aren't lowered to builtin calls.
    CHECK(Run<CsaEffectsComputationPhase>());
  }
  CHECK(Run<CsaMemoryOptimizationPhase>());
  if (v8_flags.turboshaft_enable_debug_features) {
    CHECK(Run<DebugFeatureLoweringPhase>());
  }
  CHECK(Run<CodeEliminationAndSimplificationPhase>());
}
References CHECK, v8::internal::compiler::turboshaft::Pipeline::data(), v8::internal::compiler::turboshaft::Pipeline::info(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/pipelines.h
/mnt/V8SourceCode/src/compiler/turboshaft/pipelines.cc