v8::ExecArgs Class Reference
Public Member Functions
ExecArgs ()
bool Init (Isolate *isolate, Local< Value > arg0, Local< Array > command_args)
~ExecArgs ()
char *const * arg_array () const
const char * arg0 () const
Static Public Attributes
static const unsigned kMaxArgs = 1000
Private Attributes
char * exec_args_ [kMaxArgs+1]
Detailed Description
Definition at line 161 of file d8-posix.cc.
Constructor & Destructor Documentation
ExecArgs()
v8::ExecArgs::ExecArgs () [inline]
Definition at line 163 of file d8-posix.cc.
{ exec_args_[0] = nullptr; }
References exec_args_.
 ExecArgs()
v8::ExecArgs::~ExecArgs () [inline]
Definition at line 198 of file d8-posix.cc.
              {
    for (unsigned i = 0; i < kMaxArgs; i++) {
      if (exec_args_[i] == nullptr) {
        return;
      }
      delete[] exec_args_[i];
      exec_args_[i] = nullptr;
    }
  }
References exec_args_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and kMaxArgs.
Member Function Documentation
arg0()
const char* v8::ExecArgs::arg0 () const [inline]
Definition at line 209 of file d8-posix.cc.
{ return exec_args_[0]; }
References exec_args_.
Referenced by v8::ExecSubprocess(), and Init().
arg_array()
char* const* v8::ExecArgs::arg_array () const [inline]
Definition at line 208 of file d8-posix.cc.
{ return exec_args_; }
References exec_args_.
Referenced by v8::ExecSubprocess().
Init()
bool v8::ExecArgs::Init (Isolate * isolate, Local< Value > arg0, Local< Array > command_args) [inline]
Definition at line 164 of file d8-posix.cc.
                                                                            {
    String::Utf8Value prog(isolate, arg0);
    if (*prog == nullptr) {
      isolate->ThrowError(
          "os.system(): String conversion of program name failed");
      return false;
    }
    {
      size_t len = prog.length() + 3;
      char* c_arg = new char[len];
      snprintf(c_arg, len, "%s", *prog);
      exec_args_[0] = c_arg;
    }
    int i = 1;
    for (unsigned j = 0; j < command_args->Length(); i++, j++) {
      Local<Value> arg(
          command_args
              ->Get(isolate->GetCurrentContext(), Integer::New(isolate, j))
              .ToLocalChecked());
      String::Utf8Value utf8_arg(isolate, arg);
      if (*utf8_arg == nullptr) {
        exec_args_[i] = nullptr; // Consistent state for destructor.
        isolate->ThrowError(
            "os.system(): String conversion of argument failed.");
        return false;
      }
      size_t len = utf8_arg.length() + 1;
      char* c_arg = new char[len];
      snprintf(c_arg, len, "%s", *utf8_arg);
      exec_args_[i] = c_arg;
    }
    exec_args_[i] = nullptr;
    return true;
  }
References arg0(), exec_args_, v8::internal::compiler::turboshaft::Get(), v8::Isolate::GetCurrentContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::String::Utf8Value::length(), v8::Integer::New(), and v8::Isolate::ThrowError().
Referenced by v8::Shell::System().
Member Data Documentation
exec_args_
char* v8::ExecArgs::exec_args_[kMaxArgs+1] [private]
Definition at line 212 of file d8-posix.cc.
Referenced by arg0(), arg_array(), ExecArgs(), Init(), and ~ExecArgs().
kMaxArgs
const unsigned v8::ExecArgs::kMaxArgs = 1000 [static]
Definition at line 207 of file d8-posix.cc.
Referenced by v8::Shell::System(), and ~ExecArgs().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8-posix.cc