v8::RegisteredExtension Class Reference
#include <api.h>
Public Member Functions
Extension * extension () const
RegisteredExtension * next () const
Static Public Member Functions
static void Register (std::unique_ptr< Extension >)
static void UnregisterAll ()
static RegisteredExtension * first_extension ()
Private Member Functions
RegisteredExtension (Extension *)
RegisteredExtension (std::unique_ptr< Extension >)
Private Attributes
std::unique_ptr< Extension > extension_
RegisteredExtension * next_ = nullptr
Static Private Attributes
static RegisteredExtension * first_extension_ = nullptr
Detailed Description
Definition at line 74 of file api.h.
Constructor & Destructor Documentation
RegisteredExtension() [1/2]
v8::RegisteredExtension::RegisteredExtension (Extension *) [explicit], [private]
Referenced by Register().
RegisteredExtension() [2/2]
v8::RegisteredExtension::RegisteredExtension (std::unique_ptr< Extension > extension) [explicit], [private]
Definition at line 452 of file api.cc.
    : extension_(std::move(extension)) {}
Member Function Documentation
extension()
Extension* v8::RegisteredExtension::extension () const [inline]
Definition at line 78 of file api.h.
{ return extension_.get(); }
References extension_.
Referenced by v8::internal::Genesis::InstallExtension(), and Register().
first_extension()
static RegisteredExtension* v8::RegisteredExtension::first_extension () [inline], [static]
Definition at line 80 of file api.h.
{ return first_extension_; }
References first_extension_.
Referenced by v8::internal::Genesis::InstallAutoExtensions(), and v8::internal::Genesis::InstallExtension().
next()
RegisteredExtension* v8::RegisteredExtension::next () const [inline]
Definition at line 79 of file api.h.
{ return next_; }
References next_.
Referenced by v8::internal::Genesis::InstallAutoExtensions(), v8::internal::Genesis::InstallExtension(), and UnregisterAll().
Register()
void v8::RegisteredExtension::Register (std::unique_ptr< Extension > extension) [static]
Definition at line 456 of file api.cc.
                                                                     {
  RegisteredExtension* new_extension =
      new RegisteredExtension(std::move(extension));
  new_extension->next_ = first_extension_;
  first_extension_ = new_extension;
}
References extension(), first_extension_, next_, and RegisteredExtension().
Referenced by v8::RegisterExtension().
UnregisterAll()
void v8::RegisteredExtension::UnregisterAll () [static]
Definition at line 464 of file api.cc.
                                        {
  RegisteredExtension* re = first_extension_;
  while (re != nullptr) {
    RegisteredExtension* next = re->next();
    delete re;
    re = next;
  }
  first_extension_ = nullptr;
}
References first_extension_, and next().
Referenced by v8::internal::V8::Dispose().
Member Data Documentation
extension_
std::unique_ptr<Extension> v8::RegisteredExtension::extension_ [private]
Definition at line 85 of file api.h.
Referenced by extension().
first_extension_
RegisteredExtension * v8::RegisteredExtension::first_extension_ = nullptr [static], [private]
Definition at line 87 of file api.h.
Referenced by first_extension(), Register(), and UnregisterAll().
next_
RegisteredExtension* v8::RegisteredExtension::next_ = nullptr [private]
Definition at line 86 of file api.h.
Referenced by next(), and Register().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/api/api.h
/mnt/V8SourceCode/src/api/api.cc