v8::internal::compiler::OsrHelper Class Reference
#include <osr.h>
Public Member Functions
OsrHelper (OptimizedCompilationInfo *info)
V8_EXPORT_PRIVATE void SetupFrame (Frame *frame)
size_t UnoptimizedFrameSlots ()
Static Public Member Functions
static int FirstStackSlotIndex (int parameter_count)
Private Attributes
size_t parameter_count_
size_t stack_slot_count_
Detailed Description
Definition at line 23 of file osr.h.
Constructor & Destructor Documentation
OsrHelper()
v8::internal::compiler::OsrHelper::OsrHelper (OptimizedCompilationInfo * info) [explicit]
Definition at line 15 of file osr.cc.
    : parameter_count_(info->bytecode_array()->parameter_count()),
      stack_slot_count_(UnoptimizedFrameConstants::RegisterStackSlotCount(
                            info->bytecode_array()->register_count()) +
                        UnoptimizedFrameConstants::kExtraSlotCount) {}
Member Function Documentation
FirstStackSlotIndex()
static int v8::internal::compiler::OsrHelper::FirstStackSlotIndex (int parameter_count) [inline], [static]
Definition at line 34 of file osr.h.
                                                      {
    // TurboFan environments do not contain the context.
    return 1 + parameter_count; // receiver + params
  }
Referenced by v8::internal::compiler::Linkage::GetOsrValueLocation().
SetupFrame()
void v8::internal::compiler::OsrHelper::SetupFrame (Frame * frame)
Definition at line 21 of file osr.cc.
                                       {
  // The optimized frame will subsume the unoptimized frame. Do so by reserving
  // the first spill slots.
  frame->ReserveSpillSlots(UnoptimizedFrameSlots());
}
References v8::internal::compiler::Frame::ReserveSpillSlots(), and UnoptimizedFrameSlots().
Referenced by v8::internal::compiler::TFPipelineData::InitializeFrameData().
UnoptimizedFrameSlots()
size_t v8::internal::compiler::OsrHelper::UnoptimizedFrameSlots () [inline]
Definition at line 31 of file osr.h.
{ return stack_slot_count_; }
References stack_slot_count_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), and SetupFrame().
Member Data Documentation
parameter_count_
size_t v8::internal::compiler::OsrHelper::parameter_count_ [private]
Definition at line 40 of file osr.h.
stack_slot_count_
size_t v8::internal::compiler::OsrHelper::stack_slot_count_ [private]
Definition at line 41 of file osr.h.
Referenced by UnoptimizedFrameSlots().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/osr.h
/mnt/V8SourceCode/src/compiler/osr.cc