v8::internal::BaseNameDictionaryShape Class Reference
#include <dictionary.h>
Static Public Member Functions
static bool IsMatch (DirectHandle< Name > key, Tagged< Object > other)
static uint32_t Hash (ReadOnlyRoots roots, DirectHandle< Name > key)
static uint32_t HashForObject (ReadOnlyRoots roots, Tagged< Object > object)
template<AllocationType allocation = AllocationType::kYoung>
static DirectHandle< Object > AsHandle (Isolate *isolate, DirectHandle< Name > key)
template<AllocationType allocation = AllocationType::kOld>
static DirectHandle< Object > AsHandle (LocalIsolate *isolate, DirectHandle< Name > key)
Static Public Attributes
static const int kEntryValueIndex = 1
Additional Inherited Members
Detailed Description
Definition at line 157 of file dictionary.h.
Member Function Documentation
AsHandle() [1/2]
template<AllocationType allocation>
DirectHandle< Object > v8::internal::BaseNameDictionaryShape::AsHandle (Isolate * isolate, DirectHandle< Name > key) [inline], [static]
Definition at line 358 of file dictionary-inl.h.
                                                                               {
  DCHECK(IsUniqueName(*key));
  return key;
}
References v8::internal::DCHECK(), v8::internal::IsUniqueName(), and v8::internal::key.
AsHandle() [2/2]
template<AllocationType allocation>
DirectHandle< Object > v8::internal::BaseNameDictionaryShape::AsHandle (LocalIsolate * isolate, DirectHandle< Name > key) [inline], [static]
Definition at line 365 of file dictionary-inl.h.
                                                                               {
  DCHECK(IsUniqueName(*key));
  return key;
}
References v8::internal::DCHECK(), v8::internal::IsUniqueName(), and v8::internal::key.
Hash()
uint32_t v8::internal::BaseNameDictionaryShape::Hash (ReadOnlyRoots roots, DirectHandle< Name > key) [inline], [static]
Definition at line 333 of file dictionary-inl.h.
                                                               {
  DCHECK(IsUniqueName(*key));
  return key->hash();
}
References v8::internal::DCHECK(), v8::internal::IsUniqueName(), and v8::internal::key.
HashForObject()
uint32_t v8::internal::BaseNameDictionaryShape::HashForObject (ReadOnlyRoots roots, Tagged< Object > object) [inline], [static]
Definition at line 339 of file dictionary-inl.h.
                                                                      {
  DCHECK(IsUniqueName(other));
  return Cast<Name>(other)->hash();
}
References v8::internal::DCHECK(), and v8::internal::IsUniqueName().
IsMatch()
bool v8::internal::BaseNameDictionaryShape::IsMatch (DirectHandle< Name > key, Tagged< Object > other) [inline], [static]
Definition at line 326 of file dictionary-inl.h.
                                                            {
  DCHECK(IsTheHole(other) || IsUniqueName(Cast<Name>(other)));
  DCHECK(IsUniqueName(*key));
  return *key == other;
}
References v8::internal::DCHECK(), v8::internal::IsUniqueName(), and v8::internal::key.
Member Data Documentation
kEntryValueIndex
const int v8::internal::BaseNameDictionaryShape::kEntryValueIndex = 1 [static]
Definition at line 169 of file dictionary.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/dictionary.h
/mnt/V8SourceCode/src/objects/dictionary-inl.h