v8::internal::compiler::Schedule Class Reference
#include <schedule.h>
Public Member Functions
Schedule (Zone *zone, size_t node_count_hint=0)
Schedule (const Schedule &)=delete
Schedule & operator= (const Schedule &)=delete
BasicBlock * block (Node *node) const
bool IsScheduled (Node *node)
BasicBlock * GetBlockById (BasicBlock::Id block_id)
void ClearBlockById (BasicBlock::Id block_id)
size_t BasicBlockCount () const
size_t RpoBlockCount () const
bool SameBasicBlock (Node *a, Node *b) const
BasicBlock * NewBasicBlock ()
void PlanNode (BasicBlock *block, Node *node)
void AddNode (BasicBlock *block, Node *node)
void AddGoto (BasicBlock *block, BasicBlock *succ)
void AddCall (BasicBlock *block, Node *call, BasicBlock *success_block, BasicBlock *exception_block)
void AddBranch (BasicBlock *block, Node *branch, BasicBlock *tblock, BasicBlock *fblock)
void AddSwitch (BasicBlock *block, Node *sw, BasicBlock **succ_blocks, size_t succ_count)
void AddDeoptimize (BasicBlock *block, Node *input)
void AddTailCall (BasicBlock *block, Node *input)
void AddReturn (BasicBlock *block, Node *input)
void AddThrow (BasicBlock *block, Node *input)
void InsertBranch (BasicBlock *block, BasicBlock *end, Node *branch, BasicBlock *tblock, BasicBlock *fblock)
void InsertSwitch (BasicBlock *block, BasicBlock *end, Node *sw, BasicBlock **succ_blocks, size_t succ_count)
void AddSuccessorForTesting (BasicBlock *block, BasicBlock *succ)
const BasicBlockVector * all_blocks () const
BasicBlockVector * rpo_order ()
const BasicBlockVector * rpo_order () const
BasicBlock * start ()
BasicBlock * end ()
Zone * zone () const
Private Member Functions
void EnsureCFGWellFormedness ()
void EliminateRedundantPhiNodes ()
void EnsureSplitEdgeForm (BasicBlock *block)
void MovePhis (BasicBlock *from, BasicBlock *to)
void PropagateDeferredMark ()
void AddSuccessor (BasicBlock *block, BasicBlock *succ)
void MoveSuccessors (BasicBlock *from, BasicBlock *to)
void SetControlInput (BasicBlock *block, Node *node)
void SetBlockForNode (BasicBlock *block, Node *node)
Private Attributes
Zone * zone_
BasicBlockVector all_blocks_
BasicBlockVector nodeid_to_block_
BasicBlockVector rpo_order_
BasicBlock * start_
BasicBlock * end_
Friends
class GraphAssembler
class Scheduler
class BasicBlockInstrumentor
class RawMachineAssembler
Detailed Description
Definition at line 210 of file schedule.h.
Constructor & Destructor Documentation
Schedule() [1/2]
v8::internal::compiler::Schedule::Schedule (Zone * zone, size_t node_count_hint = 0) [explicit]
Definition at line 159 of file schedule.cc.
    : zone_(zone),
      all_blocks_(zone),
      nodeid_to_block_(zone),
      rpo_order_(zone),
      start_(NewBasicBlock()),
      end_(NewBasicBlock()) {
  nodeid_to_block_.reserve(node_count_hint);
}
References nodeid_to_block_, and v8::internal::ZoneVector< T >::reserve().
Schedule() [2/2]
v8::internal::compiler::Schedule::Schedule (const Schedule &) [delete]
Member Function Documentation
AddBranch()
void v8::internal::compiler::Schedule::AddBranch (BasicBlock * block, Node * branch, BasicBlock * tblock, BasicBlock * fblock)
Definition at line 258 of file schedule.cc.
                                             {
  CHECK_EQ(BasicBlock::kNone, block->control());
  DCHECK_EQ(IrOpcode::kBranch, branch->opcode());
  block->set_control(BasicBlock::kBranch);
  AddSuccessor(block, tblock);
  AddSuccessor(block, fblock);
  SetControlInput(block, branch);
}
References AddSuccessor(), block(), CHECK_EQ, v8::internal::compiler::BasicBlock::control(), DCHECK_EQ, v8::internal::compiler::BasicBlock::kBranch, v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::Node::opcode(), v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::RawMachineAssembler::Branch(), v8::internal::compiler::CFGBuilder::ConnectBranch(), and v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
AddCall()
void v8::internal::compiler::Schedule::AddCall (BasicBlock * block, Node * call, BasicBlock * success_block, BasicBlock * exception_block)
Definition at line 248 of file schedule.cc.
                                                    {
  CHECK_EQ(BasicBlock::kNone, block->control());
  DCHECK(IsPotentiallyThrowingCall(call->opcode()));
  block->set_control(BasicBlock::kCall);
  AddSuccessor(block, success_block);
  AddSuccessor(block, exception_block);
  SetControlInput(block, call);
}
References AddSuccessor(), block(), CHECK_EQ, v8::internal::compiler::BasicBlock::control(), v8::internal::DCHECK(), v8::internal::compiler::BasicBlock::kCall, v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::Node::opcode(), v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::CFGBuilder::ConnectCall(), and v8::internal::compiler::RawMachineAssembler::Continuations().
AddDeoptimize()
void v8::internal::compiler::Schedule::AddDeoptimize (BasicBlock * block, Node * input)
Definition at line 293 of file schedule.cc.
                                                           {
  CHECK_EQ(BasicBlock::kNone, block->control());
  block->set_control(BasicBlock::kDeoptimize);
  SetControlInput(block, input);
  if (block != end()) AddSuccessor(block, end());
}
References AddSuccessor(), block(), CHECK_EQ, v8::internal::compiler::BasicBlock::control(), end(), v8::internal::compiler::BasicBlock::kDeoptimize, v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::CFGBuilder::ConnectDeoptimize().
AddGoto()
void v8::internal::compiler::Schedule::AddGoto (BasicBlock * block, BasicBlock * succ)
Definition at line 223 of file schedule.cc.
                                                          {
  CHECK_EQ(BasicBlock::kNone, block->control());
  block->set_control(BasicBlock::kGoto);
  AddSuccessor(block, succ);
}
References AddSuccessor(), block(), CHECK_EQ, v8::internal::compiler::BasicBlock::control(), v8::internal::compiler::BasicBlock::kGoto, v8::internal::compiler::BasicBlock::kNone, and v8::internal::compiler::BasicBlock::set_control().
Referenced by v8::internal::compiler::RawMachineAssembler::Branch(), v8::internal::compiler::CFGBuilder::ConnectMerge(), v8::internal::compiler::RawMachineAssembler::Goto(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::RawMachineAssembler::Switch().
AddNode()
void v8::internal::compiler::Schedule::AddNode (BasicBlock * block, Node * node)
Definition at line 213 of file schedule.cc.
                                                    {
  if (v8_flags.trace_turbo_scheduler) {
    StdoutStream{} << "Adding #" << node->id() << ":" << node->op()->mnemonic()
                   << " to id:" << block->id() << "\n";
  }
  DCHECK(this->block(node) == nullptr || this->block(node) == block);
  block->AddNode(node);
  SetBlockForNode(block, node);
}
References v8::internal::compiler::BasicBlock::AddNode(), block(), v8::internal::DCHECK(), v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), SetBlockForNode(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::RawMachineAssembler::AddNode(), v8::internal::compiler::CFGBuilder::FixNode(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::Scheduler::SealFinalSchedule(), v8::internal::compiler::RawMachineAssembler::Switch(), and v8::internal::compiler::Scheduler::UpdatePlacement().
AddReturn()
void v8::internal::compiler::Schedule::AddReturn (BasicBlock * block, Node * input)
Definition at line 286 of file schedule.cc.
                                                       {
  CHECK_EQ(BasicBlock::kNone, block->control());
  block->set_control(BasicBlock::kReturn);
  SetControlInput(block, input);
  if (block != end()) AddSuccessor(block, end());
}
References AddSuccessor(), block(), CHECK_EQ, v8::internal::compiler::BasicBlock::control(), end(), v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::BasicBlock::kReturn, v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::CFGBuilder::ConnectReturn(), v8::internal::compiler::RawMachineAssembler::PopAndReturn(), and v8::internal::compiler::RawMachineAssembler::Return().
AddSuccessor()
void v8::internal::compiler::Schedule::AddSuccessor (BasicBlock * block, BasicBlock * succ) [private]
Definition at line 436 of file schedule.cc.
                                                               {
  block->AddSuccessor(succ);
  succ->AddPredecessor(block);
}
References v8::internal::compiler::BasicBlock::AddPredecessor(), v8::internal::compiler::BasicBlock::AddSuccessor(), and block().
Referenced by AddBranch(), AddCall(), AddDeoptimize(), AddGoto(), AddReturn(), AddSwitch(), AddTailCall(), AddThrow(), InsertBranch(), and InsertSwitch().
AddSuccessorForTesting()
void v8::internal::compiler::Schedule::AddSuccessorForTesting (BasicBlock * block, BasicBlock * succ) [inline]
Definition at line 275 of file schedule.h.
                                                                   {
    return AddSuccessor(block, succ);
  }
AddSwitch()
void v8::internal::compiler::Schedule::AddSwitch (BasicBlock * block, Node * sw, BasicBlock ** succ_blocks, size_t succ_count)
Definition at line 268 of file schedule.cc.
                                            {
  CHECK_EQ(BasicBlock::kNone, block->control());
  DCHECK_EQ(IrOpcode::kSwitch, sw->opcode());
  block->set_control(BasicBlock::kSwitch);
  for (size_t index = 0; index < succ_count; ++index) {
    AddSuccessor(block, succ_blocks[index]);
  }
  SetControlInput(block, sw);
}
References AddSuccessor(), block(), CHECK_EQ, v8::internal::compiler::BasicBlock::control(), DCHECK_EQ, v8::internal::index, v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::BasicBlock::kSwitch, v8::internal::wasm::kSwitch, v8::internal::compiler::Node::opcode(), v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::CFGBuilder::ConnectSwitch(), and v8::internal::compiler::RawMachineAssembler::Switch().
AddTailCall()
void v8::internal::compiler::Schedule::AddTailCall (BasicBlock * block, Node * input)
Definition at line 279 of file schedule.cc.
                                                         {
  CHECK_EQ(BasicBlock::kNone, block->control());
  block->set_control(BasicBlock::kTailCall);
  SetControlInput(block, input);
  if (block != end()) AddSuccessor(block, end());
}
References AddSuccessor(), block(), CHECK_EQ, v8::internal::compiler::BasicBlock::control(), end(), v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::BasicBlock::kTailCall, v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::CFGBuilder::ConnectTailCall(), and v8::internal::compiler::RawMachineAssembler::TailCallN().
AddThrow()
void v8::internal::compiler::Schedule::AddThrow (BasicBlock * block, Node * input)
Definition at line 300 of file schedule.cc.
                                                      {
  CHECK_EQ(BasicBlock::kNone, block->control());
  block->set_control(BasicBlock::kThrow);
  SetControlInput(block, input);
  if (block != end()) AddSuccessor(block, end());
}
References AddSuccessor(), block(), CHECK_EQ, v8::internal::compiler::BasicBlock::control(), end(), v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::BasicBlock::kThrow, v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::CFGBuilder::ConnectThrow(), and v8::internal::compiler::RawMachineAssembler::Unreachable().
all_blocks()
const BasicBlockVector* v8::internal::compiler::Schedule::all_blocks () const [inline]
Definition at line 279 of file schedule.h.
{ return &all_blocks_; }
Referenced by v8::internal::compiler::operator<<(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::Scheduler::SealFinalSchedule().
BasicBlockCount()
size_t v8::internal::compiler::Schedule::BasicBlockCount () const [inline]
Definition at line 223 of file schedule.h.
{ return all_blocks_.size(); }
Referenced by v8::internal::compiler::Scheduler::BuildCFG(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::Scheduler::FuseFloatingControl(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode().
block()
BasicBlock * v8::internal::compiler::Schedule::block (Node * node) const
Definition at line 169 of file schedule.cc.
                                            {
  if (node->id() < static_cast<NodeId>(nodeid_to_block_.size())) {
    return nodeid_to_block_[node->id()];
  }
  return nullptr;
}
References v8::internal::compiler::Node::id(), nodeid_to_block_, and v8::internal::ZoneVector< T >::size().
Referenced by AddBranch(), AddCall(), AddDeoptimize(), AddGoto(), AddNode(), AddReturn(), AddSuccessor(), AddSwitch(), AddTailCall(), AddThrow(), v8::internal::compiler::CFGBuilder::BuildBlockForNode(), v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses(), v8::internal::compiler::StringBuilderOptimizer::CheckPreviousNodeUses(), v8::internal::compiler::CFGBuilder::CollectSuccessorBlocks(), v8::internal::compiler::CFGBuilder::ConnectMerge(), v8::internal::compiler::Dominates(), EliminateRedundantPhiNodes(), EnsureCFGWellFormedness(), EnsureSplitEdgeForm(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::CFGBuilder::FindPredecessorBlock(), v8::internal::compiler::Scheduler::FuseFloatingControl(), v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), InsertBranch(), InsertSwitch(), v8::internal::compiler::StringBuilderOptimizer::IsLoopPhi(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsPhiContainingGivenInputs(), v8::internal::compiler::StringBuilderOptimizer::LoopContains(), NewBasicBlock(), PlanNode(), PropagateDeferredMark(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::ScheduleVerifier::Run(), SameBasicBlock(), SetBlockForNode(), SetControlInput(), v8::internal::compiler::Scheduler::UpdatePlacement(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), and v8::internal::compiler::StringBuilderOptimizer::VisitNode().
ClearBlockById()
void v8::internal::compiler::Schedule::ClearBlockById (BasicBlock::Id block_id)
Definition at line 186 of file schedule.cc.
                                                   {
  DCHECK(block_id.ToSize() < all_blocks_.size());
  all_blocks_[block_id.ToSize()] = nullptr;
}
References all_blocks_, v8::internal::DCHECK(), v8::internal::ZoneVector< T >::size(), and v8::internal::compiler::BasicBlock::Id::ToSize().
Referenced by v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
EliminateRedundantPhiNodes()
void v8::internal::compiler::Schedule::EliminateRedundantPhiNodes () [private]
Definition at line 351 of file schedule.cc.
                                          {
  // Ensure that useless phi nodes that only have a single input, identical
  // inputs, or are a self-referential loop phi,
  // -- which can happen with the automatically generated code in the CSA and
  // torque -- are pruned.
  // Since we have strucured control flow, this is enough to minimize the number
  // of phi nodes.
  bool reached_fixed_point = false;
  while (!reached_fixed_point) {
    reached_fixed_point = true;
    for (BasicBlock* block : all_blocks_) {
      int predecessor_count = static_cast<int>(block->PredecessorCount());
      for (size_t node_pos = 0; node_pos < block->NodeCount(); ++node_pos) {
        Node* node = block->NodeAt(node_pos);
        if (node->opcode() == IrOpcode::kPhi) {
          Node* first_input = node->InputAt(0);
          bool inputs_equal = true;
          for (int i = 1; i < predecessor_count; ++i) {
            Node* input = node->InputAt(i);
            if (input != first_input && input != node) {
              inputs_equal = false;
              break;
            }
          }
          if (!inputs_equal) continue;
          node->ReplaceUses(first_input);
          node->Kill();
          block->RemoveNode(block->begin() + node_pos);
          --node_pos;
          reached_fixed_point = false;
        }
      }
    }
  }
}
References all_blocks_, v8::internal::compiler::BasicBlock::begin(), block(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::BasicBlock::NodeAt(), v8::internal::compiler::BasicBlock::NodeCount(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::BasicBlock::PredecessorCount(), v8::internal::compiler::BasicBlock::RemoveNode(), and v8::internal::compiler::Node::ReplaceUses().
Referenced by EnsureCFGWellFormedness().
end()
BasicBlock* v8::internal::compiler::Schedule::end () [inline]
Definition at line 284 of file schedule.h.
{ return end_; }
Referenced by AddDeoptimize(), AddReturn(), AddTailCall(), AddThrow(), v8::internal::compiler::CFGBuilder::BuildBlocks(), v8::internal::compiler::SpecialRPONumberer::ComputeSpecialRPO(), InsertBranch(), InsertSwitch(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), and v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph().
EnsureCFGWellFormedness()
void v8::internal::compiler::Schedule::EnsureCFGWellFormedness () [private]
Definition at line 338 of file schedule.cc.
                                       {
  // Ensure there are no critical edges.
  for (BasicBlock* block : all_blocks_) {
    if (block->PredecessorCount() > 1) {
      if (block != end_) {
        EnsureSplitEdgeForm(block);
      }
    }
  }
  EliminateRedundantPhiNodes();
}
References all_blocks_, block(), EliminateRedundantPhiNodes(), end_, EnsureSplitEdgeForm(), and v8::internal::compiler::BasicBlock::PredecessorCount().
Referenced by v8::internal::compiler::RawMachineAssembler::ExportForOptimization(), and v8::internal::compiler::RawMachineAssembler::ExportForTest().
EnsureSplitEdgeForm()
void v8::internal::compiler::Schedule::EnsureSplitEdgeForm (BasicBlock * block) [private]
Definition at line 387 of file schedule.cc.
                                                    {
#ifdef DEBUG
  DCHECK(block->PredecessorCount() > 1 && block != end_);
  for (auto current_pred = block->predecessors().begin();
       current_pred != block->predecessors().end(); ++current_pred) {
    BasicBlock* pred = *current_pred;
    DCHECK_LE(pred->SuccessorCount(), 1);
  }
#endif
}
References v8::internal::ZoneVector< T >::begin(), block(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::ZoneVector< T >::end(), end_, v8::internal::compiler::BasicBlock::PredecessorCount(), v8::internal::compiler::BasicBlock::predecessors(), and v8::internal::compiler::BasicBlock::SuccessorCount().
Referenced by EnsureCFGWellFormedness().
GetBlockById()
BasicBlock * v8::internal::compiler::Schedule::GetBlockById (BasicBlock::Id block_id)
Definition at line 181 of file schedule.cc.
                                                        {
  DCHECK(block_id.ToSize() < all_blocks_.size());
  return all_blocks_[block_id.ToSize()];
}
References all_blocks_, v8::internal::DCHECK(), v8::internal::ZoneVector< T >::size(), and v8::internal::compiler::BasicBlock::Id::ToSize().
Referenced by v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::Scheduler::SealFinalSchedule().
InsertBranch()
void v8::internal::compiler::Schedule::InsertBranch (BasicBlock * block, BasicBlock * end, Node * branch, BasicBlock * tblock, BasicBlock * fblock)
Definition at line 307 of file schedule.cc.
                                                                    {
  CHECK_NE(BasicBlock::kNone, block->control());
  CHECK_EQ(BasicBlock::kNone, end->control());
  end->set_control(block->control());
  block->set_control(BasicBlock::kBranch);
  MoveSuccessors(block, end);
  AddSuccessor(block, tblock);
  AddSuccessor(block, fblock);
  if (block->control_input() != nullptr) {
    SetControlInput(end, block->control_input());
  }
  SetControlInput(block, branch);
}
References AddSuccessor(), block(), CHECK_EQ, CHECK_NE, v8::internal::compiler::BasicBlock::control(), v8::internal::compiler::BasicBlock::control_input(), end(), v8::internal::compiler::BasicBlock::kBranch, v8::internal::compiler::BasicBlock::kNone, MoveSuccessors(), v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::CFGBuilder::ConnectBranch().
InsertSwitch()
void v8::internal::compiler::Schedule::InsertSwitch (BasicBlock * block, BasicBlock * end, Node * sw, BasicBlock ** succ_blocks, size_t succ_count)
Definition at line 322 of file schedule.cc.
                                                                         {
  CHECK_NE(BasicBlock::kNone, block->control());
  CHECK_EQ(BasicBlock::kNone, end->control());
  end->set_control(block->control());
  block->set_control(BasicBlock::kSwitch);
  MoveSuccessors(block, end);
  for (size_t index = 0; index < succ_count; ++index) {
    AddSuccessor(block, succ_blocks[index]);
  }
  if (block->control_input() != nullptr) {
    SetControlInput(end, block->control_input());
  }
  SetControlInput(block, sw);
}
References AddSuccessor(), block(), CHECK_EQ, CHECK_NE, v8::internal::compiler::BasicBlock::control(), v8::internal::compiler::BasicBlock::control_input(), end(), v8::internal::index, v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::BasicBlock::kSwitch, MoveSuccessors(), v8::internal::compiler::BasicBlock::set_control(), and SetControlInput().
Referenced by v8::internal::compiler::CFGBuilder::ConnectSwitch().
IsScheduled()
bool v8::internal::compiler::Schedule::IsScheduled (Node * node)
Definition at line 176 of file schedule.cc.
                                     {
  if (node->id() >= nodeid_to_block_.size()) return false;
  return nodeid_to_block_[node->id()] != nullptr;
}
References v8::internal::compiler::Node::id(), nodeid_to_block_, and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::PrepareUsesVisitor::VisitInputs(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
MovePhis()
void v8::internal::compiler::Schedule::MovePhis (BasicBlock * from, BasicBlock * to) [private]
Definition at line 398 of file schedule.cc.
                                                        {
  for (size_t i = 0; i < from->NodeCount();) {
    Node* node = from->NodeAt(i);
    if (node->opcode() == IrOpcode::kPhi) {
      to->AddNode(node);
      from->RemoveNode(from->begin() + i);
      DCHECK_EQ(nodeid_to_block_[node->id()], from);
      nodeid_to_block_[node->id()] = to;
    } else {
      ++i;
    }
  }
}
References v8::internal::compiler::BasicBlock::AddNode(), v8::internal::compiler::BasicBlock::begin(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::NodeAt(), v8::internal::compiler::BasicBlock::NodeCount(), nodeid_to_block_, v8::internal::compiler::Node::opcode(), and v8::internal::compiler::BasicBlock::RemoveNode().
MoveSuccessors()
void v8::internal::compiler::Schedule::MoveSuccessors (BasicBlock * from, BasicBlock * to) [private]
Definition at line 441 of file schedule.cc.
                                                              {
  for (BasicBlock* const successor : from->successors()) {
    to->AddSuccessor(successor);
    for (BasicBlock*& predecessor : successor->predecessors()) {
      if (predecessor == from) predecessor = to;
    }
  }
  from->ClearSuccessors();
}
References v8::internal::compiler::BasicBlock::AddSuccessor(), v8::internal::compiler::BasicBlock::ClearSuccessors(), v8::internal::compiler::BasicBlock::predecessors(), and v8::internal::compiler::BasicBlock::successors().
Referenced by InsertBranch(), InsertSwitch(), and v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
NewBasicBlock()
BasicBlock * v8::internal::compiler::Schedule::NewBasicBlock ()
Definition at line 196 of file schedule.cc.
                                    {
  BasicBlock* block = zone_->New<BasicBlock>(
      zone_, BasicBlock::Id::FromSize(all_blocks_.size()));
  all_blocks_.push_back(block);
  return block;
}
References all_blocks_, block(), v8::internal::compiler::BasicBlock::Id::FromSize(), v8::internal::Zone::New(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), and zone_.
Referenced by v8::internal::compiler::RawMachineAssembler::Branch(), v8::internal::compiler::CFGBuilder::BuildBlockForNode(), v8::internal::compiler::RawMachineAssembler::EnsureBlock(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::RawMachineAssembler::Switch().
operator=()
Schedule& v8::internal::compiler::Schedule::operator= (const Schedule &) [delete]
PlanNode()
void v8::internal::compiler::Schedule::PlanNode (BasicBlock * block, Node * node)
Definition at line 203 of file schedule.cc.
                                                     {
  if (v8_flags.trace_turbo_scheduler) {
    StdoutStream{} << "Planning #" << node->id() << ":"
                   << node->op()->mnemonic()
                   << " for future add to id:" << block->id() << "\n";
  }
  DCHECK_NULL(this->block(node));
  SetBlockForNode(block, node);
}
References block(), DCHECK_NULL, v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), SetBlockForNode(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleNode().
PropagateDeferredMark()
void v8::internal::compiler::Schedule::PropagateDeferredMark () [private]
Definition at line 412 of file schedule.cc.
                                     {
  // Push forward the deferred block marks through newly inserted blocks and
  // other improperly marked blocks until a fixed point is reached.
  // TODO(danno): optimize the propagation
  bool done = false;
  while (!done) {
    done = true;
    for (auto block : all_blocks_) {
      if (!block->deferred()) {
        bool deferred = block->PredecessorCount() > 0;
        for (auto pred : block->predecessors()) {
          if (!pred->deferred() && (pred->rpo_number() < block->rpo_number())) {
            deferred = false;
          }
        }
        if (deferred) {
          block->set_deferred(true);
          done = false;
        }
      }
    }
  }
}
References all_blocks_, block(), v8::internal::compiler::BasicBlock::deferred(), v8::internal::compiler::BasicBlock::PredecessorCount(), v8::internal::compiler::BasicBlock::predecessors(), v8::internal::compiler::BasicBlock::rpo_number(), and v8::internal::compiler::BasicBlock::set_deferred().
Referenced by v8::internal::compiler::RawMachineAssembler::ExportForTest().
rpo_order() [1/2]
BasicBlockVector* v8::internal::compiler::Schedule::rpo_order () [inline]
Definition at line 280 of file schedule.h.
{ return &rpo_order_; }
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::Scheduler::ComputeSpecialRPO(), v8::internal::compiler::RawMachineAssembler::ExportForOptimization(), v8::internal::compiler::RawMachineAssembler::ExportForTest(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::SpecialRPONumberer::SerializeRPOIntoSchedule(), and v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph().
rpo_order() [2/2]
const BasicBlockVector* v8::internal::compiler::Schedule::rpo_order () const [inline]
Definition at line 281 of file schedule.h.
{ return &rpo_order_; }
RpoBlockCount()
size_t v8::internal::compiler::Schedule::RpoBlockCount () const [inline]
Definition at line 224 of file schedule.h.
{ return rpo_order_.size(); }
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::operator<<(), and v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph().
SameBasicBlock()
bool v8::internal::compiler::Schedule::SameBasicBlock (Node * a, Node * b) const
Definition at line 191 of file schedule.cc.
                                                    {
  BasicBlock* block = this->block(a);
  return block != nullptr && block == this->block(b);
}
References block().
SetBlockForNode()
void v8::internal::compiler::Schedule::SetBlockForNode (BasicBlock * block, Node * node) [private]
Definition at line 456 of file schedule.cc.
                                                            {
  if (node->id() >= nodeid_to_block_.size()) {
    nodeid_to_block_.resize(node->id() + 1);
  }
  nodeid_to_block_[node->id()] = block;
}
References block(), v8::internal::compiler::Node::id(), nodeid_to_block_, v8::internal::ZoneVector< T >::resize(), and v8::internal::ZoneVector< T >::size().
Referenced by AddNode(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::Scheduler::MovePlannedNodes(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), PlanNode(), and SetControlInput().
SetControlInput()
void v8::internal::compiler::Schedule::SetControlInput (BasicBlock * block, Node * node) [private]
Definition at line 451 of file schedule.cc.
                                                            {
  block->set_control_input(node);
  SetBlockForNode(block, node);
}
References block(), v8::internal::compiler::BasicBlock::set_control_input(), and SetBlockForNode().
Referenced by AddBranch(), AddCall(), AddDeoptimize(), AddReturn(), AddSwitch(), AddTailCall(), AddThrow(), InsertBranch(), and InsertSwitch().
start()
BasicBlock* v8::internal::compiler::Schedule::start () [inline]
Definition at line 283 of file schedule.h.
{ return start_; }
Referenced by v8::internal::compiler::CFGBuilder::BuildBlocks(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::ComputeSpecialRPO(), v8::internal::compiler::Scheduler::DefaultSchedulerData(), v8::internal::compiler::Scheduler::GenerateDominatorTree(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode().
zone()
Zone* v8::internal::compiler::Schedule::zone () const [inline]
Definition at line 286 of file schedule.h.
{ return zone_; }
Referenced by v8::internal::compiler::SpecialRPONumberer::BeyondEndSentinel(), and v8::internal::compiler::ScheduleVerifier::Run().
Friends And Related Function Documentation
BasicBlockInstrumentor
friend class BasicBlockInstrumentor [friend]
Definition at line 291 of file schedule.h.
GraphAssembler
friend class GraphAssembler [friend]
Definition at line 289 of file schedule.h.
RawMachineAssembler
friend class RawMachineAssembler [friend]
Definition at line 292 of file schedule.h.
Scheduler
friend class Scheduler [friend]
Definition at line 290 of file schedule.h.
Member Data Documentation
all_blocks_
BasicBlockVector v8::internal::compiler::Schedule::all_blocks_ [private]
Definition at line 315 of file schedule.h.
Referenced by ClearBlockById(), EliminateRedundantPhiNodes(), EnsureCFGWellFormedness(), GetBlockById(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), NewBasicBlock(), and PropagateDeferredMark().
end_
BasicBlock* v8::internal::compiler::Schedule::end_ [private]
Definition at line 319 of file schedule.h.
Referenced by EnsureCFGWellFormedness(), and EnsureSplitEdgeForm().
nodeid_to_block_
BasicBlockVector v8::internal::compiler::Schedule::nodeid_to_block_ [private]
Definition at line 316 of file schedule.h.
Referenced by block(), IsScheduled(), MovePhis(), Schedule(), and SetBlockForNode().
rpo_order_
BasicBlockVector v8::internal::compiler::Schedule::rpo_order_ [private]
Definition at line 317 of file schedule.h.
start_
BasicBlock* v8::internal::compiler::Schedule::start_ [private]
Definition at line 318 of file schedule.h.
zone_
Zone* v8::internal::compiler::Schedule::zone_ [private]
Definition at line 314 of file schedule.h.
Referenced by NewBasicBlock().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/schedule.h
/mnt/V8SourceCode/src/compiler/schedule.cc