v8::internal::Scanner Class Reference
#include <scanner.h>
Classes
class BookmarkScope
class ErrorState
struct Location
struct TokenDesc
Public Member Functions
void set_parser_error ()
void reset_parser_error_flag ()
bool has_parser_error () const
Scanner (Utf16CharacterStream *source, UnoptimizedCompileFlags flags)
void Initialize ()
Token::Value Next ()
Token::Value PeekAhead ()
Token::Value PeekAheadAhead ()
Token::Value current_token () const
const Location & location () const
bool has_error () const
MessageTemplate error () const
const Location & error_location () const
bool has_invalid_template_escape () const
MessageTemplate invalid_template_escape_message () const
void clear_invalid_template_escape_message ()
Location invalid_template_escape_location () const
Token::Value peek () const
const Location & peek_location () const
bool literal_contains_escapes () const
bool next_literal_contains_escapes () const
const AstRawString * CurrentSymbol (AstValueFactory *ast_value_factory) const
const AstRawString * NextSymbol (AstValueFactory *ast_value_factory) const
const AstRawString * CurrentRawSymbol (AstValueFactory *ast_value_factory) const
double DoubleValue ()
base::Vector< const uint8_t > BigIntLiteral () const
const char * CurrentLiteralAsCString (Zone *zone) const
bool CurrentMatches (Token::Value token) const
template<size_t N>
bool NextLiteralExactlyEquals (const char(&s)[N])
template<size_t N>
bool CurrentLiteralEquals (const char(&s)[N])
Location octal_position () const
void clear_octal_position ()
MessageTemplate octal_message () const
uint32_t smi_value () const
void SeekForward (int pos)
bool HasLineTerminatorBeforeNext () const
bool HasLineTerminatorAfterNext ()
bool HasLineTerminatorAfterNextNext ()
bool ScanRegExpPattern ()
std::optional< RegExpFlags > ScanRegExpFlags ()
Token::Value ScanTemplateContinuation ()
template<typename IsolateT >
DirectHandle< String > SourceUrl (IsolateT *isolate) const
template<typename IsolateT >
DirectHandle< String > SourceMappingUrl (IsolateT *isolate) const
template<typename IsolateT >
DirectHandle< String > DebugId (IsolateT *isolate) const
bool SawSourceMappingUrlMagicCommentAtSign () const
bool SawMagicCommentCompileHintsAll () const
bool HasPerFunctionCompileHint (int position)
bool FoundHtmlComment () const
const Utf16CharacterStream * stream () const
Static Public Member Functions
static constexpr base::uc32 Invalid ()
static bool IsInvalid (base::uc32 c)
Static Public Attributes
static constexpr base::uc32 kEndOfInput = Utf16CharacterStream::kEndOfInput
static constexpr base::uc32 kInvalidSequence = static_cast<base::uc32>(-1)
Private Types
enum NumberKind {
IMPLICIT_OCTAL
, BINARY
, OCTAL
, HEX
,
DECIMAL
, DECIMAL_WITH_LEADING_ZERO
 }
Private Member Functions
bool IsValidBigIntKind (NumberKind kind)
bool IsDecimalNumberKind (NumberKind kind)
template<bool capture_raw>
base::uc32 ScanOctalEscape (base::uc32 c, int length)
void Init ()
void ReportScannerError (const Location &location, MessageTemplate error)
void ReportScannerError (int pos, MessageTemplate error)
void SeekNext (size_t position)
void AddLiteralChar (base::uc32 c)
void AddLiteralChar (char c)
void AddRawLiteralChar (base::uc32 c)
void AddLiteralCharAdvance ()
template<bool capture_raw = false>
void Advance ()
template<typename FunctionType >
void AdvanceUntil (FunctionType check)
bool CombineSurrogatePair ()
void PushBack (base::uc32 ch)
base::uc32 Peek () const
Token::Value Select (Token::Value tok)
Token::Value Select (base::uc32 next, Token::Value then, Token::Value else_)
base::Vector< const uint8_t > literal_one_byte_string () const
base::Vector< const uint16_t > literal_two_byte_string () const
bool is_literal_one_byte () const
base::Vector< const uint8_t > next_literal_one_byte_string () const
base::Vector< const uint16_t > next_literal_two_byte_string () const
bool is_next_literal_one_byte () const
base::Vector< const uint8_t > raw_literal_one_byte_string () const
base::Vector< const uint16_t > raw_literal_two_byte_string () const
bool is_raw_literal_one_byte () const
template<bool capture_raw, bool unicode = false>
base::uc32 ScanHexNumber (int expected_length)
template<bool capture_raw>
base::uc32 ScanUnlimitedLengthHexNumber (base::uc32 max_value, int beg_pos)
Token::Value ScanSingleToken ()
void Scan ()
void Scan (TokenDesc *next_desc)
Token::Value SkipWhiteSpace ()
Token::Value SkipSingleHTMLComment ()
Token::Value SkipSingleLineComment ()
Token::Value SkipMagicComment (base::uc32 hash_or_at_sign)
void TryToParseMagicComment (base::uc32 hash_or_at_sign)
Token::Value SkipMultiLineComment ()
Token::Value ScanHtmlComment ()
bool ScanDigitsWithNumericSeparators (bool(*predicate)(base::uc32 ch), bool is_check_first_digit)
bool ScanDecimalDigits (bool allow_numeric_separator)
bool ScanDecimalAsSmi (uint64_t *value, bool allow_numeric_separator)
bool ScanDecimalAsSmiWithNumericSeparators (uint64_t *value)
bool ScanHexDigits ()
bool ScanBinaryDigits ()
bool ScanSignedInteger ()
bool ScanOctalDigits ()
bool ScanImplicitOctalDigits (int start_pos, NumberKind *kind)
Token::Value ScanNumber (bool seen_period)
Token::Value ScanIdentifierOrKeyword ()
Token::Value ScanIdentifierOrKeywordInner ()
Token::Value ScanIdentifierOrKeywordInnerSlow (bool escaped, bool can_be_keyword)
Token::Value ScanString ()
Token::Value ScanPrivateName ()
template<bool capture_raw>
bool ScanEscape ()
base::uc32 ScanIdentifierUnicodeEscape ()
template<bool capture_raw>
base::uc32 ScanUnicodeEscape ()
Token::Value ScanTemplateSpan ()
int source_pos ()
TokenDesc & next ()
const TokenDesc & current () const
const TokenDesc & next () const
const TokenDesc & next_next () const
const TokenDesc & next_next_next () const
Static Private Member Functions
static bool LiteralContainsEscapes (const TokenDesc &token)
Private Attributes
UnoptimizedCompileFlags flags_
TokenDesc * current_
TokenDesc * next_
TokenDesc * next_next_
TokenDesc * next_next_next_
Utf16CharacterStream *const source_
base::uc32 c0_
TokenDesc token_storage_ [4]
bool found_html_comment_
LiteralBuffer source_url_
LiteralBuffer source_mapping_url_
LiteralBuffer debug_id_
bool saw_source_mapping_url_magic_comment_at_sign_ = false
bool saw_magic_comment_compile_hints_all_ = false
bool saw_non_comment_ = false
std::vector< int > per_function_compile_hint_positions_
size_t per_function_compile_hint_positions_idx_ = 0
Location octal_pos_
MessageTemplate octal_message_
MessageTemplate scanner_error_
Location scanner_error_location_
Static Private Attributes
static const int kCharacterLookaheadBufferSize = 1
static const int kMaxAscii = 127
Detailed Description
Definition at line 215 of file scanner.h.
Member Enumeration Documentation
NumberKind
enum v8::internal::Scanner::NumberKind [private]
Enumerator
IMPLICIT_OCTAL
BINARY
OCTAL
HEX
DECIMAL
DECIMAL_WITH_LEADING_ZERO
Definition at line 455 of file scanner.h.
                  {
    IMPLICIT_OCTAL,
    BINARY,
    OCTAL,
    HEX,
    DECIMAL,
    DECIMAL_WITH_LEADING_ZERO
  };
Constructor & Destructor Documentation
Scanner()
v8::internal::Scanner::Scanner (Utf16CharacterStream * source, UnoptimizedCompileFlags flags) [explicit]
Definition at line 96 of file scanner.cc.
    : flags_(flags),
      source_(source),
      found_html_comment_(false),
      octal_pos_(Location::invalid()),
      octal_message_(MessageTemplate::kNone) {
  DCHECK_NOT_NULL(source);
}
References DCHECK_NOT_NULL, and v8::internal::kNone.
Member Function Documentation
AddLiteralChar() [1/2]
void v8::internal::Scanner::AddLiteralChar (base::uc32 c) [inline], [private]
Definition at line 537 of file scanner.h.
                                            {
    next().literal_chars.AddChar(c);
  }
Referenced by ScanDecimalAsSmi(), ScanDecimalAsSmiWithNumericSeparators(), ScanEscape(), ScanIdentifierOrKeywordInner(), ScanIdentifierOrKeywordInnerSlow(), ScanNumber(), ScanPrivateName(), ScanRegExpPattern(), ScanString(), and ScanTemplateSpan().
AddLiteralChar() [2/2]
void v8::internal::Scanner::AddLiteralChar (char c) [inline], [private]
Definition at line 541 of file scanner.h.
{ next().literal_chars.AddChar(c); }
AddLiteralCharAdvance()
void v8::internal::Scanner::AddLiteralCharAdvance () [inline], [private]
Definition at line 547 of file scanner.h.
                                         {
    AddLiteralChar(c0_);
    Advance();
  }
Referenced by ScanDecimalDigits(), ScanDigitsWithNumericSeparators(), ScanIdentifierOrKeywordInnerSlow(), ScanImplicitOctalDigits(), ScanNumber(), ScanRegExpFlags(), ScanRegExpPattern(), and ScanSignedInteger().
AddRawLiteralChar()
void v8::internal::Scanner::AddRawLiteralChar (base::uc32 c) [inline], [private]
Definition at line 543 of file scanner.h.
                                               {
    next().raw_literal_chars.AddChar(c);
  }
Referenced by ScanTemplateSpan().
Advance()
template<bool capture_raw = false>
void v8::internal::Scanner::Advance () [inline], [private]
Definition at line 554 of file scanner.h.
                 {
    if (capture_raw) {
      AddRawLiteralChar(c0_);
    }
    c0_ = source_->Advance();
  }
Referenced by ScanDecimalAsSmi(), ScanDecimalAsSmiWithNumericSeparators(), ScanDigitsWithNumericSeparators(), ScanEscape(), ScanHtmlComment(), ScanIdentifierUnicodeEscape(), ScanNumber(), ScanPrivateName(), ScanRegExpPattern(), ScanSingleToken(), ScanString(), ScanTemplateSpan(), SeekForward(), SkipMultiLineComment(), and TryToParseMagicComment().
AdvanceUntil()
template<typename FunctionType >
void v8::internal::Scanner::AdvanceUntil (FunctionType check) [inline], [private]
Definition at line 562 of file scanner.h.
                                                  {
    c0_ = source_->AdvanceUntil(check);
  }
Referenced by ScanIdentifierOrKeywordInner(), ScanString(), SkipMultiLineComment(), SkipSingleLineComment(), and SkipWhiteSpace().
BigIntLiteral()
base::Vector<const uint8_t> v8::internal::Scanner::BigIntLiteral () const [inline]
Definition at line 345 of file scanner.h.
                                                  {
    return literal_one_byte_string();
  }
clear_invalid_template_escape_message()
void v8::internal::Scanner::clear_invalid_template_escape_message () [inline]
Definition at line 313 of file scanner.h.
                                               {
    DCHECK(has_invalid_template_escape());
    current_->invalid_template_escape_message = MessageTemplate::kNone;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::ParserBase< Impl >::CheckTemplateEscapes().
clear_octal_position()
void v8::internal::Scanner::clear_octal_position () [inline]
Definition at line 382 of file scanner.h.
                              {
    octal_pos_ = Location::invalid();
    octal_message_ = MessageTemplate::kNone;
  }
Referenced by v8::internal::ParserBase< Impl >::CheckStrictOctalLiteral().
CombineSurrogatePair()
bool v8::internal::Scanner::CombineSurrogatePair () [inline], [private]
Definition at line 566 of file scanner.h.
                              {
    DCHECK(!unibrow::Utf16::IsLeadSurrogate(kEndOfInput));
    if (unibrow::Utf16::IsLeadSurrogate(c0_)) {
      base::uc32 c1 = source_->Advance();
      DCHECK(!unibrow::Utf16::IsTrailSurrogate(kEndOfInput));
      if (unibrow::Utf16::IsTrailSurrogate(c1)) {
        c0_ = unibrow::Utf16::CombineSurrogatePair(c0_, c1);
        return true;
      }
      source_->Back();
    }
    return false;
  }
References unibrow::Utf16::CombineSurrogatePair(), v8::internal::DCHECK(), unibrow::Utf16::IsLeadSurrogate(), and unibrow::Utf16::IsTrailSurrogate().
Referenced by ScanIdentifierOrKeywordInnerSlow(), ScanPrivateName(), and ScanSingleToken().
current()
const TokenDesc& v8::internal::Scanner::current () const [inline], [private]
Definition at line 742 of file scanner.h.
{ return *current_; }
Referenced by DoubleValue(), Next(), and Scan().
current_token()
Token::Value v8::internal::Scanner::current_token () const [inline]
Definition at line 294 of file scanner.h.
{ return current().token; }
Referenced by v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper(), and v8::internal::ParserBase< Impl >::ParseForStatement().
CurrentLiteralAsCString()
const char * v8::internal::Scanner::CurrentLiteralAsCString (Zone * zone) const
Definition at line 1167 of file scanner.cc.
                                                             {
  DCHECK(is_literal_one_byte());
  base::Vector<const uint8_t> vector = literal_one_byte_string();
  int length = vector.length();
  char* buffer = zone->AllocateArray<char>(length + 1);
  memcpy(buffer, vector.begin(), length);
  buffer[length] = '\0';
  return buffer;
}
References v8::internal::Zone::AllocateArray(), v8::base::Vector< T >::begin(), v8::internal::DCHECK(), is_literal_one_byte(), v8::base::Vector< T >::length(), v8::internal::length, and literal_one_byte_string().
CurrentLiteralEquals()
template<size_t N>
bool v8::internal::Scanner::CurrentLiteralEquals (const char(&) s[N]) [inline]
Definition at line 371 of file scanner.h.
                                                {
    DCHECK(current().CanAccessLiteral());
    if (!is_literal_one_byte()) return false;
    base::Vector<const uint8_t> current = literal_one_byte_string();
    const char* chars = reinterpret_cast<const char*>(current.begin());
    return current.length() == N - 1 && strncmp(s, chars, N - 1) == 0;
  }
References v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::base::Vector< T >::length(), and v8::internal::N.
CurrentMatches()
bool v8::internal::Scanner::CurrentMatches (Token::Value token) const [inline]
Definition at line 351 of file scanner.h.
                                                     {
    DCHECK(Token::IsKeyword(token));
    return current().token == token;
  }
References v8::internal::DCHECK(), and v8::internal::Token::IsKeyword().
CurrentRawSymbol()
const AstRawString * v8::internal::Scanner::CurrentRawSymbol (AstValueFactory * ast_value_factory) const
Definition at line 1141 of file scanner.cc.
                                              {
  if (is_raw_literal_one_byte()) {
    return ast_value_factory->GetOneByteString(raw_literal_one_byte_string());
  }
  return ast_value_factory->GetTwoByteString(raw_literal_two_byte_string());
}
References v8::internal::AstValueFactory::GetOneByteString(), v8::internal::AstValueFactory::GetTwoByteString(), is_raw_literal_one_byte(), raw_literal_one_byte_string(), and raw_literal_two_byte_string().
CurrentSymbol()
const AstRawString * v8::internal::Scanner::CurrentSymbol (AstValueFactory * ast_value_factory) const
Definition at line 1125 of file scanner.cc.
                                              {
  if (is_literal_one_byte()) {
    return ast_value_factory->GetOneByteString(literal_one_byte_string());
  }
  return ast_value_factory->GetTwoByteString(literal_two_byte_string());
}
References v8::internal::AstValueFactory::GetOneByteString(), v8::internal::AstValueFactory::GetTwoByteString(), is_literal_one_byte(), literal_one_byte_string(), and literal_two_byte_string().
Referenced by v8::internal::PreParser::GetIdentifier().
DebugId()
template<typename IsolateT >
template DirectHandle< String > v8::internal::Scanner::DebugId (IsolateT * isolate) const
Definition at line 717 of file scanner.cc.
                                                             {
  DirectHandle<String> tmp;
  if (debug_id_.length() > 0) {
    tmp = debug_id_.Internalize(isolate);
  }
  return tmp;
}
References debug_id_, v8::internal::LiteralBuffer::Internalize(), and v8::internal::LiteralBuffer::length().
Referenced by v8::internal::Parser::HandleDebugMagicComments().
DoubleValue()
double v8::internal::Scanner::DoubleValue ()
Definition at line 1150 of file scanner.cc.
                            {
  DCHECK(is_literal_one_byte());
  switch (current().number_kind) {
    case IMPLICIT_OCTAL:
      return ImplicitOctalStringToDouble(literal_one_byte_string());
    case BINARY:
      return BinaryStringToDouble(literal_one_byte_string());
    case OCTAL:
      return OctalStringToDouble(literal_one_byte_string());
    case HEX:
      return HexStringToDouble(literal_one_byte_string());
    case DECIMAL:
    case DECIMAL_WITH_LEADING_ZERO:
      return StringToDouble(literal_one_byte_string(), NO_CONVERSION_FLAG);
  }
}
References BINARY, v8::internal::BinaryStringToDouble(), current(), v8::internal::DCHECK(), DECIMAL, DECIMAL_WITH_LEADING_ZERO, HEX, v8::internal::HexStringToDouble(), IMPLICIT_OCTAL, v8::internal::ImplicitOctalStringToDouble(), is_literal_one_byte(), literal_one_byte_string(), v8::internal::NO_CONVERSION_FLAG, OCTAL, v8::internal::OctalStringToDouble(), and v8::internal::StringToDouble().
error()
MessageTemplate v8::internal::Scanner::error () const [inline]
Definition at line 302 of file scanner.h.
{ return scanner_error_; }
error_location()
const Location& v8::internal::Scanner::error_location () const [inline]
Definition at line 303 of file scanner.h.
{ return scanner_error_location_; }
FoundHtmlComment()
bool v8::internal::Scanner::FoundHtmlComment () const [inline]
Definition at line 445 of file scanner.h.
{ return found_html_comment_; }
Referenced by v8::internal::Parser::UpdateStatistics().
has_error()
bool v8::internal::Scanner::has_error () const [inline]
Definition at line 301 of file scanner.h.
{ return scanner_error_ != MessageTemplate::kNone; }
Referenced by ScanTemplateSpan().
has_invalid_template_escape()
bool v8::internal::Scanner::has_invalid_template_escape () const [inline]
Definition at line 305 of file scanner.h.
                                           {
    return current().invalid_template_escape_message != MessageTemplate::kNone;
  }
has_parser_error()
bool v8::internal::Scanner::has_parser_error () const [inline]
Definition at line 258 of file scanner.h.
                                          {
    return source_->has_parser_error();
  }
Referenced by v8::internal::ParserBase< Impl >::has_error(), and Scan().
HasLineTerminatorAfterNext()
bool v8::internal::Scanner::HasLineTerminatorAfterNext () [inline]
Definition at line 403 of file scanner.h.
                                    {
    Token::Value ensure_next_next = PeekAhead();
    USE(ensure_next_next);
    return next_next().after_line_terminator;
  }
References USE.
Referenced by v8::internal::ParserBase< Impl >::ParseExpressionOrLabelledStatement().
HasLineTerminatorAfterNextNext()
bool v8::internal::Scanner::HasLineTerminatorAfterNextNext () [inline]
Definition at line 409 of file scanner.h.
                                        {
    Token::Value ensure_next_next_next = PeekAheadAhead();
    USE(ensure_next_next_next);
    return next_next_next().after_line_terminator;
  }
References USE.
HasLineTerminatorBeforeNext()
bool v8::internal::Scanner::HasLineTerminatorBeforeNext () const [inline]
Definition at line 399 of file scanner.h.
                                           {
    return next().after_line_terminator;
  }
Referenced by v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral().
HasPerFunctionCompileHint()
bool v8::internal::Scanner::HasPerFunctionCompileHint (int position)
Definition at line 351 of file scanner.cc.
                                                    {
  // Allow off-by-<slack> in the compile hints positions, to account for adding
  // newlines at the end of the comment, function positions being off-by-one,
  // etc.
  const int kSlack = 3;
  while (per_function_compile_hint_positions_idx_ <
             per_function_compile_hint_positions_.size() &&
         per_function_compile_hint_positions_
                 [per_function_compile_hint_positions_idx_] <
             position - kSlack) {
    ++per_function_compile_hint_positions_idx_;
  }
  if (per_function_compile_hint_positions_idx_ >=
      per_function_compile_hint_positions_.size()) {
    return false;
  }
  int hint_position = per_function_compile_hint_positions_
      [per_function_compile_hint_positions_idx_];
  return hint_position >= position - kSlack &&
         hint_position <= position + kSlack;
}
References per_function_compile_hint_positions_, and per_function_compile_hint_positions_idx_.
Referenced by v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral().
Init()
void v8::internal::Scanner::Init () [inline], [private]
Definition at line 508 of file scanner.h.
              {
    // Set c0_ (one character ahead)
    static_assert(kCharacterLookaheadBufferSize == 1);
    Advance();
    current_ = &token_storage_[0];
    next_ = &token_storage_[1];
    next_next_ = &token_storage_[2];
    next_next_next_ = &token_storage_[3];
    found_html_comment_ = false;
    scanner_error_ = MessageTemplate::kNone;
  }
Referenced by Initialize().
Initialize()
void v8::internal::Scanner::Initialize ()
Definition at line 105 of file scanner.cc.
                         {
  // Need to capture identifiers in order to recognize "get" and "set"
  // in object literals.
  Init();
  next().after_line_terminator = true;
  Scan();
}
References v8::internal::Scanner::TokenDesc::after_line_terminator, Init(), next(), and Scan().
Referenced by v8::internal::Parser::ParseFunction(), v8::internal::Parser::ParseOnBackground(), and v8::internal::Parser::ParseProgram().
Invalid()
static constexpr base::uc32 v8::internal::Scanner::Invalid () [inline], [static], [constexpr]
Definition at line 280 of file scanner.h.
{ return Scanner::kInvalidSequence; }
References kInvalidSequence.
Referenced by IsInvalid(), ScanHexNumber(), ScanIdentifierOrKeywordInner(), ScanIdentifierOrKeywordInnerSlow(), ScanIdentifierUnicodeEscape(), ScanUnicodeEscape(), and ScanUnlimitedLengthHexNumber().
invalid_template_escape_location()
Location v8::internal::Scanner::invalid_template_escape_location () const [inline]
Definition at line 318 of file scanner.h.
                                                    {
    DCHECK(has_invalid_template_escape());
    return current().invalid_template_escape_location;
  }
References v8::internal::DCHECK().
invalid_template_escape_message()
MessageTemplate v8::internal::Scanner::invalid_template_escape_message () const [inline]
Definition at line 308 of file scanner.h.
                                                          {
    DCHECK(has_invalid_template_escape());
    return current().invalid_template_escape_message;
  }
References v8::internal::DCHECK().
is_literal_one_byte()
bool v8::internal::Scanner::is_literal_one_byte () const [inline], [private]
Definition at line 627 of file scanner.h.
                                   {
    DCHECK(current().CanAccessLiteral() || Token::IsKeyword(current().token) ||
           current().token == Token::kEscapedKeyword);
    return current().literal_chars.is_one_byte();
  }
References v8::internal::DCHECK(), and v8::internal::Token::IsKeyword().
Referenced by CurrentLiteralAsCString(), CurrentSymbol(), and DoubleValue().
is_next_literal_one_byte()
bool v8::internal::Scanner::is_next_literal_one_byte () const [inline], [private]
Definition at line 642 of file scanner.h.
                                        {
    DCHECK(next().CanAccessLiteral());
    return next().literal_chars.is_one_byte();
  }
References v8::internal::DCHECK().
Referenced by NextSymbol().
is_raw_literal_one_byte()
bool v8::internal::Scanner::is_raw_literal_one_byte () const [inline], [private]
Definition at line 654 of file scanner.h.
                                       {
    DCHECK(current().CanAccessRawLiteral());
    return current().raw_literal_chars.is_one_byte();
  }
References v8::internal::DCHECK().
Referenced by CurrentRawSymbol().
IsDecimalNumberKind()
bool v8::internal::Scanner::IsDecimalNumberKind (NumberKind kind) [inline], [private]
Definition at line 496 of file scanner.h.
                                                   {
    return base::IsInRange(kind, DECIMAL, DECIMAL_WITH_LEADING_ZERO);
  }
Referenced by ScanNumber().
IsInvalid()
bool v8::internal::Scanner::IsInvalid (base::uc32 c) [static]
Definition at line 114 of file scanner.cc.
                                  {
  DCHECK(c == Invalid() || base::IsInRange(c, 0u, String::kMaxCodePoint));
  return c == Scanner::Invalid();
}
References v8::internal::DCHECK(), Invalid(), and v8::internal::String::kMaxCodePoint.
Referenced by ScanEscape().
IsValidBigIntKind()
bool v8::internal::Scanner::IsValidBigIntKind (NumberKind kind) [inline], [private]
Definition at line 492 of file scanner.h.
                                                 {
    return base::IsInRange(kind, BINARY, DECIMAL);
  }
Referenced by ScanNumber().
literal_contains_escapes()
bool v8::internal::Scanner::literal_contains_escapes () const [inline]
Definition at line 330 of file scanner.h.
                                        {
    return LiteralContainsEscapes(current());
  }
Referenced by v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper(), and v8::internal::ParserBase< Impl >::ParseForStatement().
literal_one_byte_string()
base::Vector<const uint8_t> v8::internal::Scanner::literal_one_byte_string () const [inline], [private]
Definition at line 617 of file scanner.h.
                                                            {
    DCHECK(current().CanAccessLiteral() || Token::IsKeyword(current().token) ||
           current().token == Token::kEscapedKeyword);
    return current().literal_chars.one_byte_literal();
  }
References v8::internal::DCHECK(), and v8::internal::Token::IsKeyword().
Referenced by CurrentLiteralAsCString(), CurrentSymbol(), and DoubleValue().
literal_two_byte_string()
base::Vector<const uint16_t> v8::internal::Scanner::literal_two_byte_string () const [inline], [private]
Definition at line 622 of file scanner.h.
                                                             {
    DCHECK(current().CanAccessLiteral() || Token::IsKeyword(current().token) ||
           current().token == Token::kEscapedKeyword);
    return current().literal_chars.two_byte_literal();
  }
References v8::internal::DCHECK(), and v8::internal::Token::IsKeyword().
Referenced by CurrentSymbol().
LiteralContainsEscapes()
static bool v8::internal::Scanner::LiteralContainsEscapes (const TokenDesc & token) [inline], [static], [private]
Definition at line 726 of file scanner.h.
                                                             {
    Location location = token.location;
    int source_length = (location.end_pos - location.beg_pos);
    if (token.token == Token::kString) {
      // Subtract delimiters.
      source_length -= 2;
    }
    return token.literal_chars.length() != source_length;
  }
References v8::internal::Scanner::Location::beg_pos, v8::internal::Scanner::Location::end_pos, v8::internal::LiteralBuffer::length(), v8::internal::Scanner::TokenDesc::literal_chars, v8::internal::Scanner::TokenDesc::location, and v8::internal::Scanner::TokenDesc::token.
location()
const Location& v8::internal::Scanner::location () const [inline]
Definition at line 298 of file scanner.h.
{ return current().location; }
Referenced by v8::internal::ParserBase< Impl >::end_position(), v8::internal::ParserBase< Impl >::ParseArguments(), v8::internal::ParserBase< Impl >::ParseArrowParametersWithRest(), v8::internal::ParserBase< Impl >::ParseClassExpression(), v8::internal::ParserBase< Impl >::ParseConditionalChainExpression(), v8::internal::ParserBase< Impl >::ParseFunctionExpression(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::ParserBase< Impl >::ParseReturnStatement(), v8::internal::ParserBase< Impl >::ParseVariableDeclarations(), v8::internal::ParserBase< Impl >::position(), v8::internal::PreParser::PreParseFunction(), v8::internal::ParserBase< Impl >::ReportUnexpectedToken(), SeekForward(), and SeekNext().
Next()
Token::Value v8::internal::Scanner::Next ()
Definition at line 162 of file scanner.cc.
                         {
  // Rotate through tokens.
  TokenDesc* previous = current_;
  current_ = next_;
  // Either we already have the next token lined up, in which case next_next_
  // simply becomes next_. In that case we use current_ as new next_next_ and
  // clear its token to indicate that it wasn't scanned yet. Otherwise we use
  // current_ as next_ and scan into it, leaving next_next_ uninitialized.
  if (V8_LIKELY(next_next().token == Token::kUninitialized)) {
    DCHECK(next_next_next().token == Token::kUninitialized);
    next_ = previous;
    // User 'previous' instead of 'next_' because for some reason the compiler
    // thinks 'next_' could be modified before the entry into Scan.
    previous->after_line_terminator = false;
    Scan(previous);
  } else {
    next_ = next_next_;
    if (V8_LIKELY(next_next_next().token == Token::kUninitialized)) {
      next_next_ = previous;
    } else {
      next_next_ = next_next_next_;
      next_next_next_ = previous;
    }
    previous->token = Token::kUninitialized;
    DCHECK_NE(Token::kUninitialized, current().token);
  }
  return current().token;
}
References v8::internal::Scanner::TokenDesc::after_line_terminator, current(), current_, v8::internal::DCHECK(), DCHECK_NE, next_, next_next(), next_next_, next_next_next(), next_next_next_, Scan(), v8::internal::Scanner::TokenDesc::token, and V8_LIKELY.
Referenced by v8::internal::ParserBase< Impl >::Consume(), and v8::internal::ParserBase< Impl >::Next().
next() [1/2]
TokenDesc& v8::internal::Scanner::next () [inline], [private]
Definition at line 740 of file scanner.h.
{ return *next_; }
Referenced by Initialize(), PeekAhead(), PeekAheadAhead(), Scan(), ScanIdentifierOrKeyword(), ScanIdentifierOrKeywordInner(), ScanIdentifierOrKeywordInnerSlow(), ScanNumber(), ScanPrivateName(), ScanRegExpFlags(), ScanRegExpPattern(), ScanSingleToken(), ScanString(), ScanTemplateSpan(), SeekForward(), SeekNext(), SkipMultiLineComment(), and SkipWhiteSpace().
next() [2/2]
const TokenDesc& v8::internal::Scanner::next () const [inline], [private]
Definition at line 743 of file scanner.h.
{ return *next_; }
next_literal_contains_escapes()
bool v8::internal::Scanner::next_literal_contains_escapes () const [inline]
Definition at line 334 of file scanner.h.
                                             {
    return LiteralContainsEscapes(next());
  }
Referenced by v8::internal::ParserBase< Impl >::PeekContextualKeyword().
next_literal_one_byte_string()
base::Vector<const uint8_t> v8::internal::Scanner::next_literal_one_byte_string () const [inline], [private]
Definition at line 634 of file scanner.h.
                                                                 {
    DCHECK(next().CanAccessLiteral());
    return next().literal_chars.one_byte_literal();
  }
References v8::internal::DCHECK().
Referenced by NextSymbol().
next_literal_two_byte_string()
base::Vector<const uint16_t> v8::internal::Scanner::next_literal_two_byte_string () const [inline], [private]
Definition at line 638 of file scanner.h.
                                                                  {
    DCHECK(next().CanAccessLiteral());
    return next().literal_chars.two_byte_literal();
  }
References v8::internal::DCHECK().
Referenced by NextSymbol().
next_next()
const TokenDesc& v8::internal::Scanner::next_next () const [inline], [private]
Definition at line 744 of file scanner.h.
{ return *next_next_; }
Referenced by Next(), PeekAhead(), PeekAheadAhead(), Scan(), and ScanRegExpPattern().
next_next_next()
const TokenDesc& v8::internal::Scanner::next_next_next () const [inline], [private]
Definition at line 745 of file scanner.h.
{ return *next_next_next_; }
Referenced by Next(), PeekAheadAhead(), and Scan().
NextLiteralExactlyEquals()
template<size_t N>
bool v8::internal::Scanner::NextLiteralExactlyEquals (const char(&) s[N]) [inline]
Definition at line 357 of file scanner.h.
                                                    {
    DCHECK(next().CanAccessLiteral());
    // The length of the token is used to make sure the literal equals without
    // taking escape sequences (e.g., "use \x73trict") or line continuations
    // (e.g., "use \(newline) strict") into account.
    if (!is_next_literal_one_byte()) return false;
    if (peek_location().length() != N + 1) return false;
    base::Vector<const uint8_t> next = next_literal_one_byte_string();
    const char* chars = reinterpret_cast<const char*>(next.begin());
    return next.length() == N - 1 && strncmp(s, chars, N - 1) == 0;
  }
References v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::base::Vector< T >::length(), v8::internal::length, and v8::internal::N.
NextSymbol()
const AstRawString * v8::internal::Scanner::NextSymbol (AstValueFactory * ast_value_factory) const
Definition at line 1133 of file scanner.cc.
                                              {
  if (is_next_literal_one_byte()) {
    return ast_value_factory->GetOneByteString(next_literal_one_byte_string());
  }
  return ast_value_factory->GetTwoByteString(next_literal_two_byte_string());
}
References v8::internal::AstValueFactory::GetOneByteString(), v8::internal::AstValueFactory::GetTwoByteString(), is_next_literal_one_byte(), next_literal_one_byte_string(), and next_literal_two_byte_string().
Referenced by v8::internal::ParserBase< Impl >::GetNextSymbolForRegExpLiteral(), and v8::internal::ParserBase< Impl >::PeekContextualKeyword().
octal_message()
MessageTemplate v8::internal::Scanner::octal_message () const [inline]
Definition at line 386 of file scanner.h.
{ return octal_message_; }
Referenced by v8::internal::ParserBase< Impl >::CheckStrictOctalLiteral().
octal_position()
Location v8::internal::Scanner::octal_position () const [inline]
Definition at line 381 of file scanner.h.
{ return octal_pos_; }
Referenced by v8::internal::ParserBase< Impl >::CheckStrictOctalLiteral().
peek()
Token::Value v8::internal::Scanner::peek () const [inline]
Definition at line 326 of file scanner.h.
{ return next().token; }
Referenced by v8::internal::ParserBase< Impl >::Check(), and v8::internal::ParserBase< Impl >::peek().
Peek()
base::uc32 v8::internal::Scanner::Peek () const [inline], [private]
Definition at line 587 of file scanner.h.
{ return source_->Peek(); }
Referenced by ScanHtmlComment(), ScanSingleToken(), and ScanTemplateSpan().
peek_location()
const Location& v8::internal::Scanner::peek_location () const [inline]
Definition at line 328 of file scanner.h.
{ return next().location; }
Referenced by v8::internal::ParserBase< Impl >::ParseAccessorPropertyOrAutoAccessors(), v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), v8::internal::ParserBase< Impl >::ParseClassPropertyDefinition(), v8::internal::ParserBase< Impl >::ParseForStatement(), v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation(), v8::internal::ParserBase< Impl >::ParseObjectPropertyDefinition(), v8::internal::ParserBase< Impl >::ParseStatementList(), v8::internal::PreParser::ParseStatementListAndLogFunction(), v8::internal::ParserBase< Impl >::peek_end_position(), v8::internal::ParserBase< Impl >::peek_position(), and v8::internal::SourceRangeScope::SourceRangeScope().
PeekAhead()
Token::Value v8::internal::Scanner::PeekAhead ()
Definition at line 193 of file scanner.cc.
                              {
  DCHECK(next().token != Token::kDiv);
  DCHECK(next().token != Token::kAssignDiv);
  if (next_next().token != Token::kUninitialized) {
    return next_next().token;
  }
  TokenDesc* temp = next_;
  next_ = next_next_;
  next().after_line_terminator = false;
  Scan();
  next_next_ = next_;
  next_ = temp;
  return next_next().token;
}
References v8::internal::Scanner::TokenDesc::after_line_terminator, v8::internal::DCHECK(), next(), next_, next_next(), next_next_, Scan(), and v8::internal::Scanner::TokenDesc::token.
Referenced by v8::internal::ParserBase< Impl >::PeekAhead().
PeekAheadAhead()
Token::Value v8::internal::Scanner::PeekAheadAhead ()
Definition at line 209 of file scanner.cc.
                                   {
  if (next_next_next().token != Token::kUninitialized) {
    return next_next_next().token;
  }
  // PeekAhead() must be called first in order to call PeekAheadAhead().
  DCHECK(next_next().token != Token::kUninitialized);
  TokenDesc* temp = next_;
  TokenDesc* temp_next = next_next_;
  next_ = next_next_next_;
  next().after_line_terminator = false;
  Scan();
  next_next_next_ = next_;
  next_next_ = temp_next;
  next_ = temp;
  return next_next_next().token;
}
References v8::internal::Scanner::TokenDesc::after_line_terminator, v8::internal::DCHECK(), next(), next_, next_next(), next_next_, next_next_next(), next_next_next_, Scan(), and v8::internal::Scanner::TokenDesc::token.
Referenced by v8::internal::ParserBase< Impl >::PeekAheadAhead().
PushBack()
void v8::internal::Scanner::PushBack (base::uc32 ch) [inline], [private]
Definition at line 580 of file scanner.h.
                             {
    DCHECK(IsInvalid(c0_) ||
           base::IsInRange(c0_, 0u, unibrow::Utf16::kMaxNonSurrogateCharCode));
    source_->Back();
    c0_ = ch;
  }
References v8::internal::DCHECK(), and unibrow::Utf16::kMaxNonSurrogateCharCode.
Referenced by ScanHtmlComment(), and ScanSingleToken().
raw_literal_one_byte_string()
base::Vector<const uint8_t> v8::internal::Scanner::raw_literal_one_byte_string () const [inline], [private]
Definition at line 646 of file scanner.h.
                                                                {
    DCHECK(current().CanAccessRawLiteral());
    return current().raw_literal_chars.one_byte_literal();
  }
References v8::internal::DCHECK().
Referenced by CurrentRawSymbol().
raw_literal_two_byte_string()
base::Vector<const uint16_t> v8::internal::Scanner::raw_literal_two_byte_string () const [inline], [private]
Definition at line 650 of file scanner.h.
                                                                 {
    DCHECK(current().CanAccessRawLiteral());
    return current().raw_literal_chars.two_byte_literal();
  }
References v8::internal::DCHECK().
Referenced by CurrentRawSymbol().
ReportScannerError() [1/2]
void v8::internal::Scanner::ReportScannerError (const Location & location, MessageTemplate error) [inline], [private]
Definition at line 522 of file scanner.h.
                                                                           {
    if (has_error()) return;
    scanner_error_ = error;
    scanner_error_location_ = location;
  }
Referenced by ScanDecimalAsSmiWithNumericSeparators(), ScanDecimalDigits(), ScanDigitsWithNumericSeparators(), ScanHexNumber(), ScanNumber(), ScanPrivateName(), ScanUnicodeEscape(), ScanUnlimitedLengthHexNumber(), and SkipSingleHTMLComment().
ReportScannerError() [2/2]
void v8::internal::Scanner::ReportScannerError (int pos, MessageTemplate error) [inline], [private]
Definition at line 528 of file scanner.h.
                                                          {
    if (has_error()) return;
    scanner_error_ = error;
    scanner_error_location_ = Location(pos, pos + 1);
  }
reset_parser_error_flag()
void v8::internal::Scanner::reset_parser_error_flag () [inline]
Definition at line 255 of file scanner.h.
                                           {
    source_->reset_parser_error_flag();
  }
SawMagicCommentCompileHintsAll()
bool v8::internal::Scanner::SawMagicCommentCompileHintsAll () const [inline]
Definition at line 439 of file scanner.h.
                                              {
    return saw_magic_comment_compile_hints_all_;
  }
Referenced by v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), and v8::internal::Parser::UpdateStatistics().
SawSourceMappingUrlMagicCommentAtSign()
bool v8::internal::Scanner::SawSourceMappingUrlMagicCommentAtSign () const [inline]
Definition at line 435 of file scanner.h.
                                                     {
    return saw_source_mapping_url_magic_comment_at_sign_;
  }
Referenced by v8::internal::Parser::UpdateStatistics().
Scan() [1/2]
void v8::internal::Scanner::Scan () [inline], [private]
Definition at line 575 of file scanner-inl.h.
{ Scan(next_); }
References next_.
Referenced by Initialize(), Next(), PeekAhead(), PeekAheadAhead(), SeekForward(), and SeekNext().
Scan() [2/2]
void v8::internal::Scanner::Scan (TokenDesc * next_desc) [inline], [private]
Definition at line 560 of file scanner-inl.h.
                                       {
  DCHECK_EQ(next_desc, &next());
  next_desc->token = ScanSingleToken();
  DCHECK_IMPLIES(has_parser_error(), next_desc->token == Token::kIllegal);
  next_desc->location.end_pos = source_pos();
#ifdef DEBUG
  SanityCheckTokenDesc(current());
  SanityCheckTokenDesc(next());
  SanityCheckTokenDesc(next_next());
  SanityCheckTokenDesc(next_next_next());
#endif
}
References current(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Scanner::Location::end_pos, has_parser_error(), v8::internal::Scanner::TokenDesc::location, next(), next_next(), next_next_next(), ScanSingleToken(), source_pos(), and v8::internal::Scanner::TokenDesc::token.
ScanBinaryDigits()
bool v8::internal::Scanner::ScanBinaryDigits () [private]
Definition at line 816 of file scanner.cc.
                               {
  return ScanDigitsWithNumericSeparators(&IsBinaryDigit, true);
}
References v8::internal::IsBinaryDigit(), and ScanDigitsWithNumericSeparators().
Referenced by ScanNumber().
ScanDecimalAsSmi()
bool v8::internal::Scanner::ScanDecimalAsSmi (uint64_t * value, bool allow_numeric_separator) [private]
Definition at line 802 of file scanner.cc.
                                                                            {
  if (allow_numeric_separator) {
    return ScanDecimalAsSmiWithNumericSeparators(value);
  }
  while (IsDecimalDigit(c0_)) {
    *value = 10 * *value + (c0_ - '0');
    base::uc32 first_char = c0_;
    Advance();
    AddLiteralChar(first_char);
  }
  return true;
}
References AddLiteralChar(), Advance(), c0_, v8::internal::IsDecimalDigit(), ScanDecimalAsSmiWithNumericSeparators(), and v8::internal::value.
Referenced by ScanNumber().
ScanDecimalAsSmiWithNumericSeparators()
bool v8::internal::Scanner::ScanDecimalAsSmiWithNumericSeparators (uint64_t * value) [private]
Definition at line 773 of file scanner.cc.
                                                                   {
  bool separator_seen = false;
  while (IsDecimalDigit(c0_) || c0_ == '_') {
    if (c0_ == '_') {
      Advance();
      if (c0_ == '_') {
        ReportScannerError(Location(source_pos(), source_pos() + 1),
                           MessageTemplate::kContinuousNumericSeparator);
        return false;
      }
      separator_seen = true;
      continue;
    }
    separator_seen = false;
    *value = 10 * *value + (c0_ - '0');
    base::uc32 first_char = c0_;
    Advance();
    AddLiteralChar(first_char);
  }
  if (separator_seen) {
    ReportScannerError(Location(source_pos(), source_pos() + 1),
                       MessageTemplate::kTrailingNumericSeparator);
    return false;
  }
  return true;
}
References AddLiteralChar(), Advance(), c0_, v8::internal::IsDecimalDigit(), ReportScannerError(), source_pos(), and v8::internal::value.
Referenced by ScanDecimalAsSmi().
ScanDecimalDigits()
bool v8::internal::Scanner::ScanDecimalDigits (bool allow_numeric_separator) [private]
Definition at line 758 of file scanner.cc.
                                                            {
  if (allow_numeric_separator) {
    return ScanDigitsWithNumericSeparators(&IsDecimalDigit, false);
  }
  while (IsDecimalDigit(c0_)) {
    AddLiteralCharAdvance();
  }
  if (c0_ == '_') {
    ReportScannerError(Location(source_pos(), source_pos() + 1),
                       MessageTemplate::kInvalidOrUnexpectedToken);
    return false;
  }
  return true;
}
References AddLiteralCharAdvance(), c0_, v8::internal::IsDecimalDigit(), ReportScannerError(), ScanDigitsWithNumericSeparators(), and source_pos().
Referenced by ScanNumber(), and ScanSignedInteger().
ScanDigitsWithNumericSeparators()
bool v8::internal::Scanner::ScanDigitsWithNumericSeparators (bool(*)(base::uc32 ch) predicate, bool is_check_first_digit) [private]
Definition at line 728 of file scanner.cc.
                                                                         {
  // we must have at least one digit after 'x'/'b'/'o'
  if (is_check_first_digit && !predicate(c0_)) return false;
  bool separator_seen = false;
  while (predicate(c0_) || c0_ == '_') {
    if (c0_ == '_') {
      Advance();
      if (c0_ == '_') {
        ReportScannerError(Location(source_pos(), source_pos() + 1),
                           MessageTemplate::kContinuousNumericSeparator);
        return false;
      }
      separator_seen = true;
      continue;
    }
    separator_seen = false;
    AddLiteralCharAdvance();
  }
  if (separator_seen) {
    ReportScannerError(Location(source_pos(), source_pos() + 1),
                       MessageTemplate::kTrailingNumericSeparator);
    return false;
  }
  return true;
}
References AddLiteralCharAdvance(), Advance(), c0_, ReportScannerError(), and source_pos().
Referenced by ScanBinaryDigits(), ScanDecimalDigits(), ScanHexDigits(), and ScanOctalDigits().
ScanEscape()
template<bool capture_raw>
bool v8::internal::Scanner::ScanEscape [private]
Definition at line 471 of file scanner.cc.
                         {
  base::uc32 c = c0_;
  Advance<capture_raw>();
  // Skip escaped newlines.
  DCHECK(!unibrow::IsLineTerminator(kEndOfInput));
  if (!capture_raw && unibrow::IsLineTerminator(c)) {
    // Allow escaped CR+LF newlines in multiline string literals.
    if (IsCarriageReturn(c) && IsLineFeed(c0_)) Advance();
    return true;
  }
  switch (c) {
    case 'b' : c = '\b'; break;
    case 'f' : c = '\f'; break;
    case 'n' : c = '\n'; break;
    case 'r' : c = '\r'; break;
    case 't' : c = '\t'; break;
    case 'u' : {
      c = ScanUnicodeEscape<capture_raw>();
      if (IsInvalid(c)) return false;
      break;
    }
    case 'v':
      c = '\v';
      break;
    case 'x': {
      c = ScanHexNumber<capture_raw>(2);
      if (IsInvalid(c)) return false;
      break;
    }
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
      c = ScanOctalEscape<capture_raw>(c, 2);
      break;
    case '8':
    case '9':
      // '\8' and '\9' are disallowed in strict mode.
      // Reuse the octal error state to propagate the error.
      octal_pos_ = Location(source_pos() - 2, source_pos() - 1);
      octal_message_ = capture_raw ? MessageTemplate::kTemplate8Or9Escape
                                   : MessageTemplate::kStrict8Or9Escape;
      break;
  }
  // Other escaped characters are interpreted as their non-escaped version.
  AddLiteralChar(c);
  return true;
}
References AddLiteralChar(), Advance(), c0_, v8::internal::DCHECK(), v8::internal::IsCarriageReturn(), IsInvalid(), v8::internal::IsLineFeed(), unibrow::IsLineTerminator(), kEndOfInput, octal_message_, octal_pos_, and source_pos().
ScanHexDigits()
bool v8::internal::Scanner::ScanHexDigits () [private]
Definition at line 844 of file scanner.cc.
                            {
  return ScanDigitsWithNumericSeparators(&IsHexDigit, true);
}
References v8::internal::IsHexDigit(), and ScanDigitsWithNumericSeparators().
Referenced by ScanNumber().
ScanHexNumber()
template<bool capture_raw, bool unicode>
base::uc32 v8::internal::Scanner::ScanHexNumber (int expected_length) [private]
Definition at line 120 of file scanner.cc.
                                                   {
  DCHECK_LE(expected_length, 4); // prevent overflow
  int begin = source_pos() - 2;
  base::uc32 x = 0;
  for (int i = 0; i < expected_length; i++) {
    int d = base::HexValue(c0_);
    if (d < 0) {
      ReportScannerError(Location(begin, begin + expected_length + 2),
                         unicode
                             ? MessageTemplate::kInvalidUnicodeEscapeSequence
                             : MessageTemplate::kInvalidHexEscapeSequence);
      return Invalid();
    }
    x = x * 16 + d;
    Advance<capture_raw>();
  }
  return x;
}
References v8::internal::compiler::begin(), c0_, DCHECK_LE, v8::base::HexValue(), Invalid(), ReportScannerError(), and source_pos().
ScanHtmlComment()
Token::Value v8::internal::Scanner::ScanHtmlComment () [private]
Definition at line 418 of file scanner.cc.
                                    {
  // Check for <!-- comments.
  DCHECK_EQ(c0_, '!');
  Advance();
  if (c0_ != '-' || Peek() != '-') {
    PushBack('!'); // undo Advance()
    return Token::kLessThan;
  }
  Advance();
  found_html_comment_ = true;
  return SkipSingleHTMLComment();
}
References Advance(), c0_, DCHECK_EQ, found_html_comment_, v8::internal::kLessThan, Peek(), PushBack(), and SkipSingleHTMLComment().
Referenced by ScanSingleToken().
ScanIdentifierOrKeyword()
Token::Value v8::internal::Scanner::ScanIdentifierOrKeyword () [inline], [private]
Definition at line 188 of file scanner-inl.h.
                                                      {
  next().literal_chars.Start();
  return ScanIdentifierOrKeywordInner();
}
References v8::internal::Scanner::TokenDesc::literal_chars, next(), ScanIdentifierOrKeywordInner(), and v8::internal::LiteralBuffer::Start().
Referenced by ScanSingleToken().
ScanIdentifierOrKeywordInner()
Token::Value v8::internal::Scanner::ScanIdentifierOrKeywordInner () [inline], [private]
Definition at line 265 of file scanner-inl.h.
                                                           {
  DCHECK(IsIdentifierStart(c0_));
  bool escaped = false;
  bool can_be_keyword = true;
  static_assert(arraysize(character_scan_flags) == kMaxAscii + 1);
  if (V8_LIKELY(static_cast<uint32_t>(c0_) <= kMaxAscii)) {
    if (V8_LIKELY(c0_ != '\\')) {
      uint8_t scan_flags = character_scan_flags[c0_];
      DCHECK(!TerminatesLiteral(scan_flags));
      static_assert(static_cast<uint8_t>(ScanFlags::kCannotBeKeywordStart) ==
                    static_cast<uint8_t>(ScanFlags::kCannotBeKeyword) << 1);
      scan_flags >>= 1;
      // Make sure the shifting above doesn't set IdentifierNeedsSlowPath.
      // Otherwise we'll fall into the slow path after scanning the identifier.
      DCHECK(!IdentifierNeedsSlowPath(scan_flags));
      AddLiteralChar(static_cast<char>(c0_));
      AdvanceUntil([this, &scan_flags](base::uc32 c0) {
        if (V8_UNLIKELY(static_cast<uint32_t>(c0) > kMaxAscii)) {
          // A non-ascii character means we need to drop through to the slow
          // path.
          // TODO(leszeks): This would be most efficient as a goto to the slow
          // path, check codegen and maybe use a bool instead.
          scan_flags |=
              static_cast<uint8_t>(ScanFlags::kIdentifierNeedsSlowPath);
          return true;
        }
        uint8_t char_flags = character_scan_flags[c0];
        scan_flags |= char_flags;
        if (TerminatesLiteral(char_flags)) {
          return true;
        } else {
          AddLiteralChar(static_cast<char>(c0));
          return false;
        }
      });
      if (V8_LIKELY(!IdentifierNeedsSlowPath(scan_flags))) {
        if (!CanBeKeyword(scan_flags)) return Token::kIdentifier;
        // Could be a keyword or identifier.
        base::Vector<const uint8_t> chars =
            next().literal_chars.one_byte_literal();
        return KeywordOrIdentifierToken(chars.begin(), chars.length());
      }
      can_be_keyword = CanBeKeyword(scan_flags);
    } else {
      // Special case for escapes at the start of an identifier.
      escaped = true;
      base::uc32 c = ScanIdentifierUnicodeEscape();
      DCHECK(!IsIdentifierStart(Invalid()));
      if (c == '\\' || !IsIdentifierStart(c)) {
        return Token::kIllegal;
      }
      AddLiteralChar(c);
      can_be_keyword = CharCanBeKeyword(c);
    }
  }
  return ScanIdentifierOrKeywordInnerSlow(escaped, can_be_keyword);
}
References AddLiteralChar(), AdvanceUntil(), arraysize, v8::base::Vector< T >::begin(), c0_, v8::internal::CanBeKeyword(), v8::internal::character_scan_flags, v8::internal::CharCanBeKeyword(), v8::internal::DCHECK(), v8::internal::IdentifierNeedsSlowPath(), Invalid(), v8::internal::IsIdentifierStart(), v8::internal::kCannotBeKeyword, v8::internal::kCannotBeKeywordStart, v8::internal::KeywordOrIdentifierToken(), v8::internal::kIdentifierNeedsSlowPath, kMaxAscii, v8::base::Vector< T >::length(), v8::internal::Scanner::TokenDesc::literal_chars, next(), v8::internal::LiteralBuffer::one_byte_literal(), ScanIdentifierOrKeywordInnerSlow(), ScanIdentifierUnicodeEscape(), v8::internal::TerminatesLiteral(), V8_LIKELY, and V8_UNLIKELY.
Referenced by ScanIdentifierOrKeyword(), and ScanPrivateName().
ScanIdentifierOrKeywordInnerSlow()
Token::Value v8::internal::Scanner::ScanIdentifierOrKeywordInnerSlow (bool escaped, bool can_be_keyword) [private]
Definition at line 1016 of file scanner.cc.
                                                                            {
  while (true) {
    if (c0_ == '\\') {
      escaped = true;
      base::uc32 c = ScanIdentifierUnicodeEscape();
      // Only allow legal identifier part characters.
      // TODO(verwaest): Make this true.
      // DCHECK(!IsIdentifierPart('\'));
      DCHECK(!IsIdentifierPart(Invalid()));
      if (c == '\\' || !IsIdentifierPart(c)) {
        return Token::kIllegal;
      }
      can_be_keyword = can_be_keyword && CharCanBeKeyword(c);
      AddLiteralChar(c);
    } else if (IsIdentifierPart(c0_) ||
               (CombineSurrogatePair() && IsIdentifierPart(c0_))) {
      can_be_keyword = can_be_keyword && CharCanBeKeyword(c0_);
      AddLiteralCharAdvance();
    } else {
      break;
    }
  }
  if (can_be_keyword && next().literal_chars.is_one_byte()) {
    base::Vector<const uint8_t> chars = next().literal_chars.one_byte_literal();
    Token::Value token =
        KeywordOrIdentifierToken(chars.begin(), chars.length());
    if (base::IsInRange(token, Token::kIdentifier, Token::kYield)) return token;
    if (token == Token::kFutureStrictReservedWord) {
      if (escaped) return Token::kEscapedStrictReservedWord;
      return token;
    }
    if (!escaped) return token;
    static_assert(Token::kLet + 1 == Token::kStatic);
    if (base::IsInRange(token, Token::kLet, Token::kStatic)) {
      return Token::kEscapedStrictReservedWord;
    }
    return Token::kEscapedKeyword;
  }
  return Token::kIdentifier;
}
References AddLiteralChar(), AddLiteralCharAdvance(), v8::base::Vector< T >::begin(), c0_, v8::internal::CharCanBeKeyword(), CombineSurrogatePair(), v8::internal::DCHECK(), Invalid(), v8::internal::IsIdentifierPart(), v8::internal::KeywordOrIdentifierToken(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kYield, v8::base::Vector< T >::length(), v8::internal::Scanner::TokenDesc::literal_chars, next(), v8::internal::LiteralBuffer::one_byte_literal(), and ScanIdentifierUnicodeEscape().
Referenced by ScanIdentifierOrKeywordInner().
ScanIdentifierUnicodeEscape()
base::uc32 v8::internal::Scanner::ScanIdentifierUnicodeEscape () [private]
Definition at line 988 of file scanner.cc.
                                              {
  Advance();
  if (c0_ != 'u') return Invalid();
  Advance();
  return ScanUnicodeEscape<false>();
}
References Advance(), c0_, and Invalid().
Referenced by ScanIdentifierOrKeywordInner(), and ScanIdentifierOrKeywordInnerSlow().
ScanImplicitOctalDigits()
bool v8::internal::Scanner::ScanImplicitOctalDigits (int start_pos, Scanner::NumberKind * kind) [private]
Definition at line 824 of file scanner.cc.
                                                               {
  DCHECK_EQ(*kind, IMPLICIT_OCTAL);
  while (true) {
    // (possible) octal number
    if (IsNonOctalDecimalDigit(c0_)) {
      *kind = DECIMAL_WITH_LEADING_ZERO;
      return true;
    }
    if (!IsOctalDigit(c0_)) {
      // Octal literal finished.
      octal_pos_ = Location(start_pos, source_pos());
      octal_message_ = MessageTemplate::kStrictOctalLiteral;
      return true;
    }
    AddLiteralCharAdvance();
  }
}
References AddLiteralCharAdvance(), c0_, DCHECK_EQ, DECIMAL_WITH_LEADING_ZERO, IMPLICIT_OCTAL, v8::internal::IsNonOctalDecimalDigit(), v8::internal::IsOctalDigit(), octal_message_, octal_pos_, and source_pos().
Referenced by ScanNumber().
ScanNumber()
Token::Value v8::internal::Scanner::ScanNumber (bool seen_period) [private]
Definition at line 855 of file scanner.cc.
                                               {
  DCHECK(IsDecimalDigit(c0_)); // the first digit of the number or the fraction
  NumberKind kind = DECIMAL;
  next().literal_chars.Start();
  bool at_start = !seen_period;
  int start_pos = source_pos(); // For reporting octal positions.
  if (seen_period) {
    // we have already seen a decimal point of the float
    AddLiteralChar('.');
    if (c0_ == '_') {
      return Token::kIllegal;
    }
    // we know we have at least one digit
    if (!ScanDecimalDigits(true)) return Token::kIllegal;
  } else {
    // if the first character is '0' we must check for octals and hex
    if (c0_ == '0') {
      AddLiteralCharAdvance();
      // either 0, 0exxx, 0Exxx, 0.xxx, a hex number, a binary number or
      // an octal number.
      if (AsciiAlphaToLower(c0_) == 'x') {
        AddLiteralCharAdvance();
        kind = HEX;
        if (!ScanHexDigits()) return Token::kIllegal;
      } else if (AsciiAlphaToLower(c0_) == 'o') {
        AddLiteralCharAdvance();
        kind = OCTAL;
        if (!ScanOctalDigits()) return Token::kIllegal;
      } else if (AsciiAlphaToLower(c0_) == 'b') {
        AddLiteralCharAdvance();
        kind = BINARY;
        if (!ScanBinaryDigits()) return Token::kIllegal;
      } else if (IsOctalDigit(c0_)) {
        kind = IMPLICIT_OCTAL;
        if (!ScanImplicitOctalDigits(start_pos, &kind)) {
          return Token::kIllegal;
        }
        if (kind == DECIMAL_WITH_LEADING_ZERO) {
          at_start = false;
        }
      } else if (IsNonOctalDecimalDigit(c0_)) {
        kind = DECIMAL_WITH_LEADING_ZERO;
      } else if (c0_ == '_') {
        ReportScannerError(Location(source_pos(), source_pos() + 1),
                           MessageTemplate::kZeroDigitNumericSeparator);
        return Token::kIllegal;
      }
    }
    // Parse decimal digits and allow trailing fractional part.
    if (IsDecimalNumberKind(kind)) {
      bool allow_numeric_separator = kind != DECIMAL_WITH_LEADING_ZERO;
      // This is an optimization for parsing Decimal numbers as Smi's.
      if (at_start) {
        uint64_t value = 0;
        // scan subsequent decimal digits
        if (!ScanDecimalAsSmi(&value, allow_numeric_separator)) {
          return Token::kIllegal;
        }
        if (next().literal_chars.one_byte_literal().length() <= 10 &&
            value <= Smi::kMaxValue && c0_ != '.' && !IsIdentifierStart(c0_)) {
          next().smi_value = static_cast<uint32_t>(value);
          if (kind == DECIMAL_WITH_LEADING_ZERO) {
            octal_pos_ = Location(start_pos, source_pos());
            octal_message_ = MessageTemplate::kStrictDecimalWithLeadingZero;
          }
          return Token::kSmi;
        }
      }
      if (!ScanDecimalDigits(allow_numeric_separator)) {
        return Token::kIllegal;
      }
      if (c0_ == '.') {
        seen_period = true;
        AddLiteralCharAdvance();
        if (c0_ == '_') {
          return Token::kIllegal;
        }
        if (!ScanDecimalDigits(true)) return Token::kIllegal;
      }
    }
  }
  bool is_bigint = false;
  if (c0_ == 'n' && !seen_period && IsValidBigIntKind(kind)) {
    // Check that the literal is within our limits for BigInt length.
    // For simplicity, use 4 bits per character to calculate the maximum
    // allowed literal length.
    static const int kMaxBigIntCharacters = BigInt::kMaxLengthBits / 4;
    int length = source_pos() - start_pos - (kind != DECIMAL ? 2 : 0);
    if (length > kMaxBigIntCharacters) {
      ReportScannerError(Location(start_pos, source_pos()),
                         MessageTemplate::kBigIntTooBig);
      return Token::kIllegal;
    }
    is_bigint = true;
    Advance();
  } else if (AsciiAlphaToLower(c0_) == 'e') {
    // scan exponent, if any
    DCHECK_NE(kind, HEX); // 'e'/'E' must be scanned as part of the hex number
    if (!IsDecimalNumberKind(kind)) return Token::kIllegal;
    // scan exponent
    AddLiteralCharAdvance();
    if (!ScanSignedInteger()) return Token::kIllegal;
  }
  // The source character immediately following a numeric literal must
  // not be an identifier start or a decimal digit; see ECMA-262
  // section 7.8.3, page 17 (note that we read only one decimal digit
  // if the value is 0).
  if (IsDecimalDigit(c0_) || IsIdentifierStart(c0_)) {
    return Token::kIllegal;
  }
  if (kind == DECIMAL_WITH_LEADING_ZERO) {
    octal_pos_ = Location(start_pos, source_pos());
    octal_message_ = MessageTemplate::kStrictDecimalWithLeadingZero;
  }
  next().number_kind = kind;
  return is_bigint ? Token::kBigInt : Token::kNumber;
}
References AddLiteralChar(), AddLiteralCharAdvance(), Advance(), v8::internal::AsciiAlphaToLower(), BINARY, c0_, v8::internal::DCHECK(), DCHECK_NE, DECIMAL, DECIMAL_WITH_LEADING_ZERO, HEX, IMPLICIT_OCTAL, v8::internal::IsDecimalDigit(), IsDecimalNumberKind(), v8::internal::IsIdentifierStart(), v8::internal::IsNonOctalDecimalDigit(), v8::internal::IsOctalDigit(), IsValidBigIntKind(), v8::internal::BigIntBase::kMaxLengthBits, v8::internal::Smi::kMaxValue, v8::internal::compiler::kSmi, v8::internal::length, v8::internal::Scanner::TokenDesc::literal_chars, next(), v8::internal::Scanner::TokenDesc::number_kind, OCTAL, octal_message_, octal_pos_, ReportScannerError(), ScanBinaryDigits(), ScanDecimalAsSmi(), ScanDecimalDigits(), ScanHexDigits(), ScanImplicitOctalDigits(), ScanOctalDigits(), ScanSignedInteger(), v8::internal::Scanner::TokenDesc::smi_value, source_pos(), v8::internal::LiteralBuffer::Start(), and v8::internal::value.
Referenced by ScanSingleToken().
ScanOctalDigits()
bool v8::internal::Scanner::ScanOctalDigits () [private]
Definition at line 820 of file scanner.cc.
                              {
  return ScanDigitsWithNumericSeparators(&IsOctalDigit, true);
}
References v8::internal::IsOctalDigit(), and ScanDigitsWithNumericSeparators().
Referenced by ScanNumber().
ScanOctalEscape()
template<bool capture_raw>
base::uc32 v8::internal::Scanner::ScanOctalEscape (base::uc32 c, int length) [private]
Definition at line 528 of file scanner.cc.
                                                        {
  DCHECK('0' <= c && c <= '7');
  base::uc32 x = c - '0';
  int i = 0;
  for (; i < length; i++) {
    int d = c0_ - '0';
    if (d < 0 || d > 7) break;
    int nx = x * 8 + d;
    if (nx >= 256) break;
    x = nx;
    Advance<capture_raw>();
  }
  // Anything except '\0' is an octal escape sequence, illegal in strict mode.
  // Remember the position of octal escape sequences so that an error
  // can be reported later (in strict mode).
  // We don't report the error immediately, because the octal escape can
  // occur before the "use strict" directive.
  if (c != '0' || i > 0 || IsNonOctalDecimalDigit(c0_)) {
    octal_pos_ = Location(source_pos() - i - 1, source_pos() - 1);
    octal_message_ = capture_raw ? MessageTemplate::kTemplateOctalLiteral
                                 : MessageTemplate::kStrictOctalEscape;
  }
  return x;
}
References c0_, v8::internal::DCHECK(), v8::internal::IsNonOctalDecimalDigit(), v8::internal::length, octal_message_, octal_pos_, and source_pos().
ScanPrivateName()
Token::Value v8::internal::Scanner::ScanPrivateName () [private]
Definition at line 594 of file scanner.cc.
                                    {
  next().literal_chars.Start();
  DCHECK_EQ(c0_, '#');
  DCHECK(!IsIdentifierStart(kEndOfInput));
  int pos = source_pos();
  Advance();
  if (IsIdentifierStart(c0_) ||
      (CombineSurrogatePair() && IsIdentifierStart(c0_))) {
    AddLiteralChar('#');
    Token::Value token = ScanIdentifierOrKeywordInner();
    return token == Token::kIllegal ? Token::kIllegal : Token::kPrivateName;
  }
  ReportScannerError(pos, MessageTemplate::kInvalidOrUnexpectedToken);
  return Token::kIllegal;
}
References AddLiteralChar(), Advance(), c0_, CombineSurrogatePair(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::IsIdentifierStart(), kEndOfInput, v8::internal::Scanner::TokenDesc::literal_chars, next(), ReportScannerError(), ScanIdentifierOrKeywordInner(), source_pos(), and v8::internal::LiteralBuffer::Start().
Referenced by ScanSingleToken().
ScanRegExpFlags()
std::optional< RegExpFlags > v8::internal::Scanner::ScanRegExpFlags ()
Definition at line 1107 of file scanner.cc.
                                                  {
  DCHECK_EQ(Token::kRegExpLiteral, next().token);
  RegExpFlags flags;
  next().literal_chars.Start();
  while (IsIdentifierPart(c0_)) {
    std::optional<RegExpFlag> maybe_flag = JSRegExp::FlagFromChar(c0_);
    if (!maybe_flag.has_value()) return {};
    RegExpFlag flag = maybe_flag.value();
    if (flags & flag) return {};
    AddLiteralCharAdvance();
    flags |= flag;
  }
  next().location.end_pos = source_pos();
  return flags;
}
References AddLiteralCharAdvance(), c0_, DCHECK_EQ, v8::internal::Scanner::Location::end_pos, v8::internal::JSRegExp::FlagFromChar(), v8::internal::flags, v8::internal::IsIdentifierPart(), v8::internal::Scanner::TokenDesc::literal_chars, v8::internal::Scanner::TokenDesc::location, next(), source_pos(), and v8::internal::LiteralBuffer::Start().
Referenced by v8::internal::ParserBase< Impl >::ParseRegExpLiteral().
ScanRegExpPattern()
bool v8::internal::Scanner::ScanRegExpPattern ()
Definition at line 1063 of file scanner.cc.
                                {
  DCHECK_EQ(Token::kUninitialized, next_next().token);
  DCHECK(next().token == Token::kDiv || next().token == Token::kAssignDiv);
  // Scan: ('/' | '/=') RegularExpressionBody '/' RegularExpressionFlags
  bool in_character_class = false;
  // Scan regular expression body: According to ECMA-262, 3rd, 7.8.5,
  // the scanner should pass uninterpreted bodies to the RegExp
  // constructor.
  next().literal_chars.Start();
  if (next().token == Token::kAssignDiv) {
    AddLiteralChar('=');
  }
  while (c0_ != '/' || in_character_class) {
    if (c0_ == kEndOfInput || unibrow::IsLineTerminator(c0_)) {
      return false;
    }
    if (c0_ == '\\') { // Escape sequence.
      AddLiteralCharAdvance();
      if (c0_ == kEndOfInput || unibrow::IsLineTerminator(c0_)) {
        return false;
      }
      AddLiteralCharAdvance();
      // If the escape allows more characters, i.e., \x??, \u????, or \c?,
      // only "safe" characters are allowed (letters, digits, underscore),
      // otherwise the escape isn't valid and the invalid character has
      // its normal meaning. I.e., we can just continue scanning without
      // worrying whether the following characters are part of the escape
      // or not, since any '/', '\\' or '[' is guaranteed to not be part
      // of the escape sequence.
    } else { // Unescaped character.
      if (c0_ == '[') in_character_class = true;
      if (c0_ == ']') in_character_class = false;
      AddLiteralCharAdvance();
    }
  }
  Advance(); // consume '/'
  next().token = Token::kRegExpLiteral;
  return true;
}
References AddLiteralChar(), AddLiteralCharAdvance(), Advance(), c0_, v8::internal::DCHECK(), DCHECK_EQ, unibrow::IsLineTerminator(), kEndOfInput, v8::internal::Scanner::TokenDesc::literal_chars, next(), next_next(), v8::internal::LiteralBuffer::Start(), and v8::internal::Scanner::TokenDesc::token.
ScanSignedInteger()
bool v8::internal::Scanner::ScanSignedInteger () [private]
Definition at line 848 of file scanner.cc.
                                {
  if (c0_ == '+' || c0_ == '-') AddLiteralCharAdvance();
  // we must have at least one decimal digit after 'e'/'E'
  if (!IsDecimalDigit(c0_)) return false;
  return ScanDecimalDigits(true);
}
References AddLiteralCharAdvance(), c0_, v8::internal::IsDecimalDigit(), and ScanDecimalDigits().
Referenced by ScanNumber().
ScanSingleToken()
Token::Value v8::internal::Scanner::ScanSingleToken () [inline], [private]
Definition at line 351 of file scanner-inl.h.
                                              {
  bool old_saw_non_comment = saw_non_comment_;
  // Assume the token we'll parse is not a comment; if it is, saw_non_comment_
  // is restored.
  saw_non_comment_ = true;
  Token::Value token;
  do {
    next().location.beg_pos = source_pos();
    if (V8_LIKELY(static_cast<unsigned>(c0_) <= kMaxAscii)) {
      token = one_char_tokens[c0_];
      switch (token) {
        case Token::kLeftParen:
        case Token::kRightParen:
        case Token::kLeftBrace:
        case Token::kRightBrace:
        case Token::kLeftBracket:
        case Token::kRightBracket:
        case Token::kColon:
        case Token::kSemicolon:
        case Token::kComma:
        case Token::kBitNot:
        case Token::kIllegal:
          // One character tokens.
          return Select(token);
        case Token::kConditional:
          // ? ?. ?? ??=
          Advance();
          if (c0_ == '.') {
            Advance();
            if (!IsDecimalDigit(c0_)) return Token::kQuestionPeriod;
            PushBack('.');
          } else if (c0_ == '?') {
            return Select('=', Token::kAssignNullish, Token::kNullish);
          }
          return Token::kConditional;
        case Token::kString:
          return ScanString();
        case Token::kLessThan:
          // < <= << <<= <!--
          Advance();
          if (c0_ == '=') return Select(Token::kLessThanEq);
          if (c0_ == '<') return Select('=', Token::kAssignShl, Token::kShl);
          if (c0_ == '!') {
            token = ScanHtmlComment();
            continue;
          }
          return Token::kLessThan;
        case Token::kGreaterThan:
          // > >= >> >>= >>> >>>=
          Advance();
          if (c0_ == '=') return Select(Token::kGreaterThanEq);
          if (c0_ == '>') {
            // >> >>= >>> >>>=
            Advance();
            if (c0_ == '=') return Select(Token::kAssignSar);
            if (c0_ == '>') return Select('=', Token::kAssignShr, Token::kShr);
            return Token::kSar;
          }
          return Token::kGreaterThan;
        case Token::kAssign:
          // = == === =>
          Advance();
          if (c0_ == '=') return Select('=', Token::kEqStrict, Token::kEq);
          if (c0_ == '>') return Select(Token::kArrow);
          return Token::kAssign;
        case Token::kNot:
          // ! != !==
          Advance();
          if (c0_ == '=')
            return Select('=', Token::kNotEqStrict, Token::kNotEq);
          return Token::kNot;
        case Token::kAdd:
          // + ++ +=
          Advance();
          if (c0_ == '+') return Select(Token::kInc);
          if (c0_ == '=') return Select(Token::kAssignAdd);
          return Token::kAdd;
        case Token::kSub:
          // - -- --> -=
          Advance();
          if (c0_ == '-') {
            Advance();
            if (c0_ == '>' && next().after_line_terminator) {
              // For compatibility with SpiderMonkey, we skip lines that
              // start with an HTML comment end '-->'.
              token = SkipSingleHTMLComment();
              continue;
            }
            return Token::kDec;
          }
          if (c0_ == '=') return Select(Token::kAssignSub);
          return Token::kSub;
        case Token::kMul:
          // * *=
          Advance();
          if (c0_ == '*') return Select('=', Token::kAssignExp, Token::kExp);
          if (c0_ == '=') return Select(Token::kAssignMul);
          return Token::kMul;
        case Token::kMod:
          // % %=
          return Select('=', Token::kAssignMod, Token::kMod);
        case Token::kDiv:
          // / // /* /=
          Advance();
          if (c0_ == '/') {
            saw_non_comment_ = old_saw_non_comment;
            base::uc32 c = Peek();
            if (c == '#' || c == '@') {
              Advance();
              Advance();
              token = SkipMagicComment(c);
              continue;
            }
            token = SkipSingleLineComment();
            continue;
          }
          if (c0_ == '*') {
            saw_non_comment_ = old_saw_non_comment;
            token = SkipMultiLineComment();
            continue;
          }
          if (c0_ == '=') return Select(Token::kAssignDiv);
          return Token::kDiv;
        case Token::kBitAnd:
          // & && &= &&=
          Advance();
          if (c0_ == '&') return Select('=', Token::kAssignAnd, Token::kAnd);
          if (c0_ == '=') return Select(Token::kAssignBitAnd);
          return Token::kBitAnd;
        case Token::kBitOr:
          // | || |= ||=
          Advance();
          if (c0_ == '|') return Select('=', Token::kAssignOr, Token::kOr);
          if (c0_ == '=') return Select(Token::kAssignBitOr);
          return Token::kBitOr;
        case Token::kBitXor:
          // ^ ^=
          return Select('=', Token::kAssignBitXor, Token::kBitXor);
        case Token::kPeriod:
          // . Number
          Advance();
          if (IsDecimalDigit(c0_)) return ScanNumber(true);
          if (c0_ == '.') {
            if (Peek() == '.') {
              Advance();
              Advance();
              return Token::kEllipsis;
            }
          }
          return Token::kPeriod;
        case Token::kTemplateSpan:
          Advance();
          return ScanTemplateSpan();
        case Token::kPrivateName:
          if (source_pos() == 0 && Peek() == '!') {
            token = SkipSingleLineComment();
            continue;
          }
          return ScanPrivateName();
        case Token::kWhitespace:
          token = SkipWhiteSpace();
          continue;
        case Token::kNumber:
          return ScanNumber(false);
        case Token::kIdentifier:
          return ScanIdentifierOrKeyword();
        default:
          UNREACHABLE();
      }
    }
    if (IsIdentifierStart(c0_) ||
        (CombineSurrogatePair() && IsIdentifierStart(c0_))) {
      return ScanIdentifierOrKeyword();
    }
    if (c0_ == kEndOfInput) {
      return source_->has_parser_error() ? Token::kIllegal : Token::kEos;
    }
    token = SkipWhiteSpace();
    // Continue scanning for tokens as long as we're just skipping whitespace.
  } while (token == Token::kWhitespace);
  return token;
}
References Advance(), v8::internal::Scanner::Location::beg_pos, c0_, CombineSurrogatePair(), v8::internal::Utf16CharacterStream::has_parser_error(), v8::internal::IsDecimalDigit(), v8::internal::IsIdentifierStart(), kEndOfInput, v8::internal::kGreaterThan, v8::internal::kLessThan, kMaxAscii, v8::internal::Scanner::TokenDesc::location, next(), v8::internal::one_char_tokens, Peek(), PushBack(), saw_non_comment_, ScanHtmlComment(), ScanIdentifierOrKeyword(), ScanNumber(), ScanPrivateName(), ScanString(), ScanTemplateSpan(), Select(), SkipMagicComment(), SkipMultiLineComment(), SkipSingleHTMLComment(), SkipSingleLineComment(), SkipWhiteSpace(), source_, source_pos(), v8::internal::UNREACHABLE(), and V8_LIKELY.
Referenced by Scan().
ScanString()
Token::Value v8::internal::Scanner::ScanString () [private]
Definition at line 553 of file scanner.cc.
                               {
  base::uc32 quote = c0_;
  next().literal_chars.Start();
  while (true) {
    AdvanceUntil([this](base::uc32 c0) {
      if (V8_UNLIKELY(static_cast<uint32_t>(c0) > kMaxAscii)) {
        if (V8_UNLIKELY(unibrow::IsStringLiteralLineTerminator(c0))) {
          return true;
        }
        AddLiteralChar(c0);
        return false;
      }
      uint8_t char_flags = character_scan_flags[c0];
      if (MayTerminateString(char_flags)) return true;
      AddLiteralChar(c0);
      return false;
    });
    while (c0_ == '\\') {
      Advance();
      // TODO(verwaest): Check whether we can remove the additional check.
      if (V8_UNLIKELY(c0_ == kEndOfInput || !ScanEscape<false>())) {
        return Token::kIllegal;
      }
    }
    if (c0_ == quote) {
      Advance();
      return Token::kString;
    }
    if (V8_UNLIKELY(c0_ == kEndOfInput ||
                    unibrow::IsStringLiteralLineTerminator(c0_))) {
      return Token::kIllegal;
    }
    AddLiteralChar(c0_);
  }
}
References AddLiteralChar(), Advance(), AdvanceUntil(), c0_, v8::internal::character_scan_flags, unibrow::IsStringLiteralLineTerminator(), kEndOfInput, kMaxAscii, v8::internal::Scanner::TokenDesc::literal_chars, v8::internal::MayTerminateString(), next(), v8::internal::LiteralBuffer::Start(), and V8_UNLIKELY.
Referenced by ScanSingleToken().
ScanTemplateContinuation()
Token::Value v8::internal::Scanner::ScanTemplateContinuation () [inline]
Definition at line 422 of file scanner.h.
                                        {
    DCHECK_EQ(next().token, Token::kRightBrace);
    DCHECK_EQ(source_pos() - 1, next().location.beg_pos);
    return ScanTemplateSpan();
  }
References DCHECK_EQ.
Referenced by v8::internal::ParserBase< Impl >::ParseTemplateLiteral().
ScanTemplateSpan()
Token::Value v8::internal::Scanner::ScanTemplateSpan () [private]
Definition at line 611 of file scanner.cc.
                                     {
  // When scanning a TemplateSpan, we are looking for the following construct:
  // kTemplateSpan ::
  // ` LiteralChars* ${
  // | } LiteralChars* ${
  //
  // kTemplateTail ::
  // ` LiteralChars* `
  // | } LiteralChar* `
  //
  // A kTemplateSpan should always be followed by an Expression, while a
  // kTemplateTail terminates a TemplateLiteral and does not need to be
  // followed by an Expression.
  // These scoped helpers save and restore the original error state, so that we
  // can specially treat invalid escape sequences in templates (which are
  // handled by the parser).
  ErrorState scanner_error_state(&scanner_error_, &scanner_error_location_);
  ErrorState octal_error_state(&octal_message_, &octal_pos_);
  Token::Value result = Token::kTemplateSpan;
  next().literal_chars.Start();
  next().raw_literal_chars.Start();
  const bool capture_raw = true;
  while (true) {
    base::uc32 c = c0_;
    if (c == '`') {
      Advance(); // Consume '`'
      result = Token::kTemplateTail;
      break;
    } else if (c == '$' && Peek() == '{') {
      Advance(); // Consume '$'
      Advance(); // Consume '{'
      break;
    } else if (c == '\\') {
      Advance(); // Consume '\\'
      DCHECK(!unibrow::IsLineTerminator(kEndOfInput));
      if (capture_raw) AddRawLiteralChar('\\');
      if (unibrow::IsLineTerminator(c0_)) {
        // The TV of LineContinuation :: \ LineTerminatorSequence is the empty
        // code unit sequence.
        base::uc32 lastChar = c0_;
        Advance();
        if (lastChar == '\r') {
          // Also skip \n.
          if (c0_ == '\n') Advance();
          lastChar = '\n';
        }
        if (capture_raw) AddRawLiteralChar(lastChar);
      } else {
        bool success = ScanEscape<capture_raw>();
        USE(success);
        DCHECK_EQ(!success, has_error());
        // For templates, invalid escape sequence checking is handled in the
        // parser.
        scanner_error_state.MoveErrorTo(next_);
        octal_error_state.MoveErrorTo(next_);
      }
    } else if (c == kEndOfInput) {
      // Unterminated template literal
      break;
    } else {
      Advance(); // Consume c.
      // The TRV of LineTerminatorSequence :: <CR> is the CV 0x000A.
      // The TRV of LineTerminatorSequence :: <CR><LF> is the sequence
      // consisting of the CV 0x000A.
      if (c == '\r') {
        if (c0_ == '\n') Advance(); // Consume '\n'
        c = '\n';
      }
      if (capture_raw) AddRawLiteralChar(c);
      AddLiteralChar(c);
    }
  }
  next().location.end_pos = source_pos();
  next().token = result;
  return result;
}
References AddLiteralChar(), AddRawLiteralChar(), Advance(), c0_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Scanner::Location::end_pos, has_error(), unibrow::IsLineTerminator(), kEndOfInput, v8::internal::Scanner::TokenDesc::literal_chars, v8::internal::Scanner::TokenDesc::location, v8::internal::Scanner::ErrorState::MoveErrorTo(), next(), next_, octal_message_, octal_pos_, Peek(), v8::internal::Scanner::TokenDesc::raw_literal_chars, v8::base::internal::result, scanner_error_, scanner_error_location_, source_pos(), v8::internal::LiteralBuffer::Start(), v8::internal::Scanner::TokenDesc::token, and USE.
Referenced by ScanSingleToken().
ScanUnicodeEscape()
template<bool capture_raw>
base::uc32 v8::internal::Scanner::ScanUnicodeEscape [private]
Definition at line 996 of file scanner.cc.
                                    {
  // Accept both \uxxxx and \u{xxxxxx}. In the latter case, the number of
  // hex digits between { } is arbitrary. \ and u have already been read.
  if (c0_ == '{') {
    int begin = source_pos() - 2;
    Advance<capture_raw>();
    base::uc32 cp =
        ScanUnlimitedLengthHexNumber<capture_raw>(String::kMaxCodePoint, begin);
    if (cp == kInvalidSequence || c0_ != '}') {
      ReportScannerError(source_pos(),
                         MessageTemplate::kInvalidUnicodeEscapeSequence);
      return Invalid();
    }
    Advance<capture_raw>();
    return cp;
  }
  const bool unicode = true;
  return ScanHexNumber<capture_raw, unicode>(4);
}
References v8::internal::compiler::begin(), c0_, v8::internal::cp, Invalid(), kInvalidSequence, v8::internal::String::kMaxCodePoint, ReportScannerError(), and source_pos().
ScanUnlimitedLengthHexNumber()
template<bool capture_raw>
base::uc32 v8::internal::Scanner::ScanUnlimitedLengthHexNumber (base::uc32 max_value, int beg_pos) [private]
Definition at line 142 of file scanner.cc.
                                                              {
  base::uc32 x = 0;
  int d = base::HexValue(c0_);
  if (d < 0) return Invalid();
  while (d >= 0) {
    x = x * 16 + d;
    if (x > max_value) {
      ReportScannerError(Location(beg_pos, source_pos() + 1),
                         MessageTemplate::kUndefinedUnicodeCodePoint);
      return Invalid();
    }
    Advance<capture_raw>();
    d = base::HexValue(c0_);
  }
  return x;
}
References c0_, v8::base::HexValue(), Invalid(), ReportScannerError(), and source_pos().
SeekForward()
void v8::internal::Scanner::SeekForward (int pos)
Definition at line 451 of file scanner.cc.
                                 {
  // After this call, we will have the token at the given position as
  // the "next" token. The "current" token will be invalid.
  if (pos == next().location.beg_pos) return;
  int current_pos = source_pos();
  DCHECK_EQ(next().location.end_pos, current_pos);
  // Positions inside the lookahead token aren't supported.
  DCHECK(pos >= current_pos);
  if (pos != current_pos) {
    source_->Seek(pos);
    Advance();
    // This function is only called to seek to the location
    // of the end of a function (at the "}" token). It doesn't matter
    // whether there was a line terminator in the part we skip.
    next().after_line_terminator = false;
  }
  Scan();
}
References Advance(), v8::internal::Scanner::TokenDesc::after_line_terminator, v8::internal::Scanner::Location::beg_pos, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Scanner::Location::end_pos, location(), next(), Scan(), v8::internal::Utf16CharacterStream::Seek(), source_, and source_pos().
SeekNext()
void v8::internal::Scanner::SeekNext (size_t position) [private]
Definition at line 1177 of file scanner.cc.
                                      {
  // Use with care: This cleanly resets most, but not all scanner state.
  // TODO(vogelheim): Fix this, or at least DCHECK the relevant conditions.
  // To re-scan from a given character position, we need to:
  // 1, Reset the current_, next_ and next_next_ tokens
  // (next_ + next_next_ will be overwrittem by Next(),
  // current_ will remain unchanged, so overwrite it fully.)
  for (TokenDesc& token : token_storage_) {
    token.token = Token::kUninitialized;
    token.invalid_template_escape_message = MessageTemplate::kNone;
  }
  // 2, reset the source to the desired position,
  source_->Seek(position);
  // 3, re-scan, by scanning the look-ahead char + 1 token (next_).
  c0_ = source_->Advance();
  next().after_line_terminator = false;
  Scan();
  DCHECK_EQ(next().location.beg_pos, static_cast<int>(position));
}
References v8::internal::Utf16CharacterStream::Advance(), v8::internal::Scanner::TokenDesc::after_line_terminator, v8::internal::Scanner::Location::beg_pos, c0_, DCHECK_EQ, location(), next(), Scan(), v8::internal::Utf16CharacterStream::Seek(), source_, and token_storage_.
Select() [1/2]
Token::Value v8::internal::Scanner::Select (base::uc32 next, Token::Value then, Token::Value else_) [inline], [private]
Definition at line 594 of file scanner.h.
                                               {
    Advance();
    if (c0_ == next) {
      Advance();
      return then;
    } else {
      return else_;
    }
  }
Select() [2/2]
Token::Value v8::internal::Scanner::Select (Token::Value tok) [inline], [private]
Definition at line 589 of file scanner.h.
                                           {
    Advance();
    return tok;
  }
Referenced by ScanSingleToken().
set_parser_error()
void v8::internal::Scanner::set_parser_error () [inline]
Definition at line 246 of file scanner.h.
                                    {
    if (!has_parser_error()) {
      c0_ = kEndOfInput;
      source_->set_parser_error();
      for (TokenDesc& desc : token_storage_) {
        if (desc.token != Token::kUninitialized) desc.token = Token::kIllegal;
      }
    }
  }
Referenced by v8::internal::ParserBase< Impl >::ReportMessageAt(), v8::internal::PreParser::ReportUnidentifiableError(), and v8::internal::ParserBase< Impl >::set_stack_overflow().
SkipMagicComment()
Token::Value v8::internal::Scanner::SkipMagicComment (base::uc32 hash_or_at_sign) [private]
Definition at line 245 of file scanner.cc.
                                                             {
  TryToParseMagicComment(hash_or_at_sign);
  if (unibrow::IsLineTerminator(c0_) || c0_ == kEndOfInput) {
    return Token::kWhitespace;
  }
  return SkipSingleLineComment();
}
References c0_, unibrow::IsLineTerminator(), kEndOfInput, SkipSingleLineComment(), and TryToParseMagicComment().
Referenced by ScanSingleToken().
SkipMultiLineComment()
Token::Value v8::internal::Scanner::SkipMultiLineComment () [private]
Definition at line 373 of file scanner.cc.
                                         {
  DCHECK_EQ(c0_, '*');
  // Until we see the first newline, check for * and newline characters.
  if (!next().after_line_terminator) {
    do {
      AdvanceUntil([](base::uc32 c0) {
        if (V8_UNLIKELY(static_cast<uint32_t>(c0) > kMaxAscii)) {
          return unibrow::IsLineTerminator(c0);
        }
        uint8_t char_flags = character_scan_flags[c0];
        return MultilineCommentCharacterNeedsSlowPath(char_flags);
      });
      while (c0_ == '*') {
        Advance();
        if (c0_ == '/') {
          Advance();
          return Token::kWhitespace;
        }
      }
      if (unibrow::IsLineTerminator(c0_)) {
        next().after_line_terminator = true;
        break;
      }
    } while (c0_ != kEndOfInput);
  }
  // After we've seen newline, simply try to find '*/'.
  while (c0_ != kEndOfInput) {
    AdvanceUntil([](base::uc32 c0) { return c0 == '*'; });
    while (c0_ == '*') {
      Advance();
      if (c0_ == '/') {
        Advance();
        return Token::kWhitespace;
      }
    }
  }
  return Token::kIllegal;
}
References Advance(), AdvanceUntil(), v8::internal::Scanner::TokenDesc::after_line_terminator, c0_, v8::internal::character_scan_flags, DCHECK_EQ, unibrow::IsLineTerminator(), kEndOfInput, kMaxAscii, v8::internal::MultilineCommentCharacterNeedsSlowPath(), next(), and V8_UNLIKELY.
Referenced by ScanSingleToken().
SkipSingleHTMLComment()
Token::Value v8::internal::Scanner::SkipSingleHTMLComment () [private]
Definition at line 226 of file scanner.cc.
                                          {
  if (flags_.is_module()) {
    ReportScannerError(source_pos(), MessageTemplate::kHtmlCommentInModule);
    return Token::kIllegal;
  }
  return SkipSingleLineComment();
}
References flags_, ReportScannerError(), SkipSingleLineComment(), and source_pos().
Referenced by ScanHtmlComment(), and ScanSingleToken().
SkipSingleLineComment()
Token::Value v8::internal::Scanner::SkipSingleLineComment () [private]
Definition at line 234 of file scanner.cc.
                                          {
  // The line terminator at the end of the line is not considered
  // to be part of the single-line comment; it is recognized
  // separately by the lexical grammar and becomes part of the
  // stream of input elements for the syntactic grammar (see
  // ECMA-262, section 7.4).
  AdvanceUntil([](base::uc32 c0) { return unibrow::IsLineTerminator(c0); });
  return Token::kWhitespace;
}
References AdvanceUntil(), and unibrow::IsLineTerminator().
Referenced by ScanSingleToken(), SkipMagicComment(), and SkipSingleHTMLComment().
SkipWhiteSpace()
Token::Value v8::internal::Scanner::SkipWhiteSpace () [inline], [private]
Definition at line 327 of file scanner-inl.h.
                                             {
  if (!IsWhiteSpaceOrLineTerminator(c0_)) return Token::kIllegal;
  if (!next().after_line_terminator && unibrow::IsLineTerminator(c0_)) {
    next().after_line_terminator = true;
  }
  // Advance as long as character is a WhiteSpace or LineTerminator.
  base::uc32 hint = ' ';
  AdvanceUntil([this, &hint](base::uc32 c0) {
    if (V8_LIKELY(c0 == hint)) return false;
    if (IsWhiteSpaceOrLineTerminator(c0)) {
      if (!next().after_line_terminator && unibrow::IsLineTerminator(c0)) {
        next().after_line_terminator = true;
      }
      hint = c0;
      return false;
    }
    return true;
  });
  return Token::kWhitespace;
}
References AdvanceUntil(), v8::internal::Scanner::TokenDesc::after_line_terminator, c0_, unibrow::IsLineTerminator(), v8::internal::IsWhiteSpaceOrLineTerminator(), next(), and V8_LIKELY.
Referenced by ScanSingleToken().
smi_value()
uint32_t v8::internal::Scanner::smi_value () const [inline]
Definition at line 389 of file scanner.h.
{ return current().smi_value; }
Referenced by v8::internal::ParserBase< Impl >::ParseProperty().
source_pos()
int v8::internal::Scanner::source_pos () [inline], [private]
Definition at line 722 of file scanner.h.
                   {
    return static_cast<int>(source_->pos()) - kCharacterLookaheadBufferSize;
  }
Referenced by Scan(), ScanDecimalAsSmiWithNumericSeparators(), ScanDecimalDigits(), ScanDigitsWithNumericSeparators(), ScanEscape(), ScanHexNumber(), ScanImplicitOctalDigits(), ScanNumber(), ScanOctalEscape(), ScanPrivateName(), ScanRegExpFlags(), ScanSingleToken(), ScanTemplateSpan(), ScanUnicodeEscape(), ScanUnlimitedLengthHexNumber(), SeekForward(), SkipSingleHTMLComment(), and TryToParseMagicComment().
SourceMappingUrl()
template<typename IsolateT >
template DirectHandle< String > v8::internal::Scanner::SourceMappingUrl (IsolateT * isolate) const
Definition at line 704 of file scanner.cc.
                                                                      {
  DirectHandle<String> tmp;
  if (source_mapping_url_.length() > 0) {
    tmp = source_mapping_url_.Internalize(isolate);
  }
  return tmp;
}
References v8::internal::LiteralBuffer::Internalize(), v8::internal::LiteralBuffer::length(), and source_mapping_url_.
Referenced by v8::internal::Parser::HandleDebugMagicComments().
SourceUrl()
template<typename IsolateT >
template DirectHandle< String > v8::internal::Scanner::SourceUrl (IsolateT * isolate) const
Definition at line 692 of file scanner.cc.
                                                               {
  DirectHandle<String> tmp;
  if (source_url_.length() > 0) {
    tmp = source_url_.Internalize(isolate);
  }
  return tmp;
}
References v8::internal::LiteralBuffer::Internalize(), v8::internal::LiteralBuffer::length(), and source_url_.
Referenced by v8::internal::Parser::HandleDebugMagicComments().
stream()
const Utf16CharacterStream* v8::internal::Scanner::stream () const [inline]
Definition at line 447 of file scanner.h.
{ return source_; }
TryToParseMagicComment()
void v8::internal::Scanner::TryToParseMagicComment (base::uc32 hash_or_at_sign) [private]
Definition at line 279 of file scanner.cc.
                                                             {
  // Magic comments are of the form: //[#@]\s<name>=\s*<value>\s*.* and this
  // function will just return if it cannot parse a magic comment.
  DCHECK(!IsWhiteSpaceOrLineTerminator(kEndOfInput));
  if (!IsWhiteSpace(c0_)) return;
  Advance();
  LiteralBuffer name;
  name.Start();
  while (c0_ != kEndOfInput && !IsWhiteSpaceOrLineTerminator(c0_) &&
         c0_ != '=') {
    name.AddChar(c0_);
    Advance();
  }
  if (!name.is_one_byte()) return;
  base::Vector<const uint8_t> name_literal = name.one_byte_literal();
  LiteralBuffer* value;
  LiteralBuffer per_function_compile_hints_value;
  if (name_literal == base::StaticOneByteVector("sourceURL")) {
    value = &source_url_;
  } else if (name_literal == base::StaticOneByteVector("sourceMappingURL")) {
    value = &source_mapping_url_;
    DCHECK(hash_or_at_sign == '#' || hash_or_at_sign == '@');
    saw_source_mapping_url_magic_comment_at_sign_ = hash_or_at_sign == '@';
  } else if (!saw_non_comment_ &&
             name_literal ==
                 base::StaticOneByteVector("allFunctionsCalledOnLoad") &&
             hash_or_at_sign == '#' && c0_ != '=') {
    saw_magic_comment_compile_hints_all_ = true;
  } else if (name_literal ==
                 base::StaticOneByteVector("functionsCalledOnLoad") &&
             hash_or_at_sign == '#') {
    value = &per_function_compile_hints_value;
  } else if (name_literal == base::StaticOneByteVector("debugId") &&
             hash_or_at_sign == '#') {
    value = &debug_id_;
  } else {
    return;
  }
  if (c0_ != '=')
    return;
  value->Start();
  Advance();
  while (IsWhiteSpace(c0_)) {
    Advance();
  }
  while (c0_ != kEndOfInput && !unibrow::IsLineTerminator(c0_)) {
    if (IsWhiteSpace(c0_)) {
      break;
    }
    value->AddChar(c0_);
    Advance();
  }
  // Allow whitespace at the end.
  while (c0_ != kEndOfInput && !unibrow::IsLineTerminator(c0_)) {
    if (!IsWhiteSpace(c0_)) {
      value->Start();
      break;
    }
    Advance();
  }
  if (value == &per_function_compile_hints_value &&
      per_function_compile_hints_value.is_one_byte()) {
    base::Vector<const uint8_t> value_literal =
        per_function_compile_hints_value.one_byte_literal();
    per_function_compile_hint_positions_.clear();
    per_function_compile_hint_positions_idx_ = 0;
    ProcessPerFunctionCompileHints(value_literal, source_pos(),
                                   per_function_compile_hint_positions_);
  }
}
References Advance(), c0_, v8::internal::DCHECK(), debug_id_, v8::internal::LiteralBuffer::is_one_byte(), unibrow::IsLineTerminator(), v8::internal::IsWhiteSpace(), v8::internal::IsWhiteSpaceOrLineTerminator(), kEndOfInput, v8::internal::name, v8::internal::LiteralBuffer::one_byte_literal(), per_function_compile_hint_positions_, per_function_compile_hint_positions_idx_, v8::internal::anonymous_namespace{scanner.cc}::ProcessPerFunctionCompileHints(), saw_magic_comment_compile_hints_all_, saw_non_comment_, saw_source_mapping_url_magic_comment_at_sign_, source_mapping_url_, source_pos(), source_url_, v8::base::StaticOneByteVector(), and v8::internal::value.
Referenced by SkipMagicComment().
Member Data Documentation
c0_
base::uc32 v8::internal::Scanner::c0_ [private]
Definition at line 759 of file scanner.h.
Referenced by ScanDecimalAsSmi(), ScanDecimalAsSmiWithNumericSeparators(), ScanDecimalDigits(), ScanDigitsWithNumericSeparators(), ScanEscape(), ScanHexNumber(), ScanHtmlComment(), ScanIdentifierOrKeywordInner(), ScanIdentifierOrKeywordInnerSlow(), ScanIdentifierUnicodeEscape(), ScanImplicitOctalDigits(), ScanNumber(), ScanOctalEscape(), ScanPrivateName(), ScanRegExpFlags(), ScanRegExpPattern(), ScanSignedInteger(), ScanSingleToken(), ScanString(), ScanTemplateSpan(), ScanUnicodeEscape(), ScanUnlimitedLengthHexNumber(), SeekNext(), SkipMagicComment(), SkipMultiLineComment(), SkipWhiteSpace(), and TryToParseMagicComment().
current_
TokenDesc* v8::internal::Scanner::current_ [private]
Definition at line 749 of file scanner.h.
Referenced by Next().
debug_id_
LiteralBuffer v8::internal::Scanner::debug_id_ [private]
Definition at line 769 of file scanner.h.
Referenced by DebugId(), and TryToParseMagicComment().
flags_
UnoptimizedCompileFlags v8::internal::Scanner::flags_ [private]
Definition at line 747 of file scanner.h.
Referenced by SkipSingleHTMLComment().
found_html_comment_
bool v8::internal::Scanner::found_html_comment_ [private]
Definition at line 764 of file scanner.h.
Referenced by ScanHtmlComment().
kCharacterLookaheadBufferSize
const int v8::internal::Scanner::kCharacterLookaheadBufferSize = 1 [static], [private]
Definition at line 500 of file scanner.h.
kEndOfInput
constexpr base::uc32 v8::internal::Scanner::kEndOfInput = Utf16CharacterStream::kEndOfInput [static], [constexpr]
Definition at line 277 of file scanner.h.
Referenced by ScanEscape(), ScanPrivateName(), ScanRegExpPattern(), ScanSingleToken(), ScanString(), ScanTemplateSpan(), SkipMagicComment(), SkipMultiLineComment(), and TryToParseMagicComment().
kInvalidSequence
constexpr base::uc32 v8::internal::Scanner::kInvalidSequence = static_cast<base::uc32>(-1) [static], [constexpr]
Definition at line 278 of file scanner.h.
Referenced by Invalid(), and ScanUnicodeEscape().
kMaxAscii
const int v8::internal::Scanner::kMaxAscii = 127 [static], [private]
Definition at line 501 of file scanner.h.
Referenced by ScanIdentifierOrKeywordInner(), ScanSingleToken(), ScanString(), and SkipMultiLineComment().
next_
TokenDesc* v8::internal::Scanner::next_ [private]
Definition at line 750 of file scanner.h.
Referenced by Next(), PeekAhead(), PeekAheadAhead(), Scan(), and ScanTemplateSpan().
next_next_
TokenDesc* v8::internal::Scanner::next_next_ [private]
Definition at line 751 of file scanner.h.
Referenced by Next(), PeekAhead(), and PeekAheadAhead().
next_next_next_
TokenDesc* v8::internal::Scanner::next_next_next_ [private]
Definition at line 752 of file scanner.h.
Referenced by Next(), and PeekAheadAhead().
octal_message_
MessageTemplate v8::internal::Scanner::octal_message_ [private]
Definition at line 778 of file scanner.h.
Referenced by ScanEscape(), ScanImplicitOctalDigits(), ScanNumber(), ScanOctalEscape(), and ScanTemplateSpan().
octal_pos_
Location v8::internal::Scanner::octal_pos_ [private]
Definition at line 777 of file scanner.h.
Referenced by ScanEscape(), ScanImplicitOctalDigits(), ScanNumber(), ScanOctalEscape(), and ScanTemplateSpan().
per_function_compile_hint_positions_
std::vector<int> v8::internal::Scanner::per_function_compile_hint_positions_ [private]
Definition at line 773 of file scanner.h.
Referenced by HasPerFunctionCompileHint(), and TryToParseMagicComment().
per_function_compile_hint_positions_idx_
size_t v8::internal::Scanner::per_function_compile_hint_positions_idx_ = 0 [private]
Definition at line 774 of file scanner.h.
Referenced by HasPerFunctionCompileHint(), and TryToParseMagicComment().
saw_magic_comment_compile_hints_all_
bool v8::internal::Scanner::saw_magic_comment_compile_hints_all_ = false [private]
Definition at line 771 of file scanner.h.
Referenced by TryToParseMagicComment().
saw_non_comment_
bool v8::internal::Scanner::saw_non_comment_ = false [private]
Definition at line 772 of file scanner.h.
Referenced by ScanSingleToken(), and TryToParseMagicComment().
saw_source_mapping_url_magic_comment_at_sign_
bool v8::internal::Scanner::saw_source_mapping_url_magic_comment_at_sign_ = false [private]
Definition at line 770 of file scanner.h.
Referenced by TryToParseMagicComment().
scanner_error_
MessageTemplate v8::internal::Scanner::scanner_error_ [private]
Definition at line 780 of file scanner.h.
Referenced by ScanTemplateSpan().
scanner_error_location_
Location v8::internal::Scanner::scanner_error_location_ [private]
Definition at line 781 of file scanner.h.
Referenced by ScanTemplateSpan().
source_
Utf16CharacterStream* const v8::internal::Scanner::source_ [private]
Definition at line 756 of file scanner.h.
Referenced by ScanSingleToken(), SeekForward(), and SeekNext().
source_mapping_url_
LiteralBuffer v8::internal::Scanner::source_mapping_url_ [private]
Definition at line 768 of file scanner.h.
Referenced by SourceMappingUrl(), and TryToParseMagicComment().
source_url_
LiteralBuffer v8::internal::Scanner::source_url_ [private]
Definition at line 767 of file scanner.h.
Referenced by SourceUrl(), and TryToParseMagicComment().
token_storage_
TokenDesc v8::internal::Scanner::token_storage_[4] [private]
Definition at line 761 of file scanner.h.
Referenced by SeekNext().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/scanner.h
/mnt/V8SourceCode/src/parsing/scanner-inl.h
/mnt/V8SourceCode/src/parsing/scanner.cc