v8::internal::UnalignedDoubleMember Class Reference
#include <tagged-field.h>
Public Member Functions
UnalignedDoubleMember ()=default
uint64_t value_as_bits () const
void set_value_as_bits (uint64_t value)
Additional Inherited Members
Detailed Description
Definition at line 82 of file tagged-field.h.
Constructor & Destructor Documentation
UnalignedDoubleMember()
v8::internal::UnalignedDoubleMember::UnalignedDoubleMember () [default]
Member Function Documentation
set_value_as_bits()
void v8::internal::UnalignedDoubleMember::set_value_as_bits (uint64_t value) [inline]
Definition at line 89 of file tagged-field.h.
                                         {
    base::WriteUnalignedValue(storage_, value);
  }
References v8::internal::UnalignedValueMember< double >::storage_, v8::internal::UnalignedValueMember< double >::value(), and v8::base::WriteUnalignedValue().
Referenced by v8::internal::Oddball::set_to_number_raw_as_bits(), and v8::internal::HeapNumber::set_value_as_bits().
value_as_bits()
uint64_t v8::internal::UnalignedDoubleMember::value_as_bits () const [inline]
Definition at line 86 of file tagged-field.h.
                                 {
    return base::ReadUnalignedValue<uint64_t>(storage_);
  }
References v8::internal::UnalignedValueMember< double >::storage_.
Referenced by v8::internal::HeapNumber::value_as_bits().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/tagged-field.h