v8::internal::compiler::JSCallReducerAssembler::ForBuilder0 Class Reference
Public Member Functions
ForBuilder0 (JSGraphAssembler *gasm, TNode< Number > initial_value, const ConditionFunction1 &cond, const StepFunction1 &step)
void Do (const For0BodyFunction &body)
Private Types
using For0BodyFunction = std::function< void(TNode< Number >)>
Private Attributes
JSGraphAssembler *const gasm_
const TNode< Number > initial_value_
const ConditionFunction1 cond_
const StepFunction1 step_
Static Private Attributes
static constexpr MachineRepresentation kPhiRepresentation
Detailed Description
Definition at line 235 of file js-call-reducer.cc.
Member Typedef Documentation
For0BodyFunction
using v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::For0BodyFunction = std::function<void(TNode<Number>)> [private]
Definition at line 236 of file js-call-reducer.cc.
Constructor & Destructor Documentation
ForBuilder0()
v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::ForBuilder0 (JSGraphAssembler * gasm, TNode< Number > initial_value, const ConditionFunction1 & cond, const StepFunction1 & step) [inline]
Definition at line 239 of file js-call-reducer.cc.
        : gasm_(gasm),
          initial_value_(initial_value),
          cond_(cond),
          step_(step) {}
Member Function Documentation
Do()
void v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do (const For0BodyFunction & body) [inline]
Definition at line 246 of file js-call-reducer.cc.
                                          {
      auto loop_exit = gasm_->MakeLabel();
      {
        GraphAssembler::LoopScope<kPhiRepresentation> loop_scope(gasm_);
        auto loop_header = loop_scope.loop_header_label();
        auto loop_body = gasm_->MakeLabel();
        gasm_->Goto(loop_header, initial_value_);
        gasm_->Bind(loop_header);
        TNode<Number> i = loop_header->PhiAt<Number>(0);
        gasm_->BranchWithHint(cond_(i), &loop_body, &loop_exit,
                              BranchHint::kTrue);
        gasm_->Bind(&loop_body);
        body(i);
        gasm_->Goto(loop_header, step_(i));
      }
      gasm_->Bind(&loop_exit);
    }
References v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::GraphAssembler::BranchWithHint(), cond_, gasm_, v8::internal::compiler::GraphAssembler::Goto(), initial_value_, v8::internal::kTrue, v8::internal::compiler::GraphAssembler::LoopScope< Reps >::loop_header_label(), v8::internal::compiler::GraphAssembler::MakeLabel(), and step_.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
Member Data Documentation
cond_
const ConditionFunction1 v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::cond_ [private]
Definition at line 277 of file js-call-reducer.cc.
Referenced by Do().
gasm_
JSGraphAssembler* const v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::gasm_ [private]
Definition at line 275 of file js-call-reducer.cc.
Referenced by Do().
initial_value_
const TNode<Number> v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::initial_value_ [private]
Definition at line 276 of file js-call-reducer.cc.
Referenced by Do().
kPhiRepresentation
constexpr MachineRepresentation v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::kPhiRepresentation [static], [constexpr], [private]
Initial value:
=
        MachineRepresentation::kTagged
Definition at line 272 of file js-call-reducer.cc.
step_
const StepFunction1 v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::step_ [private]
Definition at line 278 of file js-call-reducer.cc.
Referenced by Do().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc