v8::internal::ZoneList< T > Class Template Reference
#include <zone-list.h>
Public Types
using iterator = T *
using const_iterator = const T *
Public Member Functions
ZoneList (int capacity, Zone *zone)
ZoneList (const ZoneList< T > &other, Zone *zone)
ZoneList (base::Vector< const T > other, Zone *zone)
ZoneList (ZoneList< T > &&other) V8_NOEXCEPT
ZoneList (const ZoneList &)=delete
ZoneList & operator= (const ZoneList &)=delete
~ZoneList ()=default
ZoneList & operator= (ZoneList &&other) V8_NOEXCEPT
T & operator[] (int i) const
T & at (int i) const
T & last () const
T & first () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool is_empty () const
int length () const
int capacity () const
base::Vector< T > ToVector () const
base::Vector< T > ToVector (int start, int length) const
base::Vector< const T > ToConstVector () const
void Add (const T &element, Zone *zone)
void AddAll (const ZoneList< T > &other, Zone *zone)
void AddAll (base::Vector< const T > other, Zone *zone)
void InsertAt (int index, const T &element, Zone *zone)
base::Vector< T > AddBlock (T value, int count, Zone *zone)
void Set (int index, const T &element)
T Remove (int i)
T RemoveLast ()
void Clear (Zone *zone)
void DropAndClear ()
void Rewind (int pos)
bool Contains (const T &elm) const
template<class Visitor >
void Iterate (Visitor *visitor)
template<typename CompareFunction >
void Sort (CompareFunction cmp)
template<typename CompareFunction >
void StableSort (CompareFunction cmp, size_t start, size_t length)
Private Member Functions
void ResizeAdd (const T &element, Zone *zone)
void ResizeAddInternal (const T &element, Zone *zone)
void Resize (int new_capacity, Zone *zone)
Private Attributes
T * data_ = nullptr
int capacity_ = 0
int length_ = 0
Detailed Description
template<typename T>
class v8::internal::ZoneList< T >
Definition at line 31 of file zone-list.h.
Member Typedef Documentation
const_iterator
template<typename T >
using v8::internal::ZoneList< T >::const_iterator = const T*
Definition at line 96 of file zone-list.h.
iterator
template<typename T >
using v8::internal::ZoneList< T >::iterator = T*
Definition at line 92 of file zone-list.h.
Constructor & Destructor Documentation
ZoneList() [1/5]
template<typename T >
v8::internal::ZoneList< T >::ZoneList (int capacity, Zone * zone) [inline]
Definition at line 35 of file zone-list.h.
                                     : capacity_(capacity) {
    DCHECK_GE(capacity, 0);
    if (capacity > 0) {
      DCHECK_NOT_NULL(zone);
      data_ = zone->AllocateArray<T>(capacity);
    } else {
      data_ = nullptr;
    }
  }
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneList< T >::capacity(), v8::internal::ZoneList< T >::data_, DCHECK_GE, and DCHECK_NOT_NULL.
ZoneList() [2/5]
template<typename T >
v8::internal::ZoneList< T >::ZoneList (const ZoneList< T > & other, Zone * zone) [inline]
Definition at line 46 of file zone-list.h.
      : ZoneList(other.length(), zone) {
    AddAll(other, zone);
  }
References v8::internal::ZoneList< T >::AddAll().
ZoneList() [3/5]
template<typename T >
v8::internal::ZoneList< T >::ZoneList (base::Vector< const T > other, Zone * zone) [inline]
Definition at line 52 of file zone-list.h.
      : ZoneList(other.length(), zone) {
    AddAll(other, zone);
  }
References v8::internal::ZoneList< T >::AddAll().
ZoneList() [4/5]
template<typename T >
v8::internal::ZoneList< T >::ZoneList (ZoneList< T > && other) [inline]
Definition at line 57 of file zone-list.h.
{ *this = std::move(other); }
ZoneList() [5/5]
template<typename T >
v8::internal::ZoneList< T >::ZoneList (const ZoneList< T > &) [delete]
 ZoneList()
template<typename T >
v8::internal::ZoneList< T >::~ZoneList () [default]
Member Function Documentation
Add()
template<typename T >
void v8::internal::ZoneList< T >::Add (const T & element, Zone * zone)
Definition at line 19 of file zone-list-inl.h.
                                                  {
  if (length_ < capacity_) {
    data_[length_++] = element;
  } else {
    ZoneList<T>::ResizeAdd(element, zone);
  }
}
References v8::internal::ZoneList< T >::ResizeAdd().
Referenced by v8::internal::CharacterRange::AddCaseEquivalents(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddCharacter(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddClass(), v8::internal::CharacterRange::AddClassEscape(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddClassNegated(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::AddClassString(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::AddMaybeSimpleCaseFoldedRange(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTrailSurrogate(), v8::internal::CharacterRange::AddUnicodeCaseEquivalents(), v8::internal::TextNode::CreateForSurrogatePair(), v8::internal::Parser::DeclareClass(), v8::internal::Parser::DeclareFunction(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::ChoiceNode::FilterOneByte(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::CharacterRange::Intersect(), v8::internal::CharacterRange::List(), v8::internal::CharacterRange::Negate(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassIntersection(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassRanges(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSubtraction(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion(), v8::internal::Parser::ParseExportDefault(), v8::internal::Parser::PrepareWrappedArguments(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::Rewriter::RewriteBody(), and v8::internal::DynamicBitSet::Set().
AddAll() [1/2]
template<typename T >
void v8::internal::ZoneList< T >::AddAll (base::Vector< const T > other, Zone * zone)
Definition at line 33 of file zone-list-inl.h.
                                                              {
  int length = other.length();
  if (length == 0) return;
  int result_length = length_ + length;
  if (capacity_ < result_length) Resize(result_length, zone);
  if (std::is_trivially_copyable_v<T>) {
    memcpy(&data_[length_], other.begin(), sizeof(T) * length);
  } else {
    std::copy(other.begin(), other.end(), &data_[length_]);
  }
  length_ = result_length;
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), v8::base::Vector< T >::length(), v8::internal::length, and cppgc::subtle::Resize().
AddAll() [2/2]
template<typename T >
void v8::internal::ZoneList< T >::AddAll (const ZoneList< T > & other, Zone * zone)
Definition at line 28 of file zone-list-inl.h.
                                                             {
  AddAll(other.ToVector(), zone);
}
References v8::internal::ZoneList< T >::ToVector().
Referenced by v8::internal::CharacterRange::AddClassEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::AddMaybeSimpleCaseFoldedRange(), v8::internal::RegExpClassSetOperand::Union(), and v8::internal::ZoneList< T >::ZoneList().
AddBlock()
template<typename T >
base::Vector< T > v8::internal::ZoneList< T >::AddBlock (T value, int count, Zone * zone)
Definition at line 84 of file zone-list-inl.h.
                                                                  {
  int start = length_;
  for (int i = 0; i < count; i++) Add(value, zone);
  return base::Vector<T>(&data_[start], count);
}
References v8::bigint::Add(), and v8::internal::value.
at()
template<typename T >
T& v8::internal::ZoneList< T >::at (int i) const [inline]
Definition at line 88 of file zone-list.h.
{ return operator[](i); }
References v8::internal::ZoneList< T >::operator[]().
Referenced by v8::internal::CharacterRange::AddCaseEquivalents(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::AddClassString(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::CharacterRange::AddUnicodeCaseEquivalents(), v8::internal::ChoiceNode::AssertGuardsMentionRegisters(), v8::internal::interpreter::BytecodeGenerator::BuildInitializationBlockForParametersIfExist(), v8::internal::CharacterRange::Canonicalize(), v8::internal::CharacterRange::ClampToOneByte(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareInverseRanges(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareRanges(), v8::internal::ParserBase< Impl >::ContainsLabel(), v8::internal::anonymous_namespace{regexp-compiler.cc}::CutOutRange(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Equals(), v8::internal::CharacterRange::Equals(), v8::internal::TextNode::FillInBMInfo(), v8::internal::ChoiceNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::CallPrinter::FindArguments(), v8::internal::anonymous_namespace{source-range-ast-visitor.cc}::FindLastNonSyntheticStatement(), v8::internal::CallPrinter::FindStatements(), v8::internal::ZoneList< T >::first(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GenerateBranches(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Hash(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::InsertRangeInCanonicalList(), v8::internal::CharacterRange::Intersect(), v8::internal::CharacterRange::IsCanonical(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable(), v8::internal::ZoneList< T >::last(), v8::internal::anonymous_namespace{regexp-ast.cc}::ListCaptureRegisters(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MakeRangeArray(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::MaybeRewrite(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MoveRanges(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::NeedsDesugaringForUnicode(), v8::internal::CharacterRange::Negate(), v8::internal::anonymous_namespace{regexp-macro-assembler-tracer.cc}::PrintRangeArray(), v8::internal::Processor::Process(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::RangeArrayLengthFor(), v8::internal::anonymous_namespace{regexp-compiler.cc}::RangesContainLatin1Equivalents(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::SafeAdvanceRange(), v8::internal::RegExpDisjunction::SortConsecutiveAtoms(), v8::internal::anonymous_namespace{regexp-compiler.cc}::SplitSearchSpace(), v8::internal::CharacterRange::Subtract(), v8::internal::UnicodeRangeSplitter::UnicodeRangeSplitter(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAlternative(), v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral(), v8::internal::AstVisitor< Subclass >::VisitExpressions(), v8::internal::AstTraversalVisitor< Subclass >::VisitStatements(), v8::internal::AstVisitor< Subclass >::VisitStatements(), v8::internal::interpreter::BytecodeGenerator::VisitStatements(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitText().
begin() [1/2]
template<typename T >
iterator v8::internal::ZoneList< T >::begin () [inline]
Definition at line 93 of file zone-list.h.
{ return &data_[0]; }
References v8::internal::ZoneList< T >::data_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
begin() [2/2]
template<typename T >
const_iterator v8::internal::ZoneList< T >::begin () const [inline]
Definition at line 97 of file zone-list.h.
{ return &data_[0]; }
References v8::internal::ZoneList< T >::data_.
capacity()
template<typename T >
int v8::internal::ZoneList< T >::capacity () const [inline]
Definition at line 102 of file zone-list.h.
{ return capacity_; }
References v8::internal::ZoneList< T >::capacity_.
Referenced by v8::internal::ZoneList< T >::ZoneList().
Clear()
template<typename T >
void v8::internal::ZoneList< T >::Clear (Zone * zone) [inline]
Definition at line 118 of file zone-list-inl.h.
                                  {
  if (data_) zone->DeleteArray<T>(data_, capacity_);
  DropAndClear();
}
Contains()
template<typename T >
bool v8::internal::ZoneList< T >::Contains (const T & elm) const [inline]
Definition at line 159 of file zone-list.h.
                                           {
    for (int i = 0; i < length_; i++) {
      if (data_[i] == elm) return true;
    }
    return false;
  }
References v8::internal::ZoneList< T >::data_, and v8::internal::ZoneList< T >::length_.
Referenced by v8::internal::DynamicBitSet::Get(), and v8::internal::DynamicBitSet::Set().
DropAndClear()
template<typename T >
void v8::internal::ZoneList< T >::DropAndClear () [inline]
Definition at line 150 of file zone-list.h.
                                {
    data_ = nullptr;
    capacity_ = 0;
    length_ = 0;
  }
References v8::internal::ZoneList< T >::capacity_, v8::internal::ZoneList< T >::data_, and v8::internal::ZoneList< T >::length_.
end() [1/2]
template<typename T >
iterator v8::internal::ZoneList< T >::end () [inline]
Definition at line 94 of file zone-list.h.
{ return &data_[length_]; }
References v8::internal::ZoneList< T >::data_, and v8::internal::ZoneList< T >::length_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
end() [2/2]
template<typename T >
const_iterator v8::internal::ZoneList< T >::end () const [inline]
Definition at line 98 of file zone-list.h.
{ return &data_[length_]; }
References v8::internal::ZoneList< T >::data_, and v8::internal::ZoneList< T >::length_.
first()
template<typename T >
T& v8::internal::ZoneList< T >::first () const [inline]
Definition at line 90 of file zone-list.h.
{ return at(0); }
References v8::internal::ZoneList< T >::at().
Referenced by v8::internal::Parser::CloseTemplateLiteral(), and v8::internal::Parser::ParseExportDefault().
InsertAt()
template<typename T >
void v8::internal::ZoneList< T >::InsertAt (int index, const T & element, Zone * zone)
Definition at line 97 of file zone-list-inl.h.
                                                              {
  DCHECK(index >= 0 && index <= length_);
  Add(elm, zone);
  for (int i = length_ - 1; i > index; --i) {
    data_[i] = data_[i - 1];
  }
  data_[index] = elm;
}
References v8::bigint::Add(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::index.
is_empty()
template<typename T >
bool v8::internal::ZoneList< T >::is_empty () const [inline]
Definition at line 100 of file zone-list.h.
{ return length_ == 0; }
References v8::internal::ZoneList< T >::length_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::RegExpClassSetExpression::ComputeExpression(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::CreateNamedCaptureAtIndex(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::SourceRangeAstVisitor::MaybeRemoveLastContinuationRange(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSetOperand(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion(), v8::internal::Rewriter::RewriteBody(), v8::internal::DynamicBitSet::Set(), and v8::internal::CharacterRange::Subtract().
Iterate()
template<typename T >
template<class Visitor >
void v8::internal::ZoneList< T >::Iterate (Visitor * visitor)
Definition at line 131 of file zone-list-inl.h.
                                          {
  for (int i = 0; i < length_; i++) visitor->Apply(&data_[i]);
}
last()
template<typename T >
T& v8::internal::ZoneList< T >::last () const [inline]
Definition at line 89 of file zone-list.h.
{ return at(length_ - 1); }
References v8::internal::ZoneList< T >::at(), and v8::internal::ZoneList< T >::length_.
Referenced by v8::internal::SourceRangeAstVisitor::MaybeRemoveLastContinuationRange().
length()
template<typename T >
int v8::internal::ZoneList< T >::length () const [inline]
Definition at line 101 of file zone-list.h.
{ return length_; }
References v8::internal::ZoneList< T >::length_.
Referenced by v8::internal::CharacterRange::AddCaseEquivalents(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::AddClassString(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::CharacterRange::AddUnicodeCaseEquivalents(), v8::internal::ChoiceNode::AssertGuardsMentionRegisters(), v8::internal::interpreter::BytecodeGenerator::BuildInitializationBlockForParametersIfExist(), v8::internal::CharacterRange::Canonicalize(), v8::internal::CharacterRange::ClampToOneByte(), v8::internal::Parser::CloseTemplateLiteral(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareInverseRanges(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareRanges(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileCharacterRanges(), v8::internal::ParserBase< Impl >::ContainsLabel(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Equals(), v8::internal::CharacterRange::Equals(), v8::internal::TextNode::FillInBMInfo(), v8::internal::ChoiceNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::CallPrinter::FindArguments(), v8::internal::anonymous_namespace{source-range-ast-visitor.cc}::FindLastNonSyntheticStatement(), v8::internal::CallPrinter::FindStatements(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Hash(), v8::internal::CharacterRange::Intersect(), v8::internal::RegExpDisjunction::IsAnchoredAtEnd(), v8::internal::RegExpAlternative::IsAnchoredAtEnd(), v8::internal::RegExpDisjunction::IsAnchoredAtStart(), v8::internal::RegExpAlternative::IsAnchoredAtStart(), v8::internal::CharacterRange::IsCanonical(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable(), v8::internal::anonymous_namespace{regexp-ast.cc}::ListCaptureRegisters(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MakeRangeArray(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::MaybeRewrite(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::NeedsDesugaringForUnicode(), v8::internal::CharacterRange::Negate(), v8::internal::Parser::ParseExportDefault(), v8::internal::Parser::ParseImportDeclaration(), v8::internal::anonymous_namespace{regexp-macro-assembler-tracer.cc}::PrintRangeArray(), v8::internal::Processor::Process(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::RangeArrayLengthFor(), v8::internal::anonymous_namespace{regexp-compiler.cc}::RangesContainLatin1Equivalents(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::RegExpDisjunction::SortConsecutiveAtoms(), v8::internal::CharacterRange::Subtract(), v8::internal::ZoneList< T >::ToVector(), v8::internal::UnicodeRangeSplitter::UnicodeRangeSplitter(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAlternative(), v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitDisjunction(), v8::internal::AstVisitor< Subclass >::VisitExpressions(), v8::internal::AstTraversalVisitor< Subclass >::VisitStatements(), v8::internal::AstVisitor< Subclass >::VisitStatements(), v8::internal::interpreter::BytecodeGenerator::VisitStatements(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitText().
operator=() [1/2]
template<typename T >
ZoneList& v8::internal::ZoneList< T >::operator= (const ZoneList< T > &) [delete]
operator=() [2/2]
template<typename T >
ZoneList& v8::internal::ZoneList< T >::operator= (ZoneList< T > && other) [inline]
Definition at line 67 of file zone-list.h.
                                                    {
    // We don't have a Zone object, so we'll have to drop the data_ array.
    // If this assert ever fails, consider calling Clear(Zone*) or
    // DropAndClear() before the move assignment to make it explicit what's
    // happenning with the lvalue.
    DCHECK_NULL(data_);
    data_ = other.data_;
    capacity_ = other.capacity_;
    length_ = other.length_;
    other.DropAndClear();
    return *this;
  }
References v8::internal::ZoneList< T >::capacity_, v8::internal::ZoneList< T >::data_, DCHECK_NULL, and v8::internal::ZoneList< T >::length_.
operator[]()
template<typename T >
T& v8::internal::ZoneList< T >::operator[] (int i) const [inline]
Definition at line 83 of file zone-list.h.
                                    {
    DCHECK_LE(0, i);
    DCHECK_GT(static_cast<unsigned>(length_), static_cast<unsigned>(i));
    return data_[i];
  }
References v8::internal::ZoneList< T >::data_, DCHECK_GT, DCHECK_LE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::ZoneList< T >::length_.
Referenced by v8::internal::ZoneList< T >::at().
Remove()
template<typename T >
T v8::internal::ZoneList< T >::Remove (int i)
Definition at line 107 of file zone-list-inl.h.
                           {
  T element = at(i);
  length_--;
  while (i < length_) {
    data_[i] = data_[i + 1];
    i++;
  }
  return element;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::ZoneList< T >::RemoveLast().
RemoveLast()
template<typename T >
T v8::internal::ZoneList< T >::RemoveLast () [inline]
Definition at line 140 of file zone-list.h.
{ return Remove(length_ - 1); }
References v8::internal::ZoneList< T >::length_, and v8::internal::ZoneList< T >::Remove().
Resize()
template<typename T >
void v8::internal::ZoneList< T >::Resize (int new_capacity, Zone * zone) [private]
Definition at line 68 of file zone-list-inl.h.
                                                     {
  DCHECK_LE(length_, new_capacity);
  T* new_data = zone->AllocateArray<T>(new_capacity);
  if (length_ > 0) {
    if (std::is_trivially_copyable_v<T>) {
      MemCopy(new_data, data_, length_ * sizeof(T));
    } else {
      std::copy(&data_[0], &data_[length_], &new_data[0]);
    }
  }
  if (data_) zone->DeleteArray<T>(data_, capacity_);
  data_ = new_data;
  capacity_ = new_capacity;
}
References v8::internal::Zone::AllocateArray(), DCHECK_LE, v8::internal::Zone::DeleteArray(), and v8::internal::MemCopy().
ResizeAdd()
template<typename T >
void v8::internal::ZoneList< T >::ResizeAdd (const T & element, Zone * zone) [private]
Definition at line 50 of file zone-list-inl.h.
                                                        {
  ResizeAddInternal(element, zone);
}
Referenced by v8::internal::ZoneList< T >::Add().
ResizeAddInternal()
template<typename T >
void v8::internal::ZoneList< T >::ResizeAddInternal (const T & element, Zone * zone) [private]
Definition at line 55 of file zone-list-inl.h.
                                                                {
  DCHECK(length_ >= capacity_);
  // Grow the list capacity by 100%, but make sure to let it grow
  // even when the capacity is zero (possible initial case).
  int new_capacity = 1 + 2 * capacity_;
  // Since the element reference could be an element of the list, copy
  // it out of the old backing storage before resizing.
  T temp = element;
  Resize(new_capacity, zone);
  data_[length_++] = temp;
}
References v8::internal::DCHECK(), and cppgc::subtle::Resize().
Rewind()
template<typename T >
void v8::internal::ZoneList< T >::Rewind (int pos) [inline]
Definition at line 124 of file zone-list-inl.h.
                                {
  DCHECK(0 <= pos && pos <= length_);
  length_ = pos;
}
References v8::internal::DCHECK().
Referenced by v8::internal::CharacterRange::AddUnicodeCaseEquivalents(), v8::internal::CharacterRange::Canonicalize(), v8::internal::CharacterRange::ClampToOneByte(), v8::internal::RegExpClassSetExpression::ComputeExpression(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::RegExpClassSetOperand::Intersect(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), and v8::internal::RegExpClassSetOperand::Subtract().
Set()
template<typename T >
void v8::internal::ZoneList< T >::Set (int index, const T & element)
Definition at line 91 of file zone-list-inl.h.
                                             {
  DCHECK(index >= 0 && index <= length_);
  data_[index] = elm;
}
References v8::internal::DCHECK(), and v8::internal::index.
Referenced by v8::internal::Processor::Process().
Sort()
template<typename T >
template<typename CompareFunction >
void v8::internal::ZoneList< T >::Sort (CompareFunction cmp)
Definition at line 137 of file zone-list-inl.h.
                                          {
  std::sort(begin(), end(),
            [cmp](const T& a, const T& b) { return cmp(&a, &b) < 0; });
#ifdef DEBUG
  for (int i = 1; i < length_; i++) {
    DCHECK_LE(cmp(&data_[i - 1], &data_[i]), 0);
  }
#endif
}
References v8::internal::compiler::begin(), DCHECK_LE, v8::internal::compiler::end(), and v8::base::sort().
StableSort()
template<typename T >
template<typename CompareFunction >
void v8::internal::ZoneList< T >::StableSort (CompareFunction cmp, size_t start, size_t length)
Definition at line 149 of file zone-list-inl.h.
                                                                    {
  std::stable_sort(begin() + s, begin() + s + l,
                   [cmp](const T& a, const T& b) { return cmp(&a, &b) < 0; });
#ifdef DEBUG
  for (size_t i = s + 1; i < l; i++) {
    DCHECK_LE(cmp(&data_[i - 1], &data_[i]), 0);
  }
#endif
}
References v8::internal::compiler::begin(), DCHECK_LE, and v8::internal::compiler::turboshaft::l.
Referenced by v8::internal::RegExpDisjunction::SortConsecutiveAtoms().
ToConstVector()
template<typename T >
base::Vector<const T> v8::internal::ZoneList< T >::ToConstVector () const [inline]
Definition at line 110 of file zone-list.h.
                                            {
    return base::Vector<const T>(data_, length_);
  }
References v8::internal::ZoneList< T >::data_, and v8::internal::ZoneList< T >::length_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTrailSurrogate(), v8::internal::Parser::CloseTemplateLiteral(), and v8::internal::TextNode::CreateForSurrogatePair().
ToVector() [1/2]
template<typename T >
base::Vector<T> v8::internal::ZoneList< T >::ToVector () const [inline]
Definition at line 104 of file zone-list.h.
{ return base::Vector<T>(data_, length_); }
References v8::internal::ZoneList< T >::data_, and v8::internal::ZoneList< T >::length_.
Referenced by v8::internal::ZoneList< T >::AddAll(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::AddClassString(), and v8::internal::anonymous_namespace{experimental.cc}::CompileImpl().
ToVector() [2/2]
template<typename T >
base::Vector<T> v8::internal::ZoneList< T >::ToVector (int start, int length) const [inline]
Definition at line 105 of file zone-list.h.
                                                      {
    DCHECK_LE(start, length_);
    return base::Vector<T>(&data_[start], std::min(length_ - start, length));
  }
References v8::internal::ZoneList< T >::data_, DCHECK_LE, v8::internal::ZoneList< T >::length(), and v8::internal::ZoneList< T >::length_.
Member Data Documentation
capacity_
template<typename T >
int v8::internal::ZoneList< T >::capacity_ = 0 [private]
Definition at line 178 of file zone-list.h.
Referenced by v8::internal::ZoneList< T >::capacity(), v8::internal::ZoneList< T >::DropAndClear(), and v8::internal::ZoneList< T >::operator=().
data_
template<typename T >
T* v8::internal::ZoneList< T >::data_ = nullptr [private]
Definition at line 177 of file zone-list.h.
Referenced by v8::internal::ZoneList< T >::begin(), v8::internal::ZoneList< T >::Contains(), v8::internal::ZoneList< T >::DropAndClear(), v8::internal::ZoneList< T >::end(), v8::internal::ZoneList< T >::operator=(), v8::internal::ZoneList< T >::operator[](), v8::internal::ZoneList< T >::ToConstVector(), v8::internal::ZoneList< T >::ToVector(), and v8::internal::ZoneList< T >::ZoneList().
length_
template<typename T >
int v8::internal::ZoneList< T >::length_ = 0 [private]
Definition at line 179 of file zone-list.h.
Referenced by v8::internal::ZoneList< T >::Contains(), v8::internal::ZoneList< T >::DropAndClear(), v8::internal::ZoneList< T >::end(), v8::internal::ZoneList< T >::is_empty(), v8::internal::ZoneList< T >::last(), v8::internal::ZoneList< T >::length(), v8::internal::ZoneList< T >::operator=(), v8::internal::ZoneList< T >::operator[](), v8::internal::ZoneList< T >::RemoveLast(), v8::internal::ZoneList< T >::ToConstVector(), and v8::internal::ZoneList< T >::ToVector().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/scoped-list.h
/mnt/V8SourceCode/src/zone/zone-list.h
/mnt/V8SourceCode/src/zone/zone-list-inl.h