v8::internal::NativeContextStats Class Reference
#include <memory-measurement.h>
Public Member Functions
void IncrementSize (Address context, Tagged< Map > map, Tagged< HeapObject > object, size_t size)
size_t Get (Address context) const
void Clear ()
void Merge (const NativeContextStats &other)
bool Empty () const
Private Member Functions
bool HasExternalBytes (Tagged< Map > map)
void IncrementExternalSize (Address context, Tagged< Map > map, Tagged< HeapObject > object)
Private Attributes
std::unordered_map< Address, size_t > size_by_context_
Detailed Description
Definition at line 81 of file memory-measurement.h.
Member Function Documentation
Clear()
void v8::internal::NativeContextStats::Clear ()
Definition at line 375 of file memory-measurement.cc.
{ size_by_context_.clear(); }
References size_by_context_.
Referenced by v8::internal::MarkCompactCollector::Finish().
Empty()
bool v8::internal::NativeContextStats::Empty () const [inline]
Definition at line 94 of file memory-measurement.h.
{ return size_by_context_.empty(); }
Get()
size_t v8::internal::NativeContextStats::Get (Address context) const [inline]
Definition at line 86 of file memory-measurement.h.
                                    {
    const auto it = size_by_context_.find(context);
    if (it == size_by_context_.end()) return 0;
    return it->second;
  }
Referenced by v8::internal::MemoryMeasurement::FinishProcessing().
HasExternalBytes()
bool v8::internal::NativeContextStats::HasExternalBytes (Tagged< Map > map) [inline], [private]
Definition at line 32 of file memory-measurement-inl.h.
                                                                   {
  InstanceType instance_type = map->instance_type();
  return (instance_type == JS_ARRAY_BUFFER_TYPE ||
          InstanceTypeChecker::IsExternalString(instance_type));
}
References v8::internal::InstanceTypeChecker::IsExternalString().
Referenced by IncrementSize().
IncrementExternalSize()
void v8::internal::NativeContextStats::IncrementExternalSize (Address context, Tagged< Map > map, Tagged< HeapObject > object) [private]
Definition at line 383 of file memory-measurement.cc.
                                                                          {
  InstanceType instance_type = map->instance_type();
  size_t external_size = 0;
  if (instance_type == JS_ARRAY_BUFFER_TYPE) {
    external_size = Cast<JSArrayBuffer>(object)->GetByteLength();
  } else {
    DCHECK(InstanceTypeChecker::IsExternalString(instance_type));
    external_size = Cast<ExternalString>(object)->ExternalPayloadSize();
  }
  size_by_context_[context] += external_size;
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsExternalString(), and size_by_context_.
Referenced by IncrementSize().
IncrementSize()
void v8::internal::NativeContextStats::IncrementSize (Address context, Tagged< Map > map, Tagged< HeapObject > object, size_t size) [inline]
Definition at line 38 of file memory-measurement-inl.h.
                                                              {
  size_by_context_[context] += size;
  if (HasExternalBytes(map)) {
    IncrementExternalSize(context, map, object);
  }
}
References HasExternalBytes(), IncrementExternalSize(), size(), and size_by_context_.
Referenced by v8::internal::ConcurrentMarking::RunMajor().
Merge()
void v8::internal::NativeContextStats::Merge (const NativeContextStats & other)
Definition at line 377 of file memory-measurement.cc.
                                                              {
  for (const auto& it : other.size_by_context_) {
    size_by_context_[it.first] += it.second;
  }
}
References size_by_context_.
Referenced by v8::internal::ConcurrentMarking::FlushNativeContexts().
Member Data Documentation
size_by_context_
std::unordered_map<Address, size_t> v8::internal::NativeContextStats::size_by_context_ [private]
Definition at line 100 of file memory-measurement.h.
Referenced by Clear(), IncrementExternalSize(), IncrementSize(), and Merge().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/memory-measurement.h
/mnt/V8SourceCode/src/heap/memory-measurement-inl.h
/mnt/V8SourceCode/src/heap/memory-measurement.cc