v8::internal::compiler::turboshaft::Pipeline Class Reference
#include <pipelines.h>
Public Member Functions
Pipeline (PipelineData *data)
PipelineData * data () const
void BeginPhaseKind (const char *phase_kind_name)
void EndPhaseKind ()
template<TurboshaftPhase Phase, typename... Args>
V8_WARN_UNUSED_RESULT auto Run (Args &&... args)
void PrintGraph (Zone *zone, const char *phase_name)
void TraceSequence (const char *phase_name)
bool CreateGraphWithMaglev (Linkage *linkage)
bool CreateGraphFromTurbofan (compiler::TFPipelineData *turbofan_data, Linkage *linkage)
bool OptimizeTurboshaftGraph (Linkage *linkage)
V8_WARN_UNUSED_RESULT bool RunSimplificationAndNormalizationPhase ()
V8_WARN_UNUSED_RESULT bool PrepareForInstructionSelection (const ProfileDataFromFile *profile=nullptr)
bool SelectInstructions (Linkage *linkage)
V8_WARN_UNUSED_RESULT bool AllocateRegisters (CallDescriptor *call_descriptor)
bool MayHaveUnverifiableGraph () const
void VerifyGeneratedCodeIsIdempotent ()
V8_WARN_UNUSED_RESULT bool AllocateRegisters (const RegisterConfiguration *config, CallDescriptor *call_descriptor, bool run_verifier)
V8_WARN_UNUSED_RESULT bool AssembleCode (Linkage *linkage)
MaybeHandle< Code > GenerateCode (CallDescriptor *call_descriptor)
bool GenerateCode (Linkage *linkage, std::shared_ptr< OsrHelper > osr_helper={}, JumpOptimizationInfo *jump_optimization_info=nullptr, const ProfileDataFromFile *profile=nullptr, int initial_graph_hash=0)
OptimizedCompilationInfo * info ()
MaybeIndirectHandle< Code > FinalizeCode (bool retire_broker=true)
bool CommitDependencies (Handle< Code > code)
Private Attributes
PipelineData * data_
Detailed Description
Definition at line 51 of file pipelines.h.
Constructor & Destructor Documentation
Pipeline()
v8::internal::compiler::turboshaft::Pipeline::Pipeline (PipelineData * data) [inline], [explicit]
Definition at line 53 of file pipelines.h.
: data_(data) {}
Member Function Documentation
AllocateRegisters() [1/2]
V8_WARN_UNUSED_RESULT bool v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters (CallDescriptor * call_descriptor) [inline]
Definition at line 335 of file pipelines.h.
                                       {
    BeginPhaseKind("V8.TFRegisterAllocation");
    bool run_verifier = v8_flags.turbo_verify_allocation;
    // Allocate registers.
    const RegisterConfiguration* config = RegisterConfiguration::Default();
    std::unique_ptr<const RegisterConfiguration> restricted_config;
    if (call_descriptor->HasRestrictedAllocatableRegisters()) {
      RegList registers = call_descriptor->AllocatableRegisters();
      DCHECK_LT(0, registers.Count());
      restricted_config.reset(
          RegisterConfiguration::RestrictGeneralRegisters(registers));
      config = restricted_config.get();
    }
    if (!AllocateRegisters(config, call_descriptor, run_verifier)) return false;
    // Verify the instruction sequence has the same hash in two stages.
    VerifyGeneratedCodeIsIdempotent();
    RUN_MAYBE_ABORT(FrameElisionPhase);
    // TODO(mtrofin): move this off to the register allocator.
    bool generate_frame_at_start =
        data_->sequence()->instruction_blocks().front()->must_construct_frame();
    // Optimimize jumps.
    if (v8_flags.turbo_jt) {
      RUN_MAYBE_ABORT(JumpThreadingPhase, generate_frame_at_start);
    }
    EndPhaseKind();
    return !info()->was_cancelled();
  }
References v8::internal::compiler::CallDescriptor::AllocatableRegisters(), v8::internal::RegListBase< RegisterT >::Count(), DCHECK_LT, v8::internal::RegisterConfiguration::Default(), v8::internal::compiler::CallDescriptor::HasRestrictedAllocatableRegisters(), v8::internal::RegisterConfiguration::RestrictGeneralRegisters(), RUN_MAYBE_ABORT, and v8::internal::v8_flags.
Referenced by GenerateCode().
AllocateRegisters() [2/2]
bool v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters (const RegisterConfiguration * config, CallDescriptor * call_descriptor, bool run_verifier)
Definition at line 29 of file pipelines.cc.
                                                    {
  // Don't track usage for this zone in compiler stats.
  std::unique_ptr<Zone> verifier_zone;
  RegisterAllocatorVerifier* verifier = nullptr;
  if (run_verifier) {
    AccountingAllocator* allocator = data()->allocator();
    DCHECK_NOT_NULL(allocator);
    verifier_zone.reset(
        new Zone(allocator, kRegisterAllocatorVerifierZoneName));
    verifier = verifier_zone->New<RegisterAllocatorVerifier>(
        verifier_zone.get(), config, data()->sequence(), data()->frame());
  }
#ifdef DEBUG
  data_->sequence()->ValidateEdgeSplitForm();
  data_->sequence()->ValidateDeferredBlockEntryPaths();
  data_->sequence()->ValidateDeferredBlockExitPaths();
#endif
  data_->InitializeRegisterComponent(config, call_descriptor);
  RUN_MAYBE_ABORT(MeetRegisterConstraintsPhase);
  RUN_MAYBE_ABORT(ResolvePhisPhase);
  RUN_MAYBE_ABORT(BuildLiveRangesPhase);
  RUN_MAYBE_ABORT(BuildLiveRangeBundlesPhase);
  TraceSequence("before register allocation");
  if (verifier != nullptr) {
    CHECK(!data_->register_allocation_data()->ExistsUseWithoutDefinition());
    CHECK(data_->register_allocation_data()
              ->RangesDefinedInDeferredStayInDeferred());
  }
  if (data_->info()->trace_turbo_json() && !MayHaveUnverifiableGraph()) {
    TurboCfgFile tcf(data_->isolate());
    tcf << AsC1VRegisterAllocationData("PreAllocation",
                                       data_->register_allocation_data());
  }
  RUN_MAYBE_ABORT(AllocateGeneralRegistersPhase<LinearScanAllocator>);
  if (data_->sequence()->HasFPVirtualRegisters()) {
    RUN_MAYBE_ABORT(AllocateFPRegistersPhase<LinearScanAllocator>);
  }
  if (data_->sequence()->HasSimd128VirtualRegisters() &&
      (kFPAliasing == AliasingKind::kIndependent)) {
    RUN_MAYBE_ABORT(AllocateSimd128RegistersPhase<LinearScanAllocator>);
  }
  RUN_MAYBE_ABORT(DecideSpillingModePhase);
  RUN_MAYBE_ABORT(AssignSpillSlotsPhase);
  RUN_MAYBE_ABORT(CommitAssignmentPhase);
  // TODO(chromium:725559): remove this check once
  // we understand the cause of the bug. We keep just the
  // check at the end of the allocation.
  if (verifier != nullptr) {
    verifier->VerifyAssignment("Immediately after CommitAssignmentPhase.");
  }
  RUN_MAYBE_ABORT(ConnectRangesPhase);
  RUN_MAYBE_ABORT(ResolveControlFlowPhase);
  RUN_MAYBE_ABORT(PopulateReferenceMapsPhase);
  if (v8_flags.turbo_move_optimization) {
    RUN_MAYBE_ABORT(OptimizeMovesPhase);
  }
  TraceSequence("after register allocation");
  if (verifier != nullptr) {
    verifier->VerifyAssignment("End of regalloc pipeline.");
    verifier->VerifyGapMoves();
  }
  if (data_->info()->trace_turbo_json() && !MayHaveUnverifiableGraph()) {
    TurboCfgFile tcf(data_->isolate());
    tcf << AsC1VRegisterAllocationData("CodeGen",
                                       data_->register_allocation_data());
  }
  data()->ClearRegisterComponent();
  return true;
}
References v8::internal::compiler::turboshaft::PipelineData::allocator(), CHECK, v8::internal::compiler::turboshaft::PipelineData::ClearRegisterComponent(), data(), data_, DCHECK_NOT_NULL, v8::internal::compiler::RegisterAllocationData::ExistsUseWithoutDefinition(), v8::internal::compiler::turboshaft::PipelineData::frame(), v8::internal::compiler::InstructionSequence::HasFPVirtualRegisters(), v8::internal::compiler::InstructionSequence::HasSimd128VirtualRegisters(), v8::internal::compiler::turboshaft::PipelineData::info(), v8::internal::compiler::turboshaft::PipelineData::InitializeRegisterComponent(), v8::internal::compiler::turboshaft::PipelineData::isolate(), v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::compiler::kRegisterAllocatorVerifierZoneName, MayHaveUnverifiableGraph(), v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred(), v8::internal::compiler::turboshaft::PipelineData::register_allocation_data(), RUN_MAYBE_ABORT, v8::internal::compiler::turboshaft::PipelineData::sequence(), TraceSequence(), v8::internal::v8_flags, v8::internal::compiler::InstructionSequence::ValidateDeferredBlockEntryPaths(), v8::internal::compiler::InstructionSequence::ValidateDeferredBlockExitPaths(), v8::internal::compiler::InstructionSequence::ValidateEdgeSplitForm(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
AssembleCode()
V8_WARN_UNUSED_RESULT bool v8::internal::compiler::turboshaft::Pipeline::AssembleCode (Linkage * linkage) [inline]
Definition at line 403 of file pipelines.h.
                                                            {
    BeginPhaseKind("V8.TFCodeGeneration");
    data()->InitializeCodeGenerator(linkage);
    UnparkedScopeIfNeeded unparked_scope(data()->broker());
    RUN_MAYBE_ABORT(AssembleCodePhase);
    if (info()->trace_turbo_json()) {
      TurboJsonFile json_of(info(), std::ios_base::app);
      json_of
          << "{\"name\":\"code generation\"" << ", \"type\":\"instructions\""
          << InstructionStartsAsJSON{&data()->code_generator()->instr_starts()}
          << TurbolizerCodeOffsetsInfoAsJSON{
                 &data()->code_generator()->offsets_info()};
      json_of << "},\n";
    }
    data()->ClearInstructionComponent();
    EndPhaseKind();
    return !info()->was_cancelled();
  }
References broker(), v8::internal::compiler::InstructionStartsAsJSON::instr_starts, v8::internal::compiler::TurbolizerCodeOffsetsInfoAsJSON::offsets_info, and RUN_MAYBE_ABORT.
Referenced by GenerateCode().
BeginPhaseKind()
void v8::internal::compiler::turboshaft::Pipeline::BeginPhaseKind (const char * phase_kind_name) [inline]
Definition at line 56 of file pipelines.h.
                                                   {
    if (auto statistics = data()->pipeline_statistics()) {
      statistics->BeginPhaseKind(phase_kind_name);
    }
  }
CommitDependencies()
bool v8::internal::compiler::turboshaft::Pipeline::CommitDependencies (Handle< Code > code) [inline]
Definition at line 508 of file pipelines.h.
                                             {
    return data_->depedencies() == nullptr ||
           data_->depedencies()->Commit(code);
  }
References code.
Referenced by v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting().
CreateGraphFromTurbofan()
bool v8::internal::compiler::turboshaft::Pipeline::CreateGraphFromTurbofan (compiler::TFPipelineData * turbofan_data, Linkage * linkage) [inline]
Definition at line 154 of file pipelines.h.
                                                 {
    CHECK_IMPLIES(!v8_flags.disable_optimizing_compilers, v8_flags.turboshaft);
    UnparkedScopeIfNeeded scope(data_->broker(),
                                v8_flags.turboshaft_trace_reduction ||
                                    v8_flags.turboshaft_trace_emitted);
    turboshaft::Tracing::Scope tracing_scope(data_->info());
    if (std::optional<BailoutReason> bailout =
            Run<turboshaft::BuildGraphPhase>(turbofan_data, linkage)) {
      info()->AbortOptimization(*bailout);
      return false;
    }
    return true;
  }
References CHECK_IMPLIES, and v8::internal::v8_flags.
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
CreateGraphWithMaglev()
bool v8::internal::compiler::turboshaft::Pipeline::CreateGraphWithMaglev (Linkage * linkage) [inline]
Definition at line 137 of file pipelines.h.
                                               {
    UnparkedScopeIfNeeded unparked_scope(data_->broker());
    BeginPhaseKind("V8.TFGraphCreation");
    turboshaft::Tracing::Scope tracing_scope(data_->info());
    std::optional<BailoutReason> bailout =
        Run<turboshaft::TurbolevGraphBuildingPhase>(linkage);
    EndPhaseKind();
    if (bailout.has_value()) {
      data_->info()->AbortOptimization(bailout.value());
      return false;
    }
    return true;
  }
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
data()
PipelineData* v8::internal::compiler::turboshaft::Pipeline::data () const [inline]
Definition at line 55 of file pipelines.h.
{ return data_; }
Referenced by AllocateRegisters(), GenerateCode(), and v8::internal::compiler::turboshaft::BuiltinPipeline::OptimizeBuiltin().
EndPhaseKind()
void v8::internal::compiler::turboshaft::Pipeline::EndPhaseKind () [inline]
Definition at line 61 of file pipelines.h.
                      {
    if (auto statistics = data()->pipeline_statistics()) {
      statistics->EndPhaseKind();
    }
  }
FinalizeCode()
MaybeIndirectHandle<Code> v8::internal::compiler::turboshaft::Pipeline::FinalizeCode (bool retire_broker = true) [inline]
Definition at line 443 of file pipelines.h.
                                                                    {
    BeginPhaseKind("V8.TFFinalizeCode");
    if (data_->broker() && retire_broker) {
      data_->broker()->Retire();
    }
    RUN_MAYBE_ABORT(FinalizeCodePhase);
    MaybeIndirectHandle<Code> maybe_code = data_->code();
    IndirectHandle<Code> code;
    if (!maybe_code.ToHandle(&code)) {
      return maybe_code;
    }
    data_->info()->SetCode(code);
    PrintCode(data_->isolate(), code, data_->info());
    // Functions with many inline candidates are sensitive to correct call
    // frequency feedback and should therefore not be tiered up early.
    if (v8_flags.profile_guided_optimization &&
        info()->could_not_inline_all_candidates() &&
        info()->shared_info()->cached_tiering_decision() !=
            CachedTieringDecision::kDelayMaglev) {
      info()->shared_info()->set_cached_tiering_decision(
          CachedTieringDecision::kNormal);
    }
    if (info()->trace_turbo_json()) {
      TurboJsonFile json_of(info(), std::ios_base::app);
      json_of << "{\"name\":\"disassembly\",\"type\":\"disassembly\""
              << BlockStartsAsJSON{&data_->code_generator()->block_starts()}
              << "\"data\":\"";
#ifdef ENABLE_DISASSEMBLER
      std::stringstream disassembly_stream;
      code->Disassemble(nullptr, disassembly_stream, data_->isolate());
      std::string disassembly_string(disassembly_stream.str());
      for (const auto& c : disassembly_string) {
        json_of << AsEscapedUC16ForJSON(c);
      }
#endif // ENABLE_DISASSEMBLER
      json_of << "\"}\n],\n";
      json_of << "\"nodePositions\":";
      // TODO(nicohartmann): We should try to always provide source positions.
      json_of << (data_->source_position_output().empty()
                      ? "{}"
                      : data_->source_position_output())
              << ",\n";
      JsonPrintAllSourceWithPositions(json_of, data_->info(), data_->isolate());
      if (info()->has_bytecode_array()) {
        json_of << ",\n";
        JsonPrintAllBytecodeSources(json_of, info(), data_->isolate());
      }
      json_of << "\n}";
    }
    if (info()->trace_turbo_json() || info()->trace_turbo_graph()) {
      CodeTracer::StreamScope tracing_scope(data_->GetCodeTracer());
      tracing_scope.stream()
          << "---------------------------------------------------\n"
          << "Finished compiling method " << info()->GetDebugName().get()
          << " using TurboFan" << std::endl;
    }
    EndPhaseKind();
    return code;
  }
References v8::internal::compiler::BlockStartsAsJSON::block_starts, code, v8::internal::compiler::JsonPrintAllBytecodeSources(), v8::internal::compiler::JsonPrintAllSourceWithPositions(), v8::internal::kDelayMaglev, v8::internal::kNormal, v8::internal::compiler::PrintCode(), RUN_MAYBE_ABORT, v8::internal::CodeTracer::StreamScope::stream(), v8::internal::string, v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::FinalizeCode(), v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin().
GenerateCode() [1/2]
MaybeHandle<Code> v8::internal::compiler::turboshaft::Pipeline::GenerateCode (CallDescriptor * call_descriptor) [inline]
Definition at line 425 of file pipelines.h.
                                                                  {
    Linkage linkage(call_descriptor);
    if (!PrepareForInstructionSelection()) return {};
    if (!SelectInstructions(&linkage)) {
      return MaybeHandle<Code>();
    }
    if (!AllocateRegisters(linkage.GetIncomingDescriptor())) return {};
    if (!AssembleCode(&linkage)) return {};
    return FinalizeCode();
  }
References v8::internal::compiler::Linkage::GetIncomingDescriptor().
Referenced by v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), and v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting().
GenerateCode() [2/2]
bool v8::internal::compiler::turboshaft::Pipeline::GenerateCode (Linkage * linkage, std::shared_ptr< OsrHelper > osr_helper = {}, JumpOptimizationInfo * jump_optimization_info = nullptr, const ProfileDataFromFile * profile = nullptr, int initial_graph_hash = 0)
Definition at line 119 of file pipelines.cc.
                                                                {
  // Run code generation. If we optimize jumps, we repeat this a second time.
  data()->InitializeCodegenComponent(osr_helper, jump_optimization_info);
  // Perform instruction selection and register allocation.
  if (!PrepareForInstructionSelection(profile)) return false;
  if (!SelectInstructions(linkage)) return false;
  if (!AllocateRegisters(linkage->GetIncomingDescriptor())) return false;
  if (!AssembleCode(linkage)) return false;
  if (v8_flags.turbo_profiling) {
    info()->profiler_data()->SetHash(initial_graph_hash);
  }
  if (jump_optimization_info && jump_optimization_info->is_optimizable()) {
    // Reset data for a second run of instruction selection.
    data()->ClearCodegenComponent();
    jump_optimization_info->set_optimizing();
    // Perform instruction selection and register allocation.
    data()->InitializeCodegenComponent(osr_helper, jump_optimization_info);
    if (!SelectInstructions(linkage)) {
      return false;
    }
    if (!AllocateRegisters(linkage->GetIncomingDescriptor())) return false;
    // Generate the final machine code.
    if (!AssembleCode(linkage)) return false;
  }
  return true;
}
References AllocateRegisters(), AssembleCode(), v8::internal::compiler::turboshaft::PipelineData::ClearCodegenComponent(), data(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), info(), v8::internal::compiler::turboshaft::PipelineData::InitializeCodegenComponent(), v8::internal::JumpOptimizationInfo::is_optimizable(), PrepareForInstructionSelection(), v8::internal::OptimizedCompilationInfo::profiler_data(), SelectInstructions(), v8::internal::JumpOptimizationInfo::set_optimizing(), v8::internal::BasicBlockProfilerData::SetHash(), and v8::internal::v8_flags.
info()
OptimizedCompilationInfo* v8::internal::compiler::turboshaft::Pipeline::info () [inline]
Definition at line 441 of file pipelines.h.
{ return data_->info(); }
Referenced by GenerateCode(), and v8::internal::compiler::turboshaft::BuiltinPipeline::OptimizeBuiltin().
MayHaveUnverifiableGraph()
bool v8::internal::compiler::turboshaft::Pipeline::MayHaveUnverifiableGraph () const [inline]
Definition at line 371 of file pipelines.h.
                                        {
    // TODO(nicohartmann): Are there any graph which are still verifiable?
    return true;
  }
Referenced by AllocateRegisters().
OptimizeTurboshaftGraph()
bool v8::internal::compiler::turboshaft::Pipeline::OptimizeTurboshaftGraph (Linkage * linkage) [inline]
Definition at line 173 of file pipelines.h.
                                                 {
    UnparkedScopeIfNeeded scope(data_->broker(),
                                v8_flags.turboshaft_trace_reduction ||
                                    v8_flags.turboshaft_trace_emitted);
    turboshaft::Tracing::Scope tracing_scope(data_->info());
    BeginPhaseKind("V8.TurboshaftOptimize");
#ifdef V8_ENABLE_WEBASSEMBLY
    // TODO(dlehmann,353475584): Once the Wasm-in-JS TS inlining MVP is feature-
    // complete and cleaned-up, move its reducer into the beginning of the
    // `MachineLoweringPhase` since we can reuse the `DataViewLoweringReducer`
    // there and avoid a separate phase.
    if (v8_flags.turboshaft_wasm_in_js_inlining) {
      RUN_MAYBE_ABORT(turboshaft::WasmInJSInliningPhase);
    }
#endif // !V8_ENABLE_WEBASSEMBLY
    RUN_MAYBE_ABORT(turboshaft::MachineLoweringPhase);
    if (v8_flags.turboshaft_loop_unrolling) {
      RUN_MAYBE_ABORT(turboshaft::LoopUnrollingPhase);
    }
    if (v8_flags.turbo_store_elimination) {
      RUN_MAYBE_ABORT(turboshaft::StoreStoreEliminationPhase);
    }
    RUN_MAYBE_ABORT(turboshaft::OptimizePhase);
    if (v8_flags.turboshaft_typed_optimizations) {
      RUN_MAYBE_ABORT(turboshaft::TypedOptimizationsPhase);
    }
    if (v8_flags.turboshaft_assert_types) {
      RUN_MAYBE_ABORT(turboshaft::TypeAssertionsPhase);
    }
    // Perform dead code elimination, reduce stack checks, simplify loads on
    // platforms where required, ...
    RUN_MAYBE_ABORT(turboshaft::CodeEliminationAndSimplificationPhase);
#ifdef V8_ENABLE_DEBUG_CODE
    if (V8_UNLIKELY(v8_flags.turboshaft_enable_debug_features)) {
      // This phase has to run very late to allow all previous phases to use
      // debug features.
      RUN_MAYBE_ABORT(turboshaft::DebugFeatureLoweringPhase);
    }
#endif // V8_ENABLE_DEBUG_CODE
    return true;
  }
References RUN_MAYBE_ABORT, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
PrepareForInstructionSelection()
V8_WARN_UNUSED_RESULT bool v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection (const ProfileDataFromFile * profile = nullptr) [inline]
Definition at line 232 of file pipelines.h.
                                                    {
    if (V8_UNLIKELY(data()->pipeline_kind() == TurboshaftPipelineKind::kCSA ||
                    data()->pipeline_kind() ==
                        TurboshaftPipelineKind::kTSABuiltin)) {
      if (profile) {
        RUN_MAYBE_ABORT(ProfileApplicationPhase, profile);
      }
      if (v8_flags.reorder_builtins &&
          Builtins::IsBuiltinId(info()->builtin())) {
        UnparkedScopeIfNeeded unparked_scope(data()->broker());
        BasicBlockCallGraphProfiler::StoreCallGraph(info(), data()->graph());
      }
      if (v8_flags.turbo_profiling) {
        UnparkedScopeIfNeeded unparked_scope(data()->broker());
        // Basic block profiling disables concurrent compilation, so handle
        // deref is fine.
        AllowHandleDereference allow_handle_dereference;
        const size_t block_count = data()->graph().block_count();
        BasicBlockProfilerData* profiler_data =
            BasicBlockProfiler::Get()->NewData(block_count);
        // Set the function name.
        profiler_data->SetFunctionName(info()->GetDebugName());
        // Capture the schedule string before instrumentation.
        if (v8_flags.turbo_profiling_verbose) {
          std::ostringstream os;
          os << data()->graph();
          profiler_data->SetSchedule(os);
        }
        info()->set_profiler_data(profiler_data);
        RUN_MAYBE_ABORT(BlockInstrumentationPhase);
      } else {
        // We run an empty copying phase to make sure that we have the same
        // control flow as when taking the profile.
        ZoneWithName<kTempZoneName> temp_zone(data()->zone_stats(),
                                              kTempZoneName);
        CopyingPhase<>::Run(data(), temp_zone);
      }
    }
    // DecompressionOptimization has to run as the last phase because it
    // constructs an (slightly) invalid graph that mixes Tagged and Compressed
    // representations.
    RUN_MAYBE_ABORT(DecompressionOptimizationPhase);
    return Run<SpecialRPOSchedulingPhase>();
  }
References broker(), v8::internal::BasicBlockProfiler::Get(), v8::internal::compiler::GetDebugName(), graph(), v8::internal::Builtins::IsBuiltinId(), v8::internal::compiler::turboshaft::kCSA, v8::internal::compiler::turboshaft::kTempZoneName, v8::internal::compiler::turboshaft::kTSABuiltin, v8::internal::BasicBlockProfiler::NewData(), v8::internal::compiler::turboshaft::CopyingPhase< Reducers >::Run(), RUN_MAYBE_ABORT, v8::internal::BasicBlockProfilerData::SetFunctionName(), v8::internal::BasicBlockProfilerData::SetSchedule(), v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by GenerateCode().
PrintGraph()
void v8::internal::compiler::turboshaft::Pipeline::PrintGraph (Zone * zone, const char * phase_name) [inline]
Definition at line 102 of file pipelines.h.
                                                      {
    CodeTracer* code_tracer = nullptr;
    if (data_->info()->trace_turbo_graph()) {
      // NOTE: We must not call `GetCodeTracer` if tracing is not enabled,
      // because it may not yet be initialized then and doing so from the
      // background thread is not threadsafe.
      code_tracer = data_->GetCodeTracer();
      DCHECK_NOT_NULL(code_tracer);
    }
    PrintTurboshaftGraph(data_, zone, code_tracer, phase_name);
  }
References DCHECK_NOT_NULL, and v8::internal::compiler::turboshaft::PrintTurboshaftGraph().
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin().
Run()
template<TurboshaftPhase Phase, typename... Args>
V8_WARN_UNUSED_RESULT auto v8::internal::compiler::turboshaft::Pipeline::Run (Args &&... args) [inline]
Definition at line 68 of file pipelines.h.
                                                 {
    // Setup run scope.
    PhaseScope phase_scope(data_->pipeline_statistics(), Phase::phase_name());
    ZoneWithName<Phase::kPhaseName> temp_zone(data_->zone_stats(),
                                              Phase::phase_name());
    NodeOriginTable::PhaseScope origin_scope(data_->node_origins(),
                                             Phase::phase_name());
#ifdef V8_RUNTIME_CALL_STATS
    RuntimeCallTimerScope runtime_call_timer_scope(data_->runtime_call_stats(),
                                                   Phase::kRuntimeCallCounterId,
                                                   Phase::kCounterMode);
#endif
    Phase phase;
    using result_t =
        decltype(phase.Run(data_, temp_zone, std::forward<Args>(args)...));
    if constexpr (std::is_same_v<result_t, void>) {
      phase.Run(data_, temp_zone, std::forward<Args>(args)...);
      if constexpr (produces_printable_graph<Phase>::value) {
        PrintGraph(temp_zone, Phase::phase_name());
      }
      return !data_->info()->was_cancelled();
    } else {
      static_assert(std::is_same_v<result_t, std::optional<BailoutReason>>);
      auto result = phase.Run(data_, temp_zone, std::forward<Args>(args)...);
      if constexpr (produces_printable_graph<Phase>::value) {
        PrintGraph(temp_zone, Phase::phase_name());
      }
      return data_->info()->was_cancelled() ? BailoutReason::kCancelled
                                            : result;
    }
    UNREACHABLE();
  }
References v8::base::args, v8::internal::maglev::PrintGraph(), v8::base::internal::result, and v8::internal::UNREACHABLE().
RunSimplificationAndNormalizationPhase()
V8_WARN_UNUSED_RESULT bool v8::internal::compiler::turboshaft::Pipeline::RunSimplificationAndNormalizationPhase () [inline]
Definition at line 227 of file pipelines.h.
                                                                      {
    RUN_MAYBE_ABORT(SimplificationAndNormalizationPhase);
    return true;
  }
References RUN_MAYBE_ABORT.
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting().
SelectInstructions()
bool v8::internal::compiler::turboshaft::Pipeline::SelectInstructions (Linkage * linkage) [inline]
Definition at line 286 of file pipelines.h.
                                                          {
    auto call_descriptor = linkage->GetIncomingDescriptor();
    // Depending on which code path led us to this function, the frame may or
    // may not have been initialized. If it hasn't yet, initialize it now.
    if (!data_->frame()) {
      data_->InitializeFrameData(call_descriptor);
    }
    // Select and schedule instructions covering the scheduled graph.
    CodeTracer* code_tracer = nullptr;
    if (info()->trace_turbo_graph()) {
      // NOTE: We must not call `GetCodeTracer` if tracing is not enabled,
      // because it may not yet be initialized then and doing so from the
      // background thread is not threadsafe.
      code_tracer = data_->GetCodeTracer();
    }
    if (std::optional<BailoutReason> bailout = Run<InstructionSelectionPhase>(
            call_descriptor, linkage, code_tracer)) {
      data_->info()->AbortOptimization(*bailout);
      EndPhaseKind();
      return false;
    }
    return true;
    // TODO(nicohartmann@): We might need to provide this.
    // if (info()->trace_turbo_json()) {
    // UnparkedScopeIfNeeded scope(turbofan_data->broker());
    // AllowHandleDereference allow_deref;
    // TurboCfgFile tcf(isolate());
    // tcf << AsC1V("CodeGen", turbofan_data->schedule(),
    // turbofan_data->source_positions(),
    // turbofan_data->sequence());
    // std::ostringstream source_position_output;
    // // Output source position information before the graph is deleted.
    // if (data_->source_positions() != nullptr) {
    // data_->source_positions()->PrintJson(source_position_output);
    // } else {
    // source_position_output << "{}";
    // }
    // source_position_output << ",\n\"nodeOrigins\" : ";
    // data_->node_origins()->PrintJson(source_position_output);
    // data_->set_source_position_output(source_position_output.str());
    // }
  }
References v8::internal::compiler::Linkage::GetIncomingDescriptor().
Referenced by GenerateCode().
TraceSequence()
void v8::internal::compiler::turboshaft::Pipeline::TraceSequence (const char * phase_name) [inline]
Definition at line 114 of file pipelines.h.
                                             {
    if (info()->trace_turbo_json()) {
      UnparkedScopeIfNeeded scope(data()->broker());
      AllowHandleDereference allow_deref;
      TurboJsonFile json_of(info(), std::ios_base::app);
      json_of
          << "{\"name\":\"" << phase_name << "\",\"type\":\"sequence\""
          << ",\"blocks\":" << InstructionSequenceAsJSON{data()->sequence()}
          << ",\"register_allocation\":{"
          << RegisterAllocationDataAsJSON{*(data()->register_allocation_data()),
                                          *(data()->sequence())}
          << "}},\n";
    }
    if (info()->trace_turbo_graph()) {
      UnparkedScopeIfNeeded scope(data()->broker());
      AllowHandleDereference allow_deref;
      CodeTracer::StreamScope tracing_scope(data()->GetCodeTracer());
      tracing_scope.stream()
          << "----- Instruction sequence " << phase_name << " -----\n"
          << *data()->sequence();
    }
  }
References broker(), and v8::internal::CodeTracer::StreamScope::stream().
Referenced by AllocateRegisters().
VerifyGeneratedCodeIsIdempotent()
void v8::internal::compiler::turboshaft::Pipeline::VerifyGeneratedCodeIsIdempotent () [inline]
Definition at line 376 of file pipelines.h.
                                         {
    JumpOptimizationInfo* jump_opt = data()->jump_optimization_info();
    if (jump_opt == nullptr) return;
    InstructionSequence* code = data()->sequence();
    int instruction_blocks = code->InstructionBlockCount();
    int virtual_registers = code->VirtualRegisterCount();
    size_t hash_code =
        base::hash_combine(instruction_blocks, virtual_registers);
    for (Instruction* instr : *code) {
      hash_code = base::hash_combine(hash_code, instr->opcode(),
                                     instr->InputCount(), instr->OutputCount());
    }
    for (int i = 0; i < virtual_registers; i++) {
      hash_code = base::hash_combine(hash_code, code->GetRepresentation(i));
    }
    if (jump_opt->is_collecting()) {
      jump_opt->hash_code = hash_code;
    } else {
      CHECK_EQ(hash_code, jump_opt->hash_code);
    }
  }
References CHECK_EQ, code, v8::internal::JumpOptimizationInfo::hash_code, v8::base::hash_combine(), and v8::internal::JumpOptimizationInfo::is_collecting().
Member Data Documentation
data_
PipelineData* v8::internal::compiler::turboshaft::Pipeline::data_ [private]
Definition at line 518 of file pipelines.h.
Referenced by AllocateRegisters().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/pipelines.h
/mnt/V8SourceCode/src/compiler/turboshaft/pipelines.cc