v8::internal::ScannerStream Class Reference
#include <scanner-character-streams.h>
Static Public Member Functions
static Utf16CharacterStream * For (Isolate *isolate, Handle< String > data)
static Utf16CharacterStream * For (Isolate *isolate, Handle< String > data, int start_pos, int end_pos)
static Utf16CharacterStream * For (ScriptCompiler::ExternalSourceStream *source_stream, ScriptCompiler::StreamedSource::Encoding encoding)
static std::unique_ptr< Utf16CharacterStream > ForTesting (const char *data)
static std::unique_ptr< Utf16CharacterStream > ForTesting (const char *data, size_t length)
static std::unique_ptr< Utf16CharacterStream > ForTesting (const uint16_t *data, size_t length)
Detailed Description
Definition at line 19 of file scanner-character-streams.h.
Member Function Documentation
For() [1/3]
Utf16CharacterStream * v8::internal::ScannerStream::For (Isolate * isolate, Handle< String > data) [static]
Definition at line 866 of file scanner-character-streams.cc.
                                                              {
  return ScannerStream::For(isolate, data, 0, data->length());
}
Referenced by v8::internal::parsing::ParseFunction(), and v8::internal::parsing::ParseProgram().
For() [2/3]
Utf16CharacterStream * v8::internal::ScannerStream::For (Isolate * isolate, Handle< String > data, int start_pos, int end_pos) [static]
Definition at line 871 of file scanner-character-streams.cc.
                                                                     {
  CHECK_GE(start_pos, 0);
  CHECK_LE(start_pos, end_pos);
  CHECK_LE(end_pos, data->length());
  size_t start_offset = 0;
  if (IsSlicedString(*data)) {
    Tagged<SlicedString> string = Cast<SlicedString>(*data);
    start_offset = string->offset();
    Tagged<String> parent = string->parent();
    if (IsThinString(parent)) parent = Cast<ThinString>(parent)->actual();
    data = handle(parent, isolate);
  } else {
    data = String::Flatten(isolate, data);
  }
  if (IsExternalOneByteString(*data)) {
    return new BufferedCharacterStream<ExternalStringStream>(
        static_cast<size_t>(start_pos), Cast<ExternalOneByteString>(*data),
        start_offset, static_cast<size_t>(end_pos));
  } else if (IsExternalTwoByteString(*data)) {
    return new UnbufferedCharacterStream<ExternalStringStream>(
        static_cast<size_t>(start_pos), Cast<ExternalTwoByteString>(*data),
        start_offset, static_cast<size_t>(end_pos));
  } else if (IsSeqOneByteString(*data)) {
    return new BufferedCharacterStream<OnHeapStream>(
        static_cast<size_t>(start_pos), Cast<SeqOneByteString>(data),
        start_offset, static_cast<size_t>(end_pos));
  } else if (IsSeqTwoByteString(*data)) {
    return new RelocatingCharacterStream(
        isolate, static_cast<size_t>(start_pos), Cast<SeqTwoByteString>(data),
        start_offset, static_cast<size_t>(end_pos));
  } else {
    UNREACHABLE();
  }
}
References CHECK_GE, CHECK_LE, v8::internal::handle(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::InstanceTypeChecker::IsThinString(), and v8::internal::UNREACHABLE().
For() [3/3]
Utf16CharacterStream * v8::internal::ScannerStream::For (ScriptCompiler::ExternalSourceStream * source_stream, ScriptCompiler::StreamedSource::Encoding encoding) [static]
Definition at line 945 of file scanner-character-streams.cc.
                                                     {
  switch (encoding) {
    case v8::ScriptCompiler::StreamedSource::TWO_BYTE:
      return new UnbufferedCharacterStream<ChunkedStream>(
          static_cast<size_t>(0), source_stream);
    case v8::ScriptCompiler::StreamedSource::ONE_BYTE:
      return new BufferedCharacterStream<ChunkedStream>(static_cast<size_t>(0),
                                                        source_stream);
    case v8::ScriptCompiler::StreamedSource::WINDOWS_1252:
      return new Windows1252CharacterStream(static_cast<size_t>(0),
                                            source_stream);
    case v8::ScriptCompiler::StreamedSource::UTF8:
      return new Utf8ExternalStreamingStream(source_stream);
  }
  UNREACHABLE();
}
References v8::ScriptCompiler::StreamedSource::ONE_BYTE, v8::ScriptCompiler::StreamedSource::TWO_BYTE, v8::internal::UNREACHABLE(), v8::ScriptCompiler::StreamedSource::UTF8, and v8::ScriptCompiler::StreamedSource::WINDOWS_1252.
ForTesting() [1/3]
std::unique_ptr< Utf16CharacterStream > v8::internal::ScannerStream::ForTesting (const char * data) [static]
Definition at line 907 of file scanner-character-streams.cc.
                      {
  return ScannerStream::ForTesting(data, strlen(data));
}
ForTesting() [2/3]
std::unique_ptr< Utf16CharacterStream > v8::internal::ScannerStream::ForTesting (const char * data, size_t length) [static]
Definition at line 912 of file scanner-character-streams.cc.
                                     {
  if (data == nullptr) {
    DCHECK_EQ(length, 0);
    // We don't want to pass in a null pointer into the the character stream,
    // because then the one-past-the-end pointer is undefined, so instead pass
    // through this static array.
    static const char non_null_empty_string[1] = {0};
    data = non_null_empty_string;
  }
  return std::unique_ptr<Utf16CharacterStream>(
      new BufferedCharacterStream<TestingStream>(
          0, reinterpret_cast<const uint8_t*>(data), length));
}
References DCHECK_EQ, and v8::internal::length.
ForTesting() [3/3]
std::unique_ptr< Utf16CharacterStream > v8::internal::ScannerStream::ForTesting (const uint16_t * data, size_t length) [static]
Definition at line 929 of file scanner-character-streams.cc.
                                         {
  if (data == nullptr) {
    DCHECK_EQ(length, 0);
    // We don't want to pass in a null pointer into the the character stream,
    // because then the one-past-the-end pointer is undefined, so instead pass
    // through this static array.
    static const uint16_t non_null_empty_uint16_t_string[1] = {0};
    data = non_null_empty_uint16_t_string;
  }
  return std::unique_ptr<Utf16CharacterStream>(
      new UnbufferedCharacterStream<TestingStream>(0, data, length));
}
References DCHECK_EQ, and v8::internal::length.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/scanner-character-streams.h
/mnt/V8SourceCode/src/parsing/scanner-character-streams.cc