v8::internal::interpreter::BytecodeRegisterAllocator Class Reference
#include <bytecode-register-allocator.h>
Classes
class Observer
Public Member Functions
BytecodeRegisterAllocator (int start_index)
~BytecodeRegisterAllocator ()=default
BytecodeRegisterAllocator (const BytecodeRegisterAllocator &)=delete
BytecodeRegisterAllocator & operator= (const BytecodeRegisterAllocator &)=delete
Register NewRegister ()
RegisterList NewRegisterList (int count)
RegisterList NewGrowableRegisterList ()
Register GrowRegisterList (RegisterList *reg_list)
void ReleaseRegisters (int register_index)
void ReleaseRegister (Register reg)
bool RegisterIsLive (Register reg) const
RegisterList AllLiveRegisters () const
void set_observer (Observer *observer)
int next_register_index () const
int maximum_register_count () const
Private Attributes
int next_register_index_
int max_register_count_
Observer * observer_
Detailed Description
Definition at line 15 of file bytecode-register-allocator.h.
Constructor & Destructor Documentation
BytecodeRegisterAllocator() [1/2]
v8::internal::interpreter::BytecodeRegisterAllocator::BytecodeRegisterAllocator (int start_index) [inline], [explicit]
Definition at line 27 of file bytecode-register-allocator.h.
      : next_register_index_(start_index),
        max_register_count_(start_index),
        observer_(nullptr) {}
 BytecodeRegisterAllocator()
v8::internal::interpreter::BytecodeRegisterAllocator::~BytecodeRegisterAllocator () [default]
BytecodeRegisterAllocator() [2/2]
v8::internal::interpreter::BytecodeRegisterAllocator::BytecodeRegisterAllocator (const BytecodeRegisterAllocator &) [delete]
Member Function Documentation
AllLiveRegisters()
RegisterList v8::internal::interpreter::BytecodeRegisterAllocator::AllLiveRegisters () const [inline]
Definition at line 102 of file bytecode-register-allocator.h.
                                        {
    return RegisterList(0, next_register_index());
  }
References next_register_index().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildSuspendPoint().
GrowRegisterList()
Register v8::internal::interpreter::BytecodeRegisterAllocator::GrowRegisterList (RegisterList * reg_list) [inline]
Definition at line 68 of file bytecode-register-allocator.h.
                                                    {
    Register reg(NewRegister());
    reg_list->IncrementRegisterCount();
    // If the following CHECK fails then a register was allocated (and not
    // freed) between the creation of the RegisterList and this call to add a
    // Register.
    CHECK_EQ(reg.index(), reg_list->last_register().index());
    return reg;
  }
References CHECK_EQ, v8::internal::interpreter::RegisterList::IncrementRegisterCount(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::RegisterList::last_register(), and NewRegister().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildPushUndefinedIntoRegisterList(), v8::internal::interpreter::BytecodeGenerator::VisitAndPushIntoRegisterList(), and v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
maximum_register_count()
int v8::internal::interpreter::BytecodeRegisterAllocator::maximum_register_count () const [inline]
Definition at line 109 of file bytecode-register-allocator.h.
{ return max_register_count_; }
References max_register_count_.
NewGrowableRegisterList()
RegisterList v8::internal::interpreter::BytecodeRegisterAllocator::NewGrowableRegisterList () [inline]
Definition at line 58 of file bytecode-register-allocator.h.
                                         {
    RegisterList reg_list(next_register_index_, 0);
    return reg_list;
  }
References next_register_index_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
NewRegister()
Register v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister () [inline]
Definition at line 37 of file bytecode-register-allocator.h.
                         {
    Register reg(next_register_index_++);
    max_register_count_ = std::max(next_register_index_, max_register_count_);
    if (observer_) {
      observer_->RegisterAllocateEvent(reg);
    }
    return reg;
  }
References max_register_count_, next_register_index_, observer_, and v8::internal::interpreter::BytecodeRegisterAllocator::Observer::RegisterAllocateEvent().
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateTopLevelRegisters(), v8::internal::interpreter::BytecodeGenerator::BuildAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGetIterator(), v8::internal::interpreter::BytecodeGenerator::BuildGetIteratorRecord(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), v8::internal::interpreter::BytecodeGenerator::BuildLiteralStrictCompareBoolean(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalCatchContext(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalWithContext(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateGetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateSetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildReturn(), v8::internal::interpreter::BytecodeGenerator::BuildSetNamedProperty(), v8::internal::interpreter::BytecodeGenerator::BuildStoreGlobal(), v8::internal::interpreter::BytecodeGenerator::BuildTryCatch(), v8::internal::interpreter::BytecodeGenerator::BuildTryFinally(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::DisposablesStackScope(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody(), GrowRegisterList(), v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::MultipleEntryBlockContextScope(), v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression(), v8::internal::interpreter::BytecodeGenerator::VisitCallSuper(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitForRegisterValue(), v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports(), v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression().
NewRegisterList()
RegisterList v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList (int count) [inline]
Definition at line 47 of file bytecode-register-allocator.h.
                                          {
    RegisterList reg_list(next_register_index_, count);
    next_register_index_ += count;
    max_register_count_ = std::max(next_register_index_, max_register_count_);
    if (observer_) {
      observer_->RegisterListAllocateEvent(reg_list);
    }
    return reg_list;
  }
References max_register_count_, next_register_index_, observer_, and v8::internal::interpreter::BytecodeRegisterAllocator::Observer::RegisterListAllocateEvent().
Referenced by v8::internal::interpreter::BytecodeGenerator::AddDisposableValue(), v8::internal::interpreter::BytecodeGenerator::BuildAsyncReturn(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicGet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicSet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateGetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateSetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildSuperCallOptimization(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody(), v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), and v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad().
next_register_index()
int v8::internal::interpreter::BytecodeRegisterAllocator::next_register_index () const [inline]
Definition at line 108 of file bytecode-register-allocator.h.
{ return next_register_index_; }
References next_register_index_.
Referenced by AllLiveRegisters().
operator=()
BytecodeRegisterAllocator& v8::internal::interpreter::BytecodeRegisterAllocator::operator= (const BytecodeRegisterAllocator &) [delete]
RegisterIsLive()
bool v8::internal::interpreter::BytecodeRegisterAllocator::RegisterIsLive (Register reg) const [inline]
Definition at line 97 of file bytecode-register-allocator.h.
                                          {
    return reg.index() < next_register_index_;
  }
References v8::internal::interpreter::Register::index(), and next_register_index_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::RegisterIsValid().
ReleaseRegister()
void v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegister (Register reg) [inline]
Definition at line 88 of file bytecode-register-allocator.h.
                                     {
    DCHECK_EQ(next_register_index_ - 1, reg.index());
    if (observer_) {
      observer_->RegisterFreeEvent(reg);
    }
    next_register_index_--;
  }
References DCHECK_EQ, v8::internal::interpreter::Register::index(), next_register_index_, observer_, and v8::internal::interpreter::BytecodeRegisterAllocator::Observer::RegisterFreeEvent().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalCatchContext(), and v8::internal::interpreter::BytecodeGenerator::BuildNewLocalWithContext().
ReleaseRegisters()
void v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegisters (int register_index) [inline]
Definition at line 79 of file bytecode-register-allocator.h.
                                            {
    int count = next_register_index_ - register_index;
    next_register_index_ = register_index;
    if (observer_) {
      observer_->RegisterListFreeEvent(RegisterList(register_index, count));
    }
  }
References next_register_index_, observer_, and v8::internal::interpreter::BytecodeRegisterAllocator::Observer::RegisterListFreeEvent().
set_observer()
void v8::internal::interpreter::BytecodeRegisterAllocator::set_observer (Observer * observer) [inline]
Definition at line 106 of file bytecode-register-allocator.h.
{ observer_ = observer; }
References observer_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeRegisterOptimizer().
Member Data Documentation
max_register_count_
int v8::internal::interpreter::BytecodeRegisterAllocator::max_register_count_ [private]
Definition at line 113 of file bytecode-register-allocator.h.
Referenced by maximum_register_count(), NewRegister(), and NewRegisterList().
next_register_index_
int v8::internal::interpreter::BytecodeRegisterAllocator::next_register_index_ [private]
Definition at line 112 of file bytecode-register-allocator.h.
Referenced by NewGrowableRegisterList(), NewRegister(), NewRegisterList(), next_register_index(), RegisterIsLive(), ReleaseRegister(), and ReleaseRegisters().
observer_
Observer* v8::internal::interpreter::BytecodeRegisterAllocator::observer_ [private]
Definition at line 114 of file bytecode-register-allocator.h.
Referenced by NewRegister(), NewRegisterList(), ReleaseRegister(), ReleaseRegisters(), and set_observer().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-register-allocator.h