v8::internal::PagePool Class Reference
#include <page-pool.h>
Classes
class LargePagePoolImpl
class PoolImpl
class ReleasePooledChunksTask
class ReleasePooledLargeChunksTask
Public Member Functions
PagePool ()=default
~PagePool ()
PagePool (const PagePool &)=delete
PagePool & operator= (const PagePool &)=delete
void Add (Isolate *isolate, MutablePageMetadata *chunk)
MutablePageMetadata * Remove (Isolate *isolate)
void AddLarge (Isolate *isolate, std::vector< LargePageMetadata * > &pages)
LargePageMetadata * RemoveLarge (Isolate *isolate, size_t chunk_size)
void AddZoneReservation (Isolate *isolate, VirtualMemory zone_reservation)
std::optional< VirtualMemory > RemoveZoneReservation (Isolate *isolate)
void ReleaseOnTearDown (Isolate *isolate)
V8_EXPORT_PRIVATE void ReleaseImmediately (Isolate *isolate)
void ReleaseLargeImmediately ()
void TearDown ()
void GarbageCollectionPrologue (Isolate *isolate, GarbageCollector collector)
size_t GetCount (Isolate *isolate) const
size_t GetSharedCount () const
size_t GetTotalCount () const
Private Types
using InternalTime = size_t
using PageMemory = std::unique_ptr< MutablePageMetadata, std::function< void(MutablePageMetadata *)> >
using LargePageMemory = std::unique_ptr< LargePageMetadata, std::function< void(LargePageMetadata *)> >
Private Member Functions
void ReleaseUpTo (Isolate *isolate_for_printing, InternalTime release_time)
Private Attributes
PoolImpl< PageMemory > page_pool_
PoolImpl< VirtualMemory > zone_pool_
LargePagePoolImpl large_pool_
std::atomic< InternalTime > next_time_ {1}
Detailed Description
Definition at line 20 of file page-pool.h.
Member Typedef Documentation
InternalTime
using v8::internal::PagePool::InternalTime = size_t [private]
Definition at line 22 of file page-pool.h.
LargePageMemory
using v8::internal::PagePool::LargePageMemory = std::unique_ptr<LargePageMetadata, std::function<void(LargePageMetadata*)> > [private]
Definition at line 84 of file page-pool.h.
PageMemory
using v8::internal::PagePool::PageMemory = std::unique_ptr<MutablePageMetadata, std::function<void(MutablePageMetadata*)> > [private]
Definition at line 81 of file page-pool.h.
Constructor & Destructor Documentation
PagePool() [1/2]
v8::internal::PagePool::PagePool () [default]
 PagePool()
v8::internal::PagePool::~PagePool () [default]
PagePool() [2/2]
v8::internal::PagePool::PagePool (const PagePool &) [delete]
Member Function Documentation
Add()
void v8::internal::PagePool::Add (Isolate * isolate, MutablePageMetadata * chunk)
Definition at line 360 of file page-pool.cc.
                                                               {
  DCHECK_NOT_NULL(isolate);
  // This method is called only on the main thread and only during the
  // atomic pause so a lock is not needed.
  DCHECK_NOT_NULL(chunk);
  DCHECK_EQ(chunk->size(), PageMetadata::kPageSize);
  DCHECK(!chunk->Chunk()->IsLargePage());
  DCHECK(!chunk->Chunk()->IsTrusted());
  DCHECK_NE(chunk->Chunk()->executable(), EXECUTABLE);
  // Ensure that ReleaseAllAllocatedMemory() was called on the page.
  DCHECK(!chunk->ContainsAnySlots());
  page_pool_.PutLocal(isolate,
                      PageMemory(chunk, [](MutablePageMetadata* metadata) {
                        MemoryAllocator::DeleteMemoryChunk(metadata);
                      }));
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::ContainsAnySlots(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::MemoryAllocator::DeleteMemoryChunk(), v8::internal::EXECUTABLE, v8::internal::MemoryChunk::executable(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::MemoryChunk::IsTrusted(), v8::internal::MutablePageMetadata::kPageSize, page_pool_, v8::internal::PagePool::PoolImpl< PoolEntry >::PutLocal(), and v8::internal::MemoryChunkMetadata::size().
Referenced by v8::internal::MemoryAllocator::Free().
AddLarge()
void v8::internal::PagePool::AddLarge (Isolate * isolate, std::vector< LargePageMetadata * > & pages)
Definition at line 405 of file page-pool.cc.
                                                              {
  const InternalTime time = next_time_.fetch_add(1, std::memory_order_relaxed);
  const bool added_to_pool = large_pool_.Add(pages, time);
  const int timeout = v8_flags.large_page_pool_timeout;
  if (added_to_pool && timeout > 0) {
    const base::TimeDelta large_page_release_task_delay =
        base::TimeDelta::FromSeconds(timeout);
    auto task =
        std::make_unique<ReleasePooledLargeChunksTask>(isolate, this, time);
    V8::GetCurrentPlatform()->PostDelayedTaskOnWorkerThread(
        TaskPriority::kBestEffort, std::move(task),
        large_page_release_task_delay.InSecondsF());
  }
}
References v8::internal::PagePool::LargePagePoolImpl::Add(), v8::base::TimeDelta::FromSeconds(), v8::internal::V8::GetCurrentPlatform(), v8::base::TimeDelta::InSecondsF(), v8::kBestEffort, large_pool_, next_time_, v8::Platform::PostDelayedTaskOnWorkerThread(), v8::internal::time, and v8::internal::v8_flags.
Referenced by v8::internal::MemoryAllocator::FreeLargePagesPooled().
AddZoneReservation()
void v8::internal::PagePool::AddZoneReservation (Isolate * isolate, VirtualMemory zone_reservation)
Definition at line 425 of file page-pool.cc.
                                                                  {
  DCHECK_NOT_NULL(isolate);
  zone_pool_.PutLocal(isolate, std::move(zone_reservation));
}
References DCHECK_NOT_NULL, and zone_pool_.
Referenced by v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::ReturnSegment().
GarbageCollectionPrologue()
void v8::internal::PagePool::GarbageCollectionPrologue (Isolate * isolate, GarbageCollector collector)
GetCount()
size_t v8::internal::PagePool::GetCount (Isolate * isolate) const
Definition at line 352 of file page-pool.cc.
                                                {
  return page_pool_.LocalSize(isolate);
}
References v8::internal::PagePool::PoolImpl< PoolEntry >::LocalSize(), and page_pool_.
Referenced by v8::internal::MemoryAllocator::GetPooledChunksCount().
GetSharedCount()
size_t v8::internal::PagePool::GetSharedCount () const
Definition at line 356 of file page-pool.cc.
{ return page_pool_.SharedSize(); }
References page_pool_, and v8::internal::PagePool::PoolImpl< PoolEntry >::SharedSize().
Referenced by v8::internal::MemoryAllocator::GetSharedPooledChunksCount().
GetTotalCount()
size_t v8::internal::PagePool::GetTotalCount () const
Definition at line 358 of file page-pool.cc.
{ return page_pool_.Size(); }
References page_pool_, and v8::internal::PagePool::PoolImpl< PoolEntry >::Size().
Referenced by v8::internal::MemoryAllocator::GetTotalPooledChunksCount().
operator=()
PagePool& v8::internal::PagePool::operator= (const PagePool &) [delete]
ReleaseImmediately()
void v8::internal::PagePool::ReleaseImmediately (Isolate * isolate)
Definition at line 327 of file page-pool.cc.
                                                  {
  page_pool_.ReleaseLocal(isolate);
  zone_pool_.ReleaseLocal(isolate);
  large_pool_.ReleaseAll();
}
References large_pool_, page_pool_, v8::internal::PagePool::LargePagePoolImpl::ReleaseAll(), v8::internal::PagePool::PoolImpl< PoolEntry >::ReleaseLocal(), and zone_pool_.
Referenced by v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure(), and v8::internal::MemoryAllocator::ReleasePooledChunksImmediately().
ReleaseLargeImmediately()
void v8::internal::PagePool::ReleaseLargeImmediately ()
Definition at line 333 of file page-pool.cc.
{ large_pool_.ReleaseAll(); }
References large_pool_, and v8::internal::PagePool::LargePagePoolImpl::ReleaseAll().
Referenced by v8::internal::Heap::GarbageCollectionPrologueInSafepoint().
ReleaseOnTearDown()
void v8::internal::PagePool::ReleaseOnTearDown (Isolate * isolate)
Definition at line 296 of file page-pool.cc.
                                                 {
  const InternalTime time = next_time_.fetch_add(1, std::memory_order_relaxed);
  const bool shared_page_pool_populate =
      page_pool_.MoveLocalToShared(isolate, time);
  const bool shared_zone_pool_populated =
      zone_pool_.MoveLocalToShared(isolate, time);
  // Always post task when there are pages in the shared pool.
  if (shared_page_pool_populate || shared_zone_pool_populated) {
    auto schedule_task = [this, isolate, time](Isolate* target_isolate) {
      DCHECK_NE(isolate, target_isolate);
      USE(isolate);
      static constexpr base::TimeDelta kReleaseTaskDelayInSeconds =
          base::TimeDelta::FromSeconds(8);
      target_isolate->task_runner()->PostDelayedTask(
          std::make_unique<ReleasePooledChunksTask>(target_isolate, this, time),
          kReleaseTaskDelayInSeconds.InSecondsF());
    };
    if (!isolate->isolate_group()->FindAnotherIsolateLocked(isolate,
                                                            schedule_task)) {
      // No other isolate could be found. Release pooled pages right away.
      page_pool_.ReleaseShared();
      zone_pool_.ReleaseShared();
    }
  }
  large_pool_.ReleaseAll();
}
References DCHECK_NE, v8::internal::IsolateGroup::FindAnotherIsolateLocked(), v8::base::TimeDelta::FromSeconds(), v8::internal::Isolate::isolate_group(), large_pool_, v8::internal::PagePool::PoolImpl< PoolEntry >::MoveLocalToShared(), next_time_, page_pool_, v8::internal::PagePool::LargePagePoolImpl::ReleaseAll(), v8::internal::PagePool::PoolImpl< PoolEntry >::ReleaseShared(), v8::internal::time, USE, and zone_pool_.
Referenced by v8::internal::Heap::TearDown().
ReleaseUpTo()
void v8::internal::PagePool::ReleaseUpTo (Isolate * isolate_for_printing, InternalTime release_time) [private]
Definition at line 341 of file page-pool.cc.
                                                      {
  const auto pages_removed = page_pool_.ReleaseUpTo(release_time);
  const auto zone_reservations_removed = zone_pool_.ReleaseUpTo(release_time);
  if (v8_flags.trace_gc_nvp) {
    isolate_for_printing->PrintWithTimestamp(
        "Shared pool: Removed pages: %zu removed zone reservations: %zu\n",
        pages_removed, zone_reservations_removed);
  }
}
References page_pool_, v8::internal::PagePool::PoolImpl< PoolEntry >::ReleaseUpTo(), v8::internal::v8_flags, and zone_pool_.
Remove()
MutablePageMetadata * v8::internal::PagePool::Remove (Isolate * isolate)
Definition at line 377 of file page-pool.cc.
                                                      {
  DCHECK_NOT_NULL(isolate);
  auto result = page_pool_.Get(isolate);
  if (result) {
    return result.value().release();
  }
  return nullptr;
}
References DCHECK_NOT_NULL, v8::internal::PagePool::PoolImpl< PoolEntry >::Get(), page_pool_, and v8::base::internal::result.
Referenced by v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool().
RemoveLarge()
LargePageMetadata * v8::internal::PagePool::RemoveLarge (Isolate * isolate, size_t chunk_size)
Definition at line 421 of file page-pool.cc.
                                                                            {
  return large_pool_.Remove(chunk_size);
}
References large_pool_, and v8::internal::PagePool::LargePagePoolImpl::Remove().
Referenced by v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool().
RemoveZoneReservation()
std::optional< VirtualMemory > v8::internal::PagePool::RemoveZoneReservation (Isolate * isolate)
Definition at line 431 of file page-pool.cc.
                                                                           {
  DCHECK_NOT_NULL(isolate);
  return zone_pool_.Get(isolate);
}
References DCHECK_NOT_NULL, and zone_pool_.
Referenced by v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::GetOrCreateMemoryForSegment().
TearDown()
void v8::internal::PagePool::TearDown ()
Definition at line 335 of file page-pool.cc.
                        {
  page_pool_.TearDown();
  zone_pool_.TearDown();
  large_pool_.TearDown();
}
References large_pool_, page_pool_, v8::internal::PagePool::PoolImpl< PoolEntry >::TearDown(), v8::internal::PagePool::LargePagePoolImpl::TearDown(), and zone_pool_.
Member Data Documentation
large_pool_
LargePagePoolImpl v8::internal::PagePool::large_pool_ [private]
Definition at line 138 of file page-pool.h.
Referenced by AddLarge(), ReleaseImmediately(), ReleaseLargeImmediately(), ReleaseOnTearDown(), RemoveLarge(), and TearDown().
next_time_
std::atomic<InternalTime> v8::internal::PagePool::next_time_ {1} [private]
Definition at line 144 of file page-pool.h.
Referenced by AddLarge(), and ReleaseOnTearDown().
page_pool_
PoolImpl<PageMemory> v8::internal::PagePool::page_pool_ [private]
Definition at line 135 of file page-pool.h.
Referenced by Add(), GetCount(), GetSharedCount(), GetTotalCount(), ReleaseImmediately(), ReleaseOnTearDown(), ReleaseUpTo(), Remove(), and TearDown().
zone_pool_
PoolImpl<VirtualMemory> v8::internal::PagePool::zone_pool_ [private]
Definition at line 136 of file page-pool.h.
Referenced by AddZoneReservation(), ReleaseImmediately(), ReleaseOnTearDown(), ReleaseUpTo(), RemoveZoneReservation(), and TearDown().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/page-pool.h
/mnt/V8SourceCode/src/heap/page-pool.cc