v8::internal::compiler::LoopVariableOptimizer Class Reference
#include <loop-variable-optimizer.h>
Classes
struct Constraint
Public Member Functions
void Run ()
LoopVariableOptimizer (TFGraph *graph, CommonOperatorBuilder *common, Zone *zone)
const ZoneMap< int, InductionVariable * > & induction_variables ()
void ChangeToInductionVariablePhis ()
void ChangeToPhisAndInsertGuards ()
Private Types
using VariableLimits = FunctionalList< Constraint >
Private Member Functions
void VisitBackedge (Node *from, Node *loop)
void VisitNode (Node *node)
void VisitMerge (Node *node)
void VisitLoop (Node *node)
void VisitIf (Node *node, bool polarity)
void VisitStart (Node *node)
void VisitLoopExit (Node *node)
void VisitOtherControl (Node *node)
void AddCmpToLimits (VariableLimits *limits, Node *node, InductionVariable::ConstraintKind kind, bool polarity)
void TakeConditionsFromFirstControl (Node *node)
const InductionVariable * FindInductionVariable (Node *node)
InductionVariable * TryGetInductionVariable (Node *phi)
void DetectInductionVariables (Node *loop)
TFGraph * graph ()
CommonOperatorBuilder * common ()
Zone * zone ()
Private Attributes
const int kAssumedLoopEntryIndex = 0
const int kFirstBackedge = 1
TFGraph * graph_
CommonOperatorBuilder * common_
Zone * zone_
NodeAuxData< VariableLimits > limits_
NodeAuxData< bool > reduced_
ZoneMap< int, InductionVariable * > induction_vars_
Detailed Description
Definition at line 70 of file loop-variable-optimizer.h.
Member Typedef Documentation
VariableLimits
using v8::internal::compiler::LoopVariableOptimizer::VariableLimits = FunctionalList<Constraint> [private]
Definition at line 98 of file loop-variable-optimizer.h.
Constructor & Destructor Documentation
LoopVariableOptimizer()
v8::internal::compiler::LoopVariableOptimizer::LoopVariableOptimizer (TFGraph * graph, CommonOperatorBuilder * common, Zone * zone)
Definition at line 25 of file loop-variable-optimizer.cc.
    : graph_(graph),
      common_(common),
      zone_(zone),
      limits_(graph->NodeCount(), zone),
      reduced_(graph->NodeCount(), zone),
      induction_vars_(zone) {}
Member Function Documentation
AddCmpToLimits()
void v8::internal::compiler::LoopVariableOptimizer::AddCmpToLimits (VariableLimits * limits, Node * node, InductionVariable::ConstraintKind kind, bool polarity) [private]
Definition at line 182 of file loop-variable-optimizer.cc.
                   {
  Node* left = node->InputAt(0);
  Node* right = node->InputAt(1);
  if (FindInductionVariable(left) || FindInductionVariable(right)) {
    if (polarity) {
      limits->PushFront(Constraint{left, kind, right}, zone());
    } else {
      kind = (kind == InductionVariable::kStrict)
                 ? InductionVariable::kNonStrict
                 : InductionVariable::kStrict;
      limits->PushFront(Constraint{right, kind, left}, zone());
    }
  }
}
References FindInductionVariable(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::InductionVariable::kNonStrict, v8::internal::compiler::InductionVariable::kStrict, v8::internal::compiler::FunctionalList< A >::PushFront(), and zone().
Referenced by VisitIf().
ChangeToInductionVariablePhis()
void v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis ()
Definition at line 289 of file loop-variable-optimizer.cc.
                                                          {
  for (auto entry : induction_vars_) {
    // It only make sense to analyze the induction variables if
    // there is a bound.
    InductionVariable* induction_var = entry.second;
    DCHECK_EQ(MachineRepresentation::kTagged,
              PhiRepresentationOf(induction_var->phi()->op()));
    if (induction_var->upper_bounds().empty() &&
        induction_var->lower_bounds().empty()) {
      continue;
    }
    // Insert the increment value to the value inputs.
    induction_var->phi()->InsertInput(graph()->zone(),
                                      induction_var->phi()->InputCount() - 1,
                                      induction_var->increment());
    // Insert the bound inputs to the value inputs.
    for (auto bound : induction_var->lower_bounds()) {
      induction_var->phi()->InsertInput(
          graph()->zone(), induction_var->phi()->InputCount() - 1, bound.bound);
    }
    for (auto bound : induction_var->upper_bounds()) {
      induction_var->phi()->InsertInput(
          graph()->zone(), induction_var->phi()->InputCount() - 1, bound.bound);
    }
    NodeProperties::ChangeOp(
        induction_var->phi(),
        common()->InductionVariablePhi(induction_var->phi()->InputCount() - 1));
  }
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), DCHECK_EQ, graph(), v8::internal::compiler::InductionVariable::increment(), induction_vars_, v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::InsertInput(), v8::internal::kTagged, v8::internal::compiler::InductionVariable::lower_bounds(), v8::internal::compiler::Node::op(), v8::internal::compiler::InductionVariable::phi(), v8::internal::compiler::PhiRepresentationOf(), v8::internal::compiler::InductionVariable::upper_bounds(), and zone().
ChangeToPhisAndInsertGuards()
void v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards ()
Definition at line 319 of file loop-variable-optimizer.cc.
                                                        {
  for (auto entry : induction_vars_) {
    InductionVariable* induction_var = entry.second;
    if (induction_var->phi()->opcode() == IrOpcode::kInductionVariablePhi) {
      // Turn the induction variable phi back to normal phi.
      int value_count = 2;
      Node* control = NodeProperties::GetControlInput(induction_var->phi());
      DCHECK_EQ(value_count, control->op()->ControlInputCount());
      induction_var->phi()->TrimInputCount(value_count + 1);
      induction_var->phi()->ReplaceInput(value_count, control);
      NodeProperties::ChangeOp(
          induction_var->phi(),
          common()->Phi(MachineRepresentation::kTagged, value_count));
      // If the backedge is not a subtype of the phi's type, we insert a sigma
      // to get the typing right.
      Node* backedge_value = induction_var->phi()->InputAt(1);
      Type backedge_type = NodeProperties::GetType(backedge_value);
      Type phi_type = NodeProperties::GetType(induction_var->phi());
      if (!backedge_type.Is(phi_type)) {
        Node* loop = NodeProperties::GetControlInput(induction_var->phi());
        Node* backedge_control = loop->InputAt(1);
        Node* backedge_effect =
            NodeProperties::GetEffectInput(induction_var->effect_phi(), 1);
        Node* rename =
            graph()->NewNode(common()->TypeGuard(phi_type), backedge_value,
                             backedge_effect, backedge_control);
        induction_var->effect_phi()->ReplaceInput(1, rename);
        induction_var->phi()->ReplaceInput(1, rename);
      }
    }
  }
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, v8::internal::compiler::InductionVariable::effect_phi(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), graph(), induction_vars_, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Is(), v8::internal::kTagged, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::InductionVariable::phi(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::Node::TrimInputCount().
common()
CommonOperatorBuilder* v8::internal::compiler::LoopVariableOptimizer::common () [inline], [private]
Definition at line 118 of file loop-variable-optimizer.h.
{ return common_; }
References common_.
Referenced by ChangeToInductionVariablePhis(), and ChangeToPhisAndInsertGuards().
DetectInductionVariables()
void v8::internal::compiler::LoopVariableOptimizer::DetectInductionVariables (Node * loop) [private]
Definition at line 272 of file loop-variable-optimizer.cc.
                                                               {
  if (loop->op()->ControlInputCount() != 2) return;
  TRACE("Loop variables for loop %i:", loop->id());
  for (Edge edge : loop->use_edges()) {
    if (NodeProperties::IsControlEdge(edge) &&
        edge.from()->opcode() == IrOpcode::kPhi) {
      Node* phi = edge.from();
      InductionVariable* induction_var = TryGetInductionVariable(phi);
      if (induction_var) {
        induction_vars_[phi->id()] = induction_var;
        TRACE(" %i", induction_var->phi()->id());
      }
    }
  }
  TRACE("\n");
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Node::id(), induction_vars_, v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::Node::op(), v8::internal::compiler::InductionVariable::phi(), v8::internal::TRACE(), TryGetInductionVariable(), and v8::internal::compiler::Node::use_edges().
Referenced by VisitLoop().
FindInductionVariable()
const InductionVariable * v8::internal::compiler::LoopVariableOptimizer::FindInductionVariable (Node * node) [private]
Definition at line 214 of file loop-variable-optimizer.cc.
                {
  auto var = induction_vars_.find(node->id());
  if (var != induction_vars_.end()) {
    return var->second;
  }
  return nullptr;
}
References v8::internal::compiler::Node::id(), and induction_vars_.
Referenced by AddCmpToLimits().
graph()
TFGraph* v8::internal::compiler::LoopVariableOptimizer::graph () [inline], [private]
Definition at line 117 of file loop-variable-optimizer.h.
{ return graph_; }
References graph_.
Referenced by ChangeToInductionVariablePhis(), ChangeToPhisAndInsertGuards(), and Run().
induction_variables()
const ZoneMap<int, InductionVariable*>& v8::internal::compiler::LoopVariableOptimizer::induction_variables () [inline]
Definition at line 77 of file loop-variable-optimizer.h.
                                                                {
    return induction_vars_;
  }
References induction_vars_.
Run()
void v8::internal::compiler::LoopVariableOptimizer::Run ()
Definition at line 35 of file loop-variable-optimizer.cc.
                                {
  ZoneQueue<Node*> queue(zone());
  queue.push(graph()->start());
  NodeMarker<bool> queued(graph(), 2);
  while (!queue.empty()) {
    Node* node = queue.front();
    queue.pop();
    queued.Set(node, false);
    DCHECK(!reduced_.Get(node));
    bool all_inputs_visited = true;
    int inputs_end = (node->opcode() == IrOpcode::kLoop)
                         ? kFirstBackedge
                         : node->op()->ControlInputCount();
    for (int i = 0; i < inputs_end; i++) {
      if (!reduced_.Get(NodeProperties::GetControlInput(node, i))) {
        all_inputs_visited = false;
        break;
      }
    }
    if (!all_inputs_visited) continue;
    VisitNode(node);
    reduced_.Set(node, true);
    // Queue control outputs.
    for (Edge edge : node->use_edges()) {
      if (NodeProperties::IsControlEdge(edge) &&
          edge.from()->op()->ControlOutputCount() > 0) {
        Node* use = edge.from();
        if (use->opcode() == IrOpcode::kLoop &&
            edge.index() != kAssumedLoopEntryIndex) {
          VisitBackedge(node, use);
        } else if (!queued.Get(use)) {
          queue.push(use);
          queued.Set(use, true);
        }
      }
    }
  }
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::DCHECK(), v8::internal::compiler::NodeMarker< State >::Get(), v8::internal::compiler::NodeAuxData< T, def >::Get(), v8::internal::compiler::NodeProperties::GetControlInput(), graph(), v8::internal::compiler::NodeProperties::IsControlEdge(), kAssumedLoopEntryIndex, kFirstBackedge, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), reduced_, v8::internal::compiler::NodeMarker< State >::Set(), v8::internal::compiler::NodeAuxData< T, def >::Set(), use(), v8::internal::compiler::Node::use_edges(), VisitBackedge(), VisitNode(), and zone().
Referenced by v8::internal::compiler::TyperPhase::Run().
TakeConditionsFromFirstControl()
void v8::internal::compiler::LoopVariableOptimizer::TakeConditionsFromFirstControl (Node * node) [private]
Definition at line 210 of file loop-variable-optimizer.cc.
                                                                     {
  limits_.Set(node, limits_.Get(NodeProperties::GetControlInput(node, 0)));
}
References v8::internal::compiler::NodeProperties::GetControlInput(), and limits_.
Referenced by VisitLoop(), VisitLoopExit(), and VisitOtherControl().
TryGetInductionVariable()
InductionVariable * v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable (Node * phi) [private]
Definition at line 223 of file loop-variable-optimizer.cc.
                                                                           {
  DCHECK_EQ(2, phi->op()->ValueInputCount());
  Node* loop = NodeProperties::GetControlInput(phi);
  DCHECK_EQ(IrOpcode::kLoop, loop->opcode());
  Node* initial = phi->InputAt(0);
  Node* arith = phi->InputAt(1);
  InductionVariable::ArithmeticType arithmeticType;
  if (arith->opcode() == IrOpcode::kJSAdd ||
      arith->opcode() == IrOpcode::kNumberAdd ||
      arith->opcode() == IrOpcode::kSpeculativeNumberAdd ||
      arith->opcode() == IrOpcode::kSpeculativeAdditiveSafeIntegerAdd ||
      arith->opcode() == IrOpcode::kSpeculativeAdditiveSafeIntegerSubtract ||
      arith->opcode() == IrOpcode::kSpeculativeSmallIntegerAdd) {
    arithmeticType = InductionVariable::ArithmeticType::kAddition;
  } else if (arith->opcode() == IrOpcode::kJSSubtract ||
             arith->opcode() == IrOpcode::kNumberSubtract ||
             arith->opcode() == IrOpcode::kSpeculativeNumberSubtract ||
             arith->opcode() == IrOpcode::kSpeculativeSmallIntegerSubtract) {
    arithmeticType = InductionVariable::ArithmeticType::kSubtraction;
  } else {
    return nullptr;
  }
  // We allow a few additional conversions on the lhs of the arithmetic
  // operation. This needs to be kept in sync with the corresponding code in
  // {Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint}.
  // TODO(jarin) Support both sides.
  Node* input = arith->InputAt(0);
  if (input->opcode() == IrOpcode::kSpeculativeToNumber ||
      input->opcode() == IrOpcode::kJSToNumber ||
      input->opcode() == IrOpcode::kJSToNumberConvertBigInt) {
    input = input->InputAt(0);
  }
  if (input != phi) return nullptr;
  Node* effect_phi = nullptr;
  for (Node* use : loop->uses()) {
    if (use->opcode() == IrOpcode::kEffectPhi) {
      DCHECK_NULL(effect_phi);
      effect_phi = use;
    }
  }
  if (!effect_phi) return nullptr;
  Node* incr = arith->InputAt(1);
  return zone()->New<InductionVariable>(phi, effect_phi, arith, incr, initial,
                                        zone(), arithmeticType);
}
References DCHECK_EQ, DCHECK_NULL, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::InputAt(), v8::internal::Zone::New(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), use(), v8::internal::compiler::Node::uses(), v8::internal::compiler::Operator::ValueInputCount(), and zone().
Referenced by DetectInductionVariables().
VisitBackedge()
void v8::internal::compiler::LoopVariableOptimizer::VisitBackedge (Node * from, Node * loop) [private]
Definition at line 97 of file loop-variable-optimizer.cc.
                                                                {
  if (loop->op()->ControlInputCount() != 2) return;
  // Go through the constraints, and update the induction variables in
  // this loop if they are involved in the constraint.
  for (Constraint constraint : limits_.Get(from)) {
    if (constraint.left->opcode() == IrOpcode::kPhi &&
        NodeProperties::GetControlInput(constraint.left) == loop) {
      auto var = induction_vars_.find(constraint.left->id());
      if (var != induction_vars_.end()) {
        var->second->AddUpperBound(constraint.right, constraint.kind);
      }
    }
    if (constraint.right->opcode() == IrOpcode::kPhi &&
        NodeProperties::GetControlInput(constraint.right) == loop) {
      auto var = induction_vars_.find(constraint.right->id());
      if (var != induction_vars_.end()) {
        var->second->AddLowerBound(constraint.left, constraint.kind);
      }
    }
  }
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), induction_vars_, limits_, and v8::internal::compiler::Node::op().
Referenced by Run().
VisitIf()
void v8::internal::compiler::LoopVariableOptimizer::VisitIf (Node * node, bool polarity) [private]
Definition at line 154 of file loop-variable-optimizer.cc.
                                                             {
  Node* branch = node->InputAt(0);
  Node* cond = branch->InputAt(0);
  VariableLimits limits = limits_.Get(branch);
  // Normalize to less than comparison.
  switch (cond->opcode()) {
    case IrOpcode::kJSLessThan:
    case IrOpcode::kNumberLessThan:
    case IrOpcode::kSpeculativeNumberLessThan:
      AddCmpToLimits(&limits, cond, InductionVariable::kStrict, polarity);
      break;
    case IrOpcode::kJSGreaterThan:
      AddCmpToLimits(&limits, cond, InductionVariable::kNonStrict, !polarity);
      break;
    case IrOpcode::kJSLessThanOrEqual:
    case IrOpcode::kNumberLessThanOrEqual:
    case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      AddCmpToLimits(&limits, cond, InductionVariable::kNonStrict, polarity);
      break;
    case IrOpcode::kJSGreaterThanOrEqual:
      AddCmpToLimits(&limits, cond, InductionVariable::kStrict, !polarity);
      break;
    default:
      break;
  }
  limits_.Set(node, limits);
}
References AddCmpToLimits(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::InductionVariable::kNonStrict, v8::internal::compiler::InductionVariable::kStrict, limits_, and v8::internal::compiler::Node::opcode().
Referenced by VisitNode().
VisitLoop()
void v8::internal::compiler::LoopVariableOptimizer::VisitLoop (Node * node) [private]
Definition at line 148 of file loop-variable-optimizer.cc.
                                                {
  DetectInductionVariables(node);
  // Conservatively take the limits from the loop entry here.
  return TakeConditionsFromFirstControl(node);
}
References DetectInductionVariables(), and TakeConditionsFromFirstControl().
Referenced by VisitNode().
VisitLoopExit()
void v8::internal::compiler::LoopVariableOptimizer::VisitLoopExit (Node * node) [private]
Definition at line 201 of file loop-variable-optimizer.cc.
                                                    {
  return TakeConditionsFromFirstControl(node);
}
References TakeConditionsFromFirstControl().
Referenced by VisitNode().
VisitMerge()
void v8::internal::compiler::LoopVariableOptimizer::VisitMerge (Node * node) [private]
Definition at line 139 of file loop-variable-optimizer.cc.
                                                 {
  // Merge the limits of all incoming edges.
  VariableLimits merged = limits_.Get(node->InputAt(0));
  for (int i = 1; i < node->InputCount(); i++) {
    merged.ResetToCommonAncestor(limits_.Get(node->InputAt(i)));
  }
  limits_.Set(node, merged);
}
References v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), limits_, and v8::internal::compiler::FunctionalList< A >::ResetToCommonAncestor().
Referenced by VisitNode().
VisitNode()
void v8::internal::compiler::LoopVariableOptimizer::VisitNode (Node * node) [private]
Definition at line 120 of file loop-variable-optimizer.cc.
                                                {
  switch (node->opcode()) {
    case IrOpcode::kMerge:
      return VisitMerge(node);
    case IrOpcode::kLoop:
      return VisitLoop(node);
    case IrOpcode::kIfFalse:
      return VisitIf(node, false);
    case IrOpcode::kIfTrue:
      return VisitIf(node, true);
    case IrOpcode::kStart:
      return VisitStart(node);
    case IrOpcode::kLoopExit:
      return VisitLoopExit(node);
    default:
      return VisitOtherControl(node);
  }
}
References v8::kStart, v8::internal::compiler::Node::opcode(), VisitIf(), VisitLoop(), VisitLoopExit(), VisitMerge(), VisitOtherControl(), and VisitStart().
Referenced by Run().
VisitOtherControl()
void v8::internal::compiler::LoopVariableOptimizer::VisitOtherControl (Node * node) [private]
Definition at line 205 of file loop-variable-optimizer.cc.
                                                        {
  DCHECK_EQ(1, node->op()->ControlInputCount());
  return TakeConditionsFromFirstControl(node);
}
References v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, v8::internal::compiler::Node::op(), and TakeConditionsFromFirstControl().
Referenced by VisitNode().
VisitStart()
void v8::internal::compiler::LoopVariableOptimizer::VisitStart (Node * node) [private]
Definition at line 199 of file loop-variable-optimizer.cc.
{ limits_.Set(node, {}); }
References limits_.
Referenced by VisitNode().
zone()
Zone* v8::internal::compiler::LoopVariableOptimizer::zone () [inline], [private]
Definition at line 119 of file loop-variable-optimizer.h.
{ return zone_; }
References zone_.
Referenced by AddCmpToLimits(), ChangeToInductionVariablePhis(), Run(), and TryGetInductionVariable().
Member Data Documentation
common_
CommonOperatorBuilder* v8::internal::compiler::LoopVariableOptimizer::common_ [private]
Definition at line 122 of file loop-variable-optimizer.h.
Referenced by common().
graph_
TFGraph* v8::internal::compiler::LoopVariableOptimizer::graph_ [private]
Definition at line 121 of file loop-variable-optimizer.h.
Referenced by graph().
induction_vars_
ZoneMap<int, InductionVariable*> v8::internal::compiler::LoopVariableOptimizer::induction_vars_ [private]
Definition at line 127 of file loop-variable-optimizer.h.
Referenced by ChangeToInductionVariablePhis(), ChangeToPhisAndInsertGuards(), DetectInductionVariables(), FindInductionVariable(), induction_variables(), and VisitBackedge().
kAssumedLoopEntryIndex
const int v8::internal::compiler::LoopVariableOptimizer::kAssumedLoopEntryIndex = 0 [private]
Definition at line 85 of file loop-variable-optimizer.h.
Referenced by Run().
kFirstBackedge
const int v8::internal::compiler::LoopVariableOptimizer::kFirstBackedge = 1 [private]
Definition at line 86 of file loop-variable-optimizer.h.
Referenced by Run().
limits_
NodeAuxData<VariableLimits> v8::internal::compiler::LoopVariableOptimizer::limits_ [private]
Definition at line 124 of file loop-variable-optimizer.h.
Referenced by TakeConditionsFromFirstControl(), VisitBackedge(), VisitIf(), VisitMerge(), and VisitStart().
reduced_
NodeAuxData<bool> v8::internal::compiler::LoopVariableOptimizer::reduced_ [private]
Definition at line 125 of file loop-variable-optimizer.h.
Referenced by Run().
zone_
Zone* v8::internal::compiler::LoopVariableOptimizer::zone_ [private]
Definition at line 123 of file loop-variable-optimizer.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/loop-variable-optimizer.h
/mnt/V8SourceCode/src/compiler/loop-variable-optimizer.cc