v8::internal::StringTableInsertionKey Class Reference
#include <deserializer.h>
Public Member Functions
StringTableInsertionKey (Isolate *isolate, DirectHandle< String > string, DeserializingUserCodeOption deserializing_user_code)
StringTableInsertionKey (LocalIsolate *isolate, DirectHandle< String > string, DeserializingUserCodeOption deserializing_user_code)
template<typename IsolateT >
bool IsMatch (IsolateT *isolate, Tagged< String > string)
void PrepareForInsertion (Isolate *isolate)
void PrepareForInsertion (LocalIsolate *isolate)
V8_WARN_UNUSED_RESULT DirectHandle< String > GetHandleForInsertion (Isolate *isolate)
Private Attributes
DirectHandle< String > string_
Additional Inherited Members
Detailed Description
Definition at line 362 of file deserializer.h.
Constructor & Destructor Documentation
StringTableInsertionKey() [1/2]
v8::internal::StringTableInsertionKey::StringTableInsertionKey (Isolate * isolate, DirectHandle< String > string, DeserializingUserCodeOption deserializing_user_code) [explicit]
Definition at line 452 of file deserializer.cc.
    : StringTableKey(ComputeRawHashField(isolate, *string), string->length()),
      string_(string) {
#ifdef DEBUG
  deserializing_user_code_ = deserializing_user_code;
#endif
  DCHECK(IsInternalizedString(*string));
}
References v8::internal::DCHECK(), and v8::internal::InstanceTypeChecker::IsInternalizedString().
StringTableInsertionKey() [2/2]
v8::internal::StringTableInsertionKey::StringTableInsertionKey (LocalIsolate * isolate, DirectHandle< String > string, DeserializingUserCodeOption deserializing_user_code) [explicit]
Definition at line 463 of file deserializer.cc.
    : StringTableKey(ComputeRawHashField(isolate, *string), string->length()),
      string_(string) {
#ifdef DEBUG
  deserializing_user_code_ = deserializing_user_code;
#endif
  DCHECK(IsInternalizedString(*string));
}
References v8::internal::DCHECK(), and v8::internal::InstanceTypeChecker::IsInternalizedString().
Member Function Documentation
GetHandleForInsertion()
V8_WARN_UNUSED_RESULT DirectHandle<String> v8::internal::StringTableInsertionKey::GetHandleForInsertion (Isolate * isolate) [inline]
Definition at line 382 of file deserializer.h.
                        {
    return string_;
  }
References string_.
IsMatch()
template<typename IsolateT >
template bool v8::internal::StringTableInsertionKey::IsMatch (IsolateT * isolate, Tagged< String > string)
Definition at line 475 of file deserializer.cc.
                                                             {
  // We want to compare the content of two strings here.
  return string_->SlowEquals(string, SharedStringAccessGuardIfNeeded(isolate));
}
References string_.
PrepareForInsertion() [1/2]
void v8::internal::StringTableInsertionKey::PrepareForInsertion (Isolate * isolate) [inline]
Definition at line 374 of file deserializer.h.
                                             {
    // When sharing the string table, all string table lookups during snapshot
    // deserialization are hits.
    DCHECK(isolate->OwnsStringTables() ||
           deserializing_user_code_ ==
               DeserializingUserCodeOption::kIsDeserializingUserCode);
  }
References v8::internal::DCHECK(), v8::internal::kIsDeserializingUserCode, and v8::internal::Isolate::OwnsStringTables().
PrepareForInsertion() [2/2]
void v8::internal::StringTableInsertionKey::PrepareForInsertion (LocalIsolate * isolate) [inline]
Definition at line 381 of file deserializer.h.
{}
Member Data Documentation
string_
DirectHandle<String> v8::internal::StringTableInsertionKey::string_ [private]
Definition at line 388 of file deserializer.h.
Referenced by GetHandleForInsertion(), and IsMatch().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/deserializer.h
/mnt/V8SourceCode/src/snapshot/deserializer.cc