v8::internal::RegisterConfiguration Class Reference
#include <register-configuration.h>
Public Member Functions
RegisterConfiguration (AliasingKind fp_aliasing_kind, int num_general_registers, int num_double_registers, int num_simd128_registers, int num_simd256_registers, int num_allocatable_general_registers, int num_allocatable_double_registers, int num_allocatable_simd128_registers, int num_allocatable_simd256_registers, const int *allocatable_general_codes, const int *allocatable_double_codes, const int *independent_allocatable_simd128_codes=nullptr)
int num_general_registers () const
int num_float_registers () const
int num_double_registers () const
int num_simd128_registers () const
int num_simd256_registers () const
int num_allocatable_general_registers () const
int num_allocatable_float_registers () const
int num_allocatable_double_registers () const
int num_allocatable_simd128_registers () const
int num_allocatable_simd256_registers () const
AliasingKind fp_aliasing_kind () const
int32_t allocatable_general_codes_mask () const
int32_t allocatable_double_codes_mask () const
int32_t allocatable_float_codes_mask () const
int32_t allocatable_simd128_codes_mask () const
int GetAllocatableGeneralCode (int index) const
bool IsAllocatableGeneralCode (int index) const
int GetAllocatableFloatCode (int index) const
bool IsAllocatableFloatCode (int index) const
int GetAllocatableDoubleCode (int index) const
bool IsAllocatableDoubleCode (int index) const
int GetAllocatableSimd128Code (int index) const
bool IsAllocatableSimd128Code (int index) const
int GetAllocatableSimd256Code (int index) const
bool IsAllocatableSimd256Code (int index) const
const int * allocatable_general_codes () const
const int * allocatable_float_codes () const
const int * allocatable_double_codes () const
const int * allocatable_simd128_codes () const
const int * allocatable_simd256_codes () const
int GetAliases (MachineRepresentation rep, int index, MachineRepresentation other_rep, int *alias_base_index) const
bool AreAliases (MachineRepresentation rep, int index, MachineRepresentation other_rep, int other_index) const
virtual ~RegisterConfiguration ()=default
Static Public Member Functions
static const RegisterConfiguration * Default ()
static const RegisterConfiguration * Poisoning ()
static const RegisterConfiguration * RestrictGeneralRegisters (RegList registers)
Static Public Attributes
static constexpr int kMaxGeneralRegisters = 32
static constexpr int kMaxFPRegisters = 32
static constexpr int kMaxRegisters
Private Attributes
const int num_general_registers_
int num_float_registers_
const int num_double_registers_
int num_simd128_registers_
int num_simd256_registers_
int num_allocatable_general_registers_
int num_allocatable_float_registers_
int num_allocatable_double_registers_
int num_allocatable_simd128_registers_
int num_allocatable_simd256_registers_
int32_t allocatable_general_codes_mask_
int32_t allocatable_float_codes_mask_
int32_t allocatable_double_codes_mask_
int32_t allocatable_simd128_codes_mask_
int32_t allocatable_simd256_codes_mask_
const int * allocatable_general_codes_
int allocatable_float_codes_ [kMaxFPRegisters]
const int * allocatable_double_codes_
int allocatable_simd128_codes_ [kMaxFPRegisters]
int allocatable_simd256_codes_ [kMaxFPRegisters]
AliasingKind fp_aliasing_kind_
Detailed Description
Definition at line 17 of file register-configuration.h.
Constructor & Destructor Documentation
RegisterConfiguration()
v8::internal::RegisterConfiguration::RegisterConfiguration (AliasingKind fp_aliasing_kind, int num_general_registers, int num_double_registers, int num_simd128_registers, int num_simd256_registers, int num_allocatable_general_registers, int num_allocatable_double_registers, int num_allocatable_simd128_registers, int num_allocatable_simd256_registers, const int * allocatable_general_codes, const int * allocatable_double_codes, const int * independent_allocatable_simd128_codes = nullptr)
Definition at line 227 of file register-configuration.cc.
    : num_general_registers_(num_general_registers),
      num_float_registers_(0),
      num_double_registers_(num_double_registers),
      num_simd128_registers_(num_simd128_registers),
      num_simd256_registers_(num_simd256_registers),
      num_allocatable_general_registers_(num_allocatable_general_registers),
      num_allocatable_float_registers_(0),
      num_allocatable_double_registers_(num_allocatable_double_registers),
      num_allocatable_simd128_registers_(num_allocatable_simd128_registers),
      num_allocatable_simd256_registers_(num_allocatable_simd256_registers),
      allocatable_general_codes_mask_(0),
      allocatable_float_codes_mask_(0),
      allocatable_double_codes_mask_(0),
      allocatable_simd128_codes_mask_(0),
      allocatable_simd256_codes_mask_(0),
      allocatable_general_codes_(allocatable_general_codes),
      allocatable_double_codes_(allocatable_double_codes),
      fp_aliasing_kind_(fp_aliasing_kind) {
  DCHECK_LE(num_general_registers_,
            RegisterConfiguration::kMaxGeneralRegisters);
  DCHECK_LE(num_double_registers_, RegisterConfiguration::kMaxFPRegisters);
  for (int i = 0; i < num_allocatable_general_registers_; ++i) {
    allocatable_general_codes_mask_ |= (1 << allocatable_general_codes_[i]);
  }
  for (int i = 0; i < num_allocatable_double_registers_; ++i) {
    allocatable_double_codes_mask_ |= (1 << allocatable_double_codes_[i]);
  }
  if (fp_aliasing_kind_ == AliasingKind::kCombine) {
    num_float_registers_ = num_double_registers_ * 2 <= kMaxFPRegisters
                               ? num_double_registers_ * 2
                               : kMaxFPRegisters;
    num_allocatable_float_registers_ = 0;
    for (int i = 0; i < num_allocatable_double_registers_; i++) {
      int base_code = allocatable_double_codes_[i] * 2;
      if (base_code >= kMaxFPRegisters) continue;
      allocatable_float_codes_[num_allocatable_float_registers_++] = base_code;
      allocatable_float_codes_[num_allocatable_float_registers_++] =
          base_code + 1;
      allocatable_float_codes_mask_ |= (0x3 << base_code);
    }
    num_simd128_registers_ = num_double_registers_ / 2;
    num_allocatable_simd128_registers_ = 0;
    int last_simd128_code = allocatable_double_codes_[0] / 2;
    for (int i = 1; i < num_allocatable_double_registers_; i++) {
      int next_simd128_code = allocatable_double_codes_[i] / 2;
      // This scheme assumes allocatable_double_codes_ are strictly increasing.
      DCHECK_GE(next_simd128_code, last_simd128_code);
      if (last_simd128_code == next_simd128_code) {
        allocatable_simd128_codes_[num_allocatable_simd128_registers_++] =
            next_simd128_code;
        allocatable_simd128_codes_mask_ |= (0x1 << next_simd128_code);
      }
      last_simd128_code = next_simd128_code;
    }
  } else if (fp_aliasing_kind_ == AliasingKind::kOverlap) {
    num_float_registers_ = num_simd128_registers_ = num_double_registers_;
    num_allocatable_float_registers_ = num_allocatable_simd128_registers_ =
        num_allocatable_double_registers_;
    for (int i = 0; i < num_allocatable_float_registers_; ++i) {
      allocatable_float_codes_[i] = allocatable_simd128_codes_[i] =
          allocatable_double_codes_[i];
#if V8_TARGET_ARCH_X64
      allocatable_simd256_codes_[i] = allocatable_double_codes_[i];
#endif
    }
    allocatable_float_codes_mask_ = allocatable_simd128_codes_mask_ =
        allocatable_double_codes_mask_;
#if V8_TARGET_ARCH_X64
    num_simd256_registers_ = num_double_registers_;
    num_allocatable_simd256_registers_ = num_allocatable_double_registers_;
    allocatable_simd256_codes_mask_ = allocatable_double_codes_mask_;
#endif
  } else {
    DCHECK_EQ(fp_aliasing_kind_, AliasingKind::kIndependent);
    DCHECK_NE(independent_allocatable_simd128_codes, nullptr);
    num_float_registers_ = num_double_registers_;
    num_allocatable_float_registers_ = num_allocatable_double_registers_;
    for (int i = 0; i < num_allocatable_float_registers_; ++i) {
      allocatable_float_codes_[i] = allocatable_double_codes_[i];
    }
    allocatable_float_codes_mask_ = allocatable_double_codes_mask_;
    for (int i = 0; i < num_allocatable_simd128_registers; i++) {
      allocatable_simd128_codes_[i] = independent_allocatable_simd128_codes[i];
    }
    for (int i = 0; i < num_allocatable_simd128_registers_; ++i) {
      allocatable_simd128_codes_mask_ |= (1 << allocatable_simd128_codes_[i]);
    }
  }
}
References allocatable_double_codes_, allocatable_double_codes_mask_, allocatable_float_codes_, allocatable_float_codes_mask_, allocatable_general_codes_, allocatable_general_codes_mask_, allocatable_simd128_codes_, allocatable_simd128_codes_mask_, allocatable_simd256_codes_, allocatable_simd256_codes_mask_, DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_NE, fp_aliasing_kind_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kCombine, v8::internal::kIndependent, kMaxFPRegisters, kMaxGeneralRegisters, v8::internal::kOverlap, num_allocatable_double_registers_, num_allocatable_float_registers_, num_allocatable_general_registers_, num_allocatable_simd128_registers(), num_allocatable_simd128_registers_, num_allocatable_simd256_registers_, num_double_registers_, num_float_registers_, num_general_registers_, num_simd128_registers_, and num_simd256_registers_.
 RegisterConfiguration()
virtual v8::internal::RegisterConfiguration::~RegisterConfiguration () [virtual], [default]
Member Function Documentation
allocatable_double_codes()
const int* v8::internal::RegisterConfiguration::allocatable_double_codes () const [inline]
Definition at line 123 of file register-configuration.h.
                                              {
    return allocatable_double_codes_;
  }
Referenced by v8::internal::compiler::GetAllocatableRegisterCodes().
allocatable_double_codes_mask()
int32_t v8::internal::RegisterConfiguration::allocatable_double_codes_mask () const [inline]
Definition at line 72 of file register-configuration.h.
                                                {
    return allocatable_double_codes_mask_;
  }
allocatable_float_codes()
const int* v8::internal::RegisterConfiguration::allocatable_float_codes () const [inline]
Definition at line 120 of file register-configuration.h.
                                             {
    return allocatable_float_codes_;
  }
Referenced by v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet().
allocatable_float_codes_mask()
int32_t v8::internal::RegisterConfiguration::allocatable_float_codes_mask () const [inline]
Definition at line 75 of file register-configuration.h.
                                               {
    return allocatable_float_codes_mask_;
  }
allocatable_general_codes()
const int* v8::internal::RegisterConfiguration::allocatable_general_codes () const [inline]
Definition at line 117 of file register-configuration.h.
                                               {
    return allocatable_general_codes_;
  }
Referenced by v8::internal::compiler::GetAllocatableRegisterCodes().
allocatable_general_codes_mask()
int32_t v8::internal::RegisterConfiguration::allocatable_general_codes_mask () const [inline]
Definition at line 69 of file register-configuration.h.
                                                 {
    return allocatable_general_codes_mask_;
  }
allocatable_simd128_codes()
const int* v8::internal::RegisterConfiguration::allocatable_simd128_codes () const [inline]
Definition at line 126 of file register-configuration.h.
                                               {
    return allocatable_simd128_codes_;
  }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDeoptPoint(), v8::internal::compiler::GetAllocatableRegisterCodes(), v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet(), and v8::internal::compiler::LinearScanAllocator::GetSIMD128RegisterSet().
allocatable_simd128_codes_mask()
int32_t v8::internal::RegisterConfiguration::allocatable_simd128_codes_mask () const [inline]
Definition at line 78 of file register-configuration.h.
                                                 {
    return allocatable_simd128_codes_mask_;
  }
allocatable_simd256_codes()
const int* v8::internal::RegisterConfiguration::allocatable_simd256_codes () const [inline]
Definition at line 129 of file register-configuration.h.
                                               {
    return allocatable_simd256_codes_;
  }
Referenced by v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet().
AreAliases()
bool v8::internal::RegisterConfiguration::AreAliases (MachineRepresentation rep, int index, MachineRepresentation other_rep, int other_index) const
Definition at line 360 of file register-configuration.cc.
                                                              {
  DCHECK(fp_aliasing_kind_ == AliasingKind::kCombine);
  DCHECK(IsFloatingPoint(rep) && IsFloatingPoint(other_rep));
  if (rep == other_rep) {
    return index == other_index;
  }
  int rep_int = static_cast<int>(rep);
  int other_rep_int = static_cast<int>(other_rep);
  if (rep_int > other_rep_int) {
    int shift = rep_int - other_rep_int;
    return index == other_index >> shift;
  }
  int shift = other_rep_int - rep_int;
  return index >> shift == other_index;
}
References v8::internal::DCHECK(), fp_aliasing_kind_, v8::internal::index, v8::internal::IsFloatingPoint(), and v8::internal::kCombine.
Referenced by v8::internal::compiler::InstructionOperand::InterferesWith(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
Default()
const RegisterConfiguration * v8::internal::RegisterConfiguration::Default () [static]
Definition at line 203 of file register-configuration.cc.
                                                            {
  return GetDefaultRegisterConfiguration();
}
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters(), v8::internal::JavaScriptBuiltinContinuationFrame::ComputeParametersCount(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::ContainsOpOrAlias(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDeoptPoint(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes(), v8::internal::GetRegisterThatIsNotOneOf(), v8::internal::compiler::LiveRange::Print(), RestrictGeneralRegisters(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::WithAllocatableGeneralRegisters().
fp_aliasing_kind()
AliasingKind v8::internal::RegisterConfiguration::fp_aliasing_kind () const [inline]
Definition at line 68 of file register-configuration.h.
{ return fp_aliasing_kind_; }
GetAliases()
int v8::internal::RegisterConfiguration::GetAliases (MachineRepresentation rep, int index, MachineRepresentation other_rep, int * alias_base_index) const
Definition at line 334 of file register-configuration.cc.
                                                                   {
  DCHECK(fp_aliasing_kind_ == AliasingKind::kCombine);
  DCHECK(IsFloatingPoint(rep) && IsFloatingPoint(other_rep));
  if (rep == other_rep) {
    *alias_base_index = index;
    return 1;
  }
  int rep_int = static_cast<int>(rep);
  int other_rep_int = static_cast<int>(other_rep);
  if (rep_int > other_rep_int) {
    int shift = rep_int - other_rep_int;
    int base_index = index << shift;
    if (base_index >= kMaxFPRegisters) {
      // Alias indices would be out of FP register range.
      return 0;
    }
    *alias_base_index = base_index;
    return 1 << shift;
  }
  int shift = other_rep_int - rep_int;
  *alias_base_index = index >> shift;
  return 1;
}
References v8::internal::DCHECK(), fp_aliasing_kind_, v8::internal::index, v8::internal::IsFloatingPoint(), v8::internal::kCombine, and kMaxFPRegisters.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::ContainsOpOrAlias(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::RegisterAllocationData::HasFixedUse(), v8::internal::compiler::RegisterAllocationData::MarkAllocated(), and v8::internal::compiler::RegisterAllocationData::MarkFixedUse().
GetAllocatableDoubleCode()
int v8::internal::RegisterConfiguration::GetAllocatableDoubleCode (int index) const [inline]
Definition at line 95 of file register-configuration.h.
                                                {
    DCHECK(index >= 0 && index < num_allocatable_double_registers());
    return allocatable_double_codes_[index];
  }
References v8::internal::DCHECK(), and v8::internal::index.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
GetAllocatableFloatCode()
int v8::internal::RegisterConfiguration::GetAllocatableFloatCode (int index) const [inline]
Definition at line 88 of file register-configuration.h.
                                               {
    DCHECK(index >= 0 && index < num_allocatable_float_registers());
    return allocatable_float_codes_[index];
  }
References v8::internal::DCHECK(), and v8::internal::index.
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
GetAllocatableGeneralCode()
int v8::internal::RegisterConfiguration::GetAllocatableGeneralCode (int index) const [inline]
Definition at line 81 of file register-configuration.h.
                                                 {
    DCHECK(index >= 0 && index < num_allocatable_general_registers());
    return allocatable_general_codes_[index];
  }
References v8::internal::DCHECK(), and v8::internal::index.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper(), v8::internal::GetRegisterThatIsNotOneOf(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), RestrictGeneralRegisters(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::WithAllocatableGeneralRegisters().
GetAllocatableSimd128Code()
int v8::internal::RegisterConfiguration::GetAllocatableSimd128Code (int index) const [inline]
Definition at line 102 of file register-configuration.h.
                                                 {
    DCHECK(index >= 0 && index < num_allocatable_simd128_registers());
    return allocatable_simd128_codes_[index];
  }
References v8::internal::DCHECK(), and v8::internal::index.
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
GetAllocatableSimd256Code()
int v8::internal::RegisterConfiguration::GetAllocatableSimd256Code (int index) const [inline]
Definition at line 109 of file register-configuration.h.
                                                 {
    DCHECK(index >= 0 && index < num_allocatable_simd256_registers());
    return allocatable_simd256_codes_[index];
  }
References v8::internal::DCHECK(), and v8::internal::index.
IsAllocatableDoubleCode()
bool v8::internal::RegisterConfiguration::IsAllocatableDoubleCode (int index) const [inline]
Definition at line 99 of file register-configuration.h.
                                                {
    return ((1 << index) & allocatable_double_codes_mask_) != 0;
  }
References v8::internal::index.
IsAllocatableFloatCode()
bool v8::internal::RegisterConfiguration::IsAllocatableFloatCode (int index) const [inline]
Definition at line 92 of file register-configuration.h.
                                               {
    return ((1 << index) & allocatable_float_codes_mask_) != 0;
  }
References v8::internal::index.
IsAllocatableGeneralCode()
bool v8::internal::RegisterConfiguration::IsAllocatableGeneralCode (int index) const [inline]
Definition at line 85 of file register-configuration.h.
                                                 {
    return ((1 << index) & allocatable_general_codes_mask_) != 0;
  }
References v8::internal::index.
IsAllocatableSimd128Code()
bool v8::internal::RegisterConfiguration::IsAllocatableSimd128Code (int index) const [inline]
Definition at line 106 of file register-configuration.h.
                                                 {
    return ((1 << index) & allocatable_simd128_codes_mask_) != 0;
  }
References v8::internal::index.
IsAllocatableSimd256Code()
bool v8::internal::RegisterConfiguration::IsAllocatableSimd256Code (int index) const [inline]
Definition at line 113 of file register-configuration.h.
                                                 {
    return ((1 << index) & allocatable_simd256_codes_mask_) != 0;
  }
References v8::internal::index.
num_allocatable_double_registers()
int v8::internal::RegisterConfiguration::num_allocatable_double_registers () const [inline]
Definition at line 58 of file register-configuration.h.
                                               {
    return num_allocatable_double_registers_;
  }
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::compiler::GetAllocatableRegisterCount(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
num_allocatable_float_registers()
int v8::internal::RegisterConfiguration::num_allocatable_float_registers () const [inline]
Definition at line 52 of file register-configuration.h.
                                              {
    return num_allocatable_float_registers_;
  }
Referenced by v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
num_allocatable_general_registers()
int v8::internal::RegisterConfiguration::num_allocatable_general_registers () const [inline]
Definition at line 49 of file register-configuration.h.
                                                {
    return num_allocatable_general_registers_;
  }
Referenced by v8::internal::BuiltinContinuationFrameInfo::BuiltinContinuationFrameInfo(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper(), v8::internal::compiler::GetAllocatableRegisterCount(), v8::internal::GetRegisterThatIsNotOneOf(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), RestrictGeneralRegisters(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::WithAllocatableGeneralRegisters().
num_allocatable_simd128_registers()
int v8::internal::RegisterConfiguration::num_allocatable_simd128_registers () const [inline]
Definition at line 61 of file register-configuration.h.
                                                {
    return num_allocatable_simd128_registers_;
  }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDeoptPoint(), v8::internal::compiler::GetAllocatableRegisterCount(), v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet(), v8::internal::compiler::LinearScanAllocator::GetSIMD128RegisterSet(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and RegisterConfiguration().
num_allocatable_simd256_registers()
int v8::internal::RegisterConfiguration::num_allocatable_simd256_registers () const [inline]
Definition at line 64 of file register-configuration.h.
                                                {
    return num_allocatable_simd256_registers_;
  }
Referenced by v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet().
num_double_registers()
int v8::internal::RegisterConfiguration::num_double_registers () const [inline]
Definition at line 46 of file register-configuration.h.
{ return num_double_registers_; }
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor(), v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeID(), v8::internal::compiler::GetRegisterCount(), and v8::internal::compiler::RegisterAllocationData::RegisterAllocationData().
num_float_registers()
int v8::internal::RegisterConfiguration::num_float_registers () const [inline]
Definition at line 45 of file register-configuration.h.
{ return num_float_registers_; }
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor(), v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeID(), and v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet().
num_general_registers()
int v8::internal::RegisterConfiguration::num_general_registers () const [inline]
Definition at line 44 of file register-configuration.h.
{ return num_general_registers_; }
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeID(), v8::internal::compiler::LiveRangeBuilder::FixedLiveRangeFor(), v8::internal::compiler::GetRegisterCount(), and v8::internal::compiler::RegisterAllocationData::RegisterAllocationData().
num_simd128_registers()
int v8::internal::RegisterConfiguration::num_simd128_registers () const [inline]
Definition at line 47 of file register-configuration.h.
{ return num_simd128_registers_; }
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor(), v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeID(), v8::internal::compiler::LiveRangeBuilder::FixedSIMD128LiveRangeFor(), v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet(), v8::internal::compiler::GetRegisterCount(), v8::internal::compiler::LinearScanAllocator::GetSIMD128RegisterSet(), and v8::internal::compiler::RegisterAllocationData::RegisterAllocationData().
num_simd256_registers()
int v8::internal::RegisterConfiguration::num_simd256_registers () const [inline]
Definition at line 48 of file register-configuration.h.
{ return num_simd256_registers_; }
Referenced by v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet().
Poisoning()
static const RegisterConfiguration* v8::internal::RegisterConfiguration::Poisoning () [static]
RestrictGeneralRegisters()
const RegisterConfiguration * v8::internal::RegisterConfiguration::RestrictGeneralRegisters (RegList registers) [static]
Definition at line 207 of file register-configuration.cc.
                       {
  int num = registers.Count();
  std::unique_ptr<int[]> codes{new int[num]};
  std::unique_ptr<char const* []> names { new char const*[num] };
  int counter = 0;
  for (int i = 0; i < Default()->num_allocatable_general_registers(); ++i) {
    auto reg = Register::from_code(Default()->GetAllocatableGeneralCode(i));
    if (registers.has(reg)) {
      DCHECK(counter < num);
      codes[counter] = reg.code();
      names[counter] = RegisterName(Register::from_code(i));
      counter++;
    }
  }
  return new RestrictedRegisterConfiguration(num, std::move(codes),
                                             std::move(names));
}
References v8::internal::RegListBase< RegisterT >::Count(), v8::internal::DCHECK(), Default(), v8::internal::Register::from_code(), GetAllocatableGeneralCode(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and num_allocatable_general_registers().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
Member Data Documentation
allocatable_double_codes_
const int* v8::internal::RegisterConfiguration::allocatable_double_codes_ [private]
Definition at line 165 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_double_codes_mask_
int32_t v8::internal::RegisterConfiguration::allocatable_double_codes_mask_ [private]
Definition at line 160 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_float_codes_
int v8::internal::RegisterConfiguration::allocatable_float_codes_[kMaxFPRegisters] [private]
Definition at line 164 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_float_codes_mask_
int32_t v8::internal::RegisterConfiguration::allocatable_float_codes_mask_ [private]
Definition at line 159 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_general_codes_
const int* v8::internal::RegisterConfiguration::allocatable_general_codes_ [private]
Definition at line 163 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_general_codes_mask_
int32_t v8::internal::RegisterConfiguration::allocatable_general_codes_mask_ [private]
Definition at line 158 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_simd128_codes_
int v8::internal::RegisterConfiguration::allocatable_simd128_codes_[kMaxFPRegisters] [private]
Definition at line 166 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_simd128_codes_mask_
int32_t v8::internal::RegisterConfiguration::allocatable_simd128_codes_mask_ [private]
Definition at line 161 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_simd256_codes_
int v8::internal::RegisterConfiguration::allocatable_simd256_codes_[kMaxFPRegisters] [private]
Definition at line 167 of file register-configuration.h.
Referenced by RegisterConfiguration().
allocatable_simd256_codes_mask_
int32_t v8::internal::RegisterConfiguration::allocatable_simd256_codes_mask_ [private]
Definition at line 162 of file register-configuration.h.
Referenced by RegisterConfiguration().
fp_aliasing_kind_
AliasingKind v8::internal::RegisterConfiguration::fp_aliasing_kind_ [private]
Definition at line 168 of file register-configuration.h.
Referenced by AreAliases(), GetAliases(), and RegisterConfiguration().
kMaxFPRegisters
constexpr int v8::internal::RegisterConfiguration::kMaxFPRegisters = 32 [static], [constexpr]
Definition at line 21 of file register-configuration.h.
Referenced by GetAliases(), and RegisterConfiguration().
kMaxGeneralRegisters
constexpr int v8::internal::RegisterConfiguration::kMaxGeneralRegisters = 32 [static], [constexpr]
Definition at line 20 of file register-configuration.h.
Referenced by RegisterConfiguration().
kMaxRegisters
constexpr int v8::internal::RegisterConfiguration::kMaxRegisters [static], [constexpr]
Initial value:
=
      std::max(kMaxFPRegisters, kMaxGeneralRegisters)
Definition at line 22 of file register-configuration.h.
Referenced by v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors().
num_allocatable_double_registers_
int v8::internal::RegisterConfiguration::num_allocatable_double_registers_ [private]
Definition at line 155 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_allocatable_float_registers_
int v8::internal::RegisterConfiguration::num_allocatable_float_registers_ [private]
Definition at line 154 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_allocatable_general_registers_
int v8::internal::RegisterConfiguration::num_allocatable_general_registers_ [private]
Definition at line 153 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_allocatable_simd128_registers_
int v8::internal::RegisterConfiguration::num_allocatable_simd128_registers_ [private]
Definition at line 156 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_allocatable_simd256_registers_
int v8::internal::RegisterConfiguration::num_allocatable_simd256_registers_ [private]
Definition at line 157 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_double_registers_
const int v8::internal::RegisterConfiguration::num_double_registers_ [private]
Definition at line 150 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_float_registers_
int v8::internal::RegisterConfiguration::num_float_registers_ [private]
Definition at line 149 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_general_registers_
const int v8::internal::RegisterConfiguration::num_general_registers_ [private]
Definition at line 148 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_simd128_registers_
int v8::internal::RegisterConfiguration::num_simd128_registers_ [private]
Definition at line 151 of file register-configuration.h.
Referenced by RegisterConfiguration().
num_simd256_registers_
int v8::internal::RegisterConfiguration::num_simd256_registers_ [private]
Definition at line 152 of file register-configuration.h.
Referenced by RegisterConfiguration().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/register-configuration.h
/mnt/V8SourceCode/src/codegen/register-configuration.cc