v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference Class Reference
Helper class for GetReference/SetWithReference.
#include <v8-util.h>
Public Member Functions
PersistentValueReference ()
PersistentValueReference (const PersistentValueReference &other)
Local< V > NewLocal (Isolate *isolate) const
bool IsEmpty () const
template<typename T >
bool SetReturnValue (ReturnValue< T > returnValue)
void Reset ()
void operator= (const PersistentValueReference &other)
Private Member Functions
PersistentValueReference (PersistentContainerValue value)
void operator= (PersistentContainerValue value)
Private Attributes
PersistentContainerValue value_
Friends
class PersistentValueMapBase
class PersistentValueMap< K, V, Traits >
class GlobalValueMap< K, V, Traits >
Detailed Description
template<typename K, typename V, typename Traits>
class v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference
Helper class for GetReference/SetWithReference.
Do not use outside that context.
Definition at line 236 of file v8-util.h.
Constructor & Destructor Documentation
PersistentValueReference() [1/3]
template<typename K , typename V , typename Traits >
v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::PersistentValueReference () [inline]
Definition at line 238 of file v8-util.h.
: value_(kPersistentContainerNotFound) { }
PersistentValueReference() [2/3]
template<typename K , typename V , typename Traits >
v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::PersistentValueReference (const PersistentValueReference & other) [inline]
Definition at line 239 of file v8-util.h.
        : value_(other.value_) { }
PersistentValueReference() [3/3]
template<typename K , typename V , typename Traits >
v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::PersistentValueReference (PersistentContainerValue value) [inline], [explicit], [private]
Definition at line 266 of file v8-util.h.
        : value_(value) { }
Member Function Documentation
IsEmpty()
template<typename K , typename V , typename Traits >
bool v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::IsEmpty () const [inline]
Definition at line 247 of file v8-util.h.
                         {
      return value_ == kPersistentContainerNotFound;
    }
References v8::kPersistentContainerNotFound, and v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::value_.
NewLocal()
template<typename K , typename V , typename Traits >
Local<V> v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::NewLocal (Isolate * isolate) const [inline]
Definition at line 242 of file v8-util.h.
                                              {
      return Local<V>::New(isolate,
                           internal::ValueHelper::SlotAsValue<V>(
                               reinterpret_cast<internal::Address*>(value_)));
    }
References v8::PersistentValueMapBase< K, V, Traits >::isolate(), v8::Local< T >::New(), and v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::value_.
operator=() [1/2]
template<typename K , typename V , typename Traits >
void v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::operator= (const PersistentValueReference & other) [inline]
Definition at line 257 of file v8-util.h.
                                                          {
      value_ = other.value_;
    }
References v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::value_.
operator=() [2/2]
template<typename K , typename V , typename Traits >
void v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::operator= (PersistentContainerValue value) [inline], [private]
Definition at line 269 of file v8-util.h.
                                                   {
      value_ = value;
    }
References v8::internal::value, and v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::value_.
Reset()
template<typename K , typename V , typename Traits >
void v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::Reset () [inline]
Definition at line 254 of file v8-util.h.
                 {
      value_ = kPersistentContainerNotFound;
    }
References v8::kPersistentContainerNotFound, and v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::value_.
SetReturnValue()
template<typename K , typename V , typename Traits >
template<typename T >
bool v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::SetReturnValue (ReturnValue< T > returnValue) [inline]
Definition at line 251 of file v8-util.h.
                                                    {
      return SetReturnValueFromVal(&returnValue, value_);
    }
References v8::PersistentValueMapBase< K, V, Traits >::SetReturnValueFromVal(), and v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::value_.
Friends And Related Function Documentation
GlobalValueMap< K, V, Traits >
template<typename K , typename V , typename Traits >
friend class GlobalValueMap< K, V, Traits > [friend]
Definition at line 262 of file v8-util.h.
PersistentValueMap< K, V, Traits >
template<typename K , typename V , typename Traits >
friend class PersistentValueMap< K, V, Traits > [friend]
Definition at line 262 of file v8-util.h.
PersistentValueMapBase
template<typename K , typename V , typename Traits >
friend class PersistentValueMapBase [friend]
Definition at line 262 of file v8-util.h.
Member Data Documentation
value_
template<typename K , typename V , typename Traits >
PersistentContainerValue v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::value_ [private]
Definition at line 273 of file v8-util.h.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::IsEmpty(), v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::NewLocal(), v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::operator=(), v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::Reset(), and v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::SetReturnValue().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-util.h