v8::internal::torque::CCGenerator Class Reference
#include <cc-generator.h>
Public Member Functions
CCGenerator (const ControlFlowGraph &cfg, std::ostream &out, bool is_cc_debug=false)
std::optional< Stack< std::string > > EmitGraph (Stack< std::string > parameters)
Static Public Member Functions
static void EmitCCValue (VisitResult result, const Stack< std::string > &values, std::ostream &out)
Private Member Functions
void EmitSourcePosition (SourcePosition pos, bool always_emit=false) override
void EmitGoto (const Block *destination, Stack< std::string > *stack, std::string indentation)
std::vector< std::string > ProcessArgumentsCommon (const TypeVector &parameter_types, std::vector< std::string > constexpr_arguments, Stack< std::string > *stack)
Stack< std::string > EmitBlock (const Block *block)
Private Attributes
bool is_cc_debug_
Additional Inherited Members
Detailed Description
Definition at line 14 of file cc-generator.h.
Constructor & Destructor Documentation
CCGenerator()
v8::internal::torque::CCGenerator::CCGenerator (const ControlFlowGraph & cfg, std::ostream & out, bool is_cc_debug = false) [inline]
Definition at line 16 of file cc-generator.h.
      : TorqueCodeGenerator(cfg, out), is_cc_debug_(is_cc_debug) {}
Member Function Documentation
EmitBlock()
Stack< std::string > v8::internal::torque::CCGenerator::EmitBlock (const Block * block) [private]
Definition at line 51 of file cc-generator.cc.
                                                          {
  out() << "\n";
  out() << " " << BlockName(block) << ":\n";
  Stack<std::string> stack;
  for (BottomOffset i = {0}; i < block->InputTypes().AboveTop(); ++i) {
    const auto& def = block->InputDefinitions().Peek(i);
    stack.Push(DefinitionToVariable(def));
    if (def.IsPhiFromBlock(block)) {
      decls() << " "
              << (is_cc_debug_ ? block->InputTypes().Peek(i)->GetDebugType()
                               : block->InputTypes().Peek(i)->GetRuntimeType())
              << " " << stack.Top() << "{}; USE(" << stack.Top() << ");\n";
    }
  }
  for (const Instruction& instruction : block->instructions()) {
    TorqueCodeGenerator::EmitInstruction(instruction, &stack);
  }
  return stack;
}
References v8::internal::torque::TorqueCodeGenerator::BlockName(), v8::internal::torque::TorqueCodeGenerator::decls(), v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), v8::internal::torque::TorqueCodeGenerator::EmitInstruction(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Block::InputDefinitions(), v8::internal::torque::Block::InputTypes(), v8::internal::torque::Block::instructions(), is_cc_debug_, v8::internal::torque::TorqueCodeGenerator::out(), and v8::internal::stack.
Referenced by EmitGraph().
EmitCCValue()
void v8::internal::torque::CCGenerator::EmitCCValue (VisitResult result, const Stack< std::string > & values, std::ostream & out) [static]
Definition at line 514 of file cc-generator.cc.
                                               {
  std::vector<std::string> all_fields;
  CollectAllFields(result, values, all_fields);
  if (all_fields.size() == 1) {
    out << all_fields[0];
  } else {
    out << "std::make_tuple(";
    PrintCommaSeparatedList(out, all_fields);
    out << ")";
  }
}
References v8::internal::torque::anonymous_namespace{cc-generator.cc}::CollectAllFields(), v8::internal::torque::TorqueCodeGenerator::out(), v8::internal::torque::PrintCommaSeparatedList(), and v8::base::internal::result.
Referenced by ProcessArgumentsCommon(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
EmitGoto()
void v8::internal::torque::CCGenerator::EmitGoto (const Block * destination, Stack< std::string > * stack, std::string indentation) [private]
Definition at line 302 of file cc-generator.cc.
                                                  {
  const auto& destination_definitions = destination->InputDefinitions();
  DCHECK_EQ(stack->Size(), destination_definitions.Size());
  for (BottomOffset i = {0}; i < stack->AboveTop(); ++i) {
    DefinitionLocation def = destination_definitions.Peek(i);
    if (def.IsPhiFromBlock(destination)) {
      out() << indentation << DefinitionToVariable(def) << " = "
            << stack->Peek(i) << ";\n";
    }
  }
  out() << indentation << "goto " << BlockName(destination) << ";\n";
}
References v8::internal::torque::TorqueCodeGenerator::BlockName(), DCHECK_EQ, v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Block::InputDefinitions(), v8::internal::torque::DefinitionLocation::IsPhiFromBlock(), v8::internal::torque::TorqueCodeGenerator::out(), and v8::internal::stack.
EmitGraph()
std::optional< Stack< std::string > > v8::internal::torque::CCGenerator::EmitGraph (Stack< std::string > parameters)
Definition at line 17 of file cc-generator.cc.
                                 {
  for (BottomOffset i = {0}; i < parameters.AboveTop(); ++i) {
    SetDefinitionVariable(DefinitionLocation::Parameter(i.offset),
                          parameters.Peek(i));
  }
  // Redirect the output of non-declarations into a buffer and only output
  // declarations right away.
  std::stringstream out_buffer;
  std::ostream* old_out = out_;
  out_ = &out_buffer;
  EmitInstruction(GotoInstruction{cfg_.start()}, &parameters);
  for (Block* block : cfg_.blocks()) {
    if (cfg_.end() && *cfg_.end() == block) continue;
    if (block->IsDead()) continue;
    EmitBlock(block);
  }
  std::optional<Stack<std::string>> result;
  if (cfg_.end()) {
    result = EmitBlock(*cfg_.end());
  }
  // All declarations have been printed now, so we can append the buffered
  // output and redirect back to the original output stream.
  out_ = old_out;
  out() << out_buffer.str();
  return result;
}
References v8::internal::torque::Stack< T >::AboveTop(), v8::internal::torque::ControlFlowGraph::blocks(), v8::internal::torque::TorqueCodeGenerator::cfg_, EmitBlock(), v8::internal::torque::TorqueCodeGenerator::EmitInstruction(), v8::internal::torque::ControlFlowGraph::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::TorqueCodeGenerator::out(), v8::internal::torque::TorqueCodeGenerator::out_, v8::internal::torque::DefinitionLocation::Parameter(), v8::internal::torque::Stack< T >::Peek(), v8::base::internal::result, v8::internal::torque::TorqueCodeGenerator::SetDefinitionVariable(), and v8::internal::torque::ControlFlowGraph::start().
Referenced by v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
EmitSourcePosition()
void v8::internal::torque::CCGenerator::EmitSourcePosition (SourcePosition pos, bool always_emit = false) [override], [private], [virtual]
Implements v8::internal::torque::TorqueCodeGenerator.
Definition at line 74 of file cc-generator.cc.
                                                                         {
  const std::string& file = SourceFileMap::AbsolutePath(pos.source);
  if (always_emit || !previous_position_.CompareStartIgnoreColumn(pos)) {
    // Lines in Torque SourcePositions are zero-based, while the
    // CodeStubAssembler and downwind systems are one-based.
    out() << " // " << file << ":" << (pos.start.line + 1) << "\n";
    previous_position_ = pos;
  }
}
References v8::internal::torque::SourceFileMap::AbsolutePath(), v8::internal::torque::SourcePosition::CompareStartIgnoreColumn(), file(), v8::internal::torque::LineAndColumn::line, v8::internal::torque::TorqueCodeGenerator::out(), v8::internal::torque::TorqueCodeGenerator::previous_position_, v8::internal::torque::SourcePosition::source, v8::internal::torque::SourcePosition::start, and v8::internal::string.
ProcessArgumentsCommon()
std::vector< std::string > v8::internal::torque::CCGenerator::ProcessArgumentsCommon (const TypeVector & parameter_types, std::vector< std::string > constexpr_arguments, Stack< std::string > * stack) [private]
Definition at line 102 of file cc-generator.cc.
                                                                       {
  std::vector<std::string> args;
  for (auto it = parameter_types.rbegin(); it != parameter_types.rend(); ++it) {
    const Type* type = *it;
    if (type->IsConstexpr()) {
      args.push_back(std::move(constexpr_arguments.back()));
      constexpr_arguments.pop_back();
    } else {
      std::stringstream s;
      size_t slot_count = LoweredSlotCount(type);
      VisitResult arg = VisitResult(type, stack->TopRange(slot_count));
      EmitCCValue(arg, *stack, s);
      args.push_back(s.str());
      stack->PopMany(slot_count);
    }
  }
  std::reverse(args.begin(), args.end());
  return args;
}
References v8::base::args, EmitCCValue(), v8::internal::torque::LoweredSlotCount(), v8::internal::stack, and v8::internal::tracing::type.
Member Data Documentation
is_cc_debug_
bool v8::internal::torque::CCGenerator::is_cc_debug_ [private]
Definition at line 25 of file cc-generator.h.
Referenced by EmitBlock().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/cc-generator.h
/mnt/V8SourceCode/src/torque/cc-generator.cc