v8::internal::PreParserStatement Class Reference
#include <preparser.h>
Public Member Functions
void InitializeStatements (const PreParserScopedStatementList &statements, Zone *zone)
bool IsStringLiteral ()
bool IsJumpStatement ()
bool IsNull ()
bool IsIterationStatement ()
bool IsEmptyStatement ()
PreParserStatement * operator-> ()
PreParserStatementList statements ()
PreParserStatementList cases ()
void set_scope (Scope *scope)
void Initialize (const PreParserExpression &cond, PreParserStatement body, const SourceRange &body_range={})
void Initialize (PreParserStatement init, const PreParserExpression &cond, PreParserStatement next, PreParserStatement body, const SourceRange &body_range={})
void Initialize (PreParserExpression each, const PreParserExpression &subject, PreParserStatement body, Scope *subject_scope)
Static Public Member Functions
static PreParserStatement Default ()
static PreParserStatement Iteration ()
static PreParserStatement Null ()
static PreParserStatement Jump ()
static PreParserStatement ExpressionStatement (const PreParserExpression &expression)
Protected Types
enum Type {
kNullStatement
, kUnknownStatement
, kJumpStatement
, kIterationStatement
,
kStringLiteralExpressionStatement
 }
Protected Member Functions
PreParserStatement (Type code)
Private Attributes
Type code_
Detailed Description
Definition at line 364 of file preparser.h.
Member Enumeration Documentation
Type
enum v8::internal::PreParserStatement::Type [protected]
Enumerator
kNullStatement
kUnknownStatement
kJumpStatement
kIterationStatement
kStringLiteralExpressionStatement
Definition at line 428 of file preparser.h.
            {
    kNullStatement,
    kUnknownStatement,
    kJumpStatement,
    kIterationStatement,
    kStringLiteralExpressionStatement,
  };
Constructor & Destructor Documentation
PreParserStatement()
v8::internal::PreParserStatement::PreParserStatement (Type code) [inline], [explicit], [protected]
Definition at line 436 of file preparser.h.
: code_(code) {}
Referenced by Default(), ExpressionStatement(), Iteration(), Jump(), and Null().
Member Function Documentation
cases()
PreParserStatementList v8::internal::PreParserStatement::cases () [inline]
Definition at line 416 of file preparser.h.
{ return PreParserStatementList(); }
Default()
static PreParserStatement v8::internal::PreParserStatement::Default () [inline], [static]
Definition at line 366 of file preparser.h.
                                      {
    return PreParserStatement(kUnknownStatement);
  }
References kUnknownStatement, and PreParserStatement().
Referenced by v8::internal::PreParser::BuildInitializationBlock(), v8::internal::PreParser::DeclareClass(), v8::internal::PreParser::DeclareFunction(), v8::internal::PreParser::DeclareNative(), v8::internal::PreParserFactory::EmptyStatement(), ExpressionStatement(), v8::internal::PreParserFactory::NewCaseClause(), v8::internal::PreParserFactory::NewDebuggerStatement(), v8::internal::PreParserFactory::NewSwitchStatement(), v8::internal::PreParserFactory::NewWithStatement(), v8::internal::PreParser::RewriteSwitchStatement(), and v8::internal::PreParser::RewriteTryStatement().
ExpressionStatement()
static PreParserStatement v8::internal::PreParserStatement::ExpressionStatement (const PreParserExpression & expression) [inline], [static]
Definition at line 388 of file preparser.h.
                                             {
    if (expression.IsStringLiteral()) {
      return PreParserStatement(kStringLiteralExpressionStatement);
    }
    return Default();
  }
References Default(), v8::internal::PreParserExpression::IsStringLiteral(), kStringLiteralExpressionStatement, and PreParserStatement().
Referenced by v8::internal::PreParserFactory::NewExpressionStatement().
Initialize() [1/3]
void v8::internal::PreParserStatement::Initialize (const PreParserExpression & cond, PreParserStatement body, const SourceRange & body_range = {}) [inline]
Definition at line 419 of file preparser.h.
                                                  {}) {}
Initialize() [2/3]
void v8::internal::PreParserStatement::Initialize (PreParserExpression each, const PreParserExpression & subject, PreParserStatement body, Scope * subject_scope) [inline]
Definition at line 424 of file preparser.h.
                                                                 {}
Initialize() [3/3]
void v8::internal::PreParserStatement::Initialize (PreParserStatement init, const PreParserExpression & cond, PreParserStatement next, PreParserStatement body, const SourceRange & body_range = {}) [inline]
Definition at line 421 of file preparser.h.
                                                  {}) {}
InitializeStatements()
void v8::internal::PreParserStatement::InitializeStatements (const PreParserScopedStatementList & statements, Zone * zone) [inline]
Definition at line 382 of file preparser.h.
                                        {}
IsEmptyStatement()
bool v8::internal::PreParserStatement::IsEmptyStatement () [inline]
Definition at line 406 of file preparser.h.
                          {
    DCHECK(!IsNull());
    return false;
  }
References v8::internal::DCHECK(), and IsNull().
IsIterationStatement()
bool v8::internal::PreParserStatement::IsIterationStatement () [inline]
Definition at line 404 of file preparser.h.
{ return code_ == kIterationStatement; }
References code_, and kIterationStatement.
Referenced by v8::internal::PreParser::IsIterationStatement().
IsJumpStatement()
bool v8::internal::PreParserStatement::IsJumpStatement () [inline]
Definition at line 398 of file preparser.h.
                         {
    return code_ == kJumpStatement;
  }
References code_, and kJumpStatement.
IsNull()
bool v8::internal::PreParserStatement::IsNull () [inline]
Definition at line 402 of file preparser.h.
{ return code_ == kNullStatement; }
References code_, and kNullStatement.
Referenced by IsEmptyStatement().
IsStringLiteral()
bool v8::internal::PreParserStatement::IsStringLiteral () [inline]
Definition at line 396 of file preparser.h.
{ return code_ == kStringLiteralExpressionStatement; }
References code_, and kStringLiteralExpressionStatement.
Referenced by v8::internal::PreParser::IsStringLiteral().
Iteration()
static PreParserStatement v8::internal::PreParserStatement::Iteration () [inline], [static]
Definition at line 370 of file preparser.h.
                                        {
    return PreParserStatement(kIterationStatement);
  }
References kIterationStatement, and PreParserStatement().
Referenced by v8::internal::PreParserFactory::NewDoWhileStatement(), v8::internal::PreParserFactory::NewForEachStatement(), v8::internal::PreParserFactory::NewForOfStatement(), v8::internal::PreParserFactory::NewForStatement(), and v8::internal::PreParserFactory::NewWhileStatement().
Jump()
static PreParserStatement v8::internal::PreParserStatement::Jump () [inline], [static]
Definition at line 378 of file preparser.h.
                                   {
    return PreParserStatement(kJumpStatement);
  }
References kJumpStatement, and PreParserStatement().
Referenced by v8::internal::PreParserFactory::NewAsyncReturnStatement(), v8::internal::PreParserFactory::NewBreakStatement(), v8::internal::PreParserFactory::NewContinueStatement(), v8::internal::PreParserFactory::NewReturnStatement(), and v8::internal::PreParser::NewThrowStatement().
Null()
static PreParserStatement v8::internal::PreParserStatement::Null () [inline], [static]
Definition at line 374 of file preparser.h.
                                   {
    return PreParserStatement(kNullStatement);
  }
References kNullStatement, and PreParserStatement().
Referenced by v8::internal::PreParser::NullStatement().
operator->()
PreParserStatement* v8::internal::PreParserStatement::operator-> () [inline]
Definition at line 413 of file preparser.h.
{ return this; }
set_scope()
void v8::internal::PreParserStatement::set_scope (Scope * scope) [inline]
Definition at line 418 of file preparser.h.
{}
statements()
PreParserStatementList v8::internal::PreParserStatement::statements () [inline]
Definition at line 415 of file preparser.h.
{ return PreParserStatementList(); }
Member Data Documentation
code_
Type v8::internal::PreParserStatement::code_ [private]
Definition at line 439 of file preparser.h.
Referenced by IsIterationStatement(), IsJumpStatement(), IsNull(), and IsStringLiteral().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparser.h