v8::internal::compiler::IA32OperandGenerator Class Reference
Public Member Functions
IA32OperandGenerator (InstructionSelector *selector)
InstructionOperand UseByteRegister (OpIndex node)
bool CanBeMemoryOperand (InstructionCode opcode, OpIndex node, OpIndex input, int effect_level)
bool CanBeImmediate (OpIndex node)
int32_t GetImmediateIntegerValue (OpIndex node)
bool ValueFitsIntoImmediate (int64_t value) const
AddressingMode GenerateMemoryOperandInputs (OptionalOpIndex index, int scale, OpIndex base, int32_t displacement, DisplacementMode displacement_mode, InstructionOperand inputs[], size_t *input_count, RegisterMode register_mode=RegisterMode::kRegister)
AddressingMode GetEffectiveAddressMemoryOperand (OpIndex node, InstructionOperand inputs[], size_t *input_count, RegisterMode register_mode=RegisterMode::kRegister)
InstructionOperand GetEffectiveIndexOperand (OpIndex index, AddressingMode *mode)
bool CanBeBetterLeftOperand (OpIndex node) const
Additional Inherited Members
Detailed Description
Definition at line 332 of file instruction-selector-ia32.cc.
Constructor & Destructor Documentation
IA32OperandGenerator()
v8::internal::compiler::IA32OperandGenerator::IA32OperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 334 of file instruction-selector-ia32.cc.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeBetterLeftOperand()
bool v8::internal::compiler::IA32OperandGenerator::CanBeBetterLeftOperand (OpIndex node) const [inline]
Definition at line 541 of file instruction-selector-ia32.cc.
                                                  {
    return !selector()->IsLive(node);
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompare().
CanBeImmediate()
bool v8::internal::compiler::IA32OperandGenerator::CanBeImmediate (OpIndex node) [inline]
Definition at line 372 of file instruction-selector-ia32.cc.
                                    {
    if (selector()->IsExternalConstant(node)) return true;
    if (const ConstantOp* constant = Get(node).TryCast<ConstantOp>()) {
      switch (constant->kind) {
        case ConstantOp::Kind::kWord32:
        case ConstantOp::Kind::kRelocatableWasmCall:
        case ConstantOp::Kind::kRelocatableWasmStubCall:
        case ConstantOp::Kind::kSmi:
          return true;
        case ConstantOp::Kind::kNumber:
          return constant->number().get_bits() == 0;
        default:
          break;
      }
    }
    return false;
  }
References v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::ConstantOp::kNumber, v8::internal::compiler::turboshaft::ConstantOp::kRelocatableWasmCall, v8::internal::compiler::turboshaft::ConstantOp::kRelocatableWasmStubCall, v8::internal::compiler::turboshaft::ConstantOp::kSmi, and v8::internal::compiler::turboshaft::ConstantOp::kWord32.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::VisitShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare().
CanBeMemoryOperand()
bool v8::internal::compiler::IA32OperandGenerator::CanBeMemoryOperand (InstructionCode opcode, OpIndex node, OpIndex input, int effect_level) [inline]
Definition at line 342 of file instruction-selector-ia32.cc.
                                            {
    if (!selector()->IsLoadOrLoadImmutable(input)) return false;
    if (!selector()->CanCover(node, input)) return false;
    if (effect_level != selector()->GetEffectLevel(input)) {
      return false;
    }
    MachineRepresentation rep =
        selector()->load_view(input).loaded_rep().representation();
    switch (opcode) {
      case kIA32And:
      case kIA32Or:
      case kIA32Xor:
      case kIA32Add:
      case kIA32Sub:
      case kIA32Cmp:
      case kIA32Test:
        return rep == MachineRepresentation::kWord32 || IsAnyTagged(rep);
      case kIA32Cmp16:
      case kIA32Test16:
        return rep == MachineRepresentation::kWord16;
      case kIA32Cmp8:
      case kIA32Test8:
        return rep == MachineRepresentation::kWord8;
      default:
        break;
    }
    return false;
  }
References v8::internal::IsAnyTagged(), v8::internal::kWord16, v8::internal::kWord32, and v8::internal::kWord8.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare().
GenerateMemoryOperandInputs()
AddressingMode v8::internal::compiler::IA32OperandGenerator::GenerateMemoryOperandInputs (OptionalOpIndex index, int scale, OpIndex base, int32_t displacement, DisplacementMode displacement_mode, InstructionOperand inputs[], size_t * input_count, RegisterMode register_mode = RegisterMode::kRegister) [inline]
Definition at line 408 of file instruction-selector-ia32.cc.
                                                          {
    AddressingMode mode = kMode_MRI;
    if (displacement_mode == kNegativeDisplacement) {
      displacement = base::bits::WraparoundNeg32(displacement);
    }
    if (base.valid()) {
      if (const ConstantOp* constant = Get(base).TryCast<ConstantOp>()) {
        if (constant->kind == ConstantOp::Kind::kWord32) {
          displacement =
              base::bits::WraparoundAdd32(displacement, constant->word32());
          base = OpIndex{};
        } else if (constant->kind == ConstantOp::Kind::kSmi) {
          displacement = base::bits::WraparoundAdd32(
              displacement, static_cast<int32_t>(constant->smi().ptr()));
          base = OpIndex{};
        }
      }
    }
    if (base.valid()) {
      inputs[(*input_count)++] = UseRegisterWithMode(base, register_mode);
      if (index.valid()) {
        DCHECK(scale >= 0 && scale <= 3);
        inputs[(*input_count)++] =
            UseRegisterWithMode(index.value(), register_mode);
        if (displacement != 0) {
          inputs[(*input_count)++] = TempImmediate(displacement);
          static const AddressingMode kMRnI_modes[] = {kMode_MR1I, kMode_MR2I,
                                                       kMode_MR4I, kMode_MR8I};
          mode = kMRnI_modes[scale];
        } else {
          static const AddressingMode kMRn_modes[] = {kMode_MR1, kMode_MR2,
                                                      kMode_MR4, kMode_MR8};
          mode = kMRn_modes[scale];
        }
      } else {
        if (displacement == 0) {
          mode = kMode_MR;
        } else {
          inputs[(*input_count)++] = TempImmediate(displacement);
          mode = kMode_MRI;
        }
      }
    } else {
      DCHECK(scale >= 0 && scale <= 3);
      if (index.valid()) {
        inputs[(*input_count)++] =
            UseRegisterWithMode(index.value(), register_mode);
        if (displacement != 0) {
          inputs[(*input_count)++] = TempImmediate(displacement);
          static const AddressingMode kMnI_modes[] = {kMode_MRI, kMode_M2I,
                                                      kMode_M4I, kMode_M8I};
          mode = kMnI_modes[scale];
        } else {
          static const AddressingMode kMn_modes[] = {kMode_MR, kMode_M2,
                                                     kMode_M4, kMode_M8};
          mode = kMn_modes[scale];
        }
      } else {
        inputs[(*input_count)++] = TempImmediate(displacement);
        return kMode_MI;
      }
    }
    return mode;
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::compiler::kNegativeDisplacement, v8::internal::compiler::turboshaft::ConstantOp::kSmi, v8::internal::compiler::turboshaft::ConstantOp::kWord32, mode(), v8::internal::compiler::turboshaft::OpIndex::valid(), v8::base::bits::WraparoundAdd32(), and v8::base::bits::WraparoundNeg32().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::EmitLea(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon().
GetEffectiveAddressMemoryOperand()
AddressingMode v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand (OpIndex node, InstructionOperand inputs[], size_t * input_count, RegisterMode register_mode = RegisterMode::kRegister) [inline]
Definition at line 477 of file instruction-selector-ia32.cc.
                                                          {
    const Operation& op = this->Get(node);
    if (op.Is<LoadOp>() || op.Is<StoreOp>()) {
      LoadStoreView load_or_store(op);
      if (ExternalReference reference;
          this->MatchExternalConstant(load_or_store.base, &reference) &&
          !load_or_store.index.valid()) {
        if (selector()->CanAddressRelativeToRootsRegister(reference)) {
          const ptrdiff_t delta =
              load_or_store.offset +
              MacroAssemblerBase::RootRegisterOffsetForExternalReference(
                  selector()->isolate(), reference);
          if (is_int32(delta)) {
            inputs[(*input_count)++] =
                TempImmediate(static_cast<int32_t>(delta));
            return kMode_Root;
          }
        }
      }
    }
    auto m = TryMatchBaseWithScaledIndexAndDisplacement(selector(), node);
    DCHECK(m.has_value());
    if (m->base.valid() &&
        this->Get(m->base).template Is<LoadRootRegisterOp>() &&
        !m->index.valid()) {
      DCHECK_EQ(m->scale, 0);
      DCHECK(ValueFitsIntoImmediate(m->displacement));
      inputs[(*input_count)++] =
          UseImmediate(static_cast<int>(m->displacement));
      return kMode_Root;
    } else if (ValueFitsIntoImmediate(m->displacement)) {
      return GenerateMemoryOperandInputs(m->index, m->scale, m->base,
                                         m->displacement, m->displacement_mode,
                                         inputs, input_count, register_mode);
    } else if (!m->base.valid() &&
               m->displacement_mode == kPositiveDisplacement) {
      // The displacement cannot be an immediate, but we can use the
      // displacement as base instead and still benefit from addressing
      // modes for the scale.
      UNIMPLEMENTED();
    } else {
      // TODO(nicohartmann@): Turn this into a `DCHECK` once we have some
      // coverage.
      CHECK_EQ(m->displacement, 0);
      inputs[(*input_count)++] = UseRegisterWithMode(m->base, register_mode);
      inputs[(*input_count)++] = UseRegisterWithMode(m->index, register_mode);
      return kMode_MR1;
    }
  }
References CHECK_EQ, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::kPositiveDisplacement, v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference(), v8::internal::this, v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::compiler::ValueFitsIntoImmediate().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompareWithMemoryOperand(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon().
GetEffectiveIndexOperand()
InstructionOperand v8::internal::compiler::IA32OperandGenerator::GetEffectiveIndexOperand (OpIndex index, AddressingMode * mode) [inline]
Definition at line 530 of file instruction-selector-ia32.cc.
                                                                    {
    if (CanBeImmediate(index)) {
      *mode = kMode_MRI;
      return UseImmediate(index);
    } else {
      *mode = kMode_MR1;
      return UseUniqueRegister(index);
    }
  }
References v8::internal::compiler::CanBeImmediate(), v8::internal::index, and mode().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp().
GetImmediateIntegerValue()
int32_t v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue (OpIndex node) [inline]
Definition at line 390 of file instruction-selector-ia32.cc.
                                                 {
    DCHECK(CanBeImmediate(node));
    const ConstantOp& constant = Get(node).Cast<ConstantOp>();
    if (constant.kind == ConstantOp::Kind::kWord32) return constant.word32();
    if (constant.kind == ConstantOp::Kind::kSmi) {
      return static_cast<int32_t>(constant.smi().ptr());
    }
    DCHECK_EQ(constant.kind, ConstantOp::Kind::kNumber);
    DCHECK_EQ(constant.number().get_bits(), 0);
    return 0;
  }
References v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::Float64::get_bits(), v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kNumber, v8::internal::compiler::turboshaft::ConstantOp::kSmi, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::number(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::compiler::turboshaft::ConstantOp::smi(), and v8::internal::compiler::turboshaft::ConstantOp::word32().
UseByteRegister()
InstructionOperand v8::internal::compiler::IA32OperandGenerator::UseByteRegister (OpIndex node) [inline]
Definition at line 337 of file instruction-selector-ia32.cc.
                                                   {
    // TODO(titzer): encode byte register use constraints.
    return UseFixed(node, edx);
  }
References v8::internal::maglev::UseFixed().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare().
ValueFitsIntoImmediate()
bool v8::internal::compiler::IA32OperandGenerator::ValueFitsIntoImmediate (int64_t value) const [inline]
Definition at line 402 of file instruction-selector-ia32.cc.
                                                   {
    // int32_t min will overflow if displacement mode is kNegativeDisplacement.
    return std::numeric_limits<int32_t>::min() < value &&
           value <= std::numeric_limits<int32_t>::max();
  }
References v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/ia32/instruction-selector-ia32.cc