v8::internal::compiler::TFGraph Class Reference
#include <turbofan-graph.h>
Classes
class SubgraphScope
Public Member Functions
TFGraph (Zone *zone)
TFGraph (const TFGraph &)=delete
TFGraph & operator= (const TFGraph &)=delete
Node * NewNodeUnchecked (const Operator *op, int input_count, Node *const *inputs, bool incomplete=false)
Node * NewNode (const Operator *op, int input_count, Node *const *inputs, bool incomplete=false)
template<typename... Nodes>
Node * NewNode (const Operator *op, Nodes... nodes) requires(std
Node * CloneNode (const Node *node)
Zone * zone () const
Node * start () const
Node * end () const
void SetStart (Node *start)
void SetEnd (Node *end)
size_t NodeCount () const
void Decorate (Node *node)
void AddDecorator (GraphDecorator *decorator)
void RemoveDecorator (GraphDecorator *decorator)
void Print () const
bool HasSimd () const
void SetSimd (bool has_simd)
void RecordSimdStore (Node *store)
ZoneVector< Node * > const & GetSimdStoreNodes ()
Private Member Functions
NodeId NextNodeId ()
Private Attributes
Zone *const zone_
Node * start_
Node * end_
Mark mark_max_
NodeId next_node_id_
ZoneVector< GraphDecorator * > decorators_
bool has_simd_
ZoneVector< Node * > simd_stores_
Friends
class NodeMarkerBase
Detailed Description
Definition at line 32 of file turbofan-graph.h.
Constructor & Destructor Documentation
TFGraph() [1/2]
v8::internal::compiler::TFGraph::TFGraph (Zone * zone) [explicit]
Definition at line 17 of file turbofan-graph.cc.
    : zone_(zone),
      start_(nullptr),
      end_(nullptr),
      mark_max_(0),
      next_node_id_(0),
      decorators_(zone),
      has_simd_(false),
      simd_stores_(zone) {}
TFGraph() [2/2]
v8::internal::compiler::TFGraph::TFGraph (const TFGraph &) [delete]
Member Function Documentation
AddDecorator()
void v8::internal::compiler::TFGraph::AddDecorator (GraphDecorator * decorator)
Definition at line 33 of file turbofan-graph.cc.
                                                    {
  decorators_.push_back(decorator);
}
References decorators_.
Referenced by v8::internal::compiler::SourcePositionTable::AddDecorator(), v8::internal::compiler::NodeOriginTable::AddDecorator(), and v8::internal::compiler::Typer::Typer().
CloneNode()
Node * v8::internal::compiler::TFGraph::CloneNode (const Node * node)
Definition at line 58 of file turbofan-graph.cc.
                                         {
  DCHECK_NOT_NULL(node);
  Node* const clone = Node::Clone(zone(), NextNodeId(), node);
  Decorate(clone);
  return clone;
}
References v8::internal::compiler::Node::Clone(), DCHECK_NOT_NULL, Decorate(), NextNodeId(), and zone().
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), v8::internal::compiler::JSCallReducerAssembler::CopyNode(), v8::internal::compiler::JSInliningHeuristic::DuplicateFrameStateAndRename(), v8::internal::compiler::JSInliningHeuristic::DuplicateStateValuesAndRename(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded().
Decorate()
void v8::internal::compiler::TFGraph::Decorate (Node * node)
Definition at line 27 of file turbofan-graph.cc.
                                 {
  for (GraphDecorator* const decorator : decorators_) {
    decorator->Decorate(node);
  }
}
References decorators_.
Referenced by CloneNode(), and NewNodeUnchecked().
end()
Node* v8::internal::compiler::TFGraph::end () const [inline]
Definition at line 83 of file turbofan-graph.h.
{ return end_; }
Referenced by v8::internal::compiler::GraphAssembler::ConnectUnreachableToEnd(), v8::internal::compiler::RepresentationSelector::GenerateTraversal(), v8::internal::compiler::CFGBuilder::IsFinalMerge(), v8::internal::compiler::operator<<(), v8::internal::compiler::BitcastElider::ProcessGraph(), v8::internal::compiler::EffectGraphReducer::ReduceGraph(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::PrepareUsesVisitor::Run(), and v8::internal::compiler::ControlEquivalence::VisitMid().
GetSimdStoreNodes()
ZoneVector< Node * > const & v8::internal::compiler::TFGraph::GetSimdStoreNodes ()
Definition at line 76 of file turbofan-graph.cc.
{ return simd_stores_; }
References simd_stores_.
Referenced by v8::internal::compiler::Revectorizer::CollectSeeds(), and v8::internal::compiler::Revectorizer::TryRevectorize().
HasSimd()
bool v8::internal::compiler::TFGraph::HasSimd () const [inline]
Definition at line 97 of file turbofan-graph.h.
{ return has_simd_; }
NewNode() [1/2]
Node * v8::internal::compiler::TFGraph::NewNode (const Operator * op, int input_count, Node *const * inputs, bool incomplete = false)
Definition at line 43 of file turbofan-graph.cc.
                                        {
  Node* node = NewNodeUnchecked(op, input_count, inputs, incomplete);
  Verifier::VerifyNode(node);
  return node;
}
References v8::internal::compiler::turboshaft::detail::input_count(), NewNodeUnchecked(), and v8::internal::compiler::Verifier::VerifyNode().
Referenced by v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::compiler::CsaLoadElimination::AssertUnreachable(), v8::internal::compiler::WasmGraphAssembler::Branch(), v8::internal::compiler::GraphAssembler::BranchImpl(), v8::internal::compiler::WasmGraphBuilder::BuildCallNode(), v8::internal::compiler::JSNativeContextSpecialization::BuildCheckEqualsName(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckMaps(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckNumber(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckNumberFitsInt32(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckSmi(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckValue(), v8::internal::compiler::JSTypeHintLowering::BuildDeoptIfFeedbackIsInsufficient(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::JSNativeContextSpecialization::BuildIndexedStringLoad(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildLoadPrototypeFromObject(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::WasmGraphBuilder::BuildSafeStore(), v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation(), v8::internal::compiler::WasmGraphBuilder::BuildWasmCall(), v8::internal::compiler::MachineOperatorReducer::ChangeInt32ToInt64(), v8::internal::compiler::RepresentationSelector::ChangeToDeadValue(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::JSCallReducer::CheckArrayLength(), v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSCallReducer::CheckIfElementsKind(), v8::internal::compiler::JSBinopReduction::CheckInputsToInternalizedString(), v8::internal::compiler::JSBinopReduction::CheckInputsToReceiver(), v8::internal::compiler::JSBinopReduction::CheckInputsToReceiverOrNullOrUndefined(), v8::internal::compiler::JSBinopReduction::CheckInputsToString(), v8::internal::compiler::JSBinopReduction::CheckInputsToStringOrOddball(), v8::internal::compiler::JSBinopReduction::CheckInputsToStringOrStringWrapper(), v8::internal::compiler::JSBinopReduction::CheckInputsToSymbol(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToReceiver(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToReceiverOrNullOrUndefined(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToSymbol(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint(), v8::internal::compiler::GraphAssembler::ConnectUnreachableToEnd(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::JSCallReducer::ConvertHoleToUndefined(), v8::internal::compiler::JSBinopReduction::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::TypedOptimization::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::JSBinopReduction::ConvertToUI32(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::JSCallReducer::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::BytecodeGraphBuilder::CreateGraph(), v8::internal::compiler::RawMachineAssembler::CreateNodeFromPredecessors(), v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), v8::internal::compiler::DeadCodeElimination::DeadValue(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::Diamond::Diamond(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::Diamond::EffectPhi(), v8::internal::compiler::MachineGraph::ExternalConstant(), v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::MachineGraph::Float32Constant(), v8::internal::compiler::MachineOperatorReducer::Float32Constant(), v8::internal::compiler::MachineGraph::Float64Constant(), v8::internal::compiler::MachineOperatorReducer::Float64Mul(), v8::internal::compiler::MachineOperatorReducer::Float64PowHalf(), v8::internal::compiler::SimplifiedLowering::Float64Round(), v8::internal::compiler::SimplifiedLowering::Float64Sign(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::StateValuesCache::GetEmptyStateValues(), v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::StateValuesCache::GetValuesNodeFromCache(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::compiler::JSGraph::HeapConstantHole(), v8::internal::compiler::JSGraph::HeapConstantMaybeHole(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::compiler::JSNativeContextSpecialization::InlineApiCall(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertySetterCall(), v8::internal::compiler::RepresentationChanger::InsertChangeBitToTagged(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat16RawBitsToFloat64Fallback(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat32ToFloat64(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat64ToInt32(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat64ToUint32(), v8::internal::compiler::RepresentationChanger::InsertChangeInt32ToFloat64(), v8::internal::compiler::RepresentationChanger::InsertChangeTaggedSignedToInt32(), v8::internal::compiler::RepresentationChanger::InsertChangeTaggedToFloat64(), v8::internal::compiler::RepresentationChanger::InsertChangeUint32ToFloat64(), v8::internal::compiler::RepresentationChanger::InsertConversion(), v8::internal::compiler::MapInference::InsertMapChecks(), v8::internal::compiler::RepresentationSelector::InsertSemanticsHintForVerifier(), v8::internal::compiler::RepresentationChanger::InsertTruncateFloat64ToFloat16RawBitsFallback(), v8::internal::compiler::RepresentationChanger::InsertTruncateInt64ToInt32(), v8::internal::compiler::RepresentationChanger::InsertTypeOverrideForVerifier(), v8::internal::compiler::RepresentationSelector::InsertTypeOverrideForVerifier(), v8::internal::compiler::RepresentationChanger::InsertUnconditionalDeopt(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::SimplifiedLowering::Int32Abs(), v8::internal::compiler::MachineOperatorReducer::Int32Add(), v8::internal::compiler::SimplifiedLowering::Int32Div(), v8::internal::compiler::MachineOperatorReducer::Int32Div(), v8::internal::compiler::SimplifiedLowering::Int32Mod(), v8::internal::compiler::MachineOperatorReducer::Int32Mul(), v8::internal::compiler::SimplifiedLowering::Int32Sign(), v8::internal::compiler::MachineOperatorReducer::Int32Sub(), v8::internal::compiler::MachineOperatorReducer::Int64Add(), v8::internal::compiler::MachineOperatorReducer::Int64Constant(), v8::internal::compiler::MachineOperatorReducer::Int64Div(), v8::internal::compiler::MachineOperatorReducer::Int64Mul(), v8::internal::compiler::MachineOperatorReducer::Int64Sub(), v8::internal::compiler::JSCallReducer::LoadReceiverElementsKind(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupCheck(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::LowerCompareMapsWithoutLoad(), v8::internal::compiler::RawMachineAssembler::MakePhiBinary(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::GraphAssembler::MergeState(), v8::internal::compiler::JSGraph::NumberConstant(), v8::internal::compiler::WasmGraphAssembler::NumberConstant(), v8::internal::compiler::EscapeAnalysisReducer::ObjectIdNode(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::WasmGraphBuilder::Param(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::Diamond::Phi(), v8::internal::compiler::MachineGraph::PointerConstant(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceBooleanConstructor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSIntrinsicLowering::ReduceCheckTurboshaftTypeOf(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::JSIntrinsicLowering::ReduceCreateJSGeneratorObject(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceDateNow(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::JSIntrinsicLowering::ReduceDeoptimizeNow(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSIntrinsicLowering::ReduceIsInstanceType(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContinuation(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadModule(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule(), v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::TypedOptimization::ReduceNumberFloor(), v8::internal::compiler::JSCallReducer::ReduceNumberIsFinite(), v8::internal::compiler::JSCallReducer::ReduceNumberIsInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberIsNaN(), v8::internal::compiler::JSCallReducer::ReduceNumberIsSafeInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectIs(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberAdd(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberBinop(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberComparison(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::TypedOptimization::ReduceStringComparison(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSTypeHintLowering::ReduceToNumberOperation(), v8::internal::compiler::BranchElimination::ReduceTrapConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceTrapConditional(), v8::internal::compiler::JSIntrinsicLowering::ReduceTurbofanStaticAssert(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation(), v8::internal::compiler::JSIntrinsicLowering::ReduceVerifyType(), v8::internal::compiler::MachineGraph::RelocatableInt32Constant(), v8::internal::compiler::MachineGraph::RelocatableInt64Constant(), v8::internal::compiler::WasmGraphBuilder::Return(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::compiler::WasmGraphBuilder::Start(), v8::internal::compiler::AllocationBuilder::Store(), v8::internal::compiler::RawMachineAssembler::Switch(), v8::internal::compiler::MachineGraph::TaggedIndexConstant(), v8::internal::compiler::WasmGraphBuilder::TerminateThrow(), v8::internal::compiler::CsaLoadElimination::TruncateAndExtend(), v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType(), v8::internal::compiler::MachineOperatorReducer::TruncateInt64ToInt32(), v8::internal::compiler::JSGraph::TrustedHeapConstant(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::PropertyAccessBuilder::TryBuildNumberCheck(), v8::internal::compiler::PropertyAccessBuilder::TryBuildStringCheck(), v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::SimplifiedLowering::Uint32Div(), v8::internal::compiler::MachineOperatorReducer::Uint32Div(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), v8::internal::compiler::MachineOperatorReducer::Uint64Div(), v8::internal::compiler::MachineGraph::UniqueInt32Constant(), v8::internal::compiler::MachineGraph::UniqueInt64Constant(), v8::internal::compiler::JSTypedLowering::UnwrapStringWrapper(), v8::internal::compiler::BytecodeGraphBuilder::Environment::UpdateStateValues(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::MachineOperatorReducer::Word32And(), v8::internal::compiler::MachineOperatorReducer::Word32Equal(), v8::internal::compiler::MachineOperatorReducer::Word32Sar(), v8::internal::compiler::MachineOperatorReducer::Word32Shr(), v8::internal::compiler::MachineOperatorReducer::Word64And(), v8::internal::compiler::MachineOperatorReducer::Word64Equal(), v8::internal::compiler::MachineOperatorReducer::Word64Sar(), and v8::internal::compiler::MachineOperatorReducer::Word64Shr().
NewNode() [2/2]
template<typename... Nodes>
Node* v8::internal::compiler::TFGraph::NewNode (const Operator * op, Nodes... nodes) [inline]
Definition at line 70 of file turbofan-graph.h.
  {
    std::array<Node*, sizeof...(nodes)> nodes_arr{
        {static_cast<Node*>(nodes)...}};
    return NewNode(op, nodes_arr.size(), nodes_arr.data());
  }
NewNodeUnchecked()
Node * v8::internal::compiler::TFGraph::NewNodeUnchecked (const Operator * op, int input_count, Node *const * inputs, bool incomplete = false)
Definition at line 50 of file turbofan-graph.cc.
                                                                      {
  Node* const node =
      Node::New(zone(), NextNodeId(), op, input_count, inputs, incomplete);
  Decorate(node);
  return node;
}
References Decorate(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::New(), NextNodeId(), and zone().
Referenced by v8::internal::compiler::RawMachineAssembler::MakeNode(), and NewNode().
NextNodeId()
NodeId v8::internal::compiler::TFGraph::NextNodeId () [inline], [private]
Definition at line 65 of file turbofan-graph.cc.
                           {
  // A node's id is internally stored in a bit field using fewer bits than
  // NodeId (see Node::IdField). Hence the addition below won't ever overflow.
  DCHECK_LT(next_node_id_, std::numeric_limits<NodeId>::max());
  return next_node_id_++;
}
References DCHECK_LT, and next_node_id_.
Referenced by CloneNode(), and NewNodeUnchecked().
NodeCount()
size_t v8::internal::compiler::TFGraph::NodeCount () const [inline]
Definition at line 88 of file turbofan-graph.h.
{ return next_node_id_; }
Referenced by v8::internal::compiler::JSCallReducer::Finalize(), v8::internal::compiler::RepresentationSelector::GenerateTraversal(), v8::internal::compiler::GraphTrimmer::GraphTrimmer(), v8::internal::compiler::operator<<(), and v8::internal::compiler::GraphReducer::ReduceTop().
operator=()
TFGraph& v8::internal::compiler::TFGraph::operator= (const TFGraph &) [delete]
Print()
void v8::internal::compiler::TFGraph::Print () const
Definition at line 72 of file turbofan-graph.cc.
{ StdoutStream{} << AsRPO(*this); }
RecordSimdStore()
void v8::internal::compiler::TFGraph::RecordSimdStore (Node * store)
Definition at line 74 of file turbofan-graph.cc.
{ simd_stores_.push_back(store); }
References v8::internal::ZoneVector< T >::push_back(), simd_stores_, and store().
RemoveDecorator()
void v8::internal::compiler::TFGraph::RemoveDecorator (GraphDecorator * decorator)
Definition at line 37 of file turbofan-graph.cc.
                                                       {
  auto const it = std::find(decorators_.begin(), decorators_.end(), decorator);
  DCHECK(it != decorators_.end());
  decorators_.erase(it);
}
References v8::internal::DCHECK(), and decorators_.
Referenced by v8::internal::compiler::SourcePositionTable::RemoveDecorator(), v8::internal::compiler::NodeOriginTable::RemoveDecorator(), and v8::internal::compiler::Typer::~Typer().
SetEnd()
void v8::internal::compiler::TFGraph::SetEnd (Node * end) [inline]
Definition at line 86 of file turbofan-graph.h.
{ end_ = end; }
References v8::internal::compiler::end().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::CreateGraph(), v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), v8::internal::compiler::GraphReducer::Replace(), and v8::internal::compiler::WasmGraphBuilder::Start().
SetSimd()
void v8::internal::compiler::TFGraph::SetSimd (bool has_simd) [inline]
Definition at line 98 of file turbofan-graph.h.
{ has_simd_ = has_simd; }
SetStart()
void v8::internal::compiler::TFGraph::SetStart (Node * start) [inline]
Definition at line 85 of file turbofan-graph.h.
{ start_ = start; }
Referenced by v8::internal::compiler::BytecodeGraphBuilder::CreateGraph(), v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), v8::internal::compiler::GraphReducer::Replace(), and v8::internal::compiler::WasmGraphBuilder::Start().
start()
Node* v8::internal::compiler::TFGraph::start () const [inline]
Definition at line 82 of file turbofan-graph.h.
{ return start_; }
Referenced by v8::internal::compiler::LinearScheduler::ComputeControlLevel(), v8::internal::compiler::Diamond::Diamond(), v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues(), v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::RawMachineAssembler::Phi(), v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), and v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell().
zone()
Zone* v8::internal::compiler::TFGraph::zone () const [inline]
Definition at line 81 of file turbofan-graph.h.
{ return zone_; }
Referenced by v8::internal::compiler::SourcePositionTable::AddDecorator(), v8::internal::compiler::NodeOriginTable::AddDecorator(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), CloneNode(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::WasmGraphBuilder::graph_zone(), v8::internal::compiler::BytecodeGraphBuilder::graph_zone(), v8::internal::compiler::MemoryLowering::graph_zone(), v8::internal::compiler::SimplifiedLoweringVerifier::graph_zone(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), NewNodeUnchecked(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType(), v8::internal::compiler::JSBinopReduction::zone(), and v8::internal::compiler::TypeNarrowingReducer::zone().
Friends And Related Function Documentation
NodeMarkerBase
friend class NodeMarkerBase [friend]
Definition at line 104 of file turbofan-graph.h.
Member Data Documentation
decorators_
ZoneVector<GraphDecorator*> v8::internal::compiler::TFGraph::decorators_ [private]
Definition at line 113 of file turbofan-graph.h.
Referenced by AddDecorator(), Decorate(), and RemoveDecorator().
end_
Node* v8::internal::compiler::TFGraph::end_ [private]
Definition at line 110 of file turbofan-graph.h.
has_simd_
bool v8::internal::compiler::TFGraph::has_simd_ [private]
Definition at line 114 of file turbofan-graph.h.
mark_max_
Mark v8::internal::compiler::TFGraph::mark_max_ [private]
Definition at line 111 of file turbofan-graph.h.
next_node_id_
NodeId v8::internal::compiler::TFGraph::next_node_id_ [private]
Definition at line 112 of file turbofan-graph.h.
Referenced by NextNodeId().
simd_stores_
ZoneVector<Node*> v8::internal::compiler::TFGraph::simd_stores_ [private]
Definition at line 115 of file turbofan-graph.h.
Referenced by GetSimdStoreNodes(), and RecordSimdStore().
start_
Node* v8::internal::compiler::TFGraph::start_ [private]
Definition at line 109 of file turbofan-graph.h.
zone_
Zone* const v8::internal::compiler::TFGraph::zone_ [private]
Definition at line 108 of file turbofan-graph.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turbofan-graph.h
/mnt/V8SourceCode/src/compiler/turbofan-graph.cc