v8::internal::TransitionArray Class Reference
#include <transitions.h>
Public Member Functions
int number_of_transitions () const
Tagged< WeakFixedArray > GetPrototypeTransitions ()
bool HasPrototypeTransitions ()
void SetKey (int transition_number, Tagged< Name > value)
Tagged< Name > GetKey (int transition_number)
HeapObjectSlot GetKeySlot (int transition_number)
Tagged< Map > GetTarget (int transition_number)
void SetRawTarget (int transition_number, Tagged< MaybeObject > target)
Tagged< MaybeObject > GetRawTarget (int transition_number)
HeapObjectSlot GetTargetSlot (int transition_number)
bool GetTargetIfExists (int transition_number, Isolate *isolate, Tagged< Map > *target)
V8_EXPORT_PRIVATE void Sort ()
void PrintInternal (std::ostream &os)
int SearchNameForTesting (Tagged< Name > name, int *out_insertion_index=nullptr)
Tagged< Map > SearchAndGetTargetForTesting (PropertyKind kind, Tagged< Name > name, PropertyAttributes attributes)
bool HasSideStepTransitions ()
Static Public Member Functions
static int ToKeyIndex (int transition_number)
static int ToTargetIndex (int transition_number)
static void CreateSideStepTransitions (Isolate *isolate, DirectHandle< TransitionArray > transitions)
Static Public Attributes
static constexpr int kNotFound = -1
static const int kPrototypeTransitionsIndex = 0
static const int kSideStepTransitionsIndex = 1
static const int kTransitionLengthIndex = 2
static const int kFirstIndex = 3
static const int kEntryKeyIndex = 0
static const int kEntryTargetIndex = 1
static const int kEntrySize = 2
Private Member Functions
void SetNumberOfTransitions (int number_of_transitions)
int Capacity ()
void SetPrototypeTransitions (Tagged< WeakFixedArray > prototype_transitions)
int Search (PropertyKind kind, Tagged< Name > name, PropertyAttributes attributes, int *out_insertion_index=nullptr)
V8_EXPORT_PRIVATE Tagged< Map > SearchAndGetTarget (PropertyKind kind, Tagged< Name > name, PropertyAttributes attributes)
int SearchSpecial (Tagged< Symbol > symbol, bool concurrent_search=false, int *out_insertion_index=nullptr)
int SearchName (Tagged< Name > name, bool concurrent_search=false, int *out_insertion_index=nullptr)
int SearchDetails (int transition, PropertyKind kind, PropertyAttributes attributes, int *out_insertion_index)
Tagged< Map > SearchDetailsAndGetTarget (int transition, PropertyKind kind, PropertyAttributes attributes)
int LinearSearchName (Tagged< Name > name, int *out_insertion_index)
int BinarySearchName (Tagged< Name > name, int *out_insertion_index)
void ForEachTransitionTo (Tagged< Name > name, const ForEachTransitionCallback &callback)
void Set (int transition_number, Tagged< Name > key, Tagged< MaybeObject > target)
Tagged< WeakFixedArray > GetSideStepTransitions ()
void SetSideStepTransitions (Tagged< WeakFixedArray > transitions)
Static Private Member Functions
static int NumberOfPrototypeTransitions (Tagged< WeakFixedArray > proto_transitions)
static void SetNumberOfPrototypeTransitions (Tagged< WeakFixedArray > proto_transitions, int value)
static int LengthFor (int number_of_transitions)
static bool CompactPrototypeTransitionArray (Isolate *isolate, Tagged< WeakFixedArray > array)
static DirectHandle< WeakFixedArray > GrowPrototypeTransitionArray (DirectHandle< WeakFixedArray > array, int new_capacity, Isolate *isolate)
static int CompareKeys (Tagged< Name > key1, uint32_t hash1, PropertyKind kind1, PropertyAttributes attributes1, Tagged< Name > key2, uint32_t hash2, PropertyKind kind2, PropertyAttributes attributes2)
static int CompareNames (Tagged< Name > key1, uint32_t hash1, Tagged< Name > key2, uint32_t hash2)
static int CompareDetails (PropertyKind kind1, PropertyAttributes attributes1, PropertyKind kind2, PropertyAttributes attributes2)
Static Private Attributes
static const int kProtoTransitionHeaderSize = 1
static const int kMaxCachedPrototypeTransitions = 256
static const int kProtoTransitionNumberOfEntriesOffset = 0
Friends
class Factory
class MarkCompactCollector
class TransitionsAccessor
Additional Inherited Members
Detailed Description
Definition at line 317 of file transitions.h.
Member Function Documentation
BinarySearchName()
int v8::internal::TransitionArray::BinarySearchName (Tagged< Name > name, int * out_insertion_index) [inline], [private]
Definition at line 284 of file transitions-inl.h.
                                                                {
  int end = number_of_transitions();
  uint32_t hash = name->hash();
  // Find the first index whose key's hash is greater-than-or-equal-to the
  // search hash.
  int i = *std::ranges::lower_bound(std::views::iota(0, end), hash,
                                    std::less<>(), [&](int i) {
                                      Tagged<Name> entry = GetKey(i);
                                      return entry->hash();
                                    });
  // There may have been hash collisions, so search for the name from the first
  // index until the first non-matching hash.
  for (; i < end; ++i) {
    Tagged<Name> entry = GetKey(i);
    if (entry == name) {
      return i;
    }
    uint32_t entry_hash = entry->hash();
    if (entry_hash != hash) {
      if (out_insertion_index != nullptr) {
        *out_insertion_index = i + (entry_hash > hash ? 0 : 1);
      }
      return kNotFound;
    }
  }
  if (out_insertion_index != nullptr) {
    *out_insertion_index = end;
  }
  return kNotFound;
}
References v8::internal::compiler::end(), GetKey(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kNotFound, v8::internal::name, and number_of_transitions().
Referenced by SearchName().
Capacity()
int v8::internal::TransitionArray::Capacity () [inline], [private]
Definition at line 460 of file transitions-inl.h.
                              {
  if (length() <= kFirstIndex) return 0;
  return (length() - kFirstIndex) / kEntrySize;
}
References kEntrySize, kFirstIndex, and v8::internal::length.
Referenced by SetNumberOfTransitions().
CompactPrototypeTransitionArray()
bool v8::internal::TransitionArray::CompactPrototypeTransitionArray (Isolate * isolate, Tagged< WeakFixedArray > array) [static], [private]
Definition at line 342 of file transitions.cc.
                                                    {
  const int header = kProtoTransitionHeaderSize;
  int number_of_transitions = NumberOfPrototypeTransitions(array);
  if (number_of_transitions == 0) {
    // Empty array cannot be compacted.
    return false;
  }
  int new_number_of_transitions = 0;
  for (int i = 0; i < number_of_transitions; i++) {
    Tagged<MaybeObject> target = array->get(header + i);
    DCHECK(target.IsCleared() ||
           (target.IsWeak() && IsMap(target.GetHeapObject())));
    if (!target.IsCleared()) {
      if (new_number_of_transitions != i) {
        array->set(header + new_number_of_transitions, target);
      }
      new_number_of_transitions++;
    }
  }
  // Fill slots that became free with undefined value.
  Tagged<MaybeObject> undefined = *isolate->factory()->undefined_value();
  for (int i = new_number_of_transitions; i < number_of_transitions; i++) {
    array->set(header + i, undefined);
  }
  if (number_of_transitions != new_number_of_transitions) {
    SetNumberOfPrototypeTransitions(array, new_number_of_transitions);
  }
  return new_number_of_transitions < number_of_transitions;
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), kProtoTransitionHeaderSize, number_of_transitions(), NumberOfPrototypeTransitions(), SetNumberOfPrototypeTransitions(), and v8::internal::undefined.
Referenced by v8::internal::TransitionsAccessor::PutPrototypeTransition().
CompareDetails()
int v8::internal::TransitionArray::CompareDetails (PropertyKind kind1, PropertyAttributes attributes1, PropertyKind kind2, PropertyAttributes attributes2) [inline], [static], [private]
Definition at line 438 of file transitions-inl.h.
                                                                    {
  if (kind1 != kind2) {
    return static_cast<int>(kind1) < static_cast<int>(kind2) ? -1 : 1;
  }
  if (attributes1 != attributes2) {
    return static_cast<int>(attributes1) < static_cast<int>(attributes2) ? -1
                                                                         : 1;
  }
  return 0;
}
Referenced by CompareKeys(), SearchDetails(), and SearchDetailsAndGetTarget().
CompareKeys()
int v8::internal::TransitionArray::CompareKeys (Tagged< Name > key1, uint32_t hash1, PropertyKind kind1, PropertyAttributes attributes1, Tagged< Name > key2, uint32_t hash2, PropertyKind kind2, PropertyAttributes attributes2) [inline], [static], [private]
Definition at line 416 of file transitions-inl.h.
                                                                 {
  int cmp = CompareNames(key1, hash1, key2, hash2);
  if (cmp != 0) return cmp;
  return CompareDetails(kind1, attributes1, kind2, attributes2);
}
References CompareDetails(), and CompareNames().
Referenced by Sort().
CompareNames()
int v8::internal::TransitionArray::CompareNames (Tagged< Name > key1, uint32_t hash1, Tagged< Name > key2, uint32_t hash2) [inline], [static], [private]
Definition at line 428 of file transitions-inl.h.
                                                                     {
  if (key1 != key2) {
    // In case of hash collisions key1 is always "less" than key2.
    return hash1 <= hash2 ? -1 : 1;
  }
  return 0;
}
Referenced by CompareKeys().
CreateSideStepTransitions()
void v8::internal::TransitionArray::CreateSideStepTransitions (Isolate * isolate, DirectHandle< TransitionArray > transitions) [static]
Definition at line 856 of file transitions.cc.
                                                                 {
  DCHECK(!transitions->HasSideStepTransitions()); // Callers must check first.
  DirectHandle<WeakFixedArray> result = WeakFixedArray::New(
      isolate, SideStepTransition::kSize, AllocationType::kYoung,
      direct_handle(SideStepTransition::Empty, isolate));
  transitions->SetSideStepTransitions(*result);
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::SideStepTransition::Empty, v8::internal::SideStepTransition::kSize, v8::internal::kYoung, v8::internal::WeakFixedArray::New(), and v8::base::internal::result.
Referenced by v8::internal::TransitionsAccessor::EnsureHasSideStepTransitions().
ForEachTransitionTo()
void v8::internal::TransitionArray::ForEachTransitionTo (Tagged< Name > name, const ForEachTransitionCallback & callback) [private]
Definition at line 763 of file transitions.cc.
                                                                  {
  int transition = SearchName(name);
  if (transition == kNotFound) return;
  int nof_transitions = number_of_transitions();
  DCHECK(transition < nof_transitions);
  Tagged<Name> key = GetKey(transition);
  for (; transition < nof_transitions && GetKey(transition) == key;
       transition++) {
    Tagged<Map> target = GetTarget(transition);
    callback(target);
  }
}
References v8::internal::DCHECK(), GetKey(), GetTarget(), v8::internal::key, kNotFound, v8::internal::name, number_of_transitions(), and SearchName().
GetKey()
Tagged< Name > v8::internal::TransitionArray::GetKey (int transition_number) [inline]
Definition at line 129 of file transitions-inl.h.
                                                          {
  DCHECK(transition_number < number_of_transitions());
  return Cast<Name>(
      get(ToKeyIndex(transition_number)).GetHeapObjectAssumeStrong());
}
References v8::internal::DCHECK(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::get(), number_of_transitions(), and ToKeyIndex().
Referenced by BinarySearchName(), ForEachTransitionTo(), LinearSearchName(), SearchDetails(), SearchDetailsAndGetTarget(), and Sort().
GetKeySlot()
HeapObjectSlot v8::internal::TransitionArray::GetKeySlot (int transition_number) [inline]
Definition at line 110 of file transitions-inl.h.
                                                                {
  DCHECK(transition_number < number_of_transitions());
  return HeapObjectSlot(RawFieldOfElementAt(ToKeyIndex(transition_number)));
}
References v8::internal::DCHECK(), number_of_transitions(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::RawFieldOfElementAt(), and ToKeyIndex().
GetPrototypeTransitions()
Tagged< WeakFixedArray > v8::internal::TransitionArray::GetPrototypeTransitions () [inline]
Definition at line 49 of file transitions-inl.h.
                                                                {
  DCHECK(HasPrototypeTransitions()); // Callers must check first.
  Tagged<Object> prototype_transitions =
      get(kPrototypeTransitionsIndex, kAcquireLoad).GetHeapObjectAssumeStrong();
  return Cast<WeakFixedArray>(prototype_transitions);
}
References v8::internal::DCHECK(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::get(), HasPrototypeTransitions(), v8::kAcquireLoad, and kPrototypeTransitionsIndex.
GetRawTarget()
Tagged< MaybeObject > v8::internal::TransitionArray::GetRawTarget (int transition_number) [inline]
Definition at line 191 of file transitions-inl.h.
                                                                       {
  DCHECK(transition_number < number_of_transitions());
  return get(ToTargetIndex(transition_number));
}
References v8::internal::DCHECK(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::get(), number_of_transitions(), and ToTargetIndex().
Referenced by GetTarget(), GetTargetIfExists(), and Sort().
GetSideStepTransitions()
Tagged< WeakFixedArray > v8::internal::TransitionArray::GetSideStepTransitions () [inline], [private]
Definition at line 97 of file transitions-inl.h.
                                                               {
  DCHECK(HasSideStepTransitions()); // Callers must check first.
  Tagged<Object> transitions =
      get(kSideStepTransitionsIndex).GetHeapObjectAssumeStrong();
  return Cast<WeakFixedArray>(transitions);
}
References v8::internal::DCHECK(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::get(), HasSideStepTransitions(), and kSideStepTransitionsIndex.
GetTarget()
Tagged< Map > v8::internal::TransitionArray::GetTarget (int transition_number) [inline]
Definition at line 196 of file transitions-inl.h.
                                                            {
  Tagged<MaybeObject> raw = GetRawTarget(transition_number);
  return TransitionsAccessor::GetTargetFromRaw(raw);
}
References GetRawTarget(), and v8::internal::TransitionsAccessor::GetTargetFromRaw().
Referenced by ForEachTransitionTo(), SearchDetails(), and SearchDetailsAndGetTarget().
GetTargetIfExists()
bool v8::internal::TransitionArray::GetTargetIfExists (int transition_number, Isolate * isolate, Tagged< Map > * target) [inline]
Definition at line 225 of file transitions-inl.h.
                                                             {
  Tagged<MaybeObject> raw = GetRawTarget(transition_number);
  Tagged<HeapObject> heap_object;
  // If the raw target is a Smi, then this TransitionArray is in the process of
  // being deserialized, and doesn't yet have an initialized entry for this
  // transition.
  if (raw.IsSmi()) {
    DCHECK(isolate->has_active_deserializer());
    DCHECK_EQ(raw.ToSmi(), Smi::uninitialized_deserialization_value());
    return false;
  }
  if (raw.GetHeapObjectIfStrong(&heap_object) &&
      IsUndefined(heap_object, isolate)) {
    return false;
  }
  *target = TransitionsAccessor::GetTargetFromRaw(raw);
  return true;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfStrong(), GetRawTarget(), v8::internal::TransitionsAccessor::GetTargetFromRaw(), v8::internal::Isolate::has_active_deserializer(), v8::internal::Tagged< HeapObject >::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi(), and v8::internal::Smi::uninitialized_deserialization_value().
GetTargetSlot()
HeapObjectSlot v8::internal::TransitionArray::GetTargetSlot (int transition_number) [inline]
Definition at line 157 of file transitions-inl.h.
                                                                   {
  DCHECK(transition_number < number_of_transitions());
  return HeapObjectSlot(RawFieldOfElementAt(ToTargetIndex(transition_number)));
}
References v8::internal::DCHECK(), number_of_transitions(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::RawFieldOfElementAt(), and ToTargetIndex().
GrowPrototypeTransitionArray()
DirectHandle< WeakFixedArray > v8::internal::TransitionArray::GrowPrototypeTransitionArray (DirectHandle< WeakFixedArray > array, int new_capacity, Isolate * isolate) [static], [private]
Definition at line 374 of file transitions.cc.
                                                                            {
  // Grow array by factor 2 up to MaxCachedPrototypeTransitions.
  int capacity = array->length() - kProtoTransitionHeaderSize;
  new_capacity = std::min({kMaxCachedPrototypeTransitions, new_capacity});
  DCHECK_GT(new_capacity, capacity);
  int grow_by = new_capacity - capacity;
  DirectHandle<WeakFixedArray> new_array =
      isolate->factory()->CopyWeakFixedArrayAndGrow(array, grow_by);
  if (capacity < 0) {
    // There was no prototype transitions array before, so the size
    // couldn't be copied. Initialize it explicitly.
    SetNumberOfPrototypeTransitions(*new_array, 0);
  }
  return new_array;
}
References v8::internal::Factory::CopyWeakFixedArrayAndGrow(), DCHECK_GT, v8::internal::Isolate::factory(), kMaxCachedPrototypeTransitions, kProtoTransitionHeaderSize, and SetNumberOfPrototypeTransitions().
Referenced by v8::internal::TransitionsAccessor::PutPrototypeTransition().
HasPrototypeTransitions()
bool v8::internal::TransitionArray::HasPrototypeTransitions () [inline]
Definition at line 45 of file transitions-inl.h.
                                              {
  return get(kPrototypeTransitionsIndex, kAcquireLoad) != Smi::zero();
}
References v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::get(), v8::kAcquireLoad, kPrototypeTransitionsIndex, and v8::internal::Smi::zero().
Referenced by GetPrototypeTransitions().
HasSideStepTransitions()
bool v8::internal::TransitionArray::HasSideStepTransitions () [inline]
Definition at line 56 of file transitions-inl.h.
                                             {
  return get(kSideStepTransitionsIndex) != Smi::zero();
}
References v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::get(), kSideStepTransitionsIndex, and v8::internal::Smi::zero().
Referenced by GetSideStepTransitions().
LengthFor()
static int v8::internal::TransitionArray::LengthFor (int number_of_transitions) [inline], [static], [private]
Definition at line 409 of file transitions.h.
                                                  {
    return ToKeyIndex(number_of_transitions);
  }
References number_of_transitions(), and ToKeyIndex().
Referenced by v8::internal::Factory::NewTransitionArray().
LinearSearchName()
int v8::internal::TransitionArray::LinearSearchName (Tagged< Name > name, int * out_insertion_index) [inline], [private]
Definition at line 319 of file transitions-inl.h.
                                                                {
  int len = number_of_transitions();
  if (out_insertion_index != nullptr) {
    uint32_t hash = name->hash();
    for (int i = 0; i < len; i++) {
      Tagged<Name> entry = GetKey(i);
      if (entry == name) return i;
      if (entry->hash() > hash) {
        *out_insertion_index = i;
        return kNotFound;
      }
    }
    *out_insertion_index = len;
    return kNotFound;
  } else {
    for (int i = 0; i < len; i++) {
      if (GetKey(i) == name) return i;
    }
    return kNotFound;
  }
}
References GetKey(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kNotFound, v8::internal::name, and number_of_transitions().
Referenced by SearchName().
number_of_transitions()
int v8::internal::TransitionArray::number_of_transitions () const [inline]
Definition at line 411 of file transitions-inl.h.
                                                 {
  if (length() < kFirstIndex) return 0;
  return get(kTransitionLengthIndex).ToSmi().value();
}
References v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::get(), kFirstIndex, kTransitionLengthIndex, and v8::internal::length.
Referenced by BinarySearchName(), CompactPrototypeTransitionArray(), ForEachTransitionTo(), GetKey(), GetKeySlot(), GetRawTarget(), GetTargetSlot(), LengthFor(), LinearSearchName(), SearchDetails(), SearchDetailsAndGetTarget(), SearchName(), SetKey(), SetNumberOfTransitions(), SetRawTarget(), and Sort().
NumberOfPrototypeTransitions()
int v8::internal::TransitionArray::NumberOfPrototypeTransitions (Tagged< WeakFixedArray > proto_transitions) [inline], [static], [private]
Definition at line 121 of file transitions-inl.h.
                                              {
  if (proto_transitions->length() == 0) return 0;
  Tagged<MaybeObject> raw =
      proto_transitions->get(kProtoTransitionNumberOfEntriesOffset);
  return raw.ToSmi().value();
}
References kProtoTransitionNumberOfEntriesOffset, and v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
Referenced by CompactPrototypeTransitionArray(), v8::internal::TransitionsAccessor::ForEachTransitionWithKey(), v8::internal::TransitionsAccessor::GetPrototypeTransition(), v8::internal::TransitionsAccessor::PutPrototypeTransition(), and v8::internal::TransitionsAccessor::TraverseTransitionTreeInternal().
PrintInternal()
void v8::internal::TransitionArray::PrintInternal (std::ostream & os)
Search()
int v8::internal::TransitionArray::Search (PropertyKind kind, Tagged< Name > name, PropertyAttributes attributes, int * out_insertion_index = nullptr) [private]
Definition at line 745 of file transitions.cc.
                                                      {
  int transition = SearchName(name, false, out_insertion_index);
  if (transition == kNotFound) return kNotFound;
  return SearchDetails(transition, kind, attributes, out_insertion_index);
}
References kNotFound, v8::internal::name, SearchDetails(), and SearchName().
SearchAndGetTarget()
Tagged< Map > v8::internal::TransitionArray::SearchAndGetTarget (PropertyKind kind, Tagged< Name > name, PropertyAttributes attributes) [private]
Definition at line 753 of file transitions.cc.
                                                                               {
  int transition = SearchName(name);
  if (transition == kNotFound) {
    return Tagged<Map>();
  }
  return SearchDetailsAndGetTarget(transition, kind, attributes);
}
References kNotFound, v8::internal::name, SearchDetailsAndGetTarget(), and SearchName().
Referenced by SearchAndGetTargetForTesting().
SearchAndGetTargetForTesting()
Tagged< Map > v8::internal::TransitionArray::SearchAndGetTargetForTesting (PropertyKind kind, Tagged< Name > name, PropertyAttributes attributes) [inline]
Definition at line 250 of file transitions-inl.h.
                                                                         {
  return SearchAndGetTarget(kind, name, attributes);
}
References v8::internal::name, and SearchAndGetTarget().
SearchDetails()
int v8::internal::TransitionArray::SearchDetails (int transition, PropertyKind kind, PropertyAttributes attributes, int * out_insertion_index) [private]
Definition at line 699 of file transitions.cc.
                                                             {
  int nof_transitions = number_of_transitions();
  DCHECK(transition < nof_transitions);
  Tagged<Name> key = GetKey(transition);
  for (; transition < nof_transitions && GetKey(transition) == key;
       transition++) {
    Tagged<Map> target = GetTarget(transition);
    PropertyDetails target_details =
        TransitionsAccessor::GetTargetDetails(key, target);
    int cmp = CompareDetails(kind, attributes, target_details.kind(),
                             target_details.attributes());
    if (cmp == 0) {
      return transition;
    } else if (cmp < 0) {
      break;
    }
  }
  if (out_insertion_index != nullptr) *out_insertion_index = transition;
  return kNotFound;
}
References v8::internal::PropertyDetails::attributes(), CompareDetails(), v8::internal::DCHECK(), GetKey(), GetTarget(), v8::internal::TransitionsAccessor::GetTargetDetails(), v8::internal::key, v8::internal::PropertyDetails::kind(), kNotFound, and number_of_transitions().
Referenced by Search().
SearchDetailsAndGetTarget()
Tagged< Map > v8::internal::TransitionArray::SearchDetailsAndGetTarget (int transition, PropertyKind kind, PropertyAttributes attributes) [private]
Definition at line 723 of file transitions.cc.
                                                                      {
  int nof_transitions = number_of_transitions();
  DCHECK(transition < nof_transitions);
  Tagged<Name> key = GetKey(transition);
  for (; transition < nof_transitions && GetKey(transition) == key;
       transition++) {
    Tagged<Map> target = GetTarget(transition);
    PropertyDetails target_details =
        TransitionsAccessor::GetTargetDetails(key, target);
    int cmp = CompareDetails(kind, attributes, target_details.kind(),
                             target_details.attributes());
    if (cmp == 0) {
      return target;
    } else if (cmp < 0) {
      break;
    }
  }
  return Tagged<Map>();
}
References v8::internal::PropertyDetails::attributes(), CompareDetails(), v8::internal::DCHECK(), GetKey(), GetTarget(), v8::internal::TransitionsAccessor::GetTargetDetails(), v8::internal::key, v8::internal::PropertyDetails::kind(), and number_of_transitions().
Referenced by SearchAndGetTarget().
SearchName()
int v8::internal::TransitionArray::SearchName (Tagged< Name > name, bool concurrent_search = false, int * out_insertion_index = nullptr) [inline], [private]
Definition at line 261 of file transitions-inl.h.
                                                          {
  DCHECK(IsUniqueName(name));
  SLOW_DCHECK_IMPLIES(!concurrent_search, IsSortedNoDuplicates());
  if (number_of_transitions() == 0) {
    if (out_insertion_index != nullptr) {
      *out_insertion_index = 0;
    }
    return kNotFound;
  }
  // Do linear search for small arrays, and for searches in the background
  // thread.
  const int kMaxElementsForLinearSearch = 8;
  if (number_of_transitions() <= kMaxElementsForLinearSearch ||
      concurrent_search) {
    return LinearSearchName(name, out_insertion_index);
  }
  return BinarySearchName(name, out_insertion_index);
}
References BinarySearchName(), v8::internal::DCHECK(), v8::internal::IsUniqueName(), kNotFound, LinearSearchName(), v8::internal::name, number_of_transitions(), and SLOW_DCHECK_IMPLIES.
Referenced by ForEachTransitionTo(), Search(), SearchAndGetTarget(), SearchNameForTesting(), and SearchSpecial().
SearchNameForTesting()
int v8::internal::TransitionArray::SearchNameForTesting (Tagged< Name > name, int * out_insertion_index = nullptr) [inline]
Definition at line 245 of file transitions-inl.h.
                                                                    {
  return SearchName(name, out_insertion_index);
}
References v8::internal::name, and SearchName().
SearchSpecial()
int v8::internal::TransitionArray::SearchSpecial (Tagged< Symbol > symbol, bool concurrent_search = false, int * out_insertion_index = nullptr) [inline], [private]
Definition at line 255 of file transitions-inl.h.
                                                             {
  return SearchName(symbol, concurrent_search, out_insertion_index);
}
References SearchName().
Set()
void v8::internal::TransitionArray::Set (int transition_number, Tagged< Name > key, Tagged< MaybeObject > target) [inline], [private]
Definition at line 454 of file transitions-inl.h.
                                                      {
  WeakFixedArray::set(ToKeyIndex(transition_number), key);
  WeakFixedArray::set(ToTargetIndex(transition_number), target);
}
References v8::internal::key, v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::set(), ToKeyIndex(), and ToTargetIndex().
SetKey()
void v8::internal::TransitionArray::SetKey (int transition_number, Tagged< Name > value) [inline]
Definition at line 152 of file transitions-inl.h.
                                                                    {
  DCHECK(transition_number < number_of_transitions());
  WeakFixedArray::set(ToKeyIndex(transition_number), key);
}
References v8::internal::DCHECK(), v8::internal::key, number_of_transitions(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::set(), and ToKeyIndex().
Referenced by Sort().
SetNumberOfPrototypeTransitions()
void v8::internal::TransitionArray::SetNumberOfPrototypeTransitions (Tagged< WeakFixedArray > proto_transitions, int value) [static], [private]
Definition at line 496 of file transitions.cc.
                                                         {
  DCHECK_NE(proto_transitions->length(), 0);
  proto_transitions->set(kProtoTransitionNumberOfEntriesOffset,
                         Smi::FromInt(value));
}
References DCHECK_NE, v8::internal::Smi::FromInt(), kProtoTransitionNumberOfEntriesOffset, and v8::internal::value.
Referenced by CompactPrototypeTransitionArray(), GrowPrototypeTransitionArray(), and v8::internal::TransitionsAccessor::PutPrototypeTransition().
SetNumberOfTransitions()
void v8::internal::TransitionArray::SetNumberOfTransitions (int number_of_transitions) [inline], [private]
Definition at line 465 of file transitions-inl.h.
                                                                      {
  DCHECK(number_of_transitions <= Capacity());
  WeakFixedArray::set(kTransitionLengthIndex,
                      Smi::FromInt(number_of_transitions));
}
References Capacity(), v8::internal::DCHECK(), v8::internal::Smi::FromInt(), kTransitionLengthIndex, number_of_transitions(), and v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::set().
SetPrototypeTransitions()
void v8::internal::TransitionArray::SetPrototypeTransitions (Tagged< WeakFixedArray > prototype_transitions) [inline], [private]
Definition at line 115 of file transitions-inl.h.
                                        {
  DCHECK(IsWeakFixedArray(transitions));
  WeakFixedArray::set(kPrototypeTransitionsIndex, transitions, kReleaseStore);
}
References v8::internal::DCHECK(), kPrototypeTransitionsIndex, v8::kReleaseStore, and v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::set().
SetRawTarget()
void v8::internal::TransitionArray::SetRawTarget (int transition_number, Tagged< MaybeObject > target) [inline]
Definition at line 216 of file transitions-inl.h.
                                                              {
  DCHECK(transition_number < number_of_transitions());
  DCHECK(value.IsWeakOrCleared());
  DCHECK(value.IsCleared() || IsMap(value.GetHeapObjectAssumeWeak()));
  DCHECK(!value.IsCleared());
  WeakFixedArray::set(ToTargetIndex(transition_number), value);
}
References v8::internal::DCHECK(), number_of_transitions(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::set(), ToTargetIndex(), and v8::internal::value.
Referenced by Sort().
SetSideStepTransitions()
void v8::internal::TransitionArray::SetSideStepTransitions (Tagged< WeakFixedArray > transitions) [inline], [private]
Definition at line 104 of file transitions-inl.h.
                                        {
  DCHECK(IsWeakFixedArray(transitions));
  WeakFixedArray::set(kSideStepTransitionsIndex, transitions);
}
References v8::internal::DCHECK(), kSideStepTransitionsIndex, and v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::set().
Sort()
void v8::internal::TransitionArray::Sort ()
Definition at line 778 of file transitions.cc.
                           {
  DisallowGarbageCollection no_gc;
  // In-place insertion sort.
  int length = number_of_transitions();
  ReadOnlyRoots roots = GetReadOnlyRoots();
  for (int i = 1; i < length; i++) {
    Tagged<Name> key = GetKey(i);
    Tagged<MaybeObject> target = GetRawTarget(i);
    PropertyKind kind = PropertyKind::kData;
    PropertyAttributes attributes = NONE;
    if (!TransitionsAccessor::IsSpecialTransition(roots, key)) {
      Tagged<Map> target_map = TransitionsAccessor::GetTargetFromRaw(target);
      PropertyDetails details =
          TransitionsAccessor::GetTargetDetails(key, target_map);
      kind = details.kind();
      attributes = details.attributes();
    }
    int j;
    for (j = i - 1; j >= 0; j--) {
      Tagged<Name> temp_key = GetKey(j);
      Tagged<MaybeObject> temp_target = GetRawTarget(j);
      PropertyKind temp_kind = PropertyKind::kData;
      PropertyAttributes temp_attributes = NONE;
      if (!TransitionsAccessor::IsSpecialTransition(roots, temp_key)) {
        Tagged<Map> temp_target_map =
            TransitionsAccessor::GetTargetFromRaw(temp_target);
        PropertyDetails details =
            TransitionsAccessor::GetTargetDetails(temp_key, temp_target_map);
        temp_kind = details.kind();
        temp_attributes = details.attributes();
      }
      int cmp =
          CompareKeys(temp_key, temp_key->hash(), temp_kind, temp_attributes,
                      key, key->hash(), kind, attributes);
      if (cmp > 0) {
        SetKey(j + 1, temp_key);
        SetRawTarget(j + 1, temp_target);
      } else {
        break;
      }
    }
    SetKey(j + 1, key);
    SetRawTarget(j + 1, target);
  }
  DCHECK(IsSortedNoDuplicates());
}
References v8::internal::PropertyDetails::attributes(), CompareKeys(), v8::internal::DCHECK(), GetKey(), GetRawTarget(), v8::internal::GetReadOnlyRoots(), v8::internal::TransitionsAccessor::GetTargetDetails(), v8::internal::TransitionsAccessor::GetTargetFromRaw(), v8::internal::TransitionsAccessor::IsSpecialTransition(), v8::internal::kData, v8::internal::key, v8::internal::PropertyDetails::kind(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, number_of_transitions(), SetKey(), and SetRawTarget().
ToKeyIndex()
static int v8::internal::TransitionArray::ToKeyIndex (int transition_number) [inline], [static]
Definition at line 361 of file transitions.h.
                                               {
    return kFirstIndex + (transition_number * kEntrySize) + kEntryKeyIndex;
  }
References kEntryKeyIndex, kEntrySize, and kFirstIndex.
Referenced by GetKey(), GetKeySlot(), LengthFor(), Set(), and SetKey().
ToTargetIndex()
static int v8::internal::TransitionArray::ToTargetIndex (int transition_number) [inline], [static]
Definition at line 365 of file transitions.h.
                                                  {
    return kFirstIndex + (transition_number * kEntrySize) + kEntryTargetIndex;
  }
References kEntrySize, kEntryTargetIndex, and kFirstIndex.
Referenced by GetRawTarget(), GetTargetSlot(), Set(), and SetRawTarget().
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 381 of file transitions.h.
MarkCompactCollector
friend class MarkCompactCollector [friend]
Definition at line 382 of file transitions.h.
TransitionsAccessor
friend class TransitionsAccessor [friend]
Definition at line 383 of file transitions.h.
Member Data Documentation
kEntryKeyIndex
const int v8::internal::TransitionArray::kEntryKeyIndex = 0 [static]
Definition at line 356 of file transitions.h.
Referenced by v8::internal::KeyedStoreGenericAssembler::FindCandidateStoreICTransitionMapHandler(), and ToKeyIndex().
kEntrySize
const int v8::internal::TransitionArray::kEntrySize = 2 [static]
Definition at line 358 of file transitions.h.
Referenced by Capacity(), ToKeyIndex(), and ToTargetIndex().
kEntryTargetIndex
const int v8::internal::TransitionArray::kEntryTargetIndex = 1 [static]
Definition at line 357 of file transitions.h.
Referenced by v8::internal::KeyedStoreGenericAssembler::FindCandidateStoreICTransitionMapHandler(), and ToTargetIndex().
kFirstIndex
const int v8::internal::TransitionArray::kFirstIndex = 3 [static]
Definition at line 353 of file transitions.h.
Referenced by Capacity(), number_of_transitions(), ToKeyIndex(), and ToTargetIndex().
kMaxCachedPrototypeTransitions
const int v8::internal::TransitionArray::kMaxCachedPrototypeTransitions = 256 [static], [private]
Definition at line 394 of file transitions.h.
Referenced by GrowPrototypeTransitionArray(), and v8::internal::TransitionsAccessor::PutPrototypeTransition().
kNotFound
constexpr int v8::internal::TransitionArray::kNotFound = -1 [static], [constexpr]
Definition at line 336 of file transitions.h.
Referenced by BinarySearchName(), ForEachTransitionTo(), LinearSearchName(), Search(), SearchAndGetTarget(), SearchDetails(), and SearchName().
kProtoTransitionHeaderSize
const int v8::internal::TransitionArray::kProtoTransitionHeaderSize = 1 [static], [private]
Definition at line 393 of file transitions.h.
Referenced by CompactPrototypeTransitionArray(), v8::internal::TransitionsAccessor::ForEachTransitionWithKey(), v8::internal::TransitionsAccessor::GetPrototypeTransition(), GrowPrototypeTransitionArray(), v8::internal::TransitionsAccessor::PutPrototypeTransition(), and v8::internal::TransitionsAccessor::TraverseTransitionTreeInternal().
kProtoTransitionNumberOfEntriesOffset
const int v8::internal::TransitionArray::kProtoTransitionNumberOfEntriesOffset = 0 [static], [private]
Definition at line 404 of file transitions.h.
Referenced by NumberOfPrototypeTransitions(), and SetNumberOfPrototypeTransitions().
kPrototypeTransitionsIndex
const int v8::internal::TransitionArray::kPrototypeTransitionsIndex = 0 [static]
Definition at line 350 of file transitions.h.
Referenced by GetPrototypeTransitions(), HasPrototypeTransitions(), v8::internal::Factory::NewTransitionArray(), and SetPrototypeTransitions().
kSideStepTransitionsIndex
const int v8::internal::TransitionArray::kSideStepTransitionsIndex = 1 [static]
Definition at line 351 of file transitions.h.
Referenced by GetSideStepTransitions(), HasSideStepTransitions(), v8::internal::Factory::NewTransitionArray(), SetSideStepTransitions(), and v8::internal::TF_BUILTIN().
kTransitionLengthIndex
const int v8::internal::TransitionArray::kTransitionLengthIndex = 2 [static]
Definition at line 352 of file transitions.h.
Referenced by v8::internal::Factory::NewTransitionArray(), number_of_transitions(), and SetNumberOfTransitions().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/transitions.h
/mnt/V8SourceCode/src/objects/transitions-inl.h
/mnt/V8SourceCode/src/objects/transitions.cc