v8::internal::DescriptorArrayMarkingState Class Reference
#include <descriptor-array.h>
Public Types
using DescriptorIndex = uint16_t
using RawGCStateType = uint32_t
Static Public Member Functions
static constexpr RawGCStateType GetFullyMarkedState (unsigned epoch, DescriptorIndex number_of_descriptors)
static bool TryUpdateIndicesToMark (unsigned gc_epoch, Tagged< DescriptorArray > array, DescriptorIndex index_to_mark)
static std::pair< DescriptorIndex, DescriptorIndex > AcquireDescriptorRangeToMark (unsigned gc_epoch, Tagged< DescriptorArray > array)
Static Public Attributes
static constexpr RawGCStateType kInitialGCState = 0
Static Private Member Functions
static constexpr RawGCStateType NewState (unsigned masked_epoch, DescriptorIndex marked, DescriptorIndex delta)
static bool SwapState (Tagged< DescriptorArray > array, RawGCStateType old_state, RawGCStateType new_state)
Detailed Description
Definition at line 291 of file descriptor-array.h.
Member Typedef Documentation
DescriptorIndex
using v8::internal::DescriptorArrayMarkingState::DescriptorIndex = uint16_t
Definition at line 302 of file descriptor-array.h.
RawGCStateType
using v8::internal::DescriptorArrayMarkingState::RawGCStateType = uint32_t
Definition at line 303 of file descriptor-array.h.
Member Function Documentation
AcquireDescriptorRangeToMark()
std::pair< DescriptorArrayMarkingState::DescriptorIndex, DescriptorArrayMarkingState::DescriptorIndex > v8::internal::DescriptorArrayMarkingState::AcquireDescriptorRangeToMark (unsigned gc_epoch, Tagged< DescriptorArray > array) [inline], [static]
Definition at line 414 of file descriptor-array-inl.h.
                                                      {
  const auto current_epoch = gc_epoch & Epoch::kMask;
  while (true) {
    const RawGCStateType raw_gc_state = array->raw_gc_state(kRelaxedLoad);
    const DescriptorIndex marked = Marked::decode(raw_gc_state);
    const DescriptorIndex delta = Delta::decode(raw_gc_state);
    // We may encounter an array here that was merely pushed to the marker. In
    // such a case, we process all descriptors (if we succeed). The cases to
    // check are:
    // 1. Epoch mismatch: Happens when descriptors survive a GC cycle.
    // 2. Epoch matches but marked/delta is 0: Can happen when descriptors are
    // newly allocated in the current cycle.
    if (current_epoch != Epoch::decode(raw_gc_state) || (marked + delta) == 0) {
      // In case number of descriptors is 0 and we reach the array through roots
      // marking, mark also slack to get a proper transition from 0 marked to X
      // marked. Otherwise, we would need to treat the state [0,0[ for marked
      // and delta as valid state which leads to double-accounting through the
      // marking barrier (when nof>1 in the barrier).
      const int16_t number_of_descriptors =
          array->number_of_descriptors() ? array->number_of_descriptors()
                                         : array->number_of_all_descriptors();
      DCHECK_GT(number_of_descriptors, 0);
      if (SwapState(array, raw_gc_state,
                    NewState(current_epoch, number_of_descriptors, 0))) {
        return {0, number_of_descriptors};
      }
      continue;
    }
    // The delta is 0, so everything has been processed. Return the marked
    // indices.
    if (delta == 0) {
      return {marked, marked};
    }
    if (SwapState(array, raw_gc_state,
                  NewState(current_epoch, marked + delta, 0))) {
      return {marked, marked + delta};
    }
  }
}
References DCHECK_GT, v8::kRelaxedLoad, NewState(), v8::internal::number_of_descriptors, and SwapState().
Referenced by v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorArray().
GetFullyMarkedState()
static constexpr RawGCStateType v8::internal::DescriptorArrayMarkingState::GetFullyMarkedState (unsigned epoch, DescriptorIndex number_of_descriptors) [inline], [static], [constexpr]
Definition at line 307 of file descriptor-array.h.
                                                             {
    return NewState(epoch & Epoch::kMask, number_of_descriptors, 0);
  }
References v8::internal::number_of_descriptors.
Referenced by v8::internal::FactoryBase< Impl >::NewDescriptorArray().
NewState()
static constexpr RawGCStateType v8::internal::DescriptorArrayMarkingState::NewState (unsigned masked_epoch, DescriptorIndex marked, DescriptorIndex delta) [inline], [static], [constexpr], [private]
Definition at line 331 of file descriptor-array.h.
                                                                  {
    return Epoch::encode(masked_epoch) | Marked::encode(marked) |
           Delta::encode(delta);
  }
Referenced by AcquireDescriptorRangeToMark(), and TryUpdateIndicesToMark().
SwapState()
static bool v8::internal::DescriptorArrayMarkingState::SwapState (Tagged< DescriptorArray > array, RawGCStateType old_state, RawGCStateType new_state) [inline], [static], [private]
Definition at line 338 of file descriptor-array.h.
                                                  {
    return static_cast<RawGCStateType>(base::AcquireRelease_CompareAndSwap(
               reinterpret_cast<base::Atomic32*>(
                   FIELD_ADDR(array, DescriptorArray::kRawGcStateOffset)),
               old_state, new_state)) == old_state;
  }
References v8::base::AcquireRelease_CompareAndSwap(), and FIELD_ADDR.
Referenced by AcquireDescriptorRangeToMark(), and TryUpdateIndicesToMark().
TryUpdateIndicesToMark()
bool v8::internal::DescriptorArrayMarkingState::TryUpdateIndicesToMark (unsigned gc_epoch, Tagged< DescriptorArray > array, DescriptorIndex index_to_mark) [inline], [static]
Definition at line 381 of file descriptor-array-inl.h.
                                   {
  const auto current_epoch = gc_epoch & Epoch::kMask;
  while (true) {
    const RawGCStateType raw_gc_state = array->raw_gc_state(kRelaxedLoad);
    const auto epoch_from_state = Epoch::decode(raw_gc_state);
    RawGCStateType new_raw_gc_state = 0;
    if (current_epoch != epoch_from_state) {
      // If the epochs do not match, then either the raw_gc_state is zero
      // (freshly allocated descriptor array) or the epoch from value lags
      // by 1.
      DCHECK_IMPLIES(raw_gc_state != 0,
                     Epoch::decode(epoch_from_state + 1) == current_epoch);
      new_raw_gc_state = NewState(current_epoch, 0, index_to_mark);
    } else {
      const DescriptorIndex already_marked = Marked::decode(raw_gc_state);
      const DescriptorIndex delta = Delta::decode(raw_gc_state);
      if ((already_marked + delta) >= index_to_mark) {
        return false;
      }
      new_raw_gc_state = NewState(current_epoch, already_marked,
                                  index_to_mark - already_marked);
    }
    if (SwapState(array, raw_gc_state, new_raw_gc_state)) {
      return true;
    }
  }
}
References DCHECK_IMPLIES, v8::kRelaxedLoad, NewState(), and SwapState().
Referenced by v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorsForMap(), and v8::internal::MarkingBarrier::Write().
Member Data Documentation
kInitialGCState
constexpr RawGCStateType v8::internal::DescriptorArrayMarkingState::kInitialGCState = 0 [static], [constexpr]
Definition at line 305 of file descriptor-array.h.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::FactoryBase< Impl >::NewDescriptorArray(), and v8::internal::Serializer::ObjectSerializer::OutputRawData().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/descriptor-array.h
/mnt/V8SourceCode/src/objects/descriptor-array-inl.h