v8::internal::ParkingThread Class Reference
#include <parked-scope.h>
Public Member Functions
ParkingThread (const Options &options)
void ParkedJoin (LocalIsolate *local_isolate)
void ParkedJoin (LocalHeap *local_heap)
void ParkedJoin (const ParkedScope &scope)
Static Public Member Functions
template<typename ThreadCollection >
static void ParkedJoinAll (LocalIsolate *local_isolate, const ThreadCollection &threads)
template<typename ThreadCollection >
static void ParkedJoinAll (LocalHeap *local_heap, const ThreadCollection &threads)
template<typename ThreadCollection >
static void ParkedJoinAll (const ParkedScope &scope, const ThreadCollection &threads)
Additional Inherited Members
Detailed Description
Definition at line 197 of file parked-scope.h.
Constructor & Destructor Documentation
ParkingThread()
v8::internal::ParkingThread::ParkingThread (const Options & options) [inline], [explicit]
Definition at line 199 of file parked-scope.h.
: v8::base::Thread(options) {}
Member Function Documentation
ParkedJoin() [1/3]
void v8::internal::ParkingThread::ParkedJoin (const ParkedScope & scope) [inline]
Definition at line 204 of file parked-scope.h.
                                            {
    USE(scope);
    Join();
  }
References v8::base::Thread::Join(), and USE.
ParkedJoin() [2/3]
void v8::internal::ParkingThread::ParkedJoin (LocalHeap * local_heap) [inline]
Definition at line 118 of file parked-scope-inl.h.
                                                              {
  local_heap->ExecuteWhileParked(
      [this](const ParkedScope& parked) { ParkedJoin(parked); });
}
References v8::internal::LocalHeap::ExecuteWhileParked(), and ParkedJoin().
ParkedJoin() [3/3]
void v8::internal::ParkingThread::ParkedJoin (LocalIsolate * local_isolate) [inline]
Definition at line 114 of file parked-scope-inl.h.
                                                                    {
  ParkedJoin(local_isolate->heap());
}
References v8::internal::LocalIsolate::heap().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread(), and ParkedJoin().
ParkedJoinAll() [1/3]
template<typename ThreadCollection >
static void v8::internal::ParkingThread::ParkedJoinAll (const ParkedScope & scope, const ThreadCollection & threads) [inline], [static]
Definition at line 217 of file parked-scope.h.
                                                             {
    USE(scope);
    for (auto& thread : threads) thread->Join();
  }
References USE.
ParkedJoinAll() [2/3]
template<typename ThreadCollection >
void v8::internal::ParkingThread::ParkedJoinAll (LocalHeap * local_heap, const ThreadCollection & threads) [inline], [static]
Definition at line 132 of file parked-scope-inl.h.
                                                                             {
  local_heap->ExecuteWhileParked([&threads](const ParkedScope& parked) {
    ParkedJoinAll(parked, threads);
  });
}
References v8::internal::LocalHeap::ExecuteWhileParked(), and ParkedJoinAll().
ParkedJoinAll() [3/3]
template<typename ThreadCollection >
void v8::internal::ParkingThread::ParkedJoinAll (LocalIsolate * local_isolate, const ThreadCollection & threads) [inline], [static]
Definition at line 125 of file parked-scope-inl.h.
                                                                             {
  ParkedJoinAll(local_isolate->heap(), threads);
}
References v8::internal::LocalIsolate::heap().
Referenced by ParkedJoinAll().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/parked-scope.h
/mnt/V8SourceCode/src/heap/parked-scope-inl.h