v8::internal::BackReferenceNode Class Reference
#include <regexp-nodes.h>
Public Member Functions
BackReferenceNode (int start_reg, int end_reg, bool read_backward, RegExpNode *on_success)
BackReferenceNode * AsBackReferenceNode () override
void Accept (NodeVisitor *visitor) override
int start_register ()
int end_register ()
bool read_backward ()
void Emit (RegExpCompiler *compiler, Trace *trace) override
void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
Private Attributes
int start_reg_
int end_reg_
bool read_backward_
Additional Inherited Members
Detailed Description
Definition at line 557 of file regexp-nodes.h.
Constructor & Destructor Documentation
BackReferenceNode()
v8::internal::BackReferenceNode::BackReferenceNode (int start_reg, int end_reg, bool read_backward, RegExpNode * on_success) [inline]
Definition at line 559 of file regexp-nodes.h.
      : SeqRegExpNode(on_success),
        start_reg_(start_reg),
        end_reg_(end_reg),
        read_backward_(read_backward) {}
Member Function Documentation
Accept()
void v8::internal::BackReferenceNode::Accept (NodeVisitor * visitor) [override], [virtual]
Implements v8::internal::RegExpNode.
AsBackReferenceNode()
BackReferenceNode* v8::internal::BackReferenceNode::AsBackReferenceNode () [inline], [override]
Definition at line 565 of file regexp-nodes.h.
{ return this; }
Emit()
void v8::internal::BackReferenceNode::Emit (RegExpCompiler * compiler, Trace * trace) [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 3587 of file regexp-compiler.cc.
                                                                   {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  if (!trace->is_trivial()) {
    trace->Flush(compiler, this);
    return;
  }
  LimitResult limit_result = LimitVersions(compiler, trace);
  if (limit_result == DONE) return;
  DCHECK(limit_result == CONTINUE);
  RecursionCheck rc(compiler);
  DCHECK_EQ(start_reg_ + 1, end_reg_);
  if (IsIgnoreCase(compiler->flags())) {
    bool unicode = IsEitherUnicode(compiler->flags());
    assembler->CheckNotBackReferenceIgnoreCase(start_reg_, read_backward(),
                                               unicode, trace->backtrack());
  } else {
    assembler->CheckNotBackReference(start_reg_, read_backward(),
                                     trace->backtrack());
  }
  // We are going to advance backward, so we may end up at the start.
  if (read_backward()) trace->set_at_start(Trace::UNKNOWN);
  // Check that the back reference does not end inside a surrogate pair.
  if (IsEitherUnicode(compiler->flags()) && !compiler->one_byte()) {
    assembler->CheckNotInSurrogatePair(trace->cp_offset(), trace->backtrack());
  }
  on_success()->Emit(compiler, trace);
}
References v8::internal::Trace::backtrack(), v8::internal::RegExpMacroAssembler::CheckNotBackReference(), v8::internal::RegExpMacroAssembler::CheckNotBackReferenceIgnoreCase(), v8::internal::RegExpMacroAssembler::CheckNotInSurrogatePair(), v8::internal::RegExpNode::CONTINUE, v8::internal::Trace::cp_offset(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegExpNode::DONE, v8::internal::RegExpNode::Emit(), end_reg_, v8::internal::RegExpCompiler::flags(), v8::internal::Trace::Flush(), v8::internal::Trace::is_trivial(), v8::internal::IsEitherUnicode(), v8::internal::RegExpNode::LimitVersions(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::SeqRegExpNode::on_success(), v8::internal::RegExpCompiler::one_byte(), read_backward(), v8::internal::Trace::set_at_start(), start_reg_, and v8::internal::Trace::UNKNOWN.
end_register()
int v8::internal::BackReferenceNode::end_register () [inline]
Definition at line 568 of file regexp-nodes.h.
{ return end_reg_; }
References end_reg_.
FillInBMInfo()
void v8::internal::BackReferenceNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::SeqRegExpNode.
Definition at line 3945 of file regexp-compiler.cc.
                                                        {
  // Working out the set of characters that a backreference can match is too
  // hard, so we just say that any character can match.
  bm->SetRest(offset);
  SaveBMInfo(bm, not_at_start, offset);
}
References v8::internal::RegExpNode::SaveBMInfo(), and v8::internal::BoyerMooreLookahead::SetRest().
GetQuickCheckDetails()
void v8::internal::BackReferenceNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [inline], [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 571 of file regexp-nodes.h.
                                                        {
    return;
  }
read_backward()
bool v8::internal::BackReferenceNode::read_backward () [inline]
Definition at line 569 of file regexp-nodes.h.
{ return read_backward_; }
References read_backward_.
Referenced by Emit(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitBackReference().
start_register()
int v8::internal::BackReferenceNode::start_register () [inline]
Definition at line 567 of file regexp-nodes.h.
{ return start_reg_; }
References start_reg_.
Member Data Documentation
end_reg_
int v8::internal::BackReferenceNode::end_reg_ [private]
Definition at line 581 of file regexp-nodes.h.
Referenced by Emit(), and end_register().
read_backward_
bool v8::internal::BackReferenceNode::read_backward_ [private]
Definition at line 582 of file regexp-nodes.h.
Referenced by read_backward().
start_reg_
int v8::internal::BackReferenceNode::start_reg_ [private]
Definition at line 580 of file regexp-nodes.h.
Referenced by Emit(), and start_register().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc