v8::internal::StackFrameIteratorForProfiler Class Reference
#include <frames.h>
Public Member Functions
StackFrameIteratorForProfiler (Isolate *isolate, Address pc, Address fp, Address sp, Address lr, Address js_entry_sp)
StackFrame * frame () const
void Advance ()
StackFrame::Type top_frame_type () const
StackFrame::Type ComputeStackFrameType (StackFrame::State *state) const override
Private Member Functions
void AdvanceOneFrame ()
bool IsValidStackAddress (Address addr) const
bool IsValidState (const StackFrame::State &frame) const
bool HasValidExitIfEntryFrame (const StackFrame *frame) const
bool IsValidExitFrame (Address fp) const
bool IsValidTop (ThreadLocalTop *top) const
StackFrame::Type GetCallerIfValid (StackFrame *frame, StackFrame::State *state)
bool IsNoFrameBytecodeHandlerPc (Isolate *isolate, Address pc, Address fp) const
Static Private Member Functions
static bool IsValidFrameType (StackFrame::Type type)
Private Attributes
const Address low_bound_
const Address high_bound_
StackFrame::Type top_frame_type_
ExternalCallbackScope * external_callback_scope_
Address top_link_register_
Additional Inherited Members
Detailed Description
Definition at line 1800 of file frames.h.
Constructor & Destructor Documentation
StackFrameIteratorForProfiler()
v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler (Isolate * isolate, Address pc, Address fp, Address sp, Address lr, Address js_entry_sp)
Definition at line 487 of file frames.cc.
    : StackFrameIteratorBase(isolate),
      low_bound_(sp),
      high_bound_(js_entry_sp),
      top_frame_type_(StackFrame::NO_FRAME_TYPE),
      external_callback_scope_(isolate->external_callback_scope()),
      top_link_register_(lr)
#if V8_ENABLE_WEBASSEMBLY
      ,
      wasm_stacks_(isolate->wasm_stacks())
#endif
{
  if (!isolate->isolate_data()->stack_is_iterable()) {
    // The stack is not iterable in a short time interval during deoptimization.
    // See also: ExternalReference::stack_is_iterable_address.
    DCHECK(done());
    return;
  }
  // For Advance below, we need frame_ to be set; and that only happens if the
  // type is not NO_FRAME_TYPE.
  // TODO(jgruber): Clean this up.
  static constexpr StackFrame::Type kTypeForAdvance = StackFrame::TURBOFAN_JS;
  StackFrame::State state;
  state.is_profiler_entry_frame = true;
  StackFrame::Type type;
  ThreadLocalTop* const top = isolate->thread_local_top();
  bool advance_frame = true;
  const Address fast_c_fp = isolate->isolate_data()->fast_c_call_caller_fp();
  if (fast_c_fp != kNullAddress) {
    // 'Fast C calls' are a special type of C call where we call directly from
    // JS to C without an exit frame in between. The CEntryStub is responsible
    // for setting Isolate::c_entry_fp, meaning that it won't be set for fast C
    // calls. To keep the stack iterable, we store the FP and PC of the caller
    // of the fast C call on the isolate. This is guaranteed to be the topmost
    // JS frame, because fast C calls cannot call back into JS. We start
    // iterating the stack from this topmost JS frame.
    DCHECK_NE(kNullAddress, isolate->isolate_data()->fast_c_call_caller_pc());
    state.fp = fast_c_fp;
    state.sp = sp;
    state.pc_address = reinterpret_cast<Address*>(
        isolate->isolate_data()->fast_c_call_caller_pc_address());
    // ComputeStackFrameType will read both kContextOffset and
    // kFunctionOffset, we check only that kFunctionOffset is within the stack
    // bounds and do a compile time check that kContextOffset slot is pushed on
    // the stack before kFunctionOffset.
    static_assert(StandardFrameConstants::kFunctionOffset <
                  StandardFrameConstants::kContextOffset);
    if (IsValidStackAddress(state.fp +
                            StandardFrameConstants::kFunctionOffset)) {
      type = ComputeStackFrameType(&state);
      if (IsValidFrameType(type)) {
        top_frame_type_ = type;
        advance_frame = false;
      }
    } else {
      // Cannot determine the actual type; the frame will be skipped below.
      type = kTypeForAdvance;
    }
  } else if (IsValidTop(top)) {
    type = ExitFrame::GetStateForFramePointer(Isolate::c_entry_fp(top), &state);
    top_frame_type_ = type;
  } else if (IsValidStackAddress(fp)) {
    DCHECK_NE(fp, kNullAddress);
    state.fp = fp;
    state.sp = sp;
    state.pc_address =
        StackFrame::ResolveReturnAddressLocation(reinterpret_cast<Address*>(
            fp + StandardFrameConstants::kCallerPCOffset));
    bool can_lookup_frame_type =
        // Ensure frame structure is not broken, otherwise it doesn't make
        // sense to try to detect a frame type.
        (sp < fp) &&
        // Ensure there is a context/frame type value in the frame.
        (fp - sp) >= TypedFrameConstants::kFixedFrameSizeFromFp;
    // If the current PC is in a bytecode handler, the top stack frame isn't
    // the bytecode handler's frame and the top of stack or link register is a
    // return address into the interpreter entry trampoline, then we are likely
    // in a bytecode handler with elided frame. In that case, set the PC
    // properly and make sure we do not drop the frame.
    bool is_no_frame_bytecode_handler = false;
    if (can_lookup_frame_type && IsNoFrameBytecodeHandlerPc(isolate, pc, fp)) {
      Address* top_location = nullptr;
      if (top_link_register_) {
        top_location = &top_link_register_;
      } else if (IsValidStackAddress(sp)) {
        MSAN_MEMORY_IS_INITIALIZED(sp, kSystemPointerSize);
        top_location = reinterpret_cast<Address*>(sp);
      }
      std::optional<bool> is_interpreter_frame_pc =
          IsInterpreterFramePc(isolate, *top_location, &state);
      // Since we're in a signal handler, the pc lookup might not be possible
      // since the required locks are taken by the same thread.
      if (!is_interpreter_frame_pc.has_value()) {
        can_lookup_frame_type = false;
      } else if (is_interpreter_frame_pc.value()) {
        state.pc_address = top_location;
        is_no_frame_bytecode_handler = true;
        advance_frame = false;
      }
    }
    // ComputeStackFrameType will read both kContextOffset and
    // kFunctionOffset, we check only that kFunctionOffset is within the stack
    // bounds and do a compile time check that kContextOffset slot is pushed on
    // the stack before kFunctionOffset.
    static_assert(StandardFrameConstants::kFunctionOffset <
                  StandardFrameConstants::kContextOffset);
    Address function_slot = fp + StandardFrameConstants::kFunctionOffset;
    if (!can_lookup_frame_type) {
      type = StackFrame::NO_FRAME_TYPE;
    } else if (IsValidStackAddress(function_slot)) {
      if (is_no_frame_bytecode_handler) {
        type = StackFrame::INTERPRETED;
      } else {
        type = ComputeStackFrameType(&state);
      }
      top_frame_type_ = type;
    } else {
      // Cannot determine the actual type; the frame will be skipped below.
      type = kTypeForAdvance;
    }
  } else {
    // Not iterable.
    DCHECK(done());
    return;
  }
  SetNewFrame(type, &state);
  if (advance_frame && !done()) {
    Advance();
  }
}
References Advance(), v8::internal::Isolate::c_entry_fp(), ComputeStackFrameType(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::StackFrameIteratorBase::done(), v8::internal::IsolateData::fast_c_call_caller_fp(), v8::internal::IsolateData::fast_c_call_caller_pc(), v8::internal::StackFrame::State::fp, v8::internal::ExitFrame::GetStateForFramePointer(), v8::internal::StackFrame::State::is_profiler_entry_frame, v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc(), IsNoFrameBytecodeHandlerPc(), v8::internal::StackFrameIteratorBase::isolate(), v8::internal::Isolate::isolate_data(), IsValidFrameType(), IsValidStackAddress(), IsValidTop(), v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::StandardFrameConstants::kContextOffset, v8::internal::TypedFrameConstants::kFixedFrameSizeFromFp, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kNullAddress, v8::internal::kSystemPointerSize, MSAN_MEMORY_IS_INITIALIZED, v8::internal::StackFrame::NO_FRAME_TYPE, v8::internal::StackFrame::State::pc_address, v8::internal::StackFrame::ResolveReturnAddressLocation(), v8::internal::StackFrameIteratorBase::SetNewFrame(), v8::internal::StackFrame::State::sp, v8::internal::IsolateData::stack_is_iterable(), v8::internal::Isolate::thread_local_top(), top_frame_type_, top_link_register_, and v8::internal::tracing::type.
Member Function Documentation
Advance()
void v8::internal::StackFrameIteratorForProfiler::Advance ()
Definition at line 700 of file frames.cc.
                                            {
  while (true) {
    AdvanceOneFrame();
    if (done()) break;
    ExternalCallbackScope* last_callback_scope = nullptr;
    while (external_callback_scope_ != nullptr &&
           external_callback_scope_->JSStackComparableAddress() <
               frame_->fp()) {
      // As long as the setup of a frame is not atomic, we may happen to be
      // in an interval where an ExternalCallbackScope is already created,
      // but the frame is not yet entered. So we are actually observing
      // the previous frame.
      // Skip all the ExternalCallbackScope's that are below the current fp.
      last_callback_scope = external_callback_scope_;
      external_callback_scope_ = external_callback_scope_->previous();
    }
    if (frame_->is_javascript()) break;
#if V8_ENABLE_WEBASSEMBLY
    if (frame_->is_wasm() || frame_->is_wasm_to_js() ||
        frame_->is_js_to_wasm()) {
      break;
    }
#endif // V8_ENABLE_WEBASSEMBLY
    if (frame_->is_exit() || frame_->is_builtin_exit() ||
        frame_->is_api_accessor_exit() || frame_->is_api_callback_exit()) {
      // Some of the EXIT frames may have ExternalCallbackScope allocated on
      // top of them. In that case the scope corresponds to the first EXIT
      // frame beneath it. There may be other EXIT frames on top of the
      // ExternalCallbackScope, just skip them as we cannot collect any useful
      // information about them.
      if (last_callback_scope) {
        frame_->state_.pc_address =
            last_callback_scope->callback_entrypoint_address();
      }
      break;
    }
  }
}
References AdvanceOneFrame(), v8::internal::ExternalCallbackScope::callback_entrypoint_address(), v8::internal::StackFrameIteratorBase::done(), external_callback_scope_, v8::internal::StackFrame::fp(), v8::internal::StackFrameIteratorBase::frame_, v8::internal::StackFrame::is_api_accessor_exit(), v8::internal::StackFrame::is_api_callback_exit(), v8::internal::StackFrame::is_builtin_exit(), v8::internal::StackFrame::is_exit(), v8::internal::StackFrame::is_javascript(), v8::internal::ExternalCallbackScope::JSStackComparableAddress(), v8::internal::StackFrame::State::pc_address, v8::internal::ExternalCallbackScope::previous(), and v8::internal::StackFrame::state_.
Referenced by v8::internal::StackFrameIteratorForProfilerForTesting::Advance(), v8::internal::TickSample::GetStackSample(), and StackFrameIteratorForProfiler().
AdvanceOneFrame()
void v8::internal::StackFrameIteratorForProfiler::AdvanceOneFrame () [private]
Definition at line 636 of file frames.cc.
                                                    {
  DCHECK(!done());
  StackFrame* last_frame = frame_;
  Address last_sp = last_frame->sp(), last_fp = last_frame->fp();
  // Before advancing to the next stack frame, perform pointer validity tests.
  if (!IsValidState(last_frame->state_) ||
      !HasValidExitIfEntryFrame(last_frame)) {
    frame_ = nullptr;
    return;
  }
  // Advance to the previous frame, and perform pointer validity tests there
  // too.
  StackFrame::State state;
  last_frame->ComputeCallerState(&state);
  if (!IsValidState(state)) {
    frame_ = nullptr;
    return;
  }
  StackFrame::Type type = ComputeStackFrameType(&state);
  SetNewFrame(type, &state);
  if (!frame_) return;
  // Check that we have actually moved to the previous frame in the stack.
  if (frame_->sp() <= last_sp || frame_->fp() <= last_fp) {
    frame_ = nullptr;
  }
}
References v8::internal::StackFrame::ComputeCallerState(), ComputeStackFrameType(), v8::internal::DCHECK(), v8::internal::StackFrameIteratorBase::done(), v8::internal::StackFrame::fp(), v8::internal::StackFrameIteratorBase::frame_, HasValidExitIfEntryFrame(), IsValidState(), v8::internal::StackFrameIteratorBase::SetNewFrame(), v8::internal::StackFrame::sp(), v8::internal::StackFrame::state_, and v8::internal::tracing::type.
Referenced by Advance().
ComputeStackFrameType()
StackFrame::Type v8::internal::StackFrameIteratorForProfiler::ComputeStackFrameType (StackFrame::State * state) const [override], [virtual]
Implements v8::internal::StackFrameIteratorBase.
Definition at line 1020 of file frames.cc.
                                  {
#if V8_ENABLE_WEBASSEMBLY
  if (state->fp == kNullAddress) {
    DCHECK(!isolate_->wasm_stacks().empty()); // I.e., JSPI active
    return StackFrame::NO_FRAME_TYPE;
  }
#endif
  // We use unauthenticated_pc because it may come from
  // fast_c_call_caller_pc_address, for which authentication does not work.
  const Address pc = StackFrame::unauthenticated_pc(state->pc_address);
#if V8_ENABLE_WEBASSEMBLY
  if (IsWasmToJsWrapperCSA(pc)) {
    return StackFrame::WASM_TO_JS;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  MSAN_MEMORY_IS_INITIALIZED(
      state->fp + CommonFrameConstants::kContextOrFrameTypeOffset,
      kSystemPointerSize);
  const intptr_t marker = Memory<intptr_t>(
      state->fp + CommonFrameConstants::kContextOrFrameTypeOffset);
  if (StackFrame::IsTypeMarker(marker)) {
    return SafeStackFrameType(StackFrame::MarkerToType(marker));
  }
  MSAN_MEMORY_IS_INITIALIZED(
      state->fp + StandardFrameConstants::kFunctionOffset, kSystemPointerSize);
  Tagged<Object> maybe_function = Tagged<Object>(
      Memory<Address>(state->fp + StandardFrameConstants::kFunctionOffset));
  if (IsSmi(maybe_function)) {
    return StackFrame::NATIVE;
  }
  std::optional<bool> is_interpreter_frame =
      IsInterpreterFramePc(isolate(), pc, state);
  // We might not be able to lookup the frame type since we're inside a signal
  // handler and the required locks are taken.
  if (!is_interpreter_frame.has_value()) {
    return StackFrame::NO_FRAME_TYPE;
  }
  if (is_interpreter_frame.value()) {
    return StackFrame::INTERPRETED;
  }
  return StackFrame::TURBOFAN_JS;
}
References v8::internal::DCHECK(), v8::internal::StackFrame::State::fp, v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc(), v8::internal::StackFrameIteratorBase::isolate(), v8::internal::StackFrameIteratorBase::isolate_, v8::internal::IsSmi(), v8::internal::StackFrame::IsTypeMarker(), v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kNullAddress, v8::internal::kSystemPointerSize, v8::internal::StackFrame::MarkerToType(), MSAN_MEMORY_IS_INITIALIZED, v8::internal::StackFrame::NO_FRAME_TYPE, v8::internal::StackFrame::State::pc_address, v8::internal::anonymous_namespace{frames.cc}::SafeStackFrameType(), v8::internal::Tagged< Object >, and v8::internal::StackFrame::unauthenticated_pc().
Referenced by AdvanceOneFrame(), and StackFrameIteratorForProfiler().
frame()
StackFrame * v8::internal::StackFrameIteratorForProfiler::frame () const [inline]
Definition at line 444 of file frames-inl.h.
                                                              {
  DCHECK(!done());
  DCHECK(IsValidFrameType(frame_->type()));
  return frame_;
}
References v8::internal::DCHECK(), v8::internal::StackFrameIteratorBase::done(), v8::internal::StackFrameIteratorBase::frame_, IsValidFrameType(), and v8::internal::StackFrame::type().
Referenced by v8::internal::TickSample::GetStackSample(), and HasValidExitIfEntryFrame().
GetCallerIfValid()
StackFrame::Type v8::internal::StackFrameIteratorForProfiler::GetCallerIfValid (StackFrame * frame, StackFrame::State * state) [private]
HasValidExitIfEntryFrame()
bool v8::internal::StackFrameIteratorForProfiler::HasValidExitIfEntryFrame (const StackFrame * frame) const [private]
Definition at line 672 of file frames.cc.
                                   {
  if (!frame->is_entry() && !frame->is_construct_entry()) return true;
  // See EntryFrame::GetCallerState. It computes the caller FP address
  // and calls ExitFrame::GetStateForFramePointer on it. We need to be
  // sure that caller FP address is valid.
  Address next_exit_frame_fp_address =
      frame->fp() + EntryFrameConstants::kNextExitFrameFPOffset;
  // Profiling tick might be triggered in the middle of JSEntry builtin
  // before the next_exit_frame_fp value is initialized. IsValidExitFrame()
  // is able to deal with such a case, so just suppress the MSan warning.
  MSAN_MEMORY_IS_INITIALIZED(next_exit_frame_fp_address, kSystemPointerSize);
  Address next_exit_frame_fp = Memory<Address>(next_exit_frame_fp_address);
  return IsValidExitFrame(next_exit_frame_fp);
}
References v8::internal::StackFrame::fp(), frame(), v8::internal::StackFrame::is_construct_entry(), v8::internal::StackFrame::is_entry(), IsValidExitFrame(), v8::internal::EntryFrameConstants::kNextExitFrameFPOffset, v8::internal::kSystemPointerSize, and MSAN_MEMORY_IS_INITIALIZED.
Referenced by AdvanceOneFrame().
IsNoFrameBytecodeHandlerPc()
bool v8::internal::StackFrameIteratorForProfiler::IsNoFrameBytecodeHandlerPc (Isolate * isolate, Address pc, Address fp) const [private]
Definition at line 462 of file frames.cc.
                                                    {
  EmbeddedData d = EmbeddedData::FromBlob(isolate);
  if (pc < d.InstructionStartOfBytecodeHandlers() ||
      pc >= d.InstructionEndOfBytecodeHandlers()) {
    return false;
  }
  Address frame_type_address =
      fp + CommonFrameConstants::kContextOrFrameTypeOffset;
  if (!IsValidStackAddress(frame_type_address)) {
    return false;
  }
  // Check if top stack frame is a bytecode handler stub frame.
  MSAN_MEMORY_IS_INITIALIZED(frame_type_address, kSystemPointerSize);
  intptr_t marker = Memory<intptr_t>(frame_type_address);
  if (StackFrame::IsTypeMarker(marker) &&
      StackFrame::MarkerToType(marker) == StackFrame::STUB) {
    // Bytecode handler built a frame.
    return false;
  }
  return true;
}
References v8::internal::EmbeddedData::FromBlob(), v8::internal::EmbeddedData::InstructionEndOfBytecodeHandlers(), v8::internal::EmbeddedData::InstructionStartOfBytecodeHandlers(), v8::internal::StackFrameIteratorBase::isolate(), v8::internal::StackFrame::IsTypeMarker(), IsValidStackAddress(), v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::kSystemPointerSize, v8::internal::StackFrame::MarkerToType(), and MSAN_MEMORY_IS_INITIALIZED.
Referenced by StackFrameIteratorForProfiler().
IsValidExitFrame()
bool v8::internal::StackFrameIteratorForProfiler::IsValidExitFrame (Address fp) const [private]
Definition at line 689 of file frames.cc.
                                                                     {
  if (!IsAligned(fp, kSystemPointerSize)) return false;
  if (!IsValidStackAddress(fp)) return false;
  Address sp = ExitFrame::ComputeStackPointer(fp);
  if (!IsValidStackAddress(sp)) return false;
  StackFrame::State state;
  ExitFrame::FillState(fp, sp, &state);
  MSAN_MEMORY_IS_INITIALIZED(state.pc_address, sizeof(state.pc_address));
  return *state.pc_address != kNullAddress;
}
References v8::internal::ExitFrame::ComputeStackPointer(), v8::internal::ExitFrame::FillState(), IsAligned(), IsValidStackAddress(), v8::internal::kNullAddress, v8::internal::kSystemPointerSize, MSAN_MEMORY_IS_INITIALIZED, and v8::internal::StackFrame::State::pc_address.
Referenced by HasValidExitIfEntryFrame(), and IsValidTop().
IsValidFrameType()
bool v8::internal::StackFrameIteratorForProfiler::IsValidFrameType (StackFrame::Type type) [inline], [static], [private]
Definition at line 424 of file frames-inl.h.
                         {
#if V8_ENABLE_WEBASSEMBLY
  DCHECK_NE(type, StackFrame::C_WASM_ENTRY);
#endif // V8_ENABLE_WEBASSEMBLY
  return StackFrame::IsJavaScript(type) || type == StackFrame::EXIT ||
         type == StackFrame::BUILTIN_EXIT ||
         type == StackFrame::API_ACCESSOR_EXIT ||
         type == StackFrame::API_CALLBACK_EXIT ||
#if V8_ENABLE_WEBASSEMBLY
         type == StackFrame::WASM || type == StackFrame::WASM_TO_JS ||
         type == StackFrame::JS_TO_WASM ||
         type == StackFrame::WASM_SEGMENT_START ||
#if V8_ENABLE_DRUMBRAKE
         type == StackFrame::WASM_INTERPRETER_ENTRY ||
#endif // V8_ENABLE_DRUMBRAKE
#endif // V8_ENABLE_WEBASSEMBLY
         false;
}
References DCHECK_NE, v8::internal::StackFrame::IsJavaScript(), and v8::internal::tracing::type.
Referenced by frame(), and StackFrameIteratorForProfiler().
IsValidStackAddress()
bool v8::internal::StackFrameIteratorForProfiler::IsValidStackAddress (Address addr) const [inline], [private]
Definition at line 1819 of file frames.h.
                                               {
    return low_bound_ <= addr && addr <= high_bound_;
  }
References high_bound_, and low_bound_.
Referenced by IsNoFrameBytecodeHandlerPc(), IsValidExitFrame(), IsValidState(), and StackFrameIteratorForProfiler().
IsValidState()
bool v8::internal::StackFrameIteratorForProfiler::IsValidState (const StackFrame::State & frame) const [private]
Definition at line 667 of file frames.cc.
                                        {
  return IsValidStackAddress(state.sp) && IsValidStackAddress(state.fp);
}
References v8::internal::StackFrame::State::fp, IsValidStackAddress(), and v8::internal::StackFrame::State::sp.
Referenced by AdvanceOneFrame().
IsValidTop()
bool v8::internal::StackFrameIteratorForProfiler::IsValidTop (ThreadLocalTop * top) const [private]
Definition at line 628 of file frames.cc.
                                                                        {
  Address c_entry_fp = Isolate::c_entry_fp(top);
  if (!IsValidExitFrame(c_entry_fp)) return false;
  // There should be at least one JS_ENTRY stack handler.
  Address handler = Isolate::handler(top);
  return handler != kNullAddress;
}
References v8::internal::Isolate::c_entry_fp(), v8::internal::StackFrameIteratorBase::handler(), v8::internal::Isolate::handler(), IsValidExitFrame(), and v8::internal::kNullAddress.
Referenced by StackFrameIteratorForProfiler().
top_frame_type()
StackFrame::Type v8::internal::StackFrameIteratorForProfiler::top_frame_type () const [inline]
Definition at line 1808 of file frames.h.
{ return top_frame_type_; }
References top_frame_type_.
Referenced by v8::internal::TickSample::GetStackSample().
Member Data Documentation
external_callback_scope_
ExternalCallbackScope* v8::internal::StackFrameIteratorForProfiler::external_callback_scope_ [private]
Definition at line 1842 of file frames.h.
Referenced by Advance().
high_bound_
const Address v8::internal::StackFrameIteratorForProfiler::high_bound_ [private]
Definition at line 1840 of file frames.h.
Referenced by IsValidStackAddress().
low_bound_
const Address v8::internal::StackFrameIteratorForProfiler::low_bound_ [private]
Definition at line 1839 of file frames.h.
Referenced by IsValidStackAddress().
top_frame_type_
StackFrame::Type v8::internal::StackFrameIteratorForProfiler::top_frame_type_ [private]
Definition at line 1841 of file frames.h.
Referenced by StackFrameIteratorForProfiler(), and top_frame_type().
top_link_register_
Address v8::internal::StackFrameIteratorForProfiler::top_link_register_ [private]
Definition at line 1843 of file frames.h.
Referenced by StackFrameIteratorForProfiler().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc