v8::internal::CallBase Class Reference
#include <ast.h>
Public Types
enum SpreadPosition { kNoSpread
, kHasFinalSpread
, kHasNonFinalSpread
 }
Public Member Functions
Expression * expression () const
const ZonePtrList< Expression > * arguments () const
SpreadPosition spread_position () const
Protected Types
using SpreadPositionField = Expression::NextBitField< SpreadPosition, 2 >
template<class T , int size>
using NextBitField = SpreadPositionField::Next< T, size >
Protected Member Functions
CallBase (Zone *zone, NodeType type, Expression *expression, const ScopedPtrList< Expression > &arguments, int pos, bool has_spread)
void ComputeSpreadPosition ()
Protected Attributes
Expression * expression_
ZonePtrList< Expression > arguments_
Detailed Description
Definition at line 1721 of file ast.h.
Member Typedef Documentation
NextBitField
template<class T , int size>
using v8::internal::CallBase::NextBitField = SpreadPositionField::Next<T, size> [protected]
Definition at line 1751 of file ast.h.
SpreadPositionField
using v8::internal::CallBase::SpreadPositionField = Expression::NextBitField<SpreadPosition, 2> [protected]
Definition at line 1748 of file ast.h.
Member Enumeration Documentation
SpreadPosition
enum v8::internal::CallBase::SpreadPosition
Enumerator
kNoSpread
kHasFinalSpread
kHasNonFinalSpread
Definition at line 1726 of file ast.h.
{ kNoSpread, kHasFinalSpread, kHasNonFinalSpread };
Constructor & Destructor Documentation
CallBase()
v8::internal::CallBase::CallBase (Zone * zone, NodeType type, Expression * expression, const ScopedPtrList< Expression > & arguments, int pos, bool has_spread) [inline], [protected]
Definition at line 1732 of file ast.h.
      : Expression(pos, type),
        expression_(expression),
        arguments_(arguments.ToConstVector(), zone) {
    DCHECK(type == kCall || type == kCallNew);
    if (has_spread) {
      ComputeSpreadPosition();
    } else {
      bit_field_ |= SpreadPositionField::encode(kNoSpread);
    }
  }
References v8::internal::AstNode::bit_field_, ComputeSpreadPosition(), v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), kCall, kNoSpread, and v8::internal::tracing::type.
Member Function Documentation
arguments()
const ZonePtrList<Expression>* v8::internal::CallBase::arguments () const [inline]
Definition at line 1724 of file ast.h.
{ return &arguments_; }
References arguments_.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
ComputeSpreadPosition()
void v8::internal::CallBase::ComputeSpreadPosition () [protected]
Definition at line 962 of file ast.cc.
                                     {
  int arguments_length = arguments_.length();
  int first_spread_index = 0;
  for (; first_spread_index < arguments_length; first_spread_index++) {
    if (arguments_.at(first_spread_index)->IsSpread()) break;
  }
  SpreadPosition position;
  if (first_spread_index == arguments_length - 1) {
    position = kHasFinalSpread;
  } else {
    DCHECK_LT(first_spread_index, arguments_length - 1);
    position = kHasNonFinalSpread;
  }
  bit_field_ |= SpreadPositionField::encode(position);
}
References arguments_, v8::internal::AstNode::bit_field_, DCHECK_LT, v8::base::BitField< T, shift, size, U >::encode(), kHasFinalSpread, kHasNonFinalSpread, and v8::internal::AstNode::position().
Referenced by CallBase().
expression()
Expression* v8::internal::CallBase::expression () const [inline]
Definition at line 1723 of file ast.h.
{ return expression_; }
References expression_.
Referenced by v8::internal::Call::GetCallType(), and v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
spread_position()
SpreadPosition v8::internal::CallBase::spread_position () const [inline]
Definition at line 1727 of file ast.h.
                                         {
    return SpreadPositionField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
Member Data Documentation
arguments_
ZonePtrList<Expression> v8::internal::CallBase::arguments_ [protected]
Definition at line 1754 of file ast.h.
Referenced by arguments(), and ComputeSpreadPosition().
expression_
Expression* v8::internal::CallBase::expression_ [protected]
Definition at line 1753 of file ast.h.
Referenced by expression().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc