cppgc::internal::BasicMarkingState Class Reference
#include <marking-state.h>
Public Member Functions
BasicMarkingState (HeapBase &heap, MarkingWorklists &, CompactionWorklists *)
~BasicMarkingState () override
BasicMarkingState (const BasicMarkingState &)=delete
BasicMarkingState & operator= (const BasicMarkingState &)=delete
void RegisterWeakReferenceIfNeeded (const void *, TraceDescriptor, WeakCallback, const void *)
void RegisterWeakContainerCallback (WeakCallback, const void *)
void RegisterWeakCustomCallback (WeakCallback, const void *)
void RegisterMovableReference (const void **slot)
void ProcessWeakContainer (const void *, TraceDescriptor, WeakCallback, const void *)
void ProcessEphemeron (const void *, const void *, TraceDescriptor, Visitor &)
void AccountMarkedBytes (const HeapObjectHeader &)
void AccountMarkedBytes (BasePage *, size_t)
size_t marked_bytes () const
size_t RecentlyMarkedBytes ()
V8_EXPORT_PRIVATE void Publish () override
MarkingWorklists::PreviouslyNotFullyConstructedWorklist::Local & previously_not_fully_constructed_worklist ()
MarkingWorklists::WeakCallbackWorklist::Local & weak_container_callback_worklist ()
MarkingWorklists::WeakCallbackWorklist::Local & parallel_weak_callback_worklist ()
MarkingWorklists::WeakCustomCallbackWorklist::Local & weak_custom_callback_worklist ()
MarkingWorklists::WriteBarrierWorklist::Local & write_barrier_worklist ()
MarkingWorklists::ConcurrentMarkingBailoutWorklist::Local & concurrent_marking_bailout_worklist ()
MarkingWorklists::EphemeronPairsWorklist::Local & discovered_ephemeron_pairs_worklist ()
MarkingWorklists::EphemeronPairsWorklist::Local & ephemeron_pairs_for_processing_worklist ()
MarkingWorklists::WeakContainersWorklist & weak_containers_worklist ()
CompactionWorklists::MovableReferencesWorklist::Local * movable_slots_worklist ()
bool DidDiscoverNewEphemeronPairs () const
void ResetDidDiscoverNewEphemeronPairs ()
void set_in_atomic_pause ()
Protected Member Functions
void RegisterWeakContainer (HeapObjectHeader &)
Protected Attributes
MarkingWorklists::PreviouslyNotFullyConstructedWorklist::Local previously_not_fully_constructed_worklist_
MarkingWorklists::WeakCallbackWorklist::Local weak_container_callback_worklist_
MarkingWorklists::WeakCallbackWorklist::Local parallel_weak_callback_worklist_
MarkingWorklists::WeakCustomCallbackWorklist::Local weak_custom_callback_worklist_
MarkingWorklists::WriteBarrierWorklist::Local write_barrier_worklist_
MarkingWorklists::ConcurrentMarkingBailoutWorklist::Local concurrent_marking_bailout_worklist_
MarkingWorklists::EphemeronPairsWorklist::Local discovered_ephemeron_pairs_worklist_
MarkingWorklists::EphemeronPairsWorklist::Local ephemeron_pairs_for_processing_worklist_
MarkingWorklists::WeakContainersWorklist & weak_containers_worklist_
std::unique_ptr< CompactionWorklists::MovableReferencesWorklist::Local > movable_slots_worklist_
size_t marked_bytes_ = 0
size_t last_marked_bytes_ = 0
bool in_ephemeron_processing_ = false
bool discovered_new_ephemeron_pairs_ = false
bool in_atomic_pause_ = false
heap::base::CachedUnorderedMap< BasePage *, int64_t, v8::base::hash< BasePage * > > marked_bytes_map_
Detailed Description
Definition at line 112 of file marking-state.h.
Constructor & Destructor Documentation
BasicMarkingState() [1/2]
cppgc::internal::BasicMarkingState::BasicMarkingState (HeapBase & heap, MarkingWorklists & marking_worklists, CompactionWorklists * compaction_worklists)
Definition at line 17 of file marking-state.cc.
    : MarkingStateBase(heap, marking_worklists),
      previously_not_fully_constructed_worklist_(
          *marking_worklists.previously_not_fully_constructed_worklist()),
      weak_container_callback_worklist_(
          *marking_worklists.weak_container_callback_worklist()),
      parallel_weak_callback_worklist_(
          *marking_worklists.parallel_weak_callback_worklist()),
      weak_custom_callback_worklist_(
          *marking_worklists.weak_custom_callback_worklist()),
      write_barrier_worklist_(*marking_worklists.write_barrier_worklist()),
      concurrent_marking_bailout_worklist_(
          *marking_worklists.concurrent_marking_bailout_worklist()),
      discovered_ephemeron_pairs_worklist_(
          *marking_worklists.discovered_ephemeron_pairs_worklist()),
      ephemeron_pairs_for_processing_worklist_(
          *marking_worklists.ephemeron_pairs_for_processing_worklist()),
      weak_containers_worklist_(*marking_worklists.weak_containers_worklist()) {
  if (compaction_worklists) {
    movable_slots_worklist_ =
        std::make_unique<CompactionWorklists::MovableReferencesWorklist::Local>(
            *compaction_worklists->movable_slots_worklist());
  }
}
References cppgc::internal::CompactionWorklists::movable_slots_worklist(), and movable_slots_worklist_.
 BasicMarkingState()
cppgc::internal::BasicMarkingState::~BasicMarkingState () [override]
Definition at line 44 of file marking-state.cc.
                                      {
  DCHECK_EQ(last_marked_bytes_, marked_bytes_);
}
References DCHECK_EQ, last_marked_bytes_, and marked_bytes_.
BasicMarkingState() [2/2]
cppgc::internal::BasicMarkingState::BasicMarkingState (const BasicMarkingState &) [delete]
Member Function Documentation
AccountMarkedBytes() [1/2]
void cppgc::internal::BasicMarkingState::AccountMarkedBytes (BasePage * base_page, size_t marked_bytes) [inline]
Definition at line 351 of file marking-state.h.
                                                                {
  marked_bytes_ += marked_bytes;
  marked_bytes_map_[base_page] += static_cast<int64_t>(marked_bytes);
}
References marked_bytes(), marked_bytes_, and marked_bytes_map_.
AccountMarkedBytes() [2/2]
void cppgc::internal::BasicMarkingState::AccountMarkedBytes (const HeapObjectHeader & header) [inline]
Definition at line 340 of file marking-state.h.
                                                                         {
  const size_t marked_bytes =
      header.IsLargeObject<AccessMode::kAtomic>()
          ? reinterpret_cast<const LargePage*>(BasePage::FromPayload(&header))
                ->PayloadSize()
          : header.AllocatedSize<AccessMode::kAtomic>();
  auto* base_page =
      BasePage::FromPayload(&const_cast<HeapObjectHeader&>(header));
  AccountMarkedBytes(base_page, marked_bytes);
}
References cppgc::internal::HeapObjectHeader::AllocatedSize(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::HeapObjectHeader::IsLargeObject(), cppgc::internal::kAtomic, and marked_bytes().
Referenced by ProcessWeakContainer(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), and cppgc::internal::ConservativeMarkingVisitor::VisitInConstructionConservatively().
concurrent_marking_bailout_worklist()
MarkingWorklists::ConcurrentMarkingBailoutWorklist::Local& cppgc::internal::BasicMarkingState::concurrent_marking_bailout_worklist () [inline]
Definition at line 177 of file marking-state.h.
                                        {
    return concurrent_marking_bailout_worklist_;
  }
References concurrent_marking_bailout_worklist_.
Referenced by v8::internal::ConcurrentUnifiedHeapMarkingVisitor::DeferTraceToMutatorThreadIfConcurrent(), cppgc::internal::ConcurrentMarkingVisitor::DeferTraceToMutatorThreadIfConcurrent(), and cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().
DidDiscoverNewEphemeronPairs()
bool cppgc::internal::BasicMarkingState::DidDiscoverNewEphemeronPairs () const [inline]
Definition at line 197 of file marking-state.h.
                                            {
    return discovered_new_ephemeron_pairs_;
  }
References discovered_new_ephemeron_pairs_.
Referenced by cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().
discovered_ephemeron_pairs_worklist()
MarkingWorklists::EphemeronPairsWorklist::Local& cppgc::internal::BasicMarkingState::discovered_ephemeron_pairs_worklist () [inline]
Definition at line 181 of file marking-state.h.
                                        {
    return discovered_ephemeron_pairs_worklist_;
  }
References discovered_ephemeron_pairs_worklist_.
Referenced by cppgc::internal::MarkerBase::~MarkerBase().
ephemeron_pairs_for_processing_worklist()
MarkingWorklists::EphemeronPairsWorklist::Local& cppgc::internal::BasicMarkingState::ephemeron_pairs_for_processing_worklist () [inline]
Definition at line 185 of file marking-state.h.
                                            {
    return ephemeron_pairs_for_processing_worklist_;
  }
References ephemeron_pairs_for_processing_worklist_.
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), and cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().
marked_bytes()
size_t cppgc::internal::BasicMarkingState::marked_bytes () const [inline]
Definition at line 148 of file marking-state.h.
{ return marked_bytes_; }
References marked_bytes_.
Referenced by AccountMarkedBytes(), cppgc::internal::MarkerBase::AdvanceMarkingWithLimits(), cppgc::internal::anonymous_namespace{marker.cc}::DrainWorklistWithBytesAndTimeDeadline(), and cppgc::internal::MarkerBase::LeaveAtomicPause().
movable_slots_worklist()
CompactionWorklists::MovableReferencesWorklist::Local* cppgc::internal::BasicMarkingState::movable_slots_worklist () [inline]
Definition at line 193 of file marking-state.h.
                           {
    return movable_slots_worklist_.get();
  }
References movable_slots_worklist_.
operator=()
BasicMarkingState& cppgc::internal::BasicMarkingState::operator= (const BasicMarkingState &) [delete]
parallel_weak_callback_worklist()
MarkingWorklists::WeakCallbackWorklist::Local& cppgc::internal::BasicMarkingState::parallel_weak_callback_worklist () [inline]
Definition at line 166 of file marking-state.h.
                                    {
    return parallel_weak_callback_worklist_;
  }
References parallel_weak_callback_worklist_.
Referenced by cppgc::internal::MarkerBase::ProcessWeakness().
previously_not_fully_constructed_worklist()
MarkingWorklists::PreviouslyNotFullyConstructedWorklist::Local& cppgc::internal::BasicMarkingState::previously_not_fully_constructed_worklist () [inline]
Definition at line 158 of file marking-state.h.
                                              {
    return previously_not_fully_constructed_worklist_;
  }
References previously_not_fully_constructed_worklist_.
Referenced by cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().
ProcessEphemeron()
void cppgc::internal::BasicMarkingState::ProcessEphemeron (const void * key, const void * value, TraceDescriptor value_desc, Visitor & visitor) [inline]
Definition at line 306 of file marking-state.h.
                                                           {
  // ProcessEphemeron is not expected to find new ephemerons recursively, which
  // would break the main marking loop.
  DCHECK(!in_ephemeron_processing_);
  in_ephemeron_processing_ = true;
  // Keys are considered live even in incremental/concurrent marking settings
  // because the write barrier for WeakMember ensures that any newly set value
  // after this point is kept alive and does not require the callback.
  const bool key_in_construction =
      HeapObjectHeader::FromObject(key).IsInConstruction<AccessMode::kAtomic>();
  const bool key_considered_as_live =
      key_in_construction
          ? in_atomic_pause_
          : HeapObjectHeader::FromObject(key).IsMarked<AccessMode::kAtomic>();
  DCHECK_IMPLIES(
      key_in_construction && in_atomic_pause_,
      HeapObjectHeader::FromObject(key).IsMarked<AccessMode::kAtomic>());
  if (key_considered_as_live) {
    if (value_desc.base_object_payload) {
      MarkAndPush(value_desc.base_object_payload, value_desc);
    } else {
      // If value_desc.base_object_payload is nullptr, the value is not GCed and
      // should be immediately traced.
      value_desc.callback(&visitor, value);
    }
  } else {
    discovered_ephemeron_pairs_worklist_.Push({key, value, value_desc});
    discovered_new_ephemeron_pairs_ = true;
  }
  in_ephemeron_processing_ = false;
}
References cppgc::TraceDescriptor::base_object_payload, cppgc::TraceDescriptor::callback, DCHECK, DCHECK_IMPLIES, discovered_ephemeron_pairs_worklist_, discovered_new_ephemeron_pairs_, cppgc::internal::HeapObjectHeader::FromObject(), in_atomic_pause_, in_ephemeron_processing_, cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAtomic, v8::internal::key, cppgc::internal::MarkingStateBase::MarkAndPush(), and v8::internal::value.
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), v8::internal::UnifiedHeapMarkingVisitorBase::VisitEphemeron(), and cppgc::internal::MarkingVisitorBase::VisitEphemeron().
ProcessWeakContainer()
void cppgc::internal::BasicMarkingState::ProcessWeakContainer (const void * object, TraceDescriptor desc, WeakCallback callback, const void * data) [inline]
Definition at line 270 of file marking-state.h.
                                                               {
  DCHECK_NOT_NULL(object);
  HeapObjectHeader& header =
      HeapObjectHeader::FromObject(const_cast<void*>(object));
  if (header.IsInConstruction<AccessMode::kAtomic>()) {
    not_fully_constructed_worklist_.Push<AccessMode::kAtomic>(&header);
    return;
  }
  RegisterWeakContainer(header);
  // Only mark the container initially. Its buckets will be processed after
  // marking.
  if (!MarkNoPush(header)) return;
  // Register final weak processing of the backing store.
  RegisterWeakContainerCallback(callback, data);
  // Weak containers might not require tracing. In such cases the callback in
  // the TraceDescriptor will be nullptr. For ephemerons the callback will be
  // non-nullptr so that the container is traced and the ephemeron pairs are
  // processed.
  if (desc.callback) {
    PushMarked(header, desc);
  } else {
    // For weak containers, there's no trace callback and no processing loop to
    // update the marked bytes, hence inline that here.
    AccountMarkedBytes(header);
  }
}
References AccountMarkedBytes(), cppgc::TraceDescriptor::callback, DCHECK_NOT_NULL, cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::kAtomic, cppgc::internal::MarkingStateBase::MarkNoPush(), cppgc::internal::MarkingStateBase::not_fully_constructed_worklist_, cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Push(), cppgc::internal::MarkingStateBase::PushMarked(), RegisterWeakContainer(), and RegisterWeakContainerCallback().
Referenced by cppgc::internal::MarkingVisitorBase::VisitWeakContainer(), and v8::internal::UnifiedHeapMarkingVisitorBase::VisitWeakContainer().
Publish()
void cppgc::internal::BasicMarkingState::Publish () [override], [virtual]
Reimplemented from cppgc::internal::MarkingStateBase.
Reimplemented in cppgc::internal::MutatorMarkingState.
Definition at line 48 of file marking-state.cc.
                                {
  MarkingStateBase::Publish();
  previously_not_fully_constructed_worklist_.Publish();
  weak_container_callback_worklist_.Publish();
  parallel_weak_callback_worklist_.Publish();
  weak_custom_callback_worklist_.Publish();
  write_barrier_worklist_.Publish();
  concurrent_marking_bailout_worklist_.Publish();
  discovered_ephemeron_pairs_worklist_.Publish();
  ephemeron_pairs_for_processing_worklist_.Publish();
  if (movable_slots_worklist_) movable_slots_worklist_->Publish();
  for (const auto& entry : marked_bytes_map_.Take()) {
    entry.first->IncrementMarkedBytes(static_cast<size_t>(entry.second));
  }
}
References concurrent_marking_bailout_worklist_, discovered_ephemeron_pairs_worklist_, ephemeron_pairs_for_processing_worklist_, marked_bytes_map_, movable_slots_worklist_, parallel_weak_callback_worklist_, previously_not_fully_constructed_worklist_, cppgc::internal::MarkingStateBase::Publish(), weak_container_callback_worklist_, weak_custom_callback_worklist_, and write_barrier_worklist_.
Referenced by cppgc::internal::MutatorMarkingState::Publish(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
RecentlyMarkedBytes()
size_t cppgc::internal::BasicMarkingState::RecentlyMarkedBytes () [inline]
Definition at line 151 of file marking-state.h.
                               {
    return marked_bytes_ - std::exchange(last_marked_bytes_, marked_bytes_);
  }
References last_marked_bytes_, and marked_bytes_.
Referenced by cppgc::internal::MarkerBase::AdvanceMarkingWithLimits(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::DrainWorklistWithYielding(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
RegisterMovableReference()
void cppgc::internal::BasicMarkingState::RegisterMovableReference (const void ** slot) [inline]
Definition at line 125 of file marking-state.h.
                                                   {
    if (V8_LIKELY(!movable_slots_worklist_)) return;
#if defined(CPPGC_CAGED_HEAP)
    if (V8_UNLIKELY(!CagedHeapBase::IsWithinCage(slot))) return;
#else // !defined(CPPGC_CAGED_HEAP)
    if (V8_UNLIKELY(heap::base::Stack::IsOnStack(slot))) return;
#endif // !defined(CPPGC_CAGED_HEAP)
    movable_slots_worklist_->Push(slot);
  }
References heap::base::Stack::IsOnStack(), movable_slots_worklist_, V8_LIKELY, and V8_UNLIKELY.
Referenced by v8::internal::UnifiedHeapMarkingVisitorBase::HandleMovableReference(), and cppgc::internal::MarkingVisitorBase::HandleMovableReference().
RegisterWeakContainer()
void cppgc::internal::BasicMarkingState::RegisterWeakContainer (HeapObjectHeader & header) [inline], [protected]
Definition at line 266 of file marking-state.h.
                                                                      {
  weak_containers_worklist_.Push<AccessMode::kAtomic>(&header);
}
References cppgc::internal::kAtomic, cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Push(), and weak_containers_worklist_.
Referenced by ProcessWeakContainer().
RegisterWeakContainerCallback()
void cppgc::internal::BasicMarkingState::RegisterWeakContainerCallback (WeakCallback callback, const void * object) [inline]
Definition at line 254 of file marking-state.h.
                                                                          {
  DCHECK_NOT_NULL(callback);
  weak_container_callback_worklist_.Push({callback, object});
}
References DCHECK_NOT_NULL, and weak_container_callback_worklist_.
Referenced by ProcessWeakContainer().
RegisterWeakCustomCallback()
void cppgc::internal::BasicMarkingState::RegisterWeakCustomCallback (WeakCallback callback, const void * object) [inline]
Definition at line 260 of file marking-state.h.
                                                                       {
  DCHECK_NOT_NULL(callback);
  weak_custom_callback_worklist_.Push({callback, object});
}
References DCHECK_NOT_NULL, and weak_custom_callback_worklist_.
Referenced by v8::internal::UnifiedHeapMarkingVisitorBase::RegisterWeakCallback(), and cppgc::internal::MarkingVisitorBase::RegisterWeakCallback().
RegisterWeakReferenceIfNeeded()
void cppgc::internal::BasicMarkingState::RegisterWeakReferenceIfNeeded (const void * object, TraceDescriptor desc, WeakCallback weak_callback, const void * parameter) [inline]
Definition at line 240 of file marking-state.h.
                           {
  // Filter out already marked values. The write barrier for WeakMember
  // ensures that any newly set value after this point is kept alive and does
  // not require the callback.
  const HeapObjectHeader& header =
      HeapObjectHeader::FromObject(desc.base_object_payload);
  if (!header.IsInConstruction<AccessMode::kAtomic>() &&
      header.IsMarked<AccessMode::kAtomic>())
    return;
  parallel_weak_callback_worklist_.Push({weak_callback, parameter});
}
References cppgc::TraceDescriptor::base_object_payload, cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAtomic, and parallel_weak_callback_worklist_.
Referenced by v8::internal::UnifiedHeapMarkingVisitorBase::VisitWeak(), and cppgc::internal::MarkingVisitorBase::VisitWeak().
ResetDidDiscoverNewEphemeronPairs()
void cppgc::internal::BasicMarkingState::ResetDidDiscoverNewEphemeronPairs () [inline]
Definition at line 201 of file marking-state.h.
                                           {
    discovered_new_ephemeron_pairs_ = false;
  }
References discovered_new_ephemeron_pairs_.
Referenced by cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().
set_in_atomic_pause()
void cppgc::internal::BasicMarkingState::set_in_atomic_pause () [inline]
Definition at line 205 of file marking-state.h.
{ in_atomic_pause_ = true; }
References in_atomic_pause_.
Referenced by cppgc::internal::MarkerBase::EnterAtomicPause().
weak_container_callback_worklist()
MarkingWorklists::WeakCallbackWorklist::Local& cppgc::internal::BasicMarkingState::weak_container_callback_worklist () [inline]
Definition at line 162 of file marking-state.h.
                                     {
    return weak_container_callback_worklist_;
  }
References weak_container_callback_worklist_.
Referenced by cppgc::internal::MarkerBase::ProcessWeakness().
weak_containers_worklist()
MarkingWorklists::WeakContainersWorklist& cppgc::internal::BasicMarkingState::weak_containers_worklist () [inline]
Definition at line 188 of file marking-state.h.
                                                                     {
    return weak_containers_worklist_;
  }
References weak_containers_worklist_.
weak_custom_callback_worklist()
MarkingWorklists::WeakCustomCallbackWorklist::Local& cppgc::internal::BasicMarkingState::weak_custom_callback_worklist () [inline]
Definition at line 170 of file marking-state.h.
                                  {
    return weak_custom_callback_worklist_;
  }
References weak_custom_callback_worklist_.
Referenced by cppgc::internal::MarkerBase::ProcessWeakness().
write_barrier_worklist()
MarkingWorklists::WriteBarrierWorklist::Local& cppgc::internal::BasicMarkingState::write_barrier_worklist () [inline]
Definition at line 173 of file marking-state.h.
                                                                      {
    return write_barrier_worklist_;
  }
References write_barrier_worklist_.
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline(), and cppgc::internal::MarkerBase::WriteBarrierForObject().
Member Data Documentation
concurrent_marking_bailout_worklist_
MarkingWorklists::ConcurrentMarkingBailoutWorklist::Local cppgc::internal::BasicMarkingState::concurrent_marking_bailout_worklist_ [protected]
Definition at line 220 of file marking-state.h.
Referenced by concurrent_marking_bailout_worklist(), and Publish().
discovered_ephemeron_pairs_worklist_
MarkingWorklists::EphemeronPairsWorklist::Local cppgc::internal::BasicMarkingState::discovered_ephemeron_pairs_worklist_ [protected]
Definition at line 222 of file marking-state.h.
Referenced by discovered_ephemeron_pairs_worklist(), cppgc::internal::MutatorMarkingState::FlushDiscoveredEphemeronPairs(), ProcessEphemeron(), and Publish().
discovered_new_ephemeron_pairs_
bool cppgc::internal::BasicMarkingState::discovered_new_ephemeron_pairs_ = false [protected]
Definition at line 234 of file marking-state.h.
Referenced by DidDiscoverNewEphemeronPairs(), ProcessEphemeron(), and ResetDidDiscoverNewEphemeronPairs().
ephemeron_pairs_for_processing_worklist_
MarkingWorklists::EphemeronPairsWorklist::Local cppgc::internal::BasicMarkingState::ephemeron_pairs_for_processing_worklist_ [protected]
Definition at line 224 of file marking-state.h.
Referenced by ephemeron_pairs_for_processing_worklist(), cppgc::internal::MutatorMarkingState::FlushDiscoveredEphemeronPairs(), and Publish().
in_atomic_pause_
bool cppgc::internal::BasicMarkingState::in_atomic_pause_ = false [protected]
Definition at line 235 of file marking-state.h.
Referenced by ProcessEphemeron(), and set_in_atomic_pause().
in_ephemeron_processing_
bool cppgc::internal::BasicMarkingState::in_ephemeron_processing_ = false [protected]
Definition at line 233 of file marking-state.h.
Referenced by ProcessEphemeron().
last_marked_bytes_
size_t cppgc::internal::BasicMarkingState::last_marked_bytes_ = 0 [protected]
Definition at line 232 of file marking-state.h.
Referenced by RecentlyMarkedBytes(), and ~BasicMarkingState().
marked_bytes_
size_t cppgc::internal::BasicMarkingState::marked_bytes_ = 0 [protected]
Definition at line 231 of file marking-state.h.
Referenced by cppgc::internal::ConcurrentMarkingState::AccountDeferredMarkedBytes(), AccountMarkedBytes(), marked_bytes(), RecentlyMarkedBytes(), and ~BasicMarkingState().
marked_bytes_map_
heap::base::CachedUnorderedMap<BasePage*, int64_t, v8::base::hash<BasePage*> > cppgc::internal::BasicMarkingState::marked_bytes_map_ [protected]
Definition at line 237 of file marking-state.h.
Referenced by cppgc::internal::ConcurrentMarkingState::AccountDeferredMarkedBytes(), AccountMarkedBytes(), and Publish().
movable_slots_worklist_
std::unique_ptr<CompactionWorklists::MovableReferencesWorklist::Local> cppgc::internal::BasicMarkingState::movable_slots_worklist_ [protected]
Definition at line 229 of file marking-state.h.
Referenced by BasicMarkingState(), movable_slots_worklist(), Publish(), and RegisterMovableReference().
parallel_weak_callback_worklist_
MarkingWorklists::WeakCallbackWorklist::Local cppgc::internal::BasicMarkingState::parallel_weak_callback_worklist_ [protected]
Definition at line 215 of file marking-state.h.
Referenced by parallel_weak_callback_worklist(), Publish(), and RegisterWeakReferenceIfNeeded().
previously_not_fully_constructed_worklist_
MarkingWorklists::PreviouslyNotFullyConstructedWorklist::Local cppgc::internal::BasicMarkingState::previously_not_fully_constructed_worklist_ [protected]
Definition at line 211 of file marking-state.h.
Referenced by cppgc::internal::MutatorMarkingState::FlushNotFullyConstructedObjects(), previously_not_fully_constructed_worklist(), and Publish().
weak_container_callback_worklist_
MarkingWorklists::WeakCallbackWorklist::Local cppgc::internal::BasicMarkingState::weak_container_callback_worklist_ [protected]
Definition at line 213 of file marking-state.h.
Referenced by Publish(), RegisterWeakContainerCallback(), and weak_container_callback_worklist().
weak_containers_worklist_
MarkingWorklists::WeakContainersWorklist& cppgc::internal::BasicMarkingState::weak_containers_worklist_ [protected]
Definition at line 225 of file marking-state.h.
Referenced by cppgc::internal::MutatorMarkingState::IsMarkedWeakContainer(), RegisterWeakContainer(), cppgc::internal::MutatorMarkingState::ReTraceMarkedWeakContainer(), and weak_containers_worklist().
weak_custom_callback_worklist_
MarkingWorklists::WeakCustomCallbackWorklist::Local cppgc::internal::BasicMarkingState::weak_custom_callback_worklist_ [protected]
Definition at line 217 of file marking-state.h.
Referenced by Publish(), RegisterWeakCustomCallback(), and weak_custom_callback_worklist().
write_barrier_worklist_
MarkingWorklists::WriteBarrierWorklist::Local cppgc::internal::BasicMarkingState::write_barrier_worklist_ [protected]
Definition at line 218 of file marking-state.h.
Referenced by Publish(), and write_barrier_worklist().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-state.h
/mnt/V8SourceCode/src/heap/cppgc/marking-state.cc