v8::internal::MemoryMeasurement Class Reference
#include <memory-measurement.h>
Classes
struct Request
Public Member Functions
MemoryMeasurement (Isolate *isolate)
bool EnqueueRequest (std::unique_ptr< v8::MeasureMemoryDelegate > delegate, v8::MeasureMemoryExecution execution, const std::vector< Handle< NativeContext >> contexts)
std::vector< Address > StartProcessing ()
void FinishProcessing (const NativeContextStats &stats)
Static Public Member Functions
static std::unique_ptr< v8::MeasureMemoryDelegate > DefaultDelegate (v8::Isolate *isolate, v8::Local< v8::Context > context, v8::Local< v8::Promise::Resolver > promise, v8::MeasureMemoryMode mode)
Private Member Functions
void ScheduleReportingTask ()
void ReportResults ()
void ScheduleGCTask (v8::MeasureMemoryExecution execution)
bool IsGCTaskPending (v8::MeasureMemoryExecution execution)
void SetGCTaskPending (v8::MeasureMemoryExecution execution)
void SetGCTaskDone (v8::MeasureMemoryExecution execution)
int NextGCTaskDelayInSeconds ()
Private Attributes
std::list< Request > received_
std::list< Request > processing_
std::list< Request > done_
Isolate * isolate_
std::shared_ptr< v8::TaskRunner > task_runner_
bool reporting_task_pending_ = false
bool delayed_gc_task_pending_ = false
bool eager_gc_task_pending_ = false
base::RandomNumberGenerator random_number_generator_
Static Private Attributes
static const int kGCTaskDelayInSeconds = 10
Detailed Description
Definition at line 25 of file memory-measurement.h.
Constructor & Destructor Documentation
MemoryMeasurement()
v8::internal::MemoryMeasurement::MemoryMeasurement (Isolate * isolate) [explicit]
Definition at line 183 of file memory-measurement.cc.
    : isolate_(isolate),
      task_runner_(isolate->heap()->GetForegroundTaskRunner()),
      random_number_generator_() {
  if (v8_flags.random_seed) {
    random_number_generator_.SetSeed(v8_flags.random_seed);
  }
}
References random_number_generator_, v8::base::RandomNumberGenerator::SetSeed(), and v8::internal::v8_flags.
Member Function Documentation
DefaultDelegate()
std::unique_ptr< v8::MeasureMemoryDelegate > v8::internal::MemoryMeasurement::DefaultDelegate (v8::Isolate * isolate, v8::Local< v8::Context > context, v8::Local< v8::Promise::Resolver > promise, v8::MeasureMemoryMode mode) [static]
Definition at line 368 of file memory-measurement.cc.
                                                                  {
  return std::make_unique<MeasureMemoryDelegate>(isolate, context, promise,
                                                 mode);
}
References mode().
Referenced by v8::internal::Heap::CreateDefaultMeasureMemoryDelegate().
EnqueueRequest()
bool v8::internal::MemoryMeasurement::EnqueueRequest (std::unique_ptr< v8::MeasureMemoryDelegate > delegate, v8::MeasureMemoryExecution execution, const std::vector< Handle< NativeContext >> contexts)
Definition at line 192 of file memory-measurement.cc.
                                                     {
  int length = static_cast<int>(contexts.size());
  DirectHandle<WeakFixedArray> weak_contexts =
      isolate_->factory()->NewWeakFixedArray(length);
  for (int i = 0; i < length; ++i) {
    weak_contexts->set(i, MakeWeak(*contexts[i]));
  }
  Handle<WeakFixedArray> global_weak_contexts =
      isolate_->global_handles()->Create(*weak_contexts);
  Request request = {std::move(delegate), // delegate
                     global_weak_contexts, // contexts
                     std::vector<size_t>(length), // sizes
                     0u, // shared
                     0u, // wasm_code
                     0u, // wasm_metadata
                     {}}; // timer
  request.timer.Start();
  received_.push_back(std::move(request));
  ScheduleGCTask(execution);
  return true;
}
References v8::internal::GlobalHandles::Create(), v8::internal::Isolate::factory(), v8::internal::Isolate::global_handles(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::length, v8::internal::MakeWeak(), v8::internal::FactoryBase< Impl >::NewWeakFixedArray(), received_, ScheduleGCTask(), v8::base::ElapsedTimer::Start(), and v8::internal::MemoryMeasurement::Request::timer.
FinishProcessing()
void v8::internal::MemoryMeasurement::FinishProcessing (const NativeContextStats & stats)
Definition at line 234 of file memory-measurement.cc.
                                                                        {
  if (processing_.empty()) return;
  size_t shared = stats.Get(MarkingWorklists::kSharedContext);
#if V8_ENABLE_WEBASSEMBLY
  size_t wasm_code = wasm::GetWasmCodeManager()->committed_code_space();
  size_t wasm_metadata =
      wasm::GetWasmEngine()->EstimateCurrentMemoryConsumption() +
      wasm::GetWasmImportWrapperCache()->EstimateCurrentMemoryConsumption();
#endif
  while (!processing_.empty()) {
    Request request = std::move(processing_.front());
    processing_.pop_front();
    for (int i = 0; i < static_cast<int>(request.sizes.size()); i++) {
      Tagged<HeapObject> context;
      if (!request.contexts->get(i).GetHeapObject(&context)) {
        continue;
      }
      request.sizes[i] = stats.Get(context.ptr());
    }
    request.shared = shared;
#if V8_ENABLE_WEBASSEMBLY
    request.wasm_code = wasm_code;
    request.wasm_metadata = wasm_metadata;
#endif
    done_.push_back(std::move(request));
  }
  ScheduleReportingTask();
}
References v8::internal::wasm::WasmCodeManager::committed_code_space(), v8::internal::MemoryMeasurement::Request::contexts, done_, v8::internal::wasm::WasmEngine::EstimateCurrentMemoryConsumption(), v8::internal::wasm::WasmImportWrapperCache::EstimateCurrentMemoryConsumption(), v8::internal::NativeContextStats::Get(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MarkingWorklists::kSharedContext, processing_, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), ScheduleReportingTask(), v8::internal::MemoryMeasurement::Request::shared, v8::internal::MemoryMeasurement::Request::sizes, v8::internal::MemoryMeasurement::Request::wasm_code, and v8::internal::MemoryMeasurement::Request::wasm_metadata.
Referenced by v8::internal::MarkCompactCollector::CollectGarbage().
IsGCTaskPending()
bool v8::internal::MemoryMeasurement::IsGCTaskPending (v8::MeasureMemoryExecution execution) [private]
Definition at line 274 of file memory-measurement.cc.
                                                                          {
  DCHECK(execution == v8::MeasureMemoryExecution::kEager ||
         execution == v8::MeasureMemoryExecution::kDefault);
  return execution == v8::MeasureMemoryExecution::kEager
             ? eager_gc_task_pending_
             : delayed_gc_task_pending_;
}
References v8::internal::DCHECK(), delayed_gc_task_pending_, eager_gc_task_pending_, v8::kDefault, and v8::kEager.
Referenced by ScheduleGCTask().
NextGCTaskDelayInSeconds()
int v8::internal::MemoryMeasurement::NextGCTaskDelayInSeconds () [private]
Definition at line 332 of file memory-measurement.cc.
                                                {
  return kGCTaskDelayInSeconds +
         random_number_generator_.NextInt(kGCTaskDelayInSeconds);
}
References kGCTaskDelayInSeconds, v8::base::RandomNumberGenerator::NextInt(), and random_number_generator_.
Referenced by ScheduleGCTask().
ReportResults()
void v8::internal::MemoryMeasurement::ReportResults () [private]
Definition at line 337 of file memory-measurement.cc.
                                      {
  while (!done_.empty() && !isolate_->is_execution_terminating()) {
    Request request = std::move(done_.front());
    done_.pop_front();
    HandleScope handle_scope(isolate_);
    v8::LocalVector<v8::Context> contexts(
        reinterpret_cast<v8::Isolate*>(isolate_));
    std::vector<size_t> size_in_bytes;
    DCHECK_EQ(request.sizes.size(),
              static_cast<size_t>(request.contexts->length()));
    for (int i = 0; i < request.contexts->length(); i++) {
      Tagged<HeapObject> raw_context;
      if (!request.contexts->get(i).GetHeapObject(&raw_context)) {
        continue;
      }
      Local<v8::Context> context = Utils::Convert<HeapObject, v8::Context>(
          direct_handle(raw_context, isolate_));
      contexts.push_back(context);
      size_in_bytes.push_back(request.sizes[i]);
    }
    request.delegate->MeasurementComplete(
        {{contexts.begin(), contexts.end()},
         {size_in_bytes.begin(), size_in_bytes.end()},
         request.shared,
         request.wasm_code,
         request.wasm_metadata});
    isolate_->counters()->measure_memory_delay_ms()->AddSample(
        static_cast<int>(request.timer.Elapsed().InMilliseconds()));
  }
}
References v8::LocalVector< T >::begin(), v8::internal::MemoryMeasurement::Request::contexts, v8::internal::Isolate::counters(), DCHECK_EQ, v8::internal::MemoryMeasurement::Request::delegate, v8::internal::direct_handle(), done_, v8::base::ElapsedTimer::Elapsed(), v8::LocalVector< T >::end(), v8::base::TimeDelta::InMilliseconds(), v8::internal::Isolate::is_execution_terminating(), isolate_, v8::LocalVector< T >::push_back(), v8::internal::raw_context, v8::internal::MemoryMeasurement::Request::shared, v8::internal::MemoryMeasurement::Request::sizes, v8::internal::MemoryMeasurement::Request::timer, v8::internal::MemoryMeasurement::Request::wasm_code, and v8::internal::MemoryMeasurement::Request::wasm_metadata.
Referenced by ScheduleReportingTask().
ScheduleGCTask()
void v8::internal::MemoryMeasurement::ScheduleGCTask (v8::MeasureMemoryExecution execution) [private]
Definition at line 302 of file memory-measurement.cc.
                                                                         {
  if (execution == v8::MeasureMemoryExecution::kLazy) return;
  if (IsGCTaskPending(execution)) return;
  SetGCTaskPending(execution);
  auto task = MakeCancelableTask(isolate_, [this, execution] {
    SetGCTaskDone(execution);
    if (received_.empty()) return;
    Heap* heap = isolate_->heap();
    if (v8_flags.incremental_marking) {
      if (heap->incremental_marking()->IsStopped()) {
        heap->StartIncrementalMarking(GCFlag::kNoFlags,
                                      GarbageCollectionReason::kMeasureMemory);
      } else {
        if (execution == v8::MeasureMemoryExecution::kEager) {
          heap->FinalizeIncrementalMarkingAtomically(
              GarbageCollectionReason::kMeasureMemory);
        }
        ScheduleGCTask(execution);
      }
    } else {
      heap->CollectGarbage(OLD_SPACE, GarbageCollectionReason::kMeasureMemory);
    }
  });
  if (execution == v8::MeasureMemoryExecution::kEager) {
    task_runner_->PostTask(std::move(task));
  } else {
    task_runner_->PostDelayedTask(std::move(task), NextGCTaskDelayInSeconds());
  }
}
References v8::internal::Isolate::heap(), IsGCTaskPending(), isolate_, v8::kEager, v8::kLazy, v8::internal::kMeasureMemory, v8::internal::kNoFlags, v8::internal::MakeCancelableTask(), NextGCTaskDelayInSeconds(), v8::internal::OLD_SPACE, received_, SetGCTaskDone(), SetGCTaskPending(), task_runner_, and v8::internal::v8_flags.
Referenced by EnqueueRequest().
ScheduleReportingTask()
void v8::internal::MemoryMeasurement::ScheduleReportingTask () [private]
Definition at line 265 of file memory-measurement.cc.
                                              {
  if (reporting_task_pending_) return;
  reporting_task_pending_ = true;
  task_runner_->PostTask(MakeCancelableTask(isolate_, [this] {
    reporting_task_pending_ = false;
    ReportResults();
  }));
}
References isolate_, v8::internal::MakeCancelableTask(), reporting_task_pending_, ReportResults(), and task_runner_.
Referenced by FinishProcessing().
SetGCTaskDone()
void v8::internal::MemoryMeasurement::SetGCTaskDone (v8::MeasureMemoryExecution execution) [private]
Definition at line 292 of file memory-measurement.cc.
                                                                        {
  DCHECK(execution == v8::MeasureMemoryExecution::kEager ||
         execution == v8::MeasureMemoryExecution::kDefault);
  if (execution == v8::MeasureMemoryExecution::kEager) {
    eager_gc_task_pending_ = false;
  } else {
    delayed_gc_task_pending_ = false;
  }
}
References v8::internal::DCHECK(), delayed_gc_task_pending_, eager_gc_task_pending_, v8::kDefault, and v8::kEager.
Referenced by ScheduleGCTask().
SetGCTaskPending()
void v8::internal::MemoryMeasurement::SetGCTaskPending (v8::MeasureMemoryExecution execution) [private]
Definition at line 282 of file memory-measurement.cc.
                                                                           {
  DCHECK(execution == v8::MeasureMemoryExecution::kEager ||
         execution == v8::MeasureMemoryExecution::kDefault);
  if (execution == v8::MeasureMemoryExecution::kEager) {
    eager_gc_task_pending_ = true;
  } else {
    delayed_gc_task_pending_ = true;
  }
}
References v8::internal::DCHECK(), delayed_gc_task_pending_, eager_gc_task_pending_, v8::kDefault, and v8::kEager.
Referenced by ScheduleGCTask().
StartProcessing()
std::vector< Address > v8::internal::MemoryMeasurement::StartProcessing ()
Definition at line 217 of file memory-measurement.cc.
                                                      {
  if (received_.empty()) return {};
  std::unordered_set<Address> unique_contexts;
  DCHECK(processing_.empty());
  processing_ = std::move(received_);
  for (const auto& request : processing_) {
    DirectHandle<WeakFixedArray> contexts = request.contexts;
    for (int i = 0; i < contexts->length(); i++) {
      Tagged<HeapObject> context;
      if (contexts->get(i).GetHeapObject(&context)) {
        unique_contexts.insert(context.ptr());
      }
    }
  }
  return std::vector<Address>(unique_contexts.begin(), unique_contexts.end());
}
References v8::internal::DCHECK(), processing_, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and received_.
Referenced by v8::internal::MarkCompactCollector::StartMarking().
Member Data Documentation
delayed_gc_task_pending_
bool v8::internal::MemoryMeasurement::delayed_gc_task_pending_ = false [private]
Definition at line 64 of file memory-measurement.h.
Referenced by IsGCTaskPending(), SetGCTaskDone(), and SetGCTaskPending().
done_
std::list<Request> v8::internal::MemoryMeasurement::done_ [private]
Definition at line 60 of file memory-measurement.h.
Referenced by FinishProcessing(), and ReportResults().
eager_gc_task_pending_
bool v8::internal::MemoryMeasurement::eager_gc_task_pending_ = false [private]
Definition at line 65 of file memory-measurement.h.
Referenced by IsGCTaskPending(), SetGCTaskDone(), and SetGCTaskPending().
isolate_
Isolate* v8::internal::MemoryMeasurement::isolate_ [private]
Definition at line 61 of file memory-measurement.h.
Referenced by EnqueueRequest(), ReportResults(), ScheduleGCTask(), and ScheduleReportingTask().
kGCTaskDelayInSeconds
const int v8::internal::MemoryMeasurement::kGCTaskDelayInSeconds = 10 [static], [private]
Definition at line 40 of file memory-measurement.h.
Referenced by NextGCTaskDelayInSeconds().
processing_
std::list<Request> v8::internal::MemoryMeasurement::processing_ [private]
Definition at line 59 of file memory-measurement.h.
Referenced by FinishProcessing(), and StartProcessing().
random_number_generator_
base::RandomNumberGenerator v8::internal::MemoryMeasurement::random_number_generator_ [private]
Definition at line 66 of file memory-measurement.h.
Referenced by MemoryMeasurement(), and NextGCTaskDelayInSeconds().
received_
std::list<Request> v8::internal::MemoryMeasurement::received_ [private]
Definition at line 58 of file memory-measurement.h.
Referenced by EnqueueRequest(), ScheduleGCTask(), and StartProcessing().
reporting_task_pending_
bool v8::internal::MemoryMeasurement::reporting_task_pending_ = false [private]
Definition at line 63 of file memory-measurement.h.
Referenced by ScheduleReportingTask().
task_runner_
std::shared_ptr<v8::TaskRunner> v8::internal::MemoryMeasurement::task_runner_ [private]
Definition at line 62 of file memory-measurement.h.
Referenced by ScheduleGCTask(), and ScheduleReportingTask().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/memory-measurement.h
/mnt/V8SourceCode/src/heap/memory-measurement.cc