v8::bigint::RWDigits Class Reference
#include <bigint.h>
Classes
class WritableDigitReference
Public Member Functions
RWDigits (digit_t *mem, int len)
RWDigits (RWDigits src, int offset, int len)
RWDigits operator+ (int i)
WritableDigitReference operator[] (int i)
digit_t * digits ()
void set_len (int len)
void Clear ()
Additional Inherited Members
Detailed Description
Definition at line 138 of file bigint.h.
Constructor & Destructor Documentation
RWDigits() [1/2]
v8::bigint::RWDigits::RWDigits (digit_t * mem, int len) [inline]
Definition at line 140 of file bigint.h.
: Digits(mem, len) {}
Referenced by operator+().
RWDigits() [2/2]
v8::bigint::RWDigits::RWDigits (RWDigits src, int offset, int len) [inline]
Definition at line 141 of file bigint.h.
: Digits(src, offset, len) {}
Member Function Documentation
Clear()
void v8::bigint::RWDigits::Clear () [inline]
Definition at line 193 of file bigint.h.
{ memset(digits_, 0, len_ * sizeof(digit_t)); }
References v8::bigint::Digits::digits_, and v8::bigint::Digits::len_.
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine(), v8::bigint::ProcessorImpl::Divide(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::DivideBasecase(), v8::bigint::ProcessorImpl::DivideSchoolbook(), v8::bigint::ProcessorImpl::KaratsubaChunk(), v8::bigint::ProcessorImpl::Modulo(), v8::bigint::ProcessorImpl::Multiply(), v8::bigint::ProcessorImpl::MultiplySchoolbook(), and v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::NormalizeAndRecombine().
digits()
digit_t* v8::bigint::RWDigits::digits () [inline]
Definition at line 190 of file bigint.h.
{ return digits_; }
References v8::bigint::Digits::digits_.
Referenced by v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::DivideBasecase(), and v8::bigint::ProcessorImpl::FromStringLarge().
operator+()
RWDigits v8::bigint::RWDigits::operator+ (int i) [inline]
Definition at line 142 of file bigint.h.
                            {
    BIGINT_H_DCHECK(i >= 0 && i <= len_);
    return RWDigits(digits_ + i, len_ - i);
  }
References BIGINT_H_DCHECK, v8::bigint::Digits::digits_, v8::bigint::Digits::len_, and RWDigits().
operator[]()
WritableDigitReference v8::bigint::RWDigits::operator[] (int i) [inline]
Definition at line 184 of file bigint.h.
                                           {
    BIGINT_H_DCHECK(i >= 0 && i < len_);
    return WritableDigitReference(digits_ + i);
  }
References BIGINT_H_DCHECK, v8::bigint::Digits::digits_, and v8::bigint::Digits::len_.
set_len()
void v8::bigint::RWDigits::set_len (int len) [inline]
Definition at line 191 of file bigint.h.
{ len_ = len; }
References v8::bigint::Digits::len(), and v8::bigint::Digits::len_.
Referenced by v8::bigint::ProcessorImpl::FromStringClassic().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/bigint/bigint.h