v8::internal::maglev::Phi Class Reference
#include <maglev-ir.h>
Public Types
using List = base::ThreadedList< Phi >
using Key = compiler::turboshaft::SnapshotTable< ValueNode * >::Key
Public Member Functions
Phi (uint64_t bitfield, MergePointInterpreterFrameState *merge_state, interpreter::Register owner)
Input & backedge_input ()
interpreter::Register owner () const
const MergePointInterpreterFrameState * merge_state () const
bool is_exception_phi () const
bool is_loop_phi () const
bool is_backedge_offset (int i) const
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
BasicBlock * predecessor_at (int i)
void RecordUseReprHint (UseRepresentation repr)
void RecordUseReprHint (UseRepresentationSet repr_mask)
UseRepresentationSet get_uses_repr_hints ()
UseRepresentationSet get_same_loop_uses_repr_hints ()
NodeType post_loop_type () const
void merge_post_loop_type (NodeType type)
void set_post_loop_type (NodeType type)
void promote_post_loop_type ()
void merge_type (NodeType type)
void set_type (NodeType type)
NodeType type () const
Key key () const
void set_key (Key key)
bool has_key () const
void SetUseRequires31BitValue ()
bool uses_require_31_bit_value () const
void set_uses_require_31_bit_value ()
bool is_unmerged_loop_phi () const
Private Types
using Base = ValueNodeT< Phi >
using HasKeyFlag = NextBitField< bool, 1 >
using Requires31BitValueFlag = HasKeyFlag::Next< bool, 1 >
using LoopPhiAfterLoopFlag = Requires31BitValueFlag::Next< bool, 1 >
Private Member Functions
Phi ** next ()
Private Attributes
const interpreter::Register owner_
UseRepresentationSet uses_repr_hint_ = {}
UseRepresentationSet same_loop_uses_repr_hint_ = {}
Phi * next_ = nullptr
MergePointInterpreterFrameState *const merge_state_
xx xx xx xx xx xx xx xx xx
union {
 struct {
  NodeType type_
  NodeType post_loop_type_
 }
 Key key_
};
Additional Inherited Members
Detailed Description
Definition at line 9840 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Phi::Base = ValueNodeT<Phi> [private]
Definition at line 9841 of file maglev-ir.h.
HasKeyFlag
using v8::internal::maglev::Phi::HasKeyFlag = NextBitField<bool, 1> [private]
Definition at line 9961 of file maglev-ir.h.
Key
using v8::internal::maglev::Phi::Key = compiler::turboshaft::SnapshotTable<ValueNode*>::Key
Definition at line 9932 of file maglev-ir.h.
List
using v8::internal::maglev::Phi::List = base::ThreadedList<Phi>
Definition at line 9844 of file maglev-ir.h.
LoopPhiAfterLoopFlag
using v8::internal::maglev::Phi::LoopPhiAfterLoopFlag = Requires31BitValueFlag::Next<bool, 1> [private]
Definition at line 9963 of file maglev-ir.h.
Requires31BitValueFlag
using v8::internal::maglev::Phi::Requires31BitValueFlag = HasKeyFlag::Next<bool, 1> [private]
Definition at line 9962 of file maglev-ir.h.
Constructor & Destructor Documentation
Phi()
v8::internal::maglev::Phi::Phi (uint64_t bitfield, MergePointInterpreterFrameState * merge_state, interpreter::Register owner) [inline]
Definition at line 9847 of file maglev-ir.h.
      : Base(bitfield),
        owner_(owner),
        merge_state_(merge_state),
        type_(NodeType::kUnknown),
        post_loop_type_(NodeType::kUnknown) {
    DCHECK_NOT_NULL(merge_state);
  }
References DCHECK_NOT_NULL, and v8::internal::kUnknown.
Member Function Documentation
backedge_input()
Input& v8::internal::maglev::Phi::backedge_input () [inline]
Definition at line 9857 of file maglev-ir.h.
{ return input(input_count() - 1); }
References v8::internal::compiler::turboshaft::detail::input_count().
GenerateCode()
void v8::internal::maglev::Phi::GenerateCode (MaglevAssembler * , const ProcessingState &)
get_same_loop_uses_repr_hints()
UseRepresentationSet v8::internal::maglev::Phi::get_same_loop_uses_repr_hints () [inline]
Definition at line 9898 of file maglev-ir.h.
                                                       {
    return same_loop_uses_repr_hint_;
  }
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
get_uses_repr_hints()
UseRepresentationSet v8::internal::maglev::Phi::get_uses_repr_hints () [inline]
Definition at line 9897 of file maglev-ir.h.
{ return uses_repr_hint_; }
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
has_key()
bool v8::internal::maglev::Phi::has_key () const [inline]
Definition at line 9943 of file maglev-ir.h.
{ return HasKeyFlag::decode(bitfield()); }
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged().
is_backedge_offset()
bool v8::internal::maglev::Phi::is_backedge_offset (int i) const [inline]
Definition at line 9871 of file maglev-ir.h.
                                       {
    return is_loop_phi() && i == input_count() - 1;
  }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), and v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
is_exception_phi()
bool v8::internal::maglev::Phi::is_exception_phi () const [inline]
Definition at line 9868 of file maglev-ir.h.
{ return input_count() == 0; }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
is_loop_phi()
bool v8::internal::maglev::Phi::is_loop_phi () const
Definition at line 126 of file maglev-ir.cc.
{ return merge_state()->is_loop(); }
References v8::internal::maglev::MergePointInterpreterFrameState::is_loop(), and merge_state().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiInputsTagged(), is_unmerged_loop_phi(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), RecordUseReprHint(), and SetUseRequires31BitValue().
is_unmerged_loop_phi()
bool v8::internal::maglev::Phi::is_unmerged_loop_phi () const
Definition at line 128 of file maglev-ir.cc.
                                     {
  DCHECK(is_loop_phi());
  return merge_state()->is_unmerged_loop();
}
References v8::internal::DCHECK(), is_loop_phi(), v8::internal::maglev::MergePointInterpreterFrameState::is_unmerged_loop(), and merge_state().
Referenced by RecordUseReprHint().
key()
Key v8::internal::maglev::Phi::key () const [inline]
Definition at line 9933 of file maglev-ir.h.
                  {
    DCHECK(has_key());
    return key_;
  }
References DCHECK.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged().
merge_post_loop_type()
void v8::internal::maglev::Phi::merge_post_loop_type (NodeType type) [inline]
Definition at line 9903 of file maglev-ir.h.
                                           {
    DCHECK(!has_key());
    post_loop_type_ = UnionType(post_loop_type_, type);
  }
References DCHECK, v8::internal::tracing::type, and v8::internal::maglev::UnionType().
merge_state()
const MergePointInterpreterFrameState* v8::internal::maglev::Phi::merge_state () const [inline]
Definition at line 9860 of file maglev-ir.h.
                                                             {
    return merge_state_;
  }
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), is_loop_phi(), is_unmerged_loop_phi(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), and RecordUseReprHint().
merge_type()
void v8::internal::maglev::Phi::merge_type (NodeType type) [inline]
Definition at line 9919 of file maglev-ir.h.
                                 {
    DCHECK(!has_key());
    type_ = UnionType(type_, type);
  }
References DCHECK, v8::internal::tracing::type, and v8::internal::maglev::UnionType().
next()
Phi** v8::internal::maglev::Phi::next () [inline], [private]
Definition at line 9959 of file maglev-ir.h.
{ return &next_; }
owner()
interpreter::Register v8::internal::maglev::Phi::owner () const [inline]
Definition at line 9859 of file maglev-ir.h.
{ return owner_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
post_loop_type()
NodeType v8::internal::maglev::Phi::post_loop_type () const [inline]
Definition at line 9902 of file maglev-ir.h.
{ return post_loop_type_; }
predecessor_at()
BasicBlock * v8::internal::maglev::Phi::predecessor_at (int i)
Definition at line 59 of file maglev-ir.cc.
                                     {
  return merge_state_->predecessor_at(i);
}
References merge_state_, and v8::internal::maglev::MergePointInterpreterFrameState::predecessor_at().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiInputsTagged(), and v8::internal::maglev::MaglevPhiRepresentationSelector::GetReplacementForPhiInputConversion().
PrintParams()
void v8::internal::maglev::Phi::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8364 of file maglev-ir.cc.
                                                                 {
  os << "(" << (owner().is_valid() ? owner().ToString() : "VO") << ")";
}
References v8::internal::interpreter::Register::is_valid(), owner(), and v8::internal::interpreter::Register::ToString().
promote_post_loop_type()
void v8::internal::maglev::Phi::promote_post_loop_type () [inline]
Definition at line 9912 of file maglev-ir.h.
                                {
    DCHECK(!has_key());
    DCHECK(is_unmerged_loop_phi());
    DCHECK(NodeTypeIs(post_loop_type_, type_));
    type_ = post_loop_type_;
  }
References DCHECK, and v8::internal::maglev::NodeTypeIs().
RecordUseReprHint() [1/2]
void v8::internal::maglev::Phi::RecordUseReprHint (UseRepresentation repr) [inline]
Definition at line 9891 of file maglev-ir.h.
                                                 {
    RecordUseReprHint(UseRepresentationSet{repr});
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::RecordUseReprHint().
RecordUseReprHint() [2/2]
void v8::internal::maglev::Phi::RecordUseReprHint (UseRepresentationSet repr_mask)
Definition at line 133 of file maglev-ir.cc.
                                                          {
  if (is_loop_phi() && is_unmerged_loop_phi()) {
    same_loop_uses_repr_hint_.Add(repr_mask);
  }
  if (!repr_mask.is_subset_of(uses_repr_hint_)) {
    uses_repr_hint_.Add(repr_mask);
    // Propagate in inputs, ignoring unbounded loop backedges.
    int bound_inputs = input_count();
    if (merge_state()->is_unmerged_loop()) --bound_inputs;
    for (int i = 0; i < bound_inputs; i++) {
      if (Phi* phi_input = input(i).node()->TryCast<Phi>()) {
        phi_input->RecordUseReprHint(repr_mask);
      }
    }
  }
}
References v8::base::EnumSet< E, T >::Add(), v8::internal::compiler::turboshaft::detail::input_count(), is_loop_phi(), v8::base::EnumSet< E, T >::is_subset_of(), is_unmerged_loop_phi(), merge_state(), same_loop_uses_repr_hint_, and uses_repr_hint_.
set_key()
void v8::internal::maglev::Phi::set_key (Key key) [inline]
Definition at line 9937 of file maglev-ir.h.
                        {
    set_bitfield(bitfield() | HasKeyFlag::encode(true));
    key_ = key;
  }
References v8::internal::key.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged().
set_post_loop_type()
void v8::internal::maglev::Phi::set_post_loop_type (NodeType type) [inline]
Definition at line 9907 of file maglev-ir.h.
                                         {
    DCHECK(!has_key());
    DCHECK(is_unmerged_loop_phi());
    post_loop_type_ = type;
  }
References DCHECK, and v8::internal::tracing::type.
set_type()
void v8::internal::maglev::Phi::set_type (NodeType type) [inline]
Definition at line 9923 of file maglev-ir.h.
                               {
    DCHECK(!has_key());
    type_ = type;
  }
References DCHECK, and v8::internal::tracing::type.
set_uses_require_31_bit_value()
void v8::internal::maglev::Phi::set_uses_require_31_bit_value () [inline]
Definition at line 9951 of file maglev-ir.h.
                                       {
    set_bitfield(bitfield() | Requires31BitValueFlag::encode(true));
  }
Referenced by SetUseRequires31BitValue().
SetUseRequires31BitValue()
void v8::internal::maglev::Phi::SetUseRequires31BitValue ()
Definition at line 153 of file maglev-ir.cc.
                                   {
  if (uses_require_31_bit_value()) return;
  set_uses_require_31_bit_value();
  auto inputs =
      is_loop_phi() ? merge_state_->predecessors_so_far() : input_count();
  for (uint32_t i = 0; i < inputs; ++i) {
    ValueNode* input_node = input(i).node();
    DCHECK(input_node);
    if (auto phi = input_node->TryCast<Phi>()) {
      phi->SetUseRequires31BitValue();
    }
  }
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), is_loop_phi(), merge_state_, v8::internal::maglev::MergePointInterpreterFrameState::predecessors_so_far(), set_uses_require_31_bit_value(), v8::internal::maglev::NodeBase::TryCast(), and uses_require_31_bit_value().
SetValueLocationConstraints()
void v8::internal::maglev::Phi::SetValueLocationConstraints ()
type()
NodeType v8::internal::maglev::Phi::type () const [inline]
Definition at line 9927 of file maglev-ir.h.
                        {
    DCHECK(!has_key());
    return type_;
  }
References DCHECK.
uses_require_31_bit_value()
bool v8::internal::maglev::Phi::uses_require_31_bit_value () const [inline]
Definition at line 9948 of file maglev-ir.h.
                                         {
    return Requires31BitValueFlag::decode(bitfield());
  }
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), SetUseRequires31BitValue(), and v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi().
VerifyInputs()
void v8::internal::maglev::Phi::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 900 of file maglev-ir.cc.
                                                                {
  switch (value_representation()) {
#define CASE_REPR(repr) \
  case ValueRepresentation::k##repr: \
    for (int i = 0; i < input_count(); i++) { \
      CheckValueInputIs(this, i, ValueRepresentation::k##repr, \
                        graph_labeller); \
    } \
    break;
    CASE_REPR(Tagged)
    CASE_REPR(Int32)
    CASE_REPR(Uint32)
    CASE_REPR(Float64)
    CASE_REPR(HoleyFloat64)
#undef CASE_REPR
    case ValueRepresentation::kIntPtr:
      UNREACHABLE();
  }
}
References CASE_REPR, v8::internal::maglev::HoleyFloat64, v8::internal::maglev::kIntPtr, and v8::internal::UNREACHABLE().
Member Data Documentation
union { ... } [private]
key_
Key v8::internal::maglev::Phi::key_
Definition at line 9989 of file maglev-ir.h.
merge_state_
MergePointInterpreterFrameState* const v8::internal::maglev::Phi::merge_state_ [private]
Definition at line 9971 of file maglev-ir.h.
Referenced by predecessor_at(), and SetUseRequires31BitValue().
next_
Phi* v8::internal::maglev::Phi::next_ = nullptr [private]
Definition at line 9970 of file maglev-ir.h.
owner_
const interpreter::Register v8::internal::maglev::Phi::owner_ [private]
Definition at line 9965 of file maglev-ir.h.
post_loop_type_
NodeType v8::internal::maglev::Phi::post_loop_type_
Definition at line 9984 of file maglev-ir.h.
same_loop_uses_repr_hint_
UseRepresentationSet v8::internal::maglev::Phi::same_loop_uses_repr_hint_ = {} [private]
Definition at line 9968 of file maglev-ir.h.
Referenced by RecordUseReprHint().
type_
NodeType v8::internal::maglev::Phi::type_
Definition at line 9976 of file maglev-ir.h.
uses_repr_hint_
UseRepresentationSet v8::internal::maglev::Phi::uses_repr_hint_ = {} [private]
Definition at line 9967 of file maglev-ir.h.
Referenced by RecordUseReprHint().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc