v8::internal::wasm::BytecodeIterator Class Reference
#include <function-body-decoder.h>
Classes
class iterator_base
class offset_iterator
class opcode_iterator
Public Member Functions
BytecodeIterator (const uint8_t *start, const uint8_t *end)
BytecodeIterator (const uint8_t *start, const uint8_t *end, BodyLocalDecls *decls, Zone *zone)
base::iterator_range< opcode_iterator > opcodes () const
base::iterator_range< offset_iterator > offsets () const
WasmOpcode current ()
void next ()
bool has_next () const
WasmOpcode prefixed_opcode ()
const uint8_t * pc () const
Detailed Description
Definition at line 85 of file function-body-decoder.h.
Constructor & Destructor Documentation
BytecodeIterator() [1/2]
v8::internal::wasm::BytecodeIterator::BytecodeIterator (const uint8_t * start, const uint8_t * end)
Definition at line 59 of file function-body-decoder.cc.
    : Decoder(start, end) {}
BytecodeIterator() [2/2]
v8::internal::wasm::BytecodeIterator::BytecodeIterator (const uint8_t * start, const uint8_t * end, BodyLocalDecls * decls, Zone * zone)
Definition at line 62 of file function-body-decoder.cc.
    : Decoder(start, end) {
  DCHECK_NOT_NULL(decls);
  DCHECK_NOT_NULL(zone);
  DecodeLocalDecls(WasmEnabledFeatures::All(), decls, start, end, zone);
  pc_ += decls->encoded_size;
  if (pc_ > end_) pc_ = end_;
}
References v8::internal::wasm::WasmEnabledFeatures::All(), DCHECK_NOT_NULL, v8::internal::wasm::DecodeLocalDecls(), v8::internal::wasm::BodyLocalDecls::encoded_size, and v8::internal::compiler::end().
Member Function Documentation
current()
WasmOpcode v8::internal::wasm::BytecodeIterator::current () [inline]
Definition at line 158 of file function-body-decoder.h.
                       {
    return static_cast<WasmOpcode>(
        read_u8<Decoder::NoValidationTag>(pc_, "expected bytecode"));
  }
Referenced by v8::internal::wasm::BasicBlockCalculator::ComputeBasicBlocks(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), and v8::internal::WasmScript::GetPossibleBreakpoints().
has_next()
bool v8::internal::wasm::BytecodeIterator::has_next () const [inline]
Definition at line 170 of file function-body-decoder.h.
{ return pc_ < end_; }
Referenced by v8::internal::wasm::BasicBlockCalculator::ComputeBasicBlocks(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), and v8::internal::WasmScript::GetPossibleBreakpoints().
next()
void v8::internal::wasm::BytecodeIterator::next () [inline]
Definition at line 163 of file function-body-decoder.h.
              {
    if (pc_ < end_) {
      pc_ += OpcodeLength(pc_, end_);
      if (pc_ >= end_) pc_ = end_;
    }
  }
References v8::internal::wasm::OpcodeLength().
Referenced by v8::internal::wasm::BasicBlockCalculator::ComputeBasicBlocks(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), and v8::internal::WasmScript::GetPossibleBreakpoints().
offsets()
base::iterator_range<offset_iterator> v8::internal::wasm::BytecodeIterator::offsets () const [inline]
Definition at line 152 of file function-body-decoder.h.
                                                      {
    return base::iterator_range<offset_iterator>(
        offset_iterator(start_, pc_, end_),
        offset_iterator(start_, end_, end_));
  }
opcodes()
base::iterator_range<opcode_iterator> v8::internal::wasm::BytecodeIterator::opcodes () const [inline]
Definition at line 147 of file function-body-decoder.h.
                                                      {
    return base::iterator_range<opcode_iterator>(opcode_iterator(pc_, end_),
                                                 opcode_iterator(end_, end_));
  }
pc()
const uint8_t* v8::internal::wasm::BytecodeIterator::pc () const [inline]
Definition at line 177 of file function-body-decoder.h.
{ return pc_; }
prefixed_opcode()
WasmOpcode v8::internal::wasm::BytecodeIterator::prefixed_opcode () [inline]
Definition at line 172 of file function-body-decoder.h.
                               {
    auto [opcode, length] = read_prefixed_opcode<Decoder::NoValidationTag>(pc_);
    return opcode;
  }
References v8::internal::length.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/function-body-decoder.h
/mnt/V8SourceCode/src/wasm/function-body-decoder.cc