v8::internal::IterateAndScavengePromotedObjectsVisitor Class Reference
Public Member Functions
IterateAndScavengePromotedObjectsVisitor (Scavenger *scavenger)
void VisitMapPointer (Tagged< HeapObject > host) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitEphemeron (Tagged< HeapObject > obj, int entry, ObjectSlot key, ObjectSlot value) override
void VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) override
void VisitInstructionStreamPointer (Tagged< Code >, InstructionStreamSlot) final
void VisitCodeTarget (Tagged< InstructionStream >, RelocInfo *) final
void VisitEmbeddedPointer (Tagged< InstructionStream >, RelocInfo *) final
Static Public Member Functions
static constexpr bool ShouldUseUncheckedCast ()
static constexpr bool UsePrecomputedObjectSize ()
Private Member Functions
template<typename TSlot >
void VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end)
template<typename THeapObjectSlot >
void HandleSlot (Tagged< HeapObject > host, THeapObjectSlot slot, Tagged< HeapObject > target)
Private Attributes
Scavenger *const scavenger_
Additional Inherited Members
Detailed Description
Definition at line 55 of file scavenger.cc.
Constructor & Destructor Documentation
IterateAndScavengePromotedObjectsVisitor()
v8::internal::IterateAndScavengePromotedObjectsVisitor::IterateAndScavengePromotedObjectsVisitor (Scavenger * scavenger) [inline], [explicit]
Definition at line 58 of file scavenger.cc.
      : HeapVisitor(scavenger->heap()->isolate()), scavenger_(scavenger) {}
Member Function Documentation
HandleSlot()
template<typename THeapObjectSlot >
void v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot (Tagged< HeapObject > host, THeapObjectSlot slot, Tagged< HeapObject > target) [inline], [private]
Definition at line 148 of file scavenger.cc.
                                                       {
    static_assert(
        std::is_same_v<THeapObjectSlot, FullHeapObjectSlot> ||
            std::is_same_v<THeapObjectSlot, HeapObjectSlot>,
        "Only FullHeapObjectSlot and HeapObjectSlot are expected here");
    scavenger_->SynchronizePageAccess(target);
    if (Heap::InFromPage(target)) {
      SlotCallbackResult result = scavenger_->ScavengeObject(slot, target);
      bool success = (*slot).GetHeapObject(&target);
      USE(success);
      DCHECK(success);
      if (result == KEEP_SLOT) {
        SLOW_DCHECK(IsHeapObject(target));
        MemoryChunk* chunk = MemoryChunk::FromHeapObject(host);
        MutablePageMetadata* page =
            MutablePageMetadata::cast(chunk->Metadata());
        // Sweeper is stopped during scavenge, so we can directly
        // insert into its remembered set here.
        RememberedSet<OLD_TO_NEW>::Insert<AccessMode::ATOMIC>(
            page, chunk->Offset(slot.address()));
      }
      DCHECK(!MarkCompactCollector::IsOnEvacuationCandidate(target));
    }
    if (HeapLayout::InWritableSharedSpace(target)) {
      MemoryChunk* chunk = MemoryChunk::FromHeapObject(host);
      MutablePageMetadata* page = MutablePageMetadata::cast(chunk->Metadata());
      RememberedSet<OLD_TO_SHARED>::Insert<AccessMode::ATOMIC>(
          page, chunk->Offset(slot.address()));
    }
  }
References v8::internal::MutablePageMetadata::cast(), v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::Heap::InFromPage(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::IsHeapObject(), v8::internal::MarkCompactCollector::IsOnEvacuationCandidate(), heap::base::KEEP_SLOT, v8::internal::MemoryChunk::Metadata(), v8::internal::MemoryChunk::Offset(), v8::base::internal::result, v8::internal::Scavenger::ScavengeObject(), scavenger_, SLOW_DCHECK, v8::internal::Scavenger::SynchronizePageAccess(), and USE.
Referenced by VisitPointersImpl().
ShouldUseUncheckedCast()
static constexpr bool v8::internal::IterateAndScavengePromotedObjectsVisitor::ShouldUseUncheckedCast () [inline], [static], [constexpr]
Definition at line 61 of file scavenger.cc.
{ return true; }
UsePrecomputedObjectSize()
static constexpr bool v8::internal::IterateAndScavengePromotedObjectsVisitor::UsePrecomputedObjectSize () [inline], [static], [constexpr]
Definition at line 63 of file scavenger.cc.
{ return true; }
VisitCodeTarget()
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitCodeTarget (Tagged< InstructionStream > , RelocInfo *) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 124 of file scavenger.cc.
                                                                    {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitEmbeddedPointer()
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitEmbeddedPointer (Tagged< InstructionStream > , RelocInfo *) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 127 of file scavenger.cc.
                                                                         {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitEphemeron()
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitEphemeron (Tagged< HeapObject > obj, int entry, ObjectSlot key, ObjectSlot value) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 77 of file scavenger.cc.
                                                        {
    DCHECK(HeapLayout::IsSelfForwarded(obj) || IsEphemeronHashTable(obj));
    VisitPointer(obj, value);
    if (HeapLayout::InYoungGeneration(*key)) {
      // We cannot check the map here, as it might be a large object.
      scavenger_->RememberPromotedEphemeron(
          UncheckedCast<EphemeronHashTable>(obj), entry);
    } else {
      VisitPointer(obj, key);
    }
  }
References v8::internal::DCHECK(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::HeapLayout::IsSelfForwarded(), v8::internal::key, v8::internal::Scavenger::RememberPromotedEphemeron(), scavenger_, v8::internal::value, and v8::internal::ObjectVisitor::VisitPointer().
VisitExternalPointer()
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 91 of file scavenger.cc.
                                                               {
#ifdef V8_COMPRESS_POINTERS
    DCHECK(!slot.tag_range().IsEmpty());
    DCHECK(!IsSharedExternalPointerType(slot.tag_range()));
    // TODO(chromium:337580006): Remove when pointer compression always uses
    // EPT.
    if (!slot.HasExternalPointerHandle()) return;
    ExternalPointerHandle handle = slot.Relaxed_LoadHandle();
    Heap* heap = scavenger_->heap();
    ExternalPointerTable& table = heap->isolate()->external_pointer_table();
    // For survivor objects, the scavenger marks their EPT entries when they are
    // copied and then sweeps the young EPT space at the end of collection,
    // reclaiming unmarked EPT entries.
    //
    // However when promoting, we just evacuate the entry from new to old space.
    // Usually the entry will be unmarked, unless the slot was initialized since
    // the last GC (external pointer tags have the mark bit set), in which case
    // it may be marked already. In any case, transfer the color from new to
    // old EPT space.
    table.Evacuate(heap->young_external_pointer_space(),
                   heap->old_external_pointer_space(), handle, slot.address(),
                   ExternalPointerTable::EvacuateMarkMode::kTransferMark);
#endif // V8_COMPRESS_POINTERS
  }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::DCHECK(), v8::internal::handle(), v8::internal::Scavenger::heap(), v8::internal::TagRange< Tag >::IsEmpty(), v8::internal::IsSharedExternalPointerType(), scavenger_, and v8::internal::ExternalPointerSlot::tag_range().
VisitInstructionStreamPointer()
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitInstructionStreamPointer (Tagged< Code > , InstructionStreamSlot) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 120 of file scavenger.cc.
                                                                  {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitMapPointer()
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 65 of file scavenger.cc.
{}
VisitPointers() [1/2]
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 72 of file scavenger.cc.
                                                          {
    VisitPointersImpl(host, start, end);
  }
References v8::internal::compiler::end(), and VisitPointersImpl().
VisitPointers() [2/2]
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 67 of file scavenger.cc.
                                                     {
    VisitPointersImpl(host, start, end);
  }
References v8::internal::compiler::end(), and VisitPointersImpl().
VisitPointersImpl()
template<typename TSlot >
void v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end) [inline], [private]
Definition at line 133 of file scavenger.cc.
                                              {
    using THeapObjectSlot = typename TSlot::THeapObjectSlot;
    // Treat weak references as strong.
    // TODO(marja): Proper weakness handling in the young generation.
    for (TSlot slot = start; slot < end; ++slot) {
      typename TSlot::TObject object = *slot;
      Tagged<HeapObject> heap_object;
      if (object.GetHeapObject(&heap_object)) {
        HandleSlot(host, THeapObjectSlot(slot), heap_object);
      }
    }
  }
References v8::internal::compiler::end(), and HandleSlot().
Referenced by VisitPointers().
Member Data Documentation
scavenger_
Scavenger* const v8::internal::IterateAndScavengePromotedObjectsVisitor::scavenger_ [private]
Definition at line 184 of file scavenger.cc.
Referenced by HandleSlot(), VisitEphemeron(), and VisitExternalPointer().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/scavenger.cc