v8::internal::ExternalEntityTable< Entry, size > Class Template Reference
A thread-safe table with a fixed maximum size for storing references to objects located outside of the sandbox.
#include <external-entity-table.h>
Classes
struct Space
struct SpaceWithBlackAllocationSupport
class UnsealReadOnlySegmentScope
Public Member Functions
void Initialize ()
void TearDown ()
void InitializeSpace (Space *space)
void TearDownSpace (Space *space)
void AttachSpaceToReadOnlySegments (Space *space)
void DetachSpaceFromReadOnlySegments (Space *space)
void ZeroInternalNullEntry ()
Static Public Attributes
static constexpr bool kSupportsCompaction = false
Protected Types
using Base = SegmentedTable< Entry, size >
using FreelistHead = Base::FreelistHead
using Segment = Base::Segment
using WriteIterator = Base::WriteIterator
Protected Member Functions
ExternalEntityTable ()=default
ExternalEntityTable (const ExternalEntityTable &)=delete
ExternalEntityTable & operator= (const ExternalEntityTable &)=delete
uint32_t AllocateEntry (Space *space)
std::optional< uint32_t > TryAllocateEntry (Space *space)
uint32_t AllocateEntryBelow (Space *space, uint32_t threshold_index)
bool TryAllocateEntryFromFreelist (Space *space, FreelistHead freelist)
std::optional< FreelistHead > TryExtend (Space *space)
uint32_t GenericSweep (Space *space)
template<typename Callback >
uint32_t GenericSweep (Space *space, Callback marked)
template<typename Callback >
void IterateEntriesIn (Space *space, Callback callback)
Static Protected Attributes
static constexpr size_t kSegmentSize = Base::kSegmentSize
static constexpr size_t kEntriesPerSegment = Base::kEntriesPerSegment
static constexpr size_t kEntrySize = Base::kEntrySize
static constexpr size_t kNumReadOnlySegments = Base::kNumReadOnlySegments
static constexpr FreelistHead kEntryAllocationIsForbiddenMarker
static constexpr uint32_t kInternalReadOnlySegmentsOffset = 0
static constexpr uint32_t kInternalNullEntryIndex = 0
static constexpr uint32_t kEndOfReadOnlyIndex
Private Member Functions
void UnsealReadOnlySegments ()
void SealReadOnlySegments ()
void Extend (Space *space, Segment segment, FreelistHead freelist)
Friends
class Isolate
Additional Inherited Members
Detailed Description
template<typename Entry, size_t size>
class v8::internal::ExternalEntityTable< Entry, size >
A thread-safe table with a fixed maximum size for storing references to objects located outside of the sandbox.
An external entity table provides the basic mechanisms to ensure safe access to objects located outside the sandbox, but referenced from within it. When an external entity table is used, objects located inside the sandbox reference outside objects through indices into the table.
The ExternalEntityTable class should be seen an an incomplete class that needs to be extended by a concrete implementation class, such as the ExternalPointerTable class, as it is lacking some functionality. In particular, while the ExternalEntityTable implements basic table memory management as well as entry allocation routines, it does not implement any logic for reclaiming entries such as garbage collection. This must be done by the child classes.
For the purpose of memory management, the table is partitioned into Segments (for example 64kb memory chunks) that are grouped together in `Spaces`. All segments in a space share a freelist, and so entry allocation and garbage collection happen on the level of spaces.
Definition at line 47 of file external-entity-table.h.
Member Typedef Documentation
Base
template<typename Entry , size_t size>
using v8::internal::ExternalEntityTable< Entry, size >::Base = SegmentedTable<Entry, size> [protected]
Definition at line 50 of file external-entity-table.h.
FreelistHead
template<typename Entry , size_t size>
using v8::internal::ExternalEntityTable< Entry, size >::FreelistHead = Base::FreelistHead [protected]
Definition at line 51 of file external-entity-table.h.
Segment
template<typename Entry , size_t size>
using v8::internal::ExternalEntityTable< Entry, size >::Segment = Base::Segment [protected]
Definition at line 52 of file external-entity-table.h.
WriteIterator
template<typename Entry , size_t size>
using v8::internal::ExternalEntityTable< Entry, size >::WriteIterator = Base::WriteIterator [protected]
Definition at line 53 of file external-entity-table.h.
Constructor & Destructor Documentation
ExternalEntityTable() [1/2]
template<typename Entry , size_t size>
v8::internal::ExternalEntityTable< Entry, size >::ExternalEntityTable () [protected], [default]
ExternalEntityTable() [2/2]
template<typename Entry , size_t size>
v8::internal::ExternalEntityTable< Entry, size >::ExternalEntityTable (const ExternalEntityTable< Entry, size > &) [protected], [delete]
Member Function Documentation
AllocateEntry()
template<typename Entry , size_t size>
uint32_t v8::internal::ExternalEntityTable< Entry, size >::AllocateEntry (Space * space) [protected]
Definition at line 170 of file external-entity-table-inl.h.
                                                                     {
  if (auto res = TryAllocateEntry(space)) {
    return *res;
  }
  V8::FatalProcessOutOfMemory(nullptr, "ExternalEntityTable::AllocateEntry");
}
References v8::internal::V8::FatalProcessOutOfMemory(), space, and v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry().
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AttachSpaceToReadOnlySegments().
AllocateEntryBelow()
template<typename Entry , size_t size>
uint32_t v8::internal::ExternalEntityTable< Entry, size >::AllocateEntryBelow (Space * space, uint32_t threshold_index) [protected]
Definition at line 230 of file external-entity-table-inl.h.
                                            {
  DCHECK(this->is_initialized());
  FreelistHead freelist;
  bool success = false;
  while (!success) {
    freelist = space->freelist_head_.load(std::memory_order_acquire);
    // Check that the next free entry is below the threshold.
    if (freelist.is_empty() || freelist.next() >= threshold_index) return 0;
    success = TryAllocateEntryFromFreelist(space, freelist);
  }
  uint32_t allocated_entry = freelist.next();
  DCHECK(space->Contains(allocated_entry));
  DCHECK_NE(allocated_entry, 0);
  DCHECK_LT(allocated_entry, threshold_index);
  return allocated_entry;
}
References v8::internal::DCHECK(), DCHECK_LT, DCHECK_NE, v8::internal::SegmentedTable< Entry, size >::FreelistHead::is_empty(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::SegmentedTable< Entry, size >::FreelistHead::next(), space, and v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntryFromFreelist().
AttachSpaceToReadOnlySegments()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::AttachSpaceToReadOnlySegments (Space * space)
Definition at line 119 of file external-entity-table-inl.h.
                  {
  CHECK(ExternalEntityTable::kUseContiguousMemory);
  DCHECK(this->is_initialized());
  DCHECK(space->BelongsTo(this));
  DCHECK(!space->is_internal_read_only_space());
  space->is_internal_read_only_space_ = true;
  // For the internal read-only segment, index 0 is reserved for the `null`
  // entry. This call also ensures that the first segment is initialized.
  {
    UnsealReadOnlySegmentScope writable(this);
    uint32_t null_entry = AllocateEntry(space);
    CHECK_EQ(null_entry, kInternalNullEntryIndex);
    ZeroInternalNullEntry();
  }
}
References v8::internal::ExternalEntityTable< Entry, size >::AllocateEntry(), CHECK, CHECK_EQ, v8::internal::DCHECK(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::ExternalEntityTable< Entry, size >::kInternalNullEntryIndex, v8::internal::SegmentedTable< Entry, size >::kUseContiguousMemory, space, and v8::internal::ExternalEntityTable< Entry, size >::ZeroInternalNullEntry().
DetachSpaceFromReadOnlySegments()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::DetachSpaceFromReadOnlySegments (Space * space)
Definition at line 139 of file external-entity-table-inl.h.
                  {
  DCHECK(this->is_initialized());
  DCHECK(space->BelongsTo(this));
  // Remove the RO segment from the space's segment list without freeing it.
  // The table itself manages the RO segment's lifecycle.
  base::MutexGuard guard(&space->mutex_);
  DCHECK_EQ(space->segments_.size(), this->read_only_segments_used_);
  this->read_only_segments_used_ = 0;
  space->segments_.clear();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::SegmentedTable< Entry, size >::read_only_segments_used_, v8::internal::ExternalEntityTable< Entry, size >::Space::segments_, space, and v8::internal::this.
Extend()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::Extend (Space * space, Segment segment, FreelistHead freelist) [private]
Definition at line 308 of file external-entity-table-inl.h.
                                                                     {
  // Freelist should be empty when calling this method.
  DCHECK_EQ(space->freelist_length(), 0);
  // The caller must lock the space's mutex before extending it.
  space->mutex_.AssertHeld();
  space->segments_.insert(segment);
  CHECK_IMPLIES(!ExternalEntityTable::kUseContiguousMemory,
                segment.number() != 0);
  DCHECK_EQ(space->is_internal_read_only_space(),
            segment.number() < kNumReadOnlySegments);
  DCHECK_IMPLIES(
      space->is_internal_read_only_space(),
      segment.offset() == this->read_only_segments_used_ * kSegmentSize);
  // This must be a release store to prevent reordering of of earlier stores to
  // the freelist (for example during initialization of the segment) from being
  // reordered past this store. See AllocateEntry() for more details.
  space->freelist_head_.store(freelist, std::memory_order_release);
}
References CHECK_IMPLIES, DCHECK_EQ, DCHECK_IMPLIES, v8::internal::ExternalEntityTable< Entry, size >::kNumReadOnlySegments, v8::internal::ExternalEntityTable< Entry, size >::kSegmentSize, v8::internal::SegmentedTable< Entry, size >::kUseContiguousMemory, v8::internal::SegmentedTable< Entry, size >::Segment::number(), v8::internal::SegmentedTable< Entry, size >::Segment::offset(), space, and v8::internal::this.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::TryExtend().
GenericSweep() [1/2]
template<typename Entry , size_t size>
uint32_t v8::internal::ExternalEntityTable< Entry, size >::GenericSweep (Space * space) [protected]
Definition at line 331 of file external-entity-table-inl.h.
                                                                    {
  return GenericSweep(space, [](Entry&) {});
}
References space.
GenericSweep() [2/2]
template<typename Entry , size_t size>
template<typename Callback >
uint32_t v8::internal::ExternalEntityTable< Entry, size >::GenericSweep (Space * space, Callback marked) [protected]
Definition at line 337 of file external-entity-table-inl.h.
                                                                           {
  DCHECK(space->BelongsTo(this));
  // Lock the space. Technically this is not necessary since no other thread can
  // allocate entries at this point, but some of the methods we call on the
  // space assert that the lock is held.
  base::MutexGuard guard(&space->mutex_);
  // There must not be any entry allocations while the table is being swept as
  // that would not be safe. Set the freelist to this special marker value to
  // easily catch any violation of this requirement.
  space->freelist_head_.store(kEntryAllocationIsForbiddenMarker,
                              std::memory_order_relaxed);
  // Here we can iterate over the segments collection without taking a lock
  // because no other thread can currently allocate entries in this space.
  uint32_t current_freelist_head = 0;
  uint32_t current_freelist_length = 0;
  std::vector<Segment> segments_to_deallocate;
  for (auto segment : base::Reversed(space->segments_)) {
    // Remember the state of the freelist before this segment in case this
    // segment turns out to be completely empty and we deallocate it.
    uint32_t previous_freelist_head = current_freelist_head;
    uint32_t previous_freelist_length = current_freelist_length;
    // Process every entry in this segment, again going top to bottom.
    for (WriteIterator it = this->iter_at(segment.last_entry());
         it.index() >= segment.first_entry(); --it) {
      if (!it->IsMarked()) {
        it->MakeFreelistEntry(current_freelist_head);
        current_freelist_head = it.index();
        current_freelist_length++;
      } else {
        callback(*it);
        it->Unmark();
      }
    }
    // If a segment is completely empty, free it.
    uint32_t free_entries = current_freelist_length - previous_freelist_length;
    bool segment_is_empty = free_entries == kEntriesPerSegment;
    if (segment_is_empty && segment.number() >= kNumReadOnlySegments) {
      segments_to_deallocate.push_back(segment);
      // Restore the state of the freelist before this segment.
      current_freelist_head = previous_freelist_head;
      current_freelist_length = previous_freelist_length;
    }
  }
  // We cannot remove the segments while iterating over the segments set, so
  // defer that until now.
  for (auto segment : segments_to_deallocate) {
    // Segment zero is reserved.
    DCHECK_GE(segment.number(), kNumReadOnlySegments);
    this->FreeTableSegment(segment);
    space->segments_.erase(segment);
  }
  FreelistHead new_freelist(current_freelist_head, current_freelist_length);
  space->freelist_head_.store(new_freelist, std::memory_order_release);
  DCHECK_EQ(space->freelist_length(), current_freelist_length);
  uint32_t num_live_entries = space->capacity() - current_freelist_length;
  return num_live_entries;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), v8::internal::SegmentedTable< Entry, size >::WriteIterator::index(), v8::internal::SegmentedTable< Entry, size >::iter_at(), v8::internal::ExternalEntityTable< Entry, size >::kEntriesPerSegment, v8::internal::ExternalEntityTable< Entry, size >::kEntryAllocationIsForbiddenMarker, v8::internal::ExternalEntityTable< Entry, size >::kNumReadOnlySegments, v8::base::Reversed(), and space.
Initialize()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::Initialize
Definition at line 48 of file external-entity-table-inl.h.
                                                  {
  Base::Initialize();
  if (!ExternalEntityTable::kUseContiguousMemory) return;
  // Allocate the read-only segments of the table. These segments are always
  // located at offset 0. The first segment contains the null entry (pointing at
  // kNullAddress) at index 0. Initially we allocate these segments with
  // kNoAccess, which is converted to kRead on Extend. It may later be
  // temporarily marked read-write, see UnsealedReadOnlySegmentScope. The first
  // segment is already initialized at kRead such that the null handle can be
  // dereferenced during initialization.
  static_assert(kEndOfReadOnlyIndex * sizeof(Entry) ==
                kSegmentSize * kNumReadOnlySegments);
  Address first_segment = this->vas_->AllocatePages(
      this->vas_->base(), kSegmentSize * kNumReadOnlySegments, Base::kAlignment,
      PagePermissions::kRead);
  if (first_segment != this->vas_->base()) {
    V8::FatalProcessOutOfMemory(
        nullptr,
        "ExternalEntityTable::InitializeTable (r/o segments allocation)");
  }
  DCHECK_EQ(first_segment - this->vas_->base(),
            kInternalReadOnlySegmentsOffset);
  if constexpr (Base::kUseSegmentPool) {
    this->FillSegmentsPool(false);
  }
}
References v8::VirtualAddressSpace::AllocatePages(), v8::VirtualAddressSpace::base(), DCHECK_EQ, v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::SegmentedTable< Entry, size >::FillSegmentsPool(), v8::internal::SegmentedTable< Entry, size >::Initialize(), v8::internal::SegmentedTable< Entry, size >::kAlignment, v8::internal::ExternalEntityTable< Entry, size >::kEndOfReadOnlyIndex, v8::internal::ExternalEntityTable< Entry, size >::kInternalReadOnlySegmentsOffset, v8::internal::ExternalEntityTable< Entry, size >::kNumReadOnlySegments, v8::kRead, v8::internal::ExternalEntityTable< Entry, size >::kSegmentSize, v8::internal::SegmentedTable< Entry, size >::kUseContiguousMemory, v8::internal::SegmentedTable< Entry, size >::kUseSegmentPool, and v8::internal::SegmentedTable< Entry, size >::vas_.
InitializeSpace()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::InitializeSpace (Space * space)
Definition at line 93 of file external-entity-table-inl.h.
                                                                   {
#ifdef DEBUG
  DCHECK_EQ(space->owning_table_, nullptr);
  space->owning_table_ = this;
#endif
}
References DCHECK_EQ, and space.
IterateEntriesIn()
template<typename Entry , size_t size>
template<typename Callback >
void v8::internal::ExternalEntityTable< Entry, size >::IterateEntriesIn (Space * space, Callback callback) [protected]
Definition at line 407 of file external-entity-table-inl.h.
                                                                           {
  DCHECK(space->BelongsTo(this));
  base::MutexGuard guard(&space->mutex_);
  for (auto segment : space->segments_) {
    for (uint32_t i = segment.first_entry(); i <= segment.last_entry(); i++) {
      callback(i);
    }
  }
}
References v8::internal::DCHECK(), and space.
operator=()
template<typename Entry , size_t size>
ExternalEntityTable& v8::internal::ExternalEntityTable< Entry, size >::operator= (const ExternalEntityTable< Entry, size > &) [protected], [delete]
SealReadOnlySegments()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::SealReadOnlySegments [private]
Definition at line 161 of file external-entity-table-inl.h.
                                                            {
  DCHECK(this->is_initialized());
  bool success = this->vas_->SetPagePermissions(
      this->vas_->base(), kSegmentSize * kNumReadOnlySegments,
      PagePermissions::kRead);
  CHECK(success);
}
References v8::VirtualAddressSpace::base(), CHECK, v8::internal::DCHECK(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::ExternalEntityTable< Entry, size >::kNumReadOnlySegments, v8::kRead, v8::internal::ExternalEntityTable< Entry, size >::kSegmentSize, v8::VirtualAddressSpace::SetPagePermissions(), and v8::internal::SegmentedTable< Entry, size >::vas_.
TearDown()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::TearDown
Definition at line 80 of file external-entity-table-inl.h.
                                                {
  DCHECK(this->is_initialized());
  if (ExternalEntityTable::kUseContiguousMemory) {
    // Deallocate the (read-only) first segment.
    this->vas_->FreePages(this->vas_->base(),
                          kSegmentSize * kNumReadOnlySegments);
  }
  Base::TearDown();
}
References v8::VirtualAddressSpace::base(), v8::internal::DCHECK(), v8::VirtualAddressSpace::FreePages(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::ExternalEntityTable< Entry, size >::kNumReadOnlySegments, v8::internal::ExternalEntityTable< Entry, size >::kSegmentSize, v8::internal::SegmentedTable< Entry, size >::kUseContiguousMemory, v8::internal::SegmentedTable< Entry, size >::TearDown(), and v8::internal::SegmentedTable< Entry, size >::vas_.
TearDownSpace()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::TearDownSpace (Space * space)
Definition at line 101 of file external-entity-table-inl.h.
                                                                 {
  DCHECK(this->is_initialized());
  DCHECK(space->BelongsTo(this));
  for (auto segment : space->segments_) {
    this->FreeTableSegment(segment);
  }
  space->segments_.clear();
}
References v8::internal::DCHECK(), v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), and space.
TryAllocateEntry()
template<typename Entry , size_t size>
std::optional< uint32_t > v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry (Space * space) [protected]
Definition at line 178 of file external-entity-table-inl.h.
                  {
  DCHECK(this->is_initialized());
  DCHECK(space->BelongsTo(this));
  // We currently don't want entry allocation to trigger garbage collection as
  // this may cause seemingly harmless pointer field assignments to trigger
  // garbage collection. This is especially true for lazily-initialized
  // external pointer slots which will typically only allocate the external
  // pointer table entry when the pointer is first set to a non-null value.
  DisallowGarbageCollection no_gc;
  FreelistHead freelist;
  for (;;) {
    // This is essentially DCLP (see
    // https://preshing.com/20130930/double-checked-locking-is-fixed-in-cpp11/)
    // and so requires an acquire load as well as a release store in Grow() to
    // prevent reordering of memory accesses, which could for example cause one
    // thread to read a freelist entry before it has been properly initialized.
    freelist = space->freelist_head_.load(std::memory_order_acquire);
    if (V8_UNLIKELY(freelist.is_empty())) {
      // Freelist is empty. Need to take the lock, then attempt to allocate a
      // new segment if no other thread has done it in the meantime.
      base::MutexGuard guard(&space->mutex_);
      // Reload freelist head in case another thread already grew the table.
      freelist = space->freelist_head_.load(std::memory_order_relaxed);
      if (freelist.is_empty()) {
        // Freelist is (still) empty so extend this space by another segment.
        if (auto maybe_freelist = TryExtend(space)) {
          freelist = *maybe_freelist;
        } else {
          return {};
        }
        // Extend() adds one segment to the space and so to its freelist.
        DCHECK_EQ(freelist.length(), kEntriesPerSegment);
      }
    }
    if (V8_LIKELY(TryAllocateEntryFromFreelist(space, freelist))) {
      break;
    }
  }
  uint32_t allocated_entry = freelist.next();
  DCHECK(space->Contains(allocated_entry));
  DCHECK_IMPLIES(!space->is_internal_read_only_space(), allocated_entry != 0);
  return allocated_entry;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::SegmentedTable< Entry, size >::FreelistHead::is_empty(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::ExternalEntityTable< Entry, size >::kEntriesPerSegment, v8::internal::SegmentedTable< Entry, size >::FreelistHead::length(), v8::internal::SegmentedTable< Entry, size >::FreelistHead::next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, space, v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntryFromFreelist(), v8::internal::ExternalEntityTable< Entry, size >::TryExtend(), V8_LIKELY, and V8_UNLIKELY.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AllocateEntry().
TryAllocateEntryFromFreelist()
template<typename Entry , size_t size>
bool v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntryFromFreelist (Space * space, FreelistHead freelist) [protected]
Definition at line 252 of file external-entity-table-inl.h.
                                         {
  DCHECK(!freelist.is_empty());
  DCHECK(space->Contains(freelist.next()));
  Entry& freelist_entry = this->at(freelist.next());
  uint32_t next_freelist_entry = freelist_entry.GetNextFreelistEntryIndex();
  FreelistHead new_freelist(next_freelist_entry, freelist.length() - 1);
  bool success = space->freelist_head_.compare_exchange_strong(
      freelist, new_freelist, std::memory_order_relaxed);
  // When the CAS succeeded, the entry must've been a freelist entry.
  // Otherwise, this is not guaranteed as another thread may have allocated
  // and overwritten the same entry in the meantime.
  if (success) {
    DCHECK_IMPLIES(freelist.length() > 1, !new_freelist.is_empty());
    DCHECK_IMPLIES(freelist.length() == 1, new_freelist.is_empty());
  }
  return success;
}
References v8::internal::SegmentedTable< Entry, size >::at(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::SegmentedTable< Entry, size >::FreelistHead::is_empty(), v8::internal::SegmentedTable< Entry, size >::FreelistHead::length(), v8::internal::SegmentedTable< Entry, size >::FreelistHead::next(), and space.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AllocateEntryBelow(), and v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry().
TryExtend()
template<typename Entry , size_t size>
std::optional< typename ExternalEntityTable< Entry, size >::FreelistHead > v8::internal::ExternalEntityTable< Entry, size >::TryExtend (Space * space) [protected]
Definition at line 275 of file external-entity-table-inl.h.
                                                        {
  // Freelist should be empty when calling this method.
  DCHECK_EQ(space->freelist_length(), 0);
  // The caller must lock the space's mutex before extending it.
  space->mutex_.AssertHeld();
  if (space->is_internal_read_only_space()) {
    // If this check fails during snapshot generation increase
    // kNumReadOnlySegments as needed.
    CHECK_LT(this->read_only_segments_used_, kNumReadOnlySegments);
    DCHECK_EQ(space->segments_.size(), this->read_only_segments_used_);
    Segment next_segment =
        Segment::At(kInternalReadOnlySegmentsOffset +
                    kSegmentSize * this->read_only_segments_used_);
    CHECK_LT(next_segment.last_entry(), kEndOfReadOnlyIndex);
    FreelistHead freelist = Base::InitializeFreeList(next_segment);
    Extend(space, next_segment, freelist);
    DCHECK(!freelist.is_empty());
    this->read_only_segments_used_++;
    return freelist;
  }
  // Allocate the new segment.
  auto extended = this->TryAllocateAndInitializeSegment();
  if (!extended) return {};
  auto [segment, freelist_head] = *extended;
  Extend(space, segment, freelist_head);
  return freelist_head;
}
References v8::internal::SegmentedTable< Entry, size >::Segment::At(), CHECK_LT, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ExternalEntityTable< Entry, size >::Extend(), v8::internal::SegmentedTable< Entry, size >::InitializeFreeList(), v8::internal::SegmentedTable< Entry, size >::FreelistHead::is_empty(), v8::internal::ExternalEntityTable< Entry, size >::kEndOfReadOnlyIndex, v8::internal::ExternalEntityTable< Entry, size >::kInternalReadOnlySegmentsOffset, v8::internal::ExternalEntityTable< Entry, size >::kNumReadOnlySegments, v8::internal::ExternalEntityTable< Entry, size >::kSegmentSize, v8::internal::SegmentedTable< Entry, size >::Segment::last_entry(), v8::internal::SegmentedTable< Entry, size >::read_only_segments_used_, v8::internal::ExternalEntityTable< Entry, size >::Space::segments_, space, v8::internal::this, and v8::internal::SegmentedTable< Entry, size >::TryAllocateAndInitializeSegment().
Referenced by v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry().
UnsealReadOnlySegments()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::UnsealReadOnlySegments [private]
Definition at line 152 of file external-entity-table-inl.h.
                                                              {
  DCHECK(this->is_initialized());
  bool success = this->vas_->SetPagePermissions(
      this->vas_->base(), kSegmentSize * kNumReadOnlySegments,
      PagePermissions::kReadWrite);
  CHECK(success);
}
References v8::VirtualAddressSpace::base(), CHECK, v8::internal::DCHECK(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::ExternalEntityTable< Entry, size >::kNumReadOnlySegments, v8::kReadWrite, v8::internal::ExternalEntityTable< Entry, size >::kSegmentSize, v8::VirtualAddressSpace::SetPagePermissions(), and v8::internal::SegmentedTable< Entry, size >::vas_.
ZeroInternalNullEntry()
template<typename Entry , size_t size>
void v8::internal::ExternalEntityTable< Entry, size >::ZeroInternalNullEntry
Definition at line 111 of file external-entity-table-inl.h.
                                                             {
  std::conditional_t<Base::kIsWriteProtected, CFIMetadataWriteScope,
                     NopRwxMemoryWriteScope>
      write_scope("ZeroInternalNullEntry");
  memset(&this->at(kInternalNullEntryIndex), 0, sizeof(Entry));
}
References v8::internal::SegmentedTable< Entry, size >::at(), v8::internal::ExternalEntityTable< Entry, size >::kInternalNullEntryIndex, and v8::internal::SegmentedTable< Entry, size >::kIsWriteProtected.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AttachSpaceToReadOnlySegments().
Friends And Related Function Documentation
Isolate
template<typename Entry , size_t size>
friend class Isolate [friend]
Definition at line 276 of file external-entity-table.h.
Member Data Documentation
kEndOfReadOnlyIndex
template<typename Entry , size_t size>
constexpr uint32_t v8::internal::ExternalEntityTable< Entry, size >::kEndOfReadOnlyIndex [static], [constexpr], [protected]
Initial value:
=
      kEntriesPerSegment * kNumReadOnlySegments
Definition at line 271 of file external-entity-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::Initialize(), and v8::internal::ExternalEntityTable< Entry, size >::TryExtend().
kEntriesPerSegment
template<typename Entry , size_t size>
constexpr size_t v8::internal::ExternalEntityTable< Entry, size >::kEntriesPerSegment = Base::kEntriesPerSegment [static], [constexpr], [protected]
Definition at line 55 of file external-entity-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::GenericSweep(), and v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry().
kEntryAllocationIsForbiddenMarker
template<typename Entry , size_t size>
constexpr FreelistHead v8::internal::ExternalEntityTable< Entry, size >::kEntryAllocationIsForbiddenMarker [static], [constexpr], [protected]
Initial value:
=
      FreelistHead(-1, -1)
Definition at line 224 of file external-entity-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::GenericSweep().
kEntrySize
template<typename Entry , size_t size>
constexpr size_t v8::internal::ExternalEntityTable< Entry, size >::kEntrySize = Base::kEntrySize [static], [constexpr], [protected]
Definition at line 56 of file external-entity-table.h.
kInternalNullEntryIndex
template<typename Entry , size_t size>
constexpr uint32_t v8::internal::ExternalEntityTable< Entry, size >::kInternalNullEntryIndex = 0 [static], [constexpr], [protected]
Definition at line 270 of file external-entity-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AttachSpaceToReadOnlySegments(), and v8::internal::ExternalEntityTable< Entry, size >::ZeroInternalNullEntry().
kInternalReadOnlySegmentsOffset
template<typename Entry , size_t size>
constexpr uint32_t v8::internal::ExternalEntityTable< Entry, size >::kInternalReadOnlySegmentsOffset = 0 [static], [constexpr], [protected]
Definition at line 269 of file external-entity-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::Initialize(), and v8::internal::ExternalEntityTable< Entry, size >::TryExtend().
kNumReadOnlySegments
template<typename Entry , size_t size>
constexpr size_t v8::internal::ExternalEntityTable< Entry, size >::kNumReadOnlySegments = Base::kNumReadOnlySegments [static], [constexpr], [protected]
Definition at line 57 of file external-entity-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::Extend(), v8::internal::ExternalEntityTable< Entry, size >::GenericSweep(), v8::internal::ExternalEntityTable< Entry, size >::Initialize(), v8::internal::ExternalEntityTable< Entry, size >::SealReadOnlySegments(), v8::internal::ExternalEntityTable< Entry, size >::TearDown(), v8::internal::ExternalEntityTable< Entry, size >::TryExtend(), and v8::internal::ExternalEntityTable< Entry, size >::UnsealReadOnlySegments().
kSegmentSize
template<typename Entry , size_t size>
constexpr size_t v8::internal::ExternalEntityTable< Entry, size >::kSegmentSize = Base::kSegmentSize [static], [constexpr], [protected]
Definition at line 54 of file external-entity-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::Extend(), v8::internal::ExternalEntityTable< Entry, size >::Initialize(), v8::internal::ExternalEntityTable< Entry, size >::SealReadOnlySegments(), v8::internal::ExternalEntityTable< Entry, size >::TearDown(), v8::internal::ExternalEntityTable< Entry, size >::TryExtend(), and v8::internal::ExternalEntityTable< Entry, size >::UnsealReadOnlySegments().
kSupportsCompaction
template<typename Entry , size_t size>
constexpr bool v8::internal::ExternalEntityTable< Entry, size >::kSupportsCompaction = false [static], [constexpr]
Definition at line 232 of file external-entity-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/sandbox/external-entity-table.h
/mnt/V8SourceCode/src/sandbox/external-entity-table-inl.h