v8::internal::AttributePrinter Class Reference
Public Member Functions
AttributePrinter (std::ostream &os)
void PrintSeparator ()
void PrintBit (const char *name, bool value)
void PrintPositive (const char *name, int value)
Private Attributes
std::ostream & os_
bool first_
Detailed Description
Definition at line 66 of file regexp-dotprinter.cc.
Constructor & Destructor Documentation
AttributePrinter()
v8::internal::AttributePrinter::AttributePrinter (std::ostream & os) [inline], [explicit]
Definition at line 68 of file regexp-dotprinter.cc.
: os_(os), first_(true) {}
Member Function Documentation
PrintBit()
void v8::internal::AttributePrinter::PrintBit (const char * name, bool value) [inline]
Definition at line 76 of file regexp-dotprinter.cc.
                                              {
    if (!value) return;
    PrintSeparator();
    os_ << "{";
    for (const char* p = name; *p; p++) {
      os_ << AsUC16(static_cast<unsigned char>(*p));
    }
    os_ << name << "}";
  }
References v8::internal::name, os_, PrintSeparator(), and v8::internal::value.
Referenced by v8::internal::DotPrinterImpl::PrintAttributes().
PrintPositive()
void v8::internal::AttributePrinter::PrintPositive (const char * name, int value) [inline]
Definition at line 85 of file regexp-dotprinter.cc.
                                                  {
    if (value < 0) return;
    PrintSeparator();
    os_ << "{" << name << "|" << value << "}";
  }
References v8::internal::name, os_, PrintSeparator(), and v8::internal::value.
Referenced by v8::internal::DotPrinterImpl::PrintAttributes().
PrintSeparator()
void v8::internal::AttributePrinter::PrintSeparator () [inline]
Definition at line 69 of file regexp-dotprinter.cc.
                        {
    if (first_) {
      first_ = false;
    } else {
      os_ << "|";
    }
  }
References first_, and os_.
Referenced by PrintBit(), and PrintPositive().
Member Data Documentation
first_
bool v8::internal::AttributePrinter::first_ [private]
Definition at line 93 of file regexp-dotprinter.cc.
Referenced by PrintSeparator().
os_
std::ostream& v8::internal::AttributePrinter::os_ [private]
Definition at line 92 of file regexp-dotprinter.cc.
Referenced by PrintBit(), PrintPositive(), and PrintSeparator().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-dotprinter.cc