v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite Class Reference
Public Member Functions
OutOfLineRecordWrite (CodeGenerator *gen, Register object, Register offset, Register value, Register scratch0, Register scratch1, RecordWriteMode mode, StubCallMode stub_mode, UnwindingInfoWriter *unwinding_info_writer, IndirectPointerTag indirect_pointer_tag=kIndirectPointerNullTag)
OutOfLineRecordWrite (CodeGenerator *gen, Register object, int32_t offset, Register value, Register scratch0, Register scratch1, RecordWriteMode mode, StubCallMode stub_mode, UnwindingInfoWriter *unwinding_info_writer, IndirectPointerTag indirect_pointer_tag=kIndirectPointerNullTag)
void Generate () final
Private Attributes
Register const object_
Register const offset_
int32_t const offset_immediate_
Register const value_
Register const scratch0_
Register const scratch1_
RecordWriteMode const mode_
bool must_save_lr_
UnwindingInfoWriter *const unwinding_info_writer_
Zone * zone_
IndirectPointerTag indirect_pointer_tag_
Detailed Description
Definition at line 143 of file code-generator-ppc.cc.
Constructor & Destructor Documentation
OutOfLineRecordWrite() [1/2]
v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::OutOfLineRecordWrite (CodeGenerator * gen, Register object, Register offset, Register value, Register scratch0, Register scratch1, RecordWriteMode mode, StubCallMode stub_mode, UnwindingInfoWriter * unwinding_info_writer, IndirectPointerTag indirect_pointer_tag = kIndirectPointerNullTag) [inline]
Definition at line 145 of file code-generator-ppc.cc.
      : OutOfLineCode(gen),
        object_(object),
        offset_(offset),
        offset_immediate_(0),
        value_(value),
        scratch0_(scratch0),
        scratch1_(scratch1),
        mode_(mode),
#if V8_ENABLE_WEBASSEMBLY
        stub_mode_(stub_mode),
#endif // V8_ENABLE_WEBASSEMBLY
        must_save_lr_(!gen->frame_access_state()->has_frame()),
        unwinding_info_writer_(unwinding_info_writer),
        zone_(gen->zone()),
        indirect_pointer_tag_(indirect_pointer_tag) {
    DCHECK(!AreAliased(object, offset, scratch0, scratch1));
    DCHECK(!AreAliased(value, offset, scratch0, scratch1));
  }
References v8::internal::AreAliased(), v8::internal::DCHECK(), and v8::internal::value.
OutOfLineRecordWrite() [2/2]
v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::OutOfLineRecordWrite (CodeGenerator * gen, Register object, int32_t offset, Register value, Register scratch0, Register scratch1, RecordWriteMode mode, StubCallMode stub_mode, UnwindingInfoWriter * unwinding_info_writer, IndirectPointerTag indirect_pointer_tag = kIndirectPointerNullTag) [inline]
Definition at line 169 of file code-generator-ppc.cc.
      : OutOfLineCode(gen),
        object_(object),
        offset_(no_reg),
        offset_immediate_(offset),
        value_(value),
        scratch0_(scratch0),
        scratch1_(scratch1),
        mode_(mode),
#if V8_ENABLE_WEBASSEMBLY
        stub_mode_(stub_mode),
#endif // V8_ENABLE_WEBASSEMBLY
        must_save_lr_(!gen->frame_access_state()->has_frame()),
        unwinding_info_writer_(unwinding_info_writer),
        zone_(gen->zone()),
        indirect_pointer_tag_(indirect_pointer_tag) {
  }
Member Function Documentation
Generate()
void v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::Generate () [inline], [final], [virtual]
Implements v8::internal::compiler::OutOfLineCode.
Definition at line 191 of file code-generator-ppc.cc.
                        {
    ConstantPoolUnavailableScope constant_pool_unavailable(masm());
    // When storing an indirect pointer, the value will always be a
    // full/decompressed pointer.
    if (COMPRESS_POINTERS_BOOL &&
        mode_ != RecordWriteMode::kValueIsIndirectPointer) {
      __ DecompressTagged(value_, value_);
    }
    __ CheckPageFlag(value_, scratch0_,
                     MemoryChunk::kPointersToHereAreInterestingMask, eq,
                     exit());
    if (offset_ == no_reg) {
      __ addi(scratch1_, object_, Operand(offset_immediate_));
    } else {
      DCHECK_EQ(0, offset_immediate_);
      __ add(scratch1_, object_, offset_);
    }
    SaveFPRegsMode const save_fp_mode = frame()->DidAllocateDoubleRegisters()
                                            ? SaveFPRegsMode::kSave
                                            : SaveFPRegsMode::kIgnore;
    if (must_save_lr_) {
      // We need to save and restore lr if the frame was elided.
      __ mflr(scratch0_);
      __ Push(scratch0_);
      unwinding_info_writer_->MarkLinkRegisterOnTopOfStack(__ pc_offset());
    }
    if (mode_ == RecordWriteMode::kValueIsEphemeronKey) {
      __ CallEphemeronKeyBarrier(object_, scratch1_, save_fp_mode);
    } else if (mode_ == RecordWriteMode::kValueIsIndirectPointer) {
      DCHECK(IsValidIndirectPointerTag(indirect_pointer_tag_));
      __ CallIndirectPointerBarrier(object_, scratch1_, save_fp_mode,
                                    indirect_pointer_tag_);
#if V8_ENABLE_WEBASSEMBLY
    } else if (stub_mode_ == StubCallMode::kCallWasmRuntimeStub) {
      __ CallRecordWriteStubSaveRegisters(object_, scratch1_, save_fp_mode,
                                          StubCallMode::kCallWasmRuntimeStub);
#endif // V8_ENABLE_WEBASSEMBLY
    } else {
      __ CallRecordWriteStubSaveRegisters(object_, scratch1_, save_fp_mode);
    }
    if (must_save_lr_) {
      // We need to save and restore lr if the frame was elided.
      __ Pop(scratch0_);
      __ mtlr(scratch0_);
      unwinding_info_writer_->MarkPopLinkRegisterFromTopOfStack(__ pc_offset());
    }
  }
References __, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::eq, v8::internal::IsValidIndirectPointerTag(), v8::internal::kIgnore, v8::internal::MemoryChunk::kPointersToHereAreInterestingMask, v8::internal::kSave, v8::internal::compiler::kValueIsEphemeronKey, v8::internal::compiler::kValueIsIndirectPointer, and v8::internal::no_reg.
Member Data Documentation
indirect_pointer_tag_
IndirectPointerTag v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::indirect_pointer_tag_ [private]
Definition at line 253 of file code-generator-ppc.cc.
mode_
RecordWriteMode const v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::mode_ [private]
Definition at line 246 of file code-generator-ppc.cc.
must_save_lr_
bool v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::must_save_lr_ [private]
Definition at line 250 of file code-generator-ppc.cc.
object_
Register const v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::object_ [private]
Definition at line 240 of file code-generator-ppc.cc.
offset_
Register const v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::offset_ [private]
Definition at line 241 of file code-generator-ppc.cc.
offset_immediate_
int32_t const v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::offset_immediate_ [private]
Definition at line 242 of file code-generator-ppc.cc.
scratch0_
Register const v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::scratch0_ [private]
Definition at line 244 of file code-generator-ppc.cc.
scratch1_
Register const v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::scratch1_ [private]
Definition at line 245 of file code-generator-ppc.cc.
unwinding_info_writer_
UnwindingInfoWriter* const v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::unwinding_info_writer_ [private]
Definition at line 251 of file code-generator-ppc.cc.
value_
Register const v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::value_ [private]
Definition at line 243 of file code-generator-ppc.cc.
zone_
Zone* v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::zone_ [private]
Definition at line 252 of file code-generator-ppc.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/ppc/code-generator-ppc.cc