v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder Class Reference
Public Member Functions
CompilationUnitBuilder (NativeModule *native_module)
void AddBaselineUnit (int func_index, ExecutionTier tier)
void AddTopTierUnit (int func_index, ExecutionTier tier)
void Commit ()
void Clear ()
const WasmModule * module ()
Private Member Functions
CompilationStateImpl * compilation_state () const
Private Attributes
NativeModule *const native_module_
std::vector< WasmCompilationUnit > baseline_units_
std::vector< WasmCompilationUnit > tiering_units_
Detailed Description
Definition at line 1096 of file module-compiler.cc.
Constructor & Destructor Documentation
CompilationUnitBuilder()
v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::CompilationUnitBuilder (NativeModule * native_module) [inline], [explicit]
Definition at line 1098 of file module-compiler.cc.
      : native_module_(native_module) {}
Member Function Documentation
AddBaselineUnit()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::AddBaselineUnit (int func_index, ExecutionTier tier) [inline]
Definition at line 1101 of file module-compiler.cc.
                                                           {
    baseline_units_.emplace_back(func_index, tier, kNotForDebugging);
  }
References v8::internal::wasm::kNotForDebugging.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnitForSingleFunction().
AddTopTierUnit()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::AddTopTierUnit (int func_index, ExecutionTier tier) [inline]
Definition at line 1105 of file module-compiler.cc.
                                                          {
    tiering_units_.emplace_back(func_index, tier, kNotForDebugging);
  }
References v8::internal::wasm::kNotForDebugging.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnitForSingleFunction(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions().
Clear()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::Clear () [inline]
Definition at line 1116 of file module-compiler.cc.
               {
    baseline_units_.clear();
    tiering_units_.clear();
  }
Commit()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::Commit () [inline]
Definition at line 1109 of file module-compiler.cc.
                {
    if (baseline_units_.empty() && tiering_units_.empty()) return;
    compilation_state()->CommitCompilationUnits(base::VectorOf(baseline_units_),
                                                base::VectorOf(tiering_units_));
    Clear();
  }
References v8::base::VectorOf().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions().
compilation_state()
CompilationStateImpl* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::compilation_state () const [inline], [private]
Definition at line 1124 of file module-compiler.cc.
                                                  {
    return Impl(native_module_->compilation_state());
  }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
module()
const WasmModule* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::module () [inline]
Definition at line 1121 of file module-compiler.cc.
{ return native_module_->module(); }
Member Data Documentation
baseline_units_
std::vector<WasmCompilationUnit> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::baseline_units_ [private]
Definition at line 1129 of file module-compiler.cc.
native_module_
NativeModule* const v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::native_module_ [private]
Definition at line 1128 of file module-compiler.cc.
tiering_units_
std::vector<WasmCompilationUnit> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::tiering_units_ [private]
Definition at line 1130 of file module-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc