v8::internal::OptimizationDecision Class Reference
Public Member Functions
constexpr bool should_optimize () const
Static Public Member Functions
static constexpr OptimizationDecision Maglev ()
static constexpr OptimizationDecision TurbofanHotAndStable ()
static constexpr OptimizationDecision DoNotOptimize ()
Public Attributes
OptimizationReason optimization_reason
CodeKind code_kind
ConcurrencyMode concurrency_mode
Private Member Functions
OptimizationDecision ()=default
constexpr OptimizationDecision (OptimizationReason optimization_reason, CodeKind code_kind, ConcurrencyMode concurrency_mode)
Detailed Description
Definition at line 61 of file tiering-manager.cc.
Constructor & Destructor Documentation
OptimizationDecision() [1/2]
v8::internal::OptimizationDecision::OptimizationDecision () [private], [default]
OptimizationDecision() [2/2]
constexpr v8::internal::OptimizationDecision::OptimizationDecision (OptimizationReason optimization_reason, CodeKind code_kind, ConcurrencyMode concurrency_mode) [inline], [constexpr], [private]
Definition at line 88 of file tiering-manager.cc.
      : optimization_reason(optimization_reason),
        code_kind(code_kind),
        concurrency_mode(concurrency_mode) {}
Member Function Documentation
DoNotOptimize()
static constexpr OptimizationDecision v8::internal::OptimizationDecision::DoNotOptimize () [inline], [static], [constexpr]
Definition at line 72 of file tiering-manager.cc.
                                                        {
    return {OptimizationReason::kDoNotOptimize,
            // These values don't matter but we have to pass something.
            CodeKind::TURBOFAN_JS, ConcurrencyMode::kConcurrent};
  }
References v8::internal::kConcurrent.
Referenced by v8::internal::TieringManager::ShouldOptimize().
Maglev()
static constexpr OptimizationDecision v8::internal::OptimizationDecision::Maglev () [inline], [static], [constexpr]
Definition at line 63 of file tiering-manager.cc.
                                                 {
    // TODO(v8:7700): Consider using another reason here.
    return {OptimizationReason::kHotAndStable, CodeKind::MAGLEV,
            ConcurrencyMode::kConcurrent};
  }
References v8::internal::kConcurrent.
Referenced by v8::internal::TieringManager::ShouldOptimize().
should_optimize()
constexpr bool v8::internal::OptimizationDecision::should_optimize () const [inline], [constexpr]
Definition at line 78 of file tiering-manager.cc.
                                         {
    return optimization_reason != OptimizationReason::kDoNotOptimize;
  }
References optimization_reason.
Referenced by v8::internal::TieringManager::MaybeOptimizeFrame(), v8::internal::TieringManager::NotifyICChanged(), and v8::internal::TieringManager::Optimize().
TurbofanHotAndStable()
static constexpr OptimizationDecision v8::internal::OptimizationDecision::TurbofanHotAndStable () [inline], [static], [constexpr]
Definition at line 68 of file tiering-manager.cc.
                                                               {
    return {OptimizationReason::kHotAndStable, CodeKind::TURBOFAN_JS,
            ConcurrencyMode::kConcurrent};
  }
References v8::internal::kConcurrent.
Referenced by v8::internal::TieringManager::MarkForTurboFanOptimization(), and v8::internal::TieringManager::ShouldOptimize().
Member Data Documentation
code_kind
CodeKind v8::internal::OptimizationDecision::code_kind
Definition at line 83 of file tiering-manager.cc.
Referenced by v8::internal::TieringManager::MaybeOptimizeFrame(), v8::internal::TieringManager::Optimize(), and v8::internal::anonymous_namespace{tiering-manager.cc}::TraceRecompile().
concurrency_mode
ConcurrencyMode v8::internal::OptimizationDecision::concurrency_mode
Definition at line 84 of file tiering-manager.cc.
Referenced by v8::internal::TieringManager::MaybeOptimizeFrame(), v8::internal::TieringManager::Optimize(), and v8::internal::anonymous_namespace{tiering-manager.cc}::TraceRecompile().
optimization_reason
OptimizationReason v8::internal::OptimizationDecision::optimization_reason
Definition at line 82 of file tiering-manager.cc.
Referenced by should_optimize(), and v8::internal::anonymous_namespace{tiering-manager.cc}::TraceRecompile().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/tiering-manager.cc