v8::HeapGraphNode Class Reference
HeapGraphNode represents a node in a heap graph.
#include <v8-profiler.h>
Public Types
enum Type {
kHidden = 0
, kArray = 1
, kString = 2
, kObject = 3
,
kCode = 4
, kClosure = 5
, kRegExp = 6
, kHeapNumber = 7
,
kNative = 8
, kSynthetic = 9
, kConsString = 10
, kSlicedString = 11
,
kSymbol = 12
, kBigInt = 13
, kObjectShape = 14
 }
Public Member Functions
Type GetType () const
Returns node type (see HeapGraphNode::Type).
Local< String > GetName () const
Returns node name.
SnapshotObjectId GetId () const
Returns node id.
size_t GetShallowSize () const
Returns node's own size, in bytes.
int GetChildrenCount () const
Returns child nodes count of the node.
const HeapGraphEdge * GetChild (int index) const
Retrieves a child by index.
Detailed Description
HeapGraphNode represents a node in a heap graph.
Definition at line 587 of file v8-profiler.h.
Member Enumeration Documentation
Type
enum v8::HeapGraphNode::Type
Enumerator
kHidden
kArray
kString
kObject
kCode
kClosure
kRegExp
kHeapNumber
kNative
kSynthetic
kConsString
kSlicedString
kSymbol
kBigInt
kObjectShape
Definition at line 589 of file v8-profiler.h.
            {
    kHidden = 0, // Hidden node, may be filtered when shown to user.
    kArray = 1, // An array of elements.
    kString = 2, // A string.
    kObject = 3, // A JS object (except for arrays and strings).
    kCode = 4, // Compiled code.
    kClosure = 5, // Function closure.
    kRegExp = 6, // RegExp.
    kHeapNumber = 7, // Number stored in the heap.
    kNative = 8, // Native object (not from V8 heap).
    kSynthetic = 9, // Synthetic object, usually used for grouping
                         // snapshot items together.
    kConsString = 10, // Concatenated string. A pair of pointers to strings.
    kSlicedString = 11, // Sliced string. A fragment of another string.
    kSymbol = 12, // A Symbol (ES6).
    kBigInt = 13, // BigInt.
    kObjectShape = 14, // Internal data used for tracking the shapes (or
                         // "hidden classes") of JS objects.
  };
Member Function Documentation
GetChild()
const HeapGraphEdge * v8::HeapGraphNode::GetChild (int index) const
Retrieves a child by index.
Definition at line 11663 of file api.cc.
                                                            {
  return reinterpret_cast<const HeapGraphEdge*>(ToInternal(this)->child(index));
}
References v8::internal::index, and v8::ToInternal().
GetChildrenCount()
int v8::HeapGraphNode::GetChildrenCount () const
Returns child nodes count of the node.
Definition at line 11659 of file api.cc.
                                          {
  return ToInternal(this)->children_count();
}
References v8::ToInternal().
GetId()
SnapshotObjectId v8::HeapGraphNode::GetId () const
Returns node id.
For the same heap object, the id remains the same across all snapshots.
Definition at line 11653 of file api.cc.
{ return ToInternal(this)->id(); }
References v8::internal::CpuProfile::id(), and v8::ToInternal().
GetName()
Local< String > v8::HeapGraphNode::GetName () const
Returns node name.
Depending on node's type this can be the name of the constructor (for objects), the name of the function (for closures), string value, or an empty string (for compiled code).
Definition at line 11647 of file api.cc.
                                           {
  i::Isolate* i_isolate = ToInternal(this)->isolate();
  return ToApiHandle<String>(
      i_isolate->factory()->InternalizeUtf8String(ToInternal(this)->name()));
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), name, and v8::ToInternal().
GetShallowSize()
size_t v8::HeapGraphNode::GetShallowSize () const
Returns node's own size, in bytes.
Definition at line 11655 of file api.cc.
                                           {
  return ToInternal(this)->self_size();
}
References v8::ToInternal().
GetType()
HeapGraphNode::Type v8::HeapGraphNode::GetType () const
Returns node type (see HeapGraphNode::Type).
Definition at line 11643 of file api.cc.
                                               {
  return static_cast<HeapGraphNode::Type>(ToInternal(this)->type());
}
References v8::ToInternal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc