v8::internal::torque::CSAGenerator Class Reference
#include <csa-generator.h>
Public Member Functions
CSAGenerator (const ControlFlowGraph &cfg, std::ostream &out, std::optional< Builtin::Kind > linkage=std::nullopt)
std::optional< Stack< std::string > > EmitGraph (Stack< std::string > parameters)
Static Public Member Functions
static void EmitCSAValue (VisitResult result, const Stack< std::string > &values, std::ostream &out)
Static Public Attributes
static constexpr const char * ARGUMENTS_VARIABLE_STRING = `arguments`
Private Member Functions
void EmitSourcePosition (SourcePosition pos, bool always_emit=false) override
std::string PreCallableExceptionPreparation (std::optional< Block * > catch_block)
void PostCallableExceptionPreparation (const std::string &catch_name, const Type *return_type, std::optional< Block * > catch_block, Stack< std::string > *stack, const std::optional< DefinitionLocation > &exception_object_definition)
std::vector< std::string > ProcessArgumentsCommon (const TypeVector &parameter_types, std::vector< std::string > constexpr_arguments, Stack< std::string > *stack)
Stack< std::string > EmitBlock (const Block *block)
Private Attributes
std::optional< Builtin::Kind > linkage_
Additional Inherited Members
Detailed Description
Definition at line 14 of file csa-generator.h.
Constructor & Destructor Documentation
CSAGenerator()
v8::internal::torque::CSAGenerator::CSAGenerator (const ControlFlowGraph & cfg, std::ostream & out, std::optional< Builtin::Kind > linkage = std::nullopt) [inline]
Definition at line 16 of file csa-generator.h.
      : TorqueCodeGenerator(cfg, out), linkage_(linkage) {}
Member Function Documentation
EmitBlock()
Stack< std::string > v8::internal::torque::CSAGenerator::EmitBlock (const Block * block) [private]
Definition at line 69 of file csa-generator.cc.
                                                           {
  Stack<std::string> stack;
  std::stringstream phi_names;
  for (BottomOffset i = {0}; i < block->InputTypes().AboveTop(); ++i) {
    const auto& def = block->InputDefinitions().Peek(i);
    stack.Push(DefinitionToVariable(def));
    if (def.IsPhiFromBlock(block)) {
      decls() << " TNode<"
              << block->InputTypes().Peek(i)->GetGeneratedTNodeTypeName()
              << "> " << stack.Top() << ";\n";
      phi_names << ", &" << stack.Top();
    }
  }
  out() << " ca_.Bind(&" << BlockName(block) << phi_names.str() << ");\n";
  for (const Instruction& instruction : block->instructions()) {
    TorqueCodeGenerator::EmitInstruction(instruction, &stack);
  }
  return stack;
}
References v8::internal::torque::TorqueCodeGenerator::BlockName(), v8::internal::torque::TorqueCodeGenerator::decls(), v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), v8::internal::torque::TorqueCodeGenerator::EmitInstruction(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Block::InputDefinitions(), v8::internal::torque::Block::InputTypes(), v8::internal::torque::Block::instructions(), v8::internal::torque::TorqueCodeGenerator::out(), and v8::internal::stack.
Referenced by EmitGraph().
EmitCSAValue()
void v8::internal::torque::CSAGenerator::EmitCSAValue (VisitResult result, const Stack< std::string > & values, std::ostream & out) [static]
Definition at line 1061 of file csa-generator.cc.
                                                 {
  if (!result.IsOnStack()) {
    out << result.constexpr_value();
  } else if (auto struct_type = result.type()->StructSupertype()) {
    out << (*struct_type)->GetGeneratedTypeName() << "{";
    bool first = true;
    for (auto& field : (*struct_type)->fields()) {
      if (!first) {
        out << ", ";
      }
      first = false;
      EmitCSAValue(ProjectStructField(result, field.name_and_type.name), values,
                   out);
    }
    out << "}";
  } else {
    DCHECK_EQ(1, result.stack_range().Size());
    out << result.type()->GetGeneratedTypeName() << "{"
        << values.Peek(result.stack_range().begin()) << "}";
  }
}
References DCHECK_EQ, v8::internal::torque::TorqueCodeGenerator::out(), v8::internal::torque::Stack< T >::Peek(), v8::internal::torque::ProjectStructField(), and v8::base::internal::result.
Referenced by ProcessArgumentsCommon(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
EmitGraph()
std::optional< Stack< std::string > > v8::internal::torque::CSAGenerator::EmitGraph (Stack< std::string > parameters)
Definition at line 17 of file csa-generator.cc.
                                 {
  for (BottomOffset i = {0}; i < parameters.AboveTop(); ++i) {
    SetDefinitionVariable(DefinitionLocation::Parameter(i.offset),
                          parameters.Peek(i));
  }
  for (Block* block : cfg_.blocks()) {
    if (block->IsDead()) continue;
    out() << " compiler::CodeAssemblerParameterizedLabel<";
    bool first = true;
    DCHECK_EQ(block->InputTypes().Size(), block->InputDefinitions().Size());
    for (BottomOffset i = {0}; i < block->InputTypes().AboveTop(); ++i) {
      if (block->InputDefinitions().Peek(i).IsPhiFromBlock(block)) {
        if (!first) out() << ", ";
        out() << block->InputTypes().Peek(i)->GetGeneratedTNodeTypeName();
        first = false;
      }
    }
    out() << "> " << BlockName(block) << "(&ca_, compiler::CodeAssemblerLabel::"
          << (block->IsDeferred() ? "kDeferred" : "kNonDeferred") << ");\n";
  }
  EmitInstruction(GotoInstruction{cfg_.start()}, &parameters);
  for (Block* block : cfg_.blocks()) {
    if (cfg_.end() && *cfg_.end() == block) continue;
    if (block->IsDead()) continue;
    out() << "\n";
    // Redirect the output of non-declarations into a buffer and only output
    // declarations right away.
    std::stringstream out_buffer;
    std::ostream* old_out = out_;
    out_ = &out_buffer;
    out() << " if (" << BlockName(block) << ".is_used()) {\n";
    EmitBlock(block);
    out() << " }\n";
    // All declarations have been printed now, so we can append the buffered
    // output and redirect back to the original output stream.
    out_ = old_out;
    out() << out_buffer.str();
  }
  if (cfg_.end()) {
    out() << "\n";
    return EmitBlock(*cfg_.end());
  }
  return std::nullopt;
}
References v8::internal::torque::Stack< T >::AboveTop(), v8::internal::torque::TorqueCodeGenerator::BlockName(), v8::internal::torque::ControlFlowGraph::blocks(), v8::internal::torque::TorqueCodeGenerator::cfg_, DCHECK_EQ, EmitBlock(), v8::internal::torque::TorqueCodeGenerator::EmitInstruction(), v8::internal::torque::ControlFlowGraph::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::TorqueCodeGenerator::out(), v8::internal::torque::TorqueCodeGenerator::out_, v8::internal::torque::DefinitionLocation::Parameter(), v8::internal::torque::Stack< T >::Peek(), v8::internal::torque::TorqueCodeGenerator::SetDefinitionVariable(), and v8::internal::torque::ControlFlowGraph::start().
Referenced by v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
EmitSourcePosition()
void v8::internal::torque::CSAGenerator::EmitSourcePosition (SourcePosition pos, bool always_emit = false) [override], [private], [virtual]
Implements v8::internal::torque::TorqueCodeGenerator.
Definition at line 91 of file csa-generator.cc.
                                                                          {
  const std::string& file = SourceFileMap::AbsolutePath(pos.source);
  if (always_emit || !previous_position_.CompareStartIgnoreColumn(pos)) {
    // Lines in Torque SourcePositions are zero-based, while the
    // CodeStubAssembler and downwind systems are one-based.
    out() << " ca_.SetSourcePosition(\"" << file << "\", "
          << (pos.start.line + 1) << ");\n";
    previous_position_ = pos;
  }
}
References v8::internal::torque::SourceFileMap::AbsolutePath(), v8::internal::torque::SourcePosition::CompareStartIgnoreColumn(), file(), v8::internal::torque::LineAndColumn::line, v8::internal::torque::TorqueCodeGenerator::out(), v8::internal::torque::TorqueCodeGenerator::previous_position_, v8::internal::torque::SourcePosition::source, v8::internal::torque::SourcePosition::start, and v8::internal::string.
PostCallableExceptionPreparation()
void v8::internal::torque::CSAGenerator::PostCallableExceptionPreparation (const std::string & catch_name, const Type * return_type, std::optional< Block * > catch_block, Stack< std::string > * stack, const std::optional< DefinitionLocation > & exception_object_definition) [private]
Definition at line 672 of file csa-generator.cc.
                                                                        {
  if (catch_block) {
    DCHECK(exception_object_definition);
    std::string block_name = BlockName(*catch_block);
    out() << " }\n";
    out() << " if (" << catch_name << "__label.is_used()) {\n";
    out() << " compiler::CodeAssemblerLabel " << catch_name
          << "_skip(&ca_);\n";
    if (!return_type->IsNever()) {
      out() << " ca_.Goto(&" << catch_name << "_skip);\n";
    }
    decls() << " TNode<JSAny> "
            << DefinitionToVariable(*exception_object_definition) << ";\n";
    out() << " ca_.Bind(&" << catch_name << "__label, &"
          << DefinitionToVariable(*exception_object_definition) << ");\n";
    out() << " ca_.Goto(&" << block_name;
    DCHECK_EQ(stack->Size() + 1, (*catch_block)->InputDefinitions().Size());
    const auto& input_definitions = (*catch_block)->InputDefinitions();
    for (BottomOffset i = {0}; i < input_definitions.AboveTop(); ++i) {
      if (input_definitions.Peek(i).IsPhiFromBlock(*catch_block)) {
        if (i < stack->AboveTop()) {
          out() << ", " << stack->Peek(i);
        } else {
          DCHECK_EQ(i, stack->AboveTop());
          out() << ", " << DefinitionToVariable(*exception_object_definition);
        }
      }
    }
    out() << ");\n";
    if (!return_type->IsNever()) {
      out() << " ca_.Bind(&" << catch_name << "_skip);\n";
    }
    out() << " }\n";
  }
}
References v8::internal::torque::TorqueCodeGenerator::BlockName(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::torque::TorqueCodeGenerator::decls(), v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Type::IsNever(), v8::internal::torque::TorqueCodeGenerator::out(), v8::internal::stack, and v8::internal::string.
PreCallableExceptionPreparation()
std::string v8::internal::torque::CSAGenerator::PreCallableExceptionPreparation (std::optional< Block * > catch_block) [private]
Definition at line 659 of file csa-generator.cc.
                                     {
  std::string catch_name;
  if (catch_block) {
    catch_name = FreshCatchName();
    out() << " compiler::CodeAssemblerExceptionHandlerLabel " << catch_name
          << "__label(&ca_, compiler::CodeAssemblerLabel::kDeferred);\n";
    out() << " { compiler::ScopedExceptionHandler s(&ca_, &" << catch_name
          << "__label);\n";
  }
  return catch_name;
}
References v8::internal::torque::TorqueCodeGenerator::FreshCatchName(), v8::internal::torque::TorqueCodeGenerator::out(), and v8::internal::string.
ProcessArgumentsCommon()
std::vector< std::string > v8::internal::torque::CSAGenerator::ProcessArgumentsCommon (const TypeVector & parameter_types, std::vector< std::string > constexpr_arguments, Stack< std::string > * stack) [private]
Definition at line 154 of file csa-generator.cc.
                                                                       {
  std::vector<std::string> args;
  for (auto it = parameter_types.rbegin(); it != parameter_types.rend(); ++it) {
    const Type* type = *it;
    if (type->IsConstexpr()) {
      args.push_back(std::move(constexpr_arguments.back()));
      constexpr_arguments.pop_back();
    } else {
      std::stringstream s;
      size_t slot_count = LoweredSlotCount(type);
      VisitResult arg = VisitResult(type, stack->TopRange(slot_count));
      EmitCSAValue(arg, *stack, s);
      args.push_back(s.str());
      stack->PopMany(slot_count);
    }
  }
  std::reverse(args.begin(), args.end());
  return args;
}
References v8::base::args, EmitCSAValue(), v8::internal::torque::LoweredSlotCount(), v8::internal::stack, and v8::internal::tracing::type.
Member Data Documentation
ARGUMENTS_VARIABLE_STRING
constexpr const char* v8::internal::torque::CSAGenerator::ARGUMENTS_VARIABLE_STRING = `arguments` [static], [constexpr]
Definition at line 21 of file csa-generator.h.
linkage_
std::optional<Builtin::Kind> v8::internal::torque::CSAGenerator::linkage_ [private]
Definition at line 27 of file csa-generator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/csa-generator.h
/mnt/V8SourceCode/src/torque/csa-generator.cc