v8::internal::FrameInspector Class Reference
#include <debug-frames.h>
Public Member Functions
FrameInspector (CommonFrame *frame, int inlined_frame_index, Isolate *isolate)
FrameInspector (const FrameInspector &)=delete
FrameInspector & operator= (const FrameInspector &)=delete
~FrameInspector ()
Handle< JSFunction > GetFunction () const
Handle< Script > GetScript ()
Handle< Object > GetParameter (int index)
Handle< Object > GetExpression (int index)
int GetSourcePosition ()
bool IsConstructor ()
Handle< Object > GetContext ()
Handle< Object > GetReceiver ()
DirectHandle< String > GetFunctionName ()
bool IsJavaScript ()
JavaScriptFrame * javascript_frame ()
int inlined_frame_index () const
Private Member Functions
bool ParameterIsShadowedByContextLocal (DirectHandle< ScopeInfo > info, DirectHandle< String > parameter_name)
Private Attributes
CommonFrame * frame_
int inlined_frame_index_
std::unique_ptr< DeoptimizedFrameInfo > deoptimized_frame_
Isolate * isolate_
Handle< Script > script_
Handle< Object > receiver_
Handle< JSFunction > function_
int source_position_ = -1
bool is_optimized_ = false
bool is_constructor_ = false
Detailed Description
Definition at line 22 of file debug-frames.h.
Constructor & Destructor Documentation
FrameInspector() [1/2]
v8::internal::FrameInspector::FrameInspector (CommonFrame * frame, int inlined_frame_index, Isolate * isolate)
Definition at line 18 of file debug-frames.cc.
    : frame_(frame),
      inlined_frame_index_(inlined_frame_index),
      isolate_(isolate) {
  // Extract the relevant information from the frame summary and discard it.
  FrameSummary summary = FrameSummary::Get(frame, inlined_frame_index);
  summary.EnsureSourcePositionsAvailable();
  is_constructor_ = summary.is_constructor();
  source_position_ = summary.SourcePosition();
  script_ = Cast<Script>(summary.script());
  receiver_ = summary.receiver();
  if (summary.IsJavaScript()) {
    function_ = summary.AsJavaScript().function();
  }
#if V8_ENABLE_WEBASSEMBLY
  JavaScriptFrame* js_frame =
      frame->is_javascript() ? javascript_frame() : nullptr;
  DCHECK(js_frame || frame->is_wasm());
#else
  JavaScriptFrame* js_frame = javascript_frame();
#endif // V8_ENABLE_WEBASSEMBLY
  is_optimized_ = js_frame && js_frame->is_optimized();
  // Calculate the deoptimized frame.
  if (is_optimized_) {
    DCHECK_NOT_NULL(js_frame);
    deoptimized_frame_.reset(Deoptimizer::DebuggerInspectableFrame(
        js_frame, inlined_frame_index, isolate));
  }
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Deoptimizer::DebuggerInspectableFrame(), deoptimized_frame_, v8::internal::FrameSummary::EnsureSourcePositionsAvailable(), function_, v8::internal::FrameSummary::Get(), inlined_frame_index(), v8::internal::FrameSummary::is_constructor(), is_constructor_, v8::internal::StackFrame::is_javascript(), v8::internal::JavaScriptFrame::is_optimized(), is_optimized_, javascript_frame(), v8::internal::FrameSummary::receiver(), receiver_, v8::internal::FrameSummary::script(), script_, source_position_, and v8::internal::FrameSummary::SourcePosition().
FrameInspector() [2/2]
v8::internal::FrameInspector::FrameInspector (const FrameInspector &) [delete]
 FrameInspector()
v8::internal::FrameInspector::~FrameInspector () [default]
Member Function Documentation
GetContext()
Handle< Object > v8::internal::FrameInspector::GetContext ()
Definition at line 72 of file debug-frames.cc.
                                          {
  return deoptimized_frame_ ? deoptimized_frame_->GetContext()
                            : handle(frame_->context(), isolate_);
}
References v8::internal::CommonFrame::context(), deoptimized_frame_, frame_, v8::internal::handle(), and isolate_.
Referenced by v8::internal::ScopeIterator::Restart(), and v8::internal::ScopeIterator::ScopeIterator().
GetExpression()
Handle< Object > v8::internal::FrameInspector::GetExpression (int index)
Definition at line 67 of file debug-frames.cc.
                                                      {
  return is_optimized_ ? deoptimized_frame_->GetExpression(index)
                       : handle(frame_->GetExpression(index), isolate_);
}
References deoptimized_frame_, frame_, v8::internal::CommonFrame::GetExpression(), v8::internal::handle(), v8::internal::index, is_optimized_, and isolate_.
Referenced by v8::internal::ScopeIterator::VisitLocals(), and v8::internal::ScopeIterator::VisitLocalScope().
GetFunction()
Handle<JSFunction> v8::internal::FrameInspector::GetFunction () const [inline]
Definition at line 30 of file debug-frames.h.
{ return function_; }
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), v8::internal::DebugEvaluate::ContextBuilder::outer_info(), v8::internal::ScopeIterator::Restart(), and v8::internal::ScopeIterator::VisitLocals().
GetFunctionName()
DirectHandle< String > v8::internal::FrameInspector::GetFunctionName ()
Definition at line 77 of file debug-frames.cc.
                                                     {
#if V8_ENABLE_WEBASSEMBLY
  if (IsWasm()) {
#if V8_ENABLE_DRUMBRAKE
    if (IsWasmInterpreter()) {
      auto wasm_frame = WasmInterpreterEntryFrame::cast(frame_);
      auto instance_data =
          handle(wasm_frame->trusted_instance_data(), isolate_);
      return GetWasmFunctionDebugName(
          isolate_, instance_data,
          wasm_frame->function_index(inlined_frame_index_));
    }
#endif // V8_ENABLE_DRUMBRAKE
    auto wasm_frame = WasmFrame::cast(frame_);
    auto instance_data = handle(wasm_frame->trusted_instance_data(), isolate_);
    return GetWasmFunctionDebugName(isolate_, instance_data,
                                    wasm_frame->function_index());
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return JSFunction::GetDebugName(isolate_, function_);
}
References frame_, function_, v8::internal::JSFunction::GetDebugName(), v8::internal::GetWasmFunctionDebugName(), v8::internal::handle(), inlined_frame_index_, v8::internal::instance_data, and isolate_.
GetParameter()
Handle< Object > v8::internal::FrameInspector::GetParameter (int index)
Definition at line 61 of file debug-frames.cc.
                                                     {
  if (is_optimized_) return deoptimized_frame_->GetParameter(index);
  DCHECK(IsJavaScript());
  return handle(javascript_frame()->GetParameter(index), isolate_);
}
References v8::internal::DCHECK(), deoptimized_frame_, v8::internal::handle(), v8::internal::index, is_optimized_, IsJavaScript(), isolate_, and javascript_frame().
Referenced by v8::internal::ScopeIterator::VisitLocals().
GetReceiver()
Handle<Object> v8::internal::FrameInspector::GetReceiver () [inline]
Definition at line 37 of file debug-frames.h.
{ return receiver_; }
Referenced by v8::internal::ScopeIterator::VisitLocals().
GetScript()
Handle<Script> v8::internal::FrameInspector::GetScript () [inline]
Definition at line 31 of file debug-frames.h.
{ return script_; }
Referenced by v8::internal::ScopeIterator::ScopeIterator().
GetSourcePosition()
int v8::internal::FrameInspector::GetSourcePosition () [inline]
Definition at line 34 of file debug-frames.h.
{ return source_position_; }
Referenced by v8::internal::ScopeIterator::GetSourcePosition().
inlined_frame_index()
int v8::internal::FrameInspector::inlined_frame_index () const [inline]
Definition at line 51 of file debug-frames.h.
{ return inlined_frame_index_; }
Referenced by FrameInspector(), and v8::internal::ScopeIterator::VisitLocalScope().
IsConstructor()
bool v8::internal::FrameInspector::IsConstructor () [inline]
Definition at line 35 of file debug-frames.h.
{ return is_constructor_; }
IsJavaScript()
bool v8::internal::FrameInspector::IsJavaScript ()
Definition at line 108 of file debug-frames.cc.
{ return frame_->is_javascript(); }
References frame_, and v8::internal::StackFrame::is_javascript().
Referenced by GetParameter().
javascript_frame()
JavaScriptFrame * v8::internal::FrameInspector::javascript_frame ()
Definition at line 57 of file debug-frames.cc.
                                                  {
  return JavaScriptFrame::cast(frame_);
}
References v8::internal::JavaScriptFrame::cast(), and frame_.
Referenced by FrameInspector(), v8::internal::ScopeIterator::GetFrame(), and GetParameter().
operator=()
FrameInspector& v8::internal::FrameInspector::operator= (const FrameInspector &) [delete]
ParameterIsShadowedByContextLocal()
bool v8::internal::FrameInspector::ParameterIsShadowedByContextLocal (DirectHandle< ScopeInfo > info, DirectHandle< String > parameter_name) [private]
Definition at line 110 of file debug-frames.cc.
                                                                       {
  return info->ContextSlotIndex(*parameter_name) != -1;
}
Member Data Documentation
deoptimized_frame_
std::unique_ptr<DeoptimizedFrameInfo> v8::internal::FrameInspector::deoptimized_frame_ [private]
Definition at line 59 of file debug-frames.h.
Referenced by FrameInspector(), GetContext(), GetExpression(), and GetParameter().
frame_
CommonFrame* v8::internal::FrameInspector::frame_ [private]
Definition at line 57 of file debug-frames.h.
Referenced by GetContext(), GetExpression(), GetFunctionName(), IsJavaScript(), and javascript_frame().
function_
Handle<JSFunction> v8::internal::FrameInspector::function_ [private]
Definition at line 63 of file debug-frames.h.
Referenced by FrameInspector(), and GetFunctionName().
inlined_frame_index_
int v8::internal::FrameInspector::inlined_frame_index_ [private]
Definition at line 58 of file debug-frames.h.
Referenced by GetFunctionName().
is_constructor_
bool v8::internal::FrameInspector::is_constructor_ = false [private]
Definition at line 66 of file debug-frames.h.
Referenced by FrameInspector().
is_optimized_
bool v8::internal::FrameInspector::is_optimized_ = false [private]
Definition at line 65 of file debug-frames.h.
Referenced by FrameInspector(), GetExpression(), and GetParameter().
isolate_
Isolate* v8::internal::FrameInspector::isolate_ [private]
Definition at line 60 of file debug-frames.h.
Referenced by GetContext(), GetExpression(), GetFunctionName(), and GetParameter().
receiver_
Handle<Object> v8::internal::FrameInspector::receiver_ [private]
Definition at line 62 of file debug-frames.h.
Referenced by FrameInspector().
script_
Handle<Script> v8::internal::FrameInspector::script_ [private]
Definition at line 61 of file debug-frames.h.
Referenced by FrameInspector().
source_position_
int v8::internal::FrameInspector::source_position_ = -1 [private]
Definition at line 64 of file debug-frames.h.
Referenced by FrameInspector().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-frames.h
/mnt/V8SourceCode/src/debug/debug-frames.cc