v8::internal::SharedArrayBufferBuiltinsAssembler Class Reference
Public Member Functions
SharedArrayBufferBuiltinsAssembler (compiler::CodeAssemblerState *state)
Protected Types
using AssemblerFunction = TNode< Word32T >(CodeAssembler::*)(MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
template<class Type >
using AssemblerFunction64 = TNode< Type >(CodeAssembler::*)(TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
Protected Member Functions
void ValidateIntegerTypedArray (TNode< Object > maybe_array, TNode< Context > context, TNode< Int32T > *out_elements_kind, TNode< RawPtrT > *out_backing_store, Label *detached, Label *shared_struct_or_shared_array)
TNode< UintPtrT > ValidateAtomicAccess (TNode< JSTypedArray > array, TNode< JSAny > index, TNode< Context > context)
void DebugCheckAtomicIndex (TNode< JSTypedArray > array, TNode< UintPtrT > index)
void AtomicBinopBuiltinCommon (TNode< Object > maybe_array, TNode< JSAny > index, TNode< JSAny > value, TNode< Context > context, AssemblerFunction function, AssemblerFunction64< AtomicInt64 > function_int_64, AssemblerFunction64< AtomicUint64 > function_uint_64, Runtime::FunctionId runtime_function, const char *method_name)
TNode< BigInt > BigIntFromSigned64 (TNode< AtomicInt64 > signed64)
TNode< BigInt > BigIntFromUnsigned64 (TNode< AtomicUint64 > unsigned64)
Additional Inherited Members
Detailed Description
Definition at line 15 of file builtins-sharedarraybuffer-gen.cc.
Member Typedef Documentation
AssemblerFunction
using v8::internal::SharedArrayBufferBuiltinsAssembler::AssemblerFunction = TNode<Word32T> (CodeAssembler::*)(MachineType type, TNode<RawPtrT> base, TNode<UintPtrT> offset, TNode<Word32T> value) [protected]
Definition at line 22 of file builtins-sharedarraybuffer-gen.cc.
AssemblerFunction64
template<class Type >
using v8::internal::SharedArrayBufferBuiltinsAssembler::AssemblerFunction64 = TNode<Type> (CodeAssembler::*)(TNode<RawPtrT> base, TNode<UintPtrT> offset, TNode<UintPtrT> value, TNode<UintPtrT> value_high) [protected]
Definition at line 26 of file builtins-sharedarraybuffer-gen.cc.
Constructor & Destructor Documentation
SharedArrayBufferBuiltinsAssembler()
v8::internal::SharedArrayBufferBuiltinsAssembler::SharedArrayBufferBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 17 of file builtins-sharedarraybuffer-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
AtomicBinopBuiltinCommon()
void v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon (TNode< Object > maybe_array, TNode< JSAny > index, TNode< JSAny > value, TNode< Context > context, AssemblerFunction function, AssemblerFunction64< AtomicInt64 > function_int_64, AssemblerFunction64< AtomicUint64 > function_uint_64, Runtime::FunctionId runtime_function, const char * method_name) [protected]
Definition at line 747 of file builtins-sharedarraybuffer-gen.cc.
                                                                 {
  // 1. Let buffer be ? ValidateIntegerTypedArray(typedArray).
  Label detached_or_out_of_bounds(this);
  TNode<Int32T> elements_kind;
  TNode<RawPtrT> backing_store;
  ValidateIntegerTypedArray(maybe_array, context, &elements_kind,
                            &backing_store, &detached_or_out_of_bounds);
  TNode<JSTypedArray> array = CAST(maybe_array);
  // 2. Let i be ? ValidateAtomicAccess(typedArray, index).
  TNode<UintPtrT> index_word = ValidateAtomicAccess(array, index, context);
#if V8_TARGET_ARCH_MIPS64
  TNode<Number> index_number = ChangeUintPtrToTagged(index_word);
  Return(CallRuntime(runtime_function, context, array, index_number, value));
#else
  Label i8(this), u8(this), i16(this), u16(this), i32(this), u32(this),
      i64(this), u64(this), big(this), other(this);
  // 3. Let arrayTypeName be typedArray.[[TypedArrayName]].
  // 4. If typedArray.[[ContentType]] is BigInt, let v be ? ToBigInt(value).
  static_assert(BIGINT64_ELEMENTS > INT32_ELEMENTS);
  static_assert(BIGUINT64_ELEMENTS > INT32_ELEMENTS);
  GotoIf(Int32GreaterThan(elements_kind, Int32Constant(INT32_ELEMENTS)), &big);
  // 5. Otherwise, let v be ? ToInteger(value).
  TNode<Number> value_integer = ToInteger_Inline(context, value);
  // 6. If IsDetachedBuffer(buffer) is true, throw a TypeError exception.
  // 7. NOTE: The above check is not redundant with the check in
  // ValidateIntegerTypedArray because the call to ToBigInt or ToInteger on the
  // preceding lines can have arbitrary side effects, which could cause the
  // buffer to become detached or resized.
  CheckJSTypedArrayIndex(array, index_word, &detached_or_out_of_bounds);
  DebugCheckAtomicIndex(array, index_word);
  TNode<Word32T> value_word32 = TruncateTaggedToWord32(context, value_integer);
  // Steps 8-12.
  //
  // (Not copied from ecma262 due to the axiomatic nature of the memory model.)
  int32_t case_values[] = {
      INT8_ELEMENTS, UINT8_ELEMENTS, INT16_ELEMENTS,
      UINT16_ELEMENTS, INT32_ELEMENTS, UINT32_ELEMENTS,
  };
  Label* case_labels[] = {
      &i8, &u8, &i16, &u16, &i32, &u32,
  };
  Switch(elements_kind, &other, case_values, case_labels,
         arraysize(case_labels));
  BIND(&i8);
  Return(SmiFromInt32(Signed((this->*function)(
      MachineType::Int8(), backing_store, index_word, value_word32))));
  BIND(&u8);
  Return(SmiFromInt32(Signed((this->*function)(
      MachineType::Uint8(), backing_store, index_word, value_word32))));
  BIND(&i16);
  Return(SmiFromInt32(Signed((this->*function)(
      MachineType::Int16(), backing_store,
      WordShl(index_word, UintPtrConstant(1)), value_word32))));
  BIND(&u16);
  Return(SmiFromInt32(Signed((this->*function)(
      MachineType::Uint16(), backing_store,
      WordShl(index_word, UintPtrConstant(1)), value_word32))));
  BIND(&i32);
  Return(ChangeInt32ToTagged(Signed((this->*function)(
      MachineType::Int32(), backing_store,
      WordShl(index_word, UintPtrConstant(2)), value_word32))));
  BIND(&u32);
  Return(ChangeUint32ToTagged(Unsigned((this->*function)(
      MachineType::Uint32(), backing_store,
      WordShl(index_word, UintPtrConstant(2)), value_word32))));
  BIND(&big);
  // 4. If typedArray.[[ContentType]] is BigInt, let v be ? ToBigInt(value).
  TNode<BigInt> value_bigint = ToBigInt(context, value);
  // 6. If IsDetachedBuffer(buffer) is true, throw a TypeError exception.
  CheckJSTypedArrayIndex(array, index_word, &detached_or_out_of_bounds);
  DebugCheckAtomicIndex(array, index_word);
  TVARIABLE(UintPtrT, var_low);
  TVARIABLE(UintPtrT, var_high);
  BigIntToRawBytes(value_bigint, &var_low, &var_high);
  TNode<UintPtrT> high = Is64() ? TNode<UintPtrT>() : var_high.value();
  GotoIf(Word32Equal(elements_kind, Int32Constant(BIGINT64_ELEMENTS)), &i64);
  GotoIf(Word32Equal(elements_kind, Int32Constant(BIGUINT64_ELEMENTS)), &u64);
  Unreachable();
  BIND(&i64);
  Return(BigIntFromSigned64((this->*function_int_64)(
      backing_store, WordShl(index_word, UintPtrConstant(3)), var_low.value(),
      high)));
  BIND(&u64);
  Return(BigIntFromUnsigned64((this->*function_uint_64)(
      backing_store, WordShl(index_word, UintPtrConstant(3)), var_low.value(),
      high)));
  // // This shouldn't happen, we've already validated the type.
  BIND(&other);
  Unreachable();
#endif // V8_TARGET_ARCH_MIPS64
  BIND(&detached_or_out_of_bounds);
  ThrowTypeError(context, MessageTemplate::kDetachedOperation, method_name);
}
References arraysize, BigIntFromSigned64(), BigIntFromUnsigned64(), v8::internal::CodeStubAssembler::BigIntToRawBytes(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::CodeStubAssembler::ChangeInt32ToTagged(), v8::internal::CodeStubAssembler::ChangeUint32ToTagged(), v8::internal::CodeStubAssembler::ChangeUintPtrToTagged(), v8::internal::CodeStubAssembler::CheckJSTypedArrayIndex(), DebugCheckAtomicIndex(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::index, v8::internal::MachineType::Int16(), v8::internal::maglev::INT16_ELEMENTS, v8::internal::MachineType::Int32(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::MachineType::Int8(), v8::internal::maglev::INT8_ELEMENTS, v8::internal::compiler::CodeAssembler::Is64(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::compiler::CodeAssembler::Switch(), v8::internal::CodeStubAssembler::ThrowTypeError(), v8::internal::CodeStubAssembler::ToBigInt(), v8::internal::CodeStubAssembler::TruncateTaggedToWord32(), v8::internal::MachineType::Uint16(), v8::internal::maglev::UINT16_ELEMENTS, v8::internal::MachineType::Uint32(), v8::internal::MachineType::Uint8(), v8::internal::maglev::UINT8_ELEMENTS, v8::internal::compiler::CodeAssembler::UintPtrConstant(), v8::internal::compiler::CodeAssembler::Unreachable(), v8::internal::compiler::CodeAssembler::Unsigned(), ValidateAtomicAccess(), ValidateIntegerTypedArray(), v8::internal::value, v8::internal::compiler::CodeAssembler::Word32Equal(), and v8::internal::compiler::CodeAssembler::WordShl().
BigIntFromSigned64()
TNode< BigInt > v8::internal::SharedArrayBufferBuiltinsAssembler::BigIntFromSigned64 (TNode< AtomicInt64 > signed64) [protected]
Definition at line 209 of file builtins-sharedarraybuffer-gen.cc.
                                 {
#if defined(V8_HOST_ARCH_32_BIT)
  TNode<IntPtrT> low = Projection<0>(signed64);
  TNode<IntPtrT> high = Projection<1>(signed64);
  return BigIntFromInt32Pair(low, high);
#else
  return BigIntFromInt64(signed64);
#endif
}
References v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), and v8::internal::CodeStubAssembler::BigIntFromInt64().
Referenced by AtomicBinopBuiltinCommon().
BigIntFromUnsigned64()
TNode< BigInt > v8::internal::SharedArrayBufferBuiltinsAssembler::BigIntFromUnsigned64 (TNode< AtomicUint64 > unsigned64) [protected]
Definition at line 220 of file builtins-sharedarraybuffer-gen.cc.
                                    {
#if defined(V8_HOST_ARCH_32_BIT)
  TNode<UintPtrT> low = Projection<0>(unsigned64);
  TNode<UintPtrT> high = Projection<1>(unsigned64);
  return BigIntFromUint32Pair(low, high);
#else
  return BigIntFromUint64(unsigned64);
#endif
}
References v8::internal::CodeStubAssembler::BigIntFromUint32Pair(), and v8::internal::CodeStubAssembler::BigIntFromUint64().
Referenced by AtomicBinopBuiltinCommon().
DebugCheckAtomicIndex()
void v8::internal::SharedArrayBufferBuiltinsAssembler::DebugCheckAtomicIndex (TNode< JSTypedArray > array, TNode< UintPtrT > index) [inline], [protected]
Definition at line 183 of file builtins-sharedarraybuffer-gen.cc.
                                                      {
#if DEBUG
  // In Debug mode, we re-validate the index as a sanity check because ToInteger
  // above calls out to JavaScript. Atomics work on ArrayBuffers, which may be
  // detached, and detachment state must be checked and throw before this
  // check. Moreover, resizable ArrayBuffers can be shrunk.
  //
  // This function must always be called after ValidateIntegerTypedArray, which
  // will ensure that LoadJSArrayBufferViewBuffer will not be null.
  Label detached_or_out_of_bounds(this), end(this);
  CSA_DCHECK(this, Word32BinaryNot(
                       IsDetachedBuffer(LoadJSArrayBufferViewBuffer(array))));
  CSA_DCHECK(this,
             UintPtrLessThan(index, LoadJSTypedArrayLengthAndCheckDetached(
                                        array, &detached_or_out_of_bounds)));
  Goto(&end);
  BIND(&detached_or_out_of_bounds);
  Unreachable();
  BIND(&end);
#endif
}
References v8::internal::compiler::end(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::index, v8::internal::CodeStubAssembler::LoadJSArrayBufferViewBuffer(), v8::internal::CodeStubAssembler::LoadJSTypedArrayLengthAndCheckDetached(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), and v8::internal::compiler::CodeAssembler::Unreachable().
Referenced by AtomicBinopBuiltinCommon().
ValidateAtomicAccess()
TNode< UintPtrT > v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateAtomicAccess (TNode< JSTypedArray > array, TNode< JSAny > index, TNode< Context > context) [protected]
Definition at line 154 of file builtins-sharedarraybuffer-gen.cc.
                                                                           {
  Label done(this), range_error(this), unreachable(this);
  // 1. Assert: typedArray is an Object that has a [[ViewedArrayBuffer]]
  // internal slot.
  // 2. Let length be IntegerIndexedObjectLength(typedArray);
  TNode<UintPtrT> array_length =
      LoadJSTypedArrayLengthAndCheckDetached(array, &unreachable);
  // 3. Let accessIndex be ? ToIndex(requestIndex).
  TNode<UintPtrT> index_uintptr = ToIndex(context, index, &range_error);
  // 4. Assert: accessIndex ≥ 0.
  // 5. If accessIndex ≥ length, throw a RangeError exception.
  Branch(UintPtrLessThan(index_uintptr, array_length), &done, &range_error);
  BIND(&unreachable);
  // This should not happen, since we've just called ValidateIntegerTypedArray.
  Unreachable();
  BIND(&range_error);
  ThrowRangeError(context, MessageTemplate::kInvalidAtomicAccessIndex);
  // 6. Return accessIndex.
  BIND(&done);
  return index_uintptr;
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::index, v8::internal::CodeStubAssembler::LoadJSTypedArrayLengthAndCheckDetached(), v8::internal::CodeStubAssembler::ThrowRangeError(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), and v8::internal::compiler::CodeAssembler::Unreachable().
Referenced by AtomicBinopBuiltinCommon().
ValidateIntegerTypedArray()
void v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray (TNode< Object > maybe_array, TNode< Context > context, TNode< Int32T > * out_elements_kind, TNode< RawPtrT > * out_backing_store, Label * detached, Label * shared_struct_or_shared_array = nullptr) [protected]
Definition at line 57 of file builtins-sharedarraybuffer-gen.cc.
                                                                        {
  Label not_float_or_clamped(this), invalid(this);
  // The logic of TypedArrayBuiltinsAssembler::ValidateTypedArrayBuffer is
  // inlined to avoid duplicate error branches.
  // Fail if it is not a heap object.
  GotoIf(TaggedIsSmi(maybe_array_or_shared_object), &invalid);
  // Fail if the array's instance type is not JSTypedArray.
  TNode<Map> map = LoadMap(CAST(maybe_array_or_shared_object));
  GotoIfNot(IsJSTypedArrayMap(map), &invalid);
  TNode<JSTypedArray> array = CAST(maybe_array_or_shared_object);
  // Fail if the array's JSArrayBuffer is detached / out of bounds.
  GotoIf(IsJSArrayBufferViewDetachedOrOutOfBoundsBoolean(array), detached);
  // Fail if the array's element type is float16, float32, float64 or clamped.
  // clang-format off
  static_assert(
      INT8_ELEMENTS >= FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND &&
      INT8_ELEMENTS <= LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(
      INT16_ELEMENTS >= FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND &&
      INT16_ELEMENTS <= LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(
      INT32_ELEMENTS >= FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND &&
      INT32_ELEMENTS <= LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(
      BIGINT64_ELEMENTS >= FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND &&
      BIGINT64_ELEMENTS <= LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(
      UINT8_ELEMENTS >= FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND &&
      UINT8_ELEMENTS <= LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(
      UINT16_ELEMENTS >= FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND &&
      UINT16_ELEMENTS <= LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(
      UINT32_ELEMENTS >= FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND &&
      UINT32_ELEMENTS <= LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(
      BIGUINT64_ELEMENTS >= FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND &&
      BIGUINT64_ELEMENTS <= LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(FLOAT16_ELEMENTS >=
                LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(FLOAT32_ELEMENTS >=
                LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(FLOAT64_ELEMENTS >=
                LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  static_assert(UINT8_CLAMPED_ELEMENTS >=
                LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND);
  // clang-format on
  TNode<Int32T> elements_kind =
      GetNonRabGsabElementsKind(LoadMapElementsKind(map));
  CSA_DCHECK(this, Int32GreaterThanOrEqual(
                       elements_kind,
                       Int32Constant(FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND)));
  CSA_DCHECK(this, Int32LessThanOrEqual(
                       elements_kind,
                       Int32Constant(LAST_FIXED_TYPED_ARRAY_ELEMENTS_KIND)));
  CSA_DCHECK(this,
             Int32GreaterThanOrEqual(
                 elements_kind,
                 Int32Constant(FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND)));
  Branch(Int32LessThanOrEqual(
             elements_kind,
             Int32Constant(LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND)),
         &not_float_or_clamped, &invalid);
  BIND(&invalid);
  {
    if (is_shared_struct_or_shared_array) {
      GotoIf(IsJSSharedStruct(maybe_array_or_shared_object),
             is_shared_struct_or_shared_array);
      GotoIf(IsJSSharedArray(maybe_array_or_shared_object),
             is_shared_struct_or_shared_array);
    }
    ThrowTypeError(context, MessageTemplate::kNotIntegerTypedArray,
                   maybe_array_or_shared_object);
  }
  BIND(&not_float_or_clamped);
  *out_elements_kind = elements_kind;
  TNode<JSArrayBuffer> array_buffer = GetTypedArrayBuffer(context, array);
  TNode<RawPtrT> backing_store = LoadJSArrayBufferBackingStorePtr(array_buffer);
  TNode<UintPtrT> byte_offset = LoadJSArrayBufferViewByteOffset(array);
  *out_backing_store = RawPtrAdd(backing_store, Signed(byte_offset));
}
References v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::FIRST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::CodeStubAssembler::GetNonRabGsabElementsKind(), v8::internal::CodeStubAssembler::GetTypedArrayBuffer(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::maglev::INT16_ELEMENTS, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::maglev::INT8_ELEMENTS, v8::internal::CodeStubAssembler::IsJSArrayBufferViewDetachedOrOutOfBoundsBoolean(), v8::internal::CodeStubAssembler::IsJSSharedArray(), v8::internal::CodeStubAssembler::IsJSSharedStruct(), v8::internal::CodeStubAssembler::IsJSTypedArrayMap(), v8::internal::LAST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::LAST_VALID_ATOMICS_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::CodeStubAssembler::LoadJSArrayBufferBackingStorePtr(), v8::internal::CodeStubAssembler::LoadJSArrayBufferViewByteOffset(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), v8::internal::compiler::CodeAssembler::RawPtrAdd(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::CodeStubAssembler::ThrowTypeError(), v8::internal::maglev::UINT16_ELEMENTS, v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, and v8::internal::maglev::UINT8_ELEMENTS.
Referenced by AtomicBinopBuiltinCommon().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-sharedarraybuffer-gen.cc