v8::internal::compiler::ContextRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< Context > object () const
ContextRef previous (JSHeapBroker *broker, size_t *depth) const
OptionalObjectRef get (JSHeapBroker *broker, int index) const
ScopeInfoRef scope_info (JSHeapBroker *broker) const
Detailed Description
Definition at line 733 of file heap-refs.h.
Member Function Documentation
get()
OptionalObjectRef v8::internal::compiler::ContextRef::get (JSHeapBroker * broker, int index) const
Definition at line 1008 of file heap-refs.cc.
                                                                       {
  CHECK_LE(0, index);
  // Length is immutable after initialization.
  if (index >= object()->length(kRelaxedLoad)) return {};
  return TryMakeRef(broker, object()->get(index, kRelaxedLoad));
}
References broker(), CHECK_LE, v8::internal::index, v8::kRelaxedLoad, v8::internal::length, and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::maglev::MaglevGraphBuilder::CheckContextExtensions(), v8::internal::compiler::CompilationDependencies::DependOnContextCell(), v8::internal::compiler::GlobalAccessFeedback::GetConstantHint(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSContextSpecialization::ReduceJSGetImportMeta(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextConstantLoad(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlotToFunctionContext(), and v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot().
object()
IndirectHandle<Context> v8::internal::compiler::ContextRef::object () const
Referenced by v8::internal::compiler::CompilationDependencies::DependOnContextCell(), previous(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), and v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext().
previous()
ContextRef v8::internal::compiler::ContextRef::previous (JSHeapBroker * broker, size_t * depth) const
Definition at line 993 of file heap-refs.cc.
                                                                         {
  DCHECK_NOT_NULL(depth);
  if (*depth == 0) return *this;
  Tagged<Context> current = *object();
  while (*depth != 0 && i::IsContext(current->unchecked_previous())) {
    current = Cast<Context>(current->unchecked_previous());
    (*depth)--;
  }
  // The `previous` field is immutable after initialization and the
  // context itself is read through an atomic load.
  return MakeRefAssumeMemoryFence(broker, current);
}
References broker(), DCHECK_NOT_NULL, v8::internal::compiler::MakeRefAssumeMemoryFence(), and object().
Referenced by v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), and v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContextNoCell().
scope_info()
ScopeInfoRef v8::internal::compiler::ContextRef::scope_info (JSHeapBroker * broker) const
Definition at line 1916 of file heap-refs.cc.
                                                              {
  // The scope_info is immutable after initialization.
  return MakeRefAssumeMemoryFence(broker, object()->scope_info());
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc