v8::internal::ForStatement Class Reference
#include <ast.h>
Public Member Functions
void Initialize (Statement *init, Expression *cond, Statement *next, Statement *body)
Statement * init () const
Expression * cond () const
Statement * next () const
Private Member Functions
ForStatement (int pos)
Private Attributes
friend Zone
Statement * init_
Expression * cond_
Statement * next_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 492 of file ast.h.
Constructor & Destructor Documentation
ForStatement()
v8::internal::ForStatement::ForStatement (int pos) [inline], [explicit], [private]
Definition at line 510 of file ast.h.
      : IterationStatement(pos, kForStatement),
        init_(nullptr),
        cond_(nullptr),
        next_(nullptr) {}
Member Function Documentation
cond()
Expression* v8::internal::ForStatement::cond () const [inline]
Definition at line 503 of file ast.h.
{ return cond_; }
References cond_.
Referenced by Initialize().
init()
Statement* v8::internal::ForStatement::init () const [inline]
Definition at line 502 of file ast.h.
{ return init_; }
References init_.
Referenced by Initialize().
Initialize()
void v8::internal::ForStatement::Initialize (Statement * init, Expression * cond, Statement * next, Statement * body) [inline]
Definition at line 494 of file ast.h.
                                   {
    IterationStatement::Initialize(body);
    init_ = init;
    cond_ = cond;
    next_ = next;
  }
References v8::internal::IterationStatement::body(), cond(), cond_, init(), init_, v8::internal::IterationStatement::Initialize(), next(), and next_.
Referenced by v8::internal::Parser::DesugarLexicalBindingsInForStatement().
next()
Statement* v8::internal::ForStatement::next () const [inline]
Definition at line 504 of file ast.h.
{ return next_; }
References next_.
Referenced by Initialize().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 507 of file ast.h.
Member Data Documentation
cond_
Expression* v8::internal::ForStatement::cond_ [private]
Definition at line 517 of file ast.h.
Referenced by cond(), and Initialize().
init_
Statement* v8::internal::ForStatement::init_ [private]
Definition at line 516 of file ast.h.
Referenced by init(), and Initialize().
next_
Statement* v8::internal::ForStatement::next_ [private]
Definition at line 518 of file ast.h.
Referenced by Initialize(), and next().
Zone
friend v8::internal::ForStatement::Zone [private]
Definition at line 508 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h