v8::internal::MainAllocator Class Reference
#include <main-allocator.h>
Classes
struct InGCTag
Public Types
enum class IsNewGeneration { kNo
, kYes
 }
Public Member Functions
V8_EXPORT_PRIVATE MainAllocator (LocalHeap *heap, SpaceWithLinearArea *space, IsNewGeneration is_new_generation, LinearAllocationArea *allocation_info=nullptr)
V8_EXPORT_PRIVATE MainAllocator (Heap *heap, SpaceWithLinearArea *space, InGCTag)
Address start () const
Address top () const
Address limit () const
Address * allocation_top_address () const
Address * allocation_limit_address () const
std::pair< Address, Address > GetOriginalTopAndLimit () const
void MoveOriginalTopForward ()
V8_EXPORT_PRIVATE void ResetLab (Address start, Address end, Address extended_end)
V8_EXPORT_PRIVATE bool IsPendingAllocation (Address object_address)
LinearAllocationArea & allocation_info ()
const LinearAllocationArea & allocation_info () const
AllocationCounter & allocation_counter ()
const AllocationCounter & allocation_counter () const
V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin, AllocationHint hint)
V8_WARN_UNUSED_RESULT V8_EXPORT_PRIVATE AllocationResult AllocateRawForceAlignmentForTesting (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin)
V8_EXPORT_PRIVATE void AddAllocationObserver (AllocationObserver *observer)
V8_EXPORT_PRIVATE void RemoveAllocationObserver (AllocationObserver *observer)
void PauseAllocationObservers ()
void ResumeAllocationObservers ()
V8_EXPORT_PRIVATE void AdvanceAllocationObservers ()
V8_EXPORT_PRIVATE void InvokeAllocationObservers (Address soon_object, size_t size_in_bytes, size_t aligned_size_in_bytes, size_t allocation_size)
V8_EXPORT_PRIVATE void MakeLinearAllocationAreaIterable ()
V8_EXPORT_PRIVATE void MarkLinearAllocationAreaBlack ()
V8_EXPORT_PRIVATE void UnmarkLinearAllocationArea ()
V8_EXPORT_PRIVATE void FreeLinearAllocationAreaAndResetFreeList ()
V8_EXPORT_PRIVATE Address AlignTopForTesting (AllocationAlignment alignment, int offset)
bool TryFreeLast (Address object_address, int object_size)
Address ComputeLimit (Address start, Address end, size_t min_size) const
bool IsLabValid () const
V8_EXPORT_PRIVATE void FreeLinearAllocationArea ()
void ExtendLAB (Address limit)
V8_EXPORT_PRIVATE bool EnsureAllocationForTesting (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin)
Static Public Attributes
static constexpr InGCTag kInGC {}
Private Types
enum class BlackAllocation { kAlwaysEnabled
, kAlwaysDisabled
, kEnabledOnMarking
 }
Private Member Functions
V8_WARN_UNUSED_RESULT AllocationResult AllocateFastUnaligned (int size_in_bytes, AllocationOrigin origin)
V8_WARN_UNUSED_RESULT AllocationResult AllocateFastAligned (int size_in_bytes, int *result_aligned_size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin)
V8_WARN_UNUSED_RESULT V8_EXPORT_PRIVATE AllocationResult AllocateRawSlow (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin)
V8_WARN_UNUSED_RESULT AllocationResult AllocateRawSlowUnaligned (int size_in_bytes, AllocationOrigin origin=AllocationOrigin::kRuntime)
V8_WARN_UNUSED_RESULT AllocationResult AllocateRawSlowAligned (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin=AllocationOrigin::kRuntime)
bool EnsureAllocation (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin)
void MarkLabStartInitialized ()
bool IsBlackAllocationEnabled () const
LinearAreaOriginalData & linear_area_original_data ()
const LinearAreaOriginalData & linear_area_original_data () const
int ObjectAlignment () const
AllocationSpace identity () const
bool SupportsAllocationObserver () const
bool SupportsPendingAllocation () const
bool in_gc () const
bool in_gc_for_space () const
Address extended_limit () const
bool supports_extending_lab () const
V8_EXPORT_PRIVATE bool is_main_thread () const
LocalHeap * local_heap () const
Heap * isolate_heap () const
V8_EXPORT_PRIVATE Heap * space_heap () const
Static Private Member Functions
static constexpr BlackAllocation ComputeBlackAllocation (IsNewGeneration)
Private Attributes
LocalHeap *const local_heap_
Heap *const isolate_heap_
SpaceWithLinearArea *const space_
std::optional< AllocationCounter > allocation_counter_
LinearAllocationArea *const allocation_info_
LinearAllocationArea owned_allocation_info_
Address extended_limit_
std::optional< LinearAreaOriginalData > linear_area_original_data_
std::unique_ptr< AllocatorPolicy > allocator_policy_
const bool supports_extending_lab_
const BlackAllocation black_allocation_
Friends
class AllocatorPolicy
class PagedSpaceAllocatorPolicy
class SemiSpaceNewSpaceAllocatorPolicy
Detailed Description
Definition at line 153 of file main-allocator.h.
Member Enumeration Documentation
BlackAllocation
enum v8::internal::MainAllocator::BlackAllocation [strong], [private]
Enumerator
kAlwaysEnabled
kAlwaysDisabled
kEnabledOnMarking
Definition at line 266 of file main-allocator.h.
                             {
    kAlwaysEnabled,
    kAlwaysDisabled,
    kEnabledOnMarking
  };
IsNewGeneration
enum v8::internal::MainAllocator::IsNewGeneration [strong]
Enumerator
kNo
kYes
Definition at line 158 of file main-allocator.h.
{ kNo, kYes };
Constructor & Destructor Documentation
MainAllocator() [1/2]
v8::internal::MainAllocator::MainAllocator (LocalHeap * heap, SpaceWithLinearArea * space, IsNewGeneration is_new_generation, LinearAllocationArea * allocation_info = nullptr)
Definition at line 39 of file main-allocator.cc.
    : local_heap_(local_heap),
      isolate_heap_(local_heap->heap()),
      space_(space),
      allocation_info_(allocation_info != nullptr ? allocation_info
                                                  : &owned_allocation_info_),
      allocator_policy_(space->CreateAllocatorPolicy(this)),
      supports_extending_lab_(allocator_policy_->SupportsExtendingLAB()),
      black_allocation_(ComputeBlackAllocation(is_new_generation)) {
  CHECK_NOT_NULL(local_heap_);
  if (local_heap_->is_main_thread()) {
    allocation_counter_.emplace();
    linear_area_original_data_.emplace();
  }
}
References allocation_counter_, CHECK_NOT_NULL, v8::internal::LocalHeap::is_main_thread(), linear_area_original_data_, and local_heap_.
MainAllocator() [2/2]
v8::internal::MainAllocator::MainAllocator (Heap * heap, SpaceWithLinearArea * space, InGCTag)
Definition at line 57 of file main-allocator.cc.
    : local_heap_(nullptr),
      isolate_heap_(heap),
      space_(space),
      allocation_info_(&owned_allocation_info_),
      allocator_policy_(space->CreateAllocatorPolicy(this)),
      supports_extending_lab_(false),
      black_allocation_(BlackAllocation::kAlwaysDisabled) {
  DCHECK(!allocation_counter_.has_value());
  DCHECK(!linear_area_original_data_.has_value());
}
References allocation_counter_, v8::internal::DCHECK(), and linear_area_original_data_.
Member Function Documentation
AddAllocationObserver()
void v8::internal::MainAllocator::AddAllocationObserver (AllocationObserver * observer)
Definition at line 102 of file main-allocator.cc.
                                                                      {
  // Adding an allocation observer may decrease the inline allocation limit, so
  // we check here that we don't have an existing LAB.
  CHECK(!allocation_counter().IsStepInProgress());
  DCHECK(!IsLabValid());
  allocation_counter().AddAllocationObserver(observer);
}
References v8::internal::AllocationCounter::AddAllocationObserver(), allocation_counter(), CHECK, v8::internal::DCHECK(), and IsLabValid().
Referenced by v8::internal::ScheduleMinorGCTaskObserver::AddToNewSpace(), and v8::internal::Heap::SetUpSpaces().
AdvanceAllocationObservers()
void v8::internal::MainAllocator::AdvanceAllocationObservers ()
Definition at line 122 of file main-allocator.cc.
                                               {
  if (SupportsAllocationObserver() && allocation_info().top() &&
      allocation_info().start() != allocation_info().top()) {
    if (isolate_heap()->IsAllocationObserverActive()) {
      allocation_counter().AdvanceAllocationObservers(
          allocation_info().top() - allocation_info().start());
    }
    MarkLabStartInitialized();
  }
}
References v8::internal::AllocationCounter::AdvanceAllocationObservers(), allocation_counter(), allocation_info(), isolate_heap(), MarkLabStartInitialized(), start(), SupportsAllocationObserver(), and top().
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
AlignTopForTesting()
Address v8::internal::MainAllocator::AlignTopForTesting (AllocationAlignment alignment, int offset)
Definition at line 69 of file main-allocator.cc.
                                                      {
  DCHECK(top());
  int filler_size = Heap::GetFillToAlign(top(), alignment);
  if (filler_size + offset) {
    space_heap()->CreateFillerObjectAt(top(), filler_size + offset);
    allocation_info().IncrementTop(filler_size + offset);
  }
  return top();
}
References allocation_info(), v8::internal::Heap::CreateFillerObjectAt(), v8::internal::DCHECK(), v8::internal::Heap::GetFillToAlign(), v8::internal::LinearAllocationArea::IncrementTop(), space_heap(), and top().
AllocateFastAligned()
AllocationResult v8::internal::MainAllocator::AllocateFastAligned (int size_in_bytes, int * result_aligned_size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) [inline], [private]
Definition at line 61 of file main-allocator-inl.h.
                                                            {
  Address top = allocation_info().top();
  int filler_size = Heap::GetFillToAlign(top, alignment);
  int aligned_size_in_bytes = size_in_bytes + filler_size;
  if (!allocation_info().CanIncrementTop(aligned_size_in_bytes)) {
    return AllocationResult::Failure();
  }
  Tagged<HeapObject> obj = HeapObject::FromAddress(
      allocation_info().IncrementTop(aligned_size_in_bytes));
  if (result_aligned_size_in_bytes)
    *result_aligned_size_in_bytes = aligned_size_in_bytes;
  if (filler_size > 0) {
    obj = space_heap()->PrecedeWithFiller(obj, filler_size);
  }
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(obj.address(), size_in_bytes);
  DCHECK_IMPLIES(black_allocation_ == BlackAllocation::kAlwaysEnabled,
                 space_heap()->marking_state()->IsMarked(obj));
  return AllocationResult::FromObject(obj);
}
References v8::internal::Tagged< HeapObject >::address(), allocation_info(), black_allocation_, DCHECK_IMPLIES, v8::internal::AllocationResult::Failure(), v8::internal::HeapObject::FromAddress(), v8::internal::AllocationResult::FromObject(), v8::internal::Heap::GetFillToAlign(), kAlwaysEnabled, MSAN_ALLOCATED_UNINITIALIZED_MEMORY, v8::internal::Heap::PrecedeWithFiller(), space_heap(), v8::internal::LinearAllocationArea::top(), and top().
Referenced by AllocateRaw(), AllocateRawForceAlignmentForTesting(), and AllocateRawSlowAligned().
AllocateFastUnaligned()
AllocationResult v8::internal::MainAllocator::AllocateFastUnaligned (int size_in_bytes, AllocationOrigin origin) [inline], [private]
Definition at line 44 of file main-allocator-inl.h.
                                                                               {
  size_in_bytes = ALIGN_TO_ALLOCATION_ALIGNMENT(size_in_bytes);
  if (!allocation_info().CanIncrementTop(size_in_bytes)) {
    return AllocationResult::Failure();
  }
  Tagged<HeapObject> obj =
      HeapObject::FromAddress(allocation_info().IncrementTop(size_in_bytes));
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(obj.address(), size_in_bytes);
  DCHECK_IMPLIES(black_allocation_ == BlackAllocation::kAlwaysEnabled,
                 space_heap()->marking_state()->IsMarked(obj));
  return AllocationResult::FromObject(obj);
}
References v8::internal::Tagged< HeapObject >::address(), ALIGN_TO_ALLOCATION_ALIGNMENT, allocation_info(), black_allocation_, DCHECK_IMPLIES, v8::internal::AllocationResult::Failure(), v8::internal::HeapObject::FromAddress(), v8::internal::AllocationResult::FromObject(), kAlwaysEnabled, MSAN_ALLOCATED_UNINITIALIZED_MEMORY, and space_heap().
Referenced by AllocateRaw(), and AllocateRawSlowUnaligned().
AllocateRaw()
AllocationResult v8::internal::MainAllocator::AllocateRaw (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin, AllocationHint hint) [inline]
Definition at line 18 of file main-allocator-inl.h.
                                                                 {
  size_in_bytes = ALIGN_TO_ALLOCATION_ALIGNMENT(size_in_bytes);
  DCHECK_EQ(in_gc(), origin == AllocationOrigin::kGC);
  DCHECK_EQ(in_gc(), isolate_heap()->IsInGC());
  // We are not supposed to allocate in fast c calls.
  DCHECK_IMPLIES(is_main_thread(),
                 v8_flags.allow_allocation_in_fast_api_call ||
                     !isolate_heap()->isolate()->InFastCCall());
  AllocationResult result;
  if (alignment != kTaggedAligned) [[unlikely]] {
    result = AllocateFastAligned(size_in_bytes, nullptr, alignment, origin);
  } else {
    result = AllocateFastUnaligned(size_in_bytes, origin);
  }
  return result.IsFailure() ? AllocateRawSlow(size_in_bytes, alignment, origin)
                            : result;
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, AllocateFastAligned(), AllocateFastUnaligned(), AllocateRawSlow(), DCHECK_EQ, DCHECK_IMPLIES, in_gc(), is_main_thread(), isolate_heap(), v8::internal::kGC, v8::internal::kTaggedAligned, v8::base::internal::result, and v8::internal::v8_flags.
Referenced by v8::internal::EvacuationAllocator::Allocate().
AllocateRawForceAlignmentForTesting()
AllocationResult v8::internal::MainAllocator::AllocateRawForceAlignmentForTesting (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin)
Definition at line 83 of file main-allocator.cc.
                                                                               {
  size_in_bytes = ALIGN_TO_ALLOCATION_ALIGNMENT(size_in_bytes);
  AllocationResult result =
      AllocateFastAligned(size_in_bytes, nullptr, alignment, origin);
  return V8_UNLIKELY(result.IsFailure())
             ? AllocateRawSlowAligned(size_in_bytes, alignment, origin)
             : result;
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, AllocateFastAligned(), AllocateRawSlowAligned(), v8::base::internal::result, and V8_UNLIKELY.
AllocateRawSlow()
AllocationResult v8::internal::MainAllocator::AllocateRawSlow (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) [private]
Definition at line 195 of file main-allocator.cc.
                                                                         {
  // We are not supposed to allocate in fast c calls.
  CHECK_IMPLIES(is_main_thread(),
                v8_flags.allow_allocation_in_fast_api_call ||
                    !isolate_heap()->isolate()->InFastCCall());
  AllocationResult result =
      alignment != kTaggedAligned
          ? AllocateRawSlowAligned(size_in_bytes, alignment, origin)
          : AllocateRawSlowUnaligned(size_in_bytes, origin);
  return result;
}
References AllocateRawSlowAligned(), AllocateRawSlowUnaligned(), CHECK_IMPLIES, is_main_thread(), isolate_heap(), v8::internal::kTaggedAligned, v8::base::internal::result, and v8::internal::v8_flags.
Referenced by AllocateRaw().
AllocateRawSlowAligned()
AllocationResult v8::internal::MainAllocator::AllocateRawSlowAligned (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin = AllocationOrigin::kRuntime) [private]
Definition at line 225 of file main-allocator.cc.
                                                                               {
  if (!EnsureAllocation(size_in_bytes, alignment, origin)) {
    return AllocationResult::Failure();
  }
  int max_aligned_size = size_in_bytes + Heap::GetMaximumFillToAlign(alignment);
  int aligned_size_in_bytes;
  AllocationResult result = AllocateFastAligned(
      size_in_bytes, &aligned_size_in_bytes, alignment, origin);
  DCHECK_GE(max_aligned_size, aligned_size_in_bytes);
  DCHECK(!result.IsFailure());
  InvokeAllocationObservers(result.ToAddress(), size_in_bytes,
                            aligned_size_in_bytes, max_aligned_size);
  return result;
}
References AllocateFastAligned(), v8::internal::DCHECK(), DCHECK_GE, EnsureAllocation(), v8::internal::AllocationResult::Failure(), v8::internal::Heap::GetMaximumFillToAlign(), InvokeAllocationObservers(), and v8::base::internal::result.
Referenced by AllocateRawForceAlignmentForTesting(), and AllocateRawSlow().
AllocateRawSlowUnaligned()
AllocationResult v8::internal::MainAllocator::AllocateRawSlowUnaligned (int size_in_bytes, AllocationOrigin origin = AllocationOrigin::kRuntime) [private]
Definition at line 210 of file main-allocator.cc.
                                                {
  if (!EnsureAllocation(size_in_bytes, kTaggedAligned, origin)) {
    return AllocationResult::Failure();
  }
  AllocationResult result = AllocateFastUnaligned(size_in_bytes, origin);
  DCHECK(!result.IsFailure());
  InvokeAllocationObservers(result.ToAddress(), size_in_bytes, size_in_bytes,
                            size_in_bytes);
  return result;
}
References AllocateFastUnaligned(), v8::internal::DCHECK(), EnsureAllocation(), v8::internal::AllocationResult::Failure(), InvokeAllocationObservers(), v8::internal::kTaggedAligned, and v8::base::internal::result.
Referenced by AllocateRawSlow().
allocation_counter() [1/2]
AllocationCounter& v8::internal::MainAllocator::allocation_counter () [inline]
Definition at line 202 of file main-allocator.h.
                                          {
    return allocation_counter_.value();
  }
Referenced by AddAllocationObserver(), AdvanceAllocationObservers(), ComputeLimit(), InvokeAllocationObservers(), and RemoveAllocationObserver().
allocation_counter() [2/2]
const AllocationCounter& v8::internal::MainAllocator::allocation_counter () const [inline]
Definition at line 206 of file main-allocator.h.
                                                      {
    return allocation_counter_.value();
  }
allocation_info() [1/2]
LinearAllocationArea& v8::internal::MainAllocator::allocation_info () [inline]
Definition at line 196 of file main-allocator.h.
{ return *allocation_info_; }
Referenced by AdvanceAllocationObservers(), AlignTopForTesting(), AllocateFastAligned(), AllocateFastUnaligned(), ComputeLimit(), v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation(), ExtendLAB(), InvokeAllocationObservers(), MarkLabStartInitialized(), ResetLab(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), and TryFreeLast().
allocation_info() [2/2]
const LinearAllocationArea& v8::internal::MainAllocator::allocation_info () const [inline]
Definition at line 198 of file main-allocator.h.
                                                      {
    return *allocation_info_;
  }
allocation_limit_address()
Address* v8::internal::MainAllocator::allocation_limit_address () const [inline]
Definition at line 183 of file main-allocator.h.
                                            {
    return allocation_info_->limit_address();
  }
Referenced by v8::internal::Heap::OldSpaceAllocationLimitAddress().
allocation_top_address()
Address* v8::internal::MainAllocator::allocation_top_address () const [inline]
Definition at line 178 of file main-allocator.h.
                                          {
    return allocation_info_->top_address();
  }
Referenced by v8::internal::Heap::OldSpaceAllocationTopAddress().
ComputeBlackAllocation()
constexpr MainAllocator::BlackAllocation v8::internal::MainAllocator::ComputeBlackAllocation (MainAllocator::IsNewGeneration is_new_generation) [static], [constexpr], [private]
Definition at line 27 of file main-allocator.cc.
                                                    {
  if (is_new_generation == IsNewGeneration::kYes) {
    return BlackAllocation::kAlwaysDisabled;
  }
  if (v8_flags.sticky_mark_bits) {
    // Allocate black on all non-young spaces.
    return BlackAllocation::kAlwaysEnabled;
  }
  return BlackAllocation::kEnabledOnMarking;
}
References kAlwaysDisabled, kAlwaysEnabled, kEnabledOnMarking, kYes, and v8::internal::v8_flags.
ComputeLimit()
Address v8::internal::MainAllocator::ComputeLimit (Address start, Address end, size_t min_size) const
Definition at line 347 of file main-allocator.cc.
                                                           {
  DCHECK_GE(end - start, min_size);
  // Use the full LAB when allocation observers aren't enabled.
  if (!SupportsAllocationObserver()) return end;
  // LABs with allocation observers are only used outside GC and on the main
  // thread.
  DCHECK(!isolate_heap()->IsInGC());
  DCHECK(is_main_thread());
  if (!isolate_heap()->IsInlineAllocationEnabled()) {
    // LABs are disabled, so we fit the requested area exactly.
    return start + min_size;
  }
  // When LABs are enabled, pick the largest possible LAB size by default.
  size_t step_size = end - start;
  if (isolate_heap()->IsAllocationObserverActive()) {
    // Ensure there are no unaccounted allocations.
    DCHECK_EQ(allocation_info().start(), allocation_info().top());
    size_t step = allocation_counter().NextBytes();
    DCHECK_NE(step, 0);
    // Generated code may allocate inline from the linear allocation area. To
    // make sure we can observe these allocations, we use a lower limit.
    size_t rounded_step = static_cast<size_t>(
        RoundDown(static_cast<int>(step - 1), ObjectAlignment()));
    step_size = std::min(step_size, rounded_step);
  }
  if (v8_flags.stress_marking) {
    step_size = std::min(step_size, static_cast<size_t>(64));
  }
  DCHECK_LE(start + step_size, end);
  return start + std::max(step_size, min_size);
}
References allocation_counter(), allocation_info(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_NE, v8::internal::compiler::end(), is_main_thread(), isolate_heap(), v8::internal::AllocationCounter::NextBytes(), ObjectAlignment(), RoundDown(), start(), SupportsAllocationObserver(), top(), and v8::internal::v8_flags.
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
EnsureAllocation()
bool v8::internal::MainAllocator::EnsureAllocation (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) [private]
Definition at line 313 of file main-allocator.cc.
                                                              {
#ifdef V8_RUNTIME_CALL_STATS
  std::optional<RuntimeCallTimerScope> rcs_scope;
  if (is_main_thread()) {
    rcs_scope.emplace(isolate_heap()->isolate(),
                      RuntimeCallCounterId::kGC_Custom_SlowAllocateRaw);
  }
#endif // V8_RUNTIME_CALL_STATS
  std::optional<VMState<GC>> vmstate;
  if (is_main_thread()) {
    vmstate.emplace(isolate_heap()->isolate());
  }
  return allocator_policy_->EnsureAllocation(size_in_bytes, alignment, origin);
}
References allocator_policy_, is_main_thread(), and isolate_heap().
Referenced by AllocateRawSlowAligned(), AllocateRawSlowUnaligned(), and EnsureAllocationForTesting().
EnsureAllocationForTesting()
bool v8::internal::MainAllocator::EnsureAllocationForTesting (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin)
Definition at line 412 of file main-allocator.cc.
                                                                        {
  return EnsureAllocation(size_in_bytes, alignment, origin);
}
References EnsureAllocation().
extended_limit()
Address v8::internal::MainAllocator::extended_limit () const [inline], [private]
Definition at line 339 of file main-allocator.h.
{ return extended_limit_; }
Referenced by ExtendLAB(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), MoveOriginalTopForward(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
ExtendLAB()
void v8::internal::MainAllocator::ExtendLAB (Address limit)
Definition at line 341 of file main-allocator.cc.
                                           {
  DCHECK(supports_extending_lab());
  DCHECK_LE(limit, extended_limit());
  allocation_info().SetLimit(limit);
}
References allocation_info(), v8::internal::DCHECK(), DCHECK_LE, extended_limit(), limit(), v8::internal::LinearAllocationArea::SetLimit(), and supports_extending_lab().
Referenced by v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
FreeLinearAllocationArea()
void v8::internal::MainAllocator::FreeLinearAllocationArea ()
Definition at line 330 of file main-allocator.cc.
                                             {
  if (!IsLabValid()) return;
#if DEBUG
  Verify();
#endif // DEBUG
  MemoryChunkMetadata::UpdateHighWaterMark(top());
  allocator_policy_->FreeLinearAllocationArea();
}
References allocator_policy_, IsLabValid(), top(), and v8::internal::MemoryChunkMetadata::UpdateHighWaterMark().
Referenced by v8::internal::EvacuationAllocator::Finalize(), and FreeLinearAllocationAreaAndResetFreeList().
FreeLinearAllocationAreaAndResetFreeList()
void v8::internal::MainAllocator::FreeLinearAllocationAreaAndResetFreeList ()
Definition at line 279 of file main-allocator.cc.
                                                             {
  FreeLinearAllocationArea();
  PagedSpaceBase* main_space = space_heap()->paged_space(identity());
  main_space->ResetFreeList();
}
References FreeLinearAllocationArea(), identity(), v8::internal::Heap::paged_space(), v8::internal::PagedSpaceBase::ResetFreeList(), and space_heap().
Referenced by v8::internal::LocalHeap::FreeSharedLinearAllocationAreasAndResetFreeLists().
GetOriginalTopAndLimit()
std::pair<Address, Address> v8::internal::MainAllocator::GetOriginalTopAndLimit () const [inline]
Definition at line 187 of file main-allocator.h.
                                                           {
    return linear_area_original_data().GetTopAndLimit();
  }
Referenced by v8::internal::anonymous_namespace{concurrent-marking.cc}::IsYoungObjectInLab(), v8::internal::MarkCompactCollector::Prepare(), and v8::internal::ConcurrentMarking::RunMajor().
identity()
AllocationSpace v8::internal::MainAllocator::identity () const [private]
Definition at line 428 of file main-allocator.cc.
{ return space_->identity(); }
References v8::internal::BaseSpace::identity(), and space_.
Referenced by v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping(), v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation(), FreeLinearAllocationAreaAndResetFreeList(), ObjectAlignment(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
in_gc()
bool v8::internal::MainAllocator::in_gc () const [inline], [private]
Definition at line 331 of file main-allocator.h.
{ return local_heap_ == nullptr; }
Referenced by AllocateRaw(), v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationArea(), in_gc_for_space(), is_main_thread(), and v8::internal::PagedSpaceAllocatorPolicy::RefillLab().
in_gc_for_space()
bool v8::internal::MainAllocator::in_gc_for_space () const [private]
Definition at line 434 of file main-allocator.cc.
                                          {
  return in_gc() && isolate_heap() == space_heap();
}
References in_gc(), isolate_heap(), and space_heap().
Referenced by v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping().
InvokeAllocationObservers()
void v8::internal::MainAllocator::InvokeAllocationObservers (Address soon_object, size_t size_in_bytes, size_t aligned_size_in_bytes, size_t allocation_size)
Definition at line 148 of file main-allocator.cc.
                                                                      {
  DCHECK_LE(size_in_bytes, aligned_size_in_bytes);
  DCHECK_LE(aligned_size_in_bytes, allocation_size);
  DCHECK(size_in_bytes == aligned_size_in_bytes ||
         aligned_size_in_bytes == allocation_size);
  if (!SupportsAllocationObserver() ||
      !isolate_heap()->IsAllocationObserverActive()) {
    return;
  }
  if (allocation_size >= allocation_counter().NextBytes()) {
    // Only the first object in a LAB should reach the next step.
    DCHECK_EQ(soon_object, allocation_info().start() + aligned_size_in_bytes -
                               size_in_bytes);
    // Right now the LAB only contains that one object.
    DCHECK_EQ(allocation_info().top() + allocation_size - aligned_size_in_bytes,
              allocation_info().limit());
    // Ensure that there is a valid object
    space_heap()->CreateFillerObjectAt(soon_object,
                                       static_cast<int>(size_in_bytes));
#if DEBUG
    // Ensure that allocation_info_ isn't modified during one of the
    // AllocationObserver::Step methods.
    LinearAllocationArea saved_allocation_info = allocation_info();
#endif
    // Run AllocationObserver::Step through the AllocationCounter.
    allocation_counter().InvokeAllocationObservers(soon_object, size_in_bytes,
                                                   allocation_size);
    // Ensure that start/top/limit didn't change.
    DCHECK_EQ(saved_allocation_info.start(), allocation_info().start());
    DCHECK_EQ(saved_allocation_info.top(), allocation_info().top());
    DCHECK_EQ(saved_allocation_info.limit(), allocation_info().limit());
  }
  DCHECK_LT(allocation_info().limit() - allocation_info().start(),
            allocation_counter().NextBytes());
}
References allocation_counter(), allocation_info(), v8::internal::Heap::CreateFillerObjectAt(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::internal::AllocationCounter::InvokeAllocationObservers(), isolate_heap(), v8::internal::LinearAllocationArea::limit(), limit(), space_heap(), v8::internal::LinearAllocationArea::start(), start(), SupportsAllocationObserver(), v8::internal::LinearAllocationArea::top(), and top().
Referenced by AllocateRawSlowAligned(), and AllocateRawSlowUnaligned().
is_main_thread()
bool v8::internal::MainAllocator::is_main_thread () const [private]
Definition at line 430 of file main-allocator.cc.
                                         {
  return !in_gc() && local_heap()->is_main_thread();
}
References in_gc(), v8::internal::LocalHeap::is_main_thread(), and local_heap().
Referenced by AllocateRaw(), AllocateRawSlow(), ComputeLimit(), v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping(), EnsureAllocation(), v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
IsBlackAllocationEnabled()
bool v8::internal::MainAllocator::IsBlackAllocationEnabled () const [private]
Definition at line 95 of file main-allocator.cc.
                                                   {
  if (black_allocation_ == BlackAllocation::kAlwaysDisabled) return false;
  if (black_allocation_ == BlackAllocation::kAlwaysEnabled) return true;
  DCHECK_EQ(black_allocation_, BlackAllocation::kEnabledOnMarking);
  return space_heap()->incremental_marking()->black_allocation();
}
References v8::internal::IncrementalMarking::black_allocation(), black_allocation_, DCHECK_EQ, v8::internal::Heap::incremental_marking(), kAlwaysDisabled, kAlwaysEnabled, kEnabledOnMarking, and space_heap().
Referenced by v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), MarkLinearAllocationAreaBlack(), and v8::internal::PagedSpaceAllocatorPolicy::SetLinearAllocationArea().
IsLabValid()
bool v8::internal::MainAllocator::IsLabValid () const [inline]
Definition at line 253 of file main-allocator.h.
                                    {
    return allocation_info_->top() != kNullAddress;
  }
References v8::internal::kNullAddress.
Referenced by AddAllocationObserver(), v8::internal::ScheduleMinorGCTaskObserver::AddToNewSpace(), v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::EvacuationAllocator::EvacuationAllocator(), v8::internal::MarkCompactCollector::Finish(), FreeLinearAllocationArea(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationArea(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationArea(), v8::internal::PagedNewSpaceAllocatorPolicy::FreeLinearAllocationArea(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), MakeLinearAllocationAreaIterable(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), PauseAllocationObservers(), ResetLab(), and ResumeAllocationObservers().
isolate_heap()
Heap* v8::internal::MainAllocator::isolate_heap () const [inline], [private]
Definition at line 349 of file main-allocator.h.
{ return isolate_heap_; }
Referenced by AdvanceAllocationObservers(), AllocateRaw(), AllocateRawSlow(), ComputeLimit(), EnsureAllocation(), in_gc_for_space(), InvokeAllocationObservers(), and v8::internal::AllocatorPolicy::isolate_heap().
IsPendingAllocation()
bool v8::internal::MainAllocator::IsPendingAllocation (Address object_address)
Definition at line 307 of file main-allocator.cc.
                                                              {
  DCHECK(SupportsPendingAllocation());
  auto [top, limit] = linear_area_original_data().GetTopAndLimitLocked();
  return top && top <= object_address && object_address < limit;
}
References v8::internal::DCHECK(), v8::internal::LinearAreaOriginalData::GetTopAndLimitLocked(), limit(), linear_area_original_data(), SupportsPendingAllocation(), and top().
Referenced by v8::internal::Heap::IsPendingAllocationInternal().
limit()
Address v8::internal::MainAllocator::limit () const [inline]
Definition at line 175 of file main-allocator.h.
{ return allocation_info_->limit(); }
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), ExtendLAB(), v8::internal::PagedNewSpaceAllocatorPolicy::FreeLinearAllocationArea(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), InvokeAllocationObservers(), IsPendingAllocation(), MakeLinearAllocationAreaIterable(), MarkLinearAllocationAreaBlack(), v8::internal::Heap::NewSpaceLimit(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB(), and UnmarkLinearAllocationArea().
linear_area_original_data() [1/2]
LinearAreaOriginalData& v8::internal::MainAllocator::linear_area_original_data () [inline], [private]
Definition at line 310 of file main-allocator.h.
                                                      {
    return linear_area_original_data_.value();
  }
Referenced by IsPendingAllocation(), MoveOriginalTopForward(), and ResetLab().
linear_area_original_data() [2/2]
const LinearAreaOriginalData& v8::internal::MainAllocator::linear_area_original_data () const [inline], [private]
Definition at line 314 of file main-allocator.h.
                                                                  {
    return linear_area_original_data_.value();
  }
local_heap()
LocalHeap* v8::internal::MainAllocator::local_heap () const [inline], [private]
Definition at line 345 of file main-allocator.h.
{ return local_heap_; }
Referenced by v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation(), is_main_thread(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), and v8::internal::PagedSpaceAllocatorPolicy::TryExpandAndAllocate().
MakeLinearAllocationAreaIterable()
void v8::internal::MainAllocator::MakeLinearAllocationAreaIterable ()
Definition at line 245 of file main-allocator.cc.
                                                     {
  if (!IsLabValid()) return;
#if DEBUG
  Verify();
#endif // DEBUG
  Address current_top = top();
  Address current_limit = limit();
  if (current_top != current_limit) {
    space_heap()->CreateFillerObjectAt(
        current_top, static_cast<int>(current_limit - current_top));
  }
}
References v8::internal::Heap::CreateFillerObjectAt(), IsLabValid(), limit(), space_heap(), and top().
MarkLabStartInitialized()
void v8::internal::MainAllocator::MarkLabStartInitialized () [private]
Definition at line 133 of file main-allocator.cc.
                                            {
  allocation_info().ResetStart();
#if DEBUG
  Verify();
#endif
}
References allocation_info(), and v8::internal::LinearAllocationArea::ResetStart().
Referenced by AdvanceAllocationObservers().
MarkLinearAllocationAreaBlack()
void v8::internal::MainAllocator::MarkLinearAllocationAreaBlack ()
Definition at line 260 of file main-allocator.cc.
                                                  {
  DCHECK(IsBlackAllocationEnabled());
  Address current_top = top();
  Address current_limit = limit();
  if (current_top != kNullAddress && current_top != current_limit) {
    PageMetadata::FromAllocationAreaAddress(current_top)
        ->CreateBlackArea(current_top, current_limit);
  }
}
References v8::internal::PageMetadata::CreateBlackArea(), v8::internal::DCHECK(), v8::internal::PageMetadata::FromAllocationAreaAddress(), IsBlackAllocationEnabled(), v8::internal::kNullAddress, limit(), and top().
Referenced by v8::internal::LocalHeap::MarkSharedLinearAllocationAreasBlack().
MoveOriginalTopForward()
void v8::internal::MainAllocator::MoveOriginalTopForward ()
Definition at line 285 of file main-allocator.cc.
                                           {
  DCHECK(SupportsPendingAllocation());
  linear_area_original_data().SetTopAndLimit(top(), extended_limit());
}
References v8::internal::DCHECK(), extended_limit(), linear_area_original_data(), v8::internal::LinearAreaOriginalData::SetTopAndLimit(), SupportsPendingAllocation(), and top().
ObjectAlignment()
int v8::internal::MainAllocator::ObjectAlignment () const [private]
Definition at line 418 of file main-allocator.cc.
                                         {
  if (identity() == CODE_SPACE) {
    return kCodeAlignment;
  } else if (V8_COMPRESS_POINTERS_8GB_BOOL) {
    return kObjectAlignment8GbHeap;
  } else {
    return kTaggedSize;
  }
}
References v8::internal::CODE_SPACE, identity(), v8::internal::kCodeAlignment, v8::internal::kObjectAlignment8GbHeap, v8::internal::kTaggedSize, and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by ComputeLimit().
PauseAllocationObservers()
void v8::internal::MainAllocator::PauseAllocationObservers ()
Definition at line 118 of file main-allocator.cc.
{ DCHECK(!IsLabValid()); }
References v8::internal::DCHECK(), and IsLabValid().
RemoveAllocationObserver()
void v8::internal::MainAllocator::RemoveAllocationObserver (AllocationObserver * observer)
Definition at line 110 of file main-allocator.cc.
                                                                         {
  // AllocationObserver can remove themselves. So we can't CHECK here that no
  // allocation step is in progress. It is also okay if there are existing LABs
  // because removing an allocation observer can only increase the distance to
  // the next step.
  allocation_counter().RemoveAllocationObserver(observer);
}
References allocation_counter(), and v8::internal::AllocationCounter::RemoveAllocationObserver().
Referenced by v8::internal::ScheduleMinorGCTaskObserver::RemoveFromNewSpace(), v8::internal::ScheduleMinorGCTaskObserver::Step(), and v8::internal::Heap::TearDown().
ResetLab()
void v8::internal::MainAllocator::ResetLab (Address start, Address end, Address extended_end)
Definition at line 290 of file main-allocator.cc.
                                                                             {
  DCHECK_LE(start, end);
  DCHECK_LE(end, extended_end);
  DCHECK_IMPLIES(!supports_extending_lab(), end == extended_end);
  if (IsLabValid()) {
    MemoryChunkMetadata::UpdateHighWaterMark(top());
  }
  allocation_info().Reset(start, end);
  extended_limit_ = extended_end;
  if (SupportsPendingAllocation()) {
    linear_area_original_data().SetTopAndLimit(start, extended_end);
  }
}
References allocation_info(), DCHECK_IMPLIES, DCHECK_LE, v8::internal::compiler::end(), extended_limit_, IsLabValid(), linear_area_original_data(), v8::internal::LinearAllocationArea::Reset(), v8::internal::LinearAreaOriginalData::SetTopAndLimit(), start(), supports_extending_lab(), SupportsPendingAllocation(), top(), and v8::internal::MemoryChunkMetadata::UpdateHighWaterMark().
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), and v8::internal::PagedSpaceAllocatorPolicy::SetLinearAllocationArea().
ResumeAllocationObservers()
void v8::internal::MainAllocator::ResumeAllocationObservers ()
Definition at line 120 of file main-allocator.cc.
{ DCHECK(!IsLabValid()); }
References v8::internal::DCHECK(), and IsLabValid().
space_heap()
Heap * v8::internal::MainAllocator::space_heap () const [private]
Definition at line 438 of file main-allocator.cc.
{ return space_->heap(); }
References v8::internal::BaseSpace::heap(), and space_.
Referenced by AlignTopForTesting(), AllocateFastAligned(), AllocateFastUnaligned(), FreeLinearAllocationAreaAndResetFreeList(), in_gc_for_space(), InvokeAllocationObservers(), IsBlackAllocationEnabled(), MakeLinearAllocationAreaIterable(), and v8::internal::AllocatorPolicy::space_heap().
start()
Address v8::internal::MainAllocator::start () const [inline]
Definition at line 173 of file main-allocator.h.
{ return allocation_info_->start(); }
Referenced by AdvanceAllocationObservers(), ComputeLimit(), InvokeAllocationObservers(), and ResetLab().
supports_extending_lab()
bool v8::internal::MainAllocator::supports_extending_lab () const [inline], [private]
Definition at line 341 of file main-allocator.h.
{ return supports_extending_lab_; }
Referenced by ExtendLAB(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), ResetLab(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
SupportsAllocationObserver()
bool v8::internal::MainAllocator::SupportsAllocationObserver () const [inline], [private]
Definition at line 322 of file main-allocator.h.
                                          {
    return allocation_counter_.has_value();
  }
Referenced by AdvanceAllocationObservers(), ComputeLimit(), and InvokeAllocationObservers().
SupportsPendingAllocation()
bool v8::internal::MainAllocator::SupportsPendingAllocation () const [inline], [private]
Definition at line 326 of file main-allocator.h.
                                         {
    return linear_area_original_data_.has_value();
  }
Referenced by IsPendingAllocation(), MoveOriginalTopForward(), and ResetLab().
top()
Address v8::internal::MainAllocator::top () const [inline]
Definition at line 174 of file main-allocator.h.
{ return allocation_info_->top(); }
Referenced by AdvanceAllocationObservers(), AlignTopForTesting(), AllocateFastAligned(), ComputeLimit(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), FreeLinearAllocationArea(), v8::internal::PagedNewSpaceAllocatorPolicy::FreeLinearAllocationArea(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), InvokeAllocationObservers(), IsPendingAllocation(), MakeLinearAllocationAreaIterable(), MarkLinearAllocationAreaBlack(), MoveOriginalTopForward(), v8::internal::Heap::NewSpaceTop(), v8::internal::MarkCompactCollector::Prepare(), ResetLab(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB(), TryFreeLast(), and UnmarkLinearAllocationArea().
TryFreeLast()
bool v8::internal::MainAllocator::TryFreeLast (Address object_address, int object_size) [inline]
Definition at line 88 of file main-allocator-inl.h.
                                                                       {
  if (top() != kNullAddress) {
    return allocation_info().DecrementTopIfAdjacent(object_address,
                                                    object_size);
  }
  return false;
}
References allocation_info(), v8::internal::LinearAllocationArea::DecrementTopIfAdjacent(), v8::internal::kNullAddress, and top().
Referenced by v8::internal::EvacuationAllocator::FreeLastInMainAllocator().
UnmarkLinearAllocationArea()
void v8::internal::MainAllocator::UnmarkLinearAllocationArea ()
Definition at line 270 of file main-allocator.cc.
                                               {
  Address current_top = top();
  Address current_limit = limit();
  if (current_top != kNullAddress && current_top != current_limit) {
    PageMetadata::FromAllocationAreaAddress(current_top)
        ->DestroyBlackArea(current_top, current_limit);
  }
}
References v8::internal::PageMetadata::DestroyBlackArea(), v8::internal::PageMetadata::FromAllocationAreaAddress(), v8::internal::kNullAddress, limit(), and top().
Referenced by v8::internal::LocalHeap::UnmarkSharedLinearAllocationsArea().
Friends And Related Function Documentation
AllocatorPolicy
friend class AllocatorPolicy [friend]
Definition at line 375 of file main-allocator.h.
PagedSpaceAllocatorPolicy
friend class PagedSpaceAllocatorPolicy [friend]
Definition at line 376 of file main-allocator.h.
SemiSpaceNewSpaceAllocatorPolicy
friend class SemiSpaceNewSpaceAllocatorPolicy [friend]
Definition at line 377 of file main-allocator.h.
Member Data Documentation
allocation_counter_
std::optional<AllocationCounter> v8::internal::MainAllocator::allocation_counter_ [private]
Definition at line 360 of file main-allocator.h.
Referenced by MainAllocator().
allocation_info_
LinearAllocationArea* const v8::internal::MainAllocator::allocation_info_ [private]
Definition at line 361 of file main-allocator.h.
allocator_policy_
std::unique_ptr<AllocatorPolicy> v8::internal::MainAllocator::allocator_policy_ [private]
Definition at line 370 of file main-allocator.h.
Referenced by EnsureAllocation(), and FreeLinearAllocationArea().
black_allocation_
const BlackAllocation v8::internal::MainAllocator::black_allocation_ [private]
Definition at line 373 of file main-allocator.h.
Referenced by AllocateFastAligned(), AllocateFastUnaligned(), and IsBlackAllocationEnabled().
extended_limit_
Address v8::internal::MainAllocator::extended_limit_ [private]
Definition at line 367 of file main-allocator.h.
Referenced by ResetLab().
isolate_heap_
Heap* const v8::internal::MainAllocator::isolate_heap_ [private]
Definition at line 357 of file main-allocator.h.
kInGC
constexpr InGCTag v8::internal::MainAllocator::kInGC {} [static], [constexpr]
Definition at line 156 of file main-allocator.h.
Referenced by v8::internal::EvacuationAllocator::EvacuationAllocator().
linear_area_original_data_
std::optional<LinearAreaOriginalData> v8::internal::MainAllocator::linear_area_original_data_ [private]
Definition at line 369 of file main-allocator.h.
Referenced by MainAllocator().
local_heap_
LocalHeap* const v8::internal::MainAllocator::local_heap_ [private]
Definition at line 356 of file main-allocator.h.
Referenced by MainAllocator().
owned_allocation_info_
LinearAllocationArea v8::internal::MainAllocator::owned_allocation_info_ [private]
Definition at line 363 of file main-allocator.h.
space_
SpaceWithLinearArea* const v8::internal::MainAllocator::space_ [private]
Definition at line 358 of file main-allocator.h.
Referenced by identity(), and space_heap().
supports_extending_lab_
const bool v8::internal::MainAllocator::supports_extending_lab_ [private]
Definition at line 372 of file main-allocator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/main-allocator.h
/mnt/V8SourceCode/src/heap/main-allocator-inl.h
/mnt/V8SourceCode/src/heap/main-allocator.cc