v8::internal::compiler::NamedAccessFeedback Class Reference
#include <processed-feedback.h>
Public Member Functions
NamedAccessFeedback (NameRef name, ZoneVector< MapRef > const &maps, FeedbackSlotKind slot_kind, bool has_deprecated_map_without_migration_target=false)
NameRef name () const
ZoneVector< MapRef > const & maps () const
bool has_deprecated_map_without_migration_target () const
Private Attributes
NameRef const name_
ZoneVector< MapRef > const maps_
bool has_deprecated_map_without_migration_target_
Additional Inherited Members
Detailed Description
Definition at line 173 of file processed-feedback.h.
Constructor & Destructor Documentation
NamedAccessFeedback()
v8::internal::compiler::NamedAccessFeedback::NamedAccessFeedback (NameRef name, ZoneVector< MapRef > const & maps, FeedbackSlotKind slot_kind, bool has_deprecated_map_without_migration_target = false)
Definition at line 415 of file js-heap-broker.cc.
    : ProcessedFeedback(kNamedAccess, slot_kind),
      name_(name),
      maps_(maps),
      has_deprecated_map_without_migration_target_(
          has_deprecated_map_without_migration_target) {
  DCHECK(IsLoadICKind(slot_kind) || IsSetNamedICKind(slot_kind) ||
         IsDefineNamedOwnICKind(slot_kind) || IsKeyedLoadICKind(slot_kind) ||
         IsKeyedHasICKind(slot_kind) || IsKeyedStoreICKind(slot_kind) ||
         IsStoreInArrayLiteralICKind(slot_kind) ||
         IsDefineKeyedOwnPropertyInLiteralKind(slot_kind) ||
         IsDefineKeyedOwnICKind(slot_kind));
}
References v8::internal::DCHECK(), v8::internal::IsDefineKeyedOwnICKind(), v8::internal::IsDefineKeyedOwnPropertyInLiteralKind(), v8::internal::IsDefineNamedOwnICKind(), v8::internal::IsKeyedHasICKind(), v8::internal::IsKeyedLoadICKind(), v8::internal::IsKeyedStoreICKind(), v8::internal::IsLoadICKind(), v8::internal::IsSetNamedICKind(), v8::internal::IsStoreInArrayLiteralICKind(), and v8::internal::compiler::ProcessedFeedback::slot_kind().
Member Function Documentation
has_deprecated_map_without_migration_target()
bool v8::internal::compiler::NamedAccessFeedback::has_deprecated_map_without_migration_target () const [inline]
Definition at line 181 of file processed-feedback.h.
                                                           {
    return has_deprecated_map_without_migration_target_;
  }
References has_deprecated_map_without_migration_target_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess().
maps()
ZoneVector<MapRef> const& v8::internal::compiler::NamedAccessFeedback::maps () const [inline]
Definition at line 180 of file processed-feedback.h.
{ return maps_; }
References maps_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), and v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::ShouldUseMegamorphicAccessBuiltin().
name()
NameRef v8::internal::compiler::NamedAccessFeedback::name () const [inline]
Definition at line 179 of file processed-feedback.h.
{ return name_; }
References name_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildGetKeyedProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess().
Member Data Documentation
has_deprecated_map_without_migration_target_
bool v8::internal::compiler::NamedAccessFeedback::has_deprecated_map_without_migration_target_ [private]
Definition at line 188 of file processed-feedback.h.
Referenced by has_deprecated_map_without_migration_target().
maps_
ZoneVector<MapRef> const v8::internal::compiler::NamedAccessFeedback::maps_ [private]
Definition at line 187 of file processed-feedback.h.
Referenced by maps().
name_
NameRef const v8::internal::compiler::NamedAccessFeedback::name_ [private]
Definition at line 186 of file processed-feedback.h.
Referenced by name().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/processed-feedback.h
/mnt/V8SourceCode/src/compiler/js-heap-broker.cc