heap::base::Worklist< EntryType, MinSegmentSize > Class Template Reference
#include <worklist.h>
Classes
class Local
class Segment
Public Member Functions
Worklist ()=default
~Worklist ()
Worklist (const Worklist &)=delete
Worklist & operator= (const Worklist &)=delete
bool IsEmpty () const
size_t Size () const
void Merge (Worklist< EntryType, MinSegmentSize > &other)
void Clear ()
template<typename Callback >
void Update (Callback callback)
template<typename Callback >
void Iterate (Callback callback) const
Static Public Attributes
static constexpr int kMinSegmentSize = MinSegmentSize
Private Member Functions
void Push (Segment *segment)
bool Pop (Segment **segment)
Private Attributes
v8::base::Mutex lock_
Segment * top_ = nullptr
std::atomic< size_t > size_ {0}
Detailed Description
template<typename EntryType, uint16_t MinSegmentSize>
class heap::base::Worklist< EntryType, MinSegmentSize >
Definition at line 57 of file worklist.h.
Constructor & Destructor Documentation
Worklist() [1/2]
template<typename EntryType , uint16_t MinSegmentSize>
heap::base::Worklist< EntryType, MinSegmentSize >::Worklist () [default]
 Worklist()
template<typename EntryType , uint16_t MinSegmentSize>
heap::base::Worklist< EntryType, MinSegmentSize >::~Worklist () [inline]
Definition at line 67 of file worklist.h.
{ CHECK(IsEmpty()); }
References CHECK, and heap::base::Worklist< EntryType, MinSegmentSize >::IsEmpty().
Worklist() [2/2]
template<typename EntryType , uint16_t MinSegmentSize>
heap::base::Worklist< EntryType, MinSegmentSize >::Worklist (const Worklist< EntryType, MinSegmentSize > &) [delete]
Member Function Documentation
Clear()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Clear
Definition at line 139 of file worklist.h.
                                                {
  v8::base::MutexGuard guard(&lock_);
  size_.store(0, std::memory_order_relaxed);
  Segment* current = top_;
  while (current != nullptr) {
    Segment* tmp = current;
    current = current->next();
    Segment::Delete(tmp);
  }
  top_ = nullptr;
}
References heap::base::Worklist< EntryType, MinSegmentSize >::Segment::next().
Referenced by v8::internal::MarkingWorklists::Clear(), cppgc::internal::CompactionWorklists::ClearForTesting(), cppgc::internal::MarkingWorklists::ClearForTesting(), and cppgc::internal::MarkerBase::~MarkerBase().
IsEmpty()
template<typename EntryType , uint16_t MinSegmentSize>
bool heap::base::Worklist< EntryType, MinSegmentSize >::IsEmpty
Definition at line 126 of file worklist.h.
                                                        {
  return Size() == 0;
}
Referenced by v8::internal::ConcurrentMarking::GetMinorMaxConcurrency(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::HasWorkForConcurrentMarking(), v8::internal::ConcurrentMarking::IsWorkLeft(), heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Pop(), cppgc::internal::MarkerBase::ProcessWeakness(), cppgc::internal::MarkerBase::~MarkerBase(), and heap::base::Worklist< EntryType, MinSegmentSize >::~Worklist().
Iterate()
template<typename EntryType , uint16_t MinSegmentSize>
template<typename Callback >
void heap::base::Worklist< EntryType, MinSegmentSize >::Iterate (Callback callback) const
Definition at line 181 of file worklist.h.
                                                                         {
  v8::base::MutexGuard guard(&lock_);
  for (Segment* current = top_; current != nullptr; current = current->next()) {
    current->Iterate(callback);
  }
}
References heap::base::Worklist< EntryType, MinSegmentSize >::Segment::next().
Referenced by v8::internal::ScavengerCollector::ClearYoungEphemerons(), and v8::internal::MarkingWorklists::PrintWorklist().
Merge()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Merge (Worklist< EntryType, MinSegmentSize > & other)
Definition at line 189 of file worklist.h.
                                                {
  Segment* other_top;
  size_t other_size;
  {
    v8::base::MutexGuard guard(&other.lock_);
    if (!other.top_) return;
    other_top = std::exchange(other.top_, nullptr);
    other_size = other.size_.exchange(0, std::memory_order_relaxed);
  }
  // It's safe to iterate through these segments because the top was
  // extracted from `other`.
  Segment* end = other_top;
  while (end->next()) end = end->next();
  {
    v8::base::MutexGuard guard(&lock_);
    size_.fetch_add(other_size, std::memory_order_relaxed);
    end->set_next(top_);
    top_ = other_top;
  }
}
References v8::internal::compiler::end(), heap::base::Worklist< EntryType, MinSegmentSize >::lock_, heap::base::Worklist< EntryType, MinSegmentSize >::size_, and heap::base::Worklist< EntryType, MinSegmentSize >::top_.
operator=()
template<typename EntryType , uint16_t MinSegmentSize>
Worklist& heap::base::Worklist< EntryType, MinSegmentSize >::operator= (const Worklist< EntryType, MinSegmentSize > &) [delete]
Pop()
template<typename EntryType , uint16_t MinSegmentSize>
bool heap::base::Worklist< EntryType, MinSegmentSize >::Pop (Segment ** segment) [private]
Definition at line 115 of file worklist.h.
                                                               {
  v8::base::MutexGuard guard(&lock_);
  if (top_ == nullptr) return false;
  DCHECK_LT(0U, size_);
  size_.fetch_sub(1, std::memory_order_relaxed);
  *segment = top_;
  top_ = top_->next();
  return true;
}
References DCHECK_LT, heap::base::Worklist< EntryType, MinSegmentSize >::Segment::next(), and v8::base::internal::U.
Push()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Push (Segment * segment) [private]
Definition at line 106 of file worklist.h.
                                                               {
  DCHECK(!segment->IsEmpty());
  v8::base::MutexGuard guard(&lock_);
  segment->set_next(top_);
  top_ = segment;
  size_.fetch_add(1, std::memory_order_relaxed);
}
References DCHECK, heap::base::internal::SegmentBase::IsEmpty(), and heap::base::Worklist< EntryType, MinSegmentSize >::Segment::set_next().
Size()
template<typename EntryType , uint16_t MinSegmentSize>
size_t heap::base::Worklist< EntryType, MinSegmentSize >::Size
Definition at line 131 of file worklist.h.
                                                       {
  // It is safe to read |size_| without a lock since this variable is
  // atomic, keeping in mind that threads may not immediately see the new
  // value when it is updated.
  return size_.load(std::memory_order_relaxed);
}
Referenced by v8::internal::ConcurrentMarking::GetMajorMaxConcurrency(), v8::internal::ConcurrentMarking::GetMinorMaxConcurrency(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::WorkSizeForConcurrentMarking().
Update()
template<typename EntryType , uint16_t MinSegmentSize>
template<typename Callback >
void heap::base::Worklist< EntryType, MinSegmentSize >::Update (Callback callback)
Definition at line 153 of file worklist.h.
                                                                  {
  v8::base::MutexGuard guard(&lock_);
  Segment* prev = nullptr;
  Segment* current = top_;
  size_t num_deleted = 0;
  while (current != nullptr) {
    current->Update(callback);
    if (current->IsEmpty()) {
      DCHECK_LT(0U, size_);
      ++num_deleted;
      if (prev == nullptr) {
        top_ = current->next();
      } else {
        prev->set_next(current->next());
      }
      Segment* tmp = current;
      current = current->next();
      Segment::Delete(tmp);
    } else {
      prev = current;
      current = current->next();
    }
  }
  size_.fetch_sub(num_deleted, std::memory_order_relaxed);
}
References DCHECK_LT, heap::base::internal::SegmentBase::IsEmpty(), heap::base::Worklist< EntryType, MinSegmentSize >::Segment::next(), heap::base::Worklist< EntryType, MinSegmentSize >::Segment::set_next(), v8::base::internal::U, and heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Update().
Member Data Documentation
kMinSegmentSize
template<typename EntryType , uint16_t MinSegmentSize>
constexpr int heap::base::Worklist< EntryType, MinSegmentSize >::kMinSegmentSize = MinSegmentSize [static], [constexpr]
Definition at line 64 of file worklist.h.
lock_
template<typename EntryType , uint16_t MinSegmentSize>
v8::base::Mutex heap::base::Worklist< EntryType, MinSegmentSize >::lock_ [mutable], [private]
Definition at line 100 of file worklist.h.
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Merge().
size_
template<typename EntryType , uint16_t MinSegmentSize>
std::atomic<size_t> heap::base::Worklist< EntryType, MinSegmentSize >::size_ {0} [private]
Definition at line 102 of file worklist.h.
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Merge().
top_
template<typename EntryType , uint16_t MinSegmentSize>
Segment* heap::base::Worklist< EntryType, MinSegmentSize >::top_ = nullptr [private]
Definition at line 101 of file worklist.h.
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Merge().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/base/worklist.h