v8_inspector::RemoteObjectIdBase Class Reference
#include <remote-object-id.h>
Public Member Functions
uint64_t isolateId () const
int contextId () const
Protected Member Functions
RemoteObjectIdBase ()
~RemoteObjectIdBase ()=default
bool parseId (const String16 &)
Protected Attributes
uint64_t m_isolateId
int m_injectedScriptId
int m_id
Detailed Description
Definition at line 16 of file remote-object-id.h.
Constructor & Destructor Documentation
RemoteObjectIdBase()
v8_inspector::RemoteObjectIdBase::RemoteObjectIdBase () [protected]
Definition at line 23 of file remote-object-id.cc.
    : m_isolateId(0), m_injectedScriptId(0), m_id(0) {}
 RemoteObjectIdBase()
v8_inspector::RemoteObjectIdBase::~RemoteObjectIdBase () [protected], [default]
Member Function Documentation
contextId()
int v8_inspector::RemoteObjectIdBase::contextId () const [inline]
Definition at line 19 of file remote-object-id.h.
{ return m_injectedScriptId; }
References m_injectedScriptId.
Referenced by v8_inspector::V8InspectorSessionImpl::findInjectedScript().
isolateId()
uint64_t v8_inspector::RemoteObjectIdBase::isolateId () const [inline]
Definition at line 18 of file remote-object-id.h.
{ return m_isolateId; }
References m_isolateId.
Referenced by v8_inspector::V8InspectorSessionImpl::findInjectedScript(), parseId(), v8_inspector::RemoteCallFrameId::serialize(), and v8_inspector::RemoteObjectId::serialize().
parseId()
bool v8_inspector::RemoteObjectIdBase::parseId (const String16 & objectId) [protected]
Definition at line 26 of file remote-object-id.cc.
                                                         {
  const UChar dot = '.';
  size_t firstDotPos = objectId.find(dot);
  if (firstDotPos == String16::kNotFound) return false;
  bool ok = false;
  int64_t isolateId = objectId.substring(0, firstDotPos).toInteger64(&ok);
  if (!ok) return false;
  firstDotPos++;
  size_t secondDotPos = objectId.find(dot, firstDotPos);
  if (secondDotPos == String16::kNotFound) return false;
  int injectedScriptId =
      objectId.substring(firstDotPos, secondDotPos - firstDotPos)
          .toInteger(&ok);
  if (!ok) return false;
  secondDotPos++;
  int id = objectId.substring(secondDotPos).toInteger(&ok);
  if (!ok) return false;
  m_isolateId = static_cast<uint64_t>(isolateId);
  m_injectedScriptId = injectedScriptId;
  m_id = id;
  return true;
}
References v8_inspector::String16::find(), isolateId(), v8_inspector::String16::kNotFound, m_id, m_injectedScriptId, m_isolateId, v8_inspector::String16::substring(), v8_inspector::String16::toInteger(), and v8_inspector::String16::toInteger64().
Member Data Documentation
m_id
int v8_inspector::RemoteObjectIdBase::m_id [protected]
Definition at line 29 of file remote-object-id.h.
Referenced by v8_inspector::RemoteCallFrameId::frameOrdinal(), v8_inspector::RemoteObjectId::id(), and parseId().
m_injectedScriptId
int v8_inspector::RemoteObjectIdBase::m_injectedScriptId [protected]
Definition at line 28 of file remote-object-id.h.
Referenced by contextId(), and parseId().
m_isolateId
uint64_t v8_inspector::RemoteObjectIdBase::m_isolateId [protected]
Definition at line 27 of file remote-object-id.h.
Referenced by isolateId(), and parseId().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/remote-object-id.h
/mnt/V8SourceCode/src/inspector/remote-object-id.cc