v8::internal::compiler::JSHeapBroker Class Reference
#include <js-heap-broker.h>
Classes
class BoilerplateMigrationGuardIfNeeded
class MapUpdaterGuardIfNeeded
class RecursiveMutexGuardIfNeeded
Public Types
enum BrokerMode { kDisabled
, kSerializing
, kSerialized
, kRetired
 }
Public Member Functions
JSHeapBroker (Isolate *isolate, Zone *broker_zone, bool tracing_enabled, CodeKind code_kind)
JSHeapBroker (Isolate *isolate, Zone *broker_zone)
~JSHeapBroker ()
NativeContextRef target_native_context () const
void SetTargetNativeContextRef (DirectHandle< NativeContext > native_context)
void InitializeAndStartSerializing (DirectHandle< NativeContext > native_context)
Isolate * isolate () const
PtrComprCageBase cage_base () const
Zone * zone () const
bool tracing_enabled () const
NexusConfig feedback_nexus_config () const
BrokerMode mode () const
void StopSerializing ()
void Retire ()
bool SerializingAllowed () const
void AttachLocalIsolate (OptimizedCompilationInfo *info, LocalIsolate *local_isolate)
void DetachLocalIsolate (OptimizedCompilationInfo *info)
void AttachLocalIsolateForMaglev (maglev::MaglevCompilationInfo *info, LocalIsolate *local_isolate)
void DetachLocalIsolateForMaglev (maglev::MaglevCompilationInfo *info)
template<typename CompilationInfoT >
void AttachCompilationInfo (CompilationInfoT *info)
bool StackHasOverflowed () const
DirectHandle< Object > GetRootHandle (Tagged< Object > object)
ObjectData * GetOrCreateData (Handle< Object > object, GetOrCreateDataFlags flags={})
template<typename T >
ObjectData * GetOrCreateData (Tagged< T > object, GetOrCreateDataFlags flags={})
ObjectData * TryGetOrCreateData (Handle< Object > object, GetOrCreateDataFlags flags={})
template<typename T >
ObjectData * TryGetOrCreateData (Tagged< T > object, GetOrCreateDataFlags flags={})
bool IsArrayOrObjectPrototype (JSObjectRef object) const
bool IsArrayOrObjectPrototype (Handle< JSObject > object) const
bool HasFeedback (FeedbackSource const &source) const
void SetFeedback (FeedbackSource const &source, ProcessedFeedback const *feedback)
FeedbackSlotKind GetFeedbackSlotKind (FeedbackSource const &source) const
ElementAccessFeedback const & ProcessFeedbackMapsForElementAccess (ZoneVector< MapRef > &maps, KeyedAccessMode const &keyed_mode, FeedbackSlotKind slot_kind)
ElementAccessFeedback const & ProcessFeedbackMapsForKeyedPropertyAccess (ZoneVector< MapRef > &maps, KeyedAccessMode const &keyed_mode, FeedbackSlotKind slot_kind)
BinaryOperationHint GetFeedbackForBinaryOperation (FeedbackSource const &source)
CompareOperationHint GetFeedbackForCompareOperation (FeedbackSource const &source)
ForInHint GetFeedbackForForIn (FeedbackSource const &source)
ProcessedFeedback const & GetFeedbackForCall (FeedbackSource const &source)
ProcessedFeedback const & GetFeedbackForGlobalAccess (FeedbackSource const &source)
ProcessedFeedback const & GetFeedbackForInstanceOf (FeedbackSource const &source)
TypeOfFeedback::Result GetFeedbackForTypeOf (FeedbackSource const &source)
ProcessedFeedback const & GetFeedbackForArrayOrObjectLiteral (FeedbackSource const &source)
ProcessedFeedback const & GetFeedbackForRegExpLiteral (FeedbackSource const &source)
ProcessedFeedback const & GetFeedbackForTemplateObject (FeedbackSource const &source)
ProcessedFeedback const & GetFeedbackForPropertyAccess (FeedbackSource const &source, AccessMode mode, OptionalNameRef static_name)
ProcessedFeedback const & ProcessFeedbackForBinaryOperation (FeedbackSource const &source)
ProcessedFeedback const & ProcessFeedbackForCompareOperation (FeedbackSource const &source)
ProcessedFeedback const & ProcessFeedbackForForIn (FeedbackSource const &source)
ProcessedFeedback const & ProcessFeedbackForTypeOf (FeedbackSource const &source)
bool FeedbackIsInsufficient (FeedbackSource const &source) const
OptionalNameRef GetNameFeedback (FeedbackNexus const &nexus)
PropertyAccessInfo GetPropertyAccessInfo (MapRef map, NameRef name, AccessMode access_mode)
StringRef GetTypedArrayStringTag (ElementsKind kind)
bool IsMainThread () const
LocalIsolate * local_isolate () const
LocalIsolate * local_isolate_or_isolate () const
std::optional< RootIndex > FindRootIndex (HeapObjectRef object)
template<typename T >
Handle< T > CanonicalPersistentHandle (Tagged< T > object)
template<typename T >
Handle< T > CanonicalPersistentHandle (Handle< T > object)
template<typename T >
bool IsCanonicalHandle (Handle< T > handle)
std::string Trace () const
void IncrementTracingIndentation ()
void DecrementTracingIndentation ()
bool ObjectMayBeUninitialized (DirectHandle< Object > object) const
bool ObjectMayBeUninitialized (Tagged< Object > object) const
bool ObjectMayBeUninitialized (Tagged< HeapObject > object) const
void set_dependencies (CompilationDependencies *dependencies)
CompilationDependencies * dependencies () const
Private Member Functions
ProcessedFeedback const & GetFeedback (FeedbackSource const &source) const
const ProcessedFeedback & NewInsufficientFeedback (FeedbackSlotKind kind) const
ProcessedFeedback const & ReadFeedbackForArrayOrObjectLiteral (FeedbackSource const &source)
ProcessedFeedback const & ReadFeedbackForBinaryOperation (FeedbackSource const &source) const
ProcessedFeedback const & ReadFeedbackForTypeOf (FeedbackSource const &source) const
ProcessedFeedback const & ReadFeedbackForCall (FeedbackSource const &source)
ProcessedFeedback const & ReadFeedbackForCompareOperation (FeedbackSource const &source) const
ProcessedFeedback const & ReadFeedbackForForIn (FeedbackSource const &source) const
ProcessedFeedback const & ReadFeedbackForGlobalAccess (JSHeapBroker *broker, FeedbackSource const &source)
ProcessedFeedback const & ReadFeedbackForInstanceOf (FeedbackSource const &source)
ProcessedFeedback const & ReadFeedbackForPropertyAccess (FeedbackSource const &source, AccessMode mode, OptionalNameRef static_name)
ProcessedFeedback const & ReadFeedbackForRegExpLiteral (FeedbackSource const &source)
ProcessedFeedback const & ReadFeedbackForTemplateObject (FeedbackSource const &source)
void set_persistent_handles (std::unique_ptr< PersistentHandles > persistent_handles)
std::unique_ptr< PersistentHandles > DetachPersistentHandles ()
void set_canonical_handles (CanonicalHandlesMap *canonical_handles)
Private Attributes
Isolate *const isolate_
Zone *const zone_
OptionalNativeContextRef target_native_context_
RefsMap * refs_
RootIndexMap root_index_map_
BrokerMode mode_ = kDisabled
bool const tracing_enabled_
CodeKind const code_kind_
std::unique_ptr< PersistentHandles > ph_
LocalIsolate * local_isolate_ = nullptr
CanonicalHandlesMap * canonical_handles_
unsigned trace_indentation_ = 0
ZoneUnorderedMap< FeedbackSource, ProcessedFeedback const *, FeedbackSource::Hash, FeedbackSource::Equal > feedback_
ZoneUnorderedMap< PropertyAccessTarget, PropertyAccessInfo, PropertyAccessTarget::Hash, PropertyAccessTarget::Equal > property_access_infos_
CompilationDependencies * dependencies_ = nullptr
int map_updater_mutex_depth_ = 0
int boilerplate_migration_mutex_depth_ = 0
Static Private Attributes
static constexpr uint32_t kMinimalRefsBucketCount = 8
static constexpr uint32_t kInitialRefsBucketCount = 16
Friends
class JSHeapBrokerScopeForTesting
class HeapObjectRef
class ObjectRef
class ObjectData
class PropertyCellData
Detailed Description
Definition at line 95 of file js-heap-broker.h.
Member Enumeration Documentation
BrokerMode
enum v8::internal::compiler::JSHeapBroker::BrokerMode
Enumerator
kDisabled
kSerializing
kSerialized
kRetired
Definition at line 139 of file js-heap-broker.h.
{ kDisabled, kSerializing, kSerialized, kRetired };
Constructor & Destructor Documentation
JSHeapBroker() [1/2]
v8::internal::compiler::JSHeapBroker::JSHeapBroker (Isolate * isolate, Zone * broker_zone, bool tracing_enabled, CodeKind code_kind)
Definition at line 35 of file js-heap-broker.cc.
    : isolate_(isolate),
#if V8_COMPRESS_POINTERS
      cage_base_(isolate),
#endif // V8_COMPRESS_POINTERS
      zone_(broker_zone),
      // Note that this initialization of {refs_} with the minimal initial
      // capacity is redundant in the normal use case (concurrent compilation
      // enabled, standard objects to be serialized), as the map is going to be
      // replaced immediately with a larger-capacity one. It doesn't seem to
      // affect the performance in a noticeable way though.
      refs_(zone()->New<RefsMap>(kMinimalRefsBucketCount, AddressMatcher(),
                                 zone())),
      root_index_map_(isolate),
      tracing_enabled_(tracing_enabled),
      code_kind_(code_kind),
      feedback_(zone()),
      property_access_infos_(zone()) {
  TRACE(this, "Constructing heap broker");
}
References v8::internal::TRACE().
JSHeapBroker() [2/2]
v8::internal::compiler::JSHeapBroker::JSHeapBroker (Isolate * isolate, Zone * broker_zone) [inline]
Definition at line 102 of file js-heap-broker.h.
      : JSHeapBroker(isolate, broker_zone, v8_flags.trace_heap_broker,
                     CodeKind::TURBOFAN_JS) {}
 JSHeapBroker()
v8::internal::compiler::JSHeapBroker::~JSHeapBroker ()
Definition at line 57 of file js-heap-broker.cc.
{ DCHECK_NULL(local_isolate_); }
References DCHECK_NULL, and local_isolate_.
Member Function Documentation
AttachCompilationInfo()
template<typename CompilationInfoT >
void v8::internal::compiler::JSHeapBroker::AttachCompilationInfo (CompilationInfoT * info) [inline]
Definition at line 169 of file js-heap-broker.h.
                                                     {
    set_canonical_handles(info->canonical_handles());
  }
Referenced by v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo().
AttachLocalIsolate()
void v8::internal::compiler::JSHeapBroker::AttachLocalIsolate (OptimizedCompilationInfo * info, LocalIsolate * local_isolate)
Definition at line 84 of file js-heap-broker.cc.
                                                                   {
  DCHECK_NULL(local_isolate_);
  local_isolate_ = local_isolate;
  DCHECK_NOT_NULL(local_isolate_);
  local_isolate_->heap()->AttachPersistentHandles(
      info->DetachPersistentHandles());
}
References v8::internal::LocalHeap::AttachPersistentHandles(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::OptimizedCompilationInfo::DetachPersistentHandles(), v8::internal::LocalIsolate::heap(), local_isolate(), and local_isolate_.
AttachLocalIsolateForMaglev()
void v8::internal::compiler::JSHeapBroker::AttachLocalIsolateForMaglev (maglev::MaglevCompilationInfo * info, LocalIsolate * local_isolate)
Definition at line 33 of file maglev-concurrent-dispatcher.cc.
                                                                    {
  DCHECK_NULL(local_isolate_);
  local_isolate_ = local_isolate;
  DCHECK_NOT_NULL(local_isolate_);
  local_isolate_->heap()->AttachPersistentHandles(
      info->DetachPersistentHandles());
}
References v8::internal::LocalHeap::AttachPersistentHandles(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::maglev::MaglevCompilationInfo::DetachPersistentHandles(), v8::internal::LocalIsolate::heap(), local_isolate(), and local_isolate_.
cage_base()
PtrComprCageBase v8::internal::compiler::JSHeapBroker::cage_base () const [inline]
Definition at line 122 of file js-heap-broker.h.
                                     {
#if V8_COMPRESS_POINTERS
    return cage_base_;
#else
    return PtrComprCageBase{};
#endif // V8_COMPRESS_POINTERS
  }
CanonicalPersistentHandle() [1/2]
template<typename T >
Handle<T> v8::internal::compiler::JSHeapBroker::CanonicalPersistentHandle (Handle< T > object) [inline]
Definition at line 325 of file js-heap-broker.h.
                                                        {
    if (object.is_null()) return object; // Can't deref a null handle.
    return CanonicalPersistentHandle<T>(*object);
  }
CanonicalPersistentHandle() [2/2]
template<typename T >
Handle<T> v8::internal::compiler::JSHeapBroker::CanonicalPersistentHandle (Tagged< T > object) [inline]
Definition at line 292 of file js-heap-broker.h.
                                                        {
    DCHECK_NOT_NULL(canonical_handles_);
    if (Tagged<HeapObject> heap_object;
        TryCast<HeapObject>(object, &heap_object)) {
      RootIndex root_index;
      // The root index map only contains immortal, immutable objects; it never
      // contains any instances of type JSObject, since JSObjects must exist
      // within a NativeContext, and NativeContexts can be created and
      // destroyed. Thus, we can skip the lookup in the root index map for those
      // values and save a little time.
      if constexpr (std::is_convertible_v<T, JSObject> ||
                    std::is_convertible_v<T, Context>) {
        DCHECK(!root_index_map_.Lookup(heap_object, &root_index));
      } else if (root_index_map_.Lookup(heap_object, &root_index)) {
        return Handle<T>(isolate_->root_handle(root_index).location());
      }
    }
    auto find_result = canonical_handles_->FindOrInsert(object);
    if (find_result.already_exists) return Handle<T>(*find_result.entry);
    // Allocate new PersistentHandle if one wasn't created before.
    if (local_isolate()) {
      *find_result.entry =
          local_isolate()->heap()->NewPersistentHandle(object).location();
    } else {
      DCHECK(PersistentHandlesScope::IsActive(isolate()));
      *find_result.entry = IndirectHandle<T>(object, isolate()).location();
    }
    return Handle<T>(*find_result.entry);
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::PersistentHandlesScope::IsActive(), and v8::internal::HandleBase::location().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeAccessorDescriptorAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::JSNativeContextSpecialization::Concatenate(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt().
DecrementTracingIndentation()
void v8::internal::compiler::JSHeapBroker::DecrementTracingIndentation ()
Definition at line 33 of file js-heap-broker.cc.
{ --trace_indentation_; }
References trace_indentation_.
dependencies()
CompilationDependencies* v8::internal::compiler::JSHeapBroker::dependencies () const [inline]
Definition at line 396 of file js-heap-broker.h.
                                                {
    DCHECK_NOT_NULL(dependencies_);
    return dependencies_;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap(), v8::internal::maglev::MaglevGraphBuilder::CanTreatHoleAsUndefined(), v8::internal::compiler::AccessInfoFactory::dependencies(), v8::internal::compiler::JSCallReducer::dependencies(), v8::internal::compiler::JSCreateLowering::dependencies(), v8::internal::compiler::JSInliningHeuristic::dependencies(), v8::internal::compiler::JSTypedLowering::dependencies(), v8::internal::compiler::PropertyAccessBuilder::dependencies(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DependOnNoUndetectableObjectsProtector(), v8::internal::maglev::MaglevCompiler::GenerateCode(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MapLoadCanBeConstantFolded(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyGetterCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot(), and v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot().
DetachLocalIsolate()
void v8::internal::compiler::JSHeapBroker::DetachLocalIsolate (OptimizedCompilationInfo * info)
Definition at line 93 of file js-heap-broker.cc.
                                                                    {
  DCHECK_NULL(ph_);
  DCHECK_NOT_NULL(local_isolate_);
  std::unique_ptr<PersistentHandles> ph =
      local_isolate_->heap()->DetachPersistentHandles();
  local_isolate_ = nullptr;
  info->set_persistent_handles(std::move(ph));
}
References DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::LocalHeap::DetachPersistentHandles(), v8::internal::LocalIsolate::heap(), local_isolate_, ph_, and v8::internal::OptimizedCompilationInfo::set_persistent_handles().
DetachLocalIsolateForMaglev()
void v8::internal::compiler::JSHeapBroker::DetachLocalIsolateForMaglev (maglev::MaglevCompilationInfo * info)
Definition at line 42 of file maglev-concurrent-dispatcher.cc.
                                       {
  DCHECK_NULL(ph_);
  DCHECK_NOT_NULL(local_isolate_);
  std::unique_ptr<PersistentHandles> ph =
      local_isolate_->heap()->DetachPersistentHandles();
  local_isolate_ = nullptr;
  info->set_persistent_handles(std::move(ph));
}
References DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::LocalHeap::DetachPersistentHandles(), v8::internal::LocalIsolate::heap(), local_isolate_, ph_, and v8::internal::maglev::MaglevCompilationInfo::set_persistent_handles().
DetachPersistentHandles()
std::unique_ptr<PersistentHandles> v8::internal::compiler::JSHeapBroker::DetachPersistentHandles () [inline], [private]
Definition at line 446 of file js-heap-broker.h.
                                                             {
    DCHECK_NOT_NULL(ph_);
    return std::move(ph_);
  }
References DCHECK_NOT_NULL.
feedback_nexus_config()
NexusConfig v8::internal::compiler::JSHeapBroker::feedback_nexus_config () const [inline]
Definition at line 133 of file js-heap-broker.h.
                                            {
    return IsMainThread() ? NexusConfig::FromMainThread(isolate())
                          : NexusConfig::FromBackgroundThread(
                                isolate(), local_isolate()->heap());
  }
References v8::internal::NexusConfig::FromBackgroundThread(), v8::internal::NexusConfig::FromMainThread(), and heap().
Referenced by FeedbackIsInsufficient(), GetFeedbackSlotKind(), ReadFeedbackForArrayOrObjectLiteral(), ReadFeedbackForBinaryOperation(), ReadFeedbackForCall(), ReadFeedbackForCompareOperation(), ReadFeedbackForForIn(), ReadFeedbackForGlobalAccess(), ReadFeedbackForInstanceOf(), ReadFeedbackForPropertyAccess(), ReadFeedbackForRegExpLiteral(), ReadFeedbackForTemplateObject(), and ReadFeedbackForTypeOf().
FeedbackIsInsufficient()
bool v8::internal::compiler::JSHeapBroker::FeedbackIsInsufficient (FeedbackSource const & source) const
Definition at line 458 of file js-heap-broker.cc.
                                                                            {
  if (HasFeedback(source)) return GetFeedback(source).IsInsufficient();
  return FeedbackNexus(source.vector, source.slot, feedback_nexus_config())
      .IsUninitialized();
}
References feedback_nexus_config(), GetFeedback(), HasFeedback(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::compiler::FeedbackSource::slot, and v8::internal::compiler::FeedbackSource::vector.
FindRootIndex()
std::optional<RootIndex> v8::internal::compiler::JSHeapBroker::FindRootIndex (HeapObjectRef object) [inline]
Definition at line 274 of file js-heap-broker.h.
                                                             {
    // No root constant is a JSReceiver.
    if (object.IsJSReceiver()) return {};
    RootIndex root_index;
    if (root_index_map_.Lookup(*object.object(), &root_index)) {
      return root_index;
    }
    return {};
  }
GetFeedback()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::GetFeedback (FeedbackSource const & source) const [private]
Definition at line 443 of file js-heap-broker.cc.
                                        {
  DCHECK(source.IsValid());
  auto it = feedback_.find(source);
  CHECK_NE(it, feedback_.end());
  return *it->second;
}
References CHECK_NE, v8::internal::DCHECK(), feedback_, and v8::internal::compiler::FeedbackSource::IsValid().
Referenced by FeedbackIsInsufficient(), GetFeedbackForArrayOrObjectLiteral(), GetFeedbackForCall(), GetFeedbackForGlobalAccess(), GetFeedbackForInstanceOf(), GetFeedbackForPropertyAccess(), GetFeedbackForRegExpLiteral(), GetFeedbackForTemplateObject(), GetFeedbackSlotKind(), ProcessFeedbackForBinaryOperation(), ProcessFeedbackForCompareOperation(), ProcessFeedbackForForIn(), and ProcessFeedbackForTypeOf().
GetFeedbackForArrayOrObjectLiteral()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::GetFeedbackForArrayOrObjectLiteral (FeedbackSource const & source)
Definition at line 747 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback =
      ReadFeedbackForArrayOrObjectLiteral(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForArrayOrObjectLiteral(), and SetFeedback().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject().
GetFeedbackForBinaryOperation()
BinaryOperationHint v8::internal::compiler::JSHeapBroker::GetFeedbackForBinaryOperation (FeedbackSource const & source)
Definition at line 719 of file js-heap-broker.cc.
                                  {
  ProcessedFeedback const& feedback = ProcessFeedbackForBinaryOperation(source);
  return feedback.IsInsufficient() ? BinaryOperationHint::kNone
                                   : feedback.AsBinaryOperation().value();
}
References v8::internal::compiler::ProcessedFeedback::AsBinaryOperation(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::kNone, ProcessFeedbackForBinaryOperation(), and v8::internal::compiler::SingleValueFeedback< T, K >::value().
Referenced by v8::internal::compiler::JSTypeHintLowering::GetBinaryOperationHint(), and v8::internal::compiler::JSBinopReduction::GetBinaryOperationHint().
GetFeedbackForCall()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::GetFeedbackForCall (FeedbackSource const & source)
Definition at line 822 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForCall(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForCall(), and SetFeedback().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
GetFeedbackForCompareOperation()
CompareOperationHint v8::internal::compiler::JSHeapBroker::GetFeedbackForCompareOperation (FeedbackSource const & source)
Definition at line 733 of file js-heap-broker.cc.
                                  {
  ProcessedFeedback const& feedback =
      ProcessFeedbackForCompareOperation(source);
  return feedback.IsInsufficient() ? CompareOperationHint::kNone
                                   : feedback.AsCompareOperation().value();
}
References v8::internal::compiler::ProcessedFeedback::AsCompareOperation(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::kNone, ProcessFeedbackForCompareOperation(), and v8::internal::compiler::SingleValueFeedback< T, K >::value().
Referenced by v8::internal::compiler::JSTypeHintLowering::GetCompareOperationHint(), and v8::internal::compiler::JSBinopReduction::GetCompareOperationHint().
GetFeedbackForForIn()
ForInHint v8::internal::compiler::JSHeapBroker::GetFeedbackForForIn (FeedbackSource const & source)
Definition at line 741 of file js-heap-broker.cc.
                                                                        {
  ProcessedFeedback const& feedback = ProcessFeedbackForForIn(source);
  return feedback.IsInsufficient() ? ForInHint::kNone
                                   : feedback.AsForIn().value();
}
References v8::internal::compiler::ProcessedFeedback::AsForIn(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::kNone, ProcessFeedbackForForIn(), and v8::internal::compiler::SingleValueFeedback< T, K >::value().
GetFeedbackForGlobalAccess()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::GetFeedbackForGlobalAccess (FeedbackSource const & source)
Definition at line 830 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForGlobalAccess(this, source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForGlobalAccess(), and SetFeedback().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal().
GetFeedbackForInstanceOf()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::GetFeedbackForInstanceOf (FeedbackSource const & source)
Definition at line 814 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForInstanceOf(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForInstanceOf(), and SetFeedback().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf().
GetFeedbackForPropertyAccess()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::GetFeedbackForPropertyAccess (FeedbackSource const & source, AccessMode mode, OptionalNameRef static_name)
Definition at line 804 of file js-heap-broker.cc.
                                 {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback =
      ReadFeedbackForPropertyAccess(source, mode, static_name);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), mode(), ReadFeedbackForPropertyAccess(), and SetFeedback().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), and v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess().
GetFeedbackForRegExpLiteral()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::GetFeedbackForRegExpLiteral (FeedbackSource const & source)
Definition at line 756 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForRegExpLiteral(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForRegExpLiteral(), and SetFeedback().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp().
GetFeedbackForTemplateObject()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::GetFeedbackForTemplateObject (FeedbackSource const & source)
Definition at line 764 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForTemplateObject(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForTemplateObject(), and SetFeedback().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSGetTemplateObject().
GetFeedbackForTypeOf()
TypeOfFeedback::Result v8::internal::compiler::JSHeapBroker::GetFeedbackForTypeOf (FeedbackSource const & source)
Definition at line 726 of file js-heap-broker.cc.
                                  {
  ProcessedFeedback const& feedback = ProcessFeedbackForTypeOf(source);
  return feedback.IsInsufficient() ? TypeOfFeedback::kNone
                                   : feedback.AsTypeOf().value();
}
References v8::internal::compiler::ProcessedFeedback::AsTypeOf(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::TypeOfFeedback::kNone, ProcessFeedbackForTypeOf(), and v8::internal::compiler::SingleValueFeedback< T, K >::value().
Referenced by v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation().
GetFeedbackSlotKind()
FeedbackSlotKind v8::internal::compiler::JSHeapBroker::GetFeedbackSlotKind (FeedbackSource const & source) const
Definition at line 451 of file js-heap-broker.cc.
                                        {
  if (HasFeedback(source)) return GetFeedback(source).slot_kind();
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  return nexus.kind();
}
References feedback_nexus_config(), GetFeedback(), HasFeedback(), v8::internal::FeedbackNexus::kind(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::ProcessedFeedback::slot_kind(), and v8::internal::compiler::FeedbackSource::vector.
GetNameFeedback()
OptionalNameRef v8::internal::compiler::JSHeapBroker::GetNameFeedback (FeedbackNexus const & nexus)
Definition at line 928 of file js-heap-broker.cc.
                                                                        {
  Tagged<Name> raw_name = nexus.GetName();
  if (raw_name.is_null()) return std::nullopt;
  return MakeRefAssumeMemoryFence(this, raw_name);
}
References v8::internal::FeedbackNexus::GetName(), v8::internal::Tagged< HeapObject >::is_null(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by ReadFeedbackForPropertyAccess().
GetOrCreateData() [1/2]
ObjectData * v8::internal::compiler::JSHeapBroker::GetOrCreateData (Handle< Object > object, GetOrCreateDataFlags flags = {})
Definition at line 144 of file js-heap-broker.cc.
                                                                      {
  ObjectData* return_value = TryGetOrCreateData(object, flags | kCrashOnError);
  DCHECK_NOT_NULL(return_value);
  return return_value;
}
References DCHECK_NOT_NULL, v8::internal::flags, v8::internal::compiler::kCrashOnError, and TryGetOrCreateData().
GetOrCreateData() [2/2]
template<typename T >
ObjectData* v8::internal::compiler::JSHeapBroker::GetOrCreateData (Tagged< T > object, GetOrCreateDataFlags flags = {}) [inline]
Definition at line 186 of file js-heap-broker.h.
                                                           {}) {
    return GetOrCreateData(CanonicalPersistentHandle(object), flags);
  }
GetPropertyAccessInfo()
PropertyAccessInfo v8::internal::compiler::JSHeapBroker::GetPropertyAccessInfo (MapRef map, NameRef name, AccessMode access_mode)
Definition at line 934 of file js-heap-broker.cc.
                                                                               {
  DCHECK_NOT_NULL(dependencies_);
  PropertyAccessTarget target({map, name, access_mode});
  auto it = property_access_infos_.find(target);
  if (it != property_access_infos_.end()) return it->second;
  AccessInfoFactory factory(this, zone());
  PropertyAccessInfo access_info =
      factory.ComputePropertyAccessInfo(map, name, access_mode);
  TRACE(this, "Storing PropertyAccessInfo for "
                  << access_mode << " of property " << name << " on map "
                  << map);
  property_access_infos_.insert({target, access_info});
  return access_info;
}
References v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), DCHECK_NOT_NULL, dependencies_, v8::internal::name, property_access_infos_, v8::internal::TRACE(), and zone().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess().
GetRootHandle()
DirectHandle<Object> v8::internal::compiler::JSHeapBroker::GetRootHandle (Tagged< Object > object)
GetTypedArrayStringTag()
StringRef v8::internal::compiler::JSHeapBroker::GetTypedArrayStringTag (ElementsKind kind)
Definition at line 120 of file js-heap-broker.cc.
                                                                {
  DCHECK(IsTypedArrayOrRabGsabTypedArrayElementsKind(kind));
  switch (kind) {
#define TYPED_ARRAY_STRING_TAG(Type, type, TYPE, ctype) \
  case ElementsKind::TYPE##_ELEMENTS: \
    return Type##Array_string();
    TYPED_ARRAYS(TYPED_ARRAY_STRING_TAG)
    RAB_GSAB_TYPED_ARRAYS_WITH_TYPED_ARRAY_TYPE(TYPED_ARRAY_STRING_TAG)
#undef TYPED_ARRAY_STRING_TAG
    default:
      UNREACHABLE();
  }
}
References v8::internal::DCHECK(), v8::internal::IsTypedArrayOrRabGsabTypedArrayElementsKind(), RAB_GSAB_TYPED_ARRAYS_WITH_TYPED_ARRAY_TYPE, TYPED_ARRAY_STRING_TAG, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
HasFeedback()
bool v8::internal::compiler::JSHeapBroker::HasFeedback (FeedbackSource const & source) const
Definition at line 438 of file js-heap-broker.cc.
                                                                 {
  DCHECK(source.IsValid());
  return feedback_.find(source) != feedback_.end();
}
References v8::internal::DCHECK(), feedback_, and v8::internal::compiler::FeedbackSource::IsValid().
Referenced by FeedbackIsInsufficient(), GetFeedbackForArrayOrObjectLiteral(), GetFeedbackForCall(), GetFeedbackForGlobalAccess(), GetFeedbackForInstanceOf(), GetFeedbackForPropertyAccess(), GetFeedbackForRegExpLiteral(), GetFeedbackForTemplateObject(), GetFeedbackSlotKind(), ProcessFeedbackForBinaryOperation(), ProcessFeedbackForCompareOperation(), ProcessFeedbackForForIn(), and ProcessFeedbackForTypeOf().
IncrementTracingIndentation()
void v8::internal::compiler::JSHeapBroker::IncrementTracingIndentation ()
Definition at line 31 of file js-heap-broker.cc.
{ ++trace_indentation_; }
References trace_indentation_.
InitializeAndStartSerializing()
void v8::internal::compiler::JSHeapBroker::InitializeAndStartSerializing (DirectHandle< NativeContext > native_context)
Definition at line 1015 of file heap-refs.cc.
                                                       {
  TraceScope tracer(this, "JSHeapBroker::InitializeAndStartSerializing");
  CHECK_EQ(mode_, kDisabled);
  mode_ = kSerializing;
  // Throw away the dummy data that we created while disabled.
  feedback_.clear();
  refs_->Clear();
  refs_ =
      zone()->New<RefsMap>(kInitialRefsBucketCount, AddressMatcher(), zone());
  SetTargetNativeContextRef(target_native_context);
}
References CHECK_EQ, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Clear(), feedback_, kDisabled, kInitialRefsBucketCount, kSerializing, mode_, v8::internal::Zone::New(), refs_, SetTargetNativeContextRef(), target_native_context(), and zone().
Referenced by v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo().
IsArrayOrObjectPrototype() [1/2]
bool v8::internal::compiler::JSHeapBroker::IsArrayOrObjectPrototype (Handle< JSObject > object) const
Definition at line 138 of file js-heap-broker.cc.
                                                                         {
  return isolate()->IsInCreationContext(
             *object, Context::INITIAL_ARRAY_PROTOTYPE_INDEX) ||
         object->map(isolate_)->instance_type() == JS_OBJECT_PROTOTYPE_TYPE;
}
References v8::internal::Isolate::IsInCreationContext(), isolate(), and isolate_.
IsArrayOrObjectPrototype() [2/2]
bool v8::internal::compiler::JSHeapBroker::IsArrayOrObjectPrototype (JSObjectRef object) const
Definition at line 134 of file js-heap-broker.cc.
                                                                    {
  return IsArrayOrObjectPrototype(object.object());
}
IsCanonicalHandle()
template<typename T >
bool v8::internal::compiler::JSHeapBroker::IsCanonicalHandle (Handle< T > handle) [inline]
Definition at line 332 of file js-heap-broker.h.
                                           {
    DCHECK_NOT_NULL(canonical_handles_);
    if (Tagged<HeapObject> heap_object;
        TryCast<HeapObject>(*handle, &heap_object)) {
      RootIndex root_index;
      if (root_index_map_.Lookup(heap_object, &root_index)) {
        return true;
      }
      // Builtins use pseudo handles that are canonical and persistent by
      // design.
      if (isolate()->IsBuiltinTableHandleLocation(handle.location())) {
        return true;
      }
    }
    return canonical_handles_->Find(*handle) != nullptr;
  }
References DCHECK_NOT_NULL, v8::internal::handle(), and v8::internal::Isolate::IsBuiltinTableHandleLocation().
IsMainThread()
bool v8::internal::compiler::JSHeapBroker::IsMainThread () const [inline]
Definition at line 260 of file js-heap-broker.h.
                            {
    return local_isolate() == nullptr || local_isolate()->is_main_thread();
  }
Referenced by ObjectMayBeUninitialized().
isolate()
Isolate* v8::internal::compiler::JSHeapBroker::isolate () const [inline]
Definition at line 118 of file js-heap-broker.h.
{ return isolate_; }
Referenced by v8::internal::compiler::CompilationDependencies::Commit(), v8::internal::compiler::CompilationDependencies::DependOnArrayBufferDetachingProtector(), v8::internal::compiler::CompilationDependencies::DependOnArrayIteratorProtector(), v8::internal::compiler::CompilationDependencies::DependOnArraySpeciesProtector(), v8::internal::compiler::CompilationDependencies::DependOnMegaDOMProtector(), v8::internal::compiler::CompilationDependencies::DependOnNoDateTimeConfigurationChangeProtector(), v8::internal::compiler::CompilationDependencies::DependOnNoElementsProtector(), v8::internal::compiler::CompilationDependencies::DependOnNoProfilingProtector(), v8::internal::compiler::CompilationDependencies::DependOnNoUndetectableObjectsProtector(), v8::internal::compiler::CompilationDependencies::DependOnPromiseHookProtector(), v8::internal::compiler::CompilationDependencies::DependOnPromiseSpeciesProtector(), v8::internal::compiler::CompilationDependencies::DependOnPromiseThenProtector(), v8::internal::compiler::CompilationDependencies::DependOnStringWrapperToPrimitiveProtector(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), IsArrayOrObjectPrototype(), v8::internal::compiler::AccessInfoFactory::isolate(), v8::internal::compiler::RepresentationChanger::isolate(), ObjectMayBeUninitialized(), ProcessFeedbackMapsForElementAccess(), and ReadFeedbackForPropertyAccess().
local_isolate()
LocalIsolate* v8::internal::compiler::JSHeapBroker::local_isolate () const [inline]
Definition at line 264 of file js-heap-broker.h.
{ return local_isolate_; }
Referenced by AttachLocalIsolate(), and AttachLocalIsolateForMaglev().
local_isolate_or_isolate()
LocalIsolate* v8::internal::compiler::JSHeapBroker::local_isolate_or_isolate () const [inline]
Definition at line 269 of file js-heap-broker.h.
                                                 {
    return local_isolate() != nullptr ? local_isolate()
                                      : isolate()->AsLocalIsolate();
  }
References v8::internal::Isolate::AsLocalIsolate().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::Concatenate(), v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString().
mode()
BrokerMode v8::internal::compiler::JSHeapBroker::mode () const [inline]
Definition at line 140 of file js-heap-broker.h.
{ return mode_; }
Referenced by GetFeedbackForPropertyAccess(), and ReadFeedbackForCall().
NewInsufficientFeedback()
const ProcessedFeedback & v8::internal::compiler::JSHeapBroker::NewInsufficientFeedback (FeedbackSlotKind kind) const [private]
Definition at line 464 of file js-heap-broker.cc.
                                 {
  return *zone()->New<InsufficientFeedback>(kind);
}
References v8::internal::Zone::New(), and zone().
Referenced by ReadFeedbackForArrayOrObjectLiteral(), ReadFeedbackForBinaryOperation(), ReadFeedbackForCall(), ReadFeedbackForCompareOperation(), ReadFeedbackForForIn(), ReadFeedbackForGlobalAccess(), ReadFeedbackForInstanceOf(), ReadFeedbackForPropertyAccess(), ReadFeedbackForRegExpLiteral(), ReadFeedbackForTemplateObject(), and ReadFeedbackForTypeOf().
ObjectMayBeUninitialized() [1/3]
bool v8::internal::compiler::JSHeapBroker::ObjectMayBeUninitialized (DirectHandle< Object > object) const
Definition at line 159 of file js-heap-broker.cc.
                                                                             {
  return ObjectMayBeUninitialized(*object);
}
Referenced by ObjectMayBeUninitialized().
ObjectMayBeUninitialized() [2/3]
bool v8::internal::compiler::JSHeapBroker::ObjectMayBeUninitialized (Tagged< HeapObject > object) const
Definition at line 168 of file js-heap-broker.cc.
                                                                           {
  return !IsMainThread() && isolate()->heap()->IsPendingAllocation(object);
}
References v8::internal::Isolate::heap(), IsMainThread(), isolate(), and v8::internal::Heap::IsPendingAllocation().
ObjectMayBeUninitialized() [3/3]
bool v8::internal::compiler::JSHeapBroker::ObjectMayBeUninitialized (Tagged< Object > object) const
Definition at line 163 of file js-heap-broker.cc.
                                                                       {
  if (!IsHeapObject(object)) return false;
  return ObjectMayBeUninitialized(Cast<HeapObject>(object));
}
References v8::internal::IsHeapObject(), and ObjectMayBeUninitialized().
ProcessFeedbackForBinaryOperation()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ProcessFeedbackForBinaryOperation (FeedbackSource const & source)
Definition at line 780 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForBinaryOperation(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForBinaryOperation(), and SetFeedback().
Referenced by GetFeedbackForBinaryOperation().
ProcessFeedbackForCompareOperation()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ProcessFeedbackForCompareOperation (FeedbackSource const & source)
Definition at line 788 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForCompareOperation(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForCompareOperation(), and SetFeedback().
Referenced by GetFeedbackForCompareOperation().
ProcessFeedbackForForIn()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ProcessFeedbackForForIn (FeedbackSource const & source)
Definition at line 796 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForForIn(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForForIn(), and SetFeedback().
Referenced by GetFeedbackForForIn().
ProcessFeedbackForTypeOf()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ProcessFeedbackForTypeOf (FeedbackSource const & source)
Definition at line 772 of file js-heap-broker.cc.
                                  {
  if (HasFeedback(source)) return GetFeedback(source);
  ProcessedFeedback const& feedback = ReadFeedbackForTypeOf(source);
  SetFeedback(source, &feedback);
  return feedback;
}
References GetFeedback(), HasFeedback(), ReadFeedbackForTypeOf(), and SetFeedback().
Referenced by GetFeedbackForTypeOf().
ProcessFeedbackMapsForElementAccess()
ElementAccessFeedback const & v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess (ZoneVector< MapRef > & maps, KeyedAccessMode const & keyed_mode, FeedbackSlotKind slot_kind)
Definition at line 850 of file js-heap-broker.cc.
                                {
  DCHECK(!maps.empty());
  DCHECK(!keyed_mode.string_keys());
  // Collect possible transition targets.
  MapHandles possible_transition_targets(isolate());
  possible_transition_targets.reserve(maps.size());
  for (MapRef& map : maps) {
    if (map.CanInlineElementAccess() &&
        IsFastElementsKind(map.elements_kind()) &&
        GetInitialFastElementsKind() != map.elements_kind()) {
      possible_transition_targets.push_back(map.object());
    }
  }
  using TransitionGroup = ElementAccessFeedback::TransitionGroup;
  ZoneRefMap<MapRef, TransitionGroup> transition_groups(zone());
  // Separate the actual receiver maps and the possible transition sources.
  for (MapRef map : maps) {
    Tagged<Map> transition_target;
    // Don't generate elements kind transitions from stable maps.
    if (!map.is_stable()) {
      // The lock is needed for UnusedPropertyFields (called deep inside
      // FindElementsKindTransitionedMap).
      MapUpdaterGuardIfNeeded mumd_scope(this);
      transition_target = map.object()->FindElementsKindTransitionedMap(
          isolate(),
          MapHandlesSpan(possible_transition_targets.begin(),
                         possible_transition_targets.end()),
          ConcurrencyMode::kConcurrent);
    }
    if (transition_target.is_null()) {
      TransitionGroup group(1, map, zone());
      transition_groups.insert({map, group});
    } else {
      MapRef target = MakeRefAssumeMemoryFence(this, transition_target);
      TransitionGroup new_group(1, target, zone());
      TransitionGroup& actual_group =
          transition_groups.insert({target, new_group}).first->second;
      actual_group.push_back(map);
    }
  }
  ElementAccessFeedback* result =
      zone()->New<ElementAccessFeedback>(zone(), keyed_mode, slot_kind);
  for (auto& entry : transition_groups) {
    result->AddGroup(std::move(entry.second));
  }
  CHECK(!result->transition_groups().empty());
  return *result;
}
References v8::internal::DirectHandleSmallVector< T, kSize >::begin(), CHECK, v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), v8::internal::DirectHandleSmallVector< T, kSize >::end(), v8::internal::GetInitialFastElementsKind(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsFastElementsKind(), isolate(), v8::internal::kConcurrent, v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::Zone::New(), v8::internal::DirectHandleSmallVector< T, kSize >::push_back(), v8::internal::DirectHandleSmallVector< T, kSize >::reserve(), v8::base::internal::result, v8::internal::ZoneVector< T >::size(), v8::internal::compiler::KeyedAccessMode::string_keys(), and zone().
Referenced by ReadFeedbackForPropertyAccess().
ProcessFeedbackMapsForKeyedPropertyAccess()
ElementAccessFeedback const & v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForKeyedPropertyAccess (ZoneVector< MapRef > & maps, KeyedAccessMode const & keyed_mode, FeedbackSlotKind slot_kind)
Definition at line 839 of file js-heap-broker.cc.
                                {
  DCHECK_EQ(maps.size(), 1);
  DCHECK(keyed_mode.string_keys());
  ElementAccessFeedback* result =
      zone()->New<ElementAccessFeedback>(zone(), keyed_mode, slot_kind);
  result->AddGroup(ElementAccessFeedback::TransitionGroup(1, maps[0], zone()));
  return *result;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Zone::New(), v8::base::internal::result, v8::internal::ZoneVector< T >::size(), v8::internal::compiler::KeyedAccessMode::string_keys(), and zone().
Referenced by ReadFeedbackForPropertyAccess().
ReadFeedbackForArrayOrObjectLiteral()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForArrayOrObjectLiteral (FeedbackSource const & source) [private]
Definition at line 647 of file js-heap-broker.cc.
                                  {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  Tagged<HeapObject> object;
  if (!nexus.GetFeedback().GetHeapObject(&object)) {
    return NewInsufficientFeedback(nexus.kind());
  }
  AllocationSiteRef site =
      MakeRefAssumeMemoryFence(this, Cast<AllocationSite>(object));
  return *zone()->New<LiteralFeedback>(site, nexus.kind());
}
References feedback_nexus_config(), v8::internal::FeedbackNexus::GetFeedback(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by GetFeedbackForArrayOrObjectLiteral().
ReadFeedbackForBinaryOperation()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForBinaryOperation (FeedbackSource const & source) const [private]
Definition at line 595 of file js-heap-broker.cc.
                                        {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  BinaryOperationHint hint = nexus.GetBinaryOperationFeedback();
  DCHECK_NE(hint, BinaryOperationHint::kNone); // Not uninitialized.
  return *zone()->New<BinaryOperationFeedback>(hint, nexus.kind());
}
References DCHECK_NE, feedback_nexus_config(), v8::internal::FeedbackNexus::GetBinaryOperationFeedback(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::internal::kNone, v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by ProcessFeedbackForBinaryOperation().
ReadFeedbackForCall()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall (FeedbackSource const & source) [private]
Definition at line 691 of file js-heap-broker.cc.
                                  {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  OptionalHeapObjectRef target_ref;
  {
    Tagged<MaybeObject> maybe_target = nexus.GetFeedback();
    Tagged<HeapObject> target_object;
    if (maybe_target.GetHeapObject(&target_object) &&
        (!IsJSFunction(target_object) ||
         // Eval mutates the context on the function, so block specializing for
         // these functions to avoid accidentally inlining the context as a
         // constant.
         Cast<JSFunction>(target_object)
                 ->shared()
                 ->function_literal_id(kRelaxedLoad) != 0)) {
      target_ref = TryMakeRef(this, target_object);
    }
  }
  float frequency = nexus.ComputeCallFrequency();
  SpeculationMode mode = nexus.GetSpeculationMode();
  CallFeedbackContent content = nexus.GetCallFeedbackContent();
  return *zone()->New<CallFeedback>(target_ref, frequency, mode, content,
                                    nexus.kind());
}
References v8::internal::FeedbackNexus::ComputeCallFrequency(), feedback_nexus_config(), v8::internal::function_literal_id, v8::internal::FeedbackNexus::GetCallFeedbackContent(), v8::internal::FeedbackNexus::GetFeedback(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::FeedbackNexus::GetSpeculationMode(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::kRelaxedLoad, mode(), v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::TryMakeRef(), v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by GetFeedbackForCall().
ReadFeedbackForCompareOperation()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForCompareOperation (FeedbackSource const & source) const [private]
Definition at line 612 of file js-heap-broker.cc.
                                        {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  CompareOperationHint hint = nexus.GetCompareOperationFeedback();
  DCHECK_NE(hint, CompareOperationHint::kNone); // Not uninitialized.
  return *zone()->New<CompareOperationFeedback>(hint, nexus.kind());
}
References DCHECK_NE, feedback_nexus_config(), v8::internal::FeedbackNexus::GetCompareOperationFeedback(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::internal::kNone, v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by ProcessFeedbackForCompareOperation().
ReadFeedbackForForIn()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForForIn (FeedbackSource const & source) const [private]
Definition at line 621 of file js-heap-broker.cc.
                                        {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  ForInHint hint = nexus.GetForInFeedback();
  DCHECK_NE(hint, ForInHint::kNone); // Not uninitialized.
  return *zone()->New<ForInFeedback>(hint, nexus.kind());
}
References DCHECK_NE, feedback_nexus_config(), v8::internal::FeedbackNexus::GetForInFeedback(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::internal::kNone, v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by ProcessFeedbackForForIn().
ReadFeedbackForGlobalAccess()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess (JSHeapBroker * broker, FeedbackSource const & source) [private]
Definition at line 551 of file js-heap-broker.cc.
                                                        {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  DCHECK(nexus.kind() == FeedbackSlotKind::kLoadGlobalInsideTypeof ||
         nexus.kind() == FeedbackSlotKind::kLoadGlobalNotInsideTypeof ||
         nexus.kind() == FeedbackSlotKind::kStoreGlobalSloppy ||
         nexus.kind() == FeedbackSlotKind::kStoreGlobalStrict);
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  if (nexus.ic_state() != InlineCacheState::MONOMORPHIC ||
      nexus.GetFeedback().IsCleared()) {
    return *zone()->New<GlobalAccessFeedback>(nexus.kind());
  }
  Handle<Object> feedback_value =
      CanonicalPersistentHandle(nexus.GetFeedback().GetHeapObjectOrSmi());
  if (IsSmi(*feedback_value)) {
    // The wanted name belongs to a script-scope variable and the feedback
    // tells us where to find its value.
    int const number = Object::NumberValue(*feedback_value);
    int const script_context_index =
        FeedbackNexus::ContextIndexBits::decode(number);
    int const context_slot_index = FeedbackNexus::SlotIndexBits::decode(number);
    ContextRef context = MakeRefAssumeMemoryFence(
        this,
        target_native_context().script_context_table(broker).object()->get(
            script_context_index, kAcquireLoad));
    OptionalObjectRef contents = context.get(broker, context_slot_index);
    if (contents.has_value()) CHECK(!contents->IsTheHole());
    return *zone()->New<GlobalAccessFeedback>(
        context, context_slot_index,
        FeedbackNexus::ImmutabilityBit::decode(number), nexus.kind());
  }
  CHECK(IsPropertyCell(*feedback_value));
  // The wanted name belongs (or did belong) to a property on the global
  // object and the feedback is the cell holding its value.
  return *zone()->New<GlobalAccessFeedback>(
      MakeRefAssumeMemoryFence(this, Cast<PropertyCell>(feedback_value)),
      nexus.kind());
}
References broker(), CanonicalPersistentHandle(), CHECK, v8::internal::DCHECK(), feedback_nexus_config(), v8::internal::compiler::ContextRef::get(), v8::internal::FeedbackNexus::GetFeedback(), v8::internal::FeedbackNexus::ic_state(), v8::internal::IsSmi(), v8::internal::FeedbackNexus::IsUninitialized(), v8::kAcquireLoad, v8::internal::FeedbackNexus::kind(), v8::internal::kLoadGlobalInsideTypeof, v8::internal::kLoadGlobalNotInsideTypeof, v8::internal::kStoreGlobalSloppy, v8::internal::kStoreGlobalStrict, v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::MONOMORPHIC, v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::Object::NumberValue(), v8::internal::compiler::FeedbackSource::slot, target_native_context(), v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by GetFeedbackForGlobalAccess().
ReadFeedbackForInstanceOf()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForInstanceOf (FeedbackSource const & source) [private]
Definition at line 630 of file js-heap-broker.cc.
                                  {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  OptionalJSObjectRef optional_constructor;
  {
    MaybeDirectHandle<JSObject> maybe_constructor =
        nexus.GetConstructorFeedback();
    DirectHandle<JSObject> constructor;
    if (maybe_constructor.ToHandle(&constructor)) {
      optional_constructor = MakeRefAssumeMemoryFence(this, *constructor);
    }
  }
  return *zone()->New<InstanceOfFeedback>(optional_constructor, nexus.kind());
}
References feedback_nexus_config(), v8::internal::FeedbackNexus::GetConstructorFeedback(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by GetFeedbackForInstanceOf().
ReadFeedbackForPropertyAccess()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess (FeedbackSource const & source, AccessMode mode, OptionalNameRef static_name) [private]
Definition at line 469 of file js-heap-broker.cc.
                                 {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  FeedbackSlotKind kind = nexus.kind();
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(kind);
  ZoneVector<MapRef> maps(zone());
  bool has_deprecated_map_without_migration_target = false;
  nexus.IterateMapsWithUnclearedHandler(
      [this, &maps, &has_deprecated_map_without_migration_target](
          DirectHandle<Map> map_handle) {
        MapRef map = MakeRefAssumeMemoryFence(this, *map_handle);
        // May change concurrently at any time - must be guarded by a
        // dependency if non-deprecation is important.
        if (map.is_deprecated()) {
          // TODO(ishell): support fast map updating if we enable it.
          CHECK(!v8_flags.fast_map_update);
          std::optional<Tagged<Map>> maybe_map = MapUpdater::TryUpdateNoLock(
              isolate(), *map.object(), ConcurrencyMode::kConcurrent);
          if (maybe_map.has_value()) {
            map = MakeRefAssumeMemoryFence(this, maybe_map.value());
          } else {
            return; // Couldn't update the deprecated map.
          }
          if (!map.is_migration_target()) {
            // Maps are marked as migration targets only when an object
            // migrates, so it's possible to have a deprecated map whose updated
            // counterpart is not a migration target.
            has_deprecated_map_without_migration_target = true;
          }
        }
        if (map.is_abandoned_prototype_map()) return;
        maps.push_back(map);
      });
  OptionalNameRef name =
      static_name.has_value() ? static_name : GetNameFeedback(nexus);
  if (nexus.ic_state() == InlineCacheState::MEGADOM) {
    DCHECK(maps.empty());
    MaybeObjectHandle maybe_handler = nexus.ExtractMegaDOMHandler();
    if (!maybe_handler.is_null()) {
      DirectHandle<MegaDomHandler> handler =
          Cast<MegaDomHandler>(maybe_handler.object());
      if (!handler->accessor(kAcquireLoad).IsCleared()) {
        FunctionTemplateInfoRef info = MakeRefAssumeMemoryFence(
            this, Cast<FunctionTemplateInfo>(
                      handler->accessor(kAcquireLoad).GetHeapObject()));
        return *zone()->New<MegaDOMPropertyAccessFeedback>(info, kind);
      }
    }
  }
  // If no maps were found for a non-megamorphic access, then our maps died
  // and we should soft-deopt.
  if (maps.empty() && nexus.ic_state() != InlineCacheState::MEGAMORPHIC) {
    return NewInsufficientFeedback(kind);
  }
  if (name.has_value()) {
    // We rely on this invariant in JSGenericLowering.
    DCHECK_IMPLIES(maps.empty(),
                   nexus.ic_state() == InlineCacheState::MEGAMORPHIC);
    return *zone()->New<NamedAccessFeedback>(
        *name, maps, kind, has_deprecated_map_without_migration_target);
  } else if (nexus.GetKeyType() == IcCheckType::kElement && !maps.empty()) {
    return ProcessFeedbackMapsForElementAccess(
        maps, KeyedAccessMode::FromNexus(nexus), kind);
  } else if (nexus.IsOneMapManyNames() && maps.size() == 1) {
    return ProcessFeedbackMapsForKeyedPropertyAccess(
        maps, KeyedAccessMode::FromNexus(nexus), kind);
  } else {
    // No actionable feedback.
    DCHECK(maps.empty());
    DCHECK_EQ(nexus.ic_state(), InlineCacheState::MEGAMORPHIC);
    // TODO(neis): Using ElementAccessFeedback here is kind of an abuse.
    return *zone()->New<ElementAccessFeedback>(
        zone(), KeyedAccessMode::FromNexus(nexus), kind);
  }
}
References CHECK, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::ZoneVector< T >::empty(), v8::internal::FeedbackNexus::ExtractMegaDOMHandler(), feedback_nexus_config(), v8::internal::compiler::KeyedAccessMode::FromNexus(), v8::internal::FeedbackNexus::GetKeyType(), GetNameFeedback(), v8::internal::FeedbackNexus::ic_state(), v8::internal::compiler::MapRef::is_abandoned_prototype_map(), v8::internal::compiler::MapRef::is_deprecated(), v8::internal::compiler::MapRef::is_migration_target(), v8::internal::MaybeObjectHandle::is_null(), isolate(), v8::internal::FeedbackNexus::IsOneMapManyNames(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::IterateMapsWithUnclearedHandler(), v8::kAcquireLoad, v8::internal::kConcurrent, v8::internal::kElement, v8::internal::FeedbackNexus::kind(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::MEGADOM, v8::internal::MEGAMORPHIC, v8::internal::name, v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::MapRef::object(), v8::internal::MaybeObjectHandle::object(), ProcessFeedbackMapsForElementAccess(), ProcessFeedbackMapsForKeyedPropertyAccess(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::FeedbackSource::slot, v8::internal::MapUpdater::TryUpdateNoLock(), v8::internal::v8_flags, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by GetFeedbackForPropertyAccess().
ReadFeedbackForRegExpLiteral()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForRegExpLiteral (FeedbackSource const & source) [private]
Definition at line 662 of file js-heap-broker.cc.
                                  {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  Tagged<HeapObject> object;
  if (!nexus.GetFeedback().GetHeapObject(&object)) {
    return NewInsufficientFeedback(nexus.kind());
  }
  RegExpBoilerplateDescriptionRef boilerplate = MakeRefAssumeMemoryFence(
      this, Cast<RegExpBoilerplateDescription>(object));
  return *zone()->New<RegExpLiteralFeedback>(boilerplate, nexus.kind());
}
References feedback_nexus_config(), v8::internal::FeedbackNexus::GetFeedback(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by GetFeedbackForRegExpLiteral().
ReadFeedbackForTemplateObject()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForTemplateObject (FeedbackSource const & source) [private]
Definition at line 677 of file js-heap-broker.cc.
                                  {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  Tagged<HeapObject> object;
  if (!nexus.GetFeedback().GetHeapObject(&object)) {
    return NewInsufficientFeedback(nexus.kind());
  }
  JSArrayRef array = MakeRefAssumeMemoryFence(this, Cast<JSArray>(object));
  return *zone()->New<TemplateObjectFeedback>(array, nexus.kind());
}
References feedback_nexus_config(), v8::internal::FeedbackNexus::GetFeedback(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by GetFeedbackForTemplateObject().
ReadFeedbackForTypeOf()
ProcessedFeedback const & v8::internal::compiler::JSHeapBroker::ReadFeedbackForTypeOf (FeedbackSource const & source) const [private]
Definition at line 604 of file js-heap-broker.cc.
                                        {
  FeedbackNexus nexus(source.vector, source.slot, feedback_nexus_config());
  if (nexus.IsUninitialized()) return NewInsufficientFeedback(nexus.kind());
  return *zone()->New<TypeOfOpFeedback>(nexus.GetTypeOfFeedback(),
                                        nexus.kind());
}
References feedback_nexus_config(), v8::internal::FeedbackNexus::GetTypeOfFeedback(), v8::internal::FeedbackNexus::IsUninitialized(), v8::internal::FeedbackNexus::kind(), v8::internal::Zone::New(), NewInsufficientFeedback(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by ProcessFeedbackForTypeOf().
Retire()
void v8::internal::compiler::JSHeapBroker::Retire ()
Definition at line 108 of file js-heap-broker.cc.
                          {
  CHECK_EQ(mode_, kSerialized);
  TRACE(this, "Retiring");
  mode_ = kRetired;
}
References CHECK_EQ, kRetired, kSerialized, mode_, and v8::internal::TRACE().
SerializingAllowed()
bool v8::internal::compiler::JSHeapBroker::SerializingAllowed () const
set_canonical_handles()
void v8::internal::compiler::JSHeapBroker::set_canonical_handles (CanonicalHandlesMap * canonical_handles) [inline], [private]
Definition at line 451 of file js-heap-broker.h.
                                                                     {
    canonical_handles_ = canonical_handles;
  }
set_dependencies()
void v8::internal::compiler::JSHeapBroker::set_dependencies (CompilationDependencies * dependencies) [inline]
Definition at line 391 of file js-heap-broker.h.
                                                               {
    DCHECK_NOT_NULL(dependencies);
    DCHECK_NULL(dependencies_);
    dependencies_ = dependencies;
  }
References DCHECK_NOT_NULL, and DCHECK_NULL.
set_persistent_handles()
void v8::internal::compiler::JSHeapBroker::set_persistent_handles (std::unique_ptr< PersistentHandles > persistent_handles) [inline], [private]
Definition at line 440 of file js-heap-broker.h.
                                                           {
    DCHECK_NULL(ph_);
    ph_ = std::move(persistent_handles);
    DCHECK_NOT_NULL(ph_);
  }
References DCHECK_NOT_NULL, and DCHECK_NULL.
SetFeedback()
void v8::internal::compiler::JSHeapBroker::SetFeedback (FeedbackSource const & source, ProcessedFeedback const * feedback)
Definition at line 431 of file js-heap-broker.cc.
                                                                  {
  CHECK(source.IsValid());
  auto insertion = feedback_.insert({source, feedback});
  CHECK(insertion.second);
}
References CHECK, feedback_, and v8::internal::compiler::FeedbackSource::IsValid().
Referenced by GetFeedbackForArrayOrObjectLiteral(), GetFeedbackForCall(), GetFeedbackForGlobalAccess(), GetFeedbackForInstanceOf(), GetFeedbackForPropertyAccess(), GetFeedbackForRegExpLiteral(), GetFeedbackForTemplateObject(), ProcessFeedbackForBinaryOperation(), ProcessFeedbackForCompareOperation(), ProcessFeedbackForForIn(), and ProcessFeedbackForTypeOf().
SetTargetNativeContextRef()
void v8::internal::compiler::JSHeapBroker::SetTargetNativeContextRef (DirectHandle< NativeContext > native_context)
Definition at line 114 of file js-heap-broker.cc.
                                                {
  DCHECK(!target_native_context_.has_value());
  target_native_context_ = MakeRef(this, *native_context);
}
References v8::internal::DCHECK(), v8::internal::compiler::MakeRef(), v8::internal::native_context, and target_native_context_.
Referenced by InitializeAndStartSerializing().
StackHasOverflowed()
bool v8::internal::compiler::JSHeapBroker::StackHasOverflowed () const
Definition at line 151 of file js-heap-broker.cc.
                                            {
  DCHECK_IMPLIES(local_isolate_ == nullptr,
                 ThreadId::Current() == isolate_->thread_id());
  return (local_isolate_ != nullptr)
             ? StackLimitCheck::HasOverflowed(local_isolate_)
             : StackLimitCheck(isolate_).HasOverflowed();
}
References v8::internal::ThreadId::Current(), DCHECK_IMPLIES, v8::internal::StackLimitCheck::HasOverflowed(), isolate_, local_isolate_, and v8::internal::Isolate::thread_id().
StopSerializing()
void v8::internal::compiler::JSHeapBroker::StopSerializing ()
Definition at line 102 of file js-heap-broker.cc.
                                   {
  CHECK_EQ(mode_, kSerializing);
  TRACE(this, "Stopping serialization");
  mode_ = kSerialized;
}
References CHECK_EQ, kSerialized, kSerializing, mode_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), and v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo().
target_native_context()
NativeContextRef v8::internal::compiler::JSHeapBroker::target_native_context () const [inline]
Definition at line 110 of file js-heap-broker.h.
                                                 {
    return target_native_context_.value();
  }
Referenced by v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChain(), InitializeAndStartSerializing(), v8::internal::compiler::JSCallReducer::native_context(), v8::internal::compiler::JSCreateLowering::native_context(), v8::internal::maglev::MaglevCodeGenState::native_context(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), and ReadFeedbackForGlobalAccess().
Trace()
std::string v8::internal::compiler::JSHeapBroker::Trace () const
Definition at line 59 of file js-heap-broker.cc.
                                    {
  std::ostringstream oss;
  oss << "[" << this << "] ";
  for (unsigned i = 0; i < trace_indentation_ * 2; ++i) oss.put(' ');
  return oss.str();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and trace_indentation_.
tracing_enabled()
bool v8::internal::compiler::JSHeapBroker::tracing_enabled () const [inline]
Definition at line 131 of file js-heap-broker.h.
{ return tracing_enabled_; }
TryGetOrCreateData() [1/2]
ObjectData* v8::internal::compiler::JSHeapBroker::TryGetOrCreateData (Handle< Object > object, GetOrCreateDataFlags flags = {})
Referenced by GetOrCreateData().
TryGetOrCreateData() [2/2]
template<typename T >
ObjectData* v8::internal::compiler::JSHeapBroker::TryGetOrCreateData (Tagged< T > object, GetOrCreateDataFlags flags = {}) [inline]
Definition at line 196 of file js-heap-broker.h.
                                                              {}) {
    return TryGetOrCreateData(CanonicalPersistentHandle(object), flags);
  }
zone()
Zone* v8::internal::compiler::JSHeapBroker::zone () const [inline]
Definition at line 130 of file js-heap-broker.h.
{ return zone_; }
Referenced by GetPropertyAccessInfo(), InitializeAndStartSerializing(), NewInsufficientFeedback(), ProcessFeedbackMapsForElementAccess(), ProcessFeedbackMapsForKeyedPropertyAccess(), ReadFeedbackForArrayOrObjectLiteral(), ReadFeedbackForBinaryOperation(), ReadFeedbackForCall(), ReadFeedbackForCompareOperation(), ReadFeedbackForForIn(), ReadFeedbackForGlobalAccess(), ReadFeedbackForInstanceOf(), ReadFeedbackForPropertyAccess(), ReadFeedbackForRegExpLiteral(), ReadFeedbackForTemplateObject(), and ReadFeedbackForTypeOf().
Friends And Related Function Documentation
HeapObjectRef
friend class HeapObjectRef [friend]
Definition at line 407 of file js-heap-broker.h.
JSHeapBrokerScopeForTesting
friend class JSHeapBrokerScopeForTesting [friend]
Definition at line 406 of file js-heap-broker.h.
ObjectData
friend class ObjectData [friend]
Definition at line 409 of file js-heap-broker.h.
ObjectRef
friend class ObjectRef [friend]
Definition at line 408 of file js-heap-broker.h.
PropertyCellData
friend class PropertyCellData [friend]
Definition at line 410 of file js-heap-broker.h.
Member Data Documentation
boilerplate_migration_mutex_depth_
int v8::internal::compiler::JSHeapBroker::boilerplate_migration_mutex_depth_ = 0 [private]
Definition at line 498 of file js-heap-broker.h.
canonical_handles_
CanonicalHandlesMap* v8::internal::compiler::JSHeapBroker::canonical_handles_ [private]
Definition at line 473 of file js-heap-broker.h.
code_kind_
CodeKind const v8::internal::compiler::JSHeapBroker::code_kind_ [private]
Definition at line 469 of file js-heap-broker.h.
dependencies_
CompilationDependencies* v8::internal::compiler::JSHeapBroker::dependencies_ = nullptr [private]
Definition at line 488 of file js-heap-broker.h.
Referenced by GetPropertyAccessInfo().
feedback_
ZoneUnorderedMap<FeedbackSource, ProcessedFeedback const*, FeedbackSource::Hash, FeedbackSource::Equal> v8::internal::compiler::JSHeapBroker::feedback_ [private]
Definition at line 477 of file js-heap-broker.h.
Referenced by GetFeedback(), HasFeedback(), InitializeAndStartSerializing(), and SetFeedback().
isolate_
Isolate* const v8::internal::compiler::JSHeapBroker::isolate_ [private]
Definition at line 459 of file js-heap-broker.h.
Referenced by IsArrayOrObjectPrototype(), and StackHasOverflowed().
kInitialRefsBucketCount
constexpr uint32_t v8::internal::compiler::JSHeapBroker::kInitialRefsBucketCount = 16 [static], [constexpr], [private]
Definition at line 502 of file js-heap-broker.h.
Referenced by InitializeAndStartSerializing().
kMinimalRefsBucketCount
constexpr uint32_t v8::internal::compiler::JSHeapBroker::kMinimalRefsBucketCount = 8 [static], [constexpr], [private]
Definition at line 500 of file js-heap-broker.h.
local_isolate_
LocalIsolate* v8::internal::compiler::JSHeapBroker::local_isolate_ = nullptr [private]
Definition at line 471 of file js-heap-broker.h.
Referenced by AttachLocalIsolate(), AttachLocalIsolateForMaglev(), DetachLocalIsolate(), DetachLocalIsolateForMaglev(), StackHasOverflowed(), and ~JSHeapBroker().
map_updater_mutex_depth_
int v8::internal::compiler::JSHeapBroker::map_updater_mutex_depth_ = 0 [private]
Definition at line 496 of file js-heap-broker.h.
mode_
BrokerMode v8::internal::compiler::JSHeapBroker::mode_ = kDisabled [private]
Definition at line 467 of file js-heap-broker.h.
Referenced by InitializeAndStartSerializing(), Retire(), and StopSerializing().
ph_
std::unique_ptr<PersistentHandles> v8::internal::compiler::JSHeapBroker::ph_ [private]
Definition at line 470 of file js-heap-broker.h.
Referenced by DetachLocalIsolate(), and DetachLocalIsolateForMaglev().
property_access_infos_
ZoneUnorderedMap<PropertyAccessTarget, PropertyAccessInfo, PropertyAccessTarget::Hash, PropertyAccessTarget::Equal> v8::internal::compiler::JSHeapBroker::property_access_infos_ [private]
Definition at line 480 of file js-heap-broker.h.
Referenced by GetPropertyAccessInfo().
refs_
RefsMap* v8::internal::compiler::JSHeapBroker::refs_ [private]
Definition at line 465 of file js-heap-broker.h.
Referenced by InitializeAndStartSerializing().
root_index_map_
RootIndexMap v8::internal::compiler::JSHeapBroker::root_index_map_ [private]
Definition at line 466 of file js-heap-broker.h.
target_native_context_
OptionalNativeContextRef v8::internal::compiler::JSHeapBroker::target_native_context_ [private]
Definition at line 464 of file js-heap-broker.h.
Referenced by SetTargetNativeContextRef().
trace_indentation_
unsigned v8::internal::compiler::JSHeapBroker::trace_indentation_ = 0 [private]
Definition at line 474 of file js-heap-broker.h.
Referenced by DecrementTracingIndentation(), IncrementTracingIndentation(), and Trace().
tracing_enabled_
bool const v8::internal::compiler::JSHeapBroker::tracing_enabled_ [private]
Definition at line 468 of file js-heap-broker.h.
zone_
Zone* const v8::internal::compiler::JSHeapBroker::zone_ [private]
Definition at line 463 of file js-heap-broker.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-heap-broker.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc
/mnt/V8SourceCode/src/compiler/js-heap-broker.cc
/mnt/V8SourceCode/src/maglev/maglev-concurrent-dispatcher.cc