v8::internal::maglev::CallSelf Class Reference
#include <maglev-ir.h>
Public Member Functions
CallSelf (uint64_t bitfield, int expected_parameter_count, ValueNode *closure, ValueNode *context, ValueNode *receiver, ValueNode *new_target)
Input & closure ()
const Input & closure () const
Input & context ()
const Input & context () const
Input & receiver ()
const Input & receiver () const
Input & new_target ()
const Input & new_target () const
int num_args () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
auto args ()
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr int kClosureIndex = 0
static constexpr int kContextIndex = 1
static constexpr int kReceiverIndex = 2
static constexpr int kNewTargetIndex = 3
static constexpr int kFixedInputCount = 4
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< CallSelf >
Private Attributes
int expected_parameter_count_
Additional Inherited Members
Detailed Description
Definition at line 10470 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallSelf::Base = ValueNodeT<CallSelf> [private]
Definition at line 10471 of file maglev-ir.h.
Constructor & Destructor Documentation
CallSelf()
v8::internal::maglev::CallSelf::CallSelf (uint64_t bitfield, int expected_parameter_count, ValueNode * closure, ValueNode * context, ValueNode * receiver, ValueNode * new_target) [inline]
Definition at line 10486 of file maglev-ir.h.
      : Base(bitfield), expected_parameter_count_(expected_parameter_count) {
    set_input(kClosureIndex, closure);
    set_input(kContextIndex, context);
    set_input(kReceiverIndex, receiver);
    set_input(kNewTargetIndex, new_target);
  }
Member Function Documentation
arg()
Input& v8::internal::maglev::CallSelf::arg (int i) [inline]
Definition at line 10506 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
args()
auto v8::internal::maglev::CallSelf::args () [inline]
Definition at line 10510 of file maglev-ir.h.
              {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args() - 1)));
  }
References v8::base::make_iterator_range().
closure() [1/2]
Input& v8::internal::maglev::CallSelf::closure () [inline]
Definition at line 10497 of file maglev-ir.h.
{ return input(kClosureIndex); }
closure() [2/2]
const Input& v8::internal::maglev::CallSelf::closure () const [inline]
Definition at line 10498 of file maglev-ir.h.
{ return input(kClosureIndex); }
context() [1/2]
Input& v8::internal::maglev::CallSelf::context () [inline]
Definition at line 10499 of file maglev-ir.h.
{ return input(kContextIndex); }
context() [2/2]
const Input& v8::internal::maglev::CallSelf::context () const [inline]
Definition at line 10500 of file maglev-ir.h.
{ return input(kContextIndex); }
GenerateCode()
void v8::internal::maglev::CallSelf::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CallSelf::MaxCallStackArgs () const
new_target() [1/2]
Input& v8::internal::maglev::CallSelf::new_target () [inline]
Definition at line 10503 of file maglev-ir.h.
{ return input(kNewTargetIndex); }
new_target() [2/2]
const Input& v8::internal::maglev::CallSelf::new_target () const [inline]
Definition at line 10504 of file maglev-ir.h.
{ return input(kNewTargetIndex); }
num_args()
int v8::internal::maglev::CallSelf::num_args () const [inline]
Definition at line 10505 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
PrintParams()
void v8::internal::maglev::CallSelf::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8383 of file maglev-ir.cc.
                                                                      {}
receiver() [1/2]
Input& v8::internal::maglev::CallSelf::receiver () [inline]
Definition at line 10501 of file maglev-ir.h.
{ return input(kReceiverIndex); }
receiver() [2/2]
const Input& v8::internal::maglev::CallSelf::receiver () const [inline]
Definition at line 10502 of file maglev-ir.h.
{ return input(kReceiverIndex); }
set_arg()
void v8::internal::maglev::CallSelf::set_arg (int i, ValueNode * node) [inline]
Definition at line 10507 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallSelf().
SetValueLocationConstraints()
void v8::internal::maglev::CallSelf::SetValueLocationConstraints ()
VerifyInputs()
void v8::internal::maglev::CallSelf::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 979 of file maglev-ir.cc.
                                                                     {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
expected_parameter_count_
int v8::internal::maglev::CallSelf::expected_parameter_count_ [private]
Definition at line 10526 of file maglev-ir.h.
kClosureIndex
constexpr int v8::internal::maglev::CallSelf::kClosureIndex = 0 [static], [constexpr]
Definition at line 10474 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::CallSelf::kContextIndex = 1 [static], [constexpr]
Definition at line 10475 of file maglev-ir.h.
kFixedInputCount
constexpr int v8::internal::maglev::CallSelf::kFixedInputCount = 4 [static], [constexpr]
Definition at line 10478 of file maglev-ir.h.
kNewTargetIndex
constexpr int v8::internal::maglev::CallSelf::kNewTargetIndex = 3 [static], [constexpr]
Definition at line 10477 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CallSelf::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10495 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CallSelf::kReceiverIndex = 2 [static], [constexpr]
Definition at line 10476 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc