v8::internal::ExpressionScope< Types > Class Template Reference
#include <expression-scope.h>
Public Types
using ParserT = typename Types::Impl
using ExpressionT = typename Types::Expression
Public Member Functions
ExpressionScope (const ExpressionScope &)=delete
ExpressionScope & operator= (const ExpressionScope &)=delete
VariableProxy * NewVariable (const AstRawString *name, int pos=kNoSourcePosition)
void MergeVariableList (ScopedList< std::pair< VariableProxy *, int >> *variable_list)
Variable * Declare (const AstRawString *name, int pos=kNoSourcePosition)
void MarkIdentifierAsAssigned ()
void ValidateAsPattern (ExpressionT expression, int begin, int end)
void ValidateAsExpression ()
void RecordAsyncArrowParametersError (const Scanner::Location &loc, MessageTemplate message)
void RecordParameterInitializerError (const Scanner::Location &loc, MessageTemplate message)
void RecordThisUse ()
void RecordPatternError (const Scanner::Location &loc, MessageTemplate message)
void RecordStrictModeParameterError (const Scanner::Location &loc, MessageTemplate message)
void RecordDeclarationError (const Scanner::Location &loc, MessageTemplate message)
void RecordExpressionError (const Scanner::Location &loc, MessageTemplate message)
void RecordNonSimpleParameter ()
bool IsCertainlyDeclaration () const
int SetInitializers (int variable_index, int peek_position)
bool has_possible_arrow_parameter_in_scope_chain () const
Protected Types
enum ScopeType : uint8_t {
kExpression
, kMaybeArrowParameterDeclaration
, kMaybeAsyncArrowParameterDeclaration
, kParameterDeclaration
,
kVarDeclaration
, kLexicalDeclaration
 }
Protected Member Functions
ParserT * parser () const
ExpressionScope * parent () const
void Report (const Scanner::Location &loc, MessageTemplate message) const
ExpressionScope (ParserT *parser, ScopeType type)
~ExpressionScope ()
ExpressionParsingScope< Types > * AsExpressionParsingScope ()
bool CanBeExpression () const
bool CanBeDeclaration () const
bool IsVariableDeclaration () const
bool IsLexicalDeclaration () const
bool IsAsyncArrowHeadParsingScope () const
bool IsVarDeclaration () const
Private Member Functions
ArrowHeadParsingScope< Types > * AsArrowHeadParsingScope ()
ParameterDeclarationParsingScope< Types > * AsParameterDeclarationParsingScope ()
VariableDeclarationParsingScope< Types > * AsVariableDeclarationParsingScope ()
bool IsArrowHeadParsingScope () const
bool IsCertainlyPattern () const
bool CanBeParameterDeclaration () const
bool CanBeArrowParameterDeclaration () const
bool IsCertainlyParameterDeclaration () const
Private Attributes
ParserT * parser_
ExpressionScope< Types > * parent_
ScopeType type_
bool has_possible_parameter_in_scope_chain_
bool has_possible_arrow_parameter_in_scope_chain_
Friends
class AccumulationScope< Types >
class ExpressionParsingScope< Types >
Detailed Description
template<typename Types>
class v8::internal::ExpressionScope< Types >
Definition at line 44 of file expression-scope.h.
Member Typedef Documentation
ExpressionT
template<typename Types >
using v8::internal::ExpressionScope< Types >::ExpressionT = typename Types::Expression
Definition at line 50 of file expression-scope.h.
ParserT
template<typename Types >
using v8::internal::ExpressionScope< Types >::ParserT = typename Types::Impl
Definition at line 49 of file expression-scope.h.
Member Enumeration Documentation
ScopeType
template<typename Types >
enum v8::internal::ExpressionScope::ScopeType : uint8_t [protected]
Enumerator
kExpression
kMaybeArrowParameterDeclaration
kMaybeAsyncArrowParameterDeclaration
kParameterDeclaration
kVarDeclaration
kLexicalDeclaration
Definition at line 239 of file expression-scope.h.
                 : uint8_t {
    // Expression or assignment target.
    kExpression,
    // Declaration or expression or assignment target.
    kMaybeArrowParameterDeclaration,
    kMaybeAsyncArrowParameterDeclaration,
    // Declarations.
    kParameterDeclaration,
    kVarDeclaration,
    kLexicalDeclaration,
  };
Constructor & Destructor Documentation
ExpressionScope() [1/2]
template<typename Types >
v8::internal::ExpressionScope< Types >::ExpressionScope (const ExpressionScope< Types > &) [delete]
ExpressionScope() [2/2]
template<typename Types >
v8::internal::ExpressionScope< Types >::ExpressionScope (ParserT * parser, ScopeType type) [inline], [protected]
Definition at line 260 of file expression-scope.h.
      : parser_(parser),
        parent_(parser->expression_scope_),
        type_(type),
        has_possible_parameter_in_scope_chain_(
            CanBeParameterDeclaration() ||
            (parent_ && parent_->has_possible_parameter_in_scope_chain_)),
        has_possible_arrow_parameter_in_scope_chain_(
            CanBeArrowParameterDeclaration() ||
            (parent_ &&
             parent_->has_possible_arrow_parameter_in_scope_chain_)) {
    parser->expression_scope_ = this;
  }
References v8::internal::ExpressionScope< Types >::parser().
 ExpressionScope()
template<typename Types >
v8::internal::ExpressionScope< Types >::~ExpressionScope () [inline], [protected]
Definition at line 274 of file expression-scope.h.
                     {
    DCHECK(parser_->expression_scope_ == this ||
           parser_->expression_scope_ == parent_);
    parser_->expression_scope_ = parent_;
  }
References v8::internal::DCHECK(), v8::internal::ExpressionScope< Types >::parent_, and v8::internal::ExpressionScope< Types >::parser_.
Member Function Documentation
AsArrowHeadParsingScope()
template<typename Types >
ArrowHeadParsingScope<Types>* v8::internal::ExpressionScope< Types >::AsArrowHeadParsingScope () [inline], [private]
Definition at line 310 of file expression-scope.h.
                                                          {
    DCHECK(IsArrowHeadParsingScope());
    return static_cast<ArrowHeadParsingScope<Types>*>(this);
  }
References v8::internal::DCHECK(), and v8::internal::ExpressionScope< Types >::IsArrowHeadParsingScope().
Referenced by v8::internal::ExpressionScope< Types >::RecordDeclarationError(), v8::internal::ExpressionScope< Types >::RecordNonSimpleParameter(), v8::internal::ExpressionScope< Types >::RecordParameterInitializerError(), and v8::internal::ExpressionScope< Types >::RecordThisUse().
AsExpressionParsingScope()
template<typename Types >
ExpressionParsingScope<Types>* v8::internal::ExpressionScope< Types >::AsExpressionParsingScope () [inline], [protected]
Definition at line 280 of file expression-scope.h.
                                                            {
    DCHECK(CanBeExpression());
    return static_cast<ExpressionParsingScope<Types>*>(this);
  }
References v8::internal::ExpressionScope< Types >::CanBeExpression(), and v8::internal::DCHECK().
Referenced by v8::internal::AccumulationScope< Types >::AccumulationScope(), v8::internal::ExpressionScope< Types >::MarkIdentifierAsAssigned(), v8::internal::ExpressionScope< Types >::MergeVariableList(), v8::internal::ExpressionScope< Types >::NewVariable(), v8::internal::ExpressionScope< Types >::RecordAsyncArrowParametersError(), v8::internal::ExpressionScope< Types >::RecordExpressionError(), v8::internal::ExpressionScope< Types >::RecordPatternError(), v8::internal::ExpressionScope< Types >::SetInitializers(), v8::internal::ExpressionScope< Types >::ValidateAsExpression(), and v8::internal::ExpressionScope< Types >::ValidateAsPattern().
AsParameterDeclarationParsingScope()
template<typename Types >
ParameterDeclarationParsingScope<Types>* v8::internal::ExpressionScope< Types >::AsParameterDeclarationParsingScope () [inline], [private]
Definition at line 316 of file expression-scope.h.
                                       {
    DCHECK(IsCertainlyParameterDeclaration());
    return static_cast<ParameterDeclarationParsingScope<Types>*>(this);
  }
References v8::internal::DCHECK(), and v8::internal::ExpressionScope< Types >::IsCertainlyParameterDeclaration().
Referenced by v8::internal::ExpressionScope< Types >::Declare().
AsVariableDeclarationParsingScope()
template<typename Types >
VariableDeclarationParsingScope<Types>* v8::internal::ExpressionScope< Types >::AsVariableDeclarationParsingScope () [inline], [private]
Definition at line 321 of file expression-scope.h.
                                                                              {
    DCHECK(IsVariableDeclaration());
    return static_cast<VariableDeclarationParsingScope<Types>*>(this);
  }
References v8::internal::DCHECK(), and v8::internal::ExpressionScope< Types >::IsVariableDeclaration().
Referenced by v8::internal::ExpressionScope< Types >::Declare().
CanBeArrowParameterDeclaration()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::CanBeArrowParameterDeclaration () const [inline], [private]
Definition at line 335 of file expression-scope.h.
                                              {
    return base::IsInRange(type_, kMaybeArrowParameterDeclaration,
                           kMaybeAsyncArrowParameterDeclaration);
  }
References v8::internal::ExpressionScope< Types >::kMaybeArrowParameterDeclaration, v8::internal::ExpressionScope< Types >::kMaybeAsyncArrowParameterDeclaration, and v8::internal::ExpressionScope< Types >::type_.
CanBeDeclaration()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::CanBeDeclaration () const [inline], [protected]
Definition at line 293 of file expression-scope.h.
                                {
    return base::IsInRange(type_, kMaybeArrowParameterDeclaration,
                           kLexicalDeclaration);
  }
References v8::internal::ExpressionScope< Types >::kLexicalDeclaration, v8::internal::ExpressionScope< Types >::kMaybeArrowParameterDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::ArrowHeadParsingScope(), v8::internal::ExpressionScope< Types >::MergeVariableList(), v8::internal::ExpressionScope< Types >::RecordDeclarationError(), and v8::internal::ExpressionParsingScope< Types >::TrackVariable().
CanBeExpression()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::CanBeExpression () const [inline], [protected]
Definition at line 289 of file expression-scope.h.
                               {
    return base::IsInRange(type_, kExpression,
                           kMaybeAsyncArrowParameterDeclaration);
  }
References v8::internal::ExpressionScope< Types >::kExpression, v8::internal::ExpressionScope< Types >::kMaybeAsyncArrowParameterDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::AccumulationScope< Types >::AccumulationScope(), v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), v8::internal::ExpressionParsingScope< Types >::ExpressionParsingScope(), v8::internal::ExpressionScope< Types >::MarkIdentifierAsAssigned(), v8::internal::ExpressionScope< Types >::MergeVariableList(), v8::internal::ExpressionScope< Types >::NewVariable(), v8::internal::ExpressionScope< Types >::RecordAsyncArrowParametersError(), v8::internal::ExpressionScope< Types >::RecordExpressionError(), v8::internal::ExpressionScope< Types >::SetInitializers(), v8::internal::ExpressionScope< Types >::ValidateAsExpression(), and v8::internal::ExpressionScope< Types >::ValidateAsPattern().
CanBeParameterDeclaration()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::CanBeParameterDeclaration () const [inline], [private]
Definition at line 331 of file expression-scope.h.
                                         {
    return base::IsInRange(type_, kMaybeArrowParameterDeclaration,
                           kParameterDeclaration);
  }
References v8::internal::ExpressionScope< Types >::kMaybeArrowParameterDeclaration, v8::internal::ExpressionScope< Types >::kParameterDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::ExpressionScope< Types >::RecordParameterInitializerError(), and v8::internal::ExpressionScope< Types >::RecordStrictModeParameterError().
Declare()
template<typename Types >
Variable* v8::internal::ExpressionScope< Types >::Declare (const AstRawString * name, int pos = kNoSourcePosition) [inline]
Definition at line 111 of file expression-scope.h.
                                                                           {
    if (type_ == kParameterDeclaration) {
      return AsParameterDeclarationParsingScope()->Declare(name, pos);
    }
    return AsVariableDeclarationParsingScope()->Declare(name, pos);
  }
References v8::internal::ExpressionScope< Types >::AsParameterDeclarationParsingScope(), v8::internal::ExpressionScope< Types >::AsVariableDeclarationParsingScope(), v8::internal::ExpressionScope< Types >::kParameterDeclaration, v8::internal::name, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::ExpressionScope< Types >::NewVariable().
has_possible_arrow_parameter_in_scope_chain()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::has_possible_arrow_parameter_in_scope_chain () const [inline]
Definition at line 234 of file expression-scope.h.
                                                           {
    return has_possible_arrow_parameter_in_scope_chain_;
  }
References v8::internal::ExpressionScope< Types >::has_possible_arrow_parameter_in_scope_chain_.
IsArrowHeadParsingScope()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::IsArrowHeadParsingScope () const [inline], [private]
Definition at line 326 of file expression-scope.h.
                                       {
    return base::IsInRange(type_, kMaybeArrowParameterDeclaration,
                           kMaybeAsyncArrowParameterDeclaration);
  }
References v8::internal::ExpressionScope< Types >::kMaybeArrowParameterDeclaration, v8::internal::ExpressionScope< Types >::kMaybeAsyncArrowParameterDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::ExpressionScope< Types >::AsArrowHeadParsingScope(), v8::internal::ExpressionScope< Types >::RecordNonSimpleParameter(), and v8::internal::ExpressionScope< Types >::RecordThisUse().
IsAsyncArrowHeadParsingScope()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::IsAsyncArrowHeadParsingScope () const [inline], [protected]
Definition at line 301 of file expression-scope.h.
                                            {
    return type_ == kMaybeAsyncArrowParameterDeclaration;
  }
References v8::internal::ExpressionScope< Types >::kMaybeAsyncArrowParameterDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::kind().
IsCertainlyDeclaration()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::IsCertainlyDeclaration () const [inline]
Definition at line 222 of file expression-scope.h.
                                      {
    return base::IsInRange(type_, kParameterDeclaration, kLexicalDeclaration);
  }
References v8::internal::ExpressionScope< Types >::kLexicalDeclaration, v8::internal::ExpressionScope< Types >::kParameterDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::ArrowHeadParsingScope(), v8::internal::ExpressionScope< Types >::IsCertainlyPattern(), and v8::internal::ExpressionScope< Types >::RecordDeclarationError().
IsCertainlyParameterDeclaration()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::IsCertainlyParameterDeclaration () const [inline], [private]
Definition at line 339 of file expression-scope.h.
                                               {
    return type_ == kParameterDeclaration;
  }
References v8::internal::ExpressionScope< Types >::kParameterDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::ExpressionScope< Types >::AsParameterDeclarationParsingScope(), v8::internal::ExpressionScope< Types >::RecordParameterInitializerError(), and v8::internal::ExpressionScope< Types >::RecordStrictModeParameterError().
IsCertainlyPattern()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::IsCertainlyPattern () const [inline], [private]
Definition at line 330 of file expression-scope.h.
{ return IsCertainlyDeclaration(); }
References v8::internal::ExpressionScope< Types >::IsCertainlyDeclaration().
Referenced by v8::internal::ExpressionScope< Types >::RecordPatternError().
IsLexicalDeclaration()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::IsLexicalDeclaration () const [inline], [protected]
Definition at line 300 of file expression-scope.h.
{ return type_ == kLexicalDeclaration; }
References v8::internal::ExpressionScope< Types >::kLexicalDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::VariableDeclarationParsingScope< Types >::Declare().
IsVarDeclaration()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::IsVarDeclaration () const [inline], [protected]
Definition at line 304 of file expression-scope.h.
{ return type_ == kVarDeclaration; }
Referenced by v8::internal::ExpressionScope< Types >::NewVariable().
IsVariableDeclaration()
template<typename Types >
bool v8::internal::ExpressionScope< Types >::IsVariableDeclaration () const [inline], [protected]
Definition at line 297 of file expression-scope.h.
                                     {
    return base::IsInRange(type_, kVarDeclaration, kLexicalDeclaration);
  }
References v8::internal::ExpressionScope< Types >::kLexicalDeclaration, v8::internal::ExpressionScope< Types >::kVarDeclaration, and v8::internal::ExpressionScope< Types >::type_.
Referenced by v8::internal::ExpressionScope< Types >::AsVariableDeclarationParsingScope().
MarkIdentifierAsAssigned()
template<typename Types >
void v8::internal::ExpressionScope< Types >::MarkIdentifierAsAssigned () [inline]
Definition at line 118 of file expression-scope.h.
                                  {
    if (!CanBeExpression()) return;
    AsExpressionParsingScope()->MarkIdentifierAsAssigned();
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), and v8::internal::ExpressionScope< Types >::CanBeExpression().
MergeVariableList()
template<typename Types >
void v8::internal::ExpressionScope< Types >::MergeVariableList (ScopedList< std::pair< VariableProxy *, int >> * variable_list) [inline]
Definition at line 93 of file expression-scope.h.
                                                               {
    if (!CanBeExpression()) return;
    // Merged variables come from a CanBeDeclaration expression scope, and
    // weren't added as unresolved references to the variable scope yet. Add
    // them to the variable scope on the boundary where it becomes clear they
    // aren't declarations. We explicitly delay declaring the variables up to
    // that point to avoid trying to add them to the unresolved list multiple
    // times, e.g., for (((a))).
    if (!CanBeDeclaration()) {
      for (auto& proxy_initializer_pair : *variable_list) {
        VariableProxy* proxy = proxy_initializer_pair.first;
        this->parser()->scope()->AddUnresolved(proxy);
      }
    }
    variable_list->MergeInto(AsExpressionParsingScope()->variable_list());
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), v8::internal::ExpressionScope< Types >::CanBeDeclaration(), v8::internal::ExpressionScope< Types >::CanBeExpression(), and v8::internal::ExpressionScope< Types >::parser().
Referenced by v8::internal::ArrowHeadParsingScope< Types >::ValidateExpression().
NewVariable()
template<typename Types >
VariableProxy* v8::internal::ExpressionScope< Types >::NewVariable (const AstRawString * name, int pos = kNoSourcePosition) [inline]
Definition at line 52 of file expression-scope.h.
                                                          {
    VariableProxy* result = parser_->NewRawVariable(name, pos);
    if (CanBeExpression()) {
      AsExpressionParsingScope()->TrackVariable(result);
    } else {
      Variable* var = Declare(name, pos);
      if (IsVarDeclaration()) {
        bool passed_through_with = false;
        for (Scope* scope = parser()->scope(); !scope->is_declaration_scope();
             scope = scope->outer_scope()) {
          if (scope->is_with_scope()) {
            passed_through_with = true;
          } else if (scope->is_catch_scope()) {
            Variable* masking_var = scope->LookupLocal(name);
            // If a variable is declared in a catch scope with a masking
            // catch-declared variable, the initializing assignment is an
            // assignment to the catch-declared variable instead.
            // https://tc39.es/ecma262/#sec-variablestatements-in-catch-blocks
            if (masking_var != nullptr) {
              result->set_is_assigned();
              if (passed_through_with) break;
              result->BindTo(masking_var);
              masking_var->SetMaybeAssigned();
              return result;
            }
          }
        }
        if (passed_through_with) {
          // If a variable is declared in a with scope, the initializing
          // assignment might target a with-declared variable instead.
          parser()->scope()->AddUnresolved(result);
          return result;
        }
      }
      DCHECK_NOT_NULL(var);
      result->BindTo(var);
    }
    return result;
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), v8::internal::ExpressionScope< Types >::CanBeExpression(), DCHECK_NOT_NULL, v8::internal::ExpressionScope< Types >::Declare(), v8::internal::ExpressionScope< Types >::IsVarDeclaration(), v8::internal::name, v8::internal::ExpressionScope< Types >::parser(), v8::internal::ExpressionScope< Types >::parser_, v8::base::internal::result, and v8::internal::Variable::SetMaybeAssigned().
operator=()
template<typename Types >
ExpressionScope& v8::internal::ExpressionScope< Types >::operator= (const ExpressionScope< Types > &) [delete]
parent()
template<typename Types >
ExpressionScope* v8::internal::ExpressionScope< Types >::parent () const [inline], [protected]
Definition at line 254 of file expression-scope.h.
{ return parent_; }
References v8::internal::ExpressionScope< Types >::parent_.
Referenced by v8::internal::ExpressionParsingScope< Types >::RecordAsyncArrowParametersError(), v8::internal::ExpressionScope< Types >::RecordParameterInitializerError(), v8::internal::ExpressionScope< Types >::RecordThisUse(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateExpression().
parser()
template<typename Types >
ParserT* v8::internal::ExpressionScope< Types >::parser () const [inline], [protected]
Definition at line 253 of file expression-scope.h.
{ return parser_; }
References v8::internal::ExpressionScope< Types >::parser_.
Referenced by v8::internal::VariableDeclarationParsingScope< Types >::Declare(), v8::internal::ParameterDeclarationParsingScope< Types >::Declare(), v8::internal::ExpressionScope< Types >::ExpressionScope(), v8::internal::ExpressionScope< Types >::MergeVariableList(), v8::internal::ExpressionScope< Types >::NewVariable(), v8::internal::ExpressionParsingScope< Types >::TrackVariable(), v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope(), v8::internal::ExpressionParsingScope< Types >::ValidateAndRewriteReference(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateExpression().
RecordAsyncArrowParametersError()
template<typename Types >
void v8::internal::ExpressionScope< Types >::RecordAsyncArrowParametersError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 137 of file expression-scope.h.
                                                                {
    // Only ambiguous scopes (ExpressionParsingScope, *ArrowHeadParsingScope)
    // need to propagate errors to a possible kAsyncArrowHeadParsingScope, so
    // immediately return if the current scope is not ambiguous.
    if (!CanBeExpression()) return;
    AsExpressionParsingScope()->RecordAsyncArrowParametersError(loc, message);
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), v8::internal::ExpressionScope< Types >::CanBeExpression(), and v8::internal::loc.
RecordDeclarationError()
template<typename Types >
void v8::internal::ExpressionScope< Types >::RecordDeclarationError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 199 of file expression-scope.h.
                                                       {
    if (!CanBeDeclaration()) return;
    if (IsCertainlyDeclaration()) {
      Report(loc, message);
    } else {
      AsArrowHeadParsingScope()->RecordDeclarationError(loc, message);
    }
  }
References v8::internal::ExpressionScope< Types >::AsArrowHeadParsingScope(), v8::internal::ExpressionScope< Types >::CanBeDeclaration(), v8::internal::ExpressionScope< Types >::IsCertainlyDeclaration(), v8::internal::loc, and v8::internal::ExpressionScope< Types >::Report().
RecordExpressionError()
template<typename Types >
void v8::internal::ExpressionScope< Types >::RecordExpressionError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 209 of file expression-scope.h.
                                                      {
    if (!CanBeExpression()) return;
    // TODO(verwaest): Non-assigning expression?
    // if (IsCertainlyExpression()) Report(loc, message);
    AsExpressionParsingScope()->RecordExpressionError(loc, message);
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), v8::internal::ExpressionScope< Types >::CanBeExpression(), and v8::internal::loc.
RecordNonSimpleParameter()
template<typename Types >
void v8::internal::ExpressionScope< Types >::RecordNonSimpleParameter () [inline]
Definition at line 217 of file expression-scope.h.
                                  {
    if (!IsArrowHeadParsingScope()) return;
    AsArrowHeadParsingScope()->RecordNonSimpleParameter();
  }
References v8::internal::ExpressionScope< Types >::AsArrowHeadParsingScope(), and v8::internal::ExpressionScope< Types >::IsArrowHeadParsingScope().
RecordParameterInitializerError()
template<typename Types >
void v8::internal::ExpressionScope< Types >::RecordParameterInitializerError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 148 of file expression-scope.h.
                                                                {
    ExpressionScope* scope = this;
    while (!scope->IsCertainlyParameterDeclaration()) {
      if (!has_possible_parameter_in_scope_chain_) return;
      if (scope->CanBeParameterDeclaration()) {
        scope->AsArrowHeadParsingScope()->RecordDeclarationError(loc, message);
      }
      scope = scope->parent();
      if (scope == nullptr) return;
    }
    Report(loc, message);
  }
References v8::internal::ExpressionScope< Types >::AsArrowHeadParsingScope(), v8::internal::ExpressionScope< Types >::CanBeParameterDeclaration(), v8::internal::ExpressionScope< Types >::has_possible_parameter_in_scope_chain_, v8::internal::ExpressionScope< Types >::IsCertainlyParameterDeclaration(), v8::internal::loc, v8::internal::ExpressionScope< Types >::parent(), and v8::internal::ExpressionScope< Types >::Report().
RecordPatternError()
template<typename Types >
void v8::internal::ExpressionScope< Types >::RecordPatternError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 172 of file expression-scope.h.
                                                   {
    // TODO(verwaest): Non-assigning expression?
    if (IsCertainlyPattern()) {
      Report(loc, message);
    } else {
      AsExpressionParsingScope()->RecordPatternError(loc, message);
    }
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), v8::internal::ExpressionScope< Types >::IsCertainlyPattern(), v8::internal::loc, and v8::internal::ExpressionScope< Types >::Report().
RecordStrictModeParameterError()
template<typename Types >
void v8::internal::ExpressionScope< Types >::RecordStrictModeParameterError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 182 of file expression-scope.h.
                                                               {
    DCHECK_IMPLIES(!has_error(), loc.IsValid());
    if (!CanBeParameterDeclaration()) return;
    if (IsCertainlyParameterDeclaration()) {
      if (is_strict(parser_->language_mode())) {
        Report(loc, message);
      } else {
        parser_->parameters_->set_strict_parameter_error(loc, message);
      }
    } else {
      parser_->next_arrow_function_info_.strict_parameter_error_location = loc;
      parser_->next_arrow_function_info_.strict_parameter_error_message =
          message;
    }
  }
References v8::internal::ExpressionScope< Types >::CanBeParameterDeclaration(), DCHECK_IMPLIES, v8::internal::is_strict(), v8::internal::ExpressionScope< Types >::IsCertainlyParameterDeclaration(), v8::internal::loc, v8::internal::ExpressionScope< Types >::parser_, and v8::internal::ExpressionScope< Types >::Report().
RecordThisUse()
template<typename Types >
void v8::internal::ExpressionScope< Types >::RecordThisUse () [inline]
Definition at line 162 of file expression-scope.h.
                       {
    ExpressionScope* scope = this;
    do {
      if (scope->IsArrowHeadParsingScope()) {
        scope->AsArrowHeadParsingScope()->RecordThisUse();
      }
      scope = scope->parent();
    } while (scope != nullptr);
  }
References v8::internal::ExpressionScope< Types >::AsArrowHeadParsingScope(), v8::internal::ExpressionScope< Types >::IsArrowHeadParsingScope(), and v8::internal::ExpressionScope< Types >::parent().
Report()
template<typename Types >
void v8::internal::ExpressionScope< Types >::Report (const Scanner::Location & loc, MessageTemplate message) const [inline], [protected]
Definition at line 256 of file expression-scope.h.
                                                                         {
    parser_->ReportMessageAt(loc, message);
  }
References v8::internal::loc, and v8::internal::ExpressionScope< Types >::parser_.
Referenced by v8::internal::ExpressionScope< Types >::RecordDeclarationError(), v8::internal::ExpressionScope< Types >::RecordParameterInitializerError(), v8::internal::ExpressionScope< Types >::RecordPatternError(), v8::internal::ExpressionScope< Types >::RecordStrictModeParameterError(), v8::internal::ExpressionParsingScope< Types >::Report(), v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope(), and v8::internal::ExpressionParsingScope< Types >::ValidatePattern().
SetInitializers()
template<typename Types >
int v8::internal::ExpressionScope< Types >::SetInitializers (int variable_index, int peek_position) [inline]
Definition at line 226 of file expression-scope.h.
                                                             {
    if (CanBeExpression()) {
      return AsExpressionParsingScope()->SetInitializers(variable_index,
                                                         peek_position);
    }
    return variable_index;
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), and v8::internal::ExpressionScope< Types >::CanBeExpression().
ValidateAsExpression()
template<typename Types >
void v8::internal::ExpressionScope< Types >::ValidateAsExpression () [inline]
Definition at line 129 of file expression-scope.h.
                              {
    if (!CanBeExpression()) return;
    AsExpressionParsingScope()->ValidateExpression();
    AsExpressionParsingScope()->ClearPatternError();
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), and v8::internal::ExpressionScope< Types >::CanBeExpression().
ValidateAsPattern()
template<typename Types >
void v8::internal::ExpressionScope< Types >::ValidateAsPattern (ExpressionT expression, int begin, int end) [inline]
Definition at line 123 of file expression-scope.h.
                                                                     {
    if (!CanBeExpression()) return;
    AsExpressionParsingScope()->ValidatePattern(expression, begin, end);
    AsExpressionParsingScope()->ClearExpressionError();
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), v8::internal::compiler::begin(), v8::internal::ExpressionScope< Types >::CanBeExpression(), and v8::internal::compiler::end().
Friends And Related Function Documentation
AccumulationScope< Types >
template<typename Types >
friend class AccumulationScope< Types > [friend]
Definition at line 304 of file expression-scope.h.
ExpressionParsingScope< Types >
template<typename Types >
friend class ExpressionParsingScope< Types > [friend]
Definition at line 304 of file expression-scope.h.
Member Data Documentation
has_possible_arrow_parameter_in_scope_chain_
template<typename Types >
bool v8::internal::ExpressionScope< Types >::has_possible_arrow_parameter_in_scope_chain_ [private]
Definition at line 347 of file expression-scope.h.
Referenced by v8::internal::ExpressionScope< Types >::has_possible_arrow_parameter_in_scope_chain().
has_possible_parameter_in_scope_chain_
template<typename Types >
bool v8::internal::ExpressionScope< Types >::has_possible_parameter_in_scope_chain_ [private]
Definition at line 346 of file expression-scope.h.
Referenced by v8::internal::ExpressionScope< Types >::RecordParameterInitializerError().
parent_
template<typename Types >
ExpressionScope<Types>* v8::internal::ExpressionScope< Types >::parent_ [private]
Definition at line 344 of file expression-scope.h.
Referenced by v8::internal::ExpressionScope< Types >::parent(), and v8::internal::ExpressionScope< Types >::~ExpressionScope().
parser_
template<typename Types >
ParserT* v8::internal::ExpressionScope< Types >::parser_ [private]
Definition at line 343 of file expression-scope.h.
Referenced by v8::internal::ExpressionScope< Types >::NewVariable(), v8::internal::ExpressionScope< Types >::parser(), v8::internal::ExpressionScope< Types >::RecordStrictModeParameterError(), v8::internal::ExpressionScope< Types >::Report(), and v8::internal::ExpressionScope< Types >::~ExpressionScope().
type_
template<typename Types >
ScopeType v8::internal::ExpressionScope< Types >::type_ [private]
Definition at line 345 of file expression-scope.h.
Referenced by v8::internal::ExpressionScope< Types >::CanBeArrowParameterDeclaration(), v8::internal::ExpressionScope< Types >::CanBeDeclaration(), v8::internal::ExpressionScope< Types >::CanBeExpression(), v8::internal::ExpressionScope< Types >::CanBeParameterDeclaration(), v8::internal::ExpressionScope< Types >::Declare(), v8::internal::ExpressionScope< Types >::IsArrowHeadParsingScope(), v8::internal::ExpressionScope< Types >::IsAsyncArrowHeadParsingScope(), v8::internal::ExpressionScope< Types >::IsCertainlyDeclaration(), v8::internal::ExpressionScope< Types >::IsCertainlyParameterDeclaration(), v8::internal::ExpressionScope< Types >::IsLexicalDeclaration(), and v8::internal::ExpressionScope< Types >::IsVariableDeclaration().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/expression-scope.h