v8::internal::WasmTypeInfo Class Reference
#include <wasm-objects.h>
Public Member Functions
wasm::CanonicalValueType type () const
wasm::CanonicalTypeIndex type_index () const
wasm::CanonicalValueType element_type () const
Detailed Description
Definition at line 1378 of file wasm-objects.h.
Member Function Documentation
element_type()
wasm::CanonicalValueType v8::internal::WasmTypeInfo::element_type () const [inline]
Definition at line 566 of file wasm-objects-inl.h.
                                                        {
  return wasm::CanonicalValueType::FromRawBitField(canonical_element_type());
}
References v8::internal::wasm::CanonicalValueType::FromRawBitField().
type()
wasm::CanonicalValueType v8::internal::WasmTypeInfo::type () const [inline]
Definition at line 558 of file wasm-objects-inl.h.
                                                {
  return wasm::CanonicalValueType::FromRawBitField(canonical_type());
}
References v8::internal::wasm::CanonicalValueType::FromRawBitField().
Referenced by type_index().
type_index()
wasm::CanonicalTypeIndex v8::internal::WasmTypeInfo::type_index () const [inline]
Definition at line 562 of file wasm-objects-inl.h.
                                                      {
  return type().ref_index();
}
References v8::internal::wasm::CanonicalValueType::ref_index(), and type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h