v8::internal::StringTableKey Class Reference
#include <string-table.h>
Public Member Functions
virtual ~StringTableKey ()=default
StringTableKey (uint32_t raw_hash_field, uint32_t length)
uint32_t raw_hash_field () const
uint32_t hash () const
uint32_t length () const
Protected Member Functions
void set_raw_hash_field (uint32_t raw_hash_field)
Private Attributes
uint32_t raw_hash_field_ = 0
uint32_t length_
Detailed Description
Definition at line 20 of file string-table.h.
Constructor & Destructor Documentation
 StringTableKey()
virtual v8::internal::StringTableKey::~StringTableKey () [virtual], [default]
StringTableKey()
v8::internal::StringTableKey::StringTableKey (uint32_t raw_hash_field, uint32_t length) [inline]
Definition at line 17 of file string-table-inl.h.
    : raw_hash_field_(raw_hash_field), length_(length) {}
Member Function Documentation
hash()
uint32_t v8::internal::StringTableKey::hash () const [inline]
Definition at line 24 of file string-table-inl.h.
                                    {
  return Name::HashBits::decode(raw_hash_field_);
}
References v8::base::BitField< T, shift, size, U >::decode(), and raw_hash_field_.
Referenced by v8::internal::InternalizedStringKey::InternalizedStringKey().
length()
uint32_t v8::internal::StringTableKey::length () const [inline]
Definition at line 31 of file string-table.h.
{ return length_; }
References length_.
Referenced by v8::internal::SeqSubStringKey< SeqString >::IsMatch(), v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion(), v8::internal::InternalizedStringKey::PrepareForInsertion(), and v8::internal::SeqSubStringKey< SeqString >::SeqSubStringKey().
raw_hash_field()
uint32_t v8::internal::StringTableKey::raw_hash_field () const [inline]
Definition at line 25 of file string-table.h.
                                  {
    DCHECK_NE(0, raw_hash_field_);
    return raw_hash_field_;
  }
References DCHECK_NE, and raw_hash_field_.
Referenced by v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion(), v8::internal::InternalizedStringKey::PrepareForInsertion(), v8::internal::SequentialStringKey< Char >::PrepareForInsertion(), v8::internal::SeqSubStringKey< SeqString >::SeqSubStringKey(), and set_raw_hash_field().
set_raw_hash_field()
void v8::internal::StringTableKey::set_raw_hash_field (uint32_t raw_hash_field) [inline], [protected]
Definition at line 20 of file string-table-inl.h.
                                                               {
  raw_hash_field_ = raw_hash_field;
}
References raw_hash_field(), and raw_hash_field_.
Referenced by v8::internal::SeqSubStringKey< SeqString >::SeqSubStringKey().
Member Data Documentation
length_
uint32_t v8::internal::StringTableKey::length_ [private]
Definition at line 38 of file string-table.h.
Referenced by length().
raw_hash_field_
uint32_t v8::internal::StringTableKey::raw_hash_field_ = 0 [private]
Definition at line 37 of file string-table.h.
Referenced by hash(), raw_hash_field(), and set_raw_hash_field().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string-table.h
/mnt/V8SourceCode/src/objects/string-table-inl.h