v8::internal::JSTemporalPlainYearMonth Class Reference
#include <js-temporal-objects.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainYearMonth > Constructor (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > iso_year, DirectHandle< Object > iso_month, DirectHandle< Object > calendar_like, DirectHandle< Object > reference_iso_day)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainYearMonth > From (Isolate *isolate, DirectHandle< Object > item, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Smi > Compare (Isolate *isolate, DirectHandle< Object > one, DirectHandle< Object > two)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Oddball > Equals (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > other)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainYearMonth > With (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > temporal_year_month_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > ToPlainDate (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > item)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainYearMonth > Add (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainYearMonth > Subtract (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Until (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Since (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToJSON (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > year_month)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleString (Isolate *isolate, DirectHandle< JSTemporalPlainYearMonth > plain_date, DirectHandle< Object > locales, DirectHandle< Object > options)
Detailed Description
Definition at line 630 of file js-temporal-objects.h.
Member Function Documentation
Add()
MaybeDirectHandle< JSTemporalPlainYearMonth > v8::internal::JSTemporalPlainYearMonth::Add (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 2498 of file js-temporal-objects.cc.
                                                                               {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Compare()
MaybeDirectHandle< Smi > v8::internal::JSTemporalPlainYearMonth::Compare (Isolate * isolate, DirectHandle< Object > one, DirectHandle< Object > two) [static]
Definition at line 2483 of file js-temporal-objects.cc.
                                  {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Constructor()
MaybeDirectHandle< JSTemporalPlainYearMonth > v8::internal::JSTemporalPlainYearMonth::Constructor (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > iso_year, DirectHandle< Object > iso_month, DirectHandle< Object > calendar_like, DirectHandle< Object > reference_iso_day) [static]
Definition at line 2405 of file js-temporal-objects.cc.
                                                {
  // 1. If NewTarget is undefined, then
  if (IsUndefined(*new_target)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kMethodInvokedOnWrongType,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "Temporal.PlainYearMonth")));
  }
  // 2. If referenceISODay is undefined, then
  // a. Set referenceISODay to 1𝔽.
  double reference_iso_day = 1.0;
  // 3. Let y be ? ToIntegerWithTruncation(isoYear).
  double y = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, y, temporal::ToIntegerWithTruncation(isolate, iso_year_obj),
      kNullMaybeHandle);
  // 4. Let m be ? ToIntegerWithTruncation(isoMonth).
  double m = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, m, temporal::ToIntegerWithTruncation(isolate, iso_month_obj),
      kNullMaybeHandle);
  // 5. If calendar is undefined, set calendar to "iso8601".
  temporal_rs::AnyCalendarKind calendar = temporal_rs::AnyCalendarKind::Iso;
  if (!IsUndefined(*calendar_like)) {
    // 6. If calendar is not a String, throw a TypeError exception.
    if (!IsString(*calendar_like)) {
      THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR());
    }
    // 7. Set calendar to ?CanonicalizeCalendar(calendar).
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, calendar,
        temporal::CanonicalizeCalendar(isolate, Cast<String>(calendar_like)),
        kNullMaybeHandle);
  }
  if (!IsUndefined(*reference_iso_day_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, reference_iso_day,
        temporal::ToIntegerWithTruncation(isolate, reference_iso_day_obj),
        kNullMaybeHandle);
  }
  // 9. If IsValidISODate(y, m, ref) is false, throw a RangeError exception.
  if (!temporal::IsValidIsoDate(y, m, reference_iso_day)) {
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR());
  }
  // Rest of the steps handled in Rust.
  // These static_casts are fine to perform since IsValid* will have constrained
  // these values to range already.
  // https://github.com/boa-dev/temporal/issues/334 for moving this logic into
  // the Rust code.
  auto rust_object = temporal_rs::PlainYearMonth::try_new_with_overflow(
      static_cast<int32_t>(y), static_cast<uint8_t>(m),
      static_cast<uint8_t>(reference_iso_day), calendar,
      temporal_rs::ArithmeticOverflow::Reject);
  return ConstructRustWrappingType<JSTemporalPlainYearMonth>(
      isolate, target, new_target, std::move(rust_object));
}
References v8::internal::temporal::CanonicalizeCalendar(), v8::internal::Isolate::factory(), v8::internal::temporal::IsValidIsoDate(), v8::internal::kNullMaybeHandle, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR, v8::internal::temporal::ToIntegerWithTruncation(), and v8::internal::y.
Referenced by v8::internal::TEMPORAL_GET_RUST().
Equals()
MaybeDirectHandle< Oddball > v8::internal::JSTemporalPlainYearMonth::Equals (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > other) [static]
Definition at line 2490 of file js-temporal-objects.cc.
                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
From()
MaybeDirectHandle< JSTemporalPlainYearMonth > v8::internal::JSTemporalPlainYearMonth::From (Isolate * isolate, DirectHandle< Object > item, DirectHandle< Object > options) [static]
Definition at line 2476 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Since()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalPlainYearMonth::Since (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 2520 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Subtract()
MaybeDirectHandle< JSTemporalPlainYearMonth > v8::internal::JSTemporalPlainYearMonth::Subtract (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 2505 of file js-temporal-objects.cc.
                                                                               {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToJSON()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainYearMonth::ToJSON (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month) [static]
Definition at line 2544 of file js-temporal-objects.cc.
                                                                         {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToLocaleString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainYearMonth::ToLocaleString (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > plain_date, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 2557 of file js-temporal-objects.cc.
                                                                {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainDate()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainYearMonth::ToPlainDate (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > item) [static]
Definition at line 2537 of file js-temporal-objects.cc.
                                   {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainYearMonth::ToString (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > options) [static]
Definition at line 2550 of file js-temporal-objects.cc.
                                  {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Until()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalPlainYearMonth::Until (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 2512 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
With()
MaybeDirectHandle< JSTemporalPlainYearMonth > v8::internal::JSTemporalPlainYearMonth::With (Isolate * isolate, DirectHandle< JSTemporalPlainYearMonth > year_month, DirectHandle< Object > temporal_year_month_like, DirectHandle< Object > options) [static]
Definition at line 2528 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-temporal-objects.h
/mnt/V8SourceCode/src/objects/js-temporal-objects.cc