v8::internal::compiler::turboshaft::LoopLabel< Ts > Class Template Reference
#include <assembler.h>
Public Types
using values_t = typename super::values_t
Public Member Functions
template<typename Reducer >
LoopLabel (Reducer *reducer)
LoopLabel (LoopLabel &&other) V8_NOEXCEPT
Block * loop_header () const
template<typename A >
void Goto (A &assembler, const values_t &values)
template<typename A >
void GotoIf (A &assembler, OpIndex condition, BranchHint hint, const values_t &values)
template<typename A >
void GotoIfNot (A &assembler, OpIndex condition, BranchHint hint, const values_t &values)
template<typename A >
base::prepend_tuple_type< bool, values_t > Bind (A &assembler)
template<typename A >
base::prepend_tuple_type< bool, values_t > BindLoop (A &assembler)
template<typename A >
void EndLoop (A &assembler)
Private Types
using super = LabelBase< true, Ts... >
using BlockData = typename super::BlockData
Private Member Functions
LoopLabel (const LoopLabel &)=delete
LoopLabel & operator= (const LoopLabel &)=delete
template<typename A >
void FixLoopPhis (A &assembler, const typename super::values_t &values)
template<size_t I, typename A >
void FixLoopPhi (A &assembler, const typename super::values_t &values)
Static Private Member Functions
template<typename A >
static values_t MaterializeLoopPhis (A &assembler, BlockData &data)
template<typename A , size_t... indices>
static values_t MaterializeLoopPhisImpl (A &assembler, BlockData &data, std::index_sequence< indices... >)
Private Attributes
BlockData loop_header_data_
std::optional< values_t > pending_loop_phis_
Additional Inherited Members
Detailed Description
template<typename... Ts>
class v8::internal::compiler::turboshaft::LoopLabel< Ts >
Definition at line 544 of file assembler.h.
Member Typedef Documentation
BlockData
template<typename... Ts>
using v8::internal::compiler::turboshaft::LoopLabel< Ts >::BlockData = typename super::BlockData [private]
Definition at line 546 of file assembler.h.
super
template<typename... Ts>
using v8::internal::compiler::turboshaft::LoopLabel< Ts >::super = LabelBase<true, Ts...> [private]
Definition at line 545 of file assembler.h.
values_t
template<typename... Ts>
using v8::internal::compiler::turboshaft::LoopLabel< Ts >::values_t = typename super::values_t
Definition at line 552 of file assembler.h.
Constructor & Destructor Documentation
LoopLabel() [1/3]
template<typename... Ts>
v8::internal::compiler::turboshaft::LoopLabel< Ts >::LoopLabel (const LoopLabel< Ts > &) [private], [delete]
LoopLabel() [2/3]
template<typename... Ts>
template<typename Reducer >
v8::internal::compiler::turboshaft::LoopLabel< Ts >::LoopLabel (Reducer * reducer) [inline], [explicit]
Definition at line 554 of file assembler.h.
      : super(reducer->Asm().NewBlock()),
        loop_header_data_{reducer->Asm().NewLoopHeader()} {}
LoopLabel() [3/3]
template<typename... Ts>
v8::internal::compiler::turboshaft::LoopLabel< Ts >::LoopLabel (LoopLabel< Ts > && other) [inline]
Definition at line 558 of file assembler.h.
      : super(std::move(other)),
        loop_header_data_(std::move(other.loop_header_data_)),
        pending_loop_phis_(std::move(other.pending_loop_phis_)) {}
Member Function Documentation
Bind()
template<typename... Ts>
template<typename A >
base::prepend_tuple_type<bool, values_t> v8::internal::compiler::turboshaft::LoopLabel< Ts >::Bind (A & assembler) [inline]
Definition at line 626 of file assembler.h.
                                                            {
    // LoopLabels must not be bound using `Bind`, but with `Loop`.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
BindLoop()
template<typename... Ts>
template<typename A >
base::prepend_tuple_type<bool, values_t> v8::internal::compiler::turboshaft::LoopLabel< Ts >::BindLoop (A & assembler) [inline]
Definition at line 632 of file assembler.h.
                                                                {
    DCHECK(!loop_header_data_.block->IsBound());
    if (!assembler.Bind(loop_header_data_.block)) {
      return std::tuple_cat(std::tuple{false}, values_t{});
    }
    DCHECK_EQ(loop_header_data_.block, assembler.current_block());
    values_t pending_loop_phis =
        MaterializeLoopPhis(assembler, loop_header_data_);
    pending_loop_phis_ = pending_loop_phis;
    return std::tuple_cat(std::tuple{true}, pending_loop_phis);
  }
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_While().
EndLoop()
template<typename... Ts>
template<typename A >
void v8::internal::compiler::turboshaft::LoopLabel< Ts >::EndLoop (A & assembler) [inline]
Definition at line 645 of file assembler.h.
                             {
    // First, we need to bind the backedge block.
    auto bind_result = this->super::Bind(assembler);
    // `Bind` returns a tuple with a `bool` as first entry that indicates
    // whether the block was bound. The rest of the tuple contains the phi
    // values. Check if this block was bound (aka is reachable).
    if (std::get<0>(bind_result)) {
      // The block is bound.
      DCHECK_EQ(assembler.current_block(), this->super::block());
      // Now we build a jump from this block to the loop header.
      // Remove the "bound"-flag from the beginning of the tuple.
      auto values = base::tuple_drop<1>(bind_result);
      assembler.Goto(loop_header_data_.block);
      // Finalize Phis in the loop header.
      FixLoopPhis(assembler, values);
    }
    assembler.FinalizeLoop(loop_header_data_.block);
  }
References DCHECK_EQ, and v8::internal::this.
FixLoopPhi()
template<typename... Ts>
template<size_t I, typename A >
void v8::internal::compiler::turboshaft::LoopLabel< Ts >::FixLoopPhi (A & assembler, const typename super::values_t & values) [inline], [private]
Definition at line 696 of file assembler.h.
                                                                      {
    if constexpr (I < std::tuple_size_v<typename super::values_t>) {
      OpIndex phi_index = std::get<I>(*pending_loop_phis_);
      PendingLoopPhiOp& pending_loop_phi =
          assembler.output_graph()
              .Get(phi_index)
              .template Cast<PendingLoopPhiOp>();
      DCHECK_EQ(pending_loop_phi.first(),
                std::get<I>(loop_header_data_.recorded_values)[0]);
      assembler.output_graph().template Replace<PhiOp>(
          phi_index,
          base::VectorOf<OpIndex>(
              {pending_loop_phi.first(), std::get<I>(values)}),
          pending_loop_phi.rep);
      FixLoopPhi<I + 1>(assembler, values);
    }
  }
References DCHECK_EQ, v8::internal::compiler::turboshaft::PendingLoopPhiOp::first(), v8::internal::I, and v8::internal::compiler::turboshaft::PendingLoopPhiOp::rep.
FixLoopPhis()
template<typename... Ts>
template<typename A >
void v8::internal::compiler::turboshaft::LoopLabel< Ts >::FixLoopPhis (A & assembler, const typename super::values_t & values) [inline], [private]
Definition at line 687 of file assembler.h.
                                                                       {
    DCHECK(loop_header_data_.block->IsBound());
    DCHECK(loop_header_data_.block->IsLoop());
    DCHECK_LE(1, loop_header_data_.predecessors.size());
    DCHECK_LE(loop_header_data_.predecessors.size(), 2);
    FixLoopPhi<0>(assembler, values);
  }
References v8::internal::DCHECK(), and DCHECK_LE.
Goto()
template<typename... Ts>
template<typename A >
void v8::internal::compiler::turboshaft::LoopLabel< Ts >::Goto (A & assembler, const values_t & values) [inline]
Definition at line 566 of file assembler.h.
                                                  {
    if (assembler.generating_unreachable_operations()) return;
    if (!loop_header_data_.block->IsBound()) {
      // If the loop header is not bound yet, we have the forward edge to the
      // loop.
      DCHECK_EQ(0, loop_header_data_.block->PredecessorCount());
      Block* current_block = assembler.current_block();
      DCHECK_NOT_NULL(current_block);
      assembler.Goto(loop_header_data_.block);
      super::RecordValues(current_block, loop_header_data_, values);
    } else {
      // We have a jump back to the loop header and wire it to the single
      // backedge block.
      this->super::Goto(assembler, values);
    }
  }
References DCHECK_EQ, and DCHECK_NOT_NULL.
GotoIf()
template<typename... Ts>
template<typename A >
void v8::internal::compiler::turboshaft::LoopLabel< Ts >::GotoIf (A & assembler, OpIndex condition, BranchHint hint, const values_t & values) [inline]
Definition at line 584 of file assembler.h.
                                      {
    if (assembler.generating_unreachable_operations()) return;
    if (!loop_header_data_.block->IsBound()) {
      // If the loop header is not bound yet, we have the forward edge to the
      // loop.
      DCHECK_EQ(0, loop_header_data_.block->PredecessorCount());
      Block* current_block = assembler.current_block();
      DCHECK_NOT_NULL(current_block);
      if (assembler.GotoIf(condition, loop_header_data_.block, hint) &
          ConditionalGotoStatus::kGotoDestination) {
        super::RecordValues(current_block, loop_header_data_, values);
      }
    } else {
      // We have a jump back to the loop header and wire it to the single
      // backedge block.
      this->super::GotoIf(assembler, condition, hint, values);
    }
  }
References DCHECK_EQ, DCHECK_NOT_NULL, and v8::internal::compiler::turboshaft::kGotoDestination.
GotoIfNot()
template<typename... Ts>
template<typename A >
void v8::internal::compiler::turboshaft::LoopLabel< Ts >::GotoIfNot (A & assembler, OpIndex condition, BranchHint hint, const values_t & values) [inline]
Definition at line 605 of file assembler.h.
                                         {
    if (assembler.generating_unreachable_operations()) return;
    if (!loop_header_data_.block->IsBound()) {
      // If the loop header is not bound yet, we have the forward edge to the
      // loop.
      DCHECK_EQ(0, loop_header_data_.block->PredecessorCount());
      Block* current_block = assembler.current_block();
      DCHECK_NOT_NULL(current_block);
      if (assembler.GotoIf(condition, loop_header_data_.block, hint) &
          ConditionalGotoStatus::kGotoDestination) {
        super::RecordValues(current_block, loop_header_data_, values);
      }
    } else {
      // We have a jump back to the loop header and wire it to the single
      // backedge block.
      this->super::GotoIfNot(assembler, condition, hint, values);
    }
  }
References DCHECK_EQ, DCHECK_NOT_NULL, and v8::internal::compiler::turboshaft::kGotoDestination.
loop_header()
template<typename... Ts>
Block* v8::internal::compiler::turboshaft::LoopLabel< Ts >::loop_header () const [inline]
Definition at line 563 of file assembler.h.
{ return loop_header_data_.block; }
MaterializeLoopPhis()
template<typename... Ts>
template<typename A >
static values_t v8::internal::compiler::turboshaft::LoopLabel< Ts >::MaterializeLoopPhis (A & assembler, BlockData & data) [inline], [static], [private]
Definition at line 666 of file assembler.h.
                                                                     {
    return MaterializeLoopPhisImpl(assembler, data,
                                   std::make_index_sequence<super::size>());
  }
MaterializeLoopPhisImpl()
template<typename... Ts>
template<typename A , size_t... indices>
static values_t v8::internal::compiler::turboshaft::LoopLabel< Ts >::MaterializeLoopPhisImpl (A & assembler, BlockData & data, std::index_sequence< indices... >) [inline], [static], [private]
Definition at line 672 of file assembler.h.
                                                                         {
    size_t predecessor_count = data.block->PredecessorCount();
    USE(predecessor_count);
    DCHECK_EQ(data.predecessors.size(), predecessor_count);
    // If this label has no values, we don't need any Phis.
    if constexpr (super::size == 0) return typename super::values_t{};
    DCHECK_EQ(predecessor_count, 1);
    auto phis = typename super::values_t{assembler.PendingLoopPhi(
        std::get<indices>(data.recorded_values)[0])...};
    return phis;
  }
References DCHECK_EQ, size(), and USE.
operator=()
template<typename... Ts>
LoopLabel& v8::internal::compiler::turboshaft::LoopLabel< Ts >::operator= (const LoopLabel< Ts > &) [private], [delete]
Member Data Documentation
loop_header_data_
template<typename... Ts>
BlockData v8::internal::compiler::turboshaft::LoopLabel< Ts >::loop_header_data_ [private]
Definition at line 714 of file assembler.h.
pending_loop_phis_
template<typename... Ts>
std::optional<values_t> v8::internal::compiler::turboshaft::LoopLabel< Ts >::pending_loop_phis_ [private]
Definition at line 715 of file assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h