v8::internal::RegExpLookaround::Builder Class Reference
#include <regexp-ast.h>
Public Member Functions
Builder (bool is_positive, RegExpNode *on_success, int stack_pointer_register, int position_register, int capture_register_count=0, int capture_register_start=0)
RegExpNode * on_match_success () const
RegExpNode * ForMatch (RegExpNode *match)
Private Attributes
bool is_positive_
RegExpNode * on_match_success_
RegExpNode * on_success_
int stack_pointer_register_
int position_register_
Detailed Description
Definition at line 686 of file regexp-ast.h.
Constructor & Destructor Documentation
Builder()
v8::internal::RegExpLookaround::Builder::Builder (bool is_positive, RegExpNode * on_success, int stack_pointer_register, int position_register, int capture_register_count = 0, int capture_register_start = 0)
Definition at line 1212 of file regexp-compiler-tonode.cc.
    : is_positive_(is_positive),
      on_success_(on_success),
      stack_pointer_register_(stack_pointer_register),
      position_register_(position_register) {
  if (is_positive_) {
    on_match_success_ = ActionNode::PositiveSubmatchSuccess(
        stack_pointer_register, position_register, capture_register_count,
        capture_register_start, on_success_);
  } else {
    Zone* zone = on_success_->zone();
    on_match_success_ = zone->New<NegativeSubmatchSuccess>(
        stack_pointer_register, position_register, capture_register_count,
        capture_register_start, zone);
  }
}
References is_positive_, v8::internal::Zone::New(), on_match_success_, on_success_, v8::internal::ActionNode::PositiveSubmatchSuccess(), and v8::internal::RegExpNode::zone().
Member Function Documentation
ForMatch()
RegExpNode * v8::internal::RegExpLookaround::Builder::ForMatch (RegExpNode * match)
Definition at line 1233 of file regexp-compiler-tonode.cc.
                                                               {
  if (is_positive_) {
    ActionNode* on_match_success = on_match_success_->AsActionNode();
    return ActionNode::BeginPositiveSubmatch(
        stack_pointer_register_, position_register_, match, on_match_success);
  } else {
    Zone* zone = on_success_->zone();
    // We use a ChoiceNode to represent the negative lookaround. The first
    // alternative is the negative match. On success, the end node backtracks.
    // On failure, the second alternative is tried and leads to success.
    // NegativeLookaroundChoiceNode is a special ChoiceNode that ignores the
    // first exit when calculating quick checks.
    ChoiceNode* choice_node = zone->New<NegativeLookaroundChoiceNode>(
        GuardedAlternative(match), GuardedAlternative(on_success_), zone);
    return ActionNode::BeginNegativeSubmatch(stack_pointer_register_,
                                             position_register_, choice_node);
  }
}
References v8::internal::ActionNode::AsActionNode(), v8::internal::ActionNode::BeginNegativeSubmatch(), v8::internal::ActionNode::BeginPositiveSubmatch(), v8::internal::RegExpLookaround::is_positive_, and v8::internal::Zone::New().
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MatchAndNegativeLookaroundInReadDirection(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::NegativeLookaroundAgainstReadDirectionAndMatch(), and v8::internal::RegExpCompiler::OptionallyStepBackToLeadSurrogate().
on_match_success()
RegExpNode* v8::internal::RegExpLookaround::Builder::on_match_success () const [inline]
Definition at line 691 of file regexp-ast.h.
{ return on_match_success_; }
References on_match_success_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MatchAndNegativeLookaroundInReadDirection(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::NegativeLookaroundAgainstReadDirectionAndMatch(), and v8::internal::RegExpCompiler::OptionallyStepBackToLeadSurrogate().
Member Data Documentation
is_positive_
bool v8::internal::RegExpLookaround::Builder::is_positive_ [private]
Definition at line 695 of file regexp-ast.h.
Referenced by Builder().
on_match_success_
RegExpNode* v8::internal::RegExpLookaround::Builder::on_match_success_ [private]
Definition at line 696 of file regexp-ast.h.
Referenced by Builder(), and on_match_success().
on_success_
RegExpNode* v8::internal::RegExpLookaround::Builder::on_success_ [private]
Definition at line 697 of file regexp-ast.h.
Referenced by Builder().
position_register_
int v8::internal::RegExpLookaround::Builder::position_register_ [private]
Definition at line 699 of file regexp-ast.h.
stack_pointer_register_
int v8::internal::RegExpLookaround::Builder::stack_pointer_register_ [private]
Definition at line 698 of file regexp-ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc