v8::internal::wasm::StreamingDecoder Class Reference
#include <streaming-decoder.h>
Public Types
using MoreFunctionsCanBeSerializedCallback = std::function< void(const std::shared_ptr< NativeModule > &)>
Public Member Functions
virtual ~StreamingDecoder ()=default
virtual void OnBytesReceived (base::Vector< const uint8_t > bytes)=0
virtual void Finish (bool can_use_compiled_module=true)=0
virtual void Abort ()=0
virtual void NotifyCompilationDiscarded ()=0
void SetMoreFunctionsCanBeSerializedCallback (MoreFunctionsCanBeSerializedCallback callback)
void SetCompiledModuleBytes (base::Vector< const uint8_t > bytes)
virtual void NotifyNativeModuleCreated (const std::shared_ptr< NativeModule > &native_module)=0
const std::string & url () const
std::shared_ptr< const std::string > shared_url () const
void SetUrl (base::Vector< const char > url)
Static Public Member Functions
static std::unique_ptr< StreamingDecoder > CreateAsyncStreamingDecoder (std::unique_ptr< StreamingProcessor > processor)
static std::unique_ptr< StreamingDecoder > CreateSyncStreamingDecoder (Isolate *isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, DirectHandle< Context > context, const char *api_method_name_for_errors, std::shared_ptr< CompilationResultResolver > resolver)
Protected Member Functions
bool deserializing () const
Protected Attributes
const std::shared_ptr< std::string > url_ = std::make_shared<std::string>()
MoreFunctionsCanBeSerializedCallback more_functions_can_be_serialized_callback_
base::Vector< const uint8_t > compiled_module_bytes_
Detailed Description
Definition at line 69 of file streaming-decoder.h.
Member Typedef Documentation
MoreFunctionsCanBeSerializedCallback
using v8::internal::wasm::StreamingDecoder::MoreFunctionsCanBeSerializedCallback = std::function<void(const std::shared_ptr<NativeModule>&)>
Definition at line 87 of file streaming-decoder.h.
Constructor & Destructor Documentation
 StreamingDecoder()
virtual v8::internal::wasm::StreamingDecoder::~StreamingDecoder () [virtual], [default]
Member Function Documentation
Abort()
virtual void v8::internal::wasm::StreamingDecoder::Abort () [pure virtual]
Implemented in v8::internal::wasm::SyncStreamingDecoder, and v8::internal::wasm::AsyncStreamingDecoder.
CreateAsyncStreamingDecoder()
std::unique_ptr< StreamingDecoder > v8::internal::wasm::StreamingDecoder::CreateAsyncStreamingDecoder (std::unique_ptr< StreamingProcessor > processor) [static]
Definition at line 771 of file streaming-decoder.cc.
                                                 {
  return std::make_unique<AsyncStreamingDecoder>(std::move(processor));
}
Referenced by v8::internal::wasm::AsyncCompileJob::CreateStreamingDecoder().
CreateSyncStreamingDecoder()
std::unique_ptr< StreamingDecoder > v8::internal::wasm::StreamingDecoder::CreateSyncStreamingDecoder (Isolate * isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, DirectHandle< Context > context, const char * api_method_name_for_errors, std::shared_ptr< CompilationResultResolver > resolver) [static]
Definition at line 103 of file sync-streaming-decoder.cc.
                                                       {
  return std::make_unique<SyncStreamingDecoder>(
      isolate, enabled, std::move(compile_imports), context,
      api_method_name_for_errors, std::move(resolver));
}
Referenced by v8::internal::wasm::WasmEngine::StartStreamingCompilation().
deserializing()
bool v8::internal::wasm::StreamingDecoder::deserializing () const [inline], [protected]
Definition at line 121 of file streaming-decoder.h.
{ return !compiled_module_bytes_.empty(); }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::Finish(), and v8::internal::wasm::AsyncStreamingDecoder::OnBytesReceived().
Finish()
virtual void v8::internal::wasm::StreamingDecoder::Finish (bool can_use_compiled_module = true) [pure virtual]
Implemented in v8::internal::wasm::SyncStreamingDecoder, and v8::internal::wasm::AsyncStreamingDecoder.
NotifyCompilationDiscarded()
virtual void v8::internal::wasm::StreamingDecoder::NotifyCompilationDiscarded () [pure virtual]
Implemented in v8::internal::wasm::SyncStreamingDecoder, and v8::internal::wasm::AsyncStreamingDecoder.
NotifyNativeModuleCreated()
virtual void v8::internal::wasm::StreamingDecoder::NotifyNativeModuleCreated (const std::shared_ptr< NativeModule > & native_module) [pure virtual]
Implemented in v8::internal::wasm::AsyncStreamingDecoder, and v8::internal::wasm::SyncStreamingDecoder.
OnBytesReceived()
virtual void v8::internal::wasm::StreamingDecoder::OnBytesReceived (base::Vector< const uint8_t > bytes) [pure virtual]
Implemented in v8::internal::wasm::SyncStreamingDecoder, and v8::internal::wasm::AsyncStreamingDecoder.
SetCompiledModuleBytes()
void v8::internal::wasm::StreamingDecoder::SetCompiledModuleBytes (base::Vector< const uint8_t > bytes) [inline]
Definition at line 97 of file streaming-decoder.h.
                                                               {
    compiled_module_bytes_ = bytes;
  }
SetMoreFunctionsCanBeSerializedCallback()
void v8::internal::wasm::StreamingDecoder::SetMoreFunctionsCanBeSerializedCallback (MoreFunctionsCanBeSerializedCallback callback) [inline]
Definition at line 90 of file streaming-decoder.h.
                                                     {
    more_functions_can_be_serialized_callback_ = std::move(callback);
  }
SetUrl()
void v8::internal::wasm::StreamingDecoder::SetUrl (base::Vector< const char > url) [inline]
Definition at line 107 of file streaming-decoder.h.
                                          {
    url_->assign(url.begin(), url.size());
  }
References v8::base::Vector< T >::begin(), and v8::base::Vector< T >::size().
shared_url()
std::shared_ptr<const std::string> v8::internal::wasm::StreamingDecoder::shared_url () const [inline]
Definition at line 105 of file streaming-decoder.h.
{ return url_; }
url()
const std::string& v8::internal::wasm::StreamingDecoder::url () const [inline]
Definition at line 104 of file streaming-decoder.h.
{ return *url_; }
Member Data Documentation
compiled_module_bytes_
base::Vector<const uint8_t> v8::internal::wasm::StreamingDecoder::compiled_module_bytes_ [protected]
Definition at line 128 of file streaming-decoder.h.
Referenced by v8::internal::wasm::AsyncStreamingDecoder::Finish().
more_functions_can_be_serialized_callback_
MoreFunctionsCanBeSerializedCallback v8::internal::wasm::StreamingDecoder::more_functions_can_be_serialized_callback_ [protected]
Definition at line 125 of file streaming-decoder.h.
Referenced by v8::internal::wasm::AsyncStreamingDecoder::NotifyNativeModuleCreated().
url_
const std::shared_ptr<std::string> v8::internal::wasm::StreamingDecoder::url_ = std::make_shared<std::string>() [protected]
Definition at line 123 of file streaming-decoder.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/streaming-decoder.h
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc
/mnt/V8SourceCode/src/wasm/sync-streaming-decoder.cc