v8::internal::compiler::Instruction Class Reference
#include <instruction.h>
Public Types
enum GapPosition { START
, END
, FIRST_GAP_POSITION = START
, LAST_GAP_POSITION = END
 }
using OutputCountField = base::BitField< size_t, 0, 8 >
using InputCountField = base::BitField< size_t, 8, 16 >
using TempCountField = base::BitField< size_t, 24, 6 >
Public Member Functions
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
size_t OutputCount () const
const InstructionOperand * OutputAt (size_t i) const
InstructionOperand * OutputAt (size_t i)
bool HasOutput () const
const InstructionOperand * Output () const
InstructionOperand * Output ()
size_t InputCount () const
const InstructionOperand * InputAt (size_t i) const
InstructionOperand * InputAt (size_t i)
size_t TempCount () const
const InstructionOperand * TempAt (size_t i) const
InstructionOperand * TempAt (size_t i)
InstructionCode opcode () const
ArchOpcode arch_opcode () const
AddressingMode addressing_mode () const
FlagsMode flags_mode () const
FlagsCondition flags_condition () const
bool branch_hinted () const
int misc () const
bool HasMemoryAccessMode () const
MemoryAccessMode memory_access_mode () const
Instruction * MarkAsCall ()
bool IsCall () const
bool NeedsReferenceMap () const
bool HasReferenceMap () const
bool ClobbersRegisters () const
bool ClobbersTemps () const
bool ClobbersDoubleRegisters () const
ReferenceMap * reference_map () const
void set_reference_map (ReferenceMap *map)
void OverwriteWithNop ()
bool IsNop () const
bool IsDeoptimizeCall () const
bool IsTrap () const
bool IsJump () const
bool IsRet () const
bool IsTailCall () const
bool IsCallWithDescriptorFlags () const
bool HasCallDescriptorFlag (CallDescriptor::Flag flag) const
size_t CodeEnrypointTagInputIndex () const
size_t JSCallArgumentCountInputIndex () const
ParallelMove * GetOrCreateParallelMove (GapPosition pos, Zone *zone)
ParallelMove * GetParallelMove (GapPosition pos)
const ParallelMove * GetParallelMove (GapPosition pos) const
bool AreMovesRedundant () const
ParallelMove *const * parallel_moves () const
ParallelMove ** parallel_moves ()
InstructionBlock * block () const
void set_block (InstructionBlock *block)
void Print () const
Static Public Member Functions
static Instruction * New (Zone *zone, InstructionCode opcode)
static Instruction * New (Zone *zone, InstructionCode opcode, size_t output_count, InstructionOperand *outputs, size_t input_count, InstructionOperand *inputs, size_t temp_count, InstructionOperand *temps)
static constexpr bool IsCallWithDescriptorFlags (InstructionCode arch_opcode)
Static Public Attributes
static const size_t kMaxOutputCount = OutputCountField::kMax
static const size_t kMaxInputCount = InputCountField::kMax
static const size_t kMaxTempCount = TempCountField::kMax
Private Types
using IsCallField = base::BitField< bool, 30, 1 >
Private Member Functions
Instruction (InstructionCode opcode)
Instruction (InstructionCode opcode, size_t output_count, InstructionOperand *outputs, size_t input_count, InstructionOperand *inputs, size_t temp_count, InstructionOperand *temps)
Private Attributes
InstructionCode opcode_
uint32_t bit_field_
ParallelMove * parallel_moves_ [2]
ReferenceMap * reference_map_
InstructionBlock * block_
InstructionOperand operands_ [1]
Detailed Description
Definition at line 916 of file instruction.h.
Member Typedef Documentation
InputCountField
using v8::internal::compiler::Instruction::InputCountField = base::BitField<size_t, 8, 16>
Definition at line 1143 of file instruction.h.
IsCallField
using v8::internal::compiler::Instruction::IsCallField = base::BitField<bool, 30, 1> [private]
Definition at line 1158 of file instruction.h.
OutputCountField
using v8::internal::compiler::Instruction::OutputCountField = base::BitField<size_t, 0, 8>
Definition at line 1142 of file instruction.h.
TempCountField
using v8::internal::compiler::Instruction::TempCountField = base::BitField<size_t, 24, 6>
Definition at line 1144 of file instruction.h.
Member Enumeration Documentation
GapPosition
enum v8::internal::compiler::Instruction::GapPosition
Enumerator
START
END
FIRST_GAP_POSITION
LAST_GAP_POSITION
Definition at line 1103 of file instruction.h.
                   {
    START,
    END,
    FIRST_GAP_POSITION = START,
    LAST_GAP_POSITION = END
  };
Constructor & Destructor Documentation
Instruction() [1/3]
v8::internal::compiler::Instruction::Instruction (const Instruction &) [delete]
Instruction() [2/3]
v8::internal::compiler::Instruction::Instruction (InstructionCode opcode) [explicit], [private]
Definition at line 374 of file instruction.cc.
    : opcode_(opcode),
      bit_field_(OutputCountField::encode(0) | InputCountField::encode(0) |
                 TempCountField::encode(0) | IsCallField::encode(false)),
      reference_map_(nullptr),
      block_(nullptr) {
  parallel_moves_[0] = nullptr;
  parallel_moves_[1] = nullptr;
  // PendingOperands are required to be 8 byte aligned.
  static_assert(offsetof(Instruction, operands_) % 8 == 0);
}
References operands_, and parallel_moves_.
Instruction() [3/3]
v8::internal::compiler::Instruction::Instruction (InstructionCode opcode, size_t output_count, InstructionOperand * outputs, size_t input_count, InstructionOperand * inputs, size_t temp_count, InstructionOperand * temps) [private]
Definition at line 387 of file instruction.cc.
    : opcode_(opcode),
      bit_field_(OutputCountField::encode(output_count) |
                 InputCountField::encode(input_count) |
                 TempCountField::encode(temp_count) |
                 IsCallField::encode(false)),
      reference_map_(nullptr),
      block_(nullptr) {
  parallel_moves_[0] = nullptr;
  parallel_moves_[1] = nullptr;
  size_t offset = 0;
  for (size_t i = 0; i < output_count; ++i) {
    DCHECK(!outputs[i].IsInvalid());
    operands_[offset++] = outputs[i];
  }
  for (size_t i = 0; i < input_count; ++i) {
    DCHECK(!inputs[i].IsInvalid());
    operands_[offset++] = inputs[i];
  }
  for (size_t i = 0; i < temp_count; ++i) {
    DCHECK(!temps[i].IsInvalid());
    operands_[offset++] = temps[i];
  }
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), operands_, and parallel_moves_.
Member Function Documentation
addressing_mode()
AddressingMode v8::internal::compiler::Instruction::addressing_mode () const [inline]
Definition at line 957 of file instruction.h.
                                         {
    return AddressingModeField::decode(opcode());
  }
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::HasAddressingMode(), and v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::HasAddressingMode().
arch_opcode()
ArchOpcode v8::internal::compiler::Instruction::arch_opcode () const [inline]
Definition at line 956 of file instruction.h.
{ return ArchOpcodeField::decode(opcode()); }
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::compiler::AssembleBranchToLabels(), v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::CanForwardGapJump(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::InstructionScheduler::GetInstructionFlags(), v8::internal::compiler::InstructionScheduler::GetTargetInstructionFlags(), v8::internal::compiler::InstructionScheduler::IsFixedRegisterParameter(), v8::internal::compiler::FrameElider::MarkBlocks(), and v8::internal::compiler::CodeGenerator::ShouldApplyOffsetToStackCheck().
AreMovesRedundant()
bool v8::internal::compiler::Instruction::AreMovesRedundant () const
Definition at line 415 of file instruction.cc.
                                          {
  for (int i = Instruction::FIRST_GAP_POSITION;
       i <= Instruction::LAST_GAP_POSITION; i++) {
    if (parallel_moves_[i] != nullptr && !parallel_moves_[i]->IsRedundant()) {
      return false;
    }
  }
  return true;
}
References FIRST_GAP_POSITION, LAST_GAP_POSITION, and parallel_moves_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), and v8::internal::compiler::JumpThreading::ComputeForwarding().
block()
InstructionBlock* v8::internal::compiler::Instruction::block () const [inline]
Definition at line 1133 of file instruction.h.
{ return block_; }
Referenced by v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), and v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves().
branch_hinted()
bool v8::internal::compiler::Instruction::branch_hinted () const [inline]
Definition at line 964 of file instruction.h.
{ return BranchHintField::decode(opcode()); }
References v8::base::BitField< T, shift, size, U >::decode().
ClobbersDoubleRegisters()
bool v8::internal::compiler::Instruction::ClobbersDoubleRegisters () const [inline]
Definition at line 1007 of file instruction.h.
{ return IsCall(); }
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
ClobbersRegisters()
bool v8::internal::compiler::Instruction::ClobbersRegisters () const [inline]
Definition at line 1005 of file instruction.h.
{ return IsCall(); }
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
ClobbersTemps()
bool v8::internal::compiler::Instruction::ClobbersTemps () const [inline]
Definition at line 1006 of file instruction.h.
{ return IsCall(); }
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
CodeEnrypointTagInputIndex()
size_t v8::internal::compiler::Instruction::CodeEnrypointTagInputIndex () const [inline]
Definition at line 1078 of file instruction.h.
                                            {
    // Keep in sync with instruction-selector.cc where the inputs are assembled.
    switch (arch_opcode()) {
      case kArchCallCodeObject:
        return InputCount() -
               (HasCallDescriptorFlag(CallDescriptor::kHasExceptionHandler)
                    ? 2
                    : 1);
      case kArchTailCallCodeObject:
        return InputCount() - 3;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::compiler::CallDescriptor::kHasExceptionHandler, and v8::internal::UNREACHABLE().
flags_condition()
FlagsCondition v8::internal::compiler::Instruction::flags_condition () const [inline]
Definition at line 961 of file instruction.h.
                                         {
    return FlagsConditionField::decode(opcode());
  }
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::PPCOperandConverter::CompareLogical(), and v8::internal::compiler::S390OperandConverter::CompareLogical().
flags_mode()
FlagsMode v8::internal::compiler::Instruction::flags_mode () const [inline]
Definition at line 960 of file instruction.h.
{ return FlagsModeField::decode(opcode()); }
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::PPCOperandConverter::OutputRCBit(), and v8::internal::compiler::ArmOperandConverter::OutputSBit().
GetOrCreateParallelMove()
ParallelMove* v8::internal::compiler::Instruction::GetOrCreateParallelMove (GapPosition pos, Zone * zone) [inline]
Definition at line 1110 of file instruction.h.
                                                                     {
    if (parallel_moves_[pos] == nullptr) {
      parallel_moves_[pos] = zone->New<ParallelMove>(zone);
    }
    return parallel_moves_[pos];
  }
References v8::internal::Zone::New().
Referenced by v8::internal::compiler::RegisterAllocationData::AddGapMove(), v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), and v8::internal::compiler::MoveOptimizer::OptimizeMerge().
GetParallelMove() [1/2]
ParallelMove* v8::internal::compiler::Instruction::GetParallelMove (GapPosition pos) [inline]
Definition at line 1117 of file instruction.h.
                                                 {
    return parallel_moves_[pos];
  }
Referenced by v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::compiler::CodeGenerator::AssembleGaps(), v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::CanForwardGapJump(), v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::BlockAssessments::PerformMoves(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::VerifyAllocatedGaps(), and v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::VerifyEmptyGaps().
GetParallelMove() [2/2]
const ParallelMove* v8::internal::compiler::Instruction::GetParallelMove (GapPosition pos) const [inline]
Definition at line 1121 of file instruction.h.
                                                             {
    return parallel_moves_[pos];
  }
HasCallDescriptorFlag()
bool v8::internal::compiler::Instruction::HasCallDescriptorFlag (CallDescriptor::Flag flag) const [inline]
Definition at line 1049 of file instruction.h.
                                                            {
    DCHECK(IsCallWithDescriptorFlags());
    static_assert(CallDescriptor::kFlagsBitsEncodedInInstructionCode == 10);
#ifdef DEBUG
    static constexpr int kInstructionCodeFlagsMask =
        ((1 << CallDescriptor::kFlagsBitsEncodedInInstructionCode) - 1);
    DCHECK_EQ(static_cast<int>(flag) & kInstructionCodeFlagsMask, flag);
#endif
    return MiscField::decode(opcode()) & flag;
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::CallDescriptor::kFlagsBitsEncodedInInstructionCode.
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), and v8::internal::compiler::CodeGenerator::RecordCallPosition().
HasMemoryAccessMode()
bool v8::internal::compiler::Instruction::HasMemoryAccessMode () const [inline]
Definition at line 966 of file instruction.h.
                                   {
    return compiler::HasMemoryAccessMode(arch_opcode());
  }
References v8::internal::compiler::HasMemoryAccessMode().
Referenced by v8::internal::compiler::InstructionScheduler::CanTrap(), and v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitTSANAwareStore().
HasOutput()
bool v8::internal::compiler::Instruction::HasOutput () const [inline]
Definition at line 931 of file instruction.h.
{ return OutputCount() > 0; }
HasReferenceMap()
bool v8::internal::compiler::Instruction::HasReferenceMap () const [inline]
Definition at line 1003 of file instruction.h.
{ return reference_map_ != nullptr; }
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
InputAt() [1/2]
InstructionOperand* v8::internal::compiler::Instruction::InputAt (size_t i) [inline]
Definition at line 940 of file instruction.h.
                                        {
    DCHECK_LT(i, InputCount());
    return &operands_[OutputCount() + i];
  }
References DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
InputAt() [2/2]
const InstructionOperand* v8::internal::compiler::Instruction::InputAt (size_t i) const [inline]
Definition at line 936 of file instruction.h.
                                                    {
    DCHECK_LT(i, InputCount());
    return &operands_[OutputCount() + i];
  }
References DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::InstructionOperandIterator::Advance(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::AssembleConditionalCompareChain(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::EmitFpOrNeonUnop(), v8::internal::compiler::HasFPRegisterInput(), v8::internal::compiler::HasFPStackSlotInput(), v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::HasImmediateInput(), v8::internal::compiler::HasImmediateInput(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::HasImmediateInput(), v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::HasRegisterInput(), v8::internal::compiler::HasRegisterInput(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::HasRegisterInput(), v8::internal::compiler::HasStackSlotInput(), v8::internal::compiler::InstructionOperandConverter::InputCode(), v8::internal::compiler::InstructionOperandConverter::InputDouble(), v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::InputExternalReference(), v8::internal::compiler::InstructionOperandConverter::InputFloat32(), v8::internal::compiler::Arm64OperandConverter::InputFloat32OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat32OrZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrZeroRegister(), v8::internal::compiler::InstructionOperandConverter::InputFloatRegister(), v8::internal::compiler::IA32OperandConverter::InputImmediate(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::compiler::X64OperandConverter::InputImmediate(), v8::internal::compiler::ArmOperandConverter::InputImmediate(), v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputInt64(), v8::internal::compiler::InstructionOperandConverter::InputLabel(), v8::internal::compiler::Arm64OperandConverter::InputOperand(), v8::internal::compiler::Loong64OperandConverter::InputOperand(), v8::internal::compiler::MipsOperandConverter::InputOperand(), v8::internal::compiler::RiscvOperandConverter::InputOperand(), v8::internal::compiler::IA32OperandConverter::InputOperand(), v8::internal::compiler::X64OperandConverter::InputOperand(), v8::internal::compiler::Arm64OperandConverter::InputOperand32(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroDoubleRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroDoubleRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroDoubleRegister(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister32(), v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister64(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroSingleRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroSingleRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroSingleRegister(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::Arm64OperandConverter::InputRegister32(), v8::internal::compiler::InstructionSequence::InputRpo(), v8::internal::compiler::InstructionOperandConverter::InputRpo(), v8::internal::compiler::InstructionOperandConverter::InputSimd128Register(), v8::internal::compiler::Loong64OperandConverter::InputSingleRegister(), v8::internal::compiler::MipsOperandConverter::InputSingleRegister(), v8::internal::compiler::RiscvOperandConverter::InputSingleRegister(), v8::internal::compiler::S390OperandConverter::InputStackSlot(), v8::internal::compiler::S390OperandConverter::Is32BitOperand(), v8::internal::compiler::S390OperandConverter::Is64BitOperand(), v8::internal::compiler::FrameElider::MarkBlocks(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::IA32OperandConverter::NextMemoryOperand(), v8::internal::compiler::operator<<(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::CodeGenerator::RecordCallPosition(), v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::SignExtend(), v8::internal::compiler::InstructionSelector::UpdateRenames(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
InputCount()
size_t v8::internal::compiler::Instruction::InputCount () const [inline]
Definition at line 935 of file instruction.h.
{ return InputCountField::decode(bit_field_); }
Referenced by v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::CodeGenerator::AssembleArchBinarySearchSwitch(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleArchTableSwitch(), v8::internal::compiler::AssembleConditionalCompareChain(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::CodeGenerator::ComputeBranchInfo(), v8::internal::compiler::CodeGenerator::GetSlotAboveSPBeforeTailCall(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::OperandCount(), v8::internal::compiler::operator<<(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::CodeGenerator::RecordCallPosition(), v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::ShouldClearOutputRegisterBeforeInstruction(), v8::internal::compiler::InstructionSelector::UpdateRenames(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
IsCall()
bool v8::internal::compiler::Instruction::IsCall () const [inline]
Definition at line 1001 of file instruction.h.
{ return IsCallField::decode(bit_field_); }
Referenced by v8::internal::compiler::FrameElider::MarkBlocks(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
IsCallWithDescriptorFlags() [1/2]
bool v8::internal::compiler::Instruction::IsCallWithDescriptorFlags () const [inline]
Definition at line 1046 of file instruction.h.
                                         {
    return IsCallWithDescriptorFlags(arch_opcode());
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::EncodeCallDescriptorFlags().
IsCallWithDescriptorFlags() [2/2]
static constexpr bool v8::internal::compiler::Instruction::IsCallWithDescriptorFlags (InstructionCode arch_opcode) [inline], [static], [constexpr]
Definition at line 1043 of file instruction.h.
                                                                               {
    return arch_opcode <= ArchOpcode::kArchCallBuiltinPointer;
  }
IsDeoptimizeCall()
bool v8::internal::compiler::Instruction::IsDeoptimizeCall () const [inline]
Definition at line 1024 of file instruction.h.
                                {
    return arch_opcode() == ArchOpcode::kArchDeoptimize ||
           FlagsModeField::decode(opcode()) == kFlags_deoptimize;
  }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::kFlags_deoptimize.
Referenced by v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::InstructionScheduler::DependsOnDeoptOrTrap(), v8::internal::compiler::FrameElider::MarkBlocks(), v8::internal::compiler::FrameElider::MarkDeConstruction(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
IsJump()
bool v8::internal::compiler::Instruction::IsJump () const [inline]
Definition at line 1033 of file instruction.h.
{ return arch_opcode() == ArchOpcode::kArchJmp; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleInstruction(), and v8::internal::compiler::FrameElider::MarkDeConstruction().
IsNop()
bool v8::internal::compiler::Instruction::IsNop () const [inline]
Definition at line 1022 of file instruction.h.
{ return arch_opcode() == kArchNop; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), and v8::internal::compiler::JumpThreading::ComputeForwarding().
IsRet()
bool v8::internal::compiler::Instruction::IsRet () const [inline]
Definition at line 1034 of file instruction.h.
{ return arch_opcode() == ArchOpcode::kArchRet; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::FrameElider::MarkDeConstruction(), and v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations().
IsTailCall()
bool v8::internal::compiler::Instruction::IsTailCall () const [inline]
Definition at line 1035 of file instruction.h.
                          {
#if V8_ENABLE_WEBASSEMBLY
    return arch_opcode() <= ArchOpcode::kArchTailCallWasmIndirect;
#else
    return arch_opcode() <= ArchOpcode::kArchTailCallAddress;
#endif // V8_ENABLE_WEBASSEMBLY
  }
Referenced by v8::internal::compiler::CodeGenerator::GetSlotAboveSPBeforeTailCall(), v8::internal::compiler::FrameElider::MarkDeConstruction(), and v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations().
IsTrap()
bool v8::internal::compiler::Instruction::IsTrap () const [inline]
Definition at line 1029 of file instruction.h.
                      {
    return FlagsModeField::decode(opcode()) == kFlags_trap;
  }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::kFlags_trap.
Referenced by v8::internal::compiler::InstructionScheduler::CanTrap().
JSCallArgumentCountInputIndex()
size_t v8::internal::compiler::Instruction::JSCallArgumentCountInputIndex () const [inline]
Definition at line 1094 of file instruction.h.
                                               {
    // Keep in sync with instruction-selector.cc where the inputs are assembled.
    if (HasCallDescriptorFlag(CallDescriptor::kHasExceptionHandler)) {
      return InputCount() - 2;
    } else {
      return InputCount() - 1;
    }
  }
References v8::internal::compiler::CallDescriptor::kHasExceptionHandler.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction().
MarkAsCall()
Instruction* v8::internal::compiler::Instruction::MarkAsCall () [inline]
Definition at line 997 of file instruction.h.
                            {
    bit_field_ = IsCallField::update(bit_field_, true);
    return this;
  }
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
memory_access_mode()
MemoryAccessMode v8::internal::compiler::Instruction::memory_access_mode () const [inline]
Definition at line 969 of file instruction.h.
                                              {
    DCHECK(HasMemoryAccessMode());
    return AccessModeField::decode(opcode());
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::HasMemoryAccessMode().
Referenced by v8::internal::compiler::InstructionScheduler::CanTrap(), and v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::RecordTrapInfoIfNeeded().
misc()
int v8::internal::compiler::Instruction::misc () const [inline]
Definition at line 965 of file instruction.h.
{ return MiscField::decode(opcode()); }
References v8::base::BitField< T, shift, size, U >::decode().
NeedsReferenceMap()
bool v8::internal::compiler::Instruction::NeedsReferenceMap () const [inline]
Definition at line 1002 of file instruction.h.
{ return IsCall(); }
Referenced by v8::internal::compiler::InstructionSequence::AddInstruction().
New() [1/2]
static Instruction* v8::internal::compiler::Instruction::New (Zone * zone, InstructionCode opcode) [inline], [static]
Definition at line 974 of file instruction.h.
                                                              {
    return New(zone, opcode, 0, nullptr, 0, nullptr, 0, nullptr);
  }
References v8::internal::compiler::ConstantOperand::New().
Referenced by v8::internal::compiler::InstructionSelector::Emit(), and v8::internal::compiler::InstructionSelector::VisitBlock().
New() [2/2]
static Instruction* v8::internal::compiler::Instruction::New (Zone * zone, InstructionCode opcode, size_t output_count, InstructionOperand * outputs, size_t input_count, InstructionOperand * inputs, size_t temp_count, InstructionOperand * temps) [inline], [static]
Definition at line 978 of file instruction.h.
                                                                        {
    DCHECK(output_count == 0 || outputs != nullptr);
    DCHECK(input_count == 0 || inputs != nullptr);
    DCHECK(temp_count == 0 || temps != nullptr);
    // TODO(turbofan): Handle this gracefully. See crbug.com/582702.
    CHECK(InputCountField::is_valid(input_count));
    size_t total_extra_ops = output_count + input_count + temp_count;
    if (total_extra_ops != 0) total_extra_ops--;
    int size = static_cast<int>(
        RoundUp(sizeof(Instruction), sizeof(InstructionOperand)) +
        total_extra_ops * sizeof(InstructionOperand));
    return new (zone->Allocate<Instruction>(size)) Instruction(
        opcode, output_count, outputs, input_count, inputs, temp_count, temps);
  }
References v8::internal::Zone::Allocate(), CHECK, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::InstructionOperand::InstructionOperand(), RoundUp(), and size().
opcode()
InstructionCode v8::internal::compiler::Instruction::opcode () const [inline]
Definition at line 955 of file instruction.h.
{ return opcode_; }
Referenced by v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AssembleOp(), v8::internal::compiler::CodeGenerator::ComputeBranchInfo(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitTSANAwareStore(), v8::internal::compiler::ArmOperandConverter::InputOffset(), v8::internal::compiler::ArmOperandConverter::InputOperand2(), v8::internal::compiler::Arm64OperandConverter::InputOperand2_32(), v8::internal::compiler::Arm64OperandConverter::InputOperand2_64(), v8::internal::compiler::PPCOperandConverter::MemoryOperand(), v8::internal::compiler::S390OperandConverter::MemoryOperand(), v8::internal::compiler::Loong64OperandConverter::MemoryOperand(), v8::internal::compiler::MipsOperandConverter::MemoryOperand(), v8::internal::compiler::RiscvOperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::X64OperandConverter::MemoryOperand(), v8::internal::compiler::Arm64OperandConverter::MemoryOperand(), v8::internal::compiler::ArmOperandConverter::NeonInputOperand(), v8::internal::compiler::IA32OperandConverter::NextMemoryOperand(), v8::internal::compiler::operator<<(), v8::internal::compiler::ShouldAlignForJCCErratum(), v8::internal::compiler::CodeGenerator::ShouldApplyOffsetToStackCheck(), and v8::internal::compiler::ShouldClearOutputRegisterBeforeInstruction().
operator=()
Instruction& v8::internal::compiler::Instruction::operator= (const Instruction &) [delete]
Output() [1/2]
InstructionOperand* v8::internal::compiler::Instruction::Output () [inline]
Definition at line 933 of file instruction.h.
{ return OutputAt(0); }
Output() [2/2]
const InstructionOperand* v8::internal::compiler::Instruction::Output () const [inline]
Definition at line 932 of file instruction.h.
{ return OutputAt(0); }
Referenced by v8::internal::compiler::IA32OperandConverter::OutputOperand(), v8::internal::compiler::X64OperandConverter::OutputOperand(), and v8::internal::compiler::InstructionOperandConverter::OutputSimd128Register().
OutputAt() [1/2]
InstructionOperand* v8::internal::compiler::Instruction::OutputAt (size_t i) [inline]
Definition at line 926 of file instruction.h.
                                         {
    DCHECK_LT(i, OutputCount());
    return &operands_[i];
  }
References DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
OutputAt() [2/2]
const InstructionOperand* v8::internal::compiler::Instruction::OutputAt (size_t i) const [inline]
Definition at line 922 of file instruction.h.
                                                     {
    DCHECK_LT(i, OutputCount());
    return &operands_[i];
  }
References DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::HasRegisterOutput(), v8::internal::compiler::InstructionScheduler::IsFixedRegisterParameter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::operator<<(), v8::internal::compiler::InstructionOperandConverter::OutputDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::OutputFloatRegister(), v8::internal::compiler::InstructionOperandConverter::OutputRegister(), v8::internal::compiler::Loong64OperandConverter::OutputSingleRegister(), v8::internal::compiler::MipsOperandConverter::OutputSingleRegister(), v8::internal::compiler::RiscvOperandConverter::OutputSingleRegister(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations(), v8::internal::compiler::InstructionSequence::ValidateSSA(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
OutputCount()
size_t v8::internal::compiler::Instruction::OutputCount () const [inline]
Definition at line 921 of file instruction.h.
{ return OutputCountField::decode(bit_field_); }
Referenced by v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::CodeGenerator::AssembleArchBoolean(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor(), v8::internal::compiler::HasRegisterOutput(), v8::internal::compiler::InstructionScheduler::IsFixedRegisterParameter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::OperandCount(), v8::internal::compiler::operator<<(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::Arm64OperandConverter::OutputCount(), v8::internal::compiler::PPCOperandConverter::OutputCount(), v8::internal::compiler::S390OperandConverter::OutputCount(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations(), v8::internal::compiler::ShouldClearOutputRegisterBeforeInstruction(), v8::internal::compiler::InstructionSequence::ValidateSSA(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
OverwriteWithNop()
void v8::internal::compiler::Instruction::OverwriteWithNop () [inline]
Definition at line 1016 of file instruction.h.
                          {
    opcode_ = ArchOpcodeField::encode(kArchNop);
    bit_field_ = 0;
    reference_map_ = nullptr;
  }
References v8::base::BitField< T, shift, size, U >::encode().
Referenced by v8::internal::compiler::JumpThreading::ApplyForwarding().
parallel_moves() [1/2]
ParallelMove** v8::internal::compiler::Instruction::parallel_moves () [inline]
Definition at line 1128 of file instruction.h.
{ return &parallel_moves_[0]; }
parallel_moves() [2/2]
ParallelMove* const* v8::internal::compiler::Instruction::parallel_moves () const [inline]
Definition at line 1127 of file instruction.h.
{ return &parallel_moves_[0]; }
Referenced by v8::internal::compiler::MoveOptimizer::CompressGaps(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::FindFirstNonEmptySlot(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::operator<<(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), and v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations().
Print()
void v8::internal::compiler::Instruction::Print () const
Definition at line 425 of file instruction.cc.
{ StdoutStream{} << *this << std::endl; }
reference_map()
ReferenceMap* v8::internal::compiler::Instruction::reference_map () const [inline]
Definition at line 1008 of file instruction.h.
{ return reference_map_; }
Referenced by v8::internal::compiler::InstructionSequence::AddInstruction(), v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::CodeGenerator::RecordCallPosition(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
set_block()
void v8::internal::compiler::Instruction::set_block (InstructionBlock * block) [inline]
Definition at line 1134 of file instruction.h.
                                          {
    DCHECK_NOT_NULL(block);
    block_ = block;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::InstructionSequence::AddInstruction().
set_reference_map()
void v8::internal::compiler::Instruction::set_reference_map (ReferenceMap * map) [inline]
Definition at line 1010 of file instruction.h.
                                            {
    DCHECK(NeedsReferenceMap());
    DCHECK(!reference_map_);
    reference_map_ = map;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::InstructionSequence::AddInstruction().
TempAt() [1/2]
InstructionOperand* v8::internal::compiler::Instruction::TempAt (size_t i) [inline]
Definition at line 950 of file instruction.h.
                                       {
    DCHECK_LT(i, TempCount());
    return &operands_[OutputCount() + InputCount() + i];
  }
References DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
TempAt() [2/2]
const InstructionOperand* v8::internal::compiler::Instruction::TempAt (size_t i) const [inline]
Definition at line 946 of file instruction.h.
                                                   {
    DCHECK_LT(i, TempCount());
    return &operands_[OutputCount() + InputCount() + i];
  }
References DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations(), v8::internal::compiler::InstructionOperandConverter::TempDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::TempRegister(), v8::internal::compiler::Arm64OperandConverter::TempRegister32(), v8::internal::compiler::InstructionOperandConverter::TempSimd128Register(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
TempCount()
size_t v8::internal::compiler::Instruction::TempCount () const [inline]
Definition at line 945 of file instruction.h.
{ return TempCountField::decode(bit_field_); }
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::OperandCount(), v8::internal::compiler::operator<<(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
Member Data Documentation
bit_field_
uint32_t v8::internal::compiler::Instruction::bit_field_ [private]
Definition at line 1161 of file instruction.h.
block_
InstructionBlock* v8::internal::compiler::Instruction::block_ [private]
Definition at line 1164 of file instruction.h.
kMaxInputCount
const size_t v8::internal::compiler::Instruction::kMaxInputCount = InputCountField::kMax [static]
Definition at line 1147 of file instruction.h.
Referenced by v8::internal::compiler::InstructionSelector::Emit().
kMaxOutputCount
const size_t v8::internal::compiler::Instruction::kMaxOutputCount = OutputCountField::kMax [static]
Definition at line 1146 of file instruction.h.
Referenced by v8::internal::compiler::InstructionSelector::Emit().
kMaxTempCount
const size_t v8::internal::compiler::Instruction::kMaxTempCount = TempCountField::kMax [static]
Definition at line 1148 of file instruction.h.
Referenced by v8::internal::compiler::InstructionSelector::Emit().
opcode_
InstructionCode v8::internal::compiler::Instruction::opcode_ [private]
Definition at line 1160 of file instruction.h.
operands_
InstructionOperand v8::internal::compiler::Instruction::operands_[1] [private]
Definition at line 1165 of file instruction.h.
Referenced by Instruction().
parallel_moves_
ParallelMove* v8::internal::compiler::Instruction::parallel_moves_[2] [private]
Definition at line 1162 of file instruction.h.
Referenced by AreMovesRedundant(), and Instruction().
reference_map_
ReferenceMap* v8::internal::compiler::Instruction::reference_map_ [private]
Definition at line 1163 of file instruction.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc