v8::internal::AstVisitor< Subclass > Class Template Reference
#include <ast.h>
Public Member Functions
void Visit (AstNode *node)
void VisitDeclarations (Declaration::List *declarations)
void VisitStatements (const ZonePtrList< Statement > *statements)
void VisitExpressions (const ZonePtrList< Expression > *expressions)
Protected Member Functions
Subclass * impl ()
Detailed Description
template<class Subclass>
class v8::internal::AstVisitor< Subclass >
Definition at line 2933 of file ast.h.
Member Function Documentation
impl()
template<class Subclass >
Subclass* v8::internal::AstVisitor< Subclass >::impl () [inline], [protected]
Definition at line 2960 of file ast.h.
{ return static_cast<Subclass*>(this); }
Referenced by v8::internal::AstVisitor< Subclass >::Visit().
Visit()
template<class Subclass >
void v8::internal::AstVisitor< Subclass >::Visit (AstNode * node) [inline]
Definition at line 2935 of file ast.h.
{ impl()->Visit(node); }
References v8::internal::AstVisitor< Subclass >::impl().
Referenced by v8::internal::AstFunctionLiteralIdReindexer::Reindex(), v8::internal::AstTraversalVisitor< Subclass >::Run(), v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral(), v8::internal::AstVisitor< Subclass >::VisitDeclarations(), v8::internal::AstVisitor< Subclass >::VisitExpressions(), and v8::internal::AstVisitor< Subclass >::VisitStatements().
VisitDeclarations()
template<class Subclass >
void v8::internal::AstVisitor< Subclass >::VisitDeclarations (Declaration::List * declarations) [inline]
Definition at line 2937 of file ast.h.
                                                        {
    for (Declaration* decl : *declarations) Visit(decl);
  }
References v8::internal::AstVisitor< Subclass >::Visit().
VisitExpressions()
template<class Subclass >
void v8::internal::AstVisitor< Subclass >::VisitExpressions (const ZonePtrList< Expression > * expressions) [inline]
Definition at line 2948 of file ast.h.
                                                                    {
    for (int i = 0; i < expressions->length(); i++) {
      // The variable statement visiting code may pass null expressions
      // to this code. Maybe this should be handled by introducing an
      // undefined expression or literal? Revisit this code if this
      // changes.
      Expression* expression = expressions->at(i);
      if (expression != nullptr) Visit(expression);
    }
  }
References v8::internal::ZoneList< T >::at(), v8::internal::ZoneList< T >::length(), and v8::internal::AstVisitor< Subclass >::Visit().
VisitStatements()
template<class Subclass >
void v8::internal::AstVisitor< Subclass >::VisitStatements (const ZonePtrList< Statement > * statements) [inline]
Definition at line 2941 of file ast.h.
                                                                 {
    for (int i = 0; i < statements->length(); i++) {
      Statement* stmt = statements->at(i);
      Visit(stmt);
    }
  }
References v8::internal::ZoneList< T >::at(), v8::internal::ZoneList< T >::length(), and v8::internal::AstVisitor< Subclass >::Visit().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h