v8_inspector::AsyncStackTrace Class Reference
#include <v8-stack-trace-impl.h>
Public Member Functions
AsyncStackTrace (const AsyncStackTrace &)=delete
AsyncStackTrace & operator= (const AsyncStackTrace &)=delete
std::unique_ptr< protocol::Runtime::StackTrace > buildInspectorObject (V8Debugger *debugger, int maxAsyncDepth) const
const String16 & description () const
std::weak_ptr< AsyncStackTrace > parent () const
bool isEmpty () const
const V8StackTraceId & externalParent () const
const std::vector< std::shared_ptr< StackFrame > > & frames () const
Static Public Member Functions
static std::shared_ptr< AsyncStackTrace > capture (V8Debugger *, const String16 &description, bool skipTopFrame=false)
static uintptr_t store (V8Debugger *debugger, std::shared_ptr< AsyncStackTrace > stack)
Private Member Functions
AsyncStackTrace (const String16 &description, std::vector< std::shared_ptr< StackFrame >> frames, std::shared_ptr< AsyncStackTrace > asyncParent, const V8StackTraceId &externalParent)
Private Attributes
uintptr_t m_id
String16 m_description
std::vector< std::shared_ptr< StackFrame > > m_frames
std::weak_ptr< AsyncStackTrace > m_asyncParent
V8StackTraceId m_externalParent
Detailed Description
Definition at line 115 of file v8-stack-trace-impl.h.
Constructor & Destructor Documentation
AsyncStackTrace() [1/2]
v8_inspector::AsyncStackTrace::AsyncStackTrace (const AsyncStackTrace &) [delete]
AsyncStackTrace() [2/2]
v8_inspector::AsyncStackTrace::AsyncStackTrace (const String16 & description, std::vector< std::shared_ptr< StackFrame >> frames, std::shared_ptr< AsyncStackTrace > asyncParent, const V8StackTraceId & externalParent) [private]
Definition at line 440 of file v8-stack-trace-impl.cc.
    : m_id(0),
      m_description(description),
      m_frames(std::move(frames)),
      m_asyncParent(std::move(asyncParent)),
      m_externalParent(externalParent) {}
Member Function Documentation
buildInspectorObject()
std::unique_ptr< protocol::Runtime::StackTrace > v8_inspector::AsyncStackTrace::buildInspectorObject (V8Debugger * debugger, int maxAsyncDepth) const
Definition at line 452 of file v8-stack-trace-impl.cc.
                                                               {
  return buildInspectorObjectCommon(debugger, m_frames, m_description,
                                    m_asyncParent.lock(), m_externalParent,
                                    maxAsyncDepth);
}
References v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), m_asyncParent, m_description, m_externalParent, and m_frames.
capture()
std::shared_ptr< AsyncStackTrace > v8_inspector::AsyncStackTrace::capture (V8Debugger * debugger, const String16 & description, bool skipTopFrame = false) [static]
Definition at line 400 of file v8-stack-trace-impl.cc.
                                                                          {
  DCHECK(debugger);
  int maxStackSize = debugger->maxCallStackSizeToCapture();
  TRACE_EVENT1(
      TRACE_DISABLED_BY_DEFAULT("v8.inspector") "," TRACE_DISABLED_BY_DEFAULT(
          "v8.stack_trace"),
      "AsyncStackTrace::capture", "maxFrameCount", maxStackSize);
  v8::Isolate* isolate = debugger->isolate();
  v8::HandleScope handleScope(isolate);
  std::vector<std::shared_ptr<StackFrame>> frames;
  std::shared_ptr<AsyncStackTrace> asyncParent;
  V8StackTraceId externalParent;
  if (isolate->InContext()) {
    v8::Local<v8::StackTrace> v8StackTrace = v8::StackTrace::CurrentStackTrace(
        isolate, maxStackSize, stackTraceOptions);
    frames = toFramesVector(debugger, v8StackTrace, maxStackSize);
    if (skipTopFrame && !frames.empty()) {
      frames.erase(frames.begin());
    }
    debugger->asyncParentFor(v8StackTrace->GetID(), &asyncParent,
                             &externalParent);
  }
  if (frames.empty() && !asyncParent && externalParent.IsInvalid())
    return nullptr;
  if (asyncParent && frames.empty() &&
      (asyncParent->m_description == description || description.isEmpty())) {
    return asyncParent;
  }
  return std::shared_ptr<AsyncStackTrace>(new AsyncStackTrace(
      description, std::move(frames), asyncParent, externalParent));
}
References v8_inspector::V8Debugger::asyncParentFor(), v8::StackTrace::CurrentStackTrace(), DCHECK, v8_inspector::V8StackTraceImpl::frames(), v8::Isolate::InContext(), v8_inspector::String16::isEmpty(), v8_inspector::V8StackTraceId::IsInvalid(), v8_inspector::V8Debugger::isolate(), v8_inspector::V8Debugger::maxCallStackSizeToCapture(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::stackTraceOptions, v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::toFramesVector(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT1.
Referenced by v8_inspector::V8Debugger::asyncTaskScheduledForStack(), and v8_inspector::V8Debugger::storeCurrentStackTrace().
description()
const String16 & v8_inspector::AsyncStackTrace::description () const
Definition at line 466 of file v8-stack-trace-impl.cc.
{ return m_description; }
References m_description.
externalParent()
const V8StackTraceId& v8_inspector::AsyncStackTrace::externalParent () const [inline]
Definition at line 131 of file v8-stack-trace-impl.h.
{ return m_externalParent; }
References m_externalParent.
frames()
const std::vector<std::shared_ptr<StackFrame> >& v8_inspector::AsyncStackTrace::frames () const [inline]
Definition at line 133 of file v8-stack-trace-impl.h.
                                                             {
    return m_frames;
  }
References m_frames.
isEmpty()
bool v8_inspector::AsyncStackTrace::isEmpty () const
Definition at line 472 of file v8-stack-trace-impl.cc.
{ return m_frames.empty(); }
References m_frames.
operator=()
AsyncStackTrace& v8_inspector::AsyncStackTrace::operator= (const AsyncStackTrace &) [delete]
parent()
std::weak_ptr< AsyncStackTrace > v8_inspector::AsyncStackTrace::parent () const
Definition at line 468 of file v8-stack-trace-impl.cc.
                                                           {
  return m_asyncParent;
}
References m_asyncParent.
store()
uintptr_t v8_inspector::AsyncStackTrace::store (V8Debugger * debugger, std::shared_ptr< AsyncStackTrace > stack) [static]
Definition at line 459 of file v8-stack-trace-impl.cc.
                                                                       {
  if (stack->m_id) return stack->m_id;
  stack->m_id = debugger->storeStackTrace(stack);
  return stack->m_id;
}
References v8::internal::stack, and v8_inspector::V8Debugger::storeStackTrace().
Referenced by v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), and v8_inspector::V8Debugger::storeCurrentStackTrace().
Member Data Documentation
m_asyncParent
std::weak_ptr<AsyncStackTrace> v8_inspector::AsyncStackTrace::m_asyncParent [private]
Definition at line 147 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), and parent().
m_description
String16 v8_inspector::AsyncStackTrace::m_description [private]
Definition at line 144 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), and description().
m_externalParent
V8StackTraceId v8_inspector::AsyncStackTrace::m_externalParent [private]
Definition at line 148 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), and externalParent().
m_frames
std::vector<std::shared_ptr<StackFrame> > v8_inspector::AsyncStackTrace::m_frames [private]
Definition at line 146 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), frames(), and isEmpty().
m_id
uintptr_t v8_inspector::AsyncStackTrace::m_id [private]
Definition at line 143 of file v8-stack-trace-impl.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.h
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.cc