v8::internal::wasm::WasmWrapperTSGraphBuilder Class Reference
Classes
class ModifyThreadInWasmFlagScope
Public Member Functions
WasmWrapperTSGraphBuilder (Zone *zone, Assembler &assembler, const CanonicalSig *sig)
void AbortIfNot (V< Word32 > condition, AbortReason abort_reason)
V< Smi > LoadExportedFunctionIndexAsSmi (V< Object > exported_function_data)
V< Smi > BuildChangeInt32ToSmi (V< Word32 > value)
V< WordPtr > GetTargetForBuiltinCall (Builtin builtin)
template<typename Descriptor , typename... Args>
OpIndex CallBuiltin (Builtin name, OpIndex frame_state, Operator::Properties properties, Args... args)
template<typename Descriptor , typename... Args>
OpIndex CallBuiltin (Builtin name, Operator::Properties properties, Args... args)
V< Number > BuildChangeInt32ToNumber (V< Word32 > value)
V< Number > BuildChangeFloat32ToNumber (V< Float32 > value)
V< Number > BuildChangeFloat64ToNumber (V< Float64 > value)
V< Object > ToJS (OpIndex ret, CanonicalValueType type, V< Context > context)
V< JSArray > BuildCallAllocateJSArray (V< Number > array_length, V< Object > context)
void BuildCallWasmFromWrapper (Zone *zone, const CanonicalSig *sig, V< Word32 > callee, V< HeapObject > implicit_first_arg, const base::Vector< OpIndex > args, base::Vector< OpIndex > returns)
OpIndex BuildCallAndReturn (V< Context > js_context, V< HeapObject > function_data, base::Vector< OpIndex > args, bool do_conversion, bool set_in_wasm_flag)
void BuildJSToWasmWrapper (bool receiver_is_first_param)
void BuildWasmToJSWrapper (ImportCallKind kind, int expected_arity, Suspend suspend)
void BuildCapiCallWrapper ()
V< Word32 > BuildSmiShiftBitsConstant ()
V< Word32 > BuildSmiShiftBitsConstant32 ()
V< Word32 > BuildChangeSmiToInt32 (OpIndex value)
V< Float64 > HeapNumberToFloat64 (V< HeapNumber > input)
OpIndex FromJSFast (OpIndex input, CanonicalValueType type)
OpIndex LoadInstanceType (V< Map > map)
OpIndex BuildCheckString (OpIndex input, OpIndex js_context, CanonicalValueType type)
V< Float64 > BuildChangeTaggedToFloat64 (OpIndex value, OpIndex context, compiler::turboshaft::OptionalOpIndex frame_state)
OpIndex BuildChangeTaggedToInt32 (OpIndex value, OpIndex context, compiler::turboshaft::OptionalOpIndex frame_state)
CallDescriptor * GetBigIntToI64CallDescriptor (bool needs_frame_state)
OpIndex BuildChangeBigIntToInt64 (OpIndex input, OpIndex context, compiler::turboshaft::OptionalOpIndex frame_state)
OpIndex FromJS (V< Object > input, OpIndex context, CanonicalValueType type, OptionalOpIndex frame_state={})
bool QualifiesForFastTransform ()
V< Map > LoadMap (V< Object > object)
void CanTransformFast (OpIndex input, CanonicalValueType type, TSBlock *slow_path)
int AddArgumentNodes (base::Vector< OpIndex > args, int pos, base::SmallVector< OpIndex, 16 > wasm_params, const CanonicalSig *sig, V< Context > context)
OpIndex LoadSharedFunctionInfo (V< Object > js_function)
OpIndex BuildReceiverNode (OpIndex callable_node, OpIndex native_context, V< Undefined > undefined_node)
V< Context > LoadContextFromJSFunction (V< JSFunction > js_function)
V< Object > BuildSuspend (V< Object > value, V< Object > import_data, V< WordPtr > *old_sp, V< WordPtr > old_limit)
V< FixedArray > BuildMultiReturnFixedArrayFromIterable (OpIndex iterable, V< Context > context)
void SafeStore (int offset, CanonicalValueType type, OpIndex base, OpIndex value)
V< WordPtr > BuildLoadCallTargetFromExportedFunctionData (V< WasmFunctionData > function_data)
const OpIndex SafeLoad (OpIndex base, int offset, CanonicalValueType type)
Private Attributes
const CanonicalSig *const sig_
Additional Inherited Members
Detailed Description
Definition at line 63 of file wrappers.cc.
Constructor & Destructor Documentation
WasmWrapperTSGraphBuilder()
v8::internal::wasm::WasmWrapperTSGraphBuilder::WasmWrapperTSGraphBuilder (Zone * zone, Assembler & assembler, const CanonicalSig * sig) [inline]
Definition at line 65 of file wrappers.cc.
      : WasmGraphBuilderBase(zone, assembler), sig_(sig) {}
Member Function Documentation
AbortIfNot()
void v8::internal::wasm::WasmWrapperTSGraphBuilder::AbortIfNot (V< Word32 > condition, AbortReason abort_reason) [inline]
Definition at line 69 of file wrappers.cc.
                                                                 {
    if (!v8_flags.debug_code) return;
    IF_NOT (condition) {
      V<Number> message_id =
          __ NumberConstant(static_cast<int32_t>(abort_reason));
      CallRuntime(__ phase_zone(), Runtime::kAbort, {message_id},
                  __ NoContextConstant());
    }
  }
References __, v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::compiler::NumberConstant(), and v8::internal::v8_flags.
AddArgumentNodes()
int v8::internal::wasm::WasmWrapperTSGraphBuilder::AddArgumentNodes (base::Vector< OpIndex > args, int pos, base::SmallVector< OpIndex, 16 > wasm_params, const CanonicalSig * sig, V< Context > context) [inline]
Definition at line 1111 of file wrappers.cc.
                                                                    {
    // Convert wasm numbers to JS values.
    for (size_t i = 0; i < wasm_params.size(); ++i) {
      args[pos++] = ToJS(wasm_params[i], sig->GetParam(i), context);
    }
    return pos;
  }
References v8::base::args, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::sig, v8::base::SmallVector< T, kSize, Allocator >::size(), and ToJS().
Referenced by BuildWasmToJSWrapper().
BuildCallAllocateJSArray()
V<JSArray> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAllocateJSArray (V< Number > array_length, V< Object > context) [inline]
Definition at line 328 of file wrappers.cc.
                                                         {
    // Since we don't check that args will fit in an array,
    // we make sure this is true based on statically known limits.
    static_assert(kV8MaxWasmFunctionReturns <=
                  JSArray::kInitialMaxFastElementArray);
    return CallBuiltin<WasmAllocateJSArrayDescriptor>(
        Builtin::kWasmAllocateJSArray, Operator::kEliminatable, array_length,
        context);
  }
References v8::internal::compiler::Operator::kEliminatable, v8::internal::JSArray::kInitialMaxFastElementArray, and v8::internal::wasm::kV8MaxWasmFunctionReturns.
Referenced by BuildCallAndReturn().
BuildCallAndReturn()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn (V< Context > js_context, V< HeapObject > function_data, base::Vector< OpIndex > args, bool do_conversion, bool set_in_wasm_flag) [inline]
Definition at line 365 of file wrappers.cc.
                                                    {
    const int rets_count = static_cast<int>(sig_->return_count());
    base::SmallVector<OpIndex, 1> rets(rets_count);
    // Set the ThreadInWasm flag before we do the actual call.
    {
      std::optional<ModifyThreadInWasmFlagScope>
          modify_thread_in_wasm_flag_builder;
      if (set_in_wasm_flag) {
        modify_thread_in_wasm_flag_builder.emplace(this, Asm());
      }
      V<WasmInternalFunction> internal =
          V<WasmInternalFunction>::Cast(__ LoadProtectedPointerField(
              function_data, LoadOp::Kind::TaggedBase().Immutable(),
              WasmExportedFunctionData::kProtectedInternalOffset));
      auto [target, implicit_arg] = BuildFunctionTargetAndImplicitArg(internal);
      BuildCallWasmFromWrapper(__ phase_zone(), sig_, target, implicit_arg,
                               args, base::VectorOf(rets));
    }
    V<Object> jsval;
    if (sig_->return_count() == 0) {
      jsval = LOAD_ROOT(UndefinedValue);
    } else if (sig_->return_count() == 1) {
      jsval = do_conversion ? ToJS(rets[0], sig_->GetReturn(), js_context)
                            : rets[0];
    } else {
      int32_t return_count = static_cast<int32_t>(sig_->return_count());
      V<Smi> size = __ SmiConstant(Smi::FromInt(return_count));
      jsval = BuildCallAllocateJSArray(size, js_context);
      V<FixedArray> fixed_array = __ Load(jsval, LoadOp::Kind::TaggedBase(),
                                          MemoryRepresentation::TaggedPointer(),
                                          JSObject::kElementsOffset);
      for (int i = 0; i < return_count; ++i) {
        V<Object> value = ToJS(rets[i], sig_->GetReturn(i), js_context);
        __ StoreFixedArrayElement(fixed_array, i, value,
                                  compiler::kFullWriteBarrier);
      }
    }
    return jsval;
  }
References __, v8::base::args, v8::internal::wasm::WasmGraphBuilderBase::Asm(), BuildCallAllocateJSArray(), BuildCallWasmFromWrapper(), v8::internal::wasm::WasmGraphBuilderBase::BuildFunctionTargetAndImplicitArg(), v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::Smi::FromInt(), v8::internal::Signature< T >::GetReturn(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::kFullWriteBarrier, v8::Load(), LOAD_ROOT, v8::internal::Signature< T >::return_count(), sig_, size(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), ToJS(), v8::internal::value, and v8::base::VectorOf().
Referenced by BuildJSToWasmWrapper().
BuildCallWasmFromWrapper()
void v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallWasmFromWrapper (Zone * zone, const CanonicalSig * sig, V< Word32 > callee, V< HeapObject > implicit_first_arg, const base::Vector< OpIndex > args, base::Vector< OpIndex > returns) [inline]
Definition at line 339 of file wrappers.cc.
                                                             {
    const TSCallDescriptor* descriptor = TSCallDescriptor::Create(
        compiler::GetWasmCallDescriptor(
            __ graph_zone(), sig,
            compiler::WasmCallKind::kWasmIndirectFunction),
        compiler::CanThrow::kYes, compiler::LazyDeoptOnThrow::kNo,
        __ graph_zone());
    args[0] = implicit_first_arg;
    OpIndex call = __ Call(callee, OpIndex::Invalid(), base::VectorOf(args),
                           descriptor, OpEffects().CanCallAnything());
    if (sig->return_count() == 1) {
      returns[0] = call;
    } else if (sig->return_count() > 1) {
      for (uint32_t i = 0; i < sig->return_count(); i++) {
        CanonicalValueType type = sig->GetReturn(i);
        returns[i] = __ Projection(call, i, RepresentationFor(type));
      }
    }
  }
References __, v8::base::args, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::compiler::GetWasmCallDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::kNo, v8::internal::compiler::kWasmIndirectFunction, v8::internal::compiler::kYes, v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::internal::sig, v8::internal::tracing::type, and v8::base::VectorOf().
Referenced by BuildCallAndReturn().
BuildCapiCallWrapper()
void v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper () [inline]
Definition at line 673 of file wrappers.cc.
                              {
    __ Bind(__ NewBlock());
    base::SmallVector<OpIndex, 8> incoming_params;
    // Instance.
    incoming_params.push_back(
        __ Parameter(0, RegisterRepresentation::Tagged()));
    // Wasm parameters.
    for (int i = 0; i < static_cast<int>(sig_->parameter_count()); ++i) {
      incoming_params.push_back(
          __ Parameter(i + 1, RepresentationFor(sig_->GetParam(i))));
    }
    // Store arguments on our stack, then align the stack for calling to C.
    int param_bytes = 0;
    for (CanonicalValueType type : sig_->parameters()) {
      param_bytes += type.value_kind_size();
    }
    int return_bytes = 0;
    for (CanonicalValueType type : sig_->returns()) {
      return_bytes += type.value_kind_size();
    }
    int stack_slot_bytes = std::max(param_bytes, return_bytes);
    OpIndex values = stack_slot_bytes == 0
                         ? __ IntPtrConstant(0)
                         : __ StackSlot(stack_slot_bytes, kDoubleAlignment);
    int offset = 0;
    for (size_t i = 0; i < sig_->parameter_count(); ++i) {
      CanonicalValueType type = sig_->GetParam(i);
      // Start from the parameter with index 1 to drop the instance_node.
      // TODO(jkummerow): When a values is a reference type, we should pass it
      // in a GC-safe way, not just as a raw pointer.
      SafeStore(offset, type, values, incoming_params[i + 1]);
      offset += type.value_kind_size();
    }
    V<Object> function_node =
        __ LoadTaggedField(incoming_params[0], WasmImportData::kCallableOffset);
    V<HeapObject> shared = LoadSharedFunctionInfo(function_node);
    V<WasmFunctionData> function_data =
        V<WasmFunctionData>::Cast(__ LoadTrustedPointerField(
            shared, LoadOp::Kind::TaggedBase(),
            kWasmFunctionDataIndirectPointerTag,
            SharedFunctionInfo::kTrustedFunctionDataOffset));
    V<Object> host_data_foreign = __ LoadTaggedField(
        function_data, WasmCapiFunctionData::kEmbedderDataOffset);
    BuildModifyThreadInWasmFlag(__ phase_zone(), false);
    OpIndex isolate_root = __ LoadRootRegister();
    OpIndex fp_value = __ FramePointer();
    __ Store(isolate_root, fp_value, StoreOp::Kind::RawAligned(),
             MemoryRepresentation::UintPtr(), compiler::kNoWriteBarrier,
             Isolate::c_entry_fp_offset());
    V<WordPtr> call_target =
        BuildLoadCallTargetFromExportedFunctionData(function_data);
    // Parameters: Address host_data_foreign, Address arguments.
    auto host_sig =
        FixedSizeSignature<MachineType>::Returns(MachineType::Pointer())
            .Params(MachineType::AnyTagged(), MachineType::Pointer());
    OpIndex return_value =
        CallC(&host_sig, call_target, {host_data_foreign, values});
    BuildModifyThreadInWasmFlag(__ phase_zone(), true);
    IF_NOT (__ WordPtrEqual(return_value, __ IntPtrConstant(0))) {
      WasmRethrowExplicitContextDescriptor interface_descriptor;
      auto call_descriptor = compiler::Linkage::GetStubCallDescriptor(
          __ graph_zone(), interface_descriptor,
          interface_descriptor.GetStackParameterCount(),
          CallDescriptor::kNoFlags, Operator::kNoProperties,
          StubCallMode::kCallBuiltinPointer);
      const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
          call_descriptor, compiler::CanThrow::kYes,
          compiler::LazyDeoptOnThrow::kNo, __ graph_zone());
      OpIndex rethrow_call_target =
          GetTargetForBuiltinCall(Builtin::kWasmRethrowExplicitContext);
      V<Context> context =
          __ Load(incoming_params[0], LoadOp::Kind::TaggedBase(),
                  MemoryRepresentation::TaggedPointer(),
                  WasmImportData::kNativeContextOffset);
      __ Call(rethrow_call_target, {return_value, context}, ts_call_descriptor);
      __ Unreachable();
    }
    DCHECK_LT(sig_->return_count(), kV8MaxWasmFunctionReturns);
    size_t return_count = sig_->return_count();
    if (return_count == 0) {
      __ Return(__ Word32Constant(0));
    } else {
      base::SmallVector<OpIndex, 8> returns(return_count);
      offset = 0;
      for (size_t i = 0; i < return_count; ++i) {
        CanonicalValueType type = sig_->GetReturn(i);
        OpIndex val = SafeLoad(values, offset, type);
        returns[i] = val;
        offset += type.value_kind_size();
      }
      __ Return(__ Word32Constant(0), base::VectorOf(returns));
    }
  }
References __, v8::internal::MachineType::AnyTagged(), BuildLoadCallTargetFromExportedFunctionData(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlag(), v8::internal::Isolate::c_entry_fp_offset(), v8::internal::wasm::WasmGraphBuilderBase::CallC(), v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), DCHECK_LT, v8::internal::Signature< T >::GetParam(), v8::internal::Signature< T >::GetReturn(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), GetTargetForBuiltinCall(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::IntPtrConstant(), v8::internal::kCallBuiltinPointer, v8::internal::kDoubleAlignment, v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, v8::internal::compiler::kNoWriteBarrier, v8::internal::wasm::kV8MaxWasmFunctionReturns, v8::internal::compiler::kYes, v8::Load(), LoadSharedFunctionInfo(), v8::internal::Signature< T >::parameter_count(), v8::internal::Signature< T >::parameters(), v8::internal::MachineType::Pointer(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::internal::Signature< T >::return_count(), v8::internal::Signature< T >::returns(), v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns(), SafeLoad(), SafeStore(), sig_, v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::tracing::type, v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), and v8::base::VectorOf().
Referenced by v8::internal::wasm::BuildWasmWrapper().
BuildChangeBigIntToInt64()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeBigIntToInt64 (OpIndex input, OpIndex context, compiler::turboshaft::OptionalOpIndex frame_state) [inline]
Definition at line 912 of file wrappers.cc.
                                                     {
    OpIndex target;
    if (Is64()) {
      target = GetTargetForBuiltinCall(Builtin::kBigIntToI64);
    } else {
      // On 32-bit platforms we already set the target to the
      // BigIntToI32Pair builtin here, so that we don't have to replace the
      // target in the int64-lowering.
      target = GetTargetForBuiltinCall(Builtin::kBigIntToI32Pair);
    }
    CallDescriptor* call_descriptor =
        GetBigIntToI64CallDescriptor(frame_state.valid());
    const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
        call_descriptor, compiler::CanThrow::kNo,
        compiler::LazyDeoptOnThrow::kNo, __ graph_zone());
    return frame_state.valid()
               ? __ Call(target, frame_state.value(),
                         base::VectorOf({input, context}), ts_call_descriptor)
               : __ Call(target, {input, context}, ts_call_descriptor);
  }
References __, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), GetBigIntToI64CallDescriptor(), GetTargetForBuiltinCall(), v8::internal::Is64(), v8::internal::compiler::kNo, v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::base::VectorOf().
BuildChangeFloat32ToNumber()
V<Number> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeFloat32ToNumber (V< Float32 > value) [inline]
Definition at line 185 of file wrappers.cc.
                                                         {
    return CallBuiltin<WasmFloat32ToNumberDescriptor>(
        Builtin::kWasmFloat32ToNumber, Operator::kNoProperties, value);
  }
References v8::internal::compiler::Operator::kNoProperties, and v8::internal::value.
Referenced by ToJS().
BuildChangeFloat64ToNumber()
V<Number> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeFloat64ToNumber (V< Float64 > value) [inline]
Definition at line 190 of file wrappers.cc.
                                                         {
    return CallBuiltin<WasmFloat64ToTaggedDescriptor>(
        Builtin::kWasmFloat64ToNumber, Operator::kNoProperties, value);
  }
References v8::internal::compiler::Operator::kNoProperties, and v8::internal::value.
Referenced by ToJS().
BuildChangeInt32ToNumber()
V<Number> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeInt32ToNumber (V< Word32 > value) [inline]
Definition at line 160 of file wrappers.cc.
                                                      {
    // We expect most integers at runtime to be Smis, so it is important for
    // wrapper performance that Smi conversion be inlined.
    if (SmiValuesAre32Bits()) {
      return BuildChangeInt32ToSmi(value);
    }
    DCHECK(SmiValuesAre31Bits());
    // Double value to test if value can be a Smi, and if so, to convert it.
    V<Tuple<Word32, Word32>> add = __ Int32AddCheckOverflow(value, value);
    V<Word32> ovf = __ template Projection<1>(add);
    ScopedVar<Number> result(this, OpIndex::Invalid());
    IF_NOT (UNLIKELY(ovf)) {
      // If it didn't overflow, the result is {2 * value} as pointer-sized
      // value.
      result = __ BitcastWordPtrToSmi(
          __ ChangeInt32ToIntPtr(__ template Projection<0>(add)));
    } ELSE{
      // Otherwise, call builtin, to convert to a HeapNumber.
      result = CallBuiltin<WasmInt32ToHeapNumberDescriptor>(
          Builtin::kWasmInt32ToHeapNumber, Operator::kNoProperties, value);
    }
    return result;
  }
References __, BuildChangeInt32ToSmi(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::Operator::kNoProperties, v8::base::internal::result, v8::internal::SmiValuesAre31Bits(), v8::internal::SmiValuesAre32Bits(), and v8::internal::value.
Referenced by ToJS().
BuildChangeInt32ToSmi()
V<Smi> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeInt32ToSmi (V< Word32 > value) [inline]
Definition at line 117 of file wrappers.cc.
                                                {
    // With pointer compression, only the lower 32 bits are used.
    return V<Smi>::Cast(COMPRESS_POINTERS_BOOL
                            ? __ BitcastWord32ToWord64(__ Word32ShiftLeft(
                                  value, BuildSmiShiftBitsConstant32()))
                            : __ Word64ShiftLeft(__ ChangeInt32ToInt64(value),
                                                 BuildSmiShiftBitsConstant()));
  }
References __, BuildSmiShiftBitsConstant(), BuildSmiShiftBitsConstant32(), v8::internal::compiler::turboshaft::V< T >::Cast(), COMPRESS_POINTERS_BOOL, and v8::internal::value.
Referenced by BuildChangeInt32ToNumber().
BuildChangeSmiToInt32()
V<Word32> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeSmiToInt32 (OpIndex value) [inline]
Definition at line 784 of file wrappers.cc.
                                                 {
    return COMPRESS_POINTERS_BOOL
               ? __ Word32ShiftRightArithmetic(value,
                                               BuildSmiShiftBitsConstant32())
               : __
                 TruncateWordPtrToWord32(__ WordPtrShiftRightArithmetic(
                     value, BuildSmiShiftBitsConstant()));
  }
References __, BuildSmiShiftBitsConstant(), BuildSmiShiftBitsConstant32(), COMPRESS_POINTERS_BOOL, and v8::internal::value.
Referenced by BuildChangeTaggedToInt32(), and FromJSFast().
BuildChangeTaggedToFloat64()
V<Float64> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeTaggedToFloat64 (OpIndex value, OpIndex context, compiler::turboshaft::OptionalOpIndex frame_state) [inline]
Definition at line 866 of file wrappers.cc.
                                                     {
    OpIndex call = frame_state.valid()
                       ? CallBuiltin<WasmTaggedToFloat64Descriptor>(
                             Builtin::kWasmTaggedToFloat64, frame_state.value(),
                             Operator::kNoProperties, value, context)
                       : CallBuiltin<WasmTaggedToFloat64Descriptor>(
                             Builtin::kWasmTaggedToFloat64,
                             Operator::kNoProperties, value, context);
    // The source position here is needed for asm.js, see the comment on the
    // source position of the call to JavaScript in the wasm-to-js wrapper.
    __ output_graph().source_positions()[call] = SourcePosition(1);
    return call;
  }
References __, v8::internal::compiler::Operator::kNoProperties, v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::internal::value.
BuildChangeTaggedToInt32()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeTaggedToInt32 (OpIndex value, OpIndex context, compiler::turboshaft::OptionalOpIndex frame_state) [inline]
Definition at line 882 of file wrappers.cc.
                                                     {
    // We expect most integers at runtime to be Smis, so it is important for
    // wrapper performance that Smi conversion be inlined.
    ScopedVar<Word32> result(this, OpIndex::Invalid());
    IF (__ IsSmi(value)) {
      result = BuildChangeSmiToInt32(value);
    } ELSE{
      OpIndex call =
          frame_state.valid()
              ? CallBuiltin<WasmTaggedNonSmiToInt32Descriptor>(
                    Builtin::kWasmTaggedNonSmiToInt32, frame_state.value(),
                    Operator::kNoProperties, value, context)
              : CallBuiltin<WasmTaggedNonSmiToInt32Descriptor>(
                    Builtin::kWasmTaggedNonSmiToInt32, Operator::kNoProperties,
                    value, context);
      result = call;
      // The source position here is needed for asm.js, see the comment on the
      // source position of the call to JavaScript in the wasm-to-js wrapper.
      __ output_graph().source_positions()[call] = SourcePosition(1);
    }
    return result;
  }
References __, BuildChangeSmiToInt32(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::IsSmi(), v8::internal::compiler::Operator::kNoProperties, v8::base::internal::result, v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::internal::value.
BuildCheckString()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCheckString (OpIndex input, OpIndex js_context, CanonicalValueType type) [inline]
Definition at line 839 of file wrappers.cc.
                                                    {
    auto done = __ NewBlock();
    auto type_error = __ NewBlock();
    ScopedVar<Object> result(this, LOAD_ROOT(WasmNull));
    __ GotoIf(__ IsSmi(input), type_error, BranchHint::kFalse);
    if (type.is_nullable()) {
      auto not_null = __ NewBlock();
      __ GotoIfNot(__ TaggedEqual(input, LOAD_ROOT(NullValue)), not_null);
      __ Goto(done);
      __ Bind(not_null);
    }
    V<Map> map = LoadMap(input);
    OpIndex instance_type = LoadInstanceType(map);
    OpIndex check = __ Uint32LessThan(instance_type,
                                      __ Word32Constant(FIRST_NONSTRING_TYPE));
    result = input;
    __ GotoIf(check, done, BranchHint::kTrue);
    __ Goto(type_error);
    __ Bind(type_error);
    CallRuntime(__ phase_zone(), Runtime::kWasmThrowJSTypeError, {},
                js_context);
    __ Unreachable();
    __ Bind(done);
    return result;
  }
References __, v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::FIRST_NONSTRING_TYPE, v8::internal::IsSmi(), v8::internal::kFalse, v8::internal::kTrue, LOAD_ROOT, LoadInstanceType(), LoadMap(), v8::base::internal::result, and v8::internal::tracing::type.
BuildJSToWasmWrapper()
void v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper (bool receiver_is_first_param) [inline]
Definition at line 413 of file wrappers.cc.
                                                          {
    const bool do_conversion = true;
    const compiler::turboshaft::OptionalOpIndex frame_state =
        compiler::turboshaft::OptionalOpIndex::Nullopt();
    const bool set_in_wasm_flag = true;
    const int wasm_param_count = static_cast<int>(sig_->parameter_count());
    __ Bind(__ NewBlock());
    // Create the js_closure and js_context parameters.
    V<JSFunction> js_closure =
        __ Parameter(compiler::Linkage::kJSCallClosureParamIndex,
                     RegisterRepresentation::Tagged());
    V<Context> js_context = __ Parameter(
        compiler::Linkage::GetJSCallContextParamIndex(wasm_param_count + 1),
        RegisterRepresentation::Tagged());
    V<SharedFunctionInfo> shared =
        __ Load(js_closure, LoadOp::Kind::TaggedBase(),
                MemoryRepresentation::TaggedPointer(),
                JSFunction::kSharedFunctionInfoOffset);
    V<WasmFunctionData> function_data =
        V<WasmFunctionData>::Cast(__ LoadTrustedPointerField(
            shared, LoadOp::Kind::TaggedBase(),
            kWasmFunctionDataIndirectPointerTag,
            SharedFunctionInfo::kTrustedFunctionDataOffset));
    if (!IsJSCompatibleSignature(sig_)) {
      // Throw a TypeError. Use the js_context of the calling javascript
      // function (passed as a parameter), such that the generated code is
      // js_context independent.
      CallRuntime(__ phase_zone(), Runtime::kWasmThrowJSTypeError, {},
                  js_context);
      __ Unreachable();
      return;
    }
    const int args_count = wasm_param_count + 1; // +1 for wasm_code.
    // Check whether the signature of the function allows for a fast
    // transformation (if any params exist that need transformation).
    // Create a fast transformation path, only if it does.
    bool include_fast_path =
        do_conversion && wasm_param_count > 0 && QualifiesForFastTransform();
    // Prepare Param() nodes. Param() nodes can only be created once,
    // so we need to use the same nodes along all possible transformation paths.
    base::SmallVector<OpIndex, 16> params(args_count);
    const int param_offset = receiver_is_first_param ? 0 : 1;
    for (int i = 0; i < wasm_param_count; ++i) {
      params[i] =
          __ Parameter(i + param_offset, RegisterRepresentation::Tagged());
    }
    Label<Object> done(&Asm());
    V<Object> jsval;
    if (include_fast_path) {
      TSBlock* slow_path = __ NewBlock();
      // Check if the params received on runtime can be actually transformed
      // using the fast transformation. When a param that cannot be transformed
      // fast is encountered, skip checking the rest and fall back to the slow
      // path.
      for (int i = 0; i < wasm_param_count; ++i) {
        CanTransformFast(params[i], sig_->GetParam(i), slow_path);
      }
      // Convert JS parameters to wasm numbers using the fast transformation
      // and build the call.
      base::SmallVector<OpIndex, 16> args(args_count);
      for (int i = 0; i < wasm_param_count; ++i) {
        OpIndex wasm_param = FromJSFast(params[i], sig_->GetParam(i));
        args[i + 1] = wasm_param;
      }
      jsval =
          BuildCallAndReturn(js_context, function_data, base::VectorOf(args),
                             do_conversion, set_in_wasm_flag);
      GOTO(done, jsval);
      __ Bind(slow_path);
    }
    // Convert JS parameters to wasm numbers using the default transformation
    // and build the call.
    base::SmallVector<OpIndex, 16> args(args_count);
    for (int i = 0; i < wasm_param_count; ++i) {
      if (do_conversion) {
        args[i + 1] =
            FromJS(params[i], js_context, sig_->GetParam(i), frame_state);
      } else {
        OpIndex wasm_param = params[i];
        // For Float32 parameters
        // we set UseInfo::CheckedNumberOrOddballAsFloat64 in
        // simplified-lowering and we need to add here a conversion from Float64
        // to Float32.
        if (sig_->GetParam(i).kind() == kF32) {
          wasm_param = __ TruncateFloat64ToFloat32(wasm_param);
        }
        args[i + 1] = wasm_param;
      }
    }
    jsval = BuildCallAndReturn(js_context, function_data, base::VectorOf(args),
                               do_conversion, set_in_wasm_flag);
    // If both the default and a fast transformation paths are present,
    // get the return value based on the path used.
    if (include_fast_path) {
      GOTO(done, jsval);
      BIND(done, result);
      __ Return(result);
    } else {
      __ Return(jsval);
    }
  }
References __, v8::base::args, v8::internal::wasm::WasmGraphBuilderBase::Asm(), BuildCallAndReturn(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), CanTransformFast(), v8::internal::compiler::turboshaft::V< T >::Cast(), FromJS(), FromJSFast(), v8::internal::compiler::Linkage::GetJSCallContextParamIndex(), v8::internal::Signature< T >::GetParam(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::IsJSCompatibleSignature(), v8::internal::kF32, v8::internal::compiler::Linkage::kJSCallClosureParamIndex, v8::Load(), v8::internal::compiler::turboshaft::OptionalOpIndex::Nullopt(), v8::internal::Signature< T >::parameter_count(), QualifiesForFastTransform(), v8::base::internal::result, sig_, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), and v8::base::VectorOf().
Referenced by v8::internal::wasm::BuildWasmWrapper().
BuildLoadCallTargetFromExportedFunctionData()
V<WordPtr> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildLoadCallTargetFromExportedFunctionData (V< WasmFunctionData > function_data) [inline]
Definition at line 1267 of file wrappers.cc.
                                         {
    // TODO(sroettger): this code should do a signature check, but it's only
    // used for CAPI.
    V<WasmInternalFunction> internal =
        V<WasmInternalFunction>::Cast(__ LoadProtectedPointerField(
            function_data, LoadOp::Kind::TaggedBase().Immutable(),
            WasmFunctionData::kProtectedInternalOffset));
    V<Word32> code_pointer = __ Load(
        internal, LoadOp::Kind::TaggedBase(), MemoryRepresentation::Uint32(),
        WasmInternalFunction::kRawCallTargetOffset);
    constexpr size_t entry_size_log2 =
        std::bit_width(sizeof(WasmCodePointerTableEntry)) - 1;
    return __ Load(
        __ ExternalConstant(ExternalReference::wasm_code_pointer_table()),
        __ ChangeUint32ToUintPtr(code_pointer), LoadOp::Kind::RawAligned(),
        MemoryRepresentation::UintPtr(), 0, entry_size_log2);
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Referenced by BuildCapiCallWrapper().
BuildMultiReturnFixedArrayFromIterable()
V<FixedArray> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildMultiReturnFixedArrayFromIterable (OpIndex iterable, V< Context > context) [inline]
Definition at line 1240 of file wrappers.cc.
                                                                           {
    V<Smi> length = __ SmiConstant(Smi::FromIntptr(sig_->return_count()));
    return CallBuiltin<IterableToFixedArrayForWasmDescriptor>(
        Builtin::kIterableToFixedArrayForWasm, Operator::kEliminatable,
        iterable, length, context);
  }
References __, v8::internal::Smi::FromIntptr(), v8::internal::compiler::Operator::kEliminatable, v8::internal::length, v8::internal::Signature< T >::return_count(), and sig_.
Referenced by BuildWasmToJSWrapper().
BuildReceiverNode()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildReceiverNode (OpIndex callable_node, OpIndex native_context, V< Undefined > undefined_node) [inline]
Definition at line 1127 of file wrappers.cc.
                                                         {
    // Check function strict bit.
    V<SharedFunctionInfo> shared_function_info =
        LoadSharedFunctionInfo(callable_node);
    OpIndex flags = __ Load(shared_function_info, LoadOp::Kind::TaggedBase(),
                            MemoryRepresentation::Int32(),
                            SharedFunctionInfo::kFlagsOffset);
    OpIndex strict_check = __ Word32BitwiseAnd(
        flags, __ Word32Constant(SharedFunctionInfo::IsNativeBit::kMask |
                                 SharedFunctionInfo::IsStrictBit::kMask));
    // Load global receiver if sloppy else use undefined.
    ScopedVar<Object> strict_d(this, OpIndex::Invalid());
    IF (strict_check) {
      strict_d = undefined_node;
    } ELSE {
      strict_d =
          __ LoadFixedArrayElement(native_context, Context::GLOBAL_PROXY_INDEX);
    }
    return strict_d;
  }
References __, v8::internal::flags, v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::Load(), LoadSharedFunctionInfo(), v8::internal::native_context, and v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase().
Referenced by BuildWasmToJSWrapper().
BuildSmiShiftBitsConstant()
V<Word32> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSmiShiftBitsConstant () [inline]
Definition at line 776 of file wrappers.cc.
                                        {
    return __ Word32Constant(kSmiShiftSize + kSmiTagSize);
  }
References __, v8::internal::kSmiShiftSize, and v8::internal::kSmiTagSize.
Referenced by BuildChangeInt32ToSmi(), and BuildChangeSmiToInt32().
BuildSmiShiftBitsConstant32()
V<Word32> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSmiShiftBitsConstant32 () [inline]
Definition at line 780 of file wrappers.cc.
                                          {
    return __ Word32Constant(kSmiShiftSize + kSmiTagSize);
  }
References __, v8::internal::kSmiShiftSize, and v8::internal::kSmiTagSize.
Referenced by BuildChangeInt32ToSmi(), and BuildChangeSmiToInt32().
BuildSuspend()
V<Object> v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend (V< Object > value, V< Object > import_data, V< WordPtr > * old_sp, V< WordPtr > old_limit) [inline]
Definition at line 1156 of file wrappers.cc.
                                                                   {
    // If value is a promise, suspend to the js-to-wasm prompt, and resume later
    // with the promise's resolved value.
    ScopedVar<Object> result(this, value);
    ScopedVar<WordPtr> old_sp_var(this, *old_sp);
    OpIndex native_context = __ Load(import_data, LoadOp::Kind::TaggedBase(),
                                     MemoryRepresentation::TaggedPointer(),
                                     WasmImportData::kNativeContextOffset);
    OpIndex promise_ctor = __ LoadFixedArrayElement(
        native_context, Context::PROMISE_FUNCTION_INDEX);
    OpIndex promise_resolve = GetBuiltinPointerTarget(Builtin::kPromiseResolve);
    auto* resolve_call_desc =
        GetBuiltinCallDescriptor(Builtin::kPromiseResolve, __ graph_zone());
    base::SmallVector<OpIndex, 16> resolve_args{promise_ctor, value,
                                                native_context};
    OpIndex promise = __ Call(promise_resolve, OpIndex::Invalid(),
                              base::VectorOf(resolve_args), resolve_call_desc);
    OpIndex suspender = LOAD_ROOT(ActiveSuspender);
    IF (__ TaggedEqual(suspender, LOAD_ROOT(UndefinedValue))) {
      V<Smi> error = __ SmiConstant(Smi::FromInt(
          static_cast<int32_t>(MessageTemplate::kWasmSuspendError)));
      CallRuntime(__ phase_zone(), Runtime::kThrowWasmSuspendError, {error},
                  native_context);
      __ Unreachable();
    }
    if (v8_flags.stress_wasm_stack_switching) {
      V<Word32> for_stress_testing = __ TaggedEqual(
          __ LoadTaggedField(suspender, WasmSuspenderObject::kResumeOffset),
          LOAD_ROOT(UndefinedValue));
      IF (for_stress_testing) {
        V<Smi> error = __ SmiConstant(Smi::FromInt(
            static_cast<int32_t>(MessageTemplate::kWasmSuspendJSFrames)));
        CallRuntime(__ phase_zone(), Runtime::kThrowWasmSuspendError, {error},
                    native_context);
        __ Unreachable();
      }
    }
    // If {old_sp} is null, it must be that we were on the central stack
    // before entering the wasm-to-js wrapper, which means that there are JS
    // frames in the current suspender. JS frames cannot be suspended, so
    // trap.
    OpIndex has_js_frames = __ WordPtrEqual(__ IntPtrConstant(0), *old_sp);
    IF (has_js_frames) {
      V<Smi> error = __ SmiConstant(Smi::FromInt(
          static_cast<int32_t>(MessageTemplate::kWasmSuspendJSFrames)));
      CallRuntime(__ phase_zone(), Runtime::kThrowWasmSuspendError, {error},
                  native_context);
      __ Unreachable();
    }
    V<Object> on_fulfilled = __ Load(suspender, LoadOp::Kind::TaggedBase(),
                                     MemoryRepresentation::TaggedPointer(),
                                     WasmSuspenderObject::kResumeOffset);
    V<Object> on_rejected = __ Load(suspender, LoadOp::Kind::TaggedBase(),
                                    MemoryRepresentation::TaggedPointer(),
                                    WasmSuspenderObject::kRejectOffset);
    OpIndex promise_then =
        GetBuiltinPointerTarget(Builtin::kPerformPromiseThen);
    auto* then_call_desc =
        GetBuiltinCallDescriptor(Builtin::kPerformPromiseThen, __ graph_zone());
    base::SmallVector<OpIndex, 16> args{promise, on_fulfilled, on_rejected,
                                        LOAD_ROOT(UndefinedValue),
                                        native_context};
    __ Call(promise_then, OpIndex::Invalid(), base::VectorOf(args),
            then_call_desc);
    OpIndex suspend = GetTargetForBuiltinCall(Builtin::kWasmSuspend);
    auto* suspend_call_descriptor =
        GetBuiltinCallDescriptor(Builtin::kWasmSuspend, __ graph_zone());
    BuildSwitchBackFromCentralStack(*old_sp, old_limit);
    V<Object> resolved =
        __ Call<Object>(suspend, {suspender}, suspend_call_descriptor);
    old_sp_var = BuildSwitchToTheCentralStack(old_limit);
    result = resolved;
    *old_sp = old_sp_var;
    return result;
  }
References __, v8::base::args, v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::Smi::FromInt(), v8::internal::wasm::anonymous_namespace{wrappers.cc}::GetBuiltinCallDescriptor(), v8::internal::wasm::WasmGraphBuilderBase::GetBuiltinPointerTarget(), GetTargetForBuiltinCall(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::Load(), LOAD_ROOT, v8::internal::native_context, v8::base::internal::result, v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::v8_flags, v8::internal::value, and v8::base::VectorOf().
Referenced by BuildWasmToJSWrapper().
BuildWasmToJSWrapper()
void v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper (ImportCallKind kind, int expected_arity, Suspend suspend) [inline]
Definition at line 524 of file wrappers.cc.
                                             {
    int wasm_count = static_cast<int>(sig_->parameter_count());
    __ Bind(__ NewBlock());
    base::SmallVector<OpIndex, 16> wasm_params(wasm_count);
    OpIndex ref = __ Parameter(0, RegisterRepresentation::Tagged());
    for (int i = 0; i < wasm_count; ++i) {
      RegisterRepresentation rep = RepresentationFor(sig_->GetParam(i));
      wasm_params[i] = (__ Parameter(1 + i, rep));
    }
    V<Context> native_context = __ Load(ref, LoadOp::Kind::TaggedBase(),
                                        MemoryRepresentation::TaggedPointer(),
                                        WasmImportData::kNativeContextOffset);
    if (kind == ImportCallKind::kRuntimeTypeError) {
      // =======================================================================
      // === Runtime TypeError =================================================
      // =======================================================================
      CallRuntime(zone_, Runtime::kWasmThrowJSTypeError, {}, native_context);
      __ Unreachable();
      return;
    }
    V<Undefined> undefined_node = LOAD_ROOT(UndefinedValue);
    int pushed_count = std::max(expected_arity, wasm_count);
    // 5 extra arguments: receiver, new target, arg count, dispatch handle and
    // context.
    bool has_dispatch_handle =
        kind == ImportCallKind::kUseCallBuiltin
            ? false
            : V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL;
    base::SmallVector<OpIndex, 16> args(pushed_count + 4 +
                                        (has_dispatch_handle ? 1 : 0));
    SBXCHECK_LT(
        args.size(),
        std::numeric_limits<
            decltype(compiler::turboshaft::Operation::input_count)>::max());
    // Position of the first wasm argument in the JS arguments.
    int pos = kind == ImportCallKind::kUseCallBuiltin ? 3 : 1;
    pos = AddArgumentNodes(base::VectorOf(args), pos, wasm_params, sig_,
                           native_context);
    for (int i = wasm_count; i < expected_arity; ++i) {
      args[pos++] = undefined_node;
    }
    V<JSFunction> callable_node = __ Load(ref, LoadOp::Kind::TaggedBase(),
                                          MemoryRepresentation::TaggedPointer(),
                                          WasmImportData::kCallableOffset);
    auto [old_sp, old_limit] = BuildSwitchToTheCentralStackIfNeeded();
    BuildModifyThreadInWasmFlag(__ phase_zone(), false);
    OpIndex call = OpIndex::Invalid();
    switch (kind) {
      // =======================================================================
      // === JS Functions ======================================================
      // =======================================================================
      case ImportCallKind::kJSFunction: {
        auto call_descriptor = compiler::Linkage::GetJSCallDescriptor(
            __ graph_zone(), false, pushed_count + 1, CallDescriptor::kNoFlags);
        const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
            call_descriptor, compiler::CanThrow::kYes,
            compiler::LazyDeoptOnThrow::kNo, __ graph_zone());
        // Determine receiver at runtime.
        args[0] =
            BuildReceiverNode(callable_node, native_context, undefined_node);
        DCHECK_EQ(pos, pushed_count + 1);
        args[pos++] = undefined_node; // new target
        args[pos++] =
            __ Word32Constant(JSParameterCount(wasm_count)); // argument count
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
        args[pos++] = __ Word32Constant(kPlaceholderDispatchHandle.value());
#endif
        args[pos++] = LoadContextFromJSFunction(callable_node);
        call = __ Call(callable_node, OpIndex::Invalid(), base::VectorOf(args),
                       ts_call_descriptor);
        break;
      }
      // =======================================================================
      // === General case of unknown callable ==================================
      // =======================================================================
      case ImportCallKind::kUseCallBuiltin: {
        DCHECK_EQ(expected_arity, wasm_count);
        OpIndex target = GetBuiltinPointerTarget(Builtin::kCall_ReceiverIsAny);
        args[0] = callable_node;
        args[1] =
            __ Word32Constant(JSParameterCount(wasm_count)); // argument count
        args[2] = undefined_node; // receiver
        auto call_descriptor = compiler::Linkage::GetStubCallDescriptor(
            __ graph_zone(), CallTrampolineDescriptor{}, wasm_count + 1,
            CallDescriptor::kNoFlags, Operator::kNoProperties,
            StubCallMode::kCallBuiltinPointer);
        const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
            call_descriptor, compiler::CanThrow::kYes,
            compiler::LazyDeoptOnThrow::kNo, __ graph_zone());
        // The native_context is sufficient here, because all kind of callables
        // which depend on the context provide their own context. The context
        // here is only needed if the target is a constructor to throw a
        // TypeError, if the target is a native function, or if the target is a
        // callable JSObject, which can only be constructed by the runtime.
        args[pos++] = native_context;
        call = __ Call(target, OpIndex::Invalid(), base::VectorOf(args),
                       ts_call_descriptor);
        break;
      }
      default:
        UNIMPLEMENTED();
    }
    // For asm.js the error location can differ depending on whether an
    // exception was thrown in imported JS code or an exception was thrown in
    // the ToNumber builtin that converts the result of the JS code a
    // WebAssembly value. The source position allows asm.js to determine the
    // correct error location. Source position 1 encodes the call to ToNumber,
    // source position 0 encodes the call to the imported JS code.
    __ output_graph().source_positions()[call] = SourcePosition(0);
    DCHECK(call.valid());
    if (suspend == kSuspend) {
      call = BuildSuspend(call, ref, &old_sp, old_limit);
    }
    // Convert the return value(s) back.
    OpIndex val;
    base::SmallVector<OpIndex, 8> wasm_values;
    if (sig_->return_count() <= 1) {
      val = sig_->return_count() == 0
                ? __ Word32Constant(0)
                : FromJS(call, native_context, sig_->GetReturn());
    } else {
      V<FixedArray> fixed_array =
          BuildMultiReturnFixedArrayFromIterable(call, native_context);
      wasm_values.resize(sig_->return_count());
      for (unsigned i = 0; i < sig_->return_count(); ++i) {
        wasm_values[i] = FromJS(__ LoadFixedArrayElement(fixed_array, i),
                                native_context, sig_->GetReturn(i));
      }
    }
    BuildModifyThreadInWasmFlag(__ phase_zone(), true);
    BuildSwitchBackFromCentralStack(old_sp, old_limit);
    if (sig_->return_count() <= 1) {
      __ Return(val);
    } else {
      __ Return(__ Word32Constant(0), base::VectorOf(wasm_values));
    }
  }
References __, AddArgumentNodes(), v8::base::args, v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlag(), BuildMultiReturnFixedArrayFromIterable(), BuildReceiverNode(), BuildSuspend(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStackIfNeeded(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::DCHECK(), DCHECK_EQ, false, FromJS(), v8::internal::wasm::WasmGraphBuilderBase::GetBuiltinPointerTarget(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::Signature< T >::GetParam(), v8::internal::Signature< T >::GetReturn(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::JSParameterCount(), v8::internal::kCallBuiltinPointer, v8::internal::wasm::kJSFunction, v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, v8::internal::kPlaceholderDispatchHandle(), v8::internal::wasm::kRuntimeTypeError, v8::internal::wasm::kSuspend, v8::internal::wasm::kUseCallBuiltin, v8::internal::compiler::kYes, v8::Load(), LOAD_ROOT, LoadContextFromJSFunction(), v8::internal::native_context, v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::base::SmallVector< T, kSize, Allocator >::resize(), v8::internal::Signature< T >::return_count(), SBXCHECK_LT, sig_, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::UNIMPLEMENTED(), V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL, v8::internal::compiler::turboshaft::OpIndex::valid(), v8::base::StrongAlias< TagType, UnderlyingType >::value(), v8::base::VectorOf(), and v8::internal::wasm::WasmGraphBuilderBase::zone_.
Referenced by v8::internal::wasm::BuildWasmWrapper().
CallBuiltin() [1/2]
template<typename Descriptor , typename... Args>
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::CallBuiltin (Builtin name, Operator::Properties properties, Args... args) [inline]
Definition at line 148 of file wrappers.cc.
                                    {
    auto call_descriptor = compiler::Linkage::GetStubCallDescriptor(
        __ graph_zone(), Descriptor(), 0, CallDescriptor::kNoFlags,
        Operator::kNoProperties, StubCallMode::kCallBuiltinPointer);
    const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
        call_descriptor, compiler::CanThrow::kNo,
        compiler::LazyDeoptOnThrow::kNo, __ graph_zone());
    V<WordPtr> call_target = GetTargetForBuiltinCall(name);
    return __ Call(call_target, {args...}, ts_call_descriptor);
  }
References __, v8::base::args, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), GetTargetForBuiltinCall(), v8::internal::kCallBuiltinPointer, v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, and v8::internal::wasm::name().
CallBuiltin() [2/2]
template<typename Descriptor , typename... Args>
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::CallBuiltin (Builtin name, OpIndex frame_state, Operator::Properties properties, Args... args) [inline]
Definition at line 132 of file wrappers.cc.
                                                                   {
    auto call_descriptor = compiler::Linkage::GetStubCallDescriptor(
        __ graph_zone(), Descriptor(), 0,
        frame_state.valid() ? CallDescriptor::kNeedsFrameState
                            : CallDescriptor::kNoFlags,
        Operator::kNoProperties, StubCallMode::kCallBuiltinPointer);
    const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
        call_descriptor, compiler::CanThrow::kNo,
        compiler::LazyDeoptOnThrow::kNo, __ graph_zone());
    V<WordPtr> call_target = GetTargetForBuiltinCall(name);
    return __ Call(call_target, frame_state, base::VectorOf({args...}),
                   ts_call_descriptor);
  }
References __, v8::base::args, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), GetTargetForBuiltinCall(), v8::internal::kCallBuiltinPointer, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, v8::internal::wasm::name(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::base::VectorOf().
CanTransformFast()
void v8::internal::wasm::WasmWrapperTSGraphBuilder::CanTransformFast (OpIndex input, CanonicalValueType type, TSBlock * slow_path) [inline]
Definition at line 1076 of file wrappers.cc.
                                            {
    switch (type.kind()) {
      case kI32: {
        __ GotoIfNot(LIKELY(__ IsSmi(input)), slow_path);
        return;
      }
      case kF32:
      case kF64: {
        TSBlock* done = __ NewBlock();
        __ GotoIf(__ IsSmi(input), done);
        V<Map> map = LoadMap(input);
        V<Map> heap_number_map = LOAD_ROOT(HeapNumberMap);
        // TODO(thibaudm): Handle map packing.
        V<Word32> is_heap_number = __ TaggedEqual(heap_number_map, map);
        __ GotoIf(LIKELY(is_heap_number), done);
        __ Goto(slow_path);
        __ Bind(done);
        return;
      }
      case kRef:
      case kRefNull:
      case kI64:
      case kS128:
      case kI8:
      case kI16:
      case kF16:
      case kTop:
      case kBottom:
      case kVoid:
        UNREACHABLE();
    }
  }
References __, v8::internal::IsSmi(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, LOAD_ROOT, LoadMap(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by BuildJSToWasmWrapper().
FromJS()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::FromJS (V< Object > input, OpIndex context, CanonicalValueType type, OptionalOpIndex frame_state = {}) [inline]
Definition at line 936 of file wrappers.cc.
                                               {}) {
    switch (type.kind()) {
      case kRef:
      case kRefNull: {
        switch (type.heap_representation_non_shared()) {
          // TODO(14034): Add more fast paths?
          case HeapType::kExtern: {
            if (type.kind() == kRef) {
              IF (UNLIKELY(__ TaggedEqual(input, LOAD_ROOT(NullValue)))) {
                CallRuntime(__ phase_zone(), Runtime::kWasmThrowJSTypeError, {},
                            context);
                __ Unreachable();
              }
            }
            if (v8_flags.experimental_wasm_shared &&
                type.heap_representation() == HeapType::kExternShared) {
              Label<Object> done(&asm_);
              IF_NOT (__ IsSmi(input)) {
                V<WordPtr> flags = __ LoadPageFlags(V<HeapObject>::Cast(input));
                V<WordPtr> shared_or_read_only = __ WordPtrBitwiseAnd(
                    flags, static_cast<uintptr_t>(
                               MemoryChunk::IN_WRITABLE_SHARED_SPACE |
                               MemoryChunk::READ_ONLY_HEAP));
                IF (UNLIKELY(__ WordPtrEqual(shared_or_read_only, 0))) {
                  // If it isn't shared, yet, use the runtime function.
                  std::initializer_list<const OpIndex> inputs = {
                      input, __ IntPtrConstant(IntToSmi(
                                 static_cast<int>(type.raw_bit_field())))};
                  GOTO(done, CallRuntime(__ phase_zone(),
                                         Runtime::kWasmJSToWasmObject, inputs,
                                         context));
                }
              }
              GOTO(done, input);
              BIND(done, result);
              return result;
            }
            return input;
          }
          case HeapType::kString:
            return BuildCheckString(input, context, type);
          case HeapType::kExn:
          case HeapType::kNoExn: {
            UNREACHABLE();
          }
          case HeapType::kNoExtern:
          case HeapType::kNone:
          case HeapType::kNoFunc:
          case HeapType::kI31:
          case HeapType::kAny:
          case HeapType::kFunc:
          case HeapType::kStruct:
          case HeapType::kArray:
          case HeapType::kEq:
          default: {
            // Make sure ValueType fits in a Smi.
            static_assert(ValueType::kLastUsedBit + 1 <= kSmiValueSize);
            std::initializer_list<const OpIndex> inputs = {
                input, __ IntPtrConstant(
                           IntToSmi(static_cast<int>(type.raw_bit_field())))};
            return CallRuntime(__ phase_zone(), Runtime::kWasmJSToWasmObject,
                               inputs, context);
          }
        }
      }
      case kF32:
        return __ TruncateFloat64ToFloat32(
            BuildChangeTaggedToFloat64(input, context, frame_state));
      case kF64:
        return BuildChangeTaggedToFloat64(input, context, frame_state);
      case kI32:
        return BuildChangeTaggedToInt32(input, context, frame_state);
      case kI64:
        // i64 values can only come from BigInt.
        return BuildChangeBigIntToInt64(input, context, frame_state);
      case kS128:
      case kI8:
      case kI16:
      case kF16:
      case kTop:
      case kBottom:
      case kVoid:
        // If this is reached, then IsJSCompatibleSignature() is too permissive.
        UNREACHABLE();
    }
  }
Referenced by BuildJSToWasmWrapper(), and BuildWasmToJSWrapper().
FromJSFast()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::FromJSFast (OpIndex input, CanonicalValueType type) [inline]
Definition at line 798 of file wrappers.cc.
                                                             {
    switch (type.kind()) {
      case kI32:
        return BuildChangeSmiToInt32(input);
      case kF32: {
        ScopedVar<Float32> result(this, OpIndex::Invalid());
        IF (__ IsSmi(input)) {
          result = __ ChangeInt32ToFloat32(__ UntagSmi(input));
        } ELSE {
          result = __ TruncateFloat64ToFloat32(HeapNumberToFloat64(input));
        }
        return result;
      }
      case kF64: {
        ScopedVar<Float64> result(this, OpIndex::Invalid());
        IF (__ IsSmi(input)) {
          result = __ ChangeInt32ToFloat64(__ UntagSmi(input));
        } ELSE{
          result = HeapNumberToFloat64(input);
        }
        return result;
      }
      case kRef:
      case kRefNull:
      case kI64:
      case kS128:
      case kI8:
      case kI16:
      case kF16:
      case kTop:
      case kBottom:
      case kVoid:
        UNREACHABLE();
    }
  }
References __, BuildChangeSmiToInt32(), HeapNumberToFloat64(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::IsSmi(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::base::internal::result, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by BuildJSToWasmWrapper().
GetBigIntToI64CallDescriptor()
CallDescriptor* v8::internal::wasm::WasmWrapperTSGraphBuilder::GetBigIntToI64CallDescriptor (bool needs_frame_state) [inline]
Definition at line 907 of file wrappers.cc.
                                                                       {
    return GetWasmEngine()->call_descriptors()->GetBigIntToI64Descriptor(
        needs_frame_state);
  }
References v8::internal::wasm::WasmEngine::call_descriptors(), v8::internal::compiler::WasmCallDescriptors::GetBigIntToI64Descriptor(), and v8::internal::wasm::GetWasmEngine().
Referenced by BuildChangeBigIntToInt64().
GetTargetForBuiltinCall()
V<WordPtr> v8::internal::wasm::WasmWrapperTSGraphBuilder::GetTargetForBuiltinCall (Builtin builtin) [inline]
Definition at line 126 of file wrappers.cc.
                                                      {
    return WasmGraphBuilderBase::GetTargetForBuiltinCall(
        builtin, StubCallMode::kCallBuiltinPointer);
  }
References v8::internal::wasm::WasmGraphBuilderBase::GetTargetForBuiltinCall(), and v8::internal::kCallBuiltinPointer.
Referenced by BuildCapiCallWrapper(), BuildChangeBigIntToInt64(), BuildSuspend(), and CallBuiltin().
HeapNumberToFloat64()
V<Float64> v8::internal::wasm::WasmWrapperTSGraphBuilder::HeapNumberToFloat64 (V< HeapNumber > input) [inline]
Definition at line 793 of file wrappers.cc.
                                                      {
    return __ template LoadField<Float64>(
        input, compiler::AccessBuilder::ForHeapNumberValue());
  }
References __, and v8::internal::compiler::AccessBuilder::ForHeapNumberValue().
Referenced by FromJSFast().
LoadContextFromJSFunction()
V<Context> v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadContextFromJSFunction (V< JSFunction > js_function) [inline]
Definition at line 1150 of file wrappers.cc.
                                                                  {
    return __ Load(js_function, LoadOp::Kind::TaggedBase(),
                   MemoryRepresentation::TaggedPointer(),
                   JSFunction::kContextOffset);
  }
References __, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer().
Referenced by BuildWasmToJSWrapper().
LoadExportedFunctionIndexAsSmi()
V<Smi> v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadExportedFunctionIndexAsSmi (V< Object > exported_function_data) [inline]
Definition at line 110 of file wrappers.cc.
                                                                          {
    return __ Load(exported_function_data,
                   LoadOp::Kind::TaggedBase().Immutable(),
                   MemoryRepresentation::TaggedSigned(),
                   WasmExportedFunctionData::kFunctionIndexOffset);
  }
References __, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned().
LoadInstanceType()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadInstanceType (V< Map > map) [inline]
Definition at line 834 of file wrappers.cc.
                                       {
    return __ Load(map, LoadOp::Kind::TaggedBase().Immutable(),
                   MemoryRepresentation::Uint16(), Map::kInstanceTypeOffset);
  }
References __, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16().
Referenced by BuildCheckString().
LoadMap()
V<Map> v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadMap (V< Object > object) [inline]
Definition at line 1065 of file wrappers.cc.
                                   {
    // TODO(thibaudm): Handle map packing.
    OpIndex map_word = __ Load(object, LoadOp::Kind::TaggedBase(),
                               MemoryRepresentation::TaggedPointer(), 0);
#ifdef V8_MAP_PACKING
    return UnpackMapWord(map_word);
#else
    return map_word;
#endif
  }
References __, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer().
Referenced by BuildCheckString(), and CanTransformFast().
LoadSharedFunctionInfo()
OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadSharedFunctionInfo (V< Object > js_function) [inline]
Definition at line 1121 of file wrappers.cc.
                                                        {
    return __ Load(js_function, LoadOp::Kind::TaggedBase(),
                   MemoryRepresentation::TaggedPointer(),
                   JSFunction::kSharedFunctionInfoOffset);
  }
References __, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer().
Referenced by BuildCapiCallWrapper(), and BuildReceiverNode().
QualifiesForFastTransform()
bool v8::internal::wasm::WasmWrapperTSGraphBuilder::QualifiesForFastTransform () [inline]
Definition at line 1029 of file wrappers.cc.
                                   {
    const int wasm_count = static_cast<int>(sig_->parameter_count());
    for (int i = 0; i < wasm_count; ++i) {
      CanonicalValueType type = sig_->GetParam(i);
      switch (type.kind()) {
        case kRef:
        case kRefNull:
        case kI64:
        case kS128:
        case kI8:
        case kI16:
        case kF16:
        case kTop:
        case kBottom:
        case kVoid:
          return false;
        case kI32:
        case kF32:
        case kF64:
          break;
      }
    }
    return true;
  }
References v8::internal::Signature< T >::GetParam(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::Signature< T >::parameter_count(), sig_, and v8::internal::tracing::type.
Referenced by BuildJSToWasmWrapper().
SafeLoad()
const OpIndex v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeLoad (OpIndex base, int offset, CanonicalValueType type) [inline]
Definition at line 1286 of file wrappers.cc.
                                                                            {
    int alignment = offset % type.value_kind_size();
    auto rep = MemoryRepresentation::FromMachineRepresentation(
        type.machine_representation());
    if (COMPRESS_POINTERS_BOOL && rep.IsCompressibleTagged()) {
      // We are loading tagged value from off-heap location, so we need to load
      // it as a full word otherwise we will not be able to decompress it.
      rep = MemoryRepresentation::UintPtr();
    }
    LoadOp::Kind load_kind = alignment == 0 ||
                                     compiler::turboshaft::SupportedOperations::
                                         IsUnalignedLoadSupported(rep)
                                 ? LoadOp::Kind::RawAligned()
                                 : LoadOp::Kind::RawUnaligned();
    return __ Load(base, load_kind, rep, offset);
  }
References __, COMPRESS_POINTERS_BOOL, v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineRepresentation(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported(), v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawUnaligned(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Referenced by BuildCapiCallWrapper().
SafeStore()
void v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeStore (int offset, CanonicalValueType type, OpIndex base, OpIndex value) [inline]
Definition at line 1248 of file wrappers.cc.
                                {
    int alignment = offset % type.value_kind_size();
    auto rep = MemoryRepresentation::FromMachineRepresentation(
        type.machine_representation());
    if (COMPRESS_POINTERS_BOOL && rep.IsCompressibleTagged()) {
      // We are storing tagged value to off-heap location, so we need to store
      // it as a full word otherwise we will not be able to decompress it.
      rep = MemoryRepresentation::UintPtr();
      value = __ BitcastTaggedToWordPtr(value);
    }
    StoreOp::Kind store_kind =
        alignment == 0 || compiler::turboshaft::SupportedOperations::
                              IsUnalignedStoreSupported(rep)
            ? StoreOp::Kind::RawAligned()
            : StoreOp::Kind::RawUnaligned();
    __ Store(base, value, store_kind, rep, compiler::kNoWriteBarrier, offset);
  }
References __, COMPRESS_POINTERS_BOOL, v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineRepresentation(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedStoreSupported(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawUnaligned(), v8::internal::wasm::liftoff::Store(), v8::internal::tracing::type, v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), and v8::internal::value.
Referenced by BuildCapiCallWrapper().
ToJS()
V<Object> v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS (OpIndex ret, CanonicalValueType type, V< Context > context) [inline]
Definition at line 195 of file wrappers.cc.
                                                                           {
    switch (type.kind()) {
      case kI32:
        return BuildChangeInt32ToNumber(ret);
      case kI64:
        return BuildChangeInt64ToBigInt(ret, StubCallMode::kCallBuiltinPointer);
      case kF32:
        return BuildChangeFloat32ToNumber(ret);
      case kF64:
        return BuildChangeFloat64ToNumber(ret);
      case kRef:
        switch (type.heap_representation_non_shared()) {
          case HeapType::kEq:
          case HeapType::kI31:
          case HeapType::kStruct:
          case HeapType::kArray:
          case HeapType::kAny:
          case HeapType::kExtern:
          case HeapType::kString:
          case HeapType::kNone:
          case HeapType::kNoFunc:
          case HeapType::kNoExtern:
            return ret;
          case HeapType::kExn:
          case HeapType::kNoExn:
          case HeapType::kBottom:
          case HeapType::kTop:
          case HeapType::kStringViewWtf8:
          case HeapType::kStringViewWtf16:
          case HeapType::kStringViewIter:
            UNREACHABLE();
          case HeapType::kFunc:
          default:
            if (type.heap_representation_non_shared() == HeapType::kFunc ||
                GetTypeCanonicalizer()->IsFunctionSignature(type.ref_index())) {
              // Function reference. Extract the external function.
              V<WasmInternalFunction> internal =
                  V<WasmInternalFunction>::Cast(__ LoadTrustedPointerField(
                      ret, LoadOp::Kind::TaggedBase(),
                      kWasmInternalFunctionIndirectPointerTag,
                      WasmFuncRef::kTrustedInternalOffset));
              ScopedVar<Object> maybe_external(
                  this, __ Load(internal, LoadOp::Kind::TaggedBase(),
                                MemoryRepresentation::TaggedPointer(),
                                WasmInternalFunction::kExternalOffset));
              IF (__ TaggedEqual(maybe_external, LOAD_ROOT(UndefinedValue))) {
                maybe_external =
                    CallBuiltin<WasmInternalFunctionCreateExternalDescriptor>(
                        Builtin::kWasmInternalFunctionCreateExternal,
                        Operator::kNoProperties, internal, context);
              }
              return maybe_external;
            } else {
              return ret;
            }
        }
      case kRefNull:
        switch (type.heap_representation_non_shared()) {
          case HeapType::kExtern:
          case HeapType::kNoExtern:
            return ret;
          case HeapType::kNone:
          case HeapType::kNoFunc:
            return LOAD_ROOT(NullValue);
          case HeapType::kExn:
          case HeapType::kNoExn:
            UNREACHABLE();
          case HeapType::kEq:
          case HeapType::kStruct:
          case HeapType::kArray:
          case HeapType::kString:
          case HeapType::kI31:
          case HeapType::kAny: {
            ScopedVar<Object> result(this, OpIndex::Invalid());
            IF_NOT (__ TaggedEqual(ret, LOAD_ROOT(WasmNull))) {
              result = ret;
            } ELSE{
              result = LOAD_ROOT(NullValue);
            }
            return result;
          }
          case HeapType::kFunc:
          default: {
            if (type.heap_representation_non_shared() == HeapType::kFunc ||
                GetTypeCanonicalizer()->IsFunctionSignature(type.ref_index())) {
              ScopedVar<Object> result(this, OpIndex::Invalid());
              IF (__ TaggedEqual(ret, LOAD_ROOT(WasmNull))) {
                result = LOAD_ROOT(NullValue);
              } ELSE{
                V<WasmInternalFunction> internal =
                    V<WasmInternalFunction>::Cast(__ LoadTrustedPointerField(
                        ret, LoadOp::Kind::TaggedBase(),
                        kWasmInternalFunctionIndirectPointerTag,
                        WasmFuncRef::kTrustedInternalOffset));
                V<Object> maybe_external =
                    __ Load(internal, LoadOp::Kind::TaggedBase(),
                            MemoryRepresentation::AnyTagged(),
                            WasmInternalFunction::kExternalOffset);
                IF (__ TaggedEqual(maybe_external, LOAD_ROOT(UndefinedValue))) {
                  V<Object> from_builtin =
                      CallBuiltin<WasmInternalFunctionCreateExternalDescriptor>(
                          Builtin::kWasmInternalFunctionCreateExternal,
                          Operator::kNoProperties, internal, context);
                  result = from_builtin;
                } ELSE{
                  result = maybe_external;
                }
              }
              return result;
            } else {
              ScopedVar<Object> result(this, OpIndex::Invalid());
              IF (__ TaggedEqual(ret, LOAD_ROOT(WasmNull))) {
                result = LOAD_ROOT(NullValue);
              } ELSE{
                result = ret;
              }
              return result;
            }
          }
        }
      case kI8:
      case kI16:
      case kF16:
      case kS128:
      case kVoid:
      case kTop:
      case kBottom:
        // If this is reached, then IsJSCompatibleSignature() is too permissive.
        UNREACHABLE();
    }
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), BuildChangeFloat32ToNumber(), BuildChangeFloat64ToNumber(), BuildChangeInt32ToNumber(), v8::internal::wasm::WasmGraphBuilderBase::BuildChangeInt64ToBigInt(), v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::HeapType::kArray, v8::internal::wasm::HeapType::kBottom, v8::internal::kCallBuiltinPointer, v8::internal::wasm::HeapType::kEq, v8::internal::wasm::HeapType::kExn, v8::internal::wasm::HeapType::kExtern, v8::internal::kF32, v8::internal::kF64, v8::internal::wasm::HeapType::kFunc, v8::internal::kI16, v8::internal::wasm::HeapType::kI31, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::wasm::HeapType::kNoExn, v8::internal::wasm::HeapType::kNoExtern, v8::internal::wasm::HeapType::kNoFunc, v8::internal::wasm::HeapType::kNone, v8::internal::compiler::Operator::kNoProperties, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::HeapType::kString, v8::internal::wasm::HeapType::kStringViewIter, v8::internal::wasm::HeapType::kStringViewWtf16, v8::internal::wasm::HeapType::kStringViewWtf8, v8::internal::wasm::HeapType::kStruct, v8::internal::wasm::HeapType::kTop, v8::internal::kTrustedInternalOffset, v8::Load(), LOAD_ROOT, v8::base::internal::result, v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by AddArgumentNodes(), and BuildCallAndReturn().
Member Data Documentation
sig_
const CanonicalSig* const v8::internal::wasm::WasmWrapperTSGraphBuilder::sig_ [private]
Definition at line 1304 of file wrappers.cc.
Referenced by BuildCallAndReturn(), BuildCapiCallWrapper(), BuildJSToWasmWrapper(), BuildMultiReturnFixedArrayFromIterable(), BuildWasmToJSWrapper(), and QualifiesForFastTransform().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wrappers.cc