v8::internal::compiler::ArrayBufferViewAccessBuilder Class Reference
Public Member Functions
ArrayBufferViewAccessBuilder (JSGraphAssembler *assembler, InstanceType instance_type, std::set< ElementsKind > candidates)
bool maybe_rab_gsab () const
std::optional< int > TryComputeStaticElementShift ()
std::optional< int > TryComputeStaticElementSize ()
TNode< UintPtrT > BuildLength (TNode< JSArrayBufferView > view, TNode< Context > context)
TNode< UintPtrT > BuildByteLength (TNode< JSArrayBufferView > view, TNode< Context > context)
TNode< Word32T > BuildDetachedOrOutOfBoundsCheck (TNode< JSArrayBufferView > view)
Private Member Functions
template<typename T >
TNode< T > MachineLoadField (FieldAccess const &access, TNode< HeapObject > object, const UseInfo &use_info)
Private Attributes
JSGraphAssembler * assembler_
InstanceType instance_type_
std::set< ElementsKind > candidates_
Detailed Description
Definition at line 575 of file graph-assembler.cc.
Constructor & Destructor Documentation
ArrayBufferViewAccessBuilder()
v8::internal::compiler::ArrayBufferViewAccessBuilder::ArrayBufferViewAccessBuilder (JSGraphAssembler * assembler, InstanceType instance_type, std::set< ElementsKind > candidates) [inline], [explicit]
Definition at line 577 of file graph-assembler.cc.
      : assembler_(assembler),
        instance_type_(instance_type),
        candidates_(std::move(candidates)) {
    DCHECK_NOT_NULL(assembler_);
    // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
    DCHECK(instance_type_ == JS_DATA_VIEW_TYPE ||
           instance_type_ == JS_TYPED_ARRAY_TYPE);
  }
References assembler_, v8::internal::DCHECK(), DCHECK_NOT_NULL, and instance_type_.
Member Function Documentation
BuildByteLength()
TNode<UintPtrT> v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength (TNode< JSArrayBufferView > view, TNode< Context > context) [inline]
Definition at line 760 of file graph-assembler.cc.
                                                          {
    auto& a = *assembler_;
    // Case 1: Normal (backed by AB/SAB) or non-length tracking backed by GSAB
    // (can't go oob once constructed)
    auto GsabFixedOrNormal = [&]() {
      return MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteLength(), view,
          UseInfo::Word());
    };
    // If we statically know we cannot have rab/gsab backed, we can simply
    // use load from the view.
    if (!maybe_rab_gsab()) {
      return GsabFixedOrNormal();
    }
    // Otherwise, we need to generate the checks for the view's bitfield.
    TNode<Word32T> bitfield = a.EnterMachineGraph<Word32T>(
        a.LoadField<Word32T>(AccessBuilder::ForJSArrayBufferViewBitField(),
                             view),
        UseInfo::TruncatingWord32());
    TNode<Word32T> length_tracking_bit = a.Word32And(
        bitfield, a.Uint32Constant(JSArrayBufferView::kIsLengthTracking));
    TNode<Word32T> backed_by_rab_bit = a.Word32And(
        bitfield, a.Uint32Constant(JSArrayBufferView::kIsBackedByRab));
    // Load the underlying buffer.
    TNode<HeapObject> buffer = a.LoadField<HeapObject>(
        AccessBuilder::ForJSArrayBufferViewBuffer(), view);
    // Case 2: Fixed length backed by RAB (can go oob once constructed)
    auto RabFixed = [&]() {
      TNode<UintPtrT> unchecked_byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteLength(), view,
          UseInfo::Word());
      TNode<UintPtrT> underlying_byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferByteLength(), buffer, UseInfo::Word());
      TNode<UintPtrT> byte_offset = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteOffset(), view,
          UseInfo::Word());
      return a
          .MachineSelectIf<UintPtrT>(a.UintPtrLessThanOrEqual(
              a.UintPtrAdd(byte_offset, unchecked_byte_length),
              underlying_byte_length))
          .Then([&]() { return unchecked_byte_length; })
          .Else([&]() { return a.UintPtrConstant(0); })
          .Value();
    };
    auto RoundDownToElementSize = [&](TNode<UintPtrT> byte_size) {
      if (auto shift_opt = TryComputeStaticElementShift()) {
        constexpr uintptr_t all_bits = static_cast<uintptr_t>(-1);
        if (*shift_opt == 0) return byte_size;
        return TNode<UintPtrT>::UncheckedCast(
            a.WordAnd(byte_size, a.UintPtrConstant(all_bits << (*shift_opt))));
      }
      DCHECK_EQ(instance_type_, JS_TYPED_ARRAY_TYPE);
      TNode<Map> typed_array_map = a.LoadField<Map>(
          AccessBuilder::ForMap(WriteBarrierKind::kNoWriteBarrier), view);
      TNode<Uint32T> elements_kind = a.LoadElementsKind(typed_array_map);
      TNode<Uint32T> element_shift =
          a.LookupByteShiftForElementsKind(elements_kind);
      return TNode<UintPtrT>::UncheckedCast(
          a.WordShl(a.WordShr(byte_size, element_shift), element_shift));
    };
    // Case 3: Length-tracking backed by RAB (JSArrayBuffer stores the length)
    auto RabTracking = [&]() {
      TNode<UintPtrT> byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferByteLength(), buffer, UseInfo::Word());
      TNode<UintPtrT> byte_offset = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteOffset(), view,
          UseInfo::Word());
      return a
          .MachineSelectIf<UintPtrT>(
              a.UintPtrLessThanOrEqual(byte_offset, byte_length))
          .Then([&]() {
            return RoundDownToElementSize(
                a.UintPtrSub(byte_length, byte_offset));
          })
          .Else([&]() { return a.UintPtrConstant(0); })
          .ExpectTrue()
          .Value();
    };
    // Case 4: Length-tracking backed by GSAB (BackingStore stores the length)
    auto GsabTracking = [&]() {
      TNode<Number> temp = TNode<Number>::UncheckedCast(a.TypeGuard(
          TypeCache::Get()->kJSArrayBufferViewByteLengthType,
          a.JSCallRuntime1(Runtime::kGrowableSharedArrayBufferByteLength,
                           buffer, context, std::nullopt, Operator::kNoWrite)));
      TNode<UintPtrT> byte_length =
          a.EnterMachineGraph<UintPtrT>(temp, UseInfo::Word());
      TNode<UintPtrT> byte_offset = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteOffset(), view,
          UseInfo::Word());
      return a
          .MachineSelectIf<UintPtrT>(
              a.UintPtrLessThanOrEqual(byte_offset, byte_length))
          .Then([&]() {
            return RoundDownToElementSize(
                a.UintPtrSub(byte_length, byte_offset));
          })
          .Else([&]() { return a.UintPtrConstant(0); })
          .ExpectTrue()
          .Value();
    };
    return a.MachineSelectIf<UintPtrT>(length_tracking_bit)
        .Then([&]() {
          return a.MachineSelectIf<UintPtrT>(backed_by_rab_bit)
              .Then(RabTracking)
              .Else(GsabTracking)
              .Value();
        })
        .Else([&]() {
          return a.MachineSelectIf<UintPtrT>(backed_by_rab_bit)
              .Then(RabFixed)
              .Else(GsabFixedOrNormal)
              .Value();
        })
        .Value();
  }
References assembler_, DCHECK_EQ, v8::internal::compiler::AccessBuilder::ForJSArrayBufferByteLength(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBitField(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteLength(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteOffset(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::TypeCache::Get(), instance_type_, v8::internal::compiler::TypeCache::kJSArrayBufferViewByteLengthType, v8::internal::compiler::Operator::kNoWrite, v8::internal::compiler::kNoWriteBarrier, maybe_rab_gsab(), v8::internal::compiler::UseInfo::TruncatingWord32(), TryComputeStaticElementShift(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::compiler::UseInfo::Word().
Referenced by v8::internal::compiler::JSGraphAssembler::ArrayBufferViewByteLength().
BuildDetachedOrOutOfBoundsCheck()
TNode<Word32T> v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck (TNode< JSArrayBufferView > view) [inline]
Definition at line 889 of file graph-assembler.cc.
                                     {
    auto& a = *assembler_;
    // Load the underlying buffer and its bitfield.
    TNode<HeapObject> buffer = a.LoadField<HeapObject>(
        AccessBuilder::ForJSArrayBufferViewBuffer(), view);
    // Mask the detached bit.
    TNode<Word32T> detached_bit = a.ArrayBufferDetachedBit(buffer);
    // If we statically know we cannot have rab/gsab backed, we are done here.
    if (!maybe_rab_gsab()) {
      return detached_bit;
    }
    // Otherwise, we need to generate the checks for the view's bitfield.
    TNode<Word32T> bitfield = a.EnterMachineGraph<Word32T>(
        a.LoadField<Word32T>(AccessBuilder::ForJSArrayBufferViewBitField(),
                             view),
        UseInfo::TruncatingWord32());
    TNode<Word32T> length_tracking_bit = a.Word32And(
        bitfield, a.Uint32Constant(JSArrayBufferView::kIsLengthTracking));
    TNode<Word32T> backed_by_rab_bit = a.Word32And(
        bitfield, a.Uint32Constant(JSArrayBufferView::kIsBackedByRab));
    auto RabLengthTracking = [&]() {
      TNode<UintPtrT> byte_offset = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteOffset(), view,
          UseInfo::Word());
      TNode<UintPtrT> underlying_byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferByteLength(), buffer, UseInfo::Word());
      return a.Word32Or(detached_bit,
                        a.UintPtrLessThan(underlying_byte_length, byte_offset));
    };
    auto RabFixed = [&]() {
      TNode<UintPtrT> unchecked_byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteLength(), view,
          UseInfo::Word());
      TNode<UintPtrT> byte_offset = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteOffset(), view,
          UseInfo::Word());
      TNode<UintPtrT> underlying_byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferByteLength(), buffer, UseInfo::Word());
      return a.Word32Or(
          detached_bit,
          a.UintPtrLessThan(underlying_byte_length,
                            a.UintPtrAdd(byte_offset, unchecked_byte_length)));
    };
    // Dispatch depending on rab/gsab and length tracking.
    return a.MachineSelectIf<Word32T>(backed_by_rab_bit)
        .Then([&]() {
          return a.MachineSelectIf<Word32T>(length_tracking_bit)
              .Then(RabLengthTracking)
              .Else(RabFixed)
              .Value();
        })
        .Else([&]() { return detached_bit; })
        .Value();
  }
References assembler_, v8::internal::compiler::AccessBuilder::ForJSArrayBufferByteLength(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBitField(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteLength(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteOffset(), maybe_rab_gsab(), v8::internal::compiler::UseInfo::TruncatingWord32(), and v8::internal::compiler::UseInfo::Word().
Referenced by v8::internal::compiler::JSGraphAssembler::CheckIfTypedArrayWasDetachedOrOutOfBounds().
BuildLength()
TNode<UintPtrT> v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength (TNode< JSArrayBufferView > view, TNode< Context > context) [inline]
Definition at line 622 of file graph-assembler.cc.
                                                      {
    auto& a = *assembler_;
    // Case 1: Normal (backed by AB/SAB) or non-length tracking backed by GSAB
    // (can't go oob once constructed)
    auto GsabFixedOrNormal = [&]() {
      TNode<UintPtrT> byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteLength(), view,
          UseInfo::Word());
      if (auto size_opt = TryComputeStaticElementSize()) {
        return a.UintPtrDiv(byte_length, a.UintPtrConstant(*size_opt));
      } else {
        TNode<Map> typed_array_map = a.LoadField<Map>(
            AccessBuilder::ForMap(WriteBarrierKind::kNoWriteBarrier), view);
        TNode<Uint32T> elements_kind = a.LoadElementsKind(typed_array_map);
        TNode<Uint32T> element_size =
            a.LookupByteSizeForElementsKind(elements_kind);
        return a.UintPtrDiv(byte_length, a.ChangeUint32ToUintPtr(element_size));
      }
    };
    // If we statically know we cannot have rab/gsab backed, we can simply
    // load from the view.
    if (!maybe_rab_gsab()) {
      return GsabFixedOrNormal();
    }
    // Otherwise, we need to generate the checks for the view's bitfield.
    TNode<Word32T> bitfield = a.EnterMachineGraph<Word32T>(
        a.LoadField<Word32T>(AccessBuilder::ForJSArrayBufferViewBitField(),
                             view),
        UseInfo::TruncatingWord32());
    TNode<Word32T> length_tracking_bit = a.Word32And(
        bitfield, a.Uint32Constant(JSArrayBufferView::kIsLengthTracking));
    TNode<Word32T> backed_by_rab_bit = a.Word32And(
        bitfield, a.Uint32Constant(JSArrayBufferView::kIsBackedByRab));
    // Load the underlying buffer.
    TNode<HeapObject> buffer = a.LoadField<HeapObject>(
        AccessBuilder::ForJSArrayBufferViewBuffer(), view);
    // Compute the element size.
    TNode<Uint32T> element_size;
    if (auto size_opt = TryComputeStaticElementSize()) {
      element_size = a.Uint32Constant(*size_opt);
    } else {
      DCHECK_EQ(instance_type_, JS_TYPED_ARRAY_TYPE);
      TNode<Map> typed_array_map = a.LoadField<Map>(
          AccessBuilder::ForMap(WriteBarrierKind::kNoWriteBarrier), view);
      TNode<Uint32T> elements_kind = a.LoadElementsKind(typed_array_map);
      element_size = a.LookupByteSizeForElementsKind(elements_kind);
    }
    // 2) Fixed length backed by RAB (can go oob once constructed)
    auto RabFixed = [&]() {
      TNode<UintPtrT> unchecked_byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteLength(), view,
          UseInfo::Word());
      TNode<UintPtrT> underlying_byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferByteLength(), buffer, UseInfo::Word());
      TNode<UintPtrT> byte_offset = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteOffset(), view,
          UseInfo::Word());
      TNode<UintPtrT> byte_length =
          a
              .MachineSelectIf<UintPtrT>(a.UintPtrLessThanOrEqual(
                  a.UintPtrAdd(byte_offset, unchecked_byte_length),
                  underlying_byte_length))
              .Then([&]() { return unchecked_byte_length; })
              .Else([&]() { return a.UintPtrConstant(0); })
              .Value();
      return a.UintPtrDiv(byte_length, a.ChangeUint32ToUintPtr(element_size));
    };
    // 3) Length-tracking backed by RAB (JSArrayBuffer stores the length)
    auto RabTracking = [&]() {
      TNode<UintPtrT> byte_length = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferByteLength(), buffer, UseInfo::Word());
      TNode<UintPtrT> byte_offset = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteOffset(), view,
          UseInfo::Word());
      return a
          .MachineSelectIf<UintPtrT>(
              a.UintPtrLessThanOrEqual(byte_offset, byte_length))
          .Then([&]() {
            // length = floor((byte_length - byte_offset) / element_size)
            return a.UintPtrDiv(a.UintPtrSub(byte_length, byte_offset),
                                a.ChangeUint32ToUintPtr(element_size));
          })
          .Else([&]() { return a.UintPtrConstant(0); })
          .ExpectTrue()
          .Value();
    };
    // 4) Length-tracking backed by GSAB (BackingStore stores the length)
    auto GsabTracking = [&]() {
      TNode<Number> temp = TNode<Number>::UncheckedCast(a.TypeGuard(
          TypeCache::Get()->kJSArrayBufferViewByteLengthType,
          a.JSCallRuntime1(Runtime::kGrowableSharedArrayBufferByteLength,
                           buffer, context, std::nullopt, Operator::kNoWrite)));
      TNode<UintPtrT> byte_length =
          a.EnterMachineGraph<UintPtrT>(temp, UseInfo::Word());
      TNode<UintPtrT> byte_offset = MachineLoadField<UintPtrT>(
          AccessBuilder::ForJSArrayBufferViewByteOffset(), view,
          UseInfo::Word());
      return a
          .MachineSelectIf<UintPtrT>(
              a.UintPtrLessThanOrEqual(byte_offset, byte_length))
          .Then([&]() {
            // length = floor((byte_length - byte_offset) / element_size)
            return a.UintPtrDiv(a.UintPtrSub(byte_length, byte_offset),
                                a.ChangeUint32ToUintPtr(element_size));
          })
          .Else([&]() { return a.UintPtrConstant(0); })
          .ExpectTrue()
          .Value();
    };
    return a.MachineSelectIf<UintPtrT>(length_tracking_bit)
        .Then([&]() {
          return a.MachineSelectIf<UintPtrT>(backed_by_rab_bit)
              .Then(RabTracking)
              .Else(GsabTracking)
              .Value();
        })
        .Else([&]() {
          return a.MachineSelectIf<UintPtrT>(backed_by_rab_bit)
              .Then(RabFixed)
              .Else(GsabFixedOrNormal)
              .Value();
        })
        .Value();
  }
References assembler_, DCHECK_EQ, v8::internal::compiler::AccessBuilder::ForJSArrayBufferByteLength(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBitField(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteLength(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteOffset(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::TypeCache::Get(), instance_type_, v8::internal::compiler::TypeCache::kJSArrayBufferViewByteLengthType, v8::internal::compiler::Operator::kNoWrite, v8::internal::compiler::kNoWriteBarrier, maybe_rab_gsab(), v8::internal::compiler::UseInfo::TruncatingWord32(), TryComputeStaticElementSize(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::compiler::UseInfo::Word().
Referenced by v8::internal::compiler::JSGraphAssembler::TypedArrayLength().
MachineLoadField()
template<typename T >
TNode<T> v8::internal::compiler::ArrayBufferViewAccessBuilder::MachineLoadField (FieldAccess const & access, TNode< HeapObject > object, const UseInfo & use_info) [inline], [private]
Definition at line 957 of file graph-assembler.cc.
                                                     {
    return assembler_->EnterMachineGraph<T>(
        assembler_->LoadField<T>(access, object), use_info);
  }
References assembler_, v8::internal::compiler::JSGraphAssembler::EnterMachineGraph(), and v8::internal::compiler::JSGraphAssembler::LoadField().
maybe_rab_gsab()
bool v8::internal::compiler::ArrayBufferViewAccessBuilder::maybe_rab_gsab () const [inline]
Definition at line 589 of file graph-assembler.cc.
                              {
    if (candidates_.empty()) return true;
    return !base::all_of(candidates_, [](auto e) {
      return !IsRabGsabTypedArrayElementsKind(e);
    });
  }
References v8::base::all_of(), candidates_, and v8::internal::IsRabGsabTypedArrayElementsKind().
Referenced by BuildByteLength(), BuildDetachedOrOutOfBoundsCheck(), and BuildLength().
TryComputeStaticElementShift()
std::optional<int> v8::internal::compiler::ArrayBufferViewAccessBuilder::TryComputeStaticElementShift () [inline]
Definition at line 596 of file graph-assembler.cc.
                                                  {
    DCHECK(instance_type_ != JS_RAB_GSAB_DATA_VIEW_TYPE);
    if (instance_type_ == JS_DATA_VIEW_TYPE) return 0;
    if (candidates_.empty()) return std::nullopt;
    int shift = ElementsKindToShiftSize(*candidates_.begin());
    if (!base::all_of(candidates_, [shift](auto e) {
          return ElementsKindToShiftSize(e) == shift;
        })) {
      return std::nullopt;
    }
    return shift;
  }
References v8::base::all_of(), candidates_, v8::internal::DCHECK(), v8::internal::ElementsKindToShiftSize(), and instance_type_.
Referenced by BuildByteLength().
TryComputeStaticElementSize()
std::optional<int> v8::internal::compiler::ArrayBufferViewAccessBuilder::TryComputeStaticElementSize () [inline]
Definition at line 609 of file graph-assembler.cc.
                                                 {
    DCHECK(instance_type_ != JS_RAB_GSAB_DATA_VIEW_TYPE);
    if (instance_type_ == JS_DATA_VIEW_TYPE) return 1;
    if (candidates_.empty()) return std::nullopt;
    int size = ElementsKindToByteSize(*candidates_.begin());
    if (!base::all_of(candidates_, [size](auto e) {
          return ElementsKindToByteSize(e) == size;
        })) {
      return std::nullopt;
    }
    return size;
  }
References v8::base::all_of(), candidates_, v8::internal::DCHECK(), v8::internal::ElementsKindToByteSize(), instance_type_, and size().
Referenced by BuildLength().
Member Data Documentation
assembler_
JSGraphAssembler* v8::internal::compiler::ArrayBufferViewAccessBuilder::assembler_ [private]
Definition at line 963 of file graph-assembler.cc.
Referenced by ArrayBufferViewAccessBuilder(), BuildByteLength(), BuildDetachedOrOutOfBoundsCheck(), BuildLength(), and MachineLoadField().
candidates_
std::set<ElementsKind> v8::internal::compiler::ArrayBufferViewAccessBuilder::candidates_ [private]
Definition at line 965 of file graph-assembler.cc.
Referenced by maybe_rab_gsab(), TryComputeStaticElementShift(), and TryComputeStaticElementSize().
instance_type_
InstanceType v8::internal::compiler::ArrayBufferViewAccessBuilder::instance_type_ [private]
Definition at line 964 of file graph-assembler.cc.
Referenced by ArrayBufferViewAccessBuilder(), BuildByteLength(), BuildLength(), TryComputeStaticElementShift(), and TryComputeStaticElementSize().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/graph-assembler.cc