v8::internal::compiler::StateValueDescriptor Class Reference
#include <instruction.h>
Public Member Functions
StateValueDescriptor ()
bool IsArgumentsElements () const
bool IsArgumentsLength () const
bool IsRestLength () const
bool IsPlain () const
bool IsOptimizedOut () const
bool IsNestedObject () const
bool IsNested () const
bool IsDuplicate () const
bool IsStringConcat () const
MachineType type () const
size_t id () const
ArgumentsStateType arguments_type () const
void Print (std::ostream &os) const
Static Public Member Functions
static StateValueDescriptor ArgumentsElements (ArgumentsStateType type)
static StateValueDescriptor ArgumentsLength ()
static StateValueDescriptor RestLength ()
static StateValueDescriptor Plain (MachineType type)
static StateValueDescriptor OptimizedOut ()
static StateValueDescriptor Recursive (size_t id)
static StateValueDescriptor Duplicate (size_t id)
static StateValueDescriptor StringConcat (size_t id)
Private Member Functions
StateValueDescriptor (StateValueKind kind, MachineType type)
Private Attributes
StateValueKind kind_
MachineType type_
xx xx xx xx xx xx xx xx xx
union {
 size_t id_
 ArgumentsStateType args_type_
};
Detailed Description
Definition at line 1328 of file instruction.h.
Constructor & Destructor Documentation
StateValueDescriptor() [1/2]
v8::internal::compiler::StateValueDescriptor::StateValueDescriptor () [inline]
Definition at line 1330 of file instruction.h.
      : kind_(StateValueKind::kPlain), type_(MachineType::AnyTagged()) {}
References v8::internal::compiler::kPlain.
StateValueDescriptor() [2/2]
v8::internal::compiler::StateValueDescriptor::StateValueDescriptor (StateValueKind kind, MachineType type) [inline], [private]
Definition at line 1404 of file instruction.h.
      : kind_(kind), type_(type) {}
Member Function Documentation
arguments_type()
ArgumentsStateType v8::internal::compiler::StateValueDescriptor::arguments_type () const [inline]
Definition at line 1396 of file instruction.h.
                                            {
    DCHECK(kind_ == StateValueKind::kArgumentsElements);
    return args_type_;
  }
References v8::internal::DCHECK(), and v8::internal::compiler::kArgumentsElements.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
ArgumentsElements()
static StateValueDescriptor v8::internal::compiler::StateValueDescriptor::ArgumentsElements (ArgumentsStateType type) [inline], [static]
Definition at line 1333 of file instruction.h.
                                                                         {
    StateValueDescriptor descr(StateValueKind::kArgumentsElements,
                               MachineType::AnyTagged());
    descr.args_type_ = type;
    return descr;
  }
References v8::internal::MachineType::AnyTagged(), args_type_, v8::internal::compiler::kArgumentsElements, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::StateValueList::PushArgumentsElements().
ArgumentsLength()
static StateValueDescriptor v8::internal::compiler::StateValueDescriptor::ArgumentsLength () [inline], [static]
Definition at line 1339 of file instruction.h.
                                                {
    return StateValueDescriptor(StateValueKind::kArgumentsLength,
                                MachineType::AnyTagged());
  }
References v8::internal::MachineType::AnyTagged(), and v8::internal::compiler::kArgumentsLength.
Referenced by v8::internal::compiler::StateValueList::PushArgumentsLength().
Duplicate()
static StateValueDescriptor v8::internal::compiler::StateValueDescriptor::Duplicate (size_t id) [inline], [static]
Definition at line 1360 of file instruction.h.
                                                   {
    StateValueDescriptor descr(StateValueKind::kDuplicate,
                               MachineType::AnyTagged());
    descr.id_ = id;
    return descr;
  }
References v8::internal::MachineType::AnyTagged(), id_, and v8::internal::compiler::kDuplicate.
Referenced by v8::internal::compiler::StateValueList::PushDuplicate().
id()
size_t v8::internal::compiler::StateValueDescriptor::id () const [inline]
Definition at line 1390 of file instruction.h.
                    {
    DCHECK(kind_ == StateValueKind::kDuplicate ||
           kind_ == StateValueKind::kNestedObject ||
           kind_ == StateValueKind::kStringConcat);
    return id_;
  }
References v8::internal::DCHECK(), v8::internal::compiler::kDuplicate, v8::internal::compiler::kNestedObject, and v8::internal::compiler::kStringConcat.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
IsArgumentsElements()
bool v8::internal::compiler::StateValueDescriptor::IsArgumentsElements () const [inline]
Definition at line 1373 of file instruction.h.
                                   {
    return kind_ == StateValueKind::kArgumentsElements;
  }
References v8::internal::compiler::kArgumentsElements.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
IsArgumentsLength()
bool v8::internal::compiler::StateValueDescriptor::IsArgumentsLength () const [inline]
Definition at line 1376 of file instruction.h.
                                 {
    return kind_ == StateValueKind::kArgumentsLength;
  }
References v8::internal::compiler::kArgumentsLength.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
IsDuplicate()
bool v8::internal::compiler::StateValueDescriptor::IsDuplicate () const [inline]
Definition at line 1387 of file instruction.h.
{ return kind_ == StateValueKind::kDuplicate; }
References v8::internal::compiler::kDuplicate.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
IsNested()
bool v8::internal::compiler::StateValueDescriptor::IsNested () const [inline]
Definition at line 1383 of file instruction.h.
                        {
    return kind_ == StateValueKind::kNestedObject ||
           kind_ == StateValueKind::kStringConcat;
  }
References v8::internal::compiler::kNestedObject, and v8::internal::compiler::kStringConcat.
Referenced by v8::internal::compiler::StateValueList::iterator::operator*().
IsNestedObject()
bool v8::internal::compiler::StateValueDescriptor::IsNestedObject () const [inline]
Definition at line 1382 of file instruction.h.
{ return kind_ == StateValueKind::kNestedObject; }
References v8::internal::compiler::kNestedObject.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
IsOptimizedOut()
bool v8::internal::compiler::StateValueDescriptor::IsOptimizedOut () const [inline]
Definition at line 1381 of file instruction.h.
{ return kind_ == StateValueKind::kOptimizedOut; }
References v8::internal::compiler::kOptimizedOut.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
IsPlain()
bool v8::internal::compiler::StateValueDescriptor::IsPlain () const [inline]
Definition at line 1380 of file instruction.h.
{ return kind_ == StateValueKind::kPlain; }
References v8::internal::compiler::kPlain.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
IsRestLength()
bool v8::internal::compiler::StateValueDescriptor::IsRestLength () const [inline]
Definition at line 1379 of file instruction.h.
{ return kind_ == StateValueKind::kRestLength; }
References v8::internal::compiler::kRestLength.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
IsStringConcat()
bool v8::internal::compiler::StateValueDescriptor::IsStringConcat () const [inline]
Definition at line 1388 of file instruction.h.
{ return kind_ == StateValueKind::kStringConcat; }
References v8::internal::compiler::kStringConcat.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
OptimizedOut()
static StateValueDescriptor v8::internal::compiler::StateValueDescriptor::OptimizedOut () [inline], [static]
Definition at line 1350 of file instruction.h.
                                             {
    return StateValueDescriptor(StateValueKind::kOptimizedOut,
                                MachineType::AnyTagged());
  }
References v8::internal::MachineType::AnyTagged(), and v8::internal::compiler::kOptimizedOut.
Referenced by v8::internal::compiler::StateValueList::PushOptimizedOut().
Plain()
static StateValueDescriptor v8::internal::compiler::StateValueDescriptor::Plain (MachineType type) [inline], [static]
Definition at line 1347 of file instruction.h.
                                                      {
    return StateValueDescriptor(StateValueKind::kPlain, type);
  }
References v8::internal::compiler::kPlain, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::StateValueList::PushPlain().
Print()
void v8::internal::compiler::StateValueDescriptor::Print (std::ostream & os) const
Definition at line 1363 of file instruction.cc.
                                                     {
  os << "kind=" << kind_ << ", type=" << type_;
  if (kind_ == StateValueKind::kDuplicate ||
      kind_ == StateValueKind::kNestedObject) {
    os << ", id=" << id_;
  } else if (kind_ == StateValueKind::kArgumentsElements) {
    os << ", args_type=" << args_type_;
  }
}
References args_type_, id_, v8::internal::compiler::kArgumentsElements, v8::internal::compiler::kDuplicate, kind_, v8::internal::compiler::kNestedObject, and type_.
Recursive()
static StateValueDescriptor v8::internal::compiler::StateValueDescriptor::Recursive (size_t id) [inline], [static]
Definition at line 1354 of file instruction.h.
                                                   {
    StateValueDescriptor descr(StateValueKind::kNestedObject,
                               MachineType::AnyTagged());
    descr.id_ = id;
    return descr;
  }
References v8::internal::MachineType::AnyTagged(), id_, and v8::internal::compiler::kNestedObject.
Referenced by v8::internal::compiler::StateValueList::PushRecursiveField().
RestLength()
static StateValueDescriptor v8::internal::compiler::StateValueDescriptor::RestLength () [inline], [static]
Definition at line 1343 of file instruction.h.
                                           {
    return StateValueDescriptor(StateValueKind::kRestLength,
                                MachineType::AnyTagged());
  }
References v8::internal::MachineType::AnyTagged(), and v8::internal::compiler::kRestLength.
Referenced by v8::internal::compiler::StateValueList::PushRestLength().
StringConcat()
static StateValueDescriptor v8::internal::compiler::StateValueDescriptor::StringConcat (size_t id) [inline], [static]
Definition at line 1366 of file instruction.h.
                                                      {
    StateValueDescriptor descr(StateValueKind::kStringConcat,
                               MachineType::AnyTagged());
    descr.id_ = id;
    return descr;
  }
References v8::internal::MachineType::AnyTagged(), id_, and v8::internal::compiler::kStringConcat.
Referenced by v8::internal::compiler::StateValueList::PushStringConcat().
type()
MachineType v8::internal::compiler::StateValueDescriptor::type () const [inline]
Definition at line 1389 of file instruction.h.
{ return type_; }
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
Member Data Documentation
union { ... } [private]
args_type_
ArgumentsStateType v8::internal::compiler::StateValueDescriptor::args_type_
Definition at line 1411 of file instruction.h.
Referenced by ArgumentsElements(), and Print().
id_
size_t v8::internal::compiler::StateValueDescriptor::id_
Definition at line 1410 of file instruction.h.
Referenced by Duplicate(), Print(), Recursive(), and StringConcat().
kind_
StateValueKind v8::internal::compiler::StateValueDescriptor::kind_ [private]
Definition at line 1407 of file instruction.h.
Referenced by Print().
type_
MachineType v8::internal::compiler::StateValueDescriptor::type_ [private]
Definition at line 1408 of file instruction.h.
Referenced by Print().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc