v8::internal::compiler::JSCreateClosureNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSCreateClosureNode (Node *node)
const CreateClosureParameters & Parameters () const
FeedbackCellRef GetFeedbackCellRefChecked (JSHeapBroker *broker) const
Additional Inherited Members
Detailed Description
Definition at line 1720 of file js-operator.h.
Constructor & Destructor Documentation
JSCreateClosureNode()
constexpr v8::internal::compiler::JSCreateClosureNode::JSCreateClosureNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1722 of file js-operator.h.
                                                     : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSCreateClosure, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
GetFeedbackCellRefChecked()
FeedbackCellRef v8::internal::compiler::JSCreateClosureNode::GetFeedbackCellRefChecked (JSHeapBroker * broker) const
Definition at line 52 of file js-operator.cc.
                                {
  HeapObjectMatcher m(feedback_cell());
  CHECK(m.HasResolvedValue());
  return MakeRef(broker, Cast<FeedbackCell>(m.ResolvedValue()));
}
References broker(), CHECK, v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::MakeRef(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::JSInliner::DetermineCallTarget(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
Parameters()
const CreateClosureParameters& v8::internal::compiler::JSCreateClosureNode::Parameters () const [inline]
Definition at line 1726 of file js-operator.h.
                                                    {
    return CreateClosureParametersOf(node()->op());
  }
References v8::internal::compiler::CreateClosureParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-operator.h
/mnt/V8SourceCode/src/compiler/js-operator.cc