v8::internal::IsCompiledScope Class Reference
#include <shared-function-info.h>
Public Member Functions
IsCompiledScope (const Tagged< SharedFunctionInfo > shared, Isolate *isolate)
IsCompiledScope (const Tagged< SharedFunctionInfo > shared, LocalIsolate *isolate)
IsCompiledScope ()=default
bool is_compiled () const
Private Attributes
MaybeHandle< HeapObject > retain_code_ = {}
bool is_compiled_ = false
Detailed Description
Definition at line 881 of file shared-function-info.h.
Constructor & Destructor Documentation
IsCompiledScope() [1/3]
v8::internal::IsCompiledScope::IsCompiledScope (const Tagged< SharedFunctionInfo > shared, Isolate * isolate) [inline]
IsCompiledScope() [2/3]
v8::internal::IsCompiledScope::IsCompiledScope (const Tagged< SharedFunctionInfo > shared, LocalIsolate * isolate) [inline]
Definition at line 691 of file shared-function-info-inl.h.
                                                        {
  Tagged<Object> data_obj = shared->GetTrustedData(isolate);
  if (Tagged<HeapObject> data; TryCast<HeapObject>(data_obj, &data)) {
    if (Tagged<Code> code; TryCast<Code>(data, &code)) {
      DCHECK(code->kind() == CodeKind::BASELINE);
      data = code->bytecode_or_interpreter_data();
    }
    // Unlike GetBytecodeArray, we don't bother checking for DebugInfo here. If
    // there is DebugInfo, then it will hold both the debug and original
    // BytecodeArray strongly, so it doesn't matter which of those we hold.
    if (Tagged<BytecodeArray> bytecode;
        TryCast<BytecodeArray>(data, &bytecode)) {
      retain_code_ = isolate->heap()->NewPersistentHandle(bytecode);
      is_compiled_ = true;
    } else if (Tagged<InterpreterData> interpreter_data;
               TryCast<InterpreterData>(data, &interpreter_data)) {
      retain_code_ = isolate->heap()->NewPersistentHandle(
          interpreter_data->bytecode_array());
      is_compiled_ = true;
    } else if (Is<UncompiledData>(data)) {
      retain_code_ = {};
      is_compiled_ = false;
    } else {
      retain_code_ = {};
      is_compiled_ = shared->is_compiled();
    }
  } else {
    retain_code_ = {};
    is_compiled_ = shared->is_compiled();
  }
  DCHECK_IMPLIES(!retain_code_.is_null(), is_compiled());
  DCHECK_EQ(shared->is_compiled(), is_compiled());
}
References code, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::LocalIsolate::heap(), is_compiled(), is_compiled_, v8::internal::LocalHeap::NewPersistentHandle(), and retain_code_.
IsCompiledScope() [3/3]
v8::internal::IsCompiledScope::IsCompiledScope () [inline], [default]
Member Function Documentation
is_compiled()
bool v8::internal::IsCompiledScope::is_compiled () const [inline]
Definition at line 889 of file shared-function-info.h.
{ return is_compiled_; }
Referenced by v8::internal::JSFunction::CalculateExpectedNofProperties(), v8::internal::anonymous_namespace{runtime-test.cc}::CanOptimizeFunction(), v8::internal::Compiler::Compile(), v8::internal::anonymous_namespace{compiler.cc}::CompileAllWithBaseline(), v8::internal::Compiler::CompileSharedWithBaseline(), v8::internal::JSFunction::CreateAndAttachFeedbackVector(), v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), v8::internal::Debug::EnsureBreakInfo(), v8::internal::anonymous_namespace{runtime-test.cc}::EnsureCompiledAndFeedbackVector(), v8::internal::JSFunction::EnsureFeedbackVector(), v8::Function::Experimental_IsNopFunction(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), v8::internal::Debug::FindInnermostContainingFunctionInfo(), v8::internal::Debug::FindSharedFunctionInfosIntersectingRange(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetWrappedFunction(), v8::internal::InfoCellPair::has_js_function(), v8::internal::InfoCellPair::has_shared(), v8::internal::Debug::InstallDebugBreakTrampoline(), IsCompiledScope(), v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(), v8::internal::InfoCellPair::js_function(), v8::internal::ManualOptimizationTable::MarkFunctionForManualOptimization(), v8::internal::FeedbackVector::New(), v8::internal::TieringManager::OnInterruptTick(), v8::internal::Debug::PerformSideEffectCheck(), v8::internal::Compiler::PostInstantiation(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Coverage::SelectMode(), v8::internal::BackgroundMergeTask::SetUpOnMainThread(), and v8::internal::InfoCellPair::shared().
Member Data Documentation
is_compiled_
bool v8::internal::IsCompiledScope::is_compiled_ = false [private]
Definition at line 893 of file shared-function-info.h.
Referenced by IsCompiledScope().
retain_code_
MaybeHandle<HeapObject> v8::internal::IsCompiledScope::retain_code_ = {} [private]
Definition at line 892 of file shared-function-info.h.
Referenced by IsCompiledScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/shared-function-info.h
/mnt/V8SourceCode/src/objects/shared-function-info-inl.h