v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterJSCallAssembler Class Reference
Public Member Functions
InterpreterJSCallAssembler (CodeAssemblerState *state, Bytecode bytecode, OperandScale operand_scale)
void JSCall (ConvertReceiverMode receiver_mode)
void JSCallN (int arg_count, ConvertReceiverMode receiver_mode)
Additional Inherited Members
Detailed Description
Definition at line 1523 of file interpreter-generator.cc.
Constructor & Destructor Documentation
InterpreterJSCallAssembler()
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterJSCallAssembler::InterpreterJSCallAssembler (CodeAssemblerState * state, Bytecode bytecode, OperandScale operand_scale) [inline]
Definition at line 1525 of file interpreter-generator.cc.
      : InterpreterAssembler(state, bytecode, operand_scale) {}
Member Function Documentation
JSCall()
void v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterJSCallAssembler::JSCall (ConvertReceiverMode receiver_mode) [inline]
Definition at line 1530 of file interpreter-generator.cc.
                                                 {
    TNode<JSAny> function = CAST(LoadRegisterAtOperandIndex(0));
    RegListNodePair args = GetRegisterListAtOperandIndex(1);
    TNode<Context> context = GetContext();
#ifndef V8_JITLESS
    // Collect the {function} feedback.
    LazyNode<JSAny> receiver = [=, this] {
      return receiver_mode == ConvertReceiverMode::kNullOrUndefined
                 ? UndefinedConstant()
                 : TNode<JSAny>(CAST(LoadRegisterAtOperandIndex(1)));
    };
    TNode<UintPtrT> slot_id = BytecodeOperandIdx(3);
    TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
        LoadFeedbackVector();
    CollectCallFeedback(function, receiver, context, maybe_feedback_vector,
                        slot_id);
#endif // !V8_JITLESS
    // Call the function and dispatch to the next handler.
    CallJSAndDispatch(function, context, args, receiver_mode);
  }
References v8::base::args, CAST, v8::internal::kNullOrUndefined, and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
JSCallN()
void v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterJSCallAssembler::JSCallN (int arg_count, ConvertReceiverMode receiver_mode) [inline]
Definition at line 1555 of file interpreter-generator.cc.
                                                                 {
    // Indices and counts of operands on the bytecode.
    const int kFirstArgumentOperandIndex = 1;
    const int kReceiverOperandCount =
        (receiver_mode == ConvertReceiverMode::kNullOrUndefined) ? 0 : 1;
    const int kReceiverAndArgOperandCount = kReceiverOperandCount + arg_count;
    TNode<JSAny> function = CAST(LoadRegisterAtOperandIndex(0));
    TNode<Context> context = GetContext();
#ifndef V8_JITLESS
    // Collect the {function} feedback.
    LazyNode<JSAny> receiver = [=, this] {
      return receiver_mode == ConvertReceiverMode::kNullOrUndefined
                 ? UndefinedConstant()
                 : TNode<JSAny>(CAST(LoadRegisterAtOperandIndex(1)));
    };
    const int kSlotOperandIndex =
        kFirstArgumentOperandIndex + kReceiverAndArgOperandCount;
    TNode<UintPtrT> slot_id = BytecodeOperandIdx(kSlotOperandIndex);
    TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
        LoadFeedbackVector();
    CollectCallFeedback(function, receiver, context, maybe_feedback_vector,
                        slot_id);
#endif // !V8_JITLESS
    switch (kReceiverAndArgOperandCount) {
      case 0:
        CallJSAndDispatch(function, context, Int32Constant(arg_count),
                          receiver_mode);
        break;
      case 1:
        CallJSAndDispatch(
            function, context, Int32Constant(arg_count), receiver_mode,
            LoadRegisterAtOperandIndex(kFirstArgumentOperandIndex));
        break;
      case 2:
        CallJSAndDispatch(
            function, context, Int32Constant(arg_count), receiver_mode,
            LoadRegisterAtOperandIndex(kFirstArgumentOperandIndex + 1),
            LoadRegisterAtOperandIndex(kFirstArgumentOperandIndex));
        break;
      case 3:
        CallJSAndDispatch(
            function, context, Int32Constant(arg_count), receiver_mode,
            LoadRegisterAtOperandIndex(kFirstArgumentOperandIndex + 2),
            LoadRegisterAtOperandIndex(kFirstArgumentOperandIndex + 1),
            LoadRegisterAtOperandIndex(kFirstArgumentOperandIndex));
        break;
      default:
        UNREACHABLE();
    }
  }
References CAST, v8::internal::kNullOrUndefined, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::UNREACHABLE().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/interpreter-generator.cc