v8::internal::RelocInfoWriter Class Reference
#include <reloc-info.h>
Public Member Functions
RelocInfoWriter ()
RelocInfoWriter (const RelocInfoWriter &)=delete
RelocInfoWriter & operator= (const RelocInfoWriter &)=delete
uint8_t * pos () const
uint8_t * last_pc () const
void Write (const RelocInfo *rinfo)
void Reposition (uint8_t *pos, uint8_t *pc)
Static Public Attributes
static constexpr int kMaxSize = 1 + 4 + 1 + 1 + kSystemPointerSize
Private Member Functions
uint32_t WriteLongPCJump (uint32_t pc_delta)
void WriteShortTaggedPC (uint32_t pc_delta, int tag)
void WriteShortData (uint8_t data_delta)
void WriteMode (RelocInfo::Mode rmode)
void WriteModeAndPC (uint32_t pc_delta, RelocInfo::Mode rmode)
void WriteIntData (int data_delta)
Private Attributes
uint8_t * pos_
uint8_t * last_pc_
Detailed Description
Definition at line 468 of file reloc-info.h.
Constructor & Destructor Documentation
RelocInfoWriter() [1/2]
v8::internal::RelocInfoWriter::RelocInfoWriter () [inline]
Definition at line 470 of file reloc-info.h.
: pos_(nullptr), last_pc_(nullptr) {}
RelocInfoWriter() [2/2]
v8::internal::RelocInfoWriter::RelocInfoWriter (const RelocInfoWriter &) [delete]
Member Function Documentation
last_pc()
uint8_t* v8::internal::RelocInfoWriter::last_pc () const [inline]
Definition at line 476 of file reloc-info.h.
{ return last_pc_; }
References last_pc_.
Referenced by v8::internal::Assembler::GrowBuffer().
operator=()
RelocInfoWriter& v8::internal::RelocInfoWriter::operator= (const RelocInfoWriter &) [delete]
pos()
uint8_t* v8::internal::RelocInfoWriter::pos () const [inline]
Definition at line 475 of file reloc-info.h.
{ return pos_; }
References pos_.
Referenced by v8::internal::Assembler::buffer_space(), v8::internal::Assembler::GetCode(), v8::internal::Assembler::GrowBuffer(), and Reposition().
Reposition()
void v8::internal::RelocInfoWriter::Reposition (uint8_t * pos, uint8_t * pc) [inline]
Definition at line 482 of file reloc-info.h.
                                             {
    pos_ = pos;
    last_pc_ = pc;
  }
References last_pc_, pos(), and pos_.
Referenced by v8::internal::Assembler::Assembler(), and v8::internal::Assembler::GrowBuffer().
Write()
void v8::internal::RelocInfoWriter::Write (const RelocInfo * rinfo)
Definition at line 67 of file reloc-info.cc.
                                                  {
  RelocInfo::Mode rmode = rinfo->rmode();
#ifdef DEBUG
  uint8_t* begin_pos = pos_;
#endif
  DCHECK(rinfo->rmode() < RelocInfo::NUMBER_OF_MODES);
  DCHECK_GE(rinfo->pc() - reinterpret_cast<Address>(last_pc_), 0);
  // Use unsigned delta-encoding for pc.
  uint32_t pc_delta =
      static_cast<uint32_t>(rinfo->pc() - reinterpret_cast<Address>(last_pc_));
  // The two most common modes are given small tags, and usually fit in a byte.
  if (rmode == RelocInfo::FULL_EMBEDDED_OBJECT) {
    WriteShortTaggedPC(pc_delta, kEmbeddedObjectTag);
  } else if (rmode == RelocInfo::CODE_TARGET) {
    WriteShortTaggedPC(pc_delta, kCodeTargetTag);
    DCHECK_LE(begin_pos - pos_, RelocInfo::kMaxCallSize);
  } else if (rmode == RelocInfo::WASM_STUB_CALL) {
    WriteShortTaggedPC(pc_delta, kWasmStubCallTag);
  } else {
    WriteModeAndPC(pc_delta, rmode);
    if (RelocInfo::IsDeoptReason(rmode)) {
      DCHECK_LT(rinfo->data(), 1 << kBitsPerByte);
      WriteShortData(static_cast<uint8_t>(rinfo->data()));
    } else if (RelocInfo::IsConstPool(rmode) ||
               RelocInfo::IsVeneerPool(rmode) || RelocInfo::IsDeoptId(rmode) ||
               RelocInfo::IsDeoptPosition(rmode) ||
               RelocInfo::IsDeoptNodeId(rmode)) {
      WriteIntData(static_cast<int>(rinfo->data()));
    }
  }
  last_pc_ = reinterpret_cast<uint8_t*>(rinfo->pc());
#ifdef DEBUG
  DCHECK_LE(begin_pos - pos_, kMaxSize);
#endif
}
References v8::internal::RelocInfo::CODE_TARGET, v8::internal::RelocInfo::data(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, DCHECK_LT, v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, v8::internal::RelocInfo::IsConstPool(), v8::internal::RelocInfo::IsDeoptId(), v8::internal::RelocInfo::IsDeoptNodeId(), v8::internal::RelocInfo::IsDeoptPosition(), v8::internal::RelocInfo::IsDeoptReason(), v8::internal::RelocInfo::IsVeneerPool(), v8::internal::kBitsPerByte, v8::internal::detail::kCodeTargetTag, v8::internal::detail::kEmbeddedObjectTag, v8::internal::RelocInfo::kMaxCallSize, v8::internal::detail::kWasmStubCallTag, v8::internal::RelocInfo::NUMBER_OF_MODES, v8::internal::RelocInfo::pc(), v8::internal::RelocInfo::rmode(), and v8::internal::RelocInfo::WASM_STUB_CALL.
Referenced by v8::internal::Assembler::RecordRelocInfo().
WriteIntData()
void v8::internal::RelocInfoWriter::WriteIntData (int data_delta) [inline], [private]
Definition at line 59 of file reloc-info.cc.
                                             {
  for (int i = 0; i < kIntSize; i++) {
    *--pos_ = static_cast<uint8_t>(number);
    // Signed right shift is arithmetic shift. Tested in test-utils.cc.
    number = number >> kBitsPerByte;
  }
}
References v8::internal::kBitsPerByte, and v8::internal::kIntSize.
WriteLongPCJump()
uint32_t v8::internal::RelocInfoWriter::WriteLongPCJump (uint32_t pc_delta) [inline], [private]
Definition at line 24 of file reloc-info.cc.
                                                           {
  // Return if the pc_delta can fit in kSmallPCDeltaBits bits.
  // Otherwise write a variable length PC jump for the bits that do
  // not fit in the kSmallPCDeltaBits bits.
  if (is_uintn(pc_delta, kSmallPCDeltaBits)) return pc_delta;
  WriteMode(RelocInfo::PC_JUMP);
  uint32_t pc_jump = pc_delta >> kSmallPCDeltaBits;
  DCHECK_GT(pc_jump, 0);
  base::VLQEncodeUnsigned([this](uint8_t byte) { *--pos_ = byte; }, pc_jump);
  // Return the remaining kSmallPCDeltaBits of the pc_delta.
  return pc_delta & kSmallPCDeltaMask;
}
References DCHECK_GT, v8::internal::is_uintn(), v8::internal::detail::kSmallPCDeltaBits, v8::internal::detail::kSmallPCDeltaMask, v8::internal::RelocInfo::PC_JUMP, and v8::base::VLQEncodeUnsigned().
WriteMode()
void v8::internal::RelocInfoWriter::WriteMode (RelocInfo::Mode rmode) [inline], [private]
Definition at line 47 of file reloc-info.cc.
                                                   {
  static_assert(RelocInfo::NUMBER_OF_MODES <= (1 << kLongTagBits));
  *--pos_ = static_cast<int>((rmode << kTagBits) | kDefaultTag);
}
References v8::internal::detail::kDefaultTag, v8::internal::detail::kLongTagBits, v8::internal::detail::kTagBits, and v8::internal::RelocInfo::NUMBER_OF_MODES.
WriteModeAndPC()
void v8::internal::RelocInfoWriter::WriteModeAndPC (uint32_t pc_delta, RelocInfo::Mode rmode) [inline], [private]
Definition at line 52 of file reloc-info.cc.
                                                                           {
  // Write two-byte tagged pc-delta, possibly preceded by var. length pc-jump.
  pc_delta = WriteLongPCJump(pc_delta);
  WriteMode(rmode);
  *--pos_ = pc_delta;
}
WriteShortData()
void v8::internal::RelocInfoWriter::WriteShortData (uint8_t data_delta) [inline], [private]
Definition at line 43 of file reloc-info.cc.
                                                       {
  *--pos_ = data_delta;
}
WriteShortTaggedPC()
void v8::internal::RelocInfoWriter::WriteShortTaggedPC (uint32_t pc_delta, int tag) [inline], [private]
Definition at line 37 of file reloc-info.cc.
                                                                   {
  // Write a byte of tagged pc-delta, possibly preceded by an explicit pc-jump.
  pc_delta = WriteLongPCJump(pc_delta);
  *--pos_ = pc_delta << kTagBits | tag;
}
References v8::internal::detail::kTagBits.
Member Data Documentation
kMaxSize
constexpr int v8::internal::RelocInfoWriter::kMaxSize = 1 + 4 + 1 + 1 + kSystemPointerSize [static], [constexpr]
Definition at line 489 of file reloc-info.h.
Referenced by v8::internal::Assembler::RecordDeoptReason().
last_pc_
uint8_t* v8::internal::RelocInfoWriter::last_pc_ [private]
Definition at line 502 of file reloc-info.h.
Referenced by last_pc(), and Reposition().
pos_
uint8_t* v8::internal::RelocInfoWriter::pos_ [private]
Definition at line 501 of file reloc-info.h.
Referenced by pos(), and Reposition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/reloc-info.h
/mnt/V8SourceCode/src/codegen/reloc-info.cc