v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency Class Reference
Public Member Functions
ContextCellDependency (ContextCellRef slot, ContextCell::State state)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const ContextCellRef slot_
const ContextCell::State state_
Additional Inherited Members
Detailed Description
Definition at line 912 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
ContextCellDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::ContextCellDependency (ContextCellRef slot, ContextCell::State state) [inline]
Definition at line 914 of file compilation-dependencies.cc.
      : CompilationDependency(kContextCell), slot_(slot), state_(state) {
    DCHECK(v8_flags.script_context_cells || v8_flags.function_context_cells);
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 934 of file compilation-dependencies.cc.
                                                                {
    const ContextCellDependency* const zat = that->AsContextCell();
    return slot_.equals(zat->slot_) && state_ == zat->state_;
  }
References slot_, and state_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 929 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(slot_), state_);
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 923 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(slot_.object(), DependentCode::kContextCellChangedGroup);
  }
References broker(), v8::internal::DependentCode::kContextCellChangedGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 919 of file compilation-dependencies.cc.
                                                    {
    return slot_.state() == state_;
  }
Member Data Documentation
slot_
const ContextCellRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::slot_ [private]
Definition at line 939 of file compilation-dependencies.cc.
Referenced by Equals().
state_
const ContextCell::State v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::state_ [private]
Definition at line 940 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc