v8::internal::ZonePreparseData Class Reference
#include <preparse-data-impl.h>
Public Member Functions
V8_EXPORT_PRIVATE ZonePreparseData (Zone *zone, base::Vector< uint8_t > *byte_data, int child_length)
ZonePreparseData (const ZonePreparseData &)=delete
ZonePreparseData & operator= (const ZonePreparseData &)=delete
Handle< PreparseData > Serialize (Isolate *isolate)
Handle< PreparseData > Serialize (LocalIsolate *isolate)
int children_length () const
ZonePreparseData * get_child (int index)
void set_child (int index, ZonePreparseData *child)
ZoneVector< uint8_t > * byte_data ()
Private Attributes
ZoneVector< uint8_t > byte_data_
ZoneVector< ZonePreparseData * > children_
Detailed Description
Definition at line 206 of file preparse-data-impl.h.
Constructor & Destructor Documentation
ZonePreparseData() [1/2]
v8::internal::ZonePreparseData::ZonePreparseData (Zone * zone, base::Vector< uint8_t > * byte_data, int child_length)
Definition at line 787 of file preparse-data.cc.
    : byte_data_(byte_data->begin(), byte_data->end(), zone),
      children_(children_length, zone) {}
ZonePreparseData() [2/2]
v8::internal::ZonePreparseData::ZonePreparseData (const ZonePreparseData &) [delete]
Member Function Documentation
byte_data()
ZoneVector<uint8_t>* v8::internal::ZonePreparseData::byte_data () [inline]
Definition at line 227 of file preparse-data-impl.h.
{ return &byte_data_; }
References byte_data_.
Referenced by Serialize().
children_length()
int v8::internal::ZonePreparseData::children_length () const [inline]
Definition at line 218 of file preparse-data-impl.h.
{ return static_cast<int>(children_.size()); }
References children_.
Referenced by v8::internal::ZoneConsumedPreparseData::GetChildData(), Serialize(), and v8::internal::PreparseDataBuilder::Serialize().
get_child()
ZonePreparseData* v8::internal::ZonePreparseData::get_child (int index) [inline]
Definition at line 220 of file preparse-data-impl.h.
{ return children_[index]; }
References children_, and v8::internal::index.
Referenced by v8::internal::ZoneConsumedPreparseData::GetChildData(), and Serialize().
operator=()
ZonePreparseData& v8::internal::ZonePreparseData::operator= (const ZonePreparseData &) [delete]
Serialize() [1/2]
Handle< PreparseData > v8::internal::ZonePreparseData::Serialize (Isolate * isolate)
Definition at line 792 of file preparse-data.cc.
                                                                 {
  int data_size = static_cast<int>(byte_data()->size());
  int child_data_length = children_length();
  Handle<PreparseData> result =
      isolate->factory()->NewPreparseData(data_size, child_data_length);
  result->copy_in(0, byte_data()->data(), data_size);
  for (int i = 0; i < child_data_length; i++) {
    ZonePreparseData* child = get_child(i);
    DCHECK_NOT_NULL(child);
    DirectHandle<PreparseData> child_data = child->Serialize(isolate);
    result->set_child(i, *child_data);
  }
  return result;
}
References byte_data(), children_length(), DCHECK_NOT_NULL, v8::internal::Isolate::factory(), get_child(), v8::internal::FactoryBase< Impl >::NewPreparseData(), v8::base::internal::result, Serialize(), and v8::internal::ZoneVector< T >::size().
Referenced by Serialize(), v8::internal::PreparseDataBuilder::Serialize(), and v8::internal::BuilderProducedPreparseData::Serialize().
Serialize() [2/2]
Handle< PreparseData > v8::internal::ZonePreparseData::Serialize (LocalIsolate * isolate)
Definition at line 808 of file preparse-data.cc.
                                                                      {
  int data_size = static_cast<int>(byte_data()->size());
  int child_data_length = children_length();
  Handle<PreparseData> result =
      isolate->factory()->NewPreparseData(data_size, child_data_length);
  result->copy_in(0, byte_data()->data(), data_size);
  for (int i = 0; i < child_data_length; i++) {
    ZonePreparseData* child = get_child(i);
    DCHECK_NOT_NULL(child);
    DirectHandle<PreparseData> child_data = child->Serialize(isolate);
    result->set_child(i, *child_data);
  }
  return result;
}
References byte_data(), children_length(), DCHECK_NOT_NULL, v8::internal::LocalIsolate::factory(), get_child(), v8::internal::FactoryBase< Impl >::NewPreparseData(), v8::base::internal::result, Serialize(), and v8::internal::ZoneVector< T >::size().
set_child()
void v8::internal::ZonePreparseData::set_child (int index, ZonePreparseData * child) [inline]
Definition at line 222 of file preparse-data-impl.h.
                                                     {
    DCHECK_NOT_NULL(child);
    children_[index] = child;
  }
References children_, DCHECK_NOT_NULL, and v8::internal::index.
Referenced by v8::internal::PreparseDataBuilder::Serialize().
Member Data Documentation
byte_data_
ZoneVector<uint8_t> v8::internal::ZonePreparseData::byte_data_ [private]
Definition at line 230 of file preparse-data-impl.h.
Referenced by byte_data().
children_
ZoneVector<ZonePreparseData*> v8::internal::ZonePreparseData::children_ [private]
Definition at line 231 of file preparse-data-impl.h.
Referenced by children_length(), get_child(), and set_child().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparse-data-impl.h
/mnt/V8SourceCode/src/parsing/preparse-data.cc