v8::internal::SerializedCodeData Class Reference
#include <code-serializer.h>
Public Member Functions
SerializedCodeData (const std::vector< uint8_t > *payload, const CodeSerializer *cs)
AlignedCachedData * GetScriptData ()
base::Vector< const uint8_t > Payload () const
Static Public Member Functions
static SerializedCodeData FromCachedData (Isolate *isolate, AlignedCachedData *cached_data, uint32_t expected_source_hash, SerializedCodeSanityCheckResult *rejection_result)
static SerializedCodeData FromCachedDataWithoutSource (LocalIsolate *local_isolate, AlignedCachedData *cached_data, SerializedCodeSanityCheckResult *rejection_result)
static SerializedCodeData FromPartiallySanityCheckedCachedData (AlignedCachedData *cached_data, uint32_t expected_source_hash, SerializedCodeSanityCheckResult *rejection_result)
static uint32_t SourceHash (DirectHandle< String > source, DirectHandle< FixedArray > wrapped_arguments, ScriptOriginOptions origin_options)
Static Public Attributes
static const uint32_t kVersionHashOffset = kMagicNumberOffset + kUInt32Size
static const uint32_t kSourceHashOffset = kVersionHashOffset + kUInt32Size
static const uint32_t kFlagHashOffset = kSourceHashOffset + kUInt32Size
static const uint32_t kReadOnlySnapshotChecksumOffset
static const uint32_t kPayloadLengthOffset
static const uint32_t kChecksumOffset = kPayloadLengthOffset + kUInt32Size
static const uint32_t kUnalignedHeaderSize = kChecksumOffset + kUInt32Size
static const uint32_t kHeaderSize = POINTER_SIZE_ALIGN(kUnalignedHeaderSize)
Private Member Functions
SerializedCodeData (AlignedCachedData *data)
SerializedCodeData (const uint8_t *data, int size)
base::Vector< const uint8_t > ChecksummedContent () const
SerializedCodeSanityCheckResult SanityCheck (uint32_t expected_ro_snapshot_checksum, uint32_t expected_source_hash) const
SerializedCodeSanityCheckResult SanityCheckJustSource (uint32_t expected_source_hash) const
SerializedCodeSanityCheckResult SanityCheckWithoutSource (uint32_t expected_ro_snapshot_checksum) const
Additional Inherited Members
Detailed Description
Definition at line 115 of file code-serializer.h.
Constructor & Destructor Documentation
SerializedCodeData() [1/3]
v8::internal::SerializedCodeData::SerializedCodeData (const std::vector< uint8_t > * payload, const CodeSerializer * cs)
Definition at line 728 of file code-serializer.cc.
                                                                 {
  DisallowGarbageCollection no_gc;
  // Calculate sizes.
  uint32_t size = kHeaderSize + static_cast<uint32_t>(payload->size());
  DCHECK(IsAligned(size, kPointerAlignment));
  // Allocate backing store and create result data.
  AllocateData(size);
  // Zero out pre-payload data. Part of that is only used for padding.
  memset(data_, 0, kHeaderSize);
  // Set header values.
  SetMagicNumber();
  SetHeaderValue(kVersionHashOffset, Version::Hash());
  SetHeaderValue(kSourceHashOffset, cs->source_hash());
  SetHeaderValue(kFlagHashOffset, FlagList::Hash());
  SetHeaderValue(kReadOnlySnapshotChecksumOffset,
                 Snapshot::ExtractReadOnlySnapshotChecksum(
                     cs->isolate()->snapshot_blob()));
  SetHeaderValue(kPayloadLengthOffset, static_cast<uint32_t>(payload->size()));
  // Zero out any padding in the header.
  memset(data_ + kUnalignedHeaderSize, 0, kHeaderSize - kUnalignedHeaderSize);
  // Copy serialized data.
  CopyBytes(data_ + kHeaderSize, payload->data(),
            static_cast<size_t>(payload->size()));
  uint32_t checksum =
      v8_flags.verify_snapshot_checksum ? Checksum(ChecksummedContent()) : 0;
  SetHeaderValue(kChecksumOffset, checksum);
}
References v8::internal::Checksum(), v8::internal::CopyBytes(), v8::internal::cs, v8::internal::DCHECK(), v8::internal::Snapshot::ExtractReadOnlySnapshotChecksum(), v8::internal::FlagList::Hash(), v8::internal::Version::Hash(), IsAligned(), v8::internal::kPointerAlignment, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::v8_flags.
Referenced by FromCachedData(), FromCachedDataWithoutSource(), and FromPartiallySanityCheckedCachedData().
SerializedCodeData() [2/3]
v8::internal::SerializedCodeData::SerializedCodeData (AlignedCachedData * data) [explicit], [private]
Definition at line 851 of file code-serializer.cc.
    : SerializedData(const_cast<uint8_t*>(data->data()), data->length()) {}
SerializedCodeData() [3/3]
v8::internal::SerializedCodeData::SerializedCodeData (const uint8_t * data, int size) [inline], [private]
Definition at line 161 of file code-serializer.h.
      : SerializedData(const_cast<uint8_t*>(data), size) {}
Member Function Documentation
ChecksummedContent()
base::Vector<const uint8_t> v8::internal::SerializedCodeData::ChecksummedContent () const [inline], [private]
Definition at line 164 of file code-serializer.h.
                                                       {
    return base::Vector<const uint8_t>(data_ + kHeaderSize,
                                       size_ - kHeaderSize);
  }
FromCachedData()
SerializedCodeData v8::internal::SerializedCodeData::FromCachedData (Isolate * isolate, AlignedCachedData * cached_data, uint32_t expected_source_hash, SerializedCodeSanityCheckResult * rejection_result) [static]
Definition at line 854 of file code-serializer.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  SerializedCodeData scd(cached_data);
  *rejection_result = scd.SanityCheck(
      Snapshot::ExtractReadOnlySnapshotChecksum(isolate->snapshot_blob()),
      expected_source_hash);
  if (*rejection_result != SerializedCodeSanityCheckResult::kSuccess) {
    cached_data->Reject();
    return SerializedCodeData(nullptr, 0);
  }
  return scd;
}
References v8::internal::Snapshot::ExtractReadOnlySnapshotChecksum(), v8::internal::detail::kSuccess, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::AlignedCachedData::Reject(), SanityCheck(), and SerializedCodeData().
Referenced by v8::internal::CodeSerializer::Deserialize().
FromCachedDataWithoutSource()
SerializedCodeData v8::internal::SerializedCodeData::FromCachedDataWithoutSource (LocalIsolate * local_isolate, AlignedCachedData * cached_data, SerializedCodeSanityCheckResult * rejection_result) [static]
Definition at line 870 of file code-serializer.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  SerializedCodeData scd(cached_data);
  *rejection_result =
      scd.SanityCheckWithoutSource(Snapshot::ExtractReadOnlySnapshotChecksum(
          local_isolate->snapshot_blob()));
  if (*rejection_result != SerializedCodeSanityCheckResult::kSuccess) {
    cached_data->Reject();
    return SerializedCodeData(nullptr, 0);
  }
  return scd;
}
References v8::internal::Snapshot::ExtractReadOnlySnapshotChecksum(), v8::internal::detail::kSuccess, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::AlignedCachedData::Reject(), SanityCheckWithoutSource(), SerializedCodeData(), and v8::internal::LocalIsolate::snapshot_blob().
Referenced by v8::ScriptCompiler::CachedData::CompatibilityCheck(), and v8::internal::CodeSerializer::StartDeserializeOffThread().
FromPartiallySanityCheckedCachedData()
SerializedCodeData v8::internal::SerializedCodeData::FromPartiallySanityCheckedCachedData (AlignedCachedData * cached_data, uint32_t expected_source_hash, SerializedCodeSanityCheckResult * rejection_result) [static]
Definition at line 885 of file code-serializer.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  // The previous call to FromCachedDataWithoutSource may have already rejected
  // the cached data, so reuse the previous rejection result if it's not a
  // success.
  if (*rejection_result != SerializedCodeSanityCheckResult::kSuccess) {
    // FromCachedDataWithoutSource doesn't check the source, so there can't be
    // a source mismatch.
    DCHECK_NE(*rejection_result,
              SerializedCodeSanityCheckResult::kSourceMismatch);
    cached_data->Reject();
    return SerializedCodeData(nullptr, 0);
  }
  SerializedCodeData scd(cached_data);
  *rejection_result = scd.SanityCheckJustSource(expected_source_hash);
  if (*rejection_result != SerializedCodeSanityCheckResult::kSuccess) {
    // This check only checks the source, so the only possible failure is a
    // source mismatch.
    DCHECK_EQ(*rejection_result,
              SerializedCodeSanityCheckResult::kSourceMismatch);
    cached_data->Reject();
    return SerializedCodeData(nullptr, 0);
  }
  return scd;
}
References DCHECK_EQ, DCHECK_NE, v8::internal::detail::kSuccess, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::AlignedCachedData::Reject(), SanityCheckJustSource(), and SerializedCodeData().
Referenced by v8::internal::CodeSerializer::FinishOffThreadDeserialize().
GetScriptData()
AlignedCachedData * v8::internal::SerializedCodeData::GetScriptData ()
Definition at line 834 of file code-serializer.cc.
                                                     {
  DCHECK(owns_data_);
  AlignedCachedData* result = new AlignedCachedData(data_, size_);
  result->AcquireDataOwnership();
  owns_data_ = false;
  data_ = nullptr;
  return result;
}
References v8::internal::DCHECK(), and v8::base::internal::result.
Referenced by v8::internal::CodeSerializer::SerializeSharedFunctionInfo().
Payload()
base::Vector< const uint8_t > v8::internal::SerializedCodeData::Payload () const
Definition at line 843 of file code-serializer.cc.
                                                            {
  const uint8_t* payload = data_ + kHeaderSize;
  DCHECK(IsAligned(reinterpret_cast<intptr_t>(payload), kPointerAlignment));
  int length = GetHeaderValue(kPayloadLengthOffset);
  DCHECK_EQ(data_ + size_, payload + length);
  return base::Vector<const uint8_t>(payload, length);
}
References v8::internal::DCHECK(), DCHECK_EQ, IsAligned(), v8::internal::kPointerAlignment, and v8::internal::length.
SanityCheck()
SerializedCodeSanityCheckResult v8::internal::SerializedCodeData::SanityCheck (uint32_t expected_ro_snapshot_checksum, uint32_t expected_source_hash) const [private]
Definition at line 763 of file code-serializer.cc.
                                         {
  SerializedCodeSanityCheckResult result =
      SanityCheckWithoutSource(expected_ro_snapshot_checksum);
  if (result != SerializedCodeSanityCheckResult::kSuccess) return result;
  return SanityCheckJustSource(expected_source_hash);
}
References v8::internal::detail::kSuccess, and v8::base::internal::result.
Referenced by FromCachedData().
SanityCheckJustSource()
SerializedCodeSanityCheckResult v8::internal::SerializedCodeData::SanityCheckJustSource (uint32_t expected_source_hash) const [private]
Definition at line 772 of file code-serializer.cc.
                                         {
  uint32_t source_hash = GetHeaderValue(kSourceHashOffset);
  if (source_hash != expected_source_hash) {
    return SerializedCodeSanityCheckResult::kSourceMismatch;
  }
  return SerializedCodeSanityCheckResult::kSuccess;
}
References v8::internal::detail::kSuccess, and v8::internal::CodeSerializer::source_hash().
Referenced by FromPartiallySanityCheckedCachedData().
SanityCheckWithoutSource()
SerializedCodeSanityCheckResult v8::internal::SerializedCodeData::SanityCheckWithoutSource (uint32_t expected_ro_snapshot_checksum) const [private]
Definition at line 781 of file code-serializer.cc.
                                                  {
  if (size_ < kHeaderSize) {
    return SerializedCodeSanityCheckResult::kInvalidHeader;
  }
  uint32_t magic_number = GetMagicNumber();
  if (magic_number != kMagicNumber) {
    return SerializedCodeSanityCheckResult::kMagicNumberMismatch;
  }
  uint32_t version_hash = GetHeaderValue(kVersionHashOffset);
  if (version_hash != Version::Hash()) {
    return SerializedCodeSanityCheckResult::kVersionMismatch;
  }
  uint32_t flags_hash = GetHeaderValue(kFlagHashOffset);
  if (flags_hash != FlagList::Hash()) {
    return SerializedCodeSanityCheckResult::kFlagsMismatch;
  }
  uint32_t ro_snapshot_checksum =
      GetHeaderValue(kReadOnlySnapshotChecksumOffset);
  if (ro_snapshot_checksum != expected_ro_snapshot_checksum) {
    return SerializedCodeSanityCheckResult::kReadOnlySnapshotChecksumMismatch;
  }
  uint32_t payload_length = GetHeaderValue(kPayloadLengthOffset);
  uint32_t max_payload_length = size_ - kHeaderSize;
  if (payload_length > max_payload_length) {
    return SerializedCodeSanityCheckResult::kLengthMismatch;
  }
  if (v8_flags.verify_snapshot_checksum) {
    uint32_t checksum = GetHeaderValue(kChecksumOffset);
    if (Checksum(ChecksummedContent()) != checksum) {
      return SerializedCodeSanityCheckResult::kChecksumMismatch;
    }
  }
  return SerializedCodeSanityCheckResult::kSuccess;
}
References v8::internal::Checksum(), v8::internal::FlagList::Hash(), v8::internal::Version::Hash(), v8::internal::detail::kSuccess, and v8::internal::v8_flags.
Referenced by FromCachedDataWithoutSource().
SourceHash()
uint32_t v8::internal::SerializedCodeData::SourceHash (DirectHandle< String > source, DirectHandle< FixedArray > wrapped_arguments, ScriptOriginOptions origin_options) [static]
Definition at line 817 of file code-serializer.cc.
                                        {
  using LengthField = base::BitField<uint32_t, 0, 29>;
  static_assert(String::kMaxLength <= LengthField::kMax,
                "String length must fit into a LengthField");
  using HasWrappedArgumentsField = LengthField::Next<bool, 1>;
  using IsModuleField = HasWrappedArgumentsField::Next<bool, 1>;
  uint32_t hash = 0;
  hash = LengthField::update(hash, source->length());
  hash = HasWrappedArgumentsField::update(hash, !wrapped_arguments.is_null());
  hash = IsModuleField::update(hash, origin_options.IsModule());
  return hash;
}
References v8::internal::DirectHandle< T >::is_null(), v8::ScriptOriginOptions::IsModule(), and v8::internal::String::kMaxLength.
Referenced by v8::internal::CodeSerializer::Deserialize(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), and v8::internal::CodeSerializer::Serialize().
Member Data Documentation
kChecksumOffset
const uint32_t v8::internal::SerializedCodeData::kChecksumOffset = kPayloadLengthOffset + kUInt32Size [static]
Definition at line 125 of file code-serializer.h.
kFlagHashOffset
const uint32_t v8::internal::SerializedCodeData::kFlagHashOffset = kSourceHashOffset + kUInt32Size [static]
Definition at line 120 of file code-serializer.h.
kHeaderSize
const uint32_t v8::internal::SerializedCodeData::kHeaderSize = POINTER_SIZE_ALIGN(kUnalignedHeaderSize) [static]
Definition at line 127 of file code-serializer.h.
kPayloadLengthOffset
const uint32_t v8::internal::SerializedCodeData::kPayloadLengthOffset [static]
Initial value:
=
      kReadOnlySnapshotChecksumOffset + kUInt32Size
Definition at line 123 of file code-serializer.h.
kReadOnlySnapshotChecksumOffset
const uint32_t v8::internal::SerializedCodeData::kReadOnlySnapshotChecksumOffset [static]
Initial value:
=
      kFlagHashOffset + kUInt32Size
Definition at line 121 of file code-serializer.h.
kSourceHashOffset
const uint32_t v8::internal::SerializedCodeData::kSourceHashOffset = kVersionHashOffset + kUInt32Size [static]
Definition at line 119 of file code-serializer.h.
kUnalignedHeaderSize
const uint32_t v8::internal::SerializedCodeData::kUnalignedHeaderSize = kChecksumOffset + kUInt32Size [static]
Definition at line 126 of file code-serializer.h.
kVersionHashOffset
const uint32_t v8::internal::SerializedCodeData::kVersionHashOffset = kMagicNumberOffset + kUInt32Size [static]
Definition at line 118 of file code-serializer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/code-serializer.h
/mnt/V8SourceCode/src/snapshot/code-serializer.cc