v8::internal::compiler::RegisterAllocator Class Reference
#include <register-allocator.h>
Public Member Functions
RegisterAllocator (RegisterAllocationData *data, RegisterKind kind)
RegisterAllocator (const RegisterAllocator &)=delete
RegisterAllocator & operator= (const RegisterAllocator &)=delete
Protected Types
using SpillMode = RegisterAllocationData::SpillMode
Protected Member Functions
RegisterAllocationData * data () const
InstructionSequence * code () const
RegisterKind mode () const
int num_registers () const
int num_allocatable_registers () const
const int * allocatable_register_codes () const
bool check_fp_aliasing () const
LifetimePosition GetSplitPositionForInstruction (const LiveRange *range, int instruction_index)
Zone * allocation_zone () const
void SplitAndSpillRangesDefinedByMemoryOperand ()
LiveRange * SplitRangeAt (LiveRange *range, LifetimePosition pos)
bool CanProcessRange (LiveRange *range) const
LiveRange * SplitBetween (LiveRange *range, LifetimePosition start, LifetimePosition end)
LifetimePosition FindOptimalSplitPos (LifetimePosition start, LifetimePosition end)
void Spill (LiveRange *range, SpillMode spill_mode)
LifetimePosition FindOptimalSpillingPos (LiveRange *range, LifetimePosition pos, SpillMode spill_mode, LiveRange **begin_spill_out)
const ZoneVector< TopLevelLiveRange * > & GetFixedRegisters () const
const char * RegisterName (int allocation_index) const
Private Attributes
RegisterAllocationData *const data_
const RegisterKind mode_
const int num_registers_
int num_allocatable_registers_
const int * allocatable_register_codes_
bool check_fp_aliasing_
bool no_combining_
Detailed Description
Definition at line 1463 of file register-allocator.h.
Member Typedef Documentation
SpillMode
using v8::internal::compiler::RegisterAllocator::SpillMode = RegisterAllocationData::SpillMode [protected]
Definition at line 1470 of file register-allocator.h.
Constructor & Destructor Documentation
RegisterAllocator() [1/2]
v8::internal::compiler::RegisterAllocator::RegisterAllocator (RegisterAllocationData * data, RegisterKind kind)
Definition at line 2717 of file register-allocator.cc.
    : data_(data),
      mode_(kind),
      num_registers_(GetRegisterCount(data->config(), kind)),
      num_allocatable_registers_(
          GetAllocatableRegisterCount(data->config(), kind)),
      allocatable_register_codes_(
          GetAllocatableRegisterCodes(data->config(), kind)),
      check_fp_aliasing_(false) {
  if (kFPAliasing == AliasingKind::kCombine && kind == RegisterKind::kDouble) {
    check_fp_aliasing_ = (data->code()->representation_mask() &
                          (kFloat32Bit | kSimd128Bit)) != 0;
  }
}
References check_fp_aliasing_, v8::internal::compiler::RegisterAllocationData::code(), data(), v8::internal::kCombine, v8::internal::compiler::kDouble, v8::internal::compiler::anonymous_namespace{register-allocator.cc}::kFloat32Bit, v8::internal::kFPAliasing, v8::internal::compiler::anonymous_namespace{register-allocator.cc}::kSimd128Bit, and v8::internal::compiler::InstructionSequence::representation_mask().
RegisterAllocator() [2/2]
v8::internal::compiler::RegisterAllocator::RegisterAllocator (const RegisterAllocator &) [delete]
Member Function Documentation
allocatable_register_codes()
const int* v8::internal::compiler::RegisterAllocator::allocatable_register_codes () const [inline], [protected]
Definition at line 1476 of file register-allocator.h.
                                                {
    return allocatable_register_codes_;
  }
References allocatable_register_codes_.
Referenced by v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), and v8::internal::compiler::LinearScanAllocator::PickRegisterThatIsAvailableLongest().
allocation_zone()
Zone* v8::internal::compiler::RegisterAllocator::allocation_zone () const [inline], [protected]
Definition at line 1486 of file register-allocator.h.
{ return data()->allocation_zone(); }
References v8::internal::compiler::RegisterAllocationData::allocation_zone(), and data().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), SplitRangeAt(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
CanProcessRange()
bool v8::internal::compiler::RegisterAllocator::CanProcessRange (LiveRange * range) const [inline], [protected]
Definition at line 1500 of file register-allocator.h.
                                               {
    return range != nullptr && !range->IsEmpty() && range->kind() == mode();
  }
References v8::internal::compiler::LiveRange::IsEmpty(), v8::internal::compiler::LiveRange::kind(), and mode().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::PrintRangeOverview(), and SplitAndSpillRangesDefinedByMemoryOperand().
check_fp_aliasing()
bool v8::internal::compiler::RegisterAllocator::check_fp_aliasing () const [inline], [protected]
Definition at line 1480 of file register-allocator.h.
{ return check_fp_aliasing_; }
References check_fp_aliasing_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
code()
InstructionSequence* v8::internal::compiler::RegisterAllocator::code () const [inline], [protected]
Definition at line 1472 of file register-allocator.h.
{ return data()->code(); }
References v8::internal::compiler::RegisterAllocationData::code(), and data().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::BlockIsDeferredOrImmediatePredecessorIsNotDeferred(), v8::internal::compiler::LinearScanAllocator::ConsiderBlockForControlFlow(), FindOptimalSpillingPos(), FindOptimalSplitPos(), v8::internal::compiler::LinearScanAllocator::HasNonDeferredPredecessor(), v8::internal::compiler::LinearScanAllocator::LastDeferredInstructionIndex(), v8::internal::compiler::LinearScanAllocator::PickRegisterThatIsAvailableLongest(), v8::internal::compiler::LinearScanAllocator::PrintRangeOverview(), Spill(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), SplitRangeAt(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
data()
RegisterAllocationData* v8::internal::compiler::RegisterAllocator::data () const [inline], [protected]
Definition at line 1471 of file register-allocator.h.
{ return data_; }
References data_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), allocation_zone(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), v8::internal::compiler::LinearScanAllocator::CheckConflict(), v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), code(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet(), v8::internal::compiler::LinearScanAllocator::GetSIMD128RegisterSet(), v8::internal::compiler::LinearScanAllocator::PickRegisterThatIsAvailableLongest(), v8::internal::compiler::LinearScanAllocator::PrintRangeOverview(), RegisterAllocator(), v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister(), Spill(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), SplitAndSpillRangesDefinedByMemoryOperand(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
FindOptimalSpillingPos()
LifetimePosition v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos (LiveRange * range, LifetimePosition pos, SpillMode spill_mode, LiveRange ** begin_spill_out) [protected]
Definition at line 2856 of file register-allocator.cc.
                                 {
  *begin_spill_out = range;
  // TODO(herhut): Be more clever here as long as we do not move pos out of
  // deferred code.
  if (spill_mode == SpillMode::kSpillDeferred) return pos;
  const InstructionBlock* block = GetInstructionBlock(code(), pos.Start());
  const InstructionBlock* loop_header =
      block->IsLoopHeader() ? block : GetContainingLoop(code(), block);
  if (loop_header == nullptr) return pos;
  while (loop_header != nullptr) {
    // We are going to spill live range inside the loop.
    // If possible try to move spilling position backwards to loop header.
    // This will reduce number of memory moves on the back edge.
    LifetimePosition loop_start = LifetimePosition::GapFromInstructionIndex(
        loop_header->first_instruction_index());
    // Stop if we moved to a loop header before the value is defined or
    // at the define position that is not beneficial to spill.
    if (range->TopLevel()->Start() > loop_start ||
        (range->TopLevel()->Start() == loop_start &&
         range->TopLevel()->SpillAtLoopHeaderNotBeneficial()))
      return pos;
    LiveRange* live_at_header = range->TopLevel()->GetChildCovers(loop_start);
    if (live_at_header != nullptr && !live_at_header->spilled()) {
      for (const LiveRange* check_use = live_at_header;
           check_use != nullptr && check_use->Start() < pos;
           check_use = check_use->next()) {
        // If we find a use for which spilling is detrimental, don't spill
        // at the loop header
        UsePosition* next_use =
            check_use->NextUsePositionSpillDetrimental(loop_start);
        // UsePosition at the end of a UseInterval may
        // have the same value as the start of next range.
        if (next_use != nullptr && next_use->pos() <= pos) {
          return pos;
        }
      }
      // No register beneficial use inside the loop before the pos.
      *begin_spill_out = live_at_header;
      pos = loop_start;
    }
    // Try hoisting out to an outer loop.
    loop_header = GetContainingLoop(code(), loop_header);
  }
  return pos;
}
References code(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::TopLevelLiveRange::GetChildCovers(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetContainingLoop(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::InstructionBlock::IsLoopHeader(), v8::internal::compiler::UsePosition::pos(), v8::internal::compiler::TopLevelLiveRange::SpillAtLoopHeaderNotBeneficial(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::LifetimePosition::Start(), v8::internal::compiler::LiveRange::Start(), and v8::internal::compiler::LiveRange::TopLevel().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), and v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting().
FindOptimalSplitPos()
LifetimePosition v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos (LifetimePosition start, LifetimePosition end) [protected]
Definition at line 2818 of file register-allocator.cc.
                                                                              {
  int start_instr = start.ToInstructionIndex();
  int end_instr = end.ToInstructionIndex();
  DCHECK_LE(start_instr, end_instr);
  // We have no choice
  if (start_instr == end_instr) return end;
  const InstructionBlock* start_block = GetInstructionBlock(code(), start);
  const InstructionBlock* end_block = GetInstructionBlock(code(), end);
  if (end_block == start_block) {
    // The interval is split in the same basic block. Split at the latest
    // possible position.
    return end;
  }
  const InstructionBlock* block = end_block;
  // Find header of outermost loop.
  do {
    const InstructionBlock* loop = GetContainingLoop(code(), block);
    if (loop == nullptr ||
        loop->rpo_number().ToInt() <= start_block->rpo_number().ToInt()) {
      // No more loops or loop starts before the lifetime start.
      break;
    }
    block = loop;
  } while (true);
  // We did not find any suitable outer loop. Split at the latest possible
  // position unless end_block is a loop header itself.
  if (block == end_block && !end_block->IsLoopHeader()) return end;
  return LifetimePosition::GapFromInstructionIndex(
      block->first_instruction_index());
}
References code(), DCHECK_LE, v8::internal::compiler::end(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetContainingLoop(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::InstructionBlock::IsLoopHeader(), v8::internal::compiler::InstructionBlock::rpo_number(), v8::internal::compiler::LifetimePosition::ToInstructionIndex(), and v8::internal::compiler::RpoNumber::ToInt().
Referenced by SplitAndSpillRangesDefinedByMemoryOperand(), and SplitBetween().
GetFixedRegisters()
const ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocator::GetFixedRegisters () const [protected]
GetSplitPositionForInstruction()
LifetimePosition v8::internal::compiler::RegisterAllocator::GetSplitPositionForInstruction (const LiveRange * range, int instruction_index) [protected]
Definition at line 2733 of file register-allocator.cc.
                                                   {
  LifetimePosition ret = LifetimePosition::Invalid();
  ret = LifetimePosition::GapFromInstructionIndex(instruction_index);
  if (range->Start() >= ret || ret >= range->End()) {
    return LifetimePosition::Invalid();
  }
  return ret;
}
References v8::internal::compiler::LiveRange::End(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::LifetimePosition::Invalid(), and v8::internal::compiler::LiveRange::Start().
Referenced by SplitAndSpillRangesDefinedByMemoryOperand().
mode()
RegisterKind v8::internal::compiler::RegisterAllocator::mode () const [inline], [protected]
Definition at line 1473 of file register-allocator.h.
{ return mode_; }
References mode_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), CanProcessRange(), RegisterName(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
num_allocatable_registers()
int v8::internal::compiler::RegisterAllocator::num_allocatable_registers () const [inline], [protected]
Definition at line 1475 of file register-allocator.h.
{ return num_allocatable_registers_; }
References num_allocatable_registers_.
Referenced by v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), and v8::internal::compiler::LinearScanAllocator::PickRegisterThatIsAvailableLongest().
num_registers()
int v8::internal::compiler::RegisterAllocator::num_registers () const [inline], [protected]
Definition at line 1474 of file register-allocator.h.
{ return num_registers_; }
References num_registers_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::LinearScanAllocator::ForwardStateTo(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
operator=()
RegisterAllocator& v8::internal::compiler::RegisterAllocator::operator= (const RegisterAllocator &) [delete]
RegisterName()
const char * v8::internal::compiler::RegisterAllocator::RegisterName (int allocation_index) const [protected]
Definition at line 2933 of file register-allocator.cc.
                                                                   {
  if (register_code == kUnassignedRegister) return "unassigned";
  switch (mode()) {
    case RegisterKind::kGeneral:
      return i::RegisterName(Register::from_code(register_code));
    case RegisterKind::kDouble:
      return i::RegisterName(DoubleRegister::from_code(register_code));
    case RegisterKind::kSimd128:
      return i::RegisterName(Simd128Register::from_code(register_code));
  }
}
References v8::internal::Register::from_code(), v8::internal::RegisterBase< Simd128Register, kSimd128AfterLast >::from_code(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), v8::internal::compiler::kDouble, v8::internal::compiler::kGeneral, v8::internal::compiler::kSimd128, v8::internal::compiler::kUnassignedRegister, and mode().
Referenced by v8::internal::compiler::LinearScanAllocator::AddToActive(), v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::LinearScanAllocator::PickRegisterThatIsAvailableLongest(), v8::internal::compiler::LinearScanAllocator::PrintRangeRow(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
Spill()
void v8::internal::compiler::RegisterAllocator::Spill (LiveRange * range, SpillMode spill_mode) [protected]
Definition at line 2908 of file register-allocator.cc.
                                                                    {
  DCHECK(!range->spilled());
  DCHECK(spill_mode == SpillMode::kSpillAtDefinition ||
         GetInstructionBlock(code(), range->Start())->IsDeferred());
  TopLevelLiveRange* first = range->TopLevel();
  TRACE("Spilling live range %d:%d mode %d\n", first->vreg(),
        range->relative_id(), spill_mode);
  TRACE("Starting spill type is %d\n", static_cast<int>(first->spill_type()));
  if (first->HasNoSpillType()) {
    TRACE("New spill range needed\n");
    data()->AssignSpillRangeToLiveRange(first, spill_mode);
  }
  // Upgrade the spillmode, in case this was only spilled in deferred code so
  // far.
  if ((spill_mode == SpillMode::kSpillAtDefinition) &&
      (first->spill_type() ==
       TopLevelLiveRange::SpillType::kDeferredSpillRange)) {
    TRACE("Upgrading\n");
    first->set_spill_type(TopLevelLiveRange::SpillType::kSpillRange);
  }
  TRACE("Final spill type is %d\n", static_cast<int>(first->spill_type()));
  range->Spill();
}
References v8::internal::compiler::RegisterAllocationData::AssignSpillRangeToLiveRange(), code(), data(), v8::internal::DCHECK(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::TopLevelLiveRange::HasNoSpillType(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::TopLevelLiveRange::kDeferredSpillRange, v8::internal::compiler::TopLevelLiveRange::kSpillRange, v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::TopLevelLiveRange::set_spill_type(), v8::internal::compiler::LiveRange::Spill(), v8::internal::compiler::TopLevelLiveRange::spill_type(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::SpillAfter(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), SplitAndSpillRangesDefinedByMemoryOperand(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
SplitAndSpillRangesDefinedByMemoryOperand()
void v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand () [protected]
Definition at line 2744 of file register-allocator.cc.
                                                                  {
  size_t initial_range_count = data()->live_ranges().size();
  for (size_t i = 0; i < initial_range_count; ++i) {
    CHECK_EQ(initial_range_count,
             data()->live_ranges().size()); // TODO(neis): crbug.com/831822
    TopLevelLiveRange* range = data()->live_ranges()[i];
    if (!CanProcessRange(range)) continue;
    // Only assume defined by memory operand if we are guaranteed to spill it or
    // it has a spill operand.
    if (range->HasNoSpillType() ||
        (range->HasSpillRange() && !range->has_non_deferred_slot_use())) {
      continue;
    }
    LifetimePosition start = range->Start();
    TRACE("Live range %d:%d is defined by a spill operand.\n",
          range->TopLevel()->vreg(), range->relative_id());
    LifetimePosition next_pos = start;
    if (next_pos.IsGapPosition()) {
      next_pos = next_pos.NextStart();
    }
    UsePosition* pos = range->NextUsePositionRegisterIsBeneficial(next_pos);
    // If the range already has a spill operand and it doesn't need a
    // register immediately, split it and spill the first part of the range.
    if (pos == nullptr) {
      Spill(range, SpillMode::kSpillAtDefinition);
    } else if (pos->pos() > range->Start().NextStart()) {
      // Do not spill live range eagerly if use position that can benefit from
      // the register is too close to the start of live range.
      LifetimePosition split_pos = GetSplitPositionForInstruction(
          range, pos->pos().ToInstructionIndex());
      // There is no place to split, so we can't split and spill.
      if (!split_pos.IsValid()) continue;
      split_pos =
          FindOptimalSplitPos(range->Start().NextFullStart(), split_pos);
      SplitRangeAt(range, split_pos);
      Spill(range, SpillMode::kSpillAtDefinition);
    }
  }
}
References CanProcessRange(), CHECK_EQ, data(), FindOptimalSplitPos(), GetSplitPositionForInstruction(), v8::internal::compiler::TopLevelLiveRange::has_non_deferred_slot_use(), v8::internal::compiler::TopLevelLiveRange::HasNoSpillType(), v8::internal::compiler::TopLevelLiveRange::HasSpillRange(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::LifetimePosition::IsGapPosition(), v8::internal::compiler::LifetimePosition::IsValid(), v8::internal::compiler::RegisterAllocationData::live_ranges(), v8::internal::compiler::LifetimePosition::NextFullStart(), v8::internal::compiler::LifetimePosition::NextStart(), v8::internal::compiler::LiveRange::NextUsePositionRegisterIsBeneficial(), v8::internal::compiler::UsePosition::pos(), v8::internal::compiler::LiveRange::relative_id(), size(), Spill(), SplitRangeAt(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LifetimePosition::ToInstructionIndex(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters().
SplitBetween()
LiveRange * v8::internal::compiler::RegisterAllocator::SplitBetween (LiveRange * range, LifetimePosition start, LifetimePosition end) [protected]
Definition at line 2805 of file register-allocator.cc.
                                                                 {
  DCHECK(!range->TopLevel()->IsFixed());
  TRACE("Splitting live range %d:%d in position between [%d, %d]\n",
        range->TopLevel()->vreg(), range->relative_id(), start.value(),
        end.value());
  LifetimePosition split_pos = FindOptimalSplitPos(start, end);
  DCHECK(split_pos >= start);
  return SplitRangeAt(range, split_pos);
}
References v8::internal::DCHECK(), v8::internal::compiler::end(), FindOptimalSplitPos(), v8::internal::compiler::TopLevelLiveRange::IsFixed(), v8::internal::compiler::LiveRange::relative_id(), SplitRangeAt(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), and v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil().
SplitRangeAt()
LiveRange * v8::internal::compiler::RegisterAllocator::SplitRangeAt (LiveRange * range, LifetimePosition pos) [protected]
Definition at line 2787 of file register-allocator.cc.
                                                                 {
  DCHECK(!range->TopLevel()->IsFixed());
  TRACE("Splitting live range %d:%d at %d\n", range->TopLevel()->vreg(),
        range->relative_id(), pos.value());
  if (pos <= range->Start()) return range;
  // We can't properly connect liveranges if splitting occurred at the end
  // a block.
  DCHECK(pos.IsStart() || pos.IsGapPosition() ||
         (GetInstructionBlock(code(), pos)->last_instruction_index() !=
          pos.ToInstructionIndex()));
  LiveRange* result = range->SplitAt(pos, allocation_zone());
  return result;
}
References allocation_zone(), code(), v8::internal::DCHECK(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::TopLevelLiveRange::IsFixed(), v8::internal::compiler::LifetimePosition::IsGapPosition(), v8::internal::compiler::LifetimePosition::IsStart(), v8::internal::compiler::LiveRange::relative_id(), v8::base::internal::result, v8::internal::compiler::LiveRange::SplitAt(), v8::internal::compiler::LifetimePosition::ToInstructionIndex(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), v8::internal::compiler::LinearScanAllocator::SpillAfter(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), SplitAndSpillRangesDefinedByMemoryOperand(), SplitBetween(), and v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg().
Member Data Documentation
allocatable_register_codes_
const int* v8::internal::compiler::RegisterAllocator::allocatable_register_codes_ [private]
Definition at line 1531 of file register-allocator.h.
Referenced by allocatable_register_codes().
check_fp_aliasing_
bool v8::internal::compiler::RegisterAllocator::check_fp_aliasing_ [private]
Definition at line 1532 of file register-allocator.h.
Referenced by check_fp_aliasing(), and RegisterAllocator().
data_
RegisterAllocationData* const v8::internal::compiler::RegisterAllocator::data_ [private]
Definition at line 1527 of file register-allocator.h.
Referenced by data().
mode_
const RegisterKind v8::internal::compiler::RegisterAllocator::mode_ [private]
Definition at line 1528 of file register-allocator.h.
Referenced by mode().
no_combining_
bool v8::internal::compiler::RegisterAllocator::no_combining_ [private]
Definition at line 1535 of file register-allocator.h.
num_allocatable_registers_
int v8::internal::compiler::RegisterAllocator::num_allocatable_registers_ [private]
Definition at line 1530 of file register-allocator.h.
Referenced by num_allocatable_registers().
num_registers_
const int v8::internal::compiler::RegisterAllocator::num_registers_ [private]
Definition at line 1529 of file register-allocator.h.
Referenced by num_registers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc