v8::internal::compiler::NameRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< Name > object () const
bool IsUniqueName () const
Detailed Description
Definition at line 813 of file heap-refs.h.
Member Function Documentation
IsUniqueName()
bool v8::internal::compiler::NameRef::IsUniqueName () const
Definition at line 2359 of file heap-refs.cc.
                                 {
  // Must match Name::IsUniqueName.
  return IsInternalizedString() || IsSymbol();
}
References v8::internal::InstanceTypeChecker::IsInternalizedString().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess().
object()
IndirectHandle<Name> v8::internal::compiler::NameRef::object () const
Referenced by v8::internal::compiler::PropertyAccessTarget::Hash::operator()(), v8::internal::maglev::LoadGlobal::PrintParams(), v8::internal::maglev::StoreGlobal::PrintParams(), v8::internal::maglev::LoadNamedGeneric::PrintParams(), v8::internal::maglev::LoadNamedFromSuperGeneric::PrintParams(), v8::internal::maglev::SetNamedGeneric::PrintParams(), v8::internal::maglev::DefineNamedOwnGeneric::PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc