v8::InternalEscapableScope Class Reference
#include <api-inl.h>
Public Member Functions
InternalEscapableScope (i::Isolate *isolate)
template<class T >
Local< T > Escape (Local< T > value)
Pushes the value into the previous scope and returns a handle to it.
template<class T >
MaybeLocal< T > EscapeMaybe (MaybeLocal< T > maybe_value)
Additional Inherited Members
Detailed Description
Definition at line 225 of file api-inl.h.
Constructor & Destructor Documentation
InternalEscapableScope()
v8::InternalEscapableScope::InternalEscapableScope (i::Isolate * isolate) [inline], [explicit]
Definition at line 227 of file api-inl.h.
      : EscapableHandleScopeBase(reinterpret_cast<v8::Isolate*>(isolate)) {}
Member Function Documentation
Escape()
template<class T >
Local<T> v8::InternalEscapableScope::Escape (Local< T > value) [inline]
Pushes the value into the previous scope and returns a handle to it.
Cannot be called twice.
Definition at line 235 of file api-inl.h.
                                            {
#ifdef V8_ENABLE_DIRECT_HANDLE
    return value;
#else
    DCHECK(!value.IsEmpty());
    return Local<T>::FromSlot(EscapeSlot(value.slot()));
#endif
  }
References DCHECK, v8::Local< T >::FromSlot(), and v8::internal::value.
Referenced by v8::Message::Get(), v8::Message::GetSource(), v8::Message::GetSourceLine(), and v8::Message::GetStackTrace().
EscapeMaybe()
template<class T >
MaybeLocal<T> v8::InternalEscapableScope::EscapeMaybe (MaybeLocal< T > maybe_value) [inline]
Definition at line 245 of file api-inl.h.
                                                                 {
    Local<T> value;
    if (!maybe_value.ToLocal(&value)) return maybe_value;
    return Escape(value);
  }
References v8::MaybeLocal< T >::ToLocal(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/api/api-inl.h