v8::internal::wasm::NativeModuleDeserializer Class Reference
Public Member Functions
NativeModuleDeserializer (NativeModule *)
NativeModuleDeserializer (const NativeModuleDeserializer &)=delete
NativeModuleDeserializer & operator= (const NativeModuleDeserializer &)=delete
bool Read (Reader *reader)
base::Vector< const int > lazy_functions ()
base::Vector< const int > eager_functions ()
Private Member Functions
void ReadHeader (Reader *reader)
DeserializationUnit ReadCode (int fn_index, Reader *reader)
void ReadTieringBudget (Reader *reader)
void CopyAndRelocate (const DeserializationUnit &unit)
void Publish (std::vector< DeserializationUnit > batch)
Private Attributes
NativeModule *const native_module_
size_t remaining_code_size_ = 0
bool all_functions_validated_ = false
CompileTimeImports compile_imports_
base::Vector< uint8_t > current_code_space_
NativeModule::JumpTablesRef current_jump_tables_
std::vector< int > lazy_functions_
std::vector< int > eager_functions_
Friends
class DeserializeCodeTask
Detailed Description
Definition at line 698 of file wasm-serialization.cc.
Constructor & Destructor Documentation
NativeModuleDeserializer() [1/2]
v8::internal::wasm::NativeModuleDeserializer::NativeModuleDeserializer (NativeModule * native_module) [explicit]
Definition at line 799 of file wasm-serialization.cc.
    : native_module_(native_module) {}
NativeModuleDeserializer() [2/2]
v8::internal::wasm::NativeModuleDeserializer::NativeModuleDeserializer (const NativeModuleDeserializer &) [delete]
Member Function Documentation
CopyAndRelocate()
void v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate (const DeserializationUnit & unit) [private]
Definition at line 967 of file wasm-serialization.cc.
                                     {
  WritableJitAllocation jit_allocation = ThreadIsolation::RegisterJitAllocation(
      reinterpret_cast<Address>(unit.code->instructions().begin()),
      unit.code->instructions().size(),
      ThreadIsolation::JitAllocationType::kWasmCode, false);
  jit_allocation.CopyCode(0, unit.src_code_buffer.begin(),
                          unit.src_code_buffer.size());
  // Relocate the code.
  int kMask = RelocInfo::ModeMask(RelocInfo::WASM_CALL) |
              RelocInfo::ModeMask(RelocInfo::WASM_STUB_CALL) |
              RelocInfo::ModeMask(RelocInfo::WASM_CANONICAL_SIG_ID) |
              RelocInfo::ModeMask(RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY) |
              RelocInfo::ModeMask(RelocInfo::EXTERNAL_REFERENCE) |
              RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE) |
              RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE_ENCODED);
  for (WritableRelocIterator iter(jit_allocation, unit.code->instructions(),
                                  unit.code->reloc_info(),
                                  unit.code->constant_pool(), kMask);
       !iter.done(); iter.next()) {
    RelocInfo::Mode mode = iter.rinfo()->rmode();
    switch (mode) {
      case RelocInfo::WASM_CALL: {
        uint32_t tag = GetWasmCalleeTag(iter.rinfo());
        Address target =
            native_module_->GetNearCallTargetForFunction(tag, unit.jump_tables);
        iter.rinfo()->set_wasm_call_address(target);
        break;
      }
      case RelocInfo::WASM_STUB_CALL: {
        uint32_t tag = GetWasmCalleeTag(iter.rinfo());
        Address target = native_module_->GetJumpTableEntryForBuiltin(
            static_cast<Builtin>(tag), unit.jump_tables);
        iter.rinfo()->set_wasm_stub_call_address(target);
        break;
      }
      case RelocInfo::WASM_CANONICAL_SIG_ID: {
        // This is intentional: in serialized code, we patched embedded
        // canonical signature IDs with their module-specific equivalents,
        // so although the accessor is called "wasm_canonical_sig_id()", what
        // we get back is actually a module-specific signature ID, which we
        // now need to translate back to a canonical ID.
        ModuleTypeIndex module_local_sig_id{
            iter.rinfo()->wasm_canonical_sig_id()};
        CanonicalTypeIndex canonical_sig_id =
            native_module_->module()->canonical_sig_id(module_local_sig_id);
        iter.rinfo()->set_wasm_canonical_sig_id(canonical_sig_id.index);
      } break;
      case RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY: {
        Address function_index =
            iter.rinfo()->wasm_code_pointer_table_entry().value();
        WasmCodePointer target = native_module_->GetCodePointerHandle(
            base::checked_cast<uint32_t>(function_index));
        iter.rinfo()->set_wasm_code_pointer_table_entry(target,
                                                        SKIP_ICACHE_FLUSH);
      } break;
      case RelocInfo::EXTERNAL_REFERENCE: {
        uint32_t tag = GetWasmCalleeTag(iter.rinfo());
        Address address = ExternalReferenceList::Get().address_from_tag(tag);
        iter.rinfo()->set_target_external_reference(address, SKIP_ICACHE_FLUSH);
        break;
      }
      case RelocInfo::INTERNAL_REFERENCE:
      case RelocInfo::INTERNAL_REFERENCE_ENCODED: {
        Address offset = iter.rinfo()->target_internal_reference();
        Address target = unit.code->instruction_start() + offset;
        Assembler::deserialization_set_target_internal_reference_at(
            iter.rinfo()->pc(), target, jit_allocation, mode);
        break;
      }
      default:
        UNREACHABLE();
    }
  }
  // Finally, flush the icache for that code.
  FlushInstructionCache(unit.code->instructions().begin(),
                        unit.code->instructions().size());
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::WasmModule::canonical_sig_id(), v8::internal::wasm::DeserializationUnit::code, v8::internal::WritableJitAllocation::CopyCode(), v8::internal::Assembler::deserialization_set_target_internal_reference_at(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::RelocInfo::EXTERNAL_REFERENCE, v8::internal::FlushInstructionCache(), v8::internal::compiler::turboshaft::Get(), v8::internal::wasm::NativeModule::GetCodePointerHandle(), v8::internal::wasm::NativeModule::GetJumpTableEntryForBuiltin(), v8::internal::wasm::NativeModule::GetNearCallTargetForFunction(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::wasm::TypeIndex::index, v8::internal::RelocInfo::INTERNAL_REFERENCE, v8::internal::RelocInfo::INTERNAL_REFERENCE_ENCODED, v8::internal::wasm::DeserializationUnit::jump_tables, v8::internal::ThreadIsolation::kWasmCode, mode(), v8::internal::RelocInfo::ModeMask(), v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::ThreadIsolation::RegisterJitAllocation(), v8::base::Vector< T >::size(), v8::internal::SKIP_ICACHE_FLUSH, v8::internal::wasm::DeserializationUnit::src_code_buffer, v8::internal::UNREACHABLE(), v8::internal::RelocInfo::WASM_CALL, v8::internal::RelocInfo::WASM_CANONICAL_SIG_ID, v8::internal::RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY, and v8::internal::RelocInfo::WASM_STUB_CALL.
Referenced by v8::internal::wasm::DeserializeCodeTask::Run().
eager_functions()
base::Vector<const int> v8::internal::wasm::NativeModuleDeserializer::eager_functions () [inline]
Definition at line 710 of file wasm-serialization.cc.
                                          {
    return base::VectorOf(eager_functions_);
  }
References v8::base::VectorOf().
Referenced by v8::internal::wasm::DeserializeNativeModule().
lazy_functions()
base::Vector<const int> v8::internal::wasm::NativeModuleDeserializer::lazy_functions () [inline]
Definition at line 706 of file wasm-serialization.cc.
                                         {
    return base::VectorOf(lazy_functions_);
  }
References v8::base::VectorOf().
Referenced by v8::internal::wasm::DeserializeNativeModule().
operator=()
NativeModuleDeserializer& v8::internal::wasm::NativeModuleDeserializer::operator= (const NativeModuleDeserializer &) [delete]
Publish()
void v8::internal::wasm::NativeModuleDeserializer::Publish (std::vector< DeserializationUnit > batch) [private]
Definition at line 1062 of file wasm-serialization.cc.
                                                                           {
  DCHECK(!batch.empty());
  std::vector<UnpublishedWasmCode> codes;
  codes.reserve(batch.size());
  for (auto& unit : batch) {
    // We serialized the code assumptions for well-known imports (see
    // {WasmSerializer::import_statuses_}, so when publishing the deserialized
    // code here we do not need to pass any assumptions.
    codes.emplace_back(UnpublishedWasmCode{
        std::move(unit).code, std::unique_ptr<AssumptionsJournal>{
                                  UnpublishedWasmCode::kNoAssumptions}});
  }
  auto published_codes = native_module_->PublishCode(base::VectorOf(codes));
  for (auto* wasm_code : published_codes) {
    wasm_code->MaybePrint();
    wasm_code->Validate();
  }
}
References v8::internal::wasm::UnpublishedWasmCode::code, v8::internal::DCHECK(), v8::internal::wasm::UnpublishedWasmCode::kNoAssumptions, v8::internal::wasm::WasmCode::MaybePrint(), native_module_, v8::internal::wasm::NativeModule::PublishCode(), and v8::base::VectorOf().
Referenced by v8::internal::wasm::DeserializeCodeTask::TryPublishing().
Read()
bool v8::internal::wasm::NativeModuleDeserializer::Read (Reader * reader)
Definition at line 802 of file wasm-serialization.cc.
                                                  {
  DCHECK(!read_called_);
#ifdef DEBUG
  read_called_ = true;
#endif
  ReadHeader(reader);
  if (compile_imports_.compare(native_module_->compile_imports()) != 0) {
    return false;
  }
  uint32_t total_fns = native_module_->num_functions();
  uint32_t first_wasm_fn = native_module_->num_imported_functions();
  if (all_functions_validated_) {
    native_module_->module()->set_all_functions_validated();
  }
  WasmCodeRefScope wasm_code_ref_scope;
  DeserializationQueue reloc_queue;
  // Create a new job without any workers; those are spawned on
  // {NotifyConcurrencyIncrease}.
  std::unique_ptr<JobHandle> job_handle = V8::GetCurrentPlatform()->CreateJob(
      TaskPriority::kUserVisible,
      std::make_unique<DeserializeCodeTask>(this, &reloc_queue));
  // Choose a batch size such that we do not create too small batches (>=100k
  // code bytes), but also not too many (<=100 batches).
  constexpr size_t kMinBatchSizeInBytes = 100000;
  size_t batch_limit =
      std::max(kMinBatchSizeInBytes, remaining_code_size_ / 100);
  std::vector<DeserializationUnit> batch;
  size_t batch_size = 0;
  for (uint32_t i = first_wasm_fn; i < total_fns; ++i) {
    DeserializationUnit unit = ReadCode(i, reader);
    if (!unit.code) continue;
    batch_size += unit.code->instructions().size();
    batch.emplace_back(std::move(unit));
    if (batch_size >= batch_limit) {
      reloc_queue.Add(std::move(batch));
      DCHECK(batch.empty());
      batch_size = 0;
      job_handle->NotifyConcurrencyIncrease();
    }
  }
  // We should have read the expected amount of code now, and should have fully
  // utilized the allocated code space.
  DCHECK_EQ(0, remaining_code_size_);
  DCHECK_EQ(0, current_code_space_.size());
  if (!batch.empty()) {
    reloc_queue.Add(std::move(batch));
    job_handle->NotifyConcurrencyIncrease();
  }
  // Wait for all tasks to finish, while participating in their work.
  job_handle->Join();
  ReadTieringBudget(reader);
  return reader->current_size() == 0;
}
References v8::internal::wasm::DeserializationQueue::Add(), all_functions_validated_, v8::internal::wasm::DeserializationUnit::code, v8::internal::wasm::CompileTimeImports::compare(), v8::internal::wasm::NativeModule::compile_imports(), compile_imports_, v8::Platform::CreateJob(), current_code_space_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::V8::GetCurrentPlatform(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::kUserVisible, v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::wasm::NativeModule::num_functions(), v8::internal::wasm::NativeModule::num_imported_functions(), ReadCode(), ReadHeader(), ReadTieringBudget(), remaining_code_size_, v8::internal::wasm::WasmModule::set_all_functions_validated(), and v8::base::Vector< T >::size().
Referenced by v8::internal::wasm::DeserializeNativeModule().
ReadCode()
DeserializationUnit v8::internal::wasm::NativeModuleDeserializer::ReadCode (int fn_index, Reader * reader) [private]
Definition at line 897 of file wasm-serialization.cc.
                                                                       {
  uint8_t code_kind = reader->Read<uint8_t>();
  if (code_kind == kLazyFunction) {
    lazy_functions_.push_back(fn_index);
    return {};
  }
  if (code_kind == kEagerFunction) {
    eager_functions_.push_back(fn_index);
    return {};
  }
  int constant_pool_offset = reader->Read<int>();
  int safepoint_table_offset = reader->Read<int>();
  int handler_table_offset = reader->Read<int>();
  int code_comment_offset = reader->Read<int>();
  int jump_table_info_offset = reader->Read<int>();
  int unpadded_binary_size = reader->Read<int>();
  int stack_slot_count = reader->Read<int>();
  int ool_spill_count = reader->Read<int>();
  uint32_t tagged_parameter_slots = reader->Read<uint32_t>();
  int code_size = reader->Read<int>();
  int reloc_size = reader->Read<int>();
  int source_position_size = reader->Read<int>();
  int inlining_position_size = reader->Read<int>();
  int deopt_data_size = reader->Read<int>();
  // TODO(mliedtke): protected_instructions_data is the first part of the
  // meta_data_ array. Ideally the sizes would be in the same order...
  int protected_instructions_size = reader->Read<int>();
  WasmCode::Kind kind = reader->Read<WasmCode::Kind>();
  ExecutionTier tier = reader->Read<ExecutionTier>();
  DCHECK(IsAligned(code_size, kCodeAlignment));
  DCHECK_GE(remaining_code_size_, code_size);
  if (current_code_space_.size() < static_cast<size_t>(code_size)) {
    // Allocate the next code space. Don't allocate more than 90% of
    // {kMaxCodeSpaceSize}, to leave some space for jump tables.
    size_t max_reservation = RoundUp<kCodeAlignment>(
        v8_flags.wasm_max_code_space_size_mb * MB * 9 / 10);
    size_t code_space_size = std::min(max_reservation, remaining_code_size_);
    std::tie(current_code_space_, current_jump_tables_) =
        native_module_->AllocateForDeserializedCode(code_space_size);
    DCHECK_EQ(current_code_space_.size(), code_space_size);
    CHECK(current_jump_tables_.is_valid());
  }
  DeserializationUnit unit;
  unit.src_code_buffer = reader->ReadVector<uint8_t>(code_size);
  auto reloc_info = reader->ReadVector<uint8_t>(reloc_size);
  auto source_pos = reader->ReadVector<uint8_t>(source_position_size);
  auto inlining_pos = reader->ReadVector<uint8_t>(inlining_position_size);
  auto deopt_data = reader->ReadVector<uint8_t>(deopt_data_size);
  auto protected_instructions =
      reader->ReadVector<uint8_t>(protected_instructions_size);
  base::Vector<uint8_t> instructions =
      current_code_space_.SubVector(0, code_size);
  current_code_space_ += code_size;
  remaining_code_size_ -= code_size;
  unit.code = native_module_->AddDeserializedCode(
      fn_index, instructions, stack_slot_count, ool_spill_count,
      tagged_parameter_slots, safepoint_table_offset, handler_table_offset,
      constant_pool_offset, code_comment_offset, jump_table_info_offset,
      unpadded_binary_size, protected_instructions, reloc_info, source_pos,
      inlining_pos, deopt_data, kind, tier);
  unit.jump_tables = current_jump_tables_;
  return unit;
}
References v8::internal::wasm::NativeModule::AddDeserializedCode(), v8::internal::wasm::NativeModule::AllocateForDeserializedCode(), CHECK, v8::internal::wasm::DeserializationUnit::code, current_code_space_, current_jump_tables_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, eager_functions_, v8::internal::wasm::NativeModule::JumpTablesRef::is_valid(), IsAligned(), v8::internal::wasm::DeserializationUnit::jump_tables, v8::internal::kCodeAlignment, v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kEagerFunction, v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kLazyFunction, lazy_functions_, v8::internal::MB, native_module_, remaining_code_size_, v8::base::Vector< T >::size(), v8::internal::wasm::DeserializationUnit::src_code_buffer, v8::base::Vector< T >::SubVector(), and v8::internal::v8_flags.
Referenced by Read().
ReadHeader()
void v8::internal::wasm::NativeModuleDeserializer::ReadHeader (Reader * reader) [private]
Definition at line 868 of file wasm-serialization.cc.
                                                        {
  WasmDetectedFeatures detected_features = WasmDetectedFeatures::FromIntegral(
      reader->Read<WasmDetectedFeatures::StorageType>());
  // Ignore the return value of UpdateDetectedFeatures; all features will be
  // published after deserialization anyway.
  USE(native_module_->compilation_state()->UpdateDetectedFeatures(
      detected_features));
  remaining_code_size_ = reader->Read<size_t>();
  all_functions_validated_ = reader->Read<bool>();
  auto compile_imports_flags =
      reader->Read<CompileTimeImportFlags::StorageType>();
  uint32_t constants_module_size = reader->Read<uint32_t>();
  base::Vector<const char> constants_module_data =
      reader->ReadVector<char>(constants_module_size);
  compile_imports_ = CompileTimeImports::FromSerialized(compile_imports_flags,
                                                        constants_module_data);
  uint32_t imported = native_module_->module()->num_imported_functions;
  if (imported > 0) {
    base::Vector<const WellKnownImport> well_known_imports =
        reader->ReadVector<WellKnownImport>(imported);
    native_module_->module()->type_feedback.well_known_imports.Initialize(
        well_known_imports);
  }
}
References all_functions_validated_, v8::internal::wasm::NativeModule::compilation_state(), compile_imports_, v8::base::EnumSet< WasmDetectedFeature >::FromIntegral(), v8::internal::wasm::CompileTimeImports::FromSerialized(), v8::internal::wasm::WellKnownImportsList::Initialize(), v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::wasm::WasmModule::num_imported_functions, remaining_code_size_, v8::internal::wasm::WasmModule::type_feedback, v8::internal::wasm::CompilationState::UpdateDetectedFeatures(), USE, and v8::internal::wasm::TypeFeedbackStorage::well_known_imports.
Referenced by Read().
ReadTieringBudget()
void v8::internal::wasm::NativeModuleDeserializer::ReadTieringBudget (Reader * reader) [private]
Definition at line 1049 of file wasm-serialization.cc.
                                                               {
  size_t size_of_tiering_budget =
      native_module_->module()->num_declared_functions * sizeof(uint32_t);
  if (size_of_tiering_budget > reader->current_size()) {
    return;
  }
  base::Vector<const uint8_t> serialized_budget =
      reader->ReadVector<const uint8_t>(size_of_tiering_budget);
  memcpy(native_module_->tiering_budget_array(), serialized_budget.begin(),
         size_of_tiering_budget);
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::wasm::WasmModule::num_declared_functions, and v8::internal::wasm::NativeModule::tiering_budget_array().
Referenced by Read().
Friends And Related Function Documentation
DeserializeCodeTask
friend class DeserializeCodeTask [friend]
Definition at line 715 of file wasm-serialization.cc.
Member Data Documentation
all_functions_validated_
bool v8::internal::wasm::NativeModuleDeserializer::all_functions_validated_ = false [private]
Definition at line 730 of file wasm-serialization.cc.
Referenced by Read(), and ReadHeader().
compile_imports_
CompileTimeImports v8::internal::wasm::NativeModuleDeserializer::compile_imports_ [private]
Definition at line 731 of file wasm-serialization.cc.
Referenced by Read(), and ReadHeader().
current_code_space_
base::Vector<uint8_t> v8::internal::wasm::NativeModuleDeserializer::current_code_space_ [private]
Definition at line 732 of file wasm-serialization.cc.
Referenced by Read(), and ReadCode().
current_jump_tables_
NativeModule::JumpTablesRef v8::internal::wasm::NativeModuleDeserializer::current_jump_tables_ [private]
Definition at line 733 of file wasm-serialization.cc.
Referenced by ReadCode().
eager_functions_
std::vector<int> v8::internal::wasm::NativeModuleDeserializer::eager_functions_ [private]
Definition at line 735 of file wasm-serialization.cc.
Referenced by ReadCode().
lazy_functions_
std::vector<int> v8::internal::wasm::NativeModuleDeserializer::lazy_functions_ [private]
Definition at line 734 of file wasm-serialization.cc.
Referenced by ReadCode().
native_module_
NativeModule* const v8::internal::wasm::NativeModuleDeserializer::native_module_ [private]
Definition at line 723 of file wasm-serialization.cc.
Referenced by CopyAndRelocate(), Publish(), Read(), ReadCode(), ReadHeader(), and ReadTieringBudget().
remaining_code_size_
size_t v8::internal::wasm::NativeModuleDeserializer::remaining_code_size_ = 0 [private]
Definition at line 729 of file wasm-serialization.cc.
Referenced by Read(), ReadCode(), and ReadHeader().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-serialization.cc