v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency Class Reference
Public Member Functions
InitialMapDependency (JSHeapBroker *broker, JSFunctionRef function, MapRef initial_map)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const JSFunctionRef function_
const MapRef initial_map_
Additional Inherited Members
Detailed Description
Definition at line 199 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
InitialMapDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::InitialMapDependency (JSHeapBroker * broker, JSFunctionRef function, MapRef initial_map) [inline]
Definition at line 201 of file compilation-dependencies.cc.
      : CompilationDependency(kInitialMap),
        function_(function),
        initial_map_(initial_map) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 225 of file compilation-dependencies.cc.
                                                                {
    const InitialMapDependency* const zat = that->AsInitialMap();
    return function_.equals(zat->function_) &&
           initial_map_.equals(zat->initial_map_);
  }
References function_, and initial_map_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 220 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(function_), h(initial_map_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 213 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(initial_map_.object(),
                   DependentCode::kInitialMapChangedGroup);
  }
References broker(), v8::internal::DependentCode::kInitialMapChangedGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 207 of file compilation-dependencies.cc.
                                                    {
    DirectHandle<JSFunction> function = function_.object();
    return function->has_initial_map() &&
           function->initial_map() == *initial_map_.object();
  }
Member Data Documentation
function_
const JSFunctionRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::function_ [private]
Definition at line 231 of file compilation-dependencies.cc.
Referenced by Equals().
initial_map_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::initial_map_ [private]
Definition at line 232 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc