v8::internal::maglev::TaggedIndexConstant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = Register
Public Member Functions
TaggedIndexConstant (uint64_t bitfield, int value)
Tagged< TaggedIndex > value () const
bool ToBoolean (LocalIsolate *local_isolate) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
DirectHandle< Object > DoReify (LocalIsolate *isolate) const
Private Types
using Base = FixedInputValueNodeT< 0, TaggedIndexConstant >
Private Attributes
const Tagged< TaggedIndex > value_
Additional Inherited Members
Detailed Description
Definition at line 5553 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TaggedIndexConstant::Base = FixedInputValueNodeT<0, TaggedIndexConstant> [private]
Definition at line 5555 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::TaggedIndexConstant::OutputRegister = Register
Definition at line 5558 of file maglev-ir.h.
Constructor & Destructor Documentation
TaggedIndexConstant()
v8::internal::maglev::TaggedIndexConstant::TaggedIndexConstant (uint64_t bitfield, int value) [inline], [explicit]
Definition at line 5560 of file maglev-ir.h.
      : Base(bitfield), value_(TaggedIndex::FromIntptr(value)) {
    DCHECK(TaggedIndex::IsValid(value));
  }
References v8::internal::DCHECK(), v8::internal::TaggedIndex::IsValid(), and value().
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::TaggedIndexConstant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
DirectHandle< Object > v8::internal::maglev::TaggedIndexConstant::DoReify (LocalIsolate * isolate) const
Definition at line 1211 of file maglev-ir.cc.
                                                                             {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
GenerateCode()
void v8::internal::maglev::TaggedIndexConstant::GenerateCode (MaglevAssembler * , const ProcessingState &)
PrintParams()
void v8::internal::maglev::TaggedIndexConstant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7889 of file maglev-ir.cc.
                                                               {
  os << "(" << value() << ")";
}
References value().
SetValueLocationConstraints()
void v8::internal::maglev::TaggedIndexConstant::SetValueLocationConstraints ()
ToBoolean()
bool v8::internal::maglev::TaggedIndexConstant::ToBoolean (LocalIsolate * local_isolate) const [inline]
Definition at line 5567 of file maglev-ir.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
value()
Tagged<TaggedIndex> v8::internal::maglev::TaggedIndexConstant::value () const [inline]
Definition at line 5565 of file maglev-ir.h.
{ return value_; }
References value_.
Referenced by PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and TaggedIndexConstant().
Member Data Documentation
value_
const Tagged<TaggedIndex> v8::internal::maglev::TaggedIndexConstant::value_ [private]
Definition at line 5577 of file maglev-ir.h.
Referenced by value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc