v8::internal::compiler::BitcastElider Class Reference
#include <bitcast-elider.h>
Public Member Functions
BitcastElider (Zone *zone, TFGraph *graph, bool is_builtin)
~BitcastElider ()=default
void Reduce ()
void Enqueue (Node *node)
void Revisit (Node *node)
void VisitNode (Node *node)
void ProcessGraph ()
Private Attributes
TFGraph *const graph_
ZoneQueue< Node * > to_visit_
NodeMarker< bool > seen_
bool is_builtin_
Detailed Description
Definition at line 21 of file bitcast-elider.h.
Constructor & Destructor Documentation
BitcastElider()
v8::internal::compiler::BitcastElider::BitcastElider (Zone * zone, TFGraph * graph, bool is_builtin)
Definition at line 91 of file bitcast-elider.cc.
    : graph_(graph),
      to_visit_(zone),
      seen_(graph, 2),
      is_builtin_(is_builtin) {}
 BitcastElider()
v8::internal::compiler::BitcastElider::~BitcastElider () [default]
Member Function Documentation
Enqueue()
void v8::internal::compiler::BitcastElider::Enqueue (Node * node)
Definition at line 56 of file bitcast-elider.cc.
                                      {
  if (seen_.Get(node)) return;
  seen_.Set(node, true);
  to_visit_.push(node);
}
References v8::internal::compiler::NodeMarker< State >::Get(), seen_, v8::internal::compiler::NodeMarker< State >::Set(), and to_visit_.
Referenced by ProcessGraph(), and VisitNode().
ProcessGraph()
void v8::internal::compiler::BitcastElider::ProcessGraph ()
Definition at line 82 of file bitcast-elider.cc.
                                 {
  Enqueue(graph_->end());
  while (!to_visit_.empty()) {
    Node* node = to_visit_.front();
    to_visit_.pop();
    VisitNode(node);
  }
}
References v8::internal::compiler::TFGraph::end(), Enqueue(), graph_, to_visit_, and VisitNode().
Referenced by Reduce().
Reduce()
void v8::internal::compiler::BitcastElider::Reduce ()
Definition at line 97 of file bitcast-elider.cc.
{ ProcessGraph(); }
References ProcessGraph().
Revisit()
void v8::internal::compiler::BitcastElider::Revisit (Node * node)
Definition at line 62 of file bitcast-elider.cc.
{ to_visit_.push(node); }
References to_visit_.
Referenced by VisitNode().
VisitNode()
void v8::internal::compiler::BitcastElider::VisitNode (Node * node)
Definition at line 64 of file bitcast-elider.cc.
                                        {
  for (int i = 0; i < node->InputCount(); i++) {
    Node* input = node->InputAt(i);
    // This can happen as a result of previous replacements.
    if (input == nullptr) continue;
    if (input->opcode() == IrOpcode::kTruncateInt64ToInt32 &&
        OwnedByWord32Op(input)) {
      Replace(input, input->InputAt(0));
      Revisit(node);
    } else if (is_builtin_ && IsBitcast(input)) {
      Replace(input, input->InputAt(0));
      Revisit(node);
    } else {
      Enqueue(input);
    }
  }
}
References Enqueue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), is_builtin_, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::IsBitcast(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::OwnedByWord32Op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and Revisit().
Referenced by ProcessGraph().
Member Data Documentation
graph_
TFGraph* const v8::internal::compiler::BitcastElider::graph_ [private]
Definition at line 34 of file bitcast-elider.h.
Referenced by ProcessGraph().
is_builtin_
bool v8::internal::compiler::BitcastElider::is_builtin_ [private]
Definition at line 37 of file bitcast-elider.h.
Referenced by VisitNode().
seen_
NodeMarker<bool> v8::internal::compiler::BitcastElider::seen_ [private]
Definition at line 36 of file bitcast-elider.h.
Referenced by Enqueue().
to_visit_
ZoneQueue<Node*> v8::internal::compiler::BitcastElider::to_visit_ [private]
Definition at line 35 of file bitcast-elider.h.
Referenced by Enqueue(), ProcessGraph(), and Revisit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/bitcast-elider.h
/mnt/V8SourceCode/src/compiler/backend/bitcast-elider.cc