v8::internal::FeedbackNexus Class Reference
#include <feedback-vector.h>
Public Types
using TryUpdateHandler = std::function< MaybeHandle< Map >(Handle< Map >)>
using SpeculationModeField = base::BitField< SpeculationMode, 0, 2 >
using CallFeedbackContentField = base::BitField< CallFeedbackContent, 2, 1 >
using CallCountField = base::BitField< uint32_t, 3, 29 >
Public Member Functions
FeedbackNexus (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot)
FeedbackNexus (Isolate *, Tagged< FeedbackVector > vector, FeedbackSlot slot)
FeedbackNexus (Handle< FeedbackVector > vector, FeedbackSlot slot, const NexusConfig &config)
const NexusConfig * config () const
DirectHandle< FeedbackVector > vector_handle () const
Tagged< FeedbackVector > vector () const
FeedbackSlot slot () const
FeedbackSlotKind kind () const
LanguageMode GetLanguageMode () const
InlineCacheState ic_state () const
bool IsUninitialized () const
bool IsMegamorphic () const
bool IsGeneric () const
void Print (std::ostream &os)
Tagged< Map > GetFirstMap () const
int ExtractMaps (MapHandles *maps) const
int ExtractMapsAndHandlers (MapsAndHandlers *maps_and_handlers, TryUpdateHandler map_handler=TryUpdateHandler()) const
MaybeObjectDirectHandle FindHandlerForMap (DirectHandle< Map > map) const
template<typename F >
void IterateMapsWithUnclearedHandler (F) const
bool IsCleared () const
bool Clear (ClearBehavior behavior)
void ConfigureUninitialized ()
bool ConfigureMegamorphic ()
bool ConfigureMegamorphic (IcCheckType property_type)
Tagged< MaybeObject > GetFeedback () const
Tagged< MaybeObject > GetFeedbackExtra () const
std::pair< Tagged< MaybeObject >, Tagged< MaybeObject > > GetFeedbackPair () const
void ConfigureMonomorphic (DirectHandle< Name > name, DirectHandle< Map > receiver_map, const MaybeObjectDirectHandle &handler)
void ConfigurePolymorphic (DirectHandle< Name > name, MapsAndHandlers const &maps_and_handlers)
void ConfigureMegaDOM (const MaybeObjectDirectHandle &handler)
MaybeObjectHandle ExtractMegaDOMHandler ()
BinaryOperationHint GetBinaryOperationFeedback () const
CompareOperationHint GetCompareOperationFeedback () const
TypeOfFeedback::Result GetTypeOfFeedback () const
ForInHint GetForInFeedback () const
KeyedAccessLoadMode GetKeyedAccessLoadMode () const
KeyedAccessStoreMode GetKeyedAccessStoreMode () const
IcCheckType GetKeyType () const
Tagged< Name > GetName () const
bool IsOneMapManyNames () const
int GetCallCount ()
void SetSpeculationMode (SpeculationMode mode)
void NextSpeculationMode (SpeculationMode mode)
SpeculationMode GetSpeculationMode ()
CallFeedbackContent GetCallFeedbackContent ()
float ComputeCallFrequency ()
MaybeDirectHandle< JSObject > GetConstructorFeedback () const
void ConfigurePropertyCellMode (DirectHandle< PropertyCell > cell)
bool ConfigureLexicalVarMode (int script_context_index, int context_slot_index, bool immutable)
void ConfigureHandlerMode (const MaybeObjectDirectHandle &handler)
void ConfigureCloneObject (DirectHandle< Map > source_map, const MaybeObjectHandle &handler)
Static Public Attributes
static constexpr int kCloneObjectPolymorphicEntrySize = 2
Private Member Functions
template<typename FeedbackType >
void SetFeedback (Tagged< FeedbackType > feedback, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
template<typename FeedbackType , typename FeedbackExtraType >
void SetFeedback (Tagged< FeedbackType > feedback, WriteBarrierMode mode, Tagged< FeedbackExtraType > feedback_extra, WriteBarrierMode mode_extra=UPDATE_WRITE_BARRIER)
Tagged< MaybeObject > UninitializedSentinel () const
Tagged< MaybeObject > MegamorphicSentinel () const
Tagged< MaybeObject > MegaDOMSentinel () const
DirectHandle< WeakFixedArray > CreateArrayOfSize (int length)
Tagged< MaybeObject > FromHandle (MaybeObjectDirectHandle slot) const
MaybeObjectHandle ToHandle (Tagged< MaybeObject > value) const
Private Attributes
Handle< FeedbackVector > vector_handle_
Tagged< FeedbackVector > vector_
FeedbackSlot slot_
FeedbackSlotKind kind_
std::optional< std::pair< MaybeObjectHandle, MaybeObjectHandle > > feedback_cache_
NexusConfig config_
Isolate * isolate_
Detailed Description
Definition at line 932 of file feedback-vector.h.
Member Typedef Documentation
CallCountField
using v8::internal::FeedbackNexus::CallCountField = base::BitField<uint32_t, 3, 29>
Definition at line 1044 of file feedback-vector.h.
CallFeedbackContentField
using v8::internal::FeedbackNexus::CallFeedbackContentField = base::BitField<CallFeedbackContent, 2, 1>
Definition at line 1043 of file feedback-vector.h.
SpeculationModeField
using v8::internal::FeedbackNexus::SpeculationModeField = base::BitField<SpeculationMode, 0, 2>
Definition at line 1042 of file feedback-vector.h.
TryUpdateHandler
using v8::internal::FeedbackNexus::TryUpdateHandler = std::function<MaybeHandle<Map>(Handle<Map>)>
Definition at line 977 of file feedback-vector.h.
Constructor & Destructor Documentation
FeedbackNexus() [1/3]
v8::internal::FeedbackNexus::FeedbackNexus (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot)
Definition at line 585 of file feedback-vector.cc.
    : vector_handle_(vector),
      slot_(slot),
      config_(NexusConfig::FromMainThread(isolate)) {
  kind_ = vector.is_null() ? FeedbackSlotKind::kInvalid : vector->GetKind(slot);
}
References kind_, v8::internal::kInvalid, slot(), and vector().
FeedbackNexus() [2/3]
v8::internal::FeedbackNexus::FeedbackNexus (Isolate * isolate, Tagged< FeedbackVector > vector, FeedbackSlot slot)
Definition at line 593 of file feedback-vector.cc.
    : vector_(vector),
      slot_(slot),
      config_(NexusConfig::FromMainThread(isolate)) {
  kind_ = vector.is_null() ? FeedbackSlotKind::kInvalid : vector->GetKind(slot);
}
References kind_, v8::internal::kInvalid, slot(), and vector().
FeedbackNexus() [3/3]
v8::internal::FeedbackNexus::FeedbackNexus (Handle< FeedbackVector > vector, FeedbackSlot slot, const NexusConfig & config)
Definition at line 601 of file feedback-vector.cc.
    : vector_handle_(vector),
      slot_(slot),
      kind_(vector->GetKind(slot, kAcquireLoad)),
      config_(config) {}
Member Function Documentation
Clear()
bool v8::internal::FeedbackNexus::Clear (ClearBehavior behavior)
Definition at line 655 of file feedback-vector.cc.
                                                {
  bool feedback_updated = false;
  switch (kind()) {
    case FeedbackSlotKind::kCompareOp:
    case FeedbackSlotKind::kForIn:
    case FeedbackSlotKind::kBinaryOp:
    case FeedbackSlotKind::kTypeOf:
      if (V8_LIKELY(behavior == ClearBehavior::kDefault)) {
        // We don't clear these, either.
      } else if (!IsCleared()) {
        DCHECK_EQ(behavior, ClearBehavior::kClearAll);
        SetFeedback(Smi::zero(), SKIP_WRITE_BARRIER);
        feedback_updated = true;
      }
      break;
    case FeedbackSlotKind::kLiteral:
      if (!IsCleared()) {
        SetFeedback(Smi::zero(), SKIP_WRITE_BARRIER);
        feedback_updated = true;
      }
      break;
    case FeedbackSlotKind::kSetNamedSloppy:
    case FeedbackSlotKind::kSetNamedStrict:
    case FeedbackSlotKind::kSetKeyedSloppy:
    case FeedbackSlotKind::kSetKeyedStrict:
    case FeedbackSlotKind::kStoreInArrayLiteral:
    case FeedbackSlotKind::kDefineNamedOwn:
    case FeedbackSlotKind::kDefineKeyedOwn:
    case FeedbackSlotKind::kLoadProperty:
    case FeedbackSlotKind::kLoadKeyed:
    case FeedbackSlotKind::kHasKeyed:
    case FeedbackSlotKind::kStoreGlobalSloppy:
    case FeedbackSlotKind::kStoreGlobalStrict:
    case FeedbackSlotKind::kLoadGlobalNotInsideTypeof:
    case FeedbackSlotKind::kLoadGlobalInsideTypeof:
    case FeedbackSlotKind::kCall:
    case FeedbackSlotKind::kInstanceOf:
    case FeedbackSlotKind::kDefineKeyedOwnPropertyInLiteral:
    case FeedbackSlotKind::kCloneObject:
    case FeedbackSlotKind::kJumpLoop:
      if (!IsCleared()) {
        ConfigureUninitialized();
        feedback_updated = true;
      }
      break;
    case FeedbackSlotKind::kStringAddAndInternalize:
      if (V8_LIKELY(behavior == ClearBehavior::kDefault)) {
        // We don't clear these, either.
      } else if (!IsCleared()) {
        DCHECK_EQ(behavior, ClearBehavior::kClearAll);
        SetFeedback(Smi::zero(), SKIP_WRITE_BARRIER, UninitializedSentinel(),
                    SKIP_WRITE_BARRIER);
        feedback_updated = true;
      }
      break;
    case FeedbackSlotKind::kInvalid:
      UNREACHABLE();
  }
  return feedback_updated;
}
References ConfigureUninitialized(), DCHECK_EQ, IsCleared(), v8::internal::kBinaryOp, v8::internal::kCall, v8::internal::kClearAll, v8::internal::kCloneObject, v8::internal::kCompareOp, v8::internal::kDefault, v8::internal::kDefineKeyedOwn, v8::internal::kDefineKeyedOwnPropertyInLiteral, v8::internal::kDefineNamedOwn, v8::internal::kForIn, v8::internal::kHasKeyed, kind(), v8::internal::kInstanceOf, v8::internal::kInvalid, v8::internal::kJumpLoop, v8::internal::kLiteral, v8::internal::kLoadGlobalInsideTypeof, v8::internal::kLoadGlobalNotInsideTypeof, v8::internal::kLoadKeyed, v8::internal::kLoadProperty, v8::internal::kSetKeyedSloppy, v8::internal::kSetKeyedStrict, v8::internal::kSetNamedSloppy, v8::internal::kSetNamedStrict, v8::internal::kStoreGlobalSloppy, v8::internal::kStoreGlobalStrict, v8::internal::kStoreInArrayLiteral, v8::internal::kStringAddAndInternalize, v8::internal::kTypeOf, SetFeedback(), v8::internal::SKIP_WRITE_BARRIER, UninitializedSentinel(), v8::internal::UNREACHABLE(), V8_LIKELY, and v8::internal::Smi::zero().
Referenced by v8::internal::FeedbackVector::ClearSlots().
ComputeCallFrequency()
float v8::internal::FeedbackNexus::ComputeCallFrequency ()
Definition at line 1128 of file feedback-vector.cc.
                                          {
  DCHECK(IsCallICKind(kind()));
  double const invocation_count = vector()->invocation_count(kRelaxedLoad);
  double const call_count = GetCallCount();
  if (invocation_count == 0.0) { // Prevent division by 0.
    return 0.0f;
  }
  return static_cast<float>(call_count / invocation_count);
}
References v8::internal::DCHECK(), GetCallCount(), v8::internal::IsCallICKind(), kind(), v8::kRelaxedLoad, and vector().
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall().
config()
const NexusConfig* v8::internal::FeedbackNexus::config () const [inline]
Definition at line 944 of file feedback-vector.h.
{ return &config_; }
Referenced by ConfigureCloneObject(), ConfigureHandlerMode(), ConfigureLexicalVarMode(), ConfigureMegamorphic(), ConfigureUninitialized(), CreateArrayOfSize(), ExtractMaps(), ExtractMapsAndHandlers(), ExtractMegaDOMHandler(), v8::internal::FeedbackIterator::FeedbackIterator(), FindHandlerForMap(), FromHandle(), GetConstructorFeedback(), GetFeedbackPair(), IterateMapsWithUnclearedHandler(), MegaDOMSentinel(), MegamorphicSentinel(), SetFeedback(), ToHandle(), and UninitializedSentinel().
ConfigureCloneObject()
void v8::internal::FeedbackNexus::ConfigureCloneObject (DirectHandle< Map > source_map, const MaybeObjectHandle & handler)
Definition at line 991 of file feedback-vector.cc.
                                                                           {
  // TODO(olivf): Introduce a CloneHandler to deal with all the logic of this
  // state machine which is now spread between Runtime_CloneObjectIC_Miss and
  // this method.
  auto GetHandler = [=]() {
    if (IsSmi(*handler_handle)) {
      return *handler_handle;
    }
    return MakeWeak(*handler_handle);
  };
  DCHECK(config()->can_write());
  Isolate* isolate = config()->isolate();
  DirectHandle<HeapObject> feedback;
  {
    Tagged<MaybeObject> maybe_feedback = GetFeedback();
    if (maybe_feedback.IsStrongOrWeak()) {
      feedback = direct_handle(maybe_feedback.GetHeapObject(), isolate);
    } else {
      DCHECK(maybe_feedback.IsCleared());
    }
  }
  switch (ic_state()) {
    case InlineCacheState::UNINITIALIZED:
      // Cache the first map seen which meets the fast case requirements.
      SetFeedback(MakeWeak(*source_map), UPDATE_WRITE_BARRIER, GetHandler());
      break;
    case InlineCacheState::MONOMORPHIC:
      if (feedback.is_null() || feedback.is_identical_to(source_map) ||
          Cast<Map>(*feedback)->is_deprecated()) {
        SetFeedback(MakeWeak(*source_map), UPDATE_WRITE_BARRIER, GetHandler());
      } else {
        // Transition to POLYMORPHIC.
        DirectHandle<WeakFixedArray> array =
            CreateArrayOfSize(2 * kCloneObjectPolymorphicEntrySize);
        DisallowGarbageCollection no_gc;
        Tagged<WeakFixedArray> raw_array = *array;
        raw_array->set(0, MakeWeak(*feedback));
        raw_array->set(1, GetFeedbackExtra());
        raw_array->set(2, MakeWeak(*source_map));
        raw_array->set(3, GetHandler());
        SetFeedback(raw_array, UPDATE_WRITE_BARRIER, ClearedValue(isolate));
      }
      break;
    case InlineCacheState::POLYMORPHIC: {
      const int kMaxElements = v8_flags.max_valid_polymorphic_map_count *
                               kCloneObjectPolymorphicEntrySize;
      DirectHandle<WeakFixedArray> array = Cast<WeakFixedArray>(feedback);
      int i = 0;
      for (; i < array->length(); i += kCloneObjectPolymorphicEntrySize) {
        Tagged<MaybeObject> feedback_map = array->get(i);
        if (feedback_map.IsCleared()) break;
        DirectHandle<Map> cached_map(Cast<Map>(feedback_map.GetHeapObject()),
                                     isolate);
        if (cached_map.is_identical_to(source_map) ||
            cached_map->is_deprecated())
          break;
      }
      if (i >= array->length()) {
        if (i == kMaxElements) {
          // Transition to MEGAMORPHIC.
          Tagged<MaybeObject> sentinel = MegamorphicSentinel();
          SetFeedback(sentinel, SKIP_WRITE_BARRIER, ClearedValue(isolate));
          break;
        }
        // Grow polymorphic feedback array.
        DirectHandle<WeakFixedArray> new_array = CreateArrayOfSize(
            array->length() + kCloneObjectPolymorphicEntrySize);
        for (int j = 0; j < array->length(); ++j) {
          new_array->set(j, array->get(j));
        }
        SetFeedback(*new_array);
        array = new_array;
      }
      array->set(i, MakeWeak(*source_map));
      array->set(i + 1, GetHandler());
      break;
    }
    default:
      UNREACHABLE();
  }
}
References v8::internal::ClearedValue(), config(), CreateArrayOfSize(), v8::internal::DCHECK(), v8::internal::direct_handle(), GetFeedback(), GetFeedbackExtra(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), ic_state(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::DirectHandle< T >::is_null(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::NexusConfig::isolate(), v8::internal::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrongOrWeak(), kCloneObjectPolymorphicEntrySize, v8::internal::MakeWeak(), MegamorphicSentinel(), v8::internal::MONOMORPHIC, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::POLYMORPHIC, SetFeedback(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::UNINITIALIZED, v8::internal::UNREACHABLE(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::v8_flags.
ConfigureHandlerMode()
void v8::internal::FeedbackNexus::ConfigureHandlerMode (const MaybeObjectDirectHandle & handler)
Definition at line 983 of file feedback-vector.cc.
                                            {
  DCHECK(IsGlobalICKind(kind()));
  DCHECK(IC::IsHandler(*handler));
  SetFeedback(ClearedValue(config()->isolate()), UPDATE_WRITE_BARRIER, *handler,
              UPDATE_WRITE_BARRIER);
}
References v8::internal::ClearedValue(), config(), v8::internal::DCHECK(), v8::internal::IsGlobalICKind(), v8::internal::IC::IsHandler(), kind(), SetFeedback(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::IC::ConfigureVectorState().
ConfigureLexicalVarMode()
bool v8::internal::FeedbackNexus::ConfigureLexicalVarMode (int script_context_index, int context_slot_index, bool immutable)
Definition at line 957 of file feedback-vector.cc.
                                                            {
  DCHECK(IsGlobalICKind(kind()));
  DCHECK_LE(0, script_context_index);
  DCHECK_LE(0, context_slot_index);
#if DEBUG
  if (v8_flags.stress_ic &&
      shouldStressLexicalIC(script_context_index, context_slot_index)) {
    return false;
  }
#endif
  if (!ContextIndexBits::is_valid(script_context_index) ||
      !SlotIndexBits::is_valid(context_slot_index) ||
      !ImmutabilityBit::is_valid(immutable)) {
    return false;
  }
  int config = ContextIndexBits::encode(script_context_index) |
               SlotIndexBits::encode(context_slot_index) |
               ImmutabilityBit::encode(immutable);
  SetFeedback(Smi::From31BitPattern(config), SKIP_WRITE_BARRIER,
              UninitializedSentinel(), SKIP_WRITE_BARRIER);
  return true;
}
References config(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::Smi::From31BitPattern(), v8::internal::IsGlobalICKind(), kind(), SetFeedback(), v8::internal::SKIP_WRITE_BARRIER, UninitializedSentinel(), and v8::internal::v8_flags.
Referenced by v8::internal::LoadGlobalIC::Load(), and v8::internal::StoreGlobalIC::Store().
ConfigureMegaDOM()
void v8::internal::FeedbackNexus::ConfigureMegaDOM (const MaybeObjectDirectHandle & handler)
Definition at line 733 of file feedback-vector.cc.
                                                                           {
  DisallowGarbageCollection no_gc;
  Tagged<MaybeObject> sentinel = MegaDOMSentinel();
  SetFeedback(sentinel, SKIP_WRITE_BARRIER, *handler, UPDATE_WRITE_BARRIER);
}
References MegaDOMSentinel(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SetFeedback(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::IC::UpdateMegaDOMIC().
ConfigureMegamorphic() [1/2]
bool v8::internal::FeedbackNexus::ConfigureMegamorphic ()
Definition at line 721 of file feedback-vector.cc.
                                         {
  DisallowGarbageCollection no_gc;
  Isolate* isolate = config()->isolate();
  Tagged<MaybeObject> sentinel = MegamorphicSentinel();
  if (GetFeedback() != sentinel) {
    SetFeedback(sentinel, SKIP_WRITE_BARRIER, ClearedValue(isolate));
    return true;
  }
  return false;
}
References v8::internal::ClearedValue(), config(), GetFeedback(), v8::internal::NexusConfig::isolate(), MegamorphicSentinel(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SetFeedback(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::IC::ConfigureVectorState(), and v8::internal::RUNTIME_FUNCTION().
ConfigureMegamorphic() [2/2]
bool v8::internal::FeedbackNexus::ConfigureMegamorphic (IcCheckType property_type)
Definition at line 740 of file feedback-vector.cc.
                                                                  {
  DisallowGarbageCollection no_gc;
  Tagged<MaybeObject> sentinel = MegamorphicSentinel();
  Tagged<MaybeObject> maybe_extra =
      Smi::FromInt(static_cast<int>(property_type));
  auto feedback = GetFeedbackPair();
  bool update_required =
      feedback.first != sentinel || feedback.second != maybe_extra;
  if (update_required) {
    SetFeedback(sentinel, SKIP_WRITE_BARRIER, maybe_extra, SKIP_WRITE_BARRIER);
  }
  return update_required;
}
References v8::internal::Smi::FromInt(), GetFeedbackPair(), MegamorphicSentinel(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SetFeedback(), and v8::internal::SKIP_WRITE_BARRIER.
ConfigureMonomorphic()
void v8::internal::FeedbackNexus::ConfigureMonomorphic (DirectHandle< Name > name, DirectHandle< Map > receiver_map, const MaybeObjectDirectHandle & handler)
Definition at line 1139 of file feedback-vector.cc.
                                            {
  DCHECK(handler.is_null() || IC::IsHandler(*handler));
  if (kind() == FeedbackSlotKind::kDefineKeyedOwnPropertyInLiteral) {
    SetFeedback(MakeWeak(*receiver_map), UPDATE_WRITE_BARRIER, *name);
  } else {
    if (name.is_null()) {
      SetFeedback(MakeWeak(*receiver_map), UPDATE_WRITE_BARRIER, *handler);
    } else {
      DirectHandle<WeakFixedArray> array = CreateArrayOfSize(2);
      array->set(0, MakeWeak(*receiver_map));
      array->set(1, *handler);
      SetFeedback(*name, UPDATE_WRITE_BARRIER, *array);
    }
  }
}
References CreateArrayOfSize(), v8::internal::DCHECK(), v8::internal::MaybeObjectDirectHandle::is_null(), v8::internal::IC::IsHandler(), v8::internal::kDefineKeyedOwnPropertyInLiteral, kind(), v8::internal::MakeWeak(), v8::internal::name, SetFeedback(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::IC::ConfigureVectorState(), and v8::internal::RUNTIME_FUNCTION().
ConfigurePolymorphic()
void v8::internal::FeedbackNexus::ConfigurePolymorphic (DirectHandle< Name > name, MapsAndHandlers const & maps_and_handlers)
Definition at line 1157 of file feedback-vector.cc.
                                                                       {
  int receiver_count = static_cast<int>(maps_and_handlers.size());
  DCHECK_GT(receiver_count, 1);
  DirectHandle<WeakFixedArray> array = CreateArrayOfSize(receiver_count * 2);
  for (int current = 0; current < receiver_count; ++current) {
    auto [map, handler] = maps_and_handlers[current];
    array->set(current * 2, MakeWeak(*map));
    DCHECK(IC::IsHandler(*handler));
    array->set(current * 2 + 1, *handler);
  }
  if (name.is_null()) {
    SetFeedback(*array, UPDATE_WRITE_BARRIER, UninitializedSentinel(),
                SKIP_WRITE_BARRIER);
  } else {
    SetFeedback(*name, UPDATE_WRITE_BARRIER, *array);
  }
}
References CreateArrayOfSize(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::IC::IsHandler(), v8::internal::MakeWeak(), v8::internal::name, SetFeedback(), v8::internal::MapsAndHandlers::size(), v8::internal::SKIP_WRITE_BARRIER, UninitializedSentinel(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::IC::ConfigureVectorState().
ConfigurePropertyCellMode()
void v8::internal::FeedbackNexus::ConfigurePropertyCellMode (DirectHandle< PropertyCell > cell)
Definition at line 943 of file feedback-vector.cc.
                                                                             {
  DCHECK(IsGlobalICKind(kind()));
  SetFeedback(MakeWeak(*cell), UPDATE_WRITE_BARRIER, UninitializedSentinel(),
              SKIP_WRITE_BARRIER);
}
References v8::internal::DCHECK(), v8::internal::IsGlobalICKind(), kind(), v8::internal::MakeWeak(), SetFeedback(), v8::internal::SKIP_WRITE_BARRIER, UninitializedSentinel(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::LoadIC::UpdateCaches(), and v8::internal::StoreIC::UpdateCaches().
ConfigureUninitialized()
void v8::internal::FeedbackNexus::ConfigureUninitialized ()
Definition at line 615 of file feedback-vector.cc.
                                           {
  Isolate* isolate = config()->isolate();
  switch (kind()) {
    case FeedbackSlotKind::kStoreGlobalSloppy:
    case FeedbackSlotKind::kStoreGlobalStrict:
    case FeedbackSlotKind::kLoadGlobalNotInsideTypeof:
    case FeedbackSlotKind::kLoadGlobalInsideTypeof:
      SetFeedback(ClearedValue(isolate), SKIP_WRITE_BARRIER,
                  UninitializedSentinel(), SKIP_WRITE_BARRIER);
      break;
    case FeedbackSlotKind::kCloneObject:
    case FeedbackSlotKind::kCall:
      SetFeedback(UninitializedSentinel(), SKIP_WRITE_BARRIER, Smi::zero(),
                  SKIP_WRITE_BARRIER);
      break;
    case FeedbackSlotKind::kInstanceOf:
      SetFeedback(UninitializedSentinel(), SKIP_WRITE_BARRIER);
      break;
    case FeedbackSlotKind::kSetNamedSloppy:
    case FeedbackSlotKind::kSetNamedStrict:
    case FeedbackSlotKind::kSetKeyedSloppy:
    case FeedbackSlotKind::kSetKeyedStrict:
    case FeedbackSlotKind::kStoreInArrayLiteral:
    case FeedbackSlotKind::kDefineNamedOwn:
    case FeedbackSlotKind::kDefineKeyedOwn:
    case FeedbackSlotKind::kLoadProperty:
    case FeedbackSlotKind::kLoadKeyed:
    case FeedbackSlotKind::kHasKeyed:
    case FeedbackSlotKind::kDefineKeyedOwnPropertyInLiteral:
      SetFeedback(UninitializedSentinel(), SKIP_WRITE_BARRIER,
                  UninitializedSentinel(), SKIP_WRITE_BARRIER);
      break;
    case FeedbackSlotKind::kJumpLoop:
      SetFeedback(ClearedValue(isolate), SKIP_WRITE_BARRIER);
      break;
    default:
      UNREACHABLE();
  }
}
References v8::internal::ClearedValue(), config(), v8::internal::NexusConfig::isolate(), v8::internal::kCall, v8::internal::kCloneObject, v8::internal::kDefineKeyedOwn, v8::internal::kDefineKeyedOwnPropertyInLiteral, v8::internal::kDefineNamedOwn, v8::internal::kHasKeyed, kind(), v8::internal::kInstanceOf, v8::internal::kJumpLoop, v8::internal::kLoadGlobalInsideTypeof, v8::internal::kLoadGlobalNotInsideTypeof, v8::internal::kLoadKeyed, v8::internal::kLoadProperty, v8::internal::kSetKeyedSloppy, v8::internal::kSetKeyedStrict, v8::internal::kSetNamedSloppy, v8::internal::kSetNamedStrict, v8::internal::kStoreGlobalSloppy, v8::internal::kStoreGlobalStrict, v8::internal::kStoreInArrayLiteral, SetFeedback(), v8::internal::SKIP_WRITE_BARRIER, UninitializedSentinel(), v8::internal::UNREACHABLE(), and v8::internal::Smi::zero().
Referenced by Clear().
CreateArrayOfSize()
DirectHandle< WeakFixedArray > v8::internal::FeedbackNexus::CreateArrayOfSize (int length) [private]
Definition at line 608 of file feedback-vector.cc.
                                                                        {
  DCHECK(config()->can_write());
  DirectHandle<WeakFixedArray> array =
      config()->isolate()->factory()->NewWeakFixedArray(length);
  return array;
}
References config(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::NexusConfig::isolate(), v8::internal::length, and v8::internal::FactoryBase< Impl >::NewWeakFixedArray().
Referenced by ConfigureCloneObject(), ConfigureMonomorphic(), and ConfigurePolymorphic().
ExtractMaps()
int v8::internal::FeedbackNexus::ExtractMaps (MapHandles * maps) const
Definition at line 1178 of file feedback-vector.cc.
                                                     {
  DisallowGarbageCollection no_gc;
  int found = 0;
  for (FeedbackIterator it(this); !it.done(); it.Advance()) {
    maps->push_back(config()->NewHandle(it.map()));
    found++;
  }
  return found;
}
References config(), v8::internal::FeedbackIterator::done(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::DirectHandleSmallVector< T, kSize >::push_back().
Referenced by v8::internal::IC::FindTargetMaps().
ExtractMapsAndHandlers()
int v8::internal::FeedbackNexus::ExtractMapsAndHandlers (MapsAndHandlers * maps_and_handlers, TryUpdateHandler map_handler = TryUpdateHandler()) const
Definition at line 1203 of file feedback-vector.cc.
                                                                              {
  DCHECK(!IsDefineKeyedOwnPropertyInLiteralKind(kind()));
  DisallowGarbageCollection no_gc;
  int found = 0;
  for (FeedbackIterator it(this); !it.done(); it.Advance()) {
    Handle<Map> map = config()->NewHandle(it.map());
    Tagged<MaybeObject> maybe_handler = it.handler();
    if (!maybe_handler.IsCleared()) {
      DCHECK(IC::IsHandler(maybe_handler));
      MaybeObjectHandle handler = config()->NewHandle(maybe_handler);
      if (map_handler && !(map_handler(map).ToHandle(&map))) {
        continue;
      }
      maps_and_handlers->emplace_back(map, handler);
      found++;
    }
  }
  return found;
}
References config(), v8::internal::DCHECK(), v8::internal::FeedbackIterator::done(), v8::internal::MapsAndHandlers::emplace_back(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::IsDefineKeyedOwnPropertyInLiteralKind(), v8::internal::IC::IsHandler(), kind(), v8::internal::NexusConfig::NewHandle(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and ToHandle().
Referenced by v8::internal::IC::CopyICToMegamorphicCache(), GetKeyedAccessLoadMode(), GetKeyedAccessStoreMode(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
ExtractMegaDOMHandler()
MaybeObjectHandle v8::internal::FeedbackNexus::ExtractMegaDOMHandler ()
Definition at line 1189 of file feedback-vector.cc.
                                                       {
  DCHECK(ic_state() == InlineCacheState::MEGADOM);
  DisallowGarbageCollection no_gc;
  auto pair = GetFeedbackPair();
  Tagged<MaybeObject> maybe_handler = pair.second;
  if (!maybe_handler.IsCleared()) {
    MaybeObjectHandle handler = config()->NewHandle(maybe_handler);
    return handler;
  }
  return MaybeObjectHandle();
}
References config(), v8::internal::DCHECK(), GetFeedbackPair(), ic_state(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::MEGADOM, v8::internal::NexusConfig::NewHandle(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess().
FindHandlerForMap()
MaybeObjectDirectHandle v8::internal::FeedbackNexus::FindHandlerForMap (DirectHandle< Map > map) const
Definition at line 1226 of file feedback-vector.cc.
                                 {
  DCHECK(!IsStoreInArrayLiteralICKind(kind()));
  for (FeedbackIterator it(this); !it.done(); it.Advance()) {
    if (it.map() == *map && !it.handler().IsCleared()) {
      return config()->NewHandle(it.handler());
    }
  }
  return MaybeObjectDirectHandle();
}
References config(), v8::internal::DCHECK(), v8::internal::FeedbackIterator::done(), v8::internal::IsStoreInArrayLiteralICKind(), kind(), and v8::internal::NexusConfig::NewHandle().
Referenced by v8::internal::KeyedLoadIC::GetKeyedAccessLoadModeFor(), and v8::internal::IC::ShouldRecomputeHandler().
FromHandle()
Tagged< MaybeObject > v8::internal::FeedbackNexus::FromHandle (MaybeObjectDirectHandle slot) const [inline], [private]
Definition at line 557 of file feedback-vector-inl.h.
                                        {
  return slot.is_null() ? ClearedValue(config()->isolate()) : *slot;
}
References v8::internal::ClearedValue(), config(), and slot().
Referenced by GetFeedbackPair().
GetBinaryOperationFeedback()
BinaryOperationHint v8::internal::FeedbackNexus::GetBinaryOperationFeedback () const
Definition at line 1420 of file feedback-vector.cc.
                                                                    {
  DCHECK(kind() == FeedbackSlotKind::kBinaryOp ||
         kind() == FeedbackSlotKind::kStringAddAndInternalize);
  int feedback = GetFeedback().ToSmi().value();
  return BinaryOperationHintFromFeedback(feedback);
}
References v8::internal::BinaryOperationHintFromFeedback(), v8::internal::DCHECK(), GetFeedback(), v8::internal::kBinaryOp, kind(), and v8::internal::kStringAddAndInternalize.
Referenced by ic_state(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForBinaryOperation(), v8::internal::maglev::MaglevGraphBuilder::VisitBinaryOperation(), v8::internal::maglev::MaglevGraphBuilder::VisitBinarySmiOperation(), and v8::internal::maglev::MaglevGraphBuilder::VisitUnaryOperation().
GetCallCount()
int v8::internal::FeedbackNexus::GetCallCount ()
Definition at line 1078 of file feedback-vector.cc.
                                {
  DCHECK(IsCallICKind(kind()));
  Tagged<Object> call_count = Cast<Object>(GetFeedbackExtra());
  CHECK(IsSmi(call_count));
  uint32_t value = static_cast<uint32_t>(Smi::ToInt(call_count));
  return CallCountField::decode(value);
}
References CHECK, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), GetFeedbackExtra(), v8::internal::IsCallICKind(), v8::internal::IsSmi(), kind(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by ComputeCallFrequency().
GetCallFeedbackContent()
CallFeedbackContent v8::internal::FeedbackNexus::GetCallFeedbackContent ()
Definition at line 1119 of file feedback-vector.cc.
                                                          {
  DCHECK(IsCallICKind(kind()));
  Tagged<Object> call_count = Cast<Object>(GetFeedbackExtra());
  CHECK(IsSmi(call_count));
  uint32_t value = static_cast<uint32_t>(Smi::ToInt(call_count));
  return CallFeedbackContentField::decode(value);
}
References CHECK, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), GetFeedbackExtra(), v8::internal::IsCallICKind(), v8::internal::IsSmi(), kind(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall().
GetCompareOperationFeedback()
CompareOperationHint v8::internal::FeedbackNexus::GetCompareOperationFeedback () const
Definition at line 1427 of file feedback-vector.cc.
                                                                      {
  DCHECK_EQ(kind(), FeedbackSlotKind::kCompareOp);
  int feedback = GetFeedback().ToSmi().value();
  return CompareOperationHintFromFeedback(feedback);
}
References v8::internal::CompareOperationHintFromFeedback(), DCHECK_EQ, GetFeedback(), v8::internal::kCompareOp, and kind().
Referenced by ic_state(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCompareOperation(), and v8::internal::maglev::MaglevGraphBuilder::VisitCompareOperation().
GetConstructorFeedback()
MaybeDirectHandle< JSObject > v8::internal::FeedbackNexus::GetConstructorFeedback () const
Definition at line 1444 of file feedback-vector.cc.
                                                                        {
  DCHECK_EQ(kind(), FeedbackSlotKind::kInstanceOf);
  Tagged<MaybeObject> feedback = GetFeedback();
  Tagged<HeapObject> heap_object;
  if (feedback.GetHeapObjectIfWeak(&heap_object)) {
    return config()->NewHandle(Cast<JSObject>(heap_object));
  }
  return MaybeDirectHandle<JSObject>();
}
References config(), DCHECK_EQ, GetFeedback(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), kind(), v8::internal::kInstanceOf, and v8::internal::NexusConfig::NewHandle().
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForInstanceOf().
GetFeedback()
Tagged< MaybeObject > v8::internal::FeedbackNexus::GetFeedback () const [inline]
Definition at line 567 of file feedback-vector-inl.h.
                                                     {
  auto pair = GetFeedbackPair();
  return pair.first;
}
References GetFeedbackPair().
Referenced by ConfigureCloneObject(), ConfigureMegamorphic(), GetBinaryOperationFeedback(), GetCompareOperationFeedback(), GetConstructorFeedback(), GetFeedbackPair(), GetForInFeedback(), GetName(), GetTypeOfFeedback(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForRegExpLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTemplateObject(), and SetSpeculationMode().
GetFeedbackExtra()
Tagged< MaybeObject > v8::internal::FeedbackNexus::GetFeedbackExtra () const [inline]
Definition at line 572 of file feedback-vector-inl.h.
                                                          {
  auto pair = GetFeedbackPair();
  return pair.second;
}
References GetFeedbackPair().
Referenced by ConfigureCloneObject(), GetCallCount(), GetCallFeedbackContent(), GetName(), GetSpeculationMode(), and SetSpeculationMode().
GetFeedbackPair()
std::pair< Tagged< MaybeObject >, Tagged< MaybeObject > > v8::internal::FeedbackNexus::GetFeedbackPair () const [inline]
Definition at line 578 of file feedback-vector-inl.h.
                                     {
  if (config()->mode() == NexusConfig::BackgroundThread &&
      feedback_cache_.has_value()) {
    return std::make_pair(FromHandle(feedback_cache_->first),
                          FromHandle(feedback_cache_->second));
  }
  auto pair = FeedbackMetadata::GetSlotSize(kind()) == 2
                  ? config()->GetFeedbackPair(vector(), slot())
                  : std::make_pair(config()->GetFeedback(vector(), slot()),
                                   Tagged<MaybeObject>());
  if (config()->mode() == NexusConfig::BackgroundThread &&
      !feedback_cache_.has_value()) {
    feedback_cache_ =
        std::make_pair(ToHandle(pair.first), ToHandle(pair.second));
  }
  return pair;
}
References v8::internal::NexusConfig::BackgroundThread, config(), feedback_cache_, FromHandle(), GetFeedback(), v8::internal::NexusConfig::GetFeedbackPair(), v8::internal::FeedbackMetadata::GetSlotSize(), kind(), mode(), slot(), ToHandle(), and vector().
Referenced by ConfigureMegamorphic(), ExtractMegaDOMHandler(), v8::internal::FeedbackIterator::FeedbackIterator(), GetFeedback(), GetFeedbackExtra(), GetKeyType(), ic_state(), and IsOneMapManyNames().
GetFirstMap()
Tagged< Map > v8::internal::FeedbackNexus::GetFirstMap () const
Definition at line 755 of file feedback-vector.cc.
                                             {
  FeedbackIterator it(this);
  if (!it.done()) {
    return it.map();
  }
  return Map();
}
References v8::internal::FeedbackIterator::done(), v8::internal::compiler::Map, and v8::internal::FeedbackIterator::map().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::IC::UpdateOneMapManyNamesIC().
GetForInFeedback()
ForInHint v8::internal::FeedbackNexus::GetForInFeedback () const
Definition at line 1438 of file feedback-vector.cc.
                                                {
  DCHECK_EQ(kind(), FeedbackSlotKind::kForIn);
  int feedback = GetFeedback().ToSmi().value();
  return ForInHintFromFeedback(static_cast<ForInFeedback>(feedback));
}
References DCHECK_EQ, v8::internal::ForInHintFromFeedback(), GetFeedback(), v8::internal::kForIn, and kind().
Referenced by ic_state(), and v8::internal::compiler::JSHeapBroker::ReadFeedbackForForIn().
GetKeyedAccessLoadMode()
KeyedAccessLoadMode v8::internal::FeedbackNexus::GetKeyedAccessLoadMode () const
Definition at line 1255 of file feedback-vector.cc.
                                                                {
  DCHECK(IsKeyedLoadICKind(kind()) || IsKeyedHasICKind(kind()));
  // TODO(victorgomes): The KeyedAccessLoadMode::kInBounds is doing double duty
  // here. It shouldn't be used for property loads.
  if (GetKeyType() == IcCheckType::kProperty) {
    return KeyedAccessLoadMode::kInBounds;
  }
  MapsAndHandlers maps_and_handlers(isolate_);
  ExtractMapsAndHandlers(&maps_and_handlers);
  KeyedAccessLoadMode mode = KeyedAccessLoadMode::kInBounds;
  for (auto [_, handler] : maps_and_handlers) {
    mode = GeneralizeKeyedAccessLoadMode(
        mode, LoadHandler::GetKeyedAccessLoadMode(*handler));
  }
  return mode;
}
References _, v8::internal::DCHECK(), ExtractMapsAndHandlers(), v8::internal::GeneralizeKeyedAccessLoadMode(), v8::internal::LoadHandler::GetKeyedAccessLoadMode(), GetKeyType(), v8::internal::IsKeyedHasICKind(), v8::internal::IsKeyedLoadICKind(), isolate_, v8::internal::kInBounds, kind(), v8::internal::kProperty, and mode().
Referenced by v8::internal::compiler::KeyedAccessMode::FromNexus(), and v8::internal::IC::TraceIC().
GetKeyedAccessStoreMode()
KeyedAccessStoreMode v8::internal::FeedbackNexus::GetKeyedAccessStoreMode () const
Definition at line 1322 of file feedback-vector.cc.
                                                                  {
  DCHECK(IsKeyedStoreICKind(kind()) || IsStoreInArrayLiteralICKind(kind()) ||
         IsDefineKeyedOwnPropertyInLiteralKind(kind()) ||
         IsDefineKeyedOwnICKind(kind()));
  KeyedAccessStoreMode mode = KeyedAccessStoreMode::kInBounds;
  if (GetKeyType() == IcCheckType::kProperty) return mode;
  MapsAndHandlers maps_and_handlers(isolate_);
  ExtractMapsAndHandlers(&maps_and_handlers);
  for (auto [_, maybe_code_handler] : maps_and_handlers) {
    // The first handler that isn't the slow handler will have the bits we need.
    Builtin builtin_handler = Builtin::kNoBuiltinId;
    if (IsStoreHandler(*maybe_code_handler.object())) {
      auto data_handler = Cast<StoreHandler>(maybe_code_handler.object());
      if (IsSmi(data_handler->smi_handler())) {
        // Decode the KeyedAccessStoreMode information from the Handler.
        mode =
            StoreHandler::GetKeyedAccessStoreMode(data_handler->smi_handler());
        if (!StoreModeIsInBounds(mode)) return mode;
        continue;
      } else {
        Tagged<Code> code = Cast<Code>(data_handler->smi_handler());
        builtin_handler = code->builtin_id();
      }
    } else if (IsSmi(*maybe_code_handler.object())) {
      // Skip for Proxy Handlers.
      if (*maybe_code_handler.object() == StoreHandler::StoreProxy()) {
        continue;
      }
      // Decode the KeyedAccessStoreMode information from the Handler.
      mode = StoreHandler::GetKeyedAccessStoreMode(*maybe_code_handler);
      if (!StoreModeIsInBounds(mode)) return mode;
      continue;
    } else if (IsDefineKeyedOwnICKind(kind())) {
      mode = StoreHandler::GetKeyedAccessStoreMode(*maybe_code_handler);
      if (!StoreModeIsInBounds(mode)) return mode;
      continue;
    } else {
      // Element store without prototype chain check.
      Tagged<Code> code = Cast<Code>(*maybe_code_handler.object());
      builtin_handler = code->builtin_id();
    }
    if (Builtins::IsBuiltinId(builtin_handler)) {
      if (!BuiltinHasKeyedAccessStoreMode(builtin_handler)) continue;
      mode = KeyedAccessStoreModeForBuiltin(builtin_handler);
      break;
    }
  }
  return mode;
}
References _, v8::internal::anonymous_namespace{feedback-vector.cc}::BuiltinHasKeyedAccessStoreMode(), code, v8::internal::DCHECK(), ExtractMapsAndHandlers(), v8::internal::StoreHandler::GetKeyedAccessStoreMode(), GetKeyType(), v8::internal::Builtins::IsBuiltinId(), v8::internal::IsDefineKeyedOwnICKind(), v8::internal::IsDefineKeyedOwnPropertyInLiteralKind(), v8::internal::IsKeyedStoreICKind(), isolate_, v8::internal::IsSmi(), v8::internal::IsStoreInArrayLiteralICKind(), v8::internal::anonymous_namespace{feedback-vector.cc}::KeyedAccessStoreModeForBuiltin(), v8::internal::kInBounds, kind(), v8::internal::kNoBuiltinId, v8::internal::kProperty, mode(), v8::internal::StoreModeIsInBounds(), and v8::internal::StoreHandler::StoreProxy().
Referenced by v8::internal::compiler::KeyedAccessMode::FromNexus(), v8::internal::KeyedStoreIC::GetKeyedAccessStoreMode(), and v8::internal::IC::TraceIC().
GetKeyType()
IcCheckType v8::internal::FeedbackNexus::GetKeyType () const
Definition at line 1398 of file feedback-vector.cc.
                                            {
  DCHECK(IsKeyedStoreICKind(kind()) || IsKeyedLoadICKind(kind()) ||
         IsStoreInArrayLiteralICKind(kind()) || IsKeyedHasICKind(kind()) ||
         IsDefineKeyedOwnPropertyInLiteralKind(kind()) ||
         IsDefineKeyedOwnICKind(kind()));
  auto pair = GetFeedbackPair();
  Tagged<MaybeObject> feedback = pair.first;
  if (feedback == MegamorphicSentinel()) {
    return static_cast<IcCheckType>(Smi::ToInt(Cast<Smi>(pair.second)));
  }
  if (IsOneMapManyNames()) {
    return IcCheckType::kProperty;
  }
  Tagged<MaybeObject> maybe_name =
      IsDefineKeyedOwnPropertyInLiteralKind(kind()) ||
              IsDefineKeyedOwnICKind(kind())
          ? pair.second
          : feedback;
  return IsPropertyNameFeedback(maybe_name) ? IcCheckType::kProperty
                                            : IcCheckType::kElement;
}
References v8::internal::DCHECK(), GetFeedbackPair(), v8::internal::IsDefineKeyedOwnICKind(), v8::internal::IsDefineKeyedOwnPropertyInLiteralKind(), v8::internal::IsKeyedHasICKind(), v8::internal::IsKeyedLoadICKind(), v8::internal::IsKeyedStoreICKind(), IsOneMapManyNames(), v8::internal::IsPropertyNameFeedback(), v8::internal::IsStoreInArrayLiteralICKind(), v8::internal::kElement, kind(), v8::internal::kProperty, MegamorphicSentinel(), and v8::internal::Smi::ToInt().
Referenced by v8::internal::compiler::KeyedAccessMode::FromNexus(), GetKeyedAccessLoadMode(), GetKeyedAccessStoreMode(), and v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess().
GetLanguageMode()
LanguageMode v8::internal::FeedbackNexus::GetLanguageMode () const [inline]
Definition at line 956 of file feedback-vector.h.
                                              {
    return vector()->GetLanguageMode(slot());
  }
GetName()
Tagged< Name > v8::internal::FeedbackNexus::GetName () const
Definition at line 1238 of file feedback-vector.cc.
                                          {
  if (IsKeyedStoreICKind(kind()) || IsKeyedLoadICKind(kind()) ||
      IsKeyedHasICKind(kind()) || IsDefineKeyedOwnICKind(kind())) {
    Tagged<MaybeObject> feedback = GetFeedback();
    if (IsPropertyNameFeedback(feedback)) {
      return Cast<Name>(feedback.GetHeapObjectAssumeStrong());
    }
  }
  if (IsDefineKeyedOwnPropertyInLiteralKind(kind())) {
    Tagged<MaybeObject> extra = GetFeedbackExtra();
    if (IsPropertyNameFeedback(extra)) {
      return Cast<Name>(extra.GetHeapObjectAssumeStrong());
    }
  }
  return {};
}
References GetFeedback(), GetFeedbackExtra(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeStrong(), v8::internal::IsDefineKeyedOwnICKind(), v8::internal::IsDefineKeyedOwnPropertyInLiteralKind(), v8::internal::IsKeyedHasICKind(), v8::internal::IsKeyedLoadICKind(), v8::internal::IsKeyedStoreICKind(), v8::internal::IsPropertyNameFeedback(), and kind().
Referenced by v8::internal::compiler::JSHeapBroker::GetNameFeedback(), v8::internal::IC::RecomputeHandlerForName(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::IC::UpdateOneMapManyNamesIC().
GetSpeculationMode()
SpeculationMode v8::internal::FeedbackNexus::GetSpeculationMode ()
Definition at line 1110 of file feedback-vector.cc.
                                                  {
  DCHECK(IsCallICKind(kind()));
  Tagged<Object> call_count = Cast<Object>(GetFeedbackExtra());
  CHECK(IsSmi(call_count));
  uint32_t value = static_cast<uint32_t>(Smi::ToInt(call_count));
  return SpeculationModeField::decode(value);
}
References CHECK, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), GetFeedbackExtra(), v8::internal::IsCallICKind(), v8::internal::IsSmi(), kind(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by NextSpeculationMode(), and v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall().
GetTypeOfFeedback()
TypeOfFeedback::Result v8::internal::FeedbackNexus::GetTypeOfFeedback () const
Definition at line 1433 of file feedback-vector.cc.
                                                            {
  DCHECK_EQ(kind(), FeedbackSlotKind::kTypeOf);
  return static_cast<TypeOfFeedback::Result>(GetFeedback().ToSmi().value());
}
References DCHECK_EQ, GetFeedback(), kind(), and v8::internal::kTypeOf.
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForTypeOf().
ic_state()
InlineCacheState v8::internal::FeedbackNexus::ic_state () const
Definition at line 764 of file feedback-vector.cc.
                                               {
  Tagged<MaybeObject> feedback, extra;
  std::tie(feedback, extra) = GetFeedbackPair();
  switch (kind()) {
    case FeedbackSlotKind::kLiteral:
      if (IsSmi(feedback)) return InlineCacheState::UNINITIALIZED;
      return InlineCacheState::MONOMORPHIC;
    case FeedbackSlotKind::kStoreGlobalSloppy:
    case FeedbackSlotKind::kStoreGlobalStrict:
    case FeedbackSlotKind::kLoadGlobalNotInsideTypeof:
    case FeedbackSlotKind::kLoadGlobalInsideTypeof:
    case FeedbackSlotKind::kJumpLoop: {
      if (IsSmi(feedback)) return InlineCacheState::MONOMORPHIC;
      DCHECK(feedback.IsWeakOrCleared());
      if (!feedback.IsCleared() || extra != UninitializedSentinel()) {
        return InlineCacheState::MONOMORPHIC;
      }
      return InlineCacheState::UNINITIALIZED;
    }
    case FeedbackSlotKind::kSetNamedSloppy:
    case FeedbackSlotKind::kSetNamedStrict:
    case FeedbackSlotKind::kSetKeyedSloppy:
    case FeedbackSlotKind::kSetKeyedStrict:
    case FeedbackSlotKind::kStoreInArrayLiteral:
    case FeedbackSlotKind::kDefineNamedOwn:
    case FeedbackSlotKind::kDefineKeyedOwn:
    case FeedbackSlotKind::kLoadProperty:
    case FeedbackSlotKind::kLoadKeyed:
    case FeedbackSlotKind::kHasKeyed: {
      if (feedback == UninitializedSentinel()) {
        return InlineCacheState::UNINITIALIZED;
      }
      if (feedback == MegamorphicSentinel()) {
        return InlineCacheState::MEGAMORPHIC;
      }
      if (feedback == MegaDOMSentinel()) {
        DCHECK(IsLoadICKind(kind()));
        return InlineCacheState::MEGADOM;
      }
      if (feedback.IsWeakOrCleared()) {
        // Don't check if the map is cleared.
        return InlineCacheState::MONOMORPHIC;
      }
      Tagged<HeapObject> heap_object;
      if (feedback.GetHeapObjectIfStrong(&heap_object)) {
        if (IsWeakFixedArray(heap_object)) {
          // Determine state purely by our structure, don't check if the maps
          // are cleared.
          return InlineCacheState::POLYMORPHIC;
        }
        if (IsName(heap_object)) {
          DCHECK(IsKeyedLoadICKind(kind()) || IsKeyedStoreICKind(kind()) ||
                 IsKeyedHasICKind(kind()) || IsDefineKeyedOwnICKind(kind()));
          Tagged<Object> extra_object = extra.GetHeapObjectAssumeStrong();
          Tagged<WeakFixedArray> extra_array =
              Cast<WeakFixedArray>(extra_object);
          return extra_array->length() > 2 ? InlineCacheState::POLYMORPHIC
                                           : InlineCacheState::MONOMORPHIC;
        }
      }
      // TODO(1393773): Remove once the issue is solved.
      Address vector_ptr = vector().ptr();
      config_.isolate()->PushParamsAndDie(
          reinterpret_cast<void*>(feedback.ptr()),
          reinterpret_cast<void*>(extra.ptr()),
          reinterpret_cast<void*>(vector_ptr),
          reinterpret_cast<void*>(static_cast<intptr_t>(slot_.ToInt())),
          reinterpret_cast<void*>(static_cast<intptr_t>(kind())),
          // Include part of the feedback vector containing the slot.
          reinterpret_cast<void*>(
              vector_ptr + FeedbackVector::OffsetOfElementAt(slot_.ToInt())));
      UNREACHABLE();
    }
    case FeedbackSlotKind::kCall: {
      Tagged<HeapObject> heap_object;
      if (feedback == MegamorphicSentinel()) {
        return InlineCacheState::GENERIC;
      } else if (feedback.IsWeakOrCleared()) {
        if (feedback.GetHeapObjectIfWeak(&heap_object)) {
          if (IsFeedbackCell(heap_object)) {
            return InlineCacheState::POLYMORPHIC;
          }
          CHECK(IsJSFunction(heap_object) || IsJSBoundFunction(heap_object));
        }
        return InlineCacheState::MONOMORPHIC;
      } else if (feedback.GetHeapObjectIfStrong(&heap_object) &&
                 IsAllocationSite(heap_object)) {
        return InlineCacheState::MONOMORPHIC;
      }
      CHECK_EQ(feedback, UninitializedSentinel());
      return InlineCacheState::UNINITIALIZED;
    }
    case FeedbackSlotKind::kBinaryOp:
    case FeedbackSlotKind::kStringAddAndInternalize: {
      BinaryOperationHint hint = GetBinaryOperationFeedback();
      if (hint == BinaryOperationHint::kNone) {
        return InlineCacheState::UNINITIALIZED;
      } else if (hint == BinaryOperationHint::kAny) {
        return InlineCacheState::GENERIC;
      }
      return InlineCacheState::MONOMORPHIC;
    }
    case FeedbackSlotKind::kCompareOp: {
      CompareOperationHint hint = GetCompareOperationFeedback();
      if (hint == CompareOperationHint::kNone) {
        return InlineCacheState::UNINITIALIZED;
      } else if (hint == CompareOperationHint::kAny) {
        return InlineCacheState::GENERIC;
      }
      return InlineCacheState::MONOMORPHIC;
    }
    case FeedbackSlotKind::kForIn: {
      ForInHint hint = GetForInFeedback();
      if (hint == ForInHint::kNone) {
        return InlineCacheState::UNINITIALIZED;
      } else if (hint == ForInHint::kAny) {
        return InlineCacheState::GENERIC;
      }
      return InlineCacheState::MONOMORPHIC;
    }
    case FeedbackSlotKind::kTypeOf: {
      if (feedback == Smi::zero()) {
        return InlineCacheState::UNINITIALIZED;
      } else if (feedback == Smi::FromInt(TypeOfFeedback::kAny)) {
        return InlineCacheState::MEGAMORPHIC;
      } else if (base::bits::CountPopulation(
                     static_cast<uint32_t>(feedback.ToSmi().value())) == 1) {
        return InlineCacheState::MONOMORPHIC;
      } else {
        return InlineCacheState::POLYMORPHIC;
      }
    }
    case FeedbackSlotKind::kInstanceOf: {
      if (feedback == UninitializedSentinel()) {
        return InlineCacheState::UNINITIALIZED;
      } else if (feedback == MegamorphicSentinel()) {
        return InlineCacheState::MEGAMORPHIC;
      }
      return InlineCacheState::MONOMORPHIC;
    }
    case FeedbackSlotKind::kDefineKeyedOwnPropertyInLiteral: {
      if (feedback == UninitializedSentinel()) {
        return InlineCacheState::UNINITIALIZED;
      } else if (feedback.IsWeakOrCleared()) {
        // Don't check if the map is cleared.
        return InlineCacheState::MONOMORPHIC;
      }
      return InlineCacheState::MEGAMORPHIC;
    }
    case FeedbackSlotKind::kCloneObject: {
      if (feedback == UninitializedSentinel()) {
        return InlineCacheState::UNINITIALIZED;
      }
      if (feedback == MegamorphicSentinel()) {
        return InlineCacheState::MEGAMORPHIC;
      }
      if (feedback.IsWeakOrCleared()) {
        return InlineCacheState::MONOMORPHIC;
      }
      DCHECK(IsWeakFixedArray(feedback.GetHeapObjectAssumeStrong()));
      return InlineCacheState::POLYMORPHIC;
    }
    case FeedbackSlotKind::kInvalid:
      UNREACHABLE();
  }
  return InlineCacheState::UNINITIALIZED;
}
References CHECK, CHECK_EQ, config_, v8::base::bits::CountPopulation(), v8::internal::DCHECK(), v8::internal::Smi::FromInt(), v8::internal::GENERIC, GetBinaryOperationFeedback(), GetCompareOperationFeedback(), GetFeedbackPair(), GetForInFeedback(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::IsDefineKeyedOwnICKind(), v8::internal::IsKeyedHasICKind(), v8::internal::IsKeyedLoadICKind(), v8::internal::IsKeyedStoreICKind(), v8::internal::IsLoadICKind(), v8::internal::NexusConfig::isolate(), v8::internal::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared(), v8::internal::TypeOfFeedback::kAny, v8::internal::kAny, v8::internal::kBinaryOp, v8::internal::kCall, v8::internal::kCloneObject, v8::internal::kCompareOp, v8::internal::kDefineKeyedOwn, v8::internal::kDefineKeyedOwnPropertyInLiteral, v8::internal::kDefineNamedOwn, v8::internal::kForIn, v8::internal::kHasKeyed, kind(), v8::internal::kInstanceOf, v8::internal::kInvalid, v8::internal::kJumpLoop, v8::internal::kLiteral, v8::internal::kLoadGlobalInsideTypeof, v8::internal::kLoadGlobalNotInsideTypeof, v8::internal::kLoadKeyed, v8::internal::kLoadProperty, v8::internal::kNone, v8::internal::kSetKeyedSloppy, v8::internal::kSetKeyedStrict, v8::internal::kSetNamedSloppy, v8::internal::kSetNamedStrict, v8::internal::kStoreGlobalSloppy, v8::internal::kStoreGlobalStrict, v8::internal::kStoreInArrayLiteral, v8::internal::kStringAddAndInternalize, v8::internal::kTypeOf, v8::internal::MEGADOM, MegaDOMSentinel(), v8::internal::MEGAMORPHIC, MegamorphicSentinel(), v8::internal::MONOMORPHIC, v8::internal::FeedbackVector::OffsetOfElementAt(), v8::internal::POLYMORPHIC, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::Isolate::PushParamsAndDie(), slot_, v8::internal::FeedbackSlot::ToInt(), v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi(), v8::internal::UNINITIALIZED, UninitializedSentinel(), v8::internal::UNREACHABLE(), vector(), and v8::internal::Smi::zero().
Referenced by ConfigureCloneObject(), ExtractMegaDOMHandler(), v8::internal::IC::IC(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::IC::TraceIC().
IsCleared()
bool v8::internal::FeedbackNexus::IsCleared () const [inline]
Definition at line 987 of file feedback-vector.h.
                         {
    InlineCacheState state = ic_state();
    return !v8_flags.use_ic || state == InlineCacheState::UNINITIALIZED;
  }
References v8::internal::UNINITIALIZED, and v8::internal::v8_flags.
Referenced by Clear().
IsGeneric()
bool v8::internal::FeedbackNexus::IsGeneric () const [inline]
Definition at line 967 of file feedback-vector.h.
{ return ic_state() == InlineCacheState::GENERIC; }
References v8::internal::GENERIC.
IsMegamorphic()
bool v8::internal::FeedbackNexus::IsMegamorphic () const [inline]
Definition at line 964 of file feedback-vector.h.
                             {
    return ic_state() == InlineCacheState::MEGAMORPHIC;
  }
References v8::internal::MEGAMORPHIC.
IsOneMapManyNames()
bool v8::internal::FeedbackNexus::IsOneMapManyNames () const
Definition at line 1379 of file feedback-vector.cc.
                                            {
  // "1 map, many names" mode is currently only used for Wasm maps, and
  // {IsWasmObjectMap} is currently only defined for Wasm-enabled builds.
#if V8_ENABLE_WEBASSEMBLY
  if (!IsKeyedLoadICKind(kind()) && !IsKeyedStoreICKind(kind())) return false;
  auto pair = GetFeedbackPair();
  Tagged<HeapObject> heap_object;
  if (!pair.first.GetHeapObjectIfWeak(&heap_object)) return false;
  if (!IsMap(heap_object)) return false;
  if (!IsWasmObjectMap(Cast<Map>(heap_object))) return false;
  if (!IsSmi(pair.second)) return false;
  Tagged<Smi> handler = pair.second.ToSmi();
  return handler == LoadHandler::LoadGeneric() ||
         handler == StoreHandler::StoreGeneric();
#else
  return false;
#endif // V8_ENABLE_WEBASSEMBLY
}
References GetFeedbackPair(), v8::internal::IsKeyedLoadICKind(), v8::internal::IsKeyedStoreICKind(), v8::internal::IsSmi(), kind(), v8::internal::LoadHandler::LoadGeneric(), v8::internal::StoreHandler::StoreGeneric(), and v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
Referenced by GetKeyType(), and v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess().
IsUninitialized()
bool v8::internal::FeedbackNexus::IsUninitialized () const [inline]
Definition at line 961 of file feedback-vector.h.
                               {
    return ic_state() == InlineCacheState::UNINITIALIZED;
  }
References v8::internal::UNINITIALIZED.
Referenced by v8::internal::compiler::JSHeapBroker::FeedbackIsInsufficient(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForBinaryOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCompareOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForForIn(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForInstanceOf(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForRegExpLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTemplateObject(), and v8::internal::compiler::JSHeapBroker::ReadFeedbackForTypeOf().
IterateMapsWithUnclearedHandler()
template<typename F >
void v8::internal::FeedbackNexus::IterateMapsWithUnclearedHandler (F function) const
Definition at line 612 of file feedback-vector-inl.h.
                                                                    {
  // We don't need DisallowGarbageCollection here: accessing it.map() and
  // it.handle() is safe between it.Advance() and a potential GC call in
  // function(). The it itself is not invalidated, since it holds the
  // polymorphic array by handle.
  // TODO(370727490): Make the FeedbackIterator GC safe (e.g. look up
  // map/handler in the feedback array on-demand).
  for (FeedbackIterator it(this); !it.done(); it.Advance()) {
    DirectHandle<Map> map = config()->NewHandle(it.map());
    if (!it.handler().IsCleared()) {
      function(map);
    }
  }
}
References config(), v8::internal::FeedbackIterator::done(), and v8::internal::NexusConfig::NewHandle().
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess().
kind()
FeedbackSlotKind v8::internal::FeedbackNexus::kind () const [inline]
Definition at line 954 of file feedback-vector.h.
{ return kind_; }
Referenced by Clear(), ComputeCallFrequency(), ConfigureHandlerMode(), ConfigureLexicalVarMode(), ConfigureMonomorphic(), ConfigurePropertyCellMode(), ConfigureUninitialized(), ExtractMapsAndHandlers(), v8::internal::FeedbackIterator::FeedbackIterator(), FindHandlerForMap(), v8::internal::compiler::KeyedAccessMode::FromNexus(), GetBinaryOperationFeedback(), GetCallCount(), GetCallFeedbackContent(), GetCompareOperationFeedback(), GetConstructorFeedback(), GetFeedbackPair(), v8::internal::compiler::JSHeapBroker::GetFeedbackSlotKind(), GetForInFeedback(), GetKeyedAccessLoadMode(), GetKeyedAccessStoreMode(), GetKeyType(), GetName(), GetSpeculationMode(), GetTypeOfFeedback(), v8::internal::IC::IC(), ic_state(), IsOneMapManyNames(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForBinaryOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCompareOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForForIn(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForInstanceOf(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForRegExpLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTemplateObject(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTypeOf(), and SetSpeculationMode().
MegaDOMSentinel()
Tagged< MaybeObject > v8::internal::FeedbackNexus::MegaDOMSentinel () const [inline], [private]
Definition at line 553 of file feedback-vector-inl.h.
                                                         {
  return *FeedbackVector::MegaDOMSentinel(config()->isolate());
}
References config(), and v8::internal::FeedbackVector::MegaDOMSentinel().
Referenced by ConfigureMegaDOM(), and ic_state().
MegamorphicSentinel()
Tagged< MaybeObject > v8::internal::FeedbackNexus::MegamorphicSentinel () const [inline], [private]
Definition at line 549 of file feedback-vector-inl.h.
                                                             {
  return *FeedbackVector::MegamorphicSentinel(config()->isolate());
}
References config(), and v8::internal::FeedbackVector::MegamorphicSentinel().
Referenced by ConfigureCloneObject(), ConfigureMegamorphic(), GetKeyType(), and ic_state().
NextSpeculationMode()
void v8::internal::FeedbackNexus::NextSpeculationMode (SpeculationMode mode)
Definition at line 1101 of file feedback-vector.cc.
                                                            {
  SpeculationMode cur = GetSpeculationMode();
  if (cur == SpeculationMode::kAllowSpeculation) {
    SetSpeculationMode(mode);
  } else {
    SetSpeculationMode(SpeculationMode::kDisallowSpeculation);
  }
}
References GetSpeculationMode(), v8::internal::kAllowSpeculation, v8::internal::kDisallowSpeculation, mode(), and SetSpeculationMode().
Print()
void v8::internal::FeedbackNexus::Print (std::ostream & os)
Referenced by v8::internal::RUNTIME_FUNCTION().
SetFeedback() [1/2]
template<typename FeedbackType , typename FeedbackExtraType >
void v8::internal::FeedbackNexus::SetFeedback (Tagged< FeedbackType > feedback, WriteBarrierMode mode, Tagged< FeedbackExtraType > feedback_extra, WriteBarrierMode mode_extra = UPDATE_WRITE_BARRIER) [inline], [private]
Definition at line 603 of file feedback-vector-inl.h.
                                                             {
  config()->SetFeedbackPair(vector(), slot(), feedback, mode, feedback_extra,
                            mode_extra);
}
References config(), mode(), v8::internal::NexusConfig::SetFeedbackPair(), slot(), and vector().
SetFeedback() [2/2]
template<typename FeedbackType >
void v8::internal::FeedbackNexus::SetFeedback (Tagged< FeedbackType > feedback, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [private]
Definition at line 597 of file feedback-vector-inl.h.
                                                       {
  config()->SetFeedback(vector(), slot(), feedback, mode);
}
References config(), mode(), v8::internal::NexusConfig::SetFeedback(), slot(), and vector().
Referenced by Clear(), ConfigureCloneObject(), ConfigureHandlerMode(), ConfigureLexicalVarMode(), ConfigureMegaDOM(), ConfigureMegamorphic(), ConfigureMonomorphic(), ConfigurePolymorphic(), ConfigurePropertyCellMode(), ConfigureUninitialized(), and SetSpeculationMode().
SetSpeculationMode()
void v8::internal::FeedbackNexus::SetSpeculationMode (SpeculationMode mode)
Definition at line 1087 of file feedback-vector.cc.
                                                           {
  DCHECK(IsCallICKind(kind()));
  Tagged<Object> call_count = Cast<Object>(GetFeedbackExtra());
  CHECK(IsSmi(call_count));
  uint32_t count = static_cast<uint32_t>(Smi::ToInt(call_count));
  count = SpeculationModeField::update(count, mode);
  Tagged<MaybeObject> feedback = GetFeedback();
  // We could've skipped WB here (since we set the slot to the same value again)
  // but we don't to make WB verification happy.
  SetFeedback(feedback, UPDATE_WRITE_BARRIER, Smi::FromInt(count),
              SKIP_WRITE_BARRIER);
}
References CHECK, v8::internal::DCHECK(), v8::internal::Smi::FromInt(), GetFeedback(), GetFeedbackExtra(), v8::internal::IsCallICKind(), v8::internal::IsSmi(), kind(), mode(), SetFeedback(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::Smi::ToInt(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::TranslatedState::DoUpdateFeedback(), and NextSpeculationMode().
slot()
FeedbackSlot v8::internal::FeedbackNexus::slot () const [inline]
Definition at line 953 of file feedback-vector.h.
{ return slot_; }
Referenced by FeedbackNexus(), FromHandle(), GetFeedbackPair(), v8::internal::IC::OnFeedbackChanged(), and SetFeedback().
ToHandle()
MaybeObjectHandle v8::internal::FeedbackNexus::ToHandle (Tagged< MaybeObject > value) const [inline], [private]
Definition at line 562 of file feedback-vector-inl.h.
                                                                         {
  return value.IsCleared() ? MaybeObjectHandle()
                           : MaybeObjectHandle(config()->NewHandle(value));
}
References config(), and v8::internal::value.
Referenced by ExtractMapsAndHandlers(), and GetFeedbackPair().
UninitializedSentinel()
Tagged< MaybeObject > v8::internal::FeedbackNexus::UninitializedSentinel () const [inline], [private]
Definition at line 545 of file feedback-vector-inl.h.
                                                               {
  return *FeedbackVector::UninitializedSentinel(config()->isolate());
}
References config(), and v8::internal::FeedbackVector::UninitializedSentinel().
Referenced by Clear(), ConfigureLexicalVarMode(), ConfigurePolymorphic(), ConfigurePropertyCellMode(), ConfigureUninitialized(), and ic_state().
vector()
Tagged<FeedbackVector> v8::internal::FeedbackNexus::vector () const [inline]
Definition at line 949 of file feedback-vector.h.
                                        {
    return vector_handle_.is_null() ? vector_ : *vector_handle_;
  }
Referenced by ComputeCallFrequency(), FeedbackNexus(), GetFeedbackPair(), ic_state(), v8::internal::IC::OnFeedbackChanged(), and SetFeedback().
vector_handle()
DirectHandle<FeedbackVector> v8::internal::FeedbackNexus::vector_handle () const [inline]
Definition at line 945 of file feedback-vector.h.
                                                     {
    DCHECK(vector_.is_null());
    return vector_handle_;
  }
References v8::internal::DCHECK().
Member Data Documentation
config_
NexusConfig v8::internal::FeedbackNexus::config_ [private]
Definition at line 1105 of file feedback-vector.h.
Referenced by ic_state().
feedback_cache_
std::optional<std::pair<MaybeObjectHandle, MaybeObjectHandle> > v8::internal::FeedbackNexus::feedback_cache_ [mutable], [private]
Definition at line 1104 of file feedback-vector.h.
Referenced by GetFeedbackPair().
isolate_
Isolate* v8::internal::FeedbackNexus::isolate_ [private]
Definition at line 1106 of file feedback-vector.h.
Referenced by GetKeyedAccessLoadMode(), and GetKeyedAccessStoreMode().
kCloneObjectPolymorphicEntrySize
constexpr int v8::internal::FeedbackNexus::kCloneObjectPolymorphicEntrySize = 2 [static], [constexpr]
Definition at line 1057 of file feedback-vector.h.
Referenced by ConfigureCloneObject().
kind_
FeedbackSlotKind v8::internal::FeedbackNexus::kind_ [private]
Definition at line 1100 of file feedback-vector.h.
Referenced by FeedbackNexus().
slot_
FeedbackSlot v8::internal::FeedbackNexus::slot_ [private]
Definition at line 1099 of file feedback-vector.h.
Referenced by ic_state().
vector_
Tagged<FeedbackVector> v8::internal::FeedbackNexus::vector_ [private]
Definition at line 1098 of file feedback-vector.h.
vector_handle_
Handle<FeedbackVector> v8::internal::FeedbackNexus::vector_handle_ [private]
Definition at line 1097 of file feedback-vector.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-vector.h
/mnt/V8SourceCode/src/objects/feedback-vector-inl.h
/mnt/V8SourceCode/src/objects/feedback-vector.cc