v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT > Class Template Reference
Classes
class ForceUnicodeScope
struct RegExpCaptureNameLess
Private Member Functions
RegExpParserImpl (const CharT *input, int input_length, RegExpFlags flags, uintptr_t stack_limit, Zone *zone, const DisallowGarbageCollection &no_gc)
bool Parse (RegExpCompileData *result)
RegExpTree * ParsePattern ()
RegExpTree * ParseDisjunction ()
RegExpTree * ParseGroup ()
bool ParseIntervalQuantifier (int *min_out, int *max_out)
bool ParseHexEscape (int length, base::uc32 *value)
bool ParseUnicodeEscape (base::uc32 *value)
bool ParseUnlimitedLengthHexNumber (int max_value, base::uc32 *value)
bool ParsePropertyClassName (ZoneVector< char > *name_1, ZoneVector< char > *name_2)
bool AddPropertyClassRange (ZoneList< CharacterRange > *add_to_range, CharacterClassStrings *add_to_strings, bool negate, const ZoneVector< char > &name_1, const ZoneVector< char > &name_2)
RegExpTree * ParseClassRanges (ZoneList< CharacterRange > *ranges, bool add_unicode_case_equivalents)
void ParseClassEscape (ZoneList< CharacterRange > *ranges, Zone *zone, bool add_unicode_case_equivalents, base::uc32 *char_out, bool *is_class_escape)
bool TryParseCharacterClassEscape (base::uc32 next, InClassEscapeState in_class_escape_state, ZoneList< CharacterRange > *ranges, CharacterClassStrings *strings, Zone *zone, bool add_unicode_case_equivalents)
RegExpTree * ParseClassStringDisjunction (ZoneList< CharacterRange > *ranges, CharacterClassStrings *strings)
RegExpTree * ParseClassSetOperand (const RegExpBuilder *builder, ClassSetOperandType *type_out)
RegExpTree * ParseClassSetOperand (const RegExpBuilder *builder, ClassSetOperandType *type_out, ZoneList< CharacterRange > *ranges, CharacterClassStrings *strings, base::uc32 *character)
base::uc32 ParseClassSetCharacter ()
base::uc32 ParseCharacterEscape (InClassEscapeState in_class_escape_state, bool *is_escaped_unicode_character)
void AddMaybeSimpleCaseFoldedRange (ZoneList< CharacterRange > *ranges, CharacterRange new_range)
RegExpTree * ParseClassUnion (const RegExpBuilder *builder, bool is_negated, RegExpTree *first_operand, ClassSetOperandType first_operand_type, ZoneList< CharacterRange > *ranges, CharacterClassStrings *strings, base::uc32 first_character)
RegExpTree * ParseClassIntersection (const RegExpBuilder *builder, bool is_negated, RegExpTree *first_operand, ClassSetOperandType first_operand_type)
RegExpTree * ParseClassSubtraction (const RegExpBuilder *builder, bool is_negated, RegExpTree *first_operand, ClassSetOperandType first_operand_type)
RegExpTree * ParseCharacterClass (const RegExpBuilder *state)
base::uc32 ParseOctalLiteral ()
bool ParseBackReferenceIndex (int *index_out)
RegExpTree * ReportError (RegExpError error)
void Advance ()
void Advance (int dist)
void RewindByOneCodepoint ()
void Reset (int pos)
bool simple () const
bool contains_anchor () const
void set_contains_anchor ()
int captures_started () const
int position () const
bool failed () const
RegExpFlags flags () const
bool IsUnicodeMode () const
bool unicode_sets () const
bool ignore_case () const
bool IsClassSetReservedDoublePunctuator (base::uc32 c)
RegExpCapture * GetCapture (int index)
bool CreateNamedCaptureAtIndex (const RegExpParserState *state, int index)
const ZoneVector< base::uc16 > * ParseCaptureGroupName ()
bool ParseNamedBackReference (RegExpBuilder *builder, RegExpParserState *state)
RegExpParserState * ParseOpenParenthesis (RegExpParserState *state)
void PatchNamedBackReferences ()
ZoneVector< RegExpCapture * > * GetNamedCaptures ()
bool HasNamedCaptures (InClassEscapeState in_class_escape_state)
Zone * zone () const
base::uc32 current () const
bool has_more () const
bool has_next () const
base::uc32 Next ()
template<bool update_position>
base::uc32 ReadNext ()
CharT InputAt (int index) const
int input_length () const
void ScanForCaptures (InClassEscapeState in_class_escape_state)
base::uc32 ReadNext ()
base::uc32 ReadNext ()
Static Private Member Functions
static bool IsSyntaxCharacterOrSlash (base::uc32 c)
static bool IsClassSetSyntaxCharacter (base::uc32 c)
static bool IsClassSetReservedPunctuator (base::uc32 c)
Private Attributes
const DisallowGarbageCollection no_gc_
Zone *const zone_
RegExpError error_ = RegExpError::kNone
int error_pos_ = 0
ZoneList< RegExpCapture * > * captures_
ZoneMap< RegExpCapture *, ZoneList< int > *, RegExpCaptureNameLess > * named_captures_
ZoneList< RegExpBackReference * > * named_back_references_
const CharT *const input_
const int input_length_
base::uc32 current_
RegExpFlags flags_
bool force_unicode_ = false
int next_pos_
int captures_started_
int capture_count_
int quantifier_count_
int lookaround_count_
bool has_more_
bool simple_
bool contains_anchor_
bool is_scanned_for_captures_
bool has_named_captures_
bool failed_
const uintptr_t stack_limit_
Static Private Attributes
static const base::uc32 kEndMarker = (1 << 21)
Friends
class v8::internal::RegExpParser
Detailed Description
template<class CharT>
class v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >
Definition at line 446 of file regexp-parser.cc.
Constructor & Destructor Documentation
RegExpParserImpl()
template<class CharT >
v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::RegExpParserImpl (const CharT * input, int input_length, RegExpFlags flags, uintptr_t stack_limit, Zone * zone, const DisallowGarbageCollection & no_gc) [private]
Definition at line 661 of file regexp-parser.cc.
    : zone_(zone),
      captures_(nullptr),
      named_captures_(nullptr),
      named_back_references_(nullptr),
      input_(input),
      input_length_(input_length),
      current_(kEndMarker),
      flags_(flags),
      next_pos_(0),
      captures_started_(0),
      capture_count_(0),
      quantifier_count_(0),
      lookaround_count_(0),
      has_more_(true),
      simple_(false),
      contains_anchor_(false),
      is_scanned_for_captures_(false),
      has_named_captures_(false),
      failed_(false),
      stack_limit_(stack_limit) {
  Advance();
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::Advance().
Member Function Documentation
AddMaybeSimpleCaseFoldedRange()
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::AddMaybeSimpleCaseFoldedRange (ZoneList< CharacterRange > * ranges, CharacterRange new_range) [private]
Definition at line 2805 of file regexp-parser.cc.
                                                                {
  DCHECK(unicode_sets());
  if (ignore_case()) {
    ZoneList<CharacterRange>* new_ranges =
        zone()->template New<ZoneList<CharacterRange>>(2, zone());
    new_ranges->Add(new_range, zone());
    CharacterRange::AddUnicodeCaseEquivalents(new_ranges, zone());
    ranges->AddAll(*new_ranges, zone());
  } else {
    ranges->Add(new_range, zone());
  }
  CharacterRange::Canonicalize(ranges);
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::AddAll(), v8::internal::CharacterRange::AddUnicodeCaseEquivalents(), v8::internal::CharacterRange::Canonicalize(), and v8::internal::DCHECK().
AddPropertyClassRange()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::AddPropertyClassRange (ZoneList< CharacterRange > * add_to_range, CharacterClassStrings * add_to_strings, bool negate, const ZoneVector< char > & name_1, const ZoneVector< char > & name_2) [private]
Definition at line 2278 of file regexp-parser.cc.
                                                                    {
  return false;
}
Advance() [1/2]
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::Advance [private]
Definition at line 728 of file regexp-parser.cc.
                                      {
  if (has_next()) {
    if (GetCurrentStackPosition() < stack_limit_) {
      if (v8_flags.correctness_fuzzer_suppressions) {
        FATAL("Aborting on stack overflow");
      }
      ReportError(RegExpError::kStackOverflow);
    } else {
      current_ = ReadNext<true>();
    }
  } else {
    current_ = kEndMarker;
    // Advance so that position() points to 1-after-the-last-character. This is
    // important so that Reset() to this position works correctly.
    next_pos_ = input_length() + 1;
    has_more_ = false;
  }
}
References FATAL, v8::internal::GetCurrentStackPosition(), v8::internal::torque::ReportError(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::RegExpParserImpl().
Advance() [2/2]
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::Advance (int dist) [private]
Definition at line 766 of file regexp-parser.cc.
                                              {
  next_pos_ += dist - 1;
  Advance();
}
captures_started()
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::captures_started () const [inline], [private]
Definition at line 538 of file regexp-parser.cc.
{ return captures_started_; }
contains_anchor()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::contains_anchor () const [inline], [private]
Definition at line 536 of file regexp-parser.cc.
{ return contains_anchor_; }
CreateNamedCaptureAtIndex()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::CreateNamedCaptureAtIndex (const RegExpParserState * state, int index) [private]
Definition at line 1623 of file regexp-parser.cc.
                                               {
  const ZoneVector<base::uc16>* name = state->capture_name();
  const std::pair<int, int> non_participating_capture_group_interval =
      state->non_participating_capture_group_interval();
  DCHECK(0 < index && index <= captures_started_);
  DCHECK_NOT_NULL(name);
  RegExpCapture* capture = GetCapture(index);
  DCHECK_NULL(capture->name());
  capture->set_name(name);
  if (named_captures_ == nullptr) {
    named_captures_ = zone_->template New<
        ZoneMap<RegExpCapture*, ZoneList<int>*, RegExpCaptureNameLess>>(zone());
  } else {
    // Check for duplicates and bail if we find any.
    const auto& named_capture_it = named_captures_->find(capture);
    if (named_capture_it != named_captures_->end()) {
      if (v8_flags.js_regexp_duplicate_named_groups) {
        ZoneList<int>* named_capture_indices = named_capture_it->second;
        DCHECK_NOT_NULL(named_capture_indices);
        DCHECK(!named_capture_indices->is_empty());
        for (int named_index : *named_capture_indices) {
          if (named_index < non_participating_capture_group_interval.first ||
              named_index > non_participating_capture_group_interval.second) {
            ReportError(RegExpError::kDuplicateCaptureGroupName);
            return false;
          }
        }
      } else {
        ReportError(RegExpError::kDuplicateCaptureGroupName);
        return false;
      }
    }
  }
  auto entry = named_captures_->try_emplace(
      capture, zone()->template New<ZoneList<int>>(1, zone()));
  entry.first->second->Add(index, zone());
  return true;
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::capture_name(), v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::index, v8::internal::ZoneList< T >::is_empty(), v8::internal::name, v8::internal::RegExpCapture::name(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::non_participating_capture_group_interval(), v8::internal::torque::ReportError(), v8::internal::RegExpCapture::set_name(), and v8::internal::v8_flags.
current()
template<class CharT >
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::current () const [inline], [private]
Definition at line 593 of file regexp-parser.cc.
{ return current_; }
failed()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::failed () const [inline], [private]
Definition at line 546 of file regexp-parser.cc.
{ return failed_; }
flags()
template<class CharT >
RegExpFlags v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::flags () const [inline], [private]
Definition at line 547 of file regexp-parser.cc.
{ return flags_; }
GetCapture()
template<class CharT >
RegExpCapture * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::GetCapture (int index) [private]
Definition at line 1738 of file regexp-parser.cc.
                                                            {
  // The index for the capture groups are one-based. Its index in the list is
  // zero-based.
  const int known_captures =
      is_scanned_for_captures_ ? capture_count_ : captures_started_;
  SBXCHECK(index >= 1 && index <= known_captures);
  if (captures_ == nullptr) {
    captures_ =
        zone()->template New<ZoneList<RegExpCapture*>>(known_captures, zone());
  }
  while (captures_->length() < known_captures) {
    captures_->Add(zone()->template New<RegExpCapture>(captures_->length() + 1),
                   zone());
  }
  return captures_->at(index - 1);
}
References v8::internal::index, and SBXCHECK.
GetNamedCaptures()
template<class CharT >
ZoneVector< RegExpCapture * > * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::GetNamedCaptures [private]
Definition at line 1756 of file regexp-parser.cc.
                                                                      {
  if (named_captures_ == nullptr) {
    return nullptr;
  }
  DCHECK(!named_captures_->empty());
  ZoneVector<RegExpCapture*>* flattened_named_captures =
      zone()->template New<ZoneVector<RegExpCapture*>>(zone());
  for (auto capture : *named_captures_) {
    DCHECK_IMPLIES(!v8_flags.js_regexp_duplicate_named_groups,
                   capture.second->length() == 1);
    for (int index : *capture.second) {
      flattened_named_captures->push_back(GetCapture(index));
    }
  }
  return flattened_named_captures;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::index, v8::internal::ZoneVector< T >::push_back(), and v8::internal::v8_flags.
has_more()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::has_more () const [inline], [private]
Definition at line 594 of file regexp-parser.cc.
{ return has_more_; }
has_next()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::has_next () const [inline], [private]
Definition at line 595 of file regexp-parser.cc.
{ return next_pos_ < input_length(); }
HasNamedCaptures()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::HasNamedCaptures (InClassEscapeState in_class_escape_state) [private]
Definition at line 1775 of file regexp-parser.cc.
                                              {
  if (has_named_captures_ || is_scanned_for_captures_) {
    return has_named_captures_;
  }
  ScanForCaptures(in_class_escape_state);
  DCHECK(is_scanned_for_captures_);
  return has_named_captures_;
}
References v8::internal::DCHECK().
ignore_case()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ignore_case () const [inline], [private]
Definition at line 554 of file regexp-parser.cc.
{ return IsIgnoreCase(flags()); }
References v8::internal::flags.
input_length()
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::input_length () const [inline], [private]
Definition at line 603 of file regexp-parser.cc.
{ return input_length_; }
InputAt()
template<class CharT >
CharT v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::InputAt (int index) const [inline], [private]
Definition at line 599 of file regexp-parser.cc.
                                 {
    DCHECK(0 <= index && index < input_length());
    return input_[index];
  }
References v8::internal::DCHECK(), and v8::internal::index.
IsClassSetReservedDoublePunctuator()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::IsClassSetReservedDoublePunctuator (base::uc32 c) [private]
Definition at line 844 of file regexp-parser.cc.
                                                                           {
#define DOUBLE_PUNCTUATOR_CASE(Char) \
  case Char: \
    return Next() == Char
  switch (c) {
    DOUBLE_PUNCTUATOR_CASE('&');
    DOUBLE_PUNCTUATOR_CASE('!');
    DOUBLE_PUNCTUATOR_CASE('#');
    DOUBLE_PUNCTUATOR_CASE('$');
    DOUBLE_PUNCTUATOR_CASE('%');
    DOUBLE_PUNCTUATOR_CASE('*');
    DOUBLE_PUNCTUATOR_CASE('+');
    DOUBLE_PUNCTUATOR_CASE(',');
    DOUBLE_PUNCTUATOR_CASE('.');
    DOUBLE_PUNCTUATOR_CASE(':');
    DOUBLE_PUNCTUATOR_CASE(';');
    DOUBLE_PUNCTUATOR_CASE('<');
    DOUBLE_PUNCTUATOR_CASE('=');
    DOUBLE_PUNCTUATOR_CASE('>');
    DOUBLE_PUNCTUATOR_CASE('?');
    DOUBLE_PUNCTUATOR_CASE('@');
    DOUBLE_PUNCTUATOR_CASE('^');
    DOUBLE_PUNCTUATOR_CASE('`');
    DOUBLE_PUNCTUATOR_CASE('~');
    default:
      break;
  }
#undef DOUBLE_PUNCTUATOR_CASE
  return false;
}
References DOUBLE_PUNCTUATOR_CASE.
IsClassSetReservedPunctuator()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::IsClassSetReservedPunctuator (base::uc32 c) [static], [private]
Definition at line 820 of file regexp-parser.cc.
                                                                     {
  switch (c) {
    case '&':
    case '-':
    case '!':
    case '#':
    case '%':
    case ',':
    case ':':
    case ';':
    case '<':
    case '=':
    case '>':
    case '@':
    case '`':
    case '~':
      return true;
    default:
      break;
  }
  return false;
}
IsClassSetSyntaxCharacter()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::IsClassSetSyntaxCharacter (base::uc32 c) [static], [private]
Definition at line 799 of file regexp-parser.cc.
                                                                  {
  switch (c) {
    case '(':
    case ')':
    case '[':
    case ']':
    case '{':
    case '}':
    case '/':
    case '-':
    case '\\':
    case '|':
      return true;
    default:
      break;
  }
  return false;
}
IsSyntaxCharacterOrSlash()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::IsSyntaxCharacterOrSlash (base::uc32 c) [static], [private]
Definition at line 773 of file regexp-parser.cc.
                                                                 {
  switch (c) {
    case '^':
    case '$':
    case '\\':
    case '.':
    case '*':
    case '+':
    case '?':
    case '(':
    case ')':
    case '[':
    case ']':
    case '{':
    case '}':
    case '|':
    case '/':
      return true;
    default:
      break;
  }
  return false;
}
IsUnicodeMode()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::IsUnicodeMode () const [inline], [private]
Definition at line 548 of file regexp-parser.cc.
                             {
    // Either /v or /u enable UnicodeMode
    // https://tc39.es/ecma262/#sec-parsepattern
    return IsUnicode(flags()) || IsUnicodeSets(flags()) || force_unicode_;
  }
References v8::internal::flags.
Next()
template<class CharT >
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::Next [private]
Definition at line 719 of file regexp-parser.cc.
                                       {
  if (has_next()) {
    return ReadNext<false>();
  } else {
    return kEndMarker;
  }
}
Parse()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::Parse (RegExpCompileData * result) [private]
Definition at line 3089 of file regexp-parser.cc.
                                                             {
  DCHECK_NOT_NULL(result);
  RegExpTree* tree = ParsePattern();
  if (failed()) {
    DCHECK_NULL(tree);
    DCHECK_NE(error_, RegExpError::kNone);
    result->error = error_;
    result->error_pos = error_pos_;
    return false;
  }
  DCHECK_NOT_NULL(tree);
  DCHECK_EQ(error_, RegExpError::kNone);
  if (v8_flags.trace_regexp_parser) {
    StdoutStream os;
    tree->Print(os, zone());
    os << "\n";
  }
  result->tree = tree;
  const int capture_count = captures_started();
  result->simple = tree->IsAtom() && simple() && capture_count == 0;
  result->contains_anchor = contains_anchor();
  result->capture_count = capture_count;
  result->named_captures = GetNamedCaptures();
  return true;
}
References DCHECK_EQ, DCHECK_NE, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::RegExpTree::Print(), v8::base::internal::result, and v8::internal::v8_flags.
ParseBackReferenceIndex()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseBackReferenceIndex (int * index_out) [private]
Definition at line 1503 of file regexp-parser.cc.
                                                                    {
  DCHECK_EQ('\\', current());
  DCHECK('1' <= Next() && Next() <= '9');
  // Try to parse a decimal literal that is no greater than the total number
  // of left capturing parentheses in the input.
  int start = position();
  int value = Next() - '0';
  Advance(2);
  while (true) {
    base::uc32 c = current();
    if (IsDecimalDigit(c)) {
      value = 10 * value + (c - '0');
      if (value > RegExpMacroAssembler::kMaxCaptures) {
        Reset(start);
        return false;
      }
      Advance();
    } else {
      break;
    }
  }
  if (value > captures_started()) {
    if (!is_scanned_for_captures_) {
      ScanForCaptures(InClassEscapeState::kNotInClass);
    }
    if (value > capture_count_) {
      Reset(start);
      return false;
    }
  }
  *index_out = value;
  return true;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::IsDecimalDigit(), v8::internal::RegExpMacroAssembler::kMaxCaptures, v8::internal::anonymous_namespace{regexp-parser.cc}::kNotInClass, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), and v8::internal::value.
ParseCaptureGroupName()
template<class CharT >
const ZoneVector< base::uc16 > * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCaptureGroupName [private]
Definition at line 1551 of file regexp-parser.cc.
                                                                           {
  // Due to special Advance requirements (see the next comment), rewind by one
  // such that names starting with a surrogate pair are parsed correctly for
  // patterns where the unicode flag is unset.
  //
  // Note that we use this odd pattern of rewinding the last advance in order
  // to adhere to the common parser behavior of expecting `current` to point at
  // the first candidate character for a function (e.g. when entering ParseFoo,
  // `current` should point at the first character of Foo).
  RewindByOneCodepoint();
  ZoneVector<base::uc16>* name =
      zone()->template New<ZoneVector<base::uc16>>(zone());
  {
    // Advance behavior inside this function is tricky since
    // RegExpIdentifierName explicitly enables unicode (in spec terms, sets +U)
    // and thus allows surrogate pairs and \u{}-style escapes even in
    // non-unicode patterns. Therefore Advance within the capture group name
    // has to force-enable unicode, and outside the name revert to default
    // behavior.
    ForceUnicodeScope force_unicode(this);
    bool at_start = true;
    while (true) {
      Advance();
      base::uc32 c = current();
      // Convert unicode escapes.
      if (c == '\\' && Next() == 'u') {
        Advance(2);
        if (!ParseUnicodeEscape(&c)) {
          ReportError(RegExpError::kInvalidUnicodeEscape);
          return nullptr;
        }
        RewindByOneCodepoint();
      }
      // The backslash char is misclassified as both ID_Start and ID_Continue.
      if (c == '\\') {
        ReportError(RegExpError::kInvalidCaptureGroupName);
        return nullptr;
      }
      if (at_start) {
        if (!IsIdentifierStart(c)) {
          ReportError(RegExpError::kInvalidCaptureGroupName);
          return nullptr;
        }
        push_code_unit(name, c);
        at_start = false;
      } else {
        if (c == '>') {
          break;
        } else if (IsIdentifierPart(c)) {
          push_code_unit(name, c);
        } else {
          ReportError(RegExpError::kInvalidCaptureGroupName);
          return nullptr;
        }
      }
    }
  }
  // This final advance goes back into the state of pointing at the next
  // relevant char, which the rest of the parser expects. See also the previous
  // comments in this function.
  Advance();
  return name;
}
References v8::internal::IsIdentifierPart(), v8::internal::IsIdentifierStart(), v8::internal::name, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::push_code_unit(), and v8::internal::torque::ReportError().
ParseCharacterClass()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCharacterClass (const RegExpBuilder * state) [private]
Definition at line 3009 of file regexp-parser.cc.
                                  {
  DCHECK_EQ(current(), '[');
  Advance();
  bool is_negated = false;
  if (current() == '^') {
    is_negated = true;
    Advance();
  }
  ZoneList<CharacterRange>* ranges =
      zone()->template New<ZoneList<CharacterRange>>(2, zone());
  if (current() == ']') {
    Advance();
    if (unicode_sets()) {
      return RegExpClassSetExpression::Empty(zone(), is_negated);
    } else {
      RegExpClassRanges::ClassRangesFlags class_ranges_flags;
      if (is_negated) class_ranges_flags = RegExpClassRanges::NEGATED;
      return zone()->template New<RegExpClassRanges>(zone(), ranges,
                                                     class_ranges_flags);
    }
  }
  if (!unicode_sets()) {
    bool add_unicode_case_equivalents = IsUnicodeMode() && ignore_case();
    ParseClassRanges(ranges, add_unicode_case_equivalents CHECK_FAILED);
    if (!has_more()) {
      return ReportError(RegExpError::kUnterminatedCharacterClass);
    }
    DCHECK_EQ(current(), ']');
    Advance();
    RegExpClassRanges::ClassRangesFlags character_class_flags;
    if (is_negated) character_class_flags = RegExpClassRanges::NEGATED;
    return zone()->template New<RegExpClassRanges>(zone(), ranges,
                                                   character_class_flags);
  } else {
    ClassSetOperandType operand_type;
    CharacterClassStrings* strings =
        zone()->template New<CharacterClassStrings>(zone());
    base::uc32 character;
    RegExpTree* operand = ParseClassSetOperand(
        builder, &operand_type, ranges, strings, &character CHECK_FAILED);
    switch (current()) {
      case '-':
        if (Next() == '-') {
          if (operand == nullptr) {
            if (operand_type == ClassSetOperandType::kClassSetCharacter) {
              AddMaybeSimpleCaseFoldedRange(
                  ranges, CharacterRange::Singleton(character));
            }
            operand =
                zone()->template New<RegExpClassSetOperand>(ranges, strings);
          }
          return ParseClassSubtraction(builder, is_negated, operand,
                                       operand_type);
        }
        // ClassSetRange is handled in ParseClassUnion().
        break;
      case '&':
        if (Next() == '&') {
          if (operand == nullptr) {
            if (operand_type == ClassSetOperandType::kClassSetCharacter) {
              AddMaybeSimpleCaseFoldedRange(
                  ranges, CharacterRange::Singleton(character));
            }
            operand =
                zone()->template New<RegExpClassSetOperand>(ranges, strings);
          }
          return ParseClassIntersection(builder, is_negated, operand,
                                        operand_type);
        }
    }
    return ParseClassUnion(builder, is_negated, operand, operand_type, ranges,
                           strings, character);
  }
}
References v8::internal::character, CHECK_FAILED, DCHECK_EQ, v8::internal::RegExpClassSetExpression::Empty(), v8::internal::anonymous_namespace{regexp-parser.cc}::kClassSetCharacter, v8::internal::RegExpClassRanges::NEGATED, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::torque::ReportError(), and v8::internal::CharacterRange::Singleton().
ParseCharacterEscape()
template<class CharT >
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCharacterEscape (InClassEscapeState in_class_escape_state, bool * is_escaped_unicode_character) [private]
Definition at line 2309 of file regexp-parser.cc.
                                        {
  DCHECK_EQ('\\', current());
  DCHECK(has_next());
  Advance();
  const base::uc32 c = current();
  switch (c) {
    // CharacterEscape ::
    // ControlEscape :: one of
    // f n r t v
    case 'f':
      Advance();
      return '\f';
    case 'n':
      Advance();
      return '\n';
    case 'r':
      Advance();
      return '\r';
    case 't':
      Advance();
      return '\t';
    case 'v':
      Advance();
      return '\v';
    // CharacterEscape ::
    // c ControlLetter
    case 'c': {
      base::uc32 controlLetter = Next();
      base::uc32 letter = controlLetter & ~('A' ^ 'a');
      if (letter >= 'A' && letter <= 'Z') {
        Advance(2);
        // Control letters mapped to ASCII control characters in the range
        // 0x00-0x1F.
        return controlLetter & 0x1F;
      }
      if (IsUnicodeMode()) {
        // With /u and /v, invalid escapes are not treated as identity escapes.
        ReportError(RegExpError::kInvalidUnicodeEscape);
        return 0;
      }
      if (in_class_escape_state == InClassEscapeState::kInClass) {
        // Inside a character class, we also accept digits and underscore as
        // control characters, unless with /u or /v. See Annex B:
        // ES#prod-annexB-ClassControlLetter
        if ((controlLetter >= '0' && controlLetter <= '9') ||
            controlLetter == '_') {
          Advance(2);
          return controlLetter & 0x1F;
        }
      }
      // We match JSC in reading the backslash as a literal
      // character instead of as starting an escape.
      return '\\';
    }
    // CharacterEscape ::
    // 0 [lookahead DecimalDigit]
    // [~UnicodeMode] LegacyOctalEscapeSequence
    case '0':
      // \0 is interpreted as NUL if not followed by another digit.
      if (Next() < '0' || Next() > '9') {
        Advance();
        return 0;
      }
      [[fallthrough]];
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
      // For compatibility, we interpret a decimal escape that isn't
      // a back reference (and therefore either \0 or not valid according
      // to the specification) as a 1..3 digit octal character code.
      // ES#prod-annexB-LegacyOctalEscapeSequence
      if (IsUnicodeMode()) {
        // With /u or /v, decimal escape is not interpreted as octal character
        // code.
        ReportError(RegExpError::kInvalidDecimalEscape);
        return 0;
      }
      return ParseOctalLiteral();
    // CharacterEscape ::
    // HexEscapeSequence
    case 'x': {
      Advance();
      base::uc32 value;
      if (ParseHexEscape(2, &value)) return value;
      if (IsUnicodeMode()) {
        // With /u or /v, invalid escapes are not treated as identity escapes.
        ReportError(RegExpError::kInvalidEscape);
        return 0;
      }
      // If \x is not followed by a two-digit hexadecimal, treat it
      // as an identity escape.
      return 'x';
    }
    // CharacterEscape ::
    // RegExpUnicodeEscapeSequence [?UnicodeMode]
    case 'u': {
      Advance();
      base::uc32 value;
      if (ParseUnicodeEscape(&value)) {
        *is_escaped_unicode_character = true;
        return value;
      }
      if (IsUnicodeMode()) {
        // With /u or /v, invalid escapes are not treated as identity escapes.
        ReportError(RegExpError::kInvalidUnicodeEscape);
        return 0;
      }
      // If \u is not followed by a two-digit hexadecimal, treat it
      // as an identity escape.
      return 'u';
    }
    default:
      break;
  }
  // CharacterEscape ::
  // IdentityEscape[?UnicodeMode, ?N]
  //
  // * With /u, no identity escapes except for syntax characters are
  // allowed.
  // * With /v, no identity escapes except for syntax characters and
  // ClassSetReservedPunctuators (if within a class) are allowed.
  // * Without /u or /v:
  // * '\c' is not an IdentityEscape.
  // * '\k' is not an IdentityEscape when named captures exist.
  // * Otherwise, all identity escapes are allowed.
  if (unicode_sets() && in_class_escape_state == InClassEscapeState::kInClass) {
    if (IsClassSetReservedPunctuator(c)) {
      Advance();
      return c;
    }
  }
  if (IsUnicodeMode()) {
    if (!IsSyntaxCharacterOrSlash(c)) {
      ReportError(RegExpError::kInvalidEscape);
      return 0;
    }
    Advance();
    return c;
  }
  DCHECK(!IsUnicodeMode());
  if (c == 'c') {
    ReportError(RegExpError::kInvalidEscape);
    return 0;
  }
  Advance();
  // Note: It's important to Advance before the HasNamedCaptures call s.t. we
  // don't start scanning in the middle of an escape.
  if (c == 'k' && HasNamedCaptures(in_class_escape_state)) {
    ReportError(RegExpError::kInvalidEscape);
    return 0;
  }
  return c;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{regexp-parser.cc}::kInClass, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::torque::ReportError(), and v8::internal::value.
ParseClassEscape()
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassEscape (ZoneList< CharacterRange > * ranges, Zone * zone, bool add_unicode_case_equivalents, base::uc32 * char_out, bool * is_class_escape) [private]
Definition at line 2520 of file regexp-parser.cc.
                           {
  *is_class_escape = false;
  if (current() != '\\') {
    // Not a ClassEscape.
    *char_out = current();
    Advance();
    return;
  }
  const base::uc32 next = Next();
  switch (next) {
    case 'b':
      *char_out = '\b';
      Advance(2);
      return;
    case '-':
      if (IsUnicodeMode()) {
        *char_out = next;
        Advance(2);
        return;
      }
      break;
    case kEndMarker:
      ReportError(RegExpError::kEscapeAtEndOfPattern);
      return;
    default:
      break;
  }
  static constexpr InClassEscapeState kInClassEscape =
      InClassEscapeState::kInClass;
  *is_class_escape =
      TryParseCharacterClassEscape(next, kInClassEscape, ranges, nullptr, zone,
                                   add_unicode_case_equivalents);
  if (*is_class_escape) return;
  bool dummy = false; // Unused.
  *char_out = ParseCharacterEscape(kInClassEscape, &dummy);
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::kInClass, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), and v8::internal::torque::ReportError().
ParseClassIntersection()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassIntersection (const RegExpBuilder * builder, bool is_negated, RegExpTree * first_operand, ClassSetOperandType first_operand_type) [private]
Definition at line 2934 of file regexp-parser.cc.
                                            {
  DCHECK(unicode_sets());
  DCHECK(current() == '&' && Next() == '&');
  bool may_contain_strings =
      MayContainStrings(first_operand_type, first_operand);
  ZoneList<RegExpTree*>* operands =
      zone()->template New<ZoneList<RegExpTree*>>(2, zone());
  operands->Add(first_operand, zone());
  while (has_more() && current() != ']') {
    if (current() != '&' || Next() != '&') {
      return ReportError(RegExpError::kInvalidClassSetOperation);
    }
    Advance(2);
    // [lookahead &]
    if (current() == '&') {
      return ReportError(RegExpError::kInvalidCharacterInClass);
    }
    ClassSetOperandType operand_type;
    RegExpTree* operand =
        ParseClassSetOperand(builder, &operand_type CHECK_FAILED);
    may_contain_strings &= MayContainStrings(operand_type, operand);
    operands->Add(operand, zone());
  }
  if (!has_more()) {
    return ReportError(RegExpError::kUnterminatedCharacterClass);
  }
  if (is_negated && may_contain_strings) {
    return ReportError(RegExpError::kNegatedCharacterClassWithStrings);
  }
  DCHECK_EQ(current(), ']');
  Advance();
  return zone()->template New<RegExpClassSetExpression>(
      RegExpClassSetExpression::OperationType::kIntersection, is_negated,
      may_contain_strings, operands);
}
References v8::internal::ZoneList< T >::Add(), CHECK_FAILED, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegExpClassSetExpression::kIntersection, v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::MayContainStrings(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), and v8::internal::torque::ReportError().
ParseClassRanges()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassRanges (ZoneList< CharacterRange > * ranges, bool add_unicode_case_equivalents) [private]
Definition at line 2474 of file regexp-parser.cc.
                                                                         {
  base::uc32 char_1, char_2;
  bool is_class_1, is_class_2;
  while (has_more() && current() != ']') {
    ParseClassEscape(ranges, zone(), add_unicode_case_equivalents, &char_1,
                     &is_class_1 CHECK_FAILED);
    // ClassAtom
    if (current() == '-') {
      Advance();
      if (!has_more()) {
        // If we reach the end we break out of the loop and let the
        // following code report an error.
        break;
      } else if (current() == ']') {
        if (!is_class_1) ranges->Add(CharacterRange::Singleton(char_1), zone());
        ranges->Add(CharacterRange::Singleton('-'), zone());
        break;
      }
      ParseClassEscape(ranges, zone(), add_unicode_case_equivalents, &char_2,
                       &is_class_2 CHECK_FAILED);
      if (is_class_1 || is_class_2) {
        // Either end is an escaped character class. Treat the '-' verbatim.
        if (IsUnicodeMode()) {
          // ES2015 21.2.2.15.1 step 1.
          return ReportError(RegExpError::kInvalidCharacterClass);
        }
        if (!is_class_1) ranges->Add(CharacterRange::Singleton(char_1), zone());
        ranges->Add(CharacterRange::Singleton('-'), zone());
        if (!is_class_2) ranges->Add(CharacterRange::Singleton(char_2), zone());
        continue;
      }
      // ES2015 21.2.2.15.1 step 6.
      if (char_1 > char_2) {
        return ReportError(RegExpError::kOutOfOrderCharacterClass);
      }
      ranges->Add(CharacterRange::Range(char_1, char_2), zone());
    } else {
      if (!is_class_1) ranges->Add(CharacterRange::Singleton(char_1), zone());
    }
  }
  return nullptr;
}
References v8::internal::ZoneList< T >::Add(), CHECK_FAILED, v8::internal::CharacterRange::Range(), v8::internal::torque::ReportError(), and v8::internal::CharacterRange::Singleton().
ParseClassSetCharacter()
template<class CharT >
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSetCharacter [private]
Definition at line 2755 of file regexp-parser.cc.
                                                         {
  DCHECK(unicode_sets());
  const base::uc32 c = current();
  if (c == '\\') {
    const base::uc32 next = Next();
    switch (next) {
      case 'b':
        Advance(2);
        return '\b';
      case kEndMarker:
        ReportError(RegExpError::kEscapeAtEndOfPattern);
        return 0;
    }
    static constexpr InClassEscapeState kInClassEscape =
        InClassEscapeState::kInClass;
    bool dummy = false; // Unused.
    return ParseCharacterEscape(kInClassEscape, &dummy);
  }
  if (IsClassSetSyntaxCharacter(c)) {
    ReportError(RegExpError::kInvalidCharacterInClass);
    return 0;
  }
  if (IsClassSetReservedDoublePunctuator(c)) {
    ReportError(RegExpError::kInvalidClassSetOperation);
    return 0;
  }
  Advance();
  return c;
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{regexp-parser.cc}::kInClass, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), and v8::internal::torque::ReportError().
ParseClassSetOperand() [1/2]
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSetOperand (const RegExpBuilder * builder, ClassSetOperandType * type_out) [private]
Definition at line 2676 of file regexp-parser.cc.
                                                                 {
  ZoneList<CharacterRange>* ranges =
      zone()->template New<ZoneList<CharacterRange>>(1, zone());
  CharacterClassStrings* strings =
      zone()->template New<CharacterClassStrings>(zone());
  base::uc32 character;
  RegExpTree* tree = ParseClassSetOperand(builder, type_out, ranges, strings,
                                          &character CHECK_FAILED);
  DCHECK_IMPLIES(*type_out != ClassSetOperandType::kNestedClass,
                 tree == nullptr);
  DCHECK_IMPLIES(*type_out == ClassSetOperandType::kClassSetCharacter,
                 ranges->is_empty());
  DCHECK_IMPLIES(*type_out == ClassSetOperandType::kClassSetCharacter,
                 strings->empty());
  DCHECK_IMPLIES(*type_out == ClassSetOperandType::kNestedClass,
                 ranges->is_empty());
  DCHECK_IMPLIES(*type_out == ClassSetOperandType::kNestedClass,
                 strings->empty());
  DCHECK_IMPLIES(*type_out == ClassSetOperandType::kNestedClass,
                 tree->IsClassSetExpression());
  // ClassSetRange is only used within ClassSetUnion().
  DCHECK_NE(*type_out, ClassSetOperandType::kClassSetRange);
  // There are no restrictions for kCharacterClassEscape.
  // CharacterClassEscape includes \p{}, which can contain ranges, strings or
  // both and \P{}, which could contain nothing (i.e. \P{Any}).
  if (tree == nullptr) {
    if (*type_out == ClassSetOperandType::kClassSetCharacter) {
      AddMaybeSimpleCaseFoldedRange(ranges,
                                    CharacterRange::Singleton(character));
    }
    tree = zone()->template New<RegExpClassSetOperand>(ranges, strings);
  }
  return tree;
}
References v8::internal::character, CHECK_FAILED, DCHECK_IMPLIES, DCHECK_NE, v8::internal::ZoneList< T >::is_empty(), v8::internal::anonymous_namespace{regexp-parser.cc}::kClassSetCharacter, v8::internal::anonymous_namespace{regexp-parser.cc}::kClassSetRange, v8::internal::anonymous_namespace{regexp-parser.cc}::kNestedClass, and v8::internal::CharacterRange::Singleton().
ParseClassSetOperand() [2/2]
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSetOperand (const RegExpBuilder * builder, ClassSetOperandType * type_out, ZoneList< CharacterRange > * ranges, CharacterClassStrings * strings, base::uc32 * character) [private]
Definition at line 2720 of file regexp-parser.cc.
                         {
  DCHECK(unicode_sets());
  base::uc32 c = current();
  if (c == '\\') {
    const base::uc32 next = Next();
    if (next == 'q') {
      *type_out = ClassSetOperandType::kClassStringDisjunction;
      ParseClassStringDisjunction(ranges, strings CHECK_FAILED);
      return nullptr;
    }
    static constexpr InClassEscapeState kInClassEscape =
        InClassEscapeState::kInClass;
    const bool add_unicode_case_equivalents = ignore_case();
    if (TryParseCharacterClassEscape(next, kInClassEscape, ranges, strings,
                                     zone(), add_unicode_case_equivalents)) {
      *type_out = ClassSetOperandType::kCharacterClassEscape;
      return nullptr;
    }
  }
  if (c == '[') {
    *type_out = ClassSetOperandType::kNestedClass;
    return ParseCharacterClass(builder);
  }
  *type_out = ClassSetOperandType::kClassSetCharacter;
  c = ParseClassSetCharacter(CHECK_FAILED);
  *character = c;
  return nullptr;
}
References v8::internal::character, CHECK_FAILED, v8::internal::DCHECK(), v8::internal::anonymous_namespace{regexp-parser.cc}::kCharacterClassEscape, v8::internal::anonymous_namespace{regexp-parser.cc}::kClassSetCharacter, v8::internal::anonymous_namespace{regexp-parser.cc}::kClassStringDisjunction, v8::internal::anonymous_namespace{regexp-parser.cc}::kInClass, v8::internal::anonymous_namespace{regexp-parser.cc}::kNestedClass, and v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next().
ParseClassStringDisjunction()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassStringDisjunction (ZoneList< CharacterRange > * ranges, CharacterClassStrings * strings) [private]
Definition at line 2623 of file regexp-parser.cc.
                                                                      {
  DCHECK(unicode_sets());
  DCHECK_EQ(current(), '\\');
  DCHECK_EQ(Next(), 'q');
  Advance(2);
  if (current() != '{') {
    // Identity escape of 'q' is not allowed in unicode mode.
    return ReportError(RegExpError::kInvalidEscape);
  }
  Advance();
  ZoneList<base::uc32>* string =
      zone()->template New<ZoneList<base::uc32>>(4, zone());
  RegExpTextBuilder::SmallRegExpTreeVector string_storage(zone());
  RegExpTextBuilder string_builder(zone(), &string_storage, flags());
  while (has_more() && current() != '}') {
    if (current() == '|') {
      AddClassString(string, string_builder.ToRegExp(), ranges, strings,
                     zone());
      string = zone()->template New<ZoneList<base::uc32>>(4, zone());
      string_storage.clear();
      Advance();
    } else {
      base::uc32 c = ParseClassSetCharacter(CHECK_FAILED);
      if (ignore_case()) {
#ifdef V8_INTL_SUPPORT
        c = u_foldCase(c, U_FOLD_CASE_DEFAULT);
#else
        c = AsciiAlphaToLower(c);
#endif
      }
      string->Add(c, zone());
      string_builder.AddUnicodeCharacter(c);
    }
  }
  AddClassString(string, string_builder.ToRegExp(), ranges, strings, zone());
  CharacterRange::Canonicalize(ranges);
  // We don't need to handle missing closing '}' here.
  // If the character class is correctly closed, ParseClassSetCharacter will
  // report an error.
  Advance();
  return nullptr;
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::AddClassString(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddUnicodeCharacter(), v8::internal::AsciiAlphaToLower(), v8::internal::CharacterRange::Canonicalize(), CHECK_FAILED, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::flags, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::torque::ReportError(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::ToRegExp().
ParseClassSubtraction()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSubtraction (const RegExpBuilder * builder, bool is_negated, RegExpTree * first_operand, ClassSetOperandType first_operand_type) [private]
Definition at line 2975 of file regexp-parser.cc.
                                            {
  DCHECK(unicode_sets());
  DCHECK(current() == '-' && Next() == '-');
  const bool may_contain_strings =
      MayContainStrings(first_operand_type, first_operand);
  if (is_negated && may_contain_strings) {
    return ReportError(RegExpError::kNegatedCharacterClassWithStrings);
  }
  ZoneList<RegExpTree*>* operands =
      zone()->template New<ZoneList<RegExpTree*>>(2, zone());
  operands->Add(first_operand, zone());
  while (has_more() && current() != ']') {
    if (current() != '-' || Next() != '-') {
      return ReportError(RegExpError::kInvalidClassSetOperation);
    }
    Advance(2);
    ClassSetOperandType dummy; // unused
    RegExpTree* operand = ParseClassSetOperand(builder, &dummy CHECK_FAILED);
    operands->Add(operand, zone());
  }
  if (!has_more()) {
    return ReportError(RegExpError::kUnterminatedCharacterClass);
  }
  DCHECK_EQ(current(), ']');
  Advance();
  return zone()->template New<RegExpClassSetExpression>(
      RegExpClassSetExpression::OperationType::kSubtraction, is_negated,
      may_contain_strings, operands);
}
References v8::internal::ZoneList< T >::Add(), CHECK_FAILED, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegExpClassSetExpression::kSubtraction, v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::MayContainStrings(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), and v8::internal::torque::ReportError().
ParseClassUnion()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion (const RegExpBuilder * builder, bool is_negated, RegExpTree * first_operand, ClassSetOperandType first_operand_type, ZoneList< CharacterRange > * ranges, CharacterClassStrings * strings, base::uc32 first_character) [private]
Definition at line 2822 of file regexp-parser.cc.
                                                        {
  DCHECK(unicode_sets());
  ZoneList<RegExpTree*>* operands =
      zone()->template New<ZoneList<RegExpTree*>>(2, zone());
  bool may_contain_strings = false;
  // Add the lhs to operands if necessary.
  // Either the lhs values were added to |ranges|/|strings| (in which case
  // |first_operand| is nullptr), or the lhs was evaluated to a tree and passed
  // as |first_operand| (in which case |ranges| and |strings| are empty).
  if (first_operand != nullptr) {
    may_contain_strings = MayContainStrings(first_operand_type, first_operand);
    operands->Add(first_operand, zone());
  }
  ClassSetOperandType last_type = first_operand_type;
  while (has_more() && current() != ']') {
    if (current() == '-') {
      // Mix of ClassSetRange and ClassSubtraction is not allowed.
      if (Next() == '-') {
        return ReportError(RegExpError::kInvalidClassSetOperation);
      }
      Advance();
      if (!has_more()) {
        // If we reach the end we break out of the loop and let the
        // following code report an error.
        break;
      }
      // If the lhs and rhs around '-' are both ClassSetCharacters, they
      // represent a character range.
      // In case one of them is not a ClassSetCharacter, it is a syntax error,
      // as '-' can not be used unescaped within a class with /v.
      // See
      // https://tc39.es/ecma262/#prod-ClassSetRange
      if (last_type != ClassSetOperandType::kClassSetCharacter) {
        return ReportError(RegExpError::kInvalidCharacterClass);
      }
      base::uc32 from = character;
      ParseClassSetOperand(builder, &last_type, ranges, strings,
                           &character CHECK_FAILED);
      if (last_type != ClassSetOperandType::kClassSetCharacter) {
        return ReportError(RegExpError::kInvalidCharacterClass);
      }
      if (from > character) {
        return ReportError(RegExpError::kOutOfOrderCharacterClass);
      }
      AddMaybeSimpleCaseFoldedRange(ranges,
                                    CharacterRange::Range(from, character));
      last_type = ClassSetOperandType::kClassSetRange;
    } else {
      DCHECK_NE(current(), '-');
      if (last_type == ClassSetOperandType::kClassSetCharacter) {
        AddMaybeSimpleCaseFoldedRange(ranges,
                                      CharacterRange::Singleton(character));
      }
      RegExpTree* operand = ParseClassSetOperand(
          builder, &last_type, ranges, strings, &character CHECK_FAILED);
      if (operand != nullptr) {
        may_contain_strings |= MayContainStrings(last_type, operand);
        // Add the range we started building as operand and reset the current
        // range.
        if (!ranges->is_empty() || !strings->empty()) {
          may_contain_strings |= !strings->empty();
          operands->Add(
              zone()->template New<RegExpClassSetOperand>(ranges, strings),
              zone());
          ranges = zone()->template New<ZoneList<CharacterRange>>(2, zone());
          strings = zone()->template New<CharacterClassStrings>(zone());
        }
        operands->Add(operand, zone());
      }
    }
  }
  if (!has_more()) {
    return ReportError(RegExpError::kUnterminatedCharacterClass);
  }
  if (last_type == ClassSetOperandType::kClassSetCharacter) {
    AddMaybeSimpleCaseFoldedRange(ranges, CharacterRange::Singleton(character));
  }
  // Add the range we started building as operand.
  if (!ranges->is_empty() || !strings->empty()) {
    may_contain_strings |= !strings->empty();
    operands->Add(zone()->template New<RegExpClassSetOperand>(ranges, strings),
                  zone());
  }
  DCHECK_EQ(current(), ']');
  Advance();
  if (is_negated && may_contain_strings) {
    return ReportError(RegExpError::kNegatedCharacterClassWithStrings);
  }
  if (operands->is_empty()) {
    // Return empty expression if no operands were added (e.g. [\P{Any}]
    // produces an empty range).
    DCHECK(ranges->is_empty());
    DCHECK(strings->empty());
    return RegExpClassSetExpression::Empty(zone(), is_negated);
  }
  return zone()->template New<RegExpClassSetExpression>(
      RegExpClassSetExpression::OperationType::kUnion, is_negated,
      may_contain_strings, operands);
}
References v8::internal::ZoneList< T >::Add(), v8::internal::character, CHECK_FAILED, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::RegExpClassSetExpression::Empty(), v8::internal::ZoneList< T >::is_empty(), v8::internal::anonymous_namespace{regexp-parser.cc}::kClassSetCharacter, v8::internal::anonymous_namespace{regexp-parser.cc}::kClassSetRange, v8::internal::RegExpClassSetExpression::kUnion, v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::MayContainStrings(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::CharacterRange::Range(), v8::internal::torque::ReportError(), and v8::internal::CharacterRange::Singleton().
ParseDisjunction()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction [private]
Definition at line 920 of file regexp-parser.cc.
                                                      {
  // Used to store current state while parsing subexpressions.
  RegExpParserState initial_state(nullptr, INITIAL, RegExpLookaround::LOOKAHEAD,
                                  0, nullptr, flags(), zone());
  RegExpParserState* state = &initial_state;
  // Cache the builder in a local variable for quick access.
  RegExpBuilder* builder = initial_state.builder();
  while (true) {
    switch (current()) {
      case kEndMarker:
        if (failed()) return nullptr; // E.g. the initial Advance failed.
        if (state->IsSubexpression()) {
          // Inside a parenthesized group when hitting end of input.
          return ReportError(RegExpError::kUnterminatedGroup);
        }
        DCHECK_EQ(INITIAL, state->group_type());
        // Parsing completed successfully.
        return builder->ToRegExp();
      case ')': {
        if (!state->IsSubexpression()) {
          return ReportError(RegExpError::kUnmatchedParen);
        }
        DCHECK_NE(INITIAL, state->group_type());
        Advance();
        // End disjunction parsing and convert builder content to new single
        // regexp atom.
        RegExpTree* body = builder->ToRegExp();
        int end_capture_index = captures_started();
        int capture_index = state->capture_index();
        SubexpressionType group_type = state->group_type();
        // Build result of subexpression.
        if (group_type == CAPTURE) {
          if (state->IsNamedCapture()) {
            CreateNamedCaptureAtIndex(state, capture_index CHECK_FAILED);
          }
          RegExpCapture* capture = GetCapture(capture_index);
          capture->set_body(body);
          body = capture;
        } else if (group_type == GROUPING) {
          body = zone()->template New<RegExpGroup>(body, builder->flags());
        } else {
          DCHECK(group_type == POSITIVE_LOOKAROUND ||
                 group_type == NEGATIVE_LOOKAROUND);
          bool is_positive = (group_type == POSITIVE_LOOKAROUND);
          body = zone()->template New<RegExpLookaround>(
              body, is_positive, end_capture_index - capture_index,
              capture_index, state->lookaround_type(), lookaround_count_);
          lookaround_count_++;
        }
        // Restore previous state.
        state = state->previous_state();
        builder = state->builder();
        builder->AddAtom(body);
        // For compatibility with JSC and ES3, we allow quantifiers after
        // lookaheads, and break in all cases.
        break;
      }
      case '|': {
        Advance();
        state->NewAlternative(captures_started());
        builder->NewAlternative();
        continue;
      }
      case '*':
      case '+':
      case '?':
        return ReportError(RegExpError::kNothingToRepeat);
      case '^': {
        Advance();
        builder->AddAssertion(zone()->template New<RegExpAssertion>(
            builder->multiline() ? RegExpAssertion::Type::START_OF_LINE
                                 : RegExpAssertion::Type::START_OF_INPUT));
        set_contains_anchor();
        continue;
      }
      case '$': {
        Advance();
        RegExpAssertion::Type assertion_type =
            builder->multiline() ? RegExpAssertion::Type::END_OF_LINE
                                 : RegExpAssertion::Type::END_OF_INPUT;
        builder->AddAssertion(
            zone()->template New<RegExpAssertion>(assertion_type));
        continue;
      }
      case '.': {
        Advance();
        ZoneList<CharacterRange>* ranges =
            zone()->template New<ZoneList<CharacterRange>>(2, zone());
        if (builder->dotall()) {
          // Everything.
          CharacterRange::AddClassEscape(StandardCharacterSet::kEverything,
                                         ranges, false, zone());
        } else {
          // Everything except \x0A, \x0D, \u2028 and \u2029.
          CharacterRange::AddClassEscape(
              StandardCharacterSet::kNotLineTerminator, ranges, false, zone());
        }
        RegExpClassRanges* cc =
            zone()->template New<RegExpClassRanges>(zone(), ranges);
        builder->AddClassRanges(cc);
        break;
      }
      case '(': {
        state = ParseOpenParenthesis(state CHECK_FAILED);
        builder = state->builder();
        flags_ = builder->flags();
        continue;
      }
      case '[': {
        RegExpTree* cc = ParseCharacterClass(builder CHECK_FAILED);
        if (cc->IsClassRanges()) {
          builder->AddClassRanges(cc->AsClassRanges());
        } else {
          DCHECK(cc->IsClassSetExpression());
          builder->AddTerm(cc);
        }
        break;
      }
      // Atom ::
      // \ AtomEscape
      case '\\':
        switch (Next()) {
          case kEndMarker:
            return ReportError(RegExpError::kEscapeAtEndOfPattern);
          // AtomEscape ::
          // [+UnicodeMode] DecimalEscape
          // [~UnicodeMode] DecimalEscape but only if the CapturingGroupNumber
          // of DecimalEscape is NcapturingParens
          // CharacterEscape (some cases of this mixed in too)
          //
          // TODO(jgruber): It may make sense to disentangle all the different
          // cases and make the structure mirror the spec, e.g. for AtomEscape:
          //
          // if (TryParseDecimalEscape(...)) return;
          // if (TryParseCharacterClassEscape(...)) return;
          // if (TryParseCharacterEscape(...)) return;
          // if (TryParseGroupName(...)) return;
          case '1':
          case '2':
          case '3':
          case '4':
          case '5':
          case '6':
          case '7':
          case '8':
          case '9': {
            int index = 0;
            const bool is_backref =
                ParseBackReferenceIndex(&index CHECK_FAILED);
            if (is_backref) {
              if (state->IsInsideCaptureGroup(index)) {
                // The back reference is inside the capture group it refers to.
                // Nothing can possibly have been captured yet, so we use empty
                // instead. This ensures that, when checking a back reference,
                // the capture registers of the referenced capture are either
                // both set or both cleared.
                builder->AddEmpty();
              } else {
                RegExpCapture* capture = GetCapture(index);
                RegExpTree* atom =
                    zone()->template New<RegExpBackReference>(capture, zone());
                builder->AddAtom(atom);
              }
              break;
            }
            // With /u and /v, no identity escapes except for syntax characters
            // are allowed. Otherwise, all identity escapes are allowed.
            if (IsUnicodeMode()) {
              return ReportError(RegExpError::kInvalidEscape);
            }
            base::uc32 first_digit = Next();
            if (first_digit == '8' || first_digit == '9') {
              builder->AddCharacter(first_digit);
              Advance(2);
              break;
            }
            [[fallthrough]];
          }
          case '0': {
            Advance();
            if (IsUnicodeMode() && Next() >= '0' && Next() <= '9') {
              // Decimal escape with leading 0 are not parsed as octal.
              return ReportError(RegExpError::kInvalidDecimalEscape);
            }
            base::uc32 octal = ParseOctalLiteral();
            builder->AddCharacter(octal);
            break;
          }
          case 'b':
            Advance(2);
            builder->AddAssertion(zone()->template New<RegExpAssertion>(
                RegExpAssertion::Type::BOUNDARY));
            continue;
          case 'B':
            Advance(2);
            builder->AddAssertion(zone()->template New<RegExpAssertion>(
                RegExpAssertion::Type::NON_BOUNDARY));
            continue;
          // AtomEscape ::
          // CharacterClassEscape
          case 'd':
          case 'D':
          case 's':
          case 'S':
          case 'w':
          case 'W': {
            base::uc32 next = Next();
            ZoneList<CharacterRange>* ranges =
                zone()->template New<ZoneList<CharacterRange>>(2, zone());
            bool add_unicode_case_equivalents =
                IsUnicodeMode() && ignore_case();
            bool parsed_character_class_escape = TryParseCharacterClassEscape(
                next, InClassEscapeState::kNotInClass, ranges, nullptr, zone(),
                add_unicode_case_equivalents CHECK_FAILED);
            if (parsed_character_class_escape) {
              RegExpClassRanges* cc =
                  zone()->template New<RegExpClassRanges>(zone(), ranges);
              builder->AddClassRanges(cc);
            } else {
              CHECK(!IsUnicodeMode());
              Advance(2);
              builder->AddCharacter(next); // IdentityEscape.
            }
            break;
          }
          case 'p':
          case 'P': {
            base::uc32 next = Next();
            ZoneList<CharacterRange>* ranges =
                zone()->template New<ZoneList<CharacterRange>>(2, zone());
            CharacterClassStrings* strings = nullptr;
            if (unicode_sets()) {
              strings = zone()->template New<CharacterClassStrings>(zone());
            }
            bool add_unicode_case_equivalents = ignore_case();
            bool parsed_character_class_escape = TryParseCharacterClassEscape(
                next, InClassEscapeState::kNotInClass, ranges, strings, zone(),
                add_unicode_case_equivalents CHECK_FAILED);
            if (parsed_character_class_escape) {
              if (unicode_sets()) {
                RegExpClassSetOperand* op =
                    zone()->template New<RegExpClassSetOperand>(ranges,
                                                                strings);
                builder->AddTerm(op);
              } else {
                RegExpClassRanges* cc =
                    zone()->template New<RegExpClassRanges>(zone(), ranges);
                builder->AddClassRanges(cc);
              }
            } else {
              CHECK(!IsUnicodeMode());
              Advance(2);
              builder->AddCharacter(next); // IdentityEscape.
            }
            break;
          }
          // AtomEscape ::
          // k GroupName
          case 'k': {
            // Either an identity escape or a named back-reference. The two
            // interpretations are mutually exclusive: '\k' is interpreted as
            // an identity escape for non-Unicode patterns without named
            // capture groups, and as the beginning of a named back-reference
            // in all other cases.
            const bool has_named_captures =
                HasNamedCaptures(InClassEscapeState::kNotInClass CHECK_FAILED);
            if (IsUnicodeMode() || has_named_captures) {
              Advance(2);
              ParseNamedBackReference(builder, state CHECK_FAILED);
              break;
            }
          }
            [[fallthrough]];
          // AtomEscape ::
          // CharacterEscape
          default: {
            bool is_escaped_unicode_character = false;
            base::uc32 c = ParseCharacterEscape(
                InClassEscapeState::kNotInClass,
                &is_escaped_unicode_character CHECK_FAILED);
            if (is_escaped_unicode_character) {
              builder->AddEscapedUnicodeCharacter(c);
            } else {
              builder->AddCharacter(c);
            }
            break;
          }
        }
        break;
      case '{': {
        int dummy;
        bool parsed = ParseIntervalQuantifier(&dummy, &dummy CHECK_FAILED);
        if (parsed) return ReportError(RegExpError::kNothingToRepeat);
        [[fallthrough]];
      }
      case '}':
      case ']':
        if (IsUnicodeMode()) {
          return ReportError(RegExpError::kLoneQuantifierBrackets);
        }
        [[fallthrough]];
      default:
        builder->AddUnicodeCharacter(current());
        Advance();
        break;
    } // end switch(current())
    int min;
    int max;
    switch (current()) {
      // QuantifierPrefix ::
      // *
      // +
      // ?
      // {
      case '*':
        min = 0;
        max = RegExpTree::kInfinity;
        Advance();
        break;
      case '+':
        min = 1;
        max = RegExpTree::kInfinity;
        Advance();
        break;
      case '?':
        min = 0;
        max = 1;
        Advance();
        break;
      case '{':
        if (ParseIntervalQuantifier(&min, &max)) {
          if (max < min) {
            return ReportError(RegExpError::kRangeOutOfOrder);
          }
          break;
        } else if (IsUnicodeMode()) {
          // Incomplete quantifiers are not allowed.
          return ReportError(RegExpError::kIncompleteQuantifier);
        }
        continue;
      default:
        continue;
    }
    RegExpQuantifier::QuantifierType quantifier_type = RegExpQuantifier::GREEDY;
    if (current() == '?') {
      quantifier_type = RegExpQuantifier::NON_GREEDY;
      Advance();
    } else if (v8_flags.regexp_possessive_quantifier && current() == '+') {
      // v8_flags.regexp_possessive_quantifier is a debug-only flag.
      quantifier_type = RegExpQuantifier::POSSESSIVE;
      Advance();
    }
    if (!builder->AddQuantifierToAtom(min, max, quantifier_count_,
                                      quantifier_type)) {
      return ReportError(RegExpError::kInvalidQuantifier);
    }
    ++quantifier_count_;
  }
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAssertion(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAtom(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddCharacter(), v8::internal::CharacterRange::AddClassEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddClassRanges(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddEmpty(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddEscapedUnicodeCharacter(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddQuantifierToAtom(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddTerm(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddUnicodeCharacter(), v8::internal::RegExpAssertion::BOUNDARY, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::builder(), v8::internal::anonymous_namespace{regexp-parser.cc}::CAPTURE, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::capture_index(), v8::internal::cc, CHECK, CHECK_FAILED, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::dotall(), v8::internal::RegExpAssertion::END_OF_INPUT, v8::internal::RegExpAssertion::END_OF_LINE, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::flags(), v8::internal::flags, v8::internal::RegExpQuantifier::GREEDY, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::group_type(), v8::internal::anonymous_namespace{regexp-parser.cc}::GROUPING, v8::internal::index, v8::internal::anonymous_namespace{regexp-parser.cc}::INITIAL, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::IsInsideCaptureGroup(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::IsNamedCapture(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::IsSubexpression(), v8::internal::kEverything, v8::internal::RegExpTree::kInfinity, v8::internal::anonymous_namespace{regexp-parser.cc}::kNotInClass, v8::internal::kNotLineTerminator, v8::internal::RegExpLookaround::LOOKAHEAD, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::lookaround_type(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::multiline(), v8::internal::anonymous_namespace{regexp-parser.cc}::NEGATIVE_LOOKAROUND, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::NewAlternative(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::NewAlternative(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::RegExpAssertion::NON_BOUNDARY, v8::internal::RegExpQuantifier::NON_GREEDY, v8::internal::anonymous_namespace{regexp-parser.cc}::POSITIVE_LOOKAROUND, v8::internal::RegExpQuantifier::POSSESSIVE, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::previous_state(), v8::internal::torque::ReportError(), v8::internal::RegExpCapture::set_body(), v8::internal::RegExpAssertion::START_OF_INPUT, v8::internal::RegExpAssertion::START_OF_LINE, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::ToRegExp(), and v8::internal::v8_flags.
ParseGroup()
template<class CharT >
RegExpTree* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseGroup () [private]
ParseHexEscape()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseHexEscape (int length, base::uc32 * value) [private]
Definition at line 1874 of file regexp-parser.cc.
                                                                        {
  int start = position();
  base::uc32 val = 0;
  for (int i = 0; i < length; ++i) {
    base::uc32 c = current();
    int d = base::HexValue(c);
    if (d < 0) {
      Reset(start);
      return false;
    }
    val = val * 16 + d;
    Advance();
  }
  *value = val;
  return true;
}
References v8::base::HexValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and v8::internal::value.
ParseIntervalQuantifier()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseIntervalQuantifier (int * min_out, int * max_out) [private]
Definition at line 1794 of file regexp-parser.cc.
                                                                    {
  DCHECK_EQ(current(), '{');
  int start = position();
  Advance();
  int min = 0;
  if (!IsDecimalDigit(current())) {
    Reset(start);
    return false;
  }
  while (IsDecimalDigit(current())) {
    int next = current() - '0';
    if (min > (RegExpTree::kInfinity - next) / 10) {
      // Overflow. Skip past remaining decimal digits and return -1.
      do {
        Advance();
      } while (IsDecimalDigit(current()));
      min = RegExpTree::kInfinity;
      break;
    }
    min = 10 * min + next;
    Advance();
  }
  int max = 0;
  if (current() == '}') {
    max = min;
    Advance();
  } else if (current() == ',') {
    Advance();
    if (current() == '}') {
      max = RegExpTree::kInfinity;
      Advance();
    } else {
      while (IsDecimalDigit(current())) {
        int next = current() - '0';
        if (max > (RegExpTree::kInfinity - next) / 10) {
          do {
            Advance();
          } while (IsDecimalDigit(current()));
          max = RegExpTree::kInfinity;
          break;
        }
        max = 10 * max + next;
        Advance();
      }
      if (current() != '}') {
        Reset(start);
        return false;
      }
      Advance();
    }
  } else {
    Reset(start);
    return false;
  }
  *min_out = min;
  *max_out = max;
  return true;
}
References DCHECK_EQ, v8::internal::IsDecimalDigit(), and v8::internal::RegExpTree::kInfinity.
ParseNamedBackReference()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseNamedBackReference (RegExpBuilder * builder, RegExpParserState * state) [private]
Definition at line 1668 of file regexp-parser.cc.
                                                      {
  // The parser is assumed to be on the '<' in \k<name>.
  if (current() != '<') {
    ReportError(RegExpError::kInvalidNamedReference);
    return false;
  }
  Advance();
  const ZoneVector<base::uc16>* name = ParseCaptureGroupName();
  if (name == nullptr) {
    return false;
  }
  if (state->IsInsideCaptureGroup(name)) {
    builder->AddEmpty();
  } else {
    RegExpBackReference* atom =
        zone()->template New<RegExpBackReference>(zone());
    atom->set_name(name);
    builder->AddAtom(atom);
    if (named_back_references_ == nullptr) {
      named_back_references_ =
          zone()->template New<ZoneList<RegExpBackReference*>>(1, zone());
    }
    named_back_references_->Add(atom, zone());
  }
  return true;
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAtom(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddEmpty(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::IsInsideCaptureGroup(), v8::internal::name, v8::internal::torque::ReportError(), and v8::internal::RegExpBackReference::set_name().
ParseOctalLiteral()
template<class CharT >
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseOctalLiteral [private]
Definition at line 1855 of file regexp-parser.cc.
                                                    {
  DCHECK(('0' <= current() && current() <= '7') || !has_more());
  // For compatibility with some other browsers (not all), we parse
  // up to three octal digits with a value below 256.
  // ES#prod-annexB-LegacyOctalEscapeSequence
  base::uc32 value = current() - '0';
  Advance();
  if ('0' <= current() && current() <= '7') {
    value = value * 8 + current() - '0';
    Advance();
    if (value < 32 && '0' <= current() && current() <= '7') {
      value = value * 8 + current() - '0';
      Advance();
    }
  }
  return value;
}
References v8::internal::DCHECK(), and v8::internal::value.
ParseOpenParenthesis()
template<class CharT >
RegExpParserState * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseOpenParenthesis (RegExpParserState * state) [private]
Definition at line 1292 of file regexp-parser.cc.
                              {
  RegExpLookaround::Type lookaround_type = state->lookaround_type();
  bool is_named_capture = false;
  const ZoneVector<base::uc16>* capture_name = nullptr;
  SubexpressionType subexpr_type = CAPTURE;
  RegExpFlags flags = state->builder()->flags();
  bool parsing_modifiers = false;
  bool modifiers_polarity = true;
  RegExpFlags modifiers;
  Advance();
  if (current() == '?') {
    do {
      base::uc32 next = Next();
      switch (next) {
        case '-':
          if (!v8_flags.js_regexp_modifiers) {
            ReportError(RegExpError::kInvalidGroup);
            return nullptr;
          }
          Advance();
          parsing_modifiers = true;
          if (modifiers_polarity == false) {
            ReportError(RegExpError::kMultipleFlagDashes);
            return nullptr;
          }
          modifiers_polarity = false;
          break;
        case 'm':
        case 'i':
        case 's': {
          if (!v8_flags.js_regexp_modifiers) {
            ReportError(RegExpError::kInvalidGroup);
            return nullptr;
          }
          Advance();
          parsing_modifiers = true;
          RegExpFlag flag = TryRegExpFlagFromChar(next).value();
          if ((modifiers & flag) != 0) {
            ReportError(RegExpError::kRepeatedFlag);
            return nullptr;
          }
          modifiers |= flag;
          flags.set(flag, modifiers_polarity);
          break;
        }
        case ':':
          Advance(2);
          parsing_modifiers = false;
          subexpr_type = GROUPING;
          break;
        case '=':
          Advance(2);
          if (parsing_modifiers) {
            DCHECK(v8_flags.js_regexp_modifiers);
            ReportError(RegExpError::kInvalidGroup);
            return nullptr;
          }
          lookaround_type = RegExpLookaround::LOOKAHEAD;
          subexpr_type = POSITIVE_LOOKAROUND;
          break;
        case '!':
          Advance(2);
          if (parsing_modifiers) {
            DCHECK(v8_flags.js_regexp_modifiers);
            ReportError(RegExpError::kInvalidGroup);
            return nullptr;
          }
          lookaround_type = RegExpLookaround::LOOKAHEAD;
          subexpr_type = NEGATIVE_LOOKAROUND;
          break;
        case '<':
          Advance();
          if (parsing_modifiers) {
            DCHECK(v8_flags.js_regexp_modifiers);
            ReportError(RegExpError::kInvalidGroup);
            return nullptr;
          }
          if (Next() == '=') {
            Advance(2);
            lookaround_type = RegExpLookaround::LOOKBEHIND;
            subexpr_type = POSITIVE_LOOKAROUND;
            break;
          } else if (Next() == '!') {
            Advance(2);
            lookaround_type = RegExpLookaround::LOOKBEHIND;
            subexpr_type = NEGATIVE_LOOKAROUND;
            break;
          }
          is_named_capture = true;
          has_named_captures_ = true;
          Advance();
          break;
        default:
          ReportError(RegExpError::kInvalidGroup);
          return nullptr;
      }
    } while (parsing_modifiers);
  }
  if (modifiers_polarity == false) {
    // We encountered a dash.
    if (modifiers == 0) {
      ReportError(RegExpError::kInvalidFlagGroup);
      return nullptr;
    }
  }
  if (subexpr_type == CAPTURE) {
    if (captures_started_ >= RegExpMacroAssembler::kMaxCaptures) {
      ReportError(RegExpError::kTooManyCaptures);
      return nullptr;
    }
    captures_started_++;
    if (is_named_capture) {
      capture_name = ParseCaptureGroupName(CHECK_FAILED);
    }
  }
  // Store current state and begin new disjunction parsing.
  return zone()->template New<RegExpParserState>(
      state, subexpr_type, lookaround_type, captures_started_, capture_name,
      flags, zone());
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::builder(), v8::internal::anonymous_namespace{regexp-parser.cc}::CAPTURE, CHECK_FAILED, v8::internal::DCHECK(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::flags(), v8::internal::flags, v8::internal::anonymous_namespace{regexp-parser.cc}::GROUPING, v8::internal::RegExpMacroAssembler::kMaxCaptures, v8::internal::RegExpLookaround::LOOKAHEAD, v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::lookaround_type(), v8::internal::RegExpLookaround::LOOKBEHIND, v8::internal::anonymous_namespace{regexp-parser.cc}::NEGATIVE_LOOKAROUND, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::anonymous_namespace{regexp-parser.cc}::POSITIVE_LOOKAROUND, v8::internal::torque::ReportError(), v8::internal::TryRegExpFlagFromChar(), and v8::internal::v8_flags.
ParsePattern()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParsePattern [private]
Definition at line 897 of file regexp-parser.cc.
                                                  {
  RegExpTree* result = ParseDisjunction(CHECK_FAILED);
  PatchNamedBackReferences(CHECK_FAILED);
  DCHECK(!has_more());
  // If the result of parsing is a literal string atom, and it has the
  // same length as the input, then the atom is identical to the input.
  if (result->IsAtom() && result->AsAtom()->length() == input_length()) {
    simple_ = true;
  }
  return result;
}
References CHECK_FAILED, v8::internal::DCHECK(), and v8::base::internal::result.
ParsePropertyClassName()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParsePropertyClassName (ZoneVector< char > * name_1, ZoneVector< char > * name_2) [private]
Definition at line 2272 of file regexp-parser.cc.
                                                                               {
  return false;
}
ParseUnicodeEscape()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseUnicodeEscape (base::uc32 * value) [private]
Definition at line 1893 of file regexp-parser.cc.
                                                                {
  // Accept both \uxxxx and \u{xxxxxx} (if harmony unicode escapes are
  // allowed). In the latter case, the number of hex digits between { } is
  // arbitrary. \ and u have already been read.
  if (current() == '{' && IsUnicodeMode()) {
    int start = position();
    Advance();
    if (ParseUnlimitedLengthHexNumber(0x10FFFF, value)) {
      if (current() == '}') {
        Advance();
        return true;
      }
    }
    Reset(start);
    return false;
  }
  // \u but no {, or \u{...} escapes not allowed.
  bool result = ParseHexEscape(4, value);
  if (result && IsUnicodeMode() && unibrow::Utf16::IsLeadSurrogate(*value) &&
      current() == '\\') {
    // Attempt to read trail surrogate.
    int start = position();
    if (Next() == 'u') {
      Advance(2);
      base::uc32 trail;
      if (ParseHexEscape(4, &trail) &&
          unibrow::Utf16::IsTrailSurrogate(trail)) {
        *value = unibrow::Utf16::CombineSurrogatePair(
            static_cast<base::uc16>(*value), static_cast<base::uc16>(trail));
        return true;
      }
    }
    Reset(start);
  }
  return result;
}
References unibrow::Utf16::CombineSurrogatePair(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsTrailSurrogate(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::base::internal::result, and v8::internal::value.
ParseUnlimitedLengthHexNumber()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseUnlimitedLengthHexNumber (int max_value, base::uc32 * value) [private]
Definition at line 2288 of file regexp-parser.cc.
                                                                             {
  base::uc32 x = 0;
  int d = base::HexValue(current());
  if (d < 0) {
    return false;
  }
  while (d >= 0) {
    x = x * 16 + d;
    if (x > static_cast<base::uc32>(max_value)) {
      return false;
    }
    Advance();
    d = base::HexValue(current());
  }
  *value = x;
  return true;
}
References v8::base::HexValue(), and v8::internal::value.
PatchNamedBackReferences()
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::PatchNamedBackReferences [private]
Definition at line 1702 of file regexp-parser.cc.
                                                       {
  if (named_back_references_ == nullptr) return;
  if (named_captures_ == nullptr) {
    ReportError(RegExpError::kInvalidNamedCaptureReference);
    return;
  }
  // Look up and patch the actual capture for each named back reference.
  for (int i = 0; i < named_back_references_->length(); i++) {
    RegExpBackReference* ref = named_back_references_->at(i);
    // Capture used to search the named_captures_ by name, index of the
    // capture is never used.
    static const int kInvalidIndex = 0;
    RegExpCapture* search_capture =
        zone()->template New<RegExpCapture>(kInvalidIndex);
    DCHECK_NULL(search_capture->name());
    search_capture->set_name(ref->name());
    const auto& capture_it = named_captures_->find(search_capture);
    if (capture_it == named_captures_->end()) {
      ReportError(RegExpError::kInvalidNamedCaptureReference);
      return;
    }
    DCHECK_IMPLIES(!v8_flags.js_regexp_duplicate_named_groups,
                   capture_it->second->length() == 1);
    for (int index : *capture_it->second) {
      ref->add_capture(GetCapture(index), zone());
    }
  }
}
References v8::internal::RegExpBackReference::add_capture(), DCHECK_IMPLIES, DCHECK_NULL, v8::internal::index, v8::internal::trap_handler::kInvalidIndex, v8::internal::RegExpCapture::name(), v8::internal::RegExpBackReference::name(), v8::internal::torque::ReportError(), v8::internal::RegExpCapture::set_name(), and v8::internal::v8_flags.
position()
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::position () const [inline], [private]
Definition at line 539 of file regexp-parser.cc.
                       {
    const bool current_is_surrogate =
        current() != kEndMarker &&
        current() > unibrow::Utf16::kMaxNonSurrogateCharCode;
    const int rewind_bytes = current_is_surrogate ? 2 : 1;
    return next_pos_ - rewind_bytes;
  }
References unibrow::Utf16::kMaxNonSurrogateCharCode.
ReadNext() [1/3]
template<class CharT >
template<bool update_position>
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ReadNext () [private]
ReadNext() [2/3]
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< uint8_t >::ReadNext () [inline], [private]
Definition at line 689 of file regexp-parser.cc.
                                                    {
  int position = next_pos_;
  base::uc16 c0 = InputAt(position);
  position++;
  DCHECK(!unibrow::Utf16::IsLeadSurrogate(c0));
  if (update_position) next_pos_ = position;
  return c0;
}
References v8::internal::DCHECK(), and unibrow::Utf16::IsLeadSurrogate().
ReadNext() [3/3]
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< base::uc16 >::ReadNext () [inline], [private]
Definition at line 700 of file regexp-parser.cc.
                                                     {
  int position = next_pos_;
  base::uc16 c0 = InputAt(position);
  base::uc32 result = c0;
  position++;
  // Read the whole surrogate pair in case of unicode mode, if possible.
  if (IsUnicodeMode() && position < input_length() &&
      unibrow::Utf16::IsLeadSurrogate(c0)) {
    base::uc16 c1 = InputAt(position);
    if (unibrow::Utf16::IsTrailSurrogate(c1)) {
      result = unibrow::Utf16::CombineSurrogatePair(c0, c1);
      position++;
    }
  }
  if (update_position) next_pos_ = position;
  return result;
}
References unibrow::Utf16::CombineSurrogatePair(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsTrailSurrogate(), and v8::base::internal::result.
ReportError()
template<class CharT >
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ReportError (RegExpError error) [private]
Definition at line 878 of file regexp-parser.cc.
                                                                  {
  if (failed_) return nullptr; // Do not overwrite any existing error.
  failed_ = true;
  error_ = error;
  error_pos_ = position();
  // Zip to the end to make sure no more input is read.
  current_ = kEndMarker;
  next_pos_ = input_length();
  has_more_ = false;
  return nullptr;
}
Reset()
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::Reset (int pos) [private]
Definition at line 759 of file regexp-parser.cc.
                                           {
  next_pos_ = pos;
  has_more_ = (pos < input_length());
  Advance();
}
RewindByOneCodepoint()
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::RewindByOneCodepoint [private]
Definition at line 748 of file regexp-parser.cc.
                                                   {
  if (!has_more()) return;
  // Rewinds by one code point, i.e.: two code units if `current` is outside
  // the basic multilingual plane (= composed of a lead and trail surrogate),
  // or one code unit otherwise.
  const int rewind_by =
      current() > unibrow::Utf16::kMaxNonSurrogateCharCode ? -2 : -1;
  Advance(rewind_by); // Undo the last Advance.
}
References unibrow::Utf16::kMaxNonSurrogateCharCode.
ScanForCaptures()
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ScanForCaptures (InClassEscapeState in_class_escape_state) [private]
Definition at line 1426 of file regexp-parser.cc.
                                              {
  DCHECK(!is_scanned_for_captures_);
  const int saved_position = position();
  // Start with captures started previous to current position
  int capture_count = captures_started();
  // When we start inside a character class, skip everything inside the class.
  if (in_class_escape_state == InClassEscapeState::kInClass) {
    // \k is always invalid within a class in unicode mode, thus we should never
    // call ScanForCaptures within a class.
    DCHECK(!IsUnicodeMode());
    int c;
    while ((c = current()) != kEndMarker) {
      Advance();
      if (c == '\\') {
        Advance();
      } else {
        if (c == ']') break;
      }
    }
  }
  // Add count of captures after this position.
  int n;
  while ((n = current()) != kEndMarker) {
    Advance();
    switch (n) {
      case '\\':
        Advance();
        break;
      case '[': {
        int class_nest_level = 0;
        int c;
        while ((c = current()) != kEndMarker) {
          Advance();
          if (c == '\\') {
            Advance();
          } else if (c == '[') {
            // With /v, '[' inside a class is treated as a nested class.
            // Without /v, '[' is a normal character.
            if (unicode_sets()) class_nest_level++;
          } else if (c == ']') {
            if (class_nest_level == 0) break;
            class_nest_level--;
          }
        }
        break;
      }
      case '(':
        if (current() == '?') {
          // At this point we could be in
          // * a non-capturing group '(:',
          // * a lookbehind assertion '(?<=' '(?<!'
          // * or a named capture '(?<'.
          //
          // Of these, only named captures are capturing groups.
          Advance();
          if (current() != '<') break;
          Advance();
          if (current() == '=' || current() == '!') break;
          // Found a possible named capture. It could turn out to be a syntax
          // error (e.g. an unterminated or invalid name), but that distinction
          // does not matter for our purposes.
          has_named_captures_ = true;
        }
        capture_count++;
        break;
    }
  }
  capture_count_ = capture_count;
  is_scanned_for_captures_ = true;
  Reset(saved_position);
}
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{regexp-parser.cc}::kInClass.
set_contains_anchor()
template<class CharT >
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::set_contains_anchor () [inline], [private]
Definition at line 537 of file regexp-parser.cc.
{ contains_anchor_ = true; }
simple()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::simple () const [inline], [private]
Definition at line 535 of file regexp-parser.cc.
{ return simple_; }
TryParseCharacterClassEscape()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::TryParseCharacterClassEscape (base::uc32 next, InClassEscapeState in_class_escape_state, ZoneList< CharacterRange > * ranges, CharacterClassStrings * strings, Zone * zone, bool add_unicode_case_equivalents) [private]
Definition at line 2566 of file regexp-parser.cc.
                                                   {
  DCHECK_EQ(current(), '\\');
  DCHECK_EQ(Next(), next);
  switch (next) {
    case 'd':
    case 'D':
    case 's':
    case 'S':
    case 'w':
    case 'W':
      CharacterRange::AddClassEscape(static_cast<StandardCharacterSet>(next),
                                     ranges, add_unicode_case_equivalents,
                                     zone);
      Advance(2);
      return true;
    case 'p':
    case 'P': {
      if (!IsUnicodeMode()) return false;
      bool negate = next == 'P';
      Advance(2);
      ZoneVector<char> name_1(zone);
      ZoneVector<char> name_2(zone);
      if (!ParsePropertyClassName(&name_1, &name_2) ||
          !AddPropertyClassRange(ranges, strings, negate, name_1, name_2)) {
        ReportError(in_class_escape_state == InClassEscapeState::kInClass
                        ? RegExpError::kInvalidClassPropertyName
                        : RegExpError::kInvalidPropertyName);
      }
      return true;
    }
    default:
      return false;
  }
}
References v8::internal::CharacterRange::AddClassEscape(), DCHECK_EQ, v8::internal::anonymous_namespace{regexp-parser.cc}::kInClass, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), and v8::internal::torque::ReportError().
unicode_sets()
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::unicode_sets () const [inline], [private]
Definition at line 553 of file regexp-parser.cc.
{ return IsUnicodeSets(flags()); }
References v8::internal::flags.
zone()
template<class CharT >
Zone* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::zone () const [inline], [private]
Definition at line 591 of file regexp-parser.cc.
{ return zone_; }
Friends And Related Function Documentation
v8::internal::RegExpParser
template<class CharT >
friend class v8::internal::RegExpParser [friend]
Definition at line 657 of file regexp-parser.cc.
Member Data Documentation
capture_count_
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::capture_count_ [private]
Definition at line 646 of file regexp-parser.cc.
captures_
template<class CharT >
ZoneList<RegExpCapture*>* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::captures_ [private]
Definition at line 634 of file regexp-parser.cc.
captures_started_
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::captures_started_ [private]
Definition at line 645 of file regexp-parser.cc.
contains_anchor_
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::contains_anchor_ [private]
Definition at line 651 of file regexp-parser.cc.
current_
template<class CharT >
base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::current_ [private]
Definition at line 641 of file regexp-parser.cc.
error_
template<class CharT >
RegExpError v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::error_ = RegExpError::kNone [private]
Definition at line 632 of file regexp-parser.cc.
error_pos_
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::error_pos_ = 0 [private]
Definition at line 633 of file regexp-parser.cc.
failed_
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::failed_ [private]
Definition at line 654 of file regexp-parser.cc.
flags_
template<class CharT >
RegExpFlags v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::flags_ [private]
Definition at line 642 of file regexp-parser.cc.
force_unicode_
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::force_unicode_ = false [private]
Definition at line 643 of file regexp-parser.cc.
has_more_
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::has_more_ [private]
Definition at line 649 of file regexp-parser.cc.
has_named_captures_
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::has_named_captures_ [private]
Definition at line 653 of file regexp-parser.cc.
input_
template<class CharT >
const CharT* const v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::input_ [private]
Definition at line 639 of file regexp-parser.cc.
input_length_
template<class CharT >
const int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::input_length_ [private]
Definition at line 640 of file regexp-parser.cc.
is_scanned_for_captures_
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::is_scanned_for_captures_ [private]
Definition at line 652 of file regexp-parser.cc.
kEndMarker
template<class CharT >
const base::uc32 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::kEndMarker = (1 << 21) [static], [private]
Definition at line 561 of file regexp-parser.cc.
lookaround_count_
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::lookaround_count_ [private]
Definition at line 648 of file regexp-parser.cc.
named_back_references_
template<class CharT >
ZoneList<RegExpBackReference*>* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::named_back_references_ [private]
Definition at line 638 of file regexp-parser.cc.
named_captures_
template<class CharT >
ZoneMap<RegExpCapture*, ZoneList<int>*, RegExpCaptureNameLess>* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::named_captures_ [private]
Definition at line 637 of file regexp-parser.cc.
next_pos_
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::next_pos_ [private]
Definition at line 644 of file regexp-parser.cc.
no_gc_
template<class CharT >
const DisallowGarbageCollection v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::no_gc_ [private]
Definition at line 630 of file regexp-parser.cc.
quantifier_count_
template<class CharT >
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::quantifier_count_ [private]
Definition at line 647 of file regexp-parser.cc.
simple_
template<class CharT >
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::simple_ [private]
Definition at line 650 of file regexp-parser.cc.
stack_limit_
template<class CharT >
const uintptr_t v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::stack_limit_ [private]
Definition at line 655 of file regexp-parser.cc.
zone_
template<class CharT >
Zone* const v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::zone_ [private]
Definition at line 631 of file regexp-parser.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-parser.cc