v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer Class Reference
Public Member Functions
FFTContainer (int n, int K, ProcessorImpl *processor)
FFTContainer ()=delete
FFTContainer (const FFTContainer &)=delete
FFTContainer & operator= (const FFTContainer &)=delete
~FFTContainer ()
void Start_Default (Digits X, int chunk_size, int theta, int omega)
void Start (Digits X, int chunk_size, int theta, int omega)
void NormalizeAndRecombine (int omega, int m, RWDigits Z, int chunk_size)
void CounterWeightAndRecombine (int theta, int m, RWDigits Z, int chunk_size)
void FFT_ReturnShuffledThreadsafe (int start, int len, int omega, digit_t *temp)
void FFT_Recurse (int start, int half, int omega, digit_t *temp)
void BackwardFFT (int start, int len, int omega)
void BackwardFFT_Threadsafe (int start, int len, int omega, digit_t *temp)
void PointwiseMultiply (const FFTContainer &other)
void DoPointwiseMultiplication (const FFTContainer &other, int start, int end, digit_t *temp)
int length () const
Private Attributes
const int n_
const int K_
const int length_
ProcessorImpl * processor_
digit_t * storage_
digit_t ** part_
digit_t * temp_
Detailed Description
Definition at line 427 of file mul-fft.cc.
Constructor & Destructor Documentation
FFTContainer() [1/3]
v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::FFTContainer (int n, int K, ProcessorImpl * processor) [inline]
Definition at line 431 of file mul-fft.cc.
      : n_(n), K_(K), length_(K + 1), processor_(processor) {
    storage_ = new digit_t[length_ * n_];
    part_ = new digit_t*[n_];
    digit_t* ptr = storage_;
    for (int i = 0; i < n; i++, ptr += length_) {
      part_[i] = ptr;
    }
    temp_ = new digit_t[length_ * 2];
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
FFTContainer() [2/3]
v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::FFTContainer () [delete]
FFTContainer() [3/3]
v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::FFTContainer (const FFTContainer &) [delete]
 FFTContainer()
v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::~FFTContainer () [inline]
Definition at line 445 of file mul-fft.cc.
                  {
    delete[] storage_;
    delete[] part_;
    delete[] temp_;
  }
Member Function Documentation
BackwardFFT()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::BackwardFFT (int start, int len, int omega)
Definition at line 588 of file mul-fft.cc.
                                                            {
  BackwardFFT_Threadsafe(start, len, omega, temp_);
}
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::MultiplyFFT_Inner().
BackwardFFT_Threadsafe()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::BackwardFFT_Threadsafe (int start, int len, int omega, digit_t * temp)
Definition at line 592 of file mul-fft.cc.
                                                         {
  DCHECK((len & 1) == 0); // {len} must be even.
  int half = len / 2;
  // Don't recurse for half == 2, as PointwiseMultiply already performed
  // the first level of the backwards FFT.
  if (half > 2) {
    BackwardFFT_Threadsafe(start, half, 2 * omega, temp);
    BackwardFFT_Threadsafe(start + half, half, 2 * omega, temp);
  }
  SumDiff(part_[start], part_[start + half], part_[start], part_[start + half],
          length_);
  for (int k = 1; k < half; k++) {
    int w = omega * (len - k);
    ShiftModFn(temp, part_[start + half + k], w, K_);
    SumDiff(part_[start + k], part_[start + half + k], part_[start + k], temp,
            length_);
  }
}
References DCHECK, v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), and v8::bigint::anonymous_namespace{mul-fft.cc}::SumDiff().
CounterWeightAndRecombine()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine (int theta, int m, RWDigits Z, int chunk_size)
Definition at line 649 of file mul-fft.cc.
                                                    {
  Z.Clear();
  int z_index = 0;
  for (int k = 0; k < n_; k++, z_index += s) {
    int shift = -theta * k - m;
    if (shift < 0) shift += 2 * n_ * theta;
    DCHECK(shift >= 0);
    digit_t* input = part_[k];
    ShiftModFn(temp_, input, shift, K_);
    int remaining_z = Z.len() - z_index;
    if (ShouldBeNegative(temp_, length_, k + 1, s)) {
      // Subtract F_n from input before adding to result. We use the following
      // transformation (knowing that X < F_n):
      // Z + (X - F_n) == Z - (F_n - X)
      digit_t borrow_z = 0;
      digit_t borrow_Fn = 0;
      {
        // i == 0:
        digit_t d = digit_sub(1, temp_[0], &borrow_Fn);
        Z[z_index] = digit_sub(Z[z_index], d, &borrow_z);
      }
      int i = 1;
      for (; i < K_ && i < remaining_z; i++) {
        digit_t d = digit_sub2(0, temp_[i], borrow_Fn, &borrow_Fn);
        Z[z_index + i] = digit_sub2(Z[z_index + i], d, borrow_z, &borrow_z);
      }
      DCHECK(i == K_ && K_ == length_ - 1);
      for (; i < length_ && i < remaining_z; i++) {
        digit_t d = digit_sub2(1, temp_[i], borrow_Fn, &borrow_Fn);
        Z[z_index + i] = digit_sub2(Z[z_index + i], d, borrow_z, &borrow_z);
      }
      DCHECK(borrow_Fn == 0);
      for (; borrow_z > 0 && i < remaining_z; i++) {
        Z[z_index + i] = digit_sub(Z[z_index + i], borrow_z, &borrow_z);
      }
    } else {
      digit_t carry = 0;
      int i = 0;
      for (; i < length_ && i < remaining_z; i++) {
        Z[z_index + i] = digit_add3(Z[z_index + i], temp_[i], carry, &carry);
      }
      for (; i < length_; i++) {
        DCHECK(temp_[i] == 0);
      }
      for (; carry > 0 && i < remaining_z; i++) {
        Z[z_index + i] = digit_add2(Z[z_index + i], carry, &carry);
      }
      // {carry} might be != 0 here if Z was negative before. That's fine.
    }
  }
}
References v8::internal::carry, v8::bigint::RWDigits::Clear(), DCHECK, v8::bigint::digit_add2(), v8::bigint::digit_add3(), v8::bigint::digit_sub(), v8::bigint::digit_sub2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), and v8::bigint::anonymous_namespace{mul-fft.cc}::ShouldBeNegative().
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::MultiplyFFT_Inner().
DoPointwiseMultiplication()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::DoPointwiseMultiplication (const FFTContainer & other, int start, int end, digit_t * temp)
Definition at line 723 of file mul-fft.cc.
                                                            {
  // The (K_ & 3) != 0 condition makes sure that the inner FFT gets
  // to split the work into at least 4 chunks.
  bool use_fft = length_ >= kFftInnerThreshold && (K_ & 3) == 0;
  Parameters params;
  if (use_fft) ComputeParameters_Inner(K_, &params);
  RWDigits result(temp, 2 * length_);
  for (int i = start; i < end; i++) {
    Digits A(part_[i], length_);
    Digits B(other.part_[i], length_);
    if (use_fft) {
      MultiplyFFT_Inner(result, A, B, params, processor_);
    } else {
      processor_->Multiply(result, A, B);
    }
    if (processor_->should_terminate()) return;
    ModFnDoubleWidth(part_[i], result.digits(), length_);
    // To improve cache friendliness, we perform the first level of the
    // backwards FFT here.
    if ((i & 1) == 1) {
      SumDiff(part_[i - 1], part_[i], part_[i - 1], part_[i], length_);
    }
  }
}
References v8::internal::A, v8::internal::B, v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters_Inner(), v8::internal::compiler::end(), v8::bigint::kFftInnerThreshold, v8::bigint::anonymous_namespace{mul-fft.cc}::ModFnDoubleWidth(), v8::bigint::anonymous_namespace{mul-fft.cc}::MultiplyFFT_Inner(), part_, v8::base::internal::result, and v8::bigint::anonymous_namespace{mul-fft.cc}::SumDiff().
FFT_Recurse()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::FFT_Recurse (int start, int half, int omega, digit_t * temp)
Definition at line 578 of file mul-fft.cc.
                                                                            {
  if (half > 1) {
    FFT_ReturnShuffledThreadsafe(start, half, 2 * omega, temp);
    FFT_ReturnShuffledThreadsafe(start + half, half, 2 * omega, temp);
  }
}
FFT_ReturnShuffledThreadsafe()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::FFT_ReturnShuffledThreadsafe (int start, int len, int omega, digit_t * temp)
Definition at line 562 of file mul-fft.cc.
                                                               {
  DCHECK((len & 1) == 0); // {len} must be even.
  int half = len / 2;
  SumDiff(part_[start], part_[start + half], part_[start], part_[start + half],
          length_);
  for (int k = 1; k < half; k++) {
    SumDiff(part_[start + k], temp, part_[start + k], part_[start + half + k],
            length_);
    int w = omega * k;
    ShiftModFn(part_[start + half + k], temp, w, K_);
  }
  FFT_Recurse(start, half, omega, temp);
}
References DCHECK, v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), and v8::bigint::anonymous_namespace{mul-fft.cc}::SumDiff().
length()
int v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::length () const [inline]
Definition at line 468 of file mul-fft.cc.
{ return length_; }
NormalizeAndRecombine()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::NormalizeAndRecombine (int omega, int m, RWDigits Z, int chunk_size)
Definition at line 613 of file mul-fft.cc.
                                                         {
  Z.Clear();
  int z_index = 0;
  const int shift = n_ * omega - m;
  for (int i = 0; i < n_; i++, z_index += chunk_size) {
    digit_t* part = part_[i];
    ShiftModFn(temp_, part, shift, K_);
    digit_t carry = 0;
    int zi = z_index;
    int j = 0;
    for (; j < length_ && zi < Z.len(); j++, zi++) {
      Z[zi] = digit_add3(Z[zi], temp_[j], carry, &carry);
    }
    for (; j < length_; j++) {
      DCHECK(temp_[j] == 0);
    }
    if (carry != 0) {
      DCHECK(zi < Z.len());
      Z[zi] = carry;
    }
  }
}
References v8::internal::carry, v8::bigint::RWDigits::Clear(), DCHECK, v8::bigint::digit_add3(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn().
operator=()
FFTContainer& v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::operator= (const FFTContainer &) [delete]
PointwiseMultiply()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::PointwiseMultiply (const FFTContainer & other)
Definition at line 751 of file mul-fft.cc.
                                                              {
  DCHECK(n_ == other.n_);
  DoPointwiseMultiplication(other, 0, n_, temp_);
}
References DCHECK, and n_.
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::MultiplyFFT_Inner().
Start()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start (Digits X, int chunk_size, int theta, int omega)
Definition at line 528 of file mul-fft.cc.
                                                                       {
  int len = X.len();
  if (len > n_ * chunk_size / 2) {
    return Start_Default(X, chunk_size, theta, omega);
  }
  DCHECK(theta == 0);
  const digit_t* pointer = X.digits();
  const size_t part_length_in_bytes = length_ * sizeof(digit_t);
  int nhalf = n_ / 2;
  // Unrolled first iteration.
  CopyAndZeroExtend(part_[0], pointer, chunk_size, part_length_in_bytes);
  CopyAndZeroExtend(part_[nhalf], pointer, chunk_size, part_length_in_bytes);
  pointer += chunk_size;
  len -= chunk_size;
  int i = 1;
  for (; i < nhalf && len > 0; i++) {
    chunk_size = std::min(chunk_size, len);
    CopyAndZeroExtend(part_[i], pointer, chunk_size, part_length_in_bytes);
    int w = omega * i;
    ShiftModFn(part_[i + nhalf], part_[i], w, K_, chunk_size);
    pointer += chunk_size;
    len -= chunk_size;
  }
  for (; i < nhalf; i++) {
    memset(part_[i], 0, part_length_in_bytes);
    memset(part_[i + nhalf], 0, part_length_in_bytes);
  }
  FFT_Recurse(0, nhalf, omega, temp_);
}
References v8::bigint::anonymous_namespace{mul-fft.cc}::CopyAndZeroExtend(), DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), and X().
Start_Default()
void v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start_Default (Digits X, int chunk_size, int theta, int omega)
Definition at line 489 of file mul-fft.cc.
                                            {
  int len = X.len();
  const digit_t* pointer = X.digits();
  const size_t part_length_in_bytes = length_ * sizeof(digit_t);
  int current_theta = 0;
  int i = 0;
  for (; i < n_ && len > 0; i++, current_theta += theta) {
    chunk_size = std::min(chunk_size, len);
    // For invocations via MultiplyFFT_Inner, X.len() == n_ * chunk_size + 1,
    // because the outer layer's "K" is passed as the inner layer's "N".
    // Since X is (mod Fn)-normalized on the outer layer, there is the rare
    // corner case where X[n_ * chunk_size] == 1. Detect that case, and handle
    // the extra bit as part of the last chunk; we always have the space.
    if (i == n_ - 1 && len == chunk_size + 1) {
      DCHECK(X[n_ * chunk_size] <= 1);
      DCHECK(length_ >= chunk_size + 1);
      chunk_size++;
    }
    if (current_theta != 0) {
      // Multiply with theta^i, and reduce modulo 2^K + 1.
      // We pass theta as a shift amount; it really means 2^theta.
      CopyAndZeroExtend(temp_, pointer, chunk_size, part_length_in_bytes);
      ShiftModFn(part_[i], temp_, current_theta, K_, chunk_size);
    } else {
      CopyAndZeroExtend(part_[i], pointer, chunk_size, part_length_in_bytes);
    }
    pointer += chunk_size;
    len -= chunk_size;
  }
  DCHECK(len == 0);
  for (; i < n_; i++) {
    memset(part_[i], 0, part_length_in_bytes);
  }
  FFT_ReturnShuffledThreadsafe(0, n_, omega, temp_);
}
References v8::bigint::anonymous_namespace{mul-fft.cc}::CopyAndZeroExtend(), DCHECK, v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), and X().
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::MultiplyFFT_Inner().
Member Data Documentation
K_
const int v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::K_ [private]
Definition at line 472 of file mul-fft.cc.
length_
const int v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::length_ [private]
Definition at line 473 of file mul-fft.cc.
n_
const int v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::n_ [private]
Definition at line 471 of file mul-fft.cc.
Referenced by PointwiseMultiply().
part_
digit_t** v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::part_ [private]
Definition at line 476 of file mul-fft.cc.
Referenced by DoPointwiseMultiplication().
processor_
ProcessorImpl* v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::processor_ [private]
Definition at line 474 of file mul-fft.cc.
storage_
digit_t* v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::storage_ [private]
Definition at line 475 of file mul-fft.cc.
temp_
digit_t* v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::temp_ [private]
Definition at line 477 of file mul-fft.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/bigint/mul-fft.cc