v8::internal::SamplingHeapProfiler::Observer Class Reference
Public Member Functions
Observer (Heap *heap, intptr_t step_size, uint64_t rate, SamplingHeapProfiler *profiler, base::RandomNumberGenerator *random)
Protected Member Functions
void Step (int bytes_allocated, Address soon_object, size_t size) override
intptr_t GetNextStepSize () override
Private Member Functions
intptr_t GetNextSampleInterval (uint64_t rate)
Private Attributes
SamplingHeapProfiler *const profiler_
Heap *const heap_
base::RandomNumberGenerator *const random_
uint64_t const rate_
Additional Inherited Members
Detailed Description
Definition at line 129 of file sampling-heap-profiler.h.
Constructor & Destructor Documentation
Observer()
v8::internal::SamplingHeapProfiler::Observer::Observer (Heap * heap, intptr_t step_size, uint64_t rate, SamplingHeapProfiler * profiler, base::RandomNumberGenerator * random) [inline]
Definition at line 131 of file sampling-heap-profiler.h.
        : AllocationObserver(step_size),
          profiler_(profiler),
          heap_(heap),
          random_(random),
          rate_(rate) {}
Member Function Documentation
GetNextSampleInterval()
intptr_t v8::internal::SamplingHeapProfiler::Observer::GetNextSampleInterval (uint64_t rate) [private]
Definition at line 29 of file sampling-heap-profiler.cc.
                                                                          {
  if (v8_flags.sampling_heap_profiler_suppress_randomness)
    return static_cast<intptr_t>(rate);
  double u = random_->NextDouble();
  double next = (-base::ieee754::log(u)) * rate;
  return next < kTaggedSize
             ? kTaggedSize
             : (next > INT_MAX ? INT_MAX : static_cast<intptr_t>(next));
}
References v8::internal::kTaggedSize, v8::base::ieee754::log(), v8::base::RandomNumberGenerator::NextDouble(), random_, and v8::internal::v8_flags.
Referenced by GetNextStepSize().
GetNextStepSize()
intptr_t v8::internal::SamplingHeapProfiler::Observer::GetNextStepSize () [inline], [override], [protected], [virtual]
Reimplemented from v8::internal::AllocationObserver.
Definition at line 151 of file sampling-heap-profiler.h.
{ return GetNextSampleInterval(rate_); }
References GetNextSampleInterval(), and rate_.
Step()
void v8::internal::SamplingHeapProfiler::Observer::Step (int bytes_allocated, Address soon_object, size_t size) [inline], [override], [protected], [virtual]
Implements v8::internal::AllocationObserver.
Definition at line 141 of file sampling-heap-profiler.h.
                                                                              {
      USE(heap_);
      DCHECK(heap_->gc_state() == Heap::NOT_IN_GC);
      if (soon_object) {
        // TODO(ofrobots): it would be better to sample the next object rather
        // than skipping this sample epoch if soon_object happens to be null.
        profiler_->SampleObject(soon_object, size);
      }
    }
References v8::internal::DCHECK(), v8::internal::Heap::gc_state(), heap_, v8::internal::Heap::NOT_IN_GC, profiler_, v8::internal::SamplingHeapProfiler::SampleObject(), size(), and USE.
Member Data Documentation
heap_
Heap* const v8::internal::SamplingHeapProfiler::Observer::heap_ [private]
Definition at line 156 of file sampling-heap-profiler.h.
Referenced by Step().
profiler_
SamplingHeapProfiler* const v8::internal::SamplingHeapProfiler::Observer::profiler_ [private]
Definition at line 155 of file sampling-heap-profiler.h.
Referenced by Step().
random_
base::RandomNumberGenerator* const v8::internal::SamplingHeapProfiler::Observer::random_ [private]
Definition at line 157 of file sampling-heap-profiler.h.
Referenced by GetNextSampleInterval().
rate_
uint64_t const v8::internal::SamplingHeapProfiler::Observer::rate_ [private]
Definition at line 158 of file sampling-heap-profiler.h.
Referenced by GetNextStepSize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/sampling-heap-profiler.h
/mnt/V8SourceCode/src/profiler/sampling-heap-profiler.cc