v8::internal::compiler::CompilationDependency Class Reference
Public Member Functions
CompilationDependency (CompilationDependencyKind kind)
virtual bool IsValid (JSHeapBroker *broker) const =0
virtual void PrepareInstall (JSHeapBroker *broker) const
virtual void Install (JSHeapBroker *broker, PendingDependencies *deps) const =0
const char * ToString () const
Public Attributes
const CompilationDependencyKind kind
Private Member Functions
virtual size_t Hash () const =0
virtual bool Equals (const CompilationDependency *that) const =0
Friends
struct CompilationDependencies::CompilationDependencyHash
struct CompilationDependencies::CompilationDependencyEqual
Detailed Description
Definition at line 79 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
CompilationDependency()
v8::internal::compiler::CompilationDependency::CompilationDependency (CompilationDependencyKind kind) [inline], [explicit]
Definition at line 81 of file compilation-dependencies.cc.
: kind(kind) {}
Member Function Documentation
Equals()
virtual bool v8::internal::compiler::CompilationDependency::Equals (const CompilationDependency * that) const [private], [pure virtual]
Implemented in v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency, and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency.
Referenced by v8::internal::compiler::CompilationDependencies::CompilationDependencyEqual::operator()().
Hash()
virtual size_t v8::internal::compiler::CompilationDependency::Hash () const [private], [pure virtual]
Implemented in v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency, and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency.
Referenced by v8::internal::compiler::CompilationDependencies::CompilationDependencyHash::operator()().
Install()
virtual void v8::internal::compiler::CompilationDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [pure virtual]
IsValid()
virtual bool v8::internal::compiler::CompilationDependency::IsValid (JSHeapBroker * broker) const [pure virtual]
Implemented in v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency, and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency.
Referenced by v8::internal::compiler::TraceInvalidCompilationDependency().
PrepareInstall()
virtual void v8::internal::compiler::CompilationDependency::PrepareInstall (JSHeapBroker * broker) const [inline], [virtual]
Reimplemented in v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency, and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency.
Definition at line 84 of file compilation-dependencies.cc.
{}
ToString()
const char* v8::internal::compiler::CompilationDependency::ToString () const [inline]
Definition at line 94 of file compilation-dependencies.cc.
                               {
    return CompilationDependencyKindToString(kind);
  }
References v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::CompilationDependencyKindToString(), and kind.
Referenced by v8::internal::compiler::TraceInvalidCompilationDependency().
Friends And Related Function Documentation
CompilationDependencies::CompilationDependencyEqual
friend struct CompilationDependencies::CompilationDependencyEqual [friend]
Definition at line 104 of file compilation-dependencies.cc.
CompilationDependencies::CompilationDependencyHash
friend struct CompilationDependencies::CompilationDependencyHash [friend]
Definition at line 103 of file compilation-dependencies.cc.
Member Data Documentation
kind
const CompilationDependencyKind v8::internal::compiler::CompilationDependency::kind
Definition at line 98 of file compilation-dependencies.cc.
Referenced by v8::internal::compiler::CompilationDependencies::CompilationDependencyHash::operator()(), v8::internal::compiler::CompilationDependencies::CompilationDependencyEqual::operator()(), and ToString().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc