v8::internal::torque::ExternMacro Class Reference
#include <declarable.h>
Public Member Functions
const std::string & external_assembler_name () const
std::string CCName () const override
std::string CCDebugName () const override
Private Member Functions
ExternMacro (const std::string &name, std::string external_assembler_name, Signature signature)
Private Attributes
std::string external_assembler_name_
Friends
class Declarations
Additional Inherited Members
Detailed Description
Definition at line 407 of file declarable.h.
Constructor & Destructor Documentation
ExternMacro()
v8::internal::torque::ExternMacro::ExternMacro (const std::string & name, std::string external_assembler_name, Signature signature) [inline], [private]
Definition at line 427 of file declarable.h.
      : Macro(Declarable::kExternMacro, name, name, std::move(signature),
              std::nullopt),
        external_assembler_name_(std::move(external_assembler_name)) {}
Member Function Documentation
CCDebugName()
std::string v8::internal::torque::ExternMacro::CCDebugName () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Callable.
Definition at line 420 of file declarable.h.
                                         {
    return "TorqueDebugMacroShims::" + external_assembler_name() +
           "::" + ExternalName();
  }
References external_assembler_name(), and v8::internal::torque::Callable::ExternalName().
CCName()
std::string v8::internal::torque::ExternMacro::CCName () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Callable.
Definition at line 415 of file declarable.h.
                                    {
    return "TorqueRuntimeMacroShims::" + external_assembler_name() +
           "::" + ExternalName();
  }
References external_assembler_name(), and v8::internal::torque::Callable::ExternalName().
external_assembler_name()
const std::string& v8::internal::torque::ExternMacro::external_assembler_name () const [inline]
Definition at line 411 of file declarable.h.
                                                   {
    return external_assembler_name_;
  }
References external_assembler_name_.
Referenced by CCDebugName(), and CCName().
Friends And Related Function Documentation
Declarations
friend class Declarations [friend]
Definition at line 426 of file declarable.h.
Member Data Documentation
external_assembler_name_
std::string v8::internal::torque::ExternMacro::external_assembler_name_ [private]
Definition at line 433 of file declarable.h.
Referenced by external_assembler_name().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h