v8::internal::CoverageInfo Class Reference
#include <debug-objects.h>
Classes
class BodyDescriptor
Public Types
using Slot = TorqueGeneratedCoverageInfoSlotOffsets
Public Member Functions
void InitializeSlot (int slot_index, int start_pos, int end_pos)
void ResetBlockCount (int slot_index)
void CoverageInfoPrint (std::ostream &os, std::unique_ptr< char[]> function_name=nullptr)
Static Public Member Functions
static int SizeFor (int slot_count)
Detailed Description
Definition at line 179 of file debug-objects.h.
Member Typedef Documentation
Slot
using v8::internal::CoverageInfo::Slot = TorqueGeneratedCoverageInfoSlotOffsets
Definition at line 197 of file debug-objects.h.
Member Function Documentation
CoverageInfoPrint()
void v8::internal::CoverageInfo::CoverageInfoPrint (std::ostream & os, std::unique_ptr< char[]> function_name = nullptr)
Definition at line 386 of file debug-objects.cc.
                                                                          {
  DisallowGarbageCollection no_gc;
  os << "Coverage info (";
  if (function_name == nullptr) {
    os << "{unknown}";
  } else if (strlen(function_name.get()) > 0) {
    os << function_name.get();
  } else {
    os << "{anonymous}";
  }
  os << "):" << std::endl;
  for (int i = 0; i < slot_count(); i++) {
    os << "{" << slots_start_source_position(i) << ","
       << slots_end_source_position(i) << "}" << std::endl;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
InitializeSlot()
void v8::internal::CoverageInfo::InitializeSlot (int slot_index, int start_pos, int end_pos)
Definition at line 375 of file debug-objects.cc.
                                                                          {
  set_slots_start_source_position(slot_index, from_pos);
  set_slots_end_source_position(slot_index, to_pos);
  ResetBlockCount(slot_index);
  set_slots_padding(slot_index, 0);
}
References ResetBlockCount().
ResetBlockCount()
void v8::internal::CoverageInfo::ResetBlockCount (int slot_index)
Definition at line 382 of file debug-objects.cc.
                                                 {
  set_slots_block_count(slot_index, 0);
}
Referenced by InitializeSlot().
SizeFor()
static int v8::internal::CoverageInfo::SizeFor (int slot_count) [inline], [static]
Definition at line 186 of file debug-objects.h.
                                     {
    return OBJECT_POINTER_ALIGN(kHeaderSize + slot_count * Slot::kSize);
  }
References OBJECT_POINTER_ALIGN.
Referenced by v8::internal::FactoryBase< Impl >::NewCoverageInfo(), v8::internal::HeapObject::SizeFromMap(), and v8::internal::CoverageInfo::BodyDescriptor::SizeOf().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/debug-objects.h
/mnt/V8SourceCode/src/objects/debug-objects.cc