v8::internal::wasm::DeserializationQueue Class Reference
Public Member Functions
void Add (std::vector< DeserializationUnit > batch)
std::vector< DeserializationUnit > Pop ()
std::vector< DeserializationUnit > PopAll ()
size_t NumBatches () const
Private Attributes
base::Mutex mutex_
std::queue< std::vector< DeserializationUnit > > queue_
Detailed Description
Definition at line 659 of file wasm-serialization.cc.
Member Function Documentation
Add()
void v8::internal::wasm::DeserializationQueue::Add (std::vector< DeserializationUnit > batch) [inline]
Definition at line 661 of file wasm-serialization.cc.
                                                 {
    DCHECK(!batch.empty());
    base::MutexGuard guard(&mutex_);
    queue_.emplace(std::move(batch));
  }
References v8::internal::DCHECK(), mutex_, and queue_.
Referenced by v8::internal::wasm::NativeModuleDeserializer::Read(), and v8::internal::wasm::DeserializeCodeTask::Run().
NumBatches()
size_t v8::internal::wasm::DeserializationQueue::NumBatches () const [inline]
Definition at line 688 of file wasm-serialization.cc.
                            {
    base::MutexGuard guard(&mutex_);
    return queue_.size();
  }
References mutex_, and queue_.
Referenced by v8::internal::wasm::DeserializeCodeTask::GetMaxConcurrency(), and v8::internal::wasm::DeserializeCodeTask::TryPublishing().
Pop()
std::vector<DeserializationUnit> v8::internal::wasm::DeserializationQueue::Pop () [inline]
Definition at line 667 of file wasm-serialization.cc.
                                       {
    base::MutexGuard guard(&mutex_);
    if (queue_.empty()) return {};
    auto batch = std::move(queue_.front());
    queue_.pop();
    return batch;
  }
References mutex_, and queue_.
Referenced by v8::internal::wasm::DeserializeCodeTask::Run().
PopAll()
std::vector<DeserializationUnit> v8::internal::wasm::DeserializationQueue::PopAll () [inline]
Definition at line 675 of file wasm-serialization.cc.
                                          {
    base::MutexGuard guard(&mutex_);
    if (queue_.empty()) return {};
    auto units = std::move(queue_.front());
    queue_.pop();
    while (!queue_.empty()) {
      units.insert(units.end(), std::make_move_iterator(queue_.front().begin()),
                   std::make_move_iterator(queue_.front().end()));
      queue_.pop();
    }
    return units;
  }
References mutex_, and queue_.
Referenced by v8::internal::wasm::DeserializeCodeTask::TryPublishing().
Member Data Documentation
mutex_
base::Mutex v8::internal::wasm::DeserializationQueue::mutex_ [mutable], [private]
Definition at line 694 of file wasm-serialization.cc.
Referenced by Add(), NumBatches(), Pop(), and PopAll().
queue_
std::queue<std::vector<DeserializationUnit> > v8::internal::wasm::DeserializationQueue::queue_ [private]
Definition at line 695 of file wasm-serialization.cc.
Referenced by Add(), NumBatches(), Pop(), and PopAll().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-serialization.cc