v8::internal::Declaration Class Reference
#include <ast.h>
Public Types
using List = base::ThreadedList< Declaration >
Public Member Functions
Variable * var () const
void set_var (Variable *var)
Protected Member Functions
Declaration (int pos, NodeType type)
Private Member Functions
Declaration ** next ()
Private Attributes
Variable * var_
Declaration * next_
friend List
Additional Inherited Members
Detailed Description
Definition at line 359 of file ast.h.
Member Typedef Documentation
List
using v8::internal::Declaration::List = base::ThreadedList<Declaration>
Definition at line 361 of file ast.h.
Constructor & Destructor Documentation
Declaration()
v8::internal::Declaration::Declaration (int pos, NodeType type) [inline], [protected]
Definition at line 367 of file ast.h.
: AstNode(pos, type), next_(nullptr) {}
Member Function Documentation
next()
Declaration** v8::internal::Declaration::next () [inline], [private]
Definition at line 372 of file ast.h.
{ return &next_; }
References next_.
set_var()
void v8::internal::Declaration::set_var (Variable * var) [inline]
Definition at line 364 of file ast.h.
{ var_ = var; }
References var(), and var_.
Referenced by v8::internal::Parser::DeclareClassVariable(), v8::internal::Scope::DeclareVariable(), v8::internal::PreParser::DeclareVariableName(), and v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
var()
Variable* v8::internal::Declaration::var () const [inline]
Definition at line 363 of file ast.h.
{ return var_; }
References var_.
Referenced by v8::internal::ParserBase< Impl >::CheckConflictingVarDeclarations(), v8::internal::Parser::Declare(), v8::internal::Parser::DeclareFunction(), v8::internal::Parser::DeclareVariable(), and set_var().
Member Data Documentation
List
friend v8::internal::Declaration::List [private]
Definition at line 374 of file ast.h.
next_
Declaration* v8::internal::Declaration::next_ [private]
Definition at line 373 of file ast.h.
Referenced by next().
var_
Variable* v8::internal::Declaration::var_ [private]
Definition at line 370 of file ast.h.
Referenced by set_var(), and var().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h