v8::internal::compiler::turboshaft::AssertTypesReducer< Next > Class Template Reference
#include <assert-types-reducer.h>
Public Types
using Adapter = UniformReducerAdapter< AssertTypesReducer, Next >
Public Member Functions
i::Tagged< Smi > NoContextConstant ()
template<typename Op , typename Continuation >
OpIndex ReduceInputGraphOperation (OpIndex ig_index, const Op &operation)
void InsertTypeAssert (RegisterRepresentation rep, OpIndex value, const Type &type)
Private Member Functions
Factory * factory ()
Private Attributes
Isolate * isolate_ = __ data() -> isolate()
const bool type_assertions_allowed_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::AssertTypesReducer< Next >
Definition at line 30 of file assert-types-reducer.h.
Member Typedef Documentation
Adapter
template<class Next >
using v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::Adapter = UniformReducerAdapter<AssertTypesReducer, Next>
Definition at line 39 of file assert-types-reducer.h.
Member Function Documentation
factory()
template<class Next >
Factory* v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::factory () [inline], [private]
Definition at line 158 of file assert-types-reducer.h.
{ return isolate_->factory(); }
References v8::internal::Isolate::factory(), and v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::isolate_.
Referenced by v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert().
InsertTypeAssert()
template<class Next >
void v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert (RegisterRepresentation rep, OpIndex value, const Type & type) [inline]
Definition at line 76 of file assert-types-reducer.h.
                                          {
    if (!type_assertions_allowed_) return;
    DCHECK(!type.IsInvalid());
    if (type.IsNone()) {
      __ Unreachable();
      return;
    }
    if (type.IsAny()) {
      // Ignore any typed for now.
      return;
    }
    auto GenerateBuiltinCall =
        [this](Builtin builtin, OpIndex original_value,
               base::SmallVector<OpIndex, 6> actual_value_indices,
               const Type& type) {
          i::Tagged<Smi> op_id = Smi::FromInt(original_value.id());
          // Add expected type and operation id.
          Handle<TurboshaftType> expected_type = type.AllocateOnHeap(factory());
          actual_value_indices.push_back(__ HeapConstant(expected_type));
          actual_value_indices.push_back(__ SmiConstant(op_id));
          actual_value_indices.push_back(__ SmiConstant(NoContextConstant()));
          __ CallBuiltin(
              builtin, OpIndex::Invalid(),
              {actual_value_indices.data(), actual_value_indices.size()},
              CanThrow::kNo, isolate_);
#ifdef DEBUG
          // Used for debugging
          if (v8_flags.turboshaft_trace_typing) {
            PrintF("Inserted assert for %3d:%-40s (%s)\n", original_value.id(),
                   __ output_graph().Get(original_value).ToString().c_str(),
                   type.ToString().c_str());
          }
#endif
        };
    switch (rep.value()) {
      case RegisterRepresentation::Word32(): {
        DCHECK(type.IsWord32());
        base::SmallVector<OpIndex, 6> actual_value_indices = {value};
        GenerateBuiltinCall(Builtin::kCheckTurboshaftWord32Type, value,
                            std::move(actual_value_indices), type);
        break;
      }
      case RegisterRepresentation::Word64(): {
        DCHECK(type.IsWord64());
        OpIndex value_high =
            __ TruncateWord64ToWord32(__ Word64ShiftRightLogical(value, 32));
        OpIndex value_low = __ TruncateWord64ToWord32(value);
        base::SmallVector<OpIndex, 6> actual_value_indices = {value_high,
                                                              value_low};
        GenerateBuiltinCall(Builtin::kCheckTurboshaftWord64Type, value,
                            std::move(actual_value_indices), type);
        break;
      }
      case RegisterRepresentation::Float32(): {
        DCHECK(type.IsFloat32());
        base::SmallVector<OpIndex, 6> actual_value_indices = {value};
        GenerateBuiltinCall(Builtin::kCheckTurboshaftFloat32Type, value,
                            std::move(actual_value_indices), type);
        break;
      }
      case RegisterRepresentation::Float64(): {
        DCHECK(type.IsFloat64());
        base::SmallVector<OpIndex, 6> actual_value_indices = {value};
        GenerateBuiltinCall(Builtin::kCheckTurboshaftFloat64Type, value,
                            std::move(actual_value_indices), type);
        break;
      }
      case RegisterRepresentation::Tagged():
      case RegisterRepresentation::Compressed():
      case RegisterRepresentation::Simd128():
      case RegisterRepresentation::Simd256():
        // TODO(nicohartmann@): Handle remaining cases.
        break;
    }
  }
References __, v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::factory(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::Smi::FromInt(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::isolate_, v8::internal::compiler::kNo, v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::NoContextConstant(), v8::internal::PrintF(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::ToString(), v8::internal::tracing::type, v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::type_assertions_allowed_, v8::internal::v8_flags, v8::internal::compiler::turboshaft::RegisterRepresentation::value(), v8::internal::value, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::ReduceInputGraphOperation().
NoContextConstant()
template<class Next >
i::Tagged<Smi> v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::NoContextConstant () [inline]
Definition at line 41 of file assert-types-reducer.h.
                                   {
    return Smi::FromInt(Context::kNoContext);
  }
References v8::internal::Smi::FromInt(), and v8::internal::Context::kNoContext.
Referenced by v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert().
ReduceInputGraphOperation()
template<class Next >
template<typename Op , typename Continuation >
OpIndex v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::ReduceInputGraphOperation (OpIndex ig_index, const Op & operation) [inline]
Definition at line 46 of file assert-types-reducer.h.
                                                                           {
    OpIndex og_index = Continuation{this}.ReduceInputGraph(ig_index, operation);
    if constexpr (std::is_same_v<Op, LoadRootRegisterOp>) {
      // LoadRootRegister is a bit special and should never be materialized,
      // hence we cannot assert its type.
      return og_index;
    }
    if (std::is_same_v<Op, ConstantOp>) {
      // Constants are constant by definition, so asserting their types doesn't
      // seem super useful. Additionally, they can appear before Parameters in
      // the graph, which leads to issues because asserting their types requires
      // inserting a Call in the graph, which can overwrite the value of
      // Parameters.
      return og_index;
    }
    if (!og_index.valid()) return og_index;
    if (!CanBeTyped(operation)) return og_index;
    // Unfortunately, we cannot insert assertions after block terminators, so we
    // skip them here.
    if (operation.IsBlockTerminator()) return og_index;
    auto reps = operation.outputs_rep();
    DCHECK_GT(reps.size(), 0);
    if (reps.size() == 1) {
      Type type = __ GetInputGraphType(ig_index);
      InsertTypeAssert(reps[0], og_index, type);
    }
    return og_index;
  }
References __, v8::internal::compiler::turboshaft::CanBeTyped(), DCHECK_GT, v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::OpIndex::valid().
Member Data Documentation
isolate_
template<class Next >
Isolate* v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::isolate_ = __ data() -> isolate() [private]
Definition at line 159 of file assert-types-reducer.h.
Referenced by v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::factory(), and v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert().
type_assertions_allowed_
template<class Next >
const bool v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::type_assertions_allowed_ [private]
Initial value:
=
      !__ data() -> graph_has_lowered_fast_api_calls()
Definition at line 165 of file assert-types-reducer.h.
Referenced by v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assert-types-reducer.h