v8::internal::EphemeronRememberedSet Class Reference
#include <ephemeron-remembered-set.h>
Public Types
using TableList = ::heap::base::Worklist< Tagged< EphemeronHashTable >, kEphemeronTableListSegmentSize >
using IndicesSet = std::unordered_set< int >
using TableMap = std::unordered_map< Tagged< EphemeronHashTable >, IndicesSet, Object::Hasher >
Public Member Functions
void RecordEphemeronKeyWrite (Tagged< EphemeronHashTable > table, Address key_slot)
void RecordEphemeronKeyWrites (Tagged< EphemeronHashTable > table, IndicesSet indices)
TableMap * tables ()
Static Public Attributes
static constexpr int kEphemeronTableListSegmentSize = 128
Private Attributes
base::Mutex insertion_mutex_
TableMap tables_
Detailed Description
Definition at line 22 of file ephemeron-remembered-set.h.
Member Typedef Documentation
IndicesSet
using v8::internal::EphemeronRememberedSet::IndicesSet = std::unordered_set<int>
Definition at line 28 of file ephemeron-remembered-set.h.
TableList
using v8::internal::EphemeronRememberedSet::TableList = ::heap::base::Worklist<Tagged<EphemeronHashTable>, kEphemeronTableListSegmentSize>
Definition at line 25 of file ephemeron-remembered-set.h.
TableMap
using v8::internal::EphemeronRememberedSet::TableMap = std::unordered_map<Tagged<EphemeronHashTable>, IndicesSet, Object::Hasher>
Definition at line 29 of file ephemeron-remembered-set.h.
Member Function Documentation
RecordEphemeronKeyWrite()
void v8::internal::EphemeronRememberedSet::RecordEphemeronKeyWrite (Tagged< EphemeronHashTable > table, Address key_slot)
Definition at line 12 of file ephemeron-remembered-set.cc.
                                                    {
  DCHECK(HeapLayout::InYoungGeneration(HeapObjectSlot(slot).ToHeapObject()));
  int slot_index = EphemeronHashTable::SlotToIndex(table.address(), slot);
  InternalIndex entry = EphemeronHashTable::IndexToEntry(slot_index);
  base::MutexGuard guard(&insertion_mutex_);
  auto it = tables_.insert({table, IndicesSet()});
  it.first->second.insert(entry.as_int());
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::InternalIndex::as_int(), v8::internal::DCHECK(), insertion_mutex_, v8::internal::HeapLayout::InYoungGeneration(), and tables_.
Referenced by v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow().
RecordEphemeronKeyWrites()
void v8::internal::EphemeronRememberedSet::RecordEphemeronKeyWrites (Tagged< EphemeronHashTable > table, IndicesSet indices)
Definition at line 22 of file ephemeron-remembered-set.cc.
                                                          {
  base::MutexGuard guard(&insertion_mutex_);
  auto it = tables_.find(table);
  if (it != tables_.end()) {
    it->second.merge(std::move(indices));
  } else {
    tables_.insert({table, std::move(indices)});
  }
}
References insertion_mutex_, and tables_.
tables()
TableMap* v8::internal::EphemeronRememberedSet::tables () [inline]
Definition at line 37 of file ephemeron-remembered-set.h.
{ return &tables_; }
References tables_.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
Member Data Documentation
insertion_mutex_
base::Mutex v8::internal::EphemeronRememberedSet::insertion_mutex_ [private]
Definition at line 40 of file ephemeron-remembered-set.h.
Referenced by RecordEphemeronKeyWrite(), and RecordEphemeronKeyWrites().
kEphemeronTableListSegmentSize
constexpr int v8::internal::EphemeronRememberedSet::kEphemeronTableListSegmentSize = 128 [static], [constexpr]
Definition at line 24 of file ephemeron-remembered-set.h.
tables_
TableMap v8::internal::EphemeronRememberedSet::tables_ [private]
Definition at line 41 of file ephemeron-remembered-set.h.
Referenced by RecordEphemeronKeyWrite(), RecordEphemeronKeyWrites(), and tables().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/ephemeron-remembered-set.h
/mnt/V8SourceCode/src/heap/ephemeron-remembered-set.cc