v8::internal::PreParserStatementList Class Reference
#include <preparser.h>
Public Member Functions
PreParserStatementList ()
PreParserStatementList * operator-> ()
void Add (const PreParserStatement &element, Zone *zone)
bool IsNull () const
Static Public Member Functions
static PreParserStatementList Null ()
Private Member Functions
PreParserStatementList (bool is_null)
Private Attributes
bool is_null_
Detailed Description
Definition at line 322 of file preparser.h.
Constructor & Destructor Documentation
PreParserStatementList() [1/2]
v8::internal::PreParserStatementList::PreParserStatementList () [inline]
Definition at line 324 of file preparser.h.
: PreParserStatementList(false) {}
Referenced by Null().
PreParserStatementList() [2/2]
v8::internal::PreParserStatementList::PreParserStatementList (bool is_null) [inline], [explicit], [private]
Definition at line 331 of file preparser.h.
: is_null_(is_null) {}
Member Function Documentation
Add()
void v8::internal::PreParserStatementList::Add (const PreParserStatement & element, Zone * zone) [inline]
Definition at line 326 of file preparser.h.
{}
IsNull()
bool v8::internal::PreParserStatementList::IsNull () const [inline]
Definition at line 328 of file preparser.h.
{ return is_null_; }
References is_null_.
Null()
static PreParserStatementList v8::internal::PreParserStatementList::Null () [inline], [static]
Definition at line 327 of file preparser.h.
{ return PreParserStatementList(true); }
References PreParserStatementList().
Referenced by v8::internal::PreParser::NullStatementList().
operator->()
PreParserStatementList* v8::internal::PreParserStatementList::operator-> () [inline]
Definition at line 325 of file preparser.h.
{ return this; }
Member Data Documentation
is_null_
bool v8::internal::PreParserStatementList::is_null_ [private]
Definition at line 332 of file preparser.h.
Referenced by IsNull().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparser.h