v8::internal::Script::Iterator Class Reference
#include <script.h>
Public Member Functions
Iterator (Isolate *isolate)
Iterator (const Iterator &)=delete
Iterator & operator= (const Iterator &)=delete
Tagged< Script > Next ()
Private Attributes
WeakArrayList::Iterator iterator_
Detailed Description
Definition at line 259 of file script.h.
Constructor & Destructor Documentation
Iterator() [1/2]
v8::internal::Script::Iterator::Iterator (Isolate * isolate) [explicit]
Definition at line 4850 of file objects.cc.
    : iterator_(isolate->heap()->script_list()) {}
Iterator() [2/2]
v8::internal::Script::Iterator::Iterator (const Iterator &) [delete]
Member Function Documentation
Next()
Tagged< Script > v8::internal::Script::Iterator::Next ()
Definition at line 4853 of file objects.cc.
                                    {
  Tagged<Object> o = iterator_.Next();
  if (o != Tagged<Object>()) {
    return Cast<Script>(o);
  }
  return Script();
}
Referenced by v8::internal::Coverage::Collect(), v8::internal::EnumerateCompiledFunctions(), v8::internal::SamplingHeapProfiler::GetAllocationProfile(), v8::internal::Debug::GetLoadedScripts(), v8::internal::anonymous_namespace{runtime-debug.cc}::GetScriptById(), and v8::internal::V8HeapExplorer::PopulateLineEnds().
operator=()
Iterator& v8::internal::Script::Iterator::operator= (const Iterator &) [delete]
Member Data Documentation
iterator_
WeakArrayList::Iterator v8::internal::Script::Iterator::iterator_ [private]
Definition at line 267 of file script.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/script.h
/mnt/V8SourceCode/src/objects/objects.cc