v8::internal::AstValueFactory Class Reference
#include <ast-value-factory.h>
Public Member Functions
AstValueFactory (Zone *zone, const AstStringConstants *string_constants, uint64_t hash_seed)
AstValueFactory (Zone *ast_raw_string_zone, Zone *single_parse_zone, const AstStringConstants *string_constants, uint64_t hash_seed)
Zone * ast_raw_string_zone () const
Zone * single_parse_zone () const
const AstRawString * GetOneByteString (base::Vector< const uint8_t > literal)
const AstRawString * GetOneByteString (const char *string)
const AstRawString * GetTwoByteString (base::Vector< const uint16_t > literal)
const AstRawString * GetString (Tagged< String > literal, const SharedStringAccessGuardIfNeeded &)
V8_EXPORT_PRIVATE AstConsString * NewConsString ()
V8_EXPORT_PRIVATE AstConsString * NewConsString (const AstRawString *str)
V8_EXPORT_PRIVATE AstConsString * NewConsString (const AstRawString *str1, const AstRawString *str2)
template<typename IsolateT >
void Internalize (IsolateT *isolate)
AstConsString * empty_cons_string () const
Private Member Functions
AstRawString * AddString (AstRawString *string)
void ResetStrings ()
V8_EXPORT_PRIVATE const AstRawString * GetOneByteStringInternal (base::Vector< const uint8_t > literal)
const AstRawString * GetTwoByteStringInternal (base::Vector< const uint16_t > literal)
const AstRawString * GetString (uint32_t raw_hash_field, bool is_one_byte, base::Vector< const uint8_t > literal_bytes)
Private Attributes
AstRawStringMap string_table_
AstRawString * strings_
AstRawString ** strings_end_
const AstStringConstants * string_constants_
AstConsString * empty_cons_string_
Zone * ast_raw_string_zone_
Zone * single_parse_zone_
uint64_t hash_seed_
Detailed Description
Definition at line 339 of file ast-value-factory.h.
Constructor & Destructor Documentation
AstValueFactory() [1/2]
v8::internal::AstValueFactory::AstValueFactory (Zone * zone, const AstStringConstants * string_constants, uint64_t hash_seed) [inline]
Definition at line 341 of file ast-value-factory.h.
      : AstValueFactory(zone, zone, string_constants, hash_seed) {}
AstValueFactory() [2/2]
v8::internal::AstValueFactory::AstValueFactory (Zone * ast_raw_string_zone, Zone * single_parse_zone, const AstStringConstants * string_constants, uint64_t hash_seed) [inline]
Definition at line 345 of file ast-value-factory.h.
      : string_table_(string_constants->string_table()),
        strings_(nullptr),
        strings_end_(&strings_),
        string_constants_(string_constants),
        empty_cons_string_(nullptr),
        ast_raw_string_zone_(ast_raw_string_zone),
        single_parse_zone_(single_parse_zone),
        hash_seed_(hash_seed) {
    DCHECK_NOT_NULL(ast_raw_string_zone_);
    DCHECK_NOT_NULL(single_parse_zone_);
    DCHECK_EQ(hash_seed, string_constants->hash_seed());
    // Allocate the empty ConsString in the AstRawString Zone instead of the
    // single parse Zone like other ConsStrings, because unlike those it can be
    // reused across parses.
    empty_cons_string_ = ast_raw_string_zone_->New<AstConsString>();
  }
References ast_raw_string_zone_, DCHECK_EQ, DCHECK_NOT_NULL, empty_cons_string_, v8::internal::AstStringConstants::hash_seed(), v8::internal::Zone::New(), and single_parse_zone_.
Member Function Documentation
AddString()
AstRawString* v8::internal::AstValueFactory::AddString (AstRawString * string) [inline], [private]
Definition at line 406 of file ast-value-factory.h.
                                                {
    *strings_end_ = string;
    strings_end_ = string->next_location();
    return string;
  }
References v8::internal::AstRawString::next_location(), v8::internal::string, and strings_end_.
ast_raw_string_zone()
Zone* v8::internal::AstValueFactory::ast_raw_string_zone () const [inline]
Definition at line 366 of file ast-value-factory.h.
                                    {
    DCHECK_NOT_NULL(ast_raw_string_zone_);
    return ast_raw_string_zone_;
  }
References ast_raw_string_zone_, and DCHECK_NOT_NULL.
empty_cons_string()
AstConsString* v8::internal::AstValueFactory::empty_cons_string () const [inline]
Definition at line 403 of file ast-value-factory.h.
{ return empty_cons_string_; }
References empty_cons_string_.
Referenced by v8::internal::FuncNameInferrer::MakeNameFromStack(), and v8::internal::AstNodeFactory::NewScriptOrEvalFunctionLiteral().
GetOneByteString() [1/2]
const AstRawString* v8::internal::AstValueFactory::GetOneByteString (base::Vector< const uint8_t > literal) [inline]
Definition at line 376 of file ast-value-factory.h.
                                                                          {
    return GetOneByteStringInternal(literal);
  }
References GetOneByteStringInternal().
Referenced by v8::internal::ParserBase< Impl >::AutoAccessorVariableName(), v8::internal::ParserBase< Impl >::ClassFieldVariableName(), v8::internal::Scanner::CurrentRawSymbol(), v8::internal::Scanner::CurrentSymbol(), GetOneByteString(), and v8::internal::Scanner::NextSymbol().
GetOneByteString() [2/2]
const AstRawString* v8::internal::AstValueFactory::GetOneByteString (const char * string) [inline]
Definition at line 379 of file ast-value-factory.h.
                                                           {
    return GetOneByteString(base::OneByteVector(string));
  }
References GetOneByteString(), and v8::base::OneByteVector().
GetOneByteStringInternal()
const AstRawString * v8::internal::AstValueFactory::GetOneByteStringInternal (base::Vector< const uint8_t > literal) [private]
Definition at line 322 of file ast-value-factory.cc.
                                       {
  if (literal.length() == 1) {
    uint8_t key = literal[0];
    if (key < AstStringConstants::kMaxOneCharStringValue) {
      return string_constants_->one_character_string(key);
    }
  }
  uint32_t raw_hash_field = StringHasher::HashSequentialString<uint8_t>(
      literal.begin(), literal.length(), hash_seed_);
  return GetString(raw_hash_field, true, literal);
}
References v8::base::Vector< T >::begin(), GetString(), hash_seed_, v8::internal::key, v8::internal::AstStringConstants::kMaxOneCharStringValue, v8::base::Vector< T >::length(), v8::internal::AstStringConstants::one_character_string(), and string_constants_.
Referenced by GetOneByteString(), and GetString().
GetString() [1/2]
const AstRawString * v8::internal::AstValueFactory::GetString (Tagged< String > literal, const SharedStringAccessGuardIfNeeded & access_guard)
Definition at line 343 of file ast-value-factory.cc.
                                                         {
  const AstRawString* result = nullptr;
  DisallowGarbageCollection no_gc;
  String::FlatContent content = literal->GetFlatContent(no_gc, access_guard);
  if (content.IsOneByte()) {
    result = GetOneByteStringInternal(content.ToOneByteVector());
  } else {
    DCHECK(content.IsTwoByte());
    result = GetTwoByteStringInternal(content.ToUC16Vector());
  }
  return result;
}
References v8::internal::DCHECK(), GetOneByteStringInternal(), GetTwoByteStringInternal(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::FlatContent::IsTwoByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::ClassScope::ClassScope(), v8::internal::Scope::DeserializeScopeChain(), GetOneByteStringInternal(), GetTwoByteStringInternal(), and v8::internal::BackgroundCompileTask::Run().
GetString() [2/2]
const AstRawString* v8::internal::AstValueFactory::GetString (uint32_t raw_hash_field, bool is_one_byte, base::Vector< const uint8_t > literal_bytes) [private]
GetTwoByteString()
const AstRawString* v8::internal::AstValueFactory::GetTwoByteString (base::Vector< const uint16_t > literal) [inline]
Definition at line 382 of file ast-value-factory.h.
                                                                           {
    return GetTwoByteStringInternal(literal);
  }
References GetTwoByteStringInternal().
Referenced by v8::internal::Scanner::CurrentRawSymbol(), v8::internal::Scanner::CurrentSymbol(), and v8::internal::Scanner::NextSymbol().
GetTwoByteStringInternal()
const AstRawString * v8::internal::AstValueFactory::GetTwoByteStringInternal (base::Vector< const uint16_t > literal) [private]
Definition at line 335 of file ast-value-factory.cc.
                                        {
  uint32_t raw_hash_field = StringHasher::HashSequentialString<uint16_t>(
      literal.begin(), literal.length(), hash_seed_);
  return GetString(raw_hash_field, false,
                   base::Vector<const uint8_t>::cast(literal));
}
References v8::base::Vector< T >::begin(), GetString(), hash_seed_, and v8::base::Vector< T >::length().
Referenced by GetString(), and GetTwoByteString().
Internalize()
template<typename IsolateT >
void v8::internal::AstValueFactory::Internalize (IsolateT * isolate)
Definition at line 374 of file ast-value-factory.cc.
                                                   {
  // Strings need to be internalized before values, because values refer to
  // strings.
  for (AstRawString* current = strings_; current != nullptr;) {
    AstRawString* next = current->next();
    current->Internalize(isolate);
    current = next;
  }
  ResetStrings();
}
References v8::internal::AstRawString::Internalize(), v8::internal::AstRawString::next(), ResetStrings(), and strings_.
Referenced by v8::internal::Parser::DoParseProgram(), v8::internal::Parser::PostProcessParseResult(), v8::internal::PendingCompilationErrorHandler::PrepareErrors(), v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
NewConsString() [1/3]
AstConsString * v8::internal::AstValueFactory::NewConsString ()
Definition at line 358 of file ast-value-factory.cc.
                                              {
  return single_parse_zone()->New<AstConsString>();
}
References v8::internal::Zone::New(), and single_parse_zone().
Referenced by v8::internal::FuncNameInferrer::MakeNameFromStack(), NewConsString(), and v8::internal::AstNodeFactory::NewFunctionLiteral().
NewConsString() [2/3]
AstConsString * v8::internal::AstValueFactory::NewConsString (const AstRawString * str)
Definition at line 362 of file ast-value-factory.cc.
                                                                     {
  return NewConsString()->AddString(single_parse_zone(), str);
}
References v8::internal::AstConsString::AddString(), NewConsString(), and single_parse_zone().
NewConsString() [3/3]
AstConsString * v8::internal::AstValueFactory::NewConsString (const AstRawString * str1, const AstRawString * str2)
Definition at line 366 of file ast-value-factory.cc.
                                                                        {
  return NewConsString()
      ->AddString(single_parse_zone(), str1)
      ->AddString(single_parse_zone(), str2);
}
References v8::internal::AstConsString::AddString(), NewConsString(), and single_parse_zone().
ResetStrings()
void v8::internal::AstValueFactory::ResetStrings () [inline], [private]
Definition at line 411 of file ast-value-factory.h.
                      {
    strings_ = nullptr;
    strings_end_ = &strings_;
  }
References strings_, and strings_end_.
Referenced by Internalize().
single_parse_zone()
Zone* v8::internal::AstValueFactory::single_parse_zone () const [inline]
Definition at line 371 of file ast-value-factory.h.
                                  {
    DCHECK_NOT_NULL(single_parse_zone_);
    return single_parse_zone_;
  }
References DCHECK_NOT_NULL, and single_parse_zone_.
Referenced by v8::internal::ParserBase< Impl >::main_zone(), v8::internal::FuncNameInferrer::MakeNameFromStack(), NewConsString(), and v8::internal::DeclarationScope::ResetAfterPreparsing().
Member Data Documentation
ast_raw_string_zone_
Zone* v8::internal::AstValueFactory::ast_raw_string_zone_ [private]
Definition at line 433 of file ast-value-factory.h.
Referenced by ast_raw_string_zone(), and AstValueFactory().
empty_cons_string_
AstConsString* v8::internal::AstValueFactory::empty_cons_string_ [private]
Definition at line 431 of file ast-value-factory.h.
Referenced by AstValueFactory(), and empty_cons_string().
hash_seed_
uint64_t v8::internal::AstValueFactory::hash_seed_ [private]
Definition at line 436 of file ast-value-factory.h.
Referenced by GetOneByteStringInternal(), and GetTwoByteStringInternal().
single_parse_zone_
Zone* v8::internal::AstValueFactory::single_parse_zone_ [private]
Definition at line 434 of file ast-value-factory.h.
Referenced by AstValueFactory(), and single_parse_zone().
string_constants_
const AstStringConstants* v8::internal::AstValueFactory::string_constants_ [private]
Definition at line 429 of file ast-value-factory.h.
Referenced by GetOneByteStringInternal().
string_table_
AstRawStringMap v8::internal::AstValueFactory::string_table_ [private]
Definition at line 423 of file ast-value-factory.h.
strings_
AstRawString* v8::internal::AstValueFactory::strings_ [private]
Definition at line 425 of file ast-value-factory.h.
Referenced by Internalize(), and ResetStrings().
strings_end_
AstRawString** v8::internal::AstValueFactory::strings_end_ [private]
Definition at line 426 of file ast-value-factory.h.
Referenced by AddString(), and ResetStrings().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast-value-factory.h
/mnt/V8SourceCode/src/ast/ast-value-factory.cc