v8::internal::CancelableIdleTask Class Reference
#include <cancelable-task.h>
Public Member Functions
CancelableIdleTask (Isolate *isolate)
CancelableIdleTask (CancelableTaskManager *manager)
CancelableIdleTask (const CancelableIdleTask &)=delete
CancelableIdleTask & operator= (const CancelableIdleTask &)=delete
void Run (double deadline_in_seconds) final
virtual void RunInternal (double deadline_in_seconds)=0
Additional Inherited Members
Detailed Description
Definition at line 163 of file cancelable-task.h.
Constructor & Destructor Documentation
CancelableIdleTask() [1/3]
v8::internal::CancelableIdleTask::CancelableIdleTask (Isolate * isolate) [explicit]
Definition at line 127 of file cancelable-task.cc.
    : CancelableIdleTask(isolate->cancelable_task_manager()) {}
CancelableIdleTask() [2/3]
v8::internal::CancelableIdleTask::CancelableIdleTask (CancelableTaskManager * manager) [explicit]
Definition at line 130 of file cancelable-task.cc.
    : Cancelable(manager) {}
CancelableIdleTask() [3/3]
v8::internal::CancelableIdleTask::CancelableIdleTask (const CancelableIdleTask &) [delete]
Member Function Documentation
operator=()
CancelableIdleTask& v8::internal::CancelableIdleTask::operator= (const CancelableIdleTask &) [delete]
Run()
void v8::internal::CancelableIdleTask::Run (double deadline_in_seconds) [inline], [final], [virtual]
Implements v8::IdleTask.
Definition at line 171 of file cancelable-task.h.
                                             {
    if (TryRun()) {
      RunInternal(deadline_in_seconds);
    }
  }
References RunInternal(), and v8::internal::Cancelable::TryRun().
RunInternal()
virtual void v8::internal::CancelableIdleTask::RunInternal (double deadline_in_seconds) [pure virtual]
Implemented in v8::internal::IdleTaskOnContextDispose, and v8::internal::anonymous_namespace{task-utils.cc}::CancelableIdleFuncTask.
Referenced by Run().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/tasks/cancelable-task.h
/mnt/V8SourceCode/src/tasks/cancelable-task.cc