v8::internal::wasm::FastZoneVector< T > Class Template Reference
#include <function-body-decoder-impl.h>
Public Member Functions
FastZoneVector ()=default
FastZoneVector (int initial_size, Zone *zone)
void Reset (Zone *zone)
T * begin () const
T * end () const
T & front ()
T & back ()
uint32_t size () const
bool empty () const
T & operator[] (uint32_t index)
void shrink_to (uint32_t new_size)
void pop (uint32_t num=1)
void push (T value)
template<typename... Args>
void emplace_back (Args &&... args)
void EnsureMoreCapacity (int slots_needed, Zone *zone)
Private Member Functions
V8_NOINLINE V8_PRESERVE_MOST void Grow (int slots_needed, Zone *zone)
Private Attributes
T * begin_ = nullptr
T * end_ = nullptr
T * capacity_end_ = nullptr
Detailed Description
template<typename T>
class v8::internal::wasm::FastZoneVector< T >
Definition at line 1622 of file function-body-decoder-impl.h.
Constructor & Destructor Documentation
FastZoneVector() [1/2]
template<typename T >
v8::internal::wasm::FastZoneVector< T >::FastZoneVector () [default]
FastZoneVector() [2/2]
template<typename T >
v8::internal::wasm::FastZoneVector< T >::FastZoneVector (int initial_size, Zone * zone) [inline], [explicit]
Definition at line 1625 of file function-body-decoder-impl.h.
                                                        {
    Grow(initial_size, zone);
  }
References v8::internal::wasm::FastZoneVector< T >::Grow().
Member Function Documentation
back()
template<typename T >
T& v8::internal::wasm::FastZoneVector< T >::back () [inline]
Definition at line 1657 of file function-body-decoder-impl.h.
            {
    DCHECK(!empty());
    return end_[-1];
  }
References v8::internal::DCHECK(), v8::internal::wasm::FastZoneVector< T >::empty(), and v8::internal::wasm::FastZoneVector< T >::end_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Drop(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EndControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EnsureStackArguments(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EnsureStackArguments_Slow(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::FallThrough(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Pop(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopArgs(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopSomeArgs(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Push(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushMergeValues(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::requires(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::RollbackLocalsInitialization(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SetSucceedingCodeDynamicallyUnreachable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckFallThru(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge_Slow().
begin()
template<typename T >
T* v8::internal::wasm::FastZoneVector< T >::begin () const [inline]
Definition at line 1649 of file function-body-decoder-impl.h.
{ return begin_; }
References v8::internal::wasm::FastZoneVector< T >::begin_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE().
emplace_back()
template<typename T >
template<typename... Args>
void v8::internal::wasm::FastZoneVector< T >::emplace_back (Args &&... args) [inline]
Definition at line 1692 of file function-body-decoder-impl.h.
                                    {
    DCHECK_GT(capacity_end_, end_);
    new (end_) T{std::forward<Args>(args)...};
    ++end_;
  }
References v8::base::args, v8::internal::wasm::FastZoneVector< T >::capacity_end_, DCHECK_GT, and v8::internal::wasm::FastZoneVector< T >::end_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl().
empty()
template<typename T >
bool v8::internal::wasm::FastZoneVector< T >::empty () const [inline]
Definition at line 1664 of file function-body-decoder-impl.h.
{ return begin_ == end_; }
References v8::internal::wasm::FastZoneVector< T >::begin_, and v8::internal::wasm::FastZoneVector< T >::end_.
Referenced by v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Drop(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EndControl(), v8::internal::wasm::FastZoneVector< T >::front(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Pop(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl().
end()
template<typename T >
T* v8::internal::wasm::FastZoneVector< T >::end () const [inline]
Definition at line 1650 of file function-body-decoder-impl.h.
{ return end_; }
References v8::internal::wasm::FastZoneVector< T >::end_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_at(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopArgs(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopSomeArgs(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushValueTypes(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::requires(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_value(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge_Slow(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ValidateParameters().
EnsureMoreCapacity()
template<typename T >
void v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity (int slots_needed, Zone * zone) [inline]
Definition at line 1698 of file function-body-decoder-impl.h.
                                                                  {
    if (V8_LIKELY(capacity_end_ - end_ >= slots_needed)) return;
    Grow(slots_needed, zone);
  }
References v8::internal::wasm::FastZoneVector< T >::capacity_end_, v8::internal::wasm::FastZoneVector< T >::end_, v8::internal::wasm::FastZoneVector< T >::Grow(), and V8_LIKELY.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeEffectHandlerTable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EnsureStackArguments_Slow(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushMergeValues(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushReturns(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushValueTypes().
front()
template<typename T >
T& v8::internal::wasm::FastZoneVector< T >::front () [inline]
Definition at line 1652 of file function-body-decoder-impl.h.
             {
    DCHECK(!empty());
    return begin_[0];
  }
References v8::internal::wasm::FastZoneVector< T >::begin_, v8::internal::DCHECK(), and v8::internal::wasm::FastZoneVector< T >::empty().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DoReturn().
Grow()
template<typename T >
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::wasm::FastZoneVector< T >::Grow (int slots_needed, Zone * zone) [inline], [private]
Definition at line 1704 of file function-body-decoder-impl.h.
                                                                       {
    size_t new_capacity = std::max(
        size_t{8}, base::bits::RoundUpToPowerOfTwo(size() + slots_needed));
    CHECK_GE(kMaxUInt32, new_capacity);
    DCHECK_LT(capacity_end_ - begin_, new_capacity);
    T* new_begin = zone->template AllocateArray<T>(new_capacity);
    if (begin_) {
      for (T *ptr = begin_, *new_ptr = new_begin; ptr != end_;
           ++ptr, ++new_ptr) {
        new (new_ptr) T{std::move(*ptr)};
        ptr->~T();
      }
      zone->DeleteArray(begin_, capacity_end_ - begin_);
    }
    end_ = new_begin + (end_ - begin_);
    begin_ = new_begin;
    capacity_end_ = new_begin + new_capacity;
  }
References v8::internal::wasm::FastZoneVector< T >::begin_, v8::internal::wasm::FastZoneVector< T >::capacity_end_, CHECK_GE, DCHECK_LT, v8::internal::Zone::DeleteArray(), v8::internal::wasm::FastZoneVector< T >::end_, v8::internal::kMaxUInt32, v8::base::bits::RoundUpToPowerOfTwo(), and v8::internal::wasm::FastZoneVector< T >::size().
Referenced by v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), and v8::internal::wasm::FastZoneVector< T >::FastZoneVector().
operator[]()
template<typename T >
T& v8::internal::wasm::FastZoneVector< T >::operator[] (uint32_t index) [inline]
Definition at line 1666 of file function-body-decoder-impl.h.
                                {
    DCHECK_GE(size(), index);
    return begin_[index];
  }
References v8::internal::wasm::FastZoneVector< T >::begin_, DCHECK_GE, v8::internal::index, and v8::internal::wasm::FastZoneVector< T >::size().
pop()
template<typename T >
void v8::internal::wasm::FastZoneVector< T >::pop (uint32_t num = 1) [inline]
Definition at line 1677 of file function-body-decoder-impl.h.
                             {
    DCHECK_GE(size(), num);
    for (T* new_end = end_ - num; end_ != new_end;) {
      --end_;
      end_->~T();
    }
  }
References DCHECK_GE, v8::internal::wasm::FastZoneVector< T >::end_, and v8::internal::wasm::FastZoneVector< T >::size().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Drop(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Pop(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopArgs(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopSomeArgs(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::requires(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::RollbackLocalsInitialization().
push()
template<typename T >
void v8::internal::wasm::FastZoneVector< T >::push (T value) [inline]
Definition at line 1685 of file function-body-decoder-impl.h.
                     {
    DCHECK_GT(capacity_end_, end_);
    *end_ = std::move(value);
    ++end_;
  }
References v8::internal::wasm::FastZoneVector< T >::capacity_end_, DCHECK_GT, v8::internal::wasm::FastZoneVector< T >::end_, and v8::internal::value.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EnsureStackArguments_Slow(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Push(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::set_local_initialized().
Reset()
template<typename T >
void v8::internal::wasm::FastZoneVector< T >::Reset (Zone * zone) [inline]
Definition at line 1636 of file function-body-decoder-impl.h.
                         {
    if (begin_ == nullptr) return;
    if constexpr (!std::is_trivially_destructible_v<T>) {
      for (T* ptr = begin_; ptr != end_; ++ptr) {
        ptr->~T();
      }
    }
    zone->DeleteArray(begin_, capacity_end_ - begin_);
    begin_ = nullptr;
    end_ = nullptr;
    capacity_end_ = nullptr;
  }
References v8::internal::wasm::FastZoneVector< T >::begin_, v8::internal::wasm::FastZoneVector< T >::capacity_end_, v8::internal::Zone::DeleteArray(), and v8::internal::wasm::FastZoneVector< T >::end_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::~WasmFullDecoder().
shrink_to()
template<typename T >
void v8::internal::wasm::FastZoneVector< T >::shrink_to (uint32_t new_size) [inline]
Definition at line 1671 of file function-body-decoder-impl.h.
                                    {
    static_assert(std::is_trivially_destructible_v<T>);
    DCHECK_GE(size(), new_size);
    end_ = begin_ + new_size;
  }
References v8::internal::wasm::FastZoneVector< T >::begin_, DCHECK_GE, v8::internal::wasm::FastZoneVector< T >::end_, and v8::internal::wasm::FastZoneVector< T >::size().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeEffectHandlerTable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EndControl(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushMergeValues().
size()
template<typename T >
uint32_t v8::internal::wasm::FastZoneVector< T >::size () const [inline]
Definition at line 1662 of file function-body-decoder-impl.h.
{ return static_cast<uint32_t>(end_ - begin_); }
References v8::internal::wasm::FastZoneVector< T >::begin_, and v8::internal::wasm::FastZoneVector< T >::end_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_at(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_depth(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeEffectHandlerTable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DoReturn(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Drop(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EnsureStackArguments(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EnsureStackArguments_Slow(), v8::internal::wasm::FastZoneVector< T >::Grow(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initialization_stack_depth(), v8::internal::wasm::FastZoneVector< T >::operator[](), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek(), v8::internal::wasm::FastZoneVector< T >::pop(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushMergeValues(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::RollbackLocalsInitialization(), v8::internal::wasm::FastZoneVector< T >::shrink_to(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_size(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_value(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge_Slow().
Member Data Documentation
begin_
template<typename T >
T* v8::internal::wasm::FastZoneVector< T >::begin_ = nullptr [private]
Definition at line 1724 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::FastZoneVector< T >::begin(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::front(), v8::internal::wasm::FastZoneVector< T >::Grow(), v8::internal::wasm::FastZoneVector< T >::operator[](), v8::internal::wasm::FastZoneVector< T >::Reset(), v8::internal::wasm::FastZoneVector< T >::shrink_to(), and v8::internal::wasm::FastZoneVector< T >::size().
capacity_end_
template<typename T >
T* v8::internal::wasm::FastZoneVector< T >::capacity_end_ = nullptr [private]
Definition at line 1726 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::FastZoneVector< T >::emplace_back(), v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::wasm::FastZoneVector< T >::Grow(), v8::internal::wasm::FastZoneVector< T >::push(), and v8::internal::wasm::FastZoneVector< T >::Reset().
end_
template<typename T >
T* v8::internal::wasm::FastZoneVector< T >::end_ = nullptr [private]
Definition at line 1725 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::FastZoneVector< T >::emplace_back(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::wasm::FastZoneVector< T >::Grow(), v8::internal::wasm::FastZoneVector< T >::pop(), v8::internal::wasm::FastZoneVector< T >::push(), v8::internal::wasm::FastZoneVector< T >::Reset(), v8::internal::wasm::FastZoneVector< T >::shrink_to(), and v8::internal::wasm::FastZoneVector< T >::size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/function-body-decoder-impl.h