v8::internal::IrregexpInterpreter Class Reference
#include <regexp-interpreter.h>
Public Types
enum Result {
FAILURE = RegExp::kInternalRegExpFailure
, SUCCESS = RegExp::kInternalRegExpSuccess
, EXCEPTION = RegExp::kInternalRegExpException
, RETRY = RegExp::kInternalRegExpRetry
,
FALLBACK_TO_EXPERIMENTAL = RegExp::kInternalRegExpFallbackToExperimental
 }
Static Public Member Functions
static int MatchForCallFromRuntime (Isolate *isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject_string, int *output_registers, int output_register_count, int start_position)
static int MatchForCallFromJs (Address subject, int32_t start_position, Address input_start, Address input_end, int *output_registers, int32_t output_register_count, RegExp::CallOrigin call_origin, Isolate *isolate, Address regexp_data)
static Result MatchInternal (Isolate *isolate, Tagged< TrustedByteArray > *code_array, Tagged< String > *subject_string, int *output_registers, int output_register_count, int total_register_count, int start_position, RegExp::CallOrigin call_origin, uint32_t backtrack_limit)
Static Private Member Functions
static int Match (Isolate *isolate, Tagged< IrRegExpData > regexp_data, Tagged< String > subject_string, int *output_registers, int output_register_count, int start_position, RegExp::CallOrigin call_origin)
Detailed Description
Definition at line 17 of file regexp-interpreter.h.
Member Enumeration Documentation
Result
enum v8::internal::IrregexpInterpreter::Result
Enumerator
FAILURE
SUCCESS
EXCEPTION
RETRY
FALLBACK_TO_EXPERIMENTAL
Definition at line 19 of file regexp-interpreter.h.
              {
    FAILURE = RegExp::kInternalRegExpFailure,
    SUCCESS = RegExp::kInternalRegExpSuccess,
    EXCEPTION = RegExp::kInternalRegExpException,
    RETRY = RegExp::kInternalRegExpRetry,
    FALLBACK_TO_EXPERIMENTAL = RegExp::kInternalRegExpFallbackToExperimental,
  };
Member Function Documentation
Match()
int v8::internal::IrregexpInterpreter::Match (Isolate * isolate, Tagged< IrRegExpData > regexp_data, Tagged< String > subject_string, int * output_registers, int output_register_count, int start_position, RegExp::CallOrigin call_origin) [static], [private]
Definition at line 1068 of file regexp-interpreter.cc.
                                                             {
  if (v8_flags.regexp_tier_up) regexp_data->TierUpTick();
  bool is_any_unicode =
      IsEitherUnicode(JSRegExp::AsRegExpFlags(regexp_data->flags()));
  bool is_one_byte = String::IsOneByteRepresentationUnderneath(subject_string);
  Tagged<TrustedByteArray> code_array = regexp_data->bytecode(is_one_byte);
  int total_register_count = regexp_data->max_register_count();
  // MatchInternal only supports returning a single match per call. In global
  // mode, i.e. when output_registers has space for more than one match, we
  // need to keep running until all matches are filled in.
  int registers_per_match =
      JSRegExp::RegistersForCaptureCount(regexp_data->capture_count());
  DCHECK_LE(registers_per_match, output_register_count);
  int number_of_matches_in_output_registers =
      output_register_count / registers_per_match;
  int backtrack_limit = regexp_data->backtrack_limit();
  int num_matches = 0;
  int* current_output_registers = output_registers;
  for (int i = 0; i < number_of_matches_in_output_registers; i++) {
    auto current_result = MatchInternal(
        isolate, &code_array, &subject_string, current_output_registers,
        registers_per_match, total_register_count, start_position, call_origin,
        backtrack_limit);
    if (current_result == SUCCESS) {
      // Fall through.
    } else if (current_result == FAILURE) {
      break;
    } else {
      DCHECK(current_result == EXCEPTION ||
             current_result == FALLBACK_TO_EXPERIMENTAL ||
             current_result == RETRY);
      return current_result;
    }
    // Found a match. Advance the index.
    num_matches++;
    int next_start_position = current_output_registers[1];
    if (next_start_position == current_output_registers[0]) {
      // Zero-length matches.
      // TODO(jgruber): Use AdvanceStringIndex based on flat contents instead.
      next_start_position = static_cast<int>(RegExpUtils::AdvanceStringIndex(
          subject_string, next_start_position, is_any_unicode));
      if (next_start_position > static_cast<int>(subject_string->length())) {
        break;
      }
    }
    start_position = next_start_position;
    current_output_registers += registers_per_match;
  }
  return num_matches;
}
References v8::internal::RegExpUtils::AdvanceStringIndex(), v8::internal::JSRegExp::AsRegExpFlags(), v8::internal::call_origin, v8::internal::DCHECK(), DCHECK_LE, EXCEPTION, FAILURE, FALLBACK_TO_EXPERIMENTAL, v8::internal::IsEitherUnicode(), v8::internal::String::IsOneByteRepresentationUnderneath(), MatchInternal(), v8::internal::JSRegExp::RegistersForCaptureCount(), RETRY, SUCCESS, and v8::internal::v8_flags.
Referenced by MatchForCallFromJs(), and MatchForCallFromRuntime().
MatchForCallFromJs()
int v8::internal::IrregexpInterpreter::MatchForCallFromJs (Address subject, int32_t start_position, Address input_start, Address input_end, int * output_registers, int32_t output_register_count, RegExp::CallOrigin call_origin, Isolate * isolate, Address regexp_data) [static]
Definition at line 1180 of file regexp-interpreter.cc.
                                                                         {
  // TODO(422992937): investigate running the interpreter in sandboxed mode.
  ExitSandboxScope unsandboxed;
  DCHECK_NOT_NULL(isolate);
  DCHECK_NOT_NULL(output_registers);
  DCHECK(call_origin == RegExp::CallOrigin::kFromJs);
  DisallowGarbageCollection no_gc;
  DisallowJavascriptExecution no_js(isolate);
  DisallowHandleAllocation no_handles;
  DisallowHandleDereference no_deref;
  Tagged<String> subject_string = Cast<String>(Tagged<Object>(subject));
  Tagged<IrRegExpData> regexp_data_obj =
      Cast<IrRegExpData>(Tagged<Object>(regexp_data));
  if (regexp_data_obj->MarkedForTierUp()) {
    // Returning RETRY will re-enter through runtime, where actual recompilation
    // for tier-up takes place.
    return IrregexpInterpreter::RETRY;
  }
  return Match(isolate, regexp_data_obj, subject_string, output_registers,
               output_register_count, start_position, call_origin);
}
References v8::internal::call_origin, v8::internal::DCHECK(), DCHECK_NOT_NULL, Match(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and RETRY.
MatchForCallFromRuntime()
int v8::internal::IrregexpInterpreter::MatchForCallFromRuntime (Isolate * isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject_string, int * output_registers, int output_register_count, int start_position) [static]
Definition at line 1212 of file regexp-interpreter.cc.
                                                   {
  return Match(isolate, *regexp_data, *subject_string, output_registers,
               output_register_count, start_position,
               RegExp::CallOrigin::kFromRuntime);
}
References Match().
Referenced by v8::internal::RegExpImpl::IrregexpExecRaw().
MatchInternal()
IrregexpInterpreter::Result v8::internal::IrregexpInterpreter::MatchInternal (Isolate * isolate, Tagged< TrustedByteArray > * code_array, Tagged< String > * subject_string, int * output_registers, int output_register_count, int total_register_count, int start_position, RegExp::CallOrigin call_origin, uint32_t backtrack_limit) [static]
Definition at line 1134 of file regexp-interpreter.cc.
                                                            {
  DCHECK((*subject_string)->IsFlat());
  // Note: Heap allocation *is* allowed in two situations if calling from
  // Runtime:
  // 1. When creating & throwing a stack overflow exception. The interpreter
  // aborts afterwards, and thus possible-moved objects are never used.
  // 2. When handling interrupts. We manually relocate unhandlified references
  // after interrupts have run.
  DisallowGarbageCollection no_gc;
  base::uc16 previous_char = '\n';
  String::FlatContent subject_content =
      (*subject_string)->GetFlatContent(no_gc);
  // Because interrupts can result in GC and string content relocation, the
  // checksum verification in FlatContent may fail even though this code is
  // safe. See (2) above.
  subject_content.UnsafeDisableChecksumVerification();
  if (subject_content.IsOneByte()) {
    base::Vector<const uint8_t> subject_vector =
        subject_content.ToOneByteVector();
    if (start_position != 0) previous_char = subject_vector[start_position - 1];
    return RawMatch(isolate, code_array, subject_string, subject_vector,
                    output_registers, output_register_count,
                    total_register_count, start_position, previous_char,
                    call_origin, backtrack_limit);
  } else {
    DCHECK(subject_content.IsTwoByte());
    base::Vector<const base::uc16> subject_vector =
        subject_content.ToUC16Vector();
    if (start_position != 0) previous_char = subject_vector[start_position - 1];
    return RawMatch(isolate, code_array, subject_string, subject_vector,
                    output_registers, output_register_count,
                    total_register_count, start_position, previous_char,
                    call_origin, backtrack_limit);
  }
}
References v8::internal::call_origin, v8::internal::DCHECK(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::FlatContent::IsTwoByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch(), v8::internal::String::FlatContent::ToOneByteVector(), v8::internal::String::FlatContent::ToUC16Vector(), and v8::internal::String::FlatContent::UnsafeDisableChecksumVerification().
Referenced by Match().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-interpreter.h
/mnt/V8SourceCode/src/regexp/regexp-interpreter.cc