cppgc::internal::PersistentRegionLock Class Reference
#include <persistent-node.h>
Public Member Functions
PersistentRegionLock ()
~PersistentRegionLock ()
Static Public Member Functions
static void AssertLocked ()
Detailed Description
Definition at line 174 of file persistent-node.h.
Constructor & Destructor Documentation
PersistentRegionLock()
cppgc::internal::PersistentRegionLock::PersistentRegionLock ()
Definition at line 119 of file persistent-node.cc.
                                           {
  ProcessGlobalLock::Lock<
      ProcessGlobalLock::Reason::kForCrossThreadHandleCreation>();
}
 PersistentRegionLock()
cppgc::internal::PersistentRegionLock::~PersistentRegionLock ()
Definition at line 124 of file persistent-node.cc.
                                            {
  ProcessGlobalLock::Unlock<
      ProcessGlobalLock::Reason::kForCrossThreadHandleCreation>();
}
Member Function Documentation
AssertLocked()
void cppgc::internal::PersistentRegionLock::AssertLocked () [static]
Definition at line 130 of file persistent-node.cc.
{ ProcessGlobalLock::AssertHeld(); }
Referenced by cppgc::internal::CrossThreadPersistentRegion::AllocateNode(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe(), cppgc::internal::CrossThreadPersistentRegion::ClearAllUsedNodes(), cppgc::internal::CrossThreadPersistentRegion::FreeNode(), and cppgc::internal::CrossThreadPersistentRegion::Iterate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/persistent-node.h
/mnt/V8SourceCode/src/heap/cppgc/persistent-node.cc