v8::internal::SeqOneByteString Class Reference
#include <string.h>
Classes
class BodyDescriptor
Public Types
using Char = uint8_t
Public Member Functions
uint8_t Get (uint32_t index) const
uint8_t Get (uint32_t index, const SharedStringAccessGuardIfNeeded &access_guard) const
void SeqOneByteStringSet (uint32_t index, uint16_t value)
void SeqOneByteStringSetChars (uint32_t index, const uint8_t *string, uint32_t length)
Address GetCharsAddress () const
uint8_t * GetChars (const DisallowGarbageCollection &no_gc)
uint8_t * GetChars (const DisallowGarbageCollection &no_gc, const SharedStringAccessGuardIfNeeded &access_guard)
DataAndPaddingSizes GetDataAndPaddingSizes () const
void clear_padding_destructively (uint32_t length)
int AllocatedSize () const
Static Public Member Functions
static constexpr int32_t DataSizeFor (int32_t length)
static constexpr int32_t SizeFor (int32_t length)
static bool IsCompatibleMap (Tagged< Map > map, ReadOnlyRoots roots)
Static Public Attributes
static const bool kHasOneByteEncoding = true
static const uint32_t kMaxCharsSize = kMaxLength
Private Member Functions
FLEXIBLE_ARRAY_MEMBER (Char, chars)
Friends
struct OffsetsForDebug
class CodeStubAssembler
class ToDirectStringAssembler
class IntlBuiltinsAssembler
class StringBuiltinsAssembler
class StringFromCharCodeAssembler
class SandboxTesting
class maglev::MaglevAssembler
class compiler::AccessBuilder
class TorqueGeneratedSeqOneByteStringAsserts
Additional Inherited Members
Detailed Description
Definition at line 860 of file string.h.
Member Typedef Documentation
Char
using v8::internal::SeqOneByteString::Char = uint8_t
Definition at line 863 of file string.h.
Member Function Documentation
AllocatedSize()
int v8::internal::SeqOneByteString::AllocatedSize () const [inline]
Definition at line 1370 of file string-inl.h.
                                                 {
  return SizeFor(length(kAcquireLoad));
}
References v8::kAcquireLoad, and v8::internal::String::length().
clear_padding_destructively()
void v8::internal::SeqOneByteString::clear_padding_destructively (uint32_t length) [inline]
Definition at line 1841 of file string-inl.h.
                                                                  {
  // Ensure we are not killing the map word, which is already set at this point
  static_assert(SizeFor(0) >= kObjectAlignment + kTaggedSize);
  memset(reinterpret_cast<void*>(reinterpret_cast<char*>(this) +
                                 SizeFor(length) - kObjectAlignment),
         0, kObjectAlignment);
}
References v8::internal::kObjectAlignment, v8::internal::kTaggedSize, v8::internal::String::length(), and SizeFor().
DataSizeFor()
constexpr int32_t v8::internal::SeqOneByteString::DataSizeFor (int32_t length) [inline], [static], [constexpr]
Definition at line 1349 of file string-inl.h.
                                                                        {
  return sizeof(SeqOneByteString) + length * sizeof(Char);
}
References v8::internal::String::length().
Referenced by SizeFor().
FLEXIBLE_ARRAY_MEMBER()
v8::internal::SeqOneByteString::FLEXIBLE_ARRAY_MEMBER (Char , chars) [private]
Get() [1/2]
uint8_t v8::internal::SeqOneByteString::Get (uint32_t index) const [inline]
Definition at line 1270 of file string-inl.h.
                                                  {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  return Get(index, SharedStringAccessGuardIfNeeded::NotNeeded());
}
References v8::internal::DCHECK(), v8::internal::String::Get(), v8::internal::index, v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), and v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded().
Get() [2/2]
uint8_t v8::internal::SeqOneByteString::Get (uint32_t index, const SharedStringAccessGuardIfNeeded & access_guard) const [inline]
Definition at line 1275 of file string-inl.h.
                                                                               {
  USE(access_guard);
  DCHECK(index >= 0 && index < length());
  return chars()[index];
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::String::length(), and USE.
GetChars() [1/2]
uint8_t * v8::internal::SeqOneByteString::GetChars (const DisallowGarbageCollection & no_gc) [inline]
Definition at line 1303 of file string-inl.h.
                                                                          {
  USE(no_gc);
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  return chars();
}
References v8::internal::DCHECK(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and USE.
GetChars() [2/2]
uint8_t * v8::internal::SeqOneByteString::GetChars (const DisallowGarbageCollection & no_gc, const SharedStringAccessGuardIfNeeded & access_guard) [inline]
Definition at line 1309 of file string-inl.h.
                                                         {
  USE(no_gc);
  USE(access_guard);
  return chars();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and USE.
GetCharsAddress()
Address v8::internal::SeqOneByteString::GetCharsAddress () const [inline]
Definition at line 1299 of file string-inl.h.
                                                {
  return reinterpret_cast<Address>(&chars()[0]);
}
GetDataAndPaddingSizes()
SeqString::DataAndPaddingSizes v8::internal::SeqOneByteString::GetDataAndPaddingSizes () const
Definition at line 1966 of file string.cc.
          {
  int data_size = sizeof(SeqOneByteString) + length() * kOneByteSize;
  int padding_size = SizeFor(length()) - data_size;
  return DataAndPaddingSizes{data_size, padding_size};
}
References v8::internal::kOneByteSize, and v8::internal::length.
IsCompatibleMap()
bool v8::internal::SeqOneByteString::IsCompatibleMap (Tagged< Map > map, ReadOnlyRoots roots) [inline], [static]
Definition at line 1378 of file string-inl.h.
                                                                           {
  return map == roots.seq_one_byte_string_map() ||
         map == roots.shared_seq_one_byte_string_map();
}
References v8::internal::HeapObjectLayout::map().
SeqOneByteStringSet()
void v8::internal::SeqOneByteString::SeqOneByteStringSet (uint32_t index, uint16_t value) [inline]
Definition at line 1282 of file string-inl.h.
                                                                         {
  DisallowGarbageCollection no_gc;
  DCHECK_GE(index, 0);
  DCHECK_LT(index, length());
  DCHECK_LE(value, kMaxOneByteCharCode);
  chars()[index] = value;
}
References DCHECK_GE, DCHECK_LE, DCHECK_LT, v8::internal::index, v8::internal::String::kMaxOneByteCharCode, v8::internal::String::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
SeqOneByteStringSetChars()
void v8::internal::SeqOneByteString::SeqOneByteStringSetChars (uint32_t index, const uint8_t * string, uint32_t length) [inline]
Definition at line 1290 of file string-inl.h.
                                                                        {
  DisallowGarbageCollection no_gc;
  DCHECK_LT(index + string_length, length());
  void* address = static_cast<void*>(&chars()[index]);
  memcpy(address, string, string_length);
}
References v8::internal::HeapObjectLayout::address(), DCHECK_LT, v8::internal::index, v8::internal::String::length(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
SizeFor()
constexpr int32_t v8::internal::SeqOneByteString::SizeFor (int32_t length) [inline], [static], [constexpr]
Definition at line 1359 of file string-inl.h.
                                                                    {
  return OBJECT_POINTER_ALIGN(SeqOneByteString::DataSizeFor(length));
}
References DataSizeFor(), v8::internal::String::length(), and OBJECT_POINTER_ALIGN.
Referenced by v8::internal::FactoryBase< Impl >::AllocateRawOneByteInternalizedString(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), clear_padding_destructively(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::anonymous_namespace{bigint.cc}::RightTrimString(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::HeapObject::SizeFromMap(), v8::internal::maglev::MaglevAssembler::ToBoolean(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TruncateJSPrimitiveToUntagged().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 908 of file string.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 915 of file string.h.
IntlBuiltinsAssembler
friend class IntlBuiltinsAssembler [friend]
Definition at line 910 of file string.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 914 of file string.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 907 of file string.h.
SandboxTesting
friend class SandboxTesting [friend]
Definition at line 913 of file string.h.
StringBuiltinsAssembler
friend class StringBuiltinsAssembler [friend]
Definition at line 911 of file string.h.
StringFromCharCodeAssembler
friend class StringFromCharCodeAssembler [friend]
Definition at line 912 of file string.h.
ToDirectStringAssembler
friend class ToDirectStringAssembler [friend]
Definition at line 909 of file string.h.
TorqueGeneratedSeqOneByteStringAsserts
friend class TorqueGeneratedSeqOneByteStringAsserts [friend]
Definition at line 916 of file string.h.
Member Data Documentation
kHasOneByteEncoding
const bool v8::internal::SeqOneByteString::kHasOneByteEncoding = true [static]
Definition at line 862 of file string.h.
kMaxCharsSize
const uint32_t v8::internal::SeqOneByteString::kMaxCharsSize = kMaxLength [static]
Definition at line 897 of file string.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h
/mnt/V8SourceCode/src/objects/string.cc