v8::internal::wasm::ParallelMove Class Reference
#include <parallel-move.h>
Classes
struct RegisterLoad
struct RegisterMove
Public Member Functions
ParallelMove (LiftoffAssembler *wasm_asm)
ParallelMove (const ParallelMove &)=delete
ParallelMove & operator= (const ParallelMove &)=delete
~ParallelMove ()
void Execute ()
void Transfer (const VarState &dst, const VarState &src)
void TransferToStack (int dst_offset, const VarState &src)
void LoadIntoRegister (LiftoffRegister dst, const VarState &src)
void LoadI64HalfIntoRegister (LiftoffRegister dst, const VarState &src, RegPairHalf half)
void MoveRegister (LiftoffRegister dst, LiftoffRegister src, ValueKind kind)
void LoadConstant (LiftoffRegister dst, ValueKind kind, int32_t constant)
void LoadStackSlot (LiftoffRegister dst, int stack_offset, ValueKind kind)
void LoadI64HalfStackSlot (LiftoffRegister dst, int offset, RegPairHalf half)
Private Types
using VarState = LiftoffAssembler::VarState
Private Member Functions
RegisterMove * register_move (LiftoffRegister reg)
RegisterLoad * register_load (LiftoffRegister reg)
int * src_reg_use_count (LiftoffRegister reg)
void ExecuteMove (LiftoffRegister dst)
void ClearExecutedMove (LiftoffRegister dst)
V8_NOINLINE V8_PRESERVE_MOST void ExecuteMoves ()
V8_NOINLINE V8_PRESERVE_MOST void ExecuteLoads ()
Private Attributes
char register_moves_ [kAfterMaxLiftoffRegCode *sizeof(RegisterMove)]
char register_loads_ [kAfterMaxLiftoffRegCode *sizeof(RegisterLoad)]
int src_reg_use_count_ [kAfterMaxLiftoffRegCode] = {0}
LiftoffRegList move_dst_regs_
LiftoffRegList load_dst_regs_
LiftoffAssembler *const asm_
int last_spill_offset_
Detailed Description
Definition at line 24 of file parallel-move.h.
Member Typedef Documentation
VarState
using v8::internal::wasm::ParallelMove::VarState = LiftoffAssembler::VarState [private]
Definition at line 25 of file parallel-move.h.
Constructor & Destructor Documentation
ParallelMove() [1/2]
v8::internal::wasm::ParallelMove::ParallelMove (LiftoffAssembler * wasm_asm) [inline], [explicit]
Definition at line 15 of file parallel-move-inl.h.
    : asm_(wasm_asm), last_spill_offset_(asm_->TopSpillOffset()) {}
ParallelMove() [2/2]
v8::internal::wasm::ParallelMove::ParallelMove (const ParallelMove &) [delete]
 ParallelMove()
v8::internal::wasm::ParallelMove::~ParallelMove () [inline]
Definition at line 74 of file parallel-move.h.
{ Execute(); }
References Execute().
Member Function Documentation
ClearExecutedMove()
void v8::internal::wasm::ParallelMove::ClearExecutedMove (LiftoffRegister dst) [inline], [private]
Definition at line 273 of file parallel-move.h.
                                              {
    DCHECK(move_dst_regs_.has(dst));
    move_dst_regs_.clear(dst);
    RegisterMove* move = register_move(dst);
    DCHECK_LT(0, *src_reg_use_count(move->src));
    if (--*src_reg_use_count(move->src)) return;
    // src count dropped to zero. If this is a destination register, execute
    // that move now.
    if (!move_dst_regs_.has(move->src)) return;
    ExecuteMove(move->src);
  }
References v8::internal::wasm::LiftoffRegList::clear(), v8::internal::DCHECK(), DCHECK_LT, ExecuteMove(), v8::internal::wasm::LiftoffRegList::has(), move_dst_regs_, register_move(), v8::internal::wasm::ParallelMove::RegisterMove::src, and src_reg_use_count().
Referenced by ExecuteMove(), and ExecuteMoves().
Execute()
void v8::internal::wasm::ParallelMove::Execute () [inline]
Definition at line 76 of file parallel-move.h.
                           {
    // First, execute register moves. Then load constants and stack values into
    // registers.
    if (!move_dst_regs_.is_empty()) ExecuteMoves();
    DCHECK(move_dst_regs_.is_empty());
    if (!load_dst_regs_.is_empty()) ExecuteLoads();
    DCHECK(load_dst_regs_.is_empty());
    // Tell the compiler that the ParallelMove is empty after this, so it
    // can eliminate a second {Execute} in the destructor.
    bool all_done = move_dst_regs_.is_empty() && load_dst_regs_.is_empty();
    V8_ASSUME(all_done);
  }
References v8::internal::DCHECK(), ExecuteLoads(), ExecuteMoves(), v8::internal::wasm::LiftoffRegList::is_empty(), load_dst_regs_, move_dst_regs_, and V8_ASSUME.
Referenced by ~ParallelMove().
ExecuteLoads()
void v8::internal::wasm::ParallelMove::ExecuteLoads () [private]
Definition at line 72 of file parallel-move.cc.
                                {
  for (LiftoffRegister dst : load_dst_regs_) {
    RegisterLoad* load = register_load(dst);
    switch (load->load_kind) {
      case RegisterLoad::kNop:
        break;
      case RegisterLoad::kConstant:
        asm_->LoadConstant(dst, load->kind == kI64
                                    ? WasmValue(int64_t{load->value})
                                    : WasmValue(int32_t{load->value}));
        break;
      case RegisterLoad::kStack:
        if (kNeedS128RegPair && load->kind == kS128) {
          asm_->Fill(LiftoffRegister::ForFpPair(dst.fp()), load->value,
                     load->kind);
        } else {
          asm_->Fill(dst, load->value, load->kind);
        }
        break;
      case RegisterLoad::kLowHalfStack:
        // Half of a register pair, {dst} must be a gp register.
        asm_->FillI64Half(dst.gp(), load->value, kLowWord);
        break;
      case RegisterLoad::kHighHalfStack:
        // Half of a register pair, {dst} must be a gp register.
        asm_->FillI64Half(dst.gp(), load->value, kHighWord);
        break;
    }
  }
  load_dst_regs_ = {};
}
References asm_, v8::internal::wasm::LiftoffAssembler::Fill(), v8::internal::wasm::LiftoffAssembler::FillI64Half(), v8::internal::wasm::LiftoffRegister::ForFpPair(), v8::internal::wasm::ParallelMove::RegisterLoad::kConstant, v8::internal::wasm::ParallelMove::RegisterLoad::kHighHalfStack, v8::internal::wasm::kHighWord, v8::internal::kI64, v8::internal::wasm::ParallelMove::RegisterLoad::kind, v8::internal::wasm::ParallelMove::RegisterLoad::kLowHalfStack, v8::internal::wasm::kLowWord, v8::internal::wasm::kNeedS128RegPair, v8::internal::wasm::ParallelMove::RegisterLoad::kNop, v8::internal::kS128, v8::internal::wasm::ParallelMove::RegisterLoad::kStack, load_dst_regs_, v8::internal::wasm::ParallelMove::RegisterLoad::load_kind, v8::internal::wasm::LiftoffAssembler::LoadConstant(), register_load(), and v8::internal::wasm::ParallelMove::RegisterLoad::value.
Referenced by Execute().
ExecuteMove()
void v8::internal::wasm::ParallelMove::ExecuteMove (LiftoffRegister dst) [inline], [private]
Definition at line 266 of file parallel-move.h.
                                        {
    RegisterMove* move = register_move(dst);
    DCHECK_EQ(0, *src_reg_use_count(dst));
    asm_->Move(dst, move->src, move->kind);
    ClearExecutedMove(dst);
  }
References asm_, ClearExecutedMove(), DCHECK_EQ, v8::internal::wasm::ParallelMove::RegisterMove::kind, v8::internal::wasm::LiftoffAssembler::Move(), register_move(), v8::internal::wasm::ParallelMove::RegisterMove::src, and src_reg_use_count().
Referenced by ClearExecutedMove(), and ExecuteMoves().
ExecuteMoves()
void v8::internal::wasm::ParallelMove::ExecuteMoves () [private]
Definition at line 46 of file parallel-move.cc.
                                {
  // Execute all moves whose {dst} is not being used as src in another move.
  // If any src count drops to zero, also (transitively) execute the
  // corresponding move to that register.
  for (LiftoffRegister dst : move_dst_regs_) {
    // Check if already handled via transitivity in {ClearExecutedMove}.
    if (!move_dst_regs_.has(dst)) continue;
    if (*src_reg_use_count(dst)) continue;
    ExecuteMove(dst);
  }
  // All remaining moves are parts of a cycle. Just spill the first one, then
  // process all remaining moves in that cycle. Repeat for all cycles.
  while (!move_dst_regs_.is_empty()) {
    // TODO(clemensb): Use an unused register if available.
    LiftoffRegister dst = move_dst_regs_.GetFirstRegSet();
    RegisterMove* move = register_move(dst);
    last_spill_offset_ += LiftoffAssembler::SlotSizeForType(move->kind);
    LiftoffRegister spill_reg = move->src;
    asm_->Spill(last_spill_offset_, spill_reg, move->kind);
    // Remember to reload into the destination register later.
    LoadStackSlot(dst, last_spill_offset_, move->kind);
    ClearExecutedMove(dst);
  }
}
References asm_, ClearExecutedMove(), ExecuteMove(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffRegList::is_empty(), v8::internal::wasm::ParallelMove::RegisterMove::kind, last_spill_offset_, LoadStackSlot(), move_dst_regs_, register_move(), v8::internal::wasm::LiftoffAssembler::SlotSizeForType(), v8::internal::wasm::LiftoffAssembler::Spill(), v8::internal::wasm::ParallelMove::RegisterMove::src, and src_reg_use_count().
Referenced by Execute().
LoadConstant()
void v8::internal::wasm::ParallelMove::LoadConstant (LiftoffRegister dst, ValueKind kind, int32_t constant) [inline]
Definition at line 185 of file parallel-move.h.
                                                                           {
    DCHECK(!load_dst_regs_.has(dst));
    load_dst_regs_.set(dst);
    if (dst.is_gp_pair()) {
      DCHECK_EQ(kI64, kind);
      *register_load(dst.low()) = RegisterLoad::Const(kI32, constant);
      // The high word is either 0 or 0xffffffff.
      *register_load(dst.high()) = RegisterLoad::Const(kI32, constant >> 31);
    } else {
      *register_load(dst) = RegisterLoad::Const(kind, constant);
    }
  }
References v8::internal::wasm::ParallelMove::RegisterLoad::Const(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), v8::internal::kI32, v8::internal::kI64, load_dst_regs_, v8::internal::wasm::LiftoffRegister::low(), register_load(), and v8::internal::wasm::LiftoffRegList::set().
Referenced by LoadI64HalfIntoRegister(), and LoadIntoRegister().
LoadI64HalfIntoRegister()
void v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister (LiftoffRegister dst, const VarState & src, RegPairHalf half) [inline]
Definition at line 117 of file parallel-move.h.
                                                 {
    // Use CHECK such that the remaining code is statically dead if
    // {kNeedI64RegPair} is false.
    CHECK(kNeedI64RegPair);
    DCHECK_EQ(kI64, src.kind());
    switch (src.loc()) {
      case VarState::kStack:
        LoadI64HalfStackSlot(dst, src.offset(), half);
        break;
      case VarState::kRegister: {
        LiftoffRegister src_half =
            half == kLowWord ? src.reg().low() : src.reg().high();
        if (dst != src_half) MoveRegister(dst, src_half, kI32);
        break;
      }
      case VarState::kIntConst:
        int32_t value = src.i32_const();
        // The high word is the sign extension of the low word.
        if (half == kHighWord) value = value >> 31;
        LoadConstant(dst, kI32, value);
        break;
    }
  }
References CHECK, DCHECK_EQ, v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::wasm::kHighWord, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::wasm::LiftoffVarState::kIntConst, v8::internal::wasm::kLowWord, v8::internal::wasm::kNeedI64RegPair, v8::internal::wasm::LiftoffVarState::kRegister, v8::internal::wasm::LiftoffVarState::kStack, LoadConstant(), LoadI64HalfStackSlot(), v8::internal::wasm::LiftoffVarState::loc(), v8::internal::wasm::LiftoffRegister::low(), MoveRegister(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), and v8::internal::value.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers().
LoadI64HalfStackSlot()
void v8::internal::wasm::ParallelMove::LoadI64HalfStackSlot (LiftoffRegister dst, int offset, RegPairHalf half) [inline]
Definition at line 230 of file parallel-move.h.
                                                                               {
    if (load_dst_regs_.has(dst)) {
      // It can happen that we spilled the same register to different stack
      // slots, and then we reload them later into the same dst register.
      // In that case, it is enough to load one of the stack slots.
      return;
    }
    load_dst_regs_.set(dst);
    *register_load(dst) = RegisterLoad::HalfStack(offset, half);
  }
References v8::internal::wasm::ParallelMove::RegisterLoad::HalfStack(), v8::internal::wasm::LiftoffRegList::has(), load_dst_regs_, register_load(), and v8::internal::wasm::LiftoffRegList::set().
Referenced by LoadI64HalfIntoRegister().
LoadIntoRegister()
void v8::internal::wasm::ParallelMove::LoadIntoRegister (LiftoffRegister dst, const VarState & src) [inline]
Definition at line 105 of file parallel-move.h.
                                                                            {
    if (src.is_reg()) {
      DCHECK_EQ(dst.reg_class(), src.reg_class());
      if (dst != src.reg()) MoveRegister(dst, src.reg(), src.kind());
    } else if (src.is_stack()) {
      LoadStackSlot(dst, src.offset(), src.kind());
    } else {
      DCHECK(src.is_const());
      LoadConstant(dst, src.kind(), src.i32_const());
    }
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::is_stack(), v8::internal::wasm::LiftoffVarState::kind(), LoadConstant(), LoadStackSlot(), MoveRegister(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::wasm::LiftoffRegister::reg_class(), and v8::internal::wasm::LiftoffVarState::reg_class().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), and Transfer().
LoadStackSlot()
void v8::internal::wasm::ParallelMove::LoadStackSlot (LiftoffRegister dst, int stack_offset, ValueKind kind) [inline]
Definition at line 198 of file parallel-move.h.
                                                                            {
    V8_ASSUME(stack_offset > 0);
    if (load_dst_regs_.has(dst)) {
      // It can happen that we spilled the same register to different stack
      // slots, and then we reload them later into the same dst register.
      // In that case, it is enough to load one of the stack slots.
      return;
    }
    load_dst_regs_.set(dst);
    // Make sure that we only spill to positions after this stack offset to
    // avoid overwriting the content.
    if (stack_offset > last_spill_offset_) {
      last_spill_offset_ = stack_offset;
    }
    if (dst.is_gp_pair()) {
      DCHECK_EQ(kI64, kind);
      *register_load(dst.low()) =
          RegisterLoad::HalfStack(stack_offset, kLowWord);
      *register_load(dst.high()) =
          RegisterLoad::HalfStack(stack_offset, kHighWord);
    } else if (dst.is_fp_pair()) {
      DCHECK_EQ(kS128, kind);
      // Only need register_load for low_gp since we load 128 bits at one go.
      // Both low and high need to be set in load_dst_regs_ but when iterating
      // over it, both low and high will be cleared, so we won't load twice.
      *register_load(dst.low()) = RegisterLoad::Stack(stack_offset, kind);
      *register_load(dst.high()) = RegisterLoad::Nop();
    } else {
      *register_load(dst) = RegisterLoad::Stack(stack_offset, kind);
    }
  }
References DCHECK_EQ, v8::internal::wasm::ParallelMove::RegisterLoad::HalfStack(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_fp_pair(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), v8::internal::wasm::kHighWord, v8::internal::kI64, v8::internal::wasm::kLowWord, v8::internal::kS128, last_spill_offset_, load_dst_regs_, v8::internal::wasm::LiftoffRegister::low(), v8::internal::wasm::ParallelMove::RegisterLoad::Nop(), register_load(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::wasm::ParallelMove::RegisterLoad::Stack(), and V8_ASSUME.
Referenced by ExecuteMoves(), and LoadIntoRegister().
MoveRegister()
void v8::internal::wasm::ParallelMove::MoveRegister (LiftoffRegister dst, LiftoffRegister src, ValueKind kind) [inline]
Definition at line 142 of file parallel-move.h.
                                                                              {
    DCHECK_NE(dst, src);
    DCHECK_EQ(dst.reg_class(), src.reg_class());
    DCHECK_EQ(reg_class_for(kind), src.reg_class());
    if (src.is_gp_pair()) {
      DCHECK_EQ(kI64, kind);
      if (dst.low() != src.low()) MoveRegister(dst.low(), src.low(), kI32);
      if (dst.high() != src.high()) MoveRegister(dst.high(), src.high(), kI32);
      return;
    }
    if (src.is_fp_pair()) {
      DCHECK_EQ(kS128, kind);
      if (dst.low() != src.low()) {
        MoveRegister(dst.low(), src.low(), kF64);
        MoveRegister(dst.high(), src.high(), kF64);
      }
      return;
    }
    if (move_dst_regs_.has(dst)) {
      DCHECK_EQ(register_move(dst)->src, src);
      // Check for compatible value kinds.
      // - references can occur with mixed kRef / kRefNull kinds.
      // - FP registers can only occur with f32 / f64 / s128 kinds (mixed kinds
      // only if they hold the initial zero value).
      // - others must match exactly.
      DCHECK_EQ(is_object_reference(register_move(dst)->kind),
                is_object_reference(kind));
      DCHECK_EQ(dst.is_fp(), register_move(dst)->kind == kF32 ||
                                 register_move(dst)->kind == kF64 ||
                                 register_move(dst)->kind == kS128);
      if (!is_object_reference(kind) && !dst.is_fp()) {
        DCHECK_EQ(register_move(dst)->kind, kind);
      }
      // Potentially upgrade an existing `kF32` move to a `kF64` move.
      if (kind == kF64) register_move(dst)->kind = kF64;
      return;
    }
    move_dst_regs_.set(dst);
    ++*src_reg_use_count(src);
    *register_move(dst) = {src, kind};
  }
References DCHECK_EQ, DCHECK_NE, v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_fp(), v8::internal::wasm::LiftoffRegister::is_fp_pair(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), v8::internal::wasm::is_object_reference(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::ParallelMove::RegisterMove::kind, v8::internal::kS128, v8::internal::wasm::LiftoffRegister::low(), move_dst_regs_, v8::internal::wasm::LiftoffRegister::reg_class(), v8::internal::wasm::reg_class_for(), register_move(), v8::internal::wasm::LiftoffRegList::set(), and src_reg_use_count().
Referenced by LoadI64HalfIntoRegister(), LoadIntoRegister(), v8::internal::wasm::LiftoffAssembler::Move(), and v8::internal::wasm::LiftoffAssembler::ParallelRegisterMove().
operator=()
ParallelMove& v8::internal::wasm::ParallelMove::operator= (const ParallelMove &) [delete]
register_load()
RegisterLoad* v8::internal::wasm::ParallelMove::register_load (LiftoffRegister reg) [inline], [private]
Definition at line 258 of file parallel-move.h.
                                                   {
    return reinterpret_cast<RegisterLoad*>(register_loads_) +
           reg.liftoff_code();
  }
References v8::internal::wasm::LiftoffRegister::liftoff_code(), and register_loads_.
Referenced by ExecuteLoads(), LoadConstant(), LoadI64HalfStackSlot(), LoadStackSlot(), and TransferToStack().
register_move()
RegisterMove* v8::internal::wasm::ParallelMove::register_move (LiftoffRegister reg) [inline], [private]
Definition at line 254 of file parallel-move.h.
                                                   {
    return reinterpret_cast<RegisterMove*>(register_moves_) +
           reg.liftoff_code();
  }
References v8::internal::wasm::LiftoffRegister::liftoff_code(), and register_moves_.
Referenced by ClearExecutedMove(), ExecuteMove(), ExecuteMoves(), and MoveRegister().
src_reg_use_count()
int* v8::internal::wasm::ParallelMove::src_reg_use_count (LiftoffRegister reg) [inline], [private]
Definition at line 262 of file parallel-move.h.
                                              {
    return src_reg_use_count_ + reg.liftoff_code();
  }
References v8::internal::wasm::LiftoffRegister::liftoff_code(), and src_reg_use_count_.
Referenced by ClearExecutedMove(), ExecuteMove(), ExecuteMoves(), and MoveRegister().
Transfer()
void v8::internal::wasm::ParallelMove::Transfer (const VarState & dst, const VarState & src) [inline]
Definition at line 89 of file parallel-move.h.
                                                                    {
    DCHECK(CompatibleStackSlotTypes(dst.kind(), src.kind()));
    if (dst.is_stack()) {
      if (V8_UNLIKELY(!(src.is_stack() && src.offset() == dst.offset()))) {
        TransferToStack(dst.offset(), src);
      }
    } else if (dst.is_reg()) {
      LoadIntoRegister(dst.reg(), src);
    } else {
      DCHECK(dst.is_const());
      DCHECK_EQ(dst.i32_const(), src.i32_const());
    }
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::is_stack(), v8::internal::wasm::LiftoffVarState::kind(), LoadIntoRegister(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), TransferToStack(), and V8_UNLIKELY.
Referenced by v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), and v8::internal::wasm::LiftoffAssembler::MergeStackWith().
TransferToStack()
void v8::internal::wasm::ParallelMove::TransferToStack (int dst_offset, const VarState & src)
Definition at line 11 of file parallel-move.cc.
                                                                      {
  switch (src.loc()) {
    case VarState::kStack:
      // Same offsets can happen even if we move values down in the value stack,
      // because of alignment.
      if (src.offset() == dst_offset) return;
#if DEBUG
      // Check that the stack value at `dst_offset` is not used in a pending
      // register load.
      for (LiftoffRegister reg : load_dst_regs_) {
        DCHECK(!reg.is_pair());
        RegisterLoad* load = register_load(reg);
        if (load->load_kind == RegisterLoad::kStack ||
            load->load_kind == RegisterLoad::kLowHalfStack) {
          // We overwrite the lower half of the stack value for sure.
          DCHECK_NE(load->value, dst_offset);
        } else if (load->load_kind == RegisterLoad::kHighHalfStack &&
                   value_kind_size(src.kind()) > kInt32Size) {
          // We overwrite the full stack slot, but we still need the higher half
          // later.
          DCHECK_NE(load->value, dst_offset);
        }
      }
#endif
      asm_->MoveStackValue(dst_offset, src.offset(), src.kind());
      break;
    case VarState::kRegister:
      asm_->Spill(dst_offset, src.reg(), src.kind());
      break;
    case VarState::kIntConst:
      asm_->Spill(dst_offset, src.constant());
      break;
  }
}
References asm_, v8::internal::wasm::LiftoffVarState::constant(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::wasm::ParallelMove::RegisterLoad::kHighHalfStack, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::kInt32Size, v8::internal::wasm::LiftoffVarState::kIntConst, v8::internal::wasm::ParallelMove::RegisterLoad::kLowHalfStack, v8::internal::wasm::LiftoffVarState::kRegister, v8::internal::wasm::LiftoffVarState::kStack, v8::internal::wasm::ParallelMove::RegisterLoad::kStack, load_dst_regs_, v8::internal::wasm::ParallelMove::RegisterLoad::load_kind, v8::internal::wasm::LiftoffVarState::loc(), v8::internal::wasm::LiftoffAssembler::MoveStackValue(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), register_load(), v8::internal::wasm::LiftoffAssembler::Spill(), v8::internal::wasm::ParallelMove::RegisterLoad::value, and v8::internal::wasm::value_kind_size().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), and Transfer().
Member Data Documentation
asm_
LiftoffAssembler* const v8::internal::wasm::ParallelMove::asm_ [private]
Definition at line 249 of file parallel-move.h.
Referenced by ExecuteLoads(), ExecuteMove(), ExecuteMoves(), and TransferToStack().
last_spill_offset_
int v8::internal::wasm::ParallelMove::last_spill_offset_ [private]
Definition at line 252 of file parallel-move.h.
Referenced by ExecuteMoves(), and LoadStackSlot().
load_dst_regs_
LiftoffRegList v8::internal::wasm::ParallelMove::load_dst_regs_ [private]
Definition at line 248 of file parallel-move.h.
Referenced by Execute(), ExecuteLoads(), LoadConstant(), LoadI64HalfStackSlot(), LoadStackSlot(), and TransferToStack().
move_dst_regs_
LiftoffRegList v8::internal::wasm::ParallelMove::move_dst_regs_ [private]
Definition at line 247 of file parallel-move.h.
Referenced by ClearExecutedMove(), Execute(), ExecuteMoves(), and MoveRegister().
register_loads_
char v8::internal::wasm::ParallelMove::register_loads_[kAfterMaxLiftoffRegCode *sizeof(RegisterLoad)] [private]
Definition at line 244 of file parallel-move.h.
Referenced by register_load().
register_moves_
char v8::internal::wasm::ParallelMove::register_moves_[kAfterMaxLiftoffRegCode *sizeof(RegisterMove)] [private]
Definition at line 242 of file parallel-move.h.
Referenced by register_move().
src_reg_use_count_
int v8::internal::wasm::ParallelMove::src_reg_use_count_[kAfterMaxLiftoffRegCode] = {0} [private]
Definition at line 246 of file parallel-move.h.
Referenced by src_reg_use_count().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/baseline/parallel-move.h
/mnt/V8SourceCode/src/wasm/baseline/parallel-move-inl.h
/mnt/V8SourceCode/src/wasm/baseline/parallel-move.cc