v8::internal::UnalignedSlot< T >::Reference Class Reference
#include <slots.h>
Public Member Functions
Reference (Address address)
Reference (const Reference &) V8_NOEXCEPT=default
Reference & operator= (const Reference &other) V8_NOEXCEPT
Reference & operator= (T value)
operator T () const
void swap (Reference &other)
bool operator< (const Reference &other) const
bool operator== (const Reference &other) const
Private Member Functions
T value () const
Private Attributes
Address address_
Detailed Description
template<typename T>
class v8::internal::UnalignedSlot< T >::Reference
Definition at line 233 of file slots.h.
Constructor & Destructor Documentation
Reference() [1/2]
template<typename T >
v8::internal::UnalignedSlot< T >::Reference::Reference (Address address) [inline], [explicit]
Definition at line 235 of file slots.h.
: address_(address) {}
Reference() [2/2]
template<typename T >
v8::internal::UnalignedSlot< T >::Reference::Reference (const Reference &) [default]
Member Function Documentation
operator T()
template<typename T >
v8::internal::UnalignedSlot< T >::Reference::operator T () const [inline]
Definition at line 249 of file slots.h.
{ return value(); }
References v8::internal::value.
operator<()
template<typename T >
bool v8::internal::UnalignedSlot< T >::Reference::operator< (const Reference & other) const [inline]
Definition at line 257 of file slots.h.
                                                 {
      return value() < other.value();
    }
References v8::internal::value, and v8::internal::UnalignedSlot< T >::Reference::value().
operator=() [1/2]
template<typename T >
Reference& v8::internal::UnalignedSlot< T >::Reference::operator= (const Reference & other) [inline]
Definition at line 238 of file slots.h.
                                                             {
      base::WriteUnalignedValue<T>(address_, other.value());
      return *this;
    }
operator=() [2/2]
template<typename T >
Reference& v8::internal::UnalignedSlot< T >::Reference::operator= (T value) [inline]
Definition at line 242 of file slots.h.
                                  {
      base::WriteUnalignedValue<T>(address_, value);
      return *this;
    }
References v8::internal::value.
operator==()
template<typename T >
bool v8::internal::UnalignedSlot< T >::Reference::operator== (const Reference & other) const [inline]
Definition at line 261 of file slots.h.
                                                  {
      return value() == other.value();
    }
References v8::internal::value, and v8::internal::UnalignedSlot< T >::Reference::value().
swap()
template<typename T >
void v8::internal::UnalignedSlot< T >::Reference::swap (Reference & other) [inline]
Definition at line 251 of file slots.h.
                                {
      T tmp = value();
      base::WriteUnalignedValue<T>(address_, other.value());
      base::WriteUnalignedValue<T>(other.address_, tmp);
    }
References v8::internal::UnalignedSlot< T >::Reference::address_, v8::internal::value, and v8::internal::UnalignedSlot< T >::Reference::value().
value()
template<typename T >
T v8::internal::UnalignedSlot< T >::Reference::value () const [inline], [private]
Definition at line 266 of file slots.h.
{ return base::ReadUnalignedValue<T>(address_); }
Referenced by v8::internal::UnalignedSlot< T >::Reference::operator<(), v8::internal::UnalignedSlot< T >::Reference::operator==(), and v8::internal::UnalignedSlot< T >::Reference::swap().
Member Data Documentation
address_
template<typename T >
Address v8::internal::UnalignedSlot< T >::Reference::address_ [private]
Definition at line 268 of file slots.h.
Referenced by v8::internal::UnalignedSlot< T >::Reference::swap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/slots.h