v8::internal::Float32 Class Reference
#include <boxed-float.h>
Public Member Functions
Float32 ()=default
Float32 (float value)
uint32_t get_bits () const
float get_scalar () const
bool is_nan () const
bool is_quiet_nan () const
V8_WARN_UNUSED_RESULT Float32 to_quiet_nan () const
uint32_t * get_bits_address ()
Static Public Member Functions
static constexpr Float32 FromBits (uint32_t bits)
Private Member Functions
constexpr Float32 (uint32_t bit_pattern)
uint32_t exponent () const
uint32_t mantissa () const
Private Attributes
uint32_t bit_pattern_ = 0
Detailed Description
Definition at line 22 of file boxed-float.h.
Constructor & Destructor Documentation
Float32() [1/3]
v8::internal::Float32::Float32 () [default]
Referenced by FromBits().
Float32() [2/3]
v8::internal::Float32::Float32 (float value) [inline], [explicit]
Definition at line 28 of file boxed-float.h.
      : bit_pattern_(base::bit_cast<uint32_t>(value)) {
    // Check that the provided value is not a NaN, because the bit pattern of a
    // NaN may be changed by a base::bit_cast, e.g. for signalling NaNs on
    // ia32.
    DCHECK(!std::isnan(value));
  }
References v8::internal::DCHECK(), and v8::internal::value.
Float32() [3/3]
constexpr v8::internal::Float32::Float32 (uint32_t bit_pattern) [inline], [explicit], [constexpr], [private]
Definition at line 64 of file boxed-float.h.
      : bit_pattern_(bit_pattern) {}
Member Function Documentation
exponent()
uint32_t v8::internal::Float32::exponent () const [inline], [private]
Definition at line 67 of file boxed-float.h.
{ return (bit_pattern_ >> 23) & 0xff; }
References bit_pattern_.
Referenced by is_nan().
FromBits()
static constexpr Float32 v8::internal::Float32::FromBits (uint32_t bits) [inline], [static], [constexpr]
Definition at line 61 of file boxed-float.h.
{ return Float32(bits); }
References Float32().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_shuffle(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float32Constant(), v8::internal::TranslatedState::GetFloatSlot(), v8::internal::compiler::Constant::ToFloat32Safe(), and v8::internal::wasm::WasmInterpreterRuntime::UnpackException().
get_bits()
uint32_t v8::internal::Float32::get_bits () const [inline]
Definition at line 36 of file boxed-float.h.
{ return bit_pattern_; }
References bit_pattern_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::DeoptimizationLiteral::operator==().
get_bits_address()
uint32_t* v8::internal::Float32::get_bits_address () [inline]
Definition at line 59 of file boxed-float.h.
{ return &bit_pattern_; }
References bit_pattern_.
get_scalar()
float v8::internal::Float32::get_scalar () const [inline]
Definition at line 38 of file boxed-float.h.
{ return base::bit_cast<float>(bit_pattern_); }
References bit_pattern_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), v8::internal::TranslatedValue::GetValue(), is_nan(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::ConstantOp::PrintOptions(), and v8::internal::wasm::WasmInterpreterRuntime::UnpackException().
is_nan()
bool v8::internal::Float32::is_nan () const [inline]
Definition at line 40 of file boxed-float.h.
                      {
    // Even though {get_scalar()} might set the quiet NaN bit, it's ok here,
    // because this does not change the is_nan property.
    bool nan = std::isnan(get_scalar());
    DCHECK_EQ(nan, exponent() == 0xff && mantissa() != 0);
    return nan;
  }
References DCHECK_EQ, exponent(), get_scalar(), and mantissa().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), is_quiet_nan(), and to_quiet_nan().
is_quiet_nan()
bool v8::internal::Float32::is_quiet_nan () const [inline]
Definition at line 48 of file boxed-float.h.
{ return is_nan() && (bit_pattern_ & (1 << 22)); }
References bit_pattern_, and is_nan().
mantissa()
uint32_t v8::internal::Float32::mantissa () const [inline], [private]
Definition at line 68 of file boxed-float.h.
{ return bit_pattern_ & ((1 << 23) - 1); }
References bit_pattern_.
Referenced by is_nan().
to_quiet_nan()
V8_WARN_UNUSED_RESULT Float32 v8::internal::Float32::to_quiet_nan () const [inline]
Definition at line 50 of file boxed-float.h.
                                                     {
    DCHECK(is_nan());
    Float32 quiet_nan{bit_pattern_ | (1 << 22)};
    DCHECK(quiet_nan.is_quiet_nan());
    return quiet_nan;
  }
References bit_pattern_, v8::internal::DCHECK(), and is_nan().
Member Data Documentation
bit_pattern_
uint32_t v8::internal::Float32::bit_pattern_ = 0 [private]
Definition at line 70 of file boxed-float.h.
Referenced by exponent(), get_bits(), get_bits_address(), get_scalar(), is_quiet_nan(), mantissa(), and to_quiet_nan().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/boxed-float.h