v8::internal::AstTraversalVisitor< Subclass > Class Template Reference
#include <ast-traversal-visitor.h>
Public Member Functions
AstTraversalVisitor (Isolate *isolate, AstNode *root=nullptr)
AstTraversalVisitor (uintptr_t stack_limit, AstNode *root=nullptr)
AstTraversalVisitor (const AstTraversalVisitor &)=delete
AstTraversalVisitor & operator= (const AstTraversalVisitor &)=delete
void Run ()
bool VisitNode (AstNode *node)
bool VisitExpression (Expression *node)
void VisitDeclarations (Declaration::List *declarations)
void VisitStatements (const ZonePtrList< Statement > *statements)
Protected Member Functions
int depth () const
Private Member Functions
DEFINE_AST_VISITOR_SUBCLASS_MEMBERS ()
Private Attributes
AstNode * root_
int depth_
Detailed Description
template<class Subclass>
class v8::internal::AstTraversalVisitor< Subclass >
Definition at line 30 of file ast-traversal-visitor.h.
Constructor & Destructor Documentation
AstTraversalVisitor() [1/3]
template<class Subclass >
v8::internal::AstTraversalVisitor< Subclass >::AstTraversalVisitor (Isolate * isolate, AstNode * root = nullptr) [explicit]
Definition at line 93 of file ast-traversal-visitor.h.
    : root_(root), depth_(0) {
  InitializeAstVisitor(isolate);
}
AstTraversalVisitor() [2/3]
template<class Subclass >
v8::internal::AstTraversalVisitor< Subclass >::AstTraversalVisitor (uintptr_t stack_limit, AstNode * root = nullptr) [explicit]
Definition at line 100 of file ast-traversal-visitor.h.
    : root_(root), depth_(0) {
  InitializeAstVisitor(stack_limit);
}
AstTraversalVisitor() [3/3]
template<class Subclass >
v8::internal::AstTraversalVisitor< Subclass >::AstTraversalVisitor (const AstTraversalVisitor< Subclass > &) [delete]
Member Function Documentation
DEFINE_AST_VISITOR_SUBCLASS_MEMBERS()
template<class Subclass >
v8::internal::AstTraversalVisitor< Subclass >::DEFINE_AST_VISITOR_SUBCLASS_MEMBERS () [private]
depth()
template<class Subclass >
int v8::internal::AstTraversalVisitor< Subclass >::depth () const [inline], [protected]
Definition at line 55 of file ast-traversal-visitor.h.
{ return depth_; }
References v8::internal::AstTraversalVisitor< Subclass >::depth_.
operator=()
template<class Subclass >
AstTraversalVisitor& v8::internal::AstTraversalVisitor< Subclass >::operator= (const AstTraversalVisitor< Subclass > &) [delete]
Run()
template<class Subclass >
void v8::internal::AstTraversalVisitor< Subclass >::Run () [inline]
Definition at line 37 of file ast-traversal-visitor.h.
             {
    DCHECK_NOT_NULL(root_);
    Visit(root_);
  }
References DCHECK_NOT_NULL, v8::internal::AstTraversalVisitor< Subclass >::root_, and v8::internal::AstVisitor< Subclass >::Visit().
Referenced by v8::internal::anonymous_namespace{parser.cc}::MaybeProcessSourceRanges(), and v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::Run().
VisitDeclarations()
template<class Subclass >
void v8::internal::AstTraversalVisitor< Subclass >::VisitDeclarations (Declaration::List * declarations)
Definition at line 107 of file ast-traversal-visitor.h.
                            {
  for (Declaration* decl : *decls) {
    RECURSE(Visit(decl));
  }
}
References RECURSE.
VisitExpression()
template<class Subclass >
bool v8::internal::AstTraversalVisitor< Subclass >::VisitExpression (Expression * node) [inline]
Definition at line 43 of file ast-traversal-visitor.h.
{ return true; }
VisitNode()
template<class Subclass >
bool v8::internal::AstTraversalVisitor< Subclass >::VisitNode (AstNode * node) [inline]
Definition at line 42 of file ast-traversal-visitor.h.
{ return true; }
VisitStatements()
template<class Subclass >
void v8::internal::AstTraversalVisitor< Subclass >::VisitStatements (const ZonePtrList< Statement > * statements)
Definition at line 115 of file ast-traversal-visitor.h.
                                         {
  for (int i = 0; i < stmts->length(); ++i) {
    Statement* stmt = stmts->at(i);
    RECURSE(Visit(stmt));
  }
}
References v8::internal::ZoneList< T >::at(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ZoneList< T >::length(), and RECURSE.
Member Data Documentation
depth_
template<class Subclass >
int v8::internal::AstTraversalVisitor< Subclass >::depth_ [private]
Definition at line 61 of file ast-traversal-visitor.h.
Referenced by v8::internal::AstTraversalVisitor< Subclass >::depth().
root_
template<class Subclass >
AstNode* v8::internal::AstTraversalVisitor< Subclass >::root_ [private]
Definition at line 60 of file ast-traversal-visitor.h.
Referenced by v8::internal::AstTraversalVisitor< Subclass >::Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-traversal-visitor.h