v8_inspector::V8SerializationDuplicateTracker Class Reference
#include <v8-serialization-duplicate-tracker.h>
Public Member Functions
std::unique_ptr< protocol::DictionaryValue > LinkExistingOrCreate (v8::Local< v8::Value > v8Value, bool *isKnown)
V8SerializationDuplicateTracker (v8::Local< v8::Context > context)
Private Member Functions
protocol::DictionaryValue * FindKnownSerializedValue (v8::Local< v8::Value > v8Value)
void SetKnownSerializedValue (v8::Local< v8::Value > v8Value, protocol::DictionaryValue *serializedValue)
Private Attributes
v8::Local< v8::Context > m_context
int m_counter
v8::Local< v8::Map > m_v8ObjectToSerializedDictionary
Detailed Description
Definition at line 15 of file v8-serialization-duplicate-tracker.h.
Constructor & Destructor Documentation
V8SerializationDuplicateTracker()
v8_inspector::V8SerializationDuplicateTracker::V8SerializationDuplicateTracker (v8::Local< v8::Context > context) [explicit]
Definition at line 72 of file v8-serialization-duplicate-tracker.cc.
    : m_context(context),
      m_counter(1),
      m_v8ObjectToSerializedDictionary(
          v8::Map::New(v8::Isolate::GetCurrent())) {}
Member Function Documentation
FindKnownSerializedValue()
protocol::DictionaryValue * v8_inspector::V8SerializationDuplicateTracker::FindKnownSerializedValue (v8::Local< v8::Value > v8Value) [private]
Definition at line 59 of file v8-serialization-duplicate-tracker.cc.
                              {
  v8::Local<v8::Value> knownValue;
  if (!m_v8ObjectToSerializedDictionary->Get(m_context, v8Value)
           .ToLocal(&knownValue) ||
      knownValue->IsUndefined()) {
    return nullptr;
  }
  return static_cast<protocol::DictionaryValue*>(
      knownValue.As<v8::External>()->Value());
}
References v8::Local< T >::As(), v8::Map::Get(), v8::Value::IsUndefined(), m_context, m_v8ObjectToSerializedDictionary, and v8::MaybeLocal< T >::ToLocal().
Referenced by LinkExistingOrCreate().
LinkExistingOrCreate()
std::unique_ptr< protocol::DictionaryValue > v8_inspector::V8SerializationDuplicateTracker::LinkExistingOrCreate (v8::Local< v8::Value > v8Value, bool * isKnown)
Definition at line 14 of file v8-serialization-duplicate-tracker.cc.
                                             {
  std::unique_ptr<protocol::DictionaryValue> result =
      protocol::DictionaryValue::create();
  protocol::DictionaryValue* maybeKnownSerializedValue =
      FindKnownSerializedValue(v8Value);
  if (maybeKnownSerializedValue == nullptr) {
    *isKnown = false;
    // Keep reference to the serialized value, so that
    // `weakLocalObjectReference` can be set later.
    SetKnownSerializedValue(v8Value, result.get());
  } else {
    *isKnown = true;
    String16 type;
    maybeKnownSerializedValue->getString("type", &type);
    result->setString("type", type);
    int weakLocalObjectReference;
    // If `maybeKnownSerializedValue` has no `weakLocalObjectReference` yet,
    // it's need to be set.
    if (!maybeKnownSerializedValue->getInteger("weakLocalObjectReference",
                                               &weakLocalObjectReference)) {
      weakLocalObjectReference = m_counter++;
      maybeKnownSerializedValue->setInteger("weakLocalObjectReference",
                                            weakLocalObjectReference);
    }
    result->setInteger("weakLocalObjectReference", weakLocalObjectReference);
  }
  return result;
}
References FindKnownSerializedValue(), m_counter, v8::base::internal::result, SetKnownSerializedValue(), and v8::internal::tracing::type.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildDeepSerializedValue(), and v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue().
SetKnownSerializedValue()
void v8_inspector::V8SerializationDuplicateTracker::SetKnownSerializedValue (v8::Local< v8::Value > v8Value, protocol::DictionaryValue * serializedValue) [private]
Definition at line 49 of file v8-serialization-duplicate-tracker.cc.
                                                                        {
  m_v8ObjectToSerializedDictionary =
      m_v8ObjectToSerializedDictionary
          ->Set(m_context, v8Value,
                v8::External::New(v8::Isolate::GetCurrent(), serializedValue))
          .ToLocalChecked();
}
References v8::Isolate::GetCurrent(), m_context, m_v8ObjectToSerializedDictionary, v8::External::New(), and v8::Map::Set().
Referenced by LinkExistingOrCreate().
Member Data Documentation
m_context
v8::Local<v8::Context> v8_inspector::V8SerializationDuplicateTracker::m_context [private]
Definition at line 27 of file v8-serialization-duplicate-tracker.h.
Referenced by FindKnownSerializedValue(), and SetKnownSerializedValue().
m_counter
int v8_inspector::V8SerializationDuplicateTracker::m_counter [private]
Definition at line 28 of file v8-serialization-duplicate-tracker.h.
Referenced by LinkExistingOrCreate().
m_v8ObjectToSerializedDictionary
v8::Local<v8::Map> v8_inspector::V8SerializationDuplicateTracker::m_v8ObjectToSerializedDictionary [private]
Definition at line 30 of file v8-serialization-duplicate-tracker.h.
Referenced by FindKnownSerializedValue(), and SetKnownSerializedValue().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-serialization-duplicate-tracker.h
/mnt/V8SourceCode/src/inspector/v8-serialization-duplicate-tracker.cc