v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor Class Reference
Static Public Member Functions
static Handle< Object > GetAtomicInternalImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, SeqCstAccessTag tag)
static void SetAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag)
static Handle< Object > SwapAtomicInternalImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag)
static Tagged< Object > CompareAndSwapAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)
Additional Inherited Members
Detailed Description
Definition at line 3061 of file elements.cc.
Member Function Documentation
CompareAndSwapAtomicInternalImpl()
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor::CompareAndSwapAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 3087 of file elements.cc.
                                                                          {
    return Cast<BackingStore>(backing_store)
        ->compare_and_swap(entry.as_int(), expected, value, tag);
  }
References v8::internal::InternalIndex::as_int(), and v8::internal::value.
GetAtomicInternalImpl()
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor::GetAtomicInternalImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, SeqCstAccessTag tag) [inline], [static]
Definition at line 3066 of file elements.cc.
                                                {
    return handle(Cast<BackingStore>(backing_store)->get(entry.as_int(), tag),
                  isolate);
  }
References v8::internal::InternalIndex::as_int(), and v8::internal::handle().
SetAtomicInternalImpl()
static void v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor::SetAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 3073 of file elements.cc.
                                                         {
    Cast<BackingStore>(backing_store)->set(entry.as_int(), value, tag);
  }
References v8::internal::InternalIndex::as_int(), and v8::internal::value.
SwapAtomicInternalImpl()
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor::SwapAtomicInternalImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 3079 of file elements.cc.
                                                                      {
    return handle(
        Cast<BackingStore>(backing_store)->swap(entry.as_int(), value, tag),
        isolate);
  }
References v8::internal::InternalIndex::as_int(), v8::internal::handle(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc