v8::internal::torque::Item Class Reference
#include <earley-parser.h>
Public Member Functions
Item (const Rule *rule, size_t mark, size_t start, size_t pos)
bool IsComplete () const
Symbol * NextSymbol () const
Item Advance (size_t new_pos, const Item *child=nullptr) const
std::vector< const Item * > Children () const
std::string SplitByChildren (const LexerResult &tokens) const
void CheckAmbiguity (const Item &other, const LexerResult &tokens) const
MatchedInput GetMatchedInput (const LexerResult &tokens) const
bool operator== (const Item &other) const
const Rule * rule () const
Symbol * left () const
const std::vector< Symbol * > & right () const
size_t pos () const
size_t start () const
Private Attributes
const Rule * rule_
size_t mark_
size_t start_
size_t pos_
const Item * prev_ = nullptr
const Item * child_ = nullptr
Friends
size_t hash_value (const Item &i)
Detailed Description
Definition at line 279 of file earley-parser.h.
Constructor & Destructor Documentation
Item()
v8::internal::torque::Item::Item (const Rule * rule, size_t mark, size_t start, size_t pos) [inline]
Definition at line 281 of file earley-parser.h.
      : rule_(rule), mark_(mark), start_(start), pos_(pos) {
    DCHECK_LE(mark_, right().size());
  }
References DCHECK_LE, mark_, right(), and size().
Member Function Documentation
Advance()
Item v8::internal::torque::Item::Advance (size_t new_pos, const Item * child = nullptr) const [inline]
Definition at line 305 of file earley-parser.h.
                                                                  {
    if (child) {
      DCHECK(child->IsComplete());
      DCHECK_EQ(pos(), child->start());
      DCHECK_EQ(new_pos, child->pos());
      DCHECK_EQ(NextSymbol(), child->left());
    }
    Item result(rule_, mark_ + 1, start_, new_pos);
    result.prev_ = this;
    result.child_ = child;
    return result;
  }
References v8::internal::DCHECK(), DCHECK_EQ, mark_, NextSymbol(), pos(), v8::base::internal::result, rule_, and start_.
Referenced by v8::internal::torque::RunEarleyAlgorithm().
CheckAmbiguity()
void v8::internal::torque::Item::CheckAmbiguity (const Item & other, const LexerResult & tokens) const
Definition at line 98 of file earley-parser.cc.
                                                                            {
  DCHECK(*this == other);
  if (child_ != other.child_) {
    std::stringstream s;
    s << "Ambiguous grammer rules for \""
      << child_->GetMatchedInput(tokens).ToString() << "\":\n "
      << child_->SplitByChildren(tokens) << "\nvs\n "
      << other.child_->SplitByChildren(tokens);
    ReportError(s.str());
  }
  if (prev_ != other.prev_) {
    std::stringstream s;
    s << "Ambiguous grammer rules for \"" << GetMatchedInput(tokens).ToString()
      << "\":\n " << SplitByChildren(tokens) << " ...\nvs\n "
      << other.SplitByChildren(tokens) << " ...";
    ReportError(s.str());
  }
}
References child_, v8::internal::DCHECK(), GetMatchedInput(), prev_, v8::internal::torque::ReportError(), SplitByChildren(), and v8::internal::torque::MatchedInput::ToString().
Referenced by v8::internal::torque::RunEarleyAlgorithm().
Children()
std::vector< const Item * > v8::internal::torque::Item::Children () const
Definition at line 71 of file earley-parser.cc.
                                            {
  std::vector<const Item*> children;
  for (const Item* current = this; current->prev_; current = current->prev_) {
    children.push_back(current->child_);
  }
  // The above loop collects the child nodes in reversed order.
  std::reverse(children.begin(), children.end());
  DCHECK_EQ(children.size(), right().size());
  return children;
}
References DCHECK_EQ, prev_, right(), and size().
Referenced by v8::internal::torque::Rule::RunAction(), and SplitByChildren().
GetMatchedInput()
MatchedInput v8::internal::torque::Item::GetMatchedInput (const LexerResult & tokens) const [inline]
Definition at line 325 of file earley-parser.h.
                                                                {
    const MatchedInput& start = tokens.token_contents[start_];
    const MatchedInput& end = start_ == pos_ ? tokens.token_contents[start_]
                                             : tokens.token_contents[pos_ - 1];
    CHECK_EQ(start.pos.source, end.pos.source);
    SourcePosition combined{start.pos.source, start.pos.start, end.pos.end};
    return {start.begin, end.end, combined};
  }
References CHECK_EQ, v8::internal::compiler::end(), pos_, start(), start_, and v8::internal::torque::LexerResult::token_contents.
Referenced by CheckAmbiguity(), and v8::internal::torque::Rule::RunAction().
IsComplete()
bool v8::internal::torque::Item::IsComplete () const [inline]
Definition at line 288 of file earley-parser.h.
                          {
    DCHECK_LE(mark_, right().size());
    return mark_ == right().size();
  }
References DCHECK_LE, mark_, right(), and size().
Referenced by NextSymbol(), v8::internal::torque::Symbol::RunAction(), and v8::internal::torque::RunEarleyAlgorithm().
left()
Symbol* v8::internal::torque::Item::left () const [inline]
Definition at line 347 of file earley-parser.h.
{ return rule_->left(); }
References v8::internal::torque::Rule::left(), and rule_.
Referenced by v8::internal::torque::Symbol::RunAction(), and v8::internal::torque::RunEarleyAlgorithm().
NextSymbol()
Symbol* v8::internal::torque::Item::NextSymbol () const [inline]
Definition at line 295 of file earley-parser.h.
                             {
    DCHECK(!IsComplete());
    DCHECK_LT(mark_, right().size());
    return right()[mark_];
  }
References v8::internal::DCHECK(), DCHECK_LT, IsComplete(), mark_, right(), and size().
Referenced by Advance(), and v8::internal::torque::RunEarleyAlgorithm().
operator==()
bool v8::internal::torque::Item::operator== (const Item & other) const [inline]
Definition at line 337 of file earley-parser.h.
                                           {
    return rule_ == other.rule_ && mark_ == other.mark_ &&
           start_ == other.start_ && pos_ == other.pos_;
  }
References mark_, pos_, rule_, and start_.
pos()
size_t v8::internal::torque::Item::pos () const [inline]
Definition at line 349 of file earley-parser.h.
{ return pos_; }
References pos_.
Referenced by Advance(), and v8::internal::torque::RunEarleyAlgorithm().
right()
const std::vector<Symbol*>& v8::internal::torque::Item::right () const [inline]
Definition at line 348 of file earley-parser.h.
{ return rule_->right(); }
References v8::internal::torque::Rule::right(), and rule_.
Referenced by Children(), IsComplete(), Item(), NextSymbol(), and SplitByChildren().
rule()
const Rule* v8::internal::torque::Item::rule () const [inline]
Definition at line 346 of file earley-parser.h.
{ return rule_; }
References rule_.
Referenced by v8::internal::torque::Symbol::RunAction().
SplitByChildren()
std::string v8::internal::torque::Item::SplitByChildren (const LexerResult & tokens) const
Definition at line 82 of file earley-parser.cc.
                                                               {
  if (right().size() == 1) {
    if (const Item* child = Children()[0])
      return child->SplitByChildren(tokens);
  }
  std::stringstream s;
  bool first = true;
  for (const Item* item : Children()) {
    if (!item) continue;
    if (!first) s << " ";
    s << item->GetMatchedInput(tokens).ToString();
    first = false;
  }
  return s.str();
}
References Children(), right(), and size().
Referenced by CheckAmbiguity().
start()
size_t v8::internal::torque::Item::start () const [inline]
Definition at line 350 of file earley-parser.h.
{ return start_; }
References start_.
Referenced by GetMatchedInput(), and v8::internal::torque::RunEarleyAlgorithm().
Friends And Related Function Documentation
hash_value
size_t hash_value (const Item & i) [friend]
Definition at line 342 of file earley-parser.h.
                                          {
    return base::hash_combine(i.rule_, i.mark_, i.start_, i.pos_);
  }
Member Data Documentation
child_
const Item* v8::internal::torque::Item::child_ = nullptr [private]
Definition at line 359 of file earley-parser.h.
Referenced by CheckAmbiguity().
mark_
size_t v8::internal::torque::Item::mark_ [private]
Definition at line 354 of file earley-parser.h.
Referenced by Advance(), IsComplete(), Item(), NextSymbol(), and operator==().
pos_
size_t v8::internal::torque::Item::pos_ [private]
Definition at line 356 of file earley-parser.h.
Referenced by GetMatchedInput(), operator==(), and pos().
prev_
const Item* v8::internal::torque::Item::prev_ = nullptr [private]
Definition at line 358 of file earley-parser.h.
Referenced by CheckAmbiguity(), and Children().
rule_
const Rule* v8::internal::torque::Item::rule_ [private]
Definition at line 353 of file earley-parser.h.
Referenced by Advance(), left(), operator==(), right(), and rule().
start_
size_t v8::internal::torque::Item::start_ [private]
Definition at line 355 of file earley-parser.h.
Referenced by Advance(), GetMatchedInput(), operator==(), and start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/earley-parser.h
/mnt/V8SourceCode/src/torque/earley-parser.cc