v8::internal::PlatformEmbeddedFileWriterBase Class Reference
#include <platform-embedded-file-writer-base.h>
Public Member Functions
virtual ~PlatformEmbeddedFileWriterBase ()=default
void SetFile (FILE *fp)
FILE * fp () const
virtual void SectionText ()=0
virtual void SectionRoData ()=0
virtual void AlignToCodeAlignment ()=0
virtual void AlignToPageSizeIfNeeded ()
virtual void AlignToDataAlignment ()=0
virtual void DeclareUint32 (const char *name, uint32_t value)=0
virtual void DeclareSymbolGlobal (const char *name)=0
virtual void DeclareLabel (const char *name)=0
virtual void DeclareLabelProlog (const char *name)
virtual void DeclareLabelEpilogue ()
virtual void SourceInfo (int fileid, const char *filename, int line)=0
virtual void DeclareFunctionBegin (const char *name, uint32_t size)=0
virtual void DeclareFunctionEnd (const char *name)=0
virtual int HexLiteral (uint64_t value)
virtual void Comment (const char *string)=0
virtual void Newline ()
virtual void FilePrologue ()=0
virtual void DeclareExternalFilename (int fileid, const char *filename)=0
virtual void FileEpilogue ()=0
virtual int IndentedDataDirective (DataDirective directive)=0
virtual DataDirective ByteChunkDataDirective () const
virtual int WriteByteChunk (const uint8_t *data)
virtual void MaybeEmitUnwindData (const char *unwind_info_symbol, const char *embedded_blob_data_symbol, const EmbeddedData *blob, const void *unwind_infos)
Protected Attributes
FILE * fp_ = nullptr
Detailed Description
Definition at line 52 of file platform-embedded-file-writer-base.h.
Constructor & Destructor Documentation
 PlatformEmbeddedFileWriterBase()
virtual v8::internal::PlatformEmbeddedFileWriterBase::~PlatformEmbeddedFileWriterBase () [virtual], [default]
Member Function Documentation
AlignToCodeAlignment()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::AlignToCodeAlignment () [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteCodeSection().
AlignToDataAlignment()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::AlignToDataAlignment () [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteDataSection(), and v8::internal::EmbeddedFileWriter::WriteFileEpilogue().
AlignToPageSizeIfNeeded()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::AlignToPageSizeIfNeeded () [inline], [virtual]
Reimplemented in v8::internal::PlatformEmbeddedFileWriterMac, and v8::internal::PlatformEmbeddedFileWriterGeneric.
Definition at line 63 of file platform-embedded-file-writer-base.h.
{}
Referenced by v8::internal::EmbeddedFileWriter::WriteCodeSection().
ByteChunkDataDirective()
virtual DataDirective v8::internal::PlatformEmbeddedFileWriterBase::ByteChunkDataDirective () const [inline], [virtual]
Reimplemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Definition at line 89 of file platform-embedded-file-writer-base.h.
{ return kOcta; }
References v8::internal::kOcta.
Referenced by v8::internal::PlatformEmbeddedFileWriterGeneric::ByteChunkDataDirective(), v8::internal::PlatformEmbeddedFileWriterWin::ByteChunkDataDirective(), v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly(), and WriteByteChunk().
Comment()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::Comment (const char * string) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteCodeSection(), v8::internal::EmbeddedFileWriter::WriteDataSection(), v8::internal::EmbeddedFileWriter::WriteExternalFilenames(), v8::internal::EmbeddedFileWriter::WriteFileEpilogue(), and v8::internal::EmbeddedFileWriter::WriteFilePrologue().
DeclareExternalFilename()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::DeclareExternalFilename (int fileid, const char * filename) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteExternalFilenames().
DeclareFunctionBegin()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::DeclareFunctionBegin (const char * name, uint32_t size) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteBuiltin(), and v8::internal::EmbeddedFileWriter::WriteCodeSection().
DeclareFunctionEnd()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::DeclareFunctionEnd (const char * name) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteBuiltin(), and v8::internal::EmbeddedFileWriter::WriteCodeSection().
DeclareLabel()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabel (const char * name) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteBuiltinLabels(), v8::internal::EmbeddedFileWriter::WriteCodeSection(), and v8::internal::EmbeddedFileWriter::WriteDataSection().
DeclareLabelEpilogue()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabelEpilogue () [inline], [virtual]
Reimplemented in v8::internal::PlatformEmbeddedFileWriterZOS.
Definition at line 71 of file platform-embedded-file-writer-base.h.
{}
Referenced by v8::internal::EmbeddedFileWriter::WriteCodeSection(), and v8::internal::EmbeddedFileWriter::WriteDataSection().
DeclareLabelProlog()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabelProlog (const char * name) [inline], [virtual]
Reimplemented in v8::internal::PlatformEmbeddedFileWriterZOS.
Definition at line 70 of file platform-embedded-file-writer-base.h.
{}
Referenced by v8::internal::EmbeddedFileWriter::WriteCodeSection(), and v8::internal::EmbeddedFileWriter::WriteDataSection().
DeclareSymbolGlobal()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::DeclareSymbolGlobal (const char * name) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteCodeSection(), and v8::internal::EmbeddedFileWriter::WriteDataSection().
DeclareUint32()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::DeclareUint32 (const char * name, uint32_t value) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteFileEpilogue().
FileEpilogue()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::FileEpilogue () [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteFileEpilogue().
FilePrologue()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::FilePrologue () [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteFilePrologue().
fp()
FILE* v8::internal::PlatformEmbeddedFileWriterBase::fp () const [inline]
Definition at line 57 of file platform-embedded-file-writer-base.h.
{ return fp_; }
References fp_.
Referenced by SetFile(), v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly(), WriteByteChunk(), v8::internal::anonymous_namespace{embedded-file-writer.cc}::WriteDirectiveOrSeparator(), and v8::internal::anonymous_namespace{embedded-file-writer.cc}::WriteLineEndIfNeeded().
HexLiteral()
int v8::internal::PlatformEmbeddedFileWriterBase::HexLiteral (uint64_t value) [virtual]
Reimplemented in v8::internal::PlatformEmbeddedFileWriterZOS, and v8::internal::PlatformEmbeddedFileWriterWin.
Definition at line 28 of file platform-embedded-file-writer-base.cc.
                                                             {
  return fprintf(fp_, "0x%" PRIx64, value);
}
References fp_, and v8::internal::value.
Referenced by v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly(), and v8::internal::EmbeddedFileWriter::WriteCodeSection().
IndentedDataDirective()
virtual int v8::internal::PlatformEmbeddedFileWriterBase::IndentedDataDirective (DataDirective directive) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::anonymous_namespace{embedded-file-writer.cc}::WriteDirectiveOrSeparator().
MaybeEmitUnwindData()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::MaybeEmitUnwindData (const char * unwind_info_symbol, const char * embedded_blob_data_symbol, const EmbeddedData * blob, const void * unwind_infos) [inline], [virtual]
Reimplemented in v8::internal::PlatformEmbeddedFileWriterWin.
Definition at line 97 of file platform-embedded-file-writer-base.h.
                                                             {}
Referenced by v8::internal::EmbeddedFileWriter::WriteFileEpilogue().
Newline()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::Newline () [inline], [virtual]
Definition at line 81 of file platform-embedded-file-writer-base.h.
{ fprintf(fp_, "\n"); }
References fp_.
Referenced by v8::internal::PlatformEmbeddedFileWriterAIX::DeclareFunctionBegin(), v8::internal::PlatformEmbeddedFileWriterAIX::DeclareUint32(), v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareUint32(), v8::internal::PlatformEmbeddedFileWriterMac::DeclareUint32(), v8::internal::PlatformEmbeddedFileWriterWin::DeclareUint32(), v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly(), v8::internal::EmbeddedFileWriter::WriteCodeSection(), v8::internal::EmbeddedFileWriter::WriteDataSection(), v8::internal::EmbeddedFileWriter::WriteExternalFilenames(), v8::internal::EmbeddedFileWriter::WriteFileEpilogue(), and v8::internal::EmbeddedFileWriter::WriteFilePrologue().
SectionRoData()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::SectionRoData () [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteDataSection(), and v8::internal::EmbeddedFileWriter::WriteFileEpilogue().
SectionText()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::SectionText () [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteCodeSection().
SetFile()
void v8::internal::PlatformEmbeddedFileWriterBase::SetFile (FILE * fp) [inline]
Definition at line 56 of file platform-embedded-file-writer-base.h.
{ fp_ = fp; }
References fp(), and fp_.
SourceInfo()
virtual void v8::internal::PlatformEmbeddedFileWriterBase::SourceInfo (int fileid, const char * filename, int line) [pure virtual]
Implemented in v8::internal::PlatformEmbeddedFileWriterZOS, v8::internal::PlatformEmbeddedFileWriterWin, v8::internal::PlatformEmbeddedFileWriterMac, v8::internal::PlatformEmbeddedFileWriterGeneric, and v8::internal::PlatformEmbeddedFileWriterAIX.
Referenced by v8::internal::EmbeddedFileWriter::WriteBuiltin().
WriteByteChunk()
int v8::internal::PlatformEmbeddedFileWriterBase::WriteByteChunk (const uint8_t * data) [virtual]
Reimplemented in v8::internal::PlatformEmbeddedFileWriterZOS, and v8::internal::PlatformEmbeddedFileWriterWin.
Definition at line 46 of file platform-embedded-file-writer-base.cc.
                                                                      {
  size_t kSize = DataDirectiveSize(ByteChunkDataDirective());
  size_t kHalfSize = kSize / 2;
  uint64_t high = 0, low = 0;
  switch (kSize) {
    case 1:
      low = *data;
      break;
    case 4:
      low = *reinterpret_cast<const uint32_t*>(data);
      break;
    case 8:
      low = *reinterpret_cast<const uint64_t*>(data);
      break;
    case 16:
#ifdef V8_TARGET_BIG_ENDIAN
      memcpy(&high, data, kHalfSize);
      memcpy(&low, data + kHalfSize, kHalfSize);
#else
      memcpy(&high, data + kHalfSize, kHalfSize);
      memcpy(&low, data, kHalfSize);
#endif // V8_TARGET_BIG_ENDIAN
      break;
    default:
      UNREACHABLE();
  }
  if (high != 0) {
    return fprintf(fp(), "0x%" PRIx64 "%016" PRIx64, high, low);
  } else {
    return fprintf(fp(), "0x%" PRIx64, low);
  }
}
References ByteChunkDataDirective(), v8::internal::DataDirectiveSize(), fp(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly(), and v8::internal::PlatformEmbeddedFileWriterWin::WriteByteChunk().
Member Data Documentation
fp_
FILE* v8::internal::PlatformEmbeddedFileWriterBase::fp_ = nullptr [protected]
Definition at line 103 of file platform-embedded-file-writer-base.h.
Referenced by v8::internal::PlatformEmbeddedFileWriterAIX::AlignToCodeAlignment(), v8::internal::PlatformEmbeddedFileWriterGeneric::AlignToCodeAlignment(), v8::internal::PlatformEmbeddedFileWriterMac::AlignToCodeAlignment(), v8::internal::PlatformEmbeddedFileWriterWin::AlignToCodeAlignment(), v8::internal::PlatformEmbeddedFileWriterAIX::AlignToDataAlignment(), v8::internal::PlatformEmbeddedFileWriterGeneric::AlignToDataAlignment(), v8::internal::PlatformEmbeddedFileWriterMac::AlignToDataAlignment(), v8::internal::PlatformEmbeddedFileWriterWin::AlignToDataAlignment(), v8::internal::PlatformEmbeddedFileWriterGeneric::AlignToPageSizeIfNeeded(), v8::internal::PlatformEmbeddedFileWriterMac::AlignToPageSizeIfNeeded(), v8::internal::PlatformEmbeddedFileWriterAIX::Comment(), v8::internal::PlatformEmbeddedFileWriterGeneric::Comment(), v8::internal::PlatformEmbeddedFileWriterMac::Comment(), v8::internal::PlatformEmbeddedFileWriterWin::Comment(), v8::internal::PlatformEmbeddedFileWriterZOS::Comment(), v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareExternalFilename(), v8::internal::PlatformEmbeddedFileWriterMac::DeclareExternalFilename(), v8::internal::PlatformEmbeddedFileWriterAIX::DeclareFunctionBegin(), v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareFunctionBegin(), v8::internal::PlatformEmbeddedFileWriterWin::DeclareFunctionBegin(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareFunctionBegin(), v8::internal::PlatformEmbeddedFileWriterAIX::DeclareLabel(), v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareLabel(), v8::internal::PlatformEmbeddedFileWriterMac::DeclareLabel(), v8::internal::PlatformEmbeddedFileWriterWin::DeclareLabel(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareLabel(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareLabelEpilogue(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareLabelProlog(), v8::internal::PlatformEmbeddedFileWriterWin::DeclareRvaToSymbol(), v8::internal::PlatformEmbeddedFileWriterAIX::DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterMac::DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterWin::DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterAIX::DeclareUint32(), v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareUint32(), v8::internal::PlatformEmbeddedFileWriterMac::DeclareUint32(), v8::internal::PlatformEmbeddedFileWriterWin::DeclareUint32(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareUint32(), v8::internal::PlatformEmbeddedFileWriterGeneric::FileEpilogue(), v8::internal::PlatformEmbeddedFileWriterZOS::FileEpilogue(), v8::internal::PlatformEmbeddedFileWriterZOS::FilePrologue(), fp(), HexLiteral(), v8::internal::PlatformEmbeddedFileWriterWin::HexLiteral(), v8::internal::PlatformEmbeddedFileWriterZOS::HexLiteral(), v8::internal::PlatformEmbeddedFileWriterAIX::IndentedDataDirective(), v8::internal::PlatformEmbeddedFileWriterGeneric::IndentedDataDirective(), v8::internal::PlatformEmbeddedFileWriterMac::IndentedDataDirective(), v8::internal::PlatformEmbeddedFileWriterWin::IndentedDataDirective(), Newline(), v8::internal::PlatformEmbeddedFileWriterAIX::SectionRoData(), v8::internal::PlatformEmbeddedFileWriterGeneric::SectionRoData(), v8::internal::PlatformEmbeddedFileWriterMac::SectionRoData(), v8::internal::PlatformEmbeddedFileWriterWin::SectionRoData(), v8::internal::PlatformEmbeddedFileWriterAIX::SectionText(), v8::internal::PlatformEmbeddedFileWriterGeneric::SectionText(), v8::internal::PlatformEmbeddedFileWriterMac::SectionText(), v8::internal::PlatformEmbeddedFileWriterWin::SectionText(), SetFile(), v8::internal::PlatformEmbeddedFileWriterAIX::SourceInfo(), v8::internal::PlatformEmbeddedFileWriterGeneric::SourceInfo(), v8::internal::PlatformEmbeddedFileWriterMac::SourceInfo(), v8::internal::PlatformEmbeddedFileWriterZOS::SourceInfo(), v8::internal::PlatformEmbeddedFileWriterWin::StartPdataSection(), and v8::internal::PlatformEmbeddedFileWriterWin::StartXdataSection().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-base.h
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-base.cc