v8::internal::compiler::turboshaft::OperationBuffer Class Reference
#include <graph.h>
Classes
class ReplaceScope
Public Member Functions
OperationBuffer (Zone *zone, size_t initial_capacity)
OperationStorageSlot * Allocate (size_t slot_count)
void RemoveLast ()
OpIndex Index (const Operation &op) const
OpIndex Index (const OperationStorageSlot *ptr) const
OperationStorageSlot * Get (OpIndex idx)
uint16_t SlotCount (OpIndex idx)
const OperationStorageSlot * Get (OpIndex idx) const
OpIndex Next (OpIndex idx) const
OpIndex Previous (OpIndex idx) const
OpIndex BeginIndex () const
OpIndex EndIndex () const
uint32_t size () const
uint32_t capacity () const
void Grow (size_t min_capacity)
void Reset ()
Private Attributes
Zone * zone_
OperationStorageSlot * begin_
OperationStorageSlot * end_
OperationStorageSlot * end_cap_
uint16_t * operation_sizes_
Detailed Description
Definition at line 39 of file graph.h.
Constructor & Destructor Documentation
OperationBuffer()
v8::internal::compiler::turboshaft::OperationBuffer::OperationBuffer (Zone * zone, size_t initial_capacity) [inline], [explicit]
Definition at line 75 of file graph.h.
                                                                : zone_(zone) {
    DCHECK_NE(initial_capacity, 0);
    begin_ = end_ =
        zone_->AllocateArray<OperationStorageSlot>(initial_capacity);
    operation_sizes_ =
        zone_->AllocateArray<uint16_t>((initial_capacity + 1) / kSlotsPerId);
    end_cap_ = begin_ + initial_capacity;
  }
References v8::internal::Zone::AllocateArray(), begin_, DCHECK_NE, end_, end_cap_, v8::internal::compiler::turboshaft::kSlotsPerId, operation_sizes_, and zone_.
Member Function Documentation
Allocate()
OperationStorageSlot* v8::internal::compiler::turboshaft::OperationBuffer::Allocate (size_t slot_count) [inline]
Definition at line 84 of file graph.h.
                                                    {
    if (V8_UNLIKELY(static_cast<size_t>(end_cap_ - end_) < slot_count)) {
      Grow(capacity() + slot_count);
      DCHECK(slot_count <= static_cast<size_t>(end_cap_ - end_));
    }
    OperationStorageSlot* result = end_;
    end_ += slot_count;
    OpIndex idx = Index(result);
    // Store the size in both for the first and last id corresponding to the new
    // operation. This enables iteration in both directions. The two id's are
    // the same if the operation is small.
    operation_sizes_[idx.id()] = slot_count;
    operation_sizes_[OpIndex(idx.offset() + static_cast<uint32_t>(slot_count) *
                                                sizeof(OperationStorageSlot))
                         .id() -
                     1] = slot_count;
    return result;
  }
References capacity(), v8::internal::DCHECK(), end_, end_cap_, Grow(), v8::internal::compiler::turboshaft::OpIndex::id(), Index(), v8::internal::compiler::turboshaft::OpIndex::offset(), operation_sizes_, v8::internal::compiler::turboshaft::OpIndex, v8::base::internal::result, and V8_UNLIKELY.
Referenced by v8::internal::compiler::turboshaft::Graph::Allocate().
BeginIndex()
OpIndex v8::internal::compiler::turboshaft::OperationBuffer::BeginIndex () const [inline]
Definition at line 153 of file graph.h.
{ return OpIndex(0); }
References v8::internal::compiler::turboshaft::OpIndex.
Referenced by v8::internal::compiler::turboshaft::Graph::BeginIndex().
capacity()
uint32_t v8::internal::compiler::turboshaft::OperationBuffer::capacity () const [inline]
Definition at line 158 of file graph.h.
{ return static_cast<uint32_t>(end_cap_ - begin_); }
References begin_, and end_cap_.
Referenced by Allocate(), Get(), Grow(), Next(), v8::internal::compiler::turboshaft::Graph::op_id_capacity(), and Previous().
EndIndex()
OpIndex v8::internal::compiler::turboshaft::OperationBuffer::EndIndex () const [inline]
Definition at line 155 of file graph.h.
{ return Index(end_); }
References end_, and Index().
Referenced by v8::internal::compiler::turboshaft::Graph::EndIndex(), and RemoveLast().
Get() [1/2]
OperationStorageSlot* v8::internal::compiler::turboshaft::OperationBuffer::Get (OpIndex idx) [inline]
Definition at line 118 of file graph.h.
                                         {
    DCHECK_LT(idx.offset() / sizeof(OperationStorageSlot), size());
    return reinterpret_cast<OperationStorageSlot*>(
        reinterpret_cast<Address>(begin_) + idx.offset());
  }
References begin_, DCHECK_LT, v8::internal::compiler::turboshaft::OpIndex::offset(), and size().
Referenced by v8::internal::compiler::turboshaft::Graph::Get(), and v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::ReplaceScope().
Get() [2/2]
const OperationStorageSlot* v8::internal::compiler::turboshaft::OperationBuffer::Get (OpIndex idx) const [inline]
Definition at line 128 of file graph.h.
                                                     {
    DCHECK_LT(idx.offset(), capacity() * sizeof(OperationStorageSlot));
    return reinterpret_cast<const OperationStorageSlot*>(
        reinterpret_cast<Address>(begin_) + idx.offset());
  }
References begin_, capacity(), DCHECK_LT, and v8::internal::compiler::turboshaft::OpIndex::offset().
Grow()
void v8::internal::compiler::turboshaft::OperationBuffer::Grow (size_t min_capacity) [inline]
Definition at line 160 of file graph.h.
                                 {
    size_t size = this->size();
    size_t capacity = this->capacity();
    size_t new_capacity = 2 * capacity;
    while (new_capacity < min_capacity) new_capacity *= 2;
    CHECK_LT(new_capacity, std::numeric_limits<uint32_t>::max() /
                               sizeof(OperationStorageSlot));
    OperationStorageSlot* new_buffer =
        zone_->AllocateArray<OperationStorageSlot>(new_capacity);
    memcpy(new_buffer, begin_, size * sizeof(OperationStorageSlot));
    uint16_t* new_operation_sizes =
        zone_->AllocateArray<uint16_t>(new_capacity / kSlotsPerId);
    memcpy(new_operation_sizes, operation_sizes_,
           size / kSlotsPerId * sizeof(uint16_t));
    begin_ = new_buffer;
    end_ = new_buffer + size;
    end_cap_ = new_buffer + new_capacity;
    operation_sizes_ = new_operation_sizes;
  }
References v8::internal::Zone::AllocateArray(), begin_, capacity(), CHECK_LT, end_, end_cap_, v8::internal::compiler::turboshaft::kSlotsPerId, operation_sizes_, size(), and zone_.
Referenced by Allocate().
Index() [1/2]
OpIndex v8::internal::compiler::turboshaft::OperationBuffer::Index (const Operation & op) const [inline]
Definition at line 109 of file graph.h.
                                           {
    return Index(reinterpret_cast<const OperationStorageSlot*>(&op));
  }
Referenced by Allocate(), EndIndex(), and v8::internal::compiler::turboshaft::Graph::Index().
Index() [2/2]
OpIndex v8::internal::compiler::turboshaft::OperationBuffer::Index (const OperationStorageSlot * ptr) const [inline]
Definition at line 112 of file graph.h.
                                                       {
    DCHECK(begin_ <= ptr && ptr <= end_);
    return OpIndex(static_cast<uint32_t>(reinterpret_cast<Address>(ptr) -
                                         reinterpret_cast<Address>(begin_)));
  }
References begin_, v8::internal::DCHECK(), end_, and v8::internal::compiler::turboshaft::OpIndex.
Next()
OpIndex v8::internal::compiler::turboshaft::OperationBuffer::Next (OpIndex idx) const [inline]
Definition at line 134 of file graph.h.
                                  {
    DCHECK_GT(operation_sizes_[idx.id()], 0);
    OpIndex result = OpIndex(idx.offset() + operation_sizes_[idx.id()] *
                                                sizeof(OperationStorageSlot));
    DCHECK_LT(0, result.offset());
    DCHECK_LE(result.offset(), capacity() * sizeof(OperationStorageSlot));
    return result;
  }
References capacity(), DCHECK_GT, DCHECK_LE, DCHECK_LT, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::OpIndex::offset(), operation_sizes_, v8::internal::compiler::turboshaft::OpIndex, and v8::base::internal::result.
Referenced by v8::internal::compiler::turboshaft::Graph::NextIndex().
Previous()
OpIndex v8::internal::compiler::turboshaft::OperationBuffer::Previous (OpIndex idx) const [inline]
Definition at line 142 of file graph.h.
                                      {
    DCHECK_GT(idx.id(), 0);
    DCHECK_GT(operation_sizes_[idx.id() - 1], 0);
    OpIndex result = OpIndex(idx.offset() - operation_sizes_[idx.id() - 1] *
                                                sizeof(OperationStorageSlot));
    DCHECK_LE(0, result.offset());
    DCHECK_LT(result.offset(), capacity() * sizeof(OperationStorageSlot));
    return result;
  }
References capacity(), DCHECK_GT, DCHECK_LE, DCHECK_LT, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::OpIndex::offset(), operation_sizes_, v8::internal::compiler::turboshaft::OpIndex, and v8::base::internal::result.
Referenced by v8::internal::compiler::turboshaft::Graph::PreviousIndex().
RemoveLast()
void v8::internal::compiler::turboshaft::OperationBuffer::RemoveLast () [inline]
Definition at line 103 of file graph.h.
                    {
    size_t slot_count = operation_sizes_[EndIndex().id() - 1];
    end_ -= slot_count;
    DCHECK_GE(end_, begin_);
  }
References begin_, DCHECK_GE, end_, EndIndex(), v8::internal::compiler::turboshaft::OpIndex::id(), and operation_sizes_.
Referenced by v8::internal::compiler::turboshaft::Graph::RemoveLast().
Reset()
void v8::internal::compiler::turboshaft::OperationBuffer::Reset () [inline]
Definition at line 183 of file graph.h.
{ end_ = begin_; }
References begin_, and end_.
Referenced by v8::internal::compiler::turboshaft::Graph::Reset().
size()
uint32_t v8::internal::compiler::turboshaft::OperationBuffer::size () const [inline]
Definition at line 157 of file graph.h.
{ return static_cast<uint32_t>(end_ - begin_); }
References begin_, and end_.
Referenced by Get(), v8::internal::compiler::turboshaft::Graph::GetOrCreateCompanion(), Grow(), v8::internal::compiler::turboshaft::Graph::op_id_count(), and SlotCount().
SlotCount()
uint16_t v8::internal::compiler::turboshaft::OperationBuffer::SlotCount (OpIndex idx) [inline]
Definition at line 123 of file graph.h.
                                  {
    DCHECK_LT(idx.offset() / sizeof(OperationStorageSlot), size());
    return operation_sizes_[idx.id()];
  }
References DCHECK_LT, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::OpIndex::offset(), operation_sizes_, and size().
Referenced by v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::~ReplaceScope().
Member Data Documentation
begin_
OperationStorageSlot* v8::internal::compiler::turboshaft::OperationBuffer::begin_ [private]
Definition at line 187 of file graph.h.
Referenced by capacity(), Get(), Grow(), Index(), OperationBuffer(), RemoveLast(), Reset(), and size().
end_
OperationStorageSlot* v8::internal::compiler::turboshaft::OperationBuffer::end_ [private]
Definition at line 188 of file graph.h.
Referenced by Allocate(), EndIndex(), Grow(), Index(), OperationBuffer(), RemoveLast(), v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::ReplaceScope(), Reset(), size(), and v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::~ReplaceScope().
end_cap_
OperationStorageSlot* v8::internal::compiler::turboshaft::OperationBuffer::end_cap_ [private]
Definition at line 189 of file graph.h.
Referenced by Allocate(), capacity(), Grow(), and OperationBuffer().
operation_sizes_
uint16_t* v8::internal::compiler::turboshaft::OperationBuffer::operation_sizes_ [private]
Definition at line 190 of file graph.h.
Referenced by Allocate(), Grow(), Next(), OperationBuffer(), Previous(), RemoveLast(), SlotCount(), and v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::~ReplaceScope().
zone_
Zone* v8::internal::compiler::turboshaft::OperationBuffer::zone_ [private]
Definition at line 186 of file graph.h.
Referenced by Grow(), and OperationBuffer().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/graph.h