v8::internal::GraphBuildingVisitor Class Reference
Public Member Functions
GraphBuildingVisitor (CppGraphBuilderImpl &graph_builder, const ParentScope &parent_scope)
void Visit (const void *, cppgc::TraceDescriptor desc) final
void VisitWeakContainer (const void *object, cppgc::TraceDescriptor strong_desc, cppgc::TraceDescriptor weak_desc, cppgc::WeakCallback, const void *) final
void Visit (const TracedReferenceBase &ref) final
void set_edge_name (std::string_view edge_name)
Private Attributes
CppGraphBuilderImpl & graph_builder_
const ParentScope & parent_scope_
std::string edge_name_
Additional Inherited Members
Detailed Description
Definition at line 756 of file cpp-snapshot.cc.
Constructor & Destructor Documentation
GraphBuildingVisitor()
v8::internal::GraphBuildingVisitor::GraphBuildingVisitor (CppGraphBuilderImpl & graph_builder, const ParentScope & parent_scope) [inline]
Definition at line 758 of file cpp-snapshot.cc.
      : JSVisitor(cppgc::internal::VisitorFactory::CreateKey()),
        graph_builder_(graph_builder),
        parent_scope_(parent_scope) {}
Member Function Documentation
set_edge_name()
void v8::internal::GraphBuildingVisitor::set_edge_name (std::string_view edge_name) [inline]
Definition at line 788 of file cpp-snapshot.cc.
{ edge_name_ = edge_name; }
Referenced by v8::internal::CppGraphBuilderImpl::Run().
Visit() [1/2]
void v8::internal::GraphBuildingVisitor::Visit (const TracedReferenceBase & ref) [inline], [final], [virtual]
Reimplemented from v8::JSVisitor.
Definition at line 783 of file cpp-snapshot.cc.
                                                   {
    graph_builder_.AddEdge(parent_scope_.ParentAsRegularState(), ref,
                           edge_name_);
  }
Visit() [2/2]
void v8::internal::GraphBuildingVisitor::Visit (const void * , cppgc::TraceDescriptor desc) [inline], [final], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 765 of file cpp-snapshot.cc.
                                                           {
    graph_builder_.AddEdge(
        parent_scope_.ParentAsRegularState(),
        HeapObjectHeader::FromObject(desc.base_object_payload), edge_name_);
  }
References cppgc::internal::HeapObjectHeader::FromObject().
VisitWeakContainer()
void v8::internal::GraphBuildingVisitor::VisitWeakContainer (const void * object, cppgc::TraceDescriptor strong_desc, cppgc::TraceDescriptor weak_desc, cppgc::WeakCallback , const void *) [inline], [final], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 770 of file cpp-snapshot.cc.
                                             {
    // Add an edge from the object holding the weak container to the weak
    // container itself.
    graph_builder_.AddEdge(
        parent_scope_.ParentAsRegularState(),
        HeapObjectHeader::FromObject(strong_desc.base_object_payload),
        edge_name_);
  }
References cppgc::internal::HeapObjectHeader::FromObject().
Member Data Documentation
edge_name_
std::string v8::internal::GraphBuildingVisitor::edge_name_ [private]
Definition at line 793 of file cpp-snapshot.cc.
graph_builder_
CppGraphBuilderImpl& v8::internal::GraphBuildingVisitor::graph_builder_ [private]
Definition at line 791 of file cpp-snapshot.cc.
parent_scope_
const ParentScope& v8::internal::GraphBuildingVisitor::parent_scope_ [private]
Definition at line 792 of file cpp-snapshot.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-snapshot.cc