v8_inspector::V8RuntimeAgentImpl Class Reference
#include <v8-runtime-agent-impl.h>
Public Member Functions
V8RuntimeAgentImpl (V8InspectorSessionImpl *, protocol::FrontendChannel *, protocol::DictionaryValue *state, std::shared_ptr< V8DebuggerBarrier >)
~V8RuntimeAgentImpl () override
V8RuntimeAgentImpl (const V8RuntimeAgentImpl &)=delete
V8RuntimeAgentImpl & operator= (const V8RuntimeAgentImpl &)=delete
void restore ()
Response enable () override
Response disable () override
void evaluate (const String16 &expression, std::optional< String16 > objectGroup, std::optional< bool > includeCommandLineAPI, std::optional< bool > silent, std::optional< int > executionContextId, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::optional< bool > userGesture, std::optional< bool > awaitPromise, std::optional< bool > throwOnSideEffect, std::optional< double > timeout, std::optional< bool > disableBreaks, std::optional< bool > replMode, std::optional< bool > allowUnsafeEvalBlockedByCSP, std::optional< String16 > uniqueContextId, std::unique_ptr< protocol::Runtime::SerializationOptions > serializationOptions, std::unique_ptr< EvaluateCallback >) override
void awaitPromise (const String16 &promiseObjectId, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::unique_ptr< AwaitPromiseCallback >) override
void callFunctionOn (const String16 &expression, std::optional< String16 > objectId, std::unique_ptr< protocol::Array< protocol::Runtime::CallArgument >> optionalArguments, std::optional< bool > silent, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::optional< bool > userGesture, std::optional< bool > awaitPromise, std::optional< int > executionContextId, std::optional< String16 > objectGroup, std::optional< bool > throwOnSideEffect, std::optional< String16 > uniqueContextId, std::unique_ptr< protocol::Runtime::SerializationOptions > serializationOptions, std::unique_ptr< CallFunctionOnCallback >) override
Response releaseObject (const String16 &objectId) override
Response getProperties (const String16 &objectId, std::optional< bool > ownProperties, std::optional< bool > accessorPropertiesOnly, std::optional< bool > generatePreview, std::optional< bool > nonIndexedPropertiesOnly, std::unique_ptr< protocol::Array< protocol::Runtime::PropertyDescriptor >> *result, std::unique_ptr< protocol::Array< protocol::Runtime::InternalPropertyDescriptor >> *internalProperties, std::unique_ptr< protocol::Array< protocol::Runtime::PrivatePropertyDescriptor >> *privateProperties, std::unique_ptr< protocol::Runtime::ExceptionDetails > *) override
Response releaseObjectGroup (const String16 &objectGroup) override
Response runIfWaitingForDebugger () override
Response setCustomObjectFormatterEnabled (bool) override
Response setMaxCallStackSizeToCapture (int) override
Response discardConsoleEntries () override
Response compileScript (const String16 &expression, const String16 &sourceURL, bool persistScript, std::optional< int > executionContextId, std::optional< String16 > *, std::unique_ptr< protocol::Runtime::ExceptionDetails > *) override
void runScript (const String16 &, std::optional< int > executionContextId, std::optional< String16 > objectGroup, std::optional< bool > silent, std::optional< bool > includeCommandLineAPI, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::optional< bool > awaitPromise, std::unique_ptr< RunScriptCallback >) override
Response queryObjects (const String16 &prototypeObjectId, std::optional< String16 > objectGroup, std::unique_ptr< protocol::Runtime::RemoteObject > *objects) override
Response globalLexicalScopeNames (std::optional< int > executionContextId, std::unique_ptr< protocol::Array< String16 >> *outNames) override
Response getIsolateId (String16 *outIsolateId) override
Response getHeapUsage (double *out_usedSize, double *out_totalSize, double *out_embedderHeapUsedSize, double *out_backingStorageSize) override
void terminateExecution (std::unique_ptr< TerminateExecutionCallback > callback) override
Response addBinding (const String16 &name, std::optional< int > executionContextId, std::optional< String16 > executionContextName) override
Response removeBinding (const String16 &name) override
void addBindings (InspectedContext *context)
Response getExceptionDetails (const String16 &errorObjectId, std::unique_ptr< protocol::Runtime::ExceptionDetails > *out_exceptionDetails) override
void reset ()
void reportExecutionContextCreated (InspectedContext *)
void reportExecutionContextDestroyed (InspectedContext *)
void inspect (std::unique_ptr< protocol::Runtime::RemoteObject > objectToInspect, std::unique_ptr< protocol::DictionaryValue > hints, int executionContextId)
void messageAdded (V8ConsoleMessage *)
bool enabled () const
Private Member Functions
bool reportMessage (V8ConsoleMessage *, bool generatePreview)
void bindingCalled (const String16 &name, const String16 &payload, int executionContextId)
void addBinding (InspectedContext *context, const String16 &name)
Static Private Member Functions
static void bindingCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
Private Attributes
V8InspectorSessionImpl * m_session
protocol::DictionaryValue * m_state
protocol::Runtime::Frontend m_frontend
V8InspectorImpl * m_inspector
std::shared_ptr< V8DebuggerBarrier > m_debuggerBarrier
bool m_enabled
std::unordered_map< String16, std::unique_ptr< v8::Global< v8::Script > > > m_compiledScripts
std::unordered_map< String16, std::unordered_set< int > > m_activeBindings
Detailed Description
Definition at line 58 of file v8-runtime-agent-impl.h.
Constructor & Destructor Documentation
V8RuntimeAgentImpl() [1/2]
v8_inspector::V8RuntimeAgentImpl::V8RuntimeAgentImpl (V8InspectorSessionImpl * session, protocol::FrontendChannel * FrontendChannel, protocol::DictionaryValue * state, std::shared_ptr< V8DebuggerBarrier > debuggerBarrier)
Definition at line 341 of file v8-runtime-agent-impl.cc.
    : m_session(session),
      m_state(state),
      m_frontend(FrontendChannel),
      m_inspector(session->inspector()),
      m_debuggerBarrier(debuggerBarrier),
      m_enabled(false) {}
 V8RuntimeAgentImpl()
v8_inspector::V8RuntimeAgentImpl::~V8RuntimeAgentImpl () [override], [default]
V8RuntimeAgentImpl() [2/2]
v8_inspector::V8RuntimeAgentImpl::V8RuntimeAgentImpl (const V8RuntimeAgentImpl &) [delete]
Member Function Documentation
addBinding() [1/2]
Response v8_inspector::V8RuntimeAgentImpl::addBinding (const String16 & name, std::optional< int > executionContextId, std::optional< String16 > executionContextName) [override]
Definition at line 894 of file v8-runtime-agent-impl.cc.
                                                {
  if (executionContextId.has_value()) {
    if (executionContextName.has_value()) {
      return Response::InvalidParams(
          "executionContextName is mutually exclusive with executionContextId");
    }
    int contextId = executionContextId.value();
    InspectedContext* context =
        m_inspector->getContext(m_session->contextGroupId(), contextId);
    if (!context) {
      return Response::InvalidParams(
          "Cannot find execution context with given executionContextId");
    }
    addBinding(context, name);
    return Response::Success();
  }
  // If it's a globally exposed binding, i.e. no context name specified, use
  // a special value for the context name.
  String16 contextKey = V8RuntimeAgentImplState::globalBindingsKey;
  if (executionContextName.has_value()) {
    contextKey = executionContextName.value();
    if (contextKey == V8RuntimeAgentImplState::globalBindingsKey) {
      return Response::InvalidParams("Invalid executionContextName");
    }
  }
  // Only persist non context-specific bindings, as contextIds don't make
  // any sense when state is restored in a different process.
  protocol::DictionaryValue* bindings =
      getOrCreateDictionary(m_state, V8RuntimeAgentImplState::bindings);
  protocol::DictionaryValue* contextBindings =
      getOrCreateDictionary(bindings, contextKey);
  contextBindings->setBoolean(name, true);
  m_inspector->forEachContext(
      m_session->contextGroupId(),
      [&name, &executionContextName, this](InspectedContext* context) {
        if (executionContextName.has_value() &&
            executionContextName.value() != context->humanReadableName())
          return;
        addBinding(context, name);
      });
  return Response::Success();
}
References v8_inspector::V8RuntimeAgentImplState::bindings, v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::forEachContext(), v8_inspector::V8InspectorImpl::getContext(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getOrCreateDictionary(), v8_inspector::V8RuntimeAgentImplState::globalBindingsKey, m_inspector, m_session, m_state, and name.
Referenced by addBindings().
addBinding() [2/2]
void v8_inspector::V8RuntimeAgentImpl::addBinding (InspectedContext * context, const String16 & name) [private]
Definition at line 964 of file v8-runtime-agent-impl.cc.
                                                          {
  auto it = m_activeBindings.find(name);
  if (it != m_activeBindings.end() && it->second.count(context->contextId())) {
    return;
  }
  v8::HandleScope handles(m_inspector->isolate());
  v8::Local<v8::Context> localContext = context->context();
  v8::Local<v8::Object> global = localContext->Global();
  v8::Local<v8::String> v8Name = toV8String(m_inspector->isolate(), name);
  v8::Local<v8::Value> functionValue;
  v8::MicrotasksScope microtasks(localContext,
                                 v8::MicrotasksScope::kDoNotRunMicrotasks);
  if (v8::Function::New(localContext, bindingCallback, v8Name)
          .ToLocal(&functionValue)) {
    v8::Maybe<bool> success = global->Set(localContext, v8Name, functionValue);
    USE(success);
    if (it == m_activeBindings.end()) {
      m_activeBindings.emplace(name,
                               std::unordered_set<int>(context->contextId()));
    } else {
      m_activeBindings.at(name).insert(context->contextId());
    }
  }
}
References bindingCallback(), v8_inspector::InspectedContext::context(), v8_inspector::InspectedContext::contextId(), v8::Context::Global(), v8_inspector::V8InspectorImpl::isolate(), v8::MicrotasksScope::kDoNotRunMicrotasks, m_activeBindings, m_inspector, name, v8::Function::New(), v8::Object::Set(), v8_inspector::toV8String(), and USE.
addBindings()
void v8_inspector::V8RuntimeAgentImpl::addBindings (InspectedContext * context)
Definition at line 1043 of file v8-runtime-agent-impl.cc.
                                                              {
  const String16 contextName = context->humanReadableName();
  if (!m_enabled) return;
  protocol::DictionaryValue* bindings =
      m_state->getObject(V8RuntimeAgentImplState::bindings);
  if (!bindings) return;
  protocol::DictionaryValue* globalBindings =
      bindings->getObject(V8RuntimeAgentImplState::globalBindingsKey);
  if (globalBindings) {
    for (size_t i = 0; i < globalBindings->size(); ++i)
      addBinding(context, globalBindings->at(i).first);
  }
  protocol::DictionaryValue* contextBindings =
      contextName.isEmpty() ? nullptr : bindings->getObject(contextName);
  if (contextBindings) {
    for (size_t i = 0; i < contextBindings->size(); ++i)
      addBinding(context, contextBindings->at(i).first);
  }
}
References addBinding(), v8_inspector::V8RuntimeAgentImplState::bindings, v8_inspector::V8RuntimeAgentImplState::globalBindingsKey, v8_inspector::InspectedContext::humanReadableName(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::String16::isEmpty(), m_enabled, m_state, and nullptr.
awaitPromise()
void v8_inspector::V8RuntimeAgentImpl::awaitPromise (const String16 & promiseObjectId, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::unique_ptr< AwaitPromiseCallback > callback) [override]
Definition at line 453 of file v8-runtime-agent-impl.cc.
                                                  {
  InjectedScript::ObjectScope scope(m_session, promiseObjectId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  if (!scope.object()->IsPromise()) {
    callback->sendFailure(
        Response::ServerError("Could not find promise with given id"));
    return;
  }
  std::unique_ptr<WrapOptions> wrapOptions;
  response =
      getWrapOptions(std::move(returnByValue), std::move(generatePreview),
                     m_inspector->isolate(), &wrapOptions);
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  scope.injectedScript()->addPromiseCallback(
      m_session, scope.object(), scope.objectGroupName(),
      std::move(wrapOptions), false /* replMode */,
      false /* throwOnSideEffect */,
      EvaluateCallbackWrapper<AwaitPromiseCallback>::wrap(std::move(callback)));
}
References v8_inspector::InjectedScript::addPromiseCallback(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getWrapOptions(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::V8InspectorImpl::isolate(), v8::Value::IsPromise(), m_inspector, m_session, v8_inspector::InjectedScript::ObjectScope::object(), and v8_inspector::InjectedScript::ObjectScope::objectGroupName().
Referenced by callFunctionOn(), and runScript().
bindingCallback()
void v8_inspector::V8RuntimeAgentImpl::bindingCallback (const v8::FunctionCallbackInfo< v8::Value > & info) [static], [private]
Definition at line 941 of file v8-runtime-agent-impl.cc.
                                                 {
  v8::Isolate* isolate = info.GetIsolate();
  if (info.Length() != 1 || !info[0]->IsString()) {
    info.GetIsolate()->ThrowError(
        "Invalid arguments: should be exactly one string.");
    return;
  }
  V8InspectorImpl* inspector =
      static_cast<V8InspectorImpl*>(v8::debug::GetInspector(isolate));
  int contextId = InspectedContext::contextId(isolate->GetCurrentContext());
  int contextGroupId = inspector->contextGroupId(contextId);
  String16 name = toProtocolString(isolate, info.Data().As<v8::String>());
  String16 payload = toProtocolString(isolate, info[0].As<v8::String>());
  inspector->forEachSession(
      contextGroupId,
      [&name, &payload, &contextId](V8InspectorSessionImpl* session) {
        session->runtimeAgent()->bindingCalled(name, payload, contextId);
      });
}
References bindingCalled(), v8_inspector::V8InspectorImpl::contextGroupId(), v8_inspector::InspectedContext::contextId(), v8::FunctionCallbackInfo< T >::Data(), v8_inspector::V8InspectorImpl::forEachSession(), v8::Isolate::GetCurrentContext(), v8::debug::GetInspector(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), name, v8_inspector::V8InspectorSessionImpl::runtimeAgent(), v8::Isolate::ThrowError(), and v8_inspector::toProtocolString().
Referenced by addBinding().
bindingCalled()
void v8_inspector::V8RuntimeAgentImpl::bindingCalled (const String16 & name, const String16 & payload, int executionContextId) [private]
Definition at line 1035 of file v8-runtime-agent-impl.cc.
                                                               {
  if (!m_activeBindings.count(name)) return;
  m_frontend.bindingCalled(name, payload, executionContextId);
  m_frontend.flush();
}
References m_activeBindings, m_frontend, and name.
Referenced by bindingCallback().
callFunctionOn()
void v8_inspector::V8RuntimeAgentImpl::callFunctionOn (const String16 & expression, std::optional< String16 > objectId, std::unique_ptr< protocol::Array< protocol::Runtime::CallArgument >> optionalArguments, std::optional< bool > silent, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::optional< bool > userGesture, std::optional< bool > awaitPromise, std::optional< int > executionContextId, std::optional< String16 > objectGroup, std::optional< bool > throwOnSideEffect, std::optional< String16 > uniqueContextId, std::unique_ptr< protocol::Runtime::SerializationOptions > serializationOptions, std::unique_ptr< CallFunctionOnCallback > callback) [override]
Definition at line 485 of file v8-runtime-agent-impl.cc.
                                                    {
  int justCount = (objectId.has_value() ? 1 : 0) +
                  (executionContextId.has_value() ? 1 : 0) +
                  (uniqueContextId.has_value() ? 1 : 0);
  if (justCount > 1) {
    callback->sendFailure(Response::InvalidParams(
        "ObjectId, executionContextId and uniqueContextId must mutually "
        "exclude each other"));
    return;
  }
  if (justCount < 1) {
    callback->sendFailure(
        Response::InvalidParams("Either objectId or executionContextId or "
                                "uniqueContextId must be specified"));
    return;
  }
  if (objectId.has_value()) {
    InjectedScript::ObjectScope scope(m_session, objectId.value());
    Response response = scope.initialize();
    if (!response.IsSuccess()) {
      callback->sendFailure(response);
      return;
    }
    std::unique_ptr<WrapOptions> wrapOptions;
    response = getWrapOptions(
        std::move(returnByValue), std::move(generatePreview),
        std::move(serializationOptions), m_inspector->isolate(), &wrapOptions);
    if (!response.IsSuccess()) {
      callback->sendFailure(response);
      return;
    }
    innerCallFunctionOn(m_session, scope, scope.object(), expression,
                        std::move(optionalArguments), silent.value_or(false),
                        std::move(wrapOptions), userGesture.value_or(false),
                        awaitPromise.value_or(false),
                        objectGroup.value_or(scope.objectGroupName()),
                        throwOnSideEffect.value_or(false), std::move(callback));
  } else {
    int contextId = 0;
    Response response = ensureContext(m_inspector, m_session->contextGroupId(),
                                      std::move(executionContextId),
                                      std::move(uniqueContextId), &contextId);
    if (!response.IsSuccess()) {
      callback->sendFailure(response);
      return;
    }
    InjectedScript::ContextScope scope(m_session, contextId);
    response = scope.initialize();
    if (!response.IsSuccess()) {
      callback->sendFailure(response);
      return;
    }
    std::unique_ptr<WrapOptions> wrapOptions;
    response = getWrapOptions(
        std::move(returnByValue), std::move(generatePreview),
        std::move(serializationOptions), m_inspector->isolate(), &wrapOptions);
    if (!response.IsSuccess()) {
      callback->sendFailure(response);
      return;
    }
    innerCallFunctionOn(m_session, scope, scope.context()->Global(), expression,
                        std::move(optionalArguments), silent.value_or(false),
                        std::move(wrapOptions), userGesture.value_or(false),
                        awaitPromise.value_or(false), objectGroup.value_or(""),
                        throwOnSideEffect.value_or(false), std::move(callback));
  }
}
References awaitPromise(), v8_inspector::InjectedScript::Scope::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getWrapOptions(), v8::Context::Global(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::V8InspectorImpl::isolate(), m_inspector, m_session, v8_inspector::InjectedScript::ObjectScope::object(), and v8_inspector::InjectedScript::ObjectScope::objectGroupName().
compileScript()
Response v8_inspector::V8RuntimeAgentImpl::compileScript (const String16 & expression, const String16 & sourceURL, bool persistScript, std::optional< int > executionContextId, std::optional< String16 > * scriptId, std::unique_ptr< protocol::Runtime::ExceptionDetails > * exceptionDetails) [override]
Definition at line 681 of file v8-runtime-agent-impl.cc.
                                                                      {
  if (!m_enabled) return Response::ServerError("Runtime agent is not enabled");
  int contextId = 0;
  Response response = ensureContext(m_inspector, m_session->contextGroupId(),
                                    std::move(executionContextId),
                                    /*uniqueContextId*/ {}, &contextId);
  if (!response.IsSuccess()) return response;
  InjectedScript::ContextScope scope(m_session, contextId);
  response = scope.initialize();
  if (!response.IsSuccess()) return response;
  if (!persistScript) m_inspector->debugger()->muteScriptParsedEvents();
  v8::Local<v8::Script> script;
  bool isOk = m_inspector->compileScript(scope.context(), expression, sourceURL)
                  .ToLocal(&script);
  if (!persistScript) m_inspector->debugger()->unmuteScriptParsedEvents();
  if (!isOk) {
    if (scope.tryCatch().HasCaught()) {
      response = scope.injectedScript()->createExceptionDetails(
          scope.tryCatch(), String16(), exceptionDetails);
      if (!response.IsSuccess()) return response;
      return Response::Success();
    } else {
      return Response::ServerError("Script compilation failed");
    }
  }
  if (!persistScript) return Response::Success();
  String16 scriptValueId =
      String16::fromInteger(script->GetUnboundScript()->GetId());
  std::unique_ptr<v8::Global<v8::Script>> global(
      new v8::Global<v8::Script>(m_inspector->isolate(), script));
  m_compiledScripts[scriptValueId] = std::move(global);
  *scriptId = scriptValueId;
  return Response::Success();
}
References v8_inspector::V8InspectorImpl::compileScript(), v8_inspector::InjectedScript::Scope::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::V8InspectorImpl::debugger(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8_inspector::String16::fromInteger(), v8::TryCatch::HasCaught(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::V8InspectorImpl::isolate(), m_compiledScripts, m_enabled, m_inspector, m_session, v8_inspector::V8Debugger::muteScriptParsedEvents(), v8::internal::script, v8_inspector::InjectedScript::Scope::tryCatch(), and v8_inspector::V8Debugger::unmuteScriptParsedEvents().
disable()
Response v8_inspector::V8RuntimeAgentImpl::disable () [override]
Definition at line 1102 of file v8-runtime-agent-impl.cc.
                                     {
  if (!m_enabled) return Response::Success();
  TRACE_EVENT_WITH_FLOW0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                         "V8RuntimeAgentImpl::disable", this,
                         TRACE_EVENT_FLAG_FLOW_IN);
  m_enabled = false;
  m_state->setBoolean(V8RuntimeAgentImplState::runtimeEnabled, false);
  m_state->remove(V8RuntimeAgentImplState::bindings);
  m_inspector->debugger()->setMaxCallStackSizeToCapture(this, -1);
  m_session->setCustomObjectFormatterEnabled(false);
  reset();
  m_inspector->client()->endEnsureAllContextsInGroup(
      m_session->contextGroupId());
  if (m_session->debuggerAgent() && !m_session->debuggerAgent()->enabled()) {
    m_session->debuggerAgent()->setAsyncCallStackDepth(0);
  }
  return Response::Success();
}
References v8_inspector::V8RuntimeAgentImplState::bindings, v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::debugger(), v8_inspector::V8InspectorSessionImpl::debuggerAgent(), v8_inspector::V8DebuggerAgentImpl::enabled(), v8_inspector::V8InspectorClient::endEnsureAllContextsInGroup(), m_enabled, m_inspector, m_session, m_state, reset(), v8_inspector::V8RuntimeAgentImplState::runtimeEnabled, v8_inspector::V8DebuggerAgentImpl::setAsyncCallStackDepth(), v8_inspector::V8InspectorSessionImpl::setCustomObjectFormatterEnabled(), v8_inspector::V8Debugger::setMaxCallStackSizeToCapture(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_FLAG_FLOW_IN, and TRACE_EVENT_WITH_FLOW0.
discardConsoleEntries()
Response v8_inspector::V8RuntimeAgentImpl::discardConsoleEntries () [override]
Definition at line 674 of file v8-runtime-agent-impl.cc.
                                                   {
  V8ConsoleMessageStorage* storage =
      m_inspector->ensureConsoleMessageStorage(m_session->contextGroupId());
  storage->clear();
  return Response::Success();
}
References v8_inspector::V8ConsoleMessageStorage::clear(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::ensureConsoleMessageStorage(), m_inspector, and m_session.
enable()
Response v8_inspector::V8RuntimeAgentImpl::enable () [override]
Definition at line 1082 of file v8-runtime-agent-impl.cc.
                                    {
  if (m_enabled) return Response::Success();
  TRACE_EVENT_WITH_FLOW0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                         "V8RuntimeAgentImpl::enable", this,
                         TRACE_EVENT_FLAG_FLOW_OUT);
  m_inspector->client()->beginEnsureAllContextsInGroup(
      m_session->contextGroupId());
  m_enabled = true;
  m_state->setBoolean(V8RuntimeAgentImplState::runtimeEnabled, true);
  m_inspector->debugger()->setMaxCallStackSizeToCapture(
      this, V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture);
  m_session->reportAllContexts(this);
  V8ConsoleMessageStorage* storage =
      m_inspector->ensureConsoleMessageStorage(m_session->contextGroupId());
  for (const auto& message : storage->messages()) {
    if (!reportMessage(message.get(), false)) break;
  }
  return Response::Success();
}
References v8_inspector::V8InspectorClient::beginEnsureAllContextsInGroup(), v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::debugger(), v8_inspector::V8InspectorImpl::ensureConsoleMessageStorage(), v8_inspector::V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture, m_enabled, m_inspector, m_session, m_state, v8_inspector::V8ConsoleMessageStorage::messages(), v8_inspector::V8InspectorSessionImpl::reportAllContexts(), reportMessage(), v8_inspector::V8RuntimeAgentImplState::runtimeEnabled, v8_inspector::V8Debugger::setMaxCallStackSizeToCapture(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_FLAG_FLOW_OUT, and TRACE_EVENT_WITH_FLOW0.
Referenced by restore().
enabled()
bool v8_inspector::V8RuntimeAgentImpl::enabled () const [inline]
Definition at line 163 of file v8-runtime-agent-impl.h.
{ return m_enabled; }
References m_enabled.
Referenced by v8_inspector::V8Debugger::captureStackTrace(), v8_inspector::V8DebuggerAgentImpl::setAsyncCallStackDepth(), and setCustomObjectFormatterEnabled().
evaluate()
void v8_inspector::V8RuntimeAgentImpl::evaluate (const String16 & expression, std::optional< String16 > objectGroup, std::optional< bool > includeCommandLineAPI, std::optional< bool > silent, std::optional< int > executionContextId, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::optional< bool > userGesture, std::optional< bool > awaitPromise, std::optional< bool > throwOnSideEffect, std::optional< double > timeout, std::optional< bool > disableBreaks, std::optional< bool > replMode, std::optional< bool > allowUnsafeEvalBlockedByCSP, std::optional< String16 > uniqueContextId, std::unique_ptr< protocol::Runtime::SerializationOptions > serializationOptions, std::unique_ptr< EvaluateCallback > callback) [override]
Definition at line 354 of file v8-runtime-agent-impl.cc.
                                              {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("devtools.timeline"),
               "EvaluateScript");
  int contextId = 0;
  Response response = ensureContext(m_inspector, m_session->contextGroupId(),
                                    std::move(executionContextId),
                                    std::move(uniqueContextId), &contextId);
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  InjectedScript::ContextScope scope(m_session, contextId);
  response = scope.initialize();
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  if (silent.value_or(false)) scope.ignoreExceptionsAndMuteConsole();
  if (userGesture.value_or(false)) scope.pretendUserGesture();
  if (includeCommandLineAPI.value_or(false)) scope.installCommandLineAPI();
  const bool replMode = maybeReplMode.value_or(false);
  if (allowUnsafeEvalBlockedByCSP.value_or(true)) {
    // Temporarily enable allow evals for inspector.
    scope.allowCodeGenerationFromStrings();
  }
  v8::MaybeLocal<v8::Value> maybeResultValue;
  {
    V8InspectorImpl::EvaluateScope evaluateScope(scope);
    if (timeout.has_value()) {
      response = evaluateScope.setTimeout(timeout.value() / 1000.0);
      if (!response.IsSuccess()) {
        callback->sendFailure(response);
        return;
      }
    }
    v8::MicrotasksScope microtasksScope(scope.context(),
                                        v8::MicrotasksScope::kRunMicrotasks);
    v8::debug::EvaluateGlobalMode mode =
        v8::debug::EvaluateGlobalMode::kDefault;
    if (throwOnSideEffect.value_or(false)) {
      mode = v8::debug::EvaluateGlobalMode::kDisableBreaksAndThrowOnSideEffect;
    } else if (disableBreaks.value_or(false)) {
      mode = v8::debug::EvaluateGlobalMode::kDisableBreaks;
    }
    const v8::Local<v8::String> source =
        toV8String(m_inspector->isolate(), expression);
    maybeResultValue = v8::debug::EvaluateGlobal(m_inspector->isolate(), source,
                                                 mode, replMode);
  } // Run microtasks before returning result.
  // Re-initialize after running client's code, as it could have destroyed
  // context or session.
  response = scope.initialize();
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  std::unique_ptr<WrapOptions> wrapOptions;
  response = getWrapOptions(
      std::move(returnByValue), std::move(generatePreview),
      std::move(serializationOptions), m_inspector->isolate(), &wrapOptions);
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  // REPL mode always returns a promise that must be awaited.
  const bool await = replMode || maybeAwaitPromise.value_or(false);
  if (!await || scope.tryCatch().HasCaught()) {
    wrapEvaluateResultAsync(scope.injectedScript(), maybeResultValue,
                            scope.tryCatch(), objectGroup.value_or(""),
                            *wrapOptions, throwOnSideEffect.value_or(false),
                            callback.get());
    return;
  }
  scope.injectedScript()->addPromiseCallback(
      m_session, maybeResultValue, objectGroup.value_or(""),
      std::move(wrapOptions), replMode, throwOnSideEffect.value_or(false),
      EvaluateCallbackWrapper<EvaluateCallback>::wrap(std::move(callback)));
}
References v8_inspector::InjectedScript::addPromiseCallback(), v8_inspector::InjectedScript::Scope::allowCodeGenerationFromStrings(), v8_inspector::InjectedScript::Scope::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8::debug::EvaluateGlobal(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getWrapOptions(), v8::TryCatch::HasCaught(), v8_inspector::InjectedScript::Scope::ignoreExceptionsAndMuteConsole(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::InjectedScript::Scope::installCommandLineAPI(), v8_inspector::V8InspectorImpl::isolate(), v8::debug::kDefault, v8::debug::kDisableBreaks, v8::debug::kDisableBreaksAndThrowOnSideEffect, v8::MicrotasksScope::kRunMicrotasks, m_inspector, m_session, mode(), v8_inspector::InjectedScript::Scope::pretendUserGesture(), v8_inspector::V8InspectorImpl::EvaluateScope::setTimeout(), v8_inspector::toV8String(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8_inspector::InjectedScript::Scope::tryCatch(), and v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::wrapEvaluateResultAsync().
getExceptionDetails()
Response v8_inspector::V8RuntimeAgentImpl::getExceptionDetails (const String16 & errorObjectId, std::unique_ptr< protocol::Runtime::ExceptionDetails > * out_exceptionDetails) [override]
Definition at line 998 of file v8-runtime-agent-impl.cc.
                              {
  InjectedScript::ObjectScope scope(m_session, errorObjectId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  const v8::Local<v8::Value> error = scope.object();
  if (!error->IsNativeError())
    return Response::ServerError("errorObjectId is not a JS error object");
  const v8::Local<v8::Message> message =
      v8::debug::CreateMessageFromException(m_inspector->isolate(), error);
  response = scope.injectedScript()->createExceptionDetails(
      message, error, scope.objectGroupName(), out_exceptionDetails);
  if (!response.IsSuccess()) return response;
  CHECK(*out_exceptionDetails);
  // When an exception object is present, `createExceptionDetails` assumes
  // the exception is uncaught and will overwrite the text field to "Uncaught".
  // Lets use the normal message text instead.
  (*out_exceptionDetails)
      ->setText(toProtocolString(m_inspector->isolate(), message->Get()));
  // Check if the exception has any metadata on the inspector and also attach
  // it.
  std::unique_ptr<protocol::DictionaryValue> data =
      m_inspector->getAssociatedExceptionDataForProtocol(error);
  if (data) {
    (*out_exceptionDetails)->setExceptionMetaData(std::move(data));
  }
  return Response::Success();
}
References CHECK, v8_inspector::InjectedScript::createExceptionDetails(), v8::debug::CreateMessageFromException(), v8_inspector::V8InspectorImpl::getAssociatedExceptionDataForProtocol(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8::Value::IsNativeError(), v8_inspector::V8InspectorImpl::isolate(), m_inspector, m_session, v8_inspector::InjectedScript::ObjectScope::object(), v8_inspector::InjectedScript::ObjectScope::objectGroupName(), and v8_inspector::toProtocolString().
getHeapUsage()
Response v8_inspector::V8RuntimeAgentImpl::getHeapUsage (double * out_usedSize, double * out_totalSize, double * out_embedderHeapUsedSize, double * out_backingStorageSize) [override]
Definition at line 854 of file v8-runtime-agent-impl.cc.
                                                                          {
  v8::HeapStatistics stats;
  m_inspector->isolate()->GetHeapStatistics(&stats);
  *out_usedSize = stats.used_heap_size();
  *out_totalSize = stats.total_heap_size();
  *out_backingStorageSize = stats.external_memory();
  if (v8::CppHeap* cppHeap = m_inspector->isolate()->GetCppHeap()) {
    cppgc::HeapStatistics cppStats =
        cppHeap->CollectStatistics(cppgc::HeapStatistics::DetailLevel::kBrief);
    *out_embedderHeapUsedSize = cppStats.used_size_bytes;
  } else {
    *out_embedderHeapUsedSize = 0;
  }
  return Response::Success();
}
References v8::HeapStatistics::external_memory(), v8::Isolate::GetCppHeap(), v8::Isolate::GetHeapStatistics(), v8_inspector::V8InspectorImpl::isolate(), m_inspector, v8::HeapStatistics::total_heap_size(), v8::HeapStatistics::used_heap_size(), and cppgc::HeapStatistics::used_size_bytes.
getIsolateId()
Response v8_inspector::V8RuntimeAgentImpl::getIsolateId (String16 * outIsolateId) [override]
Definition at line 847 of file v8-runtime-agent-impl.cc.
                                                                {
  char buf[40];
  std::snprintf(buf, sizeof(buf), "%" PRIx64, m_inspector->isolateId());
  *outIsolateId = buf;
  return Response::Success();
}
References v8_inspector::V8InspectorImpl::isolateId(), and m_inspector.
getProperties()
Response v8_inspector::V8RuntimeAgentImpl::getProperties (const String16 & objectId, std::optional< bool > ownProperties, std::optional< bool > accessorPropertiesOnly, std::optional< bool > generatePreview, std::optional< bool > nonIndexedPropertiesOnly, std::unique_ptr< protocol::Array< protocol::Runtime::PropertyDescriptor >> * result, std::unique_ptr< protocol::Array< protocol::Runtime::InternalPropertyDescriptor >> * internalProperties, std::unique_ptr< protocol::Array< protocol::Runtime::PrivatePropertyDescriptor >> * privateProperties, std::unique_ptr< protocol::Runtime::ExceptionDetails > * exceptionDetails) [override]
Definition at line 569 of file v8-runtime-agent-impl.cc.
                                                                      {
  using protocol::Runtime::InternalPropertyDescriptor;
  using protocol::Runtime::PrivatePropertyDescriptor;
  InjectedScript::ObjectScope scope(m_session, objectId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  scope.ignoreExceptionsAndMuteConsole();
  v8::MicrotasksScope microtasks_scope(scope.context(),
                                       v8::MicrotasksScope::kRunMicrotasks);
  if (!scope.object()->IsObject())
    return Response::ServerError("Value with given id is not an object");
  v8::Local<v8::Object> object = scope.object().As<v8::Object>();
  std::unique_ptr<WrapOptions> wrapOptions;
  response =
      getWrapOptions(false /* returnByValue */, std::move(generatePreview),
                     m_inspector->isolate(), &wrapOptions);
  if (!response.IsSuccess()) return response;
  response = scope.injectedScript()->getProperties(
      object, scope.objectGroupName(), ownProperties.value_or(false),
      accessorPropertiesOnly.value_or(false),
      nonIndexedPropertiesOnly.value_or(false), *wrapOptions, result,
      exceptionDetails);
  if (!response.IsSuccess()) return response;
  if (*exceptionDetails) return Response::Success();
  std::unique_ptr<protocol::Array<InternalPropertyDescriptor>>
      internalPropertiesProtocolArray;
  std::unique_ptr<protocol::Array<PrivatePropertyDescriptor>>
      privatePropertiesProtocolArray;
  response = scope.injectedScript()->getInternalAndPrivateProperties(
      object, scope.objectGroupName(), accessorPropertiesOnly.value_or(false),
      &internalPropertiesProtocolArray, &privatePropertiesProtocolArray);
  if (!response.IsSuccess()) return response;
  if (!internalPropertiesProtocolArray->empty())
    *internalProperties = std::move(internalPropertiesProtocolArray);
  if (!privatePropertiesProtocolArray->empty())
    *privateProperties = std::move(privatePropertiesProtocolArray);
  return Response::Success();
}
References v8::Local< T >::As(), v8_inspector::InjectedScript::Scope::context(), v8_inspector::InjectedScript::getInternalAndPrivateProperties(), v8_inspector::InjectedScript::getProperties(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getWrapOptions(), v8_inspector::InjectedScript::Scope::ignoreExceptionsAndMuteConsole(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8::Value::IsObject(), v8_inspector::V8InspectorImpl::isolate(), v8::MicrotasksScope::kRunMicrotasks, m_inspector, m_session, v8_inspector::InjectedScript::ObjectScope::object(), v8_inspector::InjectedScript::ObjectScope::objectGroupName(), and v8::base::internal::result.
globalLexicalScopeNames()
Response v8_inspector::V8RuntimeAgentImpl::globalLexicalScopeNames (std::optional< int > executionContextId, std::unique_ptr< protocol::Array< String16 >> * outNames) [override]
Definition at line 824 of file v8-runtime-agent-impl.cc.
                                                      {
  int contextId = 0;
  Response response = ensureContext(m_inspector, m_session->contextGroupId(),
                                    std::move(executionContextId),
                                    /*uniqueContextId*/ {}, &contextId);
  if (!response.IsSuccess()) return response;
  InjectedScript::ContextScope scope(m_session, contextId);
  response = scope.initialize();
  if (!response.IsSuccess()) return response;
  std::vector<v8::Global<v8::String>> names;
  v8::debug::GlobalLexicalScopeNames(scope.context(), &names);
  *outNames = std::make_unique<protocol::Array<String16>>();
  for (size_t i = 0; i < names.size(); ++i) {
    (*outNames)->emplace_back(toProtocolString(
        m_inspector->isolate(), names[i].Get(m_inspector->isolate())));
  }
  return Response::Success();
}
References v8_inspector::InjectedScript::Scope::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8::debug::GlobalLexicalScopeNames(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::V8InspectorImpl::isolate(), m_inspector, m_session, and v8_inspector::toProtocolString().
inspect()
void v8_inspector::V8RuntimeAgentImpl::inspect (std::unique_ptr< protocol::Runtime::RemoteObject > objectToInspect, std::unique_ptr< protocol::DictionaryValue > hints, int executionContextId)
Definition at line 1164 of file v8-runtime-agent-impl.cc.
                                                                          {
  if (m_enabled)
    m_frontend.inspectRequested(std::move(objectToInspect), std::move(hints),
                                executionContextId);
}
References m_enabled, and m_frontend.
messageAdded()
void v8_inspector::V8RuntimeAgentImpl::messageAdded (V8ConsoleMessage * message)
Definition at line 1172 of file v8-runtime-agent-impl.cc.
                                                               {
  if (m_enabled) reportMessage(message, true);
}
References m_enabled, and reportMessage().
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage().
operator=()
V8RuntimeAgentImpl& v8_inspector::V8RuntimeAgentImpl::operator= (const V8RuntimeAgentImpl &) [delete]
queryObjects()
Response v8_inspector::V8RuntimeAgentImpl::queryObjects (const String16 & prototypeObjectId, std::optional< String16 > objectGroup, std::unique_ptr< protocol::Runtime::RemoteObject > * objects) [override]
Definition at line 808 of file v8-runtime-agent-impl.cc.
                                                         {
  InjectedScript::ObjectScope scope(m_session, prototypeObjectId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  if (!scope.object()->IsObject()) {
    return Response::ServerError("Prototype should be instance of Object");
  }
  v8::Local<v8::Array> resultArray = m_inspector->debugger()->queryObjects(
      scope.context(), scope.object().As<v8::Object>());
  return scope.injectedScript()->wrapObject(
      resultArray, objectGroup.value_or(scope.objectGroupName()),
      WrapOptions({WrapMode::kIdOnly}), objects);
}
References v8::Local< T >::As(), v8_inspector::InjectedScript::Scope::context(), v8_inspector::V8InspectorImpl::debugger(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8::Value::IsObject(), v8_inspector::kIdOnly, m_inspector, m_session, v8_inspector::InjectedScript::ObjectScope::object(), v8_inspector::InjectedScript::ObjectScope::objectGroupName(), v8_inspector::V8Debugger::queryObjects(), and v8_inspector::InjectedScript::wrapObject().
releaseObject()
Response v8_inspector::V8RuntimeAgentImpl::releaseObject (const String16 & objectId) [override]
Definition at line 626 of file v8-runtime-agent-impl.cc.
                                                                   {
  InjectedScript::ObjectScope scope(m_session, objectId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  scope.injectedScript()->releaseObject(objectId);
  return Response::Success();
}
References v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), m_session, and v8_inspector::InjectedScript::releaseObject().
releaseObjectGroup()
Response v8_inspector::V8RuntimeAgentImpl::releaseObjectGroup (const String16 & objectGroup) [override]
Definition at line 634 of file v8-runtime-agent-impl.cc.
                                                                           {
  m_session->releaseObjectGroup(objectGroup);
  return Response::Success();
}
References m_session, and v8_inspector::V8InspectorSessionImpl::releaseObjectGroup().
removeBinding()
Response v8_inspector::V8RuntimeAgentImpl::removeBinding (const String16 & name) [override]
Definition at line 990 of file v8-runtime-agent-impl.cc.
                                                               {
  protocol::DictionaryValue* bindings =
      m_state->getObject(V8RuntimeAgentImplState::bindings);
  if (bindings) bindings->remove(name);
  m_activeBindings.erase(name);
  return Response::Success();
}
References v8_inspector::V8RuntimeAgentImplState::bindings, m_activeBindings, m_state, and name.
reportExecutionContextCreated()
void v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated (InspectedContext * context)
Definition at line 1133 of file v8-runtime-agent-impl.cc.
                               {
  if (!m_enabled) return;
  context->setReported(m_session->sessionId(), true);
  std::unique_ptr<protocol::Runtime::ExecutionContextDescription> description =
      protocol::Runtime::ExecutionContextDescription::create()
          .setId(context->contextId())
          .setName(context->humanReadableName())
          .setOrigin(context->origin())
          .setUniqueId(context->uniqueId().toString())
          .build();
  const String16& aux = context->auxData();
  if (!aux.isEmpty()) {
    std::vector<uint8_t> cbor;
    v8_crdtp::json::ConvertJSONToCBOR(
        v8_crdtp::span<uint16_t>(aux.characters16(), aux.length()), &cbor);
    description->setAuxData(protocol::DictionaryValue::cast(
        protocol::Value::parseBinary(cbor.data(), cbor.size())));
  }
  m_frontend.executionContextCreated(std::move(description));
}
References v8_inspector::InspectedContext::auxData(), v8_inspector::String16::characters16(), v8_inspector::InspectedContext::contextId(), v8_inspector::InspectedContext::humanReadableName(), v8_inspector::String16::isEmpty(), v8_inspector::String16::length(), m_enabled, m_frontend, m_session, v8_inspector::InspectedContext::origin(), v8_inspector::V8InspectorSessionImpl::sessionId(), v8_inspector::InspectedContext::setReported(), v8_inspector::internal::V8DebuggerId::toString(), and v8_inspector::InspectedContext::uniqueId().
Referenced by v8_inspector::V8InspectorSessionImpl::reportAllContexts().
reportExecutionContextDestroyed()
void v8_inspector::V8RuntimeAgentImpl::reportExecutionContextDestroyed (InspectedContext * context)
Definition at line 1155 of file v8-runtime-agent-impl.cc.
                               {
  if (m_enabled && context->isReported(m_session->sessionId())) {
    context->setReported(m_session->sessionId(), false);
    m_frontend.executionContextDestroyed(context->contextId(),
                                         context->uniqueId().toString());
  }
}
References v8_inspector::InspectedContext::contextId(), v8_inspector::InspectedContext::isReported(), m_enabled, m_frontend, m_session, v8_inspector::V8InspectorSessionImpl::sessionId(), v8_inspector::InspectedContext::setReported(), v8_inspector::internal::V8DebuggerId::toString(), and v8_inspector::InspectedContext::uniqueId().
reportMessage()
bool v8_inspector::V8RuntimeAgentImpl::reportMessage (V8ConsoleMessage * message, bool generatePreview) [private]
Definition at line 1176 of file v8-runtime-agent-impl.cc.
                                                             {
  message->reportToFrontend(&m_frontend, m_session, generatePreview);
  m_frontend.flush();
  return m_inspector->hasConsoleMessageStorage(m_session->contextGroupId());
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::hasConsoleMessageStorage(), m_frontend, m_inspector, m_session, and v8_inspector::V8ConsoleMessage::reportToFrontend().
Referenced by enable(), and messageAdded().
reset()
void v8_inspector::V8RuntimeAgentImpl::reset ()
Definition at line 1121 of file v8-runtime-agent-impl.cc.
                               {
  m_compiledScripts.clear();
  if (m_enabled) {
    int sessionId = m_session->sessionId();
    m_inspector->forEachContext(m_session->contextGroupId(),
                                [&sessionId](InspectedContext* context) {
                                  context->setReported(sessionId, false);
                                });
    m_frontend.executionContextsCleared();
  }
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::forEachContext(), m_compiledScripts, m_enabled, m_frontend, m_inspector, m_session, and v8_inspector::V8InspectorSessionImpl::sessionId().
Referenced by disable().
restore()
void v8_inspector::V8RuntimeAgentImpl::restore ()
Definition at line 1063 of file v8-runtime-agent-impl.cc.
                                 {
  if (!m_state->booleanProperty(V8RuntimeAgentImplState::runtimeEnabled, false))
    return;
  m_frontend.executionContextsCleared();
  enable();
  if (m_state->booleanProperty(
          V8RuntimeAgentImplState::customObjectFormatterEnabled, false))
    m_session->setCustomObjectFormatterEnabled(true);
  int size;
  if (m_state->getInteger(V8RuntimeAgentImplState::maxCallStackSizeToCapture,
                          &size))
    m_inspector->debugger()->setMaxCallStackSizeToCapture(this, size);
  m_inspector->forEachContext(
      m_session->contextGroupId(),
      [this](InspectedContext* context) { addBindings(context); });
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8RuntimeAgentImplState::customObjectFormatterEnabled, v8_inspector::V8InspectorImpl::debugger(), enable(), v8_inspector::V8InspectorImpl::forEachContext(), m_frontend, m_inspector, m_session, m_state, v8_inspector::V8RuntimeAgentImplState::maxCallStackSizeToCapture, v8_inspector::V8RuntimeAgentImplState::runtimeEnabled, v8_inspector::V8InspectorSessionImpl::setCustomObjectFormatterEnabled(), v8_inspector::V8Debugger::setMaxCallStackSizeToCapture(), and size().
runIfWaitingForDebugger()
Response v8_inspector::V8RuntimeAgentImpl::runIfWaitingForDebugger () [override]
Definition at line 639 of file v8-runtime-agent-impl.cc.
                                                     {
  if (m_debuggerBarrier) {
    m_debuggerBarrier.reset();
    return Response::Success();
  }
  // TODO(chromium:1352175): the below is provisional until client-side changes
  // land. The call should come through the barrier only once client properly
  // communicates whether the session is waiting for debugger.
  m_inspector->client()->runIfWaitingForDebugger(m_session->contextGroupId());
  return Response::Success();
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), m_debuggerBarrier, m_inspector, m_session, and v8_inspector::V8InspectorClient::runIfWaitingForDebugger().
runScript()
void v8_inspector::V8RuntimeAgentImpl::runScript (const String16 & scriptId, std::optional< int > executionContextId, std::optional< String16 > objectGroup, std::optional< bool > silent, std::optional< bool > includeCommandLineAPI, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::optional< bool > awaitPromise, std::unique_ptr< RunScriptCallback > callback) [override]
Definition at line 723 of file v8-runtime-agent-impl.cc.
                                               {
  if (!m_enabled) {
    callback->sendFailure(
        Response::ServerError("Runtime agent is not enabled"));
    return;
  }
  auto it = m_compiledScripts.find(scriptId);
  if (it == m_compiledScripts.end()) {
    callback->sendFailure(Response::ServerError("No script with given id"));
    return;
  }
  int contextId = 0;
  Response response = ensureContext(m_inspector, m_session->contextGroupId(),
                                    std::move(executionContextId),
                                    /*uniqueContextId*/ {}, &contextId);
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  InjectedScript::ContextScope scope(m_session, contextId);
  response = scope.initialize();
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  if (silent.value_or(false)) scope.ignoreExceptionsAndMuteConsole();
  std::unique_ptr<v8::Global<v8::Script>> scriptWrapper = std::move(it->second);
  m_compiledScripts.erase(it);
  v8::Local<v8::Script> script = scriptWrapper->Get(m_inspector->isolate());
  if (script.IsEmpty()) {
    callback->sendFailure(Response::ServerError("Script execution failed"));
    return;
  }
  if (includeCommandLineAPI.value_or(false)) scope.installCommandLineAPI();
  v8::MaybeLocal<v8::Value> maybeResultValue;
  {
    v8::MicrotasksScope microtasksScope(scope.context(),
                                        v8::MicrotasksScope::kRunMicrotasks);
    maybeResultValue = script->Run(scope.context());
  }
  // Re-initialize after running client's code, as it could have destroyed
  // context or session.
  response = scope.initialize();
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  std::unique_ptr<WrapOptions> wrapOptions;
  response =
      getWrapOptions(std::move(returnByValue), std::move(generatePreview),
                     m_inspector->isolate(), &wrapOptions);
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  if (!awaitPromise.value_or(false) || scope.tryCatch().HasCaught()) {
    wrapEvaluateResultAsync(scope.injectedScript(), maybeResultValue,
                            scope.tryCatch(), objectGroup.value_or(""),
                            *wrapOptions, false /* throwOnSideEffect */,
                            callback.get());
    return;
  }
  scope.injectedScript()->addPromiseCallback(
      m_session, maybeResultValue.ToLocalChecked(), objectGroup.value_or(""),
      std::move(wrapOptions), false /* replMode */,
      false /* throwOnSideEffect */,
      EvaluateCallbackWrapper<RunScriptCallback>::wrap(std::move(callback)));
}
References v8_inspector::InjectedScript::addPromiseCallback(), awaitPromise(), v8_inspector::InjectedScript::Scope::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getWrapOptions(), v8::TryCatch::HasCaught(), v8_inspector::InjectedScript::Scope::ignoreExceptionsAndMuteConsole(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::InjectedScript::Scope::installCommandLineAPI(), v8_inspector::V8InspectorImpl::isolate(), v8::MicrotasksScope::kRunMicrotasks, m_compiledScripts, m_enabled, m_inspector, m_session, v8::internal::script, v8::MaybeLocal< T >::ToLocalChecked(), v8_inspector::InjectedScript::Scope::tryCatch(), and v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::wrapEvaluateResultAsync().
setCustomObjectFormatterEnabled()
Response v8_inspector::V8RuntimeAgentImpl::setCustomObjectFormatterEnabled (bool enabled) [override]
Definition at line 651 of file v8-runtime-agent-impl.cc.
                                                                         {
  m_state->setBoolean(V8RuntimeAgentImplState::customObjectFormatterEnabled,
                      enabled);
  if (!m_enabled) return Response::ServerError("Runtime agent is not enabled");
  m_session->setCustomObjectFormatterEnabled(enabled);
  return Response::Success();
}
References v8_inspector::V8RuntimeAgentImplState::customObjectFormatterEnabled, enabled(), m_enabled, m_session, m_state, and v8_inspector::V8InspectorSessionImpl::setCustomObjectFormatterEnabled().
setMaxCallStackSizeToCapture()
Response v8_inspector::V8RuntimeAgentImpl::setMaxCallStackSizeToCapture (int size) [override]
Definition at line 659 of file v8-runtime-agent-impl.cc.
                                                                  {
  if (size < 0) {
    return Response::ServerError(
        "maxCallStackSizeToCapture should be non-negative");
  }
  TRACE_EVENT_WITH_FLOW1(
      TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
      "V8RuntimeAgentImpl::setMaxCallStackSizeToCapture", this,
      TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT, "size", size);
  if (!m_enabled) return Response::ServerError("Runtime agent is not enabled");
  m_state->setInteger(V8RuntimeAgentImplState::maxCallStackSizeToCapture, size);
  m_inspector->debugger()->setMaxCallStackSizeToCapture(this, size);
  return Response::Success();
}
References v8_inspector::V8InspectorImpl::debugger(), m_enabled, m_inspector, m_state, v8_inspector::V8RuntimeAgentImplState::maxCallStackSizeToCapture, v8_inspector::V8Debugger::setMaxCallStackSizeToCapture(), size(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, and TRACE_EVENT_WITH_FLOW1.
terminateExecution()
void v8_inspector::V8RuntimeAgentImpl::terminateExecution (std::unique_ptr< TerminateExecutionCallback > callback) [override]
Definition at line 873 of file v8-runtime-agent-impl.cc.
                                                        {
  v8::HandleScope handles(m_inspector->isolate());
  v8::Local<v8::Context> defaultContext =
      m_inspector->client()->ensureDefaultContextInGroup(
          m_session->contextGroupId());
  m_inspector->debugger()->terminateExecution(defaultContext,
                                              std::move(callback));
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::debugger(), v8_inspector::V8InspectorClient::ensureDefaultContextInGroup(), v8_inspector::V8InspectorImpl::isolate(), m_inspector, m_session, and v8_inspector::V8Debugger::terminateExecution().
Member Data Documentation
m_activeBindings
std::unordered_map<String16, std::unordered_set<int> > v8_inspector::V8RuntimeAgentImpl::m_activeBindings [private]
Definition at line 182 of file v8-runtime-agent-impl.h.
Referenced by addBinding(), bindingCalled(), and removeBinding().
m_compiledScripts
std::unordered_map<String16, std::unique_ptr<v8::Global<v8::Script> > > v8_inspector::V8RuntimeAgentImpl::m_compiledScripts [private]
Definition at line 180 of file v8-runtime-agent-impl.h.
Referenced by compileScript(), reset(), and runScript().
m_debuggerBarrier
std::shared_ptr<V8DebuggerBarrier> v8_inspector::V8RuntimeAgentImpl::m_debuggerBarrier [private]
Definition at line 177 of file v8-runtime-agent-impl.h.
Referenced by runIfWaitingForDebugger().
m_enabled
bool v8_inspector::V8RuntimeAgentImpl::m_enabled [private]
Definition at line 178 of file v8-runtime-agent-impl.h.
Referenced by addBindings(), compileScript(), disable(), enable(), enabled(), inspect(), messageAdded(), reportExecutionContextCreated(), reportExecutionContextDestroyed(), reset(), runScript(), setCustomObjectFormatterEnabled(), and setMaxCallStackSizeToCapture().
m_frontend
protocol::Runtime::Frontend v8_inspector::V8RuntimeAgentImpl::m_frontend [private]
Definition at line 175 of file v8-runtime-agent-impl.h.
Referenced by bindingCalled(), inspect(), reportExecutionContextCreated(), reportExecutionContextDestroyed(), reportMessage(), reset(), and restore().
m_inspector
V8InspectorImpl* v8_inspector::V8RuntimeAgentImpl::m_inspector [private]
Definition at line 176 of file v8-runtime-agent-impl.h.
Referenced by addBinding(), awaitPromise(), callFunctionOn(), compileScript(), disable(), discardConsoleEntries(), enable(), evaluate(), getExceptionDetails(), getHeapUsage(), getIsolateId(), getProperties(), globalLexicalScopeNames(), queryObjects(), reportMessage(), reset(), restore(), runIfWaitingForDebugger(), runScript(), setMaxCallStackSizeToCapture(), and terminateExecution().
m_session
V8InspectorSessionImpl* v8_inspector::V8RuntimeAgentImpl::m_session [private]
Definition at line 173 of file v8-runtime-agent-impl.h.
Referenced by addBinding(), awaitPromise(), callFunctionOn(), compileScript(), disable(), discardConsoleEntries(), enable(), evaluate(), getExceptionDetails(), getProperties(), globalLexicalScopeNames(), queryObjects(), releaseObject(), releaseObjectGroup(), reportExecutionContextCreated(), reportExecutionContextDestroyed(), reportMessage(), reset(), restore(), runIfWaitingForDebugger(), runScript(), setCustomObjectFormatterEnabled(), and terminateExecution().
m_state
protocol::DictionaryValue* v8_inspector::V8RuntimeAgentImpl::m_state [private]
Definition at line 174 of file v8-runtime-agent-impl.h.
Referenced by addBinding(), addBindings(), disable(), enable(), removeBinding(), restore(), setCustomObjectFormatterEnabled(), and setMaxCallStackSizeToCapture().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-runtime-agent-impl.h
/mnt/V8SourceCode/src/inspector/v8-runtime-agent-impl.cc