v8::internal::OutputStreamWriter Class Reference
#include <output-stream-writer.h>
Public Member Functions
OutputStreamWriter (v8::OutputStream *stream)
bool aborted ()
void AddCharacter (char c)
void AddString (const char *s)
template<typename T >
void AddNumber (T n)
void Finalize ()
Private Member Functions
void MaybeWriteChunk ()
void WriteChunk ()
Private Attributes
v8::OutputStream * stream_
int chunk_size_
base::ScopedVector< char > chunk_
int chunk_pos_
bool aborted_
Detailed Description
Definition at line 22 of file output-stream-writer.h.
Constructor & Destructor Documentation
OutputStreamWriter()
v8::internal::OutputStreamWriter::OutputStreamWriter (v8::OutputStream * stream) [inline], [explicit]
Definition at line 24 of file output-stream-writer.h.
      : stream_(stream),
        chunk_size_(stream->GetChunkSize()),
        chunk_(chunk_size_),
        chunk_pos_(0),
        aborted_(false) {
    DCHECK_GT(chunk_size_, 0);
  }
References chunk_size_, and DCHECK_GT.
Member Function Documentation
aborted()
bool v8::internal::OutputStreamWriter::aborted () [inline]
Definition at line 32 of file output-stream-writer.h.
{ return aborted_; }
References aborted_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeEdges(), v8::internal::HeapSnapshotJSONSerializer::SerializeImpl(), v8::internal::CpuProfileJSONSerializer::SerializeImpl(), v8::internal::HeapSnapshotJSONSerializer::SerializeLocations(), v8::internal::HeapSnapshotJSONSerializer::SerializeNodes(), v8::internal::CpuProfileJSONSerializer::SerializeNodes(), and v8::internal::HeapSnapshotJSONSerializer::SerializeStrings().
AddCharacter()
void v8::internal::OutputStreamWriter::AddCharacter (char c) [inline]
Definition at line 33 of file output-stream-writer.h.
                            {
    DCHECK_NE(c, '\0');
    DCHECK(chunk_pos_ < chunk_size_);
    chunk_[chunk_pos_++] = c;
    MaybeWriteChunk();
  }
References chunk_, chunk_pos_, chunk_size_, v8::internal::DCHECK(), DCHECK_NE, and MaybeWriteChunk().
Referenced by v8::internal::CpuProfileJSONSerializer::SerializeCallFrame(), v8::internal::CpuProfileJSONSerializer::SerializeChildren(), v8::internal::HeapSnapshotJSONSerializer::SerializeEdge(), v8::internal::HeapSnapshotJSONSerializer::SerializeImpl(), v8::internal::CpuProfileJSONSerializer::SerializeImpl(), v8::internal::HeapSnapshotJSONSerializer::SerializeLocation(), v8::internal::HeapSnapshotJSONSerializer::SerializeLocations(), v8::internal::HeapSnapshotJSONSerializer::SerializeNode(), v8::internal::CpuProfileJSONSerializer::SerializeNode(), v8::internal::CpuProfileJSONSerializer::SerializeNodes(), v8::internal::CpuProfileJSONSerializer::SerializePositionTicks(), v8::internal::HeapSnapshotJSONSerializer::SerializeSamples(), v8::internal::HeapSnapshotJSONSerializer::SerializeString(), v8::internal::HeapSnapshotJSONSerializer::SerializeStrings(), v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNode(), v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNodeInfos(), and v8::internal::WriteUChar().
AddNumber()
template<typename T >
void v8::internal::OutputStreamWriter::AddNumber (T n) [inline]
Definition at line 54 of file output-stream-writer.h.
                      {
    std::to_chars_result result =
        std::to_chars(chunk_.begin() + chunk_pos_, chunk_.end(), n);
    if (V8_LIKELY(result.ec == std::errc{})) {
      chunk_pos_ = static_cast<int>(result.ptr - chunk_.begin());
      MaybeWriteChunk();
    } else {
      // Expected to be the only possible reason for `to_chars` to fail.
      CHECK(result.ec == std::errc::value_too_large);
      // Write the current chunk and try again if we haven't already.
      CHECK_WITH_MSG(chunk_pos_ > 0,
                     "Chunk size insufficient to serialize number");
      WriteChunk();
      AddNumber(n);
    }
  }
References v8::base::Vector< T >::begin(), CHECK, CHECK_WITH_MSG, chunk_, chunk_pos_, v8::base::Vector< T >::end(), MaybeWriteChunk(), v8::base::internal::result, V8_LIKELY, and WriteChunk().
Referenced by v8::internal::CpuProfileJSONSerializer::SerializeCallFrame(), v8::internal::CpuProfileJSONSerializer::SerializeChildren(), v8::internal::HeapSnapshotJSONSerializer::SerializeEdge(), v8::internal::CpuProfileJSONSerializer::SerializeImpl(), v8::internal::HeapSnapshotJSONSerializer::SerializeLocation(), v8::internal::HeapSnapshotJSONSerializer::SerializeNode(), v8::internal::CpuProfileJSONSerializer::SerializeNode(), v8::internal::CpuProfileJSONSerializer::SerializePositionTicks(), v8::internal::HeapSnapshotJSONSerializer::SerializeSamples(), v8::internal::CpuProfileJSONSerializer::SerializeSamples(), v8::internal::HeapSnapshotJSONSerializer::SerializeSnapshot(), v8::internal::CpuProfileJSONSerializer::SerializeTimeDeltas(), v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNode(), and v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNodeInfos().
AddString()
void v8::internal::OutputStreamWriter::AddString (const char * s) [inline]
Definition at line 39 of file output-stream-writer.h.
                                {
    size_t len = strlen(s);
    DCHECK_GE(kMaxInt, len);
    const char* s_end = s + len;
    while (s < s_end) {
      int s_chunk_size =
          std::min(chunk_size_ - chunk_pos_, static_cast<int>(s_end - s));
      DCHECK_GT(s_chunk_size, 0);
      MemCopy(chunk_.begin() + chunk_pos_, s, s_chunk_size);
      s += s_chunk_size;
      chunk_pos_ += s_chunk_size;
      MaybeWriteChunk();
    }
  }
References v8::base::Vector< T >::begin(), chunk_, chunk_pos_, chunk_size_, DCHECK_GE, DCHECK_GT, v8::internal::kMaxInt, MaybeWriteChunk(), and v8::internal::MemCopy().
Referenced by v8::internal::CpuProfileJSONSerializer::SerializeCallFrame(), v8::internal::HeapSnapshotJSONSerializer::SerializeImpl(), v8::internal::CpuProfileJSONSerializer::SerializeImpl(), v8::internal::CpuProfileJSONSerializer::SerializeNode(), v8::internal::CpuProfileJSONSerializer::SerializePositionTicks(), v8::internal::CpuProfileJSONSerializer::SerializeSamples(), v8::internal::HeapSnapshotJSONSerializer::SerializeSnapshot(), v8::internal::HeapSnapshotJSONSerializer::SerializeString(), v8::internal::HeapSnapshotJSONSerializer::SerializeStrings(), v8::internal::CpuProfileJSONSerializer::SerializeTimeDeltas(), and v8::internal::WriteUChar().
Finalize()
void v8::internal::OutputStreamWriter::Finalize () [inline]
Definition at line 70 of file output-stream-writer.h.
                  {
    if (aborted_) return;
    DCHECK(chunk_pos_ < chunk_size_);
    if (chunk_pos_ != 0) {
      WriteChunk();
    }
    stream_->EndOfStream();
  }
References aborted_, chunk_pos_, chunk_size_, v8::internal::DCHECK(), v8::OutputStream::EndOfStream(), stream_, and WriteChunk().
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeImpl(), and v8::internal::CpuProfileJSONSerializer::SerializeImpl().
MaybeWriteChunk()
void v8::internal::OutputStreamWriter::MaybeWriteChunk () [inline], [private]
Definition at line 80 of file output-stream-writer.h.
                         {
    DCHECK(chunk_pos_ <= chunk_size_);
    if (chunk_pos_ == chunk_size_) {
      WriteChunk();
    }
  }
References chunk_pos_, chunk_size_, v8::internal::DCHECK(), and WriteChunk().
Referenced by AddCharacter(), AddNumber(), and AddString().
WriteChunk()
void v8::internal::OutputStreamWriter::WriteChunk () [inline], [private]
Definition at line 86 of file output-stream-writer.h.
                    {
    if (aborted_) return;
    if (stream_->WriteAsciiChunk(chunk_.begin(), chunk_pos_) ==
        v8::OutputStream::kAbort)
      aborted_ = true;
    chunk_pos_ = 0;
  }
References aborted_, v8::base::Vector< T >::begin(), chunk_, chunk_pos_, v8::OutputStream::kAbort, stream_, and v8::OutputStream::WriteAsciiChunk().
Referenced by AddNumber(), Finalize(), and MaybeWriteChunk().
Member Data Documentation
aborted_
bool v8::internal::OutputStreamWriter::aborted_ [private]
Definition at line 98 of file output-stream-writer.h.
Referenced by aborted(), Finalize(), and WriteChunk().
chunk_
base::ScopedVector<char> v8::internal::OutputStreamWriter::chunk_ [private]
Definition at line 96 of file output-stream-writer.h.
Referenced by AddCharacter(), AddNumber(), AddString(), and WriteChunk().
chunk_pos_
int v8::internal::OutputStreamWriter::chunk_pos_ [private]
Definition at line 97 of file output-stream-writer.h.
Referenced by AddCharacter(), AddNumber(), AddString(), Finalize(), MaybeWriteChunk(), and WriteChunk().
chunk_size_
int v8::internal::OutputStreamWriter::chunk_size_ [private]
Definition at line 95 of file output-stream-writer.h.
Referenced by AddCharacter(), AddString(), Finalize(), MaybeWriteChunk(), and OutputStreamWriter().
stream_
v8::OutputStream* v8::internal::OutputStreamWriter::stream_ [private]
Definition at line 94 of file output-stream-writer.h.
Referenced by Finalize(), and WriteChunk().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/output-stream-writer.h