v8::internal::AllocationHint Class Reference
#include <globals.h>
Public Member Functions
AllocationHint ()=default
constexpr V8_WARN_UNUSED_RESULT AllocationHint WithMayGrow () const
bool MayGrow () const
Private Member Functions
constexpr AllocationHint (bool may_grow)
Private Attributes
bool may_grow_ = false
Detailed Description
Definition at line 1419 of file globals.h.
Constructor & Destructor Documentation
AllocationHint() [1/2]
v8::internal::AllocationHint::AllocationHint () [default]
Referenced by WithMayGrow().
AllocationHint() [2/2]
constexpr v8::internal::AllocationHint::AllocationHint (bool may_grow) [inline], [explicit], [constexpr], [private]
Definition at line 1430 of file globals.h.
: may_grow_(may_grow) {}
Member Function Documentation
MayGrow()
bool v8::internal::AllocationHint::MayGrow () const [inline]
Definition at line 1427 of file globals.h.
{ return may_grow_; }
References may_grow_.
Referenced by v8::internal::MemoryAllocator::AllocateAlignedMemory().
WithMayGrow()
constexpr V8_WARN_UNUSED_RESULT AllocationHint v8::internal::AllocationHint::WithMayGrow () const [inline], [constexpr]
Definition at line 1423 of file globals.h.
                                                                     {
    return AllocationHint(true);
  }
References AllocationHint().
Member Data Documentation
may_grow_
bool v8::internal::AllocationHint::may_grow_ = false [private]
Definition at line 1432 of file globals.h.
Referenced by MayGrow().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/common/globals.h