v8::internal::BuiltinExitFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
Tagged< JSFunction > function () const
Tagged< Object > receiver () const
Tagged< Object > GetParameter (int i) const
int ComputeParametersCount () const
DirectHandle< FixedArray > GetParameters () const
bool IsConstructor () const
void Print (StringStream *accumulator, PrintMode mode, int index) const override
FrameSummaries Summarize () const override
Protected Member Functions
BuiltinExitFrame (StackFrameIteratorBase *iterator)
Private Member Functions
Tagged< Object > receiver_slot_object () const
Tagged< Object > argc_slot_object () const
Tagged< Object > target_slot_object () const
Tagged< Object > new_target_slot_object () const
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 930 of file frames.h.
Constructor & Destructor Documentation
BuiltinExitFrame()
v8::internal::BuiltinExitFrame::BuiltinExitFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 140 of file frames-inl.h.
    : ExitFrame(iterator) {}
Member Function Documentation
argc_slot_object()
Tagged< Object > v8::internal::BuiltinExitFrame::argc_slot_object () const [inline], [private]
Definition at line 148 of file frames-inl.h.
                                                               {
  return Tagged<Object>(
      base::Memory<Address>(fp() + BuiltinExitFrameConstants::kArgcOffset));
}
References v8::internal::StackFrame::fp(), v8::internal::BuiltinExitFrameConstants::kArgcOffset, and v8::internal::Tagged< Object >.
Referenced by ComputeParametersCount().
ComputeParametersCount()
int v8::internal::BuiltinExitFrame::ComputeParametersCount () const
Definition at line 1250 of file frames.cc.
                                                   {
  Tagged<Object> argc_slot = argc_slot_object();
  DCHECK(IsSmi(argc_slot));
  // Argc also counts the receiver and extra arguments for BuiltinExitFrame
  // (target, new target and argc itself), therefore the real argument count
  // has to be adjusted.
  int argc = Smi::ToInt(argc_slot) -
             BuiltinExitFrameConstants::kNumExtraArgsWithReceiver;
  DCHECK_GE(argc, 0);
  return argc;
}
References argc_slot_object(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::IsSmi(), v8::internal::BuiltinExitFrameConstants::kNumExtraArgsWithReceiver, and v8::internal::Smi::ToInt().
Referenced by GetParameter(), GetParameters(), and Print().
function()
Tagged< JSFunction > v8::internal::BuiltinExitFrame::function () const
Definition at line 1235 of file frames.cc.
                                                    {
  return Cast<JSFunction>(target_slot_object());
}
References target_slot_object().
GetParameter()
Tagged< Object > v8::internal::BuiltinExitFrame::GetParameter (int i) const
Definition at line 1243 of file frames.cc.
                                                         {
  DCHECK(i >= 0 && i < ComputeParametersCount());
  int offset =
      BuiltinExitFrameConstants::kFirstArgumentOffset + i * kSystemPointerSize;
  return Tagged<Object>(Memory<Address>(fp() + offset));
}
References ComputeParametersCount(), v8::internal::DCHECK(), v8::internal::StackFrame::fp(), v8::internal::BuiltinExitFrameConstants::kFirstArgumentOffset, v8::internal::kSystemPointerSize, and v8::internal::Tagged< Object >.
Referenced by GetParameters(), and Print().
GetParameters()
DirectHandle< FixedArray > v8::internal::BuiltinExitFrame::GetParameters () const
Definition at line 1262 of file frames.cc.
                                                               {
  if (V8_LIKELY(!v8_flags.detailed_error_stack_trace)) {
    return isolate()->factory()->empty_fixed_array();
  }
  int param_count = ComputeParametersCount();
  auto parameters = isolate()->factory()->NewFixedArray(param_count);
  for (int i = 0; i < param_count; i++) {
    parameters->set(i, GetParameter(i));
  }
  return parameters;
}
References ComputeParametersCount(), v8::internal::Isolate::factory(), GetParameter(), v8::internal::StackFrame::isolate(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::v8_flags, and V8_LIKELY.
Referenced by Summarize().
IsConstructor()
bool v8::internal::BuiltinExitFrame::IsConstructor () const
Definition at line 1274 of file frames.cc.
                                           {
  return !IsUndefined(new_target_slot_object(), isolate());
}
References v8::internal::StackFrame::isolate(), and new_target_slot_object().
Referenced by Print(), and Summarize().
new_target_slot_object()
Tagged< Object > v8::internal::BuiltinExitFrame::new_target_slot_object () const [inline], [private]
Definition at line 158 of file frames-inl.h.
                                                                     {
  return Tagged<Object>(base::Memory<Address>(
      fp() + BuiltinExitFrameConstants::kNewTargetOffset));
}
References v8::internal::StackFrame::fp(), v8::internal::BuiltinExitFrameConstants::kNewTargetOffset, and v8::internal::Tagged< Object >.
Referenced by IsConstructor().
Print()
void v8::internal::BuiltinExitFrame::Print (StringStream * accumulator, PrintMode mode, int index) const [override], [virtual]
Reimplemented from v8::internal::StackFrame.
Definition at line 1406 of file frames.cc.
                                              {
  DisallowGarbageCollection no_gc;
  Tagged<Object> receiver = this->receiver();
  Tagged<JSFunction> function = this->function();
  Tagged<SharedFunctionInfo> sfi = function->shared();
  accumulator->PrintSecurityTokenIfChanged(isolate(), function);
  PrintIndex(accumulator, mode, index);
  accumulator->Add("BuiltinExitFrame ");
  if (sfi->HasBuiltinId()) {
    // API functions have builtin code but not builtin SFIs, so don't print the
    // builtins for those.
    accumulator->Add("[builtin: %s] ", Builtins::name(sfi->builtin_id()));
  }
  if (IsConstructor()) accumulator->Add("new ");
  accumulator->PrintFunction(isolate(), function, receiver);
  accumulator->Add("(this=%o", receiver);
  // Print the parameters.
  int parameters_count = ComputeParametersCount();
  for (int i = 0; i < parameters_count; i++) {
    accumulator->Add(",%o", GetParameter(i));
  }
  accumulator->Add(")\n");
}
References v8::internal::StringStream::Add(), ComputeParametersCount(), GetParameter(), v8::internal::index, IsConstructor(), v8::internal::StackFrame::isolate(), mode(), v8::internal::Builtins::name(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::StringStream::PrintFunction(), v8::internal::anonymous_namespace{frames.cc}::PrintIndex(), v8::internal::StringStream::PrintSecurityTokenIfChanged(), and receiver().
receiver()
Tagged< Object > v8::internal::BuiltinExitFrame::receiver () const
Definition at line 1239 of file frames.cc.
                                                {
  return receiver_slot_object();
}
References receiver_slot_object().
Referenced by Print(), and Summarize().
receiver_slot_object()
Tagged< Object > v8::internal::BuiltinExitFrame::receiver_slot_object () const [inline], [private]
Definition at line 143 of file frames-inl.h.
                                                                   {
  return Tagged<Object>(
      base::Memory<Address>(fp() + BuiltinExitFrameConstants::kReceiverOffset));
}
References v8::internal::StackFrame::fp(), v8::internal::BuiltinExitFrameConstants::kReceiverOffset, and v8::internal::Tagged< Object >.
Referenced by receiver().
Summarize()
FrameSummaries v8::internal::BuiltinExitFrame::Summarize () const [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 1223 of file frames.cc.
                                                 {
  DirectHandle<FixedArray> parameters = GetParameters();
  DisallowGarbageCollection no_gc;
  Tagged<Code> code;
  int code_offset = -1;
  std::tie(code, code_offset) = LookupCodeAndOffset();
  FrameSummary::JavaScriptFrameSummary summary(
      isolate(), receiver(), function(), Cast<AbstractCode>(code), code_offset,
      IsConstructor(), *parameters);
  return FrameSummaries(summary);
}
References code, GetParameters(), IsConstructor(), v8::internal::StackFrame::isolate(), v8::internal::StackFrame::LookupCodeAndOffset(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and receiver().
target_slot_object()
Tagged< Object > v8::internal::BuiltinExitFrame::target_slot_object () const [inline], [private]
Definition at line 153 of file frames-inl.h.
                                                                 {
  return Tagged<Object>(
      base::Memory<Address>(fp() + BuiltinExitFrameConstants::kTargetOffset));
}
References v8::internal::StackFrame::fp(), v8::internal::BuiltinExitFrameConstants::kTargetOffset, and v8::internal::Tagged< Object >.
Referenced by function().
type()
Type v8::internal::BuiltinExitFrame::type () const [inline], [override], [virtual]
Reimplemented from v8::internal::ExitFrame.
Definition at line 932 of file frames.h.
{ return BUILTIN_EXIT; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 959 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc