v8::base::Semaphore Class Reference
#include <semaphore.h>
Public Member Functions
Semaphore (int count)
Semaphore (const Semaphore &)=delete
Semaphore & operator= (const Semaphore &)=delete
~Semaphore ()
void Signal ()
void Wait ()
bool WaitFor (const TimeDelta &rel_time) V8_WARN_UNUSED_RESULT
NativeHandle & native_handle ()
const NativeHandle & native_handle () const
Private Attributes
NativeHandle native_handle_
Detailed Description
Definition at line 41 of file semaphore.h.
Constructor & Destructor Documentation
Semaphore() [1/2]
v8::base::Semaphore::Semaphore (int count) [explicit]
Semaphore() [2/2]
v8::base::Semaphore::Semaphore (const Semaphore &) [delete]
 Semaphore()
v8::base::Semaphore::~Semaphore ()
Member Function Documentation
native_handle() [1/2]
NativeHandle& v8::base::Semaphore::native_handle () [inline]
Definition at line 70 of file semaphore.h.
                                {
    return native_handle_;
  }
native_handle() [2/2]
const NativeHandle& v8::base::Semaphore::native_handle () const [inline]
Definition at line 73 of file semaphore.h.
                                            {
    return native_handle_;
  }
operator=()
Semaphore& v8::base::Semaphore::operator= (const Semaphore &) [delete]
Signal()
void v8::base::Semaphore::Signal ()
Referenced by v8::internal::wasm::gdb_server::TaskRunner::Append(), v8::platform::TaskQueue::Append(), v8::SourceGroup::ExecuteInThread(), v8::Worker::ExecuteInThread(), v8::platform::TaskQueue::GetNext(), v8::internal::Profiler::Insert(), v8::internal::wasm::gdb_server::Target::OnSuspended(), v8::internal::wasm::gdb_server::TaskRunner::Task::Run(), v8::internal::wasm::gdb_server::GdbServerThread::Run(), v8::SourceGroup::StartExecuteInThread(), v8::internal::wasm::gdb_server::TaskRunner::Terminate(), and v8::platform::TaskQueue::Terminate().
Wait()
void v8::base::Semaphore::Wait ()
Referenced by v8::internal::LazyCompileDispatcher::DoBackgroundWork(), v8::internal::wasm::gdb_server::TaskRunner::GetNext(), v8::platform::TaskQueue::GetNext(), v8::internal::Profiler::Remove(), v8::internal::wasm::gdb_server::GdbServer::RunSyncTask(), and v8::internal::wasm::gdb_server::GdbServerThread::StartAndInitialize().
WaitFor()
bool v8::base::Semaphore::WaitFor (const TimeDelta & rel_time)
Referenced by v8::internal::wasm::gdb_server::Target::Suspend().
Member Data Documentation
native_handle_
NativeHandle v8::base::Semaphore::native_handle_ [private]
Definition at line 78 of file semaphore.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/platform/semaphore.h