v8::internal::AlwaysSharedSpaceJSObject Class Reference
#include <js-struct.h>
Static Public Member Functions
static void PrepareMapNoEnumerableProperties (Tagged< Map > map)
static void PrepareMapNoEnumerableProperties (Isolate *isolate, Tagged< Map > map, Tagged< DescriptorArray > descriptors)
static void PrepareMapWithEnumerableProperties (Isolate *isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors, int enum_length)
static V8_WARN_UNUSED_RESULT Maybe< bool > DefineOwnProperty (Isolate *isolate, DirectHandle< AlwaysSharedSpaceJSObject > shared_obj, DirectHandle< Object > key, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static Maybe< bool > HasInstance (Isolate *isolate, DirectHandle< JSFunction > constructor, DirectHandle< Object > object)
Detailed Description
Definition at line 19 of file js-struct.h.
Member Function Documentation
DefineOwnProperty()
Maybe< bool > v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty (Isolate * isolate, DirectHandle< AlwaysSharedSpaceJSObject > shared_obj, DirectHandle< Object > key, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 63 of file js-struct.cc.
                                     {
  // Shared objects are designed to have fixed layout, i.e. their maps are
  // effectively immutable. They are constructed seal, but the semantics of
  // ordinary ECMAScript objects allow writable properties to be upgraded to
  // non-writable properties. This upgrade violates the fixed layout invariant
  // and is disallowed.
  DCHECK(IsName(*key) || IsNumber(*key)); // |key| is a PropertyKey.
  PropertyKey lookup_key(isolate, key);
  LookupIterator it(isolate, shared_obj, lookup_key, LookupIterator::OWN);
  PropertyDescriptor current;
  MAYBE_RETURN(GetOwnPropertyDescriptor(&it, &current), Nothing<bool>());
  // The only redefinition allowed is to set the value if all attributes match.
  if (!it.IsFound() ||
      PropertyDescriptor::IsDataDescriptor(desc) !=
          PropertyDescriptor::IsDataDescriptor(&current) ||
      desc->ToAttributes() != current.ToAttributes()) {
    DCHECK(!shared_obj->map()->is_extensible());
    RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                   NewTypeError(MessageTemplate::kDefineDisallowedFixedLayout,
                                it.GetName()));
  }
  DCHECK(it.property_attributes() == desc->ToAttributes());
  if (desc->has_value()) {
    return Object::SetDataProperty(&it, desc->value());
  }
  return Just(true);
}
References v8::internal::DCHECK(), v8::internal::LookupIterator::GetName(), v8::internal::GetShouldThrow(), v8::internal::PropertyDescriptor::has_value(), v8::internal::PropertyDescriptor::IsDataDescriptor(), v8::internal::LookupIterator::IsFound(), v8::internal::IsNumber(), v8::Just(), v8::internal::key, MAYBE_RETURN, v8::internal::LookupIterator::OWN, v8::internal::LookupIterator::property_attributes(), RETURN_FAILURE, v8::internal::Object::SetDataProperty(), v8::internal::PropertyDescriptor::ToAttributes(), and v8::internal::PropertyDescriptor::value().
Referenced by v8::internal::JSReceiver::DefineOwnProperty().
HasInstance()
Maybe< bool > v8::internal::AlwaysSharedSpaceJSObject::HasInstance (Isolate * isolate, DirectHandle< JSFunction > constructor, DirectHandle< Object > object) [static]
Definition at line 96 of file js-struct.cc.
                                 {
  if (!constructor->has_prototype_slot() || !constructor->has_initial_map() ||
      !IsJSReceiver(*object)) {
    return Just(false);
  }
  DirectHandle<Map> constructor_map(constructor->initial_map(), isolate);
  PrototypeIterator iter(isolate, Cast<JSReceiver>(object), kStartAtReceiver);
  DirectHandle<Map> current_map;
  while (true) {
    current_map =
        direct_handle(PrototypeIterator::GetCurrent(iter)->map(), isolate);
    if (current_map.is_identical_to(constructor_map)) {
      return Just(true);
    }
    if (!iter.AdvanceFollowingProxies()) return Nothing<bool>();
    if (iter.IsAtEnd()) return Just(false);
  }
}
References v8::internal::PrototypeIterator::AdvanceFollowingProxies(), v8::internal::direct_handle(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::PrototypeIterator::IsAtEnd(), v8::Just(), and v8::internal::kStartAtReceiver.
Referenced by v8::internal::BUILTIN().
PrepareMapNoEnumerableProperties() [1/2]
void v8::internal::AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties (Isolate * isolate, Tagged< Map > map, Tagged< DescriptorArray > descriptors) [static]
Definition at line 41 of file js-struct.cc.
                                                                            {
  PrepareMapCommon(map);
  map->InitializeDescriptors(isolate, *descriptors);
  DCHECK_EQ(0, map->NumberOfEnumerableProperties());
  map->SetEnumLength(0);
}
References DCHECK_EQ, and v8::internal::anonymous_namespace{js-struct.cc}::PrepareMapCommon().
PrepareMapNoEnumerableProperties() [2/2]
void v8::internal::AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties (Tagged< Map > map) [static]
Definition at line 34 of file js-struct.cc.
                     {
  PrepareMapCommon(map);
  map->SetEnumLength(0);
}
References v8::internal::anonymous_namespace{js-struct.cc}::PrepareMapCommon().
Referenced by v8::internal::JSSharedStruct::CreateInstanceMap(), and v8::internal::Heap::CreateLateReadOnlyJSReceiverMaps().
PrepareMapWithEnumerableProperties()
void v8::internal::AlwaysSharedSpaceJSObject::PrepareMapWithEnumerableProperties (Isolate * isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors, int enum_length) [static]
Definition at line 50 of file js-struct.cc.
                                                                {
  PrepareMapCommon(*map);
  // Shared objects with enumerable own properties need to pre-create the enum
  // cache, as creating it lazily is racy.
  map->InitializeDescriptors(isolate, *descriptors);
  FastKeyAccumulator::InitializeFastPropertyEnumCache(
      isolate, map, enum_length, AllocationType::kSharedOld);
  DCHECK_EQ(enum_length, map->EnumLength());
}
References DCHECK_EQ, v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::kSharedOld, and v8::internal::anonymous_namespace{js-struct.cc}::PrepareMapCommon().
Referenced by v8::internal::JSSharedStruct::CreateInstanceMap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-struct.h
/mnt/V8SourceCode/src/objects/js-struct.cc