v8::internal::SafepointTableBuilder Class Reference
#include <safepoint-table.h>
Classes
struct EntryBuilder
class Safepoint
Public Member Functions
SafepointTableBuilder (Zone *zone)
SafepointTableBuilder (const SafepointTableBuilder &)=delete
SafepointTableBuilder & operator= (const SafepointTableBuilder &)=delete
Safepoint DefineSafepoint (Assembler *assembler, int pc_offset=0)
V8_EXPORT_PRIVATE void Emit (Assembler *assembler, int stack_slot_count)
int UpdateDeoptimizationInfo (int pc, int trampoline, int start, int deopt_index)
Private Member Functions
void RemoveDuplicates ()
void UpdateMinMaxStackIndex (int index)
int min_stack_index () const
Private Attributes
int min_stack_index_ = std::numeric_limits<int>::max()
ZoneDeque< EntryBuilder > entries_
Zone * zone_
Additional Inherited Members
Detailed Description
Definition at line 197 of file safepoint-table.h.
Constructor & Destructor Documentation
SafepointTableBuilder() [1/2]
v8::internal::SafepointTableBuilder::SafepointTableBuilder (Zone * zone) [inline], [explicit]
Definition at line 210 of file safepoint-table.h.
: entries_(zone), zone_(zone) {}
SafepointTableBuilder() [2/2]
v8::internal::SafepointTableBuilder::SafepointTableBuilder (const SafepointTableBuilder &) [delete]
Member Function Documentation
DefineSafepoint()
SafepointTableBuilder::Safepoint v8::internal::SafepointTableBuilder::DefineSafepoint (Assembler * assembler, int pc_offset = 0)
Definition at line 143 of file safepoint-table.cc.
                                         {
  pc_offset = pc_offset ? pc_offset : assembler->pc_offset_for_safepoint();
  entries_.emplace_back(zone_, pc_offset);
  return SafepointTableBuilder::Safepoint(&entries_.back(), this);
}
References entries_, v8::internal::Assembler::pc_offset_for_safepoint(), and zone_.
Referenced by v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame(), and v8::internal::compiler::CodeGenerator::RecordSafepoint().
Emit()
void v8::internal::SafepointTableBuilder::Emit (Assembler * assembler, int stack_slot_count)
Definition at line 165 of file safepoint-table.cc.
                                                                           {
  DCHECK_LT(max_stack_index_, stack_slot_count);
#ifdef DEBUG
  int last_pc = -1;
  int last_trampoline = -1;
  for (const EntryBuilder& entry : entries_) {
    // Entries are ordered by PC.
    DCHECK_LT(last_pc, entry.pc);
    last_pc = entry.pc;
    // Trampoline PCs are increasing, and larger than regular PCs.
    if (entry.trampoline != SafepointEntry::kNoTrampolinePC) {
      DCHECK_LT(last_trampoline, entry.trampoline);
      DCHECK_LT(entries_.back().pc, entry.trampoline);
      last_trampoline = entry.trampoline;
    }
    // An entry either has trampoline and deopt index, or none of the two.
    DCHECK_EQ(entry.trampoline == SafepointEntry::kNoTrampolinePC,
              entry.deopt_index == SafepointEntry::kNoDeoptIndex);
  }
#endif // DEBUG
  RemoveDuplicates();
  // The encoding is compacted by translating stack slot indices s.t. they
  // start at 0. See also below.
  int tagged_slots_size = stack_slot_count - min_stack_index();
#if V8_TARGET_ARCH_ARM || V8_TARGET_ARCH_ARM64
  // We cannot emit a const pool within the safepoint table.
  Assembler::BlockConstPoolScope block_const_pool(assembler);
#endif
  // Make sure the safepoint table is properly aligned. Pad with nops.
  assembler->Align(InstructionStream::kMetadataAlignment);
  assembler->RecordComment(";;; Safepoint table.");
  set_safepoint_table_offset(assembler->pc_offset());
  // Compute the required sizes of the fields.
  int used_register_indexes = 0;
  static_assert(SafepointEntry::kNoTrampolinePC == -1);
  int max_pc = SafepointEntry::kNoTrampolinePC;
  static_assert(SafepointEntry::kNoDeoptIndex == -1);
  int max_deopt_index = SafepointEntry::kNoDeoptIndex;
  for (const EntryBuilder& entry : entries_) {
    used_register_indexes |= entry.register_indexes;
    max_pc = std::max(max_pc, std::max(entry.pc, entry.trampoline));
    max_deopt_index = std::max(max_deopt_index, entry.deopt_index);
  }
  // Derive the bytes and bools for the entry configuration from the values.
  auto value_to_bytes = [](int value) {
    DCHECK_LE(0, value);
    if (value == 0) return 0;
    if (value <= 0xff) return 1;
    if (value <= 0xffff) return 2;
    if (value <= 0xffffff) return 3;
    return 4;
  };
  bool has_deopt_data = max_deopt_index != -1;
  int register_indexes_size = value_to_bytes(used_register_indexes);
  // Add 1 so all values (including kNoDeoptIndex and kNoTrampolinePC) are
  // non-negative.
  static_assert(SafepointEntry::kNoDeoptIndex == -1);
  static_assert(SafepointEntry::kNoTrampolinePC == -1);
  int pc_size = value_to_bytes(max_pc + 1);
  int deopt_index_size = value_to_bytes(max_deopt_index + 1);
  int tagged_slots_bytes =
      (tagged_slots_size + kBitsPerByte - 1) / kBitsPerByte;
  // Add a CHECK to ensure we never overflow the space in the bitfield, even for
  // huge functions which might not be covered by tests.
  CHECK(SafepointTable::RegisterIndexesSizeField::is_valid(
      register_indexes_size));
  CHECK(SafepointTable::PcSizeField::is_valid(pc_size));
  CHECK(SafepointTable::DeoptIndexSizeField::is_valid(deopt_index_size));
  CHECK(SafepointTable::TaggedSlotsBytesField::is_valid(tagged_slots_bytes));
  uint32_t entry_configuration =
      SafepointTable::HasDeoptDataField::encode(has_deopt_data) |
      SafepointTable::RegisterIndexesSizeField::encode(register_indexes_size) |
      SafepointTable::PcSizeField::encode(pc_size) |
      SafepointTable::DeoptIndexSizeField::encode(deopt_index_size) |
      SafepointTable::TaggedSlotsBytesField::encode(tagged_slots_bytes);
  // Emit the table header.
  static_assert(SafepointTable::kStackSlotsOffset == 0 * kIntSize);
  static_assert(SafepointTable::kLengthOffset == 1 * kIntSize);
  static_assert(SafepointTable::kEntryConfigurationOffset == 2 * kIntSize);
  static_assert(SafepointTable::kHeaderSize == 3 * kIntSize);
  int length = static_cast<int>(entries_.size());
  assembler->dd(stack_slot_count);
  assembler->dd(length);
  assembler->dd(entry_configuration);
  auto emit_bytes = [assembler](int value, int bytes) {
    DCHECK_LE(0, value);
    for (; bytes > 0; --bytes, value >>= 8) assembler->db(value);
    DCHECK_EQ(0, value);
  };
  // Emit entries, sorted by pc offsets.
  for (const EntryBuilder& entry : entries_) {
    emit_bytes(entry.pc, pc_size);
    if (has_deopt_data) {
      // Add 1 so all values (including kNoDeoptIndex and kNoTrampolinePC) are
      // non-negative.
      static_assert(SafepointEntry::kNoDeoptIndex == -1);
      static_assert(SafepointEntry::kNoTrampolinePC == -1);
      emit_bytes(entry.deopt_index + 1, deopt_index_size);
      emit_bytes(entry.trampoline + 1, pc_size);
    }
    emit_bytes(entry.register_indexes, register_indexes_size);
  }
  // Emit bitmaps of tagged stack slots. Note the slot list is reversed in the
  // encoding.
  // TODO(jgruber): Avoid building a reversed copy of the bit vector.
  ZoneVector<uint8_t> bits(tagged_slots_bytes, 0, zone_);
  for (const EntryBuilder& entry : entries_) {
    std::fill(bits.begin(), bits.end(), 0);
    // Run through the indexes and build a bitmap.
    for (int idx : *entry.stack_indexes) {
      // The encoding is compacted by translating stack slot indices s.t. they
      // start at 0. See also above.
      const int adjusted_idx = idx - min_stack_index();
      DCHECK_GT(tagged_slots_size, adjusted_idx);
      int index = tagged_slots_size - 1 - adjusted_idx;
      int byte_index = index >> kBitsPerByteLog2;
      int bit_index = index & (kBitsPerByte - 1);
      bits[byte_index] |= (1u << bit_index);
    }
    // Emit the bitmap for the current entry.
    for (uint8_t byte : bits) assembler->db(byte);
  }
}
References v8::internal::Assembler::Align(), v8::internal::ZoneVector< T >::begin(), CHECK, v8::internal::Assembler::db(), DCHECK_EQ, DCHECK_GT, DCHECK_LE, DCHECK_LT, v8::internal::Assembler::dd(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::ZoneVector< T >::end(), entries_, v8::internal::index, v8::base::BitField< T, shift, size, U >::is_valid(), v8::internal::kBitsPerByte, v8::internal::kBitsPerByteLog2, v8::internal::kIntSize, v8::internal::InstructionStream::kMetadataAlignment, v8::internal::SafepointEntryBase::kNoDeoptIndex, v8::internal::SafepointEntryBase::kNoTrampolinePC, v8::internal::length, min_stack_index(), v8::internal::AssemblerBase::pc_offset(), v8::internal::AssemblerBase::RecordComment(), RemoveDuplicates(), v8::internal::SafepointTableBuilderBase::set_safepoint_table_offset(), v8::internal::value, and zone_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode().
min_stack_index()
int v8::internal::SafepointTableBuilder::min_stack_index () const [inline], [private]
Definition at line 266 of file safepoint-table.h.
                              {
    return min_stack_index_ == std::numeric_limits<int>::max()
               ? 0
               : min_stack_index_;
  }
Referenced by Emit().
operator=()
SafepointTableBuilder& v8::internal::SafepointTableBuilder::operator= (const SafepointTableBuilder &) [delete]
RemoveDuplicates()
void v8::internal::SafepointTableBuilder::RemoveDuplicates () [private]
Definition at line 303 of file safepoint-table.cc.
                                             {
  // Remove any duplicate entries, i.e. succeeding entries that are identical
  // except for the PC. During lookup, we will find the first entry whose PC is
  // not larger than the PC at hand, and find the first non-duplicate.
  if (entries_.size() < 2) return;
  auto is_identical_except_for_pc = [](const EntryBuilder& entry1,
                                       const EntryBuilder& entry2) {
    if (entry1.deopt_index != entry2.deopt_index) return false;
    DCHECK_EQ(entry1.trampoline, entry2.trampoline);
    return entry1.register_indexes == entry2.register_indexes &&
           entry1.stack_indexes->Equals(*entry2.stack_indexes);
  };
  auto remaining_it = entries_.begin();
  auto end = entries_.end();
  for (auto it = entries_.begin(); it != end; ++remaining_it) {
    if (remaining_it != it) *remaining_it = *it;
    // Merge identical entries.
    do {
      ++it;
    } while (it != end && is_identical_except_for_pc(*it, *remaining_it));
  }
  entries_.erase(remaining_it, end);
}
References DCHECK_EQ, v8::internal::SafepointTableBuilder::EntryBuilder::deopt_index, v8::internal::compiler::end(), entries_, v8::internal::GrowableBitVector::Equals(), v8::internal::SafepointTableBuilder::EntryBuilder::register_indexes, v8::internal::SafepointTableBuilder::EntryBuilder::stack_indexes, and v8::internal::SafepointTableBuilder::EntryBuilder::trampoline.
Referenced by Emit().
UpdateDeoptimizationInfo()
int v8::internal::SafepointTableBuilder::UpdateDeoptimizationInfo (int pc, int trampoline, int start, int deopt_index)
Definition at line 150 of file safepoint-table.cc.
                                                                     {
  DCHECK_NE(SafepointEntry::kNoTrampolinePC, trampoline);
  DCHECK_NE(SafepointEntry::kNoDeoptIndex, deopt_index);
  auto it = entries_.begin() + start;
  DCHECK(std::any_of(it, entries_.end(),
                     [pc](auto& entry) { return entry.pc == pc; }));
  int index = start;
  while (it->pc != pc) ++it, ++index;
  it->trampoline = trampoline;
  it->deopt_index = deopt_index;
  return index;
}
References v8::base::any_of(), v8::internal::DCHECK(), DCHECK_NE, entries_, v8::internal::index, v8::internal::SafepointEntryBase::kNoDeoptIndex, and v8::internal::SafepointEntryBase::kNoTrampolinePC.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode().
UpdateMinMaxStackIndex()
void v8::internal::SafepointTableBuilder::UpdateMinMaxStackIndex (int index) [inline], [private]
Definition at line 259 of file safepoint-table.h.
                                         {
#ifdef DEBUG
    if (index > max_stack_index_) max_stack_index_ = index;
#endif // DEBUG
    if (index < min_stack_index_) min_stack_index_ = index;
  }
References v8::internal::index.
Member Data Documentation
entries_
ZoneDeque<EntryBuilder> v8::internal::SafepointTableBuilder::entries_ [private]
Definition at line 281 of file safepoint-table.h.
Referenced by DefineSafepoint(), Emit(), RemoveDuplicates(), and UpdateDeoptimizationInfo().
min_stack_index_
int v8::internal::SafepointTableBuilder::min_stack_index_ = std::numeric_limits<int>::max() [private]
Definition at line 279 of file safepoint-table.h.
zone_
Zone* v8::internal::SafepointTableBuilder::zone_ [private]
Definition at line 282 of file safepoint-table.h.
Referenced by DefineSafepoint(), and Emit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/safepoint-table.h
/mnt/V8SourceCode/src/codegen/safepoint-table.cc