v8::internal::compiler::Arm64OperandConverter Class Reference
Public Member Functions
Arm64OperandConverter (CodeGenerator *gen, Instruction *instr)
DoubleRegister InputFloat32Register (size_t index)
DoubleRegister InputFloat64Register (size_t index)
DoubleRegister InputSimd128Register (size_t index)
CPURegister InputFloat32OrZeroRegister (size_t index)
DoubleRegister InputFloat32OrFPZeroRegister (size_t index)
CPURegister InputFloat64OrZeroRegister (size_t index)
DoubleRegister InputFloat64OrFPZeroRegister (size_t index)
size_t OutputCount ()
DoubleRegister OutputFloat32Register (size_t index=0)
DoubleRegister OutputFloat64Register (size_t index=0)
DoubleRegister OutputSimd128Register (size_t index=0)
Register InputRegister32 (size_t index)
Register InputOrZeroRegister32 (size_t index)
Register InputRegister64 (size_t index)
Register InputOrZeroRegister64 (size_t index)
Operand InputOperand (size_t index)
Operand InputOperand64 (size_t index)
Operand InputOperand32 (size_t index)
Register OutputRegister64 (size_t index=0)
Register OutputRegister32 (size_t index=0)
Register TempRegister32 (size_t index)
Operand InputOperand2_32 (size_t index)
Operand InputOperand2_64 (size_t index)
MemOperand MemoryOperand (size_t index=0)
Operand ToOperand (InstructionOperand *op)
Operand ToOperand32 (InstructionOperand *op)
Operand ToImmediate (InstructionOperand *operand)
MemOperand ToMemOperand (InstructionOperand *op, MacroAssembler *masm) const
MemOperand SlotToMemOperand (int slot, MacroAssembler *masm) const
Additional Inherited Members
Detailed Description
Definition at line 32 of file code-generator-arm64.cc.
Constructor & Destructor Documentation
Arm64OperandConverter()
v8::internal::compiler::Arm64OperandConverter::Arm64OperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 34 of file code-generator-arm64.cc.
      : InstructionOperandConverter(gen, instr) {}
Member Function Documentation
InputFloat32OrFPZeroRegister()
DoubleRegister v8::internal::compiler::Arm64OperandConverter::InputFloat32OrFPZeroRegister (size_t index) [inline]
Definition at line 58 of file code-generator-arm64.cc.
                                                            {
    if (instr_->InputAt(index)->IsImmediate()) {
      DCHECK_EQ(0, base::bit_cast<int32_t>(InputFloat32(index)));
      return fp_zero.S();
    }
    DCHECK(instr_->InputAt(index)->IsFPRegister());
    return InputDoubleRegister(index).S();
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::InputFloat32(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::InstructionOperand::IsFPRegister().
InputFloat32OrZeroRegister()
CPURegister v8::internal::compiler::Arm64OperandConverter::InputFloat32OrZeroRegister (size_t index) [inline]
Definition at line 49 of file code-generator-arm64.cc.
                                                       {
    if (instr_->InputAt(index)->IsImmediate()) {
      DCHECK_EQ(0, base::bit_cast<int32_t>(InputFloat32(index)));
      return wzr;
    }
    DCHECK(instr_->InputAt(index)->IsFPRegister());
    return InputDoubleRegister(index).S();
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::InputFloat32(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::InstructionOperand::IsFPRegister().
InputFloat32Register()
DoubleRegister v8::internal::compiler::Arm64OperandConverter::InputFloat32Register (size_t index) [inline]
Definition at line 37 of file code-generator-arm64.cc.
                                                    {
    return InputDoubleRegister(index).S();
  }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister().
InputFloat64OrFPZeroRegister()
DoubleRegister v8::internal::compiler::Arm64OperandConverter::InputFloat64OrFPZeroRegister (size_t index) [inline]
Definition at line 76 of file code-generator-arm64.cc.
                                                            {
    if (instr_->InputAt(index)->IsImmediate()) {
      DCHECK_EQ(0, base::bit_cast<int64_t>(InputDouble(index)));
      return fp_zero;
    }
    DCHECK(instr_->InputAt(index)->IsDoubleRegister());
    return InputDoubleRegister(index);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputDouble(), v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::InstructionOperand::IsDoubleRegister().
InputFloat64OrZeroRegister()
CPURegister v8::internal::compiler::Arm64OperandConverter::InputFloat64OrZeroRegister (size_t index) [inline]
Definition at line 67 of file code-generator-arm64.cc.
                                                       {
    if (instr_->InputAt(index)->IsImmediate()) {
      DCHECK_EQ(0, base::bit_cast<int64_t>(InputDouble(index)));
      return xzr;
    }
    DCHECK(instr_->InputAt(index)->IsDoubleRegister());
    return InputDoubleRegister(index);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputDouble(), v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::InstructionOperand::IsDoubleRegister().
InputFloat64Register()
DoubleRegister v8::internal::compiler::Arm64OperandConverter::InputFloat64Register (size_t index) [inline]
Definition at line 41 of file code-generator-arm64.cc.
                                                    {
    return InputDoubleRegister(index);
  }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister().
InputOperand()
Operand v8::internal::compiler::Arm64OperandConverter::InputOperand (size_t index) [inline]
Definition at line 123 of file code-generator-arm64.cc.
                                     {
    return ToOperand(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToOperand().
Referenced by InputOperand64().
InputOperand2_32()
Operand v8::internal::compiler::Arm64OperandConverter::InputOperand2_32 (size_t index) [inline]
Definition at line 143 of file code-generator-arm64.cc.
                                         {
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_None:
        return InputOperand32(index);
      case kMode_Operand2_R_LSL_I:
        return Operand(InputRegister32(index), LSL, InputInt5(index + 1));
      case kMode_Operand2_R_LSR_I:
        return Operand(InputRegister32(index), LSR, InputInt5(index + 1));
      case kMode_Operand2_R_ASR_I:
        return Operand(InputRegister32(index), ASR, InputInt5(index + 1));
      case kMode_Operand2_R_ROR_I:
        return Operand(InputRegister32(index), ROR, InputInt5(index + 1));
      case kMode_Operand2_R_UXTB:
        return Operand(InputRegister32(index), UXTB);
      case kMode_Operand2_R_UXTH:
        return Operand(InputRegister32(index), UXTH);
      case kMode_Operand2_R_SXTB:
        return Operand(InputRegister32(index), SXTB);
      case kMode_Operand2_R_SXTH:
        return Operand(InputRegister32(index), SXTH);
      case kMode_Operand2_R_SXTW:
        return Operand(InputRegister32(index), SXTW);
      case kMode_MRI:
      case kMode_MRR:
      case kMode_Root:
        break;
    }
    UNREACHABLE();
  }
References v8::internal::ASR, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt5(), InputOperand32(), InputRegister32(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::LSL, v8::internal::LSR, v8::internal::compiler::Instruction::opcode(), v8::internal::ROR, v8::internal::SXTB, v8::internal::SXTH, v8::internal::SXTW, v8::internal::UNREACHABLE(), v8::internal::UXTB, and v8::internal::UXTH.
InputOperand2_64()
Operand v8::internal::compiler::Arm64OperandConverter::InputOperand2_64 (size_t index) [inline]
Definition at line 173 of file code-generator-arm64.cc.
                                         {
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_None:
        return InputOperand64(index);
      case kMode_Operand2_R_LSL_I:
        return Operand(InputRegister64(index), LSL, InputInt6(index + 1));
      case kMode_Operand2_R_LSR_I:
        return Operand(InputRegister64(index), LSR, InputInt6(index + 1));
      case kMode_Operand2_R_ASR_I:
        return Operand(InputRegister64(index), ASR, InputInt6(index + 1));
      case kMode_Operand2_R_ROR_I:
        return Operand(InputRegister64(index), ROR, InputInt6(index + 1));
      case kMode_Operand2_R_UXTB:
        return Operand(InputRegister64(index), UXTB);
      case kMode_Operand2_R_UXTH:
        return Operand(InputRegister64(index), UXTH);
      case kMode_Operand2_R_SXTB:
        return Operand(InputRegister64(index), SXTB);
      case kMode_Operand2_R_SXTH:
        return Operand(InputRegister64(index), SXTH);
      case kMode_Operand2_R_SXTW:
        return Operand(InputRegister64(index), SXTW);
      case kMode_MRI:
      case kMode_MRR:
      case kMode_Root:
        break;
    }
    UNREACHABLE();
  }
References v8::internal::ASR, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt6(), InputOperand64(), InputRegister64(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::LSL, v8::internal::LSR, v8::internal::compiler::Instruction::opcode(), v8::internal::ROR, v8::internal::SXTB, v8::internal::SXTH, v8::internal::SXTW, v8::internal::UNREACHABLE(), v8::internal::UXTB, and v8::internal::UXTH.
InputOperand32()
Operand v8::internal::compiler::Arm64OperandConverter::InputOperand32 (size_t index) [inline]
Definition at line 129 of file code-generator-arm64.cc.
                                       {
    return ToOperand32(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToOperand32().
Referenced by InputOperand2_32().
InputOperand64()
Operand v8::internal::compiler::Arm64OperandConverter::InputOperand64 (size_t index) [inline]
Definition at line 127 of file code-generator-arm64.cc.
{ return InputOperand(index); }
References v8::internal::index, and InputOperand().
Referenced by InputOperand2_64().
InputOrZeroRegister32()
Register v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister32 (size_t index) [inline]
Definition at line 103 of file code-generator-arm64.cc.
                                               {
    DCHECK(instr_->InputAt(index)->IsRegister() ||
           (instr_->InputAt(index)->IsImmediate() && (InputInt32(index) == 0)));
    if (instr_->InputAt(index)->IsImmediate()) {
      return wzr;
    }
    return InputRegister32(index);
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputInt32(), InputRegister32(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::InstructionOperand::IsRegister().
InputOrZeroRegister64()
Register v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister64 (size_t index) [inline]
Definition at line 114 of file code-generator-arm64.cc.
                                               {
    DCHECK(instr_->InputAt(index)->IsRegister() ||
           (instr_->InputAt(index)->IsImmediate() && (InputInt64(index) == 0)));
    if (instr_->InputAt(index)->IsImmediate()) {
      return xzr;
    }
    return InputRegister64(index);
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputInt64(), InputRegister64(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::InstructionOperand::IsRegister().
InputRegister32()
Register v8::internal::compiler::Arm64OperandConverter::InputRegister32 (size_t index) [inline]
Definition at line 99 of file code-generator-arm64.cc.
                                         {
    return ToRegister(instr_->InputAt(index)).W();
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::InstructionOperandConverter::ToRegister().
Referenced by InputOperand2_32(), and InputOrZeroRegister32().
InputRegister64()
Register v8::internal::compiler::Arm64OperandConverter::InputRegister64 (size_t index) [inline]
Definition at line 112 of file code-generator-arm64.cc.
{ return InputRegister(index); }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::InputRegister().
Referenced by InputOperand2_64(), and InputOrZeroRegister64().
InputSimd128Register()
DoubleRegister v8::internal::compiler::Arm64OperandConverter::InputSimd128Register (size_t index) [inline]
Definition at line 45 of file code-generator-arm64.cc.
                                                    {
    return InputDoubleRegister(index).Q();
  }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister().
MemoryOperand()
MemOperand v8::internal::compiler::Arm64OperandConverter::MemoryOperand (size_t index = 0) [inline]
Definition at line 203 of file code-generator-arm64.cc.
                                             {
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_None:
      case kMode_Operand2_R_LSR_I:
      case kMode_Operand2_R_ASR_I:
      case kMode_Operand2_R_ROR_I:
      case kMode_Operand2_R_UXTB:
      case kMode_Operand2_R_UXTH:
      case kMode_Operand2_R_SXTB:
      case kMode_Operand2_R_SXTH:
      case kMode_Operand2_R_SXTW:
        break;
      case kMode_Root:
        return MemOperand(kRootRegister, InputInt64(index));
      case kMode_Operand2_R_LSL_I:
        return MemOperand(InputRegister(index + 0), InputRegister(index + 1),
                          LSL, InputInt32(index + 2));
      case kMode_MRI:
        return MemOperand(InputRegister(index + 0), InputInt32(index + 1));
      case kMode_MRR:
        return MemOperand(InputRegister(index + 0), InputRegister(index + 1));
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputInt64(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kRootRegister, v8::internal::LSL, v8::internal::compiler::Instruction::opcode(), and v8::internal::UNREACHABLE().
OutputCount()
size_t v8::internal::compiler::Arm64OperandConverter::OutputCount () [inline]
Definition at line 85 of file code-generator-arm64.cc.
{ return instr_->OutputCount(); }
References v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::Instruction::OutputCount().
OutputFloat32Register()
DoubleRegister v8::internal::compiler::Arm64OperandConverter::OutputFloat32Register (size_t index = 0) [inline]
Definition at line 87 of file code-generator-arm64.cc.
                                                         {
    return OutputDoubleRegister(index).S();
  }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::OutputDoubleRegister().
OutputFloat64Register()
DoubleRegister v8::internal::compiler::Arm64OperandConverter::OutputFloat64Register (size_t index = 0) [inline]
Definition at line 91 of file code-generator-arm64.cc.
                                                         {
    return OutputDoubleRegister(index);
  }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::OutputDoubleRegister().
OutputRegister32()
Register v8::internal::compiler::Arm64OperandConverter::OutputRegister32 (size_t index = 0) [inline]
Definition at line 135 of file code-generator-arm64.cc.
                                              {
    return OutputRegister(index).W();
  }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::OutputRegister().
OutputRegister64()
Register v8::internal::compiler::Arm64OperandConverter::OutputRegister64 (size_t index = 0) [inline]
Definition at line 133 of file code-generator-arm64.cc.
{ return OutputRegister(index); }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::OutputRegister().
OutputSimd128Register()
DoubleRegister v8::internal::compiler::Arm64OperandConverter::OutputSimd128Register (size_t index = 0) [inline]
Definition at line 95 of file code-generator-arm64.cc.
                                                         {
    return OutputDoubleRegister(index).Q();
  }
References v8::internal::index, and v8::internal::compiler::InstructionOperandConverter::OutputDoubleRegister().
SlotToMemOperand()
MemOperand v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand (int slot, MacroAssembler * masm) const [inline]
Definition at line 283 of file code-generator-arm64.cc.
                                                                    {
    FrameOffset offset = frame_access_state()->GetFrameOffset(slot);
    if (offset.from_frame_pointer()) {
      int from_sp = offset.offset() + frame_access_state()->GetSPToFPOffset();
      // Convert FP-offsets to SP-offsets if it results in better code.
      if (!frame_access_state()->frame()->invalidates_sp() &&
          (Assembler::IsImmLSUnscaled(from_sp) ||
           Assembler::IsImmLSScaled(from_sp, 3))) {
        offset = FrameOffset::FromStackPointer(from_sp);
      }
    }
    // Access below the stack pointer is not expected in arm64 and is actively
    // prevented at run time in the simulator.
    DCHECK_IMPLIES(offset.from_stack_pointer(), offset.offset() >= 0);
    return MemOperand(offset.from_stack_pointer() ? sp : fp, offset.offset());
  }
References DCHECK_IMPLIES, v8::internal::compiler::InstructionOperandConverter::frame(), v8::internal::compiler::InstructionOperandConverter::frame_access_state(), v8::internal::compiler::FrameOffset::from_frame_pointer(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::compiler::FrameOffset::FromStackPointer(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), v8::internal::compiler::FrameAccessState::GetSPToFPOffset(), v8::internal::Assembler::IsImmLSScaled(), v8::internal::Assembler::IsImmLSUnscaled(), and v8::internal::compiler::FrameOffset::offset().
Referenced by ToMemOperand().
TempRegister32()
Register v8::internal::compiler::Arm64OperandConverter::TempRegister32 (size_t index) [inline]
Definition at line 139 of file code-generator-arm64.cc.
                                        {
    return ToRegister(instr_->TempAt(index)).W();
  }
References v8::internal::index, v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::Instruction::TempAt(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
ToImmediate()
Operand v8::internal::compiler::Arm64OperandConverter::ToImmediate (InstructionOperand * operand) [inline]
Definition at line 242 of file code-generator-arm64.cc.
                                                   {
    Constant constant = ToConstant(operand);
    switch (constant.type()) {
      case Constant::kInt32:
        return Operand(constant.ToInt32(), constant.rmode());
      case Constant::kInt64:
        return Operand(constant.ToInt64(), constant.rmode());
      case Constant::kFloat32:
        return Operand::EmbeddedNumber(constant.ToFloat32());
      case Constant::kFloat64:
        return Operand::EmbeddedNumber(constant.ToFloat64().value());
      case Constant::kExternalReference:
        return Operand(constant.ToExternalReference());
      case Constant::kCompressedHeapObject: {
        RootIndex root_index;
        if (gen_->isolate()->roots_table().IsRootHandle(constant.ToHeapObject(),
                                                        &root_index)) {
          CHECK(COMPRESS_POINTERS_BOOL);
          CHECK(V8_STATIC_ROOTS_BOOL || !gen_->isolate()->bootstrapper());
          Tagged_t ptr =
              MacroAssemblerBase::ReadOnlyRootPtr(root_index, gen_->isolate());
          CHECK(Assembler::IsImmAddSub(ptr));
          return Immediate(ptr);
        }
        return Operand(constant.ToHeapObject());
      }
      case Constant::kHeapObject:
        return Operand(constant.ToHeapObject());
      case Constant::kRpoNumber:
        UNREACHABLE(); // TODO(dcarney): RPO immediates on arm64.
    }
    UNREACHABLE();
  }
References v8::internal::Isolate::bootstrapper(), CHECK, COMPRESS_POINTERS_BOOL, v8::internal::Operand::EmbeddedNumber(), v8::internal::compiler::InstructionOperandConverter::gen_, v8::internal::Assembler::IsImmAddSub(), v8::internal::compiler::CodeGenerator::isolate(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::compiler::Constant::kExternalReference, v8::internal::compiler::Constant::kFloat32, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kHeapObject, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::Constant::kRpoNumber, v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::compiler::Constant::rmode(), v8::internal::Isolate::roots_table(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToExternalReference(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToHeapObject(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToInt64(), v8::internal::compiler::Constant::type(), v8::internal::UNREACHABLE(), V8_STATIC_ROOTS_BOOL, and v8::base::Double::value().
Referenced by ToOperand(), and ToOperand32().
ToMemOperand()
MemOperand v8::internal::compiler::Arm64OperandConverter::ToMemOperand (InstructionOperand * op, MacroAssembler * masm) const [inline]
Definition at line 277 of file code-generator-arm64.cc.
                                                                              {
    DCHECK_NOT_NULL(op);
    DCHECK(op->IsStackSlot() || op->IsFPStackSlot());
    return SlotToMemOperand(AllocatedOperand::cast(op)->index(), masm);
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and SlotToMemOperand().
ToOperand()
Operand v8::internal::compiler::Arm64OperandConverter::ToOperand (InstructionOperand * op) [inline]
Definition at line 228 of file code-generator-arm64.cc.
                                            {
    if (op->IsRegister()) {
      return Operand(ToRegister(op));
    }
    return ToImmediate(op);
  }
References v8::internal::compiler::InstructionOperand::IsRegister(), ToImmediate(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
Referenced by InputOperand().
ToOperand32()
Operand v8::internal::compiler::Arm64OperandConverter::ToOperand32 (InstructionOperand * op) [inline]
Definition at line 235 of file code-generator-arm64.cc.
                                              {
    if (op->IsRegister()) {
      return Operand(ToRegister(op).W());
    }
    return ToImmediate(op);
  }
References v8::internal::compiler::InstructionOperand::IsRegister(), ToImmediate(), v8::internal::compiler::InstructionOperandConverter::ToRegister(), and v8::internal::W.
Referenced by InputOperand32().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/arm64/code-generator-arm64.cc