v8::internal::maglev::CheckInt32Condition Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckInt32Condition (uint64_t bitfield, AssertCondition condition, DeoptimizeReason reason)
Input & left_input ()
Input & right_input ()
AssertCondition condition () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::EagerDeopt()
static constexpr Base::InputTypes kInputTypes
static constexpr int kLeftIndex = 0
static constexpr int kRightIndex = 1
Private Types
using Base = FixedInputNodeT< 2, CheckInt32Condition >
using ConditionField = ReasonField::Next< AssertCondition, base::bits::WhichPowerOfTwo< size_t >(base::bits::RoundUpToPowerOfTwo32(kNumAssertConditions))>
Additional Inherited Members
Detailed Description
Definition at line 7502 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckInt32Condition::Base = FixedInputNodeT<2, CheckInt32Condition> [private]
Definition at line 7503 of file maglev-ir.h.
ConditionField
using v8::internal::maglev::CheckInt32Condition::ConditionField = ReasonField::Next<AssertCondition, base::bits::WhichPowerOfTwo<size_t>(base::bits::RoundUpToPowerOfTwo32(kNumAssertConditions))> [private]
Definition at line 7533 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckInt32Condition()
v8::internal::maglev::CheckInt32Condition::CheckInt32Condition (uint64_t bitfield, AssertCondition condition, DeoptimizeReason reason) [inline], [explicit]
Definition at line 7506 of file maglev-ir.h.
      : Base(bitfield | ConditionField::encode(condition) |
             ReasonField::encode(reason)) {}
Member Function Documentation
condition()
AssertCondition v8::internal::maglev::CheckInt32Condition::condition () const [inline]
Definition at line 7520 of file maglev-ir.h.
                                    {
    return ConditionField::decode(bitfield());
  }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CheckInt32Condition::GenerateCode (MaglevAssembler * , const ProcessingState &)
left_input()
Input& v8::internal::maglev::CheckInt32Condition::left_input () [inline]
Definition at line 7517 of file maglev-ir.h.
{ return input(kLeftIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::CheckInt32Condition::options () const [inline]
Definition at line 7528 of file maglev-ir.h.
{ return std::tuple{condition(), deoptimize_reason()}; }
PrintParams()
void v8::internal::maglev::CheckInt32Condition::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8137 of file maglev-ir.cc.
                                                               {
  os << "(" << condition() << ", " << deoptimize_reason() << ")";
}
References condition().
right_input()
Input& v8::internal::maglev::CheckInt32Condition::right_input () [inline]
Definition at line 7518 of file maglev-ir.h.
{ return input(kRightIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::CheckInt32Condition::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckInt32Condition::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kInt32, ValueRepresentation::kInt32}
Definition at line 7512 of file maglev-ir.h.
kLeftIndex
constexpr int v8::internal::maglev::CheckInt32Condition::kLeftIndex = 0 [static], [constexpr]
Definition at line 7515 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckInt32Condition::kProperties = OpProperties::EagerDeopt() [static], [constexpr]
Definition at line 7511 of file maglev-ir.h.
kRightIndex
constexpr int v8::internal::maglev::CheckInt32Condition::kRightIndex = 1 [static], [constexpr]
Definition at line 7516 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc