v8::internal::compiler::WasmGraphBuilder Class Reference
#include <wasm-compiler.h>
Public Types
enum ParameterMode { kInstanceParameterMode
, kWasmImportDataMode
, kJSFunctionAbiMode
, kNoSpecialParameterMode
 }
Public Member Functions
V8_EXPORT_PRIVATE WasmGraphBuilder (wasm::CompilationEnv *env, Zone *zone, MachineGraph *mcgraph, const wasm::FunctionSig *sig, compiler::SourcePositionTable *spt, ParameterMode parameter_mode, Isolate *isolate, wasm::WasmEnabledFeatures enabled_features, const wasm::CanonicalSig *wrapper_sig=nullptr)
V8_EXPORT_PRIVATE ~WasmGraphBuilder ()
bool TryWasmInlining (int fct_index, wasm::NativeModule *native_module, int inlining_id)
void Start (unsigned params)
Node * Param (int index, const char *debug_name=nullptr)
void TerminateThrow (Node *effect, Node *control)
Node * Int32Constant (int32_t value)
Node * Return (base::Vector< Node * > nodes)
template<typename... Nodes>
Node * Return (Node *fst, Nodes *... more)
Node * effect ()
Node * control ()
Node * SetEffect (Node *node)
Node * SetControl (Node *node)
void SetEffectControl (Node *effect, Node *control)
Node * SetEffectControl (Node *effect_and_control)
Node * SetType (Node *node, wasm::ValueType type)
V8_EXPORT_PRIVATE void LowerInt64 (Signature< MachineRepresentation > *sig)
V8_EXPORT_PRIVATE void LowerInt64 (wasm::CallOrigin origin)
void SetSourcePosition (Node *node, wasm::WasmCodePosition position)
Node * IsNull (Node *object, wasm::ValueType type)
Node * TypeGuard (Node *value, wasm::ValueType type)
bool has_simd () const
MachineGraph * mcgraph ()
TFGraph * graph ()
Zone * graph_zone ()
Protected Member Functions
Node * NoContextConstant ()
Node * BuildLoadIsolateRoot ()
Node * UndefinedValue ()
const Operator * GetSafeLoadOperator (int offset, wasm::ValueTypeBase type)
Node * BuildSafeStore (int offset, wasm::ValueTypeBase type, Node *arg_buffer, Node *value, Node *effect, Node *control)
Node * BuildCallNode (size_t param_count, base::Vector< Node * > args, wasm::WasmCodePosition position, Node *instance_node, const Operator *op, Node *frame_state=nullptr)
template<typename T >
Node * BuildWasmCall (const Signature< T > *sig, base::Vector< Node * > args, base::Vector< Node * > rets, wasm::WasmCodePosition position, Node *implicit_first_arg, bool indirect, Node *frame_state=nullptr)
Node * BuildCallToRuntime (Runtime::FunctionId f, Node **parameters, int parameter_count)
Node * BuildCallToRuntimeWithContext (Runtime::FunctionId f, Node *js_context, Node **parameters, int parameter_count)
TrapId GetTrapIdForTrap (wasm::TrapReason reason)
void BuildModifyThreadInWasmFlag (bool new_value)
void BuildModifyThreadInWasmFlagHelper (Node *thread_in_wasm_flag_address, bool new_value)
Node * BuildChangeInt64ToBigInt (Node *input, StubCallMode stub_mode)
void Assert (Node *condition, AbortReason abort_reason)
Protected Attributes
std::unique_ptr< WasmGraphAssembler > gasm_
Zone *const zone_
MachineGraph *const mcgraph_
wasm::CompilationEnv *const env_
wasm::WasmEnabledFeatures enabled_features_
Node ** parameters_
SetOncePointer< Node > stack_check_code_node_
SetOncePointer< const Operator > stack_check_call_operator_
bool has_simd_ = false
bool needs_stack_check_ = false
const wasm::FunctionSig *const function_sig_
const wasm::CanonicalSig *const wrapper_sig_ {nullptr}
compiler::WasmDecorator * decorator_ = nullptr
compiler::SourcePositionTable *const source_position_table_ = nullptr
int inlining_id_ = -1
const ParameterMode parameter_mode_
Isolate *const isolate_
SetOncePointer< Node > instance_data_node_
NullCheckStrategy null_check_strategy_
int cached_memory_index_ = kNoCachedMemoryIndex
Static Protected Attributes
static constexpr int kNoCachedMemoryIndex = -1
Detailed Description
Definition at line 133 of file wasm-compiler.h.
Member Enumeration Documentation
ParameterMode
enum v8::internal::compiler::WasmGraphBuilder::ParameterMode
Enumerator
kInstanceParameterMode
kWasmImportDataMode
kJSFunctionAbiMode
kNoSpecialParameterMode
Definition at line 136 of file wasm-compiler.h.
                     {
    // Normal wasm functions pass the instance as an implicit first parameter.
    kInstanceParameterMode,
    // For Wasm-to-JS and C-API wrappers, a {WasmImportData} object is
    // passed as first parameter.
    kWasmImportDataMode,
    // For JS-to-Wasm wrappers (which are JS functions), we load the Wasm
    // instance from the JS function data. The generated code objects live on
    // the JS heap, so those compilation pass an isolate.
    kJSFunctionAbiMode,
    // The JS-to-JS wrapper does not have an associated instance.
    // The C-entry stub uses a custom ABI (see {CWasmEntryParameters}).
    kNoSpecialParameterMode
  };
Constructor & Destructor Documentation
WasmGraphBuilder()
v8::internal::compiler::WasmGraphBuilder::WasmGraphBuilder (wasm::CompilationEnv * env, Zone * zone, MachineGraph * mcgraph, const wasm::FunctionSig * sig, compiler::SourcePositionTable * spt, ParameterMode parameter_mode, Isolate * isolate, wasm::WasmEnabledFeatures enabled_features, const wasm::CanonicalSig * wrapper_sig = nullptr)
Definition at line 97 of file wasm-compiler.cc.
    : gasm_(std::make_unique<WasmGraphAssembler>(mcgraph, zone)),
      zone_(zone),
      mcgraph_(mcgraph),
      env_(env),
      enabled_features_(enabled_features),
      has_simd_(sig ? ContainsSimd(sig) : ContainsSimd(wrapper_sig)),
      function_sig_(sig),
      wrapper_sig_(wrapper_sig),
      source_position_table_(source_position_table),
      parameter_mode_(parameter_mode),
      isolate_(isolate),
      null_check_strategy_(trap_handler::IsTrapHandlerEnabled() &&
                                   V8_STATIC_ROOTS_BOOL
                               ? NullCheckStrategy::kTrapHandler
                               : NullCheckStrategy::kExplicit) {
  // This code is only used
  // - for compiling certain wrappers (wasm-to-fast API, C-wasm-entry), and
  // - for inlining js-to-wasm wrappers into Turbofan-compile JS functions.
  CHECK(parameter_mode != ParameterMode::kInstanceParameterMode);
  // There are two kinds of isolate-specific code: JS-to-JS wrappers (passing
  // kNoSpecialParameterMode) and JS-to-Wasm wrappers (passing
  // kJSFunctionAbiMode).
  DCHECK_IMPLIES(isolate != nullptr,
                 parameter_mode_ == kJSFunctionAbiMode ||
                     parameter_mode_ == kNoSpecialParameterMode);
  DCHECK_IMPLIES(env && env->module &&
                     std::any_of(env->module->memories.begin(),
                                 env->module->memories.end(),
                                 [](auto& memory) {
                                   return memory.bounds_checks ==
                                          wasm::kTrapHandler;
                                 }),
                 trap_handler::IsTrapHandlerEnabled());
  DCHECK_NOT_NULL(mcgraph_);
}
References v8::base::any_of(), CHECK, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::trap_handler::IsTrapHandlerEnabled(), v8::internal::compiler::kExplicit, kJSFunctionAbiMode, kNoSpecialParameterMode, mcgraph_, v8::internal::wasm::WasmModule::memories, v8::internal::wasm::CompilationEnv::module, and parameter_mode_.
 WasmGraphBuilder()
v8::internal::compiler::WasmGraphBuilder::~WasmGraphBuilder () [default]
Member Function Documentation
Assert()
void v8::internal::compiler::WasmGraphBuilder::Assert (Node * condition, AbortReason abort_reason) [protected]
Definition at line 607 of file wasm-compiler.cc.
                                                                       {
  if (!v8_flags.debug_code) return;
  Diamond check(graph(), mcgraph()->common(), condition, BranchHint::kTrue);
  check.Chain(control());
  SetControl(check.if_false);
  Node* message_id = gasm_->NumberConstant(static_cast<int32_t>(abort_reason));
  Node* old_effect = effect();
  Node* call = BuildCallToRuntimeWithContext(
      Runtime::kAbort, NoContextConstant(), &message_id, 1);
  check.merge->ReplaceInput(1, call);
  SetEffectControl(check.EffectPhi(old_effect, effect()), check.merge);
}
References BuildCallToRuntimeWithContext(), v8::internal::compiler::Diamond::Chain(), control(), effect(), v8::internal::compiler::Diamond::EffectPhi(), gasm_, graph(), v8::internal::compiler::Diamond::if_false, v8::internal::kTrue, mcgraph(), v8::internal::compiler::Diamond::merge, NoContextConstant(), v8::internal::compiler::Node::ReplaceInput(), SetControl(), SetEffectControl(), and v8::internal::v8_flags.
Referenced by BuildModifyThreadInWasmFlagHelper(), and Start().
BuildCallNode()
Node * v8::internal::compiler::WasmGraphBuilder::BuildCallNode (size_t param_count, base::Vector< Node * > args, wasm::WasmCodePosition position, Node * instance_node, const Operator * op, Node * frame_state = nullptr) [protected]
Definition at line 345 of file wasm-compiler.cc.
                                                                             {
  needs_stack_check_ = true;
  const size_t has_frame_state = frame_state != nullptr ? 1 : 0;
  const size_t extra = 3; // instance_node, effect, and control.
  const size_t count = 1 + param_count + extra + has_frame_state;
  // Reallocate the buffer to make space for extra inputs.
  base::SmallVector<Node*, 16 + extra> inputs(count);
  DCHECK_EQ(1 + param_count, args.size());
  // Make room for the first argument at index 1, just after code.
  inputs[0] = args[0]; // code
  inputs[1] = implicit_first_arg;
  if (param_count > 0) {
    memcpy(&inputs[2], &args[1], param_count * sizeof(Node*));
  }
  // Add effect and control inputs.
  if (has_frame_state != 0) inputs[param_count + 2] = frame_state;
  inputs[param_count + has_frame_state + 2] = effect();
  inputs[param_count + has_frame_state + 3] = control();
  Node* call = graph()->NewNode(op, static_cast<int>(count), inputs.begin());
  // Return calls have no effect output. Other calls are the new effect node.
  if (op->EffectOutputCount() > 0) SetEffect(call);
  DCHECK(position == wasm::kNoCodePosition || position > 0);
  if (position > 0) SetSourcePosition(call, position);
  return call;
}
References v8::base::args, v8::base::SmallVector< T, kSize, Allocator >::begin(), control(), v8::internal::DCHECK(), DCHECK_EQ, effect(), v8::internal::compiler::Operator::EffectOutputCount(), graph(), v8::internal::wasm::kNoCodePosition, needs_stack_check_, v8::internal::compiler::TFGraph::NewNode(), SetEffect(), and SetSourcePosition().
Referenced by BuildWasmCall().
BuildCallToRuntime()
Node * v8::internal::compiler::WasmGraphBuilder::BuildCallToRuntime (Runtime::FunctionId f, Node ** parameters, int parameter_count) [protected]
Definition at line 454 of file wasm-compiler.cc.
                                                                {
  return BuildCallToRuntimeWithContext(f, NoContextConstant(), parameters,
                                       parameter_count);
}
References BuildCallToRuntimeWithContext(), and NoContextConstant().
BuildCallToRuntimeWithContext()
Node * v8::internal::compiler::WasmGraphBuilder::BuildCallToRuntimeWithContext (Runtime::FunctionId f, Node * js_context, Node ** parameters, int parameter_count) [protected]
Definition at line 417 of file wasm-compiler.cc.
                                                                           {
  const Runtime::Function* fun = Runtime::FunctionForId(f);
  auto call_descriptor = Linkage::GetRuntimeCallDescriptor(
      mcgraph()->zone(), f, fun->nargs, Operator::kNoProperties,
      CallDescriptor::kNoFlags);
  // The CEntryStub is loaded from the IsolateRoot so that generated code is
  // Isolate independent. At the moment this is only done for CEntryStub(1).
  Node* isolate_root = BuildLoadIsolateRoot();
  DCHECK_EQ(1, fun->result_size);
  auto centry_id = Builtin::kWasmCEntry;
  int builtin_slot_offset = IsolateData::BuiltinSlotOffset(centry_id);
  Node* centry_stub =
      gasm_->Load(MachineType::Pointer(), isolate_root, builtin_slot_offset);
  // TODO(titzer): allow arbitrary number of runtime arguments
  // At the moment we only allow 5 parameters. If more parameters are needed,
  // increase this constant accordingly.
  static const int kMaxParams = 5;
  DCHECK_GE(kMaxParams, parameter_count);
  Node* inputs[kMaxParams + 6];
  int count = 0;
  inputs[count++] = centry_stub;
  for (int i = 0; i < parameter_count; i++) {
    inputs[count++] = parameters[i];
  }
  inputs[count++] =
      mcgraph()->ExternalConstant(ExternalReference::Create(f)); // ref
  inputs[count++] = Int32Constant(fun->nargs); // arity
  inputs[count++] = js_context; // js_context
  inputs[count++] = effect();
  inputs[count++] = control();
  return gasm_->Call(call_descriptor, count, inputs);
}
References BuildLoadIsolateRoot(), v8::internal::IsolateData::BuiltinSlotOffset(), control(), v8::internal::ExternalReference::Create(), DCHECK_EQ, DCHECK_GE, effect(), v8::internal::compiler::MachineGraph::ExternalConstant(), v8::internal::Runtime::FunctionForId(), gasm_, v8::internal::compiler::Linkage::GetRuntimeCallDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, Int32Constant(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, mcgraph(), v8::internal::Runtime::Function::nargs, v8::internal::MachineType::Pointer(), and v8::internal::Runtime::Function::result_size.
Referenced by Assert(), and BuildCallToRuntime().
BuildChangeInt64ToBigInt()
Node * v8::internal::compiler::WasmGraphBuilder::BuildChangeInt64ToBigInt (Node * input, StubCallMode stub_mode) [protected]
Definition at line 550 of file wasm-compiler.cc.
                                                                         {
  if (mcgraph()->machine()->Is64()) {
    return gasm_->CallBuiltin(Builtin::kI64ToBigInt, Operator::kEliminatable,
                              input);
  } else {
    Node* low_word = gasm_->TruncateInt64ToInt32(input);
    Node* high_word = gasm_->TruncateInt64ToInt32(
        gasm_->Word64Shr(input, gasm_->Int32Constant(32)));
    return gasm_->CallBuiltin(Builtin::kI32PairToBigInt,
                              Operator::kEliminatable, low_word, high_word);
  }
}
References gasm_, v8::internal::Is64(), v8::internal::compiler::Operator::kEliminatable, and mcgraph().
BuildLoadIsolateRoot()
Node * v8::internal::compiler::WasmGraphBuilder::BuildLoadIsolateRoot () [protected]
Definition at line 270 of file wasm-compiler.cc.
                                             {
  return isolate_ ? mcgraph()->IntPtrConstant(isolate_->isolate_root())
                  : gasm_->LoadRootRegister();
}
References gasm_, v8::internal::compiler::MachineGraph::IntPtrConstant(), isolate_, v8::internal::Isolate::isolate_root(), and mcgraph().
Referenced by BuildCallToRuntimeWithContext(), and BuildModifyThreadInWasmFlag().
BuildModifyThreadInWasmFlag()
void v8::internal::compiler::WasmGraphBuilder::BuildModifyThreadInWasmFlag (bool new_value) [protected]
Definition at line 596 of file wasm-compiler.cc.
                                                                 {
  if (!trap_handler::IsTrapHandlerEnabled()) return;
  Node* isolate_root = BuildLoadIsolateRoot();
  Node* thread_in_wasm_flag_address =
      gasm_->Load(MachineType::Pointer(), isolate_root,
                  Isolate::thread_in_wasm_flag_address_offset());
  BuildModifyThreadInWasmFlagHelper(thread_in_wasm_flag_address, new_value);
}
References BuildLoadIsolateRoot(), BuildModifyThreadInWasmFlagHelper(), gasm_, v8::internal::trap_handler::IsTrapHandlerEnabled(), v8::internal::MachineType::Pointer(), and v8::internal::Isolate::thread_in_wasm_flag_address_offset().
BuildModifyThreadInWasmFlagHelper()
void v8::internal::compiler::WasmGraphBuilder::BuildModifyThreadInWasmFlagHelper (Node * thread_in_wasm_flag_address, bool new_value) [protected]
Definition at line 580 of file wasm-compiler.cc.
                                                       {
  if (v8_flags.debug_code) {
    Node* flag_value =
        gasm_->Load(MachineType::Int32(), thread_in_wasm_flag_address, 0);
    Node* check =
        gasm_->Word32Equal(flag_value, Int32Constant(new_value ? 0 : 1));
    Assert(check, new_value ? AbortReason::kUnexpectedThreadInWasmSet
                            : AbortReason::kUnexpectedThreadInWasmUnset);
  }
  gasm_->Store({MachineRepresentation::kWord32, kNoWriteBarrier},
               thread_in_wasm_flag_address, 0,
               Int32Constant(new_value ? 1 : 0));
}
References Assert(), gasm_, v8::internal::MachineType::Int32(), Int32Constant(), v8::internal::compiler::kNoWriteBarrier, v8::internal::kWord32, and v8::internal::v8_flags.
Referenced by BuildModifyThreadInWasmFlag().
BuildSafeStore()
Node * v8::internal::compiler::WasmGraphBuilder::BuildSafeStore (int offset, wasm::ValueTypeBase type, Node * arg_buffer, Node * value, Node * effect, Node * control) [protected]
Definition at line 477 of file wasm-compiler.cc.
                                                                    {
  int alignment = offset % type.value_kind_size();
  MachineRepresentation rep = type.machine_representation();
  if (COMPRESS_POINTERS_BOOL && IsAnyTagged(rep)) {
    // We are storing tagged value to off-heap location, so we need to store
    // it as a full word otherwise we will not be able to decompress it.
    rep = MachineType::PointerRepresentation();
    value = effect = graph()->NewNode(
        mcgraph()->machine()->BitcastTaggedToWord(), value, effect, control);
  }
  if (alignment == 0 || mcgraph()->machine()->UnalignedStoreSupported(rep)) {
    StoreRepresentation store_rep(rep, WriteBarrierKind::kNoWriteBarrier);
    return graph()->NewNode(mcgraph()->machine()->Store(store_rep), arg_buffer,
                            Int32Constant(offset), value, effect, control);
  }
  UnalignedStoreRepresentation store_rep(rep);
  return graph()->NewNode(mcgraph()->machine()->UnalignedStore(store_rep),
                          arg_buffer, Int32Constant(offset), value, effect,
                          control);
}
References COMPRESS_POINTERS_BOOL, control(), effect(), graph(), Int32Constant(), v8::internal::IsAnyTagged(), v8::internal::compiler::kNoWriteBarrier, mcgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::MachineType::PointerRepresentation(), v8::internal::wasm::liftoff::Store(), v8::internal::tracing::type, and v8::internal::value.
BuildWasmCall()
template<typename T >
Node * v8::internal::compiler::WasmGraphBuilder::BuildWasmCall (const Signature< T > * sig, base::Vector< Node * > args, base::Vector< Node * > rets, wasm::WasmCodePosition position, Node * implicit_first_arg, bool indirect, Node * frame_state = nullptr) [protected]
Definition at line 381 of file wasm-compiler.cc.
                                                         {
  WasmCallKind call_kind = indirect ? kWasmIndirectFunction : kWasmFunction;
  CallDescriptor* call_descriptor = GetWasmCallDescriptor(
      mcgraph()->zone(), sig, call_kind, frame_state != nullptr);
  const Operator* op = mcgraph()->common()->Call(call_descriptor);
  Node* call = BuildCallNode(sig->parameter_count(), args, position,
                             implicit_first_arg, op, frame_state);
  // TODO(manoskouk): These assume the call has control and effect outputs.
  DCHECK_GT(op->ControlOutputCount(), 0);
  DCHECK_GT(op->EffectOutputCount(), 0);
  SetEffectControl(call);
  size_t ret_count = sig->return_count();
  if (ret_count == 0) return call; // No return value.
  DCHECK_EQ(ret_count, rets.size());
  if (ret_count == 1) {
    // Only a single return value.
    rets[0] = call;
  } else {
    // Create projections for all return values.
    for (size_t i = 0; i < ret_count; i++) {
      rets[i] = graph()->NewNode(mcgraph()->common()->Projection(i), call,
                                 graph()->start());
    }
  }
  return call;
}
References v8::base::args, BuildCallNode(), v8::internal::compiler::CommonOperatorBuilder::Call(), v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::Operator::ControlOutputCount(), DCHECK_EQ, DCHECK_GT, v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::GetWasmCallDescriptor(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::kWasmFunction, v8::internal::compiler::kWasmIndirectFunction, mcgraph(), v8::internal::compiler::TFGraph::NewNode(), SetEffectControl(), v8::internal::sig, and v8::base::Vector< T >::size().
control()
Node * v8::internal::compiler::WasmGraphBuilder::control ()
Definition at line 329 of file wasm-compiler.cc.
{ return gasm_->control(); }
References gasm_.
Referenced by Assert(), BuildCallNode(), BuildCallToRuntimeWithContext(), BuildSafeStore(), Return(), SetEffect(), SetEffectControl(), TerminateThrow(), and TypeGuard().
effect()
Node * v8::internal::compiler::WasmGraphBuilder::effect ()
Definition at line 327 of file wasm-compiler.cc.
{ return gasm_->effect(); }
References gasm_.
Referenced by Assert(), BuildCallNode(), BuildCallToRuntimeWithContext(), BuildSafeStore(), Return(), SetControl(), SetEffectControl(), TerminateThrow(), and TypeGuard().
GetSafeLoadOperator()
const Operator * v8::internal::compiler::WasmGraphBuilder::GetSafeLoadOperator (int offset, wasm::ValueTypeBase type) [protected]
Definition at line 461 of file wasm-compiler.cc.
                                        {
  int alignment = offset % type.value_kind_size();
  MachineType mach_type = type.machine_type();
  if (COMPRESS_POINTERS_BOOL && mach_type.IsTagged()) {
    // We are loading tagged value from off-heap location, so we need to load
    // it as a full word otherwise we will not be able to decompress it.
    mach_type = MachineType::Pointer();
  }
  if (alignment == 0 || mcgraph()->machine()->UnalignedLoadSupported(
                            type.machine_representation())) {
    return mcgraph()->machine()->Load(mach_type);
  }
  return mcgraph()->machine()->UnalignedLoad(mach_type);
}
References COMPRESS_POINTERS_BOOL, v8::internal::MachineType::IsTagged(), v8::internal::compiler::MachineOperatorBuilder::Load(), v8::internal::compiler::MachineGraph::machine(), mcgraph(), v8::internal::MachineType::Pointer(), v8::internal::tracing::type, and v8::internal::compiler::MachineOperatorBuilder::UnalignedLoad().
GetTrapIdForTrap()
TrapId v8::internal::compiler::WasmGraphBuilder::GetTrapIdForTrap (wasm::TrapReason reason) [protected]
Definition at line 284 of file wasm-compiler.cc.
                                                               {
  switch (reason) {
#define TRAPREASON_TO_TRAPID(name) \
  case wasm::k##name: \
    static_assert(static_cast<int>(TrapId::k##name) == \
                      static_cast<int>(Builtin::kThrowWasm##name), \
                  "trap id mismatch"); \
    return TrapId::k##name;
    FOREACH_WASM_TRAPREASON(TRAPREASON_TO_TRAPID)
#undef TRAPREASON_TO_TRAPID
    default:
      UNREACHABLE();
  }
}
References FOREACH_WASM_TRAPREASON, TRAPREASON_TO_TRAPID, and v8::internal::UNREACHABLE().
graph()
TFGraph * v8::internal::compiler::WasmGraphBuilder::graph ()
Definition at line 500 of file wasm-compiler.cc.
{ return mcgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and mcgraph().
Referenced by Assert(), BuildCallNode(), BuildSafeStore(), BuildWasmCall(), graph_zone(), LowerInt64(), Param(), Return(), Start(), TerminateThrow(), TryWasmInlining(), and TypeGuard().
graph_zone()
Zone * v8::internal::compiler::WasmGraphBuilder::graph_zone ()
Definition at line 502 of file wasm-compiler.cc.
{ return graph()->zone(); }
References graph(), and v8::internal::compiler::TFGraph::zone().
Referenced by SetType().
has_simd()
bool v8::internal::compiler::WasmGraphBuilder::has_simd () const [inline]
Definition at line 204 of file wasm-compiler.h.
{ return has_simd_; }
Int32Constant()
Node * v8::internal::compiler::WasmGraphBuilder::Int32Constant (int32_t value)
Definition at line 275 of file wasm-compiler.cc.
                                                   {
  return mcgraph()->Int32Constant(value);
}
References v8::internal::compiler::MachineGraph::Int32Constant(), mcgraph(), and v8::internal::value.
Referenced by BuildCallToRuntimeWithContext(), BuildModifyThreadInWasmFlagHelper(), BuildSafeStore(), and Return().
IsNull()
Node * v8::internal::compiler::WasmGraphBuilder::IsNull (Node * object, wasm::ValueType type)
Definition at line 317 of file wasm-compiler.cc.
                                                               {
  // This version is for Wasm functions (i.e. not wrappers):
  // - they use module-specific types
  // - they go through a lowering phase later
  // Both points are different in wrappers, see
  // WasmWrapperGraphBuilder::IsNull().
  DCHECK_EQ(parameter_mode_, kInstanceParameterMode);
  return gasm_->IsNull(object, type);
}
References DCHECK_EQ, gasm_, kInstanceParameterMode, parameter_mode_, and v8::internal::tracing::type.
LowerInt64() [1/2]
void v8::internal::compiler::WasmGraphBuilder::LowerInt64 (Signature< MachineRepresentation > * sig)
Definition at line 535 of file wasm-compiler.cc.
                                                                       {
  if (mcgraph()->machine()->Is64()) return;
  Int64Lowering r(mcgraph()->graph(), mcgraph()->machine(), mcgraph()->common(),
                  gasm_->simplified(), mcgraph()->zone(), sig);
  r.LowerGraph();
}
References gasm_, graph(), v8::internal::Is64(), v8::internal::compiler::Int64Lowering::LowerGraph(), mcgraph(), and v8::internal::sig.
Referenced by LowerInt64().
LowerInt64() [2/2]
void v8::internal::compiler::WasmGraphBuilder::LowerInt64 (wasm::CallOrigin origin)
Definition at line 542 of file wasm-compiler.cc.
                                                       {
  Signature<MachineRepresentation>* machine_sig =
      function_sig_ != nullptr
          ? CreateMachineSignature(mcgraph()->zone(), function_sig_, origin)
          : CreateMachineSignature(mcgraph()->zone(), wrapper_sig_, origin);
  LowerInt64(machine_sig);
}
References v8::internal::compiler::CreateMachineSignature(), function_sig_, LowerInt64(), mcgraph(), and wrapper_sig_.
mcgraph()
MachineGraph* v8::internal::compiler::WasmGraphBuilder::mcgraph () [inline]
Definition at line 206 of file wasm-compiler.h.
{ return mcgraph_; }
Referenced by Assert(), BuildCallToRuntimeWithContext(), BuildChangeInt64ToBigInt(), BuildLoadIsolateRoot(), BuildSafeStore(), BuildWasmCall(), GetSafeLoadOperator(), graph(), Int32Constant(), LowerInt64(), NoContextConstant(), Param(), Return(), Start(), TerminateThrow(), and TypeGuard().
NoContextConstant()
Node * v8::internal::compiler::WasmGraphBuilder::NoContextConstant () [protected]
Definition at line 266 of file wasm-compiler.cc.
                                          {
  return mcgraph()->IntPtrConstant(0);
}
References v8::internal::compiler::MachineGraph::IntPtrConstant(), and mcgraph().
Referenced by Assert(), and BuildCallToRuntime().
Param()
Node * v8::internal::compiler::WasmGraphBuilder::Param (int index, const char * debug_name = nullptr)
Definition at line 247 of file wasm-compiler.cc.
                                                               {
  DCHECK_NOT_NULL(graph()->start());
  // Turbofan allows negative parameter indices.
  DCHECK_GE(index, kMinParameterIndex);
  int array_index = index - kMinParameterIndex;
  if (parameters_[array_index] == nullptr) {
    parameters_[array_index] = graph()->NewNode(
        mcgraph()->common()->Parameter(index, debug_name), graph()->start());
  }
  return parameters_[array_index];
}
References DCHECK_GE, DCHECK_NOT_NULL, graph(), v8::internal::index, v8::internal::kMinParameterIndex, mcgraph(), v8::internal::compiler::TFGraph::NewNode(), and parameters_.
Referenced by Start().
Return() [1/2]
Node * v8::internal::compiler::WasmGraphBuilder::Return (base::Vector< Node * > nodes)
Definition at line 299 of file wasm-compiler.cc.
                                                     {
  unsigned count = static_cast<unsigned>(vals.size());
  base::SmallVector<Node*, 8> buf(count + 3);
  // TODOC: What is the meaning of the 0-constant?
  buf[0] = Int32Constant(0);
  if (count > 0) {
    memcpy(buf.data() + 1, vals.begin(), sizeof(void*) * count);
  }
  buf[count + 1] = effect();
  buf[count + 2] = control();
  Node* ret = graph()->NewNode(mcgraph()->common()->Return(count), count + 3,
                               buf.data());
  gasm_->MergeControlToEnd(ret);
  return ret;
}
References v8::base::Vector< T >::begin(), control(), v8::base::SmallVector< T, kSize, Allocator >::data(), effect(), gasm_, graph(), Int32Constant(), mcgraph(), v8::internal::compiler::TFGraph::NewNode(), and v8::base::Vector< T >::size().
Return() [2/2]
template<typename... Nodes>
Node* v8::internal::compiler::WasmGraphBuilder::Return (Node * fst, Nodes *... more) [inline]
Definition at line 177 of file wasm-compiler.h.
                                          {
    Node* arr[] = {fst, more...};
    return Return(base::ArrayVector(arr));
  }
References v8::base::ArrayVector().
SetControl()
Node * v8::internal::compiler::WasmGraphBuilder::SetControl (Node * node)
Definition at line 336 of file wasm-compiler.cc.
                                             {
  SetEffectControl(effect(), node);
  return node;
}
References effect(), and SetEffectControl().
Referenced by Assert().
SetEffect()
Node * v8::internal::compiler::WasmGraphBuilder::SetEffect (Node * node)
Definition at line 331 of file wasm-compiler.cc.
                                            {
  SetEffectControl(node, control());
  return node;
}
References control(), and SetEffectControl().
Referenced by BuildCallNode(), and TypeGuard().
SetEffectControl() [1/2]
void v8::internal::compiler::WasmGraphBuilder::SetEffectControl (Node * effect, Node * control)
Definition at line 341 of file wasm-compiler.cc.
                                                                   {
  gasm_->InitializeEffectControl(effect, control);
}
References control(), effect(), and gasm_.
Referenced by Assert(), BuildWasmCall(), SetControl(), SetEffect(), and Start().
SetEffectControl() [2/2]
Node* v8::internal::compiler::WasmGraphBuilder::SetEffectControl (Node * effect_and_control) [inline]
Definition at line 187 of file wasm-compiler.h.
                                                   {
    SetEffectControl(effect_and_control, effect_and_control);
    return effect_and_control;
  }
SetSourcePosition()
void v8::internal::compiler::WasmGraphBuilder::SetSourcePosition (Node * node, wasm::WasmCodePosition position)
Definition at line 564 of file wasm-compiler.cc.
                                                                        {
  DCHECK_NE(position, wasm::kNoCodePosition);
  if (source_position_table_) {
    source_position_table_->SetSourcePosition(
        node, SourcePosition(position, inlining_id_));
  }
}
References DCHECK_NE, inlining_id_, v8::internal::wasm::kNoCodePosition, v8::internal::compiler::SourcePositionTable::SetSourcePosition(), and source_position_table_.
Referenced by BuildCallNode().
SetType()
Node * v8::internal::compiler::WasmGraphBuilder::SetType (Node * node, wasm::ValueType type)
Definition at line 621 of file wasm-compiler.cc.
                                                              {
  DCHECK_NOT_NULL(env_);
  if (!compiler::NodeProperties::IsTyped(node)) {
    compiler::NodeProperties::SetType(
        node, compiler::Type::Wasm(type, env_->module, graph_zone()));
  } else {
    // We might try to set the type twice since some nodes are cached in the
    // graph assembler, but we should never change the type.
    // The exception is imported strings support, which may special-case
    // values that are officially externref-typed as being known to be strings.
#if DEBUG
    static constexpr wasm::ValueType kRefExtern =
        wasm::kWasmExternRef.AsNonNull();
    DCHECK((compiler::NodeProperties::GetType(node).AsWasm().type == type) ||
           (enabled_features_.has_imported_strings() &&
            compiler::NodeProperties::GetType(node).AsWasm().type ==
                wasm::kWasmRefExternString &&
            (type == wasm::kWasmExternRef || type == kRefExtern)));
#endif
  }
  return node;
}
References v8::internal::wasm::IndependentHeapType::AsNonNull(), v8::internal::DCHECK(), DCHECK_NOT_NULL, enabled_features_, env_, v8::internal::compiler::NodeProperties::GetType(), graph_zone(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmRefExternString, v8::internal::wasm::CompilationEnv::module, v8::internal::compiler::NodeProperties::SetType(), and v8::internal::tracing::type.
Start()
void v8::internal::compiler::WasmGraphBuilder::Start (unsigned params)
Definition at line 200 of file wasm-compiler.cc.
                                            {
  Node* start = graph()->NewNode(mcgraph()->common()->Start(params));
  graph()->SetStart(start);
  SetEffectControl(start);
  // Initialize parameter nodes.
  parameters_ = zone_->AllocateArray<Node*>(params);
  for (unsigned i = 0; i < params; i++) {
    parameters_[i] = nullptr;
  }
  // Initialize instance node.
  switch (parameter_mode_) {
    case kInstanceParameterMode: {
      Node* param = Param(wasm::kWasmInstanceDataParameterIndex);
      if (v8_flags.debug_code) {
        Assert(gasm_->HasInstanceType(param, WASM_TRUSTED_INSTANCE_DATA_TYPE),
               AbortReason::kUnexpectedInstanceType);
      }
      instance_data_node_ = param;
      break;
    }
    case kWasmImportDataMode: {
      Node* param = Param(0);
      if (v8_flags.debug_code) {
        Assert(gasm_->HasInstanceType(param, WASM_IMPORT_DATA_TYPE),
               AbortReason::kUnexpectedInstanceType);
      }
      instance_data_node_ = gasm_->LoadProtectedPointerFromObject(
          param, wasm::ObjectAccess::ToTagged(
                     WasmImportData::kProtectedInstanceDataOffset));
      break;
    }
    case kJSFunctionAbiMode: {
      Node* param = Param(Linkage::kJSCallClosureParamIndex, "%closure");
      if (v8_flags.debug_code) {
        Assert(gasm_->HasInstanceType(param, JS_FUNCTION_TYPE),
               AbortReason::kUnexpectedInstanceType);
      }
      instance_data_node_ = gasm_->LoadExportedFunctionInstanceData(
          gasm_->LoadFunctionDataFromJSFunction(param));
      break;
    }
    case kNoSpecialParameterMode:
      break;
  }
  graph()->SetEnd(graph()->NewNode(mcgraph()->common()->End(0)));
}
References v8::internal::Zone::AllocateArray(), Assert(), gasm_, graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, instance_data_node_, kInstanceParameterMode, v8::internal::compiler::Linkage::kJSCallClosureParamIndex, kJSFunctionAbiMode, kNoSpecialParameterMode, kWasmImportDataMode, v8::internal::wasm::kWasmInstanceDataParameterIndex, mcgraph(), v8::internal::compiler::TFGraph::NewNode(), Param(), parameter_mode_, parameters_, SetEffectControl(), v8::internal::compiler::TFGraph::SetEnd(), v8::internal::compiler::TFGraph::SetStart(), v8::internal::wasm::ObjectAccess::ToTagged(), v8::internal::v8_flags, and zone_.
TerminateThrow()
void v8::internal::compiler::WasmGraphBuilder::TerminateThrow (Node * effect, Node * control)
Definition at line 259 of file wasm-compiler.cc.
                                                                 {
  Node* terminate =
      graph()->NewNode(mcgraph()->common()->Throw(), effect, control);
  gasm_->MergeControlToEnd(terminate);
  gasm_->InitializeEffectControl(nullptr, nullptr);
}
References control(), effect(), gasm_, graph(), mcgraph(), and v8::internal::compiler::TFGraph::NewNode().
TryWasmInlining()
bool v8::internal::compiler::WasmGraphBuilder::TryWasmInlining (int fct_index, wasm::NativeModule * native_module, int inlining_id)
Definition at line 145 of file wasm-compiler.cc.
                                                        {
#define TRACE(x) \
  do { \
    if (v8_flags.trace_turbo_inlining) { \
      StdoutStream() << x << "\n"; \
    } \
  } while (false)
  DCHECK(native_module->HasWireBytes());
  const wasm::WasmModule* module = native_module->module();
  const wasm::WasmFunction& inlinee = module->functions[fct_index];
  // TODO(mliedtke): What would be a proper maximum size?
  const uint32_t kMaxWasmInlineeSize = 30;
  if (inlinee.code.length() > kMaxWasmInlineeSize) {
    TRACE("- not inlining: function body is larger than max inlinee size ("
          << inlinee.code.length() << " > " << kMaxWasmInlineeSize << ")");
    return false;
  }
  if (inlinee.imported) {
    TRACE("- not inlining: function is imported");
    return false;
  }
  base::Vector<const uint8_t> bytes(native_module->wire_bytes().SubVector(
      inlinee.code.offset(), inlinee.code.end_offset()));
  bool is_shared = module->type(inlinee.sig_index).is_shared;
  const wasm::FunctionBody inlinee_body(inlinee.sig, inlinee.code.offset(),
                                        bytes.begin(), bytes.end(), is_shared);
  // If the inlinee was not validated before, do that now.
  if (V8_UNLIKELY(!module->function_was_validated(fct_index))) {
    wasm::WasmDetectedFeatures unused_detected_features;
    if (ValidateFunctionBody(graph()->zone(), enabled_features_, module,
                             &unused_detected_features, inlinee_body)
            .failed()) {
      // At this point we cannot easily raise a compilation error any more.
      // Since this situation is highly unlikely though, we just ignore this
      // inlinee and move on. The same validation error will be triggered
      // again when actually compiling the invalid function.
      TRACE("- not inlining: function body is invalid");
      return false;
    }
    module->set_function_validated(fct_index);
  }
  bool result = WasmIntoJSInliner::TryInlining(
      graph()->zone(), module, mcgraph_, inlinee_body, bytes,
      source_position_table_, inlining_id);
  TRACE((
      result
          ? "- inlining"
          : "- not inlining: function body contains unsupported instructions"));
  return result;
#undef TRACE
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::WasmFunction::code, v8::internal::DCHECK(), enabled_features_, v8::base::Vector< T >::end(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::WasmModule::function_was_validated(), v8::internal::wasm::WasmModule::functions, graph(), v8::internal::wasm::NativeModule::HasWireBytes(), v8::internal::wasm::WasmFunction::imported, v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::WireBytesRef::length(), mcgraph_, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::WireBytesRef::offset(), v8::base::internal::result, v8::internal::wasm::WasmModule::set_function_validated(), v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::WasmFunction::sig_index, source_position_table_, v8::base::Vector< T >::SubVector(), v8::internal::TRACE(), v8::internal::compiler::WasmIntoJSInliner::TryInlining(), v8::internal::wasm::WasmModule::type(), V8_UNLIKELY, v8::internal::wasm::ValidateFunctionBody(), and v8::internal::wasm::NativeModule::wire_bytes().
TypeGuard()
Node * v8::internal::compiler::WasmGraphBuilder::TypeGuard (Node * value, wasm::ValueType type)
Definition at line 573 of file wasm-compiler.cc.
                                                                 {
  DCHECK_NOT_NULL(env_);
  return SetEffect(graph()->NewNode(mcgraph()->common()->TypeGuard(Type::Wasm(
                                        type, env_->module, graph()->zone())),
                                    value, effect(), control()));
}
References control(), DCHECK_NOT_NULL, effect(), env_, graph(), mcgraph(), v8::internal::wasm::CompilationEnv::module, SetEffect(), v8::internal::tracing::type, and v8::internal::value.
UndefinedValue()
Node * v8::internal::compiler::WasmGraphBuilder::UndefinedValue () [protected]
Definition at line 279 of file wasm-compiler.cc.
                                       {
  return LOAD_ROOT(UndefinedValue, undefined_value);
}
References LOAD_ROOT.
Member Data Documentation
cached_memory_index_
int v8::internal::compiler::WasmGraphBuilder::cached_memory_index_ = kNoCachedMemoryIndex [protected]
Definition at line 278 of file wasm-compiler.h.
decorator_
compiler::WasmDecorator* v8::internal::compiler::WasmGraphBuilder::decorator_ = nullptr [protected]
Definition at line 269 of file wasm-compiler.h.
enabled_features_
wasm::WasmEnabledFeatures v8::internal::compiler::WasmGraphBuilder::enabled_features_ [protected]
Definition at line 256 of file wasm-compiler.h.
Referenced by SetType(), and TryWasmInlining().
env_
wasm::CompilationEnv* const v8::internal::compiler::WasmGraphBuilder::env_ [protected]
Definition at line 252 of file wasm-compiler.h.
Referenced by SetType(), and TypeGuard().
function_sig_
const wasm::FunctionSig* const v8::internal::compiler::WasmGraphBuilder::function_sig_ [protected]
Definition at line 266 of file wasm-compiler.h.
Referenced by LowerInt64().
gasm_
std::unique_ptr<WasmGraphAssembler> v8::internal::compiler::WasmGraphBuilder::gasm_ [protected]
Definition at line 249 of file wasm-compiler.h.
Referenced by Assert(), BuildCallToRuntimeWithContext(), BuildChangeInt64ToBigInt(), BuildLoadIsolateRoot(), BuildModifyThreadInWasmFlag(), BuildModifyThreadInWasmFlagHelper(), control(), effect(), IsNull(), LowerInt64(), Return(), SetEffectControl(), Start(), and TerminateThrow().
has_simd_
bool v8::internal::compiler::WasmGraphBuilder::has_simd_ = false [protected]
Definition at line 263 of file wasm-compiler.h.
inlining_id_
int v8::internal::compiler::WasmGraphBuilder::inlining_id_ = -1 [protected]
Definition at line 272 of file wasm-compiler.h.
Referenced by SetSourcePosition().
instance_data_node_
SetOncePointer<Node> v8::internal::compiler::WasmGraphBuilder::instance_data_node_ [protected]
Definition at line 275 of file wasm-compiler.h.
Referenced by Start().
isolate_
Isolate* const v8::internal::compiler::WasmGraphBuilder::isolate_ [protected]
Definition at line 274 of file wasm-compiler.h.
Referenced by BuildLoadIsolateRoot().
kNoCachedMemoryIndex
constexpr int v8::internal::compiler::WasmGraphBuilder::kNoCachedMemoryIndex = -1 [static], [constexpr], [protected]
Definition at line 277 of file wasm-compiler.h.
mcgraph_
MachineGraph* const v8::internal::compiler::WasmGraphBuilder::mcgraph_ [protected]
Definition at line 251 of file wasm-compiler.h.
Referenced by TryWasmInlining(), and WasmGraphBuilder().
needs_stack_check_
bool v8::internal::compiler::WasmGraphBuilder::needs_stack_check_ = false [protected]
Definition at line 264 of file wasm-compiler.h.
Referenced by BuildCallNode().
null_check_strategy_
NullCheckStrategy v8::internal::compiler::WasmGraphBuilder::null_check_strategy_ [protected]
Definition at line 276 of file wasm-compiler.h.
parameter_mode_
const ParameterMode v8::internal::compiler::WasmGraphBuilder::parameter_mode_ [protected]
Definition at line 273 of file wasm-compiler.h.
Referenced by IsNull(), Start(), and WasmGraphBuilder().
parameters_
Node** v8::internal::compiler::WasmGraphBuilder::parameters_ [protected]
Definition at line 258 of file wasm-compiler.h.
Referenced by Param(), and Start().
source_position_table_
compiler::SourcePositionTable* const v8::internal::compiler::WasmGraphBuilder::source_position_table_ = nullptr [protected]
Definition at line 271 of file wasm-compiler.h.
Referenced by SetSourcePosition(), and TryWasmInlining().
stack_check_call_operator_
SetOncePointer<const Operator> v8::internal::compiler::WasmGraphBuilder::stack_check_call_operator_ [protected]
Definition at line 261 of file wasm-compiler.h.
stack_check_code_node_
SetOncePointer<Node> v8::internal::compiler::WasmGraphBuilder::stack_check_code_node_ [protected]
Definition at line 260 of file wasm-compiler.h.
wrapper_sig_
const wasm::CanonicalSig* const v8::internal::compiler::WasmGraphBuilder::wrapper_sig_ {nullptr} [protected]
Definition at line 267 of file wasm-compiler.h.
Referenced by LowerInt64().
zone_
Zone* const v8::internal::compiler::WasmGraphBuilder::zone_ [protected]
Definition at line 250 of file wasm-compiler.h.
Referenced by Start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/wasm-compiler.h
/mnt/V8SourceCode/src/compiler/wasm-compiler.cc