v8::internal::torque::LanguageServerData Class Reference
#include <server-data.h>
Public Member Functions
LanguageServerData ()=default
Static Public Member Functions
static V8_EXPORT_PRIVATE void AddDefinition (SourcePosition token, SourcePosition definition)
static V8_EXPORT_PRIVATE std::optional< SourcePosition > FindDefinition (SourceId source, LineAndColumn pos)
static void SetGlobalContext (GlobalContext global_context)
static void SetTypeOracle (TypeOracle type_oracle)
static const Symbols & SymbolsForSourceId (SourceId id)
Private Member Functions
void PrepareAllDeclarableSymbols ()
Private Attributes
DefinitionsMap definitions_map_
SymbolsMap symbols_map_
std::unique_ptr< GlobalContext > global_context_
std::unique_ptr< TypeOracle > type_oracle_
Additional Inherited Members
Detailed Description
Definition at line 37 of file server-data.h.
Constructor & Destructor Documentation
LanguageServerData()
v8::internal::torque::LanguageServerData::LanguageServerData () [default]
Member Function Documentation
AddDefinition()
void v8::internal::torque::LanguageServerData::AddDefinition (SourcePosition token, SourcePosition definition) [static]
Definition at line 17 of file server-data.cc.
                                                                  {
  Get().definitions_map_[token.source].emplace_back(token, definition);
}
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::SourcePosition::source.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::Declarations::LookupType(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::DeclarationVisitor::Visit().
FindDefinition()
std::optional< SourcePosition > v8::internal::torque::LanguageServerData::FindDefinition (SourceId source, LineAndColumn pos) [static]
Definition at line 22 of file server-data.cc.
                                        {
  if (!source.IsValid()) return std::nullopt;
  auto iter = Get().definitions_map_.find(source);
  if (iter == Get().definitions_map_.end()) return std::nullopt;
  for (const DefinitionMapping& mapping : iter->second) {
    SourcePosition current = mapping.first;
    if (current.Contains(pos)) return mapping.second;
  }
  return std::nullopt;
}
References v8::internal::torque::SourcePosition::Contains(), definitions_map_, v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::SourceId::IsValid().
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleGotoDefinitionRequest().
PrepareAllDeclarableSymbols()
void v8::internal::torque::LanguageServerData::PrepareAllDeclarableSymbols () [private]
Definition at line 37 of file server-data.cc.
                                                     {
  const std::vector<std::unique_ptr<Declarable>>& all_declarables =
      global_context_->declarables_;
  for (const auto& declarable : all_declarables) {
    // Class field accessors and implicit specializations are
    // auto-generated and should not show up.
    if (!declarable->IsUserDefined()) continue;
    SourceId source = declarable->Position().source;
    symbols_map_[source].push_back(declarable.get());
  }
}
References global_context_, and symbols_map_.
SetGlobalContext()
static void v8::internal::torque::LanguageServerData::SetGlobalContext (GlobalContext global_context) [inline], [static]
Definition at line 47 of file server-data.h.
                                                             {
    Get().global_context_ =
        std::make_unique<GlobalContext>(std::move(global_context));
    Get().PrepareAllDeclarableSymbols();
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
SetTypeOracle()
static void v8::internal::torque::LanguageServerData::SetTypeOracle (TypeOracle type_oracle) [inline], [static]
Definition at line 53 of file server-data.h.
                                                    {
    Get().type_oracle_ = std::make_unique<TypeOracle>(std::move(type_oracle));
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
SymbolsForSourceId()
static const Symbols& v8::internal::torque::LanguageServerData::SymbolsForSourceId (SourceId id) [inline], [static]
Definition at line 57 of file server-data.h.
                                                        {
    return Get().symbols_map_[id];
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleDocumentSymbolRequest().
Member Data Documentation
definitions_map_
DefinitionsMap v8::internal::torque::LanguageServerData::definitions_map_ [private]
Definition at line 65 of file server-data.h.
Referenced by FindDefinition().
global_context_
std::unique_ptr<GlobalContext> v8::internal::torque::LanguageServerData::global_context_ [private]
Definition at line 67 of file server-data.h.
Referenced by PrepareAllDeclarableSymbols().
symbols_map_
SymbolsMap v8::internal::torque::LanguageServerData::symbols_map_ [private]
Definition at line 66 of file server-data.h.
Referenced by PrepareAllDeclarableSymbols().
type_oracle_
std::unique_ptr<TypeOracle> v8::internal::torque::LanguageServerData::type_oracle_ [private]
Definition at line 68 of file server-data.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/server-data.h
/mnt/V8SourceCode/src/torque/server-data.cc