v8::internal::LocalLogger Class Reference
#include <local-logger.h>
Public Member Functions
LocalLogger (Isolate *isolate)
bool is_logging () const
bool is_listening_to_code_events () const
void ScriptDetails (Tagged< Script > script)
void ScriptEvent (ScriptEventType type, int script_id)
void CodeLinePosInfoRecordEvent (Address code_start, Tagged< TrustedByteArray > source_position_table, JitCodeEvent::CodeType code_type)
void MapCreate (Tagged< Map > map)
void MapDetails (Tagged< Map > map)
Private Attributes
V8FileLogger * v8_file_logger_
bool is_logging_
bool is_listening_to_code_events_
Detailed Description
Definition at line 15 of file local-logger.h.
Constructor & Destructor Documentation
LocalLogger()
v8::internal::LocalLogger::LocalLogger (Isolate * isolate) [explicit]
Definition at line 14 of file local-logger.cc.
    : v8_file_logger_(isolate->v8_file_logger()),
      is_logging_(v8_file_logger_->is_logging()),
      is_listening_to_code_events_(
          v8_file_logger_->is_listening_to_code_events()) {}
Member Function Documentation
CodeLinePosInfoRecordEvent()
void v8::internal::LocalLogger::CodeLinePosInfoRecordEvent (Address code_start, Tagged< TrustedByteArray > source_position_table, JitCodeEvent::CodeType code_type)
Definition at line 26 of file local-logger.cc.
                                    {
  v8_file_logger_->CodeLinePosInfoRecordEvent(code_start, source_position_table,
                                              code_type);
}
References v8::internal::V8FileLogger::CodeLinePosInfoRecordEvent(), and v8_file_logger_.
is_listening_to_code_events()
bool v8::internal::LocalLogger::is_listening_to_code_events () const [inline]
Definition at line 20 of file local-logger.h.
                                           {
    return is_listening_to_code_events_;
  }
References is_listening_to_code_events_.
is_logging()
bool v8::internal::LocalLogger::is_logging () const [inline]
Definition at line 19 of file local-logger.h.
{ return is_logging_; }
References is_logging_.
MapCreate()
void v8::internal::LocalLogger::MapCreate (Tagged< Map > map)
Definition at line 33 of file local-logger.cc.
                                           {
  v8_file_logger_->MapCreate(map);
}
References v8::internal::V8FileLogger::MapCreate(), and v8_file_logger_.
MapDetails()
void v8::internal::LocalLogger::MapDetails (Tagged< Map > map)
Definition at line 37 of file local-logger.cc.
                                            {
  v8_file_logger_->MapDetails(map);
}
References v8::internal::V8FileLogger::MapDetails(), and v8_file_logger_.
ScriptDetails()
void v8::internal::LocalLogger::ScriptDetails (Tagged< Script > script)
Definition at line 20 of file local-logger.cc.
                                                     {
  v8_file_logger_->ScriptDetails(script);
}
References v8::internal::script, v8::internal::V8FileLogger::ScriptDetails(), and v8_file_logger_.
ScriptEvent()
void v8::internal::LocalLogger::ScriptEvent (ScriptEventType type, int script_id)
Definition at line 23 of file local-logger.cc.
                                                                 {
  v8_file_logger_->ScriptEvent(type, script_id);
}
References v8::internal::V8FileLogger::ScriptEvent(), v8::internal::tracing::type, and v8_file_logger_.
Member Data Documentation
is_listening_to_code_events_
bool v8::internal::LocalLogger::is_listening_to_code_events_ [private]
Definition at line 35 of file local-logger.h.
Referenced by is_listening_to_code_events().
is_logging_
bool v8::internal::LocalLogger::is_logging_ [private]
Definition at line 34 of file local-logger.h.
Referenced by is_logging().
v8_file_logger_
V8FileLogger* v8::internal::LocalLogger::v8_file_logger_ [private]
Definition at line 33 of file local-logger.h.
Referenced by CodeLinePosInfoRecordEvent(), MapCreate(), MapDetails(), ScriptDetails(), and ScriptEvent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/local-logger.h
/mnt/V8SourceCode/src/logging/local-logger.cc