v8::internal::WasmModuleObject Class Reference
#include <wasm-objects.h>
Public Member Functions
wasm::NativeModule * native_module () const
const std::shared_ptr< wasm::NativeModule > & shared_native_module () const
const wasm::WasmModule * module () const
bool is_asm_js ()
base::Vector< const uint8_t > GetRawFunctionName (int func_index)
Static Public Member Functions
static V8_EXPORT_PRIVATE DirectHandle< WasmModuleObject > New (Isolate *isolate, std::shared_ptr< wasm::NativeModule > native_module, DirectHandle< Script > script)
static MaybeDirectHandle< String > GetModuleNameOrNull (Isolate *, DirectHandle< WasmModuleObject >)
static MaybeDirectHandle< String > GetFunctionNameOrNull (Isolate *, DirectHandle< WasmModuleObject >, uint32_t func_index)
static DirectHandle< String > ExtractUtf8StringFromModuleBytes (Isolate *, DirectHandle< WasmModuleObject >, wasm::WireBytesRef, InternalizeString)
static DirectHandle< String > ExtractUtf8StringFromModuleBytes (Isolate *, base::Vector< const uint8_t > wire_byte, wasm::WireBytesRef, InternalizeString)
Detailed Description
Definition at line 164 of file wasm-objects.h.
Member Function Documentation
ExtractUtf8StringFromModuleBytes() [1/2]
DirectHandle< String > v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes (Isolate * isolate, base::Vector< const uint8_t > wire_byte, wasm::WireBytesRef ref, InternalizeString internalize) [static]
Definition at line 145 of file wasm-objects.cc.
                                                         {
  base::Vector<const uint8_t> name_vec =
      wire_bytes.SubVector(ref.offset(), ref.end_offset());
  // UTF8 validation happens at decode time.
  DCHECK(unibrow::Utf8::ValidateEncoding(name_vec.begin(), name_vec.length()));
  auto* factory = isolate->factory();
  return internalize
             ? factory->InternalizeUtf8String(
                   base::Vector<const char>::cast(name_vec))
             : factory
                   ->NewStringFromUtf8(base::Vector<const char>::cast(name_vec))
                   .ToHandleChecked();
}
References v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::base::Vector< T >::length(), v8::internal::wasm::WireBytesRef::offset(), v8::base::Vector< T >::SubVector(), and unibrow::Utf8::ValidateEncoding().
ExtractUtf8StringFromModuleBytes() [2/2]
DirectHandle< String > v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes (Isolate * isolate, DirectHandle< WasmModuleObject > module_object, wasm::WireBytesRef ref, InternalizeString internalize) [static]
Definition at line 136 of file wasm-objects.cc.
                                                         {
  base::Vector<const uint8_t> wire_bytes =
      module_object->native_module()->wire_bytes();
  return ExtractUtf8StringFromModuleBytes(isolate, wire_bytes, ref,
                                          internalize);
}
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::GetCustomSections(), v8::internal::wasm::GetExports(), GetFunctionNameOrNull(), v8::internal::wasm::GetImports(), GetModuleNameOrNull(), v8::internal::wasm::JSPrototypesSetup::GetString(), v8::internal::wasm::InstanceBuilder::ProcessExports(), and v8::internal::wasm::InstanceBuilder::SanitizeImports().
GetFunctionNameOrNull()
MaybeDirectHandle< String > v8::internal::WasmModuleObject::GetFunctionNameOrNull (Isolate * isolate, DirectHandle< WasmModuleObject > module_object, uint32_t func_index) [static]
Definition at line 169 of file wasm-objects.cc.
                         {
  DCHECK_LT(func_index, module_object->module()->functions.size());
  wasm::WireBytesRef name =
      module_object->module()->lazily_generated_names.LookupFunctionName(
          wasm::ModuleWireBytes(module_object->native_module()->wire_bytes()),
          func_index);
  if (!name.is_set()) return {};
  return ExtractUtf8StringFromModuleBytes(isolate, module_object, name,
                                          kNoInternalize);
}
References DCHECK_LT, ExtractUtf8StringFromModuleBytes(), v8::internal::kNoInternalize, and v8::internal::name.
Referenced by v8::internal::CallSiteInfo::GetFunctionName(), and v8::internal::WasmExportedFunction::New().
GetModuleNameOrNull()
MaybeDirectHandle< String > v8::internal::WasmModuleObject::GetModuleNameOrNull (Isolate * isolate, DirectHandle< WasmModuleObject > module_object) [static]
Definition at line 161 of file wasm-objects.cc.
                                                                    {
  const WasmModule* module = module_object->module();
  if (!module->name.is_set()) return {};
  return ExtractUtf8StringFromModuleBytes(isolate, module_object, module->name,
                                          kNoInternalize);
}
References ExtractUtf8StringFromModuleBytes(), v8::internal::wasm::WireBytesRef::is_set(), v8::internal::kNoInternalize, module(), and v8::internal::wasm::WasmModule::name.
GetRawFunctionName()
base::Vector< const uint8_t > v8::internal::WasmModuleObject::GetRawFunctionName (int func_index)
Definition at line 182 of file wasm-objects.cc.
                    {
  if (func_index == wasm::kAnonymousFuncIndex) {
    return base::Vector<const uint8_t>({nullptr, 0});
  }
  DCHECK_GT(module()->functions.size(), func_index);
  wasm::ModuleWireBytes wire_bytes(native_module()->wire_bytes());
  wasm::WireBytesRef name_ref =
      module()->lazily_generated_names.LookupFunctionName(wire_bytes,
                                                          func_index);
  wasm::WasmName name = wire_bytes.GetNameOrNull(name_ref);
  return base::Vector<const uint8_t>::cast(name);
}
References DCHECK_GT, v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::wasm::kAnonymousFuncIndex, v8::internal::wasm::WasmModule::lazily_generated_names, v8::internal::wasm::LazilyGeneratedNames::LookupFunctionName(), module(), v8::internal::name, and native_module().
is_asm_js()
bool v8::internal::WasmModuleObject::is_asm_js () [inline]
Definition at line 99 of file wasm-objects-inl.h.
                                 {
  bool asm_js = is_asmjs_module(module());
  DCHECK_EQ(asm_js, script()->IsUserJavaScript());
  return asm_js;
}
References DCHECK_EQ, v8::internal::wasm::is_asmjs_module(), module(), and v8::internal::script.
module()
const wasm::WasmModule * v8::internal::WasmModuleObject::module () const [inline]
Definition at line 95 of file wasm-objects-inl.h.
                                                     {
  // TODO(clemensb): Remove this helper (inline in callers).
  return native_module()->module();
}
References v8::internal::wasm::NativeModule::module(), and native_module().
Referenced by GetModuleNameOrNull(), GetRawFunctionName(), is_asm_js(), and New().
native_module()
wasm::NativeModule * v8::internal::WasmModuleObject::native_module () const [inline]
Definition at line 88 of file wasm-objects-inl.h.
                                                        {
  return managed_native_module()->raw();
}
Referenced by GetRawFunctionName(), module(), and New().
New()
DirectHandle< WasmModuleObject > v8::internal::WasmModuleObject::New (Isolate * isolate, std::shared_ptr< wasm::NativeModule > native_module, DirectHandle< Script > script) [static]
Definition at line 113 of file wasm-objects.cc.
                                 {
  DirectHandle<Managed<wasm::NativeModule>> managed_native_module;
  if (script->type() == Script::Type::kWasm) {
    managed_native_module = direct_handle(
        Cast<Managed<wasm::NativeModule>>(script->wasm_managed_native_module()),
        isolate);
  } else {
    const WasmModule* module = native_module->module();
    size_t memory_estimate =
        native_module->committed_code_space() +
        wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(module);
    managed_native_module = Managed<wasm::NativeModule>::From(
        isolate, memory_estimate, std::move(native_module));
  }
  DirectHandle<WasmModuleObject> module_object = Cast<WasmModuleObject>(
      isolate->factory()->NewJSObject(isolate->wasm_module_constructor()));
  module_object->set_managed_native_module(*managed_native_module);
  module_object->set_script(*script);
  return module_object;
}
References v8::internal::Cast(), v8::internal::wasm::NativeModule::committed_code_space(), v8::internal::direct_handle(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(), v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::internal::wasm::NativeModule::module(), module(), native_module(), v8::internal::Factory::NewJSObject(), and v8::internal::script.
Referenced by v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::WasmEngine::FinalizeTranslatedAsmJs(), v8::internal::wasm::WasmEngine::ImportNativeModule(), v8::internal::wasm::AsyncCompileJob::PrepareRuntimeObjects(), and v8::internal::wasm::WasmEngine::SyncCompile().
shared_native_module()
const std::shared_ptr< wasm::NativeModule > & v8::internal::WasmModuleObject::shared_native_module () const [inline]
Definition at line 92 of file wasm-objects-inl.h.
                                             {
  return managed_native_module()->get();
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc