v8::internal::FoldedMutableHeapNumberAllocator Class Reference
Public Member Functions
FoldedMutableHeapNumberAllocator (Isolate *isolate, FoldedMutableHeapNumberAllocation *allocation, DisallowGarbageCollection &no_gc)
~FoldedMutableHeapNumberAllocator ()
Tagged< HeapNumber > AllocateNext (ReadOnlyRoots roots, Float64 value)
Private Attributes
Isolate * isolate_
ReadOnlyRoots roots_
Handle< ByteArray > raw_bytes_ = {}
Address mutable_double_address_ = 0
Detailed Description
Definition at line 655 of file json-parser.cc.
Constructor & Destructor Documentation
FoldedMutableHeapNumberAllocator()
v8::internal::FoldedMutableHeapNumberAllocator::FoldedMutableHeapNumberAllocator (Isolate * isolate, FoldedMutableHeapNumberAllocation * allocation, DisallowGarbageCollection & no_gc) [inline]
Definition at line 657 of file json-parser.cc.
      : isolate_(isolate), roots_(isolate) {
    if (allocation->raw_bytes().is_null()) return;
    raw_bytes_ = allocation->raw_bytes();
    mutable_double_address_ =
        reinterpret_cast<Address>(allocation->raw_bytes()->begin());
  }
References mutable_double_address_, v8::internal::FoldedMutableHeapNumberAllocation::raw_bytes(), and raw_bytes_.
 FoldedMutableHeapNumberAllocator()
v8::internal::FoldedMutableHeapNumberAllocator::~FoldedMutableHeapNumberAllocator () [inline]
Definition at line 668 of file json-parser.cc.
                                      {
    // Make all mutable HeapNumbers alive.
    if (mutable_double_address_ == 0) {
      DCHECK(raw_bytes_.is_null());
      return;
    }
    DCHECK_EQ(mutable_double_address_,
              reinterpret_cast<Address>(raw_bytes_->end()));
    // Before setting the length of mutable_double_buffer back to zero, we
    // must ensure that the sweeper is not running or has already swept the
    // object's page. Otherwise the GC can add the contents of
    // mutable_double_buffer to the free list.
    isolate_->heap()->EnsureSweepingCompletedForObject(*raw_bytes_);
    raw_bytes_->set_length(0);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::Isolate::heap(), isolate_, mutable_double_address_, and raw_bytes_.
Member Function Documentation
AllocateNext()
Tagged<HeapNumber> v8::internal::FoldedMutableHeapNumberAllocator::AllocateNext (ReadOnlyRoots roots, Float64 value) [inline]
Definition at line 685 of file json-parser.cc.
                                                                      {
    DCHECK_GE(mutable_double_address_,
              reinterpret_cast<Address>(raw_bytes_->begin()));
    Tagged<HeapObject> hn = HeapObject::FromAddress(mutable_double_address_);
    hn->set_map_after_allocation(isolate_, roots.heap_number_map());
    Cast<HeapNumber>(hn)->set_value_as_bits(value.get_bits());
    mutable_double_address_ +=
        ALIGN_TO_ALLOCATION_ALIGNMENT(sizeof(HeapNumber));
    DCHECK_LE(mutable_double_address_,
              reinterpret_cast<Address>(raw_bytes_->end()));
    return Cast<HeapNumber>(hn);
  }
References ALIGN_TO_ALLOCATION_ALIGNMENT, DCHECK_GE, DCHECK_LE, v8::internal::HeapObject::FromAddress(), isolate_, mutable_double_address_, raw_bytes_, and v8::internal::value.
Referenced by v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject().
Member Data Documentation
isolate_
Isolate* v8::internal::FoldedMutableHeapNumberAllocator::isolate_ [private]
Definition at line 699 of file json-parser.cc.
Referenced by AllocateNext(), and ~FoldedMutableHeapNumberAllocator().
mutable_double_address_
Address v8::internal::FoldedMutableHeapNumberAllocator::mutable_double_address_ = 0 [private]
Definition at line 702 of file json-parser.cc.
Referenced by AllocateNext(), FoldedMutableHeapNumberAllocator(), and ~FoldedMutableHeapNumberAllocator().
raw_bytes_
Handle<ByteArray> v8::internal::FoldedMutableHeapNumberAllocator::raw_bytes_ = {} [private]
Definition at line 701 of file json-parser.cc.
Referenced by AllocateNext(), FoldedMutableHeapNumberAllocator(), and ~FoldedMutableHeapNumberAllocator().
roots_
ReadOnlyRoots v8::internal::FoldedMutableHeapNumberAllocator::roots_ [private]
Definition at line 700 of file json-parser.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-parser.cc