v8::internal::compiler::RegisterAllocationData Class Reference
#include <register-allocator.h>
Classes
struct DelayedReference
class PhiMapValue
Public Types
enum SpillMode { kSpillAtDefinition
, kSpillDeferred
 }
using PhiMap = ZoneMap< int, PhiMapValue * >
using DelayedReferences = ZoneVector< DelayedReference >
using RangesWithPreassignedSlots = ZoneVector< std::pair< TopLevelLiveRange *, int > >
Public Member Functions
RegisterAllocationData (const RegisterAllocationData &)=delete
RegisterAllocationData & operator= (const RegisterAllocationData &)=delete
RegisterAllocationData (const RegisterConfiguration *config, Zone *allocation_zone, Frame *frame, InstructionSequence *code, TickCounter *tick_counter, const char *debug_name=nullptr)
const ZoneVector< TopLevelLiveRange * > & live_ranges () const
ZoneVector< TopLevelLiveRange * > & live_ranges ()
const ZoneVector< TopLevelLiveRange * > & fixed_live_ranges () const
ZoneVector< TopLevelLiveRange * > & fixed_live_ranges ()
ZoneVector< TopLevelLiveRange * > & fixed_float_live_ranges ()
const ZoneVector< TopLevelLiveRange * > & fixed_float_live_ranges () const
ZoneVector< TopLevelLiveRange * > & fixed_double_live_ranges ()
const ZoneVector< TopLevelLiveRange * > & fixed_double_live_ranges () const
ZoneVector< TopLevelLiveRange * > & fixed_simd128_live_ranges ()
const ZoneVector< TopLevelLiveRange * > & fixed_simd128_live_ranges () const
ZoneVector< SparseBitVector * > & live_in_sets ()
ZoneVector< SparseBitVector * > & live_out_sets ()
DelayedReferences & delayed_references ()
InstructionSequence * code () const
Zone * allocation_zone () const
Zone * code_zone () const
Frame * frame () const
const char * debug_name () const
const RegisterConfiguration * config () const
MachineRepresentation RepresentationFor (int virtual_register)
TopLevelLiveRange * GetLiveRangeFor (int index)
TopLevelLiveRange * NewLiveRange (int index, MachineRepresentation rep)
SpillRange * AssignSpillRangeToLiveRange (TopLevelLiveRange *range, SpillMode spill_mode)
SpillRange * CreateSpillRangeForLiveRange (TopLevelLiveRange *range)
MoveOperands * AddGapMove (int index, Instruction::GapPosition position, const InstructionOperand &from, const InstructionOperand &to)
bool ExistsUseWithoutDefinition ()
bool RangesDefinedInDeferredStayInDeferred ()
void MarkFixedUse (MachineRepresentation rep, int index)
bool HasFixedUse (MachineRepresentation rep, int index)
void MarkAllocated (MachineRepresentation rep, int index)
PhiMapValue * InitializePhiMap (const InstructionBlock *block, PhiInstruction *phi)
PhiMapValue * GetPhiMapValueFor (TopLevelLiveRange *top_range)
PhiMapValue * GetPhiMapValueFor (int virtual_register)
bool IsBlockBoundary (LifetimePosition pos) const
RangesWithPreassignedSlots & preassigned_slot_ranges ()
void RememberSpillState (RpoNumber block, const ZoneVector< LiveRange * > &state)
ZoneVector< LiveRange * > & GetSpillState (RpoNumber block)
void ResetSpillState ()
TickCounter * tick_counter ()
ZoneMap< TopLevelLiveRange *, AllocatedOperand * > & slot_for_const_range ()
Static Public Attributes
static constexpr int kNumberOfFixedRangesPerRegister = 2
Private Attributes
Zone *const allocation_zone_
Frame *const frame_
InstructionSequence *const code_
const char *const debug_name_
const RegisterConfiguration *const config_
PhiMap phi_map_
ZoneVector< SparseBitVector * > live_in_sets_
ZoneVector< SparseBitVector * > live_out_sets_
ZoneVector< TopLevelLiveRange * > live_ranges_
ZoneVector< TopLevelLiveRange * > fixed_live_ranges_
ZoneVector< TopLevelLiveRange * > fixed_float_live_ranges_
ZoneVector< TopLevelLiveRange * > fixed_double_live_ranges_
ZoneVector< TopLevelLiveRange * > fixed_simd128_live_ranges_
DelayedReferences delayed_references_
BitVector * assigned_registers_
BitVector * assigned_double_registers_
BitVector * assigned_simd128_registers_
BitVector * fixed_register_use_
BitVector * fixed_fp_register_use_
BitVector * fixed_simd128_register_use_
int virtual_register_count_
RangesWithPreassignedSlots preassigned_slot_ranges_
ZoneVector< ZoneVector< LiveRange * > > spill_state_
TickCounter *const tick_counter_
ZoneMap< TopLevelLiveRange *, AllocatedOperand * > slot_for_const_range_
Detailed Description
Definition at line 197 of file register-allocator.h.
Member Typedef Documentation
DelayedReferences
using v8::internal::compiler::RegisterAllocationData::DelayedReferences = ZoneVector<DelayedReference>
Definition at line 238 of file register-allocator.h.
PhiMap
using v8::internal::compiler::RegisterAllocationData::PhiMap = ZoneMap<int, PhiMapValue*>
Definition at line 232 of file register-allocator.h.
RangesWithPreassignedSlots
using v8::internal::compiler::RegisterAllocationData::RangesWithPreassignedSlots = ZoneVector<std::pair<TopLevelLiveRange*, int> >
Definition at line 239 of file register-allocator.h.
Member Enumeration Documentation
SpillMode
enum v8::internal::compiler::RegisterAllocationData::SpillMode
Enumerator
kSpillAtDefinition
kSpillDeferred
Definition at line 204 of file register-allocator.h.
{ kSpillAtDefinition, kSpillDeferred };
Constructor & Destructor Documentation
RegisterAllocationData() [1/2]
v8::internal::compiler::RegisterAllocationData::RegisterAllocationData (const RegisterAllocationData &) [delete]
RegisterAllocationData() [2/2]
v8::internal::compiler::RegisterAllocationData::RegisterAllocationData (const RegisterConfiguration * config, Zone * allocation_zone, Frame * frame, InstructionSequence * code, TickCounter * tick_counter, const char * debug_name = nullptr)
Definition at line 1172 of file register-allocator.cc.
    : allocation_zone_(zone),
      frame_(frame),
      code_(code),
      debug_name_(debug_name),
      config_(config),
      phi_map_(allocation_zone()),
      live_in_sets_(code->InstructionBlockCount(), nullptr, allocation_zone()),
      live_out_sets_(code->InstructionBlockCount(), nullptr, allocation_zone()),
      live_ranges_(code->VirtualRegisterCount(), nullptr, allocation_zone()),
      fixed_live_ranges_(kNumberOfFixedRangesPerRegister *
                             this->config()->num_general_registers(),
                         nullptr, allocation_zone()),
      fixed_float_live_ranges_(allocation_zone()),
      fixed_double_live_ranges_(kNumberOfFixedRangesPerRegister *
                                    this->config()->num_double_registers(),
                                nullptr, allocation_zone()),
      fixed_simd128_live_ranges_(allocation_zone()),
      delayed_references_(allocation_zone()),
      assigned_registers_(nullptr),
      assigned_double_registers_(nullptr),
      virtual_register_count_(code->VirtualRegisterCount()),
      preassigned_slot_ranges_(zone),
      spill_state_(code->InstructionBlockCount(), ZoneVector<LiveRange*>(zone),
                   zone),
      tick_counter_(tick_counter),
      slot_for_const_range_(zone) {
  if (kFPAliasing == AliasingKind::kCombine) {
    fixed_float_live_ranges_.resize(
        kNumberOfFixedRangesPerRegister * this->config()->num_float_registers(),
        nullptr);
    fixed_simd128_live_ranges_.resize(
        kNumberOfFixedRangesPerRegister *
            this->config()->num_simd128_registers(),
        nullptr);
  } else if (kFPAliasing == AliasingKind::kIndependent) {
    fixed_simd128_live_ranges_.resize(
        kNumberOfFixedRangesPerRegister *
            this->config()->num_simd128_registers(),
        nullptr);
  }
  // Eagerly initialize live ranges to avoid repeated null checks.
  DCHECK_EQ(code->VirtualRegisterCount(), live_ranges_.size());
  for (int i = 0; i < code->VirtualRegisterCount(); ++i) {
    live_ranges_[i] = NewLiveRange(i, RepresentationFor(i));
  }
  assigned_registers_ = code_zone()->New<BitVector>(
      this->config()->num_general_registers(), code_zone());
  assigned_double_registers_ = code_zone()->New<BitVector>(
      this->config()->num_double_registers(), code_zone());
  fixed_register_use_ = code_zone()->New<BitVector>(
      this->config()->num_general_registers(), code_zone());
  fixed_fp_register_use_ = code_zone()->New<BitVector>(
      this->config()->num_double_registers(), code_zone());
  if (kFPAliasing == AliasingKind::kIndependent) {
    assigned_simd128_registers_ = code_zone()->New<BitVector>(
        this->config()->num_simd128_registers(), code_zone());
    fixed_simd128_register_use_ = code_zone()->New<BitVector>(
        this->config()->num_simd128_registers(), code_zone());
  }
  this->frame()->SetAllocatedRegisters(assigned_registers_);
  this->frame()->SetAllocatedDoubleRegisters(assigned_double_registers_);
}
References assigned_double_registers_, assigned_registers_, assigned_simd128_registers_, code(), code_zone(), config(), DCHECK_EQ, fixed_float_live_ranges_, fixed_fp_register_use_, fixed_register_use_, fixed_simd128_live_ranges_, fixed_simd128_register_use_, frame(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kCombine, v8::internal::kFPAliasing, v8::internal::kIndependent, kNumberOfFixedRangesPerRegister, live_ranges_, v8::internal::Zone::New(), NewLiveRange(), v8::internal::RegisterConfiguration::num_double_registers(), v8::internal::RegisterConfiguration::num_general_registers(), v8::internal::RegisterConfiguration::num_simd128_registers(), RepresentationFor(), v8::internal::compiler::Frame::SetAllocatedDoubleRegisters(), v8::internal::compiler::Frame::SetAllocatedRegisters(), and v8::internal::compiler::InstructionSequence::VirtualRegisterCount().
Member Function Documentation
AddGapMove()
MoveOperands * v8::internal::compiler::RegisterAllocationData::AddGapMove (int index, Instruction::GapPosition position, const InstructionOperand & from, const InstructionOperand & to)
Definition at line 1242 of file register-allocator.cc.
                                                                  {
  Instruction* instr = code()->InstructionAt(index);
  ParallelMove* moves = instr->GetOrCreateParallelMove(position, code_zone());
  return moves->AddMove(from, to);
}
References v8::internal::compiler::ParallelMove::AddMove(), code(), code_zone(), v8::internal::compiler::Instruction::GetOrCreateParallelMove(), v8::internal::index, and v8::internal::compiler::InstructionSequence::InstructionAt().
Referenced by v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), and v8::internal::compiler::ConstraintBuilder::ResolvePhis().
allocation_zone()
Zone* v8::internal::compiler::RegisterAllocationData::allocation_zone () const [inline]
Definition at line 281 of file register-allocator.h.
{ return allocation_zone_; }
References allocation_zone_.
Referenced by v8::internal::compiler::ConstraintBuilder::allocation_zone(), v8::internal::compiler::LiveRangeBuilder::allocation_zone(), v8::internal::compiler::RegisterAllocator::allocation_zone(), AssignSpillRangeToLiveRange(), v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), InitializePhiMap(), and NewLiveRange().
AssignSpillRangeToLiveRange()
SpillRange * v8::internal::compiler::RegisterAllocationData::AssignSpillRangeToLiveRange (TopLevelLiveRange * range, SpillMode spill_mode)
Definition at line 1345 of file register-allocator.cc.
                                                    {
  using SpillType = TopLevelLiveRange::SpillType;
  DCHECK(!range->HasSpillOperand());
  SpillRange* spill_range = range->GetAllocatedSpillRange();
  if (spill_range == nullptr) {
    spill_range = allocation_zone()->New<SpillRange>(range, allocation_zone());
  }
  if (spill_mode == SpillMode::kSpillDeferred &&
      (range->spill_type() != SpillType::kSpillRange)) {
    range->set_spill_type(SpillType::kDeferredSpillRange);
  } else {
    range->set_spill_type(SpillType::kSpillRange);
  }
  return spill_range;
}
References allocation_zone(), v8::internal::DCHECK(), v8::internal::compiler::TopLevelLiveRange::GetAllocatedSpillRange(), v8::internal::compiler::TopLevelLiveRange::HasSpillOperand(), v8::internal::Zone::New(), v8::internal::compiler::TopLevelLiveRange::set_spill_type(), and v8::internal::compiler::TopLevelLiveRange::spill_type().
Referenced by v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), and v8::internal::compiler::RegisterAllocator::Spill().
code()
InstructionSequence* v8::internal::compiler::RegisterAllocationData::code () const [inline]
Definition at line 278 of file register-allocator.h.
{ return code_; }
References code_.
Referenced by v8::internal::compiler::SpillPlacer::Add(), AddGapMove(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::SpillPlacer::ClearData(), v8::internal::compiler::ConstraintBuilder::code(), v8::internal::compiler::LiveRangeBuilder::code(), v8::internal::compiler::BundleBuilder::code(), v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::LiveRangeConnector::code(), code_zone(), v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves(), v8::internal::compiler::SpillPlacer::FirstBackwardPass(), v8::internal::compiler::SpillPlacer::ForwardPass(), v8::internal::compiler::SpillPlacer::GetOrCreateIndexForLatestVreg(), IsBlockBoundary(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), RangesDefinedInDeferredStayInDeferred(), RegisterAllocationData(), v8::internal::compiler::RegisterAllocator::RegisterAllocator(), RepresentationFor(), v8::internal::compiler::SpillPlacer::SecondBackwardPass(), and v8::internal::compiler::SpillPlacer::SetSpillRequired().
code_zone()
Zone* v8::internal::compiler::RegisterAllocationData::code_zone () const [inline]
Definition at line 284 of file register-allocator.h.
{ return code()->zone(); }
References code(), and v8::internal::compiler::InstructionSequence::zone().
Referenced by AddGapMove(), and RegisterAllocationData().
config()
const RegisterConfiguration* v8::internal::compiler::RegisterAllocationData::config () const [inline]
Definition at line 287 of file register-allocator.h.
{ return config_; }
References config_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LiveRangeBuilder::config(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet(), v8::internal::compiler::LinearScanAllocator::GetSIMD128RegisterSet(), HasFixedUse(), MarkAllocated(), MarkFixedUse(), RegisterAllocationData(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
CreateSpillRangeForLiveRange()
SpillRange* v8::internal::compiler::RegisterAllocationData::CreateSpillRangeForLiveRange (TopLevelLiveRange * range)
debug_name()
const char* v8::internal::compiler::RegisterAllocationData::debug_name () const [inline]
Definition at line 286 of file register-allocator.h.
{ return debug_name_; }
References debug_name_.
Referenced by ExistsUseWithoutDefinition().
delayed_references()
DelayedReferences& v8::internal::compiler::RegisterAllocationData::delayed_references () [inline]
Definition at line 277 of file register-allocator.h.
{ return delayed_references_; }
References delayed_references_.
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore().
ExistsUseWithoutDefinition()
bool v8::internal::compiler::RegisterAllocationData::ExistsUseWithoutDefinition ()
Definition at line 1293 of file register-allocator.cc.
                                                        {
  bool found = false;
  for (int operand_index : *live_in_sets()[0]) {
    found = true;
    PrintF("Register allocator error: live v%d reached first block.\n",
           operand_index);
    LiveRange* range = GetLiveRangeFor(operand_index);
    PrintF(" (first use is at position %d in instruction %d)\n",
           range->positions().first()->pos().value(),
           range->positions().first()->pos().ToInstructionIndex());
    if (debug_name() == nullptr) {
      PrintF("\n");
    } else {
      PrintF(" (function: %s)\n", debug_name());
    }
  }
  return found;
}
References debug_name(), GetLiveRangeFor(), live_in_sets(), v8::internal::compiler::LiveRange::positions(), and v8::internal::PrintF().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
fixed_double_live_ranges() [1/2]
ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::fixed_double_live_ranges () [inline]
Definition at line 263 of file register-allocator.h.
                                                             {
    return fixed_double_live_ranges_;
  }
References fixed_double_live_ranges_.
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor(), v8::internal::compiler::operator<<(), and v8::internal::compiler::GraphC1Visualizer::PrintLiveRanges().
fixed_double_live_ranges() [2/2]
const ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::fixed_double_live_ranges () const [inline]
Definition at line 266 of file register-allocator.h.
                                                                         {
    return fixed_double_live_ranges_;
  }
References fixed_double_live_ranges_.
fixed_float_live_ranges() [1/2]
ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::fixed_float_live_ranges () [inline]
Definition at line 257 of file register-allocator.h.
                                                            {
    return fixed_float_live_ranges_;
  }
References fixed_float_live_ranges_.
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor().
fixed_float_live_ranges() [2/2]
const ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::fixed_float_live_ranges () const [inline]
Definition at line 260 of file register-allocator.h.
                                                                        {
    return fixed_float_live_ranges_;
  }
References fixed_float_live_ranges_.
fixed_live_ranges() [1/2]
ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::fixed_live_ranges () [inline]
Definition at line 254 of file register-allocator.h.
                                                      {
    return fixed_live_ranges_;
  }
References fixed_live_ranges_.
fixed_live_ranges() [2/2]
const ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::fixed_live_ranges () const [inline]
Definition at line 251 of file register-allocator.h.
                                                                  {
    return fixed_live_ranges_;
  }
References fixed_live_ranges_.
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedLiveRangeFor(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRanges(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
fixed_simd128_live_ranges() [1/2]
ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::fixed_simd128_live_ranges () [inline]
Definition at line 269 of file register-allocator.h.
                                                              {
    return fixed_simd128_live_ranges_;
  }
References fixed_simd128_live_ranges_.
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor(), and v8::internal::compiler::LiveRangeBuilder::FixedSIMD128LiveRangeFor().
fixed_simd128_live_ranges() [2/2]
const ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::fixed_simd128_live_ranges () const [inline]
Definition at line 272 of file register-allocator.h.
                                                                          {
    return fixed_simd128_live_ranges_;
  }
References fixed_simd128_live_ranges_.
frame()
Frame* v8::internal::compiler::RegisterAllocationData::frame () const [inline]
Definition at line 285 of file register-allocator.h.
{ return frame_; }
References frame_.
Referenced by v8::internal::compiler::OperandAssigner::AssignSpillSlots(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), and RegisterAllocationData().
GetLiveRangeFor()
TopLevelLiveRange * v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor (int index)
Definition at line 1256 of file register-allocator.cc.
                                                                    {
  TopLevelLiveRange* result = live_ranges()[index];
  DCHECK_NOT_NULL(result);
  DCHECK_EQ(live_ranges()[index]->vreg(), index);
  return result;
}
References DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::index, live_ranges(), and v8::base::internal::result.
Referenced by v8::internal::compiler::LiveRangeBuilder::AddInitialIntervals(), v8::internal::compiler::BundleBuilder::BuildBundles(), ExistsUseWithoutDefinition(), v8::internal::compiler::LiveRangeBuilder::LiveRangeFor(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
GetPhiMapValueFor() [1/2]
RegisterAllocationData::PhiMapValue * v8::internal::compiler::RegisterAllocationData::GetPhiMapValueFor (int virtual_register)
Definition at line 1281 of file register-allocator.cc.
                          {
  auto it = phi_map_.find(virtual_register);
  DCHECK(it != phi_map_.end());
  return it->second;
}
References v8::internal::DCHECK(), and phi_map_.
GetPhiMapValueFor() [2/2]
RegisterAllocationData::PhiMapValue * v8::internal::compiler::RegisterAllocationData::GetPhiMapValueFor (TopLevelLiveRange * top_range)
Definition at line 1288 of file register-allocator.cc.
                                  {
  return GetPhiMapValueFor(top_range->vreg());
}
References v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::OperandAssigner::CommitAssignment(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
GetSpillState()
ZoneVector<LiveRange*>& v8::internal::compiler::RegisterAllocationData::GetSpillState (RpoNumber block) [inline]
Definition at line 326 of file register-allocator.h.
                                                         {
    auto& result = spill_state_[block.ToSize()];
    return result;
  }
References v8::base::internal::result, spill_state_, and v8::internal::compiler::RpoNumber::ToSize().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), and v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors().
HasFixedUse()
bool v8::internal::compiler::RegisterAllocationData::HasFixedUse (MachineRepresentation rep, int index)
Definition at line 1401 of file register-allocator.cc.
                                                                             {
  switch (rep) {
    case MachineRepresentation::kFloat16:
    case MachineRepresentation::kFloat32:
    case MachineRepresentation::kSimd128:
    case MachineRepresentation::kSimd256: {
      if (kFPAliasing == AliasingKind::kOverlap) {
        return fixed_fp_register_use_->Contains(index);
      } else if (kFPAliasing == AliasingKind::kIndependent) {
        if (rep == MachineRepresentation::kFloat16 ||
            rep == MachineRepresentation::kFloat32) {
          return fixed_fp_register_use_->Contains(index);
        } else {
          return fixed_simd128_register_use_->Contains(index);
        }
      } else {
        int alias_base_index = -1;
        int aliases = config()->GetAliases(
            rep, index, MachineRepresentation::kFloat64, &alias_base_index);
        DCHECK(aliases > 0 || (aliases == 0 && alias_base_index == -1));
        bool result = false;
        while (aliases-- && !result) {
          int aliased_reg = alias_base_index + aliases;
          result |= fixed_fp_register_use_->Contains(aliased_reg);
        }
        return result;
      }
    }
    case MachineRepresentation::kFloat64:
      return fixed_fp_register_use_->Contains(index);
    default:
      DCHECK(!IsFloatingPoint(rep));
      return fixed_register_use_->Contains(index);
  }
}
References config(), v8::internal::BitVector::Contains(), v8::internal::DCHECK(), fixed_fp_register_use_, fixed_register_use_, fixed_simd128_register_use_, v8::internal::RegisterConfiguration::GetAliases(), v8::internal::index, v8::internal::IsFloatingPoint(), v8::internal::kFloat16, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::kOverlap, v8::internal::kSimd128, v8::internal::kSimd256, and v8::base::internal::result.
InitializePhiMap()
RegisterAllocationData::PhiMapValue * v8::internal::compiler::RegisterAllocationData::InitializePhiMap (const InstructionBlock * block, PhiInstruction * phi)
Definition at line 1269 of file register-allocator.cc.
                                                        {
  RegisterAllocationData::PhiMapValue* map_value =
      allocation_zone()->New<RegisterAllocationData::PhiMapValue>(
          phi, block, allocation_zone());
  auto res =
      phi_map_.insert(std::make_pair(phi->virtual_register(), map_value));
  DCHECK(res.second);
  USE(res);
  return map_value;
}
References allocation_zone(), v8::internal::DCHECK(), v8::internal::Zone::New(), phi_map_, USE, and v8::internal::compiler::PhiInstruction::virtual_register().
Referenced by v8::internal::compiler::ConstraintBuilder::ResolvePhis().
IsBlockBoundary()
bool v8::internal::compiler::RegisterAllocationData::IsBlockBoundary (LifetimePosition pos) const
Definition at line 1474 of file register-allocator.cc.
                                                                       {
  return pos.IsFullStart() &&
         (static_cast<size_t>(pos.ToInstructionIndex()) ==
              code()->instructions().size() ||
          code()->GetInstructionBlock(pos.ToInstructionIndex())->code_start() ==
              pos.ToInstructionIndex());
}
References code(), v8::internal::compiler::InstructionBlock::code_start(), v8::internal::compiler::InstructionSequence::GetInstructionBlock(), v8::internal::compiler::InstructionSequence::instructions(), v8::internal::compiler::LifetimePosition::IsFullStart(), v8::internal::ZoneVector< T >::size(), and v8::internal::compiler::LifetimePosition::ToInstructionIndex().
live_in_sets()
ZoneVector<SparseBitVector*>& v8::internal::compiler::RegisterAllocationData::live_in_sets () [inline]
Definition at line 275 of file register-allocator.h.
{ return live_in_sets_; }
References live_in_sets_.
Referenced by v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), ExistsUseWithoutDefinition(), v8::internal::compiler::LiveRangeBuilder::live_in_sets(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
live_out_sets()
ZoneVector<SparseBitVector*>& v8::internal::compiler::RegisterAllocationData::live_out_sets () [inline]
Definition at line 276 of file register-allocator.h.
{ return live_out_sets_; }
References live_out_sets_.
Referenced by v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut().
live_ranges() [1/2]
ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::live_ranges () [inline]
Definition at line 250 of file register-allocator.h.
{ return live_ranges_; }
References live_ranges_.
live_ranges() [2/2]
const ZoneVector<TopLevelLiveRange*>& v8::internal::compiler::RegisterAllocationData::live_ranges () const [inline]
Definition at line 247 of file register-allocator.h.
                                                            {
    return live_ranges_;
  }
References live_ranges_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), v8::internal::compiler::OperandAssigner::CommitAssignment(), v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), GetLiveRangeFor(), v8::internal::compiler::operator<<(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRanges(), RangesDefinedInDeferredStayInDeferred(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::SpillPlacer::SecondBackwardPass(), and v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand().
MarkAllocated()
void v8::internal::compiler::RegisterAllocationData::MarkAllocated (MachineRepresentation rep, int index)
Definition at line 1437 of file register-allocator.cc.
                                                      {
  switch (rep) {
    case MachineRepresentation::kFloat16:
    case MachineRepresentation::kFloat32:
    case MachineRepresentation::kSimd128:
    case MachineRepresentation::kSimd256:
      if (kFPAliasing == AliasingKind::kOverlap) {
        assigned_double_registers_->Add(index);
      } else if (kFPAliasing == AliasingKind::kIndependent) {
        if (rep == MachineRepresentation::kFloat16 ||
            rep == MachineRepresentation::kFloat32) {
          assigned_double_registers_->Add(index);
        } else {
          assigned_simd128_registers_->Add(index);
        }
      } else {
        int alias_base_index = -1;
        int aliases = config()->GetAliases(
            rep, index, MachineRepresentation::kFloat64, &alias_base_index);
        DCHECK(aliases > 0 || (aliases == 0 && alias_base_index == -1));
        while (aliases--) {
          int aliased_reg = alias_base_index + aliases;
          assigned_double_registers_->Add(aliased_reg);
        }
      }
      break;
    case MachineRepresentation::kFloat64:
      assigned_double_registers_->Add(index);
      break;
    default:
      DCHECK(!IsFloatingPoint(rep));
      assigned_registers_->Add(index);
      break;
  }
}
References v8::internal::BitVector::Add(), assigned_double_registers_, assigned_registers_, assigned_simd128_registers_, config(), v8::internal::DCHECK(), v8::internal::RegisterConfiguration::GetAliases(), v8::internal::index, v8::internal::IsFloatingPoint(), v8::internal::kFloat16, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::kOverlap, v8::internal::kSimd128, and v8::internal::kSimd256.
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor(), v8::internal::compiler::LiveRangeBuilder::FixedLiveRangeFor(), v8::internal::compiler::LiveRangeBuilder::FixedSIMD128LiveRangeFor(), and v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister().
MarkFixedUse()
void v8::internal::compiler::RegisterAllocationData::MarkFixedUse (MachineRepresentation rep, int index)
Definition at line 1364 of file register-allocator.cc.
                                                     {
  switch (rep) {
    case MachineRepresentation::kFloat16:
    case MachineRepresentation::kFloat32:
    case MachineRepresentation::kSimd128:
    case MachineRepresentation::kSimd256:
      if (kFPAliasing == AliasingKind::kOverlap) {
        fixed_fp_register_use_->Add(index);
      } else if (kFPAliasing == AliasingKind::kIndependent) {
        if (rep == MachineRepresentation::kFloat16 ||
            rep == MachineRepresentation::kFloat32) {
          fixed_fp_register_use_->Add(index);
        } else {
          fixed_simd128_register_use_->Add(index);
        }
      } else {
        int alias_base_index = -1;
        int aliases = config()->GetAliases(
            rep, index, MachineRepresentation::kFloat64, &alias_base_index);
        DCHECK(aliases > 0 || (aliases == 0 && alias_base_index == -1));
        while (aliases--) {
          int aliased_reg = alias_base_index + aliases;
          fixed_fp_register_use_->Add(aliased_reg);
        }
      }
      break;
    case MachineRepresentation::kFloat64:
      fixed_fp_register_use_->Add(index);
      break;
    default:
      DCHECK(!IsFloatingPoint(rep));
      fixed_register_use_->Add(index);
      break;
  }
}
References v8::internal::BitVector::Add(), config(), v8::internal::DCHECK(), fixed_fp_register_use_, fixed_register_use_, fixed_simd128_register_use_, v8::internal::RegisterConfiguration::GetAliases(), v8::internal::index, v8::internal::IsFloatingPoint(), v8::internal::kFloat16, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::kOverlap, v8::internal::kSimd128, and v8::internal::kSimd256.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed().
NewLiveRange()
TopLevelLiveRange * v8::internal::compiler::RegisterAllocationData::NewLiveRange (int index, MachineRepresentation rep)
Definition at line 1263 of file register-allocator.cc.
                                          {
  return allocation_zone()->New<TopLevelLiveRange>(index, rep,
                                                   allocation_zone());
}
References allocation_zone(), v8::internal::index, and v8::internal::Zone::New().
Referenced by v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor(), v8::internal::compiler::LiveRangeBuilder::FixedLiveRangeFor(), v8::internal::compiler::LiveRangeBuilder::FixedSIMD128LiveRangeFor(), and RegisterAllocationData().
operator=()
RegisterAllocationData& v8::internal::compiler::RegisterAllocationData::operator= (const RegisterAllocationData &) [delete]
preassigned_slot_ranges()
RangesWithPreassignedSlots& v8::internal::compiler::RegisterAllocationData::preassigned_slot_ranges () [inline]
Definition at line 317 of file register-allocator.h.
                                                        {
    return preassigned_slot_ranges_;
  }
References preassigned_slot_ranges_.
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter().
RangesDefinedInDeferredStayInDeferred()
bool v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred ()
Definition at line 1320 of file register-allocator.cc.
                                                                   {
  const size_t live_ranges_size = live_ranges().size();
  for (const TopLevelLiveRange* range : live_ranges()) {
    CHECK_EQ(live_ranges_size,
             live_ranges().size()); // TODO(neis): crbug.com/831822
    DCHECK_NOT_NULL(range);
    if (range->IsEmpty() ||
        !code()
             ->GetInstructionBlock(range->Start().ToInstructionIndex())
             ->IsDeferred()) {
      continue;
    }
    for (const UseInterval& interval : range->intervals()) {
      int first = interval.FirstGapIndex();
      int last = interval.LastGapIndex();
      for (int instr = first; instr <= last;) {
        const InstructionBlock* block = code()->GetInstructionBlock(instr);
        if (!block->IsDeferred()) return false;
        instr = block->last_instruction_index() + 1;
      }
    }
  }
  return true;
}
References CHECK_EQ, code(), DCHECK_NOT_NULL, v8::internal::compiler::UseInterval::FirstGapIndex(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::InstructionSequence::GetInstructionBlock(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::UseInterval::LastGapIndex(), live_ranges(), and size().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
RememberSpillState()
void v8::internal::compiler::RegisterAllocationData::RememberSpillState (RpoNumber block, const ZoneVector< LiveRange * > & state) [inline]
Definition at line 321 of file register-allocator.h.
                                                               {
    spill_state_[block.ToSize()] = state;
  }
References spill_state_, and v8::internal::compiler::RpoNumber::ToSize().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters().
RepresentationFor()
MachineRepresentation v8::internal::compiler::RegisterAllocationData::RepresentationFor (int virtual_register)
Definition at line 1250 of file register-allocator.cc.
                          {
  DCHECK_LT(virtual_register, code()->VirtualRegisterCount());
  return code()->GetRepresentation(virtual_register);
}
References code(), DCHECK_LT, and v8::internal::compiler::InstructionSequence::GetRepresentation().
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), and RegisterAllocationData().
ResetSpillState()
void v8::internal::compiler::RegisterAllocationData::ResetSpillState () [inline]
Definition at line 331 of file register-allocator.h.
                         {
    for (auto& state : spill_state_) {
      state.clear();
    }
  }
References spill_state_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters().
slot_for_const_range()
ZoneMap<TopLevelLiveRange*, AllocatedOperand*>& v8::internal::compiler::RegisterAllocationData::slot_for_const_range () [inline]
Definition at line 339 of file register-allocator.h.
                                                                         {
    return slot_for_const_range_;
  }
References slot_for_const_range_.
Referenced by v8::internal::compiler::OperandAssigner::CommitAssignment(), and v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore().
tick_counter()
TickCounter* v8::internal::compiler::RegisterAllocationData::tick_counter () [inline]
Definition at line 337 of file register-allocator.h.
{ return tick_counter_; }
References tick_counter_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::OperandAssigner::AssignSpillSlots(), v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), v8::internal::compiler::OperandAssigner::CommitAssignment(), v8::internal::compiler::OperandAssigner::DecideSpillingMode(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraints(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), and v8::internal::compiler::ConstraintBuilder::ResolvePhis().
Member Data Documentation
allocation_zone_
Zone* const v8::internal::compiler::RegisterAllocationData::allocation_zone_ [private]
Definition at line 344 of file register-allocator.h.
Referenced by allocation_zone().
assigned_double_registers_
BitVector* v8::internal::compiler::RegisterAllocationData::assigned_double_registers_ [private]
Definition at line 359 of file register-allocator.h.
Referenced by MarkAllocated(), and RegisterAllocationData().
assigned_registers_
BitVector* v8::internal::compiler::RegisterAllocationData::assigned_registers_ [private]
Definition at line 358 of file register-allocator.h.
Referenced by MarkAllocated(), and RegisterAllocationData().
assigned_simd128_registers_
BitVector* v8::internal::compiler::RegisterAllocationData::assigned_simd128_registers_ [private]
Definition at line 360 of file register-allocator.h.
Referenced by MarkAllocated(), and RegisterAllocationData().
code_
InstructionSequence* const v8::internal::compiler::RegisterAllocationData::code_ [private]
Definition at line 346 of file register-allocator.h.
Referenced by code().
config_
const RegisterConfiguration* const v8::internal::compiler::RegisterAllocationData::config_ [private]
Definition at line 348 of file register-allocator.h.
Referenced by config().
debug_name_
const char* const v8::internal::compiler::RegisterAllocationData::debug_name_ [private]
Definition at line 347 of file register-allocator.h.
Referenced by debug_name().
delayed_references_
DelayedReferences v8::internal::compiler::RegisterAllocationData::delayed_references_ [private]
Definition at line 357 of file register-allocator.h.
Referenced by delayed_references().
fixed_double_live_ranges_
ZoneVector<TopLevelLiveRange*> v8::internal::compiler::RegisterAllocationData::fixed_double_live_ranges_ [private]
Definition at line 355 of file register-allocator.h.
Referenced by fixed_double_live_ranges().
fixed_float_live_ranges_
ZoneVector<TopLevelLiveRange*> v8::internal::compiler::RegisterAllocationData::fixed_float_live_ranges_ [private]
Definition at line 354 of file register-allocator.h.
Referenced by fixed_float_live_ranges(), and RegisterAllocationData().
fixed_fp_register_use_
BitVector* v8::internal::compiler::RegisterAllocationData::fixed_fp_register_use_ [private]
Definition at line 362 of file register-allocator.h.
Referenced by HasFixedUse(), MarkFixedUse(), and RegisterAllocationData().
fixed_live_ranges_
ZoneVector<TopLevelLiveRange*> v8::internal::compiler::RegisterAllocationData::fixed_live_ranges_ [private]
Definition at line 353 of file register-allocator.h.
Referenced by fixed_live_ranges().
fixed_register_use_
BitVector* v8::internal::compiler::RegisterAllocationData::fixed_register_use_ [private]
Definition at line 361 of file register-allocator.h.
Referenced by HasFixedUse(), MarkFixedUse(), and RegisterAllocationData().
fixed_simd128_live_ranges_
ZoneVector<TopLevelLiveRange*> v8::internal::compiler::RegisterAllocationData::fixed_simd128_live_ranges_ [private]
Definition at line 356 of file register-allocator.h.
Referenced by fixed_simd128_live_ranges(), and RegisterAllocationData().
fixed_simd128_register_use_
BitVector* v8::internal::compiler::RegisterAllocationData::fixed_simd128_register_use_ [private]
Definition at line 363 of file register-allocator.h.
Referenced by HasFixedUse(), MarkFixedUse(), and RegisterAllocationData().
frame_
Frame* const v8::internal::compiler::RegisterAllocationData::frame_ [private]
Definition at line 345 of file register-allocator.h.
Referenced by frame().
kNumberOfFixedRangesPerRegister
constexpr int v8::internal::compiler::RegisterAllocationData::kNumberOfFixedRangesPerRegister = 2 [static], [constexpr]
Definition at line 206 of file register-allocator.h.
Referenced by RegisterAllocationData().
live_in_sets_
ZoneVector<SparseBitVector*> v8::internal::compiler::RegisterAllocationData::live_in_sets_ [private]
Definition at line 350 of file register-allocator.h.
Referenced by live_in_sets().
live_out_sets_
ZoneVector<SparseBitVector*> v8::internal::compiler::RegisterAllocationData::live_out_sets_ [private]
Definition at line 351 of file register-allocator.h.
Referenced by live_out_sets().
live_ranges_
ZoneVector<TopLevelLiveRange*> v8::internal::compiler::RegisterAllocationData::live_ranges_ [private]
Definition at line 352 of file register-allocator.h.
Referenced by live_ranges(), and RegisterAllocationData().
phi_map_
PhiMap v8::internal::compiler::RegisterAllocationData::phi_map_ [private]
Definition at line 349 of file register-allocator.h.
Referenced by GetPhiMapValueFor(), and InitializePhiMap().
preassigned_slot_ranges_
RangesWithPreassignedSlots v8::internal::compiler::RegisterAllocationData::preassigned_slot_ranges_ [private]
Definition at line 365 of file register-allocator.h.
Referenced by preassigned_slot_ranges().
slot_for_const_range_
ZoneMap<TopLevelLiveRange*, AllocatedOperand*> v8::internal::compiler::RegisterAllocationData::slot_for_const_range_ [private]
Definition at line 368 of file register-allocator.h.
Referenced by slot_for_const_range().
spill_state_
ZoneVector<ZoneVector<LiveRange*> > v8::internal::compiler::RegisterAllocationData::spill_state_ [private]
Definition at line 366 of file register-allocator.h.
Referenced by GetSpillState(), RememberSpillState(), and ResetSpillState().
tick_counter_
TickCounter* const v8::internal::compiler::RegisterAllocationData::tick_counter_ [private]
Definition at line 367 of file register-allocator.h.
Referenced by tick_counter().
virtual_register_count_
int v8::internal::compiler::RegisterAllocationData::virtual_register_count_ [private]
Definition at line 364 of file register-allocator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc