v8::Locker Class Reference
#include <v8-locker.h>
Public Member Functions
Locker (Isolate *isolate)
Initialize Locker for a given Isolate.
~Locker ()
Locker (const Locker &)=delete
void operator= (const Locker &)=delete
Static Public Member Functions
static bool IsLocked (Isolate *isolate)
Returns whether or not the locker for a given isolate, is locked by the current thread.
Private Member Functions
void Initialize (Isolate *isolate)
Private Attributes
bool has_lock_
bool top_level_
internal::Isolate * isolate_
Detailed Description
Definition at line 109 of file v8-locker.h.
Constructor & Destructor Documentation
Locker() [1/2]
v8::Locker::Locker (Isolate * isolate) [inline], [explicit]
Initialize Locker for a given Isolate.
Definition at line 114 of file v8-locker.h.
{ Initialize(isolate); }
 Locker()
v8::Locker::~Locker ()
Definition at line 59 of file v8threads.cc.
                {
  DCHECK(isolate_->thread_manager()->IsLockedByCurrentThread());
  if (has_lock_) {
    if (top_level_) {
      isolate_->thread_manager()->FreeThreadResources();
    } else {
      isolate_->thread_manager()->ArchiveThread();
    }
    isolate_->thread_manager()->Unlock();
  }
}
References v8::internal::ThreadManager::ArchiveThread(), DCHECK, v8::internal::ThreadManager::FreeThreadResources(), has_lock_, v8::internal::ThreadManager::IsLockedByCurrentThread(), isolate_, v8::internal::Isolate::thread_manager(), top_level_, and v8::internal::ThreadManager::Unlock().
Locker() [2/2]
v8::Locker::Locker (const Locker &) [delete]
Member Function Documentation
Initialize()
void v8::Locker::Initialize (v8::Isolate * isolate) [private]
Definition at line 29 of file v8threads.cc.
                                          {
  DCHECK_NOT_NULL(isolate);
  has_lock_ = false;
  top_level_ = true;
  isolate_ = reinterpret_cast<i::Isolate*>(isolate);
  // Record that the Locker has been used at least once.
  base::Relaxed_Store(&g_locker_was_ever_used_, 1);
  isolate_->set_was_locker_ever_used();
  // Get the big lock if necessary.
  if (!isolate_->thread_manager()->IsLockedByCurrentThread()) {
    isolate_->thread_manager()->Lock();
    has_lock_ = true;
    // This may be a locker within an unlocker in which case we have to
    // get the saved state for this thread and restore it.
    if (isolate_->thread_manager()->RestoreThread()) {
      top_level_ = false;
    }
  }
  DCHECK(isolate_->thread_manager()->IsLockedByCurrentThread());
}
References DCHECK, DCHECK_NOT_NULL, v8::anonymous_namespace{v8threads.cc}::g_locker_was_ever_used_, has_lock_, v8::internal::ThreadManager::IsLockedByCurrentThread(), isolate_, v8::internal::ThreadManager::Lock(), v8::base::Relaxed_Store(), v8::internal::ThreadManager::RestoreThread(), v8::internal::Isolate::set_was_locker_ever_used(), v8::internal::Isolate::thread_manager(), and top_level_.
IsLocked()
bool v8::Locker::IsLocked (v8::Isolate * isolate) [static]
Returns whether or not the locker for a given isolate, is locked by the current thread.
Definition at line 53 of file v8threads.cc.
                                        {
  DCHECK_NOT_NULL(isolate);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  return i_isolate->thread_manager()->IsLockedByCurrentThread();
}
References DCHECK_NOT_NULL, v8::internal::ThreadManager::IsLockedByCurrentThread(), and v8::internal::Isolate::thread_manager().
operator=()
void v8::Locker::operator= (const Locker &) [delete]
Member Data Documentation
has_lock_
bool v8::Locker::has_lock_ [private]
Definition at line 131 of file v8-locker.h.
Referenced by Initialize(), and ~Locker().
isolate_
internal::Isolate* v8::Locker::isolate_ [private]
Definition at line 133 of file v8-locker.h.
Referenced by Initialize(), and ~Locker().
top_level_
bool v8::Locker::top_level_ [private]
Definition at line 132 of file v8-locker.h.
Referenced by Initialize(), and ~Locker().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-locker.h
/mnt/V8SourceCode/src/execution/v8threads.cc