v8::internal::compiler::SLPTree Class Reference
#include <revectorizer.h>
Public Member Functions
SLPTree (Zone *zone, TFGraph *graph)
PackNode * BuildTree (const ZoneVector< Node * > &roots)
void DeleteTree ()
PackNode * GetPackNode (Node *node)
void Print (const char *info)
template<typename FunctionType >
void ForEach (FunctionType callback)
Node * GetEarlySchedulePosition (Node *node)
Private Member Functions
PackNode * BuildTreeRec (const ZoneVector< Node * > &node_group, unsigned depth)
PackNode * NewPackNode (const ZoneVector< Node * > &node_group)
PackNode * NewPackNodeAndRecurs (const ZoneVector< Node * > &node_group, int start_index, int count, unsigned depth)
bool CanBePacked (const ZoneVector< Node * > &node_group)
TFGraph * graph () const
Zone * zone () const
void PopStack ()
void PushStack (const ZoneVector< Node * > &node_group)
void ClearStack ()
bool OnStack (Node *node)
bool AllOnStack (const ZoneVector< Node * > &node_group)
bool StackTopIsPhi ()
void TryReduceLoadChain (const ZoneVector< Node * > &loads)
bool IsSideEffectFreeLoad (const ZoneVector< Node * > &node_group)
bool SameBasicBlock (Node *node0, Node *node1)
Private Attributes
Zone *const zone_
TFGraph *const graph_
PackNode * root_
LinearScheduler * scheduler_
ZoneSet< Node * > on_stack_
ZoneStack< ZoneVector< Node * > > stack_
ZoneUnorderedMap< Node *, PackNode * > node_to_packnode_
Static Private Attributes
static constexpr size_t RecursionMaxDepth = 1000
Friends
class LinearScheduler
Detailed Description
Definition at line 90 of file revectorizer.h.
Constructor & Destructor Documentation
SLPTree()
v8::internal::compiler::SLPTree::SLPTree (Zone * zone, TFGraph * graph) [inline], [explicit]
Definition at line 92 of file revectorizer.h.
      : zone_(zone),
        graph_(graph),
        root_(nullptr),
        on_stack_(zone),
        stack_(zone),
        node_to_packnode_(zone) {
    scheduler_ = zone->New<LinearScheduler>(zone, graph);
  }
References graph(), v8::internal::Zone::New(), scheduler_, and zone().
Member Function Documentation
AllOnStack()
bool v8::internal::compiler::SLPTree::AllOnStack (const ZoneVector< Node * > & node_group) [private]
Definition at line 509 of file revectorizer.cc.
                                                            {
  for (auto node : node_group) {
    if (OnStack(node)) return true;
  }
  return false;
}
References OnStack().
Referenced by BuildTreeRec().
BuildTree()
PackNode * v8::internal::compiler::SLPTree::BuildTree (const ZoneVector< Node * > & roots)
Definition at line 612 of file revectorizer.cc.
                                                           {
  TRACE("Enter %s\n", __func__);
  DeleteTree();
  root_ = BuildTreeRec(roots, 0);
  return root_;
}
References BuildTreeRec(), DeleteTree(), root_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::Revectorizer::ReduceStoreChain().
BuildTreeRec()
PackNode * v8::internal::compiler::SLPTree::BuildTreeRec (const ZoneVector< Node * > & node_group, unsigned depth) [private]
Definition at line 621 of file revectorizer.cc.
                                                          {
  TRACE("Enter %s\n", __func__);
  DCHECK_EQ(node_group.size(), 2);
  Node* node0 = node_group[0];
  Node* node1 = node_group[1];
  if (recursion_depth == RecursionMaxDepth) {
    TRACE("Failed due to max recursion depth!\n");
    return nullptr;
  }
  if (AllOnStack(node_group)) {
    if (!StackTopIsPhi()) {
      TRACE("Failed due to (%d %s, %d %s) on stack!\n", node0->id(),
            node0->op()->mnemonic(), node1->id(), node1->op()->mnemonic());
      return nullptr;
    }
  }
  PushStack(node_group);
  if (!CanBePacked(node_group)) {
    return nullptr;
  }
  DCHECK(AllConstant(node_group) || AllPackableOperator(node_group) ||
         MaybePackSignExtensionOp(node_group));
  // Check if this is a duplicate of another entry.
  for (Node* node : node_group) {
    if (PackNode* p = GetPackNode(node)) {
      if (!p->IsSame(node_group)) {
        // TODO(jiepan): Gathering due to partial overlap
        TRACE("Failed due to partial overlap at #%d,%s!\n", node->id(),
              node->op()->mnemonic());
        return nullptr;
      }
      PopStack();
      TRACE("Perfect diamond merge at #%d,%s\n", node->id(),
            node->op()->mnemonic());
      return p;
    }
  }
  if (node0->opcode() == IrOpcode::kS128Zero) {
    PackNode* p = NewPackNode(node_group);
    PopStack();
    return p;
  }
  if (node0->opcode() == IrOpcode::kS128Const) {
    PackNode* p = NewPackNode(node_group);
    PopStack();
    return p;
  }
  if (node0->opcode() == IrOpcode::kExtractF128) {
    Node* source = node0->InputAt(0);
    TRACE("Extract leaf node from #%d,%s!\n", source->id(),
          source->op()->mnemonic());
    // For 256 only, check whether they are from the same source
    if (node0->InputAt(0) == node1->InputAt(0) &&
        (node0->InputAt(0)->opcode() == IrOpcode::kLoadTransform
             ? node0 == node1
             : OpParameter<int32_t>(node0->op()) + 1 ==
                   OpParameter<int32_t>(node1->op()))) {
      TRACE("Added a pair of Extract.\n");
      PackNode* pnode = NewPackNode(node_group);
      PopStack();
      return pnode;
    }
    TRACE("Failed due to ExtractF128!\n");
    return nullptr;
  }
  if (IsSupportedLoad(node0)) {
    TRACE("Load leaf node\n");
    if (!AllSameAddress(node_group)) {
      TRACE("Failed due to different load addr!\n");
      PopStack();
      return nullptr;
    }
    if (!IsSplat(node_group)) {
      if (node0->opcode() == IrOpcode::kProtectedLoad &&
          LoadRepresentationOf(node0->op()).representation() !=
              MachineRepresentation::kSimd128) {
        PopStack();
        return nullptr;
      }
      if (!IsSideEffectFreeLoad(node_group)) {
        TRACE("Failed due to dependency check\n");
        PopStack();
        return nullptr;
      }
      // Sort loads by offset
      ZoneVector<Node*> sorted_node_group(node_group.size(), zone_);
      std::partial_sort_copy(node_group.begin(), node_group.end(),
                             sorted_node_group.begin(), sorted_node_group.end(),
                             MemoryOffsetComparer());
      if (!IsContinuousAccess(sorted_node_group)) {
        TRACE("Failed due to non-continuous load!\n");
        PopStack();
        return nullptr;
      }
    } else if (node0->opcode() == IrOpcode::kLoadTransform) {
      LoadTransformParameters params = LoadTransformParametersOf(node0->op());
      if (params.transformation > LoadTransformation::kLast128Splat) {
        TRACE("LoadTransform failed due to unsupported type #%d!\n",
              node0->id());
        PopStack();
        return nullptr;
      }
      DCHECK_GE(params.transformation, LoadTransformation::kFirst128Splat);
    } else {
      TRACE("Failed due to unsupported splat!\n");
      PopStack();
      return nullptr;
    }
    PackNode* p = NewPackNode(node_group);
    PopStack();
    return p;
  }
  int value_in_count = node0->op()->ValueInputCount();
#define CASE(op128, op256) case IrOpcode::k##op128:
#define SIGN_EXTENSION_CASE(op_low, not_used1, not_used2) \
  case IrOpcode::k##op_low:
  switch (node0->opcode()) {
    case IrOpcode::kPhi: {
      TRACE("Added a vector of PHI nodes.\n");
      MachineRepresentation rep = PhiRepresentationOf(node0->op());
      if (rep != MachineRepresentation::kSimd128) {
        return nullptr;
      }
      PackNode* pnode =
          NewPackNodeAndRecurs(node_group, 0, value_in_count, recursion_depth);
      PopStack();
      return pnode;
    }
    case IrOpcode::kLoopExitValue: {
      MachineRepresentation rep = LoopExitValueRepresentationOf(node0->op());
      if (rep != MachineRepresentation::kSimd128) {
        return nullptr;
      }
      PackNode* pnode =
          NewPackNodeAndRecurs(node_group, 0, value_in_count, recursion_depth);
      PopStack();
      return pnode;
    }
    case IrOpcode::kI8x16Shuffle: {
      // Try match 32x8Splat or 64x4Splat.
      if (IsSplat(node_group)) {
        const uint8_t* shuffle = S128ImmediateParameterOf(node0->op()).data();
        int index;
        if ((wasm::SimdShuffle::TryMatchSplat<4>(shuffle, &index) &&
             node0->InputAt(index >> 2)->opcode() ==
                 IrOpcode::kProtectedLoad) ||
            (wasm::SimdShuffle::TryMatchSplat<2>(shuffle, &index) &&
             node0->InputAt(index >> 1)->opcode() ==
                 IrOpcode::kProtectedLoad)) {
          PopStack();
          return NewPackNode(node_group);
        }
        TRACE("Failed to match splat\n");
        PopStack();
        return nullptr;
      } else {
        PopStack();
        return NewPackNodeAndRecurs(node_group, 0, value_in_count,
                                    recursion_depth);
      }
    }
      // clang-format off
    SIMPLE_SIMD_OP(CASE) {
      TRACE("Added a vector of %s.\n", node0->op()->mnemonic());
      PackNode* pnode = NewPackNodeAndRecurs(node_group, 0, value_in_count,
                                              recursion_depth);
      PopStack();
      return pnode;
    }
    SIMD_SHIFT_OP(CASE) {
      if (ShiftBySameScalar(node_group)) {
        TRACE("Added a vector of %s.\n", node0->op()->mnemonic());
        PackNode* pnode =
            NewPackNodeAndRecurs(node_group, 0, 1, recursion_depth);
        PopStack();
        return pnode;
      }
      TRACE("Failed due to shift with different scalar!\n");
      return nullptr;
    }
    SIMD_SIGN_EXTENSION_CONVERT_OP(SIGN_EXTENSION_CASE) {
      TRACE("add a vector of sign extension op and stop building tree\n");
      PackNode* pnode = NewPackNode(node_group);
      PopStack();
      return pnode;
    }
    SIMD_SPLAT_OP(CASE) {
      TRACE("Added a vector of %s.\n", node0->op()->mnemonic());
      if (node0->InputAt(0) != node1->InputAt(0)) {
        TRACE("Failed due to different splat input");
        return nullptr;
      }
      PackNode* pnode = NewPackNode(node_group);
      PopStack();
      return pnode;
    }
    // clang-format on
    // TODO(jiepan): UnalignedStore, StoreTrapOnNull.
    case IrOpcode::kStore:
    case IrOpcode::kProtectedStore: {
      TRACE("Added a vector of stores.\n");
      if (!AllSameAddress(node_group)) {
        TRACE("Failed due to different store addr!\n");
        return nullptr;
      }
      PackNode* pnode = NewPackNodeAndRecurs(node_group, 2, 1, recursion_depth);
      PopStack();
      return pnode;
    }
    default:
      TRACE("Default branch #%d:%s\n", node0->id(), node0->op()->mnemonic());
      break;
  }
#undef CASE
#undef SIGN_EXTENSION_CASE
  return nullptr;
}
References v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllConstant(), AllOnStack(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllPackableOperator(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllSameAddress(), v8::internal::ZoneVector< T >::begin(), CanBePacked(), CASE, v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::ZoneVector< T >::end(), GetPackNode(), v8::internal::compiler::Node::id(), v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsContinuousAccess(), IsSideEffectFreeLoad(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSplat(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSupportedLoad(), v8::internal::compiler::kFirst128Splat, v8::internal::compiler::kLast128Splat, v8::internal::kSimd128, v8::internal::compiler::LoadRepresentationOf(), v8::internal::compiler::LoadTransformParametersOf(), v8::internal::compiler::LoopExitValueRepresentationOf(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::MaybePackSignExtensionOp(), v8::internal::compiler::Operator::mnemonic(), NewPackNode(), NewPackNodeAndRecurs(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::PhiRepresentationOf(), PopStack(), PushStack(), RecursionMaxDepth, v8::internal::MachineType::representation(), v8::internal::compiler::S128ImmediateParameterOf(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::ShiftBySameScalar(), SIGN_EXTENSION_CASE, SIMD_SHIFT_OP, SIMD_SIGN_EXTENSION_CONVERT_OP, SIMD_SPLAT_OP, SIMPLE_SIMD_OP, v8::internal::ZoneVector< T >::size(), StackTopIsPhi(), v8::internal::TRACE(), v8::internal::compiler::LoadTransformParameters::transformation, v8::internal::compiler::Operator::ValueInputCount(), and zone_.
Referenced by BuildTree(), and NewPackNodeAndRecurs().
CanBePacked()
bool v8::internal::compiler::SLPTree::CanBePacked (const ZoneVector< Node * > & node_group) [private]
Definition at line 401 of file revectorizer.cc.
                                                             {
  DCHECK_EQ(node_group.size(), 2);
  // Only Support simd128 operators or common operators with simd128
  // MachineRepresentation. The MachineRepresentation of root had been checked,
  // and the leaf node will be checked later. here we omit the check of
  // MachineRepresentation, only check the opcode itself.
  IrOpcode::Value op = node_group[0]->opcode();
  if (!NodeProperties::IsSimd128Operation(node_group[0]) &&
      (op != IrOpcode::kStore) && (op != IrOpcode::kProtectedStore) &&
      (op != IrOpcode::kLoad) && (op != IrOpcode::kProtectedLoad) &&
      (op != IrOpcode::kPhi) && (op != IrOpcode::kLoopExitValue) &&
      (op != IrOpcode::kExtractF128)) {
    return false;
  }
  // TODO(jiepan): add support for Constant
  if (AllConstant(node_group)) {
    TRACE("%s(#%d, #%d) are constantant, not supported yet!\n",
          node_group[0]->op()->mnemonic(), node_group[0]->id(),
          node_group[1]->id());
    return false;
  }
  if (IsSignExtensionOperation(op)) {
    if (MaybePackSignExtensionOp(node_group)) {
      return true;
    } else {
      TRACE("%s(#%d, #%d) are not (low, high) sign extension pair\n",
            node_group[0]->op()->mnemonic(), node_group[0]->id(),
            node_group[1]->id());
      return false;
    }
  }
  if (!AllPackableOperator(node_group)) {
    TRACE(
        "%s(#%d, #%d) have different op, and are not sign extension operator\n",
        node_group[0]->op()->mnemonic(), node_group[0]->id(),
        node_group[1]->id());
    return false;
  }
  return true;
}
References v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllConstant(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllPackableOperator(), DCHECK_EQ, v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSignExtensionOperation(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::MaybePackSignExtensionOp(), v8::internal::ZoneVector< T >::size(), and v8::internal::TRACE().
Referenced by BuildTreeRec().
ClearStack()
void v8::internal::compiler::SLPTree::ClearStack () [private]
Definition at line 522 of file revectorizer.cc.
                         {
  stack_ = ZoneStack<ZoneVector<Node*>>(zone_);
  on_stack_.clear();
}
References on_stack_, stack_, and zone_.
Referenced by DeleteTree().
DeleteTree()
void v8::internal::compiler::SLPTree::DeleteTree ()
Definition at line 856 of file revectorizer.cc.
                         {
  ClearStack();
  node_to_packnode_.clear();
}
References ClearStack(), and node_to_packnode_.
Referenced by BuildTree().
ForEach()
template<typename FunctionType >
void v8::internal::compiler::SLPTree::ForEach (FunctionType callback)
Definition at line 871 of file revectorizer.cc.
                                           {
  std::unordered_set<PackNode const*> visited;
  for (auto& entry : node_to_packnode_) {
    PackNode const* pnode = entry.second;
    if (!pnode || visited.find(pnode) != visited.end()) {
      continue;
    }
    visited.insert(pnode);
    callback(pnode);
  }
}
References node_to_packnode_.
Referenced by v8::internal::compiler::Revectorizer::DecideVectorize(), Print(), and v8::internal::compiler::Revectorizer::ReduceStoreChain().
GetEarlySchedulePosition()
Node* v8::internal::compiler::SLPTree::GetEarlySchedulePosition (Node * node) [inline]
Definition at line 112 of file revectorizer.h.
                                             {
    return scheduler_->GetEarlySchedulePosition(node);
  }
References v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition(), and scheduler_.
Referenced by v8::internal::compiler::Revectorizer::CollectSeeds().
GetPackNode()
PackNode * v8::internal::compiler::SLPTree::GetPackNode (Node * node)
Definition at line 475 of file revectorizer.cc.
                                         {
  auto I = node_to_packnode_.find(node);
  if (I != node_to_packnode_.end()) {
    return I->second;
  }
  return nullptr;
}
References v8::internal::I, and node_to_packnode_.
Referenced by BuildTreeRec().
graph()
TFGraph* v8::internal::compiler::SLPTree::graph () const [inline], [private]
Definition at line 131 of file revectorizer.h.
{ return graph_; }
References graph_.
Referenced by SLPTree().
IsSideEffectFreeLoad()
bool v8::internal::compiler::SLPTree::IsSideEffectFreeLoad (const ZoneVector< Node * > & node_group) [private]
Definition at line 554 of file revectorizer.cc.
                                                                      {
  DCHECK(IsSupportedLoad(node_group));
  DCHECK_EQ(node_group.size(), 2);
  TRACE("Enter IsSideEffectFreeLoad (%d %s, %d %s)\n", node_group[0]->id(),
        node_group[0]->op()->mnemonic(), node_group[1]->id(),
        node_group[1]->op()->mnemonic());
  TryReduceLoadChain(node_group);
  // We only allows Loads that are connected by effect edges.
  if (node_group[0] != node_group[1] &&
      NodeProperties::GetEffectInput(node_group[0]) != node_group[1] &&
      NodeProperties::GetEffectInput(node_group[1]) != node_group[0])
    return false;
  std::stack<Node*> to_visit;
  std::unordered_set<Node*> visited;
  // Visit all the inputs (except for control inputs) of Loads.
  for (size_t i = 0, e = node_group.size(); i < e; i++) {
    Node* load = node_group[i];
    for (int j = 0; j < NodeProperties::FirstControlIndex(load); ++j) {
      Node* input = load->InputAt(j);
      if (std::find(node_group.begin(), node_group.end(), input) ==
          node_group.end()) {
        to_visit.push(input);
      }
    }
  }
  // Check the inputs of Loads and find if they are connected to existing nodes
  // in SLPTree. If there is, then there will be side effect and we can not
  // merge such Loads.
  while (!to_visit.empty()) {
    Node* input = to_visit.top();
    to_visit.pop();
    TRACE("IsSideEffectFreeLoad visit (%d %s)\n", input->id(),
          input->op()->mnemonic());
    if (visited.find(input) == visited.end()) {
      visited.insert(input);
      if (OnStack(input)) {
        TRACE("Has internal dependency because (%d %s) on stack\n", input->id(),
              input->op()->mnemonic());
        return false;
      }
      // If the input is not in same basic block as Loads, it must not be in
      // SLPTree. Otherwise recursively visit all input's edges and find if they
      // are connected to SLPTree.
      if (SameBasicBlock(input, node_group[0])) {
        for (int i = 0; i < NodeProperties::FirstControlIndex(input); ++i) {
          to_visit.push(input->InputAt(i));
        }
      }
    }
  }
  return true;
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ZoneVector< T >::end(), v8::internal::compiler::NodeProperties::FirstControlIndex(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSupportedLoad(), v8::internal::compiler::Operator::mnemonic(), OnStack(), v8::internal::compiler::Node::op(), SameBasicBlock(), v8::internal::ZoneVector< T >::size(), v8::internal::TRACE(), and TryReduceLoadChain().
Referenced by BuildTreeRec().
NewPackNode()
PackNode * v8::internal::compiler::SLPTree::NewPackNode (const ZoneVector< Node * > & node_group) [private]
Definition at line 443 of file revectorizer.cc.
                                                                  {
  TRACE("PackNode %s(#%d:, #%d)\n", node_group[0]->op()->mnemonic(),
        node_group[0]->id(), node_group[1]->id());
  PackNode* pnode = zone_->New<PackNode>(zone_, node_group);
  for (Node* node : node_group) {
    node_to_packnode_[node] = pnode;
  }
  return pnode;
}
References v8::internal::Zone::New(), node_to_packnode_, v8::internal::TRACE(), and zone_.
Referenced by BuildTreeRec(), and NewPackNodeAndRecurs().
NewPackNodeAndRecurs()
PackNode * v8::internal::compiler::SLPTree::NewPackNodeAndRecurs (const ZoneVector< Node * > & node_group, int start_index, int count, unsigned depth) [private]
Definition at line 453 of file revectorizer.cc.
                                                                  {
  PackNode* pnode = NewPackNode(node_group);
  for (int i = start_index; i < start_index + count; ++i) {
    ZoneVector<Node*> operands(zone_);
    // Prepare the operand vector.
    for (size_t j = 0; j < node_group.size(); j++) {
      Node* node = node_group[j];
      operands.push_back(NodeProperties::GetValueInput(node, i));
    }
    PackNode* child = BuildTreeRec(operands, recursion_depth + 1);
    if (child) {
      pnode->SetOperand(i, child);
    } else {
      return nullptr;
    }
  }
  return pnode;
}
References BuildTreeRec(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, NewPackNode(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::PackNode::SetOperand(), v8::internal::ZoneVector< T >::size(), and zone_.
Referenced by BuildTreeRec().
OnStack()
bool v8::internal::compiler::SLPTree::OnStack (Node * node) [private]
Definition at line 505 of file revectorizer.cc.
                                {
  return on_stack_.find(node) != on_stack_.end();
}
References on_stack_.
Referenced by AllOnStack(), and IsSideEffectFreeLoad().
PopStack()
void v8::internal::compiler::SLPTree::PopStack () [private]
Definition at line 493 of file revectorizer.cc.
                       {
  const ZoneVector<Node*>& node_group = stack_.top();
  DCHECK_EQ(node_group.size(), 2);
  TRACE("Stack Pop (%d %s, %d %s)\n", node_group[0]->id(),
        node_group[0]->op()->mnemonic(), node_group[1]->id(),
        node_group[1]->op()->mnemonic());
  for (auto node : node_group) {
    on_stack_.erase(node);
  }
  stack_.pop();
}
References DCHECK_EQ, on_stack_, v8::internal::ZoneVector< T >::size(), stack_, and v8::internal::TRACE().
Referenced by BuildTreeRec().
Print()
void v8::internal::compiler::SLPTree::Print (const char * info)
Definition at line 861 of file revectorizer.cc.
                                    {
  TRACE("%s, Packed node:\n", info);
  if (!v8_flags.trace_wasm_revectorize) {
    return;
  }
  ForEach([](PackNode const* pnode) { pnode->Print(); });
}
References ForEach(), v8::internal::compiler::PackNode::Print(), v8::internal::TRACE(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::Revectorizer::ReduceStoreChain().
PushStack()
void v8::internal::compiler::SLPTree::PushStack (const ZoneVector< Node * > & node_group) [private]
Definition at line 483 of file revectorizer.cc.
                                                           {
  TRACE("Stack Push (%d %s, %d %s)\n", node_group[0]->id(),
        node_group[0]->op()->mnemonic(), node_group[1]->id(),
        node_group[1]->op()->mnemonic());
  for (auto node : node_group) {
    on_stack_.insert(node);
  }
  stack_.push({node_group});
}
References on_stack_, stack_, and v8::internal::TRACE().
Referenced by BuildTreeRec().
SameBasicBlock()
bool v8::internal::compiler::SLPTree::SameBasicBlock (Node * node0, Node * node1) [inline], [private]
Definition at line 144 of file revectorizer.h.
                                                {
    return scheduler_->SameBasicBlock(node0, node1);
  }
References v8::internal::compiler::LinearScheduler::SameBasicBlock(), and scheduler_.
Referenced by IsSideEffectFreeLoad(), and TryReduceLoadChain().
StackTopIsPhi()
bool v8::internal::compiler::SLPTree::StackTopIsPhi () [private]
Definition at line 516 of file revectorizer.cc.
                            {
  const ZoneVector<Node*>& node_group = stack_.top();
  DCHECK_EQ(node_group.size(), 2);
  return NodeProperties::IsPhi(node_group[0]);
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::ZoneVector< T >::size(), and stack_.
Referenced by BuildTreeRec().
TryReduceLoadChain()
void v8::internal::compiler::SLPTree::TryReduceLoadChain (const ZoneVector< Node * > & loads) [private]
Definition at line 531 of file revectorizer.cc.
                                                               {
  ZoneSet<Node*> visited(zone());
  for (Node* load : loads) {
    if (visited.find(load) != visited.end()) continue;
    visited.insert(load);
    EffectChainIterator dest(load);
    EffectChainIterator it(dest.Next());
    while (SameBasicBlock(*it, load) && IsSupportedLoad(*it)) {
      if (std::find(loads.begin(), loads.end(), *it) != loads.end()) {
        visited.insert(*it);
        if (dest.Next() != *it) {
          Node* prev = it.Prev();
          InsertAfter(dest, it);
          it.Set(prev);
        }
        dest.Advance();
      }
      it.Advance();
    }
  }
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::InsertAfter(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSupportedLoad(), SameBasicBlock(), and zone().
Referenced by IsSideEffectFreeLoad().
zone()
Zone* v8::internal::compiler::SLPTree::zone () const [inline], [private]
Definition at line 132 of file revectorizer.h.
{ return zone_; }
References zone_.
Referenced by SLPTree(), and TryReduceLoadChain().
Friends And Related Function Documentation
LinearScheduler
friend class LinearScheduler [friend]
Definition at line 117 of file revectorizer.h.
Member Data Documentation
graph_
TFGraph* const v8::internal::compiler::SLPTree::graph_ [private]
Definition at line 149 of file revectorizer.h.
Referenced by graph().
node_to_packnode_
ZoneUnorderedMap<Node*, PackNode*> v8::internal::compiler::SLPTree::node_to_packnode_ [private]
Definition at line 155 of file revectorizer.h.
Referenced by DeleteTree(), ForEach(), GetPackNode(), and NewPackNode().
on_stack_
ZoneSet<Node*> v8::internal::compiler::SLPTree::on_stack_ [private]
Definition at line 152 of file revectorizer.h.
Referenced by ClearStack(), OnStack(), PopStack(), and PushStack().
RecursionMaxDepth
constexpr size_t v8::internal::compiler::SLPTree::RecursionMaxDepth = 1000 [static], [constexpr], [private]
Definition at line 156 of file revectorizer.h.
Referenced by BuildTreeRec().
root_
PackNode* v8::internal::compiler::SLPTree::root_ [private]
Definition at line 150 of file revectorizer.h.
Referenced by BuildTree().
scheduler_
LinearScheduler* v8::internal::compiler::SLPTree::scheduler_ [private]
Definition at line 151 of file revectorizer.h.
Referenced by GetEarlySchedulePosition(), SameBasicBlock(), and SLPTree().
stack_
ZoneStack<ZoneVector<Node*> > v8::internal::compiler::SLPTree::stack_ [private]
Definition at line 153 of file revectorizer.h.
Referenced by ClearStack(), PopStack(), PushStack(), and StackTopIsPhi().
zone_
Zone* const v8::internal::compiler::SLPTree::zone_ [private]
Definition at line 148 of file revectorizer.h.
Referenced by BuildTreeRec(), ClearStack(), NewPackNode(), NewPackNodeAndRecurs(), and zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/revectorizer.h
/mnt/V8SourceCode/src/compiler/revectorizer.cc