v8::internal::DateParser::DayComposer Class Reference
Public Member Functions
DayComposer ()
bool IsEmpty () const
bool Add (int n)
void SetNamedMonth (int n)
bool Write (double *output)
void set_iso_date ()
Static Public Member Functions
static bool IsMonth (int x)
static bool IsDay (int x)
Private Attributes
int comp_ [kSize]
int index_
int named_month_
bool is_iso_date_
Static Private Attributes
static const int kSize = 3
Detailed Description
Definition at line 327 of file dateparser.h.
Constructor & Destructor Documentation
DayComposer()
v8::internal::DateParser::DayComposer::DayComposer () [inline]
Definition at line 329 of file dateparser.h.
: index_(0), named_month_(kNone), is_iso_date_(false) {}
Member Function Documentation
Add()
bool v8::internal::DateParser::DayComposer::Add (int n) [inline]
Definition at line 331 of file dateparser.h.
                    {
      if (index_ < kSize) {
        comp_[index_] = n;
        index_++;
        return true;
      }
      return false;
    }
References comp_, index_, and kSize.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
IsDay()
static bool v8::internal::DateParser::DayComposer::IsDay (int x) [inline], [static]
Definition at line 343 of file dateparser.h.
{ return Between(x, 1, 31); }
References v8::internal::DateParser::Between().
Referenced by v8::internal::DateParser::ParseES5DateTime(), and Write().
IsEmpty()
bool v8::internal::DateParser::DayComposer::IsEmpty () const [inline]
Definition at line 330 of file dateparser.h.
{ return index_ == 0; }
References index_.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
IsMonth()
static bool v8::internal::DateParser::DayComposer::IsMonth (int x) [inline], [static]
Definition at line 342 of file dateparser.h.
{ return Between(x, 1, 12); }
References v8::internal::DateParser::Between().
Referenced by v8::internal::DateParser::ParseES5DateTime(), and Write().
set_iso_date()
void v8::internal::DateParser::DayComposer::set_iso_date () [inline]
Definition at line 341 of file dateparser.h.
{ is_iso_date_ = true; }
References is_iso_date_.
Referenced by v8::internal::DateParser::ParseES5DateTime().
SetNamedMonth()
void v8::internal::DateParser::DayComposer::SetNamedMonth (int n) [inline]
Definition at line 339 of file dateparser.h.
{ named_month_ = n; }
References named_month_.
Referenced by v8::internal::DateParser::Parse().
Write()
bool v8::internal::DateParser::DayComposer::Write (double * output)
Definition at line 13 of file dateparser.cc.
                                                {
  if (index_ < 1) return false;
  // Day and month defaults to 1.
  while (index_ < kSize) {
    comp_[index_++] = 1;
  }
  int year = 0; // Default year is 0 (=> 2000) for KJS compatibility.
  int month = kNone;
  int day = kNone;
  if (named_month_ == kNone) {
    if (is_iso_date_ || (index_ == 3 && !IsDay(comp_[0]))) {
      // YMD
      year = comp_[0];
      month = comp_[1];
      day = comp_[2];
    } else {
      // MD(Y)
      month = comp_[0];
      day = comp_[1];
      if (index_ == 3) year = comp_[2];
    }
  } else {
    month = named_month_;
    if (index_ == 1) {
      // MD or DM
      day = comp_[0];
    } else if (!IsDay(comp_[0])) {
      // YMD, MYD, or YDM
      year = comp_[0];
      day = comp_[1];
    } else {
      // DMY, MDY, or DYM
      day = comp_[0];
      year = comp_[1];
    }
  }
  if (!is_iso_date_) {
    if (Between(year, 0, 49))
      year += 2000;
    else if (Between(year, 50, 99))
      year += 1900;
  }
  if (!Smi::IsValid(year) || !IsMonth(month) || !IsDay(day)) return false;
  output[YEAR] = year;
  output[MONTH] = month - 1; // 0-based
  output[DAY] = day;
  return true;
}
References v8::internal::DateParser::Between(), comp_, v8::internal::DateParser::DAY, index_, is_iso_date_, IsDay(), IsMonth(), v8::internal::Smi::IsValid(), v8::internal::DateParser::kNone, kSize, v8::internal::DateParser::MONTH, named_month_, and v8::internal::DateParser::YEAR.
Referenced by v8::internal::DateParser::Parse().
Member Data Documentation
comp_
int v8::internal::DateParser::DayComposer::comp_[kSize] [private]
Definition at line 347 of file dateparser.h.
Referenced by Add(), and Write().
index_
int v8::internal::DateParser::DayComposer::index_ [private]
Definition at line 348 of file dateparser.h.
Referenced by Add(), IsEmpty(), and Write().
is_iso_date_
bool v8::internal::DateParser::DayComposer::is_iso_date_ [private]
Definition at line 351 of file dateparser.h.
Referenced by set_iso_date(), and Write().
kSize
const int v8::internal::DateParser::DayComposer::kSize = 3 [static], [private]
Definition at line 346 of file dateparser.h.
Referenced by Add(), and Write().
named_month_
int v8::internal::DateParser::DayComposer::named_month_ [private]
Definition at line 349 of file dateparser.h.
Referenced by SetNamedMonth(), and Write().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/date/dateparser.h
/mnt/V8SourceCode/src/date/dateparser.cc