v8::base::internal::CheckedNumeric< T > Class Template Reference
#include <checked_math.h>
Classes
struct Wrapper
struct Wrapper< CheckedNumeric< Src > >
struct Wrapper< StrictNumeric< Src > >
Public Types
using type = T
Public Member Functions
constexpr CheckedNumeric ()=default
template<typename Src >
constexpr CheckedNumeric (const CheckedNumeric< Src > &rhs)
template<typename Src >
requires (std::is_arithmetic_v< Src >) const expr CheckedNumeric(Src value)
template<typename Src >
constexpr CheckedNumeric (StrictNumeric< Src > value)
template<typename Dst = T>
constexpr bool IsValid () const
template<typename Dst >
constexpr bool AssignIfValid (Dst *result) const
template<typename Dst = T, class CheckHandler = CheckOnFailure>
constexpr StrictNumeric< Dst > ValueOrDie () const
template<typename Dst = T, typename Src >
constexpr StrictNumeric< Dst > ValueOrDefault (Src default_value) const
template<typename Dst >
constexpr CheckedNumeric< UnderlyingType< Dst > > Cast () const
template<typename Src >
constexpr CheckedNumeric & operator+= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator-= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator*= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator/= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator%= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator<<= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator>>= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator&= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator|= (const Src rhs)
template<typename Src >
constexpr CheckedNumeric & operator^= (const Src rhs)
constexpr CheckedNumeric operator- () const
constexpr CheckedNumeric operator~ () const
constexpr CheckedNumeric Abs () const
template<typename U >
constexpr CheckedNumeric< typename MathWrapper< CheckedMaxOp, T, U >::type > Max (U rhs) const
template<typename U >
constexpr CheckedNumeric< typename MathWrapper< CheckedMinOp, T, U >::type > Min (U rhs) const
constexpr CheckedNumeric< typename UnsignedOrFloatForSize< T >::type > UnsignedAbs () const
constexpr CheckedNumeric & operator++ ()
constexpr CheckedNumeric operator++ (int)
constexpr CheckedNumeric & operator-- ()
constexpr CheckedNumeric operator-- (int)
template<template< typename, typename > class M, typename R >
constexpr CheckedNumeric & MathOp (R rhs)
Static Public Member Functions
template<template< typename, typename > class M, typename L , typename R >
static constexpr CheckedNumeric MathOp (L lhs, R rhs)
Private Member Functions
CheckedNumeric FastRuntimeNegate () const
template<typename Src >
constexpr CheckedNumeric (Src value, bool is_valid)
Private Attributes
template<typename U >
requires friend class CheckedNumeric
CheckedNumericState< T > state_
Friends
template<typename U >
U GetNumericValueForTest (const CheckedNumeric< U > &src)
Detailed Description
template<typename T>
class v8::base::internal::CheckedNumeric< T >
Definition at line 25 of file checked_math.h.
Member Typedef Documentation
type
template<typename T >
using v8::base::internal::CheckedNumeric< T >::type = T
Definition at line 27 of file checked_math.h.
Constructor & Destructor Documentation
CheckedNumeric() [1/4]
template<typename T >
constexpr v8::base::internal::CheckedNumeric< T >::CheckedNumeric () [constexpr], [default]
CheckedNumeric() [2/4]
template<typename T >
template<typename Src >
constexpr v8::base::internal::CheckedNumeric< T >::CheckedNumeric (const CheckedNumeric< Src > & rhs) [inline], [constexpr]
Definition at line 33 of file checked_math.h.
      : state_(rhs.state_.value(), rhs.IsValid()) {}
CheckedNumeric() [3/4]
template<typename T >
template<typename Src >
constexpr v8::base::internal::CheckedNumeric< T >::CheckedNumeric (StrictNumeric< Src > value) [inline], [constexpr]
Definition at line 47 of file checked_math.h.
      : state_(static_cast<Src>(value)) {}
CheckedNumeric() [4/4]
template<typename T >
template<typename Src >
constexpr v8::base::internal::CheckedNumeric< T >::CheckedNumeric (Src value, bool is_valid) [inline], [constexpr], [private]
Definition at line 247 of file checked_math.h.
      : state_(value, is_valid) {}
Member Function Documentation
Abs()
template<typename T >
constexpr CheckedNumeric v8::base::internal::CheckedNumeric< T >::Abs () const [inline], [constexpr]
Definition at line 162 of file checked_math.h.
                                       {
    return !IsValueNegative(state_.value()) ? *this : -*this;
  }
References v8::base::internal::CheckedNumeric< T >::state_, and v8::internal::this.
AssignIfValid()
template<typename T >
template<typename Dst >
constexpr bool v8::base::internal::CheckedNumeric< T >::AssignIfValid (Dst * result) const [inline], [constexpr]
Definition at line 69 of file checked_math.h.
                                   {
    if (IsValid<Dst>()) [[likely]] {
      *result = static_cast<Dst>(state_.value());
      return true;
    }
    return false;
  }
References v8::base::internal::result, and v8::base::internal::CheckedNumeric< T >::state_.
Cast()
template<typename T >
template<typename Dst >
constexpr CheckedNumeric<UnderlyingType<Dst> > v8::base::internal::CheckedNumeric< T >::Cast () const [inline], [constexpr]
Definition at line 111 of file checked_math.h.
                                                             {
    return *this;
  }
FastRuntimeNegate()
template<typename T >
CheckedNumeric v8::base::internal::CheckedNumeric< T >::FastRuntimeNegate () const [inline], [private]
Definition at line 240 of file checked_math.h.
                                           {
    T result;
    const bool success = CheckedSubOp<T, T>::Do(T(0), state_.value(), &result);
    return CheckedNumeric<T>(result, IsValid() && success);
  }
References v8::base::internal::Do(), v8::base::internal::CheckedNumeric< T >::IsValid(), v8::base::internal::result, v8::base::internal::CheckedNumeric< T >::state_, and v8::base::internal::T.
Referenced by v8::base::internal::CheckedNumeric< T >::operator-().
IsValid()
template<typename T >
template<typename Dst = T>
constexpr bool v8::base::internal::CheckedNumeric< T >::IsValid () const [inline], [constexpr]
Definition at line 54 of file checked_math.h.
                                 {
    return state_.is_valid() &&
           IsValueInRangeForNumericType<Dst>(state_.value());
  }
References v8::base::internal::CheckedNumeric< T >::state_.
Referenced by v8::base::internal::CheckedNumeric< T >::FastRuntimeNegate(), v8::base::internal::CheckedNumeric< T >::Wrapper< CheckedNumeric< Src > >::is_valid(), v8::base::internal::CheckedNumeric< T >::operator-(), and v8::base::internal::CheckedNumeric< T >::operator~().
MathOp() [1/2]
template<typename T >
template<template< typename, typename > class M, typename L , typename R >
static constexpr CheckedNumeric v8::base::internal::CheckedNumeric< T >::MathOp (L lhs, R rhs) [inline], [static], [constexpr]
Definition at line 212 of file checked_math.h.
                                                       {
    using Math = typename MathWrapper<M, L, R>::math;
    T result = 0;
    const bool is_valid =
        Wrapper<L>::is_valid(lhs) && Wrapper<R>::is_valid(rhs) &&
        Math::Do(Wrapper<L>::value(lhs), Wrapper<R>::value(rhs), &result);
    return CheckedNumeric<T>(result, is_valid);
  }
References v8::base::internal::Do(), v8::base::internal::CheckedNumeric< T >::Wrapper< Src >::is_valid(), and v8::base::internal::result.
MathOp() [2/2]
template<typename T >
template<template< typename, typename > class M, typename R >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::MathOp (R rhs) [inline], [constexpr]
Definition at line 223 of file checked_math.h.
                                          {
    using Math = typename MathWrapper<M, T, R>::math;
    T result = 0; // Using T as the destination saves a range check.
    const bool is_valid =
        state_.is_valid() && Wrapper<R>::is_valid(rhs) &&
        Math::Do(state_.value(), Wrapper<R>::value(rhs), &result);
    *this = CheckedNumeric<T>(result, is_valid);
    return *this;
  }
References v8::base::internal::Do(), v8::base::internal::CheckedNumeric< T >::Wrapper< Src >::is_valid(), v8::base::internal::result, and v8::base::internal::CheckedNumeric< T >::state_.
Max()
template<typename T >
template<typename U >
constexpr CheckedNumeric<typename MathWrapper<CheckedMaxOp, T, U>::type> v8::base::internal::CheckedNumeric< T >::Max (U rhs) const [inline], [constexpr]
Definition at line 167 of file checked_math.h.
                   {
    return CheckMax(*this, rhs);
  }
Min()
template<typename T >
template<typename U >
constexpr CheckedNumeric<typename MathWrapper<CheckedMinOp, T, U>::type> v8::base::internal::CheckedNumeric< T >::Min (U rhs) const [inline], [constexpr]
Definition at line 173 of file checked_math.h.
                   {
    return CheckMin(*this, rhs);
  }
operator%=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator%= (const Src rhs) [constexpr]
operator&=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator&= (const Src rhs) [constexpr]
operator*=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator*= (const Src rhs) [constexpr]
operator++() [1/2]
template<typename T >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator++ () [inline], [constexpr]
Definition at line 187 of file checked_math.h.
                                         {
    *this += 1;
    return *this;
  }
operator++() [2/2]
template<typename T >
constexpr CheckedNumeric v8::base::internal::CheckedNumeric< T >::operator++ (int) [inline], [constexpr]
Definition at line 192 of file checked_math.h.
                                           {
    const CheckedNumeric value = *this;
    ++*this;
    return value;
  }
References v8::internal::value.
operator+=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator+= (const Src rhs) [constexpr]
operator-()
template<typename T >
constexpr CheckedNumeric v8::base::internal::CheckedNumeric< T >::operator- () const [inline], [constexpr]
Definition at line 143 of file checked_math.h.
                                             {
    // Use an optimized code path for a known run-time variable.
    if (!std::is_constant_evaluated() && std::is_signed_v<T> &&
        std::is_floating_point_v<T>) {
      return FastRuntimeNegate();
    }
    // The negation of two's complement int min is int min.
    const bool is_valid =
        IsValid() &&
        (!std::is_signed_v<T> || std::is_floating_point_v<T> ||
         NegateWrapper(state_.value()) != std::numeric_limits<T>::lowest());
    return CheckedNumeric<T>(NegateWrapper(state_.value()), is_valid);
  }
References v8::base::internal::CheckedNumeric< T >::FastRuntimeNegate(), v8::base::internal::CheckedNumeric< T >::IsValid(), and v8::base::internal::CheckedNumeric< T >::state_.
operator--() [1/2]
template<typename T >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator-- () [inline], [constexpr]
Definition at line 198 of file checked_math.h.
                                         {
    *this -= 1;
    return *this;
  }
operator--() [2/2]
template<typename T >
constexpr CheckedNumeric v8::base::internal::CheckedNumeric< T >::operator-- (int) [inline], [constexpr]
Definition at line 203 of file checked_math.h.
                                           {
    const CheckedNumeric value = *this;
    --*this;
    return value;
  }
References v8::internal::value.
operator-=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator-= (const Src rhs) [constexpr]
operator/=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator/= (const Src rhs) [constexpr]
operator<<=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator<<= (const Src rhs) [constexpr]
operator>>=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator>>= (const Src rhs) [constexpr]
operator^=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator^= (const Src rhs) [constexpr]
operator|=()
template<typename T >
template<typename Src >
constexpr CheckedNumeric& v8::base::internal::CheckedNumeric< T >::operator|= (const Src rhs) [constexpr]
operator ()
template<typename T >
constexpr CheckedNumeric v8::base::internal::CheckedNumeric< T >::operator~ () const [inline], [constexpr]
Definition at line 157 of file checked_math.h.
                                             {
    return CheckedNumeric<decltype(InvertWrapper(T()))>(
        InvertWrapper(state_.value()), IsValid());
  }
References v8::base::internal::CheckedNumeric< T >::IsValid(), and v8::base::internal::CheckedNumeric< T >::state_.
requires()
template<typename T >
template<typename Src >
v8::base::internal::CheckedNumeric< T >::requires (std::is_arithmetic_v< Src >) const [inline]
Definition at line 39 of file checked_math.h.
                                      : state_(value) {}
UnsignedAbs()
template<typename T >
constexpr CheckedNumeric<typename UnsignedOrFloatForSize<T>::type> v8::base::internal::CheckedNumeric< T >::UnsignedAbs () const [inline], [constexpr]
Definition at line 182 of file checked_math.h.
                      {
    return CheckedNumeric<typename UnsignedOrFloatForSize<T>::type>(
        SafeUnsignedAbs(state_.value()), state_.is_valid());
  }
References v8::base::internal::SafeUnsignedAbs(), and v8::base::internal::CheckedNumeric< T >::state_.
ValueOrDefault()
template<typename T >
template<typename Dst = T, typename Src >
constexpr StrictNumeric<Dst> v8::base::internal::CheckedNumeric< T >::ValueOrDefault (Src default_value) const [inline], [constexpr]
Definition at line 100 of file checked_math.h.
                                                                       {
    if (IsValid<Dst>()) [[likely]] {
      return static_cast<Dst>(state_.value());
    }
    return checked_cast<Dst>(default_value);
  }
References v8::base::internal::CheckedNumeric< T >::state_.
ValueOrDie()
template<typename T >
template<typename Dst = T, class CheckHandler = CheckOnFailure>
constexpr StrictNumeric<Dst> v8::base::internal::CheckedNumeric< T >::ValueOrDie () const [inline], [constexpr]
Definition at line 86 of file checked_math.h.
                                                  {
    if (IsValid<Dst>()) [[likely]] {
      return static_cast<Dst>(state_.value());
    }
    return CheckHandler::template HandleFailure<Dst>();
  }
References v8::base::internal::CheckedNumeric< T >::state_.
Friends And Related Function Documentation
GetNumericValueForTest
template<typename T >
template<typename U >
U GetNumericValueForTest (const CheckedNumeric< U > & src) [friend]
Member Data Documentation
CheckedNumeric
template<typename T >
template<typename U >
requires friend class v8::base::internal::CheckedNumeric< T >::CheckedNumeric [private]
Definition at line 236 of file checked_math.h.
state_
template<typename T >
CheckedNumericState<T> v8::base::internal::CheckedNumeric< T >::state_ [private]
Definition at line 238 of file checked_math.h.
Referenced by v8::base::internal::CheckedNumeric< T >::Abs(), v8::base::internal::CheckedNumeric< T >::AssignIfValid(), v8::base::internal::CheckedNumeric< T >::FastRuntimeNegate(), v8::base::internal::CheckedNumeric< T >::IsValid(), v8::base::internal::CheckedNumeric< T >::MathOp(), v8::base::internal::CheckedNumeric< T >::operator-(), v8::base::internal::CheckedNumeric< T >::operator~(), v8::base::internal::CheckedNumeric< T >::UnsignedAbs(), v8::base::internal::CheckedNumeric< T >::Wrapper< CheckedNumeric< Src > >::value(), v8::base::internal::CheckedNumeric< T >::ValueOrDefault(), and v8::base::internal::CheckedNumeric< T >::ValueOrDie().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/numerics/checked_math.h