v8::ValueDeserializer::Delegate Class Reference
#include <v8-value-serializer.h>
Public Member Functions
virtual ~Delegate ()=default
virtual MaybeLocal< Object > ReadHostObject (Isolate *isolate)
The embedder overrides this method to read some kind of host object, if possible.
virtual MaybeLocal< WasmModuleObject > GetWasmModuleFromId (Isolate *isolate, uint32_t transfer_id)
Get a WasmModuleObject given a transfer_id previously provided by ValueSerializer::Delegate::GetWasmModuleTransferId.
virtual MaybeLocal< SharedArrayBuffer > GetSharedArrayBufferFromId (Isolate *isolate, uint32_t clone_id)
Get a SharedArrayBuffer given a clone_id previously provided by ValueSerializer::Delegate::GetSharedArrayBufferId.
virtual const SharedValueConveyor * GetSharedValueConveyor (Isolate *isolate)
Get the SharedValueConveyor previously provided by ValueSerializer::Delegate::AdoptSharedValueConveyor.
Detailed Description
Definition at line 217 of file v8-value-serializer.h.
Constructor & Destructor Documentation
 Delegate()
virtual v8::ValueDeserializer::Delegate::~Delegate () [virtual], [default]
Member Function Documentation
GetSharedArrayBufferFromId()
MaybeLocal< SharedArrayBuffer > v8::ValueDeserializer::Delegate::GetSharedArrayBufferFromId (Isolate * isolate, uint32_t clone_id) [virtual]
Get a SharedArrayBuffer given a clone_id previously provided by ValueSerializer::Delegate::GetSharedArrayBufferId.
Reimplemented in v8::Deserializer.
Definition at line 3399 of file api.cc.
                                                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i_isolate->Throw(*i_isolate->factory()->NewError(
      i_isolate->error_function(),
      i::MessageTemplate::kDataCloneDeserializationError));
  return {};
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewError(), and v8::internal::Isolate::Throw().
GetSharedValueConveyor()
const SharedValueConveyor * v8::ValueDeserializer::Delegate::GetSharedValueConveyor (Isolate * isolate) [virtual]
Get the SharedValueConveyor previously provided by ValueSerializer::Delegate::AdoptSharedValueConveyor.
Reimplemented in v8::Deserializer.
Definition at line 3408 of file api.cc.
                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i_isolate->Throw(*i_isolate->factory()->NewError(
      i_isolate->error_function(),
      i::MessageTemplate::kDataCloneDeserializationError));
  return nullptr;
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewError(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::ValueDeserializer::ReadSharedObject().
GetWasmModuleFromId()
MaybeLocal< WasmModuleObject > v8::ValueDeserializer::Delegate::GetWasmModuleFromId (Isolate * isolate, uint32_t transfer_id) [virtual]
Get a WasmModuleObject given a transfer_id previously provided by ValueSerializer::Delegate::GetWasmModuleTransferId.
Reimplemented in v8::Deserializer.
Definition at line 3389 of file api.cc.
                                      {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i_isolate->Throw(*i_isolate->factory()->NewError(
      i_isolate->error_function(),
      i::MessageTemplate::kDataCloneDeserializationError));
  return {};
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewError(), and v8::internal::Isolate::Throw().
ReadHostObject()
MaybeLocal< Object > v8::ValueDeserializer::Delegate::ReadHostObject (Isolate * isolate) [virtual]
The embedder overrides this method to read some kind of host object, if possible.
If not, a suitable exception should be thrown and MaybeLocal<Object>() returned.
Definition at line 3380 of file api.cc.
                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i_isolate->Throw(*i_isolate->factory()->NewError(
      i_isolate->error_function(),
      i::MessageTemplate::kDataCloneDeserializationError));
  return {};
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewError(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::ValueDeserializer::ReadHostObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-value-serializer.h
/mnt/V8SourceCode/src/api/api.cc