v8::internal::compiler::RangeType Class Reference
#include <turbofan-types.h>
Classes
struct Limits
Public Member Functions
double Min () const
double Max () const
Static Public Member Functions
static bool IsInteger (double x)
Private Member Functions
RangeType (BitsetType::bitset bitset, Limits limits)
BitsetType::bitset Lub () const
Static Private Member Functions
static RangeType * New (double min, double max, Zone *zone)
static RangeType * New (Limits lim, Zone *zone)
Private Attributes
friend Zone
BitsetType::bitset bitset_
Limits limits_
Friends
class Type
class BitsetType
class UnionType
Additional Inherited Members
Detailed Description
Definition at line 346 of file turbofan-types.h.
Constructor & Destructor Documentation
RangeType()
v8::internal::compiler::RangeType::RangeType (BitsetType::bitset bitset, Limits limits) [inline], [private]
Definition at line 385 of file turbofan-types.h.
      : TypeBase(kRange), bitset_(bitset), limits_(limits) {}
Member Function Documentation
IsInteger()
static bool v8::internal::compiler::RangeType::IsInteger (double x) [inline], [static]
Definition at line 363 of file turbofan-types.h.
                                  {
    return nearbyint(x) == x && !IsMinusZero(x); // Allows for infinities.
  }
References v8::internal::IsMinusZero().
Referenced by v8::internal::compiler::OtherNumberConstantType::IsOtherNumberConstant(), and New().
Lub()
BitsetType::bitset v8::internal::compiler::RangeType::Lub () const [inline], [private]
Definition at line 388 of file turbofan-types.h.
{ return bitset_; }
References bitset_.
Referenced by v8::internal::compiler::BitsetType::Lub().
Max()
double v8::internal::compiler::RangeType::Max () const [inline]
Definition at line 361 of file turbofan-types.h.
{ return limits_.max; }
References limits_, and v8::internal::compiler::RangeType::Limits::max.
Min()
double v8::internal::compiler::RangeType::Min () const [inline]
Definition at line 360 of file turbofan-types.h.
{ return limits_.min; }
References limits_, and v8::internal::compiler::RangeType::Limits::min.
Referenced by v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().
New() [1/2]
static RangeType* v8::internal::compiler::RangeType::New (double min, double max, Zone * zone) [inline], [static], [private]
Definition at line 373 of file turbofan-types.h.
                                                            {
    return New(Limits(min, max), zone);
  }
New() [2/2]
static RangeType* v8::internal::compiler::RangeType::New (Limits lim, Zone * zone) [inline], [static], [private]
Definition at line 377 of file turbofan-types.h.
                                                {
    DCHECK(IsInteger(lim.min) && IsInteger(lim.max));
    DCHECK(lim.min <= lim.max);
    BitsetType::bitset bits = BitsetType::Lub(lim.min, lim.max);
    return zone->New<RangeType>(bits, lim);
  }
References v8::internal::DCHECK(), IsInteger(), v8::internal::compiler::BitsetType::Lub(), v8::internal::compiler::RangeType::Limits::max, v8::internal::compiler::RangeType::Limits::min, and v8::internal::Zone::New().
Friends And Related Function Documentation
BitsetType
friend class BitsetType [friend]
Definition at line 369 of file turbofan-types.h.
Type
friend class Type [friend]
Definition at line 368 of file turbofan-types.h.
UnionType
friend class UnionType [friend]
Definition at line 370 of file turbofan-types.h.
Member Data Documentation
bitset_
BitsetType::bitset v8::internal::compiler::RangeType::bitset_ [private]
Definition at line 390 of file turbofan-types.h.
Referenced by Lub().
limits_
Limits v8::internal::compiler::RangeType::limits_ [private]
Definition at line 391 of file turbofan-types.h.
Referenced by Max(), and Min().
Zone
friend v8::internal::compiler::RangeType::Zone [private]
Definition at line 371 of file turbofan-types.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turbofan-types.h