v8_inspector::ValueMirror Class Reference
#include <value-mirror.h>
Classes
class PropertyAccumulator
Public Member Functions
virtual ~ValueMirror ()
virtual protocol::Response buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions &wrapOptions, std::unique_ptr< protocol::Runtime::RemoteObject > *result) const =0
virtual void buildPropertyPreview (v8::Local< v8::Context > context, const String16 &name, std::unique_ptr< protocol::Runtime::PropertyPreview > *) const
virtual void buildObjectPreview (v8::Local< v8::Context > context, bool generatePreviewForTable, int *nameLimit, int *indexLimit, std::unique_ptr< protocol::Runtime::ObjectPreview > *) const
virtual void buildEntryPreview (v8::Local< v8::Context > context, int *nameLimit, int *indexLimit, std::unique_ptr< protocol::Runtime::ObjectPreview > *) const
virtual v8::Local< v8::Value > v8Value (v8::Isolate *isolate) const =0
virtual Response buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::DictionaryValue > *result) const =0
Static Public Member Functions
static std::unique_ptr< ValueMirror > create (v8::Local< v8::Context > context, v8::Local< v8::Value > value)
static bool getProperties (v8::Local< v8::Context > context, v8::Local< v8::Object > object, bool ownProperties, bool accessorPropertiesOnly, bool nonIndexedPropertiesOnly, PropertyAccumulator *accumulator)
static void getInternalProperties (v8::Local< v8::Context > context, v8::Local< v8::Object > object, std::vector< InternalPropertyMirror > *mirrors)
static std::vector< PrivatePropertyMirror > getPrivateProperties (v8::Local< v8::Context > context, v8::Local< v8::Object > object, bool accessorPropertiesOnly)
Detailed Description
Definition at line 50 of file value-mirror.h.
Constructor & Destructor Documentation
 ValueMirror()
v8_inspector::ValueMirror::~ValueMirror () [virtual], [default]
Member Function Documentation
buildDeepSerializedValue()
virtual Response v8_inspector::ValueMirror::buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::DictionaryValue > * result) const [pure virtual]
Implemented in v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror, v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror, v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror, v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror, v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror, v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror, and v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror.
Referenced by v8_inspector::InjectedScript::wrapObjectMirror().
buildEntryPreview()
virtual void v8_inspector::ValueMirror::buildEntryPreview (v8::Local< v8::Context > context, int * nameLimit, int * indexLimit, std::unique_ptr< protocol::Runtime::ObjectPreview > *) const [inline], [virtual]
Reimplemented in v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror.
Definition at line 66 of file value-mirror.h.
                                                          {}
buildObjectPreview()
virtual void v8_inspector::ValueMirror::buildObjectPreview (v8::Local< v8::Context > context, bool generatePreviewForTable, int * nameLimit, int * indexLimit, std::unique_ptr< protocol::Runtime::ObjectPreview > *) const [inline], [virtual]
Definition at line 62 of file value-mirror.h.
                                                          {}
buildPropertyPreview()
virtual void v8_inspector::ValueMirror::buildPropertyPreview (v8::Local< v8::Context > context, const String16 & name, std::unique_ptr< protocol::Runtime::PropertyPreview > *) const [inline], [virtual]
Reimplemented in v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror, and v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror.
Definition at line 59 of file value-mirror.h.
                                                            {}
buildRemoteObject()
virtual protocol::Response v8_inspector::ValueMirror::buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions & wrapOptions, std::unique_ptr< protocol::Runtime::RemoteObject > * result) const [pure virtual]
Referenced by v8_inspector::InjectedScript::wrapObjectMirror().
create()
std::unique_ptr< ValueMirror > v8_inspector::ValueMirror::create (v8::Local< v8::Context > context, v8::Local< v8::Value > value) [static]
Definition at line 1817 of file value-mirror.cc.
                                                                         {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  if (value->IsNull()) {
    return std::make_unique<PrimitiveValueMirror>(
        isolate, value.As<v8::Primitive>(), RemoteObject::TypeEnum::Object);
  }
  if (value->IsBoolean()) {
    return std::make_unique<PrimitiveValueMirror>(
        isolate, value.As<v8::Primitive>(), RemoteObject::TypeEnum::Boolean);
  }
  if (value->IsNumber()) {
    return std::make_unique<NumberMirror>(isolate, value.As<v8::Number>());
  }
  if (value->IsString()) {
    return std::make_unique<PrimitiveValueMirror>(
        isolate, value.As<v8::Primitive>(), RemoteObject::TypeEnum::String);
  }
  if (value->IsBigInt()) {
    return std::make_unique<BigIntMirror>(isolate, value.As<v8::BigInt>());
  }
  if (value->IsSymbol()) {
    return std::make_unique<SymbolMirror>(isolate, value.As<v8::Symbol>());
  }
  if (value->IsUndefined()) {
    return std::make_unique<PrimitiveValueMirror>(
        isolate, value.As<v8::Primitive>(), RemoteObject::TypeEnum::Undefined);
  }
  if (!value->IsObject()) {
    return nullptr;
  }
  v8::Local<v8::Object> object = value.As<v8::Object>();
  auto clientSubtype = clientFor(context)->valueSubtype(object);
  if (clientSubtype) {
    String16 subtype = toString16(clientSubtype->string());
    return clientMirror(context, object, subtype);
  }
  if (object->IsRegExp()) {
    v8::Local<v8::RegExp> regexp = object.As<v8::RegExp>();
    return std::make_unique<ObjectMirror>(
        regexp, RemoteObject::SubtypeEnum::Regexp,
        descriptionForRegExp(isolate, regexp));
  }
  if (object->IsProxy()) {
    v8::Local<v8::Proxy> proxy = object.As<v8::Proxy>();
    return std::make_unique<ObjectMirror>(proxy,
                                          RemoteObject::SubtypeEnum::Proxy,
                                          descriptionForProxy(isolate, proxy));
  }
  if (object->IsFunction()) {
    v8::Local<v8::Function> function = object.As<v8::Function>();
    return std::make_unique<FunctionMirror>(function);
  }
  if (object->IsDate()) {
    v8::Local<v8::Date> date = object.As<v8::Date>();
    return std::make_unique<ObjectMirror>(date, RemoteObject::SubtypeEnum::Date,
                                          descriptionForDate(context, date));
  }
  if (object->IsPromise()) {
    v8::Local<v8::Promise> promise = object.As<v8::Promise>();
    return std::make_unique<ObjectMirror>(
        promise, RemoteObject::SubtypeEnum::Promise,
        descriptionForObject(isolate, promise));
  }
  if (object->IsNativeError()) {
    return std::make_unique<ObjectMirror>(object,
                                          RemoteObject::SubtypeEnum::Error,
                                          descriptionForError(context, object));
  }
  if (object->IsMap()) {
    v8::Local<v8::Map> map = object.As<v8::Map>();
    return std::make_unique<ObjectMirror>(
        map, RemoteObject::SubtypeEnum::Map,
        descriptionForCollection(isolate, map, map->Size()));
  }
  if (object->IsSet()) {
    v8::Local<v8::Set> set = object.As<v8::Set>();
    return std::make_unique<ObjectMirror>(
        set, RemoteObject::SubtypeEnum::Set,
        descriptionForCollection(isolate, set, set->Size()));
  }
  if (object->IsWeakMap()) {
    return std::make_unique<ObjectMirror>(
        object, RemoteObject::SubtypeEnum::Weakmap,
        descriptionForObject(isolate, object));
  }
  if (object->IsWeakSet()) {
    return std::make_unique<ObjectMirror>(
        object, RemoteObject::SubtypeEnum::Weakset,
        descriptionForObject(isolate, object));
  }
  if (object->IsMapIterator() || object->IsSetIterator()) {
    return std::make_unique<ObjectMirror>(
        object, RemoteObject::SubtypeEnum::Iterator,
        descriptionForObject(isolate, object));
  }
  if (object->IsGeneratorObject()) {
    return std::make_unique<ObjectMirror>(
        object, RemoteObject::SubtypeEnum::Generator,
        descriptionForObject(isolate, object));
  }
  if (object->IsTypedArray()) {
    v8::Local<v8::TypedArray> array = object.As<v8::TypedArray>();
    return std::make_unique<ObjectMirror>(
        array, RemoteObject::SubtypeEnum::Typedarray,
        descriptionForCollection(isolate, array, array->Length()));
  }
  if (object->IsArrayBuffer()) {
    v8::Local<v8::ArrayBuffer> buffer = object.As<v8::ArrayBuffer>();
    return std::make_unique<ObjectMirror>(
        buffer, RemoteObject::SubtypeEnum::Arraybuffer,
        descriptionForCollection(isolate, buffer, buffer->ByteLength()));
  }
  if (object->IsSharedArrayBuffer()) {
    v8::Local<v8::SharedArrayBuffer> buffer =
        object.As<v8::SharedArrayBuffer>();
    return std::make_unique<ObjectMirror>(
        buffer, RemoteObject::SubtypeEnum::Arraybuffer,
        descriptionForCollection(isolate, buffer, buffer->ByteLength()));
  }
  if (object->IsDataView()) {
    v8::Local<v8::DataView> view = object.As<v8::DataView>();
    return std::make_unique<ObjectMirror>(
        view, RemoteObject::SubtypeEnum::Dataview,
        descriptionForCollection(isolate, view, view->ByteLength()));
  }
  if (object->IsWasmMemoryObject()) {
    v8::Local<v8::WasmMemoryObject> memory = object.As<v8::WasmMemoryObject>();
    return std::make_unique<ObjectMirror>(
        memory, RemoteObject::SubtypeEnum::Webassemblymemory,
        descriptionForCollection(
            isolate, memory, memory->Buffer()->ByteLength() / kWasmPageSize));
  }
#if V8_ENABLE_WEBASSEMBLY
  if (v8::debug::WasmValueObject::IsWasmValueObject(object)) {
    v8::Local<v8::debug::WasmValueObject> value_object =
        object.As<v8::debug::WasmValueObject>();
    return std::make_unique<ObjectMirror>(
        value_object, RemoteObject::SubtypeEnum::Wasmvalue,
        descriptionForWasmValueObject(context, value_object));
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (!value->IsObject()) {
    return nullptr;
  }
  V8InternalValueType internalType = v8InternalValueTypeFrom(context, object);
  if (internalType == V8InternalValueType::kScopeList) {
    v8::Local<v8::Array> array = value.As<v8::Array>();
    return std::make_unique<ObjectMirror>(array, "internal#scopeList",
                                          descriptionForScopeList(array));
  }
  if (internalType == V8InternalValueType::kPrivateMethodList) {
    v8::Local<v8::Array> array = object.As<v8::Array>();
    return std::make_unique<ObjectMirror>(
        array, "internal#privateMethodList",
        descriptionForPrivateMethodList(array));
  }
  if (internalType == V8InternalValueType::kEntry) {
    return std::make_unique<ObjectMirror>(object, "internal#entry",
                                          descriptionForEntry(context, object));
  }
  if (internalType == V8InternalValueType::kScope) {
    return std::make_unique<ObjectMirror>(object, "internal#scope",
                                          descriptionForScope(context, object));
  }
  if (internalType == V8InternalValueType::kPrivateMethod) {
    return std::make_unique<ObjectMirror>(
        object, "internal#privateMethod",
        descriptionForPrivateMethod(context, object));
  }
  size_t length = 0;
  if (isArrayLike(context, object, &length)) {
    return std::make_unique<ObjectMirror>(
        object, RemoteObject::SubtypeEnum::Array,
        descriptionForCollection(isolate, object, length));
  }
  return std::make_unique<ObjectMirror>(object,
                                        descriptionForObject(isolate, object));
}
References v8::Local< T >::As(), v8_inspector::anonymous_namespace{value-mirror.cc}::clientFor(), v8_inspector::clientMirror(), v8::internal::date, v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForCollection(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForDate(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForEntry(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethod(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethodList(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForProxy(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForRegExp(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScope(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScopeList(), v8::internal::torque::Error(), v8::Isolate::GetCurrent(), v8::Value::IsArrayBuffer(), v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike(), v8::Value::IsDataView(), v8::Value::IsDate(), v8::Value::IsFunction(), v8::Value::IsGeneratorObject(), v8::Value::IsMap(), v8::Value::IsMapIterator(), v8::Value::IsNativeError(), v8::Value::IsPromise(), v8::Value::IsProxy(), v8::Value::IsRegExp(), v8::Value::IsSet(), v8::Value::IsSetIterator(), v8::Value::IsSharedArrayBuffer(), v8::Value::IsTypedArray(), v8::Value::IsWasmMemoryObject(), v8::Value::IsWeakMap(), v8::Value::IsWeakSet(), v8_inspector::kEntry, v8_inspector::kPrivateMethod, v8_inspector::kPrivateMethodList, v8_inspector::kScope, v8_inspector::kScopeList, v8_inspector::anonymous_namespace{value-mirror.cc}::kWasmPageSize, v8::internal::length, v8::internal::compiler::Map, v8::internal::compiler::Object, v8::Map::Size(), v8_inspector::toString16(), v8::internal::compiler::Undefined, v8_inspector::anonymous_namespace{value-mirror.cc}::v8InternalValueTypeFrom(), v8::internal::value, and v8_inspector::V8InspectorClient::valueSubtype().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForEntry(), v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror::getEntries(), getInternalProperties(), getPrivateProperties(), getProperties(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeArrayValue(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8_inspector::InjectedScript::wrapObject(), and v8_inspector::InjectedScript::wrapTable().
getInternalProperties()
void v8_inspector::ValueMirror::getInternalProperties (v8::Local< v8::Context > context, v8::Local< v8::Object > object, std::vector< InternalPropertyMirror > * mirrors) [static]
Definition at line 1680 of file value-mirror.cc.
                                                {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::TryCatch tryCatch(isolate);
  if (object->IsFunction()) {
    v8::Local<v8::Function> function = object.As<v8::Function>();
    auto location = LocationMirror::create(function);
    if (location) {
      mirrors->emplace_back(InternalPropertyMirror{
          String16("[[FunctionLocation]]"), std::move(location)});
    }
    if (function->IsGeneratorFunction()) {
      mirrors->emplace_back(InternalPropertyMirror{
          String16("[[IsGenerator]]"),
          ValueMirror::create(context, v8::True(v8::Isolate::GetCurrent()))});
    }
  }
  if (object->IsGeneratorObject()) {
    auto location = LocationMirror::createForGenerator(object);
    if (location) {
      mirrors->emplace_back(InternalPropertyMirror{
          String16("[[GeneratorLocation]]"), std::move(location)});
    }
  }
  V8Debugger* debugger =
      static_cast<V8InspectorImpl*>(v8::debug::GetInspector(isolate))
          ->debugger();
  v8::Local<v8::Array> properties;
  if (debugger->internalProperties(context, object).ToLocal(&properties)) {
    for (uint32_t i = 0; i < properties->Length(); i += 2) {
      v8::Local<v8::Value> name;
      if (!properties->Get(context, i).ToLocal(&name) || !name->IsString()) {
        tryCatch.Reset();
        continue;
      }
      v8::Local<v8::Value> value;
      if (!properties->Get(context, i + 1).ToLocal(&value)) {
        tryCatch.Reset();
        continue;
      }
      auto wrapper = ValueMirror::create(context, value);
      if (wrapper) {
        mirrors->emplace_back(InternalPropertyMirror{
            toProtocolStringWithTypeCheck(v8::Isolate::GetCurrent(), name),
            std::move(wrapper)});
      }
    }
  }
}
References v8::Local< T >::As(), create(), v8::Object::Get(), v8::Isolate::GetCurrent(), v8::debug::GetInspector(), v8_inspector::V8Debugger::internalProperties(), v8::Value::IsFunction(), v8::Value::IsGeneratorObject(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::Array::Length(), name, v8::TryCatch::Reset(), v8::MaybeLocal< T >::ToLocal(), v8_inspector::toProtocolStringWithTypeCheck(), v8::True(), and v8::internal::value.
Referenced by v8_inspector::InjectedScript::getInternalAndPrivateProperties(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview().
getPrivateProperties()
std::vector< PrivatePropertyMirror > v8_inspector::ValueMirror::getPrivateProperties (v8::Local< v8::Context > context, v8::Local< v8::Object > object, bool accessorPropertiesOnly) [static]
Definition at line 1734 of file value-mirror.cc.
                                 {
  std::vector<PrivatePropertyMirror> mirrors;
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::TryCatch tryCatch(isolate);
  v8::LocalVector<v8::Value> names(isolate);
  v8::LocalVector<v8::Value> values(isolate);
  int filter =
      static_cast<int>(v8::debug::PrivateMemberFilter::kPrivateAccessors) |
      static_cast<int>(v8::debug::PrivateMemberFilter::kPrivateFields);
  if (!v8::debug::GetPrivateMembers(context, object, filter, &names, &values))
    return mirrors;
  size_t len = values.size();
  for (size_t i = 0; i < len; i++) {
    v8::Local<v8::Value> name = names[i];
    DCHECK(name->IsString());
    v8::Local<v8::Value> value = values[i];
    std::unique_ptr<ValueMirror> valueMirror;
    std::unique_ptr<ValueMirror> getterMirror;
    std::unique_ptr<ValueMirror> setterMirror;
    if (v8::debug::AccessorPair::IsAccessorPair(value)) {
      v8::Local<v8::debug::AccessorPair> accessors =
          value.As<v8::debug::AccessorPair>();
      v8::Local<v8::Value> getter = accessors->getter();
      v8::Local<v8::Value> setter = accessors->setter();
      if (!getter->IsNull()) {
        getterMirror = ValueMirror::create(context, getter);
      }
      if (!setter->IsNull()) {
        setterMirror = ValueMirror::create(context, setter);
      }
    } else if (accessorPropertiesOnly) {
      continue;
    } else {
      valueMirror = ValueMirror::create(context, value);
    }
    mirrors.emplace_back(PrivatePropertyMirror{
        toProtocolStringWithTypeCheck(v8::Isolate::GetCurrent(), name),
        std::move(valueMirror), std::move(getterMirror),
        std::move(setterMirror)});
  }
  return mirrors;
}
References create(), DCHECK, v8::Isolate::GetCurrent(), v8::debug::GetPrivateMembers(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::debug::AccessorPair::IsAccessorPair(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::debug::kPrivateAccessors, v8::debug::kPrivateFields, name, v8::internal::setter, v8::LocalVector< T >::size(), v8_inspector::toProtocolStringWithTypeCheck(), and v8::internal::value.
Referenced by v8_inspector::InjectedScript::getInternalAndPrivateProperties(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getPrivatePropertiesForPreview().
getProperties()
bool v8_inspector::ValueMirror::getProperties (v8::Local< v8::Context > context, v8::Local< v8::Object > object, bool ownProperties, bool accessorPropertiesOnly, bool nonIndexedPropertiesOnly, PropertyAccumulator * accumulator) [static]
Definition at line 1525 of file value-mirror.cc.
                                                                  {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  v8::Local<v8::Set> set = v8::Set::New(isolate);
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  V8InternalValueType internalType = v8InternalValueTypeFrom(context, object);
  if (internalType == V8InternalValueType::kScope) {
    v8::Local<v8::Value> value;
    if (!object->Get(context, toV8String(isolate, "object")).ToLocal(&value) ||
        !value->IsObject()) {
      return false;
    } else {
      object = value.As<v8::Object>();
    }
  }
  if (internalType == V8InternalValueType::kScopeList ||
      internalType == V8InternalValueType::kPrivateMethodList) {
    if (!set->Add(context, toV8String(isolate, "length")).ToLocal(&set)) {
      return false;
    }
  }
  auto iterator = v8::debug::PropertyIterator::Create(context, object,
                                                      nonIndexedPropertiesOnly);
  if (!iterator) {
    CHECK(tryCatch.HasCaught());
    return false;
  }
  while (!iterator->Done()) {
    bool isOwn = iterator->is_own();
    if (!isOwn && ownProperties) break;
    v8::Local<v8::Name> v8Name = iterator->name();
    v8::Maybe<bool> result = set->Has(context, v8Name);
    if (result.IsNothing()) return false;
    if (result.FromJust()) {
      if (!iterator->Advance().FromMaybe(false)) {
        CHECK(tryCatch.HasCaught());
        return false;
      }
      continue;
    }
    if (!set->Add(context, v8Name).ToLocal(&set)) return false;
    String16 name;
    std::unique_ptr<ValueMirror> symbolMirror;
    if (v8Name->IsString()) {
      name = toProtocolString(isolate, v8Name.As<v8::String>());
    } else {
      v8::Local<v8::Symbol> symbol = v8Name.As<v8::Symbol>();
      name = descriptionForSymbol(context, symbol);
      symbolMirror = ValueMirror::create(context, symbol);
    }
    v8::PropertyAttribute attributes;
    std::unique_ptr<ValueMirror> valueMirror;
    std::unique_ptr<ValueMirror> getterMirror;
    std::unique_ptr<ValueMirror> setterMirror;
    std::unique_ptr<ValueMirror> exceptionMirror;
    bool writable = false;
    bool enumerable = false;
    bool configurable = false;
    bool isAccessorProperty = false;
    v8::TryCatch tryCatchAttributes(isolate);
    if (!iterator->attributes().To(&attributes)) {
      exceptionMirror =
          ValueMirror::create(context, tryCatchAttributes.Exception());
    } else {
      if (iterator->is_native_accessor()) {
        if (iterator->has_native_getter()) {
          getterMirror = createNativeGetter(context, object, v8Name);
        }
        if (iterator->has_native_setter()) {
          setterMirror = createNativeSetter(context, object, v8Name);
        }
        writable = !(attributes & v8::PropertyAttribute::ReadOnly);
        enumerable = !(attributes & v8::PropertyAttribute::DontEnum);
        configurable = !(attributes & v8::PropertyAttribute::DontDelete);
        isAccessorProperty = getterMirror || setterMirror;
      } else {
        v8::TryCatch tryCatchDescriptor(isolate);
        v8::debug::PropertyDescriptor descriptor;
        if (!iterator->descriptor().To(&descriptor)) {
          exceptionMirror =
              ValueMirror::create(context, tryCatchDescriptor.Exception());
        } else {
          writable = descriptor.has_writable ? descriptor.writable : false;
          enumerable =
              descriptor.has_enumerable ? descriptor.enumerable : false;
          configurable =
              descriptor.has_configurable ? descriptor.configurable : false;
          if (!descriptor.value.IsEmpty()) {
            valueMirror = ValueMirror::create(context, descriptor.value);
          }
          v8::Local<v8::Function> getterFunction;
          if (!descriptor.get.IsEmpty()) {
            v8::Local<v8::Value> get = descriptor.get;
            getterMirror = ValueMirror::create(context, get);
            if (get->IsFunction()) getterFunction = get.As<v8::Function>();
          }
          if (!descriptor.set.IsEmpty()) {
            setterMirror = ValueMirror::create(context, descriptor.set);
          }
          isAccessorProperty = getterMirror || setterMirror;
          if (name != "__proto__" && !getterFunction.IsEmpty() &&
              deepBoundFunction(getterFunction)->ScriptId() ==
                  v8::UnboundScript::kNoScriptId &&
              !doesAttributeHaveObservableSideEffectOnGet(context, object,
                                                          v8Name)) {
            v8::TryCatch tryCatchFunction(isolate);
            v8::Local<v8::Value> value;
            if (object->Get(context, v8Name).ToLocal(&value)) {
              if (value->IsPromise() &&
                  value.As<v8::Promise>()->State() == v8::Promise::kRejected) {
                value.As<v8::Promise>()->MarkAsHandled();
              } else {
                valueMirror = ValueMirror::create(context, value);
                setterMirror = nullptr;
                getterMirror = nullptr;
              }
            }
          }
        }
      }
    }
    if (accessorPropertiesOnly && !isAccessorProperty) continue;
    auto mirror = PropertyMirror{name,
                                 writable,
                                 configurable,
                                 enumerable,
                                 isOwn,
                                 iterator->is_array_index(),
                                 isAccessorProperty && valueMirror,
                                 std::move(valueMirror),
                                 std::move(getterMirror),
                                 std::move(setterMirror),
                                 std::move(symbolMirror),
                                 std::move(exceptionMirror)};
    if (!accumulator->Add(std::move(mirror))) return true;
    if (!iterator->Advance().FromMaybe(false)) {
      CHECK(tryCatchAttributes.HasCaught());
      return false;
    }
  }
  return true;
}
References v8_inspector::ValueMirror::PropertyAccumulator::Add(), v8::Local< T >::As(), CHECK, v8::debug::PropertyDescriptor::configurable, v8::debug::PropertyIterator::Create(), create(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::deepBoundFunction(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForSymbol(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8::DontDelete, v8::DontEnum, v8::debug::PropertyDescriptor::enumerable, v8::TryCatch::Exception(), v8::Object::Get(), v8::debug::PropertyDescriptor::get, v8::Isolate::GetCurrent(), v8::debug::PropertyDescriptor::has_configurable, v8::debug::PropertyDescriptor::has_enumerable, v8::debug::PropertyDescriptor::has_writable, v8::TryCatch::HasCaught(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Value::IsFunction(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::UnboundScript::kNoScriptId, v8_inspector::kPrivateMethodList, v8::Promise::kRejected, v8_inspector::kScope, v8_inspector::kScopeList, name, v8::Set::New(), v8::ReadOnly, v8::base::internal::result, v8::debug::PropertyDescriptor::set, v8::Promise::State(), v8::MaybeLocal< T >::ToLocal(), v8_inspector::toProtocolString(), v8_inspector::toV8String(), v8_inspector::anonymous_namespace{value-mirror.cc}::v8InternalValueTypeFrom(), v8::debug::PropertyDescriptor::value, v8::internal::value, and v8::debug::PropertyDescriptor::writable.
Referenced by v8_inspector::InjectedScript::getProperties(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview().
v8Value()
virtual v8::Local<v8::Value> v8_inspector::ValueMirror::v8Value (v8::Isolate * isolate) const [pure virtual]
Implemented in v8_inspector::anonymous_namespace{value-mirror.cc}::ValueMirrorBase.
Referenced by v8_inspector::InjectedScript::wrapObjectMirror().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/value-mirror.h
/mnt/V8SourceCode/src/inspector/value-mirror.cc