v8::internal::StringTable::Data Class Reference
Public Member Functions
void * operator new (size_t size, int capacity)
void * operator new (size_t size)=delete
void operator delete (void *description)
OffHeapStringHashSet & table ()
const OffHeapStringHashSet & table () const
void IterateElements (RootVisitor *visitor)
Data * PreviousData ()
void DropPreviousData ()
void Print (PtrComprCageBase cage_base) const
size_t GetCurrentMemoryUsage () const
Static Public Member Functions
static std::unique_ptr< Data > New (int capacity)
static std::unique_ptr< Data > Resize (PtrComprCageBase cage_base, std::unique_ptr< Data > data, int capacity)
template<typename Char >
static Address TryStringToIndexOrLookupExisting (Isolate *isolate, Tagged< String > string, Tagged< String > source, size_t start)
Private Member Functions
Data (int capacity)
Private Attributes
std::unique_ptr< Data > previous_data_
OffHeapStringHashSet table_
Detailed Description
Definition at line 83 of file string-table.cc.
Constructor & Destructor Documentation
Data()
v8::internal::StringTable::Data::Data (int capacity) [inline], [explicit], [private]
Definition at line 114 of file string-table.cc.
: table_(capacity) {}
Member Function Documentation
DropPreviousData()
void v8::internal::StringTable::Data::DropPreviousData () [inline]
Definition at line 108 of file string-table.cc.
{ previous_data_.reset(); }
References previous_data_.
GetCurrentMemoryUsage()
size_t v8::internal::StringTable::Data::GetCurrentMemoryUsage () const
Definition at line 131 of file string-table.cc.
                                                    {
  size_t usage = sizeof(*this) + table_.GetSizeExcludingHeader();
  if (previous_data_) {
    usage += previous_data_->GetCurrentMemoryUsage();
  }
  return usage;
}
References v8::internal::OffHeapHashTableBase< Derived >::GetSizeExcludingHeader(), previous_data_, and table_.
IterateElements()
void v8::internal::StringTable::Data::IterateElements (RootVisitor * visitor) [inline]
Definition at line 103 of file string-table.cc.
                                             {
    table_.IterateElements(Root::kStringTable, visitor);
  }
References v8::internal::OffHeapHashTableBase< Derived >::IterateElements(), and table_.
New()
std::unique_ptr< StringTable::Data > v8::internal::StringTable::Data::New (int capacity) [static]
Definition at line 139 of file string-table.cc.
                                                                {
  return std::unique_ptr<Data>(new (capacity) Data(capacity));
}
operator delete()
void v8::internal::StringTable::Data::operator delete (void * description)
Definition at line 127 of file string-table.cc.
                                                 {
  OffHeapStringHashSet::Free(table);
}
References v8::base::Free().
operator new() [1/2]
void* v8::internal::StringTable::Data::operator new (size_t size) [delete]
operator new() [2/2]
void * v8::internal::StringTable::Data::operator new (size_t size, int capacity)
Definition at line 120 of file string-table.cc.
                                                             {
  // Make sure the size given is the size of the Data structure.
  DCHECK_EQ(size, sizeof(StringTable::Data));
  return OffHeapStringHashSet::Allocate<Data, offsetof(Data, table_.elements_)>(
      capacity);
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), DCHECK_EQ, and size().
PreviousData()
Data* v8::internal::StringTable::Data::PreviousData () [inline]
Definition at line 107 of file string-table.cc.
{ return previous_data_.get(); }
References previous_data_.
Print()
void v8::internal::StringTable::Data::Print (PtrComprCageBase cage_base) const
Definition at line 151 of file string-table.cc.
                                                            {
  OFStream os(stdout);
  os << "StringTable {" << std::endl;
  for (InternalIndex i : InternalIndex::Range(table_.capacity())) {
    os << " " << i.as_uint32() << ": " << Brief(table_.GetKey(cage_base, i))
       << std::endl;
  }
  os << "}" << std::endl;
}
Resize()
std::unique_ptr< StringTable::Data > v8::internal::StringTable::Data::Resize (PtrComprCageBase cage_base, std::unique_ptr< Data > data, int capacity) [static]
Definition at line 143 of file string-table.cc.
                                                                        {
  std::unique_ptr<Data> new_data(new (capacity) Data(capacity));
  data->table_.RehashInto(cage_base, &new_data->table_);
  new_data->previous_data_ = std::move(data);
  return new_data;
}
Referenced by v8::internal::StringTable::EnsureCapacity().
table() [1/2]
OffHeapStringHashSet& v8::internal::StringTable::Data::table () [inline]
Definition at line 93 of file string-table.cc.
{ return table_; }
References table_.
Referenced by v8::internal::StringTable::EnsureCapacity(), v8::internal::StringTable::InsertEmptyStringForBootstrapping(), v8::internal::StringTable::InsertForIsolateDeserialization(), v8::internal::StringTable::LookupKey(), and TryStringToIndexOrLookupExisting().
table() [2/2]
const OffHeapStringHashSet& v8::internal::StringTable::Data::table () const [inline]
Definition at line 94 of file string-table.cc.
{ return table_; }
References table_.
TryStringToIndexOrLookupExisting()
template<typename Char >
Address v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting (Isolate * isolate, Tagged< String > string, Tagged< String > source, size_t start) [static]
Definition at line 550 of file string-table.cc.
                  {
  // TODO(leszeks): This method doesn't really belong on StringTable::Data.
  // Ideally it would be a free function in an anonymous namespace, but that
  // causes issues around method and class visibility.
  DisallowGarbageCollection no_gc;
  uint32_t length = string->length();
  // The source hash is usable if it is not from a sliced string.
  // For sliced strings we need to recalculate the hash from the given offset
  // with the correct length.
  const bool is_source_hash_usable = start == 0 && length == source->length();
  // First check if the string constains a forwarding index.
  uint32_t raw_hash_field = source->raw_hash_field(kAcquireLoad);
  if (Name::IsInternalizedForwardingIndex(raw_hash_field) &&
      is_source_hash_usable) {
    const int index = Name::ForwardingIndexValueBits::decode(raw_hash_field);
    Tagged<String> internalized =
        isolate->string_forwarding_table()->GetForwardString(isolate, index);
    return internalized.ptr();
  }
  uint64_t seed = HashSeed(isolate);
  CharBuffer<Char> buffer;
  const Char* chars;
  SharedStringAccessGuardIfNeeded access_guard(isolate);
  if (IsConsString(source, isolate)) {
    DCHECK(!source->IsFlat());
    buffer.Reset(length);
    String::WriteToFlat(source, buffer.Data(), 0, length, access_guard);
    chars = buffer.Data();
  } else {
    chars = source->GetDirectStringChars<Char>(no_gc, access_guard) + start;
  }
  if (!Name::IsHashFieldComputed(raw_hash_field) || !is_source_hash_usable) {
    raw_hash_field =
        StringHasher::HashSequentialString<Char>(chars, length, seed);
  }
  // TODO(verwaest): Internalize to one-byte when possible.
  SequentialStringKey<Char> key(raw_hash_field,
                                base::Vector<const Char>(chars, length), seed);
  // String could be an array index.
  if (Name::ContainsCachedArrayIndex(raw_hash_field)) {
    return Smi::FromInt(String::ArrayIndexValueBits::decode(raw_hash_field))
        .ptr();
  }
  if (Name::IsIntegerIndex(raw_hash_field)) {
    // It is an index, but it's not cached.
    return Smi::FromInt(ResultSentinel::kUnsupported).ptr();
  }
  Data* string_table_data =
      isolate->string_table()->data_.load(std::memory_order_acquire);
  InternalIndex entry =
      string_table_data->table().FindEntry(isolate, &key, key.hash());
  if (entry.is_not_found()) {
    // A string that's not an array index, and not in the string table,
    // cannot have been used as a property name before.
    return Smi::FromInt(ResultSentinel::kNotFound).ptr();
  }
  Tagged<String> internalized =
      Cast<String>(string_table_data->table().GetKey(isolate, entry));
  // string can be internalized here, if another thread internalized it.
  // If we found and entry in the string table and string is not internalized,
  // there is no way that it can transition to internalized later on. So a last
  // check here is sufficient.
  if (!IsInternalizedString(string)) {
    SetInternalizedReference(isolate, string, internalized);
  } else {
    DCHECK(v8_flags.shared_string_table);
  }
  return internalized.ptr();
}
References v8::internal::Name::ContainsCachedArrayIndex(), v8::internal::StringTable::data_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::OffHeapHashTableBase< Derived >::FindEntry(), v8::internal::Smi::FromInt(), v8::internal::StringForwardingTable::GetForwardString(), v8::internal::StringTable::OffHeapStringHashSet::GetKey(), v8::internal::HashSeed(), v8::internal::index, v8::internal::InternalIndex::is_not_found(), v8::internal::InstanceTypeChecker::IsConsString(), v8::internal::Name::IsHashFieldComputed(), v8::internal::Name::IsIntegerIndex(), v8::internal::Name::IsInternalizedForwardingIndex(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::kAcquireLoad, v8::internal::key, v8::internal::kNotFound, v8::internal::kUnsupported, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), v8::internal::Isolate::string_forwarding_table(), v8::internal::Isolate::string_table(), table(), v8::internal::v8_flags, and v8::internal::String::WriteToFlat().
Member Data Documentation
previous_data_
std::unique_ptr<Data> v8::internal::StringTable::Data::previous_data_ [private]
Definition at line 116 of file string-table.cc.
Referenced by DropPreviousData(), GetCurrentMemoryUsage(), and PreviousData().
table_
OffHeapStringHashSet v8::internal::StringTable::Data::table_ [private]
Definition at line 117 of file string-table.cc.
Referenced by GetCurrentMemoryUsage(), IterateElements(), and table().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string-table.cc