v8::internal::maglev::SmiConstant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = Register
Public Member Functions
SmiConstant (uint64_t bitfield, int32_t value)
Tagged< Smi > value () const
bool ToBoolean (LocalIsolate *local_isolate) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
DirectHandle< Object > DoReify (LocalIsolate *isolate) const
Private Types
using Base = FixedInputValueNodeT< 0, SmiConstant >
Private Attributes
const Tagged< Smi > value_
Additional Inherited Members
Detailed Description
Definition at line 5525 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::SmiConstant::Base = FixedInputValueNodeT<0, SmiConstant> [private]
Definition at line 5526 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::SmiConstant::OutputRegister = Register
Definition at line 5529 of file maglev-ir.h.
Constructor & Destructor Documentation
SmiConstant()
v8::internal::maglev::SmiConstant::SmiConstant (uint64_t bitfield, int32_t value) [inline], [explicit]
Definition at line 5531 of file maglev-ir.h.
      : Base(bitfield), value_(Smi::FromInt(value)) {
    DCHECK(Smi::IsValid(value));
  }
References v8::internal::DCHECK(), v8::internal::Smi::IsValid(), and value().
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::SmiConstant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
DirectHandle< Object > v8::internal::maglev::SmiConstant::DoReify (LocalIsolate * isolate) const
Definition at line 1207 of file maglev-ir.cc.
                                                                     {
  return direct_handle(value_, isolate);
}
References v8::internal::direct_handle(), and value_.
GenerateCode()
void v8::internal::maglev::SmiConstant::GenerateCode (MaglevAssembler * , const ProcessingState &)
PrintParams()
void v8::internal::maglev::SmiConstant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7884 of file maglev-ir.cc.
                                                                         {
  os << "(" << value() << ")";
}
References value().
SetValueLocationConstraints()
void v8::internal::maglev::SmiConstant::SetValueLocationConstraints ()
ToBoolean()
bool v8::internal::maglev::SmiConstant::ToBoolean (LocalIsolate * local_isolate) const [inline]
Definition at line 5538 of file maglev-ir.h.
                                                    {
    return value_ != Smi::FromInt(0);
  }
References v8::internal::Smi::FromInt(), and value_.
value()
Tagged<Smi> v8::internal::maglev::SmiConstant::value () const [inline]
Definition at line 5536 of file maglev-ir.h.
{ return value_; }
References value_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and SmiConstant().
Member Data Documentation
value_
const Tagged<Smi> v8::internal::maglev::SmiConstant::value_ [private]
Definition at line 5550 of file maglev-ir.h.
Referenced by DoReify(), ToBoolean(), and value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc