v8::internal::OldLargeObjectSpace Class Reference
#include <large-spaces.h>
Public Member Functions
V8_EXPORT_PRIVATE OldLargeObjectSpace (Heap *heap)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (LocalHeap *local_heap, int object_size, AllocationHint hint)
void PromoteNewLargeObject (LargePageMetadata *page)
Protected Member Functions
OldLargeObjectSpace (Heap *heap, AllocationSpace id)
V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (LocalHeap *local_heap, int object_size, Executability executable, AllocationHint hint)
Additional Inherited Members
Detailed Description
Definition at line 145 of file large-spaces.h.
Constructor & Destructor Documentation
OldLargeObjectSpace() [1/2]
v8::internal::OldLargeObjectSpace::OldLargeObjectSpace (Heap * heap) [explicit]
Definition at line 365 of file large-spaces.cc.
    : LargeObjectSpace(heap, LO_SPACE) {}
OldLargeObjectSpace() [2/2]
v8::internal::OldLargeObjectSpace::OldLargeObjectSpace (Heap * heap, AllocationSpace id) [explicit], [protected]
Definition at line 368 of file large-spaces.cc.
    : LargeObjectSpace(heap, id) {}
Member Function Documentation
AllocateRaw() [1/2]
AllocationResult v8::internal::OldLargeObjectSpace::AllocateRaw (LocalHeap * local_heap, int object_size, AllocationHint hint)
Definition at line 102 of file large-spaces.cc.
                                                                       {
  return AllocateRaw(local_heap, object_size, NOT_EXECUTABLE, hint);
}
References v8::internal::NOT_EXECUTABLE.
Referenced by v8::internal::CodeLargeObjectSpace::AllocateRaw(), and v8::internal::HeapAllocator::AllocateRawLargeInternal().
AllocateRaw() [2/2]
AllocationResult v8::internal::OldLargeObjectSpace::AllocateRaw (LocalHeap * local_heap, int object_size, Executability executable, AllocationHint hint) [protected]
Definition at line 108 of file large-spaces.cc.
                                                                       {
  object_size = ALIGN_TO_ALLOCATION_ALIGNMENT(object_size);
  DCHECK_IMPLIES(identity() == SHARED_LO_SPACE,
                 !allocation_counter_.HasAllocationObservers());
  DCHECK_IMPLIES(identity() == SHARED_LO_SPACE,
                 pending_object() == kNullAddress);
  // Check if we want to force a GC before growing the old space further.
  // If so, fail the allocation.
  if (!heap()->ShouldExpandOldGenerationOnSlowAllocation(
          local_heap, AllocationOrigin::kRuntime) ||
      !heap()->CanExpandOldGeneration(object_size)) {
    return AllocationResult::Failure();
  }
  heap()->StartIncrementalMarkingIfAllocationLimitIsReached(
      local_heap, heap()->GCFlagsForIncrementalMarking(),
      kGCCallbackScheduleIdleGarbageCollection);
  LargePageMetadata* page = AllocateLargePage(object_size, executable, hint);
  if (page == nullptr) return AllocationResult::Failure();
  Tagged<HeapObject> object = page->GetObject();
  if (local_heap->is_main_thread() && identity() != SHARED_LO_SPACE) {
    UpdatePendingObject(object);
  }
  if (v8_flags.sticky_mark_bits ||
      heap()->incremental_marking()->black_allocation()) {
    heap()->marking_state()->TryMarkAndAccountLiveBytes(object, object_size);
  }
  DCHECK_IMPLIES(heap()->incremental_marking()->black_allocation(),
                 heap()->marking_state()->IsMarked(object));
  page->Chunk()->InitializationMemoryFence();
  heap()->NotifyOldGenerationExpansion(local_heap, identity(), page);
  if (local_heap->is_main_thread() && identity() != SHARED_LO_SPACE) {
    AdvanceAndInvokeAllocationObservers(object.address(),
                                        static_cast<size_t>(object_size));
  }
  return AllocationResult::FromObject(object);
}
References v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers(), ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::LargeObjectSpace::AllocateLargePage(), v8::internal::LargeObjectSpace::allocation_counter_, v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_IMPLIES, v8::internal::AllocationResult::Failure(), v8::internal::AllocationResult::FromObject(), v8::internal::LargePageMetadata::GetObject(), v8::internal::BaseSpace::heap(), v8::internal::BaseSpace::identity(), v8::internal::MemoryChunk::InitializationMemoryFence(), v8::internal::LocalHeap::is_main_thread(), v8::kGCCallbackScheduleIdleGarbageCollection, v8::internal::kNullAddress, v8::internal::kRuntime, v8::internal::Heap::marking_state(), v8::internal::Heap::NotifyOldGenerationExpansion(), v8::internal::LargeObjectSpace::pending_object(), v8::internal::SHARED_LO_SPACE, v8::internal::Heap::StartIncrementalMarkingIfAllocationLimitIsReached(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMarkAndAccountLiveBytes(), v8::internal::LargeObjectSpace::UpdatePendingObject(), and v8::internal::v8_flags.
PromoteNewLargeObject()
void v8::internal::OldLargeObjectSpace::PromoteNewLargeObject (LargePageMetadata * page)
Definition at line 182 of file large-spaces.cc.
                                                                       {
  MemoryChunk* chunk = page->Chunk();
  DCHECK_EQ(page->owner_identity(), NEW_LO_SPACE);
  DCHECK(chunk->IsLargePage());
  DCHECK(chunk->IsFlagSet(MemoryChunk::FROM_PAGE));
  DCHECK(!chunk->IsFlagSet(MemoryChunk::TO_PAGE));
  PtrComprCageBase cage_base(heap()->isolate());
  static_cast<LargeObjectSpace*>(page->owner())->RemovePage(page);
  chunk->ClearFlagNonExecutable(MemoryChunk::FROM_PAGE);
  chunk->SetOldGenerationPageFlags(
      heap()->incremental_marking()->marking_mode(), LO_SPACE);
  AddPage(page, static_cast<size_t>(page->GetObject()->Size(cage_base)));
}
References v8::internal::LargeObjectSpace::AddPage(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::ClearFlagNonExecutable(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryChunk::FROM_PAGE, v8::internal::LargePageMetadata::GetObject(), v8::internal::BaseSpace::heap(), v8::internal::Heap::incremental_marking(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::LO_SPACE, v8::internal::IncrementalMarking::marking_mode(), v8::internal::NEW_LO_SPACE, v8::internal::MutablePageMetadata::owner(), v8::internal::MutablePageMetadata::owner_identity(), v8::internal::LargeObjectSpace::RemovePage(), v8::internal::MemoryChunk::SetOldGenerationPageFlags(), and v8::internal::MemoryChunk::TO_PAGE.
Referenced by v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/large-spaces.h
/mnt/V8SourceCode/src/heap/large-spaces.cc