v8::internal::compiler::ReferenceMapPopulator Class Reference
#include <register-allocator.h>
Public Member Functions
ReferenceMapPopulator (RegisterAllocationData *data)
ReferenceMapPopulator (const ReferenceMapPopulator &)=delete
ReferenceMapPopulator & operator= (const ReferenceMapPopulator &)=delete
void PopulateReferenceMaps ()
Private Member Functions
RegisterAllocationData * data () const
bool SafePointsAreInOrder () const
Private Attributes
RegisterAllocationData *const data_
Detailed Description
Definition at line 1717 of file register-allocator.h.
Constructor & Destructor Documentation
ReferenceMapPopulator() [1/2]
v8::internal::compiler::ReferenceMapPopulator::ReferenceMapPopulator (RegisterAllocationData * data) [explicit]
Definition at line 4758 of file register-allocator.cc.
    : data_(data) {}
ReferenceMapPopulator() [2/2]
v8::internal::compiler::ReferenceMapPopulator::ReferenceMapPopulator (const ReferenceMapPopulator &) [delete]
Member Function Documentation
data()
RegisterAllocationData* v8::internal::compiler::ReferenceMapPopulator::data () const [inline], [private]
Definition at line 1727 of file register-allocator.h.
{ return data_; }
References data_.
Referenced by PopulateReferenceMaps(), and SafePointsAreInOrder().
operator=()
ReferenceMapPopulator& v8::internal::compiler::ReferenceMapPopulator::operator= (const ReferenceMapPopulator &) [delete]
PopulateReferenceMaps()
void v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps ()
Definition at line 4770 of file register-allocator.cc.
                                                  {
  DCHECK(SafePointsAreInOrder());
  // Map all delayed references.
  for (RegisterAllocationData::DelayedReference& delayed_reference :
       data()->delayed_references()) {
    delayed_reference.map->RecordReference(
        AllocatedOperand::cast(*delayed_reference.operand));
  }
  // Iterate over all safe point positions and record a pointer
  // for all spilled live ranges at this point.
  int last_range_start = 0;
  const ReferenceMaps* reference_maps = data()->code()->reference_maps();
  ReferenceMaps::const_iterator first_it = reference_maps->begin();
  const size_t live_ranges_size = data()->live_ranges().size();
  // Select subset of `TopLevelLiveRange`s to process, sort them by their start.
  ZoneVector<TopLevelLiveRange*> candidate_ranges(data()->allocation_zone());
  candidate_ranges.reserve(data()->live_ranges().size());
  for (TopLevelLiveRange* range : data()->live_ranges()) {
    CHECK_EQ(live_ranges_size,
             data()->live_ranges().size()); // TODO(neis): crbug.com/831822
    DCHECK_NOT_NULL(range);
    // Skip non-reference values.
    if (!data()->code()->IsReference(range->vreg())) continue;
    // Skip empty live ranges.
    if (range->IsEmpty()) continue;
    if (range->has_preassigned_slot()) continue;
    candidate_ranges.push_back(range);
  }
  std::sort(candidate_ranges.begin(), candidate_ranges.end(),
            LiveRangeOrdering());
  for (TopLevelLiveRange* range : candidate_ranges) {
    // Find the extent of the range and its children.
    int start = range->Start().ToInstructionIndex();
    int end = range->Children().back()->End().ToInstructionIndex();
    // Ranges should be sorted, so that the first reference map in the current
    // live range has to be after {first_it}.
    DCHECK_LE(last_range_start, start);
    last_range_start = start;
    USE(last_range_start);
    // Step across all the safe points that are before the start of this range,
    // recording how far we step in order to save doing this for the next range.
    for (; first_it != reference_maps->end(); ++first_it) {
      ReferenceMap* map = *first_it;
      if (map->instruction_position() >= start) break;
    }
    InstructionOperand spill_operand;
    if (((range->HasSpillOperand() &&
          !range->GetSpillOperand()->IsConstant()) ||
         range->HasSpillRange())) {
      if (range->HasSpillOperand()) {
        spill_operand = *range->GetSpillOperand();
      } else {
        spill_operand = range->GetSpillRangeOperand();
      }
      DCHECK(spill_operand.IsStackSlot());
      DCHECK(CanBeTaggedOrCompressedPointer(
          AllocatedOperand::cast(spill_operand).representation()));
    }
    LiveRange* cur = nullptr;
    // Step through the safe points to see whether they are in the range.
    for (auto it = first_it; it != reference_maps->end(); ++it) {
      ReferenceMap* map = *it;
      int safe_point = map->instruction_position();
      // The safe points are sorted so we can stop searching here.
      if (safe_point - 1 > end) break;
      // Advance to the next active range that covers the current
      // safe point position.
      LifetimePosition safe_point_pos =
          LifetimePosition::InstructionFromInstructionIndex(safe_point);
      // Search for the child range (cur) that covers safe_point_pos. If we
      // don't find it before the children pass safe_point_pos, keep cur at
      // the last child, because the next safe_point_pos may be covered by cur.
      // This may happen if cur has more than one interval, and the current
      // safe_point_pos is in between intervals.
      // For that reason, cur may be at most the last child.
      // Use binary search for the first iteration, then linear search after.
      bool found = false;
      if (cur == nullptr) {
        cur = range->GetChildCovers(safe_point_pos);
        found = cur != nullptr;
      } else {
        while (!found) {
          if (cur->Covers(safe_point_pos)) {
            found = true;
          } else {
            LiveRange* next = cur->next();
            if (next == nullptr || next->Start() > safe_point_pos) {
              break;
            }
            cur = next;
          }
        }
      }
      if (!found) {
        continue;
      }
      // Check if the live range is spilled and the safe point is after
      // the spill position.
      int spill_index = range->IsSpilledOnlyInDeferredBlocks(data()) ||
                                range->LateSpillingSelected()
                            ? cur->Start().ToInstructionIndex()
                            : range->spill_start_index();
      if (!spill_operand.IsInvalid() && safe_point >= spill_index) {
        TRACE("Pointer for range %d (spilled at %d) at safe point %d\n",
              range->vreg(), spill_index, safe_point);
        map->RecordReference(AllocatedOperand::cast(spill_operand));
      }
      if (!cur->spilled()) {
        TRACE(
            "Pointer in register for range %d:%d (start at %d) "
            "at safe point %d\n",
            range->vreg(), cur->relative_id(), cur->Start().value(),
            safe_point);
        InstructionOperand operand = cur->GetAssignedOperand();
        DCHECK(!operand.IsStackSlot());
        DCHECK(CanBeTaggedOrCompressedPointer(
            AllocatedOperand::cast(operand).representation()));
        map->RecordReference(AllocatedOperand::cast(operand));
      }
    }
  }
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::CanBeTaggedOrCompressedPointer(), v8::internal::compiler::LocationOperand::cast(), CHECK_EQ, v8::internal::compiler::RegisterAllocationData::code(), code, v8::internal::compiler::LiveRange::Covers(), data(), v8::internal::DCHECK(), DCHECK_LE, DCHECK_NOT_NULL, v8::internal::ZoneVector< T >::end(), v8::internal::compiler::end(), v8::internal::compiler::LiveRange::GetAssignedOperand(), v8::internal::compiler::ReferenceMap::instruction_position(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::RegisterAllocationData::live_ranges(), v8::internal::compiler::LiveRange::next(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::ReferenceMap::RecordReference(), v8::internal::compiler::InstructionSequence::reference_maps(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::ZoneVector< T >::reserve(), SafePointsAreInOrder(), size(), v8::base::sort(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LifetimePosition::ToInstructionIndex(), v8::internal::TRACE(), USE, and v8::internal::compiler::LifetimePosition::value().
Referenced by v8::internal::compiler::turboshaft::PopulateReferenceMapsPhase::Run().
SafePointsAreInOrder()
bool v8::internal::compiler::ReferenceMapPopulator::SafePointsAreInOrder () const [private]
Definition at line 4761 of file register-allocator.cc.
                                                       {
  int safe_point = 0;
  for (ReferenceMap* map : *data()->code()->reference_maps()) {
    if (safe_point > map->instruction_position()) return false;
    safe_point = map->instruction_position();
  }
  return true;
}
References code, and data().
Referenced by PopulateReferenceMaps().
Member Data Documentation
data_
RegisterAllocationData* const v8::internal::compiler::ReferenceMapPopulator::data_ [private]
Definition at line 1731 of file register-allocator.h.
Referenced by data().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc