v8::internal::compiler::Verifier Class Reference
#include <verifier.h>
Classes
class Visitor
Public Types
enum Typing { TYPED
, UNTYPED
 }
enum CheckInputs { kValuesOnly
, kAll
 }
enum CodeType { kDefault
, kWasm
 }
Public Member Functions
Verifier (const Verifier &)=delete
Verifier & operator= (const Verifier &)=delete
Static Public Member Functions
static void Run (TFGraph *graph, Typing typing=TYPED, CheckInputs check_inputs=kAll, CodeType code_type=kDefault)
static void VerifyNode (Node *node)
static void VerifyEdgeInputReplacement (const Edge &edge, const Node *replacement)
Detailed Description
Definition at line 21 of file verifier.h.
Member Enumeration Documentation
CheckInputs
enum v8::internal::compiler::Verifier::CheckInputs
Enumerator
kValuesOnly
kAll
Definition at line 24 of file verifier.h.
{ kValuesOnly, kAll };
CodeType
enum v8::internal::compiler::Verifier::CodeType
Enumerator
kDefault
kWasm
Definition at line 25 of file verifier.h.
{ kDefault, kWasm };
Typing
enum v8::internal::compiler::Verifier::Typing
Enumerator
TYPED
UNTYPED
Definition at line 23 of file verifier.h.
{ TYPED, UNTYPED };
Constructor & Destructor Documentation
Verifier()
v8::internal::compiler::Verifier::Verifier (const Verifier &) [delete]
Member Function Documentation
operator=()
Verifier& v8::internal::compiler::Verifier::operator= (const Verifier &) [delete]
Run()
void v8::internal::compiler::Verifier::Run (TFGraph * graph, Typing typing = TYPED, CheckInputs check_inputs = kAll, CodeType code_type = kDefault) [static]
Definition at line 2093 of file verifier.cc.
                                       {
  CHECK_NOT_NULL(graph->start());
  CHECK_NOT_NULL(graph->end());
  Zone zone(graph->zone()->allocator(), ZONE_NAME);
  Visitor visitor(&zone, typing, check_inputs, code_type);
  AllNodes all(&zone, graph);
  for (Node* node : all.reachable) visitor.Check(node, all);
  // Check the uniqueness of projections.
  for (Node* proj : all.reachable) {
    if (proj->opcode() != IrOpcode::kProjection) continue;
    Node* node = proj->InputAt(0);
    for (Node* other : node->uses()) {
      if (all.IsLive(other) && other != proj &&
          other->opcode() == IrOpcode::kProjection &&
          other->InputAt(0) == node &&
          ProjectionIndexOf(other->op()) == ProjectionIndexOf(proj->op())) {
        FATAL("Node #%d:%s has duplicate projections #%d and #%d", node->id(),
              node->op()->mnemonic(), proj->id(), other->id());
      }
    }
  }
}
References all, v8::internal::compiler::Verifier::Visitor::Check(), CHECK_NOT_NULL, FATAL, graph(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ProjectionIndexOf(), v8::internal::compiler::Node::uses(), and ZONE_NAME.
Referenced by v8::internal::compiler::VerifyGraphPhase::Run().
VerifyEdgeInputReplacement()
static void v8::internal::compiler::Verifier::VerifyEdgeInputReplacement (const Edge & edge, const Node * replacement) [inline], [static]
Definition at line 52 of file verifier.h.
                                                                  {}
Referenced by v8::internal::compiler::GraphReducer::Replace().
VerifyNode()
static void v8::internal::compiler::Verifier::VerifyNode (Node * node) [inline], [static]
Definition at line 51 of file verifier.h.
{}
Referenced by v8::internal::compiler::NodeProperties::ChangeOp(), and v8::internal::compiler::TFGraph::NewNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/verifier.h
/mnt/V8SourceCode/src/compiler/verifier.cc