cppgc::MakeGarbageCollectedTrait< T > Class Template Reference
Default trait class that specifies how to construct an object of type T.
#include <allocation.h>
Static Public Member Functions
template<typename... Args>
static T * Call (AllocationHandle &handle, Args &&... args)
template<typename... Args>
static T * Call (AllocationHandle &handle, AdditionalBytes additional_bytes, Args &&... args)
Additional Inherited Members
Detailed Description
template<typename T>
class cppgc::MakeGarbageCollectedTrait< T >
Default trait class that specifies how to construct an object of type T.
Advanced users may override how an object is constructed using the utilities that are provided through MakeGarbageCollectedTraitBase.
Any trait overriding construction must
allocate through MakeGarbageCollectedTraitBase<T>::Allocate;
mark the object as fully constructed using MakeGarbageCollectedTraitBase<T>::MarkObjectAsFullyConstructed;
Definition at line 234 of file allocation.h.
Member Function Documentation
Call() [1/2]
template<typename T >
template<typename... Args>
static T* cppgc::MakeGarbageCollectedTrait< T >::Call (AllocationHandle & handle, AdditionalBytes additional_bytes, Args &&... args) [inline], [static]
Definition at line 246 of file allocation.h.
                                 {
    void* memory = MakeGarbageCollectedTraitBase<T>::Allocate(
        handle, sizeof(T) + additional_bytes.value);
    T* object = ::new (memory) T(std::forward<Args>(args)...);
    MakeGarbageCollectedTraitBase<T>::MarkObjectAsFullyConstructed(object);
    return object;
  }
References cppgc::MakeGarbageCollectedTraitBase< T >::Allocate(), v8::base::args, v8::internal::handle(), cppgc::MakeGarbageCollectedTraitBase< T >::MarkObjectAsFullyConstructed(), T, and cppgc::AdditionalBytes::value.
Call() [2/2]
template<typename T >
template<typename... Args>
static T* cppgc::MakeGarbageCollectedTrait< T >::Call (AllocationHandle & handle, Args &&... args) [inline], [static]
Definition at line 237 of file allocation.h.
                                                           {
    void* memory =
        MakeGarbageCollectedTraitBase<T>::Allocate(handle, sizeof(T));
    T* object = ::new (memory) T(std::forward<Args>(args)...);
    MakeGarbageCollectedTraitBase<T>::MarkObjectAsFullyConstructed(object);
    return object;
  }
References cppgc::MakeGarbageCollectedTraitBase< T >::Allocate(), v8::base::args, v8::internal::handle(), cppgc::MakeGarbageCollectedTraitBase< T >::MarkObjectAsFullyConstructed(), and T.
Referenced by cppgc::MakeGarbageCollected().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/allocation.h