v8::internal::TemplateInfo Class Reference
#include <templates.h>
Public Types
enum class CachingMode { kLimited
, kUnlimited
 }
using BodyDescriptor = StructBodyDescriptor
Public Member Functions
uint32_t EnsureHasSerialNumber (Isolate *isolate)
uint32_t GetHash () const
bool TryGetIsolate (Isolate **isolate) const
Isolate * GetIsolateChecked () const
Static Public Member Functions
template<typename ReturnType >
static MaybeHandle< ReturnType > ProbeInstantiationsCache (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateInfo > info, CachingMode caching_mode)
static MaybeHandle< Object > ProbeInstantiationsCache (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateInfo > info, CachingMode caching_mode)
static void CacheTemplateInstantiation (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateInfo > info, CachingMode caching_mode, DirectHandle< Object > object)
static void UncacheTemplateInstantiation (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateInfo > info, CachingMode caching_mode)
Static Public Attributes
static const int kFastTemplateInstantiationsCacheSize = 1 * KB
static constexpr int kMaxTemplateInstantiationsCacheSize = 1 * MB
static const int kUninitializedSerialNumber = 0
static const int kFirstNonUniqueSerialNumber
Detailed Description
Definition at line 30 of file templates.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::TemplateInfo::BodyDescriptor = StructBodyDescriptor
Definition at line 59 of file templates.h.
Member Enumeration Documentation
CachingMode
enum v8::internal::TemplateInfo::CachingMode [strong]
Enumerator
kLimited
kUnlimited
Definition at line 67 of file templates.h.
{ kLimited, kUnlimited };
Member Function Documentation
CacheTemplateInstantiation()
void v8::internal::TemplateInfo::CacheTemplateInstantiation (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateInfo > info, CachingMode caching_mode, DirectHandle< Object > object) [inline], [static]
Definition at line 382 of file templates-inl.h.
                                 {
  DCHECK(info->is_cacheable());
  uint32_t serial_number = info->EnsureHasSerialNumber(isolate);
  if (serial_number < kFastTemplateInstantiationsCacheSize) {
    Handle<FixedArray> fast_cache =
        handle(native_context->fast_template_instantiations_cache(), isolate);
    fast_cache->set(serial_number, *object);
    return;
  }
  Handle<EphemeronHashTable> cache =
      handle(native_context->slow_template_instantiations_cache(), isolate);
  if (caching_mode == CachingMode::kUnlimited ||
      (cache->NumberOfElements() < kMaxTemplateInstantiationsCacheSize)) {
    ReadOnlyRoots roots(isolate);
    // Instead of detouring via Object::GetHash() load the hash directly.
    uint32_t hash = info->GetHash();
    auto new_cache =
        EphemeronHashTable::Put(isolate, cache, info, object, hash);
    if (*new_cache != *cache) {
      native_context->set_slow_template_instantiations_cache(*new_cache);
    }
  }
}
References v8::internal::DCHECK(), v8::internal::handle(), kFastTemplateInstantiationsCacheSize, kMaxTemplateInstantiationsCacheSize, kUnlimited, and v8::internal::native_context.
Referenced by v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject(), and v8::internal::DictionaryTemplateInfo::NewInstance().
EnsureHasSerialNumber()
uint32_t v8::internal::TemplateInfo::EnsureHasSerialNumber (Isolate * isolate) [inline]
Definition at line 332 of file templates-inl.h.
                                                             {
  uint32_t serial_number = this->serial_number();
  if (serial_number == kUninitializedSerialNumber) {
    CHECK(!HeapLayout::InReadOnlySpace(*this));
    serial_number = isolate->heap()->GetNextTemplateSerialNumber();
    set_serial_number(serial_number);
  }
  return serial_number;
}
References CHECK, v8::internal::Heap::GetNextTemplateSerialNumber(), v8::internal::Isolate::heap(), v8::internal::HeapLayout::InReadOnlySpace(), and kUninitializedSerialNumber.
GetHash()
uint32_t v8::internal::TemplateInfo::GetHash () const [inline]
Definition at line 342 of file templates-inl.h.
                                     {
  uint32_t hash = ComputeUnseededHash(serial_number());
  // Make sure that the hash can be encoded in a Smi in order to make it
  // compatible with Object::GetSimpleHash() and avoid surprises.
  return hash & Smi::kMaxValue;
}
References v8::internal::ComputeUnseededHash(), and v8::internal::Smi::kMaxValue.
GetIsolateChecked()
Isolate * v8::internal::TemplateInfo::GetIsolateChecked () const [inline]
Definition at line 300 of file templates-inl.h.
                                               {
  Isolate* isolate;
  CHECK(TryGetIsolate(&isolate));
  return isolate;
}
References CHECK, and TryGetIsolate().
ProbeInstantiationsCache() [1/2]
template<typename ReturnType >
static MaybeHandle<ReturnType> v8::internal::TemplateInfo::ProbeInstantiationsCache (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateInfo > info, CachingMode caching_mode) [inline], [static]
Definition at line 70 of file templates.h.
                                                                 {
    return Cast<ReturnType>(
        ProbeInstantiationsCache(isolate, native_context, info, caching_mode));
  }
References v8::internal::native_context.
ProbeInstantiationsCache() [2/2]
MaybeHandle< Object > v8::internal::TemplateInfo::ProbeInstantiationsCache (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateInfo > info, CachingMode caching_mode) [inline], [static]
Definition at line 350 of file templates-inl.h.
                                                               {
  DCHECK(info->is_cacheable());
  uint32_t serial_number = info->serial_number();
  if (serial_number == kUninitializedSerialNumber) {
    return {};
  }
  if (serial_number < kFastTemplateInstantiationsCacheSize) {
    Tagged<FixedArray> fast_cache =
        native_context->fast_template_instantiations_cache();
    Tagged<Object> object = fast_cache->get(serial_number);
    if (IsTheHole(object, isolate)) {
      return {};
    }
    return handle(object, isolate);
  }
  Tagged<EphemeronHashTable> cache =
      native_context->slow_template_instantiations_cache();
  ReadOnlyRoots roots(isolate);
  // Instead of detouring via Object::GetHash() load the hash directly.
  uint32_t hash = info->GetHash();
  InternalIndex entry = cache->FindEntry(isolate, roots, info, hash);
  if (entry.is_found()) {
    return handle(cache->ValueAt(entry), isolate);
  }
  return {};
}
References v8::internal::DCHECK(), v8::internal::handle(), v8::internal::InternalIndex::is_found(), kFastTemplateInstantiationsCacheSize, kUninitializedSerialNumber, and v8::internal::native_context.
TryGetIsolate()
bool v8::internal::TemplateInfo::TryGetIsolate (Isolate ** isolate) const [inline]
Definition at line 290 of file templates-inl.h.
                                                        {
  if (GetIsolateFromHeapObject(*this, isolate)) return true;
  Isolate* isolate_value = Isolate::TryGetCurrent();
  if (isolate_value != nullptr) {
    *isolate = isolate_value;
    return true;
  }
  return false;
}
References v8::internal::GetIsolateFromHeapObject(), and v8::Isolate::TryGetCurrent().
Referenced by GetIsolateChecked().
UncacheTemplateInstantiation()
void v8::internal::TemplateInfo::UncacheTemplateInstantiation (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateInfo > info, CachingMode caching_mode) [inline], [static]
Definition at line 412 of file templates-inl.h.
                                                               {
  int serial_number = info->serial_number();
  if (serial_number == kUninitializedSerialNumber) return;
  if (serial_number < kFastTemplateInstantiationsCacheSize) {
    Tagged<FixedArray> fast_cache =
        native_context->fast_template_instantiations_cache();
    DCHECK(!IsUndefined(fast_cache->get(serial_number), isolate));
    fast_cache->set(serial_number, ReadOnlyRoots{isolate}.the_hole_value(),
                    SKIP_WRITE_BARRIER);
    return;
  }
  Handle<EphemeronHashTable> cache =
      handle(native_context->slow_template_instantiations_cache(), isolate);
  // Instead of detouring via Object::GetHash() load the hash directly.
  uint32_t hash = info->GetHash();
  bool was_present = false;
  auto new_cache =
      EphemeronHashTable::Remove(isolate, cache, info, &was_present, hash);
  DCHECK(was_present);
  if (!new_cache.is_identical_to(cache)) {
    native_context->set_slow_template_instantiations_cache(*new_cache);
  }
}
References v8::internal::DCHECK(), v8::internal::handle(), kFastTemplateInstantiationsCacheSize, kUninitializedSerialNumber, v8::internal::native_context, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction(), and v8::internal::DictionaryTemplateInfo::NewInstance().
Member Data Documentation
kFastTemplateInstantiationsCacheSize
const int v8::internal::TemplateInfo::kFastTemplateInstantiationsCacheSize = 1 * KB [static]
Definition at line 33 of file templates.h.
Referenced by CacheTemplateInstantiation(), v8::internal::Genesis::InstallABunchOfRandomThings(), ProbeInstantiationsCache(), and UncacheTemplateInstantiation().
kFirstNonUniqueSerialNumber
const int v8::internal::TemplateInfo::kFirstNonUniqueSerialNumber [static]
Initial value:
=
      kFastTemplateInstantiationsCacheSize
Definition at line 44 of file templates.h.
Referenced by v8::internal::Heap::GetNextTemplateSerialNumber().
kMaxTemplateInstantiationsCacheSize
constexpr int v8::internal::TemplateInfo::kMaxTemplateInstantiationsCacheSize = 1 * MB [static], [constexpr]
Definition at line 38 of file templates.h.
Referenced by CacheTemplateInstantiation().
kUninitializedSerialNumber
const int v8::internal::TemplateInfo::kUninitializedSerialNumber = 0 [static]
Definition at line 41 of file templates.h.
Referenced by v8::internal::Heap::CreateInitialMutableObjects(), EnsureHasSerialNumber(), v8::internal::Heap::GetNextTemplateSerialNumber(), v8::internal::anonymous_namespace{factory.cc}::InitializeTemplate(), ProbeInstantiationsCache(), and UncacheTemplateInstantiation().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/templates.h
/mnt/V8SourceCode/src/objects/templates-inl.h