v8::GlobalValueMap< K, V, Traits > Class Template Reference
#include <v8-util.h>
Public Types
typedef PersistentValueMapBase< K, V, Traits >::PersistentValueReference PersistentValueReference
Public Member Functions
GlobalValueMap (Isolate *isolate)
GlobalValueMap (Isolate *isolate, const char *label)
Global< V > Set (const K &key, Local< V > value)
Put value into map.
Global< V > Set (const K &key, Global< V > value)
Put value into map, like Set(const K&, Local<V>).
Global< V > SetUnique (const K &key, Global< V > *persistent)
Put the value into the map, and set the 'weak' callback when demanded by the Traits class.
Global< V > Set (const K &key, Global< V > value, PersistentValueReference *reference)
Put a value into the map and update the reference.
Static Private Member Functions
static void OnWeakCallback (const WeakCallbackInfo< typename Traits::WeakCallbackDataType > &data)
static void SecondWeakCallback (const WeakCallbackInfo< typename Traits::WeakCallbackDataType > &data)
Additional Inherited Members
Detailed Description
template<typename K, typename V, typename Traits>
class v8::GlobalValueMap< K, V, Traits >
Definition at line 437 of file v8-util.h.
Member Typedef Documentation
PersistentValueReference
template<typename K , typename V , typename Traits >
typedef PersistentValueMapBase<K, V, Traits>::PersistentValueReference v8::GlobalValueMap< K, V, Traits >::PersistentValueReference
Definition at line 446 of file v8-util.h.
Constructor & Destructor Documentation
GlobalValueMap() [1/2]
template<typename K , typename V , typename Traits >
v8::GlobalValueMap< K, V, Traits >::GlobalValueMap (Isolate * isolate) [inline], [explicit]
Definition at line 439 of file v8-util.h.
      : PersistentValueMapBase<K, V, Traits>(isolate) {}
References V.
GlobalValueMap() [2/2]
template<typename K , typename V , typename Traits >
v8::GlobalValueMap< K, V, Traits >::GlobalValueMap (Isolate * isolate, const char * label) [inline]
Definition at line 441 of file v8-util.h.
      : PersistentValueMapBase<K, V, Traits>(isolate, label) {}
References V.
Member Function Documentation
OnWeakCallback()
template<typename K , typename V , typename Traits >
static void v8::GlobalValueMap< K, V, Traits >::OnWeakCallback (const WeakCallbackInfo< typename Traits::WeakCallbackDataType > & data) [inline], [static], [private]
Definition at line 498 of file v8-util.h.
                                                                         {
    if (Traits::kCallbackType != kNotWeak) {
      auto map = Traits::MapFromWeakCallbackInfo(data);
      K key = Traits::KeyFromWeakCallbackInfo(data);
      map->RemoveWeak(key);
      Traits::OnWeakCallback(data);
      data.SetSecondPassCallback(SecondWeakCallback);
    }
  }
References v8::internal::K, v8::internal::key, v8::kNotWeak, v8::GlobalValueMap< K, V, Traits >::SecondWeakCallback(), and v8::WeakCallbackInfo< T >::SetSecondPassCallback().
Referenced by v8::GlobalValueMap< K, V, Traits >::SetUnique().
SecondWeakCallback()
template<typename K , typename V , typename Traits >
static void v8::GlobalValueMap< K, V, Traits >::SecondWeakCallback (const WeakCallbackInfo< typename Traits::WeakCallbackDataType > & data) [inline], [static], [private]
Definition at line 509 of file v8-util.h.
                                                                         {
    Traits::DisposeWeak(data);
  }
Referenced by v8::GlobalValueMap< K, V, Traits >::OnWeakCallback().
Set() [1/3]
template<typename K , typename V , typename Traits >
Global<V> v8::GlobalValueMap< K, V, Traits >::Set (const K & key, Global< V > value) [inline]
Put value into map, like Set(const K&, Local<V>).
Definition at line 461 of file v8-util.h.
                                               {
    return SetUnique(key, &value);
  }
References v8::internal::key, v8::GlobalValueMap< K, V, Traits >::SetUnique(), and v8::internal::value.
Set() [2/3]
template<typename K , typename V , typename Traits >
Global<V> v8::GlobalValueMap< K, V, Traits >::Set (const K & key, Global< V > value, PersistentValueReference * reference) [inline]
Put a value into the map and update the reference.
Restrictions of GetReference apply here as well.
Definition at line 491 of file v8-util.h.
                                                     {
    *reference = this->Leak(&value);
    return SetUnique(key, &value);
  }
References v8::internal::key, v8::PersistentValueMapBase< K, V, Traits >::Leak(), v8::GlobalValueMap< K, V, Traits >::SetUnique(), and v8::internal::value.
Set() [3/3]
template<typename K , typename V , typename Traits >
Global<V> v8::GlobalValueMap< K, V, Traits >::Set (const K & key, Local< V > value) [inline]
Put value into map.
Depending on Traits::kIsWeak, the value will be held by the map strongly or weakly. Returns old value as Global.
Definition at line 453 of file v8-util.h.
                                              {
    Global<V> persistent(this->isolate(), value);
    return SetUnique(key, &persistent);
  }
References v8::PersistentValueMapBase< K, V, Traits >::isolate(), v8::internal::key, and v8::GlobalValueMap< K, V, Traits >::SetUnique().
SetUnique()
template<typename K , typename V , typename Traits >
Global<V> v8::GlobalValueMap< K, V, Traits >::SetUnique (const K & key, Global< V > * persistent) [inline]
Put the value into the map, and set the 'weak' callback when demanded by the Traits class.
Definition at line 469 of file v8-util.h.
                                                           {
    if (Traits::kCallbackType == kNotWeak) {
      this->AnnotateStrongRetainer(persistent);
    } else {
      WeakCallbackType callback_type =
          Traits::kCallbackType == kWeakWithInternalFields
              ? WeakCallbackType::kInternalFields
              : WeakCallbackType::kParameter;
      auto value = Local<V>::New(this->isolate(), *persistent);
      persistent->template SetWeak<typename Traits::WeakCallbackDataType>(
          Traits::WeakCallbackParameter(this, key, value), OnWeakCallback,
          callback_type);
    }
    PersistentContainerValue old_value =
        Traits::Set(this->impl(), key, this->ClearAndLeak(persistent));
    return this->Release(old_value).Pass();
  }
References v8::PersistentValueMapBase< K, V, Traits >::AnnotateStrongRetainer(), v8::PersistentValueMapBase< K, V, Traits >::ClearAndLeak(), v8::PersistentValueMapBase< K, V, Traits >::impl(), v8::PersistentValueMapBase< K, V, Traits >::isolate(), v8::internal::key, v8::kInternalFields, v8::kNotWeak, v8::kParameter, v8::kWeakWithInternalFields, v8::Local< T >::New(), v8::GlobalValueMap< K, V, Traits >::OnWeakCallback(), v8::PersistentValueMapBase< K, V, Traits >::Release(), and v8::internal::value.
Referenced by v8::GlobalValueMap< K, V, Traits >::Set().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-util.h