v8::internal::JSArrayBuffer Class Reference
#include <js-array-buffer.h>
Classes
class BodyDescriptor
Public Member Functions
size_t byte_length_unchecked () const
void set_backing_store (Isolate *isolate, void *value)
void init_extension ()
void clear_padding ()
V8_EXPORT_PRIVATE void Setup (SharedFlag shared, ResizableFlag resizable, std::shared_ptr< BackingStore > backing_store, Isolate *isolate)
std::shared_ptr< BackingStore > GetBackingStore () const
size_t GetByteLength () const
V8_EXPORT_PRIVATE ArrayBufferExtension * CreateExtension (Isolate *isolate, std::shared_ptr< BackingStore > backing_store)
std::shared_ptr< BackingStore > RemoveExtension ()
void MarkExtension ()
void YoungMarkExtension ()
void YoungMarkExtensionPromoted ()
uint32_t GetBackingStoreRefForDeserialization () const
void SetBackingStoreRefForSerialization (uint32_t ref)
Static Public Member Functions
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > Detach (DirectHandle< JSArrayBuffer > buffer, bool force_for_wasm_memory=false, DirectHandle< Object > key={})
static size_t GsabByteLength (Isolate *isolate, Address raw_array_buffer)
static Maybe< bool > GetResizableBackingStorePageConfiguration (Isolate *isolate, size_t byte_length, size_t max_byte_length, ShouldThrow should_throw, size_t *page_size, size_t *initial_pages, size_t *max_pages)
static std::optional< MessageTemplate > GetResizableBackingStorePageConfigurationImpl (Isolate *isolate, size_t byte_length, size_t max_byte_length, size_t *page_size, size_t *initial_pages, size_t *max_pages)
Static Public Attributes
static constexpr size_t kMaxByteLength = kMaxSafeInteger
static constexpr int kSizeWithEmbedderFields
static constexpr bool kContainsEmbedderFields
Private Member Functions
void DetachInternal (bool force_for_wasm_memory, Isolate *isolate)
ArrayBufferExtension ** extension_location () const
Detailed Description
Definition at line 25 of file js-array-buffer.h.
Member Function Documentation
byte_length_unchecked()
size_t v8::internal::JSArrayBuffer::byte_length_unchecked () const [inline]
Referenced by GetByteLength().
clear_padding()
void v8::internal::JSArrayBuffer::clear_padding () [inline]
Definition at line 164 of file js-array-buffer-inl.h.
                                  {
  if (FIELD_SIZE(kOptionalPaddingOffset) != 0) {
    DCHECK_EQ(4, FIELD_SIZE(kOptionalPaddingOffset));
    memset(reinterpret_cast<void*>(address() + kOptionalPaddingOffset), 0,
           FIELD_SIZE(kOptionalPaddingOffset));
  }
}
References DCHECK_EQ, and FIELD_SIZE.
Referenced by Setup().
CreateExtension()
ArrayBufferExtension * v8::internal::JSArrayBuffer::CreateExtension (Isolate * isolate, std::shared_ptr< BackingStore > backing_store)
Definition at line 248 of file js-array-buffer.cc.
                                                                 {
  // `Heap::InYoungGeneration` during full GC with sticky markbits is generally
  // inaccurate. However, a full GC will sweep both lists and promote all to
  // old, so it doesn't matter which list initially holds the extension in this
  // case.
  const auto age =
      HeapLayout::InYoungGeneration(UncheckedCast<JSArrayBuffer>(*this))
          ? ArrayBufferExtension::Age::kYoung
          : ArrayBufferExtension::Age::kOld;
  ArrayBufferExtension* extension =
      new ArrayBufferExtension(std::move(backing_store), age);
  set_extension(extension);
  isolate->heap()->AppendArrayBufferExtension(extension);
  return extension;
}
References v8::internal::Heap::AppendArrayBufferExtension(), v8::internal::Isolate::heap(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::ArrayBufferExtension::kOld, and v8::internal::ArrayBufferExtension::kYoung.
Referenced by Setup().
Detach()
Maybe< bool > v8::internal::JSArrayBuffer::Detach (DirectHandle< JSArrayBuffer > buffer, bool force_for_wasm_memory = false, DirectHandle< Object > key = {}) [static]
Definition at line 123 of file js-array-buffer.cc.
                                                                  {
  Isolate* const isolate = Isolate::Current();
  DirectHandle<Object> detach_key(buffer->detach_key(), isolate);
  bool key_mismatch = false;
  if (!IsUndefined(*detach_key, isolate)) {
    key_mismatch =
        maybe_key.is_null() || !Object::StrictEquals(*maybe_key, *detach_key);
  } else {
    // Detach key is undefined; allow not passing maybe_key but disallow passing
    // something else than undefined.
    key_mismatch =
        !maybe_key.is_null() && !Object::StrictEquals(*maybe_key, *detach_key);
  }
  if (key_mismatch) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewTypeError(MessageTemplate::kArrayBufferDetachKeyDoesntMatch),
        Nothing<bool>());
  }
  if (buffer->was_detached()) return Just(true);
  if (force_for_wasm_memory) {
    // Skip the is_detachable() check.
  } else if (!buffer->is_detachable()) {
    // Not detachable, do nothing.
    return Just(true);
  }
  buffer->DetachInternal(force_for_wasm_memory, isolate);
  return Just(true);
}
References v8::internal::Isolate::Current(), v8::internal::DirectHandle< T >::is_null(), v8::Just(), v8::internal::Object::StrictEquals(), and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::ArrayBuffer::Detach(), v8::internal::WasmMemoryObject::RefreshBuffer(), and v8::internal::RUNTIME_FUNCTION().
DetachInternal()
void v8::internal::JSArrayBuffer::DetachInternal (bool force_for_wasm_memory, Isolate * isolate) [private]
Definition at line 161 of file js-array-buffer.cc.
                                                     {
  ArrayBufferExtension* extension = this->extension();
  if (extension) {
    DisallowGarbageCollection disallow_gc;
    isolate->heap()->DetachArrayBufferExtension(extension);
    std::shared_ptr<BackingStore> backing_store = RemoveExtension();
    CHECK_IMPLIES(force_for_wasm_memory, backing_store->is_wasm_memory());
  }
  if (Protectors::IsArrayBufferDetachingIntact(isolate)) {
    Protectors::InvalidateArrayBufferDetaching(isolate);
  }
  DCHECK(!is_shared());
  set_backing_store(isolate, EmptyBackingStoreBuffer());
  set_byte_length(0);
  set_was_detached(true);
}
References CHECK_IMPLIES, v8::internal::DCHECK(), v8::internal::Heap::DetachArrayBufferExtension(), v8::internal::EmptyBackingStoreBuffer(), v8::internal::Isolate::heap(), v8::internal::is_shared, RemoveExtension(), and set_backing_store().
extension_location()
ArrayBufferExtension ** v8::internal::JSArrayBuffer::extension_location () const [inline], [private]
Definition at line 158 of file js-array-buffer-inl.h.
                                                               {
  Address location = field_address(kExtensionOffset);
  return reinterpret_cast<ArrayBufferExtension**>(location);
}
Referenced by init_extension().
GetBackingStore()
std::shared_ptr< BackingStore > v8::internal::JSArrayBuffer::GetBackingStore () const [inline]
Definition at line 66 of file js-array-buffer-inl.h.
                                                                 {
  if (!extension()) return nullptr;
  return extension()->backing_store();
}
Referenced by GetByteLength().
GetBackingStoreRefForDeserialization()
uint32_t v8::internal::JSArrayBuffer::GetBackingStoreRefForDeserialization () const [inline]
Definition at line 92 of file js-array-buffer-inl.h.
                                                                   {
  return static_cast<uint32_t>(ReadField<Address>(kBackingStoreOffset));
}
GetByteLength()
size_t v8::internal::JSArrayBuffer::GetByteLength () const [inline]
Definition at line 71 of file js-array-buffer-inl.h.
                                          {
  if (V8_UNLIKELY(is_shared() && is_resizable_by_js())) {
    // Invariant: byte_length for GSAB is 0 (it needs to be read from the
    // BackingStore). Don't use the byte_length getter, which DCHECKs that it's
    // not used on growable SharedArrayBuffers.
    DCHECK_EQ(0, byte_length_unchecked());
    // If the byte length is read after the JSArrayBuffer object is allocated
    // but before it's attached to the backing store, GetBackingStore returns
    // nullptr. This is rare, but can happen e.g., when memory measurements
    // are enabled (via performance.measureMemory()).
    auto backing_store = GetBackingStore();
    if (!backing_store) {
      return 0;
    }
    return backing_store->byte_length(std::memory_order_seq_cst);
  }
  return byte_length();
}
References byte_length_unchecked(), DCHECK_EQ, GetBackingStore(), v8::internal::is_shared, and V8_UNLIKELY.
GetResizableBackingStorePageConfiguration()
Maybe< bool > v8::internal::JSArrayBuffer::GetResizableBackingStorePageConfiguration (Isolate * isolate, size_t byte_length, size_t max_byte_length, ShouldThrow should_throw, size_t * page_size, size_t * initial_pages, size_t * max_pages) [static]
Definition at line 196 of file js-array-buffer.cc.
                       {
  DCHECK_NOT_NULL(page_size);
  DCHECK_NOT_NULL(initial_pages);
  DCHECK_NOT_NULL(max_pages);
  *page_size = AllocatePageSize();
  if (!RoundUpToPageSize(byte_length, *page_size, JSArrayBuffer::kMaxByteLength,
                         initial_pages)) {
    if (should_throw == kDontThrow) return Nothing<bool>();
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NewRangeError(MessageTemplate::kInvalidArrayBufferLength),
        Nothing<bool>());
  }
  if (!RoundUpToPageSize(max_byte_length, *page_size,
                         JSArrayBuffer::kMaxByteLength, max_pages)) {
    if (should_throw == kDontThrow) return Nothing<bool>();
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NewRangeError(MessageTemplate::kInvalidArrayBufferMaxLength),
        Nothing<bool>());
  }
  return Just(true);
}
References v8::internal::AllocatePageSize(), DCHECK_NOT_NULL, v8::Just(), v8::internal::kDontThrow, kMaxByteLength, v8::internal::RoundUpToPageSize(), and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::Factory::NewJSArrayBufferAndBackingStore(), and v8::ArrayBuffer::NewResizableBackingStore().
GetResizableBackingStorePageConfigurationImpl()
std::optional< MessageTemplate > v8::internal::JSArrayBuffer::GetResizableBackingStorePageConfigurationImpl (Isolate * isolate, size_t byte_length, size_t max_byte_length, size_t * page_size, size_t * initial_pages, size_t * max_pages) [static]
Definition at line 227 of file js-array-buffer.cc.
                                                                 {
  DCHECK_NOT_NULL(page_size);
  DCHECK_NOT_NULL(initial_pages);
  DCHECK_NOT_NULL(max_pages);
  *page_size = AllocatePageSize();
  if (!RoundUpToPageSize(byte_length, *page_size, JSArrayBuffer::kMaxByteLength,
                         initial_pages)) {
    return MessageTemplate::kInvalidArrayBufferLength;
  }
  if (!RoundUpToPageSize(max_byte_length, *page_size,
                         JSArrayBuffer::kMaxByteLength, max_pages)) {
    return MessageTemplate::kInvalidArrayBufferMaxLength;
  }
  return {};
}
References v8::internal::AllocatePageSize(), DCHECK_NOT_NULL, kMaxByteLength, and v8::internal::RoundUpToPageSize().
Referenced by v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::TryAllocateBackingStore().
GsabByteLength()
size_t v8::internal::JSArrayBuffer::GsabByteLength (Isolate * isolate, Address raw_array_buffer) [static]
Definition at line 182 of file js-array-buffer.cc.
                                                               {
  // TODO(v8:11111): Cache the last seen length in JSArrayBuffer and use it
  // in bounds checks to minimize the need for calling this function.
  DisallowGarbageCollection no_gc;
  DisallowJavascriptExecution no_js(isolate);
  Tagged<JSArrayBuffer> buffer =
      Cast<JSArrayBuffer>(Tagged<Object>(raw_array_buffer));
  CHECK(buffer->is_resizable_by_js());
  CHECK(buffer->is_shared());
  return buffer->GetBackingStore()->byte_length(std::memory_order_seq_cst);
}
References CHECK, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
init_extension()
void v8::internal::JSArrayBuffer::init_extension () [inline]
Definition at line 100 of file js-array-buffer-inl.h.
                                   {
#if V8_COMPRESS_POINTERS
  // The extension field is lazily-initialized, so set it to null initially.
  base::AsAtomic32::Release_Store(extension_handle_location(),
                                  kNullExternalPointerHandle);
#else
  base::AsAtomicPointer::Release_Store(extension_location(), nullptr);
#endif // V8_COMPRESS_POINTERS
}
References extension_location(), v8::internal::kNullExternalPointerHandle, and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store().
Referenced by Setup().
MarkExtension()
void v8::internal::JSArrayBuffer::MarkExtension ()
Definition at line 275 of file js-array-buffer.cc.
                                  {
  ArrayBufferExtension* extension = this->extension();
  if (extension) {
    extension->Mark();
  }
}
References v8::internal::ArrayBufferExtension::Mark().
RemoveExtension()
std::shared_ptr< BackingStore > v8::internal::JSArrayBuffer::RemoveExtension ()
Definition at line 265 of file js-array-buffer.cc.
                                                           {
  ArrayBufferExtension* extension = this->extension();
  DCHECK_NOT_NULL(extension);
  auto result = extension->RemoveBackingStore();
  // Remove pointer to extension such that the next GC will free it
  // automatically.
  set_extension(nullptr);
  return result;
}
References DCHECK_NOT_NULL, v8::internal::ArrayBufferExtension::RemoveBackingStore(), and v8::base::internal::result.
Referenced by DetachInternal().
set_backing_store()
void v8::internal::JSArrayBuffer::set_backing_store (Isolate * isolate, void * value) [inline]
Definition at line 61 of file js-array-buffer-inl.h.
                                                                   {
  Address addr = reinterpret_cast<Address>(value);
  WriteSandboxedPointerField(kBackingStoreOffset, isolate, addr);
}
References v8::internal::value, and v8::internal::WriteSandboxedPointerField().
Referenced by DetachInternal(), and Setup().
SetBackingStoreRefForSerialization()
void v8::internal::JSArrayBuffer::SetBackingStoreRefForSerialization (uint32_t ref) [inline]
Definition at line 96 of file js-array-buffer-inl.h.
                                                                   {
  WriteField<Address>(kBackingStoreOffset, static_cast<Address>(ref));
}
Setup()
void v8::internal::JSArrayBuffer::Setup (SharedFlag shared, ResizableFlag resizable, std::shared_ptr< BackingStore > backing_store, Isolate * isolate)
Definition at line 47 of file js-array-buffer.cc.
                                            {
  auto finish_setup = [shared, isolate]() {
    // Count usage may lead to a blink allocation, through the callback, which
    // may trigger a GC. It is important to delay this, until the array buffer
    // is properly initialized.
    if (shared == SharedFlag::kShared) {
      isolate->CountUsage(
          v8::Isolate::UseCounterFeature::kSharedArrayBufferConstructed);
    }
  };
  clear_padding();
  init_extension();
  set_detach_key(ReadOnlyRoots(isolate).undefined_value());
  set_bit_field(0);
  set_is_shared(shared == SharedFlag::kShared);
  set_is_resizable_by_js(resizable == ResizableFlag::kResizable);
  set_is_detachable(shared != SharedFlag::kShared);
  SetupLazilyInitializedCppHeapPointerField(
      JSAPIObjectWithEmbedderSlots::kCppHeapWrappableOffset);
  for (int i = 0; i < v8::ArrayBuffer::kEmbedderFieldCount; i++) {
    SetEmbedderField(i, Smi::zero());
  }
  if (!backing_store) {
    set_backing_store(isolate, EmptyBackingStoreBuffer());
    set_byte_length(0);
    set_max_byte_length(0);
    finish_setup();
    return;
  }
  // Rest of the code here deals with attaching the BackingStore.
  DCHECK_EQ(is_shared(), backing_store->is_shared());
  DCHECK((is_resizable_by_js() == backing_store->is_resizable_by_js()) ||
         (backing_store->is_wasm_memory() && is_shared()));
  DCHECK_IMPLIES(
      !backing_store->is_wasm_memory() && !backing_store->is_resizable_by_js(),
      backing_store->byte_length() == backing_store->max_byte_length());
  void* backing_store_buffer = backing_store->buffer_start();
  // Wasm memory always needs a backing store; this is guaranteed by reserving
  // at least one page for the BackingStore (so {IsEmpty()} is always false).
  DCHECK_IMPLIES(backing_store->is_wasm_memory(), !backing_store->IsEmpty());
  // Non-empty backing stores must start at a non-null pointer.
  DCHECK_IMPLIES(backing_store_buffer == EmptyBackingStoreBuffer(),
                 backing_store->IsEmpty());
  // Empty backing stores can be backed by an empty buffer pointer or by an
  // externally provided pointer: Either is acceptable. However, the pointer
  // must always point into the sandbox, so nullptr is not acceptable if the
  // sandbox is enabled.
  DCHECK_IMPLIES(V8_ENABLE_SANDBOX_BOOL, backing_store_buffer != nullptr);
  set_backing_store(isolate, backing_store_buffer);
  // GSABs need to read their byte_length from the BackingStore. Maintain the
  // invariant that their byte_length field is always 0.
  auto byte_len =
      (is_shared() && is_resizable_by_js()) ? 0 : backing_store->byte_length();
  CHECK_LE(backing_store->byte_length(), kMaxByteLength);
  set_byte_length(byte_len);
  // For Wasm memories, it is possible for the backing store maximum to be
  // different from the JSArrayBuffer maximum. The maximum pages allowed on a
  // Wasm memory are tracked on the Wasm memory object, and not the
  // JSArrayBuffer associated with it.
  auto max_byte_len = is_resizable_by_js() ? backing_store->max_byte_length()
                                           : backing_store->byte_length();
  set_max_byte_length(max_byte_len);
  if (backing_store->is_wasm_memory()) {
    set_is_detachable(false);
  }
  CreateExtension(isolate, std::move(backing_store));
  finish_setup();
}
References CHECK_LE, clear_padding(), v8::internal::Isolate::CountUsage(), CreateExtension(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::EmptyBackingStoreBuffer(), init_extension(), v8::internal::is_shared, v8::ArrayBuffer::kEmbedderFieldCount, kMaxByteLength, v8::internal::kResizable, v8::internal::kShared, set_backing_store(), V8_ENABLE_SANDBOX_BOOL, and v8::internal::Smi::zero().
YoungMarkExtension()
void v8::internal::JSArrayBuffer::YoungMarkExtension ()
Definition at line 282 of file js-array-buffer.cc.
                                       {
  ArrayBufferExtension* extension = this->extension();
  if (extension) {
    DCHECK_EQ(ArrayBufferExtension::Age::kYoung, extension->age());
    extension->YoungMark();
  }
}
References v8::internal::ArrayBufferExtension::age(), DCHECK_EQ, v8::internal::ArrayBufferExtension::kYoung, and v8::internal::ArrayBufferExtension::YoungMark().
YoungMarkExtensionPromoted()
void v8::internal::JSArrayBuffer::YoungMarkExtensionPromoted ()
Definition at line 290 of file js-array-buffer.cc.
                                               {
  ArrayBufferExtension* extension = this->extension();
  if (extension) {
    extension->YoungMarkPromoted();
  }
}
References v8::internal::ArrayBufferExtension::YoungMarkPromoted().
Member Data Documentation
kContainsEmbedderFields
constexpr bool v8::internal::JSArrayBuffer::kContainsEmbedderFields [static], [constexpr]
Initial value:
=
      v8::ArrayBuffer::kEmbedderFieldCount > 0
Definition at line 166 of file js-array-buffer.h.
Referenced by v8::internal::JSArrayBuffer::BodyDescriptor::IterateBody().
kMaxByteLength
constexpr size_t v8::internal::JSArrayBuffer::kMaxByteLength = kMaxSafeInteger [static], [constexpr]
Definition at line 38 of file js-array-buffer.h.
Referenced by v8::Isolate::AdjustAmountOfExternalAllocatedMemoryImpl(), v8::internal::Heap::AllocateExternalBackingStore(), v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::internal::Runtime::GetInternalProperties(), GetResizableBackingStorePageConfiguration(), GetResizableBackingStorePageConfigurationImpl(), v8::internal::BackingStore::GrowInPlace(), v8::internal::wasm::max_mem32_pages(), v8::internal::wasm::max_mem64_pages(), v8::ArrayBuffer::NewBackingStore(), v8::SharedArrayBuffer::NewBackingStore(), v8::ArrayBuffer::NewResizableBackingStore(), v8::internal::BackingStore::ResizeInPlace(), Setup(), and v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::TryAllocateBackingStore().
kSizeWithEmbedderFields
constexpr int v8::internal::JSArrayBuffer::kSizeWithEmbedderFields [static], [constexpr]
Initial value:
=
      kHeaderSize +
      v8::ArrayBuffer::kEmbedderFieldCount * kEmbedderDataSlotSize
Definition at line 163 of file js-array-buffer.h.
Referenced by v8::internal::TypedArrayBuiltinsAssembler::AllocateEmptyOnHeapBuffer(), and v8::internal::Genesis::CreateArrayBuffer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-array-buffer.h
/mnt/V8SourceCode/src/objects/js-array-buffer-inl.h
/mnt/V8SourceCode/src/objects/js-array-buffer.cc