v8::internal::PendingCompilationErrorHandler::MessageDetails Class Reference
Classes
struct MessageArgument
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (MessageDetails)
MessageDetails ()
MessageDetails (int start_position, int end_position, MessageTemplate message, const AstRawString *arg0)
MessageDetails (int start_position, int end_position, MessageTemplate message, const AstRawString *arg0, const char *arg1)
MessageDetails (int start_position, int end_position, MessageTemplate message, const AstRawString *arg0, const AstRawString *arg1, const char *arg2)
MessageDetails (int start_position, int end_position, MessageTemplate message, const char *arg0)
DirectHandle< String > ArgString (Isolate *isolate, int index) const
int ArgCount () const
MessageLocation GetLocation (Handle< Script > script) const
int start_pos () const
int end_pos () const
MessageTemplate message () const
template<typename IsolateT >
void Prepare (IsolateT *isolate)
Static Public Attributes
static constexpr int kMaxArgumentCount = 3
Private Types
enum Type { kNone
, kAstRawString
, kConstCharString
, kMainThreadHandle
 }
Private Member Functions
void SetString (int index, Handle< String > string, Isolate *isolate)
void SetString (int index, Handle< String > string, LocalIsolate *isolate)
Private Attributes
int start_position_
int end_position_
MessageTemplate message_
MessageArgument args_ [kMaxArgumentCount]
Detailed Description
Definition at line 89 of file pending-compilation-error-handler.h.
Member Enumeration Documentation
Type
enum v8::internal::PendingCompilationErrorHandler::MessageDetails::Type [private]
Enumerator
kNone
kAstRawString
kConstCharString
kMainThreadHandle
Definition at line 158 of file pending-compilation-error-handler.h.
{ kNone, kAstRawString, kConstCharString, kMainThreadHandle };
Constructor & Destructor Documentation
MessageDetails() [1/5]
v8::internal::PendingCompilationErrorHandler::MessageDetails::MessageDetails () [inline]
Definition at line 94 of file pending-compilation-error-handler.h.
        : start_position_(-1),
          end_position_(-1),
          message_(MessageTemplate::kNone) {}
MessageDetails() [2/5]
v8::internal::PendingCompilationErrorHandler::MessageDetails::MessageDetails (int start_position, int end_position, MessageTemplate message, const AstRawString * arg0) [inline]
Definition at line 98 of file pending-compilation-error-handler.h.
        : start_position_(start_position),
          end_position_(end_position),
          message_(message),
          args_{MessageArgument{arg0}, MessageArgument{}, MessageArgument{}} {}
MessageDetails() [3/5]
v8::internal::PendingCompilationErrorHandler::MessageDetails::MessageDetails (int start_position, int end_position, MessageTemplate message, const AstRawString * arg0, const char * arg1) [inline]
Definition at line 104 of file pending-compilation-error-handler.h.
        : start_position_(start_position),
          end_position_(end_position),
          message_(message),
          args_{MessageArgument{arg0}, MessageArgument{arg1},
                MessageArgument{}} {
      DCHECK_NOT_NULL(arg0);
      DCHECK_NOT_NULL(arg1);
    }
References DCHECK_NOT_NULL.
MessageDetails() [4/5]
v8::internal::PendingCompilationErrorHandler::MessageDetails::MessageDetails (int start_position, int end_position, MessageTemplate message, const AstRawString * arg0, const AstRawString * arg1, const char * arg2) [inline]
Definition at line 115 of file pending-compilation-error-handler.h.
        : start_position_(start_position),
          end_position_(end_position),
          message_(message),
          args_{MessageArgument{arg0}, MessageArgument{arg1},
                MessageArgument{arg2}} {
      DCHECK_NOT_NULL(arg0);
      DCHECK_NOT_NULL(arg1);
      DCHECK_NOT_NULL(arg2);
    }
References DCHECK_NOT_NULL.
MessageDetails() [5/5]
v8::internal::PendingCompilationErrorHandler::MessageDetails::MessageDetails (int start_position, int end_position, MessageTemplate message, const char * arg0) [inline]
Definition at line 127 of file pending-compilation-error-handler.h.
        : start_position_(start_position),
          end_position_(end_position),
          message_(message),
          args_{MessageArgument{arg0}, MessageArgument{}, MessageArgument{}} {}
Member Function Documentation
ArgCount()
int v8::internal::PendingCompilationErrorHandler::MessageDetails::ArgCount () const [inline]
Definition at line 135 of file pending-compilation-error-handler.h.
                         {
      int argc = 0;
      for (int i = 0; i < kMaxArgumentCount; i++) {
        if (args_[i].type == kNone) break;
        argc++;
      }
#ifdef DEBUG
      for (int i = argc; i < kMaxArgumentCount; i++) {
        DCHECK_EQ(args_[i].type, kNone);
      }
#endif // DEBUG
      return argc;
    }
References args_, DCHECK_EQ, kMaxArgumentCount, kNone, and v8::internal::tracing::type.
ArgString()
DirectHandle< String > v8::internal::PendingCompilationErrorHandler::MessageDetails::ArgString (Isolate * isolate, int index) const
Definition at line 55 of file pending-compilation-error-handler.cc.
                                       {
  // `index` may be >= argc; in that case we return a default value to pass on
  // elsewhere.
  DCHECK_LT(index, kMaxArgumentCount);
  switch (args_[index].type) {
    case kMainThreadHandle:
      return args_[index].js_string;
    case kNone:
      return Handle<String>::null();
    case kConstCharString:
      return isolate->factory()
          ->NewStringFromUtf8(base::CStrVector(args_[index].c_string),
                              AllocationType::kOld)
          .ToHandleChecked();
    case kAstRawString:
      UNREACHABLE();
  }
}
References v8::base::CStrVector(), DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::index, v8::internal::kNone, v8::internal::kOld, v8::internal::Factory::NewStringFromUtf8(), v8::internal::Handle< T >::null(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::PendingCompilationErrorHandler::FormatErrorMessageForTest(), and v8::internal::PendingCompilationErrorHandler::ThrowPendingError().
end_pos()
int v8::internal::PendingCompilationErrorHandler::MessageDetails::end_pos () const [inline]
Definition at line 151 of file pending-compilation-error-handler.h.
{ return end_position_; }
References end_position_.
GetLocation()
MessageLocation v8::internal::PendingCompilationErrorHandler::MessageDetails::GetLocation (Handle< Script > script) const
Definition at line 75 of file pending-compilation-error-handler.cc.
                                 {
  return MessageLocation(script, start_position_, end_position_);
}
References v8::internal::script.
Referenced by v8::internal::PendingCompilationErrorHandler::ThrowPendingError().
message()
MessageTemplate v8::internal::PendingCompilationErrorHandler::MessageDetails::message () const [inline]
Definition at line 152 of file pending-compilation-error-handler.h.
{ return message_; }
References message_.
Referenced by v8::internal::PendingCompilationErrorHandler::FormatErrorMessageForTest(), and v8::internal::PendingCompilationErrorHandler::ThrowPendingError().
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::internal::PendingCompilationErrorHandler::MessageDetails::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (MessageDetails)
Prepare()
template<typename IsolateT >
void v8::internal::PendingCompilationErrorHandler::MessageDetails::Prepare (IsolateT * isolate)
Definition at line 35 of file pending-compilation-error-handler.cc.
                       {
  for (int i = 0; i < kMaxArgumentCount; i++) {
    switch (args_[i].type) {
      case kAstRawString:
        SetString(i, args_[i].ast_string->string(), isolate);
        break;
      case kNone:
      case kConstCharString:
        // We can delay allocation until ArgString(isolate).
        break;
      case kMainThreadHandle:
        // The message details might already be prepared, so skip them if this
        // is the case.
        break;
    }
  }
}
References v8::internal::kNone, and v8::internal::tracing::type.
Referenced by v8::internal::PendingCompilationErrorHandler::FormatErrorMessageForTest(), and v8::internal::PendingCompilationErrorHandler::PrepareErrors().
SetString() [1/2]
void v8::internal::PendingCompilationErrorHandler::MessageDetails::SetString (int index, Handle< String > string, Isolate * isolate) [private]
Definition at line 20 of file pending-compilation-error-handler.cc.
                                                        {
  DCHECK_NE(args_[index].type, kMainThreadHandle);
  args_[index].type = kMainThreadHandle;
  args_[index].js_string = string;
}
References args_, DCHECK_NE, v8::internal::index, v8::internal::PendingCompilationErrorHandler::MessageDetails::MessageArgument::js_string, kMainThreadHandle, v8::internal::string, v8::internal::PendingCompilationErrorHandler::MessageDetails::MessageArgument::type, and v8::internal::tracing::type.
SetString() [2/2]
void v8::internal::PendingCompilationErrorHandler::MessageDetails::SetString (int index, Handle< String > string, LocalIsolate * isolate) [private]
Definition at line 27 of file pending-compilation-error-handler.cc.
                                                             {
  DCHECK_NE(args_[index].type, kMainThreadHandle);
  args_[index].type = kMainThreadHandle;
  args_[index].js_string = isolate->heap()->NewPersistentHandle(string);
}
References DCHECK_NE, v8::internal::LocalIsolate::heap(), v8::internal::index, v8::internal::LocalHeap::NewPersistentHandle(), and v8::internal::tracing::type.
start_pos()
int v8::internal::PendingCompilationErrorHandler::MessageDetails::start_pos () const [inline]
Definition at line 150 of file pending-compilation-error-handler.h.
{ return start_position_; }
References start_position_.
Referenced by v8::internal::PendingCompilationErrorHandler::ReportMessageAt().
Member Data Documentation
args_
MessageArgument v8::internal::PendingCompilationErrorHandler::MessageDetails::args_[kMaxArgumentCount] [private]
Definition at line 183 of file pending-compilation-error-handler.h.
Referenced by ArgCount(), and SetString().
end_position_
int v8::internal::PendingCompilationErrorHandler::MessageDetails::end_position_ [private]
Definition at line 164 of file pending-compilation-error-handler.h.
Referenced by end_pos().
kMaxArgumentCount
constexpr int v8::internal::PendingCompilationErrorHandler::MessageDetails::kMaxArgumentCount = 3 [static], [constexpr]
Definition at line 91 of file pending-compilation-error-handler.h.
Referenced by ArgCount(), v8::internal::PendingCompilationErrorHandler::FormatErrorMessageForTest(), and v8::internal::PendingCompilationErrorHandler::ThrowPendingError().
message_
MessageTemplate v8::internal::PendingCompilationErrorHandler::MessageDetails::message_ [private]
Definition at line 166 of file pending-compilation-error-handler.h.
Referenced by message().
start_position_
int v8::internal::PendingCompilationErrorHandler::MessageDetails::start_position_ [private]
Definition at line 163 of file pending-compilation-error-handler.h.
Referenced by start_pos().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/pending-compilation-error-handler.h
/mnt/V8SourceCode/src/parsing/pending-compilation-error-handler.cc