v8::internal::ScopeInfo Class Reference
#include <scope-info.h>
Classes
class LocalNamesRange
Public Types
enum Fields {
kFlags
, kParameterCount
, kContextLocalCount
, kPositionInfoStart
,
kPositionInfoEnd
, kVariablePartIndex
 }
Public Member Functions
ScopeType scope_type () const
LanguageMode language_mode () const
bool is_declaration_scope () const
bool SloppyEvalCanExtendVars () const
int ContextLength () const
int ContextHeaderLength () const
bool HasContextExtensionSlot () const
bool SomeContextHasExtension () const
void mark_some_context_has_extension ()
bool HasReceiver () const
bool HasAllocatedReceiver () const
bool ClassScopeHasPrivateBrand () const
bool HasSavedClassVariable () const
bool HasNewTarget () const
V8_EXPORT_PRIVATE bool HasFunctionName () const
bool HasContextAllocatedFunctionName () const
V8_EXPORT_PRIVATE bool HasSharedFunctionName () const
V8_EXPORT_PRIVATE bool HasInferredFunctionName () const
void SetFunctionName (Tagged< UnionOf< Smi, String >> name)
void SetInferredFunctionName (Tagged< String > name)
bool HasPositionInfo () const
bool IsWrappedFunctionScope () const
bool HasContext () const
bool IsAsmModule () const
bool HasSimpleParameters () const
bool HasContextCells () const
V8_EXPORT_PRIVATE Tagged< UnionOf< Smi, String > > FunctionName () const
Tagged< String > FunctionDebugName () const
V8_EXPORT_PRIVATE Tagged< Object > InferredFunctionName () const
int StartPosition () const
int EndPosition () const
void SetPositionInfo (int start, int end)
int UniqueIdInScript () const
Tagged< SourceTextModuleInfo > ModuleDescriptorInfo () const
bool HasInlinedLocalNames () const
Tagged< String > ContextInlinedLocalName (int var) const
Tagged< String > ContextInlinedLocalName (PtrComprCageBase cage_base, int var) const
VariableMode ContextLocalMode (int var) const
IsStaticFlag ContextLocalIsStaticFlag (int var) const
InitializationFlag ContextLocalInitFlag (int var) const
bool ContextLocalIsParameter (int var) const
uint32_t ContextLocalParameterNumber (int var) const
MaybeAssignedFlag ContextLocalMaybeAssignedFlag (int var) const
int ContextSlotIndex (Tagged< String > name)
int ContextSlotIndex (Tagged< String > name, VariableLookupResult *lookup_result)
int ModuleIndex (Tagged< String > name, VariableMode *mode, InitializationFlag *init_flag, MaybeAssignedFlag *maybe_assigned_flag)
int ModuleVariableCount () const
int FunctionContextSlotIndex (Tagged< String > name) const
int ReceiverContextSlotIndex () const
int ParametersStartIndex () const
std::pair< Tagged< String >, int > SavedClassVariable () const
FunctionKind function_kind () const
bool HasOuterScopeInfo () const
bool IsDebugEvaluateScope () const
void SetIsDebugEvaluateScope ()
Tagged< ScopeInfo > OuterScopeInfo () const
bool is_script_scope () const
bool PrivateNameLookupSkipsOuterClass () const
bool IsReplModeScope () const
bool Equals (Tagged< ScopeInfo > other, bool is_live_edit_compare=false, int *out_last_checked_field=nullptr) const
uint32_t Flags () const
int ParameterCount () const
int ContextLocalCount () const
Tagged< DependentCode > dependent_code () const
bool IsEmpty () const
ObjectSlot data_start ()
V8_EXPORT_PRIVATE uint32_t Hash ()
Static Public Member Functions
static LocalNamesRange< DirectHandle< ScopeInfo > > IterateLocalNames (DirectHandle< ScopeInfo > scope_info)
static LocalNamesRange< Tagged< ScopeInfo > > IterateLocalNames (Tagged< ScopeInfo > scope_info, const DisallowGarbageCollection &no_gc)
static bool VariableIsSynthetic (Tagged< String > name)
template<typename IsolateT >
static Handle< ScopeInfo > Create (IsolateT *isolate, Zone *zone, Scope *scope, MaybeDirectHandle< ScopeInfo > outer_scope)
static V8_EXPORT_PRIVATE DirectHandle< ScopeInfo > CreateForWithScope (Isolate *isolate, MaybeDirectHandle< ScopeInfo > outer_scope)
static V8_EXPORT_PRIVATE DirectHandle< ScopeInfo > CreateForEmptyFunction (Isolate *isolate)
static DirectHandle< ScopeInfo > CreateForNativeContext (Isolate *isolate)
static DirectHandle< ScopeInfo > CreateForShadowRealmNativeContext (Isolate *isolate)
static DirectHandle< ScopeInfo > CreateGlobalThisBinding (Isolate *isolate)
static V8_EXPORT_PRIVATE Tagged< ScopeInfo > Empty (Isolate *isolate)
static constexpr int SizeFor (int length)
Private Types
enum class BootstrappingType { kScript
, kFunction
, kNative
, kShadowRealm
 }
Private Member Functions
int InlinedLocalNamesLookup (Tagged< String > name)
int ContextLocalNamesIndex () const
int ContextLocalInfosIndex () const
int SavedClassVariableInfoIndex () const
int FunctionVariableInfoIndex () const
int InferredFunctionNameIndex () const
int OuterScopeInfoIndex () const
int ModuleInfoIndex () const
int ModuleVariableCountIndex () const
int ModuleVariablesIndex () const
int DependentCodeIndex () const
V8_EXPORT_PRIVATE Tagged< Object > get (int index) const
Tagged< Object > get (PtrComprCageBase cage_base, int index) const
void set (int index, Tagged< Smi > value)
void set (int index, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void CopyElements (Isolate *isolate, int dst_index, Tagged< ScopeInfo > src, int src_index, int len, WriteBarrierMode mode)
ObjectSlot RawFieldOfElementAt (int index)
V8_EXPORT_PRIVATE int length () const
int Lookup (Handle< String > name, int start, int end, VariableMode *mode, VariableLocation *location, InitializationFlag *init_flag, MaybeAssignedFlag *maybe_assigned_flag)
void ModuleVariable (int i, Tagged< String > *name, int *index, VariableMode *mode=nullptr, InitializationFlag *init_flag=nullptr, MaybeAssignedFlag *maybe_assigned_flag=nullptr)
Static Private Member Functions
static constexpr int OffsetOfElementAt (int index)
static constexpr int ConvertOffsetToIndex (int offset)
static DirectHandle< ScopeInfo > CreateForBootstrapping (Isolate *isolate, BootstrappingType type)
Static Private Attributes
static const int kFunctionNameEntries
static const int kModuleVariableEntryLength
Friends
class ScopeIterator
std::ostream & operator<< (std::ostream &os, VariableAllocationInfo var)
Detailed Description
Definition at line 50 of file scope-info.h.
Member Enumeration Documentation
BootstrappingType
enum v8::internal::ScopeInfo::BootstrappingType [strong], [private]
Enumerator
kScript
kFunction
kNative
kShadowRealm
Definition at line 353 of file scope-info.h.
{ kScript, kFunction, kNative, kShadowRealm };
Fields
enum v8::internal::ScopeInfo::Fields
Enumerator
kFlags
kParameterCount
kContextLocalCount
kPositionInfoStart
kPositionInfoEnd
kVariablePartIndex
Definition at line 284 of file scope-info.h.
              {
    kFlags,
    kParameterCount,
    kContextLocalCount,
    kPositionInfoStart,
    kPositionInfoEnd,
    kVariablePartIndex
  };
Member Function Documentation
ClassScopeHasPrivateBrand()
bool v8::internal::ScopeInfo::ClassScopeHasPrivateBrand () const
Definition at line 803 of file scope-info.cc.
                                                {
  return ClassScopeHasPrivateBrandBit::decode(Flags());
}
References Flags().
ContextHeaderLength()
int v8::internal::ScopeInfo::ContextHeaderLength () const
Definition at line 778 of file scope-info.cc.
                                         {
  return HasContextExtensionSlot() ? Context::MIN_CONTEXT_EXTENDED_SLOTS
                                   : Context::MIN_CONTEXT_SLOTS;
}
References HasContextExtensionSlot(), v8::internal::Context::MIN_CONTEXT_EXTENDED_SLOTS, and v8::internal::Context::MIN_CONTEXT_SLOTS.
Referenced by ContextLength(), ContextSlotIndex(), ParametersStartIndex(), and ReceiverContextSlotIndex().
ContextInlinedLocalName() [1/2]
Tagged< String > v8::internal::ScopeInfo::ContextInlinedLocalName (int var) const
Definition at line 926 of file scope-info.cc.
                                                               {
  DCHECK(HasInlinedLocalNames());
  return context_local_names(var);
}
References v8::internal::DCHECK(), and HasInlinedLocalNames().
Referenced by InlinedLocalNamesLookup(), and SavedClassVariable().
ContextInlinedLocalName() [2/2]
Tagged< String > v8::internal::ScopeInfo::ContextInlinedLocalName (PtrComprCageBase cage_base, int var) const
Definition at line 931 of file scope-info.cc.
                                                                 {
  DCHECK(HasInlinedLocalNames());
  return context_local_names(cage_base, var);
}
References v8::internal::DCHECK(), and HasInlinedLocalNames().
ContextLength()
int v8::internal::ScopeInfo::ContextLength () const
Definition at line 728 of file scope-info.cc.
                                   {
  if (this->IsEmpty()) return 0;
  int context_locals = ContextLocalCount();
  bool function_name_context_slot = HasContextAllocatedFunctionName();
  bool force_context = ForceContextAllocationBit::decode(Flags());
  bool has_context =
      context_locals > 0 || force_context || function_name_context_slot ||
      scope_type() == WITH_SCOPE || scope_type() == CLASS_SCOPE ||
      (scope_type() == BLOCK_SCOPE && SloppyEvalCanExtendVars() &&
       is_declaration_scope()) ||
      (scope_type() == FUNCTION_SCOPE && SloppyEvalCanExtendVars()) ||
      (scope_type() == FUNCTION_SCOPE && IsAsmModule()) ||
      scope_type() == MODULE_SCOPE;
  if (!has_context) return 0;
  return ContextHeaderLength() + context_locals +
         (function_name_context_slot ? 1 : 0);
}
References v8::internal::BLOCK_SCOPE, v8::internal::CLASS_SCOPE, ContextHeaderLength(), ContextLocalCount(), Flags(), v8::internal::FUNCTION_SCOPE, HasContextAllocatedFunctionName(), is_declaration_scope(), IsAsmModule(), IsEmpty(), v8::internal::MODULE_SCOPE, scope_type(), SloppyEvalCanExtendVars(), and v8::internal::WITH_SCOPE.
Referenced by ContextSlotIndex(), and HasContext().
ContextLocalCount()
int v8::internal::ScopeInfo::ContextLocalCount () const [inline]
Definition at line 40 of file scope-info-inl.h.
{ return context_local_count(); }
Referenced by ContextLength(), HasInlinedLocalNames(), and SavedClassVariable().
ContextLocalInfosIndex()
int v8::internal::ScopeInfo::ContextLocalInfosIndex () const [private]
Definition at line 1107 of file scope-info.cc.
                                            {
  return ConvertOffsetToIndex(ContextLocalInfosOffset());
}
References ConvertOffsetToIndex().
ContextLocalInitFlag()
InitializationFlag v8::internal::ScopeInfo::ContextLocalInitFlag (int var) const
Definition at line 947 of file scope-info.cc.
                                                                {
  int value = context_local_infos(var);
  return InitFlagBit::decode(value);
}
References v8::internal::value.
Referenced by ContextSlotIndex().
ContextLocalIsParameter()
bool v8::internal::ScopeInfo::ContextLocalIsParameter (int var) const
Definition at line 952 of file scope-info.cc.
                                                     {
  int value = context_local_infos(var);
  return ParameterNumberBits::decode(value) != ParameterNumberBits::kMax;
}
References v8::internal::value.
Referenced by ContextLocalParameterNumber().
ContextLocalIsStaticFlag()
IsStaticFlag v8::internal::ScopeInfo::ContextLocalIsStaticFlag (int var) const
Definition at line 942 of file scope-info.cc.
                                                              {
  int value = context_local_infos(var);
  return IsStaticFlagBit::decode(value);
}
References v8::internal::value.
Referenced by ContextSlotIndex().
ContextLocalMaybeAssignedFlag()
MaybeAssignedFlag v8::internal::ScopeInfo::ContextLocalMaybeAssignedFlag (int var) const
Definition at line 963 of file scope-info.cc.
                                                                        {
  int value = context_local_infos(var);
  return MaybeAssignedFlagBit::decode(value);
}
References v8::internal::value.
Referenced by ContextSlotIndex().
ContextLocalMode()
VariableMode v8::internal::ScopeInfo::ContextLocalMode (int var) const
Definition at line 937 of file scope-info.cc.
                                                      {
  int value = context_local_infos(var);
  return VariableModeBits::decode(value);
}
References v8::internal::value.
Referenced by ContextSlotIndex().
ContextLocalNamesIndex()
int v8::internal::ScopeInfo::ContextLocalNamesIndex () const [private]
Definition at line 1103 of file scope-info.cc.
                                            {
  return ConvertOffsetToIndex(ContextLocalNamesOffset());
}
References ConvertOffsetToIndex().
ContextLocalParameterNumber()
uint32_t v8::internal::ScopeInfo::ContextLocalParameterNumber (int var) const
Definition at line 957 of file scope-info.cc.
                                                             {
  DCHECK(ContextLocalIsParameter(var));
  int value = context_local_infos(var);
  return ParameterNumberBits::decode(value);
}
References ContextLocalIsParameter(), v8::internal::DCHECK(), and v8::internal::value.
ContextSlotIndex() [1/2]
int v8::internal::ScopeInfo::ContextSlotIndex (Tagged< String > name)
Definition at line 1044 of file scope-info.cc.
                                                   {
  VariableLookupResult lookup_result;
  return ContextSlotIndex(name, &lookup_result);
}
References v8::internal::name.
ContextSlotIndex() [2/2]
int v8::internal::ScopeInfo::ContextSlotIndex (Tagged< String > name, VariableLookupResult * lookup_result)
Definition at line 1018 of file scope-info.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  DCHECK(IsInternalizedString(name));
  DCHECK_NOT_NULL(lookup_result);
  if (this->IsEmpty()) return -1;
  int index = HasInlinedLocalNames()
                  ? InlinedLocalNamesLookup(name)
                  : context_local_names_hashtable()->Lookup(name);
  if (index != -1) {
    lookup_result->mode = ContextLocalMode(index);
    lookup_result->is_static_flag = ContextLocalIsStaticFlag(index);
    lookup_result->init_flag = ContextLocalInitFlag(index);
    lookup_result->maybe_assigned_flag = ContextLocalMaybeAssignedFlag(index);
    lookup_result->is_repl_mode = IsReplModeScope();
    int context_slot = ContextHeaderLength() + index;
    DCHECK_LT(context_slot, ContextLength());
    return context_slot;
  }
  return -1;
}
References ContextHeaderLength(), ContextLength(), ContextLocalInitFlag(), ContextLocalIsStaticFlag(), ContextLocalMaybeAssignedFlag(), ContextLocalMode(), v8::internal::DCHECK(), DCHECK_LT, DCHECK_NOT_NULL, HasInlinedLocalNames(), v8::internal::index, v8::internal::VariableLookupResult::init_flag, InlinedLocalNamesLookup(), v8::internal::VariableLookupResult::is_repl_mode, v8::internal::VariableLookupResult::is_static_flag, IsEmpty(), v8::internal::InstanceTypeChecker::IsInternalizedString(), IsReplModeScope(), v8::internal::VariableLookupResult::maybe_assigned_flag, v8::internal::VariableLookupResult::mode, v8::internal::name, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
ConvertOffsetToIndex()
static constexpr int v8::internal::ScopeInfo::ConvertOffsetToIndex (int offset) [inline], [static], [constexpr], [private]
Definition at line 347 of file scope-info.h.
                                                        {
    int index = (offset - HeapObject::kHeaderSize) / kTaggedSize;
    DCHECK_EQ(OffsetOfElementAt(index), offset);
    return index;
  }
References DCHECK_EQ, v8::internal::index, v8::internal::HeapObject::kHeaderSize, v8::internal::kTaggedSize, and OffsetOfElementAt().
Referenced by ContextLocalInfosIndex(), ContextLocalNamesIndex(), DependentCodeIndex(), FunctionVariableInfoIndex(), InferredFunctionNameIndex(), ModuleInfoIndex(), ModuleVariableCountIndex(), ModuleVariablesIndex(), OuterScopeInfoIndex(), and SavedClassVariableInfoIndex().
CopyElements()
void v8::internal::ScopeInfo::CopyElements (Isolate * isolate, int dst_index, Tagged< ScopeInfo > src, int src_index, int len, WriteBarrierMode mode) [private]
Definition at line 673 of file scope-info.cc.
                                                    {
  if (len == 0) return;
  DCHECK_LE(src_index + len, src->length());
  DisallowGarbageCollection no_gc;
  ObjectSlot dst_slot(RawFieldOfElementAt(dst_index));
  ObjectSlot src_slot(src->RawFieldOfElementAt(src_index));
  isolate->heap()->CopyRange(*this, dst_slot, src_slot, len, mode);
}
References v8::internal::Heap::CopyRange(), DCHECK_LE, v8::internal::Isolate::heap(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and RawFieldOfElementAt().
Create()
template<typename IsolateT >
Handle< ScopeInfo > v8::internal::ScopeInfo::Create (IsolateT * isolate, Zone * zone, Scope * scope, MaybeDirectHandle< ScopeInfo > outer_scope) [static]
Definition at line 108 of file scope-info.cc.
                                                                              {
  // Collect variables.
  int context_local_count = 0;
  int module_vars_count = 0;
  // Stack allocated block scope variables are allocated in the parent
  // declaration scope, but are recorded in the block scope's scope info. First
  // slot index indicates at which offset a particular scope starts in the
  // parent declaration scope.
  for (Variable* var : *scope->locals()) {
    switch (var->location()) {
      case VariableLocation::CONTEXT:
      case VariableLocation::REPL_GLOBAL:
        context_local_count++;
        break;
      case VariableLocation::MODULE:
        module_vars_count++;
        break;
      default:
        break;
    }
  }
  // Determine use and location of the "this" binding if it is present.
  VariableAllocationInfo receiver_info;
  if (scope->is_declaration_scope() &&
      scope->AsDeclarationScope()->has_this_declaration()) {
    Variable* var = scope->AsDeclarationScope()->receiver();
    if (!var->is_used()) {
      receiver_info = VariableAllocationInfo::UNUSED;
    } else if (var->IsContextSlot()) {
      receiver_info = VariableAllocationInfo::CONTEXT;
    } else {
      DCHECK(var->IsParameter());
      receiver_info = VariableAllocationInfo::STACK;
    }
  } else {
    receiver_info = VariableAllocationInfo::NONE;
  }
  DCHECK(module_vars_count == 0 || scope->is_module_scope());
  // Make sure we allocate the correct amount.
  DCHECK_EQ(scope->ContextLocalCount(), context_local_count);
  // If the number of locals is small, we inline directly
  // in the scope info object.
  bool has_inlined_local_names =
      context_local_count < kScopeInfoMaxInlinedLocalNamesSize;
  const bool has_new_target =
      scope->is_declaration_scope() &&
      scope->AsDeclarationScope()->new_target_var() != nullptr;
  // TODO(cbruni): Don't always waste a field for the inferred name.
  const bool has_inferred_function_name = scope->is_function_scope();
  // Determine use and location of the function variable if it is present.
  VariableAllocationInfo function_name_info;
  if (scope->is_function_scope()) {
    if (scope->AsDeclarationScope()->function_var() != nullptr) {
      Variable* var = scope->AsDeclarationScope()->function_var();
      if (!var->is_used()) {
        function_name_info = VariableAllocationInfo::UNUSED;
      } else if (var->IsContextSlot()) {
        function_name_info = VariableAllocationInfo::CONTEXT;
      } else {
        DCHECK(var->IsStackLocal());
        function_name_info = VariableAllocationInfo::STACK;
      }
    } else {
      // Always reserve space for the debug name in the scope info.
      function_name_info = VariableAllocationInfo::UNUSED;
    }
  } else if (scope->is_module_scope() || scope->is_script_scope() ||
             scope->is_eval_scope()) {
    // Always reserve space for the debug name in the scope info.
    function_name_info = VariableAllocationInfo::UNUSED;
  } else {
    function_name_info = VariableAllocationInfo::NONE;
  }
  const bool has_brand =
      scope->is_class_scope()
          ? scope->AsClassScope()->brand() != nullptr
          : scope->IsConstructorScope() &&
                scope->AsDeclarationScope()->class_scope_has_private_brand();
  const bool should_save_class_variable =
      scope->is_class_scope()
          ? scope->AsClassScope()->should_save_class_variable()
          : false;
  const bool has_function_name =
      function_name_info != VariableAllocationInfo::NONE;
  const int parameter_count =
      scope->is_declaration_scope()
          ? scope->AsDeclarationScope()->num_parameters()
          : 0;
  const bool has_outer_scope_info = !outer_scope.is_null();
  DirectHandle<SourceTextModuleInfo> module_info;
  if (scope->is_module_scope()) {
    module_info = SourceTextModuleInfo::New(isolate, zone,
                                            scope->AsModuleScope()->module());
  }
  // Make sure the Fields enum agrees with Torque-generated offsets.
  static_assert(OffsetOfElementAt(kFlags) == kFlagsOffset);
  static_assert(OffsetOfElementAt(kParameterCount) == kParameterCountOffset);
  static_assert(OffsetOfElementAt(kContextLocalCount) ==
                kContextLocalCountOffset);
  FunctionKind function_kind = FunctionKind::kNormalFunction;
  bool sloppy_eval_can_extend_vars = false;
  if (scope->is_declaration_scope()) {
    function_kind = scope->AsDeclarationScope()->function_kind();
    sloppy_eval_can_extend_vars =
        scope->AsDeclarationScope()->sloppy_eval_can_extend_vars();
  }
  DCHECK_IMPLIES(sloppy_eval_can_extend_vars, scope->HasContextExtensionSlot());
  const int local_names_container_size =
      has_inlined_local_names ? context_local_count : 1;
  const int has_dependent_code = sloppy_eval_can_extend_vars;
  const int length =
      kVariablePartIndex + local_names_container_size + context_local_count +
      (should_save_class_variable ? 1 : 0) +
      (has_function_name ? kFunctionNameEntries : 0) +
      (has_inferred_function_name ? 1 : 0) + (has_outer_scope_info ? 1 : 0) +
      (scope->is_module_scope()
           ? 2 + kModuleVariableEntryLength * module_vars_count
           : 0) +
      (has_dependent_code ? 1 : 0);
  // Create hash table if local names are not inlined.
  Handle<NameToIndexHashTable> local_names_hashtable;
  if (!has_inlined_local_names) {
    local_names_hashtable = NameToIndexHashTable::New(
        isolate, context_local_count, AllocationType::kOld);
  }
  Handle<ScopeInfo> scope_info_handle =
      isolate->factory()->NewScopeInfo(length);
  int index = kVariablePartIndex;
  {
    DisallowGarbageCollection no_gc;
    Tagged<ScopeInfo> scope_info = *scope_info_handle;
    WriteBarrierMode mode = scope_info->GetWriteBarrierMode(no_gc);
    bool has_simple_parameters = false;
    bool is_asm_module = false;
    if (scope->is_function_scope()) {
      DeclarationScope* function_scope = scope->AsDeclarationScope();
      has_simple_parameters = function_scope->has_simple_parameters();
#if V8_ENABLE_WEBASSEMBLY
      is_asm_module = function_scope->is_asm_module();
#endif // V8_ENABLE_WEBASSEMBLY
    }
    // Encode the flags.
    uint32_t flags =
        ScopeTypeBits::encode(scope->scope_type()) |
        SloppyEvalCanExtendVarsBit::encode(sloppy_eval_can_extend_vars) |
        LanguageModeBit::encode(scope->language_mode()) |
        DeclarationScopeBit::encode(scope->is_declaration_scope()) |
        ReceiverVariableBits::encode(receiver_info) |
        ClassScopeHasPrivateBrandBit::encode(has_brand) |
        HasSavedClassVariableBit::encode(should_save_class_variable) |
        HasNewTargetBit::encode(has_new_target) |
        FunctionVariableBits::encode(function_name_info) |
        HasInferredFunctionNameBit::encode(has_inferred_function_name) |
        IsAsmModuleBit::encode(is_asm_module) |
        HasSimpleParametersBit::encode(has_simple_parameters) |
        FunctionKindBits::encode(function_kind) |
        HasOuterScopeInfoBit::encode(has_outer_scope_info) |
        IsDebugEvaluateScopeBit::encode(false) |
        ForceContextAllocationBit::encode(
            scope->ForceContextForLanguageMode()) |
        PrivateNameLookupSkipsOuterClassBit::encode(
            scope->private_name_lookup_skips_outer_class()) |
        HasContextExtensionSlotBit::encode(scope->HasContextExtensionSlot()) |
        IsHiddenBit::encode(scope->is_hidden()) |
        IsWrappedFunctionBit::encode(scope->is_wrapped_function()) |
        HasContextCellsBit::encode(scope->has_context_cells());
    scope_info->set_flags(flags, kRelaxedStore);
    scope_info->set_parameter_count(parameter_count);
    scope_info->set_context_local_count(context_local_count);
    scope_info->set_position_info_start(scope->start_position());
    scope_info->set_position_info_end(scope->end_position());
    if (scope->is_module_scope()) {
      scope_info->set_module_variable_count(module_vars_count);
      ++index;
    }
    if (!has_inlined_local_names) {
      scope_info->set_context_local_names_hashtable(*local_names_hashtable);
    }
    // Add context locals' names and info, module variables' names and info.
    // Context locals are added using their index.
    int context_local_base = index;
    int context_local_info_base =
        context_local_base + local_names_container_size;
    int module_var_entry = scope_info->ModuleVariablesIndex();
    for (Variable* var : *scope->locals()) {
      switch (var->location()) {
        case VariableLocation::CONTEXT:
        case VariableLocation::REPL_GLOBAL: {
          // Due to duplicate parameters, context locals aren't guaranteed to
          // come in order.
          int local_index = var->index() - scope->ContextHeaderLength();
          DCHECK_LE(0, local_index);
          DCHECK_LT(local_index, context_local_count);
          uint32_t info =
              VariableModeBits::encode(var->mode()) |
              InitFlagBit::encode(var->initialization_flag()) |
              MaybeAssignedFlagBit::encode(var->maybe_assigned()) |
              ParameterNumberBits::encode(ParameterNumberBits::kMax) |
              IsStaticFlagBit::encode(var->is_static_flag());
          if (has_inlined_local_names) {
            scope_info->set(context_local_base + local_index, *var->name(),
                            mode);
          } else {
            Handle<NameToIndexHashTable> new_table = NameToIndexHashTable::Add(
                isolate, local_names_hashtable, var->name(), local_index);
            DCHECK_EQ(*new_table, *local_names_hashtable);
            USE(new_table);
          }
          scope_info->set(context_local_info_base + local_index,
                          Smi::FromInt(info));
          break;
        }
        case VariableLocation::MODULE: {
          scope_info->set(
              module_var_entry +
                  TorqueGeneratedModuleVariableOffsets::kNameOffset /
                      kTaggedSize,
              *var->name(), mode);
          scope_info->set(
              module_var_entry +
                  TorqueGeneratedModuleVariableOffsets::kIndexOffset /
                      kTaggedSize,
              Smi::FromInt(var->index()));
          uint32_t properties =
              VariableModeBits::encode(var->mode()) |
              InitFlagBit::encode(var->initialization_flag()) |
              MaybeAssignedFlagBit::encode(var->maybe_assigned()) |
              ParameterNumberBits::encode(ParameterNumberBits::kMax) |
              IsStaticFlagBit::encode(var->is_static_flag());
          scope_info->set(
              module_var_entry +
                  TorqueGeneratedModuleVariableOffsets::kPropertiesOffset /
                      kTaggedSize,
              Smi::FromInt(properties));
          module_var_entry += kModuleVariableEntryLength;
          break;
        }
        default:
          break;
      }
    }
    if (scope->is_declaration_scope()) {
      // Mark contexts slots with the parameter number they represent. We walk
      // the list of parameters. That can include duplicate entries if a
      // parameter name is repeated. By walking upwards, we'll automatically
      // mark the context slot with the highest parameter number that uses this
      // variable. That will be the parameter number that is represented by the
      // context slot. All lower parameters will only be available on the stack
      // through the arguments object.
      for (int i = 0; i < parameter_count; i++) {
        Variable* parameter = scope->AsDeclarationScope()->parameter(i);
        if (parameter->location() != VariableLocation::CONTEXT) continue;
        int param_index = parameter->index() - scope->ContextHeaderLength();
        int info_index = context_local_info_base + param_index;
        int info = Smi::ToInt(scope_info->get(info_index));
        info = ParameterNumberBits::update(info, i);
        scope_info->set(info_index, Smi::FromInt(info));
      }
    }
    // Advance past local names and local names info.
    index += local_names_container_size + context_local_count;
    DCHECK_EQ(index, scope_info->SavedClassVariableInfoIndex());
    // If the scope is a class scope and has used static private methods,
    // save context slot index if locals are inlined, otherwise save the name.
    if (should_save_class_variable) {
      Variable* class_variable = scope->AsClassScope()->class_variable();
      DCHECK_EQ(class_variable->location(), VariableLocation::CONTEXT);
      if (has_inlined_local_names) {
        scope_info->set(index++, Smi::FromInt(class_variable->index()));
      } else {
        scope_info->set(index++, *class_variable->name());
      }
    }
    // If present, add the function variable name and its index.
    DCHECK_EQ(index, scope_info->FunctionVariableInfoIndex());
    if (has_function_name) {
      Variable* var = scope->AsDeclarationScope()->function_var();
      int var_index = -1;
      Tagged<Object> name = Smi::zero();
      if (var != nullptr) {
        var_index = var->index();
        name = *var->name();
      }
      scope_info->set(index++, name, mode);
      scope_info->set(index++, Smi::FromInt(var_index));
      DCHECK(function_name_info != VariableAllocationInfo::CONTEXT ||
             var_index == scope_info->ContextLength() - 1);
    }
    DCHECK_EQ(index, scope_info->InferredFunctionNameIndex());
    if (has_inferred_function_name) {
      // The inferred function name is taken from the SFI.
      index++;
    }
    // If present, add the outer scope info.
    DCHECK_EQ(index, scope_info->OuterScopeInfoIndex());
    if (has_outer_scope_info) {
      scope_info->set(index++, *outer_scope.ToHandleChecked(), mode);
    }
    // Module-specific information (only for module scopes).
    if (scope->is_module_scope()) {
      DCHECK_EQ(index, scope_info->ModuleInfoIndex());
      scope_info->set(index++, *module_info);
      DCHECK_EQ(index, scope_info->ModuleVariablesIndex());
      // The variable entries themselves have already been written above.
      index += kModuleVariableEntryLength * module_vars_count;
    }
    DCHECK_EQ(index, scope_info->DependentCodeIndex());
    if (has_dependent_code) {
      ReadOnlyRoots roots(isolate);
      scope_info->set(index++, DependentCode::empty_dependent_code(roots));
    }
  }
  DCHECK_EQ(index, scope_info_handle->length());
  DCHECK_EQ(length, scope_info_handle->length());
  DCHECK_EQ(parameter_count, scope_info_handle->ParameterCount());
  DCHECK_EQ(scope->num_heap_slots(), scope_info_handle->ContextLength());
  return scope_info_handle;
}
References v8::internal::NameToIndexHashTable::Add(), v8::internal::Scope::AsClassScope(), v8::internal::Scope::AsDeclarationScope(), v8::internal::Scope::AsModuleScope(), v8::internal::ClassScope::brand(), v8::internal::DeclarationScope::class_scope_has_private_brand(), v8::internal::ClassScope::class_variable(), v8::internal::CONTEXT, v8::internal::Scope::ContextHeaderLength(), v8::internal::Scope::ContextLocalCount(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LE, DCHECK_LT, v8::internal::DependentCode::empty_dependent_code(), v8::internal::Scope::end_position(), v8::internal::flags, v8::internal::Scope::ForceContextForLanguageMode(), v8::internal::Smi::FromInt(), v8::internal::DeclarationScope::function_kind(), function_kind(), v8::internal::DeclarationScope::function_var(), v8::internal::Scope::has_context_cells(), v8::internal::DeclarationScope::has_simple_parameters(), v8::internal::DeclarationScope::has_this_declaration(), v8::internal::Scope::HasContextExtensionSlot(), v8::internal::Variable::index(), v8::internal::index, v8::internal::Scope::is_class_scope(), v8::internal::Scope::is_declaration_scope(), v8::internal::Scope::is_eval_scope(), v8::internal::Scope::is_function_scope(), v8::internal::Scope::is_hidden(), v8::internal::Scope::is_module_scope(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::Scope::is_script_scope(), v8::internal::Variable::is_used(), v8::internal::Scope::is_wrapped_function(), v8::internal::Scope::IsConstructorScope(), v8::internal::Variable::IsContextSlot(), v8::internal::Variable::IsParameter(), v8::internal::Variable::IsStackLocal(), kContextLocalCount, kFlags, kFunctionNameEntries, kModuleVariableEntryLength, v8::internal::kNormalFunction, v8::internal::kOld, kParameterCount, v8::kRelaxedStore, v8::internal::kScopeInfoMaxInlinedLocalNamesSize, v8::internal::kTaggedSize, kVariablePartIndex, v8::internal::Scope::language_mode(), length(), v8::internal::Scope::locals(), v8::internal::Variable::location(), mode(), v8::internal::ModuleScope::module(), v8::internal::MODULE, v8::internal::Variable::name(), v8::internal::name, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::SourceTextModuleInfo::New(), v8::internal::DeclarationScope::new_target_var(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, nullptr, v8::internal::Scope::num_heap_slots(), v8::internal::DeclarationScope::num_parameters(), OffsetOfElementAt(), v8::internal::DeclarationScope::parameter(), v8::internal::Scope::private_name_lookup_skips_outer_class(), v8::internal::DeclarationScope::receiver(), v8::internal::REPL_GLOBAL, v8::internal::Scope::scope_type(), v8::internal::ClassScope::should_save_class_variable(), v8::internal::DeclarationScope::sloppy_eval_can_extend_vars(), v8::internal::STACK, v8::internal::Scope::start_position(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), v8::internal::Smi::ToInt(), v8::internal::UNUSED, USE, and v8::internal::Smi::zero().
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), and v8::internal::Scope::AllocateScopeInfosRecursively().
CreateForBootstrapping()
DirectHandle< ScopeInfo > v8::internal::ScopeInfo::CreateForBootstrapping (Isolate * isolate, BootstrappingType type) [static], [private]
Definition at line 550 of file scope-info.cc.
                                              {
  const int parameter_count = 0;
  const bool is_empty_function = type == BootstrappingType::kFunction;
  const bool is_native_context = (type == BootstrappingType::kNative) ||
                                 (type == BootstrappingType::kShadowRealm);
  const bool is_script = type == BootstrappingType::kScript;
  const bool is_shadow_realm = type == BootstrappingType::kShadowRealm;
  const int context_local_count =
      is_empty_function || is_native_context ? 0 : 1;
  const bool has_inferred_function_name = is_empty_function;
  // NOTE: Local names are always inlined here, since context_local_count < 2.
  DCHECK_LT(context_local_count, kScopeInfoMaxInlinedLocalNamesSize);
  const int length = kVariablePartIndex + 2 * context_local_count +
                     (is_empty_function ? kFunctionNameEntries : 0) +
                     (has_inferred_function_name ? 1 : 0);
  Factory* factory = isolate->factory();
  DirectHandle<ScopeInfo> scope_info =
      factory->NewScopeInfo(length, AllocationType::kReadOnly);
  DisallowGarbageCollection _nogc;
  // Encode the flags.
  DCHECK_IMPLIES(is_shadow_realm || is_script, !is_empty_function);
  uint32_t flags =
      ScopeTypeBits::encode(
          is_empty_function
              ? FUNCTION_SCOPE
              : (is_shadow_realm ? SHADOW_REALM_SCOPE : SCRIPT_SCOPE)) |
      SloppyEvalCanExtendVarsBit::encode(false) |
      LanguageModeBit::encode(LanguageMode::kSloppy) |
      DeclarationScopeBit::encode(true) |
      ReceiverVariableBits::encode(is_script ? VariableAllocationInfo::CONTEXT
                                             : VariableAllocationInfo::UNUSED) |
      ClassScopeHasPrivateBrandBit::encode(false) |
      HasSavedClassVariableBit::encode(false) | HasNewTargetBit::encode(false) |
      FunctionVariableBits::encode(is_empty_function
                                       ? VariableAllocationInfo::UNUSED
                                       : VariableAllocationInfo::NONE) |
      HasInferredFunctionNameBit::encode(has_inferred_function_name) |
      IsAsmModuleBit::encode(false) | HasSimpleParametersBit::encode(true) |
      FunctionKindBits::encode(FunctionKind::kNormalFunction) |
      HasOuterScopeInfoBit::encode(false) |
      IsDebugEvaluateScopeBit::encode(false) |
      ForceContextAllocationBit::encode(false) |
      PrivateNameLookupSkipsOuterClassBit::encode(false) |
      HasContextExtensionSlotBit::encode(is_native_context) |
      IsHiddenBit::encode(false) | IsWrappedFunctionBit::encode(false) |
      HasContextCellsBit::encode(false);
  Tagged<ScopeInfo> raw_scope_info = *scope_info;
  raw_scope_info->set_flags(flags, kRelaxedStore);
  raw_scope_info->set_parameter_count(parameter_count);
  raw_scope_info->set_context_local_count(context_local_count);
  raw_scope_info->set_position_info_start(0);
  raw_scope_info->set_position_info_end(0);
  int index = kVariablePartIndex;
  // Here we add info for context-allocated "this".
  DCHECK_EQ(index, raw_scope_info->ContextLocalNamesIndex());
  ReadOnlyRoots roots(isolate);
  if (context_local_count) {
    raw_scope_info->set(index++, roots.this_string());
  }
  DCHECK_EQ(index, raw_scope_info->ContextLocalInfosIndex());
  if (context_local_count > 0) {
    const uint32_t value =
        VariableModeBits::encode(VariableMode::kConst) |
        InitFlagBit::encode(kCreatedInitialized) |
        MaybeAssignedFlagBit::encode(kNotAssigned) |
        ParameterNumberBits::encode(ParameterNumberBits::kMax) |
        IsStaticFlagBit::encode(IsStaticFlag::kNotStatic);
    raw_scope_info->set(index++, Smi::FromInt(value));
  }
  DCHECK_EQ(index, raw_scope_info->FunctionVariableInfoIndex());
  if (is_empty_function) {
    raw_scope_info->set(index++, roots.empty_string());
    raw_scope_info->set(index++, Smi::zero());
  }
  DCHECK_EQ(index, raw_scope_info->InferredFunctionNameIndex());
  if (has_inferred_function_name) {
    raw_scope_info->set(index++, roots.empty_string());
  }
  DCHECK_EQ(index, raw_scope_info->OuterScopeInfoIndex());
  DCHECK_EQ(index, raw_scope_info->DependentCodeIndex());
  DCHECK_EQ(index, raw_scope_info->length());
  DCHECK_EQ(length, raw_scope_info->length());
  DCHECK_EQ(raw_scope_info->ParameterCount(), parameter_count);
  if (is_empty_function || is_native_context) {
    DCHECK_EQ(raw_scope_info->ContextLength(), 0);
  } else {
    DCHECK_EQ(raw_scope_info->ContextLength(),
              raw_scope_info->ContextHeaderLength() + 1);
  }
  return scope_info;
}
References v8::internal::CONTEXT, DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::Smi::FromInt(), v8::internal::FUNCTION_SCOPE, v8::internal::index, v8::internal::kConst, v8::internal::kCreatedInitialized, kFunction, kFunctionNameEntries, kNative, v8::internal::kNormalFunction, v8::internal::kNotAssigned, v8::internal::kNotStatic, v8::internal::kReadOnly, v8::kRelaxedStore, v8::internal::kScopeInfoMaxInlinedLocalNamesSize, kScript, kShadowRealm, v8::internal::kSloppy, kVariablePartIndex, length(), v8::internal::FactoryBase< Impl >::NewScopeInfo(), v8::internal::NONE, v8::internal::SCRIPT_SCOPE, v8::internal::SHADOW_REALM_SCOPE, v8::internal::tracing::type, v8::internal::UNUSED, v8::internal::value, and v8::internal::Smi::zero().
Referenced by CreateForEmptyFunction(), CreateForNativeContext(), CreateForShadowRealmNativeContext(), and CreateGlobalThisBinding().
CreateForEmptyFunction()
DirectHandle< ScopeInfo > v8::internal::ScopeInfo::CreateForEmptyFunction (Isolate * isolate) [static]
Definition at line 524 of file scope-info.cc.
                                                                          {
  DirectHandle<ScopeInfo> scope_info =
      CreateForBootstrapping(isolate, BootstrappingType::kFunction);
  if (v8_flags.function_context_cells) {
    // An empty function scope will set the has_context_cells_ flag, since it is
    // set to true for all function scopes with the number of context locals (in
    // this case zero) below the threshold
    // v8_flags.function_context_cells_max_size.
    scope_info->set_flags(
        scope_info->Flags() | HasContextCellsBit::encode(true), kRelaxedStore);
  }
  return scope_info;
}
References CreateForBootstrapping(), kFunction, v8::kRelaxedStore, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
CreateForNativeContext()
DirectHandle< ScopeInfo > v8::internal::ScopeInfo::CreateForNativeContext (Isolate * isolate) [static]
Definition at line 539 of file scope-info.cc.
                                                                          {
  return CreateForBootstrapping(isolate, BootstrappingType::kNative);
}
References CreateForBootstrapping(), and kNative.
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
CreateForShadowRealmNativeContext()
DirectHandle< ScopeInfo > v8::internal::ScopeInfo::CreateForShadowRealmNativeContext (Isolate * isolate) [static]
Definition at line 544 of file scope-info.cc.
                      {
  return CreateForBootstrapping(isolate, BootstrappingType::kShadowRealm);
}
References CreateForBootstrapping(), and kShadowRealm.
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
CreateForWithScope()
static V8_EXPORT_PRIVATE DirectHandle<ScopeInfo> v8::internal::ScopeInfo::CreateForWithScope (Isolate * isolate, MaybeDirectHandle< ScopeInfo > outer_scope) [static]
Referenced by v8::ScriptCompiler::CompileFunction(), v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), v8::internal::DebugEvaluate::Local(), and v8::internal::DebugEvaluate::WithTopmostArguments().
CreateGlobalThisBinding()
DirectHandle< ScopeInfo > v8::internal::ScopeInfo::CreateGlobalThisBinding (Isolate * isolate) [static]
Definition at line 519 of file scope-info.cc.
                                                                           {
  return CreateForBootstrapping(isolate, BootstrappingType::kScript);
}
References CreateForBootstrapping(), and kScript.
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
data_start()
ObjectSlot v8::internal::ScopeInfo::data_start () [inline]
Definition at line 46 of file scope-info-inl.h.
{ return RawField(OffsetOfElementAt(0)); }
References OffsetOfElementAt().
dependent_code()
Tagged< DependentCode > v8::internal::ScopeInfo::dependent_code () const [inline]
Definition at line 42 of file scope-info-inl.h.
                                                      {
  return Cast<DependentCode>(TorqueGeneratedScopeInfo::dependent_code());
}
DependentCodeIndex()
int v8::internal::ScopeInfo::DependentCodeIndex () const [private]
Definition at line 1163 of file scope-info.cc.
                                        {
  return ConvertOffsetToIndex(DependentCodeOffset());
}
References ConvertOffsetToIndex().
Empty()
Tagged< ScopeInfo > v8::internal::ScopeInfo::Empty (Isolate * isolate) [static]
Definition at line 696 of file scope-info.cc.
                                                   {
  return ReadOnlyRoots(isolate).empty_scope_info();
}
EndPosition()
int v8::internal::ScopeInfo::EndPosition () const
Definition at line 904 of file scope-info.cc.
                                 {
  DCHECK(HasPositionInfo());
  return position_info_end();
}
References v8::internal::DCHECK(), and HasPositionInfo().
Referenced by Hash().
Equals()
bool v8::internal::ScopeInfo::Equals (Tagged< ScopeInfo > other, bool is_live_edit_compare = false, int * out_last_checked_field = nullptr) const
Definition at line 47 of file scope-info.cc.
                                                          {
  if (length() != other->length()) return false;
  if (Flags() != other->Flags()) return false;
  for (int index = 0; index < length(); ++index) {
    if (out_last_checked_field) *out_last_checked_field = index;
    if (index == kFlags) continue;
    if (is_live_edit_compare && index >= kPositionInfoStart &&
        index <= kPositionInfoEnd) {
      continue;
    }
    Tagged<Object> entry = get(index);
    Tagged<Object> other_entry = other->get(index);
    if (IsSmi(entry)) {
      if (entry != other_entry) return false;
    } else {
      if (Cast<HeapObject>(entry)->map()->instance_type() !=
          Cast<HeapObject>(other_entry)->map()->instance_type()) {
        return false;
      }
      if (IsString(entry)) {
        if (!Cast<String>(entry)->Equals(Cast<String>(other_entry))) {
          return false;
        }
      } else if (IsScopeInfo(entry)) {
        if (!is_live_edit_compare && !Cast<ScopeInfo>(entry)->Equals(
                                         Cast<ScopeInfo>(other_entry), false)) {
          return false;
        }
      } else if (IsSourceTextModuleInfo(entry)) {
        if (!is_live_edit_compare &&
            !Cast<SourceTextModuleInfo>(entry)->Equals(
                Cast<SourceTextModuleInfo>(other_entry))) {
          return false;
        }
      } else if (IsOddball(entry)) {
        if (Cast<Oddball>(entry)->kind() !=
            Cast<Oddball>(other_entry)->kind()) {
          return false;
        }
      } else if (IsDependentCode(entry)) {
        DCHECK(IsDependentCode(other_entry));
        // Ignore the dependent code field since all the code have to be
        // deoptimized anyway in case of a live-edit.
      } else if (IsNameToIndexHashTable(entry)) {
        if (!NameToIndexHashTableEquals(
                Cast<NameToIndexHashTable>(entry),
                Cast<NameToIndexHashTable>(other_entry))) {
          return false;
        }
      } else {
        UNREACHABLE();
      }
    }
  }
  return true;
}
References v8::internal::DCHECK(), Flags(), get(), v8::internal::index, v8::internal::IsSmi(), kFlags, kPositionInfoEnd, kPositionInfoStart, length(), v8::internal::anonymous_namespace{scope-info.cc}::NameToIndexHashTableEquals(), and v8::internal::UNREACHABLE().
Flags()
uint32_t v8::internal::ScopeInfo::Flags () const [inline]
Definition at line 38 of file scope-info-inl.h.
{ return flags(kRelaxedLoad); }
References v8::internal::flags, and v8::kRelaxedLoad.
Referenced by ClassScopeHasPrivateBrand(), ContextLength(), Equals(), function_kind(), HasAllocatedReceiver(), HasContextAllocatedFunctionName(), HasContextCells(), HasContextExtensionSlot(), HasFunctionName(), HasInferredFunctionName(), HasNewTarget(), HasOuterScopeInfo(), HasReceiver(), HasSavedClassVariable(), HasSimpleParameters(), is_declaration_scope(), IsDebugEvaluateScope(), IsEmpty(), IsWrappedFunctionScope(), language_mode(), mark_some_context_has_extension(), ParametersStartIndex(), PrivateNameLookupSkipsOuterClass(), ReceiverContextSlotIndex(), SavedClassVariable(), scope_type(), SetIsDebugEvaluateScope(), SloppyEvalCanExtendVars(), and SomeContextHasExtension().
function_kind()
FunctionKind v8::internal::ScopeInfo::function_kind () const
Definition at line 1099 of file scope-info.cc.
                                            {
  return FunctionKindBits::decode(Flags());
}
References Flags().
Referenced by Create(), and UniqueIdInScript().
FunctionContextSlotIndex()
int v8::internal::ScopeInfo::FunctionContextSlotIndex (Tagged< String > name) const
Definition at line 1088 of file scope-info.cc.
                                                                 {
  DCHECK(IsInternalizedString(name));
  if (HasContextAllocatedFunctionName()) {
    DCHECK_IMPLIES(HasFunctionName(), IsInternalizedString(FunctionName()));
    if (FunctionName() == name) {
      return function_variable_info_context_or_stack_slot_index();
    }
  }
  return -1;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, FunctionName(), HasContextAllocatedFunctionName(), HasFunctionName(), v8::internal::InstanceTypeChecker::IsInternalizedString(), and v8::internal::name.
FunctionDebugName()
Tagged< String > v8::internal::ScopeInfo::FunctionDebugName () const
Definition at line 886 of file scope-info.cc.
                                                  {
  if (!HasFunctionName()) return GetReadOnlyRoots().empty_string();
  Tagged<Object> name = FunctionName();
  if (IsString(name) && Cast<String>(name)->length() > 0) {
    return Cast<String>(name);
  }
  if (HasInferredFunctionName()) {
    name = InferredFunctionName();
    if (IsString(name)) return Cast<String>(name);
  }
  return GetReadOnlyRoots().empty_string();
}
References FunctionName(), v8::internal::GetReadOnlyRoots(), HasFunctionName(), HasInferredFunctionName(), InferredFunctionName(), length(), and v8::internal::name.
FunctionName()
Tagged< UnionOf< Smi, String > > v8::internal::ScopeInfo::FunctionName () const
Definition at line 876 of file scope-info.cc.
                                                           {
  DCHECK(HasFunctionName());
  return function_variable_info_name();
}
References v8::internal::DCHECK(), and HasFunctionName().
Referenced by FunctionContextSlotIndex(), FunctionDebugName(), and HasSharedFunctionName().
FunctionVariableInfoIndex()
int v8::internal::ScopeInfo::FunctionVariableInfoIndex () const [private]
Definition at line 1115 of file scope-info.cc.
                                               {
  return ConvertOffsetToIndex(FunctionVariableInfoOffset());
}
References ConvertOffsetToIndex().
get() [1/2]
Tagged< Object > v8::internal::ScopeInfo::get (int index) const [private]
Definition at line 648 of file scope-info.cc.
                                             {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return get(cage_base, index);
}
References v8::internal::GetPtrComprCageBase(), and v8::internal::index.
Referenced by Equals().
get() [2/2]
Tagged< Object > v8::internal::ScopeInfo::get (PtrComprCageBase cage_base, int index) const [private]
Definition at line 653 of file scope-info.cc.
                                                                         {
  DCHECK_LT(static_cast<unsigned>(index), static_cast<unsigned>(length()));
  return TaggedField<Object>::Relaxed_Load(cage_base, *this,
                                           OffsetOfElementAt(index));
}
References DCHECK_LT, v8::internal::index, length(), OffsetOfElementAt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
HasAllocatedReceiver()
bool v8::internal::ScopeInfo::HasAllocatedReceiver () const
Definition at line 787 of file scope-info.cc.
                                           {
  // The receiver is allocated and needs to be deserialized during reparsing
  // when:
  // 1. During the initial parsing, it's been observed that the inner
  // scopes are accessing this, so the receiver should be allocated
  // again. This can be inferred when the receiver variable is
  // recorded as being allocated on the stack or context.
  // 2. The scope is created as a debug evaluate scope, so this is not
  // an actual reparse, we are not sure if the inner scope will access
  // this, but the receiver should be allocated just in case.
  VariableAllocationInfo allocation = ReceiverVariableBits::decode(Flags());
  return allocation == VariableAllocationInfo::STACK ||
         allocation == VariableAllocationInfo::CONTEXT ||
         IsDebugEvaluateScope();
}
References v8::internal::CONTEXT, Flags(), IsDebugEvaluateScope(), and v8::internal::STACK.
HasContext()
bool v8::internal::ScopeInfo::HasContext () const
Definition at line 874 of file scope-info.cc.
{ return ContextLength() > 0; }
References ContextLength().
HasContextAllocatedFunctionName()
bool v8::internal::ScopeInfo::HasContextAllocatedFunctionName () const
Definition at line 819 of file scope-info.cc.
                                                      {
  return VariableAllocationInfo::CONTEXT ==
         FunctionVariableBits::decode(Flags());
}
References v8::internal::CONTEXT, and Flags().
Referenced by ContextLength(), FunctionContextSlotIndex(), and SetFunctionName().
HasContextCells()
bool v8::internal::ScopeInfo::HasContextCells () const [inline]
Definition at line 34 of file scope-info-inl.h.
                                      {
  return HasContextCellsBit::decode(Flags());
}
References Flags().
HasContextExtensionSlot()
bool v8::internal::ScopeInfo::HasContextExtensionSlot () const
Definition at line 766 of file scope-info.cc.
                                              {
  return HasContextExtensionSlotBit::decode(Flags());
}
References Flags().
Referenced by ContextHeaderLength().
HasFunctionName()
bool v8::internal::ScopeInfo::HasFunctionName () const
Definition at line 815 of file scope-info.cc.
                                      {
  return VariableAllocationInfo::NONE != FunctionVariableBits::decode(Flags());
}
References Flags(), and v8::internal::NONE.
Referenced by FunctionContextSlotIndex(), FunctionDebugName(), FunctionName(), and SetFunctionName().
Hash()
uint32_t v8::internal::ScopeInfo::Hash ()
Definition at line 1167 of file scope-info.cc.
                         {
  // Hash ScopeInfo based on its start and end position.
  // Note: Ideally we'd also have the script ID. But since we only use the
  // hash in a debug-evaluate cache, we don't worry too much about collisions.
  if (HasPositionInfo()) {
    return static_cast<uint32_t>(base::hash_combine(
        flags(kRelaxedLoad), StartPosition(), EndPosition()));
  }
  return static_cast<uint32_t>(
      base::hash_combine(flags(kRelaxedLoad), context_local_count()));
}
References EndPosition(), v8::internal::flags, v8::base::hash_combine(), HasPositionInfo(), v8::kRelaxedLoad, and StartPosition().
HasInferredFunctionName()
bool v8::internal::ScopeInfo::HasInferredFunctionName () const
Definition at line 824 of file scope-info.cc.
                                              {
  return HasInferredFunctionNameBit::decode(Flags());
}
References Flags().
Referenced by FunctionDebugName(), InferredFunctionName(), and SetInferredFunctionName().
HasInlinedLocalNames()
bool v8::internal::ScopeInfo::HasInlinedLocalNames () const [inline]
Definition at line 48 of file scope-info-inl.h.
                                           {
  return ContextLocalCount() < kScopeInfoMaxInlinedLocalNamesSize;
}
References ContextLocalCount(), and v8::internal::kScopeInfoMaxInlinedLocalNamesSize.
Referenced by ContextInlinedLocalName(), ContextSlotIndex(), and SavedClassVariable().
HasNewTarget()
bool v8::internal::ScopeInfo::HasNewTarget () const
Definition at line 811 of file scope-info.cc.
                                   {
  return HasNewTargetBit::decode(Flags());
}
References Flags().
HasOuterScopeInfo()
bool v8::internal::ScopeInfo::HasOuterScopeInfo () const
Definition at line 846 of file scope-info.cc.
                                        {
  return HasOuterScopeInfoBit::decode(Flags());
}
References Flags().
Referenced by OuterScopeInfo().
HasPositionInfo()
bool v8::internal::ScopeInfo::HasPositionInfo () const
Definition at line 828 of file scope-info.cc.
{ return !this->IsEmpty(); }
References IsEmpty().
Referenced by EndPosition(), Hash(), SetPositionInfo(), and StartPosition().
HasReceiver()
bool v8::internal::ScopeInfo::HasReceiver () const
Definition at line 783 of file scope-info.cc.
                                  {
  return VariableAllocationInfo::NONE != ReceiverVariableBits::decode(Flags());
}
References Flags(), and v8::internal::NONE.
HasSavedClassVariable()
bool v8::internal::ScopeInfo::HasSavedClassVariable () const
Definition at line 807 of file scope-info.cc.
                                            {
  return HasSavedClassVariableBit::decode(Flags());
}
References Flags().
HasSharedFunctionName()
bool v8::internal::ScopeInfo::HasSharedFunctionName () const
Definition at line 830 of file scope-info.cc.
                                            {
  return FunctionName() != SharedFunctionInfo::kNoSharedNameSentinel;
}
References FunctionName(), and v8::internal::SharedFunctionInfo::kNoSharedNameSentinel.
HasSimpleParameters()
bool v8::internal::ScopeInfo::HasSimpleParameters () const [inline]
Definition at line 30 of file scope-info-inl.h.
                                          {
  return HasSimpleParametersBit::decode(Flags());
}
References Flags().
InferredFunctionName()
Tagged< Object > v8::internal::ScopeInfo::InferredFunctionName () const
Definition at line 881 of file scope-info.cc.
                                                     {
  DCHECK(HasInferredFunctionName());
  return inferred_function_name();
}
References v8::internal::DCHECK(), and HasInferredFunctionName().
Referenced by FunctionDebugName().
InferredFunctionNameIndex()
int v8::internal::ScopeInfo::InferredFunctionNameIndex () const [private]
Definition at line 1119 of file scope-info.cc.
                                               {
  return ConvertOffsetToIndex(InferredFunctionNameOffset());
}
References ConvertOffsetToIndex().
InlinedLocalNamesLookup()
int v8::internal::ScopeInfo::InlinedLocalNamesLookup (Tagged< String > name) [private]
Definition at line 1006 of file scope-info.cc.
                                                          {
  DisallowGarbageCollection no_gc;
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  int local_count = context_local_count();
  for (int i = 0; i < local_count; ++i) {
    if (name == ContextInlinedLocalName(cage_base, i)) {
      return i;
    }
  }
  return -1;
}
References ContextInlinedLocalName(), v8::internal::GetPtrComprCageBase(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::name, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by ContextSlotIndex().
is_declaration_scope()
bool v8::internal::ScopeInfo::is_declaration_scope () const
Definition at line 724 of file scope-info.cc.
                                           {
  return DeclarationScopeBit::decode(Flags());
}
References Flags().
Referenced by ContextLength(), and SloppyEvalCanExtendVars().
is_script_scope()
bool v8::internal::ScopeInfo::is_script_scope () const
Definition at line 707 of file scope-info.cc.
                                      {
  return !this->IsEmpty() &&
         (scope_type() == SCRIPT_SCOPE || scope_type() == REPL_MODE_SCOPE);
}
References IsEmpty(), v8::internal::REPL_MODE_SCOPE, scope_type(), and v8::internal::SCRIPT_SCOPE.
Referenced by UniqueIdInScript().
IsAsmModule()
bool v8::internal::ScopeInfo::IsAsmModule () const [inline]
Definition at line 28 of file scope-info-inl.h.
{ return IsAsmModuleBit::decode(Flags()); }
References v8::internal::Flags().
Referenced by ContextLength().
IsDebugEvaluateScope()
bool v8::internal::ScopeInfo::IsDebugEvaluateScope () const
Definition at line 850 of file scope-info.cc.
                                           {
  return IsDebugEvaluateScopeBit::decode(Flags());
}
References Flags().
Referenced by HasAllocatedReceiver().
IsEmpty()
bool v8::internal::ScopeInfo::IsEmpty () const
Definition at line 700 of file scope-info.cc.
{ return IsEmptyBit::decode(Flags()); }
References Flags().
Referenced by ContextLength(), ContextSlotIndex(), HasPositionInfo(), is_script_scope(), scope_type(), and SetIsDebugEvaluateScope().
IsReplModeScope()
bool v8::internal::ScopeInfo::IsReplModeScope () const
Definition at line 864 of file scope-info.cc.
                                      {
  return scope_type() == REPL_MODE_SCOPE;
}
References v8::internal::REPL_MODE_SCOPE, and scope_type().
Referenced by ContextSlotIndex().
IsWrappedFunctionScope()
bool v8::internal::ScopeInfo::IsWrappedFunctionScope () const
Definition at line 868 of file scope-info.cc.
                                             {
  DCHECK_IMPLIES(IsWrappedFunctionBit::decode(Flags()),
                 scope_type() == FUNCTION_SCOPE);
  return IsWrappedFunctionBit::decode(Flags());
}
References DCHECK_IMPLIES, Flags(), v8::internal::FUNCTION_SCOPE, and scope_type().
Referenced by UniqueIdInScript().
IterateLocalNames() [1/2]
ScopeInfo::LocalNamesRange< DirectHandle< ScopeInfo > > v8::internal::ScopeInfo::IterateLocalNames (DirectHandle< ScopeInfo > scope_info) [inline], [static]
Definition at line 146 of file scope-info-inl.h.
                                                               {
  return LocalNamesRange<DirectHandle<ScopeInfo>>(scope_info);
}
Referenced by v8::internal::anonymous_namespace{contexts.cc}::AddLocalNamesFromContext(), v8::internal::V8HeapExplorer::ExtractContextReferences(), v8::debug::anonymous_namespace{debug-interface.cc}::ForEachContextLocal(), v8::debug::GlobalLexicalScopeNames(), v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), v8::internal::JavaScriptFrame::Print(), v8::internal::ScopeIterator::VisitContextLocals(), and v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitObject().
IterateLocalNames() [2/2]
ScopeInfo::LocalNamesRange< Tagged< ScopeInfo > > v8::internal::ScopeInfo::IterateLocalNames (Tagged< ScopeInfo > scope_info, const DisallowGarbageCollection & no_gc) [inline], [static]
Definition at line 151 of file scope-info-inl.h.
                                                                          {
  USE(no_gc);
  return LocalNamesRange<Tagged<ScopeInfo>>(scope_info);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and USE.
language_mode()
LanguageMode v8::internal::ScopeInfo::language_mode () const
Definition at line 720 of file scope-info.cc.
                                            {
  return LanguageModeBit::decode(Flags());
}
References Flags().
Referenced by SloppyEvalCanExtendVars().
length()
int v8::internal::ScopeInfo::length () const [private]
Definition at line 689 of file scope-info.cc.
                            {
  // AllocatedSize() is generated by Torque and represents the size in bytes of
  // the object, as computed from flags, context_local_count, and possibly
  // module_variable_count. Convert that size into a number of slots.
  return (AllocatedSize() - HeapObject::kHeaderSize) / kTaggedSize;
}
References v8::internal::HeapObject::kHeaderSize, and v8::internal::kTaggedSize.
Referenced by Create(), CreateForBootstrapping(), Equals(), FunctionDebugName(), get(), set(), and SizeFor().
Lookup()
int v8::internal::ScopeInfo::Lookup (Handle< String > name, int start, int end, VariableMode * mode, VariableLocation * location, InitializationFlag * init_flag, MaybeAssignedFlag * maybe_assigned_flag) [private]
mark_some_context_has_extension()
void v8::internal::ScopeInfo::mark_some_context_has_extension ()
Definition at line 774 of file scope-info.cc.
                                                {
  set_flags(SomeContextHasExtensionBit::update(Flags(), true), kRelaxedStore);
}
References Flags(), and v8::kRelaxedStore.
ModuleDescriptorInfo()
Tagged< SourceTextModuleInfo > v8::internal::ScopeInfo::ModuleDescriptorInfo () const
Definition at line 921 of file scope-info.cc.
                                                                   {
  DCHECK(scope_type() == MODULE_SCOPE);
  return Cast<SourceTextModuleInfo>(module_info());
}
References v8::internal::DCHECK(), v8::internal::MODULE_SCOPE, and scope_type().
ModuleIndex()
int v8::internal::ScopeInfo::ModuleIndex (Tagged< String > name, VariableMode * mode, InitializationFlag * init_flag, MaybeAssignedFlag * maybe_assigned_flag)
Definition at line 983 of file scope-info.cc.
                                                                   {
  DisallowGarbageCollection no_gc;
  DCHECK(IsInternalizedString(name));
  DCHECK_EQ(scope_type(), MODULE_SCOPE);
  DCHECK_NOT_NULL(mode);
  DCHECK_NOT_NULL(init_flag);
  DCHECK_NOT_NULL(maybe_assigned_flag);
  int module_vars_count = module_variable_count();
  for (int i = 0; i < module_vars_count; ++i) {
    Tagged<String> var_name = module_variables_name(i);
    if (name->Equals(var_name)) {
      int index;
      ModuleVariable(i, nullptr, &index, mode, init_flag, maybe_assigned_flag);
      return index;
    }
  }
  return 0;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::InstanceTypeChecker::IsInternalizedString(), mode(), v8::internal::MODULE_SCOPE, ModuleVariable(), v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and scope_type().
ModuleInfoIndex()
int v8::internal::ScopeInfo::ModuleInfoIndex () const [private]
Definition at line 1127 of file scope-info.cc.
                                     {
  return ConvertOffsetToIndex(ModuleInfoOffset());
}
References ConvertOffsetToIndex().
ModuleVariable()
void v8::internal::ScopeInfo::ModuleVariable (int i, Tagged< String > * name, int * index, VariableMode * mode = nullptr, InitializationFlag * init_flag = nullptr, MaybeAssignedFlag * maybe_assigned_flag = nullptr) [private]
Definition at line 1139 of file scope-info.cc.
                                                                       {
  int properties = module_variables_properties(i);
  if (name != nullptr) {
    *name = module_variables_name(i);
  }
  if (index != nullptr) {
    *index = module_variables_index(i);
    DCHECK_NE(*index, 0);
  }
  if (mode != nullptr) {
    *mode = VariableModeBits::decode(properties);
  }
  if (init_flag != nullptr) {
    *init_flag = InitFlagBit::decode(properties);
  }
  if (maybe_assigned_flag != nullptr) {
    *maybe_assigned_flag = MaybeAssignedFlagBit::decode(properties);
  }
}
References DCHECK_NE, v8::internal::index, mode(), and v8::internal::name.
Referenced by ModuleIndex().
ModuleVariableCount()
int v8::internal::ScopeInfo::ModuleVariableCount () const
Definition at line 978 of file scope-info.cc.
                                         {
  DCHECK_EQ(scope_type(), MODULE_SCOPE);
  return module_variable_count();
}
References DCHECK_EQ, v8::internal::MODULE_SCOPE, and scope_type().
ModuleVariableCountIndex()
int v8::internal::ScopeInfo::ModuleVariableCountIndex () const [private]
Definition at line 1131 of file scope-info.cc.
                                              {
  return ConvertOffsetToIndex(kModuleVariableCountOffset);
}
References ConvertOffsetToIndex().
ModuleVariablesIndex()
int v8::internal::ScopeInfo::ModuleVariablesIndex () const [private]
Definition at line 1135 of file scope-info.cc.
                                          {
  return ConvertOffsetToIndex(ModuleVariablesOffset());
}
References ConvertOffsetToIndex().
OffsetOfElementAt()
static constexpr int v8::internal::ScopeInfo::OffsetOfElementAt (int index) [inline], [static], [constexpr], [private]
Definition at line 344 of file scope-info.h.
                                                    {
    return HeapObject::kHeaderSize + index * kTaggedSize;
  }
References v8::internal::index, v8::internal::HeapObject::kHeaderSize, and v8::internal::kTaggedSize.
Referenced by ConvertOffsetToIndex(), Create(), data_start(), get(), RawFieldOfElementAt(), set(), and SizeFor().
OuterScopeInfo()
Tagged< ScopeInfo > v8::internal::ScopeInfo::OuterScopeInfo () const
Definition at line 916 of file scope-info.cc.
                                                  {
  DCHECK(HasOuterScopeInfo());
  return Cast<ScopeInfo>(outer_scope_info());
}
References v8::internal::DCHECK(), and HasOuterScopeInfo().
OuterScopeInfoIndex()
int v8::internal::ScopeInfo::OuterScopeInfoIndex () const [private]
Definition at line 1123 of file scope-info.cc.
                                         {
  return ConvertOffsetToIndex(OuterScopeInfoOffset());
}
References ConvertOffsetToIndex().
ParameterCount()
int v8::internal::ScopeInfo::ParameterCount () const [inline]
Definition at line 39 of file scope-info-inl.h.
{ return parameter_count(); }
ParametersStartIndex()
int v8::internal::ScopeInfo::ParametersStartIndex () const
Definition at line 1080 of file scope-info.cc.
                                          {
  if (ReceiverVariableBits::decode(Flags()) ==
      VariableAllocationInfo::CONTEXT) {
    return ContextHeaderLength() + 1;
  }
  return ContextHeaderLength();
}
References v8::internal::CONTEXT, ContextHeaderLength(), and Flags().
PrivateNameLookupSkipsOuterClass()
bool v8::internal::ScopeInfo::PrivateNameLookupSkipsOuterClass () const
Definition at line 860 of file scope-info.cc.
                                                       {
  return PrivateNameLookupSkipsOuterClassBit::decode(Flags());
}
References Flags().
RawFieldOfElementAt()
ObjectSlot v8::internal::ScopeInfo::RawFieldOfElementAt (int index) [private]
Definition at line 685 of file scope-info.cc.
                                                   {
  return RawField(OffsetOfElementAt(index));
}
References v8::internal::index, and OffsetOfElementAt().
Referenced by CopyElements().
ReceiverContextSlotIndex()
int v8::internal::ScopeInfo::ReceiverContextSlotIndex () const
Definition at line 1072 of file scope-info.cc.
                                              {
  if (ReceiverVariableBits::decode(Flags()) ==
      VariableAllocationInfo::CONTEXT) {
    return ContextHeaderLength();
  }
  return -1;
}
References v8::internal::CONTEXT, ContextHeaderLength(), and Flags().
SavedClassVariable()
std::pair< Tagged< String >, int > v8::internal::ScopeInfo::SavedClassVariable () const
Definition at line 1049 of file scope-info.cc.
                                                                 {
  DCHECK(HasSavedClassVariableBit::decode(Flags()));
  auto class_variable_info = saved_class_variable_info();
  if (HasInlinedLocalNames()) {
    // The saved class variable info corresponds to the context slot index.
    DCHECK(class_variable_info.IsSmi());
    int index =
        class_variable_info.ToSmi().value() - Context::MIN_CONTEXT_SLOTS;
    DCHECK_GE(index, 0);
    DCHECK_LT(index, ContextLocalCount());
    Tagged<String> name = ContextInlinedLocalName(index);
    return std::make_pair(name, index);
  } else {
    // The saved class variable info corresponds to the name.
    Tagged<Name> name = Cast<Name>(class_variable_info);
    Tagged<NameToIndexHashTable> table = context_local_names_hashtable();
    int index = table->Lookup(name);
    DCHECK_GE(index, 0);
    DCHECK(IsString(name));
    return std::make_pair(Cast<String>(name), index);
  }
}
References ContextInlinedLocalName(), ContextLocalCount(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, Flags(), HasInlinedLocalNames(), v8::internal::index, v8::internal::Context::MIN_CONTEXT_SLOTS, and v8::internal::name.
SavedClassVariableInfoIndex()
int v8::internal::ScopeInfo::SavedClassVariableInfoIndex () const [private]
Definition at line 1111 of file scope-info.cc.
                                                 {
  return ConvertOffsetToIndex(SavedClassVariableInfoOffset());
}
References ConvertOffsetToIndex().
scope_type()
ScopeType v8::internal::ScopeInfo::scope_type () const
Definition at line 702 of file scope-info.cc.
                                      {
  DCHECK(!this->IsEmpty());
  return ScopeTypeBits::decode(Flags());
}
References v8::internal::DCHECK(), Flags(), and IsEmpty().
Referenced by ContextLength(), is_script_scope(), IsReplModeScope(), IsWrappedFunctionScope(), ModuleDescriptorInfo(), ModuleIndex(), ModuleVariableCount(), SetIsDebugEvaluateScope(), and UniqueIdInScript().
set() [1/2]
void v8::internal::ScopeInfo::set (int index, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [private]
Definition at line 666 of file scope-info.cc.
                                                                          {
  DCHECK_LT(static_cast<unsigned>(index), static_cast<unsigned>(length()));
  int offset = OffsetOfElementAt(index);
  RELAXED_WRITE_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, DCHECK_LT, v8::internal::index, length(), mode(), OffsetOfElementAt(), RELAXED_WRITE_FIELD, and v8::internal::value.
set() [2/2]
void v8::internal::ScopeInfo::set (int index, Tagged< Smi > value) [private]
Definition at line 659 of file scope-info.cc.
                                                {
  DCHECK_LT(static_cast<unsigned>(index), static_cast<unsigned>(length()));
  DCHECK(IsSmi(Tagged<Object>(value)));
  int offset = OffsetOfElementAt(index);
  RELAXED_WRITE_FIELD(*this, offset, value);
}
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::index, v8::internal::IsSmi(), length(), OffsetOfElementAt(), RELAXED_WRITE_FIELD, and v8::internal::value.
SetFunctionName()
void v8::internal::ScopeInfo::SetFunctionName (Tagged< UnionOf< Smi, String >> name)
Definition at line 834 of file scope-info.cc.
                                                                 {
  DCHECK(HasFunctionName());
  DCHECK(IsString(name) || name == SharedFunctionInfo::kNoSharedNameSentinel);
  DCHECK_IMPLIES(HasContextAllocatedFunctionName(), IsInternalizedString(name));
  set_function_variable_info_name(name);
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, HasContextAllocatedFunctionName(), HasFunctionName(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::SharedFunctionInfo::kNoSharedNameSentinel, and v8::internal::name.
SetInferredFunctionName()
void v8::internal::ScopeInfo::SetInferredFunctionName (Tagged< String > name)
Definition at line 841 of file scope-info.cc.
                                                           {
  DCHECK(HasInferredFunctionName());
  set_inferred_function_name(name);
}
References v8::internal::DCHECK(), HasInferredFunctionName(), and v8::internal::name.
SetIsDebugEvaluateScope()
void v8::internal::ScopeInfo::SetIsDebugEvaluateScope ()
Definition at line 854 of file scope-info.cc.
                                        {
  CHECK(!this->IsEmpty());
  DCHECK_EQ(scope_type(), WITH_SCOPE);
  set_flags(Flags() | IsDebugEvaluateScopeBit::encode(true), kRelaxedStore);
}
References CHECK, DCHECK_EQ, Flags(), IsEmpty(), v8::kRelaxedStore, scope_type(), and v8::internal::WITH_SCOPE.
SetPositionInfo()
void v8::internal::ScopeInfo::SetPositionInfo (int start, int end)
Definition at line 909 of file scope-info.cc.
                                                  {
  DCHECK(HasPositionInfo());
  DCHECK_LE(start, end);
  set_position_info_start(start);
  set_position_info_end(end);
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::end(), and HasPositionInfo().
SizeFor()
static constexpr int v8::internal::ScopeInfo::SizeFor (int length) [inline], [static], [constexpr]
Definition at line 301 of file scope-info.h.
{ return OffsetOfElementAt(length); }
References length(), and OffsetOfElementAt().
Referenced by v8::internal::Heap::CreateImportantReadOnlyObjects(), and v8::internal::FactoryBase< Impl >::NewScopeInfo().
SloppyEvalCanExtendVars()
bool v8::internal::ScopeInfo::SloppyEvalCanExtendVars () const
Definition at line 712 of file scope-info.cc.
                                              {
  bool sloppy_eval_can_extend_vars =
      SloppyEvalCanExtendVarsBit::decode(Flags());
  DCHECK_IMPLIES(sloppy_eval_can_extend_vars, is_sloppy(language_mode()));
  DCHECK_IMPLIES(sloppy_eval_can_extend_vars, is_declaration_scope());
  return sloppy_eval_can_extend_vars;
}
References DCHECK_IMPLIES, Flags(), is_declaration_scope(), v8::internal::is_sloppy(), and language_mode().
Referenced by ContextLength().
SomeContextHasExtension()
bool v8::internal::ScopeInfo::SomeContextHasExtension () const
Definition at line 770 of file scope-info.cc.
                                              {
  return SomeContextHasExtensionBit::decode(Flags());
}
References Flags().
StartPosition()
int v8::internal::ScopeInfo::StartPosition () const
Definition at line 899 of file scope-info.cc.
                                   {
  DCHECK(HasPositionInfo());
  return position_info_start();
}
References v8::internal::DCHECK(), and HasPositionInfo().
Referenced by Hash(), and UniqueIdInScript().
UniqueIdInScript()
int v8::internal::ScopeInfo::UniqueIdInScript () const
Definition at line 749 of file scope-info.cc.
                                      {
  // Script scopes start "before" the script to avoid clashing with a scope that
  // starts on character 0.
  if (is_script_scope() || scope_type() == EVAL_SCOPE ||
      scope_type() == MODULE_SCOPE) {
    return -2;
  }
  // Wrapped functions start before the function body, but after the script
  // start, to avoid clashing with a scope starting on character 0.
  if (IsWrappedFunctionScope()) {
    return -1;
  }
  // Default constructors have the same start position as their parent class
  // scope. Use the next char position to distinguish this scope.
  return StartPosition() + IsDefaultConstructor(function_kind());
}
References v8::internal::EVAL_SCOPE, function_kind(), is_script_scope(), v8::internal::IsDefaultConstructor(), IsWrappedFunctionScope(), v8::internal::MODULE_SCOPE, scope_type(), and StartPosition().
VariableIsSynthetic()
bool v8::internal::ScopeInfo::VariableIsSynthetic (Tagged< String > name) [static]
Definition at line 969 of file scope-info.cc.
                                                       {
  // There's currently no flag stored on the ScopeInfo to indicate that a
  // variable is a compiler-introduced temporary. However, to avoid conflict
  // with user declarations, the current temporaries like .generator_object and
  // .result start with a dot, so we can use that as a flag. It's a hack!
  return name->length() == 0 || name->Get(0) == '.' || name->Get(0) == '#' ||
         name->Equals(GetReadOnlyRoots().this_string());
}
References v8::internal::GetReadOnlyRoots(), and v8::internal::name.
Referenced by v8::debug::GlobalLexicalScopeNames(), v8::internal::Context::Lookup(), v8::internal::ScopeIterator::VisitContextLocals(), v8::internal::ScopeIterator::VisitLocals(), and v8::internal::ScopeIterator::VisitModuleScope().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, VariableAllocationInfo var) [friend]
Definition at line 1180 of file scope-info.cc.
                                                                        {
  switch (var_info) {
    case VariableAllocationInfo::NONE:
      return os << "NONE";
    case VariableAllocationInfo::STACK:
      return os << "STACK";
    case VariableAllocationInfo::CONTEXT:
      return os << "CONTEXT";
    case VariableAllocationInfo::UNUSED:
      return os << "UNUSED";
  }
  UNREACHABLE();
}
ScopeIterator
friend class ScopeIterator [friend]
Definition at line 377 of file scope-info.h.
Member Data Documentation
kFunctionNameEntries
const int v8::internal::ScopeInfo::kFunctionNameEntries [static], [private]
Initial value:
=
      TorqueGeneratedFunctionVariableInfoOffsets::kSize / kTaggedSize
Definition at line 369 of file scope-info.h.
Referenced by Create(), and CreateForBootstrapping().
kModuleVariableEntryLength
const int v8::internal::ScopeInfo::kModuleVariableEntryLength [static], [private]
Initial value:
=
      TorqueGeneratedModuleVariableOffsets::kSize / kTaggedSize
Definition at line 371 of file scope-info.h.
Referenced by Create().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/scope-info.h
/mnt/V8SourceCode/src/objects/scope-info-inl.h
/mnt/V8SourceCode/src/objects/scope-info.cc