v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope Class Reference
Public Member Functions
PipelineJobScope (TFPipelineData *data, RuntimeCallStats *stats)
PipelineJobScope (turboshaft::PipelineData *turboshaft_data, RuntimeCallStats *stats)
~PipelineJobScope ()
Private Attributes
HighAllocationThroughputScope high_throughput_scope_
TFPipelineData * data_ = nullptr
turboshaft::PipelineData * turboshaft_data_ = nullptr
CurrentHeapBrokerScope current_broker_
Detailed Description
Definition at line 671 of file pipeline.cc.
Constructor & Destructor Documentation
PipelineJobScope() [1/2]
v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::PipelineJobScope (TFPipelineData * data, RuntimeCallStats * stats) [inline]
Definition at line 673 of file pipeline.cc.
      : data_(data), current_broker_(data_->broker()) {
    data_->set_runtime_call_stats(stats);
  }
References v8::internal::compiler::PipelineCompilationJob::data_, and v8::internal::compiler::TFPipelineData::set_runtime_call_stats().
PipelineJobScope() [2/2]
v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::PipelineJobScope (turboshaft::PipelineData * turboshaft_data, RuntimeCallStats * stats) [inline]
Definition at line 677 of file pipeline.cc.
      : turboshaft_data_(turboshaft_data),
        current_broker_(turboshaft_data_->broker()) {
    turboshaft_data_->set_runtime_call_stats(stats);
  }
References v8::internal::compiler::turboshaft::PipelineData::set_runtime_call_stats(), and v8::internal::compiler::PipelineCompilationJob::turboshaft_data_.
 PipelineJobScope()
v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::~PipelineJobScope () [inline]
Definition at line 684 of file pipeline.cc.
                      {
    if (data_) data_->set_runtime_call_stats(nullptr);
    if (turboshaft_data_) turboshaft_data_->set_runtime_call_stats(nullptr);
  }
References v8::internal::compiler::PipelineCompilationJob::data_, v8::internal::compiler::TFPipelineData::set_runtime_call_stats(), v8::internal::compiler::turboshaft::PipelineData::set_runtime_call_stats(), and v8::internal::compiler::PipelineCompilationJob::turboshaft_data_.
Member Data Documentation
current_broker_
CurrentHeapBrokerScope v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::current_broker_ [private]
Definition at line 694 of file pipeline.cc.
data_
TFPipelineData* v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::data_ = nullptr [private]
Definition at line 692 of file pipeline.cc.
high_throughput_scope_
HighAllocationThroughputScope v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::high_throughput_scope_ [private]
Initial value:
{
      V8::GetCurrentPlatform()}
Definition at line 690 of file pipeline.cc.
turboshaft_data_
turboshaft::PipelineData* v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::turboshaft_data_ = nullptr [private]
Definition at line 693 of file pipeline.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc