v8::internal::UnifiedHeapMarkingState Class Reference
#include <unified-heap-marking-state.h>
Public Member Functions
UnifiedHeapMarkingState (Heap *, MarkingWorklists::Local *, cppgc::internal::CollectionType)
UnifiedHeapMarkingState (const UnifiedHeapMarkingState &)=delete
UnifiedHeapMarkingState & operator= (const UnifiedHeapMarkingState &)=delete
void Update (MarkingWorklists::Local *)
void MarkAndPush (const TracedReferenceBase &)
Heap * heap () const
Private Attributes
Heap *const heap_
MarkingState *const marking_state_
MarkingWorklists::Local * local_marking_worklist_ = nullptr
const TracedHandles::MarkMode mark_mode_
Detailed Description
Definition at line 19 of file unified-heap-marking-state.h.
Constructor & Destructor Documentation
UnifiedHeapMarkingState() [1/2]
v8::internal::UnifiedHeapMarkingState::UnifiedHeapMarkingState (Heap * heap, MarkingWorklists::Local * local_marking_worklist, cppgc::internal::CollectionType collection_type)
Definition at line 14 of file unified-heap-marking-state.cc.
    : heap_(heap),
      marking_state_(heap_ ? heap_->marking_state() : nullptr),
      local_marking_worklist_(local_marking_worklist),
      mark_mode_(collection_type == cppgc::internal::CollectionType::kMinor
                     ? TracedHandles::MarkMode::kOnlyYoung
                     : TracedHandles::MarkMode::kAll) {
  DCHECK_IMPLIES(heap_, marking_state_);
}
References DCHECK_IMPLIES, heap_, and marking_state_.
UnifiedHeapMarkingState() [2/2]
v8::internal::UnifiedHeapMarkingState::UnifiedHeapMarkingState (const UnifiedHeapMarkingState &) [delete]
Member Function Documentation
heap()
Heap* v8::internal::UnifiedHeapMarkingState::heap () const [inline]
Definition at line 31 of file unified-heap-marking-state.h.
{ return heap_; }
References heap_.
Referenced by v8::internal::UnifiedHeapMarker::AdvanceMarkingOnAllocationImpl().
MarkAndPush()
void v8::internal::UnifiedHeapMarkingState::MarkAndPush (const TracedReferenceBase & reference) [inline]
Definition at line 33 of file unified-heap-marking-state-inl.h.
                                          {
  // The following code will crash with null pointer derefs when finding a
  // non-empty `TracedReferenceBase` when `CppHeap` is in detached mode.
  Address* traced_handle_location =
      BasicTracedReferenceExtractor::GetObjectSlotForMarking(reference);
  // We cannot assume that the reference is non-null as we may get here by
  // tracing an ephemeron which doesn't have early bailouts, see
  // `cppgc::Visitor::TraceEphemeron()` for non-Member values.
  if (!traced_handle_location) {
    return;
  }
  Tagged<Object> object =
      TracedHandles::Mark(traced_handle_location, mark_mode_);
  if (!IsHeapObject(object)) {
    // The embedder is not aware of whether numbers are materialized as heap
    // objects are just passed around as Smis.
    return;
  }
  Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
  const auto worklist_target =
      MarkingHelper::ShouldMarkObject(heap_, heap_object);
  if (worklist_target) {
    MarkingHelper::TryMarkAndPush(heap_, local_marking_worklist_,
                                  marking_state_, worklist_target.value(),
                                  heap_object);
  }
}
References v8::internal::BasicTracedReferenceExtractor::GetObjectSlotForMarking(), heap_, v8::internal::IsHeapObject(), local_marking_worklist_, v8::internal::TracedHandles::Mark(), mark_mode_, marking_state_, v8::internal::MarkingHelper::ShouldMarkObject(), and v8::internal::MarkingHelper::TryMarkAndPush().
Referenced by v8::internal::UnifiedHeapMarkingVisitorBase::Visit().
operator=()
UnifiedHeapMarkingState& v8::internal::UnifiedHeapMarkingState::operator= (const UnifiedHeapMarkingState &) [delete]
Update()
void v8::internal::UnifiedHeapMarkingState::Update (MarkingWorklists::Local * local_marking_worklist)
Definition at line 26 of file unified-heap-marking-state.cc.
                                                   {
  local_marking_worklist_ = local_marking_worklist;
  DCHECK_NOT_NULL(heap_);
}
References DCHECK_NOT_NULL, heap_, and local_marking_worklist_.
Member Data Documentation
heap_
Heap* const v8::internal::UnifiedHeapMarkingState::heap_ [private]
Definition at line 34 of file unified-heap-marking-state.h.
Referenced by heap(), MarkAndPush(), UnifiedHeapMarkingState(), and Update().
local_marking_worklist_
MarkingWorklists::Local* v8::internal::UnifiedHeapMarkingState::local_marking_worklist_ = nullptr [private]
Definition at line 36 of file unified-heap-marking-state.h.
Referenced by MarkAndPush(), and Update().
mark_mode_
const TracedHandles::MarkMode v8::internal::UnifiedHeapMarkingState::mark_mode_ [private]
Definition at line 37 of file unified-heap-marking-state.h.
Referenced by MarkAndPush().
marking_state_
MarkingState* const v8::internal::UnifiedHeapMarkingState::marking_state_ [private]
Definition at line 35 of file unified-heap-marking-state.h.
Referenced by MarkAndPush(), and UnifiedHeapMarkingState().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-state.h
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-state-inl.h
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-state.cc