v8::internal::NameToIndexHashTable Class Reference
#include <hash-table.h>
Public Member Functions
int Lookup (Tagged< Name > key)
Tagged< Object > ValueAt (InternalIndex entry)
int IndexAt (InternalIndex entry)
Static Public Member Functions
static DirectHandle< Map > GetMap (RootsTable &roots)
template<typename IsolateT >
static Handle< NameToIndexHashTable > Add (IsolateT *isolate, Handle< NameToIndexHashTable > table, DirectHandle< Name > key, int32_t value)
Static Public Attributes
static const int kEntryValueIndex = NameToIndexShape::kEntryValueIndex
Static Private Member Functions
static int EntryToValueIndex (InternalIndex entry)
Detailed Description
Definition at line 540 of file hash-table.h.
Member Function Documentation
Add()
template<typename IsolateT >
Handle< NameToIndexHashTable > v8::internal::NameToIndexHashTable::Add (IsolateT * isolate, Handle< NameToIndexHashTable > table, DirectHandle< Name > key, int32_t value) [static]
Definition at line 305 of file hash-table-inl.h.
                                           {
  DCHECK_GE(index, 0);
  // Validate that the key is absent.
  SLOW_DCHECK(table->FindEntry(isolate, *key).is_not_found());
  // Check whether the dictionary should be extended.
  table = EnsureCapacity(isolate, table);
  DisallowGarbageCollection no_gc;
  Tagged<NameToIndexHashTable> raw_table = *table;
  // Compute the key object.
  InternalIndex entry = raw_table->FindInsertionEntry(isolate, key->hash());
  raw_table->set(EntryToIndex(entry), *key);
  raw_table->set(EntryToValueIndex(entry), Smi::FromInt(index));
  raw_table->ElementAdded();
  return table;
}
References DCHECK_GE, EntryToValueIndex(), v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and SLOW_DCHECK.
Referenced by v8::internal::anonymous_namespace{contexts.cc}::AddLocalNamesFromContext(), and v8::internal::ScopeInfo::Create().
EntryToValueIndex()
static int v8::internal::NameToIndexHashTable::EntryToValueIndex (InternalIndex entry) [inline], [static], [private]
Definition at line 565 of file hash-table.h.
                                                           {
    return EntryToIndex(entry) + NameToIndexShape::kEntryValueIndex;
  }
References v8::internal::NameToIndexShape::kEntryValueIndex.
Referenced by Add().
GetMap()
DirectHandle< Map > v8::internal::NameToIndexHashTable::GetMap (RootsTable & roots) [inline], [static]
Definition at line 114 of file hash-table-inl.h.
                                                                {
  return roots.name_to_index_hash_table_map();
}
IndexAt()
int v8::internal::NameToIndexHashTable::IndexAt (InternalIndex entry)
Definition at line 6099 of file objects.cc.
                                                     {
  Tagged<Object> value = ValueAt(entry);
  if (IsSmi(value)) {
    int index = Smi::ToInt(value);
    DCHECK_LE(0, index);
    return index;
  }
  return -1;
}
References DCHECK_LE, v8::internal::index, v8::internal::IsSmi(), v8::internal::Smi::ToInt(), and v8::internal::value.
Lookup()
int v8::internal::NameToIndexHashTable::Lookup (Tagged< Name > key)
Definition at line 6052 of file objects.cc.
                                                 {
  DisallowGarbageCollection no_gc;
  PtrComprCageBase cage_base = GetPtrComprCageBase(this);
  ReadOnlyRoots roots = GetReadOnlyRoots();
  InternalIndex entry = this->FindEntry(cage_base, roots, key, key->hash());
  if (entry.is_not_found()) return -1;
  return Cast<Smi>(this->get(EntryToValueIndex(entry))).value();
}
References v8::internal::GetPtrComprCageBase(), v8::internal::GetReadOnlyRoots(), v8::internal::InternalIndex::is_not_found(), v8::internal::key, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
ValueAt()
Tagged< Object > v8::internal::NameToIndexHashTable::ValueAt (InternalIndex entry)
Definition at line 6095 of file objects.cc.
                                                                {
  return this->get(EntryToValueIndex(entry));
}
Member Data Documentation
kEntryValueIndex
const int v8::internal::NameToIndexHashTable::kEntryValueIndex = NameToIndexShape::kEntryValueIndex [static]
Definition at line 543 of file hash-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/hash-table.h
/mnt/V8SourceCode/src/objects/hash-table-inl.h
/mnt/V8SourceCode/src/objects/objects.cc