v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT > Class Template Reference
#include <flags.h>
Public Types
using flag_type = EnumT
using mask_type = BitfieldT
Public Member Functions
constexpr Flags ()
constexpr Flags (flag_type flag)
constexpr Flags (mask_type mask)
constexpr bool operator== (flag_type flag) const
Flags & operator&= (const Flags &flags)
Flags & operator|= (const Flags &flags)
Flags & operator^= (const Flags &flags)
constexpr Flags operator& (const Flags &flags) const
constexpr Flags operator| (const Flags &flags) const
constexpr Flags operator^ (const Flags &flags) const
Flags & operator&= (flag_type flag)
Flags & operator|= (flag_type flag)
Flags & operator^= (flag_type flag)
Flags & set (flag_type flag, bool value)
constexpr Flags operator& (flag_type flag) const
constexpr Flags operator| (flag_type flag) const
constexpr Flags operator^ (flag_type flag) const
constexpr Flags operator~ () const
constexpr operator mask_type () const
constexpr bool operator! () const
Flags without (flag_type flag) const
Private Attributes
BitfieldStorageT mask_
Friends
size_t hash_value (const Flags &flags)
Detailed Description
template<typename EnumT, typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
class v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >
Definition at line 25 of file flags.h.
Member Typedef Documentation
flag_type
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
using v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::flag_type = EnumT
Definition at line 28 of file flags.h.
mask_type
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
using v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_type = BitfieldT
Definition at line 29 of file flags.h.
Constructor & Destructor Documentation
Flags() [1/3]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags () [inline], [constexpr]
Definition at line 31 of file flags.h.
: mask_(0) {}
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&=(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^=(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|=(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator~(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::set().
Flags() [2/3]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags (flag_type flag) [inline], [constexpr]
Definition at line 32 of file flags.h.
      : mask_(static_cast<mask_type>(flag)) {}
Flags() [3/3]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags (mask_type mask) [inline], [explicit], [constexpr]
Definition at line 34 of file flags.h.
      : mask_(static_cast<mask_type>(mask)) {}
Member Function Documentation
operator mask_type()
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator mask_type () const [inline], [constexpr]
Definition at line 86 of file flags.h.
{ return mask_; }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
operator!()
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr bool v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator! () const [inline], [constexpr]
Definition at line 87 of file flags.h.
{ return !mask_; }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
operator&() [1/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr Flags v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator& (const Flags< EnumT, BitfieldT, BitfieldStorageT > & flags) const [inline], [constexpr]
Definition at line 54 of file flags.h.
                                                      {
    return Flags(mask_ & flags.mask_);
  }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&().
operator&() [2/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr Flags v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator& (flag_type flag) const [inline], [constexpr]
Definition at line 74 of file flags.h.
                                                  {
    return operator&(Flags(flag));
  }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&().
operator&=() [1/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
Flags& v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&= (const Flags< EnumT, BitfieldT, BitfieldStorageT > & flags) [inline]
Definition at line 41 of file flags.h.
                                        {
    mask_ &= flags.mask_;
    return *this;
  }
References flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::set().
operator&=() [2/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
Flags& v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&= (flag_type flag) [inline]
Definition at line 64 of file flags.h.
{ return operator&=(Flags(flag)); }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&=().
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&=().
operator==()
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr bool v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator== (flag_type flag) const [inline], [constexpr]
Definition at line 37 of file flags.h.
                                                  {
    return mask_ == static_cast<mask_type>(flag);
  }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
operator^() [1/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr Flags v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^ (const Flags< EnumT, BitfieldT, BitfieldStorageT > & flags) const [inline], [constexpr]
Definition at line 60 of file flags.h.
                                                      {
    return Flags(mask_ ^ flags.mask_);
  }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^().
operator^() [2/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr Flags v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^ (flag_type flag) const [inline], [constexpr]
Definition at line 80 of file flags.h.
                                                  {
    return operator^(Flags(flag));
  }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^().
operator^=() [1/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
Flags& v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^= (const Flags< EnumT, BitfieldT, BitfieldStorageT > & flags) [inline]
Definition at line 49 of file flags.h.
                                        {
    mask_ ^= flags.mask_;
    return *this;
  }
References flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
operator^=() [2/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
Flags& v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^= (flag_type flag) [inline]
Definition at line 66 of file flags.h.
{ return operator^=(Flags(flag)); }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^=().
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^=().
operator|() [1/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr Flags v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator| (const Flags< EnumT, BitfieldT, BitfieldStorageT > & flags) const [inline], [constexpr]
Definition at line 57 of file flags.h.
                                                      {
    return Flags(mask_ | flags.mask_);
  }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|().
operator|() [2/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr Flags v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator| (flag_type flag) const [inline], [constexpr]
Definition at line 77 of file flags.h.
                                                  {
    return operator|(Flags(flag));
  }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|().
operator|=() [1/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
Flags& v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|= (const Flags< EnumT, BitfieldT, BitfieldStorageT > & flags) [inline]
Definition at line 45 of file flags.h.
                                        {
    mask_ |= flags.mask_;
    return *this;
  }
References flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::set().
operator|=() [2/2]
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
Flags& v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|= (flag_type flag) [inline]
Definition at line 65 of file flags.h.
{ return operator|=(Flags(flag)); }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|=().
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|=().
operator ()
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
constexpr Flags v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator~ () const [inline], [constexpr]
Definition at line 84 of file flags.h.
{ return Flags(~mask_); }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_.
set()
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
Flags& v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::set (flag_type flag, bool value) [inline]
Definition at line 69 of file flags.h.
                                         {
    if (value) return operator|=(Flags(flag));
    return operator&=(~Flags(flag));
  }
References v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::Flags(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&=(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|=(), and v8::internal::value.
without()
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
Flags v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::without (flag_type flag) const [inline]
Definition at line 89 of file flags.h.
{ return *this & (~Flags(flag)); }
Referenced by v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), v8::internal::torque::cpp::Function::SetFlag(), and v8::internal::compiler::RepresentationSelector::VisitCheckBounds().
Friends And Related Function Documentation
hash_value
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
size_t hash_value (const Flags< EnumT, BitfieldT, BitfieldStorageT > & flags) [friend]
Definition at line 91 of file flags.h.
{ return flags.mask_; }
Member Data Documentation
mask_
template<typename EnumT , typename BitfieldT = int, typename BitfieldStorageT = BitfieldT>
BitfieldStorageT v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::mask_ [private]
Definition at line 94 of file flags.h.
Referenced by v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator mask_type(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator!(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&=(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator==(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^=(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|=(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator~().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/flags.h