v8::internal::LiteralBuffer Class Reference
#include <literal-buffer.h>
Public Member Functions
LiteralBuffer ()=default
~LiteralBuffer ()
LiteralBuffer (const LiteralBuffer &)=delete
LiteralBuffer & operator= (const LiteralBuffer &)=delete
void AddChar (char code_unit)
void AddChar (base::uc32 code_unit)
bool is_one_byte () const
bool Equals (base::Vector< const char > keyword) const
base::Vector< const uint16_t > two_byte_literal () const
base::Vector< const uint8_t > one_byte_literal () const
template<typename Char >
base::Vector< const Char > literal () const
int length () const
void Start ()
template<typename IsolateT >
DirectHandle< String > Internalize (IsolateT *isolate) const
Private Member Functions
bool IsValidAscii (char code_unit)
void AddOneByteChar (uint8_t one_byte_char)
void AddTwoByteChar (base::uc32 code_unit)
int NewCapacity (int min_capacity)
V8_NOINLINE V8_PRESERVE_MOST void ExpandBuffer ()
void ConvertToTwoByte ()
Private Attributes
base::Vector< uint8_t > backing_store_
int position_ = 0
bool is_one_byte_ = true
Static Private Attributes
static constexpr int kInitialCapacity = 256
static constexpr int kGrowthFactor = 4
static constexpr int kMaxGrowth = 1 * MB
Detailed Description
Definition at line 17 of file literal-buffer.h.
Constructor & Destructor Documentation
LiteralBuffer() [1/2]
v8::internal::LiteralBuffer::LiteralBuffer () [default]
 LiteralBuffer()
v8::internal::LiteralBuffer::~LiteralBuffer () [inline]
Definition at line 20 of file literal-buffer.h.
{ backing_store_.Dispose(); }
References backing_store_, and v8::base::Vector< T >::Dispose().
LiteralBuffer() [2/2]
v8::internal::LiteralBuffer::LiteralBuffer (const LiteralBuffer &) [delete]
Member Function Documentation
AddChar() [1/2]
void v8::internal::LiteralBuffer::AddChar (base::uc32 code_unit) [inline]
Definition at line 30 of file literal-buffer.h.
                                             {
    if (is_one_byte()) {
      if (code_unit <= static_cast<base::uc32>(unibrow::Latin1::kMaxChar)) {
        AddOneByteChar(static_cast<uint8_t>(code_unit));
        return;
      }
      ConvertToTwoByte();
    }
    AddTwoByteChar(code_unit);
  }
References AddOneByteChar(), AddTwoByteChar(), ConvertToTwoByte(), is_one_byte(), and unibrow::Latin1::kMaxChar.
AddChar() [2/2]
void v8::internal::LiteralBuffer::AddChar (char code_unit) [inline]
Definition at line 25 of file literal-buffer.h.
                                         {
    DCHECK(IsValidAscii(code_unit));
    AddOneByteChar(static_cast<uint8_t>(code_unit));
  }
References AddOneByteChar(), v8::internal::DCHECK(), and IsValidAscii().
AddOneByteChar()
void v8::internal::LiteralBuffer::AddOneByteChar (uint8_t one_byte_char) [inline], [private]
Definition at line 88 of file literal-buffer.h.
                                                       {
    DCHECK(is_one_byte());
    if (position_ >= backing_store_.length()) ExpandBuffer();
    backing_store_[position_] = one_byte_char;
    position_ += kOneByteSize;
  }
References backing_store_, v8::internal::DCHECK(), ExpandBuffer(), is_one_byte(), v8::internal::kOneByteSize, v8::base::Vector< T >::length(), and position_.
Referenced by AddChar().
AddTwoByteChar()
void v8::internal::LiteralBuffer::AddTwoByteChar (base::uc32 code_unit) [private]
Definition at line 70 of file literal-buffer.cc.
                                                     {
  DCHECK(!is_one_byte());
  if (position_ >= backing_store_.length()) ExpandBuffer();
  if (code_unit <=
      static_cast<base::uc32>(unibrow::Utf16::kMaxNonSurrogateCharCode)) {
    *reinterpret_cast<uint16_t*>(&backing_store_[position_]) = code_unit;
    position_ += base::kUC16Size;
  } else {
    *reinterpret_cast<uint16_t*>(&backing_store_[position_]) =
        unibrow::Utf16::LeadSurrogate(code_unit);
    position_ += base::kUC16Size;
    if (position_ >= backing_store_.length()) ExpandBuffer();
    *reinterpret_cast<uint16_t*>(&backing_store_[position_]) =
        unibrow::Utf16::TrailSurrogate(code_unit);
    position_ += base::kUC16Size;
  }
}
References backing_store_, v8::internal::DCHECK(), ExpandBuffer(), is_one_byte(), unibrow::Utf16::kMaxNonSurrogateCharCode, v8::base::kUC16Size, unibrow::Utf16::LeadSurrogate(), v8::base::Vector< T >::length(), position_, and unibrow::Utf16::TrailSurrogate().
Referenced by AddChar().
ConvertToTwoByte()
void v8::internal::LiteralBuffer::ConvertToTwoByte () [private]
Definition at line 46 of file literal-buffer.cc.
                                     {
  DCHECK(is_one_byte());
  base::Vector<uint8_t> new_store;
  int new_content_size = position_ * base::kUC16Size;
  if (new_content_size >= backing_store_.length()) {
    // Ensure room for all currently read code units as UC16 as well
    // as the code unit about to be stored.
    new_store = base::Vector<uint8_t>::New(NewCapacity(new_content_size));
  } else {
    new_store = backing_store_;
  }
  uint8_t* src = backing_store_.begin();
  uint16_t* dst = reinterpret_cast<uint16_t*>(new_store.begin());
  for (int i = position_ - 1; i >= 0; i--) {
    dst[i] = src[i];
  }
  if (new_store.begin() != backing_store_.begin()) {
    backing_store_.Dispose();
    backing_store_ = new_store;
  }
  position_ = new_content_size;
  is_one_byte_ = false;
}
References backing_store_, v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::base::Vector< T >::Dispose(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_one_byte(), is_one_byte_, v8::base::kUC16Size, v8::base::Vector< T >::length(), v8::base::Vector< T >::New(), NewCapacity(), and position_.
Referenced by AddChar().
Equals()
bool v8::internal::LiteralBuffer::Equals (base::Vector< const char > keyword) const [inline]
Definition at line 43 of file literal-buffer.h.
                                                    {
    return is_one_byte() && keyword.length() == position_ &&
           (memcmp(keyword.begin(), backing_store_.begin(), position_) == 0);
  }
References backing_store_, v8::base::Vector< T >::begin(), is_one_byte(), v8::base::Vector< T >::length(), and position_.
ExpandBuffer()
void v8::internal::LiteralBuffer::ExpandBuffer () [private]
Definition at line 35 of file literal-buffer.cc.
                                 {
  int min_capacity = std::max({kInitialCapacity, backing_store_.length()});
  base::Vector<uint8_t> new_store =
      base::Vector<uint8_t>::New(NewCapacity(min_capacity));
  if (position_ > 0) {
    MemCopy(new_store.begin(), backing_store_.begin(), position_);
  }
  backing_store_.Dispose();
  backing_store_ = new_store;
}
References backing_store_, v8::base::Vector< T >::begin(), v8::base::Vector< T >::Dispose(), kInitialCapacity, v8::base::Vector< T >::length(), v8::internal::MemCopy(), v8::base::Vector< T >::New(), NewCapacity(), and position_.
Referenced by AddOneByteChar(), and AddTwoByteChar().
Internalize()
template<typename IsolateT >
template DirectHandle< String > v8::internal::LiteralBuffer::Internalize (IsolateT * isolate) const
Definition at line 17 of file literal-buffer.cc.
                                                                       {
  if (is_one_byte()) {
    return isolate->factory()->InternalizeString(one_byte_literal());
  }
  return isolate->factory()->InternalizeString(two_byte_literal());
}
References is_one_byte(), one_byte_literal(), and two_byte_literal().
Referenced by v8::internal::Scanner::DebugId(), v8::internal::Scanner::SourceMappingUrl(), and v8::internal::Scanner::SourceUrl().
is_one_byte()
bool v8::internal::LiteralBuffer::is_one_byte () const [inline]
Definition at line 41 of file literal-buffer.h.
{ return is_one_byte_; }
References is_one_byte_.
Referenced by AddChar(), AddOneByteChar(), AddTwoByteChar(), ConvertToTwoByte(), Equals(), Internalize(), length(), and v8::internal::Scanner::TryToParseMagicComment().
IsValidAscii()
bool v8::internal::LiteralBuffer::IsValidAscii (char code_unit) [inline], [private]
Definition at line 80 of file literal-buffer.h.
                                           {
    // Control characters and printable characters span the range of
    // valid ASCII characters (0-127). Chars are unsigned on some
    // platforms which causes compiler warnings if the validity check
    // tests the lower bound >= 0 as it's always true.
    return iscntrl(code_unit) || isprint(code_unit);
  }
Referenced by AddChar().
length()
int v8::internal::LiteralBuffer::length () const [inline]
Definition at line 65 of file literal-buffer.h.
{ return is_one_byte() ? position_ : (position_ >> 1); }
References is_one_byte(), and position_.
Referenced by v8::internal::Scanner::DebugId(), v8::internal::Scanner::LiteralContainsEscapes(), v8::internal::Scanner::SourceMappingUrl(), and v8::internal::Scanner::SourceUrl().
literal()
template<typename Char >
base::Vector<const Char> v8::internal::LiteralBuffer::literal () const [inline]
Definition at line 57 of file literal-buffer.h.
                                         {
    DCHECK_EQ(is_one_byte_, sizeof(Char) == 1);
    DCHECK_EQ(position_ & (sizeof(Char) - 1), 0);
    return base::Vector<const Char>(
        reinterpret_cast<const Char*>(backing_store_.begin()),
        position_ >> (sizeof(Char) - 1));
  }
References backing_store_, v8::base::Vector< T >::begin(), DCHECK_EQ, is_one_byte_, and position_.
NewCapacity()
int v8::internal::LiteralBuffer::NewCapacity (int min_capacity) [private]
Definition at line 29 of file literal-buffer.cc.
                                               {
  return min_capacity < (kMaxGrowth / (kGrowthFactor - 1))
             ? min_capacity * kGrowthFactor
             : min_capacity + kMaxGrowth;
}
References kGrowthFactor, and kMaxGrowth.
Referenced by ConvertToTwoByte(), and ExpandBuffer().
one_byte_literal()
base::Vector<const uint8_t> v8::internal::LiteralBuffer::one_byte_literal () const [inline]
Definition at line 52 of file literal-buffer.h.
                                                     {
    return literal<uint8_t>();
  }
Referenced by Internalize(), v8::internal::Scanner::ScanIdentifierOrKeywordInner(), v8::internal::Scanner::ScanIdentifierOrKeywordInnerSlow(), and v8::internal::Scanner::TryToParseMagicComment().
operator=()
LiteralBuffer& v8::internal::LiteralBuffer::operator= (const LiteralBuffer &) [delete]
Start()
void v8::internal::LiteralBuffer::Start () [inline]
Definition at line 67 of file literal-buffer.h.
               {
    position_ = 0;
    is_one_byte_ = true;
  }
References is_one_byte_, and position_.
Referenced by v8::internal::Scanner::ScanIdentifierOrKeyword(), v8::internal::Scanner::ScanNumber(), v8::internal::Scanner::ScanPrivateName(), v8::internal::Scanner::ScanRegExpFlags(), v8::internal::Scanner::ScanRegExpPattern(), v8::internal::Scanner::ScanString(), and v8::internal::Scanner::ScanTemplateSpan().
two_byte_literal()
base::Vector<const uint16_t> v8::internal::LiteralBuffer::two_byte_literal () const [inline]
Definition at line 48 of file literal-buffer.h.
                                                      {
    return literal<uint16_t>();
  }
Referenced by Internalize().
Member Data Documentation
backing_store_
base::Vector<uint8_t> v8::internal::LiteralBuffer::backing_store_ [private]
Definition at line 100 of file literal-buffer.h.
Referenced by AddOneByteChar(), AddTwoByteChar(), ConvertToTwoByte(), Equals(), ExpandBuffer(), literal(), and ~LiteralBuffer().
is_one_byte_
bool v8::internal::LiteralBuffer::is_one_byte_ = true [private]
Definition at line 102 of file literal-buffer.h.
Referenced by ConvertToTwoByte(), is_one_byte(), literal(), and Start().
kGrowthFactor
constexpr int v8::internal::LiteralBuffer::kGrowthFactor = 4 [static], [constexpr], [private]
Definition at line 77 of file literal-buffer.h.
Referenced by NewCapacity().
kInitialCapacity
constexpr int v8::internal::LiteralBuffer::kInitialCapacity = 256 [static], [constexpr], [private]
Definition at line 76 of file literal-buffer.h.
Referenced by ExpandBuffer().
kMaxGrowth
constexpr int v8::internal::LiteralBuffer::kMaxGrowth = 1 * MB [static], [constexpr], [private]
Definition at line 78 of file literal-buffer.h.
Referenced by NewCapacity().
position_
int v8::internal::LiteralBuffer::position_ = 0 [private]
Definition at line 101 of file literal-buffer.h.
Referenced by AddOneByteChar(), AddTwoByteChar(), ConvertToTwoByte(), Equals(), ExpandBuffer(), length(), literal(), and Start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/literal-buffer.h
/mnt/V8SourceCode/src/parsing/literal-buffer.cc