v8::internal::compiler::LocationOperand Class Reference
#include <instruction.h>
Public Types
enum LocationKind { REGISTER
, STACK_SLOT
 }
using LocationKindField = KindField::Next< LocationKind, 1 >
using RepresentationField = LocationKindField::Next< MachineRepresentation, 8 >
using IndexField = base::BitField64< int32_t, 32, 32 >
Public Member Functions
LocationOperand (InstructionOperand::Kind operand_kind, LocationOperand::LocationKind location_kind, MachineRepresentation rep, int index)
int index () const
int register_code () const
Register GetRegister () const
FloatRegister GetFloatRegister () const
DoubleRegister GetDoubleRegister () const
Simd128Register GetSimd128Register () const
LocationKind location_kind () const
MachineRepresentation representation () const
bool IsCompatible (LocationOperand *op)
Static Public Member Functions
static bool IsSupportedRepresentation (MachineRepresentation rep)
static LocationOperand * cast (InstructionOperand *op)
static const LocationOperand * cast (const InstructionOperand *op)
static LocationOperand cast (const InstructionOperand &op)
Additional Inherited Members
Detailed Description
Definition at line 497 of file instruction.h.
Member Typedef Documentation
IndexField
using v8::internal::compiler::LocationOperand::IndexField = base::BitField64<int32_t, 32, 32>
Definition at line 617 of file instruction.h.
LocationKindField
using v8::internal::compiler::LocationOperand::LocationKindField = KindField::Next<LocationKind, 1>
Definition at line 614 of file instruction.h.
RepresentationField
using v8::internal::compiler::LocationOperand::RepresentationField = LocationKindField::Next<MachineRepresentation, 8>
Definition at line 615 of file instruction.h.
Member Enumeration Documentation
LocationKind
enum v8::internal::compiler::LocationOperand::LocationKind
Enumerator
REGISTER
STACK_SLOT
Definition at line 499 of file instruction.h.
{ REGISTER, STACK_SLOT };
Constructor & Destructor Documentation
LocationOperand()
v8::internal::compiler::LocationOperand::LocationOperand (InstructionOperand::Kind operand_kind, LocationOperand::LocationKind location_kind, MachineRepresentation rep, int index) [inline]
Definition at line 501 of file instruction.h.
      : InstructionOperand(operand_kind) {
    DCHECK_IMPLIES(location_kind == REGISTER, index >= 0);
    DCHECK(IsSupportedRepresentation(rep));
    value_ |= LocationKindField::encode(location_kind);
    value_ |= RepresentationField::encode(rep);
    value_ |= static_cast<uint64_t>(static_cast<int64_t>(index))
              << IndexField::kShift;
  }
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::index, and v8::internal::compiler::InstructionOperand::value_.
Member Function Documentation
cast() [1/3]
static LocationOperand v8::internal::compiler::LocationOperand::cast (const InstructionOperand & op) [inline], [static]
Definition at line 609 of file instruction.h.
                                                            {
    DCHECK(op.IsAnyLocationOperand());
    return *static_cast<const LocationOperand*>(&op);
  }
References v8::internal::DCHECK(), and v8::internal::compiler::InstructionOperand::IsAnyLocationOperand().
cast() [2/3]
static const LocationOperand* v8::internal::compiler::LocationOperand::cast (const InstructionOperand * op) [inline], [static]
Definition at line 604 of file instruction.h.
                                                                   {
    DCHECK(op->IsAnyLocationOperand());
    return static_cast<const LocationOperand*>(op);
  }
References v8::internal::DCHECK(), and v8::internal::compiler::InstructionOperand::IsAnyLocationOperand().
cast() [3/3]
static LocationOperand* v8::internal::compiler::LocationOperand::cast (InstructionOperand * op) [inline], [static]
Definition at line 599 of file instruction.h.
                                                       {
    DCHECK(op->IsAnyLocationOperand());
    return static_cast<LocationOperand*>(op);
  }
References v8::internal::DCHECK(), and v8::internal::compiler::InstructionOperand::IsAnyLocationOperand().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::maglev::detail::AlreadyInARegister(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::maglev::ValueLocation::AssignedDoubleRegister(), v8::internal::maglev::ValueLocation::AssignedGeneralRegister(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameSingleValue(), v8::internal::compiler::RegisterAllocatorVerifier::CheckConstraint(), v8::internal::compiler::MoveOperands::CheckPointerCompressionConsistency(), v8::internal::compiler::BlockAssessments::CheckReferenceMap(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::ContainsOpOrAlias(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::MaglevAssembler::FromAnyToRegister(), v8::internal::compiler::InstructionOperand::GetCanonicalizedValue(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::UsePosition::HintRegister(), v8::internal::compiler::CodeGenerator::MoveType::InferMove(), v8::internal::compiler::CodeGenerator::MoveType::InferSwap(), v8::internal::compiler::S390OperandConverter::InputStackSlot(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::InsertOp(), v8::internal::compiler::InstructionOperand::InterferesWith(), v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::Is32BitOperand(), v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::Is32BitOperand(), v8::anonymous_namespace{code-generator-riscv.cc}::Is32BitOperand(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::Is32BitOperand(), v8::internal::compiler::S390OperandConverter::Is32BitOperand(), v8::internal::compiler::S390OperandConverter::Is64BitOperand(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::Is64BitsWide(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::compiler::InstructionOperand::IsDoubleRegister(), v8::internal::compiler::InstructionOperand::IsDoubleStackSlot(), v8::internal::compiler::InstructionOperand::IsFloatRegister(), v8::internal::compiler::InstructionOperand::IsFloatStackSlot(), v8::internal::compiler::InstructionOperand::IsFPLocationOperand(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsLocationOperand(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsSimd128Register(), v8::internal::compiler::InstructionOperand::IsSimd128StackSlot(), v8::internal::compiler::InstructionOperand::IsSimd256Register(), v8::internal::compiler::InstructionOperand::IsSimd256StackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::BlockAssessments::IsStaleReferenceStackSlot(), v8::internal::compiler::LiveRangeBuilder::LiveRangeFor(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::operator<<(), v8::internal::compiler::GapResolver::PerformCycle(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::CodeGenerator::Push(), v8::internal::maglev::detail::PushInput(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot(), v8::internal::compiler::ReferenceMap::RecordReference(), v8::internal::compiler::CodeGenerator::RecordSafepoint(), v8::internal::compiler::SignExtend(), v8::internal::maglev::ValueNode::spill_slot(), v8::internal::maglev::ToDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::ToFloatRegister(), v8::internal::maglev::MaglevAssembler::ToMemOperand(), v8::internal::compiler::ArmOperandConverter::ToMemOperand(), v8::internal::compiler::Loong64OperandConverter::ToMemOperand(), v8::internal::compiler::MipsOperandConverter::ToMemOperand(), v8::internal::compiler::PPCOperandConverter::ToMemOperand(), v8::internal::compiler::RiscvOperandConverter::ToMemOperand(), v8::internal::compiler::S390OperandConverter::ToMemOperand(), v8::internal::compiler::Arm64OperandConverter::ToMemOperand(), v8::internal::compiler::IA32OperandConverter::ToOperand(), v8::internal::compiler::X64OperandConverter::ToOperand(), v8::internal::maglev::ToRegister(), v8::internal::compiler::InstructionOperandConverter::ToRegister(), v8::internal::maglev::detail::ToRegister(), v8::internal::compiler::InstructionOperandConverter::ToSimd128Register(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves(), and v8::internal::maglev::StraightForwardRegisterAllocator::VerifyInputs().
GetDoubleRegister()
DoubleRegister v8::internal::compiler::LocationOperand::GetDoubleRegister () const [inline]
Definition at line 533 of file instruction.h.
                                           {
    // On platforms where FloatRegister, DoubleRegister, and Simd128Register
    // are all the same type, it's convenient to treat everything as a
    // DoubleRegister, so be lax about type checking here.
    DCHECK(IsFPRegister());
    return DoubleRegister::from_code(register_code());
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), and v8::internal::compiler::InstructionOperand::IsFPRegister().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), v8::internal::maglev::ValueLocation::AssignedDoubleRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptStoreRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::StraightForwardRegisterAllocator::MarkAsClobbered(), v8::internal::maglev::ToDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister(), and v8::internal::maglev::StraightForwardRegisterAllocator::VerifyInputs().
GetFloatRegister()
FloatRegister v8::internal::compiler::LocationOperand::GetFloatRegister () const [inline]
Definition at line 528 of file instruction.h.
                                         {
    DCHECK(IsFloatRegister());
    return FloatRegister::from_code(register_code());
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::from_code(), and v8::internal::compiler::InstructionOperand::IsFloatRegister().
Referenced by v8::internal::compiler::InstructionOperandConverter::ToFloatRegister().
GetRegister()
Register v8::internal::compiler::LocationOperand::GetRegister () const [inline]
Definition at line 523 of file instruction.h.
                               {
    DCHECK(IsRegister());
    return Register::from_code(register_code());
  }
References v8::internal::DCHECK(), v8::internal::Register::from_code(), and v8::internal::compiler::InstructionOperand::IsRegister().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), v8::internal::maglev::ValueLocation::AssignedGeneralRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptStoreRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::StraightForwardRegisterAllocator::MarkAsClobbered(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::maglev::detail::PushInput(), v8::internal::maglev::ToRegister(), v8::internal::compiler::InstructionOperandConverter::ToRegister(), and v8::internal::maglev::StraightForwardRegisterAllocator::VerifyInputs().
GetSimd128Register()
Simd128Register v8::internal::compiler::LocationOperand::GetSimd128Register () const [inline]
Definition at line 541 of file instruction.h.
                                             {
    DCHECK(IsSimd128Register());
    return Simd128Register::from_code(register_code());
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< Simd128Register, kSimd128AfterLast >::from_code(), and v8::internal::compiler::InstructionOperand::IsSimd128Register().
Referenced by v8::internal::compiler::InstructionOperandConverter::ToSimd128Register().
index()
int v8::internal::compiler::LocationOperand::index () const [inline]
Definition at line 513 of file instruction.h.
                    {
    DCHECK(IsStackSlot() || IsFPStackSlot());
    return static_cast<int64_t>(value_) >> IndexField::kShift;
  }
References v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap(), v8::internal::compiler::BlockAssessments::CheckReferenceMap(), v8::internal::maglev::MaglevAssembler::GetFramePointerOffsetForStackSlot(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::InstructionOperand::InterferesWith(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::compiler::ReferenceMap::RecordReference(), v8::internal::compiler::CodeGenerator::RecordSafepoint(), and v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse().
IsCompatible()
bool v8::internal::compiler::LocationOperand::IsCompatible (LocationOperand * op)
Definition at line 143 of file instruction.cc.
                                                      {
  if (IsRegister() || IsStackSlot()) {
    return op->IsRegister() || op->IsStackSlot();
  } else if (kFPAliasing != AliasingKind::kCombine) {
    // A backend may choose to generate the same instruction sequence regardless
    // of the FP representation. As a result, we can relax the compatibility and
    // allow a Double to be moved in a Float for example. However, this is only
    // allowed if registers do not overlap.
    return (IsFPRegister() || IsFPStackSlot()) &&
           (op->IsFPRegister() || op->IsFPStackSlot());
  } else if (IsFloatRegister() || IsFloatStackSlot()) {
    return op->IsFloatRegister() || op->IsFloatStackSlot();
  } else if (IsDoubleRegister() || IsDoubleStackSlot()) {
    return op->IsDoubleRegister() || op->IsDoubleStackSlot();
  } else {
    return (IsSimd128Register() || IsSimd128StackSlot()) &&
           (op->IsSimd128Register() || op->IsSimd128StackSlot());
  }
}
References v8::internal::compiler::InstructionOperand::IsDoubleRegister(), v8::internal::compiler::InstructionOperand::IsDoubleStackSlot(), v8::internal::compiler::InstructionOperand::IsFloatRegister(), v8::internal::compiler::InstructionOperand::IsFloatStackSlot(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsSimd128Register(), v8::internal::compiler::InstructionOperand::IsSimd128StackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kCombine, and v8::internal::kFPAliasing.
IsSupportedRepresentation()
static bool v8::internal::compiler::LocationOperand::IsSupportedRepresentation (MachineRepresentation rep) [inline], [static]
Definition at line 567 of file instruction.h.
                                                                   {
    switch (rep) {
      case MachineRepresentation::kWord32:
      case MachineRepresentation::kWord64:
      case MachineRepresentation::kFloat32:
      case MachineRepresentation::kFloat64:
      case MachineRepresentation::kSimd128:
      case MachineRepresentation::kSimd256:
      case MachineRepresentation::kTaggedSigned:
      case MachineRepresentation::kTaggedPointer:
      case MachineRepresentation::kTagged:
      case MachineRepresentation::kCompressedPointer:
      case MachineRepresentation::kCompressed:
      case MachineRepresentation::kProtectedPointer:
      case MachineRepresentation::kSandboxedPointer:
        return true;
      case MachineRepresentation::kBit:
      case MachineRepresentation::kWord8:
      case MachineRepresentation::kWord16:
      case MachineRepresentation::kFloat16:
      case MachineRepresentation::kNone:
        return false;
      case MachineRepresentation::kMapWord:
      case MachineRepresentation::kIndirectPointer:
      case MachineRepresentation::kFloat16RawBits:
        UNREACHABLE();
    }
  }
References v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::LiveRange::LiveRange().
location_kind()
LocationKind v8::internal::compiler::LocationOperand::location_kind () const [inline]
Definition at line 559 of file instruction.h.
                                     {
    return LocationKindField::decode(value_);
  }
References v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind(), v8::internal::compiler::InstructionOperand::InterferesWith(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::compiler::InstructionOperand::IsDoubleStackSlot(), v8::internal::compiler::InstructionOperand::IsFloatStackSlot(), v8::internal::compiler::InstructionOperand::IsSimd128StackSlot(), and v8::internal::compiler::InstructionOperand::IsSimd256StackSlot().
register_code()
int v8::internal::compiler::LocationOperand::register_code () const [inline]
Definition at line 518 of file instruction.h.
                            {
    DCHECK(IsRegister() || IsFPRegister());
    return static_cast<int64_t>(value_) >> IndexField::kShift;
  }
References v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsRegister(), and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::UsePosition::HintRegister(), v8::internal::compiler::InstructionOperand::InterferesWith(), v8::internal::compiler::LiveRangeBuilder::LiveRangeFor(), v8::internal::compiler::operator<<(), and v8::internal::compiler::GraphC1Visualizer::PrintLiveRange().
representation()
MachineRepresentation v8::internal::compiler::LocationOperand::representation () const [inline]
Definition at line 563 of file instruction.h.
                                               {
    return RepresentationField::decode(value_);
  }
References v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::MoveOperands::CheckPointerCompressionConsistency(), v8::internal::compiler::BlockAssessments::CheckReferenceMap(), v8::internal::compiler::InstructionOperand::GetCanonicalizedValue(), v8::internal::maglev::MaglevAssembler::GetFramePointerOffsetForStackSlot(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind(), v8::internal::compiler::InstructionOperand::InterferesWith(), v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::Is32BitOperand(), v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::Is32BitOperand(), v8::anonymous_namespace{code-generator-riscv.cc}::Is32BitOperand(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::Is32BitOperand(), v8::internal::compiler::S390OperandConverter::Is32BitOperand(), v8::internal::compiler::S390OperandConverter::Is64BitOperand(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::Is64BitsWide(), v8::internal::compiler::InstructionOperand::IsDoubleRegister(), v8::internal::compiler::InstructionOperand::IsDoubleStackSlot(), v8::internal::compiler::InstructionOperand::IsFloatRegister(), v8::internal::compiler::InstructionOperand::IsFloatStackSlot(), v8::internal::compiler::InstructionOperand::IsSimd128Register(), v8::internal::compiler::InstructionOperand::IsSimd128StackSlot(), v8::internal::compiler::InstructionOperand::IsSimd256Register(), v8::internal::compiler::InstructionOperand::IsSimd256StackSlot(), v8::internal::compiler::BlockAssessments::IsStaleReferenceStackSlot(), v8::internal::compiler::LiveRangeBuilder::LiveRangeFor(), v8::internal::compiler::operator<<(), v8::internal::compiler::GapResolver::PerformCycle(), v8::internal::compiler::CodeGenerator::Push(), v8::internal::compiler::SignExtend(), v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc