v8::internal::wasm::ValueType Class Reference
#include <value-type.h>
Public Member Functions
constexpr ValueType AsNonNull () const
constexpr ValueType AsNullable (Nullability nullable=kNullable) const
constexpr ValueType AsExact (Exactness exact=Exactness::kExact) const
constexpr ValueType AsExactIfIndexed (Exactness exact) const
ValueType AsExactIfEnabled (WasmEnabledFeatures enabled, Exactness exact=Exactness::kExact) const
constexpr ValueType AsNonShared () const
constexpr ValueType Unpacked () const
constexpr CanonicalValueType Canonicalize (CanonicalTypeIndex index) const
constexpr HeapType::Representation heap_representation () const
constexpr bool is_reference_to (HeapType::Representation repr) const
constexpr bool is_reference_to (GenericKind kind) const
constexpr bool operator== (ValueType other) const
constexpr HeapType heap_type () const
constexpr ModuleTypeIndex ref_index () const
Static Public Member Functions
static constexpr ValueType Primitive (NumericKind kind)
static constexpr ValueType Generic (GenericKind kind, Nullability nullable, bool shared)
static constexpr ValueType Ref (ModuleTypeIndex index, bool shared, RefTypeKind kind)
static constexpr ValueType Ref (HeapType type)
static constexpr ValueType RefNull (ModuleTypeIndex index, bool shared, RefTypeKind kind)
static constexpr ValueType RefNull (HeapType type)
static constexpr ValueType RefMaybeNull (ModuleTypeIndex index, Nullability nullable, bool shared, RefTypeKind kind)
static constexpr ValueType RefMaybeNull (HeapType type, Nullability nullable)
static constexpr ValueType FromRawBitField (uint32_t bits)
static constexpr ValueType Primitive (ValueKind kind)
static ValueType For (MachineType type)
Additional Inherited Members
Detailed Description
Definition at line 885 of file value-type.h.
Member Function Documentation
AsExact()
constexpr ValueType v8::internal::wasm::ValueType::AsExact (Exactness exact = Exactness::kExact) const [inline], [constexpr]
Definition at line 931 of file value-type.h.
                                                                       {
    DCHECK(exact == Exactness::kAnySubtype || has_index());
    return ValueType{ValueTypeBase(
        value_type_impl::IsExactField::update(raw_bit_field(), exact))};
  }
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::kAnySubtype, v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by AsExactIfEnabled(), AsExactIfIndexed(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopDescriptor(), and v8::internal::wasm::Union().
AsExactIfEnabled()
ValueType v8::internal::wasm::ValueType::AsExactIfEnabled (WasmEnabledFeatures enabled, Exactness exact = Exactness::kExact) const [inline]
Definition at line 944 of file value-type.h.
                                                                      {
    if V8_LIKELY (!enabled.has_custom_descriptors()) return *this;
    return AsExact(exact);
  }
References AsExact(), and V8_LIKELY.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE().
AsExactIfIndexed()
constexpr ValueType v8::internal::wasm::ValueType::AsExactIfIndexed (Exactness exact) const [inline], [constexpr]
Definition at line 937 of file value-type.h.
                                                              {
    if (!has_index()) return *this;
    return AsExact(exact);
  }
References AsExact(), and v8::internal::wasm::ValueTypeBase::has_index().
Referenced by v8::internal::wasm::Union().
AsNonNull()
constexpr ValueType v8::internal::wasm::ValueType::AsNonNull () const [inline], [constexpr]
Definition at line 924 of file value-type.h.
{ return AsNullable(kNonNullable); }
References AsNullable(), and v8::internal::wasm::kNonNullable.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull().
AsNonShared()
constexpr ValueType v8::internal::wasm::ValueType::AsNonShared () const [inline], [constexpr]
Definition at line 950 of file value-type.h.
                                          {
    if (!is_ref()) return *this;
    return ValueType{ValueTypeBase(
        value_type_impl::IsSharedField::update(raw_bit_field(), false))};
  }
References v8::internal::wasm::ValueTypeBase::is_ref(), v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck().
AsNullable()
constexpr ValueType v8::internal::wasm::ValueType::AsNullable (Nullability nullable = kNullable) const [inline], [constexpr]
Definition at line 925 of file value-type.h.
                                                                         {
    DCHECK(!is_numeric());
    return ValueType{ValueTypeBase(
        value_type_impl::IsNullableField::update(raw_bit_field(), nullable))};
  }
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::is_numeric(), v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by AsNonNull(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::AsNullable(), v8::internal::wasm::Intersection(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), and v8::internal::wasm::Union().
Canonicalize()
constexpr CanonicalValueType v8::internal::wasm::ValueType::Canonicalize (CanonicalTypeIndex index) const [constexpr]
Definition at line 1102 of file value-type.h.
                                    {
  DCHECK(has_index());
  return CanonicalValueType{ValueTypeBase(
      value_type_impl::PayloadField::update(raw_bit_field(), index.index))};
}
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::index, v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::WasmModule::canonical_type().
For()
static ValueType v8::internal::wasm::ValueType::For (MachineType type) [inline], [static]
Definition at line 988 of file value-type.h.
                                         {
    switch (type.representation()) {
      case MachineRepresentation::kWord8:
      case MachineRepresentation::kWord16:
      case MachineRepresentation::kWord32:
        return Primitive(NumericKind::kI32);
      case MachineRepresentation::kWord64:
        return Primitive(NumericKind::kI64);
      case MachineRepresentation::kFloat32:
        return Primitive(NumericKind::kF32);
      case MachineRepresentation::kFloat64:
        return Primitive(NumericKind::kF64);
      case MachineRepresentation::kTaggedPointer:
        return Generic(GenericKind::kAny, kNullable, kNotShared);
      case MachineRepresentation::kSimd128:
        return Primitive(NumericKind::kS128);
      default:
        UNREACHABLE();
    }
  }
References Generic(), v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::wasm::kNotShared, v8::internal::wasm::kNullable, v8::internal::kSimd128, v8::internal::kTaggedPointer, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, Primitive(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
FromRawBitField()
static constexpr ValueType v8::internal::wasm::ValueType::FromRawBitField (uint32_t bits) [inline], [static], [constexpr]
Definition at line 920 of file value-type.h.
                                                            {
    return ValueType{ValueTypeBase(bits)};
  }
References v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::array_fill_wrapper(), v8::internal::wasm::Handlers< Compressed >::RefCast(), v8::internal::wasm::Handlers< Compressed >::RefTest(), v8::internal::wasm::Handlers< Compressed >::s2s_AssertNotNullTypecheck(), v8::internal::wasm::Handlers< Compressed >::s2s_AssertNullTypecheck(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_RefNull(), v8::internal::TRUSTED_POINTER_ACCESSORS(), v8::internal::WasmTableObject::unsafe_type(), and v8::internal::wasm::WasmInstruction::Optional::Block::value_type().
Generic()
static constexpr ValueType v8::internal::wasm::ValueType::Generic (GenericKind kind, Nullability nullable, bool shared) [inline], [static], [constexpr]
Definition at line 890 of file value-type.h.
                                                  {
    return ValueType{ValueTypeBase(kind, nullable, shared)};
  }
References v8::internal::wasm::ValueTypeBase::kind(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by For(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseAnyConvertExtern(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseExternConvertAny(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseRefCast().
heap_representation()
constexpr HeapType::Representation v8::internal::wasm::ValueType::heap_representation () const [inline], [constexpr]
Definition at line 975 of file value-type.h.
                                                               {
    return static_cast<HeapType::Representation>(raw_heap_representation(true));
  }
References v8::internal::wasm::ValueTypeBase::raw_heap_representation().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastAbstract(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastFailAbstract(), is_reference_to(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckAbstract(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefCastAbstract(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefTestAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RejectSharedWasmObjectsIfUnshared(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::TrapOnSharedWasmObjectsIfUnshared().
heap_type()
constexpr HeapType v8::internal::wasm::ValueType::heap_type () const [inline], [constexpr]
Definition at line 1013 of file value-type.h.
                                       {
    DCHECK(!is_numeric());
    return HeapType{*this};
  }
References v8::internal::DCHECK(), and v8::internal::wasm::ValueTypeBase::is_numeric().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_cast(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::LocalDeclEncoder::Emit(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), v8::internal::wasm::Intersection(), v8::internal::wasm::IsSubtypeOfImpl(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayLen(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseRefCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefCast(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefCastImpl(), and v8::internal::wasm::Union().
is_reference_to() [1/2]
constexpr bool v8::internal::wasm::ValueType::is_reference_to (GenericKind kind) const [inline], [constexpr]
Definition at line 984 of file value-type.h.
                                                         {
    return ValueTypeBase::is_reference_to(kind);
  }
References v8::internal::wasm::ValueTypeBase::is_reference_to(), and v8::internal::wasm::ValueTypeBase::kind().
is_reference_to() [2/2]
constexpr bool v8::internal::wasm::ValueType::is_reference_to (HeapType::Representation repr) const [inline], [constexpr]
Definition at line 980 of file value-type.h.
                                                                    {
    return is_ref() && heap_representation() == repr;
  }
References heap_representation(), and v8::internal::wasm::ValueTypeBase::is_ref().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseAnyConvertExtern(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), and v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck().
operator==()
constexpr bool v8::internal::wasm::ValueType::operator== (ValueType other) const [inline], [constexpr]
Definition at line 1009 of file value-type.h.
                                                   {
    return bit_field_ == other.bit_field_;
  }
References v8::internal::wasm::ValueTypeBase::bit_field_.
Primitive() [1/2]
static constexpr ValueType v8::internal::wasm::ValueType::Primitive (NumericKind kind) [inline], [static], [constexpr]
Definition at line 887 of file value-type.h.
                                                         {
    return ValueType{ValueTypeBase(kind)};
  }
References v8::internal::wasm::ValueTypeBase::kind(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::block(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_if(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_null(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_table(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call_indirect(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call_ref(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop(), For(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::global_op(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::if_(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::local_op(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::loop(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::select_with_type(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_block(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_block(), and Unpacked().
Primitive() [2/2]
static constexpr ValueType v8::internal::wasm::ValueType::Primitive (ValueKind kind) [inline], [static], [constexpr]
Definition at line 970 of file value-type.h.
                                                       {
    return ValueType{ValueTypeBase::Primitive(kind)};
  }
References v8::internal::wasm::ValueTypeBase::kind(), and v8::internal::wasm::ValueTypeBase::Primitive().
Ref() [1/2]
static constexpr ValueType v8::internal::wasm::ValueType::Ref (HeapType type) [inline], [static], [constexpr]
Definition at line 899 of file value-type.h.
                                                {
    return ValueType{type}.AsNonNull();
  }
References v8::internal::tracing::type.
Ref() [2/2]
static constexpr ValueType v8::internal::wasm::ValueType::Ref (ModuleTypeIndex index, bool shared, RefTypeKind kind) [inline], [static], [constexpr]
Definition at line 894 of file value-type.h.
                                                   {
    return ValueType{ValueTypeBase(index, kNonNullable, Exactness::kAnySubtype,
                                   shared, kind)};
  }
References v8::internal::index, v8::internal::wasm::kAnySubtype, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kNonNullable, and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::AddImportedStringImports(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature(), v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseRefCast(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateArray(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessRefFunc(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysFails().
ref_index()
constexpr ModuleTypeIndex v8::internal::wasm::ValueType::ref_index () const [inline], [constexpr]
Definition at line 1018 of file value-type.h.
                                              {
    return ModuleTypeIndex{raw_index()};
  }
References v8::internal::wasm::ValueTypeBase::raw_index().
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::WasmTableObject::canonical_type(), v8::internal::wasm::WasmModule::canonical_type(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), v8::internal::wasm::JSPrototypesSetup::IsDescriptorGlobal(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseRefCast(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefCast(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::UnionExactness().
RefMaybeNull() [1/2]
static constexpr ValueType v8::internal::wasm::ValueType::RefMaybeNull (HeapType type, Nullability nullable) [inline], [static], [constexpr]
Definition at line 916 of file value-type.h.
                                                                               {
    return ValueType{type}.AsNullable(nullable);
  }
References v8::internal::tracing::type.
RefMaybeNull() [2/2]
static constexpr ValueType v8::internal::wasm::ValueType::RefMaybeNull (ModuleTypeIndex index, Nullability nullable, bool shared, RefTypeKind kind) [inline], [static], [constexpr]
Definition at line 910 of file value-type.h.
                                                            {
    return ValueType{
        ValueTypeBase(index, nullable, Exactness::kAnySubtype, shared, kind)};
  }
References v8::internal::index, v8::internal::wasm::kAnySubtype, v8::internal::wasm::ValueTypeBase::kind(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AnnotateAsString(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_ref(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_cast(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCast(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastAbstract(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastDesc(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastDescFail(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastFail(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastFailAbstract(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::get_local_ref(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseRefCast(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefCastAbstract(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefTest(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefTestAbstract(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_ref(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_get(), and v8::internal::wasm::Union().
RefNull() [1/2]
static constexpr ValueType v8::internal::wasm::ValueType::RefNull (HeapType type) [inline], [static], [constexpr]
Definition at line 907 of file value-type.h.
                                                    {
    return ValueType{type}.AsNullable(kNullable);
  }
References v8::internal::wasm::kNullable, and v8::internal::tracing::type.
RefNull() [2/2]
static constexpr ValueType v8::internal::wasm::ValueType::RefNull (ModuleTypeIndex index, bool shared, RefTypeKind kind) [inline], [static], [constexpr]
Definition at line 902 of file value-type.h.
                                                       {
    return ValueType{
        ValueTypeBase(index, kNullable, Exactness::kAnySubtype, shared, kind)};
  }
References v8::internal::index, v8::internal::wasm::kAnySubtype, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kNullable, and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::AddImportedStringImports(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::wasm::ToNullSentinel(), v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysFails(), and v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysSucceeds().
Unpacked()
constexpr ValueType v8::internal::wasm::ValueType::Unpacked () const [inline], [constexpr]
Definition at line 956 of file value-type.h.
                                       {
    if (bit_field_ == static_cast<uint32_t>(NumericKind::kI8) ||
        bit_field_ == static_cast<uint32_t>(NumericKind::kI16)) {
      return Primitive(NumericKind::kI32);
    }
    if (bit_field_ == static_cast<uint32_t>(NumericKind::kF16)) {
      return Primitive(NumericKind::kF32);
    }
    return *this;
  }
References v8::internal::wasm::ValueTypeBase::bit_field_, and Primitive().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_fill(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayGet(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseStructGet(), v8::internal::compiler::WasmTyper::Reduce(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/value-type.h