v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency Class Reference
Public Member Functions
GlobalPropertyDependency (PropertyCellRef cell, PropertyCellType type, bool read_only)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const PropertyCellRef cell_
const PropertyCellType type_
const bool read_only_
Additional Inherited Members
Detailed Description
Definition at line 867 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
GlobalPropertyDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::GlobalPropertyDependency (PropertyCellRef cell, PropertyCellType type, bool read_only) [inline]
Definition at line 869 of file compilation-dependencies.cc.
      : CompilationDependency(kGlobalProperty),
        cell_(cell),
        type_(type),
        read_only_(read_only) {
    DCHECK_EQ(type_, cell_.property_details().cell_type());
    DCHECK_EQ(read_only_, cell_.property_details().IsReadOnly());
  }
References DCHECK_EQ.
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 901 of file compilation-dependencies.cc.
                                                                {
    const GlobalPropertyDependency* const zat = that->AsGlobalProperty();
    return cell_.equals(zat->cell_) && type_ == zat->type_ &&
           read_only_ == zat->read_only_;
  }
References cell_, read_only_, and type_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 896 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(cell_), static_cast<int>(type_), read_only_);
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 890 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(cell_.object(), DependentCode::kPropertyCellChangedGroup);
  }
References broker(), v8::internal::DependentCode::kPropertyCellChangedGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 879 of file compilation-dependencies.cc.
                                                    {
    DirectHandle<PropertyCell> cell = cell_.object();
    // The dependency is never valid if the cell is 'invalidated'. This is
    // marked by setting the value to the hole.
    if (cell->value() ==
        *(broker->isolate()->factory()->property_cell_hole_value())) {
      return false;
    }
    return type_ == cell->property_details().cell_type() &&
           read_only_ == cell->property_details().IsReadOnly();
  }
References broker().
Member Data Documentation
cell_
const PropertyCellRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::cell_ [private]
Definition at line 907 of file compilation-dependencies.cc.
Referenced by Equals().
read_only_
const bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::read_only_ [private]
Definition at line 909 of file compilation-dependencies.cc.
Referenced by Equals().
type_
const PropertyCellType v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::type_ [private]
Definition at line 908 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc