cppgc::internal::HeapRegistry Class Reference
#include <process-heap.h>
Classes
class Subscription
Public Types
using Storage = std::vector< HeapBase * >
Static Public Member Functions
static HeapBase * TryFromManagedPointer (const void *needle)
static const Storage & GetRegisteredHeapsForTesting ()
Static Private Member Functions
static void RegisterHeap (HeapBase &)
static void UnregisterHeap (HeapBase &)
Detailed Description
Definition at line 72 of file process-heap.h.
Member Typedef Documentation
Storage
using cppgc::internal::HeapRegistry::Storage = std::vector<HeapBase*>
Definition at line 74 of file process-heap.h.
Member Function Documentation
GetRegisteredHeapsForTesting()
const HeapRegistry::Storage & cppgc::internal::HeapRegistry::GetRegisteredHeapsForTesting () [static]
Definition at line 69 of file process-heap.cc.
                                                                      {
  return GetHeapRegistryStorage();
}
References cppgc::internal::anonymous_namespace{process-heap.cc}::GetHeapRegistryStorage().
RegisterHeap()
void cppgc::internal::HeapRegistry::RegisterHeap (HeapBase & heap) [static], [private]
Definition at line 34 of file process-heap.cc.
                                              {
  v8::base::MutexGuard guard(g_heap_registry_mutex.Pointer());
  auto& storage = GetHeapRegistryStorage();
  DCHECK_EQ(storage.end(), std::find(storage.begin(), storage.end(), &heap));
  storage.push_back(&heap);
}
References DCHECK_EQ, cppgc::internal::anonymous_namespace{process-heap.cc}::g_heap_registry_mutex, cppgc::internal::anonymous_namespace{process-heap.cc}::GetHeapRegistryStorage(), and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by cppgc::internal::HeapRegistry::Subscription::Subscription().
TryFromManagedPointer()
HeapBase * cppgc::internal::HeapRegistry::TryFromManagedPointer (const void * needle) [static]
Definition at line 57 of file process-heap.cc.
                                                                {
  v8::base::MutexGuard guard(g_heap_registry_mutex.Pointer());
  for (auto* heap : GetHeapRegistryStorage()) {
    const auto address =
        heap->page_backend()->Lookup(reinterpret_cast<ConstAddress>(needle));
    if (address) return heap;
  }
  return nullptr;
}
References cppgc::internal::anonymous_namespace{process-heap.cc}::g_heap_registry_mutex, cppgc::internal::anonymous_namespace{process-heap.cc}::GetHeapRegistryStorage(), heap(), and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl().
UnregisterHeap()
void cppgc::internal::HeapRegistry::UnregisterHeap (HeapBase & heap) [static], [private]
Definition at line 43 of file process-heap.cc.
                                                {
  v8::base::MutexGuard guard(g_heap_registry_mutex.Pointer());
  // HeapRegistry requires access to PageBackend which means it must still
  // be present by the time a heap is removed from the registry.
  DCHECK_NOT_NULL(heap.page_backend());
  auto& storage = GetHeapRegistryStorage();
  const auto pos = std::find(storage.begin(), storage.end(), &heap);
  DCHECK_NE(storage.end(), pos);
  storage.erase(pos);
}
References DCHECK_NE, DCHECK_NOT_NULL, cppgc::internal::anonymous_namespace{process-heap.cc}::g_heap_registry_mutex, cppgc::internal::anonymous_namespace{process-heap.cc}::GetHeapRegistryStorage(), and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by cppgc::internal::HeapRegistry::Subscription::~Subscription().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/process-heap.h
/mnt/V8SourceCode/src/heap/cppgc/process-heap.cc