v8::internal::Relocatable Class Reference
#include <objects.h>
Public Member Functions
Relocatable (Isolate *isolate)
virtual ~Relocatable ()
virtual void IterateInstance (RootVisitor *v)
virtual void PostGarbageCollection ()
Static Public Member Functions
static void PostGarbageCollectionProcessing (Isolate *isolate)
static int ArchiveSpacePerThread ()
static char * ArchiveState (Isolate *isolate, char *to)
static char * RestoreState (Isolate *isolate, char *from)
static void Iterate (Isolate *isolate, RootVisitor *v)
static void Iterate (RootVisitor *v, Relocatable *top)
static char * Iterate (RootVisitor *v, char *t)
Private Attributes
Isolate * isolate_
Relocatable * prev_
Detailed Description
Definition at line 882 of file objects.h.
Constructor & Destructor Documentation
Relocatable()
v8::internal::Relocatable::Relocatable (Isolate * isolate) [inline], [explicit]
Definition at line 2027 of file objects-inl.h.
                                         {
  isolate_ = isolate;
  prev_ = isolate->relocatable_top();
  isolate->set_relocatable_top(this);
}
References isolate_, and prev_.
 Relocatable()
v8::internal::Relocatable::~Relocatable () [inline], [virtual]
Definition at line 2033 of file objects-inl.h.
                          {
  DCHECK_EQ(isolate_->relocatable_top(), this);
  isolate_->set_relocatable_top(prev_);
}
References DCHECK_EQ, isolate_, and prev_.
Member Function Documentation
ArchiveSpacePerThread()
int v8::internal::Relocatable::ArchiveSpacePerThread () [static]
Definition at line 4125 of file objects.cc.
{ return sizeof(Relocatable*); }
Referenced by v8::internal::ArchiveSpacePerThread(), ArchiveState(), Iterate(), and RestoreState().
ArchiveState()
char * v8::internal::Relocatable::ArchiveState (Isolate * isolate, char * to) [static]
Definition at line 4128 of file objects.cc.
                                                          {
  *reinterpret_cast<Relocatable**>(to) = isolate->relocatable_top();
  isolate->set_relocatable_top(nullptr);
  return to + ArchiveSpacePerThread();
}
References ArchiveSpacePerThread().
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread().
Iterate() [1/3]
void v8::internal::Relocatable::Iterate (Isolate * isolate, RootVisitor * v) [static]
Definition at line 4146 of file objects.cc.
                                                          {
  Iterate(v, isolate->relocatable_top());
}
Referenced by v8::internal::ThreadManager::Iterate(), Iterate(), and v8::internal::Heap::IterateRoots().
Iterate() [2/3]
char * v8::internal::Relocatable::Iterate (RootVisitor * v, char * t) [static]
Definition at line 4140 of file objects.cc.
                                                               {
  Relocatable* top = *reinterpret_cast<Relocatable**>(thread_storage);
  Iterate(v, top);
  return thread_storage + ArchiveSpacePerThread();
}
References ArchiveSpacePerThread(), and Iterate().
Iterate() [3/3]
void v8::internal::Relocatable::Iterate (RootVisitor * v, Relocatable * top) [static]
Definition at line 4150 of file objects.cc.
                                                          {
  Relocatable* current = top;
  while (current != nullptr) {
    current->IterateInstance(v);
    current = current->prev_;
  }
}
References IterateInstance(), and prev_.
IterateInstance()
virtual void v8::internal::Relocatable::IterateInstance (RootVisitor * v) [inline], [virtual]
Reimplemented in v8::internal::anonymous_namespace{builtins-api.cc}::RelocatableArguments, v8::internal::CustomArguments< T >, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >, and v8::internal::CustomArguments< FunctionCallbackInfo< Value > >.
Definition at line 886 of file objects.h.
{}
Referenced by Iterate().
PostGarbageCollection()
virtual void v8::internal::Relocatable::PostGarbageCollection () [inline], [virtual]
Reimplemented in v8::internal::FlatStringReader.
Definition at line 887 of file objects.h.
{}
Referenced by PostGarbageCollectionProcessing().
PostGarbageCollectionProcessing()
void v8::internal::Relocatable::PostGarbageCollectionProcessing (Isolate * isolate) [static]
Definition at line 4116 of file objects.cc.
                                                                  {
  Relocatable* current = isolate->relocatable_top();
  while (current != nullptr) {
    current->PostGarbageCollection();
    current = current->prev_;
  }
}
References PostGarbageCollection(), and prev_.
Referenced by v8::internal::Heap::PerformGarbageCollection().
RestoreState()
char * v8::internal::Relocatable::RestoreState (Isolate * isolate, char * from) [static]
Definition at line 4135 of file objects.cc.
                                                            {
  isolate->set_relocatable_top(*reinterpret_cast<Relocatable**>(from));
  return from + ArchiveSpacePerThread();
}
References ArchiveSpacePerThread().
Referenced by v8::internal::ThreadManager::RestoreThread().
Member Data Documentation
isolate_
Isolate* v8::internal::Relocatable::isolate_ [private]
Definition at line 898 of file objects.h.
Referenced by Relocatable(), and ~Relocatable().
prev_
Relocatable* v8::internal::Relocatable::prev_ [private]
Definition at line 899 of file objects.h.
Referenced by Iterate(), PostGarbageCollectionProcessing(), Relocatable(), and ~Relocatable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/objects.h
/mnt/V8SourceCode/src/objects/objects-inl.h
/mnt/V8SourceCode/src/objects/objects.cc