v8::internal::PreparseData Class Reference
#include <shared-function-info.h>
Classes
class BodyDescriptor
Public Member Functions
int inner_start_offset () const
ObjectSlot inner_data_start () const
uint8_t get (int index) const
void set (int index, uint8_t value)
void copy_in (int index, const uint8_t *buffer, int length)
Tagged< PreparseData > get_child (int index) const
void set_child (int index, Tagged< PreparseData > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void clear_padding ()
Static Public Member Functions
static int InnerOffset (int data_length)
static int SizeFor (int data_length, int children_length)
Static Public Attributes
static const int kDataStartOffset = kSize
Private Member Functions
Tagged< Object > get_child_raw (int index) const
Detailed Description
Definition at line 78 of file shared-function-info.h.
Member Function Documentation
clear_padding()
void v8::internal::PreparseData::clear_padding () [inline]
Definition at line 52 of file shared-function-info-inl.h.
                                 {
  int data_end_offset = kDataStartOffset + data_length();
  int padding_size = inner_start_offset() - data_end_offset;
  DCHECK_LE(0, padding_size);
  if (padding_size == 0) return;
  memset(reinterpret_cast<void*>(address() + data_end_offset), 0, padding_size);
}
References DCHECK_LE, inner_start_offset(), and kDataStartOffset.
copy_in()
void v8::internal::PreparseData::copy_in (int index, const uint8_t * buffer, int length) [inline]
Definition at line 74 of file shared-function-info-inl.h.
                                                                       {
  DCHECK(index >= 0 && length >= 0 && length <= kMaxInt - index &&
         index + length <= this->data_length());
  Address dst_addr = field_address(kDataStartOffset + index * kByteSize);
  memcpy(reinterpret_cast<void*>(dst_addr), buffer, length);
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::kByteSize, kDataStartOffset, v8::internal::kMaxInt, and v8::internal::length.
get()
uint8_t v8::internal::PreparseData::get (int index) const [inline]
Definition at line 60 of file shared-function-info-inl.h.
                                         {
  DCHECK_LE(0, index);
  DCHECK_LT(index, data_length());
  int offset = kDataStartOffset + index * kByteSize;
  return ReadField<uint8_t>(offset);
}
References DCHECK_LE, DCHECK_LT, v8::internal::index, v8::internal::kByteSize, and kDataStartOffset.
get_child()
Tagged< PreparseData > v8::internal::PreparseData::get_child (int index) const [inline]
Definition at line 81 of file shared-function-info-inl.h.
                                                            {
  return Cast<PreparseData>(get_child_raw(index));
}
References get_child_raw(), and v8::internal::index.
get_child_raw()
Tagged< Object > v8::internal::PreparseData::get_child_raw (int index) const [inline], [private]
Definition at line 85 of file shared-function-info-inl.h.
                                                          {
  DCHECK_LE(0, index);
  DCHECK_LT(index, this->children_length());
  int offset = inner_start_offset() + index * kTaggedSize;
  return RELAXED_READ_FIELD(*this, offset);
}
References DCHECK_LE, DCHECK_LT, v8::internal::index, inner_start_offset(), v8::internal::kTaggedSize, and RELAXED_READ_FIELD.
Referenced by get_child().
inner_data_start()
ObjectSlot v8::internal::PreparseData::inner_data_start () const [inline]
Definition at line 48 of file shared-function-info-inl.h.
                                                {
  return RawField(inner_start_offset());
}
References inner_start_offset().
inner_start_offset()
int v8::internal::PreparseData::inner_start_offset () const [inline]
Definition at line 44 of file shared-function-info-inl.h.
                                           {
  return InnerOffset(data_length());
}
Referenced by clear_padding(), get_child_raw(), inner_data_start(), and set_child().
InnerOffset()
static int v8::internal::PreparseData::InnerOffset (int data_length) [inline], [static]
Definition at line 102 of file shared-function-info.h.
                                          {
    return RoundUp(kDataStartOffset + data_length * kByteSize, kTaggedSize);
  }
References v8::internal::kByteSize, kDataStartOffset, v8::internal::kTaggedSize, and RoundUp().
Referenced by SizeFor().
set()
void v8::internal::PreparseData::set (int index, uint8_t value) [inline]
Definition at line 67 of file shared-function-info-inl.h.
                                               {
  DCHECK_LE(0, index);
  DCHECK_LT(index, data_length());
  int offset = kDataStartOffset + index * kByteSize;
  WriteField<uint8_t>(offset, value);
}
References DCHECK_LE, DCHECK_LT, v8::internal::index, v8::internal::kByteSize, kDataStartOffset, and v8::internal::value.
set_child()
void v8::internal::PreparseData::set_child (int index, Tagged< PreparseData > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 92 of file shared-function-info-inl.h.
                                                    {
  DCHECK_LE(0, index);
  DCHECK_LT(index, this->children_length());
  int offset = inner_start_offset() + index * kTaggedSize;
  RELAXED_WRITE_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, DCHECK_LE, DCHECK_LT, v8::internal::index, inner_start_offset(), v8::internal::kTaggedSize, mode(), RELAXED_WRITE_FIELD, and v8::internal::value.
SizeFor()
static int v8::internal::PreparseData::SizeFor (int data_length, int children_length) [inline], [static]
Definition at line 106 of file shared-function-info.h.
                                                           {
    return InnerOffset(data_length) + children_length * kTaggedSize;
  }
References InnerOffset(), and v8::internal::kTaggedSize.
Referenced by v8::internal::FactoryBase< Impl >::NewPreparseData(), v8::internal::HeapObject::SizeFromMap(), and v8::internal::PreparseData::BodyDescriptor::SizeOf().
Member Data Documentation
kDataStartOffset
const int v8::internal::PreparseData::kDataStartOffset = kSize [static]
Definition at line 98 of file shared-function-info.h.
Referenced by clear_padding(), copy_in(), get(), InnerOffset(), and set().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/shared-function-info.h
/mnt/V8SourceCode/src/objects/shared-function-info-inl.h