v8::internal::RootScavengeVisitor Class Reference
#include <scavenger.h>
Public Member Functions
RootScavengeVisitor (Scavenger &scavenger)
~RootScavengeVisitor () final
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) final
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
Private Member Functions
void ScavengePointer (FullObjectSlot p)
Private Attributes
Scavenger & scavenger_
Additional Inherited Members
Detailed Description
Definition at line 218 of file scavenger.h.
Constructor & Destructor Documentation
RootScavengeVisitor()
v8::internal::RootScavengeVisitor::RootScavengeVisitor (Scavenger & scavenger) [explicit]
Definition at line 1502 of file scavenger.cc.
    : scavenger_(scavenger) {}
 RootScavengeVisitor()
v8::internal::RootScavengeVisitor::~RootScavengeVisitor () [final]
Definition at line 1505 of file scavenger.cc.
{ scavenger_.Publish(); }
References v8::internal::Scavenger::Publish(), and scavenger_.
Member Function Documentation
ScavengePointer()
void v8::internal::RootScavengeVisitor::ScavengePointer (FullObjectSlot p) [private]
Definition at line 1490 of file scavenger.cc.
                                                          {
  Tagged<Object> object = *p;
#ifdef V8_ENABLE_DIRECT_HANDLE
  if (object.ptr() == kTaggedNullAddress) return;
#endif
  DCHECK(!HasWeakHeapObjectTag(object));
  DCHECK(!MapWord::IsPacked(object.ptr()));
  if (HeapLayout::InYoungGeneration(object)) {
    scavenger_.ScavengeObject(FullHeapObjectSlot(p), Cast<HeapObject>(object));
  }
}
References DCHECK, v8::internal::HasWeakHeapObjectTag(), and v8::internal::kTaggedNullAddress.
VisitRootPointer()
void v8::internal::RootScavengeVisitor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 1474 of file scavenger.cc.
                                                             {
  DCHECK(!HasWeakHeapObjectTag(*p));
  DCHECK(!MapWord::IsPacked((*p).ptr()));
  ScavengePointer(p);
}
References DCHECK, and v8::internal::HasWeakHeapObjectTag().
VisitRootPointers()
void v8::internal::RootScavengeVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 1481 of file scavenger.cc.
                                                                {
  // Copy all HeapObject pointers in [start, end)
  for (FullObjectSlot p = start; p < end; ++p) {
    ScavengePointer(p);
  }
}
References v8::internal::compiler::end().
Member Data Documentation
scavenger_
Scavenger& v8::internal::RootScavengeVisitor::scavenger_ [private]
Definition at line 231 of file scavenger.h.
Referenced by ~RootScavengeVisitor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/scavenger.h
/mnt/V8SourceCode/src/heap/scavenger.cc