v8::internal::interpreter::ControlFlowBuilder Class Reference
#include <control-flow-builders.h>
Public Member Functions
ControlFlowBuilder (BytecodeArrayBuilder *builder)
ControlFlowBuilder (const ControlFlowBuilder &)=delete
ControlFlowBuilder & operator= (const ControlFlowBuilder &)=delete
virtual ~ControlFlowBuilder ()=default
Protected Member Functions
BytecodeArrayBuilder * builder () const
Private Attributes
BytecodeArrayBuilder * builder_
Detailed Description
Definition at line 22 of file control-flow-builders.h.
Constructor & Destructor Documentation
ControlFlowBuilder() [1/2]
v8::internal::interpreter::ControlFlowBuilder::ControlFlowBuilder (BytecodeArrayBuilder * builder) [inline], [explicit]
Definition at line 24 of file control-flow-builders.h.
      : builder_(builder) {}
ControlFlowBuilder() [2/2]
v8::internal::interpreter::ControlFlowBuilder::ControlFlowBuilder (const ControlFlowBuilder &) [delete]
 ControlFlowBuilder()
virtual v8::internal::interpreter::ControlFlowBuilder::~ControlFlowBuilder () [virtual], [default]
Member Function Documentation
builder()
BytecodeArrayBuilder* v8::internal::interpreter::ControlFlowBuilder::builder () const [inline], [protected]
Definition at line 31 of file control-flow-builders.h.
{ return builder_; }
Referenced by v8::internal::interpreter::TryFinallyBuilder::BeginFinally(), v8::internal::interpreter::TryFinallyBuilder::BeginHandler(), v8::internal::interpreter::TryCatchBuilder::BeginTry(), v8::internal::interpreter::TryFinallyBuilder::BeginTry(), v8::internal::interpreter::BreakableControlFlowBuilder::BindBreakTarget(), v8::internal::interpreter::SwitchBuilder::BindCaseTargetForCompareJump(), v8::internal::interpreter::SwitchBuilder::BindCaseTargetForJumpTable(), v8::internal::interpreter::LoopBuilder::BindContinueTarget(), v8::internal::interpreter::SwitchBuilder::BindDefault(), v8::internal::interpreter::LoopBuilder::BindLoopEnd(), v8::internal::interpreter::ConditionalControlFlowBuilder::Else(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::ElseAt(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJump(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfFalse(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfForInDone(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfTrue(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfUndefined(), v8::internal::interpreter::SwitchBuilder::EmitJumpTableIfExists(), v8::internal::interpreter::TryCatchBuilder::EndCatch(), v8::internal::interpreter::TryCatchBuilder::EndTry(), v8::internal::interpreter::TryFinallyBuilder::EndTry(), v8::internal::interpreter::SwitchBuilder::JumpToCaseIfTrue(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::JumpToEnd(), v8::internal::interpreter::ConditionalControlFlowBuilder::JumpToEnd(), v8::internal::interpreter::LoopBuilder::JumpToHeader(), v8::internal::interpreter::TryFinallyBuilder::LeaveTry(), v8::internal::interpreter::LoopBuilder::LoopHeader(), v8::internal::interpreter::ConditionalControlFlowBuilder::Then(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::ThenAt(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::~ConditionalChainControlFlowBuilder(), and v8::internal::interpreter::ConditionalControlFlowBuilder::~ConditionalControlFlowBuilder().
operator=()
ControlFlowBuilder& v8::internal::interpreter::ControlFlowBuilder::operator= (const ControlFlowBuilder &) [delete]
Member Data Documentation
builder_
BytecodeArrayBuilder* v8::internal::interpreter::ControlFlowBuilder::builder_ [private]
Definition at line 34 of file control-flow-builders.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/control-flow-builders.h