v8::internal::TracingCpuProfilerImpl Class Reference
#include <tracing-cpu-profiler.h>
Public Member Functions
TracingCpuProfilerImpl (Isolate *)
~TracingCpuProfilerImpl () override
TracingCpuProfilerImpl (const TracingCpuProfilerImpl &)=delete
TracingCpuProfilerImpl & operator= (const TracingCpuProfilerImpl &)=delete
void OnTraceEnabled () final
void OnTraceDisabled () final
Private Member Functions
void StartProfiling ()
void StopProfiling ()
Private Attributes
Isolate * isolate_
std::unique_ptr< CpuProfiler > profiler_
bool profiling_enabled_
base::Mutex mutex_
Detailed Description
Definition at line 22 of file tracing-cpu-profiler.h.
Constructor & Destructor Documentation
TracingCpuProfilerImpl() [1/2]
v8::internal::TracingCpuProfilerImpl::TracingCpuProfilerImpl (Isolate * isolate) [explicit]
Definition at line 15 of file tracing-cpu-profiler.cc.
    : isolate_(isolate), profiling_enabled_(false) {
#if defined(V8_USE_PERFETTO)
  TrackEvent::AddSessionObserver(this);
  // Fire the observer if tracing is already in progress.
  if (TrackEvent::IsEnabled()) OnStart({});
#else
  V8::GetCurrentPlatform()->GetTracingController()->AddTraceStateObserver(this);
#endif
}
References v8::TracingController::AddTraceStateObserver(), v8::internal::V8::GetCurrentPlatform(), and v8::Platform::GetTracingController().
 TracingCpuProfilerImpl()
v8::internal::TracingCpuProfilerImpl::~TracingCpuProfilerImpl () [override]
Definition at line 26 of file tracing-cpu-profiler.cc.
                                                {
  StopProfiling();
#if defined(V8_USE_PERFETTO)
  TrackEvent::RemoveSessionObserver(this);
#else
  V8::GetCurrentPlatform()->GetTracingController()->RemoveTraceStateObserver(
      this);
#endif
}
References v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetTracingController(), v8::TracingController::RemoveTraceStateObserver(), and StopProfiling().
TracingCpuProfilerImpl() [2/2]
v8::internal::TracingCpuProfilerImpl::TracingCpuProfilerImpl (const TracingCpuProfilerImpl &) [delete]
Member Function Documentation
OnTraceDisabled()
void v8::internal::TracingCpuProfilerImpl::OnTraceDisabled () [final], [virtual]
Implements v8::TracingController::TraceStateObserver.
Definition at line 69 of file tracing-cpu-profiler.cc.
                                             {
#endif
  base::MutexGuard lock(&mutex_);
  if (!profiling_enabled_) return;
  profiling_enabled_ = false;
  isolate_->RequestInterrupt(
      [](v8::Isolate*, void* data) {
        reinterpret_cast<TracingCpuProfilerImpl*>(data)->StopProfiling();
      },
      this);
  // It could be a long time until the Isolate next runs any JS which could be
  // interrupted, and we'd rather not leave the sampler thread running during
  // that time, so also post a task to run any interrupts.
  V8::GetCurrentPlatform()
      ->GetForegroundTaskRunner(reinterpret_cast<v8::Isolate*>(isolate_))
      ->PostTask(std::make_unique<RunInterruptsTask>(isolate_));
}
References v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), isolate_, mutex_, profiling_enabled_, v8::internal::Isolate::RequestInterrupt(), and StopProfiling().
OnTraceEnabled()
void v8::internal::TracingCpuProfilerImpl::OnTraceEnabled () [final], [virtual]
Implements v8::TracingController::TraceStateObserver.
Definition at line 40 of file tracing-cpu-profiler.cc.
                                            {
#endif
  bool enabled;
  TRACE_EVENT_CATEGORY_GROUP_ENABLED(
      TRACE_DISABLED_BY_DEFAULT("v8.cpu_profiler"), &enabled);
  if (!enabled) return;
  profiling_enabled_ = true;
  isolate_->RequestInterrupt(
      [](v8::Isolate*, void* data) {
        reinterpret_cast<TracingCpuProfilerImpl*>(data)->StartProfiling();
      },
      this);
}
References isolate_, profiling_enabled_, v8::internal::Isolate::RequestInterrupt(), StartProfiling(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT_CATEGORY_GROUP_ENABLED.
operator=()
TracingCpuProfilerImpl& v8::internal::TracingCpuProfilerImpl::operator= (const TracingCpuProfilerImpl &) [delete]
StartProfiling()
void v8::internal::TracingCpuProfilerImpl::StartProfiling () [private]
Definition at line 87 of file tracing-cpu-profiler.cc.
                                            {
  base::MutexGuard lock(&mutex_);
  if (!profiling_enabled_ || profiler_) return;
  int sampling_interval_us = 100;
  profiler_.reset(new CpuProfiler(isolate_, kDebugNaming));
  profiler_->set_sampling_interval(
      base::TimeDelta::FromMicroseconds(sampling_interval_us));
  profiler_->StartProfiling("", {kLeafNodeLineNumbers});
}
References v8::base::TimeDelta::FromMicroseconds(), isolate_, v8::kDebugNaming, v8::kLeafNodeLineNumbers, mutex_, profiler_, and profiling_enabled_.
Referenced by OnTraceEnabled().
StopProfiling()
void v8::internal::TracingCpuProfilerImpl::StopProfiling () [private]
Definition at line 97 of file tracing-cpu-profiler.cc.
                                           {
  base::MutexGuard lock(&mutex_);
  if (!profiler_) return;
  profiler_->StopProfiling("");
  profiler_.reset();
}
References mutex_, and profiler_.
Referenced by OnTraceDisabled(), and ~TracingCpuProfilerImpl().
Member Data Documentation
isolate_
Isolate* v8::internal::TracingCpuProfilerImpl::isolate_ [private]
Definition at line 48 of file tracing-cpu-profiler.h.
Referenced by OnTraceDisabled(), OnTraceEnabled(), v8::internal::anonymous_namespace{tracing-cpu-profiler.cc}::RunInterruptsTask::Run(), and StartProfiling().
mutex_
base::Mutex v8::internal::TracingCpuProfilerImpl::mutex_ [private]
Definition at line 51 of file tracing-cpu-profiler.h.
Referenced by OnTraceDisabled(), StartProfiling(), and StopProfiling().
profiler_
std::unique_ptr<CpuProfiler> v8::internal::TracingCpuProfilerImpl::profiler_ [private]
Definition at line 49 of file tracing-cpu-profiler.h.
Referenced by StartProfiling(), and StopProfiling().
profiling_enabled_
bool v8::internal::TracingCpuProfilerImpl::profiling_enabled_ [private]
Definition at line 50 of file tracing-cpu-profiler.h.
Referenced by OnTraceDisabled(), OnTraceEnabled(), and StartProfiling().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/tracing-cpu-profiler.h
/mnt/V8SourceCode/src/profiler/tracing-cpu-profiler.cc