cppgc::internal::NormalPageSpace::LinearAllocationBuffer Class Reference
#include <heap-space.h>
Public Member Functions
Address Allocate (size_t alloc_size)
void Set (Address ptr, size_t size)
Address start () const
size_t size () const
Private Attributes
Address start_ = nullptr
size_t size_ = 0
Detailed Description
Definition at line 70 of file heap-space.h.
Member Function Documentation
Allocate()
Address cppgc::internal::NormalPageSpace::LinearAllocationBuffer::Allocate (size_t alloc_size) [inline]
Definition at line 72 of file heap-space.h.
                                        {
      DCHECK_GE(size_, alloc_size);
      Address result = start_;
      start_ += alloc_size;
      size_ -= alloc_size;
      return result;
    }
References DCHECK_GE, and v8::base::internal::result.
Referenced by cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow().
Set()
void cppgc::internal::NormalPageSpace::LinearAllocationBuffer::Set (Address ptr, size_t size) [inline]
Definition at line 80 of file heap-space.h.
                                       {
      start_ = ptr;
      size_ = size;
    }
References size().
size()
size_t cppgc::internal::NormalPageSpace::LinearAllocationBuffer::size () const [inline]
Definition at line 86 of file heap-space.h.
{ return size_; }
Referenced by cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), and cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress().
start()
Address cppgc::internal::NormalPageSpace::LinearAllocationBuffer::start () const [inline]
Definition at line 85 of file heap-space.h.
{ return start_; }
Member Data Documentation
size_
size_t cppgc::internal::NormalPageSpace::LinearAllocationBuffer::size_ = 0 [private]
Definition at line 90 of file heap-space.h.
start_
Address cppgc::internal::NormalPageSpace::LinearAllocationBuffer::start_ = nullptr [private]
Definition at line 89 of file heap-space.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/heap-space.h