v8::internal::ChunkedStream< Char > Class Template Reference
Classes
struct Chunk
Public Member Functions
ChunkedStream (ScriptCompiler::ExternalSourceStream *source)
ChunkedStream (const ChunkedStream &other) V8_NOEXCEPT
Range< Char > GetDataAt (size_t pos, RuntimeCallStats *stats, DisallowGarbageCollection *no_gc=nullptr)
Static Public Attributes
static const bool kCanBeCloned = true
static const bool kCanAccessHeap = false
Protected Attributes
std::shared_ptr< std::vector< struct Chunk > > chunks_
Private Member Functions
Chunk & FindChunk (size_t position, RuntimeCallStats *stats)
virtual void ProcessChunk (const uint8_t *data, size_t position, size_t length)
void FetchChunk (size_t position, RuntimeCallStats *stats)
Private Attributes
ScriptCompiler::ExternalSourceStream * source_
Detailed Description
template<typename Char>
class v8::internal::ChunkedStream< Char >
Definition at line 153 of file scanner-character-streams.cc.
Constructor & Destructor Documentation
ChunkedStream() [1/2]
template<typename Char >
v8::internal::ChunkedStream< Char >::ChunkedStream (ScriptCompiler::ExternalSourceStream * source) [inline], [explicit]
Definition at line 155 of file scanner-character-streams.cc.
      : source_(source), chunks_(std::make_shared<std::vector<Chunk>>()) {}
ChunkedStream() [2/2]
template<typename Char >
v8::internal::ChunkedStream< Char >::ChunkedStream (const ChunkedStream< Char > & other) [inline]
Definition at line 158 of file scanner-character-streams.cc.
      : source_(nullptr),
        chunks_(other.chunks_) {}
Member Function Documentation
FetchChunk()
template<typename Char >
void v8::internal::ChunkedStream< Char >::FetchChunk (size_t position, RuntimeCallStats * stats) [inline], [private]
Definition at line 212 of file scanner-character-streams.cc.
                                                            {
    // Cloned ChunkedStreams have a null source, and therefore can't fetch any
    // new data.
    DCHECK_NOT_NULL(source_);
    const uint8_t* data = nullptr;
    size_t length;
    {
      RCS_SCOPE(stats, RuntimeCallCounterId::kGetMoreDataCallback);
      length = source_->GetMoreData(&data);
    }
    ProcessChunk(data, position, length);
  }
References DCHECK_NOT_NULL, v8::ScriptCompiler::ExternalSourceStream::GetMoreData(), v8::internal::length, v8::internal::ChunkedStream< Char >::ProcessChunk(), RCS_SCOPE, and v8::internal::ChunkedStream< Char >::source_.
Referenced by v8::internal::ChunkedStream< Char >::FindChunk().
FindChunk()
template<typename Char >
Chunk& v8::internal::ChunkedStream< Char >::FindChunk (size_t position, RuntimeCallStats * stats) [inline], [private]
Definition at line 186 of file scanner-character-streams.cc.
                                                             {
    while (V8_UNLIKELY(chunks_->empty())) FetchChunk(size_t{0}, stats);
    // Walk forwards while the position is in front of the current chunk.
    while (position >= chunks_->back().end_position() &&
           chunks_->back().length > 0) {
      FetchChunk(chunks_->back().end_position(), stats);
    }
    // Walk backwards.
    for (auto reverse_it = chunks_->rbegin(); reverse_it != chunks_->rend();
         ++reverse_it) {
      if (reverse_it->position <= position) return *reverse_it;
    }
    UNREACHABLE();
  }
References v8::internal::ChunkedStream< Char >::chunks_, v8::internal::ChunkedStream< Char >::FetchChunk(), v8::internal::UNREACHABLE(), and V8_UNLIKELY.
Referenced by v8::internal::ChunkedStream< Char >::GetDataAt().
GetDataAt()
template<typename Char >
Range<Char> v8::internal::ChunkedStream< Char >::GetDataAt (size_t pos, RuntimeCallStats * stats, DisallowGarbageCollection * no_gc = nullptr) [inline]
Definition at line 164 of file scanner-character-streams.cc.
                                                                    {
    Chunk& chunk = FindChunk(pos, stats);
    size_t buffer_end = chunk.length;
    size_t buffer_pos = std::min(buffer_end, pos - chunk.position);
    return {&chunk.data.get()[buffer_pos], &chunk.data.get()[buffer_end]};
  }
References v8::internal::ChunkedStream< Char >::Chunk::data, v8::internal::ChunkedStream< Char >::FindChunk(), v8::internal::ChunkedStream< Char >::Chunk::length, and v8::internal::ChunkedStream< Char >::Chunk::position.
Referenced by v8::internal::Windows1252CharacterStream::ReadBlock().
ProcessChunk()
template<typename Char >
virtual void v8::internal::ChunkedStream< Char >::ProcessChunk (const uint8_t * data, size_t position, size_t length) [inline], [private], [virtual]
Definition at line 204 of file scanner-character-streams.cc.
                                           {
    // Incoming data has to be aligned to Char size.
    DCHECK_EQ(0, length % sizeof(Char));
    chunks_->emplace_back(reinterpret_cast<const Char*>(data), position,
                          length / sizeof(Char));
  }
References v8::internal::ChunkedStream< Char >::chunks_, DCHECK_EQ, and v8::internal::length.
Referenced by v8::internal::ChunkedStream< Char >::FetchChunk().
Member Data Documentation
chunks_
template<typename Char >
std::shared_ptr<std::vector<struct Chunk> > v8::internal::ChunkedStream< Char >::chunks_ [protected]
Definition at line 229 of file scanner-character-streams.cc.
Referenced by v8::internal::ChunkedStream< Char >::FindChunk(), and v8::internal::ChunkedStream< Char >::ProcessChunk().
kCanAccessHeap
template<typename Char >
const bool v8::internal::ChunkedStream< Char >::kCanAccessHeap = false [static]
Definition at line 173 of file scanner-character-streams.cc.
kCanBeCloned
template<typename Char >
const bool v8::internal::ChunkedStream< Char >::kCanBeCloned = true [static]
Definition at line 172 of file scanner-character-streams.cc.
source_
template<typename Char >
ScriptCompiler::ExternalSourceStream* v8::internal::ChunkedStream< Char >::source_ [private]
Definition at line 226 of file scanner-character-streams.cc.
Referenced by v8::internal::ChunkedStream< Char >::FetchChunk().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/scanner-character-streams.cc