v8::internal::Callable Class Reference
#include <callable.h>
Public Member Functions
Callable (Handle< Code > code, CallInterfaceDescriptor descriptor)
Handle< Code > code () const
CallInterfaceDescriptor descriptor () const
Private Attributes
const Handle< Code > code_
const CallInterfaceDescriptor descriptor_
Detailed Description
Definition at line 17 of file callable.h.
Constructor & Destructor Documentation
Callable()
v8::internal::Callable::Callable (Handle< Code > code, CallInterfaceDescriptor descriptor) [inline]
Definition at line 19 of file callable.h.
      : code_(code), descriptor_(descriptor) {}
Member Function Documentation
code()
Handle<Code> v8::internal::Callable::code () const [inline]
Definition at line 22 of file callable.h.
{ return code_; }
References code_.
Referenced by v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CallBuiltinForBigIntOp(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltinImpl(), v8::internal::compiler::CodeAssembler::CallBuiltinVoid(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltinWithVarStackArgs(), v8::internal::compiler::CodeAssembler::CallJS(), v8::internal::compiler::CodeAssembler::CallJSBuiltin(), v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::CodeAssembler::ConstructJS(), v8::internal::compiler::JSCallReducer::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::ArrayBuiltinsAssembler::TailCallArrayConstructorStub(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::TailCallBuiltinThenBytecodeDispatch(), v8::internal::compiler::CodeAssembler::TailCallJSBuiltin(), v8::internal::compiler::SimplifiedLowering::ToNumberCode(), v8::internal::compiler::SimplifiedLowering::ToNumberConvertBigIntCode(), and v8::internal::compiler::SimplifiedLowering::ToNumericCode().
descriptor()
CallInterfaceDescriptor v8::internal::Callable::descriptor () const [inline]
Definition at line 23 of file callable.h.
{ return descriptor_; }
References descriptor_.
Referenced by v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CallBuiltinForBigIntOp(), v8::internal::compiler::CodeAssembler::CallBuiltinVoid(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltinWithVarStackArgs(), v8::internal::compiler::CodeAssembler::CallJS(), v8::internal::compiler::CodeAssembler::CallJSBuiltin(), v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::CodeAssembler::ConstructJS(), v8::internal::compiler::CreateStubBuiltinContinuationFrameState(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumberOperator(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::TailCallBuiltinThenBytecodeDispatch(), v8::internal::compiler::CodeAssembler::TailCallJSBuiltin(), v8::internal::compiler::SimplifiedLowering::ToNumberConvertBigIntOperator(), v8::internal::compiler::SimplifiedLowering::ToNumberOperator(), and v8::internal::compiler::SimplifiedLowering::ToNumericOperator().
Member Data Documentation
code_
const Handle<Code> v8::internal::Callable::code_ [private]
Definition at line 26 of file callable.h.
Referenced by code().
descriptor_
const CallInterfaceDescriptor v8::internal::Callable::descriptor_ [private]
Definition at line 27 of file callable.h.
Referenced by descriptor().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/callable.h