v8::debug::Location Class Reference
Defines location inside script.
#include <interface-types.h>
Public Member Functions
Location (int line_number, int column_number)
Location ()
Create empty location.
int GetLineNumber () const
int GetColumnNumber () const
bool IsEmpty () const
Private Attributes
int line_number_
int column_number_
bool is_empty_
Detailed Description
Defines location inside script.
Lines and columns are 0-based.
Definition at line 30 of file interface-types.h.
Constructor & Destructor Documentation
Location() [1/2]
v8::debug::Location::Location (int line_number, int column_number)
Definition at line 961 of file debug-interface.cc.
    : line_number_(line_number),
      column_number_(column_number),
      is_empty_(false) {}
Location() [2/2]
v8::debug::Location::Location ()
Create empty location.
Definition at line 966 of file debug-interface.cc.
    : line_number_(Function::kLineOffsetNotFound),
      column_number_(Function::kLineOffsetNotFound),
      is_empty_(true) {}
Member Function Documentation
GetColumnNumber()
int v8::debug::Location::GetColumnNumber () const
Definition at line 976 of file debug-interface.cc.
                                    {
  DCHECK(!IsEmpty());
  return column_number_;
}
References column_number_, DCHECK, and IsEmpty().
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes(), v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::createForGenerator(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8::debug::Script::GetPossibleBreakpoints(), v8_inspector::V8DebuggerScript::getPossibleBreakpoints(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::debug::Script::GetSourceOffset(), v8_inspector::V8DebuggerAgentImpl::isFunctionBlackboxed(), v8_inspector::V8DebuggerAgentImpl::setBreakpointImpl(), and v8::Shell::WriteLcovData().
GetLineNumber()
int v8::debug::Location::GetLineNumber () const
Definition at line 971 of file debug-interface.cc.
                                  {
  DCHECK(!IsEmpty());
  return line_number_;
}
References DCHECK, IsEmpty(), and line_number_.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes(), v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::createForGenerator(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8::debug::Script::GetPossibleBreakpoints(), v8_inspector::V8DebuggerScript::getPossibleBreakpoints(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::debug::Script::GetSourceOffset(), v8_inspector::V8DebuggerAgentImpl::isFunctionBlackboxed(), v8::anonymous_namespace{d8.cc}::LineFromOffset(), v8_inspector::V8DebuggerAgentImpl::setBreakpointImpl(), and v8::Shell::WriteLcovData().
IsEmpty()
bool v8::debug::Location::IsEmpty () const
Definition at line 981 of file debug-interface.cc.
{ return is_empty_; }
References is_empty_.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), GetColumnNumber(), GetLineNumber(), and v8::debug::Script::GetPossibleBreakpoints().
Member Data Documentation
column_number_
int v8::debug::Location::column_number_ [private]
Definition at line 44 of file interface-types.h.
Referenced by GetColumnNumber().
is_empty_
bool v8::debug::Location::is_empty_ [private]
Definition at line 45 of file interface-types.h.
Referenced by IsEmpty().
line_number_
int v8::debug::Location::line_number_ [private]
Definition at line 43 of file interface-types.h.
Referenced by GetLineNumber().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/interface-types.h
/mnt/V8SourceCode/src/debug/debug-interface.cc