v8::internal::KeyedLoadBaselineDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::TaggedSigned()) static const expr inline Register ReceiverRegister()
Static Public Member Functions
static constexpr Register NameRegister ()
static constexpr Register SlotRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 1365 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::KeyedLoadBaselineDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::TaggedSigned()) const
NameRegister()
constexpr Register v8::internal::KeyedLoadBaselineDescriptor::NameRegister () [inline], [static], [constexpr]
Definition at line 76 of file interface-descriptors-riscv-inl.h.
                                                             {
  return kInterpreterAccumulatorRegister;
}
References v8::internal::kInterpreterAccumulatorRegister.
Referenced by registers(), v8::internal::KeyedLoadWithVectorDescriptor::registers(), and v8::internal::EnumeratedKeyedLoadBaselineDescriptor::registers().
registers()
constexpr auto v8::internal::KeyedLoadBaselineDescriptor::registers () [static], [constexpr]
Definition at line 644 of file interface-descriptors-inl.h.
                                                      {
  return RegisterArray(ReceiverRegister(), NameRegister(), SlotRegister());
}
References NameRegister(), v8::internal::RegisterArray(), and SlotRegister().
SlotRegister()
constexpr Register v8::internal::KeyedLoadBaselineDescriptor::SlotRegister () [inline], [static], [constexpr]
Definition at line 80 of file interface-descriptors-riscv-inl.h.
{ return a2; }
Referenced by registers(), and v8::internal::KeyedLoadWithVectorDescriptor::registers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h