v8::internal::TryCatchStatementSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
TryCatchStatementSourceRanges (const SourceRange &catch_range)
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
void RemoveContinuationRange () override
Private Attributes
SourceRange catch_range_
bool has_continuation_ = true
Detailed Description
Definition at line 355 of file ast-source-ranges.h.
Constructor & Destructor Documentation
TryCatchStatementSourceRanges()
v8::internal::TryCatchStatementSourceRanges::TryCatchStatementSourceRanges (const SourceRange & catch_range) [inline], [explicit]
Definition at line 357 of file ast-source-ranges.h.
      : catch_range_(catch_range) {}
Member Function Documentation
GetRange()
SourceRange v8::internal::TryCatchStatementSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 360 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    switch (kind) {
      case SourceRangeKind::kCatch:
        return catch_range_;
      case SourceRangeKind::kContinuation:
        if (!has_continuation_) return SourceRange::Empty();
        return SourceRange::ContinuationOf(catch_range_);
      default:
        UNREACHABLE();
    }
  }
References catch_range_, v8::internal::SourceRange::ContinuationOf(), v8::internal::DCHECK(), v8::internal::SourceRange::Empty(), has_continuation_, HasRange(), v8::internal::kCatch, v8::internal::kContinuation, and v8::internal::UNREACHABLE().
HasRange()
bool v8::internal::TryCatchStatementSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 373 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kCatch ||
           kind == SourceRangeKind::kContinuation;
  }
References v8::internal::kCatch, and v8::internal::kContinuation.
Referenced by GetRange(), and RemoveContinuationRange().
RemoveContinuationRange()
void v8::internal::TryCatchStatementSourceRanges::RemoveContinuationRange () [inline], [override], [virtual]
Reimplemented from v8::internal::AstNodeSourceRanges.
Definition at line 378 of file ast-source-ranges.h.
                                          {
    DCHECK(HasRange(SourceRangeKind::kContinuation));
    has_continuation_ = false;
  }
References v8::internal::DCHECK(), has_continuation_, HasRange(), and v8::internal::kContinuation.
Member Data Documentation
catch_range_
SourceRange v8::internal::TryCatchStatementSourceRanges::catch_range_ [private]
Definition at line 384 of file ast-source-ranges.h.
Referenced by GetRange().
has_continuation_
bool v8::internal::TryCatchStatementSourceRanges::has_continuation_ = true [private]
Definition at line 385 of file ast-source-ranges.h.
Referenced by GetRange(), and RemoveContinuationRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h