v8::internal::maglev::MaglevCodeGenerator Class Reference
#include <maglev-code-generator.h>
Public Member Functions
MaglevCodeGenerator (LocalIsolate *isolate, MaglevCompilationInfo *compilation_info, Graph *graph)
bool Assemble ()
MaybeHandle< Code > Generate (Isolate *isolate)
GlobalHandleVector< Map > RetainedMaps (Isolate *isolate)
Private Member Functions
bool EmitCode ()
void EmitDeferredCode ()
bool EmitDeopts ()
void EmitExceptionHandlerTrampolines ()
void EmitMetadata ()
void RecordInlinedFunctions ()
GlobalHandleVector< Map > CollectRetainedMaps (DirectHandle< Code > code)
Handle< DeoptimizationData > GenerateDeoptimizationData (LocalIsolate *local_isolate)
MaybeHandle< Code > BuildCodeObject (LocalIsolate *local_isolate)
int stack_slot_count () const
int stack_slot_count_with_fixed_frame () const
uint16_t parameter_count () const
MaglevAssembler * masm ()
Private Attributes
LocalIsolate * local_isolate_
MaglevSafepointTableBuilder safepoint_table_builder_
FrameTranslationBuilder frame_translation_builder_
MaglevCodeGenState code_gen_state_
MaglevAssembler masm_
Graph *const graph_
IdentityMap< int, base::DefaultAllocationPolicy > protected_deopt_literals_
IdentityMap< int, base::DefaultAllocationPolicy > deopt_literals_
int deopt_exit_start_offset_ = -1
int handler_table_offset_ = 0
int inlined_function_count_ = 0
bool code_gen_succeeded_ = false
IndirectHandle< DeoptimizationData > deopt_data_
MaybeIndirectHandle< Code > code_
GlobalHandleVector< Map > retained_maps_
bool is_context_specialized_
Zone * zone_
Detailed Description
Definition at line 22 of file maglev-code-generator.h.
Constructor & Destructor Documentation
MaglevCodeGenerator()
v8::internal::maglev::MaglevCodeGenerator::MaglevCodeGenerator (LocalIsolate * isolate, MaglevCompilationInfo * compilation_info, Graph * graph)
Definition at line 1695 of file maglev-code-generator.cc.
    : local_isolate_(isolate),
      safepoint_table_builder_(compilation_info->zone(),
                               graph->tagged_stack_slots()),
      frame_translation_builder_(compilation_info->zone()),
      code_gen_state_(compilation_info, &safepoint_table_builder_,
                      graph->max_block_id()),
      masm_(isolate->GetMainThreadIsolateUnsafe(), compilation_info->zone(),
            &code_gen_state_),
      graph_(graph),
      protected_deopt_literals_(isolate->heap()->heap()),
      deopt_literals_(isolate->heap()->heap()),
      retained_maps_(isolate->heap()),
      is_context_specialized_(
          compilation_info->specialize_to_function_context()),
      zone_(compilation_info->zone()) {
  DCHECK(maglev::IsMaglevEnabled());
  DCHECK_IMPLIES(compilation_info->toplevel_is_osr(),
                 maglev::IsMaglevOsrEnabled());
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::maglev::IsMaglevEnabled(), v8::internal::maglev::IsMaglevOsrEnabled(), and v8::internal::maglev::MaglevCompilationInfo::toplevel_is_osr().
Member Function Documentation
Assemble()
bool v8::internal::maglev::MaglevCodeGenerator::Assemble ()
Definition at line 1718 of file maglev-code-generator.cc.
                                   {
  if (!EmitCode()) {
#ifdef V8_TARGET_ARCH_ARM
    // Even if we fail, we force emit the constant pool, so that it is empty.
    __ CheckConstPool(true, false);
#endif
    return false;
  }
  EmitMetadata();
  if (v8_flags.maglev_build_code_on_background) {
    code_ = local_isolate_->heap()->NewPersistentMaybeHandle(
        BuildCodeObject(local_isolate_));
    Handle<Code> code;
    if (code_.ToHandle(&code)) {
      retained_maps_ = CollectRetainedMaps(code);
    }
  } else if (v8_flags.maglev_deopt_data_on_background) {
    // Only do this if not --maglev-build-code-on-background, since that will do
    // it itself.
    deopt_data_ = local_isolate_->heap()->NewPersistentHandle(
        GenerateDeoptimizationData(local_isolate_));
  }
  return true;
}
References __, BuildCodeObject(), code, code_, CollectRetainedMaps(), deopt_data_, EmitCode(), EmitMetadata(), GenerateDeoptimizationData(), v8::internal::LocalIsolate::heap(), local_isolate_, v8::internal::LocalHeap::NewPersistentHandle(), v8::internal::LocalHeap::NewPersistentMaybeHandle(), retained_maps_, and v8::internal::v8_flags.
BuildCodeObject()
MaybeHandle< Code > v8::internal::maglev::MaglevCodeGenerator::BuildCodeObject (LocalIsolate * local_isolate) [private]
Definition at line 1938 of file maglev-code-generator.cc.
                                 {
  if (!code_gen_succeeded_) return {};
  Handle<DeoptimizationData> deopt_data =
      (v8_flags.maglev_deopt_data_on_background &&
       !v8_flags.maglev_build_code_on_background)
          ? deopt_data_
          : GenerateDeoptimizationData(local_isolate);
  CHECK(!deopt_data.is_null());
  CodeDesc desc;
  masm()->GetCode(local_isolate, &desc, &safepoint_table_builder_,
                  handler_table_offset_);
  auto builder =
      Factory::CodeBuilder{local_isolate, desc, CodeKind::MAGLEV}
          .set_stack_slots(stack_slot_count_with_fixed_frame())
          .set_parameter_count(parameter_count())
          .set_deoptimization_data(deopt_data)
          .set_empty_source_position_table()
          .set_inlined_bytecode_size(graph_->total_inlined_bytecode_size())
          .set_osr_offset(
              code_gen_state_.compilation_info()->toplevel_osr_offset());
  if (is_context_specialized_) {
    builder.set_is_context_specialized();
  }
  return builder.TryBuild();
}
References CHECK, code_gen_state_, code_gen_succeeded_, v8::internal::maglev::MaglevCodeGenState::compilation_info(), deopt_data_, GenerateDeoptimizationData(), v8::internal::Assembler::GetCode(), graph_, handler_table_offset_, is_context_specialized_, v8::internal::HandleBase::is_null(), masm(), parameter_count(), safepoint_table_builder_, stack_slot_count_with_fixed_frame(), v8::internal::maglev::MaglevCompilationInfo::toplevel_osr_offset(), v8::internal::maglev::Graph::total_inlined_bytecode_size(), and v8::internal::v8_flags.
Referenced by Assemble(), and Generate().
CollectRetainedMaps()
GlobalHandleVector< Map > v8::internal::maglev::MaglevCodeGenerator::CollectRetainedMaps (DirectHandle< Code > code) [private]
Definition at line 1969 of file maglev-code-generator.cc.
                             {
  DCHECK(code->is_optimized_code());
  DisallowGarbageCollection no_gc;
  GlobalHandleVector<Map> maps(local_isolate_->heap());
  PtrComprCageBase cage_base(local_isolate_);
  int const mode_mask = RelocInfo::EmbeddedObjectModeMask();
  for (RelocIterator it(*code, mode_mask); !it.done(); it.next()) {
    DCHECK(RelocInfo::IsEmbeddedObjectMode(it.rinfo()->rmode()));
    Tagged<HeapObject> target_object = it.rinfo()->target_object(cage_base);
    if (code->IsWeakObjectInOptimizedCode(target_object)) {
      if (IsMap(target_object, cage_base)) {
        maps.Push(Cast<Map>(target_object));
      }
    }
  }
  return maps;
}
References code, v8::internal::DCHECK(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::RelocInfo::EmbeddedObjectModeMask(), v8::internal::LocalIsolate::heap(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), local_isolate_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::GlobalHandleVector< T >::Push().
Referenced by Assemble().
EmitCode()
bool v8::internal::maglev::MaglevCodeGenerator::EmitCode () [private]
Definition at line 1765 of file maglev-code-generator.cc.
                                   {
  GraphProcessor<NodeMultiProcessor<SafepointingNodeProcessor,
                                    MaglevCodeGeneratingNodeProcessor>>
      processor(SafepointingNodeProcessor{local_isolate_},
                MaglevCodeGeneratingNodeProcessor{masm(), zone_});
  RecordInlinedFunctions();
  if (graph_->is_osr()) {
    masm_.Abort(AbortReason::kShouldNotDirectlyEnterOsrFunction);
    masm_.RecordComment("-- OSR entrypoint --");
    masm_.BindJumpTarget(code_gen_state_.osr_entry());
  }
  processor.ProcessGraph(graph_);
  EmitDeferredCode();
  if (!EmitDeopts()) return false;
  EmitExceptionHandlerTrampolines();
  __ FinishCode();
  code_gen_succeeded_ = true;
  return true;
}
References __, v8::internal::MacroAssembler::Abort(), v8::internal::maglev::MaglevAssembler::BindJumpTarget(), code_gen_state_, code_gen_succeeded_, EmitDeferredCode(), EmitDeopts(), EmitExceptionHandlerTrampolines(), graph_, v8::internal::maglev::Graph::is_osr(), local_isolate_, masm(), masm_, v8::internal::maglev::MaglevCodeGenState::osr_entry(), v8::internal::AssemblerBase::RecordComment(), RecordInlinedFunctions(), and zone_.
Referenced by Assemble().
EmitDeferredCode()
void v8::internal::maglev::MaglevCodeGenerator::EmitDeferredCode () [private]
Definition at line 1804 of file maglev-code-generator.cc.
                                           {
  // Loop over deferred_code() multiple times, clearing the vector on each
  // outer loop, so that deferred code can itself emit deferred code.
  while (!code_gen_state_.deferred_code().empty()) {
    for (DeferredCodeInfo* deferred_code : code_gen_state_.TakeDeferredCode()) {
      __ RecordComment("-- Deferred block");
      __ bind(&deferred_code->deferred_code_label);
      deferred_code->Generate(masm());
      __ Trap();
    }
  }
}
References __, code_gen_state_, v8::internal::maglev::MaglevCodeGenState::deferred_code(), masm(), and v8::internal::maglev::MaglevCodeGenState::TakeDeferredCode().
Referenced by EmitCode().
EmitDeopts()
bool v8::internal::maglev::MaglevCodeGenerator::EmitDeopts () [private]
Definition at line 1817 of file maglev-code-generator.cc.
                                     {
  const size_t num_deopts = code_gen_state_.eager_deopts().size() +
                            code_gen_state_.lazy_deopts().size();
  if (num_deopts > Deoptimizer::kMaxNumberOfEntries) {
    return false;
  }
  MaglevFrameTranslationBuilder translation_builder(
      local_isolate_, &masm_, &frame_translation_builder_,
      &protected_deopt_literals_, &deopt_literals_);
  // Deoptimization exits must be as small as possible, since their count grows
  // with function size. These labels are an optimization which extracts the
  // (potentially large) instruction sequence for the final jump to the
  // deoptimization entry into a single spot per InstructionStream object. All
  // deopt exits can then near-call to this label. Note: not used on all
  // architectures.
  Label eager_deopt_entry;
  Label lazy_deopt_entry;
  __ MaybeEmitDeoptBuiltinsCall(
      code_gen_state_.eager_deopts().size(), &eager_deopt_entry,
      code_gen_state_.lazy_deopts().size(), &lazy_deopt_entry);
  deopt_exit_start_offset_ = __ pc_offset();
  int deopt_index = 0;
  __ RecordComment("-- Non-lazy deopts");
  for (EagerDeoptInfo* deopt_info : code_gen_state_.eager_deopts()) {
    local_isolate_->heap()->Safepoint();
    translation_builder.BuildEagerDeopt(deopt_info);
    if (masm_.compilation_info()->collect_source_positions() ||
        AlwaysPreserveDeoptReason(deopt_info->reason()) ||
        IsDeoptimizationWithoutCodeInvalidation(deopt_info->reason())) {
      // Note: Maglev uses the deopt_reason to tell the deoptimizer not to
      // discard optimized code on deopt during ML-TF OSR. This is why we
      // unconditionally emit the deopt_reason when
      // IsDeoptimizationWithoutCodeInvalidation is true.
      __ RecordDeoptReason(deopt_info->reason(), 0,
                           deopt_info->top_frame().GetSourcePosition(),
                           deopt_index);
    }
    __ bind(deopt_info->deopt_entry_label());
    __ CallForDeoptimization(Builtin::kDeoptimizationEntry_Eager, deopt_index,
                             deopt_info->deopt_entry_label(),
                             DeoptimizeKind::kEager, nullptr,
                             &eager_deopt_entry);
    deopt_index++;
  }
  __ RecordComment("-- Lazy deopts");
  int last_updated_safepoint = 0;
  for (LazyDeoptInfo* deopt_info : code_gen_state_.lazy_deopts()) {
    local_isolate_->heap()->Safepoint();
    translation_builder.BuildLazyDeopt(deopt_info);
    if (masm_.compilation_info()->collect_source_positions()) {
      __ RecordDeoptReason(DeoptimizeReason::kUnknown, 0,
                           deopt_info->top_frame().GetSourcePosition(),
                           deopt_index);
    }
    __ BindExceptionHandler(deopt_info->deopt_entry_label());
    __ CallForDeoptimization(Builtin::kDeoptimizationEntry_Lazy, deopt_index,
                             deopt_info->deopt_entry_label(),
                             DeoptimizeKind::kLazy, nullptr, &lazy_deopt_entry);
    last_updated_safepoint = safepoint_table_builder_.UpdateDeoptimizationInfo(
        deopt_info->deopting_call_return_pc(),
        deopt_info->deopt_entry_label()->pos(), last_updated_safepoint,
        deopt_index);
    deopt_index++;
  }
  return true;
}
References __, v8::internal::AlwaysPreserveDeoptReason(), code_gen_state_, v8::internal::maglev::MaglevCompilationInfo::collect_source_positions(), v8::internal::maglev::MaglevAssembler::compilation_info(), deopt_exit_start_offset_, deopt_literals_, v8::internal::maglev::MaglevCodeGenState::eager_deopts(), frame_translation_builder_, v8::internal::LocalIsolate::heap(), v8::internal::IsDeoptimizationWithoutCodeInvalidation(), v8::internal::kEager, v8::internal::kLazy, v8::internal::Deoptimizer::kMaxNumberOfEntries, v8::internal::maglev::MaglevCodeGenState::lazy_deopts(), local_isolate_, masm_, protected_deopt_literals_, v8::internal::LocalHeap::Safepoint(), safepoint_table_builder_, and v8::internal::MaglevSafepointTableBuilder::UpdateDeoptimizationInfo().
Referenced by EmitCode().
EmitExceptionHandlerTrampolines()
void v8::internal::maglev::MaglevCodeGenerator::EmitExceptionHandlerTrampolines () [private]
Definition at line 1897 of file maglev-code-generator.cc.
                                                          {
  if (code_gen_state_.handlers().empty()) return;
  __ RecordComment("-- Exception handler trampolines");
#ifdef DEBUG
  // Exception trampolines can allocate HeapNumbers (when a Float64 value is
  // used as input to a Tagged exception phi).
  masm()->set_allow_allocate(true);
#endif
  for (NodeBase* node : code_gen_state_.handlers()) {
    DCHECK(node->properties().can_throw());
    // Materializations of Phi inputs in the trampoline could allocate
    // HeapNumbers.
    DCHECK(node->properties().can_allocate());
    ExceptionHandlerTrampolineBuilder::Build(masm(), node);
  }
#ifdef DEBUG
  masm()->set_allow_allocate(false);
#endif
}
References __, code_gen_state_, v8::internal::DCHECK(), v8::internal::maglev::MaglevCodeGenState::handlers(), and masm().
Referenced by EmitCode().
EmitMetadata()
void v8::internal::maglev::MaglevCodeGenerator::EmitMetadata () [private]
Definition at line 1920 of file maglev-code-generator.cc.
                                       {
  // Final alignment before starting on the metadata section.
  masm()->Align(InstructionStream::kMetadataAlignment);
  safepoint_table_builder_.Emit(masm(), stack_slot_count_with_fixed_frame());
  // Exception handler table.
  handler_table_offset_ = HandlerTable::EmitReturnTableStart(masm());
  for (NodeBase* node : code_gen_state_.handlers()) {
    ExceptionHandlerInfo* info = node->exception_handler_info();
    DCHECK_IMPLIES(info->ShouldLazyDeopt(),
                   !info->trampoline_entry().is_bound());
    int pos = info->ShouldLazyDeopt() ? HandlerTable::kLazyDeopt
                                      : info->trampoline_entry().pos();
    HandlerTable::EmitReturnEntry(masm(), info->pc_offset(), pos);
  }
}
References v8::internal::Assembler::Align(), code_gen_state_, DCHECK_IMPLIES, v8::internal::MaglevSafepointTableBuilder::Emit(), v8::internal::HandlerTable::EmitReturnEntry(), v8::internal::HandlerTable::EmitReturnTableStart(), handler_table_offset_, v8::internal::maglev::MaglevCodeGenState::handlers(), v8::internal::Label::is_bound(), v8::internal::HandlerTable::kLazyDeopt, v8::internal::InstructionStream::kMetadataAlignment, masm(), v8::internal::maglev::ExceptionHandlerInfo::pc_offset(), v8::internal::Label::pos(), safepoint_table_builder_, v8::internal::maglev::ExceptionHandlerInfo::ShouldLazyDeopt(), stack_slot_count_with_fixed_frame(), and v8::internal::maglev::ExceptionHandlerInfo::trampoline_entry().
Referenced by Assemble().
Generate()
MaybeHandle< Code > v8::internal::maglev::MaglevCodeGenerator::Generate (Isolate * isolate)
Definition at line 1745 of file maglev-code-generator.cc.
                                                                {
  if (v8_flags.maglev_build_code_on_background) {
    Handle<Code> code;
    if (code_.ToHandle(&code)) {
      return handle(*code, isolate);
    }
    return kNullMaybeHandle;
  }
  return BuildCodeObject(isolate->main_thread_local_isolate());
}
References BuildCodeObject(), code, code_, v8::internal::handle(), v8::internal::kNullMaybeHandle, v8::internal::Isolate::main_thread_local_isolate(), and v8::internal::v8_flags.
Referenced by v8::internal::maglev::MaglevCompiler::GenerateCode().
GenerateDeoptimizationData()
Handle< DeoptimizationData > v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData (LocalIsolate * local_isolate) [private]
Definition at line 1989 of file maglev-code-generator.cc.
                                 {
  int eager_deopt_count =
      static_cast<int>(code_gen_state_.eager_deopts().size());
  int lazy_deopt_count = static_cast<int>(code_gen_state_.lazy_deopts().size());
  int deopt_count = lazy_deopt_count + eager_deopt_count;
  if (deopt_count == 0 && !graph_->is_osr()) {
    return DeoptimizationData::Empty(local_isolate);
  }
  Handle<DeoptimizationData> data =
      DeoptimizationData::New(local_isolate, deopt_count);
  DirectHandle<DeoptimizationFrameTranslation> translations =
      frame_translation_builder_.ToFrameTranslation(local_isolate->factory());
  DirectHandle<SharedFunctionInfoWrapper> sfi_wrapper =
      local_isolate->factory()->NewSharedFunctionInfoWrapper(
          code_gen_state_.compilation_info()
              ->toplevel_compilation_unit()
              ->shared_function_info()
              .object());
  {
    DisallowGarbageCollection no_gc;
    Tagged<DeoptimizationData> raw_data = *data;
    raw_data->SetFrameTranslation(*translations);
    raw_data->SetInlinedFunctionCount(Smi::FromInt(inlined_function_count_));
    raw_data->SetOptimizationId(
        Smi::FromInt(local_isolate->NextOptimizationId()));
    DCHECK_NE(deopt_exit_start_offset_, -1);
    raw_data->SetDeoptExitStart(Smi::FromInt(deopt_exit_start_offset_));
    raw_data->SetEagerDeoptCount(Smi::FromInt(eager_deopt_count));
    raw_data->SetLazyDeoptCount(Smi::FromInt(lazy_deopt_count));
    raw_data->SetWrappedSharedFunctionInfo(*sfi_wrapper);
  }
  int inlined_functions_size =
      static_cast<int>(graph_->inlined_functions().size());
  DirectHandle<ProtectedDeoptimizationLiteralArray> protected_literals =
      local_isolate->factory()->NewProtectedFixedArray(
          protected_deopt_literals_.size());
  DirectHandle<DeoptimizationLiteralArray> literals =
      local_isolate->factory()->NewDeoptimizationLiteralArray(
          deopt_literals_.size());
  DirectHandle<TrustedPodArray<InliningPosition>> inlining_positions =
      TrustedPodArray<InliningPosition>::New(local_isolate,
                                             inlined_functions_size);
  DisallowGarbageCollection no_gc;
  Tagged<ProtectedDeoptimizationLiteralArray> raw_protected_literals =
      *protected_literals;
  {
    IdentityMap<int, base::DefaultAllocationPolicy>::IteratableScope iterate(
        &protected_deopt_literals_);
    for (auto it = iterate.begin(); it != iterate.end(); ++it) {
      raw_protected_literals->set(*it.entry(), Cast<TrustedObject>(it.key()));
    }
  }
  Tagged<DeoptimizationLiteralArray> raw_literals = *literals;
  {
    IdentityMap<int, base::DefaultAllocationPolicy>::IteratableScope iterate(
        &deopt_literals_);
    for (auto it = iterate.begin(); it != iterate.end(); ++it) {
      raw_literals->set(*it.entry(), it.key());
    }
  }
  for (int i = 0; i < inlined_functions_size; i++) {
    auto inlined_function_info = graph_->inlined_functions()[i];
    inlining_positions->set(i, inlined_function_info.position);
  }
  Tagged<DeoptimizationData> raw_data = *data;
  raw_data->SetProtectedLiteralArray(raw_protected_literals);
  raw_data->SetLiteralArray(raw_literals);
  raw_data->SetInliningPositions(*inlining_positions);
  auto info = code_gen_state_.compilation_info();
  raw_data->SetOsrBytecodeOffset(
      Smi::FromInt(info->toplevel_osr_offset().ToInt()));
  if (graph_->is_osr()) {
    raw_data->SetOsrPcOffset(Smi::FromInt(code_gen_state_.osr_entry()->pos()));
  } else {
    raw_data->SetOsrPcOffset(Smi::FromInt(-1));
  }
  // Populate deoptimization entries.
  int i = 0;
  for (EagerDeoptInfo* deopt_info : code_gen_state_.eager_deopts()) {
    DCHECK_NE(deopt_info->translation_index(), -1);
    raw_data->SetBytecodeOffset(i, deopt_info->top_frame().GetBytecodeOffset());
    raw_data->SetTranslationIndex(
        i, Smi::FromInt(deopt_info->translation_index()));
    raw_data->SetPc(i, Smi::FromInt(deopt_info->deopt_entry_label()->pos()));
#ifdef DEBUG
    raw_data->SetNodeId(i, Smi::FromInt(i));
#endif // DEBUG
    i++;
  }
  for (LazyDeoptInfo* deopt_info : code_gen_state_.lazy_deopts()) {
    DCHECK_NE(deopt_info->translation_index(), -1);
    raw_data->SetBytecodeOffset(i, deopt_info->top_frame().GetBytecodeOffset());
    raw_data->SetTranslationIndex(
        i, Smi::FromInt(deopt_info->translation_index()));
    raw_data->SetPc(i, Smi::FromInt(deopt_info->deopt_entry_label()->pos()));
#ifdef DEBUG
    raw_data->SetNodeId(i, Smi::FromInt(i));
#endif // DEBUG
    i++;
  }
#ifdef DEBUG
  raw_data->Verify(code_gen_state_.compilation_info()
                       ->toplevel_compilation_unit()
                       ->bytecode()
                       .object());
#endif
  return data;
}
References v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::begin(), v8::internal::maglev::MaglevCompilationUnit::bytecode(), code_gen_state_, v8::internal::maglev::MaglevCodeGenState::compilation_info(), DCHECK_NE, deopt_exit_start_offset_, deopt_literals_, v8::internal::maglev::MaglevCodeGenState::eager_deopts(), v8::internal::DeoptimizationData::Empty(), v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::end(), v8::internal::LocalIsolate::factory(), frame_translation_builder_, v8::internal::Smi::FromInt(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, inlined_function_count_, v8::internal::maglev::Graph::inlined_functions(), v8::internal::maglev::Graph::is_osr(), v8::internal::maglev::MaglevCodeGenState::lazy_deopts(), v8::internal::DeoptimizationData::New(), v8::internal::TrustedPodArray< T >::New(), v8::internal::FactoryBase< Impl >::NewDeoptimizationLiteralArray(), v8::internal::FactoryBase< Impl >::NewProtectedFixedArray(), v8::internal::FactoryBase< Impl >::NewSharedFunctionInfoWrapper(), v8::internal::LocalIsolate::NextOptimizationId(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::compiler::BytecodeArrayRef::object(), v8::internal::compiler::SharedFunctionInfoRef::object(), v8::internal::maglev::MaglevCodeGenState::osr_entry(), v8::internal::Label::pos(), protected_deopt_literals_, v8::internal::maglev::MaglevCompilationUnit::shared_function_info(), v8::internal::FrameTranslationBuilder::ToFrameTranslation(), and v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit().
Referenced by Assemble(), and BuildCodeObject().
masm()
MaglevAssembler* v8::internal::maglev::MaglevCodeGenerator::masm () [inline], [private]
Definition at line 52 of file maglev-code-generator.h.
{ return &masm_; }
References masm_.
Referenced by BuildCodeObject(), EmitCode(), EmitDeferredCode(), EmitExceptionHandlerTrampolines(), and EmitMetadata().
parameter_count()
uint16_t v8::internal::maglev::MaglevCodeGenerator::parameter_count () const [inline], [private]
Definition at line 50 of file maglev-code-generator.h.
{ return code_gen_state_.parameter_count(); }
References code_gen_state_, and v8::internal::maglev::MaglevCodeGenState::parameter_count().
Referenced by BuildCodeObject().
RecordInlinedFunctions()
void v8::internal::maglev::MaglevCodeGenerator::RecordInlinedFunctions () [private]
Definition at line 1788 of file maglev-code-generator.cc.
                                                 {
  // The inlined functions should be the first literals.
  DCHECK_EQ(0u, deopt_literals_.size());
  for (OptimizedCompilationInfo::InlinedFunctionHolder& inlined :
       graph_->inlined_functions()) {
    IdentityMapFindResult<int> res =
        deopt_literals_.FindOrInsert(inlined.shared_info);
    if (!res.already_exists) {
      DCHECK_EQ(0, *res.entry);
      *res.entry = deopt_literals_.size() - 1;
    }
    inlined.RegisterInlinedFunctionId(*res.entry);
  }
  inlined_function_count_ = static_cast<int>(deopt_literals_.size());
}
References v8::internal::IdentityMapFindResult< T >::already_exists, DCHECK_EQ, deopt_literals_, v8::internal::IdentityMapFindResult< T >::entry, graph_, inlined_function_count_, and v8::internal::maglev::Graph::inlined_functions().
Referenced by EmitCode().
RetainedMaps()
GlobalHandleVector< Map > v8::internal::maglev::MaglevCodeGenerator::RetainedMaps (Isolate * isolate)
Definition at line 1757 of file maglev-code-generator.cc.
                                                                          {
  DisallowGarbageCollection no_gc;
  GlobalHandleVector<Map> maps(isolate->heap());
  maps.Reserve(retained_maps_.size());
  for (DirectHandle<Map> map : retained_maps_) maps.Push(*map);
  return maps;
}
References v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::GlobalHandleVector< T >::Push(), v8::internal::GlobalHandleVector< T >::Reserve(), and retained_maps_.
stack_slot_count()
int v8::internal::maglev::MaglevCodeGenerator::stack_slot_count () const [inline], [private]
Definition at line 46 of file maglev-code-generator.h.
{ return code_gen_state_.stack_slots(); }
References code_gen_state_, and v8::internal::maglev::MaglevCodeGenState::stack_slots().
Referenced by stack_slot_count_with_fixed_frame().
stack_slot_count_with_fixed_frame()
int v8::internal::maglev::MaglevCodeGenerator::stack_slot_count_with_fixed_frame () const [inline], [private]
Definition at line 47 of file maglev-code-generator.h.
                                                {
    return stack_slot_count() + StandardFrameConstants::kFixedSlotCount;
  }
References v8::internal::StandardFrameConstants::kFixedSlotCount, and stack_slot_count().
Referenced by BuildCodeObject(), and EmitMetadata().
Member Data Documentation
code_
MaybeIndirectHandle<Code> v8::internal::maglev::MaglevCodeGenerator::code_ [private]
Definition at line 70 of file maglev-code-generator.h.
Referenced by Assemble(), and Generate().
code_gen_state_
MaglevCodeGenState v8::internal::maglev::MaglevCodeGenerator::code_gen_state_ [private]
Definition at line 57 of file maglev-code-generator.h.
Referenced by BuildCodeObject(), EmitCode(), EmitDeferredCode(), EmitDeopts(), EmitExceptionHandlerTrampolines(), EmitMetadata(), GenerateDeoptimizationData(), parameter_count(), and stack_slot_count().
code_gen_succeeded_
bool v8::internal::maglev::MaglevCodeGenerator::code_gen_succeeded_ = false [private]
Definition at line 67 of file maglev-code-generator.h.
Referenced by BuildCodeObject(), and EmitCode().
deopt_data_
IndirectHandle<DeoptimizationData> v8::internal::maglev::MaglevCodeGenerator::deopt_data_ [private]
Definition at line 69 of file maglev-code-generator.h.
Referenced by Assemble(), and BuildCodeObject().
deopt_exit_start_offset_
int v8::internal::maglev::MaglevCodeGenerator::deopt_exit_start_offset_ = -1 [private]
Definition at line 63 of file maglev-code-generator.h.
Referenced by EmitDeopts(), and GenerateDeoptimizationData().
deopt_literals_
IdentityMap<int, base::DefaultAllocationPolicy> v8::internal::maglev::MaglevCodeGenerator::deopt_literals_ [private]
Definition at line 62 of file maglev-code-generator.h.
Referenced by EmitDeopts(), GenerateDeoptimizationData(), and RecordInlinedFunctions().
frame_translation_builder_
FrameTranslationBuilder v8::internal::maglev::MaglevCodeGenerator::frame_translation_builder_ [private]
Definition at line 56 of file maglev-code-generator.h.
Referenced by EmitDeopts(), and GenerateDeoptimizationData().
graph_
Graph* const v8::internal::maglev::MaglevCodeGenerator::graph_ [private]
Definition at line 59 of file maglev-code-generator.h.
Referenced by BuildCodeObject(), EmitCode(), GenerateDeoptimizationData(), and RecordInlinedFunctions().
handler_table_offset_
int v8::internal::maglev::MaglevCodeGenerator::handler_table_offset_ = 0 [private]
Definition at line 64 of file maglev-code-generator.h.
Referenced by BuildCodeObject(), and EmitMetadata().
inlined_function_count_
int v8::internal::maglev::MaglevCodeGenerator::inlined_function_count_ = 0 [private]
Definition at line 65 of file maglev-code-generator.h.
Referenced by GenerateDeoptimizationData(), and RecordInlinedFunctions().
is_context_specialized_
bool v8::internal::maglev::MaglevCodeGenerator::is_context_specialized_ [private]
Definition at line 72 of file maglev-code-generator.h.
Referenced by BuildCodeObject().
local_isolate_
LocalIsolate* v8::internal::maglev::MaglevCodeGenerator::local_isolate_ [private]
Definition at line 54 of file maglev-code-generator.h.
Referenced by Assemble(), CollectRetainedMaps(), EmitCode(), and EmitDeopts().
masm_
MaglevAssembler v8::internal::maglev::MaglevCodeGenerator::masm_ [private]
Definition at line 58 of file maglev-code-generator.h.
Referenced by EmitCode(), EmitDeopts(), and masm().
protected_deopt_literals_
IdentityMap<int, base::DefaultAllocationPolicy> v8::internal::maglev::MaglevCodeGenerator::protected_deopt_literals_ [private]
Definition at line 61 of file maglev-code-generator.h.
Referenced by EmitDeopts(), and GenerateDeoptimizationData().
retained_maps_
GlobalHandleVector<Map> v8::internal::maglev::MaglevCodeGenerator::retained_maps_ [private]
Definition at line 71 of file maglev-code-generator.h.
Referenced by Assemble(), and RetainedMaps().
safepoint_table_builder_
MaglevSafepointTableBuilder v8::internal::maglev::MaglevCodeGenerator::safepoint_table_builder_ [private]
Definition at line 55 of file maglev-code-generator.h.
Referenced by BuildCodeObject(), EmitDeopts(), and EmitMetadata().
zone_
Zone* v8::internal::maglev::MaglevCodeGenerator::zone_ [private]
Definition at line 73 of file maglev-code-generator.h.
Referenced by EmitCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-code-generator.h
/mnt/V8SourceCode/src/maglev/maglev-code-generator.cc