v8::internal::maglev::ForInPrepare Class Reference
#include <maglev-ir.h>
Public Member Functions
ForInPrepare (uint64_t bitfield, compiler::FeedbackSource &feedback)
compiler::FeedbackSource feedback () const
Input & context ()
Input & enumerator ()
int ReturnCount () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 2, ForInPrepare >
Private Attributes
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 5282 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ForInPrepare::Base = FixedInputValueNodeT<2, ForInPrepare> [private]
Definition at line 5283 of file maglev-ir.h.
Constructor & Destructor Documentation
ForInPrepare()
v8::internal::maglev::ForInPrepare::ForInPrepare (uint64_t bitfield, compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 5286 of file maglev-ir.h.
      : Base(bitfield), feedback_(feedback) {}
Member Function Documentation
context()
Input& v8::internal::maglev::ForInPrepare::context () [inline]
Definition at line 5296 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
enumerator()
Input& v8::internal::maglev::ForInPrepare::enumerator () [inline]
Definition at line 5297 of file maglev-ir.h.
{ return Node::input(1); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::ForInPrepare::feedback () const [inline]
Definition at line 5294 of file maglev-ir.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::ForInPrepare::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::ForInPrepare::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::ForInPrepare::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5304 of file maglev-ir.h.
{}
ReturnCount()
int v8::internal::maglev::ForInPrepare::ReturnCount () const [inline]
Definition at line 5299 of file maglev-ir.h.
{ return 2; }
SetValueLocationConstraints()
void v8::internal::maglev::ForInPrepare::SetValueLocationConstraints ()
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::ForInPrepare::feedback_ [private]
Definition at line 5307 of file maglev-ir.h.
Referenced by feedback().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ForInPrepare::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 5291 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::ForInPrepare::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::Call() | OpProperties::NotIdempotent()
Definition at line 5289 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h