v8::internal::CountersInitializer Class Reference
#include <counters.h>
Public Member Functions
CountersVisitor (Counters *counters)
Protected Member Functions
void Visit (Histogram *histogram, const char *caption, int min, int max, int num_buckets) final
void Visit (TimedHistogram *histogram, const char *caption, int max, TimedHistogramResolution res) final
void Visit (NestedTimedHistogram *histogram, const char *caption, int max, TimedHistogramResolution res) final
void Visit (AggregatableHistogramTimer *histogram, const char *caption) final
void Visit (PercentageHistogram *histogram, const char *caption) final
void Visit (LegacyMemoryHistogram *histogram, const char *caption) final
void Visit (StatsCounter *counter, const char *caption) final
Detailed Description
Definition at line 736 of file counters.h.
Member Function Documentation
CountersVisitor()
v8::internal::CountersVisitor::CountersVisitor [inline], [explicit]
Definition at line 708 of file counters.h.
: counters_(counters) {}
Visit() [1/7]
void v8::internal::CountersInitializer::Visit (AggregatableHistogramTimer * histogram, const char * caption) [final], [protected], [virtual]
Reimplemented from v8::internal::CountersVisitor.
Definition at line 147 of file counters.cc.
                                                     {
  histogram->Initialize(caption, 0, 10000000, DefaultTimedHistogramNumBuckets,
                        counters());
}
References v8::internal::CountersVisitor::counters(), v8::internal::anonymous_namespace{counters.cc}::DefaultTimedHistogramNumBuckets, and v8::internal::Histogram::Initialize().
Visit() [2/7]
void v8::internal::CountersInitializer::Visit (Histogram * histogram, const char * caption, int min, int max, int num_buckets) [final], [protected], [virtual]
Reimplemented from v8::internal::CountersVisitor.
Definition at line 113 of file counters.cc.
                                                                   {
  histogram->Initialize(caption, min, max, num_buckets, counters());
}
References v8::internal::CountersVisitor::counters(), and v8::internal::Histogram::Initialize().
Visit() [3/7]
void v8::internal::CountersInitializer::Visit (LegacyMemoryHistogram * histogram, const char * caption) [final], [protected], [virtual]
Reimplemented from v8::internal::CountersVisitor.
Definition at line 123 of file counters.cc.
                                                     {
  // Exponential histogram assigns bucket limits to points
  // p[1], p[2], ... p[n] such that p[i+1] / p[i] = constant.
  // The constant factor is equal to the n-th root of (high / low),
  // where the n is the number of buckets, the low is the lower limit,
  // the high is the upper limit.
  // For n = 50, low = 1000, high = 500000: the factor = 1.13.
  histogram->Initialize(caption, 1000, 500000, 50, counters());
}
References v8::internal::CountersVisitor::counters(), and v8::internal::Histogram::Initialize().
Visit() [4/7]
void v8::internal::CountersInitializer::Visit (NestedTimedHistogram * histogram, const char * caption, int max, TimedHistogramResolution res) [final], [protected], [virtual]
Reimplemented from v8::internal::CountersVisitor.
Definition at line 140 of file counters.cc.
                                                              {
  histogram->Initialize(caption, 0, max, res, DefaultTimedHistogramNumBuckets,
                        counters());
}
References v8::internal::CountersVisitor::counters(), v8::internal::anonymous_namespace{counters.cc}::DefaultTimedHistogramNumBuckets, and v8::internal::TimedHistogram::Initialize().
Visit() [5/7]
void v8::internal::CountersInitializer::Visit (PercentageHistogram * histogram, const char * caption) [final], [protected], [virtual]
Reimplemented from v8::internal::CountersVisitor.
Definition at line 118 of file counters.cc.
                                                     {
  histogram->Initialize(caption, 0, 101, 100, counters());
}
References v8::internal::CountersVisitor::counters(), and v8::internal::Histogram::Initialize().
Visit() [6/7]
void v8::internal::CountersInitializer::Visit (StatsCounter * counter, const char * caption) [final], [protected], [virtual]
Reimplemented from v8::internal::CountersVisitor.
Definition at line 153 of file counters.cc.
                                                                          {
  counter->Initialize(caption, counters());
}
References v8::internal::CountersVisitor::counters(), and v8::internal::StatsCounter::Initialize().
Visit() [7/7]
void v8::internal::CountersInitializer::Visit (TimedHistogram * histogram, const char * caption, int max, TimedHistogramResolution res) [final], [protected], [virtual]
Reimplemented from v8::internal::CountersVisitor.
Definition at line 134 of file counters.cc.
                                                                       {
  histogram->Initialize(caption, 0, max, res, DefaultTimedHistogramNumBuckets,
                        counters());
}
References v8::internal::CountersVisitor::counters(), v8::internal::anonymous_namespace{counters.cc}::DefaultTimedHistogramNumBuckets, and v8::internal::TimedHistogram::Initialize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/counters.h
/mnt/V8SourceCode/src/logging/counters.cc