v8::internal::compiler::SourceIdAssigner Class Reference
#include <turbofan-graph-visualizer.h>
Public Member Functions
SourceIdAssigner (size_t size)
int GetIdFor (Handle< SharedFunctionInfo > shared)
int GetIdAt (size_t pos) const
Private Attributes
std::vector< Handle< SharedFunctionInfo > > printed_
std::vector< int > source_ids_
Detailed Description
Definition at line 114 of file turbofan-graph-visualizer.h.
Constructor & Destructor Documentation
SourceIdAssigner()
v8::internal::compiler::SourceIdAssigner::SourceIdAssigner (size_t size) [inline], [explicit]
Definition at line 116 of file turbofan-graph-visualizer.h.
                                         {
    printed_.reserve(size);
    source_ids_.reserve(size);
  }
References size().
Member Function Documentation
GetIdAt()
int v8::internal::compiler::SourceIdAssigner::GetIdAt (size_t pos) const [inline]
Definition at line 121 of file turbofan-graph-visualizer.h.
{ return source_ids_[pos]; }
Referenced by v8::internal::compiler::JsonPrintAllSourceWithPositions().
GetIdFor()
int v8::internal::compiler::SourceIdAssigner::GetIdFor (Handle< SharedFunctionInfo > shared)
Definition at line 150 of file turbofan-graph-visualizer.cc.
                                                                {
  for (unsigned i = 0; i < printed_.size(); i++) {
    if (printed_.at(i).is_identical_to(shared)) {
      source_ids_.push_back(i);
      return i;
    }
  }
  const int source_id = static_cast<int>(printed_.size());
  printed_.push_back(shared);
  source_ids_.push_back(source_id);
  return source_id;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, printed_, and source_ids_.
Referenced by v8::internal::compiler::JsonPrintAllBytecodeSources(), v8::internal::compiler::JsonPrintAllSourceWithPositions(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintParticipatingSource().
Member Data Documentation
printed_
std::vector<Handle<SharedFunctionInfo> > v8::internal::compiler::SourceIdAssigner::printed_ [private]
Definition at line 124 of file turbofan-graph-visualizer.h.
Referenced by GetIdFor().
source_ids_
std::vector<int> v8::internal::compiler::SourceIdAssigner::source_ids_ [private]
Definition at line 125 of file turbofan-graph-visualizer.h.
Referenced by GetIdFor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turbofan-graph-visualizer.h
/mnt/V8SourceCode/src/compiler/turbofan-graph-visualizer.cc