v8::internal::ConstructStubFrameInfo Class Reference
#include <frames.h>
Public Member Functions
uint32_t frame_size_in_bytes_without_fixed () const
uint32_t frame_size_in_bytes () const
Static Public Member Functions
static ConstructStubFrameInfo Precise (int translation_height, bool is_topmost)
static ConstructStubFrameInfo Conservative (int parameters_count)
Private Member Functions
ConstructStubFrameInfo (int translation_height, bool is_topmost, FrameInfoKind frame_info_kind)
Private Attributes
uint32_t frame_size_in_bytes_without_fixed_
uint32_t frame_size_in_bytes_
Detailed Description
Definition at line 1926 of file frames.h.
Constructor & Destructor Documentation
ConstructStubFrameInfo()
v8::internal::ConstructStubFrameInfo::ConstructStubFrameInfo (int translation_height, bool is_topmost, FrameInfoKind frame_info_kind) [private]
Definition at line 4236 of file frames.cc.
                                                                              {
  // Note: This is according to the Translation's notion of 'parameters' which
  // differs to that of the SharedFunctionInfo, e.g. by including the receiver.
  const int parameters_count = translation_height;
  // If the construct frame appears to be topmost we should ensure that the
  // value of result register is preserved during continuation execution.
  // We do this here by "pushing" the result of the constructor function to
  // the top of the reconstructed stack and popping it in
  // {Builtin::kNotifyDeoptimized}.
  static constexpr int kTopOfStackPadding = TopOfStackRegisterPaddingSlots();
  static constexpr int kTheResult = 1;
  const int argument_padding = ArgumentPaddingSlots(parameters_count);
  const int adjusted_height =
      (is_topmost || frame_info_kind == FrameInfoKind::kConservative)
          ? parameters_count + argument_padding + kTheResult +
                kTopOfStackPadding
          : parameters_count + argument_padding;
  frame_size_in_bytes_without_fixed_ = adjusted_height * kSystemPointerSize;
  frame_size_in_bytes_ = frame_size_in_bytes_without_fixed_ +
                         ConstructFrameConstants::kFixedFrameSize;
}
References v8::internal::ArgumentPaddingSlots(), v8::internal::kConservative, v8::internal::TypedFrameConstants::kFixedFrameSize, v8::internal::kSystemPointerSize, and v8::internal::anonymous_namespace{frames.cc}::TopOfStackRegisterPaddingSlots().
Member Function Documentation
Conservative()
static ConstructStubFrameInfo v8::internal::ConstructStubFrameInfo::Conservative (int parameters_count) [inline], [static]
Definition at line 1933 of file frames.h.
                                                                   {
    return {parameters_count, false, FrameInfoKind::kConservative};
  }
References v8::internal::kConservative.
Referenced by v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes().
frame_size_in_bytes()
uint32_t v8::internal::ConstructStubFrameInfo::frame_size_in_bytes () const [inline]
Definition at line 1940 of file frames.h.
{ return frame_size_in_bytes_; }
References frame_size_in_bytes_.
Referenced by v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame().
frame_size_in_bytes_without_fixed()
uint32_t v8::internal::ConstructStubFrameInfo::frame_size_in_bytes_without_fixed () const [inline]
Definition at line 1937 of file frames.h.
                                                     {
    return frame_size_in_bytes_without_fixed_;
  }
References frame_size_in_bytes_without_fixed_.
Referenced by v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame().
Precise()
static ConstructStubFrameInfo v8::internal::ConstructStubFrameInfo::Precise (int translation_height, bool is_topmost) [inline], [static]
Definition at line 1928 of file frames.h.
                                                         {
    return {translation_height, is_topmost, FrameInfoKind::kPrecise};
  }
References v8::internal::kPrecise.
Referenced by v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame().
Member Data Documentation
frame_size_in_bytes_
uint32_t v8::internal::ConstructStubFrameInfo::frame_size_in_bytes_ [private]
Definition at line 1947 of file frames.h.
Referenced by frame_size_in_bytes().
frame_size_in_bytes_without_fixed_
uint32_t v8::internal::ConstructStubFrameInfo::frame_size_in_bytes_without_fixed_ [private]
Definition at line 1946 of file frames.h.
Referenced by frame_size_in_bytes_without_fixed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc