v8::internal::compiler::JSONGraphWriter Class Reference
#include <turbofan-graph-visualizer.h>
Public Member Functions
JSONGraphWriter (std::ostream &os, const TFGraph *graph, const SourcePositionTable *positions, const NodeOriginTable *origins)
JSONGraphWriter (const JSONGraphWriter &)=delete
JSONGraphWriter & operator= (const JSONGraphWriter &)=delete
void PrintPhase (const char *phase_name)
void Print ()
Protected Member Functions
void PrintNode (Node *node, bool is_live)
void PrintEdges (Node *node)
void PrintEdge (Node *from, int index, Node *to)
virtual std::optional< Type > GetType (Node *node)
Protected Attributes
std::ostream & os_
Zone * zone_
const TFGraph * graph_
const SourcePositionTable * positions_
const NodeOriginTable * origins_
bool first_node_
bool first_edge_
Detailed Description
Definition at line 159 of file turbofan-graph-visualizer.h.
Constructor & Destructor Documentation
JSONGraphWriter() [1/2]
v8::internal::compiler::JSONGraphWriter::JSONGraphWriter (std::ostream & os, const TFGraph * graph, const SourcePositionTable * positions, const NodeOriginTable * origins)
Definition at line 386 of file turbofan-graph-visualizer.cc.
    : os_(os),
      zone_(nullptr),
      graph_(graph),
      positions_(positions),
      origins_(origins),
      first_node_(true),
      first_edge_(true) {}
JSONGraphWriter() [2/2]
v8::internal::compiler::JSONGraphWriter::JSONGraphWriter (const JSONGraphWriter &) [delete]
Member Function Documentation
GetType()
std::optional< Type > v8::internal::compiler::JSONGraphWriter::GetType (Node * node) [protected], [virtual]
Reimplemented in v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::JSONGraphWriterWithVerifierTypes.
Definition at line 510 of file turbofan-graph-visualizer.cc.
                                                     {
  if (!NodeProperties::IsTyped(node)) return std::nullopt;
  return NodeProperties::GetType(node);
}
References v8::internal::compiler::NodeProperties::GetType(), and v8::internal::compiler::NodeProperties::IsTyped().
Referenced by PrintNode().
operator=()
JSONGraphWriter& v8::internal::compiler::JSONGraphWriter::operator= (const JSONGraphWriter &) [delete]
Print()
void v8::internal::compiler::JSONGraphWriter::Print ()
Definition at line 403 of file turbofan-graph-visualizer.cc.
                            {
  AccountingAllocator allocator;
  Zone tmp_zone(&allocator, ZONE_NAME);
  zone_ = &tmp_zone;
  AllNodes all(zone_, graph_, false);
  AllNodes live(zone_, graph_, true);
  os_ << "{\n\"nodes\":[";
  for (Node* const node : all.reachable) PrintNode(node, live.IsLive(node));
  os_ << "\n";
  os_ << "],\n\"edges\":[";
  for (Node* const node : all.reachable) PrintEdges(node);
  os_ << "\n";
  os_ << "]}";
  zone_ = nullptr;
}
References all, graph_, v8::internal::compiler::AllNodes::IsLive(), os_, PrintEdges(), PrintNode(), zone_, and ZONE_NAME.
Referenced by v8::internal::compiler::operator<<(), and PrintPhase().
PrintEdge()
void v8::internal::compiler::JSONGraphWriter::PrintEdge (Node * from, int index, Node * to) [protected]
Definition at line 486 of file turbofan-graph-visualizer.cc.
                                                               {
  if (first_edge_) {
    first_edge_ = false;
  } else {
    os_ << ",\n";
  }
  const char* edge_type = nullptr;
  if (index < NodeProperties::FirstValueIndex(from)) {
    edge_type = "unknown";
  } else if (index < NodeProperties::FirstContextIndex(from)) {
    edge_type = "value";
  } else if (index < NodeProperties::FirstFrameStateIndex(from)) {
    edge_type = "context";
  } else if (index < NodeProperties::FirstEffectIndex(from)) {
    edge_type = "frame-state";
  } else if (index < NodeProperties::FirstControlIndex(from)) {
    edge_type = "effect";
  } else {
    edge_type = "control";
  }
  os_ << "{\"source\":" << SafeId(to) << ",\"target\":" << SafeId(from)
      << ",\"index\":" << index << ",\"type\":\"" << edge_type << "\"}";
}
References first_edge_, v8::internal::compiler::NodeProperties::FirstContextIndex(), v8::internal::compiler::NodeProperties::FirstControlIndex(), v8::internal::compiler::NodeProperties::FirstEffectIndex(), v8::internal::compiler::NodeProperties::FirstFrameStateIndex(), v8::internal::compiler::NodeProperties::FirstValueIndex(), v8::internal::index, os_, and v8::internal::compiler::SafeId().
Referenced by PrintEdges().
PrintEdges()
void v8::internal::compiler::JSONGraphWriter::PrintEdges (Node * node) [protected]
Definition at line 478 of file turbofan-graph-visualizer.cc.
                                           {
  for (int i = 0; i < node->InputCount(); i++) {
    Node* input = node->InputAt(i);
    if (input == nullptr) continue;
    PrintEdge(node, i, input);
  }
}
References v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), and PrintEdge().
Referenced by Print().
PrintNode()
void v8::internal::compiler::JSONGraphWriter::PrintNode (Node * node, bool is_live) [protected]
Definition at line 421 of file turbofan-graph-visualizer.cc.
                                                        {
  if (first_node_) {
    first_node_ = false;
  } else {
    os_ << ",\n";
  }
  std::ostringstream label, title, properties;
  node->op()->PrintTo(label, Operator::PrintVerbosity::kSilent);
  node->op()->PrintTo(title, Operator::PrintVerbosity::kVerbose);
  node->op()->PrintPropsTo(properties);
  os_ << "{\"id\":" << SafeId(node) << ",\"label\":\"" << JSONEscaped(label)
      << "\"" << ",\"title\":\"" << JSONEscaped(title) << "\""
      << ",\"live\": " << (is_live ? "true" : "false") << ",\"properties\":\""
      << JSONEscaped(properties) << "\"";
  IrOpcode::Value opcode = node->opcode();
  if (IrOpcode::IsPhiOpcode(opcode)) {
    os_ << ",\"rankInputs\":[0," << NodeProperties::FirstControlIndex(node)
        << "]";
    os_ << ",\"rankWithInput\":[" << NodeProperties::FirstControlIndex(node)
        << "]";
  } else if (opcode == IrOpcode::kIfTrue || opcode == IrOpcode::kIfFalse ||
             opcode == IrOpcode::kLoop) {
    os_ << ",\"rankInputs\":[" << NodeProperties::FirstControlIndex(node)
        << "]";
  }
  if (opcode == IrOpcode::kBranch) {
    os_ << ",\"rankInputs\":[0]";
  }
  if (positions_ != nullptr) {
    SourcePosition position = positions_->GetSourcePosition(node);
    if (position.IsKnown()) {
      os_ << ", \"sourcePosition\" : " << AsJSON(position);
    }
  }
  if (origins_) {
    NodeOrigin origin = origins_->GetNodeOrigin(node);
    if (origin.IsKnown()) {
      os_ << ", \"origin\" : " << AsJSON(origin);
    }
  }
  os_ << ",\"opcode\":\"" << IrOpcode::Mnemonic(node->opcode()) << "\"";
  os_ << ",\"control\":"
      << (NodeProperties::IsControl(node) ? "true" : "false");
  os_ << ",\"opinfo\":\"" << node->op()->ValueInputCount() << " v "
      << node->op()->EffectInputCount() << " eff "
      << node->op()->ControlInputCount() << " ctrl in, "
      << node->op()->ValueOutputCount() << " v "
      << node->op()->EffectOutputCount() << " eff "
      << node->op()->ControlOutputCount() << " ctrl out\"";
  if (auto type_opt = GetType(node)) {
    std::ostringstream type_out;
    type_opt->PrintTo(type_out);
    os_ << ",\"type\":\"" << JSONEscaped(type_out) << "\"";
  }
  os_ << "}";
}
References v8::internal::compiler::AsJSON(), v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), first_node_, v8::internal::compiler::NodeProperties::FirstControlIndex(), v8::internal::compiler::NodeOriginTable::GetNodeOrigin(), v8::internal::compiler::SourcePositionTable::GetSourcePosition(), GetType(), v8::internal::compiler::NodeProperties::IsControl(), v8::internal::compiler::NodeOrigin::IsKnown(), v8::internal::SourcePosition::IsKnown(), v8::internal::compiler::IrOpcode::IsPhiOpcode(), v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::Operator::kSilent, v8::internal::compiler::Operator::kVerbose, v8::internal::compiler::IrOpcode::Mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), origins_, os_, positions_, v8::internal::compiler::Operator::PrintPropsTo(), v8::internal::compiler::Operator::PrintTo(), v8::internal::compiler::SafeId(), v8::internal::compiler::Operator::ValueInputCount(), and v8::internal::compiler::Operator::ValueOutputCount().
Referenced by Print().
PrintPhase()
void v8::internal::compiler::JSONGraphWriter::PrintPhase (const char * phase_name)
Definition at line 397 of file turbofan-graph-visualizer.cc.
                                                       {
  os_ << "{\"name\":\"" << phase_name << "\",\"type\":\"graph\",\"data\":";
  Print();
  os_ << "},\n";
}
References os_, and Print().
Referenced by v8::internal::compiler::RepresentationSelector::RunVerifyPhase().
Member Data Documentation
first_edge_
bool v8::internal::compiler::JSONGraphWriter::first_edge_ [protected]
Definition at line 184 of file turbofan-graph-visualizer.h.
Referenced by PrintEdge().
first_node_
bool v8::internal::compiler::JSONGraphWriter::first_node_ [protected]
Definition at line 183 of file turbofan-graph-visualizer.h.
Referenced by PrintNode().
graph_
const TFGraph* v8::internal::compiler::JSONGraphWriter::graph_ [protected]
Definition at line 180 of file turbofan-graph-visualizer.h.
Referenced by Print().
origins_
const NodeOriginTable* v8::internal::compiler::JSONGraphWriter::origins_ [protected]
Definition at line 182 of file turbofan-graph-visualizer.h.
Referenced by PrintNode().
os_
std::ostream& v8::internal::compiler::JSONGraphWriter::os_ [protected]
Definition at line 178 of file turbofan-graph-visualizer.h.
Referenced by Print(), PrintEdge(), PrintNode(), and PrintPhase().
positions_
const SourcePositionTable* v8::internal::compiler::JSONGraphWriter::positions_ [protected]
Definition at line 181 of file turbofan-graph-visualizer.h.
Referenced by PrintNode().
zone_
Zone* v8::internal::compiler::JSONGraphWriter::zone_ [protected]
Definition at line 179 of file turbofan-graph-visualizer.h.
Referenced by Print().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turbofan-graph-visualizer.h
/mnt/V8SourceCode/src/compiler/turbofan-graph-visualizer.cc