v8::internal::compiler::UseInterval Class Reference
#include <register-allocator.h>
Public Member Functions
UseInterval (LifetimePosition start, LifetimePosition end)
LifetimePosition start () const
void set_start (LifetimePosition start)
LifetimePosition end () const
void set_end (LifetimePosition end)
UseInterval SplitAt (LifetimePosition pos)
LifetimePosition Intersect (const UseInterval &other) const
bool Contains (LifetimePosition point) const
int FirstGapIndex () const
int LastGapIndex () const
bool operator== (const UseInterval &other) const
bool operator!= (const UseInterval &other) const
bool operator< (const UseInterval &other) const
void PrettyPrint (std::ostream &os) const
Private Attributes
LifetimePosition start_
LifetimePosition end_
Detailed Description
Definition at line 373 of file register-allocator.h.
Constructor & Destructor Documentation
UseInterval()
v8::internal::compiler::UseInterval::UseInterval (LifetimePosition start, LifetimePosition end) [inline]
Definition at line 375 of file register-allocator.h.
      : start_(start), end_(end) {
    DCHECK_LT(start, end);
  }
References DCHECK_LT, end(), and start().
Member Function Documentation
Contains()
bool v8::internal::compiler::UseInterval::Contains (LifetimePosition point) const [inline]
Definition at line 409 of file register-allocator.h.
                                              {
    return start_ <= point && point < end_;
  }
References end_, and start_.
Referenced by v8::internal::compiler::LiveRange::Covers(), and SplitAt().
end()
LifetimePosition v8::internal::compiler::UseInterval::end () const [inline]
Definition at line 385 of file register-allocator.h.
{ return end_; }
References end_.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), v8::internal::compiler::LiveRange::NextEndAfter(), PrettyPrint(), v8::internal::compiler::LinearScanAllocator::PrintRangeRow(), set_end(), v8::internal::compiler::SpillRange::SpillRange(), v8::internal::compiler::LiveRange::SplitAt(), and UseInterval().
FirstGapIndex()
int v8::internal::compiler::UseInterval::FirstGapIndex () const [inline]
Definition at line 414 of file register-allocator.h.
                            {
    int ret = start_.ToInstructionIndex();
    if (start_.IsInstructionPosition()) {
      ++ret;
    }
    return ret;
  }
References v8::internal::compiler::LifetimePosition::IsInstructionPosition(), start_, and v8::internal::compiler::LifetimePosition::ToInstructionIndex().
Referenced by v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred().
Intersect()
LifetimePosition v8::internal::compiler::UseInterval::Intersect (const UseInterval & other) const [inline]
Definition at line 402 of file register-allocator.h.
                                                             {
    LifetimePosition intersection_start = std::max(start_, other.start_);
    LifetimePosition intersection_end = std::min(end_, other.end_);
    if (intersection_start < intersection_end) return intersection_start;
    return LifetimePosition::Invalid();
  }
References end_, v8::internal::compiler::LifetimePosition::Invalid(), and start_.
Referenced by v8::internal::compiler::LiveRange::FirstIntersection().
LastGapIndex()
int v8::internal::compiler::UseInterval::LastGapIndex () const [inline]
Definition at line 423 of file register-allocator.h.
                           {
    int ret = end_.ToInstructionIndex();
    if (end_.IsGapPosition() && end_.IsStart()) {
      --ret;
    }
    return ret;
  }
References end_, v8::internal::compiler::LifetimePosition::IsGapPosition(), v8::internal::compiler::LifetimePosition::IsStart(), and v8::internal::compiler::LifetimePosition::ToInstructionIndex().
Referenced by v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred().
operator!=()
bool v8::internal::compiler::UseInterval::operator!= (const UseInterval & other) const [inline]
Definition at line 434 of file register-allocator.h.
{ return !(*this == other); }
operator<()
bool v8::internal::compiler::UseInterval::operator< (const UseInterval & other) const [inline]
Definition at line 436 of file register-allocator.h.
                                                 {
    return start_ < other.start_;
  }
References start_.
operator==()
bool v8::internal::compiler::UseInterval::operator== (const UseInterval & other) const [inline]
Definition at line 431 of file register-allocator.h.
                                                  {
    return std::tie(start_, end_) == std::tie(other.start_, other.end_);
  }
References end_, and start_.
PrettyPrint()
void v8::internal::compiler::UseInterval::PrettyPrint (std::ostream & os) const [inline]
Definition at line 440 of file register-allocator.h.
                                         {
    os << '[' << start() << ", " << end() << ')';
  }
References end(), and start().
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::SpillRange::Print().
set_end()
void v8::internal::compiler::UseInterval::set_end (LifetimePosition end) [inline]
Definition at line 386 of file register-allocator.h.
                                     {
    DCHECK_LT(start_, end);
    end_ = end;
  }
References DCHECK_LT, end(), end_, and start_.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval().
set_start()
void v8::internal::compiler::UseInterval::set_start (LifetimePosition start) [inline]
Definition at line 381 of file register-allocator.h.
                                         {
    DCHECK_LT(start, end_);
    start_ = start;
  }
References DCHECK_LT, end_, start(), and start_.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), and v8::internal::compiler::TopLevelLiveRange::ShortenTo().
SplitAt()
UseInterval v8::internal::compiler::UseInterval::SplitAt (LifetimePosition pos) [inline]
Definition at line 393 of file register-allocator.h.
                                            {
    DCHECK(Contains(pos) && pos != start());
    UseInterval after(pos, end_);
    end_ = pos;
    return after;
  }
References Contains(), v8::internal::DCHECK(), end_, and start().
Referenced by v8::internal::compiler::LiveRange::SplitAt().
start()
LifetimePosition v8::internal::compiler::UseInterval::start () const [inline]
Definition at line 380 of file register-allocator.h.
{ return start_; }
References start_.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::LiveRange::AdvanceLastProcessedMarker(), v8::internal::compiler::LiveRange::Covers(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), v8::internal::compiler::LiveRange::FirstIntersection(), v8::internal::compiler::LiveRange::FirstSearchIntervalForPosition(), v8::internal::compiler::LiveRange::NextStartAfter(), PrettyPrint(), v8::internal::compiler::LinearScanAllocator::PrintRangeRow(), set_start(), v8::internal::compiler::TopLevelLiveRange::ShortenTo(), v8::internal::compiler::SpillRange::SpillRange(), SplitAt(), and UseInterval().
Member Data Documentation
end_
LifetimePosition v8::internal::compiler::UseInterval::end_ [private]
Definition at line 446 of file register-allocator.h.
Referenced by Contains(), end(), Intersect(), LastGapIndex(), operator==(), set_end(), set_start(), and SplitAt().
start_
LifetimePosition v8::internal::compiler::UseInterval::start_ [private]
Definition at line 445 of file register-allocator.h.
Referenced by Contains(), FirstGapIndex(), Intersect(), operator<(), operator==(), set_end(), set_start(), and start().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h