v8::internal::RootMarkingVisitor Class Reference
#include <mark-compact.h>
Public Member Functions
RootMarkingVisitor (MarkCompactCollector *collector)
~RootMarkingVisitor ()
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) final
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
void VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot istream_or_smi_zero_slot) final
RootMarkingVisitor (const RootMarkingVisitor &)=delete
RootMarkingVisitor & operator= (const RootMarkingVisitor &)=delete
Private Member Functions
void MarkObjectByPointer (Root root, FullObjectSlot p)
Private Attributes
MarkCompactCollector *const collector_
Additional Inherited Members
Detailed Description
Definition at line 31 of file mark-compact.h.
Constructor & Destructor Documentation
RootMarkingVisitor() [1/2]
v8::internal::RootMarkingVisitor::RootMarkingVisitor (MarkCompactCollector * collector) [explicit]
Definition at line 6232 of file mark-compact.cc.
    : collector_(collector) {}
 RootMarkingVisitor()
v8::internal::RootMarkingVisitor::~RootMarkingVisitor () [default]
RootMarkingVisitor() [2/2]
v8::internal::RootMarkingVisitor::RootMarkingVisitor (const RootMarkingVisitor &) [delete]
Member Function Documentation
MarkObjectByPointer()
void v8::internal::RootMarkingVisitor::MarkObjectByPointer (Root root, FullObjectSlot p) [inline], [private]
Definition at line 122 of file mark-compact-inl.h.
                                                                        {
  Tagged<Object> object = *p;
#ifdef V8_ENABLE_DIRECT_HANDLE
  if (object.ptr() == kTaggedNullAddress) return;
#endif
  if (!IsHeapObject(object)) return;
  Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
  const auto target_worklist =
      MarkingHelper::ShouldMarkObject(collector_->heap(), heap_object);
  if (!target_worklist) {
    return;
  }
  collector_->MarkRootObject(root, heap_object, target_worklist.value());
}
References collector_, v8::internal::MarkCompactCollector::heap(), v8::internal::IsHeapObject(), v8::internal::kTaggedNullAddress, v8::internal::MarkCompactCollector::MarkRootObject(), and v8::internal::MarkingHelper::ShouldMarkObject().
Referenced by VisitRootPointer(), and VisitRootPointers().
operator=()
RootMarkingVisitor& v8::internal::RootMarkingVisitor::operator= (const RootMarkingVisitor &) [delete]
VisitRootPointer()
void v8::internal::RootMarkingVisitor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 108 of file mark-compact-inl.h.
                                                            {
  DCHECK(!MapWord::IsPacked(p.Relaxed_Load().ptr()));
  MarkObjectByPointer(root, p);
}
References v8::internal::DCHECK(), v8::internal::MapWord::IsPacked(), MarkObjectByPointer(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::FullObjectSlot::Relaxed_Load().
Referenced by VisitRunningCode().
VisitRootPointers()
void v8::internal::RootMarkingVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 114 of file mark-compact-inl.h.
                                                               {
  for (FullObjectSlot p = start; p < end; ++p) {
    MarkObjectByPointer(root, p);
  }
}
References v8::internal::compiler::end(), and MarkObjectByPointer().
VisitRunningCode()
void v8::internal::RootMarkingVisitor::VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot istream_or_smi_zero_slot) [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 6237 of file mark-compact.cc.
                                                                       {
  Tagged<Object> istream_or_smi_zero = *istream_or_smi_zero_slot;
  DCHECK(istream_or_smi_zero == Smi::zero() ||
         IsInstructionStream(istream_or_smi_zero));
  Tagged<Code> code = Cast<Code>(*code_slot);
  DCHECK_EQ(code->raw_instruction_stream(PtrComprCageBase{
                collector_->heap()->isolate()->code_cage_base()}),
            istream_or_smi_zero);
  // We must not remove deoptimization literals which may be needed in
  // order to successfully deoptimize.
  code->IterateDeoptimizationLiterals(this);
  if (istream_or_smi_zero != Smi::zero()) {
    VisitRootPointer(Root::kStackRoots, nullptr, istream_or_smi_zero_slot);
  }
  VisitRootPointer(Root::kStackRoots, nullptr, code_slot);
}
References code, v8::internal::DCHECK(), DCHECK_EQ, VisitRootPointer(), and v8::internal::Smi::zero().
Member Data Documentation
collector_
MarkCompactCollector* const v8::internal::RootMarkingVisitor::collector_ [private]
Definition at line 53 of file mark-compact.h.
Referenced by MarkObjectByPointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/mark-compact.h
/mnt/V8SourceCode/src/heap/mark-compact-inl.h
/mnt/V8SourceCode/src/heap/mark-compact.cc