v8::internal::wasm::AsyncCompileJob::DecodeModule Class Reference
Public Member Functions
DecodeModule (Counters *counters, std::shared_ptr< metrics::Recorder > metrics_recorder)
void RunInBackground (AsyncCompileJob *job) override
Private Attributes
Counters *const counters_
std::shared_ptr< metrics::Recorder > metrics_recorder_
Detailed Description
Definition at line 3038 of file module-compiler.cc.
Constructor & Destructor Documentation
DecodeModule()
v8::internal::wasm::AsyncCompileJob::DecodeModule::DecodeModule (Counters * counters, std::shared_ptr< metrics::Recorder > metrics_recorder) [inline], [explicit]
Definition at line 3040 of file module-compiler.cc.
      : counters_(counters), metrics_recorder_(std::move(metrics_recorder)) {}
Member Function Documentation
RunInBackground()
void v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground (AsyncCompileJob * job) [inline], [override], [virtual]
Reimplemented from v8::internal::wasm::AsyncCompileJob::CompileStep.
Definition at line 3044 of file module-compiler.cc.
                                                      {
    ModuleResult result;
    {
      DisallowHandleAllocation no_handle;
      DisallowGarbageCollection no_gc;
      // Decode the module bytes.
      TRACE_COMPILE("(1) Decoding module...\n");
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
                   "wasm.DecodeModule");
      auto enabled_features = job->enabled_features_;
      result = DecodeWasmModule(
          enabled_features, job->wire_bytes_.module_bytes(), false, kWasmOrigin,
          counters_, metrics_recorder_, job->context_id(),
          DecodingMethod::kAsync, &job->detected_features_);
      // Validate lazy functions here if requested.
      if (result.ok() && !v8_flags.wasm_lazy_validation) {
        const WasmModule* module = result.value().get();
        if (WasmError validation_error = ValidateFunctions(
                module, job->wire_bytes_.module_bytes(), job->enabled_features_,
                kOnlyLazyFunctions, &job->detected_features_)) {
          result = ModuleResult{std::move(validation_error)};
        }
      }
      if (result.ok()) {
        const WasmModule* module = result.value().get();
        if (WasmError error = ValidateAndSetBuiltinImports(
                module, job->wire_bytes_.module_bytes(), job->compile_imports_,
                &job->detected_features_)) {
          result = ModuleResult{std::move(error)};
        }
      }
    }
    if (result.failed()) {
      // Decoding failure; reject the promise and clean up.
      job->DoSync<Fail>();
    } else {
      // Decode passed.
      std::shared_ptr<WasmModule> module = std::move(result).value();
      size_t code_size_estimate =
          wasm::WasmCodeManager::EstimateNativeModuleCodeSize(module.get());
      job->DoSync<PrepareAndStartCompile>(
          std::move(module), true /* start_compilation */,
          true /* lazy_functions_are_validated */, code_size_estimate);
    }
  }
References v8::internal::wasm::AsyncCompileJob::compile_imports_, v8::internal::wasm::AsyncCompileJob::context_id(), counters_, v8::internal::wasm::DecodeWasmModule(), v8::internal::wasm::AsyncCompileJob::detected_features_, v8::internal::wasm::AsyncCompileJob::DoSync(), v8::internal::wasm::AsyncCompileJob::enabled_features_, v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), v8::internal::wasm::kAsync, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kOnlyLazyFunctions, v8::internal::wasm::kWasmOrigin, metrics_recorder_, v8::internal::wasm::ModuleWireBytes::module_bytes(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, TRACE_COMPILE, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8::internal::v8_flags, v8::internal::wasm::ValidateAndSetBuiltinImports(), v8::internal::wasm::ValidateFunctions(), and v8::internal::wasm::AsyncCompileJob::wire_bytes_.
Member Data Documentation
counters_
Counters* const v8::internal::wasm::AsyncCompileJob::DecodeModule::counters_ [private]
Definition at line 3092 of file module-compiler.cc.
Referenced by RunInBackground().
metrics_recorder_
std::shared_ptr<metrics::Recorder> v8::internal::wasm::AsyncCompileJob::DecodeModule::metrics_recorder_ [private]
Definition at line 3093 of file module-compiler.cc.
Referenced by RunInBackground().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc