v8::internal::compiler::BigIntOperationParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
BigIntOperationParameters (BigIntOperationHint hint, const FeedbackSource &feedback)
BigIntOperationHint hint () const
const FeedbackSource & feedback () const
Private Attributes
BigIntOperationHint hint_
FeedbackSource feedback_
Detailed Description
Definition at line 635 of file simplified-operator.h.
Constructor & Destructor Documentation
BigIntOperationParameters()
v8::internal::compiler::BigIntOperationParameters::BigIntOperationParameters (BigIntOperationHint hint, const FeedbackSource & feedback) [inline]
Definition at line 637 of file simplified-operator.h.
      : hint_(hint), feedback_(feedback) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::BigIntOperationParameters::feedback () const [inline]
Definition at line 642 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitNode().
hint()
BigIntOperationHint v8::internal::compiler::BigIntOperationParameters::hint () const [inline]
Definition at line 641 of file simplified-operator.h.
{ return hint_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::BigIntOperationParameters::feedback_ [private]
Definition at line 646 of file simplified-operator.h.
hint_
BigIntOperationHint v8::internal::compiler::BigIntOperationParameters::hint_ [private]
Definition at line 645 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h