v8::internal::maglev::ZoneLabelRef Class Reference
#include <maglev-assembler.h>
Public Member Functions
ZoneLabelRef (Zone *zone)
ZoneLabelRef (MaglevAssembler *masm)
Label * operator* ()
Static Public Member Functions
static ZoneLabelRef UnsafeFromLabelPointer (Label *label)
Private Member Functions
ZoneLabelRef (Label *label)
Private Attributes
Label * label_
Detailed Description
Definition at line 50 of file maglev-assembler.h.
Constructor & Destructor Documentation
ZoneLabelRef() [1/3]
v8::internal::maglev::ZoneLabelRef::ZoneLabelRef (Zone * zone) [inline], [explicit]
Definition at line 52 of file maglev-assembler.h.
: label_(zone->New<Label>()) {}
Referenced by UnsafeFromLabelPointer().
ZoneLabelRef() [2/3]
v8::internal::maglev::ZoneLabelRef::ZoneLabelRef (MaglevAssembler * masm) [inline], [explicit]
Definition at line 988 of file maglev-assembler.h.
    : ZoneLabelRef(masm->compilation_info()->zone()) {}
ZoneLabelRef() [3/3]
v8::internal::maglev::ZoneLabelRef::ZoneLabelRef (Label * label) [inline], [explicit], [private]
Definition at line 66 of file maglev-assembler.h.
: label_(label) {}
Member Function Documentation
operator*()
Label* v8::internal::maglev::ZoneLabelRef::operator* () [inline]
Definition at line 60 of file maglev-assembler.h.
{ return label_; }
References label_.
UnsafeFromLabelPointer()
static ZoneLabelRef v8::internal::maglev::ZoneLabelRef::UnsafeFromLabelPointer (Label * label) [inline], [static]
Definition at line 55 of file maglev-assembler.h.
                                                           {
    // This is an unsafe operation, {label} must be zone allocated.
    return ZoneLabelRef(label);
  }
References ZoneLabelRef().
Referenced by v8::internal::maglev::MaglevAssembler::JumpIfHoleNan().
Member Data Documentation
label_
Label* v8::internal::maglev::ZoneLabelRef::label_ [private]
Definition at line 63 of file maglev-assembler.h.
Referenced by operator*().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-assembler.h