v8::internal::maglev::AllocationBlock Class Reference
#include <maglev-ir.h>
Public Member Functions
AllocationBlock (uint64_t bitfield, AllocationType allocation_type)
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
AllocationType allocation_type () const
int size () const
void set_size (int size)
InlinedAllocation::List & allocation_list ()
void Add (InlinedAllocation *alloc)
void TryPretenure (ValueNode *input)
bool elided_write_barriers_depend_on_type () const
void set_elided_write_barriers_depend_on_type ()
Static Public Attributes
static constexpr OpProperties kProperties
Private Types
using Base = FixedInputValueNodeT< 0, AllocationBlock >
Private Member Functions
void TryPretenure ()
Private Attributes
AllocationType allocation_type_
int size_ = 0
bool elided_write_barriers_depend_on_type_ = false
InlinedAllocation::List allocation_list_
Additional Inherited Members
Detailed Description
Definition at line 6448 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::AllocationBlock::Base = FixedInputValueNodeT<0, AllocationBlock> [private]
Definition at line 6449 of file maglev-ir.h.
Constructor & Destructor Documentation
AllocationBlock()
v8::internal::maglev::AllocationBlock::AllocationBlock (uint64_t bitfield, AllocationType allocation_type) [inline], [explicit]
Definition at line 6452 of file maglev-ir.h.
      : Base(bitfield), allocation_type_(allocation_type) {}
Member Function Documentation
Add()
void v8::internal::maglev::AllocationBlock::Add (InlinedAllocation * alloc) [inline]
Definition at line 6470 of file maglev-ir.h.
                                     {
    allocation_list_.Add(alloc);
    size_ += alloc->size();
  }
References v8::internal::maglev::InlinedAllocation::size().
allocation_list()
InlinedAllocation::List& v8::internal::maglev::AllocationBlock::allocation_list () [inline]
Definition at line 6468 of file maglev-ir.h.
{ return allocation_list_; }
Referenced by v8::internal::maglev::DeadNodeSweepingProcessor::Process(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
allocation_type()
AllocationType v8::internal::maglev::AllocationBlock::allocation_type () const [inline]
Definition at line 6464 of file maglev-ir.h.
{ return allocation_type_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::CanElideWriteBarrier(), PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
elided_write_barriers_depend_on_type()
bool v8::internal::maglev::AllocationBlock::elided_write_barriers_depend_on_type () const [inline]
Definition at line 6477 of file maglev-ir.h.
                                                    {
    return elided_write_barriers_depend_on_type_;
  }
Referenced by TryPretenure().
GenerateCode()
void v8::internal::maglev::AllocationBlock::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::AllocationBlock::MaxCallStackArgs () const [inline]
Definition at line 6459 of file maglev-ir.h.
{ return 0; }
PrintParams()
void v8::internal::maglev::AllocationBlock::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7988 of file maglev-ir.cc.
                                                                             {
  os << "(" << allocation_type() << ")";
}
References allocation_type().
set_elided_write_barriers_depend_on_type()
void v8::internal::maglev::AllocationBlock::set_elided_write_barriers_depend_on_type () [inline]
Definition at line 6480 of file maglev-ir.h.
                                                  {
    elided_write_barriers_depend_on_type_ = true;
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::CanElideWriteBarrier().
set_size()
void v8::internal::maglev::AllocationBlock::set_size (int size) [inline]
Definition at line 6466 of file maglev-ir.h.
{ size_ = size; }
References size().
Referenced by v8::internal::maglev::DeadNodeSweepingProcessor::Process(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::AllocationBlock::SetValueLocationConstraints ()
size()
int v8::internal::maglev::AllocationBlock::size () const [inline]
Definition at line 6465 of file maglev-ir.h.
{ return size_; }
TryPretenure() [1/2]
void v8::internal::maglev::AllocationBlock::TryPretenure () [private]
Definition at line 1154 of file maglev-ir.cc.
                                   {
  if (allocation_type_ == AllocationType::kOld) {
    return;
  }
  if (elided_write_barriers_depend_on_type()) {
    return;
  }
  allocation_type_ = AllocationType::kOld;
  for (auto alloc : allocation_list_) {
    alloc->object()->ForEachInput(
        [&](ValueNode* value) { TryPretenure(value); });
  }
}
References allocation_list_, allocation_type_, elided_write_barriers_depend_on_type(), v8::internal::kOld, and v8::internal::value.
TryPretenure() [2/2]
void v8::internal::maglev::AllocationBlock::TryPretenure (ValueNode * input)
Definition at line 1168 of file maglev-ir.cc.
                                                   {
  DCHECK(v8_flags.maglev_pretenure_store_values);
  DCHECK_EQ(allocation_type_, AllocationType::kOld);
  if (elided_write_barriers_depend_on_type()) {
    return;
  }
  if (IsConstantNode(value->opcode())) return;
  if (auto next_alloc = value->TryCast<InlinedAllocation>()) {
    next_alloc->allocation_block()->TryPretenure();
  } else if (auto phi = value->TryCast<Phi>()) {
    if (!phi->is_loop_phi() || !phi->is_unmerged_loop_phi()) {
      for (int i = 0; i < phi->input_count(); ++i) {
        auto phi_input = phi->input(i).node();
        if (auto phi_alloc = phi_input->TryCast<InlinedAllocation>()) {
          phi_alloc->allocation_block()->TryPretenure();
        }
      }
    }
  }
}
References allocation_type_, v8::internal::DCHECK(), DCHECK_EQ, elided_write_barriers_depend_on_type(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::IsConstantNode(), v8::internal::kOld, v8::internal::v8_flags, and v8::internal::value.
Member Data Documentation
allocation_list_
InlinedAllocation::List v8::internal::maglev::AllocationBlock::allocation_list_ [private]
Definition at line 6489 of file maglev-ir.h.
Referenced by TryPretenure().
allocation_type_
AllocationType v8::internal::maglev::AllocationBlock::allocation_type_ [private]
Definition at line 6486 of file maglev-ir.h.
Referenced by TryPretenure().
elided_write_barriers_depend_on_type_
bool v8::internal::maglev::AllocationBlock::elided_write_barriers_depend_on_type_ = false [private]
Definition at line 6488 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::AllocationBlock::kProperties [static], [constexpr]
Initial value:
= OpProperties::CanAllocate() |
                                              OpProperties::DeferredCall() |
                                              OpProperties::NotIdempotent()
Definition at line 6455 of file maglev-ir.h.
size_
int v8::internal::maglev::AllocationBlock::size_ = 0 [private]
Definition at line 6487 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc