v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope Class Reference
#include <identity-map.h>
Public Member Functions
IteratableScope (IdentityMap *map)
IteratableScope (const IteratableScope &)=delete
IteratableScope & operator= (const IteratableScope &)=delete
~IteratableScope ()
Iterator begin ()
Iterator end ()
Private Attributes
IdentityMap * map_
Detailed Description
template<typename V, class AllocationPolicy>
class v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope
Definition at line 206 of file identity-map.h.
Constructor & Destructor Documentation
IteratableScope() [1/2]
template<typename V , class AllocationPolicy >
v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::IteratableScope (IdentityMap * map) [inline], [explicit]
Definition at line 208 of file identity-map.h.
                                               : map_(map) {
      CHECK(!map_->is_iterable());
      map_->EnableIteration();
    }
References CHECK.
IteratableScope() [2/2]
template<typename V , class AllocationPolicy >
v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::IteratableScope (const IteratableScope &) [delete]
 IteratableScope()
template<typename V , class AllocationPolicy >
v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::~IteratableScope () [inline]
Definition at line 214 of file identity-map.h.
                       {
      CHECK(map_->is_iterable());
      map_->DisableIteration();
    }
References CHECK.
Member Function Documentation
begin()
template<typename V , class AllocationPolicy >
Iterator v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::begin () [inline]
Definition at line 219 of file identity-map.h.
{ return Iterator(map_, map_->NextIndex(-1)); }
Referenced by v8::internal::SharedHeapSerializer::FinalizeSerialization(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), and v8::internal::ObjectCacheIndexMap::Values().
end()
template<typename V , class AllocationPolicy >
Iterator v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::end () [inline]
Definition at line 220 of file identity-map.h.
{ return Iterator(map_, map_->capacity()); }
Referenced by v8::internal::SharedHeapSerializer::FinalizeSerialization(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), and v8::internal::ObjectCacheIndexMap::Values().
operator=()
template<typename V , class AllocationPolicy >
IteratableScope& v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::operator= (const IteratableScope &) [delete]
Member Data Documentation
map_
template<typename V , class AllocationPolicy >
IdentityMap* v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::map_ [private]
Definition at line 223 of file identity-map.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/identity-map.h