v8::internal::torque::DefinitionLocation Class Reference
#include <instructions.h>
Public Types
enum class Kind { kInvalid
, kParameter
, kPhi
, kInstruction
 }
Public Member Functions
DefinitionLocation ()
Kind GetKind () const
bool IsValid () const
bool IsParameter () const
bool IsPhi () const
bool IsInstruction () const
std::size_t GetParameterIndex () const
const Block * GetPhiBlock () const
bool IsPhiFromBlock (const Block *block) const
std::size_t GetPhiIndex () const
const InstructionBase * GetInstruction () const
std::size_t GetInstructionIndex () const
bool operator== (const DefinitionLocation &other) const
bool operator!= (const DefinitionLocation &other) const
bool operator< (const DefinitionLocation &other) const
Static Public Member Functions
static DefinitionLocation Parameter (std::size_t index)
static DefinitionLocation Phi (const Block *block, std::size_t index)
static DefinitionLocation Instruction (const InstructionBase *instruction, std::size_t index=0)
Private Member Functions
DefinitionLocation (Kind kind, const void *location, std::size_t index)
Private Attributes
Kind kind_
const void * location_
std::size_t index_
Detailed Description
Definition at line 79 of file instructions.h.
Member Enumeration Documentation
Kind
enum v8::internal::torque::DefinitionLocation::Kind [strong]
Enumerator
kInvalid
kParameter
kPhi
kInstruction
Definition at line 81 of file instructions.h.
                  {
    kInvalid,
    kParameter,
    kPhi,
    kInstruction,
  };
Constructor & Destructor Documentation
DefinitionLocation() [1/2]
v8::internal::torque::DefinitionLocation::DefinitionLocation () [inline]
Definition at line 88 of file instructions.h.
: kind_(Kind::kInvalid), location_(nullptr), index_(0) {}
Referenced by Instruction(), Parameter(), and Phi().
DefinitionLocation() [2/2]
v8::internal::torque::DefinitionLocation::DefinitionLocation (Kind kind, const void * location, std::size_t index) [inline], [private]
Definition at line 159 of file instructions.h.
      : kind_(kind), location_(location), index_(index) {}
Member Function Documentation
GetInstruction()
const InstructionBase* v8::internal::torque::DefinitionLocation::GetInstruction () const [inline]
Definition at line 128 of file instructions.h.
                                                {
    DCHECK(IsInstruction());
    return reinterpret_cast<const InstructionBase*>(location_);
  }
References v8::internal::DCHECK(), IsInstruction(), and location_.
GetInstructionIndex()
std::size_t v8::internal::torque::DefinitionLocation::GetInstructionIndex () const [inline]
Definition at line 133 of file instructions.h.
                                        {
    DCHECK(IsInstruction());
    return index_;
  }
References v8::internal::DCHECK(), index_, and IsInstruction().
GetKind()
Kind v8::internal::torque::DefinitionLocation::GetKind () const [inline]
Definition at line 103 of file instructions.h.
{ return kind_; }
References kind_.
GetParameterIndex()
std::size_t v8::internal::torque::DefinitionLocation::GetParameterIndex () const [inline]
Definition at line 109 of file instructions.h.
                                      {
    DCHECK(IsParameter());
    return index_;
  }
References v8::internal::DCHECK(), index_, and IsParameter().
GetPhiBlock()
const Block* v8::internal::torque::DefinitionLocation::GetPhiBlock () const [inline]
Definition at line 114 of file instructions.h.
                                   {
    DCHECK(IsPhi());
    return reinterpret_cast<const Block*>(location_);
  }
References v8::internal::DCHECK(), IsPhi(), and location_.
Referenced by v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), and IsPhiFromBlock().
GetPhiIndex()
std::size_t v8::internal::torque::DefinitionLocation::GetPhiIndex () const [inline]
Definition at line 123 of file instructions.h.
                                {
    DCHECK(IsPhi());
    return index_;
  }
References v8::internal::DCHECK(), index_, and IsPhi().
Referenced by v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable().
Instruction()
static DefinitionLocation v8::internal::torque::DefinitionLocation::Instruction (const InstructionBase * instruction, std::size_t index = 0) [inline], [static]
Definition at line 98 of file instructions.h.
                                                             {
    return DefinitionLocation(Kind::kInstruction, instruction, index);
  }
References DefinitionLocation(), v8::internal::index, and kInstruction.
Referenced by v8::internal::torque::CallCsaMacroInstruction::GetExceptionObjectDefinition(), v8::internal::torque::CallCsaMacroAndBranchInstruction::GetExceptionObjectDefinition(), v8::internal::torque::CallBuiltinInstruction::GetExceptionObjectDefinition(), v8::internal::torque::CallRuntimeInstruction::GetExceptionObjectDefinition(), v8::internal::torque::CallCsaMacroAndBranchInstruction::GetLabelValueDefinition(), v8::internal::torque::PushUninitializedInstruction::GetValueDefinition(), v8::internal::torque::PushBuiltinPointerInstruction::GetValueDefinition(), v8::internal::torque::LoadReferenceInstruction::GetValueDefinition(), v8::internal::torque::LoadBitFieldInstruction::GetValueDefinition(), v8::internal::torque::StoreBitFieldInstruction::GetValueDefinition(), v8::internal::torque::MakeLazyNodeInstruction::GetValueDefinition(), v8::internal::torque::UnsafeCastInstruction::GetValueDefinition(), v8::internal::torque::NamespaceConstantInstruction::GetValueDefinition(), v8::internal::torque::CallIntrinsicInstruction::GetValueDefinition(), v8::internal::torque::CallCsaMacroInstruction::GetValueDefinition(), v8::internal::torque::CallCsaMacroAndBranchInstruction::GetValueDefinition(), v8::internal::torque::CallBuiltinInstruction::GetValueDefinition(), v8::internal::torque::CallBuiltinPointerInstruction::GetValueDefinition(), and v8::internal::torque::CallRuntimeInstruction::GetValueDefinition().
IsInstruction()
bool v8::internal::torque::DefinitionLocation::IsInstruction () const [inline]
Definition at line 107 of file instructions.h.
{ return kind_ == Kind::kInstruction; }
References kind_, and kInstruction.
Referenced by v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), GetInstruction(), and GetInstructionIndex().
IsParameter()
bool v8::internal::torque::DefinitionLocation::IsParameter () const [inline]
Definition at line 105 of file instructions.h.
{ return kind_ == Kind::kParameter; }
References kind_, and kParameter.
Referenced by v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), and GetParameterIndex().
IsPhi()
bool v8::internal::torque::DefinitionLocation::IsPhi () const [inline]
Definition at line 106 of file instructions.h.
{ return kind_ == Kind::kPhi; }
References kind_, and kPhi.
Referenced by v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), GetPhiBlock(), GetPhiIndex(), and IsPhiFromBlock().
IsPhiFromBlock()
bool v8::internal::torque::DefinitionLocation::IsPhiFromBlock (const Block * block) const [inline]
Definition at line 119 of file instructions.h.
                                                {
    return IsPhi() && GetPhiBlock() == block;
  }
References GetPhiBlock(), and IsPhi().
Referenced by v8::internal::torque::CCGenerator::EmitGoto().
IsValid()
bool v8::internal::torque::DefinitionLocation::IsValid () const [inline]
Definition at line 104 of file instructions.h.
{ return kind_ != Kind::kInvalid; }
References kind_, and kInvalid.
operator!=()
bool v8::internal::torque::DefinitionLocation::operator!= (const DefinitionLocation & other) const [inline]
Definition at line 144 of file instructions.h.
                                                         {
    return !operator==(other);
  }
References operator==().
operator<()
bool v8::internal::torque::DefinitionLocation::operator< (const DefinitionLocation & other) const [inline]
Definition at line 148 of file instructions.h.
                                                        {
    if (kind_ != other.kind_) {
      return static_cast<int>(kind_) < static_cast<int>(other.kind_);
    }
    if (location_ != other.location_) {
      return location_ < other.location_;
    }
    return index_ < other.index_;
  }
References index_, kind_, and location_.
operator==()
bool v8::internal::torque::DefinitionLocation::operator== (const DefinitionLocation & other) const [inline]
Definition at line 138 of file instructions.h.
                                                         {
    if (kind_ != other.kind_) return false;
    if (location_ != other.location_) return false;
    return index_ == other.index_;
  }
References index_, kind_, and location_.
Referenced by operator!=().
Parameter()
static DefinitionLocation v8::internal::torque::DefinitionLocation::Parameter (std::size_t index) [inline], [static]
Definition at line 90 of file instructions.h.
                                                       {
    return DefinitionLocation(Kind::kParameter, nullptr, index);
  }
References DefinitionLocation(), v8::internal::index, and kParameter.
Referenced by v8::internal::torque::CfgAssembler::ComputeInputDefinitions(), v8::internal::torque::CCGenerator::EmitGraph(), and v8::internal::torque::CSAGenerator::EmitGraph().
Phi()
static DefinitionLocation v8::internal::torque::DefinitionLocation::Phi (const Block * block, std::size_t index) [inline], [static]
Definition at line 94 of file instructions.h.
                                                                     {
    return DefinitionLocation(Kind::kPhi, block, index);
  }
References DefinitionLocation(), v8::internal::index, and kPhi.
Referenced by v8::internal::torque::Block::MergeInputDefinitions().
Member Data Documentation
index_
std::size_t v8::internal::torque::DefinitionLocation::index_ [private]
Definition at line 164 of file instructions.h.
Referenced by GetInstructionIndex(), GetParameterIndex(), GetPhiIndex(), operator<(), and operator==().
kind_
Kind v8::internal::torque::DefinitionLocation::kind_ [private]
Definition at line 162 of file instructions.h.
Referenced by GetKind(), IsInstruction(), IsParameter(), IsPhi(), IsValid(), operator<(), and operator==().
location_
const void* v8::internal::torque::DefinitionLocation::location_ [private]
Definition at line 163 of file instructions.h.
Referenced by GetInstruction(), GetPhiBlock(), operator<(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/instructions.h