v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor Class Reference
Public Member Functions
CandidateVisitor (Committee *committee, HeapObjectSet *accepted_subgraph, HeapObjectSet *visited, HeapObjectList *promotees, std::optional< Tagged< HeapObject >> maybe_host)
std::optional< Tagged< HeapObject > > maybe_host () const
int first_rejected_slot_offset () const
bool all_slots_are_promo_candidates () const
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) final
void VisitMapPointer (Tagged< HeapObject > host) final
Private Attributes
Committee *const committee_
HeapObjectSet *const accepted_subgraph_
HeapObjectSet *const visited_
HeapObjectList *const promotees_
std::optional< Tagged< HeapObject > > maybe_host_
int first_rejected_slot_offset_ = -1
Detailed Description
Definition at line 311 of file read-only-promotion.cc.
Constructor & Destructor Documentation
CandidateVisitor()
v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::CandidateVisitor (Committee * committee, HeapObjectSet * accepted_subgraph, HeapObjectSet * visited, HeapObjectList * promotees, std::optional< Tagged< HeapObject >> maybe_host) [inline]
Definition at line 313 of file read-only-promotion.cc.
        : committee_(committee),
          accepted_subgraph_(accepted_subgraph),
          visited_(visited),
          promotees_(promotees),
          maybe_host_(maybe_host) {}
Member Function Documentation
all_slots_are_promo_candidates()
bool v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::all_slots_are_promo_candidates () const [inline]
Definition at line 329 of file read-only-promotion.cc.
                                                {
      return first_rejected_slot_offset_ == -1;
    }
Referenced by v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::EvaluateSubgraph().
first_rejected_slot_offset()
int v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::first_rejected_slot_offset () const [inline]
Definition at line 326 of file read-only-promotion.cc.
                                           {
      return first_rejected_slot_offset_;
    }
Referenced by v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::EvaluateSubgraph().
maybe_host()
std::optional<Tagged<HeapObject> > v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::maybe_host () const [inline]
Definition at line 324 of file read-only-promotion.cc.
{ return maybe_host_; }
VisitInstructionStreamPointer()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 354 of file read-only-promotion.cc.
                                                                         {
      DCHECK(host->is_builtin());
    }
References v8::internal::DCHECK().
VisitMapPointer()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 358 of file read-only-promotion.cc.
                                                        {
      MaybeObjectSlot slot = host->RawMaybeWeakField(HeapObject::kMapOffset);
      VisitPointers(host, slot, slot + 1);
    }
References v8::internal::HeapObject::kMapOffset.
VisitPointers() [1/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 333 of file read-only-promotion.cc.
                                                  {
      if (!all_slots_are_promo_candidates()) return;
      for (MaybeObjectSlot slot = start; slot < end; slot++) {
        Tagged<MaybeObject> maybe_object = slot.load(committee_->isolate_);
        Tagged<HeapObject> heap_object;
        if (!maybe_object.GetHeapObject(&heap_object)) continue;
        if (!committee_->EvaluateSubgraph({host}, heap_object,
                                          accepted_subgraph_, visited_,
                                          promotees_)) {
          first_rejected_slot_offset_ =
              static_cast<int>(slot.address() - host.address());
          DCHECK_GE(first_rejected_slot_offset_, 0);
          return;
        }
      }
    }
References DCHECK_GE, v8::internal::compiler::end(), and v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject().
VisitPointers() [2/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 350 of file read-only-promotion.cc.
                                             {
      VisitPointers(host, MaybeObjectSlot(start), MaybeObjectSlot(end));
    }
References v8::internal::compiler::end().
Member Data Documentation
accepted_subgraph_
HeapObjectSet* const v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::accepted_subgraph_ [private]
Definition at line 365 of file read-only-promotion.cc.
committee_
Committee* const v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::committee_ [private]
Definition at line 364 of file read-only-promotion.cc.
first_rejected_slot_offset_
int v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::first_rejected_slot_offset_ = -1 [private]
Definition at line 369 of file read-only-promotion.cc.
maybe_host_
std::optional<Tagged<HeapObject> > v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::maybe_host_ [private]
Definition at line 368 of file read-only-promotion.cc.
promotees_
HeapObjectList* const v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::promotees_ [private]
Definition at line 367 of file read-only-promotion.cc.
visited_
HeapObjectSet* const v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::visited_ [private]
Definition at line 366 of file read-only-promotion.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/read-only-promotion.cc