v8::internal::SafepointTable Class Reference
#include <safepoint-table.h>
Public Member Functions
SafepointTable (Isolate *isolate, Address pc, Tagged< InstructionStream > code)
SafepointTable (Isolate *isolate, Address pc, Tagged< Code > code)
SafepointTable (const SafepointTable &)=delete
SafepointTable & operator= (const SafepointTable &)=delete
int stack_slots () const
int length () const
int byte_size () const
int find_return_pc (int pc_offset)
SafepointEntry GetEntry (int index) const
SafepointEntry FindEntry (Address pc) const
SafepointEntry TryFindEntry (Address pc) const
void Print (std::ostream &) const
Static Public Member Functions
static SafepointEntry FindEntry (Isolate *isolate, Tagged< GcSafeCode > code, Address pc)
Private Types
using HasDeoptDataField = base::BitField< bool, 0, 1 >
using RegisterIndexesSizeField = HasDeoptDataField::Next< int, 3 >
using PcSizeField = RegisterIndexesSizeField::Next< int, 3 >
using DeoptIndexSizeField = PcSizeField::Next< int, 3 >
using TaggedSlotsBytesField = DeoptIndexSizeField::Next< int, 22 >
Private Member Functions
SafepointTable (Isolate *isolate, Address pc, Tagged< GcSafeCode > code)
SafepointTable (Address instruction_start, Address safepoint_table_address)
int entry_size () const
int tagged_slots_bytes () const
bool has_deopt_data () const
int pc_size () const
int deopt_index_size () const
int register_indexes_size () const
Static Private Member Functions
static int read_bytes (Address *ptr, int bytes)
Private Attributes
const Address instruction_start_
const Address safepoint_table_address_
const SafepointTableStackSlotsField_t stack_slots_
const int length_
const uint32_t entry_configuration_
Friends
class SafepointTableBuilder
class SafepointEntry
Detailed Description
Definition at line 62 of file safepoint-table.h.
Member Typedef Documentation
DeoptIndexSizeField
using v8::internal::SafepointTable::DeoptIndexSizeField = PcSizeField::Next<int, 3> [private]
Definition at line 148 of file safepoint-table.h.
HasDeoptDataField
using v8::internal::SafepointTable::HasDeoptDataField = base::BitField<bool, 0, 1> [private]
Definition at line 145 of file safepoint-table.h.
PcSizeField
using v8::internal::SafepointTable::PcSizeField = RegisterIndexesSizeField::Next<int, 3> [private]
Definition at line 147 of file safepoint-table.h.
RegisterIndexesSizeField
using v8::internal::SafepointTable::RegisterIndexesSizeField = HasDeoptDataField::Next<int, 3> [private]
Definition at line 146 of file safepoint-table.h.
TaggedSlotsBytesField
using v8::internal::SafepointTable::TaggedSlotsBytesField = DeoptIndexSizeField::Next<int, 22> [private]
Definition at line 152 of file safepoint-table.h.
Constructor & Destructor Documentation
SafepointTable() [1/5]
v8::internal::SafepointTable::SafepointTable (Isolate * isolate, Address pc, Tagged< InstructionStream > code) [explicit]
SafepointTable() [2/5]
v8::internal::SafepointTable::SafepointTable (Isolate * isolate, Address pc, Tagged< Code > code) [explicit]
Definition at line 23 of file safepoint-table.cc.
    : SafepointTable(code->InstructionStart(isolate, pc),
                     code->safepoint_table_address()) {
  DCHECK(code->is_turbofanned());
}
References code, and v8::internal::DCHECK().
SafepointTable() [3/5]
v8::internal::SafepointTable::SafepointTable (const SafepointTable &) [delete]
SafepointTable() [4/5]
v8::internal::SafepointTable::SafepointTable (Isolate * isolate, Address pc, Tagged< GcSafeCode > code) [private]
Definition at line 29 of file safepoint-table.cc.
    : SafepointTable(code->InstructionStart(isolate, pc),
                     code->safepoint_table_address()) {
  DCHECK(code->is_turbofanned());
}
References code, and v8::internal::DCHECK().
SafepointTable() [5/5]
v8::internal::SafepointTable::SafepointTable (Address instruction_start, Address safepoint_table_address) [private]
Definition at line 43 of file safepoint-table.cc.
    : instruction_start_(instruction_start),
      safepoint_table_address_(safepoint_table_address),
      stack_slots_(base::Memory<SafepointTableStackSlotsField_t>(
          safepoint_table_address + kStackSlotsOffset)),
      length_(base::Memory<int>(safepoint_table_address + kLengthOffset)),
      entry_configuration_(base::Memory<uint32_t>(safepoint_table_address +
                                                  kEntryConfigurationOffset)) {}
Member Function Documentation
byte_size()
int v8::internal::SafepointTable::byte_size () const [inline]
Definition at line 80 of file safepoint-table.h.
                        {
    return kHeaderSize + length_ * (entry_size() + tagged_slots_bytes());
  }
References entry_size(), length_, and tagged_slots_bytes().
Referenced by Print().
deopt_index_size()
int v8::internal::SafepointTable::deopt_index_size () const [inline], [private]
Definition at line 168 of file safepoint-table.h.
                               {
    return DeoptIndexSizeField::decode(entry_configuration_);
  }
References v8::base::BitField< T, shift, size, U >::decode(), and entry_configuration_.
Referenced by entry_size(), and GetEntry().
entry_size()
int v8::internal::SafepointTable::entry_size () const [inline], [private]
Definition at line 156 of file safepoint-table.h.
                         {
    int deopt_data_size = has_deopt_data() ? pc_size() + deopt_index_size() : 0;
    return pc_size() + deopt_data_size + register_indexes_size();
  }
References deopt_index_size(), has_deopt_data(), pc_size(), and register_indexes_size().
Referenced by byte_size(), and GetEntry().
find_return_pc()
int v8::internal::SafepointTable::find_return_pc (int pc_offset)
Definition at line 53 of file safepoint-table.cc.
                                                {
  for (int i = 0; i < length(); i++) {
    SafepointEntry entry = GetEntry(i);
    if (entry.trampoline_pc() == pc_offset || entry.pc() == pc_offset) {
      return entry.pc();
    }
  }
  UNREACHABLE();
}
References GetEntry(), length(), v8::internal::SafepointEntryBase::pc(), v8::internal::SafepointEntryBase::trampoline_pc(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::TurbofanJSFrame::FindReturnPCForTrampoline().
FindEntry() [1/2]
SafepointEntry v8::internal::SafepointTable::FindEntry (Address pc) const
Definition at line 87 of file safepoint-table.cc.
                                                         {
  SafepointEntry result = TryFindEntry(pc);
  CHECK(result.is_initialized());
  return result;
}
References CHECK, v8::base::internal::result, and TryFindEntry().
Referenced by v8::internal::Deoptimizer::DeoptimizeMarkedCode(), FindEntry(), v8::internal::Code::GetSafepointEntry(), v8::internal::anonymous_namespace{frames.cc}::GetSafepointEntryFromCodeCache(), and v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread().
FindEntry() [2/2]
SafepointEntry v8::internal::SafepointTable::FindEntry (Isolate * isolate, Tagged< GcSafeCode > code, Address pc) [static]
Definition at line 94 of file safepoint-table.cc.
                                                                              {
  SafepointTable table(isolate, pc, code);
  return table.FindEntry(pc);
}
References code, and FindEntry().
GetEntry()
SafepointEntry v8::internal::SafepointTable::GetEntry (int index) const [inline]
Definition at line 86 of file safepoint-table.h.
                                           {
    DCHECK_GT(length_, index);
    Address entry_ptr =
        safepoint_table_address_ + kHeaderSize + index * entry_size();
    int pc = read_bytes(&entry_ptr, pc_size());
    int deopt_index = SafepointEntry::kNoDeoptIndex;
    int trampoline_pc = SafepointEntry::kNoTrampolinePC;
    if (has_deopt_data()) {
      static_assert(SafepointEntry::kNoDeoptIndex == -1);
      static_assert(SafepointEntry::kNoTrampolinePC == -1);
      // `-1` to restore the original value, see also
      // SafepointTableBuilder::Emit.
      deopt_index = read_bytes(&entry_ptr, deopt_index_size()) - 1;
      trampoline_pc = read_bytes(&entry_ptr, pc_size()) - 1;
      DCHECK(deopt_index >= 0 || deopt_index == SafepointEntry::kNoDeoptIndex);
      DCHECK(trampoline_pc >= 0 ||
             trampoline_pc == SafepointEntry::kNoTrampolinePC);
    }
    int tagged_register_indexes =
        read_bytes(&entry_ptr, register_indexes_size());
    // Entry bits start after the the vector of entries (thus the pc offset of
    // the non-existing entry after the last one).
    uint8_t* tagged_slots_start = reinterpret_cast<uint8_t*>(
        safepoint_table_address_ + kHeaderSize + length_ * entry_size());
    base::Vector<uint8_t> tagged_slots(
        tagged_slots_start + index * tagged_slots_bytes(),
        tagged_slots_bytes());
    return SafepointEntry(pc, deopt_index, tagged_register_indexes,
                          tagged_slots, trampoline_pc);
  }
References v8::internal::DCHECK(), DCHECK_GT, deopt_index_size(), entry_size(), has_deopt_data(), v8::internal::index, v8::internal::SafepointEntryBase::kNoDeoptIndex, v8::internal::SafepointEntryBase::kNoTrampolinePC, length_, pc_size(), read_bytes(), register_indexes_size(), safepoint_table_address_, SafepointEntry, and tagged_slots_bytes().
Referenced by find_return_pc(), Print(), and TryFindEntry().
has_deopt_data()
bool v8::internal::SafepointTable::has_deopt_data () const [inline], [private]
Definition at line 164 of file safepoint-table.h.
                              {
    return HasDeoptDataField::decode(entry_configuration_);
  }
References v8::base::BitField< T, shift, size, U >::decode(), and entry_configuration_.
Referenced by entry_size(), GetEntry(), and TryFindEntry().
length()
int v8::internal::SafepointTable::length () const [inline]
Definition at line 78 of file safepoint-table.h.
{ return length_; }
References length_.
Referenced by find_return_pc().
operator=()
SafepointTable& v8::internal::SafepointTable::operator= (const SafepointTable &) [delete]
pc_size()
int v8::internal::SafepointTable::pc_size () const [inline], [private]
Definition at line 167 of file safepoint-table.h.
{ return PcSizeField::decode(entry_configuration_); }
References v8::base::BitField< T, shift, size, U >::decode(), and entry_configuration_.
Referenced by entry_size(), and GetEntry().
Print()
void v8::internal::SafepointTable::Print (std::ostream & os) const
Definition at line 100 of file safepoint-table.cc.
                                               {
  os << "Safepoints (stack slots = " << stack_slots_
     << ", entries = " << length_ << ", byte size = " << byte_size() << ")\n";
  for (int index = 0; index < length_; index++) {
    SafepointEntry entry = GetEntry(index);
    os << reinterpret_cast<const void*>(instruction_start_ + entry.pc()) << " "
       << std::setw(6) << std::hex << entry.pc() << std::dec;
    if (!entry.tagged_slots().empty()) {
      os << " slots (sp->fp): ";
      uint32_t i = 0;
      for (uint8_t bits : entry.tagged_slots()) {
        for (int bit = 0; bit < kBitsPerByte && i < stack_slots_; ++bit, ++i) {
          os << ((bits >> bit) & 1);
        }
      }
      // The tagged slots bitfield ends at the min stack slot (rounded up to the
      // nearest byte) -- we might have some slots left over in the stack frame
      // before the fp, so print zeros for those.
      for (; i < stack_slots_; ++i) {
        os << 0;
      }
    }
    if (entry.tagged_register_indexes() != 0) {
      os << " registers: ";
      uint32_t register_bits = entry.tagged_register_indexes();
      int bits = 32 - base::bits::CountLeadingZeros32(register_bits);
      for (int j = bits - 1; j >= 0; --j) {
        os << ((register_bits >> j) & 1);
      }
    }
    if (entry.has_deoptimization_index()) {
      os << " deopt " << std::setw(6) << entry.deoptimization_index()
         << " trampoline: " << std::setw(6) << std::hex
         << entry.trampoline_pc();
    }
    os << "\n";
  }
}
References byte_size(), v8::base::bits::CountLeadingZeros32(), v8::internal::SafepointEntryBase::deoptimization_index(), v8::base::Vector< T >::empty(), GetEntry(), v8::internal::SafepointEntryBase::has_deoptimization_index(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, instruction_start_, v8::internal::kBitsPerByte, length_, v8::internal::SafepointEntryBase::pc(), stack_slots_, v8::internal::SafepointEntry::tagged_register_indexes(), v8::internal::SafepointEntry::tagged_slots(), and v8::internal::SafepointEntryBase::trampoline_pc().
Referenced by v8::internal::wasm::WasmCode::Disassemble().
read_bytes()
static int v8::internal::SafepointTable::read_bytes (Address * ptr, int bytes) [inline], [static], [private]
Definition at line 175 of file safepoint-table.h.
                                                 {
    uint32_t result = 0;
    for (int b = 0; b < bytes; ++b, ++*ptr) {
      result |= uint32_t{*reinterpret_cast<uint8_t*>(*ptr)} << (8 * b);
    }
    return static_cast<int>(result);
  }
References v8::base::internal::result.
Referenced by GetEntry().
register_indexes_size()
int v8::internal::SafepointTable::register_indexes_size () const [inline], [private]
Definition at line 171 of file safepoint-table.h.
                                    {
    return RegisterIndexesSizeField::decode(entry_configuration_);
  }
References v8::base::BitField< T, shift, size, U >::decode(), and entry_configuration_.
Referenced by entry_size(), and GetEntry().
stack_slots()
int v8::internal::SafepointTable::stack_slots () const [inline]
Definition at line 76 of file safepoint-table.h.
{ return stack_slots_; }
References stack_slots_.
tagged_slots_bytes()
int v8::internal::SafepointTable::tagged_slots_bytes () const [inline], [private]
Definition at line 161 of file safepoint-table.h.
                                 {
    return TaggedSlotsBytesField::decode(entry_configuration_);
  }
References v8::base::BitField< T, shift, size, U >::decode(), and entry_configuration_.
Referenced by byte_size(), and GetEntry().
TryFindEntry()
SafepointEntry v8::internal::SafepointTable::TryFindEntry (Address pc) const
Definition at line 63 of file safepoint-table.cc.
                                                            {
  int pc_offset = static_cast<int>(pc - instruction_start_);
  // Check if the PC is pointing at a trampoline.
  if (has_deopt_data()) {
    int candidate = -1;
    for (int i = 0; i < length_; ++i) {
      int trampoline_pc = GetEntry(i).trampoline_pc();
      if (trampoline_pc != -1 && trampoline_pc <= pc_offset) candidate = i;
      if (trampoline_pc > pc_offset) break;
    }
    if (candidate != -1) return GetEntry(candidate);
  }
  for (int i = 0; i < length_; ++i) {
    SafepointEntry entry = GetEntry(i);
    if (i == length_ - 1 || GetEntry(i + 1).pc() > pc_offset) {
      if (entry.pc() > pc_offset) return {};
      return entry;
    }
  }
  return {};
}
References GetEntry(), has_deopt_data(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, instruction_start_, length_, v8::internal::SafepointEntryBase::pc(), and v8::internal::SafepointEntryBase::trampoline_pc().
Referenced by FindEntry(), and v8::internal::wasm::WasmCodeManager::LookupCodeAndSafepoint().
Friends And Related Function Documentation
SafepointEntry
friend class SafepointEntry [friend]
Definition at line 194 of file safepoint-table.h.
Referenced by GetEntry().
SafepointTableBuilder
friend class SafepointTableBuilder [friend]
Definition at line 193 of file safepoint-table.h.
Member Data Documentation
entry_configuration_
const uint32_t v8::internal::SafepointTable::entry_configuration_ [private]
Definition at line 191 of file safepoint-table.h.
Referenced by deopt_index_size(), has_deopt_data(), pc_size(), register_indexes_size(), and tagged_slots_bytes().
instruction_start_
const Address v8::internal::SafepointTable::instruction_start_ [private]
Definition at line 185 of file safepoint-table.h.
Referenced by Print(), and TryFindEntry().
length_
const int v8::internal::SafepointTable::length_ [private]
Definition at line 190 of file safepoint-table.h.
Referenced by byte_size(), GetEntry(), length(), Print(), and TryFindEntry().
safepoint_table_address_
const Address v8::internal::SafepointTable::safepoint_table_address_ [private]
Definition at line 188 of file safepoint-table.h.
Referenced by GetEntry().
stack_slots_
const SafepointTableStackSlotsField_t v8::internal::SafepointTable::stack_slots_ [private]
Definition at line 189 of file safepoint-table.h.
Referenced by Print(), and stack_slots().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/safepoint-table.h
/mnt/V8SourceCode/src/codegen/safepoint-table.cc