v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency Class Reference
Public Member Functions
FieldConstnessDependency (MapRef map, MapRef owner, InternalIndex descriptor)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const MapRef map_
const MapRef owner_
const InternalIndex descriptor_
Additional Inherited Members
Detailed Description
Definition at line 822 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
FieldConstnessDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::FieldConstnessDependency (MapRef map, MapRef owner, InternalIndex descriptor) [inline]
Definition at line 824 of file compilation-dependencies.cc.
      : CompilationDependency(kFieldConstness),
        map_(map),
        owner_(owner),
        descriptor_(descriptor) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 857 of file compilation-dependencies.cc.
                                                                {
    const FieldConstnessDependency* const zat = that->AsFieldConstness();
    return map_.equals(zat->map_) && descriptor_ == zat->descriptor_;
  }
References descriptor_, and map_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 852 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(map_), descriptor_.as_int());
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 840 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    Isolate* isolate = broker->isolate();
    Handle<Map> owner = owner_.object();
    CHECK(!owner->is_deprecated());
    CHECK_EQ(PropertyConstness::kConst, owner->instance_descriptors(isolate)
                                            ->GetDetails(descriptor_)
                                            .constness());
    deps->Register(owner, DependentCode::kFieldConstGroup);
  }
References broker(), CHECK, CHECK_EQ, v8::internal::kConst, v8::internal::DependentCode::kFieldConstGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 830 of file compilation-dependencies.cc.
                                                    {
    DisallowGarbageCollection no_heap_allocation;
    if (map_.object()->is_deprecated()) return false;
    return PropertyConstness::kConst ==
           map_.object()
               ->instance_descriptors(broker->isolate())
               ->GetDetails(descriptor_)
               .constness();
  }
References broker(), and v8::internal::kConst.
Member Data Documentation
descriptor_
const InternalIndex v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::descriptor_ [private]
Definition at line 864 of file compilation-dependencies.cc.
Referenced by Equals().
map_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::map_ [private]
Definition at line 862 of file compilation-dependencies.cc.
Referenced by Equals().
owner_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::owner_ [private]
Definition at line 863 of file compilation-dependencies.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc