v8::internal::JSFunction::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Static Public Attributes
static const int kStartOffset = JSObject::BodyDescriptor::kStartOffset
static const int kCodeFieldOffset = JSFunction::kCodeOffset
Additional Inherited Members
Detailed Description
Definition at line 560 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::JSFunction::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 570 of file objects-body-descriptors-inl.h.
                                                                    {
    // Iterate JSFunction header fields first.
    int header_size = JSFunction::GetHeaderSize(map->has_prototype_slot());
    DCHECK_GE(object_size, header_size);
    IteratePointers(obj, kStartOffset, kCodeFieldOffset, v);
#ifdef V8_ENABLE_LEAPTIERING
    IterateJSDispatchEntry(obj, kDispatchHandleOffset, v);
#else
    // The code field is treated as a custom weak pointer. This field
    // is visited as a weak pointer if the Code is baseline code
    // and the bytecode array corresponding to this function is old. In the rest
    // of the cases this field is treated as strong pointer.
    // See MarkingVisitorBase::VisitJSFunction.
    IterateCodePointer(obj, kCodeOffset, v, IndirectPointerMode::kCustom);
    DCHECK_GE(header_size, kCodeOffset);
#endif // V8_ENABLE_LEAPTIERING
    // Iterate rest of the header fields
    IteratePointers(obj, kCodeFieldOffset + kTaggedSize, header_size, v);
    // Iterate rest of the fields starting after the header.
    IterateJSObjectBodyImpl(map, obj, header_size, object_size, v);
  }
References DCHECK_GE, v8::internal::JSFunction::GetHeaderSize(), v8::internal::BodyDescriptorBase::IterateCodePointer(), v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl(), v8::internal::BodyDescriptorBase::IteratePointers(), kCodeFieldOffset, v8::internal::kCustom, kStartOffset, and v8::internal::kTaggedSize.
SizeOf()
static int v8::internal::JSFunction::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 595 of file objects-body-descriptors-inl.h.
                                                                       {
    return map->instance_size();
  }
Member Data Documentation
kCodeFieldOffset
const int v8::internal::JSFunction::BodyDescriptor::kCodeFieldOffset = JSFunction::kCodeOffset [static]
Definition at line 566 of file objects-body-descriptors-inl.h.
Referenced by IterateBody().
kStartOffset
const int v8::internal::JSFunction::BodyDescriptor::kStartOffset = JSObject::BodyDescriptor::kStartOffset [static]
Definition at line 562 of file objects-body-descriptors-inl.h.
Referenced by IterateBody().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h