v8::internal::torque::CfgAssemblerScopedTemporaryBlock Class Reference
#include <cfg.h>
Public Member Functions
CfgAssemblerScopedTemporaryBlock (CfgAssembler *assembler, Block *block)
~CfgAssemblerScopedTemporaryBlock ()
Private Attributes
CfgAssembler * assembler_
Stack< const Type * > saved_stack_
Block * saved_block_
Detailed Description
Definition at line 218 of file cfg.h.
Constructor & Destructor Documentation
CfgAssemblerScopedTemporaryBlock()
v8::internal::torque::CfgAssemblerScopedTemporaryBlock::CfgAssemblerScopedTemporaryBlock (CfgAssembler * assembler, Block * block) [inline]
Definition at line 220 of file cfg.h.
      : assembler_(assembler), saved_block_(block) {
    saved_stack_ = block->InputTypes();
    DCHECK(!assembler->CurrentBlockIsComplete());
    std::swap(saved_block_, assembler->current_block_);
    std::swap(saved_stack_, assembler->current_stack_);
    assembler->cfg_.PlaceBlock(block);
  }
References v8::internal::torque::CfgAssembler::cfg_, v8::internal::torque::CfgAssembler::current_block_, v8::internal::torque::CfgAssembler::current_stack_, v8::internal::torque::CfgAssembler::CurrentBlockIsComplete(), v8::internal::DCHECK(), v8::internal::torque::Block::InputTypes(), and v8::internal::torque::ControlFlowGraph::PlaceBlock().
 CfgAssemblerScopedTemporaryBlock()
v8::internal::torque::CfgAssemblerScopedTemporaryBlock::~CfgAssemblerScopedTemporaryBlock () [inline]
Definition at line 229 of file cfg.h.
                                      {
    DCHECK(assembler_->CurrentBlockIsComplete());
    std::swap(saved_block_, assembler_->current_block_);
    std::swap(saved_stack_, assembler_->current_stack_);
  }
References v8::internal::DCHECK().
Member Data Documentation
assembler_
CfgAssembler* v8::internal::torque::CfgAssemblerScopedTemporaryBlock::assembler_ [private]
Definition at line 236 of file cfg.h.
saved_block_
Block* v8::internal::torque::CfgAssemblerScopedTemporaryBlock::saved_block_ [private]
Definition at line 238 of file cfg.h.
saved_stack_
Stack<const Type*> v8::internal::torque::CfgAssemblerScopedTemporaryBlock::saved_stack_ [private]
Definition at line 237 of file cfg.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/cfg.h