v8::internal::compiler::ConstantOperand Class Reference
#include <instruction.h>
Public Types
using VirtualRegisterField = KindField::Next< uint32_t, 32 >
Public Member Functions
ConstantOperand (int virtual_register)
int32_t virtual_register () const
Static Public Member Functions
static ConstantOperand * New (Zone *zone, int virtual_register)
Additional Inherited Members
Detailed Description
Definition at line 399 of file instruction.h.
Member Typedef Documentation
VirtualRegisterField
using v8::internal::compiler::ConstantOperand::VirtualRegisterField = KindField::Next<uint32_t, 32>
Definition at line 417 of file instruction.h.
Constructor & Destructor Documentation
ConstantOperand()
v8::internal::compiler::ConstantOperand::ConstantOperand (int virtual_register) [inline], [explicit]
Definition at line 401 of file instruction.h.
      : InstructionOperand(CONSTANT) {
    value_ |=
        VirtualRegisterField::encode(static_cast<uint32_t>(virtual_register));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::InstructionOperand::value_, and virtual_register().
Referenced by New().
Member Function Documentation
New()
static ConstantOperand* v8::internal::compiler::ConstantOperand::New (Zone * zone, int virtual_register) [inline], [static]
Definition at line 411 of file instruction.h.
                                                                {
    return InstructionOperand::New(zone, ConstantOperand(virtual_register));
  }
References ConstantOperand(), v8::internal::compiler::InstructionOperand::New(), and virtual_register().
Referenced by v8::internal::compiler::Instruction::New().
virtual_register()
int32_t v8::internal::compiler::ConstantOperand::virtual_register () const [inline]
Definition at line 407 of file instruction.h.
                                   {
    return static_cast<int32_t>(VirtualRegisterField::decode(value_));
  }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::InstructionSequence::AddConstant(), ConstantOperand(), v8::internal::compiler::InstructionSequence::GetConstant(), v8::internal::compiler::InstructionSequence::IsFP(), v8::internal::compiler::InstructionSequence::IsReference(), and New().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction.h