cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker Class Reference
Public Member Functions
DeadlineChecker (v8::base::TimeTicks end)
bool Check ()
Private Attributes
const v8::base::TimeTicks end_
size_t count_ = 0
Static Private Attributes
static constexpr size_t kInterval = 4
Detailed Description
Definition at line 42 of file sweeper.cc.
Constructor & Destructor Documentation
DeadlineChecker()
cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::DeadlineChecker (v8::base::TimeTicks end) [inline], [explicit]
Definition at line 44 of file sweeper.cc.
: end_(end) {}
Member Function Documentation
Check()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::Check () [inline]
Definition at line 46 of file sweeper.cc.
               {
    return V8_UNLIKELY(++count_ % kInterval == 0) &&
           (end_ < v8::base::TimeTicks::Now());
  }
References v8::base::TimeTicks::Now(), and V8_UNLIKELY.
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizeWithDeadline(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizeWithDeadlineAndSize(), cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepSpaceWithDeadline(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepWithDeadlineAndSize().
Member Data Documentation
count_
size_t cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::count_ = 0 [private]
Definition at line 55 of file sweeper.cc.
end_
const v8::base::TimeTicks cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::end_ [private]
Definition at line 54 of file sweeper.cc.
kInterval
constexpr size_t cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::kInterval = 4 [static], [constexpr], [private]
Definition at line 52 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc