v8::HeapStatistics Class Reference
Collection of V8 heap information.
#include <v8-statistics.h>
Public Member Functions
HeapStatistics ()
size_t total_heap_size ()
size_t total_heap_size_executable ()
size_t total_physical_size ()
size_t total_available_size ()
size_t total_global_handles_size ()
size_t used_global_handles_size ()
size_t used_heap_size ()
size_t heap_size_limit ()
size_t malloced_memory ()
size_t external_memory ()
size_t peak_malloced_memory ()
size_t number_of_native_contexts ()
size_t number_of_detached_contexts ()
size_t does_zap_garbage ()
Returns a 0/1 boolean, which signifies whether the V8 overwrite heap garbage with a bit pattern.
Private Attributes
size_t total_heap_size_
size_t total_heap_size_executable_
size_t total_physical_size_
size_t total_available_size_
size_t used_heap_size_
size_t heap_size_limit_
size_t malloced_memory_
size_t external_memory_
size_t peak_malloced_memory_
bool does_zap_garbage_
size_t number_of_native_contexts_
size_t number_of_detached_contexts_
size_t total_global_handles_size_
size_t used_global_handles_size_
Friends
class V8
class Isolate
Detailed Description
Collection of V8 heap information.
Instances of this class can be passed to v8::Isolate::GetHeapStatistics to get heap statistics from V8.
Definition at line 140 of file v8-statistics.h.
Constructor & Destructor Documentation
HeapStatistics()
v8::HeapStatistics::HeapStatistics ()
Definition at line 6468 of file api.cc.
    : total_heap_size_(0),
      total_heap_size_executable_(0),
      total_physical_size_(0),
      total_available_size_(0),
      used_heap_size_(0),
      heap_size_limit_(0),
      malloced_memory_(0),
      external_memory_(0),
      peak_malloced_memory_(0),
      does_zap_garbage_(false),
      number_of_native_contexts_(0),
      number_of_detached_contexts_(0) {}
Member Function Documentation
does_zap_garbage()
size_t v8::HeapStatistics::does_zap_garbage () [inline]
Returns a 0/1 boolean, which signifies whether the V8 overwrite heap garbage with a bit pattern.
Definition at line 161 of file v8-statistics.h.
{ return does_zap_garbage_; }
external_memory()
size_t v8::HeapStatistics::external_memory () [inline]
Definition at line 152 of file v8-statistics.h.
{ return external_memory_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics(), and v8_inspector::V8RuntimeAgentImpl::getHeapUsage().
heap_size_limit()
size_t v8::HeapStatistics::heap_size_limit () [inline]
Definition at line 150 of file v8-statistics.h.
{ return heap_size_limit_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
malloced_memory()
size_t v8::HeapStatistics::malloced_memory () [inline]
Definition at line 151 of file v8-statistics.h.
{ return malloced_memory_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
number_of_detached_contexts()
size_t v8::HeapStatistics::number_of_detached_contexts () [inline]
Definition at line 155 of file v8-statistics.h.
{ return number_of_detached_contexts_; }
number_of_native_contexts()
size_t v8::HeapStatistics::number_of_native_contexts () [inline]
Definition at line 154 of file v8-statistics.h.
{ return number_of_native_contexts_; }
peak_malloced_memory()
size_t v8::HeapStatistics::peak_malloced_memory () [inline]
Definition at line 153 of file v8-statistics.h.
{ return peak_malloced_memory_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
total_available_size()
size_t v8::HeapStatistics::total_available_size () [inline]
Definition at line 146 of file v8-statistics.h.
{ return total_available_size_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
total_global_handles_size()
size_t v8::HeapStatistics::total_global_handles_size () [inline]
Definition at line 147 of file v8-statistics.h.
{ return total_global_handles_size_; }
total_heap_size()
size_t v8::HeapStatistics::total_heap_size () [inline]
Definition at line 143 of file v8-statistics.h.
{ return total_heap_size_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics(), and v8_inspector::V8RuntimeAgentImpl::getHeapUsage().
total_heap_size_executable()
size_t v8::HeapStatistics::total_heap_size_executable () [inline]
Definition at line 144 of file v8-statistics.h.
{ return total_heap_size_executable_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
total_physical_size()
size_t v8::HeapStatistics::total_physical_size () [inline]
Definition at line 145 of file v8-statistics.h.
{ return total_physical_size_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
used_global_handles_size()
size_t v8::HeapStatistics::used_global_handles_size () [inline]
Definition at line 148 of file v8-statistics.h.
{ return used_global_handles_size_; }
used_heap_size()
size_t v8::HeapStatistics::used_heap_size () [inline]
Definition at line 149 of file v8-statistics.h.
{ return used_heap_size_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics(), and v8_inspector::V8RuntimeAgentImpl::getHeapUsage().
Friends And Related Function Documentation
Isolate
friend class Isolate [friend]
Definition at line 180 of file v8-statistics.h.
V8
friend class V8 [friend]
Definition at line 179 of file v8-statistics.h.
Member Data Documentation
does_zap_garbage_
bool v8::HeapStatistics::does_zap_garbage_ [private]
Definition at line 173 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
external_memory_
size_t v8::HeapStatistics::external_memory_ [private]
Definition at line 171 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
heap_size_limit_
size_t v8::HeapStatistics::heap_size_limit_ [private]
Definition at line 169 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
malloced_memory_
size_t v8::HeapStatistics::malloced_memory_ [private]
Definition at line 170 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
number_of_detached_contexts_
size_t v8::HeapStatistics::number_of_detached_contexts_ [private]
Definition at line 175 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
number_of_native_contexts_
size_t v8::HeapStatistics::number_of_native_contexts_ [private]
Definition at line 174 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
peak_malloced_memory_
size_t v8::HeapStatistics::peak_malloced_memory_ [private]
Definition at line 172 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
total_available_size_
size_t v8::HeapStatistics::total_available_size_ [private]
Definition at line 167 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
total_global_handles_size_
size_t v8::HeapStatistics::total_global_handles_size_ [private]
Definition at line 176 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
total_heap_size_
size_t v8::HeapStatistics::total_heap_size_ [private]
Definition at line 164 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
total_heap_size_executable_
size_t v8::HeapStatistics::total_heap_size_executable_ [private]
Definition at line 165 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
total_physical_size_
size_t v8::HeapStatistics::total_physical_size_ [private]
Definition at line 166 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
used_global_handles_size_
size_t v8::HeapStatistics::used_global_handles_size_ [private]
Definition at line 177 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
used_heap_size_
size_t v8::HeapStatistics::used_heap_size_ [private]
Definition at line 168 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapStatistics().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-statistics.h
/mnt/V8SourceCode/src/api/api.cc