v8::internal::compiler::JSLoadGlobalNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSLoadGlobalNode (Node *node)
const LoadGlobalParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1648 of file js-operator.h.
Constructor & Destructor Documentation
JSLoadGlobalNode()
constexpr v8::internal::compiler::JSLoadGlobalNode::JSLoadGlobalNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1650 of file js-operator.h.
                                                  : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSLoadGlobal, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const LoadGlobalParameters& v8::internal::compiler::JSLoadGlobalNode::Parameters () const [inline]
Definition at line 1654 of file js-operator.h.
                                                 {
    return LoadGlobalParametersOf(node()->op());
  }
References v8::internal::compiler::LoadGlobalParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h