v8::internal::compiler::ConstructForwardVarargsParameters Class Reference
#include <js-operator.h>
Public Member Functions
ConstructForwardVarargsParameters (size_t arity, uint32_t start_index)
size_t arity () const
uint32_t start_index () const
bool operator== (ConstructForwardVarargsParameters const &that) const
bool operator!= (ConstructForwardVarargsParameters const &that) const
Private Types
using ArityField = base::BitField< size_t, 0, 16 >
using StartIndexField = base::BitField< uint32_t, 16, 16 >
Private Attributes
uint32_t const bit_field_
Friends
size_t hash_value (ConstructForwardVarargsParameters const &p)
Detailed Description
Definition at line 116 of file js-operator.h.
Member Typedef Documentation
ArityField
using v8::internal::compiler::ConstructForwardVarargsParameters::ArityField = base::BitField<size_t, 0, 16> [private]
Definition at line 137 of file js-operator.h.
StartIndexField
using v8::internal::compiler::ConstructForwardVarargsParameters::StartIndexField = base::BitField<uint32_t, 16, 16> [private]
Definition at line 138 of file js-operator.h.
Constructor & Destructor Documentation
ConstructForwardVarargsParameters()
v8::internal::compiler::ConstructForwardVarargsParameters::ConstructForwardVarargsParameters (size_t arity, uint32_t start_index) [inline]
Definition at line 118 of file js-operator.h.
      : bit_field_(ArityField::encode(arity) |
                   StartIndexField::encode(start_index)) {}
Member Function Documentation
arity()
size_t v8::internal::compiler::ConstructForwardVarargsParameters::arity () const [inline]
Definition at line 122 of file js-operator.h.
{ return ArityField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::JSOperatorBuilder::ConstructForwardVarargs(), v8::internal::compiler::operator<<(), and v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs().
operator!=()
bool v8::internal::compiler::ConstructForwardVarargsParameters::operator!= (ConstructForwardVarargsParameters const & that) const [inline]
Definition at line 128 of file js-operator.h.
                                                                       {
    return !(*this == that);
  }
operator==()
bool v8::internal::compiler::ConstructForwardVarargsParameters::operator== (ConstructForwardVarargsParameters const & that) const [inline]
Definition at line 125 of file js-operator.h.
                                                                       {
    return this->bit_field_ == that.bit_field_;
  }
References bit_field_.
start_index()
uint32_t v8::internal::compiler::ConstructForwardVarargsParameters::start_index () const [inline]
Definition at line 123 of file js-operator.h.
{ return StartIndexField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs().
Friends And Related Function Documentation
hash_value
size_t hash_value (ConstructForwardVarargsParameters const & p) [friend]
Definition at line 133 of file js-operator.h.
                                                                       {
    return p.bit_field_;
  }
Member Data Documentation
bit_field_
uint32_t const v8::internal::compiler::ConstructForwardVarargsParameters::bit_field_ [private]
Definition at line 140 of file js-operator.h.
Referenced by arity(), operator==(), and start_index().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h