v8::internal::EvacuateNewToOldSpacePageVisitor Class Reference
Public Member Functions
EvacuateNewToOldSpacePageVisitor (Heap *heap, RecordMigratedSlotVisitor *record_visitor, PretenuringHandler::PretenuringFeedbackMap *local_pretenuring_feedback)
bool Visit (Tagged< HeapObject > object, int size) override
intptr_t moved_bytes ()
void account_moved_bytes (intptr_t bytes)
Static Public Member Functions
static void Move (PageMetadata *page)
Private Attributes
Heap * heap_
RecordMigratedSlotVisitor * record_visitor_
intptr_t moved_bytes_
PretenuringHandler *const pretenuring_handler_
PretenuringHandler::PretenuringFeedbackMap * local_pretenuring_feedback_
Detailed Description
Definition at line 1752 of file mark-compact.cc.
Constructor & Destructor Documentation
EvacuateNewToOldSpacePageVisitor()
v8::internal::EvacuateNewToOldSpacePageVisitor::EvacuateNewToOldSpacePageVisitor (Heap * heap, RecordMigratedSlotVisitor * record_visitor, PretenuringHandler::PretenuringFeedbackMap * local_pretenuring_feedback) [inline], [explicit]
Definition at line 1754 of file mark-compact.cc.
      : heap_(heap),
        record_visitor_(record_visitor),
        moved_bytes_(0),
        pretenuring_handler_(heap_->pretenuring_handler()),
        local_pretenuring_feedback_(local_pretenuring_feedback) {}
Member Function Documentation
account_moved_bytes()
void v8::internal::EvacuateNewToOldSpacePageVisitor::account_moved_bytes (intptr_t bytes) [inline]
Definition at line 1778 of file mark-compact.cc.
{ moved_bytes_ += bytes; }
References moved_bytes_.
Move()
static void v8::internal::EvacuateNewToOldSpacePageVisitor::Move (PageMetadata * page) [inline], [static]
Definition at line 1763 of file mark-compact.cc.
                                       {
    page->heap()->new_space()->PromotePageToOldSpace(
        page, v8_flags.minor_ms ? FreeMode::kDoNotLinkCategory
                                : FreeMode::kLinkCategory);
  }
References v8::internal::MemoryChunkMetadata::heap(), v8::internal::kDoNotLinkCategory, v8::internal::kLinkCategory, v8::internal::Heap::new_space(), v8::internal::NewSpace::PromotePageToOldSpace(), and v8::internal::v8_flags.
moved_bytes()
intptr_t v8::internal::EvacuateNewToOldSpacePageVisitor::moved_bytes () [inline]
Definition at line 1777 of file mark-compact.cc.
{ return moved_bytes_; }
References moved_bytes_.
Visit()
bool v8::internal::EvacuateNewToOldSpacePageVisitor::Visit (Tagged< HeapObject > object, int size) [inline], [override], [virtual]
Implements v8::internal::HeapObjectVisitor.
Definition at line 1769 of file mark-compact.cc.
                                                                  {
    PretenuringHandler::UpdateAllocationSite(heap_, object->map(), object, size,
                                             local_pretenuring_feedback_);
    DCHECK(!HeapLayout::InCodeSpace(object));
    record_visitor_->Visit(object->map(), object, size);
    return true;
  }
References v8::internal::DCHECK(), heap_, v8::internal::HeapLayout::InCodeSpace(), local_pretenuring_feedback_, record_visitor_, size(), v8::internal::PretenuringHandler::UpdateAllocationSite(), and v8::internal::HeapVisitor< ConcreteVisitor >::Visit().
Member Data Documentation
heap_
Heap* v8::internal::EvacuateNewToOldSpacePageVisitor::heap_ [private]
Definition at line 1781 of file mark-compact.cc.
Referenced by Visit().
local_pretenuring_feedback_
PretenuringHandler::PretenuringFeedbackMap* v8::internal::EvacuateNewToOldSpacePageVisitor::local_pretenuring_feedback_ [private]
Definition at line 1785 of file mark-compact.cc.
Referenced by Visit().
moved_bytes_
intptr_t v8::internal::EvacuateNewToOldSpacePageVisitor::moved_bytes_ [private]
Definition at line 1783 of file mark-compact.cc.
Referenced by account_moved_bytes(), and moved_bytes().
pretenuring_handler_
PretenuringHandler* const v8::internal::EvacuateNewToOldSpacePageVisitor::pretenuring_handler_ [private]
Definition at line 1784 of file mark-compact.cc.
record_visitor_
RecordMigratedSlotVisitor* v8::internal::EvacuateNewToOldSpacePageVisitor::record_visitor_ [private]
Definition at line 1782 of file mark-compact.cc.
Referenced by Visit().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc