v8::internal::FullObjectSlot Class Reference
#include <slots.h>
Public Types
using TObject = Tagged< Object >
using THeapObjectSlot = FullHeapObjectSlot
Public Member Functions
FullObjectSlot ()
FullObjectSlot (Address ptr)
FullObjectSlot (const Address *ptr)
FullObjectSlot (TaggedBase *object)
template<typename T >
FullObjectSlot (SlotBase< T, TData, kSlotDataAlignment > slot)
bool contains_map_value (Address raw_value) const
bool Relaxed_ContainsMapValue (Address raw_value) const
Tagged< Object > operator* () const
Tagged< Object > load () const
Tagged< Object > load (PtrComprCageBase cage_base) const
void store (Tagged< Object > value) const
void store_map (Tagged< Map > map) const
Tagged< Map > load_map () const
Tagged< Object > Acquire_Load () const
Tagged< Object > Acquire_Load (PtrComprCageBase cage_base) const
Tagged< Object > Relaxed_Load () const
Tagged< Object > Relaxed_Load (PtrComprCageBase cage_base) const
Address Relaxed_Load_Raw () const
void Relaxed_Store (Tagged< Object > value) const
void Release_Store (Tagged< Object > value) const
Tagged< Object > Relaxed_CompareAndSwap (Tagged< Object > old, Tagged< Object > target) const
Tagged< Object > Release_CompareAndSwap (Tagged< Object > old, Tagged< Object > target) const
Static Public Member Functions
static Tagged< Object > RawToTagged (PtrComprCageBase cage_base, Address raw)
Static Public Attributes
static constexpr bool kCanBeWeak = false
Additional Inherited Members
Detailed Description
Definition at line 98 of file slots.h.
Member Typedef Documentation
THeapObjectSlot
using v8::internal::FullObjectSlot::THeapObjectSlot = FullHeapObjectSlot
Definition at line 101 of file slots.h.
TObject
using v8::internal::FullObjectSlot::TObject = Tagged<Object>
Definition at line 100 of file slots.h.
Constructor & Destructor Documentation
FullObjectSlot() [1/5]
v8::internal::FullObjectSlot::FullObjectSlot () [inline]
Definition at line 106 of file slots.h.
: SlotBase(kNullAddress) {}
FullObjectSlot() [2/5]
v8::internal::FullObjectSlot::FullObjectSlot (Address ptr) [inline], [explicit]
Definition at line 107 of file slots.h.
: SlotBase(ptr) {}
FullObjectSlot() [3/5]
v8::internal::FullObjectSlot::FullObjectSlot (const Address * ptr) [inline], [explicit]
Definition at line 108 of file slots.h.
      : SlotBase(reinterpret_cast<Address>(ptr)) {}
FullObjectSlot() [4/5]
v8::internal::FullObjectSlot::FullObjectSlot (TaggedBase * object) [inline], [explicit]
Definition at line 33 of file slots-inl.h.
    : SlotBase(reinterpret_cast<Address>(&object->ptr_)) {}
FullObjectSlot() [5/5]
template<typename T >
v8::internal::FullObjectSlot::FullObjectSlot (SlotBase< T, TData, kSlotDataAlignment > slot) [inline], [explicit]
Definition at line 117 of file slots.h.
      : SlotBase(slot.address()) {}
Member Function Documentation
Acquire_Load() [1/2]
Tagged< Object > v8::internal::FullObjectSlot::Acquire_Load () const [inline]
Definition at line 74 of file slots-inl.h.
                                                  {
  return Tagged<Object>(base::AsAtomicPointer::Acquire_Load(location()));
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), v8::internal::SlotBase< FullObjectSlot, Address >::location(), and v8::internal::Tagged< Object >.
Referenced by Acquire_Load(), v8::internal::StringForwardingTable::Record::ForwardStringObjectOrHash(), v8::internal::StringTable::OffHeapStringHashSet::GetKey(), v8::internal::StringForwardingTable::Record::OriginalStringObject(), v8::internal::InstructionStream::raw_code(), v8::internal::InstructionStream::unchecked_relocation_info(), v8::internal::StringForwardingTable::Block::UpdateAfterFullEvacuation(), v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation(), and v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitEphemeronHashTable().
Acquire_Load() [2/2]
Tagged< Object > v8::internal::FullObjectSlot::Acquire_Load (PtrComprCageBase cage_base) const [inline]
Definition at line 78 of file slots-inl.h.
                                                                            {
  return Acquire_Load();
}
References Acquire_Load().
contains_map_value()
bool v8::internal::FullObjectSlot::contains_map_value (Address raw_value) const [inline]
Definition at line 36 of file slots-inl.h.
                                                               {
  return load_map().ptr() == raw_value;
}
References load_map(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::Heap::IsFreeSpaceValid(), and v8::internal::FreeListCategory::RepairFreeList().
load() [1/2]
Tagged< Object > v8::internal::FullObjectSlot::load () const [inline]
Definition at line 48 of file slots-inl.h.
{ return **this; }
Referenced by v8::internal::SharedStructTypeRegistry::Data::GetKey(), load(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::ProcessSlot(), v8::internal::Code::raw_deoptimization_data_or_interpreter_data(), v8::internal::Code::raw_position_table(), v8::internal::WasmObject::ReadValueAt(), v8::internal::Isolate::VerifyStaticRoots(), v8::internal::ClientObjectVisitor< Visitor >::VisitInstructionStreamPointer(), v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitInstructionStreamPointer(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitInstructionStreamPointer(), and v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer().
load() [2/2]
Tagged< Object > v8::internal::FullObjectSlot::load (PtrComprCageBase cage_base) const [inline]
Definition at line 50 of file slots-inl.h.
                                                                    {
  return load();
}
References load().
load_map()
Tagged< Map > v8::internal::FullObjectSlot::load_map () const [inline]
Definition at line 66 of file slots-inl.h.
                                           {
#ifdef V8_MAP_PACKING
  return UncheckedCast<Map>(Tagged<Object>(MapWord::Unpack(*location())));
#else
  return UncheckedCast<Map>(Tagged<Object>(*location()));
#endif
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location().
Referenced by contains_map_value().
operator*()
Tagged< Object > v8::internal::FullObjectSlot::operator* () const [inline]
Definition at line 44 of file slots-inl.h.
                                               {
  return Tagged<Object>(*location());
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), and v8::internal::Tagged< Object >.
RawToTagged()
Tagged< Object > v8::internal::FullObjectSlot::RawToTagged (PtrComprCageBase cage_base, Address raw) [inline], [static]
Definition at line 95 of file slots-inl.h.
                                                        {
  return Tagged<Object>(raw);
}
References v8::internal::Tagged< Object >.
Relaxed_CompareAndSwap()
Tagged< Object > v8::internal::FullObjectSlot::Relaxed_CompareAndSwap (Tagged< Object > old, Tagged< Object > target) const [inline]
Definition at line 108 of file slots-inl.h.
                                                     {
  Address result = base::AsAtomicPointer::Relaxed_CompareAndSwap(
      location(), old.ptr(), target.ptr());
  return Tagged<Object>(result);
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_CompareAndSwap(), v8::base::internal::result, and v8::internal::Tagged< Object >.
Referenced by v8::internal::Heap::NextScriptId().
Relaxed_ContainsMapValue()
bool v8::internal::FullObjectSlot::Relaxed_ContainsMapValue (Address raw_value) const [inline]
Definition at line 40 of file slots-inl.h.
                                                                     {
  return base::AsAtomicPointer::Relaxed_Load(location()) == raw_value;
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by v8::internal::PretenuringHandler::FindAllocationMemento().
Relaxed_Load() [1/2]
Tagged< Object > v8::internal::FullObjectSlot::Relaxed_Load () const [inline]
Definition at line 82 of file slots-inl.h.
                                                  {
  return Tagged<Object>(base::AsAtomicPointer::Relaxed_Load(location()));
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), and v8::internal::Tagged< Object >.
Referenced by v8::internal::EmbedderDataSlot::load_tagged(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::Heap::NextScriptId(), v8::internal::EphemeronTableUpdatingItem::Process(), Relaxed_Load(), v8::internal::RootMarkingVisitor::VisitRootPointer(), and v8::internal::PointersUpdatingVisitor::VisitRootPointer().
Relaxed_Load() [2/2]
Tagged< Object > v8::internal::FullObjectSlot::Relaxed_Load (PtrComprCageBase cage_base) const [inline]
Definition at line 86 of file slots-inl.h.
                                                                            {
  return Relaxed_Load();
}
References Relaxed_Load().
Relaxed_Load_Raw()
Address v8::internal::FullObjectSlot::Relaxed_Load_Raw () const [inline]
Definition at line 90 of file slots-inl.h.
                                               {
  return static_cast<Address>(base::AsAtomicPointer::Relaxed_Load(location()));
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Relaxed_Store()
void v8::internal::FullObjectSlot::Relaxed_Store (Tagged< Object > value) const [inline]
Definition at line 100 of file slots-inl.h.
                                                             {
  base::AsAtomicPointer::Relaxed_Store(location(), value.ptr());
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), and v8::internal::value.
Referenced by v8::internal::EmbedderDataSlot::gc_safe_store(), v8::internal::EmbedderDataSlot::Initialize(), v8::internal::EphemeronTableUpdatingItem::Process(), v8::internal::EmbedderDataSlot::store_aligned_pointer(), v8::internal::EmbedderDataSlot::store_smi(), and v8::internal::EmbedderDataSlot::store_tagged().
Release_CompareAndSwap()
Tagged< Object > v8::internal::FullObjectSlot::Release_CompareAndSwap (Tagged< Object > old, Tagged< Object > target) const [inline]
Definition at line 115 of file slots-inl.h.
                                                     {
  Address result = base::AsAtomicPointer::Release_CompareAndSwap(
      location(), old.ptr(), target.ptr());
  return Tagged<Object>(result);
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap(), v8::base::internal::result, and v8::internal::Tagged< Object >.
Release_Store()
void v8::internal::FullObjectSlot::Release_Store (Tagged< Object > value) const [inline]
Definition at line 104 of file slots-inl.h.
                                                             {
  base::AsAtomicPointer::Release_Store(location(), value.ptr());
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), and v8::internal::value.
Referenced by v8::internal::StringForwardingTable::Record::set_forward_string(), v8::internal::StringForwardingTable::Record::set_original_string(), v8::internal::StringTable::OffHeapStringHashSet::SetKey(), v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation(), and v8::internal::anonymous_namespace{string-forwarding-table.cc}::UpdateForwardedSlot().
store()
void v8::internal::FullObjectSlot::store (Tagged< Object > value) const [inline]
Definition at line 54 of file slots-inl.h.
                                                     {
  *location() = value.ptr();
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), and v8::internal::value.
Referenced by v8::internal::PropertyCallbackArguments::CallAccessorGetter(), v8::internal::PropertyCallbackArguments::CallAccessorSetter(), v8::internal::PropertyCallbackArguments::CallIndexedDefiner(), v8::internal::PropertyCallbackArguments::CallIndexedDeleter(), v8::internal::PropertyCallbackArguments::CallIndexedDescriptor(), v8::internal::PropertyCallbackArguments::CallIndexedGetter(), v8::internal::PropertyCallbackArguments::CallIndexedQuery(), v8::internal::PropertyCallbackArguments::CallIndexedSetter(), v8::internal::PropertyCallbackArguments::CallNamedDefiner(), v8::internal::PropertyCallbackArguments::CallNamedDeleter(), v8::internal::PropertyCallbackArguments::CallNamedDescriptor(), v8::internal::PropertyCallbackArguments::CallNamedGetter(), v8::internal::PropertyCallbackArguments::CallNamedQuery(), v8::internal::PropertyCallbackArguments::CallNamedSetter(), v8::internal::PropertyCallbackArguments::CallPropertyEnumerator(), v8::internal::ClearStaleLeftTrimmedPointerVisitor::ClearLeftTrimmedOrForward(), v8::internal::GlobalHandles::Node::CollectPhantomCallbackData(), v8::internal::FunctionCallbackArguments::FunctionCallbackArguments(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::ProcessSlot(), v8::internal::PropertyCallbackArguments::PropertyCallbackArguments(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ApiCallbackExitFrame::set_target(), v8::internal::SharedStructTypeRegistry::Data::SetKey(), store_map(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::Heap::ExternalStringTable::UpdateYoungReferences().
store_map()
void v8::internal::FullObjectSlot::store_map (Tagged< Map > map) const [inline]
Definition at line 58 of file slots-inl.h.
                                                    {
#ifdef V8_MAP_PACKING
  *location() = MapWord::Pack(map.ptr());
#else
  store(map);
#endif
}
References v8::internal::SlotBase< FullObjectSlot, Address >::location(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and store().
Referenced by v8::internal::FreeListCategory::RepairFreeList().
Member Data Documentation
kCanBeWeak
constexpr bool v8::internal::FullObjectSlot::kCanBeWeak = false [static], [constexpr]
Definition at line 104 of file slots.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/slots.h
/mnt/V8SourceCode/src/objects/slots-inl.h