v8::internal::compiler::NodeCopier Class Reference
#include <loop-analysis.h>
Public Member Functions
NodeCopier (TFGraph *graph, uint32_t max, NodeVector *p, uint32_t copy_count)
Node * map (Node *node, uint32_t copy_index)
Node * map (Node *node)
void Insert (Node *original, const NodeVector &new_copies)
void Insert (Node *original, Node *copy)
template<typename InputIterator >
void CopyNodes (TFGraph *graph, Zone *tmp_zone_, Node *dead, base::iterator_range< InputIterator > nodes, SourcePositionTable *source_positions, NodeOriginTable *node_origins)
bool Marked (Node *node)
Private Attributes
NodeMarker< size_t > node_map_
NodeVector * copies_
const uint32_t copy_count_
Detailed Description
Definition at line 202 of file loop-analysis.h.
Constructor & Destructor Documentation
NodeCopier()
v8::internal::compiler::NodeCopier::NodeCopier (TFGraph * graph, uint32_t max, NodeVector * p, uint32_t copy_count) [inline]
Definition at line 208 of file loop-analysis.h.
      : node_map_(graph, max), copies_(p), copy_count_(copy_count) {
    DCHECK_GT(copy_count, 0);
  }
References DCHECK_GT.
Member Function Documentation
CopyNodes()
template<typename InputIterator >
void v8::internal::compiler::NodeCopier::CopyNodes (TFGraph * graph, Zone * tmp_zone_, Node * dead, base::iterator_range< InputIterator > nodes, SourcePositionTable * source_positions, NodeOriginTable * node_origins) [inline]
Definition at line 227 of file loop-analysis.h.
                                                {
    // Copy all the nodes first.
    for (Node* original : nodes) {
      SourcePositionTable::Scope position(
          source_positions, source_positions->GetSourcePosition(original));
      NodeOriginTable::Scope origin_scope(node_origins, "copy nodes", original);
      node_map_.Set(original, copies_->size() + 1);
      copies_->push_back(original);
      for (uint32_t copy_index = 0; copy_index < copy_count_; copy_index++) {
        Node* copy = graph->CloneNode(original);
        copies_->push_back(copy);
      }
    }
    // Fix inputs of the copies.
    for (Node* original : nodes) {
      for (uint32_t copy_index = 0; copy_index < copy_count_; copy_index++) {
        Node* copy = map(original, copy_index);
        for (int i = 0; i < copy->InputCount(); i++) {
          copy->ReplaceInput(i, map(original->InputAt(i), copy_index));
        }
      }
    }
  }
References copies_, copy_count_, v8::internal::compiler::SourcePositionTable::GetSourcePosition(), graph(), v8::internal::compiler::Node::InputCount(), map(), node_map_, v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeMarker< State >::Set(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::LoopPeeler::Peel(), and v8::internal::compiler::UnrollLoop().
Insert() [1/2]
void v8::internal::compiler::NodeCopier::Insert (Node * original, const NodeVector & new_copies)
Definition at line 756 of file loop-analysis.cc.
                                                                    {
  DCHECK_EQ(new_copies.size(), copy_count_);
  node_map_.Set(original, copies_->size() + 1);
  copies_->push_back(original);
  copies_->insert(copies_->end(), new_copies.begin(), new_copies.end());
}
References v8::internal::ZoneVector< T >::begin(), DCHECK_EQ, v8::internal::ZoneVector< T >::end(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::LoopPeeler::Peel().
Insert() [2/2]
void v8::internal::compiler::NodeCopier::Insert (Node * original, Node * copy)
Definition at line 763 of file loop-analysis.cc.
                                                  {
  DCHECK_EQ(copy_count_, 1);
  node_map_.Set(original, copies_->size() + 1);
  copies_->push_back(original);
  copies_->push_back(copy);
}
References DCHECK_EQ.
map() [1/2]
Node* v8::internal::compiler::NodeCopier::map (Node * node) [inline]
Definition at line 218 of file loop-analysis.h.
{ return map(node, 0); }
References map().
Referenced by map().
map() [2/2]
Node * v8::internal::compiler::NodeCopier::map (Node * node, uint32_t copy_index)
Definition at line 750 of file loop-analysis.cc.
                                                     {
  DCHECK_LT(copy_index, copy_count_);
  if (node_map_.Get(node) == 0) return node;
  return copies_->at(node_map_.Get(node) + copy_index);
}
References DCHECK_LT.
Referenced by CopyNodes(), and v8::internal::compiler::LoopPeeler::Peel().
Marked()
bool v8::internal::compiler::NodeCopier::Marked (Node * node) [inline]
Definition at line 255 of file loop-analysis.h.
{ return node_map_.Get(node) > 0; }
References v8::internal::compiler::NodeMarker< State >::Get(), and node_map_.
Member Data Documentation
copies_
NodeVector* v8::internal::compiler::NodeCopier::copies_ [private]
Definition at line 261 of file loop-analysis.h.
Referenced by CopyNodes().
copy_count_
const uint32_t v8::internal::compiler::NodeCopier::copy_count_ [private]
Definition at line 263 of file loop-analysis.h.
Referenced by CopyNodes().
node_map_
NodeMarker<size_t> v8::internal::compiler::NodeCopier::node_map_ [private]
Definition at line 259 of file loop-analysis.h.
Referenced by CopyNodes(), and Marked().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/loop-analysis.h
/mnt/V8SourceCode/src/compiler/loop-analysis.cc