v8::internal::torque::Ast Class Reference
#include <ast.h>
Public Member Functions
Ast ()=default
std::vector< Declaration * > & declarations ()
const std::vector< Declaration * > & declarations () const
template<class T >
T * AddNode (std::unique_ptr< T > node)
void DeclareImportForCurrentFile (SourceId import_id)
void AddEnumDescription (EnumDescription description)
std::vector< EnumDescription > & EnumDescriptions ()
Private Attributes
std::vector< Declaration * > declarations_
std::vector< std::unique_ptr< AstNode > > nodes_
std::map< SourceId, std::set< SourceId > > declared_imports_
std::vector< EnumDescription > enum_descriptions_
Detailed Description
Definition at line 212 of file ast.h.
Constructor & Destructor Documentation
Ast()
v8::internal::torque::Ast::Ast () [default]
Member Function Documentation
AddEnumDescription()
void v8::internal::torque::Ast::AddEnumDescription (EnumDescription description) [inline]
Definition at line 231 of file ast.h.
                                                       {
    std::string name = description.name;
    DCHECK(!name.empty());
    auto f = [&](const auto& d) { return d.name == name; };
    USE(f); // Suppress unused in release.
    DCHECK_EQ(
        std::find_if(enum_descriptions_.begin(), enum_descriptions_.end(), f),
        enum_descriptions_.end());
    enum_descriptions_.push_back(std::move(description));
  }
References v8::internal::DCHECK(), DCHECK_EQ, enum_descriptions_, v8::internal::name, v8::internal::torque::EnumDescription::name, v8::internal::string, and USE.
AddNode()
template<class T >
T* v8::internal::torque::Ast::AddNode (std::unique_ptr< T > node) [inline]
Definition at line 221 of file ast.h.
                                    {
    T* result = node.get();
    nodes_.push_back(std::move(node));
    return result;
  }
References nodes_, and v8::base::internal::result.
declarations() [1/2]
std::vector<Declaration*>& v8::internal::torque::Ast::declarations () [inline]
Definition at line 216 of file ast.h.
{ return declarations_; }
References declarations_.
Referenced by v8::internal::torque::PredeclarationVisitor::Predeclare(), and v8::internal::torque::DeclarationVisitor::Visit().
declarations() [2/2]
const std::vector<Declaration*>& v8::internal::torque::Ast::declarations () const [inline]
Definition at line 217 of file ast.h.
                                                      {
    return declarations_;
  }
References declarations_.
DeclareImportForCurrentFile()
void v8::internal::torque::Ast::DeclareImportForCurrentFile (SourceId import_id) [inline]
Definition at line 227 of file ast.h.
                                                       {
    declared_imports_[CurrentSourcePosition::Get().source].insert(import_id);
  }
References declared_imports_, and v8::internal::compiler::turboshaft::Get().
EnumDescriptions()
std::vector<EnumDescription>& v8::internal::torque::Ast::EnumDescriptions () [inline]
Definition at line 242 of file ast.h.
                                                 {
    return enum_descriptions_;
  }
References enum_descriptions_.
Member Data Documentation
declarations_
std::vector<Declaration*> v8::internal::torque::Ast::declarations_ [private]
Definition at line 247 of file ast.h.
Referenced by declarations().
declared_imports_
std::map<SourceId, std::set<SourceId> > v8::internal::torque::Ast::declared_imports_ [private]
Definition at line 249 of file ast.h.
Referenced by DeclareImportForCurrentFile().
enum_descriptions_
std::vector<EnumDescription> v8::internal::torque::Ast::enum_descriptions_ [private]
Definition at line 250 of file ast.h.
Referenced by AddEnumDescription(), and EnumDescriptions().
nodes_
std::vector<std::unique_ptr<AstNode> > v8::internal::torque::Ast::nodes_ [private]
Definition at line 248 of file ast.h.
Referenced by AddNode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/ast.h