v8::internal::FrameFunctionIterator Class Reference
Public Member Functions
FrameFunctionIterator (Isolate *isolate)
bool Find (DirectHandle< JSFunction > function)
bool FindNextNonTopLevelNativeOrUserJavaScript ()
DirectHandle< JSFunction > MaterializeFunction ()
Private Member Functions
MaybeDirectHandle< JSFunction > next ()
void GetFrames ()
Private Attributes
Isolate * isolate_
DirectHandle< JSFunction > function_
JavaScriptStackFrameIterator frame_iterator_
FrameSummaries summaries_
int inlined_frame_index_
Detailed Description
Definition at line 569 of file accessors.cc.
Constructor & Destructor Documentation
FrameFunctionIterator()
v8::internal::FrameFunctionIterator::FrameFunctionIterator (Isolate * isolate) [inline], [explicit]
Definition at line 571 of file accessors.cc.
      : isolate_(isolate), frame_iterator_(isolate), inlined_frame_index_(-1) {
    GetFrames();
  }
References GetFrames().
Member Function Documentation
Find()
bool v8::internal::FrameFunctionIterator::Find (DirectHandle< JSFunction > function) [inline]
Definition at line 578 of file accessors.cc.
                                               {
    do {
      if (!next().ToHandle(&function_)) return false;
    } while (!function_.is_identical_to(function));
    return true;
  }
References function_, next(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::anonymous_namespace{accessors.cc}::FindCaller().
FindNextNonTopLevelNativeOrUserJavaScript()
bool v8::internal::FrameFunctionIterator::FindNextNonTopLevelNativeOrUserJavaScript () [inline]
Definition at line 589 of file accessors.cc.
                                                   {
    do {
      if (!next().ToHandle(&function_)) return false;
    } while (function_->shared()->is_toplevel() ||
             (!function_->shared()->native() &&
              !function_->shared()->IsUserJavaScript()));
    return true;
  }
References function_, next(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::anonymous_namespace{accessors.cc}::FindCaller().
GetFrames()
void v8::internal::FrameFunctionIterator::GetFrames () [inline], [private]
Definition at line 645 of file accessors.cc.
                   {
    DCHECK_EQ(-1, inlined_frame_index_);
    if (frame_iterator_.done()) return;
    JavaScriptFrame* frame = frame_iterator_.frame();
    summaries_ = frame->Summarize();
    inlined_frame_index_ = static_cast<int>(summaries_.size());
    DCHECK_LT(0, inlined_frame_index_);
  }
References DCHECK_EQ, DCHECK_LT, v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::JavaScriptStackFrameIterator::frame(), frame_iterator_, inlined_frame_index_, v8::internal::FrameSummaries::size(), summaries_, and v8::internal::CommonFrameWithJSLinkage::Summarize().
Referenced by FrameFunctionIterator(), and next().
MaterializeFunction()
DirectHandle<JSFunction> v8::internal::FrameFunctionIterator::MaterializeFunction () [inline]
Definition at line 603 of file accessors.cc.
                                                 {
    if (inlined_frame_index_ == 0) return function_;
    JavaScriptFrame* frame = frame_iterator_.frame();
    TranslatedState translated_values(frame);
    translated_values.Prepare(frame->fp());
    TranslatedFrame* translated_frame =
        translated_values.GetFrameFromJSFrameIndex(inlined_frame_index_);
    TranslatedFrame::iterator iter = translated_frame->begin();
    // First value is the function.
    bool should_deoptimize = iter->IsMaterializedObject();
    DirectHandle<Object> value = iter->GetValue();
    if (should_deoptimize) {
      translated_values.StoreMaterializedValuesAndDeopt(frame);
    }
    return Cast<JSFunction>(value);
  }
References v8::internal::TranslatedFrame::begin(), v8::internal::StackFrame::fp(), v8::internal::JavaScriptStackFrameIterator::frame(), frame_iterator_, function_, v8::internal::TranslatedState::GetFrameFromJSFrameIndex(), v8::internal::TranslatedValue::GetValue(), inlined_frame_index_, v8::internal::TranslatedValue::IsMaterializedObject(), v8::internal::TranslatedState::Prepare(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{accessors.cc}::FindCaller().
next()
MaybeDirectHandle<JSFunction> v8::internal::FrameFunctionIterator::next () [inline], [private]
Definition at line 625 of file accessors.cc.
                                       {
    while (true) {
      if (inlined_frame_index_ <= 0) {
        if (!frame_iterator_.done()) {
          frame_iterator_.Advance();
          summaries_.frames.clear();
          inlined_frame_index_ = -1;
          GetFrames();
        }
        if (inlined_frame_index_ == -1) return {};
      }
      --inlined_frame_index_;
      DirectHandle<JSFunction> next_function =
          summaries_.frames[inlined_frame_index_].AsJavaScript().function();
      // Skip functions from other origins.
      if (!AllowAccessToFunction(isolate_->context(), *next_function)) continue;
      return next_function;
    }
  }
References v8::internal::JavaScriptStackFrameIterator::Advance(), v8::internal::AllowAccessToFunction(), v8::internal::Isolate::context(), v8::internal::JavaScriptStackFrameIterator::done(), frame_iterator_, v8::internal::FrameSummaries::frames, GetFrames(), inlined_frame_index_, isolate_, and summaries_.
Referenced by Find(), and FindNextNonTopLevelNativeOrUserJavaScript().
Member Data Documentation
frame_iterator_
JavaScriptStackFrameIterator v8::internal::FrameFunctionIterator::frame_iterator_ [private]
Definition at line 655 of file accessors.cc.
Referenced by GetFrames(), MaterializeFunction(), and next().
function_
DirectHandle<JSFunction> v8::internal::FrameFunctionIterator::function_ [private]
Definition at line 654 of file accessors.cc.
Referenced by Find(), FindNextNonTopLevelNativeOrUserJavaScript(), and MaterializeFunction().
inlined_frame_index_
int v8::internal::FrameFunctionIterator::inlined_frame_index_ [private]
Definition at line 657 of file accessors.cc.
Referenced by GetFrames(), MaterializeFunction(), and next().
isolate_
Isolate* v8::internal::FrameFunctionIterator::isolate_ [private]
Definition at line 653 of file accessors.cc.
Referenced by next().
summaries_
FrameSummaries v8::internal::FrameFunctionIterator::summaries_ [private]
Definition at line 656 of file accessors.cc.
Referenced by GetFrames(), and next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/accessors.cc