v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope Class Reference
Public Member Functions
ModifyThreadInWasmFlagScope (WasmWrapperTSGraphBuilder *wasm_wrapper_graph_builder, Assembler &asm_)
ModifyThreadInWasmFlagScope (const ModifyThreadInWasmFlagScope &)=delete
~ModifyThreadInWasmFlagScope ()
Private Attributes
WasmWrapperTSGraphBuilder * wasm_wrapper_graph_builder_
V< WordPtr > thread_in_wasm_flag_address_
Detailed Description
Definition at line 79 of file wrappers.cc.
Constructor & Destructor Documentation
ModifyThreadInWasmFlagScope() [1/2]
v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope (WasmWrapperTSGraphBuilder * wasm_wrapper_graph_builder, Assembler & asm_) [inline]
Definition at line 81 of file wrappers.cc.
        : wasm_wrapper_graph_builder_(wasm_wrapper_graph_builder) {
      if (!trap_handler::IsTrapHandlerEnabled()) return;
      thread_in_wasm_flag_address_ =
          asm_.Load(asm_.LoadRootRegister(), OptionalOpIndex::Nullopt(),
                    LoadOp::Kind::RawAligned(), MemoryRepresentation::UintPtr(),
                    RegisterRepresentation::WordPtr(),
                    Isolate::thread_in_wasm_flag_address_offset());
      wasm_wrapper_graph_builder_->BuildModifyThreadInWasmFlagHelper(
          wasm_wrapper_graph_builder_->Asm().phase_zone(),
          thread_in_wasm_flag_address_, true);
    }
References v8::internal::wasm::WasmGraphBuilderBase::Asm(), v8::internal::wasm::WasmGraphBuilderBase::asm_, v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlagHelper(), v8::internal::trap_handler::IsTrapHandlerEnabled(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Load(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadRootRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::Nullopt(), v8::internal::compiler::turboshaft::Assembler< Reducers >::phase_zone(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), thread_in_wasm_flag_address_, v8::internal::Isolate::thread_in_wasm_flag_address_offset(), v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), wasm_wrapper_graph_builder_, and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
ModifyThreadInWasmFlagScope() [2/2]
v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope (const ModifyThreadInWasmFlagScope &) [delete]
 ModifyThreadInWasmFlagScope()
v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::~ModifyThreadInWasmFlagScope () [inline]
Definition at line 98 of file wrappers.cc.
                                   {
      if (!trap_handler::IsTrapHandlerEnabled()) return;
      wasm_wrapper_graph_builder_->BuildModifyThreadInWasmFlagHelper(
          wasm_wrapper_graph_builder_->Asm().phase_zone(),
          thread_in_wasm_flag_address_, false);
    }
References v8::internal::wasm::WasmGraphBuilderBase::Asm(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlagHelper(), v8::internal::trap_handler::IsTrapHandlerEnabled(), v8::internal::compiler::turboshaft::Assembler< Reducers >::phase_zone(), thread_in_wasm_flag_address_, and wasm_wrapper_graph_builder_.
Member Data Documentation
thread_in_wasm_flag_address_
V<WordPtr> v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::thread_in_wasm_flag_address_ [private]
Definition at line 107 of file wrappers.cc.
Referenced by ModifyThreadInWasmFlagScope(), and ~ModifyThreadInWasmFlagScope().
wasm_wrapper_graph_builder_
WasmWrapperTSGraphBuilder* v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::wasm_wrapper_graph_builder_ [private]
Definition at line 106 of file wrappers.cc.
Referenced by ModifyThreadInWasmFlagScope(), and ~ModifyThreadInWasmFlagScope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wrappers.cc