v8::base::Double Class Reference
#include <double.h>
Public Member Functions
constexpr Double ()
constexpr Double (double d)
constexpr Double (uint64_t d64)
constexpr Double (DiyFp diy_fp)
DiyFp AsDiyFp () const
DiyFp AsNormalizedDiyFp () const
constexpr uint64_t AsUint64 () const
constexpr double NextDouble () const
constexpr int Exponent () const
constexpr uint64_t Significand () const
constexpr bool IsDenormal () const
constexpr bool IsSpecial () const
constexpr bool IsInfinite () const
constexpr int Sign () const
DiyFp UpperBoundary () const
void NormalizedBoundaries (DiyFp *out_m_minus, DiyFp *out_m_plus) const
constexpr double value () const
Static Public Member Functions
static int SignificandSizeForOrderOfMagnitude (int order)
Static Public Attributes
static constexpr uint64_t kSignMask = 0x8000'0000'0000'0000
static constexpr uint64_t kExponentMask = 0x7FF0'0000'0000'0000
static constexpr uint64_t kSignificandMask = 0x000F'FFFF'FFFF'FFFF
static constexpr uint64_t kHiddenBit = 0x0010'0000'0000'0000
static constexpr int kPhysicalSignificandSize
static constexpr int kSignificandSize = 53
Static Private Member Functions
static constexpr uint64_t DiyFpToUint64 (DiyFp diy_fp)
Private Attributes
uint64_t d64_
Static Private Attributes
static constexpr int kExponentBias = 0x3FF + kPhysicalSignificandSize
static constexpr int kDenormalExponent = -kExponentBias + 1
static constexpr int kMaxExponent = 0x7FF - kExponentBias
static constexpr uint64_t kInfinity = 0x7FF0'0000'0000'0000
Detailed Description
Definition at line 25 of file double.h.
Constructor & Destructor Documentation
Double() [1/4]
constexpr v8::base::Double::Double () [inline], [constexpr]
Definition at line 35 of file double.h.
: d64_(0) {}
Referenced by NextDouble().
Double() [2/4]
constexpr v8::base::Double::Double (double d) [inline], [explicit], [constexpr]
Definition at line 36 of file double.h.
: d64_(double_to_uint64(d)) {}
Double() [3/4]
constexpr v8::base::Double::Double (uint64_t d64) [inline], [explicit], [constexpr]
Definition at line 37 of file double.h.
: d64_(d64) {}
Double() [4/4]
constexpr v8::base::Double::Double (DiyFp diy_fp) [inline], [explicit], [constexpr]
Definition at line 38 of file double.h.
: d64_(DiyFpToUint64(diy_fp)) {}
Member Function Documentation
AsDiyFp()
DiyFp v8::base::Double::AsDiyFp () const [inline]
Definition at line 42 of file double.h.
                        {
    DCHECK_GT(Sign(), 0);
    DCHECK(!IsSpecial());
    return DiyFp(Significand(), Exponent());
  }
References DCHECK, DCHECK_GT, Exponent(), IsSpecial(), Sign(), and Significand().
Referenced by NormalizedBoundaries().
AsNormalizedDiyFp()
DiyFp v8::base::Double::AsNormalizedDiyFp () const [inline]
Definition at line 49 of file double.h.
                                  {
    DCHECK_GT(value(), 0.0);
    uint64_t f = Significand();
    int e = Exponent();
    // The current double could be a denormal.
    while ((f & kHiddenBit) == 0) {
      f <<= 1;
      e--;
    }
    // Do the final shifts in one go.
    f <<= DiyFp::kSignificandSize - kSignificandSize;
    e -= DiyFp::kSignificandSize - kSignificandSize;
    return DiyFp(f, e);
  }
References DCHECK_GT, Exponent(), kHiddenBit, v8::base::DiyFp::kSignificandSize, kSignificandSize, Significand(), and value().
Referenced by v8::base::Grisu3(), and v8::base::Grisu3Counted().
AsUint64()
constexpr uint64_t v8::base::Double::AsUint64 () const [inline], [constexpr]
Definition at line 66 of file double.h.
{ return d64_; }
References d64_.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), Exponent(), v8::base::InitialScaledStartValuesNegativeExponentNegativePower(), v8::base::InitialScaledStartValuesNegativeExponentPositivePower(), v8::base::InitialScaledStartValuesPositiveExponent(), IsDenormal(), IsInfinite(), IsSpecial(), NormalizedBoundaries(), Sign(), Significand(), and v8::internal::compiler::X64OperandConverter::ToImmediate().
DiyFpToUint64()
static constexpr uint64_t v8::base::Double::DiyFpToUint64 (DiyFp diy_fp) [inline], [static], [constexpr], [private]
Definition at line 184 of file double.h.
                                                        {
    uint64_t significand = diy_fp.f();
    int exponent = diy_fp.e();
    while (significand > kHiddenBit + kSignificandMask) {
      significand >>= 1;
      exponent++;
    }
    if (exponent >= kMaxExponent) {
      return kInfinity;
    }
    if (exponent < kDenormalExponent) {
      return 0;
    }
    while (exponent > kDenormalExponent && (significand & kHiddenBit) == 0) {
      significand <<= 1;
      exponent--;
    }
    uint64_t biased_exponent;
    if (exponent == kDenormalExponent && (significand & kHiddenBit) == 0) {
      biased_exponent = 0;
    } else {
      biased_exponent = static_cast<uint64_t>(exponent + kExponentBias);
    }
    return (significand & kSignificandMask) |
           (biased_exponent << kPhysicalSignificandSize);
  }
References v8::base::DiyFp::e(), v8::base::DiyFp::f(), kDenormalExponent, kExponentBias, kHiddenBit, kInfinity, kMaxExponent, kPhysicalSignificandSize, and kSignificandMask.
Exponent()
constexpr int v8::base::Double::Exponent () const [inline], [constexpr]
Definition at line 82 of file double.h.
                                 {
    if (IsDenormal()) return kDenormalExponent;
    uint64_t d64 = AsUint64();
    int biased_e =
        static_cast<int>((d64 & kExponentMask) >> kPhysicalSignificandSize);
    return biased_e - kExponentBias;
  }
References AsUint64(), IsDenormal(), kDenormalExponent, kExponentBias, kExponentMask, and kPhysicalSignificandSize.
Referenced by AsDiyFp(), AsNormalizedDiyFp(), v8::base::BignumDtoa(), v8::internal::DoubleToInt32(), v8::internal::DoubleToWebIDLInt64(), v8::base::FastFixedDtoa(), v8::base::InitialScaledStartValuesNegativeExponentNegativePower(), v8::base::InitialScaledStartValuesNegativeExponentPositivePower(), and UpperBoundary().
IsDenormal()
constexpr bool v8::base::Double::IsDenormal () const [inline], [constexpr]
Definition at line 102 of file double.h.
                                    {
    uint64_t d64 = AsUint64();
    return (d64 & kExponentMask) == 0;
  }
References AsUint64(), and kExponentMask.
Referenced by Exponent(), and Significand().
IsInfinite()
constexpr bool v8::base::Double::IsInfinite () const [inline], [constexpr]
Definition at line 114 of file double.h.
                                    {
    uint64_t d64 = AsUint64();
    return ((d64 & kExponentMask) == kExponentMask) &&
           ((d64 & kSignificandMask) == 0);
  }
References AsUint64(), kExponentMask, and kSignificandMask.
Referenced by v8::internal::compiler::FloatMatcher< T, kOpcode >::IsPositiveOrNegativePowerOf2().
IsSpecial()
constexpr bool v8::base::Double::IsSpecial () const [inline], [constexpr]
Definition at line 109 of file double.h.
                                   {
    uint64_t d64 = AsUint64();
    return (d64 & kExponentMask) == kExponentMask;
  }
References AsUint64(), and kExponentMask.
Referenced by AsDiyFp().
NextDouble()
constexpr double v8::base::Double::NextDouble () const [inline], [constexpr]
Definition at line 69 of file double.h.
                                      {
    if (d64_ == kInfinity) return Double(kInfinity).value();
    if (Sign() < 0 && Significand() == 0) {
      // -0.0
      return 0.0;
    }
    if (Sign() < 0) {
      return Double(d64_ - 1).value();
    } else {
      return Double(d64_ + 1).value();
    }
  }
References d64_, Double(), kInfinity, Sign(), and Significand().
Referenced by v8::base::BignumStrtod(), and v8::internal::DoubleToRadixStringView().
NormalizedBoundaries()
void v8::base::Double::NormalizedBoundaries (DiyFp * out_m_minus, DiyFp * out_m_plus) const [inline]
Definition at line 136 of file double.h.
                                                                         {
    DCHECK_GT(value(), 0.0);
    DiyFp v = this->AsDiyFp();
    DiyFp m_plus = DiyFp::Normalize(DiyFp((v.f() << 1) + 1, v.e() - 1));
    DiyFp m_minus;
    if ((AsUint64() & kSignificandMask) == 0 && v.e() != kDenormalExponent) {
      // The boundary is closer. Think of v = 1000e10 and v- = 9999e9.
      // Then the boundary (== (v - v-)/2) is not just at a distance of 1e9 but
      // at a distance of 1e8.
      // The only exception is for the smallest normal: the largest denormal is
      // at the same distance as its successor.
      // Note: denormals have the same exponent as the smallest normals.
      m_minus = DiyFp((v.f() << 2) - 1, v.e() - 2);
    } else {
      m_minus = DiyFp((v.f() << 1) - 1, v.e() - 1);
    }
    m_minus.set_f(m_minus.f() << (m_minus.e() - m_plus.e()));
    m_minus.set_e(m_plus.e());
    *out_m_plus = m_plus;
    *out_m_minus = m_minus;
  }
References AsDiyFp(), AsUint64(), DCHECK_GT, v8::base::DiyFp::e(), v8::base::DiyFp::f(), kDenormalExponent, kSignificandMask, v8::base::DiyFp::Normalize(), v8::base::DiyFp::set_e(), v8::base::DiyFp::set_f(), and value().
Referenced by v8::base::Grisu3().
Sign()
constexpr int v8::base::Double::Sign () const [inline], [constexpr]
Definition at line 120 of file double.h.
                             {
    uint64_t d64 = AsUint64();
    return (d64 & kSignMask) == 0 ? 1 : -1;
  }
References AsUint64(), and kSignMask.
Referenced by AsDiyFp(), v8::internal::DoubleToInt32(), v8::internal::DoubleToWebIDLInt64(), NextDouble(), v8::internal::compiler::MachineOperatorReducer::Reduce(), and UpperBoundary().
Significand()
constexpr uint64_t v8::base::Double::Significand () const [inline], [constexpr]
Definition at line 91 of file double.h.
                                         {
    uint64_t d64 = AsUint64();
    uint64_t significand = d64 & kSignificandMask;
    if (!IsDenormal()) {
      return significand + kHiddenBit;
    } else {
      return significand;
    }
  }
References AsUint64(), IsDenormal(), kHiddenBit, and kSignificandMask.
Referenced by AsDiyFp(), AsNormalizedDiyFp(), v8::base::BignumDtoa(), v8::internal::DoubleToInt32(), v8::internal::DoubleToWebIDLInt64(), v8::base::FastFixedDtoa(), v8::base::InitialScaledStartValuesNegativeExponentNegativePower(), v8::base::InitialScaledStartValuesNegativeExponentPositivePower(), NextDouble(), and UpperBoundary().
SignificandSizeForOrderOfMagnitude()
static int v8::base::Double::SignificandSizeForOrderOfMagnitude (int order) [inline], [static]
Definition at line 166 of file double.h.
                                                           {
    if (order >= (kDenormalExponent + kSignificandSize)) {
      return kSignificandSize;
    }
    if (order <= kDenormalExponent) return 0;
    return order - kDenormalExponent;
  }
References kDenormalExponent, and kSignificandSize.
Referenced by v8::base::DiyFpStrtod().
UpperBoundary()
DiyFp v8::base::Double::UpperBoundary () const [inline]
Definition at line 127 of file double.h.
                              {
    DCHECK_GT(Sign(), 0);
    return DiyFp(Significand() * 2 + 1, Exponent() - 1);
  }
References DCHECK_GT, Exponent(), Sign(), and Significand().
Referenced by v8::base::BignumStrtod().
value()
constexpr double v8::base::Double::value () const [inline], [constexpr]
Definition at line 158 of file double.h.
{ return uint64_to_double(d64_); }
References d64_, and v8::base::uint64_to_double().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), AsNormalizedDiyFp(), v8::base::DiyFpStrtod(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), NormalizedBoundaries(), v8::internal::compiler::operator<<(), v8::internal::compiler::InstructionOperandConverter::ToDouble(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), and v8::internal::compiler::ArmOperandConverter::ToImmediate().
Member Data Documentation
d64_
uint64_t v8::base::Double::d64_ [private]
Definition at line 182 of file double.h.
Referenced by AsUint64(), NextDouble(), and value().
kDenormalExponent
constexpr int v8::base::Double::kDenormalExponent = -kExponentBias + 1 [static], [constexpr], [private]
Definition at line 176 of file double.h.
Referenced by DiyFpToUint64(), Exponent(), NormalizedBoundaries(), and SignificandSizeForOrderOfMagnitude().
kExponentBias
constexpr int v8::base::Double::kExponentBias = 0x3FF + kPhysicalSignificandSize [static], [constexpr], [private]
Definition at line 175 of file double.h.
Referenced by DiyFpToUint64(), and Exponent().
kExponentMask
constexpr uint64_t v8::base::Double::kExponentMask = 0x7FF0'0000'0000'0000 [static], [constexpr]
Definition at line 28 of file double.h.
Referenced by Exponent(), v8::base::InitialScaledStartValuesNegativeExponentNegativePower(), IsDenormal(), IsInfinite(), and IsSpecial().
kHiddenBit
constexpr uint64_t v8::base::Double::kHiddenBit = 0x0010'0000'0000'0000 [static], [constexpr]
Definition at line 30 of file double.h.
Referenced by AsNormalizedDiyFp(), v8::internal::BigInt::CompareToDouble(), DiyFpToUint64(), v8::internal::MutableBigInt::NewFromDouble(), v8::base::NormalizedExponent(), and Significand().
kInfinity
constexpr uint64_t v8::base::Double::kInfinity = 0x7FF0'0000'0000'0000 [static], [constexpr], [private]
Definition at line 178 of file double.h.
Referenced by DiyFpToUint64(), and NextDouble().
kMaxExponent
constexpr int v8::base::Double::kMaxExponent = 0x7FF - kExponentBias [static], [constexpr], [private]
Definition at line 177 of file double.h.
Referenced by DiyFpToUint64().
kPhysicalSignificandSize
constexpr int v8::base::Double::kPhysicalSignificandSize [static], [constexpr]
Initial value:
=
      52
Definition at line 31 of file double.h.
Referenced by v8::internal::BigInt::CompareToDouble(), DiyFpToUint64(), Exponent(), v8::internal::MutableBigInt::NewFromDouble(), and v8::internal::MutableBigInt::ToDouble().
kSignificandMask
constexpr uint64_t v8::base::Double::kSignificandMask = 0x000F'FFFF'FFFF'FFFF [static], [constexpr]
Definition at line 29 of file double.h.
Referenced by v8::internal::BigInt::CompareToDouble(), DiyFpToUint64(), v8::base::InitialScaledStartValuesNegativeExponentNegativePower(), v8::base::InitialScaledStartValuesNegativeExponentPositivePower(), v8::base::InitialScaledStartValuesPositiveExponent(), IsInfinite(), v8::internal::MutableBigInt::NewFromDouble(), NormalizedBoundaries(), and Significand().
kSignificandSize
constexpr int v8::base::Double::kSignificandSize = 53 [static], [constexpr]
Definition at line 33 of file double.h.
Referenced by AsNormalizedDiyFp(), v8::internal::DoubleToInt32(), v8::internal::DoubleToWebIDLInt64(), v8::internal::MutableBigInt::NewFromDouble(), and SignificandSizeForOrderOfMagnitude().
kSignMask
constexpr uint64_t v8::base::Double::kSignMask = 0x8000'0000'0000'0000 [static], [constexpr]
Definition at line 27 of file double.h.
Referenced by Sign(), and v8::internal::SignedZero().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/numbers/double.h