v8::internal::maglev::MaglevGraphVerifier Class Reference
#include <maglev-graph-verifier.h>
Public Member Functions
MaglevGraphVerifier (MaglevCompilationInfo *compilation_info)
void PreProcessGraph (Graph *graph)
void PostProcessGraph (Graph *graph)
void PostProcessBasicBlock (BasicBlock *block)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
ProcessResult Process (Dead *node, const ProcessingState &state)
template<typename NodeT >
ProcessResult Process (NodeT *node, const ProcessingState &state)
Private Attributes
MaglevGraphLabeller * graph_labeller_ = nullptr
std::vector< bool > seen_
Detailed Description
Definition at line 20 of file maglev-graph-verifier.h.
Constructor & Destructor Documentation
MaglevGraphVerifier()
v8::internal::maglev::MaglevGraphVerifier::MaglevGraphVerifier (MaglevCompilationInfo * compilation_info) [inline], [explicit]
Definition at line 22 of file maglev-graph-verifier.h.
                                                                        {
    if (compilation_info->has_graph_labeller()) {
      graph_labeller_ = compilation_info->graph_labeller();
    }
  }
References v8::internal::maglev::MaglevCompilationInfo::graph_labeller(), graph_labeller_, and v8::internal::maglev::MaglevCompilationInfo::has_graph_labeller().
Member Function Documentation
PostPhiProcessing()
void v8::internal::maglev::MaglevGraphVerifier::PostPhiProcessing () [inline]
Definition at line 37 of file maglev-graph-verifier.h.
{}
PostProcessBasicBlock()
void v8::internal::maglev::MaglevGraphVerifier::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 30 of file maglev-graph-verifier.h.
{}
PostProcessGraph()
void v8::internal::maglev::MaglevGraphVerifier::PostProcessGraph (Graph * graph) [inline]
Definition at line 29 of file maglev-graph-verifier.h.
{}
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::MaglevGraphVerifier::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 31 of file maglev-graph-verifier.h.
                                                             {
    // Check Ids are unique.
    CHECK(!seen_[block->id()]);
    seen_[block->id()] = true;
    return BlockProcessResult::kContinue;
  }
References CHECK, v8::internal::maglev::BasicBlock::id(), v8::internal::maglev::kContinue, and seen_.
PreProcessGraph()
void v8::internal::maglev::MaglevGraphVerifier::PreProcessGraph (Graph * graph) [inline]
Definition at line 28 of file maglev-graph-verifier.h.
{ seen_.resize(graph->max_block_id()); }
References graph(), and seen_.
Process() [1/2]
ProcessResult v8::internal::maglev::MaglevGraphVerifier::Process (Dead * node, const ProcessingState & state) [inline]
Definition at line 39 of file maglev-graph-verifier.h.
                                                                  {
    node->VerifyInputs(graph_labeller_);
    return ProcessResult::kContinue;
  }
References graph_labeller_, v8::internal::maglev::kContinue, and v8::internal::maglev::Dead::VerifyInputs().
Process() [2/2]
template<typename NodeT >
ProcessResult v8::internal::maglev::MaglevGraphVerifier::Process (NodeT * node, const ProcessingState & state) [inline]
Definition at line 45 of file maglev-graph-verifier.h.
                                                                   {
    for (Input& input : *node) {
      Opcode op = input.node()->opcode();
      CHECK_GE(op, kFirstOpcode);
      CHECK_LE(op, kLastOpcode);
    }
    node->VerifyInputs(graph_labeller_);
    return ProcessResult::kContinue;
  }
References CHECK_GE, CHECK_LE, graph_labeller_, v8::internal::maglev::kContinue, v8::internal::maglev::kFirstOpcode, and v8::internal::maglev::kLastOpcode.
Member Data Documentation
graph_labeller_
MaglevGraphLabeller* v8::internal::maglev::MaglevGraphVerifier::graph_labeller_ = nullptr [private]
Definition at line 56 of file maglev-graph-verifier.h.
Referenced by MaglevGraphVerifier(), and Process().
seen_
std::vector<bool> v8::internal::maglev::MaglevGraphVerifier::seen_ [private]
Definition at line 57 of file maglev-graph-verifier.h.
Referenced by PreProcessBasicBlock(), and PreProcessGraph().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-verifier.h