v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes > Class Template Reference
#include <assert-scope.h>
Public Member Functions
PerThreadAssertScopeEmpty ()
void Release ()
Detailed Description
template<bool kAllow, PerThreadAssertType... kTypes>
class v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes >
Definition at line 50 of file assert-scope.h.
Constructor & Destructor Documentation
PerThreadAssertScopeEmpty()
template<bool kAllow, PerThreadAssertType... kTypes>
v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes >::PerThreadAssertScopeEmpty () [inline]
Definition at line 54 of file assert-scope.h.
{}
Member Function Documentation
Release()
template<bool kAllow, PerThreadAssertType... kTypes>
void v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes >::Release () [inline]
Definition at line 55 of file assert-scope.h.
{}
Referenced by v8::internal::Deserializer< IsolateT >::PostProcessNewObject(), v8::internal::Isolate::ReportFailedAccessCheck(), v8::internal::SourcePositionTableIterator::SourcePositionTableIterator(), and v8::internal::Deoptimizer::TraceMarkForDeoptimization().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/common/assert-scope.h