v8::internal::RegExpQuantifier Class Reference
#include <regexp-ast.h>
Public Types
enum QuantifierType { GREEDY
, NON_GREEDY
, POSSESSIVE
 }
Public Member Functions
RegExpQuantifier (int min, int max, QuantifierType type, int index, RegExpTree *body)
DECL_BOILERPLATE (Quantifier)
Interval CaptureRegisters () override
int min_match () override
int max_match () override
int min () const
int max () const
QuantifierType quantifier_type () const
int index () const
bool is_possessive () const
bool is_non_greedy () const
bool is_greedy () const
RegExpTree * body () const
Static Public Member Functions
static RegExpNode * ToNode (int min, int max, bool is_greedy, RegExpTree *body, RegExpCompiler *compiler, RegExpNode *on_success, bool not_at_start=false)
Private Attributes
RegExpTree * body_
int min_
int max_
int min_match_
int max_match_
QuantifierType quantifier_type_
int index_
Additional Inherited Members
Detailed Description
Definition at line 548 of file regexp-ast.h.
Member Enumeration Documentation
QuantifierType
enum v8::internal::RegExpQuantifier::QuantifierType
Enumerator
GREEDY
NON_GREEDY
POSSESSIVE
Definition at line 550 of file regexp-ast.h.
{ GREEDY, NON_GREEDY, POSSESSIVE };
Constructor & Destructor Documentation
RegExpQuantifier()
v8::internal::RegExpQuantifier::RegExpQuantifier (int min, int max, QuantifierType type, int index, RegExpTree * body) [inline]
Definition at line 551 of file regexp-ast.h.
      : body_(body),
        min_(min),
        max_(max),
        quantifier_type_(type),
        index_(index) {
    if (min > 0 && body->min_match() > kInfinity / min) {
      min_match_ = kInfinity;
    } else {
      min_match_ = min * body->min_match();
    }
    if (max > 0 && body->max_match() > kInfinity / max) {
      max_match_ = kInfinity;
    } else {
      max_match_ = max * body->max_match();
    }
  }
References body(), v8::internal::RegExpTree::kInfinity, max(), v8::internal::RegExpTree::max_match(), max_match_, min(), v8::internal::RegExpTree::min_match(), and min_match_.
Member Function Documentation
body()
RegExpTree* v8::internal::RegExpQuantifier::body () const [inline]
Definition at line 585 of file regexp-ast.h.
{ return body_; }
References body_.
Referenced by CaptureRegisters(), RegExpQuantifier(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitQuantifier(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
CaptureRegisters()
Interval v8::internal::RegExpQuantifier::CaptureRegisters () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 64 of file regexp-ast.cc.
                                            {
  return body()->CaptureRegisters();
}
References body(), and v8::internal::RegExpTree::CaptureRegisters().
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
DECL_BOILERPLATE()
v8::internal::RegExpQuantifier::DECL_BOILERPLATE (Quantifier)
index()
int v8::internal::RegExpQuantifier::index () const [inline]
Definition at line 581 of file regexp-ast.h.
{ return index_; }
References index_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
is_greedy()
bool v8::internal::RegExpQuantifier::is_greedy () const [inline]
Definition at line 584 of file regexp-ast.h.
{ return quantifier_type_ == GREEDY; }
References GREEDY, and quantifier_type_.
is_non_greedy()
bool v8::internal::RegExpQuantifier::is_non_greedy () const [inline]
Definition at line 583 of file regexp-ast.h.
{ return quantifier_type_ == NON_GREEDY; }
References NON_GREEDY, and quantifier_type_.
is_possessive()
bool v8::internal::RegExpQuantifier::is_possessive () const [inline]
Definition at line 582 of file regexp-ast.h.
{ return quantifier_type_ == POSSESSIVE; }
References POSSESSIVE, and quantifier_type_.
max()
int v8::internal::RegExpQuantifier::max () const [inline]
Definition at line 579 of file regexp-ast.h.
{ return max_; }
References max_.
Referenced by RegExpQuantifier(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
max_match()
int v8::internal::RegExpQuantifier::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 577 of file regexp-ast.h.
{ return max_match_; }
References max_match_.
min()
int v8::internal::RegExpQuantifier::min () const [inline]
Definition at line 578 of file regexp-ast.h.
{ return min_; }
References min_.
Referenced by RegExpQuantifier(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
min_match()
int v8::internal::RegExpQuantifier::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 576 of file regexp-ast.h.
{ return min_match_; }
References min_match_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
quantifier_type()
QuantifierType v8::internal::RegExpQuantifier::quantifier_type () const [inline]
Definition at line 580 of file regexp-ast.h.
{ return quantifier_type_; }
References quantifier_type_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
ToNode()
RegExpNode * v8::internal::RegExpQuantifier::ToNode (int min, int max, bool is_greedy, RegExpTree * body, RegExpCompiler * compiler, RegExpNode * on_success, bool not_at_start = false) [static]
Definition at line 1053 of file regexp-compiler-tonode.cc.
                                                             {
  return ToNode(min(), max(), is_greedy(), body(), compiler, on_success);
}
Referenced by v8::internal::RegExpCompiler::PreprocessRegExp().
Member Data Documentation
body_
RegExpTree* v8::internal::RegExpQuantifier::body_ [private]
Definition at line 588 of file regexp-ast.h.
Referenced by body().
index_
int v8::internal::RegExpQuantifier::index_ [private]
Definition at line 594 of file regexp-ast.h.
Referenced by index().
max_
int v8::internal::RegExpQuantifier::max_ [private]
Definition at line 590 of file regexp-ast.h.
Referenced by max().
max_match_
int v8::internal::RegExpQuantifier::max_match_ [private]
Definition at line 592 of file regexp-ast.h.
Referenced by max_match(), and RegExpQuantifier().
min_
int v8::internal::RegExpQuantifier::min_ [private]
Definition at line 589 of file regexp-ast.h.
Referenced by min().
min_match_
int v8::internal::RegExpQuantifier::min_match_ [private]
Definition at line 591 of file regexp-ast.h.
Referenced by min_match(), and RegExpQuantifier().
quantifier_type_
QuantifierType v8::internal::RegExpQuantifier::quantifier_type_ [private]
Definition at line 593 of file regexp-ast.h.
Referenced by is_greedy(), is_non_greedy(), is_possessive(), and quantifier_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc