v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next > Class Template Reference
#include <block-instrumentation-reducer.h>
Public Types
using Adapter = UniformReducerAdapter< BlockInstrumentationReducer, Next >
Public Member Functions
BlockInstrumentationReducer ()
void Bind (Block *new_block)
template<Opcode opcode, typename Continuation , typename... Args>
OpIndex ReduceOperation (Args... args)
V< Object > REDUCE() Parameter (int32_t parameter_index, RegisterRepresentation rep, const char *debug_name)
V< Any > REDUCE() CatchBlockBegin ()
V< Any > REDUCE() DidntThrow (V< Any > throwing_operation, bool has_catch_block, const base::Vector< const RegisterRepresentation > *results_rep, OpEffects throwing_op_effects)
V< Word32 > LoadCounterValue (int block_number)
void StoreCounterValue (int block_number, V< Word32 > value)
void EmitBlockInstrumentation (int block_number)
V< None > REDUCE_INPUT_GRAPH() Branch (V< None > ig_index, const BranchOp &branch)
Private Attributes
Isolate * isolate_ = __ data() -> isolate()
BasicBlockProfilerData * data_ = __ data() -> info()->profiler_data()
const bool on_heap_counters_
size_t operations_emitted_in_current_block_ = 0
Handle< HeapObject > counters_array_handle_
Detailed Description
template<typename Next>
class v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >
Definition at line 23 of file block-instrumentation-reducer.h.
Member Typedef Documentation
Adapter
template<typename Next >
using v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Adapter = UniformReducerAdapter<BlockInstrumentationReducer, Next>
Definition at line 27 of file block-instrumentation-reducer.h.
Constructor & Destructor Documentation
BlockInstrumentationReducer()
template<typename Next >
v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::BlockInstrumentationReducer () [inline]
Definition at line 29 of file block-instrumentation-reducer.h.
                                {
    DCHECK_NOT_NULL(data_);
    if (on_heap_counters_) {
      counters_array_handle_ = detail::CreateCountersArray(isolate_);
    }
  }
References v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::counters_array_handle_, v8::internal::compiler::turboshaft::detail::CreateCountersArray(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::data_, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::isolate_, and v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::on_heap_counters_.
Member Function Documentation
Bind()
template<typename Next >
void v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Bind (Block * new_block) [inline]
Definition at line 36 of file block-instrumentation-reducer.h.
                              {
    Next::Bind(new_block);
    const int block_number = new_block->index().id();
    data_->SetBlockId(block_number, block_number);
    // Reset counter.
    operations_emitted_in_current_block_ = 0;
  }
References v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::data_, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::operations_emitted_in_current_block_, and v8::internal::BasicBlockProfilerData::SetBlockId().
Branch()
template<typename Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Branch (V< None > ig_index, const BranchOp & branch) [inline]
Definition at line 154 of file block-instrumentation-reducer.h.
                                                                               {
    const int true_id = branch.if_true->index().id();
    const int false_id = branch.if_false->index().id();
    data_->AddBranch(true_id, false_id);
    return Next::ReduceInputGraphBranch(ig_index, branch);
  }
References v8::internal::BasicBlockProfilerData::AddBranch(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::data_, and v8::internal::compiler::turboshaft::OpIndex::id().
CatchBlockBegin()
template<typename Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::CatchBlockBegin () [inline]
Definition at line 71 of file block-instrumentation-reducer.h.
                                   {
    // Skip generic callback as we don't want to emit instrumentation BEFORE
    // this operation.
    return Next::ReduceCatchBlockBegin();
  }
DidntThrow()
template<typename Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::DidntThrow (V< Any > throwing_operation, bool has_catch_block, const base::Vector< const RegisterRepresentation > * results_rep, OpEffects throwing_op_effects) [inline]
Definition at line 77 of file block-instrumentation-reducer.h.
                                     {
    // Skip generic callback as we don't want to emit instrumentation BEFORE
    // this operation.
    return Next::ReduceDidntThrow(throwing_operation, has_catch_block,
                                  results_rep, throwing_op_effects);
  }
EmitBlockInstrumentation()
template<typename Next >
void v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::EmitBlockInstrumentation (int block_number) [inline]
Definition at line 136 of file block-instrumentation-reducer.h.
                                                  {
    // Load the current counter value from the array.
    V<Word32> value = LoadCounterValue(block_number);
    // Increment the counter value.
    V<Word32> incremented_value = __ Word32Add(value, 1);
    // Branchless saturation, because we don't want to introduce additional
    // control flow here.
    V<Word32> overflow = __ Uint32LessThan(incremented_value, value);
    V<Word32> overflow_mask = __ Word32Sub(0, overflow);
    V<Word32> saturated_value =
        __ Word32BitwiseOr(incremented_value, overflow_mask);
    // Store the incremented counter value back into the array.
    StoreCounterValue(block_number, saturated_value);
  }
References __, v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue(), v8::internal::overflow, v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::ReduceOperation().
LoadCounterValue()
template<typename Next >
V<Word32> v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue (int block_number) [inline]
Definition at line 87 of file block-instrumentation-reducer.h.
                                               {
    int offset_to_counter_value = block_number * kInt32Size;
    if (on_heap_counters_) {
      offset_to_counter_value += sizeof(ByteArray::Header);
      // Allocation is disallowed here, so rather than referring to an actual
      // counters array, create a reference to a special marker object. This
      // object will get fixed up later in the constants table (see
      // PatchBasicBlockCountersReference). An important and subtle point: we
      // cannot use the root handle basic_block_counters_marker_handle() and
      // must create a new separate handle. Otherwise
      // MacroAssemblerBase::IndirectLoadConstant would helpfully emit a
      // root-relative load rather than putting this value in the constants
      // table where we expect it to be for patching.
      V<HeapObject> counter_array = __ HeapConstant(counters_array_handle_);
      return __ Load(counter_array, LoadOp::Kind::TaggedBase(),
                     MemoryRepresentation::Uint32(), offset_to_counter_value);
    } else {
      V<WordPtr> counter_array =
          __ WordPtrConstant(reinterpret_cast<uintptr_t>(data_->counts()));
      return __ LoadOffHeap(counter_array, offset_to_counter_value,
                            MemoryRepresentation::Uint32());
    }
  }
References __, v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::counters_array_handle_, v8::internal::BasicBlockProfilerData::counts(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::data_, v8::internal::kInt32Size, v8::Load(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::on_heap_counters_, v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32().
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::EmitBlockInstrumentation().
Parameter()
template<typename Next >
V<Object> REDUCE() v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Parameter (int32_t parameter_index, RegisterRepresentation rep, const char * debug_name) [inline]
Definition at line 63 of file block-instrumentation-reducer.h.
                                                      {
    // Skip generic callback as we don't want to emit instrumentation BEFORE
    // this operation.
    return Next::ReduceParameter(parameter_index, rep, debug_name);
  }
ReduceOperation()
template<typename Next >
template<Opcode opcode, typename Continuation , typename... Args>
OpIndex v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::ReduceOperation (Args... args) [inline]
Definition at line 47 of file block-instrumentation-reducer.h.
                                        {
    // Those operations must be skipped here because we want to keep them at the
    // beginning of their blocks.
    static_assert(opcode != Opcode::kCatchBlockBegin);
    static_assert(opcode != Opcode::kDidntThrow);
    static_assert(opcode != Opcode::kParameter);
    if (0 == operations_emitted_in_current_block_++) {
      // If this is the first (non-skipped) operation in this block, emit
      // instrumentation.
      const int block_number = __ current_block() -> index().id();
      EmitBlockInstrumentation(block_number);
    }
    return Continuation{this}.Reduce(args...);
  }
References __, v8::base::args, v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::EmitBlockInstrumentation(), v8::internal::index, and v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::operations_emitted_in_current_block_.
StoreCounterValue()
template<typename Next >
void v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue (int block_number, V< Word32 > value) [inline]
Definition at line 111 of file block-instrumentation-reducer.h.
                                                            {
    int offset_to_counter_value = block_number * kInt32Size;
    if (on_heap_counters_) {
      offset_to_counter_value += sizeof(ByteArray::Header);
      // Allocation is disallowed here, so rather than referring to an actual
      // counters array, create a reference to a special marker object. This
      // object will get fixed up later in the constants table (see
      // PatchBasicBlockCountersReference). An important and subtle point: we
      // cannot use the root handle basic_block_counters_marker_handle() and
      // must create a new separate handle. Otherwise
      // MacroAssemblerBase::IndirectLoadConstant would helpfully emit a
      // root-relative load rather than putting this value in the constants
      // table where we expect it to be for patching.
      V<HeapObject> counter_array = __ HeapConstant(counters_array_handle_);
      __ Store(counter_array, value, StoreOp::Kind::TaggedBase(),
               MemoryRepresentation::Uint32(),
               WriteBarrierKind::kNoWriteBarrier, offset_to_counter_value);
    } else {
      V<WordPtr> counter_array =
          __ WordPtrConstant(reinterpret_cast<uintptr_t>(data_->counts()));
      __ StoreOffHeap(counter_array, value, MemoryRepresentation::Uint32(),
                      offset_to_counter_value);
    }
  }
References __, v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::counters_array_handle_, v8::internal::BasicBlockProfilerData::counts(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::data_, v8::internal::kInt32Size, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::on_heap_counters_, v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::EmitBlockInstrumentation().
Member Data Documentation
counters_array_handle_
template<typename Next >
Handle<HeapObject> v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::counters_array_handle_ [private]
Definition at line 167 of file block-instrumentation-reducer.h.
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::BlockInstrumentationReducer(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue(), and v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue().
data_
template<typename Next >
BasicBlockProfilerData* v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::data_ = __ data() -> info()->profiler_data() [private]
Definition at line 163 of file block-instrumentation-reducer.h.
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Bind(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::BlockInstrumentationReducer(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue(), and v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue().
isolate_
template<typename Next >
Isolate* v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::isolate_ = __ data() -> isolate() [private]
Definition at line 162 of file block-instrumentation-reducer.h.
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::BlockInstrumentationReducer().
on_heap_counters_
template<typename Next >
const bool v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::on_heap_counters_ [private]
Initial value:
=
      isolate_ && isolate_->IsGeneratingEmbeddedBuiltins()
Definition at line 164 of file block-instrumentation-reducer.h.
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::BlockInstrumentationReducer(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue(), and v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue().
operations_emitted_in_current_block_
template<typename Next >
size_t v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::operations_emitted_in_current_block_ = 0 [private]
Definition at line 166 of file block-instrumentation-reducer.h.
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Bind(), and v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::ReduceOperation().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/block-instrumentation-reducer.h