v8::Function Class Reference
A JavaScript function object (ECMA-262, 15.3).
#include <v8-function.h>
Public Member Functions
V8_WARN_UNUSED_RESULT MaybeLocal< Object > NewInstance (Local< Context > context, int argc, Local< Value > argv[]) const
V8_WARN_UNUSED_RESULT MaybeLocal< Object > NewInstance (Local< Context > context) const
V8_WARN_UNUSED_RESULT MaybeLocal< Object > NewInstanceWithSideEffectType (Local< Context > context, int argc, Local< Value > argv[], SideEffectType side_effect_type=SideEffectType::kHasSideEffect) const
When side effect checks are enabled, passing kHasNoSideEffect allows the constructor to be invoked without throwing.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Call (v8::Isolate *isolate, Local< Context > context, Local< Value > recv, int argc, Local< Value > argv[])
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Call (Local< Context > context, Local< Value > recv, int argc, Local< Value > argv[])
void SetName (Local< String > name)
Local< Value > GetName () const
Local< Value > GetInferredName () const
Name inferred from variable or property assignment of this function.
Local< Value > GetDebugName () const
displayName if it is set, otherwise name if it is configured, otherwise function name, otherwise inferred name.
int GetScriptLineNumber () const
Returns zero based line number of function body and kLineOffsetNotFound if no information available.
int GetScriptColumnNumber () const
Returns zero based column number of function body and kLineOffsetNotFound if no information available.
Location GetScriptLocation () const
Returns zero based line and column number of function body, else returns {-1, -1}.
int GetScriptStartPosition () const
Returns zero based start position (character offset) of function body and kLineOffsetNotFound if no information available.
int ScriptId () const
Returns scriptId.
Local< Value > GetBoundFunction () const
Returns the original function if this function is bound, else returns v8::Undefined.
V8_WARN_UNUSED_RESULT MaybeLocal< String > FunctionProtoToString (Local< Context > context)
Calls builtin Function.prototype.toString on this function.
V8_WARN_UNUSED_RESULT bool Experimental_IsNopFunction () const
Returns true if the function does nothing.
ScriptOrigin GetScriptOrigin () const
Static Public Member Functions
static MaybeLocal< Function > New (Local< Context > context, FunctionCallback callback, Local< Value > data=Local< Value >(), int length=0, ConstructorBehavior behavior=ConstructorBehavior::kAllow, SideEffectType side_effect_type=SideEffectType::kHasSideEffect)
Create a function in the current execution context for a given FunctionCallback.
static Function * Cast (Value *value)
Static Public Attributes
static const int kLineOffsetNotFound = -1
Private Member Functions
Function ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
A JavaScript function object (ECMA-262, 15.3).
Definition at line 27 of file v8-function.h.
Constructor & Destructor Documentation
Function()
v8::Function::Function () [private]
Member Function Documentation
Call() [1/2]
MaybeLocal< v8::Value > v8::Function::Call (Local< Context > context, Local< Value > recv, int argc, Local< Value > argv[])
Definition at line 5367 of file api.cc.
                                                              {
  return Call(v8::Isolate::GetCurrent(), context, recv, argc, argv);
}
References Call(), and v8::Isolate::GetCurrent().
Call() [2/2]
MaybeLocal< v8::Value > v8::Function::Call (v8::Isolate * isolate, Local< Context > context, Local< Value > recv, int argc, Local< Value > argv[])
Definition at line 5347 of file api.cc.
                                                              {
  auto i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.Execute");
  EnterV8Scope<InternalEscapableScope> api_scope{i_isolate, context,
                                                 RCCId::kAPI_Function_Call};
  i::TimerEventScope<i::TimerEventExecute> timer_scope(i_isolate);
  i::NestedTimedHistogramScope execute_timer(i_isolate->counters()->execute(),
                                             i_isolate);
  auto self = Utils::OpenDirectHandle(this);
  Utils::ApiCheck(!self.is_null(), "v8::Function::Call",
                  "Function to be called is a null pointer");
  auto recv_obj = Utils::OpenDirectHandle(*recv);
  auto args = PrepareArguments(argc, argv);
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Execution::Call(i_isolate, self, recv_obj, args)));
}
References v8::Utils::ApiCheck(), v8::base::args, v8::internal::Execution::Call(), v8::internal::Isolate::counters(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::PrepareArguments(), v8::Utils::ToMaybeLocal(), and TRACE_EVENT_CALL_STATS_SCOPED.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), Call(), v8_inspector::V8Regex::match(), v8::InspectorClient::runMessageLoopOnPause(), and v8::InspectorFrontend::Send().
Cast()
static Function* v8::Function::Cast (Value * value) [inline], [static]
Definition at line 133 of file v8-function.h.
                                                {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<Function*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::Function::CheckCast (Value * obj) [static], [private]
Definition at line 3869 of file api.cc.
                                      {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsCallable(*obj), "v8::Function::Cast",
                  "Value is not a Function");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Experimental_IsNopFunction()
bool v8::Function::Experimental_IsNopFunction () const
Returns true if the function does nothing.
The function returns false on error. Note that this function is experimental. Embedders should not rely on this existing. We may remove this function in the future.
Definition at line 5517 of file api.cc.
                                                {
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSFunction(*self)) return false;
  auto sfi = i::Cast<i::JSFunction>(*self)->shared();
  i::Isolate* i_isolate = i::Isolate::Current();
  i::IsCompiledScope is_compiled_scope(sfi->is_compiled_scope(i_isolate));
  if (!is_compiled_scope.is_compiled() &&
      !i::Compiler::Compile(i_isolate, i::handle(sfi, i_isolate),
                            i::Compiler::CLEAR_EXCEPTION, &is_compiled_scope)) {
    return false;
  }
  DCHECK(is_compiled_scope.is_compiled());
  // Since |sfi| can be GC'ed, we get it again.
  sfi = i::Cast<i::JSFunction>(*self)->shared();
  if (!sfi->HasBytecodeArray()) return false;
  i::Handle<i::BytecodeArray> bytecode_array(sfi->GetBytecodeArray(i_isolate),
                                             i_isolate);
  i::interpreter::BytecodeArrayIterator it(bytecode_array, 0);
  if (it.current_bytecode() != i::interpreter::Bytecode::kLdaUndefined) {
    return false;
  }
  it.Advance();
  DCHECK(!it.done());
  if (it.current_bytecode() != i::interpreter::Bytecode::kReturn) return false;
  it.Advance();
  DCHECK(it.done());
  return true;
}
References v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), v8::internal::Isolate::Current(), DCHECK, v8::internal::handle(), v8::internal::IsCompiledScope::is_compiled(), and v8::Utils::OpenDirectHandle().
FunctionProtoToString()
MaybeLocal< String > v8::Function::FunctionProtoToString (Local< Context > context)
Calls builtin Function.prototype.toString on this function.
This is different from Value::ToString() that may call a user-defined toString() function, and different than Object::ObjectProtoToString() which always serializes `[object Function]`.
Definition at line 5546 of file api.cc.
                                                                           {
  PrepareForExecutionScope api_scope{
      context, RCCId::kAPI_Function_FunctionProtoToString};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  return api_scope.EscapeMaybe(i::Cast<i::String>(i::Execution::CallBuiltin(
      i_isolate, i_isolate->function_to_string(), self, {})));
}
References v8::internal::Execution::CallBuiltin(), and v8::Utils::OpenDirectHandle().
GetBoundFunction()
Local< v8::Value > v8::Function::GetBoundFunction () const
Returns the original function if this function is bound, else returns v8::Undefined.
Definition at line 5506 of file api.cc.
                                                {
  auto self = Utils::OpenDirectHandle(this);
  if (i::IsJSBoundFunction(*self)) {
    auto bound_function = i::Cast<i::JSBoundFunction>(self);
    auto bound_target_function = i::direct_handle(
        bound_function->bound_target_function(), i::Isolate::Current());
    return Utils::CallableToLocal(bound_target_function);
  }
  return v8::Undefined(reinterpret_cast<v8::Isolate*>(i::Isolate::Current()));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::Utils::OpenDirectHandle(), and v8::Undefined().
GetDebugName()
Local< Value > v8::Function::GetDebugName () const
displayName if it is set, otherwise name if it is configured, otherwise function name, otherwise inferred name.
Definition at line 5411 of file api.cc.
                                          {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  if (!IsJSFunction(*self)) {
    return ToApiHandle<Primitive>(i_isolate->factory()->undefined_value());
  }
  auto func = i::Cast<i::JSFunction>(self);
  i::DirectHandle<i::String> name =
      i::JSFunction::GetDebugName(i_isolate, func);
  return Utils::ToLocal(i::direct_handle(*name, i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSFunction::GetDebugName(), name, and v8::Utils::OpenDirectHandle().
GetInferredName()
Local< Value > v8::Function::GetInferredName () const
Name inferred from variable or property assignment of this function.
Used to facilitate debugging and profiling of JavaScript code written in an OO style, where many functions are anonymous but are assigned to object properties.
Definition at line 5400 of file api.cc.
                                             {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  if (!IsJSFunction(*self)) {
    return ToApiHandle<Primitive>(isolate->factory()->undefined_value());
  }
  auto func = i::Cast<i::JSFunction>(self);
  return Utils::ToLocal(
      i::direct_handle(func->shared()->inferred_name(), isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), and v8::Utils::OpenDirectHandle().
GetName()
Local< Value > v8::Function::GetName () const
Definition at line 5382 of file api.cc.
                                     {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  if (i::IsJSBoundFunction(*self)) {
    auto func = i::Cast<i::JSBoundFunction>(self);
    i::DirectHandle<i::Object> name;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        i_isolate, name, i::JSBoundFunction::GetName(i_isolate, func),
        Local<Value>());
    return Utils::ToLocal(name);
  }
  if (i::IsJSFunction(*self)) {
    auto func = i::Cast<i::JSFunction>(self);
    return Utils::ToLocal(i::direct_handle(func->shared()->Name(), i_isolate));
  }
  return ToApiHandle<Primitive>(i_isolate->factory()->undefined_value());
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSBoundFunction::GetName(), name, and v8::Utils::OpenDirectHandle().
GetScriptColumnNumber()
int v8::Function::GetScriptColumnNumber () const
Returns zero based column number of function body and kLineOffsetNotFound if no information available.
Definition at line 5453 of file api.cc.
                                          {
  auto self = *Utils::OpenDirectHandle(this);
  if (!IsJSFunction(self)) {
    return kLineOffsetNotFound;
  }
  auto func = i::Cast<i::JSFunction>(self);
  auto shared = func->shared();
  if (i::IsScript(shared->script())) {
    i::DirectHandle<i::Script> script(i::Cast<i::Script>(shared->script()),
                                      i::Isolate::Current());
    return i::Script::GetColumnNumber(script, shared->StartPosition());
  }
  return kLineOffsetNotFound;
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetColumnNumber(), kLineOffsetNotFound, v8::Utils::OpenDirectHandle(), and v8::internal::script.
GetScriptLineNumber()
int v8::Function::GetScriptLineNumber () const
Returns zero based line number of function body and kLineOffsetNotFound if no information available.
Definition at line 5438 of file api.cc.
                                        {
  auto self = *Utils::OpenDirectHandle(this);
  if (!IsJSFunction(self)) {
    return kLineOffsetNotFound;
  }
  auto func = i::Cast<i::JSFunction>(self);
  auto shared = func->shared();
  if (i::IsScript(shared->script())) {
    i::DirectHandle<i::Script> script(i::Cast<i::Script>(shared->script()),
                                      i::Isolate::Current());
    return i::Script::GetLineNumber(script, shared->StartPosition());
  }
  return kLineOffsetNotFound;
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetLineNumber(), kLineOffsetNotFound, v8::Utils::OpenDirectHandle(), and v8::internal::script.
GetScriptLocation()
Location v8::Function::GetScriptLocation () const
Returns zero based line and column number of function body, else returns {-1, -1}.
Definition at line 5468 of file api.cc.
                                           {
  auto self = *Utils::OpenDirectHandle(this);
  if (!IsJSFunction(self)) {
    return {-1, -1};
  }
  auto func = i::Cast<i::JSFunction>(self);
  auto shared = func->shared();
  if (i::IsScript(shared->script())) {
    i::DirectHandle<i::Script> script(i::Cast<i::Script>(shared->script()),
                                      i::Isolate::Current());
    return {i::Script::GetLineNumber(script, shared->StartPosition()),
            i::Script::GetColumnNumber(script, shared->StartPosition())};
  }
  return {-1, -1};
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetColumnNumber(), v8::internal::Script::GetLineNumber(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
GetScriptOrigin()
ScriptOrigin v8::Function::GetScriptOrigin () const
Definition at line 5423 of file api.cc.
                                             {
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSFunction(*self)) return v8::ScriptOrigin(Local<Value>());
  auto func = i::Cast<i::JSFunction>(self);
  auto shared = func->shared();
  if (i::IsScript(shared->script())) {
    i::DirectHandle<i::Script> script(i::Cast<i::Script>(shared->script()),
                                      i::Isolate::Current());
    return GetScriptOriginForScript(i::Isolate::Current(), script);
  }
  return v8::ScriptOrigin(Local<Value>());
}
References v8::internal::Isolate::Current(), v8::GetScriptOriginForScript(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
GetScriptStartPosition()
int v8::Function::GetScriptStartPosition () const
Returns zero based start position (character offset) of function body and kLineOffsetNotFound if no information available.
Definition at line 5484 of file api.cc.
                                           {
  auto self = *Utils::OpenDirectHandle(this);
  if (!IsJSFunction(self)) {
    return kLineOffsetNotFound;
  }
  auto func = i::Cast<i::JSFunction>(self);
  auto shared = func->shared();
  if (i::IsScript(shared->script())) {
    return shared->StartPosition();
  }
  return kLineOffsetNotFound;
}
References kLineOffsetNotFound, and v8::Utils::OpenDirectHandle().
New()
MaybeLocal< Function > v8::Function::New (Local< Context > context, FunctionCallback callback, Local< Value > data = Local<Value>(), int length = 0, ConstructorBehavior behavior = ConstructorBehavior::kAllow, SideEffectType side_effect_type = SideEffectType::kHasSideEffect) [static]
Create a function in the current execution context for a given FunctionCallback.
Definition at line 5297 of file api.cc.
                                                                    {
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Function_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto templ =
      FunctionTemplateNew(i_isolate, callback, data, Local<Signature>(), length,
                          behavior, true, Local<Private>(), side_effect_type);
  return Utils::ToLocal(templ)->GetFunction(context);
}
References v8::internal::Isolate::Current(), v8::anonymous_namespace{api.cc}::FunctionTemplateNew(), and v8::internal::length.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8_inspector::V8RuntimeAgentImpl::addBinding(), v8::anonymous_namespace{d8.cc}::ChainDynamicImportPromise(), v8_inspector::anonymous_namespace{v8-console.cc}::createBoundFunctionProperty(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter(), v8_inspector::generateCustomPreview(), v8_inspector::V8Console::installMemoryGetter(), and v8::anonymous_namespace{wasm-js.cc}::StartAsyncCompilationWithResolver().
NewInstance() [1/2]
V8_WARN_UNUSED_RESULT MaybeLocal<Object> v8::Function::NewInstance (Local< Context > context) const [inline]
Definition at line 42 of file v8-function.h.
                                    {
    return NewInstance(context, 0, nullptr);
  }
NewInstance() [2/2]
MaybeLocal< Object > v8::Function::NewInstance (Local< Context > context, int argc, Local< Value > argv[]) const
Definition at line 5310 of file api.cc.
                                                                        {
  return NewInstanceWithSideEffectType(context, argc, argv,
                                       SideEffectType::kHasSideEffect);
}
References v8::kHasSideEffect, and NewInstanceWithSideEffectType().
NewInstanceWithSideEffectType()
MaybeLocal< Object > v8::Function::NewInstanceWithSideEffectType (Local< Context > context, int argc, Local< Value > argv[], SideEffectType side_effect_type = SideEffectType::kHasSideEffect) const
When side effect checks are enabled, passing kHasNoSideEffect allows the constructor to be invoked without throwing.
Calls made within the constructor are still checked.
Definition at line 5316 of file api.cc.
                                           {
  auto i_isolate = i::Isolate::Current();
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.Execute");
  EnterV8Scope<InternalEscapableScope> api_scope{
      i_isolate, context, RCCId::kAPI_Function_NewInstance};
  i::TimerEventScope<i::TimerEventExecute> timer_scope(i_isolate);
  i::NestedTimedHistogramScope execute_timer(i_isolate->counters()->execute(),
                                             i_isolate);
  auto self = Utils::OpenDirectHandle(this);
  bool should_set_has_no_side_effect =
      side_effect_type == SideEffectType::kHasNoSideEffect &&
      i_isolate->should_check_side_effects();
  if (should_set_has_no_side_effect) {
    CHECK(IsJSFunction(*self) &&
          i::Cast<i::JSFunction>(*self)->shared()->IsApiFunction());
    i::Tagged<i::FunctionTemplateInfo> func_data =
        i::Cast<i::JSFunction>(*self)->shared()->api_func_data();
    if (func_data->has_callback(i_isolate)) {
      if (func_data->has_side_effects()) {
        i_isolate->debug()->IgnoreSideEffectsOnNextCallTo(
            handle(func_data, i_isolate));
      }
    }
  }
  auto args = PrepareArguments(argc, argv);
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Execution::New(i_isolate, self, self, args)));
}
References v8::base::args, CHECK, v8::internal::Isolate::counters(), v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), v8::internal::handle(), v8::internal::Debug::IgnoreSideEffectsOnNextCallTo(), v8::kHasNoSideEffect, v8::internal::Execution::New(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::PrepareArguments(), v8::internal::Isolate::should_check_side_effects(), v8::Utils::ToMaybeLocal(), and TRACE_EVENT_CALL_STATS_SCOPED.
Referenced by NewInstance().
ScriptId()
int v8::Function::ScriptId () const
Returns scriptId.
Definition at line 5497 of file api.cc.
                             {
  auto self = *Utils::OpenDirectHandle(this);
  if (!IsJSFunction(self)) return v8::UnboundScript::kNoScriptId;
  auto func = i::Cast<i::JSFunction>(self);
  auto script = func->shared()->script();
  if (!IsScript(script)) return v8::UnboundScript::kNoScriptId;
  return i::Cast<i::Script>(script)->id();
}
References v8::UnboundScript::kNoScriptId, v8::Utils::OpenDirectHandle(), and v8::internal::script.
SetName()
void v8::Function::SetName (Local< String > name)
Definition at line 5373 of file api.cc.
                                             {
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSFunction(*self)) return;
  auto func = i::Cast<i::JSFunction>(self);
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  func->shared()->SetName(*Utils::OpenDirectHandle(*name));
}
References name, and v8::Utils::OpenDirectHandle().
Member Data Documentation
kLineOffsetNotFound
const int v8::Function::kLineOffsetNotFound = -1 [static]
Definition at line 140 of file v8-function.h.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::create(), GetScriptColumnNumber(), GetScriptLineNumber(), and GetScriptStartPosition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-function.h
/mnt/V8SourceCode/src/api/api.cc