v8::Deserializer Class Reference
Public Member Functions
Deserializer (Isolate *isolate, std::unique_ptr< SerializationData > data)
Deserializer (const Deserializer &)=delete
Deserializer & operator= (const Deserializer &)=delete
MaybeLocal< Value > ReadValue (Local< Context > context)
MaybeLocal< SharedArrayBuffer > GetSharedArrayBufferFromId (Isolate *isolate, uint32_t clone_id) override
Get a SharedArrayBuffer given a clone_id previously provided by ValueSerializer::Delegate::GetSharedArrayBufferId.
MaybeLocal< WasmModuleObject > GetWasmModuleFromId (Isolate *isolate, uint32_t transfer_id) override
Get a WasmModuleObject given a transfer_id previously provided by ValueSerializer::Delegate::GetWasmModuleTransferId.
const SharedValueConveyor * GetSharedValueConveyor (Isolate *isolate) override
Get the SharedValueConveyor previously provided by ValueSerializer::Delegate::AdoptSharedValueConveyor.
Private Attributes
Isolate * isolate_
ValueDeserializer deserializer_
std::unique_ptr< SerializationData > data_
Detailed Description
Definition at line 6504 of file d8.cc.
Constructor & Destructor Documentation
Deserializer() [1/2]
v8::Deserializer::Deserializer (Isolate * isolate, std::unique_ptr< SerializationData > data) [inline]
Definition at line 6506 of file d8.cc.
      : isolate_(isolate),
        deserializer_(isolate, data->data(), data->size(), this),
        data_(std::move(data)) {
    deserializer_.SetSupportsLegacyWireFormat(true);
  }
Deserializer() [2/2]
v8::Deserializer::Deserializer (const Deserializer &) [delete]
Member Function Documentation
GetSharedArrayBufferFromId()
MaybeLocal<SharedArrayBuffer> v8::Deserializer::GetSharedArrayBufferFromId (Isolate * isolate, uint32_t clone_id) [inline], [override], [virtual]
Get a SharedArrayBuffer given a clone_id previously provided by ValueSerializer::Delegate::GetSharedArrayBufferId.
Reimplemented from v8::ValueDeserializer::Delegate.
Definition at line 6532 of file d8.cc.
                                                    {
    DCHECK_NOT_NULL(data_);
    if (clone_id < data_->sab_backing_stores().size()) {
      return SharedArrayBuffer::New(
          isolate_, std::move(data_->sab_backing_stores().at(clone_id)));
    }
    return MaybeLocal<SharedArrayBuffer>();
  }
References DCHECK_NOT_NULL, v8::Worker::isolate_, v8::SharedArrayBuffer::New(), and size().
GetSharedValueConveyor()
const SharedValueConveyor* v8::Deserializer::GetSharedValueConveyor (Isolate * isolate) [inline], [override], [virtual]
Get the SharedValueConveyor previously provided by ValueSerializer::Delegate::AdoptSharedValueConveyor.
Reimplemented from v8::ValueDeserializer::Delegate.
Definition at line 6550 of file d8.cc.
                                                                               {
    DCHECK_NOT_NULL(data_);
    if (data_->shared_value_conveyor()) {
      return &data_->shared_value_conveyor().value();
    }
    return nullptr;
  }
References DCHECK_NOT_NULL.
GetWasmModuleFromId()
MaybeLocal<WasmModuleObject> v8::Deserializer::GetWasmModuleFromId (Isolate * isolate, uint32_t transfer_id) [inline], [override], [virtual]
Get a WasmModuleObject given a transfer_id previously provided by ValueSerializer::Delegate::GetWasmModuleTransferId.
Reimplemented from v8::ValueDeserializer::Delegate.
Definition at line 6542 of file d8.cc.
                                                       {
    DCHECK_NOT_NULL(data_);
    if (transfer_id >= data_->compiled_wasm_modules().size()) return {};
    return WasmModuleObject::FromCompiledModule(
        isolate_, data_->compiled_wasm_modules().at(transfer_id));
  }
References DCHECK_NOT_NULL, v8::WasmModuleObject::FromCompiledModule(), and v8::Worker::isolate_.
operator=()
Deserializer& v8::Deserializer::operator= (const Deserializer &) [delete]
ReadValue()
MaybeLocal<Value> v8::Deserializer::ReadValue (Local< Context > context) [inline]
Definition at line 6516 of file d8.cc.
                                                      {
    bool read_header;
    if (!deserializer_.ReadHeader(context).To(&read_header)) {
      return MaybeLocal<Value>();
    }
    uint32_t index = 0;
    for (const auto& backing_store : data_->backing_stores()) {
      Local<ArrayBuffer> array_buffer =
          ArrayBuffer::New(isolate_, std::move(backing_store));
      deserializer_.TransferArrayBuffer(index++, array_buffer);
    }
    return deserializer_.ReadValue(context);
  }
References v8::internal::index, v8::Worker::isolate_, and v8::ArrayBuffer::New().
Referenced by v8::Shell::DeserializeValue().
Member Data Documentation
data_
std::unique_ptr<SerializationData> v8::Deserializer::data_ [private]
Definition at line 6561 of file d8.cc.
deserializer_
ValueDeserializer v8::Deserializer::deserializer_ [private]
Definition at line 6560 of file d8.cc.
isolate_
Isolate* v8::Deserializer::isolate_ [private]
Definition at line 6559 of file d8.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc