v8::internal::VariableMap Class Reference
#include <scopes.h>
Public Member Functions
VariableMap (Zone *zone)
VariableMap (const VariableMap &other, Zone *zone)
VariableMap (VariableMap &&other) V8_NOEXCEPT
VariableMap & operator= (VariableMap &&other) V8_NOEXCEPT
Variable * Declare (Zone *zone, Scope *scope, const AstRawString *name, VariableMode mode, VariableKind kind, InitializationFlag initialization_flag, MaybeAssignedFlag maybe_assigned_flag, IsStaticFlag is_static_flag, bool *was_added)
V8_EXPORT_PRIVATE Variable * Lookup (const AstRawString *name)
void Remove (Variable *var)
void RemoveDynamic ()
void Add (Variable *var)
Zone * zone () const
Additional Inherited Members
Detailed Description
Definition at line 51 of file scopes.h.
Constructor & Destructor Documentation
VariableMap() [1/3]
v8::internal::VariableMap::VariableMap (Zone * zone) [explicit]
Definition at line 40 of file scopes.cc.
    : ZoneHashMap(8, ZoneAllocationPolicy(zone)) {}
VariableMap() [2/3]
v8::internal::VariableMap::VariableMap (const VariableMap & other, Zone * zone)
Definition at line 43 of file scopes.cc.
    : ZoneHashMap(other, ZoneAllocationPolicy(zone)) {}
VariableMap() [3/3]
v8::internal::VariableMap::VariableMap (VariableMap && other) [inline]
Definition at line 56 of file scopes.h.
                                               : ZoneHashMap(std::move(other)) {
  }
Member Function Documentation
Add()
void v8::internal::VariableMap::Add (Variable * var)
Definition at line 87 of file scopes.cc.
                                   {
  const AstRawString* name = var->raw_name();
  Entry* p = ZoneHashMap::LookupOrInsert(const_cast<AstRawString*>(name),
                                         name->Hash());
  DCHECK_NULL(p->value);
  DCHECK_EQ(name, p->key);
  p->value = var;
}
References DCHECK_EQ, DCHECK_NULL, v8::base::TemplateHashMapEntry< Key, Value >::key, v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::LookupOrInsert(), v8::internal::name, v8::internal::Variable::raw_name(), and v8::base::TemplateHashMapEntry< Key, Value >::value.
Referenced by v8::internal::DeclarationScope::DeclareFunctionVar().
Declare()
Variable * v8::internal::VariableMap::Declare (Zone * zone, Scope * scope, const AstRawString * name, VariableMode mode, VariableKind kind, InitializationFlag initialization_flag, MaybeAssignedFlag maybe_assigned_flag, IsStaticFlag is_static_flag, bool * was_added)
Definition at line 46 of file scopes.cc.
                                                                             {
  DCHECK_EQ(zone, allocator().zone());
  // AstRawStrings are unambiguous, i.e., the same string is always represented
  // by the same AstRawString*.
  // FIXME(marja): fix the type of Lookup.
  Entry* p = ZoneHashMap::LookupOrInsert(const_cast<AstRawString*>(name),
                                         name->Hash());
  *was_added = p->value == nullptr;
  if (*was_added) {
    // The variable has not been declared yet -> insert it.
    DCHECK_EQ(name, p->key);
    Variable* variable =
        zone->New<Variable>(scope, name, mode, kind, initialization_flag,
                            maybe_assigned_flag, is_static_flag);
    p->value = variable;
  }
  return reinterpret_cast<Variable*>(p->value);
}
References v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::allocator(), DCHECK_EQ, v8::base::TemplateHashMapEntry< Key, Value >::key, v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::LookupOrInsert(), mode(), v8::internal::name, v8::internal::Zone::New(), v8::base::TemplateHashMapEntry< Key, Value >::value, and zone().
Referenced by v8::internal::DeclarationScope::DeclareDynamicGlobal(), v8::internal::Scope::LookupInScopeInfo(), and v8::internal::Scope::NonLocal().
Lookup()
Variable * v8::internal::VariableMap::Lookup (const AstRawString * name)
Definition at line 96 of file scopes.cc.
                                                      {
  Entry* p = ZoneHashMap::Lookup(const_cast<AstRawString*>(name), name->Hash());
  if (p != nullptr) {
    DCHECK(reinterpret_cast<const AstRawString*>(p->key) == name);
    DCHECK_NOT_NULL(p->value);
    return reinterpret_cast<Variable*>(p->value);
  }
  return nullptr;
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::base::TemplateHashMapEntry< Key, Value >::key, v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::Lookup(), v8::internal::name, and v8::base::TemplateHashMapEntry< Key, Value >::value.
Referenced by v8::internal::DeclarationScope::DeclareFunctionVar(), v8::internal::Scope::Lookup(), v8::internal::Scope::LookupInScopeInfo(), and v8::internal::ClassScope::LookupLocalPrivateName().
operator=()
VariableMap& v8::internal::VariableMap::operator= (VariableMap && other) [inline]
Definition at line 59 of file scopes.h.
                                                          {
    static_cast<ZoneHashMap&>(*this) = std::move(other);
    return *this;
  }
Remove()
void v8::internal::VariableMap::Remove (Variable * var)
Definition at line 70 of file scopes.cc.
                                      {
  const AstRawString* name = var->raw_name();
  ZoneHashMap::Remove(const_cast<AstRawString*>(name), name->Hash());
}
References v8::internal::name, v8::internal::Variable::raw_name(), and v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::Remove().
Referenced by v8::internal::Scope::LookupSloppyEval(), and v8::internal::Scope::LookupWith().
RemoveDynamic()
void v8::internal::VariableMap::RemoveDynamic ()
Definition at line 75 of file scopes.cc.
                                {
  Entry* current = ZoneHashMap::Start();
  while (current != nullptr) {
    Variable* var = reinterpret_cast<Variable*>(current->value);
    if (var->is_dynamic()) {
      ZoneHashMap::Remove(current);
      if (current->exists()) continue;
    }
    current = ZoneHashMap::Next(current);
  }
}
References v8::base::TemplateHashMapEntry< Key, Value >::exists(), v8::internal::Variable::is_dynamic(), v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::Next(), v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::Remove(), v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::Start(), and v8::base::TemplateHashMapEntry< Key, Value >::value.
zone()
Zone* v8::internal::VariableMap::zone () const [inline]
Definition at line 75 of file scopes.h.
{ return allocator().zone(); }
References v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::allocator().
Referenced by Declare().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/scopes.h
/mnt/V8SourceCode/src/ast/scopes.cc