v8::internal::interpreter::BreakableControlFlowBuilder Class Reference
#include <control-flow-builders.h>
Public Member Functions
BreakableControlFlowBuilder (BytecodeArrayBuilder *builder, BlockCoverageBuilder *block_coverage_builder, AstNode *node)
~BreakableControlFlowBuilder () override
void Break ()
void BreakIfTrue (BytecodeArrayBuilder::ToBooleanMode mode)
void BreakIfForInDone (Register index, Register cache_length)
BytecodeLabels * break_labels ()
Protected Member Functions
void EmitJump (BytecodeLabels *labels)
void EmitJumpIfTrue (BytecodeArrayBuilder::ToBooleanMode mode, BytecodeLabels *labels)
void EmitJumpIfFalse (BytecodeArrayBuilder::ToBooleanMode mode, BytecodeLabels *labels)
void EmitJumpIfUndefined (BytecodeLabels *labels)
void EmitJumpIfForInDone (BytecodeLabels *labels, Register index, Register cache_length)
void BindBreakTarget ()
Protected Attributes
BytecodeLabels break_labels_
AstNode * node_
BlockCoverageBuilder * block_coverage_builder_
Detailed Description
Definition at line 37 of file control-flow-builders.h.
Constructor & Destructor Documentation
BreakableControlFlowBuilder()
v8::internal::interpreter::BreakableControlFlowBuilder::BreakableControlFlowBuilder (BytecodeArrayBuilder * builder, BlockCoverageBuilder * block_coverage_builder, AstNode * node) [inline]
Definition at line 40 of file control-flow-builders.h.
      : ControlFlowBuilder(builder),
        break_labels_(builder->zone()),
        node_(node),
        block_coverage_builder_(block_coverage_builder) {}
 BreakableControlFlowBuilder()
v8::internal::interpreter::BreakableControlFlowBuilder::~BreakableControlFlowBuilder () [override]
Definition at line 13 of file control-flow-builders.cc.
                                                          {
  BindBreakTarget();
  DCHECK(break_labels_.empty() || break_labels_.is_bound());
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(
        node_, SourceRangeKind::kContinuation);
  }
}
References BindBreakTarget(), block_coverage_builder_, break_labels_, v8::internal::DCHECK(), v8::internal::interpreter::BytecodeLabels::empty(), v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), v8::internal::interpreter::BytecodeLabels::is_bound(), v8::internal::kContinuation, and node_.
Member Function Documentation
BindBreakTarget()
void v8::internal::interpreter::BreakableControlFlowBuilder::BindBreakTarget () [protected]
Definition at line 22 of file control-flow-builders.cc.
                                                  {
  break_labels_.Bind(builder());
}
References v8::internal::interpreter::BytecodeLabels::Bind(), break_labels_, and v8::internal::interpreter::ControlFlowBuilder::builder().
Referenced by ~BreakableControlFlowBuilder().
Break()
void v8::internal::interpreter::BreakableControlFlowBuilder::Break () [inline]
Definition at line 52 of file control-flow-builders.h.
{ EmitJump(&break_labels_); }
Referenced by v8::internal::interpreter::BytecodeGenerator::ControlScopeForBreakable::Execute(), and v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration::Execute().
break_labels()
BytecodeLabels* v8::internal::interpreter::BreakableControlFlowBuilder::break_labels () [inline]
Definition at line 60 of file control-flow-builders.h.
{ return &break_labels_; }
BreakIfForInDone()
void v8::internal::interpreter::BreakableControlFlowBuilder::BreakIfForInDone (Register index, Register cache_length) [inline]
Definition at line 56 of file control-flow-builders.h.
                                                               {
    EmitJumpIfForInDone(&break_labels_, index, cache_length);
  }
References v8::internal::index.
BreakIfTrue()
void v8::internal::interpreter::BreakableControlFlowBuilder::BreakIfTrue (BytecodeArrayBuilder::ToBooleanMode mode) [inline]
Definition at line 53 of file control-flow-builders.h.
                                                           {
    EmitJumpIfTrue(mode, &break_labels_);
  }
References mode().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), and v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator().
EmitJump()
void v8::internal::interpreter::BreakableControlFlowBuilder::EmitJump (BytecodeLabels * labels) [protected]
Definition at line 26 of file control-flow-builders.cc.
                                                                {
  builder()->Jump(sites->New());
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), and v8::internal::interpreter::BytecodeLabels::New().
Referenced by v8::internal::interpreter::SwitchBuilder::JumpToDefault().
EmitJumpIfFalse()
void v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfFalse (BytecodeArrayBuilder::ToBooleanMode mode, BytecodeLabels * labels) [protected]
Definition at line 35 of file control-flow-builders.cc.
                                                                   {
  builder()->JumpIfFalse(mode, sites->New());
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfFalse(), mode(), and v8::internal::interpreter::BytecodeLabels::New().
Referenced by v8::internal::interpreter::SwitchBuilder::JumpToFallThroughIfFalse().
EmitJumpIfForInDone()
void v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfForInDone (BytecodeLabels * labels, Register index, Register cache_length) [protected]
Definition at line 44 of file control-flow-builders.cc.
                                                                             {
  builder()->JumpIfForInDone(sites->New(), index, cache_length);
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::index, v8::internal::interpreter::BytecodeArrayBuilder::JumpIfForInDone(), and v8::internal::interpreter::BytecodeLabels::New().
EmitJumpIfTrue()
void v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfTrue (BytecodeArrayBuilder::ToBooleanMode mode, BytecodeLabels * labels) [protected]
Definition at line 30 of file control-flow-builders.cc.
                                                                   {
  builder()->JumpIfTrue(mode, sites->New());
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), mode(), and v8::internal::interpreter::BytecodeLabels::New().
EmitJumpIfUndefined()
void v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfUndefined (BytecodeLabels * labels) [protected]
Definition at line 40 of file control-flow-builders.cc.
                                                                           {
  builder()->JumpIfUndefined(sites->New());
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefined(), and v8::internal::interpreter::BytecodeLabels::New().
Member Data Documentation
block_coverage_builder_
BlockCoverageBuilder* v8::internal::interpreter::BreakableControlFlowBuilder::block_coverage_builder_ [protected]
Definition at line 81 of file control-flow-builders.h.
Referenced by v8::internal::interpreter::LoopBuilder::LoopBody(), and ~BreakableControlFlowBuilder().
break_labels_
BytecodeLabels v8::internal::interpreter::BreakableControlFlowBuilder::break_labels_ [protected]
Definition at line 76 of file control-flow-builders.h.
Referenced by BindBreakTarget(), v8::internal::interpreter::LoopBuilder::LoopHeader(), and ~BreakableControlFlowBuilder().
node_
AstNode* v8::internal::interpreter::BreakableControlFlowBuilder::node_ [protected]
Definition at line 80 of file control-flow-builders.h.
Referenced by ~BreakableControlFlowBuilder().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/control-flow-builders.h
/mnt/V8SourceCode/src/interpreter/control-flow-builders.cc