v8::internal::SmallOrderedHashSet Class Reference
#include <ordered-hash-table.h>
Public Member Functions
V8_EXPORT_PRIVATE bool HasKey (Isolate *isolate, DirectHandle< Object > key)
OBJECT_CONSTRUCTORS (SmallOrderedHashSet, SmallOrderedHashTable< SmallOrderedHashSet >)
Static Public Member Functions
static V8_EXPORT_PRIVATE MaybeHandle< SmallOrderedHashSet > Add (Isolate *isolate, Handle< SmallOrderedHashSet > table, DirectHandle< Object > key)
static V8_EXPORT_PRIVATE bool Delete (Isolate *isolate, Tagged< SmallOrderedHashSet > table, Tagged< Object > key)
static bool Is (DirectHandle< HeapObject > table)
static DirectHandle< Map > GetMap (RootsTable &roots)
static Handle< SmallOrderedHashSet > Rehash (Isolate *isolate, Handle< SmallOrderedHashSet > table, int new_capacity)
Static Public Attributes
static const int kKeyIndex = 0
static const int kEntrySize = 1
static const int kPrefixSize = 0
Additional Inherited Members
Detailed Description
Definition at line 666 of file ordered-hash-table.h.
Member Function Documentation
Add()
MaybeHandle< SmallOrderedHashSet > v8::internal::SmallOrderedHashSet::Add (Isolate * isolate, Handle< SmallOrderedHashSet > table, DirectHandle< Object > key) [static]
Definition at line 722 of file ordered-hash-table.cc.
                              {
  if (table->HasKey(isolate, key)) return table;
  if (table->UsedCapacity() >= table->Capacity()) {
    MaybeHandle<SmallOrderedHashSet> new_table =
        SmallOrderedHashSet::Grow(isolate, table);
    if (!new_table.ToHandle(&table)) {
      return MaybeHandle<SmallOrderedHashSet>();
    }
  }
  DisallowGarbageCollection no_gc;
  Tagged<SmallOrderedHashSet> raw_table = *table;
  int hash = Object::GetOrCreateHash(*key, isolate).value();
  int nof = raw_table->NumberOfElements();
  // Read the existing bucket values.
  int bucket = raw_table->HashToBucket(hash);
  int previous_entry = raw_table->HashToFirstEntry(hash);
  // Insert a new entry at the end,
  int new_entry = nof + raw_table->NumberOfDeletedElements();
  raw_table->SetDataEntry(new_entry, SmallOrderedHashSet::kKeyIndex, *key);
  raw_table->SetFirstEntry(bucket, new_entry);
  raw_table->SetNextEntry(new_entry, previous_entry);
  // and update book keeping.
  raw_table->SetNumberOfElements(nof + 1);
  return table;
}
References v8::internal::GetOrCreateHash(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::MaybeHandle< T >::ToHandle().
Delete()
bool v8::internal::SmallOrderedHashSet::Delete (Isolate * isolate, Tagged< SmallOrderedHashSet > table, Tagged< Object > key) [static]
Definition at line 757 of file ordered-hash-table.cc.
                                                     {
  return SmallOrderedHashTable<SmallOrderedHashSet>::Delete(isolate, table,
                                                            key);
}
References v8::internal::key.
GetMap()
DirectHandle< Map > v8::internal::SmallOrderedHashSet::GetMap (RootsTable & roots) [inline], [static]
Definition at line 80 of file ordered-hash-table-inl.h.
                                                               {
  return roots.small_ordered_hash_set_map();
}
HasKey()
bool v8::internal::SmallOrderedHashSet::HasKey (Isolate * isolate, DirectHandle< Object > key)
Definition at line 764 of file ordered-hash-table.cc.
                                                                           {
  return SmallOrderedHashTable<SmallOrderedHashSet>::HasKey(isolate, key);
}
References v8::internal::key.
Is()
bool v8::internal::SmallOrderedHashSet::Is (DirectHandle< HeapObject > table) [inline], [static]
Definition at line 168 of file ordered-hash-table-inl.h.
                                                                  {
  return IsSmallOrderedHashSet(*table);
}
OBJECT_CONSTRUCTORS()
v8::internal::SmallOrderedHashSet::OBJECT_CONSTRUCTORS (SmallOrderedHashSet , SmallOrderedHashTable< SmallOrderedHashSet >)
Rehash()
Handle< SmallOrderedHashSet > v8::internal::SmallOrderedHashSet::Rehash (Isolate * isolate, Handle< SmallOrderedHashSet > table, int new_capacity) [static]
Definition at line 978 of file ordered-hash-table.cc.
                                                                           {
  return SmallOrderedHashTable<SmallOrderedHashSet>::Rehash(isolate, table,
                                                            new_capacity);
}
Member Data Documentation
kEntrySize
const int v8::internal::SmallOrderedHashSet::kEntrySize = 1 [static]
Definition at line 672 of file ordered-hash-table.h.
kKeyIndex
const int v8::internal::SmallOrderedHashSet::kKeyIndex = 0 [static]
Definition at line 671 of file ordered-hash-table.h.
kPrefixSize
const int v8::internal::SmallOrderedHashSet::kPrefixSize = 0 [static]
Definition at line 673 of file ordered-hash-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table-inl.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc