v8::internal::maglev::CallKnownApiFunction Class Reference
#include <maglev-ir.h>
Public Types
enum Mode { kNoProfiling
, kNoProfilingInlined
, kGeneric
 }
Public Member Functions
CallKnownApiFunction (uint64_t bitfield, Mode mode, compiler::FunctionTemplateInfoRef function_template_info, ValueNode *context, ValueNode *receiver)
Input & context ()
const Input & context () const
Input & receiver ()
const Input & receiver () const
int num_args () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
auto args ()
Mode mode () const
compiler::FunctionTemplateInfoRef function_template_info () const
bool inline_builtin () const
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr int kContextIndex = 0
static constexpr int kReceiverIndex = 1
static constexpr int kFixedInputCount = 2
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< CallKnownApiFunction >
using ModeField = NextBitField< Mode, 2 >
Private Member Functions
void GenerateCallApiCallbackOptimizedInline (MaglevAssembler *masm, const ProcessingState &state)
Private Attributes
const compiler::FunctionTemplateInfoRef function_template_info_
const compiler::OptionalJSObjectRef api_holder_
Additional Inherited Members
Detailed Description
Definition at line 10599 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallKnownApiFunction::Base = ValueNodeT<CallKnownApiFunction> [private]
Definition at line 10600 of file maglev-ir.h.
ModeField
using v8::internal::maglev::CallKnownApiFunction::ModeField = NextBitField<Mode, 2> [private]
Definition at line 10670 of file maglev-ir.h.
Member Enumeration Documentation
Mode
enum v8::internal::maglev::CallKnownApiFunction::Mode
Enumerator
kNoProfiling
kNoProfilingInlined
kGeneric
Definition at line 10603 of file maglev-ir.h.
            {
    // Use Builtin::kCallApiCallbackOptimizedNoProfiling.
    kNoProfiling,
    // Inline API call sequence into the generated code.
    kNoProfilingInlined,
    // Use Builtin::kCallApiCallbackOptimized.
    kGeneric,
  };
Constructor & Destructor Documentation
CallKnownApiFunction()
v8::internal::maglev::CallKnownApiFunction::CallKnownApiFunction (uint64_t bitfield, Mode mode, compiler::FunctionTemplateInfoRef function_template_info, ValueNode * context, ValueNode * receiver) [inline]
Definition at line 10622 of file maglev-ir.h.
      : Base(bitfield | ModeField::encode(mode)),
        function_template_info_(function_template_info) {
    set_input(kContextIndex, context);
    set_input(kReceiverIndex, receiver);
  }
Member Function Documentation
arg()
Input& v8::internal::maglev::CallKnownApiFunction::arg (int i) [inline]
Definition at line 10642 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
args()
auto v8::internal::maglev::CallKnownApiFunction::args () [inline]
Definition at line 10646 of file maglev-ir.h.
              {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args() - 1)));
  }
References v8::base::make_iterator_range().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [1/2]
Input& v8::internal::maglev::CallKnownApiFunction::context () [inline]
Definition at line 10637 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [2/2]
const Input& v8::internal::maglev::CallKnownApiFunction::context () const [inline]
Definition at line 10638 of file maglev-ir.h.
{ return input(kContextIndex); }
function_template_info()
compiler::FunctionTemplateInfoRef v8::internal::maglev::CallKnownApiFunction::function_template_info () const [inline]
Definition at line 10654 of file maglev-ir.h.
                                                                 {
    return function_template_info_;
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCallApiCallbackOptimizedInline()
void v8::internal::maglev::CallKnownApiFunction::GenerateCallApiCallbackOptimizedInline (MaglevAssembler * masm, const ProcessingState & state) [private]
GenerateCode()
void v8::internal::maglev::CallKnownApiFunction::GenerateCode (MaglevAssembler * , const ProcessingState &)
inline_builtin()
bool v8::internal::maglev::CallKnownApiFunction::inline_builtin () const [inline]
Definition at line 10658 of file maglev-ir.h.
{ return mode() == kNoProfilingInlined; }
References mode().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::CallKnownApiFunction::MaxCallStackArgs () const
mode()
Mode v8::internal::maglev::CallKnownApiFunction::mode () const [inline]
Definition at line 10652 of file maglev-ir.h.
{ return ModeField::decode(bitfield()); }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
num_args()
int v8::internal::maglev::CallKnownApiFunction::num_args () const [inline]
Definition at line 10641 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::CallKnownApiFunction::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8391 of file maglev-ir.cc.
                                                               {
  os << "(";
  switch (mode()) {
    case kNoProfiling:
      os << "no profiling, ";
      break;
    case kNoProfilingInlined:
      os << "no profiling inlined, ";
      break;
    case kGeneric:
      break;
  }
  os << function_template_info_.object() << ")";
}
References function_template_info_, kGeneric, kNoProfiling, kNoProfilingInlined, mode(), and v8::internal::compiler::FunctionTemplateInfoRef::object().
receiver() [1/2]
Input& v8::internal::maglev::CallKnownApiFunction::receiver () [inline]
Definition at line 10639 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
receiver() [2/2]
const Input& v8::internal::maglev::CallKnownApiFunction::receiver () const [inline]
Definition at line 10640 of file maglev-ir.h.
{ return input(kReceiverIndex); }
set_arg()
void v8::internal::maglev::CallKnownApiFunction::set_arg (int i, ValueNode * node) [inline]
Definition at line 10643 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForApiFunction().
SetValueLocationConstraints()
void v8::internal::maglev::CallKnownApiFunction::SetValueLocationConstraints ()
VerifyInputs()
void v8::internal::maglev::CallKnownApiFunction::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 1008 of file maglev-ir.cc.
                                               {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
api_holder_
const compiler::OptionalJSObjectRef v8::internal::maglev::CallKnownApiFunction::api_holder_ [private]
Definition at line 10676 of file maglev-ir.h.
function_template_info_
const compiler::FunctionTemplateInfoRef v8::internal::maglev::CallKnownApiFunction::function_template_info_ [private]
Definition at line 10675 of file maglev-ir.h.
Referenced by PrintParams().
kContextIndex
constexpr int v8::internal::maglev::CallKnownApiFunction::kContextIndex = 0 [static], [constexpr]
Definition at line 10612 of file maglev-ir.h.
kFixedInputCount
constexpr int v8::internal::maglev::CallKnownApiFunction::kFixedInputCount = 2 [static], [constexpr]
Definition at line 10614 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CallKnownApiFunction::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10633 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CallKnownApiFunction::kReceiverIndex = 1 [static], [constexpr]
Definition at line 10613 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc