v8::internal::MicrotaskQueueBuiltinsAssembler Class Reference
Public Member Functions
MicrotaskQueueBuiltinsAssembler (compiler::CodeAssemblerState *state)
TNode< RawPtrT > GetMicrotaskQueue (TNode< Context > context)
TNode< RawPtrT > GetMicrotaskRingBuffer (TNode< RawPtrT > microtask_queue)
TNode< IntPtrT > GetMicrotaskQueueCapacity (TNode< RawPtrT > microtask_queue)
TNode< IntPtrT > GetMicrotaskQueueSize (TNode< RawPtrT > microtask_queue)
void SetMicrotaskQueueSize (TNode< RawPtrT > microtask_queue, TNode< IntPtrT > new_size)
TNode< IntPtrT > GetMicrotaskQueueStart (TNode< RawPtrT > microtask_queue)
void SetMicrotaskQueueStart (TNode< RawPtrT > microtask_queue, TNode< IntPtrT > new_start)
TNode< IntPtrT > CalculateRingBufferOffset (TNode< IntPtrT > capacity, TNode< IntPtrT > start, TNode< IntPtrT > index)
void PrepareForContext (TNode< Context > microtask_context, Label *bailout)
void RunSingleMicrotask (TNode< Context > current_context, TNode< Microtask > microtask)
void IncrementFinishedMicrotaskCount (TNode< RawPtrT > microtask_queue)
TNode< Context > GetCurrentContext ()
void SetCurrentContext (TNode< Context > context)
TNode< IntPtrT > GetEnteredContextCount ()
void EnterContext (TNode< Context > native_context)
void RewindEnteredContext (TNode< IntPtrT > saved_entered_context_count)
void RunAllPromiseHooks (PromiseHookType type, TNode< Context > context, TNode< HeapObject > promise_or_capability)
void RunPromiseHook (Runtime::FunctionId id, TNode< Context > context, TNode< HeapObject > promise_or_capability, TNode< Uint32T > promiseHookFlags)
Additional Inherited Members
Detailed Description
Definition at line 21 of file builtins-microtask-queue-gen.cc.
Constructor & Destructor Documentation
MicrotaskQueueBuiltinsAssembler()
v8::internal::MicrotaskQueueBuiltinsAssembler::MicrotaskQueueBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 23 of file builtins-microtask-queue-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
CalculateRingBufferOffset()
TNode< IntPtrT > v8::internal::MicrotaskQueueBuiltinsAssembler::CalculateRingBufferOffset (TNode< IntPtrT > capacity, TNode< IntPtrT > start, TNode< IntPtrT > index)
Definition at line 106 of file builtins-microtask-queue-gen.cc.
                                                                         {
  return TimesSystemPointerSize(
      WordAnd(IntPtrAdd(start, index), IntPtrSub(capacity, IntPtrConstant(1))));
}
References v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrSub(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), and v8::internal::compiler::CodeAssembler::WordAnd().
EnterContext()
void v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext (TNode< Context > native_context)
Definition at line 402 of file builtins-microtask-queue-gen.cc.
                                   {
  CSA_DCHECK(this, IsNativeContext(native_context));
  auto ref = ExternalReference::handle_scope_implementer_address(isolate());
  TNode<RawPtrT> hsi = Load<RawPtrT>(ExternalConstant(ref));
  using ContextStack = DetachableVector<Context>;
  TNode<IntPtrT> capacity_offset =
      IntPtrConstant(HandleScopeImplementer::kEnteredContextsOffset +
                     ContextStack::kCapacityOffset);
  TNode<IntPtrT> size_offset =
      IntPtrConstant(HandleScopeImplementer::kEnteredContextsOffset +
                     ContextStack::kSizeOffset);
  TNode<IntPtrT> capacity = Load<IntPtrT>(hsi, capacity_offset);
  TNode<IntPtrT> size = Load<IntPtrT>(hsi, size_offset);
  Label if_append(this), if_grow(this, Label::kDeferred), done(this);
  Branch(WordEqual(size, capacity), &if_grow, &if_append);
  BIND(&if_append);
  {
    TNode<IntPtrT> data_offset =
        IntPtrConstant(HandleScopeImplementer::kEnteredContextsOffset +
                       ContextStack::kDataOffset);
    TNode<RawPtrT> data = Load<RawPtrT>(hsi, data_offset);
    StoreFullTaggedNoWriteBarrier(data, TimesSystemPointerSize(size),
                                  native_context);
    TNode<IntPtrT> new_size = IntPtrAdd(size, IntPtrConstant(1));
    StoreNoWriteBarrier(MachineType::PointerRepresentation(), hsi, size_offset,
                        new_size);
    Goto(&done);
  }
  BIND(&if_grow);
  {
    TNode<ExternalReference> function =
        ExternalConstant(ExternalReference::call_enter_context_function());
    CallCFunction(function, MachineType::Int32(),
                  std::make_pair(MachineType::Pointer(), hsi),
                  std::make_pair(MachineType::Pointer(),
                                 BitcastTaggedToWord(native_context)));
    Goto(&done);
  }
  BIND(&done);
}
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::MachineType::Int32(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::HandleScopeImplementer::kEnteredContextsOffset, v8::internal::native_context, v8::internal::MachineType::Pointer(), v8::internal::MachineType::PointerRepresentation(), size(), v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), and v8::internal::compiler::CodeAssembler::WordEqual().
Referenced by PrepareForContext().
GetCurrentContext()
TNode< Context > v8::internal::MicrotaskQueueBuiltinsAssembler::GetCurrentContext ()
Definition at line 378 of file builtins-microtask-queue-gen.cc.
                                                                  {
  auto ref = ExternalReference::Create(kContextAddress, isolate());
  // TODO(delphick): Add a checked cast. For now this is not possible as context
  // can actually be Tagged<Smi>(0).
  return TNode<Context>::UncheckedCast(LoadFullTagged(ExternalConstant(ref)));
}
References v8::internal::ExternalReference::Create(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssembler::LoadFullTagged(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by RunSingleMicrotask().
GetEnteredContextCount()
TNode< IntPtrT > v8::internal::MicrotaskQueueBuiltinsAssembler::GetEnteredContextCount ()
Definition at line 391 of file builtins-microtask-queue-gen.cc.
                                                                       {
  auto ref = ExternalReference::handle_scope_implementer_address(isolate());
  TNode<RawPtrT> hsi = Load<RawPtrT>(ExternalConstant(ref));
  using ContextStack = DetachableVector<Context>;
  TNode<IntPtrT> size_offset =
      IntPtrConstant(HandleScopeImplementer::kEnteredContextsOffset +
                     ContextStack::kSizeOffset);
  return Load<IntPtrT>(hsi, size_offset);
}
References v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::isolate(), and v8::internal::HandleScopeImplementer::kEnteredContextsOffset.
Referenced by RunSingleMicrotask().
GetMicrotaskQueue()
TNode< RawPtrT > v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueue (TNode< Context > context)
Definition at line 62 of file builtins-microtask-queue-gen.cc.
                                   {
  CSA_DCHECK(this, IsNativeContext(native_context));
  return LoadExternalPointerFromObject(native_context,
                                       NativeContext::kMicrotaskQueueOffset,
                                       kNativeContextMicrotaskQueueTag);
}
References v8::internal::kNativeContextMicrotaskQueueTag, v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), and v8::internal::native_context.
Referenced by PrepareForContext().
GetMicrotaskQueueCapacity()
TNode< IntPtrT > v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueCapacity (TNode< RawPtrT > microtask_queue)
Definition at line 76 of file builtins-microtask-queue-gen.cc.
                                    {
  return Load<IntPtrT>(microtask_queue,
                       IntPtrConstant(MicrotaskQueue::kCapacityOffset));
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), and v8::internal::MicrotaskQueue::kCapacityOffset.
GetMicrotaskQueueSize()
TNode< IntPtrT > v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueSize (TNode< RawPtrT > microtask_queue)
Definition at line 82 of file builtins-microtask-queue-gen.cc.
                                    {
  return Load<IntPtrT>(microtask_queue,
                       IntPtrConstant(MicrotaskQueue::kSizeOffset));
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), and v8::internal::MicrotaskQueue::kSizeOffset.
GetMicrotaskQueueStart()
TNode< IntPtrT > v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueStart (TNode< RawPtrT > microtask_queue)
Definition at line 94 of file builtins-microtask-queue-gen.cc.
                                    {
  return Load<IntPtrT>(microtask_queue,
                       IntPtrConstant(MicrotaskQueue::kStartOffset));
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), and v8::internal::MicrotaskQueue::kStartOffset.
GetMicrotaskRingBuffer()
TNode< RawPtrT > v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskRingBuffer (TNode< RawPtrT > microtask_queue)
Definition at line 70 of file builtins-microtask-queue-gen.cc.
                                    {
  return Load<RawPtrT>(microtask_queue,
                       IntPtrConstant(MicrotaskQueue::kRingBufferOffset));
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), and v8::internal::MicrotaskQueue::kRingBufferOffset.
IncrementFinishedMicrotaskCount()
void v8::internal::MicrotaskQueueBuiltinsAssembler::IncrementFinishedMicrotaskCount (TNode< RawPtrT > microtask_queue)
Definition at line 367 of file builtins-microtask-queue-gen.cc.
                                    {
  TNode<IntPtrT> count = Load<IntPtrT>(
      microtask_queue,
      IntPtrConstant(MicrotaskQueue::kFinishedMicrotaskCountOffset));
  TNode<IntPtrT> new_count = IntPtrAdd(count, IntPtrConstant(1));
  StoreNoWriteBarrier(
      MachineType::PointerRepresentation(), microtask_queue,
      IntPtrConstant(MicrotaskQueue::kFinishedMicrotaskCountOffset), new_count);
}
References v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::MicrotaskQueue::kFinishedMicrotaskCountOffset, v8::internal::MachineType::PointerRepresentation(), and v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier().
PrepareForContext()
void v8::internal::MicrotaskQueueBuiltinsAssembler::PrepareForContext (TNode< Context > microtask_context, Label * bailout)
Definition at line 112 of file builtins-microtask-queue-gen.cc.
                                                   {
  CSA_DCHECK(this, IsNativeContext(native_context));
  // Skip the microtask execution if the associated context is shutdown.
  GotoIf(WordEqual(GetMicrotaskQueue(native_context), IntPtrConstant(0)),
         bailout);
  EnterContext(native_context);
  SetCurrentContext(native_context);
}
References EnterContext(), GetMicrotaskQueue(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::native_context, SetCurrentContext(), and v8::internal::compiler::CodeAssembler::WordEqual().
Referenced by RunSingleMicrotask().
RewindEnteredContext()
void v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext (TNode< IntPtrT > saved_entered_context_count)
Definition at line 451 of file builtins-microtask-queue-gen.cc.
                                                {
  auto ref = ExternalReference::handle_scope_implementer_address(isolate());
  TNode<RawPtrT> hsi = Load<RawPtrT>(ExternalConstant(ref));
  using ContextStack = DetachableVector<Context>;
  TNode<IntPtrT> size_offset =
      IntPtrConstant(HandleScopeImplementer::kEnteredContextsOffset +
                     ContextStack::kSizeOffset);
  if (DEBUG_BOOL) {
    TNode<IntPtrT> size = Load<IntPtrT>(hsi, size_offset);
    CSA_CHECK(this, IntPtrLessThan(IntPtrConstant(0), size));
    CSA_CHECK(this, IntPtrLessThanOrEqual(saved_entered_context_count, size));
  }
  StoreNoWriteBarrier(MachineType::PointerRepresentation(), hsi, size_offset,
                      saved_entered_context_count);
}
References DEBUG_BOOL, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThanOrEqual(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::HandleScopeImplementer::kEnteredContextsOffset, v8::internal::MachineType::PointerRepresentation(), size(), and v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier().
Referenced by RunSingleMicrotask().
RunAllPromiseHooks()
void v8::internal::MicrotaskQueueBuiltinsAssembler::RunAllPromiseHooks (PromiseHookType type, TNode< Context > context, TNode< HeapObject > promise_or_capability)
Definition at line 471 of file builtins-microtask-queue-gen.cc.
                                             {
  TNode<Uint32T> promiseHookFlags = PromiseHookFlags();
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  Label hook(this, Label::kDeferred), done_hook(this);
  Branch(NeedsAnyPromiseHooks(promiseHookFlags), &hook, &done_hook);
  BIND(&hook);
  {
#endif
    switch (type) {
      case PromiseHookType::kBefore:
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
        RunContextPromiseHookBefore(context, CAST(promise_or_capability),
                                    promiseHookFlags);
#endif
        RunPromiseHook(Runtime::kPromiseHookBefore, context,
                       promise_or_capability, promiseHookFlags);
        break;
      case PromiseHookType::kAfter:
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
        RunContextPromiseHookAfter(context, CAST(promise_or_capability),
                                   promiseHookFlags);
#endif
        RunPromiseHook(Runtime::kPromiseHookAfter, context,
                       promise_or_capability, promiseHookFlags);
        break;
      default:
        UNREACHABLE();
    }
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
    Goto(&done_hook);
  }
  BIND(&done_hook);
#endif
}
References v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::kAfter, v8::kBefore, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::NeedsAnyPromiseHooks(), v8::internal::CodeStubAssembler::PromiseHookFlags(), RunPromiseHook(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by RunSingleMicrotask().
RunPromiseHook()
void v8::internal::MicrotaskQueueBuiltinsAssembler::RunPromiseHook (Runtime::FunctionId id, TNode< Context > context, TNode< HeapObject > promise_or_capability, TNode< Uint32T > promiseHookFlags)
Definition at line 508 of file builtins-microtask-queue-gen.cc.
                                     {
  Label hook(this, Label::kDeferred), done_hook(this);
  Branch(IsIsolatePromiseHookEnabledOrDebugIsActiveOrHasAsyncEventDelegate(
      promiseHookFlags), &hook, &done_hook);
  BIND(&hook);
  {
    // Get to the underlying JSPromise instance.
    TNode<HeapObject> promise = Select<HeapObject>(
        IsPromiseCapability(promise_or_capability),
        [=, this] {
          return CAST(LoadObjectField(promise_or_capability,
                                      PromiseCapability::kPromiseOffset));
        },
        [=] { return promise_or_capability; });
    GotoIf(IsUndefined(promise), &done_hook);
    CallRuntime(id, context, promise);
    Goto(&done_hook);
  }
  BIND(&done_hook);
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IsIsolatePromiseHookEnabledOrDebugIsActiveOrHasAsyncEventDelegate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, and v8::internal::CodeStubAssembler::LoadObjectField().
Referenced by RunAllPromiseHooks().
RunSingleMicrotask()
void v8::internal::MicrotaskQueueBuiltinsAssembler::RunSingleMicrotask (TNode< Context > current_context, TNode< Microtask > microtask)
Definition at line 145 of file builtins-microtask-queue-gen.cc.
                                                                {
  CSA_DCHECK(this, TaggedIsNotSmi(microtask));
  CSA_DCHECK(this, Word32BinaryNot(IsExecutionTerminating()));
  StoreRoot(RootIndex::kCurrentMicrotask, microtask);
  TNode<IntPtrT> saved_entered_context_count = GetEnteredContextCount();
  TNode<Map> microtask_map = LoadMap(microtask);
  TNode<Uint16T> microtask_type = LoadMapInstanceType(microtask_map);
  TVARIABLE(Object, var_exception);
  Label if_exception(this, Label::kDeferred);
  Label is_callable(this), is_callback(this),
      is_promise_fulfill_reaction_job(this),
      is_promise_reject_reaction_job(this),
      is_promise_resolve_thenable_job(this),
      is_unreachable(this, Label::kDeferred), done(this);
  int32_t case_values[] = {CALLABLE_TASK_TYPE, CALLBACK_TASK_TYPE,
                           PROMISE_FULFILL_REACTION_JOB_TASK_TYPE,
                           PROMISE_REJECT_REACTION_JOB_TASK_TYPE,
                           PROMISE_RESOLVE_THENABLE_JOB_TASK_TYPE};
  Label* case_labels[] = {
      &is_callable, &is_callback, &is_promise_fulfill_reaction_job,
      &is_promise_reject_reaction_job, &is_promise_resolve_thenable_job};
  static_assert(arraysize(case_values) == arraysize(case_labels), "");
  Switch(microtask_type, &is_unreachable, case_values, case_labels,
         arraysize(case_labels));
  BIND(&is_callable);
  {
    // Enter the context of the {microtask}.
    TNode<Context> microtask_context =
        LoadObjectField<Context>(microtask, CallableTask::kContextOffset);
    TNode<NativeContext> native_context = LoadNativeContext(microtask_context);
    PrepareForContext(native_context, &done);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    SetupContinuationPreservedEmbedderData(microtask);
#endif
    TNode<JSReceiver> callable =
        LoadObjectField<JSReceiver>(microtask, CallableTask::kCallableOffset);
    {
      ScopedExceptionHandler handler(this, &if_exception, &var_exception);
      Call(microtask_context, callable, UndefinedConstant());
    }
    RewindEnteredContext(saved_entered_context_count);
    SetCurrentContext(current_context);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    ClearContinuationPreservedEmbedderData();
#endif
    Goto(&done);
  }
  BIND(&is_callback);
  {
    const TNode<Object> microtask_callback =
        LoadObjectField(microtask, CallbackTask::kCallbackOffset);
    const TNode<Object> microtask_data =
        LoadObjectField(microtask, CallbackTask::kDataOffset);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    SetupContinuationPreservedEmbedderData(microtask);
#endif
    // If this turns out to become a bottleneck because of the calls
    // to C++ via CEntry, we can choose to speed them up using a
    // similar mechanism that we use for the CallApiFunction stub,
    // except that calling the MicrotaskCallback is even easier, since
    // it doesn't accept any tagged parameters, doesn't return a value
    // and ignores exceptions.
    //
    // But from our current measurements it doesn't seem to be a
    // serious performance problem, even if the microtask is full
    // of CallHandlerTasks (which is not a realistic use case anyways).
    {
      ScopedExceptionHandler handler(this, &if_exception, &var_exception);
      CallRuntime(Runtime::kRunMicrotaskCallback, current_context,
                  microtask_callback, microtask_data);
    }
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    ClearContinuationPreservedEmbedderData();
#endif
    Goto(&done);
  }
  BIND(&is_promise_resolve_thenable_job);
  {
    // Enter the context of the {microtask}.
    TNode<Context> microtask_context = LoadObjectField<Context>(
        microtask, PromiseResolveThenableJobTask::kContextOffset);
    TNode<NativeContext> native_context = LoadNativeContext(microtask_context);
    PrepareForContext(native_context, &done);
    const TNode<Object> promise_to_resolve = LoadObjectField(
        microtask, PromiseResolveThenableJobTask::kPromiseToResolveOffset);
    const TNode<Object> then =
        LoadObjectField(microtask, PromiseResolveThenableJobTask::kThenOffset);
    const TNode<Object> thenable = LoadObjectField(
        microtask, PromiseResolveThenableJobTask::kThenableOffset);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    SetupContinuationPreservedEmbedderData(microtask);
#endif
    RunAllPromiseHooks(PromiseHookType::kBefore, microtask_context,
                   CAST(promise_to_resolve));
    {
      ScopedExceptionHandler handler(this, &if_exception, &var_exception);
      CallBuiltin(Builtin::kPromiseResolveThenableJob, native_context,
                  promise_to_resolve, thenable, then);
    }
    RunAllPromiseHooks(PromiseHookType::kAfter, microtask_context,
                   CAST(promise_to_resolve));
    RewindEnteredContext(saved_entered_context_count);
    SetCurrentContext(current_context);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    ClearContinuationPreservedEmbedderData();
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    Goto(&done);
  }
  BIND(&is_promise_fulfill_reaction_job);
  {
    // Enter the context of the {microtask}.
    TNode<Context> microtask_context = LoadObjectField<Context>(
        microtask, PromiseReactionJobTask::kContextOffset);
    TNode<NativeContext> native_context = LoadNativeContext(microtask_context);
    PrepareForContext(native_context, &done);
    const TNode<Object> argument =
        LoadObjectField(microtask, PromiseReactionJobTask::kArgumentOffset);
    const TNode<Object> job_handler =
        LoadObjectField(microtask, PromiseReactionJobTask::kHandlerOffset);
    const TNode<HeapObject> promise_or_capability = CAST(LoadObjectField(
        microtask, PromiseReactionJobTask::kPromiseOrCapabilityOffset));
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    SetupContinuationPreservedEmbedderData(microtask);
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    // Run the promise before/debug hook if enabled.
    RunAllPromiseHooks(PromiseHookType::kBefore, microtask_context,
                       promise_or_capability);
    {
      ScopedExceptionHandler handler(this, &if_exception, &var_exception);
      CallBuiltin(Builtin::kPromiseFulfillReactionJob, microtask_context,
                  argument, job_handler, promise_or_capability);
    }
    // Run the promise after/debug hook if enabled.
    RunAllPromiseHooks(PromiseHookType::kAfter, microtask_context,
                       promise_or_capability);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    ClearContinuationPreservedEmbedderData();
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    RewindEnteredContext(saved_entered_context_count);
    SetCurrentContext(current_context);
    Goto(&done);
  }
  BIND(&is_promise_reject_reaction_job);
  {
    // Enter the context of the {microtask}.
    TNode<Context> microtask_context = LoadObjectField<Context>(
        microtask, PromiseReactionJobTask::kContextOffset);
    TNode<NativeContext> native_context = LoadNativeContext(microtask_context);
    PrepareForContext(native_context, &done);
    const TNode<Object> argument =
        LoadObjectField(microtask, PromiseReactionJobTask::kArgumentOffset);
    const TNode<Object> job_handler =
        LoadObjectField(microtask, PromiseReactionJobTask::kHandlerOffset);
    const TNode<HeapObject> promise_or_capability = CAST(LoadObjectField(
        microtask, PromiseReactionJobTask::kPromiseOrCapabilityOffset));
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    SetupContinuationPreservedEmbedderData(microtask);
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    // Run the promise before/debug hook if enabled.
    RunAllPromiseHooks(PromiseHookType::kBefore, microtask_context,
                       promise_or_capability);
    {
      ScopedExceptionHandler handler(this, &if_exception, &var_exception);
      CallBuiltin(Builtin::kPromiseRejectReactionJob, microtask_context,
                  argument, job_handler, promise_or_capability);
    }
    // Run the promise after/debug hook if enabled.
    RunAllPromiseHooks(PromiseHookType::kAfter, microtask_context,
                       promise_or_capability);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    ClearContinuationPreservedEmbedderData();
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    RewindEnteredContext(saved_entered_context_count);
    SetCurrentContext(current_context);
    Goto(&done);
  }
  BIND(&is_unreachable);
  Unreachable();
  BIND(&if_exception);
  {
    // Report unhandled exceptions from microtasks.
    CallRuntime(Runtime::kReportMessageFromMicrotask, GetCurrentContext(),
                var_exception.value());
    RewindEnteredContext(saved_entered_context_count);
    SetCurrentContext(current_context);
    Goto(&done);
  }
  BIND(&done);
}
References arraysize, v8::internal::CodeStubAssembler::Call(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, GetCurrentContext(), GetEnteredContextCount(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::IsExecutionTerminating(), v8::kAfter, v8::kBefore, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::native_context, PrepareForContext(), RewindEnteredContext(), RunAllPromiseHooks(), SetCurrentContext(), v8::internal::compiler::CodeAssembler::StoreRoot(), v8::internal::compiler::CodeAssembler::Switch(), v8::internal::CodeStubAssembler::TaggedIsNotSmi(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::compiler::CodeAssembler::Unreachable().
SetCurrentContext()
void v8::internal::MicrotaskQueueBuiltinsAssembler::SetCurrentContext (TNode< Context > context)
Definition at line 385 of file builtins-microtask-queue-gen.cc.
                            {
  auto ref = ExternalReference::Create(kContextAddress, isolate());
  StoreFullTaggedNoWriteBarrier(ExternalConstant(ref), context);
}
References v8::internal::ExternalReference::Create(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::isolate(), and v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier().
Referenced by PrepareForContext(), and RunSingleMicrotask().
SetMicrotaskQueueSize()
void v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueSize (TNode< RawPtrT > microtask_queue, TNode< IntPtrT > new_size)
Definition at line 88 of file builtins-microtask-queue-gen.cc.
                                                             {
  StoreNoWriteBarrier(MachineType::PointerRepresentation(), microtask_queue,
                      IntPtrConstant(MicrotaskQueue::kSizeOffset), new_size);
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::MicrotaskQueue::kSizeOffset, v8::internal::MachineType::PointerRepresentation(), and v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier().
SetMicrotaskQueueStart()
void v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueStart (TNode< RawPtrT > microtask_queue, TNode< IntPtrT > new_start)
Definition at line 100 of file builtins-microtask-queue-gen.cc.
                                                              {
  StoreNoWriteBarrier(MachineType::PointerRepresentation(), microtask_queue,
                      IntPtrConstant(MicrotaskQueue::kStartOffset), new_start);
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::MicrotaskQueue::kStartOffset, v8::internal::MachineType::PointerRepresentation(), and v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-microtask-queue-gen.cc