v8::internal::compiler::turboshaft::OptionalOpIndex Class Reference
#include <index.h>
Public Member Functions
constexpr OptionalOpIndex (OpIndex other)
uint32_t hash () const
constexpr bool has_value () const
constexpr OpIndex value () const
constexpr OpIndex value_or_invalid () const
constexpr OpIndex (uint32_t offset)
constexpr OpIndex ()
template<typename T , typename C >
OpIndex (const ConstOrV< T, C > &)
constexpr bool valid () const
Static Public Member Functions
static constexpr OptionalOpIndex Nullopt ()
Friends
template<typename H >
H AbslHashValue (H h, const OptionalOpIndex &idx)
Additional Inherited Members
Detailed Description
Definition at line 169 of file index.h.
Constructor & Destructor Documentation
OptionalOpIndex()
constexpr v8::internal::compiler::turboshaft::OptionalOpIndex::OptionalOpIndex (OpIndex other) [inline], [constexpr]
Definition at line 174 of file index.h.
      : OpIndex(other) {}
Member Function Documentation
has_value()
constexpr bool v8::internal::compiler::turboshaft::OptionalOpIndex::has_value () const [inline], [constexpr]
Definition at line 183 of file index.h.
{ return valid(); }
References valid().
Referenced by v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Foreach(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::turboshaft::Zip< Iterables >::IsEnd(), v8::internal::compiler::RiscvOperandGenerator::IsIntegerConstant(), v8::internal::compiler::turboshaft::JSStackCheckOp::JSStackCheckOp(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::turboshaft::JSStackCheckOp::New(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), value(), and v8::internal::compiler::turboshaft::OptionalV< T >::value().
hash()
uint32_t v8::internal::compiler::turboshaft::OptionalOpIndex::hash () const [inline]
Definition at line 181 of file index.h.
{ return OpIndex::hash(); }
References v8::internal::compiler::turboshaft::OpIndex::hash().
Referenced by v8::internal::compiler::turboshaft::hash_value().
Nullopt()
static constexpr OptionalOpIndex v8::internal::compiler::turboshaft::OptionalOpIndex::Nullopt () [inline], [static], [constexpr]
Definition at line 177 of file index.h.
                                             {
    return OptionalOpIndex{OpIndex::Invalid()};
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
OpIndex() [1/3]
constexpr v8::internal::compiler::turboshaft::OpIndex::OpIndex [inline], [constexpr]
Definition at line 59 of file index.h.
: offset_(std::numeric_limits<uint32_t>::max()) {}
OpIndex() [2/3]
template<typename T , typename C >
v8::internal::compiler::turboshaft::OpIndex::OpIndex (typename T , typename C) [inline]
Definition at line 61 of file index.h.
                                 { // NOLINT(runtime/explicit)
    static_assert(base::tmp::lazy_false<T>::value,
                  "Cannot initialize OpIndex from ConstOrV<>. Did you forget "
                  "to resolve() it in the assembler?");
  }
OpIndex() [3/3]
constexpr v8::internal::compiler::turboshaft::OpIndex::OpIndex [inline], [explicit], [constexpr]
Definition at line 44 of file index.h.
                                              : offset_(offset) {
    SLOW_DCHECK(CheckInvariants());
  }
Referenced by value(), and value_or_invalid().
valid()
constexpr bool v8::internal::compiler::turboshaft::OpIndex::valid [inline], [constexpr]
Definition at line 92 of file index.h.
{ return *this != Invalid(); }
Referenced by v8::internal::compiler::turboshaft::AtomicRMWOp::AtomicRMWOp(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::AtomicWord32PairOp(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeBigIntToInt64(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeTaggedToFloat64(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeTaggedToInt32(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::turboshaft::CallOp::CallOp(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime(), v8::internal::compiler::turboshaft::CheckMapsOp::CheckMapsOp(), v8::internal::compiler::turboshaft::CompareMapsOp::CompareMapsOp(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), has_value(), v8::internal::compiler::InstructionSelector::MarkPairProjectionsAsWord32(), v8::internal::compiler::turboshaft::AtomicRMWOp::New(), v8::internal::compiler::turboshaft::CallOp::New(), v8::internal::compiler::turboshaft::CompareMapsOp::New(), v8::internal::compiler::turboshaft::CheckMapsOp::New(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), v8::internal::compiler::TryMatchInt32MulWithOverflow(), v8::internal::compiler::TryMatchInt32OpWithOverflow(), v8::internal::compiler::TryMatchInt64OpWithOverflow(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift().
value()
constexpr OpIndex v8::internal::compiler::turboshaft::OptionalOpIndex::value () const [inline], [constexpr]
Definition at line 184 of file index.h.
                                  {
    DCHECK(has_value());
    return OpIndex(*this);
  }
References v8::internal::DCHECK(), has_value(), and OpIndex().
Referenced by v8::internal::compiler::turboshaft::AtomicRMWOp::AtomicRMWOp(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeBigIntToInt64(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeTaggedToFloat64(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeTaggedToInt32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::RiscvOperandGenerator::IsIntegerConstant(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::InstructionSelector::MarkPairProjectionsAsWord32(), v8::internal::compiler::turboshaft::LoadOp::PrintInputs(), v8::internal::compiler::turboshaft::StoreOp::PrintInputs(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), v8::internal::compiler::TryMatchInt32MulWithOverflow(), v8::internal::compiler::TryMatchInt32OpWithOverflow(), v8::internal::compiler::TryMatchInt64OpWithOverflow(), v8::internal::compiler::turboshaft::OptionalV< T >::value(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift().
value_or_invalid()
constexpr OpIndex v8::internal::compiler::turboshaft::OptionalOpIndex::value_or_invalid () const [inline], [constexpr]
Definition at line 188 of file index.h.
{ return OpIndex(*this); }
References OpIndex().
Referenced by v8::internal::compiler::turboshaft::operator<<(), and v8::internal::compiler::turboshaft::OptionalV< T >::value_or_invalid().
Friends And Related Function Documentation
AbslHashValue
template<typename H >
H AbslHashValue (H h, const OptionalOpIndex & idx) [friend]
Definition at line 191 of file index.h.
                                                          {
    return H::combine(std::move(h), idx.offset_);
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/index.h