v8::debug::Coverage::BlockData Class Reference
#include <debug-interface.h>
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (BlockData)
int StartOffset () const
int EndOffset () const
uint32_t Count () const
Private Member Functions
BlockData (i::CoverageBlock *block, std::shared_ptr< i::Coverage > coverage)
Private Attributes
i::CoverageBlock * block_
std::shared_ptr< i::Coverage > coverage_
Friends
class v8::debug::Coverage::FunctionData
Detailed Description
Definition at line 401 of file debug-interface.h.
Constructor & Destructor Documentation
BlockData()
v8::debug::Coverage::BlockData::BlockData (i::CoverageBlock * block, std::shared_ptr< i::Coverage > coverage) [inline], [explicit], [private]
Definition at line 410 of file debug-interface.h.
        : block_(block), coverage_(std::move(coverage)) {}
Member Function Documentation
Count()
uint32_t v8::debug::Coverage::BlockData::Count () const
Definition at line 1334 of file debug-interface.cc.
{ return block_->count; }
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
EndOffset()
int v8::debug::Coverage::BlockData::EndOffset () const
Definition at line 1332 of file debug-interface.cc.
{ return block_->end; }
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::debug::Coverage::BlockData::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (BlockData)
StartOffset()
int v8::debug::Coverage::BlockData::StartOffset () const
Definition at line 1330 of file debug-interface.cc.
{ return block_->start; }
References block_, and v8::internal::CoverageBlock::start.
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
Friends And Related Function Documentation
v8::debug::Coverage::FunctionData
friend class v8::debug::Coverage::FunctionData [friend]
Definition at line 417 of file debug-interface.h.
Member Data Documentation
block_
i::CoverageBlock* v8::debug::Coverage::BlockData::block_ [private]
Definition at line 414 of file debug-interface.h.
Referenced by StartOffset().
coverage_
std::shared_ptr<i::Coverage> v8::debug::Coverage::BlockData::coverage_ [private]
Definition at line 415 of file debug-interface.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc