v8::internal::SeqString Class Reference
#include <string.h>
Classes
struct DataAndPaddingSizes
Public Member Functions
DataAndPaddingSizes GetDataAndPaddingSizes () const
void ClearPadding ()
Static Public Member Functions
static V8_WARN_UNUSED_RESULT Handle< String > Truncate (Isolate *isolate, Handle< SeqString > string, uint32_t new_length)
Additional Inherited Members
Detailed Description
Definition at line 830 of file string.h.
Member Function Documentation
ClearPadding()
void v8::internal::SeqString::ClearPadding ()
Definition at line 1993 of file string.cc.
                             {
  DataAndPaddingSizes sz = GetDataAndPaddingSizes();
  DCHECK_EQ(sz.data_size + sz.padding_size, Size());
  if (sz.padding_size == 0) return;
  memset(reinterpret_cast<void*>(address() + sz.data_size), 0, sz.padding_size);
}
References v8::internal::SeqString::DataAndPaddingSizes::data_size, DCHECK_EQ, and v8::internal::SeqString::DataAndPaddingSizes::padding_size.
GetDataAndPaddingSizes()
SeqString::DataAndPaddingSizes v8::internal::SeqString::GetDataAndPaddingSizes () const
Definition at line 1959 of file string.cc.
                                                                     {
  if (IsSeqOneByteString(this)) {
    return Cast<SeqOneByteString>(this)->GetDataAndPaddingSizes();
  }
  return Cast<SeqTwoByteString>(this)->GetDataAndPaddingSizes();
}
Truncate()
Handle< String > v8::internal::SeqString::Truncate (Isolate * isolate, Handle< SeqString > string, uint32_t new_length) [static]
Definition at line 1919 of file string.cc.
                                                        {
  if (new_length == 0) return isolate->factory()->empty_string();
  int new_size, old_size;
  uint32_t old_length = string->length();
  if (old_length <= new_length) return string;
  if (IsSeqOneByteString(*string)) {
    old_size = SeqOneByteString::SizeFor(old_length);
    new_size = SeqOneByteString::SizeFor(new_length);
  } else {
    DCHECK(IsSeqTwoByteString(*string));
    old_size = SeqTwoByteString::SizeFor(old_length);
    new_size = SeqTwoByteString::SizeFor(new_length);
  }
#if DEBUG
  Address start_of_string = (*string).address();
  DCHECK(IsAligned(start_of_string, kObjectAlignment));
  DCHECK(IsAligned(start_of_string + new_size, kObjectAlignment));
#endif
  Heap* heap = isolate->heap();
  if (!heap->IsLargeObject(*string)) {
    // Sizes are pointer size aligned, so that we can use filler objects
    // that are a multiple of pointer size.
    // No slot invalidation needed since this method is only used on freshly
    // allocated strings.
    heap->NotifyObjectSizeChange(*string, old_size, new_size,
                                 ClearRecordedSlots::kNo);
  }
  // We are storing the new length using release store after creating a filler
  // for the left-over space to avoid races with the sweeper thread.
  string->set_length(new_length, kReleaseStore);
  string->ClearPadding();
  return string;
}
References DCHECK, v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), IsAligned(), v8::internal::kObjectAlignment, v8::kReleaseStore, and v8::internal::string.
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::LocaleConvertCase(), and v8::internal::IncrementalStringBuilder::ShrinkCurrentPart().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string.cc