cppgc::internal::StatsCollector::AllocationObserver Class Reference
#include <stats-collector.h>
Public Member Functions
virtual void AllocatedObjectSizeIncreased (size_t)
virtual void AllocatedObjectSizeDecreased (size_t)
virtual void ResetAllocatedObjectSize (size_t)
virtual void AllocatedSizeIncreased (size_t)
virtual void AllocatedSizeDecreased (size_t)
Detailed Description
Definition at line 244 of file stats-collector.h.
Member Function Documentation
AllocatedObjectSizeDecreased()
virtual void cppgc::internal::StatsCollector::AllocationObserver::AllocatedObjectSizeDecreased (size_t) [inline], [virtual]
Reimplemented in cppgc::internal::HeapGrowing::HeapGrowingImpl, v8::internal::CppHeap, v8::internal::MinorGCHeapGrowing, and cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl.
Definition at line 254 of file stats-collector.h.
{}
Referenced by cppgc::internal::StatsCollector::AllocatedObjectSizeSafepointImpl().
AllocatedObjectSizeIncreased()
virtual void cppgc::internal::StatsCollector::AllocationObserver::AllocatedObjectSizeIncreased (size_t) [inline], [virtual]
Reimplemented in cppgc::internal::HeapGrowing::HeapGrowingImpl, v8::internal::CppHeap, v8::internal::MinorGCHeapGrowing, cppgc::internal::MarkerBase::IncrementalMarkingAllocationObserver, and cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl.
Definition at line 253 of file stats-collector.h.
{}
Referenced by cppgc::internal::StatsCollector::AllocatedObjectSizeSafepointImpl().
AllocatedSizeDecreased()
virtual void cppgc::internal::StatsCollector::AllocationObserver::AllocatedSizeDecreased (size_t) [inline], [virtual]
Reimplemented in cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl.
Definition at line 267 of file stats-collector.h.
{}
Referenced by cppgc::internal::StatsCollector::NotifyFreedMemory().
AllocatedSizeIncreased()
virtual void cppgc::internal::StatsCollector::AllocationObserver::AllocatedSizeIncreased (size_t) [inline], [virtual]
Reimplemented in cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl.
Definition at line 266 of file stats-collector.h.
{}
Referenced by cppgc::internal::StatsCollector::NotifyAllocatedMemory().
ResetAllocatedObjectSize()
virtual void cppgc::internal::StatsCollector::AllocationObserver::ResetAllocatedObjectSize (size_t) [inline], [virtual]
Reimplemented in cppgc::internal::HeapGrowing::HeapGrowingImpl, v8::internal::CppHeap, cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl, and v8::internal::MinorGCHeapGrowing.
Definition at line 260 of file stats-collector.h.
{}
Referenced by cppgc::internal::StatsCollector::NotifyMarkingCompleted().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/stats-collector.h