v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror Class Reference
Public Member Functions
Response buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions &wrapOptions, std::unique_ptr< RemoteObject > *result) const override
Response buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::DictionaryValue > *result) const override
Static Public Member Functions
static std::unique_ptr< LocationMirror > create (v8::Local< v8::Function > function)
static std::unique_ptr< LocationMirror > createForGenerator (v8::Local< v8::Object > value)
Private Member Functions
LocationMirror (v8::Local< v8::Object > value, int scriptId, int lineNumber, int columnNumber)
Static Private Member Functions
static std::unique_ptr< LocationMirror > create (v8::Local< v8::Object > value, int scriptId, int lineNumber, int columnNumber)
Private Attributes
int m_scriptId
int m_lineNumber
int m_columnNumber
Detailed Description
Definition at line 811 of file value-mirror.cc.
Constructor & Destructor Documentation
LocationMirror()
v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::LocationMirror (v8::Local< v8::Object > value, int scriptId, int lineNumber, int columnNumber) [inline], [private]
Definition at line 880 of file value-mirror.cc.
      : ValueMirrorBase(v8::Isolate::GetCurrent(), value),
        m_scriptId(scriptId),
        m_lineNumber(lineNumber),
        m_columnNumber(columnNumber) {}
Member Function Documentation
buildDeepSerializedValue()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::DictionaryValue > * result) const [inline], [override], [virtual]
Implements v8_inspector::ValueMirror.
Definition at line 850 of file value-mirror.cc.
                                                                     {
    bool isKnown;
    v8::Local<v8::Value> value = v8Value(v8::Isolate::GetCurrent());
    *result = duplicateTracker.LinkExistingOrCreate(value, &isKnown);
    if (isKnown) {
      return Response::Success();
    }
    (*result)->setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Object);
    return Response::Success();
  }
References v8::Isolate::GetCurrent(), v8_inspector::V8SerializationDuplicateTracker::LinkExistingOrCreate(), v8::internal::compiler::Object, v8::base::internal::result, and v8::internal::value.
buildRemoteObject()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions & wrapOptions, std::unique_ptr< RemoteObject > * result) const [inline], [override]
Definition at line 834 of file value-mirror.cc.
                                                          {
    auto location = protocol::DictionaryValue::create();
    location->setString("scriptId", String16::fromInteger(m_scriptId));
    location->setInteger("lineNumber", m_lineNumber);
    location->setInteger("columnNumber", m_columnNumber);
    *result = RemoteObject::create()
                  .setType(RemoteObject::TypeEnum::Object)
                  .setSubtype("internal#location")
                  .setDescription("Object")
                  .setValue(std::move(location))
                  .build();
    return Response::Success();
  }
References v8_inspector::String16::fromInteger(), v8::internal::compiler::Object, and v8::base::internal::result.
create() [1/2]
static std::unique_ptr<LocationMirror> v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::create (v8::Local< v8::Function > function) [inline], [static]
Definition at line 813 of file value-mirror.cc.
                                    {
    return create(function, function->ScriptId(),
                  function->GetScriptLineNumber(),
                  function->GetScriptColumnNumber());
  }
create() [2/2]
static std::unique_ptr<LocationMirror> v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::create (v8::Local< v8::Object > value, int scriptId, int lineNumber, int columnNumber) [inline], [static], [private]
Definition at line 868 of file value-mirror.cc.
                                                                  {
    if (scriptId == v8::UnboundScript::kNoScriptId) return nullptr;
    if (lineNumber == v8::Function::kLineOffsetNotFound ||
        columnNumber == v8::Function::kLineOffsetNotFound) {
      return nullptr;
    }
    return std::unique_ptr<LocationMirror>(
        new LocationMirror(value, scriptId, lineNumber, columnNumber));
  }
References v8::Function::kLineOffsetNotFound, v8::UnboundScript::kNoScriptId, and v8::internal::value.
createForGenerator()
static std::unique_ptr<LocationMirror> v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::createForGenerator (v8::Local< v8::Object > value) [inline], [static]
Definition at line 819 of file value-mirror.cc.
                               {
    v8::Local<v8::debug::GeneratorObject> generatorObject =
        v8::debug::GeneratorObject::Cast(value);
    if (!generatorObject->IsSuspended()) {
      return create(generatorObject->Function());
    }
    v8::Local<v8::debug::Script> script;
    if (!generatorObject->Script().ToLocal(&script)) return nullptr;
    v8::debug::Location suspendedLocation =
        generatorObject->SuspendedLocation();
    return create(value, script->Id(), suspendedLocation.GetLineNumber(),
                  suspendedLocation.GetColumnNumber());
  }
References v8::debug::GeneratorObject::Cast(), v8::debug::Location::GetColumnNumber(), v8::debug::Location::GetLineNumber(), v8::internal::script, and v8::internal::value.
Member Data Documentation
m_columnNumber
int v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::m_columnNumber [private]
Definition at line 889 of file value-mirror.cc.
m_lineNumber
int v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::m_lineNumber [private]
Definition at line 888 of file value-mirror.cc.
m_scriptId
int v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::m_scriptId [private]
Definition at line 887 of file value-mirror.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/value-mirror.cc