v8::internal::PreParserIdentifier Class Reference
#include <preparser.h>
Public Member Functions
PreParserIdentifier ()
bool IsNull () const
bool IsEval () const
bool IsAsync () const
bool IsArguments () const
bool IsEvalOrArguments () const
bool IsConstructor () const
bool IsPrivateName () const
Static Public Member Functions
static PreParserIdentifier Default ()
static PreParserIdentifier Null ()
static PreParserIdentifier Eval ()
static PreParserIdentifier Arguments ()
static PreParserIdentifier Constructor ()
static PreParserIdentifier Async ()
static PreParserIdentifier PrivateName ()
Private Types
enum Type : uint8_t {
kNullIdentifier
, kUnknownIdentifier
, kEvalIdentifier
, kArgumentsIdentifier
,
kConstructorIdentifier
, kAsyncIdentifier
, kPrivateNameIdentifier
 }
Private Member Functions
PreParserIdentifier (Type type)
Private Attributes
const AstRawString * string_
Type type_
Friends
class PreParserExpression
class PreParser
Detailed Description
Definition at line 29 of file preparser.h.
Member Enumeration Documentation
Type
enum v8::internal::PreParserIdentifier::Type : uint8_t [private]
Enumerator
kNullIdentifier
kUnknownIdentifier
kEvalIdentifier
kArgumentsIdentifier
kConstructorIdentifier
kAsyncIdentifier
kPrivateNameIdentifier
Definition at line 65 of file preparser.h.
            : uint8_t {
    kNullIdentifier,
    kUnknownIdentifier,
    kEvalIdentifier,
    kArgumentsIdentifier,
    kConstructorIdentifier,
    kAsyncIdentifier,
    kPrivateNameIdentifier
  };
Constructor & Destructor Documentation
PreParserIdentifier() [1/2]
v8::internal::PreParserIdentifier::PreParserIdentifier () [inline]
Definition at line 31 of file preparser.h.
: type_(kUnknownIdentifier) {}
Referenced by Arguments(), Async(), Constructor(), Default(), Eval(), Null(), and PrivateName().
PreParserIdentifier() [2/2]
v8::internal::PreParserIdentifier::PreParserIdentifier (Type type) [inline], [explicit], [private]
Definition at line 75 of file preparser.h.
: string_(nullptr), type_(type) {}
Member Function Documentation
Arguments()
static PreParserIdentifier v8::internal::PreParserIdentifier::Arguments () [inline], [static]
Definition at line 41 of file preparser.h.
                                         {
    return PreParserIdentifier(kArgumentsIdentifier);
  }
References kArgumentsIdentifier, and PreParserIdentifier().
Referenced by v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper().
Async()
static PreParserIdentifier v8::internal::PreParserIdentifier::Async () [inline], [static]
Definition at line 47 of file preparser.h.
                                     {
    return PreParserIdentifier(kAsyncIdentifier);
  }
References kAsyncIdentifier, and PreParserIdentifier().
Referenced by v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper().
Constructor()
static PreParserIdentifier v8::internal::PreParserIdentifier::Constructor () [inline], [static]
Definition at line 44 of file preparser.h.
                                           {
    return PreParserIdentifier(kConstructorIdentifier);
  }
References kConstructorIdentifier, and PreParserIdentifier().
Referenced by v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper().
Default()
static PreParserIdentifier v8::internal::PreParserIdentifier::Default () [inline], [static]
Definition at line 32 of file preparser.h.
                                       {
    return PreParserIdentifier(kUnknownIdentifier);
  }
References kUnknownIdentifier, and PreParserIdentifier().
Referenced by v8::internal::PreParser::EmptyIdentifierString(), v8::internal::PreParser::GetBigIntAsSymbol(), v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper(), v8::internal::PreParser::GetNextSymbol(), v8::internal::PreParser::GetNumberAsSymbol(), and v8::internal::PreParser::GetSymbol().
Eval()
static PreParserIdentifier v8::internal::PreParserIdentifier::Eval () [inline], [static]
Definition at line 38 of file preparser.h.
                                    {
    return PreParserIdentifier(kEvalIdentifier);
  }
References kEvalIdentifier, and PreParserIdentifier().
Referenced by v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper().
IsArguments()
bool v8::internal::PreParserIdentifier::IsArguments () const [inline]
Definition at line 56 of file preparser.h.
{ return type_ == kArgumentsIdentifier; }
References kArgumentsIdentifier, and type_.
Referenced by v8::internal::PreParser::IsArguments().
IsAsync()
bool v8::internal::PreParserIdentifier::IsAsync () const [inline]
Definition at line 55 of file preparser.h.
{ return type_ == kAsyncIdentifier; }
References kAsyncIdentifier, and type_.
Referenced by v8::internal::PreParser::IsAsync().
IsConstructor()
bool v8::internal::PreParserIdentifier::IsConstructor () const [inline]
Definition at line 61 of file preparser.h.
{ return type_ == kConstructorIdentifier; }
References kConstructorIdentifier, and type_.
Referenced by v8::internal::PreParser::IsConstructor().
IsEval()
bool v8::internal::PreParserIdentifier::IsEval () const [inline]
Definition at line 54 of file preparser.h.
{ return type_ == kEvalIdentifier; }
References kEvalIdentifier, and type_.
Referenced by v8::internal::PreParser::IsEval(), and v8::internal::PreParserFactory::NewCall().
IsEvalOrArguments()
bool v8::internal::PreParserIdentifier::IsEvalOrArguments () const [inline]
Definition at line 57 of file preparser.h.
                                 {
    static_assert(kEvalIdentifier + 1 == kArgumentsIdentifier);
    return base::IsInRange(type_, kEvalIdentifier, kArgumentsIdentifier);
  }
References kArgumentsIdentifier, kEvalIdentifier, and type_.
Referenced by v8::internal::PreParser::IsEvalOrArguments().
IsNull()
bool v8::internal::PreParserIdentifier::IsNull () const [inline]
Definition at line 53 of file preparser.h.
{ return type_ == kNullIdentifier; }
References kNullIdentifier, and type_.
IsPrivateName()
bool v8::internal::PreParserIdentifier::IsPrivateName () const [inline]
Definition at line 62 of file preparser.h.
{ return type_ == kPrivateNameIdentifier; }
References kPrivateNameIdentifier, and type_.
Null()
static PreParserIdentifier v8::internal::PreParserIdentifier::Null () [inline], [static]
Definition at line 35 of file preparser.h.
                                    {
    return PreParserIdentifier(kNullIdentifier);
  }
References kNullIdentifier, and PreParserIdentifier().
Referenced by v8::internal::PreParser::NullIdentifier().
PrivateName()
static PreParserIdentifier v8::internal::PreParserIdentifier::PrivateName () [inline], [static]
Definition at line 50 of file preparser.h.
                                           {
    return PreParserIdentifier(kPrivateNameIdentifier);
  }
References kPrivateNameIdentifier, and PreParserIdentifier().
Referenced by v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper().
Friends And Related Function Documentation
PreParser
friend class PreParser [friend]
Definition at line 80 of file preparser.h.
PreParserExpression
friend class PreParserExpression [friend]
Definition at line 79 of file preparser.h.
Member Data Documentation
string_
const AstRawString* v8::internal::PreParserIdentifier::string_ [private]
Definition at line 76 of file preparser.h.
Referenced by v8::internal::PreParser::DeclareCatchVariableName(), v8::internal::PreParser::DeclareClass(), v8::internal::PreParser::DeclareFunction(), v8::internal::PreParser::DeclareFunctionNameVar(), v8::internal::PreParser::DeclarePrivateClassMember(), v8::internal::PreParser::GetIdentifier(), v8::internal::PreParser::GetRawNameFromIdentifier(), v8::internal::PreParser::IdentifierEquals(), v8::internal::PreParser::IsEmptyIdentifier(), v8::internal::PreParser::ParseFunctionLiteral(), and v8::internal::PreParser::PreParserIdentifierToAstRawString().
type_
Type v8::internal::PreParserIdentifier::type_ [private]
Definition at line 78 of file preparser.h.
Referenced by IsArguments(), IsAsync(), IsConstructor(), IsEval(), IsEvalOrArguments(), IsNull(), and IsPrivateName().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparser.h