v8::internal::Assignment Class Reference
#include <ast.h>
Public Member Functions
Token::Value op () const
Expression * target () const
Expression * value () const
LookupHoistingMode lookup_hoisting_mode () const
void set_lookup_hoisting_mode (LookupHoistingMode mode)
Protected Member Functions
Assignment (NodeType type, Token::Value op, Expression *target, Expression *value, int pos)
Private Types
using TokenField = Expression::NextBitField< Token::Value, 7 >
using LookupHoistingModeField = TokenField::Next< bool, 1 >
Private Attributes
friend Zone
Expression * target_
Expression * value_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 2166 of file ast.h.
Member Typedef Documentation
LookupHoistingModeField
using v8::internal::Assignment::LookupHoistingModeField = TokenField::Next<bool, 1> [private]
Definition at line 2193 of file ast.h.
TokenField
using v8::internal::Assignment::TokenField = Expression::NextBitField<Token::Value, 7> [private]
Definition at line 2192 of file ast.h.
Constructor & Destructor Documentation
Assignment()
v8::internal::Assignment::Assignment (NodeType type, Token::Value op, Expression * target, Expression * value, int pos) [protected]
Definition at line 181 of file ast.cc.
    : Expression(pos, node_type), target_(target), value_(value) {
  bit_field_ |= TokenField::encode(op);
}
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::encode(), and op().
Member Function Documentation
lookup_hoisting_mode()
LookupHoistingMode v8::internal::Assignment::lookup_hoisting_mode () const [inline]
Definition at line 2175 of file ast.h.
                                                  {
    return static_cast<LookupHoistingMode>(
        LookupHoistingModeField::decode(bit_field_));
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
op()
Token::Value v8::internal::Assignment::op () const [inline]
Definition at line 2168 of file ast.h.
{ return TokenField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by Assignment(), and v8::internal::interpreter::BytecodeGenerator::GetDestructuringDefaultValue().
set_lookup_hoisting_mode()
void v8::internal::Assignment::set_lookup_hoisting_mode (LookupHoistingMode mode) [inline]
Definition at line 2179 of file ast.h.
                                                         {
    bit_field_ =
        LookupHoistingModeField::update(bit_field_, static_cast<bool>(mode));
  }
References v8::internal::AstNode::bit_field_, mode(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
target()
Expression* v8::internal::Assignment::target () const [inline]
Definition at line 2169 of file ast.h.
{ return target_; }
References target_.
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), and v8::internal::interpreter::BytecodeGenerator::GetDestructuringDefaultValue().
value()
Expression* v8::internal::Assignment::value () const [inline]
Definition at line 2170 of file ast.h.
{ return value_; }
References value_.
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), v8::internal::interpreter::BytecodeGenerator::GetDestructuringDefaultValue(), and v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2189 of file ast.h.
Member Data Documentation
target_
Expression* v8::internal::Assignment::target_ [private]
Definition at line 2195 of file ast.h.
Referenced by target().
value_
Expression* v8::internal::Assignment::value_ [private]
Definition at line 2196 of file ast.h.
Referenced by value().
Zone
friend v8::internal::Assignment::Zone [private]
Definition at line 2190 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc