v8::internal::SmallStringOptimizedAllocator< kInlineSize > Class Template Reference
#include <string-stream.h>
Public Types
using SmallVector = base::SmallVector< char, kInlineSize >
Public Member Functions
SmallStringOptimizedAllocator (SmallVector *vector) V8_NOEXCEPT
char * allocate (unsigned bytes) override
char * grow (unsigned *bytes) override
Private Attributes
SmallVector * vector_
Detailed Description
template<std::size_t kInlineSize>
class v8::internal::SmallStringOptimizedAllocator< kInlineSize >
Definition at line 64 of file string-stream.h.
Member Typedef Documentation
SmallVector
template<std::size_t kInlineSize>
using v8::internal::SmallStringOptimizedAllocator< kInlineSize >::SmallVector = base::SmallVector<char, kInlineSize>
Definition at line 66 of file string-stream.h.
Constructor & Destructor Documentation
SmallStringOptimizedAllocator()
template<std::size_t kInlineSize>
v8::internal::SmallStringOptimizedAllocator< kInlineSize >::SmallStringOptimizedAllocator (SmallVector * vector) [inline], [explicit]
Definition at line 68 of file string-stream.h.
      : vector_(vector) {}
Member Function Documentation
allocate()
template<std::size_t kInlineSize>
char* v8::internal::SmallStringOptimizedAllocator< kInlineSize >::allocate (unsigned bytes) [inline], [override], [virtual]
Implements v8::internal::StringAllocator.
Definition at line 71 of file string-stream.h.
                                          {
    vector_->resize(bytes);
    return vector_->data();
  }
References v8::base::SmallVector< T, kSize, Allocator >::data(), v8::base::SmallVector< T, kSize, Allocator >::resize(), and v8::internal::SmallStringOptimizedAllocator< kInlineSize >::vector_.
grow()
template<std::size_t kInlineSize>
char* v8::internal::SmallStringOptimizedAllocator< kInlineSize >::grow (unsigned * bytes) [inline], [override], [virtual]
Implements v8::internal::StringAllocator.
Definition at line 76 of file string-stream.h.
                                       {
    unsigned new_bytes = *bytes * 2;
    // Check for overflow.
    if (new_bytes <= *bytes) {
      return vector_->data();
    }
    vector_->resize(new_bytes);
    *bytes = new_bytes;
    return vector_->data();
  }
References v8::base::SmallVector< T, kSize, Allocator >::data(), v8::base::SmallVector< T, kSize, Allocator >::resize(), and v8::internal::SmallStringOptimizedAllocator< kInlineSize >::vector_.
Member Data Documentation
vector_
template<std::size_t kInlineSize>
SmallVector* v8::internal::SmallStringOptimizedAllocator< kInlineSize >::vector_ [private]
Definition at line 88 of file string-stream.h.
Referenced by v8::internal::SmallStringOptimizedAllocator< kInlineSize >::allocate(), and v8::internal::SmallStringOptimizedAllocator< kInlineSize >::grow().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/strings/string-stream.h