v8::internal::DeletePropertyBaseAssembler Class Reference
Public Member Functions
DeletePropertyBaseAssembler (compiler::CodeAssemblerState *state)
void DictionarySpecificDelete (TNode< JSReceiver > receiver, TNode< NameDictionary > properties, TNode< IntPtrT > key_index, TNode< Context > context)
void DictionarySpecificDelete (TNode< JSReceiver > receiver, TNode< SwissNameDictionary > properties, TNode< IntPtrT > key_index, TNode< Context > context)
template<typename Dictionary >
void DeleteDictionaryProperty (TNode< JSReceiver > receiver, TNode< Dictionary > properties, TNode< Name > name, TNode< Context > context, Label *dont_delete, Label *notfound)
Additional Inherited Members
Detailed Description
Definition at line 815 of file builtins-internal-gen.cc.
Constructor & Destructor Documentation
DeletePropertyBaseAssembler()
v8::internal::DeletePropertyBaseAssembler::DeletePropertyBaseAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 817 of file builtins-internal-gen.cc.
      : AccessorAssembler(state) {}
Member Function Documentation
DeleteDictionaryProperty()
template<typename Dictionary >
void v8::internal::DeletePropertyBaseAssembler::DeleteDictionaryProperty (TNode< JSReceiver > receiver, TNode< Dictionary > properties, TNode< Name > name, TNode< Context > context, Label * dont_delete, Label * notfound) [inline]
Definition at line 874 of file builtins-internal-gen.cc.
                                                 {
    TVARIABLE(IntPtrT, var_name_index);
    Label dictionary_found(this, &var_name_index);
    NameDictionaryLookup<Dictionary>(properties, name, &dictionary_found,
                                     &var_name_index, notfound);
    BIND(&dictionary_found);
    TNode<IntPtrT> key_index = var_name_index.value();
    TNode<Uint32T> details = LoadDetailsByKeyIndex(properties, key_index);
    GotoIf(IsSetWord32(details, PropertyDetails::kAttributesDontDeleteMask),
           dont_delete);
    DictionarySpecificDelete(receiver, properties, key_index, context);
    Return(TrueConstant());
  }
References DictionarySpecificDelete(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IsSetWord32(), v8::internal::PropertyDetails::kAttributesDontDeleteMask, v8::internal::CodeStubAssembler::LoadDetailsByKeyIndex(), v8::internal::name, and v8::internal::compiler::CodeAssembler::Return().
DictionarySpecificDelete() [1/2]
void v8::internal::DeletePropertyBaseAssembler::DictionarySpecificDelete (TNode< JSReceiver > receiver, TNode< NameDictionary > properties, TNode< IntPtrT > key_index, TNode< Context > context) [inline]
Definition at line 820 of file builtins-internal-gen.cc.
                                                        {
    // Overwrite the entry itself (see NameDictionary::SetEntry).
    TNode<Hole> filler = TheHoleConstant();
    DCHECK(RootsTable::IsImmortalImmovable(RootIndex::kTheHoleValue));
    StoreFixedArrayElement(properties, key_index, filler, SKIP_WRITE_BARRIER);
    StoreValueByKeyIndex<NameDictionary>(properties, key_index, filler,
                                         SKIP_WRITE_BARRIER);
    StoreDetailsByKeyIndex<NameDictionary>(properties, key_index,
                                           SmiConstant(0));
    // Update bookkeeping information (see NameDictionary::ElementRemoved).
    TNode<Smi> nof = GetNumberOfElements<NameDictionary>(properties);
    TNode<Smi> new_nof = SmiSub(nof, SmiConstant(1));
    SetNumberOfElements<NameDictionary>(properties, new_nof);
    TNode<Smi> num_deleted =
        GetNumberOfDeletedElements<NameDictionary>(properties);
    TNode<Smi> new_deleted = SmiAdd(num_deleted, SmiConstant(1));
    SetNumberOfDeletedElements<NameDictionary>(properties, new_deleted);
    // Shrink the dictionary if necessary (see NameDictionary::Shrink).
    Label shrinking_done(this);
    TNode<Smi> capacity = GetCapacity<NameDictionary>(properties);
    GotoIf(SmiGreaterThan(new_nof, SmiShr(capacity, 2)), &shrinking_done);
    GotoIf(SmiLessThan(new_nof, SmiConstant(16)), &shrinking_done);
    TNode<NameDictionary> new_properties =
        CAST(CallRuntime(Runtime::kShrinkNameDictionary, context, properties));
    StoreJSReceiverPropertiesOrHash(receiver, new_properties);
    Goto(&shrinking_done);
    BIND(&shrinking_done);
  }
References v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::DCHECK(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::RootsTable::IsImmortalImmovable(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiShr(), and v8::internal::CodeStubAssembler::StoreFixedArrayElement().
Referenced by DeleteDictionaryProperty().
DictionarySpecificDelete() [2/2]
void v8::internal::DeletePropertyBaseAssembler::DictionarySpecificDelete (TNode< JSReceiver > receiver, TNode< SwissNameDictionary > properties, TNode< IntPtrT > key_index, TNode< Context > context) [inline]
Definition at line 857 of file builtins-internal-gen.cc.
                                                        {
    Label shrunk(this), done(this);
    TVARIABLE(SwissNameDictionary, shrunk_table);
    SwissNameDictionaryDelete(properties, key_index, &shrunk, &shrunk_table);
    Goto(&done);
    BIND(&shrunk);
    StoreJSReceiverPropertiesOrHash(receiver, shrunk_table.value());
    Goto(&done);
    BIND(&done);
  }
References v8::internal::compiler::CodeAssembler::Goto().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-internal-gen.cc