v8::internal::MaybeDirectHandle< T > Class Template Reference
#include <maybe-handles.h>
Public Member Functions
MaybeDirectHandle ()=default
MaybeDirectHandle (NullMaybeHandleType)
MaybeDirectHandle (Tagged< T > object, Isolate *isolate)
MaybeDirectHandle (Tagged< T > object, LocalIsolate *isolate)
MaybeDirectHandle (Tagged< T > object, LocalHeap *local_heap)
template<typename S >
MaybeDirectHandle (DirectHandle< S > handle) requires(is_subtype_v< S
void Check () const
DirectHandle< T > ToHandleChecked () const
template<typename S >
V8_WARN_UNUSED_RESULT bool ToHandle (DirectHandle< S > *out) const
bool is_null () const
Public Attributes
T __pad0__: handle_(handle.handle_) {} template <typename S> inline MaybeDirectHandle(IndirectHandle<S> handle) requires(is_subtype_v<S
T T: handle_(handle) {} template <typename S> inline MaybeDirectHandle(MaybeDirectHandle<S> handle) requires(is_subtype_v<S
Private Attributes
MaybeIndirectHandle< T > handle_
Friends
template<typename >
class DirectHandle
template<typename >
class MaybeDirectHandle
template<typename To , typename From >
MaybeDirectHandle< To > UncheckedCast (MaybeDirectHandle< From > value)
template<typename U >
MaybeIndirectHandle< U > indirect_handle (MaybeDirectHandle< U >, Isolate *)
template<typename U >
MaybeIndirectHandle< U > indirect_handle (MaybeDirectHandle< U >, LocalIsolate *)
Detailed Description
template<typename T>
class v8::internal::MaybeDirectHandle< T >
Definition at line 241 of file maybe-handles.h.
Constructor & Destructor Documentation
MaybeDirectHandle() [1/6]
template<typename T >
v8::internal::MaybeDirectHandle< T >::MaybeDirectHandle () [inline], [default]
MaybeDirectHandle() [2/6]
template<typename T >
v8::internal::MaybeDirectHandle< T >::MaybeDirectHandle (NullMaybeHandleType) [inline]
Definition at line 244 of file maybe-handles.h.
{}
MaybeDirectHandle() [3/6]
template<typename T >
v8::internal::MaybeDirectHandle< T >::MaybeDirectHandle (Tagged< T > object, Isolate * isolate) [inline]
Definition at line 246 of file maybe-handles.h.
      : handle_(object, isolate) {}
MaybeDirectHandle() [4/6]
template<typename T >
v8::internal::MaybeDirectHandle< T >::MaybeDirectHandle (Tagged< T > object, LocalIsolate * isolate) [inline]
Definition at line 248 of file maybe-handles.h.
      : handle_(object, isolate) {}
MaybeDirectHandle() [5/6]
template<typename T >
v8::internal::MaybeDirectHandle< T >::MaybeDirectHandle (Tagged< T > object, LocalHeap * local_heap) [inline]
Definition at line 250 of file maybe-handles.h.
      : handle_(object, local_heap) {}
MaybeDirectHandle() [6/6]
template<typename T >
template<typename S >
v8::internal::MaybeDirectHandle< T >::MaybeDirectHandle (DirectHandle< S > handle) [inline]
Member Function Documentation
Check()
template<typename T >
void v8::internal::MaybeDirectHandle< T >::Check () const [inline]
Definition at line 271 of file maybe-handles.h.
{ handle_.Check(); }
References v8::internal::MaybeDirectHandle< T >::handle_.
is_null()
template<typename T >
bool v8::internal::MaybeDirectHandle< T >::is_null () const [inline]
Definition at line 281 of file maybe-handles.h.
{ return handle_.is_null(); }
References v8::internal::MaybeDirectHandle< T >::handle_.
Referenced by v8::internal::wasm::InstanceBuilder::AllocateMemory(), v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::Map::AsLanguageMode(), v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterQueueNode(), v8::internal::BUILTIN(), v8::internal::Debug::CheckBreakPointsForLocations(), v8::WasmModuleObject::Compile(), v8::internal::CompileGlobalEval(), v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread(), v8::internal::Factory::ComputeInternalizationStrategyForString(), v8::internal::MapUpdater::ConstructNewMap(), v8::internal::Map::CopyReplaceDescriptors(), v8::internal::ScopeInfo::Create(), v8::internal::JSSharedStruct::CreateInstanceMap(), v8::internal::Object::CreateListFromArrayLike(), v8::internal::ParseInfo::CreateScript(), v8::internal::SharedFunctionInfo::DiscardCompiled(), v8::internal::JSDisposableStackBase::DisposeResources(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::internal::wasm::InstanceBuilder::ExecuteStartFunction(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), v8::internal::BackgroundCompileTask::FinalizeScript(), v8::internal::Debug::FindSharedFunctionInfosIntersectingRange(), v8::internal::wasm::SyncStreamingDecoder::Finish(), v8::internal::ErrorUtils::FormatStackTrace(), v8::internal::V8HeapExplorer::GetConstructor(), v8::internal::Compiler::GetFunctionFromValidatedString(), v8::internal::FactoryBase< Impl >::GetInPlaceInternalizedStringMap(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), v8::internal::Compiler::GetWrappedFunction(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), v8::internal::DebugEvaluate::Local(), v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), v8::internal::WasmGlobalObject::New(), v8::internal::WeakFixedArray::New(), v8::internal::anonymous_namespace{map-updater.cc}::PrintGeneralization(), v8::internal::SharedStructTypeRegistry::Register(), v8::internal::FutexEmulation::ResolveAsyncWaiterPromise(), v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(), v8::internal::MicrotaskQueue::RunMicrotasks(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), v8::internal::ScopeIterator::TryParseAndRetrieveScopes(), and v8::internal::Isolate::WalkCallStackAndPromiseTree().
ToHandle()
template<typename T >
template<typename S >
V8_WARN_UNUSED_RESULT bool v8::internal::MaybeDirectHandle< T >::ToHandle (DirectHandle< S > * out) const [inline]
Definition at line 277 of file maybe-handles.h.
                                                                            {
    return handle_.ToHandle(out);
  }
References v8::internal::MaybeDirectHandle< T >::handle_.
Referenced by v8::internal::PrototypeIterator::AdvanceFollowingProxiesIgnoringAccessChecks(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::BUILTIN(), v8::internal::Debug::CheckBreakPoint(), v8::internal::BigInt::CompareToString(), v8::internal::RegExp::Compile(), v8::internal::Genesis::CompileExtension(), v8::internal::CompileGlobalEval(), v8::debug::CompileInspectorScript(), v8::ScriptCompiler::CompileUnboundInternal(), v8::internal::Genesis::ConfigureApiObject(), v8::internal::Map::CopyReplaceDescriptors(), v8::internal::ExternalizeStringExtension::CreateExternalizableString(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString(), v8::internal::JSSharedStruct::CreateInstanceMap(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::CreateWasmObject(), v8::internal::anonymous_namespace{runtime-literals.cc}::DeepCopy(), v8::internal::Runtime::DefineObjectOwnProperty(), v8::internal::CodeSerializer::Deserialize(), v8::internal::ContextDeserializer::DeserializeContext(), v8::internal::Parser::DeserializeScopeChain(), v8::internal::BigInt::EqualToString(), v8::internal::BigInt::Exponentiate(), v8::internal::BackgroundCompileTask::FinalizeFunction(), v8::internal::BackgroundCompileTask::FinalizeScript(), v8::internal::Genesis::Genesis(), v8::internal::JSFunction::GetDerivedRabGsabDataViewMap(), v8::internal::JSFunction::GetDerivedRabGsabTypedArrayMap(), v8::internal::Isolate::GetImportAttributesFromArgument(), v8::internal::Accessors::GetLegacyFunctionCaller(), v8::internal::FunctionTemplateInfo::GetOrCreateSharedFunctionInfo(), wasm::anonymous_namespace{c-api.cc}::GetProperException(), v8::internal::Compiler::GetSharedFunctionInfo(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), v8::internal::TemplateObjectDescription::GetTemplateObject(), v8::internal::Compiler::GetWrappedFunction(), v8::internal::indirect_handle(), v8::internal::anonymous_namespace{builtins-array.cc}::IsConcatSpreadable(), v8::internal::KeyedLoadIC::LoadElementHandler(), v8::internal::JitLogger::LogRecordedBuffer(), v8::internal::WasmExportedFunction::New(), v8::internal::WasmGlobalObject::New(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::internal::Factory::NewJSSharedStruct(), v8::internal::FactoryBase< Impl >::NewSharedFunctionInfo(), v8::internal::Object::NoSideEffectsToString(), v8::internal::Debug::OnException(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForInstanceOf(), v8::internal::MessageHandler::ReportMessage(), v8::internal::JSPromise::Resolve(), v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(), v8::internal::SourceTextModule::RunInitializationCode(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::ScriptHash(), v8::internal::Runtime::SetObjectProperty(), v8::internal::Intl::StringLocaleCompare(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), v8::Utils::ToMaybeLocal(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype(), v8::internal::Map::TransitionToAccessorProperty(), v8::internal::Map::TransitionToDataProperty(), v8::internal::Isolate::WalkCallStackAndPromiseTree(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl().
ToHandleChecked()
template<typename T >
DirectHandle<T> v8::internal::MaybeDirectHandle< T >::ToHandleChecked () const [inline]
Definition at line 273 of file maybe-handles.h.
                                                    {
    return handle_.ToHandleChecked();
  }
References v8::internal::MaybeDirectHandle< T >::handle_.
Referenced by v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::Map::AsLanguageMode(), v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::SourceTextModule::AsyncModuleExecutionFulfilled(), v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterQueueNode(), v8::internal::BUILTIN(), v8::internal::Debug::CheckBreakPointsForLocations(), v8::WasmModuleObject::Compile(), v8::internal::CompileGlobalEval(), v8::internal::MapUpdater::ConstructNewMap(), v8::internal::ScopeInfo::Create(), v8::internal::ParseInfo::CreateScript(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::SharedFunctionInfo::DiscardCompiled(), v8::internal::wasm::InstanceBuilder::FinalizeExportsObject(), v8::internal::wasm::SyncStreamingDecoder::Finish(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::ErrorUtils::FormatStackTrace(), v8::internal::V8HeapExplorer::GetConstructor(), v8::internal::Compiler::GetFunctionFromValidatedString(), v8::internal::SourceTextModule::InnerModuleEvaluation(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), v8::internal::WeakFixedArray::New(), v8::internal::anonymous_namespace{map-updater.cc}::PrintGeneralization(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::raw_buffer_ptr(), v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(), and v8::internal::RUNTIME_FUNCTION().
Friends And Related Function Documentation
DirectHandle
template<typename T >
template<typename >
friend class DirectHandle [friend]
Definition at line 286 of file maybe-handles.h.
indirect_handle [1/2]
template<typename T >
template<typename U >
MaybeIndirectHandle<U> indirect_handle (MaybeDirectHandle< U > , Isolate *) [friend]
indirect_handle [2/2]
template<typename T >
template<typename U >
MaybeIndirectHandle<U> indirect_handle (MaybeDirectHandle< U > , LocalIsolate *) [friend]
MaybeDirectHandle
template<typename T >
template<typename >
friend class MaybeDirectHandle [friend]
Definition at line 290 of file maybe-handles.h.
UncheckedCast
template<typename T >
template<typename To , typename From >
MaybeDirectHandle<To> UncheckedCast (MaybeDirectHandle< From > value) [friend]
Definition at line 188 of file maybe-handles-inl.h.
                                                                          {
  return MaybeDirectHandle<To>(UncheckedCast<To>(value.handle_));
}
Member Data Documentation
__pad0__
template<typename T >
T v8::internal::MaybeDirectHandle< T >::__pad0__
Definition at line 255 of file maybe-handles.h.
handle_
template<typename T >
MaybeIndirectHandle<T> v8::internal::MaybeDirectHandle< T >::handle_ [private]
Definition at line 302 of file maybe-handles.h.
Referenced by v8::internal::MaybeDirectHandle< T >::Check(), v8::internal::indirect_handle(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
T
template<typename T >
T v8::internal::MaybeDirectHandle< T >::T
Definition at line 259 of file maybe-handles.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/globals.h
/mnt/V8SourceCode/src/handles/maybe-handles.h