v8::base::StrongAlias< TagType, UnderlyingType > Class Template Reference
#include <strong-alias.h>
Classes
struct Hasher
Public Types
using underlying_type = UnderlyingType
Public Member Functions
StrongAlias ()=default
constexpr StrongAlias (const UnderlyingType &v)
constexpr StrongAlias (UnderlyingType &&v) noexcept
constexpr UnderlyingType * operator-> ()
constexpr const UnderlyingType * operator-> () const
constexpr UnderlyingType & operator* () &
constexpr const UnderlyingType & operator* () const &
constexpr UnderlyingType && operator* () &&
constexpr const UnderlyingType && operator* () const &&
constexpr UnderlyingType & value () &
constexpr const UnderlyingType & value () const &
constexpr UnderlyingType && value () &&
constexpr const UnderlyingType && value () const &&
constexpr operator const UnderlyingType & () const &
Protected Attributes
UnderlyingType value_
Friends
auto operator<=> (const StrongAlias &lhs, const StrongAlias &rhs)=default
bool operator== (const StrongAlias &lhs, const StrongAlias &rhs)=default
Detailed Description
template<typename TagType, typename UnderlyingType>
class v8::base::StrongAlias< TagType, UnderlyingType >
Definition at line 74 of file strong-alias.h.
Member Typedef Documentation
underlying_type
template<typename TagType , typename UnderlyingType >
using v8::base::StrongAlias< TagType, UnderlyingType >::underlying_type = UnderlyingType
Definition at line 76 of file strong-alias.h.
Constructor & Destructor Documentation
StrongAlias() [1/3]
template<typename TagType , typename UnderlyingType >
v8::base::StrongAlias< TagType, UnderlyingType >::StrongAlias () [default]
StrongAlias() [2/3]
template<typename TagType , typename UnderlyingType >
constexpr v8::base::StrongAlias< TagType, UnderlyingType >::StrongAlias (const UnderlyingType & v) [inline], [explicit], [constexpr]
Definition at line 79 of file strong-alias.h.
: value_(v) {}
StrongAlias() [3/3]
template<typename TagType , typename UnderlyingType >
constexpr v8::base::StrongAlias< TagType, UnderlyingType >::StrongAlias (UnderlyingType && v) [inline], [explicit], [constexpr], [noexcept]
Definition at line 80 of file strong-alias.h.
      : value_(std::move(v)) {}
Member Function Documentation
operator const UnderlyingType &()
template<typename TagType , typename UnderlyingType >
constexpr v8::base::StrongAlias< TagType, UnderlyingType >::operator const UnderlyingType & () const & [inline], [explicit], [constexpr]
Definition at line 98 of file strong-alias.h.
{ return value_; }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
operator*() [1/4]
template<typename TagType , typename UnderlyingType >
constexpr UnderlyingType& v8::base::StrongAlias< TagType, UnderlyingType >::operator* () & [inline], [constexpr]
Definition at line 86 of file strong-alias.h.
{ return value_; }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
operator*() [2/4]
template<typename TagType , typename UnderlyingType >
constexpr UnderlyingType&& v8::base::StrongAlias< TagType, UnderlyingType >::operator* () && [inline], [constexpr]
Definition at line 88 of file strong-alias.h.
{ return std::move(value_); }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
operator*() [3/4]
template<typename TagType , typename UnderlyingType >
constexpr const UnderlyingType& v8::base::StrongAlias< TagType, UnderlyingType >::operator* () const & [inline], [constexpr]
Definition at line 87 of file strong-alias.h.
{ return value_; }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
operator*() [4/4]
template<typename TagType , typename UnderlyingType >
constexpr const UnderlyingType&& v8::base::StrongAlias< TagType, UnderlyingType >::operator* () const && [inline], [constexpr]
Definition at line 89 of file strong-alias.h.
                                                       {
    return std::move(value_);
  }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
operator->() [1/2]
template<typename TagType , typename UnderlyingType >
constexpr UnderlyingType* v8::base::StrongAlias< TagType, UnderlyingType >::operator-> () [inline], [constexpr]
Definition at line 83 of file strong-alias.h.
{ return &value_; }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
operator->() [2/2]
template<typename TagType , typename UnderlyingType >
constexpr const UnderlyingType* v8::base::StrongAlias< TagType, UnderlyingType >::operator-> () const [inline], [constexpr]
Definition at line 84 of file strong-alias.h.
{ return &value_; }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
value() [1/4]
template<typename TagType , typename UnderlyingType >
constexpr UnderlyingType& v8::base::StrongAlias< TagType, UnderlyingType >::value () & [inline], [constexpr]
Definition at line 93 of file strong-alias.h.
{ return value_; }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::compiler::CodeAssembler::CallJSBuiltin(), v8::internal::FeedbackCell::clear_dispatch_handle(), v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::CodeStubAssembler::InvalidDispatchHandleConstant(), v8::base::operator<<(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), and v8::internal::TF_BUILTIN().
value() [2/4]
template<typename TagType , typename UnderlyingType >
constexpr UnderlyingType&& v8::base::StrongAlias< TagType, UnderlyingType >::value () && [inline], [constexpr]
Definition at line 95 of file strong-alias.h.
{ return std::move(value_); }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
value() [3/4]
template<typename TagType , typename UnderlyingType >
constexpr const UnderlyingType& v8::base::StrongAlias< TagType, UnderlyingType >::value () const & [inline], [constexpr]
Definition at line 94 of file strong-alias.h.
{ return value_; }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
value() [4/4]
template<typename TagType , typename UnderlyingType >
constexpr const UnderlyingType&& v8::base::StrongAlias< TagType, UnderlyingType >::value () const && [inline], [constexpr]
Definition at line 96 of file strong-alias.h.
{ return std::move(value_); }
References v8::base::StrongAlias< TagType, UnderlyingType >::value_.
Friends And Related Function Documentation
operator<=>
template<typename TagType , typename UnderlyingType >
auto operator<=> (const StrongAlias< TagType, UnderlyingType > & lhs, const StrongAlias< TagType, UnderlyingType > & rhs) [friend]
operator==
template<typename TagType , typename UnderlyingType >
bool operator== (const StrongAlias< TagType, UnderlyingType > & lhs, const StrongAlias< TagType, UnderlyingType > & rhs) [friend]
Member Data Documentation
value_
template<typename TagType , typename UnderlyingType >
UnderlyingType v8::base::StrongAlias< TagType, UnderlyingType >::value_ [protected]
Definition at line 126 of file strong-alias.h.
Referenced by v8::base::StrongAlias< TagType, UnderlyingType >::operator const UnderlyingType &(), v8::base::StrongAlias< TagType, UnderlyingType >::operator*(), v8::base::StrongAlias< TagType, UnderlyingType >::operator->(), and v8::base::StrongAlias< TagType, UnderlyingType >::value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/strong-alias.h