v8::internal::compiler::MachineOperatorReducer Class Reference
#include <machine-operator-reducer.h>
Public Types
enum SignallingNanPropagation { kSilenceSignallingNan
, kPropagateSignallingNan
 }
Public Member Functions
MachineOperatorReducer (Editor *editor, MachineGraph *mcgraph, SignallingNanPropagation signalling_nan_propagation)
~MachineOperatorReducer () override
const char * reducer_name () const override
Reduction Reduce (Node *node) override
Private Member Functions
Node * Float32Constant (float value)
Node * Float64Constant (double value)
Node * Int32Constant (int32_t value)
Node * Int64Constant (int64_t value)
Node * Uint32Constant (uint32_t value)
Node * Uint64Constant (uint64_t value)
Node * Float64Mul (Node *lhs, Node *rhs)
Node * Float64PowHalf (Node *value)
Node * Word32And (Node *lhs, Node *rhs)
Node * Word32And (Node *lhs, uint32_t rhs)
Node * Word32Sar (Node *lhs, uint32_t rhs)
Node * Word64Sar (Node *lhs, uint32_t rhs)
Node * Word32Shr (Node *lhs, uint32_t rhs)
Node * Word64Shr (Node *lhs, uint32_t rhs)
Node * Word32Equal (Node *lhs, Node *rhs)
Node * Word64Equal (Node *lhs, Node *rhs)
Node * Word64And (Node *lhs, Node *rhs)
Node * Word64And (Node *lhs, uint64_t rhs)
Node * Int32Add (Node *lhs, Node *rhs)
Node * Int64Add (Node *lhs, Node *rhs)
Node * Int32Sub (Node *lhs, Node *rhs)
Node * Int64Sub (Node *lhs, Node *rhs)
Node * Int32Mul (Node *lhs, Node *rhs)
Node * Int64Mul (Node *lhs, Node *rhs)
Node * Int32Div (Node *dividend, int32_t divisor)
Node * Int64Div (Node *dividend, int64_t divisor)
Node * Uint32Div (Node *dividend, uint32_t divisor)
Node * Uint64Div (Node *dividend, uint64_t divisor)
Node * TruncateInt64ToInt32 (Node *value)
Node * ChangeInt32ToInt64 (Node *value)
Reduction ReplaceBool (bool value)
Reduction ReplaceFloat32 (float value)
Reduction ReplaceFloat64 (double value)
Reduction ReplaceInt32 (int32_t value)
Reduction ReplaceUint32 (uint32_t value)
Reduction ReplaceInt64 (int64_t value)
Reduction ReplaceUint64 (uint64_t value)
Reduction ReduceInt32Add (Node *node)
Reduction ReduceInt64Add (Node *node)
Reduction ReduceInt32Sub (Node *node)
Reduction ReduceInt64Sub (Node *node)
Reduction ReduceInt64Mul (Node *node)
Reduction ReduceInt32Div (Node *node)
Reduction ReduceInt64Div (Node *node)
Reduction ReduceUint32Div (Node *node)
Reduction ReduceUint64Div (Node *node)
Reduction ReduceInt32Mod (Node *node)
Reduction ReduceInt64Mod (Node *node)
Reduction ReduceUint32Mod (Node *node)
Reduction ReduceUint64Mod (Node *node)
Reduction ReduceStore (Node *node)
Reduction ReduceProjection (size_t index, Node *node)
const Operator * Map64To32Comparison (const Operator *op, bool sign_extended)
Reduction ReduceWord32Comparisons (Node *node)
Reduction ReduceWord64Comparisons (Node *node)
Reduction ReduceWord32Shifts (Node *node)
Reduction ReduceWord32Shl (Node *node)
Reduction ReduceWord64Shl (Node *node)
Reduction ReduceWord32Shr (Node *node)
Reduction ReduceWord64Shr (Node *node)
Reduction ReduceWord32Sar (Node *node)
Reduction ReduceWord64Sar (Node *node)
Reduction ReduceWord32And (Node *node)
Reduction ReduceWord64And (Node *node)
Reduction TryMatchWord32Ror (Node *node)
Reduction ReduceWord32Or (Node *node)
Reduction ReduceWord64Or (Node *node)
Reduction ReduceWord32Xor (Node *node)
Reduction ReduceWord64Xor (Node *node)
Reduction ReduceWord32Equal (Node *node)
Reduction ReduceWord64Equal (Node *node)
Reduction ReduceFloat64InsertLowWord32 (Node *node)
Reduction ReduceFloat64InsertHighWord32 (Node *node)
Reduction ReduceFloat64Compare (Node *node)
Reduction ReduceFloat64RoundDown (Node *node)
Reduction ReduceTruncateInt64ToInt32 (Node *node)
Reduction ReduceConditional (Node *node)
TFGraph * graph () const
MachineGraph * mcgraph () const
CommonOperatorBuilder * common () const
MachineOperatorBuilder * machine () const
template<typename WordNAdapter >
Reduction ReduceWordNAnd (Node *node)
template<typename WordNAdapter >
Reduction ReduceWordNOr (Node *node)
template<typename WordNAdapter >
Reduction ReduceWordNXor (Node *node)
template<typename WordNAdapter >
Reduction ReduceUintNLessThanOrEqual (Node *node)
Reduction SimplifyBranch (Node *node)
void SwapBranches (Node *node)
template<typename WordNAdapter >
std::optional< Node * > ReduceConditionalN (Node *node)
template<typename WordNAdapter , typename uintN_t , typename intN_t = std::make_signed_t<uintN_t>>
std::optional< std::pair< Node *, uintN_t > > ReduceWordEqualForConstantRhs (Node *lhs, uintN_t rhs)
Private Attributes
MachineGraph * mcgraph_
SignallingNanPropagation signalling_nan_propagation_
Friends
class Word32Adapter
class Word64Adapter
Detailed Description
Definition at line 27 of file machine-operator-reducer.h.
Member Enumeration Documentation
SignallingNanPropagation
enum v8::internal::compiler::MachineOperatorReducer::SignallingNanPropagation
Enumerator
kSilenceSignallingNan
kPropagateSignallingNan
Definition at line 30 of file machine-operator-reducer.h.
                                {
    kSilenceSignallingNan,
    kPropagateSignallingNan
  };
Constructor & Destructor Documentation
MachineOperatorReducer()
v8::internal::compiler::MachineOperatorReducer::MachineOperatorReducer (Editor * editor, MachineGraph * mcgraph, SignallingNanPropagation signalling_nan_propagation) [explicit]
Definition at line 192 of file machine-operator-reducer.cc.
    : AdvancedReducer(editor),
      mcgraph_(mcgraph),
      signalling_nan_propagation_(signalling_nan_propagation) {}
 MachineOperatorReducer()
v8::internal::compiler::MachineOperatorReducer::~MachineOperatorReducer () [override], [default]
Member Function Documentation
ChangeInt32ToInt64()
Node * v8::internal::compiler::MachineOperatorReducer::ChangeInt32ToInt64 (Node * value) [private]
Definition at line 386 of file machine-operator-reducer.cc.
                                                            {
  return graph()->NewNode(machine()->ChangeInt32ToInt64(), value);
}
References graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by ReduceInt64Div(), and ReduceUint64Div().
common()
CommonOperatorBuilder * v8::internal::compiler::MachineOperatorReducer::common () const [private]
Definition at line 3025 of file machine-operator-reducer.cc.
                                                            {
  return mcgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and mcgraph().
Referenced by Float32Constant(), Float64PowHalf(), Int64Constant(), ReduceInt32Mod(), ReduceInt64Mod(), ReduceWord64Comparisons(), ReduceWord64Equal(), SimplifyBranch(), and SwapBranches().
Float32Constant()
Node * v8::internal::compiler::MachineOperatorReducer::Float32Constant (float value) [private]
Definition at line 201 of file machine-operator-reducer.cc.
                                                         {
  return graph()->NewNode(common()->Float32Constant(value));
}
References common(), graph(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by ReduceFloat64Compare().
Float64Constant()
Node * v8::internal::compiler::MachineOperatorReducer::Float64Constant (double value) [private]
Definition at line 205 of file machine-operator-reducer.cc.
                                                          {
  return mcgraph()->Float64Constant(value);
}
References v8::internal::compiler::MachineGraph::Float64Constant(), mcgraph(), and v8::internal::value.
Referenced by Float64PowHalf(), and Reduce().
Float64Mul()
Node * v8::internal::compiler::MachineOperatorReducer::Float64Mul (Node * lhs, Node * rhs) [private]
Definition at line 217 of file machine-operator-reducer.cc.
                                                             {
  return graph()->NewNode(machine()->Float64Mul(), lhs, rhs);
}
References graph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by Reduce().
Float64PowHalf()
Node * v8::internal::compiler::MachineOperatorReducer::Float64PowHalf (Node * value) [private]
Definition at line 221 of file machine-operator-reducer.cc.
                                                        {
  value =
      graph()->NewNode(machine()->Float64Add(), Float64Constant(0.0), value);
  Diamond d(graph(), common(),
            graph()->NewNode(machine()->Float64LessThanOrEqual(), value,
                             Float64Constant(-V8_INFINITY)),
            BranchHint::kFalse);
  return d.Phi(MachineRepresentation::kFloat64, Float64Constant(V8_INFINITY),
               graph()->NewNode(machine()->Float64Sqrt(), value));
}
References common(), v8::internal::compiler::Float64Add(), Float64Constant(), graph(), v8::internal::kFalse, v8::internal::kFloat64, machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Diamond::Phi(), V8_INFINITY, and v8::internal::value.
Referenced by Reduce().
graph()
TFGraph * v8::internal::compiler::MachineOperatorReducer::graph () const [private]
Definition at line 3033 of file machine-operator-reducer.cc.
{ return mcgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and mcgraph().
Referenced by ChangeInt32ToInt64(), Float32Constant(), Float64Mul(), Float64PowHalf(), Int32Add(), Int32Div(), Int32Mul(), Int32Sub(), Int64Add(), Int64Constant(), Int64Div(), Int64Mul(), Int64Sub(), Reduce(), ReduceInt32Mod(), ReduceInt64Mod(), TruncateInt64ToInt32(), Uint32Div(), Uint64Div(), Word32And(), Word32Equal(), Word32Sar(), Word32Shr(), Word64And(), Word64Equal(), Word64Sar(), and Word64Shr().
Int32Add()
Node * v8::internal::compiler::MachineOperatorReducer::Int32Add (Node * lhs, Node * rhs) [private]
Definition at line 272 of file machine-operator-reducer.cc.
                                                           {
  Node* const node = graph()->NewNode(machine()->Int32Add(), lhs, rhs);
  Reduction const reduction = ReduceInt32Add(node);
  return reduction.Changed() ? reduction.replacement() : node;
}
References v8::internal::compiler::Reduction::Changed(), graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), ReduceInt32Add(), and v8::internal::compiler::Reduction::replacement().
Referenced by Int32Div(), ReduceInt32Div(), ReduceInt32Sub(), and Uint32Div().
Int32Constant()
Node * v8::internal::compiler::MachineOperatorReducer::Int32Constant (int32_t value) [private]
Definition at line 209 of file machine-operator-reducer.cc.
                                                         {
  return mcgraph()->Int32Constant(value);
}
References v8::internal::compiler::MachineGraph::Int32Constant(), mcgraph(), and v8::internal::value.
Referenced by v8::internal::compiler::Word32Adapter::IntNConstant(), Reduce(), ReduceInt32Add(), ReduceInt32Div(), ReduceInt32Mod(), ReduceInt32Sub(), ReduceUint32Div(), ReduceWord32And(), ReduceWord32Comparisons(), ReduceWord32Equal(), ReduceWord32Sar(), ReduceWord32Xor(), ReduceWord64Comparisons(), and ReduceWord64Equal().
Int32Div()
Node * v8::internal::compiler::MachineOperatorReducer::Int32Div (Node * dividend, int32_t divisor) [private]
Definition at line 304 of file machine-operator-reducer.cc.
                                                                      {
  DCHECK_NE(0, divisor);
  DCHECK_NE(std::numeric_limits<int32_t>::min(), divisor);
  base::MagicNumbersForDivision<uint32_t> const mag =
      base::SignedDivisionByConstant(base::bit_cast<uint32_t>(divisor));
  Node* quotient = graph()->NewNode(machine()->Int32MulHigh(), dividend,
                                    Uint32Constant(mag.multiplier));
  if (divisor > 0 && base::bit_cast<int32_t>(mag.multiplier) < 0) {
    quotient = Int32Add(quotient, dividend);
  } else if (divisor < 0 && base::bit_cast<int32_t>(mag.multiplier) > 0) {
    quotient = Int32Sub(quotient, dividend);
  }
  return Int32Add(Word32Sar(quotient, mag.shift), Word32Shr(dividend, 31));
}
References DCHECK_NE, graph(), Int32Add(), Int32Sub(), machine(), v8::internal::compiler::TFGraph::NewNode(), v8::base::SignedDivisionByConstant(), Uint32Constant(), Word32Sar(), and Word32Shr().
Referenced by ReduceInt32Div(), and ReduceInt32Mod().
Int32Mul()
Node * v8::internal::compiler::MachineOperatorReducer::Int32Mul (Node * lhs, Node * rhs) [private]
Definition at line 296 of file machine-operator-reducer.cc.
                                                           {
  return graph()->NewNode(machine()->Int32Mul(), lhs, rhs);
}
References graph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by ReduceInt32Mod(), and ReduceUint32Mod().
Int32Sub()
Node * v8::internal::compiler::MachineOperatorReducer::Int32Sub (Node * lhs, Node * rhs) [private]
Definition at line 284 of file machine-operator-reducer.cc.
                                                           {
  Node* const node = graph()->NewNode(machine()->Int32Sub(), lhs, rhs);
  Reduction const reduction = ReduceInt32Sub(node);
  return reduction.Changed() ? reduction.replacement() : node;
}
References v8::internal::compiler::Reduction::Changed(), graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), ReduceInt32Sub(), and v8::internal::compiler::Reduction::replacement().
Referenced by Int32Div(), Reduce(), ReduceInt32Add(), ReduceInt32Div(), ReduceInt32Mod(), ReduceUint32Mod(), ReduceWord32Sar(), and Uint32Div().
Int64Add()
Node * v8::internal::compiler::MachineOperatorReducer::Int64Add (Node * lhs, Node * rhs) [private]
Definition at line 278 of file machine-operator-reducer.cc.
                                                           {
  Node* const node = graph()->NewNode(machine()->Int64Add(), lhs, rhs);
  Reduction const reduction = ReduceInt64Add(node);
  return reduction.Changed() ? reduction.replacement() : node;
}
References v8::internal::compiler::Reduction::Changed(), graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), ReduceInt64Add(), and v8::internal::compiler::Reduction::replacement().
Referenced by Int64Div(), Reduce(), ReduceInt64Div(), ReduceInt64Sub(), and Uint64Div().
Int64Constant()
Node * v8::internal::compiler::MachineOperatorReducer::Int64Constant (int64_t value) [private]
Definition at line 213 of file machine-operator-reducer.cc.
                                                         {
  return graph()->NewNode(common()->Int64Constant(value));
}
References common(), graph(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by v8::internal::compiler::Word64Adapter::IntNConstant(), Reduce(), ReduceInt64Add(), ReduceInt64Div(), ReduceInt64Mod(), ReduceInt64Mul(), ReduceInt64Sub(), ReduceUint64Div(), ReduceWord64Comparisons(), and ReduceWord64Equal().
Int64Div()
Node * v8::internal::compiler::MachineOperatorReducer::Int64Div (Node * dividend, int64_t divisor) [private]
Definition at line 319 of file machine-operator-reducer.cc.
                                                                      {
  DCHECK_NE(0, divisor);
  DCHECK_NE(std::numeric_limits<int64_t>::min(), divisor);
  base::MagicNumbersForDivision<uint64_t> const mag =
      base::SignedDivisionByConstant(base::bit_cast<uint64_t>(divisor));
  Node* quotient = graph()->NewNode(machine()->Int64MulHigh(), dividend,
                                    Uint64Constant(mag.multiplier));
  if (divisor > 0 && base::bit_cast<int64_t>(mag.multiplier) < 0) {
    quotient = Int64Add(quotient, dividend);
  } else if (divisor < 0 && base::bit_cast<int64_t>(mag.multiplier) > 0) {
    quotient = Int64Sub(quotient, dividend);
  }
  return Int64Add(Word64Sar(quotient, mag.shift), Word64Shr(dividend, 63));
}
References DCHECK_NE, graph(), Int64Add(), Int64Sub(), machine(), v8::internal::compiler::TFGraph::NewNode(), v8::base::SignedDivisionByConstant(), Uint64Constant(), Word64Sar(), and Word64Shr().
Referenced by ReduceInt64Div(), and ReduceInt64Mod().
Int64Mul()
Node * v8::internal::compiler::MachineOperatorReducer::Int64Mul (Node * lhs, Node * rhs) [private]
Definition at line 300 of file machine-operator-reducer.cc.
                                                           {
  return graph()->NewNode(machine()->Int64Mul(), lhs, rhs);
}
References graph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by ReduceInt64Mod(), and ReduceUint64Mod().
Int64Sub()
Node * v8::internal::compiler::MachineOperatorReducer::Int64Sub (Node * lhs, Node * rhs) [private]
Definition at line 290 of file machine-operator-reducer.cc.
                                                           {
  Node* const node = graph()->NewNode(machine()->Int64Sub(), lhs, rhs);
  Reduction const reduction = ReduceInt64Sub(node);
  return reduction.Changed() ? reduction.replacement() : node;
}
References v8::internal::compiler::Reduction::Changed(), graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), ReduceInt64Sub(), and v8::internal::compiler::Reduction::replacement().
Referenced by Int64Div(), ReduceInt64Div(), ReduceInt64Mod(), ReduceInt64Mul(), ReduceUint64Mod(), and Uint64Div().
machine()
MachineOperatorBuilder * v8::internal::compiler::MachineOperatorReducer::machine () const [private]
Definition at line 3029 of file machine-operator-reducer.cc.
                                                              {
  return mcgraph()->machine();
}
References v8::internal::compiler::MachineGraph::machine(), and mcgraph().
Referenced by ChangeInt32ToInt64(), Float64Mul(), Float64PowHalf(), Int32Add(), Int32Div(), Int32Mul(), Int32Sub(), Int64Add(), Int64Div(), Int64Mul(), Int64Sub(), Map64To32Comparison(), Reduce(), ReduceFloat64Compare(), ReduceInt32Add(), ReduceInt32Div(), ReduceInt32Mod(), ReduceInt32Sub(), ReduceInt64Div(), ReduceInt64Mod(), ReduceInt64Mul(), ReduceInt64Sub(), ReduceTruncateInt64ToInt32(), ReduceUint32Div(), ReduceUint32Mod(), ReduceUint64Div(), ReduceUint64Mod(), ReduceUintNLessThanOrEqual(), ReduceWord32And(), ReduceWord32Comparisons(), ReduceWord32Sar(), ReduceWord32Shifts(), ReduceWord32Shl(), ReduceWord64Comparisons(), ReduceWord64Equal(), ReduceWord64Shl(), ReduceWordNAnd(), TruncateInt64ToInt32(), TryMatchWord32Ror(), Uint32Div(), Uint64Div(), Word32And(), Word32Equal(), Word32Sar(), Word32Shr(), Word64And(), Word64Equal(), Word64Sar(), and Word64Shr().
Map64To32Comparison()
const Operator * v8::internal::compiler::MachineOperatorReducer::Map64To32Comparison (const Operator * op, bool sign_extended) [private]
Definition at line 1700 of file machine-operator-reducer.cc.
                                            {
  switch (op->opcode()) {
    case IrOpcode::kInt64LessThan:
      return sign_extended ? machine()->Int32LessThan()
                           : machine()->Uint32LessThan();
    case IrOpcode::kInt64LessThanOrEqual:
      return sign_extended ? machine()->Int32LessThanOrEqual()
                           : machine()->Uint32LessThanOrEqual();
    case IrOpcode::kUint64LessThan:
      return machine()->Uint32LessThan();
    case IrOpcode::kUint64LessThanOrEqual:
      return machine()->Uint32LessThanOrEqual();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::MachineOperatorBuilder::Int32LessThan(), v8::internal::compiler::MachineOperatorBuilder::Int32LessThanOrEqual(), machine(), v8::internal::compiler::Operator::opcode(), v8::internal::compiler::MachineOperatorBuilder::Uint32LessThan(), v8::internal::compiler::MachineOperatorBuilder::Uint32LessThanOrEqual(), and v8::internal::UNREACHABLE().
Referenced by ReduceWord64Comparisons().
mcgraph()
MachineGraph* v8::internal::compiler::MachineOperatorReducer::mcgraph () const [inline], [private]
Definition at line 149 of file machine-operator-reducer.h.
{ return mcgraph_; }
Referenced by common(), Float64Constant(), graph(), Int32Constant(), and machine().
Reduce()
Reduction v8::internal::compiler::MachineOperatorReducer::Reduce (Node * node) [override]
Definition at line 391 of file machine-operator-reducer.cc.
                                                   {
  switch (node->opcode()) {
    case IrOpcode::kProjection:
      return ReduceProjection(ProjectionIndexOf(node->op()), node->InputAt(0));
    case IrOpcode::kWord32And:
      return ReduceWord32And(node);
    case IrOpcode::kWord64And:
      return ReduceWord64And(node);
    case IrOpcode::kWord32Or:
      return ReduceWord32Or(node);
    case IrOpcode::kWord64Or:
      return ReduceWord64Or(node);
    case IrOpcode::kWord32Xor:
      return ReduceWord32Xor(node);
    case IrOpcode::kWord64Xor:
      return ReduceWord64Xor(node);
    case IrOpcode::kWord32Shl:
      return ReduceWord32Shl(node);
    case IrOpcode::kWord64Shl:
      return ReduceWord64Shl(node);
    case IrOpcode::kWord32Shr:
      return ReduceWord32Shr(node);
    case IrOpcode::kWord64Shr:
      return ReduceWord64Shr(node);
    case IrOpcode::kWord32Sar:
      return ReduceWord32Sar(node);
    case IrOpcode::kWord64Sar:
      return ReduceWord64Sar(node);
    case IrOpcode::kWord32Ror: {
      Int32BinopMatcher m(node);
      if (m.right().Is(0)) return Replace(m.left().node()); // x ror 0 => x
      if (m.IsFoldable()) { // K ror K => K (K stands for arbitrary constants)
        return ReplaceInt32(base::bits::RotateRight32(
            m.left().ResolvedValue(), m.right().ResolvedValue() & 31));
      }
      break;
    }
    case IrOpcode::kWord32Equal:
      return ReduceWord32Equal(node);
    case IrOpcode::kWord64Equal:
      return ReduceWord64Equal(node);
    case IrOpcode::kInt32Add:
      return ReduceInt32Add(node);
    case IrOpcode::kInt64Add:
      return ReduceInt64Add(node);
    case IrOpcode::kInt32Sub:
      return ReduceInt32Sub(node);
    case IrOpcode::kInt64Sub:
      return ReduceInt64Sub(node);
    case IrOpcode::kInt32Mul: {
      Int32BinopMatcher m(node);
      if (m.right().Is(0)) return Replace(m.right().node()); // x * 0 => 0
      if (m.right().Is(1)) return Replace(m.left().node()); // x * 1 => x
      if (m.IsFoldable()) { // K * K => K (K stands for arbitrary constants)
        return ReplaceInt32(base::MulWithWraparound(m.left().ResolvedValue(),
                                                    m.right().ResolvedValue()));
      }
      if (m.right().Is(-1)) { // x * -1 => 0 - x
        node->ReplaceInput(0, Int32Constant(0));
        node->ReplaceInput(1, m.left().node());
        NodeProperties::ChangeOp(node, machine()->Int32Sub());
        return Changed(node);
      }
      if (m.right().IsPowerOf2()) { // x * 2^n => x << n
        node->ReplaceInput(1, Int32Constant(base::bits::WhichPowerOfTwo(
                                  m.right().ResolvedValue())));
        NodeProperties::ChangeOp(node, machine()->Word32Shl());
        return Changed(node).FollowedBy(ReduceWord32Shl(node));
      }
      // (x * Int32Constant(a)) * Int32Constant(b)) => x * Int32Constant(a * b)
      if (m.right().HasResolvedValue() && m.left().IsInt32Mul()) {
        Int32BinopMatcher n(m.left().node());
        if (n.right().HasResolvedValue() && m.OwnsInput(m.left().node())) {
          node->ReplaceInput(
              1, Int32Constant(base::MulWithWraparound(
                     m.right().ResolvedValue(), n.right().ResolvedValue())));
          node->ReplaceInput(0, n.left().node());
          return Changed(node);
        }
      }
      break;
    }
    case IrOpcode::kInt32MulWithOverflow: {
      Int32BinopMatcher m(node);
      if (m.right().Is(2)) {
        node->ReplaceInput(1, m.left().node());
        NodeProperties::ChangeOp(node, machine()->Int32AddWithOverflow());
        return Changed(node);
      }
      if (m.right().Is(-1)) {
        node->ReplaceInput(0, Int32Constant(0));
        node->ReplaceInput(1, m.left().node());
        NodeProperties::ChangeOp(node, machine()->Int32SubWithOverflow());
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kInt64Mul:
      return ReduceInt64Mul(node);
    case IrOpcode::kInt32Div:
      return ReduceInt32Div(node);
    case IrOpcode::kInt64Div:
      return ReduceInt64Div(node);
    case IrOpcode::kUint32Div:
      return ReduceUint32Div(node);
    case IrOpcode::kUint64Div:
      return ReduceUint64Div(node);
    case IrOpcode::kInt32Mod:
      return ReduceInt32Mod(node);
    case IrOpcode::kInt64Mod:
      return ReduceInt64Mod(node);
    case IrOpcode::kUint32Mod:
      return ReduceUint32Mod(node);
    case IrOpcode::kUint64Mod:
      return ReduceUint64Mod(node);
    case IrOpcode::kInt32LessThan: {
      Int32BinopMatcher m(node);
      if (m.IsFoldable()) { // K < K => K (K stands for arbitrary constants)
        return ReplaceBool(m.left().ResolvedValue() <
                           m.right().ResolvedValue());
      }
      if (m.LeftEqualsRight()) return ReplaceBool(false); // x < x => false
      if (m.left().IsWord32Or() && m.right().Is(0)) {
        // (x | K) < 0 => true or (K | x) < 0 => true iff K < 0
        Int32BinopMatcher mleftmatcher(m.left().node());
        if (mleftmatcher.left().IsNegative() ||
            mleftmatcher.right().IsNegative()) {
          return ReplaceBool(true);
        }
      }
      return ReduceWord32Comparisons(node);
    }
    case IrOpcode::kInt32LessThanOrEqual: {
      Int32BinopMatcher m(node);
      if (m.IsFoldable()) { // K <= K => K (K stands for arbitrary constants)
        return ReplaceBool(m.left().ResolvedValue() <=
                           m.right().ResolvedValue());
      }
      if (m.LeftEqualsRight()) return ReplaceBool(true); // x <= x => true
      return ReduceWord32Comparisons(node);
    }
    case IrOpcode::kUint32LessThan: {
      Uint32BinopMatcher m(node);
      if (m.left().Is(kMaxUInt32)) return ReplaceBool(false); // M < x => false
      if (m.right().Is(0)) return ReplaceBool(false); // x < 0 => false
      if (m.IsFoldable()) { // K < K => K (K stands for arbitrary constants)
        return ReplaceBool(m.left().ResolvedValue() <
                           m.right().ResolvedValue());
      }
      if (m.LeftEqualsRight()) return ReplaceBool(false); // x < x => false
      if (m.left().IsWord32Sar() && m.right().HasResolvedValue()) {
        Int32BinopMatcher mleft(m.left().node());
        if (mleft.right().HasResolvedValue()) {
          // (x >> K) < C => x < (C << K)
          // when C < (M >> K)
          const uint32_t c = m.right().ResolvedValue();
          const uint32_t k = mleft.right().ResolvedValue() & 0x1F;
          if (c < static_cast<uint32_t>(kMaxInt >> k)) {
            node->ReplaceInput(0, mleft.left().node());
            node->ReplaceInput(1, Uint32Constant(c << k));
            return Changed(node);
          }
          // TODO(turbofan): else the comparison is always true.
        }
      }
      return ReduceWord32Comparisons(node);
    }
    case IrOpcode::kUint32LessThanOrEqual: {
      return ReduceUintNLessThanOrEqual<Word32Adapter>(node);
    }
    case IrOpcode::kFloat32Sub: {
      Float32BinopMatcher m(node);
      if (signalling_nan_propagation_ == kPropagateSignallingNan &&
          m.right().Is(0) &&
          (std::copysign(1.0, m.right().ResolvedValue()) > 0)) {
        return Replace(m.left().node()); // x - 0 => x
      }
      if (m.right().IsNaN()) { // x - NaN => NaN
        return ReplaceFloat32(SilenceNaN(m.right().ResolvedValue()));
      }
      if (m.left().IsNaN()) { // NaN - x => NaN
        return ReplaceFloat32(SilenceNaN(m.left().ResolvedValue()));
      }
      if (m.IsFoldable()) { // L - R => (L - R)
        return ReplaceFloat32(m.left().ResolvedValue() -
                              m.right().ResolvedValue());
      }
      if (signalling_nan_propagation_ == kPropagateSignallingNan &&
          m.left().IsMinusZero()) {
        // -0.0 - round_down(-0.0 - R) => round_up(R)
        if (machine()->Float32RoundUp().IsSupported() &&
            m.right().IsFloat32RoundDown()) {
          if (m.right().InputAt(0)->opcode() == IrOpcode::kFloat32Sub) {
            Float32BinopMatcher mright0(m.right().InputAt(0));
            if (mright0.left().IsMinusZero()) {
              return Replace(graph()->NewNode(machine()->Float32RoundUp().op(),
                                              mright0.right().node()));
            }
          }
        }
        // -0.0 - R => -R
        node->RemoveInput(0);
        NodeProperties::ChangeOp(node, machine()->Float32Neg());
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kFloat64Add: {
      Float64BinopMatcher m(node);
      if (m.right().IsNaN()) { // x + NaN => NaN
        return ReplaceFloat64(SilenceNaN(m.right().ResolvedValue()));
      }
      if (m.left().IsNaN()) { // NaN + x => NaN
        return ReplaceFloat64(SilenceNaN(m.left().ResolvedValue()));
      }
      if (m.IsFoldable()) { // K + K => K (K stands for arbitrary constants)
        return ReplaceFloat64(m.left().ResolvedValue() +
                              m.right().ResolvedValue());
      }
      break;
    }
    case IrOpcode::kFloat64Sub: {
      Float64BinopMatcher m(node);
      if (signalling_nan_propagation_ == kPropagateSignallingNan &&
          m.right().Is(0) &&
          (base::Double(m.right().ResolvedValue()).Sign() > 0)) {
        return Replace(m.left().node()); // x - 0 => x
      }
      if (m.right().IsNaN()) { // x - NaN => NaN
        return ReplaceFloat64(SilenceNaN(m.right().ResolvedValue()));
      }
      if (m.left().IsNaN()) { // NaN - x => NaN
        return ReplaceFloat64(SilenceNaN(m.left().ResolvedValue()));
      }
      if (m.IsFoldable()) { // L - R => (L - R)
        return ReplaceFloat64(m.left().ResolvedValue() -
                              m.right().ResolvedValue());
      }
      if (signalling_nan_propagation_ == kPropagateSignallingNan &&
          m.left().IsMinusZero()) {
        // -0.0 - round_down(-0.0 - R) => round_up(R)
        if (machine()->Float64RoundUp().IsSupported() &&
            m.right().IsFloat64RoundDown()) {
          if (m.right().InputAt(0)->opcode() == IrOpcode::kFloat64Sub) {
            Float64BinopMatcher mright0(m.right().InputAt(0));
            if (mright0.left().IsMinusZero()) {
              return Replace(graph()->NewNode(machine()->Float64RoundUp().op(),
                                              mright0.right().node()));
            }
          }
        }
        // -0.0 - R => -R
        node->RemoveInput(0);
        NodeProperties::ChangeOp(node, machine()->Float64Neg());
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kFloat64Mul: {
      Float64BinopMatcher m(node);
      if (signalling_nan_propagation_ == kPropagateSignallingNan &&
          m.right().Is(1))
        return Replace(m.left().node()); // x * 1.0 => x
      if (m.right().Is(-1)) { // x * -1.0 => -0.0 - x
        node->ReplaceInput(0, Float64Constant(-0.0));
        node->ReplaceInput(1, m.left().node());
        NodeProperties::ChangeOp(node, machine()->Float64Sub());
        return Changed(node);
      }
      if (m.right().IsNaN()) { // x * NaN => NaN
        return ReplaceFloat64(SilenceNaN(m.right().ResolvedValue()));
      }
      if (m.IsFoldable()) { // K * K => K (K stands for arbitrary constants)
        return ReplaceFloat64(m.left().ResolvedValue() *
                              m.right().ResolvedValue());
      }
      if (m.right().Is(2)) { // x * 2.0 => x + x
        node->ReplaceInput(1, m.left().node());
        NodeProperties::ChangeOp(node, machine()->Float64Add());
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kFloat64Div: {
      Float64BinopMatcher m(node);
      if (signalling_nan_propagation_ == kPropagateSignallingNan &&
          m.right().Is(1))
        return Replace(m.left().node()); // x / 1.0 => x
      // TODO(ahaas): We could do x / 1.0 = x if we knew that x is not an sNaN.
      if (m.right().IsNaN()) { // x / NaN => NaN
        return ReplaceFloat64(SilenceNaN(m.right().ResolvedValue()));
      }
      if (m.left().IsNaN()) { // NaN / x => NaN
        return ReplaceFloat64(SilenceNaN(m.left().ResolvedValue()));
      }
      if (m.IsFoldable()) { // K / K => K (K stands for arbitrary constants)
        return ReplaceFloat64(
            base::Divide(m.left().ResolvedValue(), m.right().ResolvedValue()));
      }
      if (signalling_nan_propagation_ == kPropagateSignallingNan &&
          m.right().Is(-1)) { // x / -1.0 => -x
        node->RemoveInput(1);
        NodeProperties::ChangeOp(node, machine()->Float64Neg());
        return Changed(node);
      }
      if (m.right().IsNormal() && m.right().IsPositiveOrNegativePowerOf2()) {
        // All reciprocals of non-denormal powers of two can be represented
        // exactly, so division by power of two can be reduced to
        // multiplication by reciprocal, with the same result.
        node->ReplaceInput(1, Float64Constant(1.0 / m.right().ResolvedValue()));
        NodeProperties::ChangeOp(node, machine()->Float64Mul());
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kFloat64Mod: {
      Float64BinopMatcher m(node);
      if (m.right().Is(0)) { // x % 0 => NaN
        return ReplaceFloat64(std::numeric_limits<double>::quiet_NaN());
      }
      if (m.right().IsNaN()) { // x % NaN => NaN
        return ReplaceFloat64(SilenceNaN(m.right().ResolvedValue()));
      }
      if (m.left().IsNaN()) { // NaN % x => NaN
        return ReplaceFloat64(SilenceNaN(m.left().ResolvedValue()));
      }
      if (m.IsFoldable()) { // K % K => K (K stands for arbitrary constants)
        return ReplaceFloat64(
            Modulo(m.left().ResolvedValue(), m.right().ResolvedValue()));
      }
      break;
    }
    case IrOpcode::kFloat64Acos: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::acos(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Acosh: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::acosh(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Asin: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::asin(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Asinh: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::asinh(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Atan: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::atan(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Atanh: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::atanh(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Atan2: {
      Float64BinopMatcher m(node);
      if (m.right().IsNaN()) {
        return ReplaceFloat64(SilenceNaN(m.right().ResolvedValue()));
      }
      if (m.left().IsNaN()) {
        return ReplaceFloat64(SilenceNaN(m.left().ResolvedValue()));
      }
      if (m.IsFoldable()) {
        return ReplaceFloat64(base::ieee754::atan2(m.left().ResolvedValue(),
                                                   m.right().ResolvedValue()));
      }
      break;
    }
    case IrOpcode::kFloat64Cbrt: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::cbrt(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Cos: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(COS_IMPL(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Cosh: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::cosh(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Exp: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::exp(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Expm1: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::expm1(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Log: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::log(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Log1p: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::log1p(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Log10: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::log10(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Log2: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::log2(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Pow: {
      Float64BinopMatcher m(node);
      if (m.IsFoldable()) {
        return ReplaceFloat64(
            math::pow(m.left().ResolvedValue(), m.right().ResolvedValue()));
      } else if (m.right().Is(0.0)) { // x ** +-0.0 => 1.0
        return ReplaceFloat64(1.0);
      } else if (m.right().Is(2.0)) { // x ** 2.0 => x * x
        node->ReplaceInput(1, m.left().node());
        NodeProperties::ChangeOp(node, machine()->Float64Mul());
        return Changed(node);
      } else if (m.right().Is(0.5)) {
        // x ** 0.5 => if x <= -Infinity then Infinity else sqrt(0.0 + x)
        return Replace(Float64PowHalf(m.left().node()));
      }
      break;
    }
    case IrOpcode::kFloat64Sin: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(SIN_IMPL(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Sinh: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::sinh(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Tan: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::tan(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kFloat64Tanh: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(base::ieee754::tanh(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kChangeFloat32ToFloat64: {
      Float32Matcher m(node->InputAt(0));
      if (m.HasResolvedValue()) {
        if (signalling_nan_propagation_ == kSilenceSignallingNan &&
            std::isnan(m.ResolvedValue())) {
          return ReplaceFloat64(SilenceNaN(m.ResolvedValue()));
        }
        return ReplaceFloat64(m.ResolvedValue());
      }
      break;
    }
    case IrOpcode::kChangeFloat64ToInt32: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceInt32(FastD2IChecked(m.ResolvedValue()));
      if (m.IsChangeInt32ToFloat64()) return Replace(m.node()->InputAt(0));
      break;
    }
    case IrOpcode::kChangeFloat64ToInt64: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceInt64(static_cast<int64_t>(m.ResolvedValue()));
      if (m.IsChangeInt64ToFloat64()) return Replace(m.node()->InputAt(0));
      break;
    }
    case IrOpcode::kChangeFloat64ToUint32: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceInt32(FastD2UI(m.ResolvedValue()));
      if (m.IsChangeUint32ToFloat64()) return Replace(m.node()->InputAt(0));
      break;
    }
    case IrOpcode::kChangeInt32ToFloat64: {
      Int32Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(FastI2D(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kBitcastWord32ToWord64: {
      Int32Matcher m(node->InputAt(0));
      if (m.HasResolvedValue()) return ReplaceInt64(m.ResolvedValue());
      // No need to truncate the value, since top 32 bits are not important.
      if (m.IsTruncateInt64ToInt32()) return Replace(m.node()->InputAt(0));
      break;
    }
    case IrOpcode::kChangeInt32ToInt64: {
      Int32Matcher m(node->InputAt(0));
      if (m.HasResolvedValue()) return ReplaceInt64(m.ResolvedValue());
      break;
    }
    case IrOpcode::kChangeInt64ToFloat64: {
      Int64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(static_cast<double>(m.ResolvedValue()));
      if (m.IsChangeFloat64ToInt64()) return Replace(m.node()->InputAt(0));
      break;
    }
    case IrOpcode::kChangeUint32ToFloat64: {
      Uint32Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceFloat64(FastUI2D(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kChangeUint32ToUint64: {
      Uint32Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceInt64(static_cast<uint64_t>(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kTruncateFloat64ToWord32: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceInt32(DoubleToInt32(m.ResolvedValue()));
      if (m.IsChangeInt32ToFloat64()) return Replace(m.node()->InputAt(0));
      return NoChange();
    }
    case IrOpcode::kTruncateInt64ToInt32:
      return ReduceTruncateInt64ToInt32(node);
    case IrOpcode::kTruncateFloat64ToFloat32: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue()) {
        if (signalling_nan_propagation_ == kSilenceSignallingNan && m.IsNaN()) {
          return ReplaceFloat32(DoubleToFloat32(SilenceNaN(m.ResolvedValue())));
        }
        return ReplaceFloat32(DoubleToFloat32(m.ResolvedValue()));
      }
      if (signalling_nan_propagation_ == kPropagateSignallingNan &&
          m.IsChangeFloat32ToFloat64())
        return Replace(m.node()->InputAt(0));
      break;
    }
    case IrOpcode::kRoundFloat64ToInt32: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue()) {
        return ReplaceInt32(DoubleToInt32(m.ResolvedValue()));
      }
      if (m.IsChangeInt32ToFloat64()) return Replace(m.node()->InputAt(0));
      break;
    }
    case IrOpcode::kFloat64InsertLowWord32:
      return ReduceFloat64InsertLowWord32(node);
    case IrOpcode::kFloat64InsertHighWord32:
      return ReduceFloat64InsertHighWord32(node);
    case IrOpcode::kStore:
    case IrOpcode::kUnalignedStore:
      return ReduceStore(node);
    case IrOpcode::kFloat64Equal:
    case IrOpcode::kFloat64LessThan:
    case IrOpcode::kFloat64LessThanOrEqual:
      return ReduceFloat64Compare(node);
    case IrOpcode::kFloat64RoundDown:
      return ReduceFloat64RoundDown(node);
    case IrOpcode::kBitcastTaggedToWord:
    case IrOpcode::kBitcastTaggedToWordForTagAndSmiBits: {
      NodeMatcher m(node->InputAt(0));
      if (m.IsBitcastWordToTaggedSigned()) {
        RelaxEffectsAndControls(node);
        return Replace(m.InputAt(0));
      }
      break;
    }
    case IrOpcode::kBranch:
    case IrOpcode::kDeoptimizeIf:
    case IrOpcode::kDeoptimizeUnless:
#if V8_ENABLE_WEBASSEMBLY
    case IrOpcode::kTrapIf:
    case IrOpcode::kTrapUnless:
#endif
      return ReduceConditional(node);
    case IrOpcode::kInt64LessThan: {
      Int64BinopMatcher m(node);
      if (m.IsFoldable()) { // K < K => K (K stands for arbitrary constants)
        return ReplaceBool(m.left().ResolvedValue() <
                           m.right().ResolvedValue());
      }
      return ReduceWord64Comparisons(node);
    }
    case IrOpcode::kInt64LessThanOrEqual: {
      Int64BinopMatcher m(node);
      if (m.IsFoldable()) { // K <= K => K (K stands for arbitrary constants)
        return ReplaceBool(m.left().ResolvedValue() <=
                           m.right().ResolvedValue());
      }
      return ReduceWord64Comparisons(node);
    }
    case IrOpcode::kUint64LessThan: {
      Uint64BinopMatcher m(node);
      if (m.IsFoldable()) { // K < K => K (K stands for arbitrary constants)
        return ReplaceBool(m.left().ResolvedValue() <
                           m.right().ResolvedValue());
      }
      return ReduceWord64Comparisons(node);
    }
    case IrOpcode::kUint64LessThanOrEqual: {
      return ReduceUintNLessThanOrEqual<Word64Adapter>(node);
    }
    case IrOpcode::kFloat32Select:
    case IrOpcode::kFloat64Select:
    case IrOpcode::kWord32Select:
    case IrOpcode::kWord64Select: {
      Int32Matcher match(node->InputAt(0));
      if (match.HasResolvedValue()) {
        if (match.Is(0)) {
          return Replace(node->InputAt(2));
        } else {
          return Replace(node->InputAt(1));
        }
      }
      break;
    }
    case IrOpcode::kLoad:
    case IrOpcode::kProtectedLoad:
    case IrOpcode::kLoadTrapOnNull: {
      Node* input0 = node->InputAt(0);
      Node* input1 = node->InputAt(1);
      if (input0->opcode() == IrOpcode::kInt64Add) {
        Int64BinopMatcher m(input0);
        if (m.right().HasResolvedValue()) {
          int64_t value = m.right().ResolvedValue();
          node->ReplaceInput(0, m.left().node());
          Node* new_node = Int64Add(input1, Int64Constant(value));
          node->ReplaceInput(1, new_node);
          return Changed(node);
        }
      }
      break;
    }
    default:
      break;
  }
  return NoChange();
}
References v8::base::ieee754::acos(), v8::base::ieee754::acosh(), v8::base::ieee754::asin(), v8::base::ieee754::asinh(), v8::base::ieee754::atan(), v8::base::ieee754::atan2(), v8::base::ieee754::atanh(), v8::base::ieee754::cbrt(), v8::internal::compiler::NodeProperties::ChangeOp(), COS_IMPL, v8::base::ieee754::cosh(), v8::base::Divide(), v8::internal::DoubleToFloat32(), v8::internal::DoubleToInt32(), v8::base::ieee754::exp(), v8::base::ieee754::expm1(), v8::internal::FastD2IChecked(), v8::internal::FastD2UI(), v8::internal::FastI2D(), v8::internal::FastUI2D(), v8::internal::compiler::Float64Add(), Float64Constant(), Float64Mul(), Float64PowHalf(), graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::NodeMatcher::InputAt(), v8::internal::compiler::Node::InputAt(), Int32Constant(), Int32Sub(), Int64Add(), Int64Constant(), v8::internal::compiler::IntMatcher< T, kOpcode >::Is(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNaN(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), v8::internal::compiler::turboshaft::kBranch, v8::internal::kMaxInt, v8::internal::kMaxUInt32, kPropagateSignallingNan, kSilenceSignallingNan, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), v8::base::ieee754::log(), v8::base::ieee754::log10(), v8::base::ieee754::log1p(), v8::base::ieee754::log2(), machine(), v8::base::MulWithWraparound(), v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::OwnsInput(), v8::internal::math::pow(), v8::internal::compiler::ProjectionIndexOf(), ReduceConditional(), ReduceFloat64Compare(), ReduceFloat64InsertHighWord32(), ReduceFloat64InsertLowWord32(), ReduceFloat64RoundDown(), ReduceInt32Add(), ReduceInt32Div(), ReduceInt32Mod(), ReduceInt32Sub(), ReduceInt64Add(), ReduceInt64Div(), ReduceInt64Mod(), ReduceInt64Mul(), ReduceInt64Sub(), ReduceProjection(), ReduceStore(), ReduceTruncateInt64ToInt32(), ReduceUint32Div(), ReduceUint32Mod(), ReduceUint64Div(), ReduceUint64Mod(), ReduceWord32And(), ReduceWord32Comparisons(), ReduceWord32Equal(), ReduceWord32Or(), ReduceWord32Sar(), ReduceWord32Shl(), ReduceWord32Shr(), ReduceWord32Xor(), ReduceWord64And(), ReduceWord64Comparisons(), ReduceWord64Equal(), ReduceWord64Or(), ReduceWord64Sar(), ReduceWord64Shl(), ReduceWord64Shr(), ReduceWord64Xor(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), ReplaceBool(), ReplaceFloat32(), ReplaceFloat64(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt32(), ReplaceInt64(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::bits::RotateRight32(), v8::base::Double::Sign(), signalling_nan_propagation_, v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::SilenceNaN(), SIN_IMPL, v8::base::ieee754::sinh(), v8::base::ieee754::tan(), v8::base::ieee754::tanh(), Uint32Constant(), v8::internal::value, and v8::base::bits::WhichPowerOfTwo().
Referenced by ReduceWord64Comparisons().
ReduceConditional()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceConditional (Node * node) [private]
Definition at line 2936 of file machine-operator-reducer.cc.
                                                              {
  DCHECK(node->opcode() == IrOpcode::kBranch ||
         node->opcode() == IrOpcode::kDeoptimizeIf ||
         node->opcode() == IrOpcode::kDeoptimizeUnless ||
         node->opcode() == IrOpcode::kTrapIf ||
         node->opcode() == IrOpcode::kTrapUnless);
  // This reducer only applies operator reductions to the branch condition.
  // Reductions involving control flow happen elsewhere. Non-zero inputs are
  // considered true in all conditional ops.
  NodeMatcher condition(NodeProperties::GetValueInput(node, 0));
  Reduction reduction = NoChange();
  if (condition.IsTruncateInt64ToInt32()) {
    if (auto replacement =
            ReduceConditionalN<Word64Adapter>(condition.node())) {
      NodeProperties::ReplaceValueInput(node, *replacement, 0);
      reduction = Changed(node);
    }
  } else if (auto replacement = ReduceConditionalN<Word32Adapter>(node)) {
    NodeProperties::ReplaceValueInput(node, *replacement, 0);
    reduction = Changed(node);
  }
  return reduction.FollowedBy(SimplifyBranch(node));
}
References v8::internal::DCHECK(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), and SimplifyBranch().
Referenced by Reduce().
ReduceConditionalN()
template<typename WordNAdapter >
std::optional< Node * > v8::internal::compiler::MachineOperatorReducer::ReduceConditionalN (Node * node) [private]
Definition at line 2961 of file machine-operator-reducer.cc.
                                                                        {
  NodeMatcher condition(NodeProperties::GetValueInput(node, 0));
  // Branch conditions are 32-bit comparisons against zero, so they are the
  // opposite of a 32-bit `x == 0` node. To avoid repetition, we can reuse logic
  // for Word32Equal: if `x == 0` can reduce to `y == 0`, then branch(x) can
  // reduce to branch(y).
  auto replacements = ReduceWordEqualForConstantRhs<WordNAdapter, uint32_t>(
      condition.node(), 0);
  if (replacements && replacements->second == 0) return replacements->first;
  return {};
}
References v8::internal::compiler::NodeProperties::GetValueInput(), and v8::internal::compiler::NodeMatcher::node().
ReduceFloat64Compare()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceFloat64Compare (Node * node) [private]
Definition at line 2695 of file machine-operator-reducer.cc.
                                                                 {
  DCHECK(IrOpcode::kFloat64Equal == node->opcode() ||
         IrOpcode::kFloat64LessThan == node->opcode() ||
         IrOpcode::kFloat64LessThanOrEqual == node->opcode());
  Float64BinopMatcher m(node);
  if (m.IsFoldable()) {
    switch (node->opcode()) {
      case IrOpcode::kFloat64Equal:
        return ReplaceBool(m.left().ResolvedValue() ==
                           m.right().ResolvedValue());
      case IrOpcode::kFloat64LessThan:
        return ReplaceBool(m.left().ResolvedValue() <
                           m.right().ResolvedValue());
      case IrOpcode::kFloat64LessThanOrEqual:
        return ReplaceBool(m.left().ResolvedValue() <=
                           m.right().ResolvedValue());
      default:
        UNREACHABLE();
    }
  } else if ((m.left().IsChangeFloat32ToFloat64() &&
              m.right().IsChangeFloat32ToFloat64()) ||
             (m.left().IsChangeFloat32ToFloat64() &&
              IsFloat64RepresentableAsFloat32(m.right())) ||
             (IsFloat64RepresentableAsFloat32(m.left()) &&
              m.right().IsChangeFloat32ToFloat64())) {
    // As all Float32 values have an exact representation in Float64, comparing
    // two Float64 values both converted from Float32 is equivalent to comparing
    // the original Float32s, so we can ignore the conversions. We can also
    // reduce comparisons of converted Float64 values against constants that
    // can be represented exactly as Float32.
    switch (node->opcode()) {
      case IrOpcode::kFloat64Equal:
        NodeProperties::ChangeOp(node, machine()->Float32Equal());
        break;
      case IrOpcode::kFloat64LessThan:
        NodeProperties::ChangeOp(node, machine()->Float32LessThan());
        break;
      case IrOpcode::kFloat64LessThanOrEqual:
        NodeProperties::ChangeOp(node, machine()->Float32LessThanOrEqual());
        break;
      default:
        UNREACHABLE();
    }
    node->ReplaceInput(
        0, m.left().HasResolvedValue()
               ? Float32Constant(static_cast<float>(m.left().ResolvedValue()))
               : m.left().InputAt(0));
    node->ReplaceInput(
        1, m.right().HasResolvedValue()
               ? Float32Constant(static_cast<float>(m.right().ResolvedValue()))
               : m.right().InputAt(0));
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), Float32Constant(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::IsFloat64RepresentableAsFloat32(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::Node::opcode(), ReplaceBool(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), and v8::internal::UNREACHABLE().
Referenced by Reduce().
ReduceFloat64InsertHighWord32()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertHighWord32 (Node * node) [private]
Definition at line 2670 of file machine-operator-reducer.cc.
                                                                          {
  DCHECK_EQ(IrOpcode::kFloat64InsertHighWord32, node->opcode());
  Float64Matcher mlhs(node->InputAt(0));
  Uint32Matcher mrhs(node->InputAt(1));
  if (mlhs.HasResolvedValue() && mrhs.HasResolvedValue()) {
    return ReplaceFloat64(base::bit_cast<double>(
        (base::bit_cast<uint64_t>(mlhs.ResolvedValue()) &
         uint64_t{0xFFFFFFFF}) |
        (static_cast<uint64_t>(mrhs.ResolvedValue()) << 32)));
  }
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::opcode(), ReplaceFloat64(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by Reduce().
ReduceFloat64InsertLowWord32()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertLowWord32 (Node * node) [private]
Definition at line 2657 of file machine-operator-reducer.cc.
                                                                         {
  DCHECK_EQ(IrOpcode::kFloat64InsertLowWord32, node->opcode());
  Float64Matcher mlhs(node->InputAt(0));
  Uint32Matcher mrhs(node->InputAt(1));
  if (mlhs.HasResolvedValue() && mrhs.HasResolvedValue()) {
    return ReplaceFloat64(
        base::bit_cast<double>((base::bit_cast<uint64_t>(mlhs.ResolvedValue()) &
                                uint64_t{0xFFFFFFFF00000000}) |
                               mrhs.ResolvedValue()));
  }
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::opcode(), ReplaceFloat64(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by Reduce().
ReduceFloat64RoundDown()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceFloat64RoundDown (Node * node) [private]
Definition at line 2751 of file machine-operator-reducer.cc.
                                                                   {
  DCHECK_EQ(IrOpcode::kFloat64RoundDown, node->opcode());
  Float64Matcher m(node->InputAt(0));
  if (m.HasResolvedValue()) {
    return ReplaceFloat64(std::floor(m.ResolvedValue()));
  }
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::opcode(), ReplaceFloat64(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by Reduce().
ReduceInt32Add()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add (Node * node) [private]
Definition at line 1100 of file machine-operator-reducer.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kInt32Add, node->opcode());
  Int32BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x + 0 => x
  if (m.IsFoldable()) { // K + K => K (K stands for arbitrary constants)
    return ReplaceInt32(base::AddWithWraparound(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.left().IsInt32Sub()) {
    Int32BinopMatcher mleft(m.left().node());
    if (mleft.left().Is(0)) { // (0 - x) + y => y - x
      node->ReplaceInput(0, m.right().node());
      node->ReplaceInput(1, mleft.right().node());
      NodeProperties::ChangeOp(node, machine()->Int32Sub());
      return Changed(node).FollowedBy(ReduceInt32Sub(node));
    }
  }
  if (m.right().IsInt32Sub()) {
    Int32BinopMatcher mright(m.right().node());
    if (mright.left().Is(0)) { // y + (0 - x) => y - x
      node->ReplaceInput(1, mright.right().node());
      NodeProperties::ChangeOp(node, machine()->Int32Sub());
      return Changed(node).FollowedBy(ReduceInt32Sub(node));
    }
  }
  // (x + Int32Constant(a)) + Int32Constant(b)) => x + Int32Constant(a + b)
  if (m.right().HasResolvedValue() && m.left().IsInt32Add()) {
    Int32BinopMatcher n(m.left().node());
    if (n.right().HasResolvedValue() && m.OwnsInput(m.left().node())) {
      node->ReplaceInput(
          1, Int32Constant(base::AddWithWraparound(m.right().ResolvedValue(),
                                                   n.right().ResolvedValue())));
      node->ReplaceInput(0, n.left().node());
      return Changed(node);
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, Int32Constant(), Int32Sub(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::OwnsInput(), ReduceInt32Sub(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt32(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Int32Add(), Reduce(), ReduceInt32Sub(), and v8::internal::compiler::Word32Adapter::ReduceIntNAdd().
ReduceInt32Div()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div (Node * node) [private]
Definition at line 1236 of file machine-operator-reducer.cc.
                                                           {
  Int32BinopMatcher m(node);
  if (m.left().Is(0)) return Replace(m.left().node()); // 0 / x => 0
  if (m.right().Is(0)) return Replace(m.right().node()); // x / 0 => 0
  if (m.right().Is(1)) return Replace(m.left().node()); // x / 1 => x
  if (m.IsFoldable()) { // K / K => K (K stands for arbitrary constants)
    return ReplaceInt32(base::bits::SignedDiv32(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.LeftEqualsRight()) { // x / x => x != 0
    Node* const zero = Int32Constant(0);
    return Replace(Word32Equal(Word32Equal(m.left().node(), zero), zero));
  }
  if (m.right().Is(-1)) { // x / -1 => 0 - x
    node->ReplaceInput(0, Int32Constant(0));
    node->ReplaceInput(1, m.left().node());
    node->TrimInputCount(2);
    NodeProperties::ChangeOp(node, machine()->Int32Sub());
    return Changed(node);
  }
  if (m.right().HasResolvedValue()) {
    int32_t const divisor = m.right().ResolvedValue();
    Node* const dividend = m.left().node();
    Node* quotient = dividend;
    if (base::bits::IsPowerOfTwo(Abs(divisor))) {
      uint32_t const shift = base::bits::WhichPowerOfTwo(Abs(divisor));
      DCHECK_NE(0u, shift);
      if (shift > 1) {
        quotient = Word32Sar(quotient, 31);
      }
      quotient = Int32Add(Word32Shr(quotient, 32u - shift), dividend);
      quotient = Word32Sar(quotient, shift);
    } else {
      quotient = Int32Div(quotient, Abs(divisor));
    }
    if (divisor < 0) {
      node->ReplaceInput(0, Int32Constant(0));
      node->ReplaceInput(1, quotient);
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Int32Sub());
      return Changed(node);
    }
    return Replace(quotient);
  }
  return NoChange();
}
References v8::internal::Abs(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_NE, Int32Add(), Int32Constant(), Int32Div(), Int32Sub(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt32(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::bits::SignedDiv32(), v8::internal::compiler::Node::TrimInputCount(), v8::base::bits::WhichPowerOfTwo(), Word32Equal(), Word32Sar(), Word32Shr(), and v8::internal::zero.
Referenced by Reduce().
ReduceInt32Mod()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod (Node * node) [private]
Definition at line 1394 of file machine-operator-reducer.cc.
                                                           {
  Int32BinopMatcher m(node);
  if (m.left().Is(0)) return Replace(m.left().node()); // 0 % x => 0
  if (m.right().Is(0)) return Replace(m.right().node()); // x % 0 => 0
  if (m.right().Is(1)) return ReplaceInt32(0); // x % 1 => 0
  if (m.right().Is(-1)) return ReplaceInt32(0); // x % -1 => 0
  if (m.LeftEqualsRight()) return ReplaceInt32(0); // x % x => 0
  if (m.IsFoldable()) { // K % K => K (K stands for arbitrary constants)
    return ReplaceInt32(base::bits::SignedMod32(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.right().HasResolvedValue()) {
    Node* const dividend = m.left().node();
    uint32_t const divisor = Abs(m.right().ResolvedValue());
    if (base::bits::IsPowerOfTwo(divisor)) {
      uint32_t const mask = divisor - 1;
      Node* const zero = Int32Constant(0);
      Diamond d(graph(), common(),
                graph()->NewNode(machine()->Int32LessThan(), dividend, zero),
                BranchHint::kFalse);
      return Replace(
          d.Phi(MachineRepresentation::kWord32,
                Int32Sub(zero, Word32And(Int32Sub(zero, dividend), mask)),
                Word32And(dividend, mask)));
    } else {
      Node* quotient = Int32Div(dividend, divisor);
      DCHECK_EQ(dividend, node->InputAt(0));
      node->ReplaceInput(1, Int32Mul(quotient, Int32Constant(divisor)));
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Int32Sub());
    }
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::Abs(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), DCHECK_EQ, graph(), v8::internal::compiler::Node::InputAt(), Int32Constant(), Int32Div(), Int32Mul(), Int32Sub(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::base::bits::IsPowerOfTwo(), v8::internal::kFalse, v8::internal::kWord32, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::internal::compiler::Diamond::Phi(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt32(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::bits::SignedMod32(), v8::internal::compiler::Node::TrimInputCount(), Word32And(), and v8::internal::zero.
Referenced by Reduce().
ReduceInt32Sub()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub (Node * node) [private]
Definition at line 1162 of file machine-operator-reducer.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kInt32Sub, node->opcode());
  Int32BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x - 0 => x
  if (m.IsFoldable()) { // K - K => K (K stands for arbitrary constants)
    return ReplaceInt32(base::SubWithWraparound(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.LeftEqualsRight()) return ReplaceInt32(0); // x - x => 0
  if (m.right().HasResolvedValue()) { // x - K => x + -K
    node->ReplaceInput(
        1,
        Int32Constant(base::NegateWithWraparound(m.right().ResolvedValue())));
    NodeProperties::ChangeOp(node, machine()->Int32Add());
    return Changed(node).FollowedBy(ReduceInt32Add(node));
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, Int32Add(), Int32Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::base::NegateWithWraparound(), v8::internal::compiler::Node::opcode(), ReduceInt32Add(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt32(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Int32Sub(), Reduce(), ReduceInt32Add(), and ReduceWord32Sar().
ReduceInt64Add()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt64Add (Node * node) [private]
Definition at line 1140 of file machine-operator-reducer.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kInt64Add, node->opcode());
  Int64BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x + 0 => 0
  if (m.IsFoldable()) {
    return ReplaceInt64(base::AddWithWraparound(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  // (x + Int64Constant(a)) + Int64Constant(b) => x + Int64Constant(a + b)
  if (m.right().HasResolvedValue() && m.left().IsInt64Add()) {
    Int64BinopMatcher n(m.left().node());
    if (n.right().HasResolvedValue() && m.OwnsInput(m.left().node())) {
      node->ReplaceInput(
          1, Int64Constant(base::AddWithWraparound(m.right().ResolvedValue(),
                                                   n.right().ResolvedValue())));
      node->ReplaceInput(0, n.left().node());
      return Changed(node);
    }
  }
  return NoChange();
}
References DCHECK_EQ, Int64Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::OwnsInput(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt64(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Int64Add(), Reduce(), ReduceInt64Sub(), and v8::internal::compiler::Word64Adapter::ReduceIntNAdd().
ReduceInt64Div()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div (Node * node) [private]
Definition at line 1283 of file machine-operator-reducer.cc.
                                                           {
  Int64BinopMatcher m(node);
  if (m.left().Is(0)) return Replace(m.left().node()); // 0 / x => 0
  if (m.right().Is(0)) return Replace(m.right().node()); // x / 0 => 0
  if (m.right().Is(1)) return Replace(m.left().node()); // x / 1 => x
  if (m.IsFoldable()) { // K / K => K (K stands for arbitrary constants)
    return ReplaceInt64(base::bits::SignedDiv64(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.LeftEqualsRight()) { // x / x => x != 0
    Node* const zero = Int64Constant(0);
    // {Word64Equal} can get reduced to a bool/int32, but we need this
    // operation to produce an int64.
    return Replace(ChangeInt32ToInt64(
        Word64Equal(Word64Equal(m.left().node(), zero), zero)));
  }
  if (m.right().Is(-1)) { // x / -1 => 0 - x
    node->ReplaceInput(0, Int64Constant(0));
    node->ReplaceInput(1, m.left().node());
    node->TrimInputCount(2);
    NodeProperties::ChangeOp(node, machine()->Int64Sub());
    return Changed(node);
  }
  if (m.right().HasResolvedValue()) {
    int64_t const divisor = m.right().ResolvedValue();
    Node* const dividend = m.left().node();
    Node* quotient = dividend;
    if (base::bits::IsPowerOfTwo(Abs(divisor))) {
      uint32_t const shift = base::bits::WhichPowerOfTwo(Abs(divisor));
      DCHECK_NE(0u, shift);
      if (shift > 1) {
        quotient = Word64Sar(quotient, 63);
      }
      quotient = Int64Add(Word64Shr(quotient, 64u - shift), dividend);
      quotient = Word64Sar(quotient, shift);
    } else {
      quotient = Int64Div(quotient, Abs(divisor));
    }
    if (divisor < 0) {
      node->ReplaceInput(0, Int64Constant(0));
      node->ReplaceInput(1, quotient);
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Int64Sub());
      return Changed(node);
    }
    return Replace(quotient);
  }
  return NoChange();
}
References v8::internal::Abs(), ChangeInt32ToInt64(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_NE, Int64Add(), Int64Constant(), Int64Div(), Int64Sub(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt64(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::bits::SignedDiv64(), v8::internal::compiler::Node::TrimInputCount(), v8::base::bits::WhichPowerOfTwo(), Word64Equal(), Word64Sar(), Word64Shr(), and v8::internal::zero.
Referenced by Reduce().
ReduceInt64Mod()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod (Node * node) [private]
Definition at line 1430 of file machine-operator-reducer.cc.
                                                           {
  Int64BinopMatcher m(node);
  if (m.left().Is(0)) return Replace(m.left().node()); // 0 % x => 0
  if (m.right().Is(0)) return Replace(m.right().node()); // x % 0 => 0
  if (m.right().Is(1)) return ReplaceInt64(0); // x % 1 => 0
  if (m.right().Is(-1)) return ReplaceInt64(0); // x % -1 => 0
  if (m.LeftEqualsRight()) return ReplaceInt64(0); // x % x => 0
  if (m.IsFoldable()) { // K % K => K (K stands for arbitrary constants)
    return ReplaceInt64(base::bits::SignedMod64(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.right().HasResolvedValue()) {
    Node* const dividend = m.left().node();
    uint64_t const divisor = Abs(m.right().ResolvedValue());
    if (base::bits::IsPowerOfTwo(divisor)) {
      uint64_t const mask = divisor - 1;
      Node* const zero = Int64Constant(0);
      Diamond d(graph(), common(),
                graph()->NewNode(machine()->Int64LessThan(), dividend, zero),
                BranchHint::kFalse);
      return Replace(
          d.Phi(MachineRepresentation::kWord64,
                Int64Sub(zero, Word64And(Int64Sub(zero, dividend), mask)),
                Word64And(dividend, mask)));
    } else {
      Node* quotient = Int64Div(dividend, divisor);
      DCHECK_EQ(dividend, node->InputAt(0));
      node->ReplaceInput(1, Int64Mul(quotient, Int64Constant(divisor)));
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Int64Sub());
    }
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::Abs(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), DCHECK_EQ, graph(), v8::internal::compiler::Node::InputAt(), Int64Constant(), Int64Div(), Int64Mul(), Int64Sub(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::base::bits::IsPowerOfTwo(), v8::internal::kFalse, v8::internal::kWord64, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::internal::compiler::Diamond::Phi(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt64(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::bits::SignedMod64(), v8::internal::compiler::Node::TrimInputCount(), Word64And(), and v8::internal::zero.
Referenced by Reduce().
ReduceInt64Mul()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul (Node * node) [private]
Definition at line 1200 of file machine-operator-reducer.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kInt64Mul, node->opcode());
  Int64BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.right().node()); // x * 0 => 0
  if (m.right().Is(1)) return Replace(m.left().node()); // x * 1 => x
  if (m.IsFoldable()) { // K * K => K (K stands for arbitrary constants)
    return ReplaceInt64(base::MulWithWraparound(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.right().Is(-1)) { // x * -1 => 0 - x
    node->ReplaceInput(0, Int64Constant(0));
    node->ReplaceInput(1, m.left().node());
    NodeProperties::ChangeOp(node, machine()->Int64Sub());
    return Changed(node);
  }
  if (m.right().IsPowerOf2()) { // x * 2^n => x << n
    node->ReplaceInput(
        1,
        Int64Constant(base::bits::WhichPowerOfTwo(m.right().ResolvedValue())));
    NodeProperties::ChangeOp(node, machine()->Word64Shl());
    return Changed(node).FollowedBy(ReduceWord64Shl(node));
  }
  // (x * Int64Constant(a)) * Int64Constant(b)) => x * Int64Constant(a * b)
  if (m.right().HasResolvedValue() && m.left().IsInt64Mul()) {
    Int64BinopMatcher n(m.left().node());
    if (n.right().HasResolvedValue() && m.OwnsInput(m.left().node())) {
      node->ReplaceInput(
          1, Int64Constant(base::MulWithWraparound(m.right().ResolvedValue(),
                                                   n.right().ResolvedValue())));
      node->ReplaceInput(0, n.left().node());
      return Changed(node);
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, Int64Constant(), Int64Sub(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::base::MulWithWraparound(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::OwnsInput(), ReduceWord64Shl(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt64(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), and v8::base::bits::WhichPowerOfTwo().
Referenced by Reduce().
ReduceInt64Sub()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub (Node * node) [private]
Definition at line 1181 of file machine-operator-reducer.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kInt64Sub, node->opcode());
  Int64BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x - 0 => x
  if (m.IsFoldable()) { // K - K => K (K stands for arbitrary constants)
    return ReplaceInt64(base::SubWithWraparound(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.LeftEqualsRight()) return Replace(Int64Constant(0)); // x - x => 0
  if (m.right().HasResolvedValue()) { // x - K => x + -K
    node->ReplaceInput(
        1,
        Int64Constant(base::NegateWithWraparound(m.right().ResolvedValue())));
    NodeProperties::ChangeOp(node, machine()->Int64Add());
    return Changed(node).FollowedBy(ReduceInt64Add(node));
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, Int64Add(), Int64Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::base::NegateWithWraparound(), v8::internal::compiler::Node::opcode(), ReduceInt64Add(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt64(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Int64Sub(), and Reduce().
ReduceProjection()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceProjection (size_t index, Node * node) [private]
Definition at line 1567 of file machine-operator-reducer.cc.
                                                                           {
  switch (node->opcode()) {
    case IrOpcode::kInt32AddWithOverflow: {
      DCHECK(index == 0 || index == 1);
      Int32BinopMatcher m(node);
      if (m.IsFoldable()) {
        int32_t val;
        bool ovf = base::bits::SignedAddOverflow32(
            m.left().ResolvedValue(), m.right().ResolvedValue(), &val);
        return ReplaceInt32(index == 0 ? val : ovf);
      }
      if (m.right().Is(0)) {
        return Replace(index == 0 ? m.left().node() : m.right().node());
      }
      break;
    }
    case IrOpcode::kInt32SubWithOverflow: {
      DCHECK(index == 0 || index == 1);
      Int32BinopMatcher m(node);
      if (m.IsFoldable()) {
        int32_t val;
        bool ovf = base::bits::SignedSubOverflow32(
            m.left().ResolvedValue(), m.right().ResolvedValue(), &val);
        return ReplaceInt32(index == 0 ? val : ovf);
      }
      if (m.right().Is(0)) {
        return Replace(index == 0 ? m.left().node() : m.right().node());
      }
      break;
    }
    case IrOpcode::kInt32MulWithOverflow: {
      DCHECK(index == 0 || index == 1);
      Int32BinopMatcher m(node);
      if (m.IsFoldable()) {
        int32_t val;
        bool ovf = base::bits::SignedMulOverflow32(
            m.left().ResolvedValue(), m.right().ResolvedValue(), &val);
        return ReplaceInt32(index == 0 ? val : ovf);
      }
      if (m.right().Is(0)) {
        return Replace(m.right().node());
      }
      if (m.right().Is(1)) {
        return index == 0 ? Replace(m.left().node()) : ReplaceInt32(0);
      }
      break;
    }
    default:
      break;
  }
  return NoChange();
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), ReplaceInt32(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::bits::SignedAddOverflow32(), v8::base::bits::SignedMulOverflow32(), and v8::base::bits::SignedSubOverflow32().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::MachineOperatorReducer::reducer_name () const [inline], [override]
Definition at line 40 of file machine-operator-reducer.h.
{ return "MachineOperatorReducer"; }
ReduceStore()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceStore (Node * node) [private]
Definition at line 1524 of file machine-operator-reducer.cc.
                                                        {
  NodeMatcher nm(node);
  DCHECK(nm.IsStore() || nm.IsUnalignedStore());
  MachineRepresentation rep =
      nm.IsStore() ? StoreRepresentationOf(node->op()).representation()
                   : UnalignedStoreRepresentationOf(node->op());
  const int value_input = 2;
  Node* const value = node->InputAt(value_input);
  switch (value->opcode()) {
    case IrOpcode::kWord32And: {
      Uint32BinopMatcher m(value);
      if (m.right().HasResolvedValue() &&
          ((rep == MachineRepresentation::kWord8 &&
            (m.right().ResolvedValue() & 0xFF) == 0xFF) ||
           (rep == MachineRepresentation::kWord16 &&
            (m.right().ResolvedValue() & 0xFFFF) == 0xFFFF))) {
        node->ReplaceInput(value_input, m.left().node());
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kWord32Sar: {
      Int32BinopMatcher m(value);
      if (m.left().IsWord32Shl() && ((rep == MachineRepresentation::kWord8 &&
                                      m.right().IsInRange(1, 24)) ||
                                     (rep == MachineRepresentation::kWord16 &&
                                      m.right().IsInRange(1, 16)))) {
        Int32BinopMatcher mleft(m.left().node());
        if (mleft.right().Is(m.right().ResolvedValue())) {
          node->ReplaceInput(value_input, mleft.left().node());
          return Changed(node);
        }
      }
      break;
    }
    default:
      break;
  }
  return NoChange();
}
References v8::internal::DCHECK(), v8::internal::compiler::Node::InputAt(), v8::internal::kWord16, v8::internal::kWord8, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::StoreRepresentation::representation(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::StoreRepresentationOf(), v8::internal::compiler::UnalignedStoreRepresentationOf(), and v8::internal::value.
Referenced by Reduce().
ReduceTruncateInt64ToInt32()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32 (Node * node) [private]
Definition at line 1061 of file machine-operator-reducer.cc.
                                                                       {
  Int64Matcher m(node->InputAt(0));
  if (m.HasResolvedValue())
    return ReplaceInt32(static_cast<int32_t>(m.ResolvedValue()));
  if (m.IsChangeInt32ToInt64() || m.IsChangeUint32ToUint64())
    return Replace(m.node()->InputAt(0));
  // TruncateInt64ToInt32(BitcastTaggedToWordForTagAndSmiBits(Load(x))) =>
  // Load(x)
  // where the new Load uses Int32 rather than the tagged representation.
  if (m.IsBitcastTaggedToWordForTagAndSmiBits() && m.node()->UseCount() == 1) {
    Node* input = m.node()->InputAt(0);
    if (input->opcode() == IrOpcode::kLoad ||
        input->opcode() == IrOpcode::kLoadImmutable) {
      LoadRepresentation load_rep = LoadRepresentationOf(input->op());
      if (ElementSizeLog2Of(load_rep.representation()) == 2) {
        // Ensure that the value output of the load is only ever used by the
        // BitcastTaggedToWordForTagAndSmiBits.
        int value_edges = 0;
        for (Edge edge : input->use_edges()) {
          if (NodeProperties::IsValueEdge(edge)) ++value_edges;
        }
        if (value_edges == 1) {
          // Removing the input is required as node is replaced by the Load, but
          // is still used by the the BitcastTaggedToWordForTagAndSmiBits, so
          // will prevent future CanCover calls being true.
          m.node()->RemoveInput(0);
          NodeProperties::ChangeOp(
              input,
              input->opcode() == IrOpcode::kLoad
                  ? machine()->Load(LoadRepresentation::Int32())
                  : machine()->LoadImmutable(LoadRepresentation::Int32()));
          return Replace(input);
        }
      }
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::ElementSizeLog2Of(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::MachineType::Int32(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::Load(), v8::internal::compiler::LoadRepresentationOf(), machine(), v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), ReplaceInt32(), v8::internal::MachineType::representation(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::internal::compiler::Node::use_edges(), and v8::internal::compiler::Node::UseCount().
Referenced by Reduce(), and TruncateInt64ToInt32().
ReduceUint32Div()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div (Node * node) [private]
Definition at line 1333 of file machine-operator-reducer.cc.
                                                            {
  Uint32BinopMatcher m(node);
  if (m.left().Is(0)) return Replace(m.left().node()); // 0 / x => 0
  if (m.right().Is(0)) return Replace(m.right().node()); // x / 0 => 0
  if (m.right().Is(1)) return Replace(m.left().node()); // x / 1 => x
  if (m.IsFoldable()) { // K / K => K (K stands for arbitrary constants)
    return ReplaceUint32(base::bits::UnsignedDiv32(m.left().ResolvedValue(),
                                                   m.right().ResolvedValue()));
  }
  if (m.LeftEqualsRight()) { // x / x => x != 0
    Node* const zero = Int32Constant(0);
    return Replace(Word32Equal(Word32Equal(m.left().node(), zero), zero));
  }
  if (m.right().HasResolvedValue()) {
    Node* const dividend = m.left().node();
    uint32_t const divisor = m.right().ResolvedValue();
    if (base::bits::IsPowerOfTwo(divisor)) { // x / 2^n => x >> n
      node->ReplaceInput(1, Uint32Constant(base::bits::WhichPowerOfTwo(
                                m.right().ResolvedValue())));
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Word32Shr());
      return Changed(node);
    } else {
      return Replace(Uint32Div(dividend, divisor));
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), Int32Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceUint32(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::Node::TrimInputCount(), Uint32Constant(), Uint32Div(), v8::base::bits::UnsignedDiv32(), v8::base::bits::WhichPowerOfTwo(), Word32Equal(), Word32Shr(), and v8::internal::zero.
Referenced by Reduce().
ReduceUint32Mod()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod (Node * node) [private]
Definition at line 1466 of file machine-operator-reducer.cc.
                                                            {
  Uint32BinopMatcher m(node);
  if (m.left().Is(0)) return Replace(m.left().node()); // 0 % x => 0
  if (m.right().Is(0)) return Replace(m.right().node()); // x % 0 => 0
  if (m.right().Is(1)) return ReplaceUint32(0); // x % 1 => 0
  if (m.LeftEqualsRight()) return ReplaceUint32(0); // x % x => 0
  if (m.IsFoldable()) { // K % K => K (K stands for arbitrary constants)
    return ReplaceUint32(base::bits::UnsignedMod32(m.left().ResolvedValue(),
                                                   m.right().ResolvedValue()));
  }
  if (m.right().HasResolvedValue()) {
    Node* const dividend = m.left().node();
    uint32_t const divisor = m.right().ResolvedValue();
    if (base::bits::IsPowerOfTwo(divisor)) { // x % 2^n => x & 2^n-1
      node->ReplaceInput(1, Uint32Constant(m.right().ResolvedValue() - 1));
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Word32And());
    } else {
      Node* quotient = Uint32Div(dividend, divisor);
      DCHECK_EQ(dividend, node->InputAt(0));
      node->ReplaceInput(1, Int32Mul(quotient, Uint32Constant(divisor)));
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Int32Sub());
    }
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, v8::internal::compiler::Node::InputAt(), Int32Mul(), Int32Sub(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceUint32(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::Node::TrimInputCount(), Uint32Constant(), Uint32Div(), v8::base::bits::UnsignedMod32(), and Word32And().
Referenced by Reduce().
ReduceUint64Div()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div (Node * node) [private]
Definition at line 1362 of file machine-operator-reducer.cc.
                                                            {
  Uint64BinopMatcher m(node);
  if (m.left().Is(0)) return Replace(m.left().node()); // 0 / x => 0
  if (m.right().Is(0)) return Replace(m.right().node()); // x / 0 => 0
  if (m.right().Is(1)) return Replace(m.left().node()); // x / 1 => x
  if (m.IsFoldable()) { // K / K => K (K stands for arbitrary constants)
    return ReplaceUint64(base::bits::UnsignedDiv64(m.left().ResolvedValue(),
                                                   m.right().ResolvedValue()));
  }
  if (m.LeftEqualsRight()) { // x / x => x != 0
    Node* const zero = Int64Constant(0);
    // {Word64Equal} can get reduced to a bool/int32, but we need this
    // operation to produce an int64.
    return Replace(ChangeInt32ToInt64(
        Word64Equal(Word64Equal(m.left().node(), zero), zero)));
  }
  if (m.right().HasResolvedValue()) {
    Node* const dividend = m.left().node();
    uint64_t const divisor = m.right().ResolvedValue();
    if (base::bits::IsPowerOfTwo(divisor)) { // x / 2^n => x >> n
      node->ReplaceInput(1, Uint64Constant(base::bits::WhichPowerOfTwo(
                                m.right().ResolvedValue())));
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Word64Shr());
      return Changed(node);
    } else {
      return Replace(Uint64Div(dividend, divisor));
    }
  }
  return NoChange();
}
References ChangeInt32ToInt64(), v8::internal::compiler::NodeProperties::ChangeOp(), Int64Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceUint64(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::Node::TrimInputCount(), Uint64Constant(), Uint64Div(), v8::base::bits::UnsignedDiv64(), v8::base::bits::WhichPowerOfTwo(), Word64Equal(), Word64Shr(), and v8::internal::zero.
Referenced by Reduce().
ReduceUint64Mod()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod (Node * node) [private]
Definition at line 1495 of file machine-operator-reducer.cc.
                                                            {
  Uint64BinopMatcher m(node);
  if (m.left().Is(0)) return Replace(m.left().node()); // 0 % x => 0
  if (m.right().Is(0)) return Replace(m.right().node()); // x % 0 => 0
  if (m.right().Is(1)) return ReplaceUint64(0); // x % 1 => 0
  if (m.LeftEqualsRight()) return ReplaceUint64(0); // x % x => 0
  if (m.IsFoldable()) { // K % K => K (K stands for arbitrary constants)
    return ReplaceUint64(base::bits::UnsignedMod64(m.left().ResolvedValue(),
                                                   m.right().ResolvedValue()));
  }
  if (m.right().HasResolvedValue()) {
    Node* const dividend = m.left().node();
    uint64_t const divisor = m.right().ResolvedValue();
    if (base::bits::IsPowerOfTwo(divisor)) { // x % 2^n => x & 2^n-1
      node->ReplaceInput(1, Uint64Constant(m.right().ResolvedValue() - 1));
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Word64And());
    } else {
      Node* quotient = Uint64Div(dividend, divisor);
      DCHECK_EQ(dividend, node->InputAt(0));
      node->ReplaceInput(1, Int64Mul(quotient, Uint64Constant(divisor)));
      node->TrimInputCount(2);
      NodeProperties::ChangeOp(node, machine()->Int64Sub());
    }
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, v8::internal::compiler::Node::InputAt(), Int64Mul(), Int64Sub(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceUint64(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::Node::TrimInputCount(), Uint64Constant(), Uint64Div(), v8::base::bits::UnsignedMod64(), and Word64And().
Referenced by Reduce().
ReduceUintNLessThanOrEqual()
template<typename WordNAdapter >
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceUintNLessThanOrEqual (Node * node) [private]
Definition at line 2252 of file machine-operator-reducer.cc.
                                                                       {
  using A = WordNAdapter;
  A a(this);
  typename A::UintNBinopMatcher m(node);
  typename A::uintN_t kMaxUIntN =
      std::numeric_limits<typename A::uintN_t>::max();
  if (m.left().Is(0)) return ReplaceBool(true); // 0 <= x => true
  if (m.right().Is(kMaxUIntN)) return ReplaceBool(true); // x <= M => true
  if (m.IsFoldable()) { // K <= K => K (K stands for arbitrary constants)
    return ReplaceBool(m.left().ResolvedValue() <= m.right().ResolvedValue());
  }
  if (m.LeftEqualsRight()) return ReplaceBool(true); // x <= x => true
  if (m.right().Is(0)) { // x <= 0 => x == 0
    NodeProperties::ChangeOp(node, a.WordNEqual(machine()));
    return Changed(node);
  }
  return a.ReduceWordNComparisons(node);
}
References v8::internal::A, v8::internal::compiler::NodeProperties::ChangeOp(), machine(), and ReplaceBool().
ReduceWord32And()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32And (Node * node) [private]
Definition at line 2373 of file machine-operator-reducer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kWord32And, node->opcode());
  Reduction reduction = ReduceWordNAnd<Word32Adapter>(node);
  if (reduction.Changed()) {
    return reduction;
  }
  // Attempt to detect multiple bitfield checks from the same bitfield struct
  // and fold them into a single check.
  Int32BinopMatcher m(node);
  if (auto right_bitfield = BitfieldCheck::Detect(m.right().node())) {
    if (auto left_bitfield = BitfieldCheck::Detect(m.left().node())) {
      if (auto combined_bitfield = left_bitfield->TryCombine(*right_bitfield)) {
        Node* source = combined_bitfield->source;
        if (combined_bitfield->truncate_from_64_bit) {
          source = TruncateInt64ToInt32(source);
        }
        node->ReplaceInput(0, Word32And(source, combined_bitfield->mask));
        node->ReplaceInput(1, Int32Constant(combined_bitfield->masked_value));
        NodeProperties::ChangeOp(node, machine()->Word32Equal());
        return Changed(node).FollowedBy(ReduceWord32Equal(node));
      }
    }
  }
  return NoChange();
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, Int32Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::Node::opcode(), ReduceWord32Equal(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), TruncateInt64ToInt32(), Word32And(), and Word32Equal().
Referenced by Reduce(), ReduceWord32Shl(), v8::internal::compiler::Word32Adapter::ReduceWordNAnd(), and Word32And().
ReduceWord32Comparisons()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32Comparisons (Node * node) [private]
Definition at line 1647 of file machine-operator-reducer.cc.
                                                                    {
  DCHECK(node->opcode() == IrOpcode::kInt32LessThan ||
         node->opcode() == IrOpcode::kInt32LessThanOrEqual ||
         node->opcode() == IrOpcode::kUint32LessThan ||
         node->opcode() == IrOpcode::kUint32LessThanOrEqual);
  Int32BinopMatcher m(node);
  // (x >> K) < (y >> K) => x < y if only zeros shifted out
  if (m.left().op() == machine()->Word32SarShiftOutZeros() &&
      m.right().op() == machine()->Word32SarShiftOutZeros()) {
    Int32BinopMatcher mleft(m.left().node());
    Int32BinopMatcher mright(m.right().node());
    if (mleft.right().HasResolvedValue() &&
        mright.right().Is(mleft.right().ResolvedValue())) {
      node->ReplaceInput(0, mleft.left().node());
      node->ReplaceInput(1, mright.left().node());
      return Changed(node);
    }
  }
  // Simplifying (x >> n) <= k into x <= (k << n), with "k << n" being
  // computed here at compile time.
  if (m.right().HasResolvedValue() &&
      m.left().op() == machine()->Word32SarShiftOutZeros() &&
      m.left().node()->UseCount() == 1) {
    uint32_t right = m.right().ResolvedValue();
    Int32BinopMatcher mleft(m.left().node());
    if (mleft.right().HasResolvedValue()) {
      auto shift = mleft.right().ResolvedValue();
      if (CanRevertLeftShiftWithRightShift<int32_t>(right, shift)) {
        node->ReplaceInput(0, mleft.left().node());
        node->ReplaceInput(1, Int32Constant(right << shift));
        return Changed(node);
      }
    }
  }
  // Simplifying k <= (x >> n) into (k << n) <= x, with "k << n" being
  // computed here at compile time.
  if (m.left().HasResolvedValue() &&
      m.right().op() == machine()->Word32SarShiftOutZeros() &&
      m.right().node()->UseCount() == 1) {
    uint32_t left = m.left().ResolvedValue();
    Int32BinopMatcher mright(m.right().node());
    if (mright.right().HasResolvedValue()) {
      auto shift = mright.right().ResolvedValue();
      if (CanRevertLeftShiftWithRightShift<int32_t>(left, shift)) {
        node->ReplaceInput(0, Int32Constant(left << shift));
        node->ReplaceInput(1, mright.left().node());
        return Changed(node);
      }
    }
  }
  return NoChange();
}
References v8::internal::DCHECK(), Int32Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Reduce(), and v8::internal::compiler::Word32Adapter::ReduceWordNComparisons().
ReduceWord32Equal()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32Equal (Node * node) [private]
Definition at line 2545 of file machine-operator-reducer.cc.
                                                              {
  Int32BinopMatcher m(node);
  if (m.IsFoldable()) { // K == K => K (K stands for arbitrary constants)
    return ReplaceBool(m.left().ResolvedValue() == m.right().ResolvedValue());
  }
  if (m.left().IsInt32Sub() && m.right().Is(0)) { // x - y == 0 => x == y
    Int32BinopMatcher msub(m.left().node());
    node->ReplaceInput(0, msub.left().node());
    node->ReplaceInput(1, msub.right().node());
    return Changed(node);
  }
  // TODO(turbofan): fold HeapConstant, ExternalReference, pointer compares
  if (m.LeftEqualsRight()) return ReplaceBool(true); // x == x => true
  if (m.right().HasResolvedValue()) {
    std::optional<std::pair<Node*, uint32_t>> replacements;
    if (m.left().IsTruncateInt64ToInt32()) {
      replacements = ReduceWordEqualForConstantRhs<Word64Adapter, uint32_t>(
          NodeProperties::GetValueInput(m.left().node(), 0),
          static_cast<uint32_t>(m.right().ResolvedValue()));
    } else {
      replacements = ReduceWordEqualForConstantRhs<Word32Adapter, uint32_t>(
          m.left().node(), static_cast<uint32_t>(m.right().ResolvedValue()));
    }
    if (replacements) {
      node->ReplaceInput(0, replacements->first);
      node->ReplaceInput(1, Uint32Constant(replacements->second));
      return Changed(node);
    }
    // Simplifying (x+k1)==k2 into x==k2-k1.
    if (m.left().IsInt32Add() && m.right().IsInt32Constant()) {
      Int32AddMatcher m_add(m.left().node());
      if (m_add.right().IsInt32Constant()) {
        int32_t lte_right = m.right().ResolvedValue();
        int32_t add_right = m_add.right().ResolvedValue();
        // No need to consider overflow in this condition (==).
        node->ReplaceInput(0, m_add.left().node());
        node->ReplaceInput(1, Int32Constant(static_cast<uint32_t>(lte_right) -
                                            static_cast<uint32_t>(add_right)));
        return Changed(node);
      }
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetValueInput(), Int32Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), ReplaceBool(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), and Uint32Constant().
Referenced by Reduce(), and ReduceWord32And().
ReduceWord32Or()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32Or (Node * node) [private]
Definition at line 2500 of file machine-operator-reducer.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kWord32Or, node->opcode());
  return ReduceWordNOr<Word32Adapter>(node);
}
References DCHECK_EQ, and v8::internal::compiler::Node::opcode().
Referenced by Reduce().
ReduceWord32Sar()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar (Node * node) [private]
Definition at line 2090 of file machine-operator-reducer.cc.
                                                            {
  Int32BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x >> 0 => x
  if (m.IsFoldable()) { // K >> K => K (K stands for arbitrary constants)
    return ReplaceInt32(m.left().ResolvedValue() >>
                        (m.right().ResolvedValue() & 31));
  }
  if (m.left().IsWord32Shl()) {
    Int32BinopMatcher mleft(m.left().node());
    if (mleft.left().IsComparison()) {
      if (m.right().Is(31) && mleft.right().Is(31)) {
        // Comparison << 31 >> 31 => 0 - Comparison
        node->ReplaceInput(0, Int32Constant(0));
        node->ReplaceInput(1, mleft.left().node());
        NodeProperties::ChangeOp(node, machine()->Int32Sub());
        return Changed(node).FollowedBy(ReduceInt32Sub(node));
      }
    } else if (mleft.left().IsLoad()) {
      LoadRepresentation const rep =
          LoadRepresentationOf(mleft.left().node()->op());
      if (m.right().Is(24) && mleft.right().Is(24) &&
          rep == MachineType::Int8()) {
        // Load[kMachInt8] << 24 >> 24 => Load[kMachInt8]
        return Replace(mleft.left().node());
      }
      if (m.right().Is(16) && mleft.right().Is(16) &&
          rep == MachineType::Int16()) {
        // Load[kMachInt16] << 16 >> 16 => Load[kMachInt8]
        return Replace(mleft.left().node());
      }
    }
  }
  return ReduceWord32Shifts(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::MachineType::Int16(), Int32Constant(), Int32Sub(), v8::internal::MachineType::Int8(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::LoadRepresentationOf(), machine(), ReduceInt32Sub(), ReduceWord32Shifts(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt32(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Reduce(), and ReduceWord32Shl().
ReduceWord32Shifts()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shifts (Node * node) [private]
Definition at line 1935 of file machine-operator-reducer.cc.
                                                               {
  DCHECK((node->opcode() == IrOpcode::kWord32Shl) ||
         (node->opcode() == IrOpcode::kWord32Shr) ||
         (node->opcode() == IrOpcode::kWord32Sar));
  if (machine()->Word32ShiftIsSafe()) {
    // Remove the explicit 'and' with 0x1F if the shift provided by the machine
    // instruction matches that required by JavaScript.
    Int32BinopMatcher m(node);
    if (m.right().IsWord32And()) {
      Int32BinopMatcher mright(m.right().node());
      if (mright.right().Is(0x1F)) {
        node->ReplaceInput(1, mright.left().node());
        return Changed(node);
      }
    }
  }
  return NoChange();
}
References v8::internal::DCHECK(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by ReduceWord32Sar(), ReduceWord32Shl(), and ReduceWord32Shr().
ReduceWord32Shl()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl (Node * node) [private]
Definition at line 1954 of file machine-operator-reducer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kWord32Shl, node->opcode());
  Int32BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x << 0 => x
  if (m.IsFoldable()) { // K << K => K (K stands for arbitrary constants)
    return ReplaceInt32(base::ShlWithWraparound(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.right().IsInRange(1, 31)) {
    if (m.left().IsWord32Sar() || m.left().IsWord32Shr()) {
      Int32BinopMatcher mleft(m.left().node());
      // If x >> K only shifted out zeros:
      // (x >> K) << L => x if K == L
      // (x >> K) << L => x >> (K-L) if K > L
      // (x >> K) << L => x << (L-K) if K < L
      // Since this is used for Smi untagging, we currently only need it for
      // signed shifts.
      if (mleft.op() == machine()->Word32SarShiftOutZeros() &&
          mleft.right().IsInRange(1, 31)) {
        Node* x = mleft.left().node();
        int k = mleft.right().ResolvedValue();
        int l = m.right().ResolvedValue();
        if (k == l) {
          return Replace(x);
        } else if (k > l) {
          node->ReplaceInput(0, x);
          node->ReplaceInput(1, Uint32Constant(k - l));
          NodeProperties::ChangeOp(node, machine()->Word32Sar());
          return Changed(node).FollowedBy(ReduceWord32Sar(node));
        } else {
          DCHECK(k < l);
          node->ReplaceInput(0, x);
          node->ReplaceInput(1, Uint32Constant(l - k));
          return Changed(node);
        }
      }
      // (x >>> K) << K => x & ~(2^K - 1)
      // (x >> K) << K => x & ~(2^K - 1)
      if (mleft.right().Is(m.right().ResolvedValue())) {
        node->ReplaceInput(0, mleft.left().node());
        node->ReplaceInput(1,
                           Uint32Constant(std::numeric_limits<uint32_t>::max()
                                          << m.right().ResolvedValue()));
        NodeProperties::ChangeOp(node, machine()->Word32And());
        return Changed(node).FollowedBy(ReduceWord32And(node));
      }
    }
  }
  return ReduceWord32Shifts(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::turboshaft::l, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::NodeMatcher::op(), v8::internal::compiler::Node::opcode(), ReduceWord32And(), ReduceWord32Sar(), ReduceWord32Shifts(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt32(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::ShlWithWraparound(), Uint32Constant(), Word32And(), and Word32Sar().
Referenced by Reduce().
ReduceWord32Shr()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shr (Node * node) [private]
Definition at line 2058 of file machine-operator-reducer.cc.
                                                            {
  Uint32BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x >>> 0 => x
  if (m.IsFoldable()) { // K >>> K => K (K stands for arbitrary constants)
    return ReplaceInt32(m.left().ResolvedValue() >>
                        (m.right().ResolvedValue() & 31));
  }
  if (m.left().IsWord32And() && m.right().HasResolvedValue()) {
    Uint32BinopMatcher mleft(m.left().node());
    if (mleft.right().HasResolvedValue()) {
      uint32_t shift = m.right().ResolvedValue() & 31;
      uint32_t mask = mleft.right().ResolvedValue();
      if ((mask >> shift) == 0) {
        // (m >>> s) == 0 implies ((x & m) >>> s) == 0
        return ReplaceInt32(0);
      }
    }
  }
  return ReduceWord32Shifts(node);
}
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), ReduceWord32Shifts(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), ReplaceInt32(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Reduce().
ReduceWord32Xor()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord32Xor (Node * node) [private]
Definition at line 2531 of file machine-operator-reducer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kWord32Xor, node->opcode());
  Int32BinopMatcher m(node);
  if (m.right().IsWord32Equal() && m.left().Is(1)) {
    return Replace(Word32Equal(m.right().node(), Int32Constant(0)));
  }
  return ReduceWordNXor<Word32Adapter>(node);
}
References DCHECK_EQ, Int32Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), and Word32Equal().
Referenced by Reduce().
ReduceWord64And()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord64And (Node * node) [private]
Definition at line 2401 of file machine-operator-reducer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kWord64And, node->opcode());
  return ReduceWordNAnd<Word64Adapter>(node);
}
References DCHECK_EQ, and v8::internal::compiler::Node::opcode().
Referenced by Reduce(), ReduceWord64Shl(), v8::internal::compiler::Word64Adapter::ReduceWordNAnd(), and Word64And().
ReduceWord64Comparisons()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons (Node * node) [private]
Definition at line 1718 of file machine-operator-reducer.cc.
                                                                    {
  DCHECK(node->opcode() == IrOpcode::kInt64LessThan ||
         node->opcode() == IrOpcode::kInt64LessThanOrEqual ||
         node->opcode() == IrOpcode::kUint64LessThan ||
         node->opcode() == IrOpcode::kUint64LessThanOrEqual);
  Int64BinopMatcher m(node);
  bool sign_extended =
      m.left().IsChangeInt32ToInt64() && m.right().IsChangeInt32ToInt64();
  if (sign_extended || (m.left().IsChangeUint32ToUint64() &&
                        m.right().IsChangeUint32ToUint64())) {
    node->ReplaceInput(0, NodeProperties::GetValueInput(m.left().node(), 0));
    node->ReplaceInput(1, NodeProperties::GetValueInput(m.right().node(), 0));
    NodeProperties::ChangeOp(node,
                             Map64To32Comparison(node->op(), sign_extended));
    return Changed(node).FollowedBy(Reduce(node));
  }
  // (x >> K) < (y >> K) => x < y if only zeros shifted out
  // This is useful for Smi untagging, which results in such a shift.
  if (m.left().op() == machine()->Word64SarShiftOutZeros() &&
      m.right().op() == machine()->Word64SarShiftOutZeros()) {
    Int64BinopMatcher mleft(m.left().node());
    Int64BinopMatcher mright(m.right().node());
    if (mleft.right().HasResolvedValue() &&
        mright.right().Is(mleft.right().ResolvedValue())) {
      node->ReplaceInput(0, mleft.left().node());
      node->ReplaceInput(1, mright.left().node());
      return Changed(node);
    }
  }
  // Simplifying (x >> n) <= k into x <= (k << n), with "k << n" being
  // computed here at compile time.
  if (m.right().HasResolvedValue() &&
      m.left().op() == machine()->Word64SarShiftOutZeros() &&
      m.left().node()->UseCount() == 1) {
    Int64BinopMatcher mleft(m.left().node());
    uint64_t right = m.right().ResolvedValue();
    if (mleft.right().HasResolvedValue()) {
      auto shift = mleft.right().ResolvedValue();
      if (CanRevertLeftShiftWithRightShift<int64_t>(right, shift)) {
        sign_extended = mleft.left().IsChangeInt32ToInt64();
        uint64_t value = right << shift;
        // Reducing to 32-bit comparison when possible.
        if ((sign_extended || mleft.left().IsChangeUint32ToUint64()) &&
            CanTruncate(static_cast<int64_t>(value))) {
          NodeProperties::ChangeOp(
              node, Map64To32Comparison(node->op(), sign_extended));
          node->ReplaceInput(0, mleft.left().node()->InputAt(0));
          node->ReplaceInput(1, Int32Constant(static_cast<int32_t>(value)));
          return Changed(node).FollowedBy(Reduce(node));
        }
        node->ReplaceInput(0, mleft.left().node());
        node->ReplaceInput(1, Int64Constant(value));
        return Changed(node);
      }
    }
  }
  // Simplifying k <= (x >> n) into (k << n) <= x, with "k << n" being
  // computed here at compile time.
  if (m.left().HasResolvedValue() &&
      m.right().op() == machine()->Word64SarShiftOutZeros() &&
      m.right().node()->UseCount() == 1) {
    uint64_t left = m.left().ResolvedValue();
    Int64BinopMatcher mright(m.right().node());
    if (mright.right().HasResolvedValue()) {
      auto shift = mright.right().ResolvedValue();
      if (CanRevertLeftShiftWithRightShift<int64_t>(left, shift)) {
        sign_extended = mright.left().IsChangeInt32ToInt64();
        uint64_t value = left << shift;
        // Reducing to 32-bit comparison when possible.
        if ((sign_extended || mright.left().IsChangeUint32ToUint64()) &&
            CanTruncate(static_cast<int64_t>(value))) {
          NodeProperties::ChangeOp(
              node, Map64To32Comparison(node->op(), sign_extended));
          node->ReplaceInput(0, Int32Constant(static_cast<int32_t>(value)));
          node->ReplaceInput(1, mright.left().node()->InputAt(0));
          return Changed(node).FollowedBy(Reduce(node));
        }
        node->ReplaceInput(0, Int64Constant(value));
        node->ReplaceInput(1, mright.left().node());
        return Changed(node);
      }
    }
  }
  /*
    If Int64Constant(c) can be casted from an Int32Constant:
    -------------------------------------------------
    Int64LessThan(Int32ToInt64(a), Int64Constant(c))
    ====>
    Int32LessThan(a,Int32Constant(c))
    -------------------------------------------------
  */
  if (node->opcode() == IrOpcode::kInt64LessThan ||
      node->opcode() == IrOpcode::kInt64LessThanOrEqual) {
    // Int64LessThan(Int32ToInt64(a), Int64Constant(c))
    if (m.left().IsChangeInt32ToInt64() && m.right().HasResolvedValue()) {
      int64_t right_value = static_cast<int64_t>(m.right().ResolvedValue());
      // Int64Constant can be casted from an Int32Constant
      if (right_value == static_cast<int32_t>(right_value)) {
        const Operator* new_op;
        if (node->opcode() == IrOpcode::kInt64LessThan) {
          new_op = machine()->Int32LessThan();
        } else {
          new_op = machine()->Int32LessThanOrEqual();
        }
        NodeProperties::ChangeOp(node, new_op);
        node->ReplaceInput(0, m.left().InputAt(0));
        node->ReplaceInput(1, Int32Constant(static_cast<int32_t>(right_value)));
        return Changed(node);
      } else if (right_value < std::numeric_limits<int32_t>::min()) {
        // left > right always
        node->TrimInputCount(0);
        NodeProperties::ChangeOp(node, common()->Int32Constant(0));
        return Changed(node);
      } else if (right_value > std::numeric_limits<int32_t>::max()) {
        // left < right always
        node->TrimInputCount(0);
        NodeProperties::ChangeOp(node, common()->Int32Constant(1));
        return Changed(node);
      }
    }
    // Int64LessThan(Int64Constant(c), Int32ToInt64(a))
    if (m.right().IsChangeInt32ToInt64() && m.left().HasResolvedValue()) {
      int64_t left_value = static_cast<int64_t>(m.left().ResolvedValue());
      // Int64Constant can be casted from an Int32Constant
      if (left_value == static_cast<int32_t>(left_value)) {
        const Operator* new_op;
        if (node->opcode() == IrOpcode::kInt64LessThan) {
          new_op = machine()->Int32LessThan();
        } else {
          new_op = machine()->Int32LessThanOrEqual();
        }
        NodeProperties::ChangeOp(node, new_op);
        node->ReplaceInput(1, m.right().InputAt(0));
        node->ReplaceInput(0, Int32Constant(static_cast<int32_t>(left_value)));
        return Changed(node);
      } else if (left_value < std::numeric_limits<int32_t>::min()) {
        // left < right always
        node->TrimInputCount(0);
        NodeProperties::ChangeOp(node, common()->Int32Constant(1));
        return Changed(node);
      } else if (left_value > std::numeric_limits<int32_t>::max()) {
        // left > right always
        node->TrimInputCount(0);
        NodeProperties::ChangeOp(node, common()->Int32Constant(0));
        return Changed(node);
      }
    }
  }
  /*
    If Uint64Constant(c) can be casted from an Uint32Constant:
    -------------------------------------------------
    Uint64LessThan(Uint32ToInt64(a), Uint64Constant(c))
    ====>
    Uint32LessThan(a,Uint32Constant(c))
    -------------------------------------------------
  */
  if (node->opcode() == IrOpcode::kUint64LessThan ||
      node->opcode() == IrOpcode::kUint64LessThanOrEqual) {
    // Uint64LessThan(Uint32ToInt64(a), Uint32Constant(c))
    if (m.left().IsChangeUint32ToUint64() && m.right().HasResolvedValue()) {
      uint64_t right_value = static_cast<uint64_t>(m.right().ResolvedValue());
      // Uint64Constant can be casted from an Uint32Constant
      if (right_value == static_cast<uint32_t>(right_value)) {
        const Operator* new_op;
        if (node->opcode() == IrOpcode::kUint64LessThan) {
          new_op = machine()->Uint32LessThan();
        } else {
          new_op = machine()->Uint32LessThanOrEqual();
        }
        NodeProperties::ChangeOp(node, new_op);
        node->ReplaceInput(0, m.left().InputAt(0));
        node->ReplaceInput(1,
                           Uint32Constant(static_cast<uint32_t>(right_value)));
        return Changed(node);
      } else {
        // left < right always
        node->TrimInputCount(0);
        NodeProperties::ChangeOp(node, common()->Int32Constant(1));
        return Changed(node);
      }
    }
    // Uint64LessThan(Uint64Constant(c), Uint32ToInt64(a))
    if (m.right().IsChangeUint32ToUint64() && m.left().HasResolvedValue()) {
      uint64_t left_value = static_cast<uint64_t>(m.left().ResolvedValue());
      // Uint64Constant can be casted from an Uint32Constant
      if (left_value == static_cast<uint32_t>(left_value)) {
        const Operator* new_op;
        if (node->opcode() == IrOpcode::kUint64LessThan) {
          new_op = machine()->Uint32LessThan();
        } else {
          new_op = machine()->Uint32LessThanOrEqual();
        }
        NodeProperties::ChangeOp(node, new_op);
        node->ReplaceInput(1, m.right().InputAt(0));
        node->ReplaceInput(0,
                           Uint32Constant(static_cast<uint32_t>(left_value)));
        return Changed(node);
      } else {
        // left > right always
        node->TrimInputCount(0);
        NodeProperties::ChangeOp(node, common()->Int32Constant(0));
        return Changed(node);
      }
    }
  }
  return NoChange();
}
References v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::CanTruncate(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetValueInput(), Int32Constant(), v8::internal::compiler::MachineOperatorBuilder::Int32LessThan(), v8::internal::compiler::MachineOperatorBuilder::Int32LessThanOrEqual(), Int64Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), Map64To32Comparison(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), Reduce(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::Node::TrimInputCount(), Uint32Constant(), v8::internal::compiler::MachineOperatorBuilder::Uint32LessThan(), v8::internal::compiler::MachineOperatorBuilder::Uint32LessThanOrEqual(), and v8::internal::value.
Referenced by Reduce(), and v8::internal::compiler::Word64Adapter::ReduceWordNComparisons().
ReduceWord64Equal()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord64Equal (Node * node) [private]
Definition at line 2592 of file machine-operator-reducer.cc.
                                                              {
  Int64BinopMatcher m(node);
  if (m.IsFoldable()) { // K == K => K (K stands for arbitrary constants)
    return ReplaceBool(m.left().ResolvedValue() == m.right().ResolvedValue());
  }
  if (m.left().IsInt64Sub() && m.right().Is(0)) { // x - y == 0 => x == y
    Int64BinopMatcher msub(m.left().node());
    node->ReplaceInput(0, msub.left().node());
    node->ReplaceInput(1, msub.right().node());
    return Changed(node);
  }
  // TODO(turbofan): fold HeapConstant, ExternalReference, pointer compares
  if (m.LeftEqualsRight()) return ReplaceBool(true); // x == x => true
  if (m.right().HasResolvedValue()) {
    std::optional<std::pair<Node*, uint64_t>> replacements =
        ReduceWordEqualForConstantRhs<Word64Adapter, uint64_t>(
            m.left().node(), static_cast<uint64_t>(m.right().ResolvedValue()));
    if (replacements) {
      node->ReplaceInput(0, replacements->first);
      node->ReplaceInput(1, Uint64Constant(replacements->second));
      return Changed(node);
    }
    // Simplifying (x+k1)==k2 into x==k2-k1.
    if (m.left().IsInt64Add() && m.right().IsInt64Constant()) {
      Int64AddMatcher m_add(m.left().node());
      if (m_add.right().IsInt64Constant()) {
        int64_t lte_right = m.right().ResolvedValue();
        int64_t add_right = m_add.right().ResolvedValue();
        // No need to consider overflow in this condition (==).
        node->ReplaceInput(0, m_add.left().node());
        node->ReplaceInput(1, Int64Constant(static_cast<uint64_t>(lte_right) -
                                            static_cast<uint64_t>(add_right)));
        return Changed(node);
      }
    }
    /*
      If Int64Constant(c) can be casted from an Int32Constant:
      -------------------------------------------------
      Word64Equal(Int32ToInt64(a), Int64Constant(c))
      ====>
      Word32Equal(a,Int32Constant(c))
      -------------------------------------------------
    */
    if (m.left().IsChangeInt32ToInt64()) {
      int64_t right_value = m.right().ResolvedValue();
      // Int64Constant can be casted from an Int32Constant
      if (right_value == static_cast<int32_t>(right_value)) {
        NodeProperties::ChangeOp(node, machine()->Word32Equal());
        node->ReplaceInput(0, m.left().InputAt(0));
        node->ReplaceInput(1, Int32Constant(static_cast<int32_t>(right_value)));
        return Changed(node);
      } else {
        // Always false, change node op to zero(false).
        node->TrimInputCount(0);
        NodeProperties::ChangeOp(node, common()->Int32Constant(0));
        return Changed(node);
      }
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), Int32Constant(), Int64Constant(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), machine(), ReplaceBool(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::Node::TrimInputCount(), Uint64Constant(), and Word32Equal().
Referenced by Reduce().
ReduceWord64Or()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord64Or (Node * node) [private]
Definition at line 2505 of file machine-operator-reducer.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kWord64Or, node->opcode());
  return ReduceWordNOr<Word64Adapter>(node);
}
References DCHECK_EQ, and v8::internal::compiler::Node::opcode().
Referenced by Reduce().
ReduceWord64Sar()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord64Sar (Node * node) [private]
Definition at line 2125 of file machine-operator-reducer.cc.
                                                            {
  Int64BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x >> 0 => x
  if (m.IsFoldable()) {
    return ReplaceInt64(m.left().ResolvedValue() >>
                        (m.right().ResolvedValue() & 63));
  }
  return NoChange();
}
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), ReplaceInt64(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Reduce(), and ReduceWord64Shl().
ReduceWord64Shl()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl (Node * node) [private]
Definition at line 2007 of file machine-operator-reducer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kWord64Shl, node->opcode());
  Int64BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x << 0 => x
  if (m.IsFoldable()) { // K << K => K (K stands for arbitrary constants)
    return ReplaceInt64(base::ShlWithWraparound(m.left().ResolvedValue(),
                                                m.right().ResolvedValue()));
  }
  if (m.right().IsInRange(1, 63) &&
      (m.left().IsWord64Sar() || m.left().IsWord64Shr())) {
    Int64BinopMatcher mleft(m.left().node());
    // If x >> K only shifted out zeros:
    // (x >> K) << L => x if K == L
    // (x >> K) << L => x >> (K-L) if K > L
    // (x >> K) << L => x << (L-K) if K < L
    // Since this is used for Smi untagging, we currently only need it for
    // signed shifts.
    if (mleft.op() == machine()->Word64SarShiftOutZeros() &&
        mleft.right().IsInRange(1, 63)) {
      Node* x = mleft.left().node();
      int64_t k = mleft.right().ResolvedValue();
      int64_t l = m.right().ResolvedValue();
      if (k == l) {
        return Replace(x);
      } else if (k > l) {
        node->ReplaceInput(0, x);
        node->ReplaceInput(1, Uint64Constant(k - l));
        NodeProperties::ChangeOp(node, machine()->Word64Sar());
        return Changed(node).FollowedBy(ReduceWord64Sar(node));
      } else {
        DCHECK(k < l);
        node->ReplaceInput(0, x);
        node->ReplaceInput(1, Uint64Constant(l - k));
        return Changed(node);
      }
    }
    // (x >>> K) << K => x & ~(2^K - 1)
    // (x >> K) << K => x & ~(2^K - 1)
    if (mleft.right().Is(m.right().ResolvedValue())) {
      node->ReplaceInput(0, mleft.left().node());
      node->ReplaceInput(1, Uint64Constant(std::numeric_limits<uint64_t>::max()
                                           << m.right().ResolvedValue()));
      NodeProperties::ChangeOp(node, machine()->Word64And());
      return Changed(node).FollowedBy(ReduceWord64And(node));
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::turboshaft::l, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::NodeMatcher::op(), v8::internal::compiler::Node::opcode(), ReduceWord64And(), ReduceWord64Sar(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt64(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::ShlWithWraparound(), Uint64Constant(), Word64And(), and Word64Sar().
Referenced by Reduce(), and ReduceInt64Mul().
ReduceWord64Shr()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shr (Node * node) [private]
Definition at line 2079 of file machine-operator-reducer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kWord64Shr, node->opcode());
  Uint64BinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x >>> 0 => x
  if (m.IsFoldable()) { // K >> K => K (K stands for arbitrary constants)
    return ReplaceInt64(m.left().ResolvedValue() >>
                        (m.right().ResolvedValue() & 63));
  }
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), ReplaceInt64(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by Reduce().
ReduceWord64Xor()
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWord64Xor (Node * node) [private]
Definition at line 2540 of file machine-operator-reducer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kWord64Xor, node->opcode());
  return ReduceWordNXor<Word64Adapter>(node);
}
References DCHECK_EQ, and v8::internal::compiler::Node::opcode().
Referenced by Reduce().
ReduceWordEqualForConstantRhs()
template<typename WordNAdapter , typename uintN_t , typename intN_t >
std::optional< std::pair< Node *, uintN_t > > v8::internal::compiler::MachineOperatorReducer::ReduceWordEqualForConstantRhs (Node * lhs, uintN_t rhs) [private]
Definition at line 2975 of file machine-operator-reducer.cc.
                                                                            {
  if (WordNAdapter::IsWordNAnd(NodeMatcher(lhs))) {
    typename WordNAdapter::UintNBinopMatcher mand(lhs);
    if ((WordNAdapter::IsWordNShr(mand.left()) ||
         WordNAdapter::IsWordNSar(mand.left())) &&
        mand.right().HasResolvedValue()) {
      typename WordNAdapter::UintNBinopMatcher mshift(mand.left().node());
      // ((x >> K1) & K2) == K3 => (x & (K2 << K1)) == (K3 << K1)
      if (mshift.right().HasResolvedValue()) {
        auto shift_bits = mshift.right().ResolvedValue();
        auto mask = mand.right().ResolvedValue();
        // Make sure that we won't shift data off the end, and that all of the
        // data ends up in the lower 32 bits for 64-bit mode.
        if (shift_bits <= base::bits::CountLeadingZeros(mask) &&
            shift_bits <= base::bits::CountLeadingZeros(rhs) &&
            (std::is_same_v<uintN_t, uint64_t> ||
             mask << shift_bits <= std::numeric_limits<uintN_t>::max())) {
          Node* new_input = mshift.left().node();
          uintN_t new_mask = static_cast<uintN_t>(mask << shift_bits);
          uintN_t new_rhs = rhs << shift_bits;
          if (std::is_same_v<uintN_t, uint32_t> &&
              WordNAdapter::WORD_SIZE == 64) {
            // We can truncate before performing the And.
            new_input = TruncateInt64ToInt32(new_input);
            return std::make_pair(Word32And(new_input, new_mask), new_rhs);
          } else {
            WordNAdapter a(this);
            return std::make_pair(
                a.WordNAnd(new_input, a.UintNConstant(new_mask)), new_rhs);
          }
        }
      }
    }
  }
  // Replaces (x >> n) == k with x == k << n, with "k << n" being computed
  // here at compile time.
  if (std::is_same_v<intN_t, typename WordNAdapter::intN_t> &&
      WordNAdapter::IsWordNSarShiftOutZeros(lhs->op()) &&
      lhs->UseCount() == 1) {
    typename WordNAdapter::UintNBinopMatcher mshift(lhs);
    if (mshift.right().HasResolvedValue()) {
      intN_t shift = static_cast<intN_t>(mshift.right().ResolvedValue());
      if (CanRevertLeftShiftWithRightShift<intN_t>(rhs, shift)) {
        return std::make_pair(mshift.left().node(), rhs << shift);
      }
    }
  }
  return {};
}
References v8::base::bits::CountLeadingZeros(), v8::internal::compiler::Node::op(), TruncateInt64ToInt32(), v8::internal::compiler::Node::UseCount(), and Word32And().
ReduceWordNAnd()
template<typename WordNAdapter >
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWordNAnd (Node * node) [private]
Definition at line 2136 of file machine-operator-reducer.cc.
                                                           {
  using A = WordNAdapter;
  A a(this);
  typename A::IntNBinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.right().node()); // x & 0 => 0
  if (m.right().Is(-1)) return Replace(m.left().node()); // x & -1 => x
  if (m.right().Is(1)) {
    // (x + x) & 1 => 0
    Node* left = m.left().node();
    while (left->opcode() == IrOpcode::kTruncateInt64ToInt32 ||
           left->opcode() == IrOpcode::kChangeInt32ToInt64 ||
           left->opcode() == IrOpcode::kChangeUint32ToUint64) {
      left = left->InputAt(0);
    }
    if ((left->opcode() == IrOpcode::kInt32Add ||
         left->opcode() == IrOpcode::kInt64Add) &&
        left->InputAt(0) == left->InputAt(1)) {
      return a.ReplaceIntN(0);
    }
  }
  if (m.left().IsComparison() && m.right().Is(1)) { // CMP & 1 => CMP
    return Replace(m.left().node());
  }
  if (m.IsFoldable()) { // K & K => K (K stands for arbitrary constants)
    return a.ReplaceIntN(m.left().ResolvedValue() & m.right().ResolvedValue());
  }
  if (m.LeftEqualsRight()) return Replace(m.left().node()); // x & x => x
  if (A::IsWordNAnd(m.left()) && m.right().HasResolvedValue()) {
    typename A::IntNBinopMatcher mleft(m.left().node());
    if (mleft.right().HasResolvedValue()) { // (x & K) & K => x & K
      node->ReplaceInput(0, mleft.left().node());
      node->ReplaceInput(1, a.IntNConstant(m.right().ResolvedValue() &
                                           mleft.right().ResolvedValue()));
      return Changed(node).FollowedBy(a.ReduceWordNAnd(node));
    }
  }
  if (m.right().IsNegativePowerOf2()) {
    typename A::intN_t const mask = m.right().ResolvedValue();
    typename A::intN_t const neg_mask = base::NegateWithWraparound(mask);
    if (A::IsWordNShl(m.left())) {
      typename A::UintNBinopMatcher mleft(m.left().node());
      if (mleft.right().HasResolvedValue() &&
          (mleft.right().ResolvedValue() & (A::WORD_SIZE - 1)) >=
              base::bits::CountTrailingZeros(mask)) {
        // (x << L) & (-1 << K) => x << L iff L >= K
        return Replace(mleft.node());
      }
    } else if (A::IsIntNAdd(m.left())) {
      typename A::IntNBinopMatcher mleft(m.left().node());
      if (mleft.right().HasResolvedValue() &&
          (mleft.right().ResolvedValue() & mask) ==
              mleft.right().ResolvedValue()) {
        // (x + (K << L)) & (-1 << L) => (x & (-1 << L)) + (K << L)
        node->ReplaceInput(0,
                           a.WordNAnd(mleft.left().node(), m.right().node()));
        node->ReplaceInput(1, mleft.right().node());
        NodeProperties::ChangeOp(node, a.IntNAdd(machine()));
        return Changed(node).FollowedBy(a.ReduceIntNAdd(node));
      }
      if (A::IsIntNMul(mleft.left())) {
        typename A::IntNBinopMatcher mleftleft(mleft.left().node());
        if (mleftleft.right().IsMultipleOf(neg_mask)) {
          // (y * (K << L) + x) & (-1 << L) => (x & (-1 << L)) + y * (K << L)
          node->ReplaceInput(
              0, a.WordNAnd(mleft.right().node(), m.right().node()));
          node->ReplaceInput(1, mleftleft.node());
          NodeProperties::ChangeOp(node, a.IntNAdd(machine()));
          return Changed(node).FollowedBy(a.ReduceIntNAdd(node));
        }
      }
      if (A::IsIntNMul(mleft.right())) {
        typename A::IntNBinopMatcher mleftright(mleft.right().node());
        if (mleftright.right().IsMultipleOf(neg_mask)) {
          // (x + y * (K << L)) & (-1 << L) => (x & (-1 << L)) + y * (K << L)
          node->ReplaceInput(0,
                             a.WordNAnd(mleft.left().node(), m.right().node()));
          node->ReplaceInput(1, mleftright.node());
          NodeProperties::ChangeOp(node, a.IntNAdd(machine()));
          return Changed(node).FollowedBy(a.ReduceIntNAdd(node));
        }
      }
      if (A::IsWordNShl(mleft.left())) {
        typename A::IntNBinopMatcher mleftleft(mleft.left().node());
        if (mleftleft.right().Is(base::bits::CountTrailingZeros(mask))) {
          // (y << L + x) & (-1 << L) => (x & (-1 << L)) + y << L
          node->ReplaceInput(
              0, a.WordNAnd(mleft.right().node(), m.right().node()));
          node->ReplaceInput(1, mleftleft.node());
          NodeProperties::ChangeOp(node, a.IntNAdd(machine()));
          return Changed(node).FollowedBy(a.ReduceIntNAdd(node));
        }
      }
      if (A::IsWordNShl(mleft.right())) {
        typename A::IntNBinopMatcher mleftright(mleft.right().node());
        if (mleftright.right().Is(base::bits::CountTrailingZeros(mask))) {
          // (x + y << L) & (-1 << L) => (x & (-1 << L)) + y << L
          node->ReplaceInput(0,
                             a.WordNAnd(mleft.left().node(), m.right().node()));
          node->ReplaceInput(1, mleftright.node());
          NodeProperties::ChangeOp(node, a.IntNAdd(machine()));
          return Changed(node).FollowedBy(a.ReduceIntNAdd(node));
        }
      }
    } else if (A::IsIntNMul(m.left())) {
      typename A::IntNBinopMatcher mleft(m.left().node());
      if (mleft.right().IsMultipleOf(neg_mask)) {
        // (x * (K << L)) & (-1 << L) => x * (K << L)
        return Replace(mleft.node());
      }
    }
  }
  return NoChange();
}
References v8::internal::A, v8::internal::compiler::NodeProperties::ChangeOp(), v8::base::bits::CountTrailingZeros(), v8::internal::compiler::Node::InputAt(), machine(), v8::base::NegateWithWraparound(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::compiler::Node::ReplaceInput().
ReduceWordNOr()
template<typename WordNAdapter >
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWordNOr (Node * node) [private]
Definition at line 2471 of file machine-operator-reducer.cc.
                                                          {
  using A = WordNAdapter;
  A a(this);
  typename A::IntNBinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x | 0 => x
  if (m.right().Is(-1)) return Replace(m.right().node()); // x | -1 => -1
  if (m.IsFoldable()) { // K | K => K (K stands for arbitrary constants)
    return a.ReplaceIntN(m.left().ResolvedValue() | m.right().ResolvedValue());
  }
  if (m.LeftEqualsRight()) return Replace(m.left().node()); // x | x => x
  // (x & K1) | K2 => x | K2 if K2 has ones for every zero bit in K1.
  // This case can be constructed by UpdateWord and UpdateWord32 in CSA.
  if (m.right().HasResolvedValue()) {
    if (A::IsWordNAnd(m.left())) {
      typename A::IntNBinopMatcher mand(m.left().node());
      if (mand.right().HasResolvedValue()) {
        if ((m.right().ResolvedValue() | mand.right().ResolvedValue()) == -1) {
          node->ReplaceInput(0, mand.left().node());
          return Changed(node);
        }
      }
    }
  }
  return a.TryMatchWordNRor(node);
}
References v8::internal::A, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::compiler::Node::ReplaceInput().
ReduceWordNXor()
template<typename WordNAdapter >
Reduction v8::internal::compiler::MachineOperatorReducer::ReduceWordNXor (Node * node) [private]
Definition at line 2511 of file machine-operator-reducer.cc.
                                                           {
  using A = WordNAdapter;
  A a(this);
  typename A::IntNBinopMatcher m(node);
  if (m.right().Is(0)) return Replace(m.left().node()); // x ^ 0 => x
  if (m.IsFoldable()) { // K ^ K => K (K stands for arbitrary constants)
    return a.ReplaceIntN(m.left().ResolvedValue() ^ m.right().ResolvedValue());
  }
  if (m.LeftEqualsRight()) return Replace(a.IntNConstant(0)); // x ^ x => 0
  if (A::IsWordNXor(m.left()) && m.right().Is(-1)) {
    typename A::IntNBinopMatcher mleft(m.left().node());
    if (mleft.right().Is(-1)) { // (x ^ -1) ^ -1 => x
      return Replace(mleft.left().node());
    }
  }
  return a.TryMatchWordNRor(node);
}
References v8::internal::A, and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
ReplaceBool()
Reduction v8::internal::compiler::MachineOperatorReducer::ReplaceBool (bool value) [inline], [private]
Definition at line 87 of file machine-operator-reducer.h.
{ return ReplaceInt32(value ? 1 : 0); }
References v8::internal::value.
Referenced by Reduce(), ReduceFloat64Compare(), ReduceUintNLessThanOrEqual(), ReduceWord32Equal(), and ReduceWord64Equal().
ReplaceFloat32()
Reduction v8::internal::compiler::MachineOperatorReducer::ReplaceFloat32 (float value) [inline], [private]
Definition at line 88 of file machine-operator-reducer.h.
                                        {
    return Replace(Float32Constant(value));
  }
References v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce().
ReplaceFloat64()
Reduction v8::internal::compiler::MachineOperatorReducer::ReplaceFloat64 (double value) [inline], [private]
Definition at line 91 of file machine-operator-reducer.h.
                                         {
    return Replace(Float64Constant(value));
  }
References v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce(), ReduceFloat64InsertHighWord32(), ReduceFloat64InsertLowWord32(), and ReduceFloat64RoundDown().
ReplaceInt32()
Reduction v8::internal::compiler::MachineOperatorReducer::ReplaceInt32 (int32_t value) [inline], [private]
Definition at line 94 of file machine-operator-reducer.h.
                                        {
    return Replace(Int32Constant(value));
  }
References v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce(), ReduceInt32Add(), ReduceInt32Div(), ReduceInt32Mod(), ReduceInt32Sub(), ReduceProjection(), ReduceTruncateInt64ToInt32(), ReduceWord32Sar(), ReduceWord32Shl(), ReduceWord32Shr(), and v8::internal::compiler::Word32Adapter::ReplaceIntN().
ReplaceInt64()
Reduction v8::internal::compiler::MachineOperatorReducer::ReplaceInt64 (int64_t value) [inline], [private]
Definition at line 100 of file machine-operator-reducer.h.
                                        {
    return Replace(Int64Constant(value));
  }
References v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce(), ReduceInt64Add(), ReduceInt64Div(), ReduceInt64Mod(), ReduceInt64Mul(), ReduceInt64Sub(), ReduceWord64Sar(), ReduceWord64Shl(), ReduceWord64Shr(), and v8::internal::compiler::Word64Adapter::ReplaceIntN().
ReplaceUint32()
Reduction v8::internal::compiler::MachineOperatorReducer::ReplaceUint32 (uint32_t value) [inline], [private]
Definition at line 97 of file machine-operator-reducer.h.
                                          {
    return Replace(Uint32Constant(value));
  }
References v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by ReduceUint32Div(), and ReduceUint32Mod().
ReplaceUint64()
Reduction v8::internal::compiler::MachineOperatorReducer::ReplaceUint64 (uint64_t value) [inline], [private]
Definition at line 103 of file machine-operator-reducer.h.
                                          {
    return Replace(Uint64Constant(value));
  }
References v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by ReduceUint64Div(), and ReduceUint64Mod().
SimplifyBranch()
Reduction v8::internal::compiler::MachineOperatorReducer::SimplifyBranch (Node * node) [private]
Definition at line 2887 of file machine-operator-reducer.cc.
                                                           {
  Node* cond = node->InputAt(0);
  if (auto simplified = TrySimplifyCompareZero(cond)) {
    node->ReplaceInput(0, simplified->condition);
    if (simplified->is_inverted) {
      switch (node->opcode()) {
        case IrOpcode::kBranch:
          SwapBranches(node);
          break;
#if V8_ENABLE_WEBASSEMBLY
        case IrOpcode::kTrapIf: {
          const bool has_frame_state = node->op()->ValueInputCount() > 1;
          NodeProperties::ChangeOp(
              node,
              common()->TrapUnless(TrapIdOf(node->op()), has_frame_state));
          break;
        }
        case IrOpcode::kTrapUnless: {
          const bool has_frame_state = node->op()->ValueInputCount() > 1;
          NodeProperties::ChangeOp(
              node, common()->TrapIf(TrapIdOf(node->op()), has_frame_state));
          break;
        }
#endif // V8_ENABLE_WEBASSEMBLY
        case IrOpcode::kDeoptimizeIf: {
          DeoptimizeParameters p = DeoptimizeParametersOf(node->op());
          NodeProperties::ChangeOp(
              node, common()->DeoptimizeUnless(p.reason(), p.feedback()));
          break;
        }
        case IrOpcode::kDeoptimizeUnless: {
          DeoptimizeParameters p = DeoptimizeParametersOf(node->op());
          NodeProperties::ChangeOp(
              node, common()->DeoptimizeIf(p.reason(), p.feedback()));
          break;
        }
        default:
          UNREACHABLE();
      }
    }
    return Changed(node);
  } else if (auto new_cond = TrySimplifyCompareForTestBit(cond)) {
    node->ReplaceInput(0, new_cond);
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::DeoptimizeParametersOf(), v8::internal::compiler::DeoptimizeParameters::feedback(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::DeoptimizeParameters::reason(), v8::internal::compiler::Node::ReplaceInput(), SwapBranches(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TrySimplifyCompareForTestBit(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TrySimplifyCompareZero(), v8::internal::UNREACHABLE(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by ReduceConditional().
SwapBranches()
void v8::internal::compiler::MachineOperatorReducer::SwapBranches (Node * node) [private]
Definition at line 2868 of file machine-operator-reducer.cc.
                                                    {
  DCHECK_EQ(node->opcode(), IrOpcode::kBranch);
  for (Node* const use : node->uses()) {
    switch (use->opcode()) {
      case IrOpcode::kIfTrue:
        NodeProperties::ChangeOp(use, common()->IfFalse());
        break;
      case IrOpcode::kIfFalse:
        NodeProperties::ChangeOp(use, common()->IfTrue());
        break;
      default:
        UNREACHABLE();
    }
  }
  NodeProperties::ChangeOp(
      node, common()->Branch(NegateBranchHint(BranchHintOf(node->op()))));
}
References v8::internal::compiler::BranchHintOf(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), DCHECK_EQ, v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::NegateBranchHint(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::UNREACHABLE(), use(), and v8::internal::compiler::Node::uses().
Referenced by SimplifyBranch().
TruncateInt64ToInt32()
Node * v8::internal::compiler::MachineOperatorReducer::TruncateInt64ToInt32 (Node * value) [private]
Definition at line 380 of file machine-operator-reducer.cc.
                                                              {
  Node* const node = graph()->NewNode(machine()->TruncateInt64ToInt32(), value);
  Reduction const reduction = ReduceTruncateInt64ToInt32(node);
  return reduction.Changed() ? reduction.replacement() : node;
}
References v8::internal::compiler::Reduction::Changed(), graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), ReduceTruncateInt64ToInt32(), v8::internal::compiler::Reduction::replacement(), and v8::internal::value.
Referenced by ReduceWord32And(), and ReduceWordEqualForConstantRhs().
TryMatchWord32Ror()
Reduction v8::internal::compiler::MachineOperatorReducer::TryMatchWord32Ror (Node * node) [private]
Definition at line 2406 of file machine-operator-reducer.cc.
                                                              {
  // Recognize rotation, we are matching and transforming as follows:
  // x << y | x >>> (32 - y) => x ror (32 - y)
  // x << (32 - y) | x >>> y => x ror y
  // x << y ^ x >>> (32 - y) => x ror (32 - y) if y & 31 != 0
  // x << (32 - y) ^ x >>> y => x ror y if y & 31 != 0
  // (As well as the commuted forms.)
  // Note the side condition for XOR: the optimization doesn't hold for
  // multiples of 32.
  DCHECK(IrOpcode::kWord32Or == node->opcode() ||
         IrOpcode::kWord32Xor == node->opcode());
  Int32BinopMatcher m(node);
  Node* shl = nullptr;
  Node* shr = nullptr;
  if (m.left().IsWord32Shl() && m.right().IsWord32Shr()) {
    shl = m.left().node();
    shr = m.right().node();
  } else if (m.left().IsWord32Shr() && m.right().IsWord32Shl()) {
    shl = m.right().node();
    shr = m.left().node();
  } else {
    return NoChange();
  }
  Int32BinopMatcher mshl(shl);
  Int32BinopMatcher mshr(shr);
  if (mshl.left().node() != mshr.left().node()) return NoChange();
  if (mshl.right().HasResolvedValue() && mshr.right().HasResolvedValue()) {
    // Case where y is a constant.
    if (mshl.right().ResolvedValue() + mshr.right().ResolvedValue() != 32) {
      return NoChange();
    }
    if (node->opcode() == IrOpcode::kWord32Xor &&
        (mshl.right().ResolvedValue() & 31) == 0) {
      return NoChange();
    }
  } else {
    Node* sub = nullptr;
    Node* y = nullptr;
    if (mshl.right().IsInt32Sub()) {
      sub = mshl.right().node();
      y = mshr.right().node();
    } else if (mshr.right().IsInt32Sub()) {
      sub = mshr.right().node();
      y = mshl.right().node();
    } else {
      return NoChange();
    }
    Int32BinopMatcher msub(sub);
    if (!msub.left().Is(32) || msub.right().node() != y) return NoChange();
    if (node->opcode() == IrOpcode::kWord32Xor) {
      return NoChange(); // Can't guarantee y & 31 != 0.
    }
  }
  node->ReplaceInput(0, mshl.left().node());
  node->ReplaceInput(1, mshr.right().node());
  NodeProperties::ChangeOp(node, machine()->Word32Ror());
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), shr, and v8::internal::y.
Referenced by v8::internal::compiler::Word32Adapter::TryMatchWordNRor().
Uint32Constant()
Node* v8::internal::compiler::MachineOperatorReducer::Uint32Constant (uint32_t value) [inline], [private]
Definition at line 52 of file machine-operator-reducer.h.
                                       {
    return Int32Constant(base::bit_cast<int32_t>(value));
  }
References v8::internal::value.
Referenced by Int32Div(), Reduce(), ReduceUint32Div(), ReduceUint32Mod(), ReduceWord32Equal(), ReduceWord32Shl(), ReduceWord64Comparisons(), Uint32Div(), v8::internal::compiler::Word32Adapter::UintNConstant(), Word32Sar(), and Word32Shr().
Uint32Div()
Node * v8::internal::compiler::MachineOperatorReducer::Uint32Div (Node * dividend, uint32_t divisor) [private]
Definition at line 334 of file machine-operator-reducer.cc.
                                                                        {
  DCHECK_LT(0u, divisor);
  // If the divisor is even, we can avoid using the expensive fixup by shifting
  // the dividend upfront.
  unsigned const shift = base::bits::CountTrailingZeros(divisor);
  dividend = Word32Shr(dividend, shift);
  divisor >>= shift;
  // Compute the magic number for the (shifted) divisor.
  base::MagicNumbersForDivision<uint32_t> const mag =
      base::UnsignedDivisionByConstant(divisor, shift);
  Node* quotient = graph()->NewNode(machine()->Uint32MulHigh(), dividend,
                                    Uint32Constant(mag.multiplier));
  if (mag.add) {
    DCHECK_LE(1u, mag.shift);
    quotient = Word32Shr(
        Int32Add(Word32Shr(Int32Sub(dividend, quotient), 1), quotient),
        mag.shift - 1);
  } else {
    quotient = Word32Shr(quotient, mag.shift);
  }
  return quotient;
}
References v8::base::bits::CountTrailingZeros(), DCHECK_LE, DCHECK_LT, graph(), Int32Add(), Int32Sub(), machine(), v8::internal::compiler::TFGraph::NewNode(), Uint32Constant(), v8::base::UnsignedDivisionByConstant(), and Word32Shr().
Referenced by ReduceUint32Div(), and ReduceUint32Mod().
Uint64Constant()
Node* v8::internal::compiler::MachineOperatorReducer::Uint64Constant (uint64_t value) [inline], [private]
Definition at line 55 of file machine-operator-reducer.h.
                                       {
    return Int64Constant(base::bit_cast<int64_t>(value));
  }
References v8::internal::value.
Referenced by Int64Div(), ReduceUint64Div(), ReduceUint64Mod(), ReduceWord64Equal(), ReduceWord64Shl(), Uint64Div(), v8::internal::compiler::Word64Adapter::UintNConstant(), Word64Sar(), and Word64Shr().
Uint64Div()
Node * v8::internal::compiler::MachineOperatorReducer::Uint64Div (Node * dividend, uint64_t divisor) [private]
Definition at line 357 of file machine-operator-reducer.cc.
                                                                        {
  DCHECK_LT(0u, divisor);
  // If the divisor is even, we can avoid using the expensive fixup by shifting
  // the dividend upfront.
  unsigned const shift = base::bits::CountTrailingZeros(divisor);
  dividend = Word64Shr(dividend, shift);
  divisor >>= shift;
  // Compute the magic number for the (shifted) divisor.
  base::MagicNumbersForDivision<uint64_t> const mag =
      base::UnsignedDivisionByConstant(divisor, shift);
  Node* quotient = graph()->NewNode(machine()->Uint64MulHigh(), dividend,
                                    Uint64Constant(mag.multiplier));
  if (mag.add) {
    DCHECK_LE(1u, mag.shift);
    quotient = Word64Shr(
        Int64Add(Word64Shr(Int64Sub(dividend, quotient), 1), quotient),
        mag.shift - 1);
  } else {
    quotient = Word64Shr(quotient, mag.shift);
  }
  return quotient;
}
References v8::base::bits::CountTrailingZeros(), DCHECK_LE, DCHECK_LT, graph(), Int64Add(), Int64Sub(), machine(), v8::internal::compiler::TFGraph::NewNode(), Uint64Constant(), v8::base::UnsignedDivisionByConstant(), and Word64Shr().
Referenced by ReduceUint64Div(), and ReduceUint64Mod().
Word32And() [1/2]
Node * v8::internal::compiler::MachineOperatorReducer::Word32And (Node * lhs, Node * rhs) [private]
Definition at line 232 of file machine-operator-reducer.cc.
                                                            {
  Node* const node = graph()->NewNode(machine()->Word32And(), lhs, rhs);
  Reduction const reduction = ReduceWord32And(node);
  return reduction.Changed() ? reduction.replacement() : node;
}
References v8::internal::compiler::Reduction::Changed(), graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), ReduceWord32And(), and v8::internal::compiler::Reduction::replacement().
Referenced by ReduceInt32Mod(), ReduceUint32Mod(), ReduceWord32And(), ReduceWord32Shl(), ReduceWordEqualForConstantRhs(), and v8::internal::compiler::Word32Adapter::WordNAnd().
Word32And() [2/2]
Node* v8::internal::compiler::MachineOperatorReducer::Word32And (Node * lhs, uint32_t rhs) [inline], [private]
Definition at line 61 of file machine-operator-reducer.h.
                                           {
    return Word32And(lhs, Uint32Constant(rhs));
  }
Word32Equal()
Node * v8::internal::compiler::MachineOperatorReducer::Word32Equal (Node * lhs, Node * rhs) [private]
Definition at line 258 of file machine-operator-reducer.cc.
                                                              {
  return graph()->NewNode(machine()->Word32Equal(), lhs, rhs);
}
References graph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by ReduceInt32Div(), ReduceUint32Div(), ReduceWord32And(), ReduceWord32Xor(), and ReduceWord64Equal().
Word32Sar()
Node * v8::internal::compiler::MachineOperatorReducer::Word32Sar (Node * lhs, uint32_t rhs) [private]
Definition at line 238 of file machine-operator-reducer.cc.
                                                               {
  if (rhs == 0) return lhs;
  return graph()->NewNode(machine()->Word32Sar(), lhs, Uint32Constant(rhs));
}
References graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), and Uint32Constant().
Referenced by Int32Div(), ReduceInt32Div(), and ReduceWord32Shl().
Word32Shr()
Node * v8::internal::compiler::MachineOperatorReducer::Word32Shr (Node * lhs, uint32_t rhs) [private]
Definition at line 248 of file machine-operator-reducer.cc.
                                                               {
  if (rhs == 0) return lhs;
  return graph()->NewNode(machine()->Word32Shr(), lhs, Uint32Constant(rhs));
}
References graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), and Uint32Constant().
Referenced by Int32Div(), ReduceInt32Div(), ReduceUint32Div(), and Uint32Div().
Word64And() [1/2]
Node * v8::internal::compiler::MachineOperatorReducer::Word64And (Node * lhs, Node * rhs) [private]
Definition at line 266 of file machine-operator-reducer.cc.
                                                            {
  Node* const node = graph()->NewNode(machine()->Word64And(), lhs, rhs);
  Reduction const reduction = ReduceWord64And(node);
  return reduction.Changed() ? reduction.replacement() : node;
}
References v8::internal::compiler::Reduction::Changed(), graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), ReduceWord64And(), and v8::internal::compiler::Reduction::replacement().
Referenced by ReduceInt64Mod(), ReduceUint64Mod(), ReduceWord64Shl(), and v8::internal::compiler::Word64Adapter::WordNAnd().
Word64And() [2/2]
Node* v8::internal::compiler::MachineOperatorReducer::Word64And (Node * lhs, uint64_t rhs) [inline], [private]
Definition at line 71 of file machine-operator-reducer.h.
                                           {
    return Word64And(lhs, Uint64Constant(rhs));
  }
Word64Equal()
Node * v8::internal::compiler::MachineOperatorReducer::Word64Equal (Node * lhs, Node * rhs) [private]
Definition at line 262 of file machine-operator-reducer.cc.
                                                              {
  return graph()->NewNode(machine()->Word64Equal(), lhs, rhs);
}
References graph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by ReduceInt64Div(), and ReduceUint64Div().
Word64Sar()
Node * v8::internal::compiler::MachineOperatorReducer::Word64Sar (Node * lhs, uint32_t rhs) [private]
Definition at line 243 of file machine-operator-reducer.cc.
                                                               {
  if (rhs == 0) return lhs;
  return graph()->NewNode(machine()->Word64Sar(), lhs, Uint64Constant(rhs));
}
References graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), and Uint64Constant().
Referenced by Int64Div(), ReduceInt64Div(), and ReduceWord64Shl().
Word64Shr()
Node * v8::internal::compiler::MachineOperatorReducer::Word64Shr (Node * lhs, uint32_t rhs) [private]
Definition at line 253 of file machine-operator-reducer.cc.
                                                               {
  if (rhs == 0) return lhs;
  return graph()->NewNode(machine()->Word64Shr(), lhs, Uint64Constant(rhs));
}
References graph(), machine(), v8::internal::compiler::TFGraph::NewNode(), and Uint64Constant().
Referenced by Int64Div(), ReduceInt64Div(), ReduceUint64Div(), and Uint64Div().
Friends And Related Function Documentation
Word32Adapter
friend class Word32Adapter [friend]
Definition at line 45 of file machine-operator-reducer.h.
Word64Adapter
friend class Word64Adapter [friend]
Definition at line 46 of file machine-operator-reducer.h.
Member Data Documentation
mcgraph_
MachineGraph* v8::internal::compiler::MachineOperatorReducer::mcgraph_ [private]
Definition at line 186 of file machine-operator-reducer.h.
signalling_nan_propagation_
SignallingNanPropagation v8::internal::compiler::MachineOperatorReducer::signalling_nan_propagation_ [private]
Definition at line 187 of file machine-operator-reducer.h.
Referenced by Reduce().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/machine-operator-reducer.h
/mnt/V8SourceCode/src/compiler/machine-operator-reducer.cc