v8::internal::wasm::WasmBytecodeGenerator::RollbackStack Class Reference
Classes
struct Entry
Public Types
typedef std::vector< uint32_t > Stack
Public Member Functions
void push_back (const uint32_t &value)
void pop_back ()
Stack::reference back ()
Stack::const_reference back () const
Stack::reference operator[] (Stack::size_type pos)
Stack::const_reference operator[] (Stack::size_type pos) const
size_t size () const
bool empty () const
void reserve (Stack::size_type new_cap)
void resize (Stack::size_type count)
void clear_history ()
void rollback ()
Private Types
enum EntryKind { Push
, Pop
 }
Private Attributes
Stack stack_
std::vector< Entry > history_
Detailed Description
Definition at line 2004 of file wasm-interpreter.h.
Member Typedef Documentation
Stack
typedef std::vector<uint32_t> v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::Stack
Definition at line 2006 of file wasm-interpreter.h.
Member Enumeration Documentation
EntryKind
enum v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::EntryKind [private]
Enumerator
Push
Pop
Definition at line 2041 of file wasm-interpreter.h.
{ Push, Pop };
Member Function Documentation
back() [1/2]
Stack::reference v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::back () [inline]
Definition at line 2015 of file wasm-interpreter.h.
{ return stack_.back(); }
References stack_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::CopyToSlotAndPop(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::Pop(), pop_back(), v8::internal::wasm::WasmBytecodeGenerator::PopSlot(), and v8::internal::wasm::WasmBytecodeGenerator::RefPop().
back() [2/2]
Stack::const_reference v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::back () const [inline]
Definition at line 2016 of file wasm-interpreter.h.
{ return stack_.back(); }
References stack_.
clear_history()
void v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::clear_history () [inline]
Definition at line 2026 of file wasm-interpreter.h.
{ history_.resize(0); }
References history_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::EncodeInstruction(), and v8::internal::wasm::WasmBytecodeGenerator::EncodeSuperInstruction().
empty()
bool v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::empty () const [inline]
Definition at line 2022 of file wasm-interpreter.h.
{ return stack_.empty(); }
References stack_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::CopyToSlotAndPop(), and v8::internal::wasm::WasmBytecodeGenerator::stack_top_index().
operator[]() [1/2]
Stack::reference v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::operator[] (Stack::size_type pos) [inline]
Definition at line 2017 of file wasm-interpreter.h.
{ return stack_[pos]; }
References stack_.
operator[]() [2/2]
Stack::const_reference v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::operator[] (Stack::size_type pos) const [inline]
Definition at line 2018 of file wasm-interpreter.h.
                                                              {
      return stack_[pos];
    }
References stack_.
pop_back()
void v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::pop_back () [inline]
Definition at line 2011 of file wasm-interpreter.h.
                    {
      history_.push_back({Pop, back()});
      stack_.pop_back();
    }
References back(), history_, Pop, and stack_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::PopSlot().
push_back()
void v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::push_back (const uint32_t & value) [inline]
Definition at line 2007 of file wasm-interpreter.h.
                                          {
      stack_.push_back(value);
      history_.push_back({Push, value});
    }
References history_, Push, stack_, and v8::internal::value.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), and v8::internal::wasm::WasmBytecodeGenerator::PushSlot().
reserve()
void v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::reserve (Stack::size_type new_cap) [inline]
Definition at line 2023 of file wasm-interpreter.h.
{ stack_.reserve(new_cap); }
References stack_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::WasmBytecodeGenerator().
resize()
void v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::resize (Stack::size_type count) [inline]
Definition at line 2024 of file wasm-interpreter.h.
{ stack_.resize(count); }
References stack_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::RestoreIfElseParams(), and v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsAndResultsIntoSlots().
rollback()
void v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::rollback () [inline]
Definition at line 2027 of file wasm-interpreter.h.
                    {
      while (!history_.empty()) {
        Entry entry = history_.back();
        history_.pop_back();
        if (entry.kind == EntryKind::Push) {
          stack_.pop_back();
        } else {
          DCHECK_EQ(entry.kind, EntryKind::Pop);
          stack_.push_back(entry.value);
        }
      }
    }
References DCHECK_EQ, history_, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::Entry::kind, stack_, and v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::Entry::value.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::EncodeInstruction(), and v8::internal::wasm::WasmBytecodeGenerator::EncodeSuperInstruction().
size()
size_t v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size () const [inline]
Definition at line 2021 of file wasm-interpreter.h.
{ return stack_.size(); }
References stack_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::CopyToSlotAndPop(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::FindSharedSlot(), v8::internal::wasm::WasmBytecodeGenerator::HasSharedSlot(), v8::internal::wasm::WasmBytecodeGenerator::InitSlotsForFunctionArgs(), v8::internal::wasm::WasmBytecodeGenerator::SetSlotType(), v8::internal::wasm::WasmBytecodeGenerator::stack_size(), v8::internal::wasm::WasmBytecodeGenerator::stack_top_index(), v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsAndResultsIntoSlots(), and v8::internal::wasm::WasmBytecodeGenerator::UpdateStack().
Member Data Documentation
history_
std::vector<Entry> v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::history_ [private]
Definition at line 2047 of file wasm-interpreter.h.
Referenced by clear_history(), pop_back(), push_back(), and rollback().
stack_
Stack v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::stack_ [private]
Definition at line 2046 of file wasm-interpreter.h.
Referenced by back(), empty(), operator[](), pop_back(), push_back(), reserve(), resize(), rollback(), and size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h