v8::internal::compiler::OptionalRef< TRef > Class Template Reference
#include <heap-refs.h>
Classes
class ArrowOperatorHelper
Public Member Functions
OptionalRef ()=default
OptionalRef (std::nullopt_t)
template<typename SRef >
OptionalRef (OptionalRef< SRef > ref) requires std
template<typename SRef >
OptionalRef (SRef ref) requires std
constexpr bool has_value () const
constexpr operator bool () const
TRef value () const
TRef operator* () const
ArrowOperatorHelper operator-> () const
bool equals (OptionalRef other) const
size_t hash_value () const
Private Member Functions
OptionalRef (ObjectData *data)
Private Attributes
ObjectData * data_ = nullptr
Friends
template<typename SRef >
class OptionalRef
Detailed Description
template<typename TRef>
class v8::internal::compiler::OptionalRef< TRef >
Definition at line 310 of file heap-refs.h.
Constructor & Destructor Documentation
OptionalRef() [1/5]
template<typename TRef >
v8::internal::compiler::OptionalRef< TRef >::OptionalRef () [default]
OptionalRef() [2/5]
template<typename TRef >
v8::internal::compiler::OptionalRef< TRef >::OptionalRef (std::nullopt_t) [inline]
Definition at line 331 of file heap-refs.h.
: OptionalRef() {}
OptionalRef() [3/5]
template<typename TRef >
template<typename SRef >
v8::internal::compiler::OptionalRef< TRef >::OptionalRef (OptionalRef< SRef > ref) [inline]
Definition at line 336 of file heap-refs.h.
      : data_(ref.data_) {}
OptionalRef() [4/5]
template<typename TRef >
template<typename SRef >
v8::internal::compiler::OptionalRef< TRef >::OptionalRef (SRef ref) [inline]
Definition at line 343 of file heap-refs.h.
      : data_(ref.data_) {}
OptionalRef() [5/5]
template<typename TRef >
v8::internal::compiler::OptionalRef< TRef >::OptionalRef (ObjectData * data) [inline], [explicit], [private]
Definition at line 366 of file heap-refs.h.
                                         : data_(data) {
    CHECK_NOT_NULL(data_);
  }
References CHECK_NOT_NULL, and v8::internal::compiler::OptionalRef< TRef >::data_.
Member Function Documentation
equals()
template<typename TRef >
bool v8::internal::compiler::OptionalRef< TRef >::equals (OptionalRef< TRef > other) const [inline]
Definition at line 359 of file heap-refs.h.
{ return data_ == other.data_; }
References v8::internal::compiler::OptionalRef< TRef >::data_.
Referenced by v8::internal::compiler::operator==().
has_value()
template<typename TRef >
constexpr bool v8::internal::compiler::OptionalRef< TRef >::has_value () const [inline], [constexpr]
Definition at line 347 of file heap-refs.h.
{ return data_ != nullptr; }
References v8::internal::compiler::OptionalRef< TRef >::data_.
Referenced by v8::internal::compiler::anonymous_namespace{js-operator.cc}::AddressOrNull(), v8::internal::compiler::OptionalRef< TRef >::hash_value(), v8::internal::compiler::OptionalRef< TRef >::operator bool(), v8::internal::compiler::anonymous_namespace{access-info.cc}::OptionalRefEquals(), and v8::internal::compiler::OptionalRef< TRef >::value().
hash_value()
template<typename TRef >
size_t v8::internal::compiler::OptionalRef< TRef >::hash_value () const [inline]
Definition at line 361 of file heap-refs.h.
                            {
    return has_value() ? value().hash_value() : base::hash_value(0);
  }
References v8::internal::compiler::OptionalRef< TRef >::has_value(), v8::base::hash_value(), and v8::internal::compiler::OptionalRef< TRef >::value().
Referenced by v8::internal::compiler::hash_value().
operator bool()
template<typename TRef >
constexpr v8::internal::compiler::OptionalRef< TRef >::operator bool () const [inline], [explicit], [constexpr]
Definition at line 348 of file heap-refs.h.
{ return has_value(); }
References v8::internal::compiler::OptionalRef< TRef >::has_value().
operator*()
template<typename TRef >
TRef v8::internal::compiler::OptionalRef< TRef >::operator* () const [inline]
Definition at line 354 of file heap-refs.h.
{ return value(); }
References v8::internal::compiler::OptionalRef< TRef >::value().
operator->()
template<typename TRef >
ArrowOperatorHelper v8::internal::compiler::OptionalRef< TRef >::operator-> () const [inline]
Definition at line 355 of file heap-refs.h.
                                         {
    return ArrowOperatorHelper(value());
  }
References v8::internal::compiler::OptionalRef< TRef >::value().
value()
template<typename TRef >
TRef v8::internal::compiler::OptionalRef< TRef >::value () const [inline]
Definition at line 350 of file heap-refs.h.
                     {
    DCHECK(has_value());
    return TRef(data_, false);
  }
References v8::internal::compiler::OptionalRef< TRef >::data_, v8::internal::DCHECK(), and v8::internal::compiler::OptionalRef< TRef >::has_value().
Referenced by v8::internal::compiler::OptionalRef< TRef >::hash_value(), v8::internal::compiler::OptionalRef< TRef >::operator*(), v8::internal::compiler::OptionalRef< TRef >::operator->(), and v8::internal::compiler::anonymous_namespace{access-info.cc}::OptionalRefEquals().
Friends And Related Function Documentation
OptionalRef
template<typename TRef >
template<typename SRef >
friend class OptionalRef [friend]
Definition at line 372 of file heap-refs.h.
Member Data Documentation
data_
template<typename TRef >
ObjectData* v8::internal::compiler::OptionalRef< TRef >::data_ = nullptr [private]
Definition at line 369 of file heap-refs.h.
Referenced by v8::internal::compiler::OptionalRef< TRef >::equals(), v8::internal::compiler::OptionalRef< TRef >::has_value(), v8::internal::compiler::OptionalRef< TRef >::OptionalRef(), and v8::internal::compiler::OptionalRef< TRef >::value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/heap-refs.h