v8::internal::maglev::ProcessingState Class Reference
#include <maglev-graph-processor.h>
Public Member Functions
ProcessingState (BlockConstIterator block_it, NodeIterator *node_it=nullptr)
ProcessingState (const ProcessingState &)=delete
ProcessingState & operator= (const ProcessingState &)=delete
BasicBlock * block () const
BasicBlock * next_block () const
NodeIterator * node_it () const
Private Attributes
BlockConstIterator block_it_
NodeIterator * node_it_
Detailed Description
Definition at line 66 of file maglev-graph-processor.h.
Constructor & Destructor Documentation
ProcessingState() [1/2]
v8::internal::maglev::ProcessingState::ProcessingState (BlockConstIterator block_it, NodeIterator * node_it = nullptr) [inline], [explicit]
Definition at line 68 of file maglev-graph-processor.h.
      : block_it_(block_it), node_it_(node_it) {}
ProcessingState() [2/2]
v8::internal::maglev::ProcessingState::ProcessingState (const ProcessingState &) [delete]
Member Function Documentation
block()
BasicBlock* v8::internal::maglev::ProcessingState::block () const [inline]
Definition at line 76 of file maglev-graph-processor.h.
{ return *block_it_; }
References block_it_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
next_block()
BasicBlock* v8::internal::maglev::ProcessingState::next_block () const [inline]
Definition at line 77 of file maglev-graph-processor.h.
{ return *(block_it_ + 1); }
References block_it_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
node_it()
NodeIterator* v8::internal::maglev::ProcessingState::node_it () const [inline]
Definition at line 79 of file maglev-graph-processor.h.
                                {
    DCHECK_NOT_NULL(node_it_);
    return node_it_;
  }
References DCHECK_NOT_NULL, and node_it_.
operator=()
ProcessingState& v8::internal::maglev::ProcessingState::operator= (const ProcessingState &) [delete]
Member Data Documentation
block_it_
BlockConstIterator v8::internal::maglev::ProcessingState::block_it_ [private]
Definition at line 85 of file maglev-graph-processor.h.
Referenced by block(), and next_block().
node_it_
NodeIterator* v8::internal::maglev::ProcessingState::node_it_ [private]
Definition at line 86 of file maglev-graph-processor.h.
Referenced by node_it().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-processor.h