v8::metrics::Recorder::ContextId Class Reference
#include <v8-metrics.h>
Public Member Functions
ContextId ()
bool IsEmpty () const
bool operator== (const ContextId &other) const
bool operator!= (const ContextId &other) const
Static Public Member Functions
static const ContextId Empty ()
Private Member Functions
ContextId (uintptr_t id)
Private Attributes
uintptr_t id_
Static Private Attributes
static constexpr uintptr_t kEmptyId = 0
Friends
class ::v8::Context
class ::v8::internal::Isolate
Detailed Description
Definition at line 190 of file v8-metrics.h.
Constructor & Destructor Documentation
ContextId() [1/2]
v8::metrics::Recorder::ContextId::ContextId () [inline]
Definition at line 192 of file v8-metrics.h.
: id_(kEmptyId) {}
ContextId() [2/2]
v8::metrics::Recorder::ContextId::ContextId (uintptr_t id) [inline], [explicit], [private]
Definition at line 204 of file v8-metrics.h.
: id_(id) {}
Member Function Documentation
Empty()
static const ContextId v8::metrics::Recorder::ContextId::Empty () [inline], [static]
Definition at line 195 of file v8-metrics.h.
{ return ContextId{kEmptyId}; }
Referenced by v8::internal::CppHeap::MetricRecorderAdapter::GetContextId(), v8::internal::anonymous_namespace{gc-tracer.cc}::GetContextId(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), and v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs().
IsEmpty()
bool v8::metrics::Recorder::ContextId::IsEmpty () const [inline]
Definition at line 194 of file v8-metrics.h.
{ return id_ == kEmptyId; }
operator!=()
bool v8::metrics::Recorder::ContextId::operator!= (const ContextId & other) const [inline]
Definition at line 198 of file v8-metrics.h.
{ return id_ != other.id_; }
References id_.
operator==()
bool v8::metrics::Recorder::ContextId::operator== (const ContextId & other) const [inline]
Definition at line 197 of file v8-metrics.h.
{ return id_ == other.id_; }
References id_.
Friends And Related Function Documentation
::v8::Context
friend class ::v8::Context [friend]
Definition at line 201 of file v8-metrics.h.
::v8::internal::Isolate
friend class ::v8::internal::Isolate [friend]
Definition at line 202 of file v8-metrics.h.
Member Data Documentation
id_
uintptr_t v8::metrics::Recorder::ContextId::id_ [private]
Definition at line 207 of file v8-metrics.h.
Referenced by operator!=(), and operator==().
kEmptyId
constexpr uintptr_t v8::metrics::Recorder::ContextId::kEmptyId = 0 [static], [constexpr], [private]
Definition at line 206 of file v8-metrics.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-metrics.h