v8::internal::ModuleScope Class Reference
#include <scopes.h>
Public Member Functions
ModuleScope (DeclarationScope *script_scope, AstValueFactory *avfactory)
ModuleScope (Handle< ScopeInfo > scope_info, AstValueFactory *avfactory)
SourceTextModuleDescriptor * module () const
void AllocateModuleVariables ()
Private Attributes
SourceTextModuleDescriptor *const module_descriptor_
Additional Inherited Members
Detailed Description
Definition at line 1382 of file scopes.h.
Constructor & Destructor Documentation
ModuleScope() [1/2]
v8::internal::ModuleScope::ModuleScope (DeclarationScope * script_scope, AstValueFactory * avfactory)
Definition at line 176 of file scopes.cc.
    : DeclarationScope(avfactory->single_parse_zone(), script_scope,
                       MODULE_SCOPE, FunctionKind::kModule),
      module_descriptor_(
          avfactory->single_parse_zone()->New<SourceTextModuleDescriptor>(
              avfactory->single_parse_zone())) {
  set_language_mode(LanguageMode::kStrict);
  DeclareThis(avfactory);
}
References v8::internal::DeclarationScope::DeclareThis(), v8::internal::kModule, v8::internal::kStrict, and v8::internal::Scope::set_language_mode().
ModuleScope() [2/2]
v8::internal::ModuleScope::ModuleScope (Handle< ScopeInfo > scope_info, AstValueFactory * avfactory)
Definition at line 187 of file scopes.cc.
    : DeclarationScope(avfactory->single_parse_zone(), MODULE_SCOPE, avfactory,
                       scope_info),
      module_descriptor_(nullptr) {
  set_language_mode(LanguageMode::kStrict);
}
References v8::internal::kStrict, and v8::internal::Scope::set_language_mode().
Member Function Documentation
AllocateModuleVariables()
void v8::internal::ModuleScope::AllocateModuleVariables ()
Definition at line 2570 of file scopes.cc.
                                          {
  for (const auto& it : module()->regular_imports()) {
    Variable* var = LookupLocal(it.first);
    var->AllocateTo(VariableLocation::MODULE, it.second->cell_index);
    DCHECK(!var->IsExport());
  }
  for (const auto& it : module()->regular_exports()) {
    Variable* var = LookupLocal(it.first);
    var->AllocateTo(VariableLocation::MODULE, it.second->cell_index);
    DCHECK(var->IsExport());
  }
}
References v8::internal::Variable::AllocateTo(), v8::internal::DCHECK(), v8::internal::Variable::IsExport(), v8::internal::Scope::LookupLocal(), and v8::internal::MODULE.
Referenced by v8::internal::DeclarationScope::AllocateVariables().
module()
SourceTextModuleDescriptor* v8::internal::ModuleScope::module () const [inline]
Definition at line 1390 of file scopes.h.
{ return module_descriptor_; }
Referenced by v8::internal::ScopeInfo::Create(), v8::internal::ParserBase< Impl >::module(), v8::internal::SourceTextModuleDescriptor::Validate(), and v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports().
Member Data Documentation
module_descriptor_
SourceTextModuleDescriptor* const v8::internal::ModuleScope::module_descriptor_ [private]
Definition at line 1397 of file scopes.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/scopes.h
/mnt/V8SourceCode/src/ast/scopes.cc