v8::internal::wasm::gdb_server::Session Class Reference
#include <session.h>
Public Member Functions
Session (TransportBase *transport)
Session (const Session &)=delete
Session & operator= (const Session &)=delete
bool SendPacket (Packet *packet, bool expect_ack=true)
bool GetPacket (Packet *packet)
bool IsDataAvailable () const
bool IsConnected () const
void Disconnect ()
void WaitForDebugStubEvent ()
bool SignalThreadEvent ()
void EnableAck (bool ack_enabled)
Private Member Functions
bool GetChar (char *ch)
bool GetPayload (Packet *pkt, uint8_t *checksum)
Private Attributes
TransportBase * io_
bool connected_
bool ack_enabled_
Detailed Description
Definition at line 19 of file session.h.
Constructor & Destructor Documentation
Session() [1/2]
v8::internal::wasm::gdb_server::Session::Session (TransportBase * transport) [explicit]
Definition at line 14 of file session.cc.
    : io_(transport), connected_(true), ack_enabled_(true) {}
Session() [2/2]
v8::internal::wasm::gdb_server::Session::Session (const Session &) [delete]
Member Function Documentation
Disconnect()
void v8::internal::wasm::gdb_server::Session::Disconnect ()
Definition at line 25 of file session.cc.
                         {
  io_->Disconnect();
  connected_ = false;
}
References connected_, v8::internal::wasm::gdb_server::TransportBase::Disconnect(), and io_.
Referenced by GetChar(), and v8::internal::wasm::gdb_server::Target::ProcessCommands().
EnableAck()
void v8::internal::wasm::gdb_server::Session::EnableAck (bool ack_enabled) [inline]
Definition at line 54 of file session.h.
{ ack_enabled_ = ack_enabled; }
GetChar()
bool v8::internal::wasm::gdb_server::Session::GetChar (char * ch) [private]
Definition at line 30 of file session.cc.
                              {
  if (!io_->Read(ch, 1)) {
    Disconnect();
    return false;
  }
  return true;
}
References Disconnect(), io_, and v8::internal::wasm::gdb_server::TransportBase::Read().
Referenced by GetPacket(), GetPayload(), and SendPacket().
GetPacket()
bool v8::internal::wasm::gdb_server::Session::GetPacket (Packet * packet)
Definition at line 91 of file session.cc.
                                   {
  while (true) {
    // Toss characters until we see a start of command
    char ch;
    do {
      if (!GetChar(&ch)) {
        return false;
      }
    } while (ch != '$');
    uint8_t running_checksum = 0;
    if (!GetPayload(pkt, &running_checksum)) {
      return false;
    }
    // Get two nibble checksum
    uint8_t trailing_checksum = 0;
    char chars[2];
    if (!GetChar(&chars[0]) || !GetChar(&chars[1]) ||
        !HexToUInt8(chars, &trailing_checksum)) {
      return false;
    }
    TRACE_GDB_REMOTE("RX $%s#%c%c\n", pkt->GetPayload(), chars[0], chars[1]);
    pkt->ParseSequence();
    // If ACKs are off, we are done.
    if (!ack_enabled_) {
      return true;
    }
    // If the XSUMs don't match, signal bad packet
    if (trailing_checksum == running_checksum) {
      char out[3] = {'+', 0, 0};
      // If we have a sequence number
      int32_t seq;
      if (pkt->GetSequence(&seq)) {
        // Respond with sequence number
        UInt8ToHex(seq, &out[1]);
        return io_->Write(out, 3);
      } else {
        return io_->Write(out, 1);
      }
    } else {
      // Resend a bad XSUM and look for retransmit
      TRACE_GDB_REMOTE("RX Bad XSUM, retry\n");
      io_->Write("-", 1);
      // retry...
    }
  }
}
References ack_enabled_, GetChar(), v8::internal::wasm::gdb_server::Packet::GetPayload(), GetPayload(), v8::internal::wasm::gdb_server::Packet::GetSequence(), v8::internal::wasm::gdb_server::HexToUInt8(), io_, v8::internal::wasm::gdb_server::Packet::ParseSequence(), TRACE_GDB_REMOTE, v8::internal::wasm::gdb_server::UInt8ToHex(), and v8::internal::wasm::gdb_server::TransportBase::Write().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessCommands().
GetPayload()
bool v8::internal::wasm::gdb_server::Session::GetPayload (Packet * pkt, uint8_t * checksum) [private]
Definition at line 67 of file session.cc.
                                                       {
  pkt->Clear();
  *checksum = 0;
  // Stream in the characters
  char ch;
  while (GetChar(&ch)) {
    if (ch == '#') {
      // If we see a '#' we must be done with the data.
      return true;
    } else if (ch == '$') {
      // If we see a '$' we must have missed the last cmd, let's retry.
      TRACE_GDB_REMOTE("RX Missing $, retry.\n");
      *checksum = 0;
      pkt->Clear();
    } else {
      // Keep a running XSUM.
      *checksum += ch;
      pkt->AddRawChar(ch);
    }
  }
  return false;
}
References v8::internal::wasm::gdb_server::Packet::AddRawChar(), v8::internal::wasm::gdb_server::Packet::Clear(), GetChar(), and TRACE_GDB_REMOTE.
Referenced by GetPacket().
IsConnected()
bool v8::internal::wasm::gdb_server::Session::IsConnected () const
Definition at line 23 of file session.cc.
{ return connected_; }
References connected_.
Referenced by v8::internal::wasm::gdb_server::Target::ProcessCommands(), and v8::internal::wasm::gdb_server::Target::Run().
IsDataAvailable()
bool v8::internal::wasm::gdb_server::Session::IsDataAvailable () const
Definition at line 21 of file session.cc.
{ return io_->IsDataAvailable(); }
References io_, and v8::internal::wasm::gdb_server::TransportBase::IsDataAvailable().
operator=()
Session& v8::internal::wasm::gdb_server::Session::operator= (const Session &) [delete]
SendPacket()
bool v8::internal::wasm::gdb_server::Session::SendPacket (Packet * packet, bool expect_ack = true)
Definition at line 39 of file session.cc.
                                                     {
  char ch;
  do {
    std::string data = pkt->GetPacketData();
    TRACE_GDB_REMOTE("TX %s\n", data.size() < 160
                                    ? data.c_str()
                                    : (data.substr(0, 160) + "...").c_str());
    if (!io_->Write(data.data(), static_cast<int32_t>(data.length()))) {
      return false;
    }
    // If ACKs are off, we are done.
    if (!expect_ack || !ack_enabled_) {
      break;
    }
    // Otherwise, poll for '+'
    if (!GetChar(&ch)) {
      return false;
    }
    // Retry if we didn't get a '+'
  } while (ch != '+');
  return true;
}
References ack_enabled_, GetChar(), v8::internal::wasm::gdb_server::Packet::GetPacketData(), io_, v8::internal::string, TRACE_GDB_REMOTE, and v8::internal::wasm::gdb_server::TransportBase::Write().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessCommands(), and v8::internal::wasm::gdb_server::Target::ProcessDebugEvent().
SignalThreadEvent()
bool v8::internal::wasm::gdb_server::Session::SignalThreadEvent ()
Definition at line 19 of file session.cc.
{ return io_->SignalThreadEvent(); }
References io_, and v8::internal::wasm::gdb_server::TransportBase::SignalThreadEvent().
Referenced by v8::internal::wasm::gdb_server::Target::OnSuspended().
WaitForDebugStubEvent()
void v8::internal::wasm::gdb_server::Session::WaitForDebugStubEvent ()
Definition at line 17 of file session.cc.
{ io_->WaitForDebugStubEvent(); }
References io_, and v8::internal::wasm::gdb_server::TransportBase::WaitForDebugStubEvent().
Referenced by v8::internal::wasm::gdb_server::Target::WaitForDebugEvent().
Member Data Documentation
ack_enabled_
bool v8::internal::wasm::gdb_server::Session::ack_enabled_ [private]
Definition at line 65 of file session.h.
Referenced by GetPacket(), and SendPacket().
connected_
bool v8::internal::wasm::gdb_server::Session::connected_ [private]
Definition at line 64 of file session.h.
Referenced by Disconnect(), and IsConnected().
io_
TransportBase* v8::internal::wasm::gdb_server::Session::io_ [private]
Definition at line 63 of file session.h.
Referenced by Disconnect(), GetChar(), GetPacket(), IsDataAvailable(), SendPacket(), SignalThreadEvent(), and WaitForDebugStubEvent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/session.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/session.cc