v8::internal::maglev::TransitionAndStoreArrayElement Class Reference
#include <maglev-ir.h>
Public Member Functions
TransitionAndStoreArrayElement (uint64_t bitfield, const compiler::MapRef &fast_map, const compiler::MapRef &double_map)
Input & array_input ()
Input & index_input ()
Input & value_input ()
compiler::MapRef fast_map () const
compiler::MapRef double_map () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 3, TransitionAndStoreArrayElement >
Private Attributes
const compiler::MapRef fast_map_
const compiler::MapRef double_map_
Additional Inherited Members
Detailed Description
Definition at line 7891 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TransitionAndStoreArrayElement::Base = FixedInputValueNodeT<3, TransitionAndStoreArrayElement> [private]
Definition at line 7893 of file maglev-ir.h.
Constructor & Destructor Documentation
TransitionAndStoreArrayElement()
v8::internal::maglev::TransitionAndStoreArrayElement::TransitionAndStoreArrayElement (uint64_t bitfield, const compiler::MapRef & fast_map, const compiler::MapRef & double_map) [inline], [explicit]
Definition at line 7896 of file maglev-ir.h.
      : Base(bitfield), fast_map_(fast_map), double_map_(double_map) {}
Member Function Documentation
array_input()
Input& v8::internal::maglev::TransitionAndStoreArrayElement::array_input () [inline]
Definition at line 7907 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
double_map()
compiler::MapRef v8::internal::maglev::TransitionAndStoreArrayElement::double_map () const [inline]
Definition at line 7912 of file maglev-ir.h.
{ return double_map_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
fast_map()
compiler::MapRef v8::internal::maglev::TransitionAndStoreArrayElement::fast_map () const [inline]
Definition at line 7911 of file maglev-ir.h.
{ return fast_map_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::TransitionAndStoreArrayElement::GenerateCode (MaglevAssembler * , const ProcessingState &)
index_input()
Input& v8::internal::maglev::TransitionAndStoreArrayElement::index_input () [inline]
Definition at line 7908 of file maglev-ir.h.
{ return input(1); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::TransitionAndStoreArrayElement::MaxCallStackArgs () const [inline]
Definition at line 7914 of file maglev-ir.h.
                               {
    // Only implemented in Turbolev.
    UNREACHABLE();
  }
References UNREACHABLE.
PrintParams()
void v8::internal::maglev::TransitionAndStoreArrayElement::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 7921 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::TransitionAndStoreArrayElement::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::TransitionAndStoreArrayElement::value_input () [inline]
Definition at line 7909 of file maglev-ir.h.
{ return input(2); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
double_map_
const compiler::MapRef v8::internal::maglev::TransitionAndStoreArrayElement::double_map_ [private]
Definition at line 7925 of file maglev-ir.h.
fast_map_
const compiler::MapRef v8::internal::maglev::TransitionAndStoreArrayElement::fast_map_ [private]
Definition at line 7924 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::TransitionAndStoreArrayElement::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kInt32,
      ValueRepresentation::kTagged}
Definition at line 7903 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::TransitionAndStoreArrayElement::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::AnySideEffects() | OpProperties::DeferredCall()
Definition at line 7901 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h