v8::internal::WasmJSFunction Class Reference
#include <wasm-objects.h>
Public Member Functions
OBJECT_CONSTRUCTORS (WasmJSFunction, JSFunction)
Static Public Member Functions
static bool IsWasmJSFunction (Tagged< Object > object)
static DirectHandle< WasmJSFunction > New (Isolate *isolate, const wasm::FunctionSig *sig, DirectHandle< JSReceiver > callable, wasm::Suspend suspend)
Additional Inherited Members
Detailed Description
Definition at line 1029 of file wasm-objects.h.
Member Function Documentation
IsWasmJSFunction()
bool v8::internal::WasmJSFunction::IsWasmJSFunction (Tagged< Object > object) [static]
Definition at line 3078 of file wasm-objects.cc.
                                                           {
  if (!IsJSFunction(object)) return false;
  Tagged<JSFunction> js_function = Cast<JSFunction>(object);
  return js_function->shared()->HasWasmJSFunctionData(
      GetCurrentIsolateForSandbox());
}
References v8::internal::GetCurrentIsolateForSandbox().
Referenced by v8::internal::WasmTableObject::GetFunctionTableEntry(), v8::internal::WasmExternalFunction::IsWasmExternalFunction(), v8::internal::wasm::JSToWasmObject(), v8::internal::RUNTIME_FUNCTION(), v8::internal::WasmTableObject::SetFunctionTableEntry(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblySuspendingImpl().
New()
DirectHandle< WasmJSFunction > v8::internal::WasmJSFunction::New (Isolate * isolate, const wasm::FunctionSig * sig, DirectHandle< JSReceiver > callable, wasm::Suspend suspend) [static]
Definition at line 3182 of file wasm-objects.cc.
                                                            {
  DCHECK_LE(sig->all().size(), kMaxInt);
  int parameter_count = static_cast<int>(sig->parameter_count());
  Factory* factory = isolate->factory();
  DirectHandle<Map> rtt;
  DirectHandle<NativeContext> context(isolate->native_context());
  static_assert(wasm::kMaxCanonicalTypes <= kMaxInt);
  // TODO(clemensb): Merge the next two lines into a single call.
  wasm::CanonicalTypeIndex sig_id =
      wasm::GetTypeCanonicalizer()->AddRecursiveGroup(sig);
  const wasm::CanonicalSig* canonical_sig =
      wasm::GetTypeCanonicalizer()->LookupFunctionSignature(sig_id);
  wasm::TypeCanonicalizer::PrepareForCanonicalTypeId(isolate, sig_id);
  DirectHandle<WeakFixedArray> canonical_rtts(
      isolate->heap()->wasm_canonical_rtts(), isolate);
  Tagged<MaybeObject> maybe_canonical_map = canonical_rtts->get(sig_id.index);
  if (!maybe_canonical_map.IsCleared()) {
    rtt = direct_handle(
        Cast<Map>(maybe_canonical_map.GetHeapObjectAssumeWeak()), isolate);
  } else {
    rtt = CreateFuncRefMap(isolate, sig_id, DirectHandle<Map>(), false);
    canonical_rtts->set(sig_id.index, MakeWeak(*rtt));
  }
  int expected_arity = parameter_count;
  wasm::ImportCallKind kind;
  if (IsJSFunction(*callable)) {
    Tagged<SharedFunctionInfo> shared = Cast<JSFunction>(callable)->shared();
    if (shared->HasWasmFunctionData(isolate)) {
      kind = wasm::ImportCallKind::kUseCallBuiltin;
    } else {
      expected_arity =
          shared->internal_formal_parameter_count_without_receiver();
      kind = wasm::ImportCallKind::kJSFunction;
    }
  } else {
    kind = wasm::ImportCallKind::kUseCallBuiltin;
  }
  wasm::WasmImportWrapperCache* cache = wasm::GetWasmImportWrapperCache();
  // Initialize the import wrapper cache if that hasn't happened yet.
  cache->LazyInitialize(isolate);
  std::shared_ptr<wasm::WasmImportWrapperHandle> wrapper_handle =
      cache->Get(isolate, kind, sig_id, expected_arity, suspend, canonical_sig);
  bool should_clear_call_origin = wrapper_handle->has_code();
  DirectHandle<Code> js_to_js_wrapper_code =
      wasm::IsJSCompatibleSignature(canonical_sig)
          ? isolate->builtins()->code_handle(Builtin::kJSToJSWrapper)
          : isolate->builtins()->code_handle(Builtin::kJSToJSWrapperInvalidSig);
  DirectHandle<WasmJSFunctionData> function_data =
      factory->NewWasmJSFunctionData(sig_id, callable, js_to_js_wrapper_code,
                                     rtt, suspend, wasm::kNoPromise,
                                     wrapper_handle);
  DirectHandle<WasmInternalFunction> internal_function{
      function_data->internal(), isolate};
  // Some later DCHECKs assume that we don't have a {call_origin} when
  // the function already uses a compiled wrapper.
  if (should_clear_call_origin) {
    Cast<WasmImportData>(internal_function->implicit_arg())
        ->clear_call_origin();
  }
  DirectHandle<String> name = factory->Function_string();
  if (IsJSFunction(*callable)) {
    name = JSFunction::GetDebugName(isolate, Cast<JSFunction>(callable));
    name = String::Flatten(isolate, name);
  }
  DirectHandle<SharedFunctionInfo> shared =
      factory->NewSharedFunctionInfoForWasmJSFunction(name, function_data);
  shared->set_internal_formal_parameter_count(
      JSParameterCount(parameter_count));
  DirectHandle<JSFunction> js_function =
      Factory::JSFunctionBuilder{isolate, shared, context}
          .set_map(isolate->wasm_exported_function_map())
          .Build();
  internal_function->set_external(*js_function);
  return Cast<WasmJSFunction>(js_function);
}
References v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::Isolate::builtins(), v8::internal::Builtins::code_handle(), v8::internal::JSFunction::context(), v8::internal::CreateFuncRefMap(), DCHECK_LE, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmImportWrapperCache::Get(), v8::internal::JSFunction::GetDebugName(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::Isolate::heap(), v8::internal::wasm::TypeIndex::index, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::wasm::IsJSCompatibleSignature(), v8::internal::JSParameterCount(), v8::internal::wasm::kJSFunction, v8::internal::wasm::kMaxCanonicalTypes, v8::internal::kMaxInt, v8::internal::wasm::kNoPromise, v8::internal::wasm::kUseCallBuiltin, v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), v8::internal::MakeWeak(), v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::wasm::TypeCanonicalizer::PrepareForCanonicalTypeId(), and v8::internal::sig.
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction().
OBJECT_CONSTRUCTORS()
v8::internal::WasmJSFunction::OBJECT_CONSTRUCTORS (WasmJSFunction , JSFunction)
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc