v8::internal::FuncNameInferrer Class Reference
#include <func-name-inferrer.h>
Classes
struct Name
class State
Public Member Functions
FuncNameInferrer (AstValueFactory *ast_value_factory)
FuncNameInferrer (const FuncNameInferrer &)=delete
FuncNameInferrer & operator= (const FuncNameInferrer &)=delete
bool IsOpen () const
void PushEnclosingName (const AstRawString *name)
void PushLiteralName (const AstRawString *name)
void PushVariableName (const AstRawString *name)
void AddFunction (FunctionLiteral *func_to_infer)
void RemoveLastFunction ()
void RemoveAsyncKeywordFromEnd ()
void Infer ()
Private Types
enum NameType : uint8_t { kEnclosingConstructorName
, kLiteralName
, kVariableName
 }
Private Member Functions
AstConsString * MakeNameFromStack ()
void InferFunctionsNames ()
Private Attributes
AstValueFactory * ast_value_factory_
base::SmallVector< Name, 8 > names_stack_
std::vector< FunctionLiteral * > funcs_to_infer_
size_t scope_depth_ = 0
Detailed Description
Definition at line 45 of file func-name-inferrer.h.
Member Enumeration Documentation
NameType
enum v8::internal::FuncNameInferrer::NameType : uint8_t [private]
Enumerator
kEnclosingConstructorName
kLiteralName
kVariableName
Definition at line 104 of file func-name-inferrer.h.
                : uint8_t {
    kEnclosingConstructorName,
    kLiteralName,
    kVariableName
  };
Constructor & Destructor Documentation
FuncNameInferrer() [1/2]
v8::internal::FuncNameInferrer::FuncNameInferrer (AstValueFactory * ast_value_factory) [explicit]
Definition at line 14 of file func-name-inferrer.cc.
    : ast_value_factory_(ast_value_factory) {}
FuncNameInferrer() [2/2]
v8::internal::FuncNameInferrer::FuncNameInferrer (const FuncNameInferrer &) [delete]
Member Function Documentation
AddFunction()
void v8::internal::FuncNameInferrer::AddFunction (FunctionLiteral * func_to_infer) [inline]
Definition at line 85 of file func-name-inferrer.h.
                                                   {
    if (IsOpen()) {
      funcs_to_infer_.push_back(func_to_infer);
    }
  }
References funcs_to_infer_, and IsOpen().
Infer()
void v8::internal::FuncNameInferrer::Infer () [inline]
Definition at line 98 of file func-name-inferrer.h.
               {
    DCHECK(IsOpen());
    if (!funcs_to_infer_.empty()) InferFunctionsNames();
  }
References v8::internal::DCHECK(), funcs_to_infer_, InferFunctionsNames(), and IsOpen().
InferFunctionsNames()
void v8::internal::FuncNameInferrer::InferFunctionsNames () [private]
Definition at line 72 of file func-name-inferrer.cc.
                                           {
  AstConsString* func_name = MakeNameFromStack();
  for (FunctionLiteral* func : funcs_to_infer_) {
    func->set_raw_inferred_name(func_name);
  }
  funcs_to_infer_.resize(0);
}
References funcs_to_infer_, and MakeNameFromStack().
Referenced by Infer().
IsOpen()
bool v8::internal::FuncNameInferrer::IsOpen () const [inline]
Definition at line 74 of file func-name-inferrer.h.
{ return scope_depth_ > 0; }
References scope_depth_.
Referenced by AddFunction(), Infer(), PushLiteralName(), PushVariableName(), RemoveAsyncKeywordFromEnd(), RemoveLastFunction(), and v8::internal::FuncNameInferrer::State::~State().
MakeNameFromStack()
AstConsString * v8::internal::FuncNameInferrer::MakeNameFromStack () [private]
Definition at line 48 of file func-name-inferrer.cc.
                                                   {
  if (names_stack_.empty()) {
    return ast_value_factory_->empty_cons_string();
  }
  AstConsString* result = ast_value_factory_->NewConsString();
  auto it = names_stack_.begin();
  while (it != names_stack_.end()) {
    // Advance the iterator to be able to peek the next value.
    auto current = it++;
    // Skip consecutive variable declarations.
    if (it != names_stack_.end() && current->type() == kVariableName &&
        it->type() == kVariableName) {
      continue;
    }
    // Add name. Separate names with ".".
    Zone* zone = ast_value_factory_->single_parse_zone();
    if (!result->IsEmpty()) {
      result->AddString(zone, ast_value_factory_->dot_string());
    }
    result->AddString(zone, current->name());
  }
  return result;
}
References ast_value_factory_, v8::internal::AstValueFactory::empty_cons_string(), kVariableName, v8::internal::Zone::name(), names_stack_, v8::internal::AstValueFactory::NewConsString(), v8::base::internal::result, and v8::internal::AstValueFactory::single_parse_zone().
Referenced by InferFunctionsNames().
operator=()
FuncNameInferrer& v8::internal::FuncNameInferrer::operator= (const FuncNameInferrer &) [delete]
PushEnclosingName()
void v8::internal::FuncNameInferrer::PushEnclosingName (const AstRawString * name)
Definition at line 17 of file func-name-inferrer.cc.
                                                                 {
  // Enclosing name is a name of a constructor function. To check
  // that it is really a constructor, we check that it is not empty
  // and starts with a capital letter.
  if (!name->IsEmpty() && unibrow::Uppercase::Is(name->FirstCharacter())) {
    names_stack_.push_back(Name(name, kEnclosingConstructorName));
  }
}
References unibrow::Uppercase::Is(), kEnclosingConstructorName, v8::internal::name, and names_stack_.
PushLiteralName()
void v8::internal::FuncNameInferrer::PushLiteralName (const AstRawString * name)
Definition at line 27 of file func-name-inferrer.cc.
                                                               {
  if (IsOpen() && name != ast_value_factory_->prototype_string()) {
    names_stack_.push_back(Name(name, kLiteralName));
  }
}
References ast_value_factory_, IsOpen(), kLiteralName, v8::internal::name, and names_stack_.
PushVariableName()
void v8::internal::FuncNameInferrer::PushVariableName (const AstRawString * name)
Definition at line 34 of file func-name-inferrer.cc.
                                                                {
  if (IsOpen() && name != ast_value_factory_->dot_result_string()) {
    names_stack_.push_back(Name(name, kVariableName));
  }
}
References ast_value_factory_, IsOpen(), kVariableName, v8::internal::name, and names_stack_.
RemoveAsyncKeywordFromEnd()
void v8::internal::FuncNameInferrer::RemoveAsyncKeywordFromEnd ()
Definition at line 40 of file func-name-inferrer.cc.
                                                 {
  if (IsOpen()) {
    CHECK_GT(names_stack_.size(), 0);
    CHECK(names_stack_.back().name()->IsOneByteEqualTo("async"));
    names_stack_.pop_back();
  }
}
References CHECK, CHECK_GT, IsOpen(), and names_stack_.
RemoveLastFunction()
void v8::internal::FuncNameInferrer::RemoveLastFunction () [inline]
Definition at line 91 of file func-name-inferrer.h.
                            {
    if (IsOpen() && !funcs_to_infer_.empty()) funcs_to_infer_.pop_back();
  }
References funcs_to_infer_, and IsOpen().
Member Data Documentation
ast_value_factory_
AstValueFactory* v8::internal::FuncNameInferrer::ast_value_factory_ [private]
Definition at line 128 of file func-name-inferrer.h.
Referenced by MakeNameFromStack(), PushLiteralName(), and PushVariableName().
funcs_to_infer_
std::vector<FunctionLiteral*> v8::internal::FuncNameInferrer::funcs_to_infer_ [private]
Definition at line 130 of file func-name-inferrer.h.
Referenced by AddFunction(), Infer(), InferFunctionsNames(), and RemoveLastFunction().
names_stack_
base::SmallVector<Name, 8> v8::internal::FuncNameInferrer::names_stack_ [private]
Definition at line 129 of file func-name-inferrer.h.
Referenced by MakeNameFromStack(), PushEnclosingName(), PushLiteralName(), PushVariableName(), RemoveAsyncKeywordFromEnd(), and v8::internal::FuncNameInferrer::State::~State().
scope_depth_
size_t v8::internal::FuncNameInferrer::scope_depth_ = 0 [private]
Definition at line 131 of file func-name-inferrer.h.
Referenced by IsOpen(), v8::internal::FuncNameInferrer::State::State(), and v8::internal::FuncNameInferrer::State::~State().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/func-name-inferrer.h
/mnt/V8SourceCode/src/parsing/func-name-inferrer.cc