v8::internal::IndirectPointerWriteBarrierDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::TaggedPointer(), MachineType::Pointer(), MachineType::Uint64()) static const expr auto registers()
Static Public Member Functions
static constexpr Register ObjectRegister ()
static constexpr Register SlotAddressRegister ()
static constexpr Register IndirectPointerTagRegister ()
static constexpr RegList ComputeSavedRegisters (Register object, Register slot_address=no_reg)
Static Public Attributes
static constexpr bool kRestrictAllocatableRegisters = true
static constexpr bool kCalleeSaveRegisters = true
Additional Inherited Members
Detailed Description
Definition at line 1588 of file interface-descriptors.h.
Member Function Documentation
ComputeSavedRegisters()
constexpr RegList v8::internal::IndirectPointerWriteBarrierDescriptor::ComputeSavedRegisters (Register object, Register slot_address = no_reg) [inline], [static], [constexpr]
Definition at line 353 of file interface-descriptors-inl.h.
                                            {
  DCHECK(!AreAliased(object, slot_address));
  // This write barrier behaves identical to the generic one, except that it
  // passes one additional parameter.
  RegList saved_registers =
      WriteBarrierDescriptor::ComputeSavedRegisters(object, slot_address);
  saved_registers.set(IndirectPointerTagRegister());
  return saved_registers;
}
References v8::internal::AreAliased(), v8::internal::WriteBarrierDescriptor::ComputeSavedRegisters(), v8::internal::DCHECK(), IndirectPointerTagRegister(), and v8::internal::RegListBase< RegisterT >::set().
Referenced by v8::internal::MacroAssembler::CallIndirectPointerBarrier().
DEFINE_PARAMETER_TYPES()
v8::internal::IndirectPointerWriteBarrierDescriptor::DEFINE_PARAMETER_TYPES (MachineType::TaggedPointer() , MachineType::Pointer() , MachineType::Uint64()) const
IndirectPointerTagRegister()
constexpr Register v8::internal::IndirectPointerWriteBarrierDescriptor::IndirectPointerTagRegister () [inline], [static], [constexpr]
Definition at line 348 of file interface-descriptors-inl.h.
                                                                  {
  return std::get<kIndirectPointerTag>(registers());
}
References v8::internal::StaticCallInterfaceDescriptor< IndirectPointerWriteBarrierDescriptor >::registers().
Referenced by v8::internal::MacroAssembler::CallIndirectPointerBarrier(), and ComputeSavedRegisters().
ObjectRegister()
constexpr Register v8::internal::IndirectPointerWriteBarrierDescriptor::ObjectRegister () [inline], [static], [constexpr]
Definition at line 338 of file interface-descriptors-inl.h.
                                                                         {
  return std::get<kObject>(registers());
}
References v8::internal::StaticCallInterfaceDescriptor< IndirectPointerWriteBarrierDescriptor >::registers().
Referenced by v8::internal::MacroAssembler::CallIndirectPointerBarrier().
SlotAddressRegister()
constexpr Register v8::internal::IndirectPointerWriteBarrierDescriptor::SlotAddressRegister () [inline], [static], [constexpr]
Definition at line 343 of file interface-descriptors-inl.h.
                                                           {
  return std::get<kSlotAddress>(registers());
}
References v8::internal::StaticCallInterfaceDescriptor< IndirectPointerWriteBarrierDescriptor >::registers().
Referenced by v8::internal::MacroAssembler::CallIndirectPointerBarrier().
Member Data Documentation
kCalleeSaveRegisters
constexpr bool v8::internal::IndirectPointerWriteBarrierDescriptor::kCalleeSaveRegisters = true [static], [constexpr]
Definition at line 1602 of file interface-descriptors.h.
kRestrictAllocatableRegisters
constexpr bool v8::internal::IndirectPointerWriteBarrierDescriptor::kRestrictAllocatableRegisters = true [static], [constexpr]
Definition at line 1601 of file interface-descriptors.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h