v8::internal::compiler::GraphReducer Class Reference
#include <graph-reducer.h>
Classes
struct NodeState
Public Types
enum class State : uint8_t { kUnvisited
, kRevisit
, kOnStack
, kVisited
 }
Public Member Functions
GraphReducer (Zone *zone, TFGraph *graph, TickCounter *tick_counter, JSHeapBroker *broker, Node *dead=nullptr, ObserveNodeManager *observe_node_manager=nullptr)
~GraphReducer () override
GraphReducer (const GraphReducer &)=delete
GraphReducer & operator= (const GraphReducer &)=delete
TFGraph * graph () const
void AddReducer (Reducer *reducer)
void ReduceNode (Node *const)
void ReduceGraph ()
Private Member Functions
Reduction Reduce (Node *const)
void ReduceTop ()
void Replace (Node *node, Node *replacement) final
void ReplaceWithValue (Node *node, Node *value, Node *effect, Node *control) final
void Replace (Node *node, Node *replacement, NodeId max_id) final
void Pop ()
void Push (Node *node)
bool Recurse (Node *node)
void Revisit (Node *node) final
Private Attributes
TFGraph *const graph_
Node *const dead_
NodeMarker< State > state_
ZoneVector< Reducer * > reducers_
ZoneQueue< Node * > revisit_
ZoneStack< NodeState > stack_
TickCounter *const tick_counter_
JSHeapBroker *const broker_
ObserveNodeManager *const observe_node_manager_
Detailed Description
Definition at line 150 of file graph-reducer.h.
Member Enumeration Documentation
State
enum v8::internal::compiler::GraphReducer::State : uint8_t [strong]
Enumerator
kUnvisited
kRevisit
kOnStack
kVisited
Definition at line 22 of file graph-reducer.cc.
                             : uint8_t {
  kUnvisited,
  kRevisit,
  kOnStack,
  kVisited
};
Constructor & Destructor Documentation
GraphReducer() [1/2]
v8::internal::compiler::GraphReducer::GraphReducer (Zone * zone, TFGraph * graph, TickCounter * tick_counter, JSHeapBroker * broker, Node * dead = nullptr, ObserveNodeManager * observe_node_manager = nullptr)
Definition at line 42 of file graph-reducer.cc.
    : graph_(graph),
      dead_(dead),
      state_(graph, 4),
      reducers_(zone),
      revisit_(zone),
      stack_(zone),
      tick_counter_(tick_counter),
      broker_(broker),
      observe_node_manager_(observe_node_manager) {
  if (dead != nullptr) {
    NodeProperties::SetType(dead_, Type::None());
  }
}
References dead_, v8::internal::compiler::turboshaft::Type::None(), and v8::internal::compiler::NodeProperties::SetType().
 GraphReducer()
v8::internal::compiler::GraphReducer::~GraphReducer () [override], [default]
GraphReducer() [2/2]
v8::internal::compiler::GraphReducer::GraphReducer (const GraphReducer &) [delete]
Member Function Documentation
AddReducer()
void v8::internal::compiler::GraphReducer::AddReducer (Reducer * reducer)
Definition at line 62 of file graph-reducer.cc.
                                              {
  reducers_.push_back(reducer);
}
References reducers_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer().
graph()
TFGraph* v8::internal::compiler::GraphReducer::graph () const [inline]
Definition at line 161 of file graph-reducer.h.
{ return graph_; }
Referenced by ReduceGraph(), ReduceTop(), Replace(), v8::internal::compiler::InliningPhase::Run(), v8::internal::compiler::TypedLoweringPhase::Run(), v8::internal::compiler::EarlyOptimizationPhase::Run(), and v8::internal::compiler::LoadEliminationPhase::Run().
operator=()
GraphReducer& v8::internal::compiler::GraphReducer::operator= (const GraphReducer &) [delete]
Pop()
void v8::internal::compiler::GraphReducer::Pop () [private]
Definition at line 289 of file graph-reducer.cc.
                       {
  Node* node = stack_.top().node;
  state_.Set(node, State::kVisited);
  stack_.pop();
}
References kVisited, stack_, and state_.
Referenced by ReduceTop().
Push()
void v8::internal::compiler::GraphReducer::Push (Node * node) [private]
Definition at line 296 of file graph-reducer.cc.
                                        {
  DCHECK_NE(State::kOnStack, state_.Get(node));
  state_.Set(node, State::kOnStack);
  stack_.push({node, 0});
}
References DCHECK_NE, kOnStack, stack_, and state_.
Referenced by Recurse(), and ReduceNode().
Recurse()
bool v8::internal::compiler::GraphReducer::Recurse (Node * node) [private]
Definition at line 303 of file graph-reducer.cc.
                                     {
  if (state_.Get(node) > State::kRevisit) return false;
  Push(node);
  return true;
}
References kRevisit, Push(), and state_.
Referenced by ReduceTop(), and Replace().
Reduce()
Reduction v8::internal::compiler::GraphReducer::Reduce (Node * const node) [private]
Definition at line 100 of file graph-reducer.cc.
                                               {
  auto skip = reducers_.end();
  for (auto i = reducers_.begin(); i != reducers_.end();) {
    if (i != skip) {
      tick_counter_->TickAndMaybeEnterSafepoint();
      Reduction reduction = (*i)->Reduce(node, observe_node_manager_);
      if (!reduction.Changed()) {
        // No change from this reducer.
      } else if (reduction.replacement() == node) {
        // {replacement} == {node} represents an in-place reduction. Rerun
        // all the other reducers for this node, as now there may be more
        // opportunities for reduction.
        if (v8_flags.trace_turbo_reduction) {
          UnparkedScopeIfNeeded unparked(broker_);
          // TODO(neis): Disallow racy handle dereference once we stop
          // supporting --no-local-heaps --no-concurrent-inlining.
          AllowHandleDereference allow_deref;
          StdoutStream{} << "- In-place update of #" << *node << " by reducer "
                         << (*i)->reducer_name() << std::endl;
        }
        skip = i;
        i = reducers_.begin();
        continue;
      } else {
        // {node} was replaced by another node.
        if (v8_flags.trace_turbo_reduction) {
          UnparkedScopeIfNeeded unparked(broker_);
          // TODO(neis): Disallow racy handle dereference once we stop
          // supporting --no-local-heaps --no-concurrent-inlining.
          AllowHandleDereference allow_deref;
          StdoutStream{} << "- Replacement of #" << *node << " with #"
                         << *(reduction.replacement()) << " by reducer "
                         << (*i)->reducer_name() << std::endl;
        }
        return reduction;
      }
    }
    ++i;
  }
  if (skip == reducers_.end()) {
    // No change from any reducer.
    return Reducer::NoChange();
  }
  // At least one reducer did some in-place reduction.
  return Reducer::Changed(node);
}
References broker_, v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::Reducer::Changed(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Reducer::NoChange(), observe_node_manager_, reducers_, v8::internal::compiler::Reduction::replacement(), tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), and v8::internal::v8_flags.
Referenced by ReduceTop().
ReduceGraph()
void v8::internal::compiler::GraphReducer::ReduceGraph ()
Definition at line 97 of file graph-reducer.cc.
{ ReduceNode(graph()->end()); }
References v8::internal::compiler::end(), graph(), and ReduceNode().
Referenced by v8::internal::compiler::InliningPhase::Run(), v8::internal::compiler::UntyperPhase::Run(), v8::internal::compiler::TypedLoweringPhase::Run(), v8::internal::compiler::EscapeAnalysisPhase::Run(), v8::internal::compiler::GenericLoweringPhase::Run(), v8::internal::compiler::EarlyOptimizationPhase::Run(), and v8::internal::compiler::LoadEliminationPhase::Run().
ReduceNode()
void v8::internal::compiler::GraphReducer::ReduceNode (Node * const node)
Definition at line 67 of file graph-reducer.cc.
                                        {
  DCHECK(stack_.empty());
  DCHECK(revisit_.empty());
  Push(node);
  for (;;) {
    if (!stack_.empty()) {
      // Process the node on the top of the stack, potentially pushing more or
      // popping the node off the stack.
      ReduceTop();
    } else if (!revisit_.empty()) {
      // If the stack becomes empty, revisit any nodes in the revisit queue.
      node = revisit_.front();
      revisit_.pop();
      if (state_.Get(node) == State::kRevisit) {
        // state can change while in queue.
        Push(node);
      }
    } else {
      // Run all finalizers.
      for (Reducer* const reducer : reducers_) reducer->Finalize();
      // Check if we have new nodes to revisit.
      if (revisit_.empty()) break;
    }
  }
  DCHECK(revisit_.empty());
  DCHECK(stack_.empty());
}
References v8::internal::DCHECK(), kRevisit, Push(), reducers_, ReduceTop(), revisit_, stack_, and state_.
Referenced by ReduceGraph().
ReduceTop()
void v8::internal::compiler::GraphReducer::ReduceTop () [private]
Definition at line 148 of file graph-reducer.cc.
                             {
  NodeState& entry = stack_.top();
  Node* node = entry.node;
  DCHECK_EQ(State::kOnStack, state_.Get(node));
  if (node->IsDead()) return Pop(); // Node was killed while on stack.
  Node::Inputs node_inputs = node->inputs();
  // Recurse on an input if necessary.
  int start = entry.input_index < node_inputs.count() ? entry.input_index : 0;
  for (int i = start; i < node_inputs.count(); ++i) {
    Node* input = node_inputs[i];
    if (input != node && Recurse(input)) {
      entry.input_index = i + 1;
      return;
    }
  }
  for (int i = 0; i < start; ++i) {
    Node* input = node_inputs[i];
    if (input != node && Recurse(input)) {
      entry.input_index = i + 1;
      return;
    }
  }
  // Remember the max node id before reduction.
  NodeId const max_id = static_cast<NodeId>(graph()->NodeCount() - 1);
  // All inputs should be visited or on stack. Apply reductions to node.
  Reduction reduction = Reduce(node);
  // If there was no reduction, pop {node} and continue.
  if (!reduction.Changed()) return Pop();
  // Check if the reduction is an in-place update of the {node}.
  Node* const replacement = reduction.replacement();
  if (replacement == node) {
    for (Node* const user : node->uses()) {
      DCHECK_IMPLIES(user == node, state_.Get(node) != State::kVisited);
      Revisit(user);
    }
    // In-place update of {node}, may need to recurse on an input.
    node_inputs = node->inputs();
    for (int i = 0; i < node_inputs.count(); ++i) {
      Node* input = node_inputs[i];
      if (input != node && Recurse(input)) {
        entry.input_index = i + 1;
        return;
      }
    }
  }
  // After reducing the node, pop it off the stack.
  Pop();
  // Check if we have a new replacement.
  if (replacement != node) {
    Replace(node, replacement, max_id);
  }
}
References v8::internal::compiler::Reduction::Changed(), DCHECK_EQ, DCHECK_IMPLIES, graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::GraphReducer::NodeState::input_index, v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::Inputs(), v8::internal::compiler::Node::IsDead(), kOnStack, kVisited, v8::internal::compiler::GraphReducer::NodeState::node, v8::internal::compiler::TFGraph::NodeCount(), Pop(), Recurse(), Reduce(), Replace(), v8::internal::compiler::Reduction::replacement(), Revisit(), stack_, state_, and v8::internal::compiler::Node::uses().
Referenced by ReduceNode().
Replace() [1/2]
void v8::internal::compiler::GraphReducer::Replace (Node * node, Node * replacement) [final], [private]
Definition at line 212 of file graph-reducer.cc.
                                                        {
  Replace(node, replacement, std::numeric_limits<NodeId>::max());
}
Referenced by ReduceTop(), and ReplaceWithValue().
Replace() [2/2]
void v8::internal::compiler::GraphReducer::Replace (Node * node, Node * replacement, NodeId max_id) [final], [private]
Definition at line 217 of file graph-reducer.cc.
                                                                       {
  if (node == graph()->start()) graph()->SetStart(replacement);
  if (node == graph()->end()) graph()->SetEnd(replacement);
  if (replacement->id() <= max_id) {
    // {replacement} is an old node, so unlink {node} and assume that
    // {replacement} was already reduced and finish.
    for (Edge edge : node->use_edges()) {
      Node* const user = edge.from();
      Verifier::VerifyEdgeInputReplacement(edge, replacement);
      edge.UpdateTo(replacement);
      // Don't revisit this node if it refers to itself.
      if (user != node) Revisit(user);
    }
    node->Kill();
  } else {
    // Replace all old uses of {node} with {replacement}, but allow new nodes
    // created by this reduction to use {node}.
    for (Edge edge : node->use_edges()) {
      Node* const user = edge.from();
      if (user->id() <= max_id) {
        edge.UpdateTo(replacement);
        // Don't revisit this node if it refers to itself.
        if (user != node) Revisit(user);
      }
    }
    // Unlink {node} if it's no longer used.
    if (node->uses().empty()) node->Kill();
    // If there was a replacement, reduce it after popping {node}.
    Recurse(replacement);
  }
}
References v8::internal::compiler::Node::Uses::empty(), v8::internal::compiler::end(), graph(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::Kill(), Recurse(), Revisit(), v8::internal::compiler::TFGraph::SetEnd(), v8::internal::compiler::TFGraph::SetStart(), v8::internal::compiler::Node::use_edges(), v8::internal::compiler::Node::uses(), and v8::internal::compiler::Verifier::VerifyEdgeInputReplacement().
ReplaceWithValue()
void v8::internal::compiler::GraphReducer::ReplaceWithValue (Node * node, Node * value, Node * effect, Node * control) [final], [private]
Definition at line 251 of file graph-reducer.cc.
                                                   {
  if (effect == nullptr && node->op()->EffectInputCount() > 0) {
    effect = NodeProperties::GetEffectInput(node);
  }
  if (control == nullptr && node->op()->ControlInputCount() > 0) {
    control = NodeProperties::GetControlInput(node);
  }
  // Requires distinguishing between value, effect and control edges.
  for (Edge edge : node->use_edges()) {
    Node* const user = edge.from();
    DCHECK(!user->IsDead());
    if (NodeProperties::IsControlEdge(edge)) {
      if (user->opcode() == IrOpcode::kIfSuccess) {
        Replace(user, control);
      } else if (user->opcode() == IrOpcode::kIfException) {
        DCHECK_NOT_NULL(dead_);
        edge.UpdateTo(dead_);
        Revisit(user);
      } else {
        DCHECK_NOT_NULL(control);
        edge.UpdateTo(control);
        Revisit(user);
      }
    } else if (NodeProperties::IsEffectEdge(edge)) {
      DCHECK_NOT_NULL(effect);
      edge.UpdateTo(effect);
      Revisit(user);
    } else {
      DCHECK_NOT_NULL(value);
      edge.UpdateTo(value);
      Revisit(user);
    }
  }
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::DCHECK(), DCHECK_NOT_NULL, dead_, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::Node::IsDead(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), Replace(), Revisit(), v8::internal::compiler::Node::use_edges(), and v8::internal::value.
Revisit()
void v8::internal::compiler::GraphReducer::Revisit (Node * node) [final], [private]
Definition at line 310 of file graph-reducer.cc.
                                     {
  if (state_.Get(node) == State::kVisited) {
    state_.Set(node, State::kRevisit);
    revisit_.push(node);
  }
}
References kRevisit, kVisited, revisit_, and state_.
Referenced by ReduceTop(), Replace(), and ReplaceWithValue().
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::GraphReducer::broker_ [private]
Definition at line 211 of file graph-reducer.h.
Referenced by Reduce().
dead_
Node* const v8::internal::compiler::GraphReducer::dead_ [private]
Definition at line 205 of file graph-reducer.h.
Referenced by GraphReducer(), and ReplaceWithValue().
graph_
TFGraph* const v8::internal::compiler::GraphReducer::graph_ [private]
Definition at line 204 of file graph-reducer.h.
observe_node_manager_
ObserveNodeManager* const v8::internal::compiler::GraphReducer::observe_node_manager_ [private]
Definition at line 212 of file graph-reducer.h.
Referenced by Reduce().
reducers_
ZoneVector<Reducer*> v8::internal::compiler::GraphReducer::reducers_ [private]
Definition at line 207 of file graph-reducer.h.
Referenced by AddReducer(), Reduce(), and ReduceNode().
revisit_
ZoneQueue<Node*> v8::internal::compiler::GraphReducer::revisit_ [private]
Definition at line 208 of file graph-reducer.h.
Referenced by ReduceNode(), and Revisit().
stack_
ZoneStack<NodeState> v8::internal::compiler::GraphReducer::stack_ [private]
Definition at line 209 of file graph-reducer.h.
Referenced by Pop(), Push(), ReduceNode(), and ReduceTop().
state_
NodeMarker<State> v8::internal::compiler::GraphReducer::state_ [private]
Definition at line 206 of file graph-reducer.h.
Referenced by Pop(), Push(), Recurse(), ReduceNode(), ReduceTop(), and Revisit().
tick_counter_
TickCounter* const v8::internal::compiler::GraphReducer::tick_counter_ [private]
Definition at line 210 of file graph-reducer.h.
Referenced by Reduce().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/graph-reducer.h
/mnt/V8SourceCode/src/compiler/graph-reducer.cc