v8::internal::SourceRangeAstVisitor Class Reference
#include <source-range-ast-visitor.h>
Public Member Functions
SourceRangeAstVisitor (uintptr_t stack_limit, Expression *root, SourceRangeMap *source_range_map)
Private Member Functions
void VisitBlock (Block *stmt)
void VisitSwitchStatement (SwitchStatement *stmt)
void VisitFunctionLiteral (FunctionLiteral *expr)
bool VisitNode (AstNode *node)
void VisitTryCatchStatement (TryCatchStatement *stmt)
void VisitTryFinallyStatement (TryFinallyStatement *stmt)
void MaybeRemoveContinuationRange (Statement *last_statement)
void MaybeRemoveLastContinuationRange (ZonePtrList< Statement > *stmts)
void MaybeRemoveContinuationRangeOfAsyncReturn (TryCatchStatement *stmt)
Private Attributes
SourceRangeMap * source_range_map_ = nullptr
std::unordered_set< int > continuation_positions_
Friends
class AstTraversalVisitor< SourceRangeAstVisitor >
Additional Inherited Members
Detailed Description
Definition at line 27 of file source-range-ast-visitor.h.
Constructor & Destructor Documentation
SourceRangeAstVisitor()
v8::internal::SourceRangeAstVisitor::SourceRangeAstVisitor (uintptr_t stack_limit, Expression * root, SourceRangeMap * source_range_map)
Definition at line 12 of file source-range-ast-visitor.cc.
    : AstTraversalVisitor(stack_limit, root),
      source_range_map_(source_range_map) {}
Member Function Documentation
MaybeRemoveContinuationRange()
void v8::internal::SourceRangeAstVisitor::MaybeRemoveContinuationRange (Statement * last_statement) [private]
Definition at line 74 of file source-range-ast-visitor.cc.
                               {
  AstNodeSourceRanges* last_range = nullptr;
  if (last_statement->IsExpressionStatement() &&
      last_statement->AsExpressionStatement()->expression()->IsThrow()) {
    // For ThrowStatement, source range is tied to Throw expression not
    // ExpressionStatement.
    last_range = source_range_map_->Find(
        last_statement->AsExpressionStatement()->expression());
  } else {
    last_range = source_range_map_->Find(last_statement);
  }
  if (last_range == nullptr) return;
  if (last_range->HasRange(SourceRangeKind::kContinuation)) {
    last_range->RemoveContinuationRange();
  }
}
References v8::internal::SourceRangeMap::Find(), v8::internal::AstNodeSourceRanges::HasRange(), v8::internal::kContinuation, v8::internal::AstNodeSourceRanges::RemoveContinuationRange(), and source_range_map_.
Referenced by MaybeRemoveContinuationRangeOfAsyncReturn(), MaybeRemoveLastContinuationRange(), VisitTryCatchStatement(), and VisitTryFinallyStatement().
MaybeRemoveContinuationRangeOfAsyncReturn()
void v8::internal::SourceRangeAstVisitor::MaybeRemoveContinuationRangeOfAsyncReturn (TryCatchStatement * stmt) [private]
Definition at line 115 of file source-range-ast-visitor.cc.
                                       {
  // Detect try-catch inserted by NewTryCatchStatementForAsyncAwait in the
  // parser (issued for async functions, including async generators), and
  // remove the continuation range of the last statement, such that the
  // range of the enclosing function body is used.
  if (try_catch_stmt->is_try_catch_for_async()) {
    Statement* last_non_synthetic =
      FindLastNonSyntheticStatement(try_catch_stmt->try_block()->statements());
    if (last_non_synthetic) {
      MaybeRemoveContinuationRange(last_non_synthetic);
    }
  }
}
References v8::internal::anonymous_namespace{source-range-ast-visitor.cc}::FindLastNonSyntheticStatement(), v8::internal::TryCatchStatement::is_try_catch_for_async(), MaybeRemoveContinuationRange(), v8::internal::Block::statements(), and v8::internal::TryStatement::try_block().
Referenced by VisitTryCatchStatement().
MaybeRemoveLastContinuationRange()
void v8::internal::SourceRangeAstVisitor::MaybeRemoveLastContinuationRange (ZonePtrList< Statement > * stmts) [private]
Definition at line 95 of file source-range-ast-visitor.cc.
                                        {
  if (statements->is_empty()) return;
  MaybeRemoveContinuationRange(statements->last());
}
References v8::internal::ZoneList< T >::is_empty(), v8::internal::ZoneList< T >::last(), and MaybeRemoveContinuationRange().
Referenced by VisitBlock(), VisitFunctionLiteral(), and VisitSwitchStatement().
VisitBlock()
void v8::internal::SourceRangeAstVisitor::VisitBlock (Block * stmt) [private]
Definition at line 18 of file source-range-ast-visitor.cc.
                                                  {
  AstTraversalVisitor::VisitBlock(stmt);
  ZonePtrList<Statement>* stmts = stmt->statements();
  AstNodeSourceRanges* enclosingSourceRanges = source_range_map_->Find(stmt);
  if (enclosingSourceRanges != nullptr) {
    CHECK(enclosingSourceRanges->HasRange(SourceRangeKind::kContinuation));
    MaybeRemoveLastContinuationRange(stmts);
  }
}
References CHECK, v8::internal::SourceRangeMap::Find(), v8::internal::AstNodeSourceRanges::HasRange(), v8::internal::kContinuation, MaybeRemoveLastContinuationRange(), source_range_map_, and v8::internal::Block::statements().
VisitFunctionLiteral()
void v8::internal::SourceRangeAstVisitor::VisitFunctionLiteral (FunctionLiteral * expr) [private]
Definition at line 36 of file source-range-ast-visitor.cc.
                                                                      {
  AstTraversalVisitor::VisitFunctionLiteral(expr);
  ZonePtrList<Statement>* stmts = expr->body();
  MaybeRemoveLastContinuationRange(stmts);
}
References v8::internal::FunctionLiteral::body(), and MaybeRemoveLastContinuationRange().
VisitNode()
bool v8::internal::SourceRangeAstVisitor::VisitNode (AstNode * node) [private]
Definition at line 54 of file source-range-ast-visitor.cc.
                                                   {
  AstNodeSourceRanges* range = source_range_map_->Find(node);
  if (range == nullptr) return true;
  if (!range->HasRange(SourceRangeKind::kContinuation)) return true;
  // Called in pre-order. In case of conflicting continuation ranges, only the
  // outermost range may survive.
  SourceRange continuation = range->GetRange(SourceRangeKind::kContinuation);
  if (continuation_positions_.find(continuation.start) !=
      continuation_positions_.end()) {
    range->RemoveContinuationRange();
  } else {
    continuation_positions_.emplace(continuation.start);
  }
  return true;
}
References continuation_positions_, v8::internal::SourceRangeMap::Find(), v8::internal::AstNodeSourceRanges::GetRange(), v8::internal::AstNodeSourceRanges::HasRange(), v8::internal::kContinuation, v8::internal::AstNodeSourceRanges::RemoveContinuationRange(), source_range_map_, and v8::internal::SourceRange::start.
VisitSwitchStatement()
void v8::internal::SourceRangeAstVisitor::VisitSwitchStatement (SwitchStatement * stmt) [private]
Definition at line 28 of file source-range-ast-visitor.cc.
                                                                      {
  AstTraversalVisitor::VisitSwitchStatement(stmt);
  ZonePtrList<CaseClause>* clauses = stmt->cases();
  for (CaseClause* clause : *clauses) {
    MaybeRemoveLastContinuationRange(clause->statements());
  }
}
References v8::internal::SwitchStatement::cases(), and MaybeRemoveLastContinuationRange().
VisitTryCatchStatement()
void v8::internal::SourceRangeAstVisitor::VisitTryCatchStatement (TryCatchStatement * stmt) [private]
Definition at line 42 of file source-range-ast-visitor.cc.
                                                                          {
  AstTraversalVisitor::VisitTryCatchStatement(stmt);
  MaybeRemoveContinuationRange(stmt->try_block());
  MaybeRemoveContinuationRangeOfAsyncReturn(stmt);
}
References MaybeRemoveContinuationRange(), MaybeRemoveContinuationRangeOfAsyncReturn(), and v8::internal::TryStatement::try_block().
VisitTryFinallyStatement()
void v8::internal::SourceRangeAstVisitor::VisitTryFinallyStatement (TryFinallyStatement * stmt) [private]
Definition at line 48 of file source-range-ast-visitor.cc.
                               {
  AstTraversalVisitor::VisitTryFinallyStatement(stmt);
  MaybeRemoveContinuationRange(stmt->try_block());
}
References MaybeRemoveContinuationRange(), and v8::internal::TryStatement::try_block().
Friends And Related Function Documentation
AstTraversalVisitor< SourceRangeAstVisitor >
friend class AstTraversalVisitor< SourceRangeAstVisitor > [friend]
Definition at line 30 of file source-range-ast-visitor.h.
Member Data Documentation
continuation_positions_
std::unordered_set<int> v8::internal::SourceRangeAstVisitor::continuation_positions_ [private]
Definition at line 48 of file source-range-ast-visitor.h.
Referenced by VisitNode().
source_range_map_
SourceRangeMap* v8::internal::SourceRangeAstVisitor::source_range_map_ = nullptr [private]
Definition at line 47 of file source-range-ast-visitor.h.
Referenced by MaybeRemoveContinuationRange(), VisitBlock(), and VisitNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/source-range-ast-visitor.h
/mnt/V8SourceCode/src/ast/source-range-ast-visitor.cc