v8::WeakCallbackInfo< T > Class Template Reference
#include <v8-weak-callback-info.h>
Public Types
using Callback = void(*)(const WeakCallbackInfo< T > &data)
Public Member Functions
WeakCallbackInfo (Isolate *isolate, T *parameter, void *embedder_fields[kEmbedderFieldsInWeakCallback], Callback *callback)
Isolate * GetIsolate () const
T * GetParameter () const
void * GetInternalField (int index) const
void SetSecondPassCallback (Callback callback) const
When a weak callback is first invoked the embedders must Reset() the handle which triggered the callback.
Private Attributes
Isolate * isolate_
T * parameter_
Callback * callback_
void * embedder_fields_ [kEmbedderFieldsInWeakCallback]
Detailed Description
template<typename T>
class v8::WeakCallbackInfo< T >
Definition at line 25 of file v8-weak-callback-info.h.
Member Typedef Documentation
Callback
template<typename T >
using v8::WeakCallbackInfo< T >::Callback = void (*)(const WeakCallbackInfo<T>& data)
Definition at line 28 of file v8-weak-callback-info.h.
Constructor & Destructor Documentation
WeakCallbackInfo()
template<typename T >
v8::WeakCallbackInfo< T >::WeakCallbackInfo (Isolate * isolate, T * parameter, void * embedder_fields[kEmbedderFieldsInWeakCallback], Callback * callback) [inline]
Definition at line 30 of file v8-weak-callback-info.h.
      : isolate_(isolate), parameter_(parameter), callback_(callback) {
    memcpy(embedder_fields_, embedder_fields,
           sizeof(embedder_fields[0]) * kEmbedderFieldsInWeakCallback);
  }
References v8::WeakCallbackInfo< T >::embedder_fields_, and v8::kEmbedderFieldsInWeakCallback.
Member Function Documentation
GetInternalField()
template<class T >
void * v8::WeakCallbackInfo< T >::GetInternalField (int index) const [inline]
Definition at line 77 of file v8-weak-callback-info.h.
                                                           {
#ifdef V8_ENABLE_CHECKS
  if (index < 0 || index >= kEmbedderFieldsInWeakCallback) {
    api_internal::InternalFieldOutOfBounds(index);
  }
#endif
  return embedder_fields_[index];
}
References v8::internal::index, v8::api_internal::InternalFieldOutOfBounds(), and v8::kEmbedderFieldsInWeakCallback.
GetIsolate()
template<typename T >
Isolate* v8::WeakCallbackInfo< T >::GetIsolate () const [inline]
Definition at line 38 of file v8-weak-callback-info.h.
{ return isolate_; }
References v8::WeakCallbackInfo< T >::isolate_.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::cleanup(), v8::internal::anonymous_namespace{managed.cc}::ManagedObjectFinalizerSecondPass(), v8::internal::SamplingHeapProfiler::OnWeakCallback(), v8::internal::Isolate::RemoveContextIdCallback(), v8_inspector::InspectedContext::WeakCallbackData::resetContext(), and v8::PersistentValueMap< K, V, Traits >::WeakCallback().
GetParameter()
template<typename T >
T* v8::WeakCallbackInfo< T >::GetParameter () const [inline]
Definition at line 39 of file v8-weak-callback-info.h.
{ return parameter_; }
References v8::WeakCallbackInfo< T >::parameter_.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::cleanup(), v8_inspector::anonymous_namespace{v8-console.cc}::cleanupTaskInfo(), v8::internal::AllocationTracker::ScriptData::HandleWeakScript(), v8_inspector::V8DebuggerScript::MakeWeak(), v8::internal::ManagedObjectFinalizer(), v8::internal::anonymous_namespace{managed.cc}::ManagedObjectFinalizerSecondPass(), v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::NopFinalizer(), v8::internal::SamplingHeapProfiler::OnWeakCallback(), v8::internal::Isolate::RemoveContextIdCallback(), v8_inspector::InspectedContext::WeakCallbackData::resetContext(), and v8::PersistentValueMap< K, V, Traits >::WeakCallback().
SetSecondPassCallback()
template<typename T >
void v8::WeakCallbackInfo< T >::SetSecondPassCallback (Callback callback) const [inline]
When a weak callback is first invoked the embedders must Reset() the handle which triggered the callback.
The handle itself is unusable for anything else. No other V8 API calls may be called in the first callback. Additional work requires scheduling a second invocation via SetSecondPassCallback() which will be called some time after all the initial callbacks are processed.
The second pass callback is prohibited from executing JavaScript. Embedders should schedule another callback in case this is required.
Definition at line 53 of file v8-weak-callback-info.h.
{ *callback_ = callback; }
References v8::WeakCallbackInfo< T >::callback_.
Referenced by v8::internal::ManagedObjectFinalizer(), and v8::GlobalValueMap< K, V, Traits >::OnWeakCallback().
Member Data Documentation
callback_
template<typename T >
Callback* v8::WeakCallbackInfo< T >::callback_ [private]
Definition at line 58 of file v8-weak-callback-info.h.
Referenced by v8::WeakCallbackInfo< T >::SetSecondPassCallback().
embedder_fields_
template<typename T >
void* v8::WeakCallbackInfo< T >::embedder_fields_[kEmbedderFieldsInWeakCallback] [private]
Definition at line 59 of file v8-weak-callback-info.h.
Referenced by v8::WeakCallbackInfo< T >::WeakCallbackInfo().
isolate_
template<typename T >
Isolate* v8::WeakCallbackInfo< T >::isolate_ [private]
Definition at line 56 of file v8-weak-callback-info.h.
Referenced by v8::WeakCallbackInfo< T >::GetIsolate().
parameter_
template<typename T >
T* v8::WeakCallbackInfo< T >::parameter_ [private]
Definition at line 57 of file v8-weak-callback-info.h.
Referenced by v8::WeakCallbackInfo< T >::GetParameter().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-weak-callback-info.h