v8::internal::interpreter::BytecodeLoopHeader Class Reference
#include <bytecode-label.h>
Public Member Functions
BytecodeLoopHeader ()
size_t offset () const
Private Member Functions
void bind_to (size_t offset)
Private Attributes
size_t offset_
Static Private Attributes
static const size_t kInvalidOffset = static_cast<size_t>(-1)
Friends
class BytecodeArrayWriter
Detailed Description
Definition at line 21 of file bytecode-label.h.
Constructor & Destructor Documentation
BytecodeLoopHeader()
v8::internal::interpreter::BytecodeLoopHeader::BytecodeLoopHeader () [inline]
Definition at line 23 of file bytecode-label.h.
: offset_(kInvalidOffset) {}
Member Function Documentation
bind_to()
void v8::internal::interpreter::BytecodeLoopHeader::bind_to (size_t offset) [inline], [private]
Definition at line 33 of file bytecode-label.h.
                              {
    DCHECK_NE(offset, kInvalidOffset);
    DCHECK_EQ(offset_, kInvalidOffset);
    offset_ = offset;
  }
References DCHECK_EQ, and DCHECK_NE.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindLoopHeader().
offset()
size_t v8::internal::interpreter::BytecodeLoopHeader::offset () const [inline]
Definition at line 25 of file bytecode-label.h.
                        {
    DCHECK_NE(offset_, kInvalidOffset);
    return offset_;
  }
References DCHECK_NE.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop(), and v8::internal::interpreter::LoopBuilder::JumpToHeader().
Friends And Related Function Documentation
BytecodeArrayWriter
friend class BytecodeArrayWriter [friend]
Definition at line 42 of file bytecode-label.h.
Member Data Documentation
kInvalidOffset
const size_t v8::internal::interpreter::BytecodeLoopHeader::kInvalidOffset = static_cast<size_t>(-1) [static], [private]
Definition at line 31 of file bytecode-label.h.
offset_
size_t v8::internal::interpreter::BytecodeLoopHeader::offset_ [private]
Definition at line 40 of file bytecode-label.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-label.h