v8::internal::compiler::ConstraintBuilder Class Reference
#include <register-allocator.h>
Public Member Functions
ConstraintBuilder (RegisterAllocationData *data)
ConstraintBuilder (const ConstraintBuilder &)=delete
ConstraintBuilder & operator= (const ConstraintBuilder &)=delete
void MeetRegisterConstraints ()
void ResolvePhis ()
Private Member Functions
RegisterAllocationData * data () const
InstructionSequence * code () const
Zone * allocation_zone () const
InstructionOperand * AllocateFixed (UnallocatedOperand *operand, int pos, bool is_tagged, bool is_input, bool is_output)
void MeetRegisterConstraints (const InstructionBlock *block)
void MeetConstraintsBefore (int index)
void MeetConstraintsAfter (int index)
void MeetRegisterConstraintsForLastInstructionInBlock (const InstructionBlock *block)
void ResolvePhis (const InstructionBlock *block)
Private Attributes
RegisterAllocationData *const data_
Detailed Description
Definition at line 1335 of file register-allocator.h.
Constructor & Destructor Documentation
ConstraintBuilder() [1/2]
v8::internal::compiler::ConstraintBuilder::ConstraintBuilder (RegisterAllocationData * data) [explicit]
Definition at line 1482 of file register-allocator.cc.
    : data_(data) {}
ConstraintBuilder() [2/2]
v8::internal::compiler::ConstraintBuilder::ConstraintBuilder (const ConstraintBuilder &) [delete]
Member Function Documentation
AllocateFixed()
InstructionOperand * v8::internal::compiler::ConstraintBuilder::AllocateFixed (UnallocatedOperand * operand, int pos, bool is_tagged, bool is_input, bool is_output) [private]
Definition at line 1485 of file register-allocator.cc.
                    {
  TRACE("Allocating fixed reg for op %d\n", operand->virtual_register());
  DCHECK(operand->HasFixedPolicy());
  InstructionOperand allocated;
  MachineRepresentation rep = InstructionSequence::DefaultRepresentation();
  int virtual_register = operand->virtual_register();
  if (virtual_register != InstructionOperand::kInvalidVirtualRegister) {
    rep = data()->RepresentationFor(virtual_register);
  }
  if (operand->HasFixedSlotPolicy()) {
    allocated = AllocatedOperand(AllocatedOperand::STACK_SLOT, rep,
                                 operand->fixed_slot_index());
  } else if (operand->HasFixedRegisterPolicy()) {
    DCHECK(!IsFloatingPoint(rep));
    DCHECK_IMPLIES(is_input || is_output,
                   data()->config()->IsAllocatableGeneralCode(
                       operand->fixed_register_index()));
    allocated = AllocatedOperand(AllocatedOperand::REGISTER, rep,
                                 operand->fixed_register_index());
  } else if (operand->HasFixedFPRegisterPolicy()) {
    DCHECK(IsFloatingPoint(rep));
    DCHECK_NE(InstructionOperand::kInvalidVirtualRegister, virtual_register);
    if (rep == MachineRepresentation::kFloat16 ||
        rep == MachineRepresentation::kFloat32) {
      DCHECK_IMPLIES(is_input || is_output,
                     data()->config()->IsAllocatableFloatCode(
                         operand->fixed_register_index()));
    } else if (rep == MachineRepresentation::kFloat64) {
      DCHECK_IMPLIES(is_input || is_output,
                     data()->config()->IsAllocatableDoubleCode(
                         operand->fixed_register_index()));
    } else if (rep == MachineRepresentation::kSimd128) {
      DCHECK_IMPLIES(is_input || is_output,
                     data()->config()->IsAllocatableSimd128Code(
                         operand->fixed_register_index()));
#ifdef V8_TARGET_ARCH_X64
      // The ExtractF128 node with lane 0 to Simd128 maybe elided as alias to
      // the corresponding Simd256 ymm register on x64.
    } else if (rep == MachineRepresentation::kSimd256) {
      DCHECK_IMPLIES(is_input || is_output,
                     data()->config()->IsAllocatableSimd256Code(
                         operand->fixed_register_index()));
#endif
    } else {
      UNREACHABLE();
    }
    allocated = AllocatedOperand(AllocatedOperand::REGISTER, rep,
                                 operand->fixed_register_index());
  } else {
    UNREACHABLE();
  }
  if (is_input && allocated.IsAnyRegister()) {
    data()->MarkFixedUse(rep, operand->fixed_register_index());
  }
  InstructionOperand::ReplaceWith(operand, &allocated);
  if (is_tagged) {
    TRACE("Fixed reg is tagged at %d\n", pos);
    Instruction* instr = code()->InstructionAt(pos);
    if (instr->HasReferenceMap()) {
      instr->reference_map()->RecordReference(*AllocatedOperand::cast(operand));
    }
  }
  return operand;
}
References v8::internal::compiler::LocationOperand::cast(), code(), data(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NE, v8::internal::compiler::InstructionSequence::DefaultRepresentation(), v8::internal::compiler::UnallocatedOperand::fixed_register_index(), v8::internal::compiler::UnallocatedOperand::fixed_slot_index(), v8::internal::compiler::UnallocatedOperand::HasFixedFPRegisterPolicy(), v8::internal::compiler::UnallocatedOperand::HasFixedPolicy(), v8::internal::compiler::UnallocatedOperand::HasFixedRegisterPolicy(), v8::internal::compiler::UnallocatedOperand::HasFixedSlotPolicy(), v8::internal::compiler::Instruction::HasReferenceMap(), v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::IsFloatingPoint(), v8::internal::kFloat16, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::compiler::RegisterAllocationData::MarkFixedUse(), v8::internal::compiler::ReferenceMap::RecordReference(), v8::internal::compiler::Instruction::reference_map(), v8::internal::compiler::LocationOperand::REGISTER, v8::internal::compiler::InstructionOperand::ReplaceWith(), v8::internal::compiler::RegisterAllocationData::RepresentationFor(), v8::internal::compiler::LocationOperand::STACK_SLOT, v8::internal::TRACE(), v8::internal::UNREACHABLE(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by MeetConstraintsAfter(), MeetConstraintsBefore(), and MeetRegisterConstraintsForLastInstructionInBlock().
allocation_zone()
Zone* v8::internal::compiler::ConstraintBuilder::allocation_zone () const [inline], [private]
Definition at line 1351 of file register-allocator.h.
{ return data()->allocation_zone(); }
References v8::internal::compiler::RegisterAllocationData::allocation_zone(), and data().
Referenced by MeetConstraintsAfter(), MeetConstraintsBefore(), MeetRegisterConstraintsForLastInstructionInBlock(), and ResolvePhis().
code()
InstructionSequence* v8::internal::compiler::ConstraintBuilder::code () const [inline], [private]
Definition at line 1350 of file register-allocator.h.
{ return data()->code(); }
References v8::internal::compiler::RegisterAllocationData::code(), and data().
Referenced by AllocateFixed(), MeetConstraintsAfter(), MeetConstraintsBefore(), MeetRegisterConstraints(), MeetRegisterConstraintsForLastInstructionInBlock(), and ResolvePhis().
data()
RegisterAllocationData* v8::internal::compiler::ConstraintBuilder::data () const [inline], [private]
Definition at line 1349 of file register-allocator.h.
{ return data_; }
References data_.
Referenced by AllocateFixed(), allocation_zone(), code(), MeetConstraintsAfter(), MeetConstraintsBefore(), MeetRegisterConstraintsForLastInstructionInBlock(), and ResolvePhis().
MeetConstraintsAfter()
void v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter (int index) [private]
Definition at line 1617 of file register-allocator.cc.
                                                            {
  Instruction* first = code()->InstructionAt(instr_index);
  // Handle fixed temporaries.
  for (size_t i = 0; i < first->TempCount(); i++) {
    UnallocatedOperand* temp = UnallocatedOperand::cast(first->TempAt(i));
    if (temp->HasFixedPolicy())
      AllocateFixed(temp, instr_index, false, false, false);
  }
  // Handle constant/fixed output operands.
  for (size_t i = 0; i < first->OutputCount(); i++) {
    InstructionOperand* output = first->OutputAt(i);
    if (output->IsConstant()) {
      int output_vreg = ConstantOperand::cast(output)->virtual_register();
      TopLevelLiveRange* range = data()->GetLiveRangeFor(output_vreg);
      range->SetSpillStartIndex(instr_index + 1);
      range->SetSpillOperand(output);
      continue;
    }
    UnallocatedOperand* first_output = UnallocatedOperand::cast(output);
    TopLevelLiveRange* range =
        data()->GetLiveRangeFor(first_output->virtual_register());
    bool assigned = false;
    if (first_output->HasFixedPolicy()) {
      int output_vreg = first_output->virtual_register();
      UnallocatedOperand output_copy(UnallocatedOperand::REGISTER_OR_SLOT,
                                     output_vreg);
      bool is_tagged = code()->IsReference(output_vreg);
      if (first_output->HasSecondaryStorage()) {
        range->MarkHasPreassignedSlot();
        data()->preassigned_slot_ranges().push_back(
            std::make_pair(range, first_output->GetSecondaryStorage()));
      }
      AllocateFixed(first_output, instr_index, is_tagged, false, true);
      // This value is produced on the stack, we never need to spill it.
      if (first_output->IsStackSlot()) {
        DCHECK(LocationOperand::cast(first_output)->index() <
               data()->frame()->GetTotalFrameSlotCount());
        range->SetSpillOperand(LocationOperand::cast(first_output));
        range->SetSpillStartIndex(instr_index + 1);
        assigned = true;
      }
      data()->AddGapMove(instr_index + 1, Instruction::START, *first_output,
                         output_copy);
    }
    // Make sure we add a gap move for spilling (if we have not done
    // so already).
    if (!assigned) {
      range->RecordSpillLocation(allocation_zone(), instr_index + 1,
                                 first_output);
      range->SetSpillStartIndex(instr_index + 1);
    }
  }
}
References v8::internal::compiler::RegisterAllocationData::AddGapMove(), AllocateFixed(), allocation_zone(), v8::internal::compiler::LocationOperand::cast(), code(), data(), v8::internal::DCHECK(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::compiler::UnallocatedOperand::GetSecondaryStorage(), v8::internal::compiler::UnallocatedOperand::HasFixedPolicy(), v8::internal::compiler::UnallocatedOperand::HasSecondaryStorage(), v8::internal::index, v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::InstructionSequence::IsReference(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::TopLevelLiveRange::MarkHasPreassignedSlot(), v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), v8::internal::compiler::RegisterAllocationData::preassigned_slot_ranges(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::TopLevelLiveRange::RecordSpillLocation(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, v8::internal::compiler::TopLevelLiveRange::SetSpillOperand(), v8::internal::compiler::TopLevelLiveRange::SetSpillStartIndex(), v8::internal::compiler::Instruction::START, v8::internal::compiler::Instruction::TempAt(), v8::internal::compiler::Instruction::TempCount(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by MeetRegisterConstraints().
MeetConstraintsBefore()
void v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore (int index) [private]
Definition at line 1672 of file register-allocator.cc.
                                                             {
  Instruction* second = code()->InstructionAt(instr_index);
  // Handle fixed input operands of second instruction.
  ZoneVector<TopLevelLiveRange*>* spilled_consts = nullptr;
  for (size_t i = 0; i < second->InputCount(); i++) {
    InstructionOperand* input = second->InputAt(i);
    if (input->IsImmediate()) {
      continue; // Ignore immediates.
    }
    UnallocatedOperand* cur_input = UnallocatedOperand::cast(input);
    if (cur_input->HasSlotPolicy()) {
      TopLevelLiveRange* range =
          data()->GetLiveRangeFor(cur_input->virtual_register());
      if (range->HasSpillOperand() && range->GetSpillOperand()->IsConstant()) {
        bool already_spilled = false;
        if (spilled_consts == nullptr) {
          spilled_consts =
              allocation_zone()->New<ZoneVector<TopLevelLiveRange*>>(
                  allocation_zone());
        } else {
          auto it =
              std::find(spilled_consts->begin(), spilled_consts->end(), range);
          already_spilled = it != spilled_consts->end();
        }
        auto it = data()->slot_for_const_range().find(range);
        if (it == data()->slot_for_const_range().end()) {
          DCHECK(!already_spilled);
          int width = ByteWidthForStackSlot(range->representation());
          int index = data()->frame()->AllocateSpillSlot(width);
          auto* slot = AllocatedOperand::New(allocation_zone(),
                                             LocationOperand::STACK_SLOT,
                                             range->representation(), index);
          it = data()->slot_for_const_range().emplace(range, slot).first;
        }
        if (!already_spilled) {
          auto* slot = it->second;
          int input_vreg = cur_input->virtual_register();
          UnallocatedOperand input_copy(UnallocatedOperand::REGISTER_OR_SLOT,
                                        input_vreg);
          // Spill at every use position for simplicity, this case is very rare.
          data()->AddGapMove(instr_index, Instruction::END, input_copy, *slot);
          spilled_consts->push_back(range);
        }
      }
    }
    if (cur_input->HasFixedPolicy()) {
      int input_vreg = cur_input->virtual_register();
      UnallocatedOperand input_copy(UnallocatedOperand::REGISTER_OR_SLOT,
                                    input_vreg);
      bool is_tagged = code()->IsReference(input_vreg);
      AllocateFixed(cur_input, instr_index, is_tagged, true, false);
      data()->AddGapMove(instr_index, Instruction::END, input_copy, *cur_input);
    }
  }
  // Handle "output same as input" for second instruction.
  for (size_t i = 0; i < second->OutputCount(); i++) {
    InstructionOperand* output = second->OutputAt(i);
    if (!output->IsUnallocated()) continue;
    UnallocatedOperand* second_output = UnallocatedOperand::cast(output);
    if (!second_output->HasSameAsInputPolicy()) continue;
    DCHECK_EQ(0, i); // Only valid for first output.
    UnallocatedOperand* cur_input =
        UnallocatedOperand::cast(second->InputAt(second_output->input_index()));
    int output_vreg = second_output->virtual_register();
    int input_vreg = cur_input->virtual_register();
    UnallocatedOperand input_copy(UnallocatedOperand::REGISTER_OR_SLOT,
                                  input_vreg);
    *cur_input =
        UnallocatedOperand(*cur_input, second_output->virtual_register());
    MoveOperands* gap_move = data()->AddGapMove(instr_index, Instruction::END,
                                                input_copy, *cur_input);
    DCHECK_NOT_NULL(gap_move);
    if (code()->IsReference(input_vreg) && !code()->IsReference(output_vreg)) {
      if (second->HasReferenceMap()) {
        RegisterAllocationData::DelayedReference delayed_reference = {
            second->reference_map(), &gap_move->source()};
        data()->delayed_references().push_back(delayed_reference);
      }
    }
  }
}
References v8::internal::compiler::RegisterAllocationData::AddGapMove(), AllocateFixed(), v8::internal::compiler::Frame::AllocateSpillSlot(), allocation_zone(), v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::ByteWidthForStackSlot(), code(), data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::compiler::RegisterAllocationData::delayed_references(), v8::internal::compiler::Instruction::END, v8::internal::ZoneVector< T >::end(), v8::internal::compiler::end(), v8::internal::compiler::RegisterAllocationData::frame(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::compiler::TopLevelLiveRange::GetSpillOperand(), v8::internal::compiler::UnallocatedOperand::HasFixedPolicy(), v8::internal::compiler::Instruction::HasReferenceMap(), v8::internal::compiler::UnallocatedOperand::HasSameAsInputPolicy(), v8::internal::compiler::UnallocatedOperand::HasSlotPolicy(), v8::internal::compiler::TopLevelLiveRange::HasSpillOperand(), v8::internal::index, v8::internal::compiler::UnallocatedOperand::input_index(), v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::InstructionSequence::IsReference(), v8::internal::Zone::New(), v8::internal::compiler::AllocatedOperand::New(), v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::Instruction::reference_map(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, v8::internal::compiler::LiveRange::representation(), v8::internal::compiler::RegisterAllocationData::slot_for_const_range(), v8::internal::compiler::MoveOperands::source(), v8::internal::compiler::LocationOperand::STACK_SLOT, and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by MeetRegisterConstraints().
MeetRegisterConstraints() [1/2]
void v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraints ()
Definition at line 1552 of file register-allocator.cc.
                                                {
  for (InstructionBlock* block : code()->instruction_blocks()) {
    data_->tick_counter()->TickAndMaybeEnterSafepoint();
    MeetRegisterConstraints(block);
  }
}
References code(), data_, v8::internal::compiler::RegisterAllocationData::tick_counter(), and v8::internal::TickCounter::TickAndMaybeEnterSafepoint().
Referenced by v8::internal::compiler::turboshaft::MeetRegisterConstraintsPhase::Run().
MeetRegisterConstraints() [2/2]
void v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraints (const InstructionBlock * block) [private]
Definition at line 1559 of file register-allocator.cc.
                                                                             {
  int start = block->first_instruction_index();
  int end = block->last_instruction_index();
  DCHECK_NE(-1, start);
  for (int i = start; i <= end; ++i) {
    MeetConstraintsBefore(i);
    if (i != end) MeetConstraintsAfter(i);
  }
  // Meet register constraints for the instruction in the end.
  MeetRegisterConstraintsForLastInstructionInBlock(block);
}
References DCHECK_NE, v8::internal::compiler::end(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionBlock::last_instruction_index(), MeetConstraintsAfter(), MeetConstraintsBefore(), and MeetRegisterConstraintsForLastInstructionInBlock().
MeetRegisterConstraintsForLastInstructionInBlock()
void v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock (const InstructionBlock * block) [private]
Definition at line 1571 of file register-allocator.cc.
                                   {
  int end = block->last_instruction_index();
  Instruction* last_instruction = code()->InstructionAt(end);
  for (size_t i = 0; i < last_instruction->OutputCount(); i++) {
    InstructionOperand* output_operand = last_instruction->OutputAt(i);
    DCHECK(!output_operand->IsConstant());
    UnallocatedOperand* output = UnallocatedOperand::cast(output_operand);
    int output_vreg = output->virtual_register();
    TopLevelLiveRange* range = data()->GetLiveRangeFor(output_vreg);
    bool assigned = false;
    if (output->HasFixedPolicy()) {
      AllocateFixed(output, -1, false, false, true);
      // This value is produced on the stack, we never need to spill it.
      if (output->IsStackSlot()) {
        DCHECK(LocationOperand::cast(output)->index() <
               data()->frame()->GetSpillSlotCount());
        range->SetSpillOperand(LocationOperand::cast(output));
        range->SetSpillStartIndex(end);
        assigned = true;
      }
      for (const RpoNumber& succ : block->successors()) {
        const InstructionBlock* successor = code()->InstructionBlockAt(succ);
        DCHECK_EQ(1, successor->PredecessorCount());
        int gap_index = successor->first_instruction_index();
        // Create an unconstrained operand for the same virtual register
        // and insert a gap move from the fixed output to the operand.
        UnallocatedOperand output_copy(UnallocatedOperand::REGISTER_OR_SLOT,
                                       output_vreg);
        data()->AddGapMove(gap_index, Instruction::START, *output, output_copy);
      }
    }
    if (!assigned) {
      for (const RpoNumber& succ : block->successors()) {
        const InstructionBlock* successor = code()->InstructionBlockAt(succ);
        DCHECK_EQ(1, successor->PredecessorCount());
        int gap_index = successor->first_instruction_index();
        range->RecordSpillLocation(allocation_zone(), gap_index, output);
        range->SetSpillStartIndex(gap_index);
      }
    }
  }
}
References v8::internal::compiler::RegisterAllocationData::AddGapMove(), AllocateFixed(), allocation_zone(), v8::internal::compiler::LocationOperand::cast(), code(), data(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::end(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::compiler::UnallocatedOperand::HasFixedPolicy(), v8::internal::index, v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::TopLevelLiveRange::RecordSpillLocation(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, v8::internal::compiler::TopLevelLiveRange::SetSpillOperand(), v8::internal::compiler::TopLevelLiveRange::SetSpillStartIndex(), v8::internal::compiler::Instruction::START, v8::internal::compiler::InstructionBlock::successors(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by MeetRegisterConstraints().
operator=()
ConstraintBuilder& v8::internal::compiler::ConstraintBuilder::operator= (const ConstraintBuilder &) [delete]
ResolvePhis() [1/2]
void v8::internal::compiler::ConstraintBuilder::ResolvePhis ()
Definition at line 1754 of file register-allocator.cc.
                                    {
  // Process the blocks in reverse order.
  for (InstructionBlock* block : base::Reversed(code()->instruction_blocks())) {
    data_->tick_counter()->TickAndMaybeEnterSafepoint();
    ResolvePhis(block);
  }
}
References code(), data_, v8::base::Reversed(), v8::internal::compiler::RegisterAllocationData::tick_counter(), and v8::internal::TickCounter::TickAndMaybeEnterSafepoint().
Referenced by v8::internal::compiler::turboshaft::ResolvePhisPhase::Run().
ResolvePhis() [2/2]
void v8::internal::compiler::ConstraintBuilder::ResolvePhis (const InstructionBlock * block) [private]
Definition at line 1762 of file register-allocator.cc.
                                                                 {
  for (PhiInstruction* phi : block->phis()) {
    int phi_vreg = phi->virtual_register();
    RegisterAllocationData::PhiMapValue* map_value =
        data()->InitializePhiMap(block, phi);
    InstructionOperand& output = phi->output();
    // Map the destination operands, so the commitment phase can find them.
    for (size_t i = 0; i < phi->operands().size(); ++i) {
      InstructionBlock* cur_block =
          code()->InstructionBlockAt(block->predecessors()[i]);
      UnallocatedOperand input(UnallocatedOperand::REGISTER_OR_SLOT,
                               phi->operands()[i]);
      MoveOperands* move = data()->AddGapMove(
          cur_block->last_instruction_index(), Instruction::END, input, output);
      map_value->AddOperand(&move->destination());
      DCHECK(!code()
                  ->InstructionAt(cur_block->last_instruction_index())
                  ->HasReferenceMap());
    }
    TopLevelLiveRange* live_range = data()->GetLiveRangeFor(phi_vreg);
    int gap_index = block->first_instruction_index();
    live_range->RecordSpillLocation(allocation_zone(), gap_index, &output);
    live_range->SetSpillStartIndex(gap_index);
    // We use the phi-ness of some nodes in some later heuristics.
    live_range->set_is_phi(true);
    live_range->set_is_non_loop_phi(!block->IsLoopHeader());
  }
}
References v8::internal::compiler::RegisterAllocationData::AddGapMove(), v8::internal::compiler::RegisterAllocationData::PhiMapValue::AddOperand(), allocation_zone(), code(), data(), v8::internal::DCHECK(), v8::internal::compiler::MoveOperands::destination(), v8::internal::compiler::Instruction::END, v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::RegisterAllocationData::InitializePhiMap(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionBlock::IsLoopHeader(), v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::InstructionBlock::phis(), v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::compiler::TopLevelLiveRange::RecordSpillLocation(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, v8::internal::compiler::TopLevelLiveRange::set_is_non_loop_phi(), v8::internal::compiler::TopLevelLiveRange::set_is_phi(), v8::internal::compiler::TopLevelLiveRange::SetSpillStartIndex(), and size().
Member Data Documentation
data_
RegisterAllocationData* const v8::internal::compiler::ConstraintBuilder::data_ [private]
Definition at line 1363 of file register-allocator.h.
Referenced by data(), MeetRegisterConstraints(), and ResolvePhis().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc