v8::internal::compiler::turboshaft::TypeInferenceReducer< Next > Class Template Reference
#include <type-inference-reducer.h>
Public Types
using Adapter = UniformReducerAdapter< TypeInferenceReducer, Next >
using Args = TypeInferenceReducerArgs
Public Member Functions
TypeInferenceReducer ()
void Analyze ()
Type GetInputGraphType (OpIndex ig_index)
Type GetOutputGraphType (OpIndex og_index)
template<Opcode opcode, typename Continuation , typename... Ts>
OpIndex ReduceOperation (Ts... args)
template<typename Op , typename Continuation >
OpIndex ReduceInputGraphOperation (OpIndex ig_index, const Op &operation)
void Bind (Block *new_block)
void RefineTypesAfterBranch (const BranchOp *branch, Block *new_block, bool then_branch)
void RefineOperationType (Block *new_block, OpIndex op, const Type &type, char case_for_tracing)
OpIndex REDUCE() PendingLoopPhi (OpIndex first, RegisterRepresentation rep)
OpIndex REDUCE() Phi (base::Vector< const OpIndex > inputs, RegisterRepresentation rep)
OpIndex REDUCE() Constant (ConstantOp::Kind kind, ConstantOp::Storage value)
V< Word32 > REDUCE() Comparison (V< Any > left, V< Any > right, ComparisonOp::Kind kind, RegisterRepresentation rep)
V< Any > REDUCE() Projection (V< Any > input, uint16_t idx, RegisterRepresentation rep)
V< Word > REDUCE() WordBinop (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep)
OpIndex REDUCE() OverflowCheckedBinop (V< Word > left, V< Word > right, OverflowCheckedBinopOp::Kind kind, WordRepresentation rep)
V< Float > REDUCE() FloatBinop (V< Float > left, V< Float > right, FloatBinopOp::Kind kind, FloatRepresentation rep)
OpIndex REDUCE() CheckTurboshaftTypeOf (OpIndex input, RegisterRepresentation rep, Type type, bool successful)
void RemoveLast (OpIndex index_of_last_operation)
Private Types
using table_t = SnapshotTable< Type >
Private Member Functions
void RefineTypeFromInputGraph (OpIndex index, const Type &og_type, const Type &ig_type)
Type GetTypeOrInvalid (OpIndex index)
Type GetTupleType (const TupleOp &tuple)
Type GetType (OpIndex index)
void SetType (OpIndex index, const Type &result_type, bool is_fallback_for_unsupported_operation=false)
bool NeedsTyping (OpIndex index) const
Private Attributes
TypeInferenceReducerArgs args_ {TypeInferenceReducerArgs::Get()}
GrowingOpIndexSidetable< Type > input_graph_types_
GrowingOpIndexSidetable< Type > & output_graph_types_
table_t table_ {Asm().phase_zone()}
const Block * current_block_ = nullptr
GrowingOpIndexSidetable< std::optional< table_t::Key > > op_to_key_mapping_
GrowingBlockSidetable< std::optional< table_t::Snapshot > > block_to_snapshot_mapping_
ZoneVector< table_t::Snapshot > predecessors_ {Asm().phase_zone()}
TypeInferenceAnalysis analyzer_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >
Definition at line 77 of file type-inference-reducer.h.
Member Typedef Documentation
Adapter
template<class Next >
using v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Adapter = UniformReducerAdapter<TypeInferenceReducer, Next>
Definition at line 85 of file type-inference-reducer.h.
Args
template<class Next >
using v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Args = TypeInferenceReducerArgs
Definition at line 86 of file type-inference-reducer.h.
table_t
template<class Next >
using v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::table_t = SnapshotTable<Type> [private]
Definition at line 80 of file type-inference-reducer.h.
Constructor & Destructor Documentation
TypeInferenceReducer()
template<class Next >
v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::TypeInferenceReducer () [inline]
Definition at line 88 of file type-inference-reducer.h.
                         {
    // It is not reasonable to try to reuse input graph types if there are none.
    DCHECK_IMPLIES(args_.output_graph_typing ==
                       Args::OutputGraphTyping::kPreserveFromInputGraph,
                   args_.input_graph_typing != Args::InputGraphTyping::kNone);
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::args_, DCHECK_IMPLIES, v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::input_graph_typing, v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::kNone, v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::kPreserveFromInputGraph, and v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::output_graph_typing.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Analyze () [inline]
Definition at line 95 of file type-inference-reducer.h.
                 {
    if (args_.input_graph_typing == Args::InputGraphTyping::kPrecise) {
#ifdef DEBUG
      GrowingBlockSidetable<std::vector<std::pair<OpIndex, Type>>>
          block_refinements(Asm().input_graph().block_count(), {},
                            Asm().phase_zone());
      input_graph_types_ = analyzer_.Run(&block_refinements);
      Tracing::Get().PrintPerBlockData(
          "Type Refinements", Asm().input_graph(),
          [&](std::ostream& stream, const turboshaft::Graph& graph,
              turboshaft::BlockIndex index) -> bool {
            const std::vector<std::pair<turboshaft::OpIndex, turboshaft::Type>>&
                refinements = block_refinements[index];
            if (refinements.empty()) return false;
            stream << "\\n";
            for (const auto& [op, type] : refinements) {
              stream << op << " : " << type << "\\n";
            }
            return true;
          });
#else
      input_graph_types_ = analyzer_.Run(nullptr);
#endif // DEBUG
      Tracing::Get().PrintPerOperationData(
          "Types", Asm().input_graph(),
          [&](std::ostream& stream, const turboshaft::Graph& graph,
              turboshaft::OpIndex index) -> bool {
            turboshaft::Type type = input_graph_types_[index];
            if (!type.IsInvalid() && !type.IsNone()) {
              type.PrintTo(stream);
              return true;
            }
            return false;
          });
    }
    Next::Analyze();
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::args_, v8::internal::anonymous_namespace{json-stringifier.cc}::for(), v8::base::ContextualVariable< Derived, VarType >::Get(), graph(), v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::input_graph_types_, v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::input_graph_typing, v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::kPrecise, v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Run(), and v8::internal::tracing::type.
Bind()
template<class Next >
void v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind (Block * new_block) [inline]
Definition at line 176 of file type-inference-reducer.h.
                              {
    Next::Bind(new_block);
    // Seal the current block first.
    if (table_.IsSealed()) {
      DCHECK_NULL(current_block_);
    } else {
      // If we bind a new block while the previous one is still unsealed, we
      // finalize it.
      DCHECK_NOT_NULL(current_block_);
      DCHECK(current_block_->index().valid());
      block_to_snapshot_mapping_[current_block_->index()] = table_.Seal();
      current_block_ = nullptr;
    }
    // Collect the snapshots of all predecessors.
    {
      predecessors_.clear();
      for (const Block* pred : new_block->PredecessorsIterable()) {
        std::optional<table_t::Snapshot> pred_snapshot =
            block_to_snapshot_mapping_[pred->index()];
        DCHECK(pred_snapshot.has_value());
        predecessors_.push_back(pred_snapshot.value());
      }
      std::reverse(predecessors_.begin(), predecessors_.end());
    }
    // Start a new snapshot for this block by merging information from
    // predecessors.
    {
      auto MergeTypes = [&](table_t::Key,
                            base::Vector<const Type> predecessors) -> Type {
        DCHECK_GT(predecessors.size(), 0);
        Type result_type = predecessors[0];
        for (size_t i = 1; i < predecessors.size(); ++i) {
          result_type = Type::LeastUpperBound(result_type, predecessors[i],
                                              Asm().graph_zone());
        }
        return result_type;
      };
      table_.StartNewSnapshot(base::VectorOf(predecessors_), MergeTypes);
    }
    // Check if the predecessor is a branch that allows us to refine a few
    // types.
    if (args_.output_graph_typing ==
        Args::OutputGraphTyping::kRefineFromInputGraph) {
      if (new_block->PredecessorCount() == 1) {
        Block* predecessor = new_block->LastPredecessor();
        const Operation& terminator =
            predecessor->LastOperation(Asm().output_graph());
        if (const BranchOp* branch = terminator.TryCast<BranchOp>()) {
          DCHECK(branch->if_true == new_block || branch->if_false == new_block);
          RefineTypesAfterBranch(branch, new_block,
                                 branch->if_true == new_block);
        }
      }
    }
    current_block_ = new_block;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::args_, v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::block_to_snapshot_mapping_, v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::current_block_, v8::internal::DCHECK(), DCHECK_GT, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::ZoneVector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::kRefineFromInputGraph, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Type::LeastUpperBound(), v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::output_graph_typing, v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::predecessors_, v8::internal::compiler::turboshaft::Block::PredecessorsIterable(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypesAfterBranch(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::table_, v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::turboshaft::BlockIndex::valid(), and v8::base::VectorOf().
CheckTurboshaftTypeOf()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::CheckTurboshaftTypeOf (OpIndex input, RegisterRepresentation rep, Type type, bool successful) [inline]
Definition at line 376 of file type-inference-reducer.h.
                                                         {
    Type input_type = GetType(input);
    if (input_type.IsSubtypeOf(type)) {
      OpIndex index = Next::ReduceCheckTurboshaftTypeOf(input, rep, type, true);
      TURBOSHAFT_TRACE_TYPING_OK(
          "CTOF %3d:%-40s\n P: %3d:%-40s ~~> %s\n", index.id(),
          Asm().output_graph().Get(index).ToString().substr(0, 40).c_str(),
          input.id(),
          Asm().output_graph().Get(input).ToString().substr(0, 40).c_str(),
          input_type.ToString().c_str());
      return index;
    }
    if (successful) {
      FATAL(
          "Checking type %s of operation %d:%s failed after it passed in a "
          "previous phase",
          type.ToString().c_str(), input.id(),
          Asm().output_graph().Get(input).ToString().c_str());
    }
    OpIndex index =
        Next::ReduceCheckTurboshaftTypeOf(input, rep, type, successful);
    TURBOSHAFT_TRACE_TYPING_FAIL(
        "CTOF %3d:%-40s\n F: %3d:%-40s ~~> %s\n", index.id(),
        Asm().output_graph().Get(index).ToString().substr(0, 40).c_str(),
        input.id(),
        Asm().output_graph().Get(input).ToString().substr(0, 40).c_str(),
        input_type.ToString().c_str());
    return index;
  }
References FATAL, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::index, v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), v8::internal::compiler::turboshaft::Type::ToString(), v8::internal::compiler::ToString(), TURBOSHAFT_TRACE_TYPING_FAIL, TURBOSHAFT_TRACE_TYPING_OK, and v8::internal::tracing::type.
Comparison()
template<class Next >
V<Word32> REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Comparison (V< Any > left, V< Any > right, ComparisonOp::Kind kind, RegisterRepresentation rep) [inline]
Definition at line 319 of file type-inference-reducer.h.
                                                           {
    OpIndex index = Next::ReduceComparison(left, right, kind, rep);
    if (!NeedsTyping(index)) return index;
    Type type = Typer::TypeComparison(GetType(left), GetType(right), rep, kind,
                                      Asm().graph_zone());
    SetType(index, type);
    return index;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::Typer::TypeComparison().
Constant()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Constant (ConstantOp::Kind kind, ConstantOp::Storage value) [inline]
Definition at line 310 of file type-inference-reducer.h.
                                                                         {
    OpIndex index = Next::ReduceConstant(kind, value);
    if (!NeedsTyping(index)) return index;
    Type type = Typer::TypeConstant(kind, value);
    SetType(index, type);
    return index;
  }
References v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::tracing::type, v8::internal::compiler::turboshaft::Typer::TypeConstant(), and v8::internal::value.
FloatBinop()
template<class Next >
V<Float> REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::FloatBinop (V< Float > left, V< Float > right, FloatBinopOp::Kind kind, FloatRepresentation rep) [inline]
Definition at line 364 of file type-inference-reducer.h.
                                                       {
    V<Float> index = Next::ReduceFloatBinop(left, right, kind, rep);
    if (!NeedsTyping(index)) return index;
    Type type = Typer::TypeFloatBinop(GetType(left), GetType(right), kind, rep,
                                      Asm().graph_zone());
    SetType(index, type);
    return index;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::Typer::TypeFloatBinop().
GetInputGraphType()
template<class Next >
Type v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetInputGraphType (OpIndex ig_index) [inline]
Definition at line 133 of file type-inference-reducer.h.
                                           {
    return input_graph_types_[ig_index];
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::input_graph_types_.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation().
GetOutputGraphType()
template<class Next >
Type v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetOutputGraphType (OpIndex og_index) [inline]
Definition at line 137 of file type-inference-reducer.h.
{ return GetType(og_index); }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType().
GetTupleType()
template<class Next >
Type v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTupleType (const TupleOp & tuple) [inline], [private]
Definition at line 448 of file type-inference-reducer.h.
                                          {
    base::SmallVector<Type, 4> tuple_types;
    for (OpIndex input : tuple.inputs()) {
      tuple_types.push_back(GetType(input));
    }
    return TupleType::Tuple(base::VectorOf(tuple_types), Asm().graph_zone());
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::TupleType::Tuple(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType().
GetType()
template<class Next >
Type v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType (OpIndex index) [inline], [private]
Definition at line 456 of file type-inference-reducer.h.
                              {
    Type type = GetTypeOrInvalid(index);
    if (type.IsInvalid()) {
      const Operation& op = Asm().output_graph().Get(index);
      if (op.Is<TupleOp>()) {
        return GetTupleType(op.Cast<TupleOp>());
      } else {
        return Typer::TypeForRepresentation(op.outputs_rep(),
                                            Asm().graph_zone());
      }
    }
    return type;
  }
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTupleType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTypeOrInvalid(), v8::internal::index, v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Operation::outputs_rep(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::Typer::TypeForRepresentation().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::CheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetOutputGraphType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTupleType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Phi(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Projection(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypesAfterBranch(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RemoveLast(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::WordBinop().
GetTypeOrInvalid()
template<class Next >
Type v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTypeOrInvalid (OpIndex index) [inline], [private]
Definition at line 443 of file type-inference-reducer.h.
                                       {
    if (auto key = op_to_key_mapping_[index]) return table_.Get(*key);
    return Type::Invalid();
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::index, v8::internal::compiler::turboshaft::Type::Invalid(), v8::internal::key, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::op_to_key_mapping_, and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::table_.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType().
NeedsTyping()
template<class Next >
bool v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping (OpIndex index) const [inline], [private]
Definition at line 546 of file type-inference-reducer.h.
                                        {
    return index.valid() && args_.output_graph_typing ==
                                Args::OutputGraphTyping::kRefineFromInputGraph;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::args_, v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::kRefineFromInputGraph, and v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::output_graph_typing.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Constant(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::PendingLoopPhi(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Phi(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Projection(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceOperation(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::WordBinop().
OverflowCheckedBinop()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::OverflowCheckedBinop (V< Word > left, V< Word > right, OverflowCheckedBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 352 of file type-inference-reducer.h.
                                                               {
    OpIndex index = Next::ReduceOverflowCheckedBinop(left, right, kind, rep);
    if (!NeedsTyping(index)) return index;
    Type type = Typer::TypeOverflowCheckedBinop(GetType(left), GetType(right),
                                                kind, rep, Asm().graph_zone());
    SetType(index, type);
    return index;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop().
PendingLoopPhi()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::PendingLoopPhi (OpIndex first, RegisterRepresentation rep) [inline]
Definition at line 285 of file type-inference-reducer.h.
                                                                            {
    OpIndex index = Next::ReducePendingLoopPhi(first, rep);
    if (!NeedsTyping(index)) return index;
    // There is not much we can do for pending loop phis, because we don't know
    // the type of the backedge yet, so we have to assume maximal type. If we
    // run with a typed input graph, we can refine this type using the input
    // graph's type (see ReduceInputGraphOperation).
    SetType(index, Typer::TypeForRepresentation(rep));
    return index;
  }
References v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), and v8::internal::compiler::turboshaft::Typer::TypeForRepresentation().
Phi()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Phi (base::Vector< const OpIndex > inputs, RegisterRepresentation rep) [inline]
Definition at line 297 of file type-inference-reducer.h.
                                                  {
    OpIndex index = Next::ReducePhi(inputs, rep);
    if (!NeedsTyping(index)) return index;
    Type type = Type::None();
    for (const OpIndex input : inputs) {
      type = Type::LeastUpperBound(type, GetType(input), Asm().graph_zone());
    }
    SetType(index, type);
    return index;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::index, v8::internal::compiler::turboshaft::Type::LeastUpperBound(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), and v8::internal::tracing::type.
Projection()
template<class Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Projection (V< Any > input, uint16_t idx, RegisterRepresentation rep) [inline]
Definition at line 331 of file type-inference-reducer.h.
                                                        {
    V<Any> index = Next::ReduceProjection(input, idx, rep);
    if (!NeedsTyping(index)) return index;
    Type type = Typer::TypeProjection(GetType(input), idx);
    SetType(index, type);
    return index;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::Typer::TypeProjection().
ReduceInputGraphOperation()
template<class Next >
template<typename Op , typename Continuation >
OpIndex v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation (OpIndex ig_index, const Op & operation) [inline]
Definition at line 154 of file type-inference-reducer.h.
                                                                           {
    OpIndex og_index = Continuation{this}.ReduceInputGraph(ig_index, operation);
    if (!og_index.valid()) return og_index;
    if (args_.output_graph_typing == Args::OutputGraphTyping::kNone) {
      return og_index;
    }
    if (!CanBeTyped(operation)) return og_index;
    Type ig_type = GetInputGraphType(ig_index);
    DCHECK_IMPLIES(args_.input_graph_typing != Args::InputGraphTyping::kNone,
                   !ig_type.IsInvalid());
    if (!ig_type.IsInvalid()) {
      Type og_type = GetType(og_index);
      // If the type we have from the input graph is more precise, we keep it.
      if (og_type.IsInvalid() ||
          (ig_type.IsSubtypeOf(og_type) && !og_type.IsSubtypeOf(ig_type))) {
        RefineTypeFromInputGraph(og_index, og_type, ig_type);
      }
    }
    return og_index;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::args_, v8::internal::compiler::turboshaft::CanBeTyped(), DCHECK_IMPLIES, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetInputGraphType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::input_graph_typing, v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::kNone, v8::internal::compiler::turboshaft::TypeInferenceReducerArgs::output_graph_typing, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypeFromInputGraph(), and v8::internal::compiler::turboshaft::OpIndex::valid().
ReduceOperation()
template<class Next >
template<Opcode opcode, typename Continuation , typename... Ts>
OpIndex v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceOperation (Ts... args) [inline]
Definition at line 140 of file type-inference-reducer.h.
                                      {
    OpIndex index = Continuation{this}.Reduce(args...);
    if (!NeedsTyping(index)) return index;
    const Operation& op = Asm().output_graph().Get(index);
    if (CanBeTyped(op)) {
      Type type = Typer::TypeForRepresentation(
          Asm().output_graph().Get(index).outputs_rep(), Asm().graph_zone());
      SetType(index, type, true);
    }
    return index;
  }
References v8::base::args, v8::internal::compiler::turboshaft::CanBeTyped(), v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::Typer::TypeForRepresentation().
RefineOperationType()
template<class Next >
void v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType (Block * new_block, OpIndex op, const Type & type, char case_for_tracing) [inline]
Definition at line 258 of file type-inference-reducer.h.
                                                  {
    DCHECK(op.valid());
    DCHECK(!type.IsInvalid());
    TURBOSHAFT_TRACE_TYPING_OK(
        " %c: %3d:%-40s ~~> %s\n", case_for_tracing, op.id(),
        Asm().output_graph().Get(op).ToString().substr(0, 40).c_str(),
        type.ToString().c_str());
    auto key_opt = op_to_key_mapping_[op];
    // We might not have a key for this value, because we are running in a mode
    // where we don't type all operations.
    if (key_opt.has_value()) {
      table_.Set(*key_opt, type);
#ifdef DEBUG
      std::vector<std::pair<OpIndex, Type>>& refinement =
          Asm().output_graph().block_type_refinement()[new_block->index()];
      refinement.push_back(std::make_pair(op, type));
#endif
      // TODO(nicohartmann@): One could push the refined type deeper into the
      // operations.
    }
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::op_to_key_mapping_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::table_, v8::internal::compiler::ToString(), TURBOSHAFT_TRACE_TYPING_OK, v8::internal::tracing::type, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypeFromInputGraph(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypesAfterBranch().
RefineTypeFromInputGraph()
template<class Next >
void v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypeFromInputGraph (OpIndex index, const Type & og_type, const Type & ig_type) [inline], [private]
Definition at line 426 of file type-inference-reducer.h.
                                                     {
    // Refinement should happen when we just lowered the corresponding
    // operation, so we should be at the point where the operation is defined
    // (e.g. not in a refinement after a branch). So the current block must
    // contain the operation.
    DCHECK(!ig_type.IsInvalid());
    TURBOSHAFT_TRACE_TYPING_OK(
        "Refi %3d:%-40s\n I: %-40s ~~> %-40s\n", index.id(),
        Asm().output_graph().Get(index).ToString().substr(0, 40).c_str(),
        (og_type.IsInvalid() ? "invalid" : og_type.ToString().c_str()),
        ig_type.ToString().c_str());
    RefineOperationType(Asm().current_block(), index, ig_type, 'I');
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), v8::internal::compiler::turboshaft::Type::ToString(), v8::internal::compiler::ToString(), and TURBOSHAFT_TRACE_TYPING_OK.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation().
RefineTypesAfterBranch()
template<class Next >
void v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypesAfterBranch (const BranchOp * branch, Block * new_block, bool then_branch) [inline]
Definition at line 238 of file type-inference-reducer.h.
                                                {
    const std::string branch_str = branch->ToString().substr(0, 40);
    USE(branch_str);
    TURBOSHAFT_TRACE_TYPING_OK("Br %3d:%-40s\n",
                               Asm().output_graph().Index(*branch).id(),
                               branch_str.c_str());
    Typer::BranchRefinements refinements(
        [this](OpIndex index) { return GetType(index); },
        [&](OpIndex index, const Type& refined_type) {
          RefineOperationType(new_block, index, refined_type,
                              then_branch ? 'T' : 'F');
        });
    // Inspect branch condition.
    const Operation& condition = Asm().output_graph().Get(branch->condition());
    refinements.RefineTypes(condition, then_branch, Asm().graph_zone());
  }
References v8::internal::compiler::turboshaft::BranchOp::condition(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), v8::internal::string, v8::internal::compiler::turboshaft::Operation::ToString(), TURBOSHAFT_TRACE_TYPING_OK, and USE.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind().
RemoveLast()
template<class Next >
void v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RemoveLast (OpIndex index_of_last_operation) [inline]
Definition at line 408 of file type-inference-reducer.h.
                                                   {
    if (op_to_key_mapping_[index_of_last_operation]) {
      op_to_key_mapping_[index_of_last_operation] = std::nullopt;
      TURBOSHAFT_TRACE_TYPING_OK(
          "REM %3d:%-40s %-40s\n", index_of_last_operation.id(),
          Asm()
              .output_graph()
              .Get(index_of_last_operation)
              .ToString()
              .substr(0, 40)
              .c_str(),
          GetType(index_of_last_operation).ToString().substr(0, 40).c_str());
      output_graph_types_[index_of_last_operation] = Type::Invalid();
    }
    Next::RemoveLast(index_of_last_operation);
  }
References v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Type::Invalid(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::op_to_key_mapping_, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::output_graph_types_, v8::internal::compiler::ToString(), and TURBOSHAFT_TRACE_TYPING_OK.
SetType()
template<class Next >
void v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType (OpIndex index, const Type & result_type, bool is_fallback_for_unsupported_operation = false) [inline], [private]
Definition at line 470 of file type-inference-reducer.h.
                                                                   {
    DCHECK(!result_type.IsInvalid());
    if (auto key_opt = op_to_key_mapping_[index]) {
      table_.Set(*key_opt, result_type);
      DCHECK(result_type.IsSubtypeOf(output_graph_types_[index]));
      output_graph_types_[index] = result_type;
      DCHECK(!output_graph_types_[index].IsInvalid());
    } else {
      auto key = table_.NewKey(Type::None());
      op_to_key_mapping_[index] = key;
      table_.Set(key, result_type);
      output_graph_types_[index] = result_type;
    }
    if (!is_fallback_for_unsupported_operation) {
      TURBOSHAFT_TRACE_TYPING_OK(
          "Type %3d:%-40s ==> %s\n", index.id(),
          Asm().output_graph().Get(index).ToString().substr(0, 40).c_str(),
          result_type.ToString().c_str());
    } else {
      // TODO(nicohartmann@): Remove the fallback case once all operations are
      // supported.
      TURBOSHAFT_TRACE_TYPING_FAIL(
          "TODO %3d:%-40s ==> %s\n", index.id(),
          Asm().output_graph().Get(index).ToString().substr(0, 40).c_str(),
          result_type.ToString().c_str());
    }
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), v8::internal::key, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewKey(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::op_to_key_mapping_, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::output_graph_types_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::table_, v8::internal::compiler::turboshaft::Type::ToString(), v8::internal::compiler::ToString(), TURBOSHAFT_TRACE_TYPING_FAIL, and TURBOSHAFT_TRACE_TYPING_OK.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Constant(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::PendingLoopPhi(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Phi(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Projection(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceOperation(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::WordBinop().
WordBinop()
template<class Next >
V<Word> REDUCE() v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::WordBinop (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 341 of file type-inference-reducer.h.
                                                    {
    V<Word> index = Next::ReduceWordBinop(left, right, kind, rep);
    if (!NeedsTyping(index)) return index;
    Type type = Typer::TypeWordBinop(GetType(left), GetType(right), kind, rep,
                                     Asm().graph_zone());
    SetType(index, type);
    return index;
  }
References v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::index, v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::Typer::TypeWordBinop().
Member Data Documentation
analyzer_
template<class Next >
TypeInferenceAnalysis v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::analyzer_ [private]
Initial value:
{Asm().modifiable_input_graph(),
                                  Asm().phase_zone()}
Definition at line 566 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Analyze().
args_
template<class Next >
TypeInferenceReducerArgs v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::args_ {TypeInferenceReducerArgs::Get()} [private]
Definition at line 551 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Analyze(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::NeedsTyping(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::TypeInferenceReducer().
block_to_snapshot_mapping_
template<class Next >
GrowingBlockSidetable<std::optional<table_t::Snapshot> > v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::block_to_snapshot_mapping_ [private]
Initial value:
{Asm().input_graph().block_count(),
                                 std::nullopt, Asm().phase_zone()}
Definition at line 561 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind().
current_block_
template<class Next >
const Block* v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::current_block_ = nullptr [private]
Definition at line 557 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind().
input_graph_types_
template<class Next >
GrowingOpIndexSidetable<Type> v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::input_graph_types_ [private]
Initial value:
{Asm().graph_zone(),
                                                   &Asm().input_graph()}
Definition at line 552 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Analyze(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetInputGraphType().
op_to_key_mapping_
template<class Next >
GrowingOpIndexSidetable<std::optional<table_t::Key> > v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::op_to_key_mapping_ [private]
Initial value:
{
      Asm().phase_zone(), &Asm().output_graph()}
Definition at line 558 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTypeOrInvalid(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RemoveLast(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType().
output_graph_types_
template<class Next >
GrowingOpIndexSidetable<Type>& v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::output_graph_types_ [private]
Initial value:
{
      Asm().output_graph().operation_types()}
Definition at line 554 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RemoveLast(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType().
predecessors_
template<class Next >
ZoneVector<table_t::Snapshot> v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::predecessors_ {Asm().phase_zone()} [private]
Definition at line 565 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind().
table_
template<class Next >
table_t v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::table_ {Asm().phase_zone()} [private]
Definition at line 556 of file type-inference-reducer.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTypeOrInvalid(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/type-inference-reducer.h