v8::internal::torque::TorqueCodeGenerator Class Reference
#include <torque-code-generator.h>
Public Member Functions
TorqueCodeGenerator (const ControlFlowGraph &cfg, std::ostream &out)
Protected Member Functions
std::string DefinitionToVariable (const DefinitionLocation &location)
void SetDefinitionVariable (const DefinitionLocation &definition, const std::string &str)
std::ostream & out ()
std::ostream & decls ()
virtual void EmitSourcePosition (SourcePosition pos, bool always_emit=false)=0
std::string FreshNodeName ()
std::string FreshCatchName ()
std::string FreshLabelName ()
std::string BlockName (const Block *block)
void EmitInstruction (const Instruction &instruction, Stack< std::string > *stack)
template<typename T >
void EmitIRAnnotation (const T &instruction, Stack< std::string > *stack)
Static Protected Member Functions
static bool IsEmptyInstruction (const Instruction &instruction)
Protected Attributes
const ControlFlowGraph & cfg_
std::ostream * out_
std::ostream * out_decls_
size_t fresh_id_ = 0
SourcePosition previous_position_
std::map< DefinitionLocation, std::string > location_map_
Detailed Description
Definition at line 17 of file torque-code-generator.h.
Constructor & Destructor Documentation
TorqueCodeGenerator()
v8::internal::torque::TorqueCodeGenerator::TorqueCodeGenerator (const ControlFlowGraph & cfg, std::ostream & out) [inline]
Definition at line 19 of file torque-code-generator.h.
      : cfg_(cfg),
        out_(&out),
        out_decls_(&out),
        previous_position_(SourcePosition::Invalid()) {}
Member Function Documentation
BlockName()
std::string v8::internal::torque::TorqueCodeGenerator::BlockName (const Block * block) [inline], [protected]
Definition at line 70 of file torque-code-generator.h.
                                          {
    return "block" + std::to_string(block->id());
  }
References v8::internal::torque::Block::id().
Referenced by v8::internal::torque::CCGenerator::EmitBlock(), v8::internal::torque::CSAGenerator::EmitBlock(), v8::internal::torque::CCGenerator::EmitGoto(), v8::internal::torque::CSAGenerator::EmitGraph(), and v8::internal::torque::CSAGenerator::PostCallableExceptionPreparation().
decls()
std::ostream& v8::internal::torque::TorqueCodeGenerator::decls () [inline], [protected]
Definition at line 61 of file torque-code-generator.h.
{ return *out_decls_; }
References out_decls_.
Referenced by v8::internal::torque::CCGenerator::EmitBlock(), v8::internal::torque::CSAGenerator::EmitBlock(), and v8::internal::torque::CSAGenerator::PostCallableExceptionPreparation().
DefinitionToVariable()
std::string v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable (const DefinitionLocation & location) [inline], [protected]
Definition at line 33 of file torque-code-generator.h.
                                                                     {
    if (location.IsPhi()) {
      std::stringstream stream;
      stream << "phi_bb" << location.GetPhiBlock()->id() << "_"
             << location.GetPhiIndex();
      return stream.str();
    } else if (location.IsParameter()) {
      auto it = location_map_.find(location);
      DCHECK_NE(it, location_map_.end());
      return it->second;
    } else {
      DCHECK(location.IsInstruction());
      auto it = location_map_.find(location);
      if (it == location_map_.end()) {
        it = location_map_.insert(std::make_pair(location, FreshNodeName()))
                 .first;
      }
      return it->second;
    }
  }
References v8::internal::DCHECK(), DCHECK_NE, FreshNodeName(), v8::internal::torque::DefinitionLocation::GetPhiBlock(), v8::internal::torque::DefinitionLocation::GetPhiIndex(), v8::internal::torque::Block::id(), v8::internal::torque::DefinitionLocation::IsInstruction(), v8::internal::torque::DefinitionLocation::IsParameter(), v8::internal::torque::DefinitionLocation::IsPhi(), and location_map_.
Referenced by v8::internal::torque::CCGenerator::EmitBlock(), v8::internal::torque::CSAGenerator::EmitBlock(), v8::internal::torque::CCGenerator::EmitGoto(), and v8::internal::torque::CSAGenerator::PostCallableExceptionPreparation().
EmitInstruction()
void v8::internal::torque::TorqueCodeGenerator::EmitInstruction (const Instruction & instruction, Stack< std::string > * stack) [protected]
Definition at line 27 of file torque-code-generator.cc.
                                                                   {
#ifdef DEBUG
  if (!IsEmptyInstruction(instruction)) {
    EmitSourcePosition(instruction->pos);
  }
#endif
  switch (instruction.kind()) {
#define ENUM_ITEM(T) \
  case InstructionKind::k##T: \
    if (GlobalContext::annotate_ir()) { \
      EmitIRAnnotation(instruction.Cast<T>(), stack); \
    } \
    return EmitInstruction(instruction.Cast<T>(), stack);
    TORQUE_INSTRUCTION_LIST(ENUM_ITEM)
#undef ENUM_ITEM
  }
}
References EmitSourcePosition(), ENUM_ITEM, IsEmptyInstruction(), v8::internal::torque::Instruction::kind(), v8::internal::torque::InstructionBase::pos, and TORQUE_INSTRUCTION_LIST.
Referenced by v8::internal::torque::CCGenerator::EmitBlock(), v8::internal::torque::CSAGenerator::EmitBlock(), v8::internal::torque::CCGenerator::EmitGraph(), and v8::internal::torque::CSAGenerator::EmitGraph().
EmitIRAnnotation()
template<typename T >
void v8::internal::torque::TorqueCodeGenerator::EmitIRAnnotation (const T & instruction, Stack< std::string > * stack) [inline], [protected]
Definition at line 78 of file torque-code-generator.h.
                                                                       {
    out() << " // " << instruction
          << ", starting stack size: " << stack->Size() << "\n";
  }
References out(), and v8::internal::stack.
EmitSourcePosition()
virtual void v8::internal::torque::TorqueCodeGenerator::EmitSourcePosition (SourcePosition pos, bool always_emit = false) [protected], [pure virtual]
Implemented in v8::internal::torque::CSAGenerator, and v8::internal::torque::CCGenerator.
Referenced by EmitInstruction().
FreshCatchName()
std::string v8::internal::torque::TorqueCodeGenerator::FreshCatchName () [inline], [protected]
Definition at line 68 of file torque-code-generator.h.
{ return "catch" + std::to_string(fresh_id_++); }
References fresh_id_.
Referenced by v8::internal::torque::CSAGenerator::PreCallableExceptionPreparation().
FreshLabelName()
std::string v8::internal::torque::TorqueCodeGenerator::FreshLabelName () [inline], [protected]
Definition at line 69 of file torque-code-generator.h.
{ return "label" + std::to_string(fresh_id_++); }
References fresh_id_.
FreshNodeName()
std::string v8::internal::torque::TorqueCodeGenerator::FreshNodeName () [inline], [protected]
Definition at line 67 of file torque-code-generator.h.
{ return "tmp" + std::to_string(fresh_id_++); }
References fresh_id_.
Referenced by DefinitionToVariable().
IsEmptyInstruction()
bool v8::internal::torque::TorqueCodeGenerator::IsEmptyInstruction (const Instruction & instruction) [static], [protected]
Definition at line 13 of file torque-code-generator.cc.
                                                                           {
  switch (instruction.kind()) {
    case InstructionKind::kPeekInstruction:
    case InstructionKind::kPokeInstruction:
    case InstructionKind::kDeleteRangeInstruction:
    case InstructionKind::kPushUninitializedInstruction:
    case InstructionKind::kPushBuiltinPointerInstruction:
    case InstructionKind::kUnsafeCastInstruction:
      return true;
    default:
      return false;
  }
}
References v8::internal::torque::Instruction::kind().
Referenced by EmitInstruction().
out()
std::ostream& v8::internal::torque::TorqueCodeGenerator::out () [inline], [protected]
Definition at line 60 of file torque-code-generator.h.
{ return *out_; }
References out_.
Referenced by v8::internal::torque::CCGenerator::EmitBlock(), v8::internal::torque::CSAGenerator::EmitBlock(), v8::internal::torque::CCGenerator::EmitCCValue(), v8::internal::torque::CSAGenerator::EmitCSAValue(), v8::internal::torque::CCGenerator::EmitGoto(), v8::internal::torque::CCGenerator::EmitGraph(), v8::internal::torque::CSAGenerator::EmitGraph(), EmitIRAnnotation(), v8::internal::torque::CCGenerator::EmitSourcePosition(), v8::internal::torque::CSAGenerator::EmitSourcePosition(), v8::internal::torque::CSAGenerator::PostCallableExceptionPreparation(), and v8::internal::torque::CSAGenerator::PreCallableExceptionPreparation().
SetDefinitionVariable()
void v8::internal::torque::TorqueCodeGenerator::SetDefinitionVariable (const DefinitionLocation & definition, const std::string & str) [inline], [protected]
Definition at line 54 of file torque-code-generator.h.
                                                   {
    DCHECK_EQ(location_map_.find(definition), location_map_.end());
    location_map_.insert(std::make_pair(definition, str));
  }
References DCHECK_EQ, and location_map_.
Referenced by v8::internal::torque::CCGenerator::EmitGraph(), and v8::internal::torque::CSAGenerator::EmitGraph().
Member Data Documentation
cfg_
const ControlFlowGraph& v8::internal::torque::TorqueCodeGenerator::cfg_ [protected]
Definition at line 26 of file torque-code-generator.h.
Referenced by v8::internal::torque::CCGenerator::EmitGraph(), and v8::internal::torque::CSAGenerator::EmitGraph().
fresh_id_
size_t v8::internal::torque::TorqueCodeGenerator::fresh_id_ = 0 [protected]
Definition at line 29 of file torque-code-generator.h.
Referenced by FreshCatchName(), FreshLabelName(), and FreshNodeName().
location_map_
std::map<DefinitionLocation, std::string> v8::internal::torque::TorqueCodeGenerator::location_map_ [protected]
Definition at line 31 of file torque-code-generator.h.
Referenced by DefinitionToVariable(), and SetDefinitionVariable().
out_
std::ostream* v8::internal::torque::TorqueCodeGenerator::out_ [protected]
Definition at line 27 of file torque-code-generator.h.
Referenced by v8::internal::torque::CCGenerator::EmitGraph(), v8::internal::torque::CSAGenerator::EmitGraph(), and out().
out_decls_
std::ostream* v8::internal::torque::TorqueCodeGenerator::out_decls_ [protected]
Definition at line 28 of file torque-code-generator.h.
Referenced by decls().
previous_position_
SourcePosition v8::internal::torque::TorqueCodeGenerator::previous_position_ [protected]
Definition at line 30 of file torque-code-generator.h.
Referenced by v8::internal::torque::CCGenerator::EmitSourcePosition(), and v8::internal::torque::CSAGenerator::EmitSourcePosition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/torque-code-generator.h
/mnt/V8SourceCode/src/torque/torque-code-generator.cc