v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor > Class Template Reference
#include <interface-descriptors.h>
Inherits v8::internal::CallInterfaceDescriptor.
Inherited by v8::internal::StaticJSCallInterfaceDescriptor< ArrayConstructorDescriptor >, v8::internal::StaticJSCallInterfaceDescriptor< Construct_WithFeedbackDescriptor >, v8::internal::StaticJSCallInterfaceDescriptor< JSTrampolineDescriptor >, v8::internal::StaticJSCallInterfaceDescriptor< Construct_BaselineDescriptor >, and v8::internal::StaticJSCallInterfaceDescriptor< CppBuiltinAdaptorDescriptor >.
Public Member Functions
StaticCallInterfaceDescriptor (CallDescriptors::Key key)
Static Public Member Functions
static constexpr auto registers ()
static constexpr auto double_registers ()
static constexpr auto return_registers ()
static constexpr auto return_double_registers ()
static constexpr Flags flags ()
static constexpr bool AllowVarArgs ()
static constexpr bool HasContextParameter ()
static constexpr int GetReturnCount ()
static constexpr int GetParameterCount ()
static constexpr int GetRegisterParameterCount ()
static constexpr int GetStackParameterCount ()
static constexpr Register * GetRegisterData ()
static constexpr Register GetRegisterParameter (int i)
static constexpr int GetStackParameterIndex (int i)
static constexpr MachineType GetParameterType (int i)
static constexpr DoubleRegister GetDoubleRegisterParameter (int i)
Static Public Attributes
static constexpr int kReturnCount
static constexpr int kParameterCount
static constexpr bool kNoContext = false
static constexpr bool kAllowVarArgs = false
static constexpr bool kNoStackScan = false
static constexpr auto kStackArgumentOrder = StackArgumentOrder::kDefault
static constexpr int kMaxRegisterParams = kMaxBuiltinRegisterParams
static constexpr bool kRestrictAllocatableRegisters = false
static constexpr bool kCalleeSaveRegisters = false
static constexpr bool kCustomMachineTypes = false
Private Member Functions
void Initialize (CallInterfaceDescriptorData *data)
Static Private Member Functions
static void InitializeTypes (CallInterfaceDescriptorData *data)
Friends
class CallDescriptors
Additional Inherited Members
Detailed Description
template<typename DerivedDescriptor>
class v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >
Definition at line 487 of file interface-descriptors.h.
Constructor & Destructor Documentation
StaticCallInterfaceDescriptor()
template<typename DerivedDescriptor >
v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::StaticCallInterfaceDescriptor (CallDescriptors::Key key) [inline], [explicit]
Definition at line 566 of file interface-descriptors.h.
      : CallInterfaceDescriptor(key) {}
Member Function Documentation
AllowVarArgs()
template<typename DerivedDescriptor >
static constexpr bool v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::AllowVarArgs () [inline], [static], [constexpr]
Definition at line 546 of file interface-descriptors.h.
                                              {
    return DerivedDescriptor::kAllowVarArgs;
  }
double_registers()
template<typename DerivedDescriptor >
constexpr auto v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::double_registers [inline], [static], [constexpr]
Definition at line 61 of file interface-descriptors-inl.h.
                                                                   {
  return CallInterfaceDescriptor::DefaultDoubleRegisterArray();
}
References v8::internal::CallInterfaceDescriptor::DefaultDoubleRegisterArray().
flags()
template<typename DerivedDescriptor >
static constexpr Flags v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::flags () [inline], [static], [constexpr]
Definition at line 532 of file interface-descriptors.h.
                                        {
    return Flags((DerivedDescriptor::kNoContext
                      ? CallInterfaceDescriptorData::kNoContext
                      : 0) |
                 (DerivedDescriptor::kAllowVarArgs
                      ? CallInterfaceDescriptorData::kAllowVarArgs
                      : 0) |
                 (DerivedDescriptor::kNoStackScan
                      ? CallInterfaceDescriptorData::kNoStackScan
                      : 0) |
                 (DerivedDescriptor::kCalleeSaveRegisters
                      ? CallInterfaceDescriptorData::kCalleeSaveRegisters
                      : 0));
  }
References v8::internal::CallInterfaceDescriptorData::kAllowVarArgs, v8::internal::CallInterfaceDescriptorData::kCalleeSaveRegisters, v8::internal::CallInterfaceDescriptorData::kNoContext, and v8::internal::CallInterfaceDescriptorData::kNoStackScan.
GetDoubleRegisterParameter()
template<typename DerivedDescriptor >
constexpr DoubleRegister v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetDoubleRegisterParameter (int i) [inline], [static], [constexpr]
Definition at line 275 of file interface-descriptors-inl.h.
           {
  DCHECK(IsFloatingPoint(GetParameterType(i).representation()));
  return DoubleRegister::from_code(
      DerivedDescriptor::double_registers()[i].code());
}
References code, v8::internal::DCHECK(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), and v8::internal::IsFloatingPoint().
GetParameterCount()
template<typename DerivedDescriptor >
constexpr int v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetParameterCount [inline], [static], [constexpr]
Definition at line 159 of file interface-descriptors-inl.h.
                                                                    {
  static_assert(
      DerivedDescriptor::kParameterCount >= 0,
      "DerivedDescriptor subclass should override parameter count with a "
      "value that is greater than or equal to 0");
  return DerivedDescriptor::kParameterCount;
}
Referenced by v8::internal::compiler::CodeAssembler::TailCallJSCode().
GetParameterType()
template<typename DerivedDescriptor >
constexpr MachineType v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetParameterType (int i) [inline], [static], [constexpr]
Definition at line 255 of file interface-descriptors-inl.h.
                                                                        {
  if constexpr (!DerivedDescriptor::kCustomMachineTypes) {
    // If there are no custom machine types, all results and parameters are
    // tagged.
    return MachineType::AnyTagged();
  } else {
    // All varags are tagged.
    if (DerivedDescriptor::AllowVarArgs() &&
        i >= DerivedDescriptor::GetParameterCount()) {
      return MachineType::AnyTagged();
    }
    DCHECK_LT(i, DerivedDescriptor::GetParameterCount());
    return DerivedDescriptor::kMachineTypes
        [DerivedDescriptor::GetReturnCount() + i];
  }
}
References v8::internal::MachineType::AnyTagged(), DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
GetRegisterData()
template<typename DerivedDescriptor >
static constexpr Register* v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetRegisterData () [inline], [static], [constexpr]
GetRegisterParameter()
template<typename DerivedDescriptor >
constexpr Register v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetRegisterParameter (int i) [inline], [static], [constexpr]
Definition at line 239 of file interface-descriptors-inl.h.
                                                                            {
  DCHECK(!IsFloatingPoint(GetParameterType(i).representation()));
  return DerivedDescriptor::registers()[i];
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::IsFloatingPoint().
GetRegisterParameterCount()
template<typename DerivedDescriptor >
constexpr int v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetRegisterParameterCount [inline], [static], [constexpr]
Definition at line 208 of file interface-descriptors-inl.h.
                                                                            {
  static_assert(
      detail::IsRegisterArray<decltype(DerivedDescriptor::registers())>::value,
      "DerivedDescriptor subclass should define a registers() function "
      "returning a std::array<Register>");
  // The register parameter count is the minimum of:
  // 1. The number of named parameters in the descriptor, and
  // 2. The number of valid registers the descriptor provides with its
  // registers() function, e.g. for {rax, rbx, no_reg} this number is 2.
  // 3. The maximum number of register parameters allowed (
  // kMaxBuiltinRegisterParams for most builtins,
  // kMaxTFSBuiltinRegisterParams for TFS builtins, customizable by the
  // subclass otherwise).
  return std::min<int>({DerivedDescriptor::GetParameterCount(),
                        static_cast<int>(detail::FirstInvalidRegister(
                            DerivedDescriptor::registers())),
                        DerivedDescriptor::kMaxRegisterParams});
}
References v8::internal::detail::FirstInvalidRegister(), and v8::internal::value.
GetReturnCount()
template<typename DerivedDescriptor >
constexpr int v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetReturnCount [inline], [static], [constexpr]
Definition at line 147 of file interface-descriptors-inl.h.
                                                                 {
  static_assert(
      DerivedDescriptor::kReturnCount >= 0,
      "DerivedDescriptor subclass should override return count with a value "
      "that is greater than or equal to 0");
  return DerivedDescriptor::kReturnCount;
}
GetStackParameterCount()
template<typename DerivedDescriptor >
constexpr int v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetStackParameterCount [inline], [static], [constexpr]
Definition at line 231 of file interface-descriptors-inl.h.
                                                                         {
  return DerivedDescriptor::GetParameterCount() -
         DerivedDescriptor::GetRegisterParameterCount();
}
Referenced by v8::internal::compiler::turboshaft::CreateAllocateBuiltinDescriptor(), v8::internal::compiler::Pipeline::NewBytecodeHandlerCompilationJob(), and v8::internal::compiler::CodeAssembler::TailCallJSCode().
GetStackParameterIndex()
template<typename DerivedDescriptor >
constexpr int v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetStackParameterIndex (int i) [inline], [static], [constexpr]
Definition at line 247 of file interface-descriptors-inl.h.
           {
  return i - DerivedDescriptor::GetRegisterParameterCount();
}
HasContextParameter()
template<typename DerivedDescriptor >
static constexpr bool v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::HasContextParameter () [inline], [static], [constexpr]
Definition at line 549 of file interface-descriptors.h.
                                                     {
    return !DerivedDescriptor::kNoContext;
  }
Referenced by v8::internal::CallDescriptors::InitializeOncePerProcess().
Initialize()
template<typename DerivedDescriptor >
void v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::Initialize (CallInterfaceDescriptorData * data) [inline], [private]
Definition at line 98 of file interface-descriptors-inl.h.
                                       {
  // Static local copy of the Registers array, for platform-specific
  // initialization
  static constexpr auto registers = DerivedDescriptor::registers();
  static constexpr auto double_registers =
      DerivedDescriptor::double_registers();
  static constexpr auto return_registers =
      DerivedDescriptor::return_registers();
  static constexpr auto return_double_registers =
      DerivedDescriptor::return_double_registers();
  // The passed pointer should be a modifiable pointer to our own data.
  DCHECK_EQ(data, this->data());
  DCHECK(!data->IsInitialized());
  if (DerivedDescriptor::kRestrictAllocatableRegisters) {
    data->RestrictAllocatableRegisters(registers.data(), registers.size());
  } else {
    DCHECK(!DerivedDescriptor::kCalleeSaveRegisters);
  }
  // Make sure the defined arrays are big enough. The arrays can be filled up
  // with `no_reg` and `no_dreg` to pass this DCHECK.
  DCHECK_GE(registers.size(), GetRegisterParameterCount());
  DCHECK_GE(double_registers.size(), GetRegisterParameterCount());
  DCHECK_GE(return_registers.size(), DerivedDescriptor::kReturnCount);
  DCHECK_GE(return_double_registers.size(), DerivedDescriptor::kReturnCount);
  data->InitializeRegisters(
      DerivedDescriptor::flags(), DerivedDescriptor::kEntrypointTag,
      DerivedDescriptor::kSandboxingMode, DerivedDescriptor::kReturnCount,
      DerivedDescriptor::GetParameterCount(),
      DerivedDescriptor::kStackArgumentOrder,
      DerivedDescriptor::GetRegisterParameterCount(), registers.data(),
      double_registers.data(), return_registers.data(),
      return_double_registers.data());
  // InitializeTypes is customizable by the DerivedDescriptor subclass.
  DerivedDescriptor::InitializeTypes(data);
  DCHECK(data->IsInitialized());
  DCHECK(this->CheckFloatingPointParameters(data));
#if DEBUG
  DerivedDescriptor::Verify(data);
#endif
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, flags(), v8::internal::CallInterfaceDescriptorData::InitializeRegisters(), v8::internal::CallInterfaceDescriptorData::IsInitialized(), and v8::internal::CallInterfaceDescriptorData::RestrictAllocatableRegisters().
InitializeTypes()
template<typename DerivedDescriptor >
static void v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::InitializeTypes (CallInterfaceDescriptorData * data) [inline], [static], [private]
Definition at line 587 of file interface-descriptors.h.
                                                                 {
    DCHECK(!kCustomMachineTypes);
    data->InitializeTypes(nullptr, 0);
  }
References v8::internal::CallInterfaceDescriptor::data(), v8::internal::DCHECK(), v8::internal::CallInterfaceDescriptorData::InitializeTypes(), and v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kCustomMachineTypes.
registers()
template<typename DerivedDescriptor >
constexpr auto v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::registers [inline], [static], [constexpr]
Definition at line 54 of file interface-descriptors-inl.h.
                                                                           {
  return CallInterfaceDescriptor::DefaultRegisterArray();
}
References v8::internal::CallInterfaceDescriptor::DefaultRegisterArray().
return_double_registers()
template<typename DerivedDescriptor >
constexpr auto v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::return_double_registers [inline], [static], [constexpr]
Definition at line 75 of file interface-descriptors-inl.h.
                                                                          {
  return CallInterfaceDescriptor::DefaultReturnDoubleRegisterArray();
}
References v8::internal::CallInterfaceDescriptor::DefaultReturnDoubleRegisterArray().
return_registers()
template<typename DerivedDescriptor >
constexpr auto v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::return_registers [inline], [static], [constexpr]
Definition at line 68 of file interface-descriptors-inl.h.
                                                                   {
  return CallInterfaceDescriptor::DefaultReturnRegisterArray();
}
References v8::internal::CallInterfaceDescriptor::DefaultReturnRegisterArray().
Friends And Related Function Documentation
CallDescriptors
template<typename DerivedDescriptor >
friend class CallDescriptors [friend]
Definition at line 580 of file interface-descriptors.h.
Member Data Documentation
kAllowVarArgs
template<typename DerivedDescriptor >
constexpr bool v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kAllowVarArgs = false [static], [constexpr]
Definition at line 497 of file interface-descriptors.h.
kCalleeSaveRegisters
template<typename DerivedDescriptor >
constexpr bool v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kCalleeSaveRegisters = false [static], [constexpr]
Definition at line 523 of file interface-descriptors.h.
kCustomMachineTypes
template<typename DerivedDescriptor >
constexpr bool v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kCustomMachineTypes = false [static], [constexpr]
Definition at line 527 of file interface-descriptors.h.
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::InitializeTypes().
kMaxRegisterParams
template<typename DerivedDescriptor >
constexpr int v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kMaxRegisterParams = kMaxBuiltinRegisterParams [static], [constexpr]
Definition at line 515 of file interface-descriptors.h.
kNoContext
template<typename DerivedDescriptor >
constexpr bool v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kNoContext = false [static], [constexpr]
Definition at line 496 of file interface-descriptors.h.
kNoStackScan
template<typename DerivedDescriptor >
constexpr bool v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kNoStackScan = false [static], [constexpr]
Definition at line 498 of file interface-descriptors.h.
kParameterCount
template<typename DerivedDescriptor >
constexpr int v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kParameterCount [static], [constexpr]
Initial value:
=
      CallInterfaceDescriptorData::kUninitializedCount
Definition at line 494 of file interface-descriptors.h.
kRestrictAllocatableRegisters
template<typename DerivedDescriptor >
constexpr bool v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kRestrictAllocatableRegisters = false [static], [constexpr]
Definition at line 520 of file interface-descriptors.h.
kReturnCount
template<typename DerivedDescriptor >
constexpr int v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kReturnCount [static], [constexpr]
Initial value:
=
      CallInterfaceDescriptorData::kUninitializedCount
Definition at line 492 of file interface-descriptors.h.
kStackArgumentOrder
template<typename DerivedDescriptor >
constexpr auto v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::kStackArgumentOrder = StackArgumentOrder::kDefault [static], [constexpr]
Definition at line 499 of file interface-descriptors.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h