v8::internal::Foreign Class Reference
#include <foreign.h>
Public Types
using BodyDescriptor = StackedBodyDescriptor< FixedBodyDescriptorFor< Foreign >, WithExternalPointer< kForeignAddressOffset, kAnyForeignExternalPointerTagRange > >
Public Member Functions
template<ExternalPointerTag tag>
Address foreign_address (IsolateForSandbox isolate) const
template<ExternalPointerTag tag>
Address foreign_address () const
template<ExternalPointerTag tag>
void set_foreign_address (IsolateForSandbox isolate, const Address value)
template<ExternalPointerTag tag>
void init_foreign_address (IsolateForSandbox isolate, const Address initial_value)
Address foreign_address_unchecked (IsolateForSandbox isolate) const
Address foreign_address_unchecked () const
ExternalPointerTag GetTag () const
Detailed Description
Definition at line 19 of file foreign.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::Foreign::BodyDescriptor = StackedBodyDescriptor< FixedBodyDescriptorFor<Foreign>, WithExternalPointer<kForeignAddressOffset, kAnyForeignExternalPointerTagRange> >
Definition at line 56 of file foreign.h.
Member Function Documentation
foreign_address() [1/2]
template<ExternalPointerTag tag>
Address v8::internal::Foreign::foreign_address [inline]
Definition at line 34 of file foreign-inl.h.
                                       {
  IsolateForSandbox isolate = GetCurrentIsolateForSandbox();
  return ReadExternalPointerField<tag>(kForeignAddressOffset, isolate);
}
References v8::internal::GetCurrentIsolateForSandbox().
foreign_address() [2/2]
template<ExternalPointerTag tag>
Address v8::internal::Foreign::foreign_address (IsolateForSandbox isolate) const [inline]
Definition at line 28 of file foreign-inl.h.
                                                                {
  return HeapObject::ReadExternalPointerField<tag>(kForeignAddressOffset,
                                                   isolate);
}
foreign_address_unchecked() [1/2]
Address v8::internal::Foreign::foreign_address_unchecked () const [inline]
Definition at line 56 of file foreign-inl.h.
                                                 {
  IsolateForSandbox isolate = GetCurrentIsolateForSandbox();
  return foreign_address_unchecked(isolate);
}
References v8::internal::GetCurrentIsolateForSandbox().
foreign_address_unchecked() [2/2]
Address v8::internal::Foreign::foreign_address_unchecked (IsolateForSandbox isolate) const [inline]
Definition at line 51 of file foreign-inl.h.
                                                                          {
  return ReadExternalPointerField<kAnyForeignExternalPointerTagRange>(
      kForeignAddressOffset, isolate);
}
GetTag()
ExternalPointerTag v8::internal::Foreign::GetTag () const [inline]
Definition at line 61 of file foreign-inl.h.
                                         {
#ifdef V8_ENABLE_SANDBOX
  ExternalPointerHandle handle =
      RawExternalPointerField(kForeignAddressOffset,
                              kAnyForeignExternalPointerTagRange)
          .Relaxed_LoadHandle();
  IsolateForSandbox isolate = GetCurrentIsolateForSandbox();
  return isolate.GetExternalPointerTableTagFor(*this, handle);
#endif // V8_ENABLE_SANDBOX
  // Without the sandbox the address is stored untagged.
  return kExternalPointerNullTag;
}
References v8::internal::GetCurrentIsolateForSandbox(), v8::internal::handle(), v8::internal::kAnyForeignExternalPointerTagRange(), and v8::internal::kExternalPointerNullTag.
init_foreign_address()
template<ExternalPointerTag tag>
void v8::internal::Foreign::init_foreign_address (IsolateForSandbox isolate, const Address initial_value) [inline]
Definition at line 46 of file foreign-inl.h.
                                                                {
  InitExternalPointerField<tag>(kForeignAddressOffset, isolate, initial_value);
}
set_foreign_address()
template<ExternalPointerTag tag>
void v8::internal::Foreign::set_foreign_address (IsolateForSandbox isolate, const Address value) [inline]
Definition at line 40 of file foreign-inl.h.
                                                       {
  WriteExternalPointerField<tag>(kForeignAddressOffset, isolate, value);
}
References v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/foreign.h
/mnt/V8SourceCode/src/objects/foreign-inl.h