v8::internal::wasm::DebugInfo Class Reference
#include <wasm-debug.h>
Public Member Functions
DebugInfo (NativeModule *)
~DebugInfo ()
int GetNumLocals (Address pc, Isolate *isolate)
WasmValue GetLocalValue (int local, Address pc, Address fp, Address debug_break_fp, Isolate *isolate)
int GetStackDepth (Address pc, Isolate *isolate)
const wasm::WasmFunction & GetFunctionAtAddress (Address pc, Isolate *isolate)
WasmValue GetStackValue (int index, Address pc, Address fp, Address debug_break_fp, Isolate *isolate)
void SetBreakpoint (int func_index, int offset, Isolate *current_isolate)
bool IsFrameBlackboxed (WasmFrame *frame)
bool PrepareStep (WasmFrame *)
void PrepareStepOutTo (WasmFrame *)
void ClearStepping (Isolate *)
void ClearStepping (WasmFrame *)
bool IsStepping (WasmFrame *)
void RemoveBreakpoint (int func_index, int offset, Isolate *current_isolate)
void RemoveDebugSideTables (base::Vector< WasmCode *const >)
DebugSideTable * GetDebugSideTableIfExists (const WasmCode *) const
void RemoveIsolate (Isolate *)
size_t EstimateCurrentMemoryConsumption () const
Private Attributes
std::unique_ptr< DebugInfoImpl > impl_
Detailed Description
Definition at line 173 of file wasm-debug.h.
Constructor & Destructor Documentation
DebugInfo()
v8::internal::wasm::DebugInfo::DebugInfo (NativeModule * native_module) [explicit]
Definition at line 818 of file wasm-debug.cc.
    : impl_(std::make_unique<DebugInfoImpl>(native_module)) {}
 DebugInfo()
v8::internal::wasm::DebugInfo::~DebugInfo () [default]
Member Function Documentation
ClearStepping() [1/2]
void v8::internal::wasm::DebugInfo::ClearStepping (Isolate * isolate)
Definition at line 863 of file wasm-debug.cc.
                                              {
  impl_->ClearStepping(isolate);
}
References impl_.
ClearStepping() [2/2]
void v8::internal::wasm::DebugInfo::ClearStepping (WasmFrame * frame)
Definition at line 867 of file wasm-debug.cc.
{ impl_->ClearStepping(frame); }
References impl_.
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::DebugInfo::EstimateCurrentMemoryConsumption () const
Definition at line 891 of file wasm-debug.cc.
                                                         {
  return impl_->EstimateCurrentMemoryConsumption();
}
References impl_.
Referenced by v8::internal::wasm::NativeModule::EstimateCurrentMemoryConsumption().
GetDebugSideTableIfExists()
DebugSideTable * v8::internal::wasm::DebugInfo::GetDebugSideTableIfExists (const WasmCode * code) const
Definition at line 882 of file wasm-debug.cc.
                                {
  return impl_->GetDebugSideTableIfExists(code);
}
References code, and impl_.
Referenced by v8::internal::wasm::WasmCode::Print().
GetFunctionAtAddress()
const wasm::WasmFunction & v8::internal::wasm::DebugInfo::GetFunctionAtAddress (Address pc, Isolate * isolate)
Definition at line 841 of file wasm-debug.cc.
                                                                            {
  return impl_->GetFunctionAtAddress(pc, isolate);
}
References impl_.
GetLocalValue()
WasmValue v8::internal::wasm::DebugInfo::GetLocalValue (int local, Address pc, Address fp, Address debug_break_fp, Isolate * isolate)
Definition at line 827 of file wasm-debug.cc.
                                                                             {
  return impl_->GetLocalValue(local, pc, fp, debug_break_fp, isolate);
}
References impl_.
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal().
GetNumLocals()
int v8::internal::wasm::DebugInfo::GetNumLocals (Address pc, Isolate * isolate)
Definition at line 823 of file wasm-debug.cc.
                                                        {
  return impl_->GetNumLocals(pc, isolate);
}
References impl_.
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal().
GetStackDepth()
int v8::internal::wasm::DebugInfo::GetStackDepth (Address pc, Isolate * isolate)
Definition at line 832 of file wasm-debug.cc.
                                                         {
  return impl_->GetStackDepth(pc, isolate);
}
References impl_.
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue().
GetStackValue()
WasmValue v8::internal::wasm::DebugInfo::GetStackValue (int index, Address pc, Address fp, Address debug_break_fp, Isolate * isolate)
Definition at line 836 of file wasm-debug.cc.
                                                                             {
  return impl_->GetStackValue(index, pc, fp, debug_break_fp, isolate);
}
References impl_, and v8::internal::index.
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue().
IsFrameBlackboxed()
bool v8::internal::wasm::DebugInfo::IsFrameBlackboxed (WasmFrame * frame)
Definition at line 851 of file wasm-debug.cc.
                                                  {
  return impl_->IsFrameBlackboxed(frame);
}
References impl_.
IsStepping()
bool v8::internal::wasm::DebugInfo::IsStepping (WasmFrame * frame)
Definition at line 869 of file wasm-debug.cc.
                                           {
  return impl_->IsStepping(frame);
}
References impl_.
PrepareStep()
bool v8::internal::wasm::DebugInfo::PrepareStep (WasmFrame * frame)
Definition at line 855 of file wasm-debug.cc.
                                            {
  return impl_->PrepareStep(frame);
}
References impl_.
PrepareStepOutTo()
void v8::internal::wasm::DebugInfo::PrepareStepOutTo (WasmFrame * frame)
Definition at line 859 of file wasm-debug.cc.
                                                 {
  impl_->PrepareStepOutTo(frame);
}
References impl_.
RemoveBreakpoint()
void v8::internal::wasm::DebugInfo::RemoveBreakpoint (int func_index, int offset, Isolate * current_isolate)
Definition at line 873 of file wasm-debug.cc.
                                                           {
  impl_->RemoveBreakpoint(func_index, offset, current_isolate);
}
References impl_.
Referenced by v8::internal::WasmScript::ClearBreakPoint().
RemoveDebugSideTables()
void v8::internal::wasm::DebugInfo::RemoveDebugSideTables (base::Vector< WasmCode *const > code)
Definition at line 878 of file wasm-debug.cc.
                                                                      {
  impl_->RemoveDebugSideTables(code);
}
References code, and impl_.
Referenced by v8::internal::wasm::NativeModule::FreeCode().
RemoveIsolate()
void v8::internal::wasm::DebugInfo::RemoveIsolate (Isolate * isolate)
Definition at line 887 of file wasm-debug.cc.
                                              {
  return impl_->RemoveIsolate(isolate);
}
References impl_.
SetBreakpoint()
void v8::internal::wasm::DebugInfo::SetBreakpoint (int func_index, int offset, Isolate * current_isolate)
Definition at line 846 of file wasm-debug.cc.
                                                        {
  impl_->SetBreakpoint(func_index, offset, current_isolate);
}
References impl_.
Referenced by v8::internal::WasmScript::SetBreakPointForFunction().
Member Data Documentation
impl_
std::unique_ptr<DebugInfoImpl> v8::internal::wasm::DebugInfo::impl_ [private]
Definition at line 222 of file wasm-debug.h.
Referenced by ClearStepping(), EstimateCurrentMemoryConsumption(), GetDebugSideTableIfExists(), GetFunctionAtAddress(), GetLocalValue(), GetNumLocals(), GetStackDepth(), GetStackValue(), IsFrameBlackboxed(), IsStepping(), PrepareStep(), PrepareStepOutTo(), RemoveBreakpoint(), RemoveDebugSideTables(), RemoveIsolate(), and SetBreakpoint().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-debug.h
/mnt/V8SourceCode/src/wasm/wasm-debug.cc