cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask Class Reference
Public Types
using Handle = SingleThreadedHandle
Public Member Functions
IncrementalSweepTask (SweeperImpl &sweeper, cppgc::TaskPriority priority)
void Run () override
Static Public Member Functions
static Handle Post (SweeperImpl &sweeper, const std::shared_ptr< cppgc::TaskRunner > &runner, cppgc::TaskPriority priority, std::optional< v8::base::TimeDelta > delay={})
Static Public Attributes
static constexpr auto kMaxSweepDuration
Private Attributes
SweeperImpl & sweeper_
Handle handle_
cppgc::TaskPriority priority_
Detailed Description
Definition at line 1441 of file sweeper.cc.
Member Typedef Documentation
Handle
using cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::Handle = SingleThreadedHandle
Definition at line 1443 of file sweeper.cc.
Constructor & Destructor Documentation
IncrementalSweepTask()
cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::IncrementalSweepTask (SweeperImpl & sweeper, cppgc::TaskPriority priority) [inline]
Definition at line 1448 of file sweeper.cc.
        : sweeper_(sweeper),
          handle_(Handle::NonEmptyTag{}),
          priority_(priority) {}
Member Function Documentation
Post()
static Handle cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::Post (SweeperImpl & sweeper, const std::shared_ptr< cppgc::TaskRunner > & runner, cppgc::TaskPriority priority, std::optional< v8::base::TimeDelta > delay = {}) [inline], [static]
Definition at line 1453 of file sweeper.cc.
                                                            {}) {
      auto task = std::make_unique<IncrementalSweepTask>(sweeper, priority);
      auto handle = task->handle_;
      if (delay.has_value()) {
        runner->PostNonNestableDelayedTask(std::move(task),
                                           delay->InSecondsF());
      } else {
        runner->PostNonNestableTask(std::move(task));
      }
      return handle;
    }
Run()
void cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::Run () [inline], [override], [virtual]
Implements v8::Task.
Definition at line 1468 of file sweeper.cc.
                        {
      if (handle_.IsCanceled()) {
        return;
      }
      switch (priority_) {
        case kForegroundRegularPriority:
          sweeper_.SweepForTask(kMaxSweepDuration);
          return;
        case kForegroundLowPriority:
          sweeper_.SweepForLowPriorityTask(kMaxSweepDuration);
          return;
        default:
          UNREACHABLE();
      }
    }
References handle_, cppgc::internal::SingleThreadedHandle::IsCanceled(), cppgc::internal::anonymous_namespace{sweeper.cc}::kForegroundLowPriority, cppgc::internal::anonymous_namespace{sweeper.cc}::kForegroundRegularPriority, kMaxSweepDuration, priority_, sweeper_, cppgc::internal::Sweeper::SweeperImpl::SweepForLowPriorityTask(), cppgc::internal::Sweeper::SweeperImpl::SweepForTask(), and UNREACHABLE.
Member Data Documentation
handle_
Handle cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::handle_ [private]
Definition at line 1487 of file sweeper.cc.
Referenced by Run().
kMaxSweepDuration
constexpr auto cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::kMaxSweepDuration [static], [constexpr]
Initial value:
=
        v8::base::TimeDelta::FromMilliseconds(5)
Definition at line 1445 of file sweeper.cc.
Referenced by Run().
priority_
cppgc::TaskPriority cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::priority_ [private]
Definition at line 1488 of file sweeper.cc.
Referenced by Run().
sweeper_
SweeperImpl& cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::sweeper_ [private]
Definition at line 1485 of file sweeper.cc.
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc