v8::internal::StateBase Class Reference
Public Types
enum class Visibility { kHidden
, kDependentVisibility
, kVisible
 }
Public Member Functions
StateBase (const void *key, size_t state_count, Visibility visibility, EmbedderNode *node, bool visited)
virtual ~StateBase ()=default
bool IsVisited () const
bool IsPending () const
bool IsVisibleNotDependent ()
void set_node (EmbedderNode *node)
EmbedderNode * get_node ()
Protected Member Functions
Visibility GetVisibility ()
StateBase * FollowDependencies ()
Protected Attributes
const void * key_
const size_t state_count_
Visibility visibility_
StateBase * visibility_dependency_ = nullptr
EmbedderNode * node_
bool visited_
bool pending_ = false
Friends
class State
Detailed Description
Definition at line 105 of file cpp-snapshot.cc.
Member Enumeration Documentation
Visibility
enum v8::internal::StateBase::Visibility [strong]
Enumerator
kHidden
kDependentVisibility
kVisible
Definition at line 109 of file cpp-snapshot.cc.
                        {
    kHidden,
    kDependentVisibility,
    kVisible,
  };
Constructor & Destructor Documentation
StateBase()
v8::internal::StateBase::StateBase (const void * key, size_t state_count, Visibility visibility, EmbedderNode * node, bool visited) [inline]
Definition at line 115 of file cpp-snapshot.cc.
      : key_(key),
        state_count_(state_count),
        visibility_(visibility),
        node_(node),
        visited_(visited) {
    DCHECK_NE(Visibility::kDependentVisibility, visibility);
  }
References DCHECK_NE, and kDependentVisibility.
 StateBase()
virtual v8::internal::StateBase::~StateBase () [virtual], [default]
Member Function Documentation
FollowDependencies()
StateBase* v8::internal::StateBase::FollowDependencies () [inline], [protected]
Definition at line 168 of file cpp-snapshot.cc.
                                  {
    if (visibility_ != Visibility::kDependentVisibility) {
      CHECK_NULL(visibility_dependency_);
      return this;
    }
    StateBase* current = this;
    std::vector<StateBase*> dependencies;
    while (current->visibility_dependency_ &&
           current->visibility_dependency_ != current) {
      DCHECK_EQ(Visibility::kDependentVisibility, current->visibility_);
      dependencies.push_back(current);
      current = current->visibility_dependency_;
    }
    auto new_visibility = Visibility::kDependentVisibility;
    auto* new_visibility_dependency = current;
    if (current->visibility_ == Visibility::kVisible) {
      new_visibility = Visibility::kVisible;
      new_visibility_dependency = nullptr;
    } else if (!IsPending()) {
      DCHECK(IsVisited());
      // The object was not visible (above case). Having a dependency on itself
      // or null means no visible object was found.
      new_visibility = Visibility::kHidden;
      new_visibility_dependency = nullptr;
    }
    current->visibility_ = new_visibility;
    current->visibility_dependency_ = new_visibility_dependency;
    for (auto* state : dependencies) {
      state->visibility_ = new_visibility;
      state->visibility_dependency_ = new_visibility_dependency;
    }
    return current;
  }
References CHECK_NULL, v8::internal::DCHECK(), DCHECK_EQ, IsPending(), IsVisited(), kDependentVisibility, kHidden, kVisible, visibility_, and visibility_dependency_.
Referenced by GetVisibility(), and v8::internal::State::MarkDependentVisibility().
get_node()
EmbedderNode* v8::internal::StateBase::get_node () [inline]
Definition at line 145 of file cpp-snapshot.cc.
                           {
    CHECK_EQ(Visibility::kVisible, GetVisibility());
    return node_;
  }
References CHECK_EQ, GetVisibility(), kVisible, and node_.
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), v8::internal::CppGraphBuilderImpl::AddEdgeForCppHeapExternalObject(), and v8::internal::CppGraphBuilderImpl::AddRootEdge().
GetVisibility()
Visibility v8::internal::StateBase::GetVisibility () [inline], [protected]
Definition at line 163 of file cpp-snapshot.cc.
                             {
    FollowDependencies();
    return visibility_;
  }
References FollowDependencies(), and visibility_.
Referenced by get_node(), IsVisibleNotDependent(), and set_node().
IsPending()
bool v8::internal::StateBase::IsPending () const [inline]
Definition at line 131 of file cpp-snapshot.cc.
{ return pending_; }
References pending_.
Referenced by FollowDependencies(), and v8::internal::State::MarkDependentVisibility().
IsVisibleNotDependent()
bool v8::internal::StateBase::IsVisibleNotDependent () [inline]
Definition at line 133 of file cpp-snapshot.cc.
                               {
    auto v = GetVisibility();
    CHECK_NE(Visibility::kDependentVisibility, v);
    return v == Visibility::kVisible;
  }
References CHECK_NE, GetVisibility(), kDependentVisibility, and kVisible.
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), v8::internal::CppGraphBuilderImpl::AddEdgeForCppHeapExternalObject(), v8::internal::CppGraphBuilderImpl::AddRootEdge(), v8::internal::CppGraphBuilderImpl::Run(), and v8::internal::CppGraphBuilderImpl::VisitRootForGraphBuilding().
IsVisited()
bool v8::internal::StateBase::IsVisited () const [inline]
Definition at line 128 of file cpp-snapshot.cc.
{ return visited_; }
References visited_.
Referenced by FollowDependencies(), and v8::internal::State::MarkDependentVisibility().
set_node()
void v8::internal::StateBase::set_node (EmbedderNode * node) [inline]
Definition at line 139 of file cpp-snapshot.cc.
                                    {
    CHECK_EQ(Visibility::kVisible, GetVisibility());
    DCHECK_NULL(node_);
    node_ = node;
  }
References CHECK_EQ, DCHECK_NULL, GetVisibility(), kVisible, and node_.
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), v8::internal::CppGraphBuilderImpl::AddEdgeForCppHeapExternalObject(), and v8::internal::CppGraphBuilderImpl::AddRootEdge().
Friends And Related Function Documentation
State
friend class State [friend]
Definition at line 202 of file cpp-snapshot.cc.
Member Data Documentation
key_
const void* v8::internal::StateBase::key_ [protected]
Definition at line 151 of file cpp-snapshot.cc.
Referenced by v8::internal::State::header().
node_
EmbedderNode* v8::internal::StateBase::node_ [protected]
Definition at line 159 of file cpp-snapshot.cc.
Referenced by get_node(), and set_node().
pending_
bool v8::internal::StateBase::pending_ = false [protected]
Definition at line 161 of file cpp-snapshot.cc.
Referenced by IsPending(), v8::internal::State::MarkPending(), and v8::internal::State::UnmarkPending().
state_count_
const size_t v8::internal::StateBase::state_count_ [protected]
Definition at line 155 of file cpp-snapshot.cc.
Referenced by v8::internal::StateStorage::CreateRootState(), v8::internal::StateStorage::GetOrCreateState(), and v8::internal::State::MarkDependentVisibility().
visibility_
Visibility v8::internal::StateBase::visibility_ [protected]
Definition at line 157 of file cpp-snapshot.cc.
Referenced by FollowDependencies(), GetVisibility(), v8::internal::State::MarkDependentVisibility(), and v8::internal::State::MarkVisible().
visibility_dependency_
StateBase* v8::internal::StateBase::visibility_dependency_ = nullptr [protected]
Definition at line 158 of file cpp-snapshot.cc.
Referenced by FollowDependencies(), v8::internal::State::MarkDependentVisibility(), and v8::internal::State::MarkVisible().
visited_
bool v8::internal::StateBase::visited_ [protected]
Definition at line 160 of file cpp-snapshot.cc.
Referenced by IsVisited(), and v8::internal::State::MarkVisited().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-snapshot.cc