v8::debug::ConsoleDelegate Class Reference
#include <interface-types.h>
Public Member Functions
virtual void Debug (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Error (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Info (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Log (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Warn (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Dir (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void DirXml (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Table (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Trace (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Group (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void GroupCollapsed (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void GroupEnd (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Clear (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Count (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void CountReset (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Assert (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Profile (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void ProfileEnd (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void Time (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void TimeLog (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void TimeEnd (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual void TimeStamp (const ConsoleCallArguments &args, const ConsoleContext &context)
virtual ~ConsoleDelegate ()=default
Detailed Description
Definition at line 135 of file interface-types.h.
Constructor & Destructor Documentation
 ConsoleDelegate()
virtual v8::debug::ConsoleDelegate::~ConsoleDelegate () [virtual], [default]
Member Function Documentation
Assert()
virtual void v8::debug::ConsoleDelegate::Assert (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 167 of file interface-types.h.
                                                     {}
Clear()
virtual void v8::debug::ConsoleDelegate::Clear (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 161 of file interface-types.h.
                                                    {}
Count()
virtual void v8::debug::ConsoleDelegate::Count (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 163 of file interface-types.h.
                                                    {}
CountReset()
virtual void v8::debug::ConsoleDelegate::CountReset (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 165 of file interface-types.h.
                                                         {}
Debug()
virtual void v8::debug::ConsoleDelegate::Debug (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 137 of file interface-types.h.
                                                    {}
Dir()
virtual void v8::debug::ConsoleDelegate::Dir (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 147 of file interface-types.h.
                                                  {}
DirXml()
virtual void v8::debug::ConsoleDelegate::DirXml (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 149 of file interface-types.h.
                                                     {}
Error()
virtual void v8::debug::ConsoleDelegate::Error (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 139 of file interface-types.h.
                                                    {}
Group()
virtual void v8::debug::ConsoleDelegate::Group (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 155 of file interface-types.h.
                                                    {}
GroupCollapsed()
virtual void v8::debug::ConsoleDelegate::GroupCollapsed (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 157 of file interface-types.h.
                                                             {}
GroupEnd()
virtual void v8::debug::ConsoleDelegate::GroupEnd (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 159 of file interface-types.h.
                                                       {}
Info()
virtual void v8::debug::ConsoleDelegate::Info (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 141 of file interface-types.h.
                                                   {}
Log()
virtual void v8::debug::ConsoleDelegate::Log (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 143 of file interface-types.h.
                                                  {}
Profile()
virtual void v8::debug::ConsoleDelegate::Profile (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 169 of file interface-types.h.
                                                      {}
ProfileEnd()
virtual void v8::debug::ConsoleDelegate::ProfileEnd (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 171 of file interface-types.h.
                                                         {}
Table()
virtual void v8::debug::ConsoleDelegate::Table (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console.
Definition at line 151 of file interface-types.h.
                                                    {}
Time()
virtual void v8::debug::ConsoleDelegate::Time (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 173 of file interface-types.h.
                                                   {}
Referenced by v8::internal::BUILTIN().
TimeEnd()
virtual void v8::debug::ConsoleDelegate::TimeEnd (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 177 of file interface-types.h.
                                                      {}
Referenced by v8::internal::BUILTIN().
TimeLog()
virtual void v8::debug::ConsoleDelegate::TimeLog (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 175 of file interface-types.h.
                                                      {}
Referenced by v8::internal::BUILTIN().
TimeStamp()
virtual void v8::debug::ConsoleDelegate::TimeStamp (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 179 of file interface-types.h.
                                                        {}
Referenced by v8::internal::BUILTIN().
Trace()
virtual void v8::debug::ConsoleDelegate::Trace (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 153 of file interface-types.h.
                                                    {}
Warn()
virtual void v8::debug::ConsoleDelegate::Warn (const ConsoleCallArguments & args, const ConsoleContext & context) [inline], [virtual]
Reimplemented in v8_inspector::V8Console, and v8::D8Console.
Definition at line 145 of file interface-types.h.
                                                   {}
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/interface-types.h