v8::internal::compiler::turboshaft::WasmRevecAnalyzer Class Reference
#include <wasm-revec-reducer.h>
Public Member Functions
WasmRevecAnalyzer (PipelineData *data, Zone *zone, Graph &graph)
void Run ()
void MergeSLPTree (SLPTree &slp_tree)
bool ShouldReduce () const
PackNode * GetPackNode (const OpIndex ig_index)
ZoneVector< PackNode * > * GetIntersectPackNodes (const OpIndex node)
const OpIndex GetReducedInput (const PackNode *pnode, const int index=0)
const Operation & GetStartOperation (const PackNode *pnode, const OpIndex node, const Operation &op)
base::Vector< const OpIndex > uses (OpIndex node)
Private Member Functions
bool IsSupportedReduceSeed (const Operation &op)
void ProcessBlock (const Block &block)
bool DecideVectorize ()
void Print (const char *info)
Private Attributes
PipelineData * data_
Graph & graph_
Zone * phase_zone_
ZoneVector< std::pair< OpIndex, OpIndex > > store_seeds_
ZoneVector< std::pair< OpIndex, OpIndex > > reduce_seeds_
const wasm::WasmModule * module_ = data_->wasm_module()
ZoneUnorderedMap< OpIndex, PackNode * > revectorizable_node_
ZoneUnorderedMap< OpIndex, ZoneVector< PackNode * > > revectorizable_intersect_node_
bool should_reduce_
Simd128UseMap * use_map_
Detailed Description
Definition at line 586 of file wasm-revec-reducer.h.
Constructor & Destructor Documentation
WasmRevecAnalyzer()
v8::internal::compiler::turboshaft::WasmRevecAnalyzer::WasmRevecAnalyzer (PipelineData * data, Zone * zone, Graph & graph) [inline]
Definition at line 588 of file wasm-revec-reducer.h.
      : data_(data),
        graph_(graph),
        phase_zone_(zone),
        store_seeds_(zone),
        reduce_seeds_(zone),
        revectorizable_node_(zone),
        revectorizable_intersect_node_(zone),
        should_reduce_(false),
        use_map_(nullptr) {
    Run();
  }
References Run().
Member Function Documentation
DecideVectorize()
bool v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize () [private]
Definition at line 1490 of file wasm-revec-reducer.cc.
                                        {
  TRACE("Enter %s\n", __func__);
  int save = 0, cost = 0;
  ForEach(
      [&](PackNode const* pnode) {
        const NodeGroup& nodes = pnode->nodes();
        // An additional store is emitted in case of OOB trap at the higher
        // 128-bit address. Thus no save if the store at lower address is
        // executed first. Return directly as we dont need to check external use
        // for stores.
        if (graph_.Get(nodes[0]).opcode == Opcode::kStore) {
          if (nodes[0] > nodes[1]) save++;
          return;
        }
        if (pnode->IsForcePackNode()) {
          cost++;
          return;
        }
        // Splat nodes will not cause a saving as it simply extends itself.
        if (!IsSplat(nodes)) {
          save++;
        }
#ifdef V8_TARGET_ARCH_X64
        // On x64 platform, we dont emit extract for lane 0 as the source ymm
        // register is alias to the corresponding xmm register in lower 128-bit.
        for (int i = 1; i < static_cast<int>(nodes.size()); i++) {
          if (nodes[i] == nodes[0]) continue;
#else
        for (int i = 0; i < static_cast<int>(nodes.size()); i++) {
          if (i > 0 && nodes[i] == nodes[0]) continue;
#endif // V8_TARGET_ARCH_X64
          for (auto use : use_map_->uses(nodes[i])) {
            if (!GetPackNode(use) || GetPackNode(use)->is_force_packing()) {
              TRACE("External use edge: (%d:%s) -> (%d:%s)\n", use.id(),
                    OpcodeName(graph_.Get(use).opcode), nodes[i].id(),
                    OpcodeName(graph_.Get(nodes[i]).opcode));
              ++cost;
              // We only need one Extract node and all other uses can share.
              break;
            }
          }
        }
      },
      revectorizable_node_);
  ForEach(
      [&](PackNode const* pnode) {
        // We always generate SimdPack128To256Op for IntersectPackNode.
        cost++;
        return;
      },
      revectorizable_intersect_node_);
  TRACE("Save: %d, cost: %d\n", save, cost);
  return save > cost;
}
References v8::internal::compiler::turboshaft::ForEach(), v8::internal::compiler::turboshaft::Graph::Get(), GetPackNode(), graph_, v8::internal::compiler::if(), v8::internal::compiler::turboshaft::PackNode::is_force_packing(), v8::internal::compiler::turboshaft::PackNode::IsForcePackNode(), v8::internal::compiler::turboshaft::IsSplat(), v8::internal::compiler::turboshaft::PackNode::nodes(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::OpcodeName(), revectorizable_intersect_node_, revectorizable_node_, v8::internal::compiler::turboshaft::NodeGroup::size(), v8::internal::TRACE(), use(), use_map_, and v8::internal::compiler::turboshaft::UseMap::uses().
Referenced by Run().
GetIntersectPackNodes()
ZoneVector<PackNode*>* v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetIntersectPackNodes (const OpIndex node) [inline]
Definition at line 614 of file wasm-revec-reducer.h.
                                                                   {
    auto I = revectorizable_intersect_node_.find(node);
    if (I != revectorizable_intersect_node_.end()) {
      return &(I->second);
    }
    return nullptr;
  }
References v8::internal::I, and revectorizable_intersect_node_.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation().
GetPackNode()
PackNode* v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode (const OpIndex ig_index) [inline]
Definition at line 606 of file wasm-revec-reducer.h.
                                                {
    auto itr = revectorizable_node_.find(ig_index);
    if (itr != revectorizable_node_.end()) {
      return itr->second;
    }
    return nullptr;
  }
References revectorizable_node_.
Referenced by DecideVectorize(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::SLPTree::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Constant(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Splat(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
GetReducedInput()
const OpIndex v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput (const PackNode * pnode, const int index = 0) [inline]
Definition at line 622 of file wasm-revec-reducer.h.
                                                                            {
    if (index >= static_cast<int>(pnode->GetOperandsSize())) {
      return OpIndex::Invalid();
    }
    return pnode->GetOperand(index)->RevectorizedNode();
  }
References v8::internal::compiler::turboshaft::PackNode::GetOperand(), v8::internal::compiler::turboshaft::PackNode::GetOperandsSize(), v8::internal::index, v8::internal::compiler::turboshaft::OpIndex::Invalid(), and v8::internal::compiler::turboshaft::PackNode::RevectorizedNode().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
GetStartOperation()
const Operation& v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetStartOperation (const PackNode * pnode, const OpIndex node, const Operation & op) [inline]
Definition at line 629 of file wasm-revec-reducer.h.
                                                          {
    DCHECK(pnode);
    const OpIndex start = pnode->nodes()[0];
    return (start == node) ? op : graph_.Get(start);
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, and v8::internal::compiler::turboshaft::PackNode::nodes().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
IsSupportedReduceSeed()
bool v8::internal::compiler::turboshaft::WasmRevecAnalyzer::IsSupportedReduceSeed (const Operation & op) [private]
Definition at line 1364 of file wasm-revec-reducer.cc.
                                                                 {
  if (!op.Is<Simd128BinopOp>()) {
    return false;
  }
  switch (op.Cast<Simd128BinopOp>().kind) {
#define CASE(op_128) case Simd128BinopOp::Kind::k##op_128:
    REDUCE_SEED_KIND(CASE) { return true; }
    default:
      return false;
  }
#undef CASE
}
References CASE, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Operation::Is(), and REDUCE_SEED_KIND.
Referenced by ProcessBlock().
MergeSLPTree()
void v8::internal::compiler::turboshaft::WasmRevecAnalyzer::MergeSLPTree (SLPTree & slp_tree)
Definition at line 1344 of file wasm-revec-reducer.cc.
                                                      {
  // We ensured the SLP trees are mergable when BuildTreeRec.
  for (const auto& entry : slp_tree.GetIntersectNodeMapping()) {
    auto it = revectorizable_intersect_node_.find(entry.first);
    if (it == revectorizable_intersect_node_.end()) {
      bool result;
      std::tie(it, result) = revectorizable_intersect_node_.emplace(
          entry.first, ZoneVector<PackNode*>(phase_zone_));
      DCHECK(result);
    }
    ZoneVector<PackNode*>& intersect_pnodes = it->second;
    intersect_pnodes.insert(intersect_pnodes.end(), entry.second.begin(),
                            entry.second.end());
    SLOW_DCHECK(std::unique(intersect_pnodes.begin(), intersect_pnodes.end()) ==
                intersect_pnodes.end());
  }
  revectorizable_node_.merge(slp_tree.GetNodeMapping());
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::turboshaft::SLPTree::GetIntersectNodeMapping(), v8::internal::compiler::turboshaft::SLPTree::GetNodeMapping(), v8::internal::ZoneVector< T >::insert(), phase_zone_, v8::base::internal::result, revectorizable_intersect_node_, revectorizable_node_, and SLOW_DCHECK.
Referenced by Run().
Print()
void v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Print (const char * info) [private]
Definition at line 1552 of file wasm-revec-reducer.cc.
                                              {
  if (!v8_flags.trace_wasm_revectorize) {
    return;
  }
  TRACE("%s, %zu revectorizable nodes:\n", info, revectorizable_node_.size());
  ForEach([this](PackNode const* pnode) { pnode->Print(&graph_); },
          revectorizable_node_);
  TRACE("%s, %zu revectorizable intersect nodes:\n", info,
        revectorizable_intersect_node_.size());
  ForEach([this](PackNode const* pnode) { pnode->Print(&graph_); },
          revectorizable_intersect_node_);
}
References v8::internal::compiler::turboshaft::ForEach(), graph_, v8::internal::compiler::turboshaft::PackNode::Print(), revectorizable_intersect_node_, revectorizable_node_, v8::internal::TRACE(), and v8::internal::v8_flags.
Referenced by Run().
ProcessBlock()
void v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock (const Block & block) [private]
Definition at line 1377 of file wasm-revec-reducer.cc.
                                                       {
  StoreInfoSet simd128_stores(phase_zone_);
  for (const Operation& op : base::Reversed(graph_.operations(block))) {
    if (const StoreOp* store_op = op.TryCast<StoreOp>()) {
      if (store_op->stored_rep == MemoryRepresentation::Simd128()) {
        StoreLoadInfo<StoreOp> info(&graph_, store_op);
        if (info.IsValid()) {
          simd128_stores.insert(info);
        }
      }
    }
    // Try to find reduce op which can be used as revec seeds.
    if (IsSupportedReduceSeed(op)) {
      const Simd128BinopOp& binop = op.Cast<Simd128BinopOp>();
      V<Simd128> left_index = binop.left();
      V<Simd128> right_index = binop.right();
      const Operation& left_op = graph_.Get(left_index);
      const Operation& right_op = graph_.Get(right_index);
      if (left_index != right_index && left_op.opcode == right_op.opcode &&
          IsSameOpAndKind(left_op, right_op)) {
        reduce_seeds_.push_back({left_index, right_index});
      }
    }
  }
  if (simd128_stores.size() >= 2) {
    for (auto it = std::next(simd128_stores.cbegin()),
              end = simd128_stores.cend();
         it != end;) {
      const StoreLoadInfo<StoreOp>& info0 = *std::prev(it);
      const StoreLoadInfo<StoreOp>& info1 = *it;
      auto diff = info1 - info0;
      if (diff.has_value()) {
        const OffsetDiff value = diff.value();
        DCHECK_EQ(value.negative(), false);
        if (value == kSimd128Size) {
          store_seeds_.push_back(
              {graph_.Index(*info0.op()), graph_.Index(*info1.op())});
          if (std::distance(it, end) < 2) {
            break;
          }
          std::advance(it, 2);
          continue;
        }
      }
      it++;
    }
  }
}
References DCHECK_EQ, v8::internal::compiler::end(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::compiler::turboshaft::IsSameOpAndKind(), IsSupportedReduceSeed(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::IsValid(), v8::internal::kSimd128Size, v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Graph::operations(), phase_zone_, reduce_seeds_, v8::base::Reversed(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), store_seeds_, v8::internal::compiler::turboshaft::Operation::TryCast(), and v8::internal::value.
Referenced by Run().
Run()
void v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run ()
Definition at line 1429 of file wasm-revec-reducer.cc.
                            {
  for (Block& block : base::Reversed(graph_.blocks())) {
    ProcessBlock(block);
  }
  if (store_seeds_.empty() && reduce_seeds_.empty()) {
    TRACE("Empty seed\n");
    return;
  }
  if (v8_flags.trace_wasm_revectorize) {
    PrintF("store seeds:\n");
    for (auto pair : store_seeds_) {
      PrintF("{\n");
      PrintF("#%u ", pair.first.id());
      graph_.Get(pair.first).Print();
      PrintF("#%u ", pair.second.id());
      graph_.Get(pair.second).Print();
      PrintF("}\n");
    }
    PrintF("reduce seeds:\n");
    for (auto pair : reduce_seeds_) {
      PrintF("{ ");
      PrintF("#%u, ", pair.first.id());
      PrintF("#%u ", pair.second.id());
      PrintF("}\n");
    }
  }
  ZoneVector<std::pair<OpIndex, OpIndex>> all_seeds(
      store_seeds_.begin(), store_seeds_.end(), phase_zone_);
  all_seeds.insert(all_seeds.end(), reduce_seeds_.begin(), reduce_seeds_.end());
  for (auto pair : all_seeds) {
    NodeGroup roots(pair.first, pair.second);
    SLPTree slp_tree(graph_, this, phase_zone_);
    PackNode* root = slp_tree.BuildTree(roots);
    if (!root) {
      TRACE("Build tree failed!\n");
      continue;
    }
    slp_tree.Print("After build tree");
    MergeSLPTree(slp_tree);
  }
  // Early exist when no revectorizable node found.
  if (revectorizable_node_.empty()) return;
  // Build SIMD usemap
  use_map_ = phase_zone_->New<Simd128UseMap>(graph_, phase_zone_);
  if (!DecideVectorize()) {
    revectorizable_node_.clear();
    revectorizable_intersect_node_.clear();
  } else {
    should_reduce_ = true;
    Print("Decide to vectorize");
  }
}
References v8::internal::compiler::turboshaft::Graph::blocks(), v8::internal::compiler::turboshaft::SLPTree::BuildTree(), DecideVectorize(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::ZoneVector< T >::insert(), MergeSLPTree(), v8::internal::Zone::New(), phase_zone_, v8::internal::compiler::turboshaft::Operation::Print(), v8::internal::compiler::turboshaft::SLPTree::Print(), Print(), v8::internal::PrintF(), ProcessBlock(), reduce_seeds_, revectorizable_intersect_node_, revectorizable_node_, v8::base::Reversed(), should_reduce_, store_seeds_, v8::internal::TRACE(), use_map_, and v8::internal::v8_flags.
Referenced by WasmRevecAnalyzer().
ShouldReduce()
bool v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ShouldReduce () const [inline]
Definition at line 604 of file wasm-revec-reducer.h.
{ return should_reduce_; }
References should_reduce_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecPhase::Run().
uses()
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::WasmRevecAnalyzer::uses (OpIndex node) [inline]
Definition at line 636 of file wasm-revec-reducer.h.
                                               {
    return use_map_->uses(node);
  }
References use_map_, and v8::internal::compiler::turboshaft::UseMap::uses().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded().
Member Data Documentation
data_
PipelineData* v8::internal::compiler::turboshaft::WasmRevecAnalyzer::data_ [private]
Definition at line 646 of file wasm-revec-reducer.h.
graph_
Graph& v8::internal::compiler::turboshaft::WasmRevecAnalyzer::graph_ [private]
Definition at line 647 of file wasm-revec-reducer.h.
Referenced by DecideVectorize(), GetStartOperation(), Print(), ProcessBlock(), and Run().
module_
const wasm::WasmModule* v8::internal::compiler::turboshaft::WasmRevecAnalyzer::module_ = data_->wasm_module() [private]
Definition at line 651 of file wasm-revec-reducer.h.
phase_zone_
Zone* v8::internal::compiler::turboshaft::WasmRevecAnalyzer::phase_zone_ [private]
Definition at line 648 of file wasm-revec-reducer.h.
Referenced by MergeSLPTree(), ProcessBlock(), and Run().
reduce_seeds_
ZoneVector<std::pair<OpIndex, OpIndex> > v8::internal::compiler::turboshaft::WasmRevecAnalyzer::reduce_seeds_ [private]
Definition at line 650 of file wasm-revec-reducer.h.
Referenced by ProcessBlock(), and Run().
revectorizable_intersect_node_
ZoneUnorderedMap<OpIndex, ZoneVector<PackNode*> > v8::internal::compiler::turboshaft::WasmRevecAnalyzer::revectorizable_intersect_node_ [private]
Definition at line 654 of file wasm-revec-reducer.h.
Referenced by DecideVectorize(), GetIntersectPackNodes(), MergeSLPTree(), Print(), and Run().
revectorizable_node_
ZoneUnorderedMap<OpIndex, PackNode*> v8::internal::compiler::turboshaft::WasmRevecAnalyzer::revectorizable_node_ [private]
Definition at line 652 of file wasm-revec-reducer.h.
Referenced by DecideVectorize(), GetPackNode(), MergeSLPTree(), Print(), and Run().
should_reduce_
bool v8::internal::compiler::turboshaft::WasmRevecAnalyzer::should_reduce_ [private]
Definition at line 655 of file wasm-revec-reducer.h.
Referenced by Run(), and ShouldReduce().
store_seeds_
ZoneVector<std::pair<OpIndex, OpIndex> > v8::internal::compiler::turboshaft::WasmRevecAnalyzer::store_seeds_ [private]
Definition at line 649 of file wasm-revec-reducer.h.
Referenced by ProcessBlock(), and Run().
use_map_
Simd128UseMap* v8::internal::compiler::turboshaft::WasmRevecAnalyzer::use_map_ [private]
Definition at line 656 of file wasm-revec-reducer.h.
Referenced by DecideVectorize(), Run(), and uses().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.cc