v8::internal::wasm::AsyncStreamingProcessor Class Reference
Public Member Functions
AsyncStreamingProcessor (AsyncCompileJob *job)
bool ProcessModuleHeader (base::Vector< const uint8_t > bytes) override
bool ProcessSection (SectionCode section_code, base::Vector< const uint8_t > bytes, uint32_t offset) override
bool ProcessCodeSectionHeader (int num_functions, uint32_t functions_mismatch_error_offset, std::shared_ptr< WireBytesStorage >, int code_section_start, int code_section_length) override
bool ProcessFunctionBody (base::Vector< const uint8_t > bytes, uint32_t offset) override
void OnFinishedChunk () override
void OnFinishedStream (base::OwnedVector< const uint8_t > bytes, bool after_error) override
void OnAbort () override
bool Deserialize (base::Vector< const uint8_t > wire_bytes, base::Vector< const uint8_t > module_bytes) override
Private Member Functions
void CommitCompilationUnits ()
Private Attributes
ModuleDecoder decoder_
AsyncCompileJob * job_
std::unique_ptr< CompilationUnitBuilder > compilation_unit_builder_
int num_functions_ = 0
bool prefix_cache_hit_ = false
bool before_code_section_ = true
ValidateFunctionsStreamingJobData validate_functions_job_data_
std::unique_ptr< JobHandle > validate_functions_job_handle_
base::Hasher prefix_hasher_
Detailed Description
Definition at line 2618 of file module-compiler.cc.
Constructor & Destructor Documentation
AsyncStreamingProcessor()
v8::internal::wasm::AsyncStreamingProcessor::AsyncStreamingProcessor (AsyncCompileJob * job) [explicit]
Definition at line 3227 of file module-compiler.cc.
    : decoder_(job->enabled_features_, &job->detected_features_),
      job_(job),
      compilation_unit_builder_(nullptr) {}
Member Function Documentation
CommitCompilationUnits()
void v8::internal::wasm::AsyncStreamingProcessor::CommitCompilationUnits () [private]
Definition at line 3376 of file module-compiler.cc.
                                                     {
  DCHECK(compilation_unit_builder_);
  compilation_unit_builder_->Commit();
}
References compilation_unit_builder_, and v8::internal::DCHECK().
Referenced by OnFinishedChunk(), and ProcessSection().
Deserialize()
bool v8::internal::wasm::AsyncStreamingProcessor::Deserialize (base::Vector< const uint8_t > wire_bytes, base::Vector< const uint8_t > module_bytes) [override], [virtual]
Implements v8::internal::wasm::StreamingProcessor.
Definition at line 3535 of file module-compiler.cc.
                                          {
  TRACE_EVENT0("v8.wasm", "wasm.Deserialize");
  std::optional<TimedHistogramScope> time_scope;
  if (base::TimeTicks::IsHighResolution()) {
    time_scope.emplace(job_->isolate()->counters()->wasm_deserialization_time(),
                       job_->isolate());
  }
  // DeserializeNativeModule and FinishCompile assume that they are executed in
  // a HandleScope, and that a context is set on the isolate.
  HandleScope scope(job_->isolate_);
  SaveAndSwitchContext saved_context(job_->isolate_, *job_->native_context_);
  MaybeDirectHandle<WasmModuleObject> result = DeserializeNativeModule(
      job_->isolate_, module_bytes, wire_bytes, job_->compile_imports_,
      base::VectorOf(job_->stream_->url()));
  if (result.is_null()) return false;
  job_->module_object_ =
      job_->isolate_->global_handles()->Create(*result.ToHandleChecked());
  job_->native_module_ = job_->module_object_->shared_native_module();
  job_->wire_bytes_ = ModuleWireBytes(job_->native_module_->wire_bytes());
  // Calling {FinishCompile} deletes the {AsyncCompileJob} and {this}.
  job_->FinishCompile(false);
  return true;
}
References v8::internal::wasm::AsyncCompileJob::compile_imports_, v8::internal::Isolate::counters(), v8::internal::GlobalHandles::Create(), v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::Isolate::global_handles(), v8::base::TimeTicks::IsHighResolution(), v8::internal::wasm::AsyncCompileJob::isolate(), v8::internal::wasm::AsyncCompileJob::isolate_, job_, v8::internal::wasm::AsyncCompileJob::module_object_, v8::internal::wasm::AsyncCompileJob::native_context_, v8::internal::wasm::AsyncCompileJob::native_module_, v8::base::internal::result, v8::internal::wasm::AsyncCompileJob::stream_, TRACE_EVENT0, v8::base::VectorOf(), and v8::internal::wasm::AsyncCompileJob::wire_bytes_.
OnAbort()
void v8::internal::wasm::AsyncStreamingProcessor::OnAbort () [override], [virtual]
Implements v8::internal::wasm::StreamingProcessor.
Definition at line 3520 of file module-compiler.cc.
                                      {
  TRACE_STREAMING("Abort stream...\n");
  if (validate_functions_job_handle_) {
    validate_functions_job_handle_->Cancel();
    validate_functions_job_handle_.reset();
  }
  if (job_->native_module_ && job_->native_module_->wire_bytes().empty()) {
    // Clean up the temporary cache entry.
    GetWasmEngine()->StreamingCompilationFailed(prefix_hasher_.hash(),
                                                job_->compile_imports_);
  }
  // {Abort} invalidates the {AsyncCompileJob}, which in turn deletes {this}.
  job_->Abort();
}
References v8::internal::wasm::AsyncCompileJob::Abort(), v8::internal::wasm::AsyncCompileJob::compile_imports_, v8::internal::wasm::GetWasmEngine(), v8::base::Hasher::hash(), job_, v8::internal::wasm::AsyncCompileJob::native_module_, prefix_hasher_, v8::internal::wasm::WasmEngine::StreamingCompilationFailed(), TRACE_STREAMING, and validate_functions_job_handle_.
OnFinishedChunk()
void v8::internal::wasm::AsyncStreamingProcessor::OnFinishedChunk () [override], [virtual]
Implements v8::internal::wasm::StreamingProcessor.
Definition at line 3381 of file module-compiler.cc.
                                              {
  TRACE_STREAMING("FinishChunk...\n");
  if (compilation_unit_builder_) CommitCompilationUnits();
}
References CommitCompilationUnits(), compilation_unit_builder_, and TRACE_STREAMING.
OnFinishedStream()
void v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream (base::OwnedVector< const uint8_t > bytes, bool after_error) [override], [virtual]
Implements v8::internal::wasm::StreamingProcessor.
Definition at line 3387 of file module-compiler.cc.
                                                            {
  TRACE_STREAMING("Finish stream...\n");
  ModuleResult module_result = decoder_.FinishDecoding();
  if (module_result.failed()) after_error = true;
  if (validate_functions_job_handle_) {
    // Wait for background validation to finish, then check if a validation
    // error was found.
    // TODO(13447): Do not block here; register validation as another finisher
    // instead.
    validate_functions_job_handle_->Join();
    validate_functions_job_handle_.reset();
    if (validate_functions_job_data_.found_error) after_error = true;
    job_->detected_features_ |=
        validate_functions_job_data_.detected_features.load(
            std::memory_order_relaxed);
  }
  job_->wire_bytes_ = ModuleWireBytes(bytes.as_vector());
  job_->bytes_copy_ = std::move(bytes);
  if (!after_error) {
    WasmDetectedFeatures detected_imports_features;
    if (WasmError error = ValidateAndSetBuiltinImports(
            module_result.value().get(), job_->wire_bytes_.module_bytes(),
            job_->compile_imports_, &detected_imports_features)) {
      after_error = true;
    } else {
      job_->detected_features_ |= detected_imports_features;
    }
  }
  // Record event metrics.
  auto duration = base::TimeTicks::Now() - job_->start_time_;
  job_->metrics_event_.success = !after_error;
  job_->metrics_event_.streamed = true;
  job_->metrics_event_.module_size_in_bytes = job_->wire_bytes_.length();
  job_->metrics_event_.function_count = num_functions_;
  job_->metrics_event_.wall_clock_duration_in_us = duration.InMicroseconds();
  job_->isolate_->metrics_recorder()->DelayMainThreadEvent(job_->metrics_event_,
                                                           job_->context_id_);
  if (after_error) {
    if (job_->native_module_ && job_->native_module_->wire_bytes().empty()) {
      // Clean up the temporary cache entry.
      GetWasmEngine()->StreamingCompilationFailed(prefix_hasher_.hash(),
                                                  job_->compile_imports_);
    }
    // Calling {Failed} will invalidate the {AsyncCompileJob} and delete {this}.
    job_->Failed();
    return;
  }
  std::shared_ptr<WasmModule> module = std::move(module_result).value();
  // At this point we identified the module as valid (except maybe for function
  // bodies, if lazy validation is enabled).
  // This DCHECK could be considered slow, but it only happens once per async
  // module compilation, and we only re-decode the module structure, without
  // validating function bodies. Overall this does not add a lot of overhead.
#ifdef DEBUG
  WasmDetectedFeatures detected_module_features;
  DCHECK(DecodeWasmModule(job_->enabled_features_,
                          job_->bytes_copy_.as_vector(),
                          /* validate functions */ false, kWasmOrigin,
                          &detected_module_features)
             .ok());
  // Module decoding should not detect any new features.
  DCHECK(job_->detected_features_.contains_all(detected_module_features));
#endif
  DCHECK_EQ(NativeModuleCache::PrefixHash(job_->wire_bytes_.module_bytes()),
            prefix_hasher_.hash());
  if (prefix_cache_hit_) {
    // Restart as an asynchronous, non-streaming compilation. Most likely
    // {PrepareAndStartCompile} will get the native module from the cache.
    size_t code_size_estimate =
        wasm::WasmCodeManager::EstimateNativeModuleCodeSize(module.get());
    job_->DoSync<AsyncCompileJob::PrepareAndStartCompile>(
        std::move(module), true /* start_compilation */,
        false /* lazy_functions_are_validated_ */, code_size_estimate);
    return;
  }
  // We have to open a HandleScope and prepare the Context for
  // CreateNativeModule, PrepareRuntimeObjects and FinishCompile as this is a
  // callback from the embedder.
  HandleScope scope(job_->isolate_);
  SaveAndSwitchContext saved_context(job_->isolate_, *job_->native_context_);
  // Record the size of the wire bytes and the number of functions. In
  // synchronous and asynchronous (non-streaming) compilation, this happens in
  // {DecodeWasmModule}.
  auto* module_size_histogram =
      job_->isolate_->counters()->wasm_wasm_module_size_bytes();
  module_size_histogram->AddSample(job_->wire_bytes_.module_bytes().length());
  auto* num_functions_histogram =
      job_->isolate_->counters()->wasm_functions_per_wasm_module();
  num_functions_histogram->AddSample(static_cast<int>(num_functions_));
  const bool has_code_section = job_->native_module_ != nullptr;
  bool cache_hit = false;
  if (!has_code_section) {
    // We are processing a WebAssembly module without code section. Create the
    // native module now (would otherwise happen in {PrepareAndStartCompile} or
    // {ProcessCodeSectionHeader}).
    constexpr size_t kCodeSizeEstimate = 0;
    cache_hit =
        job_->GetOrCreateNativeModule(std::move(module), kCodeSizeEstimate);
  } else {
    job_->native_module_->SetWireBytes(std::move(job_->bytes_copy_));
  }
  const bool needs_finish = job_->DecrementAndCheckFinisherCount();
  DCHECK_IMPLIES(!has_code_section, needs_finish);
  if (needs_finish) {
    const bool failed = job_->native_module_->compilation_state()->failed();
    if (!cache_hit) {
      auto* prev_native_module = job_->native_module_.get();
      job_->native_module_ = GetWasmEngine()->UpdateNativeModuleCache(
          failed, std::move(job_->native_module_), job_->isolate_);
      cache_hit = prev_native_module != job_->native_module_.get();
    }
    // We finally call {Failed} or {FinishCompile}, which will invalidate the
    // {AsyncCompileJob} and delete {this}.
    if (failed) {
      job_->Failed();
    } else {
      job_->FinishCompile(cache_hit);
    }
  }
}
References v8::base::OwnedVector< T >::as_vector(), v8::internal::wasm::AsyncCompileJob::bytes_copy_, v8::internal::wasm::AsyncCompileJob::compile_imports_, v8::base::EnumSet< E, T >::contains_all(), v8::internal::wasm::AsyncCompileJob::context_id_, v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, decoder_, v8::internal::wasm::DecodeWasmModule(), v8::internal::wasm::AsyncCompileJob::DecrementAndCheckFinisherCount(), v8::internal::wasm::ValidateFunctionsStreamingJobData::detected_features, v8::internal::wasm::AsyncCompileJob::detected_features_, v8::internal::wasm::AsyncCompileJob::DoSync(), v8::internal::duration, v8::internal::wasm::AsyncCompileJob::enabled_features_, v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::Result< T >::failed(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::wasm::ModuleDecoder::FinishDecoding(), v8::internal::wasm::ValidateFunctionsStreamingJobData::found_error, v8::metrics::WasmModuleDecoded::function_count, v8::internal::wasm::AsyncCompileJob::GetOrCreateNativeModule(), v8::internal::wasm::GetWasmEngine(), v8::base::Hasher::hash(), v8::internal::wasm::AsyncCompileJob::isolate_, job_, v8::internal::wasm::kWasmOrigin, v8::base::Vector< T >::length(), v8::internal::wasm::ModuleWireBytes::length(), v8::internal::wasm::AsyncCompileJob::metrics_event_, v8::internal::Isolate::metrics_recorder(), v8::internal::wasm::ModuleWireBytes::module_bytes(), v8::metrics::WasmModuleDecoded::module_size_in_bytes, v8::internal::wasm::AsyncCompileJob::native_context_, v8::internal::wasm::AsyncCompileJob::native_module_, v8::base::TimeTicks::Now(), num_functions_, v8::internal::wasm::Result< T >::ok(), prefix_cache_hit_, prefix_hasher_, v8::internal::wasm::NativeModuleCache::PrefixHash(), v8::internal::wasm::AsyncCompileJob::start_time_, v8::metrics::WasmModuleDecoded::streamed, v8::internal::wasm::WasmEngine::StreamingCompilationFailed(), v8::metrics::WasmModuleDecoded::success, TRACE_STREAMING, v8::internal::wasm::WasmEngine::UpdateNativeModuleCache(), validate_functions_job_data_, validate_functions_job_handle_, v8::internal::wasm::ValidateAndSetBuiltinImports(), v8::internal::wasm::Result< T >::value(), v8::metrics::WasmModuleDecoded::wall_clock_duration_in_us, and v8::internal::wasm::AsyncCompileJob::wire_bytes_.
ProcessCodeSectionHeader()
bool v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader (int num_functions, uint32_t functions_mismatch_error_offset, std::shared_ptr< WireBytesStorage > wire_bytes_storage, int code_section_start, int code_section_length) [override], [virtual]
Implements v8::internal::wasm::StreamingProcessor.
Definition at line 3275 of file module-compiler.cc.
                                                     {
  DCHECK_LE(0, code_section_length);
  before_code_section_ = false;
  TRACE_STREAMING("Start the code section with %d functions...\n",
                  num_functions);
  prefix_hasher_.Add(static_cast<uint32_t>(code_section_length));
  if (!decoder_.CheckFunctionsCount(static_cast<uint32_t>(num_functions),
                                    functions_mismatch_error_offset)) {
    return false;
  }
  decoder_.StartCodeSection({static_cast<uint32_t>(code_section_start),
                             static_cast<uint32_t>(code_section_length)});
  if (!GetWasmEngine()->GetStreamingCompilationOwnership(
          prefix_hasher_.hash(), job_->compile_imports_)) {
    // Known prefix, wait until the end of the stream and check the cache.
    prefix_cache_hit_ = true;
    return true;
  }
  // Execute the PrepareAndStartCompile step immediately and not in a separate
  // task.
  DCHECK_EQ(kWasmOrigin, decoder_.module()->origin);
  size_t code_size_estimate =
      wasm::WasmCodeManager::EstimateNativeModuleCodeSize(num_functions,
                                                          code_section_length);
  job_->DoImmediately<AsyncCompileJob::PrepareAndStartCompile>(
      decoder_.shared_module(),
      // start_compilation: false; triggered when we receive the bodies.
      false,
      // lazy_functions_are_validated: false (bodies not received yet).
      false, code_size_estimate);
  auto* compilation_state = Impl(job_->native_module_->compilation_state());
  compilation_state->SetWireBytesStorage(std::move(wire_bytes_storage));
  DCHECK_EQ(job_->native_module_->module()->origin, kWasmOrigin);
  // Set outstanding_finishers_ to 2, because both the AsyncCompileJob and the
  // AsyncStreamingProcessor have to finish.
  job_->outstanding_finishers_.store(2);
  // TODO(13209): Use PGO for streaming compilation, if available.
  constexpr ProfileInformation* kNoProfileInformation = nullptr;
  compilation_unit_builder_ = InitializeCompilation(
      job_->isolate(), job_->native_module_.get(), kNoProfileInformation);
  return true;
}
References v8::base::Hasher::Add(), before_code_section_, v8::internal::wasm::ModuleDecoder::CheckFunctionsCount(), compilation_unit_builder_, v8::internal::wasm::AsyncCompileJob::compile_imports_, DCHECK_EQ, DCHECK_LE, decoder_, v8::internal::wasm::AsyncCompileJob::DoImmediately(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), v8::internal::wasm::WasmEngine::GetStreamingCompilationOwnership(), v8::internal::wasm::GetWasmEngine(), v8::base::Hasher::hash(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::InitializeCompilation(), v8::internal::wasm::AsyncCompileJob::isolate(), job_, v8::internal::wasm::kWasmOrigin, v8::internal::wasm::ModuleDecoder::module(), v8::internal::wasm::AsyncCompileJob::native_module_, v8::internal::wasm::WasmModule::origin, v8::internal::wasm::AsyncCompileJob::outstanding_finishers_, prefix_cache_hit_, prefix_hasher_, v8::internal::wasm::ModuleDecoder::shared_module(), v8::internal::wasm::ModuleDecoder::StartCodeSection(), and TRACE_STREAMING.
ProcessFunctionBody()
bool v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody (base::Vector< const uint8_t > bytes, uint32_t offset) [override], [virtual]
Implements v8::internal::wasm::StreamingProcessor.
Definition at line 3327 of file module-compiler.cc.
                                                      {
  TRACE_STREAMING("Process function body %d ...\n", num_functions_);
  uint32_t func_index =
      decoder_.module()->num_imported_functions + num_functions_;
  ++num_functions_;
  // In case of {prefix_cache_hit} we still need the function body to be
  // decoded. Otherwise a later cache miss cannot be handled.
  decoder_.DecodeFunctionBody(func_index, static_cast<uint32_t>(bytes.length()),
                              offset);
  if (prefix_cache_hit_) {
    // Don't compile yet if we might have a cache hit.
    return true;
  }
  const WasmModule* module = decoder_.module();
  auto enabled_features = job_->enabled_features_;
  DCHECK_EQ(module->origin, kWasmOrigin);
  const bool lazy_module = v8_flags.wasm_lazy_compilation;
  CompileStrategy strategy =
      GetCompileStrategy(module, enabled_features, func_index, lazy_module);
  CHECK_IMPLIES(v8_flags.wasm_jitless, !v8_flags.wasm_lazy_validation);
  bool validate_lazily_compiled_function =
      v8_flags.wasm_jitless ||
      (!v8_flags.wasm_lazy_validation &&
       (strategy == CompileStrategy::kLazy ||
        strategy == CompileStrategy::kLazyBaselineEagerTopTier));
  if (validate_lazily_compiled_function) {
    // {bytes} is part of a section buffer owned by the streaming decoder. The
    // streaming decoder is held alive by the {AsyncCompileJob}, so we can just
    // use the {bytes} vector as long as the {AsyncCompileJob} is still running.
    if (!validate_functions_job_handle_) {
      validate_functions_job_data_.Initialize(module->num_declared_functions);
      validate_functions_job_handle_ = V8::GetCurrentPlatform()->CreateJob(
          TaskPriority::kUserVisible,
          std::make_unique<ValidateFunctionsStreamingJob>(
              module, enabled_features, &validate_functions_job_data_));
    }
    validate_functions_job_data_.AddUnit(func_index, bytes,
                                         validate_functions_job_handle_.get());
  }
  auto* compilation_state = Impl(job_->native_module_->compilation_state());
  compilation_state->InitializeCompilationUnitForSingleFunction(
      compilation_unit_builder_.get(), func_index);
  return true;
}
References v8::internal::wasm::ValidateFunctionsStreamingJobData::AddUnit(), CHECK_IMPLIES, compilation_unit_builder_, v8::Platform::CreateJob(), DCHECK_EQ, v8::internal::wasm::ModuleDecoder::DecodeFunctionBody(), decoder_, v8::internal::wasm::AsyncCompileJob::enabled_features_, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompileStrategy(), v8::internal::V8::GetCurrentPlatform(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::internal::wasm::ValidateFunctionsStreamingJobData::Initialize(), job_, v8::kUserVisible, v8::internal::wasm::kWasmOrigin, v8::base::Vector< T >::length(), v8::internal::wasm::ModuleDecoder::module(), v8::internal::wasm::AsyncCompileJob::native_module_, v8::internal::wasm::WasmModule::num_declared_functions, num_functions_, v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::wasm::WasmModule::origin, prefix_cache_hit_, TRACE_STREAMING, v8::internal::v8_flags, validate_functions_job_data_, and validate_functions_job_handle_.
ProcessModuleHeader()
bool v8::internal::wasm::AsyncStreamingProcessor::ProcessModuleHeader (base::Vector< const uint8_t > bytes) [override], [virtual]
Implements v8::internal::wasm::StreamingProcessor.
Definition at line 3233 of file module-compiler.cc.
                                     {
  TRACE_STREAMING("Process module header...\n");
  decoder_.DecodeModuleHeader(bytes);
  if (!decoder_.ok()) return false;
  // Note: We do not include the magic bytes in the hash; they are constant
  // anyways.
  return true;
}
References v8::internal::wasm::ModuleDecoder::DecodeModuleHeader(), decoder_, v8::internal::wasm::ModuleDecoder::ok(), and TRACE_STREAMING.
ProcessSection()
bool v8::internal::wasm::AsyncStreamingProcessor::ProcessSection (SectionCode section_code, base::Vector< const uint8_t > bytes, uint32_t offset) [override], [virtual]
Implements v8::internal::wasm::StreamingProcessor.
Definition at line 3244 of file module-compiler.cc.
                                                              {
  TRACE_STREAMING("Process section %d ...\n", section_code);
  if (compilation_unit_builder_) {
    // We reached a section after the code section, we do not need the
    // compilation_unit_builder_ anymore.
    CommitCompilationUnits();
    compilation_unit_builder_.reset();
  }
  if (before_code_section_) {
    // Combine section hashes until code section.
    prefix_hasher_.AddRange(bytes);
  }
  if (section_code == SectionCode::kUnknownSectionCode) {
    size_t bytes_consumed = ModuleDecoder::IdentifyUnknownSection(
        &decoder_, bytes, offset, &section_code);
    if (!decoder_.ok()) return false;
    if (section_code == SectionCode::kUnknownSectionCode) {
      // Skip unknown sections that we do not know how to handle.
      return true;
    }
    // Remove the unknown section tag from the payload bytes.
    offset += bytes_consumed;
    bytes = bytes.SubVector(bytes_consumed, bytes.size());
  }
  decoder_.DecodeSection(section_code, bytes, offset);
  return decoder_.ok();
}
References v8::base::Hasher::AddRange(), before_code_section_, CommitCompilationUnits(), compilation_unit_builder_, decoder_, v8::internal::wasm::ModuleDecoder::DecodeSection(), v8::internal::wasm::ModuleDecoder::IdentifyUnknownSection(), v8::internal::wasm::kUnknownSectionCode, v8::internal::wasm::ModuleDecoder::ok(), prefix_hasher_, v8::base::Vector< T >::size(), v8::base::Vector< T >::SubVector(), and TRACE_STREAMING.
Member Data Documentation
before_code_section_
bool v8::internal::wasm::AsyncStreamingProcessor::before_code_section_ = true [private]
Definition at line 2655 of file module-compiler.cc.
Referenced by ProcessCodeSectionHeader(), and ProcessSection().
compilation_unit_builder_
std::unique_ptr<CompilationUnitBuilder> v8::internal::wasm::AsyncStreamingProcessor::compilation_unit_builder_ [private]
Definition at line 2652 of file module-compiler.cc.
Referenced by CommitCompilationUnits(), OnFinishedChunk(), ProcessCodeSectionHeader(), ProcessFunctionBody(), and ProcessSection().
decoder_
ModuleDecoder v8::internal::wasm::AsyncStreamingProcessor::decoder_ [private]
Definition at line 2650 of file module-compiler.cc.
Referenced by OnFinishedStream(), ProcessCodeSectionHeader(), ProcessFunctionBody(), ProcessModuleHeader(), and ProcessSection().
job_
AsyncCompileJob* v8::internal::wasm::AsyncStreamingProcessor::job_ [private]
Definition at line 2651 of file module-compiler.cc.
Referenced by Deserialize(), OnAbort(), OnFinishedStream(), ProcessCodeSectionHeader(), and ProcessFunctionBody().
num_functions_
int v8::internal::wasm::AsyncStreamingProcessor::num_functions_ = 0 [private]
Definition at line 2653 of file module-compiler.cc.
Referenced by OnFinishedStream(), and ProcessFunctionBody().
prefix_cache_hit_
bool v8::internal::wasm::AsyncStreamingProcessor::prefix_cache_hit_ = false [private]
Definition at line 2654 of file module-compiler.cc.
Referenced by OnFinishedStream(), ProcessCodeSectionHeader(), and ProcessFunctionBody().
prefix_hasher_
base::Hasher v8::internal::wasm::AsyncStreamingProcessor::prefix_hasher_ [private]
Definition at line 2662 of file module-compiler.cc.
Referenced by OnAbort(), OnFinishedStream(), ProcessCodeSectionHeader(), and ProcessSection().
validate_functions_job_data_
ValidateFunctionsStreamingJobData v8::internal::wasm::AsyncStreamingProcessor::validate_functions_job_data_ [private]
Definition at line 2656 of file module-compiler.cc.
Referenced by OnFinishedStream(), and ProcessFunctionBody().
validate_functions_job_handle_
std::unique_ptr<JobHandle> v8::internal::wasm::AsyncStreamingProcessor::validate_functions_job_handle_ [private]
Definition at line 2657 of file module-compiler.cc.
Referenced by OnAbort(), OnFinishedStream(), and ProcessFunctionBody().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc