v8::LocalBase< T > Class Template Reference
A base class for local handles.
#include <v8-local-handle.h>
Protected Member Functions
LocalBase ()=default
LocalBase (internal::Address *location)
template<typename S >
LocalBase (const LocalBase< S > &other)
Static Protected Member Functions
static LocalBase< T > New (Isolate *isolate, internal::Address value)
static LocalBase< T > New (Isolate *isolate, T *that)
static LocalBase< T > FromSlot (internal::Address *slot)
static LocalBase< T > FromRepr (internal::ValueHelper::InternalRepresentationType repr)
Friends
template<class F >
class Local
Additional Inherited Members
Detailed Description
template<typename T>
class v8::LocalBase< T >
A base class for local handles.
Its implementation depends on whether direct handle support is enabled. When it is, a local handle contains a direct pointer to the referenced object, otherwise it contains an indirect pointer.
Definition at line 221 of file v8-local-handle.h.
Constructor & Destructor Documentation
LocalBase() [1/3]
template<typename T >
v8::LocalBase< T >::LocalBase () [inline], [protected], [default]
Referenced by v8::LocalBase< T >::New().
LocalBase() [2/3]
template<typename T >
v8::LocalBase< T >::LocalBase (internal::Address * location) [inline], [explicit], [protected]
Definition at line 228 of file v8-local-handle.h.
      : IndirectHandleBase(location) {
#ifdef V8_ENABLE_CHECKS
    if (!IsEmpty()) api_internal::TypeCheckLocal<T>(value<Value>());
#endif
  }
References v8::api_internal::IndirectHandleBase::IsEmpty().
LocalBase() [3/3]
template<typename T >
template<typename S >
v8::LocalBase< T >::LocalBase (const LocalBase< S > & other) [inline], [protected]
Definition at line 236 of file v8-local-handle.h.
: IndirectHandleBase(other) {}
Member Function Documentation
FromRepr()
template<typename T >
static LocalBase<T> v8::LocalBase< T >::FromRepr (internal::ValueHelper::InternalRepresentationType repr) [inline], [static], [protected]
Definition at line 253 of file v8-local-handle.h.
                                                          {
    return LocalBase<T>(repr);
  }
References v8::api_internal::IndirectHandleBase::repr().
FromSlot()
template<typename T >
static LocalBase<T> v8::LocalBase< T >::FromSlot (internal::Address * slot) [inline], [static], [protected]
Definition at line 249 of file v8-local-handle.h.
                                                                {
    return LocalBase<T>(slot);
  }
References v8::api_internal::IndirectHandleBase::slot().
New() [1/2]
template<typename T >
static LocalBase<T> v8::LocalBase< T >::New (Isolate * isolate, internal::Address value) [inline], [static], [protected]
Definition at line 238 of file v8-local-handle.h.
                                                                             {
    return LocalBase(HandleScope::CreateHandle(
        reinterpret_cast<internal::Isolate*>(isolate), value));
  }
References v8::HandleScope::CreateHandle(), v8::LocalBase< T >::LocalBase(), and v8::api_internal::IndirectHandleBase::value().
Referenced by v8::LocalBase< T >::New().
New() [2/2]
template<typename T >
static LocalBase<T> v8::LocalBase< T >::New (Isolate * isolate, T * that) [inline], [static], [protected]
Definition at line 243 of file v8-local-handle.h.
                                                               {
    if (internal::ValueHelper::IsEmpty(that)) return LocalBase<T>();
    return LocalBase<T>::New(isolate,
                             internal::ValueHelper::ValueAsAddress(that));
  }
References v8::internal::ValueHelper::IsEmpty(), v8::LocalBase< T >::New(), and v8::internal::ValueHelper::ValueAsAddress().
Friends And Related Function Documentation
Local
template<typename T >
template<class F >
friend class Local [friend]
Definition at line 224 of file v8-local-handle.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-local-handle.h