v8::internal::AddressToTraceMap Class Reference
#include <allocation-tracker.h>
Classes
struct RangeStack
Public Member Functions
void AddRange (Address addr, int size, unsigned node_id)
unsigned GetTraceNodeId (Address addr)
void MoveObject (Address from, Address to, int size)
void Clear ()
size_t size ()
void Print ()
Private Types
using RangeMap = std::map< Address, RangeStack >
Private Member Functions
void RemoveRange (Address start, Address end)
Private Attributes
RangeMap ranges_
Detailed Description
Definition at line 79 of file allocation-tracker.h.
Member Typedef Documentation
RangeMap
using v8::internal::AddressToTraceMap::RangeMap = std::map<Address, RangeStack> [private]
Definition at line 96 of file allocation-tracker.h.
Member Function Documentation
AddRange()
void v8::internal::AddressToTraceMap::AddRange (Address addr, int size, unsigned node_id)
Definition at line 106 of file allocation-tracker.cc.
                                                         {
  Address end = start + size;
  RemoveRange(start, end);
  RangeStack new_range(start, trace_node_id);
  ranges_.insert(RangeMap::value_type(end, new_range));
}
References v8::internal::compiler::end(), size(), and v8::internal::wasm::value_type().
Referenced by v8::internal::AllocationTracker::AllocationEvent().
Clear()
void v8::internal::AddressToTraceMap::Clear ()
Definition at line 134 of file allocation-tracker.cc.
                              {
  ranges_.clear();
}
GetTraceNodeId()
unsigned v8::internal::AddressToTraceMap::GetTraceNodeId (Address addr)
Definition at line 116 of file allocation-tracker.cc.
                                                       {
  RangeMap::const_iterator it = ranges_.upper_bound(addr);
  if (it == ranges_.end()) return 0;
  if (it->second.start <= addr) {
    return it->second.trace_node_id;
  }
  return 0;
}
MoveObject()
void v8::internal::AddressToTraceMap::MoveObject (Address from, Address to, int size)
Definition at line 126 of file allocation-tracker.cc.
                                                                     {
  unsigned trace_node_id = GetTraceNodeId(from);
  if (trace_node_id == 0) return;
  RemoveRange(from, from + size);
  AddRange(to, size, trace_node_id);
}
References v8::internal::anonymous_namespace{regexp-compiler.cc}::AddRange(), and size().
Print()
void v8::internal::AddressToTraceMap::Print ()
Definition at line 139 of file allocation-tracker.cc.
                              {
  PrintF("[AddressToTraceMap (%zu): \n", ranges_.size());
  for (RangeMap::iterator it = ranges_.begin(); it != ranges_.end(); ++it) {
    PrintF("[%p - %p] => %u\n", reinterpret_cast<void*>(it->second.start),
           reinterpret_cast<void*>(it->first), it->second.trace_node_id);
  }
  PrintF("]\n");
}
References v8::internal::PrintF().
RemoveRange()
void v8::internal::AddressToTraceMap::RemoveRange (Address start, Address end) [private]
Definition at line 149 of file allocation-tracker.cc.
                                                              {
  RangeMap::iterator it = ranges_.upper_bound(start);
  if (it == ranges_.end()) return;
  RangeStack prev_range(0, 0);
  RangeMap::iterator to_remove_begin = it;
  if (it->second.start < start) {
    prev_range = it->second;
  }
  do {
    if (it->first > end) {
      if (it->second.start < end) {
        it->second.start = end;
      }
      break;
    }
    ++it;
  } while (it != ranges_.end());
  ranges_.erase(to_remove_begin, it);
  if (prev_range.start != 0) {
    ranges_.insert(RangeMap::value_type(start, prev_range));
  }
}
References v8::internal::compiler::end(), v8::internal::AddressToTraceMap::RangeStack::start, and v8::internal::wasm::value_type().
size()
size_t v8::internal::AddressToTraceMap::size () [inline]
Definition at line 85 of file allocation-tracker.h.
{ return ranges_.size(); }
Member Data Documentation
ranges_
RangeMap v8::internal::AddressToTraceMap::ranges_ [private]
Definition at line 100 of file allocation-tracker.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/allocation-tracker.h
/mnt/V8SourceCode/src/profiler/allocation-tracker.cc