v8::internal::ScriptCacheKey Class Reference
#include <compilation-cache-table-inl.h>
Public Types
enum Index { kHash
, kWeakScript
, kEnd
 }
Public Member Functions
ScriptCacheKey (Handle< String > source, const ScriptDetails *script_details, Isolate *isolate)
ScriptCacheKey (Handle< String > source, MaybeHandle< Object > name, int line_offset, int column_offset, v8::ScriptOriginOptions origin_options, MaybeHandle< Object > host_defined_options, MaybeHandle< FixedArray > maybe_wrapped_arguments, Isolate *isolate)
bool IsMatch (Tagged< Object > other) override
bool MatchesScript (Tagged< Script > script)
DirectHandle< Object > AsHandle (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared)
Static Public Member Functions
static std::optional< Tagged< String > > SourceFromObject (Tagged< Object > obj)
Private Attributes
Handle< String > source_
MaybeHandle< Object > name_
int line_offset_
int column_offset_
v8::ScriptOriginOptions origin_options_
MaybeHandle< Object > host_defined_options_
MaybeHandle< FixedArray > wrapped_arguments_
Isolate * isolate_
Additional Inherited Members
Detailed Description
Definition at line 54 of file compilation-cache-table-inl.h.
Member Enumeration Documentation
Index
enum v8::internal::ScriptCacheKey::Index
Enumerator
kHash
kWeakScript
kEnd
Definition at line 56 of file compilation-cache-table-inl.h.
             {
    kHash,
    kWeakScript,
    kEnd,
  };
Constructor & Destructor Documentation
ScriptCacheKey() [1/2]
v8::internal::ScriptCacheKey::ScriptCacheKey (Handle< String > source, const ScriptDetails * script_details, Isolate * isolate)
Definition at line 289 of file compilation-cache-table.cc.
    : ScriptCacheKey(source, script_details->name_obj,
                     script_details->line_offset, script_details->column_offset,
                     script_details->origin_options,
                     script_details->host_defined_options,
                     script_details->wrapped_arguments, isolate) {}
ScriptCacheKey() [2/2]
v8::internal::ScriptCacheKey::ScriptCacheKey (Handle< String > source, MaybeHandle< Object > name, int line_offset, int column_offset, v8::ScriptOriginOptions origin_options, MaybeHandle< Object > host_defined_options, MaybeHandle< FixedArray > maybe_wrapped_arguments, Isolate * isolate)
Definition at line 298 of file compilation-cache-table.cc.
    : HashTableKey(static_cast<uint32_t>(ScriptHash(*source, name, line_offset,
                                                    column_offset,
                                                    origin_options, isolate)
                                             .value())),
      source_(source),
      name_(name),
      line_offset_(line_offset),
      column_offset_(column_offset),
      origin_options_(origin_options),
      host_defined_options_(host_defined_options),
      wrapped_arguments_(maybe_wrapped_arguments),
      isolate_(isolate) {
  DCHECK(Smi::IsValid(static_cast<int>(Hash())));
#ifdef DEBUG
  DirectHandle<FixedArray> wrapped_arguments;
  if (maybe_wrapped_arguments.ToHandle(&wrapped_arguments)) {
    int length = wrapped_arguments->length();
    for (int i = 0; i < length; i++) {
      Tagged<Object> arg = wrapped_arguments->get(i);
      DCHECK(IsString(arg));
    }
  }
#endif
}
References v8::internal::DCHECK(), v8::internal::HashTableKey::Hash(), v8::internal::Smi::IsValid(), v8::internal::length, and v8::internal::MaybeHandle< T >::ToHandle().
Member Function Documentation
AsHandle()
DirectHandle< Object > v8::internal::ScriptCacheKey::AsHandle (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared)
Definition at line 352 of file compilation-cache-table.cc.
                                                               {
  DirectHandle<WeakFixedArray> array =
      isolate->factory()->NewWeakFixedArray(kEnd);
  // Any SharedFunctionInfo being stored in the script cache should have a
  // Script.
  DCHECK(IsScript(shared->script()));
  array->set(kHash, Smi::FromInt(static_cast<int>(Hash())));
  array->set(kWeakScript, MakeWeak(shared->script()));
  return array;
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::HashTableKey::Hash(), kEnd, kHash, kWeakScript, v8::internal::MakeWeak(), and v8::internal::FactoryBase< Impl >::NewWeakFixedArray().
IsMatch()
bool v8::internal::ScriptCacheKey::IsMatch (Tagged< Object > other) [override], [virtual]
Implements v8::internal::HashTableKey.
Definition at line 329 of file compilation-cache-table.cc.
                                                 {
  DisallowGarbageCollection no_gc;
  DCHECK(IsWeakFixedArray(other));
  Tagged<WeakFixedArray> other_array = Cast<WeakFixedArray>(other);
  DCHECK_EQ(other_array->length(), kEnd);
  // A hash check can quickly reject many non-matches, even though this step
  // isn't strictly necessary.
  uint32_t other_hash =
      static_cast<uint32_t>(other_array->get(kHash).ToSmi().value());
  if (other_hash != Hash()) return false;
  Tagged<HeapObject> other_script_object;
  if (!other_array->get(kWeakScript)
           .GetHeapObjectIfWeak(&other_script_object)) {
    return false;
  }
  Tagged<Script> other_script = Cast<Script>(other_script_object);
  Tagged<String> other_source = Cast<String>(other_script->source());
  return other_source->Equals(*source_) && MatchesScript(other_script);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::HashTableKey::Hash(), kEnd, kHash, kWeakScript, MatchesScript(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, source_, and v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
MatchesScript()
bool v8::internal::ScriptCacheKey::MatchesScript (Tagged< Script > script)
Definition at line 210 of file compilation-cache-table.cc.
                                                        {
  DisallowGarbageCollection no_gc;
  // If the script name isn't set, the boilerplate script should have
  // an undefined name to have the same origin.
  Handle<Object> name;
  if (!name_.ToHandle(&name)) {
    return IsUndefined(script->name(), isolate_);
  }
  // Do the fast bailout checks first.
  if (line_offset_ != script->line_offset()) return false;
  if (column_offset_ != script->column_offset()) return false;
  // Check that both names are strings. If not, no match.
  if (!IsString(*name, isolate_) || !IsString(script->name(), isolate_))
    return false;
  // Are the origin_options same?
  if (origin_options_.Flags() != script->origin_options().Flags()) {
    return false;
  }
  // Compare the two name strings for equality.
  if (!Cast<String>(*name)->Equals(Cast<String>(script->name()))) {
    return false;
  }
  Handle<FixedArray> wrapped_arguments_handle;
  if (wrapped_arguments_.ToHandle(&wrapped_arguments_handle)) {
    if (!script->is_wrapped()) {
      return false;
    }
    Tagged<FixedArray> wrapped_arguments = *wrapped_arguments_handle;
    Tagged<FixedArray> other_wrapped_arguments = script->wrapped_arguments();
    int length = wrapped_arguments->length();
    if (length != other_wrapped_arguments->length()) {
      return false;
    }
    for (int i = 0; i < length; i++) {
      Tagged<Object> arg = wrapped_arguments->get(i);
      Tagged<Object> other_arg = other_wrapped_arguments->get(i);
      DCHECK(IsString(arg));
      DCHECK(IsString(other_arg));
      if (!Cast<String>(arg)->Equals(Cast<String>(other_arg))) {
        return false;
      }
    }
  } else if (script->is_wrapped()) {
    return false;
  }
  // Don't compare host options if the script was deserialized because we didn't
  // serialize host options (see CodeSerializer::SerializeObjectImpl())
  if (script->deserialized() &&
      script->host_defined_options() ==
          ReadOnlyRoots(isolate_).empty_fixed_array()) {
    return true;
  }
  // TODO(cbruni, chromium:1244145): Remove once migrated to the context
  Handle<Object> maybe_host_defined_options;
  if (!host_defined_options_.ToHandle(&maybe_host_defined_options)) {
    maybe_host_defined_options = isolate_->factory()->empty_fixed_array();
  }
  Tagged<FixedArray> host_defined_options =
      Cast<FixedArray>(*maybe_host_defined_options);
  Tagged<FixedArray> script_options =
      Cast<FixedArray>(script->host_defined_options());
  int length = host_defined_options->length();
  if (length != script_options->length()) return false;
  for (int i = 0; i < length; i++) {
    // host-defined options is a v8::PrimitiveArray.
    DCHECK(IsPrimitive(host_defined_options->get(i)));
    DCHECK(IsPrimitive(script_options->get(i)));
    if (!Object::StrictEquals(host_defined_options->get(i),
                              script_options->get(i))) {
      return false;
    }
  }
  return true;
}
References column_offset_, v8::internal::DCHECK(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), v8::internal::Isolate::factory(), v8::ScriptOriginOptions::Flags(), host_defined_options_, isolate_, v8::internal::IsPrimitive(), v8::internal::length, line_offset_, v8::internal::name, name_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, origin_options_, v8::internal::script, v8::internal::Object::StrictEquals(), and wrapped_arguments_.
Referenced by IsMatch().
SourceFromObject()
static std::optional<Tagged<String> > v8::internal::ScriptCacheKey::SourceFromObject (Tagged< Object > obj) [inline], [static]
Definition at line 77 of file compilation-cache-table-inl.h.
                                                                          {
    DisallowGarbageCollection no_gc;
    DCHECK(IsWeakFixedArray(obj));
    Tagged<WeakFixedArray> array = Cast<WeakFixedArray>(obj);
    DCHECK_EQ(array->length(), kEnd);
    Tagged<MaybeObject> maybe_script = array->get(kWeakScript);
    if (Tagged<HeapObject> script; maybe_script.GetHeapObjectIfWeak(&script)) {
      Tagged<PrimitiveHeapObject> source_or_undefined =
          Cast<Script>(script)->source();
      // Scripts stored in the script cache should always have a source string.
      return Cast<String>(source_or_undefined);
    }
    DCHECK(maybe_script.IsCleared());
    return {};
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), kEnd, kWeakScript, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
Member Data Documentation
column_offset_
int v8::internal::ScriptCacheKey::column_offset_ [private]
Definition at line 99 of file compilation-cache-table-inl.h.
Referenced by MatchesScript().
host_defined_options_
MaybeHandle<Object> v8::internal::ScriptCacheKey::host_defined_options_ [private]
Definition at line 101 of file compilation-cache-table-inl.h.
Referenced by MatchesScript().
isolate_
Isolate* v8::internal::ScriptCacheKey::isolate_ [private]
Definition at line 103 of file compilation-cache-table-inl.h.
Referenced by MatchesScript().
line_offset_
int v8::internal::ScriptCacheKey::line_offset_ [private]
Definition at line 98 of file compilation-cache-table-inl.h.
Referenced by MatchesScript().
name_
MaybeHandle<Object> v8::internal::ScriptCacheKey::name_ [private]
Definition at line 97 of file compilation-cache-table-inl.h.
Referenced by MatchesScript().
origin_options_
v8::ScriptOriginOptions v8::internal::ScriptCacheKey::origin_options_ [private]
Definition at line 100 of file compilation-cache-table-inl.h.
Referenced by MatchesScript().
source_
Handle<String> v8::internal::ScriptCacheKey::source_ [private]
Definition at line 96 of file compilation-cache-table-inl.h.
Referenced by IsMatch().
wrapped_arguments_
MaybeHandle<FixedArray> v8::internal::ScriptCacheKey::wrapped_arguments_ [private]
Definition at line 102 of file compilation-cache-table-inl.h.
Referenced by MatchesScript().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/compilation-cache-table-inl.h
/mnt/V8SourceCode/src/objects/compilation-cache-table.cc