v8::internal::OrderedHashTableIterator< Derived, TableType > Class Template Reference
#include <js-collection-iterator.h>
Public Member Functions
bool HasMore ()
void MoveNext ()
Tagged< Object > CurrentKey ()
Private Member Functions
void Transition ()
OBJECT_CONSTRUCTORS (OrderedHashTableIterator, JSCollectionIterator)
Detailed Description
template<class Derived, class TableType>
class v8::internal::OrderedHashTableIterator< Derived, TableType >
Definition at line 43 of file js-collection-iterator.h.
Member Function Documentation
CurrentKey()
template<class Derived , class TableType >
template Tagged< Object > v8::internal::OrderedHashTableIterator< Derived, TableType >::CurrentKey () [inline]
Definition at line 190 of file ordered-hash-table-inl.h.
                                                                        {
  Tagged<TableType> table = Cast<TableType>(this->table());
  int index = Smi::ToInt(this->index());
  DCHECK_LE(0, index);
  InternalIndex entry(index);
  Tagged<Object> key = table->KeyAt(entry);
  DCHECK(!IsHashTableHole(key));
  return key;
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::index, v8::internal::key, and v8::internal::Smi::ToInt().
HasMore()
template<class Derived , class TableType >
template bool v8::internal::OrderedHashTableIterator< Derived, TableType >::HasMore ()
Definition at line 1489 of file ordered-hash-table.cc.
                                                           {
  DisallowGarbageCollection no_gc;
  ReadOnlyRoots ro_roots = GetReadOnlyRoots();
  Transition();
  Tagged<TableType> table = Cast<TableType>(this->table());
  int index = Smi::ToInt(this->index());
  int used_capacity = table->UsedCapacity();
  while (index < used_capacity &&
         IsHashTableHole(table->KeyAt(InternalIndex(index)), ro_roots)) {
    index++;
  }
  set_index(Smi::FromInt(index));
  if (index < used_capacity) return true;
  set_table(TableType::GetEmpty(ro_roots));
  return false;
}
References v8::internal::GetReadOnlyRoots(), v8::internal::index, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt().
MoveNext()
template<class Derived , class TableType >
template void v8::internal::OrderedHashTableIterator< Derived, TableType >::MoveNext () [inline]
Definition at line 50 of file js-collection-iterator.h.
{ set_index(Smi::FromInt(Smi::ToInt(index()) + 1)); }
References v8::internal::Smi::FromInt(), v8::internal::index, and v8::internal::Smi::ToInt().
OBJECT_CONSTRUCTORS()
template<class Derived , class TableType >
v8::internal::OrderedHashTableIterator< Derived, TableType >::OBJECT_CONSTRUCTORS (OrderedHashTableIterator< Derived, TableType > , JSCollectionIterator) [private]
Transition()
template<class Derived , class TableType >
template void v8::internal::OrderedHashTableIterator< Derived, TableType >::Transition () [private]
Definition at line 1456 of file ordered-hash-table.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  Tagged<TableType> table = Cast<TableType>(this->table());
  if (!table->IsObsolete()) return;
  int index = Smi::ToInt(this->index());
  DCHECK_LE(0, index);
  while (table->IsObsolete()) {
    Tagged<TableType> next_table = table->NextTable();
    if (index > 0) {
      int nod = table->NumberOfDeletedElements();
      if (nod == TableType::kClearedTableSentinel) {
        index = 0;
      } else {
        int old_index = index;
        for (int i = 0; i < nod; ++i) {
          int removed_index = table->RemovedIndexAt(i);
          if (removed_index >= old_index) break;
          --index;
        }
      }
    }
    table = next_table;
  }
  set_table(table);
  set_index(Smi::FromInt(index));
}
References DCHECK_LE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-collection-iterator.h
/mnt/V8SourceCode/src/objects/ordered-hash-table-inl.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc