v8::internal::SerializerReferenceMap Class Reference
#include <references.h>
Public Member Functions
SerializerReferenceMap (Isolate *isolate)
const SerializerReference * LookupReference (Tagged< HeapObject > object) const
const SerializerReference * LookupReference (DirectHandle< HeapObject > object) const
const SerializerReference * LookupBackingStore (void *backing_store) const
void Add (Tagged< HeapObject > object, SerializerReference reference)
void AddBackingStore (void *backing_store, SerializerReference reference)
SerializerReference AddAttachedReference (Tagged< HeapObject > object)
Private Attributes
IdentityMap< SerializerReference, base::DefaultAllocationPolicy > map_
std::unordered_map< void *, SerializerReference > backing_store_map_
int attached_reference_index_
Detailed Description
Definition at line 103 of file references.h.
Constructor & Destructor Documentation
SerializerReferenceMap()
v8::internal::SerializerReferenceMap::SerializerReferenceMap (Isolate * isolate) [inline], [explicit]
Definition at line 105 of file references.h.
      : map_(isolate->heap()), attached_reference_index_(0) {}
Member Function Documentation
Add()
void v8::internal::SerializerReferenceMap::Add (Tagged< HeapObject > object, SerializerReference reference) [inline]
Definition at line 123 of file references.h.
                                                                     {
    DCHECK_NULL(LookupReference(object));
    map_.Insert(object, reference);
  }
References DCHECK_NULL, LookupReference(), and map_.
Referenced by v8::internal::Serializer::ObjectSerializer::SerializePrologue().
AddAttachedReference()
SerializerReference v8::internal::SerializerReferenceMap::AddAttachedReference (Tagged< HeapObject > object) [inline]
Definition at line 133 of file references.h.
                                                                      {
    SerializerReference reference =
        SerializerReference::AttachedReference(attached_reference_index_++);
    map_.Insert(object, reference);
    return reference;
  }
References attached_reference_index_, v8::internal::SerializerReference::AttachedReference(), and map_.
Referenced by v8::internal::ContextSerializer::Serialize().
AddBackingStore()
void v8::internal::SerializerReferenceMap::AddBackingStore (void * backing_store, SerializerReference reference) [inline]
Definition at line 128 of file references.h.
                                                                           {
    DCHECK(backing_store_map_.find(backing_store) == backing_store_map_.end());
    backing_store_map_.emplace(backing_store, reference);
  }
References backing_store_map_, and v8::internal::DCHECK().
LookupBackingStore()
const SerializerReference* v8::internal::SerializerReferenceMap::LookupBackingStore (void * backing_store) const [inline]
Definition at line 117 of file references.h.
                                                                           {
    auto it = backing_store_map_.find(backing_store);
    if (it == backing_store_map_.end()) return nullptr;
    return &it->second;
  }
References backing_store_map_.
LookupReference() [1/2]
const SerializerReference* v8::internal::SerializerReferenceMap::LookupReference (DirectHandle< HeapObject > object) const [inline]
Definition at line 112 of file references.h.
                                             {
    return map_.Find(object);
  }
References map_.
LookupReference() [2/2]
const SerializerReference* v8::internal::SerializerReferenceMap::LookupReference (Tagged< HeapObject > object) const [inline]
Definition at line 108 of file references.h.
                                                                              {
    return map_.Find(object);
  }
References map_.
Referenced by Add(), v8::internal::Serializer::QueueDeferredObject(), v8::internal::Serializer::ReferenceMapContains(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::Serializer::SerializeBackReference(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
Member Data Documentation
attached_reference_index_
int v8::internal::SerializerReferenceMap::attached_reference_index_ [private]
Definition at line 143 of file references.h.
Referenced by AddAttachedReference().
backing_store_map_
std::unordered_map<void*, SerializerReference> v8::internal::SerializerReferenceMap::backing_store_map_ [private]
Definition at line 142 of file references.h.
Referenced by AddBackingStore(), and LookupBackingStore().
map_
IdentityMap<SerializerReference, base::DefaultAllocationPolicy> v8::internal::SerializerReferenceMap::map_ [private]
Definition at line 141 of file references.h.
Referenced by Add(), AddAttachedReference(), and LookupReference().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/references.h