v8::internal::ErrorUtils Class Reference
#include <messages.h>
Classes
struct StackPropertyLookupResult
Public Types
enum class StackTraceCollection { kEnabled
, kDisabled
 }
enum class ToStringMessageSource { kPreferOriginalMessage
, kCurrentMessageProperty
 }
Static Public Member Functions
static MaybeDirectHandle< JSObject > Construct (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< Object > new_target, DirectHandle< Object > message, DirectHandle< Object > options)
static MaybeHandle< JSObject > Construct (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< Object > new_target, DirectHandle< Object > message, DirectHandle< Object > options, FrameSkipMode mode, DirectHandle< Object > caller, StackTraceCollection stack_trace_collection)
static V8_EXPORT_PRIVATE MaybeHandle< String > ToString (Isolate *isolate, DirectHandle< Object > recv, ToStringMessageSource message_source=ToStringMessageSource::kCurrentMessageProperty)
static Handle< JSObject > MakeGenericError (Isolate *isolate, DirectHandle< JSFunction > constructor, MessageTemplate index, base::Vector< const DirectHandle< Object >> args, FrameSkipMode mode)
static DirectHandle< JSObject > ShadowRealmConstructTypeErrorCopy (Isolate *isolate, DirectHandle< Object > original, MessageTemplate index, base::Vector< const DirectHandle< Object >> args)
static MaybeDirectHandle< Object > FormatStackTrace (Isolate *isolate, DirectHandle< JSObject > error, DirectHandle< Object > stack_trace)
static DirectHandle< JSObject > NewIteratorError (Isolate *isolate, DirectHandle< Object > source)
static DirectHandle< JSObject > NewCalledNonCallableError (Isolate *isolate, DirectHandle< Object > source)
static DirectHandle< JSObject > NewConstructedNonConstructable (Isolate *isolate, DirectHandle< Object > source)
static Tagged< Object > ThrowSpreadArgError (Isolate *isolate, MessageTemplate id, DirectHandle< Object > object)
static Tagged< Object > ThrowLoadFromNullOrUndefined (Isolate *isolate, DirectHandle< Object > object, MaybeDirectHandle< Object > key)
static bool HasErrorStackSymbolOwnProperty (Isolate *isolate, DirectHandle< JSObject > object)
static StackPropertyLookupResult GetErrorStackProperty (Isolate *isolate, DirectHandle< JSReceiver > maybe_error_object)
static MaybeDirectHandle< Object > GetFormattedStack (Isolate *isolate, DirectHandle< JSObject > maybe_error_object)
static void SetFormattedStack (Isolate *isolate, DirectHandle< JSObject > maybe_error_object, DirectHandle< Object > formatted_stack)
static MaybeHandle< Object > CaptureStackTrace (Isolate *isolate, DirectHandle< JSObject > object, FrameSkipMode mode, Handle< Object > caller)
Detailed Description
Definition at line 74 of file messages.h.
Member Enumeration Documentation
StackTraceCollection
enum v8::internal::ErrorUtils::StackTraceCollection [strong]
Enumerator
kEnabled
kDisabled
Definition at line 78 of file messages.h.
{ kEnabled, kDisabled };
ToStringMessageSource
enum v8::internal::ErrorUtils::ToStringMessageSource [strong]
Enumerator
kPreferOriginalMessage
kCurrentMessageProperty
Definition at line 90 of file messages.h.
                                   {
    kPreferOriginalMessage,
    kCurrentMessageProperty
  };
Member Function Documentation
CaptureStackTrace()
MaybeHandle< Object > v8::internal::ErrorUtils::CaptureStackTrace (Isolate * isolate, DirectHandle< JSObject > object, FrameSkipMode mode, Handle< Object > caller) [static]
Definition at line 1217 of file messages.cc.
                                                                         {
  Factory* factory = isolate->factory();
  Handle<Name> name = factory->stack_string();
  // Explicitly check for frozen objects to simplify things since we need to
  // add both "stack" and "error_stack_symbol" properties in one go.
  if (!JSObject::IsExtensible(isolate, object)) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kDefineDisallowed, name));
  }
  // Add the stack accessors.
  PropertyDescriptor desc;
  desc.set_enumerable(false);
  desc.set_configurable(true);
  desc.set_get(factory->error_stack_getter_fun_template());
  desc.set_set(factory->error_stack_setter_fun_template());
  Maybe<bool> success = JSReceiver::DefineOwnProperty(
      isolate, object, name, &desc, Just(kThrowOnError));
  MAYBE_RETURN(success, {});
  // Collect the stack trace and store it in |object|'s private
  // "error_stack_symbol" property.
  RETURN_ON_EXCEPTION(isolate,
                      isolate->CaptureAndSetErrorStack(object, mode, caller));
  return isolate->factory()->undefined_value();
}
References v8::internal::Isolate::CaptureAndSetErrorStack(), v8::internal::JSReceiver::DefineOwnProperty(), v8::internal::Isolate::factory(), v8::internal::JSObject::IsExtensible(), v8::Just(), v8::internal::kThrowOnError, MAYBE_RETURN, mode(), v8::internal::name, RETURN_ON_EXCEPTION, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_get(), v8::internal::PropertyDescriptor::set_set(), and THROW_NEW_ERROR.
Referenced by v8::internal::BUILTIN(), v8::Exception::CaptureStackTrace(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl().
Construct() [1/2]
MaybeDirectHandle< JSObject > v8::internal::ErrorUtils::Construct (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< Object > new_target, DirectHandle< Object > message, DirectHandle< Object > options) [static]
Definition at line 529 of file messages.cc.
                                  {
  FrameSkipMode mode = SKIP_FIRST;
  DirectHandle<Object> caller;
  // When we're passed a JSFunction as new target, we can skip frames until that
  // specific function is seen instead of unconditionally skipping the first
  // frame.
  if (IsJSFunction(*new_target)) {
    mode = SKIP_UNTIL_SEEN;
    caller = new_target;
  }
  return ErrorUtils::Construct(isolate, target, new_target, message, options,
                               mode, caller,
                               ErrorUtils::StackTraceCollection::kEnabled);
}
References kEnabled, mode(), v8::internal::SKIP_FIRST, and v8::internal::SKIP_UNTIL_SEEN.
Referenced by v8::internal::BUILTIN(), MakeGenericError(), v8::internal::Factory::NewError(), v8::internal::ValueDeserializer::ReadJSError(), v8::internal::RUNTIME_FUNCTION(), ShadowRealmConstructTypeErrorCopy(), and v8::internal::Isolate::StackOverflow().
Construct() [2/2]
MaybeHandle< JSObject > v8::internal::ErrorUtils::Construct (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< Object > new_target, DirectHandle< Object > message, DirectHandle< Object > options, FrameSkipMode mode, DirectHandle< Object > caller, StackTraceCollection stack_trace_collection) [static]
Definition at line 549 of file messages.cc.
                                                                              {
  if (v8_flags.correctness_fuzzer_suppressions) {
    // Abort range errors in correctness fuzzing, as their causes differ
    // across correctness-fuzzing scenarios.
    if (target.is_identical_to(isolate->range_error_function())) {
      FATAL("Aborting on range error");
    }
    // Ignore error messages in correctness fuzzing, because the spec leaves
    // room for undefined behavior.
    message = isolate->factory()->InternalizeUtf8String(
        "Message suppressed for fuzzers (--correctness-fuzzer-suppressions)");
  }
  // 1. If NewTarget is undefined, let newTarget be the active function object,
  // else let newTarget be NewTarget.
  DirectHandle<JSReceiver> new_target_recv = IsJSReceiver(*new_target)
                                                 ? Cast<JSReceiver>(new_target)
                                                 : Cast<JSReceiver>(target);
  // 2. Let O be ? OrdinaryCreateFromConstructor(newTarget, "%ErrorPrototype%",
  // « [[ErrorData]] »).
  Handle<JSObject> err;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, err,
                             JSObject::New(target, new_target_recv, {}));
  // 3. If message is not undefined, then
  // a. Let msg be ? ToString(message).
  // b. Let msgDesc be the PropertyDescriptor{[[Value]]: msg, [[Writable]]:
  // true, [[Enumerable]]: false, [[Configurable]]: true}.
  // c. Perform ! DefinePropertyOrThrow(O, "message", msgDesc).
  // 4. Return O.
  if (!IsUndefined(*message, isolate)) {
    DirectHandle<String> msg_string;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, msg_string,
                               Object::ToString(isolate, message));
    RETURN_ON_EXCEPTION(isolate, JSObject::SetOwnPropertyIgnoreAttributes(
                                     err, isolate->factory()->message_string(),
                                     msg_string, DONT_ENUM));
    if (v8_flags.use_original_message_for_stack_trace) {
      RETURN_ON_EXCEPTION(isolate,
                          JSObject::SetOwnPropertyIgnoreAttributes(
                              err, isolate->factory()->error_message_symbol(),
                              msg_string, DONT_ENUM));
    }
  }
  if (!IsUndefined(*options, isolate)) {
    // If Type(options) is Object and ? HasProperty(options, "cause") then
    // a. Let cause be ? Get(options, "cause").
    // b. Perform ! CreateNonEnumerableDataPropertyOrThrow(O, "cause", cause).
    DirectHandle<Name> cause_string = isolate->factory()->cause_string();
    if (IsJSReceiver(*options)) {
      DirectHandle<JSReceiver> js_options = Cast<JSReceiver>(options);
      Maybe<bool> has_cause =
          JSObject::HasProperty(isolate, js_options, cause_string);
      if (has_cause.IsNothing()) {
        DCHECK((isolate)->has_exception());
        return MaybeHandle<JSObject>();
      }
      if (has_cause.ToChecked()) {
        DirectHandle<Object> cause;
        ASSIGN_RETURN_ON_EXCEPTION(
            isolate, cause,
            JSObject::GetProperty(isolate, js_options, cause_string));
        RETURN_ON_EXCEPTION(isolate, JSObject::SetOwnPropertyIgnoreAttributes(
                                         err, cause_string, cause, DONT_ENUM));
      }
    }
  }
  switch (stack_trace_collection) {
    case StackTraceCollection::kEnabled:
      RETURN_ON_EXCEPTION(isolate,
                          isolate->CaptureAndSetErrorStack(
                              err, mode, indirect_handle(caller, isolate)));
      break;
    case StackTraceCollection::kDisabled:
      break;
  }
  return err;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::CaptureAndSetErrorStack(), v8::internal::DCHECK(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), FATAL, v8::internal::indirect_handle(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::DirectHandle< T >::is_identical_to(), v8::Maybe< T >::IsNothing(), kDisabled, kEnabled, mode(), v8::internal::JSObject::New(), RETURN_ON_EXCEPTION, v8::internal::JSObject::SetOwnPropertyIgnoreAttributes(), v8::Maybe< T >::ToChecked(), v8::Value::ToString(), and v8::internal::v8_flags.
FormatStackTrace()
MaybeDirectHandle< Object > v8::internal::ErrorUtils::FormatStackTrace (Isolate * isolate, DirectHandle< JSObject > error, DirectHandle< Object > stack_trace) [static]
Definition at line 288 of file messages.cc.
                                    {
  if (v8_flags.correctness_fuzzer_suppressions) {
    return isolate->factory()->empty_string();
  }
  DCHECK(IsFixedArray(*raw_stack));
  auto elems = Cast<FixedArray>(raw_stack);
  const bool in_recursion = isolate->formatting_stack_trace();
  const bool has_overflowed = i::StackLimitCheck{isolate}.HasOverflowed();
  DirectHandle<NativeContext> error_context;
  if (!in_recursion && !has_overflowed &&
      error->GetCreationContext(isolate).ToHandle(&error_context)) {
    if (isolate->HasPrepareStackTraceCallback()) {
      PrepareStackTraceScope scope(isolate);
      DirectHandle<JSArray> sites;
      ASSIGN_RETURN_ON_EXCEPTION(isolate, sites,
                                 GetStackFrames(isolate, elems));
      DirectHandle<Object> result;
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, result,
          isolate->RunPrepareStackTraceCallback(error_context, error, sites));
      return result;
    } else {
      DirectHandle<JSFunction> global_error(error_context->error_function(),
                                            isolate);
      // If there's a user-specified "prepareStackTrace" function, call it on
      // the frames and use its result.
      DirectHandle<Object> prepare_stack_trace;
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, prepare_stack_trace,
          JSFunction::GetProperty(isolate, global_error, "prepareStackTrace"));
      if (IsJSFunction(*prepare_stack_trace)) {
        PrepareStackTraceScope scope(isolate);
        isolate->CountUsage(v8::Isolate::kErrorPrepareStackTrace);
        DirectHandle<JSArray> sites;
        ASSIGN_RETURN_ON_EXCEPTION(isolate, sites,
                                   GetStackFrames(isolate, elems));
        constexpr int argc = 2;
        std::array<DirectHandle<Object>, argc> args;
        if (V8_UNLIKELY(IsJSGlobalObject(*error))) {
          // Pass global proxy instead of global object.
          args[0] = direct_handle(Cast<JSGlobalObject>(*error)->global_proxy(),
                                  isolate);
        } else {
          args[0] = error;
        }
        args[1] = sites;
        DirectHandle<Object> result;
        ASSIGN_RETURN_ON_EXCEPTION(
            isolate, result,
            Execution::Call(isolate, prepare_stack_trace, global_error,
                            base::VectorOf(args)));
        return result;
      }
    }
  }
  // Otherwise, run our internal formatting logic.
  IncrementalStringBuilder builder(isolate);
  RETURN_ON_EXCEPTION(isolate, AppendErrorString(isolate, error, &builder));
  for (int i = 0; i < elems->length(); ++i) {
    builder.AppendCStringLiteral("\n at ");
    DirectHandle<CallSiteInfo> frame(Cast<CallSiteInfo>(elems->get(i)),
                                     isolate);
    v8::TryCatch try_catch(reinterpret_cast<v8::Isolate*>(isolate));
    SerializeCallSiteInfo(isolate, frame, &builder);
    if (isolate->has_exception()) {
      // CallSite.toString threw. Parts of the current frame might have been
      // stringified already regardless. Still, try to append a string
      // representation of the thrown exception.
      DirectHandle<Object> exception(isolate->exception(), isolate);
      try_catch.Reset();
      MaybeDirectHandle<String> exception_string =
          ErrorUtils::ToString(isolate, exception);
      if (exception_string.is_null()) {
        // Formatting the thrown exception threw again, give up.
        builder.AppendCStringLiteral("<error>");
      } else {
        // Formatted thrown exception successfully, append it.
        builder.AppendCStringLiteral("<error: ");
        builder.AppendString(exception_string.ToHandleChecked());
        builder.AppendCStringLiteral("<error>");
      }
    }
  }
  return builder.Finish();
}
References v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::IncrementalStringBuilder::AppendString(), v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), v8::internal::Isolate::CountUsage(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::anonymous_namespace{messages.cc}::GetStackFrames(), v8::internal::Isolate::has_exception(), v8::internal::Isolate::HasPrepareStackTraceCallback(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MaybeDirectHandle< T >::is_null(), v8::Isolate::kErrorPrepareStackTrace, v8::TryCatch::Reset(), v8::base::internal::result, RETURN_ON_EXCEPTION, v8::internal::Isolate::RunPrepareStackTraceCallback(), v8::internal::SerializeCallSiteInfo(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), ToString(), v8::internal::v8_flags, V8_UNLIKELY, and v8::base::VectorOf().
Referenced by GetFormattedStack().
GetErrorStackProperty()
ErrorUtils::StackPropertyLookupResult v8::internal::ErrorUtils::GetErrorStackProperty (Isolate * isolate, DirectHandle< JSReceiver > maybe_error_object) [static]
Definition at line 1133 of file messages.cc.
                                                                   {
  LookupIterator it(isolate, LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR,
                    maybe_error_object,
                    isolate->factory()->error_stack_symbol());
  Handle<Object> result = JSReceiver::GetDataProperty(&it);
  if (!it.IsFound()) {
    return {MaybeDirectHandle<JSObject>{},
            isolate->factory()->undefined_value()};
  }
  return {it.GetHolder<JSObject>(), result};
}
References v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::IsFound(), v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, and v8::base::internal::result.
Referenced by v8::internal::Isolate::GetDetailedStackTrace(), GetFormattedStack(), v8::internal::Isolate::GetSimpleStackTrace(), and SetFormattedStack().
GetFormattedStack()
MaybeDirectHandle< Object > v8::internal::ErrorUtils::GetFormattedStack (Isolate * isolate, DirectHandle< JSObject > maybe_error_object) [static]
Definition at line 1148 of file messages.cc.
                                                                 {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.stack_trace"), __func__);
  ErrorUtils::StackPropertyLookupResult lookup =
      ErrorUtils::GetErrorStackProperty(isolate, maybe_error_object);
  if (IsErrorStackData(*lookup.error_stack)) {
    auto error_stack_data = Cast<ErrorStackData>(lookup.error_stack);
    if (error_stack_data->HasFormattedStack()) {
      return direct_handle(error_stack_data->formatted_stack(), isolate);
    }
    DirectHandle<JSObject> error_object =
        lookup.error_stack_symbol_holder.ToHandleChecked();
    DirectHandle<Object> formatted_stack;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, formatted_stack,
        FormatStackTrace(
            isolate, error_object,
            direct_handle(error_stack_data->call_site_infos(), isolate)));
    error_stack_data->set_formatted_stack(*formatted_stack);
    return formatted_stack;
  }
  if (IsFixedArray(*lookup.error_stack)) {
    DirectHandle<JSObject> error_object =
        lookup.error_stack_symbol_holder.ToHandleChecked();
    DirectHandle<Object> formatted_stack;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, formatted_stack,
        FormatStackTrace(isolate, error_object,
                         Cast<FixedArray>(lookup.error_stack)));
    RETURN_ON_EXCEPTION(
        isolate, Object::SetProperty(isolate, error_object,
                                     isolate->factory()->error_stack_symbol(),
                                     formatted_stack, StoreOrigin::kMaybeKeyed,
                                     Just(ShouldThrow::kThrowOnError)));
    return formatted_stack;
  }
  return lookup.error_stack;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::direct_handle(), v8::internal::ErrorUtils::StackPropertyLookupResult::error_stack, v8::internal::ErrorUtils::StackPropertyLookupResult::error_stack_symbol_holder, v8::internal::Isolate::factory(), FormatStackTrace(), GetErrorStackProperty(), v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, RETURN_ON_EXCEPTION, v8::internal::Object::SetProperty(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by ShadowRealmConstructTypeErrorCopy().
HasErrorStackSymbolOwnProperty()
bool v8::internal::ErrorUtils::HasErrorStackSymbolOwnProperty (Isolate * isolate, DirectHandle< JSObject > object) [static]
Definition at line 1119 of file messages.cc.
                                                                               {
  // TODO(v8:5962): consider adding object->IsWasmExceptionPackage() here
  // once it's guaranteed that WasmExceptionPackage has |error_stack_symbol|
  // property.
  DirectHandle<Name> name = isolate->factory()->error_stack_symbol();
  if (IsJSError(*object)) {
    DCHECK(JSReceiver::HasOwnProperty(isolate, object, name).FromMaybe(false));
    return true;
  }
  return JSReceiver::HasOwnProperty(isolate, object, name).FromMaybe(false);
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::HasOwnProperty(), and v8::internal::name.
Referenced by v8::internal::anonymous_namespace{objects.cc}::IsErrorObject().
MakeGenericError()
Handle< JSObject > v8::internal::ErrorUtils::MakeGenericError (Isolate * isolate, DirectHandle< JSFunction > constructor, MessageTemplate index, base::Vector< const DirectHandle< Object >> args, FrameSkipMode mode) [static]
Definition at line 731 of file messages.cc.
                        {
  if (v8_flags.clear_exceptions_on_js_entry) {
    // This function used to be implemented in JavaScript, and JSEntry
    // clears any exceptions - so whenever we'd call this from C++,
    // exceptions would be cleared. Preserve this behavior.
    isolate->clear_exception();
    isolate->clear_pending_message();
  }
  DirectHandle<String> msg = MessageFormatter::Format(isolate, index, args);
  DirectHandle<Object> options = isolate->factory()->undefined_value();
  DCHECK(mode != SKIP_UNTIL_SEEN);
  DirectHandle<Object> no_caller;
  // The call below can't fail because constructor is a builtin.
  DCHECK(constructor->shared()->HasBuiltinId());
  return ErrorUtils::Construct(isolate, constructor, constructor, msg, options,
                               mode, no_caller, StackTraceCollection::kEnabled)
      .ToHandleChecked();
}
References v8::base::args, v8::internal::Isolate::clear_exception(), v8::internal::Isolate::clear_pending_message(), Construct(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::MessageFormatter::Format(), v8::internal::index, kEnabled, mode(), v8::internal::SKIP_UNTIL_SEEN, and v8::internal::v8_flags.
Referenced by v8::internal::Factory::NewError().
NewCalledNonCallableError()
DirectHandle< JSObject > v8::internal::ErrorUtils::NewCalledNonCallableError (Isolate * isolate, DirectHandle< Object > source) [static]
Definition at line 986 of file messages.cc.
                                                   {
  MessageLocation location;
  CallPrinter::ErrorHint hint = CallPrinter::ErrorHint::kNone;
  DirectHandle<String> callsite =
      RenderCallSite(isolate, source, &location, &hint);
  MessageTemplate id = MessageTemplate::kCalledNonCallable;
  id = UpdateErrorTemplate(hint, id);
  return isolate->factory()->NewTypeError(id, callsite);
}
References v8::internal::Isolate::factory(), v8::internal::CallPrinter::kNone, v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), and v8::internal::anonymous_namespace{messages.cc}::UpdateErrorTemplate().
Referenced by v8::internal::RUNTIME_FUNCTION().
NewConstructedNonConstructable()
DirectHandle< JSObject > v8::internal::ErrorUtils::NewConstructedNonConstructable (Isolate * isolate, DirectHandle< Object > source) [static]
Definition at line 997 of file messages.cc.
                                                   {
  MessageLocation location;
  CallPrinter::ErrorHint hint = CallPrinter::ErrorHint::kNone;
  DirectHandle<String> callsite =
      RenderCallSite(isolate, source, &location, &hint);
  MessageTemplate id = MessageTemplate::kNotConstructor;
  return isolate->factory()->NewTypeError(id, callsite);
}
References v8::internal::Isolate::factory(), v8::internal::CallPrinter::kNone, and v8::internal::anonymous_namespace{messages.cc}::RenderCallSite().
Referenced by v8::internal::RUNTIME_FUNCTION().
NewIteratorError()
DirectHandle< JSObject > v8::internal::ErrorUtils::NewIteratorError (Isolate * isolate, DirectHandle< Object > source) [static]
Definition at line 930 of file messages.cc.
                                                   {
  MessageLocation location;
  CallPrinter::ErrorHint hint = CallPrinter::ErrorHint::kNone;
  DirectHandle<String> callsite =
      RenderCallSite(isolate, source, &location, &hint);
  MessageTemplate id = MessageTemplate::kNotIterableNoSymbolLoad;
  if (hint == CallPrinter::ErrorHint::kNone) {
    DirectHandle<Symbol> iterator_symbol =
        isolate->factory()->iterator_symbol();
    return isolate->factory()->NewTypeError(id, callsite, iterator_symbol);
  }
  id = UpdateErrorTemplate(hint, id);
  return isolate->factory()->NewTypeError(id, callsite);
}
References v8::internal::Isolate::factory(), v8::internal::CallPrinter::kNone, v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), and v8::internal::anonymous_namespace{messages.cc}::UpdateErrorTemplate().
Referenced by v8::internal::RUNTIME_FUNCTION(), and ThrowLoadFromNullOrUndefined().
SetFormattedStack()
void v8::internal::ErrorUtils::SetFormattedStack (Isolate * isolate, DirectHandle< JSObject > maybe_error_object, DirectHandle< Object > formatted_stack) [static]
Definition at line 1193 of file messages.cc.
                                                                         {
  ErrorUtils::StackPropertyLookupResult lookup =
      ErrorUtils::GetErrorStackProperty(isolate, maybe_error_object);
  DirectHandle<JSObject> error_object;
  // Do nothing in case |maybe_error_object| is not an Error, i.e. its
  // prototype doesn't contain objects with |error_stack_symbol| property.
  if (!lookup.error_stack_symbol_holder.ToHandle(&error_object)) return;
  if (IsErrorStackData(*lookup.error_stack)) {
    auto error_stack_data = Cast<ErrorStackData>(lookup.error_stack);
    error_stack_data->set_formatted_stack(*formatted_stack);
  } else {
    Object::SetProperty(isolate, error_object,
                        isolate->factory()->error_stack_symbol(),
                        formatted_stack, StoreOrigin::kMaybeKeyed,
                        Just(ShouldThrow::kThrowOnError))
        .Check();
  }
}
References v8::internal::ErrorUtils::StackPropertyLookupResult::error_stack, v8::internal::ErrorUtils::StackPropertyLookupResult::error_stack_symbol_holder, v8::internal::Isolate::factory(), GetErrorStackProperty(), v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, and v8::internal::Object::SetProperty().
Referenced by v8::internal::ValueDeserializer::ReadJSError().
ShadowRealmConstructTypeErrorCopy()
DirectHandle< JSObject > v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy (Isolate * isolate, DirectHandle< Object > original, MessageTemplate index, base::Vector< const DirectHandle< Object >> args) [static]
Definition at line 756 of file messages.cc.
                                                 {
  if (v8_flags.clear_exceptions_on_js_entry) {
    // This function used to be implemented in JavaScript, and JSEntry
    // clears any exceptions - so whenever we'd call this from C++,
    // exceptions would be cleared. Preserve this behavior.
    isolate->clear_exception();
    isolate->clear_pending_message();
  }
  DirectHandle<String> msg = MessageFormatter::Format(isolate, index, args);
  DirectHandle<Object> options = isolate->factory()->undefined_value();
  DirectHandle<JSObject> maybe_error_object;
  DirectHandle<Object> error_stack;
  StackTraceCollection collection = StackTraceCollection::kEnabled;
  if (IsJSObject(*original)) {
    maybe_error_object = Cast<JSObject>(original);
    if (!ErrorUtils::GetFormattedStack(isolate, maybe_error_object)
             .ToHandle(&error_stack)) {
      DCHECK(isolate->has_exception());
      DirectHandle<Object> exception =
          direct_handle(isolate->exception(), isolate);
      isolate->clear_exception();
      // Return a new side-effect-free TypeError to be loud about inner error.
      DirectHandle<String> string =
          Object::NoSideEffectsToString(isolate, exception);
      return isolate->factory()->NewTypeError(
          MessageTemplate::kShadowRealmErrorStackThrows, string);
    } else if (IsNullOrUndefined(*error_stack)) {
      // If the error stack property is null or undefined, create a new error.
      collection = StackTraceCollection::kEnabled;
    } else if (IsPrimitive(*error_stack)) {
      // If the error stack property is found (must be a formatted string, not
      // an unformatted FixedArray), set collection to disabled and reuse the
      // existing stack. If the `Error.prepareStackTrace` returned a primitive,
      // use it as the stack as well.
      collection = StackTraceCollection::kDisabled;
    } else {
      // The error stack property is an arbitrary value. Return a new TypeError
      // about the non-string value.
      DirectHandle<String> string =
          Object::NoSideEffectsToString(isolate, error_stack);
      return isolate->factory()->NewTypeError(
          MessageTemplate::kShadowRealmErrorStackNonString, string);
    }
  }
  DirectHandle<Object> no_caller;
  DirectHandle<JSFunction> constructor = isolate->type_error_function();
  DirectHandle<JSObject> new_error =
      ErrorUtils::Construct(isolate, constructor, constructor, msg, options,
                            FrameSkipMode::SKIP_NONE, no_caller, collection)
          .ToHandleChecked();
  // If collection is disabled, reuse the existing stack string from the
  // original error object.
  if (collection == StackTraceCollection::kDisabled) {
    // Error stack symbol is a private symbol and set it on an error object
    // created from built-in error constructor should not throw.
    Object::SetProperty(
        isolate, new_error, isolate->factory()->error_stack_symbol(),
        error_stack, StoreOrigin::kMaybeKeyed, Just(ShouldThrow::kThrowOnError))
        .Check();
  }
  return new_error;
}
References v8::base::args, v8::internal::Isolate::clear_exception(), v8::internal::Isolate::clear_pending_message(), Construct(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::internal::Isolate::factory(), v8::internal::MessageFormatter::Format(), GetFormattedStack(), v8::internal::Isolate::has_exception(), v8::internal::index, v8::internal::IsNullOrUndefined(), v8::internal::IsPrimitive(), v8::Just(), kDisabled, kEnabled, v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::Object::NoSideEffectsToString(), v8::internal::Object::SetProperty(), v8::internal::SKIP_NONE, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::v8_flags.
Referenced by v8::internal::Factory::ShadowRealmNewTypeErrorCopy().
ThrowLoadFromNullOrUndefined()
Tagged< Object > v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined (Isolate * isolate, DirectHandle< Object > object, MaybeDirectHandle< Object > key) [static]
Definition at line 1007 of file messages.cc.
                                   {
  DCHECK(IsNullOrUndefined(*object));
  MaybeDirectHandle<String> maybe_property_name;
  // Try to extract the property name from the given key, if any.
  DirectHandle<Object> key_handle;
  if (key.ToHandle(&key_handle)) {
    if (IsString(*key_handle)) {
      maybe_property_name = Cast<String>(key_handle);
    } else {
      maybe_property_name =
          Object::NoSideEffectsToMaybeString(isolate, key_handle);
    }
  }
  DirectHandle<String> callsite;
  // Inline the RenderCallSite logic here so that we can additionally access the
  // destructuring property.
  bool location_computed = false;
  bool is_destructuring = false;
  MessageLocation location;
  if (ComputeLocation(isolate, &location)) {
    location_computed = true;
    UnoptimizedCompileFlags flags = UnoptimizedCompileFlags::ForFunctionCompile(
        isolate, *location.shared());
    flags.set_is_reparse(true);
    UnoptimizedCompileState compile_state;
    ReusableUnoptimizedCompileState reusable_state(isolate);
    ParseInfo info(isolate, flags, &compile_state, &reusable_state);
    if (parsing::ParseAny(&info, location.shared(), isolate,
                          parsing::ReportStatisticsMode::kNo)) {
      info.ast_value_factory()->Internalize(isolate);
      CallPrinter printer(isolate, location.shared()->IsUserJavaScript());
      DirectHandle<String> str =
          printer.Print(info.literal(), location.start_pos());
      int pos = -1;
      is_destructuring = printer.destructuring_assignment() != nullptr;
      if (is_destructuring) {
        // If we don't have one yet, try to extract the property name from the
        // destructuring property in the AST.
        ObjectLiteralProperty* destructuring_prop =
            printer.destructuring_prop();
        if (maybe_property_name.is_null() && destructuring_prop != nullptr &&
            destructuring_prop->key()->IsPropertyName()) {
          maybe_property_name = destructuring_prop->key()
                                    ->AsLiteral()
                                    ->AsRawPropertyName()
                                    ->string();
          // Change the message location to point at the property name.
          pos = destructuring_prop->key()->position();
        }
        if (maybe_property_name.is_null()) {
          // Change the message location to point at the destructured value.
          pos = printer.destructuring_assignment()->value()->position();
        }
        // If we updated the pos to a valid pos, rewrite the location.
        if (pos != -1) {
          location = MessageLocation(location.script(), pos, pos + 1,
                                     location.shared());
        }
      }
      if (str->length() > 0) callsite = str;
    }
  }
  if (callsite.is_null()) {
    callsite = BuildDefaultCallSite(isolate, object);
  }
  DirectHandle<JSObject> error;
  DirectHandle<String> property_name;
  if (is_destructuring) {
    if (maybe_property_name.ToHandle(&property_name)) {
      error = isolate->factory()->NewTypeError(
          MessageTemplate::kNonCoercibleWithProperty, property_name, callsite,
          object);
    } else {
      error = isolate->factory()->NewTypeError(MessageTemplate::kNonCoercible,
                                               callsite, object);
    }
  } else {
    if (!key.ToHandle(&key_handle) ||
        !maybe_property_name.ToHandle(&property_name)) {
      error = isolate->factory()->NewTypeError(
          MessageTemplate::kNonObjectPropertyLoad, object);
    } else if (*key_handle == ReadOnlyRoots(isolate).iterator_symbol()) {
      error = NewIteratorError(isolate, object);
    } else {
      error = isolate->factory()->NewTypeError(
          MessageTemplate::kNonObjectPropertyLoadWithProperty, object,
          property_name);
    }
  }
  if (location_computed) {
    isolate->ThrowAt(error, &location);
  } else {
    isolate->Throw(*error);
  }
  return ReadOnlyRoots(isolate).exception();
}
References v8::internal::ParseInfo::ast_value_factory(), v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::anonymous_namespace{messages.cc}::ComputeLocation(), v8::internal::DCHECK(), v8::internal::CallPrinter::destructuring_assignment(), v8::internal::CallPrinter::destructuring_prop(), v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForFunctionCompile(), v8::internal::AstValueFactory::Internalize(), v8::internal::DirectHandle< T >::is_null(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::IsNullOrUndefined(), v8::internal::Expression::IsPropertyName(), v8::internal::LiteralProperty::key(), v8::internal::key, v8::internal::parsing::kNo, v8::internal::ParseInfo::literal(), NewIteratorError(), v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::parsing::ParseAny(), v8::internal::AstNode::position(), v8::internal::CallPrinter::Print(), v8::internal::MessageLocation::script(), v8::internal::MessageLocation::shared(), v8::internal::MessageLocation::start_pos(), v8::internal::Isolate::Throw(), v8::internal::Isolate::ThrowAt(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::Assignment::value().
Referenced by v8::internal::Runtime::GetObjectProperty(), v8::internal::LoadIC::Load(), and v8::internal::RUNTIME_FUNCTION().
ThrowSpreadArgError()
Tagged< Object > v8::internal::ErrorUtils::ThrowSpreadArgError (Isolate * isolate, MessageTemplate id, DirectHandle< Object > object) [static]
Definition at line 948 of file messages.cc.
                                                                            {
  MessageLocation location;
  DirectHandle<String> callsite;
  if (ComputeLocation(isolate, &location)) {
    UnoptimizedCompileFlags flags = UnoptimizedCompileFlags::ForFunctionCompile(
        isolate, *location.shared());
    flags.set_is_reparse(true);
    UnoptimizedCompileState compile_state;
    ReusableUnoptimizedCompileState reusable_state(isolate);
    ParseInfo info(isolate, flags, &compile_state, &reusable_state);
    if (parsing::ParseAny(&info, location.shared(), isolate,
                          parsing::ReportStatisticsMode::kNo)) {
      info.ast_value_factory()->Internalize(isolate);
      CallPrinter printer(isolate, location.shared()->IsUserJavaScript(),
                          CallPrinter::SpreadErrorInArgsHint::kErrorInArgs);
      DirectHandle<String> str =
          printer.Print(info.literal(), location.start_pos());
      callsite =
          str->length() > 0 ? str : BuildDefaultCallSite(isolate, object);
      if (printer.spread_arg() != nullptr) {
        // Change the message location to point at the property name.
        int pos = printer.spread_arg()->position();
        location =
            MessageLocation(location.script(), pos, pos + 1, location.shared());
      }
    } else {
      callsite = BuildDefaultCallSite(isolate, object);
    }
  }
  isolate->ThrowAt(isolate->factory()->NewTypeError(id, callsite, object),
                   &location);
  return ReadOnlyRoots(isolate).exception();
}
References v8::internal::ParseInfo::ast_value_factory(), v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::anonymous_namespace{messages.cc}::ComputeLocation(), v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForFunctionCompile(), v8::internal::AstValueFactory::Internalize(), v8::internal::CallPrinter::kErrorInArgs, v8::internal::parsing::kNo, v8::internal::ParseInfo::literal(), v8::internal::parsing::ParseAny(), v8::internal::AstNode::position(), v8::internal::CallPrinter::Print(), v8::internal::MessageLocation::script(), v8::internal::MessageLocation::shared(), v8::internal::CallPrinter::spread_arg(), v8::internal::MessageLocation::start_pos(), and v8::internal::Isolate::ThrowAt().
Referenced by v8::internal::RUNTIME_FUNCTION().
ToString()
MaybeHandle< String > v8::internal::ErrorUtils::ToString (Isolate * isolate, DirectHandle< Object > recv, ToStringMessageSource message_source = ToStringMessageSource::kCurrentMessageProperty) [static]
Definition at line 659 of file messages.cc.
                                                                               {
  // 1. Let O be the this value.
  // 2. If Type(O) is not Object, throw a TypeError exception.
  DirectHandle<JSReceiver> recv;
  if (!TryCast<JSReceiver>(receiver, &recv)) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kIncompatibleMethodReceiver,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "Error.prototype.toString"),
                                 receiver));
  }
  // 3. Let name be ? Get(O, "name").
  // 4. If name is undefined, let name be "Error"; otherwise let name be
  // ? ToString(name).
  DirectHandle<String> name_key = isolate->factory()->name_string();
  Handle<String> name_default = isolate->factory()->Error_string();
  Handle<String> name;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, name,
      GetStringPropertyOrDefault(isolate, recv, name_key, name_default));
  // 5. Let msg be ? Get(O, "message").
  // 6. If msg is undefined, let msg be the empty String; otherwise let msg be
  // ? ToString(msg).
  Handle<String> msg;
  Handle<String> msg_default = isolate->factory()->empty_string();
  if (message_source == ToStringMessageSource::kPreferOriginalMessage) {
    // V8-specific extension for Error.stack: Use the original message with
    // which the Error constructor was called. This keeps Error.stack consistent
    // w.r.t. "message" property changes regardless of the time when Error.stack
    // is accessed the first time.
    //
    // If |recv| was not constructed with %Error%, use the "message" property.
    LookupIterator it(isolate, LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR,
                      recv, isolate->factory()->error_message_symbol());
    Handle<Object> result = JSReceiver::GetDataProperty(&it);
    if (it.IsFound() && IsUndefined(*result, isolate)) {
      msg = msg_default;
    } else if (it.IsFound()) {
      ASSIGN_RETURN_ON_EXCEPTION(isolate, msg,
                                 Object::ToString(isolate, result));
    }
  }
  if (msg.is_null()) {
    DirectHandle<String> msg_key = isolate->factory()->message_string();
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, msg,
        GetStringPropertyOrDefault(isolate, recv, msg_key, msg_default));
  }
  // 7. If name is the empty String, return msg.
  // 8. If msg is the empty String, return name.
  if (name->length() == 0) return msg;
  if (msg->length() == 0) return name;
  // 9. Return the result of concatenating name, the code unit 0x003A (COLON),
  // the code unit 0x0020 (SPACE), and msg.
  IncrementalStringBuilder builder(isolate);
  builder.AppendString(name);
  builder.AppendCStringLiteral(": ");
  builder.AppendString(msg);
  Handle<String> result;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, result,
                             indirect_handle(builder.Finish(), isolate));
  return result;
}
References v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::anonymous_namespace{messages.cc}::GetStringPropertyOrDefault(), v8::internal::indirect_handle(), v8::internal::HandleBase::is_null(), v8::internal::LookupIterator::IsFound(), kPreferOriginalMessage, v8::internal::name, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, v8::base::internal::result, THROW_NEW_ERROR, and v8::Value::ToString().
Referenced by v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::BUILTIN(), v8::internal::Genesis::ConfigureApiObject(), and FormatStackTrace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/messages.h
/mnt/V8SourceCode/src/execution/messages.cc