v8::internal::Sweeper::MinorSweeperJob Class Reference
Public Member Functions
MinorSweeperJob (Isolate *isolate, Sweeper *sweeper)
~MinorSweeperJob () override=default
MinorSweeperJob (const MinorSweeperJob &)=delete
MinorSweeperJob & operator= (const MinorSweeperJob &)=delete
void Run (JobDelegate *delegate) final
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Static Public Attributes
static constexpr int kMaxTasks = 1
Private Member Functions
void RunImpl (JobDelegate *delegate, bool is_main_thread)
Private Attributes
Sweeper *const sweeper_
std::vector< ConcurrentMinorSweeper > & concurrent_sweepers
GCTracer *const tracer_
const uint64_t trace_id_
Detailed Description
Definition at line 184 of file sweeper.cc.
Constructor & Destructor Documentation
MinorSweeperJob() [1/2]
v8::internal::Sweeper::MinorSweeperJob::MinorSweeperJob (Isolate * isolate, Sweeper * sweeper) [inline]
Definition at line 188 of file sweeper.cc.
      : sweeper_(sweeper),
        concurrent_sweepers(
            sweeper_->minor_sweeping_state_.concurrent_sweepers()),
        tracer_(isolate->heap()->tracer()),
        trace_id_(sweeper_->minor_sweeping_state_.background_trace_id()) {
    DCHECK_LE(concurrent_sweepers.size(), kMaxTasks);
  }
References concurrent_sweepers, DCHECK_LE, and kMaxTasks.
 MinorSweeperJob()
v8::internal::Sweeper::MinorSweeperJob::~MinorSweeperJob () [override], [default]
MinorSweeperJob() [2/2]
v8::internal::Sweeper::MinorSweeperJob::MinorSweeperJob (const MinorSweeperJob &) [delete]
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::Sweeper::MinorSweeperJob::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 215 of file sweeper.cc.
                                                               {
    static constexpr int kPagePerTask = 2;
    return std::min<size_t>(
        concurrent_sweepers.size(),
        worker_count +
            (sweeper_->ConcurrentMinorSweepingPageCount() + kPagePerTask - 1) /
                kPagePerTask);
  }
References concurrent_sweepers, v8::internal::Sweeper::ConcurrentMinorSweepingPageCount(), and sweeper_.
operator=()
MinorSweeperJob& v8::internal::Sweeper::MinorSweeperJob::operator= (const MinorSweeperJob &) [delete]
Run()
void v8::internal::Sweeper::MinorSweeperJob::Run (JobDelegate * delegate) [inline], [final], [virtual]
Implements v8::JobTask.
Definition at line 202 of file sweeper.cc.
                                        {
    DCHECK_IMPLIES(
        delegate->IsJoiningThread(),
        sweeper_->heap_->IsMainThread() ||
            (!sweeper_->heap_->isolate()->is_shared_space_isolate() &&
             sweeper_->heap_->isolate()
                 ->shared_space_isolate()
                 ->heap()
                 ->IsMainThread()));
    RunImpl(delegate,
            delegate->IsJoiningThread() && sweeper_->heap_->IsMainThread());
  }
References DCHECK_IMPLIES, v8::internal::Isolate::heap(), v8::internal::Sweeper::heap_, v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::IsMainThread(), v8::internal::Heap::isolate(), RunImpl(), v8::internal::Isolate::shared_space_isolate(), and sweeper_.
RunImpl()
void v8::internal::Sweeper::MinorSweeperJob::RunImpl (JobDelegate * delegate, bool is_main_thread) [inline], [private]
Definition at line 225 of file sweeper.cc.
                                                           {
    DCHECK(sweeper_->minor_sweeping_in_progress());
    const int offset = delegate->GetTaskId();
    DCHECK_LT(offset, concurrent_sweepers.size());
    ConcurrentMinorSweeper& concurrent_sweeper = concurrent_sweepers[offset];
    TRACE_GC_EPOCH_WITH_FLOW(
        tracer_, sweeper_->GetTracingScope(NEW_SPACE, is_main_thread),
        is_main_thread ? ThreadKind::kMain : ThreadKind::kBackground, trace_id_,
        TRACE_EVENT_FLAG_FLOW_IN);
    // Set the current isolate such that trusted pointer tables etc are
    // available and the cage base is set correctly for multi-cage mode.
    SetCurrentIsolateScope isolate_scope(sweeper_->heap_->isolate());
    if (!concurrent_sweeper.ConcurrentSweepSpace(delegate)) return;
    concurrent_sweeper.ConcurrentSweepPromotedPages(delegate);
  }
References concurrent_sweepers, v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepPromotedPages(), v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepSpace(), v8::internal::DCHECK(), DCHECK_LT, v8::JobDelegate::GetTaskId(), v8::internal::Sweeper::GetTracingScope(), v8::internal::Sweeper::heap_, v8::internal::Heap::isolate(), v8::internal::kBackground, v8::internal::kMain, v8::internal::Sweeper::minor_sweeping_in_progress(), v8::internal::NEW_SPACE, sweeper_, TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, trace_id_, and tracer_.
Referenced by Run().
Member Data Documentation
concurrent_sweepers
std::vector<ConcurrentMinorSweeper>& v8::internal::Sweeper::MinorSweeperJob::concurrent_sweepers [private]
Definition at line 243 of file sweeper.cc.
Referenced by GetMaxConcurrency(), MinorSweeperJob(), and RunImpl().
kMaxTasks
constexpr int v8::internal::Sweeper::MinorSweeperJob::kMaxTasks = 1 [static], [constexpr]
Definition at line 186 of file sweeper.cc.
Referenced by MinorSweeperJob().
sweeper_
Sweeper* const v8::internal::Sweeper::MinorSweeperJob::sweeper_ [private]
Definition at line 242 of file sweeper.cc.
Referenced by GetMaxConcurrency(), Run(), and RunImpl().
trace_id_
const uint64_t v8::internal::Sweeper::MinorSweeperJob::trace_id_ [private]
Definition at line 245 of file sweeper.cc.
Referenced by RunImpl().
tracer_
GCTracer* const v8::internal::Sweeper::MinorSweeperJob::tracer_ [private]
Definition at line 244 of file sweeper.cc.
Referenced by RunImpl().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/sweeper.cc