v8::internal::anonymous_namespace{regexp-ast.cc}::RegExpUnparser Class Reference
Public Member Functions
RegExpUnparser (std::ostream &os, Zone *zone)
void VisitCharacterRange (CharacterRange that)
Private Attributes
std::ostream & os_
Zone * zone_
Detailed Description
Definition at line 144 of file regexp-ast.cc.
Constructor & Destructor Documentation
RegExpUnparser()
v8::internal::anonymous_namespace{regexp-ast.cc}::RegExpUnparser::RegExpUnparser (std::ostream & os, Zone * zone) [inline]
Definition at line 146 of file regexp-ast.cc.
: os_(os), zone_(zone) {}
Member Function Documentation
VisitCharacterRange()
void v8::internal::RegExpUnparser::VisitCharacterRange (CharacterRange that)
Definition at line 180 of file regexp-ast.cc.
                                                            {
  os_ << AsUC32(that.from());
  if (!that.IsSingleton()) {
    os_ << "-" << AsUC32(that.to());
  }
}
References v8::internal::CharacterRange::from(), v8::internal::CharacterRange::IsSingleton(), and v8::internal::CharacterRange::to().
Member Data Documentation
os_
std::ostream& v8::internal::anonymous_namespace{regexp-ast.cc}::RegExpUnparser::os_ [private]
Definition at line 152 of file regexp-ast.cc.
zone_
Zone* v8::internal::anonymous_namespace{regexp-ast.cc}::RegExpUnparser::zone_ [private]
Definition at line 153 of file regexp-ast.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-ast.cc