v8::internal::Scope::Snapshot Class Reference
#include <scopes.h>
Public Member Functions
Snapshot (Scope *scope)
Snapshot (const Snapshot &)=delete
Snapshot (Snapshot &&)=delete
~Snapshot ()
void Reparent (DeclarationScope *new_parent)
Private Attributes
Scope * outer_scope_
Scope * declaration_scope_
Scope * top_inner_scope_
UnresolvedList::Iterator top_unresolved_
base::ThreadedList< Variable >::Iterator top_local_
bool calls_eval_
bool sloppy_eval_can_extend_vars_
Detailed Description
Definition at line 123 of file scopes.h.
Constructor & Destructor Documentation
Snapshot() [1/3]
v8::internal::Scope::Snapshot::Snapshot (Scope * scope) [inline], [explicit]
Definition at line 1367 of file scopes.h.
    : outer_scope_(scope),
      declaration_scope_(scope->GetDeclarationScope()),
      top_inner_scope_(scope->inner_scope_),
      top_unresolved_(scope->unresolved_list_.end()),
      top_local_(scope->GetClosureScope()->locals_.end()),
      calls_eval_(outer_scope_->calls_eval_),
      sloppy_eval_can_extend_vars_(
          declaration_scope_->sloppy_eval_can_extend_vars_) {
  // Reset in order to record (sloppy) eval calls during this Snapshot's
  // lifetime.
  outer_scope_->calls_eval_ = false;
  declaration_scope_->sloppy_eval_can_extend_vars_ = false;
}
References v8::internal::Scope::calls_eval_, declaration_scope_, outer_scope_, and v8::internal::Scope::sloppy_eval_can_extend_vars_.
Snapshot() [2/3]
v8::internal::Scope::Snapshot::Snapshot (const Snapshot &) [delete]
Snapshot() [3/3]
v8::internal::Scope::Snapshot::Snapshot (Snapshot &&) [delete]
 Snapshot()
v8::internal::Scope::Snapshot::~Snapshot () [inline]
Definition at line 131 of file scopes.h.
                {
      // Restore eval flags from before the scope was active.
      if (sloppy_eval_can_extend_vars_) {
        declaration_scope_->is_dynamic_scope_ = true;
        declaration_scope_->sloppy_eval_can_extend_vars_ = true;
      }
      if (calls_eval_) {
        outer_scope_->calls_eval_ = true;
      }
    }
Member Function Documentation
Reparent()
void v8::internal::Scope::Snapshot::Reparent (DeclarationScope * new_parent)
Definition at line 932 of file scopes.cc.
                                                         {
  DCHECK_EQ(new_parent, outer_scope_->inner_scope_);
  DCHECK_EQ(new_parent->outer_scope_, outer_scope_);
  DCHECK_EQ(new_parent, new_parent->GetClosureScope());
  DCHECK_NULL(new_parent->inner_scope_);
  DCHECK(new_parent->unresolved_list_.is_empty());
  Scope* inner_scope = new_parent->sibling_;
  if (inner_scope != top_inner_scope_) {
    for (; inner_scope->sibling() != top_inner_scope_;
         inner_scope = inner_scope->sibling()) {
      inner_scope->outer_scope_ = new_parent;
      if (inner_scope->inner_scope_calls_eval_) {
        new_parent->inner_scope_calls_eval_ = true;
      }
      DCHECK_NE(inner_scope, new_parent);
    }
    inner_scope->outer_scope_ = new_parent;
    if (inner_scope->inner_scope_calls_eval_) {
      new_parent->inner_scope_calls_eval_ = true;
    }
    new_parent->inner_scope_ = new_parent->sibling_;
    inner_scope->sibling_ = nullptr;
    // Reset the sibling rather than the inner_scope_ since we
    // want to keep new_parent there.
    new_parent->sibling_ = top_inner_scope_;
  }
  new_parent->unresolved_list_.MoveTail(&outer_scope_->unresolved_list_,
                                        top_unresolved_);
  // Move temporaries allocated for complex parameter initializers.
  DeclarationScope* outer_closure = outer_scope_->GetClosureScope();
  for (auto it = top_local_; it != outer_closure->locals()->end(); ++it) {
    Variable* local = *it;
    DCHECK_EQ(VariableMode::kTemporary, local->mode());
    DCHECK_EQ(local->scope(), local->scope()->GetClosureScope());
    DCHECK_NE(local->scope(), new_parent);
    local->set_scope(new_parent);
  }
  new_parent->locals_.MoveTail(outer_closure->locals(), top_local_);
  outer_closure->locals_.Rewind(top_local_);
  // Move eval calls since Snapshot's creation into new_parent.
  if (outer_scope_->calls_eval_) {
    new_parent->RecordEvalCall();
    outer_scope_->calls_eval_ = false;
    declaration_scope_->sloppy_eval_can_extend_vars_ = false;
    declaration_scope_->is_dynamic_scope_ = false;
  }
}
References v8::internal::Scope::calls_eval_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, DCHECK_NULL, declaration_scope_, v8::internal::compiler::end(), v8::internal::Scope::GetClosureScope(), v8::internal::Scope::inner_scope(), v8::internal::Scope::inner_scope_, v8::internal::Scope::inner_scope_calls_eval_, v8::internal::Scope::is_dynamic_scope_, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::is_empty(), v8::internal::kTemporary, v8::internal::Scope::locals(), v8::internal::Scope::locals_, v8::internal::Variable::mode(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::MoveTail(), outer_scope_, v8::internal::Scope::outer_scope_, v8::internal::Scope::RecordEvalCall(), v8::internal::Variable::scope(), v8::internal::Variable::set_scope(), v8::internal::Scope::sibling(), v8::internal::Scope::sibling_, v8::internal::Scope::sloppy_eval_can_extend_vars_, top_inner_scope_, top_local_, top_unresolved_, and v8::internal::Scope::unresolved_list_.
Referenced by v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation(), and v8::internal::ParserBase< Impl >::ParsePrimaryExpression().
Member Data Documentation
calls_eval_
bool v8::internal::Scope::Snapshot::calls_eval_ [private]
Definition at line 156 of file scopes.h.
declaration_scope_
Scope* v8::internal::Scope::Snapshot::declaration_scope_ [private]
Definition at line 146 of file scopes.h.
Referenced by Reparent(), and Snapshot().
outer_scope_
Scope* v8::internal::Scope::Snapshot::outer_scope_ [private]
Definition at line 145 of file scopes.h.
Referenced by Reparent(), and Snapshot().
sloppy_eval_can_extend_vars_
bool v8::internal::Scope::Snapshot::sloppy_eval_can_extend_vars_ [private]
Definition at line 157 of file scopes.h.
top_inner_scope_
Scope* v8::internal::Scope::Snapshot::top_inner_scope_ [private]
Definition at line 147 of file scopes.h.
Referenced by Reparent().
top_local_
base::ThreadedList<Variable>::Iterator v8::internal::Scope::Snapshot::top_local_ [private]
Definition at line 149 of file scopes.h.
Referenced by Reparent().
top_unresolved_
UnresolvedList::Iterator v8::internal::Scope::Snapshot::top_unresolved_ [private]
Definition at line 148 of file scopes.h.
Referenced by Reparent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/scopes.h
/mnt/V8SourceCode/src/ast/scopes.cc