v8::internal::YMMRegister Class Reference
#include <register-x64.h>
Static Public Member Functions
static constexpr YMMRegister from_code (int code)
static constexpr YMMRegister from_xmm (XMMRegister xmm)
Private Member Functions
constexpr YMMRegister (int code)
Friends
class XMMRegister
Additional Inherited Members
Detailed Description
Definition at line 235 of file register-x64.h.
Constructor & Destructor Documentation
YMMRegister()
constexpr v8::internal::YMMRegister::YMMRegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 248 of file register-x64.h.
: XMMRegister(code) {}
Referenced by from_code(), and from_xmm().
Member Function Documentation
from_code()
static constexpr YMMRegister v8::internal::YMMRegister::from_code (int code) [inline], [static], [constexpr]
Definition at line 237 of file register-x64.h.
                                                   {
    V8_ASSUME(code >= 0 && code < XMMRegister::kNumRegisters);
    return YMMRegister(code);
  }
References v8::internal::RegisterBase< XMMRegister, kDoubleAfterLast >::code(), v8::internal::RegisterBase< XMMRegister, kDoubleAfterLast >::kNumRegisters, V8_ASSUME, and YMMRegister().
Referenced by v8::internal::wasm::F16x8BinOpViaF32(), v8::internal::wasm::F16x8CmpOpViaF32(), v8::internal::compiler::operator<<(), and v8::internal::compiler::GraphC1Visualizer::PrintLiveRange().
from_xmm()
static constexpr YMMRegister v8::internal::YMMRegister::from_xmm (XMMRegister xmm) [inline], [static], [constexpr]
Definition at line 242 of file register-x64.h.
                                                         {
    return YMMRegister(xmm.code());
  }
References YMMRegister().
Friends And Related Function Documentation
XMMRegister
friend class XMMRegister [friend]
Definition at line 247 of file register-x64.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/x64/register-x64.h