v8::internal::JSSegments Class Reference
#include <js-segments.h>
Public Member Functions
Handle< String > GranularityAsString (Isolate *isolate) const
void set_granularity (JSSegmenter::Granularity granularity)
JSSegmenter::Granularity granularity () const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSSegments > Create (Isolate *isolate, DirectHandle< JSSegmenter > segmenter, DirectHandle< String > string)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Containing (Isolate *isolate, DirectHandle< JSSegments > segments_holder, double n)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSSegmentDataObject > CreateSegmentDataObject (Isolate *isolate, JSSegmenter::Granularity granularity, icu::BreakIterator *break_iterator, DirectHandle< String > input_string, const icu::UnicodeString &unicode_string, int32_t start_index, int32_t end_index)
Detailed Description
Definition at line 33 of file js-segments.h.
Member Function Documentation
Containing()
MaybeDirectHandle< Object > v8::internal::JSSegments::Containing (Isolate * isolate, DirectHandle< JSSegments > segments_holder, double n) [static]
Definition at line 63 of file js-segments.cc.
                                                                          {
  // 5. Let len be the length of string.
  int32_t len = segments->unicode_string()->raw()->length();
  // 7. If n < 0 or n ≥ len, return undefined.
  if (n_double < 0 || n_double >= len) {
    return isolate->factory()->undefined_value();
  }
  int32_t n = static_cast<int32_t>(n_double);
  // n may point to the surrogate tail- adjust it back to the lead.
  n = segments->unicode_string()->raw()->getChar32Start(n);
  icu::BreakIterator* break_iterator = segments->icu_break_iterator()->raw();
  // 8. Let startIndex be ! FindBoundary(segmenter, string, n, before).
  int32_t start_index =
      break_iterator->isBoundary(n) ? n : break_iterator->preceding(n);
  // 9. Let endIndex be ! FindBoundary(segmenter, string, n, after).
  int32_t end_index = break_iterator->following(n);
  // 10. Return ! CreateSegmentDataObject(segmenter, string, startIndex,
  // endIndex).
  return CreateSegmentDataObject(
      isolate, segments->granularity(), break_iterator,
      direct_handle(segments->raw_string(), isolate),
      *(segments->unicode_string()->raw()), start_index, end_index);
}
References CreateSegmentDataObject(), v8::internal::direct_handle(), and v8::internal::Isolate::factory().
Referenced by v8::internal::BUILTIN().
Create()
MaybeDirectHandle< JSSegments > v8::internal::JSSegments::Create (Isolate * isolate, DirectHandle< JSSegmenter > segmenter, DirectHandle< String > string) [static]
Definition at line 29 of file js-segments.cc.
                                 {
  std::shared_ptr<icu::BreakIterator> break_iterator{
      segmenter->icu_break_iterator()->raw()->clone()};
  DCHECK_NOT_NULL(break_iterator);
  DirectHandle<Managed<icu::UnicodeString>> unicode_string =
      Intl::SetTextToBreakIterator(isolate, string, break_iterator.get());
  DirectHandle<Managed<icu::BreakIterator>> managed_break_iterator =
      Managed<icu::BreakIterator>::From(isolate, 0, std::move(break_iterator));
  // 1. Let internalSlotsList be « [[SegmentsSegmenter]], [[SegmentsString]] ».
  // 2. Let segments be ! ObjectCreate(%Segments.prototype%, internalSlotsList).
  DirectHandle<Map> map(isolate->native_context()->intl_segments_map(),
                        isolate);
  DirectHandle<JSObject> result = isolate->factory()->NewJSObjectFromMap(map);
  DirectHandle<JSSegments> segments = Cast<JSSegments>(result);
  segments->set_flags(0);
  // 3. Set segments.[[SegmentsSegmenter]] to segmenter.
  segments->set_icu_break_iterator(*managed_break_iterator);
  segments->set_granularity(segmenter->granularity());
  // 4. Set segments.[[SegmentsString]] to string.
  segments->set_raw_string(*string);
  segments->set_unicode_string(*unicode_string);
  // 5. Return segments.
  return segments;
}
References DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::internal::Isolate::native_context(), v8::internal::Factory::NewJSObjectFromMap(), v8::base::internal::result, v8::internal::Intl::SetTextToBreakIterator(), and v8::internal::unicode_string.
Referenced by v8::internal::BUILTIN().
CreateSegmentDataObject()
MaybeDirectHandle< JSSegmentDataObject > v8::internal::JSSegments::CreateSegmentDataObject (Isolate * isolate, JSSegmenter::Granularity granularity, icu::BreakIterator * break_iterator, DirectHandle< String > input_string, const icu::UnicodeString & unicode_string, int32_t start_index, int32_t end_index) [static]
Definition at line 109 of file js-segments.cc.
                       {
  Factory* factory = isolate->factory();
  // 1. Let len be the length of string.
  // 2. Assert: startIndex ≥ 0.
  DCHECK_GE(start_index, 0);
  // 3. Assert: endIndex ≤ len.
  DCHECK_LE(end_index, unicode_string.length());
  // 4. Assert: startIndex < endIndex.
  DCHECK_LT(start_index, end_index);
  // 5. Let result be ! ObjectCreate(%ObjectPrototype%).
  DirectHandle<Map> map(
      granularity == JSSegmenter::Granularity::WORD
          ? isolate->native_context()->intl_segment_data_object_wordlike_map()
          : isolate->native_context()->intl_segment_data_object_map(),
      isolate);
  DirectHandle<JSSegmentDataObject> result =
      Cast<JSSegmentDataObject>(factory->NewJSObjectFromMap(map));
  // 6. Let segment be the String value equal to the substring of string
  // consisting of the code units at indices startIndex (inclusive) through
  // endIndex (exclusive).
  DirectHandle<String> segment;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, segment,
      Intl::ToString(isolate, unicode_string, start_index, end_index));
  DirectHandle<Number> index = factory->NewNumberFromInt(start_index);
  // 7. Perform ! CreateDataPropertyOrThrow(result, "segment", segment).
  DisallowGarbageCollection no_gc;
  Tagged<JSSegmentDataObject> raw = Cast<JSSegmentDataObject>(*result);
  raw->set_segment(*segment);
  // 8. Perform ! CreateDataPropertyOrThrow(result, "index", startIndex).
  raw->set_index(*index);
  // 9. Perform ! CreateDataPropertyOrThrow(result, "input", string).
  raw->set_input(*input_string);
  // 10. Let granularity be segmenter.[[SegmenterGranularity]].
  // 11. If granularity is "word", then
  if (granularity == JSSegmenter::Granularity::WORD) {
    // a. Let isWordLike be a Boolean value indicating whether the segment in
    // string is "word-like" according to locale segmenter.[[Locale]].
    DirectHandle<Boolean> is_word_like =
        factory->ToBoolean(CurrentSegmentIsWordLike(break_iterator));
    // b. Perform ! CreateDataPropertyOrThrow(result, "isWordLike", isWordLike).
    Cast<JSSegmentDataObjectWithIsWordLike>(raw)->set_is_word_like(
        *is_word_like);
  }
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::anonymous_namespace{js-segments.cc}::CurrentSegmentIsWordLike(), DCHECK_GE, DCHECK_LE, DCHECK_LT, v8::internal::Isolate::factory(), granularity(), v8::internal::index, v8::internal::Isolate::native_context(), v8::internal::Factory::NewJSObjectFromMap(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::FactoryBase< Impl >::ToBoolean(), v8::internal::Intl::ToString(), v8::internal::unicode_string, and v8::internal::JSSegmenter::WORD.
Referenced by Containing(), and v8::internal::JSSegmentIterator::Next().
granularity()
JSSegmenter::Granularity v8::internal::JSSegments::granularity () const [inline]
Definition at line 41 of file js-segments-inl.h.
                                                            {
  return GranularityBits::decode(flags());
}
References v8::internal::flags.
Referenced by CreateSegmentDataObject(), and GranularityAsString().
GranularityAsString()
Handle< String > v8::internal::JSSegments::GranularityAsString (Isolate * isolate) const
Definition at line 165 of file js-segments.cc.
                                                                     {
  return JSSegmenter::GetGranularityString(isolate, granularity());
}
References v8::internal::JSSegmenter::GetGranularityString(), and granularity().
set_granularity()
kUnicodeStringOffset void v8::internal::JSSegments::set_granularity (JSSegmenter::Granularity granularity) [inline]
Definition at line 34 of file js-segments-inl.h.
                                                                          {
  DCHECK(GranularityBits::is_valid(granularity));
  int hints = flags();
  hints = GranularityBits::update(hints, granularity);
  set_flags(hints);
}
References v8::internal::DCHECK(), and v8::internal::flags.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-segments.h
/mnt/V8SourceCode/src/objects/js-segments-inl.h
/mnt/V8SourceCode/src/objects/js-segments.cc