v8::EscapableHandleScope Class Reference
#include <v8-local-handle.h>
Public Member Functions
EscapableHandleScope (Isolate *isolate)
~EscapableHandleScope ()=default
template<class T >
Local< T > Escape (Local< T > value)
template<class T >
MaybeLocal< T > EscapeMaybe (MaybeLocal< T > value)
Additional Inherited Members
Detailed Description
Definition at line 768 of file v8-local-handle.h.
Constructor & Destructor Documentation
EscapableHandleScope()
v8::EscapableHandleScope::EscapableHandleScope (Isolate * isolate) [inline], [explicit]
Definition at line 771 of file v8-local-handle.h.
      : EscapableHandleScopeBase(isolate) {}
 EscapableHandleScope()
v8::EscapableHandleScope::~EscapableHandleScope () [inline], [default]
Member Function Documentation
Escape()
template<class T >
Local<T> v8::EscapableHandleScope::Escape (Local< T > value) [inline]
Definition at line 775 of file v8-local-handle.h.
                                            {
#ifdef V8_ENABLE_DIRECT_HANDLE
    return value;
#else
    if (value.IsEmpty()) return value;
    return Local<T>::FromSlot(EscapeSlot(value.slot()));
#endif
  }
References v8::Local< T >::FromSlot(), and v8::internal::value.
Referenced by v8::Shell::CreateEvaluationContext(), v8::AsyncHooks::CreateHook(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8_inspector::V8InspectorImpl::getAssociatedExceptionData(), and v8_inspector::V8DebuggerScript::setSource().
EscapeMaybe()
template<class T >
MaybeLocal<T> v8::EscapableHandleScope::EscapeMaybe (MaybeLocal< T > value) [inline]
Definition at line 785 of file v8-local-handle.h.
                                                           {
    return Escape(value.FromMaybe(Local<T>()));
  }
References v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-local-handle.h