v8::internal::StaticRootsTableGen Class Reference
#include <static-roots-gen.h>
Static Public Member Functions
static void write (Isolate *isolate, const char *file)
Detailed Description
Definition at line 13 of file static-roots-gen.h.
Member Function Documentation
write()
void v8::internal::StaticRootsTableGen::write (Isolate * isolate, const char * file) [static]
Definition at line 53 of file static-roots-gen.cc.
                                                                  {
  CHECK_WITH_MSG(!V8_STATIC_ROOTS_BOOL,
                 "Re-generating the table of roots is only supported in builds "
                 "with v8_enable_static_roots disabled");
  CHECK(V8_STATIC_ROOTS_GENERATION_BOOL);
  CHECK(file);
  static_assert(static_cast<int>(RootIndex::kFirstReadOnlyRoot) == 0);
  std::ofstream out(file, std::ios::binary);
  out << "// Copyright 2022 the V8 project authors. All rights reserved.\n"
      << "// Use of this source code is governed by a BSD-style license "
         "that can be\n"
      << "// found in the LICENSE file.\n"
      << "\n"
      << "// This file is automatically generated by "
         "`tools/dev/gen-static-roots.py`. Do\n// not edit manually.\n"
      << "\n"
      << "#ifndef V8_ROOTS_STATIC_ROOTS_H_\n"
      << "#define V8_ROOTS_STATIC_ROOTS_H_\n"
      << "\n"
      << "#include \"src/common/globals.h\"\n"
      << "\n"
      << "#if V8_STATIC_ROOTS_BOOL\n"
      << "\n"
      << "#include \"src/roots/roots.h\"\n"
      << "\n"
      << "// Disabling Wasm or Intl invalidates the contents of "
         "static-roots.h.\n"
      << "// TODO(olivf): To support static roots for multiple build "
         "configurations we\n"
      << "// will need to generate target specific versions of "
         "this file.\n"
      << "static_assert(V8_ENABLE_WEBASSEMBLY);\n"
      << "static_assert(V8_INTL_SUPPORT);\n"
      << "\n"
      << "namespace v8 {\n"
      << "namespace internal {\n"
      << "\n"
      << "struct StaticReadOnlyRoot {\n";
  // Output a symbol for every root. Ordered by ptr to make it easier to see the
  // memory layout of the read only page.
  const auto size = static_cast<int>(RootIndex::kReadOnlyRootsCount);
  StaticRootsTableGenImpl gen(isolate);
  for (auto& entry : gen.sorted_roots()) {
    Tagged_t ptr = entry.first;
    CHECK_LT(ptr, kRegularPageSize);
    const std::list<RootIndex>& roots = entry.second;
    for (RootIndex root : roots) {
      static const char* kPreString = " static constexpr Tagged_t k";
      const std::string& name = gen.camel_name(root);
      size_t ptr_len = ceil(log2(ptr) / 4.0);
      // Full line is: "kPreString|name = 0x.....;"
      size_t len = strlen(kPreString) + name.length() + 5 + ptr_len + 1;
      out << kPreString << name << " =";
      if (len > 80) out << "\n ";
      out << " 0x" << std::hex << ptr << std::dec << ";\n";
    }
  }
  out << "\n";
  out << " static constexpr Tagged_t kFirstAllocatedRoot = 0x" << std::hex
      << gen.sorted_roots().cbegin()->first << std::dec << ";\n";
  out << " static constexpr Tagged_t kLastAllocatedRoot = 0x" << std::hex
      << gen.sorted_roots().crbegin()->first << std::dec << ";\n";
  out << "};\n";
  // Output in order of roots table
  out << "\nstatic constexpr std::array<Tagged_t, " << size
      << "> StaticReadOnlyRootsPointerTable = {\n";
  {
#define ENTRY(_1, _2, CamelName) \
  out << " StaticReadOnlyRoot::k" << #CamelName << ",\n";
    READ_ONLY_ROOT_LIST(ENTRY)
#undef ENTRY
    out << "};\n";
  }
  out << "\n"
      << "} // namespace internal\n"
      << "} // namespace v8\n"
      << "#endif // V8_STATIC_ROOTS_BOOL\n"
      << "#endif // V8_ROOTS_STATIC_ROOTS_H_\n";
}
References v8::internal::StaticRootsTableGenImpl::camel_name(), CHECK, CHECK_LT, CHECK_WITH_MSG, ENTRY, file(), v8::internal::kFirstReadOnlyRoot, v8::internal::kReadOnlyRootsCount, kRegularPageSize, v8::base::ieee754::log2(), v8::internal::name, READ_ONLY_ROOT_LIST, size(), v8::internal::StaticRootsTableGenImpl::sorted_roots(), v8::internal::string, V8_STATIC_ROOTS_BOOL, and V8_STATIC_ROOTS_GENERATION_BOOL.
Referenced by main().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/static-roots-gen.h
/mnt/V8SourceCode/src/snapshot/static-roots-gen.cc