v8::internal::anonymous_namespace{scavenger.cc}::PreciseObjectPinningVisitor Class Reference
Public Member Functions
PreciseObjectPinningVisitor (const Heap *heap, Scavenger &scavenger, ScavengerCollector::PinnedObjects &pinned_objects)
Private Member Functions
void HandlePointer (FullObjectSlot p)
Friends
class ObjectPinningVisitorBase< PreciseObjectPinningVisitor >
Additional Inherited Members
Detailed Description
Definition at line 548 of file scavenger.cc.
Constructor & Destructor Documentation
PreciseObjectPinningVisitor()
v8::internal::anonymous_namespace{scavenger.cc}::PreciseObjectPinningVisitor::PreciseObjectPinningVisitor (const Heap * heap, Scavenger & scavenger, ScavengerCollector::PinnedObjects & pinned_objects) [inline]
Definition at line 551 of file scavenger.cc.
      : ObjectPinningVisitorBase<PreciseObjectPinningVisitor>(heap, scavenger,
                                                              pinned_objects) {}
Member Function Documentation
HandlePointer()
void v8::internal::anonymous_namespace{scavenger.cc}::PreciseObjectPinningVisitor::HandlePointer (FullObjectSlot p) [inline], [private]
Definition at line 557 of file scavenger.cc.
                                       {
    Tagged<Object> object = *p;
    if (!object.IsHeapObject()) {
      return;
    }
    Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
    if (!MemoryChunk::FromHeapObject(heap_object)->IsFromPage()) {
      return;
    }
    if (HeapLayout::IsSelfForwarded(heap_object)) {
      return;
    }
    HandleHeapObject(heap_object);
  }
References v8::internal::MemoryChunk::FromHeapObject(), v8::internal::IsHeapObject(), and v8::internal::HeapLayout::IsSelfForwarded().
Friends And Related Function Documentation
ObjectPinningVisitorBase< PreciseObjectPinningVisitor >
friend class ObjectPinningVisitorBase< PreciseObjectPinningVisitor > [friend]
Definition at line 557 of file scavenger.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/scavenger.cc