v8::internal::StringTable::OffHeapStringHashSet Class Reference
Public Member Functions
OffHeapStringHashSet (int capacity)
Tagged< Object > GetKey (PtrComprCageBase cage_base, InternalIndex index) const
void SetKey (InternalIndex index, Tagged< Object > key)
void Set (InternalIndex index, Tagged< String > key)
void CopyEntryExcludingKeyInto (PtrComprCageBase, InternalIndex, OffHeapStringHashSet *, InternalIndex)
Static Public Member Functions
static uint32_t Hash (PtrComprCageBase, Tagged< Object > key)
template<typename IsolateT , typename StringTableKey >
static bool KeyIsMatch (IsolateT *isolate, StringTableKey *key, Tagged< Object > obj)
Static Public Attributes
static constexpr int kEntrySize = 1
static constexpr int kMaxEmptyFactor = 4
static constexpr int kMinCapacity = 2048
Friends
class StringTable::Data
Additional Inherited Members
Detailed Description
Definition at line 31 of file string-table.cc.
Constructor & Destructor Documentation
OffHeapStringHashSet()
v8::internal::StringTable::OffHeapStringHashSet::OffHeapStringHashSet (int capacity) [inline], [explicit]
Definition at line 38 of file string-table.cc.
      : OffHeapHashTableBase<OffHeapStringHashSet>(capacity) {}
Member Function Documentation
CopyEntryExcludingKeyInto()
void v8::internal::StringTable::OffHeapStringHashSet::CopyEntryExcludingKeyInto (PtrComprCageBase , InternalIndex , OffHeapStringHashSet * , InternalIndex) [inline]
Definition at line 64 of file string-table.cc.
                                                                       {
    // Do nothing, since the entry size is 1 (just the key).
  }
GetKey()
Tagged<Object> v8::internal::StringTable::OffHeapStringHashSet::GetKey (PtrComprCageBase cage_base, InternalIndex index) const [inline]
Definition at line 54 of file string-table.cc.
                                                                               {
    return slot(index).Acquire_Load(cage_base);
  }
References v8::internal::FullObjectSlot::Acquire_Load(), v8::internal::index, and v8::internal::OffHeapHashTableBase< OffHeapStringHashSet >::slot().
Referenced by v8::internal::StringTable::LookupKey(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
Hash()
static uint32_t v8::internal::StringTable::OffHeapStringHashSet::Hash (PtrComprCageBase , Tagged< Object > key) [inline], [static]
Definition at line 41 of file string-table.cc.
                                                             {
    return Cast<String>(key)->hash();
  }
References v8::internal::key.
KeyIsMatch()
template<typename IsolateT , typename StringTableKey >
static bool v8::internal::StringTable::OffHeapStringHashSet::KeyIsMatch (IsolateT * isolate, StringTableKey * key, Tagged< Object > obj) [inline], [static]
Definition at line 46 of file string-table.cc.
                                             {
    auto string = Cast<String>(obj);
    if (string->hash() != key->hash()) return false;
    if (string->length() != key->length()) return false;
    return key->IsMatch(isolate, string);
  }
References v8::internal::key, and v8::internal::string.
Set()
void v8::internal::StringTable::OffHeapStringHashSet::Set (InternalIndex index, Tagged< String > key) [inline]
Definition at line 62 of file string-table.cc.
{ SetKey(index, key); }
References v8::internal::index, v8::internal::key, and SetKey().
SetKey()
void v8::internal::StringTable::OffHeapStringHashSet::SetKey (InternalIndex index, Tagged< Object > key) [inline]
Definition at line 58 of file string-table.cc.
                                                       {
    DCHECK(IsString(key));
    slot(index).Release_Store(key);
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::key, v8::internal::FullObjectSlot::Release_Store(), and v8::internal::OffHeapHashTableBase< OffHeapStringHashSet >::slot().
Referenced by Set().
Friends And Related Function Documentation
StringTable::Data
friend class StringTable::Data [friend]
Definition at line 70 of file string-table.cc.
Member Data Documentation
kEntrySize
constexpr int v8::internal::StringTable::OffHeapStringHashSet::kEntrySize = 1 [static], [constexpr]
Definition at line 34 of file string-table.cc.
kMaxEmptyFactor
constexpr int v8::internal::StringTable::OffHeapStringHashSet::kMaxEmptyFactor = 4 [static], [constexpr]
Definition at line 35 of file string-table.cc.
kMinCapacity
constexpr int v8::internal::StringTable::OffHeapStringHashSet::kMinCapacity = 2048 [static], [constexpr]
Definition at line 36 of file string-table.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string-table.cc