v8::CpuProfileNode Class Reference
CpuProfileNode represents a node in a call graph.
#include <v8-profiler.h>
Classes
struct LineTick
Public Types
enum SourceType {
kScript = 0
, kBuiltin = 1
, kCallback = 2
, kInternal = 3
,
kUnresolved = 4
 }
Public Member Functions
Local< String > GetFunctionName () const
Returns function name (empty string for anonymous functions.)
const char * GetFunctionNameStr () const
Returns function name (empty string for anonymous functions.) The string ownership is not passed to the caller.
int GetScriptId () const
Returns id of the script where function is located.
Local< String > GetScriptResourceName () const
Returns resource name for script from where the function originates.
const char * GetScriptResourceNameStr () const
Returns resource name for script from where the function originates.
bool IsScriptSharedCrossOrigin () const
Return true if the script from where the function originates is flagged as being shared cross-origin.
int GetLineNumber () const
Returns the number, 1-based, of the line where the function originates.
int GetColumnNumber () const
Returns 1-based number of the column where the function originates.
unsigned int GetHitLineCount () const
Returns the number of the function's source lines that collect the samples.
bool GetLineTicks (LineTick *entries, unsigned int length) const
Returns the set of source lines that collect the samples.
const char * GetBailoutReason () const
Returns bailout reason for the function if the optimization was disabled for it.
unsigned GetHitCount () const
Returns the count of samples where the function was currently executing.
unsigned GetNodeId () const
Returns id of the node.
SourceType GetSourceType () const
Gets the type of the source which the node was captured from.
int GetChildrenCount () const
Returns child nodes count of the node.
const CpuProfileNode * GetChild (int index) const
Retrieves a child node by index.
const CpuProfileNode * GetParent () const
Retrieves the ancestor node, or null if the root.
const std::vector< CpuProfileDeoptInfo > & GetDeoptInfos () const
Retrieves deopt infos for the node.
Static Public Attributes
static const int kNoLineNumberInfo = Message::kNoLineNumberInfo
static const int kNoColumnNumberInfo = Message::kNoColumnInfo
Detailed Description
CpuProfileNode represents a node in a call graph.
Definition at line 68 of file v8-profiler.h.
Member Enumeration Documentation
SourceType
enum v8::CpuProfileNode::SourceType
Enumerator
kScript
kBuiltin
kCallback
kInternal
kUnresolved
Definition at line 83 of file v8-profiler.h.
                  {
    // User-supplied script with associated resource information.
    kScript = 0,
    // Native scripts and provided builtins.
    kBuiltin = 1,
    // Callbacks into native code.
    kCallback = 2,
    // VM-internal functions or state.
    kInternal = 3,
    // A node that failed to symbolize.
    kUnresolved = 4,
  };
Member Function Documentation
GetBailoutReason()
const char * v8::CpuProfileNode::GetBailoutReason () const
Returns bailout reason for the function if the optimization was disabled for it.
Definition at line 11301 of file api.cc.
                                                   {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  return node->entry()->bailout_reason();
}
References v8::internal::CodeEntry::bailout_reason(), and v8::internal::ProfileNode::entry().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), and v8::internal::CpuProfileJSONSerializer::SerializeNode().
GetChild()
const CpuProfileNode * v8::CpuProfileNode::GetChild (int index) const
Retrieves a child node by index.
Definition at line 11323 of file api.cc.
                                                              {
  const i::ProfileNode* child =
      reinterpret_cast<const i::ProfileNode*>(this)->children()->at(index);
  return reinterpret_cast<const CpuProfileNode*>(child);
}
References v8::internal::index.
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), v8::internal::anonymous_namespace{profile-generator.cc}::FlattenNodesTree(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::flattenNodesTree(), and v8::internal::CpuProfileJSONSerializer::SerializeChildren().
GetChildrenCount()
int v8::CpuProfileNode::GetChildrenCount () const
Returns child nodes count of the node.
Definition at line 11318 of file api.cc.
                                           {
  return static_cast<int>(
      reinterpret_cast<const i::ProfileNode*>(this)->children()->size());
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), v8::internal::anonymous_namespace{profile-generator.cc}::FlattenNodesTree(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::flattenNodesTree(), and v8::internal::CpuProfileJSONSerializer::SerializeNode().
GetColumnNumber()
int v8::CpuProfileNode::GetColumnNumber () const
Returns 1-based number of the column where the function originates.
kNoColumnNumberInfo if no column number information is available.
Definition at line 11284 of file api.cc.
                                          {
  return reinterpret_cast<const i::ProfileNode*>(this)
      ->line_and_column()
      .column;
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), and v8::internal::CpuProfileJSONSerializer::SerializeCallFrame().
GetDeoptInfos()
const std::vector< CpuProfileDeoptInfo > & v8::CpuProfileNode::GetDeoptInfos () const
Retrieves deopt infos for the node.
Definition at line 11335 of file api.cc.
                                                                          {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  return node->deopt_infos();
}
References v8::internal::ProfileNode::deopt_infos().
GetFunctionName()
Local< String > v8::CpuProfileNode::GetFunctionName () const
Returns function name (empty string for anonymous functions.)
Definition at line 11243 of file api.cc.
                                                    {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  i::Isolate* i_isolate = node->isolate();
  const i::CodeEntry* entry = node->entry();
  i::DirectHandle<i::String> name =
      i_isolate->factory()->InternalizeUtf8String(entry->name());
  return ToApiHandle<String>(name);
}
References v8::internal::ProfileNode::entry(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::ProfileNode::isolate(), name, and v8::internal::CodeEntry::name().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor().
GetFunctionNameStr()
const char * v8::CpuProfileNode::GetFunctionNameStr () const
Returns function name (empty string for anonymous functions.) The string ownership is not passed to the caller.
It stays valid until profile is deleted. The function is thread safe.
Definition at line 11252 of file api.cc.
                                                     {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  return node->entry()->name();
}
References v8::internal::ProfileNode::entry(), and v8::internal::CodeEntry::name().
Referenced by v8::internal::CpuProfileJSONSerializer::SerializeCallFrame().
GetHitCount()
unsigned v8::CpuProfileNode::GetHitCount () const
Returns the count of samples where the function was currently executing.
Definition at line 11306 of file api.cc.
                                           {
  return reinterpret_cast<const i::ProfileNode*>(this)->self_ticks();
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), and v8::internal::CpuProfileJSONSerializer::SerializeNode().
GetHitLineCount()
unsigned int v8::CpuProfileNode::GetHitLineCount () const
Returns the number of the function's source lines that collect the samples.
Definition at line 11290 of file api.cc.
                                                   {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  return node->GetHitLineCount();
}
References v8::internal::ProfileNode::GetHitLineCount().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForPositionTicks(), and v8::internal::CpuProfileJSONSerializer::SerializeNode().
GetLineNumber()
int v8::CpuProfileNode::GetLineNumber () const
Returns the number, 1-based, of the line where the function originates.
kNoLineNumberInfo if no line number information is available.
Definition at line 11280 of file api.cc.
                                        {
  return reinterpret_cast<const i::ProfileNode*>(this)->line_and_column().line;
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), and v8::internal::CpuProfileJSONSerializer::SerializeCallFrame().
GetLineTicks()
bool v8::CpuProfileNode::GetLineTicks (LineTick * entries, unsigned int length) const
Returns the set of source lines that collect the samples.
The caller allocates buffer and responsible for releasing it. True if all available entries are copied, otherwise false. The function copies nothing if buffer is not large enough.
Definition at line 11295 of file api.cc.
                                                             {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  return node->GetLineTicks(entries, length);
}
References v8::internal::ProfileNode::GetLineTicks(), and v8::internal::length.
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForPositionTicks(), and v8::internal::CpuProfileJSONSerializer::SerializePositionTicks().
GetNodeId()
unsigned v8::CpuProfileNode::GetNodeId () const
Returns id of the node.
The id is unique within the tree
Definition at line 11310 of file api.cc.
                                         {
  return reinterpret_cast<const i::ProfileNode*>(this)->id();
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForSamples(), v8::internal::CpuProfileJSONSerializer::SerializeChildren(), and v8::internal::CpuProfileJSONSerializer::SerializeNode().
GetParent()
const CpuProfileNode * v8::CpuProfileNode::GetParent () const
Retrieves the ancestor node, or null if the root.
Definition at line 11329 of file api.cc.
                                                      {
  const i::ProfileNode* parent =
      reinterpret_cast<const i::ProfileNode*>(this)->parent();
  return reinterpret_cast<const CpuProfileNode*>(parent);
}
GetScriptId()
int v8::CpuProfileNode::GetScriptId () const
Returns id of the script where function is located.
Definition at line 11257 of file api.cc.
                                      {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  const i::CodeEntry* entry = node->entry();
  return entry->script_id();
}
References v8::internal::ProfileNode::entry(), and v8::internal::CodeEntry::script_id().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), and v8::internal::CpuProfileJSONSerializer::SerializeCallFrame().
GetScriptResourceName()
Local< String > v8::CpuProfileNode::GetScriptResourceName () const
Returns resource name for script from where the function originates.
Definition at line 11263 of file api.cc.
                                                          {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  i::Isolate* i_isolate = node->isolate();
  return ToApiHandle<String>(i_isolate->factory()->InternalizeUtf8String(
      node->entry()->resource_name()));
}
References v8::internal::ProfileNode::entry(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::ProfileNode::isolate(), and v8::internal::CodeEntry::resource_name().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor().
GetScriptResourceNameStr()
const char * v8::CpuProfileNode::GetScriptResourceNameStr () const
Returns resource name for script from where the function originates.
The string ownership is not passed to the caller. It stays valid until profile is deleted. The function is thread safe.
Definition at line 11270 of file api.cc.
                                                           {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  return node->entry()->resource_name();
}
References v8::internal::ProfileNode::entry(), and v8::internal::CodeEntry::resource_name().
Referenced by v8::internal::CpuProfileJSONSerializer::SerializeCallFrame().
GetSourceType()
CpuProfileNode::SourceType v8::CpuProfileNode::GetSourceType () const
Gets the type of the source which the node was captured from.
Definition at line 11314 of file api.cc.
                                                             {
  return reinterpret_cast<const i::ProfileNode*>(this)->source_type();
}
IsScriptSharedCrossOrigin()
bool v8::CpuProfileNode::IsScriptSharedCrossOrigin () const
Return true if the script from where the function originates is flagged as being shared cross-origin.
Definition at line 11275 of file api.cc.
                                                     {
  const i::ProfileNode* node = reinterpret_cast<const i::ProfileNode*>(this);
  return node->entry()->is_shared_cross_origin();
}
References v8::internal::ProfileNode::entry(), and v8::internal::CodeEntry::is_shared_cross_origin().
Member Data Documentation
kNoColumnNumberInfo
const int v8::CpuProfileNode::kNoColumnNumberInfo = Message::kNoColumnInfo [static]
Definition at line 180 of file v8-profiler.h.
Referenced by v8::internal::SourcePositionTable::GetTuple().
kNoLineNumberInfo
const int v8::CpuProfileNode::kNoLineNumberInfo = Message::kNoLineNumberInfo [static]
Definition at line 179 of file v8-profiler.h.
Referenced by v8::internal::ProfileTree::AddPathFromEnd(), v8::internal::SourcePositionTable::GetTuple(), v8::internal::ProfileNode::IncrementLineAndColumnTicks(), and v8::internal::Symbolizer::SymbolizeTickSample().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc