v8::internal::compiler::CodeGenerator Class Reference
#include <code-generator.h>
Classes
struct HandlerInfo
class JumpTable
class MoveType
Public Member Functions
CodeGenerator (Zone *codegen_zone, Frame *frame, Linkage *linkage, InstructionSequence *instructions, OptimizedCompilationInfo *info, Isolate *isolate, std::optional< OsrHelper > osr_helper, int start_source_position, JumpOptimizationInfo *jump_opt, const AssemblerOptions &options, Builtin builtin, size_t max_unoptimized_frame_height, size_t max_pushed_argument_count, const char *debug_name=nullptr)
void AssembleCode ()
MaybeHandle< Code > FinalizeCode ()
base::OwnedVector< uint8_t > GetSourcePositionTable ()
base::OwnedVector< uint8_t > GetProtectedInstructionsData ()
InstructionSequence * instructions () const
FrameAccessState * frame_access_state () const
const Frame * frame () const
Isolate * isolate () const
Linkage * linkage () const
Label * GetLabel (RpoNumber rpo)
void RecordProtectedInstruction (uint32_t instr_offset)
SourcePosition start_source_position () const
void AssembleSourcePosition (Instruction *instr)
void AssembleSourcePosition (SourcePosition source_position)
void RecordSafepoint (ReferenceMap *references, int pc_offset=0)
Zone * zone () const
MacroAssembler * masm ()
SafepointTableBuilder * safepoint_table_builder ()
size_t handler_table_offset () const
const ZoneVector< int > & block_starts () const
const ZoneVector< TurbolizerInstructionStartInfo > & instr_starts () const
const TurbolizerCodeOffsetsInfo & offsets_info () const
bool ShouldApplyOffsetToStackCheck (Instruction *instr, uint32_t *offset)
uint32_t GetStackCheckOffset ()
CodeKind code_kind () const
Static Public Attributes
static constexpr int kBinarySearchSwitchMinimalCases = 4
Private Types
enum CodeGenResult { kSuccess
, kTooManyDeoptimizationBailouts
 }
enum PushTypeFlag { kImmediatePush = 0x1
, kRegisterPush = 0x2
, kStackSlotPush = 0x4
, kScalarPush = kRegisterPush | kStackSlotPush
 }
using PushTypeFlags = base::Flags< PushTypeFlag >
Private Member Functions
GapResolver * resolver ()
SafepointTableBuilder * safepoints ()
OptimizedCompilationInfo * info () const
OsrHelper * osr_helper ()
void CreateFrameAccessState (Frame *frame)
void FinishFrame (Frame *frame)
bool IsNextInAssemblyOrder (RpoNumber block) const
bool IsMaterializableFromRoot (Handle< HeapObject > object, RootIndex *index_return)
CodeGenResult AssembleBlock (const InstructionBlock *block)
CodeGenResult AssembleInstruction (int instruction_index, const InstructionBlock *block)
void AssembleGaps (Instruction *instr)
RpoNumber ComputeBranchInfo (BranchInfo *branch, FlagsCondition condition, Instruction *instr)
bool GetSlotAboveSPBeforeTailCall (Instruction *instr, int *slot)
StubCallMode DetermineStubCallMode () const
CodeGenResult AssembleDeoptimizerCall (DeoptimizationExit *exit)
DeoptimizationExit * BuildTranslation (Instruction *instr, int pc_offset, size_t frame_state_offset, size_t immediate_args_count, OutputFrameStateCombine state_combine)
CodeGenResult AssembleArchInstruction (Instruction *instr)
void AssembleArchJump (RpoNumber target)
void AssembleArchJumpRegardlessOfAssemblyOrder (RpoNumber target)
void AssembleArchBranch (Instruction *instr, BranchInfo *branch)
void AssembleArchConditionalBranch (Instruction *instr, BranchInfo *branch)
void AssembleArchDeoptBranch (Instruction *instr, BranchInfo *branch)
void AssembleArchBoolean (Instruction *instr, FlagsCondition condition)
void AssembleArchConditionalBoolean (Instruction *instr)
void AssembleArchSelect (Instruction *instr, FlagsCondition condition)
void AssembleArchBinarySearchSwitchRange (Register input, RpoNumber def_block, std::pair< int32_t, Label * > *begin, std::pair< int32_t, Label * > *end)
void AssembleArchBinarySearchSwitch (Instruction *instr)
void AssembleArchTableSwitch (Instruction *instr)
void AssembleCodeStartRegisterCheck ()
void BailoutIfDeoptimized ()
void AssemblePlaceHolderForLazyDeopt (Instruction *instr)
void AssembleConstructFrame ()
void AssembleReturn (InstructionOperand *pop)
void AssembleDeconstructFrame ()
void AssemblePrepareTailCall ()
void AssembleTailCallBeforeGap (Instruction *instr, int first_unused_stack_slot)
void AssembleTailCallAfterGap (Instruction *instr, int first_unused_stack_slot)
void FinishCode ()
void MaybeEmitOutOfLineConstantPool ()
void IncrementStackAccessCounter (InstructionOperand *source, InstructionOperand *destination)
void AssembleMove (InstructionOperand *source, InstructionOperand *destination) final
void AssembleSwap (InstructionOperand *source, InstructionOperand *destination) final
AllocatedOperand Push (InstructionOperand *src) final
void Pop (InstructionOperand *src, MachineRepresentation rep) final
void PopTempStackSlots () final
void MoveToTempLocation (InstructionOperand *src, MachineRepresentation rep) final
void MoveTempLocationTo (InstructionOperand *dst, MachineRepresentation rep) final
void SetPendingMove (MoveOperands *move) final
Label * AddJumpTable (base::Vector< Label * > targets)
void AssembleJumpTable (base::Vector< Label * > targets)
void RecordCallPosition (Instruction *instr)
void RecordDeoptInfo (Instruction *instr, int pc_offset)
Handle< DeoptimizationData > GenerateDeoptimizationData ()
int DefineProtectedDeoptimizationLiteral (IndirectHandle< TrustedObject > object)
int DefineDeoptimizationLiteral (DeoptimizationLiteral literal)
bool HasProtectedDeoptimizationLiteral (IndirectHandle< TrustedObject > object) const
DeoptimizationEntry const & GetDeoptimizationEntry (Instruction *instr, size_t frame_state_offset)
void BuildTranslationForFrameStateDescriptor (FrameStateDescriptor *descriptor, InstructionOperandIterator *iter, OutputFrameStateCombine state_combine)
void TranslateStateValueDescriptor (StateValueDescriptor *desc, StateValueList *nested, InstructionOperandIterator *iter)
void TranslateFrameStateDescriptorOperands (FrameStateDescriptor *desc, InstructionOperandIterator *iter)
void AddTranslationForOperand (Instruction *instr, InstructionOperand *op, MachineType type)
void PrepareForDeoptimizationExits (ZoneDeque< DeoptimizationExit * > *exits)
DeoptimizationExit * AddDeoptimizationExit (Instruction *instr, size_t frame_state_offset, size_t immediate_args_count)
Static Private Member Functions
static bool IsValidPush (InstructionOperand source, PushTypeFlags push_type)
static void GetPushCompatibleMoves (Instruction *instr, PushTypeFlags push_type, ZoneVector< MoveOperands * > *pushes)
Private Attributes
Zone * zone_
Isolate * isolate_
FrameAccessState * frame_access_state_
Linkage *const linkage_
InstructionSequence *const instructions_
UnwindingInfoWriter unwinding_info_writer_
OptimizedCompilationInfo *const info_
Label *const labels_
Label return_label_
RpoNumber current_block_
SourcePosition start_source_position_
SourcePosition current_source_position_
MacroAssembler masm_
GapResolver resolver_
SafepointTableBuilder safepoints_
ZoneVector< HandlerInfo > handlers_
int next_deoptimization_id_ = 0
int deopt_exit_start_offset_ = 0
int eager_deopt_count_ = 0
int lazy_deopt_count_ = 0
ZoneDeque< DeoptimizationExit * > deoptimization_exits_
ZoneDeque< IndirectHandle< TrustedObject > > protected_deoptimization_literals_
ZoneDeque< DeoptimizationLiteral > deoptimization_literals_
size_t inlined_function_count_ = 0
FrameTranslationBuilder translations_
int handler_table_offset_ = 0
Label jump_deoptimization_entry_labels_ [kDeoptimizeKindCount]
const size_t max_unoptimized_frame_height_
const size_t max_pushed_argument_count_
uint16_t parameter_count_ = 0
bool caller_registers_saved_
SaveFPRegsMode fp_mode_
JumpTable * jump_tables_
OutOfLineCode * ools_
std::optional< OsrHelper > osr_helper_
int osr_pc_offset_
SourcePositionTableBuilder source_position_table_builder_
CodeGenResult result_
ZoneVector< int > block_starts_
TurbolizerCodeOffsetsInfo offsets_info_
ZoneVector< TurbolizerInstructionStartInfo > instr_starts_
MoveCycleState move_cycle_
const char * debug_name_ = nullptr
Friends
class OutOfLineCode
class CodeGeneratorTester
Additional Inherited Members
Detailed Description
Definition at line 77 of file code-generator.h.
Member Typedef Documentation
PushTypeFlags
using v8::internal::compiler::CodeGenerator::PushTypeFlags = base::Flags<PushTypeFlag> [private]
Definition at line 282 of file code-generator.h.
Member Enumeration Documentation
CodeGenResult
enum v8::internal::compiler::CodeGenerator::CodeGenResult [private]
Enumerator
kSuccess
kTooManyDeoptimizationBailouts
Definition at line 178 of file code-generator.h.
{ kSuccess, kTooManyDeoptimizationBailouts };
PushTypeFlag
enum v8::internal::compiler::CodeGenerator::PushTypeFlag [private]
Enumerator
kImmediatePush
kRegisterPush
kStackSlotPush
kScalarPush
Definition at line 275 of file code-generator.h.
                    {
    kImmediatePush = 0x1,
    kRegisterPush = 0x2,
    kStackSlotPush = 0x4,
    kScalarPush = kRegisterPush | kStackSlotPush
  };
Constructor & Destructor Documentation
CodeGenerator()
v8::internal::compiler::CodeGenerator::CodeGenerator (Zone * codegen_zone, Frame * frame, Linkage * linkage, InstructionSequence * instructions, OptimizedCompilationInfo * info, Isolate * isolate, std::optional< OsrHelper > osr_helper, int start_source_position, JumpOptimizationInfo * jump_opt, const AssemblerOptions & options, Builtin builtin, size_t max_unoptimized_frame_height, size_t max_pushed_argument_count, const char * debug_name = nullptr) [explicit]
Definition at line 51 of file code-generator.cc.
    : zone_(codegen_zone),
      isolate_(isolate),
      frame_access_state_(nullptr),
      linkage_(linkage),
      instructions_(instructions),
      unwinding_info_writer_(codegen_zone),
      info_(info),
      labels_(codegen_zone->AllocateArray<Label>(
          instructions->InstructionBlockCount())),
      current_block_(RpoNumber::Invalid()),
      start_source_position_(start_source_position),
      current_source_position_(SourcePosition::Unknown()),
      masm_(isolate, codegen_zone, options, CodeObjectRequired::kNo,
            std::unique_ptr<AssemblerBuffer>{}),
      resolver_(this),
      safepoints_(codegen_zone),
      handlers_(codegen_zone),
      deoptimization_exits_(codegen_zone),
      protected_deoptimization_literals_(codegen_zone),
      deoptimization_literals_(codegen_zone),
      translations_(codegen_zone),
      max_unoptimized_frame_height_(max_unoptimized_frame_height),
      max_pushed_argument_count_(max_pushed_argument_count),
      caller_registers_saved_(false),
      jump_tables_(nullptr),
      ools_(nullptr),
      osr_helper_(std::move(osr_helper)),
      osr_pc_offset_(-1),
      source_position_table_builder_(
          codegen_zone, SourcePositionTableBuilder::RECORD_SOURCE_POSITIONS),
#if V8_ENABLE_WEBASSEMBLY
      protected_instructions_(codegen_zone),
#endif // V8_ENABLE_WEBASSEMBLY
      result_(kSuccess),
      block_starts_(codegen_zone),
      instr_starts_(codegen_zone),
      debug_name_(debug_name) {
  for (int i = 0; i < instructions->InstructionBlockCount(); ++i) {
    new (&labels_[i]) Label;
  }
  CreateFrameAccessState(frame);
  CHECK_EQ(info->is_osr(), osr_helper_.has_value());
  masm_.set_jump_optimization_info(jump_opt);
  CodeKind code_kind = info->code_kind();
  if (code_kind == CodeKind::WASM_FUNCTION ||
      code_kind == CodeKind::WASM_TO_CAPI_FUNCTION ||
      code_kind == CodeKind::WASM_TO_JS_FUNCTION ||
      code_kind == CodeKind::JS_TO_WASM_FUNCTION) {
    masm_.set_abort_hard(true);
  }
  masm_.set_builtin(builtin);
}
References v8::internal::kNo.
Member Function Documentation
AddDeoptimizationExit()
DeoptimizationExit * v8::internal::compiler::CodeGenerator::AddDeoptimizationExit (Instruction * instr, size_t frame_state_offset, size_t immediate_args_count) [private]
Definition at line 1618 of file code-generator.cc.
                                 {
  return BuildTranslation(instr, -1, frame_state_offset, immediate_args_count,
                          OutputFrameStateCombine::Ignore());
}
References BuildTranslation(), and v8::internal::compiler::OutputFrameStateCombine::Ignore().
Referenced by AssembleInstruction().
AddJumpTable()
Label * v8::internal::compiler::CodeGenerator::AddJumpTable (base::Vector< Label * > targets) [private]
Definition at line 1123 of file code-generator.cc.
                                                             {
  jump_tables_ = zone()->New<JumpTable>(jump_tables_, targets);
  return jump_tables_->label();
}
References jump_tables_, v8::internal::compiler::CodeGenerator::JumpTable::label(), v8::internal::Zone::New(), and zone().
AddTranslationForOperand()
void v8::internal::compiler::CodeGenerator::AddTranslationForOperand (Instruction * instr, InstructionOperand * op, MachineType type) [private]
Definition at line 1390 of file code-generator.cc.
                                                               {
  if (op->IsStackSlot()) {
    if (type.representation() == MachineRepresentation::kBit) {
      translations_.StoreBoolStackSlot(LocationOperand::cast(op)->index());
    } else if (type == MachineType::Int8() || type == MachineType::Int16() ||
               type == MachineType::Int32()) {
      translations_.StoreInt32StackSlot(LocationOperand::cast(op)->index());
    } else if (type == MachineType::Uint8() || type == MachineType::Uint16() ||
               type == MachineType::Uint32()) {
      translations_.StoreUint32StackSlot(LocationOperand::cast(op)->index());
    } else if (type == MachineType::Int64()) {
      translations_.StoreInt64StackSlot(LocationOperand::cast(op)->index());
    } else if (type == MachineType::SignedBigInt64()) {
      translations_.StoreSignedBigInt64StackSlot(
          LocationOperand::cast(op)->index());
    } else if (type == MachineType::UnsignedBigInt64()) {
      translations_.StoreUnsignedBigInt64StackSlot(
          LocationOperand::cast(op)->index());
    } else {
#if defined(V8_COMPRESS_POINTERS)
      CHECK(MachineRepresentation::kTagged == type.representation() ||
            MachineRepresentation::kCompressed == type.representation());
#else
      CHECK(MachineRepresentation::kTagged == type.representation());
#endif
      translations_.StoreStackSlot(LocationOperand::cast(op)->index());
    }
  } else if (op->IsFPStackSlot()) {
    switch (type.representation()) {
      case MachineRepresentation::kFloat32:
        translations_.StoreFloatStackSlot(LocationOperand::cast(op)->index());
        break;
      case MachineRepresentation::kFloat64:
        if (type.semantic() == MachineSemantic::kHoleyFloat64) {
          translations_.StoreHoleyDoubleStackSlot(
              LocationOperand::cast(op)->index());
        } else {
          translations_.StoreDoubleStackSlot(
              LocationOperand::cast(op)->index());
        }
        break;
      case MachineRepresentation::kSimd128:
        translations_.StoreSimd128StackSlot(LocationOperand::cast(op)->index());
        break;
      default:
        UNREACHABLE();
    }
  } else if (op->IsRegister()) {
    InstructionOperandConverter converter(this, instr);
    if (type.representation() == MachineRepresentation::kBit) {
      translations_.StoreBoolRegister(converter.ToRegister(op));
    } else if (type == MachineType::Int8() || type == MachineType::Int16() ||
               type == MachineType::Int32()) {
      translations_.StoreInt32Register(converter.ToRegister(op));
    } else if (type == MachineType::Uint8() || type == MachineType::Uint16() ||
               type == MachineType::Uint32()) {
      translations_.StoreUint32Register(converter.ToRegister(op));
    } else if (type == MachineType::Int64()) {
      translations_.StoreInt64Register(converter.ToRegister(op));
    } else if (type == MachineType::SignedBigInt64()) {
      translations_.StoreSignedBigInt64Register(converter.ToRegister(op));
    } else if (type == MachineType::UnsignedBigInt64()) {
      translations_.StoreUnsignedBigInt64Register(converter.ToRegister(op));
    } else {
#if defined(V8_COMPRESS_POINTERS)
      CHECK(MachineRepresentation::kTagged == type.representation() ||
            MachineRepresentation::kCompressed == type.representation());
#else
      CHECK(MachineRepresentation::kTagged == type.representation());
#endif
      translations_.StoreRegister(converter.ToRegister(op));
    }
  } else if (op->IsFPRegister()) {
    InstructionOperandConverter converter(this, instr);
    switch (type.representation()) {
      case MachineRepresentation::kFloat32:
        translations_.StoreFloatRegister(converter.ToFloatRegister(op));
        break;
      case MachineRepresentation::kFloat64:
        if (type.semantic() == MachineSemantic::kHoleyFloat64) {
          translations_.StoreHoleyDoubleRegister(
              converter.ToDoubleRegister(op));
        } else {
          translations_.StoreDoubleRegister(converter.ToDoubleRegister(op));
        }
        break;
      case MachineRepresentation::kSimd128:
        translations_.StoreSimd128Register(converter.ToSimd128Register(op));
        break;
      default:
        UNREACHABLE();
    }
  } else {
    CHECK(op->IsImmediate());
    InstructionOperandConverter converter(this, instr);
    Constant constant = converter.ToConstant(op);
    DeoptimizationLiteral literal;
#if V8_ENABLE_WEBASSEMBLY
    if (info_->IsWasm() && v8_flags.wasm_deopt) {
      switch (type.representation()) {
        case MachineRepresentation::kWord32:
          literal = DeoptimizationLiteral(constant.ToInt32());
          break;
        case MachineRepresentation::kWord64:
          literal = DeoptimizationLiteral(constant.ToInt64());
          break;
        case MachineRepresentation::kFloat32:
          literal = DeoptimizationLiteral(constant.ToFloat32Safe());
          break;
        case MachineRepresentation::kFloat64:
          literal = DeoptimizationLiteral(Float64(constant.ToFloat64()));
          break;
        case MachineRepresentation::kTagged: {
          DCHECK(!PointerCompressionIsEnabled() ||
                 base::IsInRange(constant.ToInt64(), 0u, UINT32_MAX));
          Tagged<Smi> smi(static_cast<Address>(constant.ToInt64()));
          DCHECK(IsSmi(smi));
          literal = DeoptimizationLiteral(smi);
          break;
        }
        default:
          UNIMPLEMENTED();
      }
      int literal_id = DefineDeoptimizationLiteral(literal);
      translations_.StoreLiteral(literal_id);
      return;
    }
#endif
    switch (constant.type()) {
      case Constant::kInt32:
        if (type.representation() == MachineRepresentation::kTagged) {
          // When pointers are 4 bytes, we can use int32 constants to represent
          // Smis.
          DCHECK_EQ(4, kSystemPointerSize);
          Tagged<Smi> smi(static_cast<Address>(constant.ToInt32()));
          DCHECK(IsSmi(smi));
          literal = DeoptimizationLiteral(static_cast<double>(smi.value()));
        } else if (type.representation() == MachineRepresentation::kBit) {
          if (constant.ToInt32() == 0) {
            literal =
                DeoptimizationLiteral(isolate()->factory()->false_value());
          } else {
            DCHECK_EQ(1, constant.ToInt32());
            literal = DeoptimizationLiteral(isolate()->factory()->true_value());
          }
        } else {
          DCHECK(type == MachineType::Int32() ||
                 type == MachineType::Uint32() ||
                 type.representation() == MachineRepresentation::kWord32 ||
                 type.representation() == MachineRepresentation::kNone);
          DCHECK(type.representation() != MachineRepresentation::kNone ||
                 constant.ToInt32() == FrameStateDescriptor::kImpossibleValue);
          if (type == MachineType::Uint32()) {
            literal = DeoptimizationLiteral(
                static_cast<double>(static_cast<uint32_t>(constant.ToInt32())));
          } else {
            literal =
                DeoptimizationLiteral(static_cast<double>(constant.ToInt32()));
          }
        }
        break;
      case Constant::kInt64:
        DCHECK_EQ(8, kSystemPointerSize);
        if (type == MachineType::SignedBigInt64()) {
          literal = DeoptimizationLiteral(constant.ToInt64());
        } else if (type == MachineType::UnsignedBigInt64()) {
          literal =
              DeoptimizationLiteral(static_cast<uint64_t>(constant.ToInt64()));
        } else if (type.representation() == MachineRepresentation::kWord64) {
          // TODO(nicohartmann@, chromium:41497374): Disabling this CHECK
          // because we can see cases where this is violated in unreachable
          // code. We should re-enable once we have an idea on how to prevent
          // this from happening.
          // CHECK_EQ(
          // constant.ToInt64(),
          // static_cast<int64_t>(static_cast<double>(constant.ToInt64())));
          literal =
              DeoptimizationLiteral(static_cast<double>(constant.ToInt64()));
        } else {
          // When pointers are 8 bytes, we can use int64 constants to represent
          // Smis.
          DCHECK_EQ(MachineRepresentation::kTagged, type.representation());
          Tagged<Smi> smi(static_cast<Address>(constant.ToInt64()));
          DCHECK(IsSmi(smi));
          literal = DeoptimizationLiteral(static_cast<double>(smi.value()));
        }
        break;
      case Constant::kFloat32:
        DCHECK(type.representation() == MachineRepresentation::kFloat32 ||
               type.representation() == MachineRepresentation::kTagged);
        literal =
            DeoptimizationLiteral(static_cast<double>(constant.ToFloat32()));
        break;
      case Constant::kFloat64:
        DCHECK(type.representation() == MachineRepresentation::kFloat64 ||
               type.representation() == MachineRepresentation::kTagged);
        if (type == MachineType::HoleyFloat64() &&
            constant.ToFloat64().AsUint64() == kHoleNanInt64) {
          literal = DeoptimizationLiteral::HoleNaN();
        } else {
          literal = DeoptimizationLiteral(constant.ToFloat64().value());
        }
        break;
      case Constant::kHeapObject:
        DCHECK_EQ(MachineRepresentation::kTagged, type.representation());
        literal = DeoptimizationLiteral(constant.ToHeapObject());
        break;
      case Constant::kCompressedHeapObject:
        DCHECK_EQ(MachineType::AnyTagged(), type);
        literal = DeoptimizationLiteral(constant.ToHeapObject());
        break;
      default:
        UNREACHABLE();
    }
    if (literal.object().equals(info()->closure()) &&
        info()->function_context_specializing()) {
      translations_.StoreJSFrameFunction();
    } else {
      int literal_id = DefineDeoptimizationLiteral(literal);
      translations_.StoreLiteral(literal_id);
    }
  }
}
References v8::internal::MachineType::AnyTagged(), v8::base::Double::AsUint64(), v8::internal::compiler::LocationOperand::cast(), CHECK, v8::internal::DCHECK(), DCHECK_EQ, DefineDeoptimizationLiteral(), v8::internal::DeoptimizationLiteral::HoleNaN(), v8::internal::MachineType::HoleyFloat64(), v8::internal::index, info(), info_, v8::internal::MachineType::Int16(), v8::internal::MachineType::Int32(), v8::internal::MachineType::Int64(), v8::internal::MachineType::Int8(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), isolate(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::IsSmi(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::kFloat32, v8::internal::compiler::Constant::kFloat32, v8::internal::kFloat64, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kHeapObject, v8::internal::kHoleNanInt64, v8::internal::kHoleyFloat64, v8::internal::compiler::FrameStateDescriptor::kImpossibleValue, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::kNone, v8::internal::kSimd128, v8::internal::kSystemPointerSize, v8::internal::kTagged, v8::internal::kWord32, v8::internal::kWord64, v8::internal::DeoptimizationLiteral::object(), v8::internal::PointerCompressionIsEnabled(), v8::internal::MachineType::SignedBigInt64(), v8::internal::FrameTranslationBuilder::StoreBoolRegister(), v8::internal::FrameTranslationBuilder::StoreBoolStackSlot(), v8::internal::FrameTranslationBuilder::StoreDoubleRegister(), v8::internal::FrameTranslationBuilder::StoreDoubleStackSlot(), v8::internal::FrameTranslationBuilder::StoreFloatRegister(), v8::internal::FrameTranslationBuilder::StoreFloatStackSlot(), v8::internal::FrameTranslationBuilder::StoreHoleyDoubleRegister(), v8::internal::FrameTranslationBuilder::StoreHoleyDoubleStackSlot(), v8::internal::FrameTranslationBuilder::StoreInt32Register(), v8::internal::FrameTranslationBuilder::StoreInt32StackSlot(), v8::internal::FrameTranslationBuilder::StoreInt64Register(), v8::internal::FrameTranslationBuilder::StoreInt64StackSlot(), v8::internal::FrameTranslationBuilder::StoreJSFrameFunction(), v8::internal::FrameTranslationBuilder::StoreLiteral(), v8::internal::FrameTranslationBuilder::StoreRegister(), v8::internal::FrameTranslationBuilder::StoreSignedBigInt64Register(), v8::internal::FrameTranslationBuilder::StoreSignedBigInt64StackSlot(), v8::internal::FrameTranslationBuilder::StoreSimd128Register(), v8::internal::FrameTranslationBuilder::StoreSimd128StackSlot(), v8::internal::FrameTranslationBuilder::StoreStackSlot(), v8::internal::FrameTranslationBuilder::StoreUint32Register(), v8::internal::FrameTranslationBuilder::StoreUint32StackSlot(), v8::internal::FrameTranslationBuilder::StoreUnsignedBigInt64Register(), v8::internal::FrameTranslationBuilder::StoreUnsignedBigInt64StackSlot(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat32Safe(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::InstructionOperandConverter::ToFloatRegister(), v8::internal::compiler::Constant::ToHeapObject(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToInt64(), v8::internal::compiler::InstructionOperandConverter::ToRegister(), v8::internal::compiler::InstructionOperandConverter::ToSimd128Register(), translations_, v8::internal::compiler::Constant::type(), v8::internal::tracing::type, v8::internal::MachineType::Uint16(), v8::internal::MachineType::Uint32(), v8::internal::MachineType::Uint8(), v8::internal::compiler::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), v8::internal::MachineType::UnsignedBigInt64(), v8::internal::v8_flags, v8::base::Double::value(), and v8::internal::Tagged< Smi >::value().
Referenced by TranslateStateValueDescriptor().
AssembleArchBinarySearchSwitch()
void v8::internal::compiler::CodeGenerator::AssembleArchBinarySearchSwitch (Instruction * instr) [private]
Definition at line 3722 of file code-generator-arm.cc.
                                                                     {
  ArmOperandConverter i(this, instr);
  Register input = i.InputRegister(0);
  std::vector<std::pair<int32_t, Label*>> cases;
  for (size_t index = 2; index < instr->InputCount(); index += 2) {
    cases.push_back({i.InputInt32(index + 0), GetLabel(i.InputRpo(index + 1))});
  }
  AssembleArchBinarySearchSwitchRange(input, i.InputRpo(1), cases.data(),
                                      cases.data() + cases.size());
}
References AssembleArchBinarySearchSwitchRange(), GetLabel(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, and v8::internal::compiler::Instruction::InputCount().
Referenced by AssembleArchInstruction().
AssembleArchBinarySearchSwitchRange()
void v8::internal::compiler::CodeGenerator::AssembleArchBinarySearchSwitchRange (Register input, RpoNumber def_block, std::pair< int32_t, Label * > * begin, std::pair< int32_t, Label * > * end) [private]
Definition at line 470 of file code-generator.cc.
                                   {
  if (end - begin < kBinarySearchSwitchMinimalCases) {
    while (begin != end) {
      masm()->JumpIfEqual(input, begin->first, begin->second);
      ++begin;
    }
    AssembleArchJumpRegardlessOfAssemblyOrder(def_block);
    return;
  }
  auto middle = begin + (end - begin) / 2;
  Label less_label;
  masm()->JumpIfLessThan(input, middle->first, &less_label);
  AssembleArchBinarySearchSwitchRange(input, def_block, middle, end);
  masm()->bind(&less_label);
  AssembleArchBinarySearchSwitchRange(input, def_block, begin, middle);
}
References AssembleArchJumpRegardlessOfAssemblyOrder(), v8::internal::compiler::begin(), v8::internal::Assembler::bind(), v8::internal::compiler::end(), v8::internal::MacroAssembler::JumpIfEqual(), v8::internal::MacroAssembler::JumpIfLessThan(), kBinarySearchSwitchMinimalCases, and masm().
Referenced by AssembleArchBinarySearchSwitch().
AssembleArchBoolean()
void v8::internal::compiler::CodeGenerator::AssembleArchBoolean (Instruction * instr, FlagsCondition condition) [private]
Definition at line 3700 of file code-generator-arm.cc.
                                                                  {
  ArmOperandConverter i(this, instr);
  // Materialize a full 32-bit 1 or 0 value. The result register is always the
  // last output of the instruction.
  DCHECK_NE(0u, instr->OutputCount());
  Register reg = i.OutputRegister(instr->OutputCount() - 1);
  Condition cc = FlagsConditionToCondition(condition);
  __ mov(reg, Operand(0));
  __ mov(reg, Operand(1), LeaveCC, cc);
}
References __, v8::internal::cc, DCHECK_NE, v8::internal::compiler::FlagsConditionToCondition(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::LeaveCC, and v8::internal::compiler::Instruction::OutputCount().
Referenced by AssembleInstruction().
AssembleArchBranch()
void v8::internal::compiler::CodeGenerator::AssembleArchBranch (Instruction * instr, BranchInfo * branch) [private]
Definition at line 3640 of file code-generator-arm.cc.
                                                                             {
  ArmOperandConverter i(this, instr);
  Label* tlabel = branch->true_label;
  Label* flabel = branch->false_label;
  Condition cc = FlagsConditionToCondition(branch->condition);
  __ b(cc, tlabel);
  if (!branch->fallthru) __ b(flabel); // no fallthru to flabel.
}
References __, v8::internal::cc, v8::internal::compiler::BranchInfo::condition, v8::internal::compiler::BranchInfo::fallthru, v8::internal::compiler::BranchInfo::false_label, v8::internal::compiler::FlagsConditionToCondition(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::BranchInfo::true_label.
Referenced by AssembleArchDeoptBranch(), and AssembleInstruction().
AssembleArchConditionalBoolean()
void v8::internal::compiler::CodeGenerator::AssembleArchConditionalBoolean (Instruction * instr) [private]
Definition at line 3713 of file code-generator-arm.cc.
                                                                     {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by AssembleInstruction().
AssembleArchConditionalBranch()
void v8::internal::compiler::CodeGenerator::AssembleArchConditionalBranch (Instruction * instr, BranchInfo * branch) [private]
Definition at line 3717 of file code-generator-arm.cc.
                                                                      {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by AssembleInstruction().
AssembleArchDeoptBranch()
void v8::internal::compiler::CodeGenerator::AssembleArchDeoptBranch (Instruction * instr, BranchInfo * branch) [private]
Definition at line 3649 of file code-generator-arm.cc.
                                                                {
  AssembleArchBranch(instr, branch);
}
References AssembleArchBranch().
Referenced by AssembleInstruction().
AssembleArchInstruction()
CodeGenerator::CodeGenResult v8::internal::compiler::CodeGenerator::AssembleArchInstruction (Instruction * instr) [private]
Definition at line 653 of file code-generator-arm.cc.
                        {
  ArmOperandConverter i(this, instr);
  __ MaybeCheckConstPool();
  InstructionCode opcode = instr->opcode();
  ArchOpcode arch_opcode = ArchOpcodeField::decode(opcode);
  switch (arch_opcode) {
    case kArchCallCodeObject: {
      if (instr->InputAt(0)->IsImmediate()) {
        __ Call(i.InputCode(0), RelocInfo::CODE_TARGET);
      } else {
        Register reg = i.InputRegister(0);
        DCHECK_IMPLIES(
            instr->HasCallDescriptorFlag(CallDescriptor::kFixedTargetRegister),
            reg == kJavaScriptCallCodeStartRegister);
        __ CallCodeObject(reg);
      }
      RecordCallPosition(instr);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      frame_access_state()->ClearSPDelta();
      break;
    }
    case kArchCallBuiltinPointer: {
      DCHECK(!instr->InputAt(0)->IsImmediate());
      Register builtin_index = i.InputRegister(0);
      Register target =
          instr->HasCallDescriptorFlag(CallDescriptor::kFixedTargetRegister)
              ? kJavaScriptCallCodeStartRegister
              : builtin_index;
      __ CallBuiltinByIndex(builtin_index, target);
      RecordCallPosition(instr);
      frame_access_state()->ClearSPDelta();
      break;
    }
#if V8_ENABLE_WEBASSEMBLY
    case kArchCallWasmFunction:
    case kArchCallWasmFunctionIndirect: {
      if (instr->InputAt(0)->IsImmediate()) {
        DCHECK_EQ(arch_opcode, kArchCallWasmFunction);
        Constant constant = i.ToConstant(instr->InputAt(0));
        Address wasm_code = static_cast<Address>(constant.ToInt32());
        __ Call(wasm_code, constant.rmode());
      } else if (arch_opcode == kArchCallWasmFunctionIndirect) {
        __ CallWasmCodePointer(i.InputRegister(0));
      } else {
        __ Call(i.InputRegister(0));
      }
      RecordCallPosition(instr);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      frame_access_state()->ClearSPDelta();
      break;
    }
    case kArchTailCallWasm:
    case kArchTailCallWasmIndirect: {
      if (instr->InputAt(0)->IsImmediate()) {
        DCHECK_EQ(arch_opcode, kArchTailCallWasm);
        Constant constant = i.ToConstant(instr->InputAt(0));
        Address wasm_code = static_cast<Address>(constant.ToInt32());
        __ Jump(wasm_code, constant.rmode());
      } else if (arch_opcode == kArchTailCallWasmIndirect) {
        __ CallWasmCodePointer(i.InputRegister(0), CallJumpMode::kTailCall);
      } else {
        __ Jump(i.InputRegister(0));
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      unwinding_info_writer_.MarkBlockWillExit();
      frame_access_state()->ClearSPDelta();
      frame_access_state()->SetFrameAccessToDefault();
      break;
    }
#endif // V8_ENABLE_WEBASSEMBLY
    case kArchTailCallCodeObject: {
      if (instr->InputAt(0)->IsImmediate()) {
        __ Jump(i.InputCode(0), RelocInfo::CODE_TARGET);
      } else {
        Register reg = i.InputRegister(0);
        DCHECK_IMPLIES(
            instr->HasCallDescriptorFlag(CallDescriptor::kFixedTargetRegister),
            reg == kJavaScriptCallCodeStartRegister);
        __ JumpCodeObject(reg);
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      unwinding_info_writer_.MarkBlockWillExit();
      frame_access_state()->ClearSPDelta();
      frame_access_state()->SetFrameAccessToDefault();
      break;
    }
    case kArchTailCallAddress: {
      CHECK(!instr->InputAt(0)->IsImmediate());
      Register reg = i.InputRegister(0);
      DCHECK_IMPLIES(
          instr->HasCallDescriptorFlag(CallDescriptor::kFixedTargetRegister),
          reg == kJavaScriptCallCodeStartRegister);
      __ Jump(reg);
      unwinding_info_writer_.MarkBlockWillExit();
      frame_access_state()->ClearSPDelta();
      frame_access_state()->SetFrameAccessToDefault();
      break;
    }
    case kArchCallJSFunction: {
      Register func = i.InputRegister(0);
      if (v8_flags.debug_code) {
        UseScratchRegisterScope temps(masm());
        Register scratch = temps.Acquire();
        // Check the function's context matches the context argument.
        __ ldr(scratch, FieldMemOperand(func, JSFunction::kContextOffset));
        __ cmp(cp, scratch);
        __ Assert(eq, AbortReason::kWrongFunctionContext);
      }
      uint32_t num_arguments =
          i.InputUint32(instr->JSCallArgumentCountInputIndex());
      __ CallJSFunction(func, num_arguments);
      RecordCallPosition(instr);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      frame_access_state()->ClearSPDelta();
      break;
    }
    case kArchPrepareCallCFunction: {
      int const num_parameters = MiscField::decode(instr->opcode());
      __ PrepareCallCFunction(num_parameters);
      // Frame alignment requires using FP-relative frame addressing.
      frame_access_state()->SetFrameAccessToFP();
      break;
    }
    case kArchSaveCallerRegisters: {
      fp_mode_ =
          static_cast<SaveFPRegsMode>(MiscField::decode(instr->opcode()));
      DCHECK(fp_mode_ == SaveFPRegsMode::kIgnore ||
             fp_mode_ == SaveFPRegsMode::kSave);
      // kReturnRegister0 should have been saved before entering the stub.
      int bytes = __ PushCallerSaved(fp_mode_, kReturnRegister0);
      DCHECK(IsAligned(bytes, kSystemPointerSize));
      DCHECK_EQ(0, frame_access_state()->sp_delta());
      frame_access_state()->IncreaseSPDelta(bytes / kSystemPointerSize);
      DCHECK(!caller_registers_saved_);
      caller_registers_saved_ = true;
      break;
    }
    case kArchRestoreCallerRegisters: {
      DCHECK(fp_mode_ ==
             static_cast<SaveFPRegsMode>(MiscField::decode(instr->opcode())));
      DCHECK(fp_mode_ == SaveFPRegsMode::kIgnore ||
             fp_mode_ == SaveFPRegsMode::kSave);
      // Don't overwrite the returned value.
      int bytes = __ PopCallerSaved(fp_mode_, kReturnRegister0);
      frame_access_state()->IncreaseSPDelta(-(bytes / kSystemPointerSize));
      DCHECK_EQ(0, frame_access_state()->sp_delta());
      DCHECK(caller_registers_saved_);
      caller_registers_saved_ = false;
      break;
    }
    case kArchPrepareTailCall:
      AssemblePrepareTailCall();
      break;
    case kArchCallCFunction: {
      uint32_t param_counts = i.InputUint32(instr->InputCount() - 1);
      int const num_gp_parameters = ParamField::decode(param_counts);
      int const num_fp_parameters = FPParamField::decode(param_counts);
      int const num_parameters = num_gp_parameters + num_fp_parameters;
      SetIsolateDataSlots set_isolate_data_slots = SetIsolateDataSlots::kYes;
      Label return_location;
#if V8_ENABLE_WEBASSEMBLY
      if (linkage()->GetIncomingDescriptor()->IsWasmCapiFunction()) {
        // Put the return address in a stack slot.
        Register pc_scratch = r5;
        __ Push(pc_scratch);
        __ GetLabelAddress(pc_scratch, &return_location);
        __ str(pc_scratch,
               MemOperand(fp, WasmExitFrameConstants::kCallingPCOffset));
        __ Pop(pc_scratch);
        set_isolate_data_slots = SetIsolateDataSlots::kNo;
      }
#endif // V8_ENABLE_WEBASSEMBLY
      int pc_offset;
      if (instr->InputAt(0)->IsImmediate()) {
        ExternalReference ref = i.InputExternalReference(0);
        pc_offset = __ CallCFunction(ref, num_parameters,
                                     set_isolate_data_slots, &return_location);
      } else {
        Register func = i.InputRegister(0);
        pc_offset = __ CallCFunction(func, num_parameters,
                                     set_isolate_data_slots, &return_location);
      }
      RecordSafepoint(instr->reference_map(), pc_offset);
      if (instr->HasCallDescriptorFlag(CallDescriptor::kHasExceptionHandler)) {
        handlers_.push_back({nullptr, pc_offset});
      }
      if (instr->HasCallDescriptorFlag(CallDescriptor::kNeedsFrameState)) {
        RecordDeoptInfo(instr, pc_offset);
      }
      frame_access_state()->SetFrameAccessToDefault();
      // Ideally, we should decrement SP delta to match the change of stack
      // pointer in CallCFunction. However, for certain architectures (e.g.
      // ARM), there may be more strict alignment requirement, causing old SP
      // to be saved on the stack. In those cases, we can not calculate the SP
      // delta statically.
      frame_access_state()->ClearSPDelta();
      if (caller_registers_saved_) {
        // Need to re-sync SP delta introduced in kArchSaveCallerRegisters.
        // Here, we assume the sequence to be:
        // kArchSaveCallerRegisters;
        // kArchCallCFunction;
        // kArchRestoreCallerRegisters;
        int bytes =
            __ RequiredStackSizeForCallerSaved(fp_mode_, kReturnRegister0);
        frame_access_state()->IncreaseSPDelta(bytes / kSystemPointerSize);
      }
      break;
    }
    case kArchJmp:
      AssembleArchJump(i.InputRpo(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArchBinarySearchSwitch:
      AssembleArchBinarySearchSwitch(instr);
      break;
    case kArchTableSwitch:
      AssembleArchTableSwitch(instr);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArchAbortCSADcheck:
      DCHECK(i.InputRegister(0) == r1);
      {
        // We don't actually want to generate a pile of code for this, so just
        // claim there is a stack frame, without generating one.
        FrameScope scope(masm(), StackFrame::NO_FRAME_TYPE);
        __ CallBuiltin(Builtin::kAbortCSADcheck);
      }
      __ stop();
      unwinding_info_writer_.MarkBlockWillExit();
      break;
    case kArchDebugBreak:
      __ DebugBreak();
      break;
    case kArchComment:
      __ RecordComment(reinterpret_cast<const char*>(i.InputInt32(0)),
                       SourceLocation());
      break;
    case kArchNop:
      // don't emit code for nops.
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArchDeoptimize: {
      DeoptimizationExit* exit =
          BuildTranslation(instr, -1, 0, 0, OutputFrameStateCombine::Ignore());
      __ b(exit->label());
      break;
    }
    case kArchRet:
      AssembleReturn(instr->InputAt(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArchFramePointer:
      __ mov(i.OutputRegister(), fp);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArchParentFramePointer:
      if (frame_access_state()->has_frame()) {
        __ ldr(i.OutputRegister(), MemOperand(fp, 0));
      } else {
        __ mov(i.OutputRegister(), fp);
      }
      break;
    case kArchRootPointer:
      __ mov(i.OutputRegister(), kRootRegister);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
#if V8_ENABLE_WEBASSEMBLY
    case kArchStackPointer:
      // The register allocator expects an allocatable register for the output,
      // we cannot use sp directly.
      __ mov(i.OutputRegister(), sp);
      break;
    case kArchSetStackPointer:
      DCHECK(instr->InputAt(0)->IsRegister());
      __ mov(sp, i.InputRegister(0));
      break;
#endif // V8_ENABLE_WEBASSEMBLY
    case kArchStackPointerGreaterThan: {
      // Potentially apply an offset to the current stack pointer before the
      // comparison to consider the size difference of an optimized frame versus
      // the contained unoptimized frames.
      Register lhs_register = sp;
      uint32_t offset;
      if (ShouldApplyOffsetToStackCheck(instr, &offset)) {
        lhs_register = i.TempRegister(0);
        __ sub(lhs_register, sp, Operand(offset));
      }
      constexpr size_t kValueIndex = 0;
      DCHECK(instr->InputAt(kValueIndex)->IsRegister());
      __ cmp(lhs_register, i.InputRegister(kValueIndex));
      break;
    }
    case kArchStackCheckOffset:
      __ Move(i.OutputRegister(), Smi::FromInt(GetStackCheckOffset()));
      break;
    case kArchTruncateDoubleToI:
      __ TruncateDoubleToI(isolate(), zone(), i.OutputRegister(),
                           i.InputDoubleRegister(0), DetermineStubCallMode());
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArchStoreWithWriteBarrier: // Fall through.
    case kArchAtomicStoreWithWriteBarrier: {
      RecordWriteMode mode;
      if (arch_opcode == kArchStoreWithWriteBarrier) {
        mode = RecordWriteModeField::decode(instr->opcode());
      } else {
        mode = AtomicStoreRecordWriteModeField::decode(instr->opcode());
      }
      Register object = i.InputRegister(0);
      Register value = i.InputRegister(2);
      if (v8_flags.debug_code) {
        // Checking that |value| is not a cleared weakref: our write barrier
        // does not support that for now.
        __ cmp(value, Operand(kClearedWeakHeapObjectLower32));
        __ Check(ne, AbortReason::kOperandIsCleared);
      }
      AddressingMode addressing_mode =
          AddressingModeField::decode(instr->opcode());
      Operand offset(0);
      if (arch_opcode == kArchAtomicStoreWithWriteBarrier) {
        __ dmb(ISH);
      }
      if (addressing_mode == kMode_Offset_RI) {
        int32_t immediate = i.InputInt32(1);
        offset = Operand(immediate);
        __ str(value, MemOperand(object, immediate));
      } else {
        DCHECK_EQ(kMode_Offset_RR, addressing_mode);
        Register reg = i.InputRegister(1);
        offset = Operand(reg);
        __ str(value, MemOperand(object, reg));
      }
      if (arch_opcode == kArchAtomicStoreWithWriteBarrier &&
          AtomicMemoryOrderField::decode(instr->opcode()) ==
              AtomicMemoryOrder::kSeqCst) {
        __ dmb(ISH);
      }
      auto ool = zone()->New<OutOfLineRecordWrite>(
          this, object, offset, value, mode, DetermineStubCallMode(),
          &unwinding_info_writer_);
      if (mode > RecordWriteMode::kValueIsPointer) {
        __ JumpIfSmi(value, ool->exit());
      }
      __ CheckPageFlag(object, MemoryChunk::kPointersFromHereAreInterestingMask,
                       ne, ool->entry());
      __ bind(ool->exit());
      break;
    }
    case kArchStoreIndirectWithWriteBarrier:
      UNREACHABLE();
    case kArchStackSlot: {
      FrameOffset offset =
          frame_access_state()->GetFrameOffset(i.InputInt32(0));
      Register base = offset.from_stack_pointer() ? sp : fp;
      __ add(i.OutputRegister(0), base, Operand(offset.offset()));
      break;
    }
    case kIeee754Float64Acos:
      ASSEMBLE_IEEE754_UNOP(acos);
      break;
    case kIeee754Float64Acosh:
      ASSEMBLE_IEEE754_UNOP(acosh);
      break;
    case kIeee754Float64Asin:
      ASSEMBLE_IEEE754_UNOP(asin);
      break;
    case kIeee754Float64Asinh:
      ASSEMBLE_IEEE754_UNOP(asinh);
      break;
    case kIeee754Float64Atan:
      ASSEMBLE_IEEE754_UNOP(atan);
      break;
    case kIeee754Float64Atanh:
      ASSEMBLE_IEEE754_UNOP(atanh);
      break;
    case kIeee754Float64Atan2:
      ASSEMBLE_IEEE754_BINOP(atan2);
      break;
    case kIeee754Float64Cbrt:
      ASSEMBLE_IEEE754_UNOP(cbrt);
      break;
    case kIeee754Float64Cos:
      ASSEMBLE_IEEE754_UNOP(cos);
      break;
    case kIeee754Float64Cosh:
      ASSEMBLE_IEEE754_UNOP(cosh);
      break;
    case kIeee754Float64Exp:
      ASSEMBLE_IEEE754_UNOP(exp);
      break;
    case kIeee754Float64Expm1:
      ASSEMBLE_IEEE754_UNOP(expm1);
      break;
    case kIeee754Float64Log:
      ASSEMBLE_IEEE754_UNOP(log);
      break;
    case kIeee754Float64Log1p:
      ASSEMBLE_IEEE754_UNOP(log1p);
      break;
    case kIeee754Float64Log2:
      ASSEMBLE_IEEE754_UNOP(log2);
      break;
    case kIeee754Float64Log10:
      ASSEMBLE_IEEE754_UNOP(log10);
      break;
    case kIeee754Float64Pow:
      ASSEMBLE_IEEE754_BINOP(pow);
      break;
    case kIeee754Float64Sin:
      ASSEMBLE_IEEE754_UNOP(sin);
      break;
    case kIeee754Float64Sinh:
      ASSEMBLE_IEEE754_UNOP(sinh);
      break;
    case kIeee754Float64Tan:
      ASSEMBLE_IEEE754_UNOP(tan);
      break;
    case kIeee754Float64Tanh:
      ASSEMBLE_IEEE754_UNOP(tanh);
      break;
    case kArmAdd:
      __ add(i.OutputRegister(), i.InputRegister(0), i.InputOperand2(1),
             i.OutputSBit());
      break;
    case kArmAnd:
      __ and_(i.OutputRegister(), i.InputRegister(0), i.InputOperand2(1),
              i.OutputSBit());
      break;
    case kArmBic:
      __ bic(i.OutputRegister(), i.InputRegister(0), i.InputOperand2(1),
             i.OutputSBit());
      break;
    case kArmMul:
      __ mul(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1),
             i.OutputSBit());
      break;
    case kArmMla:
      __ mla(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1),
             i.InputRegister(2), i.OutputSBit());
      break;
    case kArmMls: {
      CpuFeatureScope scope(masm(), ARMv7);
      __ mls(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1),
             i.InputRegister(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmSmull:
      __ smull(i.OutputRegister(0), i.OutputRegister(1), i.InputRegister(0),
               i.InputRegister(1));
      break;
    case kArmSmmul:
      __ smmul(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmSmmla:
      __ smmla(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1),
               i.InputRegister(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmUmull:
      __ umull(i.OutputRegister(0), i.OutputRegister(1), i.InputRegister(0),
               i.InputRegister(1), i.OutputSBit());
      break;
    case kArmSdiv: {
      CpuFeatureScope scope(masm(), SUDIV);
      __ sdiv(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmUdiv: {
      CpuFeatureScope scope(masm(), SUDIV);
      __ udiv(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmMov:
      __ Move(i.OutputRegister(), i.InputOperand2(0), i.OutputSBit());
      break;
    case kArmMvn:
      __ mvn(i.OutputRegister(), i.InputOperand2(0), i.OutputSBit());
      break;
    case kArmOrr:
      __ orr(i.OutputRegister(), i.InputRegister(0), i.InputOperand2(1),
             i.OutputSBit());
      break;
    case kArmEor:
      __ eor(i.OutputRegister(), i.InputRegister(0), i.InputOperand2(1),
             i.OutputSBit());
      break;
    case kArmSub:
      __ sub(i.OutputRegister(), i.InputRegister(0), i.InputOperand2(1),
             i.OutputSBit());
      break;
    case kArmRsb:
      __ rsb(i.OutputRegister(), i.InputRegister(0), i.InputOperand2(1),
             i.OutputSBit());
      break;
    case kArmBfc: {
      CpuFeatureScope scope(masm(), ARMv7);
      __ bfc(i.OutputRegister(), i.InputInt8(1), i.InputInt8(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmUbfx: {
      CpuFeatureScope scope(masm(), ARMv7);
      __ ubfx(i.OutputRegister(), i.InputRegister(0), i.InputInt8(1),
              i.InputInt8(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmSbfx: {
      CpuFeatureScope scope(masm(), ARMv7);
      __ sbfx(i.OutputRegister(), i.InputRegister(0), i.InputInt8(1),
              i.InputInt8(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmSxtb:
      __ sxtb(i.OutputRegister(), i.InputRegister(0), i.InputInt32(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmSxth:
      __ sxth(i.OutputRegister(), i.InputRegister(0), i.InputInt32(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmSxtab:
      __ sxtab(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1),
               i.InputInt32(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmSxtah:
      __ sxtah(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1),
               i.InputInt32(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmUxtb:
      __ uxtb(i.OutputRegister(), i.InputRegister(0), i.InputInt32(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmUxth:
      __ uxth(i.OutputRegister(), i.InputRegister(0), i.InputInt32(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmUxtab:
      __ uxtab(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1),
               i.InputInt32(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmUxtah:
      __ uxtah(i.OutputRegister(), i.InputRegister(0), i.InputRegister(1),
               i.InputInt32(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmRbit: {
      CpuFeatureScope scope(masm(), ARMv7);
      __ rbit(i.OutputRegister(), i.InputRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmRev:
      __ rev(i.OutputRegister(), i.InputRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmClz:
      __ clz(i.OutputRegister(), i.InputRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmCmp:
      __ cmp(i.InputRegister(0), i.InputOperand2(1));
      DCHECK_EQ(SetCC, i.OutputSBit());
      break;
    case kArmCmn:
      __ cmn(i.InputRegister(0), i.InputOperand2(1));
      DCHECK_EQ(SetCC, i.OutputSBit());
      break;
    case kArmTst:
      __ tst(i.InputRegister(0), i.InputOperand2(1));
      DCHECK_EQ(SetCC, i.OutputSBit());
      break;
    case kArmTeq:
      __ teq(i.InputRegister(0), i.InputOperand2(1));
      DCHECK_EQ(SetCC, i.OutputSBit());
      break;
    case kArmAddPair:
      // i.InputRegister(0) ... left low word.
      // i.InputRegister(1) ... left high word.
      // i.InputRegister(2) ... right low word.
      // i.InputRegister(3) ... right high word.
      __ add(i.OutputRegister(0), i.InputRegister(0), i.InputRegister(2),
             SetCC);
      __ adc(i.OutputRegister(1), i.InputRegister(1),
             Operand(i.InputRegister(3)));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmSubPair:
      // i.InputRegister(0) ... left low word.
      // i.InputRegister(1) ... left high word.
      // i.InputRegister(2) ... right low word.
      // i.InputRegister(3) ... right high word.
      __ sub(i.OutputRegister(0), i.InputRegister(0), i.InputRegister(2),
             SetCC);
      __ sbc(i.OutputRegister(1), i.InputRegister(1),
             Operand(i.InputRegister(3)));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmMulPair:
      // i.InputRegister(0) ... left low word.
      // i.InputRegister(1) ... left high word.
      // i.InputRegister(2) ... right low word.
      // i.InputRegister(3) ... right high word.
      __ umull(i.OutputRegister(0), i.OutputRegister(1), i.InputRegister(0),
               i.InputRegister(2));
      __ mla(i.OutputRegister(1), i.InputRegister(0), i.InputRegister(3),
             i.OutputRegister(1));
      __ mla(i.OutputRegister(1), i.InputRegister(2), i.InputRegister(1),
             i.OutputRegister(1));
      break;
    case kArmLslPair: {
      Register second_output =
          instr->OutputCount() >= 2 ? i.OutputRegister(1) : i.TempRegister(0);
      if (instr->InputAt(2)->IsImmediate()) {
        __ LslPair(i.OutputRegister(0), second_output, i.InputRegister(0),
                   i.InputRegister(1), i.InputInt32(2));
      } else {
        __ LslPair(i.OutputRegister(0), second_output, i.InputRegister(0),
                   i.InputRegister(1), i.InputRegister(2));
      }
      break;
    }
    case kArmLsrPair: {
      Register second_output =
          instr->OutputCount() >= 2 ? i.OutputRegister(1) : i.TempRegister(0);
      if (instr->InputAt(2)->IsImmediate()) {
        __ LsrPair(i.OutputRegister(0), second_output, i.InputRegister(0),
                   i.InputRegister(1), i.InputInt32(2));
      } else {
        __ LsrPair(i.OutputRegister(0), second_output, i.InputRegister(0),
                   i.InputRegister(1), i.InputRegister(2));
      }
      break;
    }
    case kArmAsrPair: {
      Register second_output =
          instr->OutputCount() >= 2 ? i.OutputRegister(1) : i.TempRegister(0);
      if (instr->InputAt(2)->IsImmediate()) {
        __ AsrPair(i.OutputRegister(0), second_output, i.InputRegister(0),
                   i.InputRegister(1), i.InputInt32(2));
      } else {
        __ AsrPair(i.OutputRegister(0), second_output, i.InputRegister(0),
                   i.InputRegister(1), i.InputRegister(2));
      }
      break;
    }
    case kArmVcmpF32:
      if (instr->InputAt(1)->IsFPRegister()) {
        __ VFPCompareAndSetFlags(i.InputFloatRegister(0),
                                 i.InputFloatRegister(1));
      } else {
        DCHECK(instr->InputAt(1)->IsImmediate());
        // 0.0 is the only immediate supported by vcmp instructions.
        DCHECK_EQ(0.0f, i.InputFloat32(1));
        __ VFPCompareAndSetFlags(i.InputFloatRegister(0), i.InputFloat32(1));
      }
      DCHECK_EQ(SetCC, i.OutputSBit());
      break;
    case kArmVaddF32:
      __ vadd(i.OutputFloatRegister(), i.InputFloatRegister(0),
              i.InputFloatRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVsubF32:
      __ vsub(i.OutputFloatRegister(), i.InputFloatRegister(0),
              i.InputFloatRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmulF32:
      __ vmul(i.OutputFloatRegister(), i.InputFloatRegister(0),
              i.InputFloatRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmlaF32:
      __ vmla(i.OutputFloatRegister(), i.InputFloatRegister(1),
              i.InputFloatRegister(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmlsF32:
      __ vmls(i.OutputFloatRegister(), i.InputFloatRegister(1),
              i.InputFloatRegister(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVdivF32:
      __ vdiv(i.OutputFloatRegister(), i.InputFloatRegister(0),
              i.InputFloatRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVsqrtF32:
      __ vsqrt(i.OutputFloatRegister(), i.InputFloatRegister(0));
      break;
    case kArmVabsF32:
      __ vabs(i.OutputFloatRegister(), i.InputFloatRegister(0));
      break;
    case kArmVnegF32:
      __ vneg(i.OutputFloatRegister(), i.InputFloatRegister(0));
      break;
    case kArmVcmpF64:
      if (instr->InputAt(1)->IsFPRegister()) {
        __ VFPCompareAndSetFlags(i.InputDoubleRegister(0),
                                 i.InputDoubleRegister(1));
      } else {
        DCHECK(instr->InputAt(1)->IsImmediate());
        // 0.0 is the only immediate supported by vcmp instructions.
        DCHECK_EQ(0.0, i.InputDouble(1));
        __ VFPCompareAndSetFlags(i.InputDoubleRegister(0), i.InputDouble(1));
      }
      DCHECK_EQ(SetCC, i.OutputSBit());
      break;
    case kArmVaddF64:
      __ vadd(i.OutputDoubleRegister(), i.InputDoubleRegister(0),
              i.InputDoubleRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVsubF64:
      __ vsub(i.OutputDoubleRegister(), i.InputDoubleRegister(0),
              i.InputDoubleRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmulF64:
      __ vmul(i.OutputDoubleRegister(), i.InputDoubleRegister(0),
              i.InputDoubleRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmlaF64:
      __ vmla(i.OutputDoubleRegister(), i.InputDoubleRegister(1),
              i.InputDoubleRegister(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmlsF64:
      __ vmls(i.OutputDoubleRegister(), i.InputDoubleRegister(1),
              i.InputDoubleRegister(2));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVdivF64:
      __ vdiv(i.OutputDoubleRegister(), i.InputDoubleRegister(0),
              i.InputDoubleRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmodF64: {
      // TODO(bmeurer): We should really get rid of this special instruction,
      // and generate a CallAddress instruction instead.
      FrameScope scope(masm(), StackFrame::MANUAL);
      __ PrepareCallCFunction(0, 2);
      __ MovToFloatParameters(i.InputDoubleRegister(0),
                              i.InputDoubleRegister(1));
      __ CallCFunction(ExternalReference::mod_two_doubles_operation(), 0, 2);
      // Move the result in the double result register.
      __ MovFromFloatResult(i.OutputDoubleRegister());
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVsqrtF64:
      __ vsqrt(i.OutputDoubleRegister(), i.InputDoubleRegister(0));
      break;
    case kArmVabsF64:
      __ vabs(i.OutputDoubleRegister(), i.InputDoubleRegister(0));
      break;
    case kArmVnegF64:
      __ vneg(i.OutputDoubleRegister(), i.InputDoubleRegister(0));
      break;
    case kArmVrintmF32: {
      CpuFeatureScope scope(masm(), ARMv8);
      if (instr->InputAt(0)->IsSimd128Register()) {
        __ vrintm(NeonS32, i.OutputSimd128Register(),
                  i.InputSimd128Register(0));
      } else {
        __ vrintm(i.OutputFloatRegister(), i.InputFloatRegister(0));
      }
      break;
    }
    case kArmVrintmF64: {
      CpuFeatureScope scope(masm(), ARMv8);
      __ vrintm(i.OutputDoubleRegister(), i.InputDoubleRegister(0));
      break;
    }
    case kArmVrintpF32: {
      CpuFeatureScope scope(masm(), ARMv8);
      if (instr->InputAt(0)->IsSimd128Register()) {
        __ vrintp(NeonS32, i.OutputSimd128Register(),
                  i.InputSimd128Register(0));
      } else {
        __ vrintp(i.OutputFloatRegister(), i.InputFloatRegister(0));
      }
      break;
    }
    case kArmVrintpF64: {
      CpuFeatureScope scope(masm(), ARMv8);
      __ vrintp(i.OutputDoubleRegister(), i.InputDoubleRegister(0));
      break;
    }
    case kArmVrintzF32: {
      CpuFeatureScope scope(masm(), ARMv8);
      if (instr->InputAt(0)->IsSimd128Register()) {
        __ vrintz(NeonS32, i.OutputSimd128Register(),
                  i.InputSimd128Register(0));
      } else {
        __ vrintz(i.OutputFloatRegister(), i.InputFloatRegister(0));
      }
      break;
    }
    case kArmVrintzF64: {
      CpuFeatureScope scope(masm(), ARMv8);
      __ vrintz(i.OutputDoubleRegister(), i.InputDoubleRegister(0));
      break;
    }
    case kArmVrintaF64: {
      CpuFeatureScope scope(masm(), ARMv8);
      __ vrinta(i.OutputDoubleRegister(), i.InputDoubleRegister(0));
      break;
    }
    case kArmVrintnF32: {
      CpuFeatureScope scope(masm(), ARMv8);
      if (instr->InputAt(0)->IsSimd128Register()) {
        __ vrintn(NeonS32, i.OutputSimd128Register(),
                  i.InputSimd128Register(0));
      } else {
        __ vrintn(i.OutputFloatRegister(), i.InputFloatRegister(0));
      }
      break;
    }
    case kArmVrintnF64: {
      CpuFeatureScope scope(masm(), ARMv8);
      __ vrintn(i.OutputDoubleRegister(), i.InputDoubleRegister(0));
      break;
    }
    case kArmVcvtF32F64: {
      __ vcvt_f32_f64(i.OutputFloatRegister(), i.InputDoubleRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtF64F32: {
      __ vcvt_f64_f32(i.OutputDoubleRegister(), i.InputFloatRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtF32S32: {
      UseScratchRegisterScope temps(masm());
      SwVfpRegister scratch = temps.AcquireS();
      __ vmov(scratch, i.InputRegister(0));
      __ vcvt_f32_s32(i.OutputFloatRegister(), scratch);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtF32U32: {
      UseScratchRegisterScope temps(masm());
      SwVfpRegister scratch = temps.AcquireS();
      __ vmov(scratch, i.InputRegister(0));
      __ vcvt_f32_u32(i.OutputFloatRegister(), scratch);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtF64S32: {
      UseScratchRegisterScope temps(masm());
      SwVfpRegister scratch = temps.AcquireS();
      __ vmov(scratch, i.InputRegister(0));
      __ vcvt_f64_s32(i.OutputDoubleRegister(), scratch);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtF64U32: {
      UseScratchRegisterScope temps(masm());
      SwVfpRegister scratch = temps.AcquireS();
      __ vmov(scratch, i.InputRegister(0));
      __ vcvt_f64_u32(i.OutputDoubleRegister(), scratch);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtS32F32: {
      UseScratchRegisterScope temps(masm());
      SwVfpRegister scratch = temps.AcquireS();
      __ vcvt_s32_f32(scratch, i.InputFloatRegister(0));
      __ vmov(i.OutputRegister(), scratch);
      bool set_overflow_to_min_i32 = MiscField::decode(instr->opcode());
      if (set_overflow_to_min_i32) {
        // Avoid INT32_MAX as an overflow indicator and use INT32_MIN instead,
        // because INT32_MIN allows easier out-of-bounds detection.
        __ cmn(i.OutputRegister(), Operand(1));
        __ mov(i.OutputRegister(), Operand(INT32_MIN), LeaveCC, vs);
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtU32F32: {
      UseScratchRegisterScope temps(masm());
      SwVfpRegister scratch = temps.AcquireS();
      __ vcvt_u32_f32(scratch, i.InputFloatRegister(0));
      __ vmov(i.OutputRegister(), scratch);
      bool set_overflow_to_min_u32 = MiscField::decode(instr->opcode());
      if (set_overflow_to_min_u32) {
        // Avoid UINT32_MAX as an overflow indicator and use 0 instead,
        // because 0 allows easier out-of-bounds detection.
        __ cmn(i.OutputRegister(), Operand(1));
        __ adc(i.OutputRegister(), i.OutputRegister(), Operand::Zero());
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtS32F64: {
      UseScratchRegisterScope temps(masm());
      SwVfpRegister scratch = temps.AcquireS();
      __ vcvt_s32_f64(scratch, i.InputDoubleRegister(0));
      __ vmov(i.OutputRegister(), scratch);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVcvtU32F64: {
      UseScratchRegisterScope temps(masm());
      SwVfpRegister scratch = temps.AcquireS();
      __ vcvt_u32_f64(scratch, i.InputDoubleRegister(0));
      __ vmov(i.OutputRegister(), scratch);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVmovU32F32:
      __ vmov(i.OutputRegister(), i.InputFloatRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmovF32U32:
      __ vmov(i.OutputFloatRegister(), i.InputRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmovLowU32F64:
      __ VmovLow(i.OutputRegister(), i.InputDoubleRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmovLowF64U32:
      __ VmovLow(i.OutputDoubleRegister(), i.InputRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmovHighU32F64:
      __ VmovHigh(i.OutputRegister(), i.InputDoubleRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmovHighF64U32:
      __ VmovHigh(i.OutputDoubleRegister(), i.InputRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmovF64U32U32:
      __ vmov(i.OutputDoubleRegister(), i.InputRegister(0), i.InputRegister(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVmovU32U32F64:
      __ vmov(i.OutputRegister(0), i.OutputRegister(1),
              i.InputDoubleRegister(0));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVcnt: {
      __ vcnt(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmLdrb:
      __ ldrb(i.OutputRegister(), i.InputOffset());
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmLdrsb:
      __ ldrsb(i.OutputRegister(), i.InputOffset());
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmStrb:
      __ strb(i.InputRegister(0), i.InputOffset(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmLdrh:
      __ ldrh(i.OutputRegister(), i.InputOffset());
      break;
    case kArmLdrsh:
      __ ldrsh(i.OutputRegister(), i.InputOffset());
      break;
    case kArmStrh:
      __ strh(i.InputRegister(0), i.InputOffset(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmLdr:
      __ ldr(i.OutputRegister(), i.InputOffset());
      break;
    case kArmStr:
      __ str(i.InputRegister(0), i.InputOffset(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVldrF32: {
      __ vldr(i.OutputFloatRegister(), i.InputOffset());
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVstrF32:
      __ vstr(i.InputFloatRegister(0), i.InputOffset(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmVld1F64: {
      __ vld1(Neon8, NeonListOperand(i.OutputDoubleRegister()),
              i.NeonInputOperand(0));
      break;
    }
    case kArmVst1F64: {
      __ vst1(Neon8, NeonListOperand(i.InputDoubleRegister(0)),
              i.NeonInputOperand(1));
      break;
    }
    case kArmVld1S128: {
      __ vld1(Neon8, NeonListOperand(i.OutputSimd128Register()),
              i.NeonInputOperand(0));
      break;
    }
    case kArmVst1S128: {
      __ vst1(Neon8, NeonListOperand(i.InputSimd128Register(0)),
              i.NeonInputOperand(1));
      break;
    }
    case kArmVldrF64: {
      __ vldr(i.OutputDoubleRegister(), i.InputOffset());
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmVstrF64:
      __ vstr(i.InputDoubleRegister(0), i.InputOffset(1));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    case kArmFloat32Max: {
      SwVfpRegister result = i.OutputFloatRegister();
      SwVfpRegister left = i.InputFloatRegister(0);
      SwVfpRegister right = i.InputFloatRegister(1);
      if (left == right) {
        __ Move(result, left);
      } else {
        auto ool = zone()->New<OutOfLineFloat32Max>(this, result, left, right);
        __ FloatMax(result, left, right, ool->entry());
        __ bind(ool->exit());
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmFloat64Max: {
      DwVfpRegister result = i.OutputDoubleRegister();
      DwVfpRegister left = i.InputDoubleRegister(0);
      DwVfpRegister right = i.InputDoubleRegister(1);
      if (left == right) {
        __ Move(result, left);
      } else {
        auto ool = zone()->New<OutOfLineFloat64Max>(this, result, left, right);
        __ FloatMax(result, left, right, ool->entry());
        __ bind(ool->exit());
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmFloat32Min: {
      SwVfpRegister result = i.OutputFloatRegister();
      SwVfpRegister left = i.InputFloatRegister(0);
      SwVfpRegister right = i.InputFloatRegister(1);
      if (left == right) {
        __ Move(result, left);
      } else {
        auto ool = zone()->New<OutOfLineFloat32Min>(this, result, left, right);
        __ FloatMin(result, left, right, ool->entry());
        __ bind(ool->exit());
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmFloat64Min: {
      DwVfpRegister result = i.OutputDoubleRegister();
      DwVfpRegister left = i.InputDoubleRegister(0);
      DwVfpRegister right = i.InputDoubleRegister(1);
      if (left == right) {
        __ Move(result, left);
      } else {
        auto ool = zone()->New<OutOfLineFloat64Min>(this, result, left, right);
        __ FloatMin(result, left, right, ool->entry());
        __ bind(ool->exit());
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmFloat64SilenceNaN: {
      DwVfpRegister value = i.InputDoubleRegister(0);
      DwVfpRegister result = i.OutputDoubleRegister();
      __ VFPCanonicalizeNaN(result, value);
      break;
    }
    case kArmPush: {
      int stack_decrement = i.InputInt32(0);
      int slots = stack_decrement / kSystemPointerSize;
      LocationOperand* op = LocationOperand::cast(instr->InputAt(1));
      MachineRepresentation rep = op->representation();
      int pushed_slots = ElementSizeInPointers(rep);
      // Slot-sized arguments are never padded but there may be a gap if
      // the slot allocator reclaimed other padding slots. Adjust the stack
      // here to skip any gap.
      __ AllocateStackSpace((slots - pushed_slots) * kSystemPointerSize);
      switch (rep) {
        case MachineRepresentation::kFloat32:
          __ vpush(i.InputFloatRegister(1));
          break;
        case MachineRepresentation::kFloat64:
          __ vpush(i.InputDoubleRegister(1));
          break;
        case MachineRepresentation::kSimd128:
          __ vpush(i.InputSimd128Register(1));
          break;
        default:
          __ push(i.InputRegister(1));
          break;
      }
      frame_access_state()->IncreaseSPDelta(slots);
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmPoke: {
      int const slot = MiscField::decode(instr->opcode());
      __ str(i.InputRegister(0), MemOperand(sp, slot * kSystemPointerSize));
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmPeek: {
      int reverse_slot = i.InputInt32(0);
      int offset =
          FrameSlotToFPOffset(frame()->GetTotalFrameSlotCount() - reverse_slot);
      if (instr->OutputAt(0)->IsFPRegister()) {
        LocationOperand* op = LocationOperand::cast(instr->OutputAt(0));
        if (op->representation() == MachineRepresentation::kFloat64) {
          __ vldr(i.OutputDoubleRegister(), MemOperand(fp, offset));
        } else if (op->representation() == MachineRepresentation::kFloat32) {
          __ vldr(i.OutputFloatRegister(), MemOperand(fp, offset));
        } else {
          DCHECK_EQ(MachineRepresentation::kSimd128, op->representation());
          UseScratchRegisterScope temps(masm());
          Register scratch = temps.Acquire();
          __ add(scratch, fp, Operand(offset));
          __ vld1(Neon8, NeonListOperand(i.OutputSimd128Register()),
                  NeonMemOperand(scratch));
        }
      } else {
        __ ldr(i.OutputRegister(), MemOperand(fp, offset));
      }
      break;
    }
    case kArmDmbIsh: {
      __ dmb(ISH);
      break;
    }
    case kArmDsbIsb: {
      __ dsb(SY);
      __ isb(SY);
      break;
    }
    case kArmVmullLow: {
      auto dt = static_cast<NeonDataType>(MiscField::decode(instr->opcode()));
      __ vmull(dt, i.OutputSimd128Register(), i.InputSimd128Register(0).low(),
               i.InputSimd128Register(1).low());
      break;
    }
    case kArmVmullHigh: {
      auto dt = static_cast<NeonDataType>(MiscField::decode(instr->opcode()));
      __ vmull(dt, i.OutputSimd128Register(), i.InputSimd128Register(0).high(),
               i.InputSimd128Register(1).high());
      break;
    }
    case kArmVpadal: {
      DCHECK_EQ(i.OutputSimd128Register(), i.InputSimd128Register(0));
      auto dt = static_cast<NeonDataType>(MiscField::decode(instr->opcode()));
      __ vpadal(dt, i.OutputSimd128Register(), i.InputSimd128Register(1));
      break;
    }
    case kArmVpaddl: {
      auto dt = static_cast<NeonDataType>(MiscField::decode(instr->opcode()));
      __ vpaddl(dt, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmF64x2Splat: {
      Simd128Register dst = i.OutputSimd128Register();
      DoubleRegister src = i.InputDoubleRegister(0);
      __ Move(dst.low(), src);
      __ Move(dst.high(), src);
      break;
    }
    case kArmF64x2ExtractLane: {
      __ ExtractLane(i.OutputDoubleRegister(), i.InputSimd128Register(0),
                     i.InputInt8(1));
      break;
    }
    case kArmF64x2ReplaceLane: {
      __ ReplaceLane(i.OutputSimd128Register(), i.InputSimd128Register(0),
                     i.InputDoubleRegister(2), i.InputInt8(1));
      break;
    }
    case kArmF64x2Abs: {
      __ vabs(i.OutputSimd128Register().low(), i.InputSimd128Register(0).low());
      __ vabs(i.OutputSimd128Register().high(),
              i.InputSimd128Register(0).high());
      break;
    }
    case kArmF64x2Neg: {
      __ vneg(i.OutputSimd128Register().low(), i.InputSimd128Register(0).low());
      __ vneg(i.OutputSimd128Register().high(),
              i.InputSimd128Register(0).high());
      break;
    }
    case kArmF64x2Sqrt: {
      __ vsqrt(i.OutputSimd128Register().low(),
               i.InputSimd128Register(0).low());
      __ vsqrt(i.OutputSimd128Register().high(),
               i.InputSimd128Register(0).high());
      break;
    }
    case kArmF64x2Add: {
      ASSEMBLE_F64X2_ARITHMETIC_BINOP(vadd);
      break;
    }
    case kArmF64x2Sub: {
      ASSEMBLE_F64X2_ARITHMETIC_BINOP(vsub);
      break;
    }
    case kArmF64x2Mul: {
      ASSEMBLE_F64X2_ARITHMETIC_BINOP(vmul);
      break;
    }
    case kArmF64x2Div: {
      ASSEMBLE_F64X2_ARITHMETIC_BINOP(vdiv);
      break;
    }
    case kArmF64x2Min: {
      Simd128Register result = i.OutputSimd128Register();
      Simd128Register left = i.InputSimd128Register(0);
      Simd128Register right = i.InputSimd128Register(1);
      if (left == right) {
        __ Move(result, left);
      } else {
        auto ool_low = zone()->New<OutOfLineFloat64Min>(
            this, result.low(), left.low(), right.low());
        auto ool_high = zone()->New<OutOfLineFloat64Min>(
            this, result.high(), left.high(), right.high());
        __ FloatMin(result.low(), left.low(), right.low(), ool_low->entry());
        __ bind(ool_low->exit());
        __ FloatMin(result.high(), left.high(), right.high(),
                    ool_high->entry());
        __ bind(ool_high->exit());
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
    case kArmF64x2Max: {
      Simd128Register result = i.OutputSimd128Register();
      Simd128Register left = i.InputSimd128Register(0);
      Simd128Register right = i.InputSimd128Register(1);
      if (left == right) {
        __ Move(result, left);
      } else {
        auto ool_low = zone()->New<OutOfLineFloat64Max>(
            this, result.low(), left.low(), right.low());
        auto ool_high = zone()->New<OutOfLineFloat64Max>(
            this, result.high(), left.high(), right.high());
        __ FloatMax(result.low(), left.low(), right.low(), ool_low->entry());
        __ bind(ool_low->exit());
        __ FloatMax(result.high(), left.high(), right.high(),
                    ool_high->entry());
        __ bind(ool_high->exit());
      }
      DCHECK_EQ(LeaveCC, i.OutputSBit());
      break;
    }
#undef ASSEMBLE_F64X2_ARITHMETIC_BINOP
    case kArmF64x2Eq: {
      UseScratchRegisterScope temps(masm());
      Register scratch = temps.Acquire();
      __ mov(scratch, Operand(0));
      __ VFPCompareAndSetFlags(i.InputSimd128Register(0).low(),
                               i.InputSimd128Register(1).low());
      __ mov(scratch, Operand(-1), LeaveCC, eq);
      __ vmov(i.OutputSimd128Register().low(), scratch, scratch);
      __ mov(scratch, Operand(0));
      __ VFPCompareAndSetFlags(i.InputSimd128Register(0).high(),
                               i.InputSimd128Register(1).high());
      __ mov(scratch, Operand(-1), LeaveCC, eq);
      __ vmov(i.OutputSimd128Register().high(), scratch, scratch);
      break;
    }
    case kArmF64x2Ne: {
      UseScratchRegisterScope temps(masm());
      Register scratch = temps.Acquire();
      __ mov(scratch, Operand(0));
      __ VFPCompareAndSetFlags(i.InputSimd128Register(0).low(),
                               i.InputSimd128Register(1).low());
      __ mov(scratch, Operand(-1), LeaveCC, ne);
      __ vmov(i.OutputSimd128Register().low(), scratch, scratch);
      __ mov(scratch, Operand(0));
      __ VFPCompareAndSetFlags(i.InputSimd128Register(0).high(),
                               i.InputSimd128Register(1).high());
      __ mov(scratch, Operand(-1), LeaveCC, ne);
      __ vmov(i.OutputSimd128Register().high(), scratch, scratch);
      break;
    }
    case kArmF64x2Lt: {
      UseScratchRegisterScope temps(masm());
      Register scratch = temps.Acquire();
      __ VFPCompareAndSetFlags(i.InputSimd128Register(0).low(),
                               i.InputSimd128Register(1).low());
      __ mov(scratch, Operand(0), LeaveCC, cs);
      __ mov(scratch, Operand(-1), LeaveCC, mi);
      __ vmov(i.OutputSimd128Register().low(), scratch, scratch);
      __ VFPCompareAndSetFlags(i.InputSimd128Register(0).high(),
                               i.InputSimd128Register(1).high());
      __ mov(scratch, Operand(0), LeaveCC, cs);
      __ mov(scratch, Operand(-1), LeaveCC, mi);
      __ vmov(i.OutputSimd128Register().high(), scratch, scratch);
      break;
    }
    case kArmF64x2Le: {
      UseScratchRegisterScope temps(masm());
      Register scratch = temps.Acquire();
      __ VFPCompareAndSetFlags(i.InputSimd128Register(0).low(),
                               i.InputSimd128Register(1).low());
      __ mov(scratch, Operand(0), LeaveCC, hi);
      __ mov(scratch, Operand(-1), LeaveCC, ls);
      __ vmov(i.OutputSimd128Register().low(), scratch, scratch);
      __ VFPCompareAndSetFlags(i.InputSimd128Register(0).high(),
                               i.InputSimd128Register(1).high());
      __ mov(scratch, Operand(0), LeaveCC, hi);
      __ mov(scratch, Operand(-1), LeaveCC, ls);
      __ vmov(i.OutputSimd128Register().high(), scratch, scratch);
      break;
    }
    case kArmF64x2Pmin: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register lhs = i.InputSimd128Register(0);
      Simd128Register rhs = i.InputSimd128Register(1);
      DCHECK_EQ(dst, lhs);
      // Move rhs only when rhs is strictly lesser (mi).
      __ VFPCompareAndSetFlags(rhs.low(), lhs.low());
      __ vmov(dst.low(), rhs.low(), mi);
      __ VFPCompareAndSetFlags(rhs.high(), lhs.high());
      __ vmov(dst.high(), rhs.high(), mi);
      break;
    }
    case kArmF64x2Pmax: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register lhs = i.InputSimd128Register(0);
      Simd128Register rhs = i.InputSimd128Register(1);
      DCHECK_EQ(dst, lhs);
      // Move rhs only when rhs is strictly greater (gt).
      __ VFPCompareAndSetFlags(rhs.low(), lhs.low());
      __ vmov(dst.low(), rhs.low(), gt);
      __ VFPCompareAndSetFlags(rhs.high(), lhs.high());
      __ vmov(dst.high(), rhs.high(), gt);
      break;
    }
    case kArmF64x2Qfma: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src0 = i.InputSimd128Register(0);
      Simd128Register src1 = i.InputSimd128Register(1);
      Simd128Register src2 = i.InputSimd128Register(2);
      __ vmul(dst.low(), src0.low(), src1.low());
      __ vmul(dst.high(), src0.high(), src1.high());
      __ vadd(dst.low(), src2.low(), dst.low());
      __ vadd(dst.high(), src2.high(), dst.high());
      break;
    }
    case kArmF64x2Qfms: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src0 = i.InputSimd128Register(0);
      Simd128Register src1 = i.InputSimd128Register(1);
      Simd128Register src2 = i.InputSimd128Register(2);
      __ vmul(dst.low(), src0.low(), src1.low());
      __ vmul(dst.high(), src0.high(), src1.high());
      __ vsub(dst.low(), src2.low(), dst.low());
      __ vsub(dst.high(), src2.high(), dst.high());
      break;
    }
    case kArmF64x2Ceil: {
      CpuFeatureScope scope(masm(), ARMv8);
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src = i.InputSimd128Register(0);
      __ vrintp(dst.low(), src.low());
      __ vrintp(dst.high(), src.high());
      break;
    }
    case kArmF64x2Floor: {
      CpuFeatureScope scope(masm(), ARMv8);
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src = i.InputSimd128Register(0);
      __ vrintm(dst.low(), src.low());
      __ vrintm(dst.high(), src.high());
      break;
    }
    case kArmF64x2Trunc: {
      CpuFeatureScope scope(masm(), ARMv8);
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src = i.InputSimd128Register(0);
      __ vrintz(dst.low(), src.low());
      __ vrintz(dst.high(), src.high());
      break;
    }
    case kArmF64x2NearestInt: {
      CpuFeatureScope scope(masm(), ARMv8);
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src = i.InputSimd128Register(0);
      __ vrintn(dst.low(), src.low());
      __ vrintn(dst.high(), src.high());
      break;
    }
    case kArmF64x2ConvertLowI32x4S: {
      __ F64x2ConvertLowI32x4S(i.OutputSimd128Register(),
                               i.InputSimd128Register(0));
      break;
    }
    case kArmF64x2ConvertLowI32x4U: {
      __ F64x2ConvertLowI32x4U(i.OutputSimd128Register(),
                               i.InputSimd128Register(0));
      break;
    }
    case kArmF64x2PromoteLowF32x4: {
      __ F64x2PromoteLowF32x4(i.OutputSimd128Register(),
                              i.InputSimd128Register(0));
      break;
    }
    case kArmI64x2SplatI32Pair: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vdup(Neon32, dst, i.InputRegister(0));
      __ ReplaceLane(dst, dst, i.InputRegister(1), NeonS32, 1);
      __ ReplaceLane(dst, dst, i.InputRegister(1), NeonS32, 3);
      break;
    }
    case kArmI64x2ReplaceLaneI32Pair: {
      Simd128Register dst = i.OutputSimd128Register();
      int8_t lane = i.InputInt8(1);
      __ ReplaceLane(dst, dst, i.InputRegister(2), NeonS32, lane * 2);
      __ ReplaceLane(dst, dst, i.InputRegister(3), NeonS32, lane * 2 + 1);
      break;
    }
    case kArmI64x2Add: {
      __ vadd(Neon64, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI64x2Sub: {
      __ vsub(Neon64, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI64x2Mul: {
      UseScratchRegisterScope temps(masm());
      QwNeonRegister dst = i.OutputSimd128Register();
      QwNeonRegister left = i.InputSimd128Register(0);
      QwNeonRegister right = i.InputSimd128Register(1);
      QwNeonRegister tmp1 = i.TempSimd128Register(0);
      QwNeonRegister tmp2 = temps.AcquireQ();
      // This algorithm uses vector operations to perform 64-bit integer
      // multiplication by splitting it into a high and low 32-bit integers.
      // The tricky part is getting the low and high integers in the correct
      // place inside a NEON register, so that we can use as little vmull and
      // vmlal as possible.
      // Move left and right into temporaries, they will be modified by vtrn.
      __ vmov(tmp1, left);
      __ vmov(tmp2, right);
      // This diagram shows how the 64-bit integers fit into NEON registers.
      //
      // [q.high()| q.low()]
      // left/tmp1: [ a3, a2 | a1, a0 ]
      // right/tmp2: [ b3, b2 | b1, b0 ]
      //
      // We want to multiply the low 32 bits of left with high 32 bits of right,
      // for each lane, i.e. a2 * b3, a0 * b1. However, vmull takes two input d
      // registers, and multiply the corresponding low/high 32 bits, to get a
      // 64-bit integer: a1 * b1, a0 * b0. In order to make it work we transpose
      // the vectors, so that we get the low 32 bits of each 64-bit integer into
      // the same lane, similarly for high 32 bits.
      __ vtrn(Neon32, tmp1.low(), tmp1.high());
      // tmp1: [ a3, a1 | a2, a0 ]
      __ vtrn(Neon32, tmp2.low(), tmp2.high());
      // tmp2: [ b3, b1 | b2, b0 ]
      __ vmull(NeonU32, dst, tmp1.low(), tmp2.high());
      // dst: [ a2*b3 | a0*b1 ]
      __ vmlal(NeonU32, dst, tmp1.high(), tmp2.low());
      // dst: [ a2*b3 + a3*b2 | a0*b1 + a1*b0 ]
      __ vshl(NeonU64, dst, dst, 32);
      // dst: [ (a2*b3 + a3*b2) << 32 | (a0*b1 + a1*b0) << 32 ]
      __ vmlal(NeonU32, dst, tmp1.low(), tmp2.low());
      // dst: [ (a2*b3 + a3*b2)<<32 + (a2*b2) | (a0*b1 + a1*b0)<<32 + (a0*b0) ]
      break;
    }
    case kArmI64x2Abs: {
      __ I64x2Abs(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI64x2Neg: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vmov(dst, uint64_t{0});
      __ vsub(Neon64, dst, dst, i.InputSimd128Register(0));
      break;
    }
    case kArmI64x2Shl: {
      ASSEMBLE_SIMD_SHIFT_LEFT(vshl, 6, Neon32, NeonS64);
      break;
    }
    case kArmI64x2ShrS: {
      // Only the least significant byte of each lane is used, so we can use
      // Neon32 as the size.
      ASSEMBLE_SIMD_SHIFT_RIGHT(vshr, 6, Neon32, NeonS64);
      break;
    }
    case kArmI64x2ShrU: {
      // Only the least significant byte of each lane is used, so we can use
      // Neon32 as the size.
      ASSEMBLE_SIMD_SHIFT_RIGHT(vshr, 6, Neon32, NeonU64);
      break;
    }
    case kArmI64x2BitMask: {
      __ I64x2BitMask(i.OutputRegister(), i.InputSimd128Register(0));
      break;
    }
    case kArmI64x2SConvertI32x4Low: {
      __ vmovl(NeonS32, i.OutputSimd128Register(),
               i.InputSimd128Register(0).low());
      break;
    }
    case kArmI64x2SConvertI32x4High: {
      __ vmovl(NeonS32, i.OutputSimd128Register(),
               i.InputSimd128Register(0).high());
      break;
    }
    case kArmI64x2UConvertI32x4Low: {
      __ vmovl(NeonU32, i.OutputSimd128Register(),
               i.InputSimd128Register(0).low());
      break;
    }
    case kArmI64x2UConvertI32x4High: {
      __ vmovl(NeonU32, i.OutputSimd128Register(),
               i.InputSimd128Register(0).high());
      break;
    }
    case kArmF32x4Splat: {
      int src_code = i.InputFloatRegister(0).code();
      __ vdup(Neon32, i.OutputSimd128Register(),
              DwVfpRegister::from_code(src_code / 2), src_code % 2);
      break;
    }
    case kArmF32x4ExtractLane: {
      __ ExtractLane(i.OutputFloatRegister(), i.InputSimd128Register(0),
                     i.InputInt8(1));
      break;
    }
    case kArmF32x4ReplaceLane: {
      __ ReplaceLane(i.OutputSimd128Register(), i.InputSimd128Register(0),
                     i.InputFloatRegister(2), i.InputInt8(1));
      break;
    }
    case kArmF32x4SConvertI32x4: {
      __ vcvt_f32_s32(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmF32x4UConvertI32x4: {
      __ vcvt_f32_u32(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmF32x4Abs: {
      __ vabs(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmF32x4Neg: {
      __ vneg(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmF32x4Sqrt: {
      QwNeonRegister dst = i.OutputSimd128Register();
      QwNeonRegister src1 = i.InputSimd128Register(0);
      DCHECK_EQ(dst, q0);
      DCHECK_EQ(src1, q0);
#define S_FROM_Q(reg, lane) SwVfpRegister::from_code(reg.code() * 4 + lane)
      __ vsqrt(S_FROM_Q(dst, 0), S_FROM_Q(src1, 0));
      __ vsqrt(S_FROM_Q(dst, 1), S_FROM_Q(src1, 1));
      __ vsqrt(S_FROM_Q(dst, 2), S_FROM_Q(src1, 2));
      __ vsqrt(S_FROM_Q(dst, 3), S_FROM_Q(src1, 3));
#undef S_FROM_Q
      break;
    }
    case kArmF32x4Add: {
      __ vadd(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmF32x4Sub: {
      __ vsub(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmF32x4Mul: {
      __ vmul(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmF32x4Div: {
      QwNeonRegister dst = i.OutputSimd128Register();
      QwNeonRegister src1 = i.InputSimd128Register(0);
      QwNeonRegister src2 = i.InputSimd128Register(1);
      DCHECK_EQ(dst, q0);
      DCHECK_EQ(src1, q0);
      DCHECK_EQ(src2, q1);
#define S_FROM_Q(reg, lane) SwVfpRegister::from_code(reg.code() * 4 + lane)
      __ vdiv(S_FROM_Q(dst, 0), S_FROM_Q(src1, 0), S_FROM_Q(src2, 0));
      __ vdiv(S_FROM_Q(dst, 1), S_FROM_Q(src1, 1), S_FROM_Q(src2, 1));
      __ vdiv(S_FROM_Q(dst, 2), S_FROM_Q(src1, 2), S_FROM_Q(src2, 2));
      __ vdiv(S_FROM_Q(dst, 3), S_FROM_Q(src1, 3), S_FROM_Q(src2, 3));
#undef S_FROM_Q
      break;
    }
    case kArmF32x4Min: {
      __ vmin(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmF32x4Max: {
      __ vmax(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmF32x4Eq: {
      __ vceq(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmF32x4Ne: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vceq(dst, i.InputSimd128Register(0), i.InputSimd128Register(1));
      __ vmvn(dst, dst);
      break;
    }
    case kArmF32x4Lt: {
      __ vcgt(i.OutputSimd128Register(), i.InputSimd128Register(1),
              i.InputSimd128Register(0));
      break;
    }
    case kArmF32x4Le: {
      __ vcge(i.OutputSimd128Register(), i.InputSimd128Register(1),
              i.InputSimd128Register(0));
      break;
    }
    case kArmF32x4Pmin: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register lhs = i.InputSimd128Register(0);
      Simd128Register rhs = i.InputSimd128Register(1);
      DCHECK_NE(dst, lhs);
      DCHECK_NE(dst, rhs);
      // f32x4.pmin(lhs, rhs)
      // = v128.bitselect(rhs, lhs, f32x4.lt(rhs, lhs))
      // = v128.bitselect(rhs, lhs, f32x4.gt(lhs, rhs))
      __ vcgt(dst, lhs, rhs);
      __ vbsl(dst, rhs, lhs);
      break;
    }
    case kArmF32x4Pmax: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register lhs = i.InputSimd128Register(0);
      Simd128Register rhs = i.InputSimd128Register(1);
      DCHECK_NE(dst, lhs);
      DCHECK_NE(dst, rhs);
      // f32x4.pmax(lhs, rhs)
      // = v128.bitselect(rhs, lhs, f32x4.gt(rhs, lhs))
      __ vcgt(dst, rhs, lhs);
      __ vbsl(dst, rhs, lhs);
      break;
    }
    case kArmF32x4Qfma: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vmul(dst, i.InputSimd128Register(0), i.InputSimd128Register(1));
      __ vadd(dst, i.InputSimd128Register(2), dst);
      break;
    }
    case kArmF32x4Qfms: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vmul(dst, i.InputSimd128Register(0), i.InputSimd128Register(1));
      __ vsub(dst, i.InputSimd128Register(2), dst);
      break;
    }
    case kArmF32x4DemoteF64x2Zero: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src = i.InputSimd128Register(0);
      __ vcvt_f32_f64(SwVfpRegister::from_code(dst.code() * 4), src.low());
      __ vcvt_f32_f64(SwVfpRegister::from_code(dst.code() * 4 + 1), src.high());
      __ vmov(dst.high(), 0);
      break;
    }
    case kArmI32x4Splat: {
      __ vdup(Neon32, i.OutputSimd128Register(), i.InputRegister(0));
      break;
    }
    case kArmI32x4ExtractLane: {
      __ ExtractLane(i.OutputRegister(), i.InputSimd128Register(0), NeonS32,
                     i.InputInt8(1));
      break;
    }
    case kArmI32x4ReplaceLane: {
      __ ReplaceLane(i.OutputSimd128Register(), i.InputSimd128Register(0),
                     i.InputRegister(2), NeonS32, i.InputInt8(1));
      break;
    }
    case kArmI32x4SConvertF32x4: {
      __ vcvt_s32_f32(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI32x4SConvertI16x8Low: {
      __ vmovl(NeonS16, i.OutputSimd128Register(),
               i.InputSimd128Register(0).low());
      break;
    }
    case kArmI32x4SConvertI16x8High: {
      __ vmovl(NeonS16, i.OutputSimd128Register(),
               i.InputSimd128Register(0).high());
      break;
    }
    case kArmI32x4Neg: {
      __ vneg(Neon32, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI32x4Shl: {
      ASSEMBLE_SIMD_SHIFT_LEFT(vshl, 5, Neon32, NeonS32);
      break;
    }
    case kArmI32x4ShrS: {
      ASSEMBLE_SIMD_SHIFT_RIGHT(vshr, 5, Neon32, NeonS32);
      break;
    }
    case kArmI32x4Add: {
      __ vadd(Neon32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4Sub: {
      __ vsub(Neon32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4Mul: {
      __ vmul(Neon32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4MinS: {
      __ vmin(NeonS32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4MaxS: {
      __ vmax(NeonS32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI64x2Eq: {
      __ I64x2Eq(i.OutputSimd128Register(), i.InputSimd128Register(0),
                 i.InputSimd128Register(1));
      break;
    }
    case kArmI64x2Ne: {
      __ I64x2Ne(i.OutputSimd128Register(), i.InputSimd128Register(0),
                 i.InputSimd128Register(1));
      break;
    }
    case kArmI64x2GtS: {
      __ I64x2GtS(i.OutputSimd128Register(), i.InputSimd128Register(0),
                  i.InputSimd128Register(1));
      break;
    }
    case kArmI64x2GeS: {
      __ I64x2GeS(i.OutputSimd128Register(), i.InputSimd128Register(0),
                  i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4Eq: {
      __ vceq(Neon32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4Ne: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vceq(Neon32, dst, i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      __ vmvn(dst, dst);
      break;
    }
    case kArmI32x4GtS: {
      __ vcgt(NeonS32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4GeS: {
      __ vcge(NeonS32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4UConvertF32x4: {
      __ vcvt_u32_f32(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI32x4UConvertI16x8Low: {
      __ vmovl(NeonU16, i.OutputSimd128Register(),
               i.InputSimd128Register(0).low());
      break;
    }
    case kArmI32x4UConvertI16x8High: {
      __ vmovl(NeonU16, i.OutputSimd128Register(),
               i.InputSimd128Register(0).high());
      break;
    }
    case kArmI32x4ShrU: {
      ASSEMBLE_SIMD_SHIFT_RIGHT(vshr, 5, Neon32, NeonU32);
      break;
    }
    case kArmI32x4MinU: {
      __ vmin(NeonU32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4MaxU: {
      __ vmax(NeonU32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4GtU: {
      __ vcgt(NeonU32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4GeU: {
      __ vcge(NeonU32, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI32x4Abs: {
      __ vabs(Neon32, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI32x4BitMask: {
      Register dst = i.OutputRegister();
      UseScratchRegisterScope temps(masm());
      Simd128Register src = i.InputSimd128Register(0);
      Simd128Register tmp = temps.AcquireQ();
      Simd128Register mask = i.TempSimd128Register(0);
      __ vshr(NeonS32, tmp, src, 31);
      // Set i-th bit of each lane i. When AND with tmp, the lanes that
      // are signed will have i-th bit set, unsigned will be 0.
      __ vmov(mask.low(), base::Double(uint64_t{0x0000'0002'0000'0001}));
      __ vmov(mask.high(), base::Double(uint64_t{0x0000'0008'0000'0004}));
      __ vand(tmp, mask, tmp);
      __ vpadd(Neon32, tmp.low(), tmp.low(), tmp.high());
      __ vpadd(Neon32, tmp.low(), tmp.low(), kDoubleRegZero);
      __ VmovLow(dst, tmp.low());
      break;
    }
    case kArmI32x4DotI16x8S: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register lhs = i.InputSimd128Register(0);
      Simd128Register rhs = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      __ vmull(NeonS16, scratch, lhs.low(), rhs.low());
      __ vpadd(Neon32, dst.low(), scratch.low(), scratch.high());
      __ vmull(NeonS16, scratch, lhs.high(), rhs.high());
      __ vpadd(Neon32, dst.high(), scratch.low(), scratch.high());
      break;
    }
    case kArmI16x8DotI8x16S: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register lhs = i.InputSimd128Register(0);
      Simd128Register rhs = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      __ vmull(NeonS8, scratch, lhs.low(), rhs.low());
      __ vpadd(Neon16, dst.low(), scratch.low(), scratch.high());
      __ vmull(NeonS8, scratch, lhs.high(), rhs.high());
      __ vpadd(Neon16, dst.high(), scratch.low(), scratch.high());
      break;
    }
    case kArmI32x4DotI8x16AddS: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register lhs = i.InputSimd128Register(0);
      Simd128Register rhs = i.InputSimd128Register(1);
      Simd128Register tmp1 = i.TempSimd128Register(0);
      DCHECK_EQ(dst, i.InputSimd128Register(2));
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      __ vmull(NeonS8, scratch, lhs.low(), rhs.low());
      __ vpadd(Neon16, tmp1.low(), scratch.low(), scratch.high());
      __ vmull(NeonS8, scratch, lhs.high(), rhs.high());
      __ vpadd(Neon16, tmp1.high(), scratch.low(), scratch.high());
      __ vpadal(NeonS16, dst, tmp1);
      break;
    }
    case kArmI32x4TruncSatF64x2SZero: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src = i.InputSimd128Register(0);
      __ vcvt_s32_f64(SwVfpRegister::from_code(dst.code() * 4), src.low());
      __ vcvt_s32_f64(SwVfpRegister::from_code(dst.code() * 4 + 1), src.high());
      __ vmov(dst.high(), 0);
      break;
    }
    case kArmI32x4TruncSatF64x2UZero: {
      Simd128Register dst = i.OutputSimd128Register();
      Simd128Register src = i.InputSimd128Register(0);
      __ vcvt_u32_f64(SwVfpRegister::from_code(dst.code() * 4), src.low());
      __ vcvt_u32_f64(SwVfpRegister::from_code(dst.code() * 4 + 1), src.high());
      __ vmov(dst.high(), 0);
      break;
    }
    case kArmI16x8Splat: {
      __ vdup(Neon16, i.OutputSimd128Register(), i.InputRegister(0));
      break;
    }
    case kArmI16x8ExtractLaneU: {
      __ ExtractLane(i.OutputRegister(), i.InputSimd128Register(0), NeonU16,
                     i.InputInt8(1));
      break;
    }
    case kArmI16x8ExtractLaneS: {
      __ ExtractLane(i.OutputRegister(), i.InputSimd128Register(0), NeonS16,
                     i.InputInt8(1));
      break;
    }
    case kArmI16x8ReplaceLane: {
      __ ReplaceLane(i.OutputSimd128Register(), i.InputSimd128Register(0),
                     i.InputRegister(2), NeonS16, i.InputInt8(1));
      break;
    }
    case kArmI16x8SConvertI8x16Low: {
      __ vmovl(NeonS8, i.OutputSimd128Register(),
               i.InputSimd128Register(0).low());
      break;
    }
    case kArmI16x8SConvertI8x16High: {
      __ vmovl(NeonS8, i.OutputSimd128Register(),
               i.InputSimd128Register(0).high());
      break;
    }
    case kArmI16x8Neg: {
      __ vneg(Neon16, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI16x8Shl: {
      ASSEMBLE_SIMD_SHIFT_LEFT(vshl, 4, Neon16, NeonS16);
      break;
    }
    case kArmI16x8ShrS: {
      ASSEMBLE_SIMD_SHIFT_RIGHT(vshr, 4, Neon16, NeonS16);
      break;
    }
    case kArmI16x8SConvertI32x4:
      ASSEMBLE_NEON_NARROWING_OP(NeonS16, NeonS16);
      break;
    case kArmI16x8Add: {
      __ vadd(Neon16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8AddSatS: {
      __ vqadd(NeonS16, i.OutputSimd128Register(), i.InputSimd128Register(0),
               i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8Sub: {
      __ vsub(Neon16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8SubSatS: {
      __ vqsub(NeonS16, i.OutputSimd128Register(), i.InputSimd128Register(0),
               i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8Mul: {
      __ vmul(Neon16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8MinS: {
      __ vmin(NeonS16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8MaxS: {
      __ vmax(NeonS16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8Eq: {
      __ vceq(Neon16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8Ne: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vceq(Neon16, dst, i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      __ vmvn(dst, dst);
      break;
    }
    case kArmI16x8GtS: {
      __ vcgt(NeonS16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8GeS: {
      __ vcge(NeonS16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8UConvertI8x16Low: {
      __ vmovl(NeonU8, i.OutputSimd128Register(),
               i.InputSimd128Register(0).low());
      break;
    }
    case kArmI16x8UConvertI8x16High: {
      __ vmovl(NeonU8, i.OutputSimd128Register(),
               i.InputSimd128Register(0).high());
      break;
    }
    case kArmI16x8ShrU: {
      ASSEMBLE_SIMD_SHIFT_RIGHT(vshr, 4, Neon16, NeonU16);
      break;
    }
    case kArmI16x8UConvertI32x4:
      ASSEMBLE_NEON_NARROWING_OP(NeonU16, NeonS16);
      break;
    case kArmI16x8AddSatU: {
      __ vqadd(NeonU16, i.OutputSimd128Register(), i.InputSimd128Register(0),
               i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8SubSatU: {
      __ vqsub(NeonU16, i.OutputSimd128Register(), i.InputSimd128Register(0),
               i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8MinU: {
      __ vmin(NeonU16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8MaxU: {
      __ vmax(NeonU16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8GtU: {
      __ vcgt(NeonU16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8GeU: {
      __ vcge(NeonU16, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8RoundingAverageU: {
      __ vrhadd(NeonU16, i.OutputSimd128Register(), i.InputSimd128Register(0),
                i.InputSimd128Register(1));
      break;
    }
    case kArmI16x8Abs: {
      __ vabs(Neon16, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI16x8BitMask: {
      UseScratchRegisterScope temps(masm());
      Register dst = i.OutputRegister();
      Simd128Register src = i.InputSimd128Register(0);
      Simd128Register tmp = temps.AcquireQ();
      Simd128Register mask = i.TempSimd128Register(0);
      __ vshr(NeonS16, tmp, src, 15);
      // Set i-th bit of each lane i. When AND with tmp, the lanes that
      // are signed will have i-th bit set, unsigned will be 0.
      __ vmov(mask.low(), base::Double(uint64_t{0x0008'0004'0002'0001}));
      __ vmov(mask.high(), base::Double(uint64_t{0x0080'0040'0020'0010}));
      __ vand(tmp, mask, tmp);
      __ vpadd(Neon16, tmp.low(), tmp.low(), tmp.high());
      __ vpadd(Neon16, tmp.low(), tmp.low(), tmp.low());
      __ vpadd(Neon16, tmp.low(), tmp.low(), tmp.low());
      __ vmov(NeonU16, dst, tmp.low(), 0);
      break;
    }
    case kArmI16x8Q15MulRSatS: {
      __ vqrdmulh(NeonS16, i.OutputSimd128Register(), i.InputSimd128Register(0),
                  i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16Splat: {
      __ vdup(Neon8, i.OutputSimd128Register(), i.InputRegister(0));
      break;
    }
    case kArmI8x16ExtractLaneU: {
      __ ExtractLane(i.OutputRegister(), i.InputSimd128Register(0), NeonU8,
                     i.InputInt8(1));
      break;
    }
    case kArmI8x16ExtractLaneS: {
      __ ExtractLane(i.OutputRegister(), i.InputSimd128Register(0), NeonS8,
                     i.InputInt8(1));
      break;
    }
    case kArmI8x16ReplaceLane: {
      __ ReplaceLane(i.OutputSimd128Register(), i.InputSimd128Register(0),
                     i.InputRegister(2), NeonS8, i.InputInt8(1));
      break;
    }
    case kArmI8x16Neg: {
      __ vneg(Neon8, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI8x16Shl: {
      ASSEMBLE_SIMD_SHIFT_LEFT(vshl, 3, Neon8, NeonS8);
      break;
    }
    case kArmI8x16ShrS: {
      ASSEMBLE_SIMD_SHIFT_RIGHT(vshr, 3, Neon8, NeonS8);
      break;
    }
    case kArmI8x16SConvertI16x8:
      ASSEMBLE_NEON_NARROWING_OP(NeonS8, NeonS8);
      break;
    case kArmI8x16Add: {
      __ vadd(Neon8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16AddSatS: {
      __ vqadd(NeonS8, i.OutputSimd128Register(), i.InputSimd128Register(0),
               i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16Sub: {
      __ vsub(Neon8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16SubSatS: {
      __ vqsub(NeonS8, i.OutputSimd128Register(), i.InputSimd128Register(0),
               i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16MinS: {
      __ vmin(NeonS8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16MaxS: {
      __ vmax(NeonS8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16Eq: {
      __ vceq(Neon8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16Ne: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vceq(Neon8, dst, i.InputSimd128Register(0), i.InputSimd128Register(1));
      __ vmvn(dst, dst);
      break;
    }
    case kArmI8x16GtS: {
      __ vcgt(NeonS8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16GeS: {
      __ vcge(NeonS8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16ShrU: {
      ASSEMBLE_SIMD_SHIFT_RIGHT(vshr, 3, Neon8, NeonU8);
      break;
    }
    case kArmI8x16UConvertI16x8:
      ASSEMBLE_NEON_NARROWING_OP(NeonU8, NeonS8);
      break;
    case kArmI8x16AddSatU: {
      __ vqadd(NeonU8, i.OutputSimd128Register(), i.InputSimd128Register(0),
               i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16SubSatU: {
      __ vqsub(NeonU8, i.OutputSimd128Register(), i.InputSimd128Register(0),
               i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16MinU: {
      __ vmin(NeonU8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16MaxU: {
      __ vmax(NeonU8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16GtU: {
      __ vcgt(NeonU8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16GeU: {
      __ vcge(NeonU8, i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16RoundingAverageU: {
      __ vrhadd(NeonU8, i.OutputSimd128Register(), i.InputSimd128Register(0),
                i.InputSimd128Register(1));
      break;
    }
    case kArmI8x16Abs: {
      __ vabs(Neon8, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmI8x16BitMask: {
      UseScratchRegisterScope temps(masm());
      Register dst = i.OutputRegister();
      Simd128Register src = i.InputSimd128Register(0);
      Simd128Register tmp = temps.AcquireQ();
      Simd128Register mask = i.TempSimd128Register(0);
      __ vshr(NeonS8, tmp, src, 7);
      // Set i-th bit of each lane i. When AND with tmp, the lanes that
      // are signed will have i-th bit set, unsigned will be 0.
      __ vmov(mask.low(), base::Double(uint64_t{0x8040'2010'0804'0201}));
      __ vmov(mask.high(), base::Double(uint64_t{0x8040'2010'0804'0201}));
      __ vand(tmp, mask, tmp);
      __ vext(mask, tmp, tmp, 8);
      __ vzip(Neon8, mask, tmp);
      __ vpadd(Neon16, tmp.low(), tmp.low(), tmp.high());
      __ vpadd(Neon16, tmp.low(), tmp.low(), tmp.low());
      __ vpadd(Neon16, tmp.low(), tmp.low(), tmp.low());
      __ vmov(NeonU16, dst, tmp.low(), 0);
      break;
    }
    case kArmS128Const: {
      QwNeonRegister dst = i.OutputSimd128Register();
      uint64_t imm1 = make_uint64(i.InputUint32(1), i.InputUint32(0));
      uint64_t imm2 = make_uint64(i.InputUint32(3), i.InputUint32(2));
      __ vmov(dst.low(), base::Double(imm1));
      __ vmov(dst.high(), base::Double(imm2));
      break;
    }
    case kArmS128Zero: {
      __ veor(i.OutputSimd128Register(), i.OutputSimd128Register(),
              i.OutputSimd128Register());
      break;
    }
    case kArmS128AllOnes: {
      __ vmov(i.OutputSimd128Register(), uint64_t{0xffff'ffff'ffff'ffff});
      break;
    }
    case kArmS128Dup: {
      NeonSize size = static_cast<NeonSize>(i.InputInt32(1));
      int lanes = kSimd128Size >> size;
      int index = i.InputInt32(2);
      DCHECK(index < lanes);
      int d_lanes = lanes / 2;
      int src_d_index = index & (d_lanes - 1);
      int src_d_code = i.InputSimd128Register(0).low().code() + index / d_lanes;
      __ vdup(size, i.OutputSimd128Register(),
              DwVfpRegister::from_code(src_d_code), src_d_index);
      break;
    }
    case kArmS128And: {
      __ vand(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmS128Or: {
      __ vorr(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmS128Xor: {
      __ veor(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmS128Not: {
      __ vmvn(i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmS128Select: {
      Simd128Register dst = i.OutputSimd128Register();
      DCHECK(dst == i.InputSimd128Register(0));
      __ vbsl(dst, i.InputSimd128Register(1), i.InputSimd128Register(2));
      break;
    }
    case kArmS128AndNot: {
      __ vbic(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1));
      break;
    }
    case kArmS32x4ZipLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [0, 1, 2, 3], src1 = [4, 5, 6, 7]
      __ vmov(dst.high(), src1.low()); // dst = [0, 1, 4, 5]
      __ vtrn(Neon32, dst.low(), dst.high()); // dst = [0, 4, 1, 5]
      break;
    }
    case kArmS32x4ZipRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [4, 5, 6, 7], src1 = [0, 1, 2, 3] (flipped from ZipLeft).
      __ vmov(dst.low(), src1.high()); // dst = [2, 3, 6, 7]
      __ vtrn(Neon32, dst.low(), dst.high()); // dst = [2, 6, 3, 7]
      break;
    }
    case kArmS32x4UnzipLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      DCHECK(dst == i.InputSimd128Register(0));
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      // src0 = [0, 1, 2, 3], src1 = [4, 5, 6, 7]
      __ vmov(scratch, src1);
      __ vuzp(Neon32, dst, scratch); // dst = [0, 2, 4, 6]
      break;
    }
    case kArmS32x4UnzipRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      DCHECK(dst == i.InputSimd128Register(0));
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      // src0 = [4, 5, 6, 7], src1 = [0, 1, 2, 3] (flipped from UnzipLeft).
      __ vmov(scratch, src1);
      __ vuzp(Neon32, scratch, dst); // dst = [1, 3, 5, 7]
      break;
    }
    case kArmS32x4TransposeLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      DCHECK(dst == i.InputSimd128Register(0));
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      // src0 = [0, 1, 2, 3], src1 = [4, 5, 6, 7]
      __ vmov(scratch, src1);
      __ vtrn(Neon32, dst, scratch); // dst = [0, 4, 2, 6]
      break;
    }
    case kArmS32x4Shuffle: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src0 = i.InputSimd128Register(0),
                      src1 = i.InputSimd128Register(1);
      DCHECK_NE(dst, src0);
      DCHECK_NE(dst, src1);
      // Perform shuffle as a vmov per lane.
      int dst_code = dst.code() * 4;
      int src0_code = src0.code() * 4;
      int src1_code = src1.code() * 4;
      int32_t shuffle = i.InputInt32(2);
      for (int i = 0; i < 4; i++) {
        int lane = shuffle & 0x7;
        int src_code = src0_code;
        if (lane >= 4) {
          src_code = src1_code;
          lane &= 0x3;
        }
        __ VmovExtended(dst_code + i, src_code + lane);
        shuffle >>= 8;
      }
      break;
    }
    case kArmS32x4TransposeRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [4, 5, 6, 7], src1 = [0, 1, 2, 3] (flipped from TransposeLeft).
      __ vmov(scratch, src1);
      __ vtrn(Neon32, scratch, dst); // dst = [1, 5, 3, 7]
      break;
    }
    case kArmS16x8ZipLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      // src0 = [0, 1, 2, 3, ... 7], src1 = [8, 9, 10, 11, ... 15]
      DCHECK(dst == i.InputSimd128Register(0));
      __ vmov(dst.high(), src1.low()); // dst = [0, 1, 2, 3, 8, ... 11]
      __ vzip(Neon16, dst.low(), dst.high()); // dst = [0, 8, 1, 9, ... 11]
      break;
    }
    case kArmS16x8ZipRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [8, 9, 10, 11, ... 15], src1 = [0, 1, 2, 3, ... 7] (flipped).
      __ vmov(dst.low(), src1.high());
      __ vzip(Neon16, dst.low(), dst.high()); // dst = [4, 12, 5, 13, ... 15]
      break;
    }
    case kArmS16x8UnzipLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [0, 1, 2, 3, ... 7], src1 = [8, 9, 10, 11, ... 15]
      __ vmov(scratch, src1);
      __ vuzp(Neon16, dst, scratch); // dst = [0, 2, 4, 6, ... 14]
      break;
    }
    case kArmS16x8UnzipRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [8, 9, 10, 11, ... 15], src1 = [0, 1, 2, 3, ... 7] (flipped).
      __ vmov(scratch, src1);
      __ vuzp(Neon16, scratch, dst); // dst = [1, 3, 5, 7, ... 15]
      break;
    }
    case kArmS16x8TransposeLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [0, 1, 2, 3, ... 7], src1 = [8, 9, 10, 11, ... 15]
      __ vmov(scratch, src1);
      __ vtrn(Neon16, dst, scratch); // dst = [0, 8, 2, 10, ... 14]
      break;
    }
    case kArmS16x8TransposeRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [8, 9, 10, 11, ... 15], src1 = [0, 1, 2, 3, ... 7] (flipped).
      __ vmov(scratch, src1);
      __ vtrn(Neon16, scratch, dst); // dst = [1, 9, 3, 11, ... 15]
      break;
    }
    case kArmS8x16ZipLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [0, 1, 2, 3, ... 15], src1 = [16, 17, 18, 19, ... 31]
      __ vmov(dst.high(), src1.low());
      __ vzip(Neon8, dst.low(), dst.high()); // dst = [0, 16, 1, 17, ... 23]
      break;
    }
    case kArmS8x16ZipRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [16, 17, 18, 19, ... 31], src1 = [0, 1, 2, 3, ... 15] (flipped).
      __ vmov(dst.low(), src1.high());
      __ vzip(Neon8, dst.low(), dst.high()); // dst = [8, 24, 9, 25, ... 31]
      break;
    }
    case kArmS8x16UnzipLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [0, 1, 2, 3, ... 15], src1 = [16, 17, 18, 19, ... 31]
      __ vmov(scratch, src1);
      __ vuzp(Neon8, dst, scratch); // dst = [0, 2, 4, 6, ... 30]
      break;
    }
    case kArmS8x16UnzipRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [16, 17, 18, 19, ... 31], src1 = [0, 1, 2, 3, ... 15] (flipped).
      __ vmov(scratch, src1);
      __ vuzp(Neon8, scratch, dst); // dst = [1, 3, 5, 7, ... 31]
      break;
    }
    case kArmS8x16TransposeLeft: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [0, 1, 2, 3, ... 15], src1 = [16, 17, 18, 19, ... 31]
      __ vmov(scratch, src1);
      __ vtrn(Neon8, dst, scratch); // dst = [0, 16, 2, 18, ... 30]
      break;
    }
    case kArmS8x16TransposeRight: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src1 = i.InputSimd128Register(1);
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      DCHECK(dst == i.InputSimd128Register(0));
      // src0 = [16, 17, 18, 19, ... 31], src1 = [0, 1, 2, 3, ... 15] (flipped).
      __ vmov(scratch, src1);
      __ vtrn(Neon8, scratch, dst); // dst = [1, 17, 3, 19, ... 31]
      break;
    }
    case kArmS8x16Concat: {
      __ vext(i.OutputSimd128Register(), i.InputSimd128Register(0),
              i.InputSimd128Register(1), i.InputInt4(2));
      break;
    }
    case kArmI8x16Swizzle: {
      Simd128Register dst = i.OutputSimd128Register(),
                      tbl = i.InputSimd128Register(0),
                      src = i.InputSimd128Register(1);
      NeonListOperand table(tbl);
      __ vtbl(dst.low(), table, src.low());
      __ vtbl(dst.high(), table, src.high());
      break;
    }
    case kArmI8x16Shuffle: {
      Simd128Register dst = i.OutputSimd128Register(),
                      src0 = i.InputSimd128Register(0),
                      src1 = i.InputSimd128Register(1);
      DwVfpRegister table_base = src0.low();
      UseScratchRegisterScope temps(masm());
      Simd128Register scratch = temps.AcquireQ();
      // If unary shuffle, table is src0 (2 d-registers), otherwise src0 and
      // src1. They must be consecutive.
      int table_size = src0 == src1 ? 2 : 4;
      DCHECK_IMPLIES(src0 != src1, src0.code() + 1 == src1.code());
      // The shuffle lane mask is a byte mask, materialize in scratch.
      int scratch_s_base = scratch.code() * 4;
      for (int j = 0; j < 4; j++) {
        uint32_t four_lanes = i.InputUint32(2 + j);
        DCHECK_EQ(0, four_lanes & (table_size == 2 ? 0xF0F0F0F0 : 0xE0E0E0E0));
        __ vmov(SwVfpRegister::from_code(scratch_s_base + j),
                Float32::FromBits(four_lanes));
      }
      NeonListOperand table(table_base, table_size);
      if (dst != src0 && dst != src1) {
        __ vtbl(dst.low(), table, scratch.low());
        __ vtbl(dst.high(), table, scratch.high());
      } else {
        __ vtbl(scratch.low(), table, scratch.low());
        __ vtbl(scratch.high(), table, scratch.high());
        __ vmov(dst, scratch);
      }
      break;
    }
    case kArmS32x2Reverse: {
      __ vrev64(Neon32, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmS16x4Reverse: {
      __ vrev64(Neon16, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmS16x2Reverse: {
      __ vrev32(Neon16, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmS8x8Reverse: {
      __ vrev64(Neon8, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmS8x4Reverse: {
      __ vrev32(Neon8, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmS8x2Reverse: {
      __ vrev16(Neon8, i.OutputSimd128Register(), i.InputSimd128Register(0));
      break;
    }
    case kArmV128AnyTrue: {
      const QwNeonRegister& src = i.InputSimd128Register(0);
      UseScratchRegisterScope temps(masm());
      DwVfpRegister scratch = temps.AcquireD();
      __ vpmax(NeonU32, scratch, src.low(), src.high());
      __ vpmax(NeonU32, scratch, scratch, scratch);
      __ ExtractLane(i.OutputRegister(), scratch, NeonS32, 0);
      __ cmp(i.OutputRegister(), Operand(0));
      __ mov(i.OutputRegister(), Operand(1), LeaveCC, ne);
      break;
    }
    case kArmI64x2AllTrue: {
      __ I64x2AllTrue(i.OutputRegister(), i.InputSimd128Register(0));
      break;
    }
    case kArmI32x4AllTrue: {
      const QwNeonRegister& src = i.InputSimd128Register(0);
      UseScratchRegisterScope temps(masm());
      DwVfpRegister scratch = temps.AcquireD();
      __ vpmin(NeonU32, scratch, src.low(), src.high());
      __ vpmin(NeonU32, scratch, scratch, scratch);
      __ ExtractLane(i.OutputRegister(), scratch, NeonS32, 0);
      __ cmp(i.OutputRegister(), Operand(0));
      __ mov(i.OutputRegister(), Operand(1), LeaveCC, ne);
      break;
    }
    case kArmI16x8AllTrue: {
      const QwNeonRegister& src = i.InputSimd128Register(0);
      UseScratchRegisterScope temps(masm());
      DwVfpRegister scratch = temps.AcquireD();
      __ vpmin(NeonU16, scratch, src.low(), src.high());
      __ vpmin(NeonU16, scratch, scratch, scratch);
      __ vpmin(NeonU16, scratch, scratch, scratch);
      __ ExtractLane(i.OutputRegister(), scratch, NeonS16, 0);
      __ cmp(i.OutputRegister(), Operand(0));
      __ mov(i.OutputRegister(), Operand(1), LeaveCC, ne);
      break;
    }
    case kArmI8x16AllTrue: {
      const QwNeonRegister& src = i.InputSimd128Register(0);
      UseScratchRegisterScope temps(masm());
      DwVfpRegister scratch = temps.AcquireD();
      __ vpmin(NeonU8, scratch, src.low(), src.high());
      __ vpmin(NeonU8, scratch, scratch, scratch);
      __ vpmin(NeonU8, scratch, scratch, scratch);
      __ vpmin(NeonU8, scratch, scratch, scratch);
      __ ExtractLane(i.OutputRegister(), scratch, NeonS8, 0);
      __ cmp(i.OutputRegister(), Operand(0));
      __ mov(i.OutputRegister(), Operand(1), LeaveCC, ne);
      break;
    }
    case kArmS128Load8Splat: {
      __ vld1r(Neon8, NeonListOperand(i.OutputSimd128Register()),
               i.NeonInputOperand(0));
      break;
    }
    case kArmS128Load16Splat: {
      __ vld1r(Neon16, NeonListOperand(i.OutputSimd128Register()),
               i.NeonInputOperand(0));
      break;
    }
    case kArmS128Load32Splat: {
      __ vld1r(Neon32, NeonListOperand(i.OutputSimd128Register()),
               i.NeonInputOperand(0));
      break;
    }
    case kArmS128Load64Splat: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vld1(Neon32, NeonListOperand(dst.low()), i.NeonInputOperand(0));
      __ Move(dst.high(), dst.low());
      break;
    }
    case kArmS128Load8x8S: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vld1(Neon8, NeonListOperand(dst.low()), i.NeonInputOperand(0));
      __ vmovl(NeonS8, dst, dst.low());
      break;
    }
    case kArmS128Load8x8U: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vld1(Neon8, NeonListOperand(dst.low()), i.NeonInputOperand(0));
      __ vmovl(NeonU8, dst, dst.low());
      break;
    }
    case kArmS128Load16x4S: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vld1(Neon16, NeonListOperand(dst.low()), i.NeonInputOperand(0));
      __ vmovl(NeonS16, dst, dst.low());
      break;
    }
    case kArmS128Load16x4U: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vld1(Neon16, NeonListOperand(dst.low()), i.NeonInputOperand(0));
      __ vmovl(NeonU16, dst, dst.low());
      break;
    }
    case kArmS128Load32x2S: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vld1(Neon32, NeonListOperand(dst.low()), i.NeonInputOperand(0));
      __ vmovl(NeonS32, dst, dst.low());
      break;
    }
    case kArmS128Load32x2U: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vld1(Neon32, NeonListOperand(dst.low()), i.NeonInputOperand(0));
      __ vmovl(NeonU32, dst, dst.low());
      break;
    }
    case kArmS128Load32Zero: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vmov(dst, 0);
      __ vld1s(Neon32, NeonListOperand(dst.low()), 0, i.NeonInputOperand(0));
      break;
    }
    case kArmS128Load64Zero: {
      Simd128Register dst = i.OutputSimd128Register();
      __ vmov(dst.high(), 0);
      __ vld1(Neon64, NeonListOperand(dst.low()), i.NeonInputOperand(0));
      break;
    }
    case kArmS128LoadLaneLow: {
      Simd128Register dst = i.OutputSimd128Register();
      DCHECK_EQ(dst, i.InputSimd128Register(0));
      auto sz = static_cast<NeonSize>(MiscField::decode(instr->opcode()));
      NeonListOperand dst_list = NeonListOperand(dst.low());
      __ LoadLane(sz, dst_list, i.InputUint8(1), i.NeonInputOperand(2));
      break;
    }
    case kArmS128LoadLaneHigh: {
      Simd128Register dst = i.OutputSimd128Register();
      DCHECK_EQ(dst, i.InputSimd128Register(0));
      auto sz = static_cast<NeonSize>(MiscField::decode(instr->opcode()));
      NeonListOperand dst_list = NeonListOperand(dst.high());
      __ LoadLane(sz, dst_list, i.InputUint8(1), i.NeonInputOperand(2));
      break;
    }
    case kArmS128StoreLaneLow: {
      Simd128Register src = i.InputSimd128Register(0);
      NeonListOperand src_list = NeonListOperand(src.low());
      auto sz = static_cast<NeonSize>(MiscField::decode(instr->opcode()));
      __ StoreLane(sz, src_list, i.InputUint8(1), i.NeonInputOperand(2));
      break;
    }
    case kArmS128StoreLaneHigh: {
      Simd128Register src = i.InputSimd128Register(0);
      NeonListOperand src_list = NeonListOperand(src.high());
      auto sz = static_cast<NeonSize>(MiscField::decode(instr->opcode()));
      __ StoreLane(sz, src_list, i.InputUint8(1), i.NeonInputOperand(2));
      break;
    }
    case kAtomicLoadInt8:
      ASSEMBLE_ATOMIC_LOAD_INTEGER(ldrsb);
      break;
    case kAtomicLoadUint8:
      ASSEMBLE_ATOMIC_LOAD_INTEGER(ldrb);
      break;
    case kAtomicLoadInt16:
      ASSEMBLE_ATOMIC_LOAD_INTEGER(ldrsh);
      break;
    case kAtomicLoadUint16:
      ASSEMBLE_ATOMIC_LOAD_INTEGER(ldrh);
      break;
    case kAtomicLoadWord32:
      ASSEMBLE_ATOMIC_LOAD_INTEGER(ldr);
      break;
    case kAtomicStoreWord8:
      ASSEMBLE_ATOMIC_STORE_INTEGER(strb,
                                    AtomicMemoryOrderField::decode(opcode));
      break;
    case kAtomicStoreWord16:
      ASSEMBLE_ATOMIC_STORE_INTEGER(strh,
                                    AtomicMemoryOrderField::decode(opcode));
      break;
    case kAtomicStoreWord32:
      ASSEMBLE_ATOMIC_STORE_INTEGER(str,
                                    AtomicMemoryOrderField::decode(opcode));
      break;
    case kAtomicExchangeInt8:
      ASSEMBLE_ATOMIC_EXCHANGE_INTEGER(ldrexb, strexb);
      __ sxtb(i.OutputRegister(0), i.OutputRegister(0));
      break;
    case kAtomicExchangeUint8:
      ASSEMBLE_ATOMIC_EXCHANGE_INTEGER(ldrexb, strexb);
      break;
    case kAtomicExchangeInt16:
      ASSEMBLE_ATOMIC_EXCHANGE_INTEGER(ldrexh, strexh);
      __ sxth(i.OutputRegister(0), i.OutputRegister(0));
      break;
    case kAtomicExchangeUint16:
      ASSEMBLE_ATOMIC_EXCHANGE_INTEGER(ldrexh, strexh);
      break;
    case kAtomicExchangeWord32:
      ASSEMBLE_ATOMIC_EXCHANGE_INTEGER(ldrex, strex);
      break;
    case kAtomicExchangeWithWriteBarrier: {
      ASSEMBLE_ATOMIC_EXCHANGE_INTEGER(ldrex, strex);
      Register object = i.InputRegister(0);
      Register offset = i.InputRegister(1);
      Register value = i.InputRegister(2);
      RecordWriteMode mode = RecordWriteMode::kValueIsAny;
      auto ool = zone()->New<OutOfLineRecordWrite>(
          this, object, Operand(offset), value, mode, DetermineStubCallMode(),
          &unwinding_info_writer_);
      __ JumpIfSmi(value, ool->exit());
      __ CheckPageFlag(object, MemoryChunk::kPointersFromHereAreInterestingMask,
                       ne, ool->entry());
      __ bind(ool->exit());
      break;
    }
    case kAtomicCompareExchangeInt8:
      __ add(i.TempRegister(1), i.InputRegister(0), i.InputRegister(1));
      __ uxtb(i.TempRegister(2), i.InputRegister(2));
      ASSEMBLE_ATOMIC_COMPARE_EXCHANGE_INTEGER(ldrexb, strexb,
                                               i.TempRegister(2));
      __ sxtb(i.OutputRegister(0), i.OutputRegister(0));
      break;
    case kAtomicCompareExchangeUint8:
      __ add(i.TempRegister(1), i.InputRegister(0), i.InputRegister(1));
      __ uxtb(i.TempRegister(2), i.InputRegister(2));
      ASSEMBLE_ATOMIC_COMPARE_EXCHANGE_INTEGER(ldrexb, strexb,
                                               i.TempRegister(2));
      break;
    case kAtomicCompareExchangeInt16:
      __ add(i.TempRegister(1), i.InputRegister(0), i.InputRegister(1));
      __ uxth(i.TempRegister(2), i.InputRegister(2));
      ASSEMBLE_ATOMIC_COMPARE_EXCHANGE_INTEGER(ldrexh, strexh,
                                               i.TempRegister(2));
      __ sxth(i.OutputRegister(0), i.OutputRegister(0));
      break;
    case kAtomicCompareExchangeUint16:
      __ add(i.TempRegister(1), i.InputRegister(0), i.InputRegister(1));
      __ uxth(i.TempRegister(2), i.InputRegister(2));
      ASSEMBLE_ATOMIC_COMPARE_EXCHANGE_INTEGER(ldrexh, strexh,
                                               i.TempRegister(2));
      break;
    case kAtomicCompareExchangeWord32:
      __ add(i.TempRegister(1), i.InputRegister(0), i.InputRegister(1));
      ASSEMBLE_ATOMIC_COMPARE_EXCHANGE_INTEGER(ldrex, strex,
                                               i.InputRegister(2));
      break;
#define ATOMIC_BINOP_CASE(op, inst) \
  case kAtomic##op##Int8: \
    ASSEMBLE_ATOMIC_BINOP(ldrexb, strexb, inst); \
    __ sxtb(i.OutputRegister(0), i.OutputRegister(0)); \
    break; \
  case kAtomic##op##Uint8: \
    ASSEMBLE_ATOMIC_BINOP(ldrexb, strexb, inst); \
    break; \
  case kAtomic##op##Int16: \
    ASSEMBLE_ATOMIC_BINOP(ldrexh, strexh, inst); \
    __ sxth(i.OutputRegister(0), i.OutputRegister(0)); \
    break; \
  case kAtomic##op##Uint16: \
    ASSEMBLE_ATOMIC_BINOP(ldrexh, strexh, inst); \
    break; \
  case kAtomic##op##Word32: \
    ASSEMBLE_ATOMIC_BINOP(ldrex, strex, inst); \
    break;
      ATOMIC_BINOP_CASE(Add, add)
      ATOMIC_BINOP_CASE(Sub, sub)
      ATOMIC_BINOP_CASE(And, and_)
      ATOMIC_BINOP_CASE(Or, orr)
      ATOMIC_BINOP_CASE(Xor, eor)
#undef ATOMIC_BINOP_CASE
    case kArmWord32AtomicPairLoad: {
      if (instr->OutputCount() == 2) {
        DCHECK(VerifyOutputOfAtomicPairInstr(&i, instr, r0, r1));
        __ add(i.TempRegister(0), i.InputRegister(0), i.InputRegister(1));
        __ ldrexd(r0, r1, i.TempRegister(0));
        __ dmb(ISH);
      } else {
        // A special case of this instruction: even though this is a pair load,
        // we only need one of the two words. We emit a normal atomic load.
        DCHECK_EQ(instr->OutputCount(), 1);
        Register base = i.InputRegister(0);
        Register offset = i.InputRegister(1);
        DCHECK(instr->InputAt(2)->IsImmediate());
        int32_t offset_imm = i.InputInt32(2);
        if (offset_imm != 0) {
          Register temp = i.TempRegister(0);
          __ add(temp, offset, Operand(offset_imm));
          offset = temp;
        }
        __ ldr(i.OutputRegister(), MemOperand(base, offset));
        __ dmb(ISH);
      }
      break;
    }
    case kArmWord32AtomicPairStore: {
      Label store;
      Register base = i.InputRegister(0);
      Register offset = i.InputRegister(1);
      Register value_low = i.InputRegister(2);
      Register value_high = i.InputRegister(3);
      Register actual_addr = i.TempRegister(0);
      // The {ldrexd} instruction needs two temp registers. We do not need the
      // result of {ldrexd}, but {strexd} likely fails without the {ldrexd}.
      Register tmp1 = i.TempRegister(1);
      Register tmp2 = i.TempRegister(2);
      // Reuse one of the temp registers for the result of {strexd}.
      Register store_result = tmp1;
      __ add(actual_addr, base, offset);
      __ dmb(ISH);
      __ bind(&store);
      // Add this {ldrexd} instruction here so that {strexd} below can succeed.
      // We don't need the result of {ldrexd} itself.
      __ ldrexd(tmp1, tmp2, actual_addr);
      __ strexd(store_result, value_low, value_high, actual_addr);
      __ cmp(store_result, Operand(0));
      __ b(ne, &store);
      __ dmb(ISH);
      break;
    }
#define ATOMIC_ARITH_BINOP_CASE(op, instr1, instr2) \
  case kArmWord32AtomicPair##op: { \
    DCHECK(VerifyOutputOfAtomicPairInstr(&i, instr, r2, r3)); \
    ASSEMBLE_ATOMIC64_ARITH_BINOP(instr1, instr2); \
    break; \
  }
      ATOMIC_ARITH_BINOP_CASE(Add, add, adc)
      ATOMIC_ARITH_BINOP_CASE(Sub, sub, sbc)
#undef ATOMIC_ARITH_BINOP_CASE
#define ATOMIC_LOGIC_BINOP_CASE(op, instr1) \
  case kArmWord32AtomicPair##op: { \
    DCHECK(VerifyOutputOfAtomicPairInstr(&i, instr, r2, r3)); \
    ASSEMBLE_ATOMIC64_LOGIC_BINOP(instr1); \
    break; \
  }
      ATOMIC_LOGIC_BINOP_CASE(And, and_)
      ATOMIC_LOGIC_BINOP_CASE(Or, orr)
      ATOMIC_LOGIC_BINOP_CASE(Xor, eor)
#undef ATOMIC_LOGIC_BINOP_CASE
    case kArmWord32AtomicPairExchange: {
      DCHECK(VerifyOutputOfAtomicPairInstr(&i, instr, r6, r7));
      Label exchange;
      __ add(i.TempRegister(0), i.InputRegister(2), i.InputRegister(3));
      __ dmb(ISH);
      __ bind(&exchange);
      __ ldrexd(r6, r7, i.TempRegister(0));
      __ strexd(i.TempRegister(1), i.InputRegister(0), i.InputRegister(1),
                i.TempRegister(0));
      __ teq(i.TempRegister(1), Operand(0));
      __ b(ne, &exchange);
      __ dmb(ISH);
      break;
    }
    case kArmWord32AtomicPairCompareExchange: {
      DCHECK(VerifyOutputOfAtomicPairInstr(&i, instr, r2, r3));
      __ add(i.TempRegister(0), i.InputRegister(4), i.InputRegister(5));
      Label compareExchange;
      Label exit;
      __ dmb(ISH);
      __ bind(&compareExchange);
      __ ldrexd(r2, r3, i.TempRegister(0));
      __ teq(i.InputRegister(0), Operand(r2));
      __ b(ne, &exit);
      __ teq(i.InputRegister(1), Operand(r3));
      __ b(ne, &exit);
      __ strexd(i.TempRegister(1), i.InputRegister(2), i.InputRegister(3),
                i.TempRegister(0));
      __ teq(i.TempRegister(1), Operand(0));
      __ b(ne, &compareExchange);
      __ bind(&exit);
      __ dmb(ISH);
      break;
    }
#undef ASSEMBLE_ATOMIC_LOAD_INTEGER
#undef ASSEMBLE_ATOMIC_STORE_INTEGER
#undef ASSEMBLE_ATOMIC_EXCHANGE_INTEGER
#undef ASSEMBLE_ATOMIC_COMPARE_EXCHANGE_INTEGER
#undef ASSEMBLE_ATOMIC_BINOP
#undef ASSEMBLE_ATOMIC64_ARITH_BINOP
#undef ASSEMBLE_ATOMIC64_LOGIC_BINOP
#undef ASSEMBLE_IEEE754_BINOP
#undef ASSEMBLE_IEEE754_UNOP
#undef ASSEMBLE_NEON_NARROWING_OP
#undef ASSEMBLE_SIMD_SHIFT_LEFT
#undef ASSEMBLE_SIMD_SHIFT_RIGHT
  }
  return kSuccess;
}
References __, v8::base::ieee754::acos(), v8::base::ieee754::acosh(), v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::UseScratchRegisterScope::AcquireS(), v8::bigint::Add(), v8::internal::wasm::liftoff::And(), v8::base::ieee754::asin(), v8::base::ieee754::asinh(), ASSEMBLE_ATOMIC_COMPARE_EXCHANGE_INTEGER, ASSEMBLE_ATOMIC_EXCHANGE_INTEGER, ASSEMBLE_ATOMIC_LOAD_INTEGER, ASSEMBLE_ATOMIC_STORE_INTEGER, ASSEMBLE_F64X2_ARITHMETIC_BINOP, ASSEMBLE_IEEE754_BINOP, ASSEMBLE_IEEE754_UNOP, ASSEMBLE_NEON_NARROWING_OP, ASSEMBLE_SIMD_SHIFT_LEFT, ASSEMBLE_SIMD_SHIFT_RIGHT, AssembleArchBinarySearchSwitch(), AssembleArchJump(), AssembleArchTableSwitch(), AssemblePrepareTailCall(), AssembleReturn(), v8::base::ieee754::atan(), v8::base::ieee754::atan2(), v8::base::ieee754::atanh(), ATOMIC_ARITH_BINOP_CASE, ATOMIC_BINOP_CASE, ATOMIC_LOGIC_BINOP_CASE, BuildTranslation(), caller_registers_saved_, v8::internal::compiler::LocationOperand::cast(), v8::base::ieee754::cbrt(), CHECK, v8::internal::compiler::FrameAccessState::ClearSPDelta(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RelocInfo::CODE_TARGET, v8::base::ieee754::cos(), v8::base::ieee754::cosh(), v8::internal::cp, v8::internal::cs, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::base::BitField< T, shift, size, U >::decode(), DetermineStubCallMode(), v8::internal::ElementSizeInPointers(), v8::internal::eq, v8::base::ieee754::exp(), v8::base::ieee754::expm1(), v8::internal::FieldMemOperand(), fp_mode_, frame(), frame_access_state(), v8::internal::FrameSlotToFPOffset(), v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::from_code(), v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::from_code(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::Float32::FromBits(), v8::internal::Smi::FromInt(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), GetStackCheckOffset(), v8::internal::gt, handlers_, v8::internal::compiler::Instruction::HasCallDescriptorFlag(), v8::internal::hi, v8::internal::QwNeonRegister::high(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::OutputFrameStateCombine::Ignore(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), IsAligned(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::ISH, isolate(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsSimd128Register(), v8::internal::compiler::Instruction::JSCallArgumentCountInputIndex(), v8::internal::kClearedWeakHeapObjectLower32, v8::internal::kDoubleRegZero, v8::internal::compiler::CallDescriptor::kFixedTargetRegister, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::CallDescriptor::kHasExceptionHandler, v8::internal::kIgnore, v8::internal::kJavaScriptCallCodeStartRegister, v8::internal::compiler::CallDescriptor::kNeedsFrameState, kNo, v8::internal::MemoryChunk::kPointersFromHereAreInterestingMask, v8::internal::kReturnRegister0, v8::internal::kRootRegister, v8::internal::kSave, v8::internal::kSeqCst, v8::internal::kSimd128, v8::internal::kSimd128Size, kSuccess, v8::internal::kSystemPointerSize, v8::internal::kTailCall, v8::internal::compiler::kValueIsAny, v8::internal::compiler::kValueIsPointer, kYes, v8::internal::compiler::DeoptimizationExit::label(), v8::internal::LeaveCC, linkage(), v8::base::ieee754::log(), v8::base::ieee754::log10(), v8::base::ieee754::log1p(), v8::base::ieee754::log2(), v8::internal::QwNeonRegister::low(), v8::internal::ls, make_uint64(), v8::internal::StackFrame::MANUAL, v8::internal::compiler::UnwindingInfoWriter::MarkBlockWillExit(), masm(), v8::internal::mi, mode(), v8::internal::ne, v8::internal::Neon16, v8::internal::Neon32, v8::internal::Neon64, v8::internal::Neon8, v8::internal::NeonS16, v8::internal::NeonS32, v8::internal::NeonS64, v8::internal::NeonS8, v8::internal::NeonU16, v8::internal::NeonU32, v8::internal::NeonU64, v8::internal::NeonU8, v8::internal::Zone::New(), v8::internal::StackFrame::NO_FRAME_TYPE, v8::internal::compiler::FrameOffset::offset(), v8::internal::compiler::Instruction::opcode(), v8::internal::wasm::liftoff::Or(), v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), Pop(), v8::base::ieee754::legacy::pow(), Push(), v8::internal::wasm::liftoff::push(), RecordCallPosition(), RecordDeoptInfo(), RecordSafepoint(), v8::internal::compiler::Instruction::reference_map(), v8::internal::compiler::LocationOperand::representation(), v8::base::internal::result, v8::internal::compiler::Constant::rmode(), S_FROM_Q, v8::internal::SetCC, v8::internal::compiler::FrameAccessState::SetFrameAccessToDefault(), v8::internal::compiler::FrameAccessState::SetFrameAccessToFP(), ShouldApplyOffsetToStackCheck(), v8::base::ieee754::sin(), v8::base::ieee754::sinh(), size(), store(), v8::internal::wasm::liftoff::Sub(), v8::internal::SY, v8::base::ieee754::tan(), v8::base::ieee754::tanh(), v8::internal::compiler::Constant::ToInt32(), v8::internal::UNREACHABLE(), unwinding_info_writer_, v8::internal::v8_flags, v8::internal::value, v8::internal::vs, v8::internal::wasm::liftoff::Xor(), v8::internal::Operand::Zero(), and zone().
Referenced by AssembleInstruction().
AssembleArchJump()
void v8::internal::compiler::CodeGenerator::AssembleArchJump (RpoNumber target) [private]
Definition at line 490 of file code-generator.cc.
                                                     {
  if (!IsNextInAssemblyOrder(target))
    AssembleArchJumpRegardlessOfAssemblyOrder(target);
}
References AssembleArchJumpRegardlessOfAssemblyOrder(), and IsNextInAssemblyOrder().
Referenced by AssembleArchInstruction(), and AssembleInstruction().
AssembleArchJumpRegardlessOfAssemblyOrder()
void v8::internal::compiler::CodeGenerator::AssembleArchJumpRegardlessOfAssemblyOrder (RpoNumber target) [private]
Definition at line 3654 of file code-generator-arm.cc.
                      {
  __ b(GetLabel(target));
}
References __, and GetLabel().
Referenced by AssembleArchBinarySearchSwitchRange(), and AssembleArchJump().
AssembleArchSelect()
void v8::internal::compiler::CodeGenerator::AssembleArchSelect (Instruction * instr, FlagsCondition condition) [private]
Definition at line 3749 of file code-generator-arm.cc.
                                                                 {
  UNIMPLEMENTED();
}
References v8::internal::compiler::UNIMPLEMENTED().
Referenced by AssembleInstruction().
AssembleArchTableSwitch()
void v8::internal::compiler::CodeGenerator::AssembleArchTableSwitch (Instruction * instr) [private]
Definition at line 3733 of file code-generator-arm.cc.
                                                              {
  ArmOperandConverter i(this, instr);
  Register input = i.InputRegister(0);
  size_t const case_count = instr->InputCount() - 2;
  // This {cmp} might still emit a constant pool entry.
  __ cmp(input, Operand(case_count));
  // Ensure to emit the constant pool first if necessary.
  __ CheckConstPool(true, true);
  __ BlockConstPoolFor(case_count + 2);
  __ add(pc, pc, Operand(input, LSL, 2), LeaveCC, lo);
  __ b(GetLabel(i.InputRpo(1)));
  for (size_t index = 0; index < case_count; ++index) {
    __ b(GetLabel(i.InputRpo(index + 2)));
  }
}
References __, GetLabel(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::Instruction::InputCount(), v8::internal::LeaveCC, v8::internal::lo, and v8::internal::LSL.
Referenced by AssembleArchInstruction().
AssembleBlock()
CodeGenerator::CodeGenResult v8::internal::compiler::CodeGenerator::AssembleBlock (const InstructionBlock * block) [private]
Definition at line 609 of file code-generator.cc.
                                   {
  if (block->IsHandler()) {
    masm()->ExceptionHandler();
  }
  for (int i = block->code_start(); i < block->code_end(); ++i) {
    CodeGenResult result = AssembleInstruction(i, block);
    if (result != kSuccess) return result;
  }
  return kSuccess;
}
References AssembleInstruction(), v8::internal::compiler::InstructionBlock::code_start(), v8::internal::MacroAssembler::ExceptionHandler(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionBlock::IsHandler(), kSuccess, masm(), and v8::base::internal::result.
Referenced by AssembleCode().
AssembleCode()
void v8::internal::compiler::CodeGenerator::AssembleCode ()
Definition at line 203 of file code-generator.cc.
                                 {
  OptimizedCompilationInfo* info = this->info();
  auto call_descriptor = linkage()->GetIncomingDescriptor();
  // Compute incoming parameter count for code using JS linkage. This will
  // ultimately set the parameter count on the resulting Code object.
  if (call_descriptor->IsJSFunctionCall()) {
    parameter_count_ = call_descriptor->ParameterSlotCount();
    if (Builtins::IsBuiltinId(info->builtin())) {
      CHECK_EQ(parameter_count_,
               Builtins::GetStackParameterCount(info->builtin()));
    } else if (info->has_bytecode_array()) {
      CHECK_EQ(parameter_count_, info->bytecode_array()->parameter_count());
    }
  }
  // Open a frame scope to indicate that there is a frame on the stack. The
  // MANUAL indicates that the scope shouldn't actually generate code to set up
  // the frame (that is done in AssemblePrologue).
  FrameScope frame_scope(masm(), StackFrame::MANUAL);
  if (info->source_positions()) {
    AssembleSourcePosition(start_source_position());
  }
  offsets_info_.code_start_register_check = masm()->pc_offset();
  masm()->CodeEntry();
#ifdef V8_ENABLE_SANDBOX_HARDWARE_SUPPORT
  // TODO(saelo): should there also be a info->IsJS()?
  if (v8_flags.debug_code &&
      (call_descriptor->IsJSFunctionCall() || info->IsWasm())) {
    masm()->RecordComment("-- Prologue: check sandboxing mode --");
    masm()->AssertInSandboxedExecutionMode();
  }
#endif
  // Check that {kJavaScriptCallCodeStartRegister} has been set correctly.
  if (v8_flags.debug_code && info->called_with_code_start_register()) {
    masm()->RecordComment("-- Prologue: check code start register --");
    AssembleCodeStartRegisterCheck();
  }
#ifdef V8_ENABLE_LEAPTIERING
  // Check that {kJavaScriptCallDispatchHandleRegister} has been set correctly.
  if (v8_flags.debug_code && call_descriptor->IsJSFunctionCall()) {
    masm()->RecordComment("-- Prologue: check dispatch handle register --");
    AssembleDispatchHandleRegisterCheck();
  }
#endif
  offsets_info_.deopt_check = masm()->pc_offset();
  // We want to bailout only from JS functions, which are the only ones
  // that are optimized.
  if (info->IsOptimizing()) {
    DCHECK(call_descriptor->IsJSFunctionCall());
    masm()->RecordComment("-- Prologue: check for deoptimization --");
    BailoutIfDeoptimized();
  }
  // Define deoptimization literals for all inlined functions.
  DCHECK_EQ(0u, deoptimization_literals_.size());
  for (OptimizedCompilationInfo::InlinedFunctionHolder& inlined :
       info->inlined_functions()) {
    if (!inlined.shared_info.equals(info->shared_info())) {
      int index = DefineDeoptimizationLiteral(
          DeoptimizationLiteral(inlined.shared_info));
      inlined.RegisterInlinedFunctionId(index);
    }
  }
  inlined_function_count_ = deoptimization_literals_.size();
  unwinding_info_writer_.SetNumberOfInstructionBlocks(
      instructions()->InstructionBlockCount());
  if (info->trace_turbo_json()) {
    block_starts_.assign(instructions()->instruction_blocks().size(), -1);
    instr_starts_.assign(instructions()->instructions().size(), {});
  }
  // Assemble instructions in assembly order.
  offsets_info_.blocks_start = masm()->pc_offset();
  for (const InstructionBlock* block : instructions()->ao_blocks()) {
    // Align loop headers on vendor recommended boundaries.
    if (block->ShouldAlignLoopHeader()) {
      masm()->LoopHeaderAlign();
    } else if (block->ShouldAlignCodeTarget()) {
      masm()->CodeTargetAlign();
    }
    if (info->trace_turbo_json()) {
      block_starts_[block->rpo_number().ToInt()] = masm()->pc_offset();
    }
    // Bind a label for a block.
    current_block_ = block->rpo_number();
    unwinding_info_writer_.BeginInstructionBlock(masm()->pc_offset(), block);
    if (v8_flags.code_comments && !block->omitted_by_jump_threading()) {
      std::ostringstream buffer;
      buffer << "-- B" << block->rpo_number().ToInt() << " start";
      if (block->IsDeferred()) buffer << " (deferred)";
      if (!block->needs_frame()) buffer << " (no frame)";
      if (block->must_construct_frame()) buffer << " (construct frame)";
      if (block->must_deconstruct_frame()) buffer << " (deconstruct frame)";
      if (block->IsLoopHeader()) {
        buffer << " (loop up to " << block->loop_end().ToInt() << ")";
      }
      if (block->loop_header().IsValid()) {
        buffer << " (in loop " << block->loop_header().ToInt() << ")";
      }
      buffer << " --";
      masm()->RecordComment(buffer.str().c_str(), SourceLocation());
    }
    frame_access_state()->MarkHasFrame(block->needs_frame());
    masm()->bind(GetLabel(current_block_));
#ifdef V8_ENABLE_CONTROL_FLOW_INTEGRITY
    if (block->IsTableSwitchTarget()) {
      masm()->JumpTarget();
    }
#endif
    if (block->must_construct_frame()) {
      AssembleConstructFrame();
      // We need to setup the root register after we assemble the prologue, to
      // avoid clobbering callee saved registers in case of C linkage and
      // using the roots.
      // TODO(mtrofin): investigate how we can avoid doing this repeatedly.
      if (call_descriptor->InitializeRootRegister()) {
        masm()->InitializeRootRegister();
      }
    }
#ifdef CAN_USE_RVV_INSTRUCTIONS
    // RVV uses VectorUnit to emit vset{i}vl{i}, reducing the static and dynamic
    // overhead of the vset{i}vl{i} instruction. However there are some jumps
    // back between blocks. the Rvv instruction may get an incorrect vtype. so
    // here VectorUnit needs to be cleared to ensure that the vtype is correct
    // within the block.
    masm()->VU.clear();
#endif
    if (V8_EMBEDDED_CONSTANT_POOL_BOOL && !block->needs_frame()) {
      ConstantPoolUnavailableScope constant_pool_unavailable(masm());
      result_ = AssembleBlock(block);
    } else {
      result_ = AssembleBlock(block);
    }
    if (result_ != kSuccess) return;
    unwinding_info_writer_.EndInstructionBlock(block);
  }
  // Assemble all out-of-line code.
  offsets_info_.out_of_line_code = masm()->pc_offset();
  if (ools_) {
    masm()->RecordComment("-- Out of line code --");
    for (OutOfLineCode* ool = ools_; ool; ool = ool->next()) {
      masm()->bind(ool->entry());
      ool->Generate();
      if (ool->exit()->is_bound()) masm()->jmp(ool->exit());
    }
  }
  // This nop operation is needed to ensure that the trampoline is not
  // confused with the pc of the call before deoptimization.
  // The test regress/regress-259 is an example of where we need it.
  masm()->nop();
  // For some targets, we must make sure that constant and veneer pools are
  // emitted before emitting the deoptimization exits.
  PrepareForDeoptimizationExits(&deoptimization_exits_);
  deopt_exit_start_offset_ = masm()->pc_offset();
  // Assemble deoptimization exits.
  offsets_info_.deoptimization_exits = masm()->pc_offset();
  int last_updated = 0;
  // We sort the deoptimization exits here so that the lazy ones will be visited
  // last. We need this as lazy deopts might need additional instructions.
  auto cmp = [](const DeoptimizationExit* a, const DeoptimizationExit* b) {
    // The deoptimization exits are sorted so that lazy deopt exits appear after
    // eager deopts.
    int a_kind_val = a->kind() == DeoptimizeKind::kEager ? 0 : 1;
    int b_kind_val = b->kind() == DeoptimizeKind::kEager ? 0 : 1;
    DCHECK_IMPLIES(a_kind_val == 1,
                   a->kind() == DeoptimizeKind::kLazy ||
                       a->kind() == DeoptimizeKind::kLazyAfterFastCall);
    DCHECK_IMPLIES(b_kind_val == 1,
                   b->kind() == DeoptimizeKind::kLazy ||
                       b->kind() == DeoptimizeKind::kLazyAfterFastCall);
    if (a_kind_val != b_kind_val) {
      return a_kind_val < b_kind_val;
    }
    return a->pc_offset() < b->pc_offset();
  };
  std::sort(deoptimization_exits_.begin(), deoptimization_exits_.end(), cmp);
  {
#ifdef V8_TARGET_ARCH_PPC64
    v8::internal::Assembler::BlockTrampolinePoolScope block_trampoline_pool(
        masm());
#endif
    for (DeoptimizationExit* exit : deoptimization_exits_) {
      if (exit->emitted()) continue;
      exit->set_deoptimization_id(next_deoptimization_id_++);
      result_ = AssembleDeoptimizerCall(exit);
      if (result_ != kSuccess) return;
      // UpdateDeoptimizationInfo expects lazy deopts to be visited in pc_offset
      // order, which is always the case since they are added to
      // deoptimization_exits_ in that order, and the optional sort operation
      // above preserves that order.
      if (exit->kind() == DeoptimizeKind::kLazy ||
          exit->kind() == DeoptimizeKind::kLazyAfterFastCall) {
        int trampoline_pc = exit->label()->pos();
        last_updated = safepoints()->UpdateDeoptimizationInfo(
            exit->pc_offset(), trampoline_pc, last_updated,
            exit->deoptimization_id());
      }
    }
  }
  offsets_info_.pools = masm()->pc_offset();
  // TODO(jgruber): Move all inlined metadata generation into a new,
  // architecture-independent version of FinishCode. Currently, this includes
  // the safepoint table, handler table, constant pool, and code comments, in
  // that order.
  FinishCode();
  offsets_info_.jump_tables = masm()->pc_offset();
  // Emit the jump tables.
  if (jump_tables_) {
    masm()->Align(kSystemPointerSize);
    for (JumpTable* table = jump_tables_; table; table = table->next()) {
      masm()->bind(table->label());
      AssembleJumpTable(table->targets());
    }
  }
  // The PerfJitLogger logs code up until here, excluding the safepoint
  // table. Resolve the unwinding info now so it is aware of the same code
  // size as reported by perf.
  unwinding_info_writer_.Finish(masm()->pc_offset());
  // Final alignment before starting on the metadata section.
  masm()->Align(InstructionStream::kMetadataAlignment);
  safepoints()->Emit(masm(), frame()->GetTotalFrameSlotCount());
  // Emit the exception handler table.
  if (!handlers_.empty()) {
    handler_table_offset_ = HandlerTable::EmitReturnTableStart(masm());
    for (size_t i = 0; i < handlers_.size(); ++i) {
      int pos = handlers_[i].handler != nullptr ? handlers_[i].handler->pos()
                                                : HandlerTable::kLazyDeopt;
      HandlerTable::EmitReturnEntry(masm(), handlers_[i].pc_offset, pos);
    }
  }
  masm()->MaybeEmitOutOfLineConstantPool();
  masm()->FinalizeJumpOptimizationInfo();
  result_ = kSuccess;
}
References v8::internal::Assembler::Align(), AssembleBlock(), AssembleCodeStartRegisterCheck(), AssembleConstructFrame(), AssembleDeoptimizerCall(), AssembleJumpTable(), AssembleSourcePosition(), v8::internal::MacroAssembler::AssertInSandboxedExecutionMode(), v8::internal::ZoneVector< T >::assign(), BailoutIfDeoptimized(), v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock(), v8::internal::Assembler::bind(), block_starts_, v8::internal::compiler::TurbolizerCodeOffsetsInfo::blocks_start, v8::internal::OptimizedCompilationInfo::builtin(), v8::internal::OptimizedCompilationInfo::bytecode_array(), CHECK_EQ, v8::internal::Assembler::VectorUnit::clear(), v8::internal::compiler::TurbolizerCodeOffsetsInfo::code_start_register_check, v8::internal::MacroAssembler::CodeEntry(), v8::internal::Assembler::CodeTargetAlign(), current_block_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DefineDeoptimizationLiteral(), v8::internal::compiler::TurbolizerCodeOffsetsInfo::deopt_check, deopt_exit_start_offset_, v8::internal::compiler::TurbolizerCodeOffsetsInfo::deoptimization_exits, deoptimization_exits_, deoptimization_literals_, v8::internal::SafepointTableBuilder::Emit(), v8::internal::HandlerTable::EmitReturnEntry(), v8::internal::HandlerTable::EmitReturnTableStart(), v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock(), v8::internal::Assembler::FinalizeJumpOptimizationInfo(), v8::internal::compiler::UnwindingInfoWriter::Finish(), FinishCode(), frame(), frame_access_state(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), GetLabel(), v8::internal::Builtins::GetStackParameterCount(), handler_table_offset_, handlers_, v8::internal::OptimizedCompilationInfo::has_bytecode_array(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, info(), v8::internal::MacroAssembler::InitializeRootRegister(), inlined_function_count_, v8::internal::OptimizedCompilationInfo::inlined_functions(), instr_starts_, instructions(), v8::internal::Builtins::IsBuiltinId(), v8::internal::OptimizedCompilationInfo::IsOptimizing(), v8::internal::MacroAssembler::jmp(), v8::internal::compiler::TurbolizerCodeOffsetsInfo::jump_tables, jump_tables_, v8::internal::MacroAssembler::JumpTarget(), v8::internal::kEager, v8::internal::compiler::DeoptimizationExit::kind(), v8::internal::kLazy, v8::internal::kLazyAfterFastCall, v8::internal::HandlerTable::kLazyDeopt, v8::internal::InstructionStream::kMetadataAlignment, kSuccess, v8::internal::kSystemPointerSize, linkage(), v8::internal::Assembler::LoopHeaderAlign(), v8::internal::StackFrame::MANUAL, v8::internal::compiler::FrameAccessState::MarkHasFrame(), masm(), v8::internal::Assembler::MaybeEmitOutOfLineConstantPool(), v8::internal::compiler::OutOfLineCode::next(), v8::internal::compiler::CodeGenerator::JumpTable::next(), next_deoptimization_id_, v8::internal::Assembler::nop(), offsets_info_, ools_, v8::internal::compiler::TurbolizerCodeOffsetsInfo::out_of_line_code, parameter_count_, v8::internal::AssemblerBase::pc_offset(), v8::internal::compiler::DeoptimizationExit::pc_offset(), v8::internal::compiler::TurbolizerCodeOffsetsInfo::pools, PrepareForDeoptimizationExits(), v8::internal::AssemblerBase::RecordComment(), result_, safepoints(), v8::internal::compiler::UnwindingInfoWriter::SetNumberOfInstructionBlocks(), v8::internal::OptimizedCompilationInfo::shared_info(), size(), v8::base::sort(), start_source_position(), unwinding_info_writer_, v8::internal::SafepointTableBuilder::UpdateDeoptimizationInfo(), V8_EMBEDDED_CONSTANT_POOL_BOOL, v8::internal::v8_flags, and v8::internal::Assembler::VU.
Referenced by v8::internal::compiler::turboshaft::AssembleCodePhase::Run().
AssembleCodeStartRegisterCheck()
void v8::internal::compiler::CodeGenerator::AssembleCodeStartRegisterCheck () [private]
Definition at line 629 of file code-generator-arm.cc.
                                                   {
  UseScratchRegisterScope temps(masm());
  Register scratch = temps.Acquire();
  __ ComputeCodeStartAddress(scratch);
  __ cmp(scratch, kJavaScriptCallCodeStartRegister);
  __ Assert(eq, AbortReason::kWrongFunctionCodeStart);
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::eq, v8::internal::kJavaScriptCallCodeStartRegister, and masm().
Referenced by AssembleCode().
AssembleConstructFrame()
void v8::internal::compiler::CodeGenerator::AssembleConstructFrame () [private]
Definition at line 3778 of file code-generator-arm.cc.
                                           {
  auto call_descriptor = linkage()->GetIncomingDescriptor();
  if (frame_access_state()->has_frame()) {
    if (call_descriptor->IsCFunctionCall()) {
#if V8_ENABLE_WEBASSEMBLY
      if (info()->GetOutputStackFrameType() == StackFrame::C_WASM_ENTRY) {
        __ StubPrologue(StackFrame::C_WASM_ENTRY);
        // Reserve stack space for saving the c_entry_fp later.
        __ AllocateStackSpace(kSystemPointerSize);
#else
      // For balance.
      if (false) {
#endif // V8_ENABLE_WEBASSEMBLY
      } else {
        __ Push(lr, fp);
        __ mov(fp, sp);
      }
    } else if (call_descriptor->IsJSFunctionCall()) {
      __ Prologue();
    } else {
      __ StubPrologue(info()->GetOutputStackFrameType());
#if V8_ENABLE_WEBASSEMBLY
      if (call_descriptor->IsAnyWasmFunctionCall() ||
          call_descriptor->IsWasmImportWrapper() ||
          call_descriptor->IsWasmCapiFunction()) {
        // For import wrappers and C-API functions, this stack slot is only used
        // for printing stack traces in V8. Also, it holds a WasmImportData
        // instead of the trusted instance data, which is taken care of in the
        // frames accessors.
        __ Push(kWasmImplicitArgRegister);
      }
      if (call_descriptor->IsWasmCapiFunction()) {
        // Reserve space for saving the PC later.
        __ AllocateStackSpace(kSystemPointerSize);
      }
#endif // V8_ENABLE_WEBASSEMBLY
    }
    unwinding_info_writer_.MarkFrameConstructed(__ pc_offset());
  }
  int required_slots =
      frame()->GetTotalFrameSlotCount() - frame()->GetFixedSlotCount();
  if (info()->is_osr()) {
    // TurboFan OSR-compiled functions cannot be entered directly.
    __ Abort(AbortReason::kShouldNotDirectlyEnterOsrFunction);
    // Unoptimized code jumps directly to this entrypoint while the unoptimized
    // frame is still on the stack. Optimized code uses OSR values directly from
    // the unoptimized frame. Thus, all that needs to be done is to allocate the
    // remaining stack slots.
    __ RecordComment("-- OSR entrypoint --");
    osr_pc_offset_ = __ pc_offset();
    required_slots -= osr_helper()->UnoptimizedFrameSlots();
  }
  const RegList saves = call_descriptor->CalleeSavedRegisters();
  const DoubleRegList saves_fp = call_descriptor->CalleeSavedFPRegisters();
  if (required_slots > 0) {
    DCHECK(frame_access_state()->has_frame());
#if V8_ENABLE_WEBASSEMBLY
    if (info()->IsWasm() && required_slots * kSystemPointerSize > 4 * KB) {
      // For WebAssembly functions with big frames we have to do the stack
      // overflow check before we construct the frame. Otherwise we may not
      // have enough space on the stack to call the runtime for the stack
      // overflow.
      Label done;
      // If the frame is bigger than the stack, we throw the stack overflow
      // exception unconditionally. Thereby we can avoid the integer overflow
      // check in the condition code.
      if (required_slots * kSystemPointerSize < v8_flags.stack_size * KB) {
        UseScratchRegisterScope temps(masm());
        Register stack_limit = temps.Acquire();
        __ LoadStackLimit(stack_limit, StackLimitKind::kRealStackLimit);
        __ add(stack_limit, stack_limit,
               Operand(required_slots * kSystemPointerSize));
        __ cmp(sp, stack_limit);
        __ b(cs, &done);
      }
      if (v8_flags.experimental_wasm_growable_stacks) {
        RegList regs_to_save;
        regs_to_save.set(WasmHandleStackOverflowDescriptor::GapRegister());
        regs_to_save.set(
            WasmHandleStackOverflowDescriptor::FrameBaseRegister());
        for (auto reg : wasm::kGpParamRegisters) regs_to_save.set(reg);
        __ stm(db_w, sp, regs_to_save);
        DoubleRegList fp_regs_to_save;
        for (auto reg : wasm::kFpParamRegisters) fp_regs_to_save.set(reg);
        __ vstm(db_w, sp, fp_regs_to_save.first(), fp_regs_to_save.last());
        __ mov(WasmHandleStackOverflowDescriptor::GapRegister(),
               Operand(required_slots * kSystemPointerSize));
        __ add(
            WasmHandleStackOverflowDescriptor::FrameBaseRegister(), fp,
            Operand(call_descriptor->ParameterSlotCount() * kSystemPointerSize +
                    CommonFrameConstants::kFixedFrameSizeAboveFp));
        __ CallBuiltin(Builtin::kWasmHandleStackOverflow);
        __ vldm(ia_w, sp, fp_regs_to_save.first(), fp_regs_to_save.last());
        __ ldm(ia_w, sp, regs_to_save);
      } else {
        __ Call(static_cast<intptr_t>(Builtin::kWasmStackOverflow),
                RelocInfo::WASM_STUB_CALL);
        // The call does not return, hence we can ignore any references and just
        // define an empty safepoint.
        ReferenceMap* reference_map = zone()->New<ReferenceMap>(zone());
        RecordSafepoint(reference_map);
        if (v8_flags.debug_code) __ stop();
      }
      __ bind(&done);
    }
#endif // V8_ENABLE_WEBASSEMBLY
    // Skip callee-saved and return slots, which are pushed below.
    required_slots -= saves.Count();
    required_slots -= frame()->GetReturnSlotCount();
    required_slots -= 2 * saves_fp.Count();
    if (required_slots > 0) {
      __ AllocateStackSpace(required_slots * kSystemPointerSize);
    }
  }
  if (!saves_fp.is_empty()) {
    // Save callee-saved FP registers.
    static_assert(DwVfpRegister::kNumRegisters == 32);
    __ vstm(db_w, sp, saves_fp.first(), saves_fp.last());
  }
  if (!saves.is_empty()) {
    // Save callee-saved registers.
    __ stm(db_w, sp, saves);
  }
  const int returns = frame()->GetReturnSlotCount();
  // Create space for returns.
  __ AllocateStackSpace(returns * kSystemPointerSize);
  if (!frame()->tagged_slots().IsEmpty()) {
    UseScratchRegisterScope temps(masm());
    Register zero = temps.Acquire();
    __ mov(zero, Operand(0));
    for (int spill_slot : frame()->tagged_slots()) {
      FrameOffset offset = frame_access_state()->GetFrameOffset(spill_slot);
      DCHECK(offset.from_frame_pointer());
      __ str(zero, MemOperand(fp, offset.offset()));
    }
  }
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::RegListBase< RegisterT >::Count(), v8::internal::cs, v8::internal::db_w, v8::internal::DCHECK(), v8::internal::RegListBase< RegisterT >::first(), frame(), frame_access_state(), v8::internal::compiler::FrameOffset::from_frame_pointer(), v8::internal::WasmHandleStackOverflowDescriptor::GapRegister(), v8::internal::compiler::Frame::GetFixedSlotCount(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::compiler::Frame::GetReturnSlotCount(), v8::internal::compiler::Frame::GetTotalFrameSlotCount(), v8::internal::ia_w, info(), v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::KB, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::wasm::kFpParamRegisters, v8::internal::wasm::kGpParamRegisters, v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::kNumRegisters, v8::internal::kRealStackLimit, v8::internal::kSystemPointerSize, v8::internal::kWasmImplicitArgRegister, v8::internal::RegListBase< RegisterT >::last(), linkage(), v8::internal::compiler::UnwindingInfoWriter::MarkFrameConstructed(), masm(), v8::internal::Zone::New(), v8::internal::compiler::FrameOffset::offset(), osr_helper(), osr_pc_offset_, Push(), RecordSafepoint(), v8::internal::RegListBase< RegisterT >::set(), v8::internal::compiler::OsrHelper::UnoptimizedFrameSlots(), unwinding_info_writer_, v8::internal::v8_flags, v8::internal::RelocInfo::WASM_STUB_CALL, v8::internal::zero, and zone().
Referenced by AssembleCode().
AssembleDeconstructFrame()
void v8::internal::compiler::CodeGenerator::AssembleDeconstructFrame () [private]
Definition at line 504 of file code-generator-arm.cc.
                                             {
  __ LeaveFrame(StackFrame::MANUAL);
  unwinding_info_writer_.MarkFrameDeconstructed(__ pc_offset());
}
References __, v8::internal::StackFrame::MANUAL, v8::internal::compiler::UnwindingInfoWriter::MarkFrameDeconstructed(), and unwinding_info_writer_.
Referenced by AssembleInstruction(), and AssembleReturn().
AssembleDeoptimizerCall()
CodeGenerator::CodeGenResult v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall (DeoptimizationExit * exit) [private]
Definition at line 164 of file code-generator.cc.
                              {
  int deoptimization_id = exit->deoptimization_id();
  if (deoptimization_id > Deoptimizer::kMaxNumberOfEntries) {
    return kTooManyDeoptimizationBailouts;
  }
  DeoptimizeKind deopt_kind = exit->kind();
  DeoptimizeReason deoptimization_reason = exit->reason();
  Label* jump_deoptimization_entry_label =
      &jump_deoptimization_entry_labels_[static_cast<int>(deopt_kind)];
  if (info()->source_positions() ||
      AlwaysPreserveDeoptReason(deoptimization_reason)) {
    masm()->RecordDeoptReason(deoptimization_reason, exit->node_id(),
                              exit->pos(), deoptimization_id);
  }
  if (deopt_kind == DeoptimizeKind::kLazy ||
      deopt_kind == DeoptimizeKind::kLazyAfterFastCall) {
    ++lazy_deopt_count_;
    masm()->BindExceptionHandler(exit->label());
  } else {
    ++eager_deopt_count_;
    masm()->bind(exit->label());
  }
  Builtin target = Deoptimizer::GetDeoptimizationEntry(deopt_kind);
  masm()->CallForDeoptimization(target, deoptimization_id, exit->label(),
                                deopt_kind, exit->continue_label(),
                                jump_deoptimization_entry_label);
  exit->set_emitted();
  return kSuccess;
}
References v8::internal::AlwaysPreserveDeoptReason(), v8::internal::Assembler::bind(), v8::internal::MacroAssembler::BindExceptionHandler(), v8::internal::MacroAssembler::CallForDeoptimization(), v8::internal::compiler::DeoptimizationExit::continue_label(), v8::internal::compiler::DeoptimizationExit::deoptimization_id(), eager_deopt_count_, v8::internal::Deoptimizer::GetDeoptimizationEntry(), info(), jump_deoptimization_entry_labels_, v8::internal::compiler::DeoptimizationExit::kind(), v8::internal::kLazy, v8::internal::kLazyAfterFastCall, v8::internal::Deoptimizer::kMaxNumberOfEntries, kSuccess, kTooManyDeoptimizationBailouts, v8::internal::compiler::DeoptimizationExit::label(), lazy_deopt_count_, masm(), v8::internal::compiler::DeoptimizationExit::node_id(), v8::internal::compiler::DeoptimizationExit::pos(), v8::internal::compiler::DeoptimizationExit::reason(), v8::internal::Assembler::RecordDeoptReason(), and v8::internal::compiler::DeoptimizationExit::set_emitted().
Referenced by AssembleCode().
AssembleGaps()
void v8::internal::compiler::CodeGenerator::AssembleGaps (Instruction * instr) [private]
Definition at line 958 of file code-generator.cc.
                                                   {
  for (int i = Instruction::FIRST_GAP_POSITION;
       i <= Instruction::LAST_GAP_POSITION; i++) {
    Instruction::GapPosition inner_pos =
        static_cast<Instruction::GapPosition>(i);
    ParallelMove* move = instr->GetParallelMove(inner_pos);
    if (move != nullptr) resolver()->Resolve(move);
  }
}
References v8::internal::compiler::Instruction::FIRST_GAP_POSITION, v8::internal::compiler::Instruction::GetParallelMove(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::LAST_GAP_POSITION, v8::internal::compiler::GapResolver::Resolve(), and resolver().
Referenced by AssembleInstruction().
AssembleInstruction()
CodeGenerator::CodeGenResult v8::internal::compiler::CodeGenerator::AssembleInstruction (int instruction_index, const InstructionBlock * block) [private]
Definition at line 774 of file code-generator.cc.
                                                          {
  Instruction* instr = instructions()->InstructionAt(instruction_index);
  if (info()->trace_turbo_json()) {
    instr_starts_[instruction_index].gap_pc_offset = masm()->pc_offset();
  }
  int first_unused_stack_slot;
  FlagsMode mode = FlagsModeField::decode(instr->opcode());
  if (mode != kFlags_trap) {
    AssembleSourcePosition(instr);
  }
  bool adjust_stack =
      GetSlotAboveSPBeforeTailCall(instr, &first_unused_stack_slot);
  if (adjust_stack) AssembleTailCallBeforeGap(instr, first_unused_stack_slot);
  if (instr->opcode() == kArchNop && block->successors().empty() &&
      block->code_end() - block->code_start() == 1) {
    // When the frame-less dummy end block in Turbofan contains a Phi node,
    // don't attempt to access spill slots.
    // TODO(dmercadier): When the switch to Turboshaft is complete, this
    // will no longer be required.
  } else {
    AssembleGaps(instr);
  }
  if (adjust_stack) AssembleTailCallAfterGap(instr, first_unused_stack_slot);
  DCHECK_IMPLIES(
      block->must_deconstruct_frame(),
      instr != instructions()->InstructionAt(block->last_instruction_index()) ||
          instr->IsRet() || instr->IsJump());
  if (instr->IsJump() && block->must_deconstruct_frame()) {
    AssembleDeconstructFrame();
  }
  if (info()->trace_turbo_json()) {
    instr_starts_[instruction_index].arch_instr_pc_offset = masm()->pc_offset();
  }
  // Assemble architecture-specific code for the instruction.
  CodeGenResult result = AssembleArchInstruction(instr);
  if (result != kSuccess) return result;
  if (info()->trace_turbo_json()) {
    instr_starts_[instruction_index].condition_pc_offset = masm()->pc_offset();
  }
  FlagsCondition condition = FlagsConditionField::decode(instr->opcode());
  switch (mode) {
    case kFlags_branch:
    case kFlags_conditional_branch: {
      if (mode == kFlags_conditional_branch) {
        InstructionOperandConverter i(this, instr);
        condition = static_cast<FlagsCondition>(
            i.ToConstant(instr->InputAt(instr->InputCount() -
                                        kConditionalBranchEndOffsetOfCondition))
                .ToInt64());
      }
      BranchInfo branch;
      RpoNumber target = ComputeBranchInfo(&branch, condition, instr);
      if (target.IsValid()) {
        // redundant branch.
        if (!IsNextInAssemblyOrder(target)) {
          AssembleArchJump(target);
        }
        return kSuccess;
      }
      if (mode == kFlags_branch) {
        // Assemble architecture-specific branch.
        AssembleArchBranch(instr, &branch);
      } else {
        AssembleArchConditionalBranch(instr, &branch);
      }
      break;
    }
    case kFlags_deoptimize: {
      // Assemble a conditional eager deoptimization after this instruction.
      InstructionOperandConverter i(this, instr);
      size_t frame_state_offset =
          DeoptFrameStateOffsetField::decode(instr->opcode());
      size_t immediate_args_count =
          DeoptImmedArgsCountField::decode(instr->opcode());
      DeoptimizationExit* const exit = AddDeoptimizationExit(
          instr, frame_state_offset, immediate_args_count);
      BranchInfo branch;
      branch.condition = condition;
      branch.true_label = exit->label();
      branch.false_label = exit->continue_label();
      branch.hinted = true;
      branch.fallthru = true;
      AssembleArchDeoptBranch(instr, &branch);
      masm()->bind(exit->continue_label());
      break;
    }
    case kFlags_set: {
      // Assemble a boolean materialization after this instruction.
      AssembleArchBoolean(instr, condition);
      break;
    }
    case kFlags_conditional_set: {
      // Assemble a conditional boolean materialization after this instruction.
      AssembleArchConditionalBoolean(instr);
      break;
    }
    case kFlags_select: {
      AssembleArchSelect(instr, condition);
      break;
    }
    case kFlags_trap: {
#if V8_ENABLE_WEBASSEMBLY
      AssembleArchTrap(instr, condition);
      break;
#else
      UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
    }
    case kFlags_none: {
      break;
    }
  }
  return kSuccess;
}
References AddDeoptimizationExit(), AssembleArchBoolean(), AssembleArchBranch(), AssembleArchConditionalBoolean(), AssembleArchConditionalBranch(), AssembleArchDeoptBranch(), AssembleArchInstruction(), AssembleArchJump(), AssembleArchSelect(), AssembleDeconstructFrame(), AssembleGaps(), AssembleSourcePosition(), AssembleTailCallAfterGap(), AssembleTailCallBeforeGap(), v8::internal::Assembler::bind(), v8::internal::compiler::InstructionBlock::code_end(), v8::internal::compiler::InstructionBlock::code_start(), ComputeBranchInfo(), v8::internal::compiler::BranchInfo::condition, v8::internal::compiler::DeoptimizationExit::continue_label(), DCHECK_IMPLIES, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::BranchInfo::fallthru, v8::internal::compiler::BranchInfo::false_label, GetSlotAboveSPBeforeTailCall(), v8::internal::compiler::BranchInfo::hinted, v8::internal::anonymous_namespace{json-stringifier.cc}::i, info(), v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), instr_starts_, v8::internal::compiler::InstructionSequence::InstructionAt(), instructions(), v8::internal::compiler::Instruction::IsJump(), IsNextInAssemblyOrder(), v8::internal::compiler::Instruction::IsRet(), v8::internal::compiler::RpoNumber::IsValid(), v8::internal::compiler::kConditionalBranchEndOffsetOfCondition, v8::internal::compiler::kFlags_branch, v8::internal::compiler::kFlags_conditional_branch, v8::internal::compiler::kFlags_conditional_set, v8::internal::compiler::kFlags_deoptimize, v8::internal::compiler::kFlags_none, v8::internal::compiler::kFlags_select, v8::internal::compiler::kFlags_set, v8::internal::compiler::kFlags_trap, kSuccess, v8::internal::compiler::DeoptimizationExit::label(), v8::internal::compiler::InstructionBlock::last_instruction_index(), masm(), mode(), v8::internal::compiler::InstructionBlock::must_deconstruct_frame(), v8::internal::compiler::Instruction::opcode(), v8::internal::AssemblerBase::pc_offset(), v8::base::internal::result, v8::internal::compiler::InstructionBlock::successors(), v8::internal::compiler::BranchInfo::true_label, and v8::internal::UNREACHABLE().
Referenced by AssembleBlock().
AssembleJumpTable()
void v8::internal::compiler::CodeGenerator::AssembleJumpTable (base::Vector< Label * > targets) [private]
Definition at line 4503 of file code-generator-arm.cc.
                                                                {
  // On 32-bit ARM we emit the jump tables inline.
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by AssembleCode().
AssembleMove()
void v8::internal::compiler::CodeGenerator::AssembleMove (InstructionOperand * source, InstructionOperand * destination) [final], [private], [virtual]
Implements v8::internal::compiler::GapResolver::Assembler.
Definition at line 4061 of file code-generator-arm.cc.
                                                                  {
  ArmOperandConverter g(this, nullptr);
  // Helper function to write the given constant to the dst register.
  auto MoveConstantToRegister = [&](Register dst, Constant src) {
    if (src.type() == Constant::kHeapObject) {
      Handle<HeapObject> src_object = src.ToHeapObject();
      RootIndex index;
      if (IsMaterializableFromRoot(src_object, &index)) {
        __ LoadRoot(dst, index);
      } else {
        __ Move(dst, src_object);
      }
    } else if (src.type() == Constant::kExternalReference) {
      __ Move(dst, src.ToExternalReference());
    } else {
      __ mov(dst, g.ToImmediate(source));
    }
  };
  switch (MoveType::InferMove(source, destination)) {
    case MoveType::kRegisterToRegister:
      if (source->IsRegister()) {
        __ mov(g.ToRegister(destination), g.ToRegister(source));
      } else if (source->IsFloatRegister()) {
        DCHECK(destination->IsFloatRegister());
        // GapResolver may give us reg codes that don't map to actual
        // s-registers. Generate code to work around those cases.
        int src_code = LocationOperand::cast(source)->register_code();
        int dst_code = LocationOperand::cast(destination)->register_code();
        __ VmovExtended(dst_code, src_code);
      } else if (source->IsDoubleRegister()) {
        __ Move(g.ToDoubleRegister(destination), g.ToDoubleRegister(source));
      } else {
        __ Move(g.ToSimd128Register(destination), g.ToSimd128Register(source));
      }
      return;
    case MoveType::kRegisterToStack: {
      MemOperand dst = g.ToMemOperand(destination);
      if (source->IsRegister()) {
        __ str(g.ToRegister(source), dst);
      } else if (source->IsFloatRegister()) {
        // GapResolver may give us reg codes that don't map to actual
        // s-registers. Generate code to work around those cases.
        int src_code = LocationOperand::cast(source)->register_code();
        __ VmovExtended(dst, src_code);
      } else if (source->IsDoubleRegister()) {
        __ vstr(g.ToDoubleRegister(source), dst);
      } else {
        UseScratchRegisterScope temps(masm());
        Register temp = temps.Acquire();
        QwNeonRegister src = g.ToSimd128Register(source);
        __ add(temp, dst.rn(), Operand(dst.offset()));
        __ vst1(Neon8, NeonListOperand(src.low(), 2), NeonMemOperand(temp));
      }
      return;
    }
    case MoveType::kStackToRegister: {
      MemOperand src = g.ToMemOperand(source);
      if (source->IsStackSlot()) {
        __ ldr(g.ToRegister(destination), src);
      } else if (source->IsFloatStackSlot()) {
        DCHECK(destination->IsFloatRegister());
        // GapResolver may give us reg codes that don't map to actual
        // s-registers. Generate code to work around those cases.
        int dst_code = LocationOperand::cast(destination)->register_code();
        __ VmovExtended(dst_code, src);
      } else if (source->IsDoubleStackSlot()) {
        __ vldr(g.ToDoubleRegister(destination), src);
      } else {
        UseScratchRegisterScope temps(masm());
        Register temp = temps.Acquire();
        QwNeonRegister dst = g.ToSimd128Register(destination);
        __ add(temp, src.rn(), Operand(src.offset()));
        __ vld1(Neon8, NeonListOperand(dst.low(), 2), NeonMemOperand(temp));
      }
      return;
    }
    case MoveType::kStackToStack: {
      MemOperand src = g.ToMemOperand(source);
      MemOperand dst = g.ToMemOperand(destination);
      UseScratchRegisterScope temps(masm());
      if (source->IsStackSlot() || source->IsFloatStackSlot()) {
        SwVfpRegister temp = temps.AcquireS();
        __ vldr(temp, src);
        __ vstr(temp, dst);
      } else if (source->IsDoubleStackSlot()) {
        DwVfpRegister temp = temps.AcquireD();
        __ vldr(temp, src);
        __ vstr(temp, dst);
      } else {
        DCHECK(source->IsSimd128StackSlot());
        Register temp = temps.Acquire();
        QwNeonRegister temp_q = temps.AcquireQ();
        __ add(temp, src.rn(), Operand(src.offset()));
        __ vld1(Neon8, NeonListOperand(temp_q.low(), 2), NeonMemOperand(temp));
        __ add(temp, dst.rn(), Operand(dst.offset()));
        __ vst1(Neon8, NeonListOperand(temp_q.low(), 2), NeonMemOperand(temp));
      }
      return;
    }
    case MoveType::kConstantToRegister: {
      Constant src = g.ToConstant(source);
      if (destination->IsRegister()) {
        MoveConstantToRegister(g.ToRegister(destination), src);
      } else if (destination->IsFloatRegister()) {
        __ vmov(g.ToFloatRegister(destination),
                Float32::FromBits(src.ToFloat32AsInt()));
      } else {
        // TODO(arm): Look into optimizing this further if possible. Supporting
        // the NEON version of VMOV may help.
        __ vmov(g.ToDoubleRegister(destination), src.ToFloat64());
      }
      return;
    }
    case MoveType::kConstantToStack: {
      Constant src = g.ToConstant(source);
      MemOperand dst = g.ToMemOperand(destination);
      if (destination->IsStackSlot()) {
        UseScratchRegisterScope temps(masm());
        // Acquire a S register instead of a general purpose register in case
        // `vstr` needs one to compute the address of `dst`.
        SwVfpRegister s_temp = temps.AcquireS();
        {
          // TODO(arm): This sequence could be optimized further if necessary by
          // writing the constant directly into `s_temp`.
          UseScratchRegisterScope temps(masm());
          Register temp = temps.Acquire();
          MoveConstantToRegister(temp, src);
          __ vmov(s_temp, temp);
        }
        __ vstr(s_temp, dst);
      } else if (destination->IsFloatStackSlot()) {
        UseScratchRegisterScope temps(masm());
        SwVfpRegister temp = temps.AcquireS();
        __ vmov(temp, Float32::FromBits(src.ToFloat32AsInt()));
        __ vstr(temp, dst);
      } else {
        DCHECK(destination->IsDoubleStackSlot());
        UseScratchRegisterScope temps(masm());
        DwVfpRegister temp = temps.AcquireD();
        // TODO(arm): Look into optimizing this further if possible. Supporting
        // the NEON version of VMOV may help.
        __ vmov(temp, src.ToFloat64());
        __ vstr(temp, g.ToMemOperand(destination));
      }
      return;
    }
  }
  UNREACHABLE();
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::Float32::FromBits(), v8::internal::index, v8::internal::compiler::CodeGenerator::MoveType::InferMove(), v8::internal::compiler::InstructionOperand::IsDoubleRegister(), v8::internal::compiler::InstructionOperand::IsDoubleStackSlot(), v8::internal::compiler::InstructionOperand::IsFloatRegister(), v8::internal::compiler::InstructionOperand::IsFloatStackSlot(), IsMaterializableFromRoot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsSimd128StackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::CodeGenerator::MoveType::kConstantToRegister, v8::internal::compiler::CodeGenerator::MoveType::kConstantToStack, v8::internal::compiler::Constant::kExternalReference, v8::internal::compiler::Constant::kHeapObject, v8::internal::compiler::CodeGenerator::MoveType::kRegisterToRegister, v8::internal::compiler::CodeGenerator::MoveType::kRegisterToStack, v8::internal::compiler::CodeGenerator::MoveType::kStackToRegister, v8::internal::compiler::CodeGenerator::MoveType::kStackToStack, v8::internal::QwNeonRegister::low(), masm(), v8::internal::Neon8, v8::internal::MemOperand::offset(), v8::internal::compiler::LocationOperand::register_code(), v8::internal::MemOperand::rn(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister(), v8::internal::compiler::Constant::ToFloat32AsInt(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::InstructionOperandConverter::ToFloatRegister(), v8::internal::compiler::ArmOperandConverter::ToImmediate(), v8::internal::compiler::ArmOperandConverter::ToMemOperand(), v8::internal::compiler::InstructionOperandConverter::ToRegister(), v8::internal::compiler::InstructionOperandConverter::ToSimd128Register(), and v8::internal::UNREACHABLE().
Referenced by MoveTempLocationTo(), MoveToTempLocation(), Pop(), and Push().
AssemblePlaceHolderForLazyDeopt()
void v8::internal::compiler::CodeGenerator::AssemblePlaceHolderForLazyDeopt (Instruction * instr) [private]
Definition at line 1129 of file code-generator.cc.
                                                                      {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
AssemblePrepareTailCall()
void v8::internal::compiler::CodeGenerator::AssemblePrepareTailCall () [private]
Definition at line 509 of file code-generator-arm.cc.
                                            {
  if (frame_access_state()->has_frame()) {
    __ ldm(ia, fp, {lr, fp});
  }
  frame_access_state()->SetFrameAccessToSP();
}
References __, frame_access_state(), v8::internal::ia, and v8::internal::compiler::FrameAccessState::SetFrameAccessToSP().
Referenced by AssembleArchInstruction().
AssembleReturn()
void v8::internal::compiler::CodeGenerator::AssembleReturn (InstructionOperand * pop) [private]
Definition at line 3930 of file code-generator-arm.cc.
                                                                           {
  auto call_descriptor = linkage()->GetIncomingDescriptor();
  const int returns = frame()->GetReturnSlotCount();
  if (returns != 0) {
    // Free space of returns.
    __ add(sp, sp, Operand(returns * kSystemPointerSize));
  }
  // Restore registers.
  const RegList saves = call_descriptor->CalleeSavedRegisters();
  if (!saves.is_empty()) {
    __ ldm(ia_w, sp, saves);
  }
  // Restore FP registers.
  const DoubleRegList saves_fp = call_descriptor->CalleeSavedFPRegisters();
  if (!saves_fp.is_empty()) {
    static_assert(DwVfpRegister::kNumRegisters == 32);
    __ vldm(ia_w, sp, saves_fp.first(), saves_fp.last());
  }
  unwinding_info_writer_.MarkBlockWillExit();
  ArmOperandConverter g(this, nullptr);
  const int parameter_slots =
      static_cast<int>(call_descriptor->ParameterSlotCount());
  // {additional_pop_count} is only greater than zero if {parameter_slots = 0}.
  // Check RawMachineAssembler::PopAndReturn.
  if (parameter_slots != 0) {
    if (additional_pop_count->IsImmediate()) {
      DCHECK_EQ(g.ToConstant(additional_pop_count).ToInt32(), 0);
    } else if (v8_flags.debug_code) {
      __ cmp(g.ToRegister(additional_pop_count), Operand(0));
      __ Assert(eq, AbortReason::kUnexpectedAdditionalPopValue);
    }
  }
#if V8_ENABLE_WEBASSEMBLY
  if (call_descriptor->IsAnyWasmFunctionCall() &&
      v8_flags.experimental_wasm_growable_stacks) {
    {
      UseScratchRegisterScope temps{masm()};
      Register scratch = temps.Acquire();
      __ ldr(scratch, MemOperand(fp, TypedFrameConstants::kFrameTypeOffset));
      __ cmp(scratch,
             Operand(StackFrame::TypeToMarker(StackFrame::WASM_SEGMENT_START)));
    }
    Label done;
    __ b(&done, ne);
    RegList regs_to_save;
    for (auto reg : wasm::kGpReturnRegisters) regs_to_save.set(reg);
    __ stm(db_w, sp, regs_to_save);
    DoubleRegList fp_regs_to_save;
    for (auto reg : wasm::kFpParamRegisters) fp_regs_to_save.set(reg);
    __ vstm(db_w, sp, fp_regs_to_save.first(), fp_regs_to_save.last());
    __ Move(kCArgRegs[0], ExternalReference::isolate_address());
    __ PrepareCallCFunction(1);
    __ CallCFunction(ExternalReference::wasm_shrink_stack(), 1);
    // Restore old FP. We don't need to restore old SP explicitly, because
    // it will be restored from FP in LeaveFrame before return.
    __ mov(fp, kReturnRegister0);
    __ vldm(ia_w, sp, fp_regs_to_save.first(), fp_regs_to_save.last());
    __ ldm(ia_w, sp, regs_to_save);
    __ bind(&done);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  Register argc_reg = r3;
  // Functions with JS linkage have at least one parameter (the receiver).
  // If {parameter_slots} == 0, it means it is a builtin with
  // kDontAdaptArgumentsSentinel, which takes care of JS arguments popping
  // itself.
  const bool drop_jsargs = parameter_slots != 0 &&
                           frame_access_state()->has_frame() &&
                           call_descriptor->IsJSFunctionCall();
  if (call_descriptor->IsCFunctionCall()) {
    AssembleDeconstructFrame();
  } else if (frame_access_state()->has_frame()) {
    // Canonicalize JSFunction return sites for now unless they have an variable
    // number of stack slot pops.
    if (additional_pop_count->IsImmediate() &&
        g.ToConstant(additional_pop_count).ToInt32() == 0) {
      if (return_label_.is_bound()) {
        __ b(&return_label_);
        return;
      } else {
        __ bind(&return_label_);
      }
    }
    if (drop_jsargs) {
      // Get the actual argument count.
      __ ldr(argc_reg, MemOperand(fp, StandardFrameConstants::kArgCOffset));
      DCHECK(!call_descriptor->CalleeSavedRegisters().has(argc_reg));
    }
    AssembleDeconstructFrame();
  }
  if (drop_jsargs) {
    // We must pop all arguments from the stack (including the receiver).
    // The number of arguments without the receiver is
    // max(argc_reg, parameter_slots-1), and the receiver is added in
    // DropArguments().
    DCHECK(!call_descriptor->CalleeSavedRegisters().has(argc_reg));
    if (parameter_slots > 1) {
      __ cmp(argc_reg, Operand(parameter_slots));
      __ mov(argc_reg, Operand(parameter_slots), LeaveCC, lt);
    }
    __ DropArguments(argc_reg);
  } else if (additional_pop_count->IsImmediate()) {
    DCHECK_EQ(Constant::kInt32, g.ToConstant(additional_pop_count).type());
    int additional_count = g.ToConstant(additional_pop_count).ToInt32();
    __ Drop(parameter_slots + additional_count);
  } else if (parameter_slots == 0) {
    __ Drop(g.ToRegister(additional_pop_count));
  } else {
    // {additional_pop_count} is guaranteed to be zero if {parameter_slots !=
    // 0}. Check RawMachineAssembler::PopAndReturn.
    __ Drop(parameter_slots);
  }
  __ Ret();
}
References __, AssembleDeconstructFrame(), v8::internal::db_w, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::eq, v8::internal::RegListBase< RegisterT >::first(), frame(), frame_access_state(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::compiler::Frame::GetReturnSlotCount(), v8::internal::compiler::FrameAccessState::has_frame(), v8::internal::ia_w, v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::ExternalReference::isolate_address(), v8::internal::StandardFrameConstants::kArgCOffset, v8::internal::kCArgRegs, v8::internal::wasm::kFpParamRegisters, v8::internal::TypedFrameConstants::kFrameTypeOffset, v8::internal::wasm::kGpReturnRegisters, v8::internal::compiler::Constant::kInt32, v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::kNumRegisters, v8::internal::kReturnRegister0, v8::internal::kSystemPointerSize, v8::internal::RegListBase< RegisterT >::last(), v8::internal::LeaveCC, linkage(), v8::internal::lt, v8::internal::compiler::UnwindingInfoWriter::MarkBlockWillExit(), masm(), v8::internal::ne, return_label_, v8::internal::RegListBase< RegisterT >::set(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::InstructionOperandConverter::ToRegister(), v8::internal::compiler::Constant::type(), v8::internal::StackFrame::TypeToMarker(), unwinding_info_writer_, and v8::internal::v8_flags.
Referenced by AssembleArchInstruction().
AssembleSourcePosition() [1/2]
void v8::internal::compiler::CodeGenerator::AssembleSourcePosition (Instruction * instr)
Definition at line 893 of file code-generator.cc.
                                                             {
  SourcePosition source_position = SourcePosition::Unknown();
  if (instr->IsNop() && instr->AreMovesRedundant()) return;
  if (!instructions()->GetSourcePosition(instr, &source_position)) return;
  AssembleSourcePosition(source_position);
}
References v8::internal::compiler::Instruction::AreMovesRedundant(), v8::internal::wasm::GetSourcePosition(), instructions(), v8::internal::compiler::Instruction::IsNop(), and v8::internal::SourcePosition::Unknown().
Referenced by AssembleCode(), and AssembleInstruction().
AssembleSourcePosition() [2/2]
void v8::internal::compiler::CodeGenerator::AssembleSourcePosition (SourcePosition source_position)
Definition at line 900 of file code-generator.cc.
                                                                         {
  if (source_position == current_source_position_) return;
  current_source_position_ = source_position;
  if (!source_position.IsKnown()) return;
  source_position_table_builder_.AddPosition(masm()->pc_offset(),
                                             source_position, false);
  if (v8_flags.code_comments) {
    OptimizedCompilationInfo* info = this->info();
    if (!info->IsOptimizing()) {
#if V8_ENABLE_WEBASSEMBLY
      if (!info->IsWasm()) return;
#else
      return;
#endif // V8_ENABLE_WEBASSEMBLY
    }
    std::ostringstream buffer;
    buffer << "-- ";
    // Turbolizer only needs the source position, as it can reconstruct
    // the inlining stack from other information.
    if (info->trace_turbo_json() || !masm()->isolate() ||
        masm()->isolate()->concurrent_recompilation_enabled()) {
      buffer << source_position;
    } else {
      AllowGarbageCollection allocation;
      AllowHandleAllocation handles;
      AllowHandleDereference deref;
      buffer << source_position.InliningStack(masm()->isolate(), info);
    }
    buffer << " --";
    masm()->RecordComment(buffer.str().c_str(), SourceLocation());
  }
}
References v8::internal::SourcePositionTableBuilder::AddPosition(), current_source_position_, info(), v8::internal::SourcePosition::InliningStack(), v8::internal::SourcePosition::IsKnown(), isolate(), v8::internal::OptimizedCompilationInfo::IsOptimizing(), masm(), v8::internal::AssemblerBase::RecordComment(), source_position_table_builder_, and v8::internal::v8_flags.
AssembleSwap()
void v8::internal::compiler::CodeGenerator::AssembleSwap (InstructionOperand * source, InstructionOperand * destination) [final], [private], [virtual]
Implements v8::internal::compiler::GapResolver::Assembler.
Definition at line 4380 of file code-generator-arm.cc.
                                                                  {
  ArmOperandConverter g(this, nullptr);
  switch (MoveType::InferSwap(source, destination)) {
    case MoveType::kRegisterToRegister:
      if (source->IsRegister()) {
        __ Swap(g.ToRegister(source), g.ToRegister(destination));
      } else if (source->IsFloatRegister()) {
        DCHECK(destination->IsFloatRegister());
        // GapResolver may give us reg codes that don't map to actual
        // s-registers. Generate code to work around those cases.
        UseScratchRegisterScope temps(masm());
        LowDwVfpRegister temp = temps.AcquireLowD();
        int src_code = LocationOperand::cast(source)->register_code();
        int dst_code = LocationOperand::cast(destination)->register_code();
        __ VmovExtended(temp.low().code(), src_code);
        __ VmovExtended(src_code, dst_code);
        __ VmovExtended(dst_code, temp.low().code());
      } else if (source->IsDoubleRegister()) {
        __ Swap(g.ToDoubleRegister(source), g.ToDoubleRegister(destination));
      } else {
        __ Swap(g.ToSimd128Register(source), g.ToSimd128Register(destination));
      }
      return;
    case MoveType::kRegisterToStack: {
      MemOperand dst = g.ToMemOperand(destination);
      if (source->IsRegister()) {
        Register src = g.ToRegister(source);
        UseScratchRegisterScope temps(masm());
        SwVfpRegister temp = temps.AcquireS();
        __ vmov(temp, src);
        __ ldr(src, dst);
        __ vstr(temp, dst);
      } else if (source->IsFloatRegister()) {
        int src_code = LocationOperand::cast(source)->register_code();
        UseScratchRegisterScope temps(masm());
        LowDwVfpRegister temp = temps.AcquireLowD();
        __ VmovExtended(temp.low().code(), src_code);
        __ VmovExtended(src_code, dst);
        __ vstr(temp.low(), dst);
      } else if (source->IsDoubleRegister()) {
        UseScratchRegisterScope temps(masm());
        DwVfpRegister temp = temps.AcquireD();
        DwVfpRegister src = g.ToDoubleRegister(source);
        __ Move(temp, src);
        __ vldr(src, dst);
        __ vstr(temp, dst);
      } else {
        QwNeonRegister src = g.ToSimd128Register(source);
        UseScratchRegisterScope temps(masm());
        Register temp = temps.Acquire();
        QwNeonRegister temp_q = temps.AcquireQ();
        __ Move(temp_q, src);
        __ add(temp, dst.rn(), Operand(dst.offset()));
        __ vld1(Neon8, NeonListOperand(src.low(), 2), NeonMemOperand(temp));
        __ vst1(Neon8, NeonListOperand(temp_q.low(), 2), NeonMemOperand(temp));
      }
      return;
    }
    case MoveType::kStackToStack: {
      MemOperand src = g.ToMemOperand(source);
      MemOperand dst = g.ToMemOperand(destination);
      if (source->IsStackSlot() || source->IsFloatStackSlot()) {
        UseScratchRegisterScope temps(masm());
        SwVfpRegister temp_0 = temps.AcquireS();
        SwVfpRegister temp_1 = temps.AcquireS();
        __ vldr(temp_0, dst);
        __ vldr(temp_1, src);
        __ vstr(temp_0, src);
        __ vstr(temp_1, dst);
      } else if (source->IsDoubleStackSlot()) {
        UseScratchRegisterScope temps(masm());
        LowDwVfpRegister temp = temps.AcquireLowD();
        if (temps.CanAcquireD()) {
          DwVfpRegister temp_0 = temp;
          DwVfpRegister temp_1 = temps.AcquireD();
          __ vldr(temp_0, dst);
          __ vldr(temp_1, src);
          __ vstr(temp_0, src);
          __ vstr(temp_1, dst);
        } else {
          // We only have a single D register available. However, we can split
          // it into 2 S registers and swap the slots 32 bits at a time.
          MemOperand src0 = src;
          MemOperand dst0 = dst;
          MemOperand src1(src.rn(), src.offset() + kFloatSize);
          MemOperand dst1(dst.rn(), dst.offset() + kFloatSize);
          SwVfpRegister temp_0 = temp.low();
          SwVfpRegister temp_1 = temp.high();
          __ vldr(temp_0, dst0);
          __ vldr(temp_1, src0);
          __ vstr(temp_0, src0);
          __ vstr(temp_1, dst0);
          __ vldr(temp_0, dst1);
          __ vldr(temp_1, src1);
          __ vstr(temp_0, src1);
          __ vstr(temp_1, dst1);
        }
      } else {
        DCHECK(source->IsSimd128StackSlot());
        MemOperand src0 = src;
        MemOperand dst0 = dst;
        MemOperand src1(src.rn(), src.offset() + kDoubleSize);
        MemOperand dst1(dst.rn(), dst.offset() + kDoubleSize);
        UseScratchRegisterScope temps(masm());
        DwVfpRegister temp_0 = temps.AcquireD();
        DwVfpRegister temp_1 = temps.AcquireD();
        __ vldr(temp_0, dst0);
        __ vldr(temp_1, src0);
        __ vstr(temp_0, src0);
        __ vstr(temp_1, dst0);
        __ vldr(temp_0, dst1);
        __ vldr(temp_1, src1);
        __ vstr(temp_0, src1);
        __ vstr(temp_1, dst1);
      }
      return;
    }
    default:
      UNREACHABLE();
  }
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::UseScratchRegisterScope::AcquireLowD(), v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::UseScratchRegisterScope::CanAcquireD(), v8::internal::compiler::LocationOperand::cast(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::LowDwVfpRegister::high(), v8::internal::compiler::CodeGenerator::MoveType::InferSwap(), v8::internal::compiler::InstructionOperand::IsDoubleRegister(), v8::internal::compiler::InstructionOperand::IsDoubleStackSlot(), v8::internal::compiler::InstructionOperand::IsFloatRegister(), v8::internal::compiler::InstructionOperand::IsFloatStackSlot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsSimd128StackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kDoubleSize, v8::internal::kFloatSize, v8::internal::compiler::CodeGenerator::MoveType::kRegisterToRegister, v8::internal::compiler::CodeGenerator::MoveType::kRegisterToStack, v8::internal::compiler::CodeGenerator::MoveType::kStackToStack, v8::internal::LowDwVfpRegister::low(), v8::internal::QwNeonRegister::low(), masm(), v8::internal::Neon8, v8::internal::MemOperand::offset(), v8::internal::compiler::LocationOperand::register_code(), v8::internal::MemOperand::rn(), v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister(), v8::internal::compiler::ArmOperandConverter::ToMemOperand(), v8::internal::compiler::InstructionOperandConverter::ToRegister(), v8::internal::compiler::InstructionOperandConverter::ToSimd128Register(), and v8::internal::UNREACHABLE().
AssembleTailCallAfterGap()
void v8::internal::compiler::CodeGenerator::AssembleTailCallAfterGap (Instruction * instr, int first_unused_stack_slot) [private]
Definition at line 622 of file code-generator-arm.cc.
                                                                           {
  AdjustStackPointerForTailCall(masm(), frame_access_state(),
                                first_unused_slot_offset);
}
References v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::AdjustStackPointerForTailCall(), frame_access_state(), and masm().
Referenced by AssembleInstruction().
AssembleTailCallBeforeGap()
void v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap (Instruction * instr, int first_unused_stack_slot) [private]
Definition at line 586 of file code-generator-arm.cc.
                                                                            {
  ZoneVector<MoveOperands*> pushes(zone());
  GetPushCompatibleMoves(instr, kRegisterPush, &pushes);
  if (!pushes.empty() &&
      (LocationOperand::cast(pushes.back()->destination()).index() + 1 ==
       first_unused_slot_offset)) {
    ArmOperandConverter g(this, instr);
    ZoneVector<Register> pending_pushes(zone());
    for (auto move : pushes) {
      LocationOperand destination_location(
          LocationOperand::cast(move->destination()));
      InstructionOperand source(move->source());
      AdjustStackPointerForTailCall(
          masm(), frame_access_state(),
          destination_location.index() - pending_pushes.size(),
          &pending_pushes);
      // Pushes of non-register data types are not supported.
      DCHECK(source.IsRegister());
      LocationOperand source_location(LocationOperand::cast(source));
      pending_pushes.push_back(source_location.GetRegister());
      // TODO(arm): We can push more than 3 registers at once. Add support in
      // the macro-assembler for pushing a list of registers.
      if (pending_pushes.size() == 3) {
        FlushPendingPushRegisters(masm(), frame_access_state(),
                                  &pending_pushes);
      }
      move->Eliminate();
    }
    FlushPendingPushRegisters(masm(), frame_access_state(), &pending_pushes);
  }
  AdjustStackPointerForTailCall(masm(), frame_access_state(),
                                first_unused_slot_offset, nullptr, false);
}
References v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::AdjustStackPointerForTailCall(), v8::internal::ZoneVector< T >::back(), v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::FlushPendingPushRegisters(), frame_access_state(), GetPushCompatibleMoves(), v8::internal::compiler::LocationOperand::GetRegister(), v8::internal::compiler::LocationOperand::index(), v8::internal::compiler::InstructionOperand::IsRegister(), kRegisterPush, masm(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), and zone().
Referenced by AssembleInstruction().
BailoutIfDeoptimized()
void v8::internal::compiler::CodeGenerator::BailoutIfDeoptimized () [private]
Definition at line 650 of file code-generator-arm.cc.
{ __ BailoutIfDeoptimized(); }
References __.
Referenced by AssembleCode().
block_starts()
const ZoneVector<int>& v8::internal::compiler::CodeGenerator::block_starts () const [inline]
Definition at line 130 of file code-generator.h.
{ return block_starts_; }
BuildTranslation()
DeoptimizationExit * v8::internal::compiler::CodeGenerator::BuildTranslation (Instruction * instr, int pc_offset, size_t frame_state_offset, size_t immediate_args_count, OutputFrameStateCombine state_combine) [private]
Definition at line 1347 of file code-generator.cc.
                                                                        {
  DeoptimizationEntry const& entry =
      GetDeoptimizationEntry(instr, frame_state_offset);
  FrameStateDescriptor* const descriptor = entry.descriptor();
  frame_state_offset++;
  const int translation_index = translations_.BeginTranslation(
      static_cast<int>(descriptor->GetFrameCount()),
      static_cast<int>(descriptor->GetJSFrameCount()),
      entry.feedback().IsValid());
  if (entry.feedback().IsValid()) {
    DeoptimizationLiteral literal =
        DeoptimizationLiteral(entry.feedback().vector);
    int literal_id = DefineDeoptimizationLiteral(literal);
    translations_.AddUpdateFeedback(literal_id, entry.feedback().slot.ToInt());
  }
  InstructionOperandIterator iter(instr, frame_state_offset);
  BuildTranslationForFrameStateDescriptor(descriptor, &iter, state_combine);
  DeoptimizationExit* const exit = zone()->New<DeoptimizationExit>(
      current_source_position_, descriptor->bailout_id(), translation_index,
      pc_offset, entry.kind(), entry.reason(),
#ifdef DEBUG
      entry.node_id());
#else // DEBUG
      0);
#endif // DEBUG
  if (immediate_args_count != 0) {
    auto immediate_args = zone()->New<ZoneVector<ImmediateOperand*>>(zone());
    InstructionOperandIterator imm_iter(
        instr, frame_state_offset - immediate_args_count - 1);
    for (size_t i = 0; i < immediate_args_count; i++) {
      immediate_args->emplace_back(ImmediateOperand::cast(imm_iter.Advance()));
    }
    exit->set_immediate_args(immediate_args);
  }
  deoptimization_exits_.push_back(exit);
  return exit;
}
References v8::internal::FrameTranslationBuilder::AddUpdateFeedback(), v8::internal::compiler::FrameStateDescriptor::bailout_id(), v8::internal::FrameTranslationBuilder::BeginTranslation(), BuildTranslationForFrameStateDescriptor(), current_source_position_, DefineDeoptimizationLiteral(), deoptimization_exits_, v8::internal::compiler::DeoptimizationEntry::descriptor(), v8::internal::compiler::DeoptimizationEntry::feedback(), GetDeoptimizationEntry(), v8::internal::compiler::FrameStateDescriptor::GetFrameCount(), v8::internal::compiler::FrameStateDescriptor::GetJSFrameCount(), v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::compiler::DeoptimizationEntry::kind(), v8::internal::Zone::New(), v8::internal::compiler::DeoptimizationEntry::reason(), v8::internal::compiler::DeoptimizationExit::set_immediate_args(), v8::internal::compiler::FeedbackSource::slot, v8::internal::FeedbackSlot::ToInt(), translations_, v8::internal::compiler::FeedbackSource::vector, and zone().
Referenced by AddDeoptimizationExit(), AssembleArchInstruction(), and RecordDeoptInfo().
BuildTranslationForFrameStateDescriptor()
void v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor (FrameStateDescriptor * descriptor, InstructionOperandIterator * iter, OutputFrameStateCombine state_combine) [private]
Definition at line 1247 of file code-generator.cc.
                                           {
  // Outer-most state must be added to translation first.
  if (descriptor->outer_state() != nullptr) {
    BuildTranslationForFrameStateDescriptor(descriptor->outer_state(), iter,
                                            state_combine);
  }
  Handle<SharedFunctionInfo> shared_info;
  if (!descriptor->shared_info().ToHandle(&shared_info)) {
    if (!info()->has_shared_info()
#if V8_ENABLE_WEBASSEMBLY
        && descriptor->type() != compiler::FrameStateType::kLiftoffFunction
#endif
    ) {
      return; // Stub with no SharedFunctionInfo.
    }
    shared_info = info()->shared_info();
  }
  const BytecodeOffset bailout_id = descriptor->bailout_id();
  const int shared_info_id =
#if V8_ENABLE_WEBASSEMBLY
      shared_info.is_null()
          ? DefineDeoptimizationLiteral(DeoptimizationLiteral(uint64_t{0}))
          : DefineDeoptimizationLiteral(DeoptimizationLiteral(shared_info));
  CHECK_IMPLIES(shared_info.is_null(), v8_flags.wasm_deopt);
#else
      DefineDeoptimizationLiteral(DeoptimizationLiteral(shared_info));
#endif
  const unsigned int height =
      static_cast<unsigned int>(descriptor->GetHeight());
  switch (descriptor->type()) {
    case FrameStateType::kUnoptimizedFunction: {
      int bytecode_array_id = DefineProtectedDeoptimizationLiteral(
          descriptor->bytecode_array().ToHandleChecked());
      int return_offset = 0;
      int return_count = 0;
      if (!state_combine.IsOutputIgnored()) {
        return_offset = static_cast<int>(state_combine.GetOffsetToPokeAt());
        return_count = static_cast<int>(iter->instruction()->OutputCount());
      }
      translations_.BeginInterpretedFrame(bailout_id, shared_info_id,
                                          bytecode_array_id, height,
                                          return_offset, return_count);
      break;
    }
    case FrameStateType::kInlinedExtraArguments:
      translations_.BeginInlinedExtraArguments(
          shared_info_id, height,
          descriptor->bytecode_array().ToHandleChecked()->parameter_count());
      break;
    case FrameStateType::kConstructCreateStub:
      translations_.BeginConstructCreateStubFrame(shared_info_id, height);
      break;
    case FrameStateType::kConstructInvokeStub:
      translations_.BeginConstructInvokeStubFrame(shared_info_id);
      break;
    case FrameStateType::kBuiltinContinuation: {
      translations_.BeginBuiltinContinuationFrame(bailout_id, shared_info_id,
                                                  height);
      break;
    }
#if V8_ENABLE_WEBASSEMBLY
    case FrameStateType::kWasmInlinedIntoJS:
      translations_.BeginWasmInlinedIntoJSFrame(bailout_id, shared_info_id,
                                                height);
      break;
    case FrameStateType::kJSToWasmBuiltinContinuation: {
      const JSToWasmFrameStateDescriptor* js_to_wasm_descriptor =
          static_cast<const JSToWasmFrameStateDescriptor*>(descriptor);
      translations_.BeginJSToWasmBuiltinContinuationFrame(
          bailout_id, shared_info_id, height,
          js_to_wasm_descriptor->return_kind());
      break;
    }
    case FrameStateType::kLiftoffFunction:
      translations_.BeginLiftoffFrame(bailout_id, height,
                                      descriptor->GetWasmFunctionIndex());
      break;
#endif // V8_ENABLE_WEBASSEMBLY
    case FrameStateType::kJavaScriptBuiltinContinuation: {
      translations_.BeginJavaScriptBuiltinContinuationFrame(
          bailout_id, shared_info_id, height);
      break;
    }
    case FrameStateType::kJavaScriptBuiltinContinuationWithCatch: {
      translations_.BeginJavaScriptBuiltinContinuationWithCatchFrame(
          bailout_id, shared_info_id, height);
      break;
    }
  }
  TranslateFrameStateDescriptorOperands(descriptor, iter);
}
References v8::internal::compiler::FrameStateDescriptor::bailout_id(), v8::internal::FrameTranslationBuilder::BeginBuiltinContinuationFrame(), v8::internal::FrameTranslationBuilder::BeginConstructCreateStubFrame(), v8::internal::FrameTranslationBuilder::BeginConstructInvokeStubFrame(), v8::internal::FrameTranslationBuilder::BeginInlinedExtraArguments(), v8::internal::FrameTranslationBuilder::BeginInterpretedFrame(), v8::internal::FrameTranslationBuilder::BeginJavaScriptBuiltinContinuationFrame(), v8::internal::FrameTranslationBuilder::BeginJavaScriptBuiltinContinuationWithCatchFrame(), v8::internal::compiler::FrameStateDescriptor::bytecode_array(), CHECK_IMPLIES, DefineDeoptimizationLiteral(), DefineProtectedDeoptimizationLiteral(), v8::internal::compiler::FrameStateDescriptor::GetHeight(), v8::internal::compiler::OutputFrameStateCombine::GetOffsetToPokeAt(), v8::internal::compiler::FrameStateDescriptor::GetWasmFunctionIndex(), info(), v8::internal::compiler::InstructionOperandIterator::instruction(), v8::internal::HandleBase::is_null(), v8::internal::compiler::OutputFrameStateCombine::IsOutputIgnored(), v8::internal::compiler::kBuiltinContinuation, v8::internal::compiler::kConstructCreateStub, v8::internal::compiler::kConstructInvokeStub, v8::internal::compiler::kInlinedExtraArguments, v8::internal::compiler::kJavaScriptBuiltinContinuation, v8::internal::compiler::kJavaScriptBuiltinContinuationWithCatch, v8::internal::compiler::kUnoptimizedFunction, v8::internal::compiler::FrameStateDescriptor::outer_state(), v8::internal::compiler::Instruction::OutputCount(), v8::internal::OptimizedCompilationInfo::shared_info(), v8::internal::compiler::FrameStateDescriptor::shared_info(), TranslateFrameStateDescriptorOperands(), translations_, v8::internal::compiler::FrameStateDescriptor::type(), and v8::internal::v8_flags.
Referenced by BuildTranslation().
code_kind()
CodeKind v8::internal::compiler::CodeGenerator::code_kind () const [inline]
Definition at line 154 of file code-generator.h.
{ return info_->code_kind(); }
Referenced by DetermineStubCallMode(), and FinalizeCode().
ComputeBranchInfo()
RpoNumber v8::internal::compiler::CodeGenerator::ComputeBranchInfo (BranchInfo * branch, FlagsCondition condition, Instruction * instr) [private]
Definition at line 745 of file code-generator.cc.
                                                               {
  // Assemble a branch after this instruction.
  InstructionOperandConverter i(this, instr);
  RpoNumber true_rpo =
      i.InputRpo(instr->InputCount() - kBranchEndOffsetOfTrueBlock);
  RpoNumber false_rpo =
      i.InputRpo(instr->InputCount() - kBranchEndOffsetOfFalseBlock);
  if (true_rpo == false_rpo) {
    return true_rpo;
  }
  if (IsNextInAssemblyOrder(true_rpo) || instructions()
                                             ->InstructionBlockAt(false_rpo)
                                             ->IsLoopHeaderInAssemblyOrder()) {
    // true block is next, can fall through if condition negated.
    // false block is loop header, can save one jump if condition negated.
    std::swap(true_rpo, false_rpo);
    condition = NegateFlagsCondition(condition);
  }
  branch->condition = condition;
  branch->true_label = GetLabel(true_rpo);
  branch->false_label = GetLabel(false_rpo);
  branch->hinted = static_cast<bool>(BranchHintField::decode(instr->opcode()));
  branch->fallthru = IsNextInAssemblyOrder(false_rpo);
  return RpoNumber::Invalid();
}
References v8::internal::compiler::BranchInfo::condition, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::compiler::BranchInfo::fallthru, v8::internal::compiler::BranchInfo::false_label, GetLabel(), v8::internal::compiler::BranchInfo::hinted, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputCount(), instructions(), v8::internal::compiler::RpoNumber::Invalid(), IsNextInAssemblyOrder(), v8::internal::compiler::kBranchEndOffsetOfFalseBlock, v8::internal::compiler::kBranchEndOffsetOfTrueBlock, v8::internal::compiler::NegateFlagsCondition(), v8::internal::compiler::Instruction::opcode(), and v8::internal::compiler::BranchInfo::true_label.
Referenced by AssembleInstruction().
CreateFrameAccessState()
void v8::internal::compiler::CodeGenerator::CreateFrameAccessState (Frame * frame) [private]
Definition at line 120 of file code-generator.cc.
                                                       {
  FinishFrame(frame);
  frame_access_state_ = zone()->New<FrameAccessState>(frame);
}
References FinishFrame(), frame(), frame_access_state_, v8::internal::Zone::New(), and zone().
DefineDeoptimizationLiteral()
int v8::internal::compiler::CodeGenerator::DefineDeoptimizationLiteral (DeoptimizationLiteral literal) [private]
Definition at line 1180 of file code-generator.cc.
                                                                            {
  literal.Validate();
  unsigned i;
  for (i = 0; i < deoptimization_literals_.size(); ++i) {
    deoptimization_literals_[i].Validate();
    if (deoptimization_literals_[i] == literal) return i;
  }
  deoptimization_literals_.push_back(literal);
  return i;
}
References deoptimization_literals_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::DeoptimizationLiteral::Validate().
Referenced by AddTranslationForOperand(), AssembleCode(), BuildTranslation(), and BuildTranslationForFrameStateDescriptor().
DefineProtectedDeoptimizationLiteral()
int v8::internal::compiler::CodeGenerator::DefineProtectedDeoptimizationLiteral (IndirectHandle< TrustedObject > object) [private]
Definition at line 1170 of file code-generator.cc.
                                          {
  unsigned i;
  for (i = 0; i < protected_deoptimization_literals_.size(); ++i) {
    if (protected_deoptimization_literals_[i].equals(object)) return i;
  }
  protected_deoptimization_literals_.push_back(object);
  return i;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and protected_deoptimization_literals_.
Referenced by BuildTranslationForFrameStateDescriptor().
DetermineStubCallMode()
StubCallMode v8::internal::compiler::CodeGenerator::DetermineStubCallMode () const [private]
Definition at line 944 of file code-generator.cc.
                                                        {
#if V8_ENABLE_WEBASSEMBLY
  CodeKind code_kind = info()->code_kind();
  if (code_kind == CodeKind::WASM_FUNCTION) {
    return StubCallMode::kCallWasmRuntimeStub;
  }
  if (code_kind == CodeKind::WASM_TO_CAPI_FUNCTION ||
      code_kind == CodeKind::WASM_TO_JS_FUNCTION) {
    return StubCallMode::kCallBuiltinPointer;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return StubCallMode::kCallCodeObject;
}
References v8::internal::OptimizedCompilationInfo::code_kind(), code_kind(), info(), v8::internal::kCallBuiltinPointer, and v8::internal::kCallCodeObject.
Referenced by AssembleArchInstruction().
FinalizeCode()
MaybeHandle< Code > v8::internal::compiler::CodeGenerator::FinalizeCode ()
Definition at line 508 of file code-generator.cc.
                                              {
  if (result_ != kSuccess) {
    masm()->AbortedCodeGeneration();
    return {};
  }
  // Allocate the source position table.
  Handle<TrustedByteArray> source_positions =
      source_position_table_builder_.ToSourcePositionTable(isolate());
  // Allocate and install the code.
  CodeDesc desc;
  masm()->GetCode(isolate()->main_thread_local_isolate(), &desc, safepoints(),
                  handler_table_offset_);
#if defined(V8_OS_WIN64)
  if (Builtins::IsBuiltinId(info_->builtin())) {
    isolate_->SetBuiltinUnwindData(info_->builtin(), masm()->GetUnwindInfo());
  }
#endif // V8_OS_WIN64
  if (unwinding_info_writer_.eh_frame_writer()) {
    unwinding_info_writer_.eh_frame_writer()->GetEhFrame(&desc);
  }
  Factory::CodeBuilder builder(isolate(), desc, info()->code_kind());
  builder.set_builtin(info()->builtin())
      .set_inlined_bytecode_size(info()->inlined_bytecode_size())
      .set_parameter_count(parameter_count_)
      .set_source_position_table(source_positions)
      .set_is_turbofanned()
      .set_stack_slots(frame()->GetTotalFrameSlotCount())
      .set_profiler_data(info()->profiler_data())
      .set_osr_offset(info()->osr_offset());
  if (info()->function_context_specializing()) {
    builder.set_is_context_specialized();
  }
  if (CodeKindUsesDeoptimizationData(info()->code_kind())) {
    builder.set_deoptimization_data(GenerateDeoptimizationData());
    DCHECK(info()->has_bytecode_array() ||
           info()->code_kind() == CodeKind::WASM_FUNCTION);
  }
  MaybeHandle<Code> maybe_code = builder.TryBuild();
  Handle<Code> code;
  if (!maybe_code.ToHandle(&code)) {
    masm()->AbortedCodeGeneration();
    return {};
  }
  LOG_CODE_EVENT(isolate(), CodeLinePosInfoRecordEvent(
                                code->instruction_start(), *source_positions,
                                JitCodeEvent::JIT_CODE));
  return code;
}
References v8::internal::Assembler::AbortedCodeGeneration(), v8::internal::OptimizedCompilationInfo::builtin(), code, code_kind(), v8::internal::CodeKindUsesDeoptimizationData(), v8::internal::DCHECK(), v8::internal::compiler::UnwindingInfoWriter::eh_frame_writer(), frame(), GenerateDeoptimizationData(), v8::internal::Assembler::GetCode(), v8::internal::EhFrameWriter::GetEhFrame(), handler_table_offset_, info(), info_, v8::internal::Builtins::IsBuiltinId(), isolate(), isolate_, v8::JitCodeEvent::JIT_CODE, kSuccess, LOG_CODE_EVENT, masm(), parameter_count_, result_, safepoints(), v8::internal::Factory::CodeBuilder::set_builtin(), v8::internal::Factory::CodeBuilder::set_deoptimization_data(), v8::internal::Factory::CodeBuilder::set_inlined_bytecode_size(), v8::internal::Factory::CodeBuilder::set_is_context_specialized(), v8::internal::Factory::CodeBuilder::set_is_turbofanned(), v8::internal::Factory::CodeBuilder::set_osr_offset(), v8::internal::Factory::CodeBuilder::set_parameter_count(), v8::internal::Factory::CodeBuilder::set_profiler_data(), v8::internal::Factory::CodeBuilder::set_source_position_table(), v8::internal::Factory::CodeBuilder::set_stack_slots(), source_position_table_builder_, v8::internal::MaybeHandle< T >::ToHandle(), v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(), v8::internal::Factory::CodeBuilder::TryBuild(), and unwinding_info_writer_.
Referenced by v8::internal::compiler::turboshaft::FinalizeCodePhase::Run().
FinishCode()
void v8::internal::compiler::CodeGenerator::FinishCode () [private]
Definition at line 4054 of file code-generator-arm.cc.
{ __ CheckConstPool(true, false); }
References __.
Referenced by AssembleCode().
FinishFrame()
void v8::internal::compiler::CodeGenerator::FinishFrame (Frame * frame) [private]
Definition at line 3754 of file code-generator-arm.cc.
                                            {
  auto call_descriptor = linkage()->GetIncomingDescriptor();
  const DoubleRegList saves_fp = call_descriptor->CalleeSavedFPRegisters();
  if (!saves_fp.is_empty()) {
    frame->AlignSavedCalleeRegisterSlots();
  }
  if (!saves_fp.is_empty()) {
    // Save callee-saved FP registers.
    static_assert(DwVfpRegister::kNumRegisters == 32);
    uint32_t last = base::bits::CountLeadingZeros32(saves_fp.bits()) - 1;
    uint32_t first = base::bits::CountTrailingZeros32(saves_fp.bits());
    DCHECK_EQ((last - first + 1), saves_fp.Count());
    frame->AllocateSavedCalleeRegisterSlots((last - first + 1) *
                                            (kDoubleSize / kSystemPointerSize));
  }
  const RegList saves = call_descriptor->CalleeSavedRegisters();
  if (!saves.is_empty()) {
    // Save callee-saved registers.
    frame->AllocateSavedCalleeRegisterSlots(saves.Count());
  }
}
References v8::internal::compiler::Frame::AlignSavedCalleeRegisterSlots(), v8::internal::compiler::Frame::AllocateSavedCalleeRegisterSlots(), v8::internal::RegListBase< RegisterT >::bits(), v8::internal::RegListBase< RegisterT >::Count(), v8::base::bits::CountLeadingZeros32(), v8::base::bits::CountTrailingZeros32(), DCHECK_EQ, frame(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::kDoubleSize, v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::kNumRegisters, v8::internal::kSystemPointerSize, and linkage().
Referenced by CreateFrameAccessState().
frame()
const Frame* v8::internal::compiler::CodeGenerator::frame () const [inline]
Definition at line 105 of file code-generator.h.
{ return frame_access_state_->frame(); }
Referenced by AssembleArchInstruction(), AssembleCode(), AssembleConstructFrame(), AssembleReturn(), CreateFrameAccessState(), FinalizeCode(), FinishFrame(), v8::internal::compiler::InstructionOperandConverter::frame(), GetStackCheckOffset(), and RecordSafepoint().
frame_access_state()
FrameAccessState* v8::internal::compiler::CodeGenerator::frame_access_state () const [inline]
Definition at line 104 of file code-generator.h.
{ return frame_access_state_; }
Referenced by AssembleArchInstruction(), AssembleCode(), AssembleConstructFrame(), AssemblePrepareTailCall(), AssembleReturn(), AssembleTailCallAfterGap(), AssembleTailCallBeforeGap(), v8::internal::compiler::InstructionOperandConverter::frame_access_state(), GetStackCheckOffset(), Pop(), PopTempStackSlots(), and Push().
GenerateDeoptimizationData()
Handle< DeoptimizationData > v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData () [private]
Definition at line 985 of file code-generator.cc.
                                                                     {
  OptimizedCompilationInfo* info = this->info();
  int deopt_count = static_cast<int>(deoptimization_exits_.size());
  if (deopt_count == 0 && !info->is_osr()) {
    return DeoptimizationData::Empty(isolate());
  }
  Handle<DeoptimizationData> data =
      DeoptimizationData::New(isolate(), deopt_count);
  DirectHandle<DeoptimizationFrameTranslation> translation_array =
      translations_.ToFrameTranslation(
          isolate()->main_thread_local_isolate()->factory());
  data->SetFrameTranslation(*translation_array);
  data->SetInlinedFunctionCount(
      Smi::FromInt(static_cast<int>(inlined_function_count_)));
  data->SetOptimizationId(Smi::FromInt(info->optimization_id()));
  data->SetDeoptExitStart(Smi::FromInt(deopt_exit_start_offset_));
  data->SetEagerDeoptCount(Smi::FromInt(eager_deopt_count_));
  data->SetLazyDeoptCount(Smi::FromInt(lazy_deopt_count_));
  if (info->has_shared_info()) {
    DirectHandle<SharedFunctionInfoWrapper> sfi_wrapper =
        isolate()->factory()->NewSharedFunctionInfoWrapper(info->shared_info());
    data->SetWrappedSharedFunctionInfo(*sfi_wrapper);
  } else {
    data->SetWrappedSharedFunctionInfo(Smi::zero());
  }
  DirectHandle<ProtectedDeoptimizationLiteralArray> protected_literals =
      isolate()->factory()->NewProtectedFixedArray(
          static_cast<int>(protected_deoptimization_literals_.size()));
  for (unsigned i = 0; i < protected_deoptimization_literals_.size(); i++) {
    IndirectHandle<TrustedObject> object =
        protected_deoptimization_literals_[i];
    CHECK(!object.is_null());
    protected_literals->set(i, *object);
  }
  data->SetProtectedLiteralArray(*protected_literals);
  DirectHandle<DeoptimizationLiteralArray> literals =
      isolate()->factory()->NewDeoptimizationLiteralArray(
          static_cast<int>(deoptimization_literals_.size()));
  for (unsigned i = 0; i < deoptimization_literals_.size(); i++) {
    DirectHandle<Object> object = deoptimization_literals_[i].Reify(isolate());
    CHECK(!object.is_null());
    literals->set(i, *object);
  }
  data->SetLiteralArray(*literals);
  DirectHandle<TrustedPodArray<InliningPosition>> inl_pos =
      CreateInliningPositions(info, isolate());
  data->SetInliningPositions(*inl_pos);
  if (info->is_osr()) {
    DCHECK_LE(0, osr_pc_offset_);
    data->SetOsrBytecodeOffset(Smi::FromInt(info_->osr_offset().ToInt()));
    data->SetOsrPcOffset(Smi::FromInt(osr_pc_offset_));
  } else {
    BytecodeOffset osr_offset = BytecodeOffset::None();
    data->SetOsrBytecodeOffset(Smi::FromInt(osr_offset.ToInt()));
    data->SetOsrPcOffset(Smi::FromInt(-1));
  }
  // Populate deoptimization entries.
  for (int i = 0; i < deopt_count; i++) {
    DeoptimizationExit* deoptimization_exit = deoptimization_exits_[i];
    CHECK_NOT_NULL(deoptimization_exit);
    DCHECK_EQ(i, deoptimization_exit->deoptimization_id());
    data->SetBytecodeOffset(i, deoptimization_exit->bailout_id());
    data->SetTranslationIndex(
        i, Smi::FromInt(deoptimization_exit->translation_id()));
    data->SetPc(i, Smi::FromInt(deoptimization_exit->pc_offset()));
#ifdef DEBUG
    data->SetNodeId(i, Smi::FromInt(deoptimization_exit->node_id()));
#endif // DEBUG
  }
#ifdef DEBUG
  data->Verify(info->bytecode_array());
#endif // DEBUG
  return data;
}
References v8::internal::compiler::DeoptimizationExit::bailout_id(), v8::internal::OptimizedCompilationInfo::bytecode_array(), CHECK, CHECK_NOT_NULL, v8::internal::compiler::anonymous_namespace{code-generator.cc}::CreateInliningPositions(), DCHECK_EQ, DCHECK_LE, deopt_exit_start_offset_, deoptimization_exits_, v8::internal::compiler::DeoptimizationExit::deoptimization_id(), deoptimization_literals_, eager_deopt_count_, v8::internal::DeoptimizationData::Empty(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::OptimizedCompilationInfo::has_shared_info(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, info(), info_, inlined_function_count_, v8::internal::OptimizedCompilationInfo::is_osr(), isolate(), lazy_deopt_count_, v8::internal::DeoptimizationData::New(), v8::internal::FactoryBase< Impl >::NewDeoptimizationLiteralArray(), v8::internal::FactoryBase< Impl >::NewProtectedFixedArray(), v8::internal::FactoryBase< Impl >::NewSharedFunctionInfoWrapper(), v8::internal::compiler::DeoptimizationExit::node_id(), v8::internal::BytecodeOffset::None(), v8::internal::OptimizedCompilationInfo::optimization_id(), v8::internal::OptimizedCompilationInfo::osr_offset(), osr_pc_offset_, v8::internal::compiler::DeoptimizationExit::pc_offset(), protected_deoptimization_literals_, v8::internal::OptimizedCompilationInfo::shared_info(), v8::internal::FrameTranslationBuilder::ToFrameTranslation(), v8::internal::BytecodeOffset::ToInt(), v8::internal::compiler::DeoptimizationExit::translation_id(), translations_, and v8::internal::Smi::zero().
Referenced by FinalizeCode().
GetDeoptimizationEntry()
DeoptimizationEntry const & v8::internal::compiler::CodeGenerator::GetDeoptimizationEntry (Instruction * instr, size_t frame_state_offset) [private]
Definition at line 1199 of file code-generator.cc.
                                                   {
  InstructionOperandConverter i(this, instr);
  int const state_id = i.InputInt32(frame_state_offset);
  return instructions()->GetDeoptimizationEntry(state_id);
}
References v8::internal::compiler::InstructionSequence::GetDeoptimizationEntry(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and instructions().
Referenced by BuildTranslation(), and RecordDeoptInfo().
GetLabel()
Label* v8::internal::compiler::CodeGenerator::GetLabel (RpoNumber rpo) [inline]
Definition at line 109 of file code-generator.h.
{ return &labels_[rpo.ToSize()]; }
References v8::internal::compiler::RpoNumber::ToSize().
Referenced by AssembleArchBinarySearchSwitch(), AssembleArchJumpRegardlessOfAssemblyOrder(), AssembleArchTableSwitch(), AssembleCode(), ComputeBranchInfo(), RecordCallPosition(), and v8::internal::compiler::InstructionOperandConverter::ToLabel().
GetProtectedInstructionsData()
base::OwnedVector< uint8_t > v8::internal::compiler::CodeGenerator::GetProtectedInstructionsData ()
Definition at line 499 of file code-generator.cc.
                                                                     {
#if V8_ENABLE_WEBASSEMBLY
  return base::OwnedCopyOf(
      base::Vector<uint8_t>::cast(base::VectorOf(protected_instructions_)));
#else
  return {};
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::base::OwnedCopyOf(), and v8::base::VectorOf().
GetPushCompatibleMoves()
void v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves (Instruction * instr, PushTypeFlags push_type, ZoneVector< MoveOperands * > * pushes) [static], [private]
Definition at line 638 of file code-generator.cc.
                                                                              {
  static constexpr int first_push_compatible_index =
      kReturnAddressStackSlotCount;
  pushes->clear();
  for (int i = Instruction::FIRST_GAP_POSITION;
       i <= Instruction::LAST_GAP_POSITION; ++i) {
    Instruction::GapPosition inner_pos =
        static_cast<Instruction::GapPosition>(i);
    ParallelMove* parallel_move = instr->GetParallelMove(inner_pos);
    if (parallel_move != nullptr) {
      for (auto move : *parallel_move) {
        InstructionOperand source = move->source();
        InstructionOperand destination = move->destination();
        // If there are any moves from slots that will be overridden by pushes,
        // then the full gap resolver must be used since optimization with
        // pushes don't participate in the parallel move and might clobber
        // values needed for the gap resolve.
        if (source.IsAnyStackSlot() && LocationOperand::cast(source).index() >=
                                           first_push_compatible_index) {
          pushes->clear();
          return;
        }
        // TODO(danno): Right now, only consider moves from the FIRST gap for
        // pushes. Theoretically, we could extract pushes for both gaps (there
        // are cases where this happens), but the logic for that would also have
        // to check to make sure that non-memory inputs to the pushes from the
        // LAST gap don't get clobbered in the FIRST gap.
        if (i == Instruction::FIRST_GAP_POSITION) {
          if (destination.IsStackSlot() &&
              LocationOperand::cast(destination).index() >=
                  first_push_compatible_index) {
            int index = LocationOperand::cast(destination).index();
            if (IsValidPush(source, push_type)) {
              if (index >= static_cast<int>(pushes->size())) {
                pushes->resize(index + 1);
              }
              (*pushes)[index] = move;
            }
          }
        }
      }
    }
  }
  // For now, only support a set of continuous pushes at the end of the list.
  size_t push_count_upper_bound = pushes->size();
  size_t push_begin = push_count_upper_bound;
  for (auto move : base::Reversed(*pushes)) {
    if (move == nullptr) break;
    push_begin--;
  }
  size_t push_count = pushes->size() - push_begin;
  std::copy(pushes->begin() + push_begin,
            pushes->begin() + push_begin + push_count, pushes->begin());
  pushes->resize(push_count);
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::LocationOperand::cast(), v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::Instruction::FIRST_GAP_POSITION, v8::internal::compiler::Instruction::GetParallelMove(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::LocationOperand::index(), v8::internal::index, v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), IsValidPush(), kReturnAddressStackSlotCount, v8::internal::compiler::Instruction::LAST_GAP_POSITION, v8::internal::ZoneVector< T >::resize(), v8::base::Reversed(), and v8::internal::ZoneVector< T >::size().
Referenced by AssembleTailCallBeforeGap().
GetSlotAboveSPBeforeTailCall()
bool v8::internal::compiler::CodeGenerator::GetSlotAboveSPBeforeTailCall (Instruction * instr, int * slot) [private]
Definition at line 933 of file code-generator.cc.
                                                            {
  if (instr->IsTailCall()) {
    InstructionOperandConverter g(this, instr);
    *slot = g.InputInt32(instr->InputCount() - 1);
    return true;
  } else {
    return false;
  }
}
References v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::InstructionOperandConverter::InputInt32(), and v8::internal::compiler::Instruction::IsTailCall().
Referenced by AssembleInstruction().
GetSourcePositionTable()
base::OwnedVector< uint8_t > v8::internal::compiler::CodeGenerator::GetSourcePositionTable ()
Definition at line 495 of file code-generator.cc.
                                                               {
  return source_position_table_builder_.ToSourcePositionTableVector();
}
References source_position_table_builder_, and v8::internal::SourcePositionTableBuilder::ToSourcePositionTableVector().
GetStackCheckOffset()
uint32_t v8::internal::compiler::CodeGenerator::GetStackCheckOffset ()
Definition at line 137 of file code-generator.cc.
                                            {
  if (!frame_access_state()->has_frame()) {
    DCHECK_EQ(max_unoptimized_frame_height_, 0);
    DCHECK_EQ(max_pushed_argument_count_, 0);
    return 0;
  }
  size_t incoming_parameter_count =
      linkage_->GetIncomingDescriptor()->ParameterSlotCount();
  DCHECK(is_int32(incoming_parameter_count));
  int32_t optimized_frame_height =
      static_cast<int32_t>(incoming_parameter_count) * kSystemPointerSize +
      frame()->GetTotalFrameSlotCount() * kSystemPointerSize;
  DCHECK(is_int32(max_unoptimized_frame_height_));
  int32_t signed_max_unoptimized_frame_height =
      static_cast<int32_t>(max_unoptimized_frame_height_);
  // The offset is either the delta between the optimized frames and the
  // interpreted frame, or the maximal number of bytes pushed to the stack
  // while preparing for function calls, whichever is bigger.
  uint32_t frame_height_delta = static_cast<uint32_t>(std::max(
      signed_max_unoptimized_frame_height - optimized_frame_height, 0));
  uint32_t max_pushed_argument_bytes =
      static_cast<uint32_t>(max_pushed_argument_count_ * kSystemPointerSize);
  return std::max(frame_height_delta, max_pushed_argument_bytes);
}
References v8::internal::DCHECK(), DCHECK_EQ, frame(), frame_access_state(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::compiler::Frame::GetTotalFrameSlotCount(), v8::internal::kSystemPointerSize, linkage_, max_pushed_argument_count_, max_unoptimized_frame_height_, and v8::internal::compiler::CallDescriptor::ParameterSlotCount().
Referenced by AssembleArchInstruction(), and ShouldApplyOffsetToStackCheck().
handler_table_offset()
size_t v8::internal::compiler::CodeGenerator::handler_table_offset () const [inline]
Definition at line 128 of file code-generator.h.
{ return handler_table_offset_; }
HasProtectedDeoptimizationLiteral()
bool v8::internal::compiler::CodeGenerator::HasProtectedDeoptimizationLiteral (IndirectHandle< TrustedObject > object) const [private]
Definition at line 1191 of file code-generator.cc.
                                                {
  for (unsigned i = 0; i < protected_deoptimization_literals_.size(); ++i) {
    if (protected_deoptimization_literals_[i].equals(object)) return true;
  }
  return false;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and protected_deoptimization_literals_.
IncrementStackAccessCounter()
void v8::internal::compiler::CodeGenerator::IncrementStackAccessCounter (InstructionOperand * source, InstructionOperand * destination) [private]
Definition at line 8036 of file code-generator-x64.cc.
                                                                 {
  DCHECK(v8_flags.trace_turbo_stack_accesses);
  if (!info()->IsOptimizing()) {
#if V8_ENABLE_WEBASSEMBLY
    if (!info()->IsWasm()) return;
#else
    return;
#endif // V8_ENABLE_WEBASSEMBLY
  }
  DCHECK_NOT_NULL(debug_name_);
  auto IncrementCounter = [&](ExternalReference counter) {
    __ incl(__ ExternalReferenceAsOperand(counter));
  };
  if (source->IsAnyStackSlot()) {
    IncrementCounter(
        ExternalReference::address_of_load_from_stack_count(debug_name_));
  }
  if (destination->IsAnyStackSlot()) {
    IncrementCounter(
        ExternalReference::address_of_store_to_stack_count(debug_name_));
  }
}
References __, v8::internal::ExternalReference::address_of_load_from_stack_count(), v8::internal::ExternalReference::address_of_store_to_stack_count(), v8::internal::DCHECK(), DCHECK_NOT_NULL, debug_name_, info(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), and v8::internal::v8_flags.
info()
OptimizedCompilationInfo* v8::internal::compiler::CodeGenerator::info () const [inline], [private]
Definition at line 159 of file code-generator.h.
{ return info_; }
Referenced by AddTranslationForOperand(), AssembleCode(), AssembleConstructFrame(), AssembleDeoptimizerCall(), AssembleInstruction(), AssembleSourcePosition(), BuildTranslationForFrameStateDescriptor(), v8::internal::compiler::anonymous_namespace{code-generator.cc}::CreateInliningPositions(), DetermineStubCallMode(), FinalizeCode(), GenerateDeoptimizationData(), and IncrementStackAccessCounter().
instr_starts()
const ZoneVector<TurbolizerInstructionStartInfo>& v8::internal::compiler::CodeGenerator::instr_starts () const [inline]
Definition at line 131 of file code-generator.h.
                                                                         {
    return instr_starts_;
  }
instructions()
InstructionSequence* v8::internal::compiler::CodeGenerator::instructions () const [inline]
Definition at line 103 of file code-generator.h.
{ return instructions_; }
Referenced by AssembleCode(), AssembleInstruction(), AssembleSourcePosition(), ComputeBranchInfo(), GetDeoptimizationEntry(), IsNextInAssemblyOrder(), RecordCallPosition(), and v8::internal::compiler::InstructionOperandConverter::ToConstant().
IsMaterializableFromRoot()
bool v8::internal::compiler::CodeGenerator::IsMaterializableFromRoot (Handle< HeapObject > object, RootIndex * index_return) [private]
Definition at line 598 of file code-generator.cc.
                                                                      {
  const CallDescriptor* incoming_descriptor =
      linkage()->GetIncomingDescriptor();
  if (incoming_descriptor->flags() & CallDescriptor::kCanUseRoots) {
    return isolate()->roots_table().IsRootHandle(object, index_return) &&
           RootsTable::IsImmortalImmovable(*index_return);
  }
  return false;
}
References v8::internal::compiler::CallDescriptor::flags(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::RootsTable::IsImmortalImmovable(), isolate(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::CallDescriptor::kCanUseRoots, linkage(), and v8::internal::Isolate::roots_table().
Referenced by AssembleMove().
IsNextInAssemblyOrder()
bool v8::internal::compiler::CodeGenerator::IsNextInAssemblyOrder (RpoNumber block) const [private]
Definition at line 568 of file code-generator.cc.
                                                               {
  return instructions()
      ->InstructionBlockAt(current_block_)
      ->ao_number()
      .IsNext(instructions()->InstructionBlockAt(block)->ao_number());
}
References v8::internal::compiler::InstructionBlock::ao_number(), current_block_, v8::internal::compiler::InstructionSequence::InstructionBlockAt(), instructions(), and v8::internal::compiler::RpoNumber::IsNext().
Referenced by AssembleArchJump(), AssembleInstruction(), and ComputeBranchInfo().
isolate()
Isolate* v8::internal::compiler::CodeGenerator::isolate () const [inline]
Definition at line 106 of file code-generator.h.
{ return isolate_; }
Referenced by AddTranslationForOperand(), AssembleArchInstruction(), AssembleSourcePosition(), v8::internal::compiler::anonymous_namespace{code-generator.cc}::CreateInliningPositions(), FinalizeCode(), GenerateDeoptimizationData(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), IsMaterializableFromRoot(), v8::internal::compiler::InstructionOperandConverter::isolate(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), and v8::internal::compiler::X64OperandConverter::ToImmediate().
IsValidPush()
bool v8::internal::compiler::CodeGenerator::IsValidPush (InstructionOperand source, CodeGenerator::PushTypeFlags push_type) [static], [private]
Definition at line 621 of file code-generator.cc.
                                                                      {
  if (source.IsImmediate() &&
      ((push_type & CodeGenerator::kImmediatePush) != 0)) {
    return true;
  }
  if (source.IsRegister() &&
      ((push_type & CodeGenerator::kRegisterPush) != 0)) {
    return true;
  }
  if (source.IsStackSlot() &&
      ((push_type & CodeGenerator::kStackSlotPush) != 0)) {
    return true;
  }
  return false;
}
References v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), kImmediatePush, kRegisterPush, and kStackSlotPush.
Referenced by GetPushCompatibleMoves().
linkage()
Linkage* v8::internal::compiler::CodeGenerator::linkage () const [inline]
Definition at line 107 of file code-generator.h.
{ return linkage_; }
Referenced by AssembleArchInstruction(), AssembleCode(), AssembleConstructFrame(), AssembleReturn(), FinishFrame(), IsMaterializableFromRoot(), and v8::internal::compiler::InstructionOperandConverter::linkage().
masm()
MacroAssembler* v8::internal::compiler::CodeGenerator::masm () [inline]
Definition at line 126 of file code-generator.h.
{ return &masm_; }
Referenced by AssembleArchBinarySearchSwitchRange(), AssembleArchInstruction(), AssembleBlock(), AssembleCode(), AssembleCodeStartRegisterCheck(), v8::internal::compiler::AssembleConditionalCompareChain(), AssembleConstructFrame(), AssembleDeoptimizerCall(), AssembleInstruction(), AssembleMove(), AssembleReturn(), AssembleSourcePosition(), AssembleSwap(), AssembleTailCallAfterGap(), AssembleTailCallBeforeGap(), FinalizeCode(), MaybeEmitOutOfLineConstantPool(), v8::internal::compiler::IA32OperandConverter::MoveInstructionOperandToRegister(), MoveToTempLocation(), Pop(), Push(), RecordCallPosition(), RecordSafepoint(), and SetPendingMove().
MaybeEmitOutOfLineConstantPool()
void v8::internal::compiler::CodeGenerator::MaybeEmitOutOfLineConstantPool () [private]
Definition at line 199 of file code-generator.cc.
                                                   {
  masm()->MaybeEmitOutOfLineConstantPool();
}
References masm(), and v8::internal::Assembler::MaybeEmitOutOfLineConstantPool().
MoveTempLocationTo()
void v8::internal::compiler::CodeGenerator::MoveTempLocationTo (InstructionOperand * dst, MachineRepresentation rep) [final], [private], [virtual]
Implements v8::internal::compiler::GapResolver::Assembler.
Definition at line 4317 of file code-generator-arm.cc.
                                                                  {
  int scratch_reg_code = move_cycle_.scratch_reg_code;
  DCHECK(move_cycle_.temps.has_value());
  if (scratch_reg_code != -1) {
    if (IsFloatingPoint(rep)) {
      AllocatedOperand scratch(LocationOperand::REGISTER, rep,
                               scratch_reg_code);
      AssembleMove(&scratch, dest);
    } else {
      AllocatedOperand scratch(LocationOperand::REGISTER,
                               MachineRepresentation::kFloat32,
                               scratch_reg_code);
      ArmOperandConverter g(this, nullptr);
      if (dest->IsStackSlot()) {
        __ vstr(g.ToFloatRegister(&scratch), g.ToMemOperand(dest));
      } else {
        DCHECK(dest->IsRegister());
        __ vmov(g.ToRegister(dest), g.ToFloatRegister(&scratch));
      }
    }
  } else {
    Pop(dest, rep);
  }
  // Restore the default state to release the {UseScratchRegisterScope} and to
  // prepare for the next cycle.
  move_cycle_ = MoveCycleState();
}
References __, AssembleMove(), v8::internal::DCHECK(), v8::internal::IsFloatingPoint(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kFloat32, move_cycle_, Pop(), v8::internal::compiler::LocationOperand::REGISTER, v8::internal::MoveCycleState::scratch_reg_code, v8::internal::MoveCycleState::temps, v8::internal::compiler::InstructionOperandConverter::ToFloatRegister(), v8::internal::compiler::ArmOperandConverter::ToMemOperand(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
MoveToTempLocation()
void v8::internal::compiler::CodeGenerator::MoveToTempLocation (InstructionOperand * src, MachineRepresentation rep) [final], [private], [virtual]
Implements v8::internal::compiler::GapResolver::Assembler.
Definition at line 4274 of file code-generator-arm.cc.
                                                                  {
  // Must be kept in sync with {MoveTempLocationTo}.
  move_cycle_.temps.emplace(masm());
  auto& temps = *move_cycle_.temps;
  // Temporarily exclude the reserved scratch registers while we pick a
  // location to resolve the cycle. Re-include them immediately afterwards so
  // that they are available to assemble the move.
  temps.Exclude(move_cycle_.scratch_v_reglist);
  int reg_code = -1;
  if ((!IsFloatingPoint(rep) || rep == MachineRepresentation::kFloat32) &&
      temps.CanAcquireS()) {
    reg_code = temps.AcquireS().code();
  } else if (rep == MachineRepresentation::kFloat64 && temps.CanAcquireD()) {
    reg_code = temps.AcquireD().code();
  } else if (rep == MachineRepresentation::kSimd128 && temps.CanAcquireQ()) {
    reg_code = temps.AcquireQ().code();
  }
  temps.Include(move_cycle_.scratch_v_reglist);
  if (reg_code != -1) {
    // A scratch register is available for this rep.
    move_cycle_.scratch_reg_code = reg_code;
    if (IsFloatingPoint(rep)) {
      AllocatedOperand scratch(LocationOperand::REGISTER, rep, reg_code);
      AssembleMove(source, &scratch);
    } else {
      AllocatedOperand scratch(LocationOperand::REGISTER,
                               MachineRepresentation::kFloat32, reg_code);
      ArmOperandConverter g(this, nullptr);
      if (source->IsStackSlot()) {
        __ vldr(g.ToFloatRegister(&scratch), g.ToMemOperand(source));
      } else {
        DCHECK(source->IsRegister());
        __ vmov(g.ToFloatRegister(&scratch), g.ToRegister(source));
      }
    }
  } else {
    // The scratch registers are blocked by pending moves. Use the stack
    // instead.
    Push(source);
  }
}
References __, AssembleMove(), v8::internal::DCHECK(), v8::internal::IsFloatingPoint(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kSimd128, masm(), move_cycle_, Push(), v8::internal::compiler::LocationOperand::REGISTER, v8::internal::MoveCycleState::scratch_reg_code, v8::internal::MoveCycleState::scratch_v_reglist, v8::internal::MoveCycleState::temps, v8::internal::compiler::InstructionOperandConverter::ToFloatRegister(), v8::internal::compiler::ArmOperandConverter::ToMemOperand(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
offsets_info()
const TurbolizerCodeOffsetsInfo& v8::internal::compiler::CodeGenerator::offsets_info () const [inline]
Definition at line 135 of file code-generator.h.
                                                        {
    return offsets_info_;
  }
osr_helper()
OsrHelper* v8::internal::compiler::CodeGenerator::osr_helper () [inline], [private]
Definition at line 160 of file code-generator.h.
{ return &(*osr_helper_); }
Referenced by AssembleConstructFrame().
Pop()
void v8::internal::compiler::CodeGenerator::Pop (InstructionOperand * src, MachineRepresentation rep) [final], [private], [virtual]
Implements v8::internal::compiler::GapResolver::Assembler.
Definition at line 4241 of file code-generator-arm.cc.
                                                                           {
  int dropped_slots = ElementSizeInPointers(rep);
  ArmOperandConverter g(this, nullptr);
  if (dest->IsRegister()) {
    frame_access_state()->IncreaseSPDelta(-dropped_slots);
    __ pop(g.ToRegister(dest));
  } else if (dest->IsStackSlot()) {
    frame_access_state()->IncreaseSPDelta(-dropped_slots);
    UseScratchRegisterScope temps(masm());
    Register scratch = temps.Acquire();
    __ pop(scratch);
    __ str(scratch, g.ToMemOperand(dest));
  } else {
    int last_frame_slot_id =
        frame_access_state_->frame()->GetTotalFrameSlotCount() - 1;
    int sp_delta = frame_access_state_->sp_delta();
    int slot_id = last_frame_slot_id + sp_delta;
    AllocatedOperand stack_slot(LocationOperand::STACK_SLOT, rep, slot_id);
    AssembleMove(&stack_slot, dest);
    frame_access_state()->IncreaseSPDelta(-dropped_slots);
    __ add(sp, sp, Operand(dropped_slots * kSystemPointerSize));
  }
  temp_slots_ -= dropped_slots;
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), AssembleMove(), v8::internal::ElementSizeInPointers(), v8::internal::compiler::FrameAccessState::frame(), frame_access_state(), frame_access_state_, v8::internal::compiler::Frame::GetTotalFrameSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kSystemPointerSize, masm(), v8::internal::compiler::FrameAccessState::sp_delta(), v8::internal::compiler::LocationOperand::STACK_SLOT, v8::internal::compiler::GapResolver::Assembler::temp_slots_, v8::internal::compiler::ArmOperandConverter::ToMemOperand(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
Referenced by AssembleArchInstruction(), and MoveTempLocationTo().
PopTempStackSlots()
void v8::internal::compiler::CodeGenerator::PopTempStackSlots () [final], [private], [virtual]
Implements v8::internal::compiler::GapResolver::Assembler.
Definition at line 4266 of file code-generator-arm.cc.
                                      {
  if (temp_slots_ > 0) {
    frame_access_state()->IncreaseSPDelta(-temp_slots_);
    __ add(sp, sp, Operand(temp_slots_ * kSystemPointerSize));
    temp_slots_ = 0;
  }
}
References __, frame_access_state(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::kSystemPointerSize, and v8::internal::compiler::GapResolver::Assembler::temp_slots_.
PrepareForDeoptimizationExits()
void v8::internal::compiler::CodeGenerator::PrepareForDeoptimizationExits (ZoneDeque< DeoptimizationExit * > * exits) [private]
Definition at line 4056 of file code-generator-arm.cc.
                                           {
  __ CheckConstPool(true, false);
}
References __.
Referenced by AssembleCode().
Push()
AllocatedOperand v8::internal::compiler::CodeGenerator::Push (InstructionOperand * src) [final], [private], [virtual]
Implements v8::internal::compiler::GapResolver::Assembler.
Definition at line 4212 of file code-generator-arm.cc.
                                                               {
  auto rep = LocationOperand::cast(source)->representation();
  int new_slots = ElementSizeInPointers(rep);
  ArmOperandConverter g(this, nullptr);
  int last_frame_slot_id =
      frame_access_state_->frame()->GetTotalFrameSlotCount() - 1;
  int sp_delta = frame_access_state_->sp_delta();
  int slot_id = last_frame_slot_id + sp_delta + new_slots;
  AllocatedOperand stack_slot(LocationOperand::STACK_SLOT, rep, slot_id);
  if (source->IsRegister()) {
    __ push(g.ToRegister(source));
    frame_access_state()->IncreaseSPDelta(new_slots);
  } else if (source->IsStackSlot()) {
    UseScratchRegisterScope temps(masm());
    Register scratch = temps.Acquire();
    __ ldr(scratch, g.ToMemOperand(source));
    __ push(scratch);
    frame_access_state()->IncreaseSPDelta(new_slots);
  } else {
    // No push instruction for this operand type. Bump the stack pointer and
    // assemble the move.
    __ sub(sp, sp, Operand(new_slots * kSystemPointerSize));
    frame_access_state()->IncreaseSPDelta(new_slots);
    AssembleMove(source, &stack_slot);
  }
  temp_slots_ += new_slots;
  return stack_slot;
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), AssembleMove(), v8::internal::compiler::LocationOperand::cast(), v8::internal::ElementSizeInPointers(), v8::internal::compiler::FrameAccessState::frame(), frame_access_state(), frame_access_state_, v8::internal::compiler::Frame::GetTotalFrameSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kSystemPointerSize, masm(), v8::internal::wasm::liftoff::push(), v8::internal::compiler::LocationOperand::representation(), v8::internal::compiler::FrameAccessState::sp_delta(), v8::internal::compiler::LocationOperand::STACK_SLOT, v8::internal::compiler::GapResolver::Assembler::temp_slots_, v8::internal::compiler::ArmOperandConverter::ToMemOperand(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
Referenced by AssembleArchInstruction(), AssembleConstructFrame(), and MoveToTempLocation().
RecordCallPosition()
void v8::internal::compiler::CodeGenerator::RecordCallPosition (Instruction * instr) [private]
Definition at line 1134 of file code-generator.cc.
                                                         {
  const bool needs_frame_state =
      instr->HasCallDescriptorFlag(CallDescriptor::kNeedsFrameState);
  RecordSafepoint(instr->reference_map());
  if (instr->HasCallDescriptorFlag(CallDescriptor::kHasExceptionHandler)) {
    InstructionOperandConverter i(this, instr);
    Constant handler_input =
        i.ToConstant(instr->InputAt(instr->InputCount() - 1));
    if (handler_input.type() == Constant::Type::kRpoNumber) {
      RpoNumber handler_rpo = handler_input.ToRpoNumber();
      DCHECK(instructions()->InstructionBlockAt(handler_rpo)->IsHandler());
      handlers_.push_back(
          {GetLabel(handler_rpo), masm()->pc_offset_for_safepoint()});
    } else {
      // We should lazy deopt on throw.
      DCHECK_EQ(handler_input.ToInt32(), kLazyDeoptOnThrowSentinel);
      handlers_.push_back({nullptr, masm()->pc_offset_for_safepoint()});
    }
  }
  if (needs_frame_state) {
    RecordDeoptInfo(instr, masm()->pc_offset_for_safepoint());
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, GetLabel(), handlers_, v8::internal::compiler::Instruction::HasCallDescriptorFlag(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), instructions(), v8::internal::compiler::CallDescriptor::kHasExceptionHandler, v8::internal::compiler::kLazyDeoptOnThrowSentinel, v8::internal::compiler::CallDescriptor::kNeedsFrameState, masm(), v8::internal::Assembler::pc_offset_for_safepoint(), RecordDeoptInfo(), RecordSafepoint(), v8::internal::compiler::Instruction::reference_map(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToRpoNumber(), and v8::internal::compiler::Constant::type().
Referenced by AssembleArchInstruction().
RecordDeoptInfo()
void v8::internal::compiler::CodeGenerator::RecordDeoptInfo (Instruction * instr, int pc_offset) [private]
Definition at line 1160 of file code-generator.cc.
                                                                     {
  // If the frame state is present, it starts at argument 1 - after
  // the code address.
  size_t frame_state_offset = 1;
  FrameStateDescriptor* descriptor =
      GetDeoptimizationEntry(instr, frame_state_offset).descriptor();
  BuildTranslation(instr, pc_offset, frame_state_offset, 0,
                   descriptor->state_combine());
}
References BuildTranslation(), v8::internal::compiler::DeoptimizationEntry::descriptor(), GetDeoptimizationEntry(), and v8::internal::compiler::FrameStateDescriptor::state_combine().
Referenced by AssembleArchInstruction(), and RecordCallPosition().
RecordProtectedInstruction()
void v8::internal::compiler::CodeGenerator::RecordProtectedInstruction (uint32_t instr_offset)
Definition at line 114 of file code-generator.cc.
                                                                    {
#if V8_ENABLE_WEBASSEMBLY
  protected_instructions_.push_back({instr_offset});
#endif // V8_ENABLE_WEBASSEMBLY
}
RecordSafepoint()
void v8::internal::compiler::CodeGenerator::RecordSafepoint (ReferenceMap * references, int pc_offset = 0)
Definition at line 575 of file code-generator.cc.
                                                                           {
  auto safepoint = safepoints()->DefineSafepoint(masm(), pc_offset);
  for (int tagged : frame()->tagged_slots()) {
    safepoint.DefineTaggedStackSlot(tagged);
  }
  int frame_header_offset = frame()->GetFixedSlotCount();
  for (const InstructionOperand& operand : references->reference_operands()) {
    if (operand.IsStackSlot()) {
      int index = LocationOperand::cast(operand).index();
      DCHECK_LE(0, index);
      // We might index values in the fixed part of the frame (i.e. the
      // closure pointer or the context pointer); these are not spill slots
      // and therefore don't work with the SafepointTable currently, but
      // we also don't need to worry about them, since the GC has special
      // knowledge about those fields anyway.
      if (index < frame_header_offset) continue;
      safepoint.DefineTaggedStackSlot(index);
    }
  }
}
References v8::internal::compiler::LocationOperand::cast(), DCHECK_LE, v8::internal::SafepointTableBuilder::DefineSafepoint(), v8::internal::SafepointTableBuilder::Safepoint::DefineTaggedStackSlot(), frame(), v8::internal::compiler::Frame::GetFixedSlotCount(), v8::internal::compiler::LocationOperand::index(), v8::internal::index, masm(), v8::internal::compiler::ReferenceMap::reference_operands(), and safepoints().
Referenced by AssembleArchInstruction(), AssembleConstructFrame(), and RecordCallPosition().
resolver()
GapResolver* v8::internal::compiler::CodeGenerator::resolver () [inline], [private]
Definition at line 157 of file code-generator.h.
{ return &resolver_; }
Referenced by AssembleGaps().
safepoint_table_builder()
SafepointTableBuilder* v8::internal::compiler::CodeGenerator::safepoint_table_builder () [inline]
Definition at line 127 of file code-generator.h.
{ return &safepoints_; }
safepoints()
SafepointTableBuilder* v8::internal::compiler::CodeGenerator::safepoints () [inline], [private]
Definition at line 158 of file code-generator.h.
{ return &safepoints_; }
Referenced by AssembleCode(), FinalizeCode(), and RecordSafepoint().
SetPendingMove()
void v8::internal::compiler::CodeGenerator::SetPendingMove (MoveOperands * move) [final], [private], [virtual]
Implements v8::internal::compiler::GapResolver::Assembler.
Definition at line 4346 of file code-generator-arm.cc.
                                                     {
  InstructionOperand& source = move->source();
  InstructionOperand& destination = move->destination();
  MoveType::Type move_type =
      MoveType::InferMove(&move->source(), &move->destination());
  UseScratchRegisterScope temps(masm());
  if (move_type == MoveType::kStackToStack) {
    if (source.IsStackSlot() || source.IsFloatStackSlot()) {
      SwVfpRegister temp = temps.AcquireS();
      move_cycle_.scratch_v_reglist |= temp.ToVfpRegList();
    } else if (source.IsDoubleStackSlot()) {
      DwVfpRegister temp = temps.AcquireD();
      move_cycle_.scratch_v_reglist |= temp.ToVfpRegList();
    } else {
      QwNeonRegister temp = temps.AcquireQ();
      move_cycle_.scratch_v_reglist |= temp.ToVfpRegList();
    }
    return;
  } else if (move_type == MoveType::kConstantToStack) {
    if (destination.IsStackSlot()) {
      // Acquire a S register instead of a general purpose register in case
      // `vstr` needs one to compute the address of `dst`.
      SwVfpRegister s_temp = temps.AcquireS();
      move_cycle_.scratch_v_reglist |= s_temp.ToVfpRegList();
    } else if (destination.IsFloatStackSlot()) {
      SwVfpRegister temp = temps.AcquireS();
      move_cycle_.scratch_v_reglist |= temp.ToVfpRegList();
    } else {
      DwVfpRegister temp = temps.AcquireD();
      move_cycle_.scratch_v_reglist |= temp.ToVfpRegList();
    }
  }
}
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::compiler::MoveOperands::destination(), v8::internal::compiler::CodeGenerator::MoveType::InferMove(), v8::internal::compiler::InstructionOperand::IsDoubleStackSlot(), v8::internal::compiler::InstructionOperand::IsFloatStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::CodeGenerator::MoveType::kConstantToStack, v8::internal::compiler::CodeGenerator::MoveType::kStackToStack, masm(), move_cycle_, v8::internal::MoveCycleState::scratch_v_reglist, v8::internal::compiler::MoveOperands::source(), v8::internal::SwVfpRegister::ToVfpRegList(), v8::internal::DwVfpRegister::ToVfpRegList(), and v8::internal::QwNeonRegister::ToVfpRegList().
ShouldApplyOffsetToStackCheck()
bool v8::internal::compiler::CodeGenerator::ShouldApplyOffsetToStackCheck (Instruction * instr, uint32_t * offset)
Definition at line 125 of file code-generator.cc.
                                                                    {
  DCHECK_EQ(instr->arch_opcode(), kArchStackPointerGreaterThan);
  StackCheckKind kind =
      static_cast<StackCheckKind>(StackCheckField::decode(instr->opcode()));
  if (kind != StackCheckKind::kJSFunctionEntry) return false;
  uint32_t stack_check_offset = *offset = GetStackCheckOffset();
  return stack_check_offset > kStackLimitSlackForDeoptimizationInBytes;
}
References v8::internal::compiler::Instruction::arch_opcode(), DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), GetStackCheckOffset(), v8::internal::compiler::kJSFunctionEntry, v8::internal::kStackLimitSlackForDeoptimizationInBytes, and v8::internal::compiler::Instruction::opcode().
Referenced by AssembleArchInstruction(), and v8::internal::compiler::AssembleBranchToLabels().
start_source_position()
SourcePosition v8::internal::compiler::CodeGenerator::start_source_position () const [inline]
Definition at line 113 of file code-generator.h.
                                               {
    return start_source_position_;
  }
Referenced by AssembleCode().
TranslateFrameStateDescriptorOperands()
void v8::internal::compiler::CodeGenerator::TranslateFrameStateDescriptorOperands (FrameStateDescriptor * desc, InstructionOperandIterator * iter) [private]
Definition at line 1236 of file code-generator.cc.
                                                                  {
  size_t index = 0;
  StateValueList* values = desc->GetStateValueDescriptors();
  for (StateValueList::iterator it = values->begin(); it != values->end();
       ++it, ++index) {
    TranslateStateValueDescriptor((*it).desc, (*it).nested, iter);
  }
  DCHECK_EQ(desc->GetSize(), index);
}
References v8::internal::compiler::StateValueList::begin(), DCHECK_EQ, v8::internal::compiler::StateValueList::end(), v8::internal::compiler::FrameStateDescriptor::GetSize(), v8::internal::compiler::FrameStateDescriptor::GetStateValueDescriptors(), v8::internal::index, and TranslateStateValueDescriptor().
Referenced by BuildTranslationForFrameStateDescriptor().
TranslateStateValueDescriptor()
void v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor (StateValueDescriptor * desc, StateValueList * nested, InstructionOperandIterator * iter) [private]
Definition at line 1206 of file code-generator.cc.
                                      {
  if (desc->IsNestedObject()) {
    translations_.BeginCapturedObject(static_cast<int>(nested->size()));
    for (auto field : *nested) {
      TranslateStateValueDescriptor(field.desc, field.nested, iter);
    }
  } else if (desc->IsArgumentsElements()) {
    translations_.ArgumentsElements(desc->arguments_type());
  } else if (desc->IsArgumentsLength()) {
    translations_.ArgumentsLength();
  } else if (desc->IsRestLength()) {
    translations_.RestLength();
  } else if (desc->IsDuplicate()) {
    translations_.DuplicateObject(static_cast<int>(desc->id()));
  } else if (desc->IsPlain()) {
    InstructionOperand* op = iter->Advance();
    AddTranslationForOperand(iter->instruction(), op, desc->type());
  } else if (desc->IsStringConcat()) {
    translations_.StringConcat();
    for (auto field : *nested) {
      TranslateStateValueDescriptor(field.desc, field.nested, iter);
    }
  } else {
    DCHECK(desc->IsOptimizedOut());
    translations_.StoreOptimizedOut();
  }
}
References AddTranslationForOperand(), v8::internal::compiler::InstructionOperandIterator::Advance(), v8::internal::compiler::StateValueDescriptor::arguments_type(), v8::internal::FrameTranslationBuilder::ArgumentsElements(), v8::internal::FrameTranslationBuilder::ArgumentsLength(), v8::internal::FrameTranslationBuilder::BeginCapturedObject(), v8::internal::DCHECK(), v8::internal::FrameTranslationBuilder::DuplicateObject(), v8::internal::compiler::StateValueDescriptor::id(), v8::internal::compiler::InstructionOperandIterator::instruction(), v8::internal::compiler::StateValueDescriptor::IsArgumentsElements(), v8::internal::compiler::StateValueDescriptor::IsArgumentsLength(), v8::internal::compiler::StateValueDescriptor::IsDuplicate(), v8::internal::compiler::StateValueDescriptor::IsNestedObject(), v8::internal::compiler::StateValueDescriptor::IsOptimizedOut(), v8::internal::compiler::StateValueDescriptor::IsPlain(), v8::internal::compiler::StateValueDescriptor::IsRestLength(), v8::internal::compiler::StateValueDescriptor::IsStringConcat(), v8::internal::FrameTranslationBuilder::RestLength(), v8::internal::compiler::StateValueList::size(), v8::internal::FrameTranslationBuilder::StoreOptimizedOut(), v8::internal::FrameTranslationBuilder::StringConcat(), translations_, and v8::internal::compiler::StateValueDescriptor::type().
Referenced by TranslateFrameStateDescriptorOperands().
zone()
Zone* v8::internal::compiler::CodeGenerator::zone () const [inline]
Definition at line 125 of file code-generator.h.
{ return zone_; }
Referenced by AddJumpTable(), AssembleArchInstruction(), AssembleConstructFrame(), AssembleTailCallBeforeGap(), BuildTranslation(), and CreateFrameAccessState().
Friends And Related Function Documentation
CodeGeneratorTester
friend class CodeGeneratorTester [friend]
Definition at line 404 of file code-generator.h.
OutOfLineCode
friend class OutOfLineCode [friend]
Definition at line 403 of file code-generator.h.
Member Data Documentation
block_starts_
ZoneVector<int> v8::internal::compiler::CodeGenerator::block_starts_ [private]
Definition at line 472 of file code-generator.h.
Referenced by AssembleCode().
caller_registers_saved_
bool v8::internal::compiler::CodeGenerator::caller_registers_saved_ [private]
Definition at line 460 of file code-generator.h.
Referenced by AssembleArchInstruction().
current_block_
RpoNumber v8::internal::compiler::CodeGenerator::current_block_ [private]
Definition at line 415 of file code-generator.h.
Referenced by AssembleCode(), and IsNextInAssemblyOrder().
current_source_position_
SourcePosition v8::internal::compiler::CodeGenerator::current_source_position_ [private]
Definition at line 417 of file code-generator.h.
Referenced by AssembleSourcePosition(), and BuildTranslation().
debug_name_
const char* v8::internal::compiler::CodeGenerator::debug_name_ = nullptr [private]
Definition at line 477 of file code-generator.h.
Referenced by IncrementStackAccessCounter().
deopt_exit_start_offset_
int v8::internal::compiler::CodeGenerator::deopt_exit_start_offset_ = 0 [private]
Definition at line 423 of file code-generator.h.
Referenced by AssembleCode(), and GenerateDeoptimizationData().
deoptimization_exits_
ZoneDeque<DeoptimizationExit*> v8::internal::compiler::CodeGenerator::deoptimization_exits_ [private]
Definition at line 426 of file code-generator.h.
Referenced by AssembleCode(), BuildTranslation(), and GenerateDeoptimizationData().
deoptimization_literals_
ZoneDeque<DeoptimizationLiteral> v8::internal::compiler::CodeGenerator::deoptimization_literals_ [private]
Definition at line 428 of file code-generator.h.
Referenced by AssembleCode(), DefineDeoptimizationLiteral(), and GenerateDeoptimizationData().
eager_deopt_count_
int v8::internal::compiler::CodeGenerator::eager_deopt_count_ = 0 [private]
Definition at line 424 of file code-generator.h.
Referenced by AssembleDeoptimizerCall(), and GenerateDeoptimizationData().
fp_mode_
SaveFPRegsMode v8::internal::compiler::CodeGenerator::fp_mode_ [private]
Definition at line 461 of file code-generator.h.
Referenced by AssembleArchInstruction().
frame_access_state_
FrameAccessState* v8::internal::compiler::CodeGenerator::frame_access_state_ [private]
Definition at line 408 of file code-generator.h.
Referenced by CreateFrameAccessState(), Pop(), and Push().
handler_table_offset_
int v8::internal::compiler::CodeGenerator::handler_table_offset_ = 0 [private]
Definition at line 431 of file code-generator.h.
Referenced by AssembleCode(), and FinalizeCode().
handlers_
ZoneVector<HandlerInfo> v8::internal::compiler::CodeGenerator::handlers_ [private]
Definition at line 421 of file code-generator.h.
Referenced by AssembleArchInstruction(), AssembleCode(), and RecordCallPosition().
info_
OptimizedCompilationInfo* const v8::internal::compiler::CodeGenerator::info_ [private]
Definition at line 412 of file code-generator.h.
Referenced by AddTranslationForOperand(), FinalizeCode(), and GenerateDeoptimizationData().
inlined_function_count_
size_t v8::internal::compiler::CodeGenerator::inlined_function_count_ = 0 [private]
Definition at line 429 of file code-generator.h.
Referenced by AssembleCode(), and GenerateDeoptimizationData().
instr_starts_
ZoneVector<TurbolizerInstructionStartInfo> v8::internal::compiler::CodeGenerator::instr_starts_ [private]
Definition at line 474 of file code-generator.h.
Referenced by AssembleCode(), and AssembleInstruction().
instructions_
InstructionSequence* const v8::internal::compiler::CodeGenerator::instructions_ [private]
Definition at line 410 of file code-generator.h.
isolate_
Isolate* v8::internal::compiler::CodeGenerator::isolate_ [private]
Definition at line 407 of file code-generator.h.
Referenced by FinalizeCode().
jump_deoptimization_entry_labels_
Label v8::internal::compiler::CodeGenerator::jump_deoptimization_entry_labels_[kDeoptimizeKindCount] [private]
Definition at line 439 of file code-generator.h.
Referenced by AssembleDeoptimizerCall().
jump_tables_
JumpTable* v8::internal::compiler::CodeGenerator::jump_tables_ [private]
Definition at line 463 of file code-generator.h.
Referenced by AddJumpTable(), and AssembleCode().
kBinarySearchSwitchMinimalCases
constexpr int v8::internal::compiler::CodeGenerator::kBinarySearchSwitchMinimalCases = 4 [static], [constexpr]
Definition at line 143 of file code-generator.h.
Referenced by AssembleArchBinarySearchSwitchRange().
labels_
Label* const v8::internal::compiler::CodeGenerator::labels_ [private]
Definition at line 413 of file code-generator.h.
lazy_deopt_count_
int v8::internal::compiler::CodeGenerator::lazy_deopt_count_ = 0 [private]
Definition at line 425 of file code-generator.h.
Referenced by AssembleDeoptimizerCall(), and GenerateDeoptimizationData().
linkage_
Linkage* const v8::internal::compiler::CodeGenerator::linkage_ [private]
Definition at line 409 of file code-generator.h.
Referenced by GetStackCheckOffset().
masm_
MacroAssembler v8::internal::compiler::CodeGenerator::masm_ [private]
Definition at line 418 of file code-generator.h.
max_pushed_argument_count_
const size_t v8::internal::compiler::CodeGenerator::max_pushed_argument_count_ [private]
Definition at line 445 of file code-generator.h.
Referenced by GetStackCheckOffset().
max_unoptimized_frame_height_
const size_t v8::internal::compiler::CodeGenerator::max_unoptimized_frame_height_ [private]
Definition at line 444 of file code-generator.h.
Referenced by GetStackCheckOffset().
move_cycle_
MoveCycleState v8::internal::compiler::CodeGenerator::move_cycle_ [private]
Definition at line 475 of file code-generator.h.
Referenced by MoveTempLocationTo(), MoveToTempLocation(), and SetPendingMove().
next_deoptimization_id_
int v8::internal::compiler::CodeGenerator::next_deoptimization_id_ = 0 [private]
Definition at line 422 of file code-generator.h.
Referenced by AssembleCode().
offsets_info_
TurbolizerCodeOffsetsInfo v8::internal::compiler::CodeGenerator::offsets_info_ [private]
Definition at line 473 of file code-generator.h.
Referenced by AssembleCode().
ools_
OutOfLineCode* v8::internal::compiler::CodeGenerator::ools_ [private]
Definition at line 464 of file code-generator.h.
Referenced by AssembleCode(), and v8::internal::compiler::OutOfLineCode::OutOfLineCode().
osr_helper_
std::optional<OsrHelper> v8::internal::compiler::CodeGenerator::osr_helper_ [private]
Definition at line 465 of file code-generator.h.
osr_pc_offset_
int v8::internal::compiler::CodeGenerator::osr_pc_offset_ [private]
Definition at line 466 of file code-generator.h.
Referenced by AssembleConstructFrame(), and GenerateDeoptimizationData().
parameter_count_
uint16_t v8::internal::compiler::CodeGenerator::parameter_count_ = 0 [private]
Definition at line 449 of file code-generator.h.
Referenced by AssembleCode(), and FinalizeCode().
protected_deoptimization_literals_
ZoneDeque<IndirectHandle<TrustedObject> > v8::internal::compiler::CodeGenerator::protected_deoptimization_literals_ [private]
Definition at line 427 of file code-generator.h.
Referenced by DefineProtectedDeoptimizationLiteral(), GenerateDeoptimizationData(), and HasProtectedDeoptimizationLiteral().
resolver_
GapResolver v8::internal::compiler::CodeGenerator::resolver_ [private]
Definition at line 419 of file code-generator.h.
result_
CodeGenResult v8::internal::compiler::CodeGenerator::result_ [private]
Definition at line 471 of file code-generator.h.
Referenced by AssembleCode(), and FinalizeCode().
return_label_
Label v8::internal::compiler::CodeGenerator::return_label_ [private]
Definition at line 414 of file code-generator.h.
Referenced by AssembleReturn().
safepoints_
SafepointTableBuilder v8::internal::compiler::CodeGenerator::safepoints_ [private]
Definition at line 420 of file code-generator.h.
source_position_table_builder_
SourcePositionTableBuilder v8::internal::compiler::CodeGenerator::source_position_table_builder_ [private]
Definition at line 467 of file code-generator.h.
Referenced by AssembleSourcePosition(), FinalizeCode(), and GetSourcePositionTable().
start_source_position_
SourcePosition v8::internal::compiler::CodeGenerator::start_source_position_ [private]
Definition at line 416 of file code-generator.h.
translations_
FrameTranslationBuilder v8::internal::compiler::CodeGenerator::translations_ [private]
Definition at line 430 of file code-generator.h.
Referenced by AddTranslationForOperand(), BuildTranslation(), BuildTranslationForFrameStateDescriptor(), GenerateDeoptimizationData(), and TranslateStateValueDescriptor().
unwinding_info_writer_
UnwindingInfoWriter v8::internal::compiler::CodeGenerator::unwinding_info_writer_ [private]
Definition at line 411 of file code-generator.h.
Referenced by AssembleArchInstruction(), AssembleCode(), AssembleConstructFrame(), AssembleDeconstructFrame(), AssembleReturn(), and FinalizeCode().
zone_
Zone* v8::internal::compiler::CodeGenerator::zone_ [private]
Definition at line 406 of file code-generator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/code-generator.h
/mnt/V8SourceCode/src/compiler/backend/arm/code-generator-arm.cc
/mnt/V8SourceCode/src/compiler/backend/arm64/code-generator-arm64.cc
/mnt/V8SourceCode/src/compiler/backend/code-generator.cc
/mnt/V8SourceCode/src/compiler/backend/ia32/code-generator-ia32.cc
/mnt/V8SourceCode/src/compiler/backend/loong64/code-generator-loong64.cc
/mnt/V8SourceCode/src/compiler/backend/mips64/code-generator-mips64.cc
/mnt/V8SourceCode/src/compiler/backend/ppc/code-generator-ppc.cc
/mnt/V8SourceCode/src/compiler/backend/riscv/code-generator-riscv.cc
/mnt/V8SourceCode/src/compiler/backend/s390/code-generator-s390.cc
/mnt/V8SourceCode/src/compiler/backend/x64/code-generator-x64.cc