v8::base::Vector< T > Class Template Reference
#include <vector.h>
Public Types
using value_type = T
using iterator = T *
using const_iterator = const T *
Public Member Functions
constexpr Vector ()
constexpr Vector (T *data, size_t length)
Vector< T > SubVector (size_t from, size_t to) const
Vector< T > SubVectorFrom (size_t from) const
template<class U >
void OverwriteWith (Vector< U > other)
template<class U , size_t n>
void OverwriteWith (const std::array< U, n > &other)
int length () const
constexpr size_t size () const
constexpr bool empty () const
T & operator[] (size_t index) const
const T & at (size_t index) const
T & first ()
const T & first () const
T & last ()
const T & last () const
constexpr T * begin () const
constexpr const T * cbegin () const
constexpr T * data () const
constexpr T * end () const
constexpr const T * cend () const
constexpr std::reverse_iterator< T * > rbegin () const
constexpr std::reverse_iterator< T * > rend () const
Vector< T > Clone () const
void Truncate (size_t length)
void Dispose ()
const Vector< T > operator+ (size_t offset) const
Vector< T > operator+= (size_t offset)
template<typename U >
requires std::is_convertible_v< T *, const U * > && sizeof (U)
Static Public Member Functions
static Vector< T > New (size_t length)
Public Attributes
size_t length_
Detailed Description
template<typename T>
class v8::base::Vector< T >
Definition at line 23 of file vector.h.
Member Typedef Documentation
const_iterator
template<typename T >
using v8::base::Vector< T >::const_iterator = const T*
Definition at line 27 of file vector.h.
iterator
template<typename T >
using v8::base::Vector< T >::iterator = T*
Definition at line 26 of file vector.h.
value_type
template<typename T >
using v8::base::Vector< T >::value_type = T
Definition at line 25 of file vector.h.
Constructor & Destructor Documentation
Vector() [1/2]
template<typename T >
constexpr v8::base::Vector< T >::Vector () [inline], [constexpr]
Definition at line 29 of file vector.h.
: start_(nullptr), length_(0) {}
Vector() [2/2]
template<typename T >
constexpr v8::base::Vector< T >::Vector (T * data, size_t length) [inline], [constexpr]
Definition at line 31 of file vector.h.
                                           : start_(data), length_(length) {
    DCHECK(length == 0 || data != nullptr);
  }
References v8::base::Vector< T >::data(), DCHECK, and v8::base::Vector< T >::length().
Member Function Documentation
at()
template<typename T >
const T& v8::base::Vector< T >::at (size_t index) const [inline]
Definition at line 81 of file vector.h.
{ return operator[](index); }
References v8::internal::index, and v8::base::Vector< T >::operator[]().
Referenced by v8::internal::ScopedList< T, TBacking >::AddAll(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::BackRefMatchesNoCase(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CharAtEquals(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareFirstChar(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareFirstCharCaseInsensitive(), v8::internal::anonymous_namespace{js-number-format.cc}::FindLeadingAndTrailingWhiteSpaceOrLineTerminator(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::ZoneCompactSet< T >::remove(), v8::internal::JsonStringifier::SerializeString_(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAtom(), and anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::WriteBinaryContentsAsCArray().
begin()
template<typename T >
constexpr T* v8::base::Vector< T >::begin () const [inline], [constexpr]
Definition at line 96 of file vector.h.
{ return start_; }
Referenced by v8::internal::StringStream::Add(), v8::internal::ZoneList< T >::AddAll(), v8::internal::wasm::NativeModule::AddCode(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::AllocationTraceTree::AddPathFromEnd(), v8::internal::OutputStreamWriter::AddString(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::compiler::AnyMapIsHeapNumber(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendChars(), v8::internal::LogFile::MessageBuilder::AppendString(), v8::internal::compiler::AreUseIntervalsIntersectingVector(), v8::internal::DebugPropertyIterator::attributes(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::BinaryStringToDouble(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::wasm::WasmDeoptView::BuildDeoptimizationLiteralArray(), v8::internal::Checksum(), v8::internal::Zone::CloneVector(), v8::internal::CloneVector(), v8::internal::CodeTracer::CodeTracer(), v8::internal::String::Compare(), v8::internal::SnapshotCompression::Compress(), v8::internal::wasm::NamesProvider::ComputeExportName(), v8::internal::wasm::NamesProvider::ComputeImportName(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase(), v8::internal::Intl::ConvertOneByteToLower(), v8::internal::LiteralBuffer::ConvertToTwoByte(), v8::internal::Intl::ConvertToUpper(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::OutBuffer< Char >::CopyTo(), v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), v8::internal::CreateExponentialRepresentation(), v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::CreateSnapshotBlob(), v8::internal::Scanner::CurrentLiteralAsCString(), v8::internal::Scanner::CurrentLiteralEquals(), v8::internal::wasm::DebugInfoImpl::DeadBreakpoint(), v8::internal::Utf8DecoderBase< Decoder >::Decode(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::DecodeWasmSignatureForTesting(), v8::internal::SnapshotCompression::Decompress(), v8::internal::DeoptTranslationIterator::DeoptTranslationIterator(), v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector(), v8::internal::wasm::WasmCode::Disassemble(), disasm::Disassembler::Disassemble(), v8::internal::wasm::DisassembleFunctionImpl(), v8::internal::Assembler::disassembleInstr(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::DoubleToFixedStringView(), v8::internal::DoubleToPrecisionStringView(), v8::internal::DoubleToRadixStringView(), v8::internal::DoubleToStringView(), v8::internal::wasm::DumpModule(), v8::internal::wasm::DumpProfileToFile(), v8::internal::Assembler::embedded_object_handle_at(), v8::internal::EmbeddedFileWriter::EmbeddedBlobCodeSymbol(), v8::internal::EmbeddedFileWriter::EmbeddedBlobDataSymbol(), v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8(), v8::internal::LiteralBuffer::Equals(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualTypes(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::LiteralBuffer::ExpandBuffer(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::CodeStubAssembler::FailAssert(), v8::internal::SimpleStringBuilder::Finalize(), v8::internal::FindFirstCharacter(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FindMatches(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::FindOneByteStringIndices(), v8::internal::FindTwoByteStringIndices(), v8::internal::AstRawString::FirstCharacter(), v8::internal::anonymous_namespace{js-number-format.cc}::FormatDecimalString(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::wasm::GenerateLiftoffDebugSideTable(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::StackMemory::GetCentralStackView(), v8::internal::StringsStorage::GetCopy(), v8::internal::wasm::GetCustomSections(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::compiler::GetDebugName(), v8::internal::wasm::WasmDeoptView::GetDeoptEntry(), v8::internal::wasm::WasmCode::GetInliningPosition(), wasm::anonymous_namespace{c-api.cc}::GetNameFromWireBytes(), v8::internal::AstValueFactory::GetOneByteStringInternal(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::wasm::WasmDeoptView::GetTranslationsArray(), v8::internal::AstValueFactory::GetTwoByteStringInternal(), v8::internal::anonymous_namespace{intl-objects.cc}::GetUCharBufferFromFlat(), v8::internal::wasm::AsmJsParser::GetVarInfo(), v8::internal::StringsStorage::GetVFormatted(), v8::internal::compiler::GetVisualizerLogFileName(), v8::internal::wasm::GetWireBytesHash(), v8::CompiledWasmModule::GetWireBytesRef(), v8::base::hash_value(), v8::internal::anonymous_namespace{runtime-wasm.cc}::HasUnpairedSurrogate(), v8::internal::HexStringToDouble(), v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber(), v8::internal::wasm::ModuleDecoder::IdentifyUnknownSection(), v8::internal::ImplicitOctalStringToDouble(), v8::internal::Heap::IncrementDeferredCounts(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::InitReturnPhis(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::IntToStringView(), v8::internal::AstRawString::IsOneByteEqualTo(), v8::internal::wasm::WasmCode::IsProtectedInstruction(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::IsSubtypeVec(), v8::internal::wasm::IsSupportedVersion(), v8::internal::String::IsWellFormedUnicode(), v8::internal::StringSearch< PatternChar, SubjectChar >::LinearSearch(), v8::internal::LiteralBuffer::literal(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::LoadProfileFromFile(), v8::internal::wasm::WasmEngine::LogCode(), v8::internal::LowLevelLogger::LowLevelLogger(), v8::internal::String::MakeExternal(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MaybeBailoutForUnsupportedType(), anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::MaybeWriteStartupBlob(), disasm::NameConverter::NameOfAddress(), v8::internal::FactoryBase< Impl >::NewOneByteInternalizedString(), v8::internal::FactoryBase< Impl >::NewOneByteInternalizedStringFromTwoByte(), v8::internal::FactoryBase< Impl >::NewTwoByteInternalizedString(), v8::internal::Scanner::NextLiteralExactlyEquals(), v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue(), v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::NextWithValue(), v8::internal::OctalStringToDouble(), v8::internal::CodeTracer::OpenFile(), v8::internal::compiler::turboshaft::fast_hash< base::Vector< T > >::operator()(), v8::internal::wasm::NativeModuleCache::Key::operator<(), v8::base::Vector< T >::OverwriteWith(), v8::internal::StringToIntHelper::ParseInt(), v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::internal::PassesFilter(), v8::internal::SimpleStringBuilder::position(), v8::internal::FlatStringReader::PostGarbageCollection(), v8::internal::wasm::NativeModuleCache::PrefixHash(), v8::internal::AstRawString::raw_data(), v8::internal::wasm::AsyncStreamingDecoder::DecodingState::ReadBytes(), v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::wasm::NativeModuleDeserializer::ReadTieringBudget(), v8::internal::ValueDeserializer::ReadTwoByteString(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::ZoneCompactSet< T >::remove(), v8::base::Vector< T >::rend(), v8::internal::wasm::Decoder::Reset(), v8::internal::wasm::RestoreProfileData(), v8::internal::compiler::WasmGraphBuilder::Return(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ReturnImpl(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanEtcGMTASCIISignUnpaddedHour(), v8::internal::Scanner::ScanIdentifierOrKeywordInner(), v8::internal::Scanner::ScanIdentifierOrKeywordInnerSlow(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneIANALegacyName(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Seal(), v8::internal::FlagList::SetFlagsFromString(), v8::internal::wasm::StreamingDecoder::SetUrl(), v8::internal::SimpleStringBuilder::SimpleStringBuilder(), v8::internal::Factory::SizeToString(), v8::internal::String::SlowEquals(), v8::base::SmallVector< T, kSize, Allocator >::SmallVector(), v8::internal::StringToDouble(), v8::base::StrNCpy(), v8::base::Vector< T >::SubVector(), v8::internal::anonymous_namespace{intl-objects.cc}::ToICUStringPiece(), v8::internal::Intl::ToICUUnicodeString(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperFastASCII(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperOneByte(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperWithSharpS(), v8::internal::Map::TransitionToDataProperty(), v8::base::TrimLeadingZeros(), v8::base::TrimTrailingZeros(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_rec(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::ValidateProfileData(), v8::internal::VectorToByteArray(), v8::base::VSNPrintF(), v8::internal::wasm::WasmDeoptView::WasmDeoptView(), v8::internal::EmbeddedFileWriter::WriteBuiltin(), v8::internal::OutputStreamWriter::WriteChunk(), v8::internal::EmbeddedFileWriter::WriteFileEpilogue(), v8::internal::ValueSerializer::WriteOneByteString(), v8::internal::wasm::NamesProvider::WriteRef(), v8::internal::ValueSerializer::WriteTwoByteString(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::WriteVector(), and v8::internal::ZoneCompactSet< T >::ZoneCompactSet().
cbegin()
template<typename T >
constexpr const T* v8::base::Vector< T >::cbegin () const [inline], [constexpr]
Definition at line 97 of file vector.h.
{ return start_; }
cend()
template<typename T >
constexpr const T* v8::base::Vector< T >::cend () const [inline], [constexpr]
Definition at line 104 of file vector.h.
{ return start_ + length_; }
References v8::base::Vector< T >::length_.
Clone()
template<typename T >
Vector<T> v8::base::Vector< T >::Clone () const [inline]
Definition at line 114 of file vector.h.
                          {
    T* result = new T[length_];
    for (size_t i = 0; i < length_; i++) result[i] = start_[i];
    return Vector<T>(result, length_);
  }
References v8::base::Vector< T >::length_, and v8::base::internal::result.
data()
template<typename T >
constexpr T* v8::base::Vector< T >::data () const [inline], [constexpr]
Definition at line 100 of file vector.h.
{ return start_; }
Referenced by v8::internal::compiler::turboshaft::Graph::AllocateNewBlocks(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AssertImpl(), v8::internal::BUILTIN(), v8::internal::CloneVector(), v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringFlatContent(), v8::base::FastDtoa(), v8::anonymous_namespace{wasm-js.cc}::GetAndCopyFirstArgumentAsBytes(), v8::internal::String::IsConsStringEqualToImpl(), v8::internal::String::IsEqualToImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LiftoffCompiler(), v8::internal::wasm::WasmCode::LogCode(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::MapOptionToEnum(), v8::internal::Factory::NewCopiedSubstring(), v8::internal::wasm::AsyncStreamingDecoder::OnBytesReceived(), v8::internal::wasm::SyncStreamingDecoder::OnBytesReceived(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::anonymous_namespace{scanner.cc}::ProcessPerFunctionCompileHints(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_OneCharPattern(), v8::internal::wasm::WasmDeoptDataProcessor::Serialize(), v8::internal::JsonStringifier::SerializeString_(), v8::internal::JsonStringifier::SerializeStringUnchecked_(), v8::internal::SafepointEntry::tagged_slots(), v8::internal::wasm::ValidateAndSetBuiltinImports(), v8::base::Vector< T >::Vector(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::WasmSimd128ToString(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl().
Dispose()
template<typename T >
void v8::base::Vector< T >::Dispose () [inline]
Definition at line 127 of file vector.h.
                 {
    delete[] start_;
    start_ = nullptr;
    length_ = 0;
  }
References v8::base::Vector< T >::length_.
Referenced by v8::internal::LiteralBuffer::ConvertToTwoByte(), v8::internal::LiteralBuffer::ExpandBuffer(), and v8::internal::LiteralBuffer::~LiteralBuffer().
empty()
template<typename T >
constexpr bool v8::base::Vector< T >::empty () const [inline], [constexpr]
Definition at line 73 of file vector.h.
{ return length_ == 0; }
References v8::base::Vector< T >::length_.
Referenced by v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AddUnits(), v8::internal::compiler::turboshaft::Graph::AllocateNewBlocks(), v8::internal::compiler::AreUseIntervalsIntersectingVector(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::CommitCompilationUnits(), v8::internal::wasm::NamesProvider::ComputeFunctionNamesFromImportsExports(), v8::internal::wasm::NamesProvider::ComputeNamesFromImportsExports(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ConsumeAndGenerate(), v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::DumpProfileToFile(), v8::internal::wasm::NativeModuleCache::Erase(), v8::anonymous_namespace{wasm-js.cc}::GetAndCopyFirstArgumentAsBytes(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::has_more(), v8::internal::wasm::WasmDeoptView::HasDeoptData(), v8::internal::wasm::InliningTree::Inline(), v8::internal::AstRawString::Internalize(), v8::internal::String::IsConsStringEqualToImpl(), v8::internal::anonymous_namespace{string.cc}::IsIdentifierVector(), v8::internal::wasm::LoadProfileFromFile(), v8::internal::wasm::WasmEngine::LogCode(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MaybePhi(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MoveToNewSnapshot(), v8::internal::wasm::NativeModuleCache::Key::operator<(), v8::internal::PassesFilter(), v8::internal::SafepointTable::Print(), v8::internal::wasm::PrintSignature(), v8::internal::wasm::NativeModule::should_update_code_table(), v8::internal::interpreter::anonymous_namespace{interpreter.cc}::ShouldPrintBytecode(), v8::base::Strtod(), v8::internal::wasm::WasmEngine::SyncValidate(), v8::internal::MessageFormatter::TryFormat(), v8::internal::wasm::NativeModuleCache::Update(), v8::internal::wasm::WasmDeoptView::WasmDeoptView(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::WriteVector().
end()
template<typename T >
constexpr T* v8::base::Vector< T >::end () const [inline], [constexpr]
Definition at line 103 of file vector.h.
{ return start_ + length_; }
References v8::base::Vector< T >::length_.
Referenced by v8::internal::ZoneList< T >::AddAll(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::compiler::AnyMapIsHeapNumber(), v8::internal::LogFile::MessageBuilder::AppendString(), v8::internal::compiler::AreUseIntervalsIntersectingVector(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::BinaryStringToDouble(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::Zone::CloneVector(), v8::internal::CloneVector(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::wasm::DebugInfoImpl::DeadBreakpoint(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::WasmCode::deopt_data(), v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector(), v8::internal::wasm::DisassembleFunctionImpl(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualTypes(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FindMatches(), v8::internal::wasm::GenerateLiftoffDebugSideTable(), v8::internal::wasm::AsmJsParser::GetVarInfo(), v8::base::hash_value(), v8::internal::HexStringToDouble(), v8::internal::ImplicitOctalStringToDouble(), v8::internal::Heap::IncrementDeferredCounts(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::InitReturnPhis(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::WasmCode::inlining_positions(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::IntToStringView(), v8::internal::String::IsConsStringEqualToImpl(), v8::internal::wasm::WasmCode::IsProtectedInstruction(), v8::internal::wasm::WasmEngine::LogCode(), v8::internal::OctalStringToDouble(), v8::internal::wasm::AsyncStreamingDecoder::OnBytesReceived(), v8::internal::compiler::turboshaft::fast_hash< base::Vector< T > >::operator()(), v8::base::Vector< T >::OverwriteWith(), v8::internal::PassesFilter(), v8::internal::wasm::NativeModuleCache::PrefixHash(), v8::base::Vector< T >::rbegin(), v8::internal::wasm::WasmCode::reloc_info(), v8::internal::ZoneCompactSet< T >::remove(), v8::internal::wasm::Decoder::Reset(), v8::internal::wasm::RestoreProfileData(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ReturnImpl(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Seal(), v8::base::SmallVector< T, kSize, Allocator >::SmallVector(), v8::internal::wasm::WasmCode::source_positions(), v8::internal::StringToDouble(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperFastASCII(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperOneByte(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperWithSharpS(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_rec(), v8::internal::JsonStringifier::TrySerializeSimplePropertyKey(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), and v8::internal::ZoneCompactSet< T >::ZoneCompactSet().
first() [1/2]
template<typename T >
T& v8::base::Vector< T >::first () [inline]
Definition at line 83 of file vector.h.
{ return start_[0]; }
Referenced by v8::internal::compiler::AreUseIntervalsIntersectingVector(), v8::internal::CodeStubAssembler::FailAssert(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MoveToNewSnapshot(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessPhi(), v8::internal::wasm::AsyncStreamingDecoder::DecodingState::ReadBytes(), v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes(), and v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::SectionBuffer().
first() [2/2]
template<typename T >
const T& v8::base::Vector< T >::first () const [inline]
Definition at line 84 of file vector.h.
{ return start_[0]; }
last() [1/2]
template<typename T >
T& v8::base::Vector< T >::last () [inline]
Definition at line 86 of file vector.h.
            {
    DCHECK_LT(0, length_);
    return start_[length_ - 1];
  }
References DCHECK_LT, and v8::base::Vector< T >::length_.
Referenced by v8::internal::compiler::AreUseIntervalsIntersectingVector(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE().
last() [2/2]
template<typename T >
const T& v8::base::Vector< T >::last () const [inline]
Definition at line 90 of file vector.h.
                        {
    DCHECK_LT(0, length_);
    return start_[length_ - 1];
  }
References DCHECK_LT, and v8::base::Vector< T >::length_.
length()
template<typename T >
int v8::base::Vector< T >::length () const [inline]
Definition at line 64 of file vector.h.
                     {
    CHECK_GE(std::numeric_limits<int>::max(), length_);
    return static_cast<int>(length_);
  }
References CHECK_GE, and v8::base::Vector< T >::length_.
Referenced by v8::internal::StringStream::Add(), v8::internal::ScopedList< T, TBacking >::AddAll(), v8::internal::ZoneList< T >::AddAll(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::SimpleStringBuilder::AddExponent(), v8::internal::LiteralBuffer::AddOneByteChar(), v8::internal::AllocationTraceTree::AddPathFromEnd(), v8::internal::LiteralBuffer::AddTwoByteChar(), v8::internal::SourcePositionTableIterator::Advance(), v8::internal::anonymous_namespace{runtime-regexp.cc}::AdvanceStringIndex(), v8::internal::compiler::turboshaft::Graph::AllocateNewBlocks(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendString(), v8::internal::anonymous_namespace{regexp.cc}::AtomExecRawImpl(), v8::base::BignumStrtod(), v8::internal::StringSearch< PatternChar, SubjectChar >::BoyerMooreHorspoolSearch(), v8::internal::StringSearch< PatternChar, SubjectChar >::BoyerMooreSearch(), v8::internal::AstRawString::byte_length(), v8::internal::CalculateLineEndsImpl(), v8::internal::Checksum(), v8::internal::CloneVector(), v8::internal::CodeTracer::CodeTracer(), v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), v8::internal::wasm::WasmImportWrapperCache::CompileWrapper(), v8::internal::LiteralBuffer::ConvertToTwoByte(), v8::internal::anonymous_namespace{js-regexp.cc}::CountAdditionalEscapeChars(), v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::CreateSnapshotBlob(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::Scanner::CurrentLiteralAsCString(), v8::internal::Scanner::CurrentLiteralEquals(), v8::internal::Utf8DecoderBase< Decoder >::Decode(), v8::internal::DeoptTranslationIterator::DeoptTranslationIterator(), v8::base::DiyFpStrtod(), v8::base::DoubleStrtod(), v8::internal::wasm::DumpModule(), v8::internal::LiteralBuffer::Equals(), v8::internal::LiteralBuffer::ExpandBuffer(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::TextNode::FilterOneByte(), v8::internal::FindFirstCharacter(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::FindOneByteStringIndices(), v8::internal::FindStringIndices(), v8::internal::FindStringIndicesDispatch(), v8::internal::FindTwoByteStringIndices(), v8::internal::Decoder< V >::Format(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::Parser::GetBigIntAsSymbol(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::compiler::GetDebugName(), wasm::anonymous_namespace{c-api.cc}::GetNameFromWireBytes(), v8::internal::AstValueFactory::GetOneByteStringInternal(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::AstValueFactory::GetTwoByteStringInternal(), v8::internal::compiler::GetVisualizerLogFileName(), v8::internal::wasm::GetWireBytesHash(), v8::internal::anonymous_namespace{temporal-parser.cc}::HasTwoDigits(), v8::internal::StringSearch< PatternChar, SubjectChar >::InitialSearch(), v8::internal::AstRawString::IsEmpty(), v8::internal::AstRawString::length(), v8::internal::RegExpAtom::length(), v8::internal::StringSearch< PatternChar, SubjectChar >::LinearSearch(), v8::internal::RegExpAtom::max_match(), anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::MaybeWriteStartupBlob(), v8::internal::RegExpAtom::min_match(), v8::base::Vector< T >::New(), v8::internal::FactoryBase< Impl >::NewOneByteInternalizedString(), v8::internal::FactoryBase< Impl >::NewOneByteInternalizedStringFromTwoByte(), v8::internal::FactoryBase< Impl >::NewTwoByteInternalizedString(), v8::internal::DateParser::InputReader< Char >::Next(), v8::internal::Scanner::NextLiteralExactlyEquals(), v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::CharacterClassStringLess::operator()(), v8::internal::operator<<(), v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::internal::CompiledReplacement::ParseReplacementPattern(), v8::internal::compiler::LinearScanAllocator::PickRegisterThatIsAvailableLongest(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::PopLastAtom(), v8::internal::Decoder< V >::Print(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), v8::internal::anonymous_namespace{scanner.cc}::ProcessPerFunctionCompileHints(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch(), v8::base::ReadDiyFp(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::ValueDeserializer::ReadTwoByteString(), v8::base::ReadUint64(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_Generic(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_OneCharPattern(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::SatisfiesAssertion(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendar(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarName(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarNameComponent(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarTime_L1(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDate(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateExtendedYear(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateFourDigitYear(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateSpecMonthDay(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateSpecYearMonth(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDuration(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDurationTime(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanEtcGMTAsciiSignHour(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanEtcGMTASCIISignUnpaddedHour(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanFraction(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanFractionalPart(), v8::internal::Scanner::ScanIdentifierOrKeywordInner(), v8::internal::Scanner::ScanIdentifierOrKeywordInnerSlow(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeFraction(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeSpec(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeSpecSeparator(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneBracketedAnnotation(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneIANALegacyName(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneIANAName(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneIANANameComponent(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneNumericUTCOffset(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneUTCOffset(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneUTCOffsetFraction(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneUTCOffsetName(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanUnpaddedHour(), v8::internal::anonymous_namespace{temporal-parser.cc}::ScanValidMonthDay(), v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::SectionBuffer(), v8::internal::HeapSnapshotJSONSerializer::SerializeStrings(), v8::internal::interpreter::anonymous_namespace{interpreter.cc}::ShouldPrintBytecode(), v8::internal::Factory::SizeToString(), v8::internal::anonymous_namespace{string.cc}::StringMatchBackwards(), v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch(), v8::base::StrNCpy(), v8::base::Strtod(), v8::internal::TextNode::TextEmitPass(), v8::base::TrimLeadingZeros(), v8::base::TrimToMaxSignificantDigits(), v8::base::TrimTrailingZeros(), v8::base::Vector< T >::Truncate(), v8::internal::Utf8DecoderBase< Decoder >::Utf8DecoderBase(), v8::base::Vector< T >::Vector(), v8::internal::VectorToByteArray(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAtom(), v8::base::VSNPrintF(), anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::WriteBinaryContentsAsCArray(), v8::internal::ValueSerializer::WriteOneByteString(), anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::WriteSnapshotFileData(), v8::internal::ValueSerializer::WriteString(), and v8::internal::ValueSerializer::WriteTwoByteString().
New()
template<typename T >
static Vector<T> v8::base::Vector< T >::New (size_t length) [inline], [static]
Definition at line 35 of file vector.h.
                                      {
    return Vector<T>(new T[length], length);
  }
References v8::base::Vector< T >::length().
Referenced by v8::internal::LiteralBuffer::ConvertToTwoByte(), v8::internal::DoubleToFixedStringView(), v8::internal::LiteralBuffer::ExpandBuffer(), v8::internal::StringsStorage::GetCopy(), v8::internal::StringsStorage::GetVFormatted(), and v8::internal::SimpleStringBuilder::SimpleStringBuilder().
operator+()
template<typename T >
const Vector<T> v8::base::Vector< T >::operator+ (size_t offset) const [inline]
Definition at line 133 of file vector.h.
                                                 {
    DCHECK_LE(offset, length_);
    return Vector<T>(start_ + offset, length_ - offset);
  }
References DCHECK_LE, and v8::base::Vector< T >::length_.
operator+=()
template<typename T >
Vector<T> v8::base::Vector< T >::operator+= (size_t offset) [inline]
Definition at line 138 of file vector.h.
                                      {
    DCHECK_LE(offset, length_);
    start_ += offset;
    length_ -= offset;
    return *this;
  }
References DCHECK_LE, and v8::base::Vector< T >::length_.
operator[]()
template<typename T >
T& v8::base::Vector< T >::operator[] (size_t index) const [inline]
Definition at line 76 of file vector.h.
                                    {
    DCHECK_LT(index, length_);
    return start_[index];
  }
References DCHECK_LT, v8::internal::index, and v8::base::Vector< T >::length_.
Referenced by v8::base::Vector< T >::at().
OverwriteWith() [1/2]
template<typename T >
template<class U , size_t n>
void v8::base::Vector< T >::OverwriteWith (const std::array< U, n > & other) [inline]
Definition at line 57 of file vector.h.
                                                  {
    DCHECK_EQ(size(), other.size());
    std::copy(other.begin(), other.end(), begin());
  }
References v8::base::Vector< T >::begin(), DCHECK_EQ, and v8::base::Vector< T >::size().
OverwriteWith() [2/2]
template<typename T >
template<class U >
void v8::base::Vector< T >::OverwriteWith (Vector< U > other) [inline]
Definition at line 51 of file vector.h.
                                      {
    DCHECK_EQ(size(), other.size());
    std::copy(other.begin(), other.end(), begin());
  }
References v8::base::Vector< T >::begin(), DCHECK_EQ, v8::base::Vector< T >::end(), and v8::base::Vector< T >::size().
rbegin()
template<typename T >
constexpr std::reverse_iterator<T*> v8::base::Vector< T >::rbegin () const [inline], [constexpr]
Definition at line 106 of file vector.h.
                                                   {
    return std::make_reverse_iterator(end());
  }
References v8::base::Vector< T >::end().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ConsumeAndGenerate(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop().
rend()
template<typename T >
constexpr std::reverse_iterator<T*> v8::base::Vector< T >::rend () const [inline], [constexpr]
Definition at line 109 of file vector.h.
                                                 {
    return std::make_reverse_iterator(begin());
  }
References v8::base::Vector< T >::begin().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ConsumeAndGenerate(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop().
size()
template<typename T >
constexpr size_t v8::base::Vector< T >::size () const [inline], [constexpr]
Definition at line 70 of file vector.h.
{ return length_; }
References v8::base::Vector< T >::length_.
Referenced by v8::internal::SimpleStringBuilder::AddCharacter(), v8::internal::wasm::NativeModule::AddCode(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::wasm::NativeModule::AddDeserializedCode(), v8::internal::SimpleStringBuilder::AddPadding(), v8::internal::SimpleStringBuilder::AddSubstring(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AddUnits(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendChars(), v8::internal::compiler::AreUseIntervalsIntersectingVector(), v8::internal::ArrayBufferFromHex(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::maglev::MaglevGraphBuilder::BuildCallKnownJSFunction(), v8::internal::compiler::WasmGraphBuilder::BuildWasmCall(), v8::internal::BUILTIN(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::compiler::turboshaft::CallOp::CallOp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::Zone::CloneVector(), v8::internal::SnapshotCompression::Compress(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ConsumeAndGenerate(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::OutBuffer< Char >::CopyTo(), v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), v8::internal::CreateExponentialRepresentation(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateSignature(), v8::internal::CreateWasmObject(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::DecodeAsmJsOffsets(), v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::DecodeWasmFunctionForTesting(), v8::internal::wasm::DecodeWasmModule(), v8::internal::SnapshotCompression::Decompress(), v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::DeoptFrameScope(), v8::internal::ContextDeserializer::DeserializeContext(), v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector(), v8::internal::wasm::WasmCode::Disassemble(), v8::internal::DoubleToFixedStringView(), v8::internal::DoubleToPrecisionStringView(), v8::internal::DoubleToRadixStringView(), v8::internal::DoubleToStringView(), v8::internal::wasm::DumpProfileToFile(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8(), v8::internal::wasm::EquivalentNumericSig(), v8::internal::wasm::NativeModule::EstimateCurrentMemoryConsumption(), v8::internal::compiler::turboshaft::FastApiCallOp::FastApiCallOp(), v8::internal::SimpleStringBuilder::Finalize(), v8::internal::anonymous_namespace{js-number-format.cc}::FindLeadingAndTrailingWhiteSpaceOrLineTerminator(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::anonymous_namespace{wasm-js.cc}::GetAndCopyFirstArgumentAsBytes(), v8::internal::wasm::StackMemory::GetCentralStackView(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::GetChangedStackValues(), v8::internal::wasm::AsmJsParser::GetVarInfo(), v8::CompiledWasmModule::GetWireBytesRef(), v8::internal::anonymous_namespace{runtime-wasm.cc}::HasUnpairedSurrogate(), v8::internal::wasm::WellKnownImportsList::Initialize(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::InitReturnPhis(), v8::internal::wasm::InliningTree::Inline(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::IntToStringView(), v8::internal::String::IsConsStringEqualToImpl(), v8::internal::String::IsEqualToImpl(), v8::internal::anonymous_namespace{string.cc}::IsIdentifierVector(), v8::internal::AstRawString::IsOneByteEqualTo(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::IsSubtypeVec(), v8::internal::wasm::IsSupportedVersion(), v8::internal::TypedFrame::Iterate(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), v8::internal::wasm::WasmCode::LogCode(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::MapOptionToEnum(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MaxEncodedSize(), v8::internal::wasm::WasmEngine::MaybeGetNativeModule(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MaybePhi(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MergePredecessors(), v8::internal::compiler::turboshaft::TailCallOp::New(), v8::internal::compiler::turboshaft::OperationT< Derived >::New(), v8::internal::compiler::turboshaft::CallOp::New(), v8::internal::compiler::turboshaft::FastApiCallOp::New(), v8::internal::compiler::turboshaft::ReturnOp::New(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::NewEntry(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::NewOOLEntry(), v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue(), v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::NextWithValue(), v8::internal::wasm::AsyncStreamingDecoder::OnBytesReceived(), v8::internal::wasm::SyncStreamingDecoder::OnBytesReceived(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8::internal::wasm::NativeModuleCache::Key::operator<(), v8::base::Vector< T >::OverwriteWith(), v8::internal::StringToIntHelper::ParseInt(), v8::internal::PassesFilter(), v8::internal::wasm::NativeModule::PatchJumpTableLocked(), v8::internal::wasm::PrintSignature(), v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessPhi(), v8::internal::wasm::AsyncStreamingProcessor::ProcessSection(), v8::internal::wasm::NativeModule::PublishCode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushValueTypes(), v8::internal::wasm::NativeModuleDeserializer::Read(), v8::internal::wasm::AsyncStreamingDecoder::DecodingState::ReadBytes(), v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes(), v8::internal::wasm::NativeModuleDeserializer::ReadCode(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::ReduceOperation(), v8::internal::wasm::WasmCode::RegisterTrapHandlerData(), v8::internal::ZoneCompactSet< T >::remove(), v8::internal::compiler::turboshaft::Graph::ReorderBlocks(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::WasmGraphBuilder::Return(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), v8::internal::compiler::turboshaft::ReturnOp::ReturnOp(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmDeoptDataProcessor::Serialize(), v8::internal::wasm::WasmSerializer::SerializeNativeModule(), v8::internal::JsonStringifier::SerializeString_(), v8::internal::JsonStringifier::SerializeStringUnchecked_(), v8::internal::compiler::turboshaft::FloatType< Bits >::Set(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::wasm::StreamingDecoder::SetUrl(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size(), v8::internal::ZoneCompactSet< T >::size(), v8::base::SmallVector< T, kSize, Allocator >::SmallVector(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::split(), v8::internal::compiler::turboshaft::TailCallOp::TailCallOp(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_rec(), v8::internal::MessageFormatter::TryFormat(), v8::internal::compiler::turboshaft::TupleType::Tuple(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::wasm::WellKnownImportsList::Update(), v8::internal::wasm::ValidateAndSetBuiltinImports(), v8::internal::wasm::WasmDeoptView::WasmDeoptView(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl(), v8::internal::anonymous_namespace{js-regexp.cc}::WriteEscapedRegExpSource(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::WriteVector().
sizeof()
template<typename T >
template<typename U >
requires std::is_convertible_v<T*, const U*>&& v8::base::Vector< T >::sizeof (U)
References v8::base::Vector< T >::length_.
SubVector()
template<typename T >
Vector<T> v8::base::Vector< T >::SubVector (size_t from, size_t to) const [inline]
Definition at line 41 of file vector.h.
                                                    {
    DCHECK_LE(from, to);
    DCHECK_LE(to, length_);
    return Vector<T>(begin() + from, to - from);
  }
References v8::base::Vector< T >::begin(), DCHECK_LE, and v8::base::Vector< T >::length_.
Referenced by v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::buffer(), v8::internal::compiler::turboshaft::CallOp::CallOp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::Intl::ConvertToUpper(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::compiler::turboshaft::FastApiCallOp::FastApiCallOp(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::NativeModuleWireBytesStorage::GetCode(), v8::internal::wasm::ModuleWireBytes::GetFunctionBytes(), v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::WasmTrustedInstanceData::InitDataSegmentArrays(), v8::internal::String::IsConsStringEqualToImpl(), v8::internal::WasmValueObject::New(), v8::internal::WasmExportedFunction::New(), v8::internal::wasm::AsyncStreamingDecoder::OnBytesReceived(), v8::internal::CompiledReplacement::ParseReplacementPattern(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::PopLastAtom(), v8::internal::wasm::AsyncStreamingProcessor::ProcessSection(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::wasm::NativeModuleDeserializer::ReadCode(), v8::internal::compiler::turboshaft::ReturnOp::ReturnOp(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::split(), v8::base::Vector< T >::SubVectorFrom(), v8::internal::compiler::turboshaft::TailCallOp::TailCallOp(), v8::base::TrimLeadingZeros(), v8::base::TrimTrailingZeros(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
SubVectorFrom()
template<typename T >
Vector<T> v8::base::Vector< T >::SubVectorFrom (size_t from) const [inline]
Definition at line 46 of file vector.h.
                                             {
    return SubVector(from, length_);
  }
References v8::base::Vector< T >::length_, and v8::base::Vector< T >::SubVector().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MoveToNewSnapshot(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
Truncate()
template<typename T >
void v8::base::Vector< T >::Truncate (size_t length) [inline]
Definition at line 120 of file vector.h.
                               {
    DCHECK(length <= length_);
    length_ = length;
  }
References DCHECK, v8::base::Vector< T >::length(), and v8::base::Vector< T >::length_.
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes(), v8::internal::anonymous_namespace{asm-js.cc}::ReportCompilationSuccess(), and v8::internal::anonymous_namespace{asm-js.cc}::ReportInstantiationSuccess().
Member Data Documentation
length_
template<typename T >
size_t v8::base::Vector< T >::length_
Definition at line 180 of file vector.h.
Referenced by v8::base::Vector< T >::cend(), v8::base::Vector< T >::Clone(), v8::base::Vector< T >::Dispose(), v8::base::Vector< T >::empty(), v8::base::Vector< T >::end(), v8::base::Vector< T >::last(), v8::base::Vector< T >::length(), v8::base::Vector< T >::operator+(), v8::base::Vector< T >::operator+=(), v8::base::Vector< T >::operator[](), v8::base::Vector< T >::size(), v8::base::Vector< T >::sizeof(), v8::base::Vector< T >::SubVector(), v8::base::Vector< T >::SubVectorFrom(), and v8::base::Vector< T >::Truncate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/vector.h