v8::internal::BigIntBuiltinsAssembler Class Reference
#include <builtins-bigint-gen.h>
Public Member Functions
BigIntBuiltinsAssembler (compiler::CodeAssemblerState *state)
TNode< IntPtrT > ReadBigIntLength (TNode< BigInt > value)
TNode< Uint32T > ReadBigIntSign (TNode< BigInt > value)
void WriteBigIntSignAndLength (TNode< BigInt > bigint, TNode< Uint32T > sign, TNode< IntPtrT > length)
void CppAbsoluteAddAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppAbsoluteSubAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
TNode< Int32T > CppAbsoluteMulAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
TNode< Int32T > CppAbsoluteDivAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
TNode< Int32T > CppAbsoluteModAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseAndPosPosAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseAndNegNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseAndPosNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseOrPosPosAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseOrNegNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseOrPosNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseXorPosPosAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseXorNegNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppBitwiseXorPosNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y)
void CppLeftShiftAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< IntPtrT > shift)
TNode< Uint32T > CppRightShiftResultLength (TNode< BigInt > x, TNode< Uint32T > x_sign, TNode< IntPtrT > shift)
void CppRightShiftAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< IntPtrT > shift, TNode< Uint32T > must_round_down)
TNode< Int32T > CppAbsoluteCompare (TNode< BigInt > x, TNode< BigInt > y)
Additional Inherited Members
Detailed Description
Definition at line 14 of file builtins-bigint-gen.h.
Constructor & Destructor Documentation
BigIntBuiltinsAssembler()
v8::internal::BigIntBuiltinsAssembler::BigIntBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 16 of file builtins-bigint-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
CppAbsoluteAddAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppAbsoluteAddAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 40 of file builtins-bigint-gen.h.
                                                      {
    TNode<ExternalReference> mutable_big_int_absolute_add_and_canonicalize =
        ExternalConstant(
            ExternalReference::
                mutable_big_int_absolute_add_and_canonicalize_function());
    CallCFunction(mutable_big_int_absolute_add_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppAbsoluteCompare()
TNode<Int32T> v8::internal::BigIntBuiltinsAssembler::CppAbsoluteCompare (TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 269 of file builtins-bigint-gen.h.
                                                                     {
    TNode<ExternalReference> mutable_big_int_absolute_compare =
        ExternalConstant(
            ExternalReference::mutable_big_int_absolute_compare_function());
    TNode<Int32T> result = UncheckedCast<Int32T>(
        CallCFunction(mutable_big_int_absolute_compare, MachineType::Int32(),
                      std::make_pair(MachineType::AnyTagged(), x),
                      std::make_pair(MachineType::AnyTagged(), y)));
    return result;
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Int32(), v8::base::internal::result, and v8::internal::y.
CppAbsoluteDivAndCanonicalize()
TNode<Int32T> v8::internal::BigIntBuiltinsAssembler::CppAbsoluteDivAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 81 of file builtins-bigint-gen.h.
                                                               {
    TNode<ExternalReference> mutable_big_int_absolute_div_and_canonicalize =
        ExternalConstant(
            ExternalReference::
                mutable_big_int_absolute_div_and_canonicalize_function());
    TNode<Int32T> return_code = UncheckedCast<Int32T>(CallCFunction(
        mutable_big_int_absolute_div_and_canonicalize, MachineType::Int32(),
        std::make_pair(MachineType::AnyTagged(), result),
        std::make_pair(MachineType::AnyTagged(), x),
        std::make_pair(MachineType::AnyTagged(), y)));
    return return_code;
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Int32(), v8::base::internal::result, and v8::internal::y.
CppAbsoluteModAndCanonicalize()
TNode<Int32T> v8::internal::BigIntBuiltinsAssembler::CppAbsoluteModAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 96 of file builtins-bigint-gen.h.
                                                               {
    TNode<ExternalReference> mutable_big_int_absolute_mod_and_canonicalize =
        ExternalConstant(
            ExternalReference::
                mutable_big_int_absolute_mod_and_canonicalize_function());
    TNode<Int32T> return_code = UncheckedCast<Int32T>(CallCFunction(
        mutable_big_int_absolute_mod_and_canonicalize, MachineType::Int32(),
        std::make_pair(MachineType::AnyTagged(), result),
        std::make_pair(MachineType::AnyTagged(), x),
        std::make_pair(MachineType::AnyTagged(), y)));
    return return_code;
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Int32(), v8::base::internal::result, and v8::internal::y.
CppAbsoluteMulAndCanonicalize()
TNode<Int32T> v8::internal::BigIntBuiltinsAssembler::CppAbsoluteMulAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 66 of file builtins-bigint-gen.h.
                                                               {
    TNode<ExternalReference> mutable_big_int_absolute_mul_and_canonicalize =
        ExternalConstant(
            ExternalReference::
                mutable_big_int_absolute_mul_and_canonicalize_function());
    TNode<Int32T> return_code = UncheckedCast<Int32T>(CallCFunction(
        mutable_big_int_absolute_mul_and_canonicalize, MachineType::Int32(),
        std::make_pair(MachineType::AnyTagged(), result),
        std::make_pair(MachineType::AnyTagged(), x),
        std::make_pair(MachineType::AnyTagged(), y)));
    return return_code;
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Int32(), v8::base::internal::result, and v8::internal::y.
CppAbsoluteSubAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppAbsoluteSubAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 53 of file builtins-bigint-gen.h.
                                                      {
    TNode<ExternalReference> mutable_big_int_absolute_sub_and_canonicalize =
        ExternalConstant(
            ExternalReference::
                mutable_big_int_absolute_sub_and_canonicalize_function());
    CallCFunction(mutable_big_int_absolute_sub_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseAndNegNegAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndNegNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 124 of file builtins-bigint-gen.h.
                                                           {
    TNode<ExternalReference>
        mutable_big_int_bitwise_and_neg_neg_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_and_nn_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_and_neg_neg_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseAndPosNegAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndPosNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 137 of file builtins-bigint-gen.h.
                                                           {
    TNode<ExternalReference>
        mutable_big_int_bitwise_and_pos_neg_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_and_pn_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_and_pos_neg_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseAndPosPosAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndPosPosAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 111 of file builtins-bigint-gen.h.
                                                           {
    TNode<ExternalReference>
        mutable_big_int_bitwise_and_pos_pos_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_and_pp_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_and_pos_pos_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseOrNegNegAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrNegNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 163 of file builtins-bigint-gen.h.
                                                          {
    TNode<ExternalReference>
        mutable_big_int_bitwise_or_neg_neg_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_or_nn_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_or_neg_neg_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseOrPosNegAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrPosNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 176 of file builtins-bigint-gen.h.
                                                          {
    TNode<ExternalReference>
        mutable_big_int_bitwise_or_pos_neg_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_or_pn_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_or_pos_neg_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseOrPosPosAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrPosPosAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 150 of file builtins-bigint-gen.h.
                                                          {
    TNode<ExternalReference>
        mutable_big_int_bitwise_or_pos_pos_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_or_pp_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_or_pos_pos_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseXorNegNegAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorNegNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 202 of file builtins-bigint-gen.h.
                                                           {
    TNode<ExternalReference>
        mutable_big_int_bitwise_xor_neg_neg_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_xor_nn_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_xor_neg_neg_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseXorPosNegAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorPosNegAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 215 of file builtins-bigint-gen.h.
                                                           {
    TNode<ExternalReference>
        mutable_big_int_bitwise_xor_pos_neg_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_xor_pn_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_xor_pos_neg_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppBitwiseXorPosPosAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorPosPosAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< BigInt > y) [inline]
Definition at line 189 of file builtins-bigint-gen.h.
                                                           {
    TNode<ExternalReference>
        mutable_big_int_bitwise_xor_pos_pos_and_canonicalize = ExternalConstant(
            ExternalReference::
                mutable_big_int_bitwise_xor_pp_and_canonicalize_function());
    CallCFunction(mutable_big_int_bitwise_xor_pos_pos_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::AnyTagged(), y));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::base::internal::result, and v8::internal::y.
CppLeftShiftAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppLeftShiftAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< IntPtrT > shift) [inline]
Definition at line 228 of file builtins-bigint-gen.h.
                                                         {
    TNode<ExternalReference> mutable_big_int_left_shift_and_canonicalize =
        ExternalConstant(
            ExternalReference::
                mutable_big_int_left_shift_and_canonicalize_function());
    CallCFunction(mutable_big_int_left_shift_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::IntPtr(), shift));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::IntPtr(), and v8::base::internal::result.
CppRightShiftAndCanonicalize()
void v8::internal::BigIntBuiltinsAssembler::CppRightShiftAndCanonicalize (TNode< BigInt > result, TNode< BigInt > x, TNode< IntPtrT > shift, TNode< Uint32T > must_round_down) [inline]
Definition at line 254 of file builtins-bigint-gen.h.
                                                                    {
    TNode<ExternalReference> mutable_big_int_right_shift_and_canonicalize =
        ExternalConstant(
            ExternalReference::
                mutable_big_int_right_shift_and_canonicalize_function());
    CallCFunction(mutable_big_int_right_shift_and_canonicalize,
                  MachineType::AnyTagged(),
                  std::make_pair(MachineType::AnyTagged(), result),
                  std::make_pair(MachineType::AnyTagged(), x),
                  std::make_pair(MachineType::IntPtr(), shift),
                  std::make_pair(MachineType::Uint32(), must_round_down));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::IntPtr(), v8::base::internal::result, and v8::internal::MachineType::Uint32().
CppRightShiftResultLength()
TNode<Uint32T> v8::internal::BigIntBuiltinsAssembler::CppRightShiftResultLength (TNode< BigInt > x, TNode< Uint32T > x_sign, TNode< IntPtrT > shift) [inline]
Definition at line 241 of file builtins-bigint-gen.h.
                                                                 {
    TNode<ExternalReference> big_int_right_shift_result_length =
        ExternalConstant(
            ExternalReference::big_int_right_shift_result_length_function());
    return UncheckedCast<Uint32T>(
        CallCFunction(big_int_right_shift_result_length, MachineType::Uint32(),
                      std::make_pair(MachineType::AnyTagged(), x),
                      std::make_pair(MachineType::Uint32(), x_sign),
                      std::make_pair(MachineType::IntPtr(), shift)));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::IntPtr(), and v8::internal::MachineType::Uint32().
ReadBigIntLength()
TNode<IntPtrT> v8::internal::BigIntBuiltinsAssembler::ReadBigIntLength (TNode< BigInt > value) [inline]
Definition at line 19 of file builtins-bigint-gen.h.
                                                       {
    TNode<Word32T> bitfield = LoadBigIntBitfield(value);
    return ChangeInt32ToIntPtr(
        Signed(DecodeWord32<BigIntBase::LengthBits>(bitfield)));
  }
References v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), v8::internal::CodeStubAssembler::LoadBigIntBitfield(), v8::internal::compiler::CodeAssembler::Signed(), and v8::internal::value.
ReadBigIntSign()
TNode<Uint32T> v8::internal::BigIntBuiltinsAssembler::ReadBigIntSign (TNode< BigInt > value) [inline]
Definition at line 25 of file builtins-bigint-gen.h.
                                                     {
    TNode<Word32T> bitfield = LoadBigIntBitfield(value);
    return DecodeWord32<BigIntBase::SignBits>(bitfield);
  }
References v8::internal::CodeStubAssembler::LoadBigIntBitfield(), and v8::internal::value.
WriteBigIntSignAndLength()
void v8::internal::BigIntBuiltinsAssembler::WriteBigIntSignAndLength (TNode< BigInt > bigint, TNode< Uint32T > sign, TNode< IntPtrT > length) [inline]
Definition at line 30 of file builtins-bigint-gen.h.
                                                       {
    static_assert(BigIntBase::SignBits::kShift == 0);
    TNode<Uint32T> bitfield = Unsigned(
        Word32Or(Word32Shl(TruncateIntPtrToInt32(length),
                           Int32Constant(BigIntBase::LengthBits::kShift)),
                 Word32And(sign, Int32Constant(BigIntBase::SignBits::kMask))));
    StoreBigIntBitfield(bigint, bitfield);
  }
References v8::internal::compiler::CodeAssembler::Int32Constant(), v8::base::BitField< T, shift, size, U >::kMask, v8::base::BitField< T, shift, size, U >::kShift, v8::internal::length, v8::internal::sign, v8::internal::CodeStubAssembler::StoreBigIntBitfield(), v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), v8::internal::compiler::CodeAssembler::Unsigned(), v8::internal::compiler::CodeAssembler::Word32And(), v8::internal::compiler::CodeAssembler::Word32Or(), and v8::internal::compiler::CodeAssembler::Word32Shl().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-bigint-gen.h