v8::internal::AllocationResult Class Reference
#include <allocation-result.h>
Public Member Functions
AllocationResult ()=default
bool IsFailure () const
template<typename T >
bool To (Tagged< T > *obj) const
Tagged< HeapObject > ToObjectChecked () const
Tagged< HeapObject > ToObject () const
Address ToAddress () const
operator bool () const
Static Public Member Functions
static AllocationResult Failure ()
static AllocationResult FromObject (Tagged< HeapObject > heap_object)
Private Member Functions
AllocationResult (Tagged< HeapObject > heap_object)
Private Attributes
Tagged< HeapObject > object_
Detailed Description
Definition at line 26 of file allocation-result.h.
Constructor & Destructor Documentation
AllocationResult() [1/2]
v8::internal::AllocationResult::AllocationResult () [default]
Referenced by Failure(), and FromObject().
AllocationResult() [2/2]
v8::internal::AllocationResult::AllocationResult (Tagged< HeapObject > heap_object) [inline], [explicit], [private]
Definition at line 65 of file allocation-result.h.
      : object_(heap_object) {}
Member Function Documentation
Failure()
static AllocationResult v8::internal::AllocationResult::Failure () [inline], [static]
Definition at line 28 of file allocation-result.h.
{ return AllocationResult(); }
References AllocationResult().
Referenced by v8::internal::MainAllocator::AllocateFastAligned(), v8::internal::MainAllocator::AllocateFastUnaligned(), v8::internal::HeapAllocator::AllocateRaw(), v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::MainAllocator::AllocateRawSlowAligned(), and v8::internal::MainAllocator::AllocateRawSlowUnaligned().
FromObject()
static AllocationResult v8::internal::AllocationResult::FromObject (Tagged< HeapObject > heap_object) [inline], [static]
Definition at line 30 of file allocation-result.h.
                                                                     {
    return AllocationResult(heap_object);
  }
References AllocationResult().
Referenced by v8::internal::Heap::Allocate(), v8::internal::MainAllocator::AllocateFastAligned(), v8::internal::MainAllocator::AllocateFastUnaligned(), v8::internal::Heap::AllocateMap(), v8::internal::Heap::AllocatePartialMap(), v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::ReadOnlySpace::AllocateRawAligned(), and v8::internal::ReadOnlySpace::AllocateRawUnaligned().
IsFailure()
bool v8::internal::AllocationResult::IsFailure () const [inline]
Definition at line 38 of file allocation-result.h.
{ return object_.is_null(); }
References v8::internal::Tagged< HeapObject >::is_null(), and object_.
Referenced by v8::internal::EvacuateNewSpaceVisitor::AllocateInOldSpace(), v8::internal::HeapAllocator::AllocateRaw(), v8::internal::EvacuateNewSpaceVisitor::AllocateTargetObject(), operator bool(), To(), ToAddress(), ToObject(), and ToObjectChecked().
operator bool()
v8::internal::AllocationResult::operator bool () const [inline], [explicit]
Definition at line 62 of file allocation-result.h.
{ return !IsFailure(); }
References IsFailure().
To()
template<typename T >
bool v8::internal::AllocationResult::To (Tagged< T > * obj) const [inline]
Definition at line 41 of file allocation-result.h.
                                {
    if (IsFailure()) return false;
    *obj = Cast<T>(object_);
    return true;
  }
References IsFailure(), and object_.
Referenced by v8::internal::Heap::Allocate(), v8::internal::Heap::AllocateMap(), v8::internal::Heap::AllocatePartialMap(), v8::internal::HeapAllocator::AllocateRaw(), v8::internal::EvacuateNewSpaceVisitor::AllocateTargetObject(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::Heap::CreateLateReadOnlyNonJSReceiverMaps(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::Scavenger::PromoteObject(), v8::internal::Scavenger::SemiSpaceCopyObject(), v8::internal::EvacuateVisitorBase::TryEvacuateObject(), and v8::internal::Factory::TryNewFixedArray().
ToAddress()
Address v8::internal::AllocationResult::ToAddress () const [inline]
Definition at line 57 of file allocation-result.h.
                            {
    DCHECK(!IsFailure());
    return Cast<HeapObject>(object_).address();
  }
References v8::internal::DCHECK(), IsFailure(), and object_.
ToObject()
Tagged<HeapObject> v8::internal::AllocationResult::ToObject () const [inline]
Definition at line 52 of file allocation-result.h.
                                      {
    DCHECK(!IsFailure());
    return Cast<HeapObject>(object_);
  }
References v8::internal::DCHECK(), IsFailure(), and object_.
Referenced by v8::internal::HeapAllocator::AllocateRaw().
ToObjectChecked()
Tagged<HeapObject> v8::internal::AllocationResult::ToObjectChecked () const [inline]
Definition at line 47 of file allocation-result.h.
                                             {
    CHECK(!IsFailure());
    return Cast<HeapObject>(object_);
  }
References CHECK, IsFailure(), and object_.
Referenced by v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::CopyToReadOnlyHeap().
Member Data Documentation
object_
Tagged<HeapObject> v8::internal::AllocationResult::object_ [private]
Definition at line 68 of file allocation-result.h.
Referenced by IsFailure(), To(), ToAddress(), ToObject(), and ToObjectChecked().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/allocation-result.h