v8::base::Stack Class Reference
#include <platform.h>
Classes
struct PreventNonDefaultParameters
struct StackSlot
Static Public Member Functions
static StackSlot GetStackStart ()
static V8_NOINLINE StackSlot GetCurrentStackPosition ()
static StackSlot GetCurrentFrameAddress (PreventNonDefaultParameters=PreventNonDefaultParameters(), void *frame_address=DEFAULT_CURRENT_FRAME_ADDRESS)
static StackSlot GetRealStackAddressForSlot (StackSlot slot)
Static Private Member Functions
static StackSlot GetStackStartUnchecked ()
static Stack::StackSlot ObtainCurrentThreadStackStart ()
Friends
class heap::base::Stack
Detailed Description
Definition at line 647 of file platform.h.
Member Function Documentation
GetCurrentFrameAddress()
static StackSlot v8::base::Stack::GetCurrentFrameAddress (PreventNonDefaultParameters = PreventNonDefaultParameters(), void * frame_address = DEFAULT_CURRENT_FRAME_ADDRESS) [inline], [static]
Definition at line 684 of file platform.h.
                                                           {
    return frame_address;
  }
GetCurrentStackPosition()
Stack::StackSlot v8::base::Stack::GetCurrentStackPosition () [static]
Definition at line 1455 of file platform-posix.cc.
                                              {
  return __builtin_frame_address(0);
}
Referenced by heap::base::Stack::IsOnStack().
GetRealStackAddressForSlot()
static StackSlot v8::base::Stack::GetRealStackAddressForSlot (StackSlot slot) [inline], [static]
Definition at line 694 of file platform.h.
                                                              {
#ifdef V8_USE_ADDRESS_SANITIZER
    // ASAN fetches the real stack deeper in the __asan_addr_is_in_fake_stack()
    // call (precisely, deeper in __asan_stack_malloc_()), which results in a
    // real frame that could be outside of stack bounds. Adjust for this
    // impreciseness here.
    constexpr size_t kAsanRealFrameOffsetBytes = 32;
    void* real_frame = __asan_addr_is_in_fake_stack(
        __asan_get_current_fake_stack(), slot, nullptr, nullptr);
    return real_frame ? StackSlot(static_cast<char*>(real_frame) +
                                  kAsanRealFrameOffsetBytes)
                      : slot;
#endif // V8_USE_ADDRESS_SANITIZER
    return slot;
  }
GetStackStart()
Stack::StackSlot v8::base::Stack::GetStackStart () [static]
Definition at line 489 of file platform-starboard.cc.
                                    {
  SB_NOTIMPLEMENTED();
  return nullptr;
}
Referenced by v8::internal::ConservativePinningScope::ConservativePinningScope(), v8::Isolate::Initialize(), v8::internal::StackGuard::ThreadLocal::Initialize(), heap::base::Stack::SetMarkerForBackgroundThreadAndCallbackImpl(), v8::Isolate::SetStackLimit(), and heap::base::Stack::SetStackStart().
GetStackStartUnchecked()
Stack::StackSlot v8::base::Stack::GetStackStartUnchecked () [static], [private]
Definition at line 18 of file platform.cc.
                                             {
  if (!thread_stack_start) {
    thread_stack_start = ObtainCurrentThreadStackStart();
  }
  return thread_stack_start;
}
References ObtainCurrentThreadStackStart(), and v8::base::anonymous_namespace{platform.cc}::thread_stack_start.
Referenced by heap::base::Stack::IsOnStack().
ObtainCurrentThreadStackStart()
Stack::StackSlot v8::base::Stack::ObtainCurrentThreadStackStart () [static], [private]
Definition at line 139 of file platform-aix.cc.
                                                    {
  // pthread_getthrds_np creates 3 values:
  // __pi_stackaddr, __pi_stacksize, __pi_stackend
  // higher address ----- __pi_stackend, stack base
  //
  // |
  // | __pi_stacksize, stack grows downwards
  // |
  // V
  //
  // lower address ----- __pi_stackaddr, current sp
  pthread_t tid = pthread_self();
  struct __pthrdsinfo buf;
  // clear buf
  memset(&buf, 0, sizeof(buf));
  char regbuf[1];
  int regbufsize = sizeof(regbuf);
  const int rc = pthread_getthrds_np(&tid, PTHRDSINFO_QUERY_ALL, &buf,
                                     sizeof(buf), regbuf, &regbufsize);
  CHECK(!rc);
  if (buf.__pi_stackend == NULL || buf.__pi_stackaddr == NULL) {
    return nullptr;
  }
  return reinterpret_cast<void*>(buf.__pi_stackend);
}
References CHECK.
Referenced by GetStackStartUnchecked().
Friends And Related Function Documentation
heap::base::Stack
friend class heap::base::Stack [friend]
Definition at line 715 of file platform.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/platform.h
/mnt/V8SourceCode/src/base/platform/platform-aix.cc
/mnt/V8SourceCode/src/base/platform/platform-darwin.cc
/mnt/V8SourceCode/src/base/platform/platform-freebsd.cc
/mnt/V8SourceCode/src/base/platform/platform-posix.cc
/mnt/V8SourceCode/src/base/platform/platform-solaris.cc
/mnt/V8SourceCode/src/base/platform/platform-starboard.cc
/mnt/V8SourceCode/src/base/platform/platform-win32.cc
/mnt/V8SourceCode/src/base/platform/platform.cc