v8::internal::maglev::LoadSignedIntDataViewElement Class Reference
#include <maglev-ir.h>
Public Member Functions
LoadSignedIntDataViewElement (uint64_t bitfield, ExternalArrayType type)
Input & object_input ()
Input & index_input ()
Input & is_little_endian_input ()
bool is_little_endian_constant ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
ExternalArrayType type () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kObjectIndex = 0
static constexpr int kIndexIndex = 1
static constexpr int kIsLittleEndianIndex = 2
Private Types
using Base = FixedInputValueNodeT< 3, LoadSignedIntDataViewElement >
Private Attributes
ExternalArrayType type_
Additional Inherited Members
Detailed Description
Definition at line 8587 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::LoadSignedIntDataViewElement::Base = FixedInputValueNodeT<3, LoadSignedIntDataViewElement> [private]
Definition at line 8589 of file maglev-ir.h.
Constructor & Destructor Documentation
LoadSignedIntDataViewElement()
v8::internal::maglev::LoadSignedIntDataViewElement::LoadSignedIntDataViewElement (uint64_t bitfield, ExternalArrayType type) [inline], [explicit]
Definition at line 8592 of file maglev-ir.h.
      : Base(bitfield), type_(type) {
    DCHECK(type == ExternalArrayType::kExternalInt8Array ||
           type == ExternalArrayType::kExternalInt16Array ||
           type == ExternalArrayType::kExternalInt32Array);
  }
References DCHECK, v8::internal::kExternalInt16Array, v8::internal::kExternalInt32Array, v8::internal::kExternalInt8Array, and v8::internal::tracing::type.
Member Function Documentation
GenerateCode()
void v8::internal::maglev::LoadSignedIntDataViewElement::GenerateCode (MaglevAssembler * , const ProcessingState &)
index_input()
Input& v8::internal::maglev::LoadSignedIntDataViewElement::index_input () [inline]
Definition at line 8610 of file maglev-ir.h.
{ return input(kIndexIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
is_little_endian_constant()
bool v8::internal::maglev::LoadSignedIntDataViewElement::is_little_endian_constant () [inline]
Definition at line 8613 of file maglev-ir.h.
                                   {
    return IsConstantNode(is_little_endian_input().node()->opcode());
  }
References v8::internal::maglev::IsConstantNode().
is_little_endian_input()
Input& v8::internal::maglev::LoadSignedIntDataViewElement::is_little_endian_input () [inline]
Definition at line 8611 of file maglev-ir.h.
{ return input(kIsLittleEndianIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
object_input()
Input& v8::internal::maglev::LoadSignedIntDataViewElement::object_input () [inline]
Definition at line 8609 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::LoadSignedIntDataViewElement::options () const [inline]
Definition at line 8621 of file maglev-ir.h.
{ return std::tuple{type_}; }
PrintParams()
void v8::internal::maglev::LoadSignedIntDataViewElement::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 8619 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::LoadSignedIntDataViewElement::SetValueLocationConstraints ()
type()
ExternalArrayType v8::internal::maglev::LoadSignedIntDataViewElement::type () const [inline]
Definition at line 8623 of file maglev-ir.h.
{ return type_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kIndexIndex
constexpr int v8::internal::maglev::LoadSignedIntDataViewElement::kIndexIndex = 1 [static], [constexpr]
Definition at line 8607 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::LoadSignedIntDataViewElement::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kInt32,
      ValueRepresentation::kTagged}
Definition at line 8602 of file maglev-ir.h.
kIsLittleEndianIndex
constexpr int v8::internal::maglev::LoadSignedIntDataViewElement::kIsLittleEndianIndex = 2 [static], [constexpr]
Definition at line 8608 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::LoadSignedIntDataViewElement::kObjectIndex = 0 [static], [constexpr]
Definition at line 8606 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::LoadSignedIntDataViewElement::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanRead() | OpProperties::Int32()
Definition at line 8600 of file maglev-ir.h.
type_
ExternalArrayType v8::internal::maglev::LoadSignedIntDataViewElement::type_ [private]
Definition at line 8626 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h