v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters Class Reference
#include <liftoff-assembler-arm-inl.h>
Public Member Functions
CacheStatePreservingTempRegisters (LiftoffAssembler *assm, LiftoffRegList pinned={})
~CacheStatePreservingTempRegisters ()
Register Acquire ()
CacheStatePreservingTempRegisters (LiftoffAssembler *assm, LiftoffRegList pinned={})
~CacheStatePreservingTempRegisters ()
Register Acquire ()
Private Attributes
LiftoffAssembler *const assm_
LiftoffRegList pinned_
RegList must_pop_
Detailed Description
Definition at line 425 of file liftoff-assembler-arm-inl.h.
Constructor & Destructor Documentation
CacheStatePreservingTempRegisters() [1/2]
v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::CacheStatePreservingTempRegisters (LiftoffAssembler * assm, LiftoffRegList pinned = {}) [inline], [explicit]
Definition at line 427 of file liftoff-assembler-arm-inl.h.
                                                                     {})
      : assm_(assm), pinned_(pinned) {}
 CacheStatePreservingTempRegisters() [1/2]
v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::~CacheStatePreservingTempRegisters () [inline]
Definition at line 431 of file liftoff-assembler-arm-inl.h.
                                       {
    for (Register reg : must_pop_) {
      assm_->Pop(reg);
    }
  }
CacheStatePreservingTempRegisters() [2/2]
v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::CacheStatePreservingTempRegisters (LiftoffAssembler * assm, LiftoffRegList pinned = {}) [inline], [explicit]
Definition at line 183 of file liftoff-assembler-ia32-inl.h.
                                                                     {})
      : assm_(assm), pinned_(pinned) {}
 CacheStatePreservingTempRegisters() [2/2]
v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::~CacheStatePreservingTempRegisters () [inline]
Definition at line 187 of file liftoff-assembler-ia32-inl.h.
                                       {
    for (Register reg : must_pop_) {
      assm_->pop(reg);
    }
  }
References assm_, must_pop_, and v8::internal::MacroAssembler::pop().
Member Function Documentation
Acquire() [1/2]
Register v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire () [inline]
Definition at line 437 of file liftoff-assembler-arm-inl.h.
                     {
    if (assm_->cache_state()->has_unused_register(kGpReg, pinned_)) {
      return pinned_.set(
          assm_->cache_state()->unused_register(kGpReg, pinned_).gp());
    }
    RegList available =
        kLiftoffAssemblerGpCacheRegs - pinned_.GetGpList() - must_pop_;
    DCHECK(!available.is_empty());
    // Use {last()} here so we can just iterate forwards in the destructor.
    Register reg = available.last();
    assm_->Push(reg);
    must_pop_.set(reg);
    return reg;
  }
References available(), v8::internal::DCHECK(), v8::internal::wasm::kGpReg, and v8::internal::wasm::kLiftoffAssemblerGpCacheRegs.
Acquire() [2/2]
Register v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire () [inline]
Definition at line 193 of file liftoff-assembler-ia32-inl.h.
                     {
    if (assm_->cache_state()->has_unused_register(kGpReg, pinned_)) {
      return pinned_.set(
          assm_->cache_state()->unused_register(kGpReg, pinned_).gp());
    }
    RegList available =
        kLiftoffAssemblerGpCacheRegs - pinned_.GetGpList() - must_pop_;
    DCHECK(!available.is_empty());
    // Use {last()} here so we can just iterate forwards in the destructor.
    Register reg = available.last();
    assm_->push(reg);
    must_pop_.set(reg);
    return reg;
  }
References assm_, available(), v8::internal::wasm::LiftoffAssembler::cache_state(), v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegList::GetGpList(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register(), v8::internal::wasm::kGpReg, v8::internal::wasm::kLiftoffAssemblerGpCacheRegs, must_pop_, pinned_, v8::internal::MacroAssembler::push(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::RegListBase< RegisterT >::set(), and v8::internal::wasm::LiftoffAssembler::CacheState::unused_register().
Member Data Documentation
assm_
LiftoffAssembler *const v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::assm_ [private]
Definition at line 454 of file liftoff-assembler-arm-inl.h.
Referenced by Acquire(), and ~CacheStatePreservingTempRegisters().
must_pop_
RegList v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::must_pop_ [private]
Definition at line 456 of file liftoff-assembler-arm-inl.h.
Referenced by Acquire(), and ~CacheStatePreservingTempRegisters().
pinned_
LiftoffRegList v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::pinned_ [private]
Definition at line 455 of file liftoff-assembler-arm-inl.h.
Referenced by Acquire().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/baseline/arm/liftoff-assembler-arm-inl.h
/mnt/V8SourceCode/src/wasm/baseline/ia32/liftoff-assembler-ia32-inl.h