v8::internal::compiler::CodeAssemblerVariable Class Reference
#include <code-assembler.h>
Classes
class Impl
struct ImplComparator
Public Member Functions
CodeAssemblerVariable (const CodeAssemblerVariable &)=delete
CodeAssemblerVariable & operator= (const CodeAssemblerVariable &)=delete
Node * value () const
MachineRepresentation rep () const
bool IsBound () const
Protected Member Functions
CodeAssemblerVariable (CodeAssembler *assembler, MachineRepresentation rep)
CodeAssemblerVariable (CodeAssembler *assembler, MachineRepresentation rep, Node *initial_value)
~CodeAssemblerVariable ()
void Bind (Node *value)
Private Attributes
Impl * impl_
CodeAssemblerState * state_
Friends
class CodeAssemblerLabel
class CodeAssemblerState
std::ostream & operator<< (std::ostream &, const Impl &)
std::ostream & operator<< (std::ostream &, const CodeAssemblerVariable &)
Detailed Description
Definition at line 1681 of file code-assembler.h.
Constructor & Destructor Documentation
CodeAssemblerVariable() [1/3]
v8::internal::compiler::CodeAssemblerVariable::CodeAssemblerVariable (const CodeAssemblerVariable &) [delete]
CodeAssemblerVariable() [2/3]
v8::internal::compiler::CodeAssemblerVariable::CodeAssemblerVariable (CodeAssembler * assembler, MachineRepresentation rep) [explicit], [protected]
Definition at line 1723 of file code-assembler.cc.
    : impl_(assembler->zone()->New<Impl>(rep,
                                         assembler->state()->NextVariableId())),
      state_(assembler->state()) {
  state_->variables_.insert(impl_);
}
References impl_, state_, and v8::internal::compiler::CodeAssemblerState::variables_.
CodeAssemblerVariable() [3/3]
v8::internal::compiler::CodeAssemblerVariable::CodeAssemblerVariable (CodeAssembler * assembler, MachineRepresentation rep, Node * initial_value) [protected]
Definition at line 1731 of file code-assembler.cc.
    : CodeAssemblerVariable(assembler, rep) {
  Bind(initial_value);
}
References Bind().
 CodeAssemblerVariable()
v8::internal::compiler::CodeAssemblerVariable::~CodeAssemblerVariable () [protected]
Definition at line 1759 of file code-assembler.cc.
                                              {
  state_->variables_.erase(impl_);
}
Member Function Documentation
Bind()
void v8::internal::compiler::CodeAssemblerVariable::Bind (Node * value) [protected]
Definition at line 1763 of file code-assembler.cc.
{ impl_->value_ = value; }
References v8::internal::value.
Referenced by CodeAssemblerVariable().
IsBound()
bool v8::internal::compiler::CodeAssemblerVariable::IsBound () const
Definition at line 1786 of file code-assembler.cc.
{ return impl_->value_ != nullptr; }
Referenced by v8::internal::AccessorAssembler::TryMegaDOMCase().
operator=()
CodeAssemblerVariable& v8::internal::compiler::CodeAssemblerVariable::operator= (const CodeAssemblerVariable &) [delete]
rep()
MachineRepresentation v8::internal::compiler::CodeAssemblerVariable::rep () const
Definition at line 1784 of file code-assembler.cc.
{ return impl_->rep_; }
Referenced by v8::internal::RegExpBuiltinsAssembler::GetStringPointers(), v8::internal::AccessorAssembler::HandlePolymorphicCase(), v8::internal::AccessorAssembler::LoadIC_Noninlined(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::CodeStubAssembler::TryGetOwnProperty(), and v8::internal::AccessorAssembler::TryMonomorphicCase().
value()
Node * v8::internal::compiler::CodeAssemblerVariable::value () const
Definition at line 1765 of file code-assembler.cc.
                                         {
#if DEBUG
  if (!IsBound()) {
    std::stringstream str;
    str << "#Use of unbound variable:"
        << "#\n Variable: " << *this << "#\n Current Block: ";
    state_->PrintCurrentBlock(str);
    FATAL("%s", str.str().c_str());
  }
  if (!state_->InsideBlock()) {
    std::stringstream str;
    str << "#Accessing variable value outside a block:"
        << "#\n Variable: " << *this;
    FATAL("%s", str.str().c_str());
  }
#endif // DEBUG
  return impl_->value_;
}
References FATAL.
Referenced by v8::internal::compiler::TypedCodeAssemblerVariable< T >::value().
Friends And Related Function Documentation
CodeAssemblerLabel
friend class CodeAssemblerLabel [friend]
Definition at line 1707 of file code-assembler.h.
CodeAssemblerState
friend class CodeAssemblerState [friend]
Definition at line 1708 of file code-assembler.h.
operator<< [1/2]
std::ostream& operator<< (std::ostream & , const CodeAssemblerVariable &) [friend]
Definition at line 1797 of file code-assembler.cc.
                                                                {
  os << *variable.impl_;
  return os;
}
operator<< [2/2]
std::ostream& operator<< (std::ostream & , const Impl &) [friend]
Definition at line 1788 of file code-assembler.cc.
                                                                {
#if DEBUG
  AssemblerDebugInfo info = impl.debug_info();
  if (info.name) os << "V" << info;
#endif // DEBUG
  return os;
}
Member Data Documentation
impl_
Impl* v8::internal::compiler::CodeAssemblerVariable::impl_ [private]
Definition at line 1715 of file code-assembler.h.
Referenced by v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel(), and CodeAssemblerVariable().
state_
CodeAssemblerState* v8::internal::compiler::CodeAssemblerVariable::state_ [private]
Definition at line 1716 of file code-assembler.h.
Referenced by CodeAssemblerVariable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/code-assembler.h
/mnt/V8SourceCode/src/compiler/code-assembler.cc