v8::internal::ModuleRequest Class Reference
#include <source-text-module.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Public Member Functions
void set_phase (ModuleImportPhase phase)
ModuleImportPhase phase () const
Static Public Member Functions
template<typename IsolateT >
static Handle< ModuleRequest > New (IsolateT *isolate, DirectHandle< String > specifier, ModuleImportPhase phase, DirectHandle< FixedArray > import_attributes, int position)
Static Public Attributes
static const size_t kAttributeEntrySize = 3
Detailed Description
Definition at line 278 of file source-text-module.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::ModuleRequest::BodyDescriptor = StructBodyDescriptor
Definition at line 302 of file source-text-module.h.
Member Function Documentation
New()
template<typename IsolateT >
template Handle< ModuleRequest > v8::internal::ModuleRequest::New (IsolateT * isolate, DirectHandle< String > specifier, ModuleImportPhase phase, DirectHandle< FixedArray > import_attributes, int position) [static]
Definition at line 1195 of file scope-info.cc.
                                                              {
  auto result = Cast<ModuleRequest>(
      isolate->factory()->NewStruct(MODULE_REQUEST_TYPE, AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  Tagged<ModuleRequest> raw = *result;
  raw->set_specifier(*specifier);
  raw->set_import_attributes(*import_attributes);
  raw->set_flags(0);
  raw->set_phase(phase);
  DCHECK_GE(position, 0);
  raw->set_position(position);
  return result;
}
References DCHECK_GE, v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, phase(), and v8::base::internal::result.
Referenced by v8::internal::SourceTextModuleDescriptor::AstModuleRequest::Serialize().
phase()
ModuleImportPhase v8::internal::ModuleRequest::phase () const [inline]
Definition at line 45 of file module-inl.h.
                                                    {
  return PhaseBit::decode(flags());
}
References v8::internal::flags.
Referenced by New().
set_phase()
void v8::internal::ModuleRequest::set_phase (ModuleImportPhase phase) [inline]
Member Data Documentation
kAttributeEntrySize
const size_t v8::internal::ModuleRequest::kAttributeEntrySize = 3 [static]
Definition at line 292 of file source-text-module.h.
Referenced by v8::internal::SourceTextModuleDescriptor::AstModuleRequest::Serialize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/source-text-module.h
/mnt/V8SourceCode/src/objects/module-inl.h
/mnt/V8SourceCode/src/objects/scope-info.cc