v8::internal::HeapObjectRange::iterator Class Reference
#include <paged-spaces.h>
Public Types
using value_type = Tagged< HeapObject >
using pointer = const value_type *
using reference = const value_type &
using iterator_category = std::forward_iterator_tag
Public Member Functions
iterator ()
iterator (const PageMetadata *page)
iterator & operator++ ()
iterator operator++ (int)
bool operator== (iterator other) const
bool operator!= (iterator other) const
value_type operator* ()
Private Member Functions
void AdvanceToNextObject ()
PtrComprCageBase cage_base () const
Private Attributes
PtrComprCageBase cage_base_
Address cur_addr_ = kNullAddress
int cur_size_ = 0
Address cur_end_ = kNullAddress
Detailed Description
Definition at line 41 of file paged-spaces.h.
Member Typedef Documentation
iterator_category
using v8::internal::HeapObjectRange::iterator::iterator_category = std::forward_iterator_tag
Definition at line 46 of file paged-spaces.h.
pointer
using v8::internal::HeapObjectRange::iterator::pointer = const value_type*
Definition at line 44 of file paged-spaces.h.
reference
using v8::internal::HeapObjectRange::iterator::reference = const value_type&
Definition at line 45 of file paged-spaces.h.
value_type
using v8::internal::HeapObjectRange::iterator::value_type = Tagged<HeapObject>
Definition at line 43 of file paged-spaces.h.
Constructor & Destructor Documentation
iterator() [1/2]
v8::internal::HeapObjectRange::iterator::iterator () [inline]
Definition at line 20 of file paged-spaces-inl.h.
: cage_base_(kNullAddress) {}
iterator() [2/2]
v8::internal::HeapObjectRange::iterator::iterator (const PageMetadata * page) [inline], [explicit]
Definition at line 22 of file paged-spaces-inl.h.
    : cage_base_(page->heap()->isolate()),
      cur_addr_(page->area_start()),
      cur_end_(page->area_end()) {
  AdvanceToNextObject();
}
References AdvanceToNextObject().
Member Function Documentation
AdvanceToNextObject()
void v8::internal::HeapObjectRange::iterator::AdvanceToNextObject () [inline], [private]
Definition at line 42 of file paged-spaces-inl.h.
                                                  {
  DCHECK_NE(cur_addr_, kNullAddress);
  while (cur_addr_ != cur_end_) {
    DCHECK_LT(cur_addr_, cur_end_);
    Tagged<HeapObject> obj = HeapObject::FromAddress(cur_addr_);
    cur_size_ = ALIGN_TO_ALLOCATION_ALIGNMENT(obj->Size(cage_base()));
    DCHECK_LE(cur_addr_ + cur_size_, cur_end_);
    if (IsFreeSpaceOrFiller(obj, cage_base())) {
      cur_addr_ += cur_size_;
    } else {
      if (IsInstructionStream(obj, cage_base())) {
        DCHECK_EQ(PageMetadata::FromHeapObject(obj)->owner_identity(),
                  CODE_SPACE);
        DCHECK_CODEOBJECT_SIZE(cur_size_);
      } else {
        DCHECK_OBJECT_SIZE(cur_size_);
      }
      return;
    }
  }
  cur_addr_ = kNullAddress;
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::CODE_SPACE, DCHECK_CODEOBJECT_SIZE, DCHECK_EQ, DCHECK_LE, DCHECK_LT, DCHECK_NE, DCHECK_OBJECT_SIZE, v8::internal::HeapObject::FromAddress(), v8::internal::PageMetadata::FromHeapObject(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), and v8::internal::kNullAddress.
Referenced by iterator().
cage_base()
PtrComprCageBase v8::internal::HeapObjectRange::iterator::cage_base () const [inline], [private]
Definition at line 64 of file paged-spaces.h.
{ return cage_base_; }
References cage_base_.
operator!=()
bool v8::internal::HeapObjectRange::iterator::operator!= (iterator other) const [inline]
Definition at line 57 of file paged-spaces.h.
{ return !(*this == other); }
operator*()
value_type v8::internal::HeapObjectRange::iterator::operator* () [inline]
Definition at line 59 of file paged-spaces.h.
{ return HeapObject::FromAddress(cur_addr_); }
References cur_addr_, and v8::internal::HeapObject::FromAddress().
operator++() [1/2]
HeapObjectRange::iterator & v8::internal::HeapObjectRange::iterator::operator++ () [inline]
Definition at line 29 of file paged-spaces-inl.h.
                                                             {
  DCHECK_GT(cur_size_, 0);
  cur_addr_ += cur_size_;
  AdvanceToNextObject();
  return *this;
}
References DCHECK_GT.
operator++() [2/2]
HeapObjectRange::iterator v8::internal::HeapObjectRange::iterator::operator++ (int) [inline]
Definition at line 36 of file paged-spaces-inl.h.
                                                               {
  iterator retval = *this;
  ++(*this);
  return retval;
}
operator==()
bool v8::internal::HeapObjectRange::iterator::operator== (iterator other) const [inline]
Definition at line 54 of file paged-spaces.h.
                                          {
      return cur_addr_ == other.cur_addr_;
    }
References cur_addr_.
Member Data Documentation
cage_base_
PtrComprCageBase v8::internal::HeapObjectRange::iterator::cage_base_ [private]
Definition at line 66 of file paged-spaces.h.
Referenced by cage_base().
cur_addr_
Address v8::internal::HeapObjectRange::iterator::cur_addr_ = kNullAddress [private]
Definition at line 67 of file paged-spaces.h.
Referenced by operator*(), and operator==().
cur_end_
Address v8::internal::HeapObjectRange::iterator::cur_end_ = kNullAddress [private]
Definition at line 69 of file paged-spaces.h.
cur_size_
int v8::internal::HeapObjectRange::iterator::cur_size_ = 0 [private]
Definition at line 68 of file paged-spaces.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/paged-spaces.h
/mnt/V8SourceCode/src/heap/paged-spaces-inl.h