v8::internal::compiler::StructuralType Class Reference
#include <turbofan-types.h>
Public Member Functions
int LengthForTesting () const
Protected Member Functions
int Length () const
Type Get (int i) const
void Set (int i, Type type)
void Shrink (int length)
StructuralType (Kind kind, int length, Zone *zone)
Private Attributes
int length_
Type * elements_
Friends
class Type
Additional Inherited Members
Detailed Description
Definition at line 658 of file turbofan-types.h.
Constructor & Destructor Documentation
StructuralType()
v8::internal::compiler::StructuralType::StructuralType (Kind kind, int length, Zone * zone) [inline], [protected]
Definition at line 682 of file turbofan-types.h.
      : TypeBase(kind), length_(length) {
    elements_ = zone->AllocateArray<Type>(length);
  }
References v8::internal::Zone::AllocateArray(), elements_, and v8::internal::length.
Member Function Documentation
Get()
Type v8::internal::compiler::StructuralType::Get (int i) const [inline], [protected]
Definition at line 667 of file turbofan-types.h.
                        {
    DCHECK(0 <= i && i < this->Length());
    return elements_[i];
  }
References v8::internal::DCHECK(), elements_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and Length().
Referenced by v8::internal::compiler::TupleType::Element(), and v8::internal::compiler::UnionType::Wellformed().
Length()
int v8::internal::compiler::StructuralType::Length () const [inline], [protected]
Definition at line 665 of file turbofan-types.h.
{ return length_; }
References length_.
Referenced by v8::internal::compiler::TupleType::Arity(), Get(), LengthForTesting(), Set(), Shrink(), and v8::internal::compiler::UnionType::Wellformed().
LengthForTesting()
int v8::internal::compiler::StructuralType::LengthForTesting () const [inline]
Definition at line 660 of file turbofan-types.h.
{ return Length(); }
References Length().
Set()
void v8::internal::compiler::StructuralType::Set (int i, Type type) [inline], [protected]
Definition at line 672 of file turbofan-types.h.
                             {
    DCHECK(0 <= i && i < this->Length());
    elements_[i] = type;
  }
References v8::internal::DCHECK(), elements_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, Length(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::TupleType::InitElement().
Shrink()
void v8::internal::compiler::StructuralType::Shrink (int length) [inline], [protected]
Definition at line 677 of file turbofan-types.h.
                          {
    DCHECK(2 <= length && length <= this->Length());
    length_ = length;
  }
References v8::internal::DCHECK(), v8::internal::length, Length(), and length_.
Friends And Related Function Documentation
Type
friend class Type [friend]
Definition at line 663 of file turbofan-types.h.
Member Data Documentation
elements_
Type* v8::internal::compiler::StructuralType::elements_ [private]
Definition at line 689 of file turbofan-types.h.
Referenced by Get(), Set(), and StructuralType().
length_
int v8::internal::compiler::StructuralType::length_ [private]
Definition at line 688 of file turbofan-types.h.
Referenced by Length(), and Shrink().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turbofan-types.h