v8::internal::compiler::Revectorizer Class Reference
#include <revectorizer.h>
Public Member Functions
Revectorizer (Zone *zone, TFGraph *graph, MachineGraph *mcgraph, SourcePositionTable *source_positions)
void DetectCPUFeatures ()
bool TryRevectorize (const char *name)
Private Member Functions
void CollectSeeds ()
bool ReduceStoreChains (ZoneMap< Node *, StoreNodeSet > *store_chains)
bool ReduceStoreChain (const ZoneVector< Node * > &Stores)
void PrintStores (ZoneMap< Node *, StoreNodeSet > *store_chains)
Zone * zone () const
TFGraph * graph () const
MachineGraph * mcgraph () const
PackNode * GetPackNode (Node *node) const
bool DecideVectorize ()
void SetEffectInput (PackNode *pnode, int index, Node *&nput)
void SetMemoryOpInputs (base::SmallVector< Node *, 2 > &inputs, PackNode *pnode, int index)
Node * VectorizeTree (PackNode *pnode)
void UpdateSources ()
Private Attributes
Zone *const zone_
TFGraph *const graph_
MachineGraph *const mcgraph_
ZoneMap< Node *, ZoneMap< Node *, StoreNodeSet > * > group_of_stores_
std::unordered_set< Node * > sources_
SLPTree * slp_tree_
SourcePositionTable * source_positions_
bool support_simd256_
compiler::NodeObserver * node_observer_for_test_
Detailed Description
Definition at line 163 of file revectorizer.h.
Constructor & Destructor Documentation
Revectorizer()
v8::internal::compiler::Revectorizer::Revectorizer (Zone * zone, TFGraph * graph, MachineGraph * mcgraph, SourcePositionTable * source_positions)
Definition at line 887 of file revectorizer.cc.
    : zone_(zone),
      graph_(graph),
      mcgraph_(mcgraph),
      group_of_stores_(zone),
      source_positions_(source_positions),
      support_simd256_(false) {
  DetectCPUFeatures();
  slp_tree_ = zone_->New<SLPTree>(zone, graph);
  Isolate* isolate = Isolate::TryGetCurrent();
  node_observer_for_test_ = isolate ? isolate->node_observer() : nullptr;
}
References DetectCPUFeatures(), graph(), v8::internal::Zone::New(), node_observer_for_test_, slp_tree_, v8::Isolate::TryGetCurrent(), zone(), and zone_.
Member Function Documentation
CollectSeeds()
void v8::internal::compiler::Revectorizer::CollectSeeds () [private]
Definition at line 1355 of file revectorizer.cc.
                                {
  for (auto it = graph_->GetSimdStoreNodes().begin();
       it != graph_->GetSimdStoreNodes().end(); ++it) {
    Node* node = *it;
    Node* dominator = slp_tree_->GetEarlySchedulePosition(node);
    if ((GetMemoryOffsetValue(node) % kSimd128Size) != 0) {
      continue;
    }
    Node* address = GetNodeAddress(node);
    ZoneMap<Node*, StoreNodeSet>* store_nodes;
    auto first_level_iter = group_of_stores_.find(dominator);
    if (first_level_iter == group_of_stores_.end()) {
      store_nodes = zone_->New<ZoneMap<Node*, StoreNodeSet>>(zone_);
      group_of_stores_[dominator] = store_nodes;
    } else {
      store_nodes = first_level_iter->second;
    }
    auto second_level_iter = store_nodes->find(address);
    if (second_level_iter == store_nodes->end()) {
      second_level_iter =
          store_nodes->insert({address, StoreNodeSet(zone())}).first;
    }
    second_level_iter->second.insert(node);
  }
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::SLPTree::GetEarlySchedulePosition(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetMemoryOffsetValue(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetNodeAddress(), v8::internal::compiler::TFGraph::GetSimdStoreNodes(), graph_, group_of_stores_, v8::internal::kSimd128Size, v8::internal::Zone::New(), slp_tree_, zone(), and zone_.
Referenced by TryRevectorize().
DecideVectorize()
bool v8::internal::compiler::Revectorizer::DecideVectorize () [private]
Definition at line 901 of file revectorizer.cc.
                                   {
  TRACE("Enter %s\n", __func__);
  int save = 0, cost = 0;
  slp_tree_->ForEach([&](PackNode const* pnode) {
    const ZoneVector<Node*>& nodes = pnode->Nodes();
    IrOpcode::Value op = nodes[0]->opcode();
    // Skip LoopExit as auxiliary nodes are not issued in generated code.
    // Skip Extract128 as we will reuse its revectorized input and no additional
    // extract nodes will be generated.
    if (op == IrOpcode::kLoopExitValue || op == IrOpcode::kExtractF128) {
      return;
    }
    // Splat nodes will not cause a saving as it simply extends itself.
    if (!IsSplat(nodes)) {
      save++;
    }
    for (size_t i = 0; i < nodes.size(); i++) {
      if (i > 0 && nodes[i] == nodes[0]) continue;
      for (auto edge : nodes[i]->use_edges()) {
        if (!NodeProperties::IsValueEdge(edge)) continue;
        Node* useNode = edge.from();
        if (!GetPackNode(useNode) && !(useNode->uses().empty()) &&
            useNode->opcode() != IrOpcode::kLoopExitValue) {
          TRACE("External use edge: (%d:%s) -> (%d:%s)\n", useNode->id(),
                useNode->op()->mnemonic(), nodes[i]->id(),
                nodes[i]->op()->mnemonic());
          cost++;
          // We only need one Extract node and all other uses can share.
          break;
        }
      }
    }
  });
  TRACE("Save: %d, cost: %d\n", save, cost);
  return save > cost;
}
References v8::internal::compiler::Node::Uses::empty(), v8::internal::compiler::SLPTree::ForEach(), GetPackNode(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSplat(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::PackNode::Nodes(), v8::internal::compiler::Node::opcode(), v8::internal::ZoneVector< T >::size(), slp_tree_, v8::internal::TRACE(), and v8::internal::compiler::Node::uses().
Referenced by ReduceStoreChain().
DetectCPUFeatures()
void v8::internal::compiler::Revectorizer::DetectCPUFeatures ()
Definition at line 1292 of file revectorizer.cc.
                                     {
  base::CPU cpu;
  if (v8_flags.enable_avx && v8_flags.enable_avx2 && cpu.has_avx2()) {
    support_simd256_ = true;
  }
}
References v8::base::CPU::has_avx2(), support_simd256_, and v8::internal::v8_flags.
Referenced by Revectorizer().
GetPackNode()
PackNode* v8::internal::compiler::Revectorizer::GetPackNode (Node * node) const [inline], [private]
Definition at line 182 of file revectorizer.h.
                                          {
    return slp_tree_->GetPackNode(node);
  }
Referenced by DecideVectorize(), SetEffectInput(), UpdateSources(), and VectorizeTree().
graph()
TFGraph* v8::internal::compiler::Revectorizer::graph () const [inline], [private]
Definition at line 179 of file revectorizer.h.
{ return graph_; }
Referenced by Revectorizer(), and VectorizeTree().
mcgraph()
MachineGraph* v8::internal::compiler::Revectorizer::mcgraph () const [inline], [private]
Definition at line 180 of file revectorizer.h.
{ return mcgraph_; }
Referenced by VectorizeTree().
PrintStores()
void v8::internal::compiler::Revectorizer::PrintStores (ZoneMap< Node *, StoreNodeSet > * store_chains) [private]
Definition at line 1440 of file revectorizer.cc.
                                                                         {
  if (!v8_flags.trace_wasm_revectorize) {
    return;
  }
  TRACE("Enter %s\n", __func__);
  for (auto it = store_chains->cbegin(); it != store_chains->cend(); ++it) {
    if (it->second.size() > 0) {
      TRACE("address = #%d:%s \n", it->first->id(),
            it->first->op()->mnemonic());
      for (auto node : it->second) {
        TRACE("#%d:%s, ", node->id(), node->op()->mnemonic());
      }
      TRACE("\n");
    }
  }
}
References v8::internal::TRACE(), and v8::internal::v8_flags.
Referenced by TryRevectorize().
ReduceStoreChain()
bool v8::internal::compiler::Revectorizer::ReduceStoreChain (const ZoneVector< Node * > & Stores) [private]
Definition at line 1406 of file revectorizer.cc.
                                                                   {
  TRACE("Enter %s, root@ (#%d,#%d)\n", __func__, Stores[0]->id(),
        Stores[1]->id());
  if (!IsContinuousAccess(Stores)) {
    return false;
  }
  PackNode* root = slp_tree_->BuildTree(Stores);
  if (!root) {
    TRACE("Build tree failed!\n");
    return false;
  }
  slp_tree_->Print("After build tree");
  if (DecideVectorize()) {
    VectorizeTree(root);
    UpdateSources();
    slp_tree_->Print("After vectorize tree");
    if (node_observer_for_test_) {
      slp_tree_->ForEach([&](const PackNode* pnode) {
        Node* node = pnode->RevectorizedNode();
        if (node) {
          node_observer_for_test_->OnNodeCreated(node);
        }
      });
    }
  }
  TRACE("\n");
  return true;
}
References v8::internal::compiler::SLPTree::BuildTree(), DecideVectorize(), v8::internal::compiler::SLPTree::ForEach(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsContinuousAccess(), node_observer_for_test_, v8::internal::compiler::NodeObserver::OnNodeCreated(), v8::internal::compiler::SLPTree::Print(), v8::internal::compiler::PackNode::RevectorizedNode(), slp_tree_, v8::internal::TRACE(), UpdateSources(), and VectorizeTree().
Referenced by ReduceStoreChains().
ReduceStoreChains()
bool v8::internal::compiler::Revectorizer::ReduceStoreChains (ZoneMap< Node *, StoreNodeSet > * store_chains) [private]
Definition at line 1382 of file revectorizer.cc.
                                                {
  TRACE("Enter %s\n", __func__);
  bool changed = false;
  for (auto chain_iter = store_chains->cbegin();
       chain_iter != store_chains->cend(); ++chain_iter) {
    if (chain_iter->second.size() >= 2 && chain_iter->second.size() % 2 == 0) {
      ZoneVector<Node*> store_chain(chain_iter->second.begin(),
                                    chain_iter->second.end(), zone_);
      for (auto it = store_chain.begin(); it < store_chain.end(); it = it + 2) {
        ZoneVector<Node*> stores_unit(it, it + 2, zone_);
        if ((NodeProperties::GetEffectInput(stores_unit[0]) == stores_unit[1] ||
             NodeProperties::GetEffectInput(stores_unit[1]) ==
                 stores_unit[0]) &&
            ReduceStoreChain(stores_unit)) {
          changed = true;
        }
      }
    }
  }
  return changed;
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::NodeProperties::GetEffectInput(), ReduceStoreChain(), v8::internal::TRACE(), and zone_.
Referenced by TryRevectorize().
SetEffectInput()
void v8::internal::compiler::Revectorizer::SetEffectInput (PackNode * pnode, int index, Node *& nput) [private]
Definition at line 944 of file revectorizer.cc.
                                                                          {
  const ZoneVector<Node*>& nodes = pnode->Nodes();
  // We assumed there's no effect edge to the 3rd node inbetween.
  DCHECK(nodes[0] == nodes[1] ||
         NodeProperties::GetEffectInput(nodes[0]) == nodes[1] ||
         NodeProperties::GetEffectInput(nodes[1]) == nodes[0]);
  // Scanning till find the other effect outside pnode.
  for (size_t i = 0; i < nodes.size(); i++) {
    Node* node128 = nodes[i];
    PackNode* effect = GetPackNode(node128->InputAt(index));
    if (effect == pnode) continue;
    if (effect)
      pnode->SetOperand(index, effect);
    else
      input = node128->InputAt(index);
    break;
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetEffectInput(), GetPackNode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::PackNode::Nodes(), v8::internal::compiler::PackNode::SetOperand(), and v8::internal::ZoneVector< T >::size().
Referenced by SetMemoryOpInputs().
SetMemoryOpInputs()
void v8::internal::compiler::Revectorizer::SetMemoryOpInputs (base::SmallVector< Node *, 2 > & inputs, PackNode * pnode, int index) [private]
Definition at line 965 of file revectorizer.cc.
                                                                        {
  Node* node = pnode->Nodes()[0];
  // Keep the addressing inputs
  inputs[0] = node->InputAt(0);
  inputs[1] = node->InputAt(1);
  // Set the effect input and the value input will be set later
  SetEffectInput(pnode, effect_index, inputs[effect_index]);
  // Set the control input
  inputs[effect_index + 1] = node->InputAt(effect_index + 1);
}
References v8::internal::compiler::Node::InputAt(), v8::internal::compiler::PackNode::Nodes(), and SetEffectInput().
Referenced by VectorizeTree().
TryRevectorize()
bool v8::internal::compiler::Revectorizer::TryRevectorize (const char * name)
Definition at line 1299 of file revectorizer.cc.
                                                      {
  source_positions_->AddDecorator();
  bool success = false;
  if (support_simd256_ && graph_->GetSimdStoreNodes().size()) {
    TRACE("TryRevectorize %s\n", function);
    CollectSeeds();
    for (auto entry : group_of_stores_) {
      ZoneMap<Node*, StoreNodeSet>* store_chains = entry.second;
      if (store_chains != nullptr) {
        PrintStores(store_chains);
        if (ReduceStoreChains(store_chains)) {
          TRACE("Successful revectorize %s\n", function);
          success = true;
        }
      }
    }
    TRACE("Finish revectorize %s\n", function);
  }
  source_positions_->RemoveDecorator();
  return success;
}
References v8::internal::compiler::SourcePositionTable::AddDecorator(), CollectSeeds(), v8::internal::compiler::TFGraph::GetSimdStoreNodes(), graph_, group_of_stores_, PrintStores(), ReduceStoreChains(), v8::internal::compiler::SourcePositionTable::RemoveDecorator(), v8::internal::ZoneVector< T >::size(), source_positions_, support_simd256_, and v8::internal::TRACE().
UpdateSources()
void v8::internal::compiler::Revectorizer::UpdateSources () [private]
Definition at line 1322 of file revectorizer.cc.
                                 {
  for (auto* src : sources_) {
    std::vector<Node*> effect_uses;
    bool hasExternalValueUse = false;
    for (auto edge : src->use_edges()) {
      Node* use = edge.from();
      if (!GetPackNode(use)) {
        if (NodeProperties::IsValueEdge(edge)) {
          TRACE("Source node has external value dependence %d:%s\n",
                edge.from()->id(), edge.from()->op()->mnemonic());
          hasExternalValueUse = true;
          break;
        } else if (NodeProperties::IsEffectEdge(edge)) {
          effect_uses.push_back(use);
        }
      }
    }
    if (!hasExternalValueUse) {
      // Remove unused source and linearize effect chain.
      Node* effect = NodeProperties::GetEffectInput(src);
      for (auto use : effect_uses) {
        TRACE("Replace Effect Edge for source node from %d:%s, to %d:%s\n",
              use->id(), use->op()->mnemonic(), effect->id(),
              effect->op()->mnemonic());
        NodeProperties::ReplaceEffectInput(use, effect, 0);
      }
    }
  }
  sources_.clear();
}
References v8::internal::compiler::NodeProperties::GetEffectInput(), GetPackNode(), v8::internal::compiler::Node::id(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), sources_, v8::internal::TRACE(), and use().
Referenced by ReduceStoreChain().
VectorizeTree()
Node * v8::internal::compiler::Revectorizer::VectorizeTree (PackNode * pnode) [private]
Definition at line 977 of file revectorizer.cc.
                                                 {
  TRACE("Enter %s with PackNode\n", __func__);
  Node* node0 = pnode->Nodes()[0];
  Node* node1 = pnode->Nodes()[1];
  if (pnode->RevectorizedNode()) {
    TRACE("Diamond merged for #%d:%s\n", node0->id(), node0->op()->mnemonic());
    return pnode->RevectorizedNode();
  }
  int input_count = node0->InputCount();
  TRACE("Vectorize #%d:%s, input count: %d\n", node0->id(),
        node0->op()->mnemonic(), input_count);
  IrOpcode::Value op = node0->opcode();
  const Operator* new_op = nullptr;
  Node* source = nullptr;
  Node* dead = mcgraph()->Dead();
  base::SmallVector<Node*, 2> inputs(input_count);
  for (int i = 0; i < input_count; i++) inputs[i] = dead;
  switch (op) {
    case IrOpcode::kPhi: {
      DCHECK_EQ(PhiRepresentationOf(node0->op()),
                MachineRepresentation::kSimd128);
      new_op = mcgraph_->common()->Phi(MachineRepresentation::kSimd256,
                                       input_count - 1);
      inputs[input_count - 1] = NodeProperties::GetControlInput(node0);
      break;
    }
    case IrOpcode::kLoopExitValue: {
      DCHECK_EQ(LoopExitValueRepresentationOf(node0->op()),
                MachineRepresentation::kSimd128);
      new_op =
          mcgraph_->common()->LoopExitValue(MachineRepresentation::kSimd256);
      inputs[input_count - 1] = NodeProperties::GetControlInput(node0);
      break;
    }
#define SIMPLE_CASE(from, to) \
  case IrOpcode::k##from: \
    new_op = mcgraph_->machine()->to(); \
    break;
      SIMPLE_SIMD_OP(SIMPLE_CASE)
#undef SIMPLE_CASE
#undef SIMPLE_SIMD_OP
#define SHIFT_CASE(from, to) \
  case IrOpcode::k##from: { \
    DCHECK(ShiftBySameScalar(pnode->Nodes())); \
    new_op = mcgraph_->machine()->to(); \
    inputs[1] = node0->InputAt(1); \
    break; \
  }
      SIMD_SHIFT_OP(SHIFT_CASE)
#undef SHIFT_CASE
#undef SIMD_SHIFT_OP
#define SIGN_EXTENSION_CONVERT_CASE(from, not_used, to) \
  case IrOpcode::k##from: { \
    DCHECK_EQ(node0->InputAt(0), pnode->Nodes()[1]->InputAt(0)); \
    new_op = mcgraph_->machine()->to(); \
    inputs[0] = node0->InputAt(0); \
    break; \
  }
      SIMD_SIGN_EXTENSION_CONVERT_OP(SIGN_EXTENSION_CONVERT_CASE)
#undef SIGN_EXTENSION_CONVERT_CASE
#undef SIMD_SIGN_EXTENSION_CONVERT_OP
#define SPLAT_CASE(from, to) \
  case IrOpcode::k##from: \
    new_op = mcgraph_->machine()->to(); \
    inputs[0] = node0->InputAt(0); \
    break;
      SIMD_SPLAT_OP(SPLAT_CASE)
#undef SPLAT_CASE
#undef SIMD_SPLAT_OP
    case IrOpcode::kI8x16Shuffle: {
      // clang-format off
      if (IsSplat(pnode->Nodes())) {
        const uint8_t* shuffle = S128ImmediateParameterOf(node0->op()).data();
        int index, offset;
        // Match Splat and Revectorize to LoadSplat as AVX-256 does not support
        // shuffling across 128-bit lane.
        if (wasm::SimdShuffle::TryMatchSplat<4>(shuffle, &index)) {
          new_op = mcgraph_->machine()->LoadTransform(
              MemoryAccessKind::kProtectedByTrapHandler,
              LoadTransformation::kS256Load32Splat);
          offset = index * 4;
        } else if (wasm::SimdShuffle::TryMatchSplat<2>(shuffle, &index)) {
          new_op = mcgraph_->machine()->LoadTransform(
              MemoryAccessKind::kProtectedByTrapHandler,
              LoadTransformation::kS256Load64Splat);
          offset = index * 8;
        } else {
          UNREACHABLE();
        }
        source = node0->InputAt(offset >> 4);
        DCHECK_EQ(source->opcode(), IrOpcode::kProtectedLoad);
        inputs.resize(4);
        // Update LoadSplat offset.
        if (index) {
          SourcePositionTable::Scope scope(source_positions_, source);
          inputs[0] = graph()->NewNode(mcgraph_->machine()->Int64Add(),
                                       source->InputAt(0),
                                       mcgraph_->Int64Constant(offset));
        } else {
          inputs[0] = source->InputAt(0);
        }
        // Keep source index, effect and control inputs.
        inputs[1] = source->InputAt(1);
        inputs[2] = source->InputAt(2);
        inputs[3] = source->InputAt(3);
        input_count = 4;
      } else {
        const uint8_t* shuffle0 = S128ImmediateParameterOf(node0->op()).data();
        const uint8_t* shuffle1 = S128ImmediateParameterOf(node1->op()).data();
        uint8_t new_shuffle[32];
        if (node0->InputAt(0) == node0->InputAt(1) &&
            node1->InputAt(0) == node1->InputAt(1)) {
          // Shuffle is Swizzle
          for (int i = 0; i < 16; ++i) {
            new_shuffle[i] = shuffle0[i] % 16;
            new_shuffle[i + 16] = 16 + shuffle1[i] % 16;
          }
        } else {
          for (int i = 0; i < 16; ++i) {
            if (shuffle0[i] < 16) {
              new_shuffle[i] = shuffle0[i];
            } else {
              new_shuffle[i] = 16 + shuffle0[i];
            }
            if (shuffle1[i] < 16) {
              new_shuffle[i + 16] = 16 + shuffle1[i];
            } else {
              new_shuffle[i + 16] = 32 + shuffle1[i];
            }
          }
        }
        new_op = mcgraph_->machine()->I8x32Shuffle(new_shuffle);
      }
      break;
      // clang-format on
    }
    case IrOpcode::kS128Zero: {
      new_op = mcgraph_->machine()->S256Zero();
      break;
    }
    case IrOpcode::kS128Const: {
      uint8_t value[32];
      const uint8_t* value0 = S128ImmediateParameterOf(node0->op()).data();
      const uint8_t* value1 = S128ImmediateParameterOf(node1->op()).data();
      for (int i = 0; i < kSimd128Size; ++i) {
        value[i] = value0[i];
        value[i + 16] = value1[i];
      }
      new_op = mcgraph_->machine()->S256Const(value);
      break;
    }
    case IrOpcode::kProtectedLoad: {
      DCHECK_EQ(LoadRepresentationOf(node0->op()).representation(),
                MachineRepresentation::kSimd128);
      new_op = mcgraph_->machine()->ProtectedLoad(MachineType::Simd256());
      SetMemoryOpInputs(inputs, pnode, 2);
      break;
    }
    case IrOpcode::kLoad: {
      DCHECK_EQ(LoadRepresentationOf(node0->op()).representation(),
                MachineRepresentation::kSimd128);
      new_op = mcgraph_->machine()->Load(MachineType::Simd256());
      SetMemoryOpInputs(inputs, pnode, 2);
      break;
    }
    case IrOpcode::kProtectedStore: {
      DCHECK_EQ(StoreRepresentationOf(node0->op()).representation(),
                MachineRepresentation::kSimd128);
      new_op =
          mcgraph_->machine()->ProtectedStore(MachineRepresentation::kSimd256);
      SetMemoryOpInputs(inputs, pnode, 3);
      break;
    }
    case IrOpcode::kStore: {
      DCHECK_EQ(StoreRepresentationOf(node0->op()).representation(),
                MachineRepresentation::kSimd128);
      WriteBarrierKind write_barrier_kind =
          StoreRepresentationOf(node0->op()).write_barrier_kind();
      new_op = mcgraph_->machine()->Store(StoreRepresentation(
          MachineRepresentation::kSimd256, write_barrier_kind));
      SetMemoryOpInputs(inputs, pnode, 3);
      break;
    }
    case IrOpcode::kLoadTransform: {
      LoadTransformParameters params = LoadTransformParametersOf(node0->op());
      LoadTransformation new_transformation;
      // clang-format off
      switch (params.transformation) {
        case LoadTransformation::kS128Load8Splat:
          new_transformation = LoadTransformation::kS256Load8Splat;
          break;
        case LoadTransformation::kS128Load16Splat:
          new_transformation = LoadTransformation::kS256Load16Splat;
          break;
        case LoadTransformation::kS128Load32Splat:
          new_transformation = LoadTransformation::kS256Load32Splat;
          break;
        case LoadTransformation::kS128Load64Splat:
          new_transformation = LoadTransformation::kS256Load64Splat;
          break;
        case LoadTransformation::kS128Load8x8S:
          new_transformation = LoadTransformation::kS256Load8x16S;
          break;
        case LoadTransformation::kS128Load8x8U:
          new_transformation = LoadTransformation::kS256Load8x16U;
          break;
        case LoadTransformation::kS128Load16x4S:
          new_transformation = LoadTransformation::kS256Load16x8S;
          break;
        case LoadTransformation::kS128Load16x4U:
          new_transformation = LoadTransformation::kS256Load16x8U;
          break;
        case LoadTransformation::kS128Load32x2S:
          new_transformation = LoadTransformation::kS256Load32x4S;
          break;
        case LoadTransformation::kS128Load32x2U:
          new_transformation = LoadTransformation::kS256Load32x4U;
          break;
        default:
          UNREACHABLE();
      }
      // clang-format on
      new_op =
          mcgraph_->machine()->LoadTransform(params.kind, new_transformation);
      SetMemoryOpInputs(inputs, pnode, 2);
      break;
    }
    case IrOpcode::kExtractF128: {
      pnode->SetRevectorizedNode(node0->InputAt(0));
      // The extract uses other than its parent don't need to change.
      break;
    }
    default:
      UNREACHABLE();
  }
  DCHECK(pnode->RevectorizedNode() || new_op);
  if (new_op != nullptr) {
    SourcePositionTable::Scope scope(source_positions_, node0);
    Node* new_node =
        graph()->NewNode(new_op, input_count, inputs.begin(), true);
    pnode->SetRevectorizedNode(new_node);
    for (int i = 0; i < input_count; i++) {
      if (inputs[i] == dead) {
        new_node->ReplaceInput(i, VectorizeTree(pnode->GetOperand(i)));
      }
    }
    // Extract Uses
    const ZoneVector<Node*>& nodes = pnode->Nodes();
    for (size_t i = 0; i < nodes.size(); i++) {
      if (i > 0 && nodes[i] == nodes[i - 1]) continue;
      Node* input_128 = nullptr;
      for (auto edge : nodes[i]->use_edges()) {
        Node* useNode = edge.from();
        if (!GetPackNode(useNode)) {
          if (NodeProperties::IsValueEdge(edge)) {
            // Extract use
            TRACE("Replace Value Edge from %d:%s, to %d:%s\n", useNode->id(),
                  useNode->op()->mnemonic(), edge.to()->id(),
                  edge.to()->op()->mnemonic());
            if (!input_128) {
              TRACE("Create ExtractF128(%lu) node from #%d\n", i,
                    new_node->id());
              input_128 = graph()->NewNode(
                  mcgraph()->machine()->ExtractF128(static_cast<int32_t>(i)),
                  new_node);
            }
            edge.UpdateTo(input_128);
          } else if (NodeProperties::IsEffectEdge(edge)) {
            TRACE("Replace Effect Edge from %d:%s, to %d:%s\n", useNode->id(),
                  useNode->op()->mnemonic(), edge.to()->id(),
                  edge.to()->op()->mnemonic());
            edge.UpdateTo(new_node);
          }
        }
      }
      if (nodes[i]->uses().empty()) nodes[i]->Kill();
    }
    // Update effect use of NewNode from the dependent source.
    if (op == IrOpcode::kI8x16Shuffle && IsSplat(nodes)) {
      DCHECK(source);
      NodeProperties::ReplaceEffectInput(source, new_node, 0);
      TRACE("Replace Effect Edge from %d:%s, to %d:%s\n", source->id(),
            source->op()->mnemonic(), new_node->id(),
            new_node->op()->mnemonic());
      // Remove unused value use, so that we can safely elimite the node later.
      NodeProperties::ReplaceValueInput(node0, dead, 0);
      NodeProperties::ReplaceValueInput(node0, dead, 1);
      TRACE("Remove Value Input of %d:%s\n", node0->id(),
            node0->op()->mnemonic());
      // We will try cleanup source nodes later
      sources_.insert(source);
    }
  }
  return pnode->RevectorizedNode();
}
References v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::data(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::MachineGraph::Dead(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::PackNode::GetOperand(), GetPackNode(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::MachineOperatorBuilder::Int64Add(), v8::internal::compiler::MachineGraph::Int64Constant(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSplat(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::LoadTransformParameters::kind, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::kS128Load16Splat, v8::internal::compiler::kS128Load16x4S, v8::internal::compiler::kS128Load16x4U, v8::internal::compiler::kS128Load32Splat, v8::internal::compiler::kS128Load32x2S, v8::internal::compiler::kS128Load32x2U, v8::internal::compiler::kS128Load64Splat, v8::internal::compiler::kS128Load8Splat, v8::internal::compiler::kS128Load8x8S, v8::internal::compiler::kS128Load8x8U, v8::internal::compiler::kS256Load16Splat, v8::internal::compiler::kS256Load16x8S, v8::internal::compiler::kS256Load16x8U, v8::internal::compiler::kS256Load32Splat, v8::internal::compiler::kS256Load32x4S, v8::internal::compiler::kS256Load32x4U, v8::internal::compiler::kS256Load64Splat, v8::internal::compiler::kS256Load8Splat, v8::internal::compiler::kS256Load8x16S, v8::internal::compiler::kS256Load8x16U, v8::internal::kSimd128, v8::internal::kSimd128Size, v8::internal::kSimd256, v8::internal::compiler::MachineOperatorBuilder::Load(), v8::internal::compiler::LoadRepresentationOf(), v8::internal::compiler::LoadTransformParametersOf(), v8::internal::compiler::CommonOperatorBuilder::LoopExitValue(), v8::internal::compiler::LoopExitValueRepresentationOf(), v8::internal::compiler::MachineGraph::machine(), mcgraph(), mcgraph_, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::PackNode::Nodes(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::compiler::PhiRepresentationOf(), v8::internal::compiler::MachineOperatorBuilder::ProtectedLoad(), v8::internal::compiler::MachineOperatorBuilder::ProtectedStore(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::MachineType::representation(), v8::internal::compiler::StoreRepresentation::representation(), v8::base::SmallVector< T, kSize, Allocator >::resize(), v8::internal::compiler::PackNode::RevectorizedNode(), v8::internal::compiler::S128ImmediateParameterOf(), SetMemoryOpInputs(), v8::internal::compiler::PackNode::SetRevectorizedNode(), SHIFT_CASE, SIGN_EXTENSION_CONVERT_CASE, v8::internal::MachineType::Simd256(), SIMD_SHIFT_OP, SIMD_SIGN_EXTENSION_CONVERT_OP, SIMD_SPLAT_OP, SIMPLE_CASE, SIMPLE_SIMD_OP, v8::internal::ZoneVector< T >::size(), source_positions_, sources_, SPLAT_CASE, v8::internal::compiler::MachineOperatorBuilder::Store(), v8::internal::compiler::StoreRepresentationOf(), v8::internal::TRACE(), v8::internal::compiler::LoadTransformParameters::transformation, v8::internal::UNREACHABLE(), v8::internal::value, and v8::internal::compiler::StoreRepresentation::write_barrier_kind().
Referenced by ReduceStoreChain().
zone()
Zone* v8::internal::compiler::Revectorizer::zone () const [inline], [private]
Definition at line 178 of file revectorizer.h.
{ return zone_; }
Referenced by CollectSeeds(), and Revectorizer().
Member Data Documentation
graph_
TFGraph* const v8::internal::compiler::Revectorizer::graph_ [private]
Definition at line 195 of file revectorizer.h.
Referenced by CollectSeeds(), and TryRevectorize().
group_of_stores_
ZoneMap<Node*, ZoneMap<Node*, StoreNodeSet>*> v8::internal::compiler::Revectorizer::group_of_stores_ [private]
Definition at line 197 of file revectorizer.h.
Referenced by CollectSeeds(), and TryRevectorize().
mcgraph_
MachineGraph* const v8::internal::compiler::Revectorizer::mcgraph_ [private]
Definition at line 196 of file revectorizer.h.
Referenced by VectorizeTree().
node_observer_for_test_
compiler::NodeObserver* v8::internal::compiler::Revectorizer::node_observer_for_test_ [private]
Definition at line 204 of file revectorizer.h.
Referenced by ReduceStoreChain(), and Revectorizer().
slp_tree_
SLPTree* v8::internal::compiler::Revectorizer::slp_tree_ [private]
Definition at line 199 of file revectorizer.h.
Referenced by CollectSeeds(), DecideVectorize(), ReduceStoreChain(), and Revectorizer().
source_positions_
SourcePositionTable* v8::internal::compiler::Revectorizer::source_positions_ [private]
Definition at line 200 of file revectorizer.h.
Referenced by TryRevectorize(), and VectorizeTree().
sources_
std::unordered_set<Node*> v8::internal::compiler::Revectorizer::sources_ [private]
Definition at line 198 of file revectorizer.h.
Referenced by UpdateSources(), and VectorizeTree().
support_simd256_
bool v8::internal::compiler::Revectorizer::support_simd256_ [private]
Definition at line 202 of file revectorizer.h.
Referenced by DetectCPUFeatures(), and TryRevectorize().
zone_
Zone* const v8::internal::compiler::Revectorizer::zone_ [private]
Definition at line 194 of file revectorizer.h.
Referenced by CollectSeeds(), ReduceStoreChains(), and Revectorizer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/revectorizer.h
/mnt/V8SourceCode/src/compiler/revectorizer.cc