v8::internal::maglev::RestLength Class Reference
#include <maglev-ir.h>
Public Member Functions
RestLength (uint64_t bitfield, int formal_parameter_count)
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
int formal_parameter_count () const
auto options () const
Private Types
using Base = FixedInputValueNodeT< 0, RestLength >
Private Attributes
int formal_parameter_count_
Additional Inherited Members
Detailed Description
Definition at line 6505 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::RestLength::Base = FixedInputValueNodeT<0, RestLength> [private]
Definition at line 6506 of file maglev-ir.h.
Constructor & Destructor Documentation
RestLength()
v8::internal::maglev::RestLength::RestLength (uint64_t bitfield, int formal_parameter_count) [inline], [explicit]
Definition at line 6509 of file maglev-ir.h.
      : Base(bitfield), formal_parameter_count_(formal_parameter_count) {}
Member Function Documentation
formal_parameter_count()
int v8::internal::maglev::RestLength::formal_parameter_count () const [inline]
Definition at line 6516 of file maglev-ir.h.
{ return formal_parameter_count_; }
Referenced by GenerateCode(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::RestLength::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 151 of file maglev-ir-arm.cc.
                                                            {
  Register length = ToRegister(result());
  Label done;
  __ ldr(length, MemOperand(fp, StandardFrameConstants::kArgCOffset));
  __ sub(length, length, Operand(formal_parameter_count() + 1), SetCC);
  __ b(kGreaterThanEqual, &done);
  __ Move(length, 0);
  __ bind(&done);
  __ UncheckedSmiTagInt32(length);
}
References __, formal_parameter_count(), v8::internal::StandardFrameConstants::kArgCOffset, v8::internal::kGreaterThanEqual, v8::internal::length, v8::base::internal::result, v8::internal::SetCC, and v8::internal::maglev::ToRegister().
options()
auto v8::internal::maglev::RestLength::options () const [inline]
Definition at line 6518 of file maglev-ir.h.
{ return std::tuple{formal_parameter_count_}; }
PrintParams()
void v8::internal::maglev::RestLength::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 6514 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::RestLength::SetValueLocationConstraints ()
Definition at line 149 of file maglev-ir-arm.cc.
{ DefineAsRegister(this); }
References v8::internal::maglev::DefineAsRegister().
Member Data Documentation
formal_parameter_count_
int v8::internal::maglev::RestLength::formal_parameter_count_ [private]
Definition at line 6521 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc