v8::internal::JSRegExp::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Static Public Attributes
static const int kStartOffset = JSReceiver::kPropertiesOrHashOffset
Additional Inherited Members
Detailed Description
Definition at line 384 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::JSRegExp::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 389 of file objects-body-descriptors-inl.h.
                                                                    {
    IteratePointers(obj, kPropertiesOrHashOffset, JSObject::kHeaderSize, v);
    IterateTrustedPointer(obj, kDataOffset, v, IndirectPointerMode::kStrong,
                          kRegExpDataIndirectPointerTag);
    IteratePointer(obj, kSourceOffset, v);
    IterateJSObjectBodyImpl(map, obj, kHeaderSize, object_size, v);
  }
References v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl(), v8::internal::BodyDescriptorBase::IteratePointer(), v8::internal::BodyDescriptorBase::IteratePointers(), v8::internal::BodyDescriptorBase::IterateTrustedPointer(), and v8::internal::kStrong.
SizeOf()
static int v8::internal::JSRegExp::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 398 of file objects-body-descriptors-inl.h.
                                                                       {
    return map->instance_size();
  }
Member Data Documentation
kStartOffset
const int v8::internal::JSRegExp::BodyDescriptor::kStartOffset = JSReceiver::kPropertiesOrHashOffset [static]
Definition at line 386 of file objects-body-descriptors-inl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h