v8::internal::compiler::CheckMapsParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
CheckMapsParameters (CheckMapsFlags flags, ZoneRefSet< Map > const &maps, const FeedbackSource &feedback)
CheckMapsFlags flags () const
ZoneRefSet< Map > const & maps () const
FeedbackSource const & feedback () const
Private Attributes
CheckMapsFlags const flags_
ZoneRefSet< Map > const maps_
FeedbackSource const feedback_
Detailed Description
Definition at line 456 of file simplified-operator.h.
Constructor & Destructor Documentation
CheckMapsParameters()
v8::internal::compiler::CheckMapsParameters::CheckMapsParameters (CheckMapsFlags flags, ZoneRefSet< Map > const & maps, const FeedbackSource & feedback) [inline]
Definition at line 458 of file simplified-operator.h.
      : flags_(flags), maps_(maps), feedback_(feedback) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::CheckMapsParameters::feedback () const [inline]
Definition at line 464 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitNode().
flags()
CheckMapsFlags v8::internal::compiler::CheckMapsParameters::flags () const [inline]
Definition at line 462 of file simplified-operator.h.
{ return flags_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
maps()
ZoneRefSet<Map> const& v8::internal::compiler::CheckMapsParameters::maps () const [inline]
Definition at line 463 of file simplified-operator.h.
{ return maps_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceCheckMaps(), and v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
Member Data Documentation
feedback_
FeedbackSource const v8::internal::compiler::CheckMapsParameters::feedback_ [private]
Definition at line 469 of file simplified-operator.h.
flags_
CheckMapsFlags const v8::internal::compiler::CheckMapsParameters::flags_ [private]
Definition at line 467 of file simplified-operator.h.
maps_
ZoneRefSet<Map> const v8::internal::compiler::CheckMapsParameters::maps_ [private]
Definition at line 468 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h