v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody Class Reference
Public Member Functions
DecodeFunctionBody (SectionBuffer *section_buffer, size_t buffer_offset, size_t function_body_length, size_t num_remaining_functions, uint32_t module_offset)
base::Vector< uint8_t > buffer () override
std::unique_ptr< DecodingState > Next (AsyncStreamingDecoder *streaming) override
Private Attributes
SectionBuffer *const section_buffer_
const size_t buffer_offset_
const size_t function_body_length_
const size_t num_remaining_functions_
const uint32_t module_offset_
Detailed Description
Definition at line 534 of file streaming-decoder.cc.
Constructor & Destructor Documentation
DecodeFunctionBody()
v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::DecodeFunctionBody (SectionBuffer * section_buffer, size_t buffer_offset, size_t function_body_length, size_t num_remaining_functions, uint32_t module_offset) [inline], [explicit]
Definition at line 536 of file streaming-decoder.cc.
      : section_buffer_(section_buffer),
        buffer_offset_(buffer_offset),
        function_body_length_(function_body_length),
        num_remaining_functions_(num_remaining_functions),
        module_offset_(module_offset) {}
Member Function Documentation
buffer()
base::Vector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::buffer () [inline], [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 546 of file streaming-decoder.cc.
                                        {
    base::Vector<uint8_t> remaining_buffer =
        section_buffer_->bytes() + buffer_offset_;
    return remaining_buffer.SubVector(0, function_body_length_);
  }
References v8::base::Vector< T >::SubVector().
Next()
std::unique_ptr< AsyncStreamingDecoder::DecodingState > v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::Next (AsyncStreamingDecoder * streaming) [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 737 of file streaming-decoder.cc.
                                      {
  TRACE_STREAMING("DecodeFunctionBody\n");
  streaming->ProcessFunctionBody(buffer(), module_offset_);
  if (!streaming->ok()) return nullptr;
  size_t end_offset = buffer_offset_ + function_body_length_;
  if (num_remaining_functions_ > 0) {
    return std::make_unique<DecodeFunctionLength>(section_buffer_, end_offset,
                                                  num_remaining_functions_);
  }
  // We just read the last function body. Continue with the next section.
  if (end_offset != section_buffer_->length()) {
    return streaming->ToErrorState();
  }
  return std::make_unique<DecodeSectionID>(streaming->module_offset());
}
References v8::internal::wasm::AsyncStreamingDecoder::module_offset(), v8::internal::wasm::AsyncStreamingDecoder::module_offset_, v8::internal::wasm::AsyncStreamingDecoder::ok(), v8::internal::wasm::AsyncStreamingDecoder::ProcessFunctionBody(), v8::internal::wasm::AsyncStreamingDecoder::ToErrorState(), and TRACE_STREAMING.
Member Data Documentation
buffer_offset_
const size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::buffer_offset_ [private]
Definition at line 557 of file streaming-decoder.cc.
function_body_length_
const size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::function_body_length_ [private]
Definition at line 558 of file streaming-decoder.cc.
module_offset_
const uint32_t v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::module_offset_ [private]
Definition at line 560 of file streaming-decoder.cc.
num_remaining_functions_
const size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::num_remaining_functions_ [private]
Definition at line 559 of file streaming-decoder.cc.
section_buffer_
SectionBuffer* const v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::section_buffer_ [private]
Definition at line 556 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc