v8::internal::wasm::ProfileInformation Class Reference
#include <pgo.h>
Public Member Functions
ProfileInformation (std::vector< uint32_t > executed_functions, std::vector< uint32_t > tiered_up_functions)
ProfileInformation (const ProfileInformation &)=delete
ProfileInformation & operator= (const ProfileInformation &)=delete
base::Vector< const uint32_t > executed_functions () const
base::Vector< const uint32_t > tiered_up_functions () const
Private Attributes
const std::vector< uint32_t > executed_functions_
const std::vector< uint32_t > tiered_up_functions_
Detailed Description
Definition at line 20 of file pgo.h.
Constructor & Destructor Documentation
ProfileInformation() [1/2]
v8::internal::wasm::ProfileInformation::ProfileInformation (std::vector< uint32_t > executed_functions, std::vector< uint32_t > tiered_up_functions) [inline]
Definition at line 22 of file pgo.h.
      : executed_functions_(std::move(executed_functions)),
        tiered_up_functions_(std::move(tiered_up_functions)) {}
ProfileInformation() [2/2]
v8::internal::wasm::ProfileInformation::ProfileInformation (const ProfileInformation &) [delete]
Member Function Documentation
executed_functions()
base::Vector<const uint32_t> v8::internal::wasm::ProfileInformation::executed_functions () const [inline]
Definition at line 31 of file pgo.h.
                                                        {
    return base::VectorOf(executed_functions_);
  }
References executed_functions_, and v8::base::VectorOf().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoLate(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoToInitialProgress().
operator=()
ProfileInformation& v8::internal::wasm::ProfileInformation::operator= (const ProfileInformation &) [delete]
tiered_up_functions()
base::Vector<const uint32_t> v8::internal::wasm::ProfileInformation::tiered_up_functions () const [inline]
Definition at line 34 of file pgo.h.
                                                         {
    return base::VectorOf(tiered_up_functions_);
  }
References tiered_up_functions_, and v8::base::VectorOf().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoLate(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoToInitialProgress().
Member Data Documentation
executed_functions_
const std::vector<uint32_t> v8::internal::wasm::ProfileInformation::executed_functions_ [private]
Definition at line 39 of file pgo.h.
Referenced by executed_functions().
tiered_up_functions_
const std::vector<uint32_t> v8::internal::wasm::ProfileInformation::tiered_up_functions_ [private]
Definition at line 40 of file pgo.h.
Referenced by tiered_up_functions().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/pgo.h