v8::internal::Segment Class Reference
#include <zone-segment.h>
Public Member Functions
Zone * zone () const
void set_zone (Zone *const zone)
Segment * next () const
void set_next (Segment *const next)
size_t total_size () const
size_t capacity () const
Address start () const
Address end () const
void ZapContents ()
void ZapHeader ()
Private Member Functions
Segment (size_t size)
Address address (size_t n) const
Private Attributes
Zone * zone_ = nullptr
Segment * next_ = nullptr
const size_t size_
Friends
class AccountingAllocator
Detailed Description
Definition at line 22 of file zone-segment.h.
Constructor & Destructor Documentation
Segment()
v8::internal::Segment::Segment (size_t size) [inline], [explicit], [private]
Definition at line 50 of file zone-segment.h.
: size_(size) {}
Referenced by capacity().
Member Function Documentation
address()
Address v8::internal::Segment::address (size_t n) const [inline], [private]
Definition at line 58 of file zone-segment.h.
                                  {
    return reinterpret_cast<Address>(this) + n;
  }
Referenced by end(), and start().
capacity()
size_t v8::internal::Segment::capacity () const [inline]
Definition at line 36 of file zone-segment.h.
{ return size_ - sizeof(Segment); }
References Segment(), and size_.
Referenced by v8::internal::Zone::ReleaseSegment(), v8::internal::Zone::Reset(), and ZapContents().
end()
Address v8::internal::Segment::end () const [inline]
Definition at line 39 of file zone-segment.h.
{ return address(size_); }
References address(), and size_.
Referenced by v8::internal::Zone::Expand(), v8::internal::Zone::Reset(), and v8::internal::ZoneSnapshot::Restore().
next()
Segment* v8::internal::Segment::next () const [inline]
Definition at line 27 of file zone-segment.h.
{ return next_; }
References next_.
Referenced by v8::internal::Zone::DeleteAll(), v8::internal::Zone::Reset(), v8::internal::ZoneSnapshot::Restore(), and set_next().
set_next()
void v8::internal::Segment::set_next (Segment *const next) [inline]
Definition at line 28 of file zone-segment.h.
{ next_ = next; }
References next(), and next_.
Referenced by v8::internal::Zone::Expand(), and v8::internal::Zone::Reset().
set_zone()
void v8::internal::Segment::set_zone (Zone *const zone) [inline]
Definition at line 25 of file zone-segment.h.
{ zone_ = zone; }
References zone(), and zone_.
Referenced by v8::internal::Zone::Expand().
start()
Address v8::internal::Segment::start () const [inline]
Definition at line 38 of file zone-segment.h.
{ return address(sizeof(Segment)); }
References address().
Referenced by v8::internal::Zone::Expand(), v8::internal::Zone::ReleaseSegment(), v8::internal::Zone::Reset(), v8::internal::ZoneSnapshot::Restore(), ZapContents(), and ZapHeader().
total_size()
size_t v8::internal::Segment::total_size () const [inline]
Definition at line 32 of file zone-segment.h.
{ return size_; }
References size_.
Referenced by v8::internal::Zone::DeleteAll(), v8::internal::Zone::Expand(), v8::internal::Zone::Reset(), v8::internal::AccountingAllocator::ReturnSegment(), and v8::internal::TracingAccountingAllocator::TraceAllocateSegmentImpl().
ZapContents()
void v8::internal::Segment::ZapContents ()
Definition at line 12 of file zone-segment.cc.
                          {
#ifdef DEBUG
  memset(reinterpret_cast<void*>(start()), kZapDeadByte, capacity());
#endif
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(start(), capacity());
}
References capacity(), MSAN_ALLOCATED_UNINITIALIZED_MEMORY, and start().
Referenced by v8::internal::Zone::Reset(), and v8::internal::AccountingAllocator::ReturnSegment().
ZapHeader()
void v8::internal::Segment::ZapHeader ()
Definition at line 19 of file zone-segment.cc.
                        {
#ifdef DEBUG
  memset(this, kZapDeadByte, sizeof(Segment));
#endif
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(start(), sizeof(Segment));
}
References MSAN_ALLOCATED_UNINITIALIZED_MEMORY, and start().
Referenced by v8::internal::AccountingAllocator::ReturnSegment().
zone()
Zone* v8::internal::Segment::zone () const [inline]
Definition at line 24 of file zone-segment.h.
{ return zone_; }
References zone_.
Referenced by set_zone().
Friends And Related Function Documentation
AccountingAllocator
friend class AccountingAllocator [friend]
Definition at line 48 of file zone-segment.h.
Member Data Documentation
next_
Segment* v8::internal::Segment::next_ = nullptr [private]
Definition at line 63 of file zone-segment.h.
Referenced by next(), and set_next().
size_
const size_t v8::internal::Segment::size_ [private]
Definition at line 64 of file zone-segment.h.
Referenced by capacity(), end(), and total_size().
zone_
Zone* v8::internal::Segment::zone_ = nullptr [private]
Definition at line 62 of file zone-segment.h.
Referenced by set_zone(), and zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/zone/zone-segment.h
/mnt/V8SourceCode/src/zone/zone-segment.cc