v8::internal::JSFunction Class Reference
#include <js-function.h>
Classes
class BodyDescriptor
Public Member Functions
DECL_RELEASE_ACQUIRE_ACCESSORS (prototype_or_initial_map, Tagged< UnionOf< JSPrototype, Map, Hole >>) void TraceOptimizationStatus(const char *reason
Tagged< Context > context ()
bool has_context () const
Tagged< JSGlobalProxy > global_proxy ()
Tagged< NativeContext > native_context ()
int length ()
void UpdateOptimizedCode (Isolate *isolate, Tagged< Code > code, WriteBarrierMode mode=WriteBarrierMode::UPDATE_WRITE_BARRIER)
void UpdateCode (Isolate *isolate, Tagged< Code > code, WriteBarrierMode mode=WriteBarrierMode::UPDATE_WRITE_BARRIER)
void UpdateCodeKeepTieringRequests (Isolate *isolate, Tagged< Code > code, WriteBarrierMode mode=WriteBarrierMode::UPDATE_WRITE_BARRIER)
Tagged< Object > raw_code (IsolateForSandbox isolate) const
Tagged< Object > raw_code (IsolateForSandbox isolate, AcquireLoadTag) const
Address instruction_start (IsolateForSandbox isolate) const
template<typename IsolateT >
Tagged< AbstractCode > abstract_code (IsolateT *isolate)
bool HasAvailableHigherTierCodeThan (IsolateForSandbox isolate, CodeKind kind) const
bool HasAvailableHigherTierCodeThanWithFilter (IsolateForSandbox isolate, CodeKind kind, CodeKinds filter_mask) const
V8_EXPORT_PRIVATE bool HasAttachedOptimizedCode (IsolateForSandbox isolate) const
bool HasAvailableOptimizedCode (IsolateForSandbox isolate) const
bool HasAttachedCodeKind (IsolateForSandbox isolate, CodeKind kind) const
bool HasAvailableCodeKind (IsolateForSandbox isolate, CodeKind kind) const
std::optional< CodeKind > GetActiveTier (IsolateForSandbox isolate) const
V8_EXPORT_PRIVATE bool ActiveTierIsIgnition (IsolateForSandbox isolate) const
bool ActiveTierIsBaseline (IsolateForSandbox isolate) const
bool ActiveTierIsMaglev (IsolateForSandbox isolate) const
bool ActiveTierIsTurbofan (IsolateForSandbox isolate) const
bool CanDiscardCompiled (IsolateForSandbox isolate) const
bool ChecksTieringState (IsolateForSandbox isolate)
TieringState tiering_state () const
void RequestOptimization (Isolate *isolate, CodeKind target_kind, ConcurrencyMode mode=ConcurrencyMode::kConcurrent)
bool IsLoggingRequested (Isolate *isolate) const
bool IsOptimizationRequested (Isolate *isolate) const
bool IsMaglevRequested (Isolate *isolate) const
bool IsTurbofanRequested (Isolate *isolate) const
std::optional< CodeKind > GetRequestedOptimizationIfAny (Isolate *isolate, ConcurrencyMode mode=ConcurrencyMode::kConcurrent) const
bool tiering_in_progress () const
bool IsTieringRequestedOrInProgress () const
void SetTieringInProgress (Isolate *isolate, bool in_progress, BytecodeOffset osr_offset=BytecodeOffset::None())
void ResetTieringRequests ()
bool osr_tiering_in_progress ()
void SetInterruptBudget (Isolate *isolate, BudgetModification kind, std::optional< CodeKind > override_active_tier={})
int ComputeInstanceSizeWithMinSlack (Isolate *isolate)
void CompleteInobjectSlackTrackingIfActive (Isolate *isolate)
bool has_closure_feedback_cell_array () const
Tagged< ClosureFeedbackCellArray > closure_feedback_cell_array () const
void ClearAllTypeFeedbackInfoForTesting (Isolate *isolate)
bool NeedsResetDueToFlushedBytecode (Isolate *isolate)
void ResetIfCodeFlushed (Isolate *isolate, std::optional< std::function< void(Tagged< HeapObject > object, ObjectSlot slot, Tagged< HeapObject > target)>> gc_notify_updated_slot=std::nullopt)
bool NeedsResetDueToFlushedBaselineCode (IsolateForSandbox isolate)
bool ShouldFlushBaselineCode (base::EnumSet< CodeFlushMode > code_flush_mode)
bool is_compiled (IsolateForSandbox isolate) const
std::unique_ptr< char[]> DebugNameCStr ()
void PrintName (FILE *out=stdout)
CodeKinds GetAvailableCodeKinds (IsolateForSandbox isolate) const
Static Public Member Functions
static Handle< String > GetName (Isolate *isolate, DirectHandle< JSFunction > function)
static V8_EXPORT_PRIVATE void EnsureFeedbackVector (Isolate *isolate, DirectHandle< JSFunction > function, IsCompiledScope *compiled_scope)
FeedbackVector eventually. Generally this shouldn't be used to get the.
static void CreateAndAttachFeedbackVector (Isolate *isolate, DirectHandle< JSFunction > function, IsCompiledScope *compiled_scope)
static void EnsureClosureFeedbackCellArray (Isolate *isolate, DirectHandle< JSFunction > function)
static void InitializeFeedbackCell (Isolate *isolate, DirectHandle< JSFunction > function, IsCompiledScope *compiled_scope, bool reset_budget_for_feedback_allocation)
static void SetInitialMap (Isolate *isolate, DirectHandle< JSFunction > function, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype)
static void SetInitialMap (Isolate *isolate, DirectHandle< JSFunction > function, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype, DirectHandle< JSFunction > constructor)
static V8_EXPORT_PRIVATE void EnsureHasInitialMap (Isolate *isolate, DirectHandle< JSFunction > function)
static V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT MaybeHandle< Map > GetDerivedMap (Isolate *isolate, DirectHandle< JSFunction > constructor, DirectHandle< JSReceiver > new_target)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Map > GetDerivedRabGsabTypedArrayMap (Isolate *isolate, DirectHandle< JSFunction > constructor, DirectHandle< JSReceiver > new_target)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Map > GetDerivedRabGsabDataViewMap (Isolate *isolate, DirectHandle< JSReceiver > new_target)
static void SetPrototype (Isolate *isolate, DirectHandle< JSFunction > function, DirectHandle< Object > value)
static int GetHeaderSize (bool function_has_prototype_slot)
static V8_WARN_UNUSED_RESULT int CalculateExpectedNofProperties (Isolate *isolate, DirectHandle< JSFunction > function)
static void CalculateInstanceSizeHelper (InstanceType instance_type, bool has_prototype_slot, int requested_embedder_fields, int requested_in_object_properties, int *instance_size, int *in_object_properties)
static DirectHandle< String > GetName (DirectHandle< JSFunction > function)
static V8_WARN_UNUSED_RESULT bool SetName (Isolate *isolate, DirectHandle< JSFunction > function, DirectHandle< Name > name, DirectHandle< String > prefix)
static DirectHandle< String > GetDebugName (Isolate *isolate, DirectHandle< JSFunction > function)
static DirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSFunction > function)
Static Public Attributes
static const int kMinDescriptorsForFastBindAndWrap = 2
static constexpr int kSizeWithoutPrototype = kPrototypeOrInitialMapOffset
static constexpr int kSizeWithPrototype = TorqueGeneratedClass::kHeaderSize
Private Member Functions
void set_tiering_state (IsolateForSandbox isolate, TieringState state)
void UpdateCodeImpl (Isolate *isolate, Tagged< Code > code, WriteBarrierMode mode, bool keep_tiering_request)
void UpdateDispatchEntry (Tagged< Code > new_code, WriteBarrierMode mode=WriteBarrierMode::UPDATE_WRITE_BARRIER)
void UpdateDispatchEntryKeepTieringRequest (Tagged< Code > new_code, WriteBarrierMode mode=WriteBarrierMode::UPDATE_WRITE_BARRIER)
CodeKinds GetAttachedCodeKinds (IsolateForSandbox isolate) const
Static Private Attributes
static const int kHeaderSize
Detailed Description
Definition at line 95 of file js-function.h.
Member Function Documentation
abstract_code()
template<typename IsolateT >
Tagged< AbstractCode > v8::internal::JSFunction::abstract_code (IsolateT * isolate) [inline]
Definition at line 70 of file js-function-inl.h.
                                                                {
  if (ActiveTierIsIgnition(isolate)) {
    return Cast<AbstractCode>(shared()->GetBytecodeArray(isolate));
  } else {
    return Cast<AbstractCode>(code(isolate, kAcquireLoad));
  }
}
References ActiveTierIsIgnition(), code, and v8::kAcquireLoad.
ActiveTierIsBaseline()
bool v8::internal::JSFunction::ActiveTierIsBaseline (IsolateForSandbox isolate) const
Definition at line 219 of file js-function.cc.
                                                                     {
  return GetActiveTier(isolate) == CodeKind::BASELINE;
}
References GetActiveTier().
Referenced by RequestOptimization().
ActiveTierIsIgnition()
bool v8::internal::JSFunction::ActiveTierIsIgnition (IsolateForSandbox isolate) const
Definition at line 215 of file js-function.cc.
                                                                     {
  return GetActiveTier(isolate) == CodeKind::INTERPRETED_FUNCTION;
}
References GetActiveTier().
Referenced by abstract_code(), and RequestOptimization().
ActiveTierIsMaglev()
bool v8::internal::JSFunction::ActiveTierIsMaglev (IsolateForSandbox isolate) const
Definition at line 223 of file js-function.cc.
                                                                   {
  return GetActiveTier(isolate) == CodeKind::MAGLEV;
}
References GetActiveTier().
Referenced by RequestOptimization().
ActiveTierIsTurbofan()
bool v8::internal::JSFunction::ActiveTierIsTurbofan (IsolateForSandbox isolate) const
Definition at line 227 of file js-function.cc.
                                                                     {
  return GetActiveTier(isolate) == CodeKind::TURBOFAN_JS;
}
References GetActiveTier().
Referenced by RequestOptimization().
CalculateExpectedNofProperties()
int v8::internal::JSFunction::CalculateExpectedNofProperties (Isolate * isolate, DirectHandle< JSFunction > function) [static]
Definition at line 1500 of file js-function.cc.
                                                         {
  int expected_nof_properties = 0;
  for (PrototypeIterator iter(isolate, function, kStartAtReceiver);
       !iter.IsAtEnd(); iter.Advance()) {
    DirectHandle<JSReceiver> current =
        PrototypeIterator::GetCurrent<JSReceiver>(iter);
    if (!IsJSFunction(*current)) break;
    DirectHandle<JSFunction> func = Cast<JSFunction>(current);
    // The super constructor should be compiled for the number of expected
    // properties to be available.
    DirectHandle<SharedFunctionInfo> shared(func->shared(), isolate);
    IsCompiledScope is_compiled_scope(shared->is_compiled_scope(isolate));
    if (is_compiled_scope.is_compiled() ||
        Compiler::Compile(isolate, func, Compiler::CLEAR_EXCEPTION,
                          &is_compiled_scope)) {
      DCHECK(shared->is_compiled());
      int count = shared->expected_nof_properties();
      // Check that the estimate is sensible.
      if (expected_nof_properties <= JSObject::kMaxInObjectProperties - count) {
        expected_nof_properties += count;
      } else {
        return JSObject::kMaxInObjectProperties;
      }
    } else {
      // In case there was a compilation error proceed iterating in case there
      // will be a builtin function in the prototype chain that requires
      // certain number of in-object properties.
      continue;
    }
  }
  // Inobject slack tracking will reclaim redundant inobject space
  // later, so we can afford to adjust the estimate generously,
  // meaning we over-allocate by at least 8 slots in the beginning.
  if (expected_nof_properties > 0) {
    expected_nof_properties += 8;
    if (expected_nof_properties > JSObject::kMaxInObjectProperties) {
      expected_nof_properties = JSObject::kMaxInObjectProperties;
    }
  }
  return expected_nof_properties;
}
References v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), v8::internal::DCHECK(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::JSObject::kMaxInObjectProperties, and v8::internal::kStartAtReceiver.
Referenced by EnsureHasInitialMap(), and v8::internal::anonymous_namespace{js-function.cc}::FastInitializeDerivedMap().
CalculateInstanceSizeHelper()
void v8::internal::JSFunction::CalculateInstanceSizeHelper (InstanceType instance_type, bool has_prototype_slot, int requested_embedder_fields, int requested_in_object_properties, int * instance_size, int * in_object_properties) [static]
Definition at line 1544 of file js-function.cc.
                                                                        {
  DCHECK_LE(static_cast<unsigned>(requested_embedder_fields),
            JSObject::kMaxEmbedderFields);
  int header_size = JSObject::GetHeaderSize(instance_type, has_prototype_slot);
  requested_embedder_fields *= kEmbedderDataSlotSizeInTaggedSlots;
  int max_nof_fields =
      (JSObject::kMaxInstanceSize - header_size) >> kTaggedSizeLog2;
  CHECK_LE(max_nof_fields, JSObject::kMaxInObjectProperties);
  CHECK_LE(static_cast<unsigned>(requested_embedder_fields),
           static_cast<unsigned>(max_nof_fields));
  *in_object_properties = std::min(requested_in_object_properties,
                                   max_nof_fields - requested_embedder_fields);
  *instance_size =
      header_size +
      ((requested_embedder_fields + *in_object_properties) << kTaggedSizeLog2);
  CHECK_EQ(*in_object_properties,
           ((*instance_size - header_size) >> kTaggedSizeLog2) -
               requested_embedder_fields);
  CHECK_LE(static_cast<unsigned>(*instance_size),
           static_cast<unsigned>(JSObject::kMaxInstanceSize));
}
References CHECK_EQ, CHECK_LE, DCHECK_LE, v8::internal::JSObject::GetHeaderSize(), v8::internal::has_prototype_slot, v8::internal::kEmbedderDataSlotSizeInTaggedSlots, v8::internal::JSObject::kMaxEmbedderFields, v8::internal::JSObject::kMaxInObjectProperties, v8::internal::JSObject::kMaxInstanceSize, and v8::internal::kTaggedSizeLog2.
Referenced by v8::internal::JSSharedStruct::CreateInstanceMap(), EnsureHasInitialMap(), and v8::internal::anonymous_namespace{js-function.cc}::FastInitializeDerivedMap().
CanDiscardCompiled()
bool v8::internal::JSFunction::CanDiscardCompiled (IsolateForSandbox isolate) const
Definition at line 231 of file js-function.cc.
                                                                   {
  // Essentially, what we are asking here is, has this function been compiled
  // from JS code? We can currently tell only indirectly, by looking at
  // available code kinds. If any JS code kind exists, we can discard.
  //
  // Attached optimized code that is marked for deoptimization will not show up
  // in the list of available code kinds, thus we must check for it manually.
  //
  // Note that when the function has not yet been compiled we also return
  // false; that's fine, since nothing must be discarded in that case.
  if (CodeKindIsOptimizedJSFunction(code(isolate)->kind())) return true;
  CodeKinds result = GetAvailableCodeKinds(isolate);
  return (result & kJSFunctionCodeKindsMask) != 0;
}
References code, v8::internal::CodeKindIsOptimizedJSFunction(), GetAvailableCodeKinds(), v8::internal::kJSFunctionCodeKindsMask, and v8::base::internal::result.
ChecksTieringState()
bool v8::internal::JSFunction::ChecksTieringState (IsolateForSandbox isolate) [inline]
Definition at line 58 of file js-function-inl.h.
                                                             {
  return code(isolate)->checks_tiering_state();
}
References code.
Referenced by set_tiering_state().
ClearAllTypeFeedbackInfoForTesting()
void v8::internal::JSFunction::ClearAllTypeFeedbackInfoForTesting (Isolate * isolate)
Definition at line 1572 of file js-function.cc.
                                                                    {
  ResetIfCodeFlushed(isolate);
  if (has_feedback_vector()) {
    Tagged<FeedbackVector> vector = feedback_vector();
    if (vector->ClearAllSlotsForTesting(isolate)) {
      IC::OnFeedbackChanged(isolate, vector, FeedbackSlot::Invalid(),
                            "ClearAllTypeFeedbackInfoForTesting");
    }
  }
}
References v8::internal::FeedbackSlot::Invalid(), v8::internal::IC::OnFeedbackChanged(), and ResetIfCodeFlushed().
Referenced by v8::internal::RUNTIME_FUNCTION().
closure_feedback_cell_array()
Tagged< ClosureFeedbackCellArray > v8::internal::JSFunction::closure_feedback_cell_array () const [inline]
Definition at line 52 of file js-function-inl.h.
          {
  DCHECK(has_closure_feedback_cell_array());
  return Cast<ClosureFeedbackCellArray>(raw_feedback_cell()->value());
}
References v8::internal::DCHECK(), has_closure_feedback_cell_array(), v8::internal::raw_feedback_cell, and v8::internal::value.
Referenced by CreateAndAttachFeedbackVector().
CompleteInobjectSlackTrackingIfActive()
void v8::internal::JSFunction::CompleteInobjectSlackTrackingIfActive (Isolate * isolate) [inline]
Definition at line 62 of file js-function-inl.h.
                                                                       {
  if (!has_prototype_slot()) return;
  if (has_initial_map() && initial_map()->IsInobjectSlackTrackingInProgress()) {
    MapUpdater::CompleteInobjectSlackTracking(isolate, initial_map());
  }
}
References v8::internal::MapUpdater::CompleteInobjectSlackTracking(), v8::internal::has_prototype_slot, and v8::internal::compiler::initial_map.
ComputeInstanceSizeWithMinSlack()
int v8::internal::JSFunction::ComputeInstanceSizeWithMinSlack (Isolate * isolate)
Definition at line 1338 of file js-function.cc.
                                                                {
  CHECK(has_initial_map());
  if (initial_map()->IsInobjectSlackTrackingInProgress()) {
    int slack = initial_map()->ComputeMinObjectSlack(isolate);
    return initial_map()->InstanceSizeFromSlack(slack);
  }
  return initial_map()->instance_size();
}
References CHECK, and v8::internal::compiler::initial_map.
context()
Tagged< Context > v8::internal::JSFunction::context () [inline]
Definition at line 463 of file js-function-inl.h.
                                    {
  return TaggedField<Context, kContextOffset>::load(*this);
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::load().
Referenced by GetDerivedRabGsabDataViewMap(), GetDerivedRabGsabTypedArrayMap(), global_proxy(), native_context(), v8::internal::WasmJSFunction::New(), and v8::internal::WasmExportedFunction::New().
CreateAndAttachFeedbackVector()
void v8::internal::JSFunction::CreateAndAttachFeedbackVector (Isolate * isolate, DirectHandle< JSFunction > function, IsCompiledScope * compiled_scope) [static]
Definition at line 692 of file js-function.cc.
                                     {
  CHECK(compiled_scope->is_compiled());
  DCHECK(function->shared()->HasFeedbackMetadata());
  DCHECK(!function->has_feedback_vector());
#if V8_ENABLE_WEBASSEMBLY
  DCHECK(!function->shared()->HasAsmWasmData());
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate);
  DCHECK(function->shared()->HasBytecodeArray());
  EnsureClosureFeedbackCellArray(isolate, function);
  DirectHandle<ClosureFeedbackCellArray> closure_feedback_cell_array(
      function->closure_feedback_cell_array(), isolate);
  DirectHandle<FeedbackVector> feedback_vector = FeedbackVector::New(
      isolate, shared, closure_feedback_cell_array,
      direct_handle(function->raw_feedback_cell(isolate), isolate),
      compiled_scope);
  USE(feedback_vector);
  // EnsureClosureFeedbackCellArray should handle the special case where we need
  // to allocate a new feedback cell. Please look at comment in that function
  // for more details.
  DCHECK(function->raw_feedback_cell() !=
         *isolate->factory()->many_closures_cell());
  DCHECK_EQ(function->raw_feedback_cell()->value(), *feedback_vector);
  function->SetInterruptBudget(isolate, BudgetModification::kRaise);
#ifndef V8_ENABLE_LEAPTIERING
  DCHECK_EQ(v8_flags.log_function_events,
            feedback_vector->log_next_execution());
#endif
  if (v8_flags.profile_guided_optimization &&
      v8_flags.profile_guided_optimization_for_empty_feedback_vector &&
      function->feedback_vector()->length() == 0) {
    if (function->shared()->cached_tiering_decision() ==
        CachedTieringDecision::kEarlyMaglev) {
      function->RequestOptimization(isolate, CodeKind::MAGLEV,
                                    ConcurrencyMode::kConcurrent);
    } else if (function->shared()->cached_tiering_decision() ==
               CachedTieringDecision::kEarlyTurbofan) {
      function->RequestOptimization(isolate, CodeKind::TURBOFAN_JS,
                                    ConcurrencyMode::kConcurrent);
    }
  }
}
References CHECK, closure_feedback_cell_array(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), EnsureClosureFeedbackCellArray(), v8::internal::Isolate::factory(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::kConcurrent, v8::internal::kEarlyMaglev, v8::internal::kEarlyTurbofan, v8::internal::kRaise, v8::internal::FeedbackVector::New(), USE, and v8::internal::v8_flags.
Referenced by EnsureFeedbackVector(), InitializeFeedbackCell(), v8::internal::TieringManager::OnInterruptTick(), and v8::internal::RUNTIME_FUNCTION().
DebugNameCStr()
std::unique_ptr< char[]> v8::internal::JSFunction::DebugNameCStr ()
Definition at line 1347 of file js-function.cc.
                                                {
  return shared()->DebugNameCStr();
}
Referenced by PrintName().
DECL_RELEASE_ACQUIRE_ACCESSORS()
v8::internal::JSFunction::DECL_RELEASE_ACQUIRE_ACCESSORS (prototype_or_initial_map , Tagged< UnionOf< JSPrototype, Map, Hole >>) const
EnsureClosureFeedbackCellArray()
void v8::internal::JSFunction::EnsureClosureFeedbackCellArray (Isolate * isolate, DirectHandle< JSFunction > function) [static]
Definition at line 621 of file js-function.cc.
                                                         {
  DCHECK(function->shared()->is_compiled());
  DCHECK(function->shared()->HasFeedbackMetadata());
#if V8_ENABLE_WEBASSEMBLY
  if (function->shared()->HasAsmWasmData()) return;
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate);
  DCHECK(shared->HasBytecodeArray());
  const bool has_closure_feedback_cell_array =
      (function->has_closure_feedback_cell_array() ||
       function->has_feedback_vector());
  if (has_closure_feedback_cell_array) {
    return;
  }
  // Many closure cell is used as a way to specify that there is no
  // feedback cell for this function and a new feedback cell has to be
  // allocated for this function. For ex: for eval functions, we have to create
  // a feedback cell and cache it along with the code. It is safe to use
  // many_closure_cell to indicate this because in regular cases, it should
  // already have a feedback_vector / feedback cell array allocated.
  const bool allocate_new_feedback_cell =
      function->raw_feedback_cell() ==
      *isolate->factory()->many_closures_cell();
  DirectHandle<ClosureFeedbackCellArray> feedback_cell_array =
      ClosureFeedbackCellArray::New(isolate, shared);
  if (allocate_new_feedback_cell) {
    DirectHandle<FeedbackCell> feedback_cell =
        isolate->factory()->NewOneClosureCell(feedback_cell_array);
#ifdef V8_ENABLE_LEAPTIERING
    // This is a rare case where we copy the dispatch entry from a JSFunction
    // to its FeedbackCell instead of the other way around.
    // TODO(42204201): investigate whether this can be avoided so that we only
    // ever copy a dispatch handle from a FeedbackCell to a JSFunction. That
    // would probably require refactoring the way JSFunctions are built so that
    // we always allocate a FeedbackCell up front (if needed).
    DCHECK_NE(function->dispatch_handle(), kNullJSDispatchHandle);
    // The feedback cell should never contain context specialized code.
    DCHECK(!function->code(isolate)->is_context_specialized());
    feedback_cell->set_dispatch_handle(function->dispatch_handle());
#endif // V8_ENABLE_LEAPTIERING
    function->set_raw_feedback_cell(*feedback_cell, kReleaseStore);
  } else {
    function->raw_feedback_cell()->set_value(*feedback_cell_array,
                                             kReleaseStore);
  }
  // Initialize the interrupt budget when initializing the feedback cell with
  // the closure feedback cell for the first time, whether the feedback cell
  // itself is new or not.
  function->SetInterruptBudget(isolate, BudgetModification::kReset);
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::Isolate::factory(), has_closure_feedback_cell_array(), v8::internal::kNullJSDispatchHandle(), v8::kReleaseStore, v8::internal::kReset, v8::internal::ClosureFeedbackCellArray::New(), and v8::internal::Factory::NewOneClosureCell().
Referenced by CreateAndAttachFeedbackVector(), and InitializeFeedbackCell().
EnsureFeedbackVector()
void v8::internal::JSFunction::EnsureFeedbackVector (Isolate * isolate, DirectHandle< JSFunction > function, IsCompiledScope * compiled_scope) [static]
FeedbackVector eventually. Generally this shouldn't be used to get the.
Definition at line 678 of file js-function.cc.
                                                                       {
  CHECK(compiled_scope->is_compiled());
  DCHECK(function->shared()->HasFeedbackMetadata());
  if (function->has_feedback_vector()) return;
#if V8_ENABLE_WEBASSEMBLY
  if (function->shared()->HasAsmWasmData()) return;
#endif // V8_ENABLE_WEBASSEMBLY
  CreateAndAttachFeedbackVector(isolate, function, compiled_scope);
}
References CHECK, CreateAndAttachFeedbackVector(), v8::internal::DCHECK(), and v8::internal::IsCompiledScope::is_compiled().
Referenced by v8::internal::Factory::JSFunctionBuilder::Build(), v8::internal::Compiler::Compile(), v8::internal::Compiler::CompileBaseline(), v8::internal::anonymous_namespace{runtime-test.cc}::EnsureCompiledAndFeedbackVector(), v8::internal::anonymous_namespace{runtime-test.cc}::OptimizeFunctionOnNextCall(), v8::internal::LiveEdit::PatchScript(), v8::internal::Compiler::PostInstantiation(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::Coverage::SelectMode().
EnsureHasInitialMap()
void v8::internal::JSFunction::EnsureHasInitialMap (Isolate * isolate, DirectHandle< JSFunction > function) [static]
Definition at line 931 of file js-function.cc.
                                                                        {
  DCHECK(function->has_prototype_slot());
  DCHECK(IsConstructor(*function) ||
         IsResumableFunction(function->shared()->kind()));
  if (function->has_initial_map()) return;
  int expected_nof_properties =
      CalculateExpectedNofProperties(isolate, function);
  // {CalculateExpectedNofProperties} can have had the side effect of creating
  // the initial map (e.g. it could have triggered an optimized compilation
  // whose dependency installation reentered {EnsureHasInitialMap}).
  if (function->has_initial_map()) return;
  // Create a new map with the size and number of in-object properties suggested
  // by the function.
  InstanceType instance_type;
  if (IsResumableFunction(function->shared()->kind())) {
    instance_type = IsAsyncGeneratorFunction(function->shared()->kind())
                        ? JS_ASYNC_GENERATOR_OBJECT_TYPE
                        : JS_GENERATOR_OBJECT_TYPE;
  } else {
    instance_type = JS_OBJECT_TYPE;
  }
  int instance_size;
  int inobject_properties;
  CalculateInstanceSizeHelper(instance_type, false, 0, expected_nof_properties,
                              &instance_size, &inobject_properties);
  DirectHandle<NativeContext> creation_context(function->native_context(),
                                               isolate);
  DirectHandle<Map> map = isolate->factory()->NewContextfulMap(
      creation_context, instance_type, instance_size,
      TERMINAL_FAST_ELEMENTS_KIND, inobject_properties);
  // Fetch or allocate prototype.
  DirectHandle<JSPrototype> prototype;
  if (function->has_instance_prototype()) {
    prototype = direct_handle(function->instance_prototype(), isolate);
    map->set_prototype(*prototype);
  } else {
    prototype = isolate->factory()->NewFunctionPrototype(function);
    Map::SetPrototype(isolate, map, prototype);
  }
  DCHECK(map->has_fast_object_elements());
  // Finally link initial map and constructor function.
  // This is a CHECK since the prototype could be Null according to the type
  // system.
  // TODO(leszeks): Figure out if this CHECK is needed.
  CHECK(IsJSReceiver(*prototype));
  JSFunction::SetInitialMap(isolate, function, map, prototype);
  map->StartInobjectSlackTracking();
}
References CalculateExpectedNofProperties(), CalculateInstanceSizeHelper(), CHECK, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::IsAsyncGeneratorFunction(), v8::internal::IsResumableFunction(), v8::internal::Factory::NewContextfulMap(), v8::internal::Factory::NewFunctionPrototype(), v8::internal::prototype, SetInitialMap(), v8::internal::Map::SetPrototype(), and v8::internal::TERMINAL_FAST_ELEMENTS_KIND.
Referenced by GetDerivedMap(), v8::internal::Factory::NewJSGeneratorObject(), v8::internal::Factory::NewJSObject(), and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::PrepareInstall().
GetActiveTier()
std::optional< CodeKind > v8::internal::JSFunction::GetActiveTier (IsolateForSandbox isolate) const
Definition at line 182 of file js-function.cc.
                                     {
#if V8_ENABLE_WEBASSEMBLY
  // Asm/Wasm functions are currently not supported. For simplicity, this
  // includes invalid asm.js functions whose code hasn't yet been updated to
  // CompileLazy but is still the InstantiateAsmJs builtin.
  if (shared()->HasAsmWasmData() ||
      code(isolate)->builtin_id() == Builtin::kInstantiateAsmJs) {
    return {};
  }
#endif // V8_ENABLE_WEBASSEMBLY
  CodeKind highest_tier;
  if (!HighestTierOf(GetAvailableCodeKinds(isolate), &highest_tier)) return {};
#ifdef DEBUG
  CHECK(highest_tier == CodeKind::TURBOFAN_JS ||
        highest_tier == CodeKind::BASELINE ||
        highest_tier == CodeKind::MAGLEV ||
        highest_tier == CodeKind::INTERPRETED_FUNCTION);
  if (highest_tier == CodeKind::INTERPRETED_FUNCTION) {
    CHECK(code(isolate)->is_interpreter_trampoline_builtin() ||
          (CodeKindIsOptimizedJSFunction(code(isolate)->kind()) &&
           code(isolate)->marked_for_deoptimization()) ||
          (code(isolate)->builtin_id() == Builtin::kCompileLazy &&
           shared()->HasBytecodeArray() && !shared()->HasBaselineCode()));
  }
#endif // DEBUG
  return highest_tier;
}
References CHECK, code, v8::internal::CodeKindIsOptimizedJSFunction(), GetAvailableCodeKinds(), and v8::internal::anonymous_namespace{js-function.cc}::HighestTierOf().
Referenced by ActiveTierIsBaseline(), ActiveTierIsIgnition(), ActiveTierIsMaglev(), and ActiveTierIsTurbofan().
GetAttachedCodeKinds()
CodeKinds v8::internal::JSFunction::GetAttachedCodeKinds (IsolateForSandbox isolate) const [private]
Definition at line 28 of file js-function.cc.
                                                                          {
  const CodeKind kind = code(isolate)->kind();
  if (!CodeKindIsJSFunction(kind)) return {};
  if (CodeKindIsOptimizedJSFunction(kind) &&
      code(isolate)->marked_for_deoptimization()) {
    return {};
  }
  return CodeKindToCodeKindFlag(kind);
}
References code, v8::internal::CodeKindIsJSFunction(), v8::internal::CodeKindIsOptimizedJSFunction(), and v8::internal::CodeKindToCodeKindFlag().
Referenced by GetAvailableCodeKinds(), HasAttachedCodeKind(), and HasAttachedOptimizedCode().
GetAvailableCodeKinds()
CodeKinds v8::internal::JSFunction::GetAvailableCodeKinds (IsolateForSandbox isolate) const
Definition at line 38 of file js-function.cc.
                                                                           {
  CodeKinds result = GetAttachedCodeKinds(isolate);
  if ((result & CodeKindFlag::INTERPRETED_FUNCTION) == 0) {
    // The SharedFunctionInfo could have attached bytecode.
    if (shared()->HasBytecodeArray()) {
      result |= CodeKindFlag::INTERPRETED_FUNCTION;
    }
  }
  if ((result & CodeKindFlag::BASELINE) == 0) {
    // The SharedFunctionInfo could have attached baseline code.
    if (shared()->HasBaselineCode()) {
      result |= CodeKindFlag::BASELINE;
    }
  }
#ifndef V8_ENABLE_LEAPTIERING
  // Check the optimized code cache.
  if (has_feedback_vector() && feedback_vector()->has_optimized_code() &&
      !feedback_vector()
           ->optimized_code(isolate)
           ->marked_for_deoptimization()) {
    Tagged<Code> code = feedback_vector()->optimized_code(isolate);
    DCHECK(CodeKindIsOptimizedJSFunction(code->kind()));
    result |= CodeKindToCodeKindFlag(code->kind());
  }
#endif // !V8_ENABLE_LEAPTIERING
  DCHECK_EQ((result & ~kJSFunctionCodeKindsMask), 0);
  return result;
}
References code, v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::CodeKindToCodeKindFlag(), v8::internal::DCHECK(), DCHECK_EQ, GetAttachedCodeKinds(), v8::internal::kJSFunctionCodeKindsMask, and v8::base::internal::result.
Referenced by CanDiscardCompiled(), GetActiveTier(), HasAvailableCodeKind(), HasAvailableHigherTierCodeThanWithFilter(), and HasAvailableOptimizedCode().
GetDebugName()
DirectHandle< String > v8::internal::JSFunction::GetDebugName (Isolate * isolate, DirectHandle< JSFunction > function) [static]
Definition at line 1378 of file js-function.cc.
                                                         {
  // Below we use the same fast-path that we already established for
  // Function.prototype.bind(), where we avoid a slow "name" property
  // lookup if the DescriptorArray for the |function| still has the
  // "name" property at the original spot and that property is still
  // implemented via an AccessorInfo (which effectively means that
  // it must be the FunctionNameGetter).
  if (!UseFastFunctionNameLookup(isolate, function->map())) {
    // Normally there should be an else case for the fast-path check
    // above, which should invoke JSFunction::GetName(), since that's
    // what the FunctionNameGetter does, however GetDataProperty() has
    // never invoked accessors and thus always returned undefined for
    // JSFunction where the "name" property is untouched, so we retain
    // that exact behavior and go with SharedFunctionInfo::DebugName()
    // in case of the fast-path.
    DirectHandle<Object> name =
        GetDataProperty(isolate, function, isolate->factory()->name_string());
    if (IsString(*name)) return Cast<String>(name);
  }
  return SharedFunctionInfo::DebugName(
      isolate, direct_handle(function->shared(), isolate));
}
References v8::internal::SharedFunctionInfo::DebugName(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::name, and v8::internal::anonymous_namespace{js-function.cc}::UseFastFunctionNameLookup().
Referenced by v8::internal::FrameSummary::JavaScriptFrameSummary::CreateStackFrameInfo(), v8::Function::GetDebugName(), v8::internal::ScopeIterator::GetFunctionDebugName(), v8::internal::CallSiteInfo::GetFunctionDebugName(), v8::internal::FrameInspector::GetFunctionName(), v8::internal::CallSiteInfo::GetFunctionName(), v8::internal::CallSiteInfo::GetTypeName(), and v8::internal::WasmJSFunction::New().
GetDerivedMap()
MaybeHandle< Map > v8::internal::JSFunction::GetDerivedMap (Isolate * isolate, DirectHandle< JSFunction > constructor, DirectHandle< JSReceiver > new_target) [static]
Definition at line 1188 of file js-function.cc.
                                         {
  EnsureHasInitialMap(isolate, constructor);
  DirectHandle<Map> constructor_initial_map(constructor->initial_map(),
                                            isolate);
  if (*new_target == *constructor) {
    return indirect_handle(constructor_initial_map, isolate);
  }
  DirectHandle<Map> result_map;
  // Fast case, new.target is a subclass of constructor. The map is cacheable
  // (and may already have been cached). new.target.prototype is guaranteed to
  // be a JSReceiver.
  InstanceType new_target_instance_type = new_target->map()->instance_type();
  if (InstanceTypeChecker::IsJSFunction(new_target_instance_type)) {
    DirectHandle<JSFunction> function = Cast<JSFunction>(new_target);
    if (FastInitializeDerivedMap(isolate, function, constructor,
                                 constructor_initial_map)) {
      return handle(function->initial_map(), isolate);
    }
  }
  // Slow path, new.target is either a proxy object or can't cache the map.
  // new.target.prototype is not guaranteed to be a JSReceiver, and may need to
  // fall back to the intrinsicDefaultProto.
  DirectHandle<Object> prototype;
  if (InstanceTypeChecker::IsJSFunction(new_target_instance_type) &&
      Cast<JSFunction>(new_target)->has_prototype_slot()) {
    DirectHandle<JSFunction> function = Cast<JSFunction>(new_target);
    // Make sure the new.target.prototype is cached.
    EnsureHasInitialMap(isolate, function);
    prototype = direct_handle(function->prototype(), isolate);
  } else {
    // The new.target is a constructor but it's not a JSFunction with
    // a prototype slot, so get the prototype property.
    DirectHandle<String> prototype_string =
        isolate->factory()->prototype_string();
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, prototype,
        JSReceiver::GetProperty(isolate, new_target, prototype_string));
    // The above prototype lookup might change the constructor and its
    // prototype, hence we have to reload the initial map.
    EnsureHasInitialMap(isolate, constructor);
    constructor_initial_map =
        direct_handle(constructor->initial_map(), isolate);
  }
  // If prototype is not a JSReceiver, fetch the intrinsicDefaultProto from the
  // correct realm. Rather than directly fetching the .prototype, we fetch the
  // constructor that points to the .prototype. This relies on
  // constructor.prototype being FROZEN for those constructors.
  if (!IsJSReceiver(*prototype)) {
    DirectHandle<NativeContext> native_context;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, native_context,
                               JSReceiver::GetFunctionRealm(new_target));
    DirectHandle<Object> maybe_index = JSReceiver::GetDataProperty(
        isolate, constructor,
        isolate->factory()->native_context_index_symbol());
    int index = IsSmi(*maybe_index) ? Smi::ToInt(*maybe_index)
                                    : Context::OBJECT_FUNCTION_INDEX;
    DirectHandle<JSFunction> realm_constructor(
        Cast<JSFunction>(native_context->GetNoCell(index)), isolate);
    prototype = direct_handle(realm_constructor->prototype(), isolate);
  }
  DCHECK_EQ(constructor_initial_map->constructor_or_back_pointer(),
            *constructor);
  return Map::GetDerivedMap(isolate, constructor_initial_map,
                            Cast<JSReceiver>(prototype));
}
References ASSIGN_RETURN_ON_EXCEPTION, DCHECK_EQ, v8::internal::direct_handle(), EnsureHasInitialMap(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{js-function.cc}::FastInitializeDerivedMap(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::Map::GetDerivedMap(), v8::internal::JSReceiver::GetProperty(), v8::internal::handle(), v8::internal::has_prototype_slot, v8::internal::index, v8::internal::indirect_handle(), v8::internal::IsSmi(), native_context(), v8::internal::prototype, and v8::internal::Smi::ToInt().
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-intl.cc}::CallOrConstructConstructor(), v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::anonymous_namespace{builtins-intl.cc}::DisallowCallConstructor(), GetDerivedRabGsabDataViewMap(), GetDerivedRabGsabTypedArrayMap(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugProxyMap(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::JSObject::New(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSDateTimeFormat::TemporalToLocaleString(), and v8::internal::JSDateTimeFormat::ToLocaleDateTime().
GetDerivedRabGsabDataViewMap()
MaybeDirectHandle< Map > v8::internal::JSFunction::GetDerivedRabGsabDataViewMap (Isolate * isolate, DirectHandle< JSReceiver > new_target) [static]
Definition at line 1317 of file js-function.cc.
                                                           {
  DirectHandle<Context> context(isolate->context()->native_context(), isolate);
  DirectHandle<JSFunction> constructor(context->data_view_fun(), isolate);
  MaybeDirectHandle<Map> maybe_map =
      GetDerivedMap(isolate, constructor, new_target);
  DirectHandle<Map> map;
  if (!maybe_map.ToHandle(&map)) return {};
  if (*map == constructor->initial_map()) {
    return direct_handle(Cast<Map>(context->js_rab_gsab_data_view_map()),
                         isolate);
  }
  // This only happens when subclassing DataViews. Create a new map with the
  // JS_RAB_GSAB_DATA_VIEW instance type. Note: the map is not cached and
  // reused -> every data view gets a unique map, making ICs slow.
  DirectHandle<Map> rab_gsab_map = Map::Copy(isolate, map, "RAB / GSAB");
  rab_gsab_map->set_instance_type(JS_RAB_GSAB_DATA_VIEW_TYPE);
  return rab_gsab_map;
}
References context(), v8::internal::Isolate::context(), v8::internal::Map::Copy(), v8::internal::direct_handle(), GetDerivedMap(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::internal::BUILTIN().
GetDerivedRabGsabTypedArrayMap()
MaybeDirectHandle< Map > v8::internal::JSFunction::GetDerivedRabGsabTypedArrayMap (Isolate * isolate, DirectHandle< JSFunction > constructor, DirectHandle< JSReceiver > new_target) [static]
Definition at line 1289 of file js-function.cc.
                                         {
  MaybeDirectHandle<Map> maybe_map =
      GetDerivedMap(isolate, constructor, new_target);
  DirectHandle<Map> map;
  if (!maybe_map.ToHandle(&map)) return {};
  {
    DisallowHeapAllocation no_alloc;
    Tagged<NativeContext> context = isolate->context()->native_context();
    int ctor_index =
        TypedArrayElementsKindToConstructorIndex(map->elements_kind());
    if (*new_target == context->GetNoCell(ctor_index)) {
      ctor_index =
          TypedArrayElementsKindToRabGsabCtorIndex(map->elements_kind());
      return direct_handle(Cast<Map>(context->GetNoCell(ctor_index)), isolate);
    }
  }
  // This only happens when subclassing TypedArrays. Create a new map with the
  // corresponding RAB / GSAB ElementsKind. Note: the map is not cached and
  // reused -> every array gets a unique map, making ICs slow.
  DirectHandle<Map> rab_gsab_map = Map::Copy(isolate, map, "RAB / GSAB");
  rab_gsab_map->set_elements_kind(
      GetCorrespondingRabGsabElementsKind(map->elements_kind()));
  return rab_gsab_map;
}
References context(), v8::internal::Isolate::context(), v8::internal::Map::Copy(), v8::internal::direct_handle(), v8::internal::GetCorrespondingRabGsabElementsKind(), GetDerivedMap(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::anonymous_namespace{js-function.cc}::TypedArrayElementsKindToConstructorIndex(), and v8::internal::anonymous_namespace{js-function.cc}::TypedArrayElementsKindToRabGsabCtorIndex().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetHeaderSize()
static int v8::internal::JSFunction::GetHeaderSize (bool function_has_prototype_slot) [inline], [static]
Definition at line 391 of file js-function.h.
                                                             {
    return function_has_prototype_slot ? JSFunction::kSizeWithPrototype
                                       : JSFunction::kSizeWithoutPrototype;
  }
References kSizeWithoutPrototype, and kSizeWithPrototype.
Referenced by v8::internal::Factory::JSFunctionBuilder::BuildRaw(), v8::internal::JSObject::GetHeaderSize(), and v8::internal::JSFunction::BodyDescriptor::IterateBody().
GetName() [1/2]
static DirectHandle<String> v8::internal::JSFunction::GetName (DirectHandle< JSFunction > function) [static]
GetName() [2/2]
Handle< String > v8::internal::JSFunction::GetName (Isolate * isolate, DirectHandle< JSFunction > function) [static]
Definition at line 612 of file js-function.cc.
                                                                      {
  if (function->shared()->name_should_print_as_anonymous()) {
    return isolate->factory()->anonymous_string();
  }
  return handle(function->shared()->Name(), isolate);
}
References v8::internal::Isolate::factory(), and v8::internal::handle().
Referenced by v8::internal::JSBoundFunction::GetName(), v8::internal::JSWrappedFunction::GetName(), v8::internal::Object::NoSideEffectsToMaybeString(), and v8::internal::RUNTIME_FUNCTION().
GetRequestedOptimizationIfAny()
std::optional< CodeKind > v8::internal::JSFunction::GetRequestedOptimizationIfAny (Isolate * isolate, ConcurrencyMode mode = ConcurrencyMode::kConcurrent) const [inline]
Definition at line 337 of file js-function-inl.h.
                                                  {
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
  Address entrypoint = jdt->GetEntrypoint(dispatch_handle());
  const EmbeddedData& embedded_data = EmbeddedData::FromBlob(isolate);
  auto builtin = ([&]() -> std::optional<TieringBuiltin> {
#define CASE(name, ...) \
  if (entrypoint == embedded_data.InstructionStartOf(Builtin::k##name)) { \
    DCHECK(jdt->IsTieringRequested(dispatch_handle(), TieringBuiltin::k##name, \
                                   isolate)); \
    return TieringBuiltin::k##name; \
  }
    BUILTIN_LIST_BASE_TIERING(CASE)
#undef CASE
    DCHECK(!jdt->IsTieringRequested(dispatch_handle()));
    return {};
  })();
  if (V8_LIKELY(!builtin)) return {};
  switch (*builtin) {
    case TieringBuiltin::kOptimizeMaglevEager:
      if (mode == ConcurrencyMode::kSynchronous) return CodeKind::MAGLEV;
      break;
    case TieringBuiltin::kStartMaglevOptimizeJob:
      if (mode == ConcurrencyMode::kConcurrent) return CodeKind::MAGLEV;
      break;
    case TieringBuiltin::kOptimizeTurbofanEager:
      if (mode == ConcurrencyMode::kSynchronous) return CodeKind::TURBOFAN_JS;
      break;
    case TieringBuiltin::kStartTurbofanOptimizeJob:
      if (mode == ConcurrencyMode::kConcurrent) return CodeKind::TURBOFAN_JS;
      break;
    case TieringBuiltin::kMarkLazyDeoptimized:
    case TieringBuiltin::kMarkReoptimizeLazyDeoptimized:
    case TieringBuiltin::kFunctionLogNextExecution:
      break;
  }
#else
  switch (mode) {
    case ConcurrencyMode::kConcurrent:
      if (IsRequestTurbofan_Concurrent(tiering_state())) {
        return CodeKind::TURBOFAN_JS;
      }
      if (IsRequestMaglev_Concurrent(tiering_state())) {
        return CodeKind::MAGLEV;
      }
      break;
    case ConcurrencyMode::kSynchronous:
      if (IsRequestTurbofan_Synchronous(tiering_state())) {
        return CodeKind::TURBOFAN_JS;
      }
      if (IsRequestMaglev_Synchronous(tiering_state())) {
        return CodeKind::MAGLEV;
      }
      break;
  }
#endif // !V8_ENABLE_LEAPTIERING
  return {};
}
References BUILTIN_LIST_BASE_TIERING, CASE, v8::internal::IsolateGroup::current(), v8::internal::DCHECK(), v8::internal::EmbeddedData::FromBlob(), v8::internal::kConcurrent, v8::internal::kSynchronous, mode(), tiering_state(), and V8_LIKELY.
global_proxy()
Tagged< JSGlobalProxy > v8::internal::JSFunction::global_proxy () [inline]
Definition at line 475 of file js-function-inl.h.
                                               {
  return context()->global_proxy();
}
References context().
has_closure_feedback_cell_array()
bool v8::internal::JSFunction::has_closure_feedback_cell_array () const [inline]
Definition at line 458 of file js-function-inl.h.
                                                       {
  return shared()->is_compiled() &&
         IsClosureFeedbackCellArray(raw_feedback_cell()->value());
}
References v8::internal::raw_feedback_cell, and v8::internal::value.
Referenced by closure_feedback_cell_array(), EnsureClosureFeedbackCellArray(), and InitializeFeedbackCell().
has_context()
bool v8::internal::JSFunction::has_context () const [inline]
Definition at line 471 of file js-function-inl.h.
                                   {
  return IsContext(TaggedField<HeapObject, kContextOffset>::load(*this));
}
HasAttachedCodeKind()
bool v8::internal::JSFunction::HasAttachedCodeKind (IsolateForSandbox isolate, CodeKind kind) const
Definition at line 151 of file js-function.cc.
                                                          {
  CodeKinds result = GetAttachedCodeKinds(isolate);
  return (result & CodeKindToCodeKindFlag(kind)) != 0;
}
References v8::internal::CodeKindToCodeKindFlag(), GetAttachedCodeKinds(), and v8::base::internal::result.
HasAttachedOptimizedCode()
bool v8::internal::JSFunction::HasAttachedOptimizedCode (IsolateForSandbox isolate) const
Definition at line 124 of file js-function.cc.
                                                                         {
  CodeKinds result = GetAttachedCodeKinds(isolate);
  return (result & kOptimizedJSFunctionCodeKindsMask) != 0;
}
References GetAttachedCodeKinds(), v8::internal::kOptimizedJSFunctionCodeKindsMask, and v8::base::internal::result.
HasAvailableCodeKind()
bool v8::internal::JSFunction::HasAvailableCodeKind (IsolateForSandbox isolate, CodeKind kind) const
Definition at line 157 of file js-function.cc.
                                                           {
  CodeKinds result = GetAvailableCodeKinds(isolate);
  return (result & CodeKindToCodeKindFlag(kind)) != 0;
}
References v8::internal::CodeKindToCodeKindFlag(), GetAvailableCodeKinds(), and v8::base::internal::result.
HasAvailableHigherTierCodeThan()
bool v8::internal::JSFunction::HasAvailableHigherTierCodeThan (IsolateForSandbox isolate, CodeKind kind) const
Definition at line 129 of file js-function.cc.
                                                                     {
  return HasAvailableHigherTierCodeThanWithFilter(isolate, kind,
                                                  kJSFunctionCodeKindsMask);
}
References HasAvailableHigherTierCodeThanWithFilter(), and v8::internal::kJSFunctionCodeKindsMask.
HasAvailableHigherTierCodeThanWithFilter()
bool v8::internal::JSFunction::HasAvailableHigherTierCodeThanWithFilter (IsolateForSandbox isolate, CodeKind kind, CodeKinds filter_mask) const
Definition at line 135 of file js-function.cc.
                                                                           {
  const int kind_as_int_flag = static_cast<int>(CodeKindToCodeKindFlag(kind));
  DCHECK(base::bits::IsPowerOfTwo(kind_as_int_flag));
  // Smear right - any higher present bit means we have a higher tier available.
  const int mask = kind_as_int_flag | (kind_as_int_flag - 1);
  const CodeKinds masked_available_kinds =
      GetAvailableCodeKinds(isolate) & filter_mask;
  return (masked_available_kinds & static_cast<CodeKinds>(~mask)) != 0;
}
References v8::internal::CodeKindToCodeKindFlag(), v8::internal::DCHECK(), GetAvailableCodeKinds(), and v8::base::bits::IsPowerOfTwo().
Referenced by HasAvailableHigherTierCodeThan().
HasAvailableOptimizedCode()
bool v8::internal::JSFunction::HasAvailableOptimizedCode (IsolateForSandbox isolate) const
Definition at line 146 of file js-function.cc.
                                                                          {
  CodeKinds result = GetAvailableCodeKinds(isolate);
  return (result & kOptimizedJSFunctionCodeKindsMask) != 0;
}
References GetAvailableCodeKinds(), v8::internal::kOptimizedJSFunctionCodeKindsMask, and v8::base::internal::result.
InitializeFeedbackCell()
void v8::internal::JSFunction::InitializeFeedbackCell (Isolate * isolate, DirectHandle< JSFunction > function, IsCompiledScope * compiled_scope, bool reset_budget_for_feedback_allocation) [static]
Definition at line 742 of file js-function.cc.
                                               {
#if V8_ENABLE_WEBASSEMBLY
  // The following checks ensure that the feedback vectors are compatible with
  // the feedback metadata. For Asm / Wasm functions we never allocate / use
  // feedback vectors, so a mismatch between the metadata and feedback vector is
  // harmless. The checks could fail for functions that has has_asm_wasm_broken
  // set at runtime (for ex: failed instantiation).
  if (function->shared()->HasAsmWasmData()) return;
#endif // V8_ENABLE_WEBASSEMBLY
  if (function->has_feedback_vector()) {
    CHECK_EQ(function->feedback_vector()->length(),
             function->feedback_vector()->metadata()->slot_count());
    return;
  }
  bool has_closure_feedback_cell_array =
      function->has_closure_feedback_cell_array();
  if (has_closure_feedback_cell_array) {
    CHECK_EQ(
        function->closure_feedback_cell_array()->length(),
        function->shared()->feedback_metadata()->create_closure_slot_count());
  }
  const bool needs_feedback_vector =
      !v8_flags.lazy_feedback_allocation || v8_flags.always_turbofan ||
      // We also need a feedback vector for certain log events, collecting type
      // profile and more precise code coverage.
      v8_flags.log_function_events ||
      !isolate->is_best_effort_code_coverage() ||
      function->shared()->cached_tiering_decision() !=
          CachedTieringDecision::kPending;
  if (needs_feedback_vector) {
    CreateAndAttachFeedbackVector(isolate, function, is_compiled_scope);
  } else if (has_closure_feedback_cell_array) {
    // Initialize the interrupt budget to the feedback vector allocation budget
    // after a bytecode flush. We retain the closure feedback cell array on
    // bytecode flush, so reset_budget_for_feedback_allocation is used to reset
    // the budget in this case.
    if (reset_budget_for_feedback_allocation) {
      function->SetInterruptBudget(isolate, BudgetModification::kReset);
    }
  } else {
    EnsureClosureFeedbackCellArray(isolate, function);
  }
#ifdef V8_ENABLE_SPARKPLUG
  // TODO(jgruber): Unduplicate these conditions from tiering-manager.cc.
  if (function->shared()->cached_tiering_decision() !=
          CachedTieringDecision::kPending &&
      CanCompileWithBaseline(isolate, function->shared()) &&
      function->ActiveTierIsIgnition(isolate)) {
    if (v8_flags.baseline_batch_compilation) {
      isolate->baseline_batch_compiler()->EnqueueFunction(function);
    } else {
      IsCompiledScope is_compiled_inner_scope(
          function->shared()->is_compiled_scope(isolate));
      Compiler::CompileBaseline(isolate, function, Compiler::CLEAR_EXCEPTION,
                                &is_compiled_inner_scope);
    }
  }
#endif // V8_ENABLE_SPARKPLUG
}
References v8::internal::CanCompileWithBaseline(), CHECK_EQ, v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::CompileBaseline(), CreateAndAttachFeedbackVector(), EnsureClosureFeedbackCellArray(), has_closure_feedback_cell_array(), v8::internal::Isolate::is_best_effort_code_coverage(), v8::internal::kPending, v8::internal::kReset, and v8::internal::v8_flags.
Referenced by v8::internal::Compiler::Compile(), v8::internal::Compiler::GetFunctionFromEval(), and v8::internal::Compiler::PostInstantiation().
instruction_start()
Address v8::internal::JSFunction::instruction_start (IsolateForSandbox isolate) const [inline]
Definition at line 243 of file js-function-inl.h.
                                                                     {
  return code(isolate)->instruction_start();
}
References code.
is_compiled()
bool v8::internal::JSFunction::is_compiled (IsolateForSandbox isolate) const [inline]
Definition at line 544 of file js-function-inl.h.
                                                            {
  return code(isolate, kAcquireLoad)->builtin_id() != Builtin::kCompileLazy &&
         shared()->is_compiled();
}
References code, and v8::kAcquireLoad.
Referenced by RequestOptimization().
IsLoggingRequested()
bool v8::internal::JSFunction::IsLoggingRequested (Isolate * isolate) const [inline]
Definition at line 284 of file js-function-inl.h.
                                                          {
#ifdef V8_ENABLE_LEAPTIERING
  return IsolateGroup::current()->js_dispatch_table()->IsTieringRequested(
      dispatch_handle(), TieringBuiltin::kFunctionLogNextExecution, isolate);
#else
  return feedback_vector()->log_next_execution();
#endif
}
References v8::internal::IsolateGroup::current().
IsMaglevRequested()
bool v8::internal::JSFunction::IsMaglevRequested (Isolate * isolate) const [inline]
Definition at line 293 of file js-function-inl.h.
                                                         {
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
  Address entrypoint = jdt->GetEntrypoint(dispatch_handle());
  const EmbeddedData& embedded_data = EmbeddedData::FromBlob(isolate);
#define CASE(name, ...) \
  if (entrypoint == embedded_data.InstructionStartOf(Builtin::k##name)) { \
    DCHECK(jdt->IsTieringRequested(dispatch_handle(), TieringBuiltin::k##name, \
                                   isolate)); \
    return TieringBuiltin::k##name != \
           TieringBuiltin::kFunctionLogNextExecution; \
  }
  BUILTIN_LIST_BASE_TIERING_MAGLEV(CASE)
#undef CASE
  return {};
#else
  return IsRequestMaglev(tiering_state());
#endif
}
References CASE, v8::internal::IsolateGroup::current(), v8::internal::EmbeddedData::FromBlob(), v8::internal::IsRequestMaglev(), and tiering_state().
Referenced by IsOptimizationRequested().
IsOptimizationRequested()
bool v8::internal::JSFunction::IsOptimizationRequested (Isolate * isolate) const [inline]
Definition at line 333 of file js-function-inl.h.
                                                               {
  return IsMaglevRequested(isolate) || IsTurbofanRequested(isolate);
}
References IsMaglevRequested(), and IsTurbofanRequested().
Referenced by NeedsResetDueToFlushedBytecode().
IsTieringRequestedOrInProgress()
bool v8::internal::JSFunction::IsTieringRequestedOrInProgress () const [inline]
Definition at line 273 of file js-function-inl.h.
                                                      {
#ifdef V8_ENABLE_LEAPTIERING
  if (!has_feedback_vector()) return false;
  return tiering_in_progress() ||
         IsolateGroup::current()->js_dispatch_table()->IsTieringRequested(
             dispatch_handle());
#else
  return tiering_state() != TieringState::kNone;
#endif
}
References v8::internal::IsolateGroup::current(), tiering_in_progress(), and tiering_state().
IsTurbofanRequested()
bool v8::internal::JSFunction::IsTurbofanRequested (Isolate * isolate) const [inline]
Definition at line 313 of file js-function-inl.h.
                                                           {
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
  Address entrypoint = jdt->GetEntrypoint(dispatch_handle());
  const EmbeddedData& embedded_data = EmbeddedData::FromBlob(isolate);
#define CASE(name, ...) \
  if (entrypoint == embedded_data.InstructionStartOf(Builtin::k##name)) { \
    DCHECK(jdt->IsTieringRequested(dispatch_handle(), TieringBuiltin::k##name, \
                                   isolate)); \
    return TieringBuiltin::k##name != \
           TieringBuiltin::kFunctionLogNextExecution; \
  }
  BUILTIN_LIST_BASE_TIERING_TURBOFAN(CASE)
#undef CASE
  return {};
#else
  return IsRequestTurbofan(tiering_state());
#endif
}
References CASE, v8::internal::IsolateGroup::current(), v8::internal::EmbeddedData::FromBlob(), v8::internal::IsRequestTurbofan(), and tiering_state().
Referenced by IsOptimizationRequested().
length()
int v8::internal::JSFunction::length () [inline]
Definition at line 78 of file js-function-inl.h.
{ return shared()->length(); }
Referenced by v8::internal::WasmExportedFunction::New().
native_context()
Tagged< NativeContext > v8::internal::JSFunction::native_context () [inline]
Definition at line 479 of file js-function-inl.h.
                                                 {
  return context()->native_context();
}
References context().
Referenced by GetDerivedMap(), and SetPrototype().
NeedsResetDueToFlushedBaselineCode()
bool v8::internal::JSFunction::NeedsResetDueToFlushedBaselineCode (IsolateForSandbox isolate) [inline]
Definition at line 573 of file js-function-inl.h.
                                                                             {
  return code(isolate)->kind() == CodeKind::BASELINE &&
         !shared()->HasBaselineCode();
}
References code.
Referenced by ResetIfCodeFlushed().
NeedsResetDueToFlushedBytecode()
bool v8::internal::JSFunction::NeedsResetDueToFlushedBytecode (Isolate * isolate) [inline]
Definition at line 549 of file js-function-inl.h.
                                                                {
  // Do a raw read for shared and code fields here since this function may be
  // called on a concurrent thread. JSFunction itself should be fully
  // initialized here but the SharedFunctionInfo, Code objects may not be
  // initialized. We read using acquire loads to defend against that.
  // TODO(v8) the branches for !IsSharedFunctionInfo() and !IsCode() are
  // probably dead code by now. Investigate removing them or replacing them
  // with CHECKs.
  Tagged<Object> maybe_shared =
      ACQUIRE_READ_FIELD(*this, kSharedFunctionInfoOffset);
  if (!IsSharedFunctionInfo(maybe_shared)) return false;
  Tagged<Object> maybe_code = raw_code(isolate, kAcquireLoad);
  if (!IsCode(maybe_code)) return false;
  Tagged<Code> code = Cast<Code>(maybe_code);
  Tagged<SharedFunctionInfo> shared = Cast<SharedFunctionInfo>(maybe_shared);
  return !shared->is_compiled() &&
         (code->builtin_id() != Builtin::kCompileLazy ||
          // With leaptiering we can have CompileLazy as the code object but
          // still an optimization trampoline installed.
          (V8_ENABLE_LEAPTIERING_BOOL && IsOptimizationRequested(isolate)));
}
References ACQUIRE_READ_FIELD, code, IsOptimizationRequested(), v8::kAcquireLoad, raw_code(), and V8_ENABLE_LEAPTIERING_BOOL.
Referenced by ResetIfCodeFlushed().
osr_tiering_in_progress()
bool v8::internal::JSFunction::osr_tiering_in_progress () [inline]
Definition at line 447 of file js-function-inl.h.
                                         {
  DCHECK(has_feedback_vector());
  return feedback_vector()->osr_tiering_in_progress();
}
References v8::internal::DCHECK().
PrintName()
void v8::internal::JSFunction::PrintName (FILE * out = stdout)
Definition at line 1351 of file js-function.cc.
                                    {
  PrintF(out, "%s", DebugNameCStr().get());
}
References DebugNameCStr(), and v8::internal::PrintF().
raw_code() [1/2]
Tagged< Object > v8::internal::JSFunction::raw_code (IsolateForSandbox isolate) const [inline]
Definition at line 165 of file js-function-inl.h.
                                                                   {
#if V8_ENABLE_LEAPTIERING
  JSDispatchHandle handle = dispatch_handle();
  if (handle == kNullJSDispatchHandle) return Smi::zero();
  return IsolateGroup::current()->js_dispatch_table()->GetCode(handle);
#elif V8_ENABLE_SANDBOX
  return RawIndirectPointerField(kCodeOffset, kCodeIndirectPointerTag)
      .Relaxed_Load(isolate);
#else
  return RELAXED_READ_FIELD(*this, JSFunction::kCodeOffset);
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::IsolateGroup::current(), v8::internal::handle(), v8::internal::kNullJSDispatchHandle(), RELAXED_READ_FIELD, and v8::internal::Smi::zero().
Referenced by NeedsResetDueToFlushedBytecode().
raw_code() [2/2]
Tagged< Object > v8::internal::JSFunction::raw_code (IsolateForSandbox isolate, AcquireLoadTag tag) const [inline]
Definition at line 178 of file js-function-inl.h.
                                                              {
#if V8_ENABLE_LEAPTIERING
  JSDispatchHandle handle = dispatch_handle(tag);
  if (handle == kNullJSDispatchHandle) return Smi::zero();
  return IsolateGroup::current()->js_dispatch_table()->GetCode(handle);
#elif V8_ENABLE_SANDBOX
  return RawIndirectPointerField(kCodeOffset, kCodeIndirectPointerTag)
      .Acquire_Load(isolate);
#else
  return ACQUIRE_READ_FIELD(*this, JSFunction::kCodeOffset);
#endif // V8_ENABLE_SANDBOX
}
References ACQUIRE_READ_FIELD, v8::internal::IsolateGroup::current(), v8::internal::handle(), v8::internal::kNullJSDispatchHandle(), and v8::internal::Smi::zero().
RequestOptimization()
void v8::internal::JSFunction::RequestOptimization (Isolate * isolate, CodeKind target_kind, ConcurrencyMode mode = ConcurrencyMode::kConcurrent)
Definition at line 264 of file js-function.cc.
                                                           {
  if (!isolate->concurrent_recompilation_enabled() ||
      isolate->bootstrapper()->IsActive()) {
    mode = ConcurrencyMode::kSynchronous;
  }
  DCHECK(CodeKindIsOptimizedJSFunction(target_kind));
  DCHECK(!is_compiled(isolate) || ActiveTierIsIgnition(isolate) ||
         ActiveTierIsBaseline(isolate) || ActiveTierIsMaglev(isolate));
  DCHECK(!ActiveTierIsTurbofan(isolate));
  DCHECK(shared()->HasBytecodeArray());
  DCHECK(shared()->allows_lazy_compilation() ||
         !shared()->optimization_disabled(target_kind));
  if (IsConcurrent(mode)) {
    if (tiering_in_progress()) {
      if (v8_flags.trace_concurrent_recompilation) {
        PrintF(" ** Not marking ");
        ShortPrint(*this);
        PrintF(" -- already in optimization queue.\n");
      }
      return;
    }
    if (v8_flags.trace_concurrent_recompilation) {
      PrintF(" ** Marking ");
      ShortPrint(*this);
      PrintF(" for concurrent %s recompilation.\n",
             CodeKindToString(target_kind));
    }
  }
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
  switch (target_kind) {
    case CodeKind::MAGLEV:
      switch (mode) {
        case ConcurrencyMode::kConcurrent:
          jdt->SetTieringRequest(dispatch_handle(),
                                 TieringBuiltin::kStartMaglevOptimizeJob,
                                 isolate);
          break;
        case ConcurrencyMode::kSynchronous:
          jdt->SetTieringRequest(dispatch_handle(),
                                 TieringBuiltin::kOptimizeMaglevEager, isolate);
          break;
      }
      break;
    case CodeKind::TURBOFAN_JS:
      switch (mode) {
        case ConcurrencyMode::kConcurrent:
          jdt->SetTieringRequest(dispatch_handle(),
                                 TieringBuiltin::kStartTurbofanOptimizeJob,
                                 isolate);
          break;
        case ConcurrencyMode::kSynchronous:
          jdt->SetTieringRequest(dispatch_handle(),
                                 TieringBuiltin::kOptimizeTurbofanEager,
                                 isolate);
          break;
      }
      break;
    default:
      UNREACHABLE();
  }
#else
  set_tiering_state(isolate, TieringStateFor(target_kind, mode));
#endif // V8_ENABLE_LEAPTIERING
}
References ActiveTierIsBaseline(), ActiveTierIsIgnition(), ActiveTierIsMaglev(), ActiveTierIsTurbofan(), v8::internal::Isolate::bootstrapper(), v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::CodeKindToString(), v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::IsolateGroup::current(), v8::internal::DCHECK(), is_compiled(), v8::internal::Bootstrapper::IsActive(), v8::internal::IsConcurrent(), v8::internal::kConcurrent, v8::internal::kSynchronous, mode(), v8::internal::PrintF(), set_tiering_state(), v8::internal::ShortPrint(), tiering_in_progress(), v8::internal::anonymous_namespace{js-function.cc}::TieringStateFor(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
ResetIfCodeFlushed()
void v8::internal::JSFunction::ResetIfCodeFlushed (Isolate * isolate, std::optional< std::function< void(Tagged< HeapObject > object, ObjectSlot slot, Tagged< HeapObject > target)> , gc_notify_updated_slot = std::nullopt) [inline]
Definition at line 578 of file js-function-inl.h.
                                {
  const bool kBytecodeCanFlush =
      v8_flags.flush_bytecode || v8_flags.stress_snapshot;
  const bool kBaselineCodeCanFlush =
      v8_flags.flush_baseline_code || v8_flags.stress_snapshot;
  if (!kBytecodeCanFlush && !kBaselineCodeCanFlush) return;
  DCHECK_IMPLIES(NeedsResetDueToFlushedBytecode(isolate), kBytecodeCanFlush);
  if (kBytecodeCanFlush && NeedsResetDueToFlushedBytecode(isolate)) {
    // Bytecode was flushed and function is now uncompiled, reset JSFunction
    // by setting code to CompileLazy and clearing the feedback vector.
    ResetTieringRequests();
    UpdateCode(isolate, *BUILTIN_CODE(isolate, CompileLazy));
    raw_feedback_cell()->reset_feedback_vector(gc_notify_updated_slot);
    return;
  }
  DCHECK_IMPLIES(NeedsResetDueToFlushedBaselineCode(isolate),
                 kBaselineCodeCanFlush);
  if (kBaselineCodeCanFlush && NeedsResetDueToFlushedBaselineCode(isolate)) {
    // Flush baseline code from the closure if required
    ResetTieringRequests();
    UpdateCode(isolate, *BUILTIN_CODE(isolate, InterpreterEntryTrampoline));
  }
}
References BUILTIN_CODE, v8::internal::wasm::CompileLazy(), DCHECK_IMPLIES, NeedsResetDueToFlushedBaselineCode(), NeedsResetDueToFlushedBytecode(), v8::internal::raw_feedback_cell, ResetTieringRequests(), UpdateCode(), and v8::internal::v8_flags.
Referenced by ClearAllTypeFeedbackInfoForTesting().
ResetTieringRequests()
void v8::internal::JSFunction::ResetTieringRequests () [inline]
Definition at line 397 of file js-function-inl.h.
                                      {
#ifdef V8_ENABLE_LEAPTIERING
  IsolateGroup::current()->js_dispatch_table()->ResetTieringRequest(
      dispatch_handle());
#else
  if (has_feedback_vector() && !tiering_in_progress()) {
    feedback_vector()->reset_tiering_state();
  }
#endif // V8_ENABLE_LEAPTIERING
}
References v8::internal::IsolateGroup::current(), and tiering_in_progress().
Referenced by ResetIfCodeFlushed().
set_tiering_state()
void v8::internal::JSFunction::set_tiering_state (IsolateForSandbox isolate, TieringState state) [inline], [private]
Definition at line 438 of file js-function-inl.h.
                                                       {
  DCHECK(has_feedback_vector());
  DCHECK(IsNone(state) || ChecksTieringState(isolate));
  feedback_vector()->set_tiering_state(state);
}
References ChecksTieringState(), v8::internal::DCHECK(), and v8::internal::IsNone().
Referenced by RequestOptimization().
SetInitialMap() [1/2]
void v8::internal::JSFunction::SetInitialMap (Isolate * isolate, DirectHandle< JSFunction > function, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype) [static]
Definition at line 906 of file js-function.cc.
                                                                    {
  SetInitialMap(isolate, function, map, prototype, function);
}
References v8::internal::prototype.
Referenced by v8::internal::ApiNatives::CreateApiFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype(), EnsureHasInitialMap(), v8::internal::anonymous_namespace{js-function.cc}::FastInitializeDerivedMap(), v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype(), and v8::internal::Map::TransitionToDataProperty().
SetInitialMap() [2/2]
void v8::internal::JSFunction::SetInitialMap (Isolate * isolate, DirectHandle< JSFunction > function, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype, DirectHandle< JSFunction > constructor) [static]
Definition at line 913 of file js-function.cc.
                                                                     {
  if (map->prototype() != *prototype) {
    Map::SetPrototype(isolate, map, prototype);
  }
  map->SetConstructor(*constructor);
  function->set_prototype_or_initial_map(*map, kReleaseStore);
  if (v8_flags.log_maps) {
    LOG(isolate,
        MapEvent("InitialMap", {}, map, "",
                 SharedFunctionInfo::DebugName(
                     isolate, direct_handle(function->shared(), isolate))));
  }
}
References v8::internal::SharedFunctionInfo::DebugName(), v8::internal::direct_handle(), v8::kReleaseStore, LOG, v8::internal::prototype, v8::internal::Map::SetPrototype(), and v8::internal::v8_flags.
SetInterruptBudget()
void v8::internal::JSFunction::SetInterruptBudget (Isolate * isolate, BudgetModification kind, std::optional< CodeKind > override_active_tier = {})
Definition at line 334 of file js-function.cc.
                                                {
  int32_t current = raw_feedback_cell()->interrupt_budget();
  int32_t new_budget =
      TieringManager::InterruptBudgetFor(isolate, *this, override_active_tier);
  switch (kind) {
    case BudgetModification::kRaise:
      new_budget = std::max(current, new_budget);
      break;
    case BudgetModification::kReduce:
      new_budget = std::min(current, new_budget);
      break;
    case BudgetModification::kReset:
      break;
  }
  raw_feedback_cell()->set_interrupt_budget(new_budget);
}
References v8::internal::TieringManager::InterruptBudgetFor(), v8::internal::kRaise, v8::internal::kReduce, v8::internal::kReset, and v8::internal::raw_feedback_cell.
Referenced by SetTieringInProgress().
SetName()
bool v8::internal::JSFunction::SetName (Isolate * isolate, DirectHandle< JSFunction > function, DirectHandle< Name > name, DirectHandle< String > prefix) [static]
Definition at line 1402 of file js-function.cc.
                                                                               {
  DirectHandle<String> function_name;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, function_name,
                                   Name::ToFunctionName(isolate, name), false);
  if (prefix->length() > 0) {
    IncrementalStringBuilder builder(isolate);
    builder.AppendString(prefix);
    builder.AppendCharacter(' ');
    builder.AppendString(function_name);
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, function_name, builder.Finish(),
                                     false);
  }
  RETURN_ON_EXCEPTION_VALUE(
      isolate,
      JSObject::DefinePropertyOrElementIgnoreAttributes(
          function, isolate->factory()->name_string(), function_name,
          static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY)),
      false);
  return true;
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendString(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::JSObject::DefinePropertyOrElementIgnoreAttributes(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::name, v8::internal::READ_ONLY, RETURN_ON_EXCEPTION_VALUE, and v8::internal::Name::ToFunctionName().
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::GetMethodAndSetName(), and v8::internal::RUNTIME_FUNCTION().
SetPrototype()
void v8::internal::JSFunction::SetPrototype (Isolate * isolate, DirectHandle< JSFunction > function, DirectHandle< Object > value) [static]
Definition at line 859 of file js-function.cc.
                                                          {
  DCHECK(IsConstructor(*function) ||
         IsGeneratorFunction(function->shared()->kind()));
  DirectHandle<JSReceiver> construct_prototype;
  // If the value is not a JSReceiver, store the value in the map's
  // constructor field so it can be accessed. Also, set the prototype
  // used for constructing objects to the original object prototype.
  // See ECMA-262 13.2.2.
  if (!IsJSReceiver(*value)) {
    // Copy the map so this does not affect unrelated functions.
    // Remove map transitions because they point to maps with a
    // different prototype.
    DirectHandle<Map> new_map = Map::Copy(
        isolate, direct_handle(function->map(), isolate), "SetPrototype");
    // Create a new {constructor, non-instance_prototype} tuple and store it
    // in Map::constructor field.
    DirectHandle<Object> constructor(new_map->GetConstructor(), isolate);
    DirectHandle<Tuple2> non_instance_prototype_constructor_tuple =
        isolate->factory()->NewTuple2(constructor, value, AllocationType::kOld);
    new_map->set_has_non_instance_prototype(true);
    new_map->SetConstructor(*non_instance_prototype_constructor_tuple);
    JSObject::MigrateToMap(isolate, function, new_map);
    FunctionKind kind = function->shared()->kind();
    DirectHandle<Context> native_context(function->native_context(), isolate);
    construct_prototype = direct_handle(
        IsGeneratorFunction(kind)
            ? IsAsyncFunction(kind)
                  ? native_context->initial_async_generator_prototype()
                  : native_context->initial_generator_prototype()
            : native_context->initial_object_prototype(),
        isolate);
  } else {
    construct_prototype = Cast<JSReceiver>(value);
    function->map()->set_has_non_instance_prototype(false);
  }
  SetInstancePrototype(isolate, function, construct_prototype);
}
References v8::internal::Map::Copy(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::IsAsyncFunction(), v8::internal::IsGeneratorFunction(), v8::internal::kOld, v8::internal::JSObject::MigrateToMap(), native_context(), v8::internal::Factory::NewTuple2(), v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype(), and v8::internal::value.
Referenced by v8::internal::BUILTIN(), v8::internal::Genesis::CreateObjectFunction(), v8::internal::GetFunctionPrototype(), v8::internal::Genesis::InitializeConsole(), and v8::internal::Genesis::InitializeGlobal().
SetTieringInProgress()
void v8::internal::JSFunction::SetTieringInProgress (Isolate * isolate, bool in_progress, BytecodeOffset osr_offset = BytecodeOffset::None()) [inline]
Definition at line 408 of file js-function-inl.h.
                                                                 {
  if (!has_feedback_vector()) return;
  if (osr_offset.IsNone()) {
#ifdef V8_ENABLE_LEAPTIERING
    bool was_in_progress = tiering_in_progress();
    feedback_vector()->set_tiering_in_progress(in_progress);
    if (!in_progress && was_in_progress) {
      SetInterruptBudget(isolate, BudgetModification::kReduce);
    }
#else
    if (in_progress) {
      feedback_vector()->set_tiering_state(TieringState::kInProgress);
    } else if (tiering_in_progress()) {
      feedback_vector()->reset_tiering_state();
      SetInterruptBudget(isolate, BudgetModification::kReduce);
    }
#endif // V8_ENABLE_LEAPTIERING
  } else {
    feedback_vector()->set_osr_tiering_in_progress(in_progress);
  }
}
References v8::internal::BytecodeOffset::IsNone(), v8::internal::kReduce, SetInterruptBudget(), and tiering_in_progress().
ShouldFlushBaselineCode()
bool v8::internal::JSFunction::ShouldFlushBaselineCode (base::EnumSet< CodeFlushMode > code_flush_mode) [inline]
tiering_in_progress()
bool v8::internal::JSFunction::tiering_in_progress () const [inline]
Definition at line 264 of file js-function-inl.h.
                                           {
#ifdef V8_ENABLE_LEAPTIERING
  if (!has_feedback_vector()) return false;
  return feedback_vector()->tiering_in_progress();
#else
  return IsInProgress(tiering_state());
#endif
}
References tiering_state().
Referenced by IsTieringRequestedOrInProgress(), RequestOptimization(), ResetTieringRequests(), and SetTieringInProgress().
tiering_state()
TieringState v8::internal::JSFunction::tiering_state () const [inline]
Definition at line 433 of file js-function-inl.h.
                                             {
  if (!has_feedback_vector()) return TieringState::kNone;
  return feedback_vector()->tiering_state();
}
Referenced by GetRequestedOptimizationIfAny(), IsMaglevRequested(), IsTieringRequestedOrInProgress(), IsTurbofanRequested(), and tiering_in_progress().
ToString()
DirectHandle< String > v8::internal::JSFunction::ToString (Isolate * isolate, DirectHandle< JSFunction > function) [static]
Definition at line 1438 of file js-function.cc.
                                                                             {
  DirectHandle<SharedFunctionInfo> shared_info(function->shared(), isolate);
  // Check if {function} should hide its source code.
  if (!shared_info->IsUserJavaScript()) {
    return NativeCodeFunctionSourceString(isolate, shared_info);
  }
  if (IsClassConstructor(shared_info->kind())) {
    // Check if we should print {function} as a class.
    DirectHandle<Object> maybe_class_positions = JSReceiver::GetDataProperty(
        isolate, function, isolate->factory()->class_positions_symbol());
    if (IsClassPositions(*maybe_class_positions)) {
      Tagged<ClassPositions> class_positions =
          Cast<ClassPositions>(*maybe_class_positions);
      int start_position = class_positions->start();
      int end_position = class_positions->end();
      Handle<String> script_source(
          Cast<String>(Cast<Script>(shared_info->script())->source()), isolate);
      return isolate->factory()->NewSubString(script_source, start_position,
                                              end_position);
    }
  }
  // Check if we have source code for the {function}.
  if (!shared_info->HasSourceCode()) {
    return NativeCodeFunctionSourceString(isolate, shared_info);
  }
  // If this function was compiled from asm.js, use the recorded offset
  // information.
#if V8_ENABLE_WEBASSEMBLY
  if (shared_info->HasWasmExportedFunctionData(isolate)) {
    DirectHandle<WasmExportedFunctionData> function_data(
        shared_info->wasm_exported_function_data(), isolate);
    const wasm::WasmModule* module = function_data->instance_data()->module();
    if (is_asmjs_module(module)) {
      std::pair<int, int> offsets =
          module->asm_js_offset_information->GetFunctionOffsets(
              declared_function_index(module, function_data->function_index()));
      Handle<String> source(
          Cast<String>(Cast<Script>(shared_info->script())->source()), isolate);
      return isolate->factory()->NewSubString(source, offsets.first,
                                              offsets.second);
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (shared_info->function_token_position() == kNoSourcePosition) {
    // If the function token position isn't valid, return [native code] to
    // ensure calling eval on the returned source code throws rather than
    // giving inconsistent call behaviour.
    isolate->CountUsage(
        v8::Isolate::UseCounterFeature::kFunctionTokenOffsetTooLongForToString);
    return NativeCodeFunctionSourceString(isolate, shared_info);
  }
  return Cast<String>(
      SharedFunctionInfo::GetSourceCodeHarmony(isolate, shared_info));
}
References v8::internal::wasm::WasmModule::asm_js_offset_information, v8::internal::Isolate::CountUsage(), v8::internal::wasm::declared_function_index(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::SharedFunctionInfo::GetSourceCodeHarmony(), v8::internal::wasm::is_asmjs_module(), v8::internal::IsClassConstructor(), v8::internal::kNoSourcePosition, and v8::internal::anonymous_namespace{js-function.cc}::NativeCodeFunctionSourceString().
Referenced by v8::internal::BUILTIN(), v8::debug::GetFunctionDescription(), and v8::internal::Object::NoSideEffectsToMaybeString().
UpdateCode()
void v8::internal::JSFunction::UpdateCode (Isolate * isolate, Tagged< Code > code, WriteBarrierMode mode = WriteBarrierMode::UPDATE_WRITE_BARRIER) [inline]
Definition at line 130 of file js-function-inl.h.
                                                   {
  // Optimized code must go through UpdateOptimized code, which sets a
  // back-reference in the code object to the dispatch handle for
  // deoptimization.
  CHECK(!code->is_optimized_code());
  UpdateCodeImpl(isolate, code, mode, false);
}
References CHECK, code, mode(), and UpdateCodeImpl().
Referenced by ResetIfCodeFlushed().
UpdateCodeImpl()
void v8::internal::JSFunction::UpdateCodeImpl (Isolate * isolate, Tagged< Code > code, WriteBarrierMode mode, bool keep_tiering_request) [inline], [private]
Definition at line 98 of file js-function-inl.h.
                                                           {
  DisallowGarbageCollection no_gc;
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchHandle handle = dispatch_handle();
  if (handle == kNullJSDispatchHandle) {
    handle = raw_feedback_cell()->dispatch_handle();
    DCHECK_NE(handle, kNullJSDispatchHandle);
    set_dispatch_handle(handle, mode);
  }
  if (keep_tiering_request) {
    UpdateDispatchEntryKeepTieringRequest(value, mode);
  } else {
    UpdateDispatchEntry(value, mode);
  }
  if (V8_UNLIKELY(v8_flags.log_function_events)) {
    IsolateGroup::current()->js_dispatch_table()->SetTieringRequest(
        dispatch_handle(), TieringBuiltin::kFunctionLogNextExecution, isolate);
  }
#else
  WriteCodePointerField(kCodeOffset, value);
  CONDITIONAL_CODE_POINTER_WRITE_BARRIER(*this, kCodeOffset, value, mode);
  if (V8_UNLIKELY(v8_flags.log_function_events && has_feedback_vector())) {
    feedback_vector()->set_log_next_execution(true);
  }
#endif // V8_ENABLE_LEAPTIERING
}
References CONDITIONAL_CODE_POINTER_WRITE_BARRIER, v8::internal::IsolateGroup::current(), DCHECK_NE, v8::internal::handle(), v8::internal::kNullJSDispatchHandle(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::raw_feedback_cell, UpdateDispatchEntry(), UpdateDispatchEntryKeepTieringRequest(), v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::value.
Referenced by UpdateCode(), UpdateCodeKeepTieringRequests(), and UpdateOptimizedCode().
UpdateCodeKeepTieringRequests()
void v8::internal::JSFunction::UpdateCodeKeepTieringRequests (Isolate * isolate, Tagged< Code > code, WriteBarrierMode mode = WriteBarrierMode::UPDATE_WRITE_BARRIER) [inline]
Definition at line 139 of file js-function-inl.h.
                                                                             {
  CHECK(!code->is_optimized_code());
  UpdateCodeImpl(isolate, code, mode, true);
}
References CHECK, code, mode(), and UpdateCodeImpl().
UpdateDispatchEntry()
void v8::internal::JSFunction::UpdateDispatchEntry (Tagged< Code > new_code, WriteBarrierMode mode = WriteBarrierMode::UPDATE_WRITE_BARRIER) [inline], [private]
Referenced by UpdateCodeImpl().
UpdateDispatchEntryKeepTieringRequest()
void v8::internal::JSFunction::UpdateDispatchEntryKeepTieringRequest (Tagged< Code > new_code, WriteBarrierMode mode = WriteBarrierMode::UPDATE_WRITE_BARRIER) [inline], [private]
Referenced by UpdateCodeImpl().
UpdateOptimizedCode()
void v8::internal::JSFunction::UpdateOptimizedCode (Isolate * isolate, Tagged< Code > code, WriteBarrierMode mode = WriteBarrierMode::UPDATE_WRITE_BARRIER) [inline]
Definition at line 80 of file js-function-inl.h.
                                                            {
  DisallowGarbageCollection no_gc;
  DCHECK(code->is_optimized_code());
#ifdef V8_ENABLE_LEAPTIERING
  if (code->is_context_specialized()) {
    // We can only set context-specialized code for single-closure cells.
    if (raw_feedback_cell()->map() !=
        ReadOnlyRoots(isolate).one_closure_cell_map()) {
      return;
    }
  }
  // Required for being able to deoptimize this code.
  code->set_js_dispatch_handle(dispatch_handle());
#endif // V8_ENABLE_LEAPTIERING
  UpdateCodeImpl(isolate, code, mode, false);
}
References code, v8::internal::DCHECK(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::raw_feedback_cell, and UpdateCodeImpl().
Member Data Documentation
kHeaderSize
const int v8::internal::JSFunction::kHeaderSize [static], [private]
Definition at line 449 of file js-function.h.
kMinDescriptorsForFastBindAndWrap
const int v8::internal::JSFunction::kMinDescriptorsForFastBindAndWrap = 2 [static]
Definition at line 110 of file js-function.h.
Referenced by v8::internal::TF_BUILTIN(), and v8::internal::anonymous_namespace{js-function.cc}::UseFastFunctionNameLookup().
kSizeWithoutPrototype
constexpr int v8::internal::JSFunction::kSizeWithoutPrototype = kPrototypeOrInitialMapOffset [static], [constexpr]
Definition at line 482 of file js-function.h.
Referenced by v8::internal::CodeStubAssembler::AllocateRootFunctionWithContext(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Factory::CreateStrictFunctionMap(), GetHeaderSize(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), and v8::internal::TF_BUILTIN().
kSizeWithPrototype
constexpr int v8::internal::JSFunction::kSizeWithPrototype = TorqueGeneratedClass::kHeaderSize [static], [constexpr]
Definition at line 483 of file js-function.h.
Referenced by v8::internal::Factory::CreateClassFunctionMap(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Factory::CreateStrictFunctionMap(), GetHeaderSize(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-function.h
/mnt/V8SourceCode/src/objects/js-function-inl.h
/mnt/V8SourceCode/src/objects/js-function.cc