v8::internal::V8FileLogger Class Reference
#include <log.h>
Public Member Functions
V8FileLogger (Isolate *isolate)
~V8FileLogger () override
bool SetUp (Isolate *isolate)
void LateSetup (Isolate *isolate)
V8_EXPORT_PRIVATE FILE * TearDownAndGetLogFile ()
void SetCodeEventHandler (uint32_t options, JitCodeEventHandler event_handler)
sampler::Sampler * sampler ()
V8_EXPORT_PRIVATE std::string file_name () const
V8_EXPORT_PRIVATE void StopProfilerThread ()
V8_EXPORT_PRIVATE void StringEvent (const char *name, const char *value)
void IntPtrTEvent (const char *name, intptr_t value)
void NewEvent (const char *name, void *object, size_t size)
void DeleteEvent (const char *name, void *object)
void FunctionEvent (const char *reason, int script_id, double time_delta_ms, int start_position, int end_position, Tagged< String > function_name)
void FunctionEvent (const char *reason, int script_id, double time_delta_ms, int start_position, int end_position, const char *function_name=nullptr, size_t function_name_length=0, bool is_one_byte=true)
void CompilationCacheEvent (const char *action, const char *cache_type, Tagged< SharedFunctionInfo > sfi)
void ScriptEvent (ScriptEventType type, int script_id)
void ScriptDetails (Tagged< Script > script)
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char *name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name, int line, int column) override
void CallbackEvent (DirectHandle< Name > name, Address entry_point) override
void GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) override
void CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) override
void BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) override
void SharedFunctionInfoMoveEvent (Address from, Address to) override
void NativeContextMoveEvent (Address from, Address to) override
void CodeMovingGCEvent () override
void CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) override
void CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) override
void CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > sfi, const char *reason) override
void FeedbackVectorEvent (Tagged< FeedbackVector > vector, Tagged< AbstractCode > code)
void WeakCodeClearEvent () override
void ProcessDeoptEvent (DirectHandle< Code > code, SourcePosition position, const char *kind, const char *reason)
void CodeLinePosInfoRecordEvent (Address code_start, Tagged< TrustedByteArray > source_position_table, JitCodeEvent::CodeType code_type)
void CodeNameEvent (Address addr, int pos, const char *code_name)
void ICEvent (const char *type, bool keyed, DirectHandle< Map > map, DirectHandle< Object > key, char old_state, char new_state, const char *modifier, const char *slow_stub_reason)
void MapEvent (const char *type, DirectHandle< Map > from, DirectHandle< Map > to, const char *reason=nullptr, DirectHandle< HeapObject > name_or_sfi=DirectHandle< HeapObject >())
void MapCreate (Tagged< Map > map)
void MapDetails (Tagged< Map > map)
void MapMoveEvent (Tagged< Map > from, Tagged< Map > to)
void SharedLibraryEvent (const std::string &library_path, uintptr_t start, uintptr_t end, intptr_t aslr_slide)
void SharedLibraryEnd ()
void CurrentTimeEvent ()
V8_EXPORT_PRIVATE void TimerEvent (v8::LogEventStatus se, const char *name)
V8_EXPORT_PRIVATE bool is_logging ()
bool is_listening_to_code_events () override
bool allows_code_compaction () override
void LogExistingFunction (DirectHandle< SharedFunctionInfo > shared, DirectHandle< AbstractCode > code)
V8_EXPORT_PRIVATE void LogCompiledFunctions (bool ensure_source_positions_available=true)
V8_EXPORT_PRIVATE void LogAccessorCallbacks ()
V8_EXPORT_PRIVATE void LogCodeObjects ()
V8_EXPORT_PRIVATE void LogBuiltins ()
void LogAllMaps ()
Static Public Member Functions
static void EnterExternal (Isolate *isolate)
static void LeaveExternal (Isolate *isolate)
V8_NOINLINE static V8_PRESERVE_MOST void CallEventLoggerInternal (Isolate *isolate, const char *name, v8::LogEventStatus se, bool expose_to_api)
static void CallEventLogger (Isolate *isolate, const char *name, v8::LogEventStatus se, bool expose_to_api)
static CodeTag ToNativeByScript (CodeTag tag, Tagged< Script > script)
Static Public Attributes
static const LogSeparator kNext = LogSeparator::kSeparator
Private Member Functions
Logger * logger () const
void UpdateIsLogging (bool value)
void ProfilerBeginEvent ()
void CallbackEventInternal (const char *prefix, DirectHandle< Name > name, Address entry_point)
void MoveEventInternal (Event event, Address from, Address to)
void InitNameBuffer (Event tag)
void TickEvent (TickSample *sample, bool overflow)
void RuntimeCallTimerEvent ()
void UncheckedStringEvent (const char *name, const char *value)
bool EnsureLogScriptSource (Tagged< Script > script)
void LogSourceCodeInformation (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared)
void LogCodeDisassemble (DirectHandle< AbstractCode > code)
void WriteApiSecurityCheck ()
void WriteApiNamedPropertyAccess (const char *tag, Tagged< JSObject > holder, Tagged< Object > name)
void WriteApiIndexedPropertyAccess (const char *tag, Tagged< JSObject > holder, uint32_t index)
void WriteApiObjectAccess (const char *tag, Tagged< JSReceiver > obj)
void WriteApiEntryCall (const char *name)
int64_t Time ()
Private Attributes
Isolate * isolate_
std::unique_ptr< Ticker > ticker_
std::unique_ptr< Profiler > profiler_
std::atomic< bool > is_logging_
std::unique_ptr< LogFile > log_file_
std::unique_ptr< LowLevelLogger > ll_logger_
std::unique_ptr< JitLogger > jit_logger_
std::set< int > logged_source_code_
uint32_t next_source_info_id_ = 0
bool is_initialized_
ExistingCodeLogger existing_code_logger_
base::ElapsedTimer timer_
Friends
class Profiler
Additional Inherited Members
Detailed Description
Definition at line 116 of file log.h.
Constructor & Destructor Documentation
V8FileLogger()
v8::internal::V8FileLogger::V8FileLogger (Isolate * isolate) [explicit]
Definition at line 1226 of file log.cc.
    : isolate_(isolate),
      is_logging_(false),
      is_initialized_(false),
      existing_code_logger_(isolate) {}
 V8FileLogger()
v8::internal::V8FileLogger::~V8FileLogger () [override], [default]
Member Function Documentation
allows_code_compaction()
bool v8::internal::V8FileLogger::allows_code_compaction () [inline], [override], [virtual]
Reimplemented from v8::internal::LogEventListener.
Definition at line 280 of file log.h.
                                         {
#if defined(V8_ENABLE_ETW_STACK_WALKING)
    return etw_jit_logger_ == nullptr;
#else // V8_ENABLE_ETW_STACK_WALKING
    return true;
#endif // V8_ENABLE_ETW_STACK_WALKING
  }
BytecodeMoveEvent()
void v8::internal::V8FileLogger::BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1679 of file log.cc.
                                                               {
  if (!is_listening_to_code_events()) return;
  MoveEventInternal(Event::kCodeMove, from->GetFirstBytecodeAddress(),
                    to->GetFirstBytecodeAddress());
}
References is_listening_to_code_events(), and MoveEventInternal().
CallbackEvent()
void v8::internal::V8FileLogger::CallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1645 of file log.cc.
                                                                             {
  CallbackEventInternal("", name, entry_point);
}
References CallbackEventInternal(), and v8::internal::name.
CallbackEventInternal()
void v8::internal::V8FileLogger::CallbackEventInternal (const char * prefix, DirectHandle< Name > name, Address entry_point) [private]
Definition at line 1633 of file log.cc.
                                                              {
  if (!v8_flags.log_code) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << Event::kCodeCreation << kNext << CodeTag::kCallback << kNext << -2
      << kNext << Time() << kNext << reinterpret_cast<void*>(entry_point)
      << kNext << 1 << kNext << prefix << *name;
  msg.WriteToLogFile();
}
References isolate_, kNext, MSG_BUILDER, v8::internal::name, and v8::internal::v8_flags.
Referenced by CallbackEvent(), GetterCallbackEvent(), and SetterCallbackEvent().
CallEventLogger()
static void v8::internal::V8FileLogger::CallEventLogger (Isolate * isolate, const char * name, v8::LogEventStatus se, bool expose_to_api) [inline], [static]
Definition at line 262 of file log.h.
                                                            {
    if (V8_UNLIKELY(v8_flags.log_timer_events)) {
      CallEventLoggerInternal(isolate, name, se, expose_to_api);
    }
  }
References CallEventLoggerInternal(), v8::internal::name, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::BaseTimedHistogramScope::LogEnd(), v8::internal::BaseTimedHistogramScope::LogStart(), v8::internal::TimerEventScope< TimerEvent >::LogTimerEvent(), and v8::internal::TimedHistogram::RecordAbandon().
CallEventLoggerInternal()
V8_NOINLINE static V8_PRESERVE_MOST void v8::internal::V8FileLogger::CallEventLoggerInternal (Isolate * isolate, const char * name, v8::LogEventStatus se, bool expose_to_api) [inline], [static]
Definition at line 253 of file log.h.
                          {
    LOG(isolate, TimerEvent(se, name));
    if (V8_UNLIKELY(isolate->event_logger())) {
      isolate->event_logger()(name, se);
    }
  }
References LOG, v8::internal::name, TimerEvent(), and V8_UNLIKELY.
Referenced by CallEventLogger().
CodeCreateEvent() [1/4]
void v8::internal::V8FileLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char * name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1499 of file log.cc.
                                                     {
  if (!is_listening_to_code_events()) return;
  if (!v8_flags.log_code) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  {
    MSG_BUILDER();
    AppendCodeCreateHeader(isolate_, msg, tag, *code, Time());
    msg << name;
    msg.WriteToLogFile();
  }
  LogCodeDisassemble(code);
}
References v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader(), code, is_listening_to_code_events(), isolate_, LogCodeDisassemble(), MSG_BUILDER, v8::internal::name, Time(), and v8::internal::v8_flags.
CodeCreateEvent() [2/4]
void v8::internal::V8FileLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1513 of file log.cc.
                                                            {
  if (!is_listening_to_code_events()) return;
  if (!v8_flags.log_code) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  {
    MSG_BUILDER();
    AppendCodeCreateHeader(isolate_, msg, tag, *code, Time());
    msg << *name;
    msg.WriteToLogFile();
  }
  LogCodeDisassemble(code);
}
References v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader(), code, is_listening_to_code_events(), isolate_, LogCodeDisassemble(), MSG_BUILDER, v8::internal::name, Time(), and v8::internal::v8_flags.
CodeCreateEvent() [3/4]
void v8::internal::V8FileLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1528 of file log.cc.
                                                                   {
  if (!is_listening_to_code_events()) return;
  if (!v8_flags.log_code) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  if (*code ==
      Cast<AbstractCode>(isolate_->builtins()->code(Builtin::kCompileLazy))) {
    return;
  }
  {
    MSG_BUILDER();
    AppendCodeCreateHeader(isolate_, msg, tag, *code, Time());
    msg << *script_name << kNext << reinterpret_cast<void*>(shared->address())
        << kNext << ComputeMarker(*shared, *code);
    msg.WriteToLogFile();
  }
  LogSourceCodeInformation(code, shared);
  LogCodeDisassemble(code);
}
References v8::internal::DirectHandle< T >::address(), v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader(), v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), code, v8::internal::anonymous_namespace{log.cc}::ComputeMarker(), is_listening_to_code_events(), isolate_, kNext, LogCodeDisassemble(), LogSourceCodeInformation(), MSG_BUILDER, Time(), and v8::internal::v8_flags.
CodeCreateEvent() [4/4]
void v8::internal::V8FileLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name, int line, int column) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1582 of file log.cc.
                                               {
  if (!is_listening_to_code_events()) return;
  if (!v8_flags.log_code) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  {
    MSG_BUILDER();
    AppendCodeCreateHeader(isolate_, msg, tag, *code, Time());
    msg << shared->DebugNameCStr().get() << " " << *script_name << ":" << line
        << ":" << column << kNext << reinterpret_cast<void*>(shared->address())
        << kNext << ComputeMarker(*shared, *code);
    msg.WriteToLogFile();
  }
  LogSourceCodeInformation(code, shared);
  LogCodeDisassemble(code);
}
References v8::internal::DirectHandle< T >::address(), v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader(), code, v8::internal::anonymous_namespace{log.cc}::ComputeMarker(), is_listening_to_code_events(), isolate_, kNext, LogCodeDisassemble(), LogSourceCodeInformation(), MSG_BUILDER, Time(), and v8::internal::v8_flags.
CodeDeoptEvent()
void v8::internal::V8FileLogger::CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1733 of file log.cc.
                                                                  {
  if (!is_logging() || !v8_flags.log_deopt) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  Deoptimizer::DeoptInfo info = Deoptimizer::GetDeoptInfo(*code, pc);
  ProcessDeoptEvent(code, info.position, Deoptimizer::MessageFor(kind),
                    DeoptimizeReasonToString(info.deopt_reason));
}
References code, v8::internal::Deoptimizer::DeoptInfo::deopt_reason, v8::internal::DeoptimizeReasonToString(), v8::internal::Deoptimizer::GetDeoptInfo(), is_logging(), isolate_, v8::internal::Deoptimizer::MessageFor(), v8::internal::Deoptimizer::DeoptInfo::position, ProcessDeoptEvent(), and v8::internal::v8_flags.
CodeDependencyChangeEvent()
void v8::internal::V8FileLogger::CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > sfi, const char * reason) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1742 of file log.cc.
                        {
  if (!is_logging() || !v8_flags.log_deopt) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  SourcePosition position(sfi->StartPosition(), -1);
  ProcessDeoptEvent(code, position, "dependency-change", reason);
}
References code, is_logging(), isolate_, ProcessDeoptEvent(), and v8::internal::v8_flags.
CodeDisableOptEvent()
void v8::internal::V8FileLogger::CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1697 of file log.cc.
                                                                              {
  if (!is_listening_to_code_events()) return;
  if (!v8_flags.log_code) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << Event::kCodeDisableOpt << kNext << shared->DebugNameCStr().get()
      << kNext << GetBailoutReason(shared->disabled_optimization_reason());
  msg.WriteToLogFile();
}
References v8::internal::GetBailoutReason(), is_listening_to_code_events(), isolate_, kNext, MSG_BUILDER, and v8::internal::v8_flags.
CodeLinePosInfoRecordEvent()
void v8::internal::V8FileLogger::CodeLinePosInfoRecordEvent (Address code_start, Tagged< TrustedByteArray > source_position_table, JitCodeEvent::CodeType code_type)
Definition at line 1773 of file log.cc.
                                    {
  if (!jit_logger_) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  SourcePositionTableIterator iter(source_position_table);
  CodeLinePosEvent(*jit_logger_, code_start, iter, code_type);
}
References v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent(), isolate_, and jit_logger_.
Referenced by v8::internal::LocalLogger::CodeLinePosInfoRecordEvent().
CodeMoveEvent()
void v8::internal::V8FileLogger::CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1672 of file log.cc.
                                                               {
  if (!is_listening_to_code_events()) return;
  MoveEventInternal(Event::kCodeMove, from->instruction_start(),
                    to->instruction_start());
}
References is_listening_to_code_events(), and MoveEventInternal().
CodeMovingGCEvent()
void v8::internal::V8FileLogger::CodeMovingGCEvent () [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1691 of file log.cc.
                                     {
  if (!is_listening_to_code_events()) return;
  if (!v8_flags.ll_prof) return;
  base::OS::SignalCodeMovingGC();
}
References is_listening_to_code_events(), v8::base::OS::SignalCodeMovingGC(), and v8::internal::v8_flags.
CodeNameEvent()
void v8::internal::V8FileLogger::CodeNameEvent (Address addr, int pos, const char * code_name)
Definition at line 1792 of file log.cc.
                                                                             {
  if (code_name == nullptr) return; // Not a code object.
  if (!is_listening_to_code_events()) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << Event::kSnapshotCodeName << kNext << pos << kNext << code_name;
  msg.WriteToLogFile();
}
References is_listening_to_code_events(), isolate_, kNext, and MSG_BUILDER.
CompilationCacheEvent()
void v8::internal::V8FileLogger::CompilationCacheEvent (const char * action, const char * cache_type, Tagged< SharedFunctionInfo > sfi)
Definition at line 1855 of file log.cc.
                                                                         {
  if (!v8_flags.log_function_events) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  int script_id = -1;
  if (IsScript(sfi->script())) {
    script_id = Cast<Script>(sfi->script())->id();
  }
  msg << "compilation-cache" << V8FileLogger::kNext << action
      << V8FileLogger::kNext << cache_type << V8FileLogger::kNext << script_id
      << V8FileLogger::kNext << sfi->StartPosition() << V8FileLogger::kNext
      << sfi->EndPosition() << V8FileLogger::kNext << Time();
  msg.WriteToLogFile();
}
References isolate_, kNext, MSG_BUILDER, Time(), and v8::internal::v8_flags.
CurrentTimeEvent()
void v8::internal::V8FileLogger::CurrentTimeEvent ()
Definition at line 1306 of file log.cc.
                                    {
  VMStateIfMainThread<LOGGING> state(isolate_);
  DCHECK(v8_flags.log_timer_events);
  MSG_BUILDER();
  msg << "current-time" << kNext << Time();
  msg.WriteToLogFile();
}
References v8::internal::DCHECK(), isolate_, kNext, MSG_BUILDER, Time(), and v8::internal::v8_flags.
DeleteEvent()
void v8::internal::V8FileLogger::DeleteEvent (const char * name, void * object)
Definition at line 1354 of file log.cc.
                                                             {
  if (!v8_flags.log) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << "delete" << kNext << name << kNext << object;
  msg.WriteToLogFile();
}
References isolate_, kNext, MSG_BUILDER, v8::internal::name, and v8::internal::v8_flags.
EnsureLogScriptSource()
bool v8::internal::V8FileLogger::EnsureLogScriptSource (Tagged< Script > script) [private]
Definition at line 1921 of file log.cc.
                                                              {
  if (!v8_flags.log_source_code) return true;
  VMStateIfMainThread<LOGGING> state(isolate_);
  // Make sure the script is written to the log file.
  int script_id = script->id();
  if (logged_source_code_.find(script_id) != logged_source_code_.end()) {
    return true;
  }
  // This script has not been logged yet.
  logged_source_code_.insert(script_id);
  Tagged<Object> source_object = script->source();
  if (!IsString(source_object)) return false;
  std::unique_ptr<LogFile::MessageBuilder> msg_ptr =
      log_file_->NewMessageBuilder();
  if (!msg_ptr) return false;
  LogFile::MessageBuilder& msg = *msg_ptr.get();
  Tagged<String> source_code = Cast<String>(source_object);
  msg << "script-source" << kNext << script_id << kNext;
  // Log the script name.
  if (IsString(script->name())) {
    msg << Cast<String>(script->name()) << kNext;
  } else {
    msg << "<unknown>" << kNext;
  }
  // Log the source code.
  msg << source_code;
  msg.WriteToLogFile();
  return true;
}
References isolate_, kNext, log_file_, logged_source_code_, v8::internal::script, v8::internal::v8_flags, and v8::internal::LogFile::MessageBuilder::WriteToLogFile().
Referenced by LogSourceCodeInformation(), and ScriptDetails().
EnterExternal()
static void v8::internal::V8FileLogger::EnterExternal (Isolate * isolate) [static]
FeedbackVectorEvent()
void v8::internal::V8FileLogger::FeedbackVectorEvent (Tagged< FeedbackVector > vector, Tagged< AbstractCode > code)
Definition at line 1549 of file log.cc.
                                                                  {
  DisallowGarbageCollection no_gc;
  if (!v8_flags.log_feedback_vector) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  PtrComprCageBase cage_base(isolate_);
  MSG_BUILDER();
  msg << "feedback-vector" << kNext << Time();
  msg << kNext << reinterpret_cast<void*>(vector.address()) << kNext
      << vector->length();
  msg << kNext << reinterpret_cast<void*>(code->InstructionStart(cage_base));
#ifndef V8_ENABLE_LEAPTIERING
  msg << kNext << vector->tiering_state();
  msg << kNext << vector->maybe_has_maglev_code();
  msg << kNext << vector->maybe_has_turbofan_code();
#endif // !V8_ENABLE_LEAPTIERING
  msg << kNext << vector->invocation_count();
#ifdef OBJECT_PRINT
  std::ostringstream buffer;
  vector->FeedbackVectorPrint(buffer);
  std::string contents = buffer.str();
  msg.AppendString(contents.c_str(), contents.length());
#else
  msg << "object-printing-disabled";
#endif
  msg.WriteToLogFile();
}
References v8::internal::Tagged< HeapObject >::address(), code, isolate_, kNext, MSG_BUILDER, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::string, Time(), and v8::internal::v8_flags.
file_name()
std::string v8::internal::V8FileLogger::file_name () const
Definition at line 2445 of file log.cc.
                                        {
  return log_file_.get()->file_name();
}
References log_file_.
Referenced by v8::Shell::LogGetAndStop().
FunctionEvent() [1/2]
void v8::internal::V8FileLogger::FunctionEvent (const char * reason, int script_id, double time_delta_ms, int start_position, int end_position, const char * function_name = nullptr, size_t function_name_length = 0, bool is_one_byte = true)
Definition at line 1839 of file log.cc.
                                                   {
  if (!v8_flags.log_function_events) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  AppendFunctionMessage(msg, reason, script_id, time_delta, start_position,
                        end_position, Time());
  if (function_name_length > 0) {
    msg.AppendString(function_name, function_name_length, is_one_byte);
  }
  msg.WriteToLogFile();
}
References v8::internal::anonymous_namespace{log.cc}::AppendFunctionMessage(), isolate_, MSG_BUILDER, Time(), and v8::internal::v8_flags.
FunctionEvent() [2/2]
void v8::internal::V8FileLogger::FunctionEvent (const char * reason, int script_id, double time_delta_ms, int start_position, int end_position, Tagged< String > function_name)
Definition at line 1826 of file log.cc.
                                                               {
  if (!v8_flags.log_function_events) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  AppendFunctionMessage(msg, reason, script_id, time_delta, start_position,
                        end_position, Time());
  if (!function_name.is_null()) msg << function_name;
  msg.WriteToLogFile();
}
References v8::internal::anonymous_namespace{log.cc}::AppendFunctionMessage(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, MSG_BUILDER, Time(), and v8::internal::v8_flags.
Referenced by v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), and v8::internal::PreParser::ParseFunctionLiteral().
GetterCallbackEvent()
void v8::internal::V8FileLogger::GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1649 of file log.cc.
                                                            {
  CallbackEventInternal("get ", name, entry_point);
}
References CallbackEventInternal(), and v8::internal::name.
Referenced by LogAccessorCallbacks().
ICEvent()
void v8::internal::V8FileLogger::ICEvent (const char * type, bool keyed, DirectHandle< Map > map, DirectHandle< Object > key, char old_state, char new_state, const char * modifier, const char * slow_stub_reason)
Definition at line 1991 of file log.cc.
                                                         {
  if (!v8_flags.log_ic) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  int line;
  int column;
  // GetAbstractPC must come before MSG_BUILDER(), as it can GC, which might
  // attempt to get the log lock again and result in a deadlock.
  Address pc = isolate_->GetAbstractPC(&line, &column);
  MSG_BUILDER();
  if (keyed) msg << "Keyed";
  msg << type << kNext << reinterpret_cast<void*>(pc) << kNext << Time()
      << kNext << line << kNext << column << kNext << old_state << kNext
      << new_state << kNext
      << AsHex::Address(map.is_null() ? kNullAddress : map->ptr()) << kNext;
  if (IsSmi(*key)) {
    msg << Smi::ToInt(*key);
  } else if (IsNumber(*key)) {
    msg << Object::NumberValue(*key);
  } else if (IsName(*key)) {
    msg << Cast<Name>(*key);
  }
  msg << kNext << modifier << kNext;
  if (slow_stub_reason != nullptr) {
    msg << slow_stub_reason;
  }
  msg.WriteToLogFile();
}
References v8::internal::AsHex::Address(), v8::internal::Isolate::GetAbstractPC(), v8::internal::DirectHandle< T >::is_null(), v8::internal::IsNumber(), isolate_, v8::internal::IsSmi(), v8::internal::key, kNext, v8::internal::kNullAddress, MSG_BUILDER, v8::internal::Object::NumberValue(), Time(), v8::internal::Smi::ToInt(), and v8::internal::v8_flags.
InitNameBuffer()
void v8::internal::V8FileLogger::InitNameBuffer (Event tag) [private]
IntPtrTEvent()
void v8::internal::V8FileLogger::IntPtrTEvent (const char * name, intptr_t value)
Definition at line 1277 of file log.cc.
                                                                {
  if (!v8_flags.log) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << name << kNext;
  msg.AppendFormatString("%" V8PRIdPTR, value);
  msg.WriteToLogFile();
}
References isolate_, kNext, MSG_BUILDER, v8::internal::name, v8::internal::v8_flags, V8PRIdPTR, and v8::internal::value.
is_listening_to_code_events()
bool v8::internal::V8FileLogger::is_listening_to_code_events () [inline], [override], [virtual]
Reimplemented from v8::internal::LogEventListener.
Definition at line 272 of file log.h.
                                              {
    return
#if defined(V8_ENABLE_ETW_STACK_WALKING)
        etw_jit_logger_ != nullptr ||
#endif // V8_ENABLE_ETW_STACK_WALKING
        is_logging() || jit_logger_ != nullptr;
  }
References is_logging(), and jit_logger_.
Referenced by BytecodeMoveEvent(), CodeCreateEvent(), CodeDisableOptEvent(), CodeMoveEvent(), CodeMovingGCEvent(), CodeNameEvent(), v8::internal::Isolate::IsLoggingCodeCreation(), RegExpCodeCreateEvent(), and SharedFunctionInfoMoveEvent().
is_logging()
bool v8::internal::V8FileLogger::is_logging ()
Definition at line 1332 of file log.cc.
                              {
  // Disable logging while the CPU profiler is running.
  if (isolate_->is_profiling()) return false;
  return is_logging_.load(std::memory_order_relaxed);
}
References is_logging_, v8::internal::Isolate::is_profiling(), and isolate_.
Referenced by CodeDeoptEvent(), CodeDependencyChangeEvent(), is_listening_to_code_events(), v8::Shell::LogGetAndStop(), v8::internal::Isolate::NeedsSourcePositions(), v8::internal::LogFile::NewMessageBuilder(), SetUp(), and v8::internal::Isolate::UpdateLogObjectRelocation().
LateSetup()
void v8::internal::V8FileLogger::LateSetup (Isolate * isolate)
Definition at line 2362 of file log.cc.
                                             {
  if (!isolate->logger()->is_listening_to_code_events()) return;
  Builtins::EmitCodeCreateEvents(isolate);
#if V8_ENABLE_WEBASSEMBLY
  wasm::GetWasmEngine()->EnableCodeLogging(isolate);
#endif
}
References v8::internal::Builtins::EmitCodeCreateEvents(), v8::internal::wasm::WasmEngine::EnableCodeLogging(), v8::internal::wasm::GetWasmEngine(), v8::internal::Logger::is_listening_to_code_events(), and v8::internal::Isolate::logger().
Referenced by v8::internal::Isolate::Init().
LeaveExternal()
static void v8::internal::V8FileLogger::LeaveExternal (Isolate * isolate) [static]
LogAccessorCallbacks()
void v8::internal::V8FileLogger::LogAccessorCallbacks ()
Definition at line 2217 of file log.cc.
                                        {
  Heap* heap = isolate_->heap();
  HeapObjectIterator iterator(heap);
  DisallowGarbageCollection no_gc;
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    if (!IsAccessorInfo(obj)) continue;
    Tagged<AccessorInfo> ai = Cast<AccessorInfo>(obj);
    if (!IsName(ai->name())) continue;
    Address getter_entry = ai->getter(isolate_);
    HandleScope scope(isolate_);
    DirectHandle<Name> name(Cast<Name>(ai->name()), isolate_);
    if (getter_entry != kNullAddress) {
#if USES_FUNCTION_DESCRIPTORS
      getter_entry = *FUNCTION_ENTRYPOINT_ADDRESS(getter_entry);
#endif
      PROFILE(isolate_, GetterCallbackEvent(name, getter_entry));
    }
    Address setter_entry = ai->setter(isolate_);
    if (setter_entry != kNullAddress) {
#if USES_FUNCTION_DESCRIPTORS
      setter_entry = *FUNCTION_ENTRYPOINT_ADDRESS(setter_entry);
#endif
      PROFILE(isolate_, SetterCallbackEvent(name, setter_entry));
    }
  }
}
References GetterCallbackEvent(), v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, v8::internal::kNullAddress, v8::internal::name, v8::internal::HeapObjectIterator::Next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, PROFILE, and SetterCallbackEvent().
Referenced by v8::internal::ProfilingScope::ProfilingScope().
LogAllMaps()
void v8::internal::V8FileLogger::LogAllMaps ()
Definition at line 2245 of file log.cc.
                              {
  Heap* heap = isolate_->heap();
  CombinedHeapObjectIterator iterator(heap);
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    if (!IsMap(obj)) continue;
    Tagged<Map> map = Cast<Map>(obj);
    MapCreate(map);
    MapDetails(map);
  }
}
References v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, MapCreate(), MapDetails(), and v8::internal::CombinedHeapObjectIterator::Next().
LogBuiltins()
void v8::internal::V8FileLogger::LogBuiltins ()
Definition at line 2215 of file log.cc.
{ existing_code_logger_.LogBuiltins(); }
References existing_code_logger_, and v8::internal::ExistingCodeLogger::LogBuiltins().
Referenced by SetCodeEventHandler().
LogCodeDisassemble()
void v8::internal::V8FileLogger::LogCodeDisassemble (DirectHandle< AbstractCode > code) [private]
Definition at line 1474 of file log.cc.
                                                                     {
  if (!v8_flags.log_code_disassemble) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  PtrComprCageBase cage_base(isolate_);
  MSG_BUILDER();
  msg << "code-disassemble" << V8FileLogger::kNext
      << reinterpret_cast<void*>(code->InstructionStart(cage_base))
      << V8FileLogger::kNext << CodeKindToString(code->kind(cage_base))
      << V8FileLogger::kNext;
  {
    std::ostringstream stream;
    if (IsCode(*code, cage_base)) {
#ifdef ENABLE_DISASSEMBLER
      Cast<Code>(*code)->Disassemble(nullptr, stream, isolate_);
#endif
    } else {
      Cast<BytecodeArray>(*code)->Disassemble(stream);
    }
    std::string string = stream.str();
    msg.AppendString(string.c_str(), string.length());
  }
  msg.WriteToLogFile();
}
References code, v8::internal::CodeKindToString(), isolate_, kNext, v8::internal::length, MSG_BUILDER, v8::internal::string, and v8::internal::v8_flags.
Referenced by CodeCreateEvent().
LogCodeObjects()
void v8::internal::V8FileLogger::LogCodeObjects ()
Definition at line 2203 of file log.cc.
{ existing_code_logger_.LogCodeObjects(); }
References existing_code_logger_, and v8::internal::ExistingCodeLogger::LogCodeObjects().
Referenced by v8::internal::ProfilingScope::ProfilingScope(), and SetCodeEventHandler().
LogCompiledFunctions()
void v8::internal::V8FileLogger::LogCompiledFunctions (bool ensure_source_positions_available = true)
Definition at line 2210 of file log.cc.
                                            {
  existing_code_logger_.LogCompiledFunctions(ensure_source_positions_available);
}
References existing_code_logger_, and v8::internal::ExistingCodeLogger::LogCompiledFunctions().
Referenced by v8::internal::ProfilingScope::ProfilingScope(), and SetCodeEventHandler().
LogExistingFunction()
void v8::internal::V8FileLogger::LogExistingFunction (DirectHandle< SharedFunctionInfo > shared, DirectHandle< AbstractCode > code)
Definition at line 2205 of file log.cc.
                                                                        {
  existing_code_logger_.LogExistingFunction(shared, code);
}
References code, existing_code_logger_, and v8::internal::ExistingCodeLogger::LogExistingFunction().
logger()
Logger * v8::internal::V8FileLogger::logger () const [private]
Definition at line 2493 of file log.cc.
{ return isolate_->logger(); }
References isolate_, and v8::internal::Isolate::logger().
Referenced by SetCodeEventHandler(), SetUp(), and TearDownAndGetLogFile().
LogSourceCodeInformation()
void v8::internal::V8FileLogger::LogSourceCodeInformation (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) [private]
Definition at line 1406 of file log.cc.
                                                                              {
  PtrComprCageBase cage_base(isolate_);
  Tagged<Object> script_object = shared->script(cage_base);
  if (!IsScript(script_object, cage_base)) return;
  Tagged<Script> script = Cast<Script>(script_object);
  EnsureLogScriptSource(script);
  if (!v8_flags.log_source_position) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << "code-source-info" << V8FileLogger::kNext
      << reinterpret_cast<void*>(code->InstructionStart(cage_base))
      << V8FileLogger::kNext << script->id() << V8FileLogger::kNext
      << shared->StartPosition() << V8FileLogger::kNext << shared->EndPosition()
      << V8FileLogger::kNext;
  // TODO(v8:11429): Clean-up baseline-replated code in source position
  // iteration.
  bool hasInlined = false;
  if (code->kind(cage_base) != CodeKind::BASELINE) {
    SourcePositionTableIterator iterator(
        code->SourcePositionTable(isolate_, *shared));
    for (; !iterator.done(); iterator.Advance()) {
      SourcePosition pos = iterator.source_position();
      msg << "C" << iterator.code_offset() << "O" << pos.ScriptOffset();
      if (pos.isInlined()) {
        msg << "I" << pos.InliningId();
        hasInlined = true;
      }
    }
  }
  msg << V8FileLogger::kNext;
  int maxInlinedId = -1;
  if (hasInlined) {
    Tagged<TrustedPodArray<InliningPosition>> inlining_positions =
        Cast<DeoptimizationData>(Cast<Code>(code)->deoptimization_data())
            ->InliningPositions();
    for (int i = 0; i < inlining_positions->length(); i++) {
      InliningPosition inlining_pos = inlining_positions->get(i);
      msg << "F";
      if (inlining_pos.inlined_function_id != -1) {
        msg << inlining_pos.inlined_function_id;
        if (inlining_pos.inlined_function_id > maxInlinedId) {
          maxInlinedId = inlining_pos.inlined_function_id;
        }
      }
      SourcePosition pos = inlining_pos.position;
      msg << "O" << pos.ScriptOffset();
      if (pos.isInlined()) {
        msg << "I" << pos.InliningId();
      }
    }
  }
  msg << V8FileLogger::kNext;
  if (hasInlined) {
    Tagged<DeoptimizationData> deopt_data =
        Cast<DeoptimizationData>(Cast<Code>(code)->deoptimization_data());
    msg << std::hex;
    for (int i = 0; i <= maxInlinedId; i++) {
      msg << "S"
          << reinterpret_cast<void*>(
                 deopt_data->GetInlinedFunction(i).address());
    }
    msg << std::dec;
  }
  msg.WriteToLogFile();
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::SourcePositionTableIterator::Advance(), code, v8::internal::SourcePositionTableIterator::code_offset(), v8::internal::SourcePositionTableIterator::done(), EnsureLogScriptSource(), v8::internal::InliningPosition::inlined_function_id, v8::internal::SourcePosition::InliningId(), v8::internal::SourcePosition::isInlined(), isolate_, kNext, MSG_BUILDER, v8::internal::InliningPosition::position, v8::internal::script, v8::internal::SourcePosition::ScriptOffset(), v8::internal::SourcePositionTableIterator::source_position(), and v8::internal::v8_flags.
Referenced by CodeCreateEvent().
MapCreate()
void v8::internal::V8FileLogger::MapCreate (Tagged< Map > map)
Definition at line 2054 of file log.cc.
                                            {
  if (!v8_flags.log_maps) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  DisallowGarbageCollection no_gc;
  MSG_BUILDER();
  msg << "map-create" << kNext << Time() << kNext << AsHex::Address(map.ptr());
  msg.WriteToLogFile();
}
References v8::internal::AsHex::Address(), isolate_, kNext, MSG_BUILDER, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), Time(), and v8::internal::v8_flags.
Referenced by LogAllMaps(), and v8::internal::LocalLogger::MapCreate().
MapDetails()
void v8::internal::V8FileLogger::MapDetails (Tagged< Map > map)
Definition at line 2063 of file log.cc.
                                             {
  if (!v8_flags.log_maps) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  DisallowGarbageCollection no_gc;
  MSG_BUILDER();
  msg << "map-details" << kNext << Time() << kNext << AsHex::Address(map.ptr())
      << kNext;
  if (v8_flags.log_maps_details) {
    std::ostringstream buffer;
    map->PrintMapDetails(buffer);
    msg << buffer.str().c_str();
  }
  msg.WriteToLogFile();
}
References v8::internal::AsHex::Address(), isolate_, kNext, MSG_BUILDER, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), Time(), and v8::internal::v8_flags.
Referenced by LogAllMaps(), v8::internal::LocalLogger::MapDetails(), and MapEvent().
MapEvent()
void v8::internal::V8FileLogger::MapEvent (const char * type, DirectHandle< Map > from, DirectHandle< Map > to, const char * reason = nullptr, DirectHandle< HeapObject > name_or_sfi = DirectHandle<HeapObject>())
Definition at line 2022 of file log.cc.
                                                                  {
  if (!v8_flags.log_maps) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  if (!to.is_null()) MapDetails(*to);
  int line = -1;
  int column = -1;
  Address pc = 0;
  if (!isolate_->bootstrapper()->IsActive()) {
    pc = isolate_->GetAbstractPC(&line, &column);
  }
  MSG_BUILDER();
  msg << "map" << kNext << type << kNext << Time() << kNext
      << AsHex::Address(from.is_null() ? kNullAddress : from->ptr()) << kNext
      << AsHex::Address(to.is_null() ? kNullAddress : to->ptr()) << kNext
      << AsHex::Address(pc) << kNext << line << kNext << column << kNext
      << reason << kNext;
  if (!name_or_sfi.is_null()) {
    if (IsName(*name_or_sfi)) {
      msg << Cast<Name>(*name_or_sfi);
    } else if (IsSharedFunctionInfo(*name_or_sfi)) {
      Tagged<SharedFunctionInfo> sfi = Cast<SharedFunctionInfo>(*name_or_sfi);
      msg << sfi->DebugNameCStr().get();
      msg << " " << sfi->unique_id();
    }
  }
  msg.WriteToLogFile();
}
References v8::internal::AsHex::Address(), v8::internal::Isolate::bootstrapper(), v8::internal::Isolate::GetAbstractPC(), v8::internal::DirectHandle< T >::is_null(), v8::internal::Bootstrapper::IsActive(), isolate_, kNext, v8::internal::kNullAddress, MapDetails(), MSG_BUILDER, Time(), v8::internal::tracing::type, and v8::internal::v8_flags.
MapMoveEvent()
void v8::internal::V8FileLogger::MapMoveEvent (Tagged< Map > from, Tagged< Map > to)
Definition at line 2078 of file log.cc.
                                                                {
  if (!v8_flags.log_maps) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  DisallowGarbageCollection no_gc;
  MSG_BUILDER();
  msg << "map-move" << kNext << Time() << kNext << AsHex::Address(from.ptr())
      << kNext << AsHex::Address(to.ptr());
  msg.WriteToLogFile();
}
References v8::internal::AsHex::Address(), isolate_, kNext, MSG_BUILDER, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), Time(), and v8::internal::v8_flags.
MoveEventInternal()
void v8::internal::V8FileLogger::MoveEventInternal (Event event, Address from, Address to) [private]
Definition at line 1801 of file log.cc.
                                                                          {
  if (!v8_flags.log_code) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << event << kNext << reinterpret_cast<void*>(from) << kNext
      << reinterpret_cast<void*>(to);
  msg.WriteToLogFile();
}
References isolate_, kNext, MSG_BUILDER, and v8::internal::v8_flags.
Referenced by BytecodeMoveEvent(), CodeMoveEvent(), and SharedFunctionInfoMoveEvent().
NativeContextMoveEvent()
void v8::internal::V8FileLogger::NativeContextMoveEvent (Address from, Address to) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 203 of file log.h.
{}
NewEvent()
void v8::internal::V8FileLogger::NewEvent (const char * name, void * object, size_t size)
Definition at line 1345 of file log.cc.
                                                                       {
  if (!v8_flags.log) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << "new" << kNext << name << kNext << object << kNext
      << static_cast<unsigned int>(size);
  msg.WriteToLogFile();
}
References isolate_, kNext, MSG_BUILDER, v8::internal::name, size(), and v8::internal::v8_flags.
ProcessDeoptEvent()
void v8::internal::V8FileLogger::ProcessDeoptEvent (DirectHandle< Code > code, SourcePosition position, const char * kind, const char * reason)
Definition at line 1708 of file log.cc.
                                                         {
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << Event::kCodeDeopt << kNext << Time() << kNext
      << code->InstructionStreamObjectSize() << kNext
      << reinterpret_cast<void*>(code->instruction_start());
  std::ostringstream deopt_location;
  int inlining_id = -1;
  int script_offset = -1;
  if (position.IsKnown()) {
    position.Print(deopt_location, *code);
    inlining_id = position.InliningId();
    script_offset = position.ScriptOffset();
  } else {
    deopt_location << "<unknown>";
  }
  msg << kNext << inlining_id << kNext << script_offset << kNext;
  msg << kind << kNext;
  msg << deopt_location.str().c_str() << kNext << reason;
  msg.WriteToLogFile();
}
References code, v8::internal::SourcePosition::InliningId(), v8::internal::SourcePosition::IsKnown(), isolate_, kNext, MSG_BUILDER, v8::internal::SourcePosition::Print(), v8::internal::SourcePosition::ScriptOffset(), and Time().
Referenced by CodeDeoptEvent(), and CodeDependencyChangeEvent().
ProfilerBeginEvent()
void v8::internal::V8FileLogger::ProfilerBeginEvent () [private]
Definition at line 1258 of file log.cc.
                                      {
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << "profiler" << kNext << "begin" << kNext
      << v8_flags.prof_sampling_interval;
  msg.WriteToLogFile();
}
References isolate_, kNext, MSG_BUILDER, and v8::internal::v8_flags.
RegExpCodeCreateEvent()
void v8::internal::V8FileLogger::RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1659 of file log.cc.
                                                            {
  if (!is_listening_to_code_events()) return;
  if (!v8_flags.log_code) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  AppendCodeCreateHeader(isolate_, msg, LogEventListener::CodeTag::kRegExp,
                         *code, Time());
  msg << *source;
  msg.WriteToLogFile();
}
References v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader(), code, is_listening_to_code_events(), isolate_, MSG_BUILDER, Time(), and v8::internal::v8_flags.
RuntimeCallTimerEvent()
void v8::internal::V8FileLogger::RuntimeCallTimerEvent () [private]
Definition at line 1955 of file log.cc.
                                         {
#ifdef V8_RUNTIME_CALL_STATS
  VMStateIfMainThread<LOGGING> state(isolate_);
  RuntimeCallStats* stats = isolate_->counters()->runtime_call_stats();
  RuntimeCallCounter* counter = stats->current_counter();
  if (counter == nullptr) return;
  MSG_BUILDER();
  msg << "active-runtime-timer" << kNext << counter->name();
  msg.WriteToLogFile();
#endif // V8_RUNTIME_CALL_STATS
}
References v8::internal::Isolate::counters(), isolate_, kNext, MSG_BUILDER, and v8::internal::Counters::runtime_call_stats().
Referenced by TickEvent().
sampler()
sampler::Sampler * v8::internal::V8FileLogger::sampler ()
Definition at line 2444 of file log.cc.
{ return ticker_.get(); }
References ticker_.
Referenced by v8::internal::Isolate::Deinit().
ScriptDetails()
void v8::internal::V8FileLogger::ScriptDetails (Tagged< Script > script)
Definition at line 1901 of file log.cc.
                                                      {
  if (!v8_flags.log_function_events) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  {
    MSG_BUILDER();
    msg << "script-details" << V8FileLogger::kNext << script->id()
        << V8FileLogger::kNext;
    if (IsString(script->name())) {
      msg << Cast<String>(script->name());
    }
    msg << V8FileLogger::kNext << script->line_offset() << V8FileLogger::kNext
        << script->column_offset() << V8FileLogger::kNext;
    if (IsString(script->source_mapping_url())) {
      msg << Cast<String>(script->source_mapping_url());
    }
    msg.WriteToLogFile();
  }
  EnsureLogScriptSource(script);
}
References EnsureLogScriptSource(), isolate_, kNext, MSG_BUILDER, v8::internal::script, and v8::internal::v8_flags.
Referenced by v8::internal::LocalLogger::ScriptDetails().
ScriptEvent()
void v8::internal::V8FileLogger::ScriptEvent (ScriptEventType type, int script_id)
Definition at line 1872 of file log.cc.
                                                                  {
  if (!v8_flags.log_function_events) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << "script" << V8FileLogger::kNext;
  switch (type) {
    case ScriptEventType::kReserveId:
      msg << "reserve-id";
      break;
    case ScriptEventType::kCreate:
      msg << "create";
      break;
    case ScriptEventType::kDeserialize:
      msg << "deserialize";
      break;
    case ScriptEventType::kBackgroundCompile:
      msg << "background-compile";
      break;
    case ScriptEventType::kStreamingCompileBackground:
      msg << "streaming-compile";
      break;
    case ScriptEventType::kStreamingCompileForeground:
      msg << "streaming-compile-foreground";
      break;
  }
  msg << V8FileLogger::kNext << script_id << V8FileLogger::kNext << Time();
  msg.WriteToLogFile();
}
References isolate_, v8::internal::kBackgroundCompile, v8::internal::kCreate, v8::internal::kDeserialize, kNext, v8::internal::kReserveId, v8::internal::kStreamingCompileBackground, v8::internal::kStreamingCompileForeground, MSG_BUILDER, Time(), v8::internal::tracing::type, and v8::internal::v8_flags.
Referenced by v8::internal::LocalLogger::ScriptEvent().
SetCodeEventHandler()
void v8::internal::V8FileLogger::SetCodeEventHandler (uint32_t options, JitCodeEventHandler event_handler)
Definition at line 2420 of file log.cc.
                                                                          {
  if (jit_logger_) {
    CHECK(logger()->RemoveListener(jit_logger_.get()));
    jit_logger_.reset();
    isolate_->UpdateLogObjectRelocation();
  }
  if (event_handler) {
#if V8_ENABLE_WEBASSEMBLY
    wasm::GetWasmEngine()->EnableCodeLogging(isolate_);
#endif // V8_ENABLE_WEBASSEMBLY
    jit_logger_ = std::make_unique<JitLogger>(isolate_, event_handler);
    isolate_->UpdateLogObjectRelocation();
    CHECK(logger()->AddListener(jit_logger_.get()));
    if (options & kJitCodeEventEnumExisting) {
      HandleScope scope(isolate_);
      LogBuiltins();
      LogCodeObjects();
      LogCompiledFunctions();
    }
  }
}
References CHECK, v8::internal::wasm::WasmEngine::EnableCodeLogging(), v8::internal::wasm::GetWasmEngine(), isolate_, jit_logger_, v8::kJitCodeEventEnumExisting, LogBuiltins(), LogCodeObjects(), LogCompiledFunctions(), logger(), and v8::internal::Isolate::UpdateLogObjectRelocation().
Referenced by v8::Isolate::SetJitCodeEventHandler().
SetterCallbackEvent()
void v8::internal::V8FileLogger::SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1654 of file log.cc.
                                                            {
  CallbackEventInternal("set ", name, entry_point);
}
References CallbackEventInternal(), and v8::internal::name.
Referenced by LogAccessorCallbacks().
SetUp()
bool v8::internal::V8FileLogger::SetUp (Isolate * isolate)
Definition at line 2305 of file log.cc.
                                         {
  // Tests and EnsureInitialize() can call this twice in a row. It's harmless.
  if (is_initialized_) return true;
  is_initialized_ = true;
  std::ostringstream log_file_name;
  PrepareLogFileName(log_file_name, isolate, v8_flags.logfile);
  log_file_ = std::make_unique<LogFile>(this, log_file_name.str());
#if V8_OS_LINUX || V8_OS_DARWIN
  if (v8_flags.perf_basic_prof) {
    perf_basic_logger_ = std::make_unique<PerfBasicLogger>(isolate);
    CHECK(logger()->AddListener(perf_basic_logger_.get()));
  }
  if (v8_flags.perf_prof) {
    perf_jit_logger_ = std::make_unique<PerfJitLogger>(isolate);
    CHECK(logger()->AddListener(perf_jit_logger_.get()));
  }
#else
  static_assert(
      !v8_flags.perf_prof.value(),
      "--perf-prof should be statically disabled on non-Linux platforms");
  static_assert(
      !v8_flags.perf_basic_prof.value(),
      "--perf-basic-prof should be statically disabled on non-Linux platforms");
#endif
#ifdef ENABLE_GDB_JIT_INTERFACE
  if (v8_flags.gdbjit) {
    gdb_jit_logger_ =
        std::make_unique<JitLogger>(isolate, i::GDBJITInterface::EventHandler);
    CHECK(logger()->AddListener(gdb_jit_logger_.get()));
    CHECK(isolate->logger()->is_listening_to_code_events());
  }
#endif // ENABLE_GDB_JIT_INTERFACE
  if (v8_flags.ll_prof) {
    ll_logger_ =
        std::make_unique<LowLevelLogger>(isolate, log_file_name.str().c_str());
    CHECK(logger()->AddListener(ll_logger_.get()));
  }
  ticker_ = std::make_unique<Ticker>(isolate, v8_flags.prof_sampling_interval);
  if (v8_flags.log) UpdateIsLogging(true);
  timer_.Start();
  if (v8_flags.prof_cpp) {
    CHECK(v8_flags.log);
    CHECK(is_logging());
    profiler_ = std::make_unique<Profiler>(isolate);
    profiler_->Engage();
  }
  if (is_logging_) {
    CHECK(logger()->AddListener(this));
  }
  return true;
}
References CHECK, v8::internal::ETWJITInterface::EventHandler(), is_initialized_, v8::internal::Logger::is_listening_to_code_events(), is_logging(), is_logging_, ll_logger_, log_file_, v8::internal::Isolate::logger(), logger(), v8::internal::PrepareLogFileName(), profiler_, v8::base::ElapsedTimer::Start(), ticker_, timer_, UpdateIsLogging(), and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Init().
SharedFunctionInfoMoveEvent()
void v8::internal::V8FileLogger::SharedFunctionInfoMoveEvent (Address from, Address to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 1686 of file log.cc.
                                                                       {
  if (!is_listening_to_code_events()) return;
  MoveEventInternal(Event::kSharedFuncMove, from, to);
}
References is_listening_to_code_events(), and MoveEventInternal().
SharedLibraryEnd()
void v8::internal::V8FileLogger::SharedLibraryEnd ()
Definition at line 1298 of file log.cc.
                                    {
  if (!v8_flags.prof_cpp) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << "shared-library-end";
  msg.WriteToLogFile();
}
References isolate_, MSG_BUILDER, and v8::internal::v8_flags.
SharedLibraryEvent()
void v8::internal::V8FileLogger::SharedLibraryEvent (const std::string & library_path, uintptr_t start, uintptr_t end, intptr_t aslr_slide)
Definition at line 1286 of file log.cc.
                                                           {
  if (!v8_flags.prof_cpp) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << "shared-library" << kNext << library_path.c_str() << kNext
      << reinterpret_cast<void*>(start) << kNext << reinterpret_cast<void*>(end)
      << kNext << aslr_slide;
  msg.WriteToLogFile();
}
References v8::internal::compiler::end(), isolate_, kNext, MSG_BUILDER, and v8::internal::v8_flags.
StopProfilerThread()
void v8::internal::V8FileLogger::StopProfilerThread ()
Definition at line 2449 of file log.cc.
                                      {
  if (profiler_ != nullptr) {
    profiler_->Disengage();
    profiler_.reset();
  }
}
References profiler_.
Referenced by v8::internal::Isolate::Deinit(), and TearDownAndGetLogFile().
StringEvent()
void v8::internal::V8FileLogger::StringEvent (const char * name, const char * value)
Definition at line 1266 of file log.cc.
                                                                  {
  if (v8_flags.log) UncheckedStringEvent(name, value);
}
References v8::internal::name, UncheckedStringEvent(), v8::internal::v8_flags, and v8::internal::value.
TearDownAndGetLogFile()
FILE * v8::internal::V8FileLogger::TearDownAndGetLogFile ()
Definition at line 2456 of file log.cc.
                                          {
  if (!is_initialized_) return nullptr;
  is_initialized_ = false;
  UpdateIsLogging(false);
  // Stop the profiler thread before closing the file.
  StopProfilerThread();
  ticker_.reset();
  timer_.Stop();
#if V8_OS_LINUX || V8_OS_DARWIN
  if (perf_basic_logger_) {
    CHECK(logger()->RemoveListener(perf_basic_logger_.get()));
    perf_basic_logger_.reset();
  }
  if (perf_jit_logger_) {
    CHECK(logger()->RemoveListener(perf_jit_logger_.get()));
    perf_jit_logger_.reset();
  }
#endif
  if (ll_logger_) {
    CHECK(logger()->RemoveListener(ll_logger_.get()));
    ll_logger_.reset();
  }
  if (jit_logger_) {
    CHECK(logger()->RemoveListener(jit_logger_.get()));
    jit_logger_.reset();
    isolate_->UpdateLogObjectRelocation();
  }
  return log_file_->Close();
}
References CHECK, is_initialized_, isolate_, jit_logger_, ll_logger_, log_file_, logger(), v8::base::ElapsedTimer::Stop(), StopProfilerThread(), ticker_, timer_, UpdateIsLogging(), and v8::internal::Isolate::UpdateLogObjectRelocation().
Referenced by v8::internal::Isolate::Deinit(), and v8::Shell::LogGetAndStop().
TickEvent()
void v8::internal::V8FileLogger::TickEvent (TickSample * sample, bool overflow) [private]
Definition at line 1967 of file log.cc.
                                                              {
  if (!v8_flags.prof_cpp) return;
  VMStateIfMainThread<LOGGING> state(isolate_);
  if (V8_UNLIKELY(TracingFlags::runtime_stats.load(std::memory_order_relaxed) ==
                  v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE)) {
    RuntimeCallTimerEvent();
  }
  MSG_BUILDER();
  msg << Event::kTick << kNext << reinterpret_cast<void*>(sample->pc) << kNext
      << Time();
  if (sample->has_external_callback) {
    msg << kNext << 1 << kNext
        << reinterpret_cast<void*>(sample->external_callback_entry);
  } else {
    msg << kNext << 0 << kNext << reinterpret_cast<void*>(sample->tos);
  }
  msg << kNext << static_cast<int>(sample->state);
  if (overflow) msg << kNext << "overflow";
  for (unsigned i = 0; i < sample->frames_count; ++i) {
    msg << kNext << reinterpret_cast<void*>(sample->stack[i]);
  }
  msg.WriteToLogFile();
}
References v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE, v8::internal::TickSample::external_callback_entry, v8::internal::TickSample::frames_count, v8::internal::TickSample::has_external_callback, v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, kNext, MSG_BUILDER, v8::internal::overflow, v8::internal::TickSample::pc, v8::internal::TracingFlags::runtime_stats, RuntimeCallTimerEvent(), v8::internal::TickSample::stack, v8::internal::TickSample::state, Time(), v8::internal::TickSample::tos, v8::internal::v8_flags, and V8_UNLIKELY.
Time()
int64_t v8::internal::V8FileLogger::Time () [private]
Definition at line 1236 of file log.cc.
                           {
  if (v8_flags.verify_predictable) {
    return isolate_->heap()->MonotonicallyIncreasingTimeInMs() * 1000;
  }
  return timer_.Elapsed().InMicroseconds();
}
References v8::base::ElapsedTimer::Elapsed(), v8::internal::Isolate::heap(), v8::base::TimeDelta::InMicroseconds(), isolate_, v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), timer_, and v8::internal::v8_flags.
Referenced by CodeCreateEvent(), CompilationCacheEvent(), CurrentTimeEvent(), FeedbackVectorEvent(), FunctionEvent(), ICEvent(), MapCreate(), MapDetails(), MapEvent(), MapMoveEvent(), ProcessDeoptEvent(), RegExpCodeCreateEvent(), ScriptEvent(), TickEvent(), and TimerEvent().
TimerEvent()
void v8::internal::V8FileLogger::TimerEvent (v8::LogEventStatus se, const char * name)
Definition at line 1314 of file log.cc.
                                                                   {
  VMStateIfMainThread<LOGGING> state(isolate_);
  DCHECK(v8_flags.log_timer_events);
  MSG_BUILDER();
  switch (se) {
    case kStart:
      msg << "timer-event-start";
      break;
    case kEnd:
      msg << "timer-event-end";
      break;
    case kLog:
      msg << "timer-event";
  }
  msg << kNext << name << kNext << Time();
  msg.WriteToLogFile();
}
References v8::internal::DCHECK(), isolate_, v8::kLog, kNext, v8::kStart, MSG_BUILDER, v8::internal::name, Time(), and v8::internal::v8_flags.
Referenced by CallEventLoggerInternal().
ToNativeByScript()
LogEventListener::CodeTag v8::internal::V8FileLogger::ToNativeByScript (LogEventListener::CodeTag tag, Tagged< Script > script) [inline], [static]
Definition at line 18 of file log-inl.h.
                                                        {
  if (script->type() != Script::Type::kNative) return tag;
  switch (tag) {
    case LogEventListener::CodeTag::kFunction:
      return LogEventListener::CodeTag::kNativeFunction;
    case LogEventListener::CodeTag::kScript:
      return LogEventListener::CodeTag::kNativeScript;
    default:
      return tag;
  }
}
References v8::internal::torque::ls::kFunction, v8::internal::Script::kNative, and v8::internal::script.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), v8::internal::ExistingCodeLogger::LogExistingFunction(), and v8::internal::Compiler::LogFunctionCompilation().
UncheckedStringEvent()
void v8::internal::V8FileLogger::UncheckedStringEvent (const char * name, const char * value) [private]
Definition at line 1270 of file log.cc.
                                                                           {
  VMStateIfMainThread<LOGGING> state(isolate_);
  MSG_BUILDER();
  msg << name << kNext << value;
  msg.WriteToLogFile();
}
References isolate_, kNext, MSG_BUILDER, v8::internal::name, and v8::internal::value.
Referenced by StringEvent().
UpdateIsLogging()
void v8::internal::V8FileLogger::UpdateIsLogging (bool value) [private]
Definition at line 2495 of file log.cc.
                                             {
  if (value) {
    isolate_->CollectSourcePositionsForAllBytecodeArrays();
  }
  {
    base::MutexGuard guard(log_file_->mutex());
    // Relaxed atomic to avoid locking the mutex for the most common case: when
    // logging is disabled.
    is_logging_.store(value, std::memory_order_relaxed);
  }
  isolate_->UpdateLogObjectRelocation();
}
References v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays(), is_logging_, isolate_, log_file_, v8::internal::Isolate::UpdateLogObjectRelocation(), and v8::internal::value.
Referenced by SetUp(), and TearDownAndGetLogFile().
WeakCodeClearEvent()
void v8::internal::V8FileLogger::WeakCodeClearEvent () [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 214 of file log.h.
{}
WriteApiEntryCall()
void v8::internal::V8FileLogger::WriteApiEntryCall (const char * name) [private]
WriteApiIndexedPropertyAccess()
void v8::internal::V8FileLogger::WriteApiIndexedPropertyAccess (const char * tag, Tagged< JSObject > holder, uint32_t index) [private]
WriteApiNamedPropertyAccess()
void v8::internal::V8FileLogger::WriteApiNamedPropertyAccess (const char * tag, Tagged< JSObject > holder, Tagged< Object > name) [private]
WriteApiObjectAccess()
void v8::internal::V8FileLogger::WriteApiObjectAccess (const char * tag, Tagged< JSReceiver > obj) [private]
WriteApiSecurityCheck()
void v8::internal::V8FileLogger::WriteApiSecurityCheck () [private]
Friends And Related Function Documentation
Profiler
friend class Profiler [friend]
Definition at line 362 of file log.h.
Member Data Documentation
existing_code_logger_
ExistingCodeLogger v8::internal::V8FileLogger::existing_code_logger_ [private]
Definition at line 385 of file log.h.
Referenced by LogBuiltins(), LogCodeObjects(), LogCompiledFunctions(), and LogExistingFunction().
is_initialized_
bool v8::internal::V8FileLogger::is_initialized_ [private]
Definition at line 383 of file log.h.
Referenced by SetUp(), and TearDownAndGetLogFile().
is_logging_
std::atomic<bool> v8::internal::V8FileLogger::is_logging_ [private]
Definition at line 364 of file log.h.
Referenced by is_logging(), SetUp(), and UpdateIsLogging().
isolate_
Isolate* v8::internal::V8FileLogger::isolate_ [private]
Definition at line 351 of file log.h.
Referenced by CallbackEventInternal(), CodeCreateEvent(), CodeDeoptEvent(), CodeDependencyChangeEvent(), CodeDisableOptEvent(), CodeLinePosInfoRecordEvent(), CodeNameEvent(), CompilationCacheEvent(), CurrentTimeEvent(), DeleteEvent(), EnsureLogScriptSource(), FeedbackVectorEvent(), FunctionEvent(), ICEvent(), IntPtrTEvent(), is_logging(), LogAccessorCallbacks(), LogAllMaps(), LogCodeDisassemble(), logger(), LogSourceCodeInformation(), MapCreate(), MapDetails(), MapEvent(), MapMoveEvent(), MoveEventInternal(), NewEvent(), ProcessDeoptEvent(), ProfilerBeginEvent(), RegExpCodeCreateEvent(), RuntimeCallTimerEvent(), ScriptDetails(), ScriptEvent(), SetCodeEventHandler(), SharedLibraryEnd(), SharedLibraryEvent(), TearDownAndGetLogFile(), TickEvent(), Time(), TimerEvent(), UncheckedStringEvent(), and UpdateIsLogging().
jit_logger_
std::unique_ptr<JitLogger> v8::internal::V8FileLogger::jit_logger_ [private]
Definition at line 371 of file log.h.
Referenced by CodeLinePosInfoRecordEvent(), is_listening_to_code_events(), SetCodeEventHandler(), and TearDownAndGetLogFile().
kNext
const LogSeparator v8::internal::V8FileLogger::kNext = LogSeparator::kSeparator [static]
Definition at line 122 of file log.h.
Referenced by v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader(), v8::internal::anonymous_namespace{log.cc}::AppendFunctionMessage(), CallbackEventInternal(), CodeCreateEvent(), CodeDisableOptEvent(), CodeNameEvent(), CompilationCacheEvent(), CurrentTimeEvent(), DeleteEvent(), EnsureLogScriptSource(), FeedbackVectorEvent(), ICEvent(), IntPtrTEvent(), LogCodeDisassemble(), LogSourceCodeInformation(), MapCreate(), MapDetails(), MapEvent(), MapMoveEvent(), MoveEventInternal(), NewEvent(), ProcessDeoptEvent(), ProfilerBeginEvent(), RuntimeCallTimerEvent(), ScriptDetails(), ScriptEvent(), SharedLibraryEvent(), TickEvent(), TimerEvent(), and UncheckedStringEvent().
ll_logger_
std::unique_ptr<LowLevelLogger> v8::internal::V8FileLogger::ll_logger_ [private]
Definition at line 370 of file log.h.
Referenced by SetUp(), and TearDownAndGetLogFile().
log_file_
std::unique_ptr<LogFile> v8::internal::V8FileLogger::log_file_ [private]
Definition at line 365 of file log.h.
Referenced by EnsureLogScriptSource(), file_name(), SetUp(), TearDownAndGetLogFile(), and UpdateIsLogging().
logged_source_code_
std::set<int> v8::internal::V8FileLogger::logged_source_code_ [private]
Definition at line 378 of file log.h.
Referenced by EnsureLogScriptSource().
next_source_info_id_
uint32_t v8::internal::V8FileLogger::next_source_info_id_ = 0 [private]
Definition at line 379 of file log.h.
profiler_
std::unique_ptr<Profiler> v8::internal::V8FileLogger::profiler_ [private]
Definition at line 359 of file log.h.
Referenced by SetUp(), and StopProfilerThread().
ticker_
std::unique_ptr<Ticker> v8::internal::V8FileLogger::ticker_ [private]
Definition at line 354 of file log.h.
Referenced by v8::internal::Profiler::Disengage(), v8::internal::Profiler::Engage(), sampler(), SetUp(), and TearDownAndGetLogFile().
timer_
base::ElapsedTimer v8::internal::V8FileLogger::timer_ [private]
Definition at line 387 of file log.h.
Referenced by SetUp(), TearDownAndGetLogFile(), and Time().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/log.h
/mnt/V8SourceCode/src/logging/log-inl.h
/mnt/V8SourceCode/src/logging/log.cc