v8::internal::PagedSpaceAllocatorPolicy Class Reference
#include <main-allocator.h>
Public Member Functions
PagedSpaceAllocatorPolicy (PagedSpaceBase *space, MainAllocator *allocator)
bool EnsureAllocation (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) final
void FreeLinearAllocationArea () final
Private Member Functions
bool RefillLab (int size_in_bytes, AllocationOrigin origin)
bool ContributeToSweeping (uint32_t max_pages=std::numeric_limits< uint32_t >::max())
bool TryAllocationFromFreeList (size_t size_in_bytes, AllocationOrigin origin)
bool TryExpandAndAllocate (size_t size_in_bytes, AllocationOrigin origin)
V8_WARN_UNUSED_RESULT bool TryExtendLAB (int size_in_bytes)
void SetLinearAllocationArea (Address top, Address limit, Address end)
void FreeLinearAllocationAreaUnsynchronized ()
Private Attributes
PagedSpaceBase *const space_
Friends
class PagedNewSpaceAllocatorPolicy
Additional Inherited Members
Detailed Description
Definition at line 70 of file main-allocator.h.
Constructor & Destructor Documentation
PagedSpaceAllocatorPolicy()
v8::internal::PagedSpaceAllocatorPolicy::PagedSpaceAllocatorPolicy (PagedSpaceBase * space, MainAllocator * allocator) [inline]
Definition at line 72 of file main-allocator.h.
      : AllocatorPolicy(allocator), space_(space) {}
Member Function Documentation
ContributeToSweeping()
bool v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping (uint32_t max_pages = std::numeric_limits<uint32_t>::max()) [private]
Definition at line 777 of file main-allocator.cc.
                                                                       {
  if (!space_heap()->sweeping_in_progress_for_space(allocator_->identity()))
    return false;
  if (space_heap()->sweeper()->IsSweepingDoneForSpace(allocator_->identity()))
    return false;
  const bool is_main_thread =
      allocator_->is_main_thread() ||
      (allocator_->in_gc() && isolate_heap()->IsMainThread());
  const auto sweeping_scope_kind =
      is_main_thread ? ThreadKind::kMain : ThreadKind::kBackground;
  const auto sweeping_scope_id = space_heap()->sweeper()->GetTracingScope(
      allocator_->identity(), is_main_thread);
  TRACE_GC_EPOCH_WITH_FLOW(
      isolate_heap()->tracer(), sweeping_scope_id, sweeping_scope_kind,
      isolate_heap()->sweeper()->GetTraceIdForFlowEvent(sweeping_scope_id),
      TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
  // Cleanup invalidated old-to-new refs for compaction space in the
  // final atomic pause.
  Sweeper::SweepingMode sweeping_mode =
      allocator_->in_gc_for_space() ? Sweeper::SweepingMode::kEagerDuringGC
                                    : Sweeper::SweepingMode::kLazyOrConcurrent;
  if (!space_heap()->sweeper()->ParallelSweepSpace(allocator_->identity(),
                                                   sweeping_mode, max_pages)) {
    return false;
  }
  space_->RefillFreeList();
  return true;
}
References v8::internal::AllocatorPolicy::allocator_, v8::internal::Sweeper::GetTracingScope(), v8::internal::MainAllocator::identity(), v8::internal::MainAllocator::in_gc(), v8::internal::MainAllocator::in_gc_for_space(), v8::internal::MainAllocator::is_main_thread(), v8::internal::Heap::IsMainThread(), v8::internal::AllocatorPolicy::isolate_heap(), v8::internal::kBackground, v8::internal::Sweeper::kEagerDuringGC, v8::internal::Sweeper::kLazyOrConcurrent, v8::internal::kMain, v8::internal::PagedSpaceBase::RefillFreeList(), space_, v8::internal::AllocatorPolicy::space_heap(), v8::internal::Heap::sweeper(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, and TRACE_GC_EPOCH_WITH_FLOW.
Referenced by RefillLab().
EnsureAllocation()
bool v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) [final], [virtual]
Implements v8::internal::AllocatorPolicy.
Definition at line 637 of file main-allocator.cc.
                                                                          {
  if (allocator_->identity() == NEW_SPACE) {
    DCHECK(allocator_->is_main_thread());
    space_heap()->StartMinorMSConcurrentMarkingIfNeeded();
  }
  if ((allocator_->identity() != NEW_SPACE) && !allocator_->in_gc()) {
    // Start incremental marking before the actual allocation, this allows the
    // allocation function to mark the object black when incremental marking is
    // running.
    space_heap()->StartIncrementalMarkingIfAllocationLimitIsReached(
        allocator_->local_heap(), space_heap()->GCFlagsForIncrementalMarking(),
        kGCCallbackScheduleIdleGarbageCollection);
  }
  // We don't know exactly how much filler we need to align until space is
  // allocated, so assume the worst case.
  size_in_bytes += Heap::GetMaximumFillToAlign(alignment);
  if (allocator_->allocation_info().top() + size_in_bytes <=
      allocator_->allocation_info().limit()) {
    return true;
  }
  return RefillLab(size_in_bytes, origin);
}
References v8::internal::MainAllocator::allocation_info(), v8::internal::AllocatorPolicy::allocator_, v8::internal::DCHECK(), v8::internal::Heap::GetMaximumFillToAlign(), v8::internal::MainAllocator::identity(), v8::internal::MainAllocator::in_gc(), v8::internal::MainAllocator::is_main_thread(), v8::kGCCallbackScheduleIdleGarbageCollection, v8::internal::LinearAllocationArea::limit(), v8::internal::MainAllocator::local_heap(), v8::internal::NEW_SPACE, RefillLab(), v8::internal::AllocatorPolicy::space_heap(), v8::internal::Heap::StartIncrementalMarkingIfAllocationLimitIsReached(), v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded(), and v8::internal::LinearAllocationArea::top().
FreeLinearAllocationArea()
void v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationArea () [final], [virtual]
Implements v8::internal::AllocatorPolicy.
Definition at line 904 of file main-allocator.cc.
                                                         {
  if (!allocator_->IsLabValid()) return;
  base::MutexGuard guard(space_->mutex());
  FreeLinearAllocationAreaUnsynchronized();
}
References v8::internal::AllocatorPolicy::allocator_, FreeLinearAllocationAreaUnsynchronized(), v8::internal::MainAllocator::IsLabValid(), v8::internal::PagedSpaceBase::mutex(), and space_.
FreeLinearAllocationAreaUnsynchronized()
void v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized () [private]
Definition at line 911 of file main-allocator.cc.
                                                                       {
  if (!allocator_->IsLabValid()) return;
#if DEBUG
  allocator_->Verify();
#endif // DEBUG
  Address current_top = allocator_->top();
  Address current_limit = allocator_->limit();
  Address current_max_limit = allocator_->extended_limit();
  DCHECK_IMPLIES(!allocator_->supports_extending_lab(),
                 current_max_limit == current_limit);
  allocator_->AdvanceAllocationObservers();
  if (!v8_flags.black_allocated_pages) {
    if (current_top != current_limit &&
        allocator_->IsBlackAllocationEnabled()) {
      PageMetadata::FromAddress(current_top)
          ->DestroyBlackArea(current_top, current_limit);
    }
  }
  allocator_->ResetLab(kNullAddress, kNullAddress, kNullAddress);
  DCHECK_GE(current_limit, current_top);
  DCHECK_IMPLIES(current_limit - current_top >= 2 * kTaggedSize,
                 space_heap()->marking_state()->IsUnmarked(
                     HeapObject::FromAddress(current_top)));
  space_->Free(current_top, current_max_limit - current_top);
}
References v8::internal::MainAllocator::AdvanceAllocationObservers(), v8::internal::AllocatorPolicy::allocator_, DCHECK_GE, DCHECK_IMPLIES, v8::internal::PageMetadata::DestroyBlackArea(), v8::internal::MainAllocator::extended_limit(), v8::internal::PagedSpaceBase::Free(), v8::internal::PageMetadata::FromAddress(), v8::internal::HeapObject::FromAddress(), v8::internal::MainAllocator::IsBlackAllocationEnabled(), v8::internal::MainAllocator::IsLabValid(), v8::internal::kNullAddress, v8::internal::kTaggedSize, v8::internal::MainAllocator::limit(), v8::internal::MainAllocator::ResetLab(), space_, v8::internal::AllocatorPolicy::space_heap(), v8::internal::MainAllocator::supports_extending_lab(), v8::internal::MainAllocator::top(), and v8::internal::v8_flags.
Referenced by FreeLinearAllocationArea(), and TryAllocationFromFreeList().
RefillLab()
bool v8::internal::PagedSpaceAllocatorPolicy::RefillLab (int size_in_bytes, AllocationOrigin origin) [private]
Definition at line 663 of file main-allocator.cc.
                                                                   {
  // Allocation in this space has failed.
  DCHECK_GE(size_in_bytes, 0);
  if (TryExtendLAB(size_in_bytes)) return true;
  if (TryAllocationFromFreeList(size_in_bytes, origin)) return true;
  // Don't steal pages from the shared space of the main isolate if running as a
  // client. The issue is that the concurrent marker may be running on the main
  // isolate and may reach the page and read its flags, which will then end up
  // in a race, when the page of the compaction space will be merged back to the
  // main space. For the same reason, don't take swept pages from the main
  // shared space.
  const bool running_from_client_isolate_and_allocating_in_shared_space =
      (allocator_->identity() == SHARED_SPACE) &&
      !isolate_heap()->isolate()->is_shared_space_isolate();
  if (running_from_client_isolate_and_allocating_in_shared_space) {
    // Avoid OOM crash in the GC in order to invoke NearHeapLimitCallback after
    // GC and give it a chance to increase the heap limit.
    if (!isolate_heap()->force_oom() &&
        TryExpandAndAllocate(size_in_bytes, origin)) {
      return true;
    }
    return false;
  }
  // Sweeping is still in progress. The sweeper doesn't work with black
  // allocated pages, so it's fine for the compaction space to refill the
  // freelist from just swept pages.
  if (space_heap()->sweeping_in_progress()) {
    // First try to refill the free-list, concurrent sweeper threads
    // may have freed some objects in the meantime.
    if (space_heap()->sweeper()->ShouldRefillFreelistForSpace(
            allocator_->identity())) {
      space_->RefillFreeList();
      // Retry the free list allocation.
      if (TryAllocationFromFreeList(static_cast<size_t>(size_in_bytes), origin))
        return true;
    }
    static constexpr int kMaxPagesToSweep = 1;
    if (ContributeToSweeping(kMaxPagesToSweep)) {
      if (TryAllocationFromFreeList(size_in_bytes, origin)) {
        return true;
      }
    }
  }
  // If there is not enough memory in the compaction space left, try to steal
  // a page from the corresponding "regular" page space.
  // Don't do this though when black allocated pages are enabled and incremental
  // marking is in progress, because otherwise evacuating into a black allocated
  // page will cause the marker to miss the object.
  const bool incremental_marking_with_black_allocated_pages_is_running =
      v8_flags.black_allocated_pages &&
      space_heap()->incremental_marking()->IsMajorMarking();
  if (!incremental_marking_with_black_allocated_pages_is_running &&
      space_->is_compaction_space()) {
    DCHECK_NE(NEW_SPACE, allocator_->identity());
    PagedSpaceBase* main_space =
        space_heap()->paged_space(allocator_->identity());
    PageMetadata* page = main_space->RemovePageSafe(size_in_bytes);
    if (page != nullptr) {
      // Make sure we don't evacuate into a black allocated page.
      DCHECK_IMPLIES(v8_flags.black_allocated_pages,
                     !page->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
      space_->AddPage(page);
      if (TryAllocationFromFreeList(static_cast<size_t>(size_in_bytes), origin))
        return true;
    }
  }
  if (allocator_->identity() != NEW_SPACE &&
      space_heap()->ShouldExpandOldGenerationOnSlowAllocation(
          allocator_->local_heap(), origin) &&
      space_heap()->CanExpandOldGeneration(space_->AreaSize())) {
    if (TryExpandAndAllocate(static_cast<size_t>(size_in_bytes), origin)) {
      return true;
    }
  }
  // Try sweeping all pages.
  if (ContributeToSweeping()) {
    if (TryAllocationFromFreeList(size_in_bytes, origin)) {
      return true;
    }
  }
  if (allocator_->identity() != NEW_SPACE && allocator_->in_gc() &&
      !space_heap()->force_oom()) {
    // Avoid OOM crash in the GC in order to invoke NearHeapLimitCallback after
    // GC and give it a chance to increase the heap limit.
    if (TryExpandAndAllocate(size_in_bytes, origin)) {
      return true;
    }
  }
  return false;
}
References v8::internal::PagedSpaceBase::AddPage(), v8::internal::AllocatorPolicy::allocator_, v8::internal::PagedSpaceBase::AreaSize(), v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::MemoryChunkMetadata::Chunk(), ContributeToSweeping(), DCHECK_GE, DCHECK_IMPLIES, DCHECK_NE, v8::internal::Heap::force_oom(), v8::internal::MainAllocator::identity(), v8::internal::MainAllocator::in_gc(), v8::internal::Heap::incremental_marking(), v8::internal::PagedSpaceBase::is_compaction_space(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::IncrementalMarking::IsMajorMarking(), v8::internal::Heap::isolate(), v8::internal::AllocatorPolicy::isolate_heap(), v8::internal::MainAllocator::local_heap(), v8::internal::NEW_SPACE, v8::internal::Heap::paged_space(), v8::internal::PagedSpaceBase::RefillFreeList(), v8::internal::PagedSpaceBase::RemovePageSafe(), v8::internal::SHARED_SPACE, v8::internal::Sweeper::ShouldRefillFreelistForSpace(), space_, v8::internal::AllocatorPolicy::space_heap(), v8::internal::Heap::sweeper(), v8::internal::Heap::sweeping_in_progress(), TryAllocationFromFreeList(), TryExpandAndAllocate(), TryExtendLAB(), and v8::internal::v8_flags.
Referenced by EnsureAllocation().
SetLinearAllocationArea()
void v8::internal::PagedSpaceAllocatorPolicy::SetLinearAllocationArea (Address top, Address limit, Address end) [private]
Definition at line 809 of file main-allocator.cc.
                                                                     {
  allocator_->ResetLab(top, limit, end);
  if (v8_flags.black_allocated_pages) return;
  if (top != kNullAddress && top != limit) {
    PageMetadata* page = PageMetadata::FromAllocationAreaAddress(top);
    if (allocator_->IsBlackAllocationEnabled()) {
      page->CreateBlackArea(top, limit);
    }
  }
}
References v8::internal::AllocatorPolicy::allocator_, v8::internal::PageMetadata::CreateBlackArea(), v8::internal::compiler::end(), v8::internal::PageMetadata::FromAllocationAreaAddress(), v8::internal::MainAllocator::IsBlackAllocationEnabled(), v8::internal::kNullAddress, v8::internal::MainAllocator::ResetLab(), and v8::internal::v8_flags.
Referenced by TryAllocationFromFreeList().
TryAllocationFromFreeList()
bool v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList (size_t size_in_bytes, AllocationOrigin origin) [private]
Definition at line 822 of file main-allocator.cc.
                                                   {
  PagedSpace::ConcurrentAllocationMutex guard(space_);
  DCHECK(IsAligned(size_in_bytes, kTaggedSize));
  DCHECK_LE(allocator_->top(), allocator_->limit());
#ifdef DEBUG
  if (allocator_->top() != allocator_->limit()) {
    DCHECK_EQ(PageMetadata::FromAddress(allocator_->top()),
              PageMetadata::FromAddress(allocator_->limit() - 1));
  }
#endif
  // Don't free list allocate if there is linear space available.
  DCHECK_LT(static_cast<size_t>(allocator_->limit() - allocator_->top()),
            size_in_bytes);
  size_t new_node_size = 0;
  Tagged<FreeSpace> new_node =
      space_->free_list_->Allocate(size_in_bytes, &new_node_size, origin);
  if (new_node.is_null()) return false;
  DCHECK_GE(new_node_size, size_in_bytes);
  // The old-space-step might have finished sweeping and restarted marking.
  // Verify that it did not turn the page of the new node into an evacuation
  // candidate.
  DCHECK(!MarkCompactCollector::IsOnEvacuationCandidate(new_node));
  // Mark the old linear allocation area with a free space map so it can be
  // skipped when scanning the heap. This also puts it back in the free list
  // if it is big enough.
  FreeLinearAllocationAreaUnsynchronized();
  // Memory in the linear allocation area is counted as allocated. We may free
  // a little of this again immediately - see below.
  PageMetadata* page = PageMetadata::FromHeapObject(new_node);
  space_->IncreaseAllocatedBytes(new_node_size, page);
  DCHECK_EQ(allocator_->allocation_info().start(),
            allocator_->allocation_info().top());
  Address start = new_node.address();
  Address end = new_node.address() + new_node_size;
  Address limit = allocator_->ComputeLimit(start, end, size_in_bytes);
  DCHECK_LE(limit, end);
  DCHECK_LE(size_in_bytes, limit - start);
  if (limit != end) {
    if (!allocator_->supports_extending_lab()) {
      space_->Free(limit, end - limit);
      end = limit;
    } else {
      DCHECK(allocator_->is_main_thread());
      space_heap()->CreateFillerObjectAt(limit, static_cast<int>(end - limit));
    }
  }
  SetLinearAllocationArea(start, limit, end);
  space_->AddRangeToActiveSystemPages(page, start, limit);
  return true;
}
References v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), v8::internal::Tagged< HeapObject >::address(), v8::internal::MainAllocator::allocation_info(), v8::internal::AllocatorPolicy::allocator_, v8::internal::MainAllocator::ComputeLimit(), v8::internal::Heap::CreateFillerObjectAt(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_LT, v8::internal::compiler::end(), v8::internal::PagedSpaceBase::Free(), FreeLinearAllocationAreaUnsynchronized(), v8::internal::PageMetadata::FromAddress(), v8::internal::PageMetadata::FromHeapObject(), v8::internal::PagedSpaceBase::IncreaseAllocatedBytes(), v8::internal::MainAllocator::is_main_thread(), v8::internal::Tagged< HeapObject >::is_null(), IsAligned(), v8::internal::MarkCompactCollector::IsOnEvacuationCandidate(), v8::internal::kTaggedSize, v8::internal::MainAllocator::limit(), SetLinearAllocationArea(), space_, v8::internal::AllocatorPolicy::space_heap(), v8::internal::LinearAllocationArea::start(), v8::internal::MainAllocator::supports_extending_lab(), v8::internal::LinearAllocationArea::top(), and v8::internal::MainAllocator::top().
Referenced by RefillLab(), and TryExpandAndAllocate().
TryExpandAndAllocate()
bool v8::internal::PagedSpaceAllocatorPolicy::TryExpandAndAllocate (size_t size_in_bytes, AllocationOrigin origin) [private]
Definition at line 765 of file main-allocator.cc.
                                                                              {
  // Run in a loop because concurrent threads might allocate from the new free
  // list entries before this thread gets a chance.
  while (space_->TryExpand(allocator_->local_heap(), origin)) {
    if (TryAllocationFromFreeList(static_cast<size_t>(size_in_bytes), origin)) {
      return true;
    }
  }
  return false;
}
References v8::internal::AllocatorPolicy::allocator_, v8::internal::MainAllocator::local_heap(), space_, TryAllocationFromFreeList(), and v8::internal::PagedSpaceBase::TryExpand().
Referenced by RefillLab().
TryExtendLAB()
bool v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB (int size_in_bytes) [private]
Definition at line 880 of file main-allocator.cc.
                                                              {
  if (!allocator_->supports_extending_lab()) return false;
  Address current_top = allocator_->top();
  if (current_top == kNullAddress) return false;
  Address current_limit = allocator_->limit();
  Address max_limit = allocator_->extended_limit();
  if (current_top + size_in_bytes > max_limit) {
    return false;
  }
  allocator_->AdvanceAllocationObservers();
  Address new_limit =
      allocator_->ComputeLimit(current_top, max_limit, size_in_bytes);
  allocator_->ExtendLAB(new_limit);
  DCHECK(allocator_->is_main_thread());
  space_heap()->CreateFillerObjectAt(new_limit,
                                     static_cast<int>(max_limit - new_limit));
  PageMetadata* page = PageMetadata::FromAddress(current_top);
  // No need to create a black allocation area since new space doesn't use
  // black allocation.
  DCHECK_EQ(NEW_SPACE, allocator_->identity());
  space_->AddRangeToActiveSystemPages(page, current_limit, new_limit);
  return true;
}
References v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), v8::internal::MainAllocator::AdvanceAllocationObservers(), v8::internal::AllocatorPolicy::allocator_, v8::internal::MainAllocator::ComputeLimit(), v8::internal::Heap::CreateFillerObjectAt(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MainAllocator::extended_limit(), v8::internal::MainAllocator::ExtendLAB(), v8::internal::PageMetadata::FromAddress(), v8::internal::MainAllocator::identity(), v8::internal::MainAllocator::is_main_thread(), v8::internal::kNullAddress, v8::internal::MainAllocator::limit(), v8::internal::NEW_SPACE, space_, v8::internal::AllocatorPolicy::space_heap(), v8::internal::MainAllocator::supports_extending_lab(), and v8::internal::MainAllocator::top().
Referenced by RefillLab().
Friends And Related Function Documentation
PagedNewSpaceAllocatorPolicy
friend class PagedNewSpaceAllocatorPolicy [friend]
Definition at line 98 of file main-allocator.h.
Member Data Documentation
space_
PagedSpaceBase* const v8::internal::PagedSpaceAllocatorPolicy::space_ [private]
Definition at line 96 of file main-allocator.h.
Referenced by ContributeToSweeping(), FreeLinearAllocationArea(), FreeLinearAllocationAreaUnsynchronized(), RefillLab(), TryAllocationFromFreeList(), TryExpandAndAllocate(), and TryExtendLAB().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/main-allocator.h
/mnt/V8SourceCode/src/heap/main-allocator.cc