v8::internal::HeapObject Class Reference
#include <heap-object.h>
Classes
struct SkipTypeCheckTag
Public Types
using MapField = TaggedField< MapWord, HeapObject::kMapOffset >
Public Member Functions
constexpr HeapObject ()=default
void set_map (Isolate *isolate, Tagged< Map > value)
template<typename IsolateT >
void set_map_safe_transition (IsolateT *isolate, Tagged< Map > value)
ObjectSlot map_slot () const
void set_map_no_write_barrier (Isolate *isolate, Tagged< Map > value, RelaxedStoreTag=kRelaxedStore)
void set_map_no_write_barrier (Isolate *isolate, Tagged< Map > value, ReleaseStoreTag)
void set_map_safe_transition_no_write_barrier (Isolate *isolate, Tagged< Map > value, RelaxedStoreTag=kRelaxedStore)
void set_map_safe_transition_no_write_barrier (Isolate *isolate, Tagged< Map > value, ReleaseStoreTag)
template<typename IsolateT >
void set_map (IsolateT *isolate, Tagged< Map > value, ReleaseStoreTag)
template<typename IsolateT >
void set_map_safe_transition (IsolateT *isolate, Tagged< Map > value, ReleaseStoreTag)
bool release_compare_and_swap_map_word_forwarded (MapWord old_map_word, Tagged< HeapObject > new_target_object)
bool relaxed_compare_and_swap_map_word_forwarded (MapWord old_map_word, Tagged< HeapObject > new_target_object)
template<typename IsolateT >
void set_map_after_allocation (IsolateT *isolate, Tagged< Map > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void set_map_word (Tagged< Map > map, RelaxedStoreTag)
void set_map_word_forwarded (Tagged< HeapObject > target_object, RelaxedStoreTag)
void set_map_word (Tagged< Map > map, ReleaseStoreTag)
void set_map_word_forwarded (Tagged< HeapObject > target_object, ReleaseStoreTag)
ReadOnlyRoots EarlyGetReadOnlyRoots () const
Address address () const
V8_EXPORT_PRIVATE int SizeFromMap (Tagged< Map > map) const
template<class T >
T ReadField (size_t offset) const requires(std
template<class T >
void WriteField (size_t offset, T value) const requires(std
Address ReadSandboxedPointerField (size_t offset, PtrComprCageBase cage_base) const
void WriteSandboxedPointerField (size_t offset, PtrComprCageBase cage_base, Address value)
void WriteSandboxedPointerField (size_t offset, Isolate *isolate, Address value)
size_t ReadBoundedSizeField (size_t offset) const
void WriteBoundedSizeField (size_t offset, size_t value)
template<ExternalPointerTag tag>
void InitExternalPointerField (size_t offset, IsolateForSandbox isolate, Address value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
template<ExternalPointerTagRange tag_range>
Address ReadExternalPointerField (size_t offset, IsolateForSandbox isolate) const
template<CppHeapPointerTag lower_bound, CppHeapPointerTag upper_bound>
Address ReadCppHeapPointerField (size_t offset, IsolateForPointerCompression isolate) const
Address ReadCppHeapPointerField (size_t offset, IsolateForPointerCompression isolate, CppHeapPointerTagRange tag_range) const
template<ExternalPointerTag tag>
void WriteExternalPointerField (size_t offset, IsolateForSandbox isolate, Address value)
void SetupLazilyInitializedExternalPointerField (size_t offset)
bool IsLazilyInitializedExternalPointerFieldInitialized (size_t offset) const
template<ExternalPointerTag tag>
void WriteLazilyInitializedExternalPointerField (size_t offset, IsolateForSandbox isolate, Address value)
void SetupLazilyInitializedCppHeapPointerField (size_t offset)
template<CppHeapPointerTag tag>
void WriteLazilyInitializedCppHeapPointerField (size_t offset, IsolateForPointerCompression isolate, Address value)
void WriteLazilyInitializedCppHeapPointerField (size_t offset, IsolateForPointerCompression isolate, Address value, CppHeapPointerTag tag)
template<IndirectPointerTag tag>
Tagged< ExposedTrustedObject > ReadTrustedPointerField (size_t offset, IsolateForSandbox isolate) const
template<IndirectPointerTag tag>
Tagged< ExposedTrustedObject > ReadTrustedPointerField (size_t offset, IsolateForSandbox isolate, AcquireLoadTag) const
template<IndirectPointerTag tag>
Tagged< Object > ReadMaybeEmptyTrustedPointerField (size_t offset, IsolateForSandbox isolate, AcquireLoadTag) const
template<IndirectPointerTag tag>
void WriteTrustedPointerField (size_t offset, Tagged< ExposedTrustedObject > value)
bool IsTrustedPointerFieldEmpty (size_t offset) const
bool IsTrustedPointerFieldUnpublished (size_t offset, IndirectPointerTag tag, IsolateForSandbox isolate) const
void ClearTrustedPointerField (size_t offest)
void ClearTrustedPointerField (size_t offest, ReleaseStoreTag)
Tagged< Code > ReadCodePointerField (size_t offset, IsolateForSandbox isolate) const
void WriteCodePointerField (size_t offset, Tagged< Code > value)
bool IsCodePointerFieldEmpty (size_t offset) const
void ClearCodePointerField (size_t offest)
Address ReadCodeEntrypointViaCodePointerField (size_t offset, CodeEntrypointTag tag) const
void WriteCodeEntrypointViaCodePointerField (size_t offset, Address value, CodeEntrypointTag tag)
ObjectSlot RawField (int byte_offset) const
MaybeObjectSlot RawMaybeWeakField (int byte_offset) const
InstructionStreamSlot RawInstructionStreamField (int byte_offset) const
ExternalPointerSlot RawExternalPointerField (int byte_offset, ExternalPointerTagRange tag_range) const
CppHeapPointerSlot RawCppHeapPointerField (int byte_offset) const
IndirectPointerSlot RawIndirectPointerField (int byte_offset, IndirectPointerTag tag) const
WriteBarrierMode GetWriteBarrierMode (const DisallowGarbageCollection &promise)
void HeapObjectShortPrint (std::ostream &os)
void Print ()
bool CheckRequiredAlignment (PtrComprCageBase cage_base) const
bool NeedsRehashing (InstanceType instance_type) const
bool NeedsRehashing (PtrComprCageBase cage_base) const
bool CanBeRehashed (PtrComprCageBase cage_base) const
template<typename IsolateT >
void RehashBasedOnMap (IsolateT *isolate)
Address GetFieldAddress (int field_offset) const
HeapObject * operator-> ()
const HeapObject * operator-> () const
Static Public Member Functions
static void SetFillerMap (const WritableFreeSpace &writable_page, Tagged< Map > value)
static Tagged< HeapObject > FromAddress (Address address)
template<typename ObjectType >
static JSDispatchHandle AllocateAndInstallJSDispatchHandle (ObjectType host, size_t offset, Isolate *isolate, uint16_t parameter_count, DirectHandle< Code > code, WriteBarrierMode mode=WriteBarrierMode::UPDATE_WRITE_BARRIER)
static void Print (Tagged< Object > obj)
static void Print (Tagged< Object > obj, std::ostream &os)
static AllocationAlignment RequiredAlignment (InSharedSpace in_shared_space, Tagged< Map > map)
static AllocationAlignment RequiredAlignment (AllocationSpace allocation_space, Tagged< Map > map)
Static Public Attributes
static constexpr int kMapOffset = offsetof(HeapObjectLayout, map_)
static constexpr int kHeaderSize = sizeof(HeapObjectLayout)
Protected Member Functions
constexpr HeapObject (Address ptr, HeapObject::SkipTypeCheckTag)
HeapObject (Address ptr)
Address field_address (size_t offset) const
Static Protected Member Functions
template<typename T >
static bool IsSmi (T obj)
template<typename T >
static bool IsHeapObject (T obj)
Private Types
enum class VerificationMode { kSafeMapTransition
, kPotentialLayoutChange
 }
enum class EmitWriteBarrier { kYes
, kNo
 }
Private Member Functions
template<EmitWriteBarrier emit_write_barrier, typename MemoryOrder , typename IsolateT >
void set_map (IsolateT *isolate, Tagged< Map > value, MemoryOrder order, VerificationMode mode)
Friends
class Tagged< HeapObject >
Detailed Description
Definition at line 150 of file heap-object.h.
Member Typedef Documentation
MapField
using v8::internal::HeapObject::MapField = TaggedField<MapWord, HeapObject::kMapOffset>
Definition at line 503 of file heap-object.h.
Member Enumeration Documentation
EmitWriteBarrier
enum v8::internal::HeapObject::EmitWriteBarrier [strong], [private]
Enumerator
kYes
kNo
Definition at line 535 of file heap-object.h.
                              {
    kYes,
    kNo,
  };
VerificationMode
enum v8::internal::HeapObject::VerificationMode [strong], [private]
Enumerator
kSafeMapTransition
kPotentialLayoutChange
Definition at line 530 of file heap-object.h.
                              {
    kSafeMapTransition,
    kPotentialLayoutChange,
  };
Constructor & Destructor Documentation
HeapObject() [1/3]
constexpr v8::internal::HeapObject::HeapObject () [constexpr], [default]
HeapObject() [2/3]
constexpr v8::internal::HeapObject::HeapObject (Address ptr, HeapObject::SkipTypeCheckTag) [inline], [explicit], [constexpr], [protected]
Definition at line 513 of file heap-object.h.
      : TaggedImpl(ptr) {}
HeapObject() [3/3]
v8::internal::HeapObject::HeapObject (Address ptr) [inline], [explicit], [protected]
Definition at line 546 of file heap-object.h.
                                         : TaggedImpl(ptr) {
  IsHeapObject(*this);
}
References v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::IsHeapObject().
Member Function Documentation
address()
Address v8::internal::HeapObject::address () const [inline]
Definition at line 232 of file heap-object.h.
{ return ptr() - kHeapObjectTag; }
References v8::internal::kHeapObjectTag, and v8::internal::HeapObjectLayout::ptr().
Referenced by v8::internal::GcSafeCode::CanDeoptAt(), CheckRequiredAlignment(), v8::internal::BytecodeArray::clear_padding(), v8::internal::Code::clear_padding(), v8::internal::AbstractCode::contains(), v8::internal::InstructionStream::Finalize(), v8::internal::Code::FromTargetAddress(), v8::internal::InstructionStream::FromTargetAddress(), InitExternalPointerField(), v8::internal::InstructionStream::Initialize(), and WriteLazilyInitializedExternalPointerField().
AllocateAndInstallJSDispatchHandle()
template<typename ObjectType >
JSDispatchHandle v8::internal::HeapObject::AllocateAndInstallJSDispatchHandle (ObjectType host, size_t offset, Isolate * isolate, uint16_t parameter_count, DirectHandle< Code > code, WriteBarrierMode mode = WriteBarrierMode::UPDATE_WRITE_BARRIER) [inline], [static]
Definition at line 1203 of file objects-inl.h.
                                                    {
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable::Space* space =
      isolate->GetJSDispatchTableSpaceFor(host->field_address(offset));
  JSDispatchHandle handle =
      isolate->factory()->NewJSDispatchHandle(parameter_count, code, space);
  // Use a Release_Store to ensure that the store of the pointer into the table
  // is not reordered after the store of the handle. Otherwise, other threads
  // may access an uninitialized table entry and crash.
  auto location =
      reinterpret_cast<JSDispatchHandle*>(host->field_address(offset));
  base::AsAtomic32::Release_Store(location, handle);
  CONDITIONAL_JS_DISPATCH_HANDLE_WRITE_BARRIER(*host, handle, mode);
  return handle;
#else
  UNREACHABLE();
#endif // V8_ENABLE_LEAPTIERING
}
References code, CONDITIONAL_JS_DISPATCH_HANDLE_WRITE_BARRIER, v8::internal::Isolate::factory(), v8::internal::handle(), mode(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), space, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Factory::JSFunctionBuilder::BuildRaw().
CanBeRehashed()
bool v8::internal::HeapObject::CanBeRehashed (PtrComprCageBase cage_base) const
Definition at line 2138 of file objects.cc.
                                                               {
  DCHECK(NeedsRehashing(cage_base));
  switch (map(cage_base)->instance_type()) {
    case JS_MAP_TYPE:
    case JS_SET_TYPE:
      return true;
    case ORDERED_HASH_MAP_TYPE:
    case ORDERED_HASH_SET_TYPE:
      UNREACHABLE(); // We'll rehash from the JSMap or JSSet referencing them.
    case ORDERED_NAME_DICTIONARY_TYPE:
      return false;
    case NAME_DICTIONARY_TYPE:
    case NAME_TO_INDEX_HASH_TABLE_TYPE:
    case REGISTERED_SYMBOL_TABLE_TYPE:
    case GLOBAL_DICTIONARY_TYPE:
    case NUMBER_DICTIONARY_TYPE:
    case SIMPLE_NUMBER_DICTIONARY_TYPE:
    case SWISS_NAME_DICTIONARY_TYPE:
      return true;
    case DESCRIPTOR_ARRAY_TYPE:
    case STRONG_DESCRIPTOR_ARRAY_TYPE:
      return true;
    case TRANSITION_ARRAY_TYPE:
      return true;
    case SMALL_ORDERED_HASH_MAP_TYPE:
      return Cast<SmallOrderedHashMap>(*this)->NumberOfElements() == 0;
    case SMALL_ORDERED_HASH_SET_TYPE:
      return Cast<SmallOrderedHashMap>(*this)->NumberOfElements() == 0;
    case SMALL_ORDERED_NAME_DICTIONARY_TYPE:
      return Cast<SmallOrderedNameDictionary>(*this)->NumberOfElements() == 0;
    default:
      return false;
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), NeedsRehashing(), and v8::internal::UNREACHABLE().
CheckRequiredAlignment()
bool v8::internal::HeapObject::CheckRequiredAlignment (PtrComprCageBase cage_base) const [inline]
Definition at line 1765 of file objects-inl.h.
                                                                        {
  const InSharedSpace in_shared_space = HeapLayout::InWritableSharedSpace(*this)
                                            ? kInSharedSpace
                                            : kNotInSharedSpace;
  AllocationAlignment alignment =
      HeapObject::RequiredAlignment(in_shared_space, map(cage_base));
  CHECK_EQ(0, Heap::GetFillToAlign(address(), alignment));
  return true;
}
References address(), CHECK_EQ, v8::internal::Heap::GetFillToAlign(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::kInSharedSpace, v8::internal::kNotInSharedSpace, and RequiredAlignment().
ClearCodePointerField()
void v8::internal::HeapObject::ClearCodePointerField (size_t offest) [inline]
Definition at line 1186 of file objects-inl.h.
                                                    {
  ClearTrustedPointerField(offset);
}
References ClearTrustedPointerField().
ClearTrustedPointerField() [1/2]
void v8::internal::HeapObject::ClearTrustedPointerField (size_t offest) [inline]
Definition at line 1160 of file objects-inl.h.
                                                       {
#ifdef V8_ENABLE_SANDBOX
  RELEASE_WRITE_UINT32_FIELD(*this, offset, kNullIndirectPointerHandle);
#else
  TaggedField<Smi>::Release_Store(*this, static_cast<int>(offset), Smi::zero());
#endif
}
References v8::internal::kNullIndirectPointerHandle, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), RELEASE_WRITE_UINT32_FIELD, and v8::internal::Smi::zero().
Referenced by ClearCodePointerField(), and ClearTrustedPointerField().
ClearTrustedPointerField() [2/2]
void v8::internal::HeapObject::ClearTrustedPointerField (size_t offest, ReleaseStoreTag) [inline]
Definition at line 1168 of file objects-inl.h.
                                                                        {
  return ClearTrustedPointerField(offset);
}
References ClearTrustedPointerField().
EarlyGetReadOnlyRoots()
ReadOnlyRoots v8::internal::HeapObject::EarlyGetReadOnlyRoots () const [inline]
Definition at line 1363 of file objects-inl.h.
                                                      {
  return ReadOnlyHeap::EarlyGetReadOnlyRoots(*this);
}
References v8::internal::ReadOnlyHeap::EarlyGetReadOnlyRoots().
field_address()
Address v8::internal::HeapObject::field_address (size_t offset) const [inline], [protected]
Definition at line 525 of file heap-object.h.
                                                    {
    return ptr() + offset - kHeapObjectTag;
  }
References v8::internal::kHeapObjectTag, and v8::internal::HeapObjectLayout::ptr().
Referenced by GetFieldAddress(), InitExternalPointerField(), v8::internal::InstructionStream::instruction_start(), IsLazilyInitializedExternalPointerFieldInitialized(), v8::internal::SwissNameDictionary::PropertyDetailsTable(), RawCppHeapPointerField(), RawExternalPointerField(), RawField(), RawIndirectPointerField(), RawInstructionStreamField(), RawMaybeWeakField(), v8::internal::TrustedObject::RawProtectedMaybeObjectField(), v8::internal::TrustedObject::RawProtectedPointerField(), ReadBoundedSizeField(), ReadCodeEntrypointViaCodePointerField(), ReadCppHeapPointerField(), ReadExternalPointerField(), ReadMaybeEmptyTrustedPointerField(), ReadSandboxedPointerField(), SetupLazilyInitializedCppHeapPointerField(), SetupLazilyInitializedExternalPointerField(), WriteBoundedSizeField(), WriteCodeEntrypointViaCodePointerField(), WriteExternalPointerField(), WriteLazilyInitializedCppHeapPointerField(), WriteLazilyInitializedExternalPointerField(), WriteSandboxedPointerField(), and WriteTrustedPointerField().
FromAddress()
static Tagged<HeapObject> v8::internal::HeapObject::FromAddress (Address address) [inline], [static]
Definition at line 226 of file heap-object.h.
                                                                {
    DCHECK_TAG_ALIGNED(address);
    return Tagged<HeapObject>(address + kHeapObjectTag);
  }
References v8::internal::HeapObjectLayout::address(), DCHECK_TAG_ALIGNED, v8::internal::kHeapObjectTag, and v8::internal::Tagged< HeapObject >.
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), v8::internal::HeapObjectRange::iterator::AdvanceToNextObject(), v8::internal::MainAllocator::AllocateFastAligned(), v8::internal::MainAllocator::AllocateFastUnaligned(), v8::internal::FoldedMutableHeapNumberAllocator::AllocateNext(), v8::internal::LocalFactory::AllocateRaw(), v8::internal::ReadOnlySpace::AllocateRawUnaligned(), v8::internal::Heap::AllocationTrackerForDebugging::AllocationEvent(), v8::internal::Serializer::CopyCode(), v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::FreeListCategory::Free(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), v8::internal::InstructionStream::FromEntryAddress(), v8::internal::InstructionStream::FromTargetAddress(), v8::internal::Heap::GcSafeTryFindInstructionStreamForInnerPointer(), v8::internal::LargePageMetadata::GetObject(), v8::internal::Heap::LeftTrimFixedArray(), v8::internal::Heap::AllocationTrackerForDebugging::MoveEvent(), v8::internal::ReadOnlyPageObjectIterator::Next(), v8::internal::SemiSpaceObjectIterator::Next(), v8::internal::anonymous_namespace{read-only-spaces.cc}::ReadOnlySpaceObjectIterator::Next(), v8::internal::HeapObjectRange::iterator::operator*(), v8::internal::Heap::PrecedeWithFiller(), v8::internal::Heap::PrecedeWithFillerBackground(), v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects(), v8::internal::Heap::RightTrimArray(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::SamplingHeapProfiler::SampleObject(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), v8::internal::MapWord::ToForwardingAddress(), v8::internal::ReadOnlySpace::TryAllocateLinearlyAligned(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::VisitConservativelyIfPointer(), v8::internal::WritableJitAllocation::WriteHeaderSlot(), v8::internal::WritableFreeSpace::WriteHeaderSlot(), and v8::internal::WritableJitAllocation::WriteProtectedPointerHeaderSlot().
GetFieldAddress()
Address v8::internal::HeapObject::GetFieldAddress (int field_offset) const [inline]
Definition at line 1775 of file objects-inl.h.
                                                          {
  return field_address(field_offset);
}
References field_address().
GetWriteBarrierMode()
WriteBarrierMode v8::internal::HeapObject::GetWriteBarrierMode (const DisallowGarbageCollection & promise) [inline]
Definition at line 1716 of file objects-inl.h.
                                              {
  return WriteBarrier::GetWriteBarrierModeForObject(*this, promise);
}
References v8::internal::WriteBarrier::GetWriteBarrierModeForObject().
HeapObjectShortPrint()
void v8::internal::HeapObject::HeapObjectShortPrint (std::ostream & os)
Definition at line 3545 of file objects-printer.cc.
                                                    {
  PtrComprCageBase cage_base = GetPtrComprCageBase();
  os << AsHex::Address(this->ptr()) << " ";
  if (IsString(*this, cage_base)) {
    HeapStringAllocator allocator;
    StringStream accumulator(&allocator);
    Cast<String>(*this)->StringShortPrint(&accumulator);
    os << accumulator.ToCString().get();
    return;
  }
  if (IsJSObject(*this, cage_base)) {
    HeapStringAllocator allocator;
    StringStream accumulator(&allocator);
    Cast<JSObject>(*this)->JSObjectShortPrint(&accumulator);
    os << accumulator.ToCString().get();
    return;
  }
  InstanceType instance_type = map(cage_base)->instance_type();
  // Skip invalid trusted objects. Technically it'd be fine to still handle
  // them below since we only print the objects, but such an object will
  // quickly lead to out-of-sandbox segfaults and so fuzzers will complain.
  if (InstanceTypeChecker::IsTrustedObject(instance_type) &&
      !OutsideSandboxOrInReadonlySpace(*this)) {
    os << "<Invalid TrustedObject (outside trusted space)>\n";
    return;
  }
  switch (instance_type) {
    case MAP_TYPE: {
      Tagged<Map> map = Cast<Map>(*this);
      if (map->instance_type() == MAP_TYPE) {
        // This is one of the meta maps, print only relevant fields.
        os << "<MetaMap (" << Brief(map->native_context_or_null()) << ")>";
      } else {
        os << "<Map";
        if (map->instance_size() != kVariableSizeSentinel) {
          os << "[" << map->instance_size() << "]";
        }
        os << "(";
        if (IsJSObjectMap(map)) {
          os << ElementsKindToString(map->elements_kind());
        } else {
          os << map->instance_type();
        }
        os << ")>";
      }
    } break;
    case AWAIT_CONTEXT_TYPE: {
      os << "<AwaitContext generator= ";
      HeapStringAllocator allocator;
      StringStream accumulator(&allocator);
      ShortPrint(Cast<Context>(*this)->extension(), &accumulator);
      os << accumulator.ToCString().get();
      os << '>';
      break;
    }
    case BLOCK_CONTEXT_TYPE:
      os << "<BlockContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case CATCH_CONTEXT_TYPE:
      os << "<CatchContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case DEBUG_EVALUATE_CONTEXT_TYPE:
      os << "<DebugEvaluateContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case EVAL_CONTEXT_TYPE:
      os << "<EvalContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case FUNCTION_CONTEXT_TYPE:
      os << "<FunctionContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case MODULE_CONTEXT_TYPE:
      os << "<ModuleContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case NATIVE_CONTEXT_TYPE:
      os << "<NativeContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case SCRIPT_CONTEXT_TYPE:
      os << "<ScriptContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case WITH_CONTEXT_TYPE:
      os << "<WithContext[" << Cast<Context>(*this)->length() << "]>";
      break;
    case SCRIPT_CONTEXT_TABLE_TYPE:
      os << "<ScriptContextTable["
         << Cast<ScriptContextTable>(*this)->capacity() << "]>";
      break;
    case HASH_TABLE_TYPE:
      os << "<HashTable[" << Cast<FixedArray>(*this)->length() << "]>";
      break;
    case ORDERED_HASH_MAP_TYPE:
      os << "<OrderedHashMap[" << Cast<FixedArray>(*this)->length() << "]>";
      break;
    case ORDERED_HASH_SET_TYPE:
      os << "<OrderedHashSet[" << Cast<FixedArray>(*this)->length() << "]>";
      break;
    case ORDERED_NAME_DICTIONARY_TYPE:
      os << "<OrderedNameDictionary[" << Cast<FixedArray>(*this)->length()
         << "]>";
      break;
    case NAME_DICTIONARY_TYPE:
      os << "<NameDictionary[" << Cast<FixedArray>(*this)->length() << "]>";
      break;
    case SWISS_NAME_DICTIONARY_TYPE:
      os << "<SwissNameDictionary["
         << Cast<SwissNameDictionary>(*this)->Capacity() << "]>";
      break;
    case GLOBAL_DICTIONARY_TYPE:
      os << "<GlobalDictionary[" << Cast<FixedArray>(*this)->length() << "]>";
      break;
    case NUMBER_DICTIONARY_TYPE:
      os << "<NumberDictionary[" << Cast<FixedArray>(*this)->length() << "]>";
      break;
    case SIMPLE_NUMBER_DICTIONARY_TYPE:
      os << "<SimpleNumberDictionary[" << Cast<FixedArray>(*this)->length()
         << "]>";
      break;
    case FIXED_ARRAY_TYPE:
      os << "<FixedArray[" << Cast<FixedArray>(*this)->length() << "]>";
      break;
    case OBJECT_BOILERPLATE_DESCRIPTION_TYPE:
      os << "<ObjectBoilerplateDescription["
         << Cast<ObjectBoilerplateDescription>(*this)->capacity() << "]>";
      break;
    case FIXED_DOUBLE_ARRAY_TYPE:
      os << "<FixedDoubleArray[" << Cast<FixedDoubleArray>(*this)->length()
         << "]>";
      break;
    case BYTE_ARRAY_TYPE:
      os << "<ByteArray[" << Cast<ByteArray>(*this)->length() << "]>";
      break;
    case BYTECODE_ARRAY_TYPE:
      os << "<BytecodeArray[" << Cast<BytecodeArray>(*this)->length() << "]>";
      break;
    case DESCRIPTOR_ARRAY_TYPE:
      os << "<DescriptorArray["
         << Cast<DescriptorArray>(*this)->number_of_descriptors() << "]>";
      break;
    case WEAK_FIXED_ARRAY_TYPE:
      os << "<WeakFixedArray[" << Cast<WeakFixedArray>(*this)->length() << "]>";
      break;
    case TRUSTED_FIXED_ARRAY_TYPE:
      os << "<TrustedFixedArray[" << Cast<TrustedFixedArray>(*this)->length()
         << "]>";
      break;
    case TRUSTED_WEAK_FIXED_ARRAY_TYPE:
      os << "<TrustedWeakFixedArray["
         << Cast<TrustedWeakFixedArray>(*this)->length() << "]>";
      break;
    case PROTECTED_FIXED_ARRAY_TYPE:
      os << "<ProtectedFixedArray["
         << Cast<ProtectedFixedArray>(*this)->length() << "]>";
      break;
    case PROTECTED_WEAK_FIXED_ARRAY_TYPE:
      os << "<ProtectedWeakFixedArray["
         << Cast<ProtectedWeakFixedArray>(*this)->length() << "]>";
      break;
    case TRANSITION_ARRAY_TYPE:
      os << "<TransitionArray[" << Cast<TransitionArray>(*this)->length()
         << "]>";
      break;
    case PROPERTY_ARRAY_TYPE:
      os << "<PropertyArray[" << Cast<PropertyArray>(*this)->length() << "]>";
      break;
    case CONTEXT_CELL_TYPE: {
      auto cell = Cast<ContextCell>(*this);
      os << "<ContextCell[" << cell->state();
      switch (cell->state()) {
        case ContextCell::kConst:
        case ContextCell::kSmi:
          os << "=" << Brief(cell->tagged_value());
          break;
        case ContextCell::kInt32:
          os << "=" << cell->int32_value();
          break;
        case ContextCell::kFloat64:
          os << "=" << cell->float64_value();
          break;
        case ContextCell::kDetached:
          break;
      }
      os << "]>";
      break;
    }
    case FEEDBACK_CELL_TYPE: {
      {
        ReadOnlyRoots roots = GetReadOnlyRoots();
        os << "<FeedbackCell[";
        if (map() == roots.no_closures_cell_map()) {
          os << "no feedback";
        } else if (map() == roots.one_closure_cell_map()) {
          os << "one closure";
        } else if (map() == roots.many_closures_cell_map()) {
          os << "many closures";
        } else {
          os << "!!!INVALID MAP!!!";
        }
        os << "]>";
      }
      break;
    }
    case CLOSURE_FEEDBACK_CELL_ARRAY_TYPE:
      os << "<ClosureFeedbackCellArray["
         << Cast<ClosureFeedbackCellArray>(*this)->length() << "]>";
      break;
    case FEEDBACK_VECTOR_TYPE:
      os << "<FeedbackVector[" << Cast<FeedbackVector>(*this)->length() << "]>";
      break;
    case FREE_SPACE_TYPE:
      os << "<FreeSpace[" << Cast<FreeSpace>(*this)->size(kRelaxedLoad) << "]>";
      break;
    case PREPARSE_DATA_TYPE: {
      Tagged<PreparseData> data = Cast<PreparseData>(*this);
      os << "<PreparseData[data=" << data->data_length()
         << " children=" << data->children_length() << "]>";
      break;
    }
    case UNCOMPILED_DATA_WITHOUT_PREPARSE_DATA_TYPE: {
      Tagged<UncompiledDataWithoutPreparseData> data =
          Cast<UncompiledDataWithoutPreparseData>(*this);
      os << "<UncompiledDataWithoutPreparseData (" << data->start_position()
         << ", " << data->end_position() << ")]>";
      break;
    }
    case UNCOMPILED_DATA_WITH_PREPARSE_DATA_TYPE: {
      Tagged<UncompiledDataWithPreparseData> data =
          Cast<UncompiledDataWithPreparseData>(*this);
      os << "<UncompiledDataWithPreparseData (" << data->start_position()
         << ", " << data->end_position()
         << ") preparsed=" << Brief(data->preparse_data()) << ">";
      break;
    }
    case SHARED_FUNCTION_INFO_TYPE: {
      Tagged<SharedFunctionInfo> shared = Cast<SharedFunctionInfo>(*this);
      std::unique_ptr<char[]> debug_name = shared->DebugNameCStr();
      if (debug_name[0] != '\0') {
        os << "<SharedFunctionInfo " << debug_name.get() << ">";
      } else {
        os << "<SharedFunctionInfo>";
      }
      break;
    }
    case JS_MESSAGE_OBJECT_TYPE:
      os << "<JSMessageObject>";
      break;
#define MAKE_STRUCT_CASE(TYPE, Name, name) \
  case TYPE: \
    os << "<" #Name; \
    Cast<Name>(*this)->BriefPrintDetails(os); \
    os << ">"; \
    break;
      STRUCT_LIST(MAKE_STRUCT_CASE)
#undef MAKE_STRUCT_CASE
    case ALLOCATION_SITE_TYPE: {
      os << "<AllocationSite>";
      break;
    }
    case SCOPE_INFO_TYPE: {
      Tagged<ScopeInfo> scope = Cast<ScopeInfo>(*this);
      os << "<ScopeInfo";
      if (!scope->IsEmpty()) os << " " << scope->scope_type();
      os << ">";
      break;
    }
    case CODE_TYPE: {
      Tagged<Code> code = Cast<Code>(*this);
      os << "<Code " << CodeKindToString(code->kind());
      if (code->is_builtin()) {
        os << " " << Builtins::name(code->builtin_id());
      }
      os << ">";
      break;
    }
    case HOLE_TYPE: {
#define PRINT_HOLE(Type, Value, _) \
  if (Is##Type(*this)) { \
    os << "<" #Value ">"; \
    break; \
  }
      HOLE_LIST(PRINT_HOLE)
#undef PRINT_HOLE
      UNREACHABLE();
    }
    case INSTRUCTION_STREAM_TYPE: {
      Tagged<InstructionStream> istream = Cast<InstructionStream>(*this);
      Tagged<Code> code = istream->code(kAcquireLoad);
      os << "<InstructionStream " << CodeKindToString(code->kind());
      if (code->is_builtin()) {
        os << " " << Builtins::name(code->builtin_id());
      }
      os << ">";
      break;
    }
    case ODDBALL_TYPE: {
      if (IsUndefined(*this)) {
        os << "<undefined>";
      } else if (IsNull(*this)) {
        os << "<null>";
      } else if (IsTrue(*this)) {
        os << "<true>";
      } else if (IsFalse(*this)) {
        os << "<false>";
      } else {
        os << "<Odd Oddball: ";
        os << Cast<Oddball>(*this)->to_string()->ToCString().get();
        os << ">";
      }
      break;
    }
    case SYMBOL_TYPE: {
      Tagged<Symbol> symbol = Cast<Symbol>(*this);
      symbol->SymbolShortPrint(os);
      break;
    }
    case HEAP_NUMBER_TYPE: {
      os << "<HeapNumber ";
      Cast<HeapNumber>(*this)->HeapNumberShortPrint(os);
      os << ">";
      break;
    }
    case BIGINT_TYPE: {
      os << "<BigInt ";
      Cast<BigInt>(*this)->BigIntShortPrint(os);
      os << ">";
      break;
    }
    case JS_PROXY_TYPE:
      os << "<JSProxy>";
      break;
    case FOREIGN_TYPE:
      os << "<Foreign>";
      break;
    case CELL_TYPE: {
      os << "<Cell value= ";
      HeapStringAllocator allocator;
      StringStream accumulator(&allocator);
      ShortPrint(Cast<Cell>(*this)->value(), &accumulator);
      os << accumulator.ToCString().get();
      os << '>';
      break;
    }
    case PROPERTY_CELL_TYPE: {
      Tagged<PropertyCell> cell = Cast<PropertyCell>(*this);
      os << "<PropertyCell name=";
      ShortPrint(cell->name(), os);
      os << " value=";
      HeapStringAllocator allocator;
      StringStream accumulator(&allocator);
      ShortPrint(cell->value(kAcquireLoad), &accumulator);
      os << accumulator.ToCString().get();
      os << '>';
      break;
    }
    case ACCESSOR_INFO_TYPE: {
      Tagged<AccessorInfo> info = Cast<AccessorInfo>(*this);
      os << "<AccessorInfo ";
      os << "name= " << Brief(info->name());
      os << ", data= " << Brief(info->data());
      os << ">";
      break;
    }
    case FUNCTION_TEMPLATE_INFO_TYPE: {
      Tagged<FunctionTemplateInfo> info = Cast<FunctionTemplateInfo>(*this);
      os << "<FunctionTemplateInfo ";
      Isolate* isolate;
      if (GetIsolateFromHeapObject(*this, &isolate)) {
        os << "callback= " << reinterpret_cast<void*>(info->callback(isolate));
      } else {
        os << "callback= " << kUnavailableString;
      }
      os << ", data= " << Brief(info->callback_data(kAcquireLoad));
      os << ", has_side_effects= ";
      if (info->has_side_effects()) {
        os << "true>";
      } else {
        os << "false>";
      }
      break;
    }
#if V8_ENABLE_WEBASSEMBLY
    case WASM_DISPATCH_TABLE_TYPE:
      os << "<WasmDispatchTable[" << Cast<WasmDispatchTable>(*this)->length()
         << "]>";
      break;
#endif // V8_ENABLE_WEBASSEMBLY
    default:
      os << "<Other heap object (" << map()->instance_type() << ")>";
      break;
  }
}
References v8::internal::AsHex::Address(), v8::internal::ElementsKindToString(), v8::internal::GetPtrComprCageBase(), v8::internal::kVariableSizeSentinel, v8::internal::OutsideSandboxOrInReadonlySpace(), v8::internal::ShortPrint(), and v8::internal::StringStream::ToCString().
InitExternalPointerField()
template<ExternalPointerTag tag>
void v8::internal::HeapObject::InitExternalPointerField (size_t offset, IsolateForSandbox isolate, Address value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 977 of file objects-inl.h.
                                                                 {
  i::InitExternalPointerField<tag>(address(), field_address(offset), isolate,
                                   value);
  CONDITIONAL_EXTERNAL_POINTER_WRITE_BARRIER(*this, static_cast<int>(offset),
                                             tag, mode);
}
References address(), CONDITIONAL_EXTERNAL_POINTER_WRITE_BARRIER, field_address(), mode(), and v8::internal::value.
IsCodePointerFieldEmpty()
bool v8::internal::HeapObject::IsCodePointerFieldEmpty (size_t offset) const [inline]
Definition at line 1182 of file objects-inl.h.
                                                            {
  return IsTrustedPointerFieldEmpty(offset);
}
References IsTrustedPointerFieldEmpty().
IsHeapObject()
template<typename T >
bool v8::internal::HeapObject::IsHeapObject (T obj) [static], [protected]
Definition at line 557 of file heap-object.h.
                                   {
  return i::IsHeapObject(obj);
}
References v8::internal::InstanceTypeChecker::IsHeapObject().
IsLazilyInitializedExternalPointerFieldInitialized()
bool v8::internal::HeapObject::IsLazilyInitializedExternalPointerFieldInitialized (size_t offset) const [inline]
Definition at line 1023 of file objects-inl.h.
                         {
#ifdef V8_ENABLE_SANDBOX
  auto location =
      reinterpret_cast<ExternalPointerHandle*>(field_address(offset));
  ExternalPointerHandle handle = base::AsAtomic32::Relaxed_Load(location);
  return handle != kNullExternalPointerHandle;
#else
  return ReadMaybeUnalignedValue<Address>(field_address(offset)) !=
         kNullAddress;
#endif // V8_ENABLE_SANDBOX
}
References field_address(), v8::internal::handle(), v8::internal::kNullAddress, v8::internal::kNullExternalPointerHandle, and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
IsSmi()
template<typename T >
bool v8::internal::HeapObject::IsSmi (T obj) [static], [protected]
Definition at line 552 of file heap-object.h.
                            {
  return i::IsSmi(obj);
}
References v8::internal::IsSmi().
IsTrustedPointerFieldEmpty()
bool v8::internal::HeapObject::IsTrustedPointerFieldEmpty (size_t offset) const [inline]
Definition at line 1138 of file objects-inl.h.
                                                               {
#ifdef V8_ENABLE_SANDBOX
  IndirectPointerHandle handle = ACQUIRE_READ_UINT32_FIELD(*this, offset);
  return handle == kNullIndirectPointerHandle;
#else
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return IsSmi(TaggedField<Object>::Acquire_Load(cage_base, *this,
                                                 static_cast<int>(offset)));
#endif
}
References ACQUIRE_READ_UINT32_FIELD, v8::internal::GetPtrComprCageBase(), v8::internal::handle(), v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::IsSmi(), and v8::internal::kNullIndirectPointerHandle.
Referenced by IsCodePointerFieldEmpty().
IsTrustedPointerFieldUnpublished()
bool v8::internal::HeapObject::IsTrustedPointerFieldUnpublished (size_t offset, IndirectPointerTag tag, IsolateForSandbox isolate) const [inline]
Definition at line 1149 of file objects-inl.h.
                                                                            {
#ifdef V8_ENABLE_SANDBOX
  IndirectPointerHandle handle = ACQUIRE_READ_UINT32_FIELD(*this, offset);
  const TrustedPointerTable& table = isolate.GetTrustedPointerTableFor(tag);
  return table.IsUnpublished(handle);
#else
  return false;
#endif
}
References ACQUIRE_READ_UINT32_FIELD, and v8::internal::handle().
map_slot()
ObjectSlot v8::internal::HeapObject::map_slot () const [inline]
Definition at line 1564 of file objects-inl.h.
                                      {
  return ObjectSlot(MapField::address(*this));
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::address().
Referenced by set_map(), and set_map_after_allocation().
NeedsRehashing() [1/2]
bool v8::internal::HeapObject::NeedsRehashing (InstanceType instance_type) const
Definition at line 2100 of file objects.cc.
                                                                {
  if (V8_EXTERNAL_CODE_SPACE_BOOL) {
    // Use map() only when it's guaranteed that it's not an InstructionStream
    // object.
    DCHECK_IMPLIES(instance_type != INSTRUCTION_STREAM_TYPE,
                   instance_type == map()->instance_type());
  } else {
    DCHECK_EQ(instance_type, map()->instance_type());
  }
  switch (instance_type) {
    case DESCRIPTOR_ARRAY_TYPE:
    case STRONG_DESCRIPTOR_ARRAY_TYPE:
      return Cast<DescriptorArray>(*this)->number_of_descriptors() > 1;
    case TRANSITION_ARRAY_TYPE:
      return Cast<TransitionArray>(*this)->number_of_transitions() > 1;
    case ORDERED_HASH_MAP_TYPE:
    case ORDERED_HASH_SET_TYPE:
      return false; // We'll rehash from the JSMap or JSSet referencing them.
    case NAME_DICTIONARY_TYPE:
    case NAME_TO_INDEX_HASH_TABLE_TYPE:
    case REGISTERED_SYMBOL_TABLE_TYPE:
    case GLOBAL_DICTIONARY_TYPE:
    case NUMBER_DICTIONARY_TYPE:
    case SIMPLE_NUMBER_DICTIONARY_TYPE:
    case HASH_TABLE_TYPE:
    case SMALL_ORDERED_HASH_MAP_TYPE:
    case SMALL_ORDERED_HASH_SET_TYPE:
    case SMALL_ORDERED_NAME_DICTIONARY_TYPE:
    case SWISS_NAME_DICTIONARY_TYPE:
    case JS_MAP_TYPE:
    case JS_SET_TYPE:
      return true;
    default:
      return false;
  }
  UNREACHABLE();
}
References DCHECK_EQ, DCHECK_IMPLIES, v8::internal::UNREACHABLE(), and V8_EXTERNAL_CODE_SPACE_BOOL.
Referenced by CanBeRehashed(), and NeedsRehashing().
NeedsRehashing() [2/2]
bool v8::internal::HeapObject::NeedsRehashing (PtrComprCageBase cage_base) const
Definition at line 2096 of file objects.cc.
                                                                {
  return NeedsRehashing(map(cage_base)->instance_type());
}
References NeedsRehashing().
operator->() [1/2]
HeapObject* v8::internal::HeapObject::operator-> () [inline]
Definition at line 507 of file heap-object.h.
{ return this; }
operator->() [2/2]
const HeapObject* v8::internal::HeapObject::operator-> () const [inline]
Definition at line 508 of file heap-object.h.
{ return this; }
Print() [1/3]
void v8::internal::HeapObject::Print ()
Definition at line 3535 of file objects-printer.cc.
{ Print(*this); }
References v8::internal::Print().
Referenced by v8::internal::BytecodeArray::Disassemble().
Print() [2/3]
void v8::internal::HeapObject::Print (Tagged< Object > obj) [static]
Definition at line 3538 of file objects-printer.cc.
{ v8::internal::Print(obj); }
References v8::internal::Print().
Print() [3/3]
void v8::internal::HeapObject::Print (Tagged< Object > obj, std::ostream & os) [static]
Definition at line 3541 of file objects-printer.cc.
                                                         {
  v8::internal::Print(obj, os);
}
References v8::internal::Print().
RawCppHeapPointerField()
CppHeapPointerSlot v8::internal::HeapObject::RawCppHeapPointerField (int byte_offset) const [inline]
Definition at line 1244 of file objects-inl.h.
                                                                           {
  return CppHeapPointerSlot(field_address(byte_offset));
}
References field_address().
RawExternalPointerField()
ExternalPointerSlot v8::internal::HeapObject::RawExternalPointerField (int byte_offset, ExternalPointerTagRange tag_range) const [inline]
Definition at line 1239 of file objects-inl.h.
                                                              {
  return ExternalPointerSlot(field_address(byte_offset), tag_range);
}
References field_address().
RawField()
ObjectSlot v8::internal::HeapObject::RawField (int byte_offset) const [inline]
Definition at line 1226 of file objects-inl.h.
                                                     {
  return ObjectSlot(field_address(byte_offset));
}
References field_address().
Referenced by v8::internal::SwissNameDictionary::Initialize().
RawIndirectPointerField()
IndirectPointerSlot v8::internal::HeapObject::RawIndirectPointerField (int byte_offset, IndirectPointerTag tag) const [inline]
Definition at line 1248 of file objects-inl.h.
                                                   {
  return IndirectPointerSlot(field_address(byte_offset), tag);
}
References field_address().
RawInstructionStreamField()
InstructionStreamSlot v8::internal::HeapObject::RawInstructionStreamField (int byte_offset) const [inline]
Definition at line 1234 of file objects-inl.h.
                           {
  return InstructionStreamSlot(field_address(byte_offset));
}
References field_address().
RawMaybeWeakField()
MaybeObjectSlot v8::internal::HeapObject::RawMaybeWeakField (int byte_offset) const [inline]
Definition at line 1230 of file objects-inl.h.
                                                                   {
  return MaybeObjectSlot(field_address(byte_offset));
}
References field_address().
ReadBoundedSizeField()
size_t v8::internal::HeapObject::ReadBoundedSizeField (size_t offset) const [inline]
Definition at line 968 of file objects-inl.h.
                                                           {
  return i::ReadBoundedSizeField(field_address(offset));
}
References field_address(), and v8::internal::ReadBoundedSizeField().
ReadCodeEntrypointViaCodePointerField()
Address v8::internal::HeapObject::ReadCodeEntrypointViaCodePointerField (size_t offset, CodeEntrypointTag tag) const [inline]
Definition at line 1190 of file objects-inl.h.
                                                {
  return i::ReadCodeEntrypointViaCodePointerField(field_address(offset), tag);
}
References field_address(), and v8::internal::ReadCodeEntrypointViaCodePointerField().
ReadCodePointerField()
Tagged< Code > v8::internal::HeapObject::ReadCodePointerField (size_t offset, IsolateForSandbox isolate) const [inline]
Definition at line 1172 of file objects-inl.h.
                                                                               {
  return Cast<Code>(
      ReadTrustedPointerField<kCodeIndirectPointerTag>(offset, isolate));
}
ReadCppHeapPointerField() [1/2]
template<CppHeapPointerTag lower_bound, CppHeapPointerTag upper_bound>
Address v8::internal::HeapObject::ReadCppHeapPointerField (size_t offset, IsolateForPointerCompression isolate) const [inline]
Definition at line 994 of file objects-inl.h.
                                                               {
  return i::ReadCppHeapPointerField<lower_bound, upper_bound>(
      field_address(offset), isolate);
}
References field_address().
ReadCppHeapPointerField() [2/2]
Address v8::internal::HeapObject::ReadCppHeapPointerField (size_t offset, IsolateForPointerCompression isolate, CppHeapPointerTagRange tag_range) const [inline]
Definition at line 1000 of file objects-inl.h.
                                            {
  return i::ReadCppHeapPointerField(field_address(offset), isolate, tag_range);
}
References field_address(), and v8::internal::ReadCppHeapPointerField().
ReadExternalPointerField()
template<ExternalPointerTagRange tag_range>
Address v8::internal::HeapObject::ReadExternalPointerField (size_t offset, IsolateForSandbox isolate) const [inline]
Definition at line 988 of file objects-inl.h.
                                                                              {
  return i::ReadExternalPointerField<tag_range>(field_address(offset), isolate);
}
References field_address().
ReadField()
template<class T >
T v8::internal::HeapObject::ReadField (size_t offset) const [inline]
Definition at line 243 of file heap-object.h.
  {
    return ReadMaybeUnalignedValue<T>(field_address(offset));
  }
ReadMaybeEmptyTrustedPointerField()
template<IndirectPointerTag tag>
Tagged< Object > v8::internal::HeapObject::ReadMaybeEmptyTrustedPointerField (size_t offset, IsolateForSandbox isolate, AcquireLoadTag acquire_load) const [inline]
Definition at line 1113 of file objects-inl.h.
                                       {
#ifdef V8_ENABLE_SANDBOX
  return i::ReadIndirectPointerField<tag>(field_address(offset), isolate,
                                          acquire_load);
#else
  return TaggedField<Object>::Acquire_Load(*this, static_cast<int>(offset));
#endif
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load(), and field_address().
ReadSandboxedPointerField()
Address v8::internal::HeapObject::ReadSandboxedPointerField (size_t offset, PtrComprCageBase cage_base) const [inline]
Definition at line 951 of file objects-inl.h.
                                                     {
  return i::ReadSandboxedPointerField(field_address(offset), cage_base);
}
References field_address(), and v8::internal::ReadSandboxedPointerField().
ReadTrustedPointerField() [1/2]
template<IndirectPointerTag tag>
Tagged< ExposedTrustedObject > v8::internal::HeapObject::ReadTrustedPointerField (size_t offset, IsolateForSandbox isolate) const [inline]
Definition at line 1095 of file objects-inl.h.
                                                    {
  // Currently, trusted pointer loads always use acquire semantics as the
  // under-the-hood indirect pointer loads use acquire loads anyway.
  return ReadTrustedPointerField<tag>(offset, isolate, kAcquireLoad);
}
References v8::kAcquireLoad.
ReadTrustedPointerField() [2/2]
template<IndirectPointerTag tag>
Tagged< ExposedTrustedObject > v8::internal::HeapObject::ReadTrustedPointerField (size_t offset, IsolateForSandbox isolate, AcquireLoadTag acquire_load) const [inline]
Definition at line 1103 of file objects-inl.h.
                                       {
  Tagged<Object> object =
      ReadMaybeEmptyTrustedPointerField<tag>(offset, isolate, acquire_load);
  DCHECK(IsExposedTrustedObject(object));
  return Cast<ExposedTrustedObject>(object);
}
References v8::internal::DCHECK().
RehashBasedOnMap()
template<typename IsolateT >
template void v8::internal::HeapObject::RehashBasedOnMap (IsolateT * isolate)
Definition at line 2175 of file objects.cc.
                                                   {
  switch (map(isolate)->instance_type()) {
    case HASH_TABLE_TYPE:
      Cast<ObjectHashTable>(*this)->Rehash(isolate);
      break;
    case NAME_DICTIONARY_TYPE:
      Cast<NameDictionary>(*this)->Rehash(isolate);
      break;
    case NAME_TO_INDEX_HASH_TABLE_TYPE:
      Cast<NameToIndexHashTable>(*this)->Rehash(isolate);
      break;
    case REGISTERED_SYMBOL_TABLE_TYPE:
      Cast<RegisteredSymbolTable>(*this)->Rehash(isolate);
      break;
    case SWISS_NAME_DICTIONARY_TYPE:
      Cast<SwissNameDictionary>(*this)->Rehash(isolate);
      break;
    case GLOBAL_DICTIONARY_TYPE:
      Cast<GlobalDictionary>(*this)->Rehash(isolate);
      break;
    case NUMBER_DICTIONARY_TYPE:
      Cast<NumberDictionary>(*this)->Rehash(isolate);
      break;
    case SIMPLE_NAME_DICTIONARY_TYPE:
      Cast<SimpleNameDictionary>(*this)->Rehash(isolate);
      break;
    case SIMPLE_NUMBER_DICTIONARY_TYPE:
      Cast<SimpleNumberDictionary>(*this)->Rehash(isolate);
      break;
    case DESCRIPTOR_ARRAY_TYPE:
    case STRONG_DESCRIPTOR_ARRAY_TYPE:
      DCHECK_LE(1, Cast<DescriptorArray>(*this)->number_of_descriptors());
      Cast<DescriptorArray>(*this)->Sort();
      break;
    case TRANSITION_ARRAY_TYPE:
      Cast<TransitionArray>(*this)->Sort();
      break;
    case SMALL_ORDERED_HASH_MAP_TYPE:
      DCHECK_EQ(0, Cast<SmallOrderedHashMap>(*this)->NumberOfElements());
      break;
    case SMALL_ORDERED_HASH_SET_TYPE:
      DCHECK_EQ(0, Cast<SmallOrderedHashSet>(*this)->NumberOfElements());
      break;
    case ORDERED_HASH_MAP_TYPE:
    case ORDERED_HASH_SET_TYPE:
      UNREACHABLE(); // We'll rehash from the JSMap or JSSet referencing them.
    case JS_MAP_TYPE: {
      Cast<JSMap>(*this)->Rehash(isolate->AsIsolate());
      break;
    }
    case JS_SET_TYPE: {
      Cast<JSSet>(*this)->Rehash(isolate->AsIsolate());
      break;
    }
    case SMALL_ORDERED_NAME_DICTIONARY_TYPE:
      DCHECK_EQ(0, Cast<SmallOrderedNameDictionary>(*this)->NumberOfElements());
      break;
    case INTERNALIZED_ONE_BYTE_STRING_TYPE:
    case INTERNALIZED_TWO_BYTE_STRING_TYPE:
      // Rare case, rehash read-only space strings before they are sealed.
      DCHECK(ReadOnlyHeap::Contains(*this));
      Cast<String>(*this)->EnsureHash();
      break;
    default:
      // TODO(ishell): remove once b/326043780 is no longer an issue.
      isolate->AsIsolate()->PushParamsAndDie(
          reinterpret_cast<void*>(ptr()), reinterpret_cast<void*>(map().ptr()),
          reinterpret_cast<void*>(
              static_cast<uintptr_t>(map()->instance_type())));
      UNREACHABLE();
  }
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr(), and v8::internal::UNREACHABLE().
relaxed_compare_and_swap_map_word_forwarded()
bool v8::internal::HeapObject::relaxed_compare_and_swap_map_word_forwarded (MapWord old_map_word, Tagged< HeapObject > new_target_object) [inline]
Definition at line 1634 of file objects-inl.h.
                                                                {
  Tagged_t result = MapField::Relaxed_CompareAndSwap(
      *this, old_map_word,
      MapWord::FromForwardingAddress(*this, new_target_object));
  return result == static_cast<Tagged_t>(old_map_word.ptr());
}
References v8::internal::MapWord::FromForwardingAddress(), v8::internal::MapWord::ptr(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_CompareAndSwap(), and v8::base::internal::result.
release_compare_and_swap_map_word_forwarded()
bool v8::internal::HeapObject::release_compare_and_swap_map_word_forwarded (MapWord old_map_word, Tagged< HeapObject > new_target_object) [inline]
Definition at line 1626 of file objects-inl.h.
                                                                {
  Tagged_t result = MapField::Release_CompareAndSwap(
      *this, old_map_word,
      MapWord::FromForwardingAddress(*this, new_target_object));
  return result == static_cast<Tagged_t>(old_map_word.ptr());
}
References v8::internal::MapWord::FromForwardingAddress(), v8::internal::MapWord::ptr(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_CompareAndSwap(), and v8::base::internal::result.
RequiredAlignment() [1/2]
AllocationAlignment v8::internal::HeapObject::RequiredAlignment (AllocationSpace allocation_space, Tagged< Map > map) [inline], [static]
Definition at line 1722 of file objects-inl.h.
                                                                   {
  return RequiredAlignment(
      IsAnySharedSpace(space) ? kInSharedSpace : kNotInSharedSpace, map);
}
References v8::internal::IsAnySharedSpace(), v8::internal::kInSharedSpace, v8::internal::kNotInSharedSpace, RequiredAlignment(), and space.
RequiredAlignment() [2/2]
AllocationAlignment v8::internal::HeapObject::RequiredAlignment (InSharedSpace in_shared_space, Tagged< Map > map) [inline], [static]
Definition at line 1729 of file objects-inl.h.
                                                                   {
  // TODO(v8:4153): We should think about requiring double alignment
  // in general for ByteArray, since they are used as backing store for typed
  // arrays now.
  // TODO(ishell, v8:8875): Consider using aligned allocations for BigInt.
  if (USE_ALLOCATION_ALIGNMENT_HEAP_NUMBER_BOOL) {
    int instance_type = map->instance_type();
    static_assert(!USE_ALLOCATION_ALIGNMENT_HEAP_NUMBER_BOOL ||
                  (sizeof(FixedDoubleArray::Header) & kDoubleAlignmentMask) ==
                      kTaggedSize);
    if (instance_type == FIXED_DOUBLE_ARRAY_TYPE) return kDoubleAligned;
    static_assert(!USE_ALLOCATION_ALIGNMENT_HEAP_NUMBER_BOOL ||
                  (offsetof(HeapNumber, value_) & kDoubleAlignmentMask) ==
                      kTaggedSize);
    if (instance_type == HEAP_NUMBER_TYPE) return kDoubleUnaligned;
  }
#if V8_ENABLE_WEBASSEMBLY
  if (in_shared_space && v8_flags.experimental_wasm_shared) [[unlikely]] {
    int instance_type = map->instance_type();
    if (instance_type == WASM_STRUCT_TYPE) {
      // The map of a shared wasm struct needs to be in the shared space.
      DCHECK(HeapLayout::InWritableSharedSpace(map));
      return kDoubleAligned;
    } else if (instance_type == WASM_ARRAY_TYPE) {
      // The map of a shared wasm array needs to be in the shared space.
      DCHECK(HeapLayout::InWritableSharedSpace(map));
      return kDoubleUnaligned;
    }
  }
#endif
  return kTaggedAligned;
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::kDoubleAligned, v8::internal::kDoubleAlignmentMask, v8::internal::kDoubleUnaligned, v8::internal::kTaggedAligned, v8::internal::kTaggedSize, USE_ALLOCATION_ALIGNMENT_HEAP_NUMBER_BOOL, and v8::internal::v8_flags.
Referenced by v8::internal::EvacuateNewSpaceVisitor::AllocateTargetObject(), CheckRequiredAlignment(), v8::internal::Scavenger::PromoteObject(), RequiredAlignment(), v8::internal::Scavenger::SemiSpaceCopyObject(), and v8::internal::EvacuateVisitorBase::TryEvacuateObject().
set_map() [1/3]
void v8::internal::HeapObject::set_map (Isolate * isolate, Tagged< Map > value) [inline]
Definition at line 1420 of file objects-inl.h.
                                                            {
  set_map<EmitWriteBarrier::kYes>(isolate, value, kRelaxedStore,
                                  VerificationMode::kPotentialLayoutChange);
}
References kPotentialLayoutChange, v8::kRelaxedStore, and v8::internal::value.
set_map() [2/3]
template<HeapObject::EmitWriteBarrier emit_write_barrier, typename MemoryOrder , typename IsolateT >
void v8::internal::HeapObject::set_map (IsolateT * isolate, Tagged< Map > value, MemoryOrder order, VerificationMode mode) [inline], [private]
Definition at line 1488 of file objects-inl.h.
                                                                   {
#if V8_ENABLE_WEBASSEMBLY
  // In {WasmGraphBuilder::SetMap} and {WasmGraphBuilder::LoadMap}, we treat
  // maps as immutable. Therefore we are not allowed to mutate them here.
  DCHECK(!IsWasmStructMap(value) && !IsWasmArrayMap(value));
#endif
  // Object layout changes are currently not supported on background threads.
  // This method might change object layout and therefore can't be used on
  // background threads.
  DCHECK_IMPLIES(mode != VerificationMode::kSafeMapTransition,
                 !LocalHeap::Current());
  if (v8_flags.verify_heap && !value.is_null()) {
    if (mode == VerificationMode::kSafeMapTransition) {
      HeapVerifier::VerifySafeMapTransition(isolate->heap()->AsHeap(), *this,
                                            value);
    } else {
      DCHECK_EQ(mode, VerificationMode::kPotentialLayoutChange);
      HeapVerifier::VerifyObjectLayoutChange(isolate->heap()->AsHeap(), *this,
                                             value);
    }
  }
  set_map_word(value, order);
  Heap::NotifyObjectLayoutChangeDone(*this);
#ifndef V8_DISABLE_WRITE_BARRIERS
  if (!value.is_null()) {
    if (emit_write_barrier == EmitWriteBarrier::kYes) {
      WriteBarrier::ForValue(*this, MaybeObjectSlot(map_slot()), value,
                             UPDATE_WRITE_BARRIER);
    } else {
      DCHECK_EQ(emit_write_barrier, EmitWriteBarrier::kNo);
      SLOW_DCHECK(!WriteBarrier::IsRequired(*this, value));
    }
  }
#endif
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::WriteBarrier::ForValue(), kNo, kPotentialLayoutChange, kSafeMapTransition, kYes, map_slot(), mode(), v8::internal::Heap::NotifyObjectLayoutChangeDone(), set_map_word(), SLOW_DCHECK, v8::internal::UPDATE_WRITE_BARRIER, v8::internal::v8_flags, v8::internal::value, v8::internal::HeapVerifier::VerifyObjectLayoutChange(), and v8::internal::HeapVerifier::VerifySafeMapTransition().
set_map() [3/3]
template<typename IsolateT >
void v8::internal::HeapObject::set_map (IsolateT * isolate, Tagged< Map > value, ReleaseStoreTag tag) [inline]
Definition at line 1426 of file objects-inl.h.
                                              {
  set_map<EmitWriteBarrier::kYes>(isolate, value, kReleaseStore,
                                  VerificationMode::kPotentialLayoutChange);
}
References kPotentialLayoutChange, v8::kReleaseStore, and v8::internal::value.
set_map_after_allocation()
template<typename IsolateT >
void v8::internal::HeapObject::set_map_after_allocation (IsolateT * isolate, Tagged< Map > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 1534 of file objects-inl.h.
                                                                 {
  set_map_word(value, kRelaxedStore);
#ifndef V8_DISABLE_WRITE_BARRIERS
  if (mode != SKIP_WRITE_BARRIER) {
    DCHECK(!value.is_null());
    WriteBarrier::ForValue(*this, MaybeObjectSlot(map_slot()), value, mode);
  } else {
    SLOW_DCHECK(
        // We allow writes of a null map before root initialisation.
        value.is_null() ? !isolate->read_only_heap()->roots_init_complete()
                        : !WriteBarrier::IsRequired(*this, value));
  }
#endif
}
References v8::internal::DCHECK(), v8::internal::WriteBarrier::ForValue(), v8::kRelaxedStore, map_slot(), mode(), set_map_word(), v8::internal::SKIP_WRITE_BARRIER, SLOW_DCHECK, and v8::internal::value.
set_map_no_write_barrier() [1/2]
void v8::internal::HeapObject::set_map_no_write_barrier (Isolate * isolate, Tagged< Map > value, RelaxedStoreTag tag = kRelaxedStore) [inline]
Definition at line 1474 of file objects-inl.h.
                                                               {
  set_map<EmitWriteBarrier::kNo>(isolate, value, kRelaxedStore,
                                 VerificationMode::kPotentialLayoutChange);
}
References kPotentialLayoutChange, v8::kRelaxedStore, and v8::internal::value.
set_map_no_write_barrier() [2/2]
void v8::internal::HeapObject::set_map_no_write_barrier (Isolate * isolate, Tagged< Map > value, ReleaseStoreTag tag) [inline]
Definition at line 1480 of file objects-inl.h.
                                                               {
  set_map<EmitWriteBarrier::kNo>(isolate, value, kReleaseStore,
                                 VerificationMode::kPotentialLayoutChange);
}
References kPotentialLayoutChange, v8::kReleaseStore, and v8::internal::value.
set_map_safe_transition() [1/2]
template<typename IsolateT >
void v8::internal::HeapObject::set_map_safe_transition (IsolateT * isolate, Tagged< Map > value) [inline]
Definition at line 1433 of file objects-inl.h.
                                                                             {
  set_map<EmitWriteBarrier::kYes>(isolate, value, kRelaxedStore,
                                  VerificationMode::kSafeMapTransition);
}
References v8::kRelaxedStore, kSafeMapTransition, and v8::internal::value.
set_map_safe_transition() [2/2]
template<typename IsolateT >
void v8::internal::HeapObject::set_map_safe_transition (IsolateT * isolate, Tagged< Map > value, ReleaseStoreTag tag) [inline]
Definition at line 1439 of file objects-inl.h.
                                                              {
  set_map<EmitWriteBarrier::kYes>(isolate, value, kReleaseStore,
                                  VerificationMode::kSafeMapTransition);
}
References v8::kReleaseStore, kSafeMapTransition, and v8::internal::value.
set_map_safe_transition_no_write_barrier() [1/2]
void v8::internal::HeapObject::set_map_safe_transition_no_write_barrier (Isolate * isolate, Tagged< Map > value, RelaxedStoreTag tag = kRelaxedStore) [inline]
Definition at line 1452 of file objects-inl.h.
                                                                               {
  set_map<EmitWriteBarrier::kNo>(isolate, value, kRelaxedStore,
                                 VerificationMode::kSafeMapTransition);
}
References v8::kRelaxedStore, kSafeMapTransition, and v8::internal::value.
set_map_safe_transition_no_write_barrier() [2/2]
void v8::internal::HeapObject::set_map_safe_transition_no_write_barrier (Isolate * isolate, Tagged< Map > value, ReleaseStoreTag tag) [inline]
Definition at line 1459 of file objects-inl.h.
                                                                               {
  set_map<EmitWriteBarrier::kNo>(isolate, value, kReleaseStore,
                                 VerificationMode::kSafeMapTransition);
}
References v8::kReleaseStore, kSafeMapTransition, and v8::internal::value.
set_map_word() [1/2]
void v8::internal::HeapObject::set_map_word (Tagged< Map > map, RelaxedStoreTag) [inline]
Definition at line 1581 of file objects-inl.h.
                                                              {
  MapField::Relaxed_Store_Map_Word(*this, MapWord::FromMap(map));
}
References v8::internal::MapWord::FromMap(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store_Map_Word().
Referenced by set_map(), and set_map_after_allocation().
set_map_word() [2/2]
void v8::internal::HeapObject::set_map_word (Tagged< Map > map, ReleaseStoreTag) [inline]
Definition at line 1604 of file objects-inl.h.
                                                              {
  MapField::Release_Store_Map_Word(*this, MapWord::FromMap(map));
}
References v8::internal::MapWord::FromMap(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store_Map_Word().
set_map_word_forwarded() [1/2]
void v8::internal::HeapObject::set_map_word_forwarded (Tagged< HeapObject > target_object, RelaxedStoreTag) [inline]
Definition at line 1585 of file objects-inl.h.
                                                         {
  MapField::Relaxed_Store_Map_Word(
      *this, MapWord::FromForwardingAddress(*this, target_object));
}
References v8::internal::MapWord::FromForwardingAddress(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store_Map_Word().
set_map_word_forwarded() [2/2]
void v8::internal::HeapObject::set_map_word_forwarded (Tagged< HeapObject > target_object, ReleaseStoreTag) [inline]
Definition at line 1620 of file objects-inl.h.
                                                         {
  MapField::Release_Store_Map_Word(
      *this, MapWord::FromForwardingAddress(*this, target_object));
}
References v8::internal::MapWord::FromForwardingAddress(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store_Map_Word().
SetFillerMap()
void v8::internal::HeapObject::SetFillerMap (const WritableFreeSpace & writable_page, Tagged< Map > value) [inline], [static]
Definition at line 1551 of file objects-inl.h.
                                                 {
  writable_space.WriteHeaderSlot<Map, kMapOffset>(value, kRelaxedStore);
}
References kMapOffset, v8::kRelaxedStore, v8::internal::compiler::Map, v8::internal::value, and v8::internal::WritableFreeSpace::WriteHeaderSlot().
Referenced by v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl().
SetupLazilyInitializedCppHeapPointerField()
void v8::internal::HeapObject::SetupLazilyInitializedCppHeapPointerField (size_t offset) [inline]
Definition at line 1061 of file objects-inl.h.
                                                                        {
  CppHeapPointerSlot(field_address(offset)).init();
}
References field_address(), and v8::internal::CppHeapPointerSlot::init().
SetupLazilyInitializedExternalPointerField()
void v8::internal::HeapObject::SetupLazilyInitializedExternalPointerField (size_t offset) [inline]
Definition at line 1013 of file objects-inl.h.
                                                                         {
#ifdef V8_ENABLE_SANDBOX
  auto location =
      reinterpret_cast<ExternalPointerHandle*>(field_address(offset));
  base::AsAtomic32::Release_Store(location, kNullExternalPointerHandle);
#else
  WriteMaybeUnalignedValue<Address>(field_address(offset), kNullAddress);
#endif // V8_ENABLE_SANDBOX
}
References field_address(), v8::internal::kNullAddress, v8::internal::kNullExternalPointerHandle, and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store().
SizeFromMap()
int v8::internal::HeapObject::SizeFromMap (Tagged< Map > map) const
Definition at line 1943 of file objects.cc.
                                                 {
  int instance_size = map->instance_size();
  if (instance_size != kVariableSizeSentinel) return instance_size;
  // Only inline the most frequent cases.
  InstanceType instance_type = map->instance_type();
  if (base::IsInRange(instance_type, FIRST_FIXED_ARRAY_TYPE,
                      LAST_FIXED_ARRAY_TYPE)) {
    return UncheckedCast<FixedArray>(*this)->AllocatedSize();
  }
#define CASE(TypeCamelCase, TYPE_UPPER_CASE) \
  if (instance_type == TYPE_UPPER_CASE##_TYPE) { \
    return UncheckedCast<TypeCamelCase>(*this)->AllocatedSize(); \
  }
  SIMPLE_HEAP_OBJECT_LIST2(CASE)
#undef CASE
  if (instance_type == SLOPPY_ARGUMENTS_ELEMENTS_TYPE) {
    return UncheckedCast<SloppyArgumentsElements>(*this)->AllocatedSize();
  }
  if (base::IsInRange(instance_type, FIRST_CONTEXT_TYPE, LAST_CONTEXT_TYPE)) {
    if (instance_type == NATIVE_CONTEXT_TYPE) return NativeContext::kSize;
    return Context::SizeFor(UncheckedCast<Context>(*this)->length());
  }
  if (instance_type == SEQ_ONE_BYTE_STRING_TYPE ||
      instance_type == INTERNALIZED_ONE_BYTE_STRING_TYPE ||
      instance_type == SHARED_SEQ_ONE_BYTE_STRING_TYPE) {
    // Strings may get concurrently truncated, hence we have to access its
    // length synchronized.
    return SeqOneByteString::SizeFor(
        UncheckedCast<SeqOneByteString>(*this)->length(kAcquireLoad));
  }
  if (instance_type == BYTECODE_ARRAY_TYPE) {
    return BytecodeArray::SizeFor(
        UncheckedCast<BytecodeArray>(*this)->length(kAcquireLoad));
  }
  if (instance_type == FREE_SPACE_TYPE) {
    return UncheckedCast<FreeSpace>(*this)->size(kRelaxedLoad);
  }
  if (instance_type == SEQ_TWO_BYTE_STRING_TYPE ||
      instance_type == INTERNALIZED_TWO_BYTE_STRING_TYPE ||
      instance_type == SHARED_SEQ_TWO_BYTE_STRING_TYPE) {
    // Strings may get concurrently truncated, hence we have to access its
    // length synchronized.
    return SeqTwoByteString::SizeFor(
        UncheckedCast<SeqTwoByteString>(*this)->length(kAcquireLoad));
  }
  if (instance_type == FIXED_DOUBLE_ARRAY_TYPE) {
    return UncheckedCast<FixedDoubleArray>(*this)->AllocatedSize();
  }
  if (instance_type == TRUSTED_FIXED_ARRAY_TYPE) {
    return UncheckedCast<TrustedFixedArray>(*this)->AllocatedSize();
  }
  if (instance_type == PROTECTED_FIXED_ARRAY_TYPE) {
    return UncheckedCast<ProtectedFixedArray>(*this)->AllocatedSize();
  }
  if (instance_type == PROTECTED_WEAK_FIXED_ARRAY_TYPE) {
    return UncheckedCast<ProtectedWeakFixedArray>(*this)->AllocatedSize();
  }
  if (instance_type == TRUSTED_WEAK_FIXED_ARRAY_TYPE) {
    return UncheckedCast<TrustedWeakFixedArray>(*this)->AllocatedSize();
  }
  if (instance_type == TRUSTED_BYTE_ARRAY_TYPE) {
    return UncheckedCast<TrustedByteArray>(*this)->AllocatedSize();
  }
  if (instance_type == FEEDBACK_METADATA_TYPE) {
    return UncheckedCast<FeedbackMetadata>(*this)->AllocatedSize();
  }
  if (base::IsInRange(instance_type, FIRST_DESCRIPTOR_ARRAY_TYPE,
                      LAST_DESCRIPTOR_ARRAY_TYPE)) {
    return DescriptorArray::SizeFor(
        UncheckedCast<DescriptorArray>(*this)->number_of_all_descriptors());
  }
  if (base::IsInRange(instance_type, FIRST_WEAK_FIXED_ARRAY_TYPE,
                      LAST_WEAK_FIXED_ARRAY_TYPE)) {
    return UncheckedCast<WeakFixedArray>(*this)->AllocatedSize();
  }
  if (instance_type == WEAK_ARRAY_LIST_TYPE) {
    return UncheckedCast<WeakArrayList>(*this)->AllocatedSize();
  }
  if (instance_type == SMALL_ORDERED_HASH_SET_TYPE) {
    return SmallOrderedHashSet::SizeFor(
        UncheckedCast<SmallOrderedHashSet>(*this)->Capacity());
  }
  if (instance_type == SMALL_ORDERED_HASH_MAP_TYPE) {
    return SmallOrderedHashMap::SizeFor(
        UncheckedCast<SmallOrderedHashMap>(*this)->Capacity());
  }
  if (instance_type == SMALL_ORDERED_NAME_DICTIONARY_TYPE) {
    return SmallOrderedNameDictionary::SizeFor(
        UncheckedCast<SmallOrderedNameDictionary>(*this)->Capacity());
  }
  if (instance_type == SWISS_NAME_DICTIONARY_TYPE) {
    return SwissNameDictionary::SizeFor(
        UncheckedCast<SwissNameDictionary>(*this)->Capacity());
  }
  if (instance_type == PROPERTY_ARRAY_TYPE) {
    return PropertyArray::SizeFor(
        UncheckedCast<PropertyArray>(*this)->length(kAcquireLoad));
  }
  if (instance_type == FEEDBACK_VECTOR_TYPE) {
    return FeedbackVector::SizeFor(
        UncheckedCast<FeedbackVector>(*this)->length());
  }
  if (instance_type == BIGINT_TYPE) {
    return BigInt::SizeFor(UncheckedCast<BigInt>(*this)->length());
  }
  if (instance_type == PREPARSE_DATA_TYPE) {
    Tagged<PreparseData> data = UncheckedCast<PreparseData>(*this);
    return PreparseData::SizeFor(data->data_length(), data->children_length());
  }
#define MAKE_TORQUE_SIZE_FOR(TYPE, TypeName) \
  if (instance_type == TYPE) { \
    return UncheckedCast<TypeName>(*this)->AllocatedSize(); \
  }
  TORQUE_INSTANCE_TYPE_TO_BODY_DESCRIPTOR_LIST(MAKE_TORQUE_SIZE_FOR)
#undef MAKE_TORQUE_SIZE_FOR
  if (instance_type == INSTRUCTION_STREAM_TYPE) {
    return UncheckedCast<InstructionStream>(*this)->Size();
  }
  if (instance_type == COVERAGE_INFO_TYPE) {
    return CoverageInfo::SizeFor(
        UncheckedCast<CoverageInfo>(*this)->slot_count());
  }
#if V8_ENABLE_WEBASSEMBLY
  if (instance_type == WASM_TYPE_INFO_TYPE) {
    return WasmTypeInfo::SizeFor(
        UncheckedCast<WasmTypeInfo>(*this)->supertypes_length());
  }
  if (instance_type == WASM_STRUCT_TYPE) {
    return WasmStruct::GcSafeSize(map);
  }
  if (instance_type == WASM_ARRAY_TYPE) {
    return WasmArray::SizeFor(map, UncheckedCast<WasmArray>(*this)->length());
  }
  if (instance_type == WASM_NULL_TYPE) {
    return WasmNull::kSize;
  }
  if (instance_type == WASM_DISPATCH_TABLE_TYPE) {
    return WasmDispatchTable::SizeFor(
        UncheckedCast<WasmDispatchTable>(*this)->capacity());
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (instance_type == DOUBLE_STRING_CACHE_TYPE) {
    return DoubleStringCache::SizeFor(
        UncheckedCast<DoubleStringCache>(*this)->capacity());
  }
  if (instance_type == EMBEDDER_DATA_ARRAY_TYPE) {
    return EmbedderDataArray::SizeFor(
        UncheckedCast<EmbedderDataArray>(*this)->length());
  }
  UNREACHABLE();
}
References v8::internal::BIGINT_TYPE, CASE, v8::internal::WasmStruct::GcSafeSize(), v8::internal::INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::kAcquireLoad, v8::kRelaxedLoad, v8::internal::WasmNull::kSize, v8::internal::kVariableSizeSentinel, MAKE_TORQUE_SIZE_FOR, v8::internal::SEQ_ONE_BYTE_STRING_TYPE, v8::internal::SEQ_TWO_BYTE_STRING_TYPE, v8::internal::SHARED_SEQ_ONE_BYTE_STRING_TYPE, v8::internal::SHARED_SEQ_TWO_BYTE_STRING_TYPE, SIMPLE_HEAP_OBJECT_LIST2, v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::SizeFor(), v8::internal::SmallOrderedHashTable< SmallOrderedHashSet >::SizeFor(), v8::internal::SmallOrderedHashTable< SmallOrderedHashMap >::SizeFor(), v8::internal::SwissNameDictionary::SizeFor(), v8::internal::PreparseData::SizeFor(), v8::internal::BytecodeArray::SizeFor(), v8::internal::Context::SizeFor(), v8::internal::EmbedderDataArray::SizeFor(), v8::internal::DoubleStringCache::SizeFor(), v8::internal::PropertyArray::SizeFor(), v8::internal::WasmDispatchTable::SizeFor(), v8::internal::DescriptorArray::SizeFor(), v8::internal::CoverageInfo::SizeFor(), v8::internal::SeqOneByteString::SizeFor(), v8::internal::SeqTwoByteString::SizeFor(), v8::internal::WasmArray::SizeFor(), v8::internal::BigInt::SizeFor(), and v8::internal::UNREACHABLE().
WriteBoundedSizeField()
void v8::internal::HeapObject::WriteBoundedSizeField (size_t offset, size_t value) [inline]
Definition at line 972 of file objects-inl.h.
                                                                  {
  i::WriteBoundedSizeField(field_address(offset), value);
}
References field_address(), v8::internal::value, and v8::internal::WriteBoundedSizeField().
WriteCodeEntrypointViaCodePointerField()
void v8::internal::HeapObject::WriteCodeEntrypointViaCodePointerField (size_t offset, Address value, CodeEntrypointTag tag) [inline]
Definition at line 1195 of file objects-inl.h.
                                                                               {
  i::WriteCodeEntrypointViaCodePointerField(field_address(offset), value, tag);
}
References field_address(), v8::internal::value, and v8::internal::WriteCodeEntrypointViaCodePointerField().
Referenced by v8::internal::Code::set_instruction_start().
WriteCodePointerField()
void v8::internal::HeapObject::WriteCodePointerField (size_t offset, Tagged< Code > value) [inline]
Definition at line 1178 of file objects-inl.h.
                                                                        {
  WriteTrustedPointerField<kCodeIndirectPointerTag>(offset, value);
}
References v8::internal::value.
WriteExternalPointerField()
template<ExternalPointerTag tag>
void v8::internal::HeapObject::WriteExternalPointerField (size_t offset, IsolateForSandbox isolate, Address value) [inline]
Definition at line 1007 of file objects-inl.h.
                                                          {
  i::WriteExternalPointerField<tag>(field_address(offset), isolate, value);
}
References field_address(), and v8::internal::value.
WriteField()
template<class T >
void v8::internal::HeapObject::WriteField (size_t offset, T value) const [inline]
Definition at line 251 of file heap-object.h.
  {
    return WriteMaybeUnalignedValue<T>(field_address(offset), value);
  }
References v8::internal::value.
Referenced by v8::internal::SwissNameDictionary::SetHash().
WriteLazilyInitializedCppHeapPointerField() [1/2]
template<CppHeapPointerTag tag>
void v8::internal::HeapObject::WriteLazilyInitializedCppHeapPointerField (size_t offset, IsolateForPointerCompression isolate, Address value) [inline]
Definition at line 1066 of file objects-inl.h.
                                                                        {
  i::WriteLazilyInitializedCppHeapPointerField<tag>(field_address(offset),
                                                    isolate, value);
}
References field_address(), and v8::internal::value.
WriteLazilyInitializedCppHeapPointerField() [2/2]
void v8::internal::HeapObject::WriteLazilyInitializedCppHeapPointerField (size_t offset, IsolateForPointerCompression isolate, Address value, CppHeapPointerTag tag) [inline]
Definition at line 1072 of file objects-inl.h.
                           {
  i::WriteLazilyInitializedCppHeapPointerField(field_address(offset), isolate,
                                               value, tag);
}
References field_address(), v8::internal::value, and v8::internal::WriteLazilyInitializedCppHeapPointerField().
WriteLazilyInitializedExternalPointerField()
template<ExternalPointerTag tag>
void v8::internal::HeapObject::WriteLazilyInitializedExternalPointerField (size_t offset, IsolateForSandbox isolate, Address value) [inline]
Definition at line 1037 of file objects-inl.h.
                                                             {
#ifdef V8_ENABLE_SANDBOX
  static_assert(tag != kExternalPointerNullTag);
  ExternalPointerTable& table = isolate.GetExternalPointerTableFor(tag);
  auto location =
      reinterpret_cast<ExternalPointerHandle*>(field_address(offset));
  ExternalPointerHandle handle = base::AsAtomic32::Relaxed_Load(location);
  if (handle == kNullExternalPointerHandle) {
    // Field has not been initialized yet.
    handle = table.AllocateAndInitializeEntry(
        isolate.GetExternalPointerTableSpaceFor(tag, address()), value, tag);
    base::AsAtomic32::Release_Store(location, handle);
    // In this case, we're adding a reference from an existing object to a new
    // table entry, so we always require a write barrier.
    EXTERNAL_POINTER_WRITE_BARRIER(*this, static_cast<int>(offset), tag);
  } else {
    table.Set(handle, value, tag);
  }
#else
  WriteMaybeUnalignedValue<Address>(field_address(offset), value);
#endif // V8_ENABLE_SANDBOX
}
References address(), EXTERNAL_POINTER_WRITE_BARRIER, field_address(), v8::internal::handle(), v8::internal::kExternalPointerNullTag, v8::internal::kNullExternalPointerHandle, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), and v8::internal::value.
WriteSandboxedPointerField() [1/2]
void v8::internal::HeapObject::WriteSandboxedPointerField (size_t offset, Isolate * isolate, Address value) [inline]
Definition at line 962 of file objects-inl.h.
                                                           {
  i::WriteSandboxedPointerField(field_address(offset),
                                PtrComprCageBase(isolate), value);
}
References field_address(), v8::internal::value, and v8::internal::WriteSandboxedPointerField().
WriteSandboxedPointerField() [2/2]
void v8::internal::HeapObject::WriteSandboxedPointerField (size_t offset, PtrComprCageBase cage_base, Address value) [inline]
Definition at line 956 of file objects-inl.h.
                                                           {
  i::WriteSandboxedPointerField(field_address(offset), cage_base, value);
}
References field_address(), v8::internal::value, and v8::internal::WriteSandboxedPointerField().
WriteTrustedPointerField()
template<IndirectPointerTag tag>
void v8::internal::HeapObject::WriteTrustedPointerField (size_t offset, Tagged< ExposedTrustedObject > value) [inline]
Definition at line 1125 of file objects-inl.h.
                                                                              {
  // Currently, trusted pointer stores always use release semantics as the
  // under-the-hood indirect pointer stores use release stores anyway.
#ifdef V8_ENABLE_SANDBOX
  i::WriteIndirectPointerField<tag>(field_address(offset), value,
                                    kReleaseStore);
#else
  TaggedField<ExposedTrustedObject>::Release_Store(
      *this, static_cast<int>(offset), value);
#endif
}
References field_address(), v8::kReleaseStore, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), and v8::internal::value.
Friends And Related Function Documentation
Tagged< HeapObject >
friend class Tagged< HeapObject > [friend]
Definition at line 508 of file heap-object.h.
Member Data Documentation
kHeaderSize
constexpr int v8::internal::HeapObject::kHeaderSize = sizeof(HeapObjectLayout) [static], [constexpr]
Definition at line 499 of file heap-object.h.
Referenced by v8::internal::ScopeInfo::ConvertOffsetToIndex(), v8::internal::FeedbackMetadata::GetCreateClosureParameterCount(), v8::internal::WeakCell::BodyDescriptor::IterateBody(), v8::internal::PrototypeInfo::BodyDescriptor::IterateBody(), v8::internal::AccessorInfo::BodyDescriptor::IterateBody(), v8::internal::InterceptorInfo::BodyDescriptor::IterateBody(), v8::internal::FunctionTemplateInfo::BodyDescriptor::IterateBody(), v8::internal::ScopeInfo::length(), v8::internal::FactoryBase< Impl >::NewFeedbackMetadata(), v8::internal::ScopeInfo::OffsetOfElementAt(), v8::internal::SwissNameDictionary::PrefixOffset(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::FeedbackMetadata::SetCreateClosureParameterCount(), and v8::internal::FeedbackMetadata::SizeFor().
kMapOffset
constexpr int v8::internal::HeapObject::kMapOffset = offsetof(HeapObjectLayout, map_) [static], [constexpr]
Definition at line 498 of file heap-object.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForConsString(), v8::internal::maglev::MaglevGraphBuilder::BuildJSArrayBuiltinMapSwitchOnElementsKind(), v8::internal::maglev::MaglevGraphBuilder::BuildNewConsStringMap(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), v8::internal::compiler::LoadElimination::ComputeLoopStateForStoreField(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::compiler::FieldAccess::FieldAccess(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::Builtins::Generate_CallOrConstructForwardVarargs(), v8::internal::anonymous_namespace{builtins-riscv.cc}::GetContextFromImplicitArg(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::InstructionStream::Initialize(), v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstant(), v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstantMinusTag(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::IsValid(), v8::internal::V8HeapExplorer::IterateAndExtractReferences(), v8::internal::BodyDescriptorBase::IterateMaybeWeakPointer(), v8::internal::BodyDescriptorBase::IteratePointer(), v8::internal::BodyDescriptorBase::IteratePointers(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::CodeStubAssembler::LoadAndUntagToWord32ObjectField(), v8::internal::MacroAssembler::LoadCompressedMap(), v8::internal::MacroAssembler::LoadFeedbackVector(), v8::internal::compiler::GraphAssembler::LoadMap(), v8::internal::compiler::WasmGraphAssembler::LoadMap(), v8::internal::MacroAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessStore(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::compiler::TypedOptimization::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::LoadElimination::ReduceStoreField(), SetFillerMap(), v8::internal::maglev::MaglevAssembler::SetMapAsRoot(), v8::internal::compiler::WasmGraphAssembler::StoreMap(), v8::internal::CodeStubAssembler::StoreObjectField(), v8::internal::CodeStubAssembler::StoreObjectFieldRoot(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildGetKeyedPropertyWithEnumeratedKey(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreTaggedFieldToAllocation(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), v8::internal::CodeStubAssembler::UnsafeStoreObjectFieldNoWriteBarrier(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::VisitMapPointer(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitMapPointer(), v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitMapPointer(), v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor(), v8::internal::WritableJitAllocation::WriteHeaderSlot(), v8::internal::WritableFreeSpace::WriteHeaderSlot(), and v8::internal::WritableJitAllocation::WriteProtectedPointerHeaderSlot().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/heap-object.h
/mnt/V8SourceCode/src/diagnostics/objects-printer.cc
/mnt/V8SourceCode/src/objects/objects-inl.h
/mnt/V8SourceCode/src/objects/objects.cc