v8::internal::ElementsAccessor Class Reference
#include <elements.h>
Public Member Functions
ElementsAccessor ()=default
virtual ~ElementsAccessor ()=default
ElementsAccessor (const ElementsAccessor &)=delete
ElementsAccessor & operator= (const ElementsAccessor &)=delete
virtual void Validate (Isolate *isolate, Tagged< JSObject > obj)=0
virtual bool HasElement (Isolate *isolate, Tagged< JSObject > holder, uint32_t index, Tagged< FixedArrayBase > backing_store, PropertyFilter filter=ALL_PROPERTIES)=0
bool HasElement (Isolate *isolate, Tagged< JSObject > holder, uint32_t index, PropertyFilter filter=ALL_PROPERTIES)
virtual bool HasEntry (Isolate *isolate, Tagged< JSObject > holder, InternalIndex entry)=0
virtual Handle< Object > Get (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry)=0
virtual Handle< Object > GetAtomic (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry, SeqCstAccessTag tag)=0
virtual bool HasAccessors (Tagged< JSObject > holder)=0
virtual size_t NumberOfElements (Isolate *isolate, Tagged< JSObject > holder)=0
virtual V8_WARN_UNUSED_RESULT Maybe< bool > SetLength (Isolate *isolate, DirectHandle< JSArray > holder, uint32_t new_length)=0
virtual V8_WARN_UNUSED_RESULT ExceptionStatus CollectElementIndices (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator *keys)=0
V8_WARN_UNUSED_RESULT ExceptionStatus CollectElementIndices (DirectHandle< JSObject > object, KeyAccumulator *keys)
virtual Maybe< bool > CollectValuesOrEntries (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int *nof_items, PropertyFilter filter=ALL_PROPERTIES)=0
virtual MaybeHandle< FixedArray > PrependElementIndices (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, DirectHandle< FixedArray > keys, GetKeysConversion convert, PropertyFilter filter=ALL_PROPERTIES)=0
MaybeHandle< FixedArray > PrependElementIndices (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > keys, GetKeysConversion convert, PropertyFilter filter=ALL_PROPERTIES)
virtual V8_WARN_UNUSED_RESULT ExceptionStatus AddElementsToKeyAccumulator (DirectHandle< JSObject > receiver, KeyAccumulator *accumulator, AddKeyConversion convert)=0
virtual void TransitionElementsKind (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > map)=0
virtual V8_WARN_UNUSED_RESULT Maybe< bool > GrowCapacityAndConvert (Isolate *isolate, DirectHandle< JSObject > object, uint32_t capacity)=0
virtual V8_WARN_UNUSED_RESULT Maybe< bool > GrowCapacity (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index)=0
virtual void Set (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value)=0
virtual void SetAtomic (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag)=0
virtual Handle< Object > SwapAtomic (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag)=0
virtual Handle< Object > CompareAndSwapAtomic (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)=0
virtual V8_WARN_UNUSED_RESULT Maybe< bool > Add (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)=0
virtual V8_WARN_UNUSED_RESULT Maybe< uint32_t > Push (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t push_size)=0
virtual V8_WARN_UNUSED_RESULT Maybe< uint32_t > Unshift (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t unshift_size)=0
virtual Tagged< Object > Pop (Isolate *isolate, DirectHandle< JSArray > receiver)=0
virtual Tagged< Object > Shift (Isolate *isolate, DirectHandle< JSArray > receiver)=0
virtual DirectHandle< NumberDictionary > Normalize (Isolate *isolate, DirectHandle< JSObject > object)=0
virtual size_t GetCapacity (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store)=0
virtual V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Fill (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > obj_value, size_t start, size_t end)=0
virtual Maybe< bool > IncludesValue (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start, size_t length)=0
virtual Maybe< int64_t > IndexOfValue (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start, size_t length)=0
virtual Maybe< int64_t > LastIndexOfValue (DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start)=0
virtual void Reverse (Tagged< JSObject > receiver)=0
virtual void CopyElements (Isolate *isolate, DirectHandle< FixedArrayBase > source, ElementsKind source_kind, DirectHandle< FixedArrayBase > destination, int size)=0
virtual Tagged< Object > CopyElements (Isolate *isolate, DirectHandle< JSAny > source, DirectHandle< JSObject > destination, size_t length, size_t offset)=0
virtual Handle< FixedArray > CreateListFromArrayLike (Isolate *isolate, DirectHandle< JSObject > object, uint32_t length)=0
virtual void CopyTypedArrayElementsSlice (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t start, size_t end)=0
Static Public Member Functions
static ElementsAccessor * ForKind (ElementsKind elements_kind)
static void InitializeOncePerProcess ()
static void TearDown ()
static DirectHandle< JSArray > Concat (Isolate *isolate, BuiltinArguments *args, uint32_t concat_size, uint32_t result_length)
Protected Member Functions
virtual InternalIndex GetEntryForIndex (Isolate *isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index)=0
virtual PropertyDetails GetDetails (Tagged< JSObject > holder, InternalIndex entry)=0
virtual void Reconfigure (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes)=0
virtual void Delete (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry)=0
virtual void CopyElements (Isolate *isolate, Tagged< JSObject > source_holder, uint32_t source_start, ElementsKind source_kind, DirectHandle< FixedArrayBase > destination, uint32_t destination_start, int copy_size)=0
Static Private Attributes
static V8_EXPORT_PRIVATE ElementsAccessor ** elements_accessors_ = nullptr
Friends
class LookupIterator
Detailed Description
Definition at line 21 of file elements.h.
Constructor & Destructor Documentation
ElementsAccessor() [1/2]
v8::internal::ElementsAccessor::ElementsAccessor () [default]
 ElementsAccessor()
virtual v8::internal::ElementsAccessor::~ElementsAccessor () [virtual], [default]
ElementsAccessor() [2/2]
v8::internal::ElementsAccessor::ElementsAccessor (const ElementsAccessor &) [delete]
Member Function Documentation
Add()
virtual V8_WARN_UNUSED_RESULT Maybe<bool> v8::internal::ElementsAccessor::Add (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::JSObject::AddDataElement().
AddElementsToKeyAccumulator()
virtual V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::ElementsAccessor::AddElementsToKeyAccumulator (DirectHandle< JSObject > receiver, KeyAccumulator * accumulator, AddKeyConversion convert) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::KeyAccumulator::AddKeys().
CollectElementIndices() [1/2]
virtual V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::ElementsAccessor::CollectElementIndices (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator * keys) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by CollectElementIndices(), and v8::internal::KeyAccumulator::CollectOwnElementIndices().
CollectElementIndices() [2/2]
V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::ElementsAccessor::CollectElementIndices (DirectHandle< JSObject > object, KeyAccumulator * keys) [inline]
Definition at line 19 of file elements-inl.h.
                                                              {
  return CollectElementIndices(
      object, direct_handle(object->elements(), keys->isolate()), keys);
}
References CollectElementIndices(), v8::internal::direct_handle(), and v8::internal::KeyAccumulator::isolate().
CollectValuesOrEntries()
virtual Maybe<bool> v8::internal::ElementsAccessor::CollectValuesOrEntries (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int * nof_items, PropertyFilter filter = ALL_PROPERTIES) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
CompareAndSwapAtomic()
virtual Handle<Object> v8::internal::ElementsAccessor::CompareAndSwapAtomic (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::CompareAndSwapDataValue().
Concat()
DirectHandle< JSArray > v8::internal::ElementsAccessor::Concat (Isolate * isolate, BuiltinArguments * args, uint32_t concat_size, uint32_t result_length) [static]
Definition at line 5873 of file elements.cc.
                                                                    {
  ElementsKind result_elements_kind = GetInitialFastElementsKind();
  bool has_raw_doubles = false;
  {
    DisallowGarbageCollection no_gc;
    bool is_holey = false;
    for (uint32_t i = 0; i < concat_size; i++) {
      Tagged<Object> arg = (*args)[i];
      ElementsKind arg_kind = Cast<JSArray>(arg)->GetElementsKind();
      has_raw_doubles = has_raw_doubles || IsDoubleElementsKind(arg_kind);
      is_holey = is_holey || IsHoleyElementsKind(arg_kind);
      result_elements_kind =
          GetMoreGeneralElementsKind(result_elements_kind, arg_kind);
    }
    if (is_holey) {
      result_elements_kind = GetHoleyElementsKind(result_elements_kind);
    }
  }
  // If a double array is concatted into a fast elements array, the fast
  // elements array needs to be initialized to contain proper holes, since
  // boxing doubles may cause incremental marking.
  bool requires_double_boxing =
      has_raw_doubles && !IsDoubleElementsKind(result_elements_kind);
  auto mode =
      requires_double_boxing
          ? ArrayStorageAllocationMode::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE
          : ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS;
  DirectHandle<JSArray> result_array = isolate->factory()->NewJSArray(
      result_elements_kind, result_len, result_len, mode);
  if (result_len == 0) return result_array;
  uint32_t insertion_index = 0;
  DirectHandle<FixedArrayBase> storage(result_array->elements(), isolate);
  ElementsAccessor* accessor = ElementsAccessor::ForKind(result_elements_kind);
  for (uint32_t i = 0; i < concat_size; i++) {
    // It is crucial to keep |array| in a raw pointer form to avoid
    // performance degradation.
    Tagged<JSArray> array = Cast<JSArray>((*args)[i]);
    uint32_t len = 0;
    Object::ToArrayLength(array->length(), &len);
    if (len == 0) continue;
    ElementsKind from_kind = array->GetElementsKind();
    accessor->CopyElements(isolate, array, 0, from_kind, storage,
                           insertion_index, len);
    insertion_index += len;
  }
  DCHECK_EQ(insertion_index, result_len);
  return result_array;
}
References v8::base::args, CopyElements(), DCHECK_EQ, v8::internal::DONT_INITIALIZE_ARRAY_ELEMENTS, v8::internal::Isolate::factory(), ForKind(), v8::internal::GetHoleyElementsKind(), v8::internal::GetInitialFastElementsKind(), v8::internal::GetMoreGeneralElementsKind(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE, v8::internal::IsDoubleElementsKind(), v8::internal::IsHoleyElementsKind(), mode(), v8::internal::Factory::NewJSArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Object::ToArrayLength().
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::Fast_ArrayConcat().
CopyElements() [1/3]
virtual void v8::internal::ElementsAccessor::CopyElements (Isolate * isolate, DirectHandle< FixedArrayBase > source, ElementsKind source_kind, DirectHandle< FixedArrayBase > destination, int size) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by Concat(), and v8::internal::RUNTIME_FUNCTION().
CopyElements() [2/3]
virtual Tagged<Object> v8::internal::ElementsAccessor::CopyElements (Isolate * isolate, DirectHandle< JSAny > source, DirectHandle< JSObject > destination, size_t length, size_t offset) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
CopyElements() [3/3]
virtual void v8::internal::ElementsAccessor::CopyElements (Isolate * isolate, Tagged< JSObject > source_holder, uint32_t source_start, ElementsKind source_kind, DirectHandle< FixedArrayBase > destination, uint32_t destination_start, int copy_size) [protected], [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
CopyTypedArrayElementsSlice()
virtual void v8::internal::ElementsAccessor::CopyTypedArrayElementsSlice (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t start, size_t end) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
CreateListFromArrayLike()
virtual Handle<FixedArray> v8::internal::ElementsAccessor::CreateListFromArrayLike (Isolate * isolate, DirectHandle< JSObject > object, uint32_t length) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Delete()
virtual void v8::internal::ElementsAccessor::Delete (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry) [protected], [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::Delete().
Fill()
virtual V8_WARN_UNUSED_RESULT MaybeDirectHandle<Object> v8::internal::ElementsAccessor::Fill (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > obj_value, size_t start, size_t end) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill().
ForKind()
static ElementsAccessor* v8::internal::ElementsAccessor::ForKind (ElementsKind elements_kind) [inline], [static]
Definition at line 29 of file elements.h.
                                                               {
    DCHECK_LT(static_cast<int>(elements_kind), kElementsKindCount);
    return elements_accessors_[elements_kind];
  }
References DCHECK_LT, elements_accessors_, and v8::internal::kElementsKindCount.
Referenced by v8::internal::JSObject::AddDataElement(), v8::internal::BUILTIN(), Concat(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{js-objects.cc}::TestElementsIntegrityLevel(), and v8::internal::JSObject::TransitionElementsKind().
Get()
virtual Handle<Object> v8::internal::ElementsAccessor::Get (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::FetchValue(), and v8::internal::KeyAccumulator::FilterForEnumerableProperties().
GetAtomic()
virtual Handle<Object> v8::internal::ElementsAccessor::GetAtomic (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry, SeqCstAccessTag tag) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::GetDataValue().
GetCapacity()
virtual size_t v8::internal::ElementsAccessor::GetCapacity (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::KeyAccumulator::FilterForEnumerableProperties().
GetDetails()
virtual PropertyDetails v8::internal::ElementsAccessor::GetDetails (Tagged< JSObject > holder, InternalIndex entry) [protected], [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::InternalElementsAccessor, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::LookupInRegularHolder(), and v8::internal::LookupIterator::RecheckTypedArrayBounds().
GetEntryForIndex()
virtual InternalIndex v8::internal::ElementsAccessor::GetEntryForIndex (Isolate * isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index) [protected], [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::InternalElementsAccessor, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::LookupInRegularHolder(), and v8::internal::LookupIterator::RecheckTypedArrayBounds().
GrowCapacity()
virtual V8_WARN_UNUSED_RESULT Maybe<bool> v8::internal::ElementsAccessor::GrowCapacity (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
GrowCapacityAndConvert()
virtual V8_WARN_UNUSED_RESULT Maybe<bool> v8::internal::ElementsAccessor::GrowCapacityAndConvert (Isolate * isolate, DirectHandle< JSObject > object, uint32_t capacity) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::JSObject::TransitionElementsKind().
HasAccessors()
virtual bool v8::internal::ElementsAccessor::HasAccessors (Tagged< JSObject > holder) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
HasElement() [1/2]
bool v8::internal::ElementsAccessor::HasElement (Isolate * isolate, Tagged< JSObject > holder, uint32_t index, PropertyFilter filter = ALL_PROPERTIES) [inline]
Definition at line 34 of file elements-inl.h.
                                                                {
  return HasElement(isolate, holder, index, holder->elements(), filter);
}
References HasElement(), and v8::internal::index.
HasElement() [2/2]
virtual bool v8::internal::ElementsAccessor::HasElement (Isolate * isolate, Tagged< JSObject > holder, uint32_t index, Tagged< FixedArrayBase > backing_store, PropertyFilter filter = ALL_PROPERTIES) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::CollectElementIndices(), and HasElement().
HasEntry()
virtual bool v8::internal::ElementsAccessor::HasEntry (Isolate * isolate, Tagged< JSObject > holder, InternalIndex entry) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::KeyAccumulator::FilterForEnumerableProperties().
IncludesValue()
virtual Maybe<bool> v8::internal::ElementsAccessor::IncludesValue (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start, size_t length) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), and v8::internal::RUNTIME_FUNCTION().
IndexOfValue()
virtual Maybe<int64_t> v8::internal::ElementsAccessor::IndexOfValue (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start, size_t length) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::BUILTIN(), and v8::internal::RUNTIME_FUNCTION().
InitializeOncePerProcess()
void v8::internal::ElementsAccessor::InitializeOncePerProcess () [static]
Definition at line 5836 of file elements.cc.
                                                {
  // Here we create an array with more entries than element kinds.
  // This is due to the sandbox: this array is indexed with an ElementsKind
  // read directly from within the sandbox, which must therefore be considered
  // attacker-controlled. An ElementsKind is a uint8_t under the hood, so we
  // can either use an array with 256 entries or have an explicit bounds-check
  // on access. The latter is probably more expensive.
  static_assert(std::is_same_v<std::underlying_type_t<ElementsKind>, uint8_t>);
  static ElementsAccessor* accessor_array[256] = {
#define ACCESSOR_ARRAY(Class, Kind, Store) new Class(),
      ELEMENTS_LIST(ACCESSOR_ARRAY)
#undef ACCESSOR_ARRAY
  };
  static_assert((sizeof(accessor_array) / sizeof(*accessor_array)) >=
                kElementsKindCount);
  // Check that the ELEMENTS_LIST macro is in the same order as the ElementsKind
  // enum.
  constexpr ElementsKind elements_kinds_from_macro[] = {
#define ACCESSOR_KIND(Class, Kind, Store) Kind,
      ELEMENTS_LIST(ACCESSOR_KIND)
#undef ACCESSOR_KIND
  };
  static_assert(IsIdentityMapping(elements_kinds_from_macro, 0));
  elements_accessors_ = accessor_array;
}
References ACCESSOR_ARRAY, ACCESSOR_KIND, elements_accessors_, ELEMENTS_LIST, v8::internal::IsIdentityMapping(), and v8::internal::kElementsKindCount.
Referenced by v8::internal::V8::Initialize().
LastIndexOfValue()
virtual Maybe<int64_t> v8::internal::ElementsAccessor::LastIndexOfValue (DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::BUILTIN().
Normalize()
virtual DirectHandle<NumberDictionary> v8::internal::ElementsAccessor::Normalize (Isolate * isolate, DirectHandle< JSObject > object) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
NumberOfElements()
virtual size_t v8::internal::ElementsAccessor::NumberOfElements (Isolate * isolate, Tagged< JSObject > holder) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::TestElementsIntegrityLevel().
operator=()
ElementsAccessor& v8::internal::ElementsAccessor::operator= (const ElementsAccessor &) [delete]
Pop()
virtual Tagged<Object> v8::internal::ElementsAccessor::Pop (Isolate * isolate, DirectHandle< JSArray > receiver) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::BUILTIN().
PrependElementIndices() [1/2]
MaybeHandle< FixedArray > v8::internal::ElementsAccessor::PrependElementIndices (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > keys, GetKeysConversion convert, PropertyFilter filter = ALL_PROPERTIES) [inline]
Definition at line 25 of file elements-inl.h.
                           {
  return PrependElementIndices(isolate, object,
                               direct_handle(object->elements(), isolate), keys,
                               convert, filter);
}
References v8::internal::direct_handle(), and PrependElementIndices().
PrependElementIndices() [2/2]
virtual MaybeHandle<FixedArray> v8::internal::ElementsAccessor::PrependElementIndices (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, DirectHandle< FixedArray > keys, GetKeysConversion convert, PropertyFilter filter = ALL_PROPERTIES) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::anonymous_namespace{keys.cc}::GetOwnKeysWithElements(), and PrependElementIndices().
Push()
virtual V8_WARN_UNUSED_RESULT Maybe<uint32_t> v8::internal::ElementsAccessor::Push (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t push_size) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::BUILTIN().
Reconfigure()
virtual void v8::internal::ElementsAccessor::Reconfigure (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [protected], [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Reverse()
virtual void v8::internal::ElementsAccessor::Reverse (Tagged< JSObject > receiver) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::BUILTIN().
Set()
virtual void v8::internal::ElementsAccessor::Set (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::WriteDataValue().
SetAtomic()
virtual void v8::internal::ElementsAccessor::SetAtomic (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::WriteDataValue().
SetLength()
virtual V8_WARN_UNUSED_RESULT Maybe<bool> v8::internal::ElementsAccessor::SetLength (Isolate * isolate, DirectHandle< JSArray > holder, uint32_t new_length) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill().
Shift()
virtual Tagged<Object> v8::internal::ElementsAccessor::Shift (Isolate * isolate, DirectHandle< JSArray > receiver) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::BUILTIN().
SwapAtomic()
virtual Handle<Object> v8::internal::ElementsAccessor::SwapAtomic (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::LookupIterator::SwapDataValue().
TearDown()
void v8::internal::ElementsAccessor::TearDown () [static]
Definition at line 5865 of file elements.cc.
                                {
  if (elements_accessors_ == nullptr) return;
#define ACCESSOR_DELETE(Class, Kind, Store) delete elements_accessors_[Kind];
  ELEMENTS_LIST(ACCESSOR_DELETE)
#undef ACCESSOR_DELETE
  elements_accessors_ = nullptr;
}
References ACCESSOR_DELETE, elements_accessors_, and ELEMENTS_LIST.
Referenced by v8::internal::V8::Dispose().
TransitionElementsKind()
virtual void v8::internal::ElementsAccessor::TransitionElementsKind (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > map) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::RUNTIME_FUNCTION().
Unshift()
virtual V8_WARN_UNUSED_RESULT Maybe<uint32_t> v8::internal::ElementsAccessor::Unshift (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t unshift_size) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Referenced by v8::internal::BUILTIN().
Validate()
virtual void v8::internal::ElementsAccessor::Validate (Isolate * isolate, Tagged< JSObject > obj) [pure virtual]
Implemented in v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, KindTraits >, v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< TypedElementsAccessor< Kind, ElementType >, ElementsKindTraits< Kind > >, and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< DictionaryElementsAccessor, ElementsKindTraits< DICTIONARY_ELEMENTS > >.
Friends And Related Function Documentation
LookupIterator
friend class LookupIterator [friend]
Definition at line 218 of file elements.h.
Member Data Documentation
elements_accessors_
ElementsAccessor ** v8::internal::ElementsAccessor::elements_accessors_ = nullptr [static], [private]
Definition at line 254 of file elements.h.
Referenced by ForKind(), InitializeOncePerProcess(), and TearDown().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/elements.h
/mnt/V8SourceCode/src/objects/elements-inl.h
/mnt/V8SourceCode/src/objects/elements.cc