v8::internal::compiler::StoreGlobalParameters Class Reference
#include <js-operator.h>
Public Member Functions
StoreGlobalParameters (LanguageMode language_mode, const FeedbackSource &feedback, NameRef name)
LanguageMode language_mode () const
FeedbackSource const & feedback () const
NameRef name () const
Private Attributes
LanguageMode const language_mode_
const NameRef name_
FeedbackSource const feedback_
Friends
bool operator== (StoreGlobalParameters const &, StoreGlobalParameters const &)
bool operator!= (StoreGlobalParameters const &, StoreGlobalParameters const &)
size_t hash_value (StoreGlobalParameters const &)
std::ostream & operator<< (std::ostream &, StoreGlobalParameters const &)
Detailed Description
Definition at line 505 of file js-operator.h.
Constructor & Destructor Documentation
StoreGlobalParameters()
v8::internal::compiler::StoreGlobalParameters::StoreGlobalParameters (LanguageMode language_mode, const FeedbackSource & feedback, NameRef name) [inline]
Definition at line 507 of file js-operator.h.
      : language_mode_(language_mode), name_(name), feedback_(feedback) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::StoreGlobalParameters::feedback () const [inline]
Definition at line 512 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal().
language_mode()
LanguageMode v8::internal::compiler::StoreGlobalParameters::language_mode () const [inline]
Definition at line 511 of file js-operator.h.
{ return language_mode_; }
References language_mode_.
name()
NameRef v8::internal::compiler::StoreGlobalParameters::name () const [inline]
Definition at line 513 of file js-operator.h.
{ return name_; }
References name_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal().
Friends And Related Function Documentation
hash_value
size_t hash_value (StoreGlobalParameters const & p) [friend]
Definition at line 385 of file js-operator.cc.
                                                  {
  return base::hash_combine(p.language_mode(), p.name_.object().location(),
                            FeedbackSource::Hash()(p.feedback()));
}
operator!=
bool operator!= (StoreGlobalParameters const & lhs, StoreGlobalParameters const & rhs) [friend]
Definition at line 379 of file js-operator.cc.
                                                  {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, StoreGlobalParameters const & p) [friend]
Definition at line 391 of file js-operator.cc.
                                                                       {
  return os << p.language_mode() << ", " << Brief(*p.name_.object());
}
operator==
bool operator== (StoreGlobalParameters const & lhs, StoreGlobalParameters const & rhs) [friend]
Definition at line 371 of file js-operator.cc.
                                                  {
  return lhs.language_mode() == rhs.language_mode() &&
         lhs.name_.object().location() == rhs.name_.object().location() &&
         lhs.feedback() == rhs.feedback();
}
Member Data Documentation
feedback_
FeedbackSource const v8::internal::compiler::StoreGlobalParameters::feedback_ [private]
Definition at line 518 of file js-operator.h.
Referenced by feedback().
language_mode_
LanguageMode const v8::internal::compiler::StoreGlobalParameters::language_mode_ [private]
Definition at line 516 of file js-operator.h.
Referenced by language_mode().
name_
const NameRef v8::internal::compiler::StoreGlobalParameters::name_ [private]
Definition at line 517 of file js-operator.h.
Referenced by name().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h