v8::internal::RegExpClassSetExpression Class Reference
#include <regexp-ast.h>
Public Types
enum class OperationType { kUnion
, kIntersection
, kSubtraction
 }
Public Member Functions
RegExpClassSetExpression (OperationType op, bool is_negated, bool may_contain_strings, ZoneList< RegExpTree * > *operands)
DECL_BOILERPLATE (ClassSetExpression)
bool IsTextElement () override
int min_match () override
int max_match () override
OperationType operation () const
bool is_negated () const
bool may_contain_strings () const
const ZoneList< RegExpTree * > * operands () const
ZoneList< RegExpTree * > * operands ()
Static Public Member Functions
static RegExpClassSetExpression * Empty (Zone *zone, bool is_negated)
Static Private Member Functions
static RegExpClassSetOperand * ComputeExpression (RegExpTree *root, ZoneList< CharacterRange > *temp_ranges, Zone *zone)
Private Attributes
const OperationType operation_
bool is_negated_
const bool may_contain_strings_
ZoneList< RegExpTree * > * operands_ = nullptr
int max_match_
Additional Inherited Members
Detailed Description
Definition at line 429 of file regexp-ast.h.
Member Enumeration Documentation
OperationType
enum v8::internal::RegExpClassSetExpression::OperationType [strong]
Enumerator
kUnion
kIntersection
kSubtraction
Definition at line 431 of file regexp-ast.h.
{ kUnion, kIntersection, kSubtraction };
Constructor & Destructor Documentation
RegExpClassSetExpression()
v8::internal::RegExpClassSetExpression::RegExpClassSetExpression (OperationType op, bool is_negated, bool may_contain_strings, ZoneList< RegExpTree * > * operands)
Definition at line 407 of file regexp-ast.cc.
    : operation_(op),
      is_negated_(is_negated),
      may_contain_strings_(may_contain_strings),
      operands_(operands) {
  DCHECK_NOT_NULL(operands);
  if (is_negated) {
    DCHECK(!may_contain_strings_);
    // We don't know anything about max matches for negated classes.
    // As there are no strings involved, assume that we can match a unicode
    // character (2 code points).
    max_match_ = 2;
  } else {
    max_match_ = 0;
    for (auto operand : *operands) {
      max_match_ = std::max(max_match_, operand->max_match());
    }
  }
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, is_negated(), max_match_, may_contain_strings_, and operands().
Member Function Documentation
ComputeExpression()
RegExpClassSetOperand * v8::internal::RegExpClassSetExpression::ComputeExpression (RegExpTree * root, ZoneList< CharacterRange > * temp_ranges, Zone * zone) [static], [private]
Definition at line 632 of file regexp-compiler-tonode.cc.
                                                                         {
  DCHECK(temp_ranges->is_empty());
  if (root->IsClassSetOperand()) {
    return root->AsClassSetOperand();
  }
  DCHECK(root->IsClassSetExpression());
  RegExpClassSetExpression* node = root->AsClassSetExpression();
  RegExpClassSetOperand* result =
      ComputeExpression(node->operands()->at(0), temp_ranges, zone);
  switch (node->operation()) {
    case OperationType::kUnion: {
      for (int i = 1; i < node->operands()->length(); i++) {
        RegExpClassSetOperand* op =
            ComputeExpression(node->operands()->at(i), temp_ranges, zone);
        result->Union(op, zone);
      }
      CharacterRange::Canonicalize(result->ranges());
      break;
    }
    case OperationType::kIntersection: {
      for (int i = 1; i < node->operands()->length(); i++) {
        RegExpClassSetOperand* op =
            ComputeExpression(node->operands()->at(i), temp_ranges, zone);
        result->Intersect(op, temp_ranges, zone);
      }
      break;
    }
    case OperationType::kSubtraction: {
      for (int i = 1; i < node->operands()->length(); i++) {
        RegExpClassSetOperand* op =
            ComputeExpression(node->operands()->at(i), temp_ranges, zone);
        result->Subtract(op, temp_ranges, zone);
      }
      break;
    }
  }
  if (node->is_negated()) {
    DCHECK(!result->has_strings());
    CharacterRange::Negate(result->ranges(), temp_ranges, zone);
    std::swap(*result->ranges(), *temp_ranges);
    temp_ranges->Rewind(0);
    node->is_negated_ = false;
  }
  // Store the result as single operand of the current node.
  node->operands()->Set(0, result);
  node->operands()->Rewind(1);
  return result;
}
References v8::internal::CharacterRange::Canonicalize(), v8::internal::DCHECK(), v8::internal::ZoneList< T >::is_empty(), is_negated(), is_negated_, v8::internal::length, v8::internal::CharacterRange::Negate(), operands(), operation(), v8::base::internal::result, and v8::internal::ZoneList< T >::Rewind().
DECL_BOILERPLATE()
v8::internal::RegExpClassSetExpression::DECL_BOILERPLATE (ClassSetExpression)
Empty()
RegExpClassSetExpression * v8::internal::RegExpClassSetExpression::Empty (Zone * zone, bool is_negated) [static]
Definition at line 430 of file regexp-ast.cc.
                                                                           {
  ZoneList<CharacterRange>* ranges =
      zone->template New<ZoneList<CharacterRange>>(0, zone);
  RegExpClassSetOperand* op =
      zone->template New<RegExpClassSetOperand>(ranges, nullptr);
  ZoneList<RegExpTree*>* operands =
      zone->template New<ZoneList<RegExpTree*>>(1, zone);
  operands->Add(op, zone);
  return zone->template New<RegExpClassSetExpression>(
      RegExpClassSetExpression::OperationType::kUnion, is_negated, false,
      operands);
}
References is_negated(), kUnion, and operands().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCharacterClass(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion().
is_negated()
bool v8::internal::RegExpClassSetExpression::is_negated () const [inline]
Definition at line 448 of file regexp-ast.h.
{ return is_negated_; }
References is_negated_.
Referenced by ComputeExpression(), Empty(), and RegExpClassSetExpression().
IsTextElement()
bool v8::internal::RegExpClassSetExpression::IsTextElement () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 443 of file regexp-ast.h.
{ return true; }
max_match()
int v8::internal::RegExpClassSetExpression::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 445 of file regexp-ast.h.
{ return max_match_; }
References max_match_.
may_contain_strings()
bool v8::internal::RegExpClassSetExpression::may_contain_strings () const [inline]
Definition at line 449 of file regexp-ast.h.
{ return may_contain_strings_; }
References may_contain_strings_.
min_match()
int v8::internal::RegExpClassSetExpression::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 444 of file regexp-ast.h.
{ return 0; }
operands() [1/2]
ZoneList<RegExpTree*>* v8::internal::RegExpClassSetExpression::operands () [inline]
Definition at line 451 of file regexp-ast.h.
{ return operands_; }
References operands_.
operands() [2/2]
const ZoneList<RegExpTree*>* v8::internal::RegExpClassSetExpression::operands () const [inline]
Definition at line 450 of file regexp-ast.h.
{ return operands_; }
References operands_.
Referenced by ComputeExpression(), Empty(), and RegExpClassSetExpression().
operation()
OperationType v8::internal::RegExpClassSetExpression::operation () const [inline]
Definition at line 447 of file regexp-ast.h.
{ return operation_; }
References operation_.
Referenced by ComputeExpression().
Member Data Documentation
is_negated_
bool v8::internal::RegExpClassSetExpression::is_negated_ [private]
Definition at line 466 of file regexp-ast.h.
Referenced by ComputeExpression(), and is_negated().
max_match_
int v8::internal::RegExpClassSetExpression::max_match_ [private]
Definition at line 469 of file regexp-ast.h.
Referenced by max_match(), and RegExpClassSetExpression().
may_contain_strings_
const bool v8::internal::RegExpClassSetExpression::may_contain_strings_ [private]
Definition at line 467 of file regexp-ast.h.
Referenced by may_contain_strings(), and RegExpClassSetExpression().
operands_
ZoneList<RegExpTree*>* v8::internal::RegExpClassSetExpression::operands_ = nullptr [private]
Definition at line 468 of file regexp-ast.h.
Referenced by operands().
operation_
const OperationType v8::internal::RegExpClassSetExpression::operation_ [private]
Definition at line 465 of file regexp-ast.h.
Referenced by operation().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc