cppgc::internal::MarkerBase::IncrementalMarkingTask Class Reference
Public Types
using Handle = SingleThreadedHandle
Public Member Functions
IncrementalMarkingTask (MarkerBase *, StackState)
Static Public Member Functions
static Handle Post (cppgc::TaskRunner *, MarkerBase *)
Private Member Functions
void Run () final
Private Attributes
MarkerBase *const marker_
StackState stack_state_
Handle handle_
Detailed Description
Definition at line 92 of file marker.cc.
Member Typedef Documentation
Handle
using cppgc::internal::MarkerBase::IncrementalMarkingTask::Handle = SingleThreadedHandle
Definition at line 94 of file marker.cc.
Constructor & Destructor Documentation
IncrementalMarkingTask()
cppgc::internal::MarkerBase::IncrementalMarkingTask::IncrementalMarkingTask (MarkerBase * marker, StackState stack_state)
Definition at line 109 of file marker.cc.
    : marker_(marker),
      stack_state_(stack_state),
      handle_(Handle::NonEmptyTag{}) {}
Member Function Documentation
Post()
MarkerBase::IncrementalMarkingTask::Handle cppgc::internal::MarkerBase::IncrementalMarkingTask::Post (cppgc::TaskRunner * runner, MarkerBase * marker) [static]
Definition at line 117 of file marker.cc.
                                                             {
  // Incremental GC is possible only via the GCInvoker, so getting here
  // guarantees that either non-nestable tasks or conservative stack
  // scanning are supported. This is required so that the incremental
  // task can safely finalize GC if needed.
  DCHECK_IMPLIES(marker->heap().stack_support() !=
                     HeapBase::StackSupport::kSupportsConservativeStackScan,
                 runner->NonNestableTasksEnabled());
  const bool non_nestable_tasks_enabled = runner->NonNestableTasksEnabled();
  auto task = std::make_unique<IncrementalMarkingTask>(
      marker, non_nestable_tasks_enabled ? StackState::kNoHeapPointers
                                         : StackState::kMayContainHeapPointers);
  auto handle = task->handle_;
  if (non_nestable_tasks_enabled) {
    runner->PostNonNestableTask(std::move(task));
  } else {
    runner->PostTask(std::move(task));
  }
  return handle;
}
References DCHECK_IMPLIES, v8::internal::handle(), cppgc::internal::MarkerBase::heap(), cppgc::Heap::kSupportsConservativeStackScan, v8::TaskRunner::NonNestableTasksEnabled(), v8::TaskRunner::PostNonNestableTask(), v8::TaskRunner::PostTask(), and cppgc::internal::HeapBase::stack_support().
Referenced by cppgc::internal::MarkerBase::ScheduleIncrementalMarkingTask().
Run()
void cppgc::internal::MarkerBase::IncrementalMarkingTask::Run () [final], [private], [virtual]
Implements v8::Task.
Definition at line 141 of file marker.cc.
                                           {
  if (handle_.IsCanceled()) return;
  StatsCollector::EnabledScope stats_scope(marker_->heap().stats_collector(),
                                           StatsCollector::kIncrementalMark);
  if (marker_->IncrementalMarkingStep(stack_state_)) {
    // Incremental marking is done so should finalize GC.
    marker_->heap().FinalizeIncrementalGarbageCollectionIfNeeded(stack_state_);
  }
}
References cppgc::internal::HeapBase::FinalizeIncrementalGarbageCollectionIfNeeded(), handle_, cppgc::internal::MarkerBase::heap(), cppgc::internal::MarkerBase::IncrementalMarkingStep(), cppgc::internal::SingleThreadedHandle::IsCanceled(), marker_, stack_state_, and cppgc::internal::HeapBase::stats_collector().
Member Data Documentation
handle_
Handle cppgc::internal::MarkerBase::IncrementalMarkingTask::handle_ [private]
Definition at line 106 of file marker.cc.
Referenced by Run().
marker_
MarkerBase* const cppgc::internal::MarkerBase::IncrementalMarkingTask::marker_ [private]
Definition at line 103 of file marker.cc.
Referenced by Run().
stack_state_
StackState cppgc::internal::MarkerBase::IncrementalMarkingTask::stack_state_ [private]
Definition at line 104 of file marker.cc.
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/marker.cc