v8::internal::wasm::BasicBlockCalculator Class Reference
#include <basic-block-calculator.h>
Public Member Functions
BasicBlockCalculator (Zone *zone, const base::Vector< const uint8_t > &func_code)
void V8_EXPORT_PRIVATE ComputeBasicBlocks ()
const base::Vector< const WasmCodeRange > GetCodeRanges () const
Private Member Functions
void StartNewBlock (Decoder *decoder)
void EndCurrentBlock (Decoder *decoder)
Private Attributes
Zone * zone_
const uint8_t * start_
const uint8_t * end_
int current_basic_block_ = -1
uint32_t current_basic_block_start_pos_ = 0
ZoneVector< WasmCodeRange > basic_block_ranges_
Detailed Description
Definition at line 20 of file basic-block-calculator.h.
Constructor & Destructor Documentation
BasicBlockCalculator()
v8::internal::wasm::BasicBlockCalculator::BasicBlockCalculator (Zone * zone, const base::Vector< const uint8_t > & func_code) [inline]
Definition at line 22 of file basic-block-calculator.h.
      : zone_(zone),
        start_(func_code.begin()),
        end_(func_code.end()),
        basic_block_ranges_(zone) {}
Member Function Documentation
ComputeBasicBlocks()
void v8::internal::wasm::BasicBlockCalculator::ComputeBasicBlocks ()
Definition at line 26 of file basic-block-calculator.cc.
                                              {
  DCHECK(basic_block_ranges_.empty());
  // Basic block rules.
  // ------------------
  // 1. The first basic block starts at function offset 0.
  // 2. The 'else' instructions and the 'end' instructions end the current
  // block. They are the last instruction in the basic block and the next
  // instruction will start a new block. Likewise, all branch, call, tail-call,
  // 'unreachable', 'return', 'if' and throw instructions end the current block.
  // 3. The 'loop' instructions end the current block and start a new block.
  // 4. The first instruction after the end of a block starts a new block.
  // There can be unreachable instructions in between, which are not part of
  // any block.
  // 5. The last basic block ends at the offset of the final function 'end'
  // instruction.
  BodyLocalDecls locals;
  BytecodeIterator iterator(start_, end_, &locals, zone_);
  DCHECK_LT(0, locals.encoded_size);
  // Start function.
  current_basic_block_ = 0;
  current_basic_block_start_pos_ = 0;
  bool at_block_end = false;
  for (; iterator.has_next(); iterator.next()) {
    WasmOpcode opcode = iterator.current();
    if (at_block_end) {
      StartNewBlock(&iterator);
      at_block_end = false;
    }
    switch (opcode) {
      case kExprLoop:
        DCHECK_GE(current_basic_block_, 0);
        if (iterator.position() > current_basic_block_start_pos_) {
          basic_block_ranges_.emplace_back(current_basic_block_start_pos_,
                                           iterator.position() - 1);
          StartNewBlock(&iterator);
        }
        break;
      case kExprEnd:
      case kExprIf:
      case kExprElse:
      case kExprUnreachable:
      case kExprBr:
      case kExprBrTable:
      case kExprReturn:
      case kExprDelegate:
      case kExprRethrow:
      case kExprThrow:
      case kExprThrowRef:
      case kExprCatch:
      case kExprCatchAll:
      case kExprBrIf:
      case kExprBrOnNull:
      case kExprBrOnNonNull:
      case kExprBrOnCast:
      case kExprBrOnCastFail:
      case kExprBrOnCastDesc:
      case kExprBrOnCastDescFail:
      case kExprReturnCall:
      case kExprReturnCallIndirect:
      case kExprReturnCallRef:
      case kExprCallFunction:
      case kExprCallIndirect:
      case kExprCallRef:
        EndCurrentBlock(&iterator);
        at_block_end = true;
        break;
      default:
        break;
    }
  }
  if (!at_block_end) {
    basic_block_ranges_.emplace_back(current_basic_block_start_pos_,
                                     iterator.position() - 1);
  }
}
References basic_block_ranges_, v8::internal::wasm::BytecodeIterator::current(), current_basic_block_, current_basic_block_start_pos_, v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, v8::internal::wasm::BodyLocalDecls::encoded_size, end_, EndCurrentBlock(), v8::internal::wasm::BytecodeIterator::has_next(), v8::internal::wasm::BytecodeIterator::next(), start_, StartNewBlock(), and zone_.
Referenced by v8::internal::wasm::ExecuteLiftoffCompilation().
EndCurrentBlock()
void v8::internal::wasm::BasicBlockCalculator::EndCurrentBlock (Decoder * decoder) [private]
Definition at line 16 of file basic-block-calculator.cc.
                                                           {
  DCHECK_GE(current_basic_block_, 0);
  DCHECK_GE(decoder->position(), current_basic_block_start_pos_);
  int final_instruction_length = OpcodeLength(decoder->pc(), decoder->end());
  basic_block_ranges_.emplace_back(
      current_basic_block_start_pos_,
      decoder->position() + final_instruction_length - 1);
}
References basic_block_ranges_, current_basic_block_, current_basic_block_start_pos_, DCHECK_GE, v8::internal::wasm::Decoder::end(), v8::internal::wasm::OpcodeLength(), v8::internal::wasm::Decoder::pc(), and v8::internal::wasm::Decoder::position().
Referenced by ComputeBasicBlocks().
GetCodeRanges()
const base::Vector<const WasmCodeRange> v8::internal::wasm::BasicBlockCalculator::GetCodeRanges () const [inline]
Definition at line 29 of file basic-block-calculator.h.
                                                              {
    return {basic_block_ranges_.begin(), basic_block_ranges_.size()};
  }
References basic_block_ranges_.
StartNewBlock()
void v8::internal::wasm::BasicBlockCalculator::StartNewBlock (Decoder * decoder) [private]
Definition at line 11 of file basic-block-calculator.cc.
                                                         {
  current_basic_block_++;
  current_basic_block_start_pos_ = decoder->position();
}
References current_basic_block_, current_basic_block_start_pos_, and v8::internal::wasm::Decoder::position().
Referenced by ComputeBasicBlocks().
Member Data Documentation
basic_block_ranges_
ZoneVector<WasmCodeRange> v8::internal::wasm::BasicBlockCalculator::basic_block_ranges_ [private]
Definition at line 43 of file basic-block-calculator.h.
Referenced by ComputeBasicBlocks(), EndCurrentBlock(), and GetCodeRanges().
current_basic_block_
int v8::internal::wasm::BasicBlockCalculator::current_basic_block_ = -1 [private]
Definition at line 41 of file basic-block-calculator.h.
Referenced by ComputeBasicBlocks(), EndCurrentBlock(), and StartNewBlock().
current_basic_block_start_pos_
uint32_t v8::internal::wasm::BasicBlockCalculator::current_basic_block_start_pos_ = 0 [private]
Definition at line 42 of file basic-block-calculator.h.
Referenced by ComputeBasicBlocks(), EndCurrentBlock(), and StartNewBlock().
end_
const uint8_t* v8::internal::wasm::BasicBlockCalculator::end_ [private]
Definition at line 39 of file basic-block-calculator.h.
Referenced by ComputeBasicBlocks().
start_
const uint8_t* v8::internal::wasm::BasicBlockCalculator::start_ [private]
Definition at line 38 of file basic-block-calculator.h.
Referenced by ComputeBasicBlocks().
zone_
Zone* v8::internal::wasm::BasicBlockCalculator::zone_ [private]
Definition at line 37 of file basic-block-calculator.h.
Referenced by ComputeBasicBlocks().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/basic-block-calculator.h
/mnt/V8SourceCode/src/wasm/basic-block-calculator.cc