v8::internal::Analysis< Propagators > Class Template Reference
Public Member Functions
Analysis (Isolate *isolate, bool is_one_byte, RegExpFlags flags)
void EnsureAnalyzed (RegExpNode *that)
bool has_failed ()
RegExpError error ()
void fail (RegExpError error)
Isolate * isolate () const
void VisitEnd (EndNode *that) override
void VisitText (TextNode *that) override
void VisitAction (ActionNode *that) override
void VisitChoice (ChoiceNode *that) override
void VisitLoopChoice (LoopChoiceNode *that) override
void VisitNegativeLookaroundChoice (NegativeLookaroundChoiceNode *that) override
void VisitBackReference (BackReferenceNode *that) override
void VisitAssertion (AssertionNode *that) override
Private Member Functions
RegExpFlags flags () const
void set_flags (RegExpFlags flags)
DISALLOW_IMPLICIT_CONSTRUCTORS (Analysis)
Private Attributes
Isolate * isolate_
const bool is_one_byte_
RegExpFlags flags_
RegExpError error_
Detailed Description
template<typename... Propagators>
class v8::internal::Analysis< Propagators >
Definition at line 3796 of file regexp-compiler.cc.
Constructor & Destructor Documentation
Analysis()
template<typename... Propagators>
v8::internal::Analysis< Propagators >::Analysis (Isolate * isolate, bool is_one_byte, RegExpFlags flags) [inline]
Definition at line 3798 of file regexp-compiler.cc.
      : isolate_(isolate),
        is_one_byte_(is_one_byte),
        flags_(flags),
        error_(RegExpError::kNone) {}
References v8::internal::kNone.
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS()
template<typename... Propagators>
v8::internal::Analysis< Propagators >::DISALLOW_IMPLICIT_CONSTRUCTORS (Analysis< Propagators >) [private]
EnsureAnalyzed()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::EnsureAnalyzed (RegExpNode * that) [inline]
Definition at line 3804 of file regexp-compiler.cc.
                                        {
    StackLimitCheck check(isolate());
    if (check.HasOverflowed()) {
      if (v8_flags.correctness_fuzzer_suppressions) {
        FATAL("Analysis: Aborting on stack overflow");
      }
      fail(RegExpError::kAnalysisStackOverflow);
      return;
    }
    if (that->info()->been_analyzed || that->info()->being_analyzed) return;
    that->info()->being_analyzed = true;
    that->Accept(this);
    that->info()->being_analyzed = false;
    that->info()->been_analyzed = true;
  }
References v8::internal::RegExpNode::Accept(), v8::internal::NodeInfo::been_analyzed, v8::internal::NodeInfo::being_analyzed, v8::internal::Analysis< Propagators >::fail(), FATAL, v8::internal::StackLimitCheck::HasOverflowed(), v8::internal::RegExpNode::info(), v8::internal::Analysis< Propagators >::isolate(), and v8::internal::v8_flags.
Referenced by v8::internal::AnalyzeRegExp(), v8::internal::Analysis< Propagators >::VisitAction(), v8::internal::Analysis< Propagators >::VisitAssertion(), v8::internal::Analysis< Propagators >::VisitBackReference(), v8::internal::Analysis< Propagators >::VisitChoice(), v8::internal::Analysis< Propagators >::VisitLoopChoice(), v8::internal::Analysis< Propagators >::VisitNegativeLookaroundChoice(), and v8::internal::Analysis< Propagators >::VisitText().
error()
template<typename... Propagators>
RegExpError v8::internal::Analysis< Propagators >::error () [inline]
Definition at line 3821 of file regexp-compiler.cc.
                      {
    DCHECK(error_ != RegExpError::kNone);
    return error_;
  }
References v8::internal::DCHECK(), and v8::internal::Analysis< Propagators >::error_.
Referenced by v8::internal::AnalyzeRegExp(), and v8::internal::Analysis< Propagators >::fail().
fail()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::fail (RegExpError error) [inline]
Definition at line 3825 of file regexp-compiler.cc.
{ error_ = error; }
References v8::internal::Analysis< Propagators >::error(), and v8::internal::Analysis< Propagators >::error_.
Referenced by v8::internal::Analysis< Propagators >::EnsureAnalyzed().
flags()
template<typename... Propagators>
RegExpFlags v8::internal::Analysis< Propagators >::flags () const [inline], [private]
Definition at line 3924 of file regexp-compiler.cc.
{ return flags_; }
References v8::internal::Analysis< Propagators >::flags_.
Referenced by v8::internal::Analysis< Propagators >::set_flags(), v8::internal::Analysis< Propagators >::VisitLoopChoice(), and v8::internal::Analysis< Propagators >::VisitText().
has_failed()
template<typename... Propagators>
bool v8::internal::Analysis< Propagators >::has_failed () [inline]
Definition at line 3820 of file regexp-compiler.cc.
{ return error_ != RegExpError::kNone; }
References v8::internal::Analysis< Propagators >::error_.
Referenced by v8::internal::AnalyzeRegExp(), v8::internal::Analysis< Propagators >::VisitAction(), v8::internal::Analysis< Propagators >::VisitAssertion(), v8::internal::Analysis< Propagators >::VisitBackReference(), v8::internal::Analysis< Propagators >::VisitChoice(), v8::internal::Analysis< Propagators >::VisitLoopChoice(), v8::internal::Analysis< Propagators >::VisitNegativeLookaroundChoice(), and v8::internal::Analysis< Propagators >::VisitText().
isolate()
template<typename... Propagators>
Isolate* v8::internal::Analysis< Propagators >::isolate () const [inline]
Definition at line 3827 of file regexp-compiler.cc.
{ return isolate_; }
References v8::internal::Analysis< Propagators >::isolate_.
Referenced by v8::internal::Analysis< Propagators >::EnsureAnalyzed(), and v8::internal::Analysis< Propagators >::VisitText().
set_flags()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::set_flags (RegExpFlags flags) [inline], [private]
Definition at line 3925 of file regexp-compiler.cc.
{ flags_ = flags; }
References v8::internal::Analysis< Propagators >::flags(), and v8::internal::Analysis< Propagators >::flags_.
Referenced by v8::internal::Analysis< Propagators >::VisitAction(), and v8::internal::Analysis< Propagators >::VisitLoopChoice().
VisitAction()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::VisitAction (ActionNode * that) [inline], [override]
Definition at line 3849 of file regexp-compiler.cc.
                                              {
    if (that->action_type() == ActionNode::MODIFY_FLAGS) {
      set_flags(that->flags());
    }
    EnsureAnalyzed(that->on_success());
    if (has_failed()) return;
    STATIC_FOR_EACH(Propagators::VisitAction(that));
  }
References v8::internal::ActionNode::action_type(), v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::ActionNode::flags, v8::internal::Analysis< Propagators >::has_failed(), v8::internal::ActionNode::MODIFY_FLAGS, v8::internal::SeqRegExpNode::on_success(), v8::internal::Analysis< Propagators >::set_flags(), and STATIC_FOR_EACH.
VisitAssertion()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::VisitAssertion (AssertionNode * that) [inline], [override]
Definition at line 3915 of file regexp-compiler.cc.
                                                    {
    EnsureAnalyzed(that->on_success());
    if (has_failed()) return;
    STATIC_FOR_EACH(Propagators::VisitAssertion(that));
  }
References v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::Analysis< Propagators >::has_failed(), v8::internal::SeqRegExpNode::on_success(), and STATIC_FOR_EACH.
VisitBackReference()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::VisitBackReference (BackReferenceNode * that) [inline], [override]
Definition at line 3909 of file regexp-compiler.cc.
                                                            {
    EnsureAnalyzed(that->on_success());
    if (has_failed()) return;
    STATIC_FOR_EACH(Propagators::VisitBackReference(that));
  }
References v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::Analysis< Propagators >::has_failed(), v8::internal::SeqRegExpNode::on_success(), and STATIC_FOR_EACH.
VisitChoice()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::VisitChoice (ChoiceNode * that) [inline], [override]
Definition at line 3858 of file regexp-compiler.cc.
                                              {
    for (int i = 0; i < that->alternatives()->length(); i++) {
      EnsureAnalyzed(that->alternatives()->at(i).node());
      if (has_failed()) return;
      STATIC_FOR_EACH(Propagators::VisitChoice(that, i));
    }
  }
References v8::internal::ChoiceNode::alternatives(), v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::Analysis< Propagators >::has_failed(), v8::internal::length, and STATIC_FOR_EACH.
VisitEnd()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::VisitEnd (EndNode * that) [inline], [override]
Definition at line 3829 of file regexp-compiler.cc.
                                        {
    // nothing to do
  }
VisitLoopChoice()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::VisitLoopChoice (LoopChoiceNode * that) [inline], [override]
Definition at line 3866 of file regexp-compiler.cc.
                                                      {
    DCHECK_EQ(that->alternatives()->length(), 2); // Just loop and continue.
    // First propagate all information from the continuation node.
    // Due to the unusual visitation order, we need to manage the flags manually
    // as if we were visiting the loop node before visiting the continuation.
    RegExpFlags orig_flags = flags();
    EnsureAnalyzed(that->continue_node());
    if (has_failed()) return;
    // Propagators don't access global state (including flags), so we don't need
    // to reset them here.
    STATIC_FOR_EACH(Propagators::VisitLoopChoiceContinueNode(that));
    RegExpFlags continuation_flags = flags();
    // Check the loop last since it may need the value of this node
    // to get a correct result.
    set_flags(orig_flags);
    EnsureAnalyzed(that->loop_node());
    if (has_failed()) return;
    // Propagators don't access global state (including flags), so we don't need
    // to reset them here.
    STATIC_FOR_EACH(Propagators::VisitLoopChoiceLoopNode(that));
    set_flags(continuation_flags);
  }
References v8::internal::ChoiceNode::alternatives(), v8::internal::LoopChoiceNode::continue_node(), DCHECK_EQ, v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::Analysis< Propagators >::flags(), v8::internal::Analysis< Propagators >::has_failed(), v8::internal::LoopChoiceNode::loop_node(), v8::internal::Analysis< Propagators >::set_flags(), and STATIC_FOR_EACH.
VisitNegativeLookaroundChoice()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::VisitNegativeLookaroundChoice (NegativeLookaroundChoiceNode * that) [inline], [override]
Definition at line 3894 of file regexp-compiler.cc.
                                                   {
    DCHECK_EQ(that->alternatives()->length(), 2); // Lookaround and continue.
    EnsureAnalyzed(that->lookaround_node());
    if (has_failed()) return;
    STATIC_FOR_EACH(
        Propagators::VisitNegativeLookaroundChoiceLookaroundNode(that));
    EnsureAnalyzed(that->continue_node());
    if (has_failed()) return;
    STATIC_FOR_EACH(
        Propagators::VisitNegativeLookaroundChoiceContinueNode(that));
  }
References v8::internal::ChoiceNode::alternatives(), v8::internal::NegativeLookaroundChoiceNode::continue_node(), DCHECK_EQ, v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::Analysis< Propagators >::has_failed(), v8::internal::NegativeLookaroundChoiceNode::lookaround_node(), and STATIC_FOR_EACH.
VisitText()
template<typename... Propagators>
void v8::internal::Analysis< Propagators >::VisitText (TextNode * that) [inline], [override]
Definition at line 3841 of file regexp-compiler.cc.
                                          {
    that->MakeCaseIndependent(isolate(), is_one_byte_, flags());
    EnsureAnalyzed(that->on_success());
    if (has_failed()) return;
    that->CalculateOffsets();
    STATIC_FOR_EACH(Propagators::VisitText(that));
  }
References v8::internal::TextNode::CalculateOffsets(), v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::Analysis< Propagators >::flags(), v8::internal::Analysis< Propagators >::has_failed(), v8::internal::Analysis< Propagators >::is_one_byte_, v8::internal::Analysis< Propagators >::isolate(), v8::internal::TextNode::MakeCaseIndependent(), v8::internal::SeqRegExpNode::on_success(), and STATIC_FOR_EACH.
Member Data Documentation
error_
template<typename... Propagators>
RegExpError v8::internal::Analysis< Propagators >::error_ [private]
Definition at line 3930 of file regexp-compiler.cc.
Referenced by v8::internal::Analysis< Propagators >::error(), v8::internal::Analysis< Propagators >::fail(), and v8::internal::Analysis< Propagators >::has_failed().
flags_
template<typename... Propagators>
RegExpFlags v8::internal::Analysis< Propagators >::flags_ [private]
Definition at line 3929 of file regexp-compiler.cc.
Referenced by v8::internal::Analysis< Propagators >::flags(), and v8::internal::Analysis< Propagators >::set_flags().
is_one_byte_
template<typename... Propagators>
const bool v8::internal::Analysis< Propagators >::is_one_byte_ [private]
Definition at line 3928 of file regexp-compiler.cc.
Referenced by v8::internal::Analysis< Propagators >::VisitText().
isolate_
template<typename... Propagators>
Isolate* v8::internal::Analysis< Propagators >::isolate_ [private]
Definition at line 3927 of file regexp-compiler.cc.
Referenced by v8::internal::Analysis< Propagators >::isolate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc