v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions > Class Template Reference
#include <liftoff-assembler-arm64-inl.h>
Public Member Functions
GetProtectedInstruction (LiftoffAssembler *assm, uint32_t *protected_instruction_pc)
~GetProtectedInstruction ()
Private Attributes
LiftoffAssembler * assm_
uint32_t * protected_instruction_pc_
MacroAssembler::BlockPoolsScope blocked_pools_scope_
int previous_pc_offset_
Static Private Attributes
static constexpr int kReservedInstructions = 4
Detailed Description
template<LoadOrStore kLoadOrStore, uint8_t kExtraEmittedInstructions = 0>
class v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >
Definition at line 628 of file liftoff-assembler-arm64-inl.h.
Constructor & Destructor Documentation
GetProtectedInstruction()
template<LoadOrStore kLoadOrStore, uint8_t kExtraEmittedInstructions = 0>
v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::GetProtectedInstruction (LiftoffAssembler * assm, uint32_t * protected_instruction_pc) [inline]
Definition at line 630 of file liftoff-assembler-arm64-inl.h.
      : assm_(assm),
        protected_instruction_pc_(protected_instruction_pc),
        // First emit any required pools...
        blocked_pools_scope_(assm, kReservedInstructions * kInstrSize),
        // ...then record the PC offset before the relevant instruction
        // sequence.
        previous_pc_offset_(assm->pc_offset()) {}
 GetProtectedInstruction()
template<LoadOrStore kLoadOrStore, uint8_t kExtraEmittedInstructions = 0>
v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::~GetProtectedInstruction () [inline]
Definition at line 640 of file liftoff-assembler-arm64-inl.h.
                             {
    if (!protected_instruction_pc_) return;
    *protected_instruction_pc_ =
        assm_->pc_offset() - kInstrSize * (1 + kExtraEmittedInstructions);
    if constexpr (kLoadOrStore == LoadOrStore::kLoad) {
      DCHECK(assm_->InstructionAt(*protected_instruction_pc_)->IsLoad());
    } else {
      DCHECK(assm_->InstructionAt(*protected_instruction_pc_)->IsStore());
    }
    // Make sure {kReservedInstructions} was large enough.
    DCHECK_LE(assm_->pc_offset() - previous_pc_offset_,
              kReservedInstructions * kInstrSize);
    USE(previous_pc_offset_);
  }
References v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::assm_, v8::internal::DCHECK(), DCHECK_LE, v8::internal::Assembler::InstructionAt(), v8::internal::Instruction::IsLoad(), v8::internal::Instruction::IsStore(), v8::internal::kInstrSize, v8::internal::wasm::kLoad, v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::kReservedInstructions, v8::internal::AssemblerBase::pc_offset(), v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::previous_pc_offset_, v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::protected_instruction_pc_, and USE.
Member Data Documentation
assm_
template<LoadOrStore kLoadOrStore, uint8_t kExtraEmittedInstructions = 0>
LiftoffAssembler* v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::assm_ [private]
Definition at line 662 of file liftoff-assembler-arm64-inl.h.
Referenced by v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::~GetProtectedInstruction().
blocked_pools_scope_
template<LoadOrStore kLoadOrStore, uint8_t kExtraEmittedInstructions = 0>
MacroAssembler::BlockPoolsScope v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::blocked_pools_scope_ [private]
Definition at line 664 of file liftoff-assembler-arm64-inl.h.
kReservedInstructions
template<LoadOrStore kLoadOrStore, uint8_t kExtraEmittedInstructions = 0>
constexpr int v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::kReservedInstructions = 4 [static], [constexpr], [private]
Definition at line 660 of file liftoff-assembler-arm64-inl.h.
Referenced by v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::~GetProtectedInstruction().
previous_pc_offset_
template<LoadOrStore kLoadOrStore, uint8_t kExtraEmittedInstructions = 0>
int v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::previous_pc_offset_ [private]
Definition at line 665 of file liftoff-assembler-arm64-inl.h.
Referenced by v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::~GetProtectedInstruction().
protected_instruction_pc_
template<LoadOrStore kLoadOrStore, uint8_t kExtraEmittedInstructions = 0>
uint32_t* v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::protected_instruction_pc_ [private]
Definition at line 663 of file liftoff-assembler-arm64-inl.h.
Referenced by v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::~GetProtectedInstruction().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/arm64/liftoff-assembler-arm64-inl.h