v8::internal::maglev::BasicBlock Class Reference
#include <maglev-basic-block.h>
Public Types
using Id = uint32_t
Public Member Functions
BasicBlock (MergePointInterpreterFrameState *state, Zone *zone)
NodeIdT first_id () const
void Print () const
NodeIdT first_non_phi_id () const
NodeIdT FirstNonGapMoveId () const
ZoneVector< Node * > & nodes ()
ControlNode * control_node () const
void set_control_node (ControlNode *control_node)
ControlNode * reset_control_node ()
ZoneVector< Node * > Split (Node *node, Zone *zone)
bool has_phi () const
bool is_merge_block () const
bool is_edge_split_block () const
bool is_loop () const
MergePointRegisterState & edge_split_block_register_state ()
bool contains_node_id (NodeIdT id) const
void set_edge_split_block_register_state (MergePointRegisterState *register_state)
void set_edge_split_block (BasicBlock *predecessor)
BasicBlock * predecessor () const
void set_predecessor (BasicBlock *predecessor)
bool is_start_block_of_switch_case () const
void set_start_block_of_switch_case (bool value)
bool is_dead () const
void mark_dead ()
Phi::List * phis () const
void AddPhi (Phi *phi) const
ExceptionHandlerInfo::List & exception_handlers ()
void AddExceptionHandler (ExceptionHandlerInfo *handler)
int predecessor_count () const
BasicBlock * predecessor_at (int i) const
BasicBlock * backedge_predecessor () const
int predecessor_id () const
void set_predecessor_id (int id)
base::SmallVector< BasicBlock *, 2 > successors () const
template<typename Func >
void ForEachPredecessor (Func &&functor) const
template<typename Func >
bool ForAllPredecessors (Func &&functor) const
template<typename Func >
void ForEachSuccessor (Func &&functor) const
Label * label ()
MergePointInterpreterFrameState * state () const
bool has_state () const
bool is_exception_handler_block () const
BasicBlock * ComputeRealJumpTarget ()
bool is_deferred () const
void set_deferred (bool deferred)
void set_id (Id id)
bool has_id () const
Id id () const
Static Public Member Functions
template<typename Func >
static void ForEachSuccessorFollowing (ControlNode *control, Func &&functor)
Static Public Attributes
constexpr static Id kInvalidBlockId = 0xffffffff
Private Types
enum : uint8_t { kMerge
, kEdgeSplit
, kOther
 }
Private Member Functions
bool HasPhisOrRegisterMerges () const
void check_layout ()
Private Attributes
enum v8::internal::maglev::BasicBlock:: { ... } type_
bool deferred_: 1 = false
bool is_start_block_of_switch_case_: 1 = false
bool is_dead_: 1 = false
Id id_ = kInvalidBlockId
ZoneVector< Node * > nodes_
ControlNode * control_node_
ExceptionHandlerInfo::List exception_handlers_
xx xx xx xx xx xx xx xx xx
union {
 MergePointInterpreterFrameState * state_
 MergePointRegisterState * edge_split_block_register_state_
};
BasicBlock * predecessor_ = nullptr
Label label_
Detailed Description
Definition at line 25 of file maglev-basic-block.h.
Member Typedef Documentation
Id
using v8::internal::maglev::BasicBlock::Id = uint32_t
Definition at line 288 of file maglev-basic-block.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint8_t [private]
Enumerator
kMerge
kEdgeSplit
kOther
Definition at line 337 of file maglev-basic-block.h.
: uint8_t { kMerge, kEdgeSplit, kOther } type_;
Constructor & Destructor Documentation
BasicBlock()
v8::internal::maglev::BasicBlock::BasicBlock (MergePointInterpreterFrameState * state, Zone * zone) [inline], [explicit]
Definition at line 27 of file maglev-basic-block.h.
      : type_(state ? kMerge : kOther),
        nodes_(zone),
        control_node_(nullptr),
        state_(state) {}
Member Function Documentation
AddExceptionHandler()
void v8::internal::maglev::BasicBlock::AddExceptionHandler (ExceptionHandlerInfo * handler) [inline]
Definition at line 161 of file maglev-basic-block.h.
                                                          {
    exception_handlers_.Add(handler);
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), and exception_handlers_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AttachExceptionHandlerInfo().
AddPhi()
void v8::internal::maglev::BasicBlock::AddPhi (Phi * phi) const [inline]
Definition at line 152 of file maglev-basic-block.h.
                              {
    DCHECK(has_state());
    state_->phis()->Add(phi);
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::internal::DCHECK(), has_state(), v8::internal::maglev::MergePointInterpreterFrameState::phis(), and state_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings().
backedge_predecessor()
BasicBlock* v8::internal::maglev::BasicBlock::backedge_predecessor () const [inline]
Definition at line 175 of file maglev-basic-block.h.
                                           {
    DCHECK(is_loop());
    return predecessor_at(predecessor_count() - 1);
  }
References v8::internal::DCHECK(), is_loop(), predecessor_at(), and predecessor_count().
Referenced by v8::internal::compiler::turboshaft::GeneratorAnalyzer::FindLoopBody(), v8::internal::maglev::MaglevInliner::RemovePredecessorFollowing(), and v8::internal::maglev::Graph::RemoveUnreachableBlocks().
check_layout()
void v8::internal::maglev::BasicBlock::check_layout () [inline], [private]
Definition at line 359 of file maglev-basic-block.h.
                              {
  // Ensure non pointer sized values are nicely packed.
  static_assert(offsetof(BasicBlock, nodes_) == 8);
}
References nodes_.
ComputeRealJumpTarget()
BasicBlock* v8::internal::maglev::BasicBlock::ComputeRealJumpTarget () [inline]
Definition at line 264 of file maglev-basic-block.h.
                                      {
    BasicBlock* current = this;
    while (true) {
      if (!current->nodes_.empty() || current->is_loop() ||
          current->is_exception_handler_block() ||
          current->HasPhisOrRegisterMerges()) {
        break;
      }
      Jump* control = current->control_node()->TryCast<Jump>();
      if (!control) {
        break;
      }
      BasicBlock* next = control->target();
      if (next->HasPhisOrRegisterMerges()) {
        break;
      }
      current = next;
    }
    return current;
  }
References control_node(), v8::internal::ZoneVector< T >::empty(), HasPhisOrRegisterMerges(), is_exception_handler_block(), is_loop(), nodes_, and v8::internal::maglev::NodeBase::TryCast().
Referenced by label(), and v8::internal::maglev::MaglevCodeGenState::RealJumpTarget().
contains_node_id()
bool v8::internal::maglev::BasicBlock::contains_node_id (NodeIdT id) const [inline]
Definition at line 109 of file maglev-basic-block.h.
                                          {
    return id >= first_id() && id <= control_node()->id();
  }
References control_node(), first_id(), and v8::internal::maglev::NodeBase::id().
control_node()
ControlNode* v8::internal::maglev::BasicBlock::control_node () const [inline]
Definition at line 66 of file maglev-basic-block.h.
{ return control_node_; }
References control_node_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), ComputeRealJumpTarget(), contains_node_id(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::compiler::turboshaft::GeneratorAnalyzer::FindLoopHeaderBypasses(), first_non_phi_id(), FirstNonGapMoveId(), ForEachSuccessor(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::IsMaglevMainGeneratorSwitchBlock(), predecessor_id(), v8::internal::maglev::LoopOptimizationProcessor::Process(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::MergePointInterpreterFrameState::RemovePredecessorAt(), set_control_node(), set_edge_split_block(), set_predecessor_id(), and successors().
edge_split_block_register_state()
MergePointRegisterState& v8::internal::maglev::BasicBlock::edge_split_block_register_state () [inline]
Definition at line 103 of file maglev-basic-block.h.
                                                             {
    DCHECK_EQ(type_, kEdgeSplit);
    DCHECK_NOT_NULL(edge_split_block_register_state_);
    return *edge_split_block_register_state_;
  }
References DCHECK_EQ, DCHECK_NOT_NULL, edge_split_block_register_state_, kEdgeSplit, and type_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
exception_handlers()
ExceptionHandlerInfo::List& v8::internal::maglev::BasicBlock::exception_handlers () [inline]
Definition at line 157 of file maglev-basic-block.h.
                                                 {
    return exception_handlers_;
  }
References exception_handlers_.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), and v8::internal::maglev::Graph::RemoveUnreachableBlocks().
first_id()
NodeIdT v8::internal::maglev::BasicBlock::first_id () const [inline]
Definition at line 33 of file maglev-basic-block.h.
                           {
    DCHECK(!is_dead());
    if (has_phi()) return phis()->first()->id();
    return first_non_phi_id();
  }
References v8::internal::DCHECK(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first(), first_non_phi_id(), has_phi(), is_dead(), and phis().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), contains_node_id(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeConditionalBranchTarget(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsTargetOfNodeFallthrough(), and v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkUse().
first_non_phi_id()
NodeIdT v8::internal::maglev::BasicBlock::first_non_phi_id () const [inline]
Definition at line 42 of file maglev-basic-block.h.
                                   {
    for (const Node* node : nodes_) {
      if (node == nullptr) continue;
      if (!node->Is<Identity>()) return node->id();
    }
    return control_node()->id();
  }
References control_node(), v8::internal::maglev::NodeBase::id(), and nodes_.
Referenced by first_id().
FirstNonGapMoveId()
NodeIdT v8::internal::maglev::BasicBlock::FirstNonGapMoveId () const [inline]
Definition at line 50 of file maglev-basic-block.h.
                                    {
    if (has_phi()) return phis()->first()->id();
    for (const Node* node : nodes_) {
      if (node == nullptr) continue;
      if (IsGapMoveNode(node->opcode())) continue;
      if (node->Is<Identity>()) continue;
      return node->id();
    }
    return control_node()->id();
  }
References control_node(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first(), has_phi(), v8::internal::maglev::NodeBase::id(), v8::internal::maglev::IsGapMoveNode(), nodes_, and phis().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget().
ForAllPredecessors()
template<typename Func >
bool v8::internal::maglev::BasicBlock::ForAllPredecessors (Func && functor) const [inline]
Definition at line 204 of file maglev-basic-block.h.
                                                {
    if (type_ == kEdgeSplit || type_ == kOther) {
      BasicBlock* predecessor_block = predecessor();
      if (predecessor_block) {
        if (!functor(predecessor_block)) {
          return false;
        }
      }
    } else {
      for (int i = 0; i < predecessor_count(); i++) {
        if (!functor(predecessor_at(i))) {
          return false;
        }
      }
    }
    return true;
  }
References kEdgeSplit, kOther, predecessor(), predecessor_at(), predecessor_count(), and type_.
ForEachPredecessor()
template<typename Func >
void v8::internal::maglev::BasicBlock::ForEachPredecessor (Func && functor) const [inline]
Definition at line 190 of file maglev-basic-block.h.
                                                {
    if (type_ == kEdgeSplit || type_ == kOther) {
      BasicBlock* predecessor_block = predecessor();
      if (predecessor_block) {
        functor(predecessor_block);
      }
    } else {
      for (int i = 0; i < predecessor_count(); i++) {
        functor(predecessor_at(i));
      }
    }
  }
References kEdgeSplit, kOther, predecessor(), predecessor_at(), predecessor_count(), and type_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred().
ForEachSuccessor()
template<typename Func >
void v8::internal::maglev::BasicBlock::ForEachSuccessor (Func && functor) const [inline]
Definition at line 241 of file maglev-basic-block.h.
                                              {
    ControlNode* control = control_node();
    ForEachSuccessorFollowing(control, functor);
  }
References control_node(), and ForEachSuccessorFollowing().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred(), and v8::internal::maglev::Graph::RemoveUnreachableBlocks().
ForEachSuccessorFollowing()
template<typename Func >
static void v8::internal::maglev::BasicBlock::ForEachSuccessorFollowing (ControlNode * control, Func && functor) [inline], [static]
Definition at line 223 of file maglev-basic-block.h.
                                                                              {
    if (auto unconditional_control =
            control->TryCast<UnconditionalControlNode>()) {
      functor(unconditional_control->target());
    } else if (auto branch = control->TryCast<BranchControlNode>()) {
      functor(branch->if_true());
      functor(branch->if_false());
    } else if (auto switch_node = control->TryCast<Switch>()) {
      for (int i = 0; i < switch_node->size(); i++) {
        functor(switch_node->targets()[i].block_ptr());
      }
      if (switch_node->has_fallthrough()) {
        functor(switch_node->fallthrough());
      }
    }
  }
References v8::internal::maglev::NodeBase::TryCast().
Referenced by ForEachSuccessor(), and v8::internal::maglev::MaglevInliner::RemovePredecessorFollowing().
has_id()
bool v8::internal::maglev::BasicBlock::has_id () const [inline]
Definition at line 295 of file maglev-basic-block.h.
{ return id_ != kInvalidBlockId; }
References id_, and kInvalidBlockId.
Referenced by v8::internal::maglev::Graph::Add(), id(), and set_id().
has_phi()
bool v8::internal::maglev::BasicBlock::has_phi () const [inline]
Definition at line 96 of file maglev-basic-block.h.
{ return has_state() && state_->has_phi(); }
References v8::internal::maglev::MergePointInterpreterFrameState::has_phi(), has_state(), and state_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), first_id(), FirstNonGapMoveId(), v8::internal::maglev::MaglevPhiRepresentationSelector::FixLoopPhisBackedge(), HasPhisOrRegisterMerges(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeConditionalBranchTarget(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::InsertTaggingForPhis(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses(), phis(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreProcessBasicBlock(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessBasicBlock(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartMultiPredecessorExceptionBlock(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartSinglePredecessorExceptionBlock(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::TagExceptionPhiInputsForBlock().
has_state()
bool v8::internal::maglev::BasicBlock::has_state () const [inline]
Definition at line 256 of file maglev-basic-block.h.
{ return type_ == kMerge && state_ != nullptr; }
References kMerge, state_, and type_.
Referenced by AddPhi(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), has_phi(), HasPhisOrRegisterMerges(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeConditionalBranchTarget(), is_exception_handler_block(), is_loop(), predecessor_at(), predecessor_count(), v8::internal::maglev::LiveRangeAndNextUseProcessor::PreProcessBasicBlock(), v8::internal::maglev::LiveRangeAndNextUseProcessor::Process(), v8::internal::maglev::MaglevInliner::RemovePredecessorFollowing(), v8::internal::maglev::Graph::RemoveUnreachableBlocks(), state(), and v8::internal::maglev::MaglevInliner::UpdatePredecessorsOf().
HasPhisOrRegisterMerges()
bool v8::internal::maglev::BasicBlock::HasPhisOrRegisterMerges () const [inline], [private]
Definition at line 302 of file maglev-basic-block.h.
                                       {
    if (!has_state()) {
      return false;
    }
    if (has_phi()) {
      return true;
    }
    bool has_register_merge = false;
#ifdef V8_ENABLE_MAGLEV
    if (!state()->register_state().is_initialized()) {
      // This can happen when the graph has disconnected blocks; bail out and
      // don't jump thread them.
      return true;
    }
    state()->register_state().ForEachGeneralRegister(
        [&](Register reg, RegisterState& state) {
          ValueNode* node;
          RegisterMerge* merge;
          if (LoadMergeState(state, &node, &merge)) {
            has_register_merge = true;
          }
        });
    state()->register_state().ForEachDoubleRegister(
        [&](DoubleRegister reg, RegisterState& state) {
          ValueNode* node;
          RegisterMerge* merge;
          if (LoadMergeState(state, &node, &merge)) {
            has_register_merge = true;
          }
        });
#endif // V8_ENABLE_MAGLEV
    return has_register_merge;
  }
References has_phi(), has_state(), v8::internal::maglev::LoadMergeState(), v8::internal::maglev::MergePointInterpreterFrameState::register_state(), and state().
Referenced by ComputeRealJumpTarget().
id()
Id v8::internal::maglev::BasicBlock::id () const [inline]
Definition at line 296 of file maglev-basic-block.h.
                {
    DCHECK(has_id());
    return id_;
  }
References v8::internal::DCHECK(), has_id(), and id_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads(), v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopSpills(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::IsMaglevMainGeneratorSwitchBlock(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessBasicBlock(), v8::internal::maglev::MaglevGraphVerifier::PreProcessBasicBlock(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets(), v8::internal::maglev::MaglevCodeGenState::RealJumpTarget(), v8::internal::maglev::Graph::RemoveUnreachableBlocks(), and set_id().
is_dead()
bool v8::internal::maglev::BasicBlock::is_dead () const [inline]
Definition at line 144 of file maglev-basic-block.h.
{ return is_dead_; }
References is_dead_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::MaglevInliner::BuildInlineFunction(), first_id(), nodes(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessGraph(), and v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
is_deferred()
bool v8::internal::maglev::BasicBlock::is_deferred () const [inline]
Definition at line 285 of file maglev-basic-block.h.
{ return deferred_; }
References deferred_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessGraph().
is_edge_split_block()
bool v8::internal::maglev::BasicBlock::is_edge_split_block () const [inline]
Definition at line 99 of file maglev-basic-block.h.
{ return type_ == kEdgeSplit; }
References kEdgeSplit, and type_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeConditionalBranchTarget(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeEmptyBlockRegisterValues(), and v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues().
is_exception_handler_block()
bool v8::internal::maglev::BasicBlock::is_exception_handler_block () const [inline]
Definition at line 258 of file maglev-basic-block.h.
                                          {
    return has_state() && state_->is_exception_handler();
  }
References has_state(), v8::internal::maglev::MergePointInterpreterFrameState::is_exception_handler(), and state_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), ComputeRealJumpTarget(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessBasicBlock().
is_loop()
bool v8::internal::maglev::BasicBlock::is_loop () const [inline]
Definition at line 101 of file maglev-basic-block.h.
{ return has_state() && state()->is_loop(); }
References has_state(), v8::internal::maglev::MergePointInterpreterFrameState::is_loop(), and state().
Referenced by backedge_predecessor(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildJump(), v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), ComputeRealJumpTarget(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged(), v8::internal::compiler::turboshaft::GeneratorAnalyzer::FindLoopBody(), v8::internal::compiler::turboshaft::GeneratorAnalyzer::HeaderIsBypassed(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), v8::internal::maglev::LoopOptimizationProcessor::IsLoopPhi(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PostPhiProcessing(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessBasicBlock(), v8::internal::maglev::LoopOptimizationProcessor::PreProcessBasicBlock(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessBasicBlock(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::maglev::MaglevInliner::RemovePredecessorFollowing(), and v8::internal::maglev::Graph::RemoveUnreachableBlocks().
is_merge_block()
bool v8::internal::maglev::BasicBlock::is_merge_block () const [inline]
Definition at line 98 of file maglev-basic-block.h.
{ return type_ == kMerge; }
References kMerge, and type_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings().
is_start_block_of_switch_case()
bool v8::internal::maglev::BasicBlock::is_start_block_of_switch_case () const [inline]
Definition at line 137 of file maglev-basic-block.h.
                                             {
    return is_start_block_of_switch_case_;
  }
References is_start_block_of_switch_case_.
label()
Label* v8::internal::maglev::BasicBlock::label () [inline]
Definition at line 246 of file maglev-basic-block.h.
                 {
    // If this fails, jump threading is missing for the node. See
    // MaglevCodeGeneratingNodeProcessor::PatchJumps.
    DCHECK_EQ(this, ComputeRealJumpTarget());
    return &label_;
  }
References ComputeRealJumpTarget(), DCHECK_EQ, and label_.
Referenced by v8::internal::maglev::MaglevAssembler::BindBlock(), v8::internal::maglev::MaglevAssembler::Branch(), v8::internal::maglev::MaglevAssembler::CompareFloat64AndBranch(), v8::internal::maglev::MaglevAssembler::CompareInt32AndBranch(), v8::internal::maglev::MaglevAssembler::CompareIntPtrAndBranch(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor().
mark_dead()
void v8::internal::maglev::BasicBlock::mark_dead () [inline]
Definition at line 146 of file maglev-basic-block.h.
{ is_dead_ = true; }
References is_dead_.
nodes()
ZoneVector<Node*>& v8::internal::maglev::BasicBlock::nodes () [inline]
Definition at line 61 of file maglev-basic-block.h.
                             {
    DCHECK(!is_dead());
    return nodes_;
  }
References v8::internal::DCHECK(), is_dead(), and nodes_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::maglev::MaglevPhiRepresentationSelector::AddNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::StraightForwardRegisterAllocator::ApplyPatches(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromHoleyFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromIntPtrToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromUint32ToTagged(), v8::internal::maglev::MaglevPhiRepresentationSelector::PostProcessBasicBlock(), and v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
phis()
Phi::List* v8::internal::maglev::BasicBlock::phis () const [inline]
Definition at line 148 of file maglev-basic-block.h.
                        {
    DCHECK(has_phi());
    return state_->phis();
  }
References v8::internal::DCHECK(), has_phi(), v8::internal::maglev::MergePointInterpreterFrameState::phis(), and state_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), first_id(), FirstNonGapMoveId(), v8::internal::maglev::MaglevPhiRepresentationSelector::FixLoopPhisBackedge(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreProcessBasicBlock(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves().
predecessor()
BasicBlock* v8::internal::maglev::BasicBlock::predecessor () const [inline]
Definition at line 127 of file maglev-basic-block.h.
                                  {
    DCHECK(type_ == kEdgeSplit || type_ == kOther);
    return predecessor_;
  }
References v8::internal::DCHECK(), kEdgeSplit, kOther, predecessor_, and type_.
Referenced by ForAllPredecessors(), ForEachPredecessor(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), set_edge_split_block(), set_predecessor(), and v8::internal::maglev::MaglevInliner::UpdatePredecessorsOf().
predecessor_at()
BasicBlock* v8::internal::maglev::BasicBlock::predecessor_at (int i) const [inline]
Definition at line 170 of file maglev-basic-block.h.
                                          {
    DCHECK(has_state());
    return state_->predecessor_at(i);
  }
References v8::internal::DCHECK(), has_state(), v8::internal::maglev::MergePointInterpreterFrameState::predecessor_at(), and state_.
Referenced by backedge_predecessor(), v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), ForAllPredecessors(), ForEachPredecessor(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::maglev::LoopOptimizationProcessor::Process(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), and v8::internal::maglev::MaglevInliner::UpdatePredecessorsOf().
predecessor_count()
int v8::internal::maglev::BasicBlock::predecessor_count () const [inline]
Definition at line 165 of file maglev-basic-block.h.
                                {
    DCHECK(has_state());
    return state()->predecessor_count();
  }
References v8::internal::DCHECK(), has_state(), v8::internal::maglev::MergePointInterpreterFrameState::predecessor_count(), and state().
Referenced by backedge_predecessor(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildJump(), v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), ForAllPredecessors(), ForEachPredecessor(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::maglev::MaglevInliner::RemovePredecessorFollowing(), v8::internal::maglev::Graph::RemoveUnreachableBlocks(), and v8::internal::maglev::MaglevInliner::UpdatePredecessorsOf().
predecessor_id()
int v8::internal::maglev::BasicBlock::predecessor_id () const [inline]
Definition at line 180 of file maglev-basic-block.h.
                             {
    return control_node()->Cast<UnconditionalControlNode>()->predecessor_id();
  }
References v8::internal::maglev::NodeBase::Cast(), and control_node().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), and v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses().
Print()
void v8::internal::maglev::BasicBlock::Print () const
reset_control_node()
ControlNode* v8::internal::maglev::BasicBlock::reset_control_node () [inline]
Definition at line 72 of file maglev-basic-block.h.
                                    {
    DCHECK_NOT_NULL(control_node_);
    ControlNode* control = control_node_;
    control_node_ = nullptr;
    return control;
  }
References control_node_, and DCHECK_NOT_NULL.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
set_control_node()
void v8::internal::maglev::BasicBlock::set_control_node (ControlNode * control_node) [inline]
Definition at line 67 of file maglev-basic-block.h.
                                                   {
    DCHECK_NULL(control_node_);
    control_node_ = control_node;
  }
References control_node(), control_node_, and DCHECK_NULL.
set_deferred()
void v8::internal::maglev::BasicBlock::set_deferred (bool deferred) [inline]
Definition at line 286 of file maglev-basic-block.h.
{ deferred_ = deferred; }
References deferred_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred(), and v8::internal::maglev::MaglevGraphBuilder::EmitUnconditionalDeopt().
set_edge_split_block()
void v8::internal::maglev::BasicBlock::set_edge_split_block (BasicBlock * predecessor) [inline]
Definition at line 119 of file maglev-basic-block.h.
                                                     {
    DCHECK_EQ(type_, kOther);
    DCHECK(nodes_.empty());
    DCHECK(control_node()->Is<Jump>());
    type_ = kEdgeSplit;
    predecessor_ = predecessor;
  }
References control_node(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ZoneVector< T >::empty(), kEdgeSplit, kOther, nodes_, predecessor(), predecessor_, and type_.
set_edge_split_block_register_state()
void v8::internal::maglev::BasicBlock::set_edge_split_block_register_state (MergePointRegisterState * register_state) [inline]
Definition at line 113 of file maglev-basic-block.h.
                                               {
    DCHECK_EQ(type_, kEdgeSplit);
    edge_split_block_register_state_ = register_state;
  }
References DCHECK_EQ, edge_split_block_register_state_, kEdgeSplit, and type_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::InitializeEmptyBlockRegisterValues().
set_id()
void v8::internal::maglev::BasicBlock::set_id (Id id) [inline]
Definition at line 291 of file maglev-basic-block.h.
                     {
    DCHECK(!has_id());
    id_ = id;
  }
References v8::internal::DCHECK(), has_id(), id(), and id_.
Referenced by v8::internal::maglev::Graph::Add().
set_predecessor()
void v8::internal::maglev::BasicBlock::set_predecessor (BasicBlock * predecessor) [inline]
Definition at line 131 of file maglev-basic-block.h.
                                                {
    DCHECK(type_ == kEdgeSplit || type_ == kOther);
    DCHECK_NULL(edge_split_block_register_state_);
    predecessor_ = predecessor;
  }
References v8::internal::DCHECK(), DCHECK_NULL, edge_split_block_register_state_, kEdgeSplit, kOther, predecessor(), predecessor_, and type_.
Referenced by v8::internal::maglev::MaglevInliner::UpdatePredecessorsOf().
set_predecessor_id()
void v8::internal::maglev::BasicBlock::set_predecessor_id (int id) [inline]
Definition at line 183 of file maglev-basic-block.h.
                                  {
    control_node()->Cast<UnconditionalControlNode>()->set_predecessor_id(id);
  }
References v8::internal::maglev::NodeBase::Cast(), and control_node().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::EndLoop(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
set_start_block_of_switch_case()
void v8::internal::maglev::BasicBlock::set_start_block_of_switch_case (bool value) [inline]
Definition at line 140 of file maglev-basic-block.h.
                                                  {
    is_start_block_of_switch_case_ = value;
  }
References is_start_block_of_switch_case_, and v8::internal::value.
Split()
ZoneVector<Node*> v8::internal::maglev::BasicBlock::Split (Node * node, Zone * zone) [inline]
Definition at line 81 of file maglev-basic-block.h.
                                                  {
    size_t split = 0;
    for (; split < nodes_.size(); split++) {
      if (nodes_[split] == node) break;
    }
    DCHECK_NE(split, nodes_.size());
    size_t after_split = split + 1;
    ZoneVector<Node*> result(nodes_.size() - after_split, zone);
    for (size_t i = 0; i < result.size(); i++) {
      result[i] = nodes_[i + after_split];
    }
    nodes_.resize(split);
    return result;
  }
References DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, nodes_, v8::internal::ZoneVector< T >::resize(), v8::base::internal::result, v8::internal::ZoneVector< T >::size(), and v8::internal::libvtune::split().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
state()
MergePointInterpreterFrameState* v8::internal::maglev::BasicBlock::state () const [inline]
Definition at line 252 of file maglev-basic-block.h.
                                                 {
    DCHECK(has_state());
    return state_;
  }
References v8::internal::DCHECK(), has_state(), and state_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::MaglevPhiRepresentationSelector::CanHoistUntaggingTo(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), HasPhisOrRegisterMerges(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetRegisterValues(), is_loop(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), v8::internal::maglev::LoopOptimizationProcessor::IsLoopPhi(), v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues(), predecessor_count(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::maglev::LoopOptimizationProcessor::PreProcessBasicBlock(), v8::internal::maglev::LiveRangeAndNextUseProcessor::PreProcessBasicBlock(), and v8::internal::maglev::MaglevInliner::UpdatePredecessorsOf().
successors()
base::SmallVector< BasicBlock *, 2 > v8::internal::maglev::BasicBlock::successors () const [inline]
Definition at line 364 of file maglev-basic-block.h.
                                                                    {
  ControlNode* control = control_node();
  if (auto unconditional_control =
          control->TryCast<UnconditionalControlNode>()) {
    return {unconditional_control->target()};
  } else if (auto branch = control->TryCast<BranchControlNode>()) {
    return {branch->if_true(), branch->if_false()};
  } else if (auto switch_node = control->TryCast<Switch>()) {
    base::SmallVector<BasicBlock*, 2> succs;
    for (int i = 0; i < switch_node->size(); i++) {
      succs.push_back(switch_node->targets()[i].block_ptr());
    }
    if (switch_node->has_fallthrough()) {
      succs.push_back(switch_node->fallthrough());
    }
    return succs;
  } else {
    return base::SmallVector<BasicBlock*, 2>();
  }
}
References control_node(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), v8::internal::maglev::MaglevPhiRepresentationSelector::CanHoistUntaggingTo(), v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged(), v8::internal::compiler::turboshaft::GeneratorAnalyzer::FindLoopHeaderBypasses(), and v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
Member Data Documentation
union { ... } [private]
control_node_
ControlNode* v8::internal::maglev::BasicBlock::control_node_ [private]
Definition at line 345 of file maglev-basic-block.h.
Referenced by control_node(), reset_control_node(), and set_control_node().
deferred_
bool v8::internal::maglev::BasicBlock::deferred_ [private]
Definition at line 338 of file maglev-basic-block.h.
Referenced by is_deferred(), and set_deferred().
edge_split_block_register_state_
MergePointRegisterState* v8::internal::maglev::BasicBlock::edge_split_block_register_state_
Definition at line 350 of file maglev-basic-block.h.
Referenced by edge_split_block_register_state(), set_edge_split_block_register_state(), and set_predecessor().
exception_handlers_
ExceptionHandlerInfo::List v8::internal::maglev::BasicBlock::exception_handlers_ [private]
Definition at line 346 of file maglev-basic-block.h.
Referenced by AddExceptionHandler(), and exception_handlers().
id_
Id v8::internal::maglev::BasicBlock::id_ = kInvalidBlockId [private]
Definition at line 342 of file maglev-basic-block.h.
Referenced by has_id(), id(), and set_id().
is_dead_
bool v8::internal::maglev::BasicBlock::is_dead_ [private]
Definition at line 340 of file maglev-basic-block.h.
Referenced by is_dead(), and mark_dead().
is_start_block_of_switch_case_
bool v8::internal::maglev::BasicBlock::is_start_block_of_switch_case_ [private]
Definition at line 339 of file maglev-basic-block.h.
Referenced by is_start_block_of_switch_case(), and set_start_block_of_switch_case().
kInvalidBlockId
constexpr static Id v8::internal::maglev::BasicBlock::kInvalidBlockId = 0xffffffff [static], [constexpr]
Definition at line 289 of file maglev-basic-block.h.
Referenced by has_id().
label_
Label v8::internal::maglev::BasicBlock::label_ [private]
Definition at line 354 of file maglev-basic-block.h.
Referenced by label().
nodes_
ZoneVector<Node*> v8::internal::maglev::BasicBlock::nodes_ [private]
Definition at line 344 of file maglev-basic-block.h.
Referenced by check_layout(), ComputeRealJumpTarget(), first_non_phi_id(), FirstNonGapMoveId(), nodes(), set_edge_split_block(), and Split().
predecessor_
BasicBlock* v8::internal::maglev::BasicBlock::predecessor_ = nullptr [private]
Definition at line 353 of file maglev-basic-block.h.
Referenced by predecessor(), set_edge_split_block(), and set_predecessor().
state_
MergePointInterpreterFrameState* v8::internal::maglev::BasicBlock::state_
Definition at line 349 of file maglev-basic-block.h.
Referenced by AddPhi(), has_phi(), has_state(), is_exception_handler_block(), phis(), predecessor_at(), and state().
enum { ... } v8::internal::maglev::BasicBlock::type_ [private]
Referenced by edge_split_block_register_state(), ForAllPredecessors(), ForEachPredecessor(), has_state(), is_edge_split_block(), is_merge_block(), predecessor(), set_edge_split_block(), set_edge_split_block_register_state(), and set_predecessor().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-basic-block.h