v8::internal::compiler::UnallocatedOperand Class Reference
#include <instruction.h>
Public Types
enum BasicPolicy { FIXED_SLOT
, EXTENDED_POLICY
 }
enum ExtendedPolicy {
NONE
, REGISTER_OR_SLOT
, REGISTER_OR_SLOT_OR_CONSTANT
, FIXED_REGISTER
,
FIXED_FP_REGISTER
, MUST_HAVE_REGISTER
, MUST_HAVE_SLOT
, SAME_AS_INPUT
 }
enum Lifetime { USED_AT_START
, USED_AT_END
 }
using VirtualRegisterField = KindField::Next< uint32_t, 32 >
using BasicPolicyField = VirtualRegisterField::Next< BasicPolicy, 1 >
using FixedSlotIndexField = BasicPolicyField::Next< int, 28 >
using ExtendedPolicyField = BasicPolicyField::Next< ExtendedPolicy, 3 >
using LifetimeField = ExtendedPolicyField::Next< Lifetime, 1 >
using HasSecondaryStorageField = LifetimeField::Next< bool, 1 >
using FixedRegisterField = HasSecondaryStorageField::Next< int, 6 >
using SecondaryStorageField = FixedRegisterField::Next< int, 3 >
using InputIndexField = SecondaryStorageField::Next< int, 3 >
Public Member Functions
UnallocatedOperand (ExtendedPolicy policy, int virtual_register)
UnallocatedOperand (int virtual_register, int input_index)
UnallocatedOperand (BasicPolicy policy, int index, int virtual_register)
UnallocatedOperand (ExtendedPolicy policy, int index, int virtual_register)
UnallocatedOperand (ExtendedPolicy policy, Lifetime lifetime, int virtual_register)
UnallocatedOperand (int reg_id, int slot_id, int virtual_register)
UnallocatedOperand (const UnallocatedOperand &other, int virtual_register)
bool HasRegisterOrSlotPolicy () const
bool HasRegisterOrSlotOrConstantPolicy () const
bool HasFixedPolicy () const
bool HasRegisterPolicy () const
bool HasSlotPolicy () const
bool HasSameAsInputPolicy () const
bool HasFixedSlotPolicy () const
bool HasFixedRegisterPolicy () const
bool HasFixedFPRegisterPolicy () const
bool HasSecondaryStorage () const
int GetSecondaryStorage () const
BasicPolicy basic_policy () const
ExtendedPolicy extended_policy () const
int input_index () const
int fixed_slot_index () const
int fixed_register_index () const
int32_t virtual_register () const
bool IsUsedAtStart () const
Private Member Functions
UnallocatedOperand (int virtual_register)
Additional Inherited Members
Detailed Description
Definition at line 188 of file instruction.h.
Member Typedef Documentation
BasicPolicyField
using v8::internal::compiler::UnallocatedOperand::BasicPolicyField = VirtualRegisterField::Next<BasicPolicy, 1>
Definition at line 377 of file instruction.h.
ExtendedPolicyField
using v8::internal::compiler::UnallocatedOperand::ExtendedPolicyField = BasicPolicyField::Next<ExtendedPolicy, 3>
Definition at line 384 of file instruction.h.
FixedRegisterField
using v8::internal::compiler::UnallocatedOperand::FixedRegisterField = HasSecondaryStorageField::Next<int, 6>
Definition at line 387 of file instruction.h.
FixedSlotIndexField
using v8::internal::compiler::UnallocatedOperand::FixedSlotIndexField = BasicPolicyField::Next<int, 28>
Definition at line 380 of file instruction.h.
HasSecondaryStorageField
using v8::internal::compiler::UnallocatedOperand::HasSecondaryStorageField = LifetimeField::Next<bool, 1>
Definition at line 386 of file instruction.h.
InputIndexField
using v8::internal::compiler::UnallocatedOperand::InputIndexField = SecondaryStorageField::Next<int, 3>
Definition at line 389 of file instruction.h.
LifetimeField
using v8::internal::compiler::UnallocatedOperand::LifetimeField = ExtendedPolicyField::Next<Lifetime, 1>
Definition at line 385 of file instruction.h.
SecondaryStorageField
using v8::internal::compiler::UnallocatedOperand::SecondaryStorageField = FixedRegisterField::Next<int, 3>
Definition at line 388 of file instruction.h.
VirtualRegisterField
using v8::internal::compiler::UnallocatedOperand::VirtualRegisterField = KindField::Next<uint32_t, 32>
Definition at line 374 of file instruction.h.
Member Enumeration Documentation
BasicPolicy
enum v8::internal::compiler::UnallocatedOperand::BasicPolicy
Enumerator
FIXED_SLOT
EXTENDED_POLICY
Definition at line 190 of file instruction.h.
{ FIXED_SLOT, EXTENDED_POLICY };
ExtendedPolicy
enum v8::internal::compiler::UnallocatedOperand::ExtendedPolicy
Enumerator
NONE
REGISTER_OR_SLOT
REGISTER_OR_SLOT_OR_CONSTANT
FIXED_REGISTER
FIXED_FP_REGISTER
MUST_HAVE_REGISTER
MUST_HAVE_SLOT
SAME_AS_INPUT
Definition at line 192 of file instruction.h.
                      {
    NONE,
    REGISTER_OR_SLOT,
    REGISTER_OR_SLOT_OR_CONSTANT,
    FIXED_REGISTER,
    FIXED_FP_REGISTER,
    MUST_HAVE_REGISTER,
    MUST_HAVE_SLOT,
    SAME_AS_INPUT
  };
Lifetime
enum v8::internal::compiler::UnallocatedOperand::Lifetime
Enumerator
USED_AT_START
USED_AT_END
Definition at line 204 of file instruction.h.
                {
    // USED_AT_START operand is guaranteed to be live only at instruction start.
    // The register allocator is free to assign the same register to some other
    // operand used inside instruction (i.e. temporary or output).
    USED_AT_START,
    // USED_AT_END operand is treated as live until the end of instruction.
    // This means that register allocator will not reuse its register for any
    // other operand inside instruction.
    USED_AT_END
  };
Constructor & Destructor Documentation
UnallocatedOperand() [1/8]
v8::internal::compiler::UnallocatedOperand::UnallocatedOperand (ExtendedPolicy policy, int virtual_register) [inline]
Definition at line 216 of file instruction.h.
      : UnallocatedOperand(virtual_register) {
    value_ |= BasicPolicyField::encode(EXTENDED_POLICY);
    value_ |= ExtendedPolicyField::encode(policy);
    value_ |= LifetimeField::encode(USED_AT_END);
  }
References v8::base::BitField< T, shift, size, U >::encode(), EXTENDED_POLICY, USED_AT_END, and v8::internal::compiler::InstructionOperand::value_.
UnallocatedOperand() [2/8]
v8::internal::compiler::UnallocatedOperand::UnallocatedOperand (int virtual_register, int input_index) [inline]
Definition at line 223 of file instruction.h.
      : UnallocatedOperand(virtual_register) {
    value_ |= BasicPolicyField::encode(EXTENDED_POLICY);
    value_ |= ExtendedPolicyField::encode(SAME_AS_INPUT);
    value_ |= LifetimeField::encode(USED_AT_END);
    value_ |= InputIndexField::encode(input_index);
  }
References v8::base::BitField< T, shift, size, U >::encode(), EXTENDED_POLICY, input_index(), SAME_AS_INPUT, USED_AT_END, and v8::internal::compiler::InstructionOperand::value_.
UnallocatedOperand() [3/8]
v8::internal::compiler::UnallocatedOperand::UnallocatedOperand (BasicPolicy policy, int index, int virtual_register) [inline]
Definition at line 231 of file instruction.h.
      : UnallocatedOperand(virtual_register) {
    DCHECK(policy == FIXED_SLOT);
    value_ |= BasicPolicyField::encode(policy);
    value_ |= static_cast<uint64_t>(static_cast<int64_t>(index))
              << FixedSlotIndexField::kShift;
    DCHECK(this->fixed_slot_index() == index);
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), FIXED_SLOT, fixed_slot_index(), v8::internal::index, v8::base::BitField< T, shift, size, U >::kShift, and v8::internal::compiler::InstructionOperand::value_.
UnallocatedOperand() [4/8]
v8::internal::compiler::UnallocatedOperand::UnallocatedOperand (ExtendedPolicy policy, int index, int virtual_register) [inline]
Definition at line 240 of file instruction.h.
      : UnallocatedOperand(virtual_register) {
    DCHECK(policy == FIXED_REGISTER || policy == FIXED_FP_REGISTER);
    value_ |= BasicPolicyField::encode(EXTENDED_POLICY);
    value_ |= ExtendedPolicyField::encode(policy);
    value_ |= LifetimeField::encode(USED_AT_END);
    value_ |= FixedRegisterField::encode(index);
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), EXTENDED_POLICY, FIXED_FP_REGISTER, FIXED_REGISTER, v8::internal::index, USED_AT_END, and v8::internal::compiler::InstructionOperand::value_.
UnallocatedOperand() [5/8]
v8::internal::compiler::UnallocatedOperand::UnallocatedOperand (ExtendedPolicy policy, Lifetime lifetime, int virtual_register) [inline]
Definition at line 249 of file instruction.h.
      : UnallocatedOperand(virtual_register) {
    value_ |= BasicPolicyField::encode(EXTENDED_POLICY);
    value_ |= ExtendedPolicyField::encode(policy);
    value_ |= LifetimeField::encode(lifetime);
  }
References v8::base::BitField< T, shift, size, U >::encode(), EXTENDED_POLICY, and v8::internal::compiler::InstructionOperand::value_.
UnallocatedOperand() [6/8]
v8::internal::compiler::UnallocatedOperand::UnallocatedOperand (int reg_id, int slot_id, int virtual_register) [inline]
Definition at line 257 of file instruction.h.
      : UnallocatedOperand(FIXED_REGISTER, reg_id, virtual_register) {
    value_ |= HasSecondaryStorageField::encode(true);
    value_ |= SecondaryStorageField::encode(slot_id);
  }
References v8::base::BitField< T, shift, size, U >::encode(), and v8::internal::compiler::InstructionOperand::value_.
UnallocatedOperand() [7/8]
v8::internal::compiler::UnallocatedOperand::UnallocatedOperand (const UnallocatedOperand & other, int virtual_register) [inline]
Definition at line 263 of file instruction.h.
                                                                            {
    DCHECK_NE(kInvalidVirtualRegister, virtual_register);
    value_ = VirtualRegisterField::update(
        other.value_, static_cast<uint32_t>(virtual_register));
  }
References DCHECK_NE, v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, v8::base::BitField< T, shift, size, U >::update(), v8::internal::compiler::InstructionOperand::value_, and virtual_register().
UnallocatedOperand() [8/8]
v8::internal::compiler::UnallocatedOperand::UnallocatedOperand (int virtual_register) [inline], [explicit], [private]
Definition at line 392 of file instruction.h.
      : InstructionOperand(UNALLOCATED) {
    value_ |=
        VirtualRegisterField::encode(static_cast<uint32_t>(virtual_register));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::InstructionOperand::value_, and virtual_register().
Member Function Documentation
basic_policy()
BasicPolicy v8::internal::compiler::UnallocatedOperand::basic_policy () const [inline]
Definition at line 315 of file instruction.h.
{ return BasicPolicyField::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), extended_policy(), HasFixedFPRegisterPolicy(), HasFixedPolicy(), HasFixedRegisterPolicy(), HasFixedSlotPolicy(), HasRegisterOrSlotOrConstantPolicy(), HasRegisterOrSlotPolicy(), HasRegisterPolicy(), HasSameAsInputPolicy(), HasSecondaryStorage(), HasSlotPolicy(), IsUsedAtStart(), and v8::internal::compiler::operator<<().
extended_policy()
ExtendedPolicy v8::internal::compiler::UnallocatedOperand::extended_policy () const [inline]
Definition at line 318 of file instruction.h.
                                         {
    DCHECK(basic_policy() == EXTENDED_POLICY);
    return ExtendedPolicyField::decode(value_);
  }
References basic_policy(), v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), EXTENDED_POLICY, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput(), v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), HasFixedFPRegisterPolicy(), HasFixedPolicy(), HasFixedRegisterPolicy(), HasRegisterOrSlotOrConstantPolicy(), HasRegisterOrSlotPolicy(), HasRegisterPolicy(), HasSameAsInputPolicy(), HasSecondaryStorage(), HasSlotPolicy(), and v8::internal::compiler::operator<<().
fixed_register_index()
int v8::internal::compiler::UnallocatedOperand::fixed_register_index () const [inline]
Definition at line 336 of file instruction.h.
                                   {
    DCHECK(HasFixedRegisterPolicy() || HasFixedFPRegisterPolicy());
    return FixedRegisterField::decode(value_);
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), HasFixedFPRegisterPolicy(), HasFixedRegisterPolicy(), and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput(), v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), and v8::internal::compiler::operator<<().
fixed_slot_index()
int v8::internal::compiler::UnallocatedOperand::fixed_slot_index () const [inline]
Definition at line 329 of file instruction.h.
                               {
    DCHECK(HasFixedSlotPolicy());
    return static_cast<int>(static_cast<int64_t>(value_) >>
                            FixedSlotIndexField::kShift);
  }
References v8::internal::DCHECK(), HasFixedSlotPolicy(), v8::base::BitField< T, shift, size, U >::kShift, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::operator<<(), and UnallocatedOperand().
GetSecondaryStorage()
int v8::internal::compiler::UnallocatedOperand::GetSecondaryStorage () const [inline]
Definition at line 309 of file instruction.h.
                                  {
    DCHECK(HasSecondaryStorage());
    return SecondaryStorageField::decode(value_);
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), HasSecondaryStorage(), and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), and v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter().
HasFixedFPRegisterPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasFixedFPRegisterPolicy () const [inline]
Definition at line 300 of file instruction.h.
                                        {
    return basic_policy() == EXTENDED_POLICY &&
           extended_policy() == FIXED_FP_REGISTER;
  }
References basic_policy(), EXTENDED_POLICY, extended_policy(), and FIXED_FP_REGISTER.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), and fixed_register_index().
HasFixedPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasFixedPolicy () const [inline]
Definition at line 278 of file instruction.h.
                              {
    return basic_policy() == FIXED_SLOT ||
           extended_policy() == FIXED_REGISTER ||
           extended_policy() == FIXED_FP_REGISTER;
  }
References basic_policy(), extended_policy(), FIXED_FP_REGISTER, FIXED_REGISTER, and FIXED_SLOT.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
HasFixedRegisterPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasFixedRegisterPolicy () const [inline]
Definition at line 296 of file instruction.h.
                                      {
    return basic_policy() == EXTENDED_POLICY &&
           extended_policy() == FIXED_REGISTER;
  }
References basic_policy(), EXTENDED_POLICY, extended_policy(), and FIXED_REGISTER.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), and fixed_register_index().
HasFixedSlotPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasFixedSlotPolicy () const [inline]
Definition at line 295 of file instruction.h.
{ return basic_policy() == FIXED_SLOT; }
References basic_policy(), and FIXED_SLOT.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), fixed_slot_index(), and v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
HasRegisterOrSlotOrConstantPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasRegisterOrSlotOrConstantPolicy () const [inline]
Definition at line 274 of file instruction.h.
                                                 {
    return basic_policy() == EXTENDED_POLICY &&
           extended_policy() == REGISTER_OR_SLOT_OR_CONSTANT;
  }
References basic_policy(), EXTENDED_POLICY, extended_policy(), and REGISTER_OR_SLOT_OR_CONSTANT.
Referenced by v8::internal::compiler::UsePosition::UsePosition().
HasRegisterOrSlotPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasRegisterOrSlotPolicy () const [inline]
Definition at line 270 of file instruction.h.
                                       {
    return basic_policy() == EXTENDED_POLICY &&
           extended_policy() == REGISTER_OR_SLOT;
  }
References basic_policy(), EXTENDED_POLICY, extended_policy(), and REGISTER_OR_SLOT.
Referenced by v8::internal::compiler::UsePosition::UsePosition().
HasRegisterPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasRegisterPolicy () const [inline]
Definition at line 283 of file instruction.h.
                                 {
    return basic_policy() == EXTENDED_POLICY &&
           extended_policy() == MUST_HAVE_REGISTER;
  }
References basic_policy(), EXTENDED_POLICY, extended_policy(), and MUST_HAVE_REGISTER.
Referenced by v8::internal::compiler::UsePosition::UsePosition().
HasSameAsInputPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasSameAsInputPolicy () const [inline]
Definition at line 291 of file instruction.h.
                                    {
    return basic_policy() == EXTENDED_POLICY &&
           extended_policy() == SAME_AS_INPUT;
  }
References basic_policy(), EXTENDED_POLICY, extended_policy(), and SAME_AS_INPUT.
Referenced by input_index(), and v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore().
HasSecondaryStorage()
bool v8::internal::compiler::UnallocatedOperand::HasSecondaryStorage () const [inline]
Definition at line 304 of file instruction.h.
                                   {
    return basic_policy() == EXTENDED_POLICY &&
           extended_policy() == FIXED_REGISTER &&
           HasSecondaryStorageField::decode(value_);
  }
References basic_policy(), v8::base::BitField< T, shift, size, U >::decode(), EXTENDED_POLICY, extended_policy(), FIXED_REGISTER, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), GetSecondaryStorage(), and v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter().
HasSlotPolicy()
bool v8::internal::compiler::UnallocatedOperand::HasSlotPolicy () const [inline]
Definition at line 287 of file instruction.h.
                             {
    return basic_policy() == EXTENDED_POLICY &&
           extended_policy() == MUST_HAVE_SLOT;
  }
References basic_policy(), EXTENDED_POLICY, extended_policy(), and MUST_HAVE_SLOT.
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::UsePosition::UsePosition().
input_index()
int v8::internal::compiler::UnallocatedOperand::input_index () const [inline]
Definition at line 323 of file instruction.h.
                          {
    DCHECK(HasSameAsInputPolicy());
    return InputIndexField::decode(value_);
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), HasSameAsInputPolicy(), and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::operator<<(), and UnallocatedOperand().
IsUsedAtStart()
bool v8::internal::compiler::UnallocatedOperand::IsUsedAtStart () const [inline]
Definition at line 347 of file instruction.h.
                             {
    return basic_policy() == EXTENDED_POLICY &&
           LifetimeField::decode(value_) == USED_AT_START;
  }
References basic_policy(), v8::base::BitField< T, shift, size, U >::decode(), EXTENDED_POLICY, USED_AT_START, and v8::internal::compiler::InstructionOperand::value_.
virtual_register()
int32_t v8::internal::compiler::UnallocatedOperand::virtual_register () const [inline]
Definition at line 342 of file instruction.h.
                                   {
    return static_cast<int32_t>(VirtualRegisterField::decode(value_));
  }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), v8::internal::compiler::OperandGenerator::Define(), v8::internal::compiler::InstructionSelector::MarkAsRepresentation(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::OperandGenerator::TempDoubleRegister(), v8::internal::compiler::OperandGenerator::TempFpRegister(), v8::internal::compiler::OperandGenerator::TempSimd128Register(), v8::internal::compiler::OperandGenerator::TempSimd256Register(), v8::internal::compiler::InstructionSelector::TryRename(), UnallocatedOperand(), v8::internal::compiler::OperandGenerator::Use(), and v8::internal::compiler::OperandGenerator::UsePointerLocation().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction.h