v8::internal::ApiCallbackExitFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
DirectHandle< JSFunction > GetFunction () const
DirectHandle< FunctionTemplateInfo > GetFunctionTemplateInfo () const
Tagged< Object > receiver () const
Tagged< Object > GetParameter (int i) const
int ComputeParametersCount () const
DirectHandle< FixedArray > GetParameters () const
Tagged< Object > context () const override
bool IsConstructor () const
void Print (StringStream *accumulator, PrintMode mode, int index) const override
FrameSummaries Summarize () const override
Static Public Member Functions
static ApiCallbackExitFrame * cast (StackFrame *frame)
Protected Member Functions
ApiCallbackExitFrame (StackFrameIteratorBase *iterator)
Private Member Functions
Tagged< HeapObject > target () const
void set_target (Tagged< HeapObject > function) const
FullObjectSlot target_slot () const
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 967 of file frames.h.
Constructor & Destructor Documentation
ApiCallbackExitFrame()
v8::internal::ApiCallbackExitFrame::ApiCallbackExitFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 163 of file frames-inl.h.
    : ExitFrame(iterator) {}
Member Function Documentation
cast()
static ApiCallbackExitFrame* v8::internal::ApiCallbackExitFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 993 of file frames.h.
                                                       {
    DCHECK(frame->is_api_callback_exit());
    return static_cast<ApiCallbackExitFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_api_callback_exit().
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback().
ComputeParametersCount()
int v8::internal::ApiCallbackExitFrame::ComputeParametersCount () const [inline]
Definition at line 192 of file frames-inl.h.
                                                       {
  int argc = static_cast<int>(base::Memory<Address>(
      fp() + ApiCallbackExitFrameConstants::kFCIArgcOffset));
  DCHECK_GE(argc, 0);
  return argc;
}
References DCHECK_GE, v8::internal::StackFrame::fp(), and v8::internal::ApiCallbackExitFrameConstants::kFCIArgcOffset.
Referenced by GetParameter(), GetParameters(), and Print().
context()
Tagged< Object > v8::internal::ApiCallbackExitFrame::context () const [inline], [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 167 of file frames-inl.h.
                                                          {
  return Tagged<Object>(base::Memory<Address>(
      fp() + ApiCallbackExitFrameConstants::kContextOffset));
}
References v8::internal::StackFrame::fp(), v8::internal::ApiCallbackExitFrameConstants::kContextOffset, and v8::internal::Tagged< Object >.
Referenced by GetFunction().
GetFunction()
DirectHandle< JSFunction > v8::internal::ApiCallbackExitFrame::GetFunction () const
Definition at line 1291 of file frames.cc.
                                                                 {
  Tagged<HeapObject> maybe_function = target();
  if (IsJSFunction(maybe_function)) {
    return DirectHandle<JSFunction>::FromSlot(target_slot().location());
  }
  DCHECK(IsFunctionTemplateInfo(maybe_function));
  DirectHandle<FunctionTemplateInfo> function_template_info(
      Cast<FunctionTemplateInfo>(maybe_function), isolate());
  // Instantiate function for the correct context.
  DCHECK(IsContext(context()));
  DirectHandle<NativeContext> native_context(
      Cast<Context>(context())->native_context(), isolate());
  DirectHandle<JSFunction> function =
      ApiNatives::InstantiateFunction(isolate(), native_context,
                                      function_template_info)
          .ToHandleChecked();
  set_target(*function);
  return function;
}
References context(), v8::internal::DCHECK(), v8::internal::ApiNatives::InstantiateFunction(), v8::internal::StackFrame::isolate(), v8::internal::native_context, set_target(), target(), and target_slot().
Referenced by Print(), and Summarize().
GetFunctionTemplateInfo()
DirectHandle< FunctionTemplateInfo > v8::internal::ApiCallbackExitFrame::GetFunctionTemplateInfo () const
Definition at line 1315 of file frames.cc.
                                                    {
  Tagged<HeapObject> maybe_function = target();
  if (IsJSFunction(maybe_function)) {
    Tagged<SharedFunctionInfo> shared_info =
        Cast<JSFunction>(maybe_function)->shared();
    DCHECK(shared_info->IsApiFunction());
    return direct_handle(shared_info->api_func_data(), isolate());
  }
  DCHECK(IsFunctionTemplateInfo(maybe_function));
  return direct_handle(Cast<FunctionTemplateInfo>(maybe_function), isolate());
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::StackFrame::isolate(), and target().
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback().
GetParameter()
Tagged< Object > v8::internal::ApiCallbackExitFrame::GetParameter (int i) const [inline]
Definition at line 199 of file frames-inl.h.
                                                             {
  DCHECK(i >= 0 && i < ComputeParametersCount());
  int offset = ApiCallbackExitFrameConstants::kFirstArgumentOffset +
               i * kSystemPointerSize;
  return Tagged<Object>(base::Memory<Address>(fp() + offset));
}
References ComputeParametersCount(), v8::internal::DCHECK(), v8::internal::StackFrame::fp(), v8::internal::ApiCallbackExitFrameConstants::kFirstArgumentOffset, v8::internal::kSystemPointerSize, and v8::internal::Tagged< Object >.
Referenced by GetParameters(), and Print().
GetParameters()
DirectHandle< FixedArray > v8::internal::ApiCallbackExitFrame::GetParameters () const
Definition at line 1327 of file frames.cc.
                                                                   {
  if (V8_LIKELY(!v8_flags.detailed_error_stack_trace)) {
    return isolate()->factory()->empty_fixed_array();
  }
  int param_count = ComputeParametersCount();
  auto parameters = isolate()->factory()->NewFixedArray(param_count);
  for (int i = 0; i < param_count; i++) {
    parameters->set(i, GetParameter(i));
  }
  return parameters;
}
References ComputeParametersCount(), v8::internal::Isolate::factory(), GetParameter(), v8::internal::StackFrame::isolate(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::v8_flags, and V8_LIKELY.
Referenced by Summarize().
IsConstructor()
bool v8::internal::ApiCallbackExitFrame::IsConstructor () const [inline]
Definition at line 206 of file frames-inl.h.
                                               {
  Tagged<Object> new_context(base::Memory<Address>(
      fp() + ApiCallbackExitFrameConstants::kNewTargetOffset));
  return !IsUndefined(new_context, isolate());
}
References v8::internal::StackFrame::fp(), v8::internal::StackFrame::isolate(), and v8::internal::ApiCallbackExitFrameConstants::kNewTargetOffset.
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback(), Print(), and Summarize().
Print()
void v8::internal::ApiCallbackExitFrame::Print (StringStream * accumulator, PrintMode mode, int index) const [override], [virtual]
Reimplemented from v8::internal::StackFrame.
Definition at line 1435 of file frames.cc.
                                                  {
  DirectHandle<JSFunction> function = GetFunction();
  DisallowGarbageCollection no_gc;
  Tagged<Object> receiver = this->receiver();
  accumulator->PrintSecurityTokenIfChanged(isolate(), *function);
  PrintIndex(accumulator, mode, index);
  accumulator->Add("ApiCallbackExitFrame ");
  if (IsConstructor()) accumulator->Add("new ");
  accumulator->PrintFunction(isolate(), *function, receiver);
  accumulator->Add("(this=%o", receiver);
  // Print the parameters.
  int parameters_count = ComputeParametersCount();
  for (int i = 0; i < parameters_count; i++) {
    accumulator->Add(",%o", GetParameter(i));
  }
  accumulator->Add(")\n\n");
}
References v8::internal::StringStream::Add(), ComputeParametersCount(), GetFunction(), GetParameter(), v8::internal::index, IsConstructor(), v8::internal::StackFrame::isolate(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::StringStream::PrintFunction(), v8::internal::anonymous_namespace{frames.cc}::PrintIndex(), v8::internal::StringStream::PrintSecurityTokenIfChanged(), and receiver().
receiver()
Tagged< Object > v8::internal::ApiCallbackExitFrame::receiver () const [inline]
Definition at line 176 of file frames-inl.h.
                                                    {
  return Tagged<Object>(base::Memory<Address>(
      fp() + ApiCallbackExitFrameConstants::kReceiverOffset));
}
References v8::internal::StackFrame::fp(), v8::internal::ApiCallbackExitFrameConstants::kReceiverOffset, and v8::internal::Tagged< Object >.
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback(), Print(), and Summarize().
set_target()
void v8::internal::ApiCallbackExitFrame::set_target (Tagged< HeapObject > function) const [inline], [private]
Definition at line 187 of file frames-inl.h.
                                                                       {
  DCHECK(IsJSFunction(function) || IsFunctionTemplateInfo(function));
  target_slot().store(function);
}
References v8::internal::DCHECK(), v8::internal::FullObjectSlot::store(), and target_slot().
Referenced by GetFunction().
Summarize()
FrameSummaries v8::internal::ApiCallbackExitFrame::Summarize () const [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 1339 of file frames.cc.
                                                     {
  DirectHandle<FixedArray> parameters = GetParameters();
  DirectHandle<JSFunction> function = GetFunction();
  DisallowGarbageCollection no_gc;
  Tagged<Code> code;
  int code_offset = -1;
  std::tie(code, code_offset) = LookupCodeAndOffset();
  FrameSummary::JavaScriptFrameSummary summary(
      isolate(), receiver(), *function, Cast<AbstractCode>(code), code_offset,
      IsConstructor(), *parameters);
  return FrameSummaries(summary);
}
References code, GetFunction(), GetParameters(), IsConstructor(), v8::internal::StackFrame::isolate(), v8::internal::StackFrame::LookupCodeAndOffset(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and receiver().
target()
Tagged< HeapObject > v8::internal::ApiCallbackExitFrame::target () const [inline], [private]
Definition at line 181 of file frames-inl.h.
                                                      {
  Tagged<Object> function = *target_slot();
  DCHECK(IsJSFunction(function) || IsFunctionTemplateInfo(function));
  return Cast<HeapObject>(function);
}
References v8::internal::DCHECK(), and target_slot().
Referenced by GetFunction(), and GetFunctionTemplateInfo().
target_slot()
FullObjectSlot v8::internal::ApiCallbackExitFrame::target_slot () const [inline], [private]
Definition at line 172 of file frames-inl.h.
                                                              {
  return FullObjectSlot(fp() + ApiCallbackExitFrameConstants::kTargetOffset);
}
References v8::internal::StackFrame::fp(), and v8::internal::ApiCallbackExitFrameConstants::kTargetOffset.
Referenced by GetFunction(), set_target(), and target().
type()
Type v8::internal::ApiCallbackExitFrame::type () const [inline], [override], [virtual]
Reimplemented from v8::internal::ExitFrame.
Definition at line 969 of file frames.h.
{ return API_CALLBACK_EXIT; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1010 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc