v8::internal::AstRawString Class Reference
#include <ast-value-factory.h>
Public Member Functions
bool IsEmpty () const
int length () const
bool AsArrayIndex (uint32_t *index) const
bool IsIntegerIndex () const
V8_EXPORT_PRIVATE bool IsOneByteEqualTo (const char *data) const
V8_EXPORT_PRIVATE uint16_t FirstCharacter () const
template<typename IsolateT >
void Internalize (IsolateT *isolate)
bool is_one_byte () const
int byte_length () const
const unsigned char * raw_data () const
bool IsPrivateName () const
uint32_t raw_hash_field () const
uint32_t Hash () const
IndirectHandle< String > string () const
Static Public Member Functions
static bool Equal (const AstRawString *lhs, const AstRawString *rhs)
static int Compare (const AstRawString *lhs, const AstRawString *rhs)
Private Member Functions
AstRawString (bool is_one_byte, base::Vector< const uint8_t > literal_bytes, uint32_t raw_hash_field)
AstRawString * next ()
AstRawString ** next_location ()
void set_string (IndirectHandle< String > string)
Private Attributes
friend Zone
xx xx xx xx xx xx xx xx xx
union {
 AstRawString * next_
 IndirectHandle< String > string_
};
base::Vector< const uint8_t > literal_bytes_
uint32_t raw_hash_field_
bool is_one_byte_
Friends
class AstRawStringInternalizationKey
class AstStringConstants
class AstValueFactory
Detailed Description
Definition at line 51 of file ast-value-factory.h.
Constructor & Destructor Documentation
AstRawString()
v8::internal::AstRawString::AstRawString (bool is_one_byte, base::Vector< const uint8_t > literal_bytes, uint32_t raw_hash_field) [inline], [private]
Definition at line 105 of file ast-value-factory.h.
      : next_(nullptr),
        literal_bytes_(literal_bytes),
        raw_hash_field_(raw_hash_field),
        is_one_byte_(is_one_byte) {}
Member Function Documentation
AsArrayIndex()
bool v8::internal::AstRawString::AsArrayIndex (uint32_t * index) const
Referenced by v8::internal::Literal::IsPropertyName(), and v8::internal::Literal::ToUint32().
byte_length()
int v8::internal::AstRawString::byte_length () const [inline]
Definition at line 75 of file ast-value-factory.h.
{ return literal_bytes_.length(); }
References v8::base::Vector< T >::length(), and literal_bytes_.
Referenced by Compare(), and v8::internal::Parser::ParseFunctionLiteral().
Compare()
int v8::internal::AstRawString::Compare (const AstRawString * lhs, const AstRawString * rhs) [static]
Definition at line 147 of file ast-value-factory.cc.
                                                                          {
  // Fast path for equal pointers.
  if (lhs == rhs) return 0;
  const unsigned char* lhs_data = lhs->raw_data();
  const unsigned char* rhs_data = rhs->raw_data();
  size_t length = std::min(lhs->length(), rhs->length());
  // Code point order by contents.
  if (lhs->is_one_byte()) {
    if (rhs->is_one_byte()) {
      if (int result = CompareCharsUnsigned(
              reinterpret_cast<const uint8_t*>(lhs_data),
              reinterpret_cast<const uint8_t*>(rhs_data), length))
        return result;
    } else {
      if (int result = CompareCharsUnsigned(
              reinterpret_cast<const uint8_t*>(lhs_data),
              reinterpret_cast<const uint16_t*>(rhs_data), length))
        return result;
    }
  } else {
    if (rhs->is_one_byte()) {
      if (int result = CompareCharsUnsigned(
              reinterpret_cast<const uint16_t*>(lhs_data),
              reinterpret_cast<const uint8_t*>(rhs_data), length))
        return result;
    } else {
      if (int result = CompareCharsUnsigned(
              reinterpret_cast<const uint16_t*>(lhs_data),
              reinterpret_cast<const uint16_t*>(rhs_data), length))
        return result;
    }
  }
  return lhs->byte_length() - rhs->byte_length();
}
References byte_length(), v8::internal::CompareCharsUnsigned(), is_one_byte(), length(), raw_data(), and v8::base::internal::result.
Referenced by v8::internal::SourceTextModuleDescriptor::ModuleRequestComparer::operator()(), v8::internal::SourceTextModuleDescriptor::AstRawStringComparer::operator()(), and v8::internal::ImportAttributesKeyComparer::operator()().
Equal()
bool v8::internal::AstRawString::Equal (const AstRawString * lhs, const AstRawString * rhs) [static]
Definition at line 116 of file ast-value-factory.cc.
                                                                         {
  DCHECK_EQ(lhs->Hash(), rhs->Hash());
  if (lhs->length() != rhs->length()) return false;
  if (lhs->length() == 0) return true;
  const unsigned char* l = lhs->raw_data();
  const unsigned char* r = rhs->raw_data();
  size_t length = rhs->length();
  if (lhs->is_one_byte()) {
    if (rhs->is_one_byte()) {
      return CompareCharsEqualUnsigned(reinterpret_cast<const uint8_t*>(l),
                                       reinterpret_cast<const uint8_t*>(r),
                                       length);
    } else {
      return CompareCharsEqualUnsigned(reinterpret_cast<const uint8_t*>(l),
                                       reinterpret_cast<const uint16_t*>(r),
                                       length);
    }
  } else {
    if (rhs->is_one_byte()) {
      return CompareCharsEqualUnsigned(reinterpret_cast<const uint16_t*>(l),
                                       reinterpret_cast<const uint8_t*>(r),
                                       length);
    } else {
      return CompareCharsEqualUnsigned(reinterpret_cast<const uint16_t*>(l),
                                       reinterpret_cast<const uint16_t*>(r),
                                       length);
    }
  }
}
References v8::internal::CompareCharsEqualUnsigned(), DCHECK_EQ, Hash(), is_one_byte(), v8::internal::compiler::turboshaft::l, length(), and raw_data().
Referenced by v8::internal::AstRawStringMapMatcher::operator()().
FirstCharacter()
uint16_t v8::internal::AstRawString::FirstCharacter () const
Definition at line 110 of file ast-value-factory.cc.
                                            {
  if (is_one_byte()) return literal_bytes_[0];
  const uint16_t* c = reinterpret_cast<const uint16_t*>(literal_bytes_.begin());
  return *c;
}
References v8::base::Vector< T >::begin(), is_one_byte(), and literal_bytes_.
Referenced by v8::internal::interpreter::IsCharU(), and IsPrivateName().
Hash()
uint32_t v8::internal::AstRawString::Hash () const [inline]
Definition at line 82 of file ast-value-factory.h.
                        {
    // Hash field must be computed.
    DCHECK_EQ(raw_hash_field_ & Name::kHashNotComputedMask, 0);
    return Name::HashBits::decode(raw_hash_field_);
  }
References DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::Name::kHashNotComputedMask, and raw_hash_field_.
Referenced by Equal(), v8::internal::Literal::Hash(), and v8::internal::interpreter::ConstantArrayBuilder::Insert().
Internalize()
template<typename IsolateT >
void v8::internal::AstRawString::Internalize (IsolateT * isolate)
Definition at line 62 of file ast-value-factory.cc.
                                                {
  DCHECK(!has_string_);
  if (literal_bytes_.empty()) {
    set_string(isolate->factory()->empty_string());
  } else if (is_one_byte()) {
    OneByteStringKey key(raw_hash_field_, literal_bytes_);
    set_string(isolate->factory()->InternalizeStringWithKey(&key));
  } else {
    TwoByteStringKey key(raw_hash_field_,
                         base::Vector<const uint16_t>::cast(literal_bytes_));
    set_string(isolate->factory()->InternalizeStringWithKey(&key));
  }
}
References v8::internal::DCHECK(), v8::base::Vector< T >::empty(), is_one_byte(), v8::internal::key, literal_bytes_, raw_hash_field_, and set_string().
Referenced by v8::internal::AstValueFactory::Internalize().
is_one_byte()
bool v8::internal::AstRawString::is_one_byte () const [inline]
Definition at line 74 of file ast-value-factory.h.
{ return is_one_byte_; }
References is_one_byte_.
Referenced by Compare(), Equal(), FirstCharacter(), Internalize(), IsOneByteEqualTo(), length(), v8::internal::Parser::ParseExportSpecifierName(), v8::internal::Parser::ParseFunctionLiteral(), and v8::internal::ParserBase< Impl >::ValidateRegExpLiteral().
IsEmpty()
bool v8::internal::AstRawString::IsEmpty () const [inline]
Definition at line 60 of file ast-value-factory.h.
{ return literal_bytes_.length() == 0; }
References v8::base::Vector< T >::length(), and literal_bytes_.
Referenced by v8::internal::AstConsString::AddString(), v8::internal::Parser::IsEmptyIdentifier(), v8::internal::PreParser::IsEmptyIdentifier(), and v8::internal::Scope::MustAllocate().
IsIntegerIndex()
bool v8::internal::AstRawString::IsIntegerIndex () const
Definition at line 96 of file ast-value-factory.cc.
                                        {
  return Name::IsIntegerIndex(raw_hash_field_);
}
References v8::internal::Name::IsIntegerIndex(), and raw_hash_field_.
IsOneByteEqualTo()
bool v8::internal::AstRawString::IsOneByteEqualTo (const char * data) const
Definition at line 100 of file ast-value-factory.cc.
                                                          {
  if (!is_one_byte()) return false;
  size_t length = literal_bytes_.size();
  if (length != strlen(data)) return false;
  return 0 == strncmp(reinterpret_cast<const char*>(literal_bytes_.begin()),
                      data, length);
}
References v8::base::Vector< T >::begin(), is_one_byte(), length(), literal_bytes_, and v8::base::Vector< T >::size().
Referenced by v8::internal::Expression::IsUndefinedLiteral(), and v8::internal::SuperCallReference::SuperCallReference().
IsPrivateName()
bool v8::internal::AstRawString::IsPrivateName () const [inline]
Definition at line 78 of file ast-value-factory.h.
{ return length() > 0 && FirstCharacter() == '#'; }
References FirstCharacter(), and length().
Referenced by v8::internal::VariableProxy::IsPrivateName(), and v8::internal::Variable::SetMaybeAssigned().
length()
int v8::internal::AstRawString::length () const [inline]
Definition at line 61 of file ast-value-factory.h.
                     {
    return is_one_byte() ? literal_bytes_.length()
                         : literal_bytes_.length() / 2;
  }
References is_one_byte(), v8::base::Vector< T >::length(), and literal_bytes_.
Referenced by Compare(), Equal(), v8::internal::interpreter::IsCharU(), IsOneByteEqualTo(), IsPrivateName(), v8::internal::Parser::ParseExportSpecifierName(), and v8::internal::ParserBase< Impl >::ValidateRegExpLiteral().
next()
AstRawString* v8::internal::AstRawString::next () [inline], [private]
Definition at line 111 of file ast-value-factory.h.
                       {
    DCHECK(!has_string_);
    return next_;
  }
References v8::internal::DCHECK(), and next_.
Referenced by v8::internal::AstValueFactory::Internalize().
next_location()
AstRawString** v8::internal::AstRawString::next_location () [inline], [private]
Definition at line 115 of file ast-value-factory.h.
                                 {
    DCHECK(!has_string_);
    return &next_;
  }
References v8::internal::DCHECK(), and next_.
Referenced by v8::internal::AstValueFactory::AddString().
raw_data()
const unsigned char* v8::internal::AstRawString::raw_data () const [inline]
Definition at line 76 of file ast-value-factory.h.
{ return literal_bytes_.begin(); }
References v8::base::Vector< T >::begin(), and literal_bytes_.
Referenced by Compare(), Equal(), v8::internal::Parser::ParseExportSpecifierName(), v8::internal::Parser::ParseFunctionLiteral(), and v8::internal::ParserBase< Impl >::ValidateRegExpLiteral().
raw_hash_field()
uint32_t v8::internal::AstRawString::raw_hash_field () const [inline]
Definition at line 81 of file ast-value-factory.h.
{ return raw_hash_field_; }
References raw_hash_field_.
set_string()
void v8::internal::AstRawString::set_string (IndirectHandle< String > string) [inline], [private]
Definition at line 120 of file ast-value-factory.h.
                                                 {
    DCHECK(!string.is_null());
    DCHECK(!has_string_);
    string_ = string;
#ifdef DEBUG
    has_string_ = true;
#endif
  }
References v8::internal::DCHECK(), string(), and string_.
Referenced by Internalize().
string()
IndirectHandle<String> v8::internal::AstRawString::string () const [inline]
Definition at line 89 of file ast-value-factory.h.
                                                  {
    DCHECK(has_string_);
    return string_;
  }
References v8::internal::DCHECK(), and string_.
Referenced by v8::internal::AstConsString::Allocate(), v8::internal::ObjectLiteralBoilerplateBuilder::BuildBoilerplateDescription(), v8::internal::Literal::BuildValue(), v8::internal::AstConsString::last(), v8::internal::VariableProxy::name(), v8::internal::NativeFunctionLiteral::name(), v8::internal::Variable::name(), v8::internal::ClassBoilerplate::New(), v8::internal::RegExpLiteral::pattern(), set_string(), v8::internal::interpreter::ConstantArrayBuilder::Entry::ToHandle(), and v8::internal::anonymous_namespace{modules.cc}::ToStringOrUndefined().
Friends And Related Function Documentation
AstRawStringInternalizationKey
friend class AstRawStringInternalizationKey [friend]
Definition at line 99 of file ast-value-factory.h.
AstStringConstants
friend class AstStringConstants [friend]
Definition at line 100 of file ast-value-factory.h.
AstValueFactory
friend class AstValueFactory [friend]
Definition at line 101 of file ast-value-factory.h.
Member Data Documentation
union { ... } [private]
is_one_byte_
bool v8::internal::AstRawString::is_one_byte_ [private]
Definition at line 136 of file ast-value-factory.h.
Referenced by is_one_byte().
literal_bytes_
base::Vector<const uint8_t> v8::internal::AstRawString::literal_bytes_ [private]
Definition at line 134 of file ast-value-factory.h.
Referenced by byte_length(), FirstCharacter(), Internalize(), IsEmpty(), IsOneByteEqualTo(), length(), and raw_data().
next_
AstRawString* v8::internal::AstRawString::next_
Definition at line 130 of file ast-value-factory.h.
Referenced by next(), and next_location().
raw_hash_field_
uint32_t v8::internal::AstRawString::raw_hash_field_ [private]
Definition at line 135 of file ast-value-factory.h.
Referenced by Hash(), Internalize(), IsIntegerIndex(), and raw_hash_field().
string_
IndirectHandle<String> v8::internal::AstRawString::string_
Definition at line 131 of file ast-value-factory.h.
Referenced by set_string(), and string().
Zone
friend v8::internal::AstRawString::Zone [private]
Definition at line 102 of file ast-value-factory.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast-value-factory.h
/mnt/V8SourceCode/src/ast/ast-value-factory.cc