v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer Class Reference
Classes
struct ErrorInfo
Public Member Functions
ObjectVisitorDeepFreezer (i::Isolate *isolate, Context::DeepFreezeDelegate *delegate)
bool DeepFreeze (i::DirectHandle< i::Context > context)
void VisitPointers (i::Tagged< i::HeapObject > host, i::ObjectSlot start, i::ObjectSlot end) final
void VisitPointers (i::Tagged< i::HeapObject > host, i::MaybeObjectSlot start, i::MaybeObjectSlot end) final
void VisitMapPointer (i::Tagged< i::HeapObject > host) final
void VisitInstructionStreamPointer (i::Tagged< i::Code > host, i::InstructionStreamSlot slot) final
void VisitCustomWeakPointers (i::Tagged< i::HeapObject > host, i::ObjectSlot start, i::ObjectSlot end) final
Private Member Functions
template<typename TSlot >
void VisitPointersImpl (TSlot start, TSlot end)
bool FreezeEmbedderObjectAndVisitChildren (i::DirectHandle< i::JSObject > obj)
bool VisitObject (i::Tagged< i::HeapObject > obj)
bool InstantiateAndVisitLazyAccessorPairs ()
Private Attributes
i::Isolate * isolate_
Context::DeepFreezeDelegate * delegate_
std::unordered_set< i::Tagged< i::Object >, i::Object::Hasher > done_list_
i::DirectHandleVector< i::JSReceiver > objects_to_freeze_
i::DirectHandleVector< i::AccessorPair > lazy_accessor_pairs_to_freeze_
std::optional< ErrorInfo > error_
Detailed Description
Definition at line 6899 of file api.cc.
Constructor & Destructor Documentation
ObjectVisitorDeepFreezer()
v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::ObjectVisitorDeepFreezer (i::Isolate * isolate, Context::DeepFreezeDelegate * delegate) [inline], [explicit]
Definition at line 6901 of file api.cc.
      : isolate_(isolate),
        delegate_(delegate),
        objects_to_freeze_(isolate),
        lazy_accessor_pairs_to_freeze_(isolate) {}
Member Function Documentation
DeepFreeze()
bool v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::DeepFreeze (i::DirectHandle< i::Context > context) [inline]
Definition at line 6908 of file api.cc.
                                                   {
    bool success = VisitObject(i::Cast<i::HeapObject>(*context));
    if (success) {
      success = InstantiateAndVisitLazyAccessorPairs();
    }
    DCHECK_EQ(success, !error_.has_value());
    if (!success) {
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate_, NewTypeError(error_->msg_id, error_->name), false);
    }
    for (const auto& obj : objects_to_freeze_) {
      MAYBE_RETURN_ON_EXCEPTION_VALUE(
          isolate_,
          i::JSReceiver::SetIntegrityLevel(isolate_, obj, i::FROZEN,
                                           i::kThrowOnError),
          false);
    }
    return true;
  }
References DCHECK_EQ, v8::internal::FROZEN, v8::internal::kThrowOnError, MAYBE_RETURN_ON_EXCEPTION_VALUE, v8::internal::JSReceiver::SetIntegrityLevel(), THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::VisitObject().
FreezeEmbedderObjectAndVisitChildren()
bool v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::FreezeEmbedderObjectAndVisitChildren (i::DirectHandle< i::JSObject > obj) [inline], [private]
Definition at line 6963 of file api.cc.
                                                                          {
    DCHECK(delegate_);
    LocalVector<Object> children(reinterpret_cast<Isolate*>(isolate_));
    if (!delegate_->FreezeEmbedderObjectAndGetChildren(Utils::ToLocal(obj),
                                                       children)) {
      return false;
    }
    for (auto child : children) {
      if (!VisitObject(
              *Utils::OpenDirectHandle<Object, i::JSReceiver>(child))) {
        return false;
      }
    }
    return true;
  }
References DCHECK, and v8::internal::VisitObject().
InstantiateAndVisitLazyAccessorPairs()
bool v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::InstantiateAndVisitLazyAccessorPairs () [inline], [private]
Definition at line 7081 of file api.cc.
                                              {
    i::DirectHandle<i::NativeContext> native_context =
        isolate_->native_context();
    i::DirectHandleVector<i::AccessorPair> lazy_accessor_pairs_to_freeze(
        isolate_);
    std::swap(lazy_accessor_pairs_to_freeze, lazy_accessor_pairs_to_freeze_);
    for (const auto& accessor_pair : lazy_accessor_pairs_to_freeze) {
      i::AccessorPair::GetComponent(isolate_, native_context, accessor_pair,
                                    i::ACCESSOR_GETTER);
      i::AccessorPair::GetComponent(isolate_, native_context, accessor_pair,
                                    i::ACCESSOR_SETTER);
      VisitObject(*accessor_pair);
    }
    // Ensure no new lazy accessor pairs were discovered.
    CHECK_EQ(lazy_accessor_pairs_to_freeze_.size(), 0);
    return true;
  }
References v8::internal::ACCESSOR_GETTER, v8::internal::ACCESSOR_SETTER, CHECK_EQ, v8::internal::AccessorPair::GetComponent(), v8::internal::native_context, and v8::internal::VisitObject().
VisitCustomWeakPointers()
void v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitCustomWeakPointers (i::Tagged< i::HeapObject > host, i::ObjectSlot start, i::ObjectSlot end) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 6941 of file api.cc.
                                                                         {}
VisitInstructionStreamPointer()
void v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitInstructionStreamPointer (i::Tagged< i::Code > host, i::InstructionStreamSlot slot) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 6939 of file api.cc.
                                                                        {}
VisitMapPointer()
void v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitMapPointer (i::Tagged< i::HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 6936 of file api.cc.
                                                        {
    VisitPointer(host, host->map_slot());
  }
VisitObject()
bool v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitObject (i::Tagged< i::HeapObject > obj) [inline], [private]
Definition at line 6979 of file api.cc.
                                             {
    DCHECK(!obj.is_null());
    if (error_.has_value()) {
      return false;
    }
    i::DisallowGarbageCollection no_gc;
    i::InstanceType obj_type = obj->map()->instance_type();
    // Skip common types that can't contain items to freeze.
    if (!MayContainObjectsToFreeze(obj_type)) {
      return true;
    }
    if (!done_list_.insert(obj).second) {
      // If we couldn't insert (because it is already in the set) then we're
      // done.
      return true;
    }
    if (i::InstanceTypeChecker::IsAccessorPair(obj_type)) {
      // For AccessorPairs we need to ensure that the functions they point to
      // have been instantiated into actual JavaScript objects that can be
      // frozen. If they haven't then we need to save them to instantiate
      // (and recurse) before freezing.
      i::Tagged<i::AccessorPair> accessor_pair = i::Cast<i::AccessorPair>(obj);
      if (i::IsFunctionTemplateInfo(accessor_pair->getter()) ||
          IsFunctionTemplateInfo(accessor_pair->setter())) {
        i::DirectHandle<i::AccessorPair> lazy_accessor_pair(accessor_pair,
                                                            isolate_);
        lazy_accessor_pairs_to_freeze_.push_back(lazy_accessor_pair);
      }
    } else if (i::InstanceTypeChecker::IsContext(obj_type)) {
      // For contexts we need to ensure that all accessible locals are const.
      // If not they could be replaced to bypass freezing.
      i::Tagged<i::ScopeInfo> scope_info =
          i::Cast<i::Context>(obj)->scope_info();
      for (auto it : i::ScopeInfo::IterateLocalNames(scope_info, no_gc)) {
        if (!IsImmutableLexicalVariableMode(
                scope_info->ContextLocalMode(it->index()))) {
          DCHECK(!error_.has_value());
          error_ = ErrorInfo{i::MessageTemplate::kCannotDeepFreezeValue,
                             i::direct_handle(it->name(), isolate_)};
          return false;
        }
      }
    } else if (i::InstanceTypeChecker::IsJSReceiver(obj_type)) {
      i::DirectHandle<i::JSReceiver> receiver(i::Cast<i::JSReceiver>(obj),
                                              isolate_);
      if (RequiresEmbedderSupportToFreeze(obj_type)) {
        auto js_obj = i::Cast<i::JSObject>(receiver);
        // External objects don't have slots but still need to be processed by
        // the embedder.
        if (i::InstanceTypeChecker::IsJSExternalObject(obj_type) ||
            js_obj->GetEmbedderFieldCount() > 0) {
          if (!delegate_) {
            DCHECK(!error_.has_value());
            error_ =
                ErrorInfo{i::MessageTemplate::kCannotDeepFreezeObject,
                          i::direct_handle(receiver->class_name(), isolate_)};
            return false;
          }
          // Handle embedder specific types and any v8 children it wants to
          // freeze.
          if (!FreezeEmbedderObjectAndVisitChildren(js_obj)) {
            return false;
          }
        } else {
          DCHECK_EQ(js_obj->GetEmbedderFieldCount(), 0);
        }
      } else {
        DCHECK_IMPLIES(
            i::InstanceTypeChecker::IsJSObject(obj_type),
            i::Cast<i::JSObject>(*receiver)->GetEmbedderFieldCount() == 0);
        if (!IsJSReceiverSafeToFreeze(obj_type)) {
          DCHECK(!error_.has_value());
          error_ =
              ErrorInfo{i::MessageTemplate::kCannotDeepFreezeObject,
                        i::direct_handle(receiver->class_name(), isolate_)};
          return false;
        }
      }
      // Save this to freeze after we are done. Freezing triggers garbage
      // collection which doesn't work well with this visitor pattern, so we
      // delay it until after.
      objects_to_freeze_.push_back(receiver);
    } else {
      DCHECK(!i::InstanceTypeChecker::IsAccessorPair(obj_type));
      DCHECK(!i::InstanceTypeChecker::IsContext(obj_type));
      DCHECK(!i::InstanceTypeChecker::IsJSReceiver(obj_type));
    }
    DCHECK(!error_.has_value());
    i::VisitObject(isolate_, obj, this);
    // Iterate sets error_ on failure. We should propagate errors.
    return !error_.has_value();
  }
References DCHECK, DCHECK_EQ, DCHECK_IMPLIES, v8::internal::direct_handle(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsImmutableLexicalVariableMode(), v8::anonymous_namespace{api.cc}::IsJSReceiverSafeToFreeze(), v8::internal::ScopeInfo::IterateLocalNames(), v8::anonymous_namespace{api.cc}::MayContainObjectsToFreeze(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::anonymous_namespace{api.cc}::RequiresEmbedderSupportToFreeze(), and v8::internal::VisitObject().
VisitPointers() [1/2]
void v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitPointers (i::Tagged< i::HeapObject > host, i::MaybeObjectSlot start, i::MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 6932 of file api.cc.
                                                 {
    VisitPointersImpl(start, end);
  }
References v8::internal::compiler::end().
VisitPointers() [2/2]
void v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitPointers (i::Tagged< i::HeapObject > host, i::ObjectSlot start, i::ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 6928 of file api.cc.
                                            {
    VisitPointersImpl(start, end);
  }
References v8::internal::compiler::end().
VisitPointersImpl()
template<typename TSlot >
void v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitPointersImpl (TSlot start, TSlot end) [inline], [private]
Definition at line 6951 of file api.cc.
                                                 {
    for (TSlot current = start; current < end; ++current) {
      typename TSlot::TObject object = current.load(isolate_);
      i::Tagged<i::HeapObject> heap_object;
      if (object.GetHeapObjectIfStrong(&heap_object)) {
        if (!VisitObject(heap_object)) {
          return;
        }
      }
    }
  }
References v8::internal::compiler::end(), and v8::internal::VisitObject().
Member Data Documentation
delegate_
Context::DeepFreezeDelegate* v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::delegate_ [private]
Definition at line 7102 of file api.cc.
done_list_
std::unordered_set<i::Tagged<i::Object>, i::Object::Hasher> v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::done_list_ [private]
Definition at line 7103 of file api.cc.
error_
std::optional<ErrorInfo> v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::error_ [private]
Definition at line 7106 of file api.cc.
isolate_
i::Isolate* v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::isolate_ [private]
Definition at line 7101 of file api.cc.
lazy_accessor_pairs_to_freeze_
i::DirectHandleVector<i::AccessorPair> v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::lazy_accessor_pairs_to_freeze_ [private]
Definition at line 7105 of file api.cc.
objects_to_freeze_
i::DirectHandleVector<i::JSReceiver> v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::objects_to_freeze_ [private]
Definition at line 7104 of file api.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/api/api.cc