v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope Class Reference
Public Types
enum Kind : uint8_t { kEffect
, kValue
, kValueAsPropertyKey
, kTest
 }
Public Member Functions
ExpressionResultScope (BytecodeGenerator *generator, Kind kind)
~ExpressionResultScope ()
ExpressionResultScope (const ExpressionResultScope &)=delete
ExpressionResultScope & operator= (const ExpressionResultScope &)=delete
bool IsEffect () const
bool IsValue () const
bool IsValueAsPropertyKey () const
bool IsTest () const
TestResultScope * AsTest ()
void SetResultIsBoolean ()
void SetResultIsString ()
void SetResultIsInternalizedString ()
TypeHint type_hint () const
Private Attributes
ExpressionResultScope * outer_
RegisterAllocationScope allocator_
Kind kind_
TypeHint type_hint_
Detailed Description
Definition at line 705 of file bytecode-generator.cc.
Member Enumeration Documentation
Kind
enum v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::Kind : uint8_t
Enumerator
kEffect
kValue
kValueAsPropertyKey
kTest
Definition at line 707 of file bytecode-generator.cc.
            : uint8_t {
    // Evaluated for its side effects.
    kEffect,
    // Evaluated for its value (and side effects).
    kValue,
    kValueAsPropertyKey,
    // Evaluated for control flow (and side effects).
    kTest,
  };
Constructor & Destructor Documentation
ExpressionResultScope() [1/2]
v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::ExpressionResultScope (BytecodeGenerator * generator, Kind kind) [inline]
Definition at line 717 of file bytecode-generator.cc.
      : outer_(generator->execution_result()),
        allocator_(generator),
        kind_(kind),
        type_hint_(TypeHint::kUnknown) {
    generator->set_execution_result(this);
  }
References v8::internal::interpreter::BytecodeGenerator::set_execution_result().
 ExpressionResultScope()
v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::~ExpressionResultScope () [inline]
Definition at line 725 of file bytecode-generator.cc.
                           {
    allocator_.generator()->set_execution_result(outer_);
  }
ExpressionResultScope() [2/2]
v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::ExpressionResultScope (const ExpressionResultScope &) [delete]
Member Function Documentation
AsTest()
TestResultScope* v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest () [inline]
Definition at line 737 of file bytecode-generator.cc.
                            {
    DCHECK(IsTest());
    return reinterpret_cast<TestResultScope*>(this);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil(), v8::internal::interpreter::BytecodeGenerator::VisitInSameTestExecutionScope(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalTest(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest(), v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNot(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression().
IsEffect()
bool v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::IsEffect () const [inline]
Definition at line 732 of file bytecode-generator.cc.
{ return kind_ == kEffect; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment().
IsTest()
bool v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::IsTest () const [inline]
Definition at line 735 of file bytecode-generator.cc.
{ return kind_ == kTest; }
IsValue()
bool v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::IsValue () const [inline]
Definition at line 733 of file bytecode-generator.cc.
{ return kind_ == kValue; }
References v8::internal::kValue.
IsValueAsPropertyKey()
bool v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::IsValueAsPropertyKey () const [inline]
Definition at line 734 of file bytecode-generator.cc.
{ return kind_ == kValueAsPropertyKey; }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression().
operator=()
ExpressionResultScope& v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::operator= (const ExpressionResultScope &) [delete]
SetResultIsBoolean()
void v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::SetResultIsBoolean () [inline]
Definition at line 743 of file bytecode-generator.cc.
                            {
    DCHECK_EQ(type_hint_, TypeHint::kUnknown);
    type_hint_ = TypeHint::kBoolean;
  }
References DCHECK_EQ.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), and v8::internal::interpreter::BytecodeGenerator::VisitNot().
SetResultIsInternalizedString()
void v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::SetResultIsInternalizedString () [inline]
Definition at line 753 of file bytecode-generator.cc.
                                       {
    DCHECK_EQ(type_hint_, TypeHint::kUnknown);
    type_hint_ = TypeHint::kInternalizedString;
  }
References DCHECK_EQ.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitTypeOf().
SetResultIsString()
void v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::SetResultIsString () [inline]
Definition at line 748 of file bytecode-generator.cc.
                           {
    DCHECK_EQ(type_hint_, TypeHint::kUnknown);
    type_hint_ = TypeHint::kString;
  }
References DCHECK_EQ.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression().
type_hint()
TypeHint v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::type_hint () const [inline]
Definition at line 758 of file bytecode-generator.cc.
{ return type_hint_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitForAccumulatorValueImpl(), v8::internal::interpreter::BytecodeGenerator::VisitForTest(), and v8::internal::interpreter::BytecodeGenerator::VisitInSameTestExecutionScope().
Member Data Documentation
allocator_
RegisterAllocationScope v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::allocator_ [private]
Definition at line 762 of file bytecode-generator.cc.
kind_
Kind v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::kind_ [private]
Definition at line 763 of file bytecode-generator.cc.
outer_
ExpressionResultScope* v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::outer_ [private]
Definition at line 761 of file bytecode-generator.cc.
type_hint_
TypeHint v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::type_hint_ [private]
Definition at line 764 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc