v8::internal::ConservativeTracedHandlesMarkingVisitor Class Reference
#include <traced-handles-marking-visitor.h>
Public Member Functions
ConservativeTracedHandlesMarkingVisitor (Heap &, MarkingWorklists::Local &, cppgc::internal::CollectionType)
~ConservativeTracedHandlesMarkingVisitor () override=default
void VisitPointer (const void *) override
Private Attributes
Heap & heap_
MarkingState & marking_state_
MarkingWorklists::Local & local_marking_worklist_
const TracedHandles::NodeBounds traced_node_bounds_
const TracedHandles::MarkMode mark_mode_
Detailed Description
Definition at line 19 of file traced-handles-marking-visitor.h.
Constructor & Destructor Documentation
ConservativeTracedHandlesMarkingVisitor()
v8::internal::ConservativeTracedHandlesMarkingVisitor::ConservativeTracedHandlesMarkingVisitor (Heap & heap, MarkingWorklists::Local & local_marking_worklist, cppgc::internal::CollectionType collection_type)
Definition at line 17 of file traced-handles-marking-visitor.cc.
    : heap_(heap),
      marking_state_(*heap_.marking_state()),
      local_marking_worklist_(local_marking_worklist),
      traced_node_bounds_(heap.isolate()->traced_handles()->GetNodeBounds()),
      mark_mode_(collection_type == cppgc::internal::CollectionType::kMinor
                     ? TracedHandles::MarkMode::kOnlyYoung
                     : TracedHandles::MarkMode::kAll) {}
 ConservativeTracedHandlesMarkingVisitor()
v8::internal::ConservativeTracedHandlesMarkingVisitor::~ConservativeTracedHandlesMarkingVisitor () [override], [default]
Member Function Documentation
VisitPointer()
void v8::internal::ConservativeTracedHandlesMarkingVisitor::VisitPointer (const void * address) [override], [virtual]
Implements heap::base::StackVisitor.
Definition at line 29 of file traced-handles-marking-visitor.cc.
                         {
  const auto upper_it = std::upper_bound(
      traced_node_bounds_.begin(), traced_node_bounds_.end(), address,
      [](const void* needle, const auto& pair) { return needle < pair.first; });
  // Also checks emptiness as begin() == end() on empty bounds.
  if (upper_it == traced_node_bounds_.begin()) return;
  const auto bounds = std::next(upper_it, -1);
  if (address < bounds->second) {
    auto object = TracedHandles::MarkConservatively(
        const_cast<Address*>(reinterpret_cast<const Address*>(address)),
        const_cast<Address*>(reinterpret_cast<const Address*>(bounds->first)),
        mark_mode_);
    if (!IsHeapObject(object)) {
      // The embedder is not aware of whether numbers are materialized as heap
      // objects are just passed around as Smis. This branch also filters out
      // intentionally passed `Smi::zero()` that indicate that there's no
      // object to mark.
      return;
    }
    Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
    const auto target_worklist =
        MarkingHelper::ShouldMarkObject(&heap_, heap_object);
    if (target_worklist) {
      MarkingHelper::TryMarkAndPush(&heap_, &local_marking_worklist_,
                                    &marking_state_, target_worklist.value(),
                                    heap_object);
    }
  }
}
References heap_, v8::internal::IsHeapObject(), local_marking_worklist_, mark_mode_, v8::internal::TracedHandles::MarkConservatively(), marking_state_, v8::internal::MarkingHelper::ShouldMarkObject(), traced_node_bounds_, and v8::internal::MarkingHelper::TryMarkAndPush().
Member Data Documentation
heap_
Heap& v8::internal::ConservativeTracedHandlesMarkingVisitor::heap_ [private]
Definition at line 29 of file traced-handles-marking-visitor.h.
Referenced by VisitPointer().
local_marking_worklist_
MarkingWorklists::Local& v8::internal::ConservativeTracedHandlesMarkingVisitor::local_marking_worklist_ [private]
Definition at line 31 of file traced-handles-marking-visitor.h.
Referenced by VisitPointer().
mark_mode_
const TracedHandles::MarkMode v8::internal::ConservativeTracedHandlesMarkingVisitor::mark_mode_ [private]
Definition at line 33 of file traced-handles-marking-visitor.h.
Referenced by VisitPointer().
marking_state_
MarkingState& v8::internal::ConservativeTracedHandlesMarkingVisitor::marking_state_ [private]
Definition at line 30 of file traced-handles-marking-visitor.h.
Referenced by VisitPointer().
traced_node_bounds_
const TracedHandles::NodeBounds v8::internal::ConservativeTracedHandlesMarkingVisitor::traced_node_bounds_ [private]
Definition at line 32 of file traced-handles-marking-visitor.h.
Referenced by VisitPointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/traced-handles-marking-visitor.h
/mnt/V8SourceCode/src/heap/traced-handles-marking-visitor.cc