v8::internal::TrustedObject Class Reference
#include <trusted-object.h>
Public Member Functions
Tagged< TrustedObject > ReadProtectedPointerField (int offset) const
Tagged< TrustedObject > ReadProtectedPointerField (int offset, AcquireLoadTag) const
void WriteProtectedPointerField (int offset, Tagged< TrustedObject > value)
void WriteProtectedPointerField (int offset, Tagged< TrustedObject > value, ReleaseStoreTag)
bool IsProtectedPointerFieldEmpty (int offset) const
bool IsProtectedPointerFieldEmpty (int offset, AcquireLoadTag) const
void ClearProtectedPointerField (int offset)
void ClearProtectedPointerField (int offset, ReleaseStoreTag)
ProtectedPointerSlot RawProtectedPointerField (int byte_offset) const
ProtectedMaybeObjectSlot RawProtectedMaybeObjectField (int byte_offset) const
OBJECT_CONSTRUCTORS (TrustedObject, HeapObject)
Static Public Attributes
static constexpr int kHeaderSize = HeapObject::kHeaderSize
Additional Inherited Members
Detailed Description
Definition at line 33 of file trusted-object.h.
Member Function Documentation
ClearProtectedPointerField() [1/2]
void v8::internal::TrustedObject::ClearProtectedPointerField (int offset) [inline]
Definition at line 60 of file trusted-object-inl.h.
                                                         {
  TaggedField<Object, 0, TrustedSpaceCompressionScheme>::store(*this, offset,
                                                               Smi::zero());
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store(), and v8::internal::Smi::zero().
Referenced by v8::internal::WasmDispatchTable::Clear(), and v8::internal::Code::clear_deoptimization_data_and_interpreter_data().
ClearProtectedPointerField() [2/2]
void v8::internal::TrustedObject::ClearProtectedPointerField (int offset, ReleaseStoreTag) [inline]
Definition at line 65 of file trusted-object-inl.h.
                                                                          {
  TaggedField<Object, 0, TrustedSpaceCompressionScheme>::Release_Store(
      *this, offset, Smi::zero());
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), and v8::internal::Smi::zero().
IsProtectedPointerFieldEmpty() [1/2]
bool v8::internal::TrustedObject::IsProtectedPointerFieldEmpty (int offset) const [inline]
Definition at line 49 of file trusted-object-inl.h.
                                                                 {
  return TaggedField<Object, 0, TrustedSpaceCompressionScheme>::load(
             *this, offset) == Smi::zero();
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::load(), and v8::internal::Smi::zero().
Referenced by v8::internal::Code::has_deoptimization_data_or_interpreter_data().
IsProtectedPointerFieldEmpty() [2/2]
bool v8::internal::TrustedObject::IsProtectedPointerFieldEmpty (int offset, AcquireLoadTag) const [inline]
Definition at line 54 of file trusted-object-inl.h.
                                                                       {
  return TaggedField<Object, 0, TrustedSpaceCompressionScheme>::Acquire_Load(
             *this, offset) == Smi::zero();
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load(), and v8::internal::Smi::zero().
OBJECT_CONSTRUCTORS()
v8::internal::TrustedObject::OBJECT_CONSTRUCTORS (TrustedObject , HeapObject)
RawProtectedMaybeObjectField()
ProtectedMaybeObjectSlot v8::internal::TrustedObject::RawProtectedMaybeObjectField (int byte_offset) const [inline]
Definition at line 75 of file trusted-object-inl.h.
                           {
  return ProtectedMaybeObjectSlot(field_address(byte_offset));
}
References v8::internal::HeapObject::field_address().
RawProtectedPointerField()
ProtectedPointerSlot v8::internal::TrustedObject::RawProtectedPointerField (int byte_offset) const [inline]
Definition at line 70 of file trusted-object-inl.h.
                           {
  return ProtectedPointerSlot(field_address(byte_offset));
}
References v8::internal::HeapObject::field_address().
Referenced by v8::internal::InstructionStream::raw_code(), v8::internal::Code::raw_deoptimization_data_or_interpreter_data(), v8::internal::Code::raw_position_table(), and v8::internal::InstructionStream::unchecked_relocation_info().
ReadProtectedPointerField() [1/2]
Tagged< TrustedObject > v8::internal::TrustedObject::ReadProtectedPointerField (int offset) const [inline]
Definition at line 23 of file trusted-object-inl.h.
                      {
  return TaggedField<TrustedObject, 0, TrustedSpaceCompressionScheme>::load(
      *this, offset);
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::load().
Referenced by v8::internal::Code::bytecode_or_interpreter_data(), v8::internal::InstructionStream::relocation_info(), and v8::internal::Code::unchecked_deoptimization_data().
ReadProtectedPointerField() [2/2]
Tagged< TrustedObject > v8::internal::TrustedObject::ReadProtectedPointerField (int offset, AcquireLoadTag) const [inline]
Definition at line 29 of file trusted-object-inl.h.
                                      {
  return TaggedField<TrustedObject, 0,
                     TrustedSpaceCompressionScheme>::Acquire_Load(*this,
                                                                  offset);
}
References v8::base::Acquire_Load(), and v8::internal::TrustedObject.
WriteProtectedPointerField() [1/2]
void v8::internal::TrustedObject::WriteProtectedPointerField (int offset, Tagged< TrustedObject > value) [inline]
Definition at line 36 of file trusted-object-inl.h.
                                                                            {
  TaggedField<TrustedObject, 0, TrustedSpaceCompressionScheme>::store(
      *this, offset, value);
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store(), and v8::internal::value.
Referenced by v8::internal::Code::set_bytecode_or_interpreter_data(), v8::internal::WasmDispatchTable::SetForNonWrapper(), and v8::internal::WasmDispatchTable::SetForWrapper().
WriteProtectedPointerField() [2/2]
void v8::internal::TrustedObject::WriteProtectedPointerField (int offset, Tagged< TrustedObject > value, ReleaseStoreTag) [inline]
Definition at line 42 of file trusted-object-inl.h.
                                                                {
  TaggedField<TrustedObject, 0, TrustedSpaceCompressionScheme>::Release_Store(
      *this, offset, value);
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), and v8::internal::value.
Member Data Documentation
kHeaderSize
constexpr int v8::internal::TrustedObject::kHeaderSize = HeapObject::kHeaderSize [static], [constexpr]
Definition at line 66 of file trusted-object.h.
Referenced by v8::internal::MacroAssembler::BailoutIfDeoptimized(), v8::internal::Assembler::emit_code_relative_offset(), v8::internal::InstructionStream::Finalize(), v8::internal::InstructionStream::FromEntryAddress(), v8::internal::InstructionStream::FromTargetAddress(), v8::internal::InstructionStream::Initialize(), v8::internal::InstructionStream::instruction_start(), v8::internal::Assembler::label_at_put(), v8::internal::MemoryChunkLayout::ObjectStartOffsetInCodePage(), v8::internal::RegExpMacroAssemblerRISCV::PushBacktrack(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::InstructionStream::SizeFor(), v8::internal::Assembler::target_at_put(), and v8::internal::InstructionStream::TrailingPaddingSizeFor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/trusted-object.h
/mnt/V8SourceCode/src/objects/trusted-object-inl.h