v8::internal::OrderedHashMap Class Reference
#include <ordered-hash-table.h>
Public Member Functions
template<template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< OrderedHashMap >, DirectHandle< OrderedHashMap >>) static HandleType< OrderedHashMap > requires(std::is_convertible_v< HandleType< OrderedHashMap >, DirectHandle< OrderedHashMap >>) static HandleType< OrderedHashMap > void SetEntry (InternalIndex entry, Tagged< Object > key, Tagged< Object > value)
Tagged< Object > ValueAt (InternalIndex entry)
Static Public Member Functions
static MaybeHandle< OrderedHashMap > Add (Isolate *isolate, Handle< OrderedHashMap > table, DirectHandle< Object > key, DirectHandle< Object > value)
template<typename IsolateT >
static MaybeHandle< OrderedHashMap > Allocate (IsolateT *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
static MaybeHandle< OrderedHashMap > AllocateEmpty (Isolate *isolate, AllocationType allocation=AllocationType::kReadOnly)
static Address GetHash (Isolate *isolate, Address raw_key)
static Tagged< HeapObject > GetEmpty (ReadOnlyRoots ro_roots)
static Handle< Map > GetMap (RootsTable &roots)
static bool Is (DirectHandle< HeapObject > table)
Static Public Attributes
static const int kValueOffset = 1
static const int kPrefixSize = 0
Private Types
using Base = OrderedHashTable< OrderedHashMap, 2 >
Additional Inherited Members
Detailed Description
Definition at line 321 of file ordered-hash-table.h.
Member Typedef Documentation
Base
using v8::internal::OrderedHashMap::Base = OrderedHashTable<OrderedHashMap, 2> [private]
Definition at line 323 of file ordered-hash-table.h.
Member Function Documentation
Add()
MaybeHandle< OrderedHashMap > v8::internal::OrderedHashMap::Add (Isolate * isolate, Handle< OrderedHashMap > table, DirectHandle< Object > key, DirectHandle< Object > value) [static]
Definition at line 449 of file ordered-hash-table.cc.
                                                                            {
  int hash = Object::GetOrCreateHash(*key, isolate).value();
  if (table->NumberOfElements() > 0) {
    int raw_entry = table->HashToEntryRaw(hash);
    // Walk the chain of the bucket and try finding the key.
    {
      DisallowGarbageCollection no_gc;
      Tagged<Object> raw_key = *key;
      while (raw_entry != kNotFound) {
        Tagged<Object> candidate_key = table->KeyAt(InternalIndex(raw_entry));
        // Do not add if we have the key already
        if (Object::SameValueZero(candidate_key, raw_key)) return table;
        raw_entry = table->NextChainEntryRaw(raw_entry);
      }
    }
  }
  MaybeHandle<OrderedHashMap> table_candidate =
      OrderedHashMap::EnsureCapacityForAdding(isolate, table);
  if (!table_candidate.ToHandle(&table)) {
    return table_candidate;
  }
  DisallowGarbageCollection no_gc;
  Tagged<OrderedHashMap> raw_table = *table;
  // Read the existing bucket values.
  int bucket = raw_table->HashToBucket(hash);
  int previous_entry = raw_table->HashToEntryRaw(hash);
  int nof = raw_table->NumberOfElements();
  // Insert a new entry at the end,
  int new_entry = nof + raw_table->NumberOfDeletedElements();
  int new_index = raw_table->EntryToIndexRaw(new_entry);
  raw_table->set(new_index, *key);
  raw_table->set(new_index + kValueOffset, *value);
  raw_table->set(new_index + kChainOffset, Smi::FromInt(previous_entry));
  // and point the bucket to the new entry.
  raw_table->set(HashTableStartIndex() + bucket, Smi::FromInt(new_entry));
  raw_table->SetNumberOfElements(nof + 1);
  return table;
}
References v8::internal::Smi::FromInt(), v8::internal::Object::GetOrCreateHash(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::HashTableStartIndex(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::kChainOffset, v8::internal::key, v8::internal::OrderedHashTable< OrderedHashMap, 2 >::kNotFound, kValueOffset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::SameValueZero(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::table, v8::internal::MaybeHandle< T >::ToHandle(), v8::internal::FixedArray::value, and v8::internal::Tagged< Smi >::value().
Allocate()
template<typename IsolateT >
template V8_EXPORT_PRIVATE MaybeHandle< OrderedHashMap > v8::internal::OrderedHashMap::Allocate (IsolateT * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 609 of file ordered-hash-table.cc.
                                                                {
  return Base::Allocate(isolate, capacity, allocation);
}
References v8::internal::OrderedHashTable< OrderedHashMap, 2 >::Allocate().
Referenced by v8::internal::Factory::NewOrderedHashMap().
AllocateEmpty()
MaybeHandle< OrderedHashMap > v8::internal::OrderedHashMap::AllocateEmpty (Isolate * isolate, AllocationType allocation = AllocationType::kReadOnly) [static]
Definition at line 631 of file ordered-hash-table.cc.
                                                 {
  RootIndex ri = RootIndex::kEmptyOrderedHashMap;
  return Base::AllocateEmpty(isolate, allocation, ri);
}
References v8::internal::OrderedHashTable< OrderedHashMap, 2 >::AllocateEmpty().
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
GetEmpty()
Tagged< HeapObject > v8::internal::OrderedHashMap::GetEmpty (ReadOnlyRoots ro_roots) [static]
Definition at line 269 of file ordered-hash-table.cc.
                                                                  {
  return ro_roots.empty_ordered_hash_map();
}
GetHash()
Address v8::internal::OrderedHashMap::GetHash (Isolate * isolate, Address raw_key) [static]
Definition at line 438 of file ordered-hash-table.cc.
                                                                 {
  DisallowGarbageCollection no_gc;
  Tagged<Object> key(raw_key);
  Tagged<Object> hash = Object::GetHash(key);
  // If the object does not have an identity hash, it was never used as a key
  if (IsUndefined(hash, isolate)) return Smi::FromInt(-1).ptr();
  DCHECK(IsSmi(hash));
  DCHECK_GE(Cast<Smi>(hash).value(), 0);
  return hash.ptr();
}
References v8::internal::DCHECK(), DCHECK_GE, v8::internal::Smi::FromInt(), v8::internal::Object::GetHash(), v8::internal::IsSmi(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::FixedArray::value.
GetMap()
Handle< Map > v8::internal::OrderedHashMap::GetMap (RootsTable & roots) [inline], [static]
Definition at line 64 of file ordered-hash-table-inl.h.
                                                    {
  return roots.ordered_hash_map_map();
}
Is()
bool v8::internal::OrderedHashMap::Is (DirectHandle< HeapObject > table) [inline], [static]
Definition at line 160 of file ordered-hash-table-inl.h.
                                                             {
  return IsOrderedHashMap(*table);
}
References v8::internal::OrderedHashTable< OrderedHashMap, 2 >::table.
SetEntry()
template<template< typename > typename HandleType>
void v8::internal::OrderedHashMap::SetEntry (InternalIndex entry, Tagged< Object > key, Tagged< Object > value)
Definition at line 492 of file ordered-hash-table.cc.
                                                    {
  DisallowGarbageCollection no_gc;
  int index = EntryToIndex(entry);
  this->set(index, key);
  this->set(index + kValueOffset, value);
}
References v8::internal::OrderedHashTable< OrderedHashMap, 2 >::EntryToIndex(), v8::internal::FixedArray::index, v8::internal::key, kValueOffset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set(), and v8::internal::FixedArray::value.
ValueAt()
Tagged< Object > v8::internal::OrderedHashMap::ValueAt (InternalIndex entry) [inline]
Definition at line 84 of file ordered-hash-table-inl.h.
                                                                 {
  DCHECK_LT(entry.as_int(), UsedCapacity());
  return get(EntryToIndex(entry) + kValueOffset);
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::OrderedHashTable< OrderedHashMap, 2 >::EntryToIndex(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), kValueOffset, and v8::internal::OrderedHashTable< OrderedHashMap, 2 >::UsedCapacity().
Member Data Documentation
kPrefixSize
const int v8::internal::OrderedHashMap::kPrefixSize = 0 [static]
Definition at line 367 of file ordered-hash-table.h.
kValueOffset
const int v8::internal::OrderedHashMap::kValueOffset = 1 [static]
Definition at line 366 of file ordered-hash-table.h.
Referenced by Add(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapEntryValue(), v8::internal::CollectionsBuiltinsAssembler::LoadValueFromOrderedHashMapEntry(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), SetEntry(), v8::internal::CollectionsBuiltinsAssembler::StoreValueInOrderedHashMapEntry(), and ValueAt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table-inl.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc