v8::internal::wasm::AsyncStreamingDecoder::DecodingState Class Reference
Public Member Functions
virtual ~DecodingState ()=default
virtual size_t ReadBytes (AsyncStreamingDecoder *streaming, base::Vector< const uint8_t > bytes)
virtual std::unique_ptr< DecodingState > Next (AsyncStreamingDecoder *streaming)=0
virtual base::Vector< uint8_t > buffer ()=0
size_t offset () const
void set_offset (size_t value)
virtual bool is_finishing_allowed () const
Private Attributes
size_t offset_ = 0
Detailed Description
Definition at line 118 of file streaming-decoder.cc.
Constructor & Destructor Documentation
 DecodingState()
virtual v8::internal::wasm::AsyncStreamingDecoder::DecodingState::~DecodingState () [virtual], [default]
Member Function Documentation
buffer()
virtual base::Vector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::DecodingState::buffer () [pure virtual]
Implemented in v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody, v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload, v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID, v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader, and v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32.
Referenced by ReadBytes().
is_finishing_allowed()
virtual bool v8::internal::wasm::AsyncStreamingDecoder::DecodingState::is_finishing_allowed () const [inline], [virtual]
Reimplemented in v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID.
Definition at line 137 of file streaming-decoder.cc.
{ return false; }
Next()
virtual std::unique_ptr<DecodingState> v8::internal::wasm::AsyncStreamingDecoder::DecodingState::Next (AsyncStreamingDecoder * streaming) [pure virtual]
Implemented in v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody, v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload, v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID, v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader, and v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32.
offset()
size_t v8::internal::wasm::AsyncStreamingDecoder::DecodingState::offset () const [inline]
Definition at line 133 of file streaming-decoder.cc.
{ return offset_; }
Referenced by ReadBytes().
ReadBytes()
size_t v8::internal::wasm::AsyncStreamingDecoder::DecodingState::ReadBytes (AsyncStreamingDecoder * streaming, base::Vector< const uint8_t > bytes) [virtual]
Reimplemented in v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32.
Definition at line 274 of file streaming-decoder.cc.
                                                                       {
  base::Vector<uint8_t> remaining_buf = buffer() + offset();
  size_t num_bytes = std::min(bytes.size(), remaining_buf.size());
  TRACE_STREAMING("ReadBytes(%zu bytes)\n", num_bytes);
  memcpy(remaining_buf.begin(), &bytes.first(), num_bytes);
  set_offset(offset() + num_bytes);
  return num_bytes;
}
References v8::base::Vector< T >::begin(), buffer(), v8::base::Vector< T >::first(), offset(), set_offset(), v8::base::Vector< T >::size(), and TRACE_STREAMING.
set_offset()
void v8::internal::wasm::AsyncStreamingDecoder::DecodingState::set_offset (size_t value) [inline]
Definition at line 134 of file streaming-decoder.cc.
{ offset_ = value; }
References v8::internal::value.
Referenced by ReadBytes().
Member Data Documentation
offset_
size_t v8::internal::wasm::AsyncStreamingDecoder::DecodingState::offset_ = 0 [private]
Definition at line 140 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc