v8::internal::interpreter::BlockCoverageBuilder Class Reference
#include <block-coverage-builder.h>
Public Member Functions
BlockCoverageBuilder (Zone *zone, BytecodeArrayBuilder *builder, SourceRangeMap *source_range_map)
int AllocateBlockCoverageSlot (ZoneObject *node, SourceRangeKind kind)
int AllocateNaryBlockCoverageSlot (NaryOperation *node, size_t index)
int AllocateConditionalChainBlockCoverageSlot (ConditionalChain *node, SourceRangeKind kind, size_t index)
void IncrementBlockCounter (int coverage_array_slot)
void IncrementBlockCounter (ZoneObject *node, SourceRangeKind kind)
const ZoneVector< SourceRange > & slots () const
Static Public Attributes
static constexpr int kNoCoverageArraySlot = -1
Private Attributes
ZoneVector< SourceRange > slots_
BytecodeArrayBuilder * builder_
SourceRangeMap * source_range_map_
Detailed Description
Definition at line 19 of file block-coverage-builder.h.
Constructor & Destructor Documentation
BlockCoverageBuilder()
v8::internal::interpreter::BlockCoverageBuilder::BlockCoverageBuilder (Zone * zone, BytecodeArrayBuilder * builder, SourceRangeMap * source_range_map) [inline]
Definition at line 21 of file block-coverage-builder.h.
      : slots_(0, zone),
        builder_(builder),
        source_range_map_(source_range_map) {
    DCHECK_NOT_NULL(builder);
    DCHECK_NOT_NULL(source_range_map);
  }
References DCHECK_NOT_NULL.
Member Function Documentation
AllocateBlockCoverageSlot()
int v8::internal::interpreter::BlockCoverageBuilder::AllocateBlockCoverageSlot (ZoneObject * node, SourceRangeKind kind) [inline]
Definition at line 32 of file block-coverage-builder.h.
                                                                        {
    AstNodeSourceRanges* ranges = source_range_map_->Find(node);
    if (ranges == nullptr) return kNoCoverageArraySlot;
    SourceRange range = ranges->GetRange(kind);
    if (range.IsEmpty()) return kNoCoverageArraySlot;
    const int slot = static_cast<int>(slots_.size());
    slots_.emplace_back(range);
    return slot;
  }
References v8::internal::SourceRangeMap::Find(), v8::internal::AstNodeSourceRanges::GetRange(), v8::internal::SourceRange::IsEmpty(), kNoCoverageArraySlot, slots_, and source_range_map_.
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateBlockCoverageSlotIfEnabled(), v8::internal::interpreter::ConditionalControlFlowBuilder::ConditionalControlFlowBuilder(), and IncrementBlockCounter().
AllocateConditionalChainBlockCoverageSlot()
int v8::internal::interpreter::BlockCoverageBuilder::AllocateConditionalChainBlockCoverageSlot (ConditionalChain * node, SourceRangeKind kind, size_t index) [inline]
Definition at line 57 of file block-coverage-builder.h.
                                                              {
    ConditionalChainSourceRanges* ranges =
        static_cast<ConditionalChainSourceRanges*>(
            source_range_map_->Find(node));
    if (ranges == nullptr) return kNoCoverageArraySlot;
    SourceRange range = ranges->GetRangeAtIndex(kind, index);
    if (range.IsEmpty()) return kNoCoverageArraySlot;
    const int slot = static_cast<int>(slots_.size());
    slots_.emplace_back(range);
    return slot;
  }
References v8::internal::SourceRangeMap::Find(), v8::internal::ConditionalChainSourceRanges::GetRangeAtIndex(), v8::internal::index, v8::internal::SourceRange::IsEmpty(), kNoCoverageArraySlot, slots_, and source_range_map_.
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateConditionalChainBlockCoverageSlotIfEnabled(), and v8::internal::interpreter::ConditionalChainControlFlowBuilder::ConditionalChainControlFlowBuilder().
AllocateNaryBlockCoverageSlot()
int v8::internal::interpreter::BlockCoverageBuilder::AllocateNaryBlockCoverageSlot (NaryOperation * node, size_t index) [inline]
Definition at line 44 of file block-coverage-builder.h.
                                                                       {
    NaryOperationSourceRanges* ranges =
        static_cast<NaryOperationSourceRanges*>(source_range_map_->Find(node));
    if (ranges == nullptr) return kNoCoverageArraySlot;
    SourceRange range = ranges->GetRangeAtIndex(index);
    if (range.IsEmpty()) return kNoCoverageArraySlot;
    const int slot = static_cast<int>(slots_.size());
    slots_.emplace_back(range);
    return slot;
  }
References v8::internal::SourceRangeMap::Find(), v8::internal::NaryOperationSourceRanges::GetRangeAtIndex(), v8::internal::index, v8::internal::SourceRange::IsEmpty(), kNoCoverageArraySlot, slots_, and source_range_map_.
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateNaryBlockCoverageSlotIfEnabled().
IncrementBlockCounter() [1/2]
void v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter (int coverage_array_slot) [inline]
Definition at line 73 of file block-coverage-builder.h.
                                                      {
    if (coverage_array_slot == kNoCoverageArraySlot) return;
    builder_->IncBlockCounter(coverage_array_slot);
  }
References builder_, v8::internal::interpreter::BytecodeArrayBuilder::IncBlockCounter(), and kNoCoverageArraySlot.
Referenced by v8::internal::interpreter::TryFinallyBuilder::BeginFinally(), v8::internal::interpreter::BytecodeGenerator::BuildIncrementBlockCoverageCounterIfEnabled(), v8::internal::interpreter::ConditionalControlFlowBuilder::Else(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::ElseAt(), v8::internal::interpreter::TryCatchBuilder::EndTry(), IncrementBlockCounter(), v8::internal::interpreter::LoopBuilder::LoopBody(), v8::internal::interpreter::ConditionalControlFlowBuilder::Then(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::ThenAt(), v8::internal::interpreter::BreakableControlFlowBuilder::~BreakableControlFlowBuilder(), v8::internal::interpreter::ConditionalControlFlowBuilder::~ConditionalControlFlowBuilder(), v8::internal::interpreter::TryCatchBuilder::~TryCatchBuilder(), and v8::internal::interpreter::TryFinallyBuilder::~TryFinallyBuilder().
IncrementBlockCounter() [2/2]
void v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter (ZoneObject * node, SourceRangeKind kind) [inline]
Definition at line 78 of file block-coverage-builder.h.
                                                                     {
    int slot = AllocateBlockCoverageSlot(node, kind);
    IncrementBlockCounter(slot);
  }
References AllocateBlockCoverageSlot(), and IncrementBlockCounter().
slots()
const ZoneVector<SourceRange>& v8::internal::interpreter::BlockCoverageBuilder::slots () const [inline]
Definition at line 83 of file block-coverage-builder.h.
{ return slots_; }
References slots_.
Referenced by v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode().
Member Data Documentation
builder_
BytecodeArrayBuilder* v8::internal::interpreter::BlockCoverageBuilder::builder_ [private]
Definition at line 89 of file block-coverage-builder.h.
Referenced by IncrementBlockCounter().
kNoCoverageArraySlot
constexpr int v8::internal::interpreter::BlockCoverageBuilder::kNoCoverageArraySlot = -1 [static], [constexpr]
Definition at line 30 of file block-coverage-builder.h.
Referenced by AllocateBlockCoverageSlot(), v8::internal::interpreter::BytecodeGenerator::AllocateBlockCoverageSlotIfEnabled(), AllocateConditionalChainBlockCoverageSlot(), v8::internal::interpreter::BytecodeGenerator::AllocateConditionalChainBlockCoverageSlotIfEnabled(), AllocateNaryBlockCoverageSlot(), v8::internal::interpreter::BytecodeGenerator::AllocateNaryBlockCoverageSlotIfEnabled(), v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::GetSlotFor(), and IncrementBlockCounter().
slots_
ZoneVector<SourceRange> v8::internal::interpreter::BlockCoverageBuilder::slots_ [private]
Definition at line 88 of file block-coverage-builder.h.
Referenced by AllocateBlockCoverageSlot(), AllocateConditionalChainBlockCoverageSlot(), AllocateNaryBlockCoverageSlot(), and slots().
source_range_map_
SourceRangeMap* v8::internal::interpreter::BlockCoverageBuilder::source_range_map_ [private]
Definition at line 90 of file block-coverage-builder.h.
Referenced by AllocateBlockCoverageSlot(), AllocateConditionalChainBlockCoverageSlot(), and AllocateNaryBlockCoverageSlot().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/block-coverage-builder.h