v8::internal::compiler::FixedDoubleArrayRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< FixedDoubleArray > object () const
Float64 GetFromImmutableFixedDoubleArray (int i) const
Detailed Description
Definition at line 1036 of file heap-refs.h.
Member Function Documentation
GetFromImmutableFixedDoubleArray()
Float64 v8::internal::compiler::FixedDoubleArrayRef::GetFromImmutableFixedDoubleArray (int i) const
Definition at line 1504 of file heap-refs.cc.
                                                                         {
  static_assert(ref_traits<FixedDoubleArray>::ref_serialization_kind ==
                RefSerializationKind::kNeverSerialized);
  CHECK(data_->should_access_heap());
  return Float64::FromBits(object()->get_representation(i));
}
References CHECK, v8::internal::Float64::FromBits(), and v8::internal::compiler::kNeverSerialized.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildFixedDoubleArray(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForDoubleFixedArray(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedDoubleArrayElement(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements().
object()
IndirectHandle<FixedDoubleArray> v8::internal::compiler::FixedDoubleArrayRef::object () const
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc