v8::internal::FeedbackSlot Class Reference
#include <utils.h>
Public Member Functions
FeedbackSlot ()
FeedbackSlot (int id)
int ToInt () const
bool IsInvalid () const
bool operator== (FeedbackSlot that) const
bool operator!= (FeedbackSlot that) const
FeedbackSlot WithOffset (int offset) const
Static Public Member Functions
static FeedbackSlot Invalid ()
Private Attributes
int id_
Static Private Attributes
static const int kInvalidSlot = -1
Friends
size_t hash_value (FeedbackSlot slot)
V8_EXPORT_PRIVATE friend std::ostream & operator<< (std::ostream &os, FeedbackSlot)
Detailed Description
Definition at line 645 of file utils.h.
Constructor & Destructor Documentation
FeedbackSlot() [1/2]
v8::internal::FeedbackSlot::FeedbackSlot () [inline]
Definition at line 647 of file utils.h.
: id_(kInvalidSlot) {}
Referenced by Invalid(), and WithOffset().
FeedbackSlot() [2/2]
v8::internal::FeedbackSlot::FeedbackSlot (int id) [inline], [explicit]
Definition at line 648 of file utils.h.
: id_(id) {}
Member Function Documentation
Invalid()
static FeedbackSlot v8::internal::FeedbackSlot::Invalid () [inline], [static]
Definition at line 652 of file utils.h.
{ return FeedbackSlot(); }
References FeedbackSlot().
Referenced by v8::internal::JSFunction::ClearAllTypeFeedbackInfoForTesting(), v8::internal::AccessorAssembler::GenerateLoadIC_NoFeedback(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::RUNTIME_FUNCTION(), v8::internal::KeyedStoreGenericAssembler::StoreIC_NoFeedback(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), and v8::internal::FeedbackVector::ToSlot().
IsInvalid()
bool v8::internal::FeedbackSlot::IsInvalid () const [inline]
Definition at line 653 of file utils.h.
{ return id_ == kInvalidSlot; }
References id_, and kInvalidSlot.
Referenced by v8::internal::TranslatedState::DoUpdateFeedback(), v8::internal::interpreter::BytecodeGenerator::feedback_index(), v8::internal::compiler::FeedbackSource::FeedbackSource(), v8::internal::SharedFeedbackSlot::Get(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadGlobalICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadSuperICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedStoreGlobalICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedStoreICSlot(), v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::compiler::JSTypeHintLowering::ReduceToNumberOperation(), and v8::internal::FeedbackVector::SetOptimizedOsrCode().
operator!=()
bool v8::internal::FeedbackSlot::operator!= (FeedbackSlot that) const [inline]
Definition at line 656 of file utils.h.
{ return !(*this == that); }
operator==()
bool v8::internal::FeedbackSlot::operator== (FeedbackSlot that) const [inline]
Definition at line 655 of file utils.h.
{ return this->id_ == that.id_; }
References id_.
ToInt()
int v8::internal::FeedbackSlot::ToInt () const [inline]
Definition at line 650 of file utils.h.
{ return id_; }
References id_.
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateLiteral(), v8::internal::FeedbackVector::GetIndex(), v8::internal::FeedbackVectorSpec::GetKind(), v8::internal::FeedbackMetadata::GetKind(), v8::internal::FeedbackMetadataIterator::HasNext(), v8::internal::FeedbackNexus::ic_state(), v8::internal::interpreter::LoopBuilder::JumpToHeader(), v8::internal::FeedbackMetadataIterator::Next(), v8::internal::TranslatedState::ReadUpdateFeedback(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::NexusConfig::SetFeedbackPair(), v8::internal::FeedbackMetadata::SetKind(), v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize(), v8::internal::FeedbackVector::SynchronizedGet(), v8::internal::FeedbackVector::SynchronizedSet(), v8::internal::MacroAssembler::TryLoadOptimizedOsrCode(), and v8::internal::baseline::BaselineAssembler::TryLoadOptimizedOsrCode().
WithOffset()
FeedbackSlot v8::internal::FeedbackSlot::WithOffset (int offset) const [inline]
Definition at line 662 of file utils.h.
                                            {
    return FeedbackSlot(id_ + offset);
  }
References FeedbackSlot(), and id_.
Referenced by v8::internal::NexusConfig::GetFeedbackPair(), v8::internal::FeedbackVector::New(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), and v8::internal::NexusConfig::SetFeedbackPair().
Friends And Related Function Documentation
hash_value
size_t hash_value (FeedbackSlot slot) [friend]
Definition at line 658 of file utils.h.
{ return slot.ToInt(); }
operator<<
V8_EXPORT_PRIVATE friend std::ostream& operator<< (std::ostream & os, FeedbackSlot) [friend]
Definition at line 26 of file utils.cc.
                                                          {
  return os << "#" << slot.id_;
}
Member Data Documentation
id_
int v8::internal::FeedbackSlot::id_ [private]
Definition at line 669 of file utils.h.
Referenced by IsInvalid(), operator==(), ToInt(), and WithOffset().
kInvalidSlot
const int v8::internal::FeedbackSlot::kInvalidSlot = -1 [static], [private]
Definition at line 667 of file utils.h.
Referenced by IsInvalid().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/utils.h