v8::internal::torque::UnionType Class Reference
#include <types.h>
Public Member Functions
std::string GetGeneratedTypeNameImpl () const override
std::string GetGeneratedTNodeTypeNameImpl () const override
std::string GetRuntimeType () const override
std::string GetDebugType () const override
std::string GetConstexprGeneratedTypeName () const override
bool operator== (const UnionType &other) const
std::optional< const Type * > GetSingleMember () const
bool IsSubtypeOf (const Type *other) const override
bool IsSupertypeOf (const Type *other) const
bool IsTransient () const override
bool IsConstexpr () const override
const Type * NonConstexprVersion () const override
void Extend (const Type *t)
std::string ToExplicitString () const override
void Subtract (const Type *t)
std::vector< TypeChecker > GetTypeCheckers () const override
Static Public Member Functions
static UnionType FromType (const Type *t)
Private Member Functions
UnionType (const Type *t)
void RecomputeParent ()
std::string SimpleNameImpl () const override
Static Private Member Functions
static void InsertGeneratedTNodeTypeName (std::set< std::string > &names, const Type *t)
static void InsertConstexprGeneratedTypeName (std::set< std::string > &names, const Type *t)
Private Attributes
std::set< const Type *, TypeLess > types_
Friends
size_t hash_value (const UnionType &p)
Additional Inherited Members
Detailed Description
Definition at line 389 of file types.h.
Constructor & Destructor Documentation
UnionType()
v8::internal::torque::UnionType::UnionType (const Type * t) [inline], [explicit], [private]
Definition at line 483 of file types.h.
: Type(Kind::kUnionType, t), types_({t}) {}
Member Function Documentation
Extend()
void v8::internal::torque::UnionType::Extend (const Type * t) [inline]
Definition at line 451 of file types.h.
                             {
    if (const UnionType* union_type = UnionType::DynamicCast(t)) {
      for (const Type* member : union_type->types_) {
        Extend(member);
      }
    } else {
      if (t->IsSubtypeOf(this)) return;
      set_parent(CommonSupertype(parent(), t));
      EraseIf(&types_,
              [&](const Type* member) { return member->IsSubtypeOf(t); });
      types_.insert(t);
    }
  }
References v8::internal::torque::EraseIf(), and v8::internal::torque::Type::IsSubtypeOf().
FromType()
static UnionType v8::internal::torque::UnionType::FromType (const Type * t) [inline], [static]
Definition at line 468 of file types.h.
                                           {
    const UnionType* union_type = UnionType::DynamicCast(t);
    return union_type ? UnionType(*union_type) : UnionType(t);
  }
References v8::internal::maglev::UnionType().
Referenced by v8::internal::torque::TypeOracle::GetUnionType().
GetConstexprGeneratedTypeName()
std::string v8::internal::torque::UnionType::GetConstexprGeneratedTypeName () const [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 350 of file types.cc.
                                                         {
  // For non-tagged unions, use the superclass GetConstexprGeneratedTypeName.
  for (const Type* t : types_) {
    if (!t->IsSubtypeOf(TypeOracle::GetTaggedType())) {
      return this->Type::GetConstexprGeneratedTypeName();
    }
  }
  // Allow some aliased simple names to be used as-is.
  std::string simple_name = SimpleName();
  if (simple_name == "Object") return simple_name;
  if (simple_name == "Number") return simple_name;
  if (simple_name == "Numeric") return simple_name;
  if (simple_name == "JSAny") return simple_name;
  if (simple_name == "JSPrimitive") return simple_name;
  // Deduplicate generated typenames and flatten unions.
  std::set<std::string> names;
  for (const Type* t : types_) {
    InsertConstexprGeneratedTypeName(names, t);
  }
  std::stringstream result;
  result << "Union<";
  bool first = true;
  for (std::string name : names) {
    if (!first) {
      result << ", ";
    }
    first = false;
    result << name;
  }
  result << ">";
  return result.str();
}
References name, v8::base::internal::result, and v8::internal::string.
GetDebugType()
std::string v8::internal::torque::UnionType::GetDebugType () const [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 385 of file types.cc.
{ return parent()->GetDebugType(); }
GetGeneratedTNodeTypeNameImpl()
std::string v8::internal::torque::UnionType::GetGeneratedTNodeTypeNameImpl () const [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 296 of file types.cc.
                                                         {
  // For non-tagged unions, use the parent GetGeneratedTNodeTypeName.
  for (const Type* t : types_) {
    if (!t->IsSubtypeOf(TypeOracle::GetTaggedType())) {
      return parent()->GetGeneratedTNodeTypeName();
    }
  }
  std::string simple_name = SimpleName();
  if (simple_name == "Object") return simple_name;
  if (simple_name == "Number") return simple_name;
  if (simple_name == "Numeric") return simple_name;
  if (simple_name == "JSAny") return simple_name;
  if (simple_name == "JSPrimitive") return simple_name;
  std::set<std::string> names;
  for (const Type* t : types_) {
    InsertGeneratedTNodeTypeName(names, t);
  }
  std::stringstream result;
  result << "Union<";
  bool first = true;
  for (std::string name : names) {
    if (!first) {
      result << ", ";
    }
    first = false;
    result << name;
  }
  result << ">";
  return result.str();
}
References name, v8::base::internal::result, and v8::internal::string.
GetGeneratedTypeNameImpl()
std::string v8::internal::torque::UnionType::GetGeneratedTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 392 of file types.h.
                                                      {
    return "TNode<" + GetGeneratedTNodeTypeName() + ">";
  }
GetRuntimeType()
std::string v8::internal::torque::UnionType::GetRuntimeType () const [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 329 of file types.cc.
                                          {
  for (const Type* t : types_) {
    if (!t->IsSubtypeOf(TypeOracle::GetTaggedType())) {
      return parent()->GetRuntimeType();
    }
  }
  return "Tagged<" + GetConstexprGeneratedTypeName() + ">";
}
GetSingleMember()
std::optional<const Type*> v8::internal::torque::UnionType::GetSingleMember () const [inline]
Definition at line 411 of file types.h.
                                                   {
    if (types_.size() == 1) {
      DCHECK_EQ(*types_.begin(), parent());
      return *types_.begin();
    }
    return std::nullopt;
  }
References DCHECK_EQ.
GetTypeCheckers()
std::vector<TypeChecker> v8::internal::torque::UnionType::GetTypeCheckers () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 473 of file types.h.
                                                          {
    std::vector<TypeChecker> result;
    for (const Type* member : types_) {
      std::vector<TypeChecker> sub_result = member->GetTypeCheckers();
      result.insert(result.end(), sub_result.begin(), sub_result.end());
    }
    return result;
  }
References v8::base::internal::result.
InsertConstexprGeneratedTypeName()
void v8::internal::torque::UnionType::InsertConstexprGeneratedTypeName (std::set< std::string > & names, const Type * t) [static], [private]
Definition at line 339 of file types.cc.
                                                                {
  if (t->IsUnionType()) {
    for (const Type* u : ((const UnionType*)t)->types_) {
      names.insert(u->GetConstexprGeneratedTypeName());
    }
  } else {
    names.insert(t->GetConstexprGeneratedTypeName());
  }
}
References v8::internal::torque::Type::GetConstexprGeneratedTypeName(), and v8::internal::torque::TypeBase::IsUnionType().
InsertGeneratedTNodeTypeName()
void v8::internal::torque::UnionType::InsertGeneratedTNodeTypeName (std::set< std::string > & names, const Type * t) [static], [private]
Definition at line 285 of file types.cc.
                                                            {
  if (t->IsUnionType()) {
    for (const Type* u : ((const UnionType*)t)->types_) {
      names.insert(u->GetGeneratedTNodeTypeName());
    }
  } else {
    names.insert(t->GetGeneratedTNodeTypeName());
  }
}
References v8::internal::torque::Type::GetGeneratedTNodeTypeName(), and v8::internal::torque::TypeBase::IsUnionType().
IsConstexpr()
bool v8::internal::torque::UnionType::IsConstexpr () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 444 of file types.h.
{ return parent()->IsConstexpr(); }
IsSubtypeOf()
bool v8::internal::torque::UnionType::IsSubtypeOf (const Type * other) const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 419 of file types.h.
                                                     {
    for (const Type* member : types_) {
      if (!member->IsSubtypeOf(other)) return false;
    }
    return true;
  }
IsSupertypeOf()
bool v8::internal::torque::UnionType::IsSupertypeOf (const Type * other) const [inline]
Definition at line 426 of file types.h.
                                              {
    for (const Type* member : types_) {
      if (other->IsSubtypeOf(member)) {
        return true;
      }
    }
    return false;
  }
References v8::internal::torque::Type::IsSubtypeOf().
IsTransient()
bool v8::internal::torque::UnionType::IsTransient () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 435 of file types.h.
                                    {
    for (const Type* member : types_) {
      if (member->IsTransient()) {
        return true;
      }
    }
    return false;
  }
NonConstexprVersion()
const Type* v8::internal::torque::UnionType::NonConstexprVersion () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 446 of file types.h.
                                                   {
    if (!IsConstexpr()) return this;
    return parent()->NonConstexprVersion();
  }
References v8::internal::torque::Type::NonConstexprVersion().
operator==()
bool v8::internal::torque::UnionType::operator== (const UnionType & other) const [inline]
Definition at line 407 of file types.h.
                                                {
    return types_ == other.types_;
  }
References types_.
RecomputeParent()
void v8::internal::torque::UnionType::RecomputeParent () [private]
Definition at line 387 of file types.cc.
                                {
  const Type* parent = nullptr;
  for (const Type* t : types_) {
    if (parent == nullptr) {
      parent = t;
    } else {
      parent = CommonSupertype(parent, t);
    }
  }
  set_parent(parent);
}
SimpleNameImpl()
std::string v8::internal::torque::UnionType::SimpleNameImpl () const [override], [private], [virtual]
Implements v8::internal::torque::Type.
Definition at line 271 of file types.cc.
                                          {
  std::stringstream result;
  bool first = true;
  for (const Type* t : types_) {
    if (!first) {
      result << "_OR_";
    }
    first = false;
    result << t->SimpleName();
  }
  return result.str();
}
References v8::base::internal::result.
Subtract()
void v8::internal::torque::UnionType::Subtract (const Type * t)
Definition at line 399 of file types.cc.
                                      {
  for (auto it = types_.begin(); it != types_.end();) {
    if ((*it)->IsSubtypeOf(t)) {
      it = types_.erase(it);
    } else {
      ++it;
    }
  }
  if (types_.empty()) types_.insert(TypeOracle::GetNeverType());
  RecomputeParent();
}
ToExplicitString()
std::string v8::internal::torque::UnionType::ToExplicitString () const [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 256 of file types.cc.
                                            {
  std::stringstream result;
  result << "(";
  bool first = true;
  for (const Type* t : types_) {
    if (!first) {
      result << " | ";
    }
    first = false;
    result << *t;
  }
  result << ")";
  return result.str();
}
References v8::base::internal::result.
Friends And Related Function Documentation
hash_value
size_t hash_value (const UnionType & p) [friend]
Definition at line 400 of file types.h.
                                               {
    size_t result = 0;
    for (const Type* t : p.types_) {
      result = base::hash_combine(result, t);
    }
    return result;
  }
Member Data Documentation
types_
std::set<const Type*, TypeLess> v8::internal::torque::UnionType::types_ [private]
Definition at line 492 of file types.h.
Referenced by operator==().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/types.h
/mnt/V8SourceCode/src/torque/types.cc