v8::Isolate Class Reference
Isolate represents an isolated instance of the V8 engine.
#include <v8-isolate.h>
Classes
class AllowJavascriptExecutionScope
Introduce exception to DisallowJavascriptExecutionScope.
struct CreateParams
Initial configuration parameters for a new Isolate.
class DisallowJavascriptExecutionScope
Assert that no Javascript code is invoked.
class Scope
Stack-allocated class which sets the isolate for all operations executed within a local scope.
class SuppressMicrotaskExecutionScope
Do not run microtasks while this scope is active, even if microtasks are automatically executed otherwise.
Public Types
enum GarbageCollectionType { kFullGarbageCollection
, kMinorGarbageCollection
 }
Types of garbage collections that can be requested via RequestGarbageCollectionForTesting.
enum UseCounterFeature {
kUseAsm = 0
, kBreakIterator = 1
, kOBSOLETE_LegacyConst = 2
, kOBSOLETE_MarkDequeOverflow = 3
,
kOBSOLETE_StoreBufferOverflow = 4
, kOBSOLETE_SlotsBufferOverflow = 5
, kOBSOLETE_ObjectObserve = 6
, kForcedGC = 7
,
kSloppyMode = 8
, kStrictMode = 9
, kOBSOLETE_StrongMode = 10
, kRegExpPrototypeStickyGetter = 11
,
kRegExpPrototypeToString = 12
, kRegExpPrototypeUnicodeGetter = 13
, kOBSOLETE_IntlV8Parse = 14
, kOBSOLETE_IntlPattern = 15
,
kOBSOLETE_IntlResolved = 16
, kOBSOLETE_PromiseChain = 17
, kOBSOLETE_PromiseAccept = 18
, kOBSOLETE_PromiseDefer = 19
,
kHtmlCommentInExternalScript = 20
, kHtmlComment = 21
, kSloppyModeBlockScopedFunctionRedefinition = 22
, kForInInitializer = 23
,
kOBSOLETE_ArrayProtectorDirtied = 24
, kArraySpeciesModified = 25
, kArrayPrototypeConstructorModified = 26
, kOBSOLETE_ArrayInstanceProtoModified = 27
,
kArrayInstanceConstructorModified = 28
, kOBSOLETE_LegacyFunctionDeclaration = 29
, kOBSOLETE_RegExpPrototypeSourceGetter = 30
, kOBSOLETE_RegExpPrototypeOldFlagGetter = 31
,
kDecimalWithLeadingZeroInStrictMode = 32
, kLegacyDateParser = 33
, kDefineGetterOrSetterWouldThrow = 34
, kFunctionConstructorReturnedUndefined = 35
,
kAssigmentExpressionLHSIsCallInSloppy = 36
, kAssigmentExpressionLHSIsCallInStrict = 37
, kPromiseConstructorReturnedUndefined = 38
, kOBSOLETE_ConstructorNonUndefinedPrimitiveReturn = 39
,
kOBSOLETE_LabeledExpressionStatement = 40
, kOBSOLETE_LineOrParagraphSeparatorAsLineTerminator = 41
, kIndexAccessor = 42
, kErrorCaptureStackTrace = 43
,
kErrorPrepareStackTrace = 44
, kErrorStackTraceLimit = 45
, kWebAssemblyInstantiation = 46
, kDeoptimizerDisableSpeculation = 47
,
kOBSOLETE_ArrayPrototypeSortJSArrayModifiedPrototype = 48
, kFunctionTokenOffsetTooLongForToString = 49
, kWasmSharedMemory = 50
, kWasmThreadOpcodes = 51
,
kOBSOLETE_AtomicsNotify = 52
, kOBSOLETE_AtomicsWake = 53
, kCollator = 54
, kNumberFormat = 55
,
kDateTimeFormat = 56
, kPluralRules = 57
, kRelativeTimeFormat = 58
, kLocale = 59
,
kListFormat = 60
, kSegmenter = 61
, kStringLocaleCompare = 62
, kOBSOLETE_StringToLocaleUpperCase = 63
,
kStringToLocaleLowerCase = 64
, kNumberToLocaleString = 65
, kDateToLocaleString = 66
, kDateToLocaleDateString = 67
,
kDateToLocaleTimeString = 68
, kAttemptOverrideReadOnlyOnPrototypeSloppy = 69
, kAttemptOverrideReadOnlyOnPrototypeStrict = 70
, kOBSOLETE_OptimizedFunctionWithOneShotBytecode = 71
,
kRegExpMatchIsTrueishOnNonJSRegExp = 72
, kRegExpMatchIsFalseishOnJSRegExp = 73
, kOBSOLETE_DateGetTimezoneOffset = 74
, kStringNormalize = 75
,
kCallSiteAPIGetFunctionSloppyCall = 76
, kCallSiteAPIGetThisSloppyCall = 77
, kOBSOLETE_RegExpMatchAllWithNonGlobalRegExp = 78
, kRegExpExecCalledOnSlowRegExp = 79
,
kRegExpReplaceCalledOnSlowRegExp = 80
, kDisplayNames = 81
, kSharedArrayBufferConstructed = 82
, kArrayPrototypeHasElements = 83
,
kObjectPrototypeHasElements = 84
, kNumberFormatStyleUnit = 85
, kDateTimeFormatRange = 86
, kDateTimeFormatDateTimeStyle = 87
,
kBreakIteratorTypeWord = 88
, kBreakIteratorTypeLine = 89
, kInvalidatedArrayBufferDetachingProtector = 90
, kInvalidatedArrayConstructorProtector
,
kInvalidatedArrayIteratorLookupChainProtector = 92
, kInvalidatedArraySpeciesLookupChainProtector = 93
, kInvalidatedIsConcatSpreadableLookupChainProtector = 94
, kInvalidatedMapIteratorLookupChainProtector = 95
,
kInvalidatedNoElementsProtector = 96
, kInvalidatedPromiseHookProtector = 97
, kInvalidatedPromiseResolveLookupChainProtector = 98
, kInvalidatedPromiseSpeciesLookupChainProtector = 99
,
kInvalidatedPromiseThenLookupChainProtector = 100
, kInvalidatedRegExpSpeciesLookupChainProtector = 101
, kInvalidatedSetIteratorLookupChainProtector = 102
, kInvalidatedStringIteratorLookupChainProtector = 103
,
kInvalidatedStringLengthOverflowLookupChainProtector = 104
, kInvalidatedTypedArraySpeciesLookupChainProtector = 105
, kWasmSimdOpcodes = 106
, kVarRedeclaredCatchBinding = 107
,
kWasmRefTypes = 108
, kOBSOLETE_WasmBulkMemory = 109
, kOBSOLETE_WasmMultiValue = 110
, kWasmExceptionHandling = 111
,
kInvalidatedMegaDOMProtector = 112
, kFunctionPrototypeArguments = 113
, kFunctionPrototypeCaller = 114
, kTurboFanOsrCompileStarted = 115
,
kAsyncStackTaggingCreateTaskCall = 116
, kDurationFormat = 117
, kInvalidatedNumberStringNotRegexpLikeProtector = 118
, kOBSOLETE_RegExpUnicodeSetIncompatibilitiesWithUnicodeMode = 119
,
kOBSOLETE_ImportAssertionDeprecatedSyntax = 120
, kLocaleInfoObsoletedGetters = 121
, kLocaleInfoFunctions = 122
, kCompileHintsMagicAll = 123
,
kInvalidatedNoProfilingProtector = 124
, kWasmMemory64 = 125
, kWasmMultiMemory = 126
, kWasmGC = 127
,
kWasmImportedStrings = 128
, kSourceMappingUrlMagicCommentAtSign = 129
, kTemporalObject = 130
, kWasmModuleCompilation = 131
,
kInvalidatedNoUndetectableObjectsProtector = 132
, kWasmJavaScriptPromiseIntegration = 133
, kWasmReturnCall = 134
, kWasmExtendedConst = 135
,
kWasmRelaxedSimd = 136
, kWasmTypeReflection = 137
, kWasmExnRef = 138
, kWasmTypedFuncRef = 139
,
kInvalidatedStringWrapperToPrimitiveProtector = 140
, kDocumentAllLegacyCall = 141
, kDocumentAllLegacyConstruct = 142
, kConsoleContext = 143
,
kWasmImportedStringsUtf8 = 144
, kResizableArrayBuffer = 145
, kGrowableSharedArrayBuffer = 146
, kArrayByCopy = 147
,
kArrayFromAsync = 148
, kIteratorMethods = 149
, kPromiseAny = 150
, kSetMethods = 151
,
kArrayFindLast = 152
, kArrayGroup = 153
, kArrayBufferTransfer = 154
, kPromiseWithResolvers = 155
,
kAtomicsWaitAsync = 156
, kExtendingNonExtensibleWithPrivate = 157
, kPromiseTry = 158
, kStringReplaceAll = 159
,
kStringWellFormed = 160
, kWeakReferences = 161
, kErrorIsError = 162
, kInvalidatedTypedArrayLengthLookupChainProtector = 163
,
kRegExpEscape = 164
, kFloat16Array = 165
, kExplicitResourceManagement = 166
, kWasmBranchHinting = 167
,
kWasmMultiValue = 168
, kUint8ArrayToFromBase64AndHex = 169
, kAtomicsPause = 170
, kTopLevelAwait = 171
,
kLogicalAssignment = 172
, kNullishCoalescing = 173
, kInvalidatedNoDateTimeConfigurationChangeProtector = 174
, kUseCounterFeatureCount
 }
Features reported via the SetUseCounterCallback callback.
enum MessageErrorLevel {
kMessageLog = (1 << 0)
, kMessageDebug = (1 << 1)
, kMessageInfo = (1 << 2)
, kMessageError = (1 << 3)
,
kMessageWarning = (1 << 4)
, kMessageAll
 }
enum class Priority { kBestEffort
, kUserVisible
, kUserBlocking
 }
enum class TimeZoneDetection { kSkip
, kRedetect
 }
Time zone redetection indicator for DateTimeConfigurationChangeNotification.
using UseCounterCallback = void(*)(Isolate *isolate, UseCounterFeature feature)
using AbortOnUncaughtExceptionCallback = bool(*)(Isolate *)
Custom callback used by embedders to help V8 determine if it should abort when it throws and no internal handler is predicted to catch the exception.
using GCCallback = void(*)(Isolate *isolate, GCType type, GCCallbackFlags flags)
using GCCallbackWithData = void(*)(Isolate *isolate, GCType type, GCCallbackFlags flags, void *data)
using ReleaseCppHeapCallback = void(*)(std::unique_ptr< CppHeap >)
using GetExternallyAllocatedMemoryInBytesCallback = size_t(*)()
Public Member Functions
IsolateGroup GetGroup () const
Return the group for this isolate.
bool IsCurrent () const
Return true if this isolate is currently active.
void ClearKeptObjects ()
Clears the set of objects held strongly by the heap.
void SetAbortOnUncaughtExceptionCallback (AbortOnUncaughtExceptionCallback callback)
void SetHostImportModuleDynamicallyCallback (HostImportModuleDynamicallyCallback callback)
This specifies the callback called by the upcoming dynamic import() language feature to load modules.
void SetHostImportModuleWithPhaseDynamicallyCallback (HostImportModuleWithPhaseDynamicallyCallback callback)
This specifies the callback called by the upcoming dynamic import() and import.source() language feature to load modules.
void SetHostInitializeImportMetaObjectCallback (HostInitializeImportMetaObjectCallback callback)
This specifies the callback called by the upcoming import.meta language feature to retrieve host-defined meta data for a module.
void SetHostCreateShadowRealmContextCallback (HostCreateShadowRealmContextCallback callback)
This specifies the callback called by the upcoming ShadowRealm construction language feature to retrieve host created globals.
void SetIsJSApiWrapperNativeErrorCallback (IsJSApiWrapperNativeErrorCallback callback)
Set the callback that checks whether a Error.isError should return true for a JSApiWrapper object, i.e.
void SetPrepareStackTraceCallback (PrepareStackTraceCallback callback)
This specifies the callback called when the stack property of Error is accessed.
int GetStackTraceLimit ()
Get the stackTraceLimit property of Error.
void MemoryPressureNotification (MemoryPressureLevel level)
Optional notification that the system is running low on memory.
void SetBatterySaverMode (bool battery_saver_mode_enabled)
Optional request from the embedder to tune v8 towards energy efficiency rather than speed if battery_saver_mode_enabled is true, because the embedder is in battery saver mode.
void SetMemorySaverMode (bool memory_saver_mode_enabled)
Optional request from the embedder to tune v8 towards memory efficiency rather than speed if memory_saver_mode_enabled is true, because the embedder is in memory saver mode.
void ClearCachesForTesting ()
Drop non-essential caches.
void Enter ()
Methods below this point require holding a lock (using Locker) in a multi-threaded environment.
void Exit ()
Exits this isolate by restoring the previously entered one in the current thread.
void Dispose ()
Deinitializes and frees the isolate.
void Deinitialize ()
Deinitializes the isolate, but does not free the address.
void DumpAndResetStats ()
Dumps activated low-level V8 internal stats.
void DiscardThreadSpecificMetadata ()
Discards all V8 thread-specific data for the Isolate.
void SetData (uint32_t slot, void *data)
Associate embedder-specific data with the isolate.
void * GetData (uint32_t slot)
Retrieve embedder-specific data from the isolate.
template<class T >
MaybeLocal< T > GetDataFromSnapshotOnce (size_t index)
Return data that was previously attached to the isolate snapshot via SnapshotCreator, and removes the reference to it.
Use GetContinuationPreservedEmbedderDataV2 instead Local< Value > GetContinuationPreservedEmbedderData ()
Returns the value that was set or restored by SetContinuationPreservedEmbedderData(), if any.
Use SetContinuationPreservedEmbedderDataV2 instead void SetContinuationPreservedEmbedderData (Local< Value > data)
Sets a value that will be stored on continuations and reset while the continuation runs.
Local< Data > GetContinuationPreservedEmbedderDataV2 ()
Returns the value set by SetContinuationPreservedEmbedderDataV2() or restored during microtask execution for the currently running continuation, if any.
void SetContinuationPreservedEmbedderDataV2 (Local< Data > data)
Sets a value that will be stored on continuations and restored while the continuation runs.
void GetHeapStatistics (HeapStatistics *heap_statistics)
Get statistics about the heap memory usage.
size_t NumberOfHeapSpaces ()
Returns the number of spaces in the heap.
bool GetHeapSpaceStatistics (HeapSpaceStatistics *space_statistics, size_t index)
Get the memory usage of a space in the heap.
size_t NumberOfTrackedHeapObjectTypes ()
Returns the number of types of objects tracked in the heap at GC.
bool GetHeapObjectStatisticsAtLastGC (HeapObjectStatistics *object_statistics, size_t type_index)
Get statistics about objects in the heap.
bool GetHeapCodeAndMetadataStatistics (HeapCodeStatistics *object_statistics)
Get statistics about code and its metadata in the heap.
bool MeasureMemory (std::unique_ptr< MeasureMemoryDelegate > delegate, MeasureMemoryExecution execution=MeasureMemoryExecution::kDefault)
This API is experimental and may change significantly.
void GetStackSample (const RegisterState &state, void **frames, size_t frames_limit, SampleInfo *sample_info)
Get a call stack sample from the isolate.
Use ExternalMemoryAccounter instead int64_t AdjustAmountOfExternalAllocatedMemory (int64_t change_in_bytes)
Adjusts the amount of registered external memory.
HeapProfiler * GetHeapProfiler ()
Returns heap profiler for this isolate.
void SetIdle (bool is_idle)
Tells the VM whether the embedder is idle or not.
ArrayBuffer::Allocator * GetArrayBufferAllocator ()
Returns the ArrayBuffer::Allocator used in this isolate.
bool InContext ()
Returns true if this isolate has a current context.
Local< Context > GetCurrentContext ()
Returns the context of the currently running JavaScript, or the context on the top of the stack if no JavaScript is running.
Local< Context > GetEnteredOrMicrotaskContext ()
Returns either the last context entered through V8's C++ API, or the context of the currently running microtask while processing microtasks.
Local< Context > GetIncumbentContext ()
Returns the Context that corresponds to the Incumbent realm in HTML spec.
MaybeLocal< Data > GetCurrentHostDefinedOptions ()
Returns the host defined options set for currently running script or module, if available.
template<int N>
Local< Value > ThrowError (const char(&message)[N])
Schedules a v8::Exception::Error with the given message.
Local< Value > ThrowError (Local< String > message)
Local< Value > ThrowException (Local< Value > exception)
Schedules an exception to be thrown when returning to JavaScript.
bool HasPendingException ()
Returns true if an exception was thrown but not processed yet by an exception handler on JavaScript side or by v8::TryCatch handler.
void AddGCPrologueCallback (GCCallback callback, GCType gc_type_filter=kGCTypeAll)
Enables the host application to receive a notification before a garbage collection.
void AddGCPrologueCallback (GCCallbackWithData callback, void *data=nullptr, GCType gc_type_filter=kGCTypeAll)
Enables the host application to receive a notification before a garbage collection.
void RemoveGCPrologueCallback (GCCallback callback)
This function removes a callback which was added by AddGCPrologueCallback.
void RemoveGCPrologueCallback (GCCallbackWithData, void *data=nullptr)
void AddGCEpilogueCallback (GCCallback callback, GCType gc_type_filter=kGCTypeAll)
Enables the host application to receive a notification after a garbage collection.
void AddGCEpilogueCallback (GCCallbackWithData callback, void *data=nullptr, GCType gc_type_filter=kGCTypeAll)
Enables the host application to receive a notification after a garbage collection.
void RemoveGCEpilogueCallback (GCCallback callback)
This function removes a callback which was added by AddGCEpilogueCallback.
void RemoveGCEpilogueCallback (GCCallbackWithData callback, void *data=nullptr)
This function removes a callback which was added by AddGCEpilogueCallback.
void SetEmbedderRootsHandler (EmbedderRootsHandler *handler)
Sets an embedder roots handle that V8 should consider when performing non-unified heap garbage collections.
void SetReleaseCppHeapCallbackForTesting (ReleaseCppHeapCallback callback)
Sets a callback on the isolate that gets called when the CppHeap gets detached.
CppHeap * GetCppHeap () const
void SetGetExternallyAllocatedMemoryInBytesCallback (GetExternallyAllocatedMemoryInBytesCallback callback)
Set the callback that tells V8 how much memory is currently allocated externally of the V8 heap.
void TerminateExecution ()
Forcefully terminate the current thread of JavaScript execution in the given isolate.
bool IsExecutionTerminating ()
Is V8 terminating JavaScript execution.
void CancelTerminateExecution ()
Resume execution capability in the given isolate, whose execution was previously forcefully terminated using TerminateExecution().
void RequestInterrupt (InterruptCallback callback, void *data)
Request V8 to interrupt long running JavaScript code and invoke the given |callback| passing the given |data| to it.
bool HasPendingBackgroundTasks ()
Returns true if there is ongoing background work within V8 that will eventually post a foreground task, like asynchronous WebAssembly compilation.
void RequestGarbageCollectionForTesting (GarbageCollectionType type)
Request garbage collection in this Isolate.
void RequestGarbageCollectionForTesting (GarbageCollectionType type, StackState stack_state)
Request garbage collection with a specific embedderstack state in this Isolate.
void SetEventLogger (LogEventCallback that)
Set the callback to invoke for logging event.
void AddBeforeCallEnteredCallback (BeforeCallEnteredCallback callback)
Adds a callback to notify the host application right before a script is about to run.
void RemoveBeforeCallEnteredCallback (BeforeCallEnteredCallback callback)
Removes callback that was installed by AddBeforeCallEnteredCallback.
void AddCallCompletedCallback (CallCompletedCallback callback)
Adds a callback to notify the host application when a script finished running.
void RemoveCallCompletedCallback (CallCompletedCallback callback)
Removes callback that was installed by AddCallCompletedCallback.
void SetPromiseHook (PromiseHook hook)
Set the PromiseHook callback for various promise lifecycle events.
void SetPromiseRejectCallback (PromiseRejectCallback callback)
Set callback to notify about promise reject with no handler, or revocation of such a previous notification once the handler is added.
void SetExceptionPropagationCallback (ExceptionPropagationCallback callback)
This is a part of experimental Api and might be changed without further notice.
void PerformMicrotaskCheckpoint ()
Runs the default MicrotaskQueue until it gets empty and perform other microtask checkpoint steps, such as calling ClearKeptObjects.
void EnqueueMicrotask (Local< Function > microtask)
Enqueues the callback to the default MicrotaskQueue.
void EnqueueMicrotask (MicrotaskCallback callback, void *data=nullptr)
Enqueues the callback to the default MicrotaskQueue.
void SetMicrotasksPolicy (MicrotasksPolicy policy)
Controls how Microtasks are invoked.
MicrotasksPolicy GetMicrotasksPolicy () const
Returns the policy controlling how Microtasks are invoked.
void AddMicrotasksCompletedCallback (MicrotasksCompletedCallbackWithData callback, void *data=nullptr)
Adds a callback to notify the host application after microtasks were run on the default MicrotaskQueue.
void RemoveMicrotasksCompletedCallback (MicrotasksCompletedCallbackWithData callback, void *data=nullptr)
Removes callback that was installed by AddMicrotasksCompletedCallback.
void SetUseCounterCallback (UseCounterCallback callback)
Sets a callback for counting the number of times a feature of V8 is used.
void SetCounterFunction (CounterLookupCallback)
Enables the host application to provide a mechanism for recording statistics counters.
void SetCreateHistogramFunction (CreateHistogramCallback)
Enables the host application to provide a mechanism for recording histograms.
void SetAddHistogramSampleFunction (AddHistogramSampleCallback)
void SetMetricsRecorder (const std::shared_ptr< metrics::Recorder > &metrics_recorder)
Enables the host application to provide a mechanism for recording event based metrics.
void SetAddCrashKeyCallback (AddCrashKeyCallback)
Enables the host application to provide a mechanism for recording a predefined set of data as crash keys to be used in postmortem debugging in case of a crash.
void LowMemoryNotification ()
Optional notification that the system is running low on memory.
Use version that passes ContextDependants int ContextDisposedNotification (bool dependant_context=true)
Optional notification that a context has been disposed.
void ContextDisposedNotification (ContextDependants dependants)
Optional notification that a context has been disposed.
Use SetPriority (Priority::kUserBlocking) instead`) void IsolateInForegroundNotification()
Optional notification that the isolate switched to the foreground.
Use SetPriority (Priority::kBestEffort) instead`) void IsolateInBackgroundNotification()
Optional notification that the isolate switched to the background.
void SetPriority (Priority priority)
Optional notification that the isolate changed priority.
void SetIsLoading (bool is_loading)
Optional notification to tell V8 whether the embedder is currently loading resources.
void Freeze (bool is_frozen)
Optional notification to tell V8 whether the embedder is currently frozen.
void IncreaseHeapLimitForDebugging ()
Optional notification to tell V8 the current isolate is used for debugging and requires higher heap limit.
void RestoreOriginalHeapLimit ()
Restores the original heap limit after IncreaseHeapLimitForDebugging().
bool IsHeapLimitIncreasedForDebugging ()
Returns true if the heap limit was increased for debugging and the original heap limit was not restored yet.
void SetJitCodeEventHandler (JitCodeEventOptions options, JitCodeEventHandler event_handler)
Allows the host application to provide the address of a function that is notified each time code is added, moved or removed.
void SetStackLimit (uintptr_t stack_limit)
Modifies the stack limit for this Isolate.
void GetCodeRange (void **start, size_t *length_in_bytes)
Returns a memory range that can potentially contain jitted code.
void GetEmbeddedCodeRange (const void **start, size_t *length_in_bytes)
As GetCodeRange, but for embedded builtins (these live in a distinct memory region from other V8 Code objects).
JSEntryStubs GetJSEntryStubs ()
Returns the JSEntryStubs necessary for use with the Unwinder API.
size_t CopyCodePages (size_t capacity, MemoryRange *code_pages_out)
Copies the code heap pages currently in use by V8 into |code_pages_out|.
void SetFatalErrorHandler (FatalErrorCallback that)
Set the callback to invoke in case of fatal errors.
void SetOOMErrorHandler (OOMErrorCallback that)
Set the callback to invoke in case of OOM errors.
void AddNearHeapLimitCallback (NearHeapLimitCallback callback, void *data)
Add a callback to invoke in case the heap size is close to the heap limit.
void RemoveNearHeapLimitCallback (NearHeapLimitCallback callback, size_t heap_limit)
Remove the given callback and restore the heap limit to the given limit.
void AutomaticallyRestoreInitialHeapLimit (double threshold_percent=0.5)
If the heap limit was changed by the NearHeapLimitCallback, then the initial heap limit will be restored once the heap size falls below the given threshold percentage of the initial heap limit.
void SetModifyCodeGenerationFromStringsCallback (ModifyCodeGenerationFromStringsCallback2 callback)
Set the callback to invoke to check if code generation from strings should be allowed.
void SetAllowWasmCodeGenerationCallback (AllowWasmCodeGenerationCallback callback)
Set the callback to invoke to check if wasm code generation should be allowed.
void SetWasmModuleCallback (ExtensionCallback callback)
Embedder over{ride|load} injection points for wasm APIs.
void SetWasmInstanceCallback (ExtensionCallback callback)
void SetWasmStreamingCallback (WasmStreamingCallback callback)
void SetWasmAsyncResolvePromiseCallback (WasmAsyncResolvePromiseCallback callback)
void SetWasmLoadSourceMapCallback (WasmLoadSourceMapCallback callback)
void SetWasmImportedStringsEnabledCallback (WasmImportedStringsEnabledCallback callback)
void SetSharedArrayBufferConstructorEnabledCallback (SharedArrayBufferConstructorEnabledCallback callback)
void SetWasmJSPIEnabledCallback (WasmJSPIEnabledCallback callback)
void InstallConditionalFeatures (Local< Context > context)
This function can be called by the embedder to signal V8 that the dynamic enabling of features has finished.
bool IsDead ()
Check if V8 is dead and therefore unusable.
bool AddMessageListener (MessageCallback callback, Local< Value > data=Local< Value >())
Adds a message listener (errors only).
bool AddMessageListenerWithErrorLevel (MessageCallback callback, int message_levels, Local< Value > data=Local< Value >())
Adds a message listener.
void RemoveMessageListeners (MessageCallback callback)
Remove all message listeners from the specified callback function.
void SetFailedAccessCheckCallbackFunction (FailedAccessCheckCallback)
Callback function for reporting failed access checks.
void SetCaptureStackTraceForUncaughtExceptions (bool capture, int frame_limit=10, StackTrace::StackTraceOptions options=StackTrace::kOverview)
Tells V8 to capture current stack trace when uncaught exception occurs and report it to the message listeners.
bool IsInUse ()
Check if this isolate is in use.
void SetAllowAtomicsWait (bool allow)
Set whether calling Atomics.wait (a function that may block) is allowed in this isolate.
void DateTimeConfigurationChangeNotification (TimeZoneDetection time_zone_detection=TimeZoneDetection::kSkip)
Notification that the embedder has changed the time zone, daylight savings time or other date / time configuration parameters.
void LocaleConfigurationChangeNotification ()
Notification that the embedder has changed the locale.
std::string GetDefaultLocale ()
Returns the default locale in a string if Intl support is enabled.
V8_WARN_UNUSED_RESULT Maybe< std::string > ValidateAndCanonicalizeUnicodeLocaleId (std::string_view locale)
Returns a canonical and case-regularized form of locale if Intl support is enabled.
uint64_t GetHashSeed ()
Returns the hash seed for that isolate, for testing purposes.
Isolate ()=delete
~Isolate ()=delete
Isolate (const Isolate &)=delete
Isolate & operator= (const Isolate &)=delete
void * operator new (size_t size)=delete
void * operator new[] (size_t size)=delete
void operator delete (void *, size_t)=delete
void operator delete[] (void *, size_t)=delete
Static Public Member Functions
static Isolate * Allocate ()
Allocates a new isolate but does not initialize it.
static Isolate * Allocate (const IsolateGroup &group)
static void Initialize (Isolate *isolate, const CreateParams &params)
Initialize an Isolate previously allocated by Isolate::Allocate().
static Isolate * New (const CreateParams &params)
Creates a new isolate.
static Isolate * New (const IsolateGroup &group, const CreateParams &params)
static Isolate * GetCurrent ()
Returns the entered isolate for the current thread or NULL in case there is no current isolate.
static Isolate * TryGetCurrent ()
Returns the entered isolate for the current thread or NULL in case there is no current isolate.
static void Free (Isolate *isolate)
Frees the memory allocated for the isolate.
static uint32_t GetNumberOfDataSlots ()
Returns the maximum number of available embedder data slots.
Static Public Attributes
static constexpr size_t kMinCodePagesBufferSize = 32
Private Member Functions
internal::ValueHelper::InternalRepresentationType GetDataFromSnapshotOnce (size_t index)
int64_t AdjustAmountOfExternalAllocatedMemoryImpl (int64_t change_in_bytes)
void HandleExternalMemoryInterrupt ()
Friends
template<class K , class V , class Traits >
class PersistentValueMapBase
class ExternalMemoryAccounter
Detailed Description
Isolate represents an isolated instance of the V8 engine.
V8 isolates have completely separate states. Objects from one isolate must not be used in other isolates. The embedder can create multiple isolates and use them in parallel in multiple threads. An isolate can be entered by at most one thread at any given time. The Locker/Unlocker API must be used to synchronize.
Definition at line 285 of file v8-isolate.h.
Member Typedef Documentation
AbortOnUncaughtExceptionCallback
using v8::Isolate::AbortOnUncaughtExceptionCallback = bool (*)(Isolate*)
Custom callback used by embedders to help V8 determine if it should abort when it throws and no internal handler is predicted to catch the exception.
If --abort-on-uncaught-exception is used on the command line, then V8 will abort if either:
no custom callback is set.
the custom callback set returns true. Otherwise, the custom callback will not be called and V8 will not abort.
Definition at line 775 of file v8-isolate.h.
GCCallback
using v8::Isolate::GCCallback = void (*)(Isolate* isolate, GCType type, GCCallbackFlags flags)
Definition at line 1143 of file v8-isolate.h.
GCCallbackWithData
using v8::Isolate::GCCallbackWithData = void (*)(Isolate* isolate, GCType type, GCCallbackFlags flags, void* data)
Definition at line 1145 of file v8-isolate.h.
GetExternallyAllocatedMemoryInBytesCallback
using v8::Isolate::GetExternallyAllocatedMemoryInBytesCallback = size_t (*)()
Definition at line 1241 of file v8-isolate.h.
ReleaseCppHeapCallback
using v8::Isolate::ReleaseCppHeapCallback = void (*)(std::unique_ptr<CppHeap>)
Definition at line 1226 of file v8-isolate.h.
UseCounterCallback
using v8::Isolate::UseCounterCallback = void (*)(Isolate* isolate, UseCounterFeature feature)
Definition at line 688 of file v8-isolate.h.
Member Enumeration Documentation
GarbageCollectionType
enum v8::Isolate::GarbageCollectionType
Types of garbage collections that can be requested via RequestGarbageCollectionForTesting.
Enumerator
kFullGarbageCollection
kMinorGarbageCollection
Definition at line 466 of file v8-isolate.h.
                             {
    kFullGarbageCollection,
    kMinorGarbageCollection
  };
MessageErrorLevel
enum v8::Isolate::MessageErrorLevel
Enumerator
kMessageLog
kMessageDebug
kMessageInfo
kMessageError
kMessageWarning
kMessageAll
Definition at line 663 of file v8-isolate.h.
                         {
    kMessageLog = (1 << 0),
    kMessageDebug = (1 << 1),
    kMessageInfo = (1 << 2),
    kMessageError = (1 << 3),
    kMessageWarning = (1 << 4),
    kMessageAll = kMessageLog | kMessageDebug | kMessageInfo | kMessageError |
                  kMessageWarning,
  };
Priority
enum v8::Isolate::Priority [strong]
Enumerator
kBestEffort
kUserVisible
kUserBlocking
Definition at line 674 of file v8-isolate.h.
                      {
    // The isolate does not relate to content that is currently important
    // to the user. Lowest priority.
    kBestEffort,
    // The isolate contributes to content that is visible to the user, like a
    // visible iframe that's not interacted directly with. High priority.
    kUserVisible,
    // The isolate contributes to content that is of the utmost importance to
    // the user, like visible content in the focused window. Highest priority.
    kUserBlocking,
  };
TimeZoneDetection
enum v8::Isolate::TimeZoneDetection [strong]
Time zone redetection indicator for DateTimeConfigurationChangeNotification.
kSkip indicates V8 that the notification should not trigger redetecting host time zone. kRedetect indicates V8 that host time zone should be redetected, and used to set the default time zone.
The host time zone detection may require file system access or similar operations unlikely to be available inside a sandbox. If v8 is run inside a sandbox, the host time zone has to be detected outside the sandbox before calling DateTimeConfigurationChangeNotification function.
Enumerator
kSkip
kRedetect
Definition at line 1786 of file v8-isolate.h.
{ kSkip, kRedetect };
UseCounterFeature
enum v8::Isolate::UseCounterFeature
Features reported via the SetUseCounterCallback callback.
Do not change assigned numbers of existing items; add new features to the end of this list. Dead features can be marked V8_DEPRECATE_SOON, then V8_DEPRECATED, and then finally be renamed to kOBSOLETE_... to stop embedders from using them.
Enumerator
kUseAsm
kBreakIterator
kOBSOLETE_LegacyConst
kOBSOLETE_MarkDequeOverflow
kOBSOLETE_StoreBufferOverflow
kOBSOLETE_SlotsBufferOverflow
kOBSOLETE_ObjectObserve
kForcedGC
kSloppyMode
kStrictMode
kOBSOLETE_StrongMode
kRegExpPrototypeStickyGetter
kRegExpPrototypeToString
kRegExpPrototypeUnicodeGetter
kOBSOLETE_IntlV8Parse
kOBSOLETE_IntlPattern
kOBSOLETE_IntlResolved
kOBSOLETE_PromiseChain
kOBSOLETE_PromiseAccept
kOBSOLETE_PromiseDefer
kHtmlCommentInExternalScript
kHtmlComment
kSloppyModeBlockScopedFunctionRedefinition
kForInInitializer
kOBSOLETE_ArrayProtectorDirtied
kArraySpeciesModified
kArrayPrototypeConstructorModified
kOBSOLETE_ArrayInstanceProtoModified
kArrayInstanceConstructorModified
kOBSOLETE_LegacyFunctionDeclaration
kOBSOLETE_RegExpPrototypeSourceGetter
kOBSOLETE_RegExpPrototypeOldFlagGetter
kDecimalWithLeadingZeroInStrictMode
kLegacyDateParser
kDefineGetterOrSetterWouldThrow
kFunctionConstructorReturnedUndefined
kAssigmentExpressionLHSIsCallInSloppy
kAssigmentExpressionLHSIsCallInStrict
kPromiseConstructorReturnedUndefined
kOBSOLETE_ConstructorNonUndefinedPrimitiveReturn
kOBSOLETE_LabeledExpressionStatement
kOBSOLETE_LineOrParagraphSeparatorAsLineTerminator
kIndexAccessor
kErrorCaptureStackTrace
kErrorPrepareStackTrace
kErrorStackTraceLimit
kWebAssemblyInstantiation
kDeoptimizerDisableSpeculation
kOBSOLETE_ArrayPrototypeSortJSArrayModifiedPrototype
kFunctionTokenOffsetTooLongForToString
kWasmSharedMemory
kWasmThreadOpcodes
kOBSOLETE_AtomicsNotify
kOBSOLETE_AtomicsWake
kCollator
kNumberFormat
kDateTimeFormat
kPluralRules
kRelativeTimeFormat
kLocale
kListFormat
kSegmenter
kStringLocaleCompare
kOBSOLETE_StringToLocaleUpperCase
kStringToLocaleLowerCase
kNumberToLocaleString
kDateToLocaleString
kDateToLocaleDateString
kDateToLocaleTimeString
kAttemptOverrideReadOnlyOnPrototypeSloppy
kAttemptOverrideReadOnlyOnPrototypeStrict
kOBSOLETE_OptimizedFunctionWithOneShotBytecode
kRegExpMatchIsTrueishOnNonJSRegExp
kRegExpMatchIsFalseishOnJSRegExp
kOBSOLETE_DateGetTimezoneOffset
kStringNormalize
kCallSiteAPIGetFunctionSloppyCall
kCallSiteAPIGetThisSloppyCall
kOBSOLETE_RegExpMatchAllWithNonGlobalRegExp
kRegExpExecCalledOnSlowRegExp
kRegExpReplaceCalledOnSlowRegExp
kDisplayNames
kSharedArrayBufferConstructed
kArrayPrototypeHasElements
kObjectPrototypeHasElements
kNumberFormatStyleUnit
kDateTimeFormatRange
kDateTimeFormatDateTimeStyle
kBreakIteratorTypeWord
kBreakIteratorTypeLine
kInvalidatedArrayBufferDetachingProtector
kInvalidatedArrayConstructorProtector
kInvalidatedArrayIteratorLookupChainProtector
kInvalidatedArraySpeciesLookupChainProtector
kInvalidatedIsConcatSpreadableLookupChainProtector
kInvalidatedMapIteratorLookupChainProtector
kInvalidatedNoElementsProtector
kInvalidatedPromiseHookProtector
kInvalidatedPromiseResolveLookupChainProtector
kInvalidatedPromiseSpeciesLookupChainProtector
kInvalidatedPromiseThenLookupChainProtector
kInvalidatedRegExpSpeciesLookupChainProtector
kInvalidatedSetIteratorLookupChainProtector
kInvalidatedStringIteratorLookupChainProtector
kInvalidatedStringLengthOverflowLookupChainProtector
kInvalidatedTypedArraySpeciesLookupChainProtector
kWasmSimdOpcodes
kVarRedeclaredCatchBinding
kWasmRefTypes
kOBSOLETE_WasmBulkMemory
kOBSOLETE_WasmMultiValue
kWasmExceptionHandling
kInvalidatedMegaDOMProtector
kFunctionPrototypeArguments
kFunctionPrototypeCaller
kTurboFanOsrCompileStarted
kAsyncStackTaggingCreateTaskCall
kDurationFormat
kInvalidatedNumberStringNotRegexpLikeProtector
kOBSOLETE_RegExpUnicodeSetIncompatibilitiesWithUnicodeMode
kOBSOLETE_ImportAssertionDeprecatedSyntax
kLocaleInfoObsoletedGetters
kLocaleInfoFunctions
kCompileHintsMagicAll
kInvalidatedNoProfilingProtector
kWasmMemory64
kWasmMultiMemory
kWasmGC
kWasmImportedStrings
kSourceMappingUrlMagicCommentAtSign
kTemporalObject
kWasmModuleCompilation
kInvalidatedNoUndetectableObjectsProtector
kWasmJavaScriptPromiseIntegration
kWasmReturnCall
kWasmExtendedConst
kWasmRelaxedSimd
kWasmTypeReflection
kWasmExnRef
kWasmTypedFuncRef
kInvalidatedStringWrapperToPrimitiveProtector
kDocumentAllLegacyCall
kDocumentAllLegacyConstruct
kConsoleContext
kWasmImportedStringsUtf8
kResizableArrayBuffer
kGrowableSharedArrayBuffer
kArrayByCopy
kArrayFromAsync
kIteratorMethods
kPromiseAny
kSetMethods
kArrayFindLast
kArrayGroup
kArrayBufferTransfer
kPromiseWithResolvers
kAtomicsWaitAsync
kExtendingNonExtensibleWithPrivate
kPromiseTry
kStringReplaceAll
kStringWellFormed
kWeakReferences
kErrorIsError
kInvalidatedTypedArrayLengthLookupChainProtector
kRegExpEscape
kFloat16Array
kExplicitResourceManagement
kWasmBranchHinting
kWasmMultiValue
kUint8ArrayToFromBase64AndHex
kAtomicsPause
kTopLevelAwait
kLogicalAssignment
kNullishCoalescing
kInvalidatedNoDateTimeConfigurationChangeProtector
kUseCounterFeatureCount
Definition at line 479 of file v8-isolate.h.
                         {
    kUseAsm = 0,
    kBreakIterator = 1,
    kOBSOLETE_LegacyConst = 2,
    kOBSOLETE_MarkDequeOverflow = 3,
    kOBSOLETE_StoreBufferOverflow = 4,
    kOBSOLETE_SlotsBufferOverflow = 5,
    kOBSOLETE_ObjectObserve = 6,
    kForcedGC = 7,
    kSloppyMode = 8,
    kStrictMode = 9,
    kOBSOLETE_StrongMode = 10,
    kRegExpPrototypeStickyGetter = 11,
    kRegExpPrototypeToString = 12,
    kRegExpPrototypeUnicodeGetter = 13,
    kOBSOLETE_IntlV8Parse = 14,
    kOBSOLETE_IntlPattern = 15,
    kOBSOLETE_IntlResolved = 16,
    kOBSOLETE_PromiseChain = 17,
    kOBSOLETE_PromiseAccept = 18,
    kOBSOLETE_PromiseDefer = 19,
    kHtmlCommentInExternalScript = 20,
    kHtmlComment = 21,
    kSloppyModeBlockScopedFunctionRedefinition = 22,
    kForInInitializer = 23,
    kOBSOLETE_ArrayProtectorDirtied = 24,
    kArraySpeciesModified = 25,
    kArrayPrototypeConstructorModified = 26,
    kOBSOLETE_ArrayInstanceProtoModified = 27,
    kArrayInstanceConstructorModified = 28,
    kOBSOLETE_LegacyFunctionDeclaration = 29,
    kOBSOLETE_RegExpPrototypeSourceGetter = 30,
    kOBSOLETE_RegExpPrototypeOldFlagGetter = 31,
    kDecimalWithLeadingZeroInStrictMode = 32,
    kLegacyDateParser = 33,
    kDefineGetterOrSetterWouldThrow = 34,
    kFunctionConstructorReturnedUndefined = 35,
    kAssigmentExpressionLHSIsCallInSloppy = 36,
    kAssigmentExpressionLHSIsCallInStrict = 37,
    kPromiseConstructorReturnedUndefined = 38,
    kOBSOLETE_ConstructorNonUndefinedPrimitiveReturn = 39,
    kOBSOLETE_LabeledExpressionStatement = 40,
    kOBSOLETE_LineOrParagraphSeparatorAsLineTerminator = 41,
    kIndexAccessor = 42,
    kErrorCaptureStackTrace = 43,
    kErrorPrepareStackTrace = 44,
    kErrorStackTraceLimit = 45,
    kWebAssemblyInstantiation = 46,
    kDeoptimizerDisableSpeculation = 47,
    kOBSOLETE_ArrayPrototypeSortJSArrayModifiedPrototype = 48,
    kFunctionTokenOffsetTooLongForToString = 49,
    kWasmSharedMemory = 50,
    kWasmThreadOpcodes = 51,
    kOBSOLETE_AtomicsNotify = 52,
    kOBSOLETE_AtomicsWake = 53,
    kCollator = 54,
    kNumberFormat = 55,
    kDateTimeFormat = 56,
    kPluralRules = 57,
    kRelativeTimeFormat = 58,
    kLocale = 59,
    kListFormat = 60,
    kSegmenter = 61,
    kStringLocaleCompare = 62,
    kOBSOLETE_StringToLocaleUpperCase = 63,
    kStringToLocaleLowerCase = 64,
    kNumberToLocaleString = 65,
    kDateToLocaleString = 66,
    kDateToLocaleDateString = 67,
    kDateToLocaleTimeString = 68,
    kAttemptOverrideReadOnlyOnPrototypeSloppy = 69,
    kAttemptOverrideReadOnlyOnPrototypeStrict = 70,
    kOBSOLETE_OptimizedFunctionWithOneShotBytecode = 71,
    kRegExpMatchIsTrueishOnNonJSRegExp = 72,
    kRegExpMatchIsFalseishOnJSRegExp = 73,
    kOBSOLETE_DateGetTimezoneOffset = 74,
    kStringNormalize = 75,
    kCallSiteAPIGetFunctionSloppyCall = 76,
    kCallSiteAPIGetThisSloppyCall = 77,
    kOBSOLETE_RegExpMatchAllWithNonGlobalRegExp = 78,
    kRegExpExecCalledOnSlowRegExp = 79,
    kRegExpReplaceCalledOnSlowRegExp = 80,
    kDisplayNames = 81,
    kSharedArrayBufferConstructed = 82,
    kArrayPrototypeHasElements = 83,
    kObjectPrototypeHasElements = 84,
    kNumberFormatStyleUnit = 85,
    kDateTimeFormatRange = 86,
    kDateTimeFormatDateTimeStyle = 87,
    kBreakIteratorTypeWord = 88,
    kBreakIteratorTypeLine = 89,
    kInvalidatedArrayBufferDetachingProtector = 90,
    kInvalidatedArrayConstructorProtector V8_DEPRECATE_SOON(
        "The ArrayConstructorProtector has been removed") = 91,
    kInvalidatedArrayIteratorLookupChainProtector = 92,
    kInvalidatedArraySpeciesLookupChainProtector = 93,
    kInvalidatedIsConcatSpreadableLookupChainProtector = 94,
    kInvalidatedMapIteratorLookupChainProtector = 95,
    kInvalidatedNoElementsProtector = 96,
    kInvalidatedPromiseHookProtector = 97,
    kInvalidatedPromiseResolveLookupChainProtector = 98,
    kInvalidatedPromiseSpeciesLookupChainProtector = 99,
    kInvalidatedPromiseThenLookupChainProtector = 100,
    kInvalidatedRegExpSpeciesLookupChainProtector = 101,
    kInvalidatedSetIteratorLookupChainProtector = 102,
    kInvalidatedStringIteratorLookupChainProtector = 103,
    kInvalidatedStringLengthOverflowLookupChainProtector = 104,
    kInvalidatedTypedArraySpeciesLookupChainProtector = 105,
    kWasmSimdOpcodes = 106,
    kVarRedeclaredCatchBinding = 107,
    kWasmRefTypes = 108,
    kOBSOLETE_WasmBulkMemory = 109,
    kOBSOLETE_WasmMultiValue = 110,
    kWasmExceptionHandling = 111,
    kInvalidatedMegaDOMProtector = 112,
    kFunctionPrototypeArguments = 113,
    kFunctionPrototypeCaller = 114,
    kTurboFanOsrCompileStarted = 115,
    kAsyncStackTaggingCreateTaskCall = 116,
    kDurationFormat = 117,
    kInvalidatedNumberStringNotRegexpLikeProtector = 118,
    kOBSOLETE_RegExpUnicodeSetIncompatibilitiesWithUnicodeMode = 119,
    kOBSOLETE_ImportAssertionDeprecatedSyntax = 120,
    kLocaleInfoObsoletedGetters = 121,
    kLocaleInfoFunctions = 122,
    kCompileHintsMagicAll = 123,
    kInvalidatedNoProfilingProtector = 124,
    kWasmMemory64 = 125,
    kWasmMultiMemory = 126,
    kWasmGC = 127,
    kWasmImportedStrings = 128,
    kSourceMappingUrlMagicCommentAtSign = 129,
    kTemporalObject = 130,
    kWasmModuleCompilation = 131,
    kInvalidatedNoUndetectableObjectsProtector = 132,
    kWasmJavaScriptPromiseIntegration = 133,
    kWasmReturnCall = 134,
    kWasmExtendedConst = 135,
    kWasmRelaxedSimd = 136,
    kWasmTypeReflection = 137,
    kWasmExnRef = 138,
    kWasmTypedFuncRef = 139,
    kInvalidatedStringWrapperToPrimitiveProtector = 140,
    kDocumentAllLegacyCall = 141,
    kDocumentAllLegacyConstruct = 142,
    kConsoleContext = 143,
    kWasmImportedStringsUtf8 = 144,
    kResizableArrayBuffer = 145,
    kGrowableSharedArrayBuffer = 146,
    kArrayByCopy = 147,
    kArrayFromAsync = 148,
    kIteratorMethods = 149,
    kPromiseAny = 150,
    kSetMethods = 151,
    kArrayFindLast = 152,
    kArrayGroup = 153,
    kArrayBufferTransfer = 154,
    kPromiseWithResolvers = 155,
    kAtomicsWaitAsync = 156,
    kExtendingNonExtensibleWithPrivate = 157,
    kPromiseTry = 158,
    kStringReplaceAll = 159,
    kStringWellFormed = 160,
    kWeakReferences = 161,
    kErrorIsError = 162,
    kInvalidatedTypedArrayLengthLookupChainProtector = 163,
    kRegExpEscape = 164,
    kFloat16Array = 165,
    kExplicitResourceManagement = 166,
    kWasmBranchHinting = 167,
    kWasmMultiValue = 168,
    kUint8ArrayToFromBase64AndHex = 169,
    kAtomicsPause = 170,
    kTopLevelAwait = 171,
    kLogicalAssignment = 172,
    kNullishCoalescing = 173,
    kInvalidatedNoDateTimeConfigurationChangeProtector = 174,
    // If you add new values here, you'll also need to update Chromium's:
    // web_feature.mojom, use_counter_callback.cc, and enums.xml. V8 changes to
    // this list need to be landed first, then changes on the Chromium side.
    kUseCounterFeatureCount // This enum value must be last.
  };
Constructor & Destructor Documentation
Isolate() [1/2]
v8::Isolate::Isolate () [delete]
 Isolate()
v8::Isolate::~Isolate () [delete]
Isolate() [2/2]
v8::Isolate::Isolate (const Isolate &) [delete]
Member Function Documentation
AddBeforeCallEnteredCallback()
void v8::Isolate::AddBeforeCallEnteredCallback (BeforeCallEnteredCallback callback)
Adds a callback to notify the host application right before a script is about to run.
If a script re-enters the runtime during executing, the BeforeCallEnteredCallback is invoked for each re-entrance. Executing scripts inside the callback will re-trigger the callback.
Definition at line 10456 of file api.cc.
                                                                             {
  if (callback == nullptr) return;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->AddBeforeCallEnteredCallback(callback);
}
References v8::internal::Isolate::AddBeforeCallEnteredCallback().
AddCallCompletedCallback()
void v8::Isolate::AddCallCompletedCallback (CallCompletedCallback callback)
Adds a callback to notify the host application when a script finished running.
If a script re-enters the runtime during executing, the CallCompletedCallback is only invoked when the outer-most script execution ends. Executing scripts inside the callback do not trigger further callbacks.
Definition at line 10468 of file api.cc.
                                                                     {
  if (callback == nullptr) return;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->AddCallCompletedCallback(callback);
}
References v8::internal::Isolate::AddCallCompletedCallback().
Referenced by v8_inspector::V8Debugger::installTerminateExecutionCallbacks().
AddGCEpilogueCallback() [1/2]
void v8::Isolate::AddGCEpilogueCallback (GCCallback callback, GCType gc_type_filter = kGCTypeAll)
Enables the host application to receive a notification after a garbage collection.
Parameters
callback The callback to be invoked. The callback is allowed to allocate but invocation is not re-entrant: a callback triggering garbage collection will not be called again. JS execution is prohibited from these callbacks. A single callback may only be registered once.
gc_type_filter A filter in case it should be applied.
Definition at line 9826 of file api.cc.
                                                                       {
  void* data = reinterpret_cast<void*>(callback);
  AddGCEpilogueCallback(CallGCCallbackWithoutData, data, gc_type);
}
References v8::CallGCCallbackWithoutData().
AddGCEpilogueCallback() [2/2]
void v8::Isolate::AddGCEpilogueCallback (GCCallbackWithData callback, void * data = nullptr, GCType gc_type_filter = kGCTypeAll)
Enables the host application to receive a notification after a garbage collection.
Parameters
callback The callback to be invoked. The callback is allowed to allocate but invocation is not re-entrant: a callback triggering garbage collection will not be called again. JS execution is prohibited from these callbacks. A single callback may only be registered once.
gc_type_filter A filter in case it should be applied.
data Additional data that should be passed to the callback.
Definition at line 9799 of file api.cc.
                                                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->AddGCEpilogueCallback(callback, gc_type, data);
}
References v8::internal::Heap::AddGCEpilogueCallback(), and v8::internal::Isolate::heap().
AddGCPrologueCallback() [1/2]
void v8::Isolate::AddGCPrologueCallback (GCCallback callback, GCType gc_type_filter = kGCTypeAll)
Enables the host application to receive a notification before a garbage collection.
Parameters
callback The callback to be invoked. The callback is allowed to allocate but invocation is not re-entrant: a callback triggering garbage collection will not be called again. JS execution is prohibited from these callbacks. A single callback may only be registered once.
gc_type_filter A filter in case it should be applied.
Definition at line 9816 of file api.cc.
                                                                       {
  void* data = reinterpret_cast<void*>(callback);
  AddGCPrologueCallback(CallGCCallbackWithoutData, data, gc_type);
}
References v8::CallGCCallbackWithoutData().
AddGCPrologueCallback() [2/2]
void v8::Isolate::AddGCPrologueCallback (GCCallbackWithData callback, void * data = nullptr, GCType gc_type_filter = kGCTypeAll)
Enables the host application to receive a notification before a garbage collection.
Parameters
callback The callback to be invoked. The callback is allowed to allocate but invocation is not re-entrant: a callback triggering garbage collection will not be called again. JS execution is prohibited from these callbacks. A single callback may only be registered once.
gc_type_filter A filter in case it should be applied.
data Additional data that should be passed to the callback.
Definition at line 9787 of file api.cc.
                                                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->AddGCPrologueCallback(callback, gc_type, data);
}
References v8::internal::Heap::AddGCPrologueCallback(), and v8::internal::Isolate::heap().
AddMessageListener()
bool v8::Isolate::AddMessageListener (MessageCallback callback, Local< Value > data = Local<Value>())
Adds a message listener (errors only).
The same message listener can be added more than once and in that case it will be called more than once for each message.
If data is specified, it will be passed to the callback when it is called. Otherwise, the exception object will be passed to the callback instead.
Definition at line 10831 of file api.cc.
                                                                            {
  return AddMessageListenerWithErrorLevel(callback, kMessageError, data);
}
References AddMessageListenerWithErrorLevel(), and kMessageError.
AddMessageListenerWithErrorLevel()
bool v8::Isolate::AddMessageListenerWithErrorLevel (MessageCallback callback, int message_levels, Local< Value > data = Local<Value>())
Adds a message listener.
The same message listener can be added more than once and in that case it will be called more than once for each message.
If data is specified, it will be passed to the callback when it is called. Otherwise, the exception object will be passed to the callback instead.
A listener can listen for particular error levels by providing a mask.
Definition at line 10835 of file api.cc.
                                                                  {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  i::DirectHandle<i::ArrayList> list =
      i_isolate->factory()->message_listeners();
  i::DirectHandle<i::FixedArray> listener =
      i_isolate->factory()->NewFixedArray(3);
  i::DirectHandle<i::Object> callback_obj =
      FromCData<internal::kMessageListenerTag>(i_isolate, callback);
  listener->set(0, *callback_obj);
  listener->set(1, data.IsEmpty()
                       ? i::ReadOnlyRoots(i_isolate).undefined_value()
                       : *Utils::OpenDirectHandle(*data));
  listener->set(2, i::Smi::FromInt(message_levels));
  list = i::ArrayList::Add(i_isolate, list, listener);
  i_isolate->heap()->SetMessageListeners(*list);
  return true;
}
References v8::internal::ArrayList::Add(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::Isolate::heap(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::Utils::OpenDirectHandle(), and v8::internal::Heap::SetMessageListeners().
Referenced by AddMessageListener(), and v8::Shell::Initialize().
AddMicrotasksCompletedCallback()
void v8::Isolate::AddMicrotasksCompletedCallback (MicrotasksCompletedCallbackWithData callback, void * data = nullptr)
Adds a callback to notify the host application after microtasks were run on the default MicrotaskQueue.
The callback is triggered by explicit RunMicrotasks call or automatic microtasks execution (see SetMicrotaskPolicy).
Callback will trigger even if microtasks were attempted to run, but the microtasks queue was empty and no single microtask was actually executed.
Executing scripts inside the callback will not re-trigger microtasks and the callback.
Definition at line 10530 of file api.cc.
                                                              {
  DCHECK(callback);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->default_microtask_queue()->AddMicrotasksCompletedCallback(callback,
                                                                       data);
}
References DCHECK.
AddNearHeapLimitCallback()
void v8::Isolate::AddNearHeapLimitCallback (v8::NearHeapLimitCallback callback, void * data)
Add a callback to invoke in case the heap size is close to the heap limit.
If multiple callbacks are added, only the most recently added callback is invoked.
Definition at line 10807 of file api.cc.
                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->AddNearHeapLimitCallback(callback, data);
}
References v8::internal::Heap::AddNearHeapLimitCallback(), and v8::internal::Isolate::heap().
Referenced by v8_inspector::V8Debugger::enable().
AdjustAmountOfExternalAllocatedMemory()
int64_t v8::Isolate::AdjustAmountOfExternalAllocatedMemory (int64_t change_in_bytes)
Adjusts the amount of registered external memory.
Parameters
change_in_bytes the change in externally allocated memory that is kept alive by JavaScript objects.
Returns
the adjusted value.
Definition at line 10446 of file api.cc.
                             {
  return AdjustAmountOfExternalAllocatedMemoryImpl(change_in_bytes);
}
References AdjustAmountOfExternalAllocatedMemoryImpl().
AdjustAmountOfExternalAllocatedMemoryImpl()
int64_t v8::Isolate::AdjustAmountOfExternalAllocatedMemoryImpl (int64_t change_in_bytes) [private]
Definition at line 9612 of file api.cc.
                             {
  // Try to check for unreasonably large or small values from the embedder.
  static constexpr int64_t kMaxReasonableBytes = int64_t(1) << 60;
  static constexpr int64_t kMinReasonableBytes = -kMaxReasonableBytes;
  static_assert(kMaxReasonableBytes >= i::JSArrayBuffer::kMaxByteLength);
  CHECK(kMinReasonableBytes <= change_in_bytes &&
        change_in_bytes < kMaxReasonableBytes);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  const uint64_t amount =
      i_isolate->heap()->UpdateExternalMemory(change_in_bytes);
  if (change_in_bytes <= 0) {
    return amount;
  }
  if (amount > i_isolate->heap()->external_memory_limit_for_interrupt()) {
    HandleExternalMemoryInterrupt();
  }
  return amount;
}
References CHECK, v8::internal::Heap::external_memory_limit_for_interrupt(), HandleExternalMemoryInterrupt(), v8::internal::Isolate::heap(), v8::internal::JSArrayBuffer::kMaxByteLength, and v8::internal::Heap::UpdateExternalMemory().
Referenced by AdjustAmountOfExternalAllocatedMemory(), v8::ExternalMemoryAccounter::Increase(), and v8::ExternalMemoryAccounter::Update().
Allocate() [1/2]
Isolate * v8::Isolate::Allocate () [static]
Allocates a new isolate but does not initialize it.
Does not change the currently entered isolate.
Only Isolate::GetData() and Isolate::SetData(), which access the embedder-controlled parts of the isolate, as well as Isolate::GetGroup(), are allowed to be called on the uninitialized isolate. To initialize the isolate, call Isolate::Initialize() or initialize a SnapshotCreator.
When an isolate is no longer used its resources should be freed by calling Dispose(). Using the delete operator is not allowed.
V8::Initialize() must have run prior to this.
Definition at line 9934 of file api.cc.
                           {
  return Isolate::Allocate(IsolateGroup::GetDefault());
}
References v8::IsolateGroup::GetDefault().
Referenced by main(), and New().
Allocate() [2/2]
Isolate * v8::Isolate::Allocate (const IsolateGroup & group) [static]
Definition at line 9939 of file api.cc.
                                                    {
  i::IsolateGroup* isolate_group = group.isolate_group_->Acquire();
  return reinterpret_cast<Isolate*>(i::Isolate::New(isolate_group));
}
References v8::internal::IsolateGroup::Acquire(), v8::IsolateGroup::isolate_group_, and v8::internal::Isolate::New().
AutomaticallyRestoreInitialHeapLimit()
void v8::Isolate::AutomaticallyRestoreInitialHeapLimit (double threshold_percent = 0.5)
If the heap limit was changed by the NearHeapLimitCallback, then the initial heap limit will be restored once the heap size falls below the given threshold percentage of the initial heap limit.
The threshold percentage is a number in (0.0, 1.0) range.
Definition at line 10819 of file api.cc.
                                                                           {
  DCHECK_GT(threshold_percent, 0.0);
  DCHECK_LT(threshold_percent, 1.0);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->AutomaticallyRestoreInitialHeapLimit(threshold_percent);
}
References v8::internal::Heap::AutomaticallyRestoreInitialHeapLimit(), DCHECK_GT, DCHECK_LT, and v8::internal::Isolate::heap().
CancelTerminateExecution()
void v8::Isolate::CancelTerminateExecution ()
Resume execution capability in the given isolate, whose execution was previously forcefully terminated using TerminateExecution().
When execution is forcefully terminated using TerminateExecution(), the isolate can not resume execution until all JavaScript frames have propagated the uncatchable exception which is generated. This method allows the program embedding the engine to handle the termination event and resume execution capability, even if JavaScript frames remain on the stack.
This method can be used by any thread even if that thread has not acquired the V8 lock with a Locker object.
Definition at line 9868 of file api.cc.
                                       {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->stack_guard()->ClearTerminateExecution();
  i_isolate->CancelTerminateExecution();
}
References v8::internal::Isolate::CancelTerminateExecution(), and v8::internal::Isolate::stack_guard().
Referenced by v8_inspector::V8Debugger::reportTermination(), and v8_inspector::V8InspectorImpl::EvaluateScope::~EvaluateScope().
ClearCachesForTesting()
void v8::Isolate::ClearCachesForTesting ()
Drop non-essential caches.
Should only be called from testing code. The method can potentially block for a long time and does not necessarily trigger GC.
Definition at line 10653 of file api.cc.
                                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->AbortConcurrentOptimization(i::BlockingBehavior::kBlock);
  i_isolate->ClearSerializerData();
  i_isolate->compilation_cache()->Clear();
}
References v8::internal::Isolate::AbortConcurrentOptimization(), v8::internal::CompilationCache::Clear(), v8::internal::Isolate::ClearSerializerData(), v8::internal::Isolate::compilation_cache(), and v8::internal::kBlock.
ClearKeptObjects()
void v8::Isolate::ClearKeptObjects ()
Clears the set of objects held strongly by the heap.
This set of objects are originally built when a WeakRef is created or successfully dereferenced.
This is invoked automatically after microtasks are run. See MicrotasksPolicy for when microtasks are run.
This needs to be manually invoked only if the embedder is manually running microtasks via a custom MicrotaskQueue class's PerformCheckpoint. In that case, it is the embedder's responsibility to make this call at a time which does not interrupt synchronous ECMAScript code execution.
Definition at line 9723 of file api.cc.
                               {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->ClearKeptObjects();
}
References v8::internal::Isolate::ClearKeptObjects().
ContextDisposedNotification() [1/2]
int v8::Isolate::ContextDisposedNotification (bool dependant_context = true)
Optional notification that a context has been disposed.
V8 uses these notifications to guide the GC heuristic and cancel FinalizationRegistry cleanup tasks. Returns the number of context disposals - including this one
since the last time V8 had a chance to clean up.
The optional parameter |dependant_context| specifies whether the disposed context was depending on state from other contexts or not.
Definition at line 10589 of file api.cc.
                                                               {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  if (V8_UNLIKELY(i::v8_flags.trace_context_disposal)) {
    i_isolate->PrintWithTimestamp("[context-disposal] Disposing %s context\n",
                                  dependant_context ? "nested" : "top-level");
  }
#if V8_ENABLE_WEBASSEMBLY
  if (!dependant_context) {
    if (!i_isolate->context().is_null()) {
      // We left the current context, we can abort all WebAssembly compilations
      // of that context.
      // A handle scope for the native context.
      i::HandleScope handle_scope(i_isolate);
      i::wasm::GetWasmEngine()->DeleteCompileJobsOnContext(
          i_isolate->native_context());
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
  i_isolate->AbortConcurrentOptimization(i::BlockingBehavior::kDontBlock);
  return i_isolate->heap()->NotifyContextDisposed(dependant_context);
}
References v8::internal::Isolate::AbortConcurrentOptimization(), v8::internal::Isolate::context(), v8::internal::wasm::WasmEngine::DeleteCompileJobsOnContext(), v8::internal::wasm::GetWasmEngine(), v8::internal::Isolate::heap(), v8::internal::Isolate::native_context(), v8::internal::Heap::NotifyContextDisposed(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::Shell::CollectGarbage(), ContextDisposedNotification(), v8::Shell::DisposeRealm(), and v8::internal::WarmUpSnapshotDataBlobInternal().
ContextDisposedNotification() [2/2]
void v8::Isolate::ContextDisposedNotification (ContextDependants dependants)
Optional notification that a context has been disposed.
V8 uses these notifications to guide heuristics on e.g. GC or compilers.
Parameters
dependants A signal on whether this context possibly had any dependants.
Definition at line 10611 of file api.cc.
                                                                      {
  // TODO(mlippautz): Replace implementation with the old version of
  // ContextDisposedNotification() that still has a return parameter.
  START_ALLOW_USE_DEPRECATED()
  ContextDisposedNotification(dependants == ContextDependants::kSomeDependants);
  END_ALLOW_USE_DEPRECATED()
}
References ContextDisposedNotification(), END_ALLOW_USE_DEPRECATED, v8::kSomeDependants, and START_ALLOW_USE_DEPRECATED.
CopyCodePages()
size_t v8::Isolate::CopyCodePages (size_t capacity, MemoryRange * code_pages_out)
Copies the code heap pages currently in use by V8 into |code_pages_out|.
|code_pages_out| must have at least kMinCodePagesBufferSize capacity and must be empty.
Signal-safe, does not allocate, does not access the V8 heap. No code on the stack can rely on pages that might be missing.
Returns the number of pages available to be copied, which might be greater than |capacity|. In this case, only |capacity| pages will be copied into |code_pages_out|. The caller should provide a bigger buffer on the next call in order to get all available code pages, but this is not required.
Definition at line 10729 of file api.cc.
                                                                          {
#if !defined(V8_TARGET_ARCH_64_BIT) && !defined(V8_TARGET_ARCH_ARM)
  // Not implemented on other platforms.
  UNREACHABLE();
#else
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  std::vector<MemoryRange>* code_pages = i_isolate->GetCodePages();
  DCHECK_NOT_NULL(code_pages);
  // Copy as many elements into the output vector as we can. If the
  // caller-provided buffer is not big enough, we fill it, and the caller can
  // provide a bigger one next time. We do it this way because allocation is not
  // allowed in signal handlers.
  size_t limit = std::min(capacity, code_pages->size());
  for (size_t i = 0; i < limit; i++) {
    code_pages_out[i] = code_pages->at(i);
  }
  return code_pages->size();
#endif
}
References DCHECK_NOT_NULL, v8::internal::Isolate::GetCodePages(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and UNREACHABLE.
DateTimeConfigurationChangeNotification()
void v8::Isolate::DateTimeConfigurationChangeNotification (TimeZoneDetection time_zone_detection = TimeZoneDetection::kSkip)
Notification that the embedder has changed the time zone, daylight savings time or other date / time configuration parameters.
V8 keeps a cache of various values used for date / time computation. This notification will reset those cached values for the current context so that date / time configuration changes would be reflected.
This API should not be called more than needed as it will negatively impact the performance of date operations.
Definition at line 10904 of file api.cc.
                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  ApiRuntimeCallStatsScope rcs_scope(
      i_isolate, RCCId::kAPI_Isolate_DateTimeConfigurationChangeNotification);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i_isolate->date_cache()->ResetDateCache(
      static_cast<base::TimezoneCache::TimeZoneDetection>(time_zone_detection));
  i_isolate->IncreaseDateCacheStampAndInvalidateProtector();
#ifdef V8_INTL_SUPPORT
  i_isolate->clear_cached_icu_object(
      i::Isolate::ICUObjectCacheType::kDefaultSimpleDateFormat);
  i_isolate->clear_cached_icu_object(
      i::Isolate::ICUObjectCacheType::kDefaultSimpleDateFormatForTime);
  i_isolate->clear_cached_icu_object(
      i::Isolate::ICUObjectCacheType::kDefaultSimpleDateFormatForDate);
#endif // V8_INTL_SUPPORT
}
References v8::internal::Isolate::date_cache(), v8::internal::Isolate::IncreaseDateCacheStampAndInvalidateProtector(), and v8::internal::DateCache::ResetDateCache().
Deinitialize()
void v8::Isolate::Deinitialize ()
Deinitializes the isolate, but does not free the address.
The isolate must not be entered by any thread to be deinitializable. Embedders must call Isolate::Free() to free the isolate afterwards.
Definition at line 10079 of file api.cc.
                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  if (!Utils::ApiCheck(
          !i_isolate->IsInUse(), "v8::Isolate::Deinitialize()",
          "Deinitializing the isolate that is entered by a thread")) {
    return;
  }
  i::Isolate::Deinitialize(i_isolate);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Deinitialize(), and v8::internal::Isolate::IsInUse().
DiscardThreadSpecificMetadata()
void v8::Isolate::DiscardThreadSpecificMetadata ()
Discards all V8 thread-specific data for the Isolate.
Should be used if a thread is terminating and it has used an Isolate that will outlive the thread -- all thread-specific data for an Isolate is discarded when an Isolate is disposed so this call is pointless if an Isolate is about to be Disposed.
Definition at line 10099 of file api.cc.
                                            {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->DiscardPerThreadDataForThisThread();
}
References v8::internal::Isolate::DiscardPerThreadDataForThisThread().
Dispose()
void v8::Isolate::Dispose ()
Deinitializes and frees the isolate.
The isolate must not be entered by any thread to be disposable.
Definition at line 10070 of file api.cc.
                      {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  if (!Utils::ApiCheck(!i_isolate->IsInUse(), "v8::Isolate::Dispose()",
                       "Disposing the isolate that is entered by a thread")) {
    return;
  }
  i::Isolate::Delete(i_isolate);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Delete(), and v8::internal::Isolate::IsInUse().
Referenced by v8::SourceGroup::ExecuteInThread(), v8::Worker::ExecuteInThread(), main(), v8::Shell::Main(), v8::Shell::OnExit(), and wasm::StoreImpl::~StoreImpl().
DumpAndResetStats()
void v8::Isolate::DumpAndResetStats ()
Dumps activated low-level V8 internal stats.
This can be used instead of performing a full isolate disposal.
Definition at line 10094 of file api.cc.
                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->DumpAndResetStats();
}
References v8::internal::Isolate::DumpAndResetStats().
Referenced by v8::Shell::OnExit().
EnqueueMicrotask() [1/2]
void v8::Isolate::EnqueueMicrotask (Local< Function > microtask)
Enqueues the callback to the default MicrotaskQueue.
Definition at line 10503 of file api.cc.
                                                          {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  auto function = Utils::OpenDirectHandle(*v8_function);
  i::DirectHandle<i::NativeContext> handler_context;
  if (!i::JSReceiver::GetContextForMicrotask(function).ToHandle(
          &handler_context))
    handler_context = i_isolate->native_context();
  MicrotaskQueue* microtask_queue = handler_context->microtask_queue();
  if (microtask_queue) microtask_queue->EnqueueMicrotask(this, v8_function);
}
References v8::MicrotaskQueue::EnqueueMicrotask(), v8::internal::JSReceiver::GetContextForMicrotask(), v8::internal::Isolate::native_context(), v8::Utils::OpenDirectHandle(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::Shell::HostImportModuleWithPhaseDynamically().
EnqueueMicrotask() [2/2]
void v8::Isolate::EnqueueMicrotask (MicrotaskCallback callback, void * data = nullptr)
Enqueues the callback to the default MicrotaskQueue.
Definition at line 10514 of file api.cc.
                                                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->default_microtask_queue()->EnqueueMicrotask(this, callback, data);
}
Enter()
void v8::Isolate::Enter ()
Methods below this point require holding a lock (using Locker) in a multi-threaded environment.
Sets this isolate as the entered one for the current thread. Saves the previously entered one (if any), so that it can be restored when exiting. Re-entering an isolate is allowed.
Definition at line 10104 of file api.cc.
                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->Enter();
}
References v8::internal::Isolate::Enter().
Exit()
void v8::Isolate::Exit ()
Exits this isolate by restoring the previously entered one in the current thread.
The isolate may still stay the same, if it was entered more than once.
Requires: this == Isolate::GetCurrent().
Definition at line 10109 of file api.cc.
                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->Exit();
}
References v8::internal::Isolate::Exit().
Referenced by v8::Shell::QuitOnce().
Free()
void v8::Isolate::Free (Isolate * isolate) [static]
Frees the memory allocated for the isolate.
Can only be called after the Isolate has already been deinitialized with Isolate::Deinitialize(). After the isolate is freed, the next call to Isolate::New() or Isolate::Allocate() might return the same address that just get freed.
Definition at line 10089 of file api.cc.
                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i::Isolate::Free(i_isolate);
}
References v8::internal::Isolate::Free().
Freeze()
void v8::Isolate::Freeze (bool is_frozen)
Optional notification to tell V8 whether the embedder is currently frozen.
V8 uses these notifications to guide heuristics. This is an unfinished experimental feature. Semantics and implementation may change frequently.
Definition at line 10665 of file api.cc.
                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->Freeze(is_frozen);
}
References v8::internal::Isolate::Freeze().
GetArrayBufferAllocator()
ArrayBuffer::Allocator * v8::Isolate::GetArrayBufferAllocator ()
Returns the ArrayBuffer::Allocator used in this isolate.
Definition at line 9713 of file api.cc.
                                                       {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return i_isolate->array_buffer_allocator();
}
References v8::internal::Isolate::array_buffer_allocator().
GetCodeRange()
void v8::Isolate::GetCodeRange (void ** start, size_t * length_in_bytes)
Returns a memory range that can potentially contain jitted code.
Code for V8's 'builtins' will not be in this range if embedded builtins is enabled.
On Win64, embedders are advised to install function table callbacks for these ranges, as default SEH won't be able to unwind through jitted code. The first page of the code range is reserved for the embedder and is committed, writable, and executable, to be used to store unwind data, as documented in https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64.
Might be empty on other platforms.
 https://code.google.com/p/v8/issues/detail?id=3598
Definition at line 10695 of file api.cc.
                                                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  const base::AddressRegion& code_region = i_isolate->heap()->code_region();
  *start = reinterpret_cast<void*>(code_region.begin());
  *length_in_bytes = code_region.size();
}
References v8::base::AddressRegion::begin(), v8::internal::Heap::code_region(), v8::internal::Isolate::heap(), and v8::base::AddressRegion::size().
GetContinuationPreservedEmbedderData()
Local< Value > v8::Isolate::GetContinuationPreservedEmbedderData ()
Returns the value that was set or restored by SetContinuationPreservedEmbedderData(), if any.
Definition at line 10231 of file api.cc.
                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  return ToApiHandle<Object>(i::direct_handle(
      i_isolate->isolate_data()->continuation_preserved_embedder_data(),
      i_isolate));
#else // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  return v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate));
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
}
References v8::internal::IsolateData::continuation_preserved_embedder_data(), v8::internal::direct_handle(), v8::internal::Isolate::isolate_data(), and v8::Undefined().
GetContinuationPreservedEmbedderDataV2()
Local< Data > v8::Isolate::GetContinuationPreservedEmbedderDataV2 ()
Returns the value set by SetContinuationPreservedEmbedderDataV2() or restored during microtask execution for the currently running continuation, if any.
Returns undefiend if no continuation preserved embedder data was set.
Definition at line 10252 of file api.cc.
                                                            {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  return ToApiHandle<Data>(i::direct_handle(
      i_isolate->isolate_data()->continuation_preserved_embedder_data(),
      i_isolate));
#else // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  return v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate));
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
}
References v8::internal::IsolateData::continuation_preserved_embedder_data(), v8::internal::direct_handle(), v8::internal::Isolate::isolate_data(), and v8::Undefined().
GetCppHeap()
CppHeap * v8::Isolate::GetCppHeap () const
Returns
the C++ heap managed by V8. Only available if such a heap has been attached using AttachCppHeap().
Definition at line 9841 of file api.cc.
                                   {
  const i::Isolate* i_isolate = reinterpret_cast<const i::Isolate*>(this);
  return i_isolate->heap()->cpp_heap();
}
References v8::internal::Heap::cpp_heap(), and v8::internal::Isolate::heap().
Referenced by v8_inspector::V8RuntimeAgentImpl::getHeapUsage().
GetCurrent()
Isolate * v8::Isolate::GetCurrent () [static]
Returns the entered isolate for the current thread or NULL in case there is no current isolate.
This method must not be invoked before V8::Initialize() was invoked.
Definition at line 9919 of file api.cc.
                             {
  i::Isolate* i_isolate = i::Isolate::Current();
  return reinterpret_cast<Isolate*>(i_isolate);
}
References v8::internal::Isolate::Current().
Referenced by v8::PerIsolateData::AddUnhandledPromise(), v8_inspector::InjectedScript::bindRemoteObjectIfNeeded(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildObjectPreviewInternal(), v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildRemoteObject(), v8::Function::Call(), v8_inspector::anonymous_namespace{value-mirror.cc}::clientFor(), v8_inspector::clientMirror(), v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8::ScriptCompiler::Compile(), v8::CpuProfilingOptions::CpuProfilingOptions(), v8_inspector::ValueMirror::create(), v8_inspector::anonymous_namespace{v8-console.cc}::createBoundFunctionProperty(), v8_inspector::V8Console::createCommandLineAPI(), v8_inspector::createDataProperty(), v8_inspector::V8ConsoleMessage::createForConsoleAPI(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForBigInt(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::DescriptionForDate(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForDate(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForEntry(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForFunction(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrimitiveType(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethod(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScope(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForSymbol(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8::Shell::FetchModuleSource(), v8::Shell::FetchModuleTree(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::InspectableHeapObject::get(), v8::Object::GetCreationContext(), v8::internal::Internals::GetCurrentIsolate(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8_inspector::anonymous_namespace{custom-preview.cc}::getInjectedScript(), v8_inspector::InjectedScript::getInternalAndPrivateProperties(), v8_inspector::ValueMirror::getInternalProperties(), v8_inspector::ValueMirror::getPrivateProperties(), v8_inspector::ValueMirror::getProperties(), v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview(), v8::Shell::HostCreateShadowRealmContext(), v8::Shell::HostImportModuleWithPhaseDynamically(), v8::Shell::HostInitializeImportMetaObject(), v8::InspectorFrontend::InspectorFrontend(), v8_inspector::V8Console::installAsyncStackTaggingAPI(), v8_inspector::V8Console::installMemoryGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike(), v8::Shell::JSONModuleEvaluationSteps(), v8::String::MakeExternal(), v8::anonymous_namespace{d8.cc}::ModuleEmbedderData::ModuleTypeFromImportSpecifierAndAttributes(), v8_inspector::objectToProtocolValue(), v8::PrintMessageCallback(), v8_inspector::V8Debugger::privateMethods(), v8::Shell::PromiseRejectCallback(), v8_inspector::V8Debugger::queryObjects(), v8::PerIsolateData::RemoveUnhandledPromise(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8::anonymous_namespace{d8.cc}::ResolveModuleCallback(), v8::anonymous_namespace{d8.cc}::ResolveModuleSourceCallback(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeRegexp(), v8_inspector::V8SerializationDuplicateTracker::SetKnownSerializedValue(), v8::AsyncHooks::ShellPromiseHook(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemoryFastCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ThrowNoFallbackFastCallback(), v8_inspector::toProtocolValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::v8InternalValueTypeFrom(), and v8_inspector::InjectedScript::wrapObjectMirror().
GetCurrentContext()
v8::Local< v8::Context > v8::Isolate::GetCurrentContext ()
Returns the context of the currently running JavaScript, or the context on the top of the stack if no JavaScript is running.
Definition at line 9728 of file api.cc.
                                              {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i::Tagged<i::Context> context = i_isolate->context();
  if (context.is_null()) return {};
  i::Tagged<i::NativeContext> native_context = context->native_context();
  return Utils::ToLocal(i::direct_handle(native_context, i_isolate));
}
References v8::internal::Isolate::context(), v8::internal::direct_handle(), v8::internal::Tagged< HeapObject >::is_null(), and v8::internal::native_context.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Add32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllAnnotateSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSlowCallback(), v8::internal::AddCounter(), v8::internal::AddNumber(), v8::internal::AddNumber64(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeSetterSlowCallback(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberFastCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberSlowCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompareSlowCallback(), v8::ScriptCompiler::CompileUnboundInternal(), v8::AsyncHooks::CreateHook(), v8_inspector::V8Console::createTask(), v8_inspector::V8Debugger::currentContextGroupId(), v8::Shell::DeserializeValue(), v8::Shell::EnableJSPI(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EncodeExceptionValues(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::EnforceRangeCompareSlowCallback(), v8::Shell::ExecuteString(), v8::Shell::FunctionAndArgumentsToString(), v8::internal::FuzzilliExtension::Fuzzilli(), v8::internal::GCExtension::GC(), v8::Shell::GetExtrasBindingObject(), v8::GetTimeouts(), v8::ExecArgs::Init(), v8_inspector::V8Console::inspectedObject(), v8::Shell::InstallConditionalFeatures(), v8_inspector::V8Console::keysCallback(), v8::Shell::MakeDirectory(), v8::internal::CpuTraceMarkExtension::Mark(), v8_inspector::V8Console::memoryGetterCallback(), v8::Shell::ModuleResolutionFailureCallback(), v8::Shell::ModuleResolutionSuccessCallback(), v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8::Shell::PerformanceMeasureMemory(), v8::PrintMessageCallback(), v8::Shell::ProfilerSetOnProfileEndListener(), v8::AsyncHooks::PromiseHookDispatch(), v8_inspector::V8Console::queryObjectsCallback(), v8::Shell::QuitOnce(), v8::Shell::ReadCodeTypeAndArguments(), v8::PerIsolateData::RealmIndexOrThrow(), v8::Shell::RealmOwner(), v8::Shell::ReportException(), v8_inspector::V8Console::runTask(), v8::internal::RUNTIME_FUNCTION(), v8::InspectorClient::SendInspectorMessage(), v8::Shell::SerializerDeserialize(), v8::Shell::SerializerSerialize(), v8::Shell::SerializeValue(), v8::Shell::SetPromiseHooks(), v8::Module::SetSyntheticModuleExport(), v8::Shell::SetTimeout(), v8::Shell::SetUMask(), v8::AsyncHooks::ShellPromiseHook(), v8_inspector::TaskInfo::TaskInfo(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemoryFastCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ThrowNoFallbackFastCallback(), v8::String::Utf8Value::Utf8Value(), v8::String::Value::Value(), v8_inspector::V8Console::valuesCallback(), v8::Shell::WorkerNew(), v8::Shell::WorkerOnMessageSetter(), v8::anonymous_namespace{d8-console.cc}::WriteToFile(), and v8::WriteToFile().
GetCurrentHostDefinedOptions()
v8::MaybeLocal< v8::Data > v8::Isolate::GetCurrentHostDefinedOptions ()
Returns the host defined options set for currently running script or module, if available.
Definition at line 9751 of file api.cc.
                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i::DirectHandle<i::Script> script;
  if (!i_isolate->CurrentReferrerScript().ToHandle(&script)) return {};
  return ToApiHandle<Data>(
      i::direct_handle(script->host_defined_options(), i_isolate));
}
References v8::internal::Isolate::CurrentReferrerScript(), v8::internal::direct_handle(), and v8::internal::script.
GetData()
void * v8::Isolate::GetData (uint32_t slot) [inline]
Retrieve embedder-specific data from the isolate.
Returns NULL if SetData has never been called for the given |slot|.
Definition at line 1865 of file v8-isolate.h.
                                    {
  using I = internal::Internals;
  return I::GetEmbedderData(this, slot);
}
References I.
Referenced by v8::PerIsolateData::Get().
GetDataFromSnapshotOnce() [1/2]
template<class T >
MaybeLocal< T > v8::Isolate::GetDataFromSnapshotOnce (size_t index) [inline]
Return data that was previously attached to the isolate snapshot via SnapshotCreator, and removes the reference to it.
Repeated call with the same index returns an empty MaybeLocal.
Definition at line 1876 of file v8-isolate.h.
                                                           {
  if (auto repr = GetDataFromSnapshotOnce(index);
      repr != internal::ValueHelper::kEmpty) {
    internal::PerformCastCheck(internal::ValueHelper::ReprAsValue<T>(repr));
    return Local<T>::FromRepr(repr);
  }
  return {};
}
References v8::Local< T >::FromRepr(), v8::internal::index, v8::internal::ValueHelper::kEmpty, and v8::internal::PerformCastCheck().
GetDataFromSnapshotOnce() [2/2]
i::ValueHelper::InternalRepresentationType v8::Isolate::GetDataFromSnapshotOnce (size_t index) [private]
Definition at line 10224 of file api.cc.
                  {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  auto list = i::Cast<i::FixedArray>(i_isolate->heap()->serialized_objects());
  return GetSerializedDataFromFixedArray(i_isolate, list, index);
}
References v8::anonymous_namespace{api.cc}::GetSerializedDataFromFixedArray(), v8::internal::Isolate::heap(), and v8::internal::index.
GetDefaultLocale()
std::string v8::Isolate::GetDefaultLocale ()
Returns the default locale in a string if Intl support is enabled.
Otherwise returns an empty string.
Definition at line 10934 of file api.cc.
                                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
#ifdef V8_INTL_SUPPORT
  return i_isolate->DefaultLocale();
#else
  return std::string();
#endif
}
References v8::internal::string.
GetEmbeddedCodeRange()
void v8::Isolate::GetEmbeddedCodeRange (const void ** start, size_t * length_in_bytes)
As GetCodeRange, but for embedded builtins (these live in a distinct memory region from other V8 Code objects).
Definition at line 10702 of file api.cc.
                                                            {
  // Note, we should return the embedded code rande from the .text section here.
  i::EmbeddedData d = i::EmbeddedData::FromBlob();
  *start = reinterpret_cast<const void*>(d.code());
  *length_in_bytes = d.code_size();
}
References v8::internal::EmbeddedData::code(), v8::internal::EmbeddedData::code_size(), and v8::internal::EmbeddedData::FromBlob().
GetEnteredOrMicrotaskContext()
v8::Local< v8::Context > v8::Isolate::GetEnteredOrMicrotaskContext ()
Returns either the last context entered through V8's C++ API, or the context of the currently running microtask while processing microtasks.
If a context is entered while executing a microtask, that context is returned.
Definition at line 9737 of file api.cc.
                                                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i::DirectHandle<i::NativeContext> last =
      i_isolate->handle_scope_implementer()->LastEnteredContext();
  if (last.is_null()) return {};
  return Utils::ToLocal(last);
}
References v8::internal::Isolate::handle_scope_implementer(), v8::internal::DirectHandle< T >::is_null(), and v8::internal::HandleScopeImplementer::LastEnteredContext().
Referenced by v8_inspector::V8Debugger::nearHeapLimitCallback(), v8::Shell::RealmCreateAllowCrossRealmAccess(), and v8::Shell::RealmCurrent().
GetGroup()
IsolateGroup v8::Isolate::GetGroup () const
Return the group for this isolate.
Definition at line 9944 of file api.cc.
                                     {
  const i::Isolate* i_isolate = reinterpret_cast<const i::Isolate*>(this);
  return IsolateGroup(i_isolate->isolate_group()->Acquire());
}
References v8::internal::IsolateGroup::Acquire(), and v8::internal::Isolate::isolate_group().
GetHashSeed()
uint64_t v8::Isolate::GetHashSeed ()
Returns the hash seed for that isolate, for testing purposes.
Definition at line 10961 of file api.cc.
                              {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return HashSeed(i_isolate);
}
References v8::internal::HashSeed().
GetHeapCodeAndMetadataStatistics()
bool v8::Isolate::GetHeapCodeAndMetadataStatistics (HeapCodeStatistics * object_statistics)
Get statistics about code and its metadata in the heap.
Parameters
object_statistics The HeapCodeStatistics object to fill in statistics of code, bytecode and their metadata.
Returns
true on success.
Definition at line 10399 of file api.cc.
                                         {
  if (!code_statistics) return false;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->CollectCodeStatistics();
  code_statistics->code_and_metadata_size_ =
      i_isolate->code_and_metadata_size();
  code_statistics->bytecode_and_metadata_size_ =
      i_isolate->bytecode_and_metadata_size();
  code_statistics->external_script_source_size_ =
      i_isolate->external_script_source_size();
  code_statistics->cpu_profiler_metadata_size_ =
      i::CpuProfiler::GetAllProfilersMemorySize(i_isolate);
  return true;
}
References v8::HeapCodeStatistics::bytecode_and_metadata_size_, v8::HeapCodeStatistics::code_and_metadata_size_, v8::internal::Heap::CollectCodeStatistics(), v8::HeapCodeStatistics::cpu_profiler_metadata_size_, v8::HeapCodeStatistics::external_script_source_size_, v8::internal::CpuProfiler::GetAllProfilersMemorySize(), and v8::internal::Isolate::heap().
GetHeapObjectStatisticsAtLastGC()
bool v8::Isolate::GetHeapObjectStatisticsAtLastGC (HeapObjectStatistics * object_statistics, size_t type_index)
Get statistics about objects in the heap.
Parameters
object_statistics The HeapObjectStatistics object to fill in statistics of objects of given type, which were live in the previous GC.
type_index The index of the type of object to fill details about, which ranges from 0 to NumberOfTrackedHeapObjectTypes() - 1.
Returns
true on success.
Definition at line 10372 of file api.cc.
                                                                {
  if (!object_statistics) return false;
  if (V8_LIKELY(!i::TracingFlags::is_gc_stats_enabled())) return false;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i::Heap* heap = i_isolate->heap();
  if (type_index >= heap->NumberOfTrackedHeapObjectTypes()) return false;
  const char* object_type;
  const char* object_sub_type;
  size_t object_count = heap->ObjectCountAtLastGC(type_index);
  size_t object_size = heap->ObjectSizeAtLastGC(type_index);
  if (!heap->GetObjectTypeName(type_index, &object_type, &object_sub_type)) {
    // There should be no objects counted when the type is unknown.
    DCHECK_EQ(object_count, 0U);
    DCHECK_EQ(object_size, 0U);
    return false;
  }
  object_statistics->object_type_ = object_type;
  object_statistics->object_sub_type_ = object_sub_type;
  object_statistics->object_count_ = object_count;
  object_statistics->object_size_ = object_size;
  return true;
}
References DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::TracingFlags::is_gc_stats_enabled(), v8::HeapObjectStatistics::object_count_, v8::HeapObjectStatistics::object_size_, v8::HeapObjectStatistics::object_sub_type_, v8::HeapObjectStatistics::object_type_, v8::base::internal::U, and V8_LIKELY.
GetHeapProfiler()
HeapProfiler * v8::Isolate::GetHeapProfiler ()
Returns heap profiler for this isolate.
Will return NULL until the isolate is initialized.
Definition at line 9702 of file api.cc.
                                       {
  i::HeapProfiler* heap_profiler =
      reinterpret_cast<i::Isolate*>(this)->heap()->heap_profiler();
  return reinterpret_cast<HeapProfiler*>(heap_profiler);
}
References heap().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::disable(), v8_inspector::V8HeapProfilerAgentImpl::getHeapObjectId(), v8_inspector::V8HeapProfilerAgentImpl::getSamplingProfile(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::objectByHeapObjectId(), v8_inspector::V8Debugger::queryObjects(), v8_inspector::V8HeapProfilerAgentImpl::requestHeapStatsUpdate(), v8_inspector::V8HeapProfilerAgentImpl::startSampling(), v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjectsInternal(), v8_inspector::V8HeapProfilerAgentImpl::stopSampling(), v8_inspector::V8HeapProfilerAgentImpl::stopTrackingHeapObjectsInternal(), and v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshotNow().
GetHeapSpaceStatistics()
bool v8::Isolate::GetHeapSpaceStatistics (HeapSpaceStatistics * space_statistics, size_t index)
Get the memory usage of a space in the heap.
Parameters
space_statistics The HeapSpaceStatistics object to fill in statistics.
index The index of the space to get statistics from, which ranges from 0 to NumberOfHeapSpaces() - 1.
Returns
true on success.
Definition at line 10334 of file api.cc.
                                                   {
  if (!space_statistics) return false;
  if (!i::Heap::IsValidAllocationSpace(static_cast<i::AllocationSpace>(index)))
    return false;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i::Heap* heap = i_isolate->heap();
  heap->FreeMainThreadLinearAllocationAreas();
  i::AllocationSpace allocation_space = static_cast<i::AllocationSpace>(index);
  space_statistics->space_name_ = i::ToString(allocation_space);
  if (allocation_space == i::RO_SPACE) {
    // RO_SPACE memory is shared across all isolates and accounted for
    // elsewhere.
    space_statistics->space_size_ = 0;
    space_statistics->space_used_size_ = 0;
    space_statistics->space_available_size_ = 0;
    space_statistics->physical_space_size_ = 0;
  } else {
    i::Space* space = heap->space(static_cast<int>(index));
    space_statistics->space_size_ = space ? space->CommittedMemory() : 0;
    space_statistics->space_used_size_ = space ? space->SizeOfObjects() : 0;
    space_statistics->space_available_size_ = space ? space->Available() : 0;
    space_statistics->physical_space_size_ =
        space ? space->CommittedPhysicalMemory() : 0;
  }
  return true;
}
References v8::internal::Isolate::heap(), v8::internal::index, v8::internal::Heap::IsValidAllocationSpace(), v8::HeapSpaceStatistics::physical_space_size_, v8::internal::RO_SPACE, space, v8::HeapSpaceStatistics::space_available_size_, v8::HeapSpaceStatistics::space_name_, v8::HeapSpaceStatistics::space_size_, v8::HeapSpaceStatistics::space_used_size_, and ToString().
GetHeapStatistics()
void v8::Isolate::GetHeapStatistics (HeapStatistics * heap_statistics)
Get statistics about the heap memory usage.
Definition at line 10274 of file api.cc.
                                                               {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i::Heap* heap = i_isolate->heap();
  heap->FreeMainThreadLinearAllocationAreas();
  // The order of acquiring memory statistics is important here. We query in
  // this order because of concurrent allocation: 1) used memory 2) committed
  // physical memory 3) committed memory. Therefore the condition used <=
  // committed physical <= committed should hold.
  heap_statistics->used_global_handles_size_ = heap->UsedGlobalHandlesSize();
  heap_statistics->total_global_handles_size_ = heap->TotalGlobalHandlesSize();
  DCHECK_LE(heap_statistics->used_global_handles_size_,
            heap_statistics->total_global_handles_size_);
  heap_statistics->used_heap_size_ = heap->SizeOfObjects();
  heap_statistics->total_physical_size_ = heap->CommittedPhysicalMemory();
  heap_statistics->total_heap_size_ = heap->CommittedMemory();
  heap_statistics->total_available_size_ = heap->Available();
  // TODO(dinfuehr): Right now used <= committed physical does not hold. Fix
  // this and add DCHECK.
  DCHECK_LE(heap_statistics->used_heap_size_,
            heap_statistics->total_heap_size_);
  heap_statistics->total_heap_size_executable_ =
      heap->CommittedMemoryExecutable();
  heap_statistics->heap_size_limit_ = heap->MaxReserved();
  // TODO(7424): There is no public API for the {WasmEngine} yet. Once such an
  // API becomes available we should report the malloced memory separately. For
  // now we just add the values, thereby over-approximating the peak slightly.
  heap_statistics->malloced_memory_ =
      i_isolate->allocator()->GetCurrentMemoryUsage() +
      i_isolate->string_table()->GetCurrentMemoryUsage();
  // On 32-bit systems backing_store_bytes() might overflow size_t temporarily
  // due to concurrent array buffer sweeping.
  heap_statistics->external_memory_ =
      i_isolate->heap()->backing_store_bytes() < SIZE_MAX
          ? static_cast<size_t>(i_isolate->heap()->backing_store_bytes())
          : SIZE_MAX;
  heap_statistics->peak_malloced_memory_ =
      i_isolate->allocator()->GetMaxMemoryUsage();
  heap_statistics->number_of_native_contexts_ = heap->NumberOfNativeContexts();
  heap_statistics->number_of_detached_contexts_ =
      heap->NumberOfDetachedContexts();
  heap_statistics->does_zap_garbage_ = i::heap::ShouldZapGarbage();
#if V8_ENABLE_WEBASSEMBLY
  heap_statistics->malloced_memory_ +=
      i::wasm::GetWasmEngine()->allocator()->GetCurrentMemoryUsage();
  heap_statistics->peak_malloced_memory_ +=
      i::wasm::GetWasmEngine()->allocator()->GetMaxMemoryUsage();
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::Isolate::allocator(), v8::internal::wasm::WasmEngine::allocator(), v8::internal::Heap::backing_store_bytes(), DCHECK_LE, v8::HeapStatistics::does_zap_garbage_, v8::HeapStatistics::external_memory_, v8::internal::StringTable::GetCurrentMemoryUsage(), v8::internal::AccountingAllocator::GetCurrentMemoryUsage(), v8::internal::AccountingAllocator::GetMaxMemoryUsage(), v8::internal::wasm::GetWasmEngine(), v8::internal::Isolate::heap(), v8::HeapStatistics::heap_size_limit_, v8::HeapStatistics::malloced_memory_, v8::HeapStatistics::number_of_detached_contexts_, v8::HeapStatistics::number_of_native_contexts_, v8::HeapStatistics::peak_malloced_memory_, v8::internal::heap::ShouldZapGarbage(), v8::internal::Isolate::string_table(), v8::HeapStatistics::total_available_size_, v8::HeapStatistics::total_global_handles_size_, v8::HeapStatistics::total_heap_size_, v8::HeapStatistics::total_heap_size_executable_, v8::HeapStatistics::total_physical_size_, v8::HeapStatistics::used_global_handles_size_, and v8::HeapStatistics::used_heap_size_.
Referenced by v8_inspector::V8RuntimeAgentImpl::getHeapUsage().
GetIncumbentContext()
v8::Local< v8::Context > v8::Isolate::GetIncumbentContext ()
Returns the Context that corresponds to the Incumbent realm in HTML spec.
 https://html.spec.whatwg.org/multipage/webappapis.html#incumbent
Definition at line 9745 of file api.cc.
                                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i::DirectHandle<i::NativeContext> context = i_isolate->GetIncumbentContext();
  return Utils::ToLocal(context);
}
References v8::internal::Isolate::GetIncumbentContext().
GetJSEntryStubs()
JSEntryStubs v8::Isolate::GetJSEntryStubs ()
Returns the JSEntryStubs necessary for use with the Unwinder API.
Definition at line 10710 of file api.cc.
                                      {
  JSEntryStubs entry_stubs;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  std::array<std::pair<i::Builtin, JSEntryStub*>, 3> stubs = {
      {{i::Builtin::kJSEntry, &entry_stubs.js_entry_stub},
       {i::Builtin::kJSConstructEntry, &entry_stubs.js_construct_entry_stub},
       {i::Builtin::kJSRunMicrotasksEntry,
        &entry_stubs.js_run_microtasks_entry_stub}}};
  for (auto& pair : stubs) {
    i::Tagged<i::Code> js_entry = i_isolate->builtins()->code(pair.first);
    pair.second->code.start =
        reinterpret_cast<const void*>(js_entry->instruction_start());
    pair.second->code.length_in_bytes = js_entry->instruction_size();
  }
  return entry_stubs;
}
References v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), v8::JSEntryStubs::js_construct_entry_stub, v8::JSEntryStubs::js_entry_stub, and v8::JSEntryStubs::js_run_microtasks_entry_stub.
GetMicrotasksPolicy()
MicrotasksPolicy v8::Isolate::GetMicrotasksPolicy () const
Returns the policy controlling how Microtasks are invoked.
Definition at line 10524 of file api.cc.
                                                    {
  i::Isolate* i_isolate =
      reinterpret_cast<i::Isolate*>(const_cast<Isolate*>(this));
  return i_isolate->default_microtask_queue()->microtasks_policy();
}
Referenced by PerformMicrotaskCheckpoint().
GetNumberOfDataSlots()
uint32_t v8::Isolate::GetNumberOfDataSlots () [inline], [static]
Returns the maximum number of available embedder data slots.
Valid slots are in the range of 0 - GetNumberOfDataSlots() - 1.
Definition at line 1870 of file v8-isolate.h.
                                       {
  using I = internal::Internals;
  return I::kNumIsolateDataSlots;
}
References I.
GetStackSample()
void v8::Isolate::GetStackSample (const RegisterState & state, void ** frames, size_t frames_limit, SampleInfo * sample_info)
Get a call stack sample from the isolate.
Parameters
state Execution state.
frames Caller allocated buffer to store stack frames.
frames_limit Maximum number of frames to capture. The buffer must be large enough to hold the number of frames.
sample_info The sample info is filled up by the function provides number of actual captured stack frames and the current VM state.
Note
GetStackSample should only be called when the JS thread is paused or interrupted. Otherwise the behavior is undefined.
Definition at line 10432 of file api.cc.
                                                                           {
  RegisterState regs = state;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  if (i::TickSample::GetStackSample(i_isolate, &regs,
                                    i::TickSample::kSkipCEntryFrame, frames,
                                    frames_limit, sample_info)) {
    return;
  }
  sample_info->frames_count = 0;
  sample_info->vm_state = OTHER;
  sample_info->external_callback_entry = nullptr;
}
References v8::SampleInfo::external_callback_entry, v8::SampleInfo::frames_count, v8::internal::TickSample::GetStackSample(), v8::internal::TickSample::kSkipCEntryFrame, v8::OTHER, and v8::SampleInfo::vm_state.
GetStackTraceLimit()
int v8::Isolate::GetStackTraceLimit ()
Get the stackTraceLimit property of Error.
Definition at line 10149 of file api.cc.
                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  int stack_trace_limit = 0;
  if (!i_isolate->GetStackTraceLimit(i_isolate, &stack_trace_limit)) {
    return i::v8_flags.stack_trace_limit;
  }
  return stack_trace_limit;
}
References v8::internal::Isolate::GetStackTraceLimit(), and v8::internal::v8_flags.
HandleExternalMemoryInterrupt()
void v8::Isolate::HandleExternalMemoryInterrupt () [private]
Definition at line 9635 of file api.cc.
                                            {
  i::Heap* heap = reinterpret_cast<i::Isolate*>(this)->heap();
  if (heap->gc_state() != i::Heap::NOT_IN_GC) return;
  heap->HandleExternalMemoryInterrupt();
}
References heap(), and v8::internal::Heap::NOT_IN_GC.
Referenced by AdjustAmountOfExternalAllocatedMemoryImpl().
HasPendingBackgroundTasks()
bool v8::Isolate::HasPendingBackgroundTasks ()
Returns true if there is ongoing background work within V8 that will eventually post a foreground task, like asynchronous WebAssembly compilation.
Definition at line 9879 of file api.cc.
                                        {
#if V8_ENABLE_WEBASSEMBLY
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return i::wasm::GetWasmEngine()->HasRunningCompileJob(i_isolate);
#else
  return false;
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::wasm::GetWasmEngine(), and v8::internal::wasm::WasmEngine::HasRunningCompileJob().
Referenced by v8::Shell::CompleteMessageLoop(), and v8::Shell::ExecuteModule().
HasPendingException()
bool v8::Isolate::HasPendingException ()
Returns true if an exception was thrown but not processed yet by an exception handler on JavaScript side or by v8::TryCatch handler.
This is an experimental feature and may still change significantly.
Definition at line 9777 of file api.cc.
                                  {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  if (i_isolate->has_exception()) {
    return true;
  }
  v8::TryCatch* try_catch_handler =
      i_isolate->thread_local_top()->try_catch_handler_;
  return try_catch_handler && try_catch_handler->HasCaught();
}
References v8::internal::Isolate::has_exception(), v8::TryCatch::HasCaught(), v8::internal::Isolate::thread_local_top(), and v8::internal::ThreadLocalTop::try_catch_handler_.
Referenced by v8::internal::ExternalizeStringExtension::CreateExternalizableString(), and v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString().
InContext()
bool v8::Isolate::InContext ()
Returns true if this isolate has a current context.
Definition at line 9718 of file api.cc.
                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return !i_isolate->context().is_null();
}
References v8::internal::Isolate::context().
Referenced by v8_inspector::AsyncStackTrace::capture(), v8_inspector::V8StackTraceImpl::capture(), v8_inspector::V8Debugger::currentContextGroupId(), and v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::toFramesVector().
IncreaseHeapLimitForDebugging()
void v8::Isolate::IncreaseHeapLimitForDebugging ()
Optional notification to tell V8 the current isolate is used for debugging and requires higher heap limit.
Definition at line 10670 of file api.cc.
                                            {
  // No-op.
}
Initialize()
void v8::Isolate::Initialize (Isolate * isolate, const CreateParams & params) [static]
Initialize an Isolate previously allocated by Isolate::Allocate().
Definition at line 9955 of file api.cc.
                                                              {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.IsolateInitialize");
  if (auto allocator = params.array_buffer_allocator_shared) {
    CHECK(params.array_buffer_allocator == nullptr ||
          params.array_buffer_allocator == allocator.get());
    i_isolate->set_array_buffer_allocator(allocator.get());
    i_isolate->set_array_buffer_allocator_shared(std::move(allocator));
  } else {
    CHECK_NOT_NULL(params.array_buffer_allocator);
    i_isolate->set_array_buffer_allocator(params.array_buffer_allocator);
  }
  if (params.snapshot_blob != nullptr) {
    i_isolate->set_snapshot_blob(params.snapshot_blob);
  } else {
    i_isolate->set_snapshot_blob(i::Snapshot::DefaultSnapshotBlob());
  }
  if (params.fatal_error_callback) {
    v8_isolate->SetFatalErrorHandler(params.fatal_error_callback);
  }
#if __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#endif
  if (params.oom_error_callback) {
    v8_isolate->SetOOMErrorHandler(params.oom_error_callback);
  }
#if __clang__
#pragma clang diagnostic pop
#endif
  if (params.counter_lookup_callback) {
    v8_isolate->SetCounterFunction(params.counter_lookup_callback);
  }
  if (params.create_histogram_callback) {
    v8_isolate->SetCreateHistogramFunction(params.create_histogram_callback);
  }
  if (params.add_histogram_sample_callback) {
    v8_isolate->SetAddHistogramSampleFunction(
        params.add_histogram_sample_callback);
  }
  i_isolate->set_api_external_references(params.external_references);
  i_isolate->set_allow_atomics_wait(params.allow_atomics_wait);
  CppHeap* cpp_heap = params.cpp_heap;
  if (!cpp_heap) {
    cpp_heap =
        CppHeap::Create(i::V8::GetCurrentPlatform(), CppHeapCreateParams{{}})
            .release();
  }
  i_isolate->heap()->ConfigureHeap(params.constraints, cpp_heap);
  if (params.constraints.stack_limit() != nullptr) {
    uintptr_t limit =
        reinterpret_cast<uintptr_t>(params.constraints.stack_limit());
    i_isolate->stack_guard()->SetStackLimit(limit);
    i_isolate->set_stack_size(base::Stack::GetStackStart() - limit);
  }
  // TODO(v8:2487): Once we got rid of Isolate::Current(), we can remove this.
  Isolate::Scope isolate_scope(v8_isolate);
  if (i_isolate->snapshot_blob() == nullptr) {
    FATAL(
        "V8 snapshot blob was not set during initialization. This can mean "
        "that the snapshot blob file is corrupted or missing.");
  }
  if (!i::Snapshot::Initialize(i_isolate)) {
    // If snapshot data was provided and we failed to deserialize it must
    // have been corrupted.
    FATAL(
        "Failed to deserialize the V8 snapshot blob. This can mean that the "
        "snapshot blob file is corrupted or missing.");
  }
  {
    // Set up code event handlers. Needs to be after i::Snapshot::Initialize
    // because that is where we add the isolate to WasmEngine.
    auto code_event_handler = params.code_event_handler;
    if (code_event_handler) {
      v8_isolate->SetJitCodeEventHandler(kJitCodeEventEnumExisting,
                                         code_event_handler);
    }
  }
  i_isolate->set_embedder_wrapper_type_index(
      params.embedder_wrapper_type_index);
  i_isolate->set_embedder_wrapper_object_index(
      params.embedder_wrapper_object_index);
  if (!i::V8::GetCurrentPlatform()
           ->GetForegroundTaskRunner(v8_isolate)
           ->NonNestableTasksEnabled()) {
    FATAL(
        "The current platform's foreground task runner does not have "
        "non-nestable tasks enabled. The embedder must provide one.");
  }
}
References v8::Isolate::CreateParams::add_histogram_sample_callback, v8::Isolate::CreateParams::allow_atomics_wait, v8::Isolate::CreateParams::array_buffer_allocator, v8::Isolate::CreateParams::array_buffer_allocator_shared, CHECK, CHECK_NOT_NULL, v8::Isolate::CreateParams::code_event_handler, v8::internal::Heap::ConfigureHeap(), v8::Isolate::CreateParams::constraints, v8::Isolate::CreateParams::counter_lookup_callback, v8::Isolate::CreateParams::cpp_heap, v8::CppHeap::Create(), v8::Isolate::CreateParams::create_histogram_callback, v8::internal::Snapshot::DefaultSnapshotBlob(), v8::Isolate::CreateParams::embedder_wrapper_object_index, v8::Isolate::CreateParams::embedder_wrapper_type_index, v8::Isolate::CreateParams::external_references, FATAL, v8::Isolate::CreateParams::fatal_error_callback, v8::internal::V8::GetCurrentPlatform(), v8::base::Stack::GetStackStart(), v8::internal::Isolate::heap(), v8::internal::Snapshot::Initialize(), v8::kJitCodeEventEnumExisting, v8::Isolate::CreateParams::oom_error_callback, v8::internal::Isolate::set_allow_atomics_wait(), v8::internal::Isolate::set_array_buffer_allocator(), v8::internal::Isolate::set_array_buffer_allocator_shared(), v8::internal::Isolate::set_stack_size(), SetAddHistogramSampleFunction(), SetCounterFunction(), SetCreateHistogramFunction(), SetFatalErrorHandler(), SetJitCodeEventHandler(), SetOOMErrorHandler(), v8::internal::StackGuard::SetStackLimit(), v8::Isolate::CreateParams::snapshot_blob, v8::internal::Isolate::stack_guard(), v8::ResourceConstraints::stack_limit(), and TRACE_EVENT_CALL_STATS_SCOPED.
Referenced by New().
InstallConditionalFeatures()
void v8::Isolate::InstallConditionalFeatures (Local< Context > context)
This function can be called by the embedder to signal V8 that the dynamic enabling of features has finished.
V8 can now set up dynamically added features.
Referenced by v8::Shell::EnableJSPI(), and v8::Shell::InstallConditionalFeatures().
IsCurrent()
bool v8::Isolate::IsCurrent () const
Return true if this isolate is currently active.
Definition at line 9929 of file api.cc.
                              {
  return reinterpret_cast<const i::Isolate*>(this)->IsCurrent();
}
IsDead()
bool v8::Isolate::IsDead ()
Check if V8 is dead and therefore unusable.
This is the case after fatal errors such as out-of-memory situations.
Definition at line 10826 of file api.cc.
                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return i_isolate->IsDead();
}
References v8::internal::Isolate::IsDead().
IsExecutionTerminating()
bool v8::Isolate::IsExecutionTerminating ()
Is V8 terminating JavaScript execution.
Returns true if JavaScript execution is currently terminating because of a call to TerminateExecution. In that case there are still JavaScript frames on the stack and the termination exception is still active.
Definition at line 9863 of file api.cc.
                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return i_isolate->is_execution_terminating();
}
References v8::internal::Isolate::is_execution_terminating().
Referenced by v8::Shell::CreateEvaluationContext(), v8::AsyncHooks::CreateHook(), v8::Shell::CreateRealm(), v8::internal::DefaultWasmAsyncResolvePromiseCallback(), v8_inspector::V8InspectorImpl::exceptionMetaDataContext(), v8::SourceGroup::ExecuteInThread(), v8::Shell::ExecuteString(), v8::PerIsolateData::HandleUnhandledPromiseRejections(), v8_inspector::V8Regex::match(), v8::Worker::ProcessMessage(), v8::anonymous_namespace{d8.cc}::ProcessMessages(), v8::AsyncHooks::PromiseHookDispatch(), v8::Shell::RealmEval(), v8_inspector::V8InspectorImpl::regexContext(), v8::anonymous_namespace{d8.cc}::RejectPromiseIfExecutionIsNotTerminating(), v8::Shell::ReportException(), v8::OnMessageFromWorkerTask::Run(), v8::Shell::RunMainIsolate(), v8_inspector::V8InspectorImpl::EvaluateScope::setTimeout(), v8::AsyncHooks::ShellPromiseHook(), v8::anonymous_namespace{d8.cc}::ThrowError(), v8::anonymous_namespace{d8.cc}::ThrowException(), and v8_inspector::V8Regex::V8Regex().
IsHeapLimitIncreasedForDebugging()
bool v8::Isolate::IsHeapLimitIncreasedForDebugging ()
Returns true if the heap limit was increased for debugging and the original heap limit was not restored yet.
Definition at line 10678 of file api.cc.
{ return false; }
IsInUse()
bool v8::Isolate::IsInUse ()
Check if this isolate is in use.
True if at least one thread Enter'ed this isolate.
Definition at line 10894 of file api.cc.
                      {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return i_isolate->IsInUse();
}
References v8::internal::Isolate::IsInUse().
LocaleConfigurationChangeNotification()
void v8::Isolate::LocaleConfigurationChangeNotification ()
Notification that the embedder has changed the locale.
V8 keeps a cache of various values used for locale computation. This notification will reset those cached values for the current context so that locale configuration changes would be reflected.
This API should not be called more than needed as it will negatively impact the performance of locale operations.
Definition at line 10923 of file api.cc.
                                                      {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  ApiRuntimeCallStatsScope rcs_scope(
      i_isolate, RCCId::kAPI_Isolate_LocaleConfigurationChangeNotification);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
#ifdef V8_INTL_SUPPORT
  i_isolate->ResetDefaultLocale();
#endif // V8_INTL_SUPPORT
}
LowMemoryNotification()
void v8::Isolate::LowMemoryNotification ()
Optional notification that the system is running low on memory.
V8 uses these notifications to attempt to free memory.
Definition at line 10578 of file api.cc.
                                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  {
    i::NestedTimedHistogramScope idle_notification_scope(
        i_isolate->counters()->gc_low_memory_notification());
    TRACE_EVENT0("v8", "V8.GCLowMemoryNotification");
    i_isolate->heap()->CollectAllAvailableGarbage(
        i::GarbageCollectionReason::kLowMemoryNotification);
  }
}
References v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::Isolate::counters(), v8::internal::Isolate::heap(), and TRACE_EVENT0.
Referenced by v8::Shell::CollectGarbage(), and v8::debug::ForceGarbageCollection().
MeasureMemory()
bool v8::Isolate::MeasureMemory (std::unique_ptr< MeasureMemoryDelegate > delegate, MeasureMemoryExecution execution = MeasureMemoryExecution::kDefault)
This API is experimental and may change significantly.
Enqueues a memory measurement request and invokes the delegate with the results.
Parameters
delegate the delegate that defines which contexts to measure and reports the results.
execution promptness executing the memory measurement. The kEager value is expected to be used only in tests.
Definition at line 10418 of file api.cc.
                                                              {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return i_isolate->heap()->MeasureMemory(std::move(delegate), execution);
}
References v8::internal::Isolate::heap(), and v8::internal::Heap::MeasureMemory().
Referenced by v8::Shell::PerformanceMeasureMemory().
MemoryPressureNotification()
void v8::Isolate::MemoryPressureNotification (MemoryPressureLevel level)
Optional notification that the system is running low on memory.
V8 uses these notifications to guide heuristics. It is allowed to call this function from another thread while the isolate is executing long running JavaScript code.
Definition at line 10634 of file api.cc.
                                                                  {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  bool on_isolate_thread =
      i_isolate->was_locker_ever_used()
          ? i_isolate->thread_manager()->IsLockedByCurrentThread()
          : i::ThreadId::Current() == i_isolate->thread_id();
  i_isolate->heap()->MemoryPressureNotification(level, on_isolate_thread);
}
References v8::internal::ThreadId::Current(), v8::internal::Isolate::heap(), v8::internal::ThreadManager::IsLockedByCurrentThread(), v8::internal::Heap::MemoryPressureNotification(), v8::internal::Isolate::thread_id(), v8::internal::Isolate::thread_manager(), and v8::internal::Isolate::was_locker_ever_used().
New() [1/2]
Isolate * v8::Isolate::New (const CreateParams & params) [static]
Creates a new isolate.
Does not change the currently entered isolate.
When an isolate is no longer used its resources should be freed by calling Dispose(). Using the delete operator is not allowed.
V8::Initialize() must have run prior to this.
Definition at line 10059 of file api.cc.
                                                       {
  return Isolate::New(IsolateGroup::GetDefault(), params);
}
References v8::IsolateGroup::GetDefault().
Referenced by v8::SourceGroup::ExecuteInThread(), v8::Worker::ExecuteInThread(), and v8::Shell::Main().
New() [2/2]
Isolate * v8::Isolate::New (const IsolateGroup & group, const CreateParams & params) [static]
Definition at line 10063 of file api.cc.
                                                         {
  Isolate* v8_isolate = Allocate(group);
  Initialize(v8_isolate, params);
  return v8_isolate;
}
References Allocate(), and Initialize().
NumberOfHeapSpaces()
size_t v8::Isolate::NumberOfHeapSpaces ()
Returns the number of spaces in the heap.
Definition at line 10330 of file api.cc.
                                   {
  return i::LAST_SPACE - i::FIRST_SPACE + 1;
}
References v8::internal::FIRST_SPACE, and v8::internal::LAST_SPACE.
NumberOfTrackedHeapObjectTypes()
size_t v8::Isolate::NumberOfTrackedHeapObjectTypes ()
Returns the number of types of objects tracked in the heap at GC.
Definition at line 10366 of file api.cc.
                                               {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i::Heap* heap = i_isolate->heap();
  return heap->NumberOfTrackedHeapObjectTypes();
}
References v8::internal::Isolate::heap().
operator delete()
void v8::Isolate::operator delete (void * , size_t) [delete]
operator delete[]()
void v8::Isolate::operator delete[] (void * , size_t) [delete]
operator new()
void* v8::Isolate::operator new (size_t size) [delete]
operator new[]()
void* v8::Isolate::operator new[] (size_t size) [delete]
operator=()
Isolate& v8::Isolate::operator= (const Isolate &) [delete]
PerformMicrotaskCheckpoint()
void v8::Isolate::PerformMicrotaskCheckpoint ()
Runs the default MicrotaskQueue until it gets empty and perform other microtask checkpoint steps, such as calling ClearKeptObjects.
Asserts that the MicrotasksPolicy is not kScoped. Any exceptions thrown by microtask callbacks are swallowed.
Definition at line 10497 of file api.cc.
                                         {
  DCHECK_NE(MicrotasksPolicy::kScoped, GetMicrotasksPolicy());
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->default_microtask_queue()->PerformCheckpoint(this);
}
References DCHECK_NE, GetMicrotasksPolicy(), and v8::kScoped.
RemoveBeforeCallEnteredCallback()
void v8::Isolate::RemoveBeforeCallEnteredCallback (BeforeCallEnteredCallback callback)
Removes callback that was installed by AddBeforeCallEnteredCallback.
Definition at line 10462 of file api.cc.
                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->RemoveBeforeCallEnteredCallback(callback);
}
References v8::internal::Isolate::RemoveBeforeCallEnteredCallback().
RemoveCallCompletedCallback()
void v8::Isolate::RemoveCallCompletedCallback (CallCompletedCallback callback)
Removes callback that was installed by AddCallCompletedCallback.
Definition at line 10474 of file api.cc.
                                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->RemoveCallCompletedCallback(callback);
}
References v8::internal::Isolate::RemoveCallCompletedCallback().
Referenced by v8_inspector::V8Debugger::reportTermination(), and v8_inspector::V8Debugger::~V8Debugger().
RemoveGCEpilogueCallback() [1/2]
void v8::Isolate::RemoveGCEpilogueCallback (GCCallback callback)
This function removes a callback which was added by AddGCEpilogueCallback.
Parameters
callback the callback to remove.
Definition at line 9831 of file api.cc.
                                                          {
  void* data = reinterpret_cast<void*>(callback);
  RemoveGCEpilogueCallback(CallGCCallbackWithoutData, data);
}
References v8::CallGCCallbackWithoutData().
RemoveGCEpilogueCallback() [2/2]
void v8::Isolate::RemoveGCEpilogueCallback (GCCallbackWithData callback, void * data = nullptr)
This function removes a callback which was added by AddGCEpilogueCallback.
Parameters
callback the callback to remove.
data Additional data that was used to install the callback.
Definition at line 9805 of file api.cc.
                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->RemoveGCEpilogueCallback(callback, data);
}
References v8::internal::Isolate::heap(), and v8::internal::Heap::RemoveGCEpilogueCallback().
RemoveGCPrologueCallback() [1/2]
void v8::Isolate::RemoveGCPrologueCallback (GCCallback callback)
This function removes a callback which was added by AddGCPrologueCallback.
Parameters
callback the callback to remove.
Definition at line 9821 of file api.cc.
                                                          {
  void* data = reinterpret_cast<void*>(callback);
  RemoveGCPrologueCallback(CallGCCallbackWithoutData, data);
}
References v8::CallGCCallbackWithoutData().
RemoveGCPrologueCallback() [2/2]
void v8::Isolate::RemoveGCPrologueCallback (GCCallbackWithData callback, void * data = nullptr)
Parameters
data Additional data that was used to install the callback.
Definition at line 9793 of file api.cc.
                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->RemoveGCPrologueCallback(callback, data);
}
References v8::internal::Isolate::heap(), and v8::internal::Heap::RemoveGCPrologueCallback().
RemoveMessageListeners()
void v8::Isolate::RemoveMessageListeners (MessageCallback callback)
Remove all message listeners from the specified callback function.
Definition at line 10859 of file api.cc.
                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::ArrayList> listeners = i_isolate->heap()->message_listeners();
  i::ReadOnlyRoots roots(i_isolate);
  for (int i = 0; i < listeners->length(); i++) {
    if (i::IsUndefined(listeners->get(i), roots)) {
      continue; // skip deleted ones
    }
    i::Tagged<i::FixedArray> listener =
        i::Cast<i::FixedArray>(listeners->get(i));
    v8::MessageCallback cur_callback =
        v8::ToCData<v8::MessageCallback, i::kMessageListenerTag>(
            i_isolate, listener->get(0));
    if (cur_callback == callback) {
      listeners->set(i, roots.undefined_value());
    }
  }
}
References v8::internal::Isolate::heap(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
RemoveMicrotasksCompletedCallback()
void v8::Isolate::RemoveMicrotasksCompletedCallback (MicrotasksCompletedCallbackWithData callback, void * data = nullptr)
Removes callback that was installed by AddMicrotasksCompletedCallback.
Definition at line 10538 of file api.cc.
                                                              {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->default_microtask_queue()->RemoveMicrotasksCompletedCallback(
      callback, data);
}
RemoveNearHeapLimitCallback()
void v8::Isolate::RemoveNearHeapLimitCallback (v8::NearHeapLimitCallback callback, size_t heap_limit)
Remove the given callback and restore the heap limit to the given limit.
If the given limit is zero, then it is ignored. If the current heap size is greater than the given limit, then the heap limit is restored to the minimal limit that is possible for the current heap size.
Definition at line 10813 of file api.cc.
                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->RemoveNearHeapLimitCallback(callback, heap_limit);
}
References v8::internal::Isolate::heap(), and v8::internal::Heap::RemoveNearHeapLimitCallback().
Referenced by v8_inspector::V8Debugger::disable().
RequestGarbageCollectionForTesting() [1/2]
void v8::Isolate::RequestGarbageCollectionForTesting (GarbageCollectionType type)
Request garbage collection in this Isolate.
It is only valid to call this function if --expose_gc was specified.
This should only be used for testing purposes and not to enforce a garbage collection schedule. It has strong negative impact on the garbage collection performance. Use MemoryPressureNotification() instead to influence the garbage collection schedule.
Definition at line 9888 of file api.cc.
                                                                           {
  Utils::ApiCheck(i::v8_flags.expose_gc,
                  "v8::Isolate::RequestGarbageCollectionForTesting",
                  "Must use --expose-gc");
  // The embedder must have entered the isolate (via `Isolate::Scope`) such that
  // the GC can get the "current" isolate from TLS.
  DCHECK_EQ(this, Isolate::TryGetCurrent());
  if (type == kMinorGarbageCollection) {
    reinterpret_cast<i::Isolate*>(this)->heap()->CollectGarbage(
        i::NEW_SPACE, i::GarbageCollectionReason::kTesting,
        kGCCallbackFlagForced);
  } else {
    DCHECK_EQ(kFullGarbageCollection, type);
    reinterpret_cast<i::Isolate*>(this)->heap()->PreciseCollectAllGarbage(
        i::GCFlag::kNoFlags, i::GarbageCollectionReason::kTesting,
        kGCCallbackFlagForced);
  }
}
References v8::Utils::ApiCheck(), DCHECK_EQ, heap(), kFullGarbageCollection, v8::kGCCallbackFlagForced, kMinorGarbageCollection, v8::internal::kNoFlags, v8::internal::NEW_SPACE, TryGetCurrent(), v8::internal::tracing::type, and v8::internal::v8_flags.
Referenced by RequestGarbageCollectionForTesting(), and v8::internal::RUNTIME_FUNCTION().
RequestGarbageCollectionForTesting() [2/2]
void v8::Isolate::RequestGarbageCollectionForTesting (GarbageCollectionType type, StackState stack_state)
Request garbage collection with a specific embedderstack state in this Isolate.
It is only valid to call this function if --expose_gc was specified.
This should only be used for testing purposes and not to enforce a garbage collection schedule. It has strong negative impact on the garbage collection performance. Use MemoryPressureNotification() instead to influence the garbage collection schedule.
Definition at line 9908 of file api.cc.
                                                                         {
  std::optional<i::EmbedderStackStateScope> stack_scope;
  if (type == kFullGarbageCollection) {
    stack_scope.emplace(reinterpret_cast<i::Isolate*>(this)->heap(),
                        i::EmbedderStackStateOrigin::kExplicitInvocation,
                        stack_state);
  }
  RequestGarbageCollectionForTesting(type);
}
References heap(), kFullGarbageCollection, RequestGarbageCollectionForTesting(), and v8::internal::tracing::type.
RequestInterrupt()
void v8::Isolate::RequestInterrupt (InterruptCallback callback, void * data)
Request V8 to interrupt long running JavaScript code and invoke the given |callback| passing the given |data| to it.
After |callback| returns control will be returned to the JavaScript code. There may be a number of interrupt requests in flight. Can be called from another thread without acquiring a |Locker|. Registered |callback| must not reenter interrupted Isolate.
Definition at line 9874 of file api.cc.
                                                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->RequestInterrupt(callback, data);
}
References v8::internal::Isolate::RequestInterrupt().
Referenced by v8_inspector::V8Debugger::interruptAndBreak(), v8_inspector::V8Debugger::nearHeapLimitCallback(), and v8::internal::wasm::gdb_server::GdbServer::Suspend().
RestoreOriginalHeapLimit()
void v8::Isolate::RestoreOriginalHeapLimit ()
Restores the original heap limit after IncreaseHeapLimitForDebugging().
Definition at line 10674 of file api.cc.
                                       {
  // No-op.
}
Referenced by v8_inspector::V8Debugger::handleProgramBreak().
SetAbortOnUncaughtExceptionCallback()
void v8::Isolate::SetAbortOnUncaughtExceptionCallback (AbortOnUncaughtExceptionCallback callback)
Definition at line 10114 of file api.cc.
                                               {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetAbortOnUncaughtExceptionCallback(callback);
}
References v8::internal::Isolate::SetAbortOnUncaughtExceptionCallback().
SetAddCrashKeyCallback()
void v8::Isolate::SetAddCrashKeyCallback (AddCrashKeyCallback callback)
Enables the host application to provide a mechanism for recording a predefined set of data as crash keys to be used in postmortem debugging in case of a crash.
Definition at line 10573 of file api.cc.
                                                                 {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetAddCrashKeyCallback(callback);
}
References v8::internal::Isolate::SetAddCrashKeyCallback().
SetAddHistogramSampleFunction()
void v8::Isolate::SetAddHistogramSampleFunction (AddHistogramSampleCallback callback)
Definition at line 10559 of file api.cc.
                                         {
  reinterpret_cast<i::Isolate*>(this)
      ->counters()
      ->SetAddHistogramSampleFunction(callback);
}
Referenced by Initialize(), and v8::Shell::MapCounters().
SetAllowAtomicsWait()
void v8::Isolate::SetAllowAtomicsWait (bool allow)
Set whether calling Atomics.wait (a function that may block) is allowed in this isolate.
This can also be configured via CreateParams::allow_atomics_wait.
Definition at line 10899 of file api.cc.
                                            {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->set_allow_atomics_wait(allow);
}
References v8::internal::Isolate::set_allow_atomics_wait().
SetAllowWasmCodeGenerationCallback()
void v8::Isolate::SetAllowWasmCodeGenerationCallback (AllowWasmCodeGenerationCallback callback)
Set the callback to invoke to check if wasm code generation should be allowed.
Referenced by v8::internal::RUNTIME_FUNCTION().
SetBatterySaverMode()
void v8::Isolate::SetBatterySaverMode (bool battery_saver_mode_enabled)
Optional request from the embedder to tune v8 towards energy efficiency rather than speed if battery_saver_mode_enabled is true, because the embedder is in battery saver mode.
If false, the correct tuning is left to v8 to decide.
Definition at line 10643 of file api.cc.
                                                                 {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->set_battery_saver_mode_enabled(battery_saver_mode_enabled);
}
References v8::internal::Isolate::set_battery_saver_mode_enabled().
SetCaptureStackTraceForUncaughtExceptions()
void v8::Isolate::SetCaptureStackTraceForUncaughtExceptions (bool capture, int frame_limit = 10, StackTrace::StackTraceOptions options = StackTrace::kOverview)
Tells V8 to capture current stack trace when uncaught exception occurs and report it to the message listeners.
The option is off by default.
Definition at line 10887 of file api.cc.
                                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetCaptureStackTraceForUncaughtExceptions(capture, frame_limit,
                                                       options);
}
References v8::internal::Isolate::SetCaptureStackTraceForUncaughtExceptions().
Referenced by v8::Shell::PromiseRejectCallback(), and v8_inspector::V8Debugger::setMaxCallStackSizeToCapture().
SetContinuationPreservedEmbedderData()
void v8::Isolate::SetContinuationPreservedEmbedderData (Local< Value > data)
Sets a value that will be stored on continuations and reset while the continuation runs.
Definition at line 10242 of file api.cc.
                                                                    {
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  if (data.IsEmpty())
    data = v8::Undefined(reinterpret_cast<v8::Isolate*>(this));
  i_isolate->isolate_data()->set_continuation_preserved_embedder_data(
      *Utils::OpenDirectHandle(*data));
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
}
References v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::Isolate::isolate_data(), v8::Utils::OpenDirectHandle(), v8::internal::IsolateData::set_continuation_preserved_embedder_data(), and v8::Undefined().
SetContinuationPreservedEmbedderDataV2()
void v8::Isolate::SetContinuationPreservedEmbedderDataV2 (Local< Data > data)
Sets a value that will be stored on continuations and restored while the continuation runs.
If data is empty, the continuation preserved embedder data is set to undefined.
Definition at line 10263 of file api.cc.
                                                                     {
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  if (data.IsEmpty()) {
    data = v8::Undefined(reinterpret_cast<v8::Isolate*>(this));
  }
  i_isolate->isolate_data()->set_continuation_preserved_embedder_data(
      *Utils::OpenDirectHandle(*data));
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
}
References v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::Isolate::isolate_data(), v8::Utils::OpenDirectHandle(), v8::internal::IsolateData::set_continuation_preserved_embedder_data(), and v8::Undefined().
SetCounterFunction()
void v8::Isolate::SetCounterFunction (CounterLookupCallback callback)
Enables the host application to provide a mechanism for recording statistics counters.
Definition at line 10549 of file api.cc.
                                                               {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->counters()->ResetCounterFunction(callback);
}
References v8::internal::Isolate::counters(), and v8::internal::Counters::ResetCounterFunction().
Referenced by Initialize(), v8::Shell::MapCounters(), and anonymous_namespace{mksnapshot.cc}::MaybeSetCounterFunction().
SetCreateHistogramFunction()
void v8::Isolate::SetCreateHistogramFunction (CreateHistogramCallback callback)
Enables the host application to provide a mechanism for recording histograms.
The CreateHistogram function returns a histogram which will later be passed to the AddHistogramSample function.
Definition at line 10554 of file api.cc.
                                                                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->counters()->ResetCreateHistogramFunction(callback);
}
References v8::internal::Isolate::counters(), and v8::internal::Counters::ResetCreateHistogramFunction().
Referenced by Initialize(), and v8::Shell::MapCounters().
SetData()
void v8::Isolate::SetData (uint32_t slot, void * data) [inline]
Associate embedder-specific data with the isolate.
|slot| has to be between 0 and GetNumberOfDataSlots() - 1.
Definition at line 1860 of file v8-isolate.h.
                                               {
  using I = internal::Internals;
  I::SetEmbedderData(this, slot, data);
}
References I.
Referenced by v8::PerIsolateData::PerIsolateData(), and v8::PerIsolateData::~PerIsolateData().
SetEmbedderRootsHandler()
void v8::Isolate::SetEmbedderRootsHandler (EmbedderRootsHandler * handler)
Sets an embedder roots handle that V8 should consider when performing non-unified heap garbage collections.
The intended use case is for setting a custom handler after invoking AttachCppHeap().
V8 does not take ownership of the handler.
Definition at line 9836 of file api.cc.
                                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->SetEmbedderRootsHandler(handler);
}
References v8::internal::Isolate::heap(), and v8::internal::Heap::SetEmbedderRootsHandler().
SetEventLogger()
void v8::Isolate::SetEventLogger (LogEventCallback that)
Set the callback to invoke for logging event.
Definition at line 10451 of file api.cc.
                                                  {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->set_event_logger(that);
}
SetExceptionPropagationCallback()
void v8::Isolate::SetExceptionPropagationCallback (ExceptionPropagationCallback callback)
This is a part of experimental Api and might be changed without further notice.
Do not use it.
Set callback to notify about a new exception being thrown.
Definition at line 10490 of file api.cc.
                                           {
  if (callback == nullptr) return;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetExceptionPropagationCallback(callback);
}
References v8::internal::Isolate::SetExceptionPropagationCallback().
SetFailedAccessCheckCallbackFunction()
void v8::Isolate::SetFailedAccessCheckCallbackFunction (FailedAccessCheckCallback callback)
Callback function for reporting failed access checks.
Definition at line 10881 of file api.cc.
                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetFailedAccessCheckCallback(callback);
}
References v8::internal::Isolate::SetFailedAccessCheckCallback().
SetFatalErrorHandler()
void v8::Isolate::SetFatalErrorHandler (FatalErrorCallback that)
Set the callback to invoke in case of fatal errors.
Referenced by Initialize().
SetGetExternallyAllocatedMemoryInBytesCallback()
void v8::Isolate::SetGetExternallyAllocatedMemoryInBytesCallback (GetExternallyAllocatedMemoryInBytesCallback callback)
Set the callback that tells V8 how much memory is currently allocated externally of the V8 heap.
Ideally this memory is somehow connected to V8 objects and may get freed-up when the corresponding V8 objects get collected by a V8 garbage collection.
Definition at line 9852 of file api.cc.
                                                          {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->heap()->SetGetExternallyAllocatedMemoryInBytesCallback(callback);
}
References v8::internal::Isolate::heap(), and v8::internal::Heap::SetGetExternallyAllocatedMemoryInBytesCallback().
SetHostCreateShadowRealmContextCallback()
void v8::Isolate::SetHostCreateShadowRealmContextCallback (HostCreateShadowRealmContextCallback callback)
This specifies the callback called by the upcoming ShadowRealm construction language feature to retrieve host created globals.
Definition at line 10138 of file api.cc.
                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetHostCreateShadowRealmContextCallback(callback);
}
References v8::internal::Isolate::SetHostCreateShadowRealmContextCallback().
Referenced by v8::Shell::Initialize().
SetHostImportModuleDynamicallyCallback()
void v8::Isolate::SetHostImportModuleDynamicallyCallback (HostImportModuleDynamicallyCallback callback)
This specifies the callback called by the upcoming dynamic import() language feature to load modules.
Definition at line 10120 of file api.cc.
                                                  {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetHostImportModuleDynamicallyCallback(callback);
}
References v8::internal::Isolate::SetHostImportModuleDynamicallyCallback().
Referenced by v8::Shell::Initialize().
SetHostImportModuleWithPhaseDynamicallyCallback()
void v8::Isolate::SetHostImportModuleWithPhaseDynamicallyCallback (HostImportModuleWithPhaseDynamicallyCallback callback)
This specifies the callback called by the upcoming dynamic import() and import.source() language feature to load modules.
This API is experimental and is expected to be changed or removed in the future. The callback is currently only called when for source-phase imports. Evaluation-phase imports use the existing HostImportModuleDynamicallyCallback callback.
Definition at line 10126 of file api.cc.
                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetHostImportModuleWithPhaseDynamicallyCallback(callback);
}
References v8::internal::Isolate::SetHostImportModuleWithPhaseDynamicallyCallback().
Referenced by v8::Shell::Initialize().
SetHostInitializeImportMetaObjectCallback()
void v8::Isolate::SetHostInitializeImportMetaObjectCallback (HostInitializeImportMetaObjectCallback callback)
This specifies the callback called by the upcoming import.meta language feature to retrieve host-defined meta data for a module.
Definition at line 10132 of file api.cc.
                                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetHostInitializeImportMetaObjectCallback(callback);
}
References v8::internal::Isolate::SetHostInitializeImportMetaObjectCallback().
Referenced by v8::Shell::Initialize().
SetIdle()
void v8::Isolate::SetIdle (bool is_idle)
Tells the VM whether the embedder is idle or not.
Definition at line 9708 of file api.cc.
                                  {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetIdle(is_idle);
}
References v8::internal::Isolate::SetIdle().
Referenced by v8_inspector::V8InspectorImpl::idleFinished(), and v8_inspector::V8InspectorImpl::idleStarted().
SetIsJSApiWrapperNativeErrorCallback()
void v8::Isolate::SetIsJSApiWrapperNativeErrorCallback (IsJSApiWrapperNativeErrorCallback callback)
Set the callback that checks whether a Error.isError should return true for a JSApiWrapper object, i.e.
whether it represents a native JS error. For example, in an HTML embedder, DOMExceptions are considered native errors.
SetIsLoading()
void v8::Isolate::SetIsLoading (bool is_loading)
Optional notification to tell V8 whether the embedder is currently loading resources.
If the embedder uses this notification, it should call SetIsLoading(true) when loading starts and SetIsLoading(false) when it ends. It's valid to call SetIsLoading(true) again while loading, which will update the timestamp when V8 considers the load started. Calling SetIsLoading(false) while not loading does nothing. V8 uses these notifications to guide heuristics. This is an unfinished experimental feature. Semantics and implementation may change frequently.
Definition at line 10660 of file api.cc.
                                          {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetIsLoading(is_loading);
}
References v8::internal::Isolate::SetIsLoading().
SetJitCodeEventHandler()
void v8::Isolate::SetJitCodeEventHandler (JitCodeEventOptions options, JitCodeEventHandler event_handler)
Allows the host application to provide the address of a function that is notified each time code is added, moved or removed.
Parameters
options options for the JIT code event handler.
event_handler the JIT code event handler, which will be invoked each time code is added, moved or removed.
Note
event_handler won't get notified of existent code.
since code removal notifications are not currently issued, the event_handler may get notifications of code that overlaps earlier code notifications. This happens when code areas are reused, and the earlier overlapping code areas should therefore be discarded.
the events passed to event_handler and the strings they point to are not guaranteed to live past each call. The event_handler must copy strings and other parameters it needs to keep around.
the set of events declared in JitCodeEvent::EventType is expected to grow over time, and the JitCodeEvent structure is expected to accrue new members. The event_handler function must ignore event codes it does not recognize to maintain future compatibility.
Use Isolate::CreateParams to get events for code executed during Isolate setup.
Definition at line 10680 of file api.cc.
                                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  // Ensure that logging is initialized for our isolate.
  i_isolate->InitializeLoggingAndCounters();
  i_isolate->v8_file_logger()->SetCodeEventHandler(options, event_handler);
}
References v8::internal::Isolate::InitializeLoggingAndCounters(), v8::internal::V8FileLogger::SetCodeEventHandler(), and v8::internal::Isolate::v8_file_logger().
Referenced by Initialize().
SetMemorySaverMode()
void v8::Isolate::SetMemorySaverMode (bool memory_saver_mode_enabled)
Optional request from the embedder to tune v8 towards memory efficiency rather than speed if memory_saver_mode_enabled is true, because the embedder is in memory saver mode.
If false, the correct tuning is left to v8 to decide.
Definition at line 10648 of file api.cc.
                                                               {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->set_memory_saver_mode_enabled(memory_saver_mode_enabled);
}
References v8::internal::Isolate::set_memory_saver_mode_enabled().
SetMetricsRecorder()
void v8::Isolate::SetMetricsRecorder (const std::shared_ptr< metrics::Recorder > & metrics_recorder)
Enables the host application to provide a mechanism for recording event based metrics.
In order to use this interface include/v8-metrics.h needs to be included and the recorder needs to be derived from the Recorder base class defined there. This method can only be called once per isolate and must happen during isolate initialization before background threads are spawned.
Definition at line 10566 of file api.cc.
                                                            {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->metrics_recorder()->SetEmbedderRecorder(i_isolate,
                                                     metrics_recorder);
}
References v8::internal::Isolate::metrics_recorder().
SetMicrotasksPolicy()
void v8::Isolate::SetMicrotasksPolicy (MicrotasksPolicy policy)
Controls how Microtasks are invoked.
See MicrotasksPolicy for details.
Definition at line 10519 of file api.cc.
                                                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->default_microtask_queue()->set_microtasks_policy(policy);
}
SetModifyCodeGenerationFromStringsCallback()
void v8::Isolate::SetModifyCodeGenerationFromStringsCallback (ModifyCodeGenerationFromStringsCallback2 callback)
Set the callback to invoke to check if code generation from strings should be allowed.
Referenced by v8::internal::RUNTIME_FUNCTION().
SetOOMErrorHandler()
void v8::Isolate::SetOOMErrorHandler (OOMErrorCallback that)
Set the callback to invoke in case of OOM errors.
Referenced by Initialize().
SetPrepareStackTraceCallback()
void v8::Isolate::SetPrepareStackTraceCallback (PrepareStackTraceCallback callback)
This specifies the callback called when the stack property of Error is accessed.
Definition at line 10144 of file api.cc.
                                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetPrepareStackTraceCallback(callback);
}
References v8::internal::Isolate::SetPrepareStackTraceCallback().
SetPriority() [1/3]
void v8::Isolate::SetPriority (Priority priority)
Optional notification that the isolate changed priority.
V8 uses the priority value to guide heuristics.
Definition at line 10629 of file api.cc.
                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  return i_isolate->SetPriority(priority);
}
References v8::internal::Isolate::SetPriority().
SetPriority() [2/3]
Use v8::Isolate::SetPriority (Priority::kBestEffort)
Optional notification that the isolate switched to the background.
V8 uses these notifications to guide heuristics.
SetPriority() [3/3]
Use v8::Isolate::SetPriority (Priority::kUserBlocking)
Optional notification that the isolate switched to the foreground.
V8 uses these notifications to guide heuristics.
SetPromiseHook()
void v8::Isolate::SetPromiseHook (PromiseHook hook)
Set the PromiseHook callback for various promise lifecycle events.
Definition at line 10479 of file api.cc.
                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetPromiseHook(hook);
}
References v8::internal::Isolate::SetPromiseHook().
Referenced by v8::AsyncHooks::AsyncHooks(), and v8::AsyncHooks::~AsyncHooks().
SetPromiseRejectCallback()
void v8::Isolate::SetPromiseRejectCallback (PromiseRejectCallback callback)
Set callback to notify about promise reject with no handler, or revocation of such a previous notification once the handler is added.
Definition at line 10484 of file api.cc.
                                                                     {
  if (callback == nullptr) return;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetPromiseRejectCallback(callback);
}
References v8::internal::Isolate::SetPromiseRejectCallback().
Referenced by v8::Shell::Initialize().
SetReleaseCppHeapCallbackForTesting()
void v8::Isolate::SetReleaseCppHeapCallbackForTesting (ReleaseCppHeapCallback callback)
Sets a callback on the isolate that gets called when the CppHeap gets detached.
The callback can then either take ownership of the CppHeap, or the CppHeap gets deallocated.
Definition at line 9846 of file api.cc.
                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->SetReleaseCppHeapCallback(callback);
}
References v8::internal::Isolate::SetReleaseCppHeapCallback().
SetSharedArrayBufferConstructorEnabledCallback()
void v8::Isolate::SetSharedArrayBufferConstructorEnabledCallback (SharedArrayBufferConstructorEnabledCallback callback)
SetStackLimit()
void v8::Isolate::SetStackLimit (uintptr_t stack_limit)
Modifies the stack limit for this Isolate.
Parameters
stack_limit An address beyond which the Vm's stack may not grow.
Note
If you are using threads then you should hold the V8::Locker lock while setting the stack limit and you must set a non-default stack limit separately for each thread.
Definition at line 10688 of file api.cc.
                                                 {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  CHECK(stack_limit);
  i_isolate->stack_guard()->SetStackLimit(stack_limit);
  i_isolate->set_stack_size(base::Stack::GetStackStart() - stack_limit);
}
References CHECK, v8::base::Stack::GetStackStart(), v8::internal::Isolate::set_stack_size(), v8::internal::StackGuard::SetStackLimit(), and v8::internal::Isolate::stack_guard().
SetUseCounterCallback()
void v8::Isolate::SetUseCounterCallback (UseCounterCallback callback)
Sets a callback for counting the number of times a feature of V8 is used.
Definition at line 10545 of file api.cc.
                                                               {
  reinterpret_cast<i::Isolate*>(this)->SetUseCounterCallback(callback);
}
SetWasmAsyncResolvePromiseCallback()
void v8::Isolate::SetWasmAsyncResolvePromiseCallback (WasmAsyncResolvePromiseCallback callback)
Referenced by v8::Shell::Initialize().
SetWasmImportedStringsEnabledCallback()
void v8::Isolate::SetWasmImportedStringsEnabledCallback (WasmImportedStringsEnabledCallback callback)
Referenced by v8::internal::RUNTIME_FUNCTION().
SetWasmInstanceCallback()
void v8::Isolate::SetWasmInstanceCallback (ExtensionCallback callback)
Referenced by v8::internal::RUNTIME_FUNCTION().
SetWasmJSPIEnabledCallback()
void v8::Isolate::SetWasmJSPIEnabledCallback (WasmJSPIEnabledCallback callback)
Referenced by v8::Shell::EnableJSPI().
SetWasmLoadSourceMapCallback()
void v8::Isolate::SetWasmLoadSourceMapCallback (WasmLoadSourceMapCallback callback)
Referenced by v8::Shell::CreateEvaluationContext().
SetWasmModuleCallback()
void v8::Isolate::SetWasmModuleCallback (ExtensionCallback callback)
Embedder over{ride|load} injection points for wasm APIs.
The expectation is that the embedder sets them at most once.
Referenced by v8::internal::RUNTIME_FUNCTION().
SetWasmStreamingCallback()
void v8::Isolate::SetWasmStreamingCallback (WasmStreamingCallback callback)
TerminateExecution()
void v8::Isolate::TerminateExecution ()
Forcefully terminate the current thread of JavaScript execution in the given isolate.
This method can be used by any thread even if that thread has not acquired the V8 lock with a Locker object.
Definition at line 9858 of file api.cc.
                                 {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  i_isolate->stack_guard()->RequestTerminateExecution();
}
References v8::internal::Isolate::stack_guard().
Referenced by v8::Shell::ExecuteString(), v8::Worker::ProcessMessage(), v8_inspector::V8InspectorImpl::EvaluateScope::TerminateTask::Run(), v8::Shell::ScheduleTermination(), v8::Worker::Terminate(), and v8_inspector::V8Debugger::terminateExecution().
ThrowError() [1/2]
template<int N>
Local<Value> v8::Isolate::ThrowError (const char(&) message[N]) [inline]
Schedules a v8::Exception::Error with the given message.
See ThrowException for more details. Templatized to provide compile-time errors in case of too long strings (see v8::String::NewFromUtf8Literal).
Definition at line 1122 of file v8-isolate.h.
                                                    {
    return ThrowError(String::NewFromUtf8Literal(this, message));
  }
References v8::String::NewFromUtf8Literal(), and v8::anonymous_namespace{d8.cc}::ThrowError().
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArrayFastCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArraySlowCallback(), v8::D8Console::Assert(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AssertIsExternal(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeSetterSlowCallback(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberSlowCallback(), v8::Shell::ChangeDirectory(), v8::CheckItsADirectory(), v8::ChildLaunchedOK(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ComparePointersSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CopyStringFastCallback(), v8::internal::ExternalizeStringExtension::CreateExternalizableString(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString(), v8::CreateFastCAPIObject(), v8::AsyncHooks::CreateHook(), v8::CreateLeafInterfaceObject(), v8_inspector::V8Console::createTask(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::EnforceRangeCompareSlowCallback(), v8::internal::ExternalizeStringExtension::Externalize(), v8::Serializer::FinalizeTransfer(), v8::GetStdout(), v8::GetTimeouts(), v8::ExecArgs::Init(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectSlowCallback(), v8::internal::ExternalizeStringExtension::IsOneByte(), v8::Shell::MakeDirectory(), v8::internal::CpuTraceMarkExtension::Mark(), v8::internal::VTuneDomainSupportExtension::Mark(), v8::mkdirp(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::PassPointerSlowCallback(), v8::Serializer::PrepareTransfer(), v8::Shell::RemoveDirectory(), v8_inspector::V8Console::runTask(), v8::Shell::SetEnvironment(), v8::Shell::SetUMask(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback(), v8::Shell::System(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemoryFastCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemorySlowCallback(), v8::anonymous_namespace{d8.cc}::ThrowError(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ThrowFallbackSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ThrowNoFallbackFastCallback(), v8::Shell::UnsetEnvironment(), v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook(), and v8::WaitForChild().
ThrowError() [2/2]
v8::Local< Value > v8::Isolate::ThrowError (Local< String > message)
Definition at line 9759 of file api.cc.
                                                            {
  return ThrowException(v8::Exception::Error(message));
}
References v8::Exception::Error(), and ThrowException().
ThrowException()
v8::Local< Value > v8::Isolate::ThrowException (Local< Value > exception)
Schedules an exception to be thrown when returning to JavaScript.
When an exception has been scheduled it is illegal to invoke any JavaScript operation; the caller must return immediately and only after the exception has been handled does it become legal to invoke JavaScript operations.
Definition at line 9763 of file api.cc.
                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  EnterV8BasicScope api_scope(i_isolate);
  i_isolate->clear_internal_exception();
  // If we're passed an empty handle, we throw an undefined exception
  // to deal more gracefully with out of memory situations.
  if (value.IsEmpty()) {
    i_isolate->Throw(i::ReadOnlyRoots(i_isolate).undefined_value());
  } else {
    i_isolate->Throw(*Utils::OpenDirectHandle(*value));
  }
  return v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate));
}
References v8::internal::Isolate::clear_internal_exception(), v8::Utils::OpenDirectHandle(), v8::internal::Isolate::Throw(), v8::Undefined(), and v8::internal::value.
Referenced by v8::Shell::ExecuteModule(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8::Serializer::ThrowDataCloneError(), ThrowError(), v8::anonymous_namespace{d8.cc}::ThrowException(), and v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ThrowRangeException().
TryGetCurrent()
Isolate * v8::Isolate::TryGetCurrent () [static]
Returns the entered isolate for the current thread or NULL in case there is no current isolate.
No checks are performed by this method.
Definition at line 9924 of file api.cc.
                                {
  i::Isolate* i_isolate = i::Isolate::TryGetCurrent();
  return reinterpret_cast<Isolate*>(i_isolate);
}
Referenced by v8::internal::HeapAllocator::AllocateRaw(), v8::internal::Heap::CollectGarbage(), v8::internal::HandleScope::CreateHandle(), v8::internal::GetHeapFromWritableObject(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::Isolate::IterateRegistersAndStackOfSimulator(), v8::internal::LocalHeap::LocalHeap(), RequestGarbageCollectionForTesting(), v8::internal::compiler::Revectorizer::Revectorizer(), v8::internal::compiler::turboshaft::WasmRevecPhase::Run(), v8::internal::IncrementalMarking::Start(), v8::internal::Heap::StartIncrementalMarking(), and v8::internal::TemplateInfo::TryGetIsolate().
ValidateAndCanonicalizeUnicodeLocaleId()
Maybe< std::string > v8::Isolate::ValidateAndCanonicalizeUnicodeLocaleId (std::string_view locale)
Returns a canonical and case-regularized form of locale if Intl support is enabled.
If the locale is not syntactically well-formed, throws a RangeError.
If Intl support is not enabled, returns Nothing<std::string>().
Corresponds to the combination of the abstract operations IsStructurallyValidLanguageTag and CanonicalizeUnicodeLocaleId. See: https://tc39.es/ecma402/#sec-isstructurallyvalidlanguagetag https://tc39.es/ecma402/#sec-canonicalizeunicodelocaleid
Definition at line 10945 of file api.cc.
                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  EnterV8NoScriptScope<> api_scope{
      i_isolate, RCCId::kAPI_Isolate_ValidateAndCanonicalizeUnicodeLocaleId};
#ifdef V8_INTL_SUPPORT
  return i::Intl::ValidateAndCanonicalizeUnicodeLocaleId(i_isolate, tag);
#else
  THROW_NEW_ERROR_RETURN_VALUE(
      i_isolate,
      NewRangeError(i::MessageTemplate::kInvalidLanguageTag,
                    i_isolate->factory()->NewStringFromAsciiChecked(tag)),
      Nothing<std::string>());
#endif
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId().
Friends And Related Function Documentation
ExternalMemoryAccounter
friend class ExternalMemoryAccounter [friend]
Definition at line 1852 of file v8-isolate.h.
PersistentValueMapBase
template<class K , class V , class Traits >
friend class PersistentValueMapBase [friend]
Definition at line 1851 of file v8-isolate.h.
Member Data Documentation
kMinCodePagesBufferSize
constexpr size_t v8::Isolate::kMinCodePagesBufferSize = 32 [static], [constexpr]
Definition at line 1620 of file v8-isolate.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-isolate.h
/mnt/V8SourceCode/src/api/api.cc