v8::ExternalMemoryAccounter Class Reference
This class is used to give V8 an indication of the amount of externally allocated memory that is kept alive by JavaScript objects.
#include <v8-external-memory-accounter.h>
Public Member Functions
ExternalMemoryAccounter ()=default
~ExternalMemoryAccounter ()
ExternalMemoryAccounter (ExternalMemoryAccounter &&)
ExternalMemoryAccounter & operator= (ExternalMemoryAccounter &&)
ExternalMemoryAccounter (const ExternalMemoryAccounter &)=delete
ExternalMemoryAccounter & operator= (const ExternalMemoryAccounter &)=delete
void Increase (Isolate *isolate, size_t size)
Reports an increase of size bytes of external memory.
void Update (Isolate *isolate, int64_t delta)
Reports an update of delta bytes of external memory.
void Decrease (Isolate *isolate, size_t size)
Reports an decrease of size bytes of external memory.
Static Public Member Functions
static int64_t GetTotalAmountOfExternalAllocatedMemoryForTesting (const Isolate *isolate)
Returns the amount of external memory registered for isolate.
Detailed Description
This class is used to give V8 an indication of the amount of externally allocated memory that is kept alive by JavaScript objects.
V8 uses this to decide when to perform garbage collections. Registering externally allocated memory will trigger garbage collections more often than it would otherwise in an attempt to garbage collect the JavaScript objects that keep the externally allocated memory alive. Instances of ExternalMemoryAccounter check that the reported external memory is back to 0 on destruction.
Definition at line 23 of file v8-external-memory-accounter.h.
Constructor & Destructor Documentation
ExternalMemoryAccounter() [1/3]
v8::ExternalMemoryAccounter::ExternalMemoryAccounter () [default]
 ExternalMemoryAccounter()
v8::ExternalMemoryAccounter::~ExternalMemoryAccounter ()
Definition at line 12361 of file api.cc.
                                                  {
#ifdef V8_ENABLE_MEMORY_ACCOUNTING_CHECKS
  DCHECK_EQ(amount_of_external_memory_, 0U);
#endif
}
References DCHECK_EQ, and v8::base::internal::U.
ExternalMemoryAccounter() [2/3]
v8::ExternalMemoryAccounter::ExternalMemoryAccounter (ExternalMemoryAccounter && other)
Definition at line 12367 of file api.cc.
                                     {
#if V8_ENABLE_MEMORY_ACCOUNTING_CHECKS
  amount_of_external_memory_ =
      std::exchange(other.amount_of_external_memory_, 0U);
  isolate_ = std::exchange(other.isolate_, nullptr);
#endif
}
References v8::base::internal::U.
ExternalMemoryAccounter() [3/3]
v8::ExternalMemoryAccounter::ExternalMemoryAccounter (const ExternalMemoryAccounter &) [delete]
Member Function Documentation
Decrease()
void v8::ExternalMemoryAccounter::Decrease (Isolate * isolate, size_t size)
Reports an decrease of size bytes of external memory.
Definition at line 12410 of file api.cc.
                                                                    {
  internal::DisallowGarbageCollection no_gc;
  if (size == 0) {
    return;
  }
#ifdef V8_ENABLE_MEMORY_ACCOUNTING_CHECKS
  DCHECK_EQ(isolate, isolate_);
  DCHECK_GE(amount_of_external_memory_, size);
  amount_of_external_memory_ -= size;
#endif
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i_isolate->heap()->UpdateExternalMemory(-static_cast<int64_t>(size));
}
References DCHECK_EQ, DCHECK_GE, v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::Heap::UpdateExternalMemory().
Referenced by v8::internal::ArrayBufferSweeper::DecrementExternalMemoryCounters().
GetTotalAmountOfExternalAllocatedMemoryForTesting()
int64_t v8::ExternalMemoryAccounter::GetTotalAmountOfExternalAllocatedMemoryForTesting (const Isolate * isolate) [static]
Returns the amount of external memory registered for isolate.
Definition at line 12425 of file api.cc.
                            {
  const i::Isolate* i_isolate = reinterpret_cast<const i::Isolate*>(isolate);
  return i_isolate->heap()->external_memory();
}
References v8::internal::Heap::external_memory(), and v8::internal::Isolate::heap().
Increase()
void v8::ExternalMemoryAccounter::Increase (Isolate * isolate, size_t size)
Reports an increase of size bytes of external memory.
Definition at line 12390 of file api.cc.
                                                                    {
#ifdef V8_ENABLE_MEMORY_ACCOUNTING_CHECKS
  DCHECK(isolate == isolate_ || isolate_ == nullptr);
  isolate_ = isolate;
  amount_of_external_memory_ += size;
#endif
  isolate->AdjustAmountOfExternalAllocatedMemoryImpl(
      static_cast<int64_t>(size));
}
References v8::Isolate::AdjustAmountOfExternalAllocatedMemoryImpl(), DCHECK, and size().
Referenced by v8::internal::Managed< CppType >::From(), v8::internal::TrustedManaged< CppType >::From(), and v8::internal::ArrayBufferSweeper::IncrementExternalMemoryCounters().
operator=() [1/2]
ExternalMemoryAccounter& v8::ExternalMemoryAccounter::operator= (const ExternalMemoryAccounter &) [delete]
operator=() [2/2]
ExternalMemoryAccounter & v8::ExternalMemoryAccounter::operator= (ExternalMemoryAccounter && other)
Definition at line 12376 of file api.cc.
                                     {
#if V8_ENABLE_MEMORY_ACCOUNTING_CHECKS
  if (this == &other) {
    return *this;
  }
  DCHECK_EQ(amount_of_external_memory_, 0U);
  amount_of_external_memory_ =
      std::exchange(other.amount_of_external_memory_, 0U);
  isolate_ = std::exchange(other.isolate_, nullptr);
#endif
  return *this;
}
References DCHECK_EQ, and v8::base::internal::U.
Update()
void v8::ExternalMemoryAccounter::Update (Isolate * isolate, int64_t delta)
Reports an update of delta bytes of external memory.
Definition at line 12400 of file api.cc.
                                                                    {
#ifdef V8_ENABLE_MEMORY_ACCOUNTING_CHECKS
  DCHECK(isolate == isolate_ || isolate_ == nullptr);
  DCHECK_GE(static_cast<int64_t>(amount_of_external_memory_), -delta);
  isolate_ = isolate;
  amount_of_external_memory_ += delta;
#endif
  isolate->AdjustAmountOfExternalAllocatedMemoryImpl(delta);
}
References v8::Isolate::AdjustAmountOfExternalAllocatedMemoryImpl(), DCHECK, and DCHECK_GE.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-external-memory-accounter.h
/mnt/V8SourceCode/src/api/api.cc