v8::internal::torque::ExternConstant Class Reference
#include <declarable.h>
Private Member Functions
ExternConstant (Identifier *name, const Type *type, std::string value)
Friends
class Declarations
Additional Inherited Members
Detailed Description
Definition at line 283 of file declarable.h.
Constructor & Destructor Documentation
ExternConstant()
v8::internal::torque::ExternConstant::ExternConstant (Identifier * name, const Type * type, std::string value) [inline], [explicit], [private]
Definition at line 289 of file declarable.h.
      : Value(Declarable::kExternConstant, type, name) {
    set_value(VisitResult(type, std::move(value)));
  }
References v8::internal::torque::Value::set_value(), v8::internal::torque::Value::type(), and v8::internal::torque::Value::value().
Friends And Related Function Documentation
Declarations
friend class Declarations [friend]
Definition at line 288 of file declarable.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h