v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl Class Reference
Static Public Member Functions
static v8::StartupData CreateSnapshotBlob (const SnapshotData *startup_snapshot_in, const SnapshotData *read_only_snapshot_in, const SnapshotData *shared_heap_snapshot_in, const std::vector< SnapshotData * > &context_snapshots_in, bool can_be_rehashed)
static uint32_t ExtractNumContexts (const v8::StartupData *data)
static uint32_t ExtractContextOffset (const v8::StartupData *data, uint32_t index)
static base::Vector< const uint8_t > ExtractStartupData (const v8::StartupData *data)
static base::Vector< const uint8_t > ExtractReadOnlyData (const v8::StartupData *data)
static base::Vector< const uint8_t > ExtractSharedHeapData (const v8::StartupData *data)
static base::Vector< const uint8_t > ExtractContextData (const v8::StartupData *data, uint32_t index)
static uint32_t GetHeaderValue (const v8::StartupData *data, uint32_t offset)
static void SetHeaderValue (char *data, uint32_t offset, uint32_t value)
static void CheckVersion (const v8::StartupData *data)
static base::Vector< const uint8_t > ChecksummedContent (const v8::StartupData *data)
static uint32_t StartupSnapshotOffset (int num_contexts)
static uint32_t ContextSnapshotOffsetOffset (int index)
Static Public Attributes
static const uint32_t kNumberOfContextsOffset = 0
static const uint32_t kRehashabilityOffset
static const uint32_t kChecksumOffset = kRehashabilityOffset + kUInt32Size
static const uint32_t kReadOnlySnapshotChecksumOffset
static const uint32_t kVersionStringOffset
static const uint32_t kVersionStringLength = 64
static const uint32_t kReadOnlyOffsetOffset
static const uint32_t kSharedHeapOffsetOffset
static const uint32_t kFirstContextOffsetOffset
Detailed Description
Definition at line 39 of file snapshot.cc.
Member Function Documentation
ChecksummedContent()
static base::Vector<const uint8_t> v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::ChecksummedContent (const v8::StartupData * data) [inline], [static]
Definition at line 108 of file snapshot.cc.
                                 {
    // The hashed region is everything but the header slots up-to-and-including
    // the checksum slot itself.
    // TODO(jgruber): We currently exclude #contexts and rehashability. This
    // seems arbitrary and I think we could shuffle header slot order around to
    // include them, just for consistency.
    static_assert(kReadOnlySnapshotChecksumOffset ==
                  kChecksumOffset + kUInt32Size);
    const uint32_t kChecksumStart = kReadOnlySnapshotChecksumOffset;
    return base::Vector<const uint8_t>(
        reinterpret_cast<const uint8_t*>(data->data + kChecksumStart),
        data->raw_size - kChecksumStart);
  }
References v8::StartupData::data, v8::internal::kUInt32Size, and v8::StartupData::raw_size.
CheckVersion()
void v8::internal::SnapshotImpl::CheckVersion (const v8::StartupData * data) [static]
Definition at line 735 of file snapshot.cc.
                                                         {
  if (!Snapshot::VersionIsValid(data)) {
    char version[kVersionStringLength];
    memset(version, 0, kVersionStringLength);
    CHECK_LT(kVersionStringOffset + kVersionStringLength,
             static_cast<uint32_t>(data->raw_size));
    Version::GetString(base::Vector<char>(version, kVersionStringLength));
    FATAL(
        "Version mismatch between V8 binary and snapshot.\n"
        "# V8 binary version: %.*s\n"
        "# Snapshot version: %.*s\n"
        "# The snapshot consists of %d bytes and contains %d context(s).",
        kVersionStringLength, version, kVersionStringLength,
        data->data + kVersionStringOffset, data->raw_size,
        ExtractNumContexts(data));
  }
}
References CHECK_LT, v8::StartupData::data, FATAL, v8::internal::Version::GetString(), v8::StartupData::raw_size, and v8::internal::Snapshot::VersionIsValid().
ContextSnapshotOffsetOffset()
static uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::ContextSnapshotOffsetOffset (int index) [inline], [static]
Definition at line 128 of file snapshot.cc.
                                                         {
    return kFirstContextOffsetOffset + index * kInt32Size;
  }
References v8::internal::index, and v8::internal::kInt32Size.
CreateSnapshotBlob()
v8::StartupData v8::internal::SnapshotImpl::CreateSnapshotBlob (const SnapshotData * startup_snapshot_in, const SnapshotData * read_only_snapshot_in, const SnapshotData * shared_heap_snapshot_in, const std::vector< SnapshotData * > & context_snapshots_in, bool can_be_rehashed) [static]
Definition at line 487 of file snapshot.cc.
                          {
  TRACE_EVENT0("v8", "V8.SnapshotCompress");
  // Have these separate from snapshot_in for compression, since we need to
  // access the compressed data as well as the uncompressed reservations.
  const SnapshotData* startup_snapshot;
  const SnapshotData* read_only_snapshot;
  const SnapshotData* shared_heap_snapshot;
  const std::vector<SnapshotData*>* context_snapshots;
#ifdef V8_SNAPSHOT_COMPRESSION
  SnapshotData startup_compressed(
      SnapshotCompression::Compress(startup_snapshot_in));
  SnapshotData read_only_compressed(
      SnapshotCompression::Compress(read_only_snapshot_in));
  SnapshotData shared_heap_compressed(
      SnapshotCompression::Compress(shared_heap_snapshot_in));
  startup_snapshot = &startup_compressed;
  read_only_snapshot = &read_only_compressed;
  shared_heap_snapshot = &shared_heap_compressed;
  std::vector<SnapshotData> context_snapshots_compressed;
  context_snapshots_compressed.reserve(context_snapshots_in.size());
  std::vector<SnapshotData*> context_snapshots_compressed_ptrs;
  for (unsigned int i = 0; i < context_snapshots_in.size(); ++i) {
    context_snapshots_compressed.push_back(
        SnapshotCompression::Compress(context_snapshots_in[i]));
    context_snapshots_compressed_ptrs.push_back(
        &context_snapshots_compressed[i]);
  }
  context_snapshots = &context_snapshots_compressed_ptrs;
#else
  startup_snapshot = startup_snapshot_in;
  read_only_snapshot = read_only_snapshot_in;
  shared_heap_snapshot = shared_heap_snapshot_in;
  context_snapshots = &context_snapshots_in;
#endif
  uint32_t num_contexts = static_cast<uint32_t>(context_snapshots->size());
  uint32_t startup_snapshot_offset =
      SnapshotImpl::StartupSnapshotOffset(num_contexts);
  uint32_t total_length = startup_snapshot_offset;
  total_length += static_cast<uint32_t>(startup_snapshot->RawData().length());
  total_length += static_cast<uint32_t>(read_only_snapshot->RawData().length());
  total_length +=
      static_cast<uint32_t>(shared_heap_snapshot->RawData().length());
  for (const auto context_snapshot : *context_snapshots) {
    total_length += static_cast<uint32_t>(context_snapshot->RawData().length());
  }
  char* data = new char[total_length];
  // Zero out pre-payload data. Part of that is only used for padding.
  memset(data, 0, SnapshotImpl::StartupSnapshotOffset(num_contexts));
  SnapshotImpl::SetHeaderValue(data, SnapshotImpl::kNumberOfContextsOffset,
                               num_contexts);
  SnapshotImpl::SetHeaderValue(data, SnapshotImpl::kRehashabilityOffset,
                               can_be_rehashed ? 1 : 0);
  // Write version string into snapshot data.
  memset(data + SnapshotImpl::kVersionStringOffset, 0,
         SnapshotImpl::kVersionStringLength);
  Version::GetString(
      base::Vector<char>(data + SnapshotImpl::kVersionStringOffset,
                         SnapshotImpl::kVersionStringLength));
  // Startup snapshot (isolate-specific data).
  uint32_t payload_offset = startup_snapshot_offset;
  uint32_t payload_length =
      static_cast<uint32_t>(startup_snapshot->RawData().length());
  CopyBytes(data + payload_offset,
            reinterpret_cast<const char*>(startup_snapshot->RawData().begin()),
            payload_length);
  if (v8_flags.serialization_statistics) {
    // These prints must match the regexp in test/memory/Memory.json
    PrintF("Snapshot blob consists of:\n");
    PrintF("%10d bytes for startup\n", payload_length);
  }
  payload_offset += payload_length;
  // Read-only.
  SnapshotImpl::SetHeaderValue(data, SnapshotImpl::kReadOnlyOffsetOffset,
                               payload_offset);
  payload_length = read_only_snapshot->RawData().length();
  CopyBytes(
      data + payload_offset,
      reinterpret_cast<const char*>(read_only_snapshot->RawData().begin()),
      payload_length);
  SnapshotImpl::SetHeaderValue(
      data, SnapshotImpl::kReadOnlySnapshotChecksumOffset,
      Checksum(base::VectorOf(
          reinterpret_cast<const uint8_t*>(data + payload_offset),
          payload_length)));
  if (v8_flags.serialization_statistics) {
    // These prints must match the regexp in test/memory/Memory.json
    PrintF("%10d bytes for read-only\n", payload_length);
  }
  payload_offset += payload_length;
  // Shared heap.
  SnapshotImpl::SetHeaderValue(data, SnapshotImpl::kSharedHeapOffsetOffset,
                               payload_offset);
  payload_length = shared_heap_snapshot->RawData().length();
  CopyBytes(
      data + payload_offset,
      reinterpret_cast<const char*>(shared_heap_snapshot->RawData().begin()),
      payload_length);
  if (v8_flags.serialization_statistics) {
    // These prints must match the regexp in test/memory/Memory.json
    PrintF("%10d bytes for shared heap\n", payload_length);
  }
  payload_offset += payload_length;
  // Context snapshots (context-specific data).
  for (uint32_t i = 0; i < num_contexts; i++) {
    SnapshotImpl::SetHeaderValue(
        data, SnapshotImpl::ContextSnapshotOffsetOffset(i), payload_offset);
    SnapshotData* context_snapshot = (*context_snapshots)[i];
    payload_length = context_snapshot->RawData().length();
    CopyBytes(
        data + payload_offset,
        reinterpret_cast<const char*>(context_snapshot->RawData().begin()),
        payload_length);
    if (v8_flags.serialization_statistics) {
      // These prints must match the regexp in test/memory/Memory.json
      PrintF("%10d bytes for context #%d\n", payload_length, i);
    }
    payload_offset += payload_length;
  }
  if (v8_flags.serialization_statistics) PrintF("\n");
  DCHECK_EQ(total_length, payload_offset);
  v8::StartupData result = {data, static_cast<int>(total_length)};
  SnapshotImpl::SetHeaderValue(
      data, SnapshotImpl::kChecksumOffset,
      Checksum(SnapshotImpl::ChecksummedContent(&result)));
  return result;
}
References v8::base::Vector< T >::begin(), v8::internal::Checksum(), v8::internal::SnapshotCompression::Compress(), v8::internal::CopyBytes(), DCHECK_EQ, v8::internal::Version::GetString(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::Vector< T >::length(), v8::internal::PrintF(), v8::internal::SnapshotData::RawData(), v8::base::internal::result, TRACE_EVENT0, v8::internal::v8_flags, and v8::base::VectorOf().
ExtractContextData()
base::Vector< const uint8_t > v8::internal::SnapshotImpl::ExtractContextData (const v8::StartupData * data, uint32_t index) [static]
Definition at line 715 of file snapshot.cc.
                                               {
  uint32_t num_contexts = ExtractNumContexts(data);
  CHECK_LT(index, num_contexts);
  uint32_t context_offset = ExtractContextOffset(data, index);
  uint32_t next_context_offset;
  if (index == num_contexts - 1) {
    next_context_offset = data->raw_size;
  } else {
    next_context_offset = ExtractContextOffset(data, index + 1);
    CHECK_LT(next_context_offset, data->raw_size);
  }
  const uint8_t* context_data =
      reinterpret_cast<const uint8_t*>(data->data + context_offset);
  uint32_t context_length = next_context_offset - context_offset;
  return base::Vector<const uint8_t>(context_data, context_length);
}
References CHECK_LT, v8::StartupData::data, v8::internal::index, and v8::StartupData::raw_size.
ExtractContextOffset()
uint32_t v8::internal::SnapshotImpl::ExtractContextOffset (const v8::StartupData * data, uint32_t index) [static]
Definition at line 653 of file snapshot.cc.
                                                            {
  // Extract the offset of the context at a given index from the StartupData,
  // and check that it is within bounds.
  uint32_t context_offset =
      GetHeaderValue(data, ContextSnapshotOffsetOffset(index));
  CHECK_LT(context_offset, static_cast<uint32_t>(data->raw_size));
  return context_offset;
}
References CHECK_LT, v8::internal::index, and v8::StartupData::raw_size.
ExtractNumContexts()
uint32_t v8::internal::SnapshotImpl::ExtractNumContexts (const v8::StartupData * data) [static]
Definition at line 630 of file snapshot.cc.
                                                                   {
  return GetHeaderValue(data, kNumberOfContextsOffset);
}
ExtractReadOnlyData()
base::Vector< const uint8_t > v8::internal::SnapshotImpl::ExtractReadOnlyData (const v8::StartupData * data) [static]
Definition at line 699 of file snapshot.cc.
                               {
  DCHECK(Snapshot::SnapshotIsValid(data));
  return ExtractData(data, GetHeaderValue(data, kReadOnlyOffsetOffset),
                     GetHeaderValue(data, kSharedHeapOffsetOffset));
}
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{snapshot.cc}::ExtractData().
ExtractSharedHeapData()
base::Vector< const uint8_t > v8::internal::SnapshotImpl::ExtractSharedHeapData (const v8::StartupData * data) [static]
Definition at line 707 of file snapshot.cc.
                               {
  DCHECK(Snapshot::SnapshotIsValid(data));
  return ExtractData(data, GetHeaderValue(data, kSharedHeapOffsetOffset),
                     GetHeaderValue(data, ContextSnapshotOffsetOffset(0)));
}
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{snapshot.cc}::ExtractData().
ExtractStartupData()
base::Vector< const uint8_t > v8::internal::SnapshotImpl::ExtractStartupData (const v8::StartupData * data) [static]
Definition at line 690 of file snapshot.cc.
                               {
  DCHECK(Snapshot::SnapshotIsValid(data));
  uint32_t num_contexts = ExtractNumContexts(data);
  return ExtractData(data, StartupSnapshotOffset(num_contexts),
                     GetHeaderValue(data, kReadOnlyOffsetOffset));
}
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{snapshot.cc}::ExtractData().
GetHeaderValue()
static uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::GetHeaderValue (const v8::StartupData * data, uint32_t offset) [inline], [static]
Definition at line 60 of file snapshot.cc.
                                                                             {
    DCHECK_NOT_NULL(data);
    DCHECK_LT(offset, static_cast<uint32_t>(data->raw_size));
    return base::ReadLittleEndianValue<uint32_t>(
        reinterpret_cast<Address>(data->data) + offset);
  }
References v8::StartupData::data, DCHECK_LT, DCHECK_NOT_NULL, and v8::StartupData::raw_size.
SetHeaderValue()
static void v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::SetHeaderValue (char * data, uint32_t offset, uint32_t value) [inline], [static]
Definition at line 66 of file snapshot.cc.
                                                                          {
    base::WriteLittleEndianValue(reinterpret_cast<Address>(data) + offset,
                                 value);
  }
References v8::internal::value, and v8::base::WriteLittleEndianValue().
StartupSnapshotOffset()
static uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::StartupSnapshotOffset (int num_contexts) [inline], [static]
Definition at line 123 of file snapshot.cc.
                                                          {
    return POINTER_SIZE_ALIGN(kFirstContextOffsetOffset +
                              num_contexts * kInt32Size);
  }
References v8::internal::kInt32Size, and POINTER_SIZE_ALIGN.
Member Data Documentation
kChecksumOffset
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kChecksumOffset = kRehashabilityOffset + kUInt32Size [static]
Definition at line 95 of file snapshot.cc.
kFirstContextOffsetOffset
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kFirstContextOffsetOffset [static]
Initial value:
=
      kSharedHeapOffsetOffset + kUInt32Size
Definition at line 105 of file snapshot.cc.
kNumberOfContextsOffset
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kNumberOfContextsOffset = 0 [static]
Definition at line 91 of file snapshot.cc.
kReadOnlyOffsetOffset
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kReadOnlyOffsetOffset [static]
Initial value:
=
      kVersionStringOffset + kVersionStringLength
Definition at line 101 of file snapshot.cc.
kReadOnlySnapshotChecksumOffset
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kReadOnlySnapshotChecksumOffset [static]
Initial value:
=
      kChecksumOffset + kUInt32Size
Definition at line 96 of file snapshot.cc.
kRehashabilityOffset
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kRehashabilityOffset [static]
Initial value:
=
      kNumberOfContextsOffset + kUInt32Size
Definition at line 93 of file snapshot.cc.
kSharedHeapOffsetOffset
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kSharedHeapOffsetOffset [static]
Initial value:
=
      kReadOnlyOffsetOffset + kUInt32Size
Definition at line 103 of file snapshot.cc.
kVersionStringLength
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kVersionStringLength = 64 [static]
Definition at line 100 of file snapshot.cc.
kVersionStringOffset
const uint32_t v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::kVersionStringOffset [static]
Initial value:
=
      kReadOnlySnapshotChecksumOffset + kUInt32Size
Definition at line 98 of file snapshot.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/snapshot.cc