v8::internal::compiler::Frame Class Reference
#include <frame.h>
Public Member Functions
Frame (int fixed_frame_size_in_slots, Zone *zone)
Frame (const Frame &)=delete
Frame & operator= (const Frame &)=delete
int GetTotalFrameSlotCount () const
int GetFixedSlotCount () const
int GetSpillSlotCount () const
int GetReturnSlotCount () const
void SetAllocatedRegisters (BitVector *regs)
void SetAllocatedDoubleRegisters (BitVector *regs)
bool DidAllocateDoubleRegisters () const
void AlignSavedCalleeRegisterSlots (int alignment=kDoubleSize)
void AllocateSavedCalleeRegisterSlots (int count)
int AllocateSpillSlot (int width, int alignment=0, bool is_tagged=false)
void EnsureReturnSlots (int count)
void AlignFrame (int alignment=kDoubleSize)
int ReserveSpillSlots (size_t slot_count)
const GrowableBitVector & tagged_slots () const
bool invalidates_sp () const
void set_invalidates_sp ()
Private Attributes
int fixed_slot_count_
int spill_slot_count_ = 0
int return_slot_count_ = 0
AlignedSlotAllocator slot_allocator_
BitVector * allocated_registers_
BitVector * allocated_double_registers_
Zone * zone_
GrowableBitVector tagged_slots_bits_
bool invalidates_sp_ = false
Detailed Description
Definition at line 91 of file frame.h.
Constructor & Destructor Documentation
Frame() [1/2]
v8::internal::compiler::Frame::Frame (int fixed_frame_size_in_slots, Zone * zone) [explicit]
Definition at line 11 of file frame.cc.
    : fixed_slot_count_(fixed_frame_size_in_slots),
      allocated_registers_(nullptr),
      allocated_double_registers_(nullptr),
      zone_(zone) {
  slot_allocator_.AllocateUnaligned(fixed_frame_size_in_slots);
}
References v8::internal::AlignedSlotAllocator::AllocateUnaligned(), and slot_allocator_.
Frame() [2/2]
v8::internal::compiler::Frame::Frame (const Frame &) [delete]
Member Function Documentation
AlignFrame()
void v8::internal::compiler::Frame::AlignFrame (int alignment = kDoubleSize)
Definition at line 19 of file frame.cc.
                                    {
#if DEBUG
  spill_slots_finished_ = true;
  frame_aligned_ = true;
#endif
  // In the calculations below we assume that alignment is a power of 2.
  DCHECK(base::bits::IsPowerOfTwo(alignment));
  int alignment_in_slots = AlignedSlotAllocator::NumSlotsForWidth(alignment);
  // We have to align return slots separately, because they are claimed
  // separately on the stack.
  const int mask = alignment_in_slots - 1;
  int return_delta = alignment_in_slots - (return_slot_count_ & mask);
  if (return_delta != alignment_in_slots) {
    return_slot_count_ += return_delta;
  }
  int delta = alignment_in_slots - (slot_allocator_.Size() & mask);
  if (delta != alignment_in_slots) {
    slot_allocator_.Align(alignment_in_slots);
    if (spill_slot_count_ != 0) {
      spill_slot_count_ += delta;
    }
  }
}
References v8::internal::AlignedSlotAllocator::Align(), v8::internal::DCHECK(), v8::base::bits::IsPowerOfTwo(), v8::internal::AlignedSlotAllocator::NumSlotsForWidth(), return_slot_count_, v8::internal::AlignedSlotAllocator::Size(), slot_allocator_, and spill_slot_count_.
AlignSavedCalleeRegisterSlots()
void v8::internal::compiler::Frame::AlignSavedCalleeRegisterSlots (int alignment = kDoubleSize) [inline]
Definition at line 118 of file frame.h.
                                                                  {
    DCHECK(!frame_aligned_);
#if DEBUG
    spill_slots_finished_ = true;
#endif
    DCHECK(base::bits::IsPowerOfTwo(alignment));
    DCHECK_LE(alignment, kSimd128Size);
    int alignment_in_slots = AlignedSlotAllocator::NumSlotsForWidth(alignment);
    int padding = slot_allocator_.Align(alignment_in_slots);
    spill_slot_count_ += padding;
  }
References v8::internal::DCHECK(), DCHECK_LE, v8::base::bits::IsPowerOfTwo(), v8::internal::kSimd128Size, and v8::internal::AlignedSlotAllocator::NumSlotsForWidth().
Referenced by v8::internal::compiler::CodeGenerator::FinishFrame().
AllocateSavedCalleeRegisterSlots()
void v8::internal::compiler::Frame::AllocateSavedCalleeRegisterSlots (int count) [inline]
Definition at line 130 of file frame.h.
                                                   {
    DCHECK(!frame_aligned_);
#if DEBUG
    spill_slots_finished_ = true;
#endif
    slot_allocator_.AllocateUnaligned(count);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::CodeGenerator::FinishFrame().
AllocateSpillSlot()
int v8::internal::compiler::Frame::AllocateSpillSlot (int width, int alignment = 0, bool is_tagged = false) [inline]
Definition at line 138 of file frame.h.
                                                                              {
    DCHECK_EQ(GetTotalFrameSlotCount(),
              fixed_slot_count_ + spill_slot_count_ + return_slot_count_);
    DCHECK_IMPLIES(is_tagged, width == sizeof(uintptr_t));
    DCHECK_IMPLIES(is_tagged, alignment == sizeof(uintptr_t));
    // Never allocate spill slots after the callee-saved slots are defined.
    DCHECK(!spill_slots_finished_);
    DCHECK(!frame_aligned_);
    int actual_width = std::max({width, AlignedSlotAllocator::kSlotSize});
    int actual_alignment =
        std::max({alignment, AlignedSlotAllocator::kSlotSize});
    int slots = AlignedSlotAllocator::NumSlotsForWidth(actual_width);
    int old_end = slot_allocator_.Size();
    int slot;
    if (actual_width == actual_alignment) {
      // Simple allocation, alignment equal to width.
      slot = slot_allocator_.Allocate(slots);
    } else {
      // Complex allocation, alignment different from width.
      if (actual_alignment > AlignedSlotAllocator::kSlotSize) {
        // Alignment required.
        int alignment_in_slots =
            AlignedSlotAllocator::NumSlotsForWidth(actual_alignment);
        slot_allocator_.Align(alignment_in_slots);
      }
      slot = slot_allocator_.AllocateUnaligned(slots);
    }
    int end = slot_allocator_.Size();
    spill_slot_count_ += end - old_end;
    int result_slot = slot + slots - 1;
    if (is_tagged) tagged_slots_bits_.Add(result_slot, zone_);
    return result_slot;
  }
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::end(), v8::internal::AlignedSlotAllocator::kSlotSize, and v8::internal::AlignedSlotAllocator::NumSlotsForWidth().
Referenced by v8::internal::compiler::OperandAssigner::AssignSpillSlots(), and v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore().
DidAllocateDoubleRegisters()
bool v8::internal::compiler::Frame::DidAllocateDoubleRegisters () const [inline]
Definition at line 114 of file frame.h.
                                          {
    return !allocated_double_registers_->IsEmpty();
  }
EnsureReturnSlots()
void v8::internal::compiler::Frame::EnsureReturnSlots (int count) [inline]
Definition at line 173 of file frame.h.
                                    {
    DCHECK(!frame_aligned_);
    return_slot_count_ = std::max(return_slot_count_, count);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
GetFixedSlotCount()
int v8::internal::compiler::Frame::GetFixedSlotCount () const [inline]
Definition at line 100 of file frame.h.
{ return fixed_slot_count_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), and v8::internal::compiler::CodeGenerator::RecordSafepoint().
GetReturnSlotCount()
int v8::internal::compiler::Frame::GetReturnSlotCount () const [inline]
Definition at line 102 of file frame.h.
{ return return_slot_count_; }
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), and v8::internal::compiler::CodeGenerator::AssembleReturn().
GetSpillSlotCount()
int v8::internal::compiler::Frame::GetSpillSlotCount () const [inline]
Definition at line 101 of file frame.h.
{ return spill_slot_count_; }
GetTotalFrameSlotCount()
int v8::internal::compiler::Frame::GetTotalFrameSlotCount () const [inline]
Definition at line 97 of file frame.h.
                                            {
    return slot_allocator_.Size() + return_slot_count_;
  }
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::CodeGenerator::GetStackCheckOffset(), v8::internal::compiler::CodeGenerator::Pop(), and v8::internal::compiler::CodeGenerator::Push().
invalidates_sp()
bool v8::internal::compiler::Frame::invalidates_sp () const [inline]
Definition at line 190 of file frame.h.
{ return invalidates_sp_; }
operator=()
Frame& v8::internal::compiler::Frame::operator= (const Frame &) [delete]
ReserveSpillSlots()
int v8::internal::compiler::Frame::ReserveSpillSlots (size_t slot_count) [inline]
Definition at line 180 of file frame.h.
                                           {
    DCHECK_EQ(0, spill_slot_count_);
    DCHECK(!frame_aligned_);
    spill_slot_count_ += static_cast<int>(slot_count);
    slot_allocator_.AllocateUnaligned(static_cast<int>(slot_count));
    return slot_allocator_.Size() - 1;
  }
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::compiler::OsrHelper::SetupFrame().
set_invalidates_sp()
void v8::internal::compiler::Frame::set_invalidates_sp () [inline]
Definition at line 191 of file frame.h.
{ invalidates_sp_ = true; }
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
SetAllocatedDoubleRegisters()
void v8::internal::compiler::Frame::SetAllocatedDoubleRegisters (BitVector * regs) [inline]
Definition at line 109 of file frame.h.
                                                    {
    DCHECK_NULL(allocated_double_registers_);
    allocated_double_registers_ = regs;
  }
References DCHECK_NULL.
Referenced by v8::internal::compiler::RegisterAllocationData::RegisterAllocationData().
SetAllocatedRegisters()
void v8::internal::compiler::Frame::SetAllocatedRegisters (BitVector * regs) [inline]
Definition at line 104 of file frame.h.
                                              {
    DCHECK_NULL(allocated_registers_);
    allocated_registers_ = regs;
  }
References DCHECK_NULL.
Referenced by v8::internal::compiler::RegisterAllocationData::RegisterAllocationData().
tagged_slots()
const GrowableBitVector& v8::internal::compiler::Frame::tagged_slots () const [inline]
Definition at line 188 of file frame.h.
{ return tagged_slots_bits_; }
Member Data Documentation
allocated_double_registers_
BitVector* v8::internal::compiler::Frame::allocated_double_registers_ [private]
Definition at line 201 of file frame.h.
allocated_registers_
BitVector* v8::internal::compiler::Frame::allocated_registers_ [private]
Definition at line 200 of file frame.h.
fixed_slot_count_
int v8::internal::compiler::Frame::fixed_slot_count_ [private]
Definition at line 194 of file frame.h.
invalidates_sp_
bool v8::internal::compiler::Frame::invalidates_sp_ = false [private]
Definition at line 204 of file frame.h.
return_slot_count_
int v8::internal::compiler::Frame::return_slot_count_ = 0 [private]
Definition at line 198 of file frame.h.
Referenced by AlignFrame().
slot_allocator_
AlignedSlotAllocator v8::internal::compiler::Frame::slot_allocator_ [private]
Definition at line 199 of file frame.h.
Referenced by AlignFrame(), and Frame().
spill_slot_count_
int v8::internal::compiler::Frame::spill_slot_count_ = 0 [private]
Definition at line 195 of file frame.h.
Referenced by AlignFrame().
tagged_slots_bits_
GrowableBitVector v8::internal::compiler::Frame::tagged_slots_bits_ [private]
Definition at line 203 of file frame.h.
zone_
Zone* v8::internal::compiler::Frame::zone_ [private]
Definition at line 202 of file frame.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/frame.h
/mnt/V8SourceCode/src/compiler/frame.cc