v8::internal::VariableDeclarationParsingScope< Types > Class Template Reference
#include <expression-scope.h>
Public Types
using ParserT = typename Types::Impl
using ExpressionScopeT = ExpressionScope< Types >
using ScopeType = typename ExpressionScopeT::ScopeType
Public Member Functions
VariableDeclarationParsingScope (ParserT *parser, VariableMode mode, ZonePtrList< const AstRawString > *names)
VariableDeclarationParsingScope (const VariableDeclarationParsingScope &)=delete
VariableDeclarationParsingScope & operator= (const VariableDeclarationParsingScope &)=delete
Variable * Declare (const AstRawString *name, int pos)
Private Attributes
VariableMode mode_
ZonePtrList< const AstRawString > * names_
Static Private Attributes
static const int kMaxNumFunctionLocals = (1 << 23) - 1
Additional Inherited Members
Detailed Description
template<typename Types>
class v8::internal::VariableDeclarationParsingScope< Types >
Definition at line 352 of file expression-scope.h.
Member Typedef Documentation
ExpressionScopeT
template<typename Types >
using v8::internal::VariableDeclarationParsingScope< Types >::ExpressionScopeT = ExpressionScope<Types>
Definition at line 355 of file expression-scope.h.
ParserT
template<typename Types >
using v8::internal::VariableDeclarationParsingScope< Types >::ParserT = typename Types::Impl
Definition at line 354 of file expression-scope.h.
ScopeType
template<typename Types >
using v8::internal::VariableDeclarationParsingScope< Types >::ScopeType = typename ExpressionScopeT::ScopeType
Definition at line 356 of file expression-scope.h.
Constructor & Destructor Documentation
VariableDeclarationParsingScope() [1/2]
template<typename Types >
v8::internal::VariableDeclarationParsingScope< Types >::VariableDeclarationParsingScope (ParserT * parser, VariableMode mode, ZonePtrList< const AstRawString > * names) [inline]
Definition at line 358 of file expression-scope.h.
      : ExpressionScopeT(parser, IsLexicalVariableMode(mode)
                                     ? ExpressionScopeT::kLexicalDeclaration
                                     : ExpressionScopeT::kVarDeclaration),
        mode_(mode),
        names_(names) {}
VariableDeclarationParsingScope() [2/2]
template<typename Types >
v8::internal::VariableDeclarationParsingScope< Types >::VariableDeclarationParsingScope (const VariableDeclarationParsingScope< Types > &) [delete]
Member Function Documentation
Declare()
template<typename Types >
Variable* v8::internal::VariableDeclarationParsingScope< Types >::Declare (const AstRawString * name, int pos) [inline]
Definition at line 371 of file expression-scope.h.
                                                       {
    VariableKind kind = NORMAL_VARIABLE;
    bool was_added;
    Variable* var = this->parser()->DeclareVariable(
        name, kind, mode_, Variable::DefaultInitializationFlag(mode_),
        this->parser()->scope(), &was_added, pos);
    if (was_added &&
        this->parser()->scope()->num_var() > kMaxNumFunctionLocals) {
      this->parser()->ReportMessage(MessageTemplate::kTooManyVariables);
    }
    if (names_) names_->Add(name, this->parser()->zone());
    if (this->IsLexicalDeclaration()) {
      if (this->parser()->IsLet(name)) {
        this->parser()->ReportMessageAt(
            Scanner::Location(pos, pos + name->length()),
            MessageTemplate::kLetInLexicalBinding);
      }
    } else {
      if (this->parser()->loop_nesting_depth() > 0) {
        // Due to hoisting, the value of a 'var'-declared variable may actually
        // change even if the code contains only the "initial" assignment,
        // namely when that assignment occurs inside a loop. For example:
        //
        // let i = 10;
        // do { var x = i } while (i--):
        //
        // Note that non-lexical variables include temporaries, which may also
        // get assigned inside a loop due to the various rewritings that the
        // parser performs.
        //
        // Pessimistically mark all vars in loops as assigned. This
        // overapproximates the actual assigned vars due to unassigned var
        // without initializer, but that's unlikely anyway.
        //
        // This also handles marking of loop variables in for-in and for-of
        // loops, as determined by loop-nesting-depth.
        DCHECK_NOT_NULL(var);
        var->SetMaybeAssigned();
      }
    }
    return var;
  }
References DCHECK_NOT_NULL, v8::internal::Variable::DefaultInitializationFlag(), v8::internal::ExpressionScope< Types >::IsLexicalDeclaration(), v8::internal::VariableDeclarationParsingScope< Types >::kMaxNumFunctionLocals, v8::internal::VariableDeclarationParsingScope< Types >::mode_, v8::internal::name, v8::internal::VariableDeclarationParsingScope< Types >::names_, v8::internal::NORMAL_VARIABLE, v8::internal::ExpressionScope< Types >::parser(), and v8::internal::Variable::SetMaybeAssigned().
operator=()
template<typename Types >
VariableDeclarationParsingScope& v8::internal::VariableDeclarationParsingScope< Types >::operator= (const VariableDeclarationParsingScope< Types > &) [delete]
Member Data Documentation
kMaxNumFunctionLocals
template<typename Types >
const int v8::internal::VariableDeclarationParsingScope< Types >::kMaxNumFunctionLocals = (1 << 23) - 1 [static], [private]
Definition at line 418 of file expression-scope.h.
Referenced by v8::internal::VariableDeclarationParsingScope< Types >::Declare().
mode_
template<typename Types >
VariableMode v8::internal::VariableDeclarationParsingScope< Types >::mode_ [private]
Definition at line 420 of file expression-scope.h.
Referenced by v8::internal::VariableDeclarationParsingScope< Types >::Declare().
names_
template<typename Types >
ZonePtrList<const AstRawString>* v8::internal::VariableDeclarationParsingScope< Types >::names_ [private]
Definition at line 421 of file expression-scope.h.
Referenced by v8::internal::VariableDeclarationParsingScope< Types >::Declare().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/expression-scope.h