v8::ArrayBufferView Class Reference
A base class for an instance of one of `views` over ArrayBuffer, including TypedArrays and DataView (ES6 draft 15.13).
#include <v8-array-buffer.h>
Public Member Functions
Local< ArrayBuffer > Buffer ()
Returns underlying ArrayBuffer.
size_t ByteOffset ()
Byte offset in |Buffer|.
size_t ByteLength ()
Size of a view in bytes.
size_t CopyContents (void *dest, size_t byte_length)
Copy the contents of the ArrayBufferView's buffer to an embedder defined memory without additional overhead that calling ArrayBufferView::Buffer might incur.
v8::MemorySpan< uint8_t > GetContents (v8::MemorySpan< uint8_t > storage)
Returns the contents of the ArrayBufferView's buffer as a MemorySpan.
bool HasBuffer () const
Returns true if ArrayBufferView's backing ArrayBuffer has already been allocated.
Static Public Member Functions
static ArrayBufferView * Cast (Value *value)
Static Public Attributes
static constexpr int kInternalFieldCount
static const int kEmbedderFieldCount = kInternalFieldCount
Private Member Functions
ArrayBufferView ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
A base class for an instance of one of `views` over ArrayBuffer, including TypedArrays and DataView (ES6 draft 15.13).
Definition at line 417 of file v8-array-buffer.h.
Constructor & Destructor Documentation
ArrayBufferView()
v8::ArrayBufferView::ArrayBufferView () [private]
Member Function Documentation
Buffer()
Local< ArrayBuffer > v8::ArrayBufferView::Buffer ()
Returns underlying ArrayBuffer.
Definition at line 9133 of file api.cc.
                                             {
  auto obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  if (i::IsJSDataView(*obj)) {
    i::DirectHandle<i::JSDataView> data_view(i::Cast<i::JSDataView>(*obj),
                                             i_isolate);
    DCHECK(IsJSArrayBuffer(data_view->buffer()));
    return Utils::ToLocal(i::direct_handle(
        i::Cast<i::JSArrayBuffer>(data_view->buffer()), i_isolate));
  } else if (i::IsJSRabGsabDataView(*obj)) {
    i::DirectHandle<i::JSRabGsabDataView> data_view(
        i::Cast<i::JSRabGsabDataView>(*obj), i_isolate);
    DCHECK(IsJSArrayBuffer(data_view->buffer()));
    return Utils::ToLocal(i::direct_handle(
        i::Cast<i::JSArrayBuffer>(data_view->buffer()), i_isolate));
  } else {
    DCHECK(IsJSTypedArray(*obj));
    return Utils::ToLocal(i::Cast<i::JSTypedArray>(*obj)->GetBuffer(i_isolate));
  }
}
References v8::internal::Isolate::Current(), DCHECK, v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
ByteLength()
size_t v8::ArrayBufferView::ByteLength ()
Size of a view in bytes.
Definition at line 9220 of file api.cc.
                                     {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::JSArrayBufferView> obj = *Utils::OpenDirectHandle(this);
  if (obj->IsDetachedOrOutOfBounds()) {
    return 0;
  }
  if (i::IsJSTypedArray(obj)) {
    return i::Cast<i::JSTypedArray>(obj)->GetByteLength();
  }
  if (i::IsJSDataView(obj)) {
    return i::Cast<i::JSDataView>(obj)->byte_length();
  }
  return i::Cast<i::JSRabGsabDataView>(obj)->GetByteLength();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
ByteOffset()
size_t v8::ArrayBufferView::ByteOffset ()
Byte offset in |Buffer|.
Definition at line 9215 of file api.cc.
                                     {
  auto obj = Utils::OpenDirectHandle(this);
  return obj->IsDetachedOrOutOfBounds() ? 0 : obj->byte_offset();
}
References v8::Utils::OpenDirectHandle().
Cast()
static ArrayBufferView* v8::ArrayBufferView::Cast (Value * value) [inline], [static]
Definition at line 459 of file v8-array-buffer.h.
                                                       {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<ArrayBufferView*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::ArrayBufferView::CheckCast (Value * obj) [static], [private]
Definition at line 4083 of file api.cc.
                                             {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSArrayBufferView(obj), "v8::ArrayBufferView::Cast()",
                  "Value is not an ArrayBufferView");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
CopyContents()
size_t v8::ArrayBufferView::CopyContents (void * dest, size_t byte_length)
Copy the contents of the ArrayBufferView's buffer to an embedder defined memory without additional overhead that calling ArrayBufferView::Buffer might incur.
Will write at most min(|byte_length|, ByteLength) bytes starting at ByteOffset of the underlying buffer to the memory starting at |dest|. Returns the number of bytes actually written.
Definition at line 9154 of file api.cc.
                                                                     {
  auto self = Utils::OpenDirectHandle(this);
  size_t bytes_to_copy = std::min(byte_length, self->byte_length());
  if (bytes_to_copy) {
    i::DisallowGarbageCollection no_gc;
    const char* source;
    if (i::IsJSTypedArray(*self)) {
      i::Tagged<i::JSTypedArray> array = i::Cast<i::JSTypedArray>(*self);
      source = reinterpret_cast<char*>(array->DataPtr());
    } else {
      DCHECK(i::IsJSDataView(*self) || i::IsJSRabGsabDataView(*self));
      i::Tagged<i::JSDataViewOrRabGsabDataView> data_view =
          i::Cast<i::JSDataViewOrRabGsabDataView>(*self);
      source = reinterpret_cast<char*>(data_view->data_pointer());
    }
    memcpy(dest, source, bytes_to_copy);
  }
  return bytes_to_copy;
}
References DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
GetContents()
v8::MemorySpan< uint8_t > v8::ArrayBufferView::GetContents (v8::MemorySpan< uint8_t > storage)
Returns the contents of the ArrayBufferView's buffer as a MemorySpan.
If the contents are on the V8 heap, they get copied into storage. Otherwise a view into the off-heap backing store is returned. The provided storage should be at least as large as the maximum on-heap size of a TypedArray, was defined in gn with typed_array_max_size_in_heap. The default value is 64 bytes.
Definition at line 9174 of file api.cc.
                                   {
  internal::DisallowGarbageCollection no_gc;
  auto self = Utils::OpenDirectHandle(this);
  if (self->IsDetachedOrOutOfBounds()) return {};
  if (internal::IsJSTypedArray(*self)) {
    i::Tagged<i::JSTypedArray> typed_array = i::Cast<i::JSTypedArray>(*self);
    if (typed_array->is_on_heap()) {
      // The provided storage does not have enough capacity for the content of
      // the TypedArray.
      size_t bytes_to_copy = self->byte_length();
      CHECK_LE(bytes_to_copy, storage.size());
      const uint8_t* source =
          reinterpret_cast<uint8_t*>(typed_array->DataPtr());
      memcpy(reinterpret_cast<void*>(storage.data()), source, bytes_to_copy);
      return {storage.data(), bytes_to_copy};
    }
    // The TypedArray already has off-heap storage, just return a view on it.
    return {reinterpret_cast<uint8_t*>(typed_array->DataPtr()),
            typed_array->GetByteLength()};
  }
  if (i::IsJSDataView(*self)) {
    i::Tagged<i::JSDataView> data_view = i::Cast<i::JSDataView>(*self);
    return {reinterpret_cast<uint8_t*>(data_view->data_pointer()),
            data_view->byte_length()};
  }
  // Other types of ArrayBufferView always have an off-heap storage.
  DCHECK(i::IsJSRabGsabDataView(*self));
  i::Tagged<i::JSRabGsabDataView> data_view =
      i::Cast<i::JSRabGsabDataView>(*self);
  return {reinterpret_cast<uint8_t*>(data_view->data_pointer()),
          data_view->GetByteLength()};
}
References CHECK_LE, v8::MemorySpan< T >::data(), DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::MemorySpan< T >::size().
HasBuffer()
bool v8::ArrayBufferView::HasBuffer () const
Returns true if ArrayBufferView's backing ArrayBuffer has already been allocated.
Definition at line 9208 of file api.cc.
                                        {
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSTypedArray(*self)) return true;
  auto typed_array = i::Cast<i::JSTypedArray>(self);
  return !typed_array->is_on_heap();
}
References v8::Utils::OpenDirectHandle().
Member Data Documentation
kEmbedderFieldCount
const int v8::ArrayBufferView::kEmbedderFieldCount = kInternalFieldCount [static]
Definition at line 468 of file v8-array-buffer.h.
Referenced by v8::internal::BUILTIN(), and v8::internal::Factory::NewJSArrayBufferView().
kInternalFieldCount
constexpr int v8::ArrayBufferView::kInternalFieldCount [static], [constexpr]
Initial value:
=
      V8_ARRAY_BUFFER_VIEW_INTERNAL_FIELD_COUNT
Definition at line 466 of file v8-array-buffer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-array-buffer.h
/mnt/V8SourceCode/src/api/api.cc