v8::internal::CallDescriptors Class Reference
#include <interface-descriptors.h>
Public Types
enum Key { NUMBER_OF_DESCRIPTORS
 }
Static Public Member Functions
static void InitializeOncePerProcess ()
static void TearDown ()
static CallInterfaceDescriptorData * call_descriptor_data (CallDescriptors::Key key)
static Key GetKey (const CallInterfaceDescriptorData *data)
Static Private Attributes
static CallInterfaceDescriptorData call_descriptor_data_ [NUMBER_OF_DESCRIPTORS]
Detailed Description
Definition at line 309 of file interface-descriptors.h.
Member Enumeration Documentation
Key
enum v8::internal::CallDescriptors::Key
Enumerator
NUMBER_OF_DESCRIPTORS
Definition at line 311 of file interface-descriptors.h.
           {
#define DEF_ENUM(name, ...) name,
    INTERFACE_DESCRIPTOR_LIST(DEF_ENUM)
#undef DEF_ENUM
        NUMBER_OF_DESCRIPTORS
  };
Member Function Documentation
call_descriptor_data()
static CallInterfaceDescriptorData* v8::internal::CallDescriptors::call_descriptor_data (CallDescriptors::Key key) [inline], [static]
Definition at line 321 of file interface-descriptors.h.
                              {
    return &call_descriptor_data_[key];
  }
References v8::internal::key.
GetKey()
static Key v8::internal::CallDescriptors::GetKey (const CallInterfaceDescriptorData * data) [inline], [static]
Definition at line 326 of file interface-descriptors.h.
                                                             {
    ptrdiff_t index = data - call_descriptor_data_;
    DCHECK_LE(0, index);
    DCHECK_LT(index, CallDescriptors::NUMBER_OF_DESCRIPTORS);
    return static_cast<CallDescriptors::Key>(index);
  }
References DCHECK_LE, DCHECK_LT, v8::internal::index, and NUMBER_OF_DESCRIPTORS.
Referenced by v8::internal::CallInterfaceDescriptor::DebugName().
InitializeOncePerProcess()
void v8::internal::CallDescriptors::InitializeOncePerProcess () [static]
Definition at line 112 of file interface-descriptors.cc.
                                               {
#define INTERFACE_DESCRIPTOR(name, ...) \
  name##Descriptor().Initialize(&call_descriptor_data_[CallDescriptors::name]);
  INTERFACE_DESCRIPTOR_LIST(INTERFACE_DESCRIPTOR)
#undef INTERFACE_DESCRIPTOR
  DCHECK(ContextOnlyDescriptor{}.HasContextParameter());
  DCHECK(!NoContextDescriptor{}.HasContextParameter());
  DCHECK(!AllocateDescriptor{}.HasContextParameter());
  DCHECK(!AbortDescriptor{}.HasContextParameter());
  DCHECK(!WasmFloat32ToNumberDescriptor{}.HasContextParameter());
  DCHECK(!WasmFloat64ToTaggedDescriptor{}.HasContextParameter());
}
References v8::internal::DCHECK(), v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::HasContextParameter(), INTERFACE_DESCRIPTOR, and INTERFACE_DESCRIPTOR_LIST.
Referenced by v8::internal::V8::Initialize().
TearDown()
void v8::internal::CallDescriptors::TearDown () [static]
Definition at line 126 of file interface-descriptors.cc.
                               {
  for (CallInterfaceDescriptorData& data : call_descriptor_data_) {
    data.Reset();
  }
}
References call_descriptor_data_.
Referenced by v8::internal::V8::Dispose().
Member Data Documentation
call_descriptor_data_
CallInterfaceDescriptorData v8::internal::CallDescriptors::call_descriptor_data_ [static], [private]
Definition at line 335 of file interface-descriptors.h.
Referenced by TearDown().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors.cc