v8::internal::RegExpGlobalExecRunner Class Reference
#include <regexp.h>
Public Member Functions
RegExpGlobalExecRunner (DirectHandle< RegExpData > regexp_data, DirectHandle< String > subject, Isolate *isolate)
int32_t * FetchNext ()
int32_t * LastSuccessfulMatch () const
bool HasException () const
Private Member Functions
int AdvanceZeroLength (int last_index) const
int max_matches () const
Private Attributes
RegExpResultVectorScope result_vector_scope_
int num_matches_ = 0
int current_match_index_ = 0
int registers_per_match_ = 0
int32_t * register_array_ = nullptr
int register_array_size_ = 0
DirectHandle< RegExpData > regexp_data_
DirectHandle< String > subject_
Isolate *const isolate_
Detailed Description
Definition at line 183 of file regexp.h.
Constructor & Destructor Documentation
RegExpGlobalExecRunner()
v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner (DirectHandle< RegExpData > regexp_data, DirectHandle< String > subject, Isolate * isolate)
Definition at line 1143 of file regexp.cc.
    : result_vector_scope_(isolate),
      regexp_data_(regexp_data),
      subject_(subject),
      isolate_(isolate) {
  DCHECK(IsGlobal(JSRegExp::AsRegExpFlags(regexp_data->flags())));
  switch (regexp_data_->type_tag()) {
    case RegExpData::Type::ATOM: {
      registers_per_match_ = JSRegExp::kAtomRegisterCount;
      register_array_size_ = Isolate::kJSRegexpStaticOffsetsVectorSize;
      break;
    }
    case RegExpData::Type::IRREGEXP: {
      registers_per_match_ = RegExpImpl::IrregexpPrepare(
          isolate_, Cast<IrRegExpData>(regexp_data_), subject_);
      if (registers_per_match_ < 0) {
        num_matches_ = -1; // Signal exception.
        return;
      }
      if (Cast<IrRegExpData>(regexp_data_)->ShouldProduceBytecode()) {
        // Global loop in interpreted regexp is not implemented. We choose the
        // size of the offsets vector so that it can only store one match.
        register_array_size_ = registers_per_match_;
      } else {
        register_array_size_ = std::max(
            {registers_per_match_, Isolate::kJSRegexpStaticOffsetsVectorSize});
      }
      break;
    }
    case RegExpData::Type::EXPERIMENTAL: {
      if (!ExperimentalRegExp::IsCompiled(Cast<IrRegExpData>(regexp_data_),
                                          isolate_) &&
          !ExperimentalRegExp::Compile(isolate_,
                                       Cast<IrRegExpData>(regexp_data_))) {
        DCHECK(isolate->has_exception());
        num_matches_ = -1; // Signal exception.
        return;
      }
      registers_per_match_ = JSRegExp::RegistersForCaptureCount(
          Cast<IrRegExpData>(regexp_data_)->capture_count());
      register_array_size_ = std::max(
          {registers_per_match_, Isolate::kJSRegexpStaticOffsetsVectorSize});
      break;
    }
  }
  // Cache the result vector location.
  register_array_ = result_vector_scope_.Initialize(register_array_size_);
  // Set state so that fetching the results the first time triggers a call
  // to the compiled regexp.
  current_match_index_ = max_matches() - 1;
  num_matches_ = max_matches();
  DCHECK_LE(2, registers_per_match_); // Each match has at least one capture.
  DCHECK_GE(register_array_size_, registers_per_match_);
  int32_t* last_match =
      &register_array_[current_match_index_ * registers_per_match_];
  last_match[0] = -1;
  last_match[1] = 0;
}
References v8::internal::JSRegExp::AsRegExpFlags(), v8::internal::RegExpData::ATOM, v8::internal::ExperimentalRegExp::Compile(), current_match_index_, v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::RegExpData::EXPERIMENTAL, v8::internal::Isolate::has_exception(), v8::internal::RegExpResultVectorScope::Initialize(), v8::internal::RegExpData::IRREGEXP, v8::internal::RegExpImpl::IrregexpPrepare(), v8::internal::ExperimentalRegExp::IsCompiled(), isolate_, v8::internal::JSRegExp::kAtomRegisterCount, v8::internal::Isolate::kJSRegexpStaticOffsetsVectorSize, max_matches(), num_matches_, regexp_data_, register_array_, register_array_size_, registers_per_match_, v8::internal::JSRegExp::RegistersForCaptureCount(), result_vector_scope_, and subject_.
Member Function Documentation
AdvanceZeroLength()
int v8::internal::RegExpGlobalExecRunner::AdvanceZeroLength (int last_index) const [private]
Definition at line 1208 of file regexp.cc.
                                                                  {
  if (IsEitherUnicode(JSRegExp::AsRegExpFlags(regexp_data_->flags())) &&
      static_cast<uint32_t>(last_index + 1) < subject_->length() &&
      unibrow::Utf16::IsLeadSurrogate(subject_->Get(last_index)) &&
      unibrow::Utf16::IsTrailSurrogate(subject_->Get(last_index + 1))) {
    // Advance over the surrogate pair.
    return last_index + 2;
  }
  return last_index + 1;
}
References v8::internal::JSRegExp::AsRegExpFlags(), v8::internal::IsEitherUnicode(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsTrailSurrogate(), regexp_data_, and subject_.
Referenced by FetchNext().
FetchNext()
int32_t * v8::internal::RegExpGlobalExecRunner::FetchNext ()
Definition at line 1219 of file regexp.cc.
                                           {
  current_match_index_++;
  if (current_match_index_ >= num_matches_) {
    // Current batch of results exhausted.
    // Fail if last batch was not even fully filled.
    if (num_matches_ < max_matches()) {
      num_matches_ = 0; // Signal failed match.
      return nullptr;
    }
    int32_t* last_match =
        &register_array_[(current_match_index_ - 1) * registers_per_match_];
    int last_end_index = last_match[1];
    switch (regexp_data_->type_tag()) {
      case RegExpData::Type::ATOM:
        num_matches_ = RegExpImpl::AtomExecRaw(
            isolate_, Cast<AtomRegExpData>(regexp_data_), subject_,
            last_end_index, register_array_, register_array_size_);
        break;
      case RegExpData::Type::EXPERIMENTAL: {
        DCHECK(ExperimentalRegExp::IsCompiled(Cast<IrRegExpData>(regexp_data_),
                                              isolate_));
        DisallowGarbageCollection no_gc;
        num_matches_ = ExperimentalRegExp::ExecRaw(
            isolate_, RegExp::kFromRuntime, *Cast<IrRegExpData>(regexp_data_),
            *subject_, register_array_, register_array_size_, last_end_index);
        break;
      }
      case RegExpData::Type::IRREGEXP: {
        int last_start_index = last_match[0];
        if (last_start_index == last_end_index) {
          // Zero-length match. Advance by one code point.
          last_end_index = AdvanceZeroLength(last_end_index);
        }
        if (static_cast<uint32_t>(last_end_index) > subject_->length()) {
          num_matches_ = 0; // Signal failed match.
          return nullptr;
        }
        num_matches_ = RegExpImpl::IrregexpExecRaw(
            isolate_, Cast<IrRegExpData>(regexp_data_), subject_,
            last_end_index, register_array_, register_array_size_);
        break;
      }
    }
    // Fall back to experimental engine if needed and possible.
    if (num_matches_ == RegExp::kInternalRegExpFallbackToExperimental) {
      num_matches_ = ExperimentalRegExp::OneshotExecRaw(
          isolate_, Cast<IrRegExpData>(regexp_data_), subject_, register_array_,
          register_array_size_, last_end_index);
    }
    if (num_matches_ <= 0) {
      return nullptr;
    }
    // Number of matches can't exceed maximum matches.
    // This check is enough to prevent OOB accesses to register_array_ in the
    // else branch below, since current_match_index < num_matches_ in this
    // branch, it follows that current_match_index < max_matches(). And since
    // max_matches() = register_array_size_ / registers_per_match it follows
    // that current_match_index * registers_per_match_ < register_array_size_.
    SBXCHECK_LE(num_matches_, max_matches());
    current_match_index_ = 0;
    return register_array_;
  } else {
    return &register_array_[current_match_index_ * registers_per_match_];
  }
}
References AdvanceZeroLength(), v8::internal::RegExpData::ATOM, v8::internal::RegExpImpl::AtomExecRaw(), current_match_index_, v8::internal::DCHECK(), v8::internal::ExperimentalRegExp::ExecRaw(), v8::internal::RegExpData::EXPERIMENTAL, v8::internal::RegExpData::IRREGEXP, v8::internal::RegExpImpl::IrregexpExecRaw(), v8::internal::ExperimentalRegExp::IsCompiled(), isolate_, v8::internal::RegExp::kFromRuntime, v8::internal::RegExp::kInternalRegExpFallbackToExperimental, max_matches(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, num_matches_, v8::internal::ExperimentalRegExp::OneshotExecRaw(), regexp_data_, register_array_, register_array_size_, registers_per_match_, SBXCHECK_LE, and subject_.
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), and v8::internal::StringReplaceGlobalRegExpWithString().
HasException()
bool v8::internal::RegExpGlobalExecRunner::HasException () const [inline]
Definition at line 196 of file regexp.h.
{ return num_matches_ < 0; }
References num_matches_.
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), and v8::internal::StringReplaceGlobalRegExpWithString().
LastSuccessfulMatch()
int32_t * v8::internal::RegExpGlobalExecRunner::LastSuccessfulMatch () const
Definition at line 1292 of file regexp.cc.
                                                           {
  int index = current_match_index_ * registers_per_match_;
  if (num_matches_ == 0) {
    // After a failed match we shift back by one result.
    index -= registers_per_match_;
  }
  return &register_array_[index];
}
References current_match_index_, v8::internal::index, num_matches_, register_array_, and registers_per_match_.
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), and v8::internal::StringReplaceGlobalRegExpWithString().
max_matches()
int v8::internal::RegExpGlobalExecRunner::max_matches () const [inline], [private]
Definition at line 201 of file regexp.h.
                          {
    DCHECK_NE(register_array_size_, 0);
    return register_array_size_ / registers_per_match_;
  }
References DCHECK_NE, register_array_size_, and registers_per_match_.
Referenced by FetchNext(), and RegExpGlobalExecRunner().
Member Data Documentation
current_match_index_
int v8::internal::RegExpGlobalExecRunner::current_match_index_ = 0 [private]
Definition at line 208 of file regexp.h.
Referenced by FetchNext(), LastSuccessfulMatch(), and RegExpGlobalExecRunner().
isolate_
Isolate* const v8::internal::RegExpGlobalExecRunner::isolate_ [private]
Definition at line 215 of file regexp.h.
Referenced by FetchNext(), and RegExpGlobalExecRunner().
num_matches_
int v8::internal::RegExpGlobalExecRunner::num_matches_ = 0 [private]
Definition at line 207 of file regexp.h.
Referenced by FetchNext(), HasException(), LastSuccessfulMatch(), and RegExpGlobalExecRunner().
regexp_data_
DirectHandle<RegExpData> v8::internal::RegExpGlobalExecRunner::regexp_data_ [private]
Definition at line 213 of file regexp.h.
Referenced by AdvanceZeroLength(), FetchNext(), and RegExpGlobalExecRunner().
register_array_
int32_t* v8::internal::RegExpGlobalExecRunner::register_array_ = nullptr [private]
Definition at line 211 of file regexp.h.
Referenced by FetchNext(), LastSuccessfulMatch(), and RegExpGlobalExecRunner().
register_array_size_
int v8::internal::RegExpGlobalExecRunner::register_array_size_ = 0 [private]
Definition at line 212 of file regexp.h.
Referenced by FetchNext(), max_matches(), and RegExpGlobalExecRunner().
registers_per_match_
int v8::internal::RegExpGlobalExecRunner::registers_per_match_ = 0 [private]
Definition at line 209 of file regexp.h.
Referenced by FetchNext(), LastSuccessfulMatch(), max_matches(), and RegExpGlobalExecRunner().
result_vector_scope_
RegExpResultVectorScope v8::internal::RegExpGlobalExecRunner::result_vector_scope_ [private]
Definition at line 206 of file regexp.h.
Referenced by RegExpGlobalExecRunner().
subject_
DirectHandle<String> v8::internal::RegExpGlobalExecRunner::subject_ [private]
Definition at line 214 of file regexp.h.
Referenced by AdvanceZeroLength(), FetchNext(), and RegExpGlobalExecRunner().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp.h
/mnt/V8SourceCode/src/regexp/regexp.cc