v8::internal::ScavengerCollector::JobTask Class Reference
Public Member Functions
JobTask (ScavengerCollector *collector, std::vector< std::unique_ptr< Scavenger >> *scavengers, std::vector< std::pair< ParallelWorkItem, MutablePageMetadata * >> old_to_new_chunks, const Scavenger::CopiedList &copied_list, const Scavenger::PinnedList &pinned_list, const Scavenger::PromotedList &promoted_list)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
uint64_t trace_id () const
Private Member Functions
void ProcessItems (JobDelegate *delegate, Scavenger *scavenger)
void ConcurrentScavengePages (Scavenger *scavenger)
void VisitPinnedObjects (Scavenger *scavenger)
Private Attributes
ScavengerCollector * collector_
std::vector< std::unique_ptr< Scavenger > > * scavengers_
std::vector< std::pair< ParallelWorkItem, MutablePageMetadata * > > old_to_new_chunks_
std::atomic< size_t > remaining_memory_chunks_ {0}
IndexGenerator generator_
const Scavenger::CopiedList & copied_list_
const Scavenger::PinnedList & pinned_list_
const Scavenger::PromotedList & promoted_list_
const uint64_t trace_id_
Detailed Description
Definition at line 253 of file scavenger.h.
Constructor & Destructor Documentation
JobTask()
v8::internal::ScavengerCollector::JobTask::JobTask (ScavengerCollector * collector, std::vector< std::unique_ptr< Scavenger >> * scavengers, std::vector< std::pair< ParallelWorkItem, MutablePageMetadata * >> old_to_new_chunks, const Scavenger::CopiedList & copied_list, const Scavenger::PinnedList & pinned_list, const Scavenger::PromotedList & promoted_list)
Definition at line 208 of file scavenger.cc.
    : collector_(collector),
      scavengers_(scavengers),
      old_to_new_chunks_(std::move(old_to_new_chunks)),
      remaining_memory_chunks_(old_to_new_chunks_.size()),
      generator_(old_to_new_chunks_.size()),
      copied_list_(copied_list),
      pinned_list_(pinned_list),
      promoted_list_(promoted_list),
      trace_id_(reinterpret_cast<uint64_t>(this) ^
                collector_->heap_->tracer()->CurrentEpoch(
                    GCTracer::Scope::SCAVENGER)) {}
References v8::internal::SCAVENGER.
Member Function Documentation
ConcurrentScavengePages()
void v8::internal::ScavengerCollector::JobTask::ConcurrentScavengePages (Scavenger * scavenger) [private]
Definition at line 284 of file scavenger.cc.
                          {
  while (remaining_memory_chunks_.load(std::memory_order_relaxed) > 0) {
    std::optional<size_t> index = generator_.GetNext();
    if (!index) {
      return;
    }
    for (size_t i = *index; i < old_to_new_chunks_.size(); ++i) {
      auto& work_item = old_to_new_chunks_[i];
      if (!work_item.first.TryAcquire()) {
        break;
      }
      scavenger->ScavengePage(work_item.second);
      if (remaining_memory_chunks_.fetch_sub(1, std::memory_order_relaxed) <=
          1) {
        return;
      }
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, and v8::internal::Scavenger::ScavengePage().
GetMaxConcurrency()
size_t v8::internal::ScavengerCollector::JobTask::GetMaxConcurrency (size_t worker_count) const [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 251 of file scavenger.cc.
                               {
  // We need to account for local segments held by worker_count in addition to
  // GlobalPoolSize() of copied_list_, pinned_list_ and promoted_list_.
  size_t wanted_num_workers =
      std::max<size_t>(remaining_memory_chunks_.load(std::memory_order_relaxed),
                       worker_count + copied_list_.Size() +
                           pinned_list_.Size() + promoted_list_.Size());
  if (!collector_->heap_->ShouldUseBackgroundThreads() ||
      collector_->heap_->ShouldOptimizeForBattery()) {
    return std::min<size_t>(wanted_num_workers, 1);
  }
  return std::min<size_t>(scavengers_->size(), wanted_num_workers);
}
ProcessItems()
void v8::internal::ScavengerCollector::JobTask::ProcessItems (JobDelegate * delegate, Scavenger * scavenger) [private]
Definition at line 266 of file scavenger.cc.
                                                                     {
  double scavenging_time = 0.0;
  {
    TimedScope scope(&scavenging_time);
    scavenger->VisitPinnedObjects();
    ConcurrentScavengePages(scavenger);
    scavenger->Process(delegate);
  }
  if (V8_UNLIKELY(v8_flags.trace_parallel_scavenge)) {
    PrintIsolate(collector_->heap_->isolate(),
                 "scavenge[%p]: time=%.2f copied=%zu promoted=%zu\n",
                 static_cast<void*>(this), scavenging_time,
                 scavenger->bytes_copied(), scavenger->bytes_promoted());
  }
}
References v8::internal::Scavenger::bytes_copied(), v8::internal::Scavenger::bytes_promoted(), v8::internal::PrintIsolate(), v8::internal::Scavenger::Process(), v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::Scavenger::VisitPinnedObjects().
Run()
void v8::internal::ScavengerCollector::JobTask::Run (JobDelegate * delegate) [override], [virtual]
Implements v8::JobTask.
Definition at line 228 of file scavenger.cc.
                                                         {
  DCHECK_LT(delegate->GetTaskId(), scavengers_->size());
  // Set the current isolate such that trusted pointer tables etc are
  // available and the cage base is set correctly for multi-cage mode.
  SetCurrentIsolateScope isolate_scope(collector_->heap_->isolate());
  collector_->estimate_concurrency_.fetch_add(1, std::memory_order_relaxed);
  Scavenger* scavenger = (*scavengers_)[delegate->GetTaskId()].get();
  if (delegate->IsJoiningThread()) {
    TRACE_GC_WITH_FLOW(collector_->heap_->tracer(),
                       GCTracer::Scope::SCAVENGER_SCAVENGE_PARALLEL, trace_id_,
                       TRACE_EVENT_FLAG_FLOW_IN);
    ProcessItems(delegate, scavenger);
  } else {
    TRACE_GC_EPOCH_WITH_FLOW(
        collector_->heap_->tracer(),
        GCTracer::Scope::SCAVENGER_BACKGROUND_SCAVENGE_PARALLEL,
        ThreadKind::kBackground, trace_id_, TRACE_EVENT_FLAG_FLOW_IN);
    ProcessItems(delegate, scavenger);
  }
}
References DCHECK_LT, v8::JobDelegate::GetTaskId(), v8::JobDelegate::IsJoiningThread(), v8::internal::kBackground, TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, and TRACE_GC_WITH_FLOW.
trace_id()
uint64_t v8::internal::ScavengerCollector::JobTask::trace_id () const [inline]
Definition at line 266 of file scavenger.h.
{ return trace_id_; }
References trace_id_.
VisitPinnedObjects()
void v8::internal::ScavengerCollector::JobTask::VisitPinnedObjects (Scavenger * scavenger) [private]
Member Data Documentation
collector_
ScavengerCollector* v8::internal::ScavengerCollector::JobTask::collector_ [private]
Definition at line 273 of file scavenger.h.
copied_list_
const Scavenger::CopiedList& v8::internal::ScavengerCollector::JobTask::copied_list_ [private]
Definition at line 281 of file scavenger.h.
generator_
IndexGenerator v8::internal::ScavengerCollector::JobTask::generator_ [private]
Definition at line 279 of file scavenger.h.
old_to_new_chunks_
std::vector<std::pair<ParallelWorkItem, MutablePageMetadata*> > v8::internal::ScavengerCollector::JobTask::old_to_new_chunks_ [private]
Definition at line 277 of file scavenger.h.
pinned_list_
const Scavenger::PinnedList& v8::internal::ScavengerCollector::JobTask::pinned_list_ [private]
Definition at line 282 of file scavenger.h.
promoted_list_
const Scavenger::PromotedList& v8::internal::ScavengerCollector::JobTask::promoted_list_ [private]
Definition at line 283 of file scavenger.h.
remaining_memory_chunks_
std::atomic<size_t> v8::internal::ScavengerCollector::JobTask::remaining_memory_chunks_ {0} [private]
Definition at line 278 of file scavenger.h.
scavengers_
std::vector<std::unique_ptr<Scavenger> >* v8::internal::ScavengerCollector::JobTask::scavengers_ [private]
Definition at line 275 of file scavenger.h.
trace_id_
const uint64_t v8::internal::ScavengerCollector::JobTask::trace_id_ [private]
Definition at line 285 of file scavenger.h.
Referenced by trace_id().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/scavenger.h
/mnt/V8SourceCode/src/heap/scavenger.cc