v8::internal::PrototypeCheckAssembler Class Reference
#include <code-stub-assembler.h>
Classes
struct DescriptorIndexNameValue
Public Types
enum Flag { kCheckPrototypePropertyConstness = 1 << 0
, kCheckPrototypePropertyIdentity = 1 << 1
, kCheckFull
 }
using Flags = base::Flags< Flag >
Public Member Functions
PrototypeCheckAssembler (compiler::CodeAssemblerState *state, Flags flags, TNode< NativeContext > native_context, TNode< Map > initial_prototype_map, base::Vector< DescriptorIndexNameValue > properties)
void CheckAndBranch (TNode< HeapObject > prototype, Label *if_unmodified, Label *if_modified)
Private Attributes
const Flags flags_
const TNode< NativeContext > native_context_
const TNode< Map > initial_prototype_map_
const base::Vector< DescriptorIndexNameValue > properties_
Additional Inherited Members
Detailed Description
Definition at line 4989 of file code-stub-assembler.h.
Member Typedef Documentation
Flags
using v8::internal::PrototypeCheckAssembler::Flags = base::Flags<Flag>
Definition at line 4997 of file code-stub-assembler.h.
Member Enumeration Documentation
Flag
enum v8::internal::PrototypeCheckAssembler::Flag
Enumerator
kCheckPrototypePropertyConstness
kCheckPrototypePropertyIdentity
kCheckFull
Definition at line 4991 of file code-stub-assembler.h.
            {
    kCheckPrototypePropertyConstness = 1 << 0,
    kCheckPrototypePropertyIdentity = 1 << 1,
    kCheckFull =
        kCheckPrototypePropertyConstness | kCheckPrototypePropertyIdentity,
  };
Constructor & Destructor Documentation
PrototypeCheckAssembler()
v8::internal::PrototypeCheckAssembler::PrototypeCheckAssembler (compiler::CodeAssemblerState * state, Flags flags, TNode< NativeContext > native_context, TNode< Map > initial_prototype_map, base::Vector< DescriptorIndexNameValue > properties)
Definition at line 18508 of file code-stub-assembler.cc.
    : CodeStubAssembler(state),
      flags_(flags),
      native_context_(native_context),
      initial_prototype_map_(initial_prototype_map),
      properties_(properties) {}
Member Function Documentation
CheckAndBranch()
void v8::internal::PrototypeCheckAssembler::CheckAndBranch (TNode< HeapObject > prototype, Label * if_unmodified, Label * if_modified)
Definition at line 18518 of file code-stub-assembler.cc.
                                                                 {
  TNode<Map> prototype_map = LoadMap(prototype);
  TNode<DescriptorArray> descriptors = LoadMapDescriptors(prototype_map);
  // The continuation of a failed fast check: if property identity checks are
  // enabled, we continue there (since they may still classify the prototype as
  // fast), otherwise we bail out.
  Label property_identity_check(this, Label::kDeferred);
  Label* if_fast_check_failed =
      ((flags_ & kCheckPrototypePropertyIdentity) == 0)
          ? if_modified
          : &property_identity_check;
  if ((flags_ & kCheckPrototypePropertyConstness) != 0) {
    // A simple prototype map identity check. Note that map identity does not
    // guarantee unmodified properties. It does guarantee that no new properties
    // have been added, or old properties deleted.
    GotoIfNot(TaggedEqual(prototype_map, initial_prototype_map_),
              if_fast_check_failed);
    // We need to make sure that relevant properties in the prototype have
    // not been tampered with. We do this by checking that their slots
    // in the prototype's descriptor array are still marked as const.
    TNode<Uint32T> combined_details;
    for (int i = 0; i < properties_.length(); i++) {
      // Assert the descriptor index is in-bounds.
      int descriptor = properties_[i].descriptor_index;
      CSA_DCHECK(this, Int32LessThan(Int32Constant(descriptor),
                                     LoadNumberOfDescriptors(descriptors)));
      // Assert that the name is correct. This essentially checks that
      // the descriptor index corresponds to the insertion order in
      // the bootstrapper.
      CSA_DCHECK(
          this,
          TaggedEqual(LoadKeyByDescriptorEntry(descriptors, descriptor),
                      CodeAssembler::LoadRoot(properties_[i].name_root_index)));
      TNode<Uint32T> details =
          DescriptorArrayGetDetails(descriptors, Uint32Constant(descriptor));
      if (i == 0) {
        combined_details = details;
      } else {
        combined_details = Word32And(combined_details, details);
      }
    }
    TNode<Uint32T> constness =
        DecodeWord32<PropertyDetails::ConstnessField>(combined_details);
    Branch(
        Word32Equal(constness,
                    Int32Constant(static_cast<int>(PropertyConstness::kConst))),
        if_unmodified, if_fast_check_failed);
  }
  if ((flags_ & kCheckPrototypePropertyIdentity) != 0) {
    // The above checks have failed, for whatever reason (maybe the prototype
    // map has changed, or a property is no longer const). This block implements
    // a more thorough check that can also accept maps which 1. do not have the
    // initial map, 2. have mutable relevant properties, but 3. still match the
    // expected value for all relevant properties.
    BIND(&property_identity_check);
    int max_descriptor_index = -1;
    for (int i = 0; i < properties_.length(); i++) {
      max_descriptor_index =
          std::max(max_descriptor_index, properties_[i].descriptor_index);
    }
    // If the greatest descriptor index is out of bounds, the map cannot be
    // fast.
    GotoIfNot(Int32LessThan(Int32Constant(max_descriptor_index),
                            LoadNumberOfDescriptors(descriptors)),
              if_modified);
    // Logic below only handles maps with fast properties.
    GotoIfMapHasSlowProperties(prototype_map, if_modified);
    for (int i = 0; i < properties_.length(); i++) {
      const DescriptorIndexNameValue& p = properties_[i];
      const int descriptor = p.descriptor_index;
      // Check if the name is correct. This essentially checks that
      // the descriptor index corresponds to the insertion order in
      // the bootstrapper.
      GotoIfNot(TaggedEqual(LoadKeyByDescriptorEntry(descriptors, descriptor),
                            CodeAssembler::LoadRoot(p.name_root_index)),
                if_modified);
      // Finally, check whether the actual value equals the expected value.
      TNode<Uint32T> details =
          DescriptorArrayGetDetails(descriptors, Uint32Constant(descriptor));
      TVARIABLE(Uint32T, var_details, details);
      TVARIABLE(Object, var_value);
      const int key_index = DescriptorArray::ToKeyIndex(descriptor);
      LoadPropertyFromFastObject(prototype, prototype_map, descriptors,
                                 IntPtrConstant(key_index), &var_details,
                                 &var_value);
      TNode<Object> actual_value = var_value.value();
      TNode<Object> expected_value = LoadContextElementNoCell(
          native_context_, p.expected_value_context_index);
      GotoIfNot(TaggedEqual(actual_value, expected_value), if_modified);
    }
    Goto(if_unmodified);
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::PrototypeCheckAssembler::DescriptorIndexNameValue::descriptor_index, v8::internal::CodeStubAssembler::DescriptorArrayGetDetails(), v8::internal::PrototypeCheckAssembler::DescriptorIndexNameValue::expected_value_context_index, flags_, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::GotoIfMapHasSlowProperties(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, initial_prototype_map_, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), kCheckPrototypePropertyConstness, kCheckPrototypePropertyIdentity, v8::internal::kConst, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadKeyByDescriptorEntry(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapDescriptors(), v8::internal::CodeStubAssembler::LoadNumberOfDescriptors(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), v8::internal::PrototypeCheckAssembler::DescriptorIndexNameValue::name_root_index, native_context_, properties_, v8::internal::prototype, v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::DescriptorArray::ToKeyIndex(), v8::internal::compiler::CodeAssembler::Uint32Constant(), v8::internal::compiler::CodeAssembler::Word32And(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExp(), and v8::internal::BaseCollectionsAssembler::GotoIfInitialAddFunctionModified().
Member Data Documentation
flags_
const Flags v8::internal::PrototypeCheckAssembler::flags_ [private]
Definition at line 5018 of file code-stub-assembler.h.
Referenced by CheckAndBranch().
initial_prototype_map_
const TNode<Map> v8::internal::PrototypeCheckAssembler::initial_prototype_map_ [private]
Definition at line 5020 of file code-stub-assembler.h.
Referenced by CheckAndBranch().
native_context_
const TNode<NativeContext> v8::internal::PrototypeCheckAssembler::native_context_ [private]
Definition at line 5019 of file code-stub-assembler.h.
Referenced by CheckAndBranch().
properties_
const base::Vector<DescriptorIndexNameValue> v8::internal::PrototypeCheckAssembler::properties_ [private]
Definition at line 5021 of file code-stub-assembler.h.
Referenced by CheckAndBranch().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/code-stub-assembler.h
/mnt/V8SourceCode/src/codegen/code-stub-assembler.cc