cppgc::internal::NameTrait< T > Class Template Reference
#include <name-trait.h>
Static Public Member Functions
static constexpr bool HasNonHiddenName ()
static HeapObjectName GetName (const void *obj, HeapObjectNameForUnnamedObject name_retrieval_mode)
Static Private Member Functions
static HeapObjectName GetNameFor (const NameProvider *name_provider, HeapObjectNameForUnnamedObject)
static HeapObjectName GetNameFor (const void *, HeapObjectNameForUnnamedObject name_retrieval_mode)
Additional Inherited Members
Detailed Description
template<typename T>
class cppgc::internal::NameTrait< T >
Definition at line 75 of file name-trait.h.
Member Function Documentation
GetName()
template<typename T >
static HeapObjectName cppgc::internal::NameTrait< T >::GetName (const void * obj, HeapObjectNameForUnnamedObject name_retrieval_mode) [inline], [static]
Definition at line 87 of file name-trait.h.
                                                                           {
    return GetNameFor(static_cast<const T*>(obj), name_retrieval_mode);
  }
References cppgc::internal::NameTrait< T >::GetNameFor().
GetNameFor() [1/2]
template<typename T >
static HeapObjectName cppgc::internal::NameTrait< T >::GetNameFor (const NameProvider * name_provider, HeapObjectNameForUnnamedObject) [inline], [static], [private]
Definition at line 93 of file name-trait.h.
                                                                   {
    // Objects inheriting from `NameProvider` are not considered unnamed as
    // users already provided a name for them.
    return {name_provider->GetHumanReadableName(), false};
  }
References cppgc::NameProvider::GetHumanReadableName().
Referenced by cppgc::internal::NameTrait< T >::GetName().
GetNameFor() [2/2]
template<typename T >
static HeapObjectName cppgc::internal::NameTrait< T >::GetNameFor (const void * , HeapObjectNameForUnnamedObject name_retrieval_mode) [inline], [static], [private]
Definition at line 100 of file name-trait.h.
                                                                       {
    if (name_retrieval_mode == HeapObjectNameForUnnamedObject::kUseHiddenName)
      return {NameProvider::kHiddenName, true};
#if CPPGC_SUPPORTS_COMPILE_TIME_TYPENAME
    return {GetTypename<T>(), false};
#elif CPPGC_SUPPORTS_OBJECT_NAMES
#if defined(V8_CC_GNU)
#define PRETTY_FUNCTION_VALUE __PRETTY_FUNCTION__
#elif defined(V8_CC_MSVC)
#define PRETTY_FUNCTION_VALUE __FUNCSIG__
#else
#define PRETTY_FUNCTION_VALUE nullptr
#endif
    static const HeapObjectName leaky_name =
        GetNameFromTypeSignature(PRETTY_FUNCTION_VALUE);
    return leaky_name;
#undef PRETTY_FUNCTION_VALUE
#else // !CPPGC_SUPPORTS_OBJECT_NAMES
    // We wanted to use a class name but were unable to provide one due to
    // compiler limitations or build configuration. As such, return the hidden
    // name with name_was_hidden=false, which will cause this object to be
    // visible in the snapshot.
    return {NameProvider::kHiddenName, false};
#endif // !CPPGC_SUPPORTS_OBJECT_NAMES
  }
References cppgc::internal::NameTraitBase::GetNameFromTypeSignature(), cppgc::NameProvider::kHiddenName, and cppgc::internal::kUseHiddenName.
HasNonHiddenName()
template<typename T >
static constexpr bool cppgc::internal::NameTrait< T >::HasNonHiddenName () [inline], [static], [constexpr]
Definition at line 77 of file name-trait.h.
                                           {
#if CPPGC_SUPPORTS_COMPILE_TIME_TYPENAME
    return true;
#elif CPPGC_SUPPORTS_OBJECT_NAMES
    return true;
#else // !CPPGC_SUPPORTS_OBJECT_NAMES
    return std::is_base_of_v<NameProvider, T>;
#endif // !CPPGC_SUPPORTS_OBJECT_NAMES
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/internal/name-trait.h