v8::internal::wasm::gdb_server::GdbServerThread Class Reference
#include <gdb-server-thread.h>
Public Member Functions
GdbServerThread (GdbServer *gdb_server)
GdbServerThread (const GdbServerThread &)=delete
GdbServerThread & operator= (const GdbServerThread &)=delete
void Run () override
bool StartAndInitialize ()
void Stop ()
Target & GetTarget ()
Private Member Functions
void CleanupThread ()
Private Attributes
GdbServer * gdb_server_
base::Semaphore start_semaphore_
base::Mutex mutex_
std::unique_ptr< TransportBase > transport_
std::unique_ptr< Target > target_
Additional Inherited Members
Detailed Description
Definition at line 22 of file gdb-server-thread.h.
Constructor & Destructor Documentation
GdbServerThread() [1/2]
v8::internal::wasm::gdb_server::GdbServerThread::GdbServerThread (GdbServer * gdb_server) [explicit]
Definition at line 16 of file gdb-server-thread.cc.
    : Thread(v8::base::Thread::Options("GdbServerThread")),
      gdb_server_(gdb_server),
      start_semaphore_(0) {}
GdbServerThread() [2/2]
v8::internal::wasm::gdb_server::GdbServerThread::GdbServerThread (const GdbServerThread &) [delete]
Member Function Documentation
CleanupThread()
void v8::internal::wasm::gdb_server::GdbServerThread::CleanupThread () [private]
Definition at line 40 of file gdb-server-thread.cc.
                                    {
  // Executed in the GdbServer thread.
  v8::base::MutexGuard guard(&mutex_);
  target_ = nullptr;
  transport_ = nullptr;
#if _WIN32
  ::WSACleanup();
#endif
}
References mutex_, target_, and transport_.
Referenced by Run().
GetTarget()
Target& v8::internal::wasm::gdb_server::GdbServerThread::GetTarget () [inline]
Definition at line 39 of file gdb-server-thread.h.
{ return *target_; }
References target_.
operator=()
GdbServerThread& v8::internal::wasm::gdb_server::GdbServerThread::operator= (const GdbServerThread &) [delete]
Run()
void v8::internal::wasm::gdb_server::GdbServerThread::Run () [override], [virtual]
Implements v8::base::Thread.
Definition at line 52 of file gdb-server-thread.cc.
                          {
  // Executed in the GdbServer thread.
#ifdef _WIN32
  // Initialize Winsock
  WSADATA wsaData;
  int iResult = ::WSAStartup(MAKEWORD(2, 2), &wsaData);
  if (iResult != 0) {
    TRACE_GDB_REMOTE("GdbServerThread::Run: WSAStartup failed\n");
    return;
  }
#endif
  // If the default port is not available, try any port.
  SocketBinding socket_binding =
      SocketBinding::Bind(v8_flags.wasm_gdb_remote_port);
  if (!socket_binding.IsValid()) {
    socket_binding = SocketBinding::Bind(0);
  }
  if (!socket_binding.IsValid()) {
    TRACE_GDB_REMOTE("GdbServerThread::Run: Failed to bind any TCP port\n");
    return;
  }
  TRACE_GDB_REMOTE("gdb-remote(%d) : Connect GDB with 'target remote :%d\n",
                   __LINE__, socket_binding.GetBoundPort());
  transport_ = socket_binding.CreateTransport();
  target_ = std::make_unique<Target>(gdb_server_);
  // Here we have completed the initialization, and the thread that called
  // {StartAndInitialize} may resume execution.
  start_semaphore_.Signal();
  while (!target_->IsTerminated()) {
    // Wait for incoming connections.
    if (!transport_->AcceptConnection()) {
      continue;
    }
    // Create a new session for this connection
    Session session(transport_.get());
    TRACE_GDB_REMOTE("GdbServerThread: Connected\n");
    // Run this session for as long as it lasts
    target_->Run(&session);
  }
  CleanupThread();
}
References v8::internal::wasm::gdb_server::SocketBinding::Bind(), CleanupThread(), v8::internal::wasm::gdb_server::SocketBinding::CreateTransport(), gdb_server_, v8::internal::wasm::gdb_server::SocketBinding::GetBoundPort(), v8::internal::wasm::gdb_server::SocketBinding::IsValid(), v8::base::Semaphore::Signal(), start_semaphore_, target_, TRACE_GDB_REMOTE, transport_, and v8::internal::v8_flags.
StartAndInitialize()
bool v8::internal::wasm::gdb_server::GdbServerThread::StartAndInitialize ()
Definition at line 21 of file gdb-server-thread.cc.
                                         {
  // Executed in the Isolate thread.
  if (!Start()) {
    return false;
  }
  // We need to make sure that {Stop} is never called before the thread has
  // completely initialized {transport_} and {target_}. Otherwise there could be
  // a race condition where in the main thread {Stop} might get called before
  // the transport is created, and then in the GDBServer thread we may have time
  // to setup the transport and block on accept() before the main thread blocks
  // on joining the thread.
  // The small performance hit caused by this Wait should be negligeable because
  // this operation happensat most once per process and only when the
  // --wasm-gdb-remote flag is set.
  start_semaphore_.Wait();
  return !!target_;
}
References v8::base::Thread::Start(), start_semaphore_, target_, and v8::base::Semaphore::Wait().
Stop()
void v8::internal::wasm::gdb_server::GdbServerThread::Stop ()
Definition at line 100 of file gdb-server-thread.cc.
                           {
  // Executed in the Isolate thread.
  // Synchronized, becauses {Stop} might be called while {Run} is still
  // initializing {transport_} and {target_}. If this happens and the thread is
  // blocked waiting for an incoming connection or GdbServer for incoming
  // packets, it will unblocked when {transport_} is closed.
  v8::base::MutexGuard guard(&mutex_);
  if (target_) {
    target_->Terminate();
  }
  if (transport_) {
    transport_->Close();
  }
}
References mutex_, target_, and transport_.
Member Data Documentation
gdb_server_
GdbServer* v8::internal::wasm::gdb_server::GdbServerThread::gdb_server_ [private]
Definition at line 44 of file gdb-server-thread.h.
Referenced by Run().
mutex_
base::Mutex v8::internal::wasm::gdb_server::GdbServerThread::mutex_ [private]
Definition at line 52 of file gdb-server-thread.h.
Referenced by CleanupThread(), and Stop().
start_semaphore_
base::Semaphore v8::internal::wasm::gdb_server::GdbServerThread::start_semaphore_ [private]
Definition at line 50 of file gdb-server-thread.h.
Referenced by Run(), and StartAndInitialize().
target_
std::unique_ptr<Target> v8::internal::wasm::gdb_server::GdbServerThread::target_ [private]
Definition at line 55 of file gdb-server-thread.h.
Referenced by CleanupThread(), GetTarget(), Run(), StartAndInitialize(), and Stop().
transport_
std::unique_ptr<TransportBase> v8::internal::wasm::gdb_server::GdbServerThread::transport_ [private]
Definition at line 54 of file gdb-server-thread.h.
Referenced by CleanupThread(), Run(), and Stop().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/gdb-server-thread.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/gdb-server-thread.cc