v8::internal::CompactionSpace Class Reference
#include <paged-spaces.h>
Public Types
enum class DestinationHeap { kSameHeap
, kSharedSpaceHeap
 }
Public Member Functions
CompactionSpace (Heap *heap, AllocationSpace id, Executability executable, CompactionSpaceKind compaction_space_kind, DestinationHeap destination_heap)
const std::vector< PageMetadata * > & GetNewPages ()
void RefillFreeList () final
DestinationHeap destination_heap () const
Protected Member Functions
void NotifyNewPage (PageMetadata *page) final
bool snapshotable () const final
Protected Attributes
std::vector< PageMetadata * > new_pages_
const DestinationHeap destination_heap_
Additional Inherited Members
Detailed Description
Definition at line 375 of file paged-spaces.h.
Member Enumeration Documentation
DestinationHeap
enum v8::internal::CompactionSpace::DestinationHeap [strong]
Enumerator
kSameHeap
kSharedSpaceHeap
Definition at line 378 of file paged-spaces.h.
                             {
    // Should be merged to the same heap.
    kSameHeap,
    // Should be merged to the main isolate shared space.
    kSharedSpaceHeap
  };
Constructor & Destructor Documentation
CompactionSpace()
v8::internal::CompactionSpace::CompactionSpace (Heap * heap, AllocationSpace id, Executability executable, CompactionSpaceKind compaction_space_kind, DestinationHeap destination_heap) [inline]
Definition at line 385 of file paged-spaces.h.
      : PagedSpace(heap, id, executable, FreeList::CreateFreeList(),
                   compaction_space_kind),
        destination_heap_(destination_heap) {
    DCHECK(is_compaction_space());
  }
References v8::internal::DCHECK().
Member Function Documentation
destination_heap()
DestinationHeap v8::internal::CompactionSpace::destination_heap () const [inline]
Definition at line 398 of file paged-spaces.h.
{ return destination_heap_; }
Referenced by v8::internal::PagedSpaceBase::MergeCompactionSpace(), and NotifyNewPage().
GetNewPages()
const std::vector<PageMetadata*>& v8::internal::CompactionSpace::GetNewPages () [inline]
Definition at line 394 of file paged-spaces.h.
{ return new_pages_; }
Referenced by v8::internal::PagedSpaceBase::MergeCompactionSpace().
NotifyNewPage()
void v8::internal::CompactionSpace::NotifyNewPage (PageMetadata * page) [final], [protected], [virtual]
Reimplemented from v8::internal::PagedSpaceBase.
Definition at line 571 of file paged-spaces.cc.
                                                      {
  // Incremental marking can be running on the main thread isolate, so when
  // allocating a new page for the client's compaction space we can get a black
  // allocated page. This is fine, since the page is not observed the main
  // isolate until it's merged.
  DCHECK_IMPLIES(identity() != SHARED_SPACE ||
                     destination_heap() != DestinationHeap::kSharedSpaceHeap,
                 !page->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
  new_pages_.push_back(page);
}
References v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_IMPLIES, destination_heap(), v8::internal::MemoryChunk::IsFlagSet(), kSharedSpaceHeap, new_pages_, and v8::internal::SHARED_SPACE.
RefillFreeList()
void v8::internal::CompactionSpace::RefillFreeList () [final], [virtual]
Reimplemented from v8::internal::PagedSpaceBase.
Definition at line 582 of file paged-spaces.cc.
                                     {
  DCHECK_NE(NEW_SPACE, identity());
  Sweeper* sweeper = heap()->sweeper();
  size_t added = 0;
  PageMetadata* p = nullptr;
  while ((added <= kCompactionMemoryWanted) &&
         (p = sweeper->GetSweptPageSafe(this))) {
    // We regularly sweep NEVER_ALLOCATE_ON_PAGE pages. We drop the freelist
    // entries here to make them unavailable for allocations.
    if (p->Chunk()->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE)) {
      free_list()->EvictFreeListItems(p);
    }
    // Only during compaction pages can actually change ownership. This is
    // safe because there exists no other competing action on the page links
    // during compaction.
    DCHECK_NE(this, p->owner());
    PagedSpace* owner = static_cast<PagedSpace*>(p->owner());
    base::MutexGuard guard(owner->mutex());
    owner->RefineAllocatedBytesAfterSweeping(p);
    owner->RemovePage(p);
    added += AddPage(p);
    added += p->wasted_memory();
  }
}
References v8::internal::PagedSpaceBase::AddPage(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_NE, v8::internal::Sweeper::GetSweptPageSafe(), heap(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::PagedSpaceBase::kCompactionMemoryWanted, v8::internal::PagedSpaceBase::mutex(), v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE, v8::internal::NEW_SPACE, v8::internal::MutablePageMetadata::owner(), v8::internal::PagedSpaceBase::RefineAllocatedBytesAfterSweeping(), v8::internal::PagedSpaceBase::RemovePage(), and v8::internal::MemoryChunkMetadata::wasted_memory().
snapshotable()
bool v8::internal::CompactionSpace::snapshotable () const [inline], [final], [protected], [virtual]
Reimplemented from v8::internal::PagedSpaceBase.
Definition at line 404 of file paged-spaces.h.
{ return false; }
Member Data Documentation
destination_heap_
const DestinationHeap v8::internal::CompactionSpace::destination_heap_ [protected]
Definition at line 408 of file paged-spaces.h.
new_pages_
std::vector<PageMetadata*> v8::internal::CompactionSpace::new_pages_ [protected]
Definition at line 407 of file paged-spaces.h.
Referenced by NotifyNewPage().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/paged-spaces.h
/mnt/V8SourceCode/src/heap/paged-spaces.cc