v8::internal::ManualOptimizationTable Class Reference
#include <pending-optimization-table.h>
Static Public Member Functions
static void MarkFunctionForManualOptimization (Isolate *isolate, DirectHandle< JSFunction > function, IsCompiledScope *is_compiled_scope)
static bool IsMarkedForManualOptimization (Isolate *isolate, Tagged< JSFunction > function)
Detailed Description
Definition at line 18 of file pending-optimization-table.h.
Member Function Documentation
IsMarkedForManualOptimization()
bool v8::internal::ManualOptimizationTable::IsMarkedForManualOptimization (Isolate * isolate, Tagged< JSFunction > function) [static]
Definition at line 45 of file pending-optimization-table.cc.
                                                   {
  DCHECK(v8_flags.testing_d8_test_runner || v8_flags.allow_natives_syntax);
  DirectHandle<Object> table(
      isolate->heap()->functions_marked_for_manual_optimization(), isolate);
  DirectHandle<Object> entry(
      IsUndefined(*table) ? ReadOnlyRoots(isolate).the_hole_value()
                          : Cast<ObjectHashTable>(table)->Lookup(
                                direct_handle(function->shared(), isolate)),
      isolate);
  return !IsTheHole(*entry);
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::heap(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{runtime-test.cc}::CheckMarkedForManualOptimization(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), and v8::internal::TieringManager::MaybeOptimizeFrame().
MarkFunctionForManualOptimization()
void v8::internal::ManualOptimizationTable::MarkFunctionForManualOptimization (Isolate * isolate, DirectHandle< JSFunction > function, IsCompiledScope * is_compiled_scope) [static]
Definition at line 16 of file pending-optimization-table.cc.
                                        {
  DCHECK(v8_flags.testing_d8_test_runner || v8_flags.allow_natives_syntax);
  DCHECK(is_compiled_scope->is_compiled());
  DCHECK(function->has_feedback_vector());
  DirectHandle<SharedFunctionInfo> shared_info(function->shared(), isolate);
  Handle<ObjectHashTable> table =
      IsUndefined(isolate->heap()->functions_marked_for_manual_optimization())
          ? ObjectHashTable::New(isolate, 1)
          : handle(Cast<ObjectHashTable>(
                       isolate->heap()
                           ->functions_marked_for_manual_optimization()),
                   isolate);
  // We want to keep the function's BytecodeArray alive as bytecode flushing
  // may otherwise delete it. However, we can't directly store a reference to
  // the BytecodeArray inside the hash table as the BytecodeArray lives in
  // trusted space (outside of the main pointer compression cage) when the
  // sandbox is enabled. So instead, we reference the BytecodeArray's
  // in-sandbox wrapper object.
  table = ObjectHashTable::Put(
      table, shared_info,
      direct_handle(shared_info->GetBytecodeArray(isolate)->wrapper(),
                    isolate));
  isolate->heap()->SetFunctionsMarkedForManualOptimization(*table);
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::handle(), v8::internal::Isolate::heap(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::Heap::SetFunctionsMarkedForManualOptimization(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/pending-optimization-table.h
/mnt/V8SourceCode/src/codegen/pending-optimization-table.cc