v8::internal::StringComparator::State Class Reference
Public Member Functions
State ()
State (const State &)=delete
State & operator= (const State &)=delete
void Init (Tagged< String > string, const SharedStringAccessGuardIfNeeded &access_guard)
void VisitOneByteString (const uint8_t *chars, int length)
void VisitTwoByteString (const uint16_t *chars, int length)
void Advance (int consumed, const SharedStringAccessGuardIfNeeded &access_guard)
Public Attributes
ConsStringIterator iter_
bool is_one_byte_
int length_
xx xx xx xx xx xx xx xx xx
union {
 const uint8_t * buffer8_
 const uint16_t * buffer16_
};
Detailed Description
Definition at line 17 of file string-comparator.h.
Constructor & Destructor Documentation
State() [1/2]
v8::internal::StringComparator::State::State () [inline]
Definition at line 19 of file string-comparator.h.
: is_one_byte_(true), length_(0), buffer8_(nullptr) {}
State() [2/2]
v8::internal::StringComparator::State::State (const State &) [delete]
Member Function Documentation
Advance()
void v8::internal::StringComparator::State::Advance (int consumed, const SharedStringAccessGuardIfNeeded & access_guard)
Definition at line 28 of file string-comparator.cc.
                                                                       {
  DCHECK(consumed <= length_);
  // Still in buffer.
  if (length_ != consumed) {
    if (is_one_byte_) {
      buffer8_ += consumed;
    } else {
      buffer16_ += consumed;
    }
    length_ -= consumed;
    return;
  }
  // Advance state.
  int offset;
  Tagged<String> next = iter_.Next(&offset);
  DCHECK_EQ(0, offset);
  DCHECK(!next.is_null());
  String::VisitFlat(this, next, 0, access_guard);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Tagged< HeapObject >::is_null(), and v8::internal::String::VisitFlat().
Referenced by v8::internal::StringComparator::Equals().
Init()
void v8::internal::StringComparator::State::Init (Tagged< String > string, const SharedStringAccessGuardIfNeeded & access_guard)
Definition at line 12 of file string-comparator.cc.
                                                         {
  Tagged<ConsString> cons_string =
      String::VisitFlat(this, string, 0, access_guard);
  iter_.Reset(cons_string);
  if (!cons_string.is_null()) {
    int offset;
    string = iter_.Next(&offset);
    // We are resetting the iterator with zero offset, so we should never have
    // a per-segment offset.
    DCHECK_EQ(offset, 0);
    String::VisitFlat(this, string, 0, access_guard);
  }
}
References DCHECK_EQ, v8::internal::Tagged< HeapObject >::is_null(), iter_, v8::internal::ConsStringIterator::Next(), v8::internal::ConsStringIterator::Reset(), and v8::internal::String::VisitFlat().
Referenced by v8::internal::StringComparator::Equals().
operator=()
State& v8::internal::StringComparator::State::operator= (const State &) [delete]
VisitOneByteString()
void v8::internal::StringComparator::State::VisitOneByteString (const uint8_t * chars, int length) [inline]
Definition at line 26 of file string-comparator.h.
                                                                     {
      is_one_byte_ = true;
      buffer8_ = chars;
      length_ = length;
    }
References buffer8_, is_one_byte_, v8::internal::length, and length_.
VisitTwoByteString()
void v8::internal::StringComparator::State::VisitTwoByteString (const uint16_t * chars, int length) [inline]
Definition at line 32 of file string-comparator.h.
                                                                      {
      is_one_byte_ = false;
      buffer16_ = chars;
      length_ = length;
    }
References buffer16_, is_one_byte_, v8::internal::length, and length_.
Member Data Documentation
union { ... }
buffer16_
const uint16_t* v8::internal::StringComparator::State::buffer16_
Definition at line 46 of file string-comparator.h.
Referenced by VisitTwoByteString().
buffer8_
const uint8_t* v8::internal::StringComparator::State::buffer8_
Definition at line 45 of file string-comparator.h.
Referenced by v8::internal::StringComparator::Equals(), and VisitOneByteString().
is_one_byte_
bool v8::internal::StringComparator::State::is_one_byte_
Definition at line 42 of file string-comparator.h.
Referenced by v8::internal::StringComparator::Equals(), VisitOneByteString(), and VisitTwoByteString().
iter_
ConsStringIterator v8::internal::StringComparator::State::iter_
Definition at line 41 of file string-comparator.h.
Referenced by Init().
length_
int v8::internal::StringComparator::State::length_
Definition at line 43 of file string-comparator.h.
Referenced by v8::internal::StringComparator::Equals(), VisitOneByteString(), and VisitTwoByteString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string-comparator.h
/mnt/V8SourceCode/src/objects/string-comparator.cc