v8::internal::JSSegmentIterator Class Reference
#include <js-segment-iterator.h>
Public Member Functions
Handle< String > GranularityAsString (Isolate *isolate) const
void set_granularity (JSSegmenter::Granularity granularity)
JSSegmenter::Granularity granularity () const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSSegmentIterator > Create (Isolate *isolate, DirectHandle< String > input_string, icu::BreakIterator *icu_break_iterator, JSSegmenter::Granularity granularity)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > Next (Isolate *isolate, DirectHandle< JSSegmentIterator > segment_iterator_holder)
Detailed Description
Definition at line 33 of file js-segment-iterator.h.
Member Function Documentation
Create()
MaybeDirectHandle< JSSegmentIterator > v8::internal::JSSegmentIterator::Create (Isolate * isolate, DirectHandle< String > input_string, icu::BreakIterator * icu_break_iterator, JSSegmenter::Granularity granularity) [static]
Definition at line 32 of file js-segment-iterator.cc.
                                        {
  // Clone a copy for both the ownership and not sharing with containing and
  // other calls to the iterator because icu::BreakIterator keep the iteration
  // position internally and cannot be shared across multiple calls to
  // JSSegmentIterator::Create and JSSegments::Containing.
  std::shared_ptr<icu::BreakIterator> break_iterator{
      incoming_break_iterator->clone()};
  DCHECK_NOT_NULL(break_iterator);
  DirectHandle<Map> map(isolate->native_context()->intl_segment_iterator_map(),
                        isolate);
  // 5. Set iterator.[[IteratedStringNextSegmentCodeUnitIndex]] to 0.
  break_iterator->first();
  DirectHandle<Managed<icu::BreakIterator>> managed_break_iterator =
      Managed<icu::BreakIterator>::From(isolate, 0, break_iterator);
  std::shared_ptr<icu::UnicodeString> string =
      std::make_shared<icu::UnicodeString>();
  break_iterator->getText().getText(*string);
  DirectHandle<Managed<icu::UnicodeString>> unicode_string =
      Managed<icu::UnicodeString>::From(isolate, 0, string);
  break_iterator->setText(*string);
  // Now all properties are ready, so we can allocate the result object.
  DirectHandle<JSObject> result = isolate->factory()->NewJSObjectFromMap(map);
  DisallowGarbageCollection no_gc;
  DirectHandle<JSSegmentIterator> segment_iterator =
      Cast<JSSegmentIterator>(result);
  segment_iterator->set_flags(0);
  segment_iterator->set_granularity(granularity);
  segment_iterator->set_icu_break_iterator(*managed_break_iterator);
  segment_iterator->set_raw_string(*input_string);
  segment_iterator->set_unicode_string(*unicode_string);
  return segment_iterator;
}
References DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), granularity(), v8::internal::Isolate::native_context(), v8::internal::Factory::NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::unicode_string.
Referenced by v8::internal::BUILTIN().
granularity()
JSSegmenter::Granularity v8::internal::JSSegmentIterator::granularity () const [inline]
Definition at line 44 of file js-segment-iterator-inl.h.
                                                                   {
  return GranularityBits::decode(flags());
}
References v8::internal::flags.
Referenced by Create(), and GranularityAsString().
GranularityAsString()
Handle< String > v8::internal::JSSegmentIterator::GranularityAsString (Isolate * isolate) const
Definition at line 27 of file js-segment-iterator.cc.
                                                                            {
  return JSSegmenter::GetGranularityString(isolate, granularity());
}
References v8::internal::JSSegmenter::GetGranularityString(), and granularity().
Next()
MaybeDirectHandle< JSReceiver > v8::internal::JSSegmentIterator::Next (Isolate * isolate, DirectHandle< JSSegmentIterator > segment_iterator_holder) [static]
Definition at line 75 of file js-segment-iterator.cc.
                                                                        {
  // Sketches of ideas for future performance improvements, roughly in order
  // of difficulty:
  // - Add a fast path for grapheme segmentation of one-byte strings that
  // entirely skips calling into ICU.
  // - When we enter this function, perform a batch of calls into ICU and
  // stash away the results, so the next couple of invocations can access
  // them from a (Torque?) builtin without calling into C++.
  // - Implement compiler support for escape-analyzing the JSSegmentDataObject
  // and avoid allocating it when possible.
  // TODO(v8:14681): We StackCheck here to break execution in the event of an
  // interrupt. Ordinarily in JS loops, this stack check should already be
  // occurring, however some loops implemented within CodeStubAssembler and
  // Torque builtins do not currently implement these checks. A preferable
  // solution which would benefit other iterators implemented in C++ include:
  // 1) Performing the stack check in CEntry, which would provide a solution
  // for all methods implemented in C++.
  //
  // 2) Rewriting the loop to include an outer loop, which performs periodic
  // stack checks every N loop bodies (where N is some arbitrary heuristic
  // selected to allow short loop counts to run with few interruptions).
  STACK_CHECK(isolate, MaybeDirectHandle<JSReceiver>());
  Factory* factory = isolate->factory();
  icu::BreakIterator* icu_break_iterator =
      segment_iterator->icu_break_iterator()->raw();
  // 5. Let startIndex be iterator.[[IteratedStringNextSegmentCodeUnitIndex]].
  int32_t start_index = icu_break_iterator->current();
  // 6. Let endIndex be ! FindBoundary(segmenter, string, startIndex, after).
  int32_t end_index = icu_break_iterator->next();
  // 7. If endIndex is not finite, then
  if (end_index == icu::BreakIterator::DONE) {
    // a. Return ! CreateIterResultObject(undefined, true).
    return factory->NewJSIteratorResult(isolate->factory()->undefined_value(),
                                        true);
  }
  // 8. Set iterator.[[IteratedStringNextSegmentCodeUnitIndex]] to endIndex.
  // 9. Let segmentData be ! CreateSegmentDataObject(segmenter, string,
  // startIndex, endIndex).
  DirectHandle<JSSegmentDataObject> segment_data;
  if (segment_iterator->granularity() == JSSegmenter::Granularity::GRAPHEME &&
      start_index == end_index - 1) {
    // Fast path: use cached segment string and skip avoidable handle creations.
    DirectHandle<String> segment;
    uint16_t code = segment_iterator->raw_string()->Get(start_index);
    if (code > unibrow::Latin1::kMaxChar) {
      segment = factory->LookupSingleCharacterStringFromCode(code);
    }
    DirectHandle<Number> index;
    if (!Smi::IsValid(start_index)) index = factory->NewHeapNumber(start_index);
    DirectHandle<Map> map(
        isolate->native_context()->intl_segment_data_object_map(), isolate);
    segment_data = Cast<JSSegmentDataObject>(factory->NewJSObjectFromMap(map));
    Tagged<JSSegmentDataObject> raw = *segment_data;
    DisallowHeapAllocation no_gc;
    // We can skip write barriers because {segment_data} is the last object
    // that was allocated.
    raw->set_segment(code <= unibrow::Latin1::kMaxChar
                         ? ReadOnlyRoots(isolate).single_character_string(code)
                         : *segment,
                     SKIP_WRITE_BARRIER);
    raw->set_index(
        Smi::IsValid(start_index) ? Smi::FromInt(start_index) : *index,
        SKIP_WRITE_BARRIER);
    raw->set_input(segment_iterator->raw_string(), SKIP_WRITE_BARRIER);
  } else {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, segment_data,
        JSSegments::CreateSegmentDataObject(
            isolate, segment_iterator->granularity(), icu_break_iterator,
            direct_handle(segment_iterator->raw_string(), isolate),
            *segment_iterator->unicode_string()->raw(), start_index,
            end_index));
  }
  // 10. Return ! CreateIterResultObject(segmentData, false).
  return factory->NewJSIteratorResult(segment_data, false);
}
References ASSIGN_RETURN_ON_EXCEPTION, code, v8::internal::JSSegments::CreateSegmentDataObject(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::JSSegmenter::GRAPHEME, v8::internal::index, v8::internal::Smi::IsValid(), unibrow::Latin1::kMaxChar, v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), v8::internal::Isolate::native_context(), v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::Factory::NewJSIteratorResult(), v8::internal::Factory::NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, and STACK_CHECK.
Referenced by v8::internal::BUILTIN().
set_granularity()
kUnicodeStringOffset void v8::internal::JSSegmentIterator::set_granularity (JSSegmenter::Granularity granularity) [inline]
Definition at line 36 of file js-segment-iterator-inl.h.
                                        {
  DCHECK(GranularityBits::is_valid(granularity));
  int hints = flags();
  hints = GranularityBits::update(hints, granularity);
  set_flags(hints);
}
References v8::internal::DCHECK(), and v8::internal::flags.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-segment-iterator.h
/mnt/V8SourceCode/src/objects/js-segment-iterator-inl.h
/mnt/V8SourceCode/src/objects/js-segment-iterator.cc