v8::internal::compiler::ArmOperandConverter Class Reference
Public Member Functions
ArmOperandConverter (CodeGenerator *gen, Instruction *instr)
SBit OutputSBit () const
Operand InputImmediate (size_t index) const
Operand InputOperand2 (size_t first_index)
MemOperand InputOffset (size_t *first_index)
MemOperand InputOffset (size_t first_index=0)
Operand ToImmediate (InstructionOperand *operand) const
MemOperand ToMemOperand (InstructionOperand *op) const
MemOperand SlotToMemOperand (int slot) const
NeonMemOperand NeonInputOperand (size_t first_index)
Additional Inherited Members
Detailed Description
Definition at line 36 of file code-generator-arm.cc.
Constructor & Destructor Documentation
ArmOperandConverter()
v8::internal::compiler::ArmOperandConverter::ArmOperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 38 of file code-generator-arm.cc.
      : InstructionOperandConverter(gen, instr) {}
Member Function Documentation
InputImmediate()
Operand v8::internal::compiler::ArmOperandConverter::InputImmediate (size_t index) const [inline]
Definition at line 57 of file code-generator-arm.cc.
                                             {
    return ToImmediate(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToImmediate().
Referenced by InputOperand2().
InputOffset() [1/2]
MemOperand v8::internal::compiler::ArmOperandConverter::InputOffset (size_t * first_index) [inline]
Definition at line 93 of file code-generator-arm.cc.
                                              {
    const size_t index = *first_index;
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_None:
      case kMode_Operand2_I:
      case kMode_Operand2_R:
      case kMode_Operand2_R_ASR_I:
      case kMode_Operand2_R_ASR_R:
      case kMode_Operand2_R_LSL_R:
      case kMode_Operand2_R_LSR_I:
      case kMode_Operand2_R_LSR_R:
      case kMode_Operand2_R_ROR_I:
      case kMode_Operand2_R_ROR_R:
        break;
      case kMode_Operand2_R_LSL_I:
        *first_index += 3;
        return MemOperand(InputRegister(index + 0), InputRegister(index + 1),
                          LSL, InputInt32(index + 2));
      case kMode_Offset_RI:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputInt32(index + 1));
      case kMode_Offset_RR:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputRegister(index + 1));
      case kMode_Root:
        *first_index += 1;
        return MemOperand(kRootRegister, InputInt32(index));
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kRootRegister, v8::internal::LSL, v8::internal::compiler::Instruction::opcode(), and v8::internal::UNREACHABLE().
Referenced by InputOffset().
InputOffset() [2/2]
MemOperand v8::internal::compiler::ArmOperandConverter::InputOffset (size_t first_index = 0) [inline]
Definition at line 124 of file code-generator-arm.cc.
                                                 {
    return InputOffset(&first_index);
  }
References InputOffset().
InputOperand2()
Operand v8::internal::compiler::ArmOperandConverter::InputOperand2 (size_t first_index) [inline]
Definition at line 61 of file code-generator-arm.cc.
                                            {
    const size_t index = first_index;
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_None:
      case kMode_Offset_RI:
      case kMode_Offset_RR:
      case kMode_Root:
        break;
      case kMode_Operand2_I:
        return InputImmediate(index + 0);
      case kMode_Operand2_R:
        return Operand(InputRegister(index + 0));
      case kMode_Operand2_R_ASR_I:
        return Operand(InputRegister(index + 0), ASR, InputInt5(index + 1));
      case kMode_Operand2_R_ASR_R:
        return Operand(InputRegister(index + 0), ASR, InputRegister(index + 1));
      case kMode_Operand2_R_LSL_I:
        return Operand(InputRegister(index + 0), LSL, InputInt5(index + 1));
      case kMode_Operand2_R_LSL_R:
        return Operand(InputRegister(index + 0), LSL, InputRegister(index + 1));
      case kMode_Operand2_R_LSR_I:
        return Operand(InputRegister(index + 0), LSR, InputInt5(index + 1));
      case kMode_Operand2_R_LSR_R:
        return Operand(InputRegister(index + 0), LSR, InputRegister(index + 1));
      case kMode_Operand2_R_ROR_I:
        return Operand(InputRegister(index + 0), ROR, InputInt5(index + 1));
      case kMode_Operand2_R_ROR_R:
        return Operand(InputRegister(index + 0), ROR, InputRegister(index + 1));
    }
    UNREACHABLE();
  }
References v8::internal::ASR, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, InputImmediate(), v8::internal::compiler::InstructionOperandConverter::InputInt5(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::LSL, v8::internal::LSR, v8::internal::compiler::Instruction::opcode(), v8::internal::ROR, and v8::internal::UNREACHABLE().
NeonInputOperand()
NeonMemOperand v8::internal::compiler::ArmOperandConverter::NeonInputOperand (size_t first_index) [inline]
Definition at line 160 of file code-generator-arm.cc.
                                                      {
    const size_t index = first_index;
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_Operand2_R:
        return NeonMemOperand(InputRegister(index + 0));
      default:
        break;
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::Instruction::opcode(), and v8::internal::UNREACHABLE().
OutputSBit()
SBit v8::internal::compiler::ArmOperandConverter::OutputSBit () const [inline]
Definition at line 41 of file code-generator-arm.cc.
                          {
    switch (instr_->flags_mode()) {
      case kFlags_branch:
      case kFlags_conditional_branch:
      case kFlags_deoptimize:
      case kFlags_set:
      case kFlags_conditional_set:
      case kFlags_trap:
      case kFlags_select:
        return SetCC;
      case kFlags_none:
        return LeaveCC;
    }
    UNREACHABLE();
  }
References v8::internal::compiler::Instruction::flags_mode(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::kFlags_branch, v8::internal::compiler::kFlags_conditional_branch, v8::internal::compiler::kFlags_conditional_set, v8::internal::compiler::kFlags_deoptimize, v8::internal::compiler::kFlags_none, v8::internal::compiler::kFlags_select, v8::internal::compiler::kFlags_set, v8::internal::compiler::kFlags_trap, v8::internal::LeaveCC, v8::internal::SetCC, and v8::internal::UNREACHABLE().
SlotToMemOperand()
MemOperand v8::internal::compiler::ArmOperandConverter::SlotToMemOperand (int slot) const [inline]
Definition at line 155 of file code-generator-arm.cc.
                                              {
    FrameOffset offset = frame_access_state()->GetFrameOffset(slot);
    return MemOperand(offset.from_stack_pointer() ? sp : fp, offset.offset());
  }
References v8::internal::compiler::InstructionOperandConverter::frame_access_state(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), and v8::internal::compiler::FrameOffset::offset().
Referenced by ToMemOperand().
ToImmediate()
Operand v8::internal::compiler::ArmOperandConverter::ToImmediate (InstructionOperand * operand) const [inline]
Definition at line 128 of file code-generator-arm.cc.
                                                         {
    Constant constant = ToConstant(operand);
    switch (constant.type()) {
      case Constant::kInt32:
        return Operand(constant.ToInt32(), constant.rmode());
      case Constant::kFloat32:
        return Operand::EmbeddedNumber(constant.ToFloat32());
      case Constant::kFloat64:
        return Operand::EmbeddedNumber(constant.ToFloat64().value());
      case Constant::kExternalReference:
        return Operand(constant.ToExternalReference());
      case Constant::kInt64:
      case Constant::kCompressedHeapObject:
      case Constant::kHeapObject:
      // TODO(dcarney): loading RPO constants on arm.
      case Constant::kRpoNumber:
        break;
    }
    UNREACHABLE();
  }
References v8::internal::Operand::EmbeddedNumber(), v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::compiler::Constant::kExternalReference, v8::internal::compiler::Constant::kFloat32, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kHeapObject, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::Constant::kRpoNumber, v8::internal::compiler::Constant::rmode(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToExternalReference(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::type(), v8::internal::UNREACHABLE(), and v8::base::Double::value().
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), and InputImmediate().
ToMemOperand()
MemOperand v8::internal::compiler::ArmOperandConverter::ToMemOperand (InstructionOperand * op) const [inline]
Definition at line 149 of file code-generator-arm.cc.
                                                        {
    DCHECK_NOT_NULL(op);
    DCHECK(op->IsStackSlot() || op->IsFPStackSlot());
    return SlotToMemOperand(AllocatedOperand::cast(op)->index());
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and SlotToMemOperand().
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::CodeGenerator::MoveTempLocationTo(), v8::internal::compiler::CodeGenerator::MoveToTempLocation(), v8::internal::compiler::CodeGenerator::Pop(), and v8::internal::compiler::CodeGenerator::Push().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/arm/code-generator-arm.cc