v8::internal::HeapUtils Class Reference
#include <heap-utils.h>
Static Public Member Functions
static Heap * GetOwnerHeap (Tagged< HeapObject > object)
Detailed Description
Definition at line 15 of file heap-utils.h.
Member Function Documentation
GetOwnerHeap()
Heap * v8::internal::HeapUtils::GetOwnerHeap (Tagged< HeapObject > object) [inline], [static]
Definition at line 16 of file heap-utils-inl.h.
                                                       {
  return MemoryChunk::FromHeapObject(object)->GetHeap();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::GetHeap().
Referenced by v8::internal::Heap::IsFreeSpaceValid(), and v8::internal::ConcurrentMarking::RunMajor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap-utils.h
/mnt/V8SourceCode/src/heap/heap-utils-inl.h