v8::internal::OutBuffer< Char > Class Template Reference
Public Member Functions
OutBuffer (AccountingAllocator *allocator)
template<typename SrcChar >
requires (sizeof(Char) >=sizeof(SrcChar)) inline void AppendCharacter(SrcChar c)
template<typename SrcChar >
requires (sizeof(Char) >=sizeof(SrcChar)) void Append(const SrcChar *chars
DCHECK_GE (SegmentFreeChars(), length)
CopyChars (cur_, chars, length)
void EnsureCapacity (size_t size)
size_t length () const
template<typename Dst >
void CopyTo (Dst *dst)
Public Attributes
size_t length
cur_ = length
Private Member Functions
V8_NOINLINE V8_PRESERVE_MOST void Extend (size_t min_size)
size_t SegmentFreeChars () const
size_t StackBufferLength () const
size_t CurSegmentLength () const
size_t SegmentCapacity (size_t segment)
size_t CurSegmentCapacity ()
void ReduceCurrentCapacity (size_t size)
bool ZoneUsed () const
Private Attributes
AccountingAllocator * allocator_
Char stack_buffer_ [kStackBufferSize]
size_t stack_buffer_size_
Char * cur_
Char * segment_end_
std::optional< Zone > zone_
std::optional< ZoneList< base::Vector< Char > > > segments_
Static Private Attributes
static constexpr uint32_t kInitialSegmentSize = 2 * KB
static constexpr uint32_t kMaxSegmentSize = 32 * KB
static constexpr uint8_t kInitialSegmentSizeHighestBit
static constexpr uint8_t kMaxSegmentSizeHighestBit
static constexpr uint8_t kNumVariableSegments
static constexpr size_t kStackBufferSize = 256
Detailed Description
template<typename Char>
class v8::internal::OutBuffer< Char >
Definition at line 1805 of file json-stringifier.cc.
Constructor & Destructor Documentation
OutBuffer()
template<typename Char >
v8::internal::OutBuffer< Char >::OutBuffer (AccountingAllocator * allocator) [inline], [explicit]
Definition at line 1807 of file json-stringifier.cc.
                                                     : allocator_(allocator) {
    cur_ = stack_buffer_;
    segment_end_ = cur_ + kStackBufferSize;
  }
References v8::internal::OutBuffer< Char >::cur_, v8::internal::OutBuffer< Char >::kStackBufferSize, v8::internal::OutBuffer< Char >::segment_end_, and v8::internal::OutBuffer< Char >::stack_buffer_.
Member Function Documentation
CopyChars()
template<typename Char >
v8::internal::OutBuffer< Char >::CopyChars (cur_ , chars , length)
Referenced by v8::internal::OutBuffer< Char >::CopyTo().
CopyTo()
template<typename Char >
template<typename Dst >
void v8::internal::OutBuffer< Char >::CopyTo (Dst * dst) [inline]
Definition at line 1848 of file json-stringifier.cc.
                        {
    if (ZoneUsed()) {
      // Copy stack segment.
      CopyChars(dst, stack_buffer_, stack_buffer_size_);
      dst += stack_buffer_size_;
      // Copy full segments.
      DCHECK_GT(segments_->length(), 0);
      for (int i = 0; i < segments_->length() - 1; i++) {
        base::Vector<Char> segment = segments_.value()[i];
        size_t segment_length = segment.size();
        CopyChars(dst, segment.begin(), segment_length);
        dst += segment_length;
      }
      // Copy last (partially filled) segment.
      base::Vector<Char> segment = segments_->last();
      CopyChars(dst, segment.begin(), CurSegmentLength());
    } else {
      // Copy (partially filled) stack segment.
      CopyChars(dst, stack_buffer_, StackBufferLength());
    }
  }
References v8::base::Vector< T >::begin(), v8::internal::OutBuffer< Char >::CopyChars(), v8::internal::OutBuffer< Char >::CurSegmentLength(), DCHECK_GT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::OutBuffer< Char >::segments_, v8::base::Vector< T >::size(), v8::internal::OutBuffer< Char >::stack_buffer_, v8::internal::OutBuffer< Char >::stack_buffer_size_, v8::internal::OutBuffer< Char >::StackBufferLength(), and v8::internal::OutBuffer< Char >::ZoneUsed().
CurSegmentCapacity()
template<typename Char >
size_t v8::internal::OutBuffer< Char >::CurSegmentCapacity () [inline], [private]
Definition at line 1911 of file json-stringifier.cc.
                                        {
    DCHECK(ZoneUsed());
    DCHECK_GT(segments_->length(), 0);
    return segments_->last().size();
  }
References v8::internal::DCHECK(), DCHECK_GT, v8::internal::OutBuffer< Char >::segments_, and v8::internal::OutBuffer< Char >::ZoneUsed().
Referenced by v8::internal::OutBuffer< Char >::EnsureCapacity().
CurSegmentLength()
template<typename Char >
size_t v8::internal::OutBuffer< Char >::CurSegmentLength () const [inline], [private]
Definition at line 1903 of file json-stringifier.cc.
                                            {
    DCHECK(ZoneUsed());
    return cur_ - segments_->last().begin();
  }
References v8::internal::OutBuffer< Char >::cur_, v8::internal::DCHECK(), v8::internal::OutBuffer< Char >::segments_, and v8::internal::OutBuffer< Char >::ZoneUsed().
Referenced by v8::internal::OutBuffer< Char >::CopyTo(), v8::internal::OutBuffer< Char >::Extend(), and v8::internal::OutBuffer< Char >::length().
DCHECK_GE()
template<typename Char >
v8::internal::OutBuffer< Char >::DCHECK_GE (SegmentFreeChars() , length)
Referenced by v8::internal::OutBuffer< Char >::EnsureCapacity(), and v8::internal::OutBuffer< Char >::requires().
EnsureCapacity()
template<typename Char >
void v8::internal::OutBuffer< Char >::EnsureCapacity (size_t size) [inline]
Definition at line 1826 of file json-stringifier.cc.
                                   {
#ifdef DEBUG
    current_requested_capacity_ = size;
#endif
    if (V8_LIKELY(size <= SegmentFreeChars())) return;
    Extend(size);
    DCHECK_GE(CurSegmentCapacity(), size);
  }
References v8::internal::OutBuffer< Char >::CurSegmentCapacity(), v8::internal::OutBuffer< Char >::DCHECK_GE(), v8::internal::OutBuffer< Char >::Extend(), v8::internal::OutBuffer< Char >::SegmentFreeChars(), size(), and V8_LIKELY.
Extend()
template<typename Char >
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::OutBuffer< Char >::Extend (size_t min_size) [inline], [private]
Definition at line 1883 of file json-stringifier.cc.
                                                            {
    if (ZoneUsed()) {
      segments_->last().Truncate(CurSegmentLength());
    } else {
      stack_buffer_size_ = StackBufferLength();
      zone_.emplace(allocator_, kJsonStringifierZoneName);
      segments_.emplace(1, &zone_.value());
    }
    const size_t new_segment_size =
        std::max(min_size, SegmentCapacity(segments_->length()));
    segments_->Add(zone_->AllocateVector<Char>(new_segment_size),
                   &zone_.value());
    cur_ = segments_->last().begin();
    segment_end_ = segments_->last().end();
  }
References v8::internal::OutBuffer< Char >::allocator_, v8::internal::OutBuffer< Char >::cur_, v8::internal::OutBuffer< Char >::CurSegmentLength(), v8::internal::kJsonStringifierZoneName, v8::internal::OutBuffer< Char >::segment_end_, v8::internal::OutBuffer< Char >::SegmentCapacity(), v8::internal::OutBuffer< Char >::segments_, v8::internal::OutBuffer< Char >::stack_buffer_size_, v8::internal::OutBuffer< Char >::StackBufferLength(), v8::internal::OutBuffer< Char >::zone_, and v8::internal::OutBuffer< Char >::ZoneUsed().
Referenced by v8::internal::OutBuffer< Char >::EnsureCapacity().
length()
template<typename Char >
size_t v8::internal::OutBuffer< Char >::length () const [inline]
Definition at line 1834 of file json-stringifier.cc.
                        {
    if (ZoneUsed()) {
      DCHECK_GT(segments_->length(), 0);
      size_t length = stack_buffer_size_;
      for (int i = 0; i < segments_->length() - 1; i++) {
        length += segments_->at(i).size();
      }
      length += CurSegmentLength();
      return length;
    } else {
      return StackBufferLength();
    }
  }
References v8::internal::OutBuffer< Char >::CurSegmentLength(), DCHECK_GT, v8::internal::OutBuffer< Char >::length, v8::internal::OutBuffer< Char >::segments_, v8::internal::OutBuffer< Char >::stack_buffer_size_, v8::internal::OutBuffer< Char >::StackBufferLength(), and v8::internal::OutBuffer< Char >::ZoneUsed().
ReduceCurrentCapacity()
template<typename Char >
void v8::internal::OutBuffer< Char >::ReduceCurrentCapacity (size_t size) [inline], [private]
Definition at line 1916 of file json-stringifier.cc.
                                                    {
#ifdef DEBUG
    DCHECK_LE(size, current_requested_capacity_);
    current_requested_capacity_ -= size;
#endif
  }
References DCHECK_LE, and size().
Referenced by v8::internal::OutBuffer< Char >::requires().
requires() [1/2]
template<typename Char >
template<typename SrcChar >
v8::internal::OutBuffer< Char >::requires (sizeof(Char) >=sizeof(SrcChar)) [inline]
Definition at line 1812 of file json-stringifier.cc.
                                            {
    ReduceCurrentCapacity(1);
    DCHECK_GE(SegmentFreeChars(), 1);
    *cur_++ = c;
  }
References v8::internal::OutBuffer< Char >::cur_, v8::internal::OutBuffer< Char >::DCHECK_GE(), v8::internal::OutBuffer< Char >::ReduceCurrentCapacity(), and v8::internal::OutBuffer< Char >::SegmentFreeChars().
requires() [2/2]
template<typename Char >
template<typename SrcChar >
v8::internal::OutBuffer< Char >::requires (sizeof(Char) >=sizeof(SrcChar)) const
SegmentCapacity()
template<typename Char >
size_t v8::internal::OutBuffer< Char >::SegmentCapacity (size_t segment) [inline], [private]
Definition at line 1907 of file json-stringifier.cc.
                                                   {
    return 1u << std::min<size_t>(segment + kInitialSegmentSizeHighestBit,
                                  kMaxSegmentSizeHighestBit);
  }
References v8::internal::OutBuffer< Char >::kInitialSegmentSizeHighestBit, and v8::internal::OutBuffer< Char >::kMaxSegmentSizeHighestBit.
Referenced by v8::internal::OutBuffer< Char >::Extend().
SegmentFreeChars()
template<typename Char >
size_t v8::internal::OutBuffer< Char >::SegmentFreeChars () const [inline], [private]
Definition at line 1898 of file json-stringifier.cc.
{ return segment_end_ - cur_; }
References v8::internal::OutBuffer< Char >::cur_, and v8::internal::OutBuffer< Char >::segment_end_.
Referenced by v8::internal::OutBuffer< Char >::EnsureCapacity(), and v8::internal::OutBuffer< Char >::requires().
StackBufferLength()
template<typename Char >
size_t v8::internal::OutBuffer< Char >::StackBufferLength () const [inline], [private]
Definition at line 1899 of file json-stringifier.cc.
                                             {
    DCHECK(!ZoneUsed());
    return cur_ - stack_buffer_;
  }
References v8::internal::OutBuffer< Char >::cur_, v8::internal::DCHECK(), v8::internal::OutBuffer< Char >::stack_buffer_, and v8::internal::OutBuffer< Char >::ZoneUsed().
Referenced by v8::internal::OutBuffer< Char >::CopyTo(), v8::internal::OutBuffer< Char >::Extend(), and v8::internal::OutBuffer< Char >::length().
ZoneUsed()
template<typename Char >
bool v8::internal::OutBuffer< Char >::ZoneUsed () const [inline], [private]
Definition at line 1922 of file json-stringifier.cc.
{ return zone_.has_value(); }
References v8::internal::OutBuffer< Char >::zone_.
Referenced by v8::internal::OutBuffer< Char >::CopyTo(), v8::internal::OutBuffer< Char >::CurSegmentCapacity(), v8::internal::OutBuffer< Char >::CurSegmentLength(), v8::internal::OutBuffer< Char >::Extend(), v8::internal::OutBuffer< Char >::length(), and v8::internal::OutBuffer< Char >::StackBufferLength().
Member Data Documentation
allocator_
template<typename Char >
AccountingAllocator* v8::internal::OutBuffer< Char >::allocator_ [private]
Definition at line 1924 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::Extend().
cur_ [1/2]
template<typename Char >
v8::internal::OutBuffer< Char >::cur_ = length
Definition at line 1824 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::CurSegmentLength(), v8::internal::OutBuffer< Char >::Extend(), v8::internal::OutBuffer< Char >::OutBuffer(), v8::internal::OutBuffer< Char >::requires(), v8::internal::OutBuffer< Char >::SegmentFreeChars(), and v8::internal::OutBuffer< Char >::StackBufferLength().
cur_ [2/2]
template<typename Char >
Char* v8::internal::OutBuffer< Char >::cur_ [private]
Definition at line 1927 of file json-stringifier.cc.
kInitialSegmentSize
template<typename Char >
constexpr uint32_t v8::internal::OutBuffer< Char >::kInitialSegmentSize = 2 * KB [static], [constexpr], [private]
Definition at line 1871 of file json-stringifier.cc.
kInitialSegmentSizeHighestBit
template<typename Char >
constexpr uint8_t v8::internal::OutBuffer< Char >::kInitialSegmentSizeHighestBit [static], [constexpr], [private]
Initial value:
=
      kBitsPerInt - base::bits::CountLeadingZeros32(kInitialSegmentSize) - 1
Definition at line 1875 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::SegmentCapacity().
kMaxSegmentSize
template<typename Char >
constexpr uint32_t v8::internal::OutBuffer< Char >::kMaxSegmentSize = 32 * KB [static], [constexpr], [private]
Definition at line 1872 of file json-stringifier.cc.
kMaxSegmentSizeHighestBit
template<typename Char >
constexpr uint8_t v8::internal::OutBuffer< Char >::kMaxSegmentSizeHighestBit [static], [constexpr], [private]
Initial value:
=
      kBitsPerInt - base::bits::CountLeadingZeros32(kMaxSegmentSize) - 1
Definition at line 1877 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::SegmentCapacity().
kNumVariableSegments
template<typename Char >
constexpr uint8_t v8::internal::OutBuffer< Char >::kNumVariableSegments [static], [constexpr], [private]
Initial value:
=
      kMaxSegmentSizeHighestBit - kInitialSegmentSizeHighestBit
Definition at line 1879 of file json-stringifier.cc.
kStackBufferSize
template<typename Char >
constexpr size_t v8::internal::OutBuffer< Char >::kStackBufferSize = 256 [static], [constexpr], [private]
Definition at line 1881 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::OutBuffer().
length
template<typename Char >
size_t v8::internal::OutBuffer< Char >::length
Initial value:
{
    ReduceCurrentCapacity(length)
Definition at line 1820 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::length().
segment_end_
template<typename Char >
Char* v8::internal::OutBuffer< Char >::segment_end_ [private]
Definition at line 1928 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::Extend(), v8::internal::OutBuffer< Char >::OutBuffer(), and v8::internal::OutBuffer< Char >::SegmentFreeChars().
segments_
template<typename Char >
std::optional<ZoneList<base::Vector<Char> > > v8::internal::OutBuffer< Char >::segments_ [private]
Definition at line 1930 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::CopyTo(), v8::internal::OutBuffer< Char >::CurSegmentCapacity(), v8::internal::OutBuffer< Char >::CurSegmentLength(), v8::internal::OutBuffer< Char >::Extend(), and v8::internal::OutBuffer< Char >::length().
stack_buffer_
template<typename Char >
Char v8::internal::OutBuffer< Char >::stack_buffer_[kStackBufferSize] [private]
Definition at line 1925 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::CopyTo(), v8::internal::OutBuffer< Char >::OutBuffer(), and v8::internal::OutBuffer< Char >::StackBufferLength().
stack_buffer_size_
template<typename Char >
size_t v8::internal::OutBuffer< Char >::stack_buffer_size_ [private]
Definition at line 1926 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::CopyTo(), v8::internal::OutBuffer< Char >::Extend(), and v8::internal::OutBuffer< Char >::length().
zone_
template<typename Char >
std::optional<Zone> v8::internal::OutBuffer< Char >::zone_ [private]
Definition at line 1929 of file json-stringifier.cc.
Referenced by v8::internal::OutBuffer< Char >::Extend(), and v8::internal::OutBuffer< Char >::ZoneUsed().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-stringifier.cc