v8_inspector::InjectedScript::ProtocolPromiseHandler Class Reference
Static Public Member Functions
static void add (V8InspectorSessionImpl *session, v8::Local< v8::Context > context, v8::Local< v8::Value > value, int executionContextId, const String16 &objectGroup, std::unique_ptr< WrapOptions > wrapOptions, bool replMode, bool throwOnSideEffect, std::weak_ptr< EvaluateCallback > callback)
Private Member Functions
ProtocolPromiseHandler (PromiseHandlerTracker::Id id, V8InspectorSessionImpl *session, int executionContextId, const String16 &objectGroup, std::unique_ptr< WrapOptions > wrapOptions, bool replMode, bool throwOnSideEffect, std::weak_ptr< EvaluateCallback > callback, v8::Local< v8::Promise > evaluationResult)
void thenCallback (v8::Local< v8::Value > value)
void catchCallback (v8::Local< v8::Value > result)
Static Private Member Functions
static v8::Local< v8::String > GetDotReplResultString (v8::Isolate *isolate)
static void thenCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
static void catchCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
static void cleanup (const v8::WeakCallbackInfo< PromiseHandlerTracker::Id > &data)
Private Attributes
V8InspectorImpl * m_inspector
int m_sessionId
int m_contextGroupId
int m_executionContextId
String16 m_objectGroup
std::unique_ptr< WrapOptions > m_wrapOptions
bool m_replMode
bool m_throwOnSideEffect
std::weak_ptr< EvaluateCallback > m_callback
v8::Global< v8::Promise > m_evaluationResult
Friends
class PromiseHandlerTracker
Detailed Description
Definition at line 96 of file injected-script.cc.
Constructor & Destructor Documentation
ProtocolPromiseHandler()
v8_inspector::InjectedScript::ProtocolPromiseHandler::ProtocolPromiseHandler (PromiseHandlerTracker::Id id, V8InspectorSessionImpl * session, int executionContextId, const String16 & objectGroup, std::unique_ptr< WrapOptions > wrapOptions, bool replMode, bool throwOnSideEffect, std::weak_ptr< EvaluateCallback > callback, v8::Local< v8::Promise > evaluationResult) [inline], [private]
Definition at line 207 of file injected-script.cc.
      : m_inspector(session->inspector()),
        m_sessionId(session->sessionId()),
        m_contextGroupId(session->contextGroupId()),
        m_executionContextId(executionContextId),
        m_objectGroup(objectGroup),
        m_wrapOptions(std::move(wrapOptions)),
        m_replMode(replMode),
        m_throwOnSideEffect(throwOnSideEffect),
        m_callback(std::move(callback)),
        m_evaluationResult(m_inspector->isolate(), evaluationResult) {
    m_evaluationResult.SetWeak(reinterpret_cast<PromiseHandlerTracker::Id*>(id),
                               cleanup, v8::WeakCallbackType::kParameter);
  }
References cleanup(), v8::kParameter, m_evaluationResult, and v8::PersistentBase< T >::SetWeak().
Member Function Documentation
add()
static void v8_inspector::InjectedScript::ProtocolPromiseHandler::add (V8InspectorSessionImpl * session, v8::Local< v8::Context > context, v8::Local< v8::Value > value, int executionContextId, const String16 & objectGroup, std::unique_ptr< WrapOptions > wrapOptions, bool replMode, bool throwOnSideEffect, std::weak_ptr< EvaluateCallback > callback) [inline], [static]
Definition at line 98 of file injected-script.cc.
                                                          {
    InjectedScript::ContextScope scope(session, executionContextId);
    Response response = scope.initialize();
    if (!response.IsSuccess()) return;
    v8::Local<v8::Promise> promise;
    v8::Local<v8::Promise::Resolver> resolver;
    if (value->IsPromise()) {
      // If value is a promise, we can chain the handlers directly onto `value`.
      promise = value.As<v8::Promise>();
    } else {
      // Otherwise we do `Promise.resolve(value)`.
      CHECK(!replMode);
      if (!v8::Promise::Resolver::New(context).ToLocal(&resolver)) {
        EvaluateCallback::sendFailure(callback, scope.injectedScript(),
                                      Response::InternalError());
        return;
      }
      if (!resolver->Resolve(context, value).FromMaybe(false)) {
        EvaluateCallback::sendFailure(callback, scope.injectedScript(),
                                      Response::InternalError());
        return;
      }
      promise = resolver->GetPromise();
    }
    V8InspectorImpl* inspector = session->inspector();
    PromiseHandlerTracker::Id handlerId =
        inspector->promiseHandlerTracker().create(
            session, executionContextId, objectGroup, std::move(wrapOptions),
            replMode, throwOnSideEffect, callback, promise);
    v8::Local<v8::Number> data =
        v8::Number::New(inspector->isolate(), handlerId);
    v8::Local<v8::Function> thenCallbackFunction =
        v8::Function::New(context, thenCallback, data, 0,
                          v8::ConstructorBehavior::kThrow)
            .ToLocalChecked();
    v8::Local<v8::Function> catchCallbackFunction =
        v8::Function::New(context, catchCallback, data, 0,
                          v8::ConstructorBehavior::kThrow)
            .ToLocalChecked();
    if (promise->Then(context, thenCallbackFunction, catchCallbackFunction)
            .IsEmpty()) {
      // Re-initialize after returning from JS.
      Response new_response = scope.initialize();
      if (!new_response.IsSuccess()) return;
      EvaluateCallback::sendFailure(callback, scope.injectedScript(),
                                    Response::InternalError());
    }
  }
References catchCallback(), CHECK, v8_inspector::InjectedScript::context(), v8_inspector::PromiseHandlerTracker::create(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::V8InspectorSessionImpl::inspector(), v8::MaybeLocal< T >::IsEmpty(), v8_inspector::V8InspectorImpl::isolate(), v8::kThrow, v8::Number::New(), v8::Promise::Resolver::New(), v8::Function::New(), v8_inspector::V8InspectorImpl::promiseHandlerTracker(), v8_inspector::EvaluateCallback::sendFailure(), v8::Promise::Then(), thenCallback(), and v8::internal::value.
Referenced by v8_inspector::InjectedScript::addPromiseCallback().
catchCallback() [1/2]
static void v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback (const v8::FunctionCallbackInfo< v8::Value > & info) [inline], [static], [private]
Definition at line 186 of file injected-script.cc.
                                                                         {
    PromiseHandlerTracker::Id handlerId =
        static_cast<PromiseHandlerTracker::Id>(
            info.Data().As<v8::Number>()->Value());
    PromiseHandlerTracker& handlerTracker =
        static_cast<V8InspectorImpl*>(
            v8::debug::GetInspector(info.GetIsolate()))
            ->promiseHandlerTracker();
    // We currently store the handlers with the inspector. In rare cases the
    // inspector dies (discarding the handler) with the micro task queue
    // running after. Don't do anything in that case.
    ProtocolPromiseHandler* handler = handlerTracker.get(handlerId);
    if (!handler) return;
    v8::Local<v8::Value> value =
        info.Length() > 0 ? info[0]
                          : v8::Undefined(info.GetIsolate()).As<v8::Value>();
    handler->catchCallback(value);
    handlerTracker.discard(handlerId,
                           PromiseHandlerTracker::DiscardReason::kFulfilled);
  }
References catchCallback(), v8::FunctionCallbackInfo< T >::Data(), v8_inspector::PromiseHandlerTracker::discard(), v8_inspector::PromiseHandlerTracker::get(), v8::debug::GetInspector(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8_inspector::PromiseHandlerTracker::kFulfilled, v8::FunctionCallbackInfo< T >::Length(), v8::Undefined(), and v8::internal::value.
Referenced by add(), and catchCallback().
catchCallback() [2/2]
void v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback (v8::Local< v8::Value > result) [inline], [private]
Definition at line 287 of file injected-script.cc.
                                              {
    // Hold strongly onto m_evaluationResult now to prevent `cleanup` from
    // running in case any code below triggers GC.
    m_evaluationResult.ClearWeak();
    V8InspectorSessionImpl* session =
        m_inspector->sessionById(m_contextGroupId, m_sessionId);
    if (!session) return;
    InjectedScript::ContextScope scope(session, m_executionContextId);
    Response response = scope.initialize();
    if (!response.IsSuccess()) return;
    std::unique_ptr<protocol::Runtime::RemoteObject> wrappedValue;
    response = scope.injectedScript()->wrapObject(
        result, m_objectGroup, *m_wrapOptions, &wrappedValue);
    if (!response.IsSuccess()) {
      EvaluateCallback::sendFailure(m_callback, scope.injectedScript(),
                                    response);
      return;
    }
    v8::Isolate* isolate = session->inspector()->isolate();
    v8::MaybeLocal<v8::Message> maybeMessage =
        m_evaluationResult.IsEmpty()
            ? v8::MaybeLocal<v8::Message>()
            : v8::debug::GetMessageFromPromise(m_evaluationResult.Get(isolate));
    v8::Local<v8::Message> message;
    // In case a MessageObject was attached to the rejected promise, we
    // construct the exception details from the message object. Otherwise
    // we try to capture a fresh stack trace.
    if (maybeMessage.ToLocal(&message)) {
      v8::Local<v8::Value> exception = result;
      if (!m_throwOnSideEffect) {
        session->inspector()->client()->dispatchError(scope.context(), message,
                                                      exception);
      }
      std::unique_ptr<protocol::Runtime::ExceptionDetails> exceptionDetails;
      response = scope.injectedScript()->createExceptionDetails(
          message, exception, m_objectGroup, &exceptionDetails);
      if (!response.IsSuccess()) {
        EvaluateCallback::sendFailure(m_callback, scope.injectedScript(),
                                      response);
        return;
      }
      EvaluateCallback::sendSuccess(m_callback, scope.injectedScript(),
                                    std::move(wrappedValue),
                                    std::move(exceptionDetails));
      return;
    }
    String16 messageString;
    std::unique_ptr<V8StackTraceImpl> stack;
    if (result->IsNativeError()) {
      messageString =
          " " +
          toProtocolString(isolate,
                           result->ToDetailString(isolate->GetCurrentContext())
                               .ToLocalChecked());
      v8::Local<v8::StackTrace> stackTrace =
          v8::Exception::GetStackTrace(result);
      if (!stackTrace.IsEmpty()) {
        stack = m_inspector->debugger()->createStackTrace(stackTrace);
      }
    }
    if (!stack) {
      stack = m_inspector->debugger()->captureStackTrace(true);
    }
    // REPL mode implicitly handles the script like an async function.
    // Do not prepend the '(in promise)' prefix for these exceptions since that
    // would be confusing for the user. The stringified error is part of the
    // exception and does not need to be added in REPL mode, otherwise it would
    // be printed twice.
    String16 exceptionDetailsText =
        m_replMode ? "Uncaught" : "Uncaught (in promise)" + messageString;
    std::unique_ptr<protocol::Runtime::ExceptionDetails> exceptionDetails =
        protocol::Runtime::ExceptionDetails::create()
            .setExceptionId(m_inspector->nextExceptionId())
            .setText(exceptionDetailsText)
            .setLineNumber(stack && !stack->isEmpty() ? stack->topLineNumber()
                                                      : 0)
            .setColumnNumber(
                stack && !stack->isEmpty() ? stack->topColumnNumber() : 0)
            .build();
    response = scope.injectedScript()->addExceptionToDetails(
        result, exceptionDetails.get(), m_objectGroup);
    if (!response.IsSuccess()) {
      EvaluateCallback::sendFailure(m_callback, scope.injectedScript(),
                                    response);
      return;
    }
    if (stack)
      exceptionDetails->setStackTrace(
          stack->buildInspectorObjectImpl(m_inspector->debugger()));
    if (stack && !stack->isEmpty())
      exceptionDetails->setScriptId(
          String16::fromInteger(stack->topScriptId()));
    EvaluateCallback::sendSuccess(m_callback, scope.injectedScript(),
                                  std::move(wrappedValue),
                                  std::move(exceptionDetails));
  }
References v8_inspector::InjectedScript::addExceptionToDetails(), v8_inspector::V8Debugger::captureStackTrace(), v8::PersistentBase< T >::ClearWeak(), v8_inspector::V8InspectorImpl::client(), v8_inspector::InjectedScript::Scope::context(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::V8Debugger::createStackTrace(), v8_inspector::V8InspectorImpl::debugger(), v8_inspector::V8InspectorClient::dispatchError(), v8_inspector::String16::fromInteger(), v8::PersistentBase< T >::Get(), v8::Isolate::GetCurrentContext(), v8::debug::GetMessageFromPromise(), v8::Exception::GetStackTrace(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::V8InspectorSessionImpl::inspector(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::V8InspectorImpl::isolate(), m_callback, m_contextGroupId, m_evaluationResult, m_executionContextId, m_inspector, m_objectGroup, m_replMode, m_sessionId, m_throwOnSideEffect, m_wrapOptions, v8_inspector::V8InspectorImpl::nextExceptionId(), v8::base::internal::result, v8_inspector::EvaluateCallback::sendFailure(), v8_inspector::EvaluateCallback::sendSuccess(), v8_inspector::V8InspectorImpl::sessionById(), v8::internal::stack, v8::MaybeLocal< T >::ToLocal(), v8_inspector::toProtocolString(), and v8_inspector::InjectedScript::wrapObject().
cleanup()
static void v8_inspector::InjectedScript::ProtocolPromiseHandler::cleanup (const v8::WeakCallbackInfo< PromiseHandlerTracker::Id > & data) [inline], [static], [private]
Definition at line 228 of file injected-script.cc.
                                                               {
    auto id = reinterpret_cast<PromiseHandlerTracker::Id>(data.GetParameter());
    PromiseHandlerTracker& handlerTracker =
        static_cast<V8InspectorImpl*>(
            v8::debug::GetInspector(data.GetIsolate()))
            ->promiseHandlerTracker();
    // {discard} deletes the {ProtocolPromiseHandler} which resets the handle.
    handlerTracker.discard(
        id, PromiseHandlerTracker::DiscardReason::kPromiseCollected);
  }
References v8_inspector::PromiseHandlerTracker::discard(), v8::debug::GetInspector(), v8::WeakCallbackInfo< T >::GetIsolate(), v8::WeakCallbackInfo< T >::GetParameter(), and v8_inspector::PromiseHandlerTracker::kPromiseCollected.
Referenced by ProtocolPromiseHandler().
GetDotReplResultString()
static v8::Local<v8::String> v8_inspector::InjectedScript::ProtocolPromiseHandler::GetDotReplResultString (v8::Isolate * isolate) [inline], [static], [private]
Definition at line 158 of file injected-script.cc.
                                                                      {
    // TODO(szuend): Cache the string in a v8::Persistent handle.
    return v8::String::NewFromOneByte(
               isolate, reinterpret_cast<const uint8_t*>(".repl_result"))
        .ToLocalChecked();
  }
References v8::String::NewFromOneByte().
Referenced by thenCallback().
thenCallback() [1/2]
static void v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback (const v8::FunctionCallbackInfo< v8::Value > & info) [inline], [static], [private]
Definition at line 165 of file injected-script.cc.
                                                                        {
    PromiseHandlerTracker::Id handlerId =
        static_cast<PromiseHandlerTracker::Id>(
            info.Data().As<v8::Number>()->Value());
    PromiseHandlerTracker& handlerTracker =
        static_cast<V8InspectorImpl*>(
            v8::debug::GetInspector(info.GetIsolate()))
            ->promiseHandlerTracker();
    // We currently store the handlers with the inspector. In rare cases the
    // inspector dies (discarding the handler) with the micro task queue
    // running after. Don't do anything in that case.
    ProtocolPromiseHandler* handler = handlerTracker.get(handlerId);
    if (!handler) return;
    v8::Local<v8::Value> value =
        info.Length() > 0 ? info[0]
                          : v8::Undefined(info.GetIsolate()).As<v8::Value>();
    handler->thenCallback(value);
    handlerTracker.discard(handlerId,
                           PromiseHandlerTracker::DiscardReason::kFulfilled);
  }
References v8::FunctionCallbackInfo< T >::Data(), v8_inspector::PromiseHandlerTracker::discard(), v8_inspector::PromiseHandlerTracker::get(), v8::debug::GetInspector(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8_inspector::PromiseHandlerTracker::kFulfilled, v8::FunctionCallbackInfo< T >::Length(), thenCallback(), v8::Undefined(), and v8::internal::value.
Referenced by add(), and thenCallback().
thenCallback() [2/2]
void v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback (v8::Local< v8::Value > value) [inline], [private]
Definition at line 240 of file injected-script.cc.
                                            {
    // We don't need the m_evaluationResult in the `thenCallback`, but we also
    // don't want `cleanup` running in case we re-enter JS.
    m_evaluationResult.Reset();
    V8InspectorSessionImpl* session =
        m_inspector->sessionById(m_contextGroupId, m_sessionId);
    if (!session) return;
    InjectedScript::ContextScope scope(session, m_executionContextId);
    Response response = scope.initialize();
    if (!response.IsSuccess()) return;
    // In REPL mode the result is additionally wrapped in an object.
    // The evaluation result can be found at ".repl_result".
    v8::Local<v8::Value> result = value;
    if (m_replMode) {
      v8::Local<v8::Object> object;
      if (!result->ToObject(scope.context()).ToLocal(&object)) {
        EvaluateCallback::sendFailure(m_callback, scope.injectedScript(),
                                      response);
        return;
      }
      v8::Local<v8::String> name =
          GetDotReplResultString(m_inspector->isolate());
      if (!object->Get(scope.context(), name).ToLocal(&result)) {
        EvaluateCallback::sendFailure(m_callback, scope.injectedScript(),
                                      response);
        return;
      }
    }
    if (m_objectGroup == "console") {
      scope.injectedScript()->setLastEvaluationResult(result);
    }
    std::unique_ptr<protocol::Runtime::RemoteObject> wrappedValue;
    response = scope.injectedScript()->wrapObject(
        result, m_objectGroup, *m_wrapOptions, &wrappedValue);
    if (!response.IsSuccess()) {
      EvaluateCallback::sendFailure(m_callback, scope.injectedScript(),
                                    response);
      return;
    }
    EvaluateCallback::sendSuccess(m_callback, scope.injectedScript(),
                                  std::move(wrappedValue), nullptr);
  }
References v8_inspector::InjectedScript::Scope::context(), v8::Object::Get(), GetDotReplResultString(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::V8InspectorImpl::isolate(), m_callback, m_contextGroupId, m_evaluationResult, m_executionContextId, m_inspector, m_objectGroup, m_replMode, m_sessionId, m_wrapOptions, name, v8::PersistentBase< T >::Reset(), v8::base::internal::result, v8_inspector::EvaluateCallback::sendFailure(), v8_inspector::EvaluateCallback::sendSuccess(), v8_inspector::V8InspectorImpl::sessionById(), v8_inspector::InjectedScript::setLastEvaluationResult(), v8::MaybeLocal< T >::ToLocal(), v8::internal::value, and v8_inspector::InjectedScript::wrapObject().
Friends And Related Function Documentation
PromiseHandlerTracker
friend class PromiseHandlerTracker [friend]
Definition at line 156 of file injected-script.cc.
Member Data Documentation
m_callback
std::weak_ptr<EvaluateCallback> v8_inspector::InjectedScript::ProtocolPromiseHandler::m_callback [private]
Definition at line 396 of file injected-script.cc.
Referenced by catchCallback(), v8_inspector::PromiseHandlerTracker::sendFailure(), and thenCallback().
m_contextGroupId
int v8_inspector::InjectedScript::ProtocolPromiseHandler::m_contextGroupId [private]
Definition at line 390 of file injected-script.cc.
Referenced by catchCallback(), v8_inspector::PromiseHandlerTracker::sendFailure(), and thenCallback().
m_evaluationResult
v8::Global<v8::Promise> v8_inspector::InjectedScript::ProtocolPromiseHandler::m_evaluationResult [private]
Definition at line 397 of file injected-script.cc.
Referenced by catchCallback(), ProtocolPromiseHandler(), and thenCallback().
m_executionContextId
int v8_inspector::InjectedScript::ProtocolPromiseHandler::m_executionContextId [private]
Definition at line 391 of file injected-script.cc.
Referenced by catchCallback(), v8_inspector::PromiseHandlerTracker::sendFailure(), and thenCallback().
m_inspector
V8InspectorImpl* v8_inspector::InjectedScript::ProtocolPromiseHandler::m_inspector [private]
Definition at line 388 of file injected-script.cc.
Referenced by catchCallback(), v8_inspector::PromiseHandlerTracker::sendFailure(), and thenCallback().
m_objectGroup
String16 v8_inspector::InjectedScript::ProtocolPromiseHandler::m_objectGroup [private]
Definition at line 392 of file injected-script.cc.
Referenced by catchCallback(), and thenCallback().
m_replMode
bool v8_inspector::InjectedScript::ProtocolPromiseHandler::m_replMode [private]
Definition at line 394 of file injected-script.cc.
Referenced by catchCallback(), and thenCallback().
m_sessionId
int v8_inspector::InjectedScript::ProtocolPromiseHandler::m_sessionId [private]
Definition at line 389 of file injected-script.cc.
Referenced by catchCallback(), v8_inspector::PromiseHandlerTracker::sendFailure(), and thenCallback().
m_throwOnSideEffect
bool v8_inspector::InjectedScript::ProtocolPromiseHandler::m_throwOnSideEffect [private]
Definition at line 395 of file injected-script.cc.
Referenced by catchCallback().
m_wrapOptions
std::unique_ptr<WrapOptions> v8_inspector::InjectedScript::ProtocolPromiseHandler::m_wrapOptions [private]
Definition at line 393 of file injected-script.cc.
Referenced by catchCallback(), and thenCallback().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/injected-script.cc