v8::internal::DateParser::DateStringTokenizer< Char > Class Template Reference
Public Member Functions
DateStringTokenizer (InputReader< Char > *in)
DateToken Next ()
DateToken Peek ()
bool SkipSymbol (char symbol)
Private Member Functions
DateToken Scan ()
Private Attributes
InputReader< Char > * in_
DateToken next_
Detailed Description
template<typename Char>
class v8::internal::DateParser::DateStringTokenizer< Char >
Definition at line 221 of file dateparser.h.
Constructor & Destructor Documentation
DateStringTokenizer()
template<typename Char >
v8::internal::DateParser::DateStringTokenizer< Char >::DateStringTokenizer (InputReader< Char > * in) [inline], [explicit]
Definition at line 223 of file dateparser.h.
        : in_(in), next_(Scan()) {}
Member Function Documentation
Next()
template<typename Char >
DateToken v8::internal::DateParser::DateStringTokenizer< Char >::Next () [inline]
Definition at line 225 of file dateparser.h.
                     {
      DateToken result = next_;
      next_ = Scan();
      return result;
    }
References v8::internal::DateParser::DateStringTokenizer< Char >::next_, v8::base::internal::result, and v8::internal::DateParser::DateStringTokenizer< Char >::Scan().
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
Peek()
template<typename Char >
DateToken v8::internal::DateParser::DateStringTokenizer< Char >::Peek () [inline]
Definition at line 231 of file dateparser.h.
{ return next_; }
References v8::internal::DateParser::DateStringTokenizer< Char >::next_.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
Scan()
template<typename Char >
DateParser::DateToken v8::internal::DateParser::DateStringTokenizer< CharType >::Scan () [private]
Definition at line 184 of file dateparser-inl.h.
                                                                  {
  int pre_pos = in_->position();
  if (in_->IsEnd()) return DateToken::EndOfInput();
  if (in_->IsAsciiDigit()) {
    int n = in_->ReadUnsignedNumeral();
    int length = in_->position() - pre_pos;
    return DateToken::Number(n, length);
  }
  if (in_->Skip(':')) return DateToken::Symbol(':');
  if (in_->Skip('-')) return DateToken::Symbol('-');
  if (in_->Skip('+')) return DateToken::Symbol('+');
  if (in_->Skip('.')) return DateToken::Symbol('.');
  if (in_->Skip(')')) return DateToken::Symbol(')');
  if (in_->IsAsciiAlphaOrAbove() && !in_->IsWhiteSpaceChar()) {
    DCHECK_EQ(KeywordTable::kPrefixLength, 3);
    uint32_t buffer[3] = {0, 0, 0};
    int length = in_->ReadWord(buffer, 3);
    int index = KeywordTable::Lookup(buffer, length);
    return DateToken::Keyword(KeywordTable::GetType(index),
                              KeywordTable::GetValue(index), length);
  }
  if (in_->SkipWhiteSpace()) {
    return DateToken::WhiteSpace(in_->position() - pre_pos);
  }
  if (in_->SkipParentheses()) {
    return DateToken::Unknown();
  }
  in_->Next();
  return DateToken::Unknown();
}
References DCHECK_EQ, v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), v8::internal::index, and v8::internal::length.
Referenced by v8::internal::DateParser::DateStringTokenizer< Char >::Next(), and v8::internal::DateParser::DateStringTokenizer< Char >::SkipSymbol().
SkipSymbol()
template<typename Char >
bool v8::internal::DateParser::DateStringTokenizer< Char >::SkipSymbol (char symbol) [inline]
Definition at line 232 of file dateparser.h.
                                 {
      if (next_.IsSymbol(symbol)) {
        next_ = Scan();
        return true;
      }
      return false;
    }
References v8::internal::DateParser::DateToken::IsSymbol(), v8::internal::DateParser::DateStringTokenizer< Char >::next_, and v8::internal::DateParser::DateStringTokenizer< Char >::Scan().
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
Member Data Documentation
in_
template<typename Char >
InputReader<Char>* v8::internal::DateParser::DateStringTokenizer< Char >::in_ [private]
Definition at line 243 of file dateparser.h.
next_
template<typename Char >
DateToken v8::internal::DateParser::DateStringTokenizer< Char >::next_ [private]
Definition at line 244 of file dateparser.h.
Referenced by v8::internal::DateParser::DateStringTokenizer< Char >::Next(), v8::internal::DateParser::DateStringTokenizer< Char >::Peek(), and v8::internal::DateParser::DateStringTokenizer< Char >::SkipSymbol().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/date/dateparser.h
/mnt/V8SourceCode/src/date/dateparser-inl.h