v8::internal::StackFrame Class Reference
#include <frames.h>
Classes
struct State
Public Types
enum Type { NO_FRAME_TYPE = 0
, STACK_FRAME_TYPE_LIST =(DECLARE_TYPE) NUMBER_OF_TYPES
, MANUAL
 }
enum JsFrameMarker { INNER_JSENTRY_FRAME = (0 << kSmiTagSize) | kSmiTag
, OUTERMOST_JSENTRY_FRAME = (1 << kSmiTagSize) | kSmiTag
 }
enum PrintMode { OVERVIEW
, DETAILS
 }
Public Member Functions
StackFrame (const StackFrame &original) V8_NOEXCEPT
bool is_entry () const
bool is_construct_entry () const
bool is_exit () const
bool is_optimized_js () const
bool is_unoptimized_js () const
bool is_interpreted () const
bool is_baseline () const
bool is_maglev () const
bool is_turbofan_js () const
bool is_builtin () const
bool is_internal () const
bool is_builtin_continuation () const
bool is_javascript_builtin_continuation () const
bool is_javascript_builtin_with_catch_continuation () const
bool is_construct () const
bool is_fast_construct () const
bool is_builtin_exit () const
bool is_api_accessor_exit () const
bool is_api_callback_exit () const
bool is_irregexp () const
bool is_javascript () const
Address sp () const
Address fp () const
Address callee_fp () const
Address callee_pc () const
Address caller_sp () const
Address pc () const
bool is_profiler_entry_frame () const
bool is_stack_exit_frame () const
Address unauthenticated_pc () const
Address maybe_unauthenticated_pc () const
bool InFastCCall () const
Address constant_pool () const
void set_constant_pool (Address constant_pool)
Address * pc_address () const
Address * constant_pool_address () const
StackFrameId id () const
StackHandler * top_handler () const
virtual Type type () const =0
virtual Tagged< HeapObject > unchecked_code () const =0
V8_EXPORT_PRIVATE Tagged< Code > LookupCode () const
V8_EXPORT_PRIVATE std::pair< Tagged< Code >, int > LookupCodeAndOffset () const
V8_EXPORT_PRIVATE Tagged< GcSafeCode > GcSafeLookupCode () const
V8_EXPORT_PRIVATE std::pair< Tagged< GcSafeCode >, int > GcSafeLookupCodeAndOffset () const
virtual void Iterate (RootVisitor *v) const =0
void IteratePc (RootVisitor *v, Address *constant_pool_address, Tagged< GcSafeCode > holder) const
virtual void Print (StringStream *accumulator, PrintMode mode, int index) const
Isolate * isolate () const
void operator= (const StackFrame &original)=delete
Static Public Member Functions
static constexpr int32_t TypeToMarker (Type type)
static constexpr Type MarkerToType (intptr_t marker)
static constexpr bool IsTypeMarker (uintptr_t function_or_marker)
static bool IsJavaScript (Type t)
static Address unauthenticated_pc (Address *pc_address)
static Address maybe_unauthenticated_pc (Address *pc_address)
static void SetReturnAddressLocationResolver (ReturnAddressLocationResolver resolver)
static Address ReadPC (Address *pc_address)
static Address * ResolveReturnAddressLocation (Address *pc_address)
Protected Member Functions
StackFrame (StackFrameIteratorBase *iterator)
virtual Address GetCallerStackPointer () const =0
Protected Attributes
const StackFrameIteratorBase *const iterator_
Private Member Functions
virtual void ComputeCallerState (State *state) const =0
virtual Type GetCallerState (State *state) const
Private Attributes
Isolate *const isolate_
State state_
Static Private Attributes
static ReturnAddressLocationResolver return_address_location_resolver_
static const intptr_t kIsolateTag = 1
Friends
class StackFrameIterator
class StackFrameIteratorBase
class StackHandlerIterator
class StackFrameIteratorForProfiler
Detailed Description
Definition at line 150 of file frames.h.
Member Enumeration Documentation
JsFrameMarker
enum v8::internal::StackFrame::JsFrameMarker
Enumerator
INNER_JSENTRY_FRAME
OUTERMOST_JSENTRY_FRAME
Definition at line 166 of file frames.h.
                     {
    INNER_JSENTRY_FRAME = (0 << kSmiTagSize) | kSmiTag,
    OUTERMOST_JSENTRY_FRAME = (1 << kSmiTagSize) | kSmiTag
  };
PrintMode
enum v8::internal::StackFrame::PrintMode
Enumerator
OVERVIEW
DETAILS
Definition at line 369 of file frames.h.
{ OVERVIEW, DETAILS };
Type
enum v8::internal::StackFrame::Type
Enumerator
NO_FRAME_TYPE
STACK_FRAME_TYPE_LIST
MANUAL
Definition at line 153 of file frames.h.
            {
    NO_FRAME_TYPE = 0,
    STACK_FRAME_TYPE_LIST(DECLARE_TYPE) NUMBER_OF_TYPES,
    // Used by FrameScope to indicate that the stack frame is constructed
    // manually and the FrameScope does not need to emit code.
    MANUAL
  };
Constructor & Destructor Documentation
StackFrame() [1/2]
v8::internal::StackFrame::StackFrame (const StackFrame & original) [inline]
Definition at line 223 of file frames.h.
      : iterator_(nullptr),
        isolate_(original.isolate_),
        state_(original.state_) {}
StackFrame() [2/2]
v8::internal::StackFrame::StackFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 71 of file frames-inl.h.
    : iterator_(iterator), isolate_(iterator_->isolate()) {}
Member Function Documentation
callee_fp()
Address v8::internal::StackFrame::callee_fp () const [inline]
Definition at line 295 of file frames.h.
{ return state_.callee_fp; }
References v8::internal::StackFrame::State::callee_fp, and state_.
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal(), and v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue().
callee_pc()
Address v8::internal::StackFrame::callee_pc () const [inline]
Definition at line 296 of file frames.h.
{ return state_.callee_pc; }
References v8::internal::StackFrame::State::callee_pc, and state_.
Referenced by v8::internal::CommonFrame::HasTaggedOutgoingParams().
caller_sp()
Address v8::internal::StackFrame::caller_sp () const [inline]
Definition at line 297 of file frames.h.
{ return GetCallerStackPointer(); }
References GetCallerStackPointer().
Referenced by v8::internal::CommonFrame::ComputeCallerState(), v8::internal::NativeFrame::ComputeCallerState(), v8::internal::ExitFrame::ComputeCallerState(), v8::internal::CommonFrameWithJSLinkage::GetParameterSlot(), and id().
ComputeCallerState()
virtual void v8::internal::StackFrame::ComputeCallerState (State * state) const [private], [pure virtual]
Implemented in v8::internal::ExitFrame, v8::internal::EntryFrame, v8::internal::NativeFrame, and v8::internal::CommonFrame.
Referenced by v8::internal::StackFrameIteratorForProfiler::AdvanceOneFrame(), and GetCallerState().
constant_pool()
Address v8::internal::StackFrame::constant_pool () const [inline]
Definition at line 319 of file frames.h.
{ return *constant_pool_address(); }
References constant_pool_address().
Referenced by set_constant_pool().
constant_pool_address()
Address* v8::internal::StackFrame::constant_pool_address () const [inline]
Definition at line 326 of file frames.h.
                                         {
    return state_.constant_pool_address;
  }
References v8::internal::StackFrame::State::constant_pool_address, and state_.
Referenced by constant_pool(), v8::internal::TypedFrame::Iterate(), v8::internal::TypedFrameWithJSLinkage::Iterate(), v8::internal::ExitFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::ConstructFrame::Iterate(), IteratePc(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), and set_constant_pool().
fp()
Address v8::internal::StackFrame::fp () const [inline]
Definition at line 294 of file frames.h.
{ return state_.fp; }
References v8::internal::StackFrame::State::fp, and state_.
Referenced by v8::internal::ProfilerEventsProcessor::AddCurrentStack(), v8::internal::StackFrameIterator::Advance(), v8::internal::StackFrameIteratorForProfiler::Advance(), v8::internal::StackFrameIteratorForProfiler::AdvanceOneFrame(), v8::internal::BuiltinExitFrame::argc_slot_object(), v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::CommonFrame::caller_fp(), v8::internal::CommonFrame::caller_pc(), v8::internal::DebugStackTraceIterator::CanBeRestarted(), v8::internal::anonymous_namespace{runtime-object.cc}::CheckExcludedPropertiesAreOnCallerStack(), v8::internal::CommonFrame::ComputeCallerState(), v8::internal::NativeFrame::ComputeCallerState(), v8::internal::ExitFrame::ComputeCallerState(), v8::internal::ExitFrame::ComputeFrameType(), v8::internal::ApiCallbackExitFrame::ComputeParametersCount(), v8::internal::TurbofanJSFrame::ComputeParametersCount(), v8::internal::JavaScriptBuiltinContinuationFrame::ComputeParametersCount(), v8::internal::ExitFrame::ComputeStackPointer(), v8::internal::JavaScriptFrame::context(), v8::internal::ApiCallbackExitFrame::context(), v8::internal::JavaScriptBuiltinContinuationFrame::context(), v8::internal::Deoptimizer::DebuggerInspectableFrame(), v8::internal::ExitFrame::FillState(), v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc}::FindInterpreterEntryFramePointer(), v8::internal::JavaScriptBuiltinContinuationFrame::function(), v8::internal::JavaScriptFrame::function_slot_object(), v8::internal::Accessors::FunctionGetArguments(), v8::internal::JavaScriptFrame::GetActualArgumentCount(), v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), v8::internal::CommonFrame::GetCallerStackPointer(), v8::internal::JavaScriptFrame::GetCallerStackPointer(), v8::internal::EntryFrame::GetCallerState(), v8::internal::CommonFrame::GetExpressionAddress(), v8::internal::UnoptimizedJSFrame::GetExpressionAddress(), v8::internal::BuiltinExitFrame::GetParameter(), v8::internal::ApiCallbackExitFrame::GetParameter(), v8::internal::JavaScriptBuiltinContinuationFrame::GetSPToFPDelta(), v8::internal::TickSample::GetStackSample(), v8::internal::ExitFrame::GetStateForFramePointer(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue(), v8::internal::StackFrameIteratorForProfiler::HasValidExitIfEntryFrame(), v8::internal::ApiAccessorExitFrame::holder_slot(), v8::internal::CommonFrameWithJSLinkage::IsConstructFrame(), v8::internal::ApiCallbackExitFrame::IsConstructor(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::ConstructFrame::Iterate(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), v8::internal::FrameFunctionIterator::MaterializeFunction(), v8::internal::BuiltinExitFrame::new_target_slot_object(), v8::internal::Isolate::NotifyExceptionPropagationCallback(), v8::internal::ApiAccessorExitFrame::property_name_slot(), v8::internal::ApiCallbackExitFrame::receiver(), v8::internal::ApiAccessorExitFrame::receiver_slot(), v8::internal::BuiltinExitFrame::receiver_slot_object(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::SetException(), v8::internal::UnoptimizedJSFrame::SetFeedbackVector(), v8::internal::ApiCallbackExitFrame::target_slot(), v8::internal::BuiltinExitFrame::target_slot_object(), v8::internal::TranslatedState::TranslatedState(), and v8::internal::Isolate::UnwindAndFindHandler().
GcSafeLookupCode()
Tagged< GcSafeCode > v8::internal::StackFrame::GcSafeLookupCode () const
Definition at line 760 of file frames.cc.
                                                      {
  return GcSafeLookupCodeAndOffset().first;
}
References GcSafeLookupCodeAndOffset().
Referenced by v8::internal::TurbofanJSFrame::ComputeParametersCount(), v8::internal::TypedFrameWithJSLinkage::Iterate(), v8::internal::ExitFrame::Iterate(), v8::internal::ConstructFrame::Iterate(), LookupCode(), and v8::internal::Isolate::UnwindAndFindHandler().
GcSafeLookupCodeAndOffset()
std::pair< Tagged< GcSafeCode >, int > v8::internal::StackFrame::GcSafeLookupCodeAndOffset () const
Definition at line 764 of file frames.cc.
          {
  const Address pc = maybe_unauthenticated_pc();
  std::optional<Tagged<GcSafeCode>> result = GetContainingCode(isolate(), pc);
  return {result.value(),
          result.value()->GetOffsetFromInstructionStart(isolate(), pc)};
}
References v8::internal::anonymous_namespace{frames.cc}::GetContainingCode(), isolate(), maybe_unauthenticated_pc(), pc(), and v8::base::internal::result.
Referenced by GcSafeLookupCode(), LookupCodeAndOffset(), and v8::internal::CommonFrameWithJSLinkage::Summarize().
GetCallerStackPointer()
virtual Address v8::internal::StackFrame::GetCallerStackPointer () const [protected], [pure virtual]
Implemented in v8::internal::EntryFrame, v8::internal::JavaScriptFrame, and v8::internal::CommonFrame.
Referenced by caller_sp().
GetCallerState()
StackFrame::Type v8::internal::StackFrame::GetCallerState (State * state) const [private], [virtual]
Reimplemented in v8::internal::EntryFrame.
Definition at line 1071 of file frames.cc.
                                                            {
  ComputeCallerState(state);
  return iterator_->ComputeStackFrameType(state);
}
References ComputeCallerState(), v8::internal::StackFrameIteratorBase::ComputeStackFrameType(), and iterator_.
Referenced by v8::internal::StackFrameIterator::Advance().
id()
StackFrameId v8::internal::StackFrame::id () const [inline]
Definition at line 331 of file frames.h.
{ return static_cast<StackFrameId>(caller_sp()); }
References caller_sp().
Referenced by v8::internal::Debug::CurrentFrameCount(), v8::internal::DebugScope::DebugScope(), v8::internal::DebugStackTraceIterator::Evaluate(), v8::internal::Debug::PrepareRestartFrame(), v8::internal::Debug::RestoreDebug(), and v8::internal::Isolate::UnwindAndFindHandler().
InFastCCall()
bool v8::internal::StackFrame::InFastCCall () const [inline]
Definition at line 317 of file frames.h.
{ return state_.sp == kNullAddress; }
References v8::internal::kNullAddress, v8::internal::StackFrame::State::sp, and state_.
Referenced by IteratePc(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), maybe_unauthenticated_pc(), v8::internal::Isolate::NotifyExceptionPropagationCallback(), sp(), and v8::internal::StackHandlerIterator::StackHandlerIterator().
is_api_accessor_exit()
bool v8::internal::StackFrame::is_api_accessor_exit () const [inline]
Definition at line 277 of file frames.h.
{ return type() == API_ACCESSOR_EXIT; }
References type().
Referenced by v8::internal::StackFrameIteratorForProfiler::Advance(), and v8::internal::ApiAccessorExitFrame::cast().
is_api_callback_exit()
bool v8::internal::StackFrame::is_api_callback_exit () const [inline]
Definition at line 278 of file frames.h.
{ return type() == API_CALLBACK_EXIT; }
References type().
Referenced by v8::internal::StackFrameIteratorForProfiler::Advance(), and v8::internal::ApiCallbackExitFrame::cast().
is_baseline()
bool v8::internal::StackFrame::is_baseline () const [inline]
Definition at line 241 of file frames.h.
{ return type() == BASELINE; }
References type().
Referenced by v8::internal::BaselineFrame::cast(), v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), v8::internal::anonymous_namespace{runtime-compiler.cc}::GetOsrOffsetAndFunctionForOSR(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::Isolate::UnwindAndFindHandler().
is_builtin()
bool v8::internal::StackFrame::is_builtin () const [inline]
Definition at line 263 of file frames.h.
{ return type() == BUILTIN; }
References v8::internal::BUILTIN(), and type().
Referenced by v8::internal::BuiltinFrame::cast(), and v8::internal::Isolate::GetAbstractPC().
is_builtin_continuation()
bool v8::internal::StackFrame::is_builtin_continuation () const [inline]
Definition at line 265 of file frames.h.
                                       {
    return type() == BUILTIN_CONTINUATION;
  }
References type().
Referenced by v8::internal::BuiltinContinuationFrame::cast().
is_builtin_exit()
bool v8::internal::StackFrame::is_builtin_exit () const [inline]
Definition at line 276 of file frames.h.
{ return type() == BUILTIN_EXIT; }
References type().
Referenced by v8::internal::StackFrameIteratorForProfiler::Advance().
is_construct()
bool v8::internal::StackFrame::is_construct () const [inline]
Definition at line 274 of file frames.h.
{ return type() == CONSTRUCT; }
References type().
Referenced by v8::internal::ConstructFrame::cast().
is_construct_entry()
bool v8::internal::StackFrame::is_construct_entry () const [inline]
Definition at line 230 of file frames.h.
{ return type() == CONSTRUCT_ENTRY; }
References CONSTRUCT_ENTRY, and type().
Referenced by v8::internal::ConstructEntryFrame::cast(), and v8::internal::StackFrameIteratorForProfiler::HasValidExitIfEntryFrame().
is_entry()
bool v8::internal::StackFrame::is_entry () const [inline]
Definition at line 229 of file frames.h.
{ return type() == ENTRY; }
References ENTRY, and type().
Referenced by v8::internal::EntryFrame::cast(), and v8::internal::StackFrameIteratorForProfiler::HasValidExitIfEntryFrame().
is_exit()
bool v8::internal::StackFrame::is_exit () const [inline]
Definition at line 231 of file frames.h.
{ return type() == EXIT; }
References type().
Referenced by v8::internal::StackFrameIteratorForProfiler::Advance(), and v8::internal::ExitFrame::cast().
is_fast_construct()
bool v8::internal::StackFrame::is_fast_construct () const [inline]
Definition at line 275 of file frames.h.
{ return type() == FAST_CONSTRUCT; }
References type().
Referenced by v8::internal::FastConstructFrame::cast().
is_internal()
bool v8::internal::StackFrame::is_internal () const [inline]
Definition at line 264 of file frames.h.
{ return type() == INTERNAL; }
References type().
Referenced by v8::internal::InternalFrame::cast().
is_interpreted()
bool v8::internal::StackFrame::is_interpreted () const [inline]
Definition at line 240 of file frames.h.
{ return type() == INTERPRETED; }
References type().
Referenced by v8::internal::InterpretedFrame::cast(), v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), v8::internal::anonymous_namespace{runtime-compiler.cc}::GetOsrOffsetAndFunctionForOSR(), v8::internal::TickSample::GetStackSample(), v8::internal::RUNTIME_FUNCTION(), v8::internal::RUNTIME_FUNCTION_RETURN_PAIR(), and v8::internal::RedirectActiveFunctions::VisitThread().
is_irregexp()
bool v8::internal::StackFrame::is_irregexp () const [inline]
Definition at line 279 of file frames.h.
{ return type() == IRREGEXP; }
References type().
Referenced by v8::internal::IrregexpFrame::cast().
is_javascript()
bool v8::internal::StackFrame::is_javascript () const [inline]
Definition at line 287 of file frames.h.
{ return IsJavaScript(type()); }
References IsJavaScript(), and type().
Referenced by _v8_internal_Expand_StackTrace(), v8::internal::JavaScriptStackFrameIterator::Advance(), v8::internal::StackFrameIteratorForProfiler::Advance(), v8::internal::Debug::AllFramesOnStackAreBlackboxed(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), v8::internal::JavaScriptFrame::cast(), v8::internal::anonymous_namespace{runtime-object.cc}::CheckExcludedPropertiesAreOnCallerStack(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::FrameInspector::FrameInspector(), v8::internal::Debug::HandleDebugBreak(), v8::internal::DebuggableStackFrameIterator::is_javascript(), v8::internal::FrameInspector::IsJavaScript(), v8::internal::DebuggableStackFrameIterator::IsValidFrame(), v8::internal::Debug::OnException(), v8::internal::Debug::PrepareStep(), v8::internal::JavaScriptFrame::PrintTop(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::DebugStackTraceIterator::UpdateInlineFrameIndexAndResumableFnOnStack().
is_javascript_builtin_continuation()
bool v8::internal::StackFrame::is_javascript_builtin_continuation () const [inline]
Definition at line 268 of file frames.h.
                                                  {
    return type() == JAVASCRIPT_BUILTIN_CONTINUATION;
  }
References type().
Referenced by v8::internal::JavaScriptBuiltinContinuationFrame::cast().
is_javascript_builtin_with_catch_continuation()
bool v8::internal::StackFrame::is_javascript_builtin_with_catch_continuation () const [inline]
Definition at line 271 of file frames.h.
                                                             {
    return type() == JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH;
  }
References type().
Referenced by v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::cast().
is_maglev()
bool v8::internal::StackFrame::is_maglev () const [inline]
Definition at line 242 of file frames.h.
{ return type() == MAGLEV; }
References type().
Referenced by v8::internal::MaglevFrame::cast(), and v8::internal::RUNTIME_FUNCTION().
is_optimized_js()
bool v8::internal::StackFrame::is_optimized_js () const [inline]
Definition at line 232 of file frames.h.
                               {
    static_assert(TURBOFAN_JS == MAGLEV + 1);
    return base::IsInRange(type(), MAGLEV, TURBOFAN_JS);
  }
References type().
Referenced by _v8_internal_Expand_StackTrace(), v8::internal::Deoptimizer::DebuggerInspectableFrame(), v8::internal::DebuggableStackFrameIterator::FrameFunctionCount(), v8::internal::DebugStackTraceIterator::GetReturnValue(), v8::internal::JavaScriptFrame::is_optimized(), and v8::internal::Isolate::UnwindAndFindHandler().
is_profiler_entry_frame()
bool v8::internal::StackFrame::is_profiler_entry_frame () const [inline]
Definition at line 299 of file frames.h.
                                       {
    return state_.is_profiler_entry_frame;
  }
References v8::internal::StackFrame::State::is_profiler_entry_frame, and state_.
Referenced by maybe_unauthenticated_pc().
is_stack_exit_frame()
bool v8::internal::StackFrame::is_stack_exit_frame () const [inline]
Definition at line 302 of file frames.h.
{ return state_.is_stack_exit_frame; }
References v8::internal::StackFrame::State::is_stack_exit_frame, and state_.
Referenced by maybe_unauthenticated_pc().
is_turbofan_js()
bool v8::internal::StackFrame::is_turbofan_js () const [inline]
Definition at line 243 of file frames.h.
{ return type() == TURBOFAN_JS; }
References type().
Referenced by v8::internal::JavaScriptFrame::is_turbofan().
is_unoptimized_js()
bool v8::internal::StackFrame::is_unoptimized_js () const [inline]
Definition at line 236 of file frames.h.
                                 {
    static_assert(BASELINE == INTERPRETED + 1);
    return base::IsInRange(type(), INTERPRETED, BASELINE);
  }
References type().
Referenced by v8::internal::UnoptimizedJSFrame::cast(), and v8::internal::JavaScriptFrame::is_unoptimized().
IsJavaScript()
static bool v8::internal::StackFrame::IsJavaScript (Type t) [inline], [static]
Definition at line 281 of file frames.h.
                                   {
    static_assert(INTERPRETED + 1 == BASELINE);
    static_assert(BASELINE + 1 == MAGLEV);
    static_assert(MAGLEV + 1 == TURBOFAN_JS);
    return t >= INTERPRETED && t <= TURBOFAN_JS;
  }
Referenced by v8::internal::MacroAssembler::EnterFrame(), is_javascript(), and v8::internal::StackFrameIteratorForProfiler::IsValidFrameType().
isolate()
Isolate* v8::internal::StackFrame::isolate () const [inline]
Definition at line 373 of file frames.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::JavaScriptFrame::CollectFunctionAndOffsetForICStats(), v8::internal::CommonFrameWithJSLinkage::ComputeParametersCount(), v8::internal::CommonFrame::context(), v8::internal::Accessors::FunctionGetArguments(), GcSafeLookupCodeAndOffset(), v8::internal::EntryFrame::GetCallerState(), v8::internal::ApiCallbackExitFrame::GetFunction(), v8::internal::JavaScriptFrame::GetFunctions(), v8::internal::ApiCallbackExitFrame::GetFunctionTemplateInfo(), v8::internal::CommonFrameWithJSLinkage::GetParameters(), v8::internal::BuiltinExitFrame::GetParameters(), v8::internal::ApiCallbackExitFrame::GetParameters(), v8::internal::CommonFrame::HasTaggedOutgoingParams(), v8::internal::BuiltinExitFrame::IsConstructor(), v8::internal::ApiCallbackExitFrame::IsConstructor(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), IteratePc(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), LookupCode(), LookupCodeAndOffset(), v8::internal::BuiltinExitFrame::Print(), v8::internal::ApiCallbackExitFrame::Print(), v8::internal::JavaScriptFrame::PrintFunctionAndOffset(), v8::internal::JavaScriptFrame::PrintTop(), v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::SetException(), v8::internal::StackHandlerIterator::StackHandlerIterator(), v8::internal::CommonFrameWithJSLinkage::Summarize(), v8::internal::BuiltinExitFrame::Summarize(), v8::internal::ApiCallbackExitFrame::Summarize(), v8::internal::StubFrame::Summarize(), v8::internal::TranslatedState::TranslatedState(), v8::internal::TurbofanStubWithContextFrame::unchecked_code(), v8::internal::CommonFrameWithJSLinkage::unchecked_code(), v8::internal::EntryFrame::unchecked_code(), v8::internal::ConstructEntryFrame::unchecked_code(), v8::internal::StubFrame::unchecked_code(), and v8::internal::JavaScriptFrame::unchecked_function().
IsTypeMarker()
static constexpr bool v8::internal::StackFrame::IsTypeMarker (uintptr_t function_or_marker) [inline], [static], [constexpr]
Definition at line 213 of file frames.h.
                                                                   {
    static_assert(kSmiTag == 0);
    static_assert((std::numeric_limits<uintptr_t>::max() >> kSmiTagSize) >
                  Type::NUMBER_OF_TYPES);
    return (function_or_marker & kSmiTagMask) == kSmiTag &&
           function_or_marker < (Type::NUMBER_OF_TYPES << kSmiTagSize);
  }
References v8::internal::kSmiTag, v8::internal::kSmiTagMask, and v8::internal::kSmiTagSize.
Referenced by v8::internal::StackFrameIterator::ComputeStackFrameType(), v8::internal::StackFrameIteratorForProfiler::ComputeStackFrameType(), v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc(), v8::internal::StackFrameIteratorForProfiler::IsNoFrameBytecodeHandlerPc(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::CommonFrame::IterateExpressions(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), and MarkerToType().
Iterate()
virtual void v8::internal::StackFrame::Iterate (RootVisitor * v) const [pure virtual]
Implemented in v8::internal::IrregexpFrame, v8::internal::ConstructFrame, v8::internal::InternalFrame, v8::internal::TurbofanJSFrame, v8::internal::MaglevFrame, v8::internal::ExitFrame, v8::internal::EntryFrame, v8::internal::NativeFrame, v8::internal::JavaScriptFrame, v8::internal::TypedFrameWithJSLinkage, v8::internal::TypedFrame, and v8::internal::TurbofanStubWithContextFrame.
IteratePc()
void v8::internal::StackFrame::IteratePc (RootVisitor * v, Address * constant_pool_address, Tagged< GcSafeCode > holder) const
Definition at line 783 of file frames.cc.
                                                            {
  const Address old_pc = maybe_unauthenticated_pc();
  DCHECK_GE(old_pc, holder->InstructionStart(isolate(), old_pc));
  DCHECK_LT(old_pc, holder->InstructionEnd(isolate(), old_pc));
  // Keep the old pc offset before visiting the code since we need it to
  // calculate the new pc after a potential InstructionStream move.
  const uintptr_t pc_offset_from_start = old_pc - holder->instruction_start();
  // Visit.
  Tagged<GcSafeCode> visited_holder = holder;
  PtrComprCageBase code_cage_base{isolate()->code_cage_base()};
  const Tagged<Object> old_istream =
      holder->raw_instruction_stream(code_cage_base);
  Tagged<Object> visited_istream = old_istream;
  v->VisitRunningCode(FullObjectSlot{&visited_holder},
                      FullObjectSlot{&visited_istream});
  if (visited_istream == old_istream) {
    // Note this covers two important cases:
    // 1. the associated InstructionStream object did not move, and
    // 2. `holder` is an embedded builtin and has no InstructionStream.
    return;
  }
  DCHECK(visited_holder->has_instruction_stream());
  // We can only relocate the InstructionStream object when we are able to patch
  // the return address. We only know the location of the return address if the
  // stack pointer is known. This means we cannot relocate InstructionStreams
  // for fast c calls.
  DCHECK(!InFastCCall());
  // Currently we turn off code space compaction fully when performing a GC in a
  // fast C call.
  DCHECK(!isolate()->InFastCCall());
  Tagged<InstructionStream> istream =
      GCSafeCast<InstructionStream>(visited_istream, isolate()->heap());
  const Address new_pc = istream->instruction_start() + pc_offset_from_start;
  // TODO(v8:10026): avoid replacing a signed pointer.
  PointerAuthentication::ReplacePC(pc_address(), new_pc, kSystemPointerSize);
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL && constant_pool_address != nullptr) {
    *constant_pool_address = istream->constant_pool();
  }
}
References v8::internal::Isolate::code_cage_base(), constant_pool_address(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, heap(), InFastCCall(), isolate(), v8::internal::kSystemPointerSize, maybe_unauthenticated_pc(), pc_address(), v8::internal::PointerAuthentication::ReplacePC(), V8_EMBEDDED_CONSTANT_POOL_BOOL, and v8::internal::RootVisitor::VisitRunningCode().
Referenced by v8::internal::TypedFrame::Iterate(), v8::internal::TypedFrameWithJSLinkage::Iterate(), v8::internal::ExitFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::ConstructFrame::Iterate(), and v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame().
LookupCode()
Tagged< Code > v8::internal::StackFrame::LookupCode () const
Definition at line 772 of file frames.cc.
                                          {
  DCHECK_NE(isolate()->heap()->gc_state(), Heap::MARK_COMPACT);
  return GcSafeLookupCode()->UnsafeCastToCode();
}
References DCHECK_NE, GcSafeLookupCode(), heap(), isolate(), and v8::internal::Heap::MARK_COMPACT.
Referenced by v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), v8::internal::anonymous_namespace{runtime-compiler.cc}::GetOsrOffsetAndFunctionForOSR(), v8::internal::CommonFrameWithJSLinkage::LookupExceptionHandlerInTable(), v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame(), v8::internal::RUNTIME_FUNCTION(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), v8::internal::StubFrame::Summarize(), v8::internal::TranslatedState::TranslatedState(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread().
LookupCodeAndOffset()
std::pair< Tagged< Code >, int > v8::internal::StackFrame::LookupCodeAndOffset () const
Definition at line 777 of file frames.cc.
                                                                 {
  DCHECK_NE(isolate()->heap()->gc_state(), Heap::MARK_COMPACT);
  auto gc_safe_pair = GcSafeLookupCodeAndOffset();
  return {gc_safe_pair.first->UnsafeCastToCode(), gc_safe_pair.second};
}
References DCHECK_NE, GcSafeLookupCodeAndOffset(), heap(), isolate(), and v8::internal::Heap::MARK_COMPACT.
Referenced by v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), v8::internal::StubFrame::LookupExceptionHandlerInTable(), v8::internal::CommonFrame::position(), v8::internal::BuiltinExitFrame::Summarize(), and v8::internal::ApiCallbackExitFrame::Summarize().
MarkerToType()
static constexpr Type v8::internal::StackFrame::MarkerToType (intptr_t marker) [inline], [static], [constexpr]
Definition at line 204 of file frames.h.
                                                      {
    DCHECK(IsTypeMarker(marker));
    return static_cast<Type>(marker >> kSmiTagSize);
  }
References v8::internal::DCHECK(), IsTypeMarker(), and v8::internal::kSmiTagSize.
Referenced by v8::internal::StackFrameIterator::ComputeStackFrameType(), v8::internal::StackFrameIteratorForProfiler::ComputeStackFrameType(), v8::internal::anonymous_namespace{runtime-wasm.cc}::GetWasmInstanceDataOnStackTop(), and v8::internal::StackFrameIteratorForProfiler::IsNoFrameBytecodeHandlerPc().
maybe_unauthenticated_pc() [1/2]
Address v8::internal::StackFrame::maybe_unauthenticated_pc () const [inline]
Definition at line 89 of file frames-inl.h.
                                                          {
  if (!InFastCCall() && !is_profiler_entry_frame() && !is_stack_exit_frame()) {
    // Here the pc_address() is on the stack and properly authenticated.
    return pc();
  } else {
    // For fast C calls pc_address() points into IsolateData and the pc in there
    // is unauthenticated. For the profiler, the pc_address of the first visited
    // frame is also not written by a call instruction.
    // For wasm stacks, the exit frame's pc is stored in the jump buffer
    // unsigned.
    return unauthenticated_pc(pc_address());
  }
}
References InFastCCall(), is_profiler_entry_frame(), is_stack_exit_frame(), pc(), pc_address(), and unauthenticated_pc().
Referenced by v8::internal::CommonFrame::ComputeCallerState(), GcSafeLookupCodeAndOffset(), IteratePc(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), and Print().
maybe_unauthenticated_pc() [2/2]
static Address v8::internal::StackFrame::maybe_unauthenticated_pc (Address * pc_address) [inline], [static]
operator=()
void v8::internal::StackFrame::operator= (const StackFrame & original) [delete]
pc()
Address v8::internal::StackFrame::pc () const [inline]
Definition at line 78 of file frames-inl.h.
{ return ReadPC(pc_address()); }
References pc_address(), and ReadPC().
Referenced by v8::internal::ProfilerEventsProcessor::AddCurrentStack(), GcSafeLookupCodeAndOffset(), v8::internal::Isolate::GetAbstractPC(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), maybe_unauthenticated_pc(), v8::internal::TurbofanStubWithContextFrame::unchecked_code(), v8::internal::StubFrame::unchecked_code(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread().
pc_address()
Address* v8::internal::StackFrame::pc_address () const [inline]
Definition at line 324 of file frames.h.
{ return state_.pc_address; }
References v8::internal::StackFrame::State::pc_address, and state_.
Referenced by IteratePc(), maybe_unauthenticated_pc(), pc(), ReadPC(), ResolveReturnAddressLocation(), unauthenticated_pc(), and v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread().
Print()
void v8::internal::StackFrame::Print (StringStream * accumulator, PrintMode mode, int index) const [virtual]
Reimplemented in v8::internal::ApiAccessorExitFrame, v8::internal::ApiCallbackExitFrame, v8::internal::BuiltinExitFrame, and v8::internal::JavaScriptFrame.
Definition at line 1397 of file frames.cc.
                                        {
  DisallowGarbageCollection no_gc;
  PrintIndex(accumulator, mode, index);
  accumulator->Add(StringForStackFrameType(type()));
  accumulator->Add(" [pc: %p]\n",
                   reinterpret_cast<void*>(maybe_unauthenticated_pc()));
}
References v8::internal::StringStream::Add(), v8::internal::index, maybe_unauthenticated_pc(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{frames.cc}::PrintIndex(), v8::internal::anonymous_namespace{frames.cc}::StringForStackFrameType(), and type().
Referenced by _v8_internal_Expand_StackTrace(), and v8::internal::PrintFrames().
ReadPC()
Address v8::internal::StackFrame::ReadPC (Address * pc_address) [inline], [static]
Definition at line 103 of file frames-inl.h.
                                                     {
  return PointerAuthentication::AuthenticatePC(pc_address, kSystemPointerSize);
}
References v8::internal::PointerAuthentication::AuthenticatePC(), v8::internal::kSystemPointerSize, and pc_address().
Referenced by v8::internal::CommonFrame::caller_pc(), v8::internal::StackFrameIterator::ComputeStackFrameType(), and pc().
ResolveReturnAddressLocation()
Address * v8::internal::StackFrame::ResolveReturnAddressLocation (Address * pc_address) [inline], [static]
Definition at line 107 of file frames-inl.h.
                                                                            {
  if (return_address_location_resolver_ == nullptr) {
    return pc_address;
  } else {
    return reinterpret_cast<Address*>(return_address_location_resolver_(
        reinterpret_cast<uintptr_t>(pc_address)));
  }
}
References pc_address(), and return_address_location_resolver_.
Referenced by v8::internal::CommonFrame::ComputeCallerState(), v8::internal::NativeFrame::ComputeCallerState(), v8::internal::ExitFrame::ComputeCallerState(), v8::internal::ExitFrame::FillState(), and v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler().
set_constant_pool()
void v8::internal::StackFrame::set_constant_pool (Address constant_pool) [inline]
Definition at line 320 of file frames.h.
                                                {
    *constant_pool_address() = constant_pool;
  }
References constant_pool(), and constant_pool_address().
SetReturnAddressLocationResolver()
void v8::internal::StackFrame::SetReturnAddressLocationResolver (ReturnAddressLocationResolver resolver) [static]
Definition at line 828 of file frames.cc.
                                            {
  DCHECK_NULL(return_address_location_resolver_);
  return_address_location_resolver_ = resolver;
}
References DCHECK_NULL, and return_address_location_resolver_.
Referenced by v8::V8::SetReturnAddressLocationResolver().
sp()
Address v8::internal::StackFrame::sp () const [inline]
Definition at line 290 of file frames.h.
                     {
    DCHECK(!InFastCCall());
    return state_.sp;
  }
References v8::internal::DCHECK(), InFastCCall(), v8::internal::StackFrame::State::sp, and state_.
Referenced by v8::internal::ProfilerEventsProcessor::AddCurrentStack(), v8::internal::StackFrameIteratorForProfiler::AdvanceOneFrame(), v8::internal::anonymous_namespace{runtime-object.cc}::CheckExcludedPropertiesAreOnCallerStack(), v8::internal::CommonFrame::ComputeExpressionsCount(), v8::internal::ExitFrame::FillState(), v8::internal::Isolate::GetIncumbentContextSlow(), v8::internal::ExitFrame::GetStateForFramePointer(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::ConstructFrame::Iterate(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), v8::internal::StackHandlerIterator::StackHandlerIterator(), and v8::internal::Isolate::UnwindAndFindHandler().
top_handler()
StackHandler * v8::internal::StackFrame::top_handler () const [inline]
Definition at line 74 of file frames-inl.h.
                                                   {
  return iterator_->handler();
}
References v8::internal::StackFrameIteratorBase::handler(), and iterator_.
Referenced by v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame(), and v8::internal::Isolate::UnwindAndFindHandler().
type()
virtual Type v8::internal::StackFrame::type () const [pure virtual]
Implemented in v8::internal::JavaScriptFrame, v8::internal::IrregexpFrame, v8::internal::JavaScriptBuiltinContinuationWithCatchFrame, v8::internal::JavaScriptBuiltinContinuationFrame, v8::internal::BuiltinContinuationFrame, v8::internal::FastConstructFrame, v8::internal::ConstructFrame, v8::internal::InternalFrame, v8::internal::TurbofanJSFrame, v8::internal::MaglevFrame, v8::internal::BaselineFrame, v8::internal::InterpretedFrame, v8::internal::StubFrame, v8::internal::ApiAccessorExitFrame, v8::internal::ApiCallbackExitFrame, v8::internal::BuiltinExitFrame, v8::internal::ExitFrame, v8::internal::ConstructEntryFrame, v8::internal::EntryFrame, v8::internal::NativeFrame, v8::internal::TurbofanStubWithContextFrame, and v8::internal::BuiltinFrame.
Referenced by _v8_internal_Expand_StackTrace(), v8::internal::StackFrameIterator::Advance(), v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc}::FindInterpreterEntryFramePointer(), v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame(), v8::internal::StackFrameIteratorForProfiler::frame(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack(), is_api_accessor_exit(), is_api_callback_exit(), is_baseline(), is_builtin(), is_builtin_continuation(), is_builtin_exit(), is_construct(), is_construct_entry(), is_entry(), is_exit(), is_fast_construct(), is_internal(), is_interpreted(), is_irregexp(), is_javascript(), is_javascript_builtin_continuation(), is_javascript_builtin_with_catch_continuation(), is_maglev(), is_optimized_js(), is_turbofan_js(), is_unoptimized_js(), v8::internal::TypedFrame::Iterate(), v8::internal::Isolate::NotifyExceptionPropagationCallback(), v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame(), Print(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::ReportLiveCodeFromFrameForGC(), TypeToMarker(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::anonymous_namespace{isolate.cc}::VisitStack().
TypeToMarker()
static constexpr int32_t v8::internal::StackFrame::TypeToMarker (Type type) [inline], [static], [constexpr]
Definition at line 195 of file frames.h.
                                                   {
    DCHECK_GE(type, 0);
    return (type << kSmiTagSize) | kSmiTag;
  }
References DCHECK_GE, v8::internal::kSmiTag, v8::internal::kSmiTagSize, and type().
Referenced by v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::wasm::LiftoffAssembler::CallFrameSetupStub(), v8::internal::wasm::LiftoffAssembler::CheckStackShrink(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::MacroAssembler::EnterExitFrame(), v8::internal::MacroAssembler::EnterFrame(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant(), v8::internal::RegExpMacroAssemblerRISCV::GetCode(), v8::internal::CommonFrameWithJSLinkage::IsConstructFrame(), v8::internal::wasm::LiftoffAssembler::LoadOldFramePointer(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), and v8::internal::MacroAssembler::StubPrologue().
unauthenticated_pc() [1/2]
Address v8::internal::StackFrame::unauthenticated_pc () const [inline]
Definition at line 80 of file frames-inl.h.
                                                    {
  return unauthenticated_pc(pc_address());
}
References pc_address().
Referenced by v8::internal::StackFrameIteratorForProfiler::ComputeStackFrameType(), v8::internal::TickSample::GetStackSample(), and maybe_unauthenticated_pc().
unauthenticated_pc() [2/2]
Address v8::internal::StackFrame::unauthenticated_pc (Address * pc_address) [inline], [static]
Definition at line 85 of file frames-inl.h.
                                                                 {
  return PointerAuthentication::StripPAC(*pc_address);
}
References pc_address(), and v8::internal::PointerAuthentication::StripPAC().
unchecked_code()
virtual Tagged<HeapObject> v8::internal::StackFrame::unchecked_code () const [pure virtual]
Implemented in v8::internal::StubFrame, v8::internal::ConstructEntryFrame, v8::internal::EntryFrame, v8::internal::CommonFrameWithJSLinkage, v8::internal::TypedFrame, and v8::internal::TurbofanStubWithContextFrame.
Referenced by v8::internal::StackTraceFailureMessage::StackTraceFailureMessage().
Friends And Related Function Documentation
StackFrameIterator
friend class StackFrameIterator [friend]
Definition at line 399 of file frames.h.
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 400 of file frames.h.
StackFrameIteratorForProfiler
friend class StackFrameIteratorForProfiler [friend]
Definition at line 402 of file frames.h.
StackHandlerIterator
friend class StackHandlerIterator [friend]
Definition at line 401 of file frames.h.
Member Data Documentation
isolate_
Isolate* const v8::internal::StackFrame::isolate_ [private]
Definition at line 386 of file frames.h.
Referenced by isolate().
iterator_
const StackFrameIteratorBase* const v8::internal::StackFrame::iterator_ [protected]
Definition at line 383 of file frames.h.
Referenced by v8::internal::CommonFrameWithJSLinkage::ComputeParametersCount(), GetCallerState(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), and top_handler().
kIsolateTag
const intptr_t v8::internal::StackFrame::kIsolateTag = 1 [static], [private]
Definition at line 397 of file frames.h.
return_address_location_resolver_
ReturnAddressLocationResolver v8::internal::StackFrame::return_address_location_resolver_ [static], [private]
Initial value:
=
    nullptr
Definition at line 389 of file frames.h.
Referenced by ResolveReturnAddressLocation(), and SetReturnAddressLocationResolver().
state_
State v8::internal::StackFrame::state_ [private]
Definition at line 387 of file frames.h.
Referenced by v8::internal::StackFrameIteratorForProfiler::Advance(), v8::internal::StackFrameIteratorForProfiler::AdvanceOneFrame(), callee_fp(), callee_pc(), constant_pool_address(), fp(), InFastCCall(), is_profiler_entry_frame(), is_stack_exit_frame(), pc_address(), v8::internal::StackFrameIterator::Reframe(), v8::internal::StackFrameIteratorBase::SetNewFrame(), and sp().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc