v8::internal::Debug::TemporaryObjectsTracker Class Reference
Public Member Functions
TemporaryObjectsTracker ()=default
~TemporaryObjectsTracker () override=default
TemporaryObjectsTracker (const TemporaryObjectsTracker &)=delete
TemporaryObjectsTracker & operator= (const TemporaryObjectsTracker &)=delete
void AllocationEvent (Address addr, int size) override
void MoveEvent (Address from, Address to, int size) override
bool HasObject (DirectHandle< HeapObject > obj)
Public Attributes
bool disabled = false
Private Member Functions
bool HasRegionContainingObject (Address start, Address end)
std::map< Address, Address >::iterator FindOverlappingRegion (Address start, Address end, bool include_adjacent)
void AddRegion (Address start, Address end)
bool RemoveFromRegions (Address start, Address end)
Private Attributes
std::map< Address, Address > regions_
base::Mutex mutex_
Detailed Description
Definition at line 48 of file debug.cc.
Constructor & Destructor Documentation
TemporaryObjectsTracker() [1/2]
v8::internal::Debug::TemporaryObjectsTracker::TemporaryObjectsTracker () [default]
 TemporaryObjectsTracker()
v8::internal::Debug::TemporaryObjectsTracker::~TemporaryObjectsTracker () [override], [default]
TemporaryObjectsTracker() [2/2]
v8::internal::Debug::TemporaryObjectsTracker::TemporaryObjectsTracker (const TemporaryObjectsTracker &) [delete]
Member Function Documentation
AddRegion()
void v8::internal::Debug::TemporaryObjectsTracker::AddRegion (Address start, Address end) [inline], [private]
Definition at line 120 of file debug.cc.
                                             {
    DCHECK_LT(start, end);
    // Region [start, end) can be combined with an existing region if they
    // overlap.
    while (true) {
      auto it = FindOverlappingRegion(start, end, true);
      // If there is no such region, we don't need to merge anything.
      if (it == regions_.end()) break;
      // Otherwise, we found an overlapping region. We remove the old one and
      // add the new region recursively (to handle cases where the new region
      // overlaps multiple existing ones).
      start = std::min(start, it->second);
      end = std::max(end, it->first);
      regions_.erase(it);
    }
    // Add the new (possibly combined) region.
    regions_.emplace(end, start);
  }
References DCHECK_LT, v8::internal::compiler::end(), FindOverlappingRegion(), and regions_.
Referenced by AllocationEvent(), MoveEvent(), and RemoveFromRegions().
AllocationEvent()
void v8::internal::Debug::TemporaryObjectsTracker::AllocationEvent (Address addr, int size) [inline], [override], [virtual]
Implements v8::internal::HeapObjectAllocationTracker.
Definition at line 55 of file debug.cc.
                                                        {
    if (disabled) return;
    AddRegion(addr, addr + size);
  }
References AddRegion(), disabled, and size().
FindOverlappingRegion()
std::map<Address, Address>::iterator v8::internal::Debug::TemporaryObjectsTracker::FindOverlappingRegion (Address start, Address end, bool include_adjacent) [inline], [private]
Definition at line 102 of file debug.cc.
                                                         {
    // Region A = [start, end) overlaps with an existing region [existing_start,
    // existing_end) iff (start <= existing_end) && (existing_start <= end).
    // Since we index {regions_} by end address, we can find a candidate that
    // satisfies the first condition using lower_bound.
    if (include_adjacent) {
      auto it = regions_.lower_bound(start);
      if (it == regions_.end()) return regions_.end();
      if (it->second <= end) return it;
    } else {
      auto it = regions_.upper_bound(start);
      if (it == regions_.end()) return regions_.end();
      if (it->second < end) return it;
    }
    return regions_.end();
  }
References v8::internal::compiler::end(), and regions_.
Referenced by AddRegion(), HasRegionContainingObject(), and RemoveFromRegions().
HasObject()
bool v8::internal::Debug::TemporaryObjectsTracker::HasObject (DirectHandle< HeapObject > obj) [inline]
Definition at line 75 of file debug.cc.
                                               {
    if (IsJSObject(*obj) && Cast<JSObject>(obj)->GetEmbedderFieldCount()) {
      // Embedder may store any pointers using embedder fields and implements
      // non trivial logic, e.g. create wrappers lazily and store pointer to
      // native object inside embedder field. We should consider all objects
      // with embedder fields as non temporary.
      return false;
    }
    Address addr = obj->address();
    return HasRegionContainingObject(addr, addr + obj->Size());
  }
References v8::internal::DirectHandle< T >::address(), and HasRegionContainingObject().
HasRegionContainingObject()
bool v8::internal::Debug::TemporaryObjectsTracker::HasRegionContainingObject (Address start, Address end) [inline], [private]
Definition at line 90 of file debug.cc.
                                                             {
    // Check if there is a region that contains (overlaps) this object's space.
    auto it = FindOverlappingRegion(start, end, false);
    // If there is, we expect the region to contain the entire object.
    DCHECK_IMPLIES(it != regions_.end(),
                   it->second <= start && end <= it->first);
    return it != regions_.end();
  }
References DCHECK_IMPLIES, v8::internal::compiler::end(), FindOverlappingRegion(), and regions_.
Referenced by HasObject().
MoveEvent()
void v8::internal::Debug::TemporaryObjectsTracker::MoveEvent (Address from, Address to, int size) [inline], [override], [virtual]
Reimplemented from v8::internal::HeapObjectAllocationTracker.
Definition at line 60 of file debug.cc.
                                                              {
    if (from == to) return;
    base::MutexGuard guard(&mutex_);
    if (RemoveFromRegions(from, from + size)) {
      // We had the object tracked as temporary, so we will track the
      // new location as temporary, too.
      AddRegion(to, to + size);
    } else {
      // The object we moved is a non-temporary, so the new location is also
      // non-temporary. Thus we remove everything we track there (because it
      // must have become dead).
      RemoveFromRegions(to, to + size);
    }
  }
References AddRegion(), mutex_, RemoveFromRegions(), and size().
operator=()
TemporaryObjectsTracker& v8::internal::Debug::TemporaryObjectsTracker::operator= (const TemporaryObjectsTracker &) [delete]
RemoveFromRegions()
bool v8::internal::Debug::TemporaryObjectsTracker::RemoveFromRegions (Address start, Address end) [inline], [private]
Definition at line 142 of file debug.cc.
                                                     {
    // Check if we have anything that overlaps with [start, end).
    auto it = FindOverlappingRegion(start, end, false);
    if (it == regions_.end()) return false;
    // We need to update all overlapping regions.
    for (; it != regions_.end();
         it = FindOverlappingRegion(start, end, false)) {
      Address existing_start = it->second;
      Address existing_end = it->first;
      // If we remove the region [start, end) from an existing region
      // [existing_start, existing_end), there can be at most 2 regions left:
      regions_.erase(it);
      // The one before {start} is: [existing_start, start)
      if (existing_start < start) AddRegion(existing_start, start);
      // And the one after {end} is: [end, existing_end)
      if (end < existing_end) AddRegion(end, existing_end);
    }
    return true;
  }
References AddRegion(), v8::internal::compiler::end(), FindOverlappingRegion(), and regions_.
Referenced by MoveEvent().
Member Data Documentation
disabled
bool v8::internal::Debug::TemporaryObjectsTracker::disabled = false
Definition at line 87 of file debug.cc.
Referenced by AllocationEvent().
mutex_
base::Mutex v8::internal::Debug::TemporaryObjectsTracker::mutex_ [private]
Definition at line 168 of file debug.cc.
Referenced by MoveEvent().
regions_
std::map<Address, Address> v8::internal::Debug::TemporaryObjectsTracker::regions_ [private]
Definition at line 167 of file debug.cc.
Referenced by AddRegion(), FindOverlappingRegion(), HasRegionContainingObject(), and RemoveFromRegions().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug.cc