v8::internal::JavaScriptBuiltinContinuationWithCatchFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
void SetException (Tagged< Object > exception)
Static Public Member Functions
static JavaScriptBuiltinContinuationWithCatchFrame * cast (StackFrame *frame)
Protected Member Functions
JavaScriptBuiltinContinuationWithCatchFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1585 of file frames.h.
Constructor & Destructor Documentation
JavaScriptBuiltinContinuationWithCatchFrame()
v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::JavaScriptBuiltinContinuationWithCatchFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 379 of file frames-inl.h.
    : JavaScriptBuiltinContinuationFrame(iterator) {}
Member Function Documentation
cast()
static JavaScriptBuiltinContinuationWithCatchFrame* v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1592 of file frames.h.
                                                                              {
    DCHECK(frame->is_javascript_builtin_with_catch_continuation());
    return static_cast<JavaScriptBuiltinContinuationWithCatchFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_javascript_builtin_with_catch_continuation().
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
SetException()
void v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::SetException (Tagged< Object > exception)
Definition at line 2675 of file frames.cc.
                              {
  int argc = ComputeParametersCount();
  Address exception_argument_slot =
      fp() + BuiltinContinuationFrameConstants::kFixedFrameSizeAboveFp +
      (argc - 1) * kSystemPointerSize;
  // Only allow setting exception if previous value was the hole.
  CHECK_EQ(ReadOnlyRoots(isolate()).the_hole_value(),
           Tagged<Object>(Memory<Address>(exception_argument_slot)));
  Memory<Address>(exception_argument_slot) = exception.ptr();
}
References CHECK_EQ, v8::internal::JavaScriptBuiltinContinuationFrame::ComputeParametersCount(), v8::internal::StackFrame::fp(), v8::internal::StackFrame::isolate(), v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::kSystemPointerSize, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
type()
Type v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::type () const [inline], [override], [virtual]
Reimplemented from v8::internal::JavaScriptBuiltinContinuationFrame.
Definition at line 1588 of file frames.h.
                             {
    return JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH;
  }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1606 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc