v8::internal::ObjectLiteral Class Reference
#include <ast.h>
Public Types
enum Flags { kFastElements = 1 << 3
, kHasNullPrototype = 1 << 4
 }
using Property = ObjectLiteralProperty
Public Member Functions
void CalculateEmitStore (Zone *zone)
ZoneList< Property * > * properties ()
const ObjectLiteralBoilerplateBuilder * builder () const
ObjectLiteralBoilerplateBuilder * builder ()
Variable * home_object () const
Private Member Functions
ObjectLiteral (Zone *zone, const ScopedPtrList< Property > &properties, uint32_t boilerplate_properties, int pos, bool has_rest_property, Variable *home_object)
Private Attributes
friend Zone
ZoneList< Property * > properties_
Variable * home_object_
ObjectLiteralBoilerplateBuilder builder_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1379 of file ast.h.
Member Typedef Documentation
Property
using v8::internal::ObjectLiteral::Property = ObjectLiteralProperty
Definition at line 1381 of file ast.h.
Member Enumeration Documentation
Flags
enum v8::internal::ObjectLiteral::Flags
Enumerator
kFastElements
kHasNullPrototype
Definition at line 1383 of file ast.h.
             {
    kFastElements = 1 << 3,
    kHasNullPrototype = 1 << 4,
  };
Constructor & Destructor Documentation
ObjectLiteral()
v8::internal::ObjectLiteral::ObjectLiteral (Zone * zone, const ScopedPtrList< Property > & properties, uint32_t boilerplate_properties, int pos, bool has_rest_property, Variable * home_object) [inline], [private]
Definition at line 1408 of file ast.h.
      : AggregateLiteral(pos, kObjectLiteral),
        properties_(properties.ToConstVector(), zone),
        home_object_(home_object),
        builder_(&properties_, boilerplate_properties, has_rest_property) {}
Member Function Documentation
builder() [1/2]
ObjectLiteralBoilerplateBuilder* v8::internal::ObjectLiteral::builder () [inline]
Definition at line 1400 of file ast.h.
{ return &builder_; }
References builder_.
builder() [2/2]
const ObjectLiteralBoilerplateBuilder* v8::internal::ObjectLiteral::builder () const [inline]
Definition at line 1398 of file ast.h.
{ return &builder_; }
References builder_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), and v8::internal::LiteralBoilerplateBuilder::GetBoilerplateValue().
CalculateEmitStore()
void v8::internal::ObjectLiteral::CalculateEmitStore (Zone * zone)
Definition at line 339 of file ast.cc.
                                                 {
  const auto GETTER = ObjectLiteral::Property::GETTER;
  const auto SETTER = ObjectLiteral::Property::SETTER;
  CustomMatcherZoneHashMap table(Literal::Match,
                                 ZoneHashMap::kDefaultHashMapCapacity,
                                 ZoneAllocationPolicy(zone));
  for (int i = properties()->length() - 1; i >= 0; i--) {
    ObjectLiteral::Property* property = properties()->at(i);
    if (property->is_computed_name()) continue;
    if (property->IsPrototype()) continue;
    Literal* literal = property->key()->AsLiteral();
    DCHECK(!literal->IsNullLiteral());
    uint32_t hash = literal->Hash();
    ZoneHashMap::Entry* entry = table.LookupOrInsert(literal, hash);
    if (entry->value == nullptr) {
      entry->value = property;
    } else {
      // We already have a later definition of this property, so we don't need
      // to emit a store for the current one.
      //
      // There are two subtleties here.
      //
      // (1) Emitting a store might actually be incorrect. For example, in {get
      // foo() {}, foo: 42}, the getter store would override the data property
      // (which, being a non-computed compile-time valued property, is already
      // part of the initial literal object.
      //
      // (2) If the later definition is an accessor (say, a getter), and the
      // current definition is a complementary accessor (here, a setter), then
      // we still must emit a store for the current definition.
      auto later_kind =
          static_cast<ObjectLiteral::Property*>(entry->value)->kind();
      bool complementary_accessors =
          (property->kind() == GETTER && later_kind == SETTER) ||
          (property->kind() == SETTER && later_kind == GETTER);
      if (!complementary_accessors) {
        property->set_emit_store(false);
        if (later_kind == GETTER || later_kind == SETTER) {
          entry->value = property;
        }
      }
    }
  }
}
References v8::internal::DCHECK(), v8::internal::ObjectLiteralProperty::GETTER, GETTER, v8::internal::Literal::Hash(), v8::internal::Expression::IsNullLiteral(), v8::base::TemplateHashMapImpl< void *, void *, KeyEqualityMatcher< void * >, AllocationPolicy >::kDefaultHashMapCapacity, v8::internal::length, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::LookupOrInsert(), v8::internal::Literal::Match(), properties(), v8::internal::ObjectLiteralProperty::set_emit_store(), v8::internal::ObjectLiteralProperty::SETTER, SETTER, and v8::base::TemplateHashMapEntry< Key, Value >::value.
Referenced by v8::internal::Parser::InitializeObjectLiteral().
home_object()
Variable* v8::internal::ObjectLiteral::home_object () const [inline]
Definition at line 1402 of file ast.h.
{ return home_object_; }
References home_object_.
properties()
ZoneList<Property*>* v8::internal::ObjectLiteral::properties () [inline]
Definition at line 1396 of file ast.h.
{ return &properties_; }
References properties_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), and CalculateEmitStore().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1405 of file ast.h.
Member Data Documentation
builder_
ObjectLiteralBoilerplateBuilder v8::internal::ObjectLiteral::builder_ [private]
Definition at line 1418 of file ast.h.
Referenced by builder().
home_object_
Variable* v8::internal::ObjectLiteral::home_object_ [private]
Definition at line 1417 of file ast.h.
Referenced by home_object().
properties_
ZoneList<Property*> v8::internal::ObjectLiteral::properties_ [private]
Definition at line 1416 of file ast.h.
Referenced by properties().
Zone
friend v8::internal::ObjectLiteral::Zone [private]
Definition at line 1406 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc