v8::internal::wasm::WasmEHData Class Reference
#include <wasm-interpreter.h>
Classes
struct CatchBlock
struct CatchHandler
struct ExceptionPayloadSlotOffsets
struct TryBlock
Public Types
typedef int BlockIndex
Public Member Functions
const TryBlock * GetTryBlock (CodeOffset code_offset) const
const TryBlock * GetParentTryBlock (const TryBlock *try_block) const
const TryBlock * GetDelegateTryBlock (const TryBlock *try_block) const
size_t GetEndInstructionOffsetFor (BlockIndex catch_block_index) const
ExceptionPayloadSlotOffsets GetExceptionPayloadStartSlotOffsets (BlockIndex catch_block_index) const
void SetCaughtException (Isolate *isolate, BlockIndex catch_block_index, DirectHandle< Object > exception)
DirectHandle< Object > GetCaughtException (Isolate *isolate, BlockIndex catch_block_index) const
Static Public Attributes
static const int kCatchAllTagIndex = -1
static const int kDelegateToCallerIndex = 0
Protected Member Functions
BlockIndex GetTryBranchOf (BlockIndex catch_block_index) const
Protected Attributes
std::unordered_map< CodeOffset, BlockIndex > code_trycatch_map_
std::unordered_map< BlockIndex, TryBlock > try_blocks_
std::unordered_map< BlockIndex, CatchBlock > catch_blocks_
Detailed Description
Definition at line 1245 of file wasm-interpreter.h.
Member Typedef Documentation
BlockIndex
typedef int v8::internal::wasm::WasmEHData::BlockIndex
Definition at line 1253 of file wasm-interpreter.h.
Member Function Documentation
GetCaughtException()
DirectHandle<Object> v8::internal::wasm::WasmEHData::GetCaughtException (Isolate * isolate, BlockIndex catch_block_index) const
Referenced by v8::internal::wasm::WasmBytecode::GetCaughtException().
GetDelegateTryBlock()
const WasmEHData::TryBlock * v8::internal::wasm::WasmEHData::GetDelegateTryBlock (const TryBlock * try_block) const
Definition at line 7213 of file wasm-interpreter.cc.
                                               {
  DCHECK_GE(try_block->delegate_try_index, 0);
  if (try_block->delegate_try_index == WasmEHData::kDelegateToCallerIndex) {
    return nullptr;
  }
  const auto& try_it = try_blocks_.find(try_block->delegate_try_index);
  DCHECK_NE(try_it, try_blocks_.end());
  return &try_it->second;
}
References DCHECK_GE, DCHECK_NE, v8::internal::wasm::WasmEHData::TryBlock::delegate_try_index, kDelegateToCallerIndex, and try_blocks_.
Referenced by GetTryBlock().
GetEndInstructionOffsetFor()
size_t v8::internal::wasm::WasmEHData::GetEndInstructionOffsetFor (WasmEHData::BlockIndex catch_block_index) const
Definition at line 7224 of file wasm-interpreter.cc.
                                                  {
  int try_block_index = GetTryBranchOf(catch_block_index);
  DCHECK_GE(try_block_index, 0);
  const auto& it = try_blocks_.find(try_block_index);
  DCHECK_NE(it, try_blocks_.end());
  return it->second.end_instruction_code_offset;
}
References DCHECK_GE, DCHECK_NE, GetTryBranchOf(), and try_blocks_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets().
GetExceptionPayloadStartSlotOffsets()
WasmEHData::ExceptionPayloadSlotOffsets v8::internal::wasm::WasmEHData::GetExceptionPayloadStartSlotOffsets (WasmEHData::BlockIndex catch_block_index) const
Definition at line 7235 of file wasm-interpreter.cc.
                                                  {
  const auto& it = catch_blocks_.find(catch_block_index);
  DCHECK_NE(it, catch_blocks_.end());
  return {it->second.first_param_slot_offset,
          it->second.first_param_ref_stack_index};
}
References catch_blocks_, and DCHECK_NE.
Referenced by v8::internal::wasm::WasmBytecode::GetExceptionPayloadStartSlotOffsets().
GetParentTryBlock()
const WasmEHData::TryBlock * v8::internal::wasm::WasmEHData::GetParentTryBlock (const TryBlock * try_block) const
Definition at line 7206 of file wasm-interpreter.cc.
                                               {
  const auto& try_it =
      try_blocks_.find(try_block->parent_or_matching_try_block);
  return try_it != try_blocks_.end() ? &try_it->second : nullptr;
}
References v8::internal::wasm::WasmEHData::TryBlock::parent_or_matching_try_block, and try_blocks_.
Referenced by v8::internal::wasm::WasmBytecode::GetParentTryBlock().
GetTryBlock()
const WasmEHData::TryBlock * v8::internal::wasm::WasmEHData::GetTryBlock (CodeOffset code_offset) const
Definition at line 7191 of file wasm-interpreter.cc.
                                  {
  const auto& catch_it = code_trycatch_map_.find(code_offset);
  if (catch_it == code_trycatch_map_.end()) return nullptr;
  BlockIndex try_block_index = catch_it->second;
  const auto& try_it = try_blocks_.find(try_block_index);
  DCHECK_NE(try_it, try_blocks_.end());
  const WasmEHData::TryBlock* try_block = &try_it->second;
  if (try_block->IsTryDelegate()) {
    try_block = GetDelegateTryBlock(try_block);
  }
  return try_block;
}
References code_trycatch_map_, DCHECK_NE, GetDelegateTryBlock(), v8::internal::wasm::WasmEHData::TryBlock::IsTryDelegate(), and try_blocks_.
Referenced by v8::internal::wasm::WasmBytecode::GetTryBlock().
GetTryBranchOf()
WasmEHData::BlockIndex v8::internal::wasm::WasmEHData::GetTryBranchOf (WasmEHData::BlockIndex catch_block_index) const [protected]
Definition at line 7243 of file wasm-interpreter.cc.
                                                  {
  const auto& it = catch_blocks_.find(catch_block_index);
  if (it == catch_blocks_.end()) return -1;
  return it->second.try_block_index;
}
References catch_blocks_.
Referenced by v8::internal::wasm::WasmEHDataGenerator::EndTryCatchBlocks(), and GetEndInstructionOffsetFor().
SetCaughtException()
void v8::internal::wasm::WasmEHData::SetCaughtException (Isolate * isolate, BlockIndex catch_block_index, DirectHandle< Object > exception)
Member Data Documentation
catch_blocks_
std::unordered_map<BlockIndex, CatchBlock> v8::internal::wasm::WasmEHData::catch_blocks_ [protected]
Definition at line 1317 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmEHDataGenerator::AddCatchBlock(), GetExceptionPayloadStartSlotOffsets(), and GetTryBranchOf().
code_trycatch_map_
std::unordered_map<CodeOffset, BlockIndex> v8::internal::wasm::WasmEHData::code_trycatch_map_ [protected]
Definition at line 1315 of file wasm-interpreter.h.
Referenced by GetTryBlock(), and v8::internal::wasm::WasmEHDataGenerator::RecordPotentialExceptionThrowingInstruction().
kCatchAllTagIndex
const int v8::internal::wasm::WasmEHData::kCatchAllTagIndex = -1 [static]
Definition at line 1247 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
kDelegateToCallerIndex
const int v8::internal::wasm::WasmEHData::kDelegateToCallerIndex = 0 [static]
Definition at line 1251 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), and GetDelegateTryBlock().
try_blocks_
std::unordered_map<BlockIndex, TryBlock> v8::internal::wasm::WasmEHData::try_blocks_ [protected]
Definition at line 1316 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmEHDataGenerator::AddCatchBlock(), v8::internal::wasm::WasmEHDataGenerator::AddDelegatedBlock(), v8::internal::wasm::WasmEHDataGenerator::AddTryBlock(), v8::internal::wasm::WasmEHDataGenerator::EndTryCatchBlocks(), GetDelegateTryBlock(), GetEndInstructionOffsetFor(), GetParentTryBlock(), GetTryBlock(), and v8::internal::wasm::WasmEHDataGenerator::RecordPotentialExceptionThrowingInstruction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc