v8::internal::IncrementalMarking Class Reference
#include <incremental-marking.h>
Classes
class Observer
Public Member Functions
IncrementalMarking (Heap *heap, WeakObjects *weak_objects)
IncrementalMarking (const IncrementalMarking &)=delete
IncrementalMarking & operator= (const IncrementalMarking &)=delete
MarkingMode marking_mode () const
bool IsMinorMarking () const
bool IsMajorMarking () const
bool IsStopped () const
bool IsMarking () const
bool IsMajorMarkingComplete () const
bool MajorCollectionRequested () const
bool CanAndShouldBeStarted () const
void Start (GarbageCollector garbage_collector, GarbageCollectionReason gc_reason)
bool Stop ()
void AdvanceAndFinalizeIfComplete ()
void AdvanceAndFinalizeIfNecessary ()
void AdvanceOnAllocation ()
bool IsCompacting ()
Heap * heap () const
Isolate * isolate () const
IncrementalMarkingJob * incremental_marking_job () const
bool black_allocation ()
bool IsBelowActivationThresholds () const
void MarkBlackBackground (Tagged< HeapObject > obj, int object_size)
void MarkRootsForTesting ()
void AdvanceForTesting (v8::base::TimeDelta max_duration, size_t max_bytes_to_mark=SIZE_MAX)
uint64_t current_trace_id () const
std::shared_ptr<::heap::base::IncrementalMarkingSchedule > schedule ()
Private Member Functions
void StartMarkingMajor ()
void StartMarkingMinor ()
bool CanBeStarted () const
void StartBlackAllocation ()
void PauseBlackAllocation ()
void FinishBlackAllocation ()
void StartPointerTableBlackAllocation ()
void StopPointerTableBlackAllocation ()
void MarkRoots ()
void PublishWriteBarrierWorklists ()
void FetchBytesMarkedConcurrently ()
size_t GetScheduledBytes (StepOrigin step_origin)
bool ShouldFinalize () const
bool ShouldWaitForTask ()
bool TryInitializeTaskTimeout ()
std::pair< v8::base::TimeDelta, size_t > CppHeapStep (v8::base::TimeDelta max_duration, size_t marked_bytes_limit)
void Step (v8::base::TimeDelta max_duration, size_t max_bytes_to_process, StepOrigin step_origin)
size_t OldGenerationSizeOfObjects () const
MarkingState * marking_state ()
MarkingWorklists::Local * local_marking_worklists () const
Private Attributes
Heap *const heap_
MarkCompactCollector *const major_collector_
MinorMarkSweepCollector *const minor_collector_
WeakObjects * weak_objects_
MarkingWorklists::Local * current_local_marking_worklists_ = nullptr
MarkingState *const marking_state_
v8::base::TimeTicks start_time_
size_t main_thread_marked_bytes_ = 0
size_t bytes_marked_concurrently_ = 0
MarkingMode marking_mode_ = MarkingMode::kNoMarking
bool is_compacting_ = false
bool black_allocation_ = false
bool completion_task_scheduled_ = false
v8::base::TimeTicks completion_task_timeout_
bool major_collection_requested_via_stack_guard_ = false
std::unique_ptr< IncrementalMarkingJob > incremental_marking_job_
Observer new_generation_observer_
Observer old_generation_observer_
base::Mutex background_live_bytes_mutex_
std::unordered_map< MutablePageMetadata *, intptr_t, base::hash< MutablePageMetadata * > > background_live_bytes_
std::shared_ptr<::heap::base::IncrementalMarkingSchedule > schedule_
std::optional< uint64_t > current_trace_id_
Friends
class IncrementalMarkingJob
Detailed Description
Definition at line 54 of file incremental-marking.h.
Constructor & Destructor Documentation
IncrementalMarking() [1/2]
v8::internal::IncrementalMarking::IncrementalMarking (Heap * heap, WeakObjects * weak_objects)
Definition at line 93 of file incremental-marking.cc.
    : heap_(heap),
      major_collector_(heap->mark_compact_collector()),
      minor_collector_(heap->minor_mark_sweep_collector()),
      weak_objects_(weak_objects),
      marking_state_(heap->marking_state()),
      incremental_marking_job_(
          v8_flags.incremental_marking_task
              ? std::make_unique<IncrementalMarkingJob>(heap)
              : nullptr),
      new_generation_observer_(this,
                               kMajorGCYoungGenerationAllocationObserverStep),
      old_generation_observer_(this,
                               kMajorGCOldGenerationAllocationObserverStep) {}
IncrementalMarking() [2/2]
v8::internal::IncrementalMarking::IncrementalMarking (const IncrementalMarking &) [delete]
Member Function Documentation
AdvanceAndFinalizeIfComplete()
void v8::internal::IncrementalMarking::AdvanceAndFinalizeIfComplete ()
Definition at line 676 of file incremental-marking.cc.
                                                      {
  const size_t max_bytes_to_process = GetScheduledBytes(StepOrigin::kTask);
  Step(GetMaxDuration(StepOrigin::kTask), max_bytes_to_process,
       StepOrigin::kTask);
  if (IsMajorMarkingComplete()) {
    heap()->FinalizeIncrementalMarkingAtomically(
        GarbageCollectionReason::kFinalizeMarkingViaTask);
  }
}
References v8::internal::Heap::FinalizeIncrementalMarkingAtomically(), v8::internal::anonymous_namespace{incremental-marking.cc}::GetMaxDuration(), GetScheduledBytes(), heap(), IsMajorMarkingComplete(), v8::internal::kFinalizeMarkingViaTask, v8::internal::kTask, and Step().
AdvanceAndFinalizeIfNecessary()
void v8::internal::IncrementalMarking::AdvanceAndFinalizeIfNecessary ()
Definition at line 686 of file incremental-marking.cc.
                                                       {
  if (!IsMajorMarking()) return;
  DCHECK(!heap_->always_allocate());
  AdvanceOnAllocation();
  if (major_collection_requested_via_stack_guard_ && IsMajorMarkingComplete()) {
    heap()->FinalizeIncrementalMarkingAtomically(
        GarbageCollectionReason::kFinalizeMarkingViaStackGuard);
  }
}
References AdvanceOnAllocation(), v8::internal::Heap::always_allocate(), v8::internal::DCHECK(), v8::internal::Heap::FinalizeIncrementalMarkingAtomically(), heap(), heap_, IsMajorMarking(), IsMajorMarkingComplete(), v8::internal::kFinalizeMarkingViaStackGuard, and major_collection_requested_via_stack_guard_.
Referenced by v8::internal::Heap::HandleExternalMemoryInterrupt().
AdvanceForTesting()
void v8::internal::IncrementalMarking::AdvanceForTesting (v8::base::TimeDelta max_duration, size_t max_bytes_to_mark = SIZE_MAX)
Definition at line 696 of file incremental-marking.cc.
                                                                     {
  Step(max_duration, max_bytes_to_mark, StepOrigin::kV8);
}
References v8::internal::kV8, and Step().
AdvanceOnAllocation()
void v8::internal::IncrementalMarking::AdvanceOnAllocation ()
Definition at line 701 of file incremental-marking.cc.
                                             {
  DCHECK_EQ(heap_->gc_state(), Heap::NOT_IN_GC);
  DCHECK(v8_flags.incremental_marking);
  DCHECK(IsMajorMarking());
  const size_t max_bytes_to_process = GetScheduledBytes(StepOrigin::kV8);
  Step(GetMaxDuration(StepOrigin::kV8), max_bytes_to_process, StepOrigin::kV8);
  // Bail out when an AlwaysAllocateScope is active as the assumption is that
  // there's no GC being triggered. Check this condition at last position to
  // allow a completion task to be scheduled.
  if (IsMajorMarkingComplete() && !ShouldWaitForTask() &&
      !heap()->always_allocate()) {
    // When completion task isn't run soon enough, fall back to stack guard to
    // force completion.
    major_collection_requested_via_stack_guard_ = true;
    isolate()->stack_guard()->RequestGC();
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Heap::gc_state(), v8::internal::anonymous_namespace{incremental-marking.cc}::GetMaxDuration(), GetScheduledBytes(), heap(), heap_, IsMajorMarking(), IsMajorMarkingComplete(), isolate(), v8::internal::kV8, major_collection_requested_via_stack_guard_, v8::internal::Heap::NOT_IN_GC, ShouldWaitForTask(), v8::internal::Isolate::stack_guard(), Step(), and v8::internal::v8_flags.
Referenced by AdvanceAndFinalizeIfNecessary(), and v8::internal::UnifiedHeapMarker::AdvanceMarkingOnAllocationImpl().
black_allocation()
bool v8::internal::IncrementalMarking::black_allocation () [inline]
Definition at line 109 of file incremental-marking.h.
{ return black_allocation_; }
Referenced by v8::internal::MemoryAllocator::AllocatePage(), and v8::internal::MainAllocator::IsBlackAllocationEnabled().
CanAndShouldBeStarted()
bool v8::internal::IncrementalMarking::CanAndShouldBeStarted () const
Definition at line 116 of file incremental-marking.cc.
                                                     {
  return CanBeStarted() && heap_->ShouldUseIncrementalMarking();
}
References CanBeStarted(), heap_, and v8::internal::Heap::ShouldUseIncrementalMarking().
CanBeStarted()
bool v8::internal::IncrementalMarking::CanBeStarted () const [private]
Definition at line 120 of file incremental-marking.cc.
                                            {
  // Only start incremental marking in a safe state:
  // 1) when incremental marking is turned on
  // 2) when we are currently not in a GC, and
  // 3) when we are currently not serializing or deserializing the heap, and
  // 4) not a shared heap.
  return v8_flags.incremental_marking && heap_->gc_state() == Heap::NOT_IN_GC &&
         heap_->deserialization_complete() && !isolate()->serializer_enabled();
}
References v8::internal::Heap::deserialization_complete(), v8::internal::Heap::gc_state(), heap_, isolate(), v8::internal::Heap::NOT_IN_GC, v8::internal::Isolate::serializer_enabled(), and v8::internal::v8_flags.
Referenced by CanAndShouldBeStarted(), and Start().
CppHeapStep()
std::pair< v8::base::TimeDelta, size_t > v8::internal::IncrementalMarking::CppHeapStep (v8::base::TimeDelta max_duration, size_t marked_bytes_limit) [private]
Definition at line 472 of file incremental-marking.cc.
                                                             {
  DCHECK(IsMarking());
  auto* cpp_heap = CppHeap::From(heap_->cpp_heap());
  if (!cpp_heap || !cpp_heap->incremental_marking_supported()) {
    return {};
  }
  TRACE_GC(heap()->tracer(), GCTracer::Scope::MC_INCREMENTAL_EMBEDDER_TRACING);
  const auto start = v8::base::TimeTicks::Now();
  cpp_heap->AdvanceMarking(max_duration, marked_bytes_limit);
  return {v8::base::TimeTicks::Now() - start, cpp_heap->last_bytes_marked()};
}
References v8::internal::Heap::cpp_heap(), v8::internal::DCHECK(), v8::internal::CppHeap::From(), heap(), heap_, IsMarking(), v8::base::TimeTicks::Now(), and TRACE_GC.
Referenced by Step().
current_trace_id()
uint64_t v8::internal::IncrementalMarking::current_trace_id () const [inline]
Definition at line 121 of file incremental-marking.h.
{ return current_trace_id_.value(); }
FetchBytesMarkedConcurrently()
void v8::internal::IncrementalMarking::FetchBytesMarkedConcurrently () [private]
Definition at line 732 of file incremental-marking.cc.
                                                      {
  if (!v8_flags.concurrent_marking) return;
  const size_t current_bytes_marked_concurrently =
      heap()->concurrent_marking()->TotalMarkedBytes();
  // The concurrent_marking()->TotalMarkedBytes() is not monotonic for a
  // short period of time when a concurrent marking task is finishing.
  if (current_bytes_marked_concurrently > bytes_marked_concurrently_) {
    const size_t delta =
        current_bytes_marked_concurrently - bytes_marked_concurrently_;
    schedule_->AddConcurrentlyMarkedBytes(delta);
    bytes_marked_concurrently_ = current_bytes_marked_concurrently;
  }
}
References bytes_marked_concurrently_, v8::internal::Heap::concurrent_marking(), heap(), schedule_, v8::internal::ConcurrentMarking::TotalMarkedBytes(), and v8::internal::v8_flags.
Referenced by GetScheduledBytes().
FinishBlackAllocation()
void v8::internal::IncrementalMarking::FinishBlackAllocation () [private]
Definition at line 423 of file incremental-marking.cc.
                                               {
  if (!black_allocation_) {
    return;
  }
  // Don't fixup the marking bitmaps of the black allocated pages, since the
  // concurrent marker may still be running and will access the page flags.
  black_allocation_ = false;
  StopPointerTableBlackAllocation();
  if (v8_flags.trace_incremental_marking) {
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Black allocation finished\n");
  }
}
References black_allocation_, isolate(), StopPointerTableBlackAllocation(), and v8::internal::v8_flags.
Referenced by Stop().
GetScheduledBytes()
size_t v8::internal::IncrementalMarking::GetScheduledBytes (StepOrigin step_origin) [private]
Definition at line 646 of file incremental-marking.cc.
                                                                   {
  FetchBytesMarkedConcurrently();
  // TODO(v8:14140): Consider the size including young generation here as well
  // as the full marker marks both the young and old generations.
  size_t estimated_live_bytes = OldGenerationSizeOfObjects();
  if (v8_flags.incremental_marking_unified_schedule) {
    if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap())) {
      estimated_live_bytes += cpp_heap->used_size();
    }
  }
  const size_t marked_bytes_limit =
      schedule_->GetNextIncrementalStepDuration(estimated_live_bytes);
  if (V8_UNLIKELY(v8_flags.trace_incremental_marking)) {
    const auto step_info = schedule_->GetCurrentStepInfo();
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Schedule: %zuKB to mark, origin: %s, elapsed: "
        "%.1f, marked: %zuKB (mutator: %zuKB, concurrent %zuKB), expected "
        "marked: %zuKB, estimated live: %zuKB, schedule delta: %+" PRIi64
        "KB\n",
        marked_bytes_limit / KB, ToString(step_origin),
        step_info.elapsed_time.InMillisecondsF(), step_info.marked_bytes() / KB,
        step_info.mutator_marked_bytes / KB,
        step_info.concurrent_marked_bytes / KB,
        step_info.expected_marked_bytes / KB,
        step_info.estimated_live_bytes / KB,
        step_info.scheduled_delta_bytes() / KB);
  }
  return marked_bytes_limit;
}
References v8::internal::Heap::cpp_heap(), FetchBytesMarkedConcurrently(), v8::internal::CppHeap::From(), heap_, isolate(), v8::internal::KB, OldGenerationSizeOfObjects(), schedule_, v8::internal::ToString(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by AdvanceAndFinalizeIfComplete(), and AdvanceOnAllocation().
heap()
Heap* v8::internal::IncrementalMarking::heap () const [inline]
Definition at line 102 of file incremental-marking.h.
{ return heap_; }
Referenced by AdvanceAndFinalizeIfComplete(), AdvanceAndFinalizeIfNecessary(), AdvanceOnAllocation(), CppHeapStep(), FetchBytesMarkedConcurrently(), PauseBlackAllocation(), ShouldFinalize(), Start(), StartBlackAllocation(), StartMarkingMajor(), StartMarkingMinor(), StartPointerTableBlackAllocation(), Step(), Stop(), and StopPointerTableBlackAllocation().
incremental_marking_job()
IncrementalMarkingJob* v8::internal::IncrementalMarking::incremental_marking_job () const [inline]
Definition at line 105 of file incremental-marking.h.
                                                         {
    return incremental_marking_job_.get();
  }
Referenced by ShouldWaitForTask(), StartMarkingMajor(), and TryInitializeTaskTimeout().
IsBelowActivationThresholds()
bool v8::internal::IncrementalMarking::IsBelowActivationThresholds () const
Definition at line 130 of file incremental-marking.cc.
                                                           {
  return heap_->OldGenerationSizeOfObjects() <= kV8ActivationThreshold &&
         heap_->EmbedderSizeOfObjects() <= kEmbedderActivationThreshold;
}
References v8::internal::Heap::EmbedderSizeOfObjects(), heap_, v8::internal::anonymous_namespace{incremental-marking.cc}::kEmbedderActivationThreshold, v8::internal::anonymous_namespace{incremental-marking.cc}::kV8ActivationThreshold, and v8::internal::Heap::OldGenerationSizeOfObjects().
IsCompacting()
bool v8::internal::IncrementalMarking::IsCompacting () [inline]
Definition at line 100 of file incremental-marking.h.
{ return IsMajorMarking() && is_compacting_; }
Referenced by v8::internal::LocalHeap::LocalHeap().
IsMajorMarking()
bool v8::internal::IncrementalMarking::IsMajorMarking () const [inline]
Definition at line 66 of file incremental-marking.h.
                              {
    return marking_mode_ == MarkingMode::kMajorMarking;
  }
References v8::internal::kMajorMarking.
Referenced by AdvanceAndFinalizeIfNecessary(), AdvanceOnAllocation(), v8::internal::Isolate::Init(), MarkRoots(), PauseBlackAllocation(), v8::internal::MarkCompactCollector::Prepare(), v8::internal::Sweeper::RawSweep(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), v8::internal::LocalHeap::SetUpSharedMarking(), StartBlackAllocation(), Step(), Stop(), and v8::internal::MarkCompactCollector::TearDown().
IsMajorMarkingComplete()
bool v8::internal::IncrementalMarking::IsMajorMarkingComplete () const [inline]
Definition at line 72 of file incremental-marking.h.
                                      {
    return IsMajorMarking() && ShouldFinalize();
  }
Referenced by AdvanceAndFinalizeIfComplete(), AdvanceAndFinalizeIfNecessary(), and AdvanceOnAllocation().
IsMarking()
bool v8::internal::IncrementalMarking::IsMarking () const [inline]
Definition at line 71 of file incremental-marking.h.
{ return marking_mode_ != MarkingMode::kNoMarking; }
References v8::internal::kNoMarking.
Referenced by CppHeapStep(), v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), v8::internal::Heap::IsNewSpaceAllowedToGrowAboveTargetCapacity(), v8::internal::LocalHeap::LocalHeap(), v8::internal::MarkCompactCollector::Prepare(), ShouldFinalize(), and v8::internal::CppHeap::StartDetachingIsolate().
IsMinorMarking()
bool v8::internal::IncrementalMarking::IsMinorMarking () const [inline]
Definition at line 63 of file incremental-marking.h.
                              {
    return marking_mode_ == MarkingMode::kMinorMarking;
  }
References v8::internal::kMinorMarking.
Referenced by MarkRoots(), v8::internal::Sweeper::RawSweep(), and v8::internal::MinorMarkSweepCollector::TearDown().
isolate()
Isolate * v8::internal::IncrementalMarking::isolate () const
Definition at line 865 of file incremental-marking.cc.
{ return heap_->isolate(); }
References heap_, and v8::internal::Heap::isolate().
Referenced by AdvanceOnAllocation(), CanBeStarted(), FinishBlackAllocation(), GetScheduledBytes(), MarkRoots(), PauseBlackAllocation(), ShouldWaitForTask(), Start(), StartBlackAllocation(), StartMarkingMajor(), StartMarkingMinor(), StartPointerTableBlackAllocation(), Step(), Stop(), StopPointerTableBlackAllocation(), and TryInitializeTaskTimeout().
IsStopped()
bool v8::internal::IncrementalMarking::IsStopped () const [inline]
Definition at line 70 of file incremental-marking.h.
{ return !IsMarking(); }
Referenced by v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), v8::internal::IncrementalMarkingJob::ScheduleTask(), Start(), Stop(), and v8::internal::MarkCompactCollector::VerifyMarking().
local_marking_worklists()
MarkingWorklists::Local* v8::internal::IncrementalMarking::local_marking_worklists () const [inline], [private]
Definition at line 174 of file incremental-marking.h.
                                                         {
    return current_local_marking_worklists_;
  }
Referenced by StartMarkingMinor(), and Step().
MajorCollectionRequested()
bool v8::internal::IncrementalMarking::MajorCollectionRequested () const [inline]
Definition at line 76 of file incremental-marking.h.
                                        {
    return major_collection_requested_via_stack_guard_;
  }
MarkBlackBackground()
void v8::internal::IncrementalMarking::MarkBlackBackground (Tagged< HeapObject > obj, int object_size)
Definition at line 108 of file incremental-marking.cc.
                                                              {
  CHECK(marking_state()->TryMark(obj));
  base::MutexGuard guard(&background_live_bytes_mutex_);
  background_live_bytes_[MutablePageMetadata::FromHeapObject(obj)] +=
      static_cast<intptr_t>(object_size);
}
References background_live_bytes_, background_live_bytes_mutex_, CHECK, v8::internal::MutablePageMetadata::FromHeapObject(), and marking_state().
marking_mode()
MarkingMode v8::internal::IncrementalMarking::marking_mode () const [inline]
Definition at line 61 of file incremental-marking.h.
{ return marking_mode_; }
Referenced by v8::internal::PageMetadata::ConvertNewToOld(), v8::internal::LocalHeap::LocalHeap(), and v8::internal::OldLargeObjectSpace::PromoteNewLargeObject().
marking_state()
MarkingState* v8::internal::IncrementalMarking::marking_state () [inline], [private]
Definition at line 173 of file incremental-marking.h.
{ return marking_state_; }
Referenced by MarkBlackBackground().
MarkRoots()
void v8::internal::IncrementalMarking::MarkRoots () [private]
Definition at line 214 of file incremental-marking.cc.
                                   {
  if (IsMajorMarking()) {
    RootMarkingVisitor root_visitor(heap_->mark_compact_collector());
    heap_->IterateRoots(
        &root_visitor,
        base::EnumSet<SkipRoot>{SkipRoot::kStack, SkipRoot::kMainThreadHandles,
                                SkipRoot::kTracedHandles, SkipRoot::kWeak,
                                SkipRoot::kReadOnlyBuiltins});
  } else {
    DCHECK(IsMinorMarking());
    YoungGenerationRootMarkingVisitor root_visitor(
        heap_->minor_mark_sweep_collector());
    heap_->IterateRoots(
        &root_visitor,
        base::EnumSet<SkipRoot>{
            SkipRoot::kStack, SkipRoot::kMainThreadHandles, SkipRoot::kWeak,
            SkipRoot::kExternalStringTable, SkipRoot::kGlobalHandles,
            SkipRoot::kTracedHandles, SkipRoot::kOldGeneration,
            SkipRoot::kReadOnlyBuiltins});
    isolate()->global_handles()->IterateYoungStrongAndDependentRoots(
        &root_visitor);
  }
}
References v8::internal::DCHECK(), v8::internal::Isolate::global_handles(), heap_, IsMajorMarking(), IsMinorMarking(), isolate(), v8::internal::Heap::IterateRoots(), v8::internal::GlobalHandles::IterateYoungStrongAndDependentRoots(), v8::internal::kExternalStringTable, v8::internal::kGlobalHandles, v8::internal::kMainThreadHandles, v8::internal::kOldGeneration, v8::internal::kReadOnlyBuiltins, v8::internal::kStack, v8::internal::kTracedHandles, v8::internal::kWeak, v8::internal::Heap::mark_compact_collector(), and v8::internal::Heap::minor_mark_sweep_collector().
Referenced by MarkRootsForTesting(), StartMarkingMajor(), and StartMarkingMinor().
MarkRootsForTesting()
void v8::internal::IncrementalMarking::MarkRootsForTesting ()
Definition at line 238 of file incremental-marking.cc.
{ MarkRoots(); }
References MarkRoots().
OldGenerationSizeOfObjects()
size_t v8::internal::IncrementalMarking::OldGenerationSizeOfObjects () const [private]
Definition at line 549 of file incremental-marking.cc.
                                                            {
  // TODO(v8:14140): This is different to Heap::OldGenerationSizeOfObjects() in
  // that it only considers shared space for the shared space isolate. Consider
  // adjusting the Heap version.
  const bool is_shared_space_isolate =
      heap_->isolate()->is_shared_space_isolate();
  size_t total = 0;
  PagedSpaceIterator spaces(heap_);
  for (PagedSpace* space = spaces.Next(); space != nullptr;
       space = spaces.Next()) {
    if (space->identity() == SHARED_SPACE && !is_shared_space_isolate) continue;
    total += space->SizeOfObjects();
  }
  total += heap_->lo_space()->SizeOfObjects();
  total += heap_->code_lo_space()->SizeOfObjects();
  if (heap_->shared_lo_space() && is_shared_space_isolate) {
    total += heap_->shared_lo_space()->SizeOfObjects();
  }
  return total;
}
References v8::internal::Heap::code_lo_space(), heap_, v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::isolate(), v8::internal::Heap::lo_space(), v8::internal::PagedSpaceIterator::Next(), v8::internal::Heap::shared_lo_space(), v8::internal::SHARED_SPACE, v8::internal::LargeObjectSpace::SizeOfObjects(), and space.
Referenced by GetScheduledBytes().
operator=()
IncrementalMarking& v8::internal::IncrementalMarking::operator= (const IncrementalMarking &) [delete]
PauseBlackAllocation()
void v8::internal::IncrementalMarking::PauseBlackAllocation () [private]
Definition at line 399 of file incremental-marking.cc.
                                              {
  DCHECK(IsMajorMarking());
  if (!v8_flags.black_allocated_pages) {
    heap()->allocator()->UnmarkLinearAllocationsArea();
    if (isolate()->is_shared_space_isolate()) {
      isolate()->global_safepoint()->IterateSharedSpaceAndClientIsolates(
          [](Isolate* client) {
            client->heap()->UnmarkSharedLinearAllocationAreas();
          });
    }
    heap()->safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
      local_heap->UnmarkLinearAllocationsArea();
    });
  }
  StopPointerTableBlackAllocation();
  if (v8_flags.trace_incremental_marking) {
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Black allocation paused\n");
  }
  black_allocation_ = false;
}
References v8::internal::Heap::allocator(), black_allocation_, v8::internal::DCHECK(), v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), heap(), IsMajorMarking(), isolate(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), v8::internal::GlobalSafepoint::IterateSharedSpaceAndClientIsolates(), v8::internal::Heap::safepoint(), StopPointerTableBlackAllocation(), v8::internal::HeapAllocator::UnmarkLinearAllocationsArea(), v8::internal::LocalHeap::UnmarkLinearAllocationsArea(), and v8::internal::v8_flags.
PublishWriteBarrierWorklists()
void v8::internal::IncrementalMarking::PublishWriteBarrierWorklists () [private]
schedule()
std::shared_ptr<::heap::base::IncrementalMarkingSchedule> v8::internal::IncrementalMarking::schedule () [inline]
Definition at line 123 of file incremental-marking.h.
                                                               {
    return schedule_;
  }
ShouldFinalize()
bool v8::internal::IncrementalMarking::ShouldFinalize () const [private]
Definition at line 721 of file incremental-marking.cc.
                                              {
  DCHECK(IsMarking());
  const auto* cpp_heap = CppHeap::From(heap_->cpp_heap());
  return heap()
             ->mark_compact_collector()
             ->local_marking_worklists()
             ->IsEmpty() &&
         (!cpp_heap || cpp_heap->ShouldFinalizeIncrementalMarking());
}
References v8::internal::Heap::cpp_heap(), v8::internal::DCHECK(), v8::internal::CppHeap::From(), heap(), heap_, IsMarking(), v8::internal::MarkCompactCollector::local_marking_worklists(), and v8::internal::Heap::mark_compact_collector().
ShouldWaitForTask()
bool v8::internal::IncrementalMarking::ShouldWaitForTask () [private]
Definition at line 570 of file incremental-marking.cc.
                                           {
  if (!completion_task_scheduled_) {
    if (!incremental_marking_job()) {
      return false;
    }
    incremental_marking_job()->ScheduleTask();
    completion_task_scheduled_ = true;
    if (!TryInitializeTaskTimeout()) {
      return false;
    }
  }
  const auto now = v8::base::TimeTicks::Now();
  const bool wait_for_task = now < completion_task_timeout_;
  if (V8_UNLIKELY(v8_flags.trace_incremental_marking)) {
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Completion: %s GC via stack guard, time left: "
        "%.1fms\n",
        wait_for_task ? "Delaying" : "Not delaying",
        (completion_task_timeout_ - now).InMillisecondsF());
  }
  return wait_for_task;
}
References completion_task_scheduled_, completion_task_timeout_, incremental_marking_job(), isolate(), v8::base::TimeTicks::Now(), v8::internal::IncrementalMarkingJob::ScheduleTask(), TryInitializeTaskTimeout(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by AdvanceOnAllocation().
Start()
void v8::internal::IncrementalMarking::Start (GarbageCollector garbage_collector, GarbageCollectionReason gc_reason)
Definition at line 135 of file incremental-marking.cc.
                                                                  {
  CHECK(IsStopped());
  CHECK_IMPLIES(garbage_collector == GarbageCollector::MARK_COMPACTOR,
                !heap_->sweeping_in_progress());
  CHECK_IMPLIES(garbage_collector == GarbageCollector::MINOR_MARK_SWEEPER,
                !heap_->minor_sweeping_in_progress());
  // Do not invoke CanAndShouldBeStarted() here again because its return value
  // might change across multiple invocations (its internal state could be
  // updated concurrently from another thread between invocations).
  CHECK(CanBeStarted());
  // The "current isolate" must be set correctly so we can access pointer
  // tables.
  DCHECK_EQ(isolate(), Isolate::TryGetCurrent());
  if (V8_UNLIKELY(v8_flags.trace_incremental_marking)) {
    const size_t old_generation_size_mb =
        heap()->OldGenerationSizeOfObjects() / MB;
    const size_t old_generation_waste_mb =
        heap()->OldGenerationWastedBytes() / MB;
    const size_t old_generation_limit_mb =
        heap()->old_generation_allocation_limit() / MB;
    const size_t global_size_mb = heap()->GlobalSizeOfObjects() / MB;
    const size_t global_waste_mb = heap()->GlobalWastedBytes() / MB;
    const size_t global_limit_mb = heap()->global_allocation_limit() / MB;
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Start (%s): (size/waste/limit/slack) v8: %zuMB / "
        "%zuMB / %zuMB "
        "/ %zuMB global: %zuMB / %zuMB / %zuMB / %zuMB\n",
        ToString(gc_reason), old_generation_size_mb, old_generation_waste_mb,
        old_generation_limit_mb,
        old_generation_size_mb + old_generation_waste_mb >
                old_generation_limit_mb
            ? 0
            : old_generation_limit_mb - old_generation_size_mb,
        global_size_mb, global_waste_mb, global_limit_mb,
        global_size_mb + global_waste_mb > global_limit_mb
            ? 0
            : global_limit_mb - global_size_mb);
  }
  Counters* counters = isolate()->counters();
  const bool is_major = garbage_collector == GarbageCollector::MARK_COMPACTOR;
  if (is_major) {
    // Reasons are only reported for major GCs
    counters->incremental_marking_reason()->AddSample(
        static_cast<int>(gc_reason));
  }
  NestedTimedHistogramScope incremental_marking_scope(
      is_major ? counters->gc_incremental_marking_start()
               : counters->gc_minor_incremental_marking_start());
  const auto scope_id = is_major ? GCTracer::Scope::MC_INCREMENTAL_START
                                 : GCTracer::Scope::MINOR_MS_INCREMENTAL_START;
  DCHECK(!current_trace_id_.has_value());
  current_trace_id_.emplace(reinterpret_cast<uint64_t>(this) ^
                            heap_->tracer()->CurrentEpoch(scope_id));
  TRACE_EVENT2("v8",
               is_major ? "V8.GCIncrementalMarkingStart"
                        : "V8.GCMinorIncrementalMarkingStart",
               "epoch", heap_->tracer()->CurrentEpoch(scope_id), "reason",
               ToString(gc_reason));
  TRACE_GC_EPOCH_WITH_FLOW(heap()->tracer(), scope_id, ThreadKind::kMain,
                           current_trace_id_.value(),
                           TRACE_EVENT_FLAG_FLOW_OUT);
  heap_->tracer()->NotifyIncrementalMarkingStart();
  start_time_ = v8::base::TimeTicks::Now();
  completion_task_scheduled_ = false;
  completion_task_timeout_ = v8::base::TimeTicks();
  main_thread_marked_bytes_ = 0;
  bytes_marked_concurrently_ = 0;
  if (is_major) {
    StartMarkingMajor();
  } else {
    StartMarkingMinor();
  }
}
References bytes_marked_concurrently_, CanBeStarted(), CHECK, CHECK_IMPLIES, completion_task_scheduled_, completion_task_timeout_, v8::internal::Isolate::counters(), current_trace_id_, v8::internal::GCTracer::CurrentEpoch(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Heap::global_allocation_limit(), v8::internal::Heap::GlobalSizeOfObjects(), v8::internal::Heap::GlobalWastedBytes(), heap(), heap_, isolate(), IsStopped(), v8::internal::kMain, main_thread_marked_bytes_, v8::internal::MARK_COMPACTOR, v8::internal::MB, v8::internal::MINOR_MARK_SWEEPER, v8::internal::Heap::minor_sweeping_in_progress(), v8::internal::GCTracer::NotifyIncrementalMarkingStart(), v8::base::TimeTicks::Now(), v8::internal::Heap::old_generation_allocation_limit(), v8::internal::Heap::OldGenerationSizeOfObjects(), v8::internal::Heap::OldGenerationWastedBytes(), start_time_, StartMarkingMajor(), StartMarkingMinor(), v8::internal::Heap::sweeping_in_progress(), v8::internal::ToString(), TRACE_EVENT2, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, v8::internal::Heap::tracer(), v8::Isolate::TryGetCurrent(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Heap::StartIncrementalMarking().
StartBlackAllocation()
void v8::internal::IncrementalMarking::StartBlackAllocation () [private]
Definition at line 362 of file incremental-marking.cc.
                                              {
  DCHECK(!black_allocation_);
  DCHECK(IsMajorMarking());
  black_allocation_ = true;
  if (v8_flags.black_allocated_pages) {
    heap()->allocator()->FreeLinearAllocationAreasAndResetFreeLists();
  } else {
    heap()->allocator()->MarkLinearAllocationAreasBlack();
  }
  if (isolate()->is_shared_space_isolate()) {
    isolate()->global_safepoint()->IterateSharedSpaceAndClientIsolates(
        [](Isolate* client) {
          if (v8_flags.black_allocated_pages) {
            client->heap()->FreeSharedLinearAllocationAreasAndResetFreeLists();
          } else {
            client->heap()->MarkSharedLinearAllocationAreasBlack();
          }
        });
  }
  heap()->safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    if (v8_flags.black_allocated_pages) {
      // The freelists of the underlying spaces must anyway be empty after the
      // first call to FreeLinearAllocationAreasAndResetFreeLists(). However,
      // don't call FreeLinearAllocationAreas(), since it also frees the
      // shared-space areas.
      local_heap->FreeLinearAllocationAreasAndResetFreeLists();
    } else {
      local_heap->MarkLinearAllocationAreasBlack();
    }
  });
  StartPointerTableBlackAllocation();
  if (v8_flags.trace_incremental_marking) {
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Black allocation started\n");
  }
}
References v8::internal::Heap::allocator(), black_allocation_, v8::internal::DCHECK(), v8::internal::HeapAllocator::FreeLinearAllocationAreasAndResetFreeLists(), v8::internal::Isolate::global_safepoint(), heap(), IsMajorMarking(), isolate(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), v8::internal::GlobalSafepoint::IterateSharedSpaceAndClientIsolates(), v8::internal::HeapAllocator::MarkLinearAllocationAreasBlack(), v8::internal::Heap::safepoint(), StartPointerTableBlackAllocation(), and v8::internal::v8_flags.
Referenced by StartMarkingMajor().
StartMarkingMajor()
void v8::internal::IncrementalMarking::StartMarkingMajor () [private]
Definition at line 240 of file incremental-marking.cc.
                                           {
  if (isolate()->serializer_enabled()) {
    // Black allocation currently starts when we start incremental marking,
    // but we cannot enable black allocation while deserializing. Hence, we
    // have to delay the start of incremental marking in that case.
    if (v8_flags.trace_incremental_marking) {
      isolate()->PrintWithTimestamp(
          "[IncrementalMarking] Start delayed - serializer\n");
    }
    return;
  }
  if (v8_flags.trace_incremental_marking) {
    isolate()->PrintWithTimestamp("[IncrementalMarking] Start marking\n");
  }
  heap_->InvokeIncrementalMarkingPrologueCallbacks();
  // Free all existing LABs in the heap such that selecting evacuation
  // candidates does not need to deal with LABs on a page. While we don't need
  // this for correctness, we want to avoid creating additional work for
  // evacuation.
  heap_->FreeLinearAllocationAreas();
  is_compacting_ = major_collector_->StartCompaction(
      MarkCompactCollector::StartCompactionMode::kIncremental);
  // The schedule is acquired for CppHeap as well. Initialize it early.
  schedule_ =
      ::heap::base::IncrementalMarkingSchedule::Create(v8_flags.predictable);
  schedule_->NotifyIncrementalMarkingStart();
  if (v8_flags.incremental_marking_unified_schedule) {
    major_collector_->StartMarking(schedule_);
  } else {
    major_collector_->StartMarking();
  }
  current_local_marking_worklists_ =
      major_collector_->local_marking_worklists();
  marking_mode_ = MarkingMode::kMajorMarking;
  heap_->SetIsMarkingFlag(true);
  MarkingBarrier::ActivateAll(heap(), is_compacting_);
  isolate()->traced_handles()->SetIsMarking(true);
  StartBlackAllocation();
  {
    TRACE_GC(heap()->tracer(), GCTracer::Scope::MC_MARK_ROOTS);
    MarkRoots();
  }
  if (v8_flags.concurrent_marking && !heap_->IsTearingDown()) {
    heap_->concurrent_marking()->TryScheduleJob(
        GarbageCollector::MARK_COMPACTOR);
  }
  // Ready to start incremental marking.
  if (v8_flags.trace_incremental_marking) {
    isolate()->PrintWithTimestamp("[IncrementalMarking] Running\n");
  }
  if (heap()->cpp_heap()) {
    // `StartMarking()` may call back into V8 in corner cases, requiring that
    // marking (including write barriers) is fully set up.
    TRACE_GC(heap()->tracer(), GCTracer::Scope::MC_MARK_EMBEDDER_PROLOGUE);
    CppHeap::From(heap()->cpp_heap())->StartMarking();
  }
  heap_->InvokeIncrementalMarkingEpilogueCallbacks();
  heap_->allocator()->AddAllocationObserver(&old_generation_observer_,
                                            &new_generation_observer_);
  if (incremental_marking_job()) {
    incremental_marking_job()->ScheduleTask();
  }
}
References v8::internal::MarkingBarrier::ActivateAll(), v8::internal::HeapAllocator::AddAllocationObserver(), v8::internal::Heap::allocator(), v8::internal::Heap::concurrent_marking(), heap::base::IncrementalMarkingSchedule::Create(), current_local_marking_worklists_, v8::internal::Heap::FreeLinearAllocationAreas(), v8::internal::CppHeap::From(), heap(), heap_, incremental_marking_job(), v8::internal::Heap::InvokeIncrementalMarkingEpilogueCallbacks(), v8::internal::Heap::InvokeIncrementalMarkingPrologueCallbacks(), is_compacting_, isolate(), v8::internal::Heap::IsTearingDown(), v8::internal::MarkCompactCollector::kIncremental, v8::internal::kMajorMarking, v8::internal::MarkCompactCollector::local_marking_worklists(), major_collector_, v8::internal::MARK_COMPACTOR, marking_mode_, MarkRoots(), new_generation_observer_, old_generation_observer_, schedule_, v8::internal::IncrementalMarkingJob::ScheduleTask(), v8::internal::TracedHandles::SetIsMarking(), v8::internal::Heap::SetIsMarkingFlag(), StartBlackAllocation(), v8::internal::MarkCompactCollector::StartCompaction(), v8::internal::CppHeap::StartMarking(), v8::internal::MarkCompactCollector::StartMarking(), TRACE_GC, v8::internal::Isolate::traced_handles(), v8::internal::ConcurrentMarking::TryScheduleJob(), and v8::internal::v8_flags.
Referenced by Start().
StartMarkingMinor()
void v8::internal::IncrementalMarking::StartMarkingMinor () [private]
Definition at line 318 of file incremental-marking.cc.
                                           {
  // Removed serializer_enabled() check because we don't do black allocation.
  if (v8_flags.trace_incremental_marking) {
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] (MinorMS) Start marking\n");
  }
  // We only reach this code if Heap::ShouldUseBackgroundThreads() returned
  // true. So we can force the use of background threads here.
  minor_collector_->StartMarking(true);
  current_local_marking_worklists_ =
      minor_collector_->local_marking_worklists();
  marking_mode_ = MarkingMode::kMinorMarking;
  heap_->SetIsMarkingFlag(true);
  heap_->SetIsMinorMarkingFlag(true);
  {
    Sweeper::PauseMajorSweepingScope pause_sweeping_scope(heap_->sweeper());
    MarkingBarrier::ActivateYoung(heap());
  }
  {
    TRACE_GC(heap()->tracer(), GCTracer::Scope::MINOR_MS_MARK_INCREMENTAL_SEED);
    MarkRoots();
  }
  if (v8_flags.concurrent_minor_ms_marking && !heap_->IsTearingDown()) {
    local_marking_worklists()->PublishWork();
    heap_->concurrent_marking()->TryScheduleJob(
        GarbageCollector::MINOR_MARK_SWEEPER);
  }
  if (v8_flags.trace_incremental_marking) {
    isolate()->PrintWithTimestamp("[IncrementalMarking] (MinorMS) Running\n");
  }
  DCHECK(!is_compacting_);
  // Allocation observers are not currently used by MinorMS because we don't
  // do incremental marking.
}
References v8::internal::MarkingBarrier::ActivateYoung(), v8::internal::Heap::concurrent_marking(), current_local_marking_worklists_, v8::internal::DCHECK(), heap(), heap_, is_compacting_, isolate(), v8::internal::Heap::IsTearingDown(), v8::internal::kMinorMarking, v8::internal::MinorMarkSweepCollector::local_marking_worklists(), local_marking_worklists(), marking_mode_, MarkRoots(), minor_collector_, v8::internal::MINOR_MARK_SWEEPER, v8::internal::Heap::SetIsMarkingFlag(), v8::internal::Heap::SetIsMinorMarkingFlag(), v8::internal::MinorMarkSweepCollector::StartMarking(), v8::internal::Heap::sweeper(), TRACE_GC, v8::internal::ConcurrentMarking::TryScheduleJob(), and v8::internal::v8_flags.
Referenced by Start().
StartPointerTableBlackAllocation()
void v8::internal::IncrementalMarking::StartPointerTableBlackAllocation () [private]
Definition at line 437 of file incremental-marking.cc.
                                                          {
#ifdef V8_COMPRESS_POINTERS
  heap()->old_external_pointer_space()->set_allocate_black(true);
  heap()->cpp_heap_pointer_space()->set_allocate_black(true);
#endif // V8_COMPRESS_POINTERS
#ifdef V8_ENABLE_SANDBOX
  heap()->code_pointer_space()->set_allocate_black(true);
  heap()->trusted_pointer_space()->set_allocate_black(true);
  if (isolate()->is_shared_space_isolate()) {
    isolate()->shared_trusted_pointer_space()->set_allocate_black(true);
  }
#endif // V8_ENABLE_SANDBOX
#ifdef V8_ENABLE_LEAPTIERING
  heap()->js_dispatch_table_space()->set_allocate_black(true);
#endif // V8_ENABLE_LEAPTIERING
}
References heap(), and isolate().
Referenced by StartBlackAllocation().
Step()
void v8::internal::IncrementalMarking::Step (v8::base::TimeDelta max_duration, size_t max_bytes_to_process, StepOrigin step_origin) [private]
Definition at line 747 of file incremental-marking.cc.
                                                      {
  NestedTimedHistogramScope incremental_marking_scope(
      isolate()->counters()->gc_incremental_marking());
  TRACE_EVENT1("v8", "V8.GCIncrementalMarking", "epoch",
               heap_->tracer()->CurrentEpoch(GCTracer::Scope::MC_INCREMENTAL));
  TRACE_GC_EPOCH_WITH_FLOW(
      heap_->tracer(), GCTracer::Scope::MC_INCREMENTAL, ThreadKind::kMain,
      current_trace_id_.value(),
      TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
  DCHECK(IsMajorMarking());
  const auto start = v8::base::TimeTicks::Now();
  std::optional<SafepointScope> safepoint_scope;
  // Conceptually an incremental marking step (even though it always runs on the
  // main thread) may introduce a form of concurrent marking when background
  // threads access the heap concurrently (e.g. concurrent compilation). On
  // builds that verify concurrent heap accesses this may lead to false positive
  // reports. We can avoid this by stopping background threads just in this
  // configuration. This should not hide potential issues because the concurrent
  // marker doesn't rely on correct synchronization but e.g. on black allocation
  // and the on_hold worklist.
#ifndef V8_ATOMIC_OBJECT_FIELD_WRITES
  {
    DCHECK(!v8_flags.concurrent_marking);
    // Ensure that the isolate has no shared heap. Otherwise a shared GC might
    // happen when trying to enter the safepoint.
    DCHECK(!isolate()->has_shared_space());
    AllowGarbageCollection allow_gc;
    safepoint_scope.emplace(isolate(), SafepointKind::kIsolate);
  }
#endif
  if (V8_LIKELY(v8_flags.concurrent_marking)) {
    // It is safe to merge back all objects that were on hold to the shared
    // work list at Step because we are at a safepoint where all objects
    // are properly initialized. The exception is the last allocated object
    // before invoking an AllocationObserver. This allocation had no way to
    // escape and get marked though.
    local_marking_worklists()->MergeOnHold();
    heap()->mark_compact_collector()->MaybeEnableBackgroundThreadsInCycle(
        MarkCompactCollector::CallOrigin::kIncrementalMarkingStep);
  }
  if (step_origin == StepOrigin::kTask) {
    // We cannot publish the pending allocations for V8 step origin because the
    // last object was allocated before invoking the step.
    heap()->PublishMainThreadPendingAllocations();
  }
  // Perform a single V8 and a single embedder step. In case both have been
  // observed as empty back to back, we can finalize.
  //
  // This ignores that case where the embedder finds new V8-side objects. The
  // assumption is that large graphs are well connected and can mostly be
  // processed on their own. For small graphs, helping is not necessary.
  //
  // The idea of a unified incremental marking step is the following:
  // - We use a single schedule for both V8 and CppHeap.
  // - Process CppHeap first in here as there's some objects in there that can
  // only be processed on the main thread.
  // - Use the left over time and bytes for a V8 step.
  // - We ignore the case where both individual steps discover new references to
  // each other and assume that graphs are generally well connected.
  // - Always flush objects to enable concurrent marking to make progress.
  // Start with a CppHeap step as there's objects on CppHeap that must be marked
  // on the main thread.
  v8::base::TimeDelta cpp_heap_duration;
  size_t cpp_heap_marked_bytes;
  std::tie(cpp_heap_duration, cpp_heap_marked_bytes) =
      CppHeapStep(max_duration, marked_bytes_limit);
  // Add an optional V8 step if we are not exceeding our limits.
  size_t v8_marked_bytes = 0;
  v8::base::TimeDelta v8_time;
  if (cpp_heap_duration < max_duration &&
      (!v8_flags.incremental_marking_unified_schedule ||
       (cpp_heap_marked_bytes < marked_bytes_limit))) {
    const auto v8_start = v8::base::TimeTicks::Now();
    const size_t v8_marked_bytes_limit =
        v8_flags.incremental_marking_unified_schedule
            ? marked_bytes_limit - cpp_heap_marked_bytes
            : marked_bytes_limit;
    std::tie(v8_marked_bytes, std::ignore) =
        major_collector_->ProcessMarkingWorklist(
            max_duration - cpp_heap_duration, v8_marked_bytes_limit);
    v8_time = v8::base::TimeTicks::Now() - v8_start;
    heap_->tracer()->AddIncrementalMarkingStep(v8_time.InMillisecondsF(),
                                               v8_marked_bytes);
  }
  if (V8_LIKELY(v8_flags.concurrent_marking)) {
    local_marking_worklists()->ShareWork();
    heap_->concurrent_marking()->RescheduleJobIfNeeded(
        GarbageCollector::MARK_COMPACTOR);
  }
  if (V8_UNLIKELY(v8_flags.trace_incremental_marking)) {
    const auto v8_max_duration = max_duration - cpp_heap_duration;
    const auto v8_marked_bytes_limit =
        marked_bytes_limit - cpp_heap_marked_bytes;
    isolate()->PrintWithTimestamp(
        "[IncrementalMaring] Step: origin: %s overall: %.1fms "
        "V8: %zuKB (%zuKB), %.1fms (%.1fms), %.1fMB/s "
        "CppHeap: %zuKB (%zuKB), %.1fms (%.1fms)\n",
        ToString(step_origin),
        (v8::base::TimeTicks::Now() - start).InMillisecondsF(), v8_marked_bytes,
        v8_marked_bytes_limit, v8_time.InMillisecondsF(),
        v8_max_duration.InMillisecondsF(),
        heap()->tracer()->IncrementalMarkingSpeedInBytesPerMillisecond() *
            1000 / MB,
        cpp_heap_marked_bytes, marked_bytes_limit,
        cpp_heap_duration.InMillisecondsF(), max_duration.InMillisecondsF());
  }
}
References v8::internal::GCTracer::AddIncrementalMarkingStep(), v8::internal::Heap::concurrent_marking(), CppHeapStep(), current_trace_id_, v8::internal::GCTracer::CurrentEpoch(), v8::internal::DCHECK(), heap(), heap_, wasm::ignore(), v8::base::TimeDelta::InMillisecondsF(), IsMajorMarking(), isolate(), v8::internal::MarkCompactCollector::kIncrementalMarkingStep, v8::internal::kIsolate, v8::internal::kMain, v8::internal::kTask, local_marking_worklists(), major_collector_, v8::internal::Heap::mark_compact_collector(), v8::internal::MARK_COMPACTOR, v8::internal::MarkCompactCollector::MaybeEnableBackgroundThreadsInCycle(), v8::internal::MB, v8::base::TimeTicks::Now(), v8::internal::MarkCompactCollector::ProcessMarkingWorklist(), v8::internal::Heap::PublishMainThreadPendingAllocations(), v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), v8::internal::ToString(), TRACE_EVENT1, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, v8::internal::Heap::tracer(), v8::internal::v8_flags, V8_LIKELY, and V8_UNLIKELY.
Referenced by AdvanceAndFinalizeIfComplete(), AdvanceForTesting(), and AdvanceOnAllocation().
Stop()
bool v8::internal::IncrementalMarking::Stop ()
Definition at line 486 of file incremental-marking.cc.
                              {
  if (IsStopped()) return false;
  if (v8_flags.trace_incremental_marking) {
    int old_generation_size_mb =
        static_cast<int>(heap()->OldGenerationSizeOfObjects() / MB);
    int old_generation_waste_mb =
        static_cast<int>(heap()->OldGenerationWastedBytes() / MB);
    int old_generation_limit_mb =
        static_cast<int>(heap()->old_generation_allocation_limit() / MB);
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Stopping: old generation size %dMB, waste %dMB, "
        "limit %dMB, "
        "overshoot %dMB\n",
        old_generation_size_mb, old_generation_waste_mb,
        old_generation_limit_mb,
        std::max(0, old_generation_size_mb + old_generation_waste_mb -
                        old_generation_limit_mb));
  }
  if (IsMajorMarking()) {
    heap()->allocator()->RemoveAllocationObserver(&old_generation_observer_,
                                                  &new_generation_observer_);
    major_collection_requested_via_stack_guard_ = false;
    isolate()->stack_guard()->ClearGC();
  }
  marking_mode_ = MarkingMode::kNoMarking;
  current_local_marking_worklists_ = nullptr;
  current_trace_id_.reset();
  if (isolate()->has_shared_space() && !isolate()->is_shared_space_isolate()) {
    // When disabling local incremental marking in a client isolate (= worker
    // isolate), the marking barrier needs to stay enabled when incremental
    // marking in the shared heap is running.
    const bool is_marking = isolate()
                                ->shared_space_isolate()
                                ->heap()
                                ->incremental_marking()
                                ->IsMajorMarking();
    heap_->SetIsMarkingFlag(is_marking);
  } else {
    heap_->SetIsMarkingFlag(false);
  }
  heap_->SetIsMinorMarkingFlag(false);
  is_compacting_ = false;
  FinishBlackAllocation();
  // Merge live bytes counters of background threads
  for (const auto& pair : background_live_bytes_) {
    MutablePageMetadata* memory_chunk = pair.first;
    intptr_t live_bytes = pair.second;
    if (live_bytes) {
      memory_chunk->IncrementLiveBytesAtomically(live_bytes);
    }
  }
  background_live_bytes_.clear();
  schedule_.reset();
  return true;
}
References v8::internal::Heap::allocator(), background_live_bytes_, current_local_marking_worklists_, current_trace_id_, FinishBlackAllocation(), v8::internal::Isolate::heap(), heap(), heap_, v8::internal::Heap::incremental_marking(), v8::internal::MutablePageMetadata::IncrementLiveBytesAtomically(), is_compacting_, IsMajorMarking(), isolate(), IsStopped(), v8::internal::kNoMarking, major_collection_requested_via_stack_guard_, marking_mode_, v8::internal::MB, new_generation_observer_, v8::internal::Heap::old_generation_allocation_limit(), old_generation_observer_, v8::internal::Heap::OldGenerationSizeOfObjects(), v8::internal::Heap::OldGenerationWastedBytes(), v8::internal::HeapAllocator::RemoveAllocationObserver(), schedule_, v8::internal::Heap::SetIsMarkingFlag(), v8::internal::Heap::SetIsMinorMarkingFlag(), v8::internal::Isolate::shared_space_isolate(), v8::internal::Isolate::stack_guard(), and v8::internal::v8_flags.
StopPointerTableBlackAllocation()
void v8::internal::IncrementalMarking::StopPointerTableBlackAllocation () [private]
Definition at line 454 of file incremental-marking.cc.
                                                         {
#ifdef V8_COMPRESS_POINTERS
  heap()->old_external_pointer_space()->set_allocate_black(false);
  heap()->cpp_heap_pointer_space()->set_allocate_black(false);
#endif // V8_COMPRESS_POINTERS
#ifdef V8_ENABLE_SANDBOX
  heap()->code_pointer_space()->set_allocate_black(false);
  heap()->trusted_pointer_space()->set_allocate_black(false);
  if (isolate()->is_shared_space_isolate()) {
    heap()->isolate()->shared_trusted_pointer_space()->set_allocate_black(
        false);
  }
#endif // V8_ENABLE_SANDBOX
#ifdef V8_ENABLE_LEAPTIERING
  heap()->js_dispatch_table_space()->set_allocate_black(false);
#endif // V8_ENABLE_LEAPTIERING
}
References heap(), v8::internal::Heap::isolate(), and isolate().
Referenced by FinishBlackAllocation(), and PauseBlackAllocation().
TryInitializeTaskTimeout()
bool v8::internal::IncrementalMarking::TryInitializeTaskTimeout () [private]
Definition at line 594 of file incremental-marking.cc.
                                                  {
  DCHECK_NOT_NULL(incremental_marking_job());
  // Allowed overshoot percentage of incremental marking walltime.
  constexpr double kAllowedOvershootPercentBasedOnWalltime = 0.1;
  // Minimum overshoot in ms. This is used to allow moving away from stack
  // when marking was fast.
  constexpr auto kMinAllowedOvershoot =
      v8::base::TimeDelta::FromMilliseconds(50);
  const auto now = v8::base::TimeTicks::Now();
  const auto allowed_overshoot = std::max(
      kMinAllowedOvershoot, v8::base::TimeDelta::FromMillisecondsD(
                                (now - start_time_).InMillisecondsF() *
                                kAllowedOvershootPercentBasedOnWalltime));
  const auto optional_avg_time_to_marking_task =
      incremental_marking_job()->AverageTimeToTask();
  // Only allowed to delay if the recorded average exists and is below the
  // threshold.
  bool delaying =
      optional_avg_time_to_marking_task.has_value() &&
      optional_avg_time_to_marking_task.value() <= allowed_overshoot;
  const auto optional_time_to_current_task =
      incremental_marking_job()->CurrentTimeToTask();
  // Don't bother delaying if the currently scheduled task is already waiting
  // too long.
  delaying =
      delaying && (!optional_time_to_current_task.has_value() ||
                   optional_time_to_current_task.value() <= allowed_overshoot);
  if (delaying) {
    const auto delta =
        !optional_time_to_current_task.has_value()
            ? allowed_overshoot
            : allowed_overshoot - optional_time_to_current_task.value();
    completion_task_timeout_ = now + delta;
  }
  DCHECK_IMPLIES(!delaying, completion_task_timeout_ <= now);
  if (V8_UNLIKELY(v8_flags.trace_incremental_marking)) {
    isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Completion: %s GC via stack guard, "
        "avg time to task: %.1fms, current time to task: %.1fms allowed "
        "overshoot: %.1fms\n",
        delaying ? "Delaying" : "Not delaying",
        optional_avg_time_to_marking_task.has_value()
            ? optional_avg_time_to_marking_task->InMillisecondsF()
            : NAN,
        optional_time_to_current_task.has_value()
            ? optional_time_to_current_task->InMillisecondsF()
            : NAN,
        allowed_overshoot.InMillisecondsF());
  }
  return delaying;
}
References v8::internal::IncrementalMarkingJob::AverageTimeToTask(), completion_task_timeout_, v8::internal::IncrementalMarkingJob::CurrentTimeToTask(), DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::base::TimeDelta::FromMilliseconds(), v8::base::TimeDelta::FromMillisecondsD(), incremental_marking_job(), isolate(), v8::base::TimeTicks::Now(), start_time_, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by ShouldWaitForTask().
Friends And Related Function Documentation
IncrementalMarkingJob
friend class IncrementalMarkingJob [friend]
Definition at line 206 of file incremental-marking.h.
Member Data Documentation
background_live_bytes_
std::unordered_map<MutablePageMetadata*, intptr_t, base::hash<MutablePageMetadata*> > v8::internal::IncrementalMarking::background_live_bytes_ [private]
Definition at line 202 of file incremental-marking.h.
Referenced by MarkBlackBackground(), and Stop().
background_live_bytes_mutex_
base::Mutex v8::internal::IncrementalMarking::background_live_bytes_mutex_ [private]
Definition at line 199 of file incremental-marking.h.
Referenced by MarkBlackBackground().
black_allocation_
bool v8::internal::IncrementalMarking::black_allocation_ = false [private]
Definition at line 192 of file incremental-marking.h.
Referenced by FinishBlackAllocation(), PauseBlackAllocation(), and StartBlackAllocation().
bytes_marked_concurrently_
size_t v8::internal::IncrementalMarking::bytes_marked_concurrently_ = 0 [private]
Definition at line 188 of file incremental-marking.h.
Referenced by FetchBytesMarkedConcurrently(), and Start().
completion_task_scheduled_
bool v8::internal::IncrementalMarking::completion_task_scheduled_ = false [private]
Definition at line 193 of file incremental-marking.h.
Referenced by ShouldWaitForTask(), and Start().
completion_task_timeout_
v8::base::TimeTicks v8::internal::IncrementalMarking::completion_task_timeout_ [private]
Definition at line 194 of file incremental-marking.h.
Referenced by ShouldWaitForTask(), Start(), and TryInitializeTaskTimeout().
current_local_marking_worklists_
MarkingWorklists::Local* v8::internal::IncrementalMarking::current_local_marking_worklists_ = nullptr [private]
Definition at line 182 of file incremental-marking.h.
Referenced by StartMarkingMajor(), StartMarkingMinor(), and Stop().
current_trace_id_
std::optional<uint64_t> v8::internal::IncrementalMarking::current_trace_id_ [private]
Definition at line 204 of file incremental-marking.h.
Referenced by Start(), Step(), and Stop().
heap_
Heap* const v8::internal::IncrementalMarking::heap_ [private]
Definition at line 178 of file incremental-marking.h.
Referenced by AdvanceAndFinalizeIfNecessary(), AdvanceOnAllocation(), CanAndShouldBeStarted(), CanBeStarted(), CppHeapStep(), GetScheduledBytes(), IsBelowActivationThresholds(), isolate(), MarkRoots(), OldGenerationSizeOfObjects(), ShouldFinalize(), Start(), StartMarkingMajor(), StartMarkingMinor(), Step(), and Stop().
incremental_marking_job_
std::unique_ptr<IncrementalMarkingJob> v8::internal::IncrementalMarking::incremental_marking_job_ [private]
Definition at line 196 of file incremental-marking.h.
is_compacting_
bool v8::internal::IncrementalMarking::is_compacting_ = false [private]
Definition at line 191 of file incremental-marking.h.
Referenced by StartMarkingMajor(), StartMarkingMinor(), and Stop().
main_thread_marked_bytes_
size_t v8::internal::IncrementalMarking::main_thread_marked_bytes_ = 0 [private]
Definition at line 185 of file incremental-marking.h.
Referenced by Start().
major_collection_requested_via_stack_guard_
bool v8::internal::IncrementalMarking::major_collection_requested_via_stack_guard_ = false [private]
Definition at line 195 of file incremental-marking.h.
Referenced by AdvanceAndFinalizeIfNecessary(), AdvanceOnAllocation(), and Stop().
major_collector_
MarkCompactCollector* const v8::internal::IncrementalMarking::major_collector_ [private]
Definition at line 179 of file incremental-marking.h.
Referenced by StartMarkingMajor(), and Step().
marking_mode_
MarkingMode v8::internal::IncrementalMarking::marking_mode_ = MarkingMode::kNoMarking [private]
Definition at line 189 of file incremental-marking.h.
Referenced by StartMarkingMajor(), StartMarkingMinor(), and Stop().
marking_state_
MarkingState* const v8::internal::IncrementalMarking::marking_state_ [private]
Definition at line 183 of file incremental-marking.h.
minor_collector_
MinorMarkSweepCollector* const v8::internal::IncrementalMarking::minor_collector_ [private]
Definition at line 180 of file incremental-marking.h.
Referenced by StartMarkingMinor().
new_generation_observer_
Observer v8::internal::IncrementalMarking::new_generation_observer_ [private]
Definition at line 197 of file incremental-marking.h.
Referenced by StartMarkingMajor(), and Stop().
old_generation_observer_
Observer v8::internal::IncrementalMarking::old_generation_observer_ [private]
Definition at line 198 of file incremental-marking.h.
Referenced by StartMarkingMajor(), and Stop().
schedule_
std::shared_ptr<::heap::base::IncrementalMarkingSchedule> v8::internal::IncrementalMarking::schedule_ [private]
Definition at line 203 of file incremental-marking.h.
Referenced by FetchBytesMarkedConcurrently(), GetScheduledBytes(), StartMarkingMajor(), and Stop().
start_time_
v8::base::TimeTicks v8::internal::IncrementalMarking::start_time_ [private]
Definition at line 184 of file incremental-marking.h.
Referenced by Start(), and TryInitializeTaskTimeout().
weak_objects_
WeakObjects* v8::internal::IncrementalMarking::weak_objects_ [private]
Definition at line 181 of file incremental-marking.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/incremental-marking.h
/mnt/V8SourceCode/src/heap/incremental-marking.cc