v8::internal::Intl::FormatRangeSourceTracker Class Reference
#include <intl-objects.h>
Public Member Functions
FormatRangeSourceTracker ()
void Add (int32_t field, int32_t start, int32_t limit)
FormatRangeSource GetSource (int32_t start, int32_t limit) const
Private Member Functions
bool FieldContains (int32_t field, int32_t start, int32_t limit) const
Private Attributes
int32_t start_ [2]
int32_t limit_ [2]
Detailed Description
Definition at line 85 of file intl-objects.h.
Constructor & Destructor Documentation
FormatRangeSourceTracker()
v8::internal::Intl::FormatRangeSourceTracker::FormatRangeSourceTracker ()
Definition at line 3015 of file intl-objects.cc.
                                                       {
  start_[0] = start_[1] = limit_[0] = limit_[1] = 0;
}
References limit_, and start_.
Member Function Documentation
Add()
void v8::internal::Intl::FormatRangeSourceTracker::Add (int32_t field, int32_t start, int32_t limit)
Definition at line 3019 of file intl-objects.cc.
                                                        {
  DCHECK_LT(field, 2);
  start_[field] = start;
  limit_[field] = limit;
}
References DCHECK_LT.
Referenced by v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts(), and v8::internal::anonymous_namespace{js-date-time-format.cc}::FormattedDateIntervalToJSArray().
FieldContains()
bool v8::internal::Intl::FormatRangeSourceTracker::FieldContains (int32_t field, int32_t start, int32_t limit) const [private]
Definition at line 3037 of file intl-objects.cc.
                                                                        {
  DCHECK_LT(field, 2);
  return (start_[field] <= start) && (start <= limit_[field]) &&
         (start_[field] <= limit) && (limit <= limit_[field]);
}
References DCHECK_LT.
GetSource()
Intl::FormatRangeSource v8::internal::Intl::FormatRangeSourceTracker::GetSource (int32_t start, int32_t limit) const
Definition at line 3026 of file intl-objects.cc.
                                        {
  FormatRangeSource source = FormatRangeSource::kShared;
  if (FieldContains(0, start, limit)) {
    source = FormatRangeSource::kStartRange;
  } else if (FieldContains(1, start, limit)) {
    source = FormatRangeSource::kEndRange;
  }
  return source;
}
References v8::internal::Intl::kEndRange, v8::internal::Intl::kShared, and v8::internal::Intl::kStartRange.
Referenced by v8::internal::anonymous_namespace{js-date-time-format.cc}::AddPartForFormatRange(), and v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts().
Member Data Documentation
limit_
int32_t v8::internal::Intl::FormatRangeSourceTracker::limit_[2] [private]
Definition at line 93 of file intl-objects.h.
Referenced by FormatRangeSourceTracker().
start_
int32_t v8::internal::Intl::FormatRangeSourceTracker::start_[2] [private]
Definition at line 92 of file intl-objects.h.
Referenced by FormatRangeSourceTracker().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/intl-objects.h
/mnt/V8SourceCode/src/objects/intl-objects.cc