v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState Class Reference
Public Member Functions
RegExpParserState (RegExpParserState *previous_state, SubexpressionType group_type, RegExpLookaround::Type lookaround_type, int disjunction_capture_index, const ZoneVector< base::uc16 > *capture_name, RegExpFlags flags, Zone *zone)
RegExpParserState * previous_state () const
bool IsSubexpression ()
RegExpBuilder * builder ()
SubexpressionType group_type () const
RegExpLookaround::Type lookaround_type () const
int capture_index () const
const ZoneVector< base::uc16 > * capture_name () const
std::pair< int, int > non_participating_capture_group_interval () const
bool IsNamedCapture () const
bool IsInsideCaptureGroup (int index) const
bool IsInsideCaptureGroup (const ZoneVector< base::uc16 > *name) const
void NewAlternative (int captures_started)
Private Attributes
RegExpParserState *const previous_state_
RegExpBuilder builder_
const SubexpressionType group_type_
const RegExpLookaround::Type lookaround_type_
const int disjunction_capture_index_
const ZoneVector< base::uc16 > *const capture_name_
std::pair< int, int > non_participating_capture_group_interval_
Detailed Description
Definition at line 347 of file regexp-parser.cc.
Constructor & Destructor Documentation
RegExpParserState()
v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::RegExpParserState (RegExpParserState * previous_state, SubexpressionType group_type, RegExpLookaround::Type lookaround_type, int disjunction_capture_index, const ZoneVector< base::uc16 > * capture_name, RegExpFlags flags, Zone * zone) [inline]
Definition at line 350 of file regexp-parser.cc.
      : previous_state_(previous_state),
        builder_(zone, flags),
        group_type_(group_type),
        lookaround_type_(lookaround_type),
        disjunction_capture_index_(disjunction_capture_index),
        capture_name_(capture_name) {
    if (previous_state != nullptr) {
      non_participating_capture_group_interval_ =
          previous_state->non_participating_capture_group_interval();
    }
  }
References non_participating_capture_group_interval().
Member Function Documentation
builder()
RegExpBuilder* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::builder () [inline]
Definition at line 371 of file regexp-parser.cc.
{ return &builder_; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseOpenParenthesis().
capture_index()
int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::capture_index () const [inline]
Definition at line 379 of file regexp-parser.cc.
{ return disjunction_capture_index_; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
capture_name()
const ZoneVector<base::uc16>* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::capture_name () const [inline]
Definition at line 382 of file regexp-parser.cc.
{ return capture_name_; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::CreateNamedCaptureAtIndex().
group_type()
SubexpressionType v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::group_type () const [inline]
Definition at line 373 of file regexp-parser.cc.
{ return group_type_; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
IsInsideCaptureGroup() [1/2]
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::IsInsideCaptureGroup (const ZoneVector< base::uc16 > * name) const [inline]
Definition at line 403 of file regexp-parser.cc.
                                                                    {
    DCHECK_NOT_NULL(name);
    for (const RegExpParserState* s = this; s != nullptr;
         s = s->previous_state()) {
      if (s->capture_name() == nullptr) continue;
      if (*s->capture_name() == *name) return true;
    }
    return false;
  }
References DCHECK_NOT_NULL, v8::internal::name, and previous_state().
IsInsideCaptureGroup() [2/2]
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::IsInsideCaptureGroup (int index) const [inline]
Definition at line 390 of file regexp-parser.cc.
                                             {
    for (const RegExpParserState* s = this; s != nullptr;
         s = s->previous_state()) {
      if (s->group_type() != CAPTURE) continue;
      // Return true if we found the matching capture index.
      if (index == s->capture_index()) return true;
      // Abort if index is larger than what has been parsed up till this state.
      if (index > s->capture_index()) return false;
    }
    return false;
  }
References v8::internal::anonymous_namespace{regexp-parser.cc}::CAPTURE, v8::internal::index, and previous_state().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseNamedBackReference().
IsNamedCapture()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::IsNamedCapture () const [inline]
Definition at line 387 of file regexp-parser.cc.
{ return capture_name_ != nullptr; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
IsSubexpression()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::IsSubexpression () [inline]
Definition at line 369 of file regexp-parser.cc.
{ return previous_state_ != nullptr; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
lookaround_type()
RegExpLookaround::Type v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::lookaround_type () const [inline]
Definition at line 375 of file regexp-parser.cc.
{ return lookaround_type_; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseOpenParenthesis().
NewAlternative()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::NewAlternative (int captures_started) [inline]
Definition at line 413 of file regexp-parser.cc.
                                            {
    if (non_participating_capture_group_interval().second != 0) {
      // Extend the non-participating interval.
      non_participating_capture_group_interval_.second = captures_started;
    } else {
      // Create new non-participating interval from the start of the current
      // enclosing group to all captures created within that group so far.
      non_participating_capture_group_interval_ =
          std::make_pair(capture_index(), captures_started);
    }
  }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
non_participating_capture_group_interval()
std::pair<int, int> v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::non_participating_capture_group_interval () const [inline]
Definition at line 383 of file regexp-parser.cc.
                                                                     {
    return non_participating_capture_group_interval_;
  }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::CreateNamedCaptureAtIndex(), and RegExpParserState().
previous_state()
RegExpParserState* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::previous_state () const [inline]
Definition at line 368 of file regexp-parser.cc.
{ return previous_state_; }
Referenced by IsInsideCaptureGroup(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
Member Data Documentation
builder_
RegExpBuilder v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::builder_ [private]
Definition at line 429 of file regexp-parser.cc.
capture_name_
const ZoneVector<base::uc16>* const v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::capture_name_ [private]
Definition at line 437 of file regexp-parser.cc.
disjunction_capture_index_
const int v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::disjunction_capture_index_ [private]
Definition at line 435 of file regexp-parser.cc.
group_type_
const SubexpressionType v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::group_type_ [private]
Definition at line 431 of file regexp-parser.cc.
lookaround_type_
const RegExpLookaround::Type v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::lookaround_type_ [private]
Definition at line 433 of file regexp-parser.cc.
non_participating_capture_group_interval_
std::pair<int, int> v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::non_participating_capture_group_interval_ [private]
Definition at line 442 of file regexp-parser.cc.
previous_state_
RegExpParserState* const v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserState::previous_state_ [private]
Definition at line 427 of file regexp-parser.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-parser.cc