v8::internal::wasm::ObjectAccess Class Reference
#include <object-access.h>
Static Public Member Functions
static constexpr int ToTagged (int offset)
static constexpr int ElementOffsetInTaggedFixedArray (int index)
static constexpr int ElementOffsetInTaggedFixedUInt8Array (int index)
static constexpr int ElementOffsetInTaggedFixedUInt32Array (int index)
static constexpr int ElementOffsetInTaggedFixedAddressArray (int index)
static constexpr int ElementOffsetInTaggedTrustedFixedAddressArray (int index)
static constexpr int ElementOffsetInProtectedFixedArray (int index)
static constexpr int ContextOffsetInTaggedJSFunction ()
static constexpr int SharedFunctionInfoOffsetInTaggedJSFunction ()
static constexpr int FlagsOffsetInSharedFunctionInfo ()
Detailed Description
Definition at line 21 of file object-access.h.
Member Function Documentation
ContextOffsetInTaggedJSFunction()
static constexpr int v8::internal::wasm::ObjectAccess::ContextOffsetInTaggedJSFunction () [inline], [static], [constexpr]
Definition at line 58 of file object-access.h.
                                                         {
    return ToTagged(JSFunction::kContextOffset);
  }
References ToTagged().
Referenced by v8::internal::compiler::WasmGraphAssembler::LoadContextNoCellFromJSFunction().
ElementOffsetInProtectedFixedArray()
static constexpr int v8::internal::wasm::ObjectAccess::ElementOffsetInProtectedFixedArray (int index) [inline], [static], [constexpr]
Definition at line 53 of file object-access.h.
                                                                     {
    return ToTagged(ProtectedFixedArray::OffsetOfElementAt(index));
  }
References v8::internal::index, v8::internal::TaggedArrayBase< ProtectedFixedArray, ProtectedArrayShape, TrustedObjectLayout >::OffsetOfElementAt(), and ToTagged().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), and v8::internal::compiler::WasmGraphAssembler::LoadProtectedFixedArrayElement().
ElementOffsetInTaggedFixedAddressArray()
static constexpr int v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedFixedAddressArray (int index) [inline], [static], [constexpr]
Definition at line 42 of file object-access.h.
                                                                         {
    return ToTagged(FixedAddressArray::OffsetOfElementAt(index));
  }
References v8::internal::index, v8::internal::FixedIntegerArrayBase< Address, Base >::OffsetOfElementAt(), and ToTagged().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetBaseAndOffsetForImportedMutableExternRefGlobal(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetGlobalBaseAndOffset().
ElementOffsetInTaggedFixedArray()
static constexpr int v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedFixedArray (int index) [inline], [static], [constexpr]
Definition at line 27 of file object-access.h.
                                                                  {
    return ToTagged(FixedArray::OffsetOfElementAt(index));
  }
References v8::internal::index, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), and ToTagged().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ElemDrop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetBaseAndOffsetForImportedMutableExternRefGlobal(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Load16BitExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadExceptionValue(), v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElement(), v8::internal::compiler::WasmGCLowering::ReduceRttCanon(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RttCanon(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Store32BitExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreExceptionValue(), v8::internal::compiler::WasmGraphAssembler::StoreFixedArrayElement(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSize(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Throw().
ElementOffsetInTaggedFixedUInt32Array()
static constexpr int v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedFixedUInt32Array (int index) [inline], [static], [constexpr]
Definition at line 37 of file object-access.h.
                                                                        {
    return ToTagged(FixedUInt32Array::OffsetOfElementAt(index));
  }
References v8::internal::index, v8::internal::FixedIntegerArrayBase< T, Base >::OffsetOfElementAt(), and ToTagged().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::DataDrop().
ElementOffsetInTaggedFixedUInt8Array()
static constexpr int v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedFixedUInt8Array (int index) [inline], [static], [constexpr]
Definition at line 32 of file object-access.h.
                                                                       {
    return ToTagged(FixedUInt8Array::OffsetOfElementAt(index));
  }
References v8::internal::index, v8::internal::FixedIntegerArrayBase< T, Base >::OffsetOfElementAt(), and ToTagged().
ElementOffsetInTaggedTrustedFixedAddressArray()
static constexpr int v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedTrustedFixedAddressArray (int index) [inline], [static], [constexpr]
Definition at line 47 of file object-access.h.
                 {
    return ToTagged(TrustedFixedAddressArray::OffsetOfElementAt(index));
  }
References v8::internal::index, v8::internal::FixedIntegerArrayBase< Address, Base >::OffsetOfElementAt(), and ToTagged().
FlagsOffsetInSharedFunctionInfo()
static constexpr int v8::internal::wasm::ObjectAccess::FlagsOffsetInSharedFunctionInfo () [inline], [static], [constexpr]
Definition at line 68 of file object-access.h.
                                                         {
    return ToTagged(SharedFunctionInfo::kFlagsOffset);
  }
References ToTagged().
Referenced by v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildReceiverNode().
SharedFunctionInfoOffsetInTaggedJSFunction()
static constexpr int v8::internal::wasm::ObjectAccess::SharedFunctionInfoOffsetInTaggedJSFunction () [inline], [static], [constexpr]
Definition at line 63 of file object-access.h.
                                                                    {
    return ToTagged(JSFunction::kSharedFunctionInfoOffset);
  }
References ToTagged().
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_WasmResumeHelper(), and v8::internal::compiler::WasmGraphAssembler::LoadSharedFunctionInfo().
ToTagged()
static constexpr int v8::internal::wasm::ObjectAccess::ToTagged (int offset) [inline], [static], [constexpr]
Definition at line 24 of file object-access.h.
{ return offset - kHeapObjectTag; }
References v8::internal::kHeapObjectTag.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFillImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayLen(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewFixed(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArraySet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckArray(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckMem(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCallAndReturn(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper(), v8::internal::compiler::WasmGraphAssembler::BuildLoadExternalPointerFromObject(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallRefImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::LiftoffAssembler::CheckTierUp(), ContextOffsetInTaggedJSFunction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CurrentMemoryPages(), ElementOffsetInProtectedFixedArray(), ElementOffsetInTaggedFixedAddressArray(), ElementOffsetInTaggedFixedArray(), ElementOffsetInTaggedFixedUInt32Array(), ElementOffsetInTaggedFixedUInt8Array(), ElementOffsetInTaggedTrustedFixedAddressArray(), v8::internal::compiler::WasmGraphAssembler::FieldOffset(), FlagsOffsetInSharedFunctionInfo(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetMemoryStart_Slow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetRttFromDescriptorOnStack(), v8::internal::compiler::WasmGraphAssembler::LoadByteArrayElement(), v8::internal::compiler::WasmGraphAssembler::LoadExportedFunctionIndexAsSmi(), v8::internal::compiler::WasmGraphAssembler::LoadExportedFunctionInstanceData(), v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElement(), v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayLengthAsSmi(), v8::internal::compiler::WasmGraphAssembler::LoadFunctionDataFromJSFunction(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableFixedArrayElement(), v8::internal::compiler::WasmGraphAssembler::LoadInstanceType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadInstanceType(), v8::internal::compiler::WasmGraphAssembler::LoadJSArrayElements(), v8::internal::compiler::WasmGraphAssembler::LoadProtectedFixedArrayElement(), v8::internal::compiler::WasmGraphAssembler::LoadStringLength(), v8::internal::compiler::WasmGraphAssembler::LoadTrustedDataFromInstanceObject(), v8::internal::compiler::WasmGraphAssembler::LoadWasmTypeInfo(), v8::internal::compiler::WasmGraphAssembler::LoadWeakFixedArrayElement(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefGetDesc(), SharedFunctionInfoOffsetInTaggedJSFunction(), v8::internal::compiler::WasmGraphBuilder::Start(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringMeasureWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructFieldOffset(), v8::internal::wasm::StructFieldOffset(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSize(), v8::internal::compiler::anonymous_namespace{wasm-gc-lowering.cc}::TaggedOffset(), and v8::internal::compiler::WasmGraphAssembler::WasmArrayElementOffset().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/object-access.h