v8::internal::compiler::BytecodeAnalysis Class Reference
#include <bytecode-analysis.h>
Classes
class BytecodeAnalysisImpl
Public Member Functions
BytecodeAnalysis (Handle< BytecodeArray > bytecode_array, Zone *zone, BytecodeOffset osr_bailout_id, bool analyze_liveness)
BytecodeAnalysis (const BytecodeAnalysis &)=delete
BytecodeAnalysis & operator= (const BytecodeAnalysis &)=delete
bool IsLoopHeader (int offset) const
int GetLoopOffsetFor (int offset) const
int GetLoopEndOffsetForInnermost (int header_offset) const
const LoopInfo & GetLoopInfoFor (int header_offset) const
const LoopInfo * TryGetLoopInfoFor (int header_offset) const
const ZoneMap< int, LoopInfo > & GetLoopInfos () const
const ZoneVector< ResumeJumpTarget > & resume_jump_targets () const
const BytecodeLivenessState * GetInLivenessFor (int offset) const
const BytecodeLivenessState * GetOutLivenessFor (int offset) const
int osr_entry_point () const
BytecodeOffset osr_bailout_id () const
bool liveness_analyzed () const
int bytecode_count () const
Private Member Functions
BytecodeLivenessMap & liveness_map ()
const BytecodeLivenessMap & liveness_map () const
Private Attributes
BytecodeOffset const osr_bailout_id_
bool const analyze_liveness_
ZoneVector< ResumeJumpTarget > resume_jump_targets_
ZoneMap< int, int > end_to_header_
ZoneMap< int, LoopInfo > header_to_info_
int osr_entry_point_
std::optional< BytecodeLivenessMap > liveness_map_
int bytecode_count_ = -1
Friends
class BytecodeAnalysisImpl
Detailed Description
Definition at line 116 of file bytecode-analysis.h.
Constructor & Destructor Documentation
BytecodeAnalysis() [1/2]
v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysis (Handle< BytecodeArray > bytecode_array, Zone * zone, BytecodeOffset osr_bailout_id, bool analyze_liveness)
Definition at line 1165 of file bytecode-analysis.cc.
    : osr_bailout_id_(osr_bailout_id),
      analyze_liveness_(analyze_liveness),
      resume_jump_targets_(zone),
      end_to_header_(zone),
      header_to_info_(zone),
      osr_entry_point_(-1) {
  BytecodeAnalysisImpl analysis(*this, bytecode_array, zone);
  analysis.Analyze();
  DCHECK_IMPLIES(analyze_liveness_, liveness_map_.has_value());
  DCHECK_NE(bytecode_count_, -1);
}
References v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), analyze_liveness_, bytecode_count_, DCHECK_IMPLIES, DCHECK_NE, and liveness_map_.
BytecodeAnalysis() [2/2]
v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysis (const BytecodeAnalysis &) [delete]
Member Function Documentation
bytecode_count()
int v8::internal::compiler::BytecodeAnalysis::bytecode_count () const [inline]
Definition at line 162 of file bytecode-analysis.h.
{ return bytecode_count_; }
GetInLivenessFor()
const BytecodeLivenessState * v8::internal::compiler::BytecodeAnalysis::GetInLivenessFor (int offset) const
Definition at line 812 of file bytecode-analysis.cc.
                      {
  if (!analyze_liveness_) return nullptr;
  return liveness_map().GetInLiveness(offset);
}
References analyze_liveness_, v8::internal::compiler::BytecodeLivenessMap::GetInLiveness(), and liveness_map().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint().
GetLoopEndOffsetForInnermost()
int v8::internal::compiler::BytecodeAnalysis::GetLoopEndOffsetForInnermost (int header_offset) const
Definition at line 793 of file bytecode-analysis.cc.
                                                                          {
  DCHECK(GetLoopInfoFor(header_offset).innermost());
  auto loop_end_to_header = end_to_header_.upper_bound(header_offset + 1);
  DCHECK_EQ(loop_end_to_header->second, header_offset);
  return loop_end_to_header->first;
}
References v8::internal::DCHECK(), DCHECK_EQ, end_to_header_, and GetLoopInfoFor().
GetLoopInfoFor()
const LoopInfo & v8::internal::compiler::BytecodeAnalysis::GetLoopInfoFor (int header_offset) const
Definition at line 800 of file bytecode-analysis.cc.
                                                                        {
  DCHECK(IsLoopHeader(header_offset));
  return header_to_info_.find(header_offset)->second;
}
References v8::internal::DCHECK(), header_to_info_, and IsLoopHeader().
Referenced by GetLoopEndOffsetForInnermost().
GetLoopInfos()
const ZoneMap<int, LoopInfo>& v8::internal::compiler::BytecodeAnalysis::GetLoopInfos () const [inline]
Definition at line 136 of file bytecode-analysis.h.
{ return header_to_info_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates().
GetLoopOffsetFor()
int v8::internal::compiler::BytecodeAnalysis::GetLoopOffsetFor (int offset) const
Definition at line 760 of file bytecode-analysis.cc.
                                                       {
  auto loop_end_to_header = end_to_header_.upper_bound(offset);
  // If there is no next end => offset is not in a loop.
  if (loop_end_to_header == end_to_header_.end()) {
    return -1;
  }
  // If the header precedes the offset, this is the loop
  //
  // .> header <--loop_end_to_header
  // |
  // | <--offset
  // |
  // `- end
  if (loop_end_to_header->second <= offset) {
    return loop_end_to_header->second;
  }
  // Otherwise there is a (potentially nested) loop after this offset.
  //
  // <--offset
  //
  // .> header
  // |
  // | .> header <--loop_end_to_header
  // | |
  // | `- end
  // |
  // `- end
  // We just return the parent of the next loop (might be -1).
  DCHECK(header_to_info_.upper_bound(offset) != header_to_info_.end());
  return header_to_info_.upper_bound(offset)->second.parent_offset();
}
References v8::internal::DCHECK(), end_to_header_, and header_to_info_.
GetOutLivenessFor()
const BytecodeLivenessState * v8::internal::compiler::BytecodeAnalysis::GetOutLivenessFor (int offset) const
Definition at line 819 of file bytecode-analysis.cc.
                      {
  if (!analyze_liveness_) return nullptr;
  return liveness_map().GetOutLiveness(offset);
}
References analyze_liveness_, v8::internal::compiler::BytecodeLivenessMap::GetOutLiveness(), and liveness_map().
IsLoopHeader()
bool v8::internal::compiler::BytecodeAnalysis::IsLoopHeader (int offset) const
Definition at line 756 of file bytecode-analysis.cc.
                                                    {
  return header_to_info_.find(offset) != header_to_info_.end();
}
References header_to_info_.
Referenced by GetLoopInfoFor().
liveness_analyzed()
bool v8::internal::compiler::BytecodeAnalysis::liveness_analyzed () const [inline]
Definition at line 158 of file bytecode-analysis.h.
{ return analyze_liveness_; }
liveness_map() [1/2]
BytecodeLivenessMap& v8::internal::compiler::BytecodeAnalysis::liveness_map () [inline], [private]
Definition at line 165 of file bytecode-analysis.h.
                                      {
    DCHECK(analyze_liveness_);
    return *liveness_map_;
  }
References v8::internal::DCHECK().
Referenced by GetInLivenessFor(), and GetOutLivenessFor().
liveness_map() [2/2]
const BytecodeLivenessMap& v8::internal::compiler::BytecodeAnalysis::liveness_map () const [inline], [private]
Definition at line 169 of file bytecode-analysis.h.
                                                  {
    DCHECK(analyze_liveness_);
    return *liveness_map_;
  }
References v8::internal::DCHECK().
operator=()
BytecodeAnalysis& v8::internal::compiler::BytecodeAnalysis::operator= (const BytecodeAnalysis &) [delete]
osr_bailout_id()
BytecodeOffset v8::internal::compiler::BytecodeAnalysis::osr_bailout_id () const [inline]
Definition at line 155 of file bytecode-analysis.h.
{ return osr_bailout_id_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::bailout_for_entrypoint(), and v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForOSREntryStackCheck().
osr_entry_point()
int v8::internal::compiler::BytecodeAnalysis::osr_entry_point () const [inline]
Definition at line 150 of file bytecode-analysis.h.
                              {
    CHECK_LE(0, osr_entry_point_);
    return osr_entry_point_;
  }
References CHECK_LE.
resume_jump_targets()
const ZoneVector<ResumeJumpTarget>& v8::internal::compiler::BytecodeAnalysis::resume_jump_targets () const [inline]
Definition at line 139 of file bytecode-analysis.h.
                                                                  {
    return resume_jump_targets_;
  }
TryGetLoopInfoFor()
const LoopInfo * v8::internal::compiler::BytecodeAnalysis::TryGetLoopInfoFor (int header_offset) const
Definition at line 806 of file bytecode-analysis.cc.
                                                                           {
  auto it = header_to_info_.find(header_offset);
  if (it == header_to_info_.end()) return nullptr;
  return &it->second;
}
References header_to_info_.
Friends And Related Function Documentation
BytecodeAnalysisImpl
friend class BytecodeAnalysisImpl [friend]
Definition at line 184 of file bytecode-analysis.h.
Member Data Documentation
analyze_liveness_
bool const v8::internal::compiler::BytecodeAnalysis::analyze_liveness_ [private]
Definition at line 175 of file bytecode-analysis.h.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::analyze_liveness(), BytecodeAnalysis(), GetInLivenessFor(), and GetOutLivenessFor().
bytecode_count_
int v8::internal::compiler::BytecodeAnalysis::bytecode_count_ = -1 [private]
Definition at line 181 of file bytecode-analysis.h.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), and BytecodeAnalysis().
end_to_header_
ZoneMap<int, int> v8::internal::compiler::BytecodeAnalysis::end_to_header_ [private]
Definition at line 177 of file bytecode-analysis.h.
Referenced by GetLoopEndOffsetForInnermost(), GetLoopOffsetFor(), and v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::PushLoop().
header_to_info_
ZoneMap<int, LoopInfo> v8::internal::compiler::BytecodeAnalysis::header_to_info_ [private]
Definition at line 178 of file bytecode-analysis.h.
Referenced by GetLoopInfoFor(), GetLoopOffsetFor(), IsLoopHeader(), v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::PushLoop(), and TryGetLoopInfoFor().
liveness_map_
std::optional<BytecodeLivenessMap> v8::internal::compiler::BytecodeAnalysis::liveness_map_ [private]
Definition at line 180 of file bytecode-analysis.h.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), BytecodeAnalysis(), and v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::liveness_map().
osr_bailout_id_
BytecodeOffset const v8::internal::compiler::BytecodeAnalysis::osr_bailout_id_ [private]
Definition at line 174 of file bytecode-analysis.h.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
osr_entry_point_
int v8::internal::compiler::BytecodeAnalysis::osr_entry_point_ [private]
Definition at line 179 of file bytecode-analysis.h.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
resume_jump_targets_
ZoneVector<ResumeJumpTarget> v8::internal::compiler::BytecodeAnalysis::resume_jump_targets_ [private]
Definition at line 176 of file bytecode-analysis.h.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/bytecode-analysis.h
/mnt/V8SourceCode/src/compiler/bytecode-analysis.cc