v8::internal::wasm::Result< T > Class Template Reference
#include <wasm-result.h>
Public Member Functions
Result ()=default
Result (Result< T > &&)=default
Result & operator= (Result< T > &&)=default
Result & operator= (const Result< T > &)=delete
Result (const Result &)=delete
template<typename U >
Result (U &&value)
Result (WasmError error)
template<typename U >
operator Result< U > () const &&requires(std
bool ok () const
bool failed () const
const WasmError & error () const &
WasmError && error () &&
const T & value () const &
T && value () &&
Private Attributes
T value_ = T{}
WasmError error_
Detailed Description
template<typename T>
class v8::internal::wasm::Result< T >
Definition at line 68 of file wasm-result.h.
Constructor & Destructor Documentation
Result() [1/5]
template<typename T >
v8::internal::wasm::Result< T >::Result () [default]
Result() [2/5]
template<typename T >
v8::internal::wasm::Result< T >::Result (Result< T > &&) [default]
Result() [3/5]
template<typename T >
v8::internal::wasm::Result< T >::Result (const Result< T > &) [delete]
Result() [4/5]
template<typename T >
template<typename U >
v8::internal::wasm::Result< T >::Result (U && value) [inline], [explicit]
Definition at line 85 of file wasm-result.h.
: value_(std::forward<U>(value)) {}
Result() [5/5]
template<typename T >
v8::internal::wasm::Result< T >::Result (WasmError error) [inline], [explicit]
Definition at line 87 of file wasm-result.h.
: error_(std::move(error)) {}
Member Function Documentation
error() [1/2]
template<typename T >
WasmError&& v8::internal::wasm::Result< T >::error () && [inline]
Definition at line 102 of file wasm-result.h.
{ return std::move(error_); }
References v8::internal::wasm::Result< T >::error_.
error() [2/2]
template<typename T >
const WasmError& v8::internal::wasm::Result< T >::error () const & [inline]
Definition at line 101 of file wasm-result.h.
{ return error_; }
References v8::internal::wasm::Result< T >::error_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting(), and v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints().
failed()
template<typename T >
bool v8::internal::wasm::Result< T >::failed () const [inline]
Definition at line 100 of file wasm-result.h.
{ return error_.has_error(); }
References v8::internal::wasm::Result< T >::error_, and v8::internal::wasm::WasmError::has_error().
Referenced by v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::Result< T >::ok(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::ThrowLazyCompilationError(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::ValidateFunction(), and v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded().
ok()
template<typename T >
bool v8::internal::wasm::Result< T >::ok () const [inline]
Definition at line 99 of file wasm-result.h.
{ return !failed(); }
References v8::internal::wasm::Result< T >::failed().
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::Result< T >::operator Result< U >(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), and v8::internal::wasm::Result< T >::value().
operator Result< U >()
template<typename T >
template<typename U >
v8::internal::wasm::Result< T >::operator Result< U > () const && [inline]
Definition at line 93 of file wasm-result.h.
  {
    return ok() ? Result<U>{std::move(value_)} : Result<U>{error_};
  }
References v8::internal::wasm::Result< T >::error_, v8::internal::wasm::Result< T >::ok(), and v8::internal::wasm::Result< T >::value_.
operator=() [1/2]
template<typename T >
Result& v8::internal::wasm::Result< T >::operator= (const Result< T > &) [delete]
operator=() [2/2]
template<typename T >
Result& v8::internal::wasm::Result< T >::operator= (Result< T > &&) [default]
value() [1/2]
template<typename T >
T&& v8::internal::wasm::Result< T >::value () && [inline]
Definition at line 112 of file wasm-result.h.
                 {
    DCHECK(ok());
    return std::move(value_);
  }
References v8::internal::DCHECK(), v8::internal::wasm::Result< T >::ok(), and v8::internal::wasm::Result< T >::value_.
value() [2/2]
template<typename T >
const T& v8::internal::wasm::Result< T >::value () const & [inline]
Definition at line 108 of file wasm-result.h.
                           {
    DCHECK(ok());
    return value_;
  }
References v8::internal::DCHECK(), v8::internal::wasm::Result< T >::ok(), and v8::internal::wasm::Result< T >::value_.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
Member Data Documentation
error_
template<typename T >
WasmError v8::internal::wasm::Result< T >::error_ [private]
Definition at line 119 of file wasm-result.h.
Referenced by v8::internal::wasm::Result< T >::error(), v8::internal::wasm::Result< T >::failed(), and v8::internal::wasm::Result< T >::operator Result< U >().
value_
template<typename T >
T v8::internal::wasm::Result< T >::value_ = T{} [private]
Definition at line 118 of file wasm-result.h.
Referenced by v8::internal::wasm::Result< T >::operator Result< U >(), and v8::internal::wasm::Result< T >::value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-result.h