v8_inspector::V8ConsoleMessageStorage Class Reference
#include <v8-console-message.h>
Classes
struct PerContextData
Public Member Functions
V8ConsoleMessageStorage (V8InspectorImpl *, int contextGroupId)
~V8ConsoleMessageStorage ()
int contextGroupId ()
const std::deque< std::unique_ptr< V8ConsoleMessage > > & messages () const
void addMessage (std::unique_ptr< V8ConsoleMessage >)
void contextDestroyed (int contextId)
void clear ()
bool shouldReportDeprecationMessage (int contextId, const String16 &method)
int count (int contextId, int consoleContextId, const String16 &id)
bool countReset (int contextId, int consoleContextId, const String16 &id)
bool time (int contextId, int consoleContextId, const String16 &label)
std::optional< double > timeLog (int contextId, int consoleContextId, const String16 &label)
std::optional< double > timeEnd (int contextId, int consoleContextId, const String16 &label)
Private Types
typedef std::pair< int, String16 > LabelKey
Private Attributes
V8InspectorImpl * m_inspector
int m_contextGroupId
int m_estimatedSize = 0
std::deque< std::unique_ptr< V8ConsoleMessage > > m_messages
std::map< int, PerContextData > m_data
Detailed Description
Definition at line 111 of file v8-console-message.h.
Member Typedef Documentation
LabelKey
typedef std::pair<int, String16> v8_inspector::V8ConsoleMessageStorage::LabelKey [private]
Definition at line 144 of file v8-console-message.h.
Constructor & Destructor Documentation
V8ConsoleMessageStorage()
v8_inspector::V8ConsoleMessageStorage::V8ConsoleMessageStorage (V8InspectorImpl * inspector, int contextGroupId)
Definition at line 550 of file v8-console-message.cc.
    : m_inspector(inspector), m_contextGroupId(contextGroupId) {}
 V8ConsoleMessageStorage()
v8_inspector::V8ConsoleMessageStorage::~V8ConsoleMessageStorage ()
Definition at line 554 of file v8-console-message.cc.
{ clear(); }
References clear().
Member Function Documentation
addMessage()
void v8_inspector::V8ConsoleMessageStorage::addMessage (std::unique_ptr< V8ConsoleMessage > message)
Definition at line 576 of file v8-console-message.cc.
                                             {
  int contextGroupId = m_contextGroupId;
  V8InspectorImpl* inspector = m_inspector;
  if (message->type() == ConsoleAPIType::kClear) clear();
  TraceV8ConsoleMessageEvent(message->origin(), message->type());
  inspector->forEachSession(
      contextGroupId, [&message](V8InspectorSessionImpl* session) {
        if (message->origin() == V8MessageOrigin::kConsole)
          session->consoleAgent()->messageAdded(message.get());
        session->runtimeAgent()->messageAdded(message.get());
      });
  if (!inspector->hasConsoleMessageStorage(contextGroupId)) return;
  DCHECK(m_messages.size() <= maxConsoleMessageCount);
  if (m_messages.size() == maxConsoleMessageCount) {
    m_estimatedSize -= m_messages.front()->estimatedSize();
    m_messages.pop_front();
  }
  while (m_estimatedSize + message->estimatedSize() > maxConsoleMessageV8Size &&
         !m_messages.empty()) {
    m_estimatedSize -= m_messages.front()->estimatedSize();
    m_messages.pop_front();
  }
  m_messages.push_back(std::move(message));
  m_estimatedSize += m_messages.back()->estimatedSize();
}
References clear(), v8_inspector::V8InspectorSessionImpl::consoleAgent(), contextGroupId(), DCHECK, v8_inspector::V8InspectorImpl::forEachSession(), v8_inspector::V8InspectorImpl::hasConsoleMessageStorage(), v8_inspector::kClear, v8_inspector::kConsole, m_contextGroupId, m_estimatedSize, m_inspector, m_messages, v8_inspector::anonymous_namespace{v8-console-message.cc}::maxConsoleMessageCount, v8_inspector::anonymous_namespace{v8-console-message.cc}::maxConsoleMessageV8Size, v8_inspector::V8ConsoleAgentImpl::messageAdded(), v8_inspector::V8RuntimeAgentImpl::messageAdded(), v8_inspector::V8InspectorSessionImpl::runtimeAgent(), and v8_inspector::anonymous_namespace{v8-console-message.cc}::TraceV8ConsoleMessageEvent().
Referenced by v8_inspector::V8InspectorImpl::exceptionRevoked(), v8_inspector::V8InspectorImpl::exceptionThrown(), and v8_inspector::anonymous_namespace{custom-preview.cc}::reportError().
clear()
void v8_inspector::V8ConsoleMessageStorage::clear ()
Definition at line 607 of file v8-console-message.cc.
                                    {
  m_messages.clear();
  m_estimatedSize = 0;
  m_inspector->forEachSession(m_contextGroupId,
                              [](V8InspectorSessionImpl* session) {
                                session->releaseObjectGroup("console");
                              });
  for (auto& data : m_data) {
    data.second.m_counters.clear();
    data.second.m_reportedDeprecationMessages.clear();
  }
}
References v8_inspector::V8InspectorImpl::forEachSession(), m_contextGroupId, m_data, m_estimatedSize, m_inspector, m_messages, and v8_inspector::V8InspectorSessionImpl::releaseObjectGroup().
Referenced by addMessage(), v8_inspector::V8RuntimeAgentImpl::discardConsoleEntries(), and ~V8ConsoleMessageStorage().
contextDestroyed()
void v8_inspector::V8ConsoleMessageStorage::contextDestroyed (int contextId)
Definition at line 673 of file v8-console-message.cc.
                                                            {
  m_estimatedSize = 0;
  for (size_t i = 0; i < m_messages.size(); ++i) {
    m_messages[i]->contextDestroyed(contextId);
    m_estimatedSize += m_messages[i]->estimatedSize();
  }
  {
    auto it = m_data.find(contextId);
    if (it != m_data.end()) m_data.erase(contextId);
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, m_data, m_estimatedSize, and m_messages.
contextGroupId()
int v8_inspector::V8ConsoleMessageStorage::contextGroupId () [inline]
Definition at line 116 of file v8-console-message.h.
{ return m_contextGroupId; }
References m_contextGroupId.
Referenced by addMessage().
count()
int v8_inspector::V8ConsoleMessageStorage::count (int contextId, int consoleContextId, const String16 & id)
Definition at line 630 of file v8-console-message.cc.
                                                          {
  return ++m_data[contextId].m_counters[LabelKey{consoleContextId, label}];
}
References m_data.
countReset()
bool v8_inspector::V8ConsoleMessageStorage::countReset (int contextId, int consoleContextId, const String16 & id)
Definition at line 635 of file v8-console-message.cc.
                                                                {
  std::map<LabelKey, int>& counters = m_data[contextId].m_counters;
  auto it = counters.find(LabelKey{consoleContextId, label});
  if (it == counters.end()) return false;
  counters.erase(it);
  return true;
}
References m_data.
messages()
const std::deque<std::unique_ptr<V8ConsoleMessage> >& v8_inspector::V8ConsoleMessageStorage::messages () const [inline]
Definition at line 117 of file v8-console-message.h.
                                                                    {
    return m_messages;
  }
References m_messages.
Referenced by v8_inspector::V8RuntimeAgentImpl::enable(), and v8_inspector::V8ConsoleAgentImpl::reportAllMessages().
shouldReportDeprecationMessage()
bool v8_inspector::V8ConsoleMessageStorage::shouldReportDeprecationMessage (int contextId, const String16 & method)
Definition at line 620 of file v8-console-message.cc.
                                           {
  std::set<String16>& reportedDeprecationMessages =
      m_data[contextId].m_reportedDeprecationMessages;
  auto it = reportedDeprecationMessages.find(method);
  if (it != reportedDeprecationMessages.end()) return false;
  reportedDeprecationMessages.insert(it, method);
  return true;
}
References m_data.
time()
bool v8_inspector::V8ConsoleMessageStorage::time (int contextId, int consoleContextId, const String16 & label)
Definition at line 644 of file v8-console-message.cc.
                                                          {
  return m_data[contextId]
      .m_timers
      .try_emplace(LabelKey{consoleContextId, label},
                   m_inspector->client()->currentTimeMS())
      .second;
}
References v8_inspector::V8InspectorImpl::client(), m_data, and m_inspector.
timeEnd()
std::optional< double > v8_inspector::V8ConsoleMessageStorage::timeEnd (int contextId, int consoleContextId, const String16 & label)
Definition at line 662 of file v8-console-message.cc.
                                                                              {
  auto& timers = m_data[contextId].m_timers;
  auto it = timers.find(std::make_pair(consoleContextId, label));
  if (it == timers.end()) return std::nullopt;
  double result = m_inspector->client()->currentTimeMS() - it->second;
  timers.erase(it);
  return result;
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::currentTimeMS(), m_data, m_inspector, and v8::base::internal::result.
timeLog()
std::optional< double > v8_inspector::V8ConsoleMessageStorage::timeLog (int contextId, int consoleContextId, const String16 & label)
Definition at line 653 of file v8-console-message.cc.
                                                                              {
  auto& timers = m_data[contextId].m_timers;
  auto it = timers.find(std::make_pair(consoleContextId, label));
  if (it == timers.end()) return std::nullopt;
  return m_inspector->client()->currentTimeMS() - it->second;
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::currentTimeMS(), m_data, and m_inspector.
Member Data Documentation
m_contextGroupId
int v8_inspector::V8ConsoleMessageStorage::m_contextGroupId [private]
Definition at line 138 of file v8-console-message.h.
Referenced by addMessage(), clear(), and contextGroupId().
m_data
std::map<int, PerContextData> v8_inspector::V8ConsoleMessageStorage::m_data [private]
Definition at line 153 of file v8-console-message.h.
Referenced by clear(), contextDestroyed(), count(), countReset(), shouldReportDeprecationMessage(), time(), timeEnd(), and timeLog().
m_estimatedSize
int v8_inspector::V8ConsoleMessageStorage::m_estimatedSize = 0 [private]
Definition at line 139 of file v8-console-message.h.
Referenced by addMessage(), clear(), and contextDestroyed().
m_inspector
V8InspectorImpl* v8_inspector::V8ConsoleMessageStorage::m_inspector [private]
Definition at line 137 of file v8-console-message.h.
Referenced by addMessage(), clear(), time(), timeEnd(), and timeLog().
m_messages
std::deque<std::unique_ptr<V8ConsoleMessage> > v8_inspector::V8ConsoleMessageStorage::m_messages [private]
Definition at line 140 of file v8-console-message.h.
Referenced by addMessage(), clear(), contextDestroyed(), and messages().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-console-message.h
/mnt/V8SourceCode/src/inspector/v8-console-message.cc