v8::internal::JSDurationFormat Class Reference
#include <js-duration-format.h>
Public Types
enum class Display { kAuto
, kAlways
, kMax = kAlways
 }
enum class Style {
kLong
, kShort
, kNarrow
, kDigital
,
kMax = kDigital
 }
enum class Separator {
kColon
, kFullStop
, kFullwidthColon
, kArabicDecimalSeparator
,
kMax = kArabicDecimalSeparator
 }
enum class FieldStyle {
kLong
, kShort
, kNarrow
, kNumeric
,
k2Digit
, kFractional
, kUndefined
, kStyle3Max = kNarrow
,
kStyle4Max = kFractional
, kStyle5Max = k2Digit
 }
Public Member Functions
void set_fractional_digits (int32_t digits)
int32_t fractional_digits () const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSDurationFormat > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT DirectHandle< JSObject > ResolvedOptions (Isolate *isolate, DirectHandle< JSDurationFormat > format_holder)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > Format (Isolate *isolate, DirectHandle< JSDurationFormat > df, Handle< Object > duration)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > FormatToParts (Isolate *isolate, DirectHandle< JSDurationFormat > df, Handle< Object > duration)
static V8_EXPORT_PRIVATE const std::set< std::string > & GetAvailableLocales ()
Static Public Attributes
static const uint32_t kUndefinedFractionalDigits = 15
Detailed Description
Definition at line 32 of file js-duration-format.h.
Member Enumeration Documentation
Display
enum v8::internal::JSDurationFormat::Display [strong]
Enumerator
kAuto
kAlways
kMax
Definition at line 54 of file js-duration-format.h.
                     {
    kAuto,
    kAlways,
    kMax = kAlways
  };
FieldStyle
enum v8::internal::JSDurationFormat::FieldStyle [strong]
Enumerator
kLong
kShort
kNarrow
kNumeric
k2Digit
kFractional
kUndefined
kStyle3Max
kStyle4Max
kStyle5Max
Definition at line 84 of file js-duration-format.h.
                        {
    kLong,
    kShort,
    kNarrow,
    kNumeric,
    k2Digit,
    kFractional,
    kUndefined,
    kStyle3Max = kNarrow,
    kStyle4Max = kFractional,
    kStyle5Max = k2Digit,
  };
Separator
enum v8::internal::JSDurationFormat::Separator [strong]
Enumerator
kColon
kFullStop
kFullwidthColon
kArabicDecimalSeparator
kMax
Definition at line 73 of file js-duration-format.h.
                       {
    kColon, // U+003A
    kFullStop, // U+002E
    kFullwidthColon, // U+FF1A
    kArabicDecimalSeparator, // U+066B
    kMax = kArabicDecimalSeparator
  };
Style
enum v8::internal::JSDurationFormat::Style [strong]
Enumerator
kLong
kShort
kNarrow
kDigital
kMax
Definition at line 61 of file js-duration-format.h.
                   {
    kLong,
    kShort,
    kNarrow,
    kDigital,
    kMax = kDigital
  };
Member Function Documentation
Format()
MaybeDirectHandle< String > v8::internal::JSDurationFormat::Format (Isolate * isolate, DirectHandle< JSDurationFormat > df, Handle< Object > duration) [static]
Definition at line 1127 of file js-duration-format.cc.
                             {
  const char* method_name = "Intl.DurationFormat.prototype.format";
  return FormatCommon<String, false, FormattedToString>(isolate, df, duration,
                                                        method_name);
}
References v8::internal::duration.
Referenced by v8::internal::BUILTIN().
FormatToParts()
MaybeDirectHandle< JSArray > v8::internal::JSDurationFormat::FormatToParts (Isolate * isolate, DirectHandle< JSDurationFormat > df, Handle< Object > duration) [static]
Definition at line 1135 of file js-duration-format.cc.
                             {
  const char* method_name = "Intl.DurationFormat.prototype.formatToParts";
  return FormatCommon<JSArray, true, FormattedListToJSArray>(
      isolate, df, duration, method_name);
}
References v8::internal::duration.
Referenced by v8::internal::BUILTIN().
fractional_digits()
int32_t v8::internal::JSDurationFormat::fractional_digits () const [inline]
Definition at line 93 of file js-duration-format-inl.h.
                                                         {
  int32_t v = FractionalDigitsBits::decode(display_flags());
  DCHECK((0 <= v && v <= 9) || v == kUndefinedFractionalDigits);
  return v;
}
References v8::internal::DCHECK(), and kUndefinedFractionalDigits.
Referenced by New(), and ResolvedOptions().
GetAvailableLocales()
const std::set< std::string > & v8::internal::JSDurationFormat::GetAvailableLocales () [static]
Definition at line 1143 of file js-duration-format.cc.
                                                               {
  return JSNumberFormat::GetAvailableLocales();
}
References v8::internal::JSNumberFormat::GetAvailableLocales().
Referenced by v8::internal::BUILTIN(), and New().
New()
MaybeDirectHandle< JSDurationFormat > v8::internal::JSDurationFormat::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 248 of file js-duration-format.cc.
                                        {
  Factory* factory = isolate->factory();
  const char* method_name = "Intl.DurationFormat";
  // 3. Let requestedLocales be ? CanonicalizeLocaleList(locales).
  std::vector<std::string> requested_locales;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, requested_locales,
      Intl::CanonicalizeLocaleList(isolate, locales),
      DirectHandle<JSDurationFormat>());
  // 4. Let options be ? GetOptionsObject(options).
  DirectHandle<JSReceiver> options;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, GetOptionsObject(isolate, input_options, method_name));
  // 5. Let matcher be ? GetOption(options, "localeMatcher", "string", «
  // "lookup", "best fit" », "best fit").
  Intl::MatcherOption matcher;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, matcher, Intl::GetLocaleMatcher(isolate, options, method_name),
      DirectHandle<JSDurationFormat>());
  // 6. Let numberingSystem be ? GetOption(options, "numberingSystem", "string",
  // undefined, undefined).
  //
  // 7. If numberingSystem is not undefined, then
  //
  // a. If numberingSystem does not match the Unicode Locale Identifier type
  // nonterminal, throw a RangeError exception.
  // Note: The matching test and throw in Step 7-a is throw inside
  // Intl::GetNumberingSystem.
  std::string numbering_system_str;
  bool get;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, get,
      Intl::GetNumberingSystem(isolate, options, method_name,
                               numbering_system_str),
      DirectHandle<JSDurationFormat>());
  // 8. Let opt be the Record { [[localeMatcher]]: matcher, [[nu]]:
  // numberingSystem }.
  // 9. Let r be ResolveLocale(%DurationFormat%.[[AvailableLocales]],
  // requestedLocales, opt, %DurationFormat%.[[RelevantExtensionKeys]],
  // %DurationFormat%.[[LocaleData]]).
  Intl::ResolvedLocale r;
  if (!Intl::ResolveLocale(isolate, JSDurationFormat::GetAvailableLocales(),
                           requested_locales, matcher, {"nu"})
           .To(&r)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  // 10. Let locale be r.[[locale]].
  icu::Locale r_locale = r.icu_locale;
  UErrorCode status = U_ZERO_ERROR;
  // 11. Set durationFormat.[[Locale]] to locale.
  // 12. Set durationFormat.[[NumberingSystem]] to r.[[nu]].
  if (get) {
    auto nu_extension_it = r.extensions.find("nu");
    if (nu_extension_it != r.extensions.end() &&
        nu_extension_it->second != numbering_system_str) {
      r_locale.setUnicodeKeywordValue("nu", nullptr, status);
      DCHECK(U_SUCCESS(status));
    }
  }
  icu::Locale icu_locale = r_locale;
  if (get && Intl::IsValidNumberingSystem(numbering_system_str)) {
    r_locale.setUnicodeKeywordValue("nu", numbering_system_str, status);
    DCHECK(U_SUCCESS(status));
  }
  std::string numbering_system = Intl::GetNumberingSystem(r_locale);
  Separator separator = GetSeparator(r_locale);
  // 13. Let style be ? GetOption(options, "style", "string", « "long", "short",
  // "narrow", "digital" », "long").
  Style style;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, style,
      GetStringOption<Style>(isolate, options, "style", method_name,
                             std::to_array<const std::string_view>(
                                 {"long", "short", "narrow", "digital"}),
                             std::array{Style::kLong, Style::kShort,
                                        Style::kNarrow, Style::kDigital},
                             Style::kShort),
      DirectHandle<JSDurationFormat>());
  // 14. Set durationFormat.[[Style]] to style.
  // 15. Set durationFormat.[[DataLocale]] to r.[[dataLocale]].
  DirectHandle<Managed<icu::Locale>> managed_locale =
      Managed<icu::Locale>::From(
          isolate, 0, std::shared_ptr<icu::Locale>{icu_locale.clone()});
  // 16. Let prevStyle be the empty String.
  // 17. For each row of Table 1, except the header row, in table order, do
  // a. Let styleSlot be the Style Slot value of the current row.
  // b. Let displaySlot be the Display Slot value of the current row.
  // c. Let unit be the Unit value.
  // d. Let valueList be the Values value.
  // e. Let digitalBase be the Digital Default value.
  // f. Let unitOptions be ? GetDurationUnitOptions(unit, options, style,
  // valueList, digitalBase, prevStyle).
  // of durationFormat to unitOptions.[[Style]].
  // h. Set the value of the
  // displaySlot slot of durationFormat to unitOptions.[[Display]].
  // i. If unit is one of "hours", "minutes", "seconds", "milliseconds",
  // or "microseconds", then
  // i. Set prevStyle to unitOptions.[[Style]].
  // g. Set the value of the styleSlot slot
  DurationUnitOptions years_option;
  DurationUnitOptions months_option;
  DurationUnitOptions weeks_option;
  DurationUnitOptions days_option;
  DurationUnitOptions hours_option;
  DurationUnitOptions minutes_option;
  DurationUnitOptions seconds_option;
  DurationUnitOptions milliseconds_option;
  DurationUnitOptions microseconds_option;
  DurationUnitOptions nanoseconds_option;
#define CALL_GET_DURATION_UNIT_OPTIONS(unit, property, strings, enums, \
                                       digital_base, prev_style) \
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(\
      isolate, property##_option, \
      GetDurationUnitOptions(\
          isolate, Unit::unit, #property, #property "Display", options, style, \
          strings, enums, JSDurationFormat::FieldStyle::digital_base, \
          prev_style), \
      DirectHandle<JSDurationFormat>());
  // #table-durationformat
  // Table 3: Internal slots and property names of DurationFormat instances
  // relevant to Intl.DurationFormat constructor
  // [[YearsStyle]] [[YearsDisplay]] "years" « "long", "short",
  // "narrow" » "short"
  CALL_GET_DURATION_UNIT_OPTIONS(kYears, years, kLongShortNarrowStrings,
                                 kLongShortNarrowEnums, kShort,
                                 FieldStyle::kUndefined)
  // [[MonthsStyle]] [[MonthsDisplay]] "months" « "long",
  // "short", "narrow" » "short"
  CALL_GET_DURATION_UNIT_OPTIONS(kMonths, months, kLongShortNarrowStrings,
                                 kLongShortNarrowEnums, kShort,
                                 years_option.style)
  // [[WeeksStyle]] [[WeeksDisplay]] "weeks" « "long", "short",
  // "narrow" » "short"
  CALL_GET_DURATION_UNIT_OPTIONS(kWeeks, weeks, kLongShortNarrowStrings,
                                 kLongShortNarrowEnums, kShort,
                                 months_option.style)
  // [[DaysStyle]] [[DaysDisplay]] "days" « "long", "short", "narrow" »
  // "short"
  CALL_GET_DURATION_UNIT_OPTIONS(kDays, days, kLongShortNarrowStrings,
                                 kLongShortNarrowEnums, kShort,
                                 weeks_option.style)
  // [[HoursStyle]] [[HoursDisplay]] "hours" « "long", "short",
  // "narrow", "numeric", "2-digit" » "numeric"
  CALL_GET_DURATION_UNIT_OPTIONS(
      kHours, hours, kLongShortNarrowNumeric2DigitStrings,
      kLongShortNarrowNumeric2DigitEnums, kNumeric, days_option.style)
  // [[MinutesStyle]] [[MinutesDisplay]] "minutes" « "long",
  // "short", "narrow", "numeric", "2-digit" » "numeric"
  CALL_GET_DURATION_UNIT_OPTIONS(
      kMinutes, minutes, kLongShortNarrowNumeric2DigitStrings,
      kLongShortNarrowNumeric2DigitEnums, kNumeric, hours_option.style)
  // [[SecondsStyle]] [[SecondsDisplay]] "seconds" « "long",
  // "short", "narrow", "numeric", "2-digit" »
  CALL_GET_DURATION_UNIT_OPTIONS(
      kSeconds, seconds, kLongShortNarrowNumeric2DigitStrings,
      kLongShortNarrowNumeric2DigitEnums, kNumeric, minutes_option.style)
  // [[MillisecondsStyle]] [[MillisecondsDisplay]] "milliseconds" «
  // "long", "short", "narrow", "numeric" » "numeric"
  CALL_GET_DURATION_UNIT_OPTIONS(
      kMilliseconds, milliseconds, kLongShortNarrowNumericStrings,
      kLongShortNarrowNumericEnums, kNumeric, seconds_option.style)
  // [[MicrosecondsStyle]] [[MicrosecondsDisplay]] "microseconds" «
  // "long", "short", "narrow", "numeric" » "numeric"
  CALL_GET_DURATION_UNIT_OPTIONS(
      kMicroseconds, microseconds, kLongShortNarrowNumericStrings,
      kLongShortNarrowNumericEnums, kNumeric, milliseconds_option.style)
  // [[NanosecondsStyle]] [[NanosecondsDisplay]] "nanoseconds" «
  // "long", "short", "narrow", "numeric" » "numeric"
  CALL_GET_DURATION_UNIT_OPTIONS(
      kNanoseconds, nanoseconds, kLongShortNarrowNumericStrings,
      kLongShortNarrowNumericEnums, kNumeric, microseconds_option.style)
#undef CALL_GET_DURATION_UNIT_OPTIONS
  // 18. Set durationFormat.[[FractionalDigits]] to ? GetNumberOption(options,
  // "fractionalDigits", 0, 9, undefined).
  int fractional_digits;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, fractional_digits,
      GetNumberOption(isolate, options, factory->fractionalDigits_string(), 0,
                      9, kUndefinedFractionalDigits),
      DirectHandle<JSDurationFormat>());
  icu::number::LocalizedNumberFormatter fmt =
      icu::number::UnlocalizedNumberFormatter()
          .roundingMode(UNUM_ROUND_HALFUP)
          .locale(icu_locale);
  if (!numbering_system.empty() && numbering_system != "latn") {
    fmt = fmt.adoptSymbols(icu::NumberingSystem::createInstanceByName(
        numbering_system.c_str(), status));
    DCHECK(U_SUCCESS(status));
  }
  DirectHandle<Managed<icu::number::LocalizedNumberFormatter>>
      managed_number_formatter =
          Managed<icu::number::LocalizedNumberFormatter>::From(
              isolate, 0,
              std::make_shared<icu::number::LocalizedNumberFormatter>(fmt));
  // 19. Return durationFormat.
  DirectHandle<JSDurationFormat> duration_format =
      Cast<JSDurationFormat>(factory->NewFastOrSlowJSObjectFromMap(map));
  duration_format->set_style_flags(0);
  duration_format->set_display_flags(0);
  duration_format->set_style(style);
  duration_format->set_years_style(years_option.style);
  duration_format->set_months_style(months_option.style);
  duration_format->set_weeks_style(weeks_option.style);
  duration_format->set_days_style(days_option.style);
  duration_format->set_hours_style(hours_option.style);
  duration_format->set_minutes_style(minutes_option.style);
  duration_format->set_seconds_style(seconds_option.style);
  duration_format->set_milliseconds_style(milliseconds_option.style);
  duration_format->set_microseconds_style(microseconds_option.style);
  duration_format->set_nanoseconds_style(nanoseconds_option.style);
  duration_format->set_separator(separator);
  duration_format->set_years_display(years_option.display);
  duration_format->set_months_display(months_option.display);
  duration_format->set_weeks_display(weeks_option.display);
  duration_format->set_days_display(days_option.display);
  duration_format->set_hours_display(hours_option.display);
  duration_format->set_minutes_display(minutes_option.display);
  duration_format->set_seconds_display(seconds_option.display);
  duration_format->set_milliseconds_display(milliseconds_option.display);
  duration_format->set_microseconds_display(microseconds_option.display);
  duration_format->set_nanoseconds_display(nanoseconds_option.display);
  duration_format->set_fractional_digits(fractional_digits);
  duration_format->set_icu_locale(*managed_locale);
  duration_format->set_icu_number_formatter(*managed_number_formatter);
  return duration_format;
}
References ASSIGN_RETURN_ON_EXCEPTION, CALL_GET_DURATION_UNIT_OPTIONS, v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::DCHECK(), v8::internal::Intl::ResolvedLocale::extensions, v8::internal::Isolate::factory(), fractional_digits(), v8::internal::Managed< CppType >::From(), GetAvailableLocales(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::Intl::GetNumberingSystem(), v8::internal::GetNumberOption(), v8::internal::GetOptionsObject(), v8::internal::anonymous_namespace{js-duration-format.cc}::GetSeparator(), v8::internal::Intl::ResolvedLocale::icu_locale, v8::internal::Intl::IsValidNumberingSystem(), kDigital, kLong, v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowEnums, v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowNumeric2DigitEnums, v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowNumeric2DigitStrings, v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowNumericEnums, v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowNumericStrings, v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowStrings, kNarrow, kShort, kUndefined, kUndefinedFractionalDigits, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::microseconds, v8::internal::nanoseconds, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::Intl::ResolveLocale(), v8::internal::seconds, v8::internal::separator, v8::internal::status, v8::internal::string, and THROW_NEW_ERROR.
ResolvedOptions()
DirectHandle< JSObject > v8::internal::JSDurationFormat::ResolvedOptions (Isolate * isolate, DirectHandle< JSDurationFormat > format_holder) [static]
Definition at line 559 of file js-duration-format.cc.
                                                             {
  Factory* factory = isolate->factory();
  DirectHandle<JSObject> options =
      factory->NewJSObject(isolate->object_function());
  DirectHandle<String> locale = factory->NewStringFromAsciiChecked(
      Intl::ToLanguageTag(*format->icu_locale()->raw()).FromJust().c_str());
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString skeleton =
      format->icu_number_formatter()->raw()->toSkeleton(status);
  DCHECK(U_SUCCESS(status));
  DirectHandle<String> numbering_system;
  CHECK(Intl::ToString(isolate,
                       JSNumberFormat::NumberingSystemFromSkeleton(skeleton))
            .ToHandle(&numbering_system));
  bool created;
#define OUTPUT_PROPERTY(s, f) \
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(\
      isolate, created, \
      JSReceiver::CreateDataProperty(isolate, options, factory->s(), f, \
                                     Just(kDontThrow)), \
      DirectHandle<JSObject>()); \
  CHECK(created);
#define OUTPUT_STYLE_PROPERTY(p) \
  OUTPUT_PROPERTY(p##_string, StyleToString(isolate, format->p##_style()))
#define OUTPUT_DISPLAY_PROPERTY(p) \
  OUTPUT_PROPERTY(p##Display_string, \
                  DisplayToString(isolate, format->p##_display()))
#define OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(p) \
  OUTPUT_STYLE_PROPERTY(p); \
  OUTPUT_DISPLAY_PROPERTY(p);
  // #table-durationformat-resolvedoptions-properties
  // Table 4: Resolved Options of DurationFormat Instances
  // [[Locale]] "locale"
  OUTPUT_PROPERTY(locale_string, locale);
  // [[NumberingSystem]] "numberingSystem"
  OUTPUT_PROPERTY(numberingSystem_string, numbering_system);
  // [[Style]] "style"
  OUTPUT_PROPERTY(style_string, StyleToString(isolate, format->style()));
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(years);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(months);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(weeks);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(days);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(hours);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(minutes);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(seconds);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(milliseconds);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(microseconds);
  OUTPUT_STYLE_AND_DISPLAY_PROPERTIES(nanoseconds);
  // [[FractionalDigits]] "fractionalDigits"
  // c. If p is "fractionalDigits", then
  int32_t fractional_digits = format->fractional_digits();
  // i. If v is not undefined, set v to 𝔽(v).
  if (kUndefinedFractionalDigits != fractional_digits) {
    DirectHandle<Smi> fractional_digits_obj =
        direct_handle(Smi::FromInt(fractional_digits), isolate);
    // f. If v is not undefined, then
    // i. Perform ! CreateDataPropertyOrThrow(options, p, v).
    OUTPUT_PROPERTY(fractionalDigits_string, fractional_digits_obj);
  }
#undef OUTPUT_PROPERTY
#undef OUTPUT_STYLE_PROPERTY
#undef OUTPUT_DISPLAY_PROPERTY
#undef OUTPUT_STYLE_AND_DISPLAY_PROPERTIES
  return options;
}
References CHECK, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::format, fractional_digits(), v8::internal::Smi::FromInt(), kUndefinedFractionalDigits, v8::internal::microseconds, v8::internal::nanoseconds, v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::JSNumberFormat::NumberingSystemFromSkeleton(), OUTPUT_PROPERTY, OUTPUT_STYLE_AND_DISPLAY_PROPERTIES, v8::internal::seconds, v8::internal::status, v8::internal::anonymous_namespace{js-duration-format.cc}::StyleToString(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Intl::ToLanguageTag(), and v8::internal::Intl::ToString().
Referenced by v8::internal::BUILTIN().
set_fractional_digits()
kMax void v8::internal::JSDurationFormat::set_fractional_digits (int32_t digits) [inline]
Definition at line 87 of file js-duration-format-inl.h.
                                                                  {
  DCHECK((0 <= digits && digits <= 9) || digits == kUndefinedFractionalDigits);
  int hints = display_flags();
  hints = FractionalDigitsBits::update(hints, digits);
  set_display_flags(hints);
}
References v8::internal::DCHECK(), and kUndefinedFractionalDigits.
Member Data Documentation
kUndefinedFractionalDigits
const uint32_t v8::internal::JSDurationFormat::kUndefinedFractionalDigits = 15 [static]
Definition at line 139 of file js-duration-format.h.
Referenced by v8::internal::anonymous_namespace{js-duration-format.cc}::DurationRecordToListOfFormattedNumber(), fractional_digits(), New(), ResolvedOptions(), and set_fractional_digits().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-duration-format.h
/mnt/V8SourceCode/src/objects/js-duration-format-inl.h
/mnt/V8SourceCode/src/objects/js-duration-format.cc