v8::internal::BackingStore Class Reference
#include <backing-store.h>
Classes
union TypeSpecificData
Public Types
enum ResizeOrGrowResult { kSuccess
, kFailure
, kRace
 }
Public Member Functions
~BackingStore ()
void * buffer_start () const
size_t byte_length (std::memory_order memory_order=std::memory_order_relaxed) const
size_t max_byte_length () const
size_t byte_capacity () const
bool is_shared () const
bool is_resizable_by_js () const
bool is_wasm_memory () const
bool is_wasm_memory64 () const
bool has_guard_regions () const
bool IsEmpty () const
ResizeOrGrowResult ResizeInPlace (Isolate *isolate, size_t new_byte_length)
ResizeOrGrowResult GrowInPlace (Isolate *isolate, size_t new_byte_length)
size_t PerIsolateAccountingLength ()
uint32_t id () const
Static Public Member Functions
static std::unique_ptr< BackingStore > Allocate (Isolate *isolate, size_t byte_length, SharedFlag shared, InitializedFlag initialized)
static std::unique_ptr< BackingStore > TryAllocateAndPartiallyCommitMemory (Isolate *isolate, size_t byte_length, size_t max_byte_length, size_t page_size, size_t initial_pages, size_t maximum_pages, WasmMemoryFlag wasm_memory, SharedFlag shared, bool has_guard_regions=false)
static std::unique_ptr< BackingStore > WrapAllocation (void *allocation_base, size_t allocation_length, v8::BackingStore::DeleterCallback deleter, void *deleter_data, SharedFlag shared)
static std::unique_ptr< BackingStore > EmptyBackingStore (SharedFlag shared)
Private Types
enum Flag {
kIsShared
, kIsResizableByJs
, kIsWasmMemory
, kIsWasmMemory64
,
kHoldsSharedPtrToAllocater
, kHasGuardRegions
, kGloballyRegistered
, kCustomDeleter
,
kEmptyDeleter
 }
Private Member Functions
BackingStore (PageAllocator *page_allocator, void *buffer_start, size_t byte_length, size_t max_byte_length, size_t byte_capacity, SharedFlag shared, ResizableFlag resizable, bool is_wasm_memory, bool is_wasm_memory64, bool has_guard_regions, bool custom_deleter, bool empty_deleter)
BackingStore (const BackingStore &)=delete
BackingStore & operator= (const BackingStore &)=delete
void SetAllocatorFromIsolate (Isolate *isolate)
v8::ArrayBuffer::Allocator * get_v8_api_array_buffer_allocator ()
SharedWasmMemoryData * get_shared_wasm_memory_data () const
bool has_flag (Flag flag) const
void set_flag (Flag flag)
void clear_flag (Flag flag)
bool holds_shared_ptr_to_allocator () const
bool custom_deleter () const
bool globally_registered () const
Private Attributes
void * buffer_start_ = nullptr
std::atomic< size_t > byte_length_
size_t max_byte_length_
size_t byte_capacity_
const uint32_t id_
v8::PageAllocator * page_allocator_ = nullptr
union v8::internal::BackingStore::TypeSpecificData type_specific_data_
std::atomic< base::EnumSet< Flag, uint16_t > > flags_
Friends
class GlobalBackingStoreRegistry
Detailed Description
Definition at line 45 of file backing-store.h.
Member Enumeration Documentation
Flag
enum v8::internal::BackingStore::Flag [private]
Enumerator
kIsShared
kIsResizableByJs
kIsWasmMemory
kIsWasmMemory64
kHoldsSharedPtrToAllocater
kHasGuardRegions
kGloballyRegistered
kCustomDeleter
kEmptyDeleter
Definition at line 189 of file backing-store.h.
            {
    kIsShared,
    kIsResizableByJs,
    kIsWasmMemory,
    kIsWasmMemory64,
    kHoldsSharedPtrToAllocater,
    kHasGuardRegions,
    kGloballyRegistered,
    kCustomDeleter,
    kEmptyDeleter
  };
ResizeOrGrowResult
enum v8::internal::BackingStore::ResizeOrGrowResult
Enumerator
kSuccess
kFailure
kRace
Definition at line 108 of file backing-store.h.
{ kSuccess, kFailure, kRace };
Constructor & Destructor Documentation
 BackingStore()
v8::internal::BackingStore::~BackingStore ()
Definition at line 136 of file backing-store.cc.
                            {
  GlobalBackingStoreRegistry::Unregister(this);
  struct ClearSharedAllocator {
    BackingStore* const bs;
    ~ClearSharedAllocator() {
      if (!bs->holds_shared_ptr_to_allocator()) return;
      bs->type_specific_data_.v8_api_array_buffer_allocator_shared
          .std::shared_ptr<v8::ArrayBuffer::Allocator>::~shared_ptr();
    }
  } clear_shared_allocator{this};
  if (buffer_start_ == nullptr) return;
  auto FreeResizableMemory = [this] {
    DCHECK(!custom_deleter());
    DCHECK(is_resizable_by_js() || is_wasm_memory());
    auto region = GetReservedRegion(has_guard_regions(), is_wasm_memory64(),
                                    buffer_start_, byte_capacity_);
    if (!region.is_empty()) {
      FreePages(page_allocator_, reinterpret_cast<void*>(region.begin()),
                region.size());
    }
  };
#if V8_ENABLE_WEBASSEMBLY
  if (is_wasm_memory()) {
    size_t reservation_size = GetReservationSize(
        has_guard_regions(), byte_capacity_, is_wasm_memory64());
    TRACE_BS(
        "BSw:free bs=%p mem=%p (length=%zu, capacity=%zu, reservation=%zu)\n",
        this, buffer_start_, byte_length(), byte_capacity_, reservation_size);
    if (is_shared()) {
      // Deallocate the list of attached memory objects.
      SharedWasmMemoryData* shared_data = get_shared_wasm_memory_data();
      delete shared_data;
    }
    // Wasm memories are always allocated through the page allocator.
    FreeResizableMemory();
    return;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (is_resizable_by_js()) {
    FreeResizableMemory();
    return;
  }
  if (custom_deleter()) {
    TRACE_BS("BS:custom deleter bs=%p mem=%p (length=%zu, capacity=%zu)\n",
             this, buffer_start_, byte_length(), byte_capacity_);
    type_specific_data_.deleter.callback(buffer_start_, byte_length_,
                                         type_specific_data_.deleter.data);
    return;
  }
  // JSArrayBuffer backing store. Deallocate through the embedder's allocator.
  auto allocator = get_v8_api_array_buffer_allocator();
  TRACE_BS("BS:free bs=%p mem=%p (length=%zu, capacity=%zu)\n", this,
           buffer_start_, byte_length(), byte_capacity_);
  allocator->Free(buffer_start_, byte_length_);
}
References buffer_start_, byte_capacity_, byte_length(), byte_length_, v8::internal::BackingStore::TypeSpecificData::DeleterInfo::callback, custom_deleter(), v8::internal::BackingStore::TypeSpecificData::DeleterInfo::data, v8::internal::DCHECK(), v8::internal::BackingStore::TypeSpecificData::deleter, v8::internal::FreePages(), get_shared_wasm_memory_data(), get_v8_api_array_buffer_allocator(), v8::internal::anonymous_namespace{backing-store.cc}::GetReservationSize(), v8::internal::anonymous_namespace{backing-store.cc}::GetReservedRegion(), has_guard_regions(), holds_shared_ptr_to_allocator(), is_resizable_by_js(), is_shared(), is_wasm_memory(), is_wasm_memory64(), page_allocator_, TRACE_BS, type_specific_data_, v8::internal::GlobalBackingStoreRegistry::Unregister(), and v8::internal::BackingStore::TypeSpecificData::v8_api_array_buffer_allocator_shared.
Referenced by v8::BackingStore::~BackingStore().
BackingStore() [1/2]
v8::internal::BackingStore::BackingStore (PageAllocator * page_allocator, void * buffer_start, size_t byte_length, size_t max_byte_length, size_t byte_capacity, SharedFlag shared, ResizableFlag resizable, bool is_wasm_memory, bool is_wasm_memory64, bool has_guard_regions, bool custom_deleter, bool empty_deleter) [private]
Definition at line 97 of file backing-store.cc.
    : buffer_start_(buffer_start),
      byte_length_(byte_length),
      max_byte_length_(max_byte_length),
      byte_capacity_(byte_capacity),
      id_(next_backing_store_id_.fetch_add(1)),
      page_allocator_(page_allocator) {
  // TODO(v8:11111): RAB / GSAB - Wasm integration.
  DCHECK_IMPLIES(is_wasm_memory64, is_wasm_memory);
  DCHECK_IMPLIES(has_guard_regions, is_wasm_memory);
  DCHECK_IMPLIES(is_wasm_memory, resizable == ResizableFlag::kNotResizable);
  DCHECK_IMPLIES(resizable == ResizableFlag::kResizable, !custom_deleter);
  DCHECK_IMPLIES(!is_wasm_memory && resizable == ResizableFlag::kNotResizable,
                 byte_length_ == max_byte_length_);
  DCHECK_GE(max_byte_length, byte_length);
  DCHECK_GE(byte_capacity, max_byte_length);
  // TODO(1445003): Demote to a DCHECK once we found the issue.
  // Wasm memory should never be empty (== zero capacity). Otherwise
  // {JSArrayBuffer::Attach} would replace it by the {EmptyBackingStore} and we
  // loose information.
  // This is particularly important for shared Wasm memory.
  CHECK_IMPLIES(is_wasm_memory, byte_capacity != 0);
  base::EnumSet<Flag, uint16_t> flags;
  if (shared == SharedFlag::kShared) flags.Add(kIsShared);
  if (resizable == ResizableFlag::kResizable) flags.Add(kIsResizableByJs);
  if (is_wasm_memory) flags.Add(kIsWasmMemory);
  if (is_wasm_memory64) flags.Add(kIsWasmMemory64);
  if (has_guard_regions) flags.Add(kHasGuardRegions);
  if (custom_deleter) flags.Add(kCustomDeleter);
  if (empty_deleter) flags.Add(kEmptyDeleter);
  flags_.store(flags, std::memory_order_relaxed);
}
References byte_capacity(), byte_length(), byte_length_, CHECK_IMPLIES, custom_deleter(), DCHECK_GE, DCHECK_IMPLIES, v8::internal::flags, flags_, has_guard_regions(), is_wasm_memory(), is_wasm_memory64(), kCustomDeleter, kEmptyDeleter, kHasGuardRegions, kIsResizableByJs, kIsShared, kIsWasmMemory, kIsWasmMemory64, v8::internal::kNotResizable, v8::internal::kResizable, v8::internal::kShared, max_byte_length(), and max_byte_length_.
Referenced by Allocate(), EmptyBackingStore(), TryAllocateAndPartiallyCommitMemory(), and WrapAllocation().
BackingStore() [2/2]
v8::internal::BackingStore::BackingStore (const BackingStore &) [private], [delete]
Member Function Documentation
Allocate()
std::unique_ptr< BackingStore > v8::internal::BackingStore::Allocate (Isolate * isolate, size_t byte_length, SharedFlag shared, InitializedFlag initialized) [static]
Definition at line 201 of file backing-store.cc.
                                 {
  void* buffer_start = nullptr;
  auto allocator = isolate->array_buffer_allocator();
  CHECK_NOT_NULL(allocator);
  if (byte_length > allocator->MaxAllocationSize()) return {};
  if (byte_length != 0) {
    auto counters = isolate->counters();
    int mb_length = static_cast<int>(byte_length / MB);
    if (mb_length > 0) {
      counters->array_buffer_big_allocations()->AddSample(mb_length);
    }
    if (shared == SharedFlag::kShared) {
      counters->shared_array_allocations()->AddSample(mb_length);
    }
    auto allocate_buffer = [allocator, initialized](size_t byte_length) {
      if (initialized == InitializedFlag::kUninitialized) {
        return allocator->AllocateUninitialized(byte_length);
      }
      return allocator->Allocate(byte_length);
    };
    buffer_start = isolate->heap()->AllocateExternalBackingStore(
        allocate_buffer, byte_length);
    if (buffer_start == nullptr) {
      // Allocation failed.
      counters->array_buffer_new_size_failures()->AddSample(mb_length);
      return {};
    }
#ifdef V8_ENABLE_SANDBOX
    // Check to catch use of a non-sandbox-compatible ArrayBufferAllocator.
    CHECK_WITH_MSG(isolate->isolate_group()->sandbox()->Contains(buffer_start),
                   "When the V8 Sandbox is enabled, ArrayBuffer backing stores "
                   "must be allocated inside the sandbox address space. Please "
                   "use an appropriate ArrayBuffer::Allocator to allocate "
                   "these buffers, or disable the sandbox.");
#endif
  }
  PageAllocator* page_allocator =
      isolate->isolate_group()->GetBackingStorePageAllocator();
  auto result = new BackingStore(page_allocator,
                                 buffer_start, // start
                                 byte_length, // length
                                 byte_length, // max length
                                 byte_length, // capacity
                                 shared, // shared
                                 ResizableFlag::kNotResizable, // resizable
                                 false, // is_wasm_memory
                                 false, // is_wasm_memory64
                                 false, // has_guard_regions
                                 false, // custom_deleter
                                 false); // empty_deleter
  TRACE_BS("BS:alloc bs=%p mem=%p (length=%zu)\n", result,
           result->buffer_start(), byte_length);
  result->SetAllocatorFromIsolate(isolate);
  return std::unique_ptr<BackingStore>(result);
}
References v8::internal::Heap::AllocateExternalBackingStore(), v8::internal::Isolate::array_buffer_allocator(), BackingStore(), buffer_start(), byte_length(), CHECK_NOT_NULL, CHECK_WITH_MSG, v8::internal::Isolate::counters(), v8::internal::IsolateGroup::GetBackingStorePageAllocator(), v8::internal::Isolate::heap(), v8::internal::Isolate::isolate_group(), v8::internal::kNotResizable, v8::internal::kShared, v8::internal::kUninitialized, v8::internal::MB, v8::base::internal::result, and TRACE_BS.
Referenced by v8::internal::JSTypedArray::GetBuffer(), v8::SharedArrayBuffer::MaybeNew(), v8::SharedArrayBuffer::New(), v8::ArrayBuffer::NewBackingStore(), v8::SharedArrayBuffer::NewBackingStore(), v8::internal::Factory::NewJSArrayBufferAndBackingStore(), and v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::TryAllocateBackingStore().
buffer_start()
void* v8::internal::BackingStore::buffer_start () const [inline]
Definition at line 88 of file backing-store.h.
                             {
    return buffer_start_ != nullptr ? buffer_start_ : EmptyBackingStoreBuffer();
  }
References v8::internal::EmptyBackingStoreBuffer().
Referenced by Allocate(), TryAllocateAndPartiallyCommitMemory(), and v8::internal::GlobalBackingStoreRegistry::Unregister().
byte_capacity()
size_t v8::internal::BackingStore::byte_capacity () const [inline]
Definition at line 96 of file backing-store.h.
{ return byte_capacity_; }
Referenced by BackingStore(), and TryAllocateAndPartiallyCommitMemory().
byte_length()
size_t v8::internal::BackingStore::byte_length (std::memory_order memory_order = std::memory_order_relaxed) const [inline]
Definition at line 91 of file backing-store.h.
                                                                    {
    return byte_length_.load(memory_order);
  }
Referenced by Allocate(), BackingStore(), TryAllocateAndPartiallyCommitMemory(), and ~BackingStore().
clear_flag()
void v8::internal::BackingStore::clear_flag (Flag flag) [inline], [private]
Definition at line 225 of file backing-store.h.
                             {
    base::EnumSet<Flag, uint16_t> old_flags =
        flags_.load(std::memory_order_relaxed);
    while (!flags_.compare_exchange_weak(old_flags, old_flags - flag,
                                         std::memory_order_relaxed)) {
      // Retry with updated `old_flags`.
    }
  }
Referenced by v8::internal::GlobalBackingStoreRegistry::Unregister().
custom_deleter()
bool v8::internal::BackingStore::custom_deleter () const [inline], [private]
Definition at line 237 of file backing-store.h.
{ return has_flag(kCustomDeleter); }
Referenced by BackingStore(), and ~BackingStore().
EmptyBackingStore()
std::unique_ptr< BackingStore > v8::internal::BackingStore::EmptyBackingStore (SharedFlag shared) [static]
Definition at line 720 of file backing-store.cc.
                       {
  auto result = new BackingStore(nullptr,
                                 nullptr, // start
                                 0, // length
                                 0, // max length
                                 0, // capacity
                                 shared, // shared
                                 ResizableFlag::kNotResizable, // resizable
                                 false, // is_wasm_memory
                                 false, // is_wasm_memory64
                                 false, // has_guard_regions
                                 false, // custom_deleter
                                 false); // empty_deleter
  return std::unique_ptr<BackingStore>(result);
}
References BackingStore(), v8::internal::kNotResizable, and v8::base::internal::result.
Referenced by v8::ArrayBuffer::GetBackingStore(), and v8::SharedArrayBuffer::GetBackingStore().
get_shared_wasm_memory_data()
SharedWasmMemoryData * v8::internal::BackingStore::get_shared_wasm_memory_data () const [private]
Definition at line 748 of file backing-store.cc.
                                                                      {
  CHECK(is_wasm_memory() && is_shared());
  auto shared_wasm_memory_data = type_specific_data_.shared_wasm_memory_data;
  CHECK(shared_wasm_memory_data);
  return shared_wasm_memory_data;
}
References CHECK, is_shared(), is_wasm_memory(), v8::internal::BackingStore::TypeSpecificData::shared_wasm_memory_data, and type_specific_data_.
Referenced by ~BackingStore().
get_v8_api_array_buffer_allocator()
v8::ArrayBuffer::Allocator * v8::internal::BackingStore::get_v8_api_array_buffer_allocator () [private]
Definition at line 738 of file backing-store.cc.
                                                                        {
  CHECK(!is_wasm_memory());
  auto array_buffer_allocator =
      holds_shared_ptr_to_allocator()
          ? type_specific_data_.v8_api_array_buffer_allocator_shared.get()
          : type_specific_data_.v8_api_array_buffer_allocator;
  CHECK_NOT_NULL(array_buffer_allocator);
  return array_buffer_allocator;
}
References CHECK, CHECK_NOT_NULL, holds_shared_ptr_to_allocator(), is_wasm_memory(), type_specific_data_, v8::internal::BackingStore::TypeSpecificData::v8_api_array_buffer_allocator, and v8::internal::BackingStore::TypeSpecificData::v8_api_array_buffer_allocator_shared.
Referenced by ~BackingStore().
globally_registered()
bool v8::internal::BackingStore::globally_registered () const [inline], [private]
Definition at line 238 of file backing-store.h.
{ return has_flag(kGloballyRegistered); }
Referenced by v8::internal::GlobalBackingStoreRegistry::Unregister().
GrowInPlace()
BackingStore::ResizeOrGrowResult v8::internal::BackingStore::GrowInPlace (Isolate * isolate, size_t new_byte_length)
Definition at line 648 of file backing-store.cc.
                                              {
  size_t page_size = AllocatePageSize();
  size_t new_committed_pages;
  bool round_return_value =
      RoundUpToPageSize(new_byte_length, page_size,
                        JSArrayBuffer::kMaxByteLength, &new_committed_pages);
  CHECK(round_return_value);
  size_t new_committed_length = new_committed_pages * page_size;
  DCHECK_LE(new_byte_length, new_committed_length);
  DCHECK(is_shared());
  // See comment in GrowWasmMemoryInPlace.
  // GrowableSharedArrayBuffer.prototype.grow can be called from several
  // threads. If two threads try to grow() in a racy way, the spec allows the
  // larger grow to throw also if the smaller grow succeeds first. The
  // implementation below doesn't throw in that case - instead, it retries and
  // succeeds. If the larger grow finishes first though, the smaller grow must
  // throw.
  size_t old_byte_length = byte_length_.load(std::memory_order_seq_cst);
  while (true) {
    if (new_byte_length < old_byte_length) {
      // The caller checks for the new_byte_length < old_byte_length_ case. This
      // can only happen if another thread grew the memory after that.
      return kRace;
    }
    if (new_byte_length == old_byte_length) {
      // i::SetPermissions with size 0 fails on some platforms, so special
      // handling for the case old_byte_length == new_byte_length == 0 is
      // required.
      return kSuccess;
    }
    // Try to adjust the permissions on the memory.
    if (!i::SetPermissions(GetPlatformPageAllocator(), buffer_start_,
                           new_committed_length, PageAllocator::kReadWrite)) {
      return kFailure;
    }
    // compare_exchange_weak updates old_byte_length.
    if (byte_length_.compare_exchange_weak(old_byte_length, new_byte_length,
                                           std::memory_order_seq_cst)) {
      // Successfully updated both the length and permissions.
      break;
    }
  }
  return kSuccess;
}
References v8::internal::AllocatePageSize(), buffer_start_, byte_length_, CHECK, v8::internal::DCHECK(), DCHECK_LE, v8::internal::GetPlatformPageAllocator(), is_shared(), kFailure, v8::internal::JSArrayBuffer::kMaxByteLength, kRace, v8::PageAllocator::kReadWrite, kSuccess, v8::internal::RoundUpToPageSize(), and v8::internal::SetPermissions().
has_flag()
bool v8::internal::BackingStore::has_flag (Flag flag) const [inline], [private]
Definition at line 214 of file backing-store.h.
                                 {
    return flags_.load(std::memory_order_relaxed).contains(flag);
  }
has_guard_regions()
bool v8::internal::BackingStore::has_guard_regions () const [inline]
Definition at line 101 of file backing-store.h.
{ return has_flag(kHasGuardRegions); }
Referenced by BackingStore(), TryAllocateAndPartiallyCommitMemory(), and ~BackingStore().
holds_shared_ptr_to_allocator()
bool v8::internal::BackingStore::holds_shared_ptr_to_allocator () const [inline], [private]
Definition at line 234 of file backing-store.h.
                                             {
    return has_flag(kHoldsSharedPtrToAllocater);
  }
Referenced by get_v8_api_array_buffer_allocator(), and ~BackingStore().
id()
uint32_t v8::internal::BackingStore::id () const [inline]
Definition at line 184 of file backing-store.h.
{ return id_; }
is_resizable_by_js()
bool v8::internal::BackingStore::is_resizable_by_js () const [inline]
Definition at line 98 of file backing-store.h.
{ return has_flag(kIsResizableByJs); }
Referenced by ~BackingStore().
is_shared()
bool v8::internal::BackingStore::is_shared () const [inline]
Definition at line 97 of file backing-store.h.
{ return has_flag(kIsShared); }
Referenced by get_shared_wasm_memory_data(), GrowInPlace(), ResizeInPlace(), and ~BackingStore().
is_wasm_memory()
bool v8::internal::BackingStore::is_wasm_memory () const [inline]
Definition at line 99 of file backing-store.h.
{ return has_flag(kIsWasmMemory); }
Referenced by BackingStore(), get_shared_wasm_memory_data(), get_v8_api_array_buffer_allocator(), TryAllocateAndPartiallyCommitMemory(), v8::internal::GlobalBackingStoreRegistry::Unregister(), and ~BackingStore().
is_wasm_memory64()
bool v8::internal::BackingStore::is_wasm_memory64 () const [inline]
Definition at line 100 of file backing-store.h.
{ return has_flag(kIsWasmMemory64); }
Referenced by BackingStore(), TryAllocateAndPartiallyCommitMemory(), and ~BackingStore().
IsEmpty()
bool v8::internal::BackingStore::IsEmpty () const [inline]
Definition at line 103 of file backing-store.h.
                       {
    DCHECK_GE(byte_capacity_, byte_length_);
    return byte_capacity_ == 0;
  }
References DCHECK_GE.
max_byte_length()
size_t v8::internal::BackingStore::max_byte_length () const [inline]
Definition at line 95 of file backing-store.h.
{ return max_byte_length_; }
Referenced by BackingStore(), and TryAllocateAndPartiallyCommitMemory().
operator=()
BackingStore& v8::internal::BackingStore::operator= (const BackingStore &) [private], [delete]
PerIsolateAccountingLength()
size_t v8::internal::BackingStore::PerIsolateAccountingLength () [inline]
Definition at line 167 of file backing-store.h.
                                      {
    if (has_flag(kIsShared)) {
      // TODO(titzer): SharedArrayBuffers and shared WasmMemorys cause problems
      // with accounting for per-isolate external memory. In particular, sharing
      // the same array buffer or memory multiple times, which happens in stress
      // tests, can cause overcounting, leading to GC thrashing. Fix with global
      // accounting?
      return 0;
    }
    if (has_flag(kEmptyDeleter)) {
      // The backing store has an empty deleter. Even if the backing store is
      // freed after GC, it would not free the memory block.
      return 0;
    }
    return byte_length();
  }
ResizeInPlace()
BackingStore::ResizeOrGrowResult v8::internal::BackingStore::ResizeInPlace (Isolate * isolate, size_t new_byte_length)
Definition at line 583 of file backing-store.cc.
                                              {
  size_t page_size = AllocatePageSize();
  size_t new_committed_pages;
  bool round_return_value =
      RoundUpToPageSize(new_byte_length, page_size,
                        JSArrayBuffer::kMaxByteLength, &new_committed_pages);
  CHECK(round_return_value);
  size_t new_committed_length = new_committed_pages * page_size;
  DCHECK_LE(new_byte_length, new_committed_length);
  DCHECK(!is_shared());
  if (new_byte_length < byte_length_) {
    // Zero the memory so that in case the buffer is grown later, we have
    // zeroed the contents already. This is especially needed for the portion of
    // the memory we're not going to decommit below (since it belongs to a
    // committed page). In addition, we don't rely on all platforms always
    // zeroing decommitted-then-recommitted memory, but zero the memory
    // explicitly here.
    memset(reinterpret_cast<uint8_t*>(buffer_start_) + new_byte_length, 0,
           byte_length_ - new_byte_length);
    // Check if we can un-commit some pages.
    size_t old_committed_pages;
    round_return_value =
        RoundUpToPageSize(byte_length_, page_size,
                          JSArrayBuffer::kMaxByteLength, &old_committed_pages);
    CHECK(round_return_value);
    DCHECK_LE(new_committed_pages, old_committed_pages);
    if (new_committed_pages < old_committed_pages) {
      size_t old_committed_length = old_committed_pages * page_size;
      if (!i::SetPermissions(
              GetPlatformPageAllocator(),
              reinterpret_cast<uint8_t*>(buffer_start_) + new_committed_length,
              old_committed_length - new_committed_length,
              PageAllocator::kNoAccess)) {
        return kFailure;
      }
    }
    // Changing the byte length wouldn't strictly speaking be needed, since
    // the JSArrayBuffer already stores the updated length. This is to keep
    // the BackingStore and JSArrayBuffer in sync.
    byte_length_ = new_byte_length;
    return kSuccess;
  }
  if (new_byte_length == byte_length_) {
    // i::SetPermissions with size 0 fails on some platforms, so special
    // handling for the case byte_length_ == new_byte_length == 0 is required.
    return kSuccess;
  }
  // Try to adjust the permissions on the memory.
  if (!i::SetPermissions(GetPlatformPageAllocator(), buffer_start_,
                         new_committed_length, PageAllocator::kReadWrite)) {
    return kFailure;
  }
  byte_length_ = new_byte_length;
  return kSuccess;
}
References v8::internal::AllocatePageSize(), buffer_start_, byte_length_, CHECK, v8::internal::DCHECK(), DCHECK_LE, v8::internal::GetPlatformPageAllocator(), is_shared(), kFailure, v8::internal::JSArrayBuffer::kMaxByteLength, v8::PageAllocator::kNoAccess, v8::PageAllocator::kReadWrite, kSuccess, v8::internal::RoundUpToPageSize(), and v8::internal::SetPermissions().
set_flag()
void v8::internal::BackingStore::set_flag (Flag flag) [inline], [private]
Definition at line 217 of file backing-store.h.
                           {
    base::EnumSet<Flag, uint16_t> old_flags =
        flags_.load(std::memory_order_relaxed);
    while (!flags_.compare_exchange_weak(old_flags, old_flags | flag,
                                         std::memory_order_relaxed)) {
      // Retry with updated `old_flags`.
    }
  }
Referenced by SetAllocatorFromIsolate().
SetAllocatorFromIsolate()
void v8::internal::BackingStore::SetAllocatorFromIsolate (Isolate * isolate) [private]
Definition at line 263 of file backing-store.cc.
                                                           {
  if (auto allocator_shared = isolate->array_buffer_allocator_shared()) {
    set_flag(kHoldsSharedPtrToAllocater);
    new (&type_specific_data_.v8_api_array_buffer_allocator_shared)
        std::shared_ptr<v8::ArrayBuffer::Allocator>(
            std::move(allocator_shared));
  } else {
    type_specific_data_.v8_api_array_buffer_allocator =
        isolate->array_buffer_allocator();
  }
}
References v8::internal::Isolate::array_buffer_allocator(), v8::internal::Isolate::array_buffer_allocator_shared(), kHoldsSharedPtrToAllocater, set_flag(), type_specific_data_, v8::internal::BackingStore::TypeSpecificData::v8_api_array_buffer_allocator, and v8::internal::BackingStore::TypeSpecificData::v8_api_array_buffer_allocator_shared.
TryAllocateAndPartiallyCommitMemory()
std::unique_ptr< BackingStore > v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory (Isolate * isolate, size_t byte_length, size_t max_byte_length, size_t page_size, size_t initial_pages, size_t maximum_pages, WasmMemoryFlag wasm_memory, SharedFlag shared, bool has_guard_regions = false) [static]
Definition at line 275 of file backing-store.cc.
                                                                           {
  // Enforce engine limitation on the maximum number of pages.
  if (maximum_pages > std::numeric_limits<size_t>::max() / page_size) {
    return nullptr;
  }
  // Cannot reserve 0 pages on some OSes.
  if (maximum_pages == 0) maximum_pages = 1;
  TRACE_BS("BSw:try %zu pages, %zu max\n", initial_pages, maximum_pages);
#if V8_ENABLE_WEBASSEMBLY
  bool is_wasm_memory = wasm_memory != WasmMemoryFlag::kNotWasm;
  bool is_wasm_memory64 = wasm_memory == WasmMemoryFlag::kWasmMemory64;
#else
  CHECK_EQ(WasmMemoryFlag::kNotWasm, wasm_memory);
  constexpr bool is_wasm_memory = false;
  constexpr bool is_wasm_memory64 = false;
#endif // V8_ENABLE_WEBASSEMBLY
  DCHECK_IMPLIES(has_guard_regions, is_wasm_memory);
  // For accounting purposes, whether a GC was necessary.
  bool did_retry = false;
  // A helper to try running a function up to 3 times, executing a GC
  // if the first and second attempts failed.
  auto gc_retry = [&](const std::function<bool()>& fn) {
    for (int i = 0; i < 3; i++) {
      if (fn()) return true;
      // Collect garbage and retry.
      did_retry = true;
      if (isolate != nullptr) {
        isolate->heap()->MemoryPressureNotification(
            MemoryPressureLevel::kCritical, true);
      }
    }
    return false;
  };
  size_t byte_capacity = maximum_pages * page_size;
  size_t reservation_size =
      GetReservationSize(has_guard_regions, byte_capacity, is_wasm_memory64);
  //--------------------------------------------------------------------------
  // Allocate pages (inaccessible by default).
  //--------------------------------------------------------------------------
  void* allocation_base = nullptr;
#ifdef V8_COMPRESS_POINTERS_IN_MULTIPLE_CAGES
#ifdef V8_ENABLE_SANDBOX
  CHECK_WITH_MSG(isolate || Sandbox::current(),
#else
  CHECK_WITH_MSG(isolate || IsolateGroup::current(),
#endif
                 "One must enter an v8::Isolate before allocating resizable "
                 "array backing stores");
#endif
  IsolateGroup* group =
      isolate ? isolate->isolate_group() : IsolateGroup::current();
  PageAllocator* page_allocator = group ? group->GetBackingStorePageAllocator()
                                        : GetArrayBufferPageAllocator();
  auto allocate_pages = [&] {
    allocation_base = AllocatePages(page_allocator, reservation_size, page_size,
                                    PageAllocator::kNoAccess);
    return allocation_base != nullptr;
  };
  if (!gc_retry(allocate_pages)) {
    // Page allocator could not reserve enough pages.
    if (isolate != nullptr) {
      RecordStatus(isolate, AllocationStatus::kOtherFailure);
    }
    TRACE_BS("BSw:try failed to allocate pages\n");
    return {};
  }
  uint8_t* buffer_start = reinterpret_cast<uint8_t*>(allocation_base);
  //--------------------------------------------------------------------------
  // Commit the initial pages (allow read/write).
  //--------------------------------------------------------------------------
  size_t committed_byte_length = initial_pages * page_size;
  auto commit_memory = [&] {
    return committed_byte_length == 0 ||
           SetPermissions(page_allocator, buffer_start, committed_byte_length,
                          PageAllocator::kReadWrite);
  };
  if (!gc_retry(commit_memory)) {
    TRACE_BS("BSw:try failed to set permissions (%p, %zu)\n", buffer_start,
             committed_byte_length);
    FreePages(page_allocator, allocation_base, reservation_size);
    // SetPermissions put us over the process memory limit.
    // We return an empty result so that the caller can throw an exception.
    return {};
  }
  if (isolate != nullptr) {
    RecordStatus(isolate, did_retry ? AllocationStatus::kSuccessAfterRetry
                                    : AllocationStatus::kSuccess);
  }
  ResizableFlag resizable =
      is_wasm_memory ? ResizableFlag::kNotResizable : ResizableFlag::kResizable;
  auto result = new BackingStore(page_allocator,
                                 buffer_start, // start
                                 byte_length, // length
                                 max_byte_length, // max_byte_length
                                 byte_capacity, // capacity
                                 shared, // shared
                                 resizable, // resizable
                                 is_wasm_memory, // is_wasm_memory
                                 is_wasm_memory64, // is_wasm_memory64
                                 has_guard_regions, // has_guard_regions
                                 false, // custom_deleter
                                 false); // empty_deleter
  TRACE_BS(
      "BSw:alloc bs=%p mem=%p (length=%zu, capacity=%zu, reservation=%zu)\n",
      result, result->buffer_start(), byte_length, byte_capacity,
      reservation_size);
  return std::unique_ptr<BackingStore>(result);
}
References v8::internal::AllocatePages(), BackingStore(), v8::internal::bool, buffer_start(), byte_capacity(), byte_length(), CHECK_EQ, CHECK_WITH_MSG, v8::internal::IsolateGroup::current(), DCHECK_IMPLIES, v8::internal::FreePages(), v8::internal::GetArrayBufferPageAllocator(), v8::internal::anonymous_namespace{backing-store.cc}::GetReservationSize(), has_guard_regions(), v8::internal::Isolate::heap(), is_wasm_memory(), is_wasm_memory64(), v8::internal::Isolate::isolate_group(), v8::kCritical, v8::PageAllocator::kNoAccess, v8::internal::kNotResizable, v8::internal::kNotWasm, v8::PageAllocator::kReadWrite, v8::internal::kResizable, v8::internal::detail::kSuccess, v8::internal::kWasmMemory64, max_byte_length(), v8::internal::Heap::MemoryPressureNotification(), v8::internal::anonymous_namespace{backing-store.cc}::RecordStatus(), v8::base::internal::result, v8::internal::SetPermissions(), and TRACE_BS.
Referenced by v8::internal::Factory::NewJSArrayBufferAndBackingStore(), v8::ArrayBuffer::NewResizableBackingStore(), and v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::TryAllocateBackingStore().
WrapAllocation()
std::unique_ptr< BackingStore > v8::internal::BackingStore::WrapAllocation (void * allocation_base, size_t allocation_length, v8::BackingStore::DeleterCallback deleter, void * deleter_data, SharedFlag shared) [static]
Definition at line 697 of file backing-store.cc.
                       {
  bool is_empty_deleter = (deleter == v8::BackingStore::EmptyDeleter);
  auto result = new BackingStore(nullptr,
                                 allocation_base, // start
                                 allocation_length, // length
                                 allocation_length, // max length
                                 allocation_length, // capacity
                                 shared, // shared
                                 ResizableFlag::kNotResizable, // resizable
                                 false, // is_wasm_memory
                                 false, // is_wasm_memory64
                                 false, // has_guard_regions
                                 true, // custom_deleter
                                 is_empty_deleter); // empty_deleter
  result->type_specific_data_.deleter = {deleter, deleter_data};
  TRACE_BS("BS:wrap bs=%p mem=%p (length=%zu)\n", result,
           result->buffer_start(), result->byte_length());
  return std::unique_ptr<BackingStore>(result);
}
References BackingStore(), v8::BackingStore::EmptyDeleter(), v8::internal::kNotResizable, v8::base::internal::result, and TRACE_BS.
Referenced by v8::ArrayBuffer::NewBackingStore(), and v8::SharedArrayBuffer::NewBackingStore().
Friends And Related Function Documentation
GlobalBackingStoreRegistry
friend class GlobalBackingStoreRegistry [friend]
Definition at line 187 of file backing-store.h.
Member Data Documentation
buffer_start_
void* v8::internal::BackingStore::buffer_start_ = nullptr [private]
Definition at line 240 of file backing-store.h.
Referenced by GrowInPlace(), ResizeInPlace(), and ~BackingStore().
byte_capacity_
size_t v8::internal::BackingStore::byte_capacity_ [private]
Definition at line 245 of file backing-store.h.
Referenced by ~BackingStore().
byte_length_
std::atomic<size_t> v8::internal::BackingStore::byte_length_ [private]
Definition at line 241 of file backing-store.h.
Referenced by BackingStore(), GrowInPlace(), ResizeInPlace(), and ~BackingStore().
flags_
std::atomic<base::EnumSet<Flag, uint16_t> > v8::internal::BackingStore::flags_ [private]
Definition at line 280 of file backing-store.h.
Referenced by BackingStore().
id_
const uint32_t v8::internal::BackingStore::id_ [private]
Definition at line 249 of file backing-store.h.
max_byte_length_
size_t v8::internal::BackingStore::max_byte_length_ [private]
Definition at line 243 of file backing-store.h.
Referenced by BackingStore().
page_allocator_
v8::PageAllocator* v8::internal::BackingStore::page_allocator_ = nullptr [private]
Definition at line 251 of file backing-store.h.
Referenced by ~BackingStore().
type_specific_data_
union v8::internal::BackingStore::TypeSpecificData v8::internal::BackingStore::type_specific_data_ [private]
Referenced by get_shared_wasm_memory_data(), get_v8_api_array_buffer_allocator(), SetAllocatorFromIsolate(), and ~BackingStore().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/backing-store.h
/mnt/V8SourceCode/src/objects/backing-store.cc