v8_inspector::V8Regex Class Reference
#include <v8-regex.h>
Public Member Functions
V8Regex (V8InspectorImpl *, const String16 &, bool caseSensitive, bool multiline=false)
V8Regex (const V8Regex &)=delete
V8Regex & operator= (const V8Regex &)=delete
int match (const String16 &, int startFrom=0, int *matchLength=nullptr) const
bool isValid () const
const String16 & errorMessage () const
Private Attributes
V8InspectorImpl * m_inspector
v8::Global< v8::RegExp > m_regex
String16 m_errorMessage
Detailed Description
Definition at line 22 of file v8-regex.h.
Constructor & Destructor Documentation
V8Regex() [1/2]
v8_inspector::V8Regex::V8Regex (V8InspectorImpl * inspector, const String16 & pattern, bool caseSensitive, bool multiline = false)
Definition at line 20 of file v8-regex.cc.
    : m_inspector(inspector) {
  v8::Isolate* isolate = m_inspector->isolate();
  v8::HandleScope handleScope(isolate);
  v8::Local<v8::Context> context;
  if (!m_inspector->regexContext().ToLocal(&context)) {
    DCHECK(isolate->IsExecutionTerminating());
    m_errorMessage = "terminated";
    return;
  }
  v8::Context::Scope contextScope(context);
  v8::TryCatch tryCatch(isolate);
  unsigned flags = v8::RegExp::kNone;
  if (!caseSensitive) flags |= v8::RegExp::kIgnoreCase;
  if (multiline) flags |= v8::RegExp::kMultiline;
  v8::Local<v8::RegExp> regex;
  // Protect against reentrant debugger calls via interrupts.
  v8::debug::PostponeInterruptsScope no_interrupts(m_inspector->isolate());
  if (v8::RegExp::New(context, toV8String(isolate, pattern),
                      static_cast<v8::RegExp::Flags>(flags))
          .ToLocal(&regex))
    m_regex.Reset(isolate, regex);
  else if (tryCatch.HasCaught())
    m_errorMessage = toProtocolString(isolate, tryCatch.Message()->Get());
  else
    m_errorMessage = "Internal error";
}
References DCHECK, flags(), v8::TryCatch::HasCaught(), v8::Isolate::IsExecutionTerminating(), v8_inspector::V8InspectorImpl::isolate(), v8::RegExp::kIgnoreCase, v8::RegExp::kMultiline, v8::RegExp::kNone, m_errorMessage, m_inspector, m_regex, v8::TryCatch::Message(), v8::RegExp::New(), v8_inspector::V8InspectorImpl::regexContext(), v8::PersistentBase< T >::Reset(), v8_inspector::toProtocolString(), and v8_inspector::toV8String().
V8Regex() [2/2]
v8_inspector::V8Regex::V8Regex (const V8Regex &) [delete]
Member Function Documentation
errorMessage()
const String16& v8_inspector::V8Regex::errorMessage () const [inline]
Definition at line 31 of file v8-regex.h.
{ return m_errorMessage; }
References m_errorMessage.
isValid()
bool v8_inspector::V8Regex::isValid () const [inline]
Definition at line 30 of file v8-regex.h.
{ return !m_regex.IsEmpty(); }
References v8::api_internal::IndirectHandleBase::IsEmpty(), and m_regex.
match()
int v8_inspector::V8Regex::match (const String16 & string, int startFrom = 0, int * matchLength = nullptr) const
Definition at line 51 of file v8-regex.cc.
                                           {
  if (matchLength) *matchLength = 0;
  if (m_regex.IsEmpty() || string.isEmpty()) return -1;
  // v8 strings are limited to int.
  if (string.length() > INT_MAX) return -1;
  v8::Isolate* isolate = m_inspector->isolate();
  v8::HandleScope handleScope(isolate);
  v8::Local<v8::Context> context;
  if (!m_inspector->regexContext().ToLocal(&context)) {
    DCHECK(isolate->IsExecutionTerminating());
    return -1;
  }
  v8::Context::Scope contextScope(context);
  v8::MicrotasksScope microtasks(context,
                                 v8::MicrotasksScope::kDoNotRunMicrotasks);
  // Protect against reentrant debugger calls via interrupts.
  v8::debug::PostponeInterruptsScope no_interrupts(m_inspector->isolate());
  v8::TryCatch tryCatch(isolate);
  v8::Local<v8::RegExp> regex = m_regex.Get(isolate);
  v8::Local<v8::Value> exec;
  if (!regex->Get(context, toV8StringInternalized(isolate, "exec"))
           .ToLocal(&exec))
    return -1;
  v8::Local<v8::Value> argv[] = {
      toV8String(isolate, string.substring(startFrom))};
  v8::Local<v8::Value> returnValue;
  if (!exec.As<v8::Function>()
           ->Call(context, regex, arraysize(argv), argv)
           .ToLocal(&returnValue))
    return -1;
  // RegExp#exec returns null if there's no match, otherwise it returns an
  // Array of strings with the first being the whole match string and others
  // being subgroups. The Array also has some random properties tacked on like
  // "index" which is the offset of the match.
  //
  // https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/RegExp/exec
  DCHECK(!returnValue.IsEmpty());
  if (!returnValue->IsArray()) return -1;
  v8::Local<v8::Array> result = returnValue.As<v8::Array>();
  v8::Local<v8::Value> matchOffset;
  if (!result->Get(context, toV8StringInternalized(isolate, "index"))
           .ToLocal(&matchOffset))
    return -1;
  if (matchLength) {
    v8::Local<v8::Value> match;
    if (!result->Get(context, 0).ToLocal(&match)) return -1;
    *matchLength = match.As<v8::String>()->Length();
  }
  return matchOffset.As<v8::Int32>()->Value() + startFrom;
}
References arraysize, v8::Local< T >::As(), v8::Function::Call(), DCHECK, v8::PersistentBase< T >::Get(), v8::Value::IsArray(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Isolate::IsExecutionTerminating(), v8_inspector::V8InspectorImpl::isolate(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::internal::length, m_inspector, m_regex, v8_inspector::V8InspectorImpl::regexContext(), v8::base::internal::result, v8_inspector::toV8String(), and v8_inspector::toV8StringInternalized().
Referenced by v8_inspector::anonymous_namespace{search-util.cc}::scriptRegexpMatchesByLines().
operator=()
V8Regex& v8_inspector::V8Regex::operator= (const V8Regex &) [delete]
Member Data Documentation
m_errorMessage
String16 v8_inspector::V8Regex::m_errorMessage [private]
Definition at line 36 of file v8-regex.h.
Referenced by errorMessage(), and V8Regex().
m_inspector
V8InspectorImpl* v8_inspector::V8Regex::m_inspector [private]
Definition at line 34 of file v8-regex.h.
Referenced by match(), and V8Regex().
m_regex
v8::Global<v8::RegExp> v8_inspector::V8Regex::m_regex [private]
Definition at line 35 of file v8-regex.h.
Referenced by isValid(), match(), and V8Regex().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-regex.h
/mnt/V8SourceCode/src/inspector/v8-regex.cc