v8::internal::wasm::WellKnownImportsList Class Reference
#include <well-known-imports.h>
Public Types
enum class UpdateResult : bool { kFoundIncompatibility
, kOK
 }
Public Member Functions
WellKnownImportsList ()=default
void Initialize (int size)
void Initialize (base::Vector< const WellKnownImport > entries)
WellKnownImport get (int index) const
V8_WARN_UNUSED_RESULT UpdateResult Update (base::Vector< WellKnownImport > entries)
Private Attributes
std::unique_ptr< std::atomic< WellKnownImport >[]> statuses_
Detailed Description
Definition at line 119 of file well-known-imports.h.
Member Enumeration Documentation
UpdateResult
enum v8::internal::wasm::WellKnownImportsList::UpdateResult : bool [strong]
Enumerator
kFoundIncompatibility
kOK
Definition at line 121 of file well-known-imports.h.
: bool { kFoundIncompatibility, kOK };
Constructor & Destructor Documentation
WellKnownImportsList()
v8::internal::wasm::WellKnownImportsList::WellKnownImportsList () [default]
Member Function Documentation
get()
WellKnownImport v8::internal::wasm::WellKnownImportsList::get (int index) const [inline]
Definition at line 144 of file well-known-imports.h.
                                       {
    DCHECK_LT(index, size_);
    return statuses_[index].load(std::memory_order_relaxed);
  }
References DCHECK_LT, v8::internal::index, and statuses_.
Referenced by v8::internal::wasm::GetImports(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::wasm::NativeModule::PublishCodeLocked(), and v8::internal::wasm::InstanceBuilder::SanitizeImports().
Initialize() [1/2]
void v8::internal::wasm::WellKnownImportsList::Initialize (base::Vector< const WellKnownImport > entries)
Definition at line 174 of file well-known-imports.cc.
                                               {
  DCHECK_EQ(entries.size(), static_cast<size_t>(size_));
  for (size_t i = 0; i < entries.size(); i++) {
    DCHECK_EQ(WellKnownImport::kUninstantiated,
              statuses_[i].load(std::memory_order_relaxed));
    statuses_[i].store(entries[i], std::memory_order_relaxed);
  }
}
References DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kUninstantiated, v8::base::Vector< T >::size(), and statuses_.
Initialize() [2/2]
void v8::internal::wasm::WellKnownImportsList::Initialize (int size) [inline]
Definition at line 126 of file well-known-imports.h.
                            {
#if DEBUG
    DCHECK_EQ(-1, size_);
    size_ = size;
#endif
    static_assert(static_cast<int>(WellKnownImport::kUninstantiated) == 0);
    statuses_ = std::make_unique<std::atomic<WellKnownImport>[]>(size);
#if !defined(__cpp_lib_atomic_value_initialization) || \
    __cpp_lib_atomic_value_initialization < 201911L
    for (int i = 0; i < size; i++) {
      std::atomic_init(&statuses_.get()[i], WellKnownImport::kUninstantiated);
    }
#endif
  }
References DCHECK_EQ, v8::internal::wasm::kUninstantiated, size(), and statuses_.
Referenced by v8::internal::wasm::NativeModuleDeserializer::ReadHeader(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
Update()
WellKnownImportsList::UpdateResult v8::internal::wasm::WellKnownImportsList::Update (base::Vector< WellKnownImport > entries)
Definition at line 145 of file well-known-imports.cc.
                                         {
  DCHECK_EQ(entries.size(), static_cast<size_t>(size_));
  for (size_t i = 0; i < entries.size(); i++) {
    WellKnownImport entry = entries[i];
    DCHECK(entry != WellKnownImport::kUninstantiated);
    WellKnownImport old = statuses_[i].load(std::memory_order_relaxed);
    if (old == WellKnownImport::kGeneric) continue;
    if (old == entry) continue;
    if (old == WellKnownImport::kUninstantiated) {
      statuses_[i].store(entry, std::memory_order_relaxed);
    } else {
      // To avoid having to clear Turbofan code multiple times, we give up
      // entirely once the first problem occurs.
      // This is a heuristic; we could also choose to make finer-grained
      // decisions and only set {statuses_[i] = kGeneric}. We expect that
      // this case won't ever happen for production modules, so guarding
      // against pathological cases seems more important than being lenient
      // towards almost-well-behaved modules.
      for (size_t j = 0; j < entries.size(); j++) {
        statuses_[j].store(WellKnownImport::kGeneric,
                           std::memory_order_relaxed);
      }
      return UpdateResult::kFoundIncompatibility;
    }
  }
  return UpdateResult::kOK;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kFoundIncompatibility, v8::internal::wasm::kGeneric, kOK, v8::internal::wasm::kUninstantiated, v8::base::Vector< T >::size(), and statuses_.
Member Data Documentation
statuses_
std::unique_ptr<std::atomic<WellKnownImport>[]> v8::internal::wasm::WellKnownImportsList::statuses_ [private]
Definition at line 160 of file well-known-imports.h.
Referenced by get(), Initialize(), and Update().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/well-known-imports.h
/mnt/V8SourceCode/src/wasm/well-known-imports.cc