v8::internal::JSWrappedFunction Class Reference
#include <js-function.h>
Static Public Member Functions
static MaybeHandle< String > GetName (Isolate *isolate, DirectHandle< JSWrappedFunction > function)
static Maybe< int > GetLength (Isolate *isolate, DirectHandle< JSWrappedFunction > function)
static MaybeDirectHandle< Object > Create (Isolate *isolate, DirectHandle< NativeContext > creation_context, DirectHandle< JSReceiver > value)
static DirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSWrappedFunction > function)
Detailed Description
Definition at line 67 of file js-function.h.
Member Function Documentation
Create()
MaybeDirectHandle< Object > v8::internal::JSWrappedFunction::Create (Isolate * isolate, DirectHandle< NativeContext > creation_context, DirectHandle< JSReceiver > value) [static]
Definition at line 559 of file js-function.cc.
                                    {
  // The value must be a callable according to the specification.
  DCHECK(IsCallable(*value));
  // The intermediate wrapped functions are not user-visible. And calling a
  // wrapped function won't cause a side effect in the creation realm.
  // Unwrap here to avoid nested unwrapping at the call site.
  if (IsJSWrappedFunction(*value)) {
    auto target_wrapped = Cast<JSWrappedFunction>(value);
    value = direct_handle(target_wrapped->wrapped_target_function(), isolate);
  }
  // 1. Let internalSlotsList be the internal slots listed in Table 2, plus
  // [[Prototype]] and [[Extensible]].
  // 2. Let wrapped be ! MakeBasicObject(internalSlotsList).
  // 3. Set wrapped.[[Prototype]] to
  // callerRealm.[[Intrinsics]].[[%Function.prototype%]].
  // 4. Set wrapped.[[Call]] as described in 2.1.
  // 5. Set wrapped.[[WrappedTargetFunction]] to Target.
  // 6. Set wrapped.[[Realm]] to callerRealm.
  DirectHandle<JSWrappedFunction> wrapped =
      isolate->factory()->NewJSWrappedFunction(creation_context, value);
  // 7. Let result be CopyNameAndLength(wrapped, Target, "wrapped").
  Maybe<bool> is_abrupt =
      JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(
          isolate, wrapped, value, DirectHandle<String>(), 0);
  // 8. If result is an Abrupt Completion, throw a TypeError exception.
  if (is_abrupt.IsNothing()) {
    DCHECK(isolate->has_exception());
    DirectHandle<Object> exception(isolate->exception(), isolate);
    isolate->clear_exception();
    // The TypeError thrown is created with creation Realm's TypeError
    // constructor instead of the executing Realm's.
    DirectHandle<JSFunction> type_error_function(
        creation_context->type_error_function(), isolate);
    DirectHandle<String> string =
        Object::NoSideEffectsToString(isolate, exception);
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewError(type_error_function, MessageTemplate::kCannotWrap, string),
        {});
  }
  DCHECK(is_abrupt.FromJust());
  // 9. Return wrapped.
  return wrapped;
}
References v8::internal::Isolate::clear_exception(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::Isolate::has_exception(), v8::Maybe< T >::IsNothing(), v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::internal::Factory::NewJSWrappedFunction(), v8::internal::Object::NoSideEffectsToString(), THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{builtins-shadow-realm.cc}::GetWrappedValue(), and v8::internal::RUNTIME_FUNCTION().
GetLength()
Maybe< int > v8::internal::JSWrappedFunction::GetLength (Isolate * isolate, DirectHandle< JSWrappedFunction > function) [static]
Definition at line 537 of file js-function.cc.
                                                                {
  STACK_CHECK(isolate, Nothing<int>());
  DirectHandle<JSReceiver> target(function->wrapped_target_function(), isolate);
  if (IsJSBoundFunction(*target)) {
    return JSBoundFunction::GetLength(
        isolate, direct_handle(
                     Cast<JSBoundFunction>(function->wrapped_target_function()),
                     isolate));
  }
  // All non JSFunction targets get a direct property and don't use this
  // accessor.
  return Just(Cast<JSFunction>(target)->length());
}
References v8::internal::direct_handle(), v8::internal::JSBoundFunction::GetLength(), v8::Just(), v8::internal::length, and STACK_CHECK.
Referenced by v8::internal::JSBoundFunction::GetLength().
GetName()
MaybeHandle< String > v8::internal::JSWrappedFunction::GetName (Isolate * isolate, DirectHandle< JSWrappedFunction > function) [static]
Definition at line 515 of file js-function.cc.
                                                                {
  STACK_CHECK(isolate, MaybeHandle<String>());
  Factory* factory = isolate->factory();
  Handle<String> target_name = factory->empty_string();
  DirectHandle<JSReceiver> target(function->wrapped_target_function(), isolate);
  if (IsJSBoundFunction(*target)) {
    return JSBoundFunction::GetName(
        isolate, direct_handle(
                     Cast<JSBoundFunction>(function->wrapped_target_function()),
                     isolate));
  } else if (IsJSFunction(*target)) {
    return JSFunction::GetName(
        isolate,
        direct_handle(Cast<JSFunction>(function->wrapped_target_function()),
                      isolate));
  }
  // This will omit the proper target name for bound JSProxies.
  return target_name;
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSBoundFunction::GetName(), v8::internal::JSFunction::GetName(), and STACK_CHECK.
Referenced by v8::internal::JSBoundFunction::GetName().
ToString()
DirectHandle< String > v8::internal::JSWrappedFunction::ToString (Isolate * isolate, DirectHandle< JSWrappedFunction > function) [static]
Definition at line 553 of file js-function.cc.
                                                                {
  return isolate->factory()->function_native_code_string();
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::Object::NoSideEffectsToMaybeString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-function.h
/mnt/V8SourceCode/src/objects/js-function.cc