v8::Promise Class Reference
An instance of the built-in Promise constructor (ES6 draft).
#include <v8-promise.h>
Classes
class Resolver
Public Types
enum PromiseState { kPending
, kFulfilled
, kRejected
 }
State of the promise.
Public Member Functions
V8_WARN_UNUSED_RESULT MaybeLocal< Promise > Catch (Local< Context > context, Local< Function > handler)
Register a resolution/rejection handler with a promise.
V8_WARN_UNUSED_RESULT MaybeLocal< Promise > Then (Local< Context > context, Local< Function > handler)
V8_WARN_UNUSED_RESULT MaybeLocal< Promise > Then (Local< Context > context, Local< Function > on_fulfilled, Local< Function > on_rejected)
bool HasHandler () const
Returns true if the promise has at least one derived promise, and therefore resolve/reject handlers (including default handler).
Local< Value > Result ()
Returns the content of the [[PromiseResult]] field.
PromiseState State ()
Returns the value of the [[PromiseState]] field.
void MarkAsHandled ()
Marks this promise as handled to avoid reporting unhandled rejections.
void MarkAsSilent ()
Marks this promise as silent to prevent pausing the debugger when the promise is rejected.
Static Public Member Functions
static Promise * Cast (Value *value)
Static Public Attributes
static constexpr int kEmbedderFieldCount = V8_PROMISE_INTERNAL_FIELD_COUNT
Private Member Functions
Promise ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of the built-in Promise constructor (ES6 draft).
Definition at line 24 of file v8-promise.h.
Member Enumeration Documentation
PromiseState
enum v8::Promise::PromiseState
State of the promise.
Each value corresponds to one of the possible values of the [[PromiseState]] field.
Enumerator
kPending
kFulfilled
kRejected
Definition at line 30 of file v8-promise.h.
{ kPending, kFulfilled, kRejected };
Constructor & Destructor Documentation
Promise()
v8::Promise::Promise () [private]
Member Function Documentation
Cast()
static Promise* v8::Promise::Cast (Value * value) [inline], [static]
Definition at line 111 of file v8-promise.h.
                                               {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<Promise*>(value);
  }
References v8::internal::value.
Catch()
MaybeLocal< Promise > v8::Promise::Catch (Local< Context > context, Local< Function > handler)
Register a resolution/rejection handler with a promise.
The handler is given the respective resolution/rejection value as an argument. If the promise is already resolved/rejected, the handler is invoked at the end of turn.
Definition at line 8665 of file api.cc.
                                                            {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Promise_Catch};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> args[] = {i_isolate->factory()->undefined_value(),
                                       Utils::OpenDirectHandle(*handler)};
  // Do not call the built-in Promise.prototype.catch!
  // v8::Promise should not call out to a monkeypatched Promise.prototype.then
  // as the implementation of Promise.prototype.catch does.
  return api_scope.EscapeMaybe(
      MaybeLocal<Promise>::Cast(Utils::ToMaybeLocal(i::Execution::CallBuiltin(
          i_isolate, i_isolate->promise_then(), self, base::VectorOf(args)))));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::Isolate::factory(), v8::Utils::OpenDirectHandle(), v8::Utils::ToMaybeLocal(), and v8::base::VectorOf().
CheckCast()
void v8::Promise::CheckCast (Value * obj) [static], [private]
Definition at line 3977 of file api.cc.
                                     {
  Utils::ApiCheck(that->IsPromise(), "v8::Promise::Cast",
                  "Value is not a Promise");
}
References v8::Utils::ApiCheck(), and v8::Value::IsPromise().
HasHandler()
bool v8::Promise::HasHandler () const
Returns true if the promise has at least one derived promise, and therefore resolve/reject handlers (including default handler).
Definition at line 8704 of file api.cc.
                               {
  i::Tagged<i::JSReceiver> promise = *Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_Promise_HasRejectHandler);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  if (!IsJSPromise(promise)) return false;
  return i::Cast<i::JSPromise>(promise)->has_handler();
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
MarkAsHandled()
void v8::Promise::MarkAsHandled ()
Marks this promise as handled to avoid reporting unhandled rejections.
Definition at line 8732 of file api.cc.
                            {
  Utils::OpenDirectHandle(this)->set_has_handler(true);
}
References v8::Utils::OpenDirectHandle().
MarkAsSilent()
void v8::Promise::MarkAsSilent ()
Marks this promise as silent to prevent pausing the debugger when the promise is rejected.
Definition at line 8736 of file api.cc.
                           {
  Utils::OpenDirectHandle(this)->set_is_silent(true);
}
References v8::Utils::OpenDirectHandle().
Result()
Local< Value > v8::Promise::Result ()
Returns the content of the [[PromiseResult]] field.
The Promise must not be pending.
Definition at line 8714 of file api.cc.
                             {
  auto promise = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Promise_Result);
  auto js_promise = i::Cast<i::JSPromise>(promise);
  Utils::ApiCheck(js_promise->status() != kPending, "v8_Promise_Result",
                  "Promise is still pending");
  return Utils::ToLocal(i::direct_handle(js_promise->result(), i_isolate));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
State()
Promise::PromiseState v8::Promise::State ()
Returns the value of the [[PromiseState]] field.
Definition at line 8724 of file api.cc.
                                   {
  auto promise = Utils::OpenDirectHandle(this);
  ApiRuntimeCallStatsScope rcs_scope(i::Isolate::Current(),
                                     RCCId::kAPI_Promise_Status);
  auto js_promise = i::Cast<i::JSPromise>(promise);
  return static_cast<PromiseState>(js_promise->status());
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::getProperties().
Then() [1/2]
MaybeLocal< Promise > v8::Promise::Then (Local< Context > context, Local< Function > handler)
Definition at line 8680 of file api.cc.
                                                           {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Promise_Then};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*handler)};
  return api_scope.EscapeMaybe(
      MaybeLocal<Promise>::Cast(Utils::ToMaybeLocal(i::Execution::CallBuiltin(
          i_isolate, i_isolate->promise_then(), self, base::VectorOf(args)))));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::Utils::OpenDirectHandle(), v8::Utils::ToMaybeLocal(), and v8::base::VectorOf().
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add().
Then() [2/2]
MaybeLocal< Promise > v8::Promise::Then (Local< Context > context, Local< Function > on_fulfilled, Local< Function > on_rejected)
Definition at line 8691 of file api.cc.
                                                               {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Promise_Then};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*on_fulfilled),
                                       Utils::OpenDirectHandle(*on_rejected)};
  return api_scope.EscapeMaybe(
      MaybeLocal<Promise>::Cast(Utils::ToMaybeLocal(i::Execution::CallBuiltin(
          i_isolate, i_isolate->promise_then(), self, base::VectorOf(args)))));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::Utils::OpenDirectHandle(), v8::Utils::ToMaybeLocal(), and v8::base::VectorOf().
Member Data Documentation
kEmbedderFieldCount
constexpr int v8::Promise::kEmbedderFieldCount = V8_PROMISE_INTERNAL_FIELD_COUNT [static], [constexpr]
Definition at line 118 of file v8-promise.h.
Referenced by v8::internal::Factory::NewJSPromiseWithoutHook().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-promise.h
/mnt/V8SourceCode/src/api/api.cc