v8::internal::maglev::CheckMapsWithMigrationAndDeopt Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckMapsWithMigrationAndDeopt (uint64_t bitfield, const compiler::ZoneRefSet< Map > &maps, CheckType check_type)
CheckMapsWithMigrationAndDeopt (uint64_t bitfield, base::Vector< const compiler::MapRef > maps, CheckType check_type, Zone *zone)
const compiler::ZoneRefSet< Map > & maps () const
CheckType check_type () const
Input & receiver_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kReceiverIndex = 0
Private Types
using Base = FixedInputNodeT< 1, CheckMapsWithMigrationAndDeopt >
using CheckTypeBitField = NextBitField< CheckType, 1 >
Private Attributes
const compiler::ZoneRefSet< Map > maps_
Additional Inherited Members
Detailed Description
Definition at line 6825 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckMapsWithMigrationAndDeopt::Base = FixedInputNodeT<1, CheckMapsWithMigrationAndDeopt> [private]
Definition at line 6827 of file maglev-ir.h.
CheckTypeBitField
using v8::internal::maglev::CheckMapsWithMigrationAndDeopt::CheckTypeBitField = NextBitField<CheckType, 1> [private]
Definition at line 6862 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckMapsWithMigrationAndDeopt() [1/2]
v8::internal::maglev::CheckMapsWithMigrationAndDeopt::CheckMapsWithMigrationAndDeopt (uint64_t bitfield, const compiler::ZoneRefSet< Map > & maps, CheckType check_type) [inline], [explicit]
Definition at line 6830 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)), maps_(maps) {}
CheckMapsWithMigrationAndDeopt() [2/2]
v8::internal::maglev::CheckMapsWithMigrationAndDeopt::CheckMapsWithMigrationAndDeopt (uint64_t bitfield, base::Vector< const compiler::MapRef > maps, CheckType check_type, Zone * zone) [inline], [explicit]
Definition at line 6834 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)),
        maps_(maps.begin(), maps.end(), zone) {}
Member Function Documentation
check_type()
CheckType v8::internal::maglev::CheckMapsWithMigrationAndDeopt::check_type () const [inline]
Definition at line 6849 of file maglev-ir.h.
{ return CheckTypeBitField::decode(bitfield()); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CheckMapsWithMigrationAndDeopt::GenerateCode (MaglevAssembler * , const ProcessingState &)
maps()
const compiler::ZoneRefSet<Map>& v8::internal::maglev::CheckMapsWithMigrationAndDeopt::maps () const [inline]
Definition at line 6848 of file maglev-ir.h.
{ return maps_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::CheckMapsWithMigrationAndDeopt::MaxCallStackArgs () const
options()
auto v8::internal::maglev::CheckMapsWithMigrationAndDeopt::options () const [inline]
Definition at line 6859 of file maglev-ir.h.
{ return std::tuple{maps_, check_type()}; }
PrintParams()
void v8::internal::maglev::CheckMapsWithMigrationAndDeopt::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8059 of file maglev-ir.cc.
                                                               {
  os << "(";
  bool first = true;
  for (compiler::MapRef map : maps()) {
    if (first) {
      first = false;
    } else {
      os << ", ";
    }
    os << *map.object();
  }
  os << ")";
}
References maps().
receiver_input()
Input& v8::internal::maglev::CheckMapsWithMigrationAndDeopt::receiver_input () [inline]
Definition at line 6852 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::CheckMapsWithMigrationAndDeopt::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckMapsWithMigrationAndDeopt::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 6846 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckMapsWithMigrationAndDeopt::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::EagerDeopt() | OpProperties::DeferredCall() |
      OpProperties::CanAllocate() | OpProperties::CanWrite() |
      OpProperties::CanRead()
Definition at line 6840 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CheckMapsWithMigrationAndDeopt::kReceiverIndex = 0 [static], [constexpr]
Definition at line 6851 of file maglev-ir.h.
maps_
const compiler::ZoneRefSet<Map> v8::internal::maglev::CheckMapsWithMigrationAndDeopt::maps_ [private]
Definition at line 6863 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc