v8::internal::WasmExportedFunction Class Reference
#include <wasm-objects.h>
Public Member Functions
OBJECT_CONSTRUCTORS (WasmExportedFunction, JSFunction)
Static Public Member Functions
static V8_EXPORT_PRIVATE bool IsWasmExportedFunction (Tagged< Object > object)
static V8_EXPORT_PRIVATE DirectHandle< WasmExportedFunction > New (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > instance_data, DirectHandle< WasmFuncRef > func_ref, DirectHandle< WasmInternalFunction > internal_function, int arity, DirectHandle< Code > export_wrapper)
static void MarkAsReceiverIsFirstParam (Isolate *isolate, DirectHandle< WasmExportedFunction > exported_function)
static DirectHandle< Code > GetWrapper (Isolate *isolate, const wasm::CanonicalSig *sig, wasm::CanonicalTypeIndex sig_id, bool receiver_is_first_param, const wasm::WasmModule *module)
static std::unique_ptr< char[]> GetDebugName (const wasm::CanonicalSig *sig)
Additional Inherited Members
Detailed Description
Definition at line 999 of file wasm-objects.h.
Member Function Documentation
GetDebugName()
std::unique_ptr< char[]> v8::internal::WasmExportedFunction::GetDebugName (const wasm::CanonicalSig * sig) [static]
Definition at line 3066 of file wasm-objects.cc.
                                 {
  constexpr const char kPrefix[] = "js-to-wasm:";
  // prefix + parameters + delimiter + returns + zero byte
  size_t len = strlen(kPrefix) + sig->all().size() + 2;
  auto buffer = base::OwnedVector<char>::New(len);
  memcpy(buffer.begin(), kPrefix, strlen(kPrefix));
  PrintSignature(buffer.as_vector() + strlen(kPrefix), sig);
  return buffer.ReleaseData();
}
References v8::base::OwnedVector< T >::New(), v8::internal::torque::PrintSignature(), and v8::internal::sig.
Referenced by v8::internal::SharedFunctionInfo::DebugNameCStr(), and v8::internal::compiler::NewJSToWasmCompilationJob().
GetWrapper()
DirectHandle< Code > v8::internal::WasmExportedFunction::GetWrapper (Isolate * isolate, const wasm::CanonicalSig * sig, wasm::CanonicalTypeIndex sig_id, bool receiver_is_first_param, const wasm::WasmModule * module) [static]
Definition at line 2095 of file wasm-objects.cc.
                              {
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    return isolate->builtins()->code_handle(
        Builtin::kGenericJSToWasmInterpreterWrapper);
  }
#endif // V8_ENABLE_DRUMBRAKE
  Tagged<CodeWrapper> entry = wasm::WasmExportWrapperCache::Get(
      isolate, sig_id, receiver_is_first_param);
  if (!entry.is_null()) {
    return direct_handle(entry->code(isolate), isolate);
  }
  if (wasm::CanUseGenericJsToWasmWrapper(module, sig)) {
    if (v8_flags.stress_wasm_stack_switching) {
      return isolate->builtins()->code_handle(Builtin::kWasmStressSwitch);
    }
    return isolate->builtins()->code_handle(Builtin::kJSToWasmWrapper);
  }
  // Otherwise compile a wrapper.
  DirectHandle<Code> compiled =
      wasm::JSToWasmWrapperCompilationUnit::CompileJSToWasmWrapper(
          isolate, sig, sig_id, receiver_is_first_param);
  // This should have added an entry in the per-isolate cache.
  DCHECK_EQ(compiled->wrapper(), wasm::WasmExportWrapperCache::Get(
                                     isolate, sig_id, receiver_is_first_param));
  return compiled;
}
References v8::internal::Isolate::builtins(), v8::internal::wasm::CanUseGenericJsToWasmWrapper(), v8::internal::Builtins::code_handle(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::CompileJSToWasmWrapper(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::wasm::WasmExportWrapperCache::Get(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::sig, and v8::internal::v8_flags.
Referenced by v8::internal::WasmInternalFunction::GetOrCreateExternal(), and MarkAsReceiverIsFirstParam().
IsWasmExportedFunction()
bool v8::internal::WasmExportedFunction::IsWasmExportedFunction (Tagged< Object > object) [static]
Definition at line 2899 of file wasm-objects.cc.
                                                                       {
  if (!IsJSFunction(object)) return false;
  Tagged<JSFunction> js_function = Cast<JSFunction>(object);
  Tagged<Code> code = js_function->code(GetCurrentIsolateForSandbox());
  if (CodeKind::JS_TO_WASM_FUNCTION != code->kind() &&
#if V8_ENABLE_DRUMBRAKE
      code->builtin_id() != Builtin::kGenericJSToWasmInterpreterWrapper &&
#endif // V8_ENABLE_DRUMBRAKE
      code->builtin_id() != Builtin::kJSToWasmWrapper &&
      code->builtin_id() != Builtin::kWasmPromising &&
      code->builtin_id() != Builtin::kWasmStressSwitch) {
    return false;
  }
  DCHECK(js_function->shared()->HasWasmExportedFunctionData(
      GetCurrentIsolateForSandbox()));
  return true;
}
References code, v8::internal::DCHECK(), and v8::internal::GetCurrentIsolateForSandbox().
Referenced by v8::internal::CastTraits< WasmExportedFunction >::AllowFrom(), v8::internal::WasmTableObject::GetFunctionTableEntry(), v8::internal::WasmExternalFunction::IsWasmExternalFunction(), v8::internal::wasm::JSToWasmObject(), v8::internal::RUNTIME_FUNCTION(), v8::internal::WasmTableObject::SetFunctionTableEntry(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyPromising(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblySuspendingImpl().
MarkAsReceiverIsFirstParam()
void v8::internal::WasmExportedFunction::MarkAsReceiverIsFirstParam (Isolate * isolate, DirectHandle< WasmExportedFunction > exported_function) [static]
Definition at line 2127 of file wasm-objects.cc.
                                                                            {
  Tagged<WasmExportedFunctionData> data =
      exported_function->shared()->wasm_exported_function_data();
  if (data->receiver_is_first_param() != 0) return;
  data->set_receiver_is_first_param(1);
  DirectHandle<WasmExportedFunctionData> data_handle(data, isolate);
  // Reset the wrapper code. If that's a compiled wrapper, it baked in the
  // bit we just flipped.
  DirectHandle<Code> wrapper =
      GetWrapper(isolate, data->sig(), data->sig_index(), true,
                 data->instance_data()->module());
  data = {}; // Might be stale due to GC.
  data_handle->set_wrapper_code(*wrapper);
  exported_function->UpdateCode(isolate, *wrapper);
}
References GetWrapper().
Referenced by v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl().
New()
DirectHandle< WasmExportedFunction > v8::internal::WasmExportedFunction::New (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > instance_data, DirectHandle< WasmFuncRef > func_ref, DirectHandle< WasmInternalFunction > internal_function, int arity, DirectHandle< Code > export_wrapper) [static]
Definition at line 2957 of file wasm-objects.cc.
                                       {
  DCHECK(CodeKind::JS_TO_WASM_FUNCTION == export_wrapper->kind() ||
         (export_wrapper->is_builtin() &&
          (export_wrapper->builtin_id() == Builtin::kJSToWasmWrapper ||
#if V8_ENABLE_DRUMBRAKE
           export_wrapper->builtin_id() ==
               Builtin::kGenericJSToWasmInterpreterWrapper ||
#endif // V8_ENABLE_DRUMBRAKE
           export_wrapper->builtin_id() == Builtin::kWasmPromising ||
           export_wrapper->builtin_id() == Builtin::kWasmStressSwitch)));
  int func_index = internal_function->function_index();
  Factory* factory = isolate->factory();
  DirectHandle<Map> rtt;
  wasm::Promise promise =
      export_wrapper->builtin_id() == Builtin::kWasmPromising
          ? wasm::kPromise
          : wasm::kNoPromise;
  const wasm::WasmModule* module = instance_data->module();
  wasm::CanonicalTypeIndex sig_id =
      module->canonical_sig_id(module->functions[func_index].sig_index);
  const wasm::CanonicalSig* sig =
      wasm::GetTypeCanonicalizer()->LookupFunctionSignature(sig_id);
  DirectHandle<WasmExportedFunctionData> function_data =
      factory->NewWasmExportedFunctionData(
          export_wrapper, instance_data, func_ref, internal_function, sig,
          sig_id, v8_flags.wasm_wrapper_tiering_budget, promise);
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    const wasm::FunctionSig* function_sig =
        reinterpret_cast<const wasm::FunctionSig*>(sig);
    uint32_t aligned_size =
        wasm::WasmBytecode::JSToWasmWrapperPackedArraySize(function_sig);
    bool hasRefArgs = wasm::WasmBytecode::RefArgsCount(function_sig) > 0;
    bool hasRefRets = wasm::WasmBytecode::RefRetsCount(function_sig) > 0;
    function_data->set_packed_args_size(
        wasm::WasmInterpreterRuntime::PackedArgsSizeField::encode(
            aligned_size) |
        wasm::WasmInterpreterRuntime::HasRefArgsField::encode(hasRefArgs) |
        wasm::WasmInterpreterRuntime::HasRefRetsField::encode(hasRefRets));
  }
#endif // V8_ENABLE_DRUMBRAKE
  MaybeDirectHandle<String> maybe_name;
  bool is_asm_js_module = is_asmjs_module(module);
  if (is_asm_js_module) {
    // We can use the function name only for asm.js. For WebAssembly, the
    // function name is specified as the function_index.toString().
    maybe_name = WasmModuleObject::GetFunctionNameOrNull(
        isolate, direct_handle(instance_data->module_object(), isolate),
        func_index);
  }
  DirectHandle<String> name;
  if (!maybe_name.ToHandle(&name)) {
    base::EmbeddedVector<char, 16> buffer;
    int length = SNPrintF(buffer, "%d", func_index);
    name = factory
               ->NewStringFromOneByte(
                   base::Vector<uint8_t>::cast(buffer.SubVector(0, length)))
               .ToHandleChecked();
  }
  DirectHandle<NativeContext> context(isolate->native_context());
  DirectHandle<SharedFunctionInfo> shared =
      factory->NewSharedFunctionInfoForWasmExportedFunction(name, function_data,
                                                            arity, kAdapt);
  DirectHandle<Map> function_map;
  switch (module->origin) {
    case wasm::kWasmOrigin:
      function_map = isolate->wasm_exported_function_map();
      break;
    case wasm::kAsmJsSloppyOrigin:
      function_map = isolate->sloppy_function_map();
      break;
    case wasm::kAsmJsStrictOrigin:
      function_map = isolate->strict_function_map();
      shared->set_language_mode(LanguageMode::kStrict);
      break;
  }
  DirectHandle<JSFunction> js_function =
      Factory::JSFunctionBuilder{isolate, shared, context}
          .set_map(function_map)
          .Build();
  // According to the spec, exported functions should not have a [[Construct]]
  // method. This does not apply to functions exported from asm.js however.
  DCHECK_EQ(is_asm_js_module, IsConstructor(*js_function));
  if (instance_data->has_instance_object()) {
    shared->set_script(instance_data->module_object()->script(), kReleaseStore);
  } else {
    shared->set_script(*isolate->factory()->undefined_value(), kReleaseStore);
  }
  function_data->internal()->set_external(*js_function);
  return Cast<WasmExportedFunction>(js_function);
}
References v8::internal::wasm::WasmModule::canonical_sig_id(), v8::internal::JSFunction::context(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Isolate::factory(), v8::internal::libvtune::function_map, v8::internal::wasm::WasmModule::functions, v8::internal::WasmModuleObject::GetFunctionNameOrNull(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::instance_data, v8::internal::wasm::is_asmjs_module(), v8::internal::wasm::WasmBytecode::JSToWasmWrapperPackedArraySize(), v8::internal::kAdapt, v8::internal::wasm::kAsmJsSloppyOrigin, v8::internal::wasm::kAsmJsStrictOrigin, v8::internal::wasm::kNoPromise, v8::internal::wasm::kPromise, v8::kReleaseStore, v8::internal::kStrict, v8::internal::wasm::kWasmOrigin, v8::internal::JSFunction::length(), v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), v8::internal::wasm::WasmModule::origin, v8::internal::wasm::WasmBytecode::RefArgsCount(), v8::internal::wasm::WasmBytecode::RefRetsCount(), v8::internal::sig, v8::base::SNPrintF(), v8::base::Vector< T >::SubVector(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::v8_flags.
Referenced by v8::internal::WasmInternalFunction::GetOrCreateExternal(), and v8::anonymous_namespace{wasm-js.cc}::NewPromisingWasmExportedFunction().
OBJECT_CONSTRUCTORS()
v8::internal::WasmExportedFunction::OBJECT_CONSTRUCTORS (WasmExportedFunction , JSFunction)
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc