v8::internal::ConservativePinningScope Class Reference
#include <heap.h>
Public Member Functions
ConservativePinningScope (Heap *heap)
~ConservativePinningScope ()
Private Member Functions
V8_STACK_ALLOCATED ()
Private Attributes
Heap *const heap_
Detailed Description
Definition at line 195 of file heap.h.
Constructor & Destructor Documentation
ConservativePinningScope()
v8::internal::ConservativePinningScope::ConservativePinningScope (Heap * heap) [explicit]
Definition at line 7712 of file heap.cc.
                                                             : heap_(heap) {
  DCHECK(::heap::base::Stack::IsOnCurrentStack(this));
  DCHECK(!heap_->selective_stack_scan_start_address_.has_value());
  // `frame_address` should be higher than `this`, but we observed that this
  // may not hold in some cases (e.g. due to missing inlining or unexpected
  // frame layouts). In such cases, we scan the stack either from the last
  // c_entry_fp or the whole stack.
  const Address c_entry_fp = *heap_->isolate()->c_entry_fp_address();
  const void* frame_address =
      (c_entry_fp == kNullAddress)
          ? static_cast<void*>(v8::base::Stack::GetStackStart())
          : reinterpret_cast<const void*>(c_entry_fp);
  // The stack segment covered by this scope should include the scope itself.
  DCHECK_NOT_NULL(frame_address);
  DCHECK_LE(this, frame_address);
  DCHECK(::heap::base::Stack::IsOnCurrentStack(frame_address));
  heap_->selective_stack_scan_start_address_ = frame_address;
}
References v8::internal::Isolate::c_entry_fp_address(), v8::internal::DCHECK(), DCHECK_LE, DCHECK_NOT_NULL, v8::base::Stack::GetStackStart(), heap_, v8::internal::Heap::isolate(), v8::internal::kNullAddress, and v8::internal::Heap::selective_stack_scan_start_address_.
 ConservativePinningScope()
v8::internal::ConservativePinningScope::~ConservativePinningScope ()
Definition at line 7730 of file heap.cc.
                                                    {
  DCHECK(heap_->selective_stack_scan_start_address_.has_value());
  heap_->selective_stack_scan_start_address_.reset();
}
References v8::internal::DCHECK(), heap_, and v8::internal::Heap::selective_stack_scan_start_address_.
Member Function Documentation
V8_STACK_ALLOCATED()
v8::internal::ConservativePinningScope::V8_STACK_ALLOCATED () [private]
Member Data Documentation
heap_
Heap* const v8::internal::ConservativePinningScope::heap_ [private]
Definition at line 206 of file heap.h.
Referenced by ConservativePinningScope(), and ~ConservativePinningScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap.h
/mnt/V8SourceCode/src/heap/heap.cc