v8::internal::StackTraceFailureMessage Class Reference
#include <isolate.h>
Public Types
enum StackTraceMode { kIncludeStackTrace
, kDontIncludeStackTrace
 }
Public Member Functions
StackTraceFailureMessage (Isolate *isolate, StackTraceMode mode, const Address *ptrs, size_t ptrs_count)
StackTraceFailureMessage (Isolate *isolate, StackTraceMode mode, std::initializer_list< Address > ptrs)
StackTraceFailureMessage (Isolate *isolate, StackTraceMode mode, std::initializer_list< void * > ptrs)
V8_NOINLINE void Print () volatile
Public Attributes
uintptr_t start_marker_ = kStartMarker
Isolate * isolate_
Address ptrs_ [64] = {}
uintptr_t middle_marker_ = kMiddleMarker
Address code_objects_ [4] = {}
char js_stack_trace_ [kStacktraceBufferSize] = {}
uintptr_t end_marker_ = kEndMarker
Static Public Attributes
static const uintptr_t kStartMarker = 0xdecade30
static const uintptr_t kMiddleMarker = 0xdecade33
static const uintptr_t kEndMarker = 0xdecade36
static const int kStacktraceBufferSize = 32 * KB
Detailed Description
Definition at line 3119 of file isolate.h.
Member Enumeration Documentation
StackTraceMode
enum v8::internal::StackTraceFailureMessage::StackTraceMode
Enumerator
kIncludeStackTrace
kDontIncludeStackTrace
Definition at line 3121 of file isolate.h.
{ kIncludeStackTrace, kDontIncludeStackTrace };
Constructor & Destructor Documentation
StackTraceFailureMessage() [1/3]
v8::internal::StackTraceFailureMessage::StackTraceFailureMessage (Isolate * isolate, StackTraceFailureMessage::StackTraceMode mode, const Address * ptrs, size_t ptrs_count) [explicit]
Definition at line 748 of file isolate.cc.
    : isolate_(isolate) {
  size_t ptrs_size = std::min(arraysize(ptrs_), ptrs_count);
  std::copy(ptrs, ptrs + ptrs_size, &ptrs_[0]);
  if (mode == kIncludeStackTrace) {
    // Write a stracktrace into the {js_stack_trace_} buffer.
    const size_t buffer_length = arraysize(js_stack_trace_);
    FixedStringAllocator fixed(&js_stack_trace_[0], buffer_length - 1);
    StringStream accumulator(&fixed, StringStream::kPrintObjectConcise);
    isolate_->PrintStack(&accumulator, Isolate::kPrintStackVerbose);
    // Keeping a reference to the last code objects to increase likelihood that
    // they get included in the minidump.
    const size_t code_objects_length = arraysize(code_objects_);
    size_t i = 0;
    StackFrameIterator it(isolate_);
    for (; !it.done() && i < code_objects_length; it.Advance()) {
      code_objects_[i++] = it.frame()->unchecked_code().ptr();
    }
  }
}
References v8::internal::StackFrameIterator::Advance(), arraysize, code_objects_, v8::internal::StackFrameIteratorBase::done(), v8::internal::StackFrameIterator::frame(), isolate_, js_stack_trace_, kIncludeStackTrace, v8::internal::StringStream::kPrintObjectConcise, v8::internal::Isolate::kPrintStackVerbose, mode(), v8::internal::Isolate::PrintStack(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), ptrs_, and v8::internal::StackFrame::unchecked_code().
StackTraceFailureMessage() [2/3]
v8::internal::StackTraceFailureMessage::StackTraceFailureMessage (Isolate * isolate, StackTraceMode mode, std::initializer_list< Address > ptrs) [inline], [explicit]
Definition at line 3126 of file isolate.h.
      : StackTraceFailureMessage(isolate, mode, ptrs.begin(), ptrs.size()) {}
StackTraceFailureMessage() [3/3]
v8::internal::StackTraceFailureMessage::StackTraceFailureMessage (Isolate * isolate, StackTraceMode mode, std::initializer_list< void * > ptrs) [inline], [explicit]
Definition at line 3130 of file isolate.h.
      : StackTraceFailureMessage(isolate, mode,
                                 reinterpret_cast<const Address*>(ptrs.begin()),
                                 ptrs.size()) {}
Member Function Documentation
Print()
void v8::internal::StackTraceFailureMessage::Print () volatile
Definition at line 735 of file isolate.cc.
                                              {
  // Print the details of this failure message object, including its own address
  // to force stack allocation.
  static_assert(arraysize(ptrs_) >= 6);
  base::OS::PrintError(
      "Stacktrace:\n ptr0=%p\n ptr1=%p\n ptr2=%p\n ptr3=%p\n "
      "ptr4=%p\n ptr5=%p\n failure_message_object=%p\n%s",
      reinterpret_cast<void*>(ptrs_[0]), reinterpret_cast<void*>(ptrs_[1]),
      reinterpret_cast<void*>(ptrs_[2]), reinterpret_cast<void*>(ptrs_[3]),
      reinterpret_cast<void*>(ptrs_[4]), reinterpret_cast<void*>(ptrs_[5]),
      this, &js_stack_trace_[0]);
}
References arraysize, js_stack_trace_, and ptrs_.
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::Isolate::PushParamsAndContinue(), v8::internal::Isolate::PushParamsAndDie(), v8::internal::Isolate::PushStackTraceAndContinue(), and v8::internal::Isolate::PushStackTraceAndDie().
Member Data Documentation
code_objects_
Address v8::internal::StackTraceFailureMessage::code_objects_[4] = {}
Definition at line 3147 of file isolate.h.
Referenced by StackTraceFailureMessage().
end_marker_
uintptr_t v8::internal::StackTraceFailureMessage::end_marker_ = kEndMarker
Definition at line 3149 of file isolate.h.
isolate_
Isolate* v8::internal::StackTraceFailureMessage::isolate_
Definition at line 3144 of file isolate.h.
Referenced by StackTraceFailureMessage().
js_stack_trace_
char v8::internal::StackTraceFailureMessage::js_stack_trace_[kStacktraceBufferSize] = {}
Definition at line 3148 of file isolate.h.
Referenced by Print(), and StackTraceFailureMessage().
kEndMarker
const uintptr_t v8::internal::StackTraceFailureMessage::kEndMarker = 0xdecade36 [static]
Definition at line 3140 of file isolate.h.
kMiddleMarker
const uintptr_t v8::internal::StackTraceFailureMessage::kMiddleMarker = 0xdecade33 [static]
Definition at line 3139 of file isolate.h.
kStacktraceBufferSize
const int v8::internal::StackTraceFailureMessage::kStacktraceBufferSize = 32 * KB [static]
Definition at line 3141 of file isolate.h.
kStartMarker
const uintptr_t v8::internal::StackTraceFailureMessage::kStartMarker = 0xdecade30 [static]
Definition at line 3138 of file isolate.h.
middle_marker_
uintptr_t v8::internal::StackTraceFailureMessage::middle_marker_ = kMiddleMarker
Definition at line 3146 of file isolate.h.
ptrs_
Address v8::internal::StackTraceFailureMessage::ptrs_[64] = {}
Definition at line 3145 of file isolate.h.
Referenced by Print(), and StackTraceFailureMessage().
start_marker_
uintptr_t v8::internal::StackTraceFailureMessage::start_marker_ = kStartMarker
Definition at line 3143 of file isolate.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/isolate.h
/mnt/V8SourceCode/src/execution/isolate.cc