v8::internal::ParkedMutexGuard Class Reference
#include <parked-scope.h>
Public Member Functions
ParkedMutexGuard (LocalIsolate *local_isolate, base::Mutex *mutex)
ParkedMutexGuard (LocalHeap *local_heap, base::Mutex *mutex)
ParkedMutexGuard (const ParkedMutexGuard &)=delete
ParkedMutexGuard & operator= (const ParkedMutexGuard &)=delete
~ParkedMutexGuard ()
Private Attributes
base::Mutex * mutex_
Detailed Description
Definition at line 74 of file parked-scope.h.
Constructor & Destructor Documentation
ParkedMutexGuard() [1/3]
v8::internal::ParkedMutexGuard::ParkedMutexGuard (LocalIsolate * local_isolate, base::Mutex * mutex) [inline], [explicit]
Definition at line 20 of file parked-scope-inl.h.
    : ParkedMutexGuard(local_isolate->heap(), mutex) {}
ParkedMutexGuard() [2/3]
v8::internal::ParkedMutexGuard::ParkedMutexGuard (LocalHeap * local_heap, base::Mutex * mutex) [inline], [explicit]
Definition at line 24 of file parked-scope-inl.h.
    : mutex_(mutex) {
  DCHECK(AllowGarbageCollection::IsAllowed());
  if (!mutex_->TryLock()) {
    local_heap->ExecuteWhileParked([this]() { mutex_->Lock(); });
  }
}
References v8::internal::DCHECK(), v8::internal::LocalHeap::ExecuteWhileParked(), v8::base::Mutex::Lock(), mutex_, and v8::base::Mutex::TryLock().
ParkedMutexGuard() [3/3]
v8::internal::ParkedMutexGuard::ParkedMutexGuard (const ParkedMutexGuard &) [delete]
 ParkedMutexGuard()
v8::internal::ParkedMutexGuard::~ParkedMutexGuard () [inline]
Definition at line 84 of file parked-scope.h.
{ mutex_->Unlock(); }
Member Function Documentation
operator=()
ParkedMutexGuard& v8::internal::ParkedMutexGuard::operator= (const ParkedMutexGuard &) [delete]
Member Data Documentation
mutex_
base::Mutex* v8::internal::ParkedMutexGuard::mutex_ [private]
Definition at line 87 of file parked-scope.h.
Referenced by ParkedMutexGuard().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/parked-scope.h
/mnt/V8SourceCode/src/heap/parked-scope-inl.h