v8::internal::compiler::EscapeAnalysisReducer Class Reference
#include <escape-analysis-reducer.h>
Public Member Functions
EscapeAnalysisReducer (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker, EscapeAnalysisResult analysis_result, Zone *zone)
EscapeAnalysisReducer (const EscapeAnalysisReducer &)=delete
EscapeAnalysisReducer & operator= (const EscapeAnalysisReducer &)=delete
Reduction Reduce (Node *node) override
const char * reducer_name () const override
void Finalize () override
void VerifyReplacement () const
Private Member Functions
void ReduceFrameStateInputs (Node *node)
Node * ReduceDeoptState (Node *node, Node *effect, Deduplicator *deduplicator)
Node * ObjectIdNode (const VirtualObject *vobject)
Reduction ReplaceNode (Node *original, Node *replacement)
JSGraph * jsgraph () const
Isolate * isolate () const
EscapeAnalysisResult analysis_result () const
Zone * zone () const
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker *const broker_
EscapeAnalysisResult analysis_result_
ZoneVector< Node * > object_id_cache_
NodeHashCache node_cache_
ZoneSet< Node * > arguments_elements_
Zone *const zone_
Detailed Description
Definition at line 82 of file escape-analysis-reducer.h.
Constructor & Destructor Documentation
EscapeAnalysisReducer() [1/2]
v8::internal::compiler::EscapeAnalysisReducer::EscapeAnalysisReducer (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker, EscapeAnalysisResult analysis_result, Zone * zone)
Definition at line 17 of file escape-analysis-reducer.cc.
    : AdvancedReducer(editor),
      jsgraph_(jsgraph),
      broker_(broker),
      analysis_result_(analysis_result),
      object_id_cache_(zone),
      node_cache_(jsgraph->graph(), zone),
      arguments_elements_(zone),
      zone_(zone) {}
EscapeAnalysisReducer() [2/2]
v8::internal::compiler::EscapeAnalysisReducer::EscapeAnalysisReducer (const EscapeAnalysisReducer &) [delete]
Member Function Documentation
analysis_result()
EscapeAnalysisResult v8::internal::compiler::EscapeAnalysisReducer::analysis_result () const [inline], [private]
Definition at line 106 of file escape-analysis-reducer.h.
{ return analysis_result_; }
Referenced by Reduce(), ReduceDeoptState(), ReplaceNode(), and VerifyReplacement().
Finalize()
void v8::internal::compiler::EscapeAnalysisReducer::Finalize () [override]
Definition at line 217 of file escape-analysis-reducer.cc.
                                     {
  OperationTyper op_typer(broker_, jsgraph()->graph()->zone());
  for (Node* node : arguments_elements_) {
    const NewArgumentsElementsParameters& params =
        NewArgumentsElementsParametersOf(node->op());
    ArgumentsStateType type = params.arguments_type();
    int mapped_count = type == CreateArgumentsType::kMappedArguments
                           ? params.formal_parameter_count()
                           : 0;
    Node* arguments_length = NodeProperties::GetValueInput(node, 0);
    if (arguments_length->opcode() != IrOpcode::kArgumentsLength) continue;
    Node* arguments_length_state = nullptr;
    for (Edge edge : arguments_length->use_edges()) {
      Node* use = edge.from();
      switch (use->opcode()) {
        case IrOpcode::kObjectState:
        case IrOpcode::kTypedObjectState:
        case IrOpcode::kStateValues:
        case IrOpcode::kTypedStateValues:
          if (!arguments_length_state) {
            arguments_length_state = jsgraph()->graph()->NewNode(
                jsgraph()->common()->ArgumentsLengthState());
            NodeProperties::SetType(arguments_length_state,
                                    Type::OtherInternal());
          }
          edge.UpdateTo(arguments_length_state);
          break;
        default:
          break;
      }
    }
    bool escaping_use = false;
    ZoneVector<Node*> loads(zone());
    for (Edge edge : node->use_edges()) {
      Node* use = edge.from();
      if (!NodeProperties::IsValueEdge(edge)) continue;
      if (use->use_edges().empty()) {
        // A node without uses is dead, so we don't have to care about it.
        continue;
      }
      switch (use->opcode()) {
        case IrOpcode::kStateValues:
        case IrOpcode::kTypedStateValues:
        case IrOpcode::kObjectState:
        case IrOpcode::kTypedObjectState:
          break;
        case IrOpcode::kLoadElement:
          if (mapped_count == 0) {
            loads.push_back(use);
          } else {
            escaping_use = true;
          }
          break;
        case IrOpcode::kLoadField:
          if (FieldAccessOf(use->op()).offset ==
              offsetof(FixedArray, length_)) {
            loads.push_back(use);
          } else {
            escaping_use = true;
          }
          break;
        default:
          // If the arguments elements node node is used by an unhandled node,
          // then we cannot remove this allocation.
          escaping_use = true;
          break;
      }
      if (escaping_use) break;
    }
    if (!escaping_use) {
      Node* arguments_elements_state = jsgraph()->graph()->NewNode(
          jsgraph()->common()->ArgumentsElementsState(type));
      NodeProperties::SetType(arguments_elements_state, Type::OtherInternal());
      ReplaceWithValue(node, arguments_elements_state);
      for (Node* load : loads) {
        switch (load->opcode()) {
          case IrOpcode::kLoadElement: {
            Node* index = NodeProperties::GetValueInput(load, 1);
            Node* formal_parameter_count =
                jsgraph()->ConstantNoHole(params.formal_parameter_count());
            NodeProperties::SetType(
                formal_parameter_count,
                Type::Constant(params.formal_parameter_count(),
                               jsgraph()->graph()->zone()));
            Node* offset_to_first_elem = jsgraph()->ConstantNoHole(
                CommonFrameConstants::kFixedSlotCountAboveFp);
            if (!NodeProperties::IsTyped(offset_to_first_elem)) {
              NodeProperties::SetType(
                  offset_to_first_elem,
                  Type::Constant(CommonFrameConstants::kFixedSlotCountAboveFp,
                                 jsgraph()->graph()->zone()));
            }
            Node* offset = jsgraph()->graph()->NewNode(
                jsgraph()->simplified()->NumberAdd(), index,
                offset_to_first_elem);
            Type offset_type = op_typer.NumberAdd(
                NodeProperties::GetType(index),
                NodeProperties::GetType(offset_to_first_elem));
            NodeProperties::SetType(offset, offset_type);
            if (type == CreateArgumentsType::kRestParameter) {
              // In the case of rest parameters we should skip the formal
              // parameters.
              offset = jsgraph()->graph()->NewNode(
                  jsgraph()->simplified()->NumberAdd(), offset,
                  formal_parameter_count);
              NodeProperties::SetType(
                  offset, op_typer.NumberAdd(
                              offset_type,
                              NodeProperties::GetType(formal_parameter_count)));
            }
            Node* frame = jsgraph()->graph()->NewNode(
                jsgraph()->machine()->LoadFramePointer());
            NodeProperties::SetType(frame, Type::ExternalPointer());
            NodeProperties::ReplaceValueInput(load, frame, 0);
            NodeProperties::ReplaceValueInput(load, offset, 1);
            NodeProperties::ChangeOp(
                load, jsgraph()->simplified()->LoadStackArgument());
            break;
          }
          case IrOpcode::kLoadField: {
            DCHECK_EQ(FieldAccessOf(load->op()).offset,
                      offsetof(FixedArray, length_));
            Node* length = NodeProperties::GetValueInput(node, 0);
            ReplaceWithValue(load, length);
            break;
          }
          default:
            UNREACHABLE();
        }
      }
    }
  }
}
References arguments_elements_, v8::internal::compiler::NewArgumentsElementsParameters::arguments_type(), broker_, v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::Type::Constant(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::NewArgumentsElementsParameters::formal_parameter_count(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::MachineGraph::graph(), graph(), v8::internal::index, v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::NodeProperties::IsValueEdge(), jsgraph(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, v8::internal::kMappedArguments, v8::internal::kRestParameter, v8::internal::length, v8::internal::compiler::NewArgumentsElementsParametersOf(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::FieldAccess::offset, v8::internal::compiler::Node::opcode(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), use(), v8::internal::compiler::Node::use_edges(), and zone().
isolate()
Isolate* v8::internal::compiler::EscapeAnalysisReducer::isolate () const [inline], [private]
Definition at line 105 of file escape-analysis-reducer.h.
{ return jsgraph_->isolate(); }
References v8::internal::Factory::isolate().
jsgraph()
JSGraph* v8::internal::compiler::EscapeAnalysisReducer::jsgraph () const [inline], [private]
Definition at line 104 of file escape-analysis-reducer.h.
{ return jsgraph_; }
Referenced by Finalize(), ObjectIdNode(), ReduceDeoptState(), ReplaceNode(), and VerifyReplacement().
ObjectIdNode()
Node * v8::internal::compiler::EscapeAnalysisReducer::ObjectIdNode (const VirtualObject * vobject) [private]
Definition at line 64 of file escape-analysis-reducer.cc.
                                                                      {
  VirtualObject::Id id = vobject->id();
  if (id >= object_id_cache_.size()) object_id_cache_.resize(id + 1);
  if (!object_id_cache_[id]) {
    Node* node = jsgraph()->graph()->NewNode(jsgraph()->common()->ObjectId(id));
    NodeProperties::SetType(node, Type::Object());
    object_id_cache_[id] = node;
  }
  return object_id_cache_[id];
}
References v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::VirtualObject::id(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Object, object_id_cache_, v8::internal::ZoneVector< T >::resize(), v8::internal::compiler::NodeProperties::SetType(), and v8::internal::ZoneVector< T >::size().
Referenced by ReduceDeoptState().
operator=()
EscapeAnalysisReducer& v8::internal::compiler::EscapeAnalysisReducer::operator= (const EscapeAnalysisReducer &) [delete]
Reduce()
Reduction v8::internal::compiler::EscapeAnalysisReducer::Reduce (Node * node) [override]
Definition at line 75 of file escape-analysis-reducer.cc.
                                                  {
  if (Node* replacement = analysis_result().GetReplacementOf(node)) {
    DCHECK(node->opcode() != IrOpcode::kAllocate &&
           node->opcode() != IrOpcode::kFinishRegion);
    DCHECK_NE(replacement, node);
    return ReplaceNode(node, replacement);
  }
  switch (node->opcode()) {
    case IrOpcode::kAllocate:
    case IrOpcode::kTypeGuard: {
      const VirtualObject* vobject = analysis_result().GetVirtualObject(node);
      if (vobject && !vobject->HasEscaped()) {
        RelaxEffectsAndControls(node);
      }
      return NoChange();
    }
    case IrOpcode::kFinishRegion: {
      Node* effect = NodeProperties::GetEffectInput(node, 0);
      if (effect->opcode() == IrOpcode::kBeginRegion) {
        RelaxEffectsAndControls(effect);
        RelaxEffectsAndControls(node);
      }
      return NoChange();
    }
    case IrOpcode::kNewArgumentsElements:
      arguments_elements_.insert(node);
      return NoChange();
    default: {
      // TODO(sigurds): Change this to GetFrameStateInputCount once
      // it is working. For now we use EffectInputCount > 0 to determine
      // whether a node might have a frame state input.
      if (node->op()->EffectInputCount() > 0) {
        ReduceFrameStateInputs(node);
      }
      return NoChange();
    }
  }
}
References analysis_result(), arguments_elements_, v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::EscapeAnalysisResult::GetVirtualObject(), v8::internal::compiler::VirtualObject::HasEscaped(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), ReduceFrameStateInputs(), and ReplaceNode().
ReduceDeoptState()
Node * v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState (Node * node, Node * effect, Deduplicator * deduplicator) [private]
Definition at line 149 of file escape-analysis-reducer.cc.
                                                                          {
  if (node->opcode() == IrOpcode::kFrameState) {
    NodeHashCache::Constructor new_node(&node_cache_, node);
    // This input order is important to match the DFS traversal used in the
    // instruction selector. Otherwise, the instruction selector might find a
    // duplicate node before the original one.
    for (int input_id : {FrameState::kFrameStateOuterStateInput,
                         FrameState::kFrameStateFunctionInput,
                         FrameState::kFrameStateParametersInput,
                         FrameState::kFrameStateContextInput,
                         FrameState::kFrameStateLocalsInput,
                         FrameState::kFrameStateStackInput}) {
      Node* input = node->InputAt(input_id);
      new_node.ReplaceInput(ReduceDeoptState(input, effect, deduplicator),
                            input_id);
    }
    return new_node.Get();
  } else if (node->opcode() == IrOpcode::kStateValues) {
    NodeHashCache::Constructor new_node(&node_cache_, node);
    for (int i = 0; i < node->op()->ValueInputCount(); ++i) {
      Node* input = NodeProperties::GetValueInput(node, i);
      new_node.ReplaceValueInput(ReduceDeoptState(input, effect, deduplicator),
                                 i);
    }
    return new_node.Get();
  } else if (const VirtualObject* vobject = analysis_result().GetVirtualObject(
                 SkipValueIdentities(node))) {
    if (vobject->HasEscaped()) return node;
    if (deduplicator->SeenBefore(vobject)) {
      return ObjectIdNode(vobject);
    } else {
      std::vector<Node*> inputs;
      for (int offset = 0; offset < vobject->size(); offset += kTaggedSize) {
        Node* field =
            analysis_result().GetVirtualObjectField(vobject, offset, effect);
        CHECK_NOT_NULL(field);
        if (field != jsgraph()->Dead()) {
          inputs.push_back(ReduceDeoptState(field, effect, deduplicator));
        }
      }
      int num_inputs = static_cast<int>(inputs.size());
      NodeHashCache::Constructor new_node(
          &node_cache_,
          jsgraph()->common()->ObjectState(vobject->id(), num_inputs),
          num_inputs, &inputs.front(), NodeProperties::GetType(node));
      return new_node.Get();
    }
  } else {
    return node;
  }
}
References analysis_result(), CHECK_NOT_NULL, v8::internal::compiler::NodeHashCache::Constructor::Get(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::EscapeAnalysisResult::GetVirtualObjectField(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::compiler::FrameState::kFrameStateContextInput, v8::internal::compiler::FrameState::kFrameStateFunctionInput, v8::internal::compiler::FrameState::kFrameStateLocalsInput, v8::internal::compiler::FrameState::kFrameStateOuterStateInput, v8::internal::compiler::FrameState::kFrameStateParametersInput, v8::internal::compiler::FrameState::kFrameStateStackInput, v8::internal::kTaggedSize, node_cache_, ObjectIdNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeHashCache::Constructor::ReplaceInput(), v8::internal::compiler::NodeHashCache::Constructor::ReplaceValueInput(), v8::internal::compiler::Deduplicator::SeenBefore(), and v8::internal::compiler::SkipValueIdentities().
Referenced by ReduceFrameStateInputs().
ReduceFrameStateInputs()
void v8::internal::compiler::EscapeAnalysisReducer::ReduceFrameStateInputs (Node * node) [private]
Definition at line 136 of file escape-analysis-reducer.cc.
                                                             {
  DCHECK_GE(node->op()->EffectInputCount(), 1);
  for (int i = 0; i < node->InputCount(); ++i) {
    Node* input = node->InputAt(i);
    if (input->opcode() == IrOpcode::kFrameState) {
      Deduplicator deduplicator(zone());
      if (Node* ret = ReduceDeoptState(input, node, &deduplicator)) {
        node->ReplaceInput(i, ret);
      }
    }
  }
}
References DCHECK_GE, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), ReduceDeoptState(), v8::internal::compiler::Node::ReplaceInput(), and zone().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::EscapeAnalysisReducer::reducer_name () const [inline], [override]
Definition at line 91 of file escape-analysis-reducer.h.
{ return "EscapeAnalysisReducer"; }
ReplaceNode()
Reduction v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode (Node * original, Node * replacement) [private]
Definition at line 29 of file escape-analysis-reducer.cc.
                                                                {
  const VirtualObject* vobject =
      analysis_result().GetVirtualObject(replacement);
  if (replacement->opcode() == IrOpcode::kDead ||
      (vobject && !vobject->HasEscaped())) {
    RelaxEffectsAndControls(original);
    return Replace(replacement);
  }
  Type const replacement_type = NodeProperties::GetType(replacement);
  Type const original_type = NodeProperties::GetType(original);
  if (replacement_type.Is(original_type)) {
    RelaxEffectsAndControls(original);
    return Replace(replacement);
  }
  // We need to guard the replacement if we would widen the type otherwise.
  DCHECK_EQ(1, original->op()->EffectOutputCount());
  DCHECK_EQ(1, original->op()->EffectInputCount());
  DCHECK_EQ(1, original->op()->ControlInputCount());
  Node* effect = NodeProperties::GetEffectInput(original);
  Node* control = NodeProperties::GetControlInput(original);
  original->TrimInputCount(0);
  original->AppendInput(jsgraph()->zone(), replacement);
  original->AppendInput(jsgraph()->zone(), effect);
  original->AppendInput(jsgraph()->zone(), control);
  NodeProperties::SetType(
      original,
      Type::Intersect(original_type, replacement_type, jsgraph()->zone()));
  NodeProperties::ChangeOp(original,
                           jsgraph()->common()->TypeGuard(original_type));
  ReplaceWithValue(original, original, original, control);
  return NoChange();
}
References analysis_result(), v8::internal::compiler::Node::AppendInput(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::EscapeAnalysisResult::GetVirtualObject(), v8::internal::compiler::VirtualObject::HasEscaped(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Is(), jsgraph(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::compiler::Node::TrimInputCount(), and zone().
Referenced by Reduce().
VerifyReplacement()
void v8::internal::compiler::EscapeAnalysisReducer::VerifyReplacement () const
Definition at line 202 of file escape-analysis-reducer.cc.
                                                    {
  AllNodes all(zone(), jsgraph()->graph());
  for (Node* node : all.reachable) {
    if (node->opcode() == IrOpcode::kAllocate) {
      if (const VirtualObject* vobject =
              analysis_result().GetVirtualObject(node)) {
        if (!vobject->HasEscaped()) {
          FATAL("Escape analysis failed to remove node %s#%d\n",
                node->op()->mnemonic(), node->id());
        }
      }
    }
  }
}
References all, analysis_result(), FATAL, graph(), v8::internal::compiler::Node::id(), jsgraph(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and zone().
Referenced by v8::internal::compiler::EscapeAnalysisPhase::Run().
zone()
Zone* v8::internal::compiler::EscapeAnalysisReducer::zone () const [inline], [private]
Definition at line 107 of file escape-analysis-reducer.h.
{ return zone_; }
Referenced by Finalize(), ReduceFrameStateInputs(), ReplaceNode(), and VerifyReplacement().
Member Data Documentation
analysis_result_
EscapeAnalysisResult v8::internal::compiler::EscapeAnalysisReducer::analysis_result_ [private]
Definition at line 111 of file escape-analysis-reducer.h.
arguments_elements_
ZoneSet<Node*> v8::internal::compiler::EscapeAnalysisReducer::arguments_elements_ [private]
Definition at line 114 of file escape-analysis-reducer.h.
Referenced by Finalize(), and Reduce().
broker_
JSHeapBroker* const v8::internal::compiler::EscapeAnalysisReducer::broker_ [private]
Definition at line 110 of file escape-analysis-reducer.h.
Referenced by Finalize().
jsgraph_
JSGraph* const v8::internal::compiler::EscapeAnalysisReducer::jsgraph_ [private]
Definition at line 109 of file escape-analysis-reducer.h.
node_cache_
NodeHashCache v8::internal::compiler::EscapeAnalysisReducer::node_cache_ [private]
Definition at line 113 of file escape-analysis-reducer.h.
Referenced by ReduceDeoptState().
object_id_cache_
ZoneVector<Node*> v8::internal::compiler::EscapeAnalysisReducer::object_id_cache_ [private]
Definition at line 112 of file escape-analysis-reducer.h.
Referenced by ObjectIdNode().
zone_
Zone* const v8::internal::compiler::EscapeAnalysisReducer::zone_ [private]
Definition at line 115 of file escape-analysis-reducer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/escape-analysis-reducer.h
/mnt/V8SourceCode/src/compiler/escape-analysis-reducer.cc