v8::internal::HeapEntry Class Reference
#include <heap-snapshot-generator.h>
Public Types
enum Type {
kHidden = v8::HeapGraphNode::kHidden
, kArray = v8::HeapGraphNode::kArray
, kString = v8::HeapGraphNode::kString
, kObject = v8::HeapGraphNode::kObject
,
kCode = v8::HeapGraphNode::kCode
, kClosure = v8::HeapGraphNode::kClosure
, kRegExp = v8::HeapGraphNode::kRegExp
, kHeapNumber = v8::HeapGraphNode::kHeapNumber
,
kNative = v8::HeapGraphNode::kNative
, kSynthetic = v8::HeapGraphNode::kSynthetic
, kConsString = v8::HeapGraphNode::kConsString
, kSlicedString = v8::HeapGraphNode::kSlicedString
,
kSymbol = v8::HeapGraphNode::kSymbol
, kBigInt = v8::HeapGraphNode::kBigInt
, kObjectShape = v8::HeapGraphNode::kObjectShape
, kNumTypes
 }
enum ReferenceVerification { kVerify
, kEphemeron
, kOffHeapPointer
, kCustomWeakPointer
 }
Public Member Functions
HeapEntry (HeapSnapshot *snapshot, int index, Type type, const char *name, SnapshotObjectId id, size_t self_size, unsigned trace_node_id)
HeapSnapshot * snapshot ()
Type type () const
void set_type (Type type)
const char * name () const
void set_name (const char *name)
SnapshotObjectId id () const
size_t self_size () const
void add_self_size (size_t size)
unsigned trace_node_id () const
int index () const
int children_count () const
int set_children_index (int index)
void add_child (HeapGraphEdge *edge)
HeapGraphEdge * child (int i)
Isolate * isolate () const
void set_detachedness (v8::EmbedderGraph::Node::Detachedness value)
uint8_t detachedness () const
void VerifyReference (HeapGraphEdge::Type type, HeapEntry *entry, HeapSnapshotGenerator *generator, ReferenceVerification verification)
void SetIndexedReference (HeapGraphEdge::Type type, int index, HeapEntry *entry, HeapSnapshotGenerator *generator, ReferenceVerification verification=kVerify)
void SetNamedReference (HeapGraphEdge::Type type, const char *name, HeapEntry *entry, HeapSnapshotGenerator *generator, ReferenceVerification verification=kVerify)
void SetIndexedAutoIndexReference (HeapGraphEdge::Type type, HeapEntry *child, HeapSnapshotGenerator *generator, ReferenceVerification verification=kVerify)
void SetNamedAutoIndexReference (HeapGraphEdge::Type type, const char *description, HeapEntry *child, StringsStorage *strings, HeapSnapshotGenerator *generator, ReferenceVerification verification=kVerify)
V8_EXPORT_PRIVATE void Print (const char *prefix, const char *edge_name, int max_depth, int indent) const
Private Member Functions
std::vector< HeapGraphEdge * >::iterator children_begin () const
std::vector< HeapGraphEdge * >::iterator children_end () const
const char * TypeAsString () const
Private Attributes
unsigned type_: 4
unsigned index_: 28
xx xx xx xx xx xx xx xx xx
union {
 unsigned children_count_
 unsigned children_end_index_
};
size_t self_size_
uint8_t detachedness_ = 0
HeapSnapshot * snapshot_
const char * name_
SnapshotObjectId id_
unsigned trace_node_id_
Detailed Description
Definition at line 108 of file heap-snapshot-generator.h.
Member Enumeration Documentation
ReferenceVerification
enum v8::internal::HeapEntry::ReferenceVerification
Enumerator
kVerify
kEphemeron
kOffHeapPointer
kCustomWeakPointer
Definition at line 153 of file heap-snapshot-generator.h.
                             {
    // Verify that the reference can be found via marking, if verification is
    // enabled.
    kVerify,
    // Skip verifying that the reference can be found via marking, for any of
    // the following reasons:
    kEphemeron,
    kOffHeapPointer,
    kCustomWeakPointer,
  };
Type
enum v8::internal::HeapEntry::Type
Enumerator
kHidden
kArray
kString
kObject
kCode
kClosure
kRegExp
kHeapNumber
kNative
kSynthetic
kConsString
kSlicedString
kSymbol
kBigInt
kObjectShape
kNumTypes
Definition at line 110 of file heap-snapshot-generator.h.
            {
    kHidden = v8::HeapGraphNode::kHidden,
    kArray = v8::HeapGraphNode::kArray,
    kString = v8::HeapGraphNode::kString,
    kObject = v8::HeapGraphNode::kObject,
    kCode = v8::HeapGraphNode::kCode,
    kClosure = v8::HeapGraphNode::kClosure,
    kRegExp = v8::HeapGraphNode::kRegExp,
    kHeapNumber = v8::HeapGraphNode::kHeapNumber,
    kNative = v8::HeapGraphNode::kNative,
    kSynthetic = v8::HeapGraphNode::kSynthetic,
    kConsString = v8::HeapGraphNode::kConsString,
    kSlicedString = v8::HeapGraphNode::kSlicedString,
    kSymbol = v8::HeapGraphNode::kSymbol,
    kBigInt = v8::HeapGraphNode::kBigInt,
    kObjectShape = v8::HeapGraphNode::kObjectShape,
    kNumTypes,
  };
Constructor & Destructor Documentation
HeapEntry()
v8::internal::HeapEntry::HeapEntry (HeapSnapshot * snapshot, int index, Type type, const char * name, SnapshotObjectId id, size_t self_size, unsigned trace_node_id)
Definition at line 229 of file heap-snapshot-generator.cc.
    : type_(static_cast<unsigned>(type)),
      index_(index),
      children_count_(0),
      self_size_(self_size),
      snapshot_(snapshot),
      name_(name),
      id_(id),
      trace_node_id_(trace_node_id) {
  DCHECK_GE(index, 0);
}
References DCHECK_GE, and index().
Member Function Documentation
add_child()
void v8::internal::HeapEntry::add_child (HeapGraphEdge * edge) [inline]
Definition at line 34 of file heap-snapshot-generator-inl.h.
                                             {
  snapshot_->children()[children_end_index_++] = edge;
}
References v8::internal::HeapSnapshot::children(), children_end_index_, and snapshot_.
add_self_size()
void v8::internal::HeapEntry::add_self_size (size_t size) [inline]
Definition at line 139 of file heap-snapshot-generator.h.
{ self_size_ += size; }
References self_size_, and size().
Referenced by v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
child()
HeapGraphEdge * v8::internal::HeapEntry::child (int i) [inline]
Definition at line 38 of file heap-snapshot-generator-inl.h.
{ return children_begin()[i]; }
References children_begin(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by SetIndexedAutoIndexReference(), and SetNamedAutoIndexReference().
children_begin()
std::vector< HeapGraphEdge * >::iterator v8::internal::HeapEntry::children_begin () const [inline], [private]
Definition at line 40 of file heap-snapshot-generator-inl.h.
                                                                  {
  return index_ == 0 ? snapshot_->children().begin()
                     : snapshot_->entries()[index_ - 1].children_end();
}
References v8::internal::HeapSnapshot::children(), v8::internal::HeapSnapshot::entries(), index_, and snapshot_.
Referenced by child(), children_count(), and Print().
children_count()
int v8::internal::HeapEntry::children_count () const [inline]
Definition at line 50 of file heap-snapshot-generator-inl.h.
                                    {
  return static_cast<int>(children_end() - children_begin());
}
References children_begin(), and children_end().
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeNode().
children_end()
std::vector< HeapGraphEdge * >::iterator v8::internal::HeapEntry::children_end () const [inline], [private]
Definition at line 45 of file heap-snapshot-generator-inl.h.
                                                                {
  DCHECK_GE(children_end_index_, 0);
  return snapshot_->children().begin() + children_end_index_;
}
References v8::internal::HeapSnapshot::children(), children_end_index_, DCHECK_GE, and snapshot_.
Referenced by children_count(), and Print().
detachedness()
uint8_t v8::internal::HeapEntry::detachedness () const [inline]
Definition at line 151 of file heap-snapshot-generator.h.
{ return detachedness_; }
References detachedness_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeNode().
id()
SnapshotObjectId v8::internal::HeapEntry::id () const [inline]
Definition at line 137 of file heap-snapshot-generator.h.
{ return id_; }
References id_.
Referenced by v8::internal::V8HeapExplorer::ExtractEphemeronHashTableReferences(), v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry(), and v8::internal::HeapSnapshotJSONSerializer::SerializeNode().
index()
int v8::internal::HeapEntry::index () const [inline]
Definition at line 141 of file heap-snapshot-generator.h.
{ return index_; }
References index_.
Referenced by v8::internal::HeapSnapshot::AddLocation(), HeapEntry(), Print(), v8::internal::HeapSnapshotJSONSerializer::SerializeImpl(), set_children_index(), SetIndexedReference(), SetNamedAutoIndexReference(), and v8::internal::HeapSnapshotJSONSerializer::to_node_index().
isolate()
Isolate * v8::internal::HeapEntry::isolate () const [inline]
Definition at line 54 of file heap-snapshot-generator-inl.h.
{ return snapshot_->profiler()->isolate(); }
References v8::internal::HeapProfiler::isolate(), v8::internal::HeapSnapshot::profiler(), and snapshot_.
Referenced by v8::internal::HeapGraphEdge::isolate().
name()
const char* v8::internal::HeapEntry::name () const [inline]
Definition at line 135 of file heap-snapshot-generator.h.
{ return name_; }
References name_.
Referenced by v8::internal::V8HeapExplorer::ExtractContextReferences(), v8::internal::V8HeapExplorer::ExtractEphemeronHashTableReferences(), v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry(), v8::internal::HeapSnapshotJSONSerializer::SerializeNode(), set_name(), SetNamedAutoIndexReference(), SetNamedReference(), and v8::internal::V8HeapExplorer::TagObject().
Print()
void v8::internal::HeapEntry::Print (const char * prefix, const char * edge_name, int max_depth, int indent) const
Definition at line 323 of file heap-snapshot-generator.cc.
                                        {
  static_assert(sizeof(unsigned) == sizeof(id()));
  base::OS::Print("%6zu @%6u %*c %s%s: ", self_size(), id(), indent, ' ',
                  prefix, edge_name);
  if (type() != kString) {
    base::OS::Print("%s %.40s\n", TypeAsString(), name_);
  } else {
    base::OS::Print("\"");
    const char* c = name_;
    while (*c && (c - name_) <= 40) {
      if (*c != '\n')
        base::OS::Print("%c", *c);
      else
        base::OS::Print("\\n");
      ++c;
    }
    base::OS::Print("\"\n");
  }
  if (--max_depth == 0) return;
  for (auto i = children_begin(); i != children_end(); ++i) {
    HeapGraphEdge& edge = **i;
    const char* edge_prefix = "";
    base::EmbeddedVector<char, 64> index;
    edge_name = index.begin();
    switch (edge.type()) {
      case HeapGraphEdge::kContextVariable:
        edge_prefix = "#";
        edge_name = edge.name();
        break;
      case HeapGraphEdge::kElement:
        SNPrintF(index, "%d", edge.index());
        break;
      case HeapGraphEdge::kInternal:
        edge_prefix = "$";
        edge_name = edge.name();
        break;
      case HeapGraphEdge::kProperty:
        edge_name = edge.name();
        break;
      case HeapGraphEdge::kHidden:
        edge_prefix = "$";
        SNPrintF(index, "%d", edge.index());
        break;
      case HeapGraphEdge::kShortcut:
        edge_prefix = "^";
        edge_name = edge.name();
        break;
      case HeapGraphEdge::kWeak:
        edge_prefix = "w";
        edge_name = edge.name();
        break;
      default:
        SNPrintF(index, "!!! unknown edge type: %d ", edge.type());
    }
    edge.to()->Print(edge_prefix, edge_name, max_depth, indent + 2);
  }
}
References children_begin(), children_end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::HeapGraphEdge::index(), index(), v8::internal::HeapGraphEdge::kContextVariable, v8::internal::HeapGraphEdge::kElement, v8::internal::HeapGraphEdge::kHidden, v8::internal::HeapGraphEdge::kInternal, v8::internal::HeapGraphEdge::kProperty, v8::internal::HeapGraphEdge::kShortcut, kString, v8::internal::HeapGraphEdge::kWeak, v8::internal::HeapGraphEdge::name(), name_, Print(), v8::internal::Print(), self_size(), v8::base::SNPrintF(), v8::internal::HeapGraphEdge::to(), v8::internal::HeapGraphEdge::type(), type(), and TypeAsString().
Referenced by Print(), and v8::internal::HeapSnapshot::Print().
self_size()
size_t v8::internal::HeapEntry::self_size () const [inline]
Definition at line 138 of file heap-snapshot-generator.h.
{ return self_size_; }
References self_size_.
Referenced by v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry(), Print(), and v8::internal::HeapSnapshotJSONSerializer::SerializeNode().
set_children_index()
int v8::internal::HeapEntry::set_children_index (int index) [inline]
Definition at line 27 of file heap-snapshot-generator-inl.h.
                                           {
  // Note: children_count_ and children_end_index_ are parts of a union.
  int next_index = index + children_count_;
  children_end_index_ = index;
  return next_index;
}
References children_count_, children_end_index_, and index().
set_detachedness()
void v8::internal::HeapEntry::set_detachedness (v8::EmbedderGraph::Node::Detachedness value) [inline]
Definition at line 148 of file heap-snapshot-generator.h.
                                                               {
    detachedness_ = static_cast<uint8_t>(value);
  }
References detachedness_, and v8::internal::value.
Referenced by v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), and v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
set_name()
void v8::internal::HeapEntry::set_name (const char * name) [inline]
Definition at line 136 of file heap-snapshot-generator.h.
{ name_ = name; }
References name(), and name_.
Referenced by v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry(), and v8::internal::V8HeapExplorer::TagObject().
set_type()
void v8::internal::HeapEntry::set_type (Type type) [inline]
Definition at line 134 of file heap-snapshot-generator.h.
{ type_ = static_cast<unsigned>(type); }
References type(), and type_.
Referenced by v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry(), and v8::internal::V8HeapExplorer::TagObject().
SetIndexedAutoIndexReference()
void v8::internal::HeapEntry::SetIndexedAutoIndexReference (HeapGraphEdge::Type type, HeapEntry * child, HeapSnapshotGenerator * generator, ReferenceVerification verification = kVerify) [inline]
Definition at line 175 of file heap-snapshot-generator.h.
                                                    {
    SetIndexedReference(type, children_count_ + 1, child, generator,
                        verification);
  }
References child(), children_count_, SetIndexedReference(), and type().
Referenced by v8::internal::NativeObjectsExplorer::IterateAndExtractReferences(), v8::internal::V8HeapExplorer::SetGcRootsReference(), and v8::internal::V8HeapExplorer::SetRootGcRootsReference().
SetIndexedReference()
void v8::internal::HeapEntry::SetIndexedReference (HeapGraphEdge::Type type, int index, HeapEntry * entry, HeapSnapshotGenerator * generator, ReferenceVerification verification = kVerify)
Definition at line 301 of file heap-snapshot-generator.cc.
                                                                        {
  ++children_count_;
  snapshot_->edges().emplace_back(type, index, this, entry);
  VerifyReference(type, entry, generator, verification);
}
References children_count_, v8::internal::HeapSnapshot::edges(), index(), snapshot_, type(), and VerifyReference().
Referenced by v8::internal::V8HeapExplorer::SetElementReference(), v8::internal::V8HeapExplorer::SetHiddenReference(), and SetIndexedAutoIndexReference().
SetNamedAutoIndexReference()
void v8::internal::HeapEntry::SetNamedAutoIndexReference (HeapGraphEdge::Type type, const char * description, HeapEntry * child, StringsStorage * strings, HeapSnapshotGenerator * generator, ReferenceVerification verification = kVerify)
Definition at line 310 of file heap-snapshot-generator.cc.
                                                                               {
  int index = children_count_ + 1;
  const char* name = description
                         ? names->GetFormatted("%d / %s", index, description)
                         : names->GetName(index);
  SetNamedReference(type, name, child, generator, verification);
}
References child(), children_count_, v8::internal::StringsStorage::GetName(), index(), name(), SetNamedReference(), and type().
Referenced by v8::internal::V8HeapExplorer::ExtractEphemeronHashTableReferences(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::ExternalStringRecorder::RecordSharedMemoryUsage(), v8::internal::V8HeapExplorer::SetGcSubrootReference(), and v8::internal::V8HeapExplorer::SetUserGlobalReference().
SetNamedReference()
void v8::internal::HeapEntry::SetNamedReference (HeapGraphEdge::Type type, const char * name, HeapEntry * entry, HeapSnapshotGenerator * generator, ReferenceVerification verification = kVerify)
Definition at line 292 of file heap-snapshot-generator.cc.
                                                                      {
  ++children_count_;
  snapshot_->edges().emplace_back(type, name, this, entry);
  VerifyReference(type, entry, generator, verification);
}
References children_count_, v8::internal::HeapSnapshot::edges(), name(), snapshot_, type(), and VerifyReference().
Referenced by v8::internal::V8HeapExplorer::ExtractJSArrayBufferReferences(), v8::internal::V8HeapExplorer::ExtractNumberReference(), v8::internal::NativeObjectsExplorer::IterateAndExtractReferences(), v8::internal::V8HeapExplorer::SetContextReference(), v8::internal::V8HeapExplorer::SetGcSubrootReference(), v8::internal::V8HeapExplorer::SetInternalReference(), SetNamedAutoIndexReference(), v8::internal::V8HeapExplorer::SetNativeBindReference(), v8::internal::V8HeapExplorer::SetPropertyReference(), and v8::internal::V8HeapExplorer::SetWeakReference().
snapshot()
HeapSnapshot* v8::internal::HeapEntry::snapshot () [inline]
Definition at line 132 of file heap-snapshot-generator.h.
{ return snapshot_; }
References snapshot_.
Referenced by v8::internal::HeapGraphEdge::snapshot().
trace_node_id()
unsigned v8::internal::HeapEntry::trace_node_id () const [inline]
Definition at line 140 of file heap-snapshot-generator.h.
{ return trace_node_id_; }
References trace_node_id_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeNode().
type()
Type v8::internal::HeapEntry::type () const [inline]
Definition at line 133 of file heap-snapshot-generator.h.
{ return static_cast<Type>(type_); }
References type_.
Referenced by Print(), v8::internal::HeapSnapshotJSONSerializer::SerializeNode(), set_type(), SetIndexedAutoIndexReference(), SetIndexedReference(), SetNamedAutoIndexReference(), SetNamedReference(), TypeAsString(), and VerifyReference().
TypeAsString()
const char * v8::internal::HeapEntry::TypeAsString () const [private]
Definition at line 382 of file heap-snapshot-generator.cc.
                                          {
  switch (type()) {
    case kHidden:
      return "/hidden/";
    case kObject:
      return "/object/";
    case kClosure:
      return "/closure/";
    case kString:
      return "/string/";
    case kCode:
      return "/code/";
    case kArray:
      return "/array/";
    case kRegExp:
      return "/regexp/";
    case kHeapNumber:
      return "/number/";
    case kNative:
      return "/native/";
    case kSynthetic:
      return "/synthetic/";
    case kConsString:
      return "/concatenated string/";
    case kSlicedString:
      return "/sliced string/";
    case kSymbol:
      return "/symbol/";
    case kBigInt:
      return "/bigint/";
    case kObjectShape:
      return "/object shape/";
    default:
      return "???";
  }
}
References kArray, kBigInt, kClosure, kCode, kConsString, kHeapNumber, kHidden, kNative, kObject, kObjectShape, kRegExp, kSlicedString, kString, kSymbol, kSynthetic, and type().
Referenced by Print().
VerifyReference()
void v8::internal::HeapEntry::VerifyReference (HeapGraphEdge::Type type, HeapEntry * entry, HeapSnapshotGenerator * generator, ReferenceVerification verification)
Definition at line 243 of file heap-snapshot-generator.cc.
                                                                    {
#ifdef V8_ENABLE_HEAP_SNAPSHOT_VERIFY
  if (verification == kOffHeapPointer || generator->verifier() == nullptr) {
    // Off-heap pointers are outside the scope of this verification; we just
    // trust the embedder to provide accurate data. If the verifier is null,
    // then verification is disabled.
    return;
  }
  if (verification == kCustomWeakPointer) {
    // The caller declared that this is a weak pointer ignored by the marking
    // visitor. All we can verify at this point is that the edge type declares
    // it to be weak.
    CHECK_EQ(type, HeapGraphEdge::kWeak);
    return;
  }
  Address from_address =
      reinterpret_cast<Address>(generator->FindHeapThingForHeapEntry(this));
  Address to_address =
      reinterpret_cast<Address>(generator->FindHeapThingForHeapEntry(entry));
  if (from_address == kNullAddress || to_address == kNullAddress) {
    // One of these entries doesn't correspond to a real heap object.
    // Verification is not possible.
    return;
  }
  Tagged<HeapObject> from_obj = Cast<HeapObject>(Tagged<Object>(from_address));
  Tagged<HeapObject> to_obj = Cast<HeapObject>(Tagged<Object>(to_address));
  if (MemoryChunk::FromHeapObject(to_obj)->InReadOnlySpace()) {
    // We can't verify pointers into read-only space, because marking visitors
    // might not mark those. For example, every Map has a pointer to the
    // MetaMap, but marking visitors don't bother with following that link.
    // Read-only objects are immortal and can never point to things outside of
    // read-only space, so ignoring these objects is safe from the perspective
    // of ensuring accurate retaining paths for normal read-write objects.
    // Therefore, do nothing.
  } else if (verification == kEphemeron) {
    // Ephemerons can't be verified because they aren't marked directly by the
    // marking visitor.
    generator->verifier()->MarkReferenceCheckedWithoutChecking(from_obj,
                                                               to_obj);
  } else if (type == HeapGraphEdge::kWeak) {
    generator->verifier()->CheckWeakReference(from_obj, to_obj);
  } else {
    generator->verifier()->CheckStrongReference(from_obj, to_obj);
  }
#endif
}
References CHECK_EQ, v8::internal::MemoryChunk::FromHeapObject(), kCustomWeakPointer, kEphemeron, v8::internal::kNullAddress, kOffHeapPointer, v8::internal::HeapGraphEdge::kWeak, and type().
Referenced by SetIndexedReference(), and SetNamedReference().
Member Data Documentation
union { ... } [private]
children_count_
unsigned v8::internal::HeapEntry::children_count_
Definition at line 202 of file heap-snapshot-generator.h.
Referenced by set_children_index(), SetIndexedAutoIndexReference(), SetIndexedReference(), SetNamedAutoIndexReference(), and SetNamedReference().
children_end_index_
unsigned v8::internal::HeapEntry::children_end_index_
Definition at line 203 of file heap-snapshot-generator.h.
Referenced by add_child(), children_end(), and set_children_index().
detachedness_
uint8_t v8::internal::HeapEntry::detachedness_ = 0 [private]
Definition at line 210 of file heap-snapshot-generator.h.
Referenced by detachedness(), and set_detachedness().
id_
SnapshotObjectId v8::internal::HeapEntry::id_ [private]
Definition at line 213 of file heap-snapshot-generator.h.
Referenced by id().
index_
unsigned v8::internal::HeapEntry::index_ [private]
Definition at line 198 of file heap-snapshot-generator.h.
Referenced by children_begin(), and index().
name_
const char* v8::internal::HeapEntry::name_ [private]
Definition at line 212 of file heap-snapshot-generator.h.
Referenced by name(), Print(), and set_name().
self_size_
size_t v8::internal::HeapEntry::self_size_ [private]
Definition at line 208 of file heap-snapshot-generator.h.
Referenced by add_self_size(), and self_size().
snapshot_
HeapSnapshot* v8::internal::HeapEntry::snapshot_ [private]
Definition at line 211 of file heap-snapshot-generator.h.
Referenced by add_child(), children_begin(), children_end(), isolate(), SetIndexedReference(), SetNamedReference(), and snapshot().
trace_node_id_
unsigned v8::internal::HeapEntry::trace_node_id_ [private]
Definition at line 215 of file heap-snapshot-generator.h.
Referenced by trace_node_id().
type_
unsigned v8::internal::HeapEntry::type_ [private]
Definition at line 197 of file heap-snapshot-generator.h.
Referenced by set_type(), and type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator-inl.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc