v8::internal::compiler::Loong64OperandGenerator Class Reference
Public Member Functions
Loong64OperandGenerator (InstructionSelector *selector)
InstructionOperand UseOperand (OpIndex node, InstructionCode opcode)
InstructionOperand UseRegisterOrImmediateZero (OpIndex node)
bool IsIntegerConstant (OpIndex node)
std::optional< int64_t > GetOptionalIntegerConstant (OpIndex operation)
bool CanBeImmediate (OpIndex node, InstructionCode mode)
bool CanBeImmediate (int64_t value, InstructionCode opcode)
Private Member Functions
bool ImmediateFitsAddrMode1Instruction (int32_t imm) const
Additional Inherited Members
Detailed Description
Definition at line 24 of file instruction-selector-loong64.cc.
Constructor & Destructor Documentation
Loong64OperandGenerator()
v8::internal::compiler::Loong64OperandGenerator::Loong64OperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 26 of file instruction-selector-loong64.cc.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeImmediate() [1/2]
bool v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate (int64_t value, InstructionCode opcode) [inline]
Definition at line 89 of file instruction-selector-loong64.cc.
                                                             {
    switch (ArchOpcodeField::decode(opcode)) {
      case kLoong64Cmp32:
      case kLoong64Cmp64:
        return true;
      case kLoong64Sll_w:
      case kLoong64Srl_w:
      case kLoong64Sra_w:
        return is_uint5(value);
      case kLoong64Sll_d:
      case kLoong64Srl_d:
      case kLoong64Sra_d:
        return is_uint6(value);
      case kLoong64And:
      case kLoong64And32:
      case kLoong64Or:
      case kLoong64Or32:
      case kLoong64Xor:
      case kLoong64Xor32:
      case kLoong64Tst:
        return is_uint12(value);
      case kLoong64Ld_w:
      case kLoong64St_w:
      case kLoong64Ld_d:
      case kLoong64St_d:
      case kAtomicLoadWord32:
      case kAtomicStoreWord32:
      case kLoong64Word64AtomicLoadUint64:
      case kLoong64Word64AtomicStoreWord64:
      case kLoong64StoreCompressTagged:
        return (is_int12(value) || (is_int16(value) && ((value & 0b11) == 0)));
      default:
        return is_int12(value);
    }
  }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::value.
CanBeImmediate() [2/2]
bool v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate (OpIndex node, InstructionCode mode) [inline]
Definition at line 63 of file instruction-selector-loong64.cc.
                                                          {
    const ConstantOp* constant = selector()->Get(node).TryCast<ConstantOp>();
    if (!constant) return false;
    if (constant->kind == ConstantOp::Kind::kCompressedHeapObject) {
      if (!COMPRESS_POINTERS_BOOL) return false;
      // For builtin code we need static roots
      if (selector()->isolate()->bootstrapper() && !V8_STATIC_ROOTS_BOOL) {
        return false;
      }
      const RootsTable& roots_table = selector()->isolate()->roots_table();
      RootIndex root_index;
      Handle<HeapObject> value = constant->handle();
      if (roots_table.IsRootHandle(value, &root_index)) {
        if (!RootsTable::IsReadOnly(root_index)) return false;
        return CanBeImmediate(MacroAssemblerBase::ReadOnlyRootPtr(
                                  root_index, selector()->isolate()),
                              mode);
      }
      return false;
    }
    int64_t value;
    return selector()->MatchSignedIntegralConstant(node, &value) &&
           CanBeImmediate(value, mode);
  }
References v8::internal::compiler::CanBeImmediate(), COMPRESS_POINTERS_BOOL, v8::internal::compiler::turboshaft::ConstantOp::handle(), v8::internal::RootsTable::IsReadOnly(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::turboshaft::ConstantOp::kCompressedHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kind, mode(), v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::compiler::turboshaft::Operation::TryCast(), V8_STATIC_ROOTS_BOOL, and v8::internal::value.
Referenced by v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::TryMatchImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), and v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare().
GetOptionalIntegerConstant()
std::optional<int64_t> v8::internal::compiler::Loong64OperandGenerator::GetOptionalIntegerConstant (OpIndex operation) [inline]
Definition at line 56 of file instruction-selector-loong64.cc.
                                                                     {
    if (int64_t constant; MatchSignedIntegralConstant(operation, &constant)) {
      return constant;
    }
    return std::nullopt;
  }
ImmediateFitsAddrMode1Instruction()
bool v8::internal::compiler::Loong64OperandGenerator::ImmediateFitsAddrMode1Instruction (int32_t imm) const [inline], [private]
Definition at line 126 of file instruction-selector-loong64.cc.
                                                            {
    TRACE("UNIMPLEMENTED instr_sel: %s at line %d\n", __FUNCTION__, __LINE__);
    return false;
  }
References v8::internal::TRACE().
IsIntegerConstant()
bool v8::internal::compiler::Loong64OperandGenerator::IsIntegerConstant (OpIndex node) [inline]
Definition at line 51 of file instruction-selector-loong64.cc.
                                       {
    int64_t unused;
    return selector()->MatchSignedIntegralConstant(node, &unused);
  }
UseOperand()
InstructionOperand v8::internal::compiler::Loong64OperandGenerator::UseOperand (OpIndex node, InstructionCode opcode) [inline]
Definition at line 29 of file instruction-selector-loong64.cc.
                                                                      {
    if (CanBeImmediate(node, opcode)) {
      return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::compiler::CanBeImmediate(), and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::VisitBinop(), and v8::internal::compiler::VisitRRO().
UseRegisterOrImmediateZero()
InstructionOperand v8::internal::compiler::Loong64OperandGenerator::UseRegisterOrImmediateZero (OpIndex node) [inline]
Definition at line 38 of file instruction-selector-loong64.cc.
                                                              {
    if (const ConstantOp* constant =
            selector()->Get(node).TryCast<ConstantOp>()) {
      if ((constant->IsIntegral() && constant->integral() == 0) ||
          (constant->kind == ConstantOp::Kind::kFloat32 &&
           constant->float32().get_bits() == 0) ||
          (constant->kind == ConstantOp::Kind::kFloat64 &&
           constant->float64().get_bits() == 0))
        return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::ConstantOp::kFloat32, v8::internal::compiler::turboshaft::ConstantOp::kFloat64, and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/loong64/instruction-selector-loong64.cc