v8::internal::compiler::PPCOperandGenerator Class Reference
Public Member Functions
PPCOperandGenerator (InstructionSelector *selector)
InstructionOperand UseOperand (OpIndex node, ImmediateMode mode)
bool CanBeImmediate (OpIndex node, ImmediateMode mode)
bool CanBeImmediate (int64_t value, ImmediateMode mode)
Additional Inherited Members
Detailed Description
Definition at line 31 of file instruction-selector-ppc.cc.
Constructor & Destructor Documentation
PPCOperandGenerator()
v8::internal::compiler::PPCOperandGenerator::PPCOperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 33 of file instruction-selector-ppc.cc.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeImmediate() [1/2]
bool v8::internal::compiler::PPCOperandGenerator::CanBeImmediate (int64_t value, ImmediateMode mode) [inline]
Definition at line 69 of file instruction-selector-ppc.cc.
                                                         {
    switch (mode) {
      case kInt16Imm:
        return is_int16(value);
      case kInt16Imm_Unsigned:
        return is_uint16(value);
      case kInt16Imm_Negate:
        return is_int16(-value);
      case kInt16Imm_4ByteAligned:
        return is_int16(value) && !(value & 3);
      case kShift32Imm:
        return 0 <= value && value < 32;
      case kInt34Imm:
        return is_int34(value);
      case kShift64Imm:
        return 0 <= value && value < 64;
      case kNoImmediate:
        return false;
    }
    return false;
  }
References v8::internal::compiler::kInt16Imm, v8::internal::compiler::kInt16Imm_4ByteAligned, v8::internal::compiler::kInt16Imm_Negate, v8::internal::compiler::kInt16Imm_Unsigned, v8::internal::compiler::kInt34Imm, v8::internal::compiler::kNoImmediate, v8::internal::compiler::kShift32Imm, v8::internal::compiler::kShift64Imm, mode(), and v8::internal::value.
CanBeImmediate() [2/2]
bool v8::internal::compiler::PPCOperandGenerator::CanBeImmediate (OpIndex node, ImmediateMode mode) [inline]
Definition at line 43 of file instruction-selector-ppc.cc.
                                                        {
    const ConstantOp* constant = selector()->Get(node).TryCast<ConstantOp>();
    if (!constant) return false;
    if (constant->kind == ConstantOp::Kind::kCompressedHeapObject) {
      if (!COMPRESS_POINTERS_BOOL) return false;
      // For builtin code we need static roots
      if (selector()->isolate()->bootstrapper() && !V8_STATIC_ROOTS_BOOL) {
        return false;
      }
      const RootsTable& roots_table = selector()->isolate()->roots_table();
      RootIndex root_index;
      Handle<HeapObject> value = constant->handle();
      if (roots_table.IsRootHandle(value, &root_index)) {
        if (!RootsTable::IsReadOnly(root_index)) return false;
        return CanBeImmediate(MacroAssemblerBase::ReadOnlyRootPtr(
                                  root_index, selector()->isolate()),
                              mode);
      }
      return false;
    }
    int64_t value;
    if (!selector()->MatchSignedIntegralConstant(node, &value)) return false;
    return CanBeImmediate(value, mode);
  }
References v8::internal::compiler::CanBeImmediate(), COMPRESS_POINTERS_BOOL, v8::internal::compiler::turboshaft::ConstantOp::handle(), v8::internal::RootsTable::IsReadOnly(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::turboshaft::ConstantOp::kCompressedHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kind, mode(), v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::compiler::turboshaft::Operation::TryCast(), V8_STATIC_ROOTS_BOOL, and v8::internal::value.
Referenced by v8::internal::compiler::VisitLoadCommon(), v8::internal::compiler::VisitStoreCommon(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWordCompare().
UseOperand()
InstructionOperand v8::internal::compiler::PPCOperandGenerator::UseOperand (OpIndex node, ImmediateMode mode) [inline]
Definition at line 36 of file instruction-selector-ppc.cc.
                                                                  {
    if (CanBeImmediate(node, mode)) {
      return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::compiler::CanBeImmediate(), mode(), and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRO().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/ppc/instruction-selector-ppc.cc