v8::internal::LargePageMetadata Class Reference
#include <large-page-metadata.h>
Public Member Functions
LargePageMetadata (Heap *heap, BaseSpace *space, size_t chunk_size, Address area_start, Address area_end, VirtualMemory reservation, Executability executable)
MemoryChunk::MainThreadFlags InitialFlags (Executability executable) const
Tagged< HeapObject > GetObject () const
LargePageMetadata * next_page ()
const LargePageMetadata * next_page () const
void ClearOutOfLiveRangeSlots (Address free_start)
Static Public Member Functions
static LargePageMetadata * cast (MutablePageMetadata *metadata)
static LargePageMetadata * cast (MemoryChunkMetadata *metadata)
static LargePageMetadata * FromHeapObject (Tagged< HeapObject > o)
Static Public Attributes
static constexpr int kMaxCodePageSize = 512 * MB
Friends
class MemoryAllocator
Additional Inherited Members
Detailed Description
Definition at line 13 of file large-page-metadata.h.
Constructor & Destructor Documentation
LargePageMetadata()
v8::internal::LargePageMetadata::LargePageMetadata (Heap * heap, BaseSpace * space, size_t chunk_size, Address area_start, Address area_end, VirtualMemory reservation, Executability executable)
Definition at line 18 of file large-page-metadata.cc.
    : MutablePageMetadata(heap, space, chunk_size, area_start, area_end,
                          std::move(reservation), PageSize::kLarge) {
  static_assert(LargePageMetadata::kMaxCodePageSize <=
                TypedSlotSet::kMaxOffset);
  DCHECK(IsLargePage());
  if (executable && chunk_size > LargePageMetadata::kMaxCodePageSize) {
    FATAL("Code page is too large.");
  }
  list_node().Initialize();
}
References v8::internal::DCHECK(), FATAL, v8::internal::MutablePageMetadata::IsLargePage(), v8::internal::kLarge, kMaxCodePageSize, v8::internal::TypedSlots::kMaxOffset, and v8::internal::MutablePageMetadata::list_node().
Member Function Documentation
cast() [1/2]
static LargePageMetadata* v8::internal::LargePageMetadata::cast (MemoryChunkMetadata * metadata) [inline], [static]
Definition at line 25 of file large-page-metadata.h.
                                                                {
    return cast(MutablePageMetadata::cast(metadata));
  }
References v8::internal::MutablePageMetadata::cast(), and cast().
cast() [2/2]
static LargePageMetadata* v8::internal::LargePageMetadata::cast (MutablePageMetadata * metadata) [inline], [static]
Definition at line 20 of file large-page-metadata.h.
                                                                {
    DCHECK_IMPLIES(metadata, metadata->Chunk()->IsLargePage());
    return static_cast<LargePageMetadata*>(metadata);
  }
References v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_IMPLIES, and v8::internal::MemoryChunk::IsLargePage().
Referenced by cast(), FromHeapObject(), next_page(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), and v8::internal::HeapAllocator::TryResizeLargeObject().
ClearOutOfLiveRangeSlots()
void v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots (Address free_start)
Definition at line 43 of file large-page-metadata.cc.
                                                                   {
  DCHECK_NULL(slot_set<OLD_TO_NEW>());
  DCHECK_NULL(typed_slot_set<OLD_TO_NEW>());
  DCHECK_NULL(slot_set<OLD_TO_NEW_BACKGROUND>());
  DCHECK_NULL(typed_slot_set<OLD_TO_NEW_BACKGROUND>());
  DCHECK_NULL(slot_set<OLD_TO_OLD>());
  DCHECK_NULL(typed_slot_set<OLD_TO_OLD>());
  DCHECK(!Chunk()->InTrustedSpace());
  DCHECK_NULL(slot_set<TRUSTED_TO_TRUSTED>());
  DCHECK_NULL(typed_slot_set<TRUSTED_TO_TRUSTED>());
  DCHECK_NULL(slot_set<TRUSTED_TO_SHARED_TRUSTED>());
  DCHECK_NULL(typed_slot_set<TRUSTED_TO_SHARED_TRUSTED>());
  // area_end() might not be aligned to a full bucket size with large objects.
  // Align it to bucket size such that the following RemoveRange invocation just
  // drops the whole bucket and the bucket is reset to nullptr.
  Address aligned_area_end =
      ChunkAddress() + SlotSet::OffsetForBucket(BucketsInSlotSet());
  DCHECK_LE(area_end(), aligned_area_end);
  RememberedSet<OLD_TO_SHARED>::RemoveRange(this, free_start, aligned_area_end,
                                            SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_SHARED>::RemoveRangeTyped(this, free_start, area_end());
}
References v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MutablePageMetadata::BucketsInSlotSet(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::DCHECK(), DCHECK_LE, DCHECK_NULL, heap::base::BasicSlotSet< kTaggedSize >::FREE_EMPTY_BUCKETS, v8::internal::MemoryChunkMetadata::InTrustedSpace(), heap::base::BasicSlotSet< kTaggedSize >::OffsetForBucket(), v8::internal::RememberedSet< type >::RemoveRange(), and v8::internal::RememberedSet< type >::RemoveRangeTyped().
Referenced by v8::internal::LargeObjectSpace::ShrinkPageToObjectSize().
FromHeapObject()
LargePageMetadata * v8::internal::LargePageMetadata::FromHeapObject (Tagged< HeapObject > o) [inline], [static]
Definition at line 17 of file large-page-metadata-inl.h.
                                                                         {
  return cast(MutablePageMetadata::FromHeapObject(o));
}
References cast(), and v8::internal::MutablePageMetadata::FromHeapObject().
Referenced by v8::internal::FactoryBase< Impl >::AllocateRawArray(), v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), and v8::internal::Factory::TryNewFixedArray().
GetObject()
Tagged<HeapObject> v8::internal::LargePageMetadata::GetObject () const [inline]
Definition at line 37 of file large-page-metadata.h.
                                       {
    return HeapObject::FromAddress(area_start());
  }
References v8::internal::MemoryChunkMetadata::area_start(), and v8::internal::HeapObject::FromAddress().
Referenced by v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::MarkCompactCollector::EvacuatePagesInParallel(), v8::internal::NewLargeObjectSpace::FreeDeadObjects(), v8::internal::LargeObjectSpaceObjectIterator::Next(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::anonymous_namespace{mark-compact.cc}::ShrinkPagesToObjectSizes(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::MarkCompactCollector::SweepLargeSpace(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
InitialFlags()
MemoryChunk::MainThreadFlags v8::internal::LargePageMetadata::InitialFlags (Executability executable) const
Definition at line 37 of file large-page-metadata.cc.
                                    {
  return MutablePageMetadata::InitialFlags(executable) |
         MemoryChunk::LARGE_PAGE;
}
References v8::internal::MutablePageMetadata::InitialFlags(), and v8::internal::MemoryChunk::LARGE_PAGE.
Referenced by v8::internal::MemoryAllocator::AllocateLargePage().
next_page() [1/2]
LargePageMetadata* v8::internal::LargePageMetadata::next_page () [inline]
Definition at line 41 of file large-page-metadata.h.
                                 {
    return LargePageMetadata::cast(list_node_.next());
  }
References cast(), and v8::internal::MutablePageMetadata::list_node_.
Referenced by v8::internal::NewLargeObjectSpace::Flip(), and v8::internal::LargeObjectSpaceObjectIterator::Next().
next_page() [2/2]
const LargePageMetadata* v8::internal::LargePageMetadata::next_page () const [inline]
Definition at line 44 of file large-page-metadata.h.
                                             {
    return static_cast<const LargePageMetadata*>(list_node_.next());
  }
References v8::internal::MutablePageMetadata::list_node_.
Friends And Related Function Documentation
MemoryAllocator
friend class MemoryAllocator [friend]
Definition at line 51 of file large-page-metadata.h.
Member Data Documentation
kMaxCodePageSize
constexpr int v8::internal::LargePageMetadata::kMaxCodePageSize = 512 * MB [static], [constexpr]
Definition at line 18 of file large-page-metadata.h.
Referenced by LargePageMetadata().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/large-page-metadata.h
/mnt/V8SourceCode/src/heap/large-page-metadata-inl.h
/mnt/V8SourceCode/src/heap/large-page-metadata.cc