v8::internal::GrowableBitVector Class Reference
#include <bit-vector.h>
Public Member Functions
GrowableBitVector ()=default
GrowableBitVector (int length, Zone *zone)
bool Contains (int value) const
void Add (int value, Zone *zone)
bool IsEmpty () const
void Clear ()
int length () const
bool Equals (const GrowableBitVector &other) const
BitVector::Iterator begin () const
BitVector::Iterator end () const
Private Member Functions
bool InBitsRange (int value) const
V8_NOINLINE void Grow (int needed_value, Zone *zone)
Private Attributes
BitVector bits_
Static Private Attributes
static constexpr int kInitialLength = 1024
static constexpr int kMaxSupportedValue = (1 << 30) - 1
Detailed Description
Definition at line 292 of file bit-vector.h.
Constructor & Destructor Documentation
GrowableBitVector() [1/2]
v8::internal::GrowableBitVector::GrowableBitVector () [default]
GrowableBitVector() [2/2]
v8::internal::GrowableBitVector::GrowableBitVector (int length, Zone * zone) [inline]
Definition at line 295 of file bit-vector.h.
: bits_(length, zone) {}
Member Function Documentation
Add()
void v8::internal::GrowableBitVector::Add (int value, Zone * zone) [inline]
Definition at line 302 of file bit-vector.h.
                                  {
    if (V8_UNLIKELY(!InBitsRange(value))) Grow(value, zone);
    bits_.Add(value);
  }
References v8::internal::BitVector::Add(), bits_, Grow(), InBitsRange(), V8_UNLIKELY, and v8::internal::value.
begin()
BitVector::Iterator v8::internal::GrowableBitVector::begin () const [inline]
Definition at line 317 of file bit-vector.h.
{ return bits_.begin(); }
References v8::internal::BitVector::begin(), and bits_.
Clear()
void v8::internal::GrowableBitVector::Clear () [inline]
Definition at line 309 of file bit-vector.h.
{ bits_.Clear(); }
References bits_, and v8::internal::BitVector::Clear().
Contains()
bool v8::internal::GrowableBitVector::Contains (int value) const [inline]
Definition at line 297 of file bit-vector.h.
                                 {
    if (!InBitsRange(value)) return false;
    return bits_.Contains(value);
  }
References bits_, v8::internal::BitVector::Contains(), InBitsRange(), and v8::internal::value.
end()
BitVector::Iterator v8::internal::GrowableBitVector::end () const [inline]
Definition at line 319 of file bit-vector.h.
{ return bits_.end(); }
References bits_, and v8::internal::BitVector::end().
Equals()
bool v8::internal::GrowableBitVector::Equals (const GrowableBitVector & other) const [inline]
Definition at line 313 of file bit-vector.h.
                                                    {
    return length() == other.length() && bits_.Equals(other.bits_);
  }
References bits_, v8::internal::BitVector::Equals(), and length().
Referenced by v8::internal::SafepointTableBuilder::RemoveDuplicates().
Grow()
V8_NOINLINE void v8::internal::GrowableBitVector::Grow (int needed_value, Zone * zone) [inline], [private]
Definition at line 330 of file bit-vector.h.
                                                      {
    DCHECK(!InBitsRange(needed_value));
    // Ensure that {RoundUpToPowerOfTwo32} does not overflow {int} range.
    CHECK_GE(kMaxSupportedValue, needed_value);
    int new_length = std::max(
        kInitialLength, static_cast<int>(base::bits::RoundUpToPowerOfTwo32(
                            static_cast<uint32_t>(needed_value + 1))));
    bits_.Resize(new_length, zone);
  }
References bits_, CHECK_GE, v8::internal::DCHECK(), InBitsRange(), kInitialLength, kMaxSupportedValue, and v8::internal::BitVector::Resize().
Referenced by Add().
InBitsRange()
bool v8::internal::GrowableBitVector::InBitsRange (int value) const [inline], [private]
Definition at line 328 of file bit-vector.h.
{ return bits_.length() > value; }
References bits_, v8::internal::BitVector::length(), and v8::internal::value.
Referenced by Add(), Contains(), and Grow().
IsEmpty()
bool v8::internal::GrowableBitVector::IsEmpty () const [inline]
Definition at line 307 of file bit-vector.h.
{ return bits_.IsEmpty(); }
References bits_, and v8::internal::BitVector::IsEmpty().
length()
int v8::internal::GrowableBitVector::length () const [inline]
Definition at line 311 of file bit-vector.h.
{ return bits_.length(); }
References bits_, and v8::internal::BitVector::length().
Referenced by Equals().
Member Data Documentation
bits_
BitVector v8::internal::GrowableBitVector::bits_ [private]
Definition at line 340 of file bit-vector.h.
Referenced by Add(), begin(), Clear(), Contains(), end(), Equals(), Grow(), InBitsRange(), IsEmpty(), and length().
kInitialLength
constexpr int v8::internal::GrowableBitVector::kInitialLength = 1024 [static], [constexpr], [private]
Definition at line 322 of file bit-vector.h.
Referenced by Grow().
kMaxSupportedValue
constexpr int v8::internal::GrowableBitVector::kMaxSupportedValue = (1 << 30) - 1 [static], [constexpr], [private]
Definition at line 326 of file bit-vector.h.
Referenced by Grow().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/bit-vector.h