cppgc::internal::RawHeap Class Reference
#include <raw-heap.h>
Public Types
enum class RegularSpaceType : uint8_t {
kNormal1
, kNormal2
, kNormal3
, kNormal4
,
kLarge
 }
using Spaces = std::vector< std::unique_ptr< BaseSpace > >
using iterator = Spaces::iterator
using const_iterator = Spaces::const_iterator
Public Member Functions
RawHeap (HeapBase *heap, const std::vector< std::unique_ptr< CustomSpaceBase >> &custom_spaces)
RawHeap (const RawHeap &)=delete
RawHeap & operator= (const RawHeap &)=delete
~RawHeap ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator custom_begin ()
iterator custom_end ()
size_t size () const
BaseSpace * Space (RegularSpaceType type)
const BaseSpace * Space (RegularSpaceType space) const
BaseSpace * CustomSpace (CustomSpaceIndex space_index)
const BaseSpace * CustomSpace (CustomSpaceIndex space_index) const
HeapBase * heap ()
const HeapBase * heap () const
Static Public Attributes
static constexpr size_t kNumberOfRegularSpaces
Private Member Functions
size_t SpaceIndexForCustomSpace (CustomSpaceIndex space_index) const
BaseSpace * Space (size_t space_index)
const BaseSpace * Space (size_t space_index) const
Private Attributes
HeapBase * main_heap_
Spaces spaces_
Detailed Description
Definition at line 23 of file raw-heap.h.
Member Typedef Documentation
const_iterator
using cppgc::internal::RawHeap::const_iterator = Spaces::const_iterator
Definition at line 48 of file raw-heap.h.
iterator
using cppgc::internal::RawHeap::iterator = Spaces::iterator
Definition at line 47 of file raw-heap.h.
Spaces
using cppgc::internal::RawHeap::Spaces = std::vector<std::unique_ptr<BaseSpace> >
Definition at line 46 of file raw-heap.h.
Member Enumeration Documentation
RegularSpaceType
enum cppgc::internal::RawHeap::RegularSpaceType : uint8_t [strong]
Enumerator
kNormal1
kNormal2
kNormal3
kNormal4
kLarge
Definition at line 35 of file raw-heap.h.
                              : uint8_t {
    kNormal1,
    kNormal2,
    kNormal3,
    kNormal4,
    kLarge,
  };
Constructor & Destructor Documentation
RawHeap() [1/2]
cppgc::internal::RawHeap::RawHeap (HeapBase * heap, const std::vector< std::unique_ptr< CustomSpaceBase >> & custom_spaces)
Definition at line 15 of file raw-heap.cc.
    : main_heap_(heap) {
  size_t i = 0;
  for (; i < static_cast<size_t>(RegularSpaceType::kLarge); ++i) {
    spaces_.push_back(std::make_unique<NormalPageSpace>(this, i, false));
  }
  spaces_.push_back(std::make_unique<LargePageSpace>(
      this, static_cast<size_t>(RegularSpaceType::kLarge)));
  DCHECK_EQ(kNumberOfRegularSpaces, spaces_.size());
  for (size_t j = 0; j < custom_spaces.size(); j++) {
    spaces_.push_back(std::make_unique<NormalPageSpace>(
        this, kNumberOfRegularSpaces + j, custom_spaces[j]->IsCompactable()));
  }
}
References DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kLarge, kNumberOfRegularSpaces, and spaces_.
RawHeap() [2/2]
cppgc::internal::RawHeap::RawHeap (const RawHeap &) [delete]
 RawHeap()
cppgc::internal::RawHeap::~RawHeap () [default]
Member Function Documentation
begin() [1/2]
iterator cppgc::internal::RawHeap::begin () [inline]
Definition at line 59 of file raw-heap.h.
{ return spaces_.begin(); }
begin() [2/2]
const_iterator cppgc::internal::RawHeap::begin () const [inline]
Definition at line 60 of file raw-heap.h.
{ return spaces_.begin(); }
custom_begin()
iterator cppgc::internal::RawHeap::custom_begin () [inline]
Definition at line 64 of file raw-heap.h.
{ return std::next(begin(), kNumberOfRegularSpaces); }
References v8::internal::compiler::begin().
custom_end()
iterator cppgc::internal::RawHeap::custom_end () [inline]
Definition at line 65 of file raw-heap.h.
{ return end(); }
References v8::internal::compiler::end().
CustomSpace() [1/2]
BaseSpace* cppgc::internal::RawHeap::CustomSpace (CustomSpaceIndex space_index) [inline]
Definition at line 78 of file raw-heap.h.
                                                       {
    return Space(SpaceIndexForCustomSpace(space_index));
  }
Referenced by cppgc::internal::ObjectAllocator::AllocateObject(), CustomSpace(), and v8::internal::anonymous_namespace{cpp-heap.cc}::ReportCustomSpaceStatistics().
CustomSpace() [2/2]
const BaseSpace* cppgc::internal::RawHeap::CustomSpace (CustomSpaceIndex space_index) const [inline]
Definition at line 81 of file raw-heap.h.
                                                                   {
    return const_cast<RawHeap&>(*this).CustomSpace(space_index);
  }
References CustomSpace().
end() [1/2]
iterator cppgc::internal::RawHeap::end () [inline]
Definition at line 61 of file raw-heap.h.
{ return spaces_.end(); }
end() [2/2]
const_iterator cppgc::internal::RawHeap::end () const [inline]
Definition at line 62 of file raw-heap.h.
{ return spaces_.end(); }
heap() [1/2]
HeapBase* cppgc::internal::RawHeap::heap () [inline]
Definition at line 85 of file raw-heap.h.
{ return main_heap_; }
Referenced by cppgc::internal::Compactor::CompactSpacesIfEnabled(), cppgc::internal::BasePage::Destroy(), cppgc::internal::Compactor::EnableForNextGCForTesting(), cppgc::internal::Sweeper::SweeperImpl::Finish(), cppgc::internal::ObjectAllocator::in_disallow_gc_scope(), cppgc::internal::Sweeper::SweeperImpl::NotifyDone(), cppgc::internal::Sweeper::SweeperImpl::PerformSweepOnMutatorThread(), cppgc::internal::Sweeper::SweeperImpl::ScheduleConcurrentSweeping(), cppgc::internal::Sweeper::SweeperImpl::Start(), cppgc::internal::Sweeper::SweeperImpl::SweepForLargeAllocation(), cppgc::internal::Sweeper::SweeperImpl::SweepForNormalAllocation(), cppgc::internal::LargePage::TryCreate(), cppgc::internal::NormalPage::TryCreate(), and cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer().
heap() [2/2]
const HeapBase* cppgc::internal::RawHeap::heap () const [inline]
Definition at line 86 of file raw-heap.h.
{ return main_heap_; }
operator=()
RawHeap& cppgc::internal::RawHeap::operator= (const RawHeap &) [delete]
size()
size_t cppgc::internal::RawHeap::size () const [inline]
Definition at line 67 of file raw-heap.h.
{ return spaces_.size(); }
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::Run().
Space() [1/4]
const BaseSpace* cppgc::internal::RawHeap::Space (RegularSpaceType space) const [inline]
Definition at line 74 of file raw-heap.h.
                                                       {
    return const_cast<RawHeap&>(*this).Space(space);
  }
References space, and Space().
Space() [2/4]
BaseSpace* cppgc::internal::RawHeap::Space (RegularSpaceType type) [inline]
Definition at line 69 of file raw-heap.h.
                                          {
    const size_t index = static_cast<size_t>(type);
    DCHECK_GT(kNumberOfRegularSpaces, index);
    return Space(index);
  }
References DCHECK_GT, v8::internal::index, and v8::internal::tracing::type.
Referenced by cppgc::internal::ObjectAllocator::AllocateObject(), cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl(), and Space().
Space() [3/4]
BaseSpace* cppgc::internal::RawHeap::Space (size_t space_index) [inline], [private]
Definition at line 94 of file raw-heap.h.
                                       {
    DCHECK_GT(spaces_.size(), space_index);
    BaseSpace* space = spaces_[space_index].get();
    DCHECK(space);
    return space;
  }
References DCHECK, DCHECK_GT, and space.
Space() [4/4]
const BaseSpace* cppgc::internal::RawHeap::Space (size_t space_index) const [inline], [private]
Definition at line 100 of file raw-heap.h.
                                                   {
    return const_cast<RawHeap&>(*this).Space(space_index);
  }
References Space().
SpaceIndexForCustomSpace()
size_t cppgc::internal::RawHeap::SpaceIndexForCustomSpace (CustomSpaceIndex space_index) const [inline], [private]
Definition at line 89 of file raw-heap.h.
                                                                      {
    DCHECK_LT(space_index.value, spaces_.size() - kNumberOfRegularSpaces);
    return kNumberOfRegularSpaces + space_index.value;
  }
References DCHECK_LT, and cppgc::CustomSpaceIndex::value.
Member Data Documentation
kNumberOfRegularSpaces
constexpr size_t cppgc::internal::RawHeap::kNumberOfRegularSpaces [static], [constexpr]
Initial value:
=
      static_cast<size_t>(RegularSpaceType::kLarge) + 1
Definition at line 43 of file raw-heap.h.
Referenced by v8::internal::MinorGCHeapGrowing::ConfigureLimit(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::GetNormalPageSpaceName(), and RawHeap().
main_heap_
HeapBase* cppgc::internal::RawHeap::main_heap_ [private]
Definition at line 104 of file raw-heap.h.
spaces_
Spaces cppgc::internal::RawHeap::spaces_ [private]
Definition at line 105 of file raw-heap.h.
Referenced by RawHeap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/raw-heap.h
/mnt/V8SourceCode/src/heap/cppgc/raw-heap.cc