v8::internal::compiler::NamedAccess Class Reference
#include <js-operator.h>
Public Member Functions
NamedAccess (LanguageMode language_mode, NameRef name, FeedbackSource const &feedback)
NameRef name () const
LanguageMode language_mode () const
FeedbackSource const & feedback () const
Private Attributes
const NameRef name_
FeedbackSource const feedback_
LanguageMode const language_mode_
Friends
bool operator== (NamedAccess const &, NamedAccess const &)
bool operator!= (NamedAccess const &, NamedAccess const &)
size_t hash_value (NamedAccess const &)
std::ostream & operator<< (std::ostream &, NamedAccess const &)
Detailed Description
Definition at line 446 of file js-operator.h.
Constructor & Destructor Documentation
NamedAccess()
v8::internal::compiler::NamedAccess::NamedAccess (LanguageMode language_mode, NameRef name, FeedbackSource const & feedback) [inline]
Definition at line 448 of file js-operator.h.
      : name_(name), feedback_(feedback), language_mode_(language_mode) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::NamedAccess::feedback () const [inline]
Definition at line 454 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamedFromSuper(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetNamedProperty().
language_mode()
LanguageMode v8::internal::compiler::NamedAccess::language_mode () const [inline]
Definition at line 453 of file js-operator.h.
{ return language_mode_; }
References language_mode_.
name()
NameRef v8::internal::compiler::NamedAccess::name () const [inline]
Definition at line 452 of file js-operator.h.
{ return name_; }
References name_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamedFromSuper(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetNamedProperty().
Friends And Related Function Documentation
hash_value
size_t hash_value (NamedAccess const & p) [friend]
Definition at line 289 of file js-operator.cc.
                                        {
  return base::hash_combine(p.name_.object().location(), p.language_mode(),
                            FeedbackSource::Hash()(p.feedback()));
}
operator!=
bool operator!= (NamedAccess const & lhs, NamedAccess const & rhs) [friend]
Definition at line 284 of file js-operator.cc.
                                                                {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, NamedAccess const & p) [friend]
Definition at line 295 of file js-operator.cc.
                                                             {
  return os << Brief(*p.name_.object()) << ", " << p.language_mode();
}
operator==
bool operator== (NamedAccess const & lhs, NamedAccess const & rhs) [friend]
Definition at line 277 of file js-operator.cc.
                                                                {
  return lhs.name_.object().location() == rhs.name_.object().location() &&
         lhs.language_mode() == rhs.language_mode() &&
         lhs.feedback() == rhs.feedback();
}
Member Data Documentation
feedback_
FeedbackSource const v8::internal::compiler::NamedAccess::feedback_ [private]
Definition at line 458 of file js-operator.h.
Referenced by feedback().
language_mode_
LanguageMode const v8::internal::compiler::NamedAccess::language_mode_ [private]
Definition at line 459 of file js-operator.h.
Referenced by language_mode().
name_
const NameRef v8::internal::compiler::NamedAccess::name_ [private]
Definition at line 457 of file js-operator.h.
Referenced by name().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h