v8::internal::FreeListCategory Class Reference
#include <free-list.h>
Public Member Functions
void Initialize (FreeListCategoryType type)
void Unlink (FreeList *owner)
void Reset (FreeList *owner)
void RepairFreeList (Heap *heap)
void Relink (FreeList *owner)
void Free (const WritableFreeSpace &writable_free_space, FreeMode mode, FreeList *owner)
V8_EXPORT_PRIVATE Tagged< FreeSpace > PickNodeFromList (size_t minimum_size, size_t *node_size)
Tagged< FreeSpace > SearchForNodeInList (size_t minimum_size, size_t *node_size)
bool is_linked (FreeList *owner) const
bool is_empty ()
uint32_t available () const
size_t SumFreeList ()
int FreeListLength ()
template<typename Callback >
void IterateNodesForTesting (Callback callback)
Private Member Functions
void UpdateCountersAfterAllocation (size_t allocation_size)
Tagged< FreeSpace > top ()
void set_top (Tagged< FreeSpace > top)
FreeListCategory * prev ()
void set_prev (FreeListCategory *prev)
FreeListCategory * next ()
void set_next (FreeListCategory *next)
Private Attributes
FreeListCategoryType type_ = kInvalidCategory
uint32_t available_ = 0
Tagged< FreeSpace > top_
FreeListCategory * prev_ = nullptr
FreeListCategory * next_ = nullptr
Static Private Attributes
static constexpr int kVeryLongFreeList = 500
Friends
class FreeList
class FreeListManyCached
class PagedSpace
class MapSpace
Detailed Description
Definition at line 45 of file free-list.h.
Member Function Documentation
available()
uint32_t v8::internal::FreeListCategory::available () const [inline]
Definition at line 80 of file free-list.h.
{ return available_; }
References available_.
Referenced by v8::internal::FreeList::AddCategory(), v8::internal::PageMetadata::AvailableInFreeList(), v8::internal::FreeList::EvictFreeListItems(), v8::internal::PagedSpaceBase::RelinkFreeListCategories(), and v8::internal::FreeList::RemoveCategory().
Free()
void v8::internal::FreeListCategory::Free (const WritableFreeSpace & writable_free_space, FreeMode mode, FreeList * owner)
Definition at line 86 of file free-list.cc.
                                                            {
  Tagged<FreeSpace> free_space =
      Cast<FreeSpace>(HeapObject::FromAddress(writable_free_space.Address()));
  DCHECK_EQ(free_space->Size(), writable_free_space.Size());
  free_space->SetNext(writable_free_space, top());
  set_top(free_space);
  size_t size_in_bytes = writable_free_space.Size();
  available_ += size_in_bytes;
  if (mode == kLinkCategory) {
    if (is_linked(owner)) {
      owner->IncreaseAvailableBytes(size_in_bytes);
    } else {
      owner->AddCategory(this);
    }
  }
}
References v8::internal::FreeList::AddCategory(), v8::internal::WritableFreeSpace::Address(), available_, DCHECK_EQ, v8::internal::HeapObject::FromAddress(), v8::internal::FreeList::IncreaseAvailableBytes(), is_linked(), v8::internal::kLinkCategory, mode(), set_top(), v8::internal::WritableFreeSpace::Size(), and top().
Referenced by v8::internal::FreeList::Free(), and v8::internal::FreeListManyCached::Free().
FreeListLength()
int v8::internal::FreeListCategory::FreeListLength ()
Definition at line 556 of file free-list.cc.
                                     {
  int length = 0;
  Tagged<FreeSpace> cur = top();
  while (!cur.is_null()) {
    length++;
    cur = cur->next();
  }
  return length;
}
References v8::internal::Tagged< HeapObject >::is_null(), and v8::internal::length.
Referenced by v8::internal::MutablePageMetadata::ComputeFreeListsLength(), and v8::internal::Heap::PrintFreeListsStats().
Initialize()
void v8::internal::FreeListCategory::Initialize (FreeListCategoryType type) [inline]
Definition at line 47 of file free-list.h.
                                             {
    type_ = type;
    available_ = 0;
    prev_ = nullptr;
    next_ = nullptr;
  }
References available_, next_, prev_, v8::internal::tracing::type, and type_.
Referenced by v8::internal::PageMetadata::InitializeFreeListCategories().
is_empty()
bool v8::internal::FreeListCategory::is_empty () [inline]
Definition at line 79 of file free-list.h.
{ return top().is_null(); }
References top().
Referenced by v8::internal::FreeList::AddCategory(), v8::internal::FreeList::IsEmpty(), v8::internal::FreeList::ResetForNonBlackAllocatedPages(), v8::internal::FreeList::SearchForNodeInList(), and v8::internal::FreeList::TryFindNodeIn().
is_linked()
bool v8::internal::FreeListCategory::is_linked (FreeList * owner) const [inline]
Definition at line 17 of file free-list-inl.h.
                                                      {
  return prev_ != nullptr || next_ != nullptr ||
         owner->categories_[type_] == this;
}
References v8::internal::FreeList::categories_, next_, prev_, and type_.
Referenced by Free(), Relink(), v8::internal::FreeList::RemoveCategory(), Unlink(), and v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage().
IterateNodesForTesting()
template<typename Callback >
void v8::internal::FreeListCategory::IterateNodesForTesting (Callback callback) [inline]
Definition at line 86 of file free-list.h.
                                                 {
    for (Tagged<FreeSpace> cur_node = top(); !cur_node.is_null();
         cur_node = cur_node->next()) {
      callback(cur_node);
    }
  }
References top().
next()
FreeListCategory* v8::internal::FreeListCategory::next () [inline], [private]
Definition at line 106 of file free-list.h.
{ return next_; }
References next_.
Referenced by v8::internal::FreeList::ForAllFreeListCategories(), v8::internal::FreeList::FreeListCategoryIterator::Next(), v8::internal::FreeList::RemoveCategory(), and set_next().
PickNodeFromList()
Tagged< FreeSpace > v8::internal::FreeListCategory::PickNodeFromList (size_t minimum_size, size_t * node_size)
Definition at line 35 of file free-list.cc.
                                                                        {
  Tagged<FreeSpace> node = top();
  DCHECK(!node.is_null());
  DCHECK(MemoryChunk::FromHeapObject(node)->CanAllocate());
  if (static_cast<size_t>(node->Size()) < minimum_size) {
    *node_size = 0;
    return Tagged<FreeSpace>();
  }
  set_top(node->next());
  *node_size = node->Size();
  UpdateCountersAfterAllocation(*node_size);
  return node;
}
References v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanAllocate(), v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::Tagged< HeapObject >::is_null(), set_top(), top(), and UpdateCountersAfterAllocation().
Referenced by v8::internal::FreeList::TryFindNodeIn().
prev()
FreeListCategory* v8::internal::FreeListCategory::prev () [inline], [private]
Definition at line 104 of file free-list.h.
{ return prev_; }
References prev_.
Referenced by v8::internal::FreeList::RemoveCategory(), and set_prev().
Relink()
void v8::internal::FreeListCategory::Relink (FreeList * owner)
Definition at line 118 of file free-list.cc.
                                             {
  DCHECK(!is_linked(owner));
  owner->AddCategory(this);
}
References v8::internal::FreeList::AddCategory(), v8::internal::DCHECK(), and is_linked().
Referenced by v8::internal::PagedSpaceBase::RelinkFreeListCategories().
RepairFreeList()
void v8::internal::FreeListCategory::RepairFreeList (Heap * heap)
Definition at line 104 of file free-list.cc.
                                                {
  Tagged<Map> free_space_map = ReadOnlyRoots(heap).free_space_map();
  Tagged<FreeSpace> n = top();
  while (!n.is_null()) {
    ObjectSlot map_slot = n->map_slot();
    if (map_slot.contains_map_value(kNullAddress)) {
      map_slot.store_map(free_space_map);
    } else {
      DCHECK(map_slot.contains_map_value(free_space_map.ptr()));
    }
    n = n->next();
  }
}
References v8::internal::FullObjectSlot::contains_map_value(), v8::internal::DCHECK(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::kNullAddress, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FullObjectSlot::store_map(), and top().
Referenced by v8::internal::FreeList::RepairLists().
Reset()
void v8::internal::FreeListCategory::Reset (FreeList * owner)
Definition at line 29 of file free-list.cc.
                                            {
  Unlink(owner);
  set_top(Tagged<FreeSpace>());
  available_ = 0;
}
References available_, set_top(), and Unlink().
Referenced by v8::internal::FreeList::EvictFreeListItems(), v8::internal::FreeList::Reset(), and v8::internal::FreeList::ResetForNonBlackAllocatedPages().
SearchForNodeInList()
Tagged< FreeSpace > v8::internal::FreeListCategory::SearchForNodeInList (size_t minimum_size, size_t * node_size)
Definition at line 50 of file free-list.cc.
                                                                           {
  Tagged<FreeSpace> prev_non_evac_node;
  for (Tagged<FreeSpace> cur_node = top(); !cur_node.is_null();
       cur_node = cur_node->next()) {
    DCHECK(MemoryChunk::FromHeapObject(cur_node)->CanAllocate());
    size_t size = cur_node->size(kRelaxedLoad);
    if (size >= minimum_size) {
      DCHECK_GE(available_, size);
      UpdateCountersAfterAllocation(size);
      if (cur_node == top()) {
        set_top(cur_node->next());
      }
      if (!prev_non_evac_node.is_null()) {
        if (MemoryChunk::FromHeapObject(prev_non_evac_node)->executable()) {
          WritableJitPage jit_page(prev_non_evac_node->address(),
                                   prev_non_evac_node->Size());
          WritableFreeSpace free_space = jit_page.FreeRange(
              prev_non_evac_node->address(), prev_non_evac_node->Size());
          prev_non_evac_node->SetNext(free_space, cur_node->next());
        } else {
          prev_non_evac_node->SetNext(
              WritableFreeSpace::ForNonExecutableMemory(
                  prev_non_evac_node->address(), prev_non_evac_node->Size()),
              cur_node->next());
        }
      }
      *node_size = size;
      return cur_node;
    }
    prev_non_evac_node = cur_node;
  }
  return Tagged<FreeSpace>();
}
References v8::internal::Tagged< HeapObject >::address(), available_, v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanAllocate(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::WritableFreeSpace::ForNonExecutableMemory(), v8::internal::WritableJitPage::FreeRange(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::Tagged< HeapObject >::is_null(), v8::kRelaxedLoad, set_top(), size(), top(), and UpdateCountersAfterAllocation().
Referenced by v8::internal::FreeList::SearchForNodeInList().
set_next()
void v8::internal::FreeListCategory::set_next (FreeListCategory * next) [inline], [private]
Definition at line 107 of file free-list.h.
{ next_ = next; }
References next(), and next_.
Referenced by v8::internal::FreeList::AddCategory(), v8::internal::FreeList::RemoveCategory(), and Unlink().
set_prev()
void v8::internal::FreeListCategory::set_prev (FreeListCategory * prev) [inline], [private]
Definition at line 105 of file free-list.h.
{ prev_ = prev; }
References prev(), and prev_.
Referenced by v8::internal::FreeList::AddCategory(), v8::internal::FreeList::RemoveCategory(), and Unlink().
set_top()
void v8::internal::FreeListCategory::set_top (Tagged< FreeSpace > top) [inline], [private]
Definition at line 103 of file free-list.h.
{ top_ = top; }
References top(), and top_.
Referenced by Free(), PickNodeFromList(), Reset(), and SearchForNodeInList().
SumFreeList()
size_t v8::internal::FreeListCategory::SumFreeList ()
Definition at line 539 of file free-list.cc.
                                     {
  size_t sum = 0;
  Tagged<FreeSpace> cur = top();
  while (!cur.is_null()) {
    // We can't use "cur->map()" here because both cur's map and the
    // root can be null during bootstrapping.
    DCHECK(
        cur->map_slot().contains_map_value(PageMetadata::FromHeapObject(cur)
                                               ->heap()
                                               ->isolate()
                                               ->root(RootIndex::kFreeSpaceMap)
                                               .ptr()));
    sum += cur->size(kRelaxedLoad);
    cur = cur->next();
  }
  return sum;
}
References DCHECK, v8::internal::Tagged< HeapObject >::is_null(), and v8::kRelaxedLoad.
Referenced by v8::internal::Heap::PrintFreeListsStats().
top()
Tagged<FreeSpace> v8::internal::FreeListCategory::top () [inline], [private]
Definition at line 102 of file free-list.h.
{ return top_; }
References top_.
Referenced by Free(), v8::internal::FreeList::GetPageForCategoryType(), is_empty(), IterateNodesForTesting(), PickNodeFromList(), RepairFreeList(), SearchForNodeInList(), set_top(), and Unlink().
Unlink()
void v8::internal::FreeListCategory::Unlink (FreeList * owner)
Definition at line 21 of file free-list.cc.
                                             {
  if (is_linked(owner) && !top().is_null()) {
    owner->DecreaseAvailableBytes(available_);
  }
  set_prev(nullptr);
  set_next(nullptr);
}
References available_, v8::internal::FreeList::DecreaseAvailableBytes(), is_linked(), set_next(), set_prev(), and top().
Referenced by Reset().
UpdateCountersAfterAllocation()
void v8::internal::FreeListCategory::UpdateCountersAfterAllocation (size_t allocation_size) [inline], [private]
Definition at line 22 of file free-list-inl.h.
                                                                           {
  available_ -= allocation_size;
}
References available_.
Referenced by PickNodeFromList(), and SearchForNodeInList().
Friends And Related Function Documentation
FreeList
friend class FreeList [friend]
Definition at line 122 of file free-list.h.
FreeListManyCached
friend class FreeListManyCached [friend]
Definition at line 123 of file free-list.h.
MapSpace
friend class MapSpace [friend]
Definition at line 125 of file free-list.h.
PagedSpace
friend class PagedSpace [friend]
Definition at line 124 of file free-list.h.
Member Data Documentation
available_
uint32_t v8::internal::FreeListCategory::available_ = 0 [private]
Definition at line 114 of file free-list.h.
Referenced by available(), Free(), Initialize(), Reset(), SearchForNodeInList(), Unlink(), and UpdateCountersAfterAllocation().
kVeryLongFreeList
constexpr int v8::internal::FreeListCategory::kVeryLongFreeList = 500 [static], [constexpr], [private]
Definition at line 96 of file free-list.h.
next_
FreeListCategory* v8::internal::FreeListCategory::next_ = nullptr [private]
Definition at line 120 of file free-list.h.
Referenced by Initialize(), is_linked(), next(), and set_next().
prev_
FreeListCategory* v8::internal::FreeListCategory::prev_ = nullptr [private]
Definition at line 119 of file free-list.h.
Referenced by Initialize(), is_linked(), prev(), and set_prev().
top_
Tagged<FreeSpace> v8::internal::FreeListCategory::top_ [private]
Definition at line 117 of file free-list.h.
Referenced by set_top(), and top().
type_
FreeListCategoryType v8::internal::FreeListCategory::type_ = kInvalidCategory [private]
Definition at line 110 of file free-list.h.
Referenced by v8::internal::FreeList::AddCategory(), v8::internal::FreeListManyCached::AddCategory(), Initialize(), is_linked(), v8::internal::FreeList::RemoveCategory(), and v8::internal::FreeListManyCached::RemoveCategory().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/free-list.h
/mnt/V8SourceCode/src/heap/free-list-inl.h
/mnt/V8SourceCode/src/heap/free-list.cc