v8::internal::JSArray Class Reference
#include <js-array.h>
Public Member Functions
Tagged< Number > length (PtrComprCageBase cage_base, AcquireLoadTag tag) const =delete
void set_length (Tagged< Number > value, ReleaseStoreTag tag, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)=delete
void set_length (Tagged< Smi > length)
bool SetLengthWouldNormalize (uint32_t new_length)
bool HasArrayPrototype (Isolate *isolate)
Static Public Member Functions
static bool MayHaveReadOnlyLength (Tagged< Map > js_array_map)
static bool HasReadOnlyLength (DirectHandle< JSArray > array)
V8_NOINLINE static V8_PRESERVE_MOST bool HasReadOnlyLengthSlowPath (DirectHandle< JSArray > array)
static bool WouldChangeReadOnlyLength (DirectHandle< JSArray > array, uint32_t index)
static V8_EXPORT_PRIVATE void Initialize (Isolate *isolate, DirectHandle< JSArray > array, int capacity, int length=0)
static bool SetLengthWouldNormalize (Heap *heap, uint32_t new_length)
static V8_EXPORT_PRIVATE Maybe< bool > SetLength (Isolate *isolate, DirectHandle< JSArray > array, uint32_t length)
static void SetContent (Isolate *isolate, DirectHandle< JSArray > array, DirectHandle< FixedArrayBase > storage)
static V8_WARN_UNUSED_RESULT Maybe< bool > DefineOwnProperty (Isolate *isolate, DirectHandle< JSArray > o, DirectHandle< Object > name, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static bool AnythingToArrayLength (Isolate *isolate, DirectHandle< Object > length_object, uint32_t *output)
static V8_WARN_UNUSED_RESULT Maybe< bool > ArraySetLength (Isolate *isolate, DirectHandle< JSArray > a, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static Address ArrayJoinConcatToSequentialString (Isolate *isolate, Address raw_fixed_array, intptr_t length, Address raw_separator, Address raw_dest)
Static Public Attributes
static const int kPreallocatedArrayElements = 4
static const int kLengthDescriptorIndex = 0
static const int kMaxCopyElements = 100
static constexpr uint32_t kMaxArrayLength = JSObject::kMaxElementCount
static constexpr uint32_t kMaxArrayIndex = JSObject::kMaxElementIndex
static constexpr uint32_t kMaxFastArrayLength
static const uint32_t kMinJoinStackSize = 2
static const int kInitialMaxFastElementArray
Detailed Description
Definition at line 25 of file js-array.h.
Member Function Documentation
AnythingToArrayLength()
bool v8::internal::JSArray::AnythingToArrayLength (Isolate * isolate, DirectHandle< Object > length_object, uint32_t * output) [static]
Definition at line 3222 of file objects.cc.
                                                      {
  // Fast path: check numbers and strings that can be converted directly
  // and unobservably.
  if (Object::ToArrayLength(*length_object, output)) return true;
  if (IsString(*length_object) &&
      Cast<String>(length_object)->AsArrayIndex(output)) {
    return true;
  }
  // Slow path: follow steps in ES6 9.4.2.4 "ArraySetLength".
  // 3. Let newLen be ToUint32(Desc.[[Value]]).
  DirectHandle<Number> uint32_v;
  if (!Object::ToUint32(isolate, length_object).ToHandle(&uint32_v)) {
    // 4. ReturnIfAbrupt(newLen).
    return false;
  }
  // 5. Let numberLen be ToNumber(Desc.[[Value]]).
  DirectHandle<Number> number_v;
  if (!Object::ToNumber(isolate, length_object).ToHandle(&number_v)) {
    // 6. ReturnIfAbrupt(newLen).
    return false;
  }
  // 7. If newLen != numberLen, throw a RangeError exception.
  if (Object::NumberValue(*uint32_v) != Object::NumberValue(*number_v)) {
    DirectHandle<Object> exception =
        isolate->factory()->NewRangeError(MessageTemplate::kInvalidArrayLength);
    isolate->Throw(*exception);
    return false;
  }
  CHECK(Object::ToArrayLength(*uint32_v, output));
  return true;
}
References CHECK, v8::internal::Isolate::factory(), v8::internal::Object::NumberValue(), v8::internal::Isolate::Throw(), v8::internal::Object::ToArrayLength(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::Value::ToNumber(), and v8::internal::Object::ToUint32().
Referenced by ArraySetLength().
ArrayJoinConcatToSequentialString()
Address v8::internal::JSArray::ArrayJoinConcatToSequentialString (Isolate * isolate, Address raw_fixed_array, intptr_t length, Address raw_separator, Address raw_dest) [static]
Definition at line 4284 of file objects.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  DisallowJavascriptExecution no_js(isolate);
  Tagged<FixedArray> fixed_array =
      Cast<FixedArray>(Tagged<Object>(raw_fixed_array));
  Tagged<String> separator = Cast<String>(Tagged<Object>(raw_separator));
  Tagged<String> dest = Cast<String>(Tagged<Object>(raw_dest));
  DCHECK(IsFixedArray(fixed_array));
  DCHECK(StringShape(dest).IsSequentialOneByte() ||
         StringShape(dest).IsSequentialTwoByte());
  if (StringShape(dest).IsSequentialOneByte()) {
    WriteFixedArrayToFlat(fixed_array, static_cast<int>(length), separator,
                          Cast<SeqOneByteString>(dest)->GetChars(no_gc),
                          dest->length());
  } else {
    DCHECK(StringShape(dest).IsSequentialTwoByte());
    WriteFixedArrayToFlat(fixed_array, static_cast<int>(length), separator,
                          Cast<SeqTwoByteString>(dest)->GetChars(no_gc),
                          dest->length());
  }
  return dest.ptr();
}
References v8::internal::DCHECK(), length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::separator, and v8::internal::anonymous_namespace{objects.cc}::WriteFixedArrayToFlat().
ArraySetLength()
Maybe< bool > v8::internal::JSArray::ArraySetLength (Isolate * isolate, DirectHandle< JSArray > a, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 3258 of file objects.cc.
                                                                     {
  // 1. If the [[Value]] field of Desc is absent, then
  if (!desc->has_value()) {
    // 1a. Return OrdinaryDefineOwnProperty(A, "length", Desc).
    return OrdinaryDefineOwnProperty(
        isolate, a, isolate->factory()->length_string(), desc, should_throw);
  }
  // 2. Let newLenDesc be a copy of Desc.
  // (Actual copying is not necessary.)
  PropertyDescriptor* new_len_desc = desc;
  // 3. - 7. Convert Desc.[[Value]] to newLen.
  uint32_t new_len = 0;
  if (!AnythingToArrayLength(isolate, desc->value(), &new_len)) {
    DCHECK(isolate->has_exception());
    return Nothing<bool>();
  }
  // 8. Set newLenDesc.[[Value]] to newLen.
  // (Done below, if needed.)
  // 9. Let oldLenDesc be OrdinaryGetOwnProperty(A, "length").
  PropertyDescriptor old_len_desc;
  Maybe<bool> success = GetOwnPropertyDescriptor(
      isolate, a, isolate->factory()->length_string(), &old_len_desc);
  // 10. (Assert)
  DCHECK(success.FromJust());
  USE(success);
  // 11. Let oldLen be oldLenDesc.[[Value]].
  uint32_t old_len = 0;
  CHECK(Object::ToArrayLength(*old_len_desc.value(), &old_len));
  // 12. If newLen >= oldLen, then
  if (new_len >= old_len) {
    // 8. Set newLenDesc.[[Value]] to newLen.
    // 12a. Return OrdinaryDefineOwnProperty(A, "length", newLenDesc).
    new_len_desc->set_value(isolate->factory()->NewNumberFromUint(new_len));
    return OrdinaryDefineOwnProperty(isolate, a,
                                     isolate->factory()->length_string(),
                                     new_len_desc, should_throw);
  }
  // 13. If oldLenDesc.[[Writable]] is false, return false.
  if (!old_len_desc.writable() ||
      // Also handle the {configurable: true} and enumerable changes
      // since we later use JSArray::SetLength instead of
      // OrdinaryDefineOwnProperty to change the length,
      // and it doesn't have access to the descriptor anymore.
      new_len_desc->configurable() ||
      (new_len_desc->has_enumerable() &&
       (old_len_desc.enumerable() != new_len_desc->enumerable()))) {
    RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                   NewTypeError(MessageTemplate::kRedefineDisallowed,
                                isolate->factory()->length_string()));
  }
  // 14. If newLenDesc.[[Writable]] is absent or has the value true,
  // let newWritable be true.
  bool new_writable = false;
  if (!new_len_desc->has_writable() || new_len_desc->writable()) {
    new_writable = true;
  } else {
    // 15. Else,
    // 15a. Need to defer setting the [[Writable]] attribute to false in case
    // any elements cannot be deleted.
    // 15b. Let newWritable be false. (It's initialized as "false" anyway.)
    // 15c. Set newLenDesc.[[Writable]] to true.
    // (Not needed.)
  }
  // Most of steps 16 through 19 is implemented by JSArray::SetLength.
  MAYBE_RETURN(JSArray::SetLength(isolate, a, new_len), Nothing<bool>());
  // Steps 19d-ii, 20.
  if (!new_writable) {
    PropertyDescriptor readonly;
    readonly.set_writable(false);
    success = OrdinaryDefineOwnProperty(isolate, a,
                                        isolate->factory()->length_string(),
                                        &readonly, should_throw);
    DCHECK(success.FromJust());
    USE(success);
  }
  uint32_t actual_new_len = 0;
  CHECK(Object::ToArrayLength(a->length(), &actual_new_len));
  // Steps 19d-v, 21. Return false if there were non-deletable elements.
  bool result = actual_new_len == new_len;
  if (!result) {
    RETURN_FAILURE(
        isolate, GetShouldThrow(isolate, should_throw),
        NewTypeError(MessageTemplate::kStrictDeleteProperty,
                     isolate->factory()->NewNumberFromUint(actual_new_len - 1),
                     a));
  }
  return Just(result);
}
References AnythingToArrayLength(), CHECK, v8::internal::PropertyDescriptor::configurable(), v8::internal::DCHECK(), v8::internal::PropertyDescriptor::enumerable(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::GetShouldThrow(), v8::internal::PropertyDescriptor::has_enumerable(), v8::internal::Isolate::has_exception(), v8::internal::PropertyDescriptor::has_value(), v8::internal::PropertyDescriptor::has_writable(), v8::Just(), MAYBE_RETURN, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::base::internal::result, RETURN_FAILURE, v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), SetLength(), v8::internal::Object::ToArrayLength(), USE, v8::internal::PropertyDescriptor::value(), and v8::internal::PropertyDescriptor::writable().
Referenced by DefineOwnProperty().
DefineOwnProperty()
Maybe< bool > v8::internal::JSArray::DefineOwnProperty (Isolate * isolate, DirectHandle< JSArray > o, DirectHandle< Object > name, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 3154 of file objects.cc.
                                                                        {
  if (IsName(*name)) {
    name = isolate->factory()->InternalizeName(Cast<Name>(name));
  }
  // 1. Assert: IsPropertyKey(P) is true. ("P" is |name|.)
  // 2. If P is "length", then:
  if (*name == ReadOnlyRoots(isolate).length_string()) {
    // 2a. Return ArraySetLength(A, Desc).
    return ArraySetLength(isolate, o, desc, should_throw);
  }
  // 3. Else if P is an array index, then:
  uint32_t index = 0;
  if (PropertyKeyToArrayIndex(name, &index)) {
    // 3a. Let oldLenDesc be OrdinaryGetOwnProperty(A, "length").
    PropertyDescriptor old_len_desc;
    Maybe<bool> success = GetOwnPropertyDescriptor(
        isolate, o, isolate->factory()->length_string(), &old_len_desc);
    // 3b. (Assert)
    DCHECK(success.FromJust());
    USE(success);
    // 3c. Let oldLen be oldLenDesc.[[Value]].
    uint32_t old_len = 0;
    CHECK(Object::ToArrayLength(*old_len_desc.value(), &old_len));
    // 3d. Let index be ToUint32(P).
    // (Already done above.)
    // 3e. (Assert)
    // 3f. If index >= oldLen and oldLenDesc.[[Writable]] is false,
    // return false.
    if (index >= old_len && old_len_desc.has_writable() &&
        !old_len_desc.writable()) {
      RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                     NewTypeError(MessageTemplate::kDefineDisallowed, name));
    }
    // 3g. Let succeeded be OrdinaryDefineOwnProperty(A, P, Desc).
    Maybe<bool> succeeded =
        OrdinaryDefineOwnProperty(isolate, o, name, desc, should_throw);
    // 3h. Assert: succeeded is not an abrupt completion.
    // In our case, if should_throw == kThrowOnError, it can be!
    // 3i. If succeeded is false, return false.
    if (succeeded.IsNothing() || !succeeded.FromJust()) return succeeded;
    // 3j. If index >= oldLen, then:
    if (index >= old_len) {
      // 3j i. Set oldLenDesc.[[Value]] to index + 1.
      old_len_desc.set_value(isolate->factory()->NewNumberFromUint(index + 1));
      // 3j ii. Let succeeded be
      // OrdinaryDefineOwnProperty(A, "length", oldLenDesc).
      succeeded = OrdinaryDefineOwnProperty(isolate, o,
                                            isolate->factory()->length_string(),
                                            &old_len_desc, should_throw);
      // 3j iii. Assert: succeeded is true.
      DCHECK(succeeded.FromJust());
      USE(succeeded);
    }
    // 3k. Return true.
    return Just(true);
  }
  // 4. Return OrdinaryDefineOwnProperty(A, P, Desc).
  return OrdinaryDefineOwnProperty(isolate, o, name, desc, should_throw);
}
References ArraySetLength(), CHECK, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::GetShouldThrow(), v8::internal::PropertyDescriptor::has_writable(), v8::internal::index, v8::Maybe< T >::IsNothing(), v8::Just(), v8::internal::name, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::PropertyKeyToArrayIndex(), RETURN_FAILURE, v8::internal::PropertyDescriptor::set_value(), v8::internal::Object::ToArrayLength(), USE, v8::internal::PropertyDescriptor::value(), and v8::internal::PropertyDescriptor::writable().
Referenced by v8::internal::JSReceiver::DefineOwnProperty(), and v8::internal::Genesis::InstallABunchOfRandomThings().
HasArrayPrototype()
bool v8::internal::JSArray::HasArrayPrototype (Isolate * isolate) [inline]
Definition at line 76 of file js-array-inl.h.
                                                {
  return map()->prototype() == *isolate->initial_array_prototype();
}
HasReadOnlyLength()
bool v8::internal::JSArray::HasReadOnlyLength (DirectHandle< JSArray > array) [inline], [static]
Definition at line 1355 of file objects-inl.h.
                                                           {
  Tagged<Map> map = array->map();
  // If map guarantees that there can't be a read-only length, we are done.
  if (!MayHaveReadOnlyLength(map)) return false;
  return V8_UNLIKELY(HasReadOnlyLengthSlowPath(array));
}
References HasReadOnlyLengthSlowPath(), MayHaveReadOnlyLength(), and V8_UNLIKELY.
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-array.cc}::CanUseFastArrayModification(), v8::internal::anonymous_namespace{builtins-array.cc}::SetLengthProperty(), and v8::internal::KeyedStoreIC::Store().
HasReadOnlyLengthSlowPath()
bool v8::internal::JSArray::HasReadOnlyLengthSlowPath (DirectHandle< JSArray > array) [static]
Definition at line 2445 of file js-objects.cc.
                                                                   {
  // Look at the object.
  Isolate* isolate = Isolate::Current();
  LookupIterator it(isolate, array, isolate->factory()->length_string(), array,
                    LookupIterator::OWN_SKIP_INTERCEPTOR);
  CHECK_EQ(LookupIterator::ACCESSOR, it.state());
  return it.IsReadOnly();
}
References v8::internal::LookupIterator::ACCESSOR, CHECK_EQ, v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::IsReadOnly(), v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, and v8::internal::LookupIterator::state().
Referenced by HasReadOnlyLength().
Initialize()
void v8::internal::JSArray::Initialize (Isolate * isolate, DirectHandle< JSArray > array, int capacity, int length = 0) [static]
Definition at line 4862 of file objects.cc.
                                                   {
  DCHECK_GE(capacity, 0);
  isolate->factory()->NewJSArrayStorage(
      array, length, capacity,
      ArrayStorageAllocationMode::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE);
}
References DCHECK_GE, v8::internal::Isolate::factory(), v8::internal::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE, v8::internal::length, and v8::internal::Factory::NewJSArrayStorage().
Referenced by v8::internal::ArrayConstructInitializeElements().
length()
Tagged< Number > v8::internal::JSArray::length (PtrComprCageBase cage_base, AcquireLoadTag tag) const [delete]
Definition at line 35 of file js-array-inl.h.
                                                         {
  return TaggedField<Number, kLengthOffset>::Relaxed_Load(cage_base, *this);
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
Referenced by ArrayJoinConcatToSequentialString(), and set_length().
MayHaveReadOnlyLength()
bool v8::internal::JSArray::MayHaveReadOnlyLength (Tagged< Map > js_array_map) [inline], [static]
Definition at line 1337 of file objects-inl.h.
                                                            {
  DCHECK(IsJSArrayMap(js_array_map));
  if (V8_UNLIKELY(
          js_array_map->instance_descriptors()->number_of_descriptors() == 0)) {
    return true;
  }
  DCHECK(!js_array_map->is_dictionary_map());
  // Fast path: "length" is the first fast property of arrays with non
  // dictionary properties. Since it's not configurable, it's guaranteed to be
  // the first in the descriptor array.
  InternalIndex first(0);
  DCHECK(js_array_map->instance_descriptors()->GetKey(first) ==
         GetReadOnlyRoots().length_string());
  return V8_UNLIKELY(
      js_array_map->instance_descriptors()->GetDetails(first).IsReadOnly());
}
References v8::internal::DCHECK(), v8::internal::GetReadOnlyRoots(), and V8_UNLIKELY.
Referenced by HasReadOnlyLength(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
set_length() [1/2]
void v8::internal::JSArray::set_length (Tagged< Number > value, ReleaseStoreTag tag, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [delete]
Referenced by set_length().
set_length() [2/2]
void v8::internal::JSArray::set_length (Tagged< Smi > length) [inline]
Definition at line 40 of file js-array-inl.h.
                                           {
  // Don't need a write barrier for a Smi.
  set_length(Tagged<Number>(length), SKIP_WRITE_BARRIER);
}
References length(), set_length(), and v8::internal::SKIP_WRITE_BARRIER.
SetContent()
void v8::internal::JSArray::SetContent (Isolate * isolate, DirectHandle< JSArray > array, DirectHandle< FixedArrayBase > storage) [inline], [static]
Definition at line 49 of file js-array-inl.h.
                                                               {
  EnsureCanContainElements(isolate, array, storage, storage->length(),
                           ALLOW_COPIED_DOUBLE_ELEMENTS);
#ifdef DEBUG
  ReadOnlyRoots roots = GetReadOnlyRoots();
  Tagged<Map> map = storage->map();
  if (map == roots.fixed_double_array_map()) {
    DCHECK(IsDoubleElementsKind(array->GetElementsKind()));
  } else {
    DCHECK_NE(map, roots.fixed_double_array_map());
    if (IsSmiElementsKind(array->GetElementsKind())) {
      auto elems = Cast<FixedArray>(storage);
      Tagged<Object> the_hole = roots.the_hole_value();
      for (int i = 0; i < elems->length(); i++) {
        Tagged<Object> candidate = elems->get(i);
        DCHECK(IsSmi(candidate) || candidate == the_hole);
      }
    } else {
      DCHECK(IsObjectElementsKind(array->GetElementsKind()));
    }
  }
#endif // DEBUG
  array->set_elements(*storage);
  array->set_length(Smi::FromInt(storage->length()));
}
References v8::internal::ALLOW_COPIED_DOUBLE_ELEMENTS, v8::internal::DCHECK(), DCHECK_NE, v8::internal::Smi::FromInt(), v8::internal::GetReadOnlyRoots(), v8::internal::IsDoubleElementsKind(), v8::internal::IsObjectElementsKind(), v8::internal::IsSmi(), and v8::internal::IsSmiElementsKind().
Referenced by v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::wasm::GetCustomSections(), v8::internal::wasm::GetExports(), and v8::internal::wasm::GetImports().
SetLength()
Maybe< bool > v8::internal::JSArray::SetLength (Isolate * isolate, DirectHandle< JSArray > array, uint32_t length) [static]
Definition at line 4870 of file objects.cc.
                                                    {
  if (array->SetLengthWouldNormalize(new_length)) {
    JSObject::NormalizeElements(isolate, array);
  }
  return array->GetElementsAccessor()->SetLength(isolate, array, new_length);
}
References v8::internal::JSObject::NormalizeElements().
Referenced by v8::internal::ArrayConstructInitializeElements(), ArraySetLength(), v8::internal::BUILTIN(), v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), v8::internal::ValueDeserializer::ReadSparseJSArray(), and v8::internal::anonymous_namespace{builtins-array.cc}::SetLengthProperty().
SetLengthWouldNormalize() [1/2]
bool v8::internal::JSArray::SetLengthWouldNormalize (Heap * heap, uint32_t new_length) [inline], [static]
Definition at line 45 of file js-array-inl.h.
                                                                     {
  return new_length > kMaxFastArrayLength;
}
References kMaxFastArrayLength.
SetLengthWouldNormalize() [2/2]
bool v8::internal::JSArray::SetLengthWouldNormalize (uint32_t new_length)
Definition at line 4949 of file objects.cc.
                                                         {
  if (!HasFastElements()) return false;
  uint32_t capacity = static_cast<uint32_t>(elements()->length());
  uint32_t new_capacity;
  return JSArray::SetLengthWouldNormalize(Isolate::Current()->heap(),
                                          new_length) &&
         ShouldConvertToSlowElements(*this, capacity, new_length - 1,
                                     &new_capacity);
}
References v8::internal::Isolate::Current(), heap(), and v8::internal::ShouldConvertToSlowElements().
Referenced by v8::internal::RUNTIME_FUNCTION().
WouldChangeReadOnlyLength()
bool v8::internal::JSArray::WouldChangeReadOnlyLength (DirectHandle< JSArray > array, uint32_t index) [static]
Definition at line 5007 of file objects.cc.
                                                        {
  uint32_t length = 0;
  CHECK(Object::ToArrayLength(array->length(), &length));
  if (length <= index) return HasReadOnlyLength(array);
  return false;
}
References CHECK, v8::internal::index, v8::internal::length, and v8::internal::Object::ToArrayLength().
Referenced by v8::internal::Object::AddDataProperty().
Member Data Documentation
kInitialMaxFastElementArray
const int v8::internal::JSArray::kInitialMaxFastElementArray [static]
Initial value:
=
      (kMaxRegularHeapObjectSize - sizeof(FixedArray) - kHeaderSize -
       sizeof(AllocationMemento)) >>
      kDoubleSizeLog2
Definition at line 148 of file js-array.h.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateElements(), v8::internal::ArrayConstructInitializeElements(), v8::internal::CodeStubAssembler::ArrayCreate(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAllocateJSArray(), v8::internal::Heap::ConfigureHeap(), v8::internal::ArrayBuiltinsAssembler::GenerateConstructor(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructArrayConstructor().
kLengthDescriptorIndex
const int v8::internal::JSArray::kLengthDescriptorIndex = 0 [static]
Definition at line 128 of file js-array.h.
Referenced by v8::internal::Genesis::InitializeGlobal().
kMaxArrayIndex
constexpr uint32_t v8::internal::JSArray::kMaxArrayIndex = JSObject::kMaxElementIndex [static], [constexpr]
Definition at line 135 of file js-array.h.
Referenced by v8::internal::LookupIterator::array_index(), v8::internal::anonymous_namespace{ic.cc}::GetStoreMode(), v8::internal::LookupIterator::is_js_array_element(), and v8::internal::Factory::SizeToString().
kMaxArrayLength
constexpr uint32_t v8::internal::JSArray::kMaxArrayLength = JSObject::kMaxElementCount [static], [constexpr]
Definition at line 134 of file js-array.h.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::increase_index_offset(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), and v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::visit().
kMaxCopyElements
const int v8::internal::JSArray::kMaxCopyElements = 100 [static]
Definition at line 131 of file js-array.h.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement().
kMaxFastArrayLength
constexpr uint32_t v8::internal::JSArray::kMaxFastArrayLength [static], [constexpr]
Initial value:
=
      V8_LOWER_LIMITS_MODE_BOOL ? (8 * 1024 * 1024) : (32 * 1024 * 1024)
Definition at line 140 of file js-array.h.
Referenced by v8::internal::RegExpBuiltinsAssembler::AllocateRegExpResult(), v8::Shell::CreateD8Template(), v8::internal::IteratorBuiltinsAssembler::FastIterableToList(), v8::internal::CodeStubAssembler::IsValidFastJSArrayCapacity(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), and SetLengthWouldNormalize().
kMinJoinStackSize
const uint32_t v8::internal::JSArray::kMinJoinStackSize = 2 [static]
Definition at line 146 of file js-array.h.
kPreallocatedArrayElements
const int v8::internal::JSArray::kPreallocatedArrayElements = 4 [static]
Definition at line 126 of file js-array.h.
Referenced by v8::internal::ArrayConstructInitializeElements(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNoArgumentConstructor(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructArrayConstructor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-array.h
/mnt/V8SourceCode/src/objects/js-array-inl.h
/mnt/V8SourceCode/src/objects/js-objects.cc
/mnt/V8SourceCode/src/objects/objects-inl.h
/mnt/V8SourceCode/src/objects/objects.cc