v8::internal::SwVfpRegister Class Reference
#include <register-arm.h>
Public Member Functions
void split_code (int *vm, int *m) const
VfpRegList ToVfpRegList () const
Static Public Member Functions
static void split_code (int reg_code, int *vm, int *m)
Static Public Attributes
static constexpr int kSizeInBytes = 4
Private Member Functions
constexpr SwVfpRegister (int code)
Friends
class RegisterBase
Additional Inherited Members
Detailed Description
Definition at line 128 of file register-arm.h.
Constructor & Destructor Documentation
SwVfpRegister()
constexpr v8::internal::SwVfpRegister::SwVfpRegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 145 of file register-arm.h.
: RegisterBase(code) {}
Member Function Documentation
split_code() [1/2]
void v8::internal::SwVfpRegister::split_code (int * vm, int * m) const [inline]
Definition at line 137 of file register-arm.h.
{ split_code(code(), vm, m); }
References v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::code(), and split_code().
Referenced by split_code().
split_code() [2/2]
static void v8::internal::SwVfpRegister::split_code (int reg_code, int * vm, int * m) [inline], [static]
Definition at line 132 of file register-arm.h.
                                                        {
    DCHECK(from_code(reg_code).is_valid());
    *m = reg_code & 0x1;
    *vm = reg_code >> 1;
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::from_code(), and v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::is_valid().
ToVfpRegList()
VfpRegList v8::internal::SwVfpRegister::ToVfpRegList () const [inline]
Definition at line 138 of file register-arm.h.
                                  {
    // Each bit in the list corresponds to a S register.
    return uint64_t{0x1} << code();
  }
References v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::code().
Referenced by v8::internal::compiler::CodeGenerator::SetPendingMove().
Friends And Related Function Documentation
RegisterBase
friend class RegisterBase [friend]
Definition at line 144 of file register-arm.h.
Member Data Documentation
kSizeInBytes
constexpr int v8::internal::SwVfpRegister::kSizeInBytes = 4 [static], [constexpr]
Definition at line 130 of file register-arm.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/arm/register-arm.h