v8::internal::ParkingSemaphore Class Reference
#include <parked-scope.h>
Public Member Functions
ParkingSemaphore (int count)
ParkingSemaphore (const ParkingSemaphore &)=delete
ParkingSemaphore & operator= (const ParkingSemaphore &)=delete
void ParkedWait (LocalIsolate *local_isolate)
void ParkedWait (LocalHeap *local_heap)
void ParkedWait (const ParkedScope &scope)
bool ParkedWaitFor (LocalIsolate *local_isolate, const base::TimeDelta &rel_time) V8_WARN_UNUSED_RESULT
bool ParkedWaitFor (LocalHeap *local_heap, const base::TimeDelta &rel_time) V8_WARN_UNUSED_RESULT
bool ParkedWaitFor (const ParkedScope &scope, const base::TimeDelta &rel_time)
Detailed Description
Definition at line 165 of file parked-scope.h.
Constructor & Destructor Documentation
ParkingSemaphore() [1/2]
v8::internal::ParkingSemaphore::ParkingSemaphore (int count) [inline], [explicit]
Definition at line 167 of file parked-scope.h.
: base::Semaphore(count) {}
ParkingSemaphore() [2/2]
v8::internal::ParkingSemaphore::ParkingSemaphore (const ParkingSemaphore &) [delete]
Member Function Documentation
operator=()
ParkingSemaphore& v8::internal::ParkingSemaphore::operator= (const ParkingSemaphore &) [delete]
ParkedWait() [1/3]
void v8::internal::ParkingSemaphore::ParkedWait (const ParkedScope & scope) [inline]
Definition at line 174 of file parked-scope.h.
                                            {
    USE(scope);
    Wait();
  }
References USE.
ParkedWait() [2/3]
void v8::internal::ParkingSemaphore::ParkedWait (LocalHeap * local_heap) [inline]
Definition at line 94 of file parked-scope-inl.h.
                                                                 {
  local_heap->ExecuteWhileParked(
      [this](const ParkedScope& parked) { ParkedWait(parked); });
}
References v8::internal::LocalHeap::ExecuteWhileParked(), and ParkedWait().
ParkedWait() [3/3]
void v8::internal::ParkingSemaphore::ParkedWait (LocalIsolate * local_isolate) [inline]
Definition at line 90 of file parked-scope-inl.h.
                                                                       {
  ParkedWait(local_isolate->heap());
}
References v8::internal::LocalIsolate::heap().
Referenced by v8::SourceGroup::ExecuteInThread(), v8::Worker::GetMessage(), ParkedWait(), and v8::SourceGroup::WaitForThread().
ParkedWaitFor() [1/3]
bool v8::internal::ParkingSemaphore::ParkedWaitFor (const ParkedScope & scope, const base::TimeDelta & rel_time) [inline]
Definition at line 186 of file parked-scope.h.
                                                    {
    USE(scope);
    return WaitFor(rel_time);
  }
References USE.
ParkedWaitFor() [2/3]
bool v8::internal::ParkingSemaphore::ParkedWaitFor (LocalHeap * local_heap, const base::TimeDelta & rel_time) [inline]
Definition at line 104 of file parked-scope-inl.h.
                                                          {
  bool result;
  local_heap->ExecuteWhileParked(
      [this, rel_time, &result](const ParkedScope& parked) {
        result = ParkedWaitFor(parked, rel_time);
      });
  return result;
}
References v8::internal::LocalHeap::ExecuteWhileParked(), ParkedWaitFor(), and v8::base::internal::result.
ParkedWaitFor() [3/3]
bool v8::internal::ParkingSemaphore::ParkedWaitFor (LocalIsolate * local_isolate, const base::TimeDelta & rel_time) [inline]
Definition at line 99 of file parked-scope-inl.h.
                                                                {
  return ParkedWaitFor(local_isolate->heap(), rel_time);
}
References v8::internal::LocalIsolate::heap().
Referenced by ParkedWaitFor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/parked-scope.h
/mnt/V8SourceCode/src/heap/parked-scope-inl.h