v8::internal::UnreachableObjectsFilter::MarkingVisitor Class Reference
Public Member Functions
MarkingVisitor (UnreachableObjectsFilter *filter)
void VisitMapPointer (Tagged< HeapObject > object) override
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end) override
void TransitiveClosure ()
Private Member Functions
template<typename TSlot >
void MarkPointersImpl (TSlot start, TSlot end)
void MarkHeapObject (Tagged< HeapObject > heap_object)
Private Attributes
UnreachableObjectsFilter * filter_
std::vector< Tagged< HeapObject > > marking_stack_
Additional Inherited Members
Detailed Description
Definition at line 6725 of file heap.cc.
Constructor & Destructor Documentation
MarkingVisitor()
v8::internal::UnreachableObjectsFilter::MarkingVisitor::MarkingVisitor (UnreachableObjectsFilter * filter) [inline], [explicit]
Definition at line 6727 of file heap.cc.
        : ObjectVisitorWithCageBases(filter->heap_), filter_(filter) {}
Member Function Documentation
MarkHeapObject()
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::MarkHeapObject (Tagged< HeapObject > heap_object) [inline], [private]
Definition at line 6797 of file heap.cc.
                                                                  {
      if (filter_->MarkAsReachable(heap_object)) {
        marking_stack_.push_back(heap_object);
      }
    }
References filter_, v8::internal::UnreachableObjectsFilter::MarkAsReachable(), and marking_stack_.
Referenced by MarkPointersImpl(), VisitCodeTarget(), VisitEmbeddedPointer(), VisitInstructionStreamPointer(), and VisitMapPointer().
MarkPointersImpl()
template<typename TSlot >
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::MarkPointersImpl (TSlot start, TSlot end) [inline], [private]
Definition at line 6783 of file heap.cc.
                                                            {
      // Treat weak references as strong.
      for (TSlot p = start; p < end; ++p) {
        typename TSlot::TObject object = p.load(cage_base());
#ifdef V8_ENABLE_DIRECT_HANDLE
        if (object.ptr() == kTaggedNullAddress) continue;
#endif
        Tagged<HeapObject> heap_object;
        if (object.GetHeapObject(&heap_object)) {
          MarkHeapObject(heap_object);
        }
      }
    }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), v8::internal::compiler::end(), v8::internal::kTaggedNullAddress, and MarkHeapObject().
Referenced by VisitPointers(), and VisitRootPointers().
TransitiveClosure()
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::TransitiveClosure () [inline]
Definition at line 6773 of file heap.cc.
                             {
      while (!marking_stack_.empty()) {
        Tagged<HeapObject> obj = marking_stack_.back();
        marking_stack_.pop_back();
        VisitObject(filter_->heap_->isolate(), obj, this);
      }
    }
References filter_, v8::internal::UnreachableObjectsFilter::heap_, v8::internal::Heap::isolate(), marking_stack_, and v8::internal::VisitObject().
Referenced by v8::internal::UnreachableObjectsFilter::MarkReachableObjects().
VisitCodeTarget()
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 6752 of file heap.cc.
                                                 {
      Tagged<InstructionStream> target =
          InstructionStream::FromTargetAddress(rinfo->target_address());
      MarkHeapObject(target);
    }
References v8::internal::InstructionStream::FromTargetAddress(), and MarkHeapObject().
VisitEmbeddedPointer()
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 6758 of file heap.cc.
                                                      {
      MarkHeapObject(rinfo->target_object(cage_base()));
    }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and MarkHeapObject().
VisitInstructionStreamPointer()
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 6743 of file heap.cc.
                                                                            {
      Tagged<Object> maybe_code = slot.load(code_cage_base());
      Tagged<HeapObject> heap_object;
      if (maybe_code.GetHeapObject(&heap_object)) {
        MarkHeapObject(heap_object);
      }
    }
References v8::internal::ObjectVisitorWithCageBases::code_cage_base(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::FullObjectSlot::load(), and MarkHeapObject().
VisitMapPointer()
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitMapPointer (Tagged< HeapObject > object) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 6730 of file heap.cc.
                                                             {
      MarkHeapObject(UncheckedCast<Map>(object->map(cage_base())));
    }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and MarkHeapObject().
VisitPointers() [1/2]
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 6738 of file heap.cc.
                                                  {
      MarkPointersImpl(start, end);
    }
References v8::internal::compiler::end(), and MarkPointersImpl().
VisitPointers() [2/2]
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 6733 of file heap.cc.
                                                {
      MarkPointersImpl(start, end);
    }
References v8::internal::compiler::end(), and MarkPointersImpl().
VisitRootPointers() [1/2]
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 6763 of file heap.cc.
                                                                              {
      MarkPointersImpl(start, end);
    }
References v8::internal::compiler::end(), and MarkPointersImpl().
VisitRootPointers() [2/2]
void v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 6767 of file heap.cc.
                                                           {
      MarkPointersImpl(start, end);
    }
References v8::internal::compiler::end(), and MarkPointersImpl().
Member Data Documentation
filter_
UnreachableObjectsFilter* v8::internal::UnreachableObjectsFilter::MarkingVisitor::filter_ [private]
Definition at line 6803 of file heap.cc.
Referenced by MarkHeapObject(), and TransitiveClosure().
marking_stack_
std::vector<Tagged<HeapObject> > v8::internal::UnreachableObjectsFilter::MarkingVisitor::marking_stack_ [private]
Definition at line 6804 of file heap.cc.
Referenced by MarkHeapObject(), and TransitiveClosure().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/heap.cc