v8::internal::wasm::Decoder Class Reference
#include <decoder.h>
Classes
struct FullValidationTag
struct NoName
struct NoValidationTag
Public Types
enum TraceFlag : bool { kTrace = true
, kNoTrace = false
 }
template<typename ValidationTag >
using Name = std::conditional_t< ValidationTag::validate, const char *, NoName >
Public Member Functions
Decoder (const uint8_t *start, const uint8_t *end, uint32_t buffer_offset=0)
Decoder (const base::Vector< const uint8_t > bytes, uint32_t buffer_offset=0)
Decoder (const uint8_t *start, const uint8_t *pc, const uint8_t *end, uint32_t buffer_offset=0)
virtual ~Decoder ()=default
template<typename ValidationTag >
uint8_t read_u8 (const uint8_t *pc, Name< ValidationTag > msg=`expected 1 byte`)
template<typename ValidationTag >
uint16_t read_u16 (const uint8_t *pc, Name< ValidationTag > msg=`expected 2 bytes`)
template<typename ValidationTag >
uint32_t read_u32 (const uint8_t *pc, Name< ValidationTag > msg=`expected 4 bytes`)
template<typename ValidationTag >
uint64_t read_u64 (const uint8_t *pc, Name< ValidationTag > msg=`expected 8 bytes`)
template<typename ValidationTag >
std::pair< uint32_t, uint32_t > read_u32v (const uint8_t *pc, Name< ValidationTag > name=`LEB32`)
template<typename ValidationTag >
std::pair< int32_t, uint32_t > read_i32v (const uint8_t *pc, Name< ValidationTag > name=`signed LEB32`)
template<typename ValidationTag >
std::pair< uint64_t, uint32_t > read_u64v (const uint8_t *pc, Name< ValidationTag > name=`LEB64`)
template<typename ValidationTag >
std::pair< int64_t, uint32_t > read_i64v (const uint8_t *pc, Name< ValidationTag > name=`signed LEB64`)
template<typename ValidationTag >
std::pair< int64_t, uint32_t > read_i33v (const uint8_t *pc, Name< ValidationTag > name=`signed LEB33`)
template<typename ValidationTag >
std::pair< WasmOpcode, uint32_t > read_prefixed_opcode (const uint8_t *pc, Name< ValidationTag > name=`prefixed opcode`)
uint8_t consume_u8 (const char *name=`uint8_t`)
uint8_t consume_u8 (const char *name, ITracer *tracer)
uint16_t consume_u16 (const char *name=`uint16_t`)
uint32_t consume_u32 (const char *name, ITracer *tracer)
uint32_t consume_u32v (const char *name=`var_uint32`)
uint32_t consume_u32v (const char *name, ITracer *tracer)
int32_t consume_i32v (const char *name=`var_int32`)
uint64_t consume_u64v (const char *name, ITracer *tracer)
int64_t consume_i64v (const char *name=`var_int64`)
void consume_bytes (uint32_t size, const char *name=`skip`)
void consume_bytes (uint32_t size, const char *name, ITracer *tracer)
uint32_t available_bytes () const
bool checkAvailable (uint32_t size)
void V8_NOINLINE V8_PRESERVE_MOST error (const char *msg)
void V8_NOINLINE V8_PRESERVE_MOST error (const uint8_t *pc, const char *msg)
void V8_NOINLINE V8_PRESERVE_MOST error (uint32_t offset, const char *msg)
template<typename... Args>
void V8_NOINLINE V8_PRESERVE_MOST errorf (const char *format, Args... args)
template<typename... Args>
void V8_NOINLINE V8_PRESERVE_MOST errorf (const uint8_t *pc, const char *format, Args... args)
template<typename... Args>
void V8_NOINLINE V8_PRESERVE_MOST errorf (uint32_t offset, const char *format, Args... args)
virtual void onFirstError ()
void traceByteRange (const uint8_t *start, const uint8_t *end)
void traceOffEnd ()
template<typename T , typename R = std::decay_t<T>>
Result< R > toResult (T &&val)
void Reset (const uint8_t *start, const uint8_t *end, uint32_t buffer_offset=0)
void Reset (base::Vector< const uint8_t > bytes, uint32_t buffer_offset=0)
bool ok () const
bool failed () const
bool more () const
const WasmError & error () const
const uint8_t * start () const
const uint8_t * pc () const
uint32_t position () const
uint32_t pc_offset (const uint8_t *pc) const
uint32_t pc_offset () const
uint32_t buffer_offset () const
uint32_t GetBufferRelativeOffset (uint32_t offset) const
const uint8_t * end () const
void set_end (const uint8_t *end)
bool lookahead (int offset, uint8_t expected)
Static Public Attributes
static constexpr struct v8::internal::wasm::Decoder::NoValidationTag kNoValidation = {}
static constexpr struct v8::internal::wasm::Decoder::FullValidationTag kFullValidation = {}
Protected Attributes
const uint8_t * start_
const uint8_t * pc_
const uint8_t * end_
uint32_t buffer_offset_
WasmError error_
Private Member Functions
void V8_NOINLINE PRINTF_FORMAT (3, 4) verrorf(uint32_t offset
va_start (args, format)
va_end (args)
CHECK_LT (0, len)
onFirstError ()
template<typename IntType , typename ValidationTag >
IntType read_little_endian (const uint8_t *pc, Name< ValidationTag > msg)
template<typename IntType , TraceFlag trace>
IntType consume_little_endian (const char *name)
template<typename IntType , typename ValidationTag , TraceFlag trace, size_t size_in_bits = 8 * sizeof(IntType)>
std::pair< IntType, uint32_t > read_leb (const uint8_t *pc, Name< ValidationTag > name=`varint`)
template<typename IntType , typename ValidationTag , TraceFlag trace, size_t size_in_bits = 8 * sizeof(IntType)>
V8_NOINLINE V8_PRESERVE_MOST std::pair< IntType, uint32_t > read_leb_slowpath (const uint8_t *pc, Name< ValidationTag > name)
template<typename IntType , typename ValidationTag , TraceFlag trace, size_t size_in_bits, int byte_index>
std::pair< IntType, uint32_t > read_leb_tail (const uint8_t *pc, Name< ValidationTag > name, IntType intermediate_result)
Private Attributes
void V8_NOINLINE const char * format
void V8_NOINLINE const char constexpr int kMaxErrorMsg = 256
base::EmbeddedVector< char, kMaxErrorMsg > buffer
va_list args
int len = base::VSNPrintF(buffer, format, args)
error_ = {offset, {buffer.begin(), static_cast<size_t>(len)}}
Detailed Description
Definition at line 88 of file decoder.h.
Member Typedef Documentation
Name
template<typename ValidationTag >
using v8::internal::wasm::Decoder::Name = std::conditional_t<ValidationTag::validate, const char*, NoName>
Definition at line 110 of file decoder.h.
Member Enumeration Documentation
TraceFlag
enum v8::internal::wasm::Decoder::TraceFlag : bool
Enumerator
kTrace
kNoTrace
Definition at line 113 of file decoder.h.
: bool { kTrace = true, kNoTrace = false };
Constructor & Destructor Documentation
Decoder() [1/3]
v8::internal::wasm::Decoder::Decoder (const uint8_t * start, const uint8_t * end, uint32_t buffer_offset = 0) [inline]
Definition at line 115 of file decoder.h.
      : Decoder(start, start, end, buffer_offset) {}
Decoder() [2/3]
v8::internal::wasm::Decoder::Decoder (const base::Vector< const uint8_t > bytes, uint32_t buffer_offset = 0) [inline], [explicit]
Definition at line 117 of file decoder.h.
      : Decoder(bytes.begin(), bytes.begin() + bytes.length(), buffer_offset) {}
Decoder() [3/3]
v8::internal::wasm::Decoder::Decoder (const uint8_t * start, const uint8_t * pc, const uint8_t * end, uint32_t buffer_offset = 0) [inline]
Definition at line 120 of file decoder.h.
      : start_(start), pc_(pc), end_(end), buffer_offset_(buffer_offset) {
    DCHECK_LE(start, pc);
    DCHECK_LE(pc, end);
    DCHECK_EQ(static_cast<uint32_t>(end - start), end - start);
  }
References DCHECK_EQ, DCHECK_LE, end(), pc(), and start().
 Decoder()
virtual v8::internal::wasm::Decoder::~Decoder () [virtual], [default]
Member Function Documentation
available_bytes()
uint32_t v8::internal::wasm::Decoder::available_bytes () const [inline]
Definition at line 314 of file decoder.h.
                                   {
    DCHECK_LE(pc_, end_);
    DCHECK_GE(kMaxUInt32, end_ - pc_);
    return static_cast<uint32_t>(end_ - pc_);
  }
References DCHECK_GE, DCHECK_LE, end_, v8::internal::kMaxUInt32, and pc_.
Referenced by checkAvailable(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), and v8::internal::wasm::WasmSectionIterator::next().
buffer_offset()
uint32_t v8::internal::wasm::Decoder::buffer_offset () const [inline]
Definition at line 419 of file decoder.h.
{ return buffer_offset_; }
References buffer_offset_.
Referenced by Reset(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::WasmDecoder().
CHECK_LT()
v8::internal::wasm::Decoder::CHECK_LT (0 , len) [private]
checkAvailable()
bool v8::internal::wasm::Decoder::checkAvailable (uint32_t size) [inline]
Definition at line 321 of file decoder.h.
                                     {
    if (V8_UNLIKELY(size > available_bytes())) {
      errorf(pc_, "expected %u bytes, fell off end", size);
      return false;
    }
    return true;
  }
References available_bytes(), errorf(), pc_, size(), and V8_UNLIKELY.
Referenced by consume_bytes(), consume_little_endian(), v8::internal::wasm::DecodeAsmJsOffsets(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::DecodeFunctionNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
consume_bytes() [1/2]
void v8::internal::wasm::Decoder::consume_bytes (uint32_t size, const char * name, ITracer * tracer) [inline]
Definition at line 306 of file decoder.h.
                                                                       {
    if (tracer) {
      tracer->Bytes(pc_, size);
      tracer->Description(name);
    }
    consume_bytes(size, nullptr);
  }
References v8::internal::wasm::ITracer::Bytes(), consume_bytes(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::name(), pc_, and size().
consume_bytes() [2/2]
void v8::internal::wasm::Decoder::consume_bytes (uint32_t size, const char * name = `skip`) [inline]
Definition at line 297 of file decoder.h.
                                                               {
    // Only trace if the name is not null.
    TRACE_IF(name, " +%u %-20s: %u bytes\n", pc_offset(), name, size);
    if (checkAvailable(size)) {
      pc_ += size;
    } else {
      pc_ = end_;
    }
  }
References checkAvailable(), end_, v8::internal::wasm::name(), pc_, pc_offset(), size(), and TRACE_IF.
Referenced by v8::internal::wasm::WasmSectionIterator::advance(), consume_bytes(), v8::internal::wasm::ModuleDecoderImpl::consume_described_type(), v8::internal::wasm::ModuleDecoderImpl::consume_describing_type(), v8::internal::wasm::ModuleDecoderImpl::consume_heap_type(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::ModuleDecoderImpl::consume_shared_type(), v8::internal::wasm::ModuleDecoderImpl::consume_storage_type(), v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), v8::internal::wasm::ModuleDecoderImpl::consume_value_type(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeBuildIdSection(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::DecodeCustomSections(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDescriptorsSection(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExternalDebugInfoSection(), v8::internal::wasm::DecodeFunctionNames(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeIndirectNameMap(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMap(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSourceMappingURLSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection(), v8::internal::wasm::InitializeElementSegment(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::wasm::WasmSectionIterator::next(), v8::internal::wasm::NativeModuleCache::PrefixHash(), v8::internal::wasm::ModuleDisassembler::PrintModule(), and v8::internal::wasm::DescriptorsSectionIterator::SkipCurrentSubsection().
consume_i32v()
int32_t v8::internal::wasm::Decoder::consume_i32v (const char * name = `var_int32`) [inline]
Definition at line 269 of file decoder.h.
                                                       {
    auto [result, length] =
        read_leb<int32_t, FullValidationTag, kTrace>(pc_, name);
    pc_ += length;
    return result;
  }
References v8::internal::length, v8::internal::wasm::name(), pc_, and v8::base::internal::result.
Referenced by v8::internal::wasm::DecodeAsmJsOffsets(), and v8::internal::wasm::DeserializeTypeFeedback().
consume_i64v()
int64_t v8::internal::wasm::Decoder::consume_i64v (const char * name = `var_int64`) [inline]
Definition at line 289 of file decoder.h.
                                                       {
    auto [result, length] =
        read_leb<int64_t, FullValidationTag, kTrace>(pc_, name);
    pc_ += length;
    return result;
  }
References v8::internal::length, v8::internal::wasm::name(), pc_, and v8::base::internal::result.
consume_little_endian()
template<typename IntType , TraceFlag trace>
IntType v8::internal::wasm::Decoder::consume_little_endian (const char * name) [inline], [private]
Definition at line 474 of file decoder.h.
                                                  {
    TRACE_IF(trace, " +%u %-20s: ", pc_offset(), name);
    if (!checkAvailable(sizeof(IntType))) {
      traceOffEnd();
      pc_ = end_;
      return IntType{0};
    }
    IntType val = read_little_endian<IntType, NoValidationTag>(pc_, name);
    traceByteRange(pc_, pc_ + sizeof(IntType));
    TRACE_IF(trace, "= %d\n", val);
    pc_ += sizeof(IntType);
    return val;
  }
References checkAvailable(), end_, v8::internal::wasm::name(), pc_, pc_offset(), TRACE_IF, traceByteRange(), and traceOffEnd().
consume_u16()
uint16_t v8::internal::wasm::Decoder::consume_u16 (const char * name = `uint16_t`) [inline]
Definition at line 237 of file decoder.h.
                                                      {
    return consume_little_endian<uint16_t, kTrace>(name);
  }
References v8::internal::wasm::name().
consume_u32()
uint32_t v8::internal::wasm::Decoder::consume_u32 (const char * name, ITracer * tracer) [inline]
Definition at line 242 of file decoder.h.
                                                          {
    if (tracer) {
      tracer->Bytes(pc_, sizeof(uint32_t));
      tracer->Description(name);
    }
    return consume_little_endian<uint32_t, kNoTrace>(name);
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::name(), and pc_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader().
consume_u32v() [1/2]
uint32_t v8::internal::wasm::Decoder::consume_u32v (const char * name, ITracer * tracer) [inline]
Definition at line 257 of file decoder.h.
                                                           {
    auto [result, length] =
        read_leb<uint32_t, FullValidationTag, kNoTrace>(pc_, name);
    if (tracer) {
      tracer->Bytes(pc_, length);
      tracer->Description(name);
    }
    pc_ += length;
    return result;
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::ITracer::Description(), v8::internal::length, v8::internal::wasm::name(), pc_, and v8::base::internal::result.
consume_u32v() [2/2]
uint32_t v8::internal::wasm::Decoder::consume_u32v (const char * name = `var_uint32`) [inline]
Definition at line 251 of file decoder.h.
                                                         {
    auto [result, length] =
        read_leb<uint32_t, FullValidationTag, kTrace>(pc_, name);
    pc_ += length;
    return result;
  }
References v8::internal::length, v8::internal::wasm::name(), pc_, and v8::base::internal::result.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::Entry::Constructor(), v8::internal::wasm::ModuleDecoderImpl::consume_count(), v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_described_type(), v8::internal::wasm::ModuleDecoderImpl::consume_describing_type(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_exception_attribute(), v8::internal::wasm::ModuleDecoderImpl::consume_index(), v8::internal::wasm::ModuleDecoderImpl::consume_resizable_limits(), v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_u32v(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::DecodeAsmJsOffsets(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection(), v8::internal::wasm::DecodeCustomSections(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::DecodeFunctionNames(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeIndirectNameMap(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::DescriptorsSectionIterator::DescriptorsSectionIterator(), v8::internal::wasm::DeserializeTypeFeedback(), v8::internal::wasm::WasmSectionIterator::next(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethodImpl(), v8::internal::wasm::DescriptorsSectionIterator::NumImportAndDeclEntries(), v8::internal::wasm::NativeModuleCache::PrefixHash(), and v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes().
consume_u64v()
uint64_t v8::internal::wasm::Decoder::consume_u64v (const char * name, ITracer * tracer) [inline]
Definition at line 277 of file decoder.h.
                                                           {
    auto [result, length] =
        read_leb<uint64_t, FullValidationTag, kNoTrace>(pc_, name);
    if (tracer) {
      tracer->Bytes(pc_, length);
      tracer->Description(name);
    }
    pc_ += length;
    return result;
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::ITracer::Description(), v8::internal::length, v8::internal::wasm::name(), pc_, and v8::base::internal::result.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_resizable_limits().
consume_u8() [1/2]
uint8_t v8::internal::wasm::Decoder::consume_u8 (const char * name, ITracer * tracer) [inline]
Definition at line 228 of file decoder.h.
                                                        {
    if (tracer) {
      tracer->Bytes(pc_, sizeof(uint8_t));
      tracer->Description(name);
    }
    return consume_little_endian<uint8_t, kNoTrace>(name);
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::name(), and pc_.
consume_u8() [2/2]
uint8_t v8::internal::wasm::Decoder::consume_u8 (const char * name = `uint8_t`) [inline]
Definition at line 225 of file decoder.h.
                                                   {
    return consume_little_endian<uint8_t, kTrace>(name);
  }
References v8::internal::wasm::name().
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_global_flags(), v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte(), v8::internal::wasm::ModuleDecoderImpl::consume_mutability(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection(), v8::internal::wasm::DecodeCustomSections(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::DecodeFunctionNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::DeserializeTieringInformation(), v8::internal::wasm::ModuleDecoderImpl::expect_u8(), v8::internal::wasm::WasmSectionIterator::next(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethodImpl(), v8::internal::wasm::DescriptorsSectionIterator::NextSubsection(), v8::internal::wasm::DescriptorsSectionIterator::NumImportAndDeclEntries(), and v8::internal::wasm::NativeModuleCache::PrefixHash().
end()
const uint8_t* v8::internal::wasm::Decoder::end () const [inline]
Definition at line 426 of file decoder.h.
{ return end_; }
References end_.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), Decoder(), v8::internal::wasm::BasicBlockCalculator::EndCurrentBlock(), v8::internal::wasm::WasmSectionIterator::next(), v8::internal::wasm::FunctionBodyDisassembler::PrintHexNumber(), Reset(), set_end(), and traceByteRange().
error() [1/4]
const WasmError& v8::internal::wasm::Decoder::error () const [inline]
Definition at line 405 of file decoder.h.
{ return error_; }
References error_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_described_type(), v8::internal::wasm::ModuleDecoderImpl::consume_describing_type(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_global_flags(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte(), v8::internal::wasm::ModuleDecoderImpl::consume_mutability(), v8::internal::wasm::ModuleDecoderImpl::consume_shared_type(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStartSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), read_leb_tail(), and read_little_endian().
error() [2/4]
void V8_NOINLINE V8_PRESERVE_MOST v8::internal::wasm::Decoder::error (const char * msg) [inline]
Definition at line 331 of file decoder.h.
                                                           {
    errorf(pc_offset(), "%s", msg);
  }
References errorf(), and pc_offset().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular(), v8::internal::wasm::DecodeCustomSections(), v8::internal::wasm::DecodeError(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptions(), and v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToConstructor().
error() [3/4]
void V8_NOINLINE V8_PRESERVE_MOST v8::internal::wasm::Decoder::error (const uint8_t * pc, const char * msg) [inline]
Definition at line 334 of file decoder.h.
                                                                              {
    errorf(pc_offset(pc), "%s", msg);
  }
References errorf(), pc(), and pc_offset().
error() [4/4]
void V8_NOINLINE V8_PRESERVE_MOST v8::internal::wasm::Decoder::error (uint32_t offset, const char * msg) [inline]
Definition at line 337 of file decoder.h.
                                                                            {
    errorf(offset, "%s", msg);
  }
References errorf().
errorf() [1/3]
template<typename... Args>
void V8_NOINLINE V8_PRESERVE_MOST v8::internal::wasm::Decoder::errorf (const char * format, Args... args) [inline]
Definition at line 342 of file decoder.h.
                                                                             {
    errorf(pc_offset(), format, args...);
  }
References args, format, and pc_offset().
Referenced by v8::internal::wasm::WasmSectionIterator::advance(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout(), checkAvailable(), v8::internal::wasm::ModuleDecoderImpl::CheckDataSegmentsCount(), v8::internal::wasm::ModuleDecoderImpl::CheckFunctionsCount(), v8::internal::wasm::DescriptorsSectionIterator::Entry::CheckIndex(), v8::internal::wasm::ModuleDecoderImpl::CheckMismatchedCounts(), v8::internal::wasm::ModuleDecoderImpl::CheckSectionOrder(), v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::consume_count(), v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_described_type(), v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_exception_attribute(), v8::internal::wasm::ModuleDecoderImpl::consume_global_flags(), v8::internal::wasm::ModuleDecoderImpl::consume_index(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte(), v8::internal::wasm::ModuleDecoderImpl::consume_resizable_limits(), v8::internal::wasm::ModuleDecoderImpl::consume_shared_type(), v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), v8::internal::wasm::ModuleDecoderImpl::consume_tag_sig_index(), v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::DeclEntry(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection(), v8::internal::wasm::DecodeError(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection(), v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), v8::internal::wasm::DescriptorsSectionIterator::DescriptorsSectionIterator(), error(), errorf(), v8::internal::wasm::ModuleDecoderImpl::expect_u8(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::GlobalEntry(), v8::internal::wasm::WasmSectionIterator::next(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextExport(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethodImpl(), v8::internal::wasm::DescriptorsSectionIterator::NextSubsection(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::Parent(), v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::Parent(), v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::ProtoConfig(), read_leb_tail(), read_prefixed_opcode(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::unsupported().
errorf() [2/3]
template<typename... Args>
void V8_NOINLINE V8_PRESERVE_MOST v8::internal::wasm::Decoder::errorf (const uint8_t * pc, const char * format, Args... args) [inline]
Definition at line 347 of file decoder.h.
                                                                             {
    errorf(pc_offset(pc), format, args...);
  }
References args, errorf(), format, pc(), and pc_offset().
errorf() [3/3]
template<typename... Args>
void V8_NOINLINE V8_PRESERVE_MOST v8::internal::wasm::Decoder::errorf (uint32_t offset, const char * format, Args... args) [inline]
Definition at line 353 of file decoder.h.
                                                         {
    static_assert(
        sizeof...(Args) > 0,
        "Use error instead of errorf if the format string has no placeholders");
    verrorf(offset, format, args...);
  }
References args, and format.
failed()
bool v8::internal::wasm::Decoder::failed () const [inline]
Definition at line 403 of file decoder.h.
{ return error_.has_error(); }
References error_, and v8::internal::wasm::WasmError::has_error().
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_array(), v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::consume_struct(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection(), v8::internal::wasm::DecodeCustomSections(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeElementSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::DecodeLocalDecls(), v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::DidAssemblerBailout(), v8::internal::wasm::ExecuteLiftoffCompilation(), v8::internal::wasm::IdentifyUnknownSectionInternal(), v8::internal::wasm::WasmSectionIterator::next(), ok(), v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes(), and toResult().
GetBufferRelativeOffset()
uint32_t v8::internal::wasm::Decoder::GetBufferRelativeOffset (uint32_t offset) const [inline]
Definition at line 422 of file decoder.h.
                                                          {
    DCHECK_LE(buffer_offset_, offset);
    return offset - buffer_offset_;
  }
References buffer_offset_, and DCHECK_LE.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::IdentifyUnknownSectionInternal(), and v8::internal::wasm::validate_utf8().
lookahead()
bool v8::internal::wasm::Decoder::lookahead (int offset, uint8_t expected) [inline]
Definition at line 430 of file decoder.h.
                                               {
    DCHECK_LE(pc_, end_);
    return end_ - pc_ > offset && pc_[offset] == expected;
  }
References DCHECK_LE, end_, and pc_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitI32CmpOp(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnOp().
more()
bool v8::internal::wasm::Decoder::more () const [inline]
Definition at line 404 of file decoder.h.
{ return pc_ < end_; }
References end_, and pc_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::DecodeAsmJsOffsets(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::DecodeCustomSections(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::DecodeFunctionNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::WasmSectionIterator::more(), v8::internal::wasm::WasmSectionIterator::next(), v8::internal::wasm::DescriptorsSectionIterator::NextSubsection(), and v8::internal::wasm::NativeModuleCache::PrefixHash().
ok()
bool v8::internal::wasm::Decoder::ok () const [inline]
Definition at line 402 of file decoder.h.
{ return !failed(); }
References failed().
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl(), v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::consume_struct(), v8::internal::wasm::ModuleDecoderImpl::consume_value_type(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::DecodeAsmJsOffsets(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeBuildIdSection(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExternalDebugInfoSection(), v8::internal::wasm::DecodeFunctionNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSignatureForTesting(), v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeIndirectNameMap(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::DecodeLocalDecls(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection(), v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting(), v8::internal::wasm::ModuleDecoderImpl::DecodeSourceMappingURLSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTagSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), v8::internal::wasm::DescriptorsSectionIterator::DescriptorsSectionIterator(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection(), v8::internal::wasm::ModuleDecoderImpl::FinishDecoding(), v8::internal::wasm::GenerateLiftoffDebugSideTable(), v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), v8::internal::wasm::TryTableIterator< ValidationTag >::has_next(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::has_next(), v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptions(), v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), v8::internal::wasm::WasmSectionIterator::more(), v8::internal::wasm::WasmSectionIterator::next(), v8::internal::wasm::DescriptorsSectionIterator::NextSubsection(), v8::internal::wasm::DescriptorsSectionIterator::NumImportAndDeclEntries(), v8::internal::wasm::DescriptorsSectionIterator::Entry::ok(), v8::internal::wasm::NativeModuleCache::PrefixHash(), and v8::internal::wasm::value_type_reader::read_value_type().
onFirstError() [1/2]
virtual void v8::internal::wasm::Decoder::onFirstError () [inline], [virtual]
Reimplemented in v8::internal::wasm::ModuleDecoderImpl, and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >.
Definition at line 362 of file decoder.h.
{}
onFirstError() [2/2]
v8::internal::wasm::Decoder::onFirstError () [private]
pc()
const uint8_t* v8::internal::wasm::Decoder::pc () const [inline]
Definition at line 408 of file decoder.h.
{ return pc_; }
References pc_.
Referenced by v8::internal::wasm::WasmSectionIterator::advance(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout(), v8::internal::wasm::ModuleDecoderImpl::CheckDataSegmentsCount(), v8::internal::wasm::ModuleDecoderImpl::CheckMismatchedCounts(), v8::internal::wasm::ModuleDecoderImpl::CheckSectionOrder(), v8::internal::wasm::DescriptorsSectionIterator::Entry::Constructor(), v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_described_type(), v8::internal::wasm::ModuleDecoderImpl::consume_describing_type(), v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_global_flags(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte(), v8::internal::wasm::ModuleDecoderImpl::consume_resizable_limits(), v8::internal::wasm::ModuleDecoderImpl::consume_shared_type(), v8::internal::wasm::ModuleDecoderImpl::consume_storage_type(), v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::DeclEntry(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::DecodeAsmJsOffsets(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::DecodeLocalDecls(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection(), Decoder(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), v8::internal::wasm::BasicBlockCalculator::EndCurrentBlock(), error(), errorf(), v8::internal::wasm::ModuleDecoderImpl::expect_u8(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::GlobalEntry(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop(), v8::internal::wasm::WasmSectionIterator::next(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextExport(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::NextInstruction(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethodImpl(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::Parent(), v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::Parent(), pc_offset(), v8::internal::wasm::NativeModuleCache::PrefixHash(), v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToConstructor(), v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::ProtoConfig(), read_i32v(), read_i33v(), read_i64v(), read_leb(), read_leb_slowpath(), read_leb_tail(), read_little_endian(), read_prefixed_opcode(), read_u16(), read_u32(), read_u32v(), read_u64(), read_u64v(), read_u8(), v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SafeOpcodeNameAt(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateCont(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateDataSegment(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateElementSegment(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateFunction(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateHeapType(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateLocal(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateValueType().
pc_offset() [1/2]
uint32_t v8::internal::wasm::Decoder::pc_offset () const [inline]
Definition at line 418 of file decoder.h.
{ return pc_offset(pc_); }
References pc_, and pc_offset().
Referenced by consume_bytes(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), consume_little_endian(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeElementSection(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionBody(), v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStartSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTagSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), error(), errorf(), pc_offset(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::pc_relative_offset(), and read_leb().
pc_offset() [2/2]
uint32_t v8::internal::wasm::Decoder::pc_offset (const uint8_t * pc) const [inline]
Definition at line 413 of file decoder.h.
                                                        {
    DCHECK_LE(start_, pc);
    DCHECK_GE(kMaxUInt32 - buffer_offset_, pc - start_);
    return static_cast<uint32_t>(pc - start_) + buffer_offset_;
  }
References buffer_offset_, DCHECK_GE, DCHECK_LE, v8::internal::kMaxUInt32, pc(), and start_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallRefImpl(), v8::internal::wasm::consume_string(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::DecodeCustomSections(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishCall(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreFrameDescriptionForDeopt(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::unsupported().
position()
uint32_t v8::internal::wasm::Decoder::position () const [inline]
Definition at line 409 of file decoder.h.
                                      {
    return static_cast<uint32_t>(pc_ - start_);
  }
References pc_, and start_.
Referenced by v8::internal::wasm::BasicBlockCalculator::EndCurrentBlock(), v8::internal::wasm::DescriptorsSectionIterator::SkipCurrentSubsection(), and v8::internal::wasm::BasicBlockCalculator::StartNewBlock().
PRINTF_FORMAT()
void V8_NOINLINE v8::internal::wasm::Decoder::PRINTF_FORMAT (3 , 4) [private]
read_i32v()
template<typename ValidationTag >
std::pair<int32_t, uint32_t> v8::internal::wasm::Decoder::read_i32v (const uint8_t * pc, Name< ValidationTag > name = `signed LEB32`) [inline]
Definition at line 169 of file decoder.h.
                                                                    {
    return read_leb<int32_t, ValidationTag, kNoTrace>(pc, name);
  }
References v8::internal::wasm::name(), and pc().
read_i33v()
template<typename ValidationTag >
std::pair<int64_t, uint32_t> v8::internal::wasm::Decoder::read_i33v (const uint8_t * pc, Name< ValidationTag > name = `signed LEB33`) [inline]
Definition at line 193 of file decoder.h.
                                                                    {
    return read_leb<int64_t, ValidationTag, kNoTrace, 33>(pc, name);
  }
References v8::internal::wasm::name(), and pc().
Referenced by v8::internal::wasm::value_type_reader::read_heap_type().
read_i64v()
template<typename ValidationTag >
std::pair<int64_t, uint32_t> v8::internal::wasm::Decoder::read_i64v (const uint8_t * pc, Name< ValidationTag > name = `signed LEB64`) [inline]
Definition at line 185 of file decoder.h.
                                                                    {
    return read_leb<int64_t, ValidationTag, kNoTrace>(pc, name);
  }
References v8::internal::wasm::name(), and pc().
read_leb()
template<typename IntType , typename ValidationTag , TraceFlag trace, size_t size_in_bits = 8 * sizeof(IntType)>
std::pair<IntType, uint32_t> v8::internal::wasm::Decoder::read_leb (const uint8_t * pc, Name< ValidationTag > name = `varint`) [inline], [private]
Definition at line 492 of file decoder.h.
                                                              {
    static_assert(size_in_bits <= 8 * sizeof(IntType),
                  "leb does not fit in type");
    TRACE_IF(trace, " +%u %-20s: ", pc_offset(),
             implicit_cast<const char*>(name));
    // Fast path for single-byte integers.
    if (V8_LIKELY((!ValidationTag::validate || pc < end_) && !(*pc & 0x80))) {
      TRACE_IF(trace, "%02x ", *pc);
      IntType result = *pc;
      if (std::is_signed_v<IntType>) {
        // Perform sign extension.
        constexpr int sign_ext_shift = int{8 * sizeof(IntType)} - 7;
        result = (result << sign_ext_shift) >> sign_ext_shift;
        TRACE_IF(trace, "= %" PRIi64 "\n", static_cast<int64_t>(result));
      } else {
        TRACE_IF(trace, "= %" PRIu64 "\n", static_cast<uint64_t>(result));
      }
      return {result, 1};
    }
    auto [result, length] =
        read_leb_slowpath<IntType, ValidationTag, trace, size_in_bits>(pc,
                                                                       name);
    V8_ASSUME(length >= 0 && length <= (size_in_bits + 6) / 7);
    V8_ASSUME(ValidationTag::validate || length >= 1);
    return {result, length};
  }
References end_, v8::internal::length, v8::internal::wasm::name(), pc(), pc_offset(), v8::base::internal::result, TRACE_IF, V8_ASSUME, and V8_LIKELY.
read_leb_slowpath()
template<typename IntType , typename ValidationTag , TraceFlag trace, size_t size_in_bits = 8 * sizeof(IntType)>
V8_NOINLINE V8_PRESERVE_MOST std::pair<IntType, uint32_t> v8::internal::wasm::Decoder::read_leb_slowpath (const uint8_t * pc, Name< ValidationTag > name) [inline], [private]
Definition at line 522 of file decoder.h.
                                                   {
    // Create an unrolled LEB decoding function per integer type.
    return read_leb_tail<IntType, ValidationTag, trace, size_in_bits, 0>(
        pc, name, 0);
  }
References v8::internal::wasm::name(), and pc().
read_leb_tail()
template<typename IntType , typename ValidationTag , TraceFlag trace, size_t size_in_bits, int byte_index>
std::pair<IntType, uint32_t> v8::internal::wasm::Decoder::read_leb_tail (const uint8_t * pc, Name< ValidationTag > name, IntType intermediate_result) [inline], [private]
Definition at line 531 of file decoder.h.
                                   {
    constexpr bool is_signed = std::is_signed_v<IntType>;
    constexpr int kMaxLength = (size_in_bits + 6) / 7;
    static_assert(byte_index < kMaxLength, "invalid template instantiation");
    constexpr int shift = byte_index * 7;
    constexpr bool is_last_byte = byte_index == kMaxLength - 1;
    const bool at_end = ValidationTag::validate && pc >= end_;
    uint8_t b = 0;
    if (V8_LIKELY(!at_end)) {
      DCHECK_LT(pc, end_);
      b = *pc;
      TRACE_IF(trace, "%02x ", b);
      using Unsigned = std::make_unsigned_t<IntType>;
      intermediate_result |=
          (static_cast<Unsigned>(static_cast<IntType>(b) & 0x7f) << shift);
    }
    if (!is_last_byte && (b & 0x80)) {
      // Make sure that we only instantiate the template for valid byte indexes.
      // Compilers are not smart enough to figure out statically that the
      // following call is unreachable if is_last_byte is false.
      constexpr int next_byte_index = byte_index + (is_last_byte ? 0 : 1);
      return read_leb_tail<IntType, ValidationTag, trace, size_in_bits,
                           next_byte_index>(pc + 1, name, intermediate_result);
    }
    if (ValidationTag::validate && V8_UNLIKELY(at_end || (b & 0x80))) {
      TRACE_IF(trace, at_end ? "<end> " : "<length overflow> ");
      errorf(pc, "%s while decoding %s",
             at_end ? "reached end" : "length overflow", name);
      return {0, 0};
    }
    if constexpr (is_last_byte) {
      // A signed-LEB128 must sign-extend the final byte, excluding its
      // most-significant bit; e.g. for a 32-bit LEB128:
      // kExtraBits = 4 (== 32 - (5-1) * 7)
      // For unsigned values, the extra bits must be all zero.
      // For signed values, the extra bits *plus* the most significant bit must
      // either be 0, or all ones.
      constexpr int kExtraBits = size_in_bits - ((kMaxLength - 1) * 7);
      constexpr int kSignExtBits = kExtraBits - (is_signed ? 1 : 0);
      const uint8_t checked_bits = b & (0xFF << kSignExtBits);
      constexpr uint8_t kSignExtendedExtraBits = 0x7f & (0xFF << kSignExtBits);
      const bool valid_extra_bits =
          checked_bits == 0 ||
          (is_signed && checked_bits == kSignExtendedExtraBits);
      if (!ValidationTag::validate) {
        DCHECK(valid_extra_bits);
      } else if (V8_UNLIKELY(!valid_extra_bits)) {
        error(pc, "extra bits in varint");
        return {0, 0};
      }
    }
    constexpr int sign_ext_shift =
        is_signed ? std::max(0, int{8 * sizeof(IntType)} - shift - 7) : 0;
    // Perform sign extension.
    intermediate_result =
        (intermediate_result << sign_ext_shift) >> sign_ext_shift;
    if (trace && is_signed) {
      TRACE("= %" PRIi64 "\n", static_cast<int64_t>(intermediate_result));
    } else if (trace) {
      TRACE("= %" PRIu64 "\n", static_cast<uint64_t>(intermediate_result));
    }
    const uint32_t length = byte_index + 1;
    return {intermediate_result, length};
  }
References v8::internal::DCHECK(), DCHECK_LT, end_, error(), errorf(), v8::internal::is_signed(), v8::internal::length, v8::internal::wasm::name(), pc(), v8::internal::TRACE(), TRACE_IF, v8::base::bits::Unsigned(), V8_LIKELY, and V8_UNLIKELY.
read_little_endian()
template<typename IntType , typename ValidationTag >
IntType v8::internal::wasm::Decoder::read_little_endian (const uint8_t * pc, Name< ValidationTag > msg) [inline], [private]
Definition at line 460 of file decoder.h.
                                                                         {
    DCHECK_LE(start_, pc);
    if (!ValidationTag::validate) {
      DCHECK_LE(pc, end_);
      DCHECK_LE(sizeof(IntType), end_ - pc);
    } else if (V8_UNLIKELY(ptrdiff_t{sizeof(IntType)} > end_ - pc)) {
      error(pc, msg);
      return 0;
    }
    return base::ReadLittleEndianValue<IntType>(reinterpret_cast<Address>(pc));
  }
References DCHECK_LE, end_, error(), pc(), start_, and V8_UNLIKELY.
read_prefixed_opcode()
template<typename ValidationTag >
std::pair<WasmOpcode, uint32_t> v8::internal::wasm::Decoder::read_prefixed_opcode (const uint8_t * pc, Name< ValidationTag > name = `prefixed opcode`) [inline]
Definition at line 202 of file decoder.h.
                                                                       {
    // Prefixed opcodes all use LEB128 encoding.
    auto [index, index_length] =
        read_u32v<ValidationTag>(pc + 1, "prefixed opcode index");
    uint32_t length = index_length + 1; // 1 for prefix byte.
    // Only support opcodes that go up to 0xFFF (when decoded). Anything
    // bigger will need more than 2 bytes, and the '<< 12' below will be wrong.
    if (ValidationTag::validate && V8_UNLIKELY(index > 0xfff)) {
      errorf(pc, "Invalid prefixed opcode %d", index);
      // On validation failure we return "unreachable" (opcode 0).
      static_assert(kExprUnreachable == 0);
      return {kExprUnreachable, 0};
    }
    if (index > 0xff) {
      return {static_cast<WasmOpcode>((*pc) << 12 | index), length};
    }
    return {static_cast<WasmOpcode>((*pc) << 8 | index), length};
  }
References errorf(), v8::internal::index, v8::internal::length, pc(), and V8_UNLIKELY.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::NextInstruction(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength(), and v8::internal::RUNTIME_FUNCTION().
read_u16()
template<typename ValidationTag >
uint16_t v8::internal::wasm::Decoder::read_u16 (const uint8_t * pc, Name< ValidationTag > msg = `expected 2 bytes`) [inline]
Definition at line 139 of file decoder.h.
                                                                  {
    return read_little_endian<uint16_t, ValidationTag>(pc, msg);
  }
References pc().
read_u32()
template<typename ValidationTag >
uint32_t v8::internal::wasm::Decoder::read_u32 (const uint8_t * pc, Name< ValidationTag > msg = `expected 4 bytes`) [inline]
Definition at line 146 of file decoder.h.
                                                                  {
    return read_little_endian<uint32_t, ValidationTag>(pc, msg);
  }
References pc().
read_u32v()
template<typename ValidationTag >
std::pair<uint32_t, uint32_t> v8::internal::wasm::Decoder::read_u32v (const uint8_t * pc, Name< ValidationTag > name = `LEB32`) [inline]
Definition at line 161 of file decoder.h.
                                                                              {
    return read_leb<uint32_t, ValidationTag, kNoTrace>(pc, name);
  }
References v8::internal::wasm::name(), and pc().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BranchTable(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrTable(), v8::internal::wasm::MemoryAccessImmediate::ConstructSlow(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::EffectHandlerTable(), v8::internal::wasm::BranchTableIterator< ValidationTag >::next(), v8::internal::wasm::value_type_reader::read_heap_type(), v8::internal::wasm::WasmBytecodeGenerator::ScanConstInstructions(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable().
read_u64()
template<typename ValidationTag >
uint64_t v8::internal::wasm::Decoder::read_u64 (const uint8_t * pc, Name< ValidationTag > msg = `expected 8 bytes`) [inline]
Definition at line 153 of file decoder.h.
                                                                  {
    return read_little_endian<uint64_t, ValidationTag>(pc, msg);
  }
References pc().
read_u64v()
template<typename ValidationTag >
std::pair<uint64_t, uint32_t> v8::internal::wasm::Decoder::read_u64v (const uint8_t * pc, Name< ValidationTag > name = `LEB64`) [inline]
Definition at line 177 of file decoder.h.
                                                                              {
    return read_leb<uint64_t, ValidationTag, kNoTrace>(pc, name);
  }
References v8::internal::wasm::name(), and pc().
Referenced by v8::internal::wasm::MemoryAccessImmediate::ConstructSlow().
read_u8()
template<typename ValidationTag >
uint8_t v8::internal::wasm::Decoder::read_u8 (const uint8_t * pc, Name< ValidationTag > msg = `expected 1 byte`) [inline]
Definition at line 132 of file decoder.h.
                                                               {
    return read_little_endian<uint8_t, ValidationTag>(pc, msg);
  }
References pc().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::EffectHandlerTable(), v8::internal::wasm::TryTableIterator< ValidationTag >::next(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::next(), v8::internal::wasm::value_type_reader::read_heap_type(), v8::internal::wasm::value_type_reader::read_value_type(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable().
Reset() [1/2]
void v8::internal::wasm::Decoder::Reset (base::Vector< const uint8_t > bytes, uint32_t buffer_offset = 0) [inline]
Definition at line 398 of file decoder.h.
                                                                          {
    Reset(bytes.begin(), bytes.end(), buffer_offset);
  }
References v8::base::Vector< T >::begin(), buffer_offset(), v8::base::Vector< T >::end(), and Reset().
Reset() [2/2]
void v8::internal::wasm::Decoder::Reset (const uint8_t * start, const uint8_t * end, uint32_t buffer_offset = 0) [inline]
Definition at line 387 of file decoder.h.
                                         {
    DCHECK_LE(start, end);
    DCHECK_EQ(static_cast<uint32_t>(end - start), end - start);
    start_ = start;
    pc_ = start;
    end_ = end;
    buffer_offset_ = buffer_offset;
    error_ = {};
  }
References buffer_offset(), buffer_offset_, DCHECK_EQ, DCHECK_LE, end(), end_, error_, pc_, start(), and start_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection(), and Reset().
set_end()
void v8::internal::wasm::Decoder::set_end (const uint8_t * end) [inline]
Definition at line 427 of file decoder.h.
{ end_ = end; }
References end(), and end_.
Referenced by v8::internal::wasm::WasmSectionIterator::next().
start()
const uint8_t* v8::internal::wasm::Decoder::start () const [inline]
Definition at line 407 of file decoder.h.
{ return start_; }
References start_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSignatureForTesting(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), Decoder(), v8::internal::wasm::IdentifyUnknownSectionInternal(), Reset(), traceByteRange(), and v8::internal::wasm::validate_utf8().
toResult()
template<typename T , typename R = std::decay_t<T>>
Result<R> v8::internal::wasm::Decoder::toResult (T && val) [inline]
Definition at line 378 of file decoder.h.
                              {
    if (failed()) {
      TRACE("Result error: %s\n", error_.message().c_str());
      return Result<R>{error_};
    }
    return Result<R>{std::forward<T>(val)};
  }
References error_, failed(), v8::internal::wasm::WasmError::message(), and v8::internal::TRACE().
Referenced by v8::internal::wasm::DecodeAsmJsOffsets(), v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::ModuleDecoderImpl::FinishDecoding(), and v8::internal::wasm::ValidateFunctionBody().
traceByteRange()
void v8::internal::wasm::Decoder::traceByteRange (const uint8_t * start, const uint8_t * end) [inline]
Definition at line 365 of file decoder.h.
                                                                {
    DCHECK_LE(start, end);
    for (const uint8_t* p = start; p < end; ++p) TRACE("%02x ", *p);
  }
References DCHECK_LE, end(), start(), and v8::internal::TRACE().
Referenced by consume_little_endian(), and traceOffEnd().
traceOffEnd()
void v8::internal::wasm::Decoder::traceOffEnd () [inline]
Definition at line 371 of file decoder.h.
                     {
    traceByteRange(pc_, end_);
    TRACE("<end>\n");
  }
References end_, pc_, v8::internal::TRACE(), and traceByteRange().
Referenced by consume_little_endian().
va_end()
v8::internal::wasm::Decoder::va_end (args) [private]
va_start()
v8::internal::wasm::Decoder::va_start (args , format) [private]
Member Data Documentation
args
va_list v8::internal::wasm::Decoder::args [private]
Definition at line 450 of file decoder.h.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), and errorf().
buffer
base::EmbeddedVector<char, kMaxErrorMsg> v8::internal::wasm::Decoder::buffer [private]
Definition at line 449 of file decoder.h.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::PrintHexNumber().
buffer_offset_
uint32_t v8::internal::wasm::Decoder::buffer_offset_ [protected]
Definition at line 440 of file decoder.h.
Referenced by buffer_offset(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeBuildIdSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDescriptorsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExternalDebugInfoSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSourceMappingURLSection(), GetBufferRelativeOffset(), v8::internal::wasm::DescriptorsSectionIterator::NumImportAndDeclEntries(), v8::internal::wasm::ModuleDecoderImpl::off(), pc_offset(), and Reset().
end_
const uint8_t* v8::internal::wasm::Decoder::end_ [protected]
Definition at line 438 of file decoder.h.
Referenced by available_bytes(), consume_bytes(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), consume_little_endian(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeBuildIdSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDescriptorsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExternalDebugInfoSection(), v8::internal::wasm::FunctionBodyDisassembler::DecodeGlobalInitializer(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting(), v8::internal::wasm::ModuleDecoderImpl::DecodeSourceMappingURLSection(), end(), lookahead(), more(), v8::internal::wasm::DescriptorsSectionIterator::NumImportAndDeclEntries(), v8::internal::wasm::ModuleDecoderImpl::onFirstError(), read_leb(), read_leb_tail(), read_little_endian(), Reset(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SafeOpcodeNameAt(), set_end(), and traceOffEnd().
error_ [1/2]
WasmError v8::internal::wasm::Decoder::error_ [protected]
Definition at line 441 of file decoder.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting(), error(), failed(), Reset(), toResult(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TraceFailed().
error_ [2/2]
v8::internal::wasm::Decoder::error_ = {offset, {buffer.begin(), static_cast<size_t>(len)}} [private]
Definition at line 455 of file decoder.h.
format
void V8_NOINLINE const char* v8::internal::wasm::Decoder::format [private]
Definition at line 445 of file decoder.h.
Referenced by errorf().
kFullValidation
constexpr struct v8::internal::wasm::Decoder::FullValidationTag v8::internal::wasm::Decoder::kFullValidation = {} [static]
kMaxErrorMsg
void V8_NOINLINE const char constexpr int v8::internal::wasm::Decoder::kMaxErrorMsg = 256 [constexpr], [private]
Definition at line 448 of file decoder.h.
kNoValidation
constexpr struct v8::internal::wasm::Decoder::NoValidationTag v8::internal::wasm::Decoder::kNoValidation = {} [static]
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeAtomicOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeGCOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::DecodeNumericOp(), and v8::internal::wasm::WasmBytecodeGenerator::DecodeSimdOp().
len
int v8::internal::wasm::Decoder::len = base::VSNPrintF(buffer, format, args) [private]
Definition at line 452 of file decoder.h.
pc_
const uint8_t* v8::internal::wasm::Decoder::pc_ [protected]
Definition at line 437 of file decoder.h.
Referenced by available_bytes(), checkAvailable(), consume_bytes(), v8::internal::wasm::ModuleDecoderImpl::consume_count(), v8::internal::wasm::ModuleDecoderImpl::consume_exception_attribute(), v8::internal::wasm::ModuleDecoderImpl::consume_global_flags(), v8::internal::wasm::ModuleDecoderImpl::consume_heap_type(), consume_i32v(), consume_i64v(), v8::internal::wasm::ModuleDecoderImpl::consume_index(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte(), consume_little_endian(), v8::internal::wasm::ModuleDecoderImpl::consume_mutability(), v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), v8::internal::wasm::ModuleDecoderImpl::consume_tag_sig_index(), consume_u32(), consume_u32v(), consume_u64v(), consume_u8(), v8::internal::wasm::ModuleDecoderImpl::consume_value_type(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeBuildIdSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExternalDebugInfoSection(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionBody(), v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSignatureForTesting(), v8::internal::wasm::FunctionBodyDisassembler::DecodeGlobalInitializer(), v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting(), v8::internal::wasm::ModuleDecoderImpl::DecodeSourceMappingURLSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStartSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTagSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::FunctionBodyDisassembler::GetOpcode(), lookahead(), more(), v8::internal::wasm::DescriptorsSectionIterator::NextSubsection(), v8::internal::wasm::ModuleDecoderImpl::onFirstError(), pc(), pc_offset(), position(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::position(), v8::internal::wasm::FunctionBodyDisassembler::PrintImmediatesAndGetLength(), Reset(), and traceOffEnd().
start_
const uint8_t* v8::internal::wasm::Decoder::start_ [protected]
Definition at line 436 of file decoder.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeBuildIdSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDescriptorsSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExternalDebugInfoSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting(), v8::internal::wasm::ModuleDecoderImpl::DecodeSourceMappingURLSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTagSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), v8::internal::wasm::DescriptorsSectionIterator::DescriptorsSectionIterator(), v8::internal::wasm::DescriptorsSectionIterator::NumImportAndDeclEntries(), v8::internal::wasm::ModuleDecoderImpl::off(), pc_offset(), position(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::position(), read_little_endian(), Reset(), and start().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/decoder.h