v8::Eternal< T > Class Template Reference
Eternal handles are set-once handles that live for the lifetime of the isolate.
#include <v8-persistent-handle.h>
Public Member Functions
Eternal ()=default
template<class S >
requires (std::is_base_of_v< T, S >) inline Eternal(Isolate *isolate
Constructor for handling automatic up casting.
Local< T > Get (Isolate *isolate) const
template<class S >
requires (std::is_base_of_v< T, S >) void Set(Isolate *isolate
Public Attributes
Local< S > handle
Additional Inherited Members
Detailed Description
template<class T>
class v8::Eternal< T >
Eternal handles are set-once handles that live for the lifetime of the isolate.
Definition at line 45 of file v8-persistent-handle.h.
Constructor & Destructor Documentation
Eternal()
template<class T >
v8::Eternal< T >::Eternal () [inline], [default]
Member Function Documentation
Get()
template<class T >
Local<T> v8::Eternal< T >::Get (Isolate * isolate) const [inline]
Definition at line 59 of file v8-persistent-handle.h.
                                                 {
    // The eternal handle will never go away, so as with the roots, we don't
    // even need to open a handle.
    return Local<T>::FromSlot(slot());
  }
References v8::Local< T >::FromSlot(), and v8::api_internal::IndirectHandleBase::slot().
Referenced by wasm::StoreImpl::context().
requires() [1/2]
template<class T >
template<class S >
v8::Eternal< T >::requires (std::is_base_of_v< T, S >)
Constructor for handling automatic up casting.
requires() [2/2]
template<class T >
template<class S >
v8::Eternal< T >::requires (std::is_base_of_v< T, S >)
References v8::api_internal::Eternalize(), v8::Eternal< T >::handle, and v8::api_internal::IndirectHandleBase::slot().
Member Data Documentation
handle
template<class T >
Local< S > v8::Eternal< T >::handle
Initial value:
{
    Set(isolate, handle)
Definition at line 54 of file v8-persistent-handle.h.
Referenced by v8::Eternal< T >::requires().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-local-handle.h
/mnt/V8SourceCode/include/v8-persistent-handle.h