v8::internal::compiler::Assessment Class Reference
#include <register-allocator-verifier.h>
Public Member Functions
Assessment (const Assessment &)=delete
Assessment & operator= (const Assessment &)=delete
AssessmentKind kind () const
Protected Member Functions
Assessment (AssessmentKind kind)
Protected Attributes
AssessmentKind kind_
Detailed Description
Definition at line 57 of file register-allocator-verifier.h.
Constructor & Destructor Documentation
Assessment() [1/2]
v8::internal::compiler::Assessment::Assessment (const Assessment &) [delete]
Assessment() [2/2]
v8::internal::compiler::Assessment::Assessment (AssessmentKind kind) [inline], [explicit], [protected]
Definition at line 65 of file register-allocator-verifier.h.
: kind_(kind) {}
Member Function Documentation
kind()
AssessmentKind v8::internal::compiler::Assessment::kind () const [inline]
Definition at line 62 of file register-allocator-verifier.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::compiler::PendingAssessment::cast(), v8::internal::compiler::FinalAssessment::cast(), v8::internal::compiler::BlockAssessments::Print(), v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment(), and v8::internal::compiler::RegisterAllocatorVerifier::ValidateUse().
operator=()
Assessment& v8::internal::compiler::Assessment::operator= (const Assessment &) [delete]
Member Data Documentation
kind_
AssessmentKind v8::internal::compiler::Assessment::kind_ [protected]
Definition at line 66 of file register-allocator-verifier.h.
Referenced by kind().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/register-allocator-verifier.h