v8::internal::compiler::turboshaft::LoopPeelingReducer< Next > Class Template Reference
#include <loop-peeling-reducer.h>
Public Member Functions
V< None > REDUCE_INPUT_GRAPH() Goto (V< None > ig_idx, const GotoOp &gto)
V< None > REDUCE_INPUT_GRAPH() JSStackCheck (V< None > ig_idx, const JSStackCheckOp &stack_check)
OpIndex REDUCE_INPUT_GRAPH() Phi (OpIndex ig_idx, const PhiOp &phi)
Private Types
enum class PeelingStatus { kNotPeeling
, kEmittingPeeledLoop
, kEmittingUnpeeledBody
 }
Private Member Functions
void PeelFirstIteration (const Block *header)
bool CanPeelLoop (const Block *header)
bool IsPeeling () const
bool IsEmittingPeeledIteration () const
bool IsEmittingUnpeeledBody () const
Private Attributes
PeelingStatus peeling_ = PeelingStatus::kNotPeeling
const Block * current_loop_header_ = nullptr
LoopFinder loop_finder_
JSHeapBroker * broker_ = __ data() -> broker()
Static Private Attributes
static constexpr int kMaxSizeForPeeling = 1000
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >
Definition at line 38 of file loop-peeling-reducer.h.
Member Enumeration Documentation
PeelingStatus
template<class Next >
enum v8::internal::compiler::turboshaft::LoopPeelingReducer::PeelingStatus [strong], [private]
Enumerator
kNotPeeling
kEmittingPeeledLoop
kEmittingUnpeeledBody
Definition at line 107 of file loop-peeling-reducer.h.
                           {
    kNotPeeling,
    kEmittingPeeledLoop,
    kEmittingUnpeeledBody
  };
Member Function Documentation
CanPeelLoop()
template<class Next >
bool v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::CanPeelLoop (const Block * header) [inline], [private]
Definition at line 145 of file loop-peeling-reducer.h.
                                        {
    TRACE("LoopPeeling: considering " << header->index());
    if (IsPeeling()) {
      TRACE("> Cannot peel because we're already peeling a loop");
      return false;
    }
    auto info = loop_finder_.GetLoopInfo(header);
    if (info.has_inner_loops) {
      TRACE("> Cannot peel because it has inner loops");
      return false;
    }
    if (info.op_count > kMaxSizeForPeeling) {
      TRACE("> Cannot peel because it contains too many operations");
      return false;
    }
    return true;
  }
References v8::internal::compiler::turboshaft::LoopFinder::GetLoopInfo(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsPeeling(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::kMaxSizeForPeeling, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::loop_finder_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Goto().
Goto()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Goto (V< None > ig_idx, const GotoOp & gto) [inline]
Definition at line 49 of file loop-peeling-reducer.h.
                                                                      {
    // Note that the "ShouldSkipOptimizationStep" is placed in the part of
    // this Reduce method triggering the peeling rather than at the begining.
    // This is because the backedge skipping is not an optimization but a
    // mandatory lowering when peeling is being performed.
    LABEL_BLOCK(no_change) { return Next::ReduceInputGraphGoto(ig_idx, gto); }
    const Block* dst = gto.destination;
    if (dst->IsLoop() && !gto.is_backedge && CanPeelLoop(dst)) {
      if (ShouldSkipOptimizationStep()) goto no_change;
      PeelFirstIteration(dst);
      return {};
    } else if (IsEmittingPeeledIteration() && dst == current_loop_header_) {
      // We skip the backedge of the loop: PeelFirstIeration will instead emit a
      // forward edge to the non-peeled header.
      return {};
    }
    goto no_change;
  }
References v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::CanPeelLoop(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::current_loop_header_, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingPeeledIteration(), v8::internal::compiler::turboshaft::Block::IsLoop(), LABEL_BLOCK, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::PeelFirstIteration(), and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
IsEmittingPeeledIteration()
template<class Next >
bool v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingPeeledIteration () const [inline], [private]
Definition at line 166 of file loop-peeling-reducer.h.
                                         {
    return peeling_ == PeelingStatus::kEmittingPeeledLoop;
  }
References v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::kEmittingPeeledLoop, and v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::peeling_.
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Goto(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsPeeling(), and v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::JSStackCheck().
IsEmittingUnpeeledBody()
template<class Next >
bool v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingUnpeeledBody () const [inline], [private]
Definition at line 169 of file loop-peeling-reducer.h.
                                      {
    return peeling_ == PeelingStatus::kEmittingUnpeeledBody;
  }
References v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::kEmittingUnpeeledBody, and v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::peeling_.
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsPeeling(), and v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Phi().
IsPeeling()
template<class Next >
bool v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsPeeling () const [inline], [private]
Definition at line 163 of file loop-peeling-reducer.h.
                         {
    return IsEmittingPeeledIteration() || IsEmittingUnpeeledBody();
  }
References v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingPeeledIteration(), and v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingUnpeeledBody().
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::CanPeelLoop().
JSStackCheck()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::JSStackCheck (V< None > ig_idx, const JSStackCheckOp & stack_check) [inline]
Definition at line 70 of file loop-peeling-reducer.h.
                                                                              {
    if (ShouldSkipOptimizationStep() || !IsEmittingPeeledIteration()) {
      return Next::ReduceInputGraphJSStackCheck(ig_idx, stack_check);
    }
    // We remove the stack check of the peeled iteration.
    return V<None>::Invalid();
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingPeeledIteration(), and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
PeelFirstIteration()
template<class Next >
void v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::PeelFirstIteration (const Block * header) [inline], [private]
Definition at line 113 of file loop-peeling-reducer.h.
                                               {
    TRACE("LoopPeeling: peeling loop at " << header->index());
    DCHECK_EQ(peeling_, PeelingStatus::kNotPeeling);
    ScopedModification<PeelingStatus> scope(&peeling_,
                                            PeelingStatus::kEmittingPeeledLoop);
    current_loop_header_ = header;
    // Emitting the peeled iteration.
    auto loop_body = loop_finder_.GetLoopBody(header);
    // Note that this call to CloneSubGraph will not emit the backedge because
    // we'll skip it in ReduceInputGraphGoto (above). The next CloneSubGraph
    // call will start with a forward Goto to the header (like all
    // CloneSubGraphs do), and will end by emitting the backedge, because this
    // time {peeling_} won't be EmittingPeeledLoop, and the backedge Goto will
    // thus be emitted.
    TRACE("> Emitting peeled iteration");
    __ CloneSubGraph(loop_body, /* keep_loop_kinds */ false);
    if (__ generating_unreachable_operations()) {
      // While peeling, we realized that the 2nd iteration of the loop is not
      // reachable.
      TRACE("> Second iteration is not reachable, stopping now");
      return;
    }
    // We now emit the regular unpeeled loop.
    peeling_ = PeelingStatus::kEmittingUnpeeledBody;
    TRACE("> Emitting unpeeled loop body");
    __ CloneSubGraph(loop_body, /* keep_loop_kinds */ true,
                     /* is_loop_after_peeling */ true);
  }
References __, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::current_loop_header_, DCHECK_EQ, v8::internal::compiler::turboshaft::LoopFinder::GetLoopBody(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::kEmittingPeeledLoop, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::kEmittingUnpeeledBody, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::kNotPeeling, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::loop_finder_, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::peeling_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Goto().
Phi()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Phi (OpIndex ig_idx, const PhiOp & phi) [inline]
Definition at line 92 of file loop-peeling-reducer.h.
                                                                    {
    if (!IsEmittingUnpeeledBody() ||
        __ current_input_block() != current_loop_header_) {
      return Next::ReduceInputGraphPhi(ig_idx, phi);
    }
    // The 1st input of the loop phis of the unpeeled loop header should be the
    // 2nd input of the original loop phis, since with the peeling, they
    // actually come from the backedge of the peeled iteration.
    return __ PendingLoopPhi(
        __ MapToNewGraph(phi.input(PhiOp::kLoopPhiBackEdgeIndex)), phi.rep);
  }
References __, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::current_loop_header_, v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingUnpeeledBody(), and v8::internal::compiler::turboshaft::PhiOp::kLoopPhiBackEdgeIndex.
Member Data Documentation
broker_
template<class Next >
JSHeapBroker* v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::broker_ = __ data() -> broker() [private]
Definition at line 178 of file loop-peeling-reducer.h.
current_loop_header_
template<class Next >
const Block* v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::current_loop_header_ = nullptr [private]
Definition at line 174 of file loop-peeling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Goto(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::PeelFirstIteration(), and v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Phi().
kMaxSizeForPeeling
template<class Next >
constexpr int v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::kMaxSizeForPeeling = 1000 [static], [constexpr], [private]
Definition at line 106 of file loop-peeling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::CanPeelLoop().
loop_finder_
template<class Next >
LoopFinder v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::loop_finder_ [private]
Initial value:
{__ phase_zone(), &__ modifiable_input_graph(),
                          LoopFinder::Config{}}
Definition at line 176 of file loop-peeling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::CanPeelLoop(), and v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::PeelFirstIteration().
peeling_
template<class Next >
PeelingStatus v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::peeling_ = PeelingStatus::kNotPeeling [private]
Definition at line 173 of file loop-peeling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingPeeledIteration(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::IsEmittingUnpeeledBody(), and v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::PeelFirstIteration().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/loop-peeling-reducer.h