v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob Class Reference
Public Member Functions
~CodeAssemblerTurboshaftCompilationJob () final
CodeAssemblerTurboshaftCompilationJob (const CodeAssemblerTurboshaftCompilationJob &)=delete
CodeAssemblerTurboshaftCompilationJob & operator= (const CodeAssemblerTurboshaftCompilationJob &)=delete
Status ExecuteJobImpl (RuntimeCallStats *stats, LocalIsolate *local_isolate) final
CodeAssemblerCompilationJob (Isolate *isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions &assembler_options, std::function< compiler::CallDescriptor *(Zone *)> get_call_descriptor, CodeKind code_kind, const char *name, const ProfileDataFromFile *profile_data, int finalize_order)
CodeAssemblerCompilationJob (const CodeAssemblerCompilationJob &)=delete
Private Member Functions
PipelineImpl * EmplacePipeline (Isolate *isolate) final
Handle< Code > FinalizeCode (Isolate *isolate) final
Private Attributes
std::optional< TFDataAndPipeline > pipeline_
std::optional< turboshaft::PipelineData > turboshaft_data_
Additional Inherited Members
Detailed Description
Definition at line 2383 of file pipeline.cc.
Constructor & Destructor Documentation
 CodeAssemblerTurboshaftCompilationJob()
v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::~CodeAssemblerTurboshaftCompilationJob () [final], [default]
CodeAssemblerTurboshaftCompilationJob()
v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::CodeAssemblerTurboshaftCompilationJob (const CodeAssemblerTurboshaftCompilationJob &) [delete]
Member Function Documentation
CodeAssemblerCompilationJob() [1/2]
v8::internal::compiler::CodeAssemblerCompilationJob::CodeAssemblerCompilationJob [delete]
CodeAssemblerCompilationJob() [2/2]
v8::internal::compiler::CodeAssemblerCompilationJob::CodeAssemblerCompilationJob
Definition at line 31 of file pipeline.cc.
    : TurbofanCompilationJob(isolate, &compilation_info_,
                             State::kReadyToPrepare),
      generator_(generator),
      installer_(installer),
      profile_data_(profile_data),
      zone_(isolate->allocator(), ZONE_NAME),
      zone_stats_(isolate->allocator()),
      code_assembler_state_(isolate, &zone_, get_call_descriptor(&zone_),
                            code_kind, name, builtin),
      assembler_options_(assembler_options),
      compilation_info_(base::CStrVector(name), &zone_, code_kind),
      jump_opt_(ShouldOptimizeJumps(isolate) ? new JumpOptimizationInfo()
                                             : nullptr),
      finalize_order_(finalize_order) {
  DCHECK(code_kind == CodeKind::BUILTIN ||
         code_kind == CodeKind::BYTECODE_HANDLER ||
         code_kind == CodeKind::FOR_TESTING);
  compilation_info_.set_builtin(builtin);
}
References v8::internal::internal.
EmplacePipeline()
PipelineImpl * v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::EmplacePipeline (Isolate * isolate) [final], [private], [virtual]
Implements v8::internal::compiler::CodeAssemblerCompilationJob.
Definition at line 2409 of file pipeline.cc.
                      {
  pipeline_.emplace(this);
  turboshaft_data_.emplace(pipeline_->data.zone_stats(),
                           turboshaft::TurboshaftPipelineKind::kCSA, isolate,
                           pipeline_->data.info(), assembler_options_,
                           pipeline_->data.start_source_position());
  return &pipeline_->pipeline;
}
References v8::internal::compiler::CodeAssemblerCompilationJob::assembler_options_, v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::turboshaft::kCSA, pipeline_, and turboshaft_data_.
ExecuteJobImpl()
PipelineCompilationJob::Status v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl (RuntimeCallStats * stats, LocalIsolate * local_isolate) [final], [virtual]
Implements v8::internal::OptimizedCompilationJob.
Definition at line 2420 of file pipeline.cc.
                                                          {
  if (!pipeline_->pipeline.ComputeScheduledGraph()) return FAILED;
  DCHECK_NULL(pipeline_->data.frame());
  DCHECK_NOT_NULL(pipeline_->data.schedule());
  turboshaft::BuiltinPipeline turboshaft_pipeline(&turboshaft_data_.value());
  CallDescriptor* call_descriptor = raw_assembler()->call_descriptor();
  Linkage linkage(call_descriptor);
  CHECK(
      turboshaft_pipeline.CreateGraphFromTurbofan(&pipeline_->data, &linkage));
  turboshaft_pipeline.OptimizeBuiltin();
  CHECK_NULL(pipeline_->data.osr_helper_ptr());
  CHECK(turboshaft_pipeline.GenerateCode(
      &linkage, pipeline_->data.osr_helper_ptr(), jump_opt_.get(),
      profile_data_, initial_graph_hash_));
  return SUCCEEDED;
}
References v8::internal::compiler::RawMachineAssembler::call_descriptor(), CHECK, CHECK_NULL, v8::internal::compiler::turboshaft::Pipeline::CreateGraphFromTurbofan(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::CompilationJob::FAILED, v8::internal::compiler::turboshaft::Pipeline::GenerateCode(), v8::internal::compiler::CodeAssemblerCompilationJob::initial_graph_hash_, v8::internal::compiler::CodeAssemblerCompilationJob::jump_opt_, v8::internal::compiler::turboshaft::BuiltinPipeline::OptimizeBuiltin(), pipeline_, v8::internal::compiler::CodeAssemblerCompilationJob::profile_data_, v8::internal::compiler::CodeAssemblerCompilationJob::raw_assembler(), v8::internal::CompilationJob::SUCCEEDED, and turboshaft_data_.
FinalizeCode()
Handle< Code > v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::FinalizeCode (Isolate * isolate) [final], [private], [virtual]
Implements v8::internal::compiler::CodeAssemblerCompilationJob.
Definition at line 2443 of file pipeline.cc.
                      {
  PipelineJobScope scope(&pipeline_->data,
                         isolate->counters()->runtime_call_stats());
  turboshaft::Pipeline turboshaft_pipeline(&turboshaft_data_.value());
  turboshaft::Tracing::Scope tracing_scope(pipeline_->data.info());
  return turboshaft_pipeline.FinalizeCode().ToHandleChecked();
}
References v8::internal::Isolate::counters(), v8::internal::compiler::turboshaft::Pipeline::FinalizeCode(), v8::internal::TurbofanCompilationJob::isolate(), pipeline_, v8::internal::Counters::runtime_call_stats(), and turboshaft_data_.
operator=()
CodeAssemblerTurboshaftCompilationJob& v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::operator= (const CodeAssemblerTurboshaftCompilationJob &) [delete]
Member Data Documentation
pipeline_
std::optional<TFDataAndPipeline> v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::pipeline_ [private]
Definition at line 2402 of file pipeline.cc.
Referenced by EmplacePipeline(), ExecuteJobImpl(), and FinalizeCode().
turboshaft_data_
std::optional<turboshaft::PipelineData> v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::turboshaft_data_ [private]
Definition at line 2403 of file pipeline.cc.
Referenced by EmplacePipeline(), ExecuteJobImpl(), and FinalizeCode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc