v8::internal::Code Class Reference
#include <code.h>
Classes
class BodyDescriptor
Public Member Functions
PtrComprCageBase code_cage_base () const
Tagged< InstructionStream > unchecked_instruction_stream () const
bool has_instruction_stream () const
bool has_instruction_stream (RelaxedLoadTag) const
Address instruction_end () const
CodeEntrypointTag entrypoint_tag () const
CodeSandboxingMode sandboxing_mode () const
void SetInstructionStreamAndInstructionStart (IsolateForSandbox isolate, Tagged< InstructionStream > code, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void SetInstructionStartForOffHeapBuiltin (IsolateForSandbox isolate, Address entry)
void ClearInstructionStartForSerialization (IsolateForSandbox isolate)
void UpdateInstructionStart (IsolateForSandbox isolate, Tagged< InstructionStream > istream)
void initialize_flags (CodeKind kind, bool is_context_specialized, bool is_turbofanned)
void clear_padding ()
void FlushICache () const
uint16_t parameter_count_without_receiver () const
bool uses_deoptimization_data () const
void clear_deoptimization_data_and_interpreter_data ()
bool has_deoptimization_data_or_interpreter_data () const
Tagged< TrustedObject > bytecode_or_interpreter_data () const
void set_bytecode_or_interpreter_data (Tagged< TrustedObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
bool has_source_position_table_or_bytecode_offset_table () const
bool has_source_position_table () const
bool has_bytecode_offset_table () const
void clear_source_position_table_and_bytecode_offset_table ()
Tagged< ProtectedFixedArray > unchecked_deoptimization_data () const
CodeKind kind () const
void set_builtin_id (Builtin builtin_id)
Builtin builtin_id () const
bool is_builtin () const
bool is_optimized_code () const
bool is_wasm_code () const
bool is_interpreter_trampoline_builtin () const
bool is_baseline_trampoline_builtin () const
bool is_baseline_leave_frame_builtin () const
bool checks_tiering_state () const
bool has_tagged_outgoing_params () const
bool is_maglevved () const
bool is_turbofanned () const
bool is_context_specialized () const
bool uses_safepoint_table () const
uint32_t stack_slots () const
Tagged< TrustedByteArray > SourcePositionTable (Isolate *isolate, Tagged< SharedFunctionInfo > sfi) const
int SourcePosition (int offset) const
int SourceStatementPosition (int offset) const
Address safepoint_table_address () const
int safepoint_table_size () const
bool has_safepoint_table () const
Address handler_table_address () const
int handler_table_size () const
bool has_handler_table () const
Address constant_pool () const
int constant_pool_size () const
bool has_constant_pool () const
Address code_comments () const
int code_comments_size () const
bool has_code_comments () const
Address jump_table_info () const
int jump_table_info_size () const
bool has_jump_table_info () const
Address unwinding_info_start () const
Address unwinding_info_end () const
int unwinding_info_size () const
bool has_unwinding_info () const
uint8_t * relocation_start () const
uint8_t * relocation_end () const
int relocation_size () const
int safepoint_table_offset () const
Address body_start () const
Address body_end () const
int body_size () const
Address metadata_start () const
Address metadata_end () const
int InstructionStreamObjectSize () const
int SizeIncludingMetadata () const
Address InstructionStart (Isolate *isolate, Address pc) const
Address InstructionEnd (Isolate *isolate, Address pc) const
bool contains (Isolate *isolate, Address pc) const
int GetOffsetFromInstructionStart (Isolate *isolate, Address pc) const
SafepointEntry GetSafepointEntry (Isolate *isolate, Address pc)
MaglevSafepointEntry GetMaglevSafepointEntry (Isolate *isolate, Address pc)
void SetMarkedForDeoptimization (Isolate *isolate, LazyDeoptimizeReason reason)
void TraceMarkForDeoptimization (Isolate *isolate, LazyDeoptimizeReason reason)
bool CanContainWeakObjects ()
bool IsWeakObject (Tagged< HeapObject > object)
void ClearEmbeddedObjectsAndJSDispatchHandles (Heap *heap)
bool embedded_objects_cleared () const
void set_embedded_objects_cleared (bool flag)
bool IsIsolateIndependent (Isolate *isolate)
uintptr_t GetBaselineStartPCForBytecodeOffset (int bytecode_offset, Tagged< BytecodeArray > bytecodes)
uintptr_t GetBaselineEndPCForBytecodeOffset (int bytecode_offset, Tagged< BytecodeArray > bytecodes)
bool Inlines (Tagged< SharedFunctionInfo > sfi)
uintptr_t GetBaselinePCForNextExecutedBytecode (int bytecode_offset, Tagged< BytecodeArray > bytecodes)
int GetBytecodeOffsetForBaselinePC (Address baseline_pc, Tagged< BytecodeArray > bytecodes)
void IterateDeoptimizationLiterals (RootVisitor *v)
DEFINE_FIELD_OFFSET_CONSTANTS (ExposedTrustedObject::kHeaderSize, CODE_DATA_FIELDS) template< typename T > using ExternalCodeField
Static Public Member Functions
static bool IsWeakObjectInOptimizedCode (Tagged< HeapObject > object)
static bool IsWeakObjectInDeoptimizationLiteralArray (Tagged< Object > object)
static Tagged< Code > FromTargetAddress (Address address)
Static Public Attributes
static const int kMarkedForDeoptimizationBit
static const int kIsTurbofannedBit = IsTurbofannedField::kShift
static const int kArgumentsBits = 16
static const int kMaxArguments = (1 << kArgumentsBits) - 10
Private Types
enum BytecodeToPCPosition { kPcAtStartOfBytecode
, kPcAtEndOfBytecode
 }
Private Member Functions
void set_instruction_start (IsolateForSandbox isolate, Address value)
Tagged< Object > raw_deoptimization_data_or_interpreter_data () const
Tagged< Object > raw_position_table () const
uintptr_t GetBaselinePCForBytecodeOffset (int bytecode_offset, BytecodeToPCPosition position, Tagged< BytecodeArray > bytecodes)
OBJECT_CONSTRUCTORS (Code, ExposedTrustedObject)
Private Attributes
friend Factory
friend FactoryBase< Factory >
friend FactoryBase< LocalFactory >
Friends
template<typename IsolateT >
class Deserializer
Additional Inherited Members
Detailed Description
Definition at line 63 of file code.h.
Member Enumeration Documentation
BytecodeToPCPosition
enum v8::internal::Code::BytecodeToPCPosition [private]
Enumerator
kPcAtStartOfBytecode
kPcAtEndOfBytecode
Definition at line 499 of file code.h.
                            {
    kPcAtStartOfBytecode,
    // End of bytecode equals the start of the next bytecode.
    // We need it when we deoptimize to the next bytecode (lazy deopt or deopt
    // of non-topmost frame).
    kPcAtEndOfBytecode
  };
Member Function Documentation
body_end()
Address v8::internal::Code::body_end () const [inline]
Definition at line 222 of file code-inl.h.
{ return body_start() + body_size(); }
References body_size(), and body_start().
body_size()
int v8::internal::Code::body_size () const [inline]
Definition at line 224 of file code-inl.h.
{ return instruction_size() + metadata_size(); }
Referenced by body_end(), and InstructionStreamObjectSize().
body_start()
Address v8::internal::Code::body_start () const [inline]
Definition at line 220 of file code-inl.h.
{ return instruction_start(); }
Referenced by body_end().
builtin_id()
Builtin v8::internal::Code::builtin_id () const [inline]
Definition at line 934 of file code-inl.h.
                               {
  // Rely on sign-extension when converting int16_t to int to preserve
  // kNoBuiltinId value.
  static_assert(FIELD_SIZE(kBuiltinIdOffset) == kInt16Size);
  static_assert(static_cast<int>(static_cast<int16_t>(Builtin::kNoBuiltinId)) ==
                static_cast<int>(Builtin::kNoBuiltinId));
  int value = ReadField<int16_t>(kBuiltinIdOffset);
  return static_cast<Builtin>(value);
}
References FIELD_SIZE, v8::internal::kInt16Size, v8::internal::kNoBuiltinId, and v8::internal::value.
Referenced by checks_tiering_state(), entrypoint_tag(), has_tagged_outgoing_params(), InstructionStart(), is_baseline_leave_frame_builtin(), is_baseline_trampoline_builtin(), is_builtin(), is_interpreter_trampoline_builtin(), metadata_start(), sandboxing_mode(), and set_builtin_id().
bytecode_or_interpreter_data()
Tagged< TrustedObject > v8::internal::Code::bytecode_or_interpreter_data () const [inline]
Definition at line 135 of file code-inl.h.
                                                               {
  // It's important to CHECK that the Code object is baseline code. We trust
  // baseline code to have bytecode/interpreter data here, but the reference to
  // this code might be corrupted, such that we get type confusion on this field
  // in cases where we assume that it must be baseline code.
  SBXCHECK_EQ(kind(), CodeKind::BASELINE);
  return ReadProtectedPointerField(kDeoptimizationDataOrInterpreterDataOffset);
}
References kind(), v8::internal::TrustedObject::ReadProtectedPointerField(), and SBXCHECK_EQ.
Referenced by GetBaselinePCForBytecodeOffset().
CanContainWeakObjects()
bool v8::internal::Code::CanContainWeakObjects () [inline]
Definition at line 696 of file code-inl.h.
                                 {
  return is_optimized_code() && can_have_weak_objects();
}
References is_optimized_code().
Referenced by IsWeakObject().
checks_tiering_state()
bool v8::internal::Code::checks_tiering_state () const [inline]
Definition at line 419 of file code-inl.h.
                                             {
  bool checks_state = (builtin_id() == Builtin::kCompileLazy ||
                       builtin_id() == Builtin::kInterpreterEntryTrampoline ||
                       CodeKindCanTierUp(kind()));
  return checks_state ||
         (CodeKindCanDeoptimize(kind()) && marked_for_deoptimization());
}
References builtin_id(), v8::internal::CodeKindCanDeoptimize(), v8::internal::CodeKindCanTierUp(), and kind().
clear_deoptimization_data_and_interpreter_data()
void v8::internal::Code::clear_deoptimization_data_and_interpreter_data () [inline]
Definition at line 126 of file code-inl.h.
                                                                 {
  ClearProtectedPointerField(kDeoptimizationDataOrInterpreterDataOffset);
}
References v8::internal::TrustedObject::ClearProtectedPointerField().
clear_padding()
void v8::internal::Code::clear_padding () [inline]
Definition at line 905 of file code-inl.h.
                         {
  memset(reinterpret_cast<void*>(address() + kUnalignedSize), 0,
         kSize - kUnalignedSize);
}
References v8::internal::HeapObject::address().
clear_source_position_table_and_bytecode_offset_table()
void v8::internal::Code::clear_source_position_table_and_bytecode_offset_table () [inline]
Definition at line 199 of file code-inl.h.
                                                                 {
  TaggedField<Object, kPositionTableOffset>::store(*this, Smi::zero());
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store(), and v8::internal::Smi::zero().
ClearEmbeddedObjectsAndJSDispatchHandles()
void v8::internal::Code::ClearEmbeddedObjectsAndJSDispatchHandles (Heap * heap)
Definition at line 34 of file code.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  Tagged<HeapObject> undefined = ReadOnlyRoots(heap).undefined_value();
  Tagged<InstructionStream> istream = unchecked_instruction_stream();
  int mode_mask = RelocInfo::EmbeddedObjectModeMask();
#ifdef V8_ENABLE_LEAPTIERING
  mode_mask |= RelocInfo::JSDispatchHandleModeMask();
#endif
  {
    WritableJitAllocation jit_allocation = ThreadIsolation::LookupJitAllocation(
        istream->address(), istream->Size(),
        ThreadIsolation::JitAllocationType::kInstructionStream, true);
    for (WritableRelocIterator it(jit_allocation, istream, constant_pool(),
                                  mode_mask);
         !it.done(); it.next()) {
      const auto mode = it.rinfo()->rmode();
      if (RelocInfo::IsEmbeddedObjectMode(mode)) {
        it.rinfo()->set_target_object(istream, undefined, SKIP_WRITE_BARRIER);
#ifdef V8_ENABLE_LEAPTIERING
      } else {
        it.rinfo()->set_js_dispatch_handle(istream, kNullJSDispatchHandle,
                                           SKIP_WRITE_BARRIER);
#endif // V8_ENABLE_LEAPTIERING
      }
    }
  }
  set_embedded_objects_cleared(true);
}
References v8::internal::Tagged< HeapObject >::address(), constant_pool(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::RelocInfo::EmbeddedObjectModeMask(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::RelocInfo::JSDispatchHandleModeMask(), v8::internal::ThreadIsolation::kInstructionStream, v8::internal::kNullJSDispatchHandle(), v8::internal::ThreadIsolation::LookupJitAllocation(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, set_embedded_objects_cleared(), v8::internal::SKIP_WRITE_BARRIER, unchecked_instruction_stream(), and v8::internal::undefined.
ClearInstructionStartForSerialization()
void v8::internal::Code::ClearInstructionStartForSerialization (IsolateForSandbox isolate) [inline]
Definition at line 889 of file code-inl.h.
                                                                          {
#ifdef V8_ENABLE_SANDBOX
  // The instruction start is stored in this object's code pointer table.
  WriteField<CodePointerHandle>(kSelfIndirectPointerOffset,
                                kNullCodePointerHandle);
#else
  set_instruction_start(isolate, kNullAddress);
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::kNullAddress, v8::internal::kNullCodePointerHandle, and set_instruction_start().
code_cage_base()
PtrComprCageBase v8::internal::Code::code_cage_base () const [inline]
Definition at line 782 of file code-inl.h.
                                            {
#ifdef V8_EXTERNAL_CODE_SPACE
  return PtrComprCageBase(ExternalCodeCompressionScheme::base());
#else // V8_EXTERNAL_CODE_SPACE
  // Without external code space: `code_cage_base == main_cage_base`. We can
  // get the main cage base from any heap object, including objects in RO
  // space.
  return GetPtrComprCageBase(*this);
#endif // V8_EXTERNAL_CODE_SPACE
}
References v8::internal::GetPtrComprCageBase().
code_comments()
Address v8::internal::Code::code_comments () const [inline]
Definition at line 642 of file code-inl.h.
                                  {
  return metadata_start() + code_comments_offset();
}
References metadata_start().
code_comments_size()
int v8::internal::Code::code_comments_size () const [inline]
Definition at line 646 of file code-inl.h.
                                   {
  return jump_table_info_offset() - code_comments_offset();
}
Referenced by has_code_comments().
constant_pool()
Address v8::internal::Code::constant_pool () const [inline]
Definition at line 637 of file code-inl.h.
                                  {
  if (!has_constant_pool()) return kNullAddress;
  return metadata_start() + constant_pool_offset();
}
References has_constant_pool(), v8::internal::kNullAddress, and metadata_start().
Referenced by ClearEmbeddedObjectsAndJSDispatchHandles().
constant_pool_size()
int v8::internal::Code::constant_pool_size () const [inline]
Definition at line 286 of file code-inl.h.
                                   {
  const int size = code_comments_offset() - constant_pool_offset();
  if (!V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    DCHECK_EQ(size, 0);
    return 0;
  }
  DCHECK_GE(size, 0);
  return size;
}
References DCHECK_EQ, DCHECK_GE, size(), and V8_EMBEDDED_CONSTANT_POOL_BOOL.
Referenced by has_constant_pool().
contains()
bool v8::internal::Code::contains (Isolate * isolate, Address pc) const [inline]
Definition at line 321 of file code-inl.h.
                                                                 {
  const Address start = InstructionStart(isolate, inner_pointer);
  if (inner_pointer < start) return false;
  return inner_pointer < start + instruction_size();
}
References InstructionStart().
DEFINE_FIELD_OFFSET_CONSTANTS()
v8::internal::Code::DEFINE_FIELD_OFFSET_CONSTANTS (ExposedTrustedObject::kHeaderSize , CODE_DATA_FIELDS)
embedded_objects_cleared()
bool v8::internal::Code::embedded_objects_cleared () const [inline]
Definition at line 597 of file code-inl.h.
                                          {
  return Code::EmbeddedObjectsClearedField::decode(flags(kRelaxedLoad));
}
References v8::internal::flags, and v8::kRelaxedLoad.
entrypoint_tag()
CodeEntrypointTag v8::internal::Code::entrypoint_tag () const [inline]
Definition at line 847 of file code-inl.h.
                                             {
  switch (kind()) {
    case CodeKind::BYTECODE_HANDLER:
      return kBytecodeHandlerEntrypointTag;
    case CodeKind::BUILTIN:
      return Builtins::EntrypointTagFor(builtin_id());
    case CodeKind::REGEXP:
      return kRegExpEntrypointTag;
    case CodeKind::WASM_FUNCTION:
    case CodeKind::WASM_TO_CAPI_FUNCTION:
    case CodeKind::WASM_TO_JS_FUNCTION:
      return kWasmEntrypointTag;
    case CodeKind::JS_TO_WASM_FUNCTION:
      return kJSEntrypointTag;
    default:
      // TODO(saelo): eventually we'll want this to be UNREACHABLE().
      return kDefaultCodeEntrypointTag;
  }
}
References BUILTIN, builtin_id(), v8::internal::Builtins::EntrypointTagFor(), v8::internal::kBytecodeHandlerEntrypointTag, v8::internal::kDefaultCodeEntrypointTag, kind(), v8::internal::kJSEntrypointTag, v8::internal::kRegExpEntrypointTag, and v8::internal::kWasmEntrypointTag.
Referenced by set_instruction_start().
FlushICache()
void v8::internal::Code::FlushICache () const
Definition at line 63 of file code.cc.
                             {
  FlushInstructionCache(instruction_start(), instruction_size());
}
References v8::internal::FlushInstructionCache().
FromTargetAddress()
Tagged< Code > v8::internal::Code::FromTargetAddress (Address address) [inline], [static]
Definition at line 692 of file code-inl.h.
                                                    {
  return InstructionStream::FromTargetAddress(address)->code(kAcquireLoad);
}
References v8::internal::HeapObject::address(), v8::internal::InstructionStream::FromTargetAddress(), and v8::kAcquireLoad.
Referenced by v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), IsIsolateIndependent(), and v8::internal::SetupIsolateDelegate::ReplacePlaceholders().
GetBaselineEndPCForBytecodeOffset()
uintptr_t v8::internal::Code::GetBaselineEndPCForBytecodeOffset (int bytecode_offset, Tagged< BytecodeArray > bytecodes) [inline]
Definition at line 391 of file code-inl.h.
                                                          {
  return GetBaselinePCForBytecodeOffset(bytecode_offset, kPcAtEndOfBytecode,
                                        bytecodes);
}
References GetBaselinePCForBytecodeOffset(), and kPcAtEndOfBytecode.
Referenced by GetBaselinePCForNextExecutedBytecode().
GetBaselinePCForBytecodeOffset()
uintptr_t v8::internal::Code::GetBaselinePCForBytecodeOffset (int bytecode_offset, BytecodeToPCPosition position, Tagged< BytecodeArray > bytecodes) [inline], [private]
Definition at line 355 of file code-inl.h.
                                     {
  DisallowGarbageCollection no_gc;
  CHECK_EQ(kind(), CodeKind::BASELINE);
  // The following check ties together the bytecode being executed in
  // Generate_BaselineOrInterpreterEntry with the bytecode that was used to
  // compile this baseline code. Together, this ensures that we don't OSR into a
  // wrong code object.
  auto maybe_bytecodes = bytecode_or_interpreter_data();
  if (IsBytecodeArray(maybe_bytecodes)) {
    SBXCHECK_EQ(maybe_bytecodes, bytecodes);
  } else {
    CHECK(IsInterpreterData(maybe_bytecodes));
    SBXCHECK_EQ(Cast<InterpreterData>(maybe_bytecodes)->bytecode_array(),
                bytecodes);
  }
  baseline::BytecodeOffsetIterator offset_iterator(
      Cast<TrustedByteArray>(bytecode_offset_table()), bytecodes);
  offset_iterator.AdvanceToBytecodeOffset(bytecode_offset);
  uintptr_t pc = 0;
  if (position == kPcAtStartOfBytecode) {
    pc = offset_iterator.current_pc_start_offset();
  } else {
    DCHECK_EQ(position, kPcAtEndOfBytecode);
    pc = offset_iterator.current_pc_end_offset();
  }
  return pc;
}
References v8::internal::baseline::BytecodeOffsetIterator::AdvanceToBytecodeOffset(), bytecode_or_interpreter_data(), CHECK, CHECK_EQ, v8::internal::baseline::BytecodeOffsetIterator::current_pc_end_offset(), v8::internal::baseline::BytecodeOffsetIterator::current_pc_start_offset(), DCHECK_EQ, kind(), kPcAtEndOfBytecode, kPcAtStartOfBytecode, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and SBXCHECK_EQ.
Referenced by GetBaselineEndPCForBytecodeOffset(), and GetBaselineStartPCForBytecodeOffset().
GetBaselinePCForNextExecutedBytecode()
uintptr_t v8::internal::Code::GetBaselinePCForNextExecutedBytecode (int bytecode_offset, Tagged< BytecodeArray > bytecodes) [inline]
Definition at line 397 of file code-inl.h.
                                                          {
  DisallowGarbageCollection no_gc;
  CHECK_EQ(kind(), CodeKind::BASELINE);
  baseline::BytecodeOffsetIterator offset_iterator(
      Cast<TrustedByteArray>(bytecode_offset_table()), bytecodes);
  Handle<BytecodeArray> bytecodes_handle(
      reinterpret_cast<Address*>(&bytecodes));
  interpreter::BytecodeArrayIterator bytecode_iterator(bytecodes_handle,
                                                       bytecode_offset);
  interpreter::Bytecode bytecode = bytecode_iterator.current_bytecode();
  if (bytecode == interpreter::Bytecode::kJumpLoop) {
    return GetBaselineStartPCForBytecodeOffset(
        bytecode_iterator.GetJumpTargetOffset(), bytecodes);
  } else {
    DCHECK(!interpreter::Bytecodes::IsJump(bytecode));
    DCHECK(!interpreter::Bytecodes::IsSwitch(bytecode));
    DCHECK(!interpreter::Bytecodes::Returns(bytecode));
    return GetBaselineEndPCForBytecodeOffset(bytecode_offset, bytecodes);
  }
}
References CHECK_EQ, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::DCHECK(), GetBaselineEndPCForBytecodeOffset(), GetBaselineStartPCForBytecodeOffset(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::interpreter::Bytecodes::IsJump(), v8::internal::interpreter::Bytecodes::IsSwitch(), kind(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::interpreter::Bytecodes::Returns().
GetBaselineStartPCForBytecodeOffset()
uintptr_t v8::internal::Code::GetBaselineStartPCForBytecodeOffset (int bytecode_offset, Tagged< BytecodeArray > bytecodes) [inline]
Definition at line 385 of file code-inl.h.
                                                          {
  return GetBaselinePCForBytecodeOffset(bytecode_offset, kPcAtStartOfBytecode,
                                        bytecodes);
}
References GetBaselinePCForBytecodeOffset(), and kPcAtStartOfBytecode.
Referenced by GetBaselinePCForNextExecutedBytecode().
GetBytecodeOffsetForBaselinePC()
int v8::internal::Code::GetBytecodeOffsetForBaselinePC (Address baseline_pc, Tagged< BytecodeArray > bytecodes) [inline]
Definition at line 342 of file code-inl.h.
                                                                          {
  DisallowGarbageCollection no_gc;
  CHECK(!is_baseline_trampoline_builtin());
  if (is_baseline_leave_frame_builtin()) return kFunctionExitBytecodeOffset;
  CHECK_EQ(kind(), CodeKind::BASELINE);
  baseline::BytecodeOffsetIterator offset_iterator(
      Cast<TrustedByteArray>(bytecode_offset_table()), bytecodes);
  Address pc = baseline_pc - instruction_start();
  offset_iterator.AdvanceToPCOffset(pc);
  return offset_iterator.current_bytecode_offset();
}
References v8::internal::baseline::BytecodeOffsetIterator::AdvanceToPCOffset(), CHECK, CHECK_EQ, v8::internal::baseline::BytecodeOffsetIterator::current_bytecode_offset(), is_baseline_leave_frame_builtin(), is_baseline_trampoline_builtin(), v8::internal::kFunctionExitBytecodeOffset, kind(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetMaglevSafepointEntry()
MaglevSafepointEntry v8::internal::Code::GetMaglevSafepointEntry (Isolate * isolate, Address pc)
Definition at line 108 of file code.cc.
                                                               {
  DCHECK(is_maglevved());
  MaglevSafepointTable table(isolate, pc, *this);
  return table.FindEntry(pc);
}
References v8::internal::DCHECK(), v8::internal::MaglevSafepointTable::FindEntry(), and is_maglevved().
GetOffsetFromInstructionStart()
int v8::internal::Code::GetOffsetFromInstructionStart (Isolate * isolate, Address pc) const [inline]
Definition at line 256 of file code-inl.h.
                                                                          {
  const Address offset = pc - InstructionStart(isolate, pc);
  DCHECK_LE(offset, instruction_size());
  return static_cast<int>(offset);
}
References DCHECK_LE, and InstructionStart().
GetSafepointEntry()
SafepointEntry v8::internal::Code::GetSafepointEntry (Isolate * isolate, Address pc)
Definition at line 102 of file code.cc.
                                                                   {
  DCHECK(!is_maglevved());
  SafepointTable table(isolate, pc, *this);
  return table.FindEntry(pc);
}
References v8::internal::DCHECK(), v8::internal::SafepointTable::FindEntry(), and is_maglevved().
handler_table_address()
Address v8::internal::Code::handler_table_address () const [inline]
Definition at line 276 of file code-inl.h.
                                          {
  return metadata_start() + handler_table_offset();
}
References metadata_start().
handler_table_size()
int v8::internal::Code::handler_table_size () const [inline]
Definition at line 280 of file code-inl.h.
                                   {
  return constant_pool_offset() - handler_table_offset();
}
Referenced by has_handler_table().
has_bytecode_offset_table()
bool v8::internal::Code::has_bytecode_offset_table () const [inline]
Definition at line 194 of file code-inl.h.
                                           {
  return has_source_position_table_or_bytecode_offset_table() &&
         CodeKindUsesBytecodeOffsetTable(kind());
}
References v8::internal::CodeKindUsesBytecodeOffsetTable(), has_source_position_table_or_bytecode_offset_table(), and kind().
has_code_comments()
bool v8::internal::Code::has_code_comments () const [inline]
Definition at line 650 of file code-inl.h.
{ return code_comments_size() > 0; }
References code_comments_size().
has_constant_pool()
bool v8::internal::Code::has_constant_pool () const [inline]
Definition at line 296 of file code-inl.h.
{ return constant_pool_size() > 0; }
References constant_pool_size().
Referenced by constant_pool().
has_deoptimization_data_or_interpreter_data()
bool v8::internal::Code::has_deoptimization_data_or_interpreter_data () const [inline]
Definition at line 130 of file code-inl.h.
                                                                    {
  return !IsProtectedPointerFieldEmpty(
      kDeoptimizationDataOrInterpreterDataOffset);
}
References v8::internal::TrustedObject::IsProtectedPointerFieldEmpty().
Referenced by IterateDeoptimizationLiterals().
has_handler_table()
bool v8::internal::Code::has_handler_table () const [inline]
Definition at line 284 of file code-inl.h.
{ return handler_table_size() > 0; }
References handler_table_size().
has_instruction_stream() [1/2]
bool v8::internal::Code::has_instruction_stream () const [inline]
Definition at line 760 of file code-inl.h.
                                        {
#if defined(V8_COMPRESS_POINTERS) || !defined(V8_HOST_ARCH_64_BIT)
  const uint32_t value = ReadField<uint32_t>(kInstructionStreamOffset);
#else
  const uint64_t value = ReadField<uint64_t>(kInstructionStreamOffset);
#endif
  SLOW_DCHECK(value == 0 || !HeapLayout::InReadOnlySpace(*this));
  return value != 0;
}
References v8::internal::HeapLayout::InReadOnlySpace(), SLOW_DCHECK, and v8::internal::value.
Referenced by InstructionStart(), metadata_start(), relocation_end(), relocation_size(), relocation_start(), and SetInstructionStartForOffHeapBuiltin().
has_instruction_stream() [2/2]
bool v8::internal::Code::has_instruction_stream (RelaxedLoadTag tag) const [inline]
Definition at line 770 of file code-inl.h.
                                                          {
#if defined(V8_COMPRESS_POINTERS) || !defined(V8_HOST_ARCH_64_BIT)
  const uint32_t value =
      RELAXED_READ_INT32_FIELD(*this, kInstructionStreamOffset);
#else
  const uint64_t value =
      RELAXED_READ_INT64_FIELD(*this, kInstructionStreamOffset);
#endif
  SLOW_DCHECK(value == 0 || !HeapLayout::InReadOnlySpace(*this));
  return value != 0;
}
References v8::internal::HeapLayout::InReadOnlySpace(), RELAXED_READ_INT32_FIELD, SLOW_DCHECK, and v8::internal::value.
has_jump_table_info()
bool v8::internal::Code::has_jump_table_info () const [inline]
Definition at line 677 of file code-inl.h.
{ return jump_table_info_size() > 0; }
References jump_table_info_size().
has_safepoint_table()
bool v8::internal::Code::has_safepoint_table () const [inline]
Definition at line 274 of file code-inl.h.
{ return safepoint_table_size() > 0; }
References safepoint_table_size().
has_source_position_table()
bool v8::internal::Code::has_source_position_table () const [inline]
Definition at line 187 of file code-inl.h.
                                           {
  bool has_table = has_source_position_table_or_bytecode_offset_table() &&
                   !CodeKindUsesBytecodeOffsetTable(kind());
  DCHECK_IMPLIES(!CodeKindMayLackSourcePositionTable(kind()), has_table);
  return has_table;
}
References v8::internal::CodeKindMayLackSourcePositionTable(), v8::internal::CodeKindUsesBytecodeOffsetTable(), DCHECK_IMPLIES, has_source_position_table_or_bytecode_offset_table(), and kind().
Referenced by SourcePosition(), and SourceStatementPosition().
has_source_position_table_or_bytecode_offset_table()
bool v8::internal::Code::has_source_position_table_or_bytecode_offset_table () const [inline]
Definition at line 183 of file code-inl.h.
                                                                    {
  return TaggedField<Object, kPositionTableOffset>::load(*this) != Smi::zero();
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::load(), and v8::internal::Smi::zero().
Referenced by has_bytecode_offset_table(), and has_source_position_table().
has_tagged_outgoing_params()
bool v8::internal::Code::has_tagged_outgoing_params () const [inline]
Definition at line 432 of file code-inl.h.
                                                   {
#if V8_ENABLE_WEBASSEMBLY
  return CodeKindHasTaggedOutgoingParams(kind()) &&
         builtin_id() != Builtin::kWasmCompileLazy;
#else
  return CodeKindHasTaggedOutgoingParams(kind());
#endif
}
References builtin_id(), v8::internal::CodeKindHasTaggedOutgoingParams(), and kind().
has_unwinding_info()
bool v8::internal::Code::has_unwinding_info () const [inline]
Definition at line 689 of file code-inl.h.
{ return unwinding_info_size() > 0; }
References unwinding_info_size().
initialize_flags()
void v8::internal::Code::initialize_flags (CodeKind kind, bool is_context_specialized, bool is_turbofanned) [inline]
Definition at line 912 of file code-inl.h.
                                                 {
  DCHECK(!CodeKindIsInterpretedJSFunction(kind));
  uint32_t value = KindField::encode(kind) |
                   IsContextSpecializedField::encode(is_context_specialized) |
                   IsTurbofannedField::encode(is_turbofanned);
  static_assert(FIELD_SIZE(kFlagsOffset) == kInt32Size);
  set_flags(value, kRelaxedStore);
}
References v8::internal::CodeKindIsInterpretedJSFunction(), v8::internal::DCHECK(), FIELD_SIZE, v8::internal::kInt32Size, v8::kRelaxedStore, and v8::internal::value.
Inlines()
bool v8::internal::Code::Inlines (Tagged< SharedFunctionInfo > sfi)
Definition at line 165 of file code.cc.
                                                 {
  // We can only check for inlining for optimized code.
  DCHECK(is_optimized_code());
  DisallowGarbageCollection no_gc;
  Tagged<DeoptimizationData> const data =
      Cast<DeoptimizationData>(deoptimization_data());
  if (data->length() == 0) return false;
  if (data->GetSharedFunctionInfo() == sfi) return true;
  Tagged<DeoptimizationLiteralArray> const literals = data->LiteralArray();
  int const inlined_count = data->InlinedFunctionCount().value();
  for (int i = 0; i < inlined_count; ++i) {
    if (Cast<SharedFunctionInfo>(literals->get(i)) == sfi) return true;
  }
  return false;
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_optimized_code(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
instruction_end()
Address v8::internal::Code::instruction_end () const [inline]
Definition at line 226 of file code-inl.h.
                                    {
  return instruction_start() + instruction_size();
}
InstructionEnd()
Address v8::internal::Code::InstructionEnd (Isolate * isolate, Address pc) const [inline]
Definition at line 252 of file code-inl.h.
                                                               {
  return InstructionStart(isolate, pc) + instruction_size();
}
References InstructionStart().
InstructionStart()
Address v8::internal::Code::InstructionStart (Isolate * isolate, Address pc) const [inline]
Definition at line 244 of file code-inl.h.
                                                                 {
  if (V8_LIKELY(has_instruction_stream())) return instruction_start();
  // Note we intentionally don't bounds-check that `pc` is within the returned
  // instruction area.
  return EmbeddedData::FromBlobForPc(isolate, pc)
      .InstructionStartOf(builtin_id());
}
References builtin_id(), v8::internal::EmbeddedData::FromBlobForPc(), has_instruction_stream(), v8::internal::EmbeddedData::InstructionStartOf(), and V8_LIKELY.
Referenced by contains(), GetOffsetFromInstructionStart(), and InstructionEnd().
InstructionStreamObjectSize()
int v8::internal::Code::InstructionStreamObjectSize () const [inline]
Definition at line 327 of file code-inl.h.
                                            {
  return InstructionStream::SizeFor(body_size());
}
References body_size(), and v8::internal::InstructionStream::SizeFor().
Referenced by SizeIncludingMetadata().
is_baseline_leave_frame_builtin()
bool v8::internal::Code::is_baseline_leave_frame_builtin () const [inline]
Definition at line 958 of file code-inl.h.
                                                        {
  return builtin_id() == Builtin::kBaselineLeaveFrame;
}
References builtin_id().
Referenced by GetBytecodeOffsetForBaselinePC().
is_baseline_trampoline_builtin()
bool v8::internal::Code::is_baseline_trampoline_builtin () const [inline]
Definition at line 954 of file code-inl.h.
                                                       {
  return IsBaselineTrampolineBuiltin(builtin_id());
}
References builtin_id(), and v8::internal::IsBaselineTrampolineBuiltin().
Referenced by GetBytecodeOffsetForBaselinePC().
is_builtin()
bool v8::internal::Code::is_builtin () const [inline]
Definition at line 944 of file code-inl.h.
{ return builtin_id() != Builtin::kNoBuiltinId; }
References builtin_id(), and v8::internal::kNoBuiltinId.
Referenced by sandboxing_mode().
is_context_specialized()
bool v8::internal::Code::is_context_specialized () const [inline]
Definition at line 441 of file code-inl.h.
                                               {
  return IsContextSpecializedField::decode(flags(kRelaxedLoad));
}
References v8::internal::flags, and v8::kRelaxedLoad.
is_interpreter_trampoline_builtin()
bool v8::internal::Code::is_interpreter_trampoline_builtin () const [inline]
Definition at line 950 of file code-inl.h.
                                                          {
  return IsInterpreterTrampolineBuiltin(builtin_id());
}
References builtin_id(), and v8::internal::IsInterpreterTrampolineBuiltin().
is_maglevved()
bool v8::internal::Code::is_maglevved () const [inline]
Definition at line 464 of file code-inl.h.
{ return kind() == CodeKind::MAGLEV; }
References kind().
Referenced by GetMaglevSafepointEntry(), GetSafepointEntry(), and uses_safepoint_table().
is_optimized_code()
bool v8::internal::Code::is_optimized_code () const [inline]
Definition at line 946 of file code-inl.h.
                                   {
  return CodeKindIsOptimizedJSFunction(kind());
}
References v8::internal::CodeKindIsOptimizedJSFunction(), and kind().
Referenced by CanContainWeakObjects(), and Inlines().
is_turbofanned()
bool v8::internal::Code::is_turbofanned () const [inline]
Definition at line 460 of file code-inl.h.
                                       {
  return IsTurbofannedField::decode(flags(kRelaxedLoad));
}
References v8::internal::flags, and v8::kRelaxedLoad.
Referenced by uses_safepoint_table().
is_wasm_code()
bool v8::internal::Code::is_wasm_code () const [inline]
Definition at line 618 of file code-inl.h.
{ return kind() == CodeKind::WASM_FUNCTION; }
References kind().
Referenced by uses_safepoint_table().
IsIsolateIndependent()
bool v8::internal::Code::IsIsolateIndependent (Isolate * isolate)
Definition at line 115 of file code.cc.
                                                {
  static constexpr int kModeMask =
      RelocInfo::AllRealModesMask() &
      ~RelocInfo::ModeMask(RelocInfo::CONST_POOL) &
      ~RelocInfo::ModeMask(RelocInfo::OFF_HEAP_TARGET) &
      ~RelocInfo::ModeMask(RelocInfo::VENEER_POOL) &
      ~RelocInfo::ModeMask(RelocInfo::WASM_CANONICAL_SIG_ID) &
      ~RelocInfo::ModeMask(RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY);
  static_assert(kModeMask ==
                (RelocInfo::ModeMask(RelocInfo::CODE_TARGET) |
                 RelocInfo::ModeMask(RelocInfo::RELATIVE_CODE_TARGET) |
                 RelocInfo::ModeMask(RelocInfo::COMPRESSED_EMBEDDED_OBJECT) |
                 RelocInfo::ModeMask(RelocInfo::FULL_EMBEDDED_OBJECT) |
                 RelocInfo::ModeMask(RelocInfo::EXTERNAL_REFERENCE) |
                 RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE) |
                 RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE_ENCODED) |
                 RelocInfo::ModeMask(RelocInfo::JS_DISPATCH_HANDLE) |
                 RelocInfo::ModeMask(RelocInfo::NEAR_BUILTIN_ENTRY) |
                 RelocInfo::ModeMask(RelocInfo::WASM_CALL) |
                 RelocInfo::ModeMask(RelocInfo::WASM_STUB_CALL)));
#if defined(V8_TARGET_ARCH_PPC64) || defined(V8_TARGET_ARCH_MIPS64)
  return RelocIterator(*this, kModeMask).done();
#elif defined(V8_TARGET_ARCH_X64) || defined(V8_TARGET_ARCH_ARM64) || \
    defined(V8_TARGET_ARCH_ARM) || defined(V8_TARGET_ARCH_S390X) || \
    defined(V8_TARGET_ARCH_IA32) || defined(V8_TARGET_ARCH_RISCV64) || \
    defined(V8_TARGET_ARCH_LOONG64) || defined(V8_TARGET_ARCH_RISCV32)
  for (RelocIterator it(*this, kModeMask); !it.done(); it.next()) {
    // On these platforms we emit relative builtin-to-builtin
    // jumps for isolate independent builtins in the snapshot. They are later
    // rewritten as pc-relative jumps to the off-heap instruction stream and are
    // thus process-independent. See also: FinalizeEmbeddedCodeTargets.
    if (RelocInfo::IsCodeTargetMode(it.rinfo()->rmode())) {
      Address target_address = it.rinfo()->target_address();
      if (OffHeapInstructionStream::PcIsOffHeap(isolate, target_address))
        continue;
      Tagged<Code> target = Code::FromTargetAddress(target_address);
      if (Builtins::IsIsolateIndependentBuiltin(target)) {
        continue;
      }
    }
    return false;
  }
  return true;
#else
#error Unsupported architecture.
#endif
}
References v8::internal::RelocInfo::AllRealModesMask(), v8::internal::RelocInfo::CODE_TARGET, v8::internal::RelocInfo::COMPRESSED_EMBEDDED_OBJECT, v8::internal::RelocInfo::CONST_POOL, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::RelocInfo::EXTERNAL_REFERENCE, FromTargetAddress(), v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, v8::internal::RelocInfo::INTERNAL_REFERENCE, v8::internal::RelocInfo::INTERNAL_REFERENCE_ENCODED, v8::internal::RelocInfo::IsCodeTargetMode(), v8::internal::Builtins::IsIsolateIndependentBuiltin(), v8::internal::RelocInfo::JS_DISPATCH_HANDLE, v8::internal::RelocInfo::ModeMask(), v8::internal::RelocInfo::NEAR_BUILTIN_ENTRY, v8::internal::RelocInfo::OFF_HEAP_TARGET, v8::internal::OffHeapInstructionStream::PcIsOffHeap(), v8::internal::RelocInfo::RELATIVE_CODE_TARGET, v8::internal::RelocInfo::VENEER_POOL, v8::internal::RelocInfo::WASM_CALL, v8::internal::RelocInfo::WASM_CANONICAL_SIG_ID, v8::internal::RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY, and v8::internal::RelocInfo::WASM_STUB_CALL.
IsWeakObject()
bool v8::internal::Code::IsWeakObject (Tagged< HeapObject > object) [inline]
Definition at line 700 of file code-inl.h.
                                                 {
  return (CanContainWeakObjects() && IsWeakObjectInOptimizedCode(object));
}
References CanContainWeakObjects(), and IsWeakObjectInOptimizedCode().
IsWeakObjectInDeoptimizationLiteralArray()
bool v8::internal::Code::IsWeakObjectInDeoptimizationLiteralArray (Tagged< Object > object) [inline], [static]
Definition at line 714 of file code-inl.h.
                                                                         {
  // Maps must be strong because they can be used as part of the description for
  // how to materialize an object upon deoptimization, in which case it is
  // possible to reach the code that requires the Map without anything else
  // holding a strong pointer to that Map.
  return IsHeapObject(object) && !IsMap(object) &&
         Code::IsWeakObjectInOptimizedCode(Cast<HeapObject>(object));
}
References v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::IsHeapObject(), and IsWeakObjectInOptimizedCode().
Referenced by v8::internal::DeoptimizationLiteralArray::set().
IsWeakObjectInOptimizedCode()
bool v8::internal::Code::IsWeakObjectInOptimizedCode (Tagged< HeapObject > object) [inline], [static]
Definition at line 704 of file code-inl.h.
                                                                {
  Tagged<Map> map_object = object->map(kAcquireLoad);
  if (InstanceTypeChecker::IsMap(map_object)) {
    return Cast<Map>(object)->CanTransition();
  }
  return InstanceTypeChecker::IsPropertyCell(map_object) ||
         InstanceTypeChecker::IsJSReceiver(map_object) ||
         InstanceTypeChecker::IsContext(map_object);
}
References v8::kAcquireLoad.
Referenced by IsWeakObject(), and IsWeakObjectInDeoptimizationLiteralArray().
IterateDeoptimizationLiterals()
void v8::internal::Code::IterateDeoptimizationLiterals (RootVisitor * v) [inline]
Definition at line 723 of file code-inl.h.
                                                       {
  if (!uses_deoptimization_data()) {
    DCHECK(kind() == CodeKind::BASELINE ||
           !has_deoptimization_data_or_interpreter_data());
    return;
  }
  auto deopt_data = Cast<DeoptimizationData>(deoptimization_data());
  if (deopt_data->length() == 0) return;
  Tagged<DeoptimizationLiteralArray> literals = deopt_data->LiteralArray();
  const int literals_length = literals->length();
  for (int i = 0; i < literals_length; ++i) {
    Tagged<MaybeObject> maybe_literal = literals->get_raw(i);
    Tagged<HeapObject> heap_literal;
    if (maybe_literal.GetHeapObject(&heap_literal)) {
      v->VisitRootPointer(Root::kStackRoots, "deoptimization literal",
                          FullObjectSlot(&heap_literal));
    }
  }
}
References v8::internal::DCHECK(), v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::FullObjectSlot, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), has_deoptimization_data_or_interpreter_data(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kind(), uses_deoptimization_data(), and v8::internal::RootVisitor::VisitRootPointer().
jump_table_info()
Address v8::internal::Code::jump_table_info () const [inline]
Definition at line 669 of file code-inl.h.
                                    {
  return metadata_start() + jump_table_info_offset();
}
References metadata_start().
jump_table_info_size()
int v8::internal::Code::jump_table_info_size () const [inline]
Definition at line 673 of file code-inl.h.
                                     {
  return unwinding_info_offset() - jump_table_info_offset();
}
Referenced by has_jump_table_info().
kind()
CodeKind v8::internal::Code::kind () const [inline]
Definition at line 340 of file code-inl.h.
{ return KindField::decode(flags(kRelaxedLoad)); }
References v8::internal::flags, and v8::kRelaxedLoad.
Referenced by bytecode_or_interpreter_data(), checks_tiering_state(), entrypoint_tag(), GetBaselinePCForBytecodeOffset(), GetBaselinePCForNextExecutedBytecode(), GetBytecodeOffsetForBaselinePC(), has_bytecode_offset_table(), has_source_position_table(), has_tagged_outgoing_params(), is_maglevved(), is_optimized_code(), is_wasm_code(), IterateDeoptimizationLiterals(), set_bytecode_or_interpreter_data(), SourcePosition(), SourceStatementPosition(), and uses_deoptimization_data().
metadata_end()
Address v8::internal::Code::metadata_end () const [inline]
Definition at line 262 of file code-inl.h.
                                 {
  return metadata_start() + metadata_size();
}
References metadata_start().
Referenced by unwinding_info_end().
metadata_start()
Address v8::internal::Code::metadata_start () const [inline]
Definition at line 230 of file code-inl.h.
                                   {
  if (has_instruction_stream()) {
    static_assert(InstructionStream::kOnHeapBodyIsContiguous);
    return instruction_start() + instruction_size();
  }
  // An embedded builtin. Remapping is irrelevant wrt the metadata section so
  // we can simply use the global blob.
  // TODO(jgruber): Consider adding this as a physical Code field to avoid the
  // lookup. Alternatively, rename this (and callers) to camel-case to clarify
  // it's more than a simple accessor.
  static_assert(!InstructionStream::kOffHeapBodyIsContiguous);
  return EmbeddedData::FromBlob().MetadataStartOf(builtin_id());
}
References builtin_id(), v8::internal::EmbeddedData::FromBlob(), has_instruction_stream(), v8::internal::InstructionStream::kOffHeapBodyIsContiguous, v8::internal::InstructionStream::kOnHeapBodyIsContiguous, and v8::internal::EmbeddedData::MetadataStartOf().
Referenced by code_comments(), constant_pool(), handler_table_address(), jump_table_info(), metadata_end(), safepoint_table_address(), and unwinding_info_start().
OBJECT_CONSTRUCTORS()
v8::internal::Code::OBJECT_CONSTRUCTORS (Code , ExposedTrustedObject) [private]
parameter_count_without_receiver()
uint16_t v8::internal::Code::parameter_count_without_receiver () const [inline]
Definition at line 98 of file code-inl.h.
                                                             {
  return parameter_count() - 1;
}
raw_deoptimization_data_or_interpreter_data()
Tagged< Object > v8::internal::Code::raw_deoptimization_data_or_interpreter_data () const [private]
Definition at line 25 of file code.cc.
                                                                       {
  return RawProtectedPointerField(kDeoptimizationDataOrInterpreterDataOffset)
      .load();
}
References v8::internal::FullObjectSlot::load(), and v8::internal::TrustedObject::RawProtectedPointerField().
raw_position_table()
Tagged< Object > v8::internal::Code::raw_position_table () const [private]
Definition at line 30 of file code.cc.
                                              {
  return RawProtectedPointerField(kPositionTableOffset).load();
}
References v8::internal::FullObjectSlot::load(), and v8::internal::TrustedObject::RawProtectedPointerField().
relocation_end()
uint8_t * v8::internal::Code::relocation_end () const [inline]
Definition at line 309 of file code-inl.h.
                                    {
  return V8_LIKELY(has_instruction_stream())
             ? instruction_stream()->relocation_end()
             : nullptr;
}
References has_instruction_stream(), and V8_LIKELY.
relocation_size()
int v8::internal::Code::relocation_size () const [inline]
Definition at line 315 of file code-inl.h.
                                {
  return V8_LIKELY(has_instruction_stream())
             ? instruction_stream()->relocation_size()
             : 0;
}
References has_instruction_stream(), and V8_LIKELY.
Referenced by SizeIncludingMetadata().
relocation_start()
uint8_t * v8::internal::Code::relocation_start () const [inline]
Definition at line 303 of file code-inl.h.
                                      {
  return V8_LIKELY(has_instruction_stream())
             ? instruction_stream()->relocation_start()
             : nullptr;
}
References has_instruction_stream(), and V8_LIKELY.
safepoint_table_address()
Address v8::internal::Code::safepoint_table_address () const [inline]
Definition at line 266 of file code-inl.h.
                                            {
  return metadata_start() + safepoint_table_offset();
}
References metadata_start(), and safepoint_table_offset().
Referenced by stack_slots().
safepoint_table_offset()
int v8::internal::Code::safepoint_table_offset () const [inline]
Definition at line 269 of file code.h.
{ return 0; }
Referenced by safepoint_table_address(), and safepoint_table_size().
safepoint_table_size()
int v8::internal::Code::safepoint_table_size () const [inline]
Definition at line 270 of file code-inl.h.
                                     {
  return handler_table_offset() - safepoint_table_offset();
}
References safepoint_table_offset().
Referenced by has_safepoint_table(), and stack_slots().
sandboxing_mode()
CodeSandboxingMode v8::internal::Code::sandboxing_mode () const [inline]
Definition at line 867 of file code-inl.h.
                                               {
  if (is_builtin()) {
    return Builtins::SandboxingModeOf(builtin_id());
  } else {
    // All runtime-generated code should run sandboxed.
    return CodeSandboxingMode::kSandboxed;
  }
}
References builtin_id(), is_builtin(), v8::internal::kSandboxed, and v8::internal::Builtins::SandboxingModeOf().
set_builtin_id()
void v8::internal::Code::set_builtin_id (Builtin builtin_id) [inline]
Definition at line 928 of file code-inl.h.
                                            {
  static_assert(FIELD_SIZE(kBuiltinIdOffset) == kInt16Size);
  Relaxed_WriteField<int16_t>(kBuiltinIdOffset,
                              static_cast<int16_t>(builtin_id));
}
References builtin_id(), FIELD_SIZE, and v8::internal::kInt16Size.
set_bytecode_or_interpreter_data()
void v8::internal::Code::set_bytecode_or_interpreter_data (Tagged< TrustedObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 143 of file code-inl.h.
                                                                   {
  DCHECK(kind() == CodeKind::BASELINE);
  DCHECK(IsBytecodeArray(value) || IsInterpreterData(value));
  WriteProtectedPointerField(kDeoptimizationDataOrInterpreterDataOffset, value);
  CONDITIONAL_PROTECTED_POINTER_WRITE_BARRIER(
      *this, kDeoptimizationDataOrInterpreterDataOffset, value, mode);
}
References CONDITIONAL_PROTECTED_POINTER_WRITE_BARRIER, v8::internal::DCHECK(), kind(), mode(), v8::internal::value, and v8::internal::TrustedObject::WriteProtectedPointerField().
set_embedded_objects_cleared()
void v8::internal::Code::set_embedded_objects_cleared (bool flag) [inline]
Definition at line 601 of file code-inl.h.
                                                 {
  DCHECK_IMPLIES(flag, marked_for_deoptimization());
  int32_t previous = flags(kRelaxedLoad);
  int32_t updated = Code::EmbeddedObjectsClearedField::update(previous, flag);
  set_flags(updated, kRelaxedStore);
}
References DCHECK_IMPLIES, v8::internal::flags, v8::kRelaxedLoad, and v8::kRelaxedStore.
Referenced by ClearEmbeddedObjectsAndJSDispatchHandles().
set_instruction_start()
void v8::internal::Code::set_instruction_start (IsolateForSandbox isolate, Address value) [inline], [private]
Definition at line 838 of file code-inl.h.
                                                                         {
#ifdef V8_ENABLE_SANDBOX
  WriteCodeEntrypointViaCodePointerField(kSelfIndirectPointerOffset, value,
                                         entrypoint_tag());
#else
  WriteField<Address>(kInstructionStartOffset, value);
#endif
}
References entrypoint_tag(), v8::internal::value, and v8::internal::HeapObject::WriteCodeEntrypointViaCodePointerField().
Referenced by ClearInstructionStartForSerialization(), SetInstructionStartForOffHeapBuiltin(), SetInstructionStreamAndInstructionStart(), and UpdateInstructionStart().
SetInstructionStartForOffHeapBuiltin()
void v8::internal::Code::SetInstructionStartForOffHeapBuiltin (IsolateForSandbox isolate, Address entry) [inline]
Definition at line 883 of file code-inl.h.
                                                               {
  DCHECK(!has_instruction_stream());
  set_instruction_start(isolate, entry);
}
References v8::internal::DCHECK(), has_instruction_stream(), and set_instruction_start().
SetInstructionStreamAndInstructionStart()
void v8::internal::Code::SetInstructionStreamAndInstructionStart (IsolateForSandbox isolate, Tagged< InstructionStream > code, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 876 of file code-inl.h.
                           {
  set_raw_instruction_stream(code, mode);
  set_instruction_start(isolate, code->instruction_start());
}
References code, mode(), and set_instruction_start().
SetMarkedForDeoptimization()
void v8::internal::Code::SetMarkedForDeoptimization (Isolate * isolate, LazyDeoptimizeReason reason) [inline]
Definition at line 536 of file code-inl.h.
                                                                          {
  set_marked_for_deoptimization(true);
  // Eager deopts are already logged by the deoptimizer.
  if (reason != LazyDeoptimizeReason::kEagerDeopt &&
      V8_UNLIKELY(v8_flags.trace_deopt || v8_flags.log_deopt)) {
    TraceMarkForDeoptimization(isolate, reason);
  }
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchHandle handle = js_dispatch_handle();
  if (handle != kNullJSDispatchHandle) {
    JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
    Tagged<Code> cur = jdt->GetCode(handle);
    if (SafeEquals(cur)) {
      if (v8_flags.reopt_after_lazy_deopts &&
          isolate->concurrent_recompilation_enabled()) {
        jdt->SetCodeNoWriteBarrier(
            handle, *BUILTIN_CODE(isolate, InterpreterEntryTrampoline));
        // Somewhat arbitrary list of lazy deopt reasons which we expect to be
        // stable enough to warrant either immediate re-optimization, or
        // re-optimization after one invocation (to detect potential follow-up
        // IC changes).
        // TODO(olivf): We should also work on reducing the number of
        // dependencies we create in the compilers to require less of these
        // quick re-compilations.
        switch (reason) {
          case LazyDeoptimizeReason::kAllocationSiteTenuringChange:
          case LazyDeoptimizeReason::kAllocationSiteTransitionChange:
          case LazyDeoptimizeReason::kEmptyContextExtensionChange:
          case LazyDeoptimizeReason::kFrameValueMaterialized:
          case LazyDeoptimizeReason::kPropertyCellChange:
          case LazyDeoptimizeReason::kContextCellChange:
          case LazyDeoptimizeReason::kPrototypeChange:
          case LazyDeoptimizeReason::kExceptionCaught:
          case LazyDeoptimizeReason::kFieldTypeConstChange:
          case LazyDeoptimizeReason::kFieldRepresentationChange:
          case LazyDeoptimizeReason::kFieldTypeChange:
          case LazyDeoptimizeReason::kInitialMapChange:
          case LazyDeoptimizeReason::kMapDeprecated:
            jdt->SetTieringRequest(
                handle, TieringBuiltin::kMarkReoptimizeLazyDeoptimized,
                isolate);
            break;
          default:
            // TODO(olivf): This trampoline is just used to reset the budget. If
            // we knew the feedback cell and the bytecode size here, we could
            // directly reset the budget.
            jdt->SetTieringRequest(handle, TieringBuiltin::kMarkLazyDeoptimized,
                                   isolate);
            break;
        }
      } else {
        jdt->SetCodeNoWriteBarrier(handle, *BUILTIN_CODE(isolate, CompileLazy));
      }
    }
    // Ensure we don't try to patch the entry multiple times.
    set_js_dispatch_handle(kNullJSDispatchHandle);
  }
#endif
}
References BUILTIN_CODE, v8::internal::wasm::CompileLazy(), v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::IsolateGroup::current(), v8::internal::handle(), v8::internal::kNullJSDispatchHandle(), v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::SafeEquals(), TraceMarkForDeoptimization(), v8::internal::v8_flags, and V8_UNLIKELY.
SizeIncludingMetadata()
int v8::internal::Code::SizeIncludingMetadata () const [inline]
Definition at line 331 of file code-inl.h.
                                      {
  int size = InstructionStreamObjectSize();
  size += relocation_size();
  if (uses_deoptimization_data()) {
    size += deoptimization_data()->Size();
  }
  return size;
}
References InstructionStreamObjectSize(), relocation_size(), size(), and uses_deoptimization_data().
SourcePosition()
int v8::internal::Code::SourcePosition (int offset) const
Definition at line 67 of file code.cc.
                                         {
  CHECK_NE(kind(), CodeKind::BASELINE);
  // Subtract one because the current PC is one instruction after the call site.
  offset--;
  int position = 0;
  if (!has_source_position_table()) return position;
  for (SourcePositionTableIterator it(
           source_position_table(),
           SourcePositionTableIterator::kJavaScriptOnly,
           SourcePositionTableIterator::kDontSkipFunctionEntry);
       !it.done() && it.code_offset() <= offset; it.Advance()) {
    position = it.source_position().ScriptOffset();
  }
  return position;
}
References CHECK_NE, v8::internal::SourcePositionTableIterator::done(), has_source_position_table(), v8::internal::SourcePositionTableIterator::kDontSkipFunctionEntry, kind(), and v8::internal::SourcePositionTableIterator::kJavaScriptOnly.
SourcePositionTable()
Tagged< TrustedByteArray > v8::internal::Code::SourcePositionTable (Isolate * isolate, Tagged< SharedFunctionInfo > sfi) const [inline]
Definition at line 205 of file code-inl.h.
                                                            {
  DisallowGarbageCollection no_gc;
  if (kind() == CodeKind::BASELINE) {
    return sfi->GetBytecodeArray(isolate)->SourcePositionTable(isolate);
  }
  if (!has_source_position_table()) {
    return *isolate->factory()->empty_trusted_byte_array();
  }
  return source_position_table();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
SourceStatementPosition()
int v8::internal::Code::SourceStatementPosition (int offset) const
Definition at line 85 of file code.cc.
                                                  {
  CHECK_NE(kind(), CodeKind::BASELINE);
  // Subtract one because the current PC is one instruction after the call site.
  offset--;
  int position = 0;
  if (!has_source_position_table()) return position;
  for (SourcePositionTableIterator it(source_position_table());
       !it.done() && it.code_offset() <= offset; it.Advance()) {
    if (it.is_statement()) {
      position = it.source_position().ScriptOffset();
    }
  }
  return position;
}
References CHECK_NE, v8::internal::SourcePositionTableIterator::done(), has_source_position_table(), and kind().
stack_slots()
uint32_t v8::internal::Code::stack_slots () const [inline]
Definition at line 514 of file code-inl.h.
                                 {
  DCHECK_IMPLIES(safepoint_table_size() > 0, uses_safepoint_table());
  if (safepoint_table_size() == 0) return 0;
  DCHECK(safepoint_table_size() >=
         static_cast<int>(sizeof(SafepointTableStackSlotsField_t)));
  static_assert(kSafepointTableStackSlotsOffset == 0);
  return base::Memory<SafepointTableStackSlotsField_t>(
      safepoint_table_address() + kSafepointTableStackSlotsOffset);
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::kSafepointTableStackSlotsOffset, safepoint_table_address(), safepoint_table_size(), and uses_safepoint_table().
TraceMarkForDeoptimization()
void v8::internal::Code::TraceMarkForDeoptimization (Isolate * isolate, LazyDeoptimizeReason reason)
Definition at line 337 of file code.cc.
                                                                   {
  Deoptimizer::TraceMarkForDeoptimization(isolate, *this, reason);
}
References v8::internal::Deoptimizer::TraceMarkForDeoptimization().
Referenced by SetMarkedForDeoptimization().
unchecked_deoptimization_data()
Tagged< ProtectedFixedArray > v8::internal::Code::unchecked_deoptimization_data () const [inline]
Definition at line 298 of file code-inl.h.
                                                                      {
  return UncheckedCast<ProtectedFixedArray>(
      ReadProtectedPointerField(kDeoptimizationDataOrInterpreterDataOffset));
}
References v8::internal::TrustedObject::ReadProtectedPointerField().
unchecked_instruction_stream()
Tagged< InstructionStream > v8::internal::Code::unchecked_instruction_stream () const [inline]
Definition at line 798 of file code-inl.h.
                                                                   {
  return UncheckedCast<InstructionStream>(raw_instruction_stream());
}
Referenced by ClearEmbeddedObjectsAndJSDispatchHandles().
unwinding_info_end()
Address v8::internal::Code::unwinding_info_end () const [inline]
Definition at line 683 of file code-inl.h.
{ return metadata_end(); }
References metadata_end().
Referenced by unwinding_info_size().
unwinding_info_size()
int v8::internal::Code::unwinding_info_size () const [inline]
Definition at line 685 of file code-inl.h.
                                    {
  return static_cast<int>(unwinding_info_end() - unwinding_info_start());
}
References unwinding_info_end(), and unwinding_info_start().
Referenced by has_unwinding_info().
unwinding_info_start()
Address v8::internal::Code::unwinding_info_start () const [inline]
Definition at line 679 of file code-inl.h.
                                         {
  return metadata_start() + unwinding_info_offset();
}
References metadata_start().
Referenced by unwinding_info_size().
UpdateInstructionStart()
void v8::internal::Code::UpdateInstructionStart (IsolateForSandbox isolate, Tagged< InstructionStream > istream) [inline]
Definition at line 899 of file code-inl.h.
                                                                     {
  DCHECK_EQ(raw_instruction_stream(), istream);
  set_instruction_start(isolate, istream->instruction_start());
}
References DCHECK_EQ, and set_instruction_start().
uses_deoptimization_data()
bool v8::internal::Code::uses_deoptimization_data () const [inline]
Definition at line 122 of file code-inl.h.
                                                 {
  return CodeKindUsesDeoptimizationData(kind());
}
References v8::internal::CodeKindUsesDeoptimizationData(), and kind().
Referenced by IterateDeoptimizationLiterals(), and SizeIncludingMetadata().
uses_safepoint_table()
bool v8::internal::Code::uses_safepoint_table () const [inline]
Definition at line 510 of file code-inl.h.
                                      {
  return is_turbofanned() || is_maglevved() || is_wasm_code();
}
References is_maglevved(), is_turbofanned(), and is_wasm_code().
Referenced by stack_slots().
Friends And Related Function Documentation
Deserializer
template<typename IsolateT >
friend class Deserializer [friend]
Definition at line 511 of file code.h.
Member Data Documentation
Factory
friend v8::internal::Code::Factory [private]
Definition at line 512 of file code.h.
FactoryBase< Factory >
friend v8::internal::Code::FactoryBase< Factory > [private]
Definition at line 513 of file code.h.
FactoryBase< LocalFactory >
friend v8::internal::Code::FactoryBase< LocalFactory > [private]
Definition at line 514 of file code.h.
kArgumentsBits
const int v8::internal::Code::kArgumentsBits = 16 [static]
Definition at line 484 of file code.h.
kIsTurbofannedBit
const int v8::internal::Code::kIsTurbofannedBit = IsTurbofannedField::kShift [static]
Definition at line 482 of file code.h.
Referenced by v8::internal::MacroAssembler::TryLoadOptimizedOsrCode().
kMarkedForDeoptimizationBit
const int v8::internal::Code::kMarkedForDeoptimizationBit [static]
Initial value:
=
      MarkedForDeoptimizationField::kShift
Definition at line 480 of file code.h.
Referenced by v8::internal::MacroAssembler::BailoutIfDeoptimized(), v8::internal::MacroAssembler::JumpIfCodeIsMarkedForDeoptimization(), and v8::internal::MacroAssembler::TryLoadOptimizedOsrCode().
kMaxArguments
const int v8::internal::Code::kMaxArguments = (1 << kArgumentsBits) - 10 [static]
Definition at line 487 of file code.h.
Referenced by v8::internal::Parser::DeclareArrowFunctionFormalParameters(), v8::internal::anonymous_namespace{runtime-regexp.cc}::GetArgcForReplaceCallable(), v8::internal::Factory::NewJSBoundFunction(), v8::internal::ParserBase< Impl >::ParseArguments(), v8::internal::ParserBase< Impl >::ParseFormalParameterList(), v8::internal::ParserBase< Impl >::ParseObjectLiteral(), and v8::internal::compiler::JSCallReducer::ReduceJSCall().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/code.h
/mnt/V8SourceCode/src/objects/code-inl.h
/mnt/V8SourceCode/src/objects/code.cc