v8::internal::StackHandler Class Reference
#include <frames.h>
Public Member Functions
Address address () const
StackHandler * next () const
Address next_address () const
Static Public Member Functions
static StackHandler * FromAddress (Address address)
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (StackHandler)
Detailed Description
Definition at line 96 of file frames.h.
Member Function Documentation
address()
Address v8::internal::StackHandler::address () const [inline]
Definition at line 54 of file frames-inl.h.
                                           {
  return reinterpret_cast<Address>(const_cast<StackHandler*>(this));
}
Referenced by v8::internal::anonymous_namespace{frames.cc}::AddressOf(), FromAddress(), next(), and next_address().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::StackHandler::DISALLOW_IMPLICIT_CONSTRUCTORS (StackHandler) [private]
FromAddress()
StackHandler * v8::internal::StackHandler::FromAddress (Address address) [inline], [static]
Definition at line 67 of file frames-inl.h.
                                                              {
  return reinterpret_cast<StackHandler*>(address);
}
References address().
Referenced by next(), and v8::internal::StackFrameIterator::Reset().
next()
StackHandler * v8::internal::StackHandler::next () const [inline]
Definition at line 58 of file frames-inl.h.
                                              {
  const int offset = StackHandlerConstants::kNextOffset;
  return FromAddress(base::Memory<Address>(address() + offset));
}
References address(), FromAddress(), and v8::internal::StackHandlerConstants::kNextOffset.
Referenced by v8::internal::StackHandlerIterator::Advance(), and v8::internal::StackHandlerIterator::StackHandlerIterator().
next_address()
Address v8::internal::StackHandler::next_address () const [inline]
Definition at line 63 of file frames-inl.h.
                                                {
  return base::Memory<Address>(address() + StackHandlerConstants::kNextOffset);
}
References address(), and v8::internal::StackHandlerConstants::kNextOffset.
Referenced by v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h