v8::internal::RootsTable Class Reference
#include <roots.h>
Public Member Functions
RootsTable ()
bool IsRootHandleLocation (Address *handle_location, RootIndex *index) const
template<typename T >
bool IsRootHandle (IndirectHandle< T > handle, RootIndex *index) const
IndirectHandle< HeapNumber > FindHeapNumber (double value)
IndirectHandle< Object > handle_at (RootIndex root_index)
Address const & operator[] (RootIndex root_index) const
FullObjectSlot slot (RootIndex root_index)
Static Public Member Functions
static const char * name (RootIndex root_index)
static constexpr int offset_of (RootIndex root_index)
static constexpr bool IsImmortalImmovable (RootIndex root_index)
static constexpr bool IsReadOnly (RootIndex root_index)
static constexpr RootIndex SingleCharacterStringIndex (int c)
Static Public Attributes
static constexpr size_t kEntriesCount
Private Member Functions
FullObjectSlot begin ()
FullObjectSlot end ()
FullObjectSlot strong_or_read_only_roots_begin () const
FullObjectSlot strong_or_read_only_roots_end () const
FullObjectSlot read_only_roots_begin () const
FullObjectSlot read_only_roots_end () const
FullObjectSlot strong_roots_begin () const
FullObjectSlot strong_roots_end () const
FullObjectSlot smi_roots_begin () const
FullObjectSlot smi_roots_end () const
Address & operator[] (RootIndex root_index)
Private Attributes
Address roots_ [kEntriesCount]
Static Private Attributes
static const char * root_names_ [kEntriesCount]
Friends
class Isolate
class Heap
class Factory
class FactoryBase< Factory >
class FactoryBase< LocalFactory >
class ReadOnlyHeap
class ReadOnlyRoots
class RootsSerializer
Detailed Description
Definition at line 579 of file roots.h.
Constructor & Destructor Documentation
RootsTable()
v8::internal::RootsTable::RootsTable () [inline]
Definition at line 584 of file roots.h.
: roots_{} {}
Member Function Documentation
begin()
FullObjectSlot v8::internal::RootsTable::begin () [inline], [private]
Definition at line 654 of file roots.h.
                         {
    return FullObjectSlot(&roots_[static_cast<size_t>(RootIndex::kFirstRoot)]);
  }
References v8::internal::kFirstRoot, and roots_.
Referenced by v8::internal::RootsSerializer::VisitRootPointers().
end()
FullObjectSlot v8::internal::RootsTable::end () [inline], [private]
Definition at line 657 of file roots.h.
                       {
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kLastRoot) + 1]);
  }
References v8::internal::kLastRoot, and roots_.
FindHeapNumber()
IndirectHandle< HeapNumber > v8::internal::RootsTable::FindHeapNumber (double value)
Definition at line 38 of file roots.cc.
                                                                  {
  auto bits = base::bit_cast<uint64_t>(value);
  for (auto pos = RootIndex::kFirstHeapNumberRoot;
       pos <= RootIndex::kLastHeapNumberRoot; ++pos) {
    auto root = Cast<HeapNumber>(Tagged<Object>((*this)[pos]));
    if (base::bit_cast<uint64_t>(root->value()) == bits) {
      return IndirectHandle<HeapNumber>(&(*this)[pos]);
    }
  }
  return {};
}
References v8::internal::kFirstHeapNumberRoot, v8::internal::kLastHeapNumberRoot, and v8::internal::value.
Referenced by v8::internal::Factory::NewHeapNumberForCodeAssembler().
handle_at()
IndirectHandle< Object > v8::internal::RootsTable::handle_at (RootIndex root_index) [inline]
Definition at line 78 of file roots-inl.h.
                                                            {
  return IndirectHandle<Object>(&(*this)[index]);
}
References v8::internal::index.
IsImmortalImmovable()
static constexpr bool v8::internal::RootsTable::IsImmortalImmovable (RootIndex root_index) [inline], [static], [constexpr]
Definition at line 631 of file roots.h.
                                                                  {
    static_assert(static_cast<int>(RootIndex::kFirstImmortalImmovableRoot) ==
                  0);
    return static_cast<unsigned>(root_index) <=
           static_cast<unsigned>(RootIndex::kLastImmortalImmovableRoot);
  }
References v8::internal::kFirstImmortalImmovableRoot, and v8::internal::kLastImmortalImmovableRoot.
Referenced by v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::CodeStubAssembler::AllocateFixedArray(), v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateNonEmptyByteArray(), v8::internal::CodeStubAssembler::AllocatePropertyArray(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateSlicedString(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::BuiltinsConstantsTableBuilder::BuiltinsConstantsTableBuilder(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::DeletePropertyBaseAssembler::DictionarySpecificDelete(), v8::internal::compiler::CodeGenerator::IsMaterializableFromRoot(), v8::internal::MacroAssembler::LoadFromConstantsTable(), v8::internal::compiler::CodeAssembler::LoadRoot(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadRoot(), v8::internal::compiler::turboshaft::LoadRootHelper(), v8::internal::LocalIsolate::root(), v8::internal::LocalIsolate::root_handle(), v8::internal::RootIndexMap::RootIndexMap(), v8::internal::CodeStubAssembler::StoreObjectFieldRoot(), v8::internal::compiler::CodeAssembler::StoreRoot(), v8::internal::compiler::turboshaft::ValueNeedsWriteBarrier(), v8::internal::compiler::anonymous_namespace{memory-lowering.cc}::ValueNeedsWriteBarrier(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
IsReadOnly()
static constexpr bool v8::internal::RootsTable::IsReadOnly (RootIndex root_index) [inline], [static], [constexpr]
Definition at line 638 of file roots.h.
                                                         {
    static_assert(static_cast<int>(RootIndex::kFirstReadOnlyRoot) == 0);
    return static_cast<unsigned>(root_index) <=
           static_cast<unsigned>(RootIndex::kLastReadOnlyRoot);
  }
References v8::internal::kFirstReadOnlyRoot, and v8::internal::kLastReadOnlyRoot.
Referenced by v8::internal::MacroAssembler::Branch(), v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::PPCOperandGenerator::CanBeImmediate(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::MacroAssemblerBase::CanBeImmediate(), v8::internal::MacroAssembler::CompareTaggedRootAndBranch(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::IsRootConstant(), v8::internal::maglev::RootConstant::ToBoolean(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl().
IsRootHandle()
template<typename T >
bool v8::internal::RootsTable::IsRootHandle (IndirectHandle< T > handle, RootIndex * index) const
Definition at line 61 of file roots-inl.h.
                                                      {
  // This can't use handle.location() because it is called from places
  // where handle dereferencing is disallowed. Comparing the handle's
  // location against the root handle list is safe though.
  Address* handle_location = reinterpret_cast<Address*>(handle.address());
  return IsRootHandleLocation(handle_location, index);
}
References v8::internal::handle(), v8::internal::index, and IsRootHandleLocation().
Referenced by v8::internal::BuiltinsConstantsTableBuilder::AddObject(), v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::PPCOperandGenerator::CanBeImmediate(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::anonymous_namespace{constants-table-builder.cc}::CheckPreconditionsForPatching(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::CodeGenerator::IsMaterializableFromRoot(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), v8::internal::compiler::turboshaft::ValueNeedsWriteBarrier(), v8::internal::compiler::anonymous_namespace{memory-lowering.cc}::ValueNeedsWriteBarrier(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
IsRootHandleLocation()
bool v8::internal::RootsTable::IsRootHandleLocation (Address * handle_location, RootIndex * index) const [inline]
Definition at line 49 of file roots-inl.h.
                                                              {
  FullObjectSlot location(handle_location);
  FullObjectSlot first_root(&roots_[0]);
  FullObjectSlot last_root(&roots_[kEntriesCount]);
  if (location >= last_root) return false;
  if (location < first_root) return false;
  *index = static_cast<RootIndex>(location - first_root);
  return true;
}
References v8::internal::index, kEntriesCount, and roots_.
Referenced by IsRootHandle().
name()
static const char* v8::internal::RootsTable::name (RootIndex root_index) [inline], [static]
Definition at line 615 of file roots.h.
                                                {
    size_t index = static_cast<size_t>(root_index);
    DCHECK_LT(index, kEntriesCount);
    return root_names_[index];
  }
References DCHECK_LT, v8::internal::index, kEntriesCount, and root_names_.
Referenced by v8::internal::V8HeapExplorer::GetStrongGcSubrootName(), v8::internal::maglev::RootConstant::PrintParams(), and v8::internal::maglev::BranchIfRootConstant::PrintParams().
offset_of()
static constexpr int v8::internal::RootsTable::offset_of (RootIndex root_index) [inline], [static], [constexpr]
Definition at line 621 of file roots.h.
                                                       {
    return static_cast<int>(root_index) * kSystemPointerSize;
  }
References v8::internal::kSystemPointerSize.
Referenced by v8::internal::IsolateData::root_slot_offset().
operator[]() [1/2]
Address& v8::internal::RootsTable::operator[] (RootIndex root_index) [inline], [private]
Definition at line 703 of file roots.h.
                                            {
    size_t index = static_cast<size_t>(root_index);
    DCHECK_LT(index, kEntriesCount);
    return roots_[index];
  }
References DCHECK_LT, v8::internal::index, kEntriesCount, and roots_.
operator[]() [2/2]
Address const& v8::internal::RootsTable::operator[] (RootIndex root_index) const [inline]
Definition at line 603 of file roots.h.
                                                        {
    size_t index = static_cast<size_t>(root_index);
    DCHECK_LT(index, kEntriesCount);
    return roots_[index];
  }
References DCHECK_LT, v8::internal::index, kEntriesCount, and roots_.
read_only_roots_begin()
FullObjectSlot v8::internal::RootsTable::read_only_roots_begin () const [inline], [private]
Definition at line 676 of file roots.h.
                                               {
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kFirstReadOnlyRoot)]);
  }
References v8::internal::kFirstReadOnlyRoot, and roots_.
Referenced by v8::internal::ReadOnlyHeap::InitializeFromIsolateRoots(), and v8::internal::ReadOnlyHeap::InitializeIsolateRoots().
read_only_roots_end()
FullObjectSlot v8::internal::RootsTable::read_only_roots_end () const [inline], [private]
Definition at line 680 of file roots.h.
                                             {
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kLastReadOnlyRoot) + 1]);
  }
References v8::internal::kLastReadOnlyRoot, and roots_.
SingleCharacterStringIndex()
static constexpr RootIndex v8::internal::RootsTable::SingleCharacterStringIndex (int c) [inline], [static], [constexpr]
Definition at line 644 of file roots.h.
                                                               {
    DCHECK_GE(c, 0);
    DCHECK_LT(
        c, static_cast<unsigned>(RootIndex::kSingleCharacterStringRootsCount));
    static_assert(static_cast<int>(RootIndex::kFirstReadOnlyRoot) == 0);
    return static_cast<RootIndex>(
        static_cast<unsigned>(RootIndex::kFirstSingleCharacterString) + c);
  }
References DCHECK_GE, DCHECK_LT, v8::internal::kFirstReadOnlyRoot, v8::internal::kFirstSingleCharacterString, and v8::internal::kSingleCharacterStringRootsCount.
Referenced by v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::maglev::MaglevGraphBuilder::GetConstantSingleCharacterStringFromCode(), v8::internal::maglev::MaglevAssembler::LoadSingleCharacterString(), v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), and v8::internal::ReadOnlyRoots::single_character_string().
slot()
FullObjectSlot v8::internal::RootsTable::slot (RootIndex root_index) [inline]
Definition at line 609 of file roots.h.
                                            {
    size_t index = static_cast<size_t>(root_index);
    DCHECK_LT(index, kEntriesCount);
    return FullObjectSlot(&roots_[index]);
  }
References DCHECK_LT, v8::internal::index, kEntriesCount, and roots_.
Referenced by v8::internal::RUNTIME_FUNCTION(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::Isolate::VerifyStaticRoots().
smi_roots_begin()
FullObjectSlot v8::internal::RootsTable::smi_roots_begin () const [inline], [private]
Definition at line 694 of file roots.h.
                                         {
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kFirstSmiRoot)]);
  }
References v8::internal::kFirstSmiRoot, and roots_.
smi_roots_end()
FullObjectSlot v8::internal::RootsTable::smi_roots_end () const [inline], [private]
Definition at line 698 of file roots.h.
                                       {
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kLastSmiRoot) + 1]);
  }
References v8::internal::kLastSmiRoot, and roots_.
strong_or_read_only_roots_begin()
FullObjectSlot v8::internal::RootsTable::strong_or_read_only_roots_begin () const [inline], [private]
Definition at line 663 of file roots.h.
                                                         {
    static_assert(static_cast<size_t>(RootIndex::kLastReadOnlyRoot) ==
                  static_cast<size_t>(RootIndex::kFirstStrongRoot) - 1);
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kFirstStrongOrReadOnlyRoot)]);
  }
References v8::internal::kFirstStrongOrReadOnlyRoot, v8::internal::kFirstStrongRoot, v8::internal::kLastReadOnlyRoot, and roots_.
strong_or_read_only_roots_end()
FullObjectSlot v8::internal::RootsTable::strong_or_read_only_roots_end () const [inline], [private]
Definition at line 669 of file roots.h.
                                                       {
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kLastStrongOrReadOnlyRoot) + 1]);
  }
References v8::internal::kLastStrongOrReadOnlyRoot, and roots_.
strong_roots_begin()
FullObjectSlot v8::internal::RootsTable::strong_roots_begin () const [inline], [private]
Definition at line 685 of file roots.h.
                                            {
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kFirstStrongRoot)]);
  }
References v8::internal::kFirstStrongRoot, and roots_.
strong_roots_end()
FullObjectSlot v8::internal::RootsTable::strong_roots_end () const [inline], [private]
Definition at line 689 of file roots.h.
                                          {
    return FullObjectSlot(
        &roots_[static_cast<size_t>(RootIndex::kLastStrongRoot) + 1]);
  }
References v8::internal::kLastStrongRoot, and roots_.
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 714 of file roots.h.
FactoryBase< Factory >
friend class FactoryBase< Factory > [friend]
Definition at line 714 of file roots.h.
FactoryBase< LocalFactory >
friend class FactoryBase< LocalFactory > [friend]
Definition at line 714 of file roots.h.
Heap
friend class Heap [friend]
Definition at line 713 of file roots.h.
Isolate
friend class Isolate [friend]
Definition at line 712 of file roots.h.
ReadOnlyHeap
friend class ReadOnlyHeap [friend]
Definition at line 717 of file roots.h.
ReadOnlyRoots
friend class ReadOnlyRoots [friend]
Definition at line 718 of file roots.h.
RootsSerializer
friend class RootsSerializer [friend]
Definition at line 719 of file roots.h.
Member Data Documentation
kEntriesCount
constexpr size_t v8::internal::RootsTable::kEntriesCount [static], [constexpr]
Initial value:
=
      static_cast<size_t>(RootIndex::kRootListLength)
Definition at line 581 of file roots.h.
Referenced by IsRootHandleLocation(), name(), operator[](), and slot().
root_names_
const char * v8::internal::RootsTable::root_names_ [static], [private]
Initial value:
= {
#define ROOT_NAME(type, name, CamelName)
}
Definition at line 710 of file roots.h.
Referenced by name().
roots_
Address v8::internal::RootsTable::roots_[kEntriesCount] [private]
Definition at line 709 of file roots.h.
Referenced by begin(), end(), IsRootHandleLocation(), operator[](), read_only_roots_begin(), read_only_roots_end(), slot(), smi_roots_begin(), smi_roots_end(), strong_or_read_only_roots_begin(), strong_or_read_only_roots_end(), strong_roots_begin(), and strong_roots_end().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/roots/roots.h
/mnt/V8SourceCode/src/roots/roots-inl.h
/mnt/V8SourceCode/src/roots/roots.cc