v8::internal::HashTableKey Class Reference
#include <hash-table.h>
Public Member Functions
HashTableKey (uint32_t hash)
virtual bool IsMatch (Tagged< Object > other)=0
virtual ~HashTableKey ()=default
uint32_t Hash () const
Protected Member Functions
void set_hash (uint32_t hash)
Private Attributes
uint32_t hash_ = 0
Detailed Description
Definition at line 331 of file hash-table.h.
Constructor & Destructor Documentation
HashTableKey()
v8::internal::HashTableKey::HashTableKey (uint32_t hash) [inline], [explicit]
Definition at line 333 of file hash-table.h.
: hash_(hash) {}
 HashTableKey()
virtual v8::internal::HashTableKey::~HashTableKey () [virtual], [default]
Member Function Documentation
Hash()
uint32_t v8::internal::HashTableKey::Hash () const [inline]
Definition at line 341 of file hash-table.h.
{ return hash_; }
Referenced by v8::internal::ScriptCacheKey::AsHandle(), v8::internal::ScriptCacheKey::IsMatch(), and v8::internal::ScriptCacheKey::ScriptCacheKey().
IsMatch()
virtual bool v8::internal::HashTableKey::IsMatch (Tagged< Object > other) [pure virtual]
Implemented in v8::internal::anonymous_namespace{compilation-cache-table.cc}::CodeKey, v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey, v8::internal::ScriptCacheKey, and v8::internal::anonymous_namespace{compilation-cache-table.cc}::RegExpKey.
set_hash()
void v8::internal::HashTableKey::set_hash (uint32_t hash) [inline], [protected]
Definition at line 344 of file hash-table.h.
                               {
    DCHECK_EQ(0, hash_);
    hash_ = hash;
  }
References DCHECK_EQ.
Member Data Documentation
hash_
uint32_t v8::internal::HashTableKey::hash_ = 0 [private]
Definition at line 350 of file hash-table.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/hash-table.h