v8::internal::SourcePositionTableBuilder Class Reference
#include <source-position-table.h>
Public Types
enum RecordingMode { OMIT_SOURCE_POSITIONS
, LAZY_SOURCE_POSITIONS
, RECORD_SOURCE_POSITIONS
 }
Public Member Functions
SourcePositionTableBuilder (Zone *zone, RecordingMode mode=RECORD_SOURCE_POSITIONS)
void AddPosition (size_t code_offset, SourcePosition source_position, bool is_statement, bool is_breakable=true)
template<typename IsolateT >
Handle< TrustedByteArray > ToSourcePositionTable (IsolateT *isolate)
base::OwnedVector< uint8_t > ToSourcePositionTableVector ()
bool Omit () const
bool Lazy () const
Private Member Functions
void AddEntry (const PositionTableEntry &entry)
Private Attributes
RecordingMode mode_
ZoneVector< uint8_t > bytes_
PositionTableEntry previous_
Detailed Description
Definition at line 41 of file source-position-table.h.
Member Enumeration Documentation
RecordingMode
enum v8::internal::SourcePositionTableBuilder::RecordingMode
Enumerator
OMIT_SOURCE_POSITIONS
LAZY_SOURCE_POSITIONS
RECORD_SOURCE_POSITIONS
Definition at line 43 of file source-position-table.h.
                     {
    // Indicates that source positions are never to be generated. (Resulting in
    // an empty table).
    OMIT_SOURCE_POSITIONS,
    // Indicates that source positions are not currently required, but may be
    // generated later.
    LAZY_SOURCE_POSITIONS,
    // Indicates that source positions should be immediately generated.
    RECORD_SOURCE_POSITIONS
  };
Constructor & Destructor Documentation
SourcePositionTableBuilder()
v8::internal::SourcePositionTableBuilder::SourcePositionTableBuilder (Zone * zone, SourcePositionTableBuilder::RecordingMode mode = RECORD_SOURCE_POSITIONS) [explicit]
Definition at line 159 of file source-position-table.cc.
    : mode_(mode),
      bytes_(zone),
#ifdef ENABLE_SLOW_DCHECKS
      raw_entries_(zone),
#endif
      previous_() {
}
Member Function Documentation
AddEntry()
void v8::internal::SourcePositionTableBuilder::AddEntry (const PositionTableEntry & entry) [inline], [private]
Definition at line 179 of file source-position-table.cc.
                                     {
  PositionTableEntry tmp(entry);
  SubtractFromEntry(&tmp, previous_);
  EncodeEntry(&bytes_, tmp);
  previous_ = entry;
#ifdef ENABLE_SLOW_DCHECKS
  raw_entries_.push_back(entry);
#endif
}
References bytes_, v8::internal::anonymous_namespace{source-position-table.cc}::EncodeEntry(), previous_, and v8::internal::anonymous_namespace{source-position-table.cc}::SubtractFromEntry().
Referenced by AddPosition().
AddPosition()
void v8::internal::SourcePositionTableBuilder::AddPosition (size_t code_offset, SourcePosition source_position, bool is_statement, bool is_breakable = true)
Definition at line 169 of file source-position-table.cc.
                                                                {
  if (Omit()) return;
  DCHECK(source_position.IsKnown());
  int offset = static_cast<int>(code_offset);
  AddEntry({offset, source_position.raw(), is_statement, is_breakable});
}
References AddEntry(), v8::internal::DCHECK(), v8::internal::SourcePosition::IsKnown(), Omit(), and v8::internal::SourcePosition::raw().
Referenced by v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), v8::internal::interpreter::BytecodeArrayWriter::SetFunctionEntrySourcePosition(), v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable(), and v8::internal::interpreter::BytecodeArrayWriter::UpdateSourcePositionTable().
Lazy()
bool v8::internal::SourcePositionTableBuilder::Lazy () const [inline]
Definition at line 66 of file source-position-table.h.
{ return mode_ == LAZY_SOURCE_POSITIONS; }
Omit()
bool v8::internal::SourcePositionTableBuilder::Omit () const [inline]
Definition at line 65 of file source-position-table.h.
{ return mode_ != RECORD_SOURCE_POSITIONS; }
Referenced by AddPosition(), and ToSourcePositionTable().
ToSourcePositionTable()
template<typename IsolateT >
Handle< TrustedByteArray > v8::internal::SourcePositionTableBuilder::ToSourcePositionTable (IsolateT * isolate)
Definition at line 191 of file source-position-table.cc.
                       {
  if (bytes_.empty()) return isolate->factory()->empty_trusted_byte_array();
  DCHECK(!Omit());
  Handle<TrustedByteArray> table =
      isolate->factory()->NewTrustedByteArray(static_cast<int>(bytes_.size()));
  MemCopy(table->begin(), bytes_.data(), bytes_.size());
#ifdef ENABLE_SLOW_DCHECKS
  // Brute force testing: Record all positions and decode
  // the entire table to verify they are identical.
  SourcePositionTableIterator it(
      *table, SourcePositionTableIterator::kAll,
      SourcePositionTableIterator::kDontSkipFunctionEntry);
  CheckTableEquals(raw_entries_, &it);
  // No additional source positions after creating the table.
  mode_ = OMIT_SOURCE_POSITIONS;
#endif
  return table;
}
References bytes_, v8::internal::ZoneVector< T >::data(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), v8::internal::SourcePositionTableIterator::kAll, v8::internal::SourcePositionTableIterator::kDontSkipFunctionEntry, v8::internal::MemCopy(), mode_, Omit(), OMIT_SOURCE_POSITIONS, and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode(), and v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable().
ToSourcePositionTableVector()
base::OwnedVector<uint8_t> v8::internal::SourcePositionTableBuilder::ToSourcePositionTableVector ()
Referenced by v8::internal::compiler::CodeGenerator::GetSourcePositionTable().
Member Data Documentation
bytes_
ZoneVector<uint8_t> v8::internal::SourcePositionTableBuilder::bytes_ [private]
Definition at line 72 of file source-position-table.h.
Referenced by AddEntry(), and ToSourcePositionTable().
mode_
RecordingMode v8::internal::SourcePositionTableBuilder::mode_ [private]
Definition at line 71 of file source-position-table.h.
Referenced by ToSourcePositionTable().
previous_
PositionTableEntry v8::internal::SourcePositionTableBuilder::previous_ [private]
Definition at line 76 of file source-position-table.h.
Referenced by AddEntry().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/source-position-table.h
/mnt/V8SourceCode/src/codegen/source-position-table.cc