v8::internal::LowLevelLogger Class Reference
Classes
struct CodeCreateStruct
struct CodeMoveStruct
Public Member Functions
LowLevelLogger (Isolate *isolate, const char *file_name)
~LowLevelLogger () override
void CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) override
void BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) override
void CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) override
void SnapshotPositionEvent (Tagged< HeapObject > obj, int pos)
void CodeMovingGCEvent () override
Private Member Functions
void LogRecordedBuffer (Tagged< AbstractCode > code, MaybeDirectHandle< SharedFunctionInfo > maybe_shared, const char *name, size_t length) override
void LogCodeInfo ()
void LogWriteBytes (const char *bytes, size_t size)
template<typename T >
void LogWriteStruct (const T &s)
Private Attributes
FILE * ll_output_handle_
Static Private Attributes
static const char kCodeMovingGCTag = 'G'
static const char kLogExt [] = `.ll`
Additional Inherited Members
Detailed Description
Definition at line 672 of file log.cc.
Constructor & Destructor Documentation
LowLevelLogger()
v8::internal::LowLevelLogger::LowLevelLogger (Isolate * isolate, const char * file_name)
Definition at line 731 of file log.cc.
    : CodeEventLogger(isolate), ll_output_handle_(nullptr) {
  // Open the low-level log file.
  size_t len = strlen(name);
  base::ScopedVector<char> ll_name(static_cast<int>(len + sizeof(kLogExt)));
  MemCopy(ll_name.begin(), name, len);
  MemCopy(ll_name.begin() + len, kLogExt, sizeof(kLogExt));
  ll_output_handle_ =
      base::OS::FOpen(ll_name.begin(), base::OS::LogFileOpenMode);
  setvbuf(ll_output_handle_, nullptr, _IOLBF, 0);
  LogCodeInfo();
}
References v8::base::Vector< T >::begin(), v8::base::OS::FOpen(), kLogExt, ll_output_handle_, LogCodeInfo(), v8::base::OS::LogFileOpenMode, v8::internal::MemCopy(), and v8::internal::name.
 LowLevelLogger()
v8::internal::LowLevelLogger::~LowLevelLogger () [override]
Definition at line 745 of file log.cc.
                                {
  base::Fclose(ll_output_handle_);
  ll_output_handle_ = nullptr;
}
References v8::base::Fclose(), and ll_output_handle_.
Member Function Documentation
BytecodeMoveEvent()
void v8::internal::LowLevelLogger::BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 813 of file log.cc.
                                                                 {
  CodeMoveStruct event;
  event.from_address = from->GetFirstBytecodeAddress();
  event.to_address = to->GetFirstBytecodeAddress();
  LogWriteStruct(event);
}
References v8::internal::LowLevelLogger::CodeMoveStruct::from_address, and LogWriteStruct().
CodeDisableOptEvent()
void v8::internal::LowLevelLogger::CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 681 of file log.cc.
                                                                             {}
CodeMoveEvent()
void v8::internal::LowLevelLogger::CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 805 of file log.cc.
                                                                 {
  CodeMoveStruct event;
  event.from_address = from->instruction_start();
  event.to_address = to->instruction_start();
  LogWriteStruct(event);
}
References v8::internal::LowLevelLogger::CodeMoveStruct::from_address, and LogWriteStruct().
CodeMovingGCEvent()
void v8::internal::LowLevelLogger::CodeMovingGCEvent () [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 827 of file log.cc.
                                       {
  const char tag = kCodeMovingGCTag;
  LogWriteBytes(&tag, sizeof(tag));
}
References kCodeMovingGCTag, and LogWriteBytes().
LogCodeInfo()
void v8::internal::LowLevelLogger::LogCodeInfo () [private]
Definition at line 750 of file log.cc.
                                 {
#if V8_TARGET_ARCH_IA32
  const char arch[] = "ia32";
#elif V8_TARGET_ARCH_X64 && V8_TARGET_ARCH_64_BIT
  const char arch[] = "x64";
#elif V8_TARGET_ARCH_ARM
  const char arch[] = "arm";
#elif V8_TARGET_ARCH_PPC64
  const char arch[] = "ppc64";
#elif V8_TARGET_ARCH_LOONG64
  const char arch[] = "loong64";
#elif V8_TARGET_ARCH_ARM64
  const char arch[] = "arm64";
#elif V8_TARGET_ARCH_S390X
  const char arch[] = "s390x";
#elif V8_TARGET_ARCH_RISCV64
  const char arch[] = "riscv64";
#elif V8_TARGET_ARCH_RISCV32
  const char arch[] = "riscv32";
#else
  const char arch[] = "unknown";
#endif
  LogWriteBytes(arch, sizeof(arch));
}
References LogWriteBytes().
Referenced by LowLevelLogger().
LogRecordedBuffer()
void v8::internal::LowLevelLogger::LogRecordedBuffer (Tagged< AbstractCode > code, MaybeDirectHandle< SharedFunctionInfo > maybe_shared, const char * name, size_t length) [override], [private], [virtual]
Implements v8::internal::CodeEventLogger.
Definition at line 775 of file log.cc.
                                                                        {
  DisallowGarbageCollection no_gc;
  PtrComprCageBase cage_base(isolate_);
  CodeCreateStruct event;
  event.name_size = static_cast<uint32_t>(length);
  event.code_address = code->InstructionStart(cage_base);
  event.code_size = code->InstructionSize(cage_base);
  LogWriteStruct(event);
  LogWriteBytes(name, length);
  LogWriteBytes(
      reinterpret_cast<const char*>(code->InstructionStart(cage_base)),
      code->InstructionSize(cage_base));
}
References code, v8::internal::CodeEventLogger::isolate_, v8::internal::length, LogWriteBytes(), LogWriteStruct(), v8::internal::name, v8::internal::LowLevelLogger::CodeCreateStruct::name_size, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
LogWriteBytes()
void v8::internal::LowLevelLogger::LogWriteBytes (const char * bytes, size_t size) [private]
Definition at line 821 of file log.cc.
                                                                 {
  size_t rv = fwrite(bytes, 1, size, ll_output_handle_);
  DCHECK_EQ(size, rv);
  USE(rv);
}
References DCHECK_EQ, ll_output_handle_, size(), and USE.
Referenced by CodeMovingGCEvent(), LogCodeInfo(), LogRecordedBuffer(), and LogWriteStruct().
LogWriteStruct()
template<typename T >
void v8::internal::LowLevelLogger::LogWriteStruct (const T & s) [inline], [private]
Definition at line 720 of file log.cc.
                                  {
    char tag = T::kTag;
    LogWriteBytes(reinterpret_cast<const char*>(&tag), sizeof(tag));
    LogWriteBytes(reinterpret_cast<const char*>(&s), sizeof(s));
  }
References LogWriteBytes().
Referenced by BytecodeMoveEvent(), CodeMoveEvent(), and LogRecordedBuffer().
SnapshotPositionEvent()
void v8::internal::LowLevelLogger::SnapshotPositionEvent (Tagged< HeapObject > obj, int pos)
Member Data Documentation
kCodeMovingGCTag
const char v8::internal::LowLevelLogger::kCodeMovingGCTag = 'G' [static], [private]
Definition at line 711 of file log.cc.
Referenced by CodeMovingGCEvent().
kLogExt
const char v8::internal::LowLevelLogger::kLogExt = `.ll` [static], [private]
Definition at line 714 of file log.cc.
Referenced by LowLevelLogger().
ll_output_handle_
FILE* v8::internal::LowLevelLogger::ll_output_handle_ [private]
Definition at line 726 of file log.cc.
Referenced by LogWriteBytes(), LowLevelLogger(), and ~LowLevelLogger().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/log.cc