v8::internal::torque::VisitResult Class Reference
#include <types.h>
Public Member Functions
VisitResult ()=default
VisitResult (const Type *type, const std::string &constexpr_value)
VisitResult (const Type *type, StackRange stack_range)
const Type * type () const
const std::string & constexpr_value () const
const StackRange & stack_range () const
void SetType (const Type *new_type)
bool IsOnStack () const
bool operator== (const VisitResult &other) const
Static Public Member Functions
static VisitResult NeverResult ()
static VisitResult TopTypeResult (std::string top_reason, const Type *from_type)
Private Attributes
const Type * type_ = nullptr
std::optional< std::string > constexpr_value_
std::optional< StackRange > stack_range_
Detailed Description
Definition at line 832 of file types.h.
Constructor & Destructor Documentation
VisitResult() [1/3]
v8::internal::torque::VisitResult::VisitResult () [default]
VisitResult() [2/3]
v8::internal::torque::VisitResult::VisitResult (const Type * type, const std::string & constexpr_value) [inline]
Definition at line 835 of file types.h.
      : type_(type), constexpr_value_(constexpr_value) {
    DCHECK(type->IsConstexpr());
  }
References v8::internal::DCHECK(), v8::internal::torque::Type::IsConstexpr(), and type().
VisitResult() [3/3]
v8::internal::torque::VisitResult::VisitResult (const Type * type, StackRange stack_range) [inline]
Definition at line 842 of file types.h.
      : type_(type), stack_range_(stack_range) {
    DCHECK(!type->IsConstexpr());
  }
References v8::internal::DCHECK(), v8::internal::torque::Type::IsConstexpr(), and type().
Member Function Documentation
constexpr_value()
const std::string& v8::internal::torque::VisitResult::constexpr_value () const [inline]
Definition at line 847 of file types.h.
{ return *constexpr_value_; }
References constexpr_value_.
Referenced by v8::internal::torque::ImplementationVisitor::AddCallParameter(), and v8::internal::torque::ImplementationVisitor::Visit().
IsOnStack()
bool v8::internal::torque::VisitResult::IsOnStack () const [inline]
Definition at line 850 of file types.h.
{ return stack_range_ != std::nullopt; }
References stack_range_.
Referenced by v8::internal::torque::ImplementationVisitor::AddCallParameter(), v8::internal::torque::ImplementationVisitor::GenerateCopy(), v8::internal::torque::LocationReference::VariableAccess(), and v8::internal::torque::ImplementationVisitor::Visit().
NeverResult()
VisitResult v8::internal::torque::VisitResult::NeverResult () [static]
Definition at line 1236 of file types.cc.
                                     {
  VisitResult result;
  result.type_ = TypeOracle::GetNeverType();
  return result;
}
References v8::internal::torque::TypeOracle::GetNeverType(), and v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::InlineMacro().
operator==()
bool v8::internal::torque::VisitResult::operator== (const VisitResult & other) const [inline]
Definition at line 851 of file types.h.
                                                  {
    return type_ == other.type_ && constexpr_value_ == other.constexpr_value_ &&
           stack_range_ == other.stack_range_;
  }
References constexpr_value_, stack_range_, and type_.
SetType()
void v8::internal::torque::VisitResult::SetType (const Type * new_type) [inline]
Definition at line 849 of file types.h.
{ type_ = new_type; }
References type_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), and v8::internal::torque::ImplementationVisitor::GenerateImplicitConvert().
stack_range()
const StackRange& v8::internal::torque::VisitResult::stack_range () const [inline]
Definition at line 848 of file types.h.
{ return *stack_range_; }
References stack_range_.
Referenced by v8::internal::torque::ImplementationVisitor::AddCallParameter(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateCopy(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit(), v8::internal::torque::ProjectStructField(), and v8::internal::torque::ImplementationVisitor::Visit().
TopTypeResult()
VisitResult v8::internal::torque::VisitResult::TopTypeResult (std::string top_reason, const Type * from_type) [static]
Definition at line 1242 of file types.cc.
                                                              {
  VisitResult result;
  result.type_ = TypeOracle::GetTopType(std::move(top_reason), from_type);
  return result;
}
References v8::internal::torque::TypeOracle::GetTopType(), and v8::base::internal::result.
type()
const Type* v8::internal::torque::VisitResult::type () const [inline]
Definition at line 846 of file types.h.
{ return type_; }
References type_.
Referenced by v8::internal::torque::ImplementationVisitor::AddCallParameter(), v8::internal::torque::Binding< T >::CheckWritten(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateCopy(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GenerateImplicitConvert(), v8::internal::torque::ImplementationVisitor::GeneratePointerCall(), v8::internal::torque::ImplementationVisitor::GenerateReferenceToItemInHeapSlice(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::LocationReference::HeapReference(), v8::internal::torque::LocationReference::HeapSlice(), v8::internal::torque::ProjectStructField(), v8::internal::torque::LocationReference::ReferencedType(), v8::internal::torque::ImplementationVisitor::Visit(), and VisitResult().
Member Data Documentation
constexpr_value_
std::optional<std::string> v8::internal::torque::VisitResult::constexpr_value_ [private]
Definition at line 858 of file types.h.
Referenced by constexpr_value(), and operator==().
stack_range_
std::optional<StackRange> v8::internal::torque::VisitResult::stack_range_ [private]
Definition at line 859 of file types.h.
Referenced by IsOnStack(), operator==(), and stack_range().
type_
const Type* v8::internal::torque::VisitResult::type_ = nullptr [private]
Definition at line 857 of file types.h.
Referenced by operator==(), SetType(), and type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/types.h
/mnt/V8SourceCode/src/torque/types.cc