v8::internal::AssemblerRISCVA Class Reference
#include <extension-riscv-a.h>
Public Member Functions
void lr_w (bool aq, bool rl, Register rd, Register addr)
void sc_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amoswap_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amoadd_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amoxor_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amoand_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amoor_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amomin_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amomax_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amominu_w (bool aq, bool rl, Register rd, Register addr, Register src)
void amomaxu_w (bool aq, bool rl, Register rd, Register addr, Register src)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-a.h.
Member Function Documentation
amoadd_w()
void v8::internal::AssemblerRISCVA::amoadd_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 24 of file extension-riscv-a.cc.
                                             {
  GenInstrRAtomic(0b00000, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
amoand_w()
void v8::internal::AssemblerRISCVA::amoand_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 34 of file extension-riscv-a.cc.
                                             {
  GenInstrRAtomic(0b01100, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
amomax_w()
void v8::internal::AssemblerRISCVA::amomax_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 49 of file extension-riscv-a.cc.
                                             {
  GenInstrRAtomic(0b10100, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
amomaxu_w()
void v8::internal::AssemblerRISCVA::amomaxu_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 59 of file extension-riscv-a.cc.
                                              {
  GenInstrRAtomic(0b11100, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
amomin_w()
void v8::internal::AssemblerRISCVA::amomin_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 44 of file extension-riscv-a.cc.
                                             {
  GenInstrRAtomic(0b10000, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
amominu_w()
void v8::internal::AssemblerRISCVA::amominu_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 54 of file extension-riscv-a.cc.
                                              {
  GenInstrRAtomic(0b11000, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
amoor_w()
void v8::internal::AssemblerRISCVA::amoor_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 39 of file extension-riscv-a.cc.
                                            {
  GenInstrRAtomic(0b01000, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
amoswap_w()
void v8::internal::AssemblerRISCVA::amoswap_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 19 of file extension-riscv-a.cc.
                                              {
  GenInstrRAtomic(0b00001, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
amoxor_w()
void v8::internal::AssemblerRISCVA::amoxor_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 29 of file extension-riscv-a.cc.
                                             {
  GenInstrRAtomic(0b00100, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
lr_w()
void v8::internal::AssemblerRISCVA::lr_w (bool aq, bool rl, Register rd, Register addr)
Definition at line 10 of file extension-riscv-a.cc.
                                                                       {
  GenInstrRAtomic(0b00010, aq, rl, 0b010, rd, addr, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
Referenced by v8::internal::MacroAssembler::Ll().
sc_w()
void v8::internal::AssemblerRISCVA::sc_w (bool aq, bool rl, Register rd, Register addr, Register src)
Definition at line 14 of file extension-riscv-a.cc.
                                         {
  GenInstrRAtomic(0b00011, aq, rl, 0b010, rd, addr, src);
}
References v8::internal::AssemblerRiscvBase::GenInstrRAtomic().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-a.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-a.cc