v8::internal::compiler::UnionType Class Reference
#include <turbofan-types.h>
Private Member Functions
UnionType (int length, Zone *zone)
bool Wellformed () const
Static Private Member Functions
static UnionType * New (int length, Zone *zone)
Private Attributes
friend Type
friend BitsetType
friend Zone
Additional Inherited Members
Detailed Description
Definition at line 720 of file turbofan-types.h.
Constructor & Destructor Documentation
UnionType()
v8::internal::compiler::UnionType::UnionType (int length, Zone * zone) [inline], [private]
Definition at line 726 of file turbofan-types.h.
: StructuralType(kUnion, length, zone) {}
Member Function Documentation
New()
static UnionType* v8::internal::compiler::UnionType::New (int length, Zone * zone) [inline], [static], [private]
Definition at line 728 of file turbofan-types.h.
                                                {
    return zone->New<UnionType>(length, zone);
  }
References v8::internal::length, and v8::internal::Zone::New().
Wellformed()
bool v8::internal::compiler::UnionType::Wellformed () const [private]
Definition at line 694 of file turbofan-types.cc.
                                 {
  DisallowGarbageCollection no_gc;
  // This checks the invariants of the union representation:
  // 1. There are at least two elements.
  // 2. The first element is a bitset, no other element is a bitset.
  // 3. At most one element is a range, and it must be the second one.
  // 4. No element is itself a union.
  // 5. No element (except the bitset) is a subtype of any other.
  // 6. If there is a range, then the bitset type does not contain
  // plain number bits.
  DCHECK_LE(2, this->Length()); // (1)
  DCHECK(this->Get(0).IsBitset()); // (2a)
  for (int i = 0; i < this->Length(); ++i) {
    if (i != 0) DCHECK(!this->Get(i).IsBitset()); // (2b)
    if (i != 1) DCHECK(!this->Get(i).IsRange()); // (3)
    DCHECK(!this->Get(i).IsUnion()); // (4)
    for (int j = 0; j < this->Length(); ++j) {
      if (i != j && i != 0) DCHECK(!this->Get(i).Is(this->Get(j))); // (5)
    }
  }
  DCHECK(!this->Get(1).IsRange() ||
         (BitsetType::NumberBits(this->Get(0).AsBitset()) ==
          BitsetType::kNone)); // (6)
  return true;
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::StructuralType::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Is(), v8::internal::compiler::StructuralType::Length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::compiler::BitsetType::NumberBits().
Member Data Documentation
BitsetType
friend v8::internal::compiler::UnionType::BitsetType [private]
Definition at line 723 of file turbofan-types.h.
Type
friend v8::internal::compiler::UnionType::Type [private]
Definition at line 722 of file turbofan-types.h.
Zone
friend v8::internal::compiler::UnionType::Zone [private]
Definition at line 724 of file turbofan-types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turbofan-types.h
/mnt/V8SourceCode/src/compiler/turbofan-types.cc