v8::internal::maglev::GetTemplateObject Class Reference
#include <maglev-ir.h>
Public Member Functions
GetTemplateObject (uint64_t bitfield, compiler::SharedFunctionInfoRef shared_function_info, const compiler::FeedbackSource &feedback)
Input & description ()
compiler::SharedFunctionInfoRef shared_function_info ()
compiler::FeedbackSource feedback () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, GetTemplateObject >
Private Attributes
compiler::SharedFunctionInfoRef shared_function_info_
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 7645 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::GetTemplateObject::Base = FixedInputValueNodeT<1, GetTemplateObject> [private]
Definition at line 7646 of file maglev-ir.h.
Constructor & Destructor Documentation
GetTemplateObject()
v8::internal::maglev::GetTemplateObject::GetTemplateObject (uint64_t bitfield, compiler::SharedFunctionInfoRef shared_function_info, const compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 7649 of file maglev-ir.h.
      : Base(bitfield),
        shared_function_info_(shared_function_info),
        feedback_(feedback) {}
Member Function Documentation
description()
Input& v8::internal::maglev::GetTemplateObject::description () [inline]
Definition at line 7662 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::GetTemplateObject::feedback () const [inline]
Definition at line 7667 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::GetTemplateObject::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::GetTemplateObject::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::GetTemplateObject::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 7672 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::GetTemplateObject::SetValueLocationConstraints ()
shared_function_info()
compiler::SharedFunctionInfoRef v8::internal::maglev::GetTemplateObject::shared_function_info () [inline]
Definition at line 7664 of file maglev-ir.h.
                                                       {
    return shared_function_info_;
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::GetTemplateObject::feedback_ [private]
Definition at line 7676 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::GetTemplateObject::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 7660 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::GetTemplateObject::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::GenericRuntimeOrBuiltinCall()
Definition at line 7657 of file maglev-ir.h.
shared_function_info_
compiler::SharedFunctionInfoRef v8::internal::maglev::GetTemplateObject::shared_function_info_ [private]
Definition at line 7675 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h