v8::internal::TurbofanCompilationJob Class Reference
#include <compiler.h>
Public Member Functions
V8_EXPORT_PRIVATE TurbofanCompilationJob (Isolate *isolate, OptimizedCompilationInfo *compilation_info, State initial_state)
OptimizedCompilationInfo * compilation_info () const
Status RetryOptimization (BailoutReason reason)
Status AbortOptimization (BailoutReason reason)
void RecordCompilationStats (ConcurrencyMode mode, Isolate *isolate) const
void RecordFunctionCompilation (LogEventListener::CodeTag code_type, Isolate *isolate) const
virtual int FinalizeOrder () const
uint64_t trace_id () const
Isolate * isolate () const
void Cancel ()
Private Attributes
Isolate *const isolate_
OptimizedCompilationInfo *const compilation_info_
uint64_t trace_id_
Additional Inherited Members
Detailed Description
Definition at line 465 of file compiler.h.
Constructor & Destructor Documentation
TurbofanCompilationJob()
v8::internal::TurbofanCompilationJob::TurbofanCompilationJob (Isolate * isolate, OptimizedCompilationInfo * compilation_info, State initial_state)
Definition at line 525 of file compiler.cc.
    : OptimizedCompilationJob("Turbofan", initial_state),
      isolate_(isolate),
      compilation_info_(compilation_info),
      trace_id_(GetNextTraceId() ^ reinterpret_cast<uintptr_t>(this)) {}
Member Function Documentation
AbortOptimization()
CompilationJob::Status v8::internal::TurbofanCompilationJob::AbortOptimization (BailoutReason reason)
Definition at line 540 of file compiler.cc.
                          {
  DCHECK(compilation_info_->IsOptimizing());
  compilation_info_->AbortOptimization(reason);
  return UpdateState(FAILED, State::kFailed);
}
References v8::internal::OptimizedCompilationInfo::AbortOptimization(), compilation_info_, v8::internal::DCHECK(), v8::internal::CompilationJob::FAILED, v8::internal::OptimizedCompilationInfo::IsOptimizing(), v8::internal::CompilationJob::kFailed, and v8::internal::CompilationJob::UpdateState().
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), and v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl().
Cancel()
void v8::internal::TurbofanCompilationJob::Cancel ()
Definition at line 547 of file compiler.cc.
{ compilation_info_->mark_cancelled(); }
References compilation_info_, and v8::internal::OptimizedCompilationInfo::mark_cancelled().
compilation_info()
OptimizedCompilationInfo* v8::internal::TurbofanCompilationJob::compilation_info () const [inline]
Definition at line 471 of file compiler.h.
                                                     {
    return compilation_info_;
  }
References compilation_info_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::Compiler::DisposeTurbofanCompilationJob(), v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), v8::internal::Compiler::FinalizeTurbofanCompilationJob(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), RecordCompilationStats(), and RecordFunctionCompilation().
FinalizeOrder()
virtual int v8::internal::TurbofanCompilationJob::FinalizeOrder () const [inline], [virtual]
Reimplemented in v8::internal::compiler::CodeAssemblerCompilationJob.
Definition at line 489 of file compiler.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
isolate()
Isolate* v8::internal::TurbofanCompilationJob::isolate () const [inline]
Definition at line 494 of file compiler.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::compiler::CheckNoDeprecatedMaps(), v8::internal::OptimizingCompileInputQueue::Dequeue(), v8::internal::OptimizingCompileInputQueue::DequeueIfIsolateMatches(), v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::EmplacePipeline(), v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::FinalizeCode(), v8::internal::compiler::CodeAssemblerCompilationJob::FinalizeJobImpl(), v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), v8::internal::OptimizingCompileInputQueue::FlushJobsForIsolate(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), v8::internal::compiler::Pipeline::NewBytecodeHandlerCompilationJob(), v8::internal::compiler::Pipeline::NewCompilationJob(), v8::internal::compiler::Pipeline::NewCSLinkageCodeStubBuiltinCompilationJob(), v8::internal::compiler::CodeAssemblerCompilationJob::NewJobForTesting(), v8::internal::compiler::Pipeline::NewJSLinkageCodeStubBuiltinCompilationJob(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), v8::internal::compiler::PrintCode(), v8::internal::OptimizingCompileDispatcher::QueueFinishedJob(), RecordCompilationStats(), RecordFunctionCompilation(), v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run(), and v8::internal::compiler::CodeAssemblerCompilationJob::ShouldOptimizeJumps().
RecordCompilationStats()
void v8::internal::TurbofanCompilationJob::RecordCompilationStats (ConcurrencyMode mode, Isolate * isolate) const
Definition at line 549 of file compiler.cc.
                                                                            {
  DCHECK(compilation_info()->IsOptimizing());
  DirectHandle<SharedFunctionInfo> shared = compilation_info()->shared_info();
  if (v8_flags.trace_opt || v8_flags.trace_opt_stats) {
    double ms_creategraph = time_taken_to_prepare_.InMillisecondsF();
    double ms_optimize = time_taken_to_execute_.InMillisecondsF();
    double ms_codegen = time_taken_to_finalize_.InMillisecondsF();
    if (v8_flags.trace_opt) {
      CompilerTracer::TraceFinishTurbofanCompile(
          isolate, compilation_info(), ms_creategraph, ms_optimize, ms_codegen);
    }
    if (v8_flags.trace_opt_stats) {
      static double compilation_time = 0.0;
      static int compiled_functions = 0;
      static int code_size = 0;
      compilation_time += (ms_creategraph + ms_optimize + ms_codegen);
      compiled_functions++;
      code_size += shared->SourceSize();
      PrintF(
          "[turbofan] Compiled: %d functions with %d byte source size in "
          "%fms.\n",
          compiled_functions, code_size, compilation_time);
    }
  }
  // Don't record samples from machines without high-resolution timers,
  // as that can cause serious reporting issues. See the thread at
  // http://g/chrome-metrics-team/NwwJEyL8odU/discussion for more details.
  if (!base::TimeTicks::IsHighResolution()) return;
  int elapsed_microseconds = static_cast<int>(ElapsedTime().InMicroseconds());
  Counters* const counters = isolate->counters();
  counters->turbofan_ticks()->AddSample(static_cast<int>(
      compilation_info()->tick_counter().CurrentTicks() / 1000));
  if (compilation_info()->is_osr()) {
    counters->turbofan_osr_prepare()->AddSample(
        static_cast<int>(time_taken_to_prepare_.InMicroseconds()));
    counters->turbofan_osr_execute()->AddSample(
        static_cast<int>(time_taken_to_execute_.InMicroseconds()));
    counters->turbofan_osr_finalize()->AddSample(
        static_cast<int>(time_taken_to_finalize_.InMicroseconds()));
    counters->turbofan_osr_total_time()->AddSample(elapsed_microseconds);
    return;
  }
  DCHECK(!compilation_info()->is_osr());
  counters->turbofan_optimize_prepare()->AddSample(
      static_cast<int>(time_taken_to_prepare_.InMicroseconds()));
  counters->turbofan_optimize_execute()->AddSample(
      static_cast<int>(time_taken_to_execute_.InMicroseconds()));
  counters->turbofan_optimize_finalize()->AddSample(
      static_cast<int>(time_taken_to_finalize_.InMicroseconds()));
  counters->turbofan_optimize_total_time()->AddSample(elapsed_microseconds);
  // Compute foreground / background time.
  base::TimeDelta time_background;
  base::TimeDelta time_foreground =
      time_taken_to_prepare_ + time_taken_to_finalize_;
  switch (mode) {
    case ConcurrencyMode::kConcurrent:
      time_background += time_taken_to_execute_;
      counters->turbofan_optimize_concurrent_total_time()->AddSample(
          elapsed_microseconds);
      break;
    case ConcurrencyMode::kSynchronous:
      counters->turbofan_optimize_non_concurrent_total_time()->AddSample(
          elapsed_microseconds);
      time_foreground += time_taken_to_execute_;
      break;
  }
  counters->turbofan_optimize_total_background()->AddSample(
      static_cast<int>(time_background.InMicroseconds()));
  counters->turbofan_optimize_total_foreground()->AddSample(
      static_cast<int>(time_foreground.InMicroseconds()));
  if (v8_flags.profile_guided_optimization &&
      shared->cached_tiering_decision() ==
          CachedTieringDecision::kEarlyMaglev) {
    shared->set_cached_tiering_decision(CachedTieringDecision::kEarlyTurbofan);
  }
}
References compilation_info(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::internal::OptimizedCompilationJob::ElapsedTime(), v8::base::TimeDelta::InMicroseconds(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::base::TimeTicks::IsHighResolution(), isolate(), v8::internal::kConcurrent, v8::internal::kEarlyMaglev, v8::internal::kEarlyTurbofan, v8::internal::kSynchronous, mode(), v8::internal::PrintF(), v8::internal::OptimizedCompilationInfo::shared_info(), v8::internal::OptimizedCompilationJob::time_taken_to_execute_, v8::internal::OptimizedCompilationJob::time_taken_to_finalize_, v8::internal::OptimizedCompilationJob::time_taken_to_prepare_, and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), and v8::internal::Compiler::FinalizeTurbofanCompilationJob().
RecordFunctionCompilation()
void v8::internal::TurbofanCompilationJob::RecordFunctionCompilation (LogEventListener::CodeTag code_type, Isolate * isolate) const
Definition at line 633 of file compiler.cc.
                                                               {
  DirectHandle<AbstractCode> abstract_code =
      Cast<AbstractCode>(compilation_info()->code());
  double time_taken_ms = time_taken_to_prepare_.InMillisecondsF() +
                         time_taken_to_execute_.InMillisecondsF() +
                         time_taken_to_finalize_.InMillisecondsF();
  DirectHandle<Script> script(
      Cast<Script>(compilation_info()->shared_info()->script()), isolate);
  DirectHandle<FeedbackVector> feedback_vector(
      compilation_info()->closure()->feedback_vector(), isolate);
  Compiler::LogFunctionCompilation(
      isolate, code_type, script, compilation_info()->shared_info(),
      feedback_vector, abstract_code, compilation_info()->code_kind(),
      time_taken_ms);
}
References code, compilation_info(), v8::base::TimeDelta::InMillisecondsF(), isolate(), v8::internal::Compiler::LogFunctionCompilation(), v8::internal::script, v8::internal::OptimizedCompilationJob::time_taken_to_execute_, v8::internal::OptimizedCompilationJob::time_taken_to_finalize_, and v8::internal::OptimizedCompilationJob::time_taken_to_prepare_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), and v8::internal::Compiler::FinalizeTurbofanCompilationJob().
RetryOptimization()
CompilationJob::Status v8::internal::TurbofanCompilationJob::RetryOptimization (BailoutReason reason)
Definition at line 533 of file compiler.cc.
                          {
  DCHECK(compilation_info_->IsOptimizing());
  compilation_info_->RetryOptimization(reason);
  return UpdateState(FAILED, State::kFailed);
}
References compilation_info_, v8::internal::DCHECK(), v8::internal::CompilationJob::FAILED, v8::internal::OptimizedCompilationInfo::IsOptimizing(), v8::internal::CompilationJob::kFailed, v8::internal::OptimizedCompilationInfo::RetryOptimization(), and v8::internal::CompilationJob::UpdateState().
Referenced by v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), and v8::internal::Compiler::FinalizeTurbofanCompilationJob().
trace_id()
uint64_t v8::internal::TurbofanCompilationJob::trace_id () const
Definition at line 652 of file compiler.cc.
                                                {
  // Xor together the this pointer and the optimization id, to try to make the
  // id more unique on platforms where just the `this` pointer is likely to be
  // reused.
  return trace_id_;
}
References trace_id_.
Referenced by v8::internal::Compiler::DisposeTurbofanCompilationJob(), v8::internal::Compiler::FinalizeTurbofanCompilationJob(), and v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob().
Member Data Documentation
compilation_info_
OptimizedCompilationInfo* const v8::internal::TurbofanCompilationJob::compilation_info_ [private]
Definition at line 500 of file compiler.h.
Referenced by AbortOptimization(), Cancel(), compilation_info(), and RetryOptimization().
isolate_
Isolate* const v8::internal::TurbofanCompilationJob::isolate_ [private]
Definition at line 499 of file compiler.h.
Referenced by isolate().
trace_id_
uint64_t v8::internal::TurbofanCompilationJob::trace_id_ [private]
Definition at line 501 of file compiler.h.
Referenced by trace_id().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compiler.h
/mnt/V8SourceCode/src/codegen/compiler.cc