v8::internal::ClassLiteralStaticElement Class Reference
#include <ast.h>
Public Types
enum Kind : uint8_t { PROPERTY
, STATIC_BLOCK
 }
Public Member Functions
Kind kind () const
ClassLiteralProperty * property () const
Block * static_block () const
Private Member Functions
ClassLiteralStaticElement (ClassLiteralProperty *property)
ClassLiteralStaticElement (Block *static_block)
Private Attributes
friend Zone
Kind kind_
xx xx xx xx xx xx xx xx xx
union {
 ClassLiteralProperty * property_
 Block * static_block_
};
Friends
class AstNodeFactory
Detailed Description
Definition at line 2606 of file ast.h.
Member Enumeration Documentation
Kind
enum v8::internal::ClassLiteralStaticElement::Kind : uint8_t
Enumerator
PROPERTY
STATIC_BLOCK
Definition at line 2608 of file ast.h.
: uint8_t { PROPERTY, STATIC_BLOCK };
Constructor & Destructor Documentation
ClassLiteralStaticElement() [1/2]
v8::internal::ClassLiteralStaticElement::ClassLiteralStaticElement (ClassLiteralProperty * property) [inline], [explicit], [private]
Definition at line 2626 of file ast.h.
      : kind_(PROPERTY), property_(property) {}
ClassLiteralStaticElement() [2/2]
v8::internal::ClassLiteralStaticElement::ClassLiteralStaticElement (Block * static_block) [inline], [explicit], [private]
Definition at line 2629 of file ast.h.
      : kind_(STATIC_BLOCK), static_block_(static_block) {}
Member Function Documentation
kind()
Kind v8::internal::ClassLiteralStaticElement::kind () const [inline]
Definition at line 2610 of file ast.h.
{ return kind_; }
References kind_.
Referenced by property(), and static_block().
property()
ClassLiteralProperty* v8::internal::ClassLiteralStaticElement::property () const [inline]
Definition at line 2612 of file ast.h.
                                         {
    DCHECK(kind() == PROPERTY);
    return property_;
  }
References v8::internal::DCHECK(), kind(), PROPERTY, and property_.
static_block()
Block* v8::internal::ClassLiteralStaticElement::static_block () const [inline]
Definition at line 2617 of file ast.h.
                              {
    DCHECK(kind() == STATIC_BLOCK);
    return static_block_;
  }
References v8::internal::DCHECK(), kind(), STATIC_BLOCK, and static_block_.
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2623 of file ast.h.
Member Data Documentation
union { ... } [private]
kind_
Kind v8::internal::ClassLiteralStaticElement::kind_ [private]
Definition at line 2632 of file ast.h.
Referenced by kind().
property_
ClassLiteralProperty* v8::internal::ClassLiteralStaticElement::property_
Definition at line 2635 of file ast.h.
Referenced by property().
static_block_
Block* v8::internal::ClassLiteralStaticElement::static_block_
Definition at line 2636 of file ast.h.
Referenced by static_block().
Zone
friend v8::internal::ClassLiteralStaticElement::Zone [private]
Definition at line 2624 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h