v8::internal::PlatformEmbeddedFileWriterMac Class Reference
#include <platform-embedded-file-writer-mac.h>
Public Member Functions
PlatformEmbeddedFileWriterMac (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os)
void SectionText () override
void SectionRoData () override
void AlignToCodeAlignment () override
void AlignToPageSizeIfNeeded () override
void AlignToDataAlignment () override
void DeclareUint32 (const char *name, uint32_t value) override
void DeclareSymbolGlobal (const char *name) override
void DeclareLabel (const char *name) override
void SourceInfo (int fileid, const char *filename, int line) override
void DeclareFunctionBegin (const char *name, uint32_t size) override
void DeclareFunctionEnd (const char *name) override
void Comment (const char *string) override
void FilePrologue () override
void DeclareExternalFilename (int fileid, const char *filename) override
void FileEpilogue () override
int IndentedDataDirective (DataDirective directive) override
Private Attributes
const EmbeddedTargetArch target_arch_
const EmbeddedTargetOs target_os_
Additional Inherited Members
Detailed Description
Definition at line 14 of file platform-embedded-file-writer-mac.h.
Constructor & Destructor Documentation
PlatformEmbeddedFileWriterMac()
v8::internal::PlatformEmbeddedFileWriterMac::PlatformEmbeddedFileWriterMac (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os) [inline]
Definition at line 16 of file platform-embedded-file-writer-mac.h.
      : target_arch_(target_arch), target_os_(target_os) {
    USE(target_arch_);
    USE(target_os_);
    DCHECK_EQ(target_os_, EmbeddedTargetOs::kMac);
  }
References DCHECK_EQ, v8::internal::kMac, target_arch_, target_os_, and USE.
Member Function Documentation
AlignToCodeAlignment()
void v8::internal::PlatformEmbeddedFileWriterMac::AlignToCodeAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 53 of file platform-embedded-file-writer-mac.cc.
                                                         {
#if V8_TARGET_ARCH_X64
  // On x64 use 64-bytes code alignment to allow 64-bytes loop header alignment.
  static_assert(64 >= kCodeAlignment);
  fprintf(fp_, ".balign 64\n");
#elif V8_TARGET_ARCH_PPC64
  // 64 byte alignment is needed on ppc64 to make sure p10 prefixed instructions
  // don't cross 64-byte boundaries.
  static_assert(64 >= kCodeAlignment);
  fprintf(fp_, ".balign 64\n");
#elif V8_TARGET_ARCH_ARM64
  // ARM64 macOS has a 16kiB page size. Since we want to remap it on the heap,
  // needs to be page-aligned.
  fprintf(fp_, ".balign 16384\n");
#else
  static_assert(32 >= kCodeAlignment);
  fprintf(fp_, ".balign 32\n");
#endif
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::kCodeAlignment.
AlignToDataAlignment()
void v8::internal::PlatformEmbeddedFileWriterMac::AlignToDataAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 82 of file platform-embedded-file-writer-mac.cc.
                                                         {
  static_assert(8 >= InstructionStream::kMetadataAlignment);
  fprintf(fp_, ".balign 8\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::InstructionStream::kMetadataAlignment.
AlignToPageSizeIfNeeded()
void v8::internal::PlatformEmbeddedFileWriterMac::AlignToPageSizeIfNeeded () [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 73 of file platform-embedded-file-writer-mac.cc.
                                                            {
#if V8_TARGET_ARCH_ARM64
  // ARM64 macOS has a 16kiB page size. Since we want to remap builtins on the
  // heap, make sure that the trailing part of the page doesn't contain anything
  // dangerous.
  fprintf(fp_, ".balign 16384\n");
#endif
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Comment()
void v8::internal::PlatformEmbeddedFileWriterMac::Comment (const char * string) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 87 of file platform-embedded-file-writer-mac.cc.
                                                              {
  fprintf(fp_, "// %s\n", string);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
DeclareExternalFilename()
void v8::internal::PlatformEmbeddedFileWriterMac::DeclareExternalFilename (int fileid, const char * filename) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 113 of file platform-embedded-file-writer-mac.cc.
                                      {
  fprintf(fp_, ".file %d \"%s\"\n", fileid, filename);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
DeclareFunctionBegin()
void v8::internal::PlatformEmbeddedFileWriterMac::DeclareFunctionBegin (const char * name, uint32_t size) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 101 of file platform-embedded-file-writer-mac.cc.
                                                                        {
  DeclareLabel(name);
  // TODO(mvstanton): Investigate the proper incantations to mark the label as
  // a function on OSX.
}
References DeclareLabel(), and v8::internal::name.
DeclareFunctionEnd()
void v8::internal::PlatformEmbeddedFileWriterMac::DeclareFunctionEnd (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 109 of file platform-embedded-file-writer-mac.cc.
{}
DeclareLabel()
void v8::internal::PlatformEmbeddedFileWriterMac::DeclareLabel (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 91 of file platform-embedded-file-writer-mac.cc.
                                                                 {
  fprintf(fp_, "_%s:\n", name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::name.
Referenced by DeclareFunctionBegin(), and DeclareUint32().
DeclareSymbolGlobal()
void v8::internal::PlatformEmbeddedFileWriterMac::DeclareSymbolGlobal (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 45 of file platform-embedded-file-writer-mac.cc.
                                                                        {
  // TODO(jgruber): Investigate switching to .globl. Using .private_extern
  // prevents something along the compilation chain from messing with the
  // embedded blob. Using .global here causes embedded blob hash verification
  // failures at runtime.
  fprintf(fp_, ".private_extern _%s\n", name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::name.
Referenced by DeclareUint32().
DeclareUint32()
void v8::internal::PlatformEmbeddedFileWriterMac::DeclareUint32 (const char * name, uint32_t value) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 36 of file platform-embedded-file-writer-mac.cc.
                                                                  {
  DeclareSymbolGlobal(name);
  DeclareLabel(name);
  IndentedDataDirective(kLong);
  fprintf(fp_, "%d", value);
  Newline();
}
References DeclareLabel(), DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterBase::fp_, IndentedDataDirective(), v8::internal::kLong, v8::internal::name, v8::internal::PlatformEmbeddedFileWriterBase::Newline(), and v8::internal::value.
FileEpilogue()
void v8::internal::PlatformEmbeddedFileWriterMac::FileEpilogue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 118 of file platform-embedded-file-writer-mac.cc.
{}
FilePrologue()
void v8::internal::PlatformEmbeddedFileWriterMac::FilePrologue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 111 of file platform-embedded-file-writer-mac.cc.
{}
IndentedDataDirective()
int v8::internal::PlatformEmbeddedFileWriterMac::IndentedDataDirective (DataDirective directive) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 120 of file platform-embedded-file-writer-mac.cc.
                             {
  return fprintf(fp_, " %s ", DirectiveAsString(directive));
}
References v8::internal::anonymous_namespace{platform-embedded-file-writer-mac.cc}::DirectiveAsString(), and v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Referenced by DeclareUint32().
SectionRoData()
void v8::internal::PlatformEmbeddedFileWriterMac::SectionRoData () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 32 of file platform-embedded-file-writer-mac.cc.
                                                  {
  fprintf(fp_, ".const_data\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
SectionText()
void v8::internal::PlatformEmbeddedFileWriterMac::SectionText () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 30 of file platform-embedded-file-writer-mac.cc.
{ fprintf(fp_, ".text\n"); }
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
SourceInfo()
void v8::internal::PlatformEmbeddedFileWriterMac::SourceInfo (int fileid, const char * filename, int line) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 95 of file platform-embedded-file-writer-mac.cc.
                                                         {
  fprintf(fp_, ".loc %d %d\n", fileid, line);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Member Data Documentation
target_arch_
const EmbeddedTargetArch v8::internal::PlatformEmbeddedFileWriterMac::target_arch_ [private]
Definition at line 49 of file platform-embedded-file-writer-mac.h.
Referenced by PlatformEmbeddedFileWriterMac().
target_os_
const EmbeddedTargetOs v8::internal::PlatformEmbeddedFileWriterMac::target_os_ [private]
Definition at line 50 of file platform-embedded-file-writer-mac.h.
Referenced by PlatformEmbeddedFileWriterMac().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-mac.h
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-mac.cc