v8::base::PosixMemoryMappedFile Class Reference
Public Member Functions
PosixMemoryMappedFile (FILE *file, void *memory, size_t size)
~PosixMemoryMappedFile () final
void * memory () const final
size_t size () const final
PosixMemoryMappedFile (FILE *file, void *memory, size_t size, bool ismmap)
~PosixMemoryMappedFile () final
void * memory () const final
size_t size () const final
Private Attributes
FILE *const file_
void *const memory_
size_t const size_
bool ismmap_
Additional Inherited Members
Detailed Description
Definition at line 807 of file platform-posix.cc.
Constructor & Destructor Documentation
PosixMemoryMappedFile() [1/2]
v8::base::PosixMemoryMappedFile::PosixMemoryMappedFile (FILE * file, void * memory, size_t size) [inline]
Definition at line 809 of file platform-posix.cc.
      : file_(file), memory_(memory), size_(size) {}
 PosixMemoryMappedFile() [1/2]
v8::base::PosixMemoryMappedFile::~PosixMemoryMappedFile () [final]
Definition at line 872 of file platform-posix.cc.
                                              {
  if (memory_) OS::Free(memory_, RoundUp(size_, OS::AllocatePageSize()));
  fclose(file_);
}
References v8::base::OS::AllocatePageSize(), v8::base::OS::Free(), and RoundUp().
PosixMemoryMappedFile() [2/2]
v8::base::PosixMemoryMappedFile::PosixMemoryMappedFile (FILE * file, void * memory, size_t size, bool ismmap) [inline]
Definition at line 158 of file platform-zos.cc.
      : file_(file), memory_(memory), size_(size), ismmap_(ismmap) {}
 PosixMemoryMappedFile() [2/2]
v8::base::PosixMemoryMappedFile::~PosixMemoryMappedFile () [final]
Member Function Documentation
memory() [1/2]
void* v8::base::PosixMemoryMappedFile::memory () const [inline], [final], [virtual]
Implements v8::base::OS::MemoryMappedFile.
Definition at line 812 of file platform-posix.cc.
{ return memory_; }
References memory_.
memory() [2/2]
void* v8::base::PosixMemoryMappedFile::memory () const [inline], [final], [virtual]
Implements v8::base::OS::MemoryMappedFile.
Definition at line 161 of file platform-zos.cc.
{ return memory_; }
References memory_.
size() [1/2]
size_t v8::base::PosixMemoryMappedFile::size () const [inline], [final], [virtual]
Implements v8::base::OS::MemoryMappedFile.
Definition at line 813 of file platform-posix.cc.
{ return size_; }
References size_.
size() [2/2]
size_t v8::base::PosixMemoryMappedFile::size () const [inline], [final], [virtual]
Implements v8::base::OS::MemoryMappedFile.
Definition at line 162 of file platform-zos.cc.
{ return size_; }
References size_.
Member Data Documentation
file_
FILE *const v8::base::PosixMemoryMappedFile::file_ [private]
Definition at line 816 of file platform-posix.cc.
ismmap_
bool v8::base::PosixMemoryMappedFile::ismmap_ [private]
Definition at line 168 of file platform-zos.cc.
memory_
void *const v8::base::PosixMemoryMappedFile::memory_ [private]
Definition at line 817 of file platform-posix.cc.
Referenced by memory().
size_
size_t const v8::base::PosixMemoryMappedFile::size_ [private]
Definition at line 818 of file platform-posix.cc.
Referenced by size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/platform-posix.cc
/mnt/V8SourceCode/src/base/platform/platform-zos.cc