v8::internal::wasm::ProfileGenerator Class Reference
Public Member Functions
ProfileGenerator (const WasmModule *module, const std::atomic< uint32_t > *tiering_budget_array)
base::OwnedVector< uint8_t > GetProfileData ()
Private Member Functions
void SerializeTypeFeedback (ZoneBuffer &buffer)
void SerializeTieringInfo (ZoneBuffer &buffer)
Private Attributes
const WasmModule * module_
AccountingAllocator allocator_
Zone zone_ {&allocator_, `wasm::ProfileGenerator`}
base::MutexGuard type_feedback_mutex_guard_
const std::atomic< uint32_t > *const tiering_budget_array_
Detailed Description
Definition at line 15 of file pgo.cc.
Constructor & Destructor Documentation
ProfileGenerator()
v8::internal::wasm::ProfileGenerator::ProfileGenerator (const WasmModule * module, const std::atomic< uint32_t > * tiering_budget_array) [inline]
Definition at line 17 of file pgo.cc.
      : module_(module),
        type_feedback_mutex_guard_(&module->type_feedback.mutex),
        tiering_budget_array_(tiering_budget_array) {}
Member Function Documentation
GetProfileData()
base::OwnedVector<uint8_t> v8::internal::wasm::ProfileGenerator::GetProfileData () [inline]
Definition at line 23 of file pgo.cc.
                                            {
    ZoneBuffer buffer{&zone_};
    SerializeTypeFeedback(buffer);
    SerializeTieringInfo(buffer);
    return base::OwnedCopyOf(buffer);
  }
References v8::base::OwnedCopyOf(), SerializeTieringInfo(), SerializeTypeFeedback(), and zone_.
SerializeTieringInfo()
void v8::internal::wasm::ProfileGenerator::SerializeTieringInfo (ZoneBuffer & buffer) [inline], [private]
Definition at line 72 of file pgo.cc.
                                                {
    const std::unordered_map<uint32_t, FunctionTypeFeedback>&
        feedback_for_function = module_->type_feedback.feedback_for_function;
    const uint32_t initial_budget = v8_flags.wasm_tiering_budget;
    for (uint32_t declared_index = 0;
         declared_index < module_->num_declared_functions; ++declared_index) {
      uint32_t func_index = declared_index + module_->num_imported_functions;
      auto feedback_it = feedback_for_function.find(func_index);
      int prio = feedback_it == feedback_for_function.end()
                     ? 0
                     : feedback_it->second.tierup_priority;
      DCHECK_LE(0, prio);
      uint32_t remaining_budget =
          tiering_budget_array_[declared_index].load(std::memory_order_relaxed);
      DCHECK_GE(initial_budget, remaining_budget);
      bool was_tiered_up = prio > 0;
      bool was_executed = was_tiered_up || remaining_budget != initial_budget;
      // TODO(13209): Make this less V8-specific for productionization.
      buffer.write_u8((was_executed ? kFunctionExecutedBit : 0) |
                      (was_tiered_up ? kFunctionTieredUpBit : 0));
    }
  }
References DCHECK_GE, DCHECK_LE, v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, v8::internal::wasm::kFunctionExecutedBit, v8::internal::wasm::kFunctionTieredUpBit, module_, v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::num_imported_functions, tiering_budget_array_, v8::internal::wasm::WasmModule::type_feedback, v8::internal::v8_flags, and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by GetProfileData().
SerializeTypeFeedback()
void v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback (ZoneBuffer & buffer) [inline], [private]
Definition at line 33 of file pgo.cc.
                                                 {
    const std::unordered_map<uint32_t, FunctionTypeFeedback>&
        feedback_for_function = module_->type_feedback.feedback_for_function;
    // Get an ordered list of function indexes, so we generate deterministic
    // data.
    std::vector<uint32_t> ordered_function_indexes;
    ordered_function_indexes.reserve(feedback_for_function.size());
    for (const auto& entry : feedback_for_function) {
      // Skip functions for which we have no feedback.
      if (entry.second.feedback_vector.empty()) continue;
      ordered_function_indexes.push_back(entry.first);
    }
    std::sort(ordered_function_indexes.begin(), ordered_function_indexes.end());
    buffer.write_u32v(static_cast<uint32_t>(ordered_function_indexes.size()));
    for (const uint32_t func_index : ordered_function_indexes) {
      buffer.write_u32v(func_index);
      // Serialize {feedback_vector}.
      const FunctionTypeFeedback& feedback =
          feedback_for_function.at(func_index);
      buffer.write_u32v(static_cast<uint32_t>(feedback.feedback_vector.size()));
      for (const CallSiteFeedback& call_site_feedback :
           feedback.feedback_vector) {
        int cases = call_site_feedback.num_cases();
        buffer.write_i32v(cases);
        for (int i = 0; i < cases; ++i) {
          buffer.write_i32v(call_site_feedback.function_index(i));
          buffer.write_i32v(call_site_feedback.call_count(i));
        }
      }
      // Serialize {call_targets}.
      buffer.write_u32v(static_cast<uint32_t>(feedback.call_targets.size()));
      for (uint32_t call_target : feedback.call_targets) {
        buffer.write_u32v(call_target);
      }
    }
  }
References v8::internal::wasm::CallSiteFeedback::call_count(), v8::internal::wasm::FunctionTypeFeedback::call_targets, v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, v8::internal::wasm::FunctionTypeFeedback::feedback_vector, v8::internal::wasm::CallSiteFeedback::function_index(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, module_, v8::internal::wasm::CallSiteFeedback::num_cases(), v8::base::OwnedVector< T >::size(), v8::base::sort(), v8::internal::wasm::WasmModule::type_feedback, v8::internal::wasm::ZoneBuffer::write_i32v(), and v8::internal::wasm::ZoneBuffer::write_u32v().
Referenced by GetProfileData().
Member Data Documentation
allocator_
AccountingAllocator v8::internal::wasm::ProfileGenerator::allocator_ [private]
Definition at line 99 of file pgo.cc.
module_
const WasmModule* v8::internal::wasm::ProfileGenerator::module_ [private]
Definition at line 98 of file pgo.cc.
Referenced by SerializeTieringInfo(), and SerializeTypeFeedback().
tiering_budget_array_
const std::atomic<uint32_t>* const v8::internal::wasm::ProfileGenerator::tiering_budget_array_ [private]
Definition at line 102 of file pgo.cc.
Referenced by SerializeTieringInfo().
type_feedback_mutex_guard_
base::MutexGuard v8::internal::wasm::ProfileGenerator::type_feedback_mutex_guard_ [private]
Definition at line 101 of file pgo.cc.
zone_
Zone v8::internal::wasm::ProfileGenerator::zone_ {&allocator_, `wasm::ProfileGenerator`} [private]
Definition at line 100 of file pgo.cc.
Referenced by GetProfileData().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/pgo.cc