v8::internal::compiler::AllocateParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
AllocateParameters (Type type, AllocationType allocation_type)
Type type () const
AllocationType allocation_type () const
Private Attributes
Type type_
AllocationType allocation_type_
Detailed Description
Definition at line 683 of file simplified-operator.h.
Constructor & Destructor Documentation
AllocateParameters()
v8::internal::compiler::AllocateParameters::AllocateParameters (Type type, AllocationType allocation_type) [inline]
Definition at line 685 of file simplified-operator.h.
      : type_(type), allocation_type_(allocation_type) {}
Member Function Documentation
allocation_type()
AllocationType v8::internal::compiler::AllocateParameters::allocation_type () const [inline]
Definition at line 689 of file simplified-operator.h.
{ return allocation_type_; }
Referenced by v8::internal::compiler::AllocationTypeOf(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), and v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw().
type()
Type v8::internal::compiler::AllocateParameters::type () const [inline]
Definition at line 688 of file simplified-operator.h.
{ return type_; }
Referenced by v8::internal::compiler::AllocateTypeOf(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
allocation_type_
AllocationType v8::internal::compiler::AllocateParameters::allocation_type_ [private]
Definition at line 693 of file simplified-operator.h.
type_
Type v8::internal::compiler::AllocateParameters::type_ [private]
Definition at line 692 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h