v8::internal::JSMessageObject Class Reference
#include <js-objects.h>
Public Types
using BodyDescriptor = FixedBodyDescriptor< HeapObject::kMapOffset, kPointerFieldsEndOffset, kHeaderSize >
Public Member Functions
MessageTemplate type () const
void set_type (MessageTemplate value)
int GetStartPosition () const
int GetEndPosition () const
V8_EXPORT_PRIVATE int GetLineNumber () const
V8_EXPORT_PRIVATE int GetColumnNumber () const
V8_EXPORT_PRIVATE Tagged< String > GetSource () const
DirectHandle< String > GetSourceLine () const
Static Public Member Functions
static void EnsureSourcePositionsAvailable (Isolate *isolate, DirectHandle< JSMessageObject > message)
Static Public Attributes
static const int kPointerFieldsEndOffset = kStartPositionOffset
Private Member Functions
bool DidEnsureSourcePositionsAvailable () const
Static Private Member Functions
static void V8_PRESERVE_MOST V8_EXPORT_PRIVATE InitializeSourcePositions (Isolate *isolate, DirectHandle< JSMessageObject > message)
Friends
class Factory
Detailed Description
Definition at line 1311 of file js-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::JSMessageObject::BodyDescriptor = FixedBodyDescriptor<HeapObject::kMapOffset, kPointerFieldsEndOffset, kHeaderSize>
Definition at line 1355 of file js-objects.h.
Member Function Documentation
DidEnsureSourcePositionsAvailable()
bool v8::internal::JSMessageObject::DidEnsureSourcePositionsAvailable () const [inline], [private]
Referenced by GetColumnNumber(), GetLineNumber(), and GetSourceLine().
EnsureSourcePositionsAvailable()
static void v8::internal::JSMessageObject::EnsureSourcePositionsAvailable (Isolate * isolate, DirectHandle< JSMessageObject > message) [inline], [static]
Referenced by v8::Message::GetEndColumn(), v8::Message::GetEndPosition(), v8::Message::GetLineNumber(), v8::Message::GetSourceLine(), v8::Message::GetStartColumn(), v8::Message::GetStartPosition(), v8::Message::GetWasmFunctionIndex(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), and v8::internal::Isolate::ReportPendingMessages().
GetColumnNumber()
int v8::internal::JSMessageObject::GetColumnNumber () const
Definition at line 5947 of file js-objects.cc.
                                           {
  DisallowGarbageCollection no_gc;
  DCHECK(DidEnsureSourcePositionsAvailable());
  if (start_position() == -1) return -1;
  DCHECK(script()->has_line_ends());
  DirectHandle<Script> the_script(script(), Isolate::Current());
  Script::PositionInfo info;
  if (!script()->GetPositionInfo(start_position(), &info)) {
    return -1;
  }
  return info.column; // Note: No '+1' in contrast to GetLineNumber.
}
References v8::internal::Script::PositionInfo::column, v8::internal::Isolate::Current(), v8::internal::DCHECK(), DidEnsureSourcePositionsAvailable(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
GetEndPosition()
int v8::internal::JSMessageObject::GetEndPosition () const [inline]
Definition at line 683 of file js-objects-inl.h.
                                          {
  // TODO(cbruni): make this DCHECK stricter (>= 0).
  DCHECK_LE(-1, end_position());
  return end_position();
}
References DCHECK_LE.
GetLineNumber()
int v8::internal::JSMessageObject::GetLineNumber () const
Definition at line 5933 of file js-objects.cc.
                                         {
  DisallowGarbageCollection no_gc;
  DCHECK(DidEnsureSourcePositionsAvailable());
  if (start_position() == -1) return Message::kNoLineNumberInfo;
  DCHECK(script()->has_line_ends());
  DirectHandle<Script> the_script(script(), Isolate::Current());
  Script::PositionInfo info;
  if (!script()->GetPositionInfo(start_position(), &info)) {
    return Message::kNoLineNumberInfo;
  }
  return info.line + 1;
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), DidEnsureSourcePositionsAvailable(), v8::Message::kNoLineNumberInfo, v8::internal::Script::PositionInfo::line, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
GetSource()
Tagged< String > v8::internal::JSMessageObject::GetSource () const
Definition at line 5961 of file js-objects.cc.
                                                {
  DisallowGarbageCollection no_gc;
  Tagged<Script> script_object = script();
  if (script_object->HasValidSource()) {
    Tagged<Object> source = script_object->source();
    if (IsString(source)) return Cast<String>(source);
  }
  return ReadOnlyRoots(Isolate::Current()).empty_string();
}
References v8::internal::Isolate::Current(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
GetSourceLine()
DirectHandle< String > v8::internal::JSMessageObject::GetSourceLine () const
Definition at line 5971 of file js-objects.cc.
                                                          {
  Isolate* isolate = Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (script()->type() == Script::Type::kWasm) {
    return isolate->factory()->empty_string();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  Script::PositionInfo info;
  {
    DisallowGarbageCollection no_gc;
    DCHECK(DidEnsureSourcePositionsAvailable());
    DCHECK(script()->has_line_ends());
    if (!script()->GetPositionInfo(start_position(), &info)) {
      return isolate->factory()->empty_string();
    }
  }
  Handle<String> src(Cast<String>(script()->source()), isolate);
  return isolate->factory()->NewSubString(src, info.line_start, info.line_end);
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), DidEnsureSourcePositionsAvailable(), v8::internal::Isolate::factory(), v8::internal::Script::PositionInfo::line_end, v8::internal::Script::PositionInfo::line_start, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::script, and type().
GetStartPosition()
int v8::internal::JSMessageObject::GetStartPosition () const [inline]
Definition at line 677 of file js-objects-inl.h.
                                            {
  // TODO(cbruni): make this DCHECK stricter (>= 0).
  DCHECK_LE(-1, start_position());
  return start_position();
}
References DCHECK_LE.
InitializeSourcePositions()
void v8::internal::JSMessageObject::InitializeSourcePositions (Isolate * isolate, DirectHandle< JSMessageObject > message) [static], [private]
Definition at line 5908 of file js-objects.cc.
                                                             {
  DCHECK(!message->DidEnsureSourcePositionsAvailable());
  Script::InitLineEnds(isolate, direct_handle(message->script(), isolate));
  if (message->shared_info() == Smi::FromInt(-1)) {
    message->set_shared_info(Smi::zero());
    return;
  }
  DCHECK(IsSharedFunctionInfo(message->shared_info()));
  DCHECK_GE(message->bytecode_offset().value(), kFunctionEntryBytecodeOffset);
  Handle<SharedFunctionInfo> shared_info(
      Cast<SharedFunctionInfo>(message->shared_info()), isolate);
  IsCompiledScope is_compiled_scope;
  SharedFunctionInfo::EnsureBytecodeArrayAvailable(
      isolate, shared_info, &is_compiled_scope, CreateSourcePositions::kYes);
  SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, shared_info);
  DCHECK(shared_info->HasBytecodeArray());
  int position = shared_info->abstract_code(isolate)->SourcePosition(
      isolate, message->bytecode_offset().value());
  DCHECK_GE(position, 0);
  message->set_start_position(position);
  message->set_end_position(position + 1);
  message->set_shared_info(Smi::zero());
}
References v8::internal::DCHECK(), DCHECK_GE, v8::internal::direct_handle(), v8::internal::SharedFunctionInfo::EnsureBytecodeArrayAvailable(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::Smi::FromInt(), v8::internal::Script::InitLineEnds(), v8::internal::kFunctionEntryBytecodeOffset, v8::internal::kYes, and v8::internal::Smi::zero().
set_type()
void v8::internal::JSMessageObject::set_type (MessageTemplate value) [inline]
Definition at line 693 of file js-objects-inl.h.
                                                    {
  set_raw_type(static_cast<int>(value));
}
References v8::internal::value.
type()
MessageTemplate v8::internal::JSMessageObject::type () const [inline]
Definition at line 689 of file js-objects-inl.h.
                                            {
  return MessageTemplateFromInt(raw_type());
}
References v8::internal::MessageTemplateFromInt().
Referenced by GetSourceLine().
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 1360 of file js-objects.h.
Member Data Documentation
kPointerFieldsEndOffset
const int v8::internal::JSMessageObject::kPointerFieldsEndOffset = kStartPositionOffset [static]
Definition at line 1353 of file js-objects.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-objects.h
/mnt/V8SourceCode/src/objects/js-objects-inl.h
/mnt/V8SourceCode/src/objects/js-objects.cc