v8::internal::JSLocale Class Reference
#include <js-locale.h>
Static Public Member Functions
static MaybeDirectHandle< JSLocale > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< String > locale, DirectHandle< JSReceiver > options)
static MaybeDirectHandle< JSLocale > Maximize (Isolate *isolate, DirectHandle< JSLocale > locale)
static MaybeDirectHandle< JSLocale > Minimize (Isolate *isolate, DirectHandle< JSLocale > locale)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > GetCalendars (Isolate *isolate, DirectHandle< JSLocale > locale)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > GetCollations (Isolate *isolate, DirectHandle< JSLocale > locale)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > GetHourCycles (Isolate *isolate, DirectHandle< JSLocale > locale)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > GetNumberingSystems (Isolate *isolate, DirectHandle< JSLocale > locale)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSObject > GetTextInfo (Isolate *isolate, DirectHandle< JSLocale > locale)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > GetTimeZones (Isolate *isolate, DirectHandle< JSLocale > locale)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSObject > GetWeekInfo (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > Language (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > Script (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > Region (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< String > BaseName (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > Calendar (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > CaseFirst (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > Collation (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > HourCycle (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > FirstDayOfWeek (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > Numeric (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< Object > NumberingSystem (Isolate *isolate, DirectHandle< JSLocale > locale)
static DirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSLocale > locale)
static std::string ToString (DirectHandle< JSLocale > locale)
static bool StartsWithUnicodeLanguageId (std::string_view value)
static bool Is38AlphaNumList (std::string_view value)
static bool Is3Alpha (std::string_view value)
Detailed Description
Definition at line 30 of file js-locale.h.
Member Function Documentation
BaseName()
DirectHandle< String > v8::internal::JSLocale::BaseName (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 814 of file js-locale.cc.
                                                                       {
  icu::Locale icu_locale =
      icu::Locale::createFromName(locale->icu_locale()->raw()->getBaseName());
  std::string base_name = Intl::ToLanguageTag(icu_locale).FromJust();
  return isolate->factory()->NewStringFromAsciiChecked(base_name.c_str());
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::string, and v8::internal::Intl::ToLanguageTag().
Referenced by v8::internal::BUILTIN().
Calendar()
DirectHandle< Object > v8::internal::JSLocale::Calendar (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 822 of file js-locale.cc.
                                                                       {
  return UnicodeKeywordValue(isolate, locale, "ca");
}
References v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue().
Referenced by v8::internal::BUILTIN().
CaseFirst()
DirectHandle< Object > v8::internal::JSLocale::CaseFirst (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 827 of file js-locale.cc.
                                                                        {
  return UnicodeKeywordValue(isolate, locale, "kf");
}
References v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue().
Referenced by v8::internal::BUILTIN().
Collation()
DirectHandle< Object > v8::internal::JSLocale::Collation (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 832 of file js-locale.cc.
                                                                        {
  return UnicodeKeywordValue(isolate, locale, "co");
}
References v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue().
Referenced by v8::internal::BUILTIN().
FirstDayOfWeek()
DirectHandle< Object > v8::internal::JSLocale::FirstDayOfWeek (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 837 of file js-locale.cc.
                                                                             {
  return UnicodeKeywordValue(isolate, locale, "fw");
}
References v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue().
Referenced by v8::internal::BUILTIN().
GetCalendars()
MaybeDirectHandle< JSArray > v8::internal::JSLocale::GetCalendars (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 552 of file js-locale.cc.
                                                     {
  icu::Locale icu_locale(*(locale->icu_locale()->raw()));
  return CalendarsForLocale(isolate, icu_locale, true, false);
}
References v8::internal::anonymous_namespace{js-locale.cc}::CalendarsForLocale().
Referenced by v8::internal::BUILTIN().
GetCollations()
MaybeDirectHandle< JSArray > v8::internal::JSLocale::GetCollations (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 563 of file js-locale.cc.
                                                     {
  icu::Locale icu_locale(*(locale->icu_locale()->raw()));
  return GetKeywordValuesFromLocale<icu::Collator>(
      isolate, "collations", "co", icu_locale, Intl::RemoveCollation, true,
      true);
}
References v8::internal::Intl::RemoveCollation().
Referenced by v8::internal::BUILTIN().
GetHourCycles()
MaybeDirectHandle< JSArray > v8::internal::JSLocale::GetHourCycles (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 571 of file js-locale.cc.
                                                     {
  // Let preferred be loc.[[HourCycle]].
  // Let locale be loc.[[Locale]].
  icu::Locale icu_locale(*(locale->icu_locale()->raw()));
  Factory* factory = isolate->factory();
  // Assert: locale matches the unicode_locale_id production.
  // Let list be a List of 1 or more hour cycle identifiers, which must be
  // String values indicating either the 12-hour format ("h11", "h12") or the
  // 24-hour format ("h23", "h24"), sorted in descending preference of those in
  // common use in the locale for date and time formatting.
  // Return CreateArrayFromListAndPreferred(list, preferred).
  DirectHandle<FixedArray> fixed_array = factory->NewFixedArray(1);
  UErrorCode status = U_ZERO_ERROR;
  std::string ext =
      icu_locale.getUnicodeKeywordValue<std::string>("hc", status);
  if (!ext.empty()) {
    DirectHandle<String> str = factory->NewStringFromAsciiChecked(ext.c_str());
    fixed_array->set(0, *str);
    return factory->NewJSArrayWithElements(fixed_array);
  }
  status = U_ZERO_ERROR;
  std::unique_ptr<icu::DateTimePatternGenerator> generator(
      icu::DateTimePatternGenerator::createInstance(icu_locale, status));
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  UDateFormatHourCycle hc = generator->getDefaultHourCycle(status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  DirectHandle<String> hour_cycle;
  switch (hc) {
    case UDAT_HOUR_CYCLE_11:
      hour_cycle = factory->h11_string();
      break;
    case UDAT_HOUR_CYCLE_12:
      hour_cycle = factory->h12_string();
      break;
    case UDAT_HOUR_CYCLE_23:
      hour_cycle = factory->h23_string();
      break;
    case UDAT_HOUR_CYCLE_24:
      hour_cycle = factory->h24_string();
      break;
    default:
      break;
  }
  fixed_array->set(0, *hour_cycle);
  return factory->NewJSArrayWithElements(fixed_array);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::status, v8::internal::string, and THROW_NEW_ERROR.
Referenced by v8::internal::BUILTIN().
GetNumberingSystems()
MaybeDirectHandle< JSArray > v8::internal::JSLocale::GetNumberingSystems (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 628 of file js-locale.cc.
                                                     {
  // Let preferred be loc.[[NumberingSystem]].
  // Let locale be loc.[[Locale]].
  icu::Locale icu_locale(*(locale->icu_locale()->raw()));
  Factory* factory = isolate->factory();
  // Assert: locale matches the unicode_locale_id production.
  // Let list be a List of 1 or more numbering system identifiers, which must be
  // String values conforming to the type sequence from UTS 35 Unicode Locale
  // Identifier, section 3.2, sorted in descending preference of those in common
  // use in the locale for formatting numeric values.
  // Return CreateArrayFromListAndPreferred(list, preferred).
  UErrorCode status = U_ZERO_ERROR;
  DirectHandle<FixedArray> fixed_array = factory->NewFixedArray(1);
  std::string numbering_system =
      icu_locale.getUnicodeKeywordValue<std::string>("nu", status);
  if (numbering_system.empty()) {
    numbering_system = Intl::GetNumberingSystem(icu_locale);
  }
  DirectHandle<String> str =
      factory->NewStringFromAsciiChecked(numbering_system.c_str());
  fixed_array->set(0, *str);
  return factory->NewJSArrayWithElements(fixed_array);
}
References v8::internal::Isolate::factory(), v8::internal::Intl::GetNumberingSystem(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::status, and v8::internal::string.
Referenced by v8::internal::BUILTIN().
GetTextInfo()
MaybeDirectHandle< JSObject > v8::internal::JSLocale::GetTextInfo (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 697 of file js-locale.cc.
                                                     {
  // Let loc be the this value.
  // Perform ? RequireInternalSlot(loc, [[InitializedLocale]]).
  // Let locale be loc.[[Locale]].
  // Assert: locale matches the unicode_locale_id production.
  Factory* factory = isolate->factory();
  // Let info be ! ObjectCreate(%Object.prototype%).
  DirectHandle<JSObject> info =
      factory->NewJSObject(isolate->object_function());
  // Let dir be "ltr".
  DirectHandle<String> dir = locale->icu_locale()->raw()->isRightToLeft()
                                 ? factory->rtl_string()
                                 : factory->ltr_string();
  // Perform ! CreateDataPropertyOrThrow(info, "direction", dir).
  CHECK(JSReceiver::CreateDataProperty(
            isolate, info, factory->direction_string(), dir, Just(kDontThrow))
            .FromJust());
  // Return info.
  return info;
}
References CHECK, v8::internal::JSReceiver::CreateDataProperty(), v8::internal::Isolate::factory(), v8::Just(), v8::internal::kDontThrow, and v8::internal::Factory::NewJSObject().
Referenced by v8::internal::BUILTIN().
GetTimeZones()
MaybeDirectHandle< Object > v8::internal::JSLocale::GetTimeZones (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 658 of file js-locale.cc.
                                                     {
  // Let loc be the this value.
  // Perform ? RequireInternalSlot(loc, [[InitializedLocale]])
  // Let locale be loc.[[Locale]].
  icu::Locale icu_locale(*(locale->icu_locale()->raw()));
  Factory* factory = isolate->factory();
  // If the unicode_language_id production of locale does not contain the
  // ["-" unicode_region_subtag] sequence, return undefined.
  const char* region = icu_locale.getCountry();
  if (region == nullptr || strlen(region) == 0) {
    return factory->undefined_value();
  }
  // Return TimeZonesOfLocale(loc).
  // Let locale be loc.[[Locale]].
  // Assert: locale matches the unicode_locale_id production.
  // Let region be the substring of locale corresponding to the
  // unicode_region_subtag production of the unicode_language_id.
  // Let list be a List of 1 or more time zone identifiers, which must be String
  // values indicating a Zone or Link name of the IANA Time Zone Database,
  // sorted in descending preference of those in common use in region.
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::StringEnumeration> enumeration(
      icu::TimeZone::createTimeZoneIDEnumeration(UCAL_ZONE_TYPE_CANONICAL,
                                                 region, nullptr, status));
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  return Intl::ToJSArray(isolate, nullptr, enumeration.get(), nullptr, true);
}
References v8::internal::Isolate::factory(), v8::internal::status, THROW_NEW_ERROR, and v8::internal::Intl::ToJSArray().
Referenced by v8::internal::BUILTIN().
GetWeekInfo()
MaybeDirectHandle< JSObject > v8::internal::JSLocale::GetWeekInfo (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 726 of file js-locale.cc.
                                                     {
  // Let loc be the this value.
  // Perform ? RequireInternalSlot(loc, [[InitializedLocale]]).
  // Let locale be loc.[[Locale]].
  // Assert: locale matches the unicode_locale_id production.
  Factory* factory = isolate->factory();
  // Let info be ! ObjectCreate(%Object.prototype%).
  DirectHandle<JSObject> info =
      factory->NewJSObject(isolate->object_function());
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::Calendar> calendar(
      icu::Calendar::createInstance(*(locale->icu_locale()->raw()), status));
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  // Let fd be the weekday value indicating which day of the week is considered
  // the 'first' day, for calendar purposes, in the locale.
  int32_t fd = weekdayFromEDaysOfWeek(calendar->getFirstDayOfWeek());
  // Let wi be ! WeekInfoOfLocale(loc).
  // Let we be ! CreateArrayFromList(wi.[[Weekend]]).
  Handle<FixedArray> wi = Cast<FixedArray>(factory->NewFixedArray(2));
  int32_t length = 0;
  for (int32_t i = 1; i <= 7; i++) {
    UCalendarDaysOfWeek day =
        (i == 7) ? UCAL_SUNDAY : static_cast<UCalendarDaysOfWeek>(i + 1);
    if (UCAL_WEEKDAY != calendar->getDayOfWeekType(day, status)) {
      wi->set(length++, Smi::FromInt(i));
      CHECK_LE(length, 2);
    }
  }
  if (length != 2) {
    wi = wi->RightTrimOrEmpty(isolate, wi, length);
  }
  DirectHandle<JSArray> we = factory->NewJSArrayWithElements(wi);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  // Perform ! CreateDataPropertyOrThrow(info, "firstDay", fd).
  CHECK(JSReceiver::CreateDataProperty(
            isolate, info, factory->firstDay_string(),
            factory->NewNumberFromInt(fd), Just(kDontThrow))
            .FromJust());
  // Perform ! CreateDataPropertyOrThrow(info, "weekend", we).
  CHECK(JSReceiver::CreateDataProperty(isolate, info, factory->weekend_string(),
                                       we, Just(kDontThrow))
            .FromJust());
  // Return info.
  return info;
}
References CHECK, CHECK_LE, v8::internal::JSReceiver::CreateDataProperty(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::Just(), v8::internal::kDontThrow, v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::status, THROW_NEW_ERROR, and v8::internal::anonymous_namespace{js-locale.cc}::weekdayFromEDaysOfWeek().
Referenced by v8::internal::BUILTIN().
HourCycle()
DirectHandle< Object > v8::internal::JSLocale::HourCycle (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 841 of file js-locale.cc.
                                                                        {
  return UnicodeKeywordValue(isolate, locale, "hc");
}
References v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue().
Referenced by v8::internal::BUILTIN().
Is38AlphaNumList()
bool v8::internal::JSLocale::Is38AlphaNumList (std::string_view value) [static]
Definition at line 212 of file js-locale.cc.
                                                 {
  std::string_view value = in;
  while (true) {
    std::size_t found_dash = value.find('-');
    if (found_dash == std::string::npos) {
      return IsAlphanum(value, 3, 8);
    }
    if (!IsAlphanum(value.substr(0, found_dash), 3, 8)) return false;
    value = value.substr(found_dash + 1);
  }
}
References v8::internal::anonymous_namespace{js-locale.cc}::IsAlphanum(), v8::internal::size_t, and v8::internal::value.
Referenced by v8::internal::Intl::IsWellFormedCalendar(), v8::internal::anonymous_namespace{intl-objects.cc}::IsWellFormedNumberingSystem(), and v8::internal::JSCollator::New().
Is3Alpha()
bool v8::internal::JSLocale::Is3Alpha (std::string_view value) [static]
Definition at line 224 of file js-locale.cc.
{ return IsAlpha(value, 3, 3); }
References v8::internal::anonymous_namespace{js-locale.cc}::IsAlpha(), and v8::internal::value.
Referenced by v8::internal::Intl::IsWellFormedCurrency().
Language()
DirectHandle< Object > v8::internal::JSLocale::Language (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 787 of file js-locale.cc.
                                                                       {
  Factory* factory = isolate->factory();
  const char* language = locale->icu_locale()->raw()->getLanguage();
  constexpr const char kUnd[] = "und";
  if (strlen(language) == 0) {
    language = kUnd;
  }
  return factory->NewStringFromAsciiChecked(language);
}
References v8::internal::Isolate::factory(), and v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked().
Referenced by v8::internal::BUILTIN().
Maximize()
MaybeDirectHandle< JSLocale > v8::internal::JSLocale::Maximize (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 448 of file js-locale.cc.
                                                                              {
  // ICU has limitation on the length of the locale while addLikelySubtags
  // is called. Work around the issue by only perform addLikelySubtags
  // on the base locale and merge the extension if needed.
  icu::Locale source(*(locale->icu_locale()->raw()));
  icu::Locale result = icu::Locale::createFromName(source.getBaseName());
  UErrorCode status = U_ZERO_ERROR;
  result.addLikelySubtags(status);
  if (strlen(source.getBaseName()) != strlen(result.getBaseName())) {
    // Base name is changed
    if (strlen(source.getBaseName()) != strlen(source.getName())) {
      // the source has extensions, get the extensions from the source.
      result = icu::LocaleBuilder()
                   .setLocale(source)
                   .setLanguage(result.getLanguage())
                   .setRegion(result.getCountry())
                   .setScript(result.getScript())
                   .setVariant(result.getVariant())
                   .build(status);
    }
  } else {
    // Base name is not changed
    result = source;
  }
  if (U_FAILURE(status) || result.isBogus()) {
    // Due to https://unicode-org.atlassian.net/browse/ICU-21639
    // Valid but super long locale will fail. Just throw here for now.
    THROW_NEW_ERROR(isolate,
                    NewRangeError(MessageTemplate::kLocaleBadParameters));
  }
  return Construct(isolate, result);
}
References v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::base::internal::result, v8::internal::status, and THROW_NEW_ERROR.
Referenced by v8::internal::BUILTIN().
Minimize()
MaybeDirectHandle< JSLocale > v8::internal::JSLocale::Minimize (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 482 of file js-locale.cc.
                                                                              {
  // ICU has limitation on the length of the locale while minimizeSubtags
  // is called. Work around the issue by only perform addLikelySubtags
  // on the base locale and merge the extension if needed.
  icu::Locale source(*(locale->icu_locale()->raw()));
  icu::Locale result = icu::Locale::createFromName(source.getBaseName());
  UErrorCode status = U_ZERO_ERROR;
  result.minimizeSubtags(status);
  if (strlen(source.getBaseName()) != strlen(result.getBaseName())) {
    // Base name is changed
    if (strlen(source.getBaseName()) != strlen(source.getName())) {
      // the source has extensions, get the extensions from the source.
      result = icu::LocaleBuilder()
                   .setLocale(source)
                   .setLanguage(result.getLanguage())
                   .setRegion(result.getCountry())
                   .setScript(result.getScript())
                   .setVariant(result.getVariant())
                   .build(status);
    }
  } else {
    // Base name is not changed
    result = source;
  }
  if (U_FAILURE(status) || result.isBogus()) {
    // Due to https://unicode-org.atlassian.net/browse/ICU-21639
    // Valid but super long locale will fail. Just throw here for now.
    THROW_NEW_ERROR(isolate,
                    NewRangeError(MessageTemplate::kLocaleBadParameters));
  }
  return Construct(isolate, result);
}
References v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::base::internal::result, v8::internal::status, and THROW_NEW_ERROR.
Referenced by v8::internal::BUILTIN().
New()
MaybeDirectHandle< JSLocale > v8::internal::JSLocale::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< String > locale, DirectHandle< JSReceiver > options) [static]
Definition at line 384 of file js-locale.cc.
                                                                            {
  icu::LocaleBuilder builder;
  Maybe<bool> maybe_apply =
      ApplyOptionsToTag(isolate, locale_str, options, &builder);
  MAYBE_RETURN(maybe_apply, MaybeDirectHandle<JSLocale>());
  if (!maybe_apply.FromJust()) {
    THROW_NEW_ERROR(isolate,
                    NewRangeError(MessageTemplate::kLocaleBadParameters));
  }
  Maybe<bool> maybe_insert =
      InsertOptionsIntoLocale(isolate, options, &builder);
  MAYBE_RETURN(maybe_insert, MaybeDirectHandle<JSLocale>());
  UErrorCode status = U_ZERO_ERROR;
  icu::Locale icu_locale = builder.build(status);
  icu_locale.canonicalize(status);
  if (!maybe_insert.FromJust() || U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate,
                    NewRangeError(MessageTemplate::kLocaleBadParameters));
  }
  // 31. Set locale.[[Locale]] to r.[[locale]].
  DirectHandle<Managed<icu::Locale>> managed_locale =
      Managed<icu::Locale>::From(
          isolate, 0, std::shared_ptr<icu::Locale>{icu_locale.clone()});
  // Now all properties are ready, so we can allocate the result object.
  DirectHandle<JSLocale> locale =
      Cast<JSLocale>(isolate->factory()->NewFastOrSlowJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  locale->set_icu_locale(*managed_locale);
  return locale;
}
References v8::internal::anonymous_namespace{js-locale.cc}::ApplyOptionsToTag(), v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::Maybe< T >::FromJust(), v8::internal::anonymous_namespace{js-locale.cc}::InsertOptionsIntoLocale(), MAYBE_RETURN, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::status, and THROW_NEW_ERROR.
Referenced by v8::internal::BUILTIN().
NumberingSystem()
DirectHandle< Object > v8::internal::JSLocale::NumberingSystem (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 856 of file js-locale.cc.
                                                                              {
  return UnicodeKeywordValue(isolate, locale, "nu");
}
References v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue().
Referenced by v8::internal::BUILTIN().
Numeric()
DirectHandle< Object > v8::internal::JSLocale::Numeric (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 846 of file js-locale.cc.
                                                                      {
  Factory* factory = isolate->factory();
  icu::Locale* icu_locale = locale->icu_locale()->raw();
  UErrorCode status = U_ZERO_ERROR;
  std::string numeric =
      icu_locale->getUnicodeKeywordValue<std::string>("kn", status);
  return factory->ToBoolean(numeric == "true");
}
References v8::internal::Isolate::factory(), v8::internal::status, v8::internal::string, and v8::internal::FactoryBase< Impl >::ToBoolean().
Referenced by v8::internal::BUILTIN().
Region()
DirectHandle< Object > v8::internal::JSLocale::Region (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 806 of file js-locale.cc.
                                                                     {
  Factory* factory = isolate->factory();
  const char* region = locale->icu_locale()->raw()->getCountry();
  if (strlen(region) == 0) return factory->undefined_value();
  return factory->NewStringFromAsciiChecked(region);
}
References v8::internal::Isolate::factory(), and v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked().
Referenced by v8::internal::BUILTIN().
Script()
DirectHandle< Object > v8::internal::JSLocale::Script (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 798 of file js-locale.cc.
                                                                     {
  Factory* factory = isolate->factory();
  const char* script = locale->icu_locale()->raw()->getScript();
  if (strlen(script) == 0) return factory->undefined_value();
  return factory->NewStringFromAsciiChecked(script);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::internal::script.
Referenced by v8::internal::BUILTIN().
StartsWithUnicodeLanguageId()
bool v8::internal::JSLocale::StartsWithUnicodeLanguageId (std::string_view value) [static]
Definition at line 228 of file js-locale.cc.
                                                               {
  // unicode_language_id =
  // unicode_language_subtag (sep unicode_script_subtag)?
  // (sep unicode_region_subtag)? (sep unicode_variant_subtag)* ;
  if (value.empty()) return false;
  std::vector<std::string_view> tokens;
  size_t token_start = 0;
  size_t token_end;
  for (token_end = 0; token_end < value.size(); ++token_end) {
    if (value[token_end] == '-') {
      tokens.emplace_back(&value[token_start], token_end - token_start);
      token_start = token_end + 1;
    }
  }
  if (token_start != token_end) {
    tokens.emplace_back(&value[token_start], token_end - token_start);
  }
  DCHECK(!tokens.empty());
  // length >= 1
  if (!IsUnicodeLanguageSubtag(tokens[0])) return false;
  if (tokens.size() == 1) return true;
  // length >= 2
  if (IsExtensionSingleton(tokens[1])) return true;
  size_t index = 1;
  if (IsUnicodeScriptSubtag(tokens[index])) {
    index++;
    if (index == tokens.size()) return true;
  }
  if (IsUnicodeRegionSubtag(tokens[index])) {
    index++;
  }
  while (index < tokens.size()) {
    if (IsExtensionSingleton(tokens[index])) return true;
    if (!IsUnicodeVariantSubtag(tokens[index])) return false;
    index++;
  }
  return true;
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::anonymous_namespace{js-locale.cc}::IsExtensionSingleton(), v8::internal::anonymous_namespace{js-locale.cc}::IsUnicodeLanguageSubtag(), v8::internal::anonymous_namespace{js-locale.cc}::IsUnicodeRegionSubtag(), v8::internal::anonymous_namespace{js-locale.cc}::IsUnicodeScriptSubtag(), v8::internal::anonymous_namespace{js-locale.cc}::IsUnicodeVariantSubtag(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{js-locale.cc}::ApplyOptionsToTag(), v8::internal::anonymous_namespace{intl-objects.cc}::IsStructurallyValidLanguageTag(), and v8::internal::anonymous_namespace{js-display-names.cc}::LanguageNames::of().
ToString() [1/2]
std::string v8::internal::JSLocale::ToString (DirectHandle< JSLocale > locale) [static]
Definition at line 861 of file js-locale.cc.
                                                          {
  icu::Locale* icu_locale = locale->icu_locale()->raw();
  return Intl::ToLanguageTag(*icu_locale).FromJust();
}
References v8::internal::Intl::ToLanguageTag().
ToString() [2/2]
DirectHandle< String > v8::internal::JSLocale::ToString (Isolate * isolate, DirectHandle< JSLocale > locale) [static]
Definition at line 866 of file js-locale.cc.
                                                                       {
  std::string locale_str = JSLocale::ToString(locale);
  return isolate->factory()->NewStringFromAsciiChecked(locale_str.c_str());
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::internal::string.
Referenced by v8::internal::BUILTIN(), and v8::internal::Intl::CanonicalizeLocaleList().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-locale.h
/mnt/V8SourceCode/src/objects/js-locale.cc