v8_inspector::V8InspectorImpl Class Reference
#include <v8-inspector-impl.h>
Classes
class EvaluateScope
Public Member Functions
V8_EXPORT_PRIVATE V8InspectorImpl (v8::Isolate *, V8InspectorClient *)
~V8InspectorImpl () override
V8InspectorImpl (const V8InspectorImpl &)=delete
V8InspectorImpl & operator= (const V8InspectorImpl &)=delete
v8::Isolate * isolate () const
V8InspectorClient * client ()
V8Debugger * debugger ()
PromiseHandlerTracker & promiseHandlerTracker ()
int contextGroupId (v8::Local< v8::Context >) const
int contextGroupId (int contextId) const
int resolveUniqueContextId (internal::V8DebuggerId uniqueId) const
v8::MaybeLocal< v8::Value > compileAndRunInternalScript (v8::Local< v8::Context >, v8::Local< v8::String >)
v8::MaybeLocal< v8::Script > compileScript (v8::Local< v8::Context >, const String16 &code, const String16 &fileName)
v8::MaybeLocal< v8::Context > regexContext ()
v8::MaybeLocal< v8::Context > exceptionMetaDataContext ()
std::unique_ptr< V8InspectorSession > connect (int contextGroupId, V8Inspector::Channel *, StringView state, ClientTrustLevel, SessionPauseState) override
std::shared_ptr< V8InspectorSession > connectShared (int contextGroupId, V8Inspector::Channel *, StringView state, ClientTrustLevel, SessionPauseState) override
void contextCreated (const V8ContextInfo &) override
void contextDestroyed (v8::Local< v8::Context >) override
v8::MaybeLocal< v8::Context > contextById (int contextId) override
V8DebuggerId uniqueDebuggerId (int contextId) override
uint64_t isolateId () override
void contextCollected (int contextGroupId, int contextId)
void resetContextGroup (int contextGroupId) override
void idleStarted () override
void idleFinished () override
unsigned exceptionThrown (v8::Local< v8::Context >, StringView message, v8::Local< v8::Value > exception, StringView detailedMessage, StringView url, unsigned lineNumber, unsigned columnNumber, std::unique_ptr< V8StackTrace >, int scriptId) override
void exceptionRevoked (v8::Local< v8::Context >, unsigned exceptionId, StringView message) override
std::unique_ptr< V8StackTrace > createStackTrace (v8::Local< v8::StackTrace >) override
std::unique_ptr< V8StackTrace > captureStackTrace (bool fullStack) override
void asyncTaskScheduled (StringView taskName, void *task, bool recurring) override
void asyncTaskCanceled (void *task) override
void asyncTaskStarted (void *task) override
void asyncTaskFinished (void *task) override
void allAsyncTasksCanceled () override
V8StackTraceId storeCurrentStackTrace (StringView description) override
void externalAsyncTaskStarted (const V8StackTraceId &parent) override
void externalAsyncTaskFinished (const V8StackTraceId &parent) override
V8_EXPORT_PRIVATE bool associateExceptionData (v8::Local< v8::Context >, v8::Local< v8::Value > exception, v8::Local< v8::Name > key, v8::Local< v8::Value > value) override
unsigned nextExceptionId ()
void muteExceptions (int contextGroupId)
void unmuteExceptions (int contextGroupId)
V8ConsoleMessageStorage * ensureConsoleMessageStorage (int contextGroupId)
bool hasConsoleMessageStorage (int contextGroupId)
void discardInspectedContext (int contextGroupId, int contextId)
void disconnect (V8InspectorSessionImpl *)
V8InspectorSessionImpl * sessionById (int contextGroupId, int sessionId)
InspectedContext * getContext (int groupId, int contextId) const
InspectedContext * getContext (int contextId) const
V8_EXPORT_PRIVATE V8Console * console ()
void forEachContext (int contextGroupId, const std::function< void(InspectedContext *)> &callback)
void forEachSession (int contextGroupId, const std::function< void(V8InspectorSessionImpl *)> &callback)
int64_t generateUniqueId ()
V8_EXPORT_PRIVATE v8::MaybeLocal< v8::Object > getAssociatedExceptionData (v8::Local< v8::Value > exception)
std::unique_ptr< protocol::DictionaryValue > getAssociatedExceptionDataForProtocol (v8::Local< v8::Value > exception)
Private Types
using MuteExceptionsMap = std::unordered_map< int, int >
using ContextByIdMap = std::unordered_map< int, std::unique_ptr< InspectedContext > >
using ContextsByGroupMap = std::unordered_map< int, std::unique_ptr< ContextByIdMap > >
using ConsoleStorageMap = std::unordered_map< int, std::unique_ptr< V8ConsoleMessageStorage > >
Private Member Functions
V8InspectorSessionImpl * connectImpl (int contextGroupId, V8Inspector::Channel *, StringView state, ClientTrustLevel, SessionPauseState)
Private Attributes
v8::Isolate * m_isolate
V8InspectorClient * m_client
std::unique_ptr< V8Debugger > m_debugger
v8::Global< v8::Context > m_regexContext
v8::Global< v8::Context > m_exceptionMetaDataContext
v8::Global< v8::debug::EphemeronTable > m_exceptionMetaData
unsigned m_lastExceptionId
int m_lastContextId
int m_lastSessionId = 0
MuteExceptionsMap m_muteExceptionsMap
ContextsByGroupMap m_contexts
std::unordered_map< int, std::map< int, V8InspectorSessionImpl * > > m_sessions
std::unordered_map< int, std::weak_ptr< V8DebuggerBarrier > > m_debuggerBarriers
ConsoleStorageMap m_consoleStorageMap
std::unordered_map< int, int > m_contextIdToGroupIdMap
std::map< std::pair< int64_t, int64_t >, int > m_uniqueIdToContextId
std::unique_ptr< V8Console > m_console
PromiseHandlerTracker m_promiseHandlerTracker
Additional Inherited Members
Detailed Description
Definition at line 57 of file v8-inspector-impl.h.
Member Typedef Documentation
ConsoleStorageMap
using v8_inspector::V8InspectorImpl::ConsoleStorageMap = std::unordered_map<int, std::unique_ptr<V8ConsoleMessageStorage> > [private]
Definition at line 195 of file v8-inspector-impl.h.
ContextByIdMap
using v8_inspector::V8InspectorImpl::ContextByIdMap = std::unordered_map<int, std::unique_ptr<InspectedContext> > [private]
Definition at line 184 of file v8-inspector-impl.h.
ContextsByGroupMap
using v8_inspector::V8InspectorImpl::ContextsByGroupMap = std::unordered_map<int, std::unique_ptr<ContextByIdMap> > [private]
Definition at line 186 of file v8-inspector-impl.h.
MuteExceptionsMap
using v8_inspector::V8InspectorImpl::MuteExceptionsMap = std::unordered_map<int, int> [private]
Definition at line 181 of file v8-inspector-impl.h.
Constructor & Destructor Documentation
V8InspectorImpl() [1/2]
v8_inspector::V8InspectorImpl::V8InspectorImpl (v8::Isolate * isolate, V8InspectorClient * client)
Definition at line 63 of file v8-inspector-impl.cc.
    : m_isolate(isolate),
      m_client(client),
      m_debugger(new V8Debugger(isolate, this)),
      m_lastExceptionId(0),
      m_lastContextId(0) {
  v8::debug::SetInspector(m_isolate, this);
  v8::debug::SetConsoleDelegate(m_isolate, console());
  v8::debug::SetIsolateId(m_isolate, generateUniqueId());
}
References console(), generateUniqueId(), m_isolate, v8::debug::SetConsoleDelegate(), v8::debug::SetInspector(), and v8::debug::SetIsolateId().
 V8InspectorImpl()
v8_inspector::V8InspectorImpl::~V8InspectorImpl () [override]
Definition at line 75 of file v8-inspector-impl.cc.
                                  {
  v8::debug::SetInspector(m_isolate, nullptr);
  v8::debug::SetConsoleDelegate(m_isolate, nullptr);
}
References m_isolate, v8::debug::SetConsoleDelegate(), and v8::debug::SetInspector().
V8InspectorImpl() [2/2]
v8_inspector::V8InspectorImpl::V8InspectorImpl (const V8InspectorImpl &) [delete]
Member Function Documentation
allAsyncTasksCanceled()
void v8_inspector::V8InspectorImpl::allAsyncTasksCanceled () [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 371 of file v8-inspector-impl.cc.
                                            {
  m_debugger->allAsyncTasksCanceled();
}
References m_debugger.
associateExceptionData()
bool v8_inspector::V8InspectorImpl::associateExceptionData (v8::Local< v8::Context > , v8::Local< v8::Value > exception, v8::Local< v8::Name > key, v8::Local< v8::Value > value) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 511 of file v8-inspector-impl.cc.
                                                                     {
  if (!exception->IsObject()) {
    return false;
  }
  v8::Local<v8::Context> context;
  if (!exceptionMetaDataContext().ToLocal(&context)) return false;
  v8::TryCatch tryCatch(m_isolate);
  v8::Context::Scope contextScope(context);
  v8::HandleScope handles(m_isolate);
  if (m_exceptionMetaData.IsEmpty())
    m_exceptionMetaData.Reset(m_isolate,
                              v8::debug::EphemeronTable::New(m_isolate));
  v8::Local<v8::debug::EphemeronTable> map = m_exceptionMetaData.Get(m_isolate);
  v8::MaybeLocal<v8::Value> entry = map->Get(m_isolate, exception);
  v8::Local<v8::Object> object;
  if (entry.IsEmpty() || !entry.ToLocalChecked()->IsObject()) {
    object =
        v8::Object::New(m_isolate, v8::Null(m_isolate), nullptr, nullptr, 0);
    m_exceptionMetaData.Reset(m_isolate,
                              map->Set(m_isolate, exception, object));
  } else {
    object = entry.ToLocalChecked().As<v8::Object>();
  }
  CHECK(object->IsObject());
  v8::Maybe<bool> result = object->CreateDataProperty(context, key, value);
  return result.FromMaybe(false);
}
References v8::Local< T >::As(), CHECK, exceptionMetaDataContext(), v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::MaybeLocal< T >::IsEmpty(), v8::Value::IsObject(), v8::internal::key, m_exceptionMetaData, m_isolate, v8::Object::New(), v8::debug::EphemeronTable::New(), v8::Null(), v8::PersistentBase< T >::Reset(), v8::base::internal::result, v8::MaybeLocal< T >::ToLocalChecked(), and v8::internal::value.
asyncTaskCanceled()
void v8_inspector::V8InspectorImpl::asyncTaskCanceled (void * task) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 356 of file v8-inspector-impl.cc.
                                                  {
  if (!task) return;
  m_debugger->asyncTaskCanceled(task);
}
References m_debugger.
Referenced by v8_inspector::V8Console::cancelConsoleTask().
asyncTaskFinished()
void v8_inspector::V8InspectorImpl::asyncTaskFinished (void * task) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 366 of file v8-inspector-impl.cc.
                                                  {
  if (!task) return;
  m_debugger->asyncTaskFinished(task);
}
References m_debugger.
Referenced by v8_inspector::V8Console::runTask().
asyncTaskScheduled()
void v8_inspector::V8InspectorImpl::asyncTaskScheduled (StringView taskName, void * task, bool recurring) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 350 of file v8-inspector-impl.cc.
                                                         {
  if (!task) return;
  m_debugger->asyncTaskScheduled(taskName, task, recurring);
}
References m_debugger.
Referenced by v8_inspector::V8Console::createTask().
asyncTaskStarted()
void v8_inspector::V8InspectorImpl::asyncTaskStarted (void * task) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 361 of file v8-inspector-impl.cc.
                                                 {
  if (!task) return;
  m_debugger->asyncTaskStarted(task);
}
References m_debugger.
Referenced by v8_inspector::V8Console::runTask().
captureStackTrace()
std::unique_ptr< V8StackTrace > v8_inspector::V8InspectorImpl::captureStackTrace (bool fullStack) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 333 of file v8-inspector-impl.cc.
                    {
  return m_debugger->captureStackTrace(fullStack);
}
References m_debugger.
client()
V8InspectorClient* v8_inspector::V8InspectorImpl::client () [inline]
Definition at line 65 of file v8-inspector-impl.h.
{ return m_client; }
References m_client.
Referenced by v8_inspector::V8HeapProfilerAgentImpl::addInspectedHeapObject(), v8_inspector::V8Debugger::BreakOnInstrumentation(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8Console::Clear(), v8_inspector::V8Debugger::continueProgram(), v8_inspector::V8Console::createCommandLineAPI(), v8_inspector::V8ConsoleMessage::createForConsoleAPI(), v8_inspector::V8Debugger::disable(), v8_inspector::V8RuntimeAgentImpl::disable(), v8_inspector::V8RuntimeAgentImpl::enable(), v8_inspector::V8DebuggerAgentImpl::enable(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8_inspector::V8Debugger::getCompiledScripts(), v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId(), v8_inspector::V8Debugger::handleProgramBreak(), v8_inspector::V8Console::memoryGetterCallback(), v8_inspector::V8HeapProfilerAgentImpl::onTimerImpl(), v8_inspector::V8Debugger::quitMessageLoopIfAgentsFinishedInstrumentation(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8_inspector::V8HeapProfilerAgentImpl::requestHeapStatsUpdate(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::resourceNameToUrl(), v8_inspector::V8DebuggerAgentImpl::restore(), v8_inspector::V8RuntimeAgentImpl::runIfWaitingForDebugger(), v8_inspector::V8Debugger::ScriptCompiled(), v8_inspector::V8Debugger::setAsyncCallStackDepth(), v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjectsInternal(), v8_inspector::V8HeapProfilerAgentImpl::stopTrackingHeapObjectsInternal(), v8_inspector::V8RuntimeAgentImpl::terminateExecution(), v8_inspector::V8Console::Time(), v8_inspector::V8ConsoleMessageStorage::time(), v8_inspector::V8Console::TimeEnd(), v8_inspector::V8ConsoleMessageStorage::timeEnd(), v8_inspector::V8ConsoleMessageStorage::timeLog(), v8_inspector::V8Console::TimeStamp(), and v8_inspector::InjectedScript::wrapEvaluateResult().
compileAndRunInternalScript()
v8::MaybeLocal< v8::Value > v8_inspector::V8InspectorImpl::compileAndRunInternalScript (v8::Local< v8::Context > context, v8::Local< v8::String > source)
Definition at line 95 of file v8-inspector-impl.cc.
                                                          {
  v8::Local<v8::UnboundScript> unboundScript;
  if (!v8::debug::CompileInspectorScript(m_isolate, source)
           .ToLocal(&unboundScript))
    return v8::MaybeLocal<v8::Value>();
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::Context::Scope contextScope(context);
  return unboundScript->BindToCurrentContext()->Run(context);
}
References v8::UnboundScript::BindToCurrentContext(), v8::debug::CompileInspectorScript(), v8::MicrotasksScope::kDoNotRunMicrotasks, and m_isolate.
Referenced by v8_inspector::InjectedScript::resolveCallArgument().
compileScript()
v8::MaybeLocal< v8::Script > v8_inspector::V8InspectorImpl::compileScript (v8::Local< v8::Context > context, const String16 & code, const String16 & fileName)
Definition at line 107 of file v8-inspector-impl.cc.
                              {
  v8::ScriptOrigin origin(toV8String(m_isolate, fileName), 0, 0, false);
  v8::ScriptCompiler::Source source(toV8String(m_isolate, code), origin);
  return v8::ScriptCompiler::Compile(context, &source,
                                     v8::ScriptCompiler::kNoCompileOptions);
}
References code, v8::ScriptCompiler::Compile(), v8::ScriptCompiler::kNoCompileOptions, m_isolate, and v8_inspector::toV8String().
Referenced by v8_inspector::V8RuntimeAgentImpl::compileScript().
connect()
std::unique_ptr< V8InspectorSession > v8_inspector::V8InspectorImpl::connect (int contextGroupId, V8Inspector::Channel * channel, StringView state, ClientTrustLevel client_trust_level, SessionPauseState pause_state) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 147 of file v8-inspector-impl.cc.
                                                                        {
  return std::unique_ptr<V8InspectorSession>(connectImpl(
      contextGroupId, channel, state, client_trust_level, pause_state));
}
References connectImpl(), and contextGroupId().
connectImpl()
V8InspectorSessionImpl * v8_inspector::V8InspectorImpl::connectImpl (int contextGroupId, V8Inspector::Channel * channel, StringView state, ClientTrustLevel client_trust_level, SessionPauseState pause_state) [private]
Definition at line 165 of file v8-inspector-impl.cc.
                                                                        {
  int sessionId = ++m_lastSessionId;
  std::shared_ptr<V8DebuggerBarrier> debuggerBarrier;
  if (pause_state == kWaitingForDebugger) {
    auto it = m_debuggerBarriers.find(contextGroupId);
    if (it != m_debuggerBarriers.end()) {
      // Note this will be empty in case a pre-existent barrier is already
      // released. This is by design, as a released throttle is no longer
      // efficient.
      debuggerBarrier = it->second.lock();
    } else {
      debuggerBarrier =
          std::make_shared<V8DebuggerBarrier>(m_client, contextGroupId);
      m_debuggerBarriers.insert(it, {contextGroupId, debuggerBarrier});
    }
  }
  V8InspectorSessionImpl* session = V8InspectorSessionImpl::create(
      this, contextGroupId, sessionId, channel, state, client_trust_level,
      std::move(debuggerBarrier));
  m_sessions[contextGroupId][sessionId] = session;
  return session;
}
References contextGroupId(), v8_inspector::V8InspectorSessionImpl::create(), v8_inspector::V8Inspector::kWaitingForDebugger, m_client, m_debuggerBarriers, m_lastSessionId, and m_sessions.
Referenced by connect(), and connectShared().
connectShared()
std::shared_ptr< V8InspectorSession > v8_inspector::V8InspectorImpl::connectShared (int contextGroupId, V8Inspector::Channel * channel, StringView state, ClientTrustLevel client_trust_level, SessionPauseState pause_state) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 154 of file v8-inspector-impl.cc.
                                                                        {
  std::shared_ptr<V8InspectorSessionImpl> session(connectImpl(
      contextGroupId, channel, state, client_trust_level, pause_state));
  // TODO(crbug.com/40071155): Move to V8InspectorSessionImpl::create once the
  // unique_ptr version is no longer required.
  session->setWeakThis(session);
  return session;
}
References connectImpl(), and contextGroupId().
console()
V8Console * v8_inspector::V8InspectorImpl::console ()
Definition at line 414 of file v8-inspector-impl.cc.
                                    {
  if (!m_console) m_console.reset(new V8Console(this));
  return m_console.get();
}
References m_console.
Referenced by v8_inspector::InjectedScript::commandLineAPI(), v8_inspector::InspectedContext::InspectedContext(), and V8InspectorImpl().
contextById()
v8::MaybeLocal< v8::Context > v8_inspector::V8InspectorImpl::contextById (int contextId) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 216 of file v8-inspector-impl.cc.
                                                                  {
  InspectedContext* context = getContext(contextId);
  return context ? context->context() : v8::MaybeLocal<v8::Context>();
}
References v8_inspector::InspectedContext::context(), and getContext().
Referenced by contextCreated().
contextCollected()
void v8_inspector::V8InspectorImpl::contextCollected (int contextGroupId, int contextId)
Definition at line 267 of file v8-inspector-impl.cc.
                                                                 {
  m_contextIdToGroupIdMap.erase(contextId);
  auto storageIt = m_consoleStorageMap.find(groupId);
  if (storageIt != m_consoleStorageMap.end())
    storageIt->second->contextDestroyed(contextId);
  InspectedContext* inspectedContext = getContext(groupId, contextId);
  if (!inspectedContext) return;
  forEachSession(groupId, [&inspectedContext](V8InspectorSessionImpl* session) {
    session->runtimeAgent()->reportExecutionContextDestroyed(inspectedContext);
  });
  discardInspectedContext(groupId, contextId);
}
References discardInspectedContext(), forEachSession(), getContext(), m_consoleStorageMap, m_contextIdToGroupIdMap, and v8_inspector::V8InspectorSessionImpl::runtimeAgent().
Referenced by contextDestroyed().
contextCreated()
void v8_inspector::V8InspectorImpl::contextCreated (const V8ContextInfo & info) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 233 of file v8-inspector-impl.cc.
                                                              {
  int contextId = ++m_lastContextId;
  auto* context = new InspectedContext(this, info, contextId);
  m_contextIdToGroupIdMap[contextId] = info.contextGroupId;
  DCHECK(m_uniqueIdToContextId.find(context->uniqueId().pair()) ==
         m_uniqueIdToContextId.end());
  m_uniqueIdToContextId.insert(
      std::make_pair(context->uniqueId().pair(), contextId));
  auto contextIt = m_contexts.find(info.contextGroupId);
  if (contextIt == m_contexts.end())
    contextIt = m_contexts
                    .insert(std::make_pair(
                        info.contextGroupId,
                        std::unique_ptr<ContextByIdMap>(new ContextByIdMap())))
                    .first;
  const auto& contextById = contextIt->second;
  DCHECK(contextById->find(contextId) == contextById->cend());
  (*contextById)[contextId].reset(context);
  forEachSession(
      info.contextGroupId, [&context](V8InspectorSessionImpl* session) {
        session->runtimeAgent()->addBindings(context);
        session->runtimeAgent()->reportExecutionContextCreated(context);
      });
}
References contextById(), v8_inspector::V8ContextInfo::contextGroupId, DCHECK, forEachSession(), m_contextIdToGroupIdMap, m_contexts, m_lastContextId, and m_uniqueIdToContextId.
contextDestroyed()
void v8_inspector::V8InspectorImpl::contextDestroyed (v8::Local< v8::Context > context) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 261 of file v8-inspector-impl.cc.
                                                                 {
  int contextId = InspectedContext::contextId(context);
  int groupId = contextGroupId(context);
  contextCollected(groupId, contextId);
}
References contextCollected(), contextGroupId(), and v8_inspector::InspectedContext::contextId().
contextGroupId() [1/2]
int v8_inspector::V8InspectorImpl::contextGroupId (int contextId) const
Definition at line 84 of file v8-inspector-impl.cc.
                                                       {
  auto it = m_contextIdToGroupIdMap.find(contextId);
  return it != m_contextIdToGroupIdMap.end() ? it->second : 0;
}
References m_contextIdToGroupIdMap.
contextGroupId() [2/2]
int v8_inspector::V8InspectorImpl::contextGroupId (v8::Local< v8::Context > context) const
Definition at line 80 of file v8-inspector-impl.cc.
                                                                    {
  return contextGroupId(InspectedContext::contextId(context));
}
References v8_inspector::InspectedContext::contextId().
Referenced by v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::V8Debugger::BreakOnInstrumentation(), connect(), connectImpl(), connectShared(), contextDestroyed(), v8_inspector::V8Debugger::currentContextGroupId(), v8_inspector::V8DebuggerAgentImpl::didParseSource(), discardInspectedContext(), ensureConsoleMessageStorage(), exceptionRevoked(), exceptionThrown(), forEachContext(), forEachSession(), v8_inspector::V8Debugger::getCompiledScripts(), getContext(), v8_inspector::V8Debugger::handleProgramBreak(), hasConsoleMessageStorage(), v8_inspector::V8Debugger::IsFunctionBlackboxed(), muteExceptions(), v8_inspector::V8Debugger::nearHeapLimitCallback(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), resetContextGroup(), v8_inspector::V8Debugger::ScriptCompiled(), sessionById(), v8_inspector::V8Debugger::ShouldBeSkipped(), and unmuteExceptions().
createStackTrace()
std::unique_ptr< V8StackTrace > v8_inspector::V8InspectorImpl::createStackTrace (v8::Local< v8::StackTrace > stackTrace) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 142 of file v8-inspector-impl.cc.
                                      {
  return m_debugger->createStackTrace(stackTrace);
}
References m_debugger.
debugger()
V8Debugger* v8_inspector::V8InspectorImpl::debugger () [inline]
Definition at line 66 of file v8-inspector-impl.h.
{ return m_debugger.get(); }
References m_debugger.
Referenced by v8_inspector::V8Console::Assert(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::currentDebugLocation(), v8_inspector::V8DebuggerAgentImpl::didParseSource(), v8_inspector::V8RuntimeAgentImpl::disable(), v8_inspector::V8RuntimeAgentImpl::enable(), v8_inspector::V8RuntimeAgentImpl::queryObjects(), v8_inspector::V8ConsoleMessage::reportToFrontend(), v8_inspector::V8RuntimeAgentImpl::restore(), v8_inspector::V8RuntimeAgentImpl::setMaxCallStackSizeToCapture(), v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshot(), v8_inspector::V8RuntimeAgentImpl::terminateExecution(), and v8_inspector::V8Debugger::terminateExecutionCompletedCallback().
discardInspectedContext()
void v8_inspector::V8InspectorImpl::discardInspectedContext (int contextGroupId, int contextId)
Definition at line 397 of file v8-inspector-impl.cc.
                                                             {
  auto* context = getContext(contextGroupId, contextId);
  if (!context) return;
  m_uniqueIdToContextId.erase(context->uniqueId().pair());
  m_contexts[contextGroupId]->erase(contextId);
  if (m_contexts[contextGroupId]->empty()) m_contexts.erase(contextGroupId);
}
References contextGroupId(), getContext(), m_contexts, and m_uniqueIdToContextId.
Referenced by contextCollected().
disconnect()
void v8_inspector::V8InspectorImpl::disconnect (V8InspectorSessionImpl * session)
Definition at line 190 of file v8-inspector-impl.cc.
                                                                {
  auto& map = m_sessions[session->contextGroupId()];
  map.erase(session->sessionId());
  if (map.empty()) {
    m_sessions.erase(session->contextGroupId());
    m_debuggerBarriers.erase(session->contextGroupId());
  }
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), m_debuggerBarriers, m_sessions, and v8_inspector::V8InspectorSessionImpl::sessionId().
Referenced by v8_inspector::V8InspectorSessionImpl::~V8InspectorSessionImpl().
ensureConsoleMessageStorage()
V8ConsoleMessageStorage * v8_inspector::V8InspectorImpl::ensureConsoleMessageStorage (int contextGroupId)
Definition at line 124 of file v8-inspector-impl.cc.
                        {
  auto storageIt = m_consoleStorageMap.find(contextGroupId);
  if (storageIt == m_consoleStorageMap.end())
    storageIt = m_consoleStorageMap
                    .insert(std::make_pair(
                        contextGroupId,
                        std::unique_ptr<V8ConsoleMessageStorage>(
                            new V8ConsoleMessageStorage(this, contextGroupId))))
                    .first;
  return storageIt->second.get();
}
References contextGroupId(), and m_consoleStorageMap.
Referenced by v8_inspector::V8RuntimeAgentImpl::discardConsoleEntries(), v8_inspector::V8RuntimeAgentImpl::enable(), exceptionRevoked(), exceptionThrown(), v8_inspector::V8ConsoleAgentImpl::reportAllMessages(), and v8_inspector::anonymous_namespace{custom-preview.cc}::reportError().
exceptionMetaDataContext()
v8::MaybeLocal< v8::Context > v8_inspector::V8InspectorImpl::exceptionMetaDataContext ()
Definition at line 386 of file v8-inspector-impl.cc.
                                                                  {
  if (m_exceptionMetaDataContext.IsEmpty()) {
    m_exceptionMetaDataContext.Reset(m_isolate, v8::Context::New(m_isolate));
    if (m_exceptionMetaDataContext.IsEmpty()) {
      DCHECK(m_isolate->IsExecutionTerminating());
      return {};
    }
  }
  return m_exceptionMetaDataContext.Get(m_isolate);
}
References DCHECK, v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Isolate::IsExecutionTerminating(), m_exceptionMetaDataContext, m_isolate, v8::Context::New(), and v8::PersistentBase< T >::Reset().
Referenced by associateExceptionData(), getAssociatedExceptionData(), and getAssociatedExceptionDataForProtocol().
exceptionRevoked()
void v8_inspector::V8InspectorImpl::exceptionRevoked (v8::Local< v8::Context > context, unsigned exceptionId, StringView message) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 321 of file v8-inspector-impl.cc.
                                                           {
  int groupId = contextGroupId(context);
  if (!groupId) return;
  std::unique_ptr<V8ConsoleMessage> consoleMessage =
      V8ConsoleMessage::createForRevokedException(
          m_client->currentTimeMS(), toString16(message), exceptionId);
  ensureConsoleMessageStorage(groupId)->addMessage(std::move(consoleMessage));
}
References v8_inspector::V8ConsoleMessageStorage::addMessage(), contextGroupId(), v8_inspector::V8ConsoleMessage::createForRevokedException(), v8_inspector::V8InspectorClient::currentTimeMS(), ensureConsoleMessageStorage(), m_client, and v8_inspector::toString16().
exceptionThrown()
unsigned v8_inspector::V8InspectorImpl::exceptionThrown (v8::Local< v8::Context > context, StringView message, v8::Local< v8::Value > exception, StringView detailedMessage, StringView url, unsigned lineNumber, unsigned columnNumber, std::unique_ptr< V8StackTrace > stackTrace, int scriptId) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 301 of file v8-inspector-impl.cc.
                                                          {
  int groupId = contextGroupId(context);
  if (!groupId || m_muteExceptionsMap[groupId]) return 0;
  std::unique_ptr<V8StackTraceImpl> stackTraceImpl(
      static_cast<V8StackTraceImpl*>(stackTrace.release()));
  unsigned exceptionId = nextExceptionId();
  std::unique_ptr<V8ConsoleMessage> consoleMessage =
      V8ConsoleMessage::createForException(
          m_client->currentTimeMS(), toString16(detailedMessage),
          toString16(url), lineNumber, columnNumber, std::move(stackTraceImpl),
          scriptId, m_isolate, toString16(message),
          InspectedContext::contextId(context), exception, exceptionId);
  ensureConsoleMessageStorage(groupId)->addMessage(std::move(consoleMessage));
  return exceptionId;
}
References v8_inspector::V8ConsoleMessageStorage::addMessage(), contextGroupId(), v8_inspector::InspectedContext::contextId(), v8_inspector::V8ConsoleMessage::createForException(), v8_inspector::V8InspectorClient::currentTimeMS(), ensureConsoleMessageStorage(), m_client, m_isolate, m_muteExceptionsMap, nextExceptionId(), and v8_inspector::toString16().
Referenced by v8_inspector::V8Debugger::BreakpointConditionEvaluated().
externalAsyncTaskFinished()
void v8_inspector::V8InspectorImpl::externalAsyncTaskFinished (const V8StackTraceId & parent) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 346 of file v8-inspector-impl.cc.
                                                                            {
  m_debugger->externalAsyncTaskFinished(parent);
}
References m_debugger.
externalAsyncTaskStarted()
void v8_inspector::V8InspectorImpl::externalAsyncTaskStarted (const V8StackTraceId & parent) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 342 of file v8-inspector-impl.cc.
                                                                           {
  m_debugger->externalAsyncTaskStarted(parent);
}
References m_debugger.
forEachContext()
void v8_inspector::V8InspectorImpl::forEachContext (int contextGroupId, const std::function< void(InspectedContext *)> & callback)
Definition at line 419 of file v8-inspector-impl.cc.
                                                          {
  auto it = m_contexts.find(contextGroupId);
  if (it == m_contexts.end()) return;
  std::vector<int> ids;
  ids.reserve(it->second->size());
  for (auto& contextIt : *(it->second)) ids.push_back(contextIt.first);
  // Retrieve by ids each time since |callback| may destroy some contexts.
  for (auto& contextId : ids) {
    it = m_contexts.find(contextGroupId);
    if (it == m_contexts.end()) continue;
    auto contextIt = it->second->find(contextId);
    if (contextIt != it->second->end()) callback(contextIt->second.get());
  }
}
References contextGroupId(), and m_contexts.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding(), v8_inspector::V8InspectorSessionImpl::discardInjectedScripts(), v8_inspector::V8InspectorSessionImpl::releaseObjectGroup(), v8_inspector::V8InspectorSessionImpl::reportAllContexts(), v8_inspector::V8RuntimeAgentImpl::reset(), v8_inspector::V8RuntimeAgentImpl::restore(), and v8_inspector::V8InspectorSessionImpl::setCustomObjectFormatterEnabled().
forEachSession()
void v8_inspector::V8InspectorImpl::forEachSession (int contextGroupId, const std::function< void(V8InspectorSessionImpl *)> & callback)
Definition at line 437 of file v8-inspector-impl.cc.
                                                                {
  auto it = m_sessions.find(contextGroupId);
  if (it == m_sessions.end()) return;
  std::vector<int> ids;
  ids.reserve(it->second.size());
  for (auto& sessionIt : it->second) ids.push_back(sessionIt.first);
  // Retrieve by ids each time since |callback| may destroy some contexts.
  for (auto& sessionId : ids) {
    it = m_sessions.find(contextGroupId);
    if (it == m_sessions.end()) continue;
    auto sessionIt = it->second.find(sessionId);
    if (sessionIt != it->second.end()) callback(sessionIt->second);
  }
}
References contextGroupId(), and m_sessions.
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::V8Debugger::BreakOnInstrumentation(), v8_inspector::V8Debugger::captureStackTrace(), v8_inspector::V8ConsoleMessageStorage::clear(), contextCollected(), contextCreated(), v8_inspector::V8Debugger::disable(), v8_inspector::V8Debugger::handleProgramBreak(), v8_inspector::V8Debugger::IsFunctionBlackboxed(), v8_inspector::V8Debugger::quitMessageLoopIfAgentsFinishedInstrumentation(), resetContextGroup(), v8_inspector::V8Debugger::ScriptCompiled(), and v8_inspector::V8Debugger::ShouldBeSkipped().
generateUniqueId()
int64_t v8_inspector::V8InspectorImpl::generateUniqueId ()
Definition at line 455 of file v8-inspector-impl.cc.
                                          {
  int64_t id = m_client->generateUniqueId();
  if (!id) id = v8::debug::GetNextRandomInt64(m_isolate);
  if (!id) id = 1;
  return id;
}
References v8_inspector::V8InspectorClient::generateUniqueId(), v8::debug::GetNextRandomInt64(), m_client, and m_isolate.
Referenced by v8_inspector::internal::V8DebuggerId::generate(), and V8InspectorImpl().
getAssociatedExceptionData()
v8::MaybeLocal< v8::Object > v8_inspector::V8InspectorImpl::getAssociatedExceptionData (v8::Local< v8::Value > exception)
Definition at line 543 of file v8-inspector-impl.cc.
                                {
  if (!exception->IsObject()) {
    return v8::MaybeLocal<v8::Object>();
  }
  v8::EscapableHandleScope scope(m_isolate);
  v8::Local<v8::Context> context;
  if (m_exceptionMetaData.IsEmpty() ||
      !exceptionMetaDataContext().ToLocal(&context)) {
    return v8::MaybeLocal<v8::Object>();
  }
  v8::Local<v8::debug::EphemeronTable> map = m_exceptionMetaData.Get(m_isolate);
  auto entry = map->Get(m_isolate, exception);
  v8::Local<v8::Value> object;
  if (!entry.ToLocal(&object) || !object->IsObject())
    return v8::MaybeLocal<v8::Object>();
  return scope.Escape(object.As<v8::Object>());
}
References v8::EscapableHandleScope::Escape(), exceptionMetaDataContext(), v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Value::IsObject(), m_exceptionMetaData, and m_isolate.
Referenced by getAssociatedExceptionDataForProtocol().
getAssociatedExceptionDataForProtocol()
std::unique_ptr< protocol::DictionaryValue > v8_inspector::V8InspectorImpl::getAssociatedExceptionDataForProtocol (v8::Local< v8::Value > exception)
Definition at line 563 of file v8-inspector-impl.cc.
                                {
  v8::MaybeLocal<v8::Object> maybeData = getAssociatedExceptionData(exception);
  v8::Local<v8::Object> data;
  if (!maybeData.ToLocal(&data)) return nullptr;
  v8::Local<v8::Context> context;
  if (!exceptionMetaDataContext().ToLocal(&context)) return nullptr;
  v8::TryCatch tryCatch(m_isolate);
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::Context::Scope contextScope(context);
  std::unique_ptr<protocol::DictionaryValue> jsonObject;
  objectToProtocolValue(context, data, 2, &jsonObject);
  return jsonObject;
}
References exceptionMetaDataContext(), getAssociatedExceptionData(), v8::MicrotasksScope::kDoNotRunMicrotasks, m_isolate, v8_inspector::objectToProtocolValue(), and v8::MaybeLocal< T >::ToLocal().
Referenced by v8_inspector::V8ConsoleMessage::getAssociatedExceptionData(), and v8_inspector::V8RuntimeAgentImpl::getExceptionDetails().
getContext() [1/2]
InspectedContext * v8_inspector::V8InspectorImpl::getContext (int contextId) const
Definition at line 212 of file v8-inspector-impl.cc.
                                                                 {
  return getContext(contextGroupId(contextId), contextId);
}
References contextGroupId(), and getContext().
getContext() [2/2]
InspectedContext * v8_inspector::V8InspectorImpl::getContext (int groupId, int contextId) const
Definition at line 199 of file v8-inspector-impl.cc.
                                                                   {
  if (!groupId || !contextId) return nullptr;
  auto contextGroupIt = m_contexts.find(groupId);
  if (contextGroupIt == m_contexts.end()) return nullptr;
  auto contextIt = contextGroupIt->second->find(contextId);
  if (contextIt == contextGroupIt->second->end()) return nullptr;
  return contextIt->second.get();
}
References m_contexts.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding(), v8_inspector::V8Debugger::addInternalObject(), v8_inspector::InjectedScript::bindRemoteObjectIfNeeded(), contextById(), contextCollected(), v8_inspector::V8DebuggerAgentImpl::continueToLocation(), v8_inspector::V8DebuggerAgentImpl::didParseSource(), discardInspectedContext(), v8_inspector::V8InspectorSessionImpl::findInjectedScript(), getContext(), v8_inspector::anonymous_namespace{custom-preview.cc}::getInjectedScript(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GetName(), v8_inspector::V8DebuggerAgentImpl::getPossibleBreakpoints(), v8_inspector::V8DebuggerAgentImpl::isFunctionBlackboxed(), v8_inspector::V8DebuggerAgentImpl::setBreakpointImpl(), v8_inspector::V8DebuggerAgentImpl::setScriptSource(), uniqueDebuggerId(), v8_inspector::anonymous_namespace{value-mirror.cc}::v8InternalValueTypeFrom(), v8_inspector::V8ConsoleMessage::wrapArguments(), and v8_inspector::V8ConsoleMessage::wrapException().
hasConsoleMessageStorage()
bool v8_inspector::V8InspectorImpl::hasConsoleMessageStorage (int contextGroupId)
Definition at line 137 of file v8-inspector-impl.cc.
                                                                 {
  auto storageIt = m_consoleStorageMap.find(contextGroupId);
  return storageIt != m_consoleStorageMap.end();
}
References contextGroupId(), and m_consoleStorageMap.
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage(), v8_inspector::V8ConsoleAgentImpl::reportMessage(), v8_inspector::V8RuntimeAgentImpl::reportMessage(), and v8_inspector::V8ConsoleMessage::reportToFrontend().
idleFinished()
void v8_inspector::V8InspectorImpl::idleFinished () [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 299 of file v8-inspector-impl.cc.
{ m_isolate->SetIdle(false); }
References m_isolate, and v8::Isolate::SetIdle().
idleStarted()
void v8_inspector::V8InspectorImpl::idleStarted () [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 297 of file v8-inspector-impl.cc.
{ m_isolate->SetIdle(true); }
References m_isolate, and v8::Isolate::SetIdle().
isolate()
v8::Isolate* v8_inspector::V8InspectorImpl::isolate () const [inline]
Definition at line 64 of file v8-inspector-impl.h.
{ return m_isolate; }
References m_isolate.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8_inspector::V8RuntimeAgentImpl::addBinding(), v8_inspector::V8Console::Assert(), v8_inspector::V8RuntimeAgentImpl::awaitPromise(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::V8Console::Count(), v8_inspector::V8Console::CountReset(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8_inspector::V8ConsoleMessage::getAssociatedExceptionData(), v8_inspector::V8RuntimeAgentImpl::getExceptionDetails(), v8_inspector::V8RuntimeAgentImpl::getHeapUsage(), v8_inspector::V8RuntimeAgentImpl::getProperties(), v8_inspector::V8RuntimeAgentImpl::globalLexicalScopeNames(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::InspectedContext::InspectedContext(), v8_inspector::InspectedContext::isolate(), v8_inspector::V8Regex::match(), v8_inspector::V8Console::Profile(), v8_inspector::V8Console::ProfileEnd(), v8_inspector::V8Debugger::queryObjects(), v8_inspector::V8ConsoleMessage::reportToFrontend(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::resourceNameToUrl(), v8_inspector::V8RuntimeAgentImpl::runScript(), v8_inspector::V8Console::taskInfoKey(), v8_inspector::V8Console::taskTemplate(), v8_inspector::V8RuntimeAgentImpl::terminateExecution(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8_inspector::V8Console::Time(), v8_inspector::V8Console::TimeEnd(), v8_inspector::V8Console::TimeLog(), v8_inspector::V8Console::TimeStamp(), v8_inspector::V8Regex::V8Regex(), and v8_inspector::V8InspectorSessionImpl::~V8InspectorSessionImpl().
isolateId()
uint64_t v8_inspector::V8InspectorImpl::isolateId () [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 229 of file v8-inspector-impl.cc.
                                    {
  return v8::debug::GetIsolateId(m_isolate);
}
References v8::debug::GetIsolateId(), and m_isolate.
Referenced by v8_inspector::InjectedScript::bindObject(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8_inspector::V8InspectorSessionImpl::findInjectedScript(), v8_inspector::V8RuntimeAgentImpl::getIsolateId(), and v8_inspector::InjectedScript::resolveCallArgument().
muteExceptions()
void v8_inspector::V8InspectorImpl::muteExceptions (int contextGroupId)
Definition at line 116 of file v8-inspector-impl.cc.
                                                       {
  m_muteExceptionsMap[contextGroupId]++;
}
References contextGroupId(), and m_muteExceptionsMap.
nextExceptionId()
unsigned v8_inspector::V8InspectorImpl::nextExceptionId () [inline]
Definition at line 128 of file v8-inspector-impl.h.
{ return ++m_lastExceptionId; }
References m_lastExceptionId.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::InjectedScript::createExceptionDetails(), exceptionThrown(), and v8_inspector::V8DebuggerAgentImpl::setScriptSource().
operator=()
V8InspectorImpl& v8_inspector::V8InspectorImpl::operator= (const V8InspectorImpl &) [delete]
promiseHandlerTracker()
PromiseHandlerTracker& v8_inspector::V8InspectorImpl::promiseHandlerTracker () [inline]
Definition at line 67 of file v8-inspector-impl.h.
                                                 {
    return m_promiseHandlerTracker;
  }
References m_promiseHandlerTracker.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add().
regexContext()
v8::MaybeLocal< v8::Context > v8_inspector::V8InspectorImpl::regexContext ()
Definition at line 375 of file v8-inspector-impl.cc.
                                                      {
  if (m_regexContext.IsEmpty()) {
    m_regexContext.Reset(m_isolate, v8::Context::New(m_isolate));
    if (m_regexContext.IsEmpty()) {
      DCHECK(m_isolate->IsExecutionTerminating());
      return {};
    }
  }
  return m_regexContext.Get(m_isolate);
}
References DCHECK, v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Isolate::IsExecutionTerminating(), m_isolate, m_regexContext, v8::Context::New(), and v8::PersistentBase< T >::Reset().
Referenced by v8_inspector::V8Regex::match(), and v8_inspector::V8Regex::V8Regex().
resetContextGroup()
void v8_inspector::V8InspectorImpl::resetContextGroup (int contextGroupId) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 283 of file v8-inspector-impl.cc.
                                                          {
  m_consoleStorageMap.erase(contextGroupId);
  m_muteExceptionsMap.erase(contextGroupId);
  auto contextsIt = m_contexts.find(contextGroupId);
  // Context might have been removed already by discardContextScript()
  if (contextsIt != m_contexts.end()) {
    for (const auto& map_entry : *contextsIt->second)
      m_uniqueIdToContextId.erase(map_entry.second->uniqueId().pair());
    m_contexts.erase(contextsIt);
  }
  forEachSession(contextGroupId,
                 [](V8InspectorSessionImpl* session) { session->reset(); });
}
References contextGroupId(), forEachSession(), m_consoleStorageMap, m_contexts, m_muteExceptionsMap, m_uniqueIdToContextId, and v8_inspector::V8InspectorSessionImpl::reset().
resolveUniqueContextId()
int v8_inspector::V8InspectorImpl::resolveUniqueContextId (internal::V8DebuggerId uniqueId) const
Definition at line 89 of file v8-inspector-impl.cc.
                                         {
  auto it = m_uniqueIdToContextId.find(uniqueId.pair());
  return it == m_uniqueIdToContextId.end() ? 0 : it->second;
}
References m_uniqueIdToContextId, and v8_inspector::internal::V8DebuggerId::pair().
Referenced by v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext().
sessionById()
V8InspectorSessionImpl * v8_inspector::V8InspectorImpl::sessionById (int contextGroupId, int sessionId)
Definition at line 406 of file v8-inspector-impl.cc.
                                                                    {
  auto it = m_sessions.find(contextGroupId);
  if (it == m_sessions.end()) return nullptr;
  auto it2 = it->second.find(sessionId);
  return it2 == it->second.end() ? nullptr : it2->second;
}
References contextGroupId(), m_sessions, and nullptr.
Referenced by v8_inspector::V8DebuggerAgentImpl::breakProgram(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::PromiseHandlerTracker::sendFailure(), and v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
storeCurrentStackTrace()
V8StackTraceId v8_inspector::V8InspectorImpl::storeCurrentStackTrace (StringView description) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 338 of file v8-inspector-impl.cc.
                                                                             {
  return m_debugger->storeCurrentStackTrace(description);
}
References m_debugger.
uniqueDebuggerId()
V8DebuggerId v8_inspector::V8InspectorImpl::uniqueDebuggerId (int contextId) [override], [virtual]
Implements v8_inspector::V8Inspector.
Definition at line 221 of file v8-inspector-impl.cc.
                                                            {
  InspectedContext* context = getContext(contextId);
  internal::V8DebuggerId unique_id;
  if (context) unique_id = m_debugger->debuggerIdFor(context->contextGroupId());
  return unique_id.toV8DebuggerId();
}
References v8_inspector::InspectedContext::contextGroupId(), getContext(), m_debugger, and v8_inspector::internal::V8DebuggerId::toV8DebuggerId().
unmuteExceptions()
void v8_inspector::V8InspectorImpl::unmuteExceptions (int contextGroupId)
Definition at line 120 of file v8-inspector-impl.cc.
                                                         {
  m_muteExceptionsMap[contextGroupId]--;
}
References contextGroupId(), and m_muteExceptionsMap.
Member Data Documentation
m_client
V8InspectorClient* v8_inspector::V8InspectorImpl::m_client [private]
Definition at line 172 of file v8-inspector-impl.h.
Referenced by client(), connectImpl(), exceptionRevoked(), exceptionThrown(), and generateUniqueId().
m_console
std::unique_ptr<V8Console> v8_inspector::V8InspectorImpl::m_console [private]
Definition at line 202 of file v8-inspector-impl.h.
Referenced by console().
m_consoleStorageMap
ConsoleStorageMap v8_inspector::V8InspectorImpl::m_consoleStorageMap [private]
Definition at line 197 of file v8-inspector-impl.h.
Referenced by contextCollected(), ensureConsoleMessageStorage(), hasConsoleMessageStorage(), and resetContextGroup().
m_contextIdToGroupIdMap
std::unordered_map<int, int> v8_inspector::V8InspectorImpl::m_contextIdToGroupIdMap [private]
Definition at line 199 of file v8-inspector-impl.h.
Referenced by contextCollected(), contextCreated(), and contextGroupId().
m_contexts
ContextsByGroupMap v8_inspector::V8InspectorImpl::m_contexts [private]
Definition at line 188 of file v8-inspector-impl.h.
Referenced by contextCreated(), discardInspectedContext(), forEachContext(), getContext(), and resetContextGroup().
m_debugger
std::unique_ptr<V8Debugger> v8_inspector::V8InspectorImpl::m_debugger [private]
Definition at line 173 of file v8-inspector-impl.h.
Referenced by allAsyncTasksCanceled(), asyncTaskCanceled(), asyncTaskFinished(), asyncTaskScheduled(), asyncTaskStarted(), captureStackTrace(), createStackTrace(), debugger(), externalAsyncTaskFinished(), externalAsyncTaskStarted(), storeCurrentStackTrace(), and uniqueDebuggerId().
m_debuggerBarriers
std::unordered_map<int, std::weak_ptr<V8DebuggerBarrier> > v8_inspector::V8InspectorImpl::m_debuggerBarriers [private]
Definition at line 193 of file v8-inspector-impl.h.
Referenced by connectImpl(), and disconnect().
m_exceptionMetaData
v8::Global<v8::debug::EphemeronTable> v8_inspector::V8InspectorImpl::m_exceptionMetaData [private]
Definition at line 176 of file v8-inspector-impl.h.
Referenced by associateExceptionData(), and getAssociatedExceptionData().
m_exceptionMetaDataContext
v8::Global<v8::Context> v8_inspector::V8InspectorImpl::m_exceptionMetaDataContext [private]
Definition at line 175 of file v8-inspector-impl.h.
Referenced by exceptionMetaDataContext().
m_isolate
v8::Isolate* v8_inspector::V8InspectorImpl::m_isolate [private]
Definition at line 171 of file v8-inspector-impl.h.
Referenced by associateExceptionData(), compileAndRunInternalScript(), compileScript(), exceptionMetaDataContext(), exceptionThrown(), generateUniqueId(), getAssociatedExceptionData(), getAssociatedExceptionDataForProtocol(), idleFinished(), idleStarted(), isolate(), isolateId(), regexContext(), v8_inspector::V8InspectorImpl::EvaluateScope::TerminateTask::Run(), v8_inspector::V8InspectorImpl::EvaluateScope::setTimeout(), V8InspectorImpl(), v8_inspector::V8InspectorImpl::EvaluateScope::~EvaluateScope(), and ~V8InspectorImpl().
m_lastContextId
int v8_inspector::V8InspectorImpl::m_lastContextId [private]
Definition at line 178 of file v8-inspector-impl.h.
Referenced by contextCreated().
m_lastExceptionId
unsigned v8_inspector::V8InspectorImpl::m_lastExceptionId [private]
Definition at line 177 of file v8-inspector-impl.h.
Referenced by nextExceptionId().
m_lastSessionId
int v8_inspector::V8InspectorImpl::m_lastSessionId = 0 [private]
Definition at line 179 of file v8-inspector-impl.h.
Referenced by connectImpl().
m_muteExceptionsMap
MuteExceptionsMap v8_inspector::V8InspectorImpl::m_muteExceptionsMap [private]
Definition at line 182 of file v8-inspector-impl.h.
Referenced by exceptionThrown(), muteExceptions(), resetContextGroup(), and unmuteExceptions().
m_promiseHandlerTracker
PromiseHandlerTracker v8_inspector::V8InspectorImpl::m_promiseHandlerTracker [private]
Definition at line 203 of file v8-inspector-impl.h.
Referenced by promiseHandlerTracker().
m_regexContext
v8::Global<v8::Context> v8_inspector::V8InspectorImpl::m_regexContext [private]
Definition at line 174 of file v8-inspector-impl.h.
Referenced by regexContext().
m_sessions
std::unordered_map<int, std::map<int, V8InspectorSessionImpl*> > v8_inspector::V8InspectorImpl::m_sessions [private]
Definition at line 191 of file v8-inspector-impl.h.
Referenced by connectImpl(), disconnect(), forEachSession(), and sessionById().
m_uniqueIdToContextId
std::map<std::pair<int64_t, int64_t>, int> v8_inspector::V8InspectorImpl::m_uniqueIdToContextId [private]
Definition at line 200 of file v8-inspector-impl.h.
Referenced by contextCreated(), discardInspectedContext(), resetContextGroup(), and resolveUniqueContextId().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-inspector-impl.h
/mnt/V8SourceCode/src/inspector/v8-inspector-impl.cc