v8_inspector::StackFrame Class Reference
#include <v8-stack-trace-impl.h>
Public Member Functions
StackFrame (String16 &&functionName, int scriptId, String16 &&sourceURL, int lineNumber, int columnNumber, bool hasSourceURLComment)
~StackFrame ()=default
const String16 & functionName () const
int scriptId () const
const String16 & sourceURL () const
int lineNumber () const
int columnNumber () const
std::unique_ptr< protocol::Runtime::CallFrame > buildInspectorObject (V8InspectorClient *client) const
bool isEqual (StackFrame *frame) const
Private Attributes
String16 m_functionName
int m_scriptId
String16 m_sourceURL
int m_lineNumber
int m_columnNumber
bool m_hasSourceURLComment
Detailed Description
Definition at line 28 of file v8-stack-trace-impl.h.
Constructor & Destructor Documentation
StackFrame()
v8_inspector::StackFrame::StackFrame (String16 && functionName, int scriptId, String16 && sourceURL, int lineNumber, int columnNumber, bool hasSourceURLComment)
Definition at line 158 of file v8-stack-trace-impl.cc.
    : m_functionName(std::move(functionName)),
      m_scriptId(scriptId),
      m_sourceURL(std::move(sourceURL)),
      m_lineNumber(lineNumber),
      m_columnNumber(columnNumber),
      m_hasSourceURLComment(hasSourceURLComment) {
  DCHECK_NE(v8::Message::kNoLineNumberInfo, m_lineNumber + 1);
  DCHECK_NE(v8::Message::kNoColumnInfo, m_columnNumber + 1);
}
References DCHECK_NE, v8::Message::kNoColumnInfo, v8::Message::kNoLineNumberInfo, m_columnNumber, and m_lineNumber.
 StackFrame()
v8_inspector::StackFrame::~StackFrame () [default]
Member Function Documentation
buildInspectorObject()
std::unique_ptr< protocol::Runtime::CallFrame > v8_inspector::StackFrame::buildInspectorObject (V8InspectorClient * client) const
Definition at line 181 of file v8-stack-trace-impl.cc.
                                     {
  String16 frameUrl;
  const char* dataURIPrefix = "data:";
  if (m_sourceURL.substring(0, strlen(dataURIPrefix)) != dataURIPrefix) {
    frameUrl = m_sourceURL;
  }
  if (client && !m_hasSourceURLComment && frameUrl.length() > 0) {
    std::unique_ptr<StringBuffer> url =
        client->resourceNameToUrl(toStringView(m_sourceURL));
    if (url) {
      frameUrl = toString16(url->string());
    }
  }
  return protocol::Runtime::CallFrame::create()
      .setFunctionName(m_functionName)
      .setScriptId(String16::fromInteger(m_scriptId))
      .setUrl(frameUrl)
      .setLineNumber(m_lineNumber)
      .setColumnNumber(m_columnNumber)
      .build();
}
References v8_inspector::String16::fromInteger(), v8_inspector::String16::length(), m_columnNumber, m_functionName, m_hasSourceURLComment, m_lineNumber, m_scriptId, m_sourceURL, v8_inspector::V8InspectorClient::resourceNameToUrl(), v8_inspector::String16::substring(), v8_inspector::toString16(), and v8_inspector::toStringView().
columnNumber()
int v8_inspector::StackFrame::columnNumber () const
Definition at line 179 of file v8-stack-trace-impl.cc.
{ return m_columnNumber; }
References m_columnNumber.
Referenced by v8_inspector::V8StackTraceImpl::toString().
functionName()
const String16 & v8_inspector::StackFrame::functionName () const
Definition at line 171 of file v8-stack-trace-impl.cc.
{ return m_functionName; }
References m_functionName.
Referenced by v8_inspector::V8StackTraceImpl::toString().
isEqual()
bool v8_inspector::StackFrame::isEqual (StackFrame * frame) const
Definition at line 205 of file v8-stack-trace-impl.cc.
                                                {
  return m_scriptId == frame->m_scriptId &&
         m_lineNumber == frame->m_lineNumber &&
         m_columnNumber == frame->m_columnNumber;
}
References m_columnNumber, m_lineNumber, and m_scriptId.
Referenced by v8_inspector::V8StackTraceImpl::isEqualIgnoringTopFrame().
lineNumber()
int v8_inspector::StackFrame::lineNumber () const
Definition at line 177 of file v8-stack-trace-impl.cc.
{ return m_lineNumber; }
References m_lineNumber.
Referenced by v8_inspector::V8StackTraceImpl::toString().
scriptId()
int v8_inspector::StackFrame::scriptId () const
Definition at line 173 of file v8-stack-trace-impl.cc.
{ return m_scriptId; }
References m_scriptId.
sourceURL()
const String16 & v8_inspector::StackFrame::sourceURL () const
Definition at line 175 of file v8-stack-trace-impl.cc.
{ return m_sourceURL; }
References m_sourceURL.
Referenced by v8_inspector::V8StackTraceImpl::firstNonEmptySourceURL(), and v8_inspector::V8StackTraceImpl::toString().
Member Data Documentation
m_columnNumber
int v8_inspector::StackFrame::m_columnNumber [private]
Definition at line 48 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), columnNumber(), isEqual(), and StackFrame().
m_functionName
String16 v8_inspector::StackFrame::m_functionName [private]
Definition at line 44 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), and functionName().
m_hasSourceURLComment
bool v8_inspector::StackFrame::m_hasSourceURLComment [private]
Definition at line 49 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject().
m_lineNumber
int v8_inspector::StackFrame::m_lineNumber [private]
Definition at line 47 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), isEqual(), lineNumber(), and StackFrame().
m_scriptId
int v8_inspector::StackFrame::m_scriptId [private]
Definition at line 45 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), isEqual(), and scriptId().
m_sourceURL
String16 v8_inspector::StackFrame::m_sourceURL [private]
Definition at line 46 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), and sourceURL().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.h
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.cc