v8::internal::StartupSerializer Class Reference
#include <startup-serializer.h>
Public Member Functions
StartupSerializer (Isolate *isolate, Snapshot::SerializerFlags flags, SharedHeapSerializer *shared_heap_serializer)
~StartupSerializer () override
StartupSerializer (const StartupSerializer &)=delete
StartupSerializer & operator= (const StartupSerializer &)=delete
void SerializeStrongReferences (const DisallowGarbageCollection &no_gc)
void SerializeWeakReferencesAndDeferred ()
bool SerializeUsingSharedHeapObjectCache (SnapshotByteSink *sink, Handle< HeapObject > obj)
void SerializeUsingStartupObjectCache (SnapshotByteSink *sink, Handle< HeapObject > obj)
void CheckNoDirtyFinalizationRegistries ()
Private Member Functions
void SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) override
Private Attributes
SharedHeapSerializer *const shared_heap_serializer_
GlobalHandleVector< AccessorInfo > accessor_infos_
GlobalHandleVector< FunctionTemplateInfo > function_template_infos_
Additional Inherited Members
Detailed Description
Definition at line 20 of file startup-serializer.h.
Constructor & Destructor Documentation
StartupSerializer() [1/2]
v8::internal::StartupSerializer::StartupSerializer (Isolate * isolate, Snapshot::SerializerFlags flags, SharedHeapSerializer * shared_heap_serializer)
Definition at line 63 of file startup-serializer.cc.
    : RootsSerializer(isolate, flags, RootIndex::kFirstStrongRoot),
      shared_heap_serializer_(shared_heap_serializer),
      accessor_infos_(isolate->heap()),
      function_template_infos_(isolate->heap()) {
  InitializeCodeAddressMap();
  // This serializes any external reference which don't encode to their own
  // index. This is so that the deserializer can verify that any entries that
  // were deduplicated during serialization are also deduplicated in the
  // deserializing binary.
  ExternalReferenceTable* table = isolate->external_reference_table();
  for (uint32_t i = 0; i < ExternalReferenceTable::kSizeIsolateIndependent;
       ++i) {
    ExternalReferenceEncoder::Value encoded_reference =
        EncodeExternalReference(table->address(i));
    if (encoded_reference.index() != i) {
      sink_.PutUint30(i, "expected reference index");
      sink_.PutUint30(encoded_reference.index(), "actual reference index");
    }
  }
  sink_.PutUint30(ExternalReferenceTable::kSizeIsolateIndependent,
                  "end of deduplicated reference indices");
}
References v8::internal::ExternalReferenceTable::address(), v8::internal::Serializer::EncodeExternalReference(), v8::internal::Isolate::external_reference_table(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ExternalReferenceEncoder::Value::index(), v8::internal::Serializer::InitializeCodeAddressMap(), v8::internal::Serializer::isolate(), v8::internal::kFirstStrongRoot, v8::internal::ExternalReferenceTable::kSizeIsolateIndependent, v8::internal::SnapshotByteSink::PutUint30(), and v8::internal::Serializer::sink_.
 StartupSerializer()
v8::internal::StartupSerializer::~StartupSerializer () [override]
Definition at line 90 of file startup-serializer.cc.
                                      {
  for (DirectHandle<AccessorInfo> info : accessor_infos_) {
    RestoreExternalReferenceRedirector(isolate(), *info);
  }
  for (DirectHandle<FunctionTemplateInfo> info : function_template_infos_) {
    RestoreExternalReferenceRedirector(isolate(), *info);
  }
  OutputStatistics("StartupSerializer");
}
References accessor_infos_, function_template_infos_, v8::internal::Serializer::isolate(), v8::internal::Serializer::OutputStatistics(), and v8::internal::SerializerDeserializer::RestoreExternalReferenceRedirector().
StartupSerializer() [2/2]
v8::internal::StartupSerializer::StartupSerializer (const StartupSerializer &) [delete]
Member Function Documentation
CheckNoDirtyFinalizationRegistries()
void v8::internal::StartupSerializer::CheckNoDirtyFinalizationRegistries ()
Definition at line 209 of file startup-serializer.cc.
                                                           {
  Isolate* isolate = this->isolate();
  CHECK(IsUndefined(isolate->heap()->dirty_js_finalization_registries_list(),
                    isolate));
  CHECK(IsUndefined(
      isolate->heap()->dirty_js_finalization_registries_list_tail(), isolate));
}
References CHECK, v8::internal::Heap::dirty_js_finalization_registries_list(), v8::internal::Heap::dirty_js_finalization_registries_list_tail(), v8::internal::Isolate::heap(), and v8::internal::Serializer::isolate().
Referenced by v8::internal::Snapshot::Create().
operator=()
StartupSerializer& v8::internal::StartupSerializer::operator= (const StartupSerializer &) [delete]
SerializeObjectImpl()
void v8::internal::StartupSerializer::SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) [override], [private], [virtual]
Implements v8::internal::Serializer.
Definition at line 100 of file startup-serializer.cc.
                                                                {
  PtrComprCageBase cage_base(isolate());
#ifdef DEBUG
  if (IsJSFunction(*obj, cage_base)) {
    v8::base::OS::PrintError("Reference stack:\n");
    PrintStack(std::cerr);
    Print(*obj, std::cerr);
    FATAL(
        "JSFunction should be added through the context snapshot instead of "
        "the isolate snapshot");
  }
#endif // DEBUG
  {
    DisallowGarbageCollection no_gc;
    Tagged<HeapObject> raw = *obj;
    DCHECK(!IsInstructionStream(raw));
    if (SerializeHotObject(raw)) return;
    if (IsRootAndHasBeenSerialized(raw) && SerializeRoot(raw)) return;
  }
  if (SerializeReadOnlyObjectReference(*obj, &sink_)) return;
  if (SerializeUsingSharedHeapObjectCache(&sink_, obj)) return;
  if (SerializeBackReference(*obj)) return;
  if (USE_SIMULATOR_BOOL && IsAccessorInfo(*obj, cage_base)) {
    // Wipe external reference redirects in the accessor info.
    auto info = Cast<AccessorInfo>(obj);
    info->remove_getter_redirection(isolate());
    accessor_infos_.Push(*info);
  } else if (USE_SIMULATOR_BOOL && IsFunctionTemplateInfo(*obj, cage_base)) {
    auto info = Cast<FunctionTemplateInfo>(obj);
    info->remove_callback_redirection(isolate());
    function_template_infos_.Push(*info);
  } else if (IsScript(*obj, cage_base) &&
             Cast<Script>(obj)->IsUserJavaScript()) {
    Cast<Script>(obj)->set_context_data(
        ReadOnlyRoots(isolate()).uninitialized_symbol());
  } else if (IsSharedFunctionInfo(*obj, cage_base)) {
    // Clear inferred name for native functions.
    auto shared = Cast<SharedFunctionInfo>(obj);
    if (!shared->IsSubjectToDebugging() &&
        shared->HasUncompiledData(isolate())) {
      shared->uncompiled_data(isolate())->set_inferred_name(
          ReadOnlyRoots(isolate()).empty_string());
    }
  }
  CheckRehashability(*obj);
  // Object has not yet been serialized. Serialize it here.
  DCHECK(!ReadOnlyHeap::Contains(*obj));
  ObjectSerializer object_serializer(this, obj, &sink_);
  object_serializer.Serialize(slot_type);
}
References accessor_infos_, v8::internal::Serializer::cage_base(), v8::internal::RootsSerializer::CheckRehashability(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), FATAL, function_template_infos_, v8::internal::Serializer::isolate(), v8::internal::RootsSerializer::IsRootAndHasBeenSerialized(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Print(), v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::Serializer::SerializeBackReference(), v8::internal::Serializer::SerializeHotObject(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::Serializer::SerializeRoot(), SerializeUsingSharedHeapObjectCache(), v8::internal::Serializer::sink_, and USE_SIMULATOR_BOOL.
SerializeStrongReferences()
void v8::internal::StartupSerializer::SerializeStrongReferences (const DisallowGarbageCollection & no_gc)
Definition at line 170 of file startup-serializer.cc.
                                            {
  Isolate* isolate = this->isolate();
  // No active threads.
  CHECK_NULL(isolate->thread_manager()->FirstThreadStateInUse());
  SanitizeIsolateScope sanitize_isolate(
      isolate, allow_active_isolate_for_testing(), no_gc);
  // Visit smi roots and immortal immovables first to make sure they end up in
  // the first page.
  isolate->heap()->IterateSmiRoots(this);
  isolate->heap()->IterateRoots(
      this, base::EnumSet<SkipRoot>{SkipRoot::kUnserializable, SkipRoot::kWeak,
                                    SkipRoot::kTracedHandles});
}
References v8::internal::Serializer::allow_active_isolate_for_testing(), CHECK_NULL, v8::internal::ThreadManager::FirstThreadStateInUse(), v8::internal::Isolate::heap(), v8::internal::Serializer::isolate(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateSmiRoots(), v8::internal::kTracedHandles, v8::internal::kUnserializable, v8::internal::kWeak, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Isolate::thread_manager().
Referenced by v8::internal::Snapshot::Create().
SerializeUsingSharedHeapObjectCache()
bool v8::internal::StartupSerializer::SerializeUsingSharedHeapObjectCache (SnapshotByteSink * sink, Handle< HeapObject > obj)
Definition at line 196 of file startup-serializer.cc.
                                                    {
  return shared_heap_serializer_->SerializeUsingSharedHeapObjectCache(sink,
                                                                      obj);
}
References v8::internal::SharedHeapSerializer::SerializeUsingSharedHeapObjectCache(), and shared_heap_serializer_.
Referenced by v8::internal::ContextSerializer::SerializeObjectImpl(), and SerializeObjectImpl().
SerializeUsingStartupObjectCache()
void v8::internal::StartupSerializer::SerializeUsingStartupObjectCache (SnapshotByteSink * sink, Handle< HeapObject > obj)
Definition at line 202 of file startup-serializer.cc.
                                                    {
  int cache_index = SerializeInObjectCache(obj);
  sink->Put(kStartupObjectCache, "StartupObjectCache");
  sink->PutUint30(cache_index, "startup_object_cache_index");
}
References v8::internal::SerializerDeserializer::kStartupObjectCache, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), and v8::internal::RootsSerializer::SerializeInObjectCache().
Referenced by v8::internal::ContextSerializer::SerializeObjectImpl().
SerializeWeakReferencesAndDeferred()
void v8::internal::StartupSerializer::SerializeWeakReferencesAndDeferred ()
Definition at line 156 of file startup-serializer.cc.
                                                           {
  // This comes right after serialization of the context snapshot, where we
  // add entries to the startup object cache of the startup snapshot. Add
  // one entry with 'undefined' to terminate the startup object cache.
  Tagged<Object> undefined = ReadOnlyRoots(isolate()).undefined_value();
  VisitRootPointer(Root::kStartupObjectCache, nullptr,
                   FullObjectSlot(&undefined));
  isolate()->heap()->IterateWeakRoots(
      this, base::EnumSet<SkipRoot>{SkipRoot::kUnserializable});
  SerializeDeferredObjects();
  Pad();
}
References v8::internal::Isolate::heap(), v8::internal::Serializer::isolate(), v8::internal::Heap::IterateWeakRoots(), v8::internal::kUnserializable, v8::internal::Serializer::Pad(), v8::internal::Serializer::SerializeDeferredObjects(), v8::internal::undefined, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::Snapshot::Create().
Member Data Documentation
accessor_infos_
GlobalHandleVector<AccessorInfo> v8::internal::StartupSerializer::accessor_infos_ [private]
Definition at line 56 of file startup-serializer.h.
Referenced by SerializeObjectImpl(), and ~StartupSerializer().
function_template_infos_
GlobalHandleVector<FunctionTemplateInfo> v8::internal::StartupSerializer::function_template_infos_ [private]
Definition at line 57 of file startup-serializer.h.
Referenced by SerializeObjectImpl(), and ~StartupSerializer().
shared_heap_serializer_
SharedHeapSerializer* const v8::internal::StartupSerializer::shared_heap_serializer_ [private]
Definition at line 55 of file startup-serializer.h.
Referenced by SerializeUsingSharedHeapObjectCache().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/startup-serializer.h
/mnt/V8SourceCode/src/snapshot/startup-serializer.cc