v8::base::RandomNumberGenerator Class Reference
#include <random-number-generator.h>
Public Types
using EntropySource = bool(*)(unsigned char *buffer, size_t buflen)
using result_type = unsigned
Public Member Functions
RandomNumberGenerator ()
RandomNumberGenerator (int64_t seed)
int NextInt () V8_WARN_UNUSED_RESULT
int NextInt (int max) V8_WARN_UNUSED_RESULT
bool NextBool () V8_WARN_UNUSED_RESULT
double NextDouble () V8_WARN_UNUSED_RESULT
int64_t NextInt64 () V8_WARN_UNUSED_RESULT
void NextBytes (void *buffer, size_t buflen)
std::vector< uint64_t > NextSample (uint64_t max, size_t n) V8_WARN_UNUSED_RESULT
std::vector< uint64_t > NextSampleSlow (uint64_t max, size_t n, const std::unordered_set< uint64_t > &excluded=std::unordered_set< uint64_t >{}) V8_WARN_UNUSED_RESULT
void SetSeed (int64_t seed)
int64_t initial_seed () const
result_type operator() ()
Static Public Member Functions
static void SetEntropySource (EntropySource entropy_source)
static double ToDouble (uint64_t state0)
static void XorShift128 (uint64_t *state0, uint64_t *state1)
static uint64_t MurmurHash3 (uint64_t)
static constexpr result_type min ()
static constexpr result_type max ()
Private Member Functions
int Next (int bits) V8_WARN_UNUSED_RESULT
Private Attributes
int64_t initial_seed_
uint64_t state0_
uint64_t state1_
Static Private Attributes
static const int64_t kMultiplier = 0x5'deec'e66d
static const int64_t kAddend = 0xb
static const int64_t kMask = 0xffff'ffff'ffff
Detailed Description
Definition at line 38 of file random-number-generator.h.
Member Typedef Documentation
EntropySource
using v8::base::RandomNumberGenerator::EntropySource = bool (*)(unsigned char* buffer, size_t buflen)
Definition at line 42 of file random-number-generator.h.
result_type
using v8::base::RandomNumberGenerator::result_type = unsigned
Definition at line 135 of file random-number-generator.h.
Constructor & Destructor Documentation
RandomNumberGenerator() [1/2]
v8::base::RandomNumberGenerator::RandomNumberGenerator ()
Definition at line 35 of file random-number-generator.cc.
                                             {
  // Check if embedder supplied an entropy source.
  {
    MutexGuard lock_guard(entropy_mutex.Pointer());
    if (entropy_source != nullptr) {
      int64_t seed;
      if (entropy_source(reinterpret_cast<unsigned char*>(&seed),
                         sizeof(seed))) {
        SetSeed(seed);
        return;
      }
    }
  }
#if V8_OS_CYGWIN || V8_OS_WIN
  // Use rand_s() to gather entropy on Windows. See:
  // https://code.google.com/p/v8/issues/detail?id=2905
  unsigned first_half, second_half;
  errno_t result = rand_s(&first_half);
  DCHECK_EQ(0, result);
  result = rand_s(&second_half);
  DCHECK_EQ(0, result);
  USE(result);
  SetSeed((static_cast<int64_t>(first_half) << 32) + second_half);
#elif V8_OS_DARWIN || V8_OS_FREEBSD || V8_OS_OPENBSD
  // Despite its prefix suggests it is not RC4 algorithm anymore.
  // It always succeeds while having decent performance and
  // no file descriptor involved.
  int64_t seed;
  arc4random_buf(&seed, sizeof(seed));
  SetSeed(seed);
#elif V8_OS_STARBOARD
  SetSeed(SbSystemGetRandomUInt64());
#else
  // Gather entropy from /dev/urandom if available.
  FILE* fp = base::Fopen("/dev/urandom", "rb");
  if (fp != nullptr) {
    int64_t seed;
    size_t n = fread(&seed, sizeof(seed), 1, fp);
    base::Fclose(fp);
    if (n == 1) {
      SetSeed(seed);
      return;
    }
  }
  // We cannot assume that random() or rand() were seeded
  // properly, so instead of relying on random() or rand(),
  // we just seed our PRNG using timing data as fallback.
  // This is weak entropy, but it's sufficient, because
  // it is the responsibility of the embedder to install
  // an entropy source using v8::V8::SetEntropySource(),
  // which provides reasonable entropy, see:
  // https://code.google.com/p/v8/issues/detail?id=2905
  int64_t seed = Time::NowFromSystemTime().ToInternalValue() << 24;
  seed ^= TimeTicks::Now().ToInternalValue();
  SetSeed(seed);
#endif // V8_OS_CYGWIN || V8_OS_WIN
}
References DCHECK_EQ, v8::base::entropy_mutex, v8::base::entropy_source, v8::base::Fclose(), v8::base::Fopen(), v8::base::TimeTicks::Now(), v8::base::Time::NowFromSystemTime(), v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), v8::base::internal::result, SetSeed(), v8::base::time_internal::TimeBase< TimeClass >::ToInternalValue(), and USE.
RandomNumberGenerator() [2/2]
v8::base::RandomNumberGenerator::RandomNumberGenerator (int64_t seed) [inline], [explicit]
Definition at line 46 of file random-number-generator.h.
{ SetSeed(seed); }
Member Function Documentation
initial_seed()
int64_t v8::base::RandomNumberGenerator::initial_seed () const [inline]
Definition at line 108 of file random-number-generator.h.
{ return initial_seed_; }
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::clone(), v8::internal::Isolate::fuzzer_rng(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::split().
max()
static constexpr result_type v8::base::RandomNumberGenerator::max () [inline], [static], [constexpr]
Definition at line 138 of file random-number-generator.h.
                                     {
    return std::numeric_limits<result_type>::max();
  }
Referenced by NextInt(), NextSample(), and NextSampleSlow().
min()
static constexpr result_type v8::base::RandomNumberGenerator::min () [inline], [static], [constexpr]
Definition at line 137 of file random-number-generator.h.
{ return 0; }
MurmurHash3()
uint64_t v8::base::RandomNumberGenerator::MurmurHash3 (uint64_t h) [static]
Definition at line 228 of file random-number-generator.cc.
                                                      {
  h ^= h >> 33;
  h *= uint64_t{0xFF51AFD7ED558CCD};
  h ^= h >> 33;
  h *= uint64_t{0xC4CEB9FE1A85EC53};
  h ^= h >> 33;
  return h;
}
References h().
Referenced by v8::internal::MathRandom::RefillCache(), and SetSeed().
Next()
int v8::base::RandomNumberGenerator::Next (int bits) [private]
Definition at line 212 of file random-number-generator.cc.
                                        {
  DCHECK_LT(0, bits);
  DCHECK_GE(32, bits);
  XorShift128(&state0_, &state1_);
  return static_cast<int>((state0_ + state1_) >> (64 - bits));
}
References DCHECK_GE, DCHECK_LT, state0_, state1_, and XorShift128().
Referenced by NextBytes(), and NextInt().
NextBool()
bool v8::base::RandomNumberGenerator::NextBool () [inline]
Definition at line 68 of file random-number-generator.h.
{ return Next(1) != 0; }
References v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next().
NextBytes()
void v8::base::RandomNumberGenerator::NextBytes (void * buffer, size_t buflen)
Definition at line 126 of file random-number-generator.cc.
                                                                 {
  for (size_t n = 0; n < buflen; ++n) {
    static_cast<uint8_t*>(buffer)[n] = static_cast<uint8_t>(Next(8));
  }
}
References Next().
Referenced by v8::base::RegionAllocator::AllocateRegion(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), and v8::internal::MathRandom::RefillCache().
NextDouble()
double v8::base::RandomNumberGenerator::NextDouble ()
Definition at line 114 of file random-number-generator.cc.
                                         {
  XorShift128(&state0_, &state1_);
  return ToDouble(state0_);
}
References state0_, state1_, ToDouble(), and XorShift128().
Referenced by v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::SamplingHeapProfiler::Observer::GetNextSampleInterval(), v8::DelayedTasksPlatform::GetRandomDelayInMilliseconds(), NextSample(), and NextSampleSlow().
NextInt() [1/2]
int v8::base::RandomNumberGenerator::NextInt () [inline]
Definition at line 53 of file random-number-generator.h.
{ return Next(32); }
References v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next().
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBytecode(), v8::internal::Isolate::GenerateIdentityHash(), v8::internal::MemoryMeasurement::NextGCTaskDelayInSeconds(), v8::internal::StressScavengeObserver::NextLimit(), and v8::internal::Heap::NextStressMarkingLimit().
NextInt() [2/2]
int v8::base::RandomNumberGenerator::NextInt (int max)
Definition at line 96 of file random-number-generator.cc.
                                          {
  DCHECK_LT(0, max);
  // Fast path if max is a power of 2.
  if (bits::IsPowerOfTwo(max)) {
    return static_cast<int>((max * static_cast<int64_t>(Next(31))) >> 31);
  }
  while (true) {
    int rnd = Next(31);
    int val = rnd % max;
    if (std::numeric_limits<int>::max() - (rnd - val) >= (max - 1)) {
      return val;
    }
  }
}
References DCHECK_LT, v8::base::bits::IsPowerOfTwo(), max(), and Next().
NextInt64()
int64_t v8::base::RandomNumberGenerator::NextInt64 ()
Definition at line 120 of file random-number-generator.cc.
                                         {
  XorShift128(&state0_, &state1_);
  return base::bit_cast<int64_t>(state0_ + state1_);
}
References state0_, state1_, and XorShift128().
Referenced by v8::internal::EvacuateVisitorBase::EvacuateVisitorBase(), v8::internal::Heap::InitializeHashSeed(), v8::base::EmulatedVirtualAddressSubspace::RandomPageAddress(), v8::base::VirtualAddressSubspace::RandomPageAddress(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::split().
NextSample()
std::vector< uint64_t > v8::base::RandomNumberGenerator::NextSample (uint64_t max, size_t n)
Definition at line 144 of file random-number-generator.cc.
                                                                  {
  CHECK_LE(n, max);
  if (n == 0) {
    return std::vector<uint64_t>();
  }
  // Choose to select or exclude, whatever needs fewer generator calls.
  size_t smaller_part = static_cast<size_t>(
      std::min(max - static_cast<uint64_t>(n), static_cast<uint64_t>(n)));
  std::unordered_set<uint64_t> selected;
  size_t counter = 0;
  while (selected.size() != smaller_part && counter / 3 < smaller_part) {
    uint64_t x = static_cast<uint64_t>(NextDouble() * max);
    CHECK_LT(x, max);
    selected.insert(x);
    counter++;
  }
  if (selected.size() == smaller_part) {
    if (smaller_part != n) {
      return ComplementSample(selected, max);
    }
    return std::vector<uint64_t>(selected.begin(), selected.end());
  }
  // Failed to select numbers in smaller_part * 3 steps, try different approach.
  return NextSampleSlow(max, n, selected);
}
References CHECK_LE, CHECK_LT, v8::base::ComplementSample(), max(), NextDouble(), and NextSampleSlow().
Referenced by v8::internal::MarkCompactCollector::CollectEvacuationCandidates().
NextSampleSlow()
std::vector< uint64_t > v8::base::RandomNumberGenerator::NextSampleSlow (uint64_t max, size_t n, const std::unordered_set< uint64_t > & excluded = std::unordered_set<uint64_t>{})
Definition at line 177 of file random-number-generator.cc.
                                                                        {
  CHECK_GE(max - excluded.size(), n);
  std::vector<uint64_t> result;
  result.reserve(max - excluded.size());
  for (uint64_t i = 0; i < max; i++) {
    if (!excluded.count(i)) {
      result.push_back(i);
    }
  }
  // Decrease result vector until it contains values to select or exclude,
  // whatever needs fewer generator calls.
  size_t larger_part = static_cast<size_t>(
      std::max(max - static_cast<uint64_t>(n), static_cast<uint64_t>(n)));
  // Excluded set may cause that initial result is already smaller than
  // larget_part.
  while (result.size() != larger_part && result.size() > n) {
    size_t x = static_cast<size_t>(NextDouble() * result.size());
    CHECK_LT(x, result.size());
    std::swap(result[x], result.back());
    result.pop_back();
  }
  if (result.size() != n) {
    return ComplementSample(
        std::unordered_set<uint64_t>(result.begin(), result.end()), max);
  }
  return result;
}
References CHECK_GE, CHECK_LT, v8::base::ComplementSample(), max(), NextDouble(), and v8::base::internal::result.
Referenced by NextSample().
operator()()
result_type v8::base::RandomNumberGenerator::operator() () [inline]
Definition at line 136 of file random-number-generator.h.
{ return NextInt(); }
SetEntropySource()
void v8::base::RandomNumberGenerator::SetEntropySource (EntropySource entropy_source) [static]
Definition at line 29 of file random-number-generator.cc.
                                                                 {
  MutexGuard lock_guard(entropy_mutex.Pointer());
  entropy_source = source;
}
References v8::base::entropy_mutex, v8::base::entropy_source, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by v8::V8::SetEntropySource().
SetSeed()
void v8::base::RandomNumberGenerator::SetSeed (int64_t seed)
Definition at line 220 of file random-number-generator.cc.
                                                {
  initial_seed_ = seed;
  state0_ = MurmurHash3(base::bit_cast<uint64_t>(seed));
  state1_ = MurmurHash3(~state0_);
  CHECK(state0_ != 0 || state1_ != 0);
}
References CHECK, initial_seed_, MurmurHash3(), state0_, and state1_.
Referenced by v8::internal::MemoryMeasurement::MemoryMeasurement(), RandomNumberGenerator(), v8::base::EmulatedVirtualAddressSubspace::SetRandomSeed(), and v8::base::VirtualAddressSubspace::SetRandomSeed().
ToDouble()
static double v8::base::RandomNumberGenerator::ToDouble (uint64_t state0) [inline], [static]
Definition at line 111 of file random-number-generator.h.
                                                 {
    // Get a random [0,2**53) integer value (up to MAX_SAFE_INTEGER) by dropping
    // 11 bits of the state.
    double random_0_to_2_53 = static_cast<double>(state0 >> 11);
    // Map this to [0,1) by division with 2**53.
    constexpr double k2_53{static_cast<uint64_t>(1) << 53};
    return random_0_to_2_53 / k2_53;
  }
Referenced by NextDouble(), and v8::internal::MathRandom::RefillCache().
XorShift128()
static void v8::base::RandomNumberGenerator::XorShift128 (uint64_t * state0, uint64_t * state1) [inline], [static]
Definition at line 121 of file random-number-generator.h.
                                                                     {
    uint64_t s1 = *state0;
    uint64_t s0 = *state1;
    *state0 = s0;
    s1 ^= s1 << 23;
    s1 ^= s1 >> 17;
    s1 ^= s0;
    s1 ^= s0 >> 26;
    *state1 = s1;
  }
Referenced by Next(), NextDouble(), NextInt64(), and v8::internal::MathRandom::RefillCache().
Member Data Documentation
initial_seed_
int64_t v8::base::RandomNumberGenerator::initial_seed_ [private]
Definition at line 149 of file random-number-generator.h.
Referenced by SetSeed().
kAddend
const int64_t v8::base::RandomNumberGenerator::kAddend = 0xb [static], [private]
Definition at line 144 of file random-number-generator.h.
kMask
const int64_t v8::base::RandomNumberGenerator::kMask = 0xffff'ffff'ffff [static], [private]
Definition at line 145 of file random-number-generator.h.
kMultiplier
const int64_t v8::base::RandomNumberGenerator::kMultiplier = 0x5'deec'e66d [static], [private]
Definition at line 143 of file random-number-generator.h.
state0_
uint64_t v8::base::RandomNumberGenerator::state0_ [private]
Definition at line 150 of file random-number-generator.h.
Referenced by Next(), NextDouble(), NextInt64(), and SetSeed().
state1_
uint64_t v8::base::RandomNumberGenerator::state1_ [private]
Definition at line 151 of file random-number-generator.h.
Referenced by Next(), NextDouble(), NextInt64(), and SetSeed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/utils/random-number-generator.h
/mnt/V8SourceCode/src/base/utils/random-number-generator.cc