v8::internal::ExitFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
void Iterate (RootVisitor *v) const override
Static Public Member Functions
static ExitFrame * cast (StackFrame *frame)
static Type GetStateForFramePointer (Address fp, State *state)
static Address ComputeStackPointer (Address fp)
static StackFrame::Type ComputeFrameType (Address fp)
static void FillState (Address fp, Address sp, State *state)
Protected Member Functions
ExitFrame (StackFrameIteratorBase *iterator)
Private Member Functions
void ComputeCallerState (State *state) const override
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 898 of file frames.h.
Constructor & Destructor Documentation
ExitFrame()
v8::internal::ExitFrame::ExitFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 137 of file frames-inl.h.
    : TypedFrame(iterator) {}
Member Function Documentation
cast()
static ExitFrame* v8::internal::ExitFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 905 of file frames.h.
                                            {
    DCHECK(frame->is_exit());
    return static_cast<ExitFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_exit().
ComputeCallerState()
void v8::internal::ExitFrame::ComputeCallerState (State * state) const [override], [private], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 1133 of file frames.cc.
                                                     {
  // Set up the caller state.
  state->sp = caller_sp();
  state->fp = Memory<Address>(fp() + ExitFrameConstants::kCallerFPOffset);
  state->pc_address = ResolveReturnAddressLocation(
      reinterpret_cast<Address*>(fp() + ExitFrameConstants::kCallerPCOffset));
  state->callee_pc = kNullAddress;
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    state->constant_pool_address = reinterpret_cast<Address*>(
        fp() + ExitFrameConstants::kConstantPoolOffset);
  }
}
References v8::internal::StackFrame::State::callee_pc, v8::internal::StackFrame::caller_sp(), v8::internal::StackFrame::State::constant_pool_address, v8::internal::StackFrame::State::fp, v8::internal::StackFrame::fp(), v8::internal::CommonFrameConstants::kCallerFPOffset, v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::CommonFrameConstants::kConstantPoolOffset, v8::internal::kNullAddress, v8::internal::StackFrame::State::pc_address, v8::internal::StackFrame::ResolveReturnAddressLocation(), v8::internal::StackFrame::State::sp, and V8_EMBEDDED_CONSTANT_POOL_BOOL.
ComputeFrameType()
StackFrame::Type v8::internal::ExitFrame::ComputeFrameType (Address fp) [static]
Definition at line 1166 of file frames.cc.
                                                     {
  // Distinguish between different exit frame types.
  // Default to EXIT in all hairy cases (e.g., when called from profiler).
  const int offset = ExitFrameConstants::kFrameTypeOffset;
  Tagged<Object> marker(Memory<Address>(fp + offset));
  if (!IsSmi(marker)) {
    return EXIT;
  }
  intptr_t marker_int = base::bit_cast<intptr_t>(marker);
  StackFrame::Type frame_type = static_cast<StackFrame::Type>(marker_int >> 1);
  switch (frame_type) {
    case BUILTIN_EXIT:
    case API_ACCESSOR_EXIT:
    case API_CALLBACK_EXIT:
#if V8_ENABLE_WEBASSEMBLY
    case WASM_EXIT:
    case STACK_SWITCH:
#endif // V8_ENABLE_WEBASSEMBLY
      return frame_type;
    default:
      return EXIT;
  }
}
References v8::internal::StackFrame::fp(), v8::internal::IsSmi(), and v8::internal::TypedFrameConstants::kFrameTypeOffset.
Referenced by GetStateForFramePointer().
ComputeStackPointer()
Address v8::internal::ExitFrame::ComputeStackPointer (Address fp) [static]
Definition at line 1193 of file frames.cc.
                                                 {
  MSAN_MEMORY_IS_INITIALIZED(fp + ExitFrameConstants::kSPOffset,
                             kSystemPointerSize);
  return Memory<Address>(fp + ExitFrameConstants::kSPOffset);
}
References v8::internal::StackFrame::fp(), v8::internal::ExitFrameConstants::kSPOffset, v8::internal::kSystemPointerSize, and MSAN_MEMORY_IS_INITIALIZED.
Referenced by GetStateForFramePointer(), and v8::internal::StackFrameIteratorForProfiler::IsValidExitFrame().
FillState()
void v8::internal::ExitFrame::FillState (Address fp, Address sp, State * state) [static]
Definition at line 1210 of file frames.cc.
                                                              {
  state->sp = sp;
  state->fp = fp;
  state->pc_address = ResolveReturnAddressLocation(
      reinterpret_cast<Address*>(sp - 1 * kPCOnStackSize));
  state->callee_pc = kNullAddress;
  // The constant pool recorded in the exit frame is not associated
  // with the pc in this state (the return address into a C entry
  // stub). ComputeCallerState will retrieve the constant pool
  // together with the associated caller pc.
  state->constant_pool_address = nullptr;
}
References v8::internal::StackFrame::State::callee_pc, v8::internal::StackFrame::State::constant_pool_address, v8::internal::StackFrame::State::fp, v8::internal::StackFrame::fp(), v8::internal::kNullAddress, v8::internal::kPCOnStackSize, v8::internal::StackFrame::State::pc_address, v8::internal::StackFrame::ResolveReturnAddressLocation(), v8::internal::StackFrame::State::sp, and v8::internal::StackFrame::sp().
Referenced by GetStateForFramePointer(), and v8::internal::StackFrameIteratorForProfiler::IsValidExitFrame().
GetStateForFramePointer()
StackFrame::Type v8::internal::ExitFrame::GetStateForFramePointer (Address fp, State * state) [static]
Definition at line 1152 of file frames.cc.
                                                                          {
  if (fp == 0) return NO_FRAME_TYPE;
  StackFrame::Type type = ComputeFrameType(fp);
#if V8_ENABLE_WEBASSEMBLY
  Address sp = type == WASM_EXIT ? WasmExitFrame::ComputeStackPointer(fp)
                                 : ExitFrame::ComputeStackPointer(fp);
#else
  Address sp = ExitFrame::ComputeStackPointer(fp);
#endif // V8_ENABLE_WEBASSEMBLY
  FillState(fp, sp, state);
  DCHECK_NE(*state->pc_address, kNullAddress);
  return type;
}
References ComputeFrameType(), ComputeStackPointer(), DCHECK_NE, FillState(), v8::internal::StackFrame::fp(), v8::internal::kNullAddress, v8::internal::StackFrame::NO_FRAME_TYPE, v8::internal::StackFrame::State::pc_address, v8::internal::StackFrame::sp(), and type().
Referenced by v8::internal::EntryFrame::GetCallerState(), v8::internal::StackFrameIterator::Reset(), and v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler().
Iterate()
void v8::internal::ExitFrame::Iterate (RootVisitor * v) const [override], [virtual]
Reimplemented from v8::internal::TypedFrame.
Definition at line 1146 of file frames.cc.
                                            {
  // The arguments are traversed as part of the expression stack of
  // the calling frame.
  IteratePc(v, constant_pool_address(), GcSafeLookupCode());
}
References v8::internal::StackFrame::constant_pool_address(), v8::internal::StackFrame::GcSafeLookupCode(), and v8::internal::StackFrame::IteratePc().
type()
Type v8::internal::ExitFrame::type () const [inline], [override], [virtual]
Implements v8::internal::StackFrame.
Reimplemented in v8::internal::ApiAccessorExitFrame, v8::internal::ApiCallbackExitFrame, and v8::internal::BuiltinExitFrame.
Definition at line 900 of file frames.h.
{ return EXIT; }
Referenced by GetStateForFramePointer().
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 924 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc