v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next > Class Template Reference
#include <store-store-elimination-reducer-inl.h>
Public Member Functions
void Analyze ()
OpIndex REDUCE_INPUT_GRAPH() Store (OpIndex ig_index, const StoreOp &store)
Private Attributes
RedundantStoreAnalysis analysis_ {Asm().input_graph(), Asm().phase_zone()}
ZoneSet< OpIndex > eliminable_stores_ {Asm().phase_zone()}
ZoneMap< OpIndex, uint64_t > mergeable_store_pairs_ {Asm().phase_zone()}
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >
Definition at line 454 of file store-store-elimination-reducer-inl.h.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Analyze () [inline]
Definition at line 458 of file store-store-elimination-reducer-inl.h.
                 {
    analysis_.Run(eliminable_stores_, mergeable_store_pairs_);
    Next::Analyze();
  }
References v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::analysis_, v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::eliminable_stores_, v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::mergeable_store_pairs_, and v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run().
Store()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Store (OpIndex ig_index, const StoreOp & store) [inline]
Definition at line 463 of file store-store-elimination-reducer-inl.h.
                                                                            {
    if (eliminable_stores_.count(ig_index) > 0) {
      return OpIndex::Invalid();
    } else if (mergeable_store_pairs_.count(ig_index) > 0) {
      DCHECK(COMPRESS_POINTERS_BOOL);
      OpIndex value = __ Word64Constant(mergeable_store_pairs_[ig_index]);
      __ Store(__ MapToNewGraph(store.base()), value,
               StoreOp::Kind::TaggedBase(), MemoryRepresentation::Uint64(),
               WriteBarrierKind::kNoWriteBarrier, store.offset);
      return OpIndex::Invalid();
    }
    return Next::ReduceInputGraphStore(ig_index, store);
  }
References __, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::eliminable_stores_, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::mergeable_store_pairs_, store(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), and v8::internal::value.
Member Data Documentation
analysis_
template<class Next >
RedundantStoreAnalysis v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::analysis_ {Asm().input_graph(), Asm().phase_zone()} [private]
Definition at line 478 of file store-store-elimination-reducer-inl.h.
Referenced by v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Analyze().
eliminable_stores_
template<class Next >
ZoneSet<OpIndex> v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::eliminable_stores_ {Asm().phase_zone()} [private]
Definition at line 479 of file store-store-elimination-reducer-inl.h.
Referenced by v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Analyze(), and v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Store().
mergeable_store_pairs_
template<class Next >
ZoneMap<OpIndex, uint64_t> v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::mergeable_store_pairs_ {Asm().phase_zone()} [private]
Definition at line 480 of file store-store-elimination-reducer-inl.h.
Referenced by v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Analyze(), and v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Store().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/store-store-elimination-reducer-inl.h