v8::internal::RegExpClassSetOperand Class Reference
#include <regexp-ast.h>
Public Member Functions
RegExpClassSetOperand (ZoneList< CharacterRange > *ranges, CharacterClassStrings *strings)
DECL_BOILERPLATE (ClassSetOperand)
bool IsTextElement () override
int min_match () override
int max_match () override
void Union (RegExpClassSetOperand *other, Zone *zone)
void Intersect (RegExpClassSetOperand *other, ZoneList< CharacterRange > *temp_ranges, Zone *zone)
void Subtract (RegExpClassSetOperand *other, ZoneList< CharacterRange > *temp_ranges, Zone *zone)
bool has_strings () const
ZoneList< CharacterRange > * ranges ()
CharacterClassStrings * strings ()
Private Attributes
ZoneList< CharacterRange > * ranges_
CharacterClassStrings * strings_
int min_match_
int max_match_
Additional Inherited Members
Detailed Description
Definition at line 398 of file regexp-ast.h.
Constructor & Destructor Documentation
RegExpClassSetOperand()
v8::internal::RegExpClassSetOperand::RegExpClassSetOperand (ZoneList< CharacterRange > * ranges, CharacterClassStrings * strings)
Definition at line 389 of file regexp-ast.cc.
    : ranges_(ranges), strings_(strings) {
  DCHECK_NOT_NULL(ranges);
  min_match_ = 0;
  max_match_ = 0;
  if (!ranges->is_empty()) {
    min_match_ = 1;
    max_match_ = 2;
  }
  if (has_strings()) {
    for (auto string : *strings) {
      min_match_ = std::min(min_match_, string.second->min_match());
      max_match_ = std::max(max_match_, string.second->max_match());
    }
  }
}
References DCHECK_NOT_NULL, has_strings(), max_match_, min_match_, ranges(), and strings().
Member Function Documentation
DECL_BOILERPLATE()
v8::internal::RegExpClassSetOperand::DECL_BOILERPLATE (ClassSetOperand)
has_strings()
bool v8::internal::RegExpClassSetOperand::has_strings () const [inline]
Definition at line 415 of file regexp-ast.h.
{ return strings_ != nullptr && !strings_->empty(); }
References strings_.
Referenced by Intersect(), RegExpClassSetOperand(), Subtract(), Union(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitClassSetOperand(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitClassSetOperand().
Intersect()
void v8::internal::RegExpClassSetOperand::Intersect (RegExpClassSetOperand * other, ZoneList< CharacterRange > * temp_ranges, Zone * zone)
Definition at line 593 of file regexp-compiler-tonode.cc.
                                                  {
  CharacterRange::Intersect(ranges(), other->ranges(), temp_ranges, zone);
  std::swap(*ranges(), *temp_ranges);
  temp_ranges->Rewind(0);
  if (has_strings()) {
    if (!other->has_strings()) {
      strings()->clear();
    } else {
      for (auto iter = strings()->begin(); iter != strings()->end();) {
        if (other->strings()->find(iter->first) == other->strings()->end()) {
          iter = strings()->erase(iter);
        } else {
          iter++;
        }
      }
    }
  }
}
References v8::internal::compiler::begin(), has_strings(), v8::internal::CharacterRange::Intersect(), ranges(), v8::internal::ZoneList< T >::Rewind(), and strings().
IsTextElement()
bool v8::internal::RegExpClassSetOperand::IsTextElement () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 405 of file regexp-ast.h.
{ return true; }
max_match()
int v8::internal::RegExpClassSetOperand::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 407 of file regexp-ast.h.
{ return max_match_; }
References max_match_.
min_match()
int v8::internal::RegExpClassSetOperand::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 406 of file regexp-ast.h.
{ return min_match_; }
References min_match_.
ranges()
ZoneList<CharacterRange>* v8::internal::RegExpClassSetOperand::ranges () [inline]
Definition at line 416 of file regexp-ast.h.
{ return ranges_; }
References ranges_.
Referenced by Intersect(), RegExpClassSetOperand(), Subtract(), Union(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitClassSetOperand().
strings()
CharacterClassStrings* v8::internal::RegExpClassSetOperand::strings () [inline]
Definition at line 417 of file regexp-ast.h.
                                   {
    DCHECK_NOT_NULL(strings_);
    return strings_;
  }
References DCHECK_NOT_NULL, and strings_.
Referenced by Intersect(), RegExpClassSetOperand(), Subtract(), and Union().
Subtract()
void v8::internal::RegExpClassSetOperand::Subtract (RegExpClassSetOperand * other, ZoneList< CharacterRange > * temp_ranges, Zone * zone)
Definition at line 614 of file regexp-compiler-tonode.cc.
                                                 {
  CharacterRange::Subtract(ranges(), other->ranges(), temp_ranges, zone);
  std::swap(*ranges(), *temp_ranges);
  temp_ranges->Rewind(0);
  if (has_strings() && other->has_strings()) {
    for (auto iter = strings()->begin(); iter != strings()->end();) {
      if (other->strings()->find(iter->first) != other->strings()->end()) {
        iter = strings()->erase(iter);
      } else {
        iter++;
      }
    }
  }
}
References v8::internal::compiler::begin(), has_strings(), ranges(), v8::internal::ZoneList< T >::Rewind(), strings(), and v8::internal::CharacterRange::Subtract().
Union()
void v8::internal::RegExpClassSetOperand::Union (RegExpClassSetOperand * other, Zone * zone)
Definition at line 583 of file regexp-compiler-tonode.cc.
                                                                          {
  ranges()->AddAll(*other->ranges(), zone);
  if (other->has_strings()) {
    if (strings_ == nullptr) {
      strings_ = zone->template New<CharacterClassStrings>(zone);
    }
    strings()->insert(other->strings()->begin(), other->strings()->end());
  }
}
References v8::internal::ZoneList< T >::AddAll(), has_strings(), ranges(), and strings().
Member Data Documentation
max_match_
int v8::internal::RegExpClassSetOperand::max_match_ [private]
Definition at line 426 of file regexp-ast.h.
Referenced by max_match(), and RegExpClassSetOperand().
min_match_
int v8::internal::RegExpClassSetOperand::min_match_ [private]
Definition at line 425 of file regexp-ast.h.
Referenced by min_match(), and RegExpClassSetOperand().
ranges_
ZoneList<CharacterRange>* v8::internal::RegExpClassSetOperand::ranges_ [private]
Definition at line 423 of file regexp-ast.h.
Referenced by ranges().
strings_
CharacterClassStrings* v8::internal::RegExpClassSetOperand::strings_ [private]
Definition at line 424 of file regexp-ast.h.
Referenced by has_strings(), and strings().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc