v8::internal::compiler::JSGetIteratorNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSGetIteratorNode (Node *node)
const GetIteratorParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1203 of file js-operator.h.
Constructor & Destructor Documentation
JSGetIteratorNode()
constexpr v8::internal::compiler::JSGetIteratorNode::JSGetIteratorNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1205 of file js-operator.h.
                                                   : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSGetIterator, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const GetIteratorParameters& v8::internal::compiler::JSGetIteratorNode::Parameters () const [inline]
Definition at line 1209 of file js-operator.h.
                                                  {
    return GetIteratorParametersOf(node()->op());
  }
References v8::internal::compiler::GetIteratorParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h