v8::internal::compiler::S390OperandConverter Class Reference
Public Member Functions
S390OperandConverter (CodeGenerator *gen, Instruction *instr)
size_t OutputCount ()
bool Is64BitOperand (int index)
bool Is32BitOperand (int index)
bool CompareLogical () const
Operand InputImmediate (size_t index)
MemOperand MemoryOperand (AddressingMode *mode, size_t *first_index)
MemOperand MemoryOperand (AddressingMode *mode=nullptr, size_t first_index=0)
MemOperand ToMemOperand (InstructionOperand *op) const
MemOperand SlotToMemOperand (int slot) const
MemOperand InputStackSlot (size_t index)
MemOperand InputStackSlot32 (size_t index)
Additional Inherited Members
Detailed Description
Definition at line 31 of file code-generator-s390.cc.
Constructor & Destructor Documentation
S390OperandConverter()
v8::internal::compiler::S390OperandConverter::S390OperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 33 of file code-generator-s390.cc.
      : InstructionOperandConverter(gen, instr) {}
Member Function Documentation
CompareLogical()
bool v8::internal::compiler::S390OperandConverter::CompareLogical () const [inline]
Definition at line 48 of file code-generator-s390.cc.
                              {
    switch (instr_->flags_condition()) {
      case kUnsignedLessThan:
      case kUnsignedGreaterThanOrEqual:
      case kUnsignedLessThanOrEqual:
      case kUnsignedGreaterThan:
        return true;
      default:
        return false;
    }
    UNREACHABLE();
  }
References v8::internal::compiler::Instruction::flags_condition(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, and v8::internal::UNREACHABLE().
InputImmediate()
Operand v8::internal::compiler::S390OperandConverter::InputImmediate (size_t index) [inline]
Definition at line 61 of file code-generator-s390.cc.
                                       {
    Constant constant = ToConstant(instr_->InputAt(index));
    switch (constant.type()) {
      case Constant::kInt32:
        return Operand(constant.ToInt32());
      case Constant::kFloat32:
        return Operand::EmbeddedNumber(constant.ToFloat32());
      case Constant::kFloat64:
        return Operand::EmbeddedNumber(constant.ToFloat64().value());
      case Constant::kInt64:
        return Operand(constant.ToInt64());
      case Constant::kExternalReference:
        return Operand(constant.ToExternalReference());
      case Constant::kCompressedHeapObject:
      case Constant::kHeapObject:
      case Constant::kRpoNumber:
        break;
    }
    UNREACHABLE();
  }
References v8::internal::Operand::EmbeddedNumber(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::compiler::Constant::kExternalReference, v8::internal::compiler::Constant::kFloat32, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kHeapObject, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::Constant::kRpoNumber, v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToExternalReference(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToInt64(), v8::internal::compiler::Constant::type(), v8::internal::UNREACHABLE(), and v8::base::Double::value().
InputStackSlot()
MemOperand v8::internal::compiler::S390OperandConverter::InputStackSlot (size_t index) [inline]
Definition at line 124 of file code-generator-s390.cc.
                                          {
    InstructionOperand* op = instr_->InputAt(index);
    return SlotToMemOperand(AllocatedOperand::cast(op)->index());
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and SlotToMemOperand().
Referenced by InputStackSlot32().
InputStackSlot32()
MemOperand v8::internal::compiler::S390OperandConverter::InputStackSlot32 (size_t index) [inline]
Definition at line 129 of file code-generator-s390.cc.
                                            {
#if V8_TARGET_ARCH_S390X && !V8_TARGET_LITTLE_ENDIAN
    // We want to read the 32-bits directly from memory
    MemOperand mem = InputStackSlot(index);
    return MemOperand(mem.rx(), mem.rb(), mem.offset() + 4);
#else
    return InputStackSlot(index);
#endif
  }
References v8::internal::index, InputStackSlot(), v8::internal::MemOperand::offset(), v8::internal::MemOperand::rb(), and v8::internal::MemOperand::rx().
Is32BitOperand()
bool v8::internal::compiler::S390OperandConverter::Is32BitOperand (int index) [inline]
Definition at line 43 of file code-generator-s390.cc.
                                 {
    return LocationOperand::cast(instr_->InputAt(index))->representation() ==
           MachineRepresentation::kWord32;
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kWord32, and v8::internal::compiler::LocationOperand::representation().
Is64BitOperand()
bool v8::internal::compiler::S390OperandConverter::Is64BitOperand (int index) [inline]
Definition at line 38 of file code-generator-s390.cc.
                                 {
    return LocationOperand::cast(instr_->InputAt(index))->representation() ==
           MachineRepresentation::kWord64;
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kWord64, and v8::internal::compiler::LocationOperand::representation().
MemoryOperand() [1/2]
MemOperand v8::internal::compiler::S390OperandConverter::MemoryOperand (AddressingMode * mode, size_t * first_index) [inline]
Definition at line 82 of file code-generator-s390.cc.
                                                                      {
    const size_t index = *first_index;
    if (mode) *mode = AddressingModeField::decode(instr_->opcode());
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_None:
        break;
      case kMode_MR:
        *first_index += 1;
        return MemOperand(InputRegister(index + 0), 0);
      case kMode_MRI:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputInt32(index + 1));
      case kMode_MRR:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputRegister(index + 1));
      case kMode_MRRI:
        *first_index += 3;
        return MemOperand(InputRegister(index + 0), InputRegister(index + 1),
                          InputInt32(index + 2));
      case kMode_Root:
        *first_index += 1;
        return MemOperand(kRootRegister, InputInt32(index));
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kRootRegister, mode(), v8::internal::compiler::Instruction::opcode(), and v8::internal::UNREACHABLE().
Referenced by MemoryOperand().
MemoryOperand() [2/2]
MemOperand v8::internal::compiler::S390OperandConverter::MemoryOperand (AddressingMode * mode = nullptr, size_t first_index = 0) [inline]
Definition at line 108 of file code-generator-s390.cc.
                                                   {
    return MemoryOperand(mode, &first_index);
  }
References MemoryOperand(), and mode().
OutputCount()
size_t v8::internal::compiler::S390OperandConverter::OutputCount () [inline]
Definition at line 36 of file code-generator-s390.cc.
{ return instr_->OutputCount(); }
References v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::Instruction::OutputCount().
SlotToMemOperand()
MemOperand v8::internal::compiler::S390OperandConverter::SlotToMemOperand (int slot) const [inline]
Definition at line 119 of file code-generator-s390.cc.
                                              {
    FrameOffset offset = frame_access_state()->GetFrameOffset(slot);
    return MemOperand(offset.from_stack_pointer() ? sp : fp, offset.offset());
  }
References v8::internal::compiler::InstructionOperandConverter::frame_access_state(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), and v8::internal::compiler::FrameOffset::offset().
Referenced by InputStackSlot(), and ToMemOperand().
ToMemOperand()
MemOperand v8::internal::compiler::S390OperandConverter::ToMemOperand (InstructionOperand * op) const [inline]
Definition at line 113 of file code-generator-s390.cc.
                                                        {
    DCHECK_NOT_NULL(op);
    DCHECK(op->IsStackSlot() || op->IsFPStackSlot());
    return SlotToMemOperand(AllocatedOperand::cast(op)->index());
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and SlotToMemOperand().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/s390/code-generator-s390.cc