cppgc::internal::HeapObjectHeader Class Reference
#include <heap-object-header.h>
Public Member Functions
HeapObjectHeader (size_t size, GCInfoIndex gc_info_index)
Address ObjectStart () const
template<AccessMode mode = AccessMode::kNonAtomic>
Address ObjectEnd () const
template<AccessMode mode = AccessMode::kNonAtomic>
GCInfoIndex GetGCInfoIndex () const
template<AccessMode mode = AccessMode::kNonAtomic>
size_t AllocatedSize () const
void SetAllocatedSize (size_t size)
template<AccessMode mode = AccessMode::kNonAtomic>
size_t ObjectSize () const
template<AccessMode mode = AccessMode::kNonAtomic>
bool IsLargeObject () const
template<AccessMode = AccessMode::kNonAtomic>
bool IsInConstruction () const
V8_EXPORT_PRIVATE void MarkAsFullyConstructed ()
template<AccessMode = AccessMode::kNonAtomic>
bool IsMarked () const
template<AccessMode = AccessMode::kNonAtomic>
void Unmark ()
bool TryMarkAtomic ()
void MarkNonAtomic ()
template<AccessMode = AccessMode::kNonAtomic>
bool IsYoung () const
template<AccessMode = AccessMode::kNonAtomic>
bool IsFree () const
bool IsFinalizable () const
void Finalize ()
V8_EXPORT_PRIVATE HeapObjectName GetName () const
V8_EXPORT_PRIVATE HeapObjectName GetName (HeapObjectNameForUnnamedObject) const
template<AccessMode = AccessMode::kNonAtomic>
void TraceImpl (Visitor *) const
Static Public Member Functions
static HeapObjectHeader & FromObject (void *address)
static const HeapObjectHeader & FromObject (const void *address)
Static Public Attributes
static constexpr size_t kSizeLog2 = 17
static constexpr size_t kMaxSize = (size_t{1} << kSizeLog2) - 1
static constexpr uint16_t kLargeObjectSizeInHeader = 0
Private Types
enum class EncodedHalf : uint8_t { kLow
, kHigh
 }
using FullyConstructedField = v8::base::BitField16< bool, 0, 1 >
using UnusedField1 = FullyConstructedField::Next< bool, 1 >
using GCInfoIndexField = UnusedField1::Next< GCInfoIndex, 14 >
using MarkBitField = v8::base::BitField16< bool, 0, 1 >
using SizeField = MarkBitField::Next< size_t, 15 >
Private Member Functions
V8_EXPORT_PRIVATE void CheckApiConstants ()
template<AccessMode , EncodedHalf part, std::memory_order memory_order = std::memory_order_seq_cst>
uint16_t LoadEncoded () const
template<AccessMode mode, EncodedHalf part, std::memory_order memory_order = std::memory_order_seq_cst>
void StoreEncoded (uint16_t bits, uint16_t mask)
Static Private Member Functions
static constexpr size_t DecodeSize (uint16_t encoded)
static constexpr uint16_t EncodeSize (size_t size)
Private Attributes
uint16_t encoded_high_
uint16_t encoded_low_
Detailed Description
Definition at line 58 of file heap-object-header.h.
Member Typedef Documentation
FullyConstructedField
using cppgc::internal::HeapObjectHeader::FullyConstructedField = v8::base::BitField16<bool, 0, 1> [private]
Definition at line 129 of file heap-object-header.h.
GCInfoIndexField
using cppgc::internal::HeapObjectHeader::GCInfoIndexField = UnusedField1::Next<GCInfoIndex, 14> [private]
Definition at line 131 of file heap-object-header.h.
MarkBitField
using cppgc::internal::HeapObjectHeader::MarkBitField = v8::base::BitField16<bool, 0, 1> [private]
Definition at line 133 of file heap-object-header.h.
SizeField
using cppgc::internal::HeapObjectHeader::SizeField = MarkBitField::Next<size_t, 15> [private]
Definition at line 134 of file heap-object-header.h.
UnusedField1
using cppgc::internal::HeapObjectHeader::UnusedField1 = FullyConstructedField::Next<bool, 1> [private]
Definition at line 130 of file heap-object-header.h.
Member Enumeration Documentation
EncodedHalf
enum cppgc::internal::HeapObjectHeader::EncodedHalf : uint8_t [strong], [private]
Enumerator
kLow
kHigh
Definition at line 126 of file heap-object-header.h.
: uint8_t { kLow, kHigh };
Constructor & Destructor Documentation
HeapObjectHeader()
cppgc::internal::HeapObjectHeader::HeapObjectHeader (size_t size, GCInfoIndex gc_info_index) [inline]
Definition at line 185 of file heap-object-header.h.
                                                                         {
#if defined(V8_HOST_ARCH_64_BIT) && !defined(CPPGC_CAGED_HEAP)
  USE(padding_);
#endif // defined(V8_HOST_ARCH_64_BIT) && !defined(CPPGC_CAGED_HEAP)
  DCHECK_LT(gc_info_index, GCInfoTable::kMaxIndex);
  DCHECK_EQ(0u, size & (sizeof(HeapObjectHeader) - 1));
  DCHECK_GE(kMaxSize, size);
  encoded_low_ = EncodeSize(size);
  // Objects may get published to the marker without any other synchronization
  // (e.g., write barrier) in which case the in-construction bit is read
  // concurrently which requires reading encoded_high_ atomically. It is ok if
  // this write is not observed by the marker, since the sweeper sets the
  // in-construction bit to 0 and we can rely on that to guarantee a correct
  // answer when checking if objects are in-construction.
  v8::base::AsAtomicPtr(&encoded_high_)
      ->store(GCInfoIndexField::encode(gc_info_index),
              std::memory_order_relaxed);
  DCHECK(IsInConstruction());
#ifdef DEBUG
  CheckApiConstants();
#endif // DEBUG
}
References v8::base::AsAtomicPtr(), CheckApiConstants(), DCHECK, DCHECK_EQ, DCHECK_GE, DCHECK_LT, v8::base::BitField< T, shift, size, U >::encode(), encoded_high_, encoded_low_, EncodeSize(), IsInConstruction(), cppgc::internal::GCInfoTable::kMaxIndex, kMaxSize, size(), and USE.
Referenced by ObjectSize(), and ObjectStart().
Member Function Documentation
AllocatedSize()
template<AccessMode mode>
size_t cppgc::internal::HeapObjectHeader::AllocatedSize [inline]
Definition at line 228 of file heap-object-header.h.
                                             {
  // Size is immutable after construction while either marking or sweeping
  // is running so relaxed load (if mode == kAtomic) is enough.
  uint16_t encoded_low_value =
      LoadEncoded<mode, EncodedHalf::kLow, std::memory_order_relaxed>();
  const size_t size = DecodeSize(encoded_low_value);
  return size;
}
References DecodeSize(), and size().
Referenced by cppgc::internal::BasicMarkingState::AccountMarkedBytes(), v8::internal::CppGraphBuilderImpl::AddNode(), cppgc::internal::FreeList::Allocate(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), cppgc::internal::ObjectHeaderFromInnerAddressImpl(), v8::internal::CppGraphBuilderImpl::Run(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), and cppgc::internal::HeapStatisticsCollector::VisitHeapObjectHeader().
CheckApiConstants()
void cppgc::internal::HeapObjectHeader::CheckApiConstants () [private]
Definition at line 20 of file heap-object-header.cc.
                                         {
  static_assert(api_constants::kFullyConstructedBitMask ==
                FullyConstructedField::kMask);
  static_assert(api_constants::kFullyConstructedBitFieldOffsetFromPayload ==
                (sizeof(encoded_high_) + sizeof(encoded_low_)));
}
References encoded_high_, encoded_low_, cppgc::internal::api_constants::kFullyConstructedBitFieldOffsetFromPayload, cppgc::internal::api_constants::kFullyConstructedBitMask, and v8::base::BitField< T, shift, size, U >::kMask.
Referenced by HeapObjectHeader().
DecodeSize()
static constexpr size_t cppgc::internal::HeapObjectHeader::DecodeSize (uint16_t encoded) [inline], [static], [constexpr], [private]
Definition at line 137 of file heap-object-header.h.
                                                       {
    // Essentially, gets optimized to << 1.
    return SizeField::decode(encoded) * kAllocationGranularity;
  }
References v8::base::BitField< T, shift, size, U >::decode(), and cppgc::internal::kAllocationGranularity.
Referenced by AllocatedSize().
EncodeSize()
static constexpr uint16_t cppgc::internal::HeapObjectHeader::EncodeSize (size_t size) [inline], [static], [constexpr], [private]
Definition at line 142 of file heap-object-header.h.
                                                    {
    // Essentially, gets optimized to >> 1.
    return SizeField::encode(size / kAllocationGranularity);
  }
References v8::base::BitField< T, shift, size, U >::encode(), cppgc::internal::kAllocationGranularity, and size().
Referenced by HeapObjectHeader(), and SetAllocatedSize().
Finalize()
void cppgc::internal::HeapObjectHeader::Finalize ()
Definition at line 27 of file heap-object-header.cc.
                                {
#ifdef V8_USE_ADDRESS_SANITIZER
  const size_t size =
      IsLargeObject()
          ? LargePage::From(BasePage::FromPayload(this))->ObjectSize()
          : ObjectSize();
  ASAN_UNPOISON_MEMORY_REGION(ObjectStart(), size);
#endif // V8_USE_ADDRESS_SANITIZER
  const GCInfo& gc_info = GlobalGCInfoTable::GCInfoFromIndex(GetGCInfoIndex());
  if (gc_info.finalize) {
    gc_info.finalize(ObjectStart());
  }
}
References ASAN_UNPOISON_MEMORY_REGION, cppgc::internal::GCInfo::finalize, cppgc::internal::LargePage::From(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex(), GetGCInfoIndex(), IsLargeObject(), ObjectSize(), cppgc::internal::LargePage::ObjectSize(), ObjectStart(), and size().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::AddFinalizer(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitLargePage().
FromObject() [1/2]
const HeapObjectHeader & cppgc::internal::HeapObjectHeader::FromObject (const void * address) [inline], [static]
Definition at line 180 of file heap-object-header.h.
                                                                       {
  return *reinterpret_cast<const HeapObjectHeader*>(
      static_cast<ConstAddress>(object) - sizeof(HeapObjectHeader));
}
FromObject() [2/2]
HeapObjectHeader & cppgc::internal::HeapObjectHeader::FromObject (void * address) [inline], [static]
Definition at line 174 of file heap-object-header.h.
                                                           {
  return *reinterpret_cast<HeapObjectHeader*>(static_cast<Address>(object) -
                                              sizeof(HeapObjectHeader));
}
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), v8::internal::CppGraphBuilderImpl::AddEdgeForCppHeapExternalObject(), cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::BaseObjectSizeTrait::GetObjectSizeForGarbageCollected(), cppgc::internal::MutatorMarkingState::InvokeWeakRootsCallbackIfNeeded(), cppgc::LivenessBroker::IsHeapObjectAliveImpl(), cppgc::testing::IsHeapObjectOld(), cppgc::internal::MarkingStateBase::MarkAndPush(), v8::internal::CppMarkingState::MarkAndPush(), cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint(), cppgc::internal::BasicMarkingState::ProcessEphemeron(), cppgc::internal::BasicMarkingState::ProcessWeakContainer(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), cppgc::internal::BasicMarkingState::RegisterWeakReferenceIfNeeded(), cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::Relocate(), cppgc::internal::ExplicitManagementImpl::Resize(), cppgc::internal::VerificationState::VerifyMarked(), v8::internal::VisiblityVisitor::Visit(), v8::internal::GraphBuildingVisitor::Visit(), v8::internal::WeakVisitor::VisitEphemeron(), v8::internal::GraphBuildingRootVisitor::VisitRoot(), v8::internal::WeakVisitor::VisitWeakContainer(), v8::internal::GraphBuildingVisitor::VisitWeakContainer(), v8::internal::CppHeap::WriteBarrier(), and cppgc::internal::MarkerBase::~MarkerBase().
GetGCInfoIndex()
template<AccessMode mode>
GCInfoIndex cppgc::internal::HeapObjectHeader::GetGCInfoIndex [inline]
Definition at line 221 of file heap-object-header.h.
                                                   {
  const uint16_t encoded =
      LoadEncoded<mode, EncodedHalf::kHigh, std::memory_order_acquire>();
  return GCInfoIndexField::decode(encoded);
}
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by cppgc::internal::MutatorMarkingState::DynamicallyMarkAddress(), Finalize(), GetName(), cppgc::internal::TraceTraitFromInnerAddressImpl::GetTraceDescriptor(), IsFinalizable(), cppgc::internal::MarkingStateBase::MarkAndPush(), cppgc::internal::BasePage::ObjectHeaderFromInnerAddress(), and cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress().
GetName() [1/2]
HeapObjectName cppgc::internal::HeapObjectHeader::GetName () const
Definition at line 41 of file heap-object-header.cc.
                                               {
  return GetName(BasePage::FromPayload(this)->heap().name_of_unnamed_object());
}
References cppgc::internal::BasePage::FromPayload(), and heap().
Referenced by v8::internal::CppGraphBuilderImpl::AddNode(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::RecordObjectType(), cppgc::internal::MarkingVerifierBase::ReportHeapObjectHeader(), cppgc::internal::VerificationState::VerifyMarked(), and v8::internal::CppGraphBuilderImpl::VisitForVisibility().
GetName() [2/2]
HeapObjectName cppgc::internal::HeapObjectHeader::GetName (HeapObjectNameForUnnamedObject heap_object_name) const
Definition at line 45 of file heap-object-header.cc.
                                                           {
  const GCInfo& gc_info = GlobalGCInfoTable::GCInfoFromIndex(GetGCInfoIndex());
  return gc_info.name(ObjectStart(), heap_object_name);
}
References cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex(), GetGCInfoIndex(), cppgc::internal::GCInfo::name, and ObjectStart().
IsFinalizable()
bool cppgc::internal::HeapObjectHeader::IsFinalizable () const [inline]
Definition at line 309 of file heap-object-header.h.
                                           {
  const GCInfo& gc_info = GlobalGCInfoTable::GCInfoFromIndex(GetGCInfoIndex());
  return gc_info.finalize;
}
References cppgc::internal::GCInfo::finalize, cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex(), and GetGCInfoIndex().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::AddFinalizer(), and cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::VisitLargePage().
IsFree()
template<AccessMode mode>
bool cppgc::internal::HeapObjectHeader::IsFree
Definition at line 305 of file heap-object-header.h.
                                    {
  return GetGCInfoIndex<mode>() == kFreeListGCInfoIndex;
}
References cppgc::internal::kFreeListGCInfoIndex.
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), cppgc::internal::MarkingStateBase::MarkNoPush(), cppgc::internal::MarkingVerifierBase::ReportHeapObjectHeader(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress(), cppgc::internal::HeapStatisticsCollector::VisitHeapObjectHeader(), cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader(), v8::internal::LiveObjectsForVisibilityIterator::VisitHeapObjectHeader(), and cppgc::internal::anonymous_namespace{heap-base.cc}::ObjectSizeCounter::VisitHeapObjectHeader().
IsInConstruction()
template<AccessMode mode>
bool cppgc::internal::HeapObjectHeader::IsInConstruction
Definition at line 263 of file heap-object-header.h.
                                              {
  const uint16_t encoded =
      LoadEncoded<mode, EncodedHalf::kHigh, std::memory_order_acquire>();
  return !FullyConstructedField::decode(encoded);
}
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by cppgc::internal::MutatorMarkingState::DynamicallyMarkAddress(), cppgc::internal::DynamicallyTraceMarkedObject(), HeapObjectHeader(), cppgc::internal::MutatorMarkingState::InvokeWeakRootsCallbackIfNeeded(), cppgc::internal::MutatorMarkingState::IsMarkedWeakContainer(), cppgc::internal::MarkingStateBase::MarkAndPush(), cppgc::internal::BasicMarkingState::ProcessEphemeron(), cppgc::internal::BasicMarkingState::ProcessWeakContainer(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), cppgc::internal::MarkingStateBase::PushMarked(), cppgc::internal::BasicMarkingState::RegisterWeakReferenceIfNeeded(), v8::internal::CppGraphBuilderImpl::Run(), cppgc::internal::ConservativeTracingVisitor::TraceConservativelyIfNeeded(), cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader(), and cppgc::internal::MarkerBase::WriteBarrierForObject().
IsLargeObject()
template<AccessMode mode>
bool cppgc::internal::HeapObjectHeader::IsLargeObject [inline]
Definition at line 258 of file heap-object-header.h.
                                           {
  return AllocatedSize<mode>() == kLargeObjectSizeInHeader;
}
References kLargeObjectSizeInHeader.
Referenced by cppgc::internal::BasicMarkingState::AccountMarkedBytes(), Finalize(), cppgc::internal::HeapStatisticsCollector::VisitHeapObjectHeader(), and cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::VisitHeapObjectHeader().
IsMarked()
template<AccessMode mode>
bool cppgc::internal::HeapObjectHeader::IsMarked
Definition at line 270 of file heap-object-header.h.
                                      {
  const uint16_t encoded =
      LoadEncoded<mode, EncodedHalf::kLow, std::memory_order_relaxed>();
  return MarkBitField::decode(encoded);
}
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::AddOrFilter(), cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), cppgc::internal::DynamicallyTraceMarkedObject(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), cppgc::internal::MutatorMarkingState::InvokeWeakRootsCallbackIfNeeded(), cppgc::LivenessBroker::IsHeapObjectAliveImpl(), cppgc::testing::IsHeapObjectOld(), cppgc::internal::MutatorMarkingState::IsMarkedWeakContainer(), cppgc::internal::BasicMarkingState::ProcessEphemeron(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), cppgc::internal::MarkingStateBase::PushMarked(), cppgc::internal::BasicMarkingState::RegisterWeakReferenceIfNeeded(), cppgc::internal::MarkingVerifierBase::ReportHeapObjectHeader(), SetAllocatedSize(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepLiveLargePage(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), cppgc::internal::VerificationState::VerifyMarked(), cppgc::internal::ConservativeMarkingVisitor::VisitFullyConstructedConservatively(), cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader(), cppgc::internal::SequentialUnmarker::VisitHeapObjectHeader(), cppgc::internal::MarkingVerifierBase::VisitInConstructionConservatively(), cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitLargePage(), cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::VisitLargePage(), cppgc::internal::MarkerBase::WriteBarrierForObject(), and cppgc::internal::MarkerBase::~MarkerBase().
IsYoung()
template<AccessMode mode>
bool cppgc::internal::HeapObjectHeader::IsYoung
Definition at line 300 of file heap-object-header.h.
                                     {
  return !IsMarked<mode>();
}
LoadEncoded()
template<AccessMode mode, HeapObjectHeader::EncodedHalf part, std::memory_order memory_order>
uint16_t cppgc::internal::HeapObjectHeader::LoadEncoded [inline], [private]
Definition at line 351 of file heap-object-header.h.
                                             {
  const uint16_t& half =
      part == EncodedHalf::kLow ? encoded_low_ : encoded_high_;
  if (mode == AccessMode::kNonAtomic) return half;
  return v8::base::AsAtomicPtr(&half)->load(memory_order);
}
References v8::base::AsAtomicPtr(), encoded_high_, encoded_low_, kLow, cppgc::internal::kNonAtomic, and mode().
MarkAsFullyConstructed()
void cppgc::internal::HeapObjectHeader::MarkAsFullyConstructed ()
Definition at line 51 of file heap-object-header.cc.
                                              {
  MakeGarbageCollectedTraitInternal::MarkObjectAsFullyConstructed(
      ObjectStart());
}
References cppgc::internal::MakeGarbageCollectedTraitInternal::MarkObjectAsFullyConstructed(), and ObjectStart().
MarkNonAtomic()
void cppgc::internal::HeapObjectHeader::MarkNonAtomic () [inline]
Definition at line 294 of file heap-object-header.h.
                                     {
  DCHECK(!IsMarked<AccessMode::kNonAtomic>());
  encoded_low_ |= MarkBitField::encode(true);
}
References DCHECK, v8::base::BitField< T, shift, size, U >::encode(), and encoded_low_.
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint().
ObjectEnd()
template<AccessMode mode>
Address cppgc::internal::HeapObjectHeader::ObjectEnd [inline]
Definition at line 214 of file heap-object-header.h.
                                          {
  DCHECK(!IsLargeObject<mode>());
  return reinterpret_cast<Address>(const_cast<HeapObjectHeader*>(this)) +
         AllocatedSize<mode>();
}
References DCHECK.
Referenced by cppgc::internal::FreeList::AddReturningUnusedBounds(), cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
ObjectSize()
template<AccessMode mode>
size_t cppgc::internal::HeapObjectHeader::ObjectSize [inline]
Definition at line 251 of file heap-object-header.h.
                                          {
  // The following DCHECK also fails for large objects.
  DCHECK_GT(AllocatedSize<mode>(), sizeof(HeapObjectHeader));
  return AllocatedSize<mode>() - sizeof(HeapObjectHeader);
}
References DCHECK_GT, and HeapObjectHeader().
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), Finalize(), cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::Relocate(), and cppgc::internal::MarkingVerifierBase::ReportHeapObjectHeader().
ObjectStart()
Address cppgc::internal::HeapObjectHeader::ObjectStart () const [inline]
Definition at line 208 of file heap-object-header.h.
                                            {
  return reinterpret_cast<Address>(const_cast<HeapObjectHeader*>(this)) +
         sizeof(HeapObjectHeader);
}
References HeapObjectHeader().
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::AddOrFilter(), cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), cppgc::internal::MutatorMarkingState::DynamicallyMarkAddress(), Finalize(), GetName(), cppgc::internal::TraceTraitFromInnerAddressImpl::GetTraceDescriptor(), cppgc::internal::MarkingStateBase::MarkAndPush(), MarkAsFullyConstructed(), cppgc::internal::MarkingVerifierBase::ReportHeapObjectHeader(), TraceImpl(), cppgc::internal::VerificationState::VerifyMarked(), v8::internal::UnifiedHeapVerificationState::VerifyMarkedTracedReference(), v8::internal::anonymous_namespace{cpp-snapshot.cc}::GraphBuildingStackVisitor::VisitConservatively(), cppgc::internal::ConservativeTracingVisitor::VisitFullyConstructedConservatively(), cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader(), and cppgc::internal::MarkingVerifierBase::VisitInConstructionConservatively().
SetAllocatedSize()
void cppgc::internal::HeapObjectHeader::SetAllocatedSize (size_t size) [inline]
Definition at line 237 of file heap-object-header.h.
                                                   {
#if !defined(CPPGC_YOUNG_GENERATION)
  // With sticky bits, marked objects correspond to old objects.
  // TODO(bikineev:1029379): Consider disallowing old/marked objects to be
  // resized.
  DCHECK(!IsMarked());
#endif
  // The object may be marked (i.e. old, in case young generation is enabled).
  // Make sure to not overwrite the mark bit.
  encoded_low_ &= ~SizeField::encode(SizeField::kMax);
  encoded_low_ |= EncodeSize(size);
}
References DCHECK, encoded_low_, EncodeSize(), IsMarked(), v8::base::BitField< T, shift, size, U >::kMax, and size().
Referenced by cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
StoreEncoded()
template<AccessMode mode, HeapObjectHeader::EncodedHalf part, std::memory_order memory_order>
void cppgc::internal::HeapObjectHeader::StoreEncoded (uint16_t bits, uint16_t mask) [inline], [private]
Definition at line 360 of file heap-object-header.h.
                                                                {
  // Caveat: Not all changes to HeapObjectHeader's bitfields go through
  // StoreEncoded. The following have their own implementations and need to be
  // kept in sync:
  // - HeapObjectHeader::TryMarkAtomic
  // - MarkObjectAsFullyConstructed (API)
  DCHECK_EQ(0u, bits & ~mask);
  uint16_t& half = part == EncodedHalf::kLow ? encoded_low_ : encoded_high_;
  if (mode == AccessMode::kNonAtomic) {
    half = (half & ~mask) | bits;
    return;
  }
  // We don't perform CAS loop here assuming that only none of the info that
  // shares the same encoded halfs change at the same time.
  auto* atomic_encoded = v8::base::AsAtomicPtr(&half);
  uint16_t value = atomic_encoded->load(std::memory_order_relaxed);
  value = (value & ~mask) | bits;
  atomic_encoded->store(value, memory_order);
}
References v8::base::AsAtomicPtr(), DCHECK_EQ, encoded_high_, encoded_low_, kLow, cppgc::internal::kNonAtomic, mode(), and v8::internal::value.
TraceImpl()
template<AccessMode mode>
void cppgc::internal::HeapObjectHeader::TraceImpl (Visitor * visitor) const
Definition at line 343 of file heap-object-header.h.
                                                       {
  const GCInfo& gc_info =
      GlobalGCInfoTable::GCInfoFromIndex(GetGCInfoIndex<mode>());
  return gc_info.trace(visitor, ObjectStart());
}
References cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex(), ObjectStart(), and cppgc::internal::GCInfo::trace.
Referenced by cppgc::internal::DynamicallyTraceMarkedObject(), v8::internal::CppGraphBuilderImpl::Run(), v8::internal::CppGraphBuilderImpl::VisitForVisibility(), and cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader().
TryMarkAtomic()
bool cppgc::internal::HeapObjectHeader::TryMarkAtomic () [inline]
Definition at line 283 of file heap-object-header.h.
                                     {
  auto* atomic_encoded = v8::base::AsAtomicPtr(&encoded_low_);
  uint16_t old_value = atomic_encoded->load(std::memory_order_relaxed);
  const uint16_t new_value = old_value | MarkBitField::encode(true);
  if (new_value == old_value) {
    return false;
  }
  return atomic_encoded->compare_exchange_strong(old_value, new_value,
                                                 std::memory_order_relaxed);
}
References v8::base::AsAtomicPtr(), v8::base::BitField< T, shift, size, U >::encode(), and encoded_low_.
Referenced by cppgc::internal::MarkingStateBase::MarkNoPush(), and cppgc::internal::MarkerBase::WriteBarrierForObject().
Unmark()
template<AccessMode mode>
void cppgc::internal::HeapObjectHeader::Unmark
Definition at line 277 of file heap-object-header.h.
                              {
  DCHECK(IsMarked<mode>());
  StoreEncoded<mode, EncodedHalf::kLow, std::memory_order_relaxed>(
      MarkBitField::encode(false), MarkBitField::kMask);
}
References DCHECK, v8::base::BitField< T, shift, size, U >::encode(), and v8::base::BitField< T, shift, size, U >::kMask.
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), cppgc::internal::anonymous_namespace{sweeper.cc}::StickyUnmark(), cppgc::internal::SequentialUnmarker::VisitHeapObjectHeader(), and cppgc::internal::MarkerBase::WriteBarrierForObject().
Member Data Documentation
encoded_high_
uint16_t cppgc::internal::HeapObjectHeader::encoded_high_ [private]
Definition at line 165 of file heap-object-header.h.
Referenced by CheckApiConstants(), HeapObjectHeader(), LoadEncoded(), and StoreEncoded().
encoded_low_
uint16_t cppgc::internal::HeapObjectHeader::encoded_low_ [private]
Definition at line 166 of file heap-object-header.h.
Referenced by CheckApiConstants(), HeapObjectHeader(), LoadEncoded(), MarkNonAtomic(), SetAllocatedSize(), StoreEncoded(), and TryMarkAtomic().
kLargeObjectSizeInHeader
constexpr uint16_t cppgc::internal::HeapObjectHeader::kLargeObjectSizeInHeader = 0 [static], [constexpr]
Definition at line 62 of file heap-object-header.h.
Referenced by IsLargeObject(), and cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject().
kMaxSize
constexpr size_t cppgc::internal::HeapObjectHeader::kMaxSize = (size_t{1} << kSizeLog2) - 1 [static], [constexpr]
Definition at line 61 of file heap-object-header.h.
Referenced by HeapObjectHeader().
kSizeLog2
constexpr size_t cppgc::internal::HeapObjectHeader::kSizeLog2 = 17 [static], [constexpr]
Definition at line 60 of file heap-object-header.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap-object-header.h
/mnt/V8SourceCode/src/heap/cppgc/heap-object-header.cc