v8::internal::Property Class Reference
#include <ast.h>
Public Member Functions
bool is_optional_chain_link () const
bool IsValidReferenceExpression () const
Expression * obj () const
Expression * key () const
bool IsSuperAccess ()
bool IsPrivateReference () const
Static Public Member Functions
static AssignType GetAssignType (Property *property)
Private Types
using IsOptionalChainLinkField = Expression::NextBitField< bool, 1 >
Private Member Functions
Property (Expression *obj, Expression *key, int pos, bool optional_chain)
Private Attributes
friend Zone
Expression * obj_
Expression * key_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1659 of file ast.h.
Member Typedef Documentation
IsOptionalChainLinkField
using v8::internal::Property::IsOptionalChainLinkField = Expression::NextBitField<bool, 1> [private]
Definition at line 1715 of file ast.h.
Constructor & Destructor Documentation
Property()
v8::internal::Property::Property (Expression * obj, Expression * key, int pos, bool optional_chain) [inline], [private]
Definition at line 1710 of file ast.h.
      : Expression(pos, kProperty), obj_(obj), key_(key) {
    bit_field_ |= IsOptionalChainLinkField::encode(optional_chain);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::encode().
Member Function Documentation
GetAssignType()
static AssignType v8::internal::Property::GetAssignType (Property * property) [inline], [static]
Definition at line 1674 of file ast.h.
                                                      {
    if (property == nullptr) return NON_PROPERTY;
    if (property->IsPrivateReference()) {
      DCHECK(!property->IsSuperAccess());
      VariableProxy* proxy = property->key()->AsVariableProxy();
      DCHECK_NOT_NULL(proxy);
      Variable* var = proxy->var();
      switch (var->mode()) {
        case VariableMode::kPrivateMethod:
          return PRIVATE_METHOD;
        case VariableMode::kConst:
          return KEYED_PROPERTY; // Use KEYED_PROPERTY for private fields.
        case VariableMode::kPrivateGetterOnly:
          return PRIVATE_GETTER_ONLY;
        case VariableMode::kPrivateSetterOnly:
          return PRIVATE_SETTER_ONLY;
        case VariableMode::kPrivateGetterAndSetter:
          return PRIVATE_GETTER_AND_SETTER;
        case VariableMode::kDynamic:
          // From debug-evaluate.
          return PRIVATE_DEBUG_DYNAMIC;
        default:
          UNREACHABLE();
      }
    }
    bool super_access = property->IsSuperAccess();
    return (property->key()->IsPropertyName())
               ? (super_access ? NAMED_SUPER_PROPERTY : NAMED_PROPERTY)
               : (super_access ? KEYED_SUPER_PROPERTY : KEYED_PROPERTY);
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, IsPrivateReference(), v8::internal::Expression::IsPropertyName(), IsSuperAccess(), v8::internal::kConst, v8::internal::kDynamic, key(), v8::internal::KEYED_PROPERTY, v8::internal::KEYED_SUPER_PROPERTY, v8::internal::kPrivateGetterAndSetter, v8::internal::kPrivateGetterOnly, v8::internal::kPrivateMethod, v8::internal::kPrivateSetterOnly, v8::internal::Variable::mode(), v8::internal::NAMED_PROPERTY, v8::internal::NAMED_SUPER_PROPERTY, v8::internal::NON_PROPERTY, v8::internal::PRIVATE_DEBUG_DYNAMIC, v8::internal::PRIVATE_GETTER_AND_SETTER, v8::internal::PRIVATE_GETTER_ONLY, v8::internal::PRIVATE_METHOD, v8::internal::PRIVATE_SETTER_ONLY, v8::internal::UNREACHABLE(), and v8::internal::VariableProxy::var().
Referenced by v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad().
is_optional_chain_link()
bool v8::internal::Property::is_optional_chain_link () const [inline]
Definition at line 1661 of file ast.h.
                                      {
    return IsOptionalChainLinkField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitDelete(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad().
IsPrivateReference()
bool v8::internal::Property::IsPrivateReference () const [inline]
Definition at line 1671 of file ast.h.
{ return key()->IsPrivateName(); }
References v8::internal::Expression::IsPrivateName(), and key().
Referenced by GetAssignType(), v8::internal::Call::GetCallType(), and v8::internal::interpreter::BytecodeGenerator::VisitDelete().
IsSuperAccess()
bool v8::internal::Property::IsSuperAccess () [inline]
Definition at line 1670 of file ast.h.
{ return obj()->IsSuperPropertyReference(); }
References obj().
Referenced by GetAssignType(), v8::internal::Call::GetCallType(), v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs(), and v8::internal::interpreter::BytecodeGenerator::VisitDelete().
IsValidReferenceExpression()
bool v8::internal::Property::IsValidReferenceExpression () const [inline]
Definition at line 1665 of file ast.h.
{ return true; }
key()
Expression* v8::internal::Property::key () const [inline]
Definition at line 1668 of file ast.h.
{ return key_; }
References key_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicGet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicSet(), GetAssignType(), v8::internal::Call::GetCallType(), IsPrivateReference(), v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad().
obj()
Expression* v8::internal::Property::obj () const [inline]
Definition at line 1667 of file ast.h.
{ return obj_; }
References obj_.
Referenced by IsSuperAccess(), v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1707 of file ast.h.
Member Data Documentation
key_
Expression* v8::internal::Property::key_ [private]
Definition at line 1718 of file ast.h.
Referenced by key().
obj_
Expression* v8::internal::Property::obj_ [private]
Definition at line 1717 of file ast.h.
Referenced by obj().
Zone
friend v8::internal::Property::Zone [private]
Definition at line 1708 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h