v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots Class Reference
Public Member Functions
NaryCodeCoverageSlots (BytecodeGenerator *generator, NaryOperation *expr)
int GetSlotFor (size_t subsequent_expr_index) const
Private Attributes
BytecodeGenerator * generator_
std::vector< int > coverage_slots_
Detailed Description
Definition at line 607 of file bytecode-generator.cc.
Constructor & Destructor Documentation
NaryCodeCoverageSlots()
v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::NaryCodeCoverageSlots (BytecodeGenerator * generator, NaryOperation * expr) [inline]
Definition at line 609 of file bytecode-generator.cc.
      : generator_(generator) {
    if (generator_->block_coverage_builder_ == nullptr) return;
    for (size_t i = 0; i < expr->subsequent_length(); i++) {
      coverage_slots_.push_back(
          generator_->AllocateNaryBlockCoverageSlotIfEnabled(expr, i));
    }
  }
References v8::internal::interpreter::BytecodeGenerator::AllocateNaryBlockCoverageSlotIfEnabled(), v8::internal::interpreter::BytecodeGenerator::block_coverage_builder_, coverage_slots_, generator_, and v8::internal::NaryOperation::subsequent_length().
Member Function Documentation
GetSlotFor()
int v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::GetSlotFor (size_t subsequent_expr_index) const [inline]
Definition at line 618 of file bytecode-generator.cc.
                                                     {
    if (generator_->block_coverage_builder_ == nullptr) {
      return BlockCoverageBuilder::kNoCoverageArraySlot;
    }
    DCHECK(coverage_slots_.size() > subsequent_expr_index);
    return coverage_slots_[subsequent_expr_index];
  }
References v8::internal::interpreter::BytecodeGenerator::block_coverage_builder_, coverage_slots_, v8::internal::DCHECK(), generator_, and v8::internal::interpreter::BlockCoverageBuilder::kNoCoverageArraySlot.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression().
Member Data Documentation
coverage_slots_
std::vector<int> v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::coverage_slots_ [private]
Definition at line 628 of file bytecode-generator.cc.
Referenced by GetSlotFor(), and NaryCodeCoverageSlots().
generator_
BytecodeGenerator* v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::generator_ [private]
Definition at line 627 of file bytecode-generator.cc.
Referenced by GetSlotFor(), and NaryCodeCoverageSlots().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc