v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher Class Reference
Public Member Functions
JobDispatcher (Isolate *isolate, LockedQueue< std::unique_ptr< BaselineBatchCompilerJob >> *incoming_queue, LockedQueue< std::unique_ptr< BaselineBatchCompilerJob >> *outcoming_queue)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Attributes
Isolate * isolate_
LockedQueue< std::unique_ptr< BaselineBatchCompilerJob > > * incoming_queue_
LockedQueue< std::unique_ptr< BaselineBatchCompilerJob > > * outgoing_queue_
Detailed Description
Definition at line 150 of file baseline-batch-compiler.cc.
Constructor & Destructor Documentation
JobDispatcher()
v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::JobDispatcher (Isolate * isolate, LockedQueue< std::unique_ptr< BaselineBatchCompilerJob >> * incoming_queue, LockedQueue< std::unique_ptr< BaselineBatchCompilerJob >> * outcoming_queue) [inline]
Definition at line 152 of file baseline-batch-compiler.cc.
        : isolate_(isolate),
          incoming_queue_(incoming_queue),
          outgoing_queue_(outcoming_queue) {}
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 177 of file baseline-batch-compiler.cc.
                                                                 {
      size_t max_threads = v8_flags.concurrent_sparkplug_max_threads;
      size_t num_tasks = incoming_queue_->size() + worker_count;
      if (max_threads > 0) {
        return std::min(max_threads, num_tasks);
      }
      return num_tasks;
    }
References incoming_queue_, and v8::internal::v8_flags.
Run()
void v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 160 of file baseline-batch-compiler.cc.
                                             {
      base::FlushDenormalsScope flush_denormals_scope(
          isolate_->flush_denormals());
      LocalIsolate local_isolate(isolate_, ThreadKind::kBackground);
      UnparkedScope unparked_scope(&local_isolate);
      LocalHandleScope handle_scope(&local_isolate);
      while (!incoming_queue_->IsEmpty() && !delegate->ShouldYield()) {
        std::unique_ptr<BaselineBatchCompilerJob> job;
        if (!incoming_queue_->Dequeue(&job)) break;
        DCHECK_NOT_NULL(job);
        job->Compile(&local_isolate);
        outgoing_queue_->Enqueue(std::move(job));
      }
      isolate_->stack_guard()->RequestInstallBaselineCode();
    }
References DCHECK_NOT_NULL, v8::internal::Isolate::flush_denormals(), incoming_queue_, isolate_, v8::internal::kBackground, outgoing_queue_, v8::JobDelegate::ShouldYield(), and v8::internal::Isolate::stack_guard().
Member Data Documentation
incoming_queue_
LockedQueue<std::unique_ptr<BaselineBatchCompilerJob> >* v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::incoming_queue_ [private]
Definition at line 188 of file baseline-batch-compiler.cc.
Referenced by GetMaxConcurrency(), and Run().
isolate_
Isolate* v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::isolate_ [private]
Definition at line 187 of file baseline-batch-compiler.cc.
Referenced by Run().
outgoing_queue_
LockedQueue<std::unique_ptr<BaselineBatchCompilerJob> >* v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::outgoing_queue_ [private]
Definition at line 189 of file baseline-batch-compiler.cc.
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/baseline/baseline-batch-compiler.cc