v8::internal::Snapshot Class Reference
#include <snapshot.h>
Public Types
enum SerializerFlag { kAllowUnknownExternalReferencesForTesting = 1 << 0
, kAllowActiveIsolateForTesting = 1 << 1
, kReconstructReadOnlyAndSharedObjectCachesForTesting = 1 << 2
 }
using SerializerFlags = base::Flags< SerializerFlag >
Static Public Member Functions
static V8_EXPORT_PRIVATE void ClearReconstructableDataForSerialization (Isolate *isolate, bool clear_recompilable_data)
static v8::StartupData Create (Isolate *isolate, std::vector< Tagged< Context >> *contexts, const std::vector< SerializeEmbedderFieldsCallback > &embedder_fields_serializers, const SafepointScope &safepoint_scope, const DisallowGarbageCollection &no_gc, SerializerFlags flags=kDefaultSerializerFlags)
static bool Initialize (Isolate *isolate)
static MaybeDirectHandle< Context > NewContextFromSnapshot (Isolate *isolate, DirectHandle< JSGlobalProxy > global_proxy, size_t context_index, DeserializeEmbedderFieldsCallback embedder_fields_deserializer)
static V8_EXPORT_PRIVATE void SerializeDeserializeAndVerifyForTesting (Isolate *isolate, DirectHandle< Context > default_context)
static bool HasContextSnapshot (Isolate *isolate, size_t index)
static bool EmbedsScript (Isolate *isolate)
static V8_EXPORT_PRIVATE uint32_t GetExpectedChecksum (const v8::StartupData *data)
static V8_EXPORT_PRIVATE uint32_t CalculateChecksum (const v8::StartupData *data)
static V8_EXPORT_PRIVATE bool VerifyChecksum (const v8::StartupData *data)
static bool ExtractRehashability (const v8::StartupData *data)
static V8_EXPORT_PRIVATE uint32_t ExtractReadOnlySnapshotChecksum (const v8::StartupData *data)
static bool VersionIsValid (const v8::StartupData *data)
static const v8::StartupData * DefaultSnapshotBlob ()
static bool ShouldVerifyChecksum (const v8::StartupData *data)
Static Public Attributes
static constexpr V8_EXPORT_PRIVATE SerializerFlags kDefaultSerializerFlags
Detailed Description
Definition at line 25 of file snapshot.h.
Member Typedef Documentation
SerializerFlags
using v8::internal::Snapshot::SerializerFlags = base::Flags<SerializerFlag>
Definition at line 56 of file snapshot.h.
Member Enumeration Documentation
SerializerFlag
enum v8::internal::Snapshot::SerializerFlag
Enumerator
kAllowUnknownExternalReferencesForTesting
kAllowActiveIsolateForTesting
kReconstructReadOnlyAndSharedObjectCachesForTesting
Definition at line 29 of file snapshot.h.
                      {
    // If set, serializes unknown external references as verbatim data. This
    // usually leads to invalid state if the snapshot is deserialized in a
    // different isolate or a different process.
    // If unset, all external references must be known to the encoder.
    kAllowUnknownExternalReferencesForTesting = 1 << 0,
    // If set, the serializer enters a more permissive mode which allows
    // serialization of a currently active, running isolate. This has multiple
    // effects; for example, open handles are allowed, microtasks may exist,
    // etc. Note that in this mode, the serializer is allowed to skip
    // visitation of certain problematic areas even if they are non-empty. The
    // resulting snapshot is not guaranteed to result in a runnable context
    // after deserialization.
    // If unset, we assert that these previously mentioned areas are empty.
    kAllowActiveIsolateForTesting = 1 << 1,
    // If set, the ReadOnlySerializer and the SharedHeapSerializer reconstructs
    // their respective object caches from the existing ReadOnlyHeap's read-only
    // object cache or the existing shared heap's object cache so the same
    // mapping is used. This mode is used for testing deserialization of a
    // snapshot from a live isolate that's using a shared ReadOnlyHeap or is
    // attached to a shared isolate. Otherwise during deserialization the
    // indices will mismatch, causing deserialization crashes when e.g. types
    // mismatch. If unset, the read-only object cache is populated as read-only
    // objects are serialized, and the shared heap object cache is populated as
    // shared heap objects are serialized.
    kReconstructReadOnlyAndSharedObjectCachesForTesting = 1 << 2,
  };
Member Function Documentation
CalculateChecksum()
uint32_t v8::internal::Snapshot::CalculateChecksum (const v8::StartupData * data) [static]
Definition at line 637 of file snapshot.cc.
                                                              {
  return Checksum(SnapshotImpl::ChecksummedContent(data));
}
References v8::internal::Checksum().
Referenced by VerifyChecksum().
ClearReconstructableDataForSerialization()
void v8::internal::Snapshot::ClearReconstructableDataForSerialization (Isolate * isolate, bool clear_recompilable_data) [static]
Definition at line 221 of file snapshot.cc.
                                                    {
  // Clear SFIs and JSRegExps.
  PtrComprCageBase cage_base(isolate);
  {
    HandleScope scope(isolate);
    std::vector<i::Handle<i::SharedFunctionInfo>> sfis_to_clear;
    {
      i::HeapObjectIterator it(isolate->heap());
      for (i::Tagged<i::HeapObject> o = it.Next(); !o.is_null();
           o = it.Next()) {
        if (clear_recompilable_data && IsSharedFunctionInfo(o, cage_base)) {
          i::Tagged<i::SharedFunctionInfo> shared =
              i::Cast<i::SharedFunctionInfo>(o);
          if (IsScript(shared->script(cage_base), cage_base) &&
              Cast<Script>(shared->script(cage_base))->type() ==
                  Script::Type::kExtension) {
            continue; // Don't clear extensions, they cannot be recompiled.
          }
          if (shared->CanDiscardCompiled()) {
            sfis_to_clear.emplace_back(shared, isolate);
          }
        } else if (IsJSRegExp(o, cage_base)) {
          i::Tagged<i::JSRegExp> regexp = i::Cast<i::JSRegExp>(o);
          if (regexp->has_data()) {
            i::Tagged<i::RegExpData> data = regexp->data(isolate);
            if (data->HasCompiledCode()) {
              DCHECK(Is<IrRegExpData>(regexp->data(isolate)));
              Cast<IrRegExpData>(data)->DiscardCompiledCodeForSerialization();
            }
          }
        }
      }
    }
#if V8_ENABLE_WEBASSEMBLY
    // Clear the cached js-to-wasm wrappers.
    isolate->heap()->SetJSToWasmWrappers(
        ReadOnlyRoots(isolate).empty_weak_fixed_array());
#endif // V8_ENABLE_WEBASSEMBLY
    // Must happen after heap iteration since SFI::DiscardCompiled may allocate.
    for (i::DirectHandle<i::SharedFunctionInfo> shared : sfis_to_clear) {
      if (shared->CanDiscardCompiled()) {
        i::SharedFunctionInfo::DiscardCompiled(isolate, shared);
      }
    }
  }
  // Clear JSFunctions.
  {
    i::HeapObjectIterator it(isolate->heap());
    for (i::Tagged<i::HeapObject> o = it.Next(); !o.is_null(); o = it.Next()) {
      if (!IsJSFunction(o, cage_base)) continue;
      i::Tagged<i::JSFunction> fun = i::Cast<i::JSFunction>(o);
      fun->CompleteInobjectSlackTrackingIfActive(isolate);
      i::Tagged<i::SharedFunctionInfo> shared = fun->shared();
      if (IsScript(shared->script(cage_base), cage_base) &&
          Cast<Script>(shared->script(cage_base))->type() ==
              Script::Type::kExtension) {
        continue; // Don't clear extensions, they cannot be recompiled.
      }
      // Also, clear out feedback vectors and recompilable code.
      if (fun->CanDiscardCompiled(isolate)) {
        fun->UpdateCode(isolate, *BUILTIN_CODE(isolate, CompileLazy));
      }
      if (!IsUndefined(fun->raw_feedback_cell(cage_base)->value(cage_base))) {
        fun->raw_feedback_cell(cage_base)->set_value(
            i::ReadOnlyRoots(isolate).undefined_value());
      }
#ifdef DEBUG
      if (clear_recompilable_data) {
        DCHECK(fun->shared()->HasBuiltinId() ||
               fun->shared()->IsApiFunction() ||
#if V8_ENABLE_WEBASSEMBLY
               fun->shared()->HasWasmExportedFunctionData(isolate) ||
#endif // V8_ENABLE_WEBASSEMBLY
               fun->shared()->HasUncompiledDataWithoutPreparseData(isolate));
      }
#endif // DEBUG
    }
  }
  // PendingOptimizeTable also contains BytecodeArray, we need to clear the
  // recompilable code same as above.
  ReadOnlyRoots roots(isolate);
  isolate->heap()->SetFunctionsMarkedForManualOptimization(
      roots.undefined_value());
#if V8_ENABLE_WEBASSEMBLY
  {
    // Check if there are any asm.js / wasm functions on the heap.
    // These cannot be serialized due to restrictions with the js-to-wasm
    // wrapper. A tiered-up wrapper would have to be replaced with a generic
    // wrapper which isn't supported. For asm.js there also isn't any support
    // for the generic wrapper at all.
    i::HeapObjectIterator it(isolate->heap(),
                             HeapObjectIterator::kFilterUnreachable);
    for (i::Tagged<i::HeapObject> o = it.Next(); !o.is_null(); o = it.Next()) {
      if (IsJSFunction(o)) {
        i::Tagged<i::JSFunction> fun = i::Cast<i::JSFunction>(o);
        if (fun->shared()->HasAsmWasmData()) {
          FATAL("asm.js functions are not supported in snapshots");
        }
        if (fun->shared()->HasWasmExportedFunctionData(isolate)) {
          FATAL(
              "Exported WebAssembly functions are not supported in snapshots");
        }
      }
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
}
References BUILTIN_CODE, v8::internal::wasm::CompileLazy(), v8::internal::DCHECK(), v8::internal::SharedFunctionInfo::DiscardCompiled(), FATAL, v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Script::kExtension, v8::internal::HeapObjectIterator::kFilterUnreachable, v8::internal::HeapObjectIterator::Next(), and v8::internal::Heap::SetFunctionsMarkedForManualOptimization().
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob(), and v8::Shell::RunMain().
Create()
v8::StartupData v8::internal::Snapshot::Create (Isolate * isolate, std::vector< Tagged< Context >> * contexts, const std::vector< SerializeEmbedderFieldsCallback > & embedder_fields_serializers, const SafepointScope & safepoint_scope, const DisallowGarbageCollection & no_gc, SerializerFlags flags = kDefaultSerializerFlags) [static]
Definition at line 403 of file snapshot.cc.
                                                                   {
  TRACE_EVENT0("v8", "V8.SnapshotCreate");
  DCHECK_EQ(contexts->size(), embedder_fields_serializers.size());
  DCHECK_GT(contexts->size(), 0);
  HandleScope scope(isolate);
  ReadOnlySerializer read_only_serializer(isolate, flags);
  read_only_serializer.Serialize();
  // TODO(v8:6593): generalize rehashing, and remove this flag.
  bool can_be_rehashed = read_only_serializer.can_be_rehashed();
  SharedHeapSerializer shared_heap_serializer(isolate, flags);
  StartupSerializer startup_serializer(isolate, flags, &shared_heap_serializer);
  startup_serializer.SerializeStrongReferences(no_gc);
  // Serialize each context with a new serializer.
  const int num_contexts = static_cast<int>(contexts->size());
  std::vector<SnapshotData*> context_snapshots;
  context_snapshots.reserve(num_contexts);
  std::vector<int> context_allocation_sizes;
  for (int i = 0; i < num_contexts; i++) {
    ContextSerializer context_serializer(isolate, flags, &startup_serializer,
                                         embedder_fields_serializers[i]);
    context_serializer.Serialize(&contexts->at(i), no_gc);
    can_be_rehashed = can_be_rehashed && context_serializer.can_be_rehashed();
    context_snapshots.push_back(new SnapshotData(&context_serializer));
    if (v8_flags.serialization_statistics) {
      context_allocation_sizes.push_back(
          context_serializer.TotalAllocationSize());
    }
  }
  startup_serializer.SerializeWeakReferencesAndDeferred();
  can_be_rehashed = can_be_rehashed && startup_serializer.can_be_rehashed();
  startup_serializer.CheckNoDirtyFinalizationRegistries();
  shared_heap_serializer.FinalizeSerialization();
  can_be_rehashed = can_be_rehashed && shared_heap_serializer.can_be_rehashed();
  if (v8_flags.serialization_statistics) {
    DCHECK_NE(read_only_serializer.TotalAllocationSize(), 0);
    DCHECK_NE(startup_serializer.TotalAllocationSize(), 0);
    // The shared heap snapshot can be empty, no problem.
    // DCHECK_NE(shared_heap_serializer.TotalAllocationSize(), 0);
    int per_isolate_allocation_size = startup_serializer.TotalAllocationSize();
    int per_process_allocation_size =
        read_only_serializer.TotalAllocationSize();
    // TODO(jgruber): At snapshot-generation time we don't know whether the
    // shared heap snapshot will actually be shared at runtime, or if it will
    // be deserialized into each isolate. Conservatively account to per-isolate
    // memory here.
    per_isolate_allocation_size += shared_heap_serializer.TotalAllocationSize();
    // These prints must match the regexp in test/memory/Memory.json
    PrintF("Deserialization will allocate:\n");
    PrintF("%10d bytes per process\n", per_process_allocation_size);
    PrintF("%10d bytes per isolate\n", per_isolate_allocation_size);
    for (int i = 0; i < num_contexts; i++) {
      DCHECK_NE(context_allocation_sizes[i], 0);
      PrintF("%10d bytes per context #%d\n", context_allocation_sizes[i], i);
    }
    PrintF("\n");
  }
  SnapshotData read_only_snapshot(&read_only_serializer);
  SnapshotData shared_heap_snapshot(&shared_heap_serializer);
  SnapshotData startup_snapshot(&startup_serializer);
  v8::StartupData result = SnapshotImpl::CreateSnapshotBlob(
      &startup_snapshot, &read_only_snapshot, &shared_heap_snapshot,
      context_snapshots, can_be_rehashed);
  for (const SnapshotData* ptr : context_snapshots) delete ptr;
  CHECK(Snapshot::VerifyChecksum(&result));
  return result;
}
References v8::internal::ContextSerializer::can_be_rehashed(), v8::internal::RootsSerializer::can_be_rehashed(), CHECK, v8::internal::StartupSerializer::CheckNoDirtyFinalizationRegistries(), DCHECK_EQ, DCHECK_GT, DCHECK_NE, v8::internal::SharedHeapSerializer::FinalizeSerialization(), v8::internal::flags, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), v8::base::internal::result, v8::internal::ReadOnlySerializer::Serialize(), v8::internal::ContextSerializer::Serialize(), v8::internal::StartupSerializer::SerializeStrongReferences(), v8::internal::StartupSerializer::SerializeWeakReferencesAndDeferred(), v8::internal::Serializer::TotalAllocationSize(), TRACE_EVENT0, v8::internal::v8_flags, and VerifyChecksum().
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob(), and SerializeDeserializeAndVerifyForTesting().
DefaultSnapshotBlob()
const v8::StartupData * v8::internal::Snapshot::DefaultSnapshotBlob () [static]
Definition at line 24 of file snapshot-empty.cc.
{ return nullptr; }
Referenced by v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers(), v8::Isolate::Initialize(), and v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl().
EmbedsScript()
static bool v8::internal::Snapshot::EmbedsScript (Isolate * isolate) [static]
ExtractReadOnlySnapshotChecksum()
uint32_t v8::internal::Snapshot::ExtractReadOnlySnapshotChecksum (const v8::StartupData * data) [static]
Definition at line 671 of file snapshot.cc.
                               {
  return SnapshotImpl::GetHeaderValue(
      data, SnapshotImpl::kReadOnlySnapshotChecksumOffset);
}
Referenced by v8::internal::SerializedCodeData::FromCachedData(), v8::internal::SerializedCodeData::FromCachedDataWithoutSource(), and v8::internal::SerializedCodeData::SerializedCodeData().
ExtractRehashability()
bool v8::internal::Snapshot::ExtractRehashability (const v8::StartupData * data) [static]
Definition at line 663 of file snapshot.cc.
                                                             {
  uint32_t rehashability =
      SnapshotImpl::GetHeaderValue(data, SnapshotImpl::kRehashabilityOffset);
  CHECK_IMPLIES(rehashability != 0, rehashability == 1);
  return rehashability != 0;
}
References CHECK_IMPLIES.
Referenced by v8::StartupData::CanBeRehashed(), Initialize(), and NewContextFromSnapshot().
GetExpectedChecksum()
uint32_t v8::internal::Snapshot::GetExpectedChecksum (const v8::StartupData * data) [static]
Definition at line 634 of file snapshot.cc.
                                                                {
  return SnapshotImpl::GetHeaderValue(data, SnapshotImpl::kChecksumOffset);
}
Referenced by v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers(), and VerifyChecksum().
HasContextSnapshot()
bool v8::internal::Snapshot::HasContextSnapshot (Isolate * isolate, size_t index) [static]
Definition at line 154 of file snapshot.cc.
                                                                {
  // Do not use snapshots if the isolate is used to create snapshots.
  const v8::StartupData* blob = isolate->snapshot_blob();
  if (blob == nullptr) return false;
  if (blob->data == nullptr) return false;
  size_t num_contexts =
      static_cast<size_t>(SnapshotImpl::ExtractNumContexts(blob));
  return index < num_contexts;
}
References v8::StartupData::data, and v8::internal::index.
Referenced by v8::Context::FromSnapshot().
Initialize()
bool v8::internal::Snapshot::Initialize (Isolate * isolate) [static]
Definition at line 176 of file snapshot.cc.
                                          {
  if (!isolate->snapshot_available()) return false;
  const v8::StartupData* blob = isolate->snapshot_blob();
  SnapshotImpl::CheckVersion(blob);
  if (Snapshot::ShouldVerifyChecksum(blob)) {
    CHECK(VerifyChecksum(blob));
  }
  base::Vector<const uint8_t> startup_data =
      SnapshotImpl::ExtractStartupData(blob);
  base::Vector<const uint8_t> read_only_data =
      SnapshotImpl::ExtractReadOnlyData(blob);
  base::Vector<const uint8_t> shared_heap_data =
      SnapshotImpl::ExtractSharedHeapData(blob);
  SnapshotData startup_snapshot_data(MaybeDecompress(isolate, startup_data));
  SnapshotData read_only_snapshot_data(
      MaybeDecompress(isolate, read_only_data));
  SnapshotData shared_heap_snapshot_data(
      MaybeDecompress(isolate, shared_heap_data));
  return isolate->InitWithSnapshot(
      &startup_snapshot_data, &read_only_snapshot_data,
      &shared_heap_snapshot_data, ExtractRehashability(blob));
}
References CHECK, ExtractRehashability(), v8::internal::Isolate::InitWithSnapshot(), v8::internal::MaybeDecompress(), ShouldVerifyChecksum(), v8::internal::Isolate::snapshot_available(), and VerifyChecksum().
Referenced by v8::Isolate::Initialize(), v8::internal::SnapshotCreatorImpl::InitInternal(), and SerializeDeserializeAndVerifyForTesting().
NewContextFromSnapshot()
MaybeDirectHandle< Context > v8::internal::Snapshot::NewContextFromSnapshot (Isolate * isolate, DirectHandle< JSGlobalProxy > global_proxy, size_t context_index, DeserializeEmbedderFieldsCallback embedder_fields_deserializer) [static]
Definition at line 203 of file snapshot.cc.
                                                                    {
  if (!isolate->snapshot_available()) return DirectHandle<Context>();
  const v8::StartupData* blob = isolate->snapshot_blob();
  bool can_rehash = ExtractRehashability(blob);
  base::Vector<const uint8_t> context_data = SnapshotImpl::ExtractContextData(
      blob, static_cast<uint32_t>(context_index));
  SnapshotData snapshot_data(MaybeDecompress(isolate, context_data));
  return ContextDeserializer::DeserializeContext(
      isolate, &snapshot_data, context_index, can_rehash, global_proxy,
      embedder_fields_deserializer);
}
References v8::internal::ContextDeserializer::DeserializeContext(), ExtractRehashability(), v8::internal::MaybeDecompress(), and v8::internal::Isolate::snapshot_available().
Referenced by v8::internal::Genesis::Genesis().
SerializeDeserializeAndVerifyForTesting()
void v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting (Isolate * isolate, DirectHandle< Context > default_context) [static]
Definition at line 340 of file snapshot.cc.
                                                             {
  StartupData serialized_data;
  std::unique_ptr<const char[]> auto_delete_serialized_data;
  isolate->heap()->CollectAllAvailableGarbage(
      i::GarbageCollectionReason::kSnapshotCreator);
  // Test serialization.
  {
    SafepointKind safepoint_kind = isolate->has_shared_space()
                                       ? SafepointKind::kGlobal
                                       : SafepointKind::kIsolate;
    SafepointScope safepoint_scope(isolate, safepoint_kind);
    DisallowGarbageCollection no_gc;
    Snapshot::SerializerFlags flags(
        Snapshot::kAllowUnknownExternalReferencesForTesting |
        Snapshot::kAllowActiveIsolateForTesting |
        Snapshot::kReconstructReadOnlyAndSharedObjectCachesForTesting);
    std::vector<Tagged<Context>> contexts{*default_context};
    std::vector<SerializeEmbedderFieldsCallback> callbacks{
        SerializeEmbedderFieldsCallback()};
    serialized_data = Snapshot::Create(isolate, &contexts, callbacks,
                                       safepoint_scope, no_gc, flags);
    auto_delete_serialized_data.reset(serialized_data.data);
  }
  // The shared heap is verified on Heap teardown, which performs a global
  // safepoint. Both isolate and new_isolate are running in the same thread, so
  // park isolate before running new_isolate to avoid deadlock.
  isolate->main_thread_local_isolate()->ExecuteMainThreadWhileParked(
      [&serialized_data]() {
        // Test deserialization.
        Isolate* new_isolate = Isolate::New();
        std::unique_ptr<v8::ArrayBuffer::Allocator> array_buffer_allocator(
            v8::ArrayBuffer::Allocator::NewDefaultAllocator());
        {
          // Set serializer_enabled() to not install extensions and experimental
          // natives on the new isolate.
          // TODO(v8:10416): This should be a separate setting on the isolate.
          new_isolate->enable_serializer();
          new_isolate->Enter();
          new_isolate->set_snapshot_blob(&serialized_data);
          new_isolate->set_array_buffer_allocator(array_buffer_allocator.get());
          CHECK(Snapshot::Initialize(new_isolate));
          HandleScope scope(new_isolate);
          DirectHandle<Context> new_native_context =
              new_isolate->bootstrapper()->CreateEnvironmentForTesting();
          CHECK(IsNativeContext(*new_native_context));
#ifdef VERIFY_HEAP
          if (v8_flags.verify_heap)
            HeapVerifier::VerifyHeap(new_isolate->heap());
#endif // VERIFY_HEAP
        }
        new_isolate->Exit();
        Isolate::Delete(new_isolate);
      });
}
References v8::internal::Isolate::bootstrapper(), CHECK, v8::internal::Heap::CollectAllAvailableGarbage(), Create(), v8::internal::Bootstrapper::CreateEnvironmentForTesting(), v8::StartupData::data, v8::internal::Isolate::Delete(), v8::internal::Isolate::enable_serializer(), v8::internal::Isolate::Enter(), v8::internal::LocalIsolate::ExecuteMainThreadWhileParked(), v8::internal::Isolate::Exit(), v8::internal::flags, v8::internal::Isolate::has_shared_space(), v8::internal::Isolate::heap(), Initialize(), kAllowActiveIsolateForTesting, kAllowUnknownExternalReferencesForTesting, v8::internal::kGlobal, v8::internal::kIsolate, kReconstructReadOnlyAndSharedObjectCachesForTesting, v8::internal::Isolate::main_thread_local_isolate(), v8::internal::Isolate::New(), v8::ArrayBuffer::Allocator::NewDefaultAllocator(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Isolate::set_array_buffer_allocator(), v8::internal::v8_flags, and v8::internal::HeapVerifier::VerifyHeap().
Referenced by v8::Shell::RunMain(), and v8::internal::RUNTIME_FUNCTION().
ShouldVerifyChecksum()
bool v8::internal::Snapshot::ShouldVerifyChecksum (const v8::StartupData * data) [static]
Definition at line 25 of file snapshot-empty.cc.
                                                             {
  return false;
}
Referenced by Initialize().
VerifyChecksum()
bool v8::internal::Snapshot::VerifyChecksum (const v8::StartupData * data) [static]
Definition at line 641 of file snapshot.cc.
                                                       {
  base::ElapsedTimer timer;
  if (v8_flags.profile_deserialization) timer.Start();
  uint32_t expected = GetExpectedChecksum(data);
  uint32_t result = CalculateChecksum(data);
  if (v8_flags.profile_deserialization) {
    double ms = timer.Elapsed().InMillisecondsF();
    PrintF("[Verifying snapshot checksum took %0.3f ms]\n", ms);
  }
  return result == expected;
}
References CalculateChecksum(), v8::base::ElapsedTimer::Elapsed(), GetExpectedChecksum(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::PrintF(), v8::base::internal::result, v8::base::ElapsedTimer::Start(), and v8::internal::v8_flags.
Referenced by v8::StartupData::CanBeRehashed(), Create(), and Initialize().
VersionIsValid()
bool v8::internal::Snapshot::VersionIsValid (const v8::StartupData * data) [static]
Definition at line 164 of file snapshot.cc.
                                                       {
  char version[SnapshotImpl::kVersionStringLength];
  memset(version, 0, SnapshotImpl::kVersionStringLength);
  CHECK_LT(
      SnapshotImpl::kVersionStringOffset + SnapshotImpl::kVersionStringLength,
      static_cast<uint32_t>(data->raw_size));
  Version::GetString(
      base::Vector<char>(version, SnapshotImpl::kVersionStringLength));
  return strncmp(version, data->data + SnapshotImpl::kVersionStringOffset,
                 SnapshotImpl::kVersionStringLength) == 0;
}
References CHECK_LT, v8::StartupData::data, v8::internal::Version::GetString(), and v8::StartupData::raw_size.
Referenced by v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::CheckVersion(), and v8::StartupData::IsValid().
Member Data Documentation
kDefaultSerializerFlags
constexpr V8_EXPORT_PRIVATE SerializerFlags v8::internal::Snapshot::kDefaultSerializerFlags [static], [constexpr]
Initial value:
=
      {}
Definition at line 57 of file snapshot.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/snapshot.h
/mnt/V8SourceCode/src/snapshot/snapshot-empty.cc
/mnt/V8SourceCode/src/snapshot/snapshot-external.cc
/mnt/V8SourceCode/src/snapshot/snapshot.cc