v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally Class Reference
Public Member Functions
ControlScopeForTryFinally (BytecodeGenerator *generator, TryFinallyBuilder *try_finally_builder, DeferredCommands *commands)
Protected Member Functions
bool Execute (Command command, Statement *statement, int source_position) override
Private Attributes
TryFinallyBuilder * try_finally_builder_
DeferredCommands * commands_
Additional Inherited Members
Detailed Description
Definition at line 536 of file bytecode-generator.cc.
Constructor & Destructor Documentation
ControlScopeForTryFinally()
v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally::ControlScopeForTryFinally (BytecodeGenerator * generator, TryFinallyBuilder * try_finally_builder, DeferredCommands * commands) [inline]
Definition at line 539 of file bytecode-generator.cc.
      : ControlScope(generator),
        try_finally_builder_(try_finally_builder),
        commands_(commands) {}
Member Function Documentation
Execute()
bool v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally::Execute (Command command, Statement * statement, int source_position) [inline], [override], [protected], [virtual]
Implements v8::internal::interpreter::BytecodeGenerator::ControlScope.
Definition at line 547 of file bytecode-generator.cc.
                                             {
    switch (command) {
      case CMD_BREAK:
      case CMD_CONTINUE:
      case CMD_RETURN:
      case CMD_ASYNC_RETURN:
      case CMD_RETHROW:
        PopContextToExpectedDepth();
        // We don't record source_position here since we don't generate return
        // bytecode right here and will generate it later as part of finally
        // block. Each return bytecode generated in finally block will get own
        // return source position from corresponded return statement or we'll
        // use end of function if no return statement is presented.
        commands_->RecordCommand(command, statement);
        try_finally_builder_->LeaveTry();
        return true;
    }
    return false;
  }
References v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_ASYNC_RETURN, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_BREAK, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_CONTINUE, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_RETHROW, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_RETURN, commands_, v8::internal::interpreter::TryFinallyBuilder::LeaveTry(), v8::internal::interpreter::BytecodeGenerator::ControlScope::PopContextToExpectedDepth(), v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::RecordCommand(), and try_finally_builder_.
Member Data Documentation
commands_
DeferredCommands* v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally::commands_ [private]
Definition at line 570 of file bytecode-generator.cc.
Referenced by Execute().
try_finally_builder_
TryFinallyBuilder* v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally::try_finally_builder_ [private]
Definition at line 569 of file bytecode-generator.cc.
Referenced by Execute().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc