v8::internal::AccumulationScope< Types > Class Template Reference
#include <expression-scope.h>
Public Types
using ParserT = typename Types::Impl
Public Member Functions
AccumulationScope (ExpressionScope< Types > *scope)
AccumulationScope (const AccumulationScope &)=delete
AccumulationScope & operator= (const AccumulationScope &)=delete
void Accumulate ()
void ValidateExpression ()
~AccumulationScope ()
Static Public Attributes
static const int kNumberOfErrors
Private Member Functions
void copy (int entry)
void copy_back (int entry)
Private Attributes
ExpressionParsingScope< Types > * scope_
MessageTemplate messages_ [2]
Scanner::Location locations_ [2]
Detailed Description
template<typename Types>
class v8::internal::AccumulationScope< Types >
Definition at line 669 of file expression-scope.h.
Member Typedef Documentation
ParserT
template<typename Types >
using v8::internal::AccumulationScope< Types >::ParserT = typename Types::Impl
Definition at line 671 of file expression-scope.h.
Constructor & Destructor Documentation
AccumulationScope() [1/2]
template<typename Types >
v8::internal::AccumulationScope< Types >::AccumulationScope (ExpressionScope< Types > * scope) [inline], [explicit]
Definition at line 675 of file expression-scope.h.
                                                            : scope_(nullptr) {
    if (!scope->CanBeExpression()) return;
    scope_ = scope->AsExpressionParsingScope();
    for (int i = 0; i < kNumberOfErrors; i++) {
      copy(i);
      scope_->clear(i);
    }
  }
References v8::internal::ExpressionScope< Types >::AsExpressionParsingScope(), v8::internal::ExpressionScope< Types >::CanBeExpression(), v8::internal::AccumulationScope< Types >::copy(), v8::internal::AccumulationScope< Types >::kNumberOfErrors, and v8::internal::AccumulationScope< Types >::scope_.
AccumulationScope() [2/2]
template<typename Types >
v8::internal::AccumulationScope< Types >::AccumulationScope (const AccumulationScope< Types > &) [delete]
 AccumulationScope()
template<typename Types >
v8::internal::AccumulationScope< Types >::~AccumulationScope () [inline]
Definition at line 717 of file expression-scope.h.
                       {
    if (scope_ == nullptr) return;
    Accumulate();
    for (int i = 0; i < kNumberOfErrors; i++) copy_back(i);
  }
References v8::internal::AccumulationScope< Types >::Accumulate(), v8::internal::AccumulationScope< Types >::copy_back(), v8::internal::AccumulationScope< Types >::kNumberOfErrors, and v8::internal::AccumulationScope< Types >::scope_.
Member Function Documentation
Accumulate()
template<typename Types >
void v8::internal::AccumulationScope< Types >::Accumulate () [inline]
Definition at line 690 of file expression-scope.h.
                    {
    if (scope_ == nullptr) return;
    DCHECK(!scope_->is_verified());
    for (int i = 0; i < kNumberOfErrors; i++) {
      if (!locations_[i].IsValid()) copy(i);
      scope_->clear(i);
    }
  }
References v8::internal::AccumulationScope< Types >::copy(), v8::internal::DCHECK(), v8::internal::AccumulationScope< Types >::kNumberOfErrors, v8::internal::AccumulationScope< Types >::locations_, and v8::internal::AccumulationScope< Types >::scope_.
Referenced by v8::internal::AccumulationScope< Types >::~AccumulationScope().
copy()
template<typename Types >
void v8::internal::AccumulationScope< Types >::copy (int entry) [inline], [private]
Definition at line 724 of file expression-scope.h.
                       {
    messages_[entry] = scope_->messages_[entry];
    locations_[entry] = scope_->locations_[entry];
  }
References v8::internal::AccumulationScope< Types >::locations_, v8::internal::AccumulationScope< Types >::messages_, and v8::internal::AccumulationScope< Types >::scope_.
Referenced by v8::internal::AccumulationScope< Types >::Accumulate(), and v8::internal::AccumulationScope< Types >::AccumulationScope().
copy_back()
template<typename Types >
void v8::internal::AccumulationScope< Types >::copy_back (int entry) [inline], [private]
Definition at line 729 of file expression-scope.h.
                            {
    if (!locations_[entry].IsValid()) return;
    scope_->messages_[entry] = messages_[entry];
    scope_->locations_[entry] = locations_[entry];
  }
References v8::internal::AccumulationScope< Types >::locations_, v8::internal::AccumulationScope< Types >::messages_, and v8::internal::AccumulationScope< Types >::scope_.
Referenced by v8::internal::AccumulationScope< Types >::~AccumulationScope().
operator=()
template<typename Types >
AccumulationScope& v8::internal::AccumulationScope< Types >::operator= (const AccumulationScope< Types > &) [delete]
ValidateExpression()
template<typename Types >
void v8::internal::AccumulationScope< Types >::ValidateExpression () [inline]
Definition at line 706 of file expression-scope.h.
                            {
    if (scope_ == nullptr) return;
    DCHECK(!scope_->is_verified());
    scope_->ValidateExpression();
    DCHECK(scope_->is_verified());
    scope_->clear(ExpressionParsingScope<Types>::kPatternIndex);
#ifdef DEBUG
    scope_->clear_verified();
#endif
  }
References v8::internal::DCHECK(), and v8::internal::AccumulationScope< Types >::scope_.
Member Data Documentation
kNumberOfErrors
template<typename Types >
const int v8::internal::AccumulationScope< Types >::kNumberOfErrors [static]
Initial value:
=
      ExpressionParsingScope<Types>::kNumberOfErrors
Definition at line 673 of file expression-scope.h.
Referenced by v8::internal::AccumulationScope< Types >::Accumulate(), v8::internal::AccumulationScope< Types >::AccumulationScope(), and v8::internal::AccumulationScope< Types >::~AccumulationScope().
locations_
template<typename Types >
Scanner::Location v8::internal::AccumulationScope< Types >::locations_[2] [private]
Definition at line 737 of file expression-scope.h.
Referenced by v8::internal::AccumulationScope< Types >::Accumulate(), v8::internal::AccumulationScope< Types >::copy(), and v8::internal::AccumulationScope< Types >::copy_back().
messages_
template<typename Types >
MessageTemplate v8::internal::AccumulationScope< Types >::messages_[2] [private]
Definition at line 736 of file expression-scope.h.
Referenced by v8::internal::AccumulationScope< Types >::copy(), and v8::internal::AccumulationScope< Types >::copy_back().
scope_
template<typename Types >
ExpressionParsingScope<Types>* v8::internal::AccumulationScope< Types >::scope_ [private]
Definition at line 735 of file expression-scope.h.
Referenced by v8::internal::AccumulationScope< Types >::Accumulate(), v8::internal::AccumulationScope< Types >::AccumulationScope(), v8::internal::AccumulationScope< Types >::copy(), v8::internal::AccumulationScope< Types >::copy_back(), v8::internal::AccumulationScope< Types >::ValidateExpression(), and v8::internal::AccumulationScope< Types >::~AccumulationScope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/expression-scope.h