v8::internal::maglev::TransitionElementsKindOrCheckMap Class Reference
#include <maglev-ir.h>
Public Member Functions
TransitionElementsKindOrCheckMap (uint64_t bitfield, const ZoneVector< compiler::MapRef > &transition_sources, compiler::MapRef transition_target)
Input & object_input ()
Input & map_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
const ZoneVector< compiler::MapRef > & transition_sources () const
const compiler::MapRef transition_target () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputNodeT< 2, TransitionElementsKindOrCheckMap >
Private Attributes
ZoneVector< compiler::MapRef > transition_sources_
const compiler::MapRef transition_target_
Additional Inherited Members
Detailed Description
Definition at line 11118 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TransitionElementsKindOrCheckMap::Base = FixedInputNodeT<2, TransitionElementsKindOrCheckMap> [private]
Definition at line 11120 of file maglev-ir.h.
Constructor & Destructor Documentation
TransitionElementsKindOrCheckMap()
v8::internal::maglev::TransitionElementsKindOrCheckMap::TransitionElementsKindOrCheckMap (uint64_t bitfield, const ZoneVector< compiler::MapRef > & transition_sources, compiler::MapRef transition_target) [inline], [explicit]
Definition at line 11123 of file maglev-ir.h.
      : Base(bitfield),
        transition_sources_(transition_sources),
        transition_target_(transition_target) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::TransitionElementsKindOrCheckMap::GenerateCode (MaglevAssembler * , const ProcessingState &)
map_input()
Input& v8::internal::maglev::TransitionElementsKindOrCheckMap::map_input () [inline]
Definition at line 11138 of file maglev-ir.h.
{ return Node::input(1); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::TransitionElementsKindOrCheckMap::MaxCallStackArgs () const
object_input()
Input& v8::internal::maglev::TransitionElementsKindOrCheckMap::object_input () [inline]
Definition at line 11137 of file maglev-ir.h.
{ return Node::input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::TransitionElementsKindOrCheckMap::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8074 of file maglev-ir.cc.
                                                               {
  os << "(" << Node::input(0).node() << ", [";
  os << *transition_target().object();
  for (compiler::MapRef source : transition_sources()) {
    os << ", " << *source.object();
  }
  os << "]-->" << *transition_target().object() << ")";
}
References v8::internal::maglev::NodeBase::input(), v8::internal::maglev::Input::node(), v8::internal::compiler::MapRef::object(), transition_sources(), and transition_target().
SetValueLocationConstraints()
void v8::internal::maglev::TransitionElementsKindOrCheckMap::SetValueLocationConstraints ()
transition_sources()
const ZoneVector<compiler::MapRef>& v8::internal::maglev::TransitionElementsKindOrCheckMap::transition_sources () const [inline]
Definition at line 11145 of file maglev-ir.h.
                                                               {
    return transition_sources_;
  }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
transition_target()
const compiler::MapRef v8::internal::maglev::TransitionElementsKindOrCheckMap::transition_target () const [inline]
Definition at line 11148 of file maglev-ir.h.
                                                 {
    return transition_target_;
  }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::TransitionElementsKindOrCheckMap::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 11134 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::TransitionElementsKindOrCheckMap::kProperties [static], [constexpr]
Initial value:
= OpProperties::AnySideEffects() |
                                              OpProperties::DeferredCall() |
                                              OpProperties::EagerDeopt()
Definition at line 11131 of file maglev-ir.h.
transition_sources_
ZoneVector<compiler::MapRef> v8::internal::maglev::TransitionElementsKindOrCheckMap::transition_sources_ [private]
Definition at line 11153 of file maglev-ir.h.
transition_target_
const compiler::MapRef v8::internal::maglev::TransitionElementsKindOrCheckMap::transition_target_ [private]
Definition at line 11154 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc