v8::internal::compiler::CodeAssemblerParameterizedLabel< Types > Class Template Reference
#include <code-assembler.h>
Public Member Functions
CodeAssemblerParameterizedLabel (CodeAssembler *assembler, CodeAssemblerLabel::Type type)
Static Public Attributes
static constexpr size_t kArity = sizeof...(Types)
Private Member Functions
void AddInputsVector (std::vector< Node * > inputs)
void AddInputs (TNode< Types >... inputs)
void CreatePhis (TNode< Types > *... results)
Static Private Member Functions
template<class T >
static void AssignPhi (TNode< T > *result, Node *phi)
Friends
class CodeAssembler
Additional Inherited Members
Detailed Description
template<class... Types>
class v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >
Definition at line 1842 of file code-assembler.h.
Constructor & Destructor Documentation
CodeAssemblerParameterizedLabel()
template<class... Types>
v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::CodeAssemblerParameterizedLabel (CodeAssembler * assembler, CodeAssemblerLabel::Type type) [inline], [explicit]
Definition at line 1846 of file code-assembler.h.
      : CodeAssemblerParameterizedLabelBase(assembler, kArity, type) {}
Member Function Documentation
AddInputs()
template<class... Types>
void v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AddInputs (TNode< Types >... inputs) [inline], [private]
Definition at line 1856 of file code-assembler.h.
                                         {
    CodeAssemblerParameterizedLabelBase::AddInputs(
        std::vector<Node*>{inputs...});
  }
References v8::internal::compiler::CodeAssemblerParameterizedLabelBase::AddInputs().
Referenced by v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::Goto(), and v8::internal::compiler::CodeAssembler::HandleException().
AddInputsVector()
template<class... Types>
void v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AddInputsVector (std::vector< Node * > inputs) [inline], [private]
Definition at line 1853 of file code-assembler.h.
                                                {
    CodeAssemblerParameterizedLabelBase::AddInputs(std::move(inputs));
  }
References v8::internal::compiler::CodeAssemblerParameterizedLabelBase::AddInputs().
Referenced by v8::internal::compiler::CodeAssembler::Branch().
AssignPhi()
template<class... Types>
template<class T >
static void v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AssignPhi (TNode< T > * result, Node * phi) [inline], [static], [private]
Definition at line 1869 of file code-assembler.h.
                                                     {
    if (phi != nullptr) *result = TNode<T>::UncheckedCast(phi);
  }
References v8::base::internal::result, and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::CreatePhis().
CreatePhis()
template<class... Types>
void v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::CreatePhis (TNode< Types > *... results) [inline], [private]
Definition at line 1860 of file code-assembler.h.
                                            {
    const std::vector<Node*>& phi_nodes =
        CodeAssemblerParameterizedLabelBase::CreatePhis(
            {PhiMachineRepresentationOf<Types>...});
    auto it = phi_nodes.begin();
    USE(it);
    (AssignPhi(results, *(it++)), ...);
  }
References v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AssignPhi(), v8::internal::compiler::CodeAssemblerParameterizedLabelBase::CreatePhis(), and USE.
Referenced by v8::internal::compiler::CodeAssembler::Bind().
Friends And Related Function Documentation
CodeAssembler
template<class... Types>
friend class CodeAssembler [friend]
Definition at line 1851 of file code-assembler.h.
Member Data Documentation
kArity
template<class... Types>
constexpr size_t v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::kArity = sizeof...(Types) [static], [constexpr]
Definition at line 1845 of file code-assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/code-assembler.h