v8::internal::MaterializedLiteral Class Reference
#include <ast.h>
Public Member Functions
bool IsSimple () const
Protected Member Functions
MaterializedLiteral (int pos, NodeType type)
bool NeedsInitialAllocationSite ()
Friends
class CompileTimeValue
class LiteralBoilerplateBuilder
class ArrayLiteralBoilerplateBuilder
class ObjectLiteralBoilerplateBuilder
Additional Inherited Members
Detailed Description
Definition at line 1080 of file ast.h.
Constructor & Destructor Documentation
MaterializedLiteral()
v8::internal::MaterializedLiteral::MaterializedLiteral (int pos, NodeType type) [inline], [protected]
Definition at line 1087 of file ast.h.
: Expression(pos, type) {}
Member Function Documentation
IsSimple()
bool v8::internal::MaterializedLiteral::IsSimple () const
Definition at line 760 of file ast.cc.
                                         {
  if (IsArrayLiteral()) return AsArrayLiteral()->builder()->is_simple();
  if (IsObjectLiteral()) return AsObjectLiteral()->builder()->is_simple();
  DCHECK(IsRegExpLiteral());
  return false;
}
References v8::internal::DCHECK().
Referenced by v8::internal::Expression::IsCompileTimeValue().
NeedsInitialAllocationSite()
bool v8::internal::MaterializedLiteral::NeedsInitialAllocationSite () [protected]
Definition at line 778 of file ast.cc.
  {
  if (IsArrayLiteral()) {
    return AsArrayLiteral()->builder()->needs_initial_allocation_site();
  }
  if (IsObjectLiteral()) {
    return AsObjectLiteral()->builder()->needs_initial_allocation_site();
  }
  DCHECK(IsRegExpLiteral());
  return false;
}
References v8::internal::DCHECK().
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags().
Friends And Related Function Documentation
ArrayLiteralBoilerplateBuilder
friend class ArrayLiteralBoilerplateBuilder [friend]
Definition at line 1094 of file ast.h.
CompileTimeValue
friend class CompileTimeValue [friend]
Definition at line 1091 of file ast.h.
LiteralBoilerplateBuilder
friend class LiteralBoilerplateBuilder [friend]
Definition at line 1093 of file ast.h.
ObjectLiteralBoilerplateBuilder
friend class ObjectLiteralBoilerplateBuilder [friend]
Definition at line 1095 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc