v8::internal::YoungGenerationRememberedSetsMarkingWorklist Class Reference
#include <minor-mark-sweep.h>
Classes
class Local
class MarkingItem
Public Member Functions
YoungGenerationRememberedSetsMarkingWorklist (Heap *heap)
~YoungGenerationRememberedSetsMarkingWorklist ()
size_t RemainingRememberedSetsMarkingIteams () const
void TearDown ()
Static Public Member Functions
static std::vector< MarkingItem > CollectItems (Heap *heap)
Private Member Functions
template<typename Visitor >
bool ProcessNextItem (Visitor *visitor, std::optional< size_t > &index)
Private Attributes
std::vector< MarkingItem > remembered_sets_marking_items_
std::atomic_size_t remaining_remembered_sets_marking_items_
IndexGenerator remembered_sets_marking_index_generator_
Detailed Description
Definition at line 33 of file minor-mark-sweep.h.
Constructor & Destructor Documentation
YoungGenerationRememberedSetsMarkingWorklist()
v8::internal::YoungGenerationRememberedSetsMarkingWorklist::YoungGenerationRememberedSetsMarkingWorklist (Heap * heap) [explicit]
Definition at line 249 of file minor-mark-sweep.cc.
    : remembered_sets_marking_items_(CollectItems(heap)),
      remaining_remembered_sets_marking_items_(
          remembered_sets_marking_items_.size()),
      remembered_sets_marking_index_generator_(
          remembered_sets_marking_items_.size()) {}
 YoungGenerationRememberedSetsMarkingWorklist()
v8::internal::YoungGenerationRememberedSetsMarkingWorklist::~YoungGenerationRememberedSetsMarkingWorklist ()
Definition at line 257 of file minor-mark-sweep.cc.
                                                    {
  for (MarkingItem item : remembered_sets_marking_items_) {
    if (v8_flags.sticky_mark_bits) {
      item.DeleteRememberedSets();
    } else {
      item.MergeAndDeleteRememberedSets();
    }
  }
}
References remembered_sets_marking_items_, and v8::internal::v8_flags.
Member Function Documentation
CollectItems()
std::vector< YoungGenerationRememberedSetsMarkingWorklist::MarkingItem > v8::internal::YoungGenerationRememberedSetsMarkingWorklist::CollectItems (Heap * heap) [static]
Definition at line 180 of file minor-mark-sweep.cc.
                                                                     {
  std::vector<MarkingItem> items;
  int max_remembered_set_count = EstimateMaxNumberOfRemeberedSets(heap);
  items.reserve(max_remembered_set_count);
  OldGenerationMemoryChunkIterator::ForAll(
      heap, [&items](MutablePageMetadata* chunk) {
        SlotSet* slot_set = chunk->ExtractSlotSet<OLD_TO_NEW>();
        SlotSet* background_slot_set =
            chunk->ExtractSlotSet<OLD_TO_NEW_BACKGROUND>();
        if (slot_set || background_slot_set) {
          items.emplace_back(chunk, MarkingItem::SlotsType::kRegularSlots,
                             slot_set, background_slot_set);
        }
        if (TypedSlotSet* typed_slot_set =
                chunk->ExtractTypedSlotSet<OLD_TO_NEW>()) {
          DCHECK(IsAnyCodeSpace(chunk->owner_identity()));
          items.emplace_back(chunk, MarkingItem::SlotsType::kTypedSlots,
                             typed_slot_set);
        }
      });
  DCHECK_LE(items.size(), max_remembered_set_count);
  return items;
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::anonymous_namespace{minor-mark-sweep.cc}::EstimateMaxNumberOfRemeberedSets(), v8::internal::MutablePageMetadata::ExtractSlotSet(), v8::internal::MutablePageMetadata::ExtractTypedSlotSet(), v8::internal::OldGenerationMemoryChunkIterator::ForAll(), v8::internal::IsAnyCodeSpace(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::kRegularSlots, v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::kTypedSlots, v8::internal::OLD_TO_NEW, v8::internal::OLD_TO_NEW_BACKGROUND, and v8::internal::MutablePageMetadata::owner_identity().
ProcessNextItem()
template<typename Visitor >
bool v8::internal::YoungGenerationRememberedSetsMarkingWorklist::ProcessNextItem (Visitor * visitor, std::optional< size_t > & index) [private]
Definition at line 62 of file minor-mark-sweep-inl.h.
                                                  {
  if (remaining_remembered_sets_marking_items_.load(
          std::memory_order_relaxed) == 0) {
    return false;
  }
  while (true) {
    if (index && (index < remembered_sets_marking_items_.size())) {
      auto& work_item = remembered_sets_marking_items_[*index];
      if (work_item.TryAcquire()) {
        remaining_remembered_sets_marking_items_.fetch_sub(
            1, std::memory_order_relaxed);
        work_item.Process(visitor);
        (*index)++;
        return true;
      }
    }
    index = remembered_sets_marking_index_generator_.GetNext();
    if (!index) return false;
  }
}
References v8::internal::IndexGenerator::GetNext(), v8::internal::index, remaining_remembered_sets_marking_items_, remembered_sets_marking_index_generator_, and remembered_sets_marking_items_.
Referenced by v8::internal::YoungGenerationRememberedSetsMarkingWorklist::Local::ProcessNextItem().
RemainingRememberedSetsMarkingIteams()
size_t v8::internal::YoungGenerationRememberedSetsMarkingWorklist::RemainingRememberedSetsMarkingIteams () const [inline]
Definition at line 58 of file minor-mark-sweep.h.
                                                      {
    return remaining_remembered_sets_marking_items_.load(
        std::memory_order_relaxed);
  }
References remaining_remembered_sets_marking_items_.
Referenced by v8::internal::ConcurrentMarking::GetMinorMaxConcurrency(), and v8::internal::ConcurrentMarking::IsWorkLeft().
TearDown()
void v8::internal::YoungGenerationRememberedSetsMarkingWorklist::TearDown ()
Definition at line 268 of file minor-mark-sweep.cc.
                                                            {
  for (MarkingItem& item : remembered_sets_marking_items_) {
    item.DeleteSetsOnTearDown();
  }
  remembered_sets_marking_items_.clear();
  remaining_remembered_sets_marking_items_.store(0, std::memory_order_relaxed);
}
References remaining_remembered_sets_marking_items_, and remembered_sets_marking_items_.
Member Data Documentation
remaining_remembered_sets_marking_items_
std::atomic_size_t v8::internal::YoungGenerationRememberedSetsMarkingWorklist::remaining_remembered_sets_marking_items_ [private]
Definition at line 114 of file minor-mark-sweep.h.
Referenced by ProcessNextItem(), RemainingRememberedSetsMarkingIteams(), and TearDown().
remembered_sets_marking_index_generator_
IndexGenerator v8::internal::YoungGenerationRememberedSetsMarkingWorklist::remembered_sets_marking_index_generator_ [private]
Definition at line 115 of file minor-mark-sweep.h.
Referenced by ProcessNextItem().
remembered_sets_marking_items_
std::vector<MarkingItem> v8::internal::YoungGenerationRememberedSetsMarkingWorklist::remembered_sets_marking_items_ [private]
Definition at line 113 of file minor-mark-sweep.h.
Referenced by ProcessNextItem(), TearDown(), and ~YoungGenerationRememberedSetsMarkingWorklist().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/minor-mark-sweep.h
/mnt/V8SourceCode/src/heap/minor-mark-sweep-inl.h
/mnt/V8SourceCode/src/heap/minor-mark-sweep.cc