v8::internal::DebugStackTraceIterator Class Reference
#include <debug-stack-trace-iterator.h>
Public Member Functions
DebugStackTraceIterator (Isolate *isolate, int index)
~DebugStackTraceIterator () override
bool Done () const override
void Advance () override
int GetContextId () const override
v8::MaybeLocal< v8::Value > GetReceiver () const override
v8::Local< v8::Value > GetReturnValue () const override
v8::Local< v8::String > GetFunctionDebugName () const override
v8::Local< v8::debug::Script > GetScript () const override
debug::Location GetSourceLocation () const override
debug::Location GetFunctionLocation () const override
v8::Local< v8::Function > GetFunction () const override
std::unique_ptr< v8::debug::ScopeIterator > GetScopeIterator () const override
bool CanBeRestarted () const override
v8::MaybeLocal< v8::Value > Evaluate (v8::Local< v8::String > source, bool throw_on_side_effect) override
void PrepareRestart ()
Handle< SharedFunctionInfo > GetSharedFunctionInfo () const
Private Member Functions
void UpdateInlineFrameIndexAndResumableFnOnStack ()
Private Attributes
Isolate * isolate_
DebuggableStackFrameIterator iterator_
std::unique_ptr< FrameInspector > frame_inspector_
int inlined_frame_index_
bool is_top_frame_
bool resumable_fn_on_stack_
Additional Inherited Members
Detailed Description
Definition at line 17 of file debug-stack-trace-iterator.h.
Constructor & Destructor Documentation
DebugStackTraceIterator()
v8::internal::DebugStackTraceIterator::DebugStackTraceIterator (Isolate * isolate, int index)
Definition at line 31 of file debug-stack-trace-iterator.cc.
    : isolate_(isolate),
      iterator_(isolate, isolate->debug()->break_frame_id()),
      is_top_frame_(true),
      resumable_fn_on_stack_(false) {
  if (iterator_.done()) return;
  UpdateInlineFrameIndexAndResumableFnOnStack();
  Advance();
  for (; !Done() && index > 0; --index) Advance();
}
References Advance(), v8::internal::DebuggableStackFrameIterator::done(), Done(), v8::internal::index, iterator_, and UpdateInlineFrameIndexAndResumableFnOnStack().
 DebugStackTraceIterator()
v8::internal::DebugStackTraceIterator::~DebugStackTraceIterator () [override], [default]
Member Function Documentation
Advance()
void v8::internal::DebugStackTraceIterator::Advance () [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 46 of file debug-stack-trace-iterator.cc.
                                      {
  while (true) {
    --inlined_frame_index_;
    for (; inlined_frame_index_ >= 0; --inlined_frame_index_) {
      // Omit functions from native and extension scripts.
      if (FrameSummary::Get(iterator_.frame(), inlined_frame_index_)
              .is_subject_to_debugging()) {
        break;
      }
      is_top_frame_ = false;
    }
    if (inlined_frame_index_ >= 0) {
      frame_inspector_.reset(new FrameInspector(
          iterator_.frame(), inlined_frame_index_, isolate_));
      break;
    }
    is_top_frame_ = false;
    frame_inspector_.reset();
    iterator_.Advance();
    if (iterator_.done()) break;
    UpdateInlineFrameIndexAndResumableFnOnStack();
  }
}
References v8::internal::DebuggableStackFrameIterator::Advance(), v8::internal::DebuggableStackFrameIterator::done(), v8::internal::DebuggableStackFrameIterator::frame(), frame_inspector_, v8::internal::FrameSummary::Get(), inlined_frame_index_, v8::internal::FrameSummary::is_subject_to_debugging(), is_top_frame_, isolate_, iterator_, and UpdateInlineFrameIndexAndResumableFnOnStack().
Referenced by DebugStackTraceIterator().
CanBeRestarted()
bool v8::internal::DebugStackTraceIterator::CanBeRestarted () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 214 of file debug-stack-trace-iterator.cc.
                                                   {
  DCHECK(!Done());
  if (resumable_fn_on_stack_) return false;
  StackFrame* frame = iterator_.frame();
  // We do not support restarting WASM frames.
#if V8_ENABLE_WEBASSEMBLY
  if (frame->is_wasm()) return false;
#endif // V8_ENABLE_WEBASSEMBLY
  // Check that no embedder API calls are between the top-most frame, and the
  // current frame. While we *could* determine whether embedder
  // frames are safe to terminate (via the CallDepthScope chain), we don't know
  // if embedder frames would cancel the termination effectively breaking
  // restart frame.
  if (isolate_->thread_local_top()->last_api_entry_ < frame->fp()) {
    return false;
  }
  return true;
}
References v8::internal::DCHECK(), Done(), v8::internal::StackFrame::fp(), v8::internal::DebuggableStackFrameIterator::frame(), isolate_, iterator_, v8::internal::ThreadLocalTop::last_api_entry_, resumable_fn_on_stack_, and v8::internal::Isolate::thread_local_top().
Referenced by PrepareRestart(), and v8::debug::PrepareRestartFrame().
Done()
bool v8::internal::DebugStackTraceIterator::Done () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 44 of file debug-stack-trace-iterator.cc.
{ return iterator_.done(); }
References v8::internal::DebuggableStackFrameIterator::done(), and iterator_.
Referenced by CanBeRestarted(), DebugStackTraceIterator(), Evaluate(), GetContextId(), GetFunction(), GetFunctionDebugName(), GetFunctionLocation(), GetReceiver(), GetReturnValue(), GetScopeIterator(), GetScript(), GetSharedFunctionInfo(), GetSourceLocation(), PrepareRestart(), v8::debug::PrepareRestartFrame(), and v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::VisitCurrentThread().
Evaluate()
v8::MaybeLocal< v8::Value > v8::internal::DebugStackTraceIterator::Evaluate (v8::Local< v8::String > source, bool throw_on_side_effect) [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 258 of file debug-stack-trace-iterator.cc.
                                                         {
  DCHECK(!Done());
  DirectHandle<Object> value;
  i::SafeForInterruptsScope safe_for_interrupt_scope(isolate_);
  if (!DebugEvaluate::Local(
           isolate_, iterator_.frame()->id(), inlined_frame_index_,
           Utils::OpenDirectHandle(*source), throw_on_side_effect)
           .ToHandle(&value)) {
    return v8::MaybeLocal<v8::Value>();
  }
  return Utils::ToLocal(value);
}
References v8::internal::DCHECK(), Done(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::StackFrame::id(), inlined_frame_index_, isolate_, iterator_, v8::internal::DebugEvaluate::Local(), v8::Utils::OpenDirectHandle(), and v8::internal::value.
GetContextId()
int v8::internal::DebugStackTraceIterator::GetContextId () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 70 of file debug-stack-trace-iterator.cc.
                                                {
  DCHECK(!Done());
  DirectHandle<Object> context = frame_inspector_->GetContext();
  if (IsContext(*context)) {
    Tagged<Object> value =
        Cast<Context>(*context)->native_context()->debug_context_id();
    if (IsSmi(value)) return Smi::ToInt(value);
  }
  return 0;
}
References v8::internal::DCHECK(), Done(), frame_inspector_, v8::internal::IsSmi(), v8::internal::Smi::ToInt(), and v8::internal::value.
GetFunction()
v8::Local< v8::Function > v8::internal::DebugStackTraceIterator::GetFunction () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 181 of file debug-stack-trace-iterator.cc.
                                                               {
  DCHECK(!Done());
  if (!frame_inspector_->IsJavaScript()) return v8::Local<v8::Function>();
  return Utils::ToLocal(frame_inspector_->GetFunction());
}
References v8::internal::DCHECK(), Done(), and frame_inspector_.
Referenced by GetFunctionLocation().
GetFunctionDebugName()
v8::Local< v8::String > v8::internal::DebugStackTraceIterator::GetFunctionDebugName () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 134 of file debug-stack-trace-iterator.cc.
                                                                      {
  DCHECK(!Done());
  return Utils::ToLocal(frame_inspector_->GetFunctionName());
}
References v8::internal::DCHECK(), Done(), and frame_inspector_.
GetFunctionLocation()
debug::Location v8::internal::DebugStackTraceIterator::GetFunctionLocation () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 153 of file debug-stack-trace-iterator.cc.
                                                                 {
  DCHECK(!Done());
  v8::Local<v8::Function> func = this->GetFunction();
  if (!func.IsEmpty()) {
    return v8::debug::Location(func->GetScriptLineNumber(),
                               func->GetScriptColumnNumber());
  }
#if V8_ENABLE_WEBASSEMBLY
#if V8_ENABLE_DRUMBRAKE
  if (iterator_.frame()->is_wasm_interpreter_entry()) {
    auto frame = WasmInterpreterEntryFrame::cast(iterator_.frame());
    Handle<WasmInstanceObject> instance(frame->wasm_instance(), isolate_);
    auto offset =
        instance->module()->functions[frame->function_index(0)].code.offset();
    return v8::debug::Location(inlined_frame_index_, offset);
  }
#endif // V8_ENABLE_DRUMBRAKE
  if (iterator_.frame()->is_wasm()) {
    auto frame = WasmFrame::cast(iterator_.frame());
    const wasm::WasmModule* module = frame->trusted_instance_data()->module();
    auto offset = module->functions[frame->function_index()].code.offset();
    return v8::debug::Location(0, offset);
  }
#endif
  return v8::debug::Location();
}
References v8::internal::DCHECK(), Done(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::wasm::WasmModule::functions, GetFunction(), inlined_frame_index_, v8::api_internal::IndirectHandleBase::IsEmpty(), isolate_, and iterator_.
GetReceiver()
v8::MaybeLocal< v8::Value > v8::internal::DebugStackTraceIterator::GetReceiver () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 81 of file debug-stack-trace-iterator.cc.
                                                                 {
  DCHECK(!Done());
  if (frame_inspector_->IsJavaScript() &&
      frame_inspector_->GetFunction()->shared()->kind() ==
          FunctionKind::kArrowFunction) {
    // FrameInspector is not able to get receiver for arrow function.
    // So let's try to fetch it using same logic as is used to retrieve 'this'
    // during DebugEvaluate::Local.
    DirectHandle<JSFunction> function = frame_inspector_->GetFunction();
    DirectHandle<Context> context(function->context(), isolate_);
    // Arrow function defined in top level function without references to
    // variables may have NativeContext as context.
    if (!context->IsFunctionContext()) return v8::MaybeLocal<v8::Value>();
    ScopeIterator scope_iterator(
        isolate_, frame_inspector_.get(),
        ScopeIterator::ReparseStrategy::kFunctionLiteral);
    // We lookup this variable in function context only when it is used in arrow
    // function otherwise V8 can optimize it out.
    if (!scope_iterator.ClosureScopeHasThisReference()) {
      return v8::MaybeLocal<v8::Value>();
    }
    DisallowGarbageCollection no_gc;
    int slot_index = context->scope_info()->ContextSlotIndex(
        *isolate_->factory()->this_string());
    if (slot_index < 0) return v8::MaybeLocal<v8::Value>();
    DirectHandle<Object> value(context->GetNoCell(slot_index), isolate_);
    if (IsTheHole(*value, isolate_)) return v8::MaybeLocal<v8::Value>();
    return Utils::ToLocal(value);
  }
  DirectHandle<Object> value = frame_inspector_->GetReceiver();
  if (value.is_null() || (IsSmi(*value) || !IsTheHole(*value, isolate_))) {
    return Utils::ToLocal(value);
  }
  return v8::MaybeLocal<v8::Value>();
}
References v8::internal::ScopeIterator::ClosureScopeHasThisReference(), v8::internal::DCHECK(), Done(), v8::internal::Isolate::factory(), frame_inspector_, isolate_, v8::internal::IsSmi(), v8::internal::kArrowFunction, v8::internal::ScopeIterator::kFunctionLiteral, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
GetReturnValue()
v8::Local< v8::Value > v8::internal::DebugStackTraceIterator::GetReturnValue () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 118 of file debug-stack-trace-iterator.cc.
                                                               {
  CHECK(!Done());
#if V8_ENABLE_WEBASSEMBLY
  if (frame_inspector_ && frame_inspector_->IsWasm()) {
    return v8::Local<v8::Value>();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  CHECK_NOT_NULL(iterator_.frame());
  bool is_optimized = iterator_.frame()->is_optimized_js();
  if (is_optimized || !is_top_frame_ ||
      !isolate_->debug()->IsBreakAtReturn(iterator_.javascript_frame())) {
    return v8::Local<v8::Value>();
  }
  return Utils::ToLocal(isolate_->debug()->return_value_handle());
}
References CHECK, CHECK_NOT_NULL, v8::internal::Isolate::debug(), Done(), v8::internal::DebuggableStackFrameIterator::frame(), frame_inspector_, v8::internal::StackFrame::is_optimized_js(), is_top_frame_, v8::internal::Debug::IsBreakAtReturn(), isolate_, iterator_, v8::internal::DebuggableStackFrameIterator::javascript_frame(), and v8::internal::Debug::return_value_handle().
GetScopeIterator()
std::unique_ptr< v8::debug::ScopeIterator > v8::internal::DebugStackTraceIterator::GetScopeIterator () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 195 of file debug-stack-trace-iterator.cc.
                                                {
  DCHECK(!Done());
#if V8_ENABLE_WEBASSEMBLY
#if V8_ENABLE_DRUMBRAKE
  if (iterator_.frame()->is_wasm_interpreter_entry()) {
    return GetWasmInterpreterScopeIterator(
        WasmInterpreterEntryFrame::cast(iterator_.frame()));
  } else {
#endif // V8_ENABLE_DRUMBRAKE
    if (iterator_.frame()->is_wasm()) {
      return GetWasmScopeIterator(WasmFrame::cast(iterator_.frame()));
    }
#if V8_ENABLE_DRUMBRAKE
  }
#endif // V8_ENABLE_DRUMBRAKE
#endif // V8_ENABLE_WEBASSEMBLY
  return std::make_unique<DebugScopeIterator>(isolate_, frame_inspector_.get());
}
References v8::internal::DCHECK(), Done(), v8::internal::DebuggableStackFrameIterator::frame(), frame_inspector_, v8::internal::GetWasmScopeIterator(), isolate_, and iterator_.
GetScript()
v8::Local< v8::debug::Script > v8::internal::DebugStackTraceIterator::GetScript () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 139 of file debug-stack-trace-iterator.cc.
                                                                {
  DCHECK(!Done());
  DirectHandle<Object> value = frame_inspector_->GetScript();
  if (!IsScript(*value)) return v8::Local<v8::debug::Script>();
  return ToApiHandle<debug::Script>(Cast<Script>(value));
}
References v8::internal::DCHECK(), Done(), frame_inspector_, and v8::internal::value.
Referenced by GetSourceLocation().
GetSharedFunctionInfo()
Handle< SharedFunctionInfo > v8::internal::DebugStackTraceIterator::GetSharedFunctionInfo () const
Definition at line 187 of file debug-stack-trace-iterator.cc.
          {
  DCHECK(!Done());
  if (!frame_inspector_->IsJavaScript()) return Handle<SharedFunctionInfo>();
  return handle(frame_inspector_->GetFunction()->shared(), isolate_);
}
References v8::internal::DCHECK(), Done(), frame_inspector_, v8::internal::handle(), and isolate_.
GetSourceLocation()
debug::Location v8::internal::DebugStackTraceIterator::GetSourceLocation () const [override], [virtual]
Implements v8::debug::StackTraceIterator.
Definition at line 146 of file debug-stack-trace-iterator.cc.
                                                               {
  DCHECK(!Done());
  v8::Local<v8::debug::Script> script = GetScript();
  if (script.IsEmpty()) return v8::debug::Location();
  return script->GetSourceLocation(frame_inspector_->GetSourcePosition());
}
References v8::internal::DCHECK(), Done(), frame_inspector_, GetScript(), and v8::internal::script.
PrepareRestart()
void v8::internal::DebugStackTraceIterator::PrepareRestart ()
Definition at line 273 of file debug-stack-trace-iterator.cc.
                                             {
  CHECK(!Done());
  CHECK(CanBeRestarted());
  isolate_->debug()->PrepareRestartFrame(iterator_.javascript_frame(),
                                         inlined_frame_index_);
}
References CanBeRestarted(), CHECK, v8::internal::Isolate::debug(), Done(), inlined_frame_index_, isolate_, iterator_, v8::internal::DebuggableStackFrameIterator::javascript_frame(), and v8::internal::Debug::PrepareRestartFrame().
Referenced by v8::debug::PrepareRestartFrame().
UpdateInlineFrameIndexAndResumableFnOnStack()
void v8::internal::DebugStackTraceIterator::UpdateInlineFrameIndexAndResumableFnOnStack () [private]
Definition at line 237 of file debug-stack-trace-iterator.cc.
                                                                          {
  CHECK(!iterator_.done());
  FrameSummaries summaries = iterator_.frame()->Summarize();
  inlined_frame_index_ = static_cast<int>(summaries.size());
  if (resumable_fn_on_stack_) return;
  StackFrame* frame = iterator_.frame();
  if (!frame->is_javascript()) return;
  std::vector<Handle<SharedFunctionInfo>> shareds;
  JavaScriptFrame::cast(frame)->GetFunctions(&shareds);
  for (auto& shared : shareds) {
    if (IsResumableFunction(shared->kind())) {
      resumable_fn_on_stack_ = true;
      return;
    }
  }
}
References v8::internal::JavaScriptFrame::cast(), CHECK, v8::internal::DebuggableStackFrameIterator::done(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::JavaScriptFrame::GetFunctions(), inlined_frame_index_, v8::internal::StackFrame::is_javascript(), v8::internal::IsResumableFunction(), iterator_, resumable_fn_on_stack_, v8::internal::FrameSummaries::size(), and v8::internal::CommonFrame::Summarize().
Referenced by Advance(), and DebugStackTraceIterator().
Member Data Documentation
frame_inspector_
std::unique_ptr<FrameInspector> v8::internal::DebugStackTraceIterator::frame_inspector_ [private]
Definition at line 47 of file debug-stack-trace-iterator.h.
Referenced by Advance(), GetContextId(), GetFunction(), GetFunctionDebugName(), GetReceiver(), GetReturnValue(), GetScopeIterator(), GetScript(), GetSharedFunctionInfo(), and GetSourceLocation().
inlined_frame_index_
int v8::internal::DebugStackTraceIterator::inlined_frame_index_ [private]
Definition at line 48 of file debug-stack-trace-iterator.h.
Referenced by Advance(), Evaluate(), GetFunctionLocation(), PrepareRestart(), and UpdateInlineFrameIndexAndResumableFnOnStack().
is_top_frame_
bool v8::internal::DebugStackTraceIterator::is_top_frame_ [private]
Definition at line 49 of file debug-stack-trace-iterator.h.
Referenced by Advance(), and GetReturnValue().
isolate_
Isolate* v8::internal::DebugStackTraceIterator::isolate_ [private]
Definition at line 45 of file debug-stack-trace-iterator.h.
Referenced by Advance(), CanBeRestarted(), Evaluate(), GetFunctionLocation(), GetReceiver(), GetReturnValue(), GetScopeIterator(), GetSharedFunctionInfo(), and PrepareRestart().
iterator_
DebuggableStackFrameIterator v8::internal::DebugStackTraceIterator::iterator_ [private]
Definition at line 46 of file debug-stack-trace-iterator.h.
Referenced by Advance(), CanBeRestarted(), DebugStackTraceIterator(), Done(), Evaluate(), GetFunctionLocation(), GetReturnValue(), GetScopeIterator(), PrepareRestart(), and UpdateInlineFrameIndexAndResumableFnOnStack().
resumable_fn_on_stack_
bool v8::internal::DebugStackTraceIterator::resumable_fn_on_stack_ [private]
Definition at line 50 of file debug-stack-trace-iterator.h.
Referenced by CanBeRestarted(), and UpdateInlineFrameIndexAndResumableFnOnStack().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-stack-trace-iterator.h
/mnt/V8SourceCode/src/debug/debug-stack-trace-iterator.cc