v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder Class Reference
Classes
class ModifyThreadInWasmFlagScope
Public Member Functions
WasmWrapperGraphBuilder (Zone *zone, MachineGraph *mcgraph, const wasm::CanonicalSig *sig, ParameterMode parameter_mode, Isolate *isolate, compiler::SourcePositionTable *spt)
Node * BuildCallAndReturn (Node *js_context, Node *function_data, base::SmallVector< Node *, 16 > args, Node *frame_state, bool set_in_wasm_flag)
void BuildJSToWasmWrapper (Node *frame_state, bool set_in_wasm_flag)
Node * BuildReceiverNode (Node *callable_node, Node *native_context, Node *undefined_node)
template<typename... Args>
Node * BuildCCall (MachineSignature *sig, Node *function, Args... args)
Node * BuildSwitchToTheCentralStack ()
void BuildSwitchBackFromCentralStack (Node *old_sp)
Node * BuildSwitchToTheCentralStackIfNeeded ()
void BuildJSFastApiCallWrapper (DirectHandle< JSReceiver > callable)
void BuildCWasmEntry ()
Private Attributes
SetOncePointer< const Operator > int32_to_heapnumber_operator_
SetOncePointer< const Operator > tagged_non_smi_to_int32_operator_
SetOncePointer< const Operator > float32_to_number_operator_
SetOncePointer< const Operator > float64_to_number_operator_
SetOncePointer< const Operator > tagged_to_float64_operator_
Additional Inherited Members
Detailed Description
Definition at line 664 of file wasm-compiler.cc.
Constructor & Destructor Documentation
WasmWrapperGraphBuilder()
v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::WasmWrapperGraphBuilder (Zone * zone, MachineGraph * mcgraph, const wasm::CanonicalSig * sig, ParameterMode parameter_mode, Isolate * isolate, compiler::SourcePositionTable * spt) [inline]
Definition at line 666 of file wasm-compiler.cc.
      : WasmGraphBuilder(nullptr, zone, mcgraph, nullptr, spt, parameter_mode,
                         isolate, wasm::WasmEnabledFeatures::All(), sig) {}
Member Function Documentation
BuildCallAndReturn()
Node* v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCallAndReturn (Node * js_context, Node * function_data, base::SmallVector< Node *, 16 > args, Node * frame_state, bool set_in_wasm_flag) [inline]
Definition at line 704 of file wasm-compiler.cc.
                                                  {
    const int rets_count = static_cast<int>(wrapper_sig_->return_count());
    base::SmallVector<Node*, 1> rets(rets_count);
    // Set the ThreadInWasm flag before we do the actual call.
    {
      std::optional<ModifyThreadInWasmFlagScope>
          modify_thread_in_wasm_flag_builder;
      if (set_in_wasm_flag) {
        modify_thread_in_wasm_flag_builder.emplace(this, gasm_.get());
      }
      // Call to an import or a wasm function defined in this module.
      // The (cached) call target is the jump table slot for that function.
      // We do not use the imports dispatch table here so that the wrapper is
      // target independent, in particular for tier-up.
      Node* internal = gasm_->LoadImmutableProtectedPointerFromObject(
          function_data, wasm::ObjectAccess::ToTagged(
                             WasmFunctionData::kProtectedInternalOffset));
      args[0] = gasm_->LoadFromObject(
          MachineType::Uint32(), internal,
          wasm::ObjectAccess::ToTagged(
              WasmInternalFunction::kRawCallTargetOffset));
      Node* implicit_arg = gasm_->LoadImmutableProtectedPointerFromObject(
          internal, wasm::ObjectAccess::ToTagged(
                        WasmInternalFunction::kProtectedImplicitArgOffset));
      BuildWasmCall(wrapper_sig_, base::VectorOf(args), base::VectorOf(rets),
                    wasm::kNoCodePosition, implicit_arg, true, frame_state);
    }
    Node* jsval;
    if (wrapper_sig_->return_count() == 0) {
      jsval = UndefinedValue();
    } else if (wrapper_sig_->return_count() == 1) {
      jsval = rets[0];
    } else {
      UNREACHABLE();
    }
    return jsval;
  }
References v8::base::args, v8::internal::wasm::kNoCodePosition, v8::internal::wasm::ObjectAccess::ToTagged(), v8::internal::MachineType::Uint32(), v8::internal::UNREACHABLE(), and v8::base::VectorOf().
BuildCCall()
template<typename... Args>
Node* v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCCall (MachineSignature * sig, Node * function, Args... args) [inline]
Definition at line 852 of file wasm-compiler.cc.
                                                                        {
    DCHECK_LE(sig->return_count(), 1);
    DCHECK_EQ(sizeof...(args), sig->parameter_count());
    Node* call_args[] = {function, args..., effect(), control()};
    auto call_descriptor =
        Linkage::GetSimplifiedCDescriptor(mcgraph()->zone(), sig);
    return gasm_->Call(call_descriptor, arraysize(call_args), call_args);
  }
References v8::base::args, arraysize, DCHECK_EQ, DCHECK_LE, v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), and v8::internal::sig.
BuildCWasmEntry()
void v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCWasmEntry () [inline]
Definition at line 1016 of file wasm-compiler.cc.
                         {
    // +1 offset for first parameter index being -1.
    Start(CWasmEntryParameters::kNumParameters + 1);
    Node* code_entry = Param(CWasmEntryParameters::kCodeEntry);
    Node* object_ref = Param(CWasmEntryParameters::kObjectRef);
    Node* arg_buffer = Param(CWasmEntryParameters::kArgumentsBuffer);
    Node* c_entry_fp = Param(CWasmEntryParameters::kCEntryFp);
    Node* fp_value = graph()->NewNode(mcgraph()->machine()->LoadFramePointer());
    gasm_->Store(StoreRepresentation(MachineType::PointerRepresentation(),
                                     kNoWriteBarrier),
                 fp_value, TypedFrameConstants::kFirstPushedFrameValueOffset,
                 c_entry_fp);
    int wasm_arg_count = static_cast<int>(wrapper_sig_->parameter_count());
    base::SmallVector<Node*, 16> args(wasm_arg_count + 4);
    int pos = 0;
    args[pos++] = code_entry;
    args[pos++] = gasm_->LoadTrustedDataFromInstanceObject(object_ref);
    int offset = 0;
    for (wasm::CanonicalValueType type : wrapper_sig_->parameters()) {
      Node* arg_load = SetEffect(
          graph()->NewNode(GetSafeLoadOperator(offset, type), arg_buffer,
                           Int32Constant(offset), effect(), control()));
      args[pos++] = arg_load;
      offset += type.value_kind_size();
    }
    args[pos++] = effect();
    args[pos++] = control();
    // Call the wasm code.
    auto call_descriptor = GetWasmCallDescriptor(
        mcgraph()->zone(), wrapper_sig_, WasmCallKind::kWasmIndirectFunction);
    DCHECK_EQ(pos, args.size());
    Node* call = gasm_->Call(call_descriptor, pos, args.begin());
    Node* if_success = graph()->NewNode(mcgraph()->common()->IfSuccess(), call);
    Node* if_exception =
        graph()->NewNode(mcgraph()->common()->IfException(), call, call);
    // Handle exception: return it.
    SetEffectControl(if_exception);
    Return(if_exception);
    // Handle success: store the return value(s).
    SetEffectControl(call, if_success);
    pos = 0;
    offset = 0;
    for (wasm::CanonicalValueType type : wrapper_sig_->returns()) {
      Node* value = wrapper_sig_->return_count() == 1
                        ? call
                        : graph()->NewNode(mcgraph()->common()->Projection(pos),
                                           call, control());
      SetEffect(
          BuildSafeStore(offset, type, arg_buffer, value, effect(), control()));
      offset += type.value_kind_size();
      pos++;
    }
    Return(mcgraph()->IntPtrConstant(0));
    if (mcgraph()->machine()->Is32() && ContainsInt64(wrapper_sig_)) {
      // These correspond to {sig_types[]} in {CompileCWasmEntry}.
      MachineRepresentation sig_reps[] = {
          MachineType::PointerRepresentation(), // return value
          MachineType::PointerRepresentation(), // target
          MachineRepresentation::kTagged, // object_ref
          MachineType::PointerRepresentation(), // argv
          MachineType::PointerRepresentation() // c_entry_fp
      };
      Signature<MachineRepresentation> c_entry_sig(1, 4, sig_reps);
      Int64Lowering r(mcgraph()->graph(), mcgraph()->machine(),
                      mcgraph()->common(), gasm_->simplified(),
                      mcgraph()->zone(), &c_entry_sig);
      r.LowerGraph();
    }
  }
References v8::base::args, v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::ContainsInt64(), DCHECK_EQ, v8::internal::compiler::GetWasmCallDescriptor(), graph(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::kArgumentsBuffer, v8::internal::compiler::kCEntryFp, v8::internal::compiler::kCodeEntry, v8::internal::TypedFrameConstants::kFirstPushedFrameValueOffset, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kNumParameters, v8::internal::compiler::kObjectRef, v8::internal::kTagged, v8::internal::compiler::kWasmIndirectFunction, v8::internal::compiler::Int64Lowering::LowerGraph(), v8::internal::MachineType::PointerRepresentation(), v8::internal::tracing::type, and v8::internal::value.
BuildJSFastApiCallWrapper()
void v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper (DirectHandle< JSReceiver > callable) [inline]
Definition at line 911 of file wasm-compiler.cc.
                                                                    {
    // Here 'callable_node' must be equal to 'callable' but we cannot pass a
    // HeapConstant(callable) because WasmCode::Validate() fails with
    // Unexpected mode: FULL_EMBEDDED_OBJECT.
    Node* callable_node = gasm_->Load(
        MachineType::TaggedPointer(), Param(0),
        wasm::ObjectAccess::ToTagged(WasmImportData::kCallableOffset));
    Node* native_context = gasm_->Load(
        MachineType::TaggedPointer(), Param(0),
        wasm::ObjectAccess::ToTagged(WasmImportData::kNativeContextOffset));
    gasm_->Store(StoreRepresentation(mcgraph_->machine()->Is64()
                                         ? MachineRepresentation::kWord64
                                         : MachineRepresentation::kWord32,
                                     WriteBarrierKind::kNoWriteBarrier),
                 gasm_->LoadRootRegister(), Isolate::context_offset(),
                 gasm_->BitcastMaybeObjectToWord(native_context));
    Node* undefined_node = UndefinedValue();
    BuildModifyThreadInWasmFlag(false);
    DirectHandle<JSFunction> target;
    Node* target_node;
    Node* receiver_node;
    Isolate* isolate = Isolate::Current();
    if (IsJSBoundFunction(*callable)) {
      target = direct_handle(
          Cast<JSFunction>(
              Cast<JSBoundFunction>(callable)->bound_target_function()),
          isolate);
      target_node =
          gasm_->Load(MachineType::TaggedPointer(), callable_node,
                      wasm::ObjectAccess::ToTagged(
                          JSBoundFunction::kBoundTargetFunctionOffset));
      receiver_node = gasm_->Load(
          MachineType::TaggedPointer(), callable_node,
          wasm::ObjectAccess::ToTagged(JSBoundFunction::kBoundThisOffset));
    } else {
      DCHECK(IsJSFunction(*callable));
      target = Cast<JSFunction>(callable);
      target_node = callable_node;
      receiver_node =
          BuildReceiverNode(callable_node, native_context, undefined_node);
    }
    Tagged<SharedFunctionInfo> shared = target->shared();
    Tagged<FunctionTemplateInfo> api_func_data = shared->api_func_data();
    const Address c_address = api_func_data->GetCFunction(isolate, 0);
    const v8::CFunctionInfo* c_signature =
        api_func_data->GetCSignature(isolate, 0);
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
    Address c_functions[] = {c_address};
    const v8::CFunctionInfo* const c_signatures[] = {c_signature};
    isolate->simulator_data()->RegisterFunctionsAndSignatures(c_functions,
                                                              c_signatures, 1);
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
    Node* shared_function_info = gasm_->LoadSharedFunctionInfo(target_node);
    Node* function_template_info =
        gasm_->Load(MachineType::TaggedPointer(), shared_function_info,
                    wasm::ObjectAccess::ToTagged(
                        SharedFunctionInfo::kUntrustedFunctionDataOffset));
    Node* api_data_argument =
        gasm_->Load(MachineType::TaggedPointer(), function_template_info,
                    wasm::ObjectAccess::ToTagged(
                        FunctionTemplateInfo::kCallbackDataOffset));
    FastApiCallFunction c_function{c_address, c_signature};
    Node* old_sp = BuildSwitchToTheCentralStackIfNeeded();
    Node* call = fast_api_call::BuildFastApiCall(
        isolate, graph(), gasm_.get(), c_function, api_data_argument,
        // Load and convert parameters passed to C function
        [this, c_signature, receiver_node](
            int param_index,
            GraphAssemblerLabel<0>* /* error label, unused */) {
          if (param_index == 0) {
            return gasm_->AdaptLocalArgument(receiver_node);
          }
          switch (c_signature->ArgumentInfo(param_index).GetType()) {
            case CTypeInfo::Type::kV8Value:
              return gasm_->AdaptLocalArgument(Param(param_index));
            default:
              return Param(param_index);
          }
        },
        // Convert return value (no conversion needed for wasm)
        [](const CFunctionInfo* signature, Node* c_return_value) {
          return c_return_value;
        },
        [](Node* options_stack_slot) {},
        // Generate fallback slow call if fast call fails.
        []() -> Node* {
          // This is not needed because the error label (see the lambda above)
          // is not used.
          UNREACHABLE();
        });
    BuildSwitchBackFromCentralStack(old_sp);
    BuildModifyThreadInWasmFlag(true);
    Return(call);
  }
References v8::CFunctionInfo::ArgumentInfo(), v8::internal::compiler::fast_api_call::BuildFastApiCall(), v8::internal::Isolate::context_offset(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::CTypeInfo::GetType(), graph(), v8::internal::compiler::kNoWriteBarrier, v8::internal::kWord32, v8::internal::kWord64, v8::internal::native_context, v8::internal::MachineType::TaggedPointer(), and v8::internal::wasm::ObjectAccess::ToTagged().
BuildJSToWasmWrapper()
void v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSToWasmWrapper (Node * frame_state, bool set_in_wasm_flag) [inline]
Definition at line 747 of file wasm-compiler.cc.
                                                                      {
    const int wasm_param_count =
        static_cast<int>(wrapper_sig_->parameter_count());
    // Build the start and the JS parameter nodes.
    // TODO(saelo): this should probably be a constant with a descriptive name.
    // As far as I understand, it's the number of additional parameters in the
    // JS calling convention. Also there should be a static_assert here that it
    // matches the number of parameters in the JSTrampolineDescriptor?
    // static_assert
    Start(wasm_param_count + 6);
    // Create the js_closure and js_context parameters.
    Node* js_closure = Param(Linkage::kJSCallClosureParamIndex, "%closure");
    Node* js_context = Param(
        Linkage::GetJSCallContextParamIndex(wasm_param_count + 1), "%context");
    Node* function_data = gasm_->LoadFunctionDataFromJSFunction(js_closure);
    if (!wasm::IsJSCompatibleSignature(wrapper_sig_)) {
      // Throw a TypeError. Use the js_context of the calling javascript
      // function (passed as a parameter), such that the generated code is
      // js_context independent.
      BuildCallToRuntimeWithContext(Runtime::kWasmThrowJSTypeError, js_context,
                                    nullptr, 0);
      TerminateThrow(effect(), control());
      return;
    }
#if V8_ENABLE_DRUMBRAKE
    if (v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms &&
        !v8_flags.wasm_jitless) {
      Node* runtime_call = BuildCallToRuntimeWithContext(
          Runtime::kWasmTraceBeginExecution, js_context, nullptr, 0);
      SetControl(runtime_call);
    }
#endif // V8_ENABLE_DRUMBRAKE
    const int args_count = wasm_param_count + 1; // +1 for wasm_code.
    // Prepare Param() nodes. Param() nodes can only be created once,
    // so we need to use the same nodes along all possible transformation paths.
    base::SmallVector<Node*, 16> params(args_count);
    for (int i = 0; i < wasm_param_count; ++i) {
      params[i] = Param(i + 1); // Skip the receiver.
    }
    auto done = gasm_->MakeLabel(MachineRepresentation::kTagged);
    // Convert JS parameters to wasm numbers using the default transformation
    // and build the call.
    base::SmallVector<Node*, 16> args(args_count);
    for (int i = 0; i < wasm_param_count; ++i) {
      Node* wasm_param = params[i];
      // For Float32 parameters
      // we set UseInfo::CheckedNumberOrOddballAsFloat64 in
      // simplified-lowering and we need to add here a conversion from Float64
      // to Float32.
      if (wrapper_sig_->GetParam(i).kind() == wasm::kF32) {
        wasm_param = gasm_->TruncateFloat64ToFloat32(wasm_param);
      }
      args[i + 1] = wasm_param;
    }
    Node* jsval = BuildCallAndReturn(js_context, function_data, args,
                                     frame_state, set_in_wasm_flag);
#if V8_ENABLE_DRUMBRAKE
    if (v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms &&
        !v8_flags.wasm_jitless) {
      Node* runtime_call = BuildCallToRuntimeWithContext(
          Runtime::kWasmTraceEndExecution, js_context, nullptr, 0);
      SetControl(runtime_call);
    }
#endif // V8_ENABLE_DRUMBRAKE
    Return(jsval);
    if (ContainsInt64(wrapper_sig_)) LowerInt64(wasm::kCalledFromJS);
  }
References v8::base::args, v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::ContainsInt64(), v8::internal::compiler::Linkage::GetJSCallContextParamIndex(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::IsJSCompatibleSignature(), v8::internal::compiler::Linkage::kJSCallClosureParamIndex, v8::internal::kTagged, and v8::internal::v8_flags.
BuildReceiverNode()
Node* v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildReceiverNode (Node * callable_node, Node * native_context, Node * undefined_node) [inline]
Definition at line 827 of file wasm-compiler.cc.
                                                {
    // Check function strict bit.
    Node* shared_function_info = gasm_->LoadSharedFunctionInfo(callable_node);
    Node* flags = gasm_->LoadFromObject(
        MachineType::Int32(), shared_function_info,
        wasm::ObjectAccess::FlagsOffsetInSharedFunctionInfo());
    Node* strict_check = gasm_->Word32And(
        flags, Int32Constant(SharedFunctionInfo::IsNativeBit::kMask |
                             SharedFunctionInfo::IsStrictBit::kMask));
    // Load global receiver if sloppy else use undefined.
    Diamond strict_d(graph(), mcgraph()->common(), strict_check,
                     BranchHint::kNone);
    Node* old_effect = effect();
    SetControl(strict_d.if_false);
    Node* global_proxy = gasm_->LoadFixedArrayElementPtr(
        native_context, Context::GLOBAL_PROXY_INDEX);
    SetEffectControl(strict_d.EffectPhi(old_effect, global_proxy),
                     strict_d.merge);
    return strict_d.Phi(MachineRepresentation::kTagged, undefined_node,
                        global_proxy);
  }
References v8::internal::compiler::Diamond::EffectPhi(), v8::internal::flags, v8::internal::wasm::ObjectAccess::FlagsOffsetInSharedFunctionInfo(), graph(), v8::internal::compiler::Diamond::if_false, v8::internal::MachineType::Int32(), v8::internal::kNone, v8::internal::kTagged, v8::internal::compiler::Diamond::merge, v8::internal::native_context, and v8::internal::compiler::Diamond::Phi().
BuildSwitchBackFromCentralStack()
void v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchBackFromCentralStack (Node * old_sp) [inline]
Definition at line 880 of file wasm-compiler.cc.
                                                     {
    auto skip = gasm_->MakeLabel();
    gasm_->GotoIf(gasm_->IntPtrEqual(old_sp, gasm_->IntPtrConstant(0)), &skip);
    Node* do_switch = gasm_->ExternalConstant(
        ExternalReference::wasm_switch_from_the_central_stack_for_js());
    MachineType reps[] = {MachineType::Pointer()};
    MachineSignature sig(0, 1, reps);
    BuildCCall(&sig, do_switch,
               gasm_->ExternalConstant(ExternalReference::isolate_address()));
    gasm_->SetStackPointer(old_sp);
    gasm_->Goto(&skip);
    gasm_->Bind(&skip);
  }
References v8::internal::ExternalReference::isolate_address(), v8::internal::MachineType::Pointer(), and v8::internal::sig.
BuildSwitchToTheCentralStack()
Node* v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchToTheCentralStack () [inline]
Definition at line 863 of file wasm-compiler.cc.
                                       {
    Node* do_switch = gasm_->ExternalConstant(
        ExternalReference::wasm_switch_to_the_central_stack_for_js());
    MachineType reps[] = {MachineType::Pointer(), MachineType::Pointer(),
                          MachineType::Pointer()};
    MachineSignature sig(1, 2, reps);
    Node* central_stack_sp = BuildCCall(
        &sig, do_switch,
        gasm_->ExternalConstant(ExternalReference::isolate_address()),
        gasm_->LoadFramePointer());
    Node* old_sp = gasm_->LoadStackPointer();
    // Temporarily disallow sp-relative offsets.
    gasm_->SetStackPointer(central_stack_sp);
    return old_sp;
  }
References v8::internal::ExternalReference::isolate_address(), v8::internal::MachineType::Pointer(), and v8::internal::sig.
BuildSwitchToTheCentralStackIfNeeded()
Node* v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchToTheCentralStackIfNeeded () [inline]
Definition at line 894 of file wasm-compiler.cc.
                                               {
    // If the current stack is a secondary stack, switch to the central stack.
    auto end = gasm_->MakeLabel(MachineType::PointerRepresentation());
    Node* isolate_root = BuildLoadIsolateRoot();
    Node* is_on_central_stack_flag =
        gasm_->Load(MachineType::Uint8(), isolate_root,
                    IsolateData::is_on_central_stack_flag_offset());
    gasm_->GotoIf(is_on_central_stack_flag, &end, BranchHint::kTrue,
                  gasm_->IntPtrConstant(0));
    Node* old_sp = BuildSwitchToTheCentralStack();
    gasm_->Goto(&end, old_sp);
    gasm_->Bind(&end);
    return end.PhiAt(0);
  }
References v8::internal::compiler::end(), v8::internal::kTrue, v8::internal::MachineType::PointerRepresentation(), and v8::internal::MachineType::Uint8().
Member Data Documentation
float32_to_number_operator_
SetOncePointer<const Operator> v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::float32_to_number_operator_ [private]
Definition at line 1102 of file wasm-compiler.cc.
float64_to_number_operator_
SetOncePointer<const Operator> v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::float64_to_number_operator_ [private]
Definition at line 1103 of file wasm-compiler.cc.
int32_to_heapnumber_operator_
SetOncePointer<const Operator> v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::int32_to_heapnumber_operator_ [private]
Definition at line 1100 of file wasm-compiler.cc.
tagged_non_smi_to_int32_operator_
SetOncePointer<const Operator> v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::tagged_non_smi_to_int32_operator_ [private]
Definition at line 1101 of file wasm-compiler.cc.
tagged_to_float64_operator_
SetOncePointer<const Operator> v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::tagged_to_float64_operator_ [private]
Definition at line 1104 of file wasm-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/wasm-compiler.cc