v8::internal::compiler::CodeAssemblerCompilationJob Class Reference
#include <code-assembler-compilation-job.h>
Classes
struct TFDataAndPipeline
Public Types
using CodeAssemblerGenerator = std::function< void(compiler::CodeAssemblerState *)>
using CodeAssemblerInstaller = std::function< void(Builtin builtin, Handle< Code > code)>
Public Member Functions
CodeAssemblerCompilationJob (Isolate *isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions &assembler_options, std::function< compiler::CallDescriptor *(Zone *)> get_call_descriptor, CodeKind code_kind, const char *name, const ProfileDataFromFile *profile_data, int finalize_order)
CodeAssemblerCompilationJob (const CodeAssemblerCompilationJob &)=delete
CodeAssemblerCompilationJob & operator= (const CodeAssemblerCompilationJob &)=delete
int FinalizeOrder () const final
Static Public Attributes
static constexpr int kNoFinalizeOrder = -1
Protected Member Functions
RawMachineAssembler * raw_assembler ()
JSGraph * jsgraph ()
Status PrepareJobImpl (Isolate *isolate) final
Status FinalizeJobImpl (Isolate *isolate) final
virtual PipelineImpl * EmplacePipeline (Isolate *isolate)=0
virtual Handle< Code > FinalizeCode (Isolate *isolate)=0
Static Protected Member Functions
static V8_EXPORT_PRIVATE std::unique_ptr< CodeAssemblerCompilationJob > NewJobForTesting (Isolate *isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, std::function< compiler::CallDescriptor *(Zone *)> get_call_descriptor, CodeKind code_kind, const char *name)
static bool ShouldOptimizeJumps (Isolate *isolate)
Protected Attributes
CodeAssemblerGenerator generator_
CodeAssemblerInstaller installer_
const ProfileDataFromFile * profile_data_
int initial_graph_hash_ = 0
Zone zone_
ZoneStats zone_stats_
CodeAssemblerState code_assembler_state_
AssemblerOptions assembler_options_
OptimizedCompilationInfo compilation_info_
std::optional< NodeOriginTable > node_origins_
std::unique_ptr< JumpOptimizationInfo > jump_opt_
std::unique_ptr< TurbofanPipelineStatistics > pipeline_statistics_
int finalize_order_
Friends
class CodeAssemblerTester
Detailed Description
Definition at line 24 of file code-assembler-compilation-job.h.
Member Typedef Documentation
CodeAssemblerGenerator
using v8::internal::compiler::CodeAssemblerCompilationJob::CodeAssemblerGenerator = std::function<void(compiler::CodeAssemblerState*)>
Definition at line 26 of file code-assembler-compilation-job.h.
CodeAssemblerInstaller
using v8::internal::compiler::CodeAssemblerCompilationJob::CodeAssemblerInstaller = std::function<void(Builtin builtin, Handle<Code> code)>
Definition at line 28 of file code-assembler-compilation-job.h.
Constructor & Destructor Documentation
CodeAssemblerCompilationJob() [1/2]
v8::internal::compiler::CodeAssemblerCompilationJob::CodeAssemblerCompilationJob (Isolate * isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions & assembler_options, std::function< compiler::CallDescriptor *(Zone *)> get_call_descriptor, CodeKind code_kind, const char * name, const ProfileDataFromFile * profile_data, int finalize_order)
Definition at line 2278 of file pipeline.cc.
    : TurbofanCompilationJob(isolate, &compilation_info_,
                             State::kReadyToPrepare),
      generator_(generator),
      installer_(installer),
      profile_data_(profile_data),
      zone_(isolate->allocator(), ZONE_NAME),
      zone_stats_(isolate->allocator()),
      code_assembler_state_(isolate, &zone_, get_call_descriptor(&zone_),
                            code_kind, name, builtin),
      assembler_options_(assembler_options),
      compilation_info_(base::CStrVector(name), &zone_, code_kind),
      jump_opt_(ShouldOptimizeJumps(isolate) ? new JumpOptimizationInfo()
                                             : nullptr),
      finalize_order_(finalize_order) {
  DCHECK(code_kind == CodeKind::BUILTIN ||
         code_kind == CodeKind::BYTECODE_HANDLER ||
         code_kind == CodeKind::FOR_TESTING);
  compilation_info_.set_builtin(builtin);
}
References BUILTIN, compilation_info_, v8::internal::DCHECK(), and v8::internal::OptimizedCompilationInfo::set_builtin().
CodeAssemblerCompilationJob() [2/2]
v8::internal::compiler::CodeAssemblerCompilationJob::CodeAssemblerCompilationJob (const CodeAssemblerCompilationJob &) [delete]
Member Function Documentation
EmplacePipeline()
virtual PipelineImpl* v8::internal::compiler::CodeAssemblerCompilationJob::EmplacePipeline (Isolate * isolate) [protected], [pure virtual]
Implemented in v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob.
Referenced by PrepareJobImpl().
FinalizeCode()
virtual Handle<Code> v8::internal::compiler::CodeAssemblerCompilationJob::FinalizeCode (Isolate * isolate) [protected], [pure virtual]
Implemented in v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob.
Referenced by FinalizeJobImpl().
FinalizeJobImpl()
PipelineCompilationJob::Status v8::internal::compiler::CodeAssemblerCompilationJob::FinalizeJobImpl (Isolate * isolate) [final], [protected], [virtual]
Implements v8::internal::OptimizedCompilationJob.
Definition at line 2361 of file pipeline.cc.
                      {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kOptimizeFinalizePipelineJob);
  HandleScope scope(isolate);
  Handle<Code> code = FinalizeCode(isolate);
#ifdef ENABLE_DISASSEMBLER
  if (v8_flags.trace_ignition_codegen &&
      code->kind() == CodeKind::BYTECODE_HANDLER) {
    StdoutStream os;
    code->Disassemble(code_assembler_state_.name_, os, isolate);
    os << std::flush;
  }
#endif // ENABLE_DISASSEMBLER
  code_assembler_state_.code_generated_ = true;
  installer_(compilation_info_.builtin(), scope.CloseAndEscape(code));
  return SUCCEEDED;
}
References v8::internal::OptimizedCompilationInfo::builtin(), code, code_assembler_state_, v8::internal::compiler::CodeAssemblerState::code_generated_, compilation_info_, FinalizeCode(), installer_, v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::CodeAssemblerState::name_, RCS_SCOPE, v8::internal::CompilationJob::SUCCEEDED, and v8::internal::v8_flags.
FinalizeOrder()
int v8::internal::compiler::CodeAssemblerCompilationJob::FinalizeOrder () const [inline], [final], [virtual]
Reimplemented from v8::internal::TurbofanCompilationJob.
Definition at line 44 of file code-assembler-compilation-job.h.
                                  {
    DCHECK_NE(kNoFinalizeOrder, finalize_order_);
    return finalize_order_;
  }
References DCHECK_NE, finalize_order_, and kNoFinalizeOrder.
jsgraph()
JSGraph* v8::internal::compiler::CodeAssemblerCompilationJob::jsgraph () [inline], [protected]
Definition at line 65 of file code-assembler-compilation-job.h.
{ return code_assembler_state_.jsgraph_; }
References code_assembler_state_, and v8::internal::compiler::CodeAssemblerState::jsgraph_.
NewJobForTesting()
std::unique_ptr< CodeAssemblerCompilationJob > v8::internal::compiler::CodeAssemblerCompilationJob::NewJobForTesting (Isolate * isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, std::function< compiler::CallDescriptor *(Zone *)> get_call_descriptor, CodeKind code_kind, const char * name) [static], [protected]
Definition at line 2513 of file pipeline.cc.
                                          {
  AssemblerOptions assembler_options = AssemblerOptions::Default(isolate);
    return std::make_unique<CodeAssemblerTurboshaftCompilationJob>(
        isolate, builtin, generator, installer, assembler_options,
        get_call_descriptor, code_kind, name, nullptr, -1);
}
References v8::internal::AssemblerOptions::Default(), v8::internal::TurbofanCompilationJob::isolate(), and v8::internal::name.
operator=()
CodeAssemblerCompilationJob& v8::internal::compiler::CodeAssemblerCompilationJob::operator= (const CodeAssemblerCompilationJob &) [delete]
PrepareJobImpl()
PipelineCompilationJob::Status v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl (Isolate * isolate) [final], [protected], [virtual]
Implements v8::internal::OptimizedCompilationJob.
Definition at line 2310 of file pipeline.cc.
                      {
  {
    // Work around that the PersistentHandlesScope inside CompilationHandleScope
    // requires there to be at least one handle.
    HandleScope handle_scope(isolate);
    DirectHandle<Object> dummy(ReadOnlyRoots(isolate->heap()).empty_string(),
                               isolate);
    CompilationHandleScope compilation_scope(isolate, &compilation_info_);
    generator_(&code_assembler_state_);
  }
  node_origins_.emplace(raw_assembler()->ExportForOptimization());
  PipelineImpl* pipeline = EmplacePipeline(isolate);
  TFPipelineData* data = pipeline->data();
  PipelineJobScope pipeline_scope(data,
                                  isolate->counters()->runtime_call_stats());
  if (v8_flags.turbo_stats || v8_flags.turbo_stats_nvp) {
    pipeline_statistics_.reset(new TurbofanPipelineStatistics(
        &compilation_info_, isolate->GetTurboStatistics(), &zone_stats_));
  }
  const char* debug_name = code_assembler_state_.name_;
  if (compilation_info_.trace_turbo_json() ||
      compilation_info_.trace_turbo_graph()) {
    CodeTracer::StreamScope tracing_scope(data->GetCodeTracer());
    tracing_scope.stream()
        << "---------------------------------------------------\n"
        << "Begin compiling " << debug_name << " using TurboFan" << std::endl;
    if (compilation_info_.trace_turbo_json()) {
      TurboJsonFile json_of(&compilation_info_, std::ios_base::trunc);
      json_of << "{\"function\" : ";
      JsonPrintFunctionSource(json_of, -1, compilation_info_.GetDebugName(),
                              DirectHandle<Script>(), isolate,
                              DirectHandle<SharedFunctionInfo>());
      json_of << ",\n\"phases\":[";
    }
    if (!pipeline->Run<PrintGraphPhase>("V8.TFMachineCode")) return FAILED;
  }
  // Validate pgo profile.
  initial_graph_hash_ = ComputeInitialGraphHash(compilation_info_.builtin(),
                                                profile_data_, data->graph());
  profile_data_ = ValidateProfileData(profile_data_, initial_graph_hash_,
                                      code_assembler_state_.name_);
  data->set_profile_data(profile_data_);
  return SUCCEEDED;
}
References v8::internal::OptimizedCompilationInfo::builtin(), code_assembler_state_, compilation_info_, v8::internal::compiler::anonymous_namespace{pipeline.cc}::ComputeInitialGraphHash(), v8::internal::Isolate::counters(), v8::internal::compiler::PipelineImpl::data(), EmplacePipeline(), v8::internal::CompilationJob::FAILED, generator_, v8::internal::compiler::TFPipelineData::GetCodeTracer(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::Isolate::GetTurboStatistics(), v8::internal::compiler::TFPipelineData::graph(), v8::internal::Isolate::heap(), initial_graph_hash_, v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::JsonPrintFunctionSource(), v8::internal::compiler::CodeAssemblerState::name_, node_origins_, pipeline_statistics_, profile_data_, raw_assembler(), v8::internal::compiler::PipelineImpl::Run(), v8::internal::Counters::runtime_call_stats(), v8::internal::compiler::TFPipelineData::set_profile_data(), v8::internal::CodeTracer::StreamScope::stream(), v8::internal::CompilationJob::SUCCEEDED, v8::internal::v8_flags, v8::internal::compiler::anonymous_namespace{pipeline.cc}::ValidateProfileData(), and zone_stats_.
raw_assembler()
RawMachineAssembler* v8::internal::compiler::CodeAssemblerCompilationJob::raw_assembler () [inline], [protected]
Definition at line 62 of file code-assembler-compilation-job.h.
                                       {
    return code_assembler_state_.raw_assembler_.get();
  }
References code_assembler_state_, and v8::internal::compiler::CodeAssemblerState::raw_assembler_.
Referenced by v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl(), and PrepareJobImpl().
ShouldOptimizeJumps()
bool v8::internal::compiler::CodeAssemblerCompilationJob::ShouldOptimizeJumps (Isolate * isolate) [static], [protected]
Definition at line 2305 of file pipeline.cc.
                                                                      {
  return isolate->serializer_enabled() && v8_flags.turbo_rewrite_far_jumps &&
         !v8_flags.turbo_profiling && !v8_flags.dump_builtins_hashes_to_file;
}
References v8::internal::TurbofanCompilationJob::isolate(), v8::internal::Isolate::serializer_enabled(), and v8::internal::v8_flags.
Friends And Related Function Documentation
CodeAssemblerTester
friend class CodeAssemblerTester [friend]
Definition at line 52 of file code-assembler-compilation-job.h.
Member Data Documentation
assembler_options_
AssemblerOptions v8::internal::compiler::CodeAssemblerCompilationJob::assembler_options_ [protected]
Definition at line 83 of file code-assembler-compilation-job.h.
Referenced by v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::EmplacePipeline().
code_assembler_state_
CodeAssemblerState v8::internal::compiler::CodeAssemblerCompilationJob::code_assembler_state_ [protected]
Definition at line 82 of file code-assembler-compilation-job.h.
Referenced by FinalizeJobImpl(), jsgraph(), PrepareJobImpl(), and raw_assembler().
compilation_info_
OptimizedCompilationInfo v8::internal::compiler::CodeAssemblerCompilationJob::compilation_info_ [protected]
Definition at line 84 of file code-assembler-compilation-job.h.
Referenced by CodeAssemblerCompilationJob(), FinalizeJobImpl(), and PrepareJobImpl().
finalize_order_
int v8::internal::compiler::CodeAssemblerCompilationJob::finalize_order_ [protected]
Definition at line 92 of file code-assembler-compilation-job.h.
Referenced by FinalizeOrder().
generator_
CodeAssemblerGenerator v8::internal::compiler::CodeAssemblerCompilationJob::generator_ [protected]
Definition at line 75 of file code-assembler-compilation-job.h.
Referenced by PrepareJobImpl().
initial_graph_hash_
int v8::internal::compiler::CodeAssemblerCompilationJob::initial_graph_hash_ = 0 [protected]
Definition at line 78 of file code-assembler-compilation-job.h.
Referenced by v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl(), and PrepareJobImpl().
installer_
CodeAssemblerInstaller v8::internal::compiler::CodeAssemblerCompilationJob::installer_ [protected]
Definition at line 76 of file code-assembler-compilation-job.h.
Referenced by FinalizeJobImpl().
jump_opt_
std::unique_ptr<JumpOptimizationInfo> v8::internal::compiler::CodeAssemblerCompilationJob::jump_opt_ [protected]
Definition at line 88 of file code-assembler-compilation-job.h.
Referenced by v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl().
kNoFinalizeOrder
constexpr int v8::internal::compiler::CodeAssemblerCompilationJob::kNoFinalizeOrder = -1 [static], [constexpr]
Definition at line 43 of file code-assembler-compilation-job.h.
Referenced by FinalizeOrder().
node_origins_
std::optional<NodeOriginTable> v8::internal::compiler::CodeAssemblerCompilationJob::node_origins_ [protected]
Definition at line 85 of file code-assembler-compilation-job.h.
Referenced by PrepareJobImpl().
pipeline_statistics_
std::unique_ptr<TurbofanPipelineStatistics> v8::internal::compiler::CodeAssemblerCompilationJob::pipeline_statistics_ [protected]
Definition at line 89 of file code-assembler-compilation-job.h.
Referenced by PrepareJobImpl().
profile_data_
const ProfileDataFromFile* v8::internal::compiler::CodeAssemblerCompilationJob::profile_data_ [protected]
Definition at line 77 of file code-assembler-compilation-job.h.
Referenced by v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl(), and PrepareJobImpl().
zone_
Zone v8::internal::compiler::CodeAssemblerCompilationJob::zone_ [protected]
Definition at line 80 of file code-assembler-compilation-job.h.
zone_stats_
ZoneStats v8::internal::compiler::CodeAssemblerCompilationJob::zone_stats_ [protected]
Definition at line 81 of file code-assembler-compilation-job.h.
Referenced by PrepareJobImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/code-assembler-compilation-job.h
/mnt/V8SourceCode/src/compiler/pipeline.cc