v8::internal::maglev::ExtendPropertiesBackingStore Class Reference
#include <maglev-ir.h>
Public Member Functions
ExtendPropertiesBackingStore (uint64_t bitfield, int old_length)
Input & property_array_input ()
Input & object_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
int old_length () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kPropertyArrayIndex = 0
static constexpr int kObjectIndex = 1
Private Types
using Base = FixedInputValueNodeT< 2, ExtendPropertiesBackingStore >
Private Attributes
const int old_length_
Additional Inherited Members
Detailed Description
Definition at line 8360 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ExtendPropertiesBackingStore::Base = FixedInputValueNodeT<2, ExtendPropertiesBackingStore> [private]
Definition at line 8362 of file maglev-ir.h.
Constructor & Destructor Documentation
ExtendPropertiesBackingStore()
v8::internal::maglev::ExtendPropertiesBackingStore::ExtendPropertiesBackingStore (uint64_t bitfield, int old_length) [inline], [explicit]
Definition at line 8365 of file maglev-ir.h.
      : Base(bitfield), old_length_(old_length) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::ExtendPropertiesBackingStore::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::ExtendPropertiesBackingStore::MaxCallStackArgs () const [inline]
Definition at line 8381 of file maglev-ir.h.
{ return 0; }
object_input()
Input& v8::internal::maglev::ExtendPropertiesBackingStore::object_input () [inline]
Definition at line 8379 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
old_length()
int v8::internal::maglev::ExtendPropertiesBackingStore::old_length () const [inline]
Definition at line 8386 of file maglev-ir.h.
{ return old_length_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::ExtendPropertiesBackingStore::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8473 of file maglev-ir.cc.
                                                               {
  os << "(" << old_length_ << ")";
}
References old_length_.
property_array_input()
Input& v8::internal::maglev::ExtendPropertiesBackingStore::property_array_input () [inline]
Definition at line 8378 of file maglev-ir.h.
{ return input(kPropertyArrayIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::ExtendPropertiesBackingStore::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ExtendPropertiesBackingStore::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 8373 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::ExtendPropertiesBackingStore::kObjectIndex = 1 [static], [constexpr]
Definition at line 8377 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::ExtendPropertiesBackingStore::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanAllocate() | OpProperties::CanRead() |
      OpProperties::CanWrite() | OpProperties::DeferredCall() |
      OpProperties::EagerDeopt() | OpProperties::NotIdempotent()
Definition at line 8368 of file maglev-ir.h.
kPropertyArrayIndex
constexpr int v8::internal::maglev::ExtendPropertiesBackingStore::kPropertyArrayIndex = 0 [static], [constexpr]
Definition at line 8376 of file maglev-ir.h.
old_length_
const int v8::internal::maglev::ExtendPropertiesBackingStore::old_length_ [private]
Definition at line 8389 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc