v8::internal::CodeAddressMap::NameMap Class Reference
Public Member Functions
NameMap ()
NameMap (const NameMap &)=delete
NameMap & operator= (const NameMap &)=delete
~NameMap ()
void Insert (Address code_address, const char *name, size_t name_size)
const char * Lookup (Address code_address)
void Remove (Address code_address)
void Move (Address from, Address to)
Private Member Functions
base::HashMap::Entry * FindOrCreateEntry (Address code_address)
base::HashMap::Entry * FindEntry (Address code_address)
void RemoveEntry (base::HashMap::Entry *entry)
Static Private Member Functions
static char * CopyName (const char *name, size_t name_size)
Private Attributes
base::HashMap impl_
Detailed Description
Definition at line 52 of file serializer.h.
Constructor & Destructor Documentation
NameMap() [1/2]
v8::internal::CodeAddressMap::NameMap::NameMap () [inline]
Definition at line 54 of file serializer.h.
: impl_() {}
NameMap() [2/2]
v8::internal::CodeAddressMap::NameMap::NameMap (const NameMap &) [delete]
 NameMap()
v8::internal::CodeAddressMap::NameMap::~NameMap () [inline]
Definition at line 58 of file serializer.h.
               {
      for (base::HashMap::Entry* p = impl_.Start(); p != nullptr;
           p = impl_.Next(p)) {
        DeleteArray(static_cast<const char*>(p->value));
      }
    }
References impl_.
Member Function Documentation
CopyName()
static char* v8::internal::CodeAddressMap::NameMap::CopyName (const char * name, size_t name_size) [inline], [static], [private]
Definition at line 98 of file serializer.h.
                                                              {
      char* result = NewArray<char>(name_size + 1);
      for (size_t i = 0; i < name_size; ++i) {
        char c = name[i];
        if (c == '\0') c = ' ';
        result[i] = c;
      }
      result[name_size] = '\0';
      return result;
    }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::name, and v8::base::internal::result.
Referenced by Insert().
FindEntry()
base::HashMap::Entry* v8::internal::CodeAddressMap::NameMap::FindEntry (Address code_address) [inline], [private]
Definition at line 114 of file serializer.h.
                                                      {
      return impl_.Lookup(reinterpret_cast<void*>(code_address),
                          ComputeAddressHash(code_address));
    }
References v8::internal::ComputeAddressHash(), and impl_.
Referenced by Lookup(), Move(), and Remove().
FindOrCreateEntry()
base::HashMap::Entry* v8::internal::CodeAddressMap::NameMap::FindOrCreateEntry (Address code_address) [inline], [private]
Definition at line 109 of file serializer.h.
                                                              {
      return impl_.LookupOrInsert(reinterpret_cast<void*>(code_address),
                                  ComputeAddressHash(code_address));
    }
References v8::internal::ComputeAddressHash(), and impl_.
Referenced by Insert(), and Move().
Insert()
void v8::internal::CodeAddressMap::NameMap::Insert (Address code_address, const char * name, size_t name_size) [inline]
Definition at line 65 of file serializer.h.
                                                                          {
      base::HashMap::Entry* entry = FindOrCreateEntry(code_address);
      if (entry->value == nullptr) {
        entry->value = CopyName(name, name_size);
      }
    }
References CopyName(), FindOrCreateEntry(), and v8::internal::name.
Referenced by v8::internal::CodeAddressMap::LogRecordedBuffer().
Lookup()
const char* v8::internal::CodeAddressMap::NameMap::Lookup (Address code_address) [inline]
Definition at line 72 of file serializer.h.
                                             {
      base::HashMap::Entry* entry = FindEntry(code_address);
      return (entry != nullptr) ? static_cast<const char*>(entry->value)
                                : nullptr;
    }
References FindEntry().
Referenced by v8::internal::CodeAddressMap::Lookup().
Move()
void v8::internal::CodeAddressMap::NameMap::Move (Address from, Address to) [inline]
Definition at line 86 of file serializer.h.
                                        {
      if (from == to) return;
      base::HashMap::Entry* from_entry = FindEntry(from);
      DCHECK_NOT_NULL(from_entry);
      void* value = from_entry->value;
      RemoveEntry(from_entry);
      base::HashMap::Entry* to_entry = FindOrCreateEntry(to);
      DCHECK_NULL(to_entry->value);
      to_entry->value = value;
    }
References DCHECK_NOT_NULL, DCHECK_NULL, FindEntry(), FindOrCreateEntry(), RemoveEntry(), and v8::internal::value.
Referenced by v8::internal::CodeAddressMap::BytecodeMoveEvent(), and v8::internal::CodeAddressMap::CodeMoveEvent().
operator=()
NameMap& v8::internal::CodeAddressMap::NameMap::operator= (const NameMap &) [delete]
Remove()
void v8::internal::CodeAddressMap::NameMap::Remove (Address code_address) [inline]
Definition at line 78 of file serializer.h.
                                      {
      base::HashMap::Entry* entry = FindEntry(code_address);
      if (entry != nullptr) {
        DeleteArray(static_cast<char*>(entry->value));
        RemoveEntry(entry);
      }
    }
References FindEntry(), and RemoveEntry().
RemoveEntry()
void v8::internal::CodeAddressMap::NameMap::RemoveEntry (base::HashMap::Entry * entry) [inline], [private]
Definition at line 119 of file serializer.h.
                                              {
      impl_.Remove(entry->key, entry->hash);
    }
References impl_.
Referenced by Move(), and Remove().
Member Data Documentation
impl_
base::HashMap v8::internal::CodeAddressMap::NameMap::impl_ [private]
Definition at line 123 of file serializer.h.
Referenced by FindEntry(), FindOrCreateEntry(), RemoveEntry(), and ~NameMap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/serializer.h