v8::internal::HeapAllocator Class Reference
#include <heap-allocator.h>
Public Types
enum AllocationRetryMode { kLightRetry
, kRetryOrFail
 }
Public Member Functions
HeapAllocator (LocalHeap *)
void Setup (LinearAllocationArea *new_allocation_info=nullptr, LinearAllocationArea *old_allocation_info=nullptr)
void SetReadOnlySpace (ReadOnlySpace *)
V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (int size_in_bytes, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
template<AllocationType type>
V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (int size_in_bytes, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
template<AllocationRetryMode mode>
V8_WARN_UNUSED_RESULT Tagged< HeapObject > AllocateRawWith (int size, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
bool TryResizeLargeObject (Tagged< HeapObject > object, size_t old_object_size, size_t new_object_size)
bool CanAllocateInReadOnlySpace () const
void FreeLinearAllocationAreas ()
void MakeLinearAllocationAreasIterable ()
void MarkLinearAllocationAreasBlack ()
void UnmarkLinearAllocationsArea ()
void MarkSharedLinearAllocationAreasBlack ()
void UnmarkSharedLinearAllocationAreas ()
void FreeLinearAllocationAreasAndResetFreeLists ()
void FreeSharedLinearAllocationAreasAndResetFreeLists ()
void PauseAllocationObservers ()
void ResumeAllocationObservers ()
void PublishPendingAllocations ()
void AddAllocationObserver (AllocationObserver *observer, AllocationObserver *new_space_observer)
void RemoveAllocationObserver (AllocationObserver *observer, AllocationObserver *new_space_observer)
MainAllocator * new_space_allocator ()
const MainAllocator * new_space_allocator () const
MainAllocator * old_space_allocator ()
MainAllocator * trusted_space_allocator ()
MainAllocator * code_space_allocator ()
MainAllocator * shared_space_allocator ()
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT auto CustomAllocateWithRetryOrFail (AllocateFunction &&Allocate, AllocationType allocation)
template<typename AllocateFunction >
std::invoke_result_t< AllocateFunction > AllocateRawWithRetryOrFailSlowPath (AllocateFunction &&Allocate, AllocationType allocation)
template<typename AllocateFunction >
std::invoke_result_t< AllocateFunction > CollectGarbageAndRetryAllocation (AllocateFunction &&Allocate, AllocationType allocation)
template<typename AllocateFunction >
std::invoke_result_t< AllocateFunction > RetryAllocation (AllocateFunction &&Allocate)
Private Member Functions
PagedSpace * code_space () const
CodeLargeObjectSpace * code_lo_space () const
NewSpace * new_space () const
NewLargeObjectSpace * new_lo_space () const
OldLargeObjectSpace * lo_space () const
OldLargeObjectSpace * shared_lo_space () const
OldLargeObjectSpace * shared_trusted_lo_space () const
PagedSpace * old_space () const
ReadOnlySpace * read_only_space () const
PagedSpace * trusted_space () const
OldLargeObjectSpace * trusted_lo_space () const
V8_WARN_UNUSED_RESULT AllocationResult AllocateRawLargeInternal (int size_in_bytes, AllocationType allocation, AllocationOrigin origin, AllocationAlignment alignment, AllocationHint hint)
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT std::invoke_result_t< AllocateFunction > AllocateRawWithRetryOrFailSlowPath (AllocateFunction &&Allocate, AllocationType allocation)
V8_WARN_UNUSED_RESULT AllocationResult AllocateRawWithRetryOrFailSlowPath (int size, AllocationType allocation, AllocationOrigin origin, AllocationAlignment alignment, AllocationHint hint)
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT std::invoke_result_t< AllocateFunction > AllocateRawWithLightRetrySlowPath (AllocateFunction &&Allocate, AllocationType allocation)
V8_WARN_UNUSED_RESULT AllocationResult AllocateRawWithLightRetrySlowPath (int size, AllocationType allocation, AllocationOrigin origin, AllocationAlignment alignment, AllocationHint hint)
void CollectGarbage (AllocationType allocation, PerformHeapLimitCheck perform_heap_limit_check=PerformHeapLimitCheck::kYes)
void CollectAllAvailableGarbage (AllocationType allocation)
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT std::invoke_result_t< AllocateFunction > CollectGarbageAndRetryAllocation (AllocateFunction &&Allocate, AllocationType allocation)
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT std::invoke_result_t< AllocateFunction > RetryAllocation (AllocateFunction &&Allocate)
bool ReachedAllocationTimeout ()
Heap * heap_for_allocation (AllocationType allocation)
Private Attributes
LocalHeap * local_heap_
Heap *const heap_
Space * spaces_ [LAST_SPACE+1]
ReadOnlySpace * read_only_space_
std::optional< MainAllocator > new_space_allocator_
std::optional< MainAllocator > old_space_allocator_
std::optional< MainAllocator > trusted_space_allocator_
std::optional< MainAllocator > code_space_allocator_
std::optional< MainAllocator > shared_space_allocator_
std::optional< MainAllocator > shared_trusted_space_allocator_
OldLargeObjectSpace * shared_lo_space_
SharedTrustedLargeObjectSpace * shared_trusted_lo_space_
Detailed Description
Definition at line 35 of file heap-allocator.h.
Member Enumeration Documentation
AllocationRetryMode
enum v8::internal::HeapAllocator::AllocationRetryMode
Enumerator
kLightRetry
kRetryOrFail
Definition at line 63 of file heap-allocator.h.
{ kLightRetry, kRetryOrFail };
Constructor & Destructor Documentation
HeapAllocator()
v8::internal::HeapAllocator::HeapAllocator (LocalHeap * local_heap) [explicit]
Definition at line 25 of file heap-allocator.cc.
    : local_heap_(local_heap), heap_(local_heap->heap()) {}
Member Function Documentation
AddAllocationObserver()
void v8::internal::HeapAllocator::AddAllocationObserver (AllocationObserver * observer, AllocationObserver * new_space_observer)
Definition at line 315 of file heap-allocator.cc.
                                                                          {
  if (new_space_allocator_) {
    new_space_allocator_->AddAllocationObserver(new_space_observer);
  }
  if (new_lo_space()) {
    new_lo_space()->AddAllocationObserver(new_space_observer);
  }
  old_space_allocator_->AddAllocationObserver(observer);
  lo_space()->AddAllocationObserver(observer);
  trusted_space_allocator_->AddAllocationObserver(observer);
  trusted_lo_space()->AddAllocationObserver(observer);
  code_space_allocator_->AddAllocationObserver(observer);
  code_lo_space()->AddAllocationObserver(observer);
}
References v8::internal::LargeObjectSpace::AddAllocationObserver(), code_lo_space(), code_space_allocator_, lo_space(), new_lo_space(), new_space_allocator_, old_space_allocator_, trusted_lo_space(), and trusted_space_allocator_.
Referenced by v8::internal::Heap::AddAllocationObserversToAllSpaces(), and v8::internal::IncrementalMarking::StartMarkingMajor().
AllocateRaw() [1/2]
template<AllocationType type>
V8_WARN_UNUSED_RESULT AllocationResult v8::internal::HeapAllocator::AllocateRaw (int size_in_bytes, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [inline]
Definition at line 75 of file heap-allocator-inl.h.
                                                                               {
  DCHECK(!heap_->IsInGC());
  DCHECK(AllowHandleAllocation::IsAllowed());
  DCHECK(AllowHeapAllocation::IsAllowed());
  CHECK(AllowHeapAllocationInRelease::IsAllowed());
  DCHECK(local_heap_->IsRunning());
  // We need to have entered the isolate before allocating.
  DCHECK_EQ(heap_->isolate(), Isolate::TryGetCurrent());
#if V8_ENABLE_WEBASSEMBLY
  if (!v8_flags.wasm_jitless) {
    trap_handler::AssertThreadNotInWasm();
  }
#endif
#if DEBUG
  local_heap_->VerifyCurrent();
#endif
  if (v8_flags.single_generation.value() && type == AllocationType::kYoung) {
    return AllocateRaw(size_in_bytes, AllocationType::kOld, origin, alignment);
  }
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  if (V8_UNLIKELY(allocation_timeout_.has_value()) &&
      ReachedAllocationTimeout()) {
    return AllocationResult::Failure();
  }
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
#ifdef DEBUG
  IncrementObjectCounters();
#endif // DEBUG
  if (heap_->CanSafepoint()) {
    local_heap_->Safepoint();
  }
  const size_t large_object_threshold = heap_->MaxRegularHeapObjectSize(type);
  const bool large_object =
      static_cast<size_t>(size_in_bytes) > large_object_threshold;
  Tagged<HeapObject> object;
  AllocationResult allocation;
  if (V8_UNLIKELY(large_object)) {
    allocation =
        AllocateRawLargeInternal(size_in_bytes, type, origin, alignment, hint);
  } else {
    switch (type) {
      case AllocationType::kYoung:
        allocation = new_space_allocator_->AllocateRaw(size_in_bytes, alignment,
                                                       origin, hint);
        break;
      case AllocationType::kMap:
      case AllocationType::kOld:
        allocation = old_space_allocator_->AllocateRaw(size_in_bytes, alignment,
                                                       origin, hint);
        DCHECK_IMPLIES(v8_flags.sticky_mark_bits && !allocation.IsFailure(),
                       heap_->marking_state()->IsMarked(allocation.ToObject()));
        break;
      case AllocationType::kCode: {
        DCHECK_EQ(alignment, AllocationAlignment::kTaggedAligned);
        DCHECK(AllowCodeAllocation::IsAllowed());
        allocation = code_space_allocator_->AllocateRaw(
            size_in_bytes, AllocationAlignment::kTaggedAligned, origin, hint);
        break;
      }
      case AllocationType::kReadOnly:
        DCHECK(read_only_space()->writable());
        DCHECK_EQ(AllocationOrigin::kRuntime, origin);
        allocation = read_only_space()->AllocateRaw(size_in_bytes, alignment);
        break;
      case AllocationType::kSharedMap:
      case AllocationType::kSharedOld:
        allocation = shared_space_allocator_->AllocateRaw(
            size_in_bytes, alignment, origin, hint);
        break;
      case AllocationType::kTrusted:
        allocation = trusted_space_allocator_->AllocateRaw(
            size_in_bytes, alignment, origin, hint);
        break;
      case AllocationType::kSharedTrusted:
        allocation = shared_trusted_space_allocator_->AllocateRaw(
            size_in_bytes, alignment, origin, hint);
        break;
    }
  }
  if (allocation.To(&object)) {
    if (heap::ShouldZapGarbage() && AllocationType::kCode == type) {
      heap::ZapCodeBlock(object.address(), size_in_bytes);
    }
    if (local_heap_->is_main_thread()) {
      for (auto& tracker : heap_->allocation_trackers_) {
        tracker->AllocationEvent(object.address(), size_in_bytes);
      }
    }
  }
  return allocation;
}
References v8::internal::ReadOnlySpace::AllocateRaw(), AllocateRaw(), AllocateRawLargeInternal(), v8::internal::Heap::allocation_trackers_, v8::internal::trap_handler::AssertThreadNotInWasm(), v8::internal::Heap::CanSafepoint(), CHECK, code_space_allocator_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::AllocationResult::Failure(), heap_, v8::internal::LocalHeap::is_main_thread(), v8::internal::PerThreadAssertScope< kAllow, kTypes >::IsAllowed(), v8::internal::AllocationResult::IsFailure(), v8::internal::Heap::IsInGC(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::IsMarked(), v8::internal::Heap::isolate(), v8::internal::LocalHeap::IsRunning(), v8::internal::kCode, v8::internal::kMap, v8::internal::kOld, v8::internal::kReadOnly, v8::internal::kRuntime, v8::internal::kSharedMap, v8::internal::kSharedOld, v8::internal::kSharedTrusted, v8::internal::kTaggedAligned, v8::internal::kTrusted, v8::internal::kYoung, local_heap_, v8::internal::Heap::marking_state(), v8::internal::Heap::MaxRegularHeapObjectSize(), new_space_allocator_, old_space_allocator_, ReachedAllocationTimeout(), read_only_space(), v8::internal::LocalHeap::Safepoint(), shared_space_allocator_, shared_trusted_space_allocator_, v8::internal::heap::ShouldZapGarbage(), v8::internal::AllocationResult::To(), v8::internal::AllocationResult::ToObject(), trusted_space_allocator_, v8::Isolate::TryGetCurrent(), v8::internal::tracing::type, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::heap::ZapCodeBlock().
AllocateRaw() [2/2]
AllocationResult v8::internal::HeapAllocator::AllocateRaw (int size_in_bytes, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [inline]
Definition at line 178 of file heap-allocator-inl.h.
                                                                 {
  switch (type) {
    case AllocationType::kYoung:
      return AllocateRaw<AllocationType::kYoung>(size_in_bytes, origin,
                                                 alignment, hint);
    case AllocationType::kOld:
      return AllocateRaw<AllocationType::kOld>(size_in_bytes, origin, alignment,
                                               hint);
    case AllocationType::kCode:
      return AllocateRaw<AllocationType::kCode>(size_in_bytes, origin,
                                                alignment, hint);
    case AllocationType::kMap:
      return AllocateRaw<AllocationType::kMap>(size_in_bytes, origin, alignment,
                                               hint);
    case AllocationType::kReadOnly:
      return AllocateRaw<AllocationType::kReadOnly>(size_in_bytes, origin,
                                                    alignment, hint);
    case AllocationType::kSharedMap:
      return AllocateRaw<AllocationType::kSharedMap>(size_in_bytes, origin,
                                                     alignment, hint);
    case AllocationType::kSharedOld:
      return AllocateRaw<AllocationType::kSharedOld>(size_in_bytes, origin,
                                                     alignment, hint);
    case AllocationType::kTrusted:
      return AllocateRaw<AllocationType::kTrusted>(size_in_bytes, origin,
                                                   alignment, hint);
    case AllocationType::kSharedTrusted:
      return AllocateRaw<AllocationType::kSharedTrusted>(size_in_bytes, origin,
                                                         alignment, hint);
  }
  UNREACHABLE();
}
References v8::internal::kCode, v8::internal::kMap, v8::internal::kOld, v8::internal::kReadOnly, v8::internal::kSharedMap, v8::internal::kSharedOld, v8::internal::kSharedTrusted, v8::internal::kTrusted, v8::internal::kYoung, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by AllocateRaw(), v8::internal::Heap::AllocateRaw(), v8::internal::LocalHeap::AllocateRaw(), AllocateRawWithLightRetrySlowPath(), and AllocateRawWithRetryOrFailSlowPath().
AllocateRawLargeInternal()
AllocationResult v8::internal::HeapAllocator::AllocateRawLargeInternal (int size_in_bytes, AllocationType allocation, AllocationOrigin origin, AllocationAlignment alignment, AllocationHint hint) [private]
Definition at line 70 of file heap-allocator.cc.
                                                        {
  DCHECK_GT(size_in_bytes, heap_->MaxRegularHeapObjectSize(allocation));
  switch (allocation) {
    case AllocationType::kYoung:
      return new_lo_space()->AllocateRaw(local_heap_, size_in_bytes, hint);
    case AllocationType::kOld:
      return lo_space()->AllocateRaw(local_heap_, size_in_bytes, hint);
    case AllocationType::kCode:
      return code_lo_space()->AllocateRaw(local_heap_, size_in_bytes, hint);
    case AllocationType::kSharedOld:
      return shared_lo_space()->AllocateRaw(local_heap_, size_in_bytes, hint);
    case AllocationType::kTrusted:
      return trusted_lo_space()->AllocateRaw(local_heap_, size_in_bytes, hint);
    case AllocationType::kSharedTrusted:
      return shared_trusted_lo_space()->AllocateRaw(local_heap_, size_in_bytes,
                                                    hint);
    case AllocationType::kMap:
    case AllocationType::kReadOnly:
    case AllocationType::kSharedMap:
      UNREACHABLE();
  }
}
References v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::CodeLargeObjectSpace::AllocateRaw(), code_lo_space(), DCHECK_GT, heap_, v8::internal::kCode, v8::internal::kMap, v8::internal::kOld, v8::internal::kReadOnly, v8::internal::kSharedMap, v8::internal::kSharedOld, v8::internal::kSharedTrusted, v8::internal::kTrusted, v8::internal::kYoung, lo_space(), local_heap_, v8::internal::Heap::MaxRegularHeapObjectSize(), new_lo_space(), shared_lo_space(), shared_trusted_lo_space(), trusted_lo_space(), and v8::internal::UNREACHABLE().
Referenced by AllocateRaw().
AllocateRawWith()
template<HeapAllocator::AllocationRetryMode mode>
V8_WARN_UNUSED_RESULT Tagged< HeapObject > v8::internal::HeapAllocator::AllocateRawWith (int size, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [inline]
Definition at line 217 of file heap-allocator-inl.h.
                                                    {
  AllocationResult result;
  Tagged<HeapObject> object;
  size = ALIGN_TO_ALLOCATION_ALIGNMENT(size);
  if (allocation == AllocationType::kYoung) {
    result = AllocateRaw<AllocationType::kYoung>(size, origin, alignment, hint);
    if (result.To(&object)) {
      return object;
    }
  } else if (allocation == AllocationType::kOld) {
    result = AllocateRaw<AllocationType::kOld>(size, origin, alignment, hint);
    if (result.To(&object)) {
      return object;
    }
  }
  switch (mode) {
    case kLightRetry:
      result = AllocateRawWithLightRetrySlowPath(size, allocation, origin,
                                                 alignment, hint);
      break;
    case kRetryOrFail:
      result = AllocateRawWithRetryOrFailSlowPath(size, allocation, origin,
                                                  alignment, hint);
      break;
  }
  if (result.To(&object)) {
    return object;
  }
  return HeapObject();
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, AllocateRawWithLightRetrySlowPath(), AllocateRawWithRetryOrFailSlowPath(), kLightRetry, v8::internal::kOld, kRetryOrFail, v8::internal::kYoung, mode(), v8::base::internal::result, and size().
Referenced by v8::internal::Factory::AllocateRaw(), v8::internal::Heap::AllocateRawOrFail(), v8::internal::LocalHeap::AllocateRawWith(), v8::internal::Factory::AllocateRawWithAllocationSite(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::Factory::New(), v8::internal::Factory::NewContextInternal(), v8::internal::Factory::NewFillerObject(), v8::internal::Factory::NewMapImpl(), and v8::internal::Heap::StaticRootsEnsureAllocatedSize().
AllocateRawWithLightRetrySlowPath() [1/2]
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT std::invoke_result_t< AllocateFunction > v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath (AllocateFunction && Allocate, AllocationType allocation) [inline], [private]
Definition at line 253 of file heap-allocator-inl.h.
                                                                            {
  DCHECK_NE(AllocationType::kYoung, allocation);
  if (auto result = Allocate()) [[likely]] {
    return result;
  }
  if (auto result = CollectGarbageAndRetryAllocation(Allocate, allocation)) {
    return result;
  }
  heap_for_allocation(allocation)->CheckHeapLimitReached();
  return {};
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::Heap::CheckHeapLimitReached(), CollectGarbageAndRetryAllocation(), DCHECK_NE, heap_for_allocation(), v8::internal::kYoung, and v8::base::internal::result.
Referenced by AllocateRawWith(), and AllocateRawWithLightRetrySlowPath().
AllocateRawWithLightRetrySlowPath() [2/2]
AllocationResult v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath (int size, AllocationType allocation, AllocationOrigin origin, AllocationAlignment alignment, AllocationHint hint) [private]
Definition at line 117 of file heap-allocator.cc.
                                                        {
  auto Allocate = [&]() {
    return AllocateRaw(size, allocation, origin, alignment, hint);
  };
  return AllocateRawWithLightRetrySlowPath(Allocate, allocation);
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), AllocateRaw(), AllocateRawWithLightRetrySlowPath(), and size().
AllocateRawWithRetryOrFailSlowPath() [1/3]
template<typename AllocateFunction >
std::invoke_result_t<AllocateFunction> v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath (AllocateFunction && Allocate, AllocationType allocation)
Definition at line 272 of file heap-allocator-inl.h.
                                                                             {
  if (auto result = Allocate()) [[likely]] {
    return result;
  }
  if (auto result = CollectGarbageAndRetryAllocation(Allocate, allocation)) {
    return result;
  }
  // In the case of young allocations, the GCs above were minor GCs. Try "light"
  // full GCs before performing the last-resort GCs.
  if (allocation == AllocationType::kYoung) {
    if (auto result =
            CollectGarbageAndRetryAllocation(Allocate, AllocationType::kOld)) {
      return result;
    }
  }
  // Perform last resort GC. This call will clear more caches and perform more
  // GCs. It will also enforce the heap limit if still violated.
  CollectAllAvailableGarbage(allocation);
  if (auto result = RetryAllocation(Allocate)) {
    return result;
  }
  V8::FatalProcessOutOfMemory(heap_->isolate(), "CALL_AND_RETRY_LAST",
                              V8::kHeapOOM);
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), CollectAllAvailableGarbage(), CollectGarbageAndRetryAllocation(), v8::internal::V8::FatalProcessOutOfMemory(), heap_, v8::internal::Heap::isolate(), v8::internal::V8::kHeapOOM, v8::internal::kOld, v8::internal::kYoung, v8::base::internal::result, and RetryAllocation().
AllocateRawWithRetryOrFailSlowPath() [2/3]
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT std::invoke_result_t<AllocateFunction> v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath (AllocateFunction && Allocate, AllocationType allocation) [inline], [private]
Referenced by AllocateRawWith(), AllocateRawWithRetryOrFailSlowPath(), and CustomAllocateWithRetryOrFail().
AllocateRawWithRetryOrFailSlowPath() [3/3]
AllocationResult v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath (int size, AllocationType allocation, AllocationOrigin origin, AllocationAlignment alignment, AllocationHint hint) [private]
Definition at line 144 of file heap-allocator.cc.
                                                        {
  auto Allocate = [&]() {
    return AllocateRaw(size, allocation, origin, alignment, hint);
  };
  return AllocateRawWithRetryOrFailSlowPath(Allocate, allocation);
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), AllocateRaw(), AllocateRawWithRetryOrFailSlowPath(), and size().
CanAllocateInReadOnlySpace()
bool v8::internal::HeapAllocator::CanAllocateInReadOnlySpace () const [inline]
Definition at line 69 of file heap-allocator-inl.h.
                                                     {
  return read_only_space()->writable();
}
References read_only_space(), and v8::internal::ReadOnlySpace::writable().
Referenced by v8::internal::Factory::CanAllocateInReadOnlySpace().
code_lo_space()
CodeLargeObjectSpace * v8::internal::HeapAllocator::code_lo_space () const [inline], [private]
Definition at line 29 of file heap-allocator-inl.h.
                                                         {
  return static_cast<CodeLargeObjectSpace*>(spaces_[CODE_LO_SPACE]);
}
References v8::internal::CODE_LO_SPACE, and spaces_.
Referenced by AddAllocationObserver(), AllocateRawLargeInternal(), PublishPendingAllocations(), and RemoveAllocationObserver().
code_space()
PagedSpace * v8::internal::HeapAllocator::code_space () const [inline], [private]
Definition at line 25 of file heap-allocator-inl.h.
                                            {
  return static_cast<PagedSpace*>(spaces_[CODE_SPACE]);
}
References v8::internal::CODE_SPACE, and spaces_.
code_space_allocator()
MainAllocator* v8::internal::HeapAllocator::code_space_allocator () [inline]
Definition at line 135 of file heap-allocator.h.
                                        {
    return &code_space_allocator_.value();
  }
Referenced by v8::internal::Heap::IsPendingAllocationInternal().
CollectAllAvailableGarbage()
void v8::internal::HeapAllocator::CollectAllAvailableGarbage (AllocationType allocation) [private]
Definition at line 153 of file heap-allocator.cc.
                                                                        {
  if (IsSharedAllocationType(allocation)) {
    heap_->CollectGarbageShared(heap_->main_thread_local_heap(),
                                GarbageCollectionReason::kLastResort);
  } else if (local_heap_->is_main_thread()) {
    // On the main thread we can directly start the GC.
    heap_->CollectAllAvailableGarbage(GarbageCollectionReason::kLastResort);
  } else {
    // Request GC from main thread.
    heap_->CollectGarbageFromAnyThread(local_heap_);
  }
}
References v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::Heap::CollectGarbageFromAnyThread(), v8::internal::Heap::CollectGarbageShared(), heap_, v8::internal::LocalHeap::is_main_thread(), v8::internal::IsSharedAllocationType(), v8::internal::kLastResort, local_heap_, and v8::internal::Heap::main_thread_local_heap().
Referenced by AllocateRawWithRetryOrFailSlowPath().
CollectGarbage()
void v8::internal::HeapAllocator::CollectGarbage (AllocationType allocation, PerformHeapLimitCheck perform_heap_limit_check = PerformHeapLimitCheck::kYes) [private]
Definition at line 127 of file heap-allocator.cc.
                                                                               {
  if (IsSharedAllocationType(allocation)) {
    heap_->CollectGarbageShared(local_heap_,
                                GarbageCollectionReason::kAllocationFailure);
  } else if (local_heap_->is_main_thread()) {
    // On the main thread we can directly start the GC.
    AllocationSpace space_to_gc = AllocationTypeToGCSpace(allocation);
    heap_->CollectGarbage(space_to_gc,
                          GarbageCollectionReason::kAllocationFailure,
                          kNoGCCallbackFlags, perform_heap_limit_check);
  } else {
    // Request GC from main thread.
    heap_->CollectGarbageFromAnyThread(local_heap_);
  }
}
References v8::internal::anonymous_namespace{heap-allocator.cc}::AllocationTypeToGCSpace(), v8::internal::Heap::CollectGarbage(), v8::internal::Heap::CollectGarbageFromAnyThread(), v8::internal::Heap::CollectGarbageShared(), heap_, v8::internal::LocalHeap::is_main_thread(), v8::internal::IsSharedAllocationType(), v8::internal::kAllocationFailure, v8::kNoGCCallbackFlags, and local_heap_.
Referenced by CollectGarbageAndRetryAllocation().
CollectGarbageAndRetryAllocation() [1/2]
template<typename AllocateFunction >
std::invoke_result_t<AllocateFunction> v8::internal::HeapAllocator::CollectGarbageAndRetryAllocation (AllocateFunction && Allocate, AllocationType allocation)
Definition at line 305 of file heap-allocator-inl.h.
                                                                           {
  const auto perform_heap_limit_check = v8_flags.late_heap_limit_check
                                            ? PerformHeapLimitCheck::kNo
                                            : PerformHeapLimitCheck::kYes;
  for (int i = 0; i < 2; i++) {
    // Skip the heap limit check in the GC if enabled. The heap limit needs to
    // be enforced by the caller.
    CollectGarbage(allocation, perform_heap_limit_check);
    // As long as we are at or above the heap limit, we definitely need another
    // GC.
    if (heap_for_allocation(allocation)->ReachedHeapLimit()) {
      continue;
    }
    if (auto result = RetryAllocation(Allocate)) {
      return result;
    }
  }
  return {};
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), CollectGarbage(), heap_for_allocation(), v8::internal::kNo, v8::internal::kYes, v8::base::internal::result, RetryAllocation(), and v8::internal::v8_flags.
CollectGarbageAndRetryAllocation() [2/2]
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT std::invoke_result_t<AllocateFunction> v8::internal::HeapAllocator::CollectGarbageAndRetryAllocation (AllocateFunction && Allocate, AllocationType allocation) [private]
Referenced by AllocateRawWithLightRetrySlowPath(), and AllocateRawWithRetryOrFailSlowPath().
CustomAllocateWithRetryOrFail()
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT auto v8::internal::HeapAllocator::CustomAllocateWithRetryOrFail (AllocateFunction && Allocate, AllocationType allocation) [inline]
Definition at line 343 of file heap-allocator-inl.h.
                                                            {
  return *AllocateRawWithRetryOrFailSlowPath(Allocate, allocation);
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), and AllocateRawWithRetryOrFailSlowPath().
FreeLinearAllocationAreas()
void v8::internal::HeapAllocator::FreeLinearAllocationAreas ()
Definition at line 283 of file heap-allocator.cc.
                                              {
  if (new_space_allocator_) {
    new_space_allocator_->FreeLinearAllocationArea();
  }
  old_space_allocator_->FreeLinearAllocationArea();
  trusted_space_allocator_->FreeLinearAllocationArea();
  code_space_allocator_->FreeLinearAllocationArea();
  if (shared_space_allocator_) {
    shared_space_allocator_->FreeLinearAllocationArea();
  }
  if (shared_trusted_space_allocator_) {
    shared_trusted_space_allocator_->FreeLinearAllocationArea();
  }
}
References code_space_allocator_, new_space_allocator_, old_space_allocator_, shared_space_allocator_, shared_trusted_space_allocator_, and trusted_space_allocator_.
Referenced by v8::internal::LocalHeap::FreeLinearAllocationAreas(), and v8::internal::Heap::FreeMainThreadLinearAllocationAreas().
FreeLinearAllocationAreasAndResetFreeLists()
void v8::internal::HeapAllocator::FreeLinearAllocationAreasAndResetFreeLists ()
Definition at line 266 of file heap-allocator.cc.
                                                               {
  DCHECK(v8_flags.black_allocated_pages);
  old_space_allocator_->FreeLinearAllocationAreaAndResetFreeList();
  trusted_space_allocator_->FreeLinearAllocationAreaAndResetFreeList();
  code_space_allocator_->FreeLinearAllocationAreaAndResetFreeList();
}
References code_space_allocator_, v8::internal::DCHECK(), old_space_allocator_, trusted_space_allocator_, and v8::internal::v8_flags.
Referenced by v8::internal::LocalHeap::FreeLinearAllocationAreasAndResetFreeLists(), and v8::internal::IncrementalMarking::StartBlackAllocation().
FreeSharedLinearAllocationAreasAndResetFreeLists()
void v8::internal::HeapAllocator::FreeSharedLinearAllocationAreasAndResetFreeLists ()
Definition at line 273 of file heap-allocator.cc.
                                                                     {
  DCHECK(v8_flags.black_allocated_pages);
  if (shared_space_allocator_) {
    shared_space_allocator_->FreeLinearAllocationAreaAndResetFreeList();
  }
  if (shared_trusted_space_allocator_) {
    shared_trusted_space_allocator_->FreeLinearAllocationAreaAndResetFreeList();
  }
}
References v8::internal::DCHECK(), shared_space_allocator_, shared_trusted_space_allocator_, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::FreeSharedLinearAllocationAreasAndResetFreeLists().
heap_for_allocation()
Heap * v8::internal::HeapAllocator::heap_for_allocation (AllocationType allocation) [private]
Definition at line 429 of file heap-allocator.cc.
                                                                  {
  if (IsSharedAllocationType(allocation)) {
    return heap_->isolate()->shared_space_isolate()->heap();
  } else {
    return heap_;
  }
}
References v8::internal::Isolate::heap(), heap_, v8::internal::Heap::isolate(), v8::internal::IsSharedAllocationType(), and v8::internal::Isolate::shared_space_isolate().
Referenced by AllocateRawWithLightRetrySlowPath(), and CollectGarbageAndRetryAllocation().
lo_space()
OldLargeObjectSpace * v8::internal::HeapAllocator::lo_space () const [inline], [private]
Definition at line 33 of file heap-allocator-inl.h.
                                                   {
  return static_cast<OldLargeObjectSpace*>(spaces_[LO_SPACE]);
}
References v8::internal::LO_SPACE, and spaces_.
Referenced by AddAllocationObserver(), AllocateRawLargeInternal(), PublishPendingAllocations(), and RemoveAllocationObserver().
MakeLinearAllocationAreasIterable()
void v8::internal::HeapAllocator::MakeLinearAllocationAreasIterable ()
Definition at line 196 of file heap-allocator.cc.
                                                      {
  if (new_space_allocator_) {
    new_space_allocator_->MakeLinearAllocationAreaIterable();
  }
  old_space_allocator_->MakeLinearAllocationAreaIterable();
  trusted_space_allocator_->MakeLinearAllocationAreaIterable();
  code_space_allocator_->MakeLinearAllocationAreaIterable();
  if (shared_space_allocator_) {
    shared_space_allocator_->MakeLinearAllocationAreaIterable();
  }
  if (shared_trusted_space_allocator_) {
    shared_trusted_space_allocator_->MakeLinearAllocationAreaIterable();
  }
}
References code_space_allocator_, new_space_allocator_, old_space_allocator_, shared_space_allocator_, shared_trusted_space_allocator_, and trusted_space_allocator_.
Referenced by v8::internal::Heap::MakeLinearAllocationAreasIterable(), and v8::internal::LocalHeap::MakeLinearAllocationAreasIterable().
MarkLinearAllocationAreasBlack()
void v8::internal::HeapAllocator::MarkLinearAllocationAreasBlack ()
Definition at line 232 of file heap-allocator.cc.
                                                   {
  DCHECK(!v8_flags.black_allocated_pages);
  old_space_allocator_->MarkLinearAllocationAreaBlack();
  trusted_space_allocator_->MarkLinearAllocationAreaBlack();
  code_space_allocator_->MarkLinearAllocationAreaBlack();
}
References code_space_allocator_, v8::internal::DCHECK(), old_space_allocator_, trusted_space_allocator_, and v8::internal::v8_flags.
Referenced by v8::internal::LocalHeap::MarkLinearAllocationAreasBlack(), and v8::internal::IncrementalMarking::StartBlackAllocation().
MarkSharedLinearAllocationAreasBlack()
void v8::internal::HeapAllocator::MarkSharedLinearAllocationAreasBlack ()
Definition at line 246 of file heap-allocator.cc.
                                                         {
  DCHECK(!v8_flags.black_allocated_pages);
  if (shared_space_allocator_) {
    shared_space_allocator_->MarkLinearAllocationAreaBlack();
  }
  if (shared_trusted_space_allocator_) {
    shared_trusted_space_allocator_->MarkLinearAllocationAreaBlack();
  }
}
References v8::internal::DCHECK(), shared_space_allocator_, shared_trusted_space_allocator_, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::MarkSharedLinearAllocationAreasBlack().
new_lo_space()
NewLargeObjectSpace * v8::internal::HeapAllocator::new_lo_space () const [inline], [private]
Definition at line 45 of file heap-allocator-inl.h.
                                                       {
  return static_cast<NewLargeObjectSpace*>(spaces_[NEW_LO_SPACE]);
}
References v8::internal::NEW_LO_SPACE, and spaces_.
Referenced by AddAllocationObserver(), AllocateRawLargeInternal(), PublishPendingAllocations(), and RemoveAllocationObserver().
new_space()
NewSpace * v8::internal::HeapAllocator::new_space () const [inline], [private]
Definition at line 41 of file heap-allocator-inl.h.
                                         {
  return static_cast<NewSpace*>(spaces_[NEW_SPACE]);
}
References v8::internal::NEW_SPACE, and spaces_.
new_space_allocator() [1/2]
MainAllocator* v8::internal::HeapAllocator::new_space_allocator () [inline]
Definition at line 127 of file heap-allocator.h.
{ return &new_space_allocator_.value(); }
Referenced by v8::internal::ScheduleMinorGCTaskObserver::AddToNewSpace(), v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::EvacuationAllocator::EvacuationAllocator(), v8::internal::MarkCompactCollector::Finish(), v8::internal::Heap::IsPendingAllocationInternal(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::Heap::NewSpaceLimit(), v8::internal::Heap::NewSpaceTop(), v8::internal::MarkCompactCollector::Prepare(), v8::internal::ScheduleMinorGCTaskObserver::RemoveFromNewSpace(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::ConcurrentMarking::RunMinorImpl(), v8::internal::Heap::SetUpSpaces(), v8::internal::ScheduleMinorGCTaskObserver::Step(), and v8::internal::Heap::TearDown().
new_space_allocator() [2/2]
const MainAllocator* v8::internal::HeapAllocator::new_space_allocator () const [inline]
Definition at line 128 of file heap-allocator.h.
                                                   {
    return &new_space_allocator_.value();
  }
old_space()
PagedSpace * v8::internal::HeapAllocator::old_space () const [inline], [private]
Definition at line 49 of file heap-allocator-inl.h.
                                           {
  return static_cast<PagedSpace*>(spaces_[OLD_SPACE]);
}
References v8::internal::OLD_SPACE, and spaces_.
old_space_allocator()
MainAllocator* v8::internal::HeapAllocator::old_space_allocator () [inline]
Definition at line 131 of file heap-allocator.h.
{ return &old_space_allocator_.value(); }
Referenced by v8::internal::Heap::IsPendingAllocationInternal(), v8::internal::Heap::OldSpaceAllocationLimitAddress(), and v8::internal::Heap::OldSpaceAllocationTopAddress().
PauseAllocationObservers()
void v8::internal::HeapAllocator::PauseAllocationObservers ()
Definition at line 347 of file heap-allocator.cc.
                                             {
  if (new_space_allocator_) {
    new_space_allocator_->PauseAllocationObservers();
  }
  old_space_allocator_->PauseAllocationObservers();
  trusted_space_allocator_->PauseAllocationObservers();
  code_space_allocator_->PauseAllocationObservers();
}
References code_space_allocator_, new_space_allocator_, old_space_allocator_, and trusted_space_allocator_.
PublishPendingAllocations()
void v8::internal::HeapAllocator::PublishPendingAllocations ()
Definition at line 300 of file heap-allocator.cc.
                                              {
  if (new_space_allocator_) {
    new_space_allocator_->MoveOriginalTopForward();
  }
  old_space_allocator_->MoveOriginalTopForward();
  trusted_space_allocator_->MoveOriginalTopForward();
  code_space_allocator_->MoveOriginalTopForward();
  lo_space()->ResetPendingObject();
  if (new_lo_space()) new_lo_space()->ResetPendingObject();
  code_lo_space()->ResetPendingObject();
  trusted_lo_space()->ResetPendingObject();
}
References code_lo_space(), code_space_allocator_, lo_space(), new_lo_space(), new_space_allocator_, old_space_allocator_, v8::internal::LargeObjectSpace::ResetPendingObject(), trusted_lo_space(), and trusted_space_allocator_.
Referenced by v8::internal::Heap::PublishMainThreadPendingAllocations().
ReachedAllocationTimeout()
bool v8::internal::HeapAllocator::ReachedAllocationTimeout () [private]
Referenced by AllocateRaw().
read_only_space()
ReadOnlySpace * v8::internal::HeapAllocator::read_only_space () const [inline], [private]
Definition at line 53 of file heap-allocator-inl.h.
                                                    {
  return read_only_space_;
}
References read_only_space_.
Referenced by AllocateRaw(), CanAllocateInReadOnlySpace(), and SetReadOnlySpace().
RemoveAllocationObserver()
void v8::internal::HeapAllocator::RemoveAllocationObserver (AllocationObserver * observer, AllocationObserver * new_space_observer)
Definition at line 331 of file heap-allocator.cc.
                                                                          {
  if (new_space_allocator_) {
    new_space_allocator_->RemoveAllocationObserver(new_space_observer);
  }
  if (new_lo_space()) {
    new_lo_space()->RemoveAllocationObserver(new_space_observer);
  }
  old_space_allocator_->RemoveAllocationObserver(observer);
  lo_space()->RemoveAllocationObserver(observer);
  trusted_space_allocator_->RemoveAllocationObserver(observer);
  trusted_lo_space()->RemoveAllocationObserver(observer);
  code_space_allocator_->RemoveAllocationObserver(observer);
  code_lo_space()->RemoveAllocationObserver(observer);
}
References code_lo_space(), code_space_allocator_, lo_space(), new_lo_space(), new_space_allocator_, old_space_allocator_, v8::internal::LargeObjectSpace::RemoveAllocationObserver(), trusted_lo_space(), and trusted_space_allocator_.
Referenced by v8::internal::Heap::RemoveAllocationObserversFromAllSpaces(), and v8::internal::IncrementalMarking::Stop().
ResumeAllocationObservers()
void v8::internal::HeapAllocator::ResumeAllocationObservers ()
Definition at line 356 of file heap-allocator.cc.
                                              {
  if (new_space_allocator_) {
    new_space_allocator_->ResumeAllocationObservers();
  }
  old_space_allocator_->ResumeAllocationObservers();
  trusted_space_allocator_->ResumeAllocationObservers();
  code_space_allocator_->ResumeAllocationObservers();
}
References code_space_allocator_, new_space_allocator_, old_space_allocator_, and trusted_space_allocator_.
Referenced by v8::internal::PauseAllocationObserversScope::~PauseAllocationObserversScope().
RetryAllocation() [1/2]
template<typename AllocateFunction >
std::invoke_result_t<AllocateFunction> v8::internal::HeapAllocator::RetryAllocation (AllocateFunction && Allocate)
Definition at line 331 of file heap-allocator-inl.h.
                                 {
  // Initially flags on the LocalHeap are always disabled. They are only
  // active while this method is running.
  DCHECK(!local_heap_->IsRetryOfFailedAllocation());
  local_heap_->SetRetryOfFailedAllocation(true);
  auto result = Allocate();
  local_heap_->SetRetryOfFailedAllocation(false);
  return result;
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::DCHECK(), v8::internal::LocalHeap::IsRetryOfFailedAllocation(), local_heap_, v8::base::internal::result, and v8::internal::LocalHeap::SetRetryOfFailedAllocation().
RetryAllocation() [2/2]
template<typename AllocateFunction >
V8_WARN_UNUSED_RESULT std::invoke_result_t<AllocateFunction> v8::internal::HeapAllocator::RetryAllocation (AllocateFunction && Allocate) [private]
Referenced by AllocateRawWithRetryOrFailSlowPath(), and CollectGarbageAndRetryAllocation().
SetReadOnlySpace()
void v8::internal::HeapAllocator::SetReadOnlySpace (ReadOnlySpace * read_only_space)
Definition at line 66 of file heap-allocator.cc.
                                                                   {
  read_only_space_ = read_only_space;
}
References read_only_space(), and read_only_space_.
Referenced by v8::internal::Heap::ReplaceReadOnlySpace(), and v8::internal::Heap::SetUpFromReadOnlyHeap().
Setup()
void v8::internal::HeapAllocator::Setup (LinearAllocationArea * new_allocation_info = nullptr, LinearAllocationArea * old_allocation_info = nullptr)
Definition at line 28 of file heap-allocator.cc.
                                                                     {
  for (int i = FIRST_SPACE; i <= LAST_SPACE; ++i) {
    spaces_[i] = heap_->space(i);
  }
  if ((heap_->new_space() || v8_flags.sticky_mark_bits) &&
      local_heap_->is_main_thread()) {
    new_space_allocator_.emplace(
        local_heap_,
        v8_flags.sticky_mark_bits
            ? static_cast<SpaceWithLinearArea*>(heap_->sticky_space())
            : static_cast<SpaceWithLinearArea*>(heap_->new_space()),
        MainAllocator::IsNewGeneration::kYes, new_allocation_info);
  }
  old_space_allocator_.emplace(local_heap_, heap_->old_space(),
                               MainAllocator::IsNewGeneration::kNo,
                               old_allocation_info);
  trusted_space_allocator_.emplace(local_heap_, heap_->trusted_space(),
                                   MainAllocator::IsNewGeneration::kNo);
  code_space_allocator_.emplace(local_heap_, heap_->code_space(),
                                MainAllocator::IsNewGeneration::kNo);
  if (heap_->isolate()->has_shared_space()) {
    shared_space_allocator_.emplace(local_heap_,
                                    heap_->shared_allocation_space(),
                                    MainAllocator::IsNewGeneration::kNo);
    shared_lo_space_ = heap_->shared_lo_allocation_space();
    shared_trusted_space_allocator_.emplace(
        local_heap_, heap_->shared_trusted_allocation_space(),
        MainAllocator::IsNewGeneration::kNo);
    shared_trusted_lo_space_ = heap_->shared_trusted_lo_allocation_space();
  }
}
References v8::internal::Heap::code_space(), code_space_allocator_, v8::internal::FIRST_SPACE, v8::internal::Isolate::has_shared_space(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::LocalHeap::is_main_thread(), v8::internal::Heap::isolate(), v8::internal::MainAllocator::kNo, v8::internal::MainAllocator::kYes, v8::internal::LAST_SPACE, local_heap_, v8::internal::Heap::new_space(), new_space_allocator_, v8::internal::Heap::old_space(), old_space_allocator_, v8::internal::Heap::shared_allocation_space(), v8::internal::Heap::shared_lo_allocation_space(), shared_lo_space_, shared_space_allocator_, v8::internal::Heap::shared_trusted_allocation_space(), v8::internal::Heap::shared_trusted_lo_allocation_space(), shared_trusted_lo_space_, shared_trusted_space_allocator_, v8::internal::Heap::space(), spaces_, v8::internal::Heap::sticky_space(), v8::internal::Heap::trusted_space(), trusted_space_allocator_, and v8::internal::v8_flags.
Referenced by v8::internal::LocalHeap::LocalHeap(), v8::internal::LocalHeap::SetUpMainThread(), and v8::internal::LocalHeap::SetUpMainThreadForTesting().
shared_lo_space()
OldLargeObjectSpace * v8::internal::HeapAllocator::shared_lo_space () const [inline], [private]
Definition at line 37 of file heap-allocator-inl.h.
                                                          {
  return shared_lo_space_;
}
References shared_lo_space_.
Referenced by AllocateRawLargeInternal().
shared_space_allocator()
MainAllocator* v8::internal::HeapAllocator::shared_space_allocator () [inline]
Definition at line 138 of file heap-allocator.h.
                                          {
    return &shared_space_allocator_.value();
  }
Referenced by v8::internal::LocalHeap::FreeSharedLinearAllocationAreasAndResetFreeLists(), v8::internal::LocalHeap::MarkSharedLinearAllocationAreasBlack(), and v8::internal::LocalHeap::UnmarkSharedLinearAllocationsArea().
shared_trusted_lo_space()
OldLargeObjectSpace * v8::internal::HeapAllocator::shared_trusted_lo_space () const [inline], [private]
Definition at line 65 of file heap-allocator-inl.h.
                                                                  {
  return shared_trusted_lo_space_;
}
References shared_trusted_lo_space_.
Referenced by AllocateRawLargeInternal().
trusted_lo_space()
OldLargeObjectSpace * v8::internal::HeapAllocator::trusted_lo_space () const [inline], [private]
Definition at line 61 of file heap-allocator-inl.h.
                                                           {
  return static_cast<OldLargeObjectSpace*>(spaces_[TRUSTED_LO_SPACE]);
}
References spaces_, and v8::internal::TRUSTED_LO_SPACE.
Referenced by AddAllocationObserver(), AllocateRawLargeInternal(), PublishPendingAllocations(), and RemoveAllocationObserver().
trusted_space()
PagedSpace * v8::internal::HeapAllocator::trusted_space () const [inline], [private]
Definition at line 57 of file heap-allocator-inl.h.
                                               {
  return static_cast<PagedSpace*>(spaces_[TRUSTED_SPACE]);
}
References spaces_, and v8::internal::TRUSTED_SPACE.
trusted_space_allocator()
MainAllocator* v8::internal::HeapAllocator::trusted_space_allocator () [inline]
Definition at line 132 of file heap-allocator.h.
                                           {
    return &trusted_space_allocator_.value();
  }
Referenced by v8::internal::Heap::IsPendingAllocationInternal().
TryResizeLargeObject()
bool v8::internal::HeapAllocator::TryResizeLargeObject (Tagged< HeapObject > object, size_t old_object_size, size_t new_object_size)
Definition at line 166 of file heap-allocator.cc.
                                                                 {
  if (V8_UNLIKELY(!v8_flags.resize_large_object)) {
    return false;
  }
  PageMetadata* page = PageMetadata::FromHeapObject(object);
  Space* space = page->owner();
  if (space->identity() != NEW_LO_SPACE && space->identity() != LO_SPACE) {
    return false;
  }
  DCHECK(page->IsLargePage());
  DCHECK_EQ(page->area_size(), old_object_size);
  CHECK_GT(new_object_size, old_object_size);
  if (!heap_->memory_allocator()->ResizeLargePage(
          LargePageMetadata::cast(page), old_object_size, new_object_size)) {
    if (V8_UNLIKELY(v8_flags.trace_resize_large_object)) {
      heap_->isolate()->PrintWithTimestamp(
          "resizing large object failed: allocation could not be extended\n");
    }
    return false;
  }
  LargeObjectSpace* large_space = static_cast<LargeObjectSpace*>(page->owner());
  large_space->UpdateAccountingAfterResizingObject(old_object_size,
                                                   new_object_size);
  return true;
}
References v8::internal::MemoryChunkMetadata::area_size(), v8::internal::LargePageMetadata::cast(), CHECK_GT, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::PageMetadata::FromHeapObject(), heap_, v8::internal::MutablePageMetadata::IsLargePage(), v8::internal::Heap::isolate(), v8::internal::LO_SPACE, v8::internal::Heap::memory_allocator(), v8::internal::NEW_LO_SPACE, v8::internal::MutablePageMetadata::owner(), v8::internal::MemoryAllocator::ResizeLargePage(), space, v8::internal::LargeObjectSpace::UpdateAccountingAfterResizingObject(), v8::internal::v8_flags, and V8_UNLIKELY.
UnmarkLinearAllocationsArea()
void v8::internal::HeapAllocator::UnmarkLinearAllocationsArea ()
Definition at line 239 of file heap-allocator.cc.
                                                {
  DCHECK(!v8_flags.black_allocated_pages);
  old_space_allocator_->UnmarkLinearAllocationArea();
  trusted_space_allocator_->UnmarkLinearAllocationArea();
  code_space_allocator_->UnmarkLinearAllocationArea();
}
References code_space_allocator_, v8::internal::DCHECK(), old_space_allocator_, trusted_space_allocator_, and v8::internal::v8_flags.
Referenced by v8::internal::IncrementalMarking::PauseBlackAllocation(), and v8::internal::LocalHeap::UnmarkLinearAllocationsArea().
UnmarkSharedLinearAllocationAreas()
void v8::internal::HeapAllocator::UnmarkSharedLinearAllocationAreas ()
Definition at line 256 of file heap-allocator.cc.
                                                      {
  DCHECK(!v8_flags.black_allocated_pages);
  if (shared_space_allocator_) {
    shared_space_allocator_->UnmarkLinearAllocationArea();
  }
  if (shared_trusted_space_allocator_) {
    shared_trusted_space_allocator_->UnmarkLinearAllocationArea();
  }
}
References v8::internal::DCHECK(), shared_space_allocator_, shared_trusted_space_allocator_, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::UnmarkSharedLinearAllocationAreas().
Member Data Documentation
code_space_allocator_
std::optional<MainAllocator> v8::internal::HeapAllocator::code_space_allocator_ [private]
Definition at line 216 of file heap-allocator.h.
Referenced by AddAllocationObserver(), AllocateRaw(), FreeLinearAllocationAreas(), FreeLinearAllocationAreasAndResetFreeLists(), MakeLinearAllocationAreasIterable(), MarkLinearAllocationAreasBlack(), PauseAllocationObservers(), PublishPendingAllocations(), RemoveAllocationObserver(), ResumeAllocationObservers(), Setup(), and UnmarkLinearAllocationsArea().
heap_
Heap* const v8::internal::HeapAllocator::heap_ [private]
Definition at line 209 of file heap-allocator.h.
Referenced by AllocateRaw(), AllocateRawLargeInternal(), AllocateRawWithRetryOrFailSlowPath(), CollectAllAvailableGarbage(), CollectGarbage(), heap_for_allocation(), Setup(), and TryResizeLargeObject().
local_heap_
LocalHeap* v8::internal::HeapAllocator::local_heap_ [private]
Definition at line 208 of file heap-allocator.h.
Referenced by AllocateRaw(), AllocateRawLargeInternal(), CollectAllAvailableGarbage(), CollectGarbage(), RetryAllocation(), and Setup().
new_space_allocator_
std::optional<MainAllocator> v8::internal::HeapAllocator::new_space_allocator_ [private]
Definition at line 213 of file heap-allocator.h.
Referenced by AddAllocationObserver(), AllocateRaw(), FreeLinearAllocationAreas(), MakeLinearAllocationAreasIterable(), PauseAllocationObservers(), PublishPendingAllocations(), RemoveAllocationObserver(), ResumeAllocationObservers(), and Setup().
old_space_allocator_
std::optional<MainAllocator> v8::internal::HeapAllocator::old_space_allocator_ [private]
Definition at line 214 of file heap-allocator.h.
Referenced by AddAllocationObserver(), AllocateRaw(), FreeLinearAllocationAreas(), FreeLinearAllocationAreasAndResetFreeLists(), MakeLinearAllocationAreasIterable(), MarkLinearAllocationAreasBlack(), PauseAllocationObservers(), PublishPendingAllocations(), RemoveAllocationObserver(), ResumeAllocationObservers(), Setup(), and UnmarkLinearAllocationsArea().
read_only_space_
ReadOnlySpace* v8::internal::HeapAllocator::read_only_space_ [private]
Definition at line 211 of file heap-allocator.h.
Referenced by read_only_space(), and SetReadOnlySpace().
shared_lo_space_
OldLargeObjectSpace* v8::internal::HeapAllocator::shared_lo_space_ [private]
Definition at line 221 of file heap-allocator.h.
Referenced by Setup(), and shared_lo_space().
shared_space_allocator_
std::optional<MainAllocator> v8::internal::HeapAllocator::shared_space_allocator_ [private]
Definition at line 219 of file heap-allocator.h.
Referenced by AllocateRaw(), FreeLinearAllocationAreas(), FreeSharedLinearAllocationAreasAndResetFreeLists(), MakeLinearAllocationAreasIterable(), MarkSharedLinearAllocationAreasBlack(), Setup(), and UnmarkSharedLinearAllocationAreas().
shared_trusted_lo_space_
SharedTrustedLargeObjectSpace* v8::internal::HeapAllocator::shared_trusted_lo_space_ [private]
Definition at line 222 of file heap-allocator.h.
Referenced by Setup(), and shared_trusted_lo_space().
shared_trusted_space_allocator_
std::optional<MainAllocator> v8::internal::HeapAllocator::shared_trusted_space_allocator_ [private]
Definition at line 220 of file heap-allocator.h.
Referenced by AllocateRaw(), FreeLinearAllocationAreas(), FreeSharedLinearAllocationAreasAndResetFreeLists(), MakeLinearAllocationAreasIterable(), MarkSharedLinearAllocationAreasBlack(), Setup(), and UnmarkSharedLinearAllocationAreas().
spaces_
Space* v8::internal::HeapAllocator::spaces_[LAST_SPACE+1] [private]
Definition at line 210 of file heap-allocator.h.
Referenced by code_lo_space(), code_space(), lo_space(), new_lo_space(), new_space(), old_space(), Setup(), trusted_lo_space(), and trusted_space().
trusted_space_allocator_
std::optional<MainAllocator> v8::internal::HeapAllocator::trusted_space_allocator_ [private]
Definition at line 215 of file heap-allocator.h.
Referenced by AddAllocationObserver(), AllocateRaw(), FreeLinearAllocationAreas(), FreeLinearAllocationAreasAndResetFreeLists(), MakeLinearAllocationAreasIterable(), MarkLinearAllocationAreasBlack(), PauseAllocationObservers(), PublishPendingAllocations(), RemoveAllocationObserver(), ResumeAllocationObservers(), Setup(), and UnmarkLinearAllocationsArea().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap-allocator.h
/mnt/V8SourceCode/src/heap/heap-allocator-inl.h
/mnt/V8SourceCode/src/heap/heap-allocator.cc