v8::internal::compiler::StoreRepresentation Class Reference
#include <machine-operator.h>
Public Member Functions
StoreRepresentation (MachineRepresentation representation, WriteBarrierKind write_barrier_kind)
MachineRepresentation representation () const
WriteBarrierKind write_barrier_kind () const
Private Attributes
MachineRepresentation representation_
WriteBarrierKind write_barrier_kind_
Detailed Description
Definition at line 177 of file machine-operator.h.
Constructor & Destructor Documentation
StoreRepresentation()
v8::internal::compiler::StoreRepresentation::StoreRepresentation (MachineRepresentation representation, WriteBarrierKind write_barrier_kind) [inline]
Definition at line 179 of file machine-operator.h.
      : representation_(representation),
        write_barrier_kind_(write_barrier_kind) {}
Member Function Documentation
representation()
MachineRepresentation v8::internal::compiler::StoreRepresentation::representation () const [inline]
Definition at line 184 of file machine-operator.h.
{ return representation_; }
References representation_.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetSeqCstStoreOpcode(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MachineOperatorReducer::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::AtomicStoreParameters::representation(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Run(), v8::internal::compiler::MachineOperatorBuilder::Store(), v8::internal::compiler::InstructionSelector::StoreView::stored_rep(), v8::internal::compiler::MachineOperatorBuilder::StoreTrapOnNull(), v8::internal::compiler::MachineOperatorBuilder::TryStorePair(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), and v8::internal::compiler::VisitStoreCommon().
write_barrier_kind()
WriteBarrierKind v8::internal::compiler::StoreRepresentation::write_barrier_kind () const [inline]
Definition at line 185 of file machine-operator.h.
{ return write_barrier_kind_; }
References write_barrier_kind_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), and v8::internal::compiler::AtomicStoreParameters::write_barrier_kind().
Member Data Documentation
representation_
MachineRepresentation v8::internal::compiler::StoreRepresentation::representation_ [private]
Definition at line 188 of file machine-operator.h.
Referenced by representation().
write_barrier_kind_
WriteBarrierKind v8::internal::compiler::StoreRepresentation::write_barrier_kind_ [private]
Definition at line 189 of file machine-operator.h.
Referenced by write_barrier_kind().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator.h