v8::internal::ConsString Class Reference
#include <string.h>
Public Member Functions
Tagged< String > first () const
void set_first (Tagged< String > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< String > second () const
void set_second (Tagged< String > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > unchecked_first () const
Tagged< Object > unchecked_second () const
bool IsFlat () const
V8_EXPORT_PRIVATE uint16_t Get (uint32_t index, const SharedStringAccessGuardIfNeeded &access_guard) const
void PrintTree ()
Static Public Attributes
static const uint32_t kMinLength = 13
Private Attributes
TaggedMember< String > first_
TaggedMember< String > second_
Friends
struct ObjectTraits< ConsString >
struct OffsetsForDebug
class V8HeapExplorer
class CodeStubAssembler
class ToDirectStringAssembler
class StringBuiltinsAssembler
class SandboxTesting
class maglev::MaglevAssembler
class maglev::MaglevGraphBuilder
class compiler::AccessBuilder
class TorqueGeneratedConsStringAsserts
Tagged< String > String::GetUnderlying () const
Additional Inherited Members
Detailed Description
Definition at line 1014 of file string.h.
Member Function Documentation
first()
Tagged< String > v8::internal::ConsString::first () const [inline]
Definition at line 1402 of file string-inl.h.
{ return first_.load(); }
Get()
uint16_t v8::internal::ConsString::Get (uint32_t index, const SharedStringAccessGuardIfNeeded & access_guard) const
Definition at line 2000 of file string.cc.
                                                                               {
  DCHECK(index >= 0 && index < this->length());
  // Check for a flattened cons string
  if (second()->length() == 0) {
    Tagged<String> left = first();
    return left->Get(index);
  }
  Tagged<String> string = Cast<String>(this);
  while (true) {
    if (StringShape(string).IsCons()) {
      Tagged<ConsString> cons_string = Cast<ConsString>(string);
      Tagged<String> left = cons_string->first();
      if (left->length() > index) {
        string = left;
      } else {
        index -= left->length();
        string = cons_string->second();
      }
    } else {
      return string->Get(index, access_guard);
    }
  }
  UNREACHABLE();
}
References DCHECK, v8::internal::index, v8::internal::length, and UNREACHABLE.
IsFlat()
bool v8::internal::ConsString::IsFlat () const [inline]
Definition at line 1419 of file string-inl.h.
{ return second()->length() == 0; }
PrintTree()
void v8::internal::ConsString::PrintTree ()
Definition at line 2030 of file string.cc.
                           {
  DisallowGarbageCollection no_gc;
  using stack_elem_t = std::pair<Tagged<String>, int>;
  std::stack<stack_elem_t> s{{stack_elem_t{this, 0}}};
  while (!s.empty()) {
    auto elem = s.top();
    s.pop();
    int depth = elem.second;
    if (IsConsString(elem.first)) {
      auto cons = Cast<ConsString>(elem.first);
      printf("%d %p\n", depth, reinterpret_cast<void*>(cons.ptr()));
      s.push({cons->second(), depth + 1});
      s.push({cons->first(), depth + 1});
    } else {
      printf("%d ", depth);
      Print(elem.first);
    }
  }
}
References v8::internal::InstanceTypeChecker::IsConsString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Print().
second()
Tagged< String > v8::internal::ConsString::second () const [inline]
Definition at line 1407 of file string-inl.h.
{ return second_.load(); }
set_first()
void v8::internal::ConsString::set_first (Tagged< String > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 1403 of file string-inl.h.
                                                                             {
  first_.store(this, value, mode);
}
References mode(), and v8::internal::value.
set_second()
void v8::internal::ConsString::set_second (Tagged< String > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 1408 of file string-inl.h.
                                                          {
  second_.store(this, value, mode);
}
References mode(), and v8::internal::value.
unchecked_first()
Tagged< Object > v8::internal::ConsString::unchecked_first () const [inline]
Definition at line 1413 of file string-inl.h.
{ return first_.load(); }
unchecked_second()
Tagged< Object > v8::internal::ConsString::unchecked_second () const [inline]
Definition at line 1415 of file string-inl.h.
                                                  {
  return second_.Relaxed_Load();
}
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 1051 of file string.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 1057 of file string.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 1055 of file string.h.
maglev::MaglevGraphBuilder
friend class maglev::MaglevGraphBuilder [friend]
Definition at line 1056 of file string.h.
ObjectTraits< ConsString >
friend struct ObjectTraits< ConsString > [friend]
Definition at line 1043 of file string.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 1049 of file string.h.
SandboxTesting
friend class SandboxTesting [friend]
Definition at line 1054 of file string.h.
String::GetUnderlying
Tagged<String> String::GetUnderlying () const [friend]
StringBuiltinsAssembler
friend class StringBuiltinsAssembler [friend]
Definition at line 1053 of file string.h.
ToDirectStringAssembler
friend class ToDirectStringAssembler [friend]
Definition at line 1052 of file string.h.
TorqueGeneratedConsStringAsserts
friend class TorqueGeneratedConsStringAsserts [friend]
Definition at line 1058 of file string.h.
V8HeapExplorer
friend class V8HeapExplorer [friend]
Definition at line 1050 of file string.h.
Member Data Documentation
first_
TaggedMember<String> v8::internal::ConsString::first_ [private]
Definition at line 1062 of file string.h.
kMinLength
const uint32_t v8::internal::ConsString::kMinLength = 13 [static]
Definition at line 1043 of file string.h.
Referenced by v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::requires(), v8::internal::compiler::JSBinopReduction::ShouldCreateConsString(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::maglev::MaglevGraphBuilder::StringLengthStaticLowerBound(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildNewConsString().
second_
TaggedMember<String> v8::internal::ConsString::second_ [private]
Definition at line 1063 of file string.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h
/mnt/V8SourceCode/src/objects/string.cc