v8::debug::Coverage::ScriptData Class Reference
#include <debug-interface.h>
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (ScriptData)
Local< debug::Script > GetScript () const
size_t FunctionCount () const
FunctionData GetFunctionData (size_t i) const
Private Member Functions
ScriptData (size_t index, std::shared_ptr< i::Coverage > c)
Private Attributes
i::CoverageScript * script_
std::shared_ptr< i::Coverage > coverage_
Friends
class v8::debug::Coverage
Detailed Description
Definition at line 443 of file debug-interface.h.
Constructor & Destructor Documentation
ScriptData()
v8::debug::Coverage::ScriptData::ScriptData (size_t index, std::shared_ptr< i::Coverage > c) [explicit], [private]
Definition at line 1370 of file debug-interface.cc.
    : script_(&coverage->at(index)), coverage_(std::move(coverage)) {}
Member Function Documentation
FunctionCount()
size_t v8::debug::Coverage::ScriptData::FunctionCount () const
Definition at line 1362 of file debug-interface.cc.
                                               {
  return script_->functions.size();
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
GetFunctionData()
Coverage::FunctionData v8::debug::Coverage::ScriptData::GetFunctionData (size_t i) const
Definition at line 1366 of file debug-interface.cc.
                                                                       {
  return FunctionData(&script_->functions.at(i), coverage_);
}
References v8::debug::Coverage::coverage_.
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
GetScript()
Local< Script > v8::debug::Coverage::ScriptData::GetScript () const
Definition at line 1358 of file debug-interface.cc.
                                                  {
  return ToApiHandle<Script>(script_->script);
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::debug::Coverage::ScriptData::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (ScriptData)
Friends And Related Function Documentation
v8::debug::Coverage
friend class v8::debug::Coverage [friend]
Definition at line 457 of file debug-interface.h.
Member Data Documentation
coverage_
std::shared_ptr<i::Coverage> v8::debug::Coverage::ScriptData::coverage_ [private]
Definition at line 455 of file debug-interface.h.
script_
i::CoverageScript* v8::debug::Coverage::ScriptData::script_ [private]
Definition at line 454 of file debug-interface.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc