v8::internal::TurbofanStubWithContextFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
Tagged< HeapObject > unchecked_code () const override
void Iterate (RootVisitor *v) const override
Protected Member Functions
TurbofanStubWithContextFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 687 of file frames.h.
Constructor & Destructor Documentation
TurbofanStubWithContextFrame()
v8::internal::TurbofanStubWithContextFrame::TurbofanStubWithContextFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 296 of file frames-inl.h.
    : CommonFrame(iterator) {}
Member Function Documentation
Iterate()
void v8::internal::TurbofanStubWithContextFrame::Iterate (RootVisitor * v) const [override], [virtual]
Implements v8::internal::StackFrame.
Definition at line 2352 of file frames.cc.
                                                               {
  return IterateTurbofanJSOptimizedFrame(v);
}
References v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame().
type()
Type v8::internal::TurbofanStubWithContextFrame::type () const [inline], [override], [virtual]
Implements v8::internal::StackFrame.
Definition at line 689 of file frames.h.
{ return TURBOFAN_STUB_WITH_CONTEXT; }
unchecked_code()
Tagged< HeapObject > v8::internal::TurbofanStubWithContextFrame::unchecked_code () const [override], [virtual]
Implements v8::internal::StackFrame.
Definition at line 2261 of file frames.cc.
                                                                      {
  std::optional<Tagged<GcSafeCode>> code_lookup =
      isolate()->heap()->GcSafeTryFindCodeForInnerPointer(pc());
  if (!code_lookup.has_value()) return {};
  return code_lookup.value();
}
References v8::internal::Heap::GcSafeTryFindCodeForInnerPointer(), v8::internal::Isolate::heap(), v8::internal::StackFrame::isolate(), and v8::internal::StackFrame::pc().
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 699 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc