v8::internal::CpuProfiler Class Reference
#include <cpu-profiler.h>
Public Types
using ProfilingMode = v8::CpuProfilingMode
using CpuProfilingResult = v8::CpuProfilingResult
using NamingMode = v8::CpuProfilingNamingMode
using LoggingMode = v8::CpuProfilingLoggingMode
using StartProfilingStatus = CpuProfilingStatus
Public Member Functions
CpuProfiler (Isolate *isolate, CpuProfilingNamingMode=kDebugNaming, CpuProfilingLoggingMode=kLazyLogging)
CpuProfiler (Isolate *isolate, CpuProfilingNamingMode naming_mode, CpuProfilingLoggingMode logging_mode, CpuProfilesCollection *profiles, Symbolizer *test_symbolizer, ProfilerEventsProcessor *test_processor, ProfilerCodeObserver *test_code_observer)
~CpuProfiler ()
CpuProfiler (const CpuProfiler &)=delete
CpuProfiler & operator= (const CpuProfiler &)=delete
base::TimeDelta sampling_interval () const
void set_sampling_interval (base::TimeDelta value)
void set_use_precise_sampling (bool)
void CollectSample (const std::optional< uint64_t > trace_id=std::nullopt)
size_t GetEstimatedMemoryUsage () const
CpuProfilingResult StartProfiling (CpuProfilingOptions options={}, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
CpuProfilingResult StartProfiling (const char *title, CpuProfilingOptions options={}, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
CpuProfilingResult StartProfiling (Tagged< String > title, CpuProfilingOptions options={}, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
CpuProfile * StopProfiling (const char *title)
CpuProfile * StopProfiling (Tagged< String > title)
CpuProfile * StopProfiling (ProfilerId id)
int GetProfilesCount ()
CpuProfile * GetProfile (int index)
void DeleteAllProfiles ()
void DeleteProfile (CpuProfile *profile)
bool is_profiling () const
Symbolizer * symbolizer () const
ProfilerEventsProcessor * processor () const
Isolate * isolate () const
CodeEntryStorage * code_entries ()
ProfilerListener * profiler_listener_for_test () const
InstructionStreamMap * code_map_for_test ()
Static Public Member Functions
static void CollectSample (Isolate *isolate, std::optional< uint64_t > trace_id=std::nullopt)
static size_t GetAllProfilersMemorySize (Isolate *isolate)
Private Member Functions
void StartProcessorIfNotStarted ()
void StopProcessor ()
void ResetProfiles ()
void EnableLogging ()
void DisableLogging ()
base::TimeDelta ComputeSamplingInterval ()
void AdjustSamplingInterval ()
Private Attributes
Isolate *const isolate_
const NamingMode naming_mode_
const LoggingMode logging_mode_
bool use_precise_sampling_ = true
base::TimeDelta base_sampling_interval_
CodeEntryStorage code_entries_
std::unique_ptr< ProfilerCodeObserver > code_observer_
std::unique_ptr< CpuProfilesCollection > profiles_
std::unique_ptr< Symbolizer > symbolizer_
std::unique_ptr< ProfilerEventsProcessor > processor_
std::unique_ptr< ProfilerListener > profiler_listener_
std::unique_ptr< ProfilingScope > profiling_scope_
bool is_profiling_
Detailed Description
Definition at line 328 of file cpu-profiler.h.
Member Typedef Documentation
CpuProfilingResult
using v8::internal::CpuProfiler::CpuProfilingResult = v8::CpuProfilingResult
Definition at line 348 of file cpu-profiler.h.
LoggingMode
using v8::internal::CpuProfiler::LoggingMode = v8::CpuProfilingLoggingMode
Definition at line 350 of file cpu-profiler.h.
NamingMode
using v8::internal::CpuProfiler::NamingMode = v8::CpuProfilingNamingMode
Definition at line 349 of file cpu-profiler.h.
ProfilingMode
using v8::internal::CpuProfiler::ProfilingMode = v8::CpuProfilingMode
Definition at line 347 of file cpu-profiler.h.
StartProfilingStatus
using v8::internal::CpuProfiler::StartProfilingStatus = CpuProfilingStatus
Definition at line 351 of file cpu-profiler.h.
Constructor & Destructor Documentation
CpuProfiler() [1/3]
v8::internal::CpuProfiler::CpuProfiler (Isolate * isolate, CpuProfilingNamingMode naming_mode = kDebugNaming, CpuProfilingLoggingMode logging_mode = kLazyLogging) [explicit]
Definition at line 525 of file cpu-profiler.cc.
    : CpuProfiler(isolate, naming_mode, logging_mode,
                  new CpuProfilesCollection(isolate), nullptr, nullptr,
                  new ProfilerCodeObserver(isolate, code_entries_)) {}
CpuProfiler() [2/3]
v8::internal::CpuProfiler::CpuProfiler (Isolate * isolate, CpuProfilingNamingMode naming_mode, CpuProfilingLoggingMode logging_mode, CpuProfilesCollection * profiles, Symbolizer * test_symbolizer, ProfilerEventsProcessor * test_processor, ProfilerCodeObserver * test_code_observer)
Definition at line 531 of file cpu-profiler.cc.
    : isolate_(isolate),
      naming_mode_(naming_mode),
      logging_mode_(logging_mode),
      base_sampling_interval_(base::TimeDelta::FromMicroseconds(
          v8_flags.cpu_profiler_sampling_interval)),
      code_observer_(test_code_observer),
      profiles_(test_profiles),
      symbolizer_(test_symbolizer),
      processor_(test_processor),
      is_profiling_(false) {
  profiles_->set_cpu_profiler(this);
  GetProfilersManager()->AddProfiler(isolate, this);
  if (logging_mode == kEagerLogging) EnableLogging();
}
References EnableLogging(), isolate(), v8::kEagerLogging, and profiles_.
 CpuProfiler()
v8::internal::CpuProfiler::~CpuProfiler ()
Definition at line 553 of file cpu-profiler.cc.
                          {
  DCHECK(!is_profiling_);
  GetProfilersManager()->RemoveProfiler(isolate_, this);
  DisableLogging();
  profiles_.reset();
  // We don't currently expect any references to refcounted strings to be
  // maintained with zero profiles after the code map is cleared.
  DCHECK(code_entries_.strings().empty());
}
References code_entries_, v8::internal::DCHECK(), DisableLogging(), v8::internal::StringsStorage::empty(), is_profiling_, isolate_, profiles_, and v8::internal::CodeEntryStorage::strings().
CpuProfiler() [3/3]
v8::internal::CpuProfiler::CpuProfiler (const CpuProfiler &) [delete]
Member Function Documentation
AdjustSamplingInterval()
void v8::internal::CpuProfiler::AdjustSamplingInterval () [private]
Definition at line 605 of file cpu-profiler.cc.
                                         {
  if (!processor_) return;
  base::TimeDelta base_interval = ComputeSamplingInterval();
  processor_->SetSamplingInterval(base_interval);
}
References ComputeSamplingInterval(), and processor_.
Referenced by StartProfiling(), and StopProfiling().
code_entries()
CodeEntryStorage* v8::internal::CpuProfiler::code_entries () [inline]
Definition at line 382 of file cpu-profiler.h.
{ return &code_entries_; }
code_map_for_test()
InstructionStreamMap* v8::internal::CpuProfiler::code_map_for_test () [inline]
Definition at line 387 of file cpu-profiler.h.
                                            {
    return code_observer_->instruction_stream_map();
  }
CollectSample() [1/2]
void v8::internal::CpuProfiler::CollectSample (const std::optional< uint64_t > trace_id = std::nullopt)
Definition at line 620 of file cpu-profiler.cc.
                                                                    {
  if (processor_) {
    processor_->AddCurrentStack(false, trace_id);
  }
}
References processor_.
CollectSample() [2/2]
void v8::internal::CpuProfiler::CollectSample (Isolate * isolate, std::optional< uint64_t > trace_id = std::nullopt) [static]
Definition at line 615 of file cpu-profiler.cc.
                                                                      {
  GetProfilersManager()->CallCollectSample(isolate, trace_id);
}
References isolate().
Referenced by v8::CpuProfiler::CollectSample().
ComputeSamplingInterval()
base::TimeDelta v8::internal::CpuProfiler::ComputeSamplingInterval () [private]
Definition at line 601 of file cpu-profiler.cc.
                                                   {
  return profiles_->GetCommonSamplingInterval();
}
References profiles_.
Referenced by AdjustSamplingInterval(), and StartProcessorIfNotStarted().
DeleteAllProfiles()
void v8::internal::CpuProfiler::DeleteAllProfiles ()
Definition at line 463 of file cpu-profiler.cc.
                                    {
  if (is_profiling_) StopProcessor();
  ResetProfiles();
}
References is_profiling_, ResetProfiles(), and StopProcessor().
DeleteProfile()
void v8::internal::CpuProfiler::DeleteProfile (CpuProfile * profile)
Definition at line 469 of file cpu-profiler.cc.
                                                   {
  profiles_->RemoveProfile(profile);
  if (profiles_->profiles()->empty() && !is_profiling_) {
    // If this was the last profile, clean up all accessory data as well.
    ResetProfiles();
  }
}
References is_profiling_, profiles_, and ResetProfiles().
Referenced by v8::CpuProfile::Delete().
DisableLogging()
void v8::internal::CpuProfiler::DisableLogging () [private]
Definition at line 592 of file cpu-profiler.cc.
                                 {
  if (!profiling_scope_) return;
  DCHECK(profiler_listener_);
  profiling_scope_.reset();
  profiler_listener_.reset();
  code_observer_->ClearCodeMap();
}
References code_observer_, v8::internal::DCHECK(), profiler_listener_, and profiling_scope_.
Referenced by StopProfiling(), and ~CpuProfiler().
EnableLogging()
void v8::internal::CpuProfiler::EnableLogging () [private]
Definition at line 580 of file cpu-profiler.cc.
                                {
  if (profiling_scope_) return;
  if (!profiler_listener_) {
    profiler_listener_.reset(new ProfilerListener(
        isolate_, code_observer_.get(), *code_observer_->code_entries(),
        *code_observer_->weak_code_registry(), naming_mode_));
  }
  profiling_scope_.reset(
      new ProfilingScope(isolate_, profiler_listener_.get()));
}
References code_observer_, isolate_, naming_mode_, profiler_listener_, and profiling_scope_.
Referenced by CpuProfiler(), and StartProcessorIfNotStarted().
GetAllProfilersMemorySize()
size_t v8::internal::CpuProfiler::GetAllProfilersMemorySize (Isolate * isolate) [static]
Definition at line 627 of file cpu-profiler.cc.
                                                              {
  return GetProfilersManager()->GetAllProfilersMemorySize(isolate);
}
References isolate().
Referenced by v8::Isolate::GetHeapCodeAndMetadataStatistics().
GetEstimatedMemoryUsage()
size_t v8::internal::CpuProfiler::GetEstimatedMemoryUsage () const
Definition at line 631 of file cpu-profiler.cc.
                                                  {
  return code_observer_->GetEstimatedMemoryUsage();
}
References code_observer_.
GetProfile()
CpuProfile * v8::internal::CpuProfiler::GetProfile (int index)
Definition at line 458 of file cpu-profiler.cc.
                                             {
  return profiles_->profiles()->at(index).get();
}
References v8::internal::index, and profiles_.
GetProfilesCount()
int v8::internal::CpuProfiler::GetProfilesCount ()
Definition at line 452 of file cpu-profiler.cc.
                                  {
  // The count of profiles doesn't depend on a security token.
  return static_cast<int>(profiles_->profiles()->size());
}
References profiles_.
is_profiling()
bool v8::internal::CpuProfiler::is_profiling () const [inline]
Definition at line 377 of file cpu-profiler.h.
{ return is_profiling_; }
isolate()
Isolate* v8::internal::CpuProfiler::isolate () const [inline]
Definition at line 381 of file cpu-profiler.h.
{ return isolate_; }
Referenced by v8::internal::CpuProfile::AddPath(), CollectSample(), CpuProfiler(), and GetAllProfilersMemorySize().
operator=()
CpuProfiler& v8::internal::CpuProfiler::operator= (const CpuProfiler &) [delete]
processor()
ProfilerEventsProcessor* v8::internal::CpuProfiler::processor () const [inline]
Definition at line 380 of file cpu-profiler.h.
{ return processor_.get(); }
profiler_listener_for_test()
ProfilerListener* v8::internal::CpuProfiler::profiler_listener_for_test () const [inline]
Definition at line 384 of file cpu-profiler.h.
                                                       {
    return profiler_listener_.get();
  }
ResetProfiles()
void v8::internal::CpuProfiler::ResetProfiles () [private]
Definition at line 575 of file cpu-profiler.cc.
                                {
  profiles_.reset(new CpuProfilesCollection(isolate_));
  profiles_->set_cpu_profiler(this);
}
References isolate_, and profiles_.
Referenced by DeleteAllProfiles(), and DeleteProfile().
sampling_interval()
base::TimeDelta v8::internal::CpuProfiler::sampling_interval () const [inline]
Definition at line 353 of file cpu-profiler.h.
{ return base_sampling_interval_; }
Referenced by v8::internal::CpuProfilesCollection::GetCommonSamplingInterval(), and StartProcessorIfNotStarted().
set_sampling_interval()
void v8::internal::CpuProfiler::set_sampling_interval (base::TimeDelta value)
Definition at line 565 of file cpu-profiler.cc.
                                                           {
  DCHECK(!is_profiling_);
  base_sampling_interval_ = value;
}
References base_sampling_interval_, v8::internal::DCHECK(), is_profiling_, and v8::internal::value.
set_use_precise_sampling()
void v8::internal::CpuProfiler::set_use_precise_sampling (bool value)
Definition at line 570 of file cpu-profiler.cc.
                                                     {
  DCHECK(!is_profiling_);
  use_precise_sampling_ = value;
}
References v8::internal::DCHECK(), is_profiling_, use_precise_sampling_, and v8::internal::value.
StartProcessorIfNotStarted()
void v8::internal::CpuProfiler::StartProcessorIfNotStarted () [private]
Definition at line 691 of file cpu-profiler.cc.
                                             {
  if (processor_) {
    processor_->AddCurrentStack();
    return;
  }
  if (!profiling_scope_) {
    DCHECK_EQ(logging_mode_, kLazyLogging);
    EnableLogging();
  }
  if (!symbolizer_) {
    symbolizer_ =
        std::make_unique<Symbolizer>(code_observer_->instruction_stream_map());
  }
  base::TimeDelta sampling_interval = ComputeSamplingInterval();
  processor_.reset(new SamplingEventsProcessor(
      isolate_, symbolizer_.get(), code_observer_.get(), profiles_.get(),
      sampling_interval, use_precise_sampling_));
  is_profiling_ = true;
  // Enable stack sampling.
  processor_->AddCurrentStack();
  CHECK(processor_->StartSynchronously());
}
References CHECK, code_observer_, ComputeSamplingInterval(), DCHECK_EQ, EnableLogging(), is_profiling_, isolate_, v8::kLazyLogging, logging_mode_, processor_, profiles_, profiling_scope_, sampling_interval(), symbolizer_, and use_precise_sampling_.
Referenced by StartProfiling().
StartProfiling() [1/3]
CpuProfilingResult v8::internal::CpuProfiler::StartProfiling (const char * title, CpuProfilingOptions options = {}, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr)
Definition at line 641 of file cpu-profiler.cc.
                                                      {
  CpuProfilingResult result =
      profiles_->StartProfiling(title, std::move(options), std::move(delegate));
  // TODO(nicodubus): Revisit logic for if we want to do anything different for
  // kAlreadyStarted
  if (result.status == CpuProfilingStatus::kStarted ||
      result.status == CpuProfilingStatus::kAlreadyStarted) {
    TRACE_EVENT0("v8", "CpuProfiler::StartProfiling");
    AdjustSamplingInterval();
    StartProcessorIfNotStarted();
    // Collect script rundown at the start of profiling if trace category is
    // turned on
    bool source_rundown_trace_enabled;
    bool source_rundown_sources_trace_enabled;
    TRACE_EVENT_CATEGORY_GROUP_ENABLED(
        TRACE_DISABLED_BY_DEFAULT("devtools.v8-source-rundown"),
        &source_rundown_trace_enabled);
    TRACE_EVENT_CATEGORY_GROUP_ENABLED(
        TRACE_DISABLED_BY_DEFAULT("devtools.v8-source-rundown-sources"),
        &source_rundown_sources_trace_enabled);
    if (source_rundown_trace_enabled || source_rundown_sources_trace_enabled) {
      Handle<WeakArrayList> script_objects = isolate_->factory()->script_list();
      for (int i = 0; i < script_objects->length(); i++) {
        if (Tagged<HeapObject> script_object;
            script_objects->get(i).GetHeapObjectIfWeak(&script_object)) {
          Tagged<Script> script(Cast<Script>(script_object));
          if (source_rundown_trace_enabled) {
            script->TraceScriptRundown();
          }
          if (source_rundown_sources_trace_enabled) {
            script->TraceScriptRundownSources();
          }
        }
      }
    }
  }
  return result;
}
References AdjustSamplingInterval(), v8::internal::Isolate::factory(), isolate_, v8::kAlreadyStarted, v8::kStarted, profiles_, v8::base::internal::result, v8::internal::script, StartProcessorIfNotStarted(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and TRACE_EVENT_CATEGORY_GROUP_ENABLED.
StartProfiling() [2/3]
CpuProfilingResult v8::internal::CpuProfiler::StartProfiling (CpuProfilingOptions options = {}, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr)
Definition at line 635 of file cpu-profiler.cc.
                                                      {
  return StartProfiling(nullptr, std::move(options), std::move(delegate));
}
Referenced by StartProfiling().
StartProfiling() [3/3]
CpuProfilingResult v8::internal::CpuProfiler::StartProfiling (Tagged< String > title, CpuProfilingOptions options = {}, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr)
Definition at line 684 of file cpu-profiler.cc.
                                                      {
  return StartProfiling(profiles_->GetName(title), std::move(options),
                        std::move(delegate));
}
References profiles_, and StartProfiling().
StopProcessor()
void v8::internal::CpuProfiler::StopProcessor () [private]
Definition at line 747 of file cpu-profiler.cc.
                                {
  is_profiling_ = false;
  processor_->StopSynchronously();
  processor_.reset();
}
References is_profiling_, and processor_.
Referenced by DeleteAllProfiles(), and StopProfiling().
StopProfiling() [1/3]
CpuProfile * v8::internal::CpuProfiler::StopProfiling (const char * title)
Definition at line 718 of file cpu-profiler.cc.
                                                        {
  CpuProfile* profile = profiles_->Lookup(title);
  if (profile) {
    return StopProfiling(profile->id());
  }
  return nullptr;
}
References v8::internal::CpuProfile::id(), and profiles_.
Referenced by StopProfiling().
StopProfiling() [2/3]
CpuProfile * v8::internal::CpuProfiler::StopProfiling (ProfilerId id)
Definition at line 726 of file cpu-profiler.cc.
                                                    {
  if (!is_profiling_) return nullptr;
  const bool last_profile = profiles_->IsLastProfileLeft(id);
  if (last_profile) StopProcessor();
  CpuProfile* profile = profiles_->StopProfiling(id);
  AdjustSamplingInterval();
  DCHECK(profiling_scope_);
  if (last_profile && logging_mode_ == kLazyLogging) {
    DisableLogging();
  }
  return profile;
}
References AdjustSamplingInterval(), v8::internal::DCHECK(), DisableLogging(), is_profiling_, v8::kLazyLogging, logging_mode_, profiles_, profiling_scope_, and StopProcessor().
StopProfiling() [3/3]
CpuProfile * v8::internal::CpuProfiler::StopProfiling (Tagged< String > title)
Definition at line 743 of file cpu-profiler.cc.
                                                           {
  return StopProfiling(profiles_->GetName(title));
}
References profiles_, and StopProfiling().
symbolizer()
Symbolizer* v8::internal::CpuProfiler::symbolizer () const [inline]
Definition at line 379 of file cpu-profiler.h.
{ return symbolizer_.get(); }
Member Data Documentation
base_sampling_interval_
base::TimeDelta v8::internal::CpuProfiler::base_sampling_interval_ [private]
Definition at line 411 of file cpu-profiler.h.
Referenced by set_sampling_interval().
code_entries_
CodeEntryStorage v8::internal::CpuProfiler::code_entries_ [private]
Definition at line 415 of file cpu-profiler.h.
Referenced by ~CpuProfiler().
code_observer_
std::unique_ptr<ProfilerCodeObserver> v8::internal::CpuProfiler::code_observer_ [private]
Definition at line 417 of file cpu-profiler.h.
Referenced by DisableLogging(), EnableLogging(), GetEstimatedMemoryUsage(), and StartProcessorIfNotStarted().
is_profiling_
bool v8::internal::CpuProfiler::is_profiling_ [private]
Definition at line 423 of file cpu-profiler.h.
Referenced by DeleteAllProfiles(), DeleteProfile(), set_sampling_interval(), set_use_precise_sampling(), StartProcessorIfNotStarted(), StopProcessor(), StopProfiling(), and ~CpuProfiler().
isolate_
Isolate* const v8::internal::CpuProfiler::isolate_ [private]
Definition at line 405 of file cpu-profiler.h.
Referenced by EnableLogging(), ResetProfiles(), StartProcessorIfNotStarted(), StartProfiling(), and ~CpuProfiler().
logging_mode_
const LoggingMode v8::internal::CpuProfiler::logging_mode_ [private]
Definition at line 407 of file cpu-profiler.h.
Referenced by StartProcessorIfNotStarted(), and StopProfiling().
naming_mode_
const NamingMode v8::internal::CpuProfiler::naming_mode_ [private]
Definition at line 406 of file cpu-profiler.h.
Referenced by EnableLogging().
processor_
std::unique_ptr<ProfilerEventsProcessor> v8::internal::CpuProfiler::processor_ [private]
Definition at line 420 of file cpu-profiler.h.
Referenced by AdjustSamplingInterval(), CollectSample(), StartProcessorIfNotStarted(), and StopProcessor().
profiler_listener_
std::unique_ptr<ProfilerListener> v8::internal::CpuProfiler::profiler_listener_ [private]
Definition at line 421 of file cpu-profiler.h.
Referenced by DisableLogging(), and EnableLogging().
profiles_
std::unique_ptr<CpuProfilesCollection> v8::internal::CpuProfiler::profiles_ [private]
Definition at line 418 of file cpu-profiler.h.
Referenced by ComputeSamplingInterval(), CpuProfiler(), DeleteProfile(), GetProfile(), GetProfilesCount(), ResetProfiles(), StartProcessorIfNotStarted(), StartProfiling(), StopProfiling(), and ~CpuProfiler().
profiling_scope_
std::unique_ptr<ProfilingScope> v8::internal::CpuProfiler::profiling_scope_ [private]
Definition at line 422 of file cpu-profiler.h.
Referenced by DisableLogging(), EnableLogging(), StartProcessorIfNotStarted(), and StopProfiling().
symbolizer_
std::unique_ptr<Symbolizer> v8::internal::CpuProfiler::symbolizer_ [private]
Definition at line 419 of file cpu-profiler.h.
Referenced by StartProcessorIfNotStarted().
use_precise_sampling_
bool v8::internal::CpuProfiler::use_precise_sampling_ = true [private]
Definition at line 408 of file cpu-profiler.h.
Referenced by set_use_precise_sampling(), and StartProcessorIfNotStarted().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/cpu-profiler.h
/mnt/V8SourceCode/src/profiler/cpu-profiler.cc