v8::internal::compiler::AtomicOpParameters Class Reference
#include <machine-operator.h>
Public Member Functions
AtomicOpParameters (MachineType type, MemoryAccessKind kind=MemoryAccessKind::kNormal)
MachineType type () const
MemoryAccessKind kind () const
Private Attributes
MachineType type_
MemoryAccessKind kind_
Detailed Description
Definition at line 84 of file machine-operator.h.
Constructor & Destructor Documentation
AtomicOpParameters()
v8::internal::compiler::AtomicOpParameters::AtomicOpParameters (MachineType type, MemoryAccessKind kind = MemoryAccessKind::kNormal) [inline]
Definition at line 86 of file machine-operator.h.
      : type_(type), kind_(kind) {}
Member Function Documentation
kind()
MemoryAccessKind v8::internal::compiler::AtomicOpParameters::kind () const [inline]
Definition at line 91 of file machine-operator.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
type()
MachineType v8::internal::compiler::AtomicOpParameters::type () const [inline]
Definition at line 90 of file machine-operator.h.
{ return type_; }
References type_.
Referenced by v8::internal::compiler::AtomicOpType(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
kind_
MemoryAccessKind v8::internal::compiler::AtomicOpParameters::kind_ [private]
Definition at line 95 of file machine-operator.h.
Referenced by kind().
type_
MachineType v8::internal::compiler::AtomicOpParameters::type_ [private]
Definition at line 94 of file machine-operator.h.
Referenced by type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator.h