v8::internal::StringShape Class Reference
#include <string.h>
Public Member Functions
StringShape (const Tagged< String > s)
StringShape (Tagged< Map > s)
bool IsOneByte () const
bool IsTwoByte () const
bool IsSequential () const
bool IsExternal () const
bool IsCons () const
bool IsSliced () const
bool IsThin () const
bool IsDirect () const
bool IsIndirect () const
bool IsUncachedExternal () const
bool IsExternalOneByte () const
bool IsExternalTwoByte () const
bool IsSequentialOneByte () const
bool IsSequentialTwoByte () const
bool IsInternalized () const
bool IsShared () const
uint32_t encoding_tag () const
void invalidate ()
template<typename TDispatcher >
auto DispatchToSpecificType (Tagged< String > str, TDispatcher &&dispatcher) const
Private Member Functions
InstanceType map_or_type () const
void set_valid ()
Private Attributes
InstanceType type_
Detailed Description
Definition at line 58 of file string.h.
Constructor & Destructor Documentation
StringShape() [1/2]
v8::internal::StringShape::StringShape (const Tagged< String > s) [inline], [explicit]
Definition at line 152 of file string-inl.h.
    : StringShape(str->map(kAcquireLoad)) {}
StringShape() [2/2]
v8::internal::StringShape::StringShape (Tagged< Map > s) [inline], [explicit]
Definition at line 165 of file string-inl.h.
                                        : type_(map->instance_type()) {
  set_valid();
  DCHECK(InstanceTypeChecker::IsString(map));
  DCHECK(InstanceTypeChecker::IsString(map_or_type()));
}
References v8::internal::DCHECK(), map_or_type(), and set_valid().
Member Function Documentation
DispatchToSpecificType()
template<typename TDispatcher >
auto v8::internal::StringShape::DispatchToSpecificType (Tagged< String > str, TDispatcher && dispatcher) const [inline]
Definition at line 325 of file string-inl.h.
                                                                         {
  // Figure out a common return type from the possible dispatcher overloads.
  using TReturn = typename detail::common_type_handle_nullopt<
      decltype(dispatcher(Tagged<SeqOneByteString>{})),
      decltype(dispatcher(Tagged<SeqTwoByteString>{})),
      decltype(dispatcher(Tagged<ExternalOneByteString>{})),
      decltype(dispatcher(Tagged<ExternalTwoByteString>{})),
      decltype(dispatcher(Tagged<ThinString>{})),
      decltype(dispatcher(Tagged<ConsString>{})),
      decltype(dispatcher(Tagged<SlicedString>{}))>::type;
  // The following code inlines the dispatcher calls with V8_INLINE_STATEMENT.
  // This is so that this behaves, as far as the caller is concerned, like an
  // inlined type switch.
  DCHECK(IsValidFor(string));
#if V8_STATIC_ROOTS_BOOL
  // Check the string map ranges in dense increasing order, to avoid needing
  // to subtract away the lower bound. Don't use the InstanceTypeChecker::IsFoo
  // helpers, because clang doesn't realise it can avoid the subtraction.
  Tagged_t map = V8HeapCompressionScheme::CompressObject(map_.ptr());
  using StringTypeRange = InstanceTypeChecker::kUniqueMapRangeOfStringType;
  static_assert(StringTypeRange::kSeqString.first == 0);
  if (map <= StringTypeRange::kSeqString.second) {
    if ((map & InstanceTypeChecker::kStringMapEncodingMask) ==
        InstanceTypeChecker::kOneByteStringMapBit) {
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<SeqOneByteString>(string)));
    } else {
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<SeqTwoByteString>(string)));
    }
  }
  static_assert(StringTypeRange::kSeqString.second + Map::kSize ==
                StringTypeRange::kExternalString.first);
  if (map <= StringTypeRange::kExternalString.second) {
    if ((map & InstanceTypeChecker::kStringMapEncodingMask) ==
        InstanceTypeChecker::kOneByteStringMapBit) {
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<ExternalOneByteString>(string)));
    } else {
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<ExternalTwoByteString>(string)));
    }
  }
  static_assert(StringTypeRange::kExternalString.second + Map::kSize ==
                StringTypeRange::kConsString.first);
  if (map <= StringTypeRange::kConsString.second) {
    V8_INLINE_STATEMENT return static_cast<TReturn>(
        dispatcher(UncheckedCast<ConsString>(string)));
  }
  static_assert(StringTypeRange::kConsString.second + Map::kSize ==
                StringTypeRange::kSlicedString.first);
  if (map <= StringTypeRange::kSlicedString.second) {
    V8_INLINE_STATEMENT return static_cast<TReturn>(
        dispatcher(UncheckedCast<SlicedString>(string)));
  }
  static_assert(StringTypeRange::kSlicedString.second + Map::kSize ==
                StringTypeRange::kThinString.first);
  if (map <= StringTypeRange::kThinString.second) {
    V8_INLINE_STATEMENT return static_cast<TReturn>(
        dispatcher(UncheckedCast<ThinString>(string)));
  }
  [[unlikely]] if (!TryReportUnreachable(string, map_)) {
    return static_cast<TReturn>(dispatcher(
        UncheckedCast<SeqOneByteString>(GetReadOnlyRoots().empty_string())));
  }
  UNREACHABLE();
#else
  switch (type_ & kStringRepresentationAndEncodingMask) {
    case kSeqStringTag | kOneByteStringTag:
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<SeqOneByteString>(string)));
    case kSeqStringTag | kTwoByteStringTag:
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<SeqTwoByteString>(string)));
    case kConsStringTag | kOneByteStringTag:
    case kConsStringTag | kTwoByteStringTag:
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<ConsString>(string)));
    case kExternalStringTag | kOneByteStringTag:
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<ExternalOneByteString>(string)));
    case kExternalStringTag | kTwoByteStringTag:
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<ExternalTwoByteString>(string)));
    case kSlicedStringTag | kOneByteStringTag:
    case kSlicedStringTag | kTwoByteStringTag:
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<SlicedString>(string)));
    case kThinStringTag | kOneByteStringTag:
    case kThinStringTag | kTwoByteStringTag:
      V8_INLINE_STATEMENT return static_cast<TReturn>(
          dispatcher(UncheckedCast<ThinString>(string)));
    default:
      UNREACHABLE();
  }
  UNREACHABLE();
#endif
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), v8::internal::DCHECK(), v8::internal::GetReadOnlyRoots(), v8::internal::kConsStringTag, v8::internal::kExternalStringTag, v8::internal::kOneByteStringTag, v8::internal::kSeqStringTag, v8::internal::kSlicedStringTag, v8::internal::kStringRepresentationAndEncodingMask, v8::internal::kThinStringTag, v8::internal::kTwoByteStringTag, v8::internal::tracing::type, type_, v8::internal::UNREACHABLE(), and V8_INLINE_STATEMENT.
Referenced by v8::internal::String::AddressOfCharacterAt(), v8::internal::String::DispatchToSpecificType(), and v8::internal::anonymous_namespace{string.cc}::WriteNonConsToFlat2().
encoding_tag()
uint32_t v8::internal::StringShape::encoding_tag () const [inline]
invalidate()
void v8::internal::StringShape::invalidate () [inline]
Definition at line 83 of file string.h.
{}
IsCons()
bool v8::internal::StringShape::IsCons () const [inline]
Definition at line 185 of file string-inl.h.
                               {
  return InstanceTypeChecker::IsConsString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsConsString(), and map_or_type().
Referenced by v8::internal::String::AddressOfCharacterAt(), v8::internal::String::ComputeAndSetRawHash(), v8::internal::DEF_HEAP_OBJECT_PREDICATE(), v8::internal::String::PrefixForDebugPrint(), v8::internal::requires(), and v8::internal::anonymous_namespace{string.cc}::WriteNonConsToFlat2().
IsDirect()
bool v8::internal::StringShape::IsDirect () const [inline]
Definition at line 201 of file string-inl.h.
                                 {
  return InstanceTypeChecker::IsDirectString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsDirectString(), and map_or_type().
Referenced by v8::internal::requires().
IsExternal()
bool v8::internal::StringShape::IsExternal () const [inline]
Definition at line 205 of file string-inl.h.
                                   {
  return InstanceTypeChecker::IsExternalString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsExternalString(), and map_or_type().
Referenced by v8::internal::LogFile::MessageBuilder::AppendSymbolNameDetails(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::ExternalizeStringExtension::Externalize(), v8::internal::String::GetDirectStringChars(), v8::anonymous_namespace{api.cc}::HasExternalStringResource(), v8::internal::JsonParser< Char >::JsonParser(), v8::internal::String::MakeThin(), v8::internal::String::PrefixForDebugPrint(), v8::internal::String::SupportsExternalization(), and v8::internal::JsonParser< Char >::~JsonParser().
IsExternalOneByte()
bool v8::internal::StringShape::IsExternalOneByte () const [inline]
Definition at line 442 of file string-inl.h.
                                          {
  return InstanceTypeChecker::IsExternalString(map_or_type()) &&
         InstanceTypeChecker::IsOneByteString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsOneByteString(), and map_or_type().
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE(), v8::String::GetExternalStringResourceBaseSlow(), v8::String::IsExternalOneByte(), and v8::internal::InternalizedStringKey::PrepareForInsertion().
IsExternalTwoByte()
bool v8::internal::StringShape::IsExternalTwoByte () const [inline]
Definition at line 447 of file string-inl.h.
                                          {
  return InstanceTypeChecker::IsExternalString(map_or_type()) &&
         InstanceTypeChecker::IsTwoByteString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsTwoByteString(), and map_or_type().
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE(), v8::String::GetExternalStringResourceBaseSlow(), v8::String::IsExternalTwoByte(), v8::internal::InternalizedStringKey::PrepareForInsertion(), and v8::String::VerifyExternalStringResourceBase().
IsIndirect()
bool v8::internal::StringShape::IsIndirect () const [inline]
Definition at line 197 of file string-inl.h.
                                   {
  return InstanceTypeChecker::IsIndirectString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsIndirectString(), and map_or_type().
Referenced by v8::internal::String::MakeExternal(), and v8::internal::String::MakeThin().
IsInternalized()
bool v8::internal::StringShape::IsInternalized () const [inline]
Definition at line 180 of file string-inl.h.
                                       {
  DCHECK(valid());
  return InstanceTypeChecker::IsInternalizedString(map_or_type());
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsInternalizedString(), and map_or_type().
Referenced by v8::internal::LogFile::MessageBuilder::AppendSymbolNameDetails(), v8::internal::anonymous_namespace{string.cc}::ComputeExternalStringMap(), v8::internal::String::PrefixForDebugPrint(), and v8::internal::String::SuffixForDebugPrint().
IsOneByte()
bool v8::internal::StringShape::IsOneByte () const [inline]
Definition at line 172 of file string-inl.h.
                                  {
  return InstanceTypeChecker::IsOneByteString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsOneByteString(), and map_or_type().
Referenced by v8::internal::String::ComputeAndSetRawHash(), and v8::internal::String::SupportsExternalization().
IsSequential()
bool v8::internal::StringShape::IsSequential () const [inline]
Definition at line 209 of file string-inl.h.
                                     {
  return InstanceTypeChecker::IsSeqString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsSeqString(), and map_or_type().
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE().
IsSequentialOneByte()
bool v8::internal::StringShape::IsSequentialOneByte () const [inline]
Definition at line 432 of file string-inl.h.
                                            {
  return InstanceTypeChecker::IsSeqString(map_or_type()) &&
         InstanceTypeChecker::IsOneByteString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsOneByteString(), v8::internal::InstanceTypeChecker::IsSeqString(), and map_or_type().
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE(), and v8::internal::anonymous_namespace{objects.cc}::WriteFixedArrayToFlat().
IsSequentialTwoByte()
bool v8::internal::StringShape::IsSequentialTwoByte () const [inline]
Definition at line 437 of file string-inl.h.
                                            {
  return InstanceTypeChecker::IsSeqString(map_or_type()) &&
         InstanceTypeChecker::IsTwoByteString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsSeqString(), v8::internal::InstanceTypeChecker::IsTwoByteString(), and map_or_type().
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE().
IsShared()
bool v8::internal::StringShape::IsShared () const [inline]
Definition at line 217 of file string-inl.h.
                                 {
  return InstanceTypeChecker::IsSharedString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsSharedString(), and map_or_type().
Referenced by v8::internal::anonymous_namespace{string.cc}::ComputeExternalStringMap(), v8::internal::String::IsShared(), v8::internal::String::MakeThin(), and v8::internal::InternalizedStringKey::PrepareForInsertion().
IsSliced()
bool v8::internal::StringShape::IsSliced () const [inline]
Definition at line 193 of file string-inl.h.
                                 {
  return InstanceTypeChecker::IsSlicedString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsSlicedString(), and map_or_type().
Referenced by v8::internal::String::AddressOfCharacterAt(), v8::internal::String::ComputeAndSetRawHash(), and v8::internal::DEF_HEAP_OBJECT_PREDICATE().
IsThin()
bool v8::internal::StringShape::IsThin () const [inline]
Definition at line 189 of file string-inl.h.
                               {
  return InstanceTypeChecker::IsThinString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsThinString(), and map_or_type().
Referenced by v8::internal::String::AddressOfCharacterAt(), v8::internal::String::ComputeAndSetRawHash(), v8::internal::DEF_HEAP_OBJECT_PREDICATE(), v8::internal::String::MakeThin(), v8::internal::String::PrefixForDebugPrint(), and v8::internal::requires().
IsTwoByte()
bool v8::internal::StringShape::IsTwoByte () const [inline]
Definition at line 176 of file string-inl.h.
                                  {
  return InstanceTypeChecker::IsTwoByteString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsTwoByteString(), and map_or_type().
IsUncachedExternal()
bool v8::internal::StringShape::IsUncachedExternal () const [inline]
Definition at line 213 of file string-inl.h.
                                           {
  return InstanceTypeChecker::IsUncachedExternalString(map_or_type());
}
References v8::internal::InstanceTypeChecker::IsUncachedExternalString(), and map_or_type().
Referenced by v8::internal::InternalizedStringKey::PrepareForInsertion().
map_or_type()
InstanceType v8::internal::StringShape::map_or_type () const [inline], [private]
Definition at line 99 of file string.h.
{ return type_; }
References type_.
Referenced by IsCons(), IsDirect(), IsExternal(), IsExternalOneByte(), IsExternalTwoByte(), IsIndirect(), IsInternalized(), IsOneByte(), IsSequential(), IsSequentialOneByte(), IsSequentialTwoByte(), IsShared(), IsSliced(), IsThin(), IsTwoByte(), IsUncachedExternal(), and StringShape().
set_valid()
void v8::internal::StringShape::set_valid () [inline], [private]
Definition at line 106 of file string.h.
{}
Referenced by StringShape().
Member Data Documentation
type_
InstanceType v8::internal::StringShape::type_ [private]
Definition at line 100 of file string.h.
Referenced by DispatchToSpecificType(), and map_or_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h