v8::internal::PropertyDetails Class Reference
#include <property-details.h>
Public Types
enum PrintMode {
kPrintAttributes = 1 << 0
, kPrintFieldIndex = 1 << 1
, kPrintRepresentation = 1 << 2
, kPrintPointer = 1 << 3
,
kForProperties = kPrintFieldIndex | kPrintAttributes
, kForTransitions = kPrintAttributes
, kPrintFull = -1
 }
using KindField = base::BitField< PropertyKind, 0, 1 >
using ConstnessField = KindField::Next< PropertyConstness, 1 >
using AttributesField = ConstnessField::Next< PropertyAttributes, 3 >
using PropertyCellTypeField = AttributesField::Next< PropertyCellType, 3 >
using DictionaryStorageField = PropertyCellTypeField::Next< uint32_t, 23 >
using LocationField = AttributesField::Next< PropertyLocation, 1 >
using RepresentationField = LocationField::Next< uint32_t, 3 >
using DescriptorPointer = RepresentationField::Next< uint32_t, kDescriptorIndexBitCount >
using FieldIndexField = DescriptorPointer::Next< uint32_t, kDescriptorIndexBitCount >
Public Member Functions
constexpr PropertyDetails (PropertyKind kind, PropertyAttributes attributes, PropertyCellType cell_type, int dictionary_index=0)
constexpr PropertyDetails (PropertyKind kind, PropertyAttributes attributes, PropertyConstness constness, int dictionary_index=0)
constexpr PropertyDetails (PropertyKind kind, PropertyAttributes attributes, PropertyLocation location, PropertyConstness constness, Representation representation, int field_index=0)
bool operator== (PropertyDetails const &other) const
bool operator!= (PropertyDetails const &other) const
int pointer () const
PropertyDetails set_pointer (int i) const
PropertyDetails set_cell_type (PropertyCellType type) const
PropertyDetails set_index (int index) const
PropertyDetails CopyWithRepresentation (Representation representation) const
PropertyDetails CopyWithConstness (PropertyConstness constness) const
PropertyDetails CopyAddAttributes (PropertyAttributes new_attributes) const
PropertyDetails (Tagged< Smi > smi)
Tagged< Smi > AsSmi () const
PropertyKind kind () const
PropertyLocation location () const
PropertyConstness constness () const
PropertyAttributes attributes () const
bool HasKindAndAttributes (PropertyKind kind, PropertyAttributes attributes)
int dictionary_index () const
Representation representation () const
int field_index () const
int field_width_in_words () const
bool IsReadOnly () const
bool IsConfigurable () const
bool IsDontEnum () const
bool IsEnumerable () const
PropertyCellType cell_type () const
void PrintAsSlowTo (std::ostream &out, bool print_dict_index)
void PrintAsFastTo (std::ostream &out, PrintMode mode=kPrintFull)
uint8_t ToByte ()
Static Public Member Functions
static constexpr PropertyDetails Empty (PropertyCellType cell_type=PropertyCellType::kNoCell)
static constexpr uint8_t EncodeRepresentation (Representation representation)
static Representation DecodeRepresentation (uint32_t bits)
static bool IsValidIndex (int index)
static PropertyDetails FromByte (uint8_t encoded_details)
Static Public Attributes
static const int kAttributesReadOnlyMask
static const int kAttributesDontDeleteMask
static const int kAttributesDontEnumMask
static const int kInitialIndex = 1
static constexpr PropertyConstness kConstIfDictConstnessTracking
Private Member Functions
PropertyDetails (int value, int pointer)
PropertyDetails (int value, Representation representation)
PropertyDetails (int value, PropertyConstness constness)
PropertyDetails (int value, PropertyAttributes attributes)
PropertyDetails (uint32_t value)
Private Attributes
uint32_t value_
Detailed Description
Definition at line 267 of file property-details.h.
Member Typedef Documentation
AttributesField
using v8::internal::PropertyDetails::AttributesField = ConstnessField::Next<PropertyAttributes, 3>
Definition at line 402 of file property-details.h.
ConstnessField
using v8::internal::PropertyDetails::ConstnessField = KindField::Next<PropertyConstness, 1>
Definition at line 401 of file property-details.h.
DescriptorPointer
using v8::internal::PropertyDetails::DescriptorPointer = RepresentationField::Next<uint32_t, kDescriptorIndexBitCount>
Definition at line 417 of file property-details.h.
DictionaryStorageField
using v8::internal::PropertyDetails::DictionaryStorageField = PropertyCellTypeField::Next<uint32_t, 23>
Definition at line 412 of file property-details.h.
FieldIndexField
using v8::internal::PropertyDetails::FieldIndexField = DescriptorPointer::Next<uint32_t, kDescriptorIndexBitCount>
Definition at line 419 of file property-details.h.
KindField
using v8::internal::PropertyDetails::KindField = base::BitField<PropertyKind, 0, 1>
Definition at line 400 of file property-details.h.
LocationField
using v8::internal::PropertyDetails::LocationField = AttributesField::Next<PropertyLocation, 1>
Definition at line 415 of file property-details.h.
PropertyCellTypeField
using v8::internal::PropertyDetails::PropertyCellTypeField = AttributesField::Next<PropertyCellType, 3>
Definition at line 411 of file property-details.h.
RepresentationField
using v8::internal::PropertyDetails::RepresentationField = LocationField::Next<uint32_t, 3>
Definition at line 416 of file property-details.h.
Member Enumeration Documentation
PrintMode
enum v8::internal::PropertyDetails::PrintMode
Enumerator
kPrintAttributes
kPrintFieldIndex
kPrintRepresentation
kPrintPointer
kForProperties
kForTransitions
kPrintFull
Definition at line 447 of file property-details.h.
                 {
    kPrintAttributes = 1 << 0,
    kPrintFieldIndex = 1 << 1,
    kPrintRepresentation = 1 << 2,
    kPrintPointer = 1 << 3,
    kForProperties = kPrintFieldIndex | kPrintAttributes,
    kForTransitions = kPrintAttributes,
    kPrintFull = -1,
  };
Constructor & Destructor Documentation
PropertyDetails() [1/9]
constexpr v8::internal::PropertyDetails::PropertyDetails (PropertyKind kind, PropertyAttributes attributes, PropertyCellType cell_type, int dictionary_index = 0) [inline], [constexpr]
Definition at line 270 of file property-details.h.
      : value_(KindField::encode(kind) |
               LocationField::encode(PropertyLocation::kField) |
               AttributesField::encode(attributes) |
               // We track PropertyCell constness via PropertyCellTypeField,
               // so we set ConstnessField to kMutable to simplify DCHECKs
               // related to non-global property constness tracking.
               ConstnessField::encode(PropertyConstness::kMutable) |
               DictionaryStorageField::encode(dictionary_index) |
               PropertyCellTypeField::encode(cell_type)) {}
References v8::internal::kMutable.
Referenced by CopyAddAttributes(), CopyWithConstness(), CopyWithRepresentation(), Empty(), and set_pointer().
PropertyDetails() [2/9]
constexpr v8::internal::PropertyDetails::PropertyDetails (PropertyKind kind, PropertyAttributes attributes, PropertyConstness constness, int dictionary_index = 0) [inline], [constexpr]
Definition at line 284 of file property-details.h.
      : value_(KindField::encode(kind) |
               LocationField::encode(PropertyLocation::kField) |
               AttributesField::encode(attributes) |
               ConstnessField::encode(constness) |
               DictionaryStorageField::encode(dictionary_index) |
               PropertyCellTypeField::encode(PropertyCellType::kNoCell)) {}
References v8::internal::kNoCell.
PropertyDetails() [3/9]
constexpr v8::internal::PropertyDetails::PropertyDetails (PropertyKind kind, PropertyAttributes attributes, PropertyLocation location, PropertyConstness constness, Representation representation, int field_index = 0) [inline], [constexpr]
Definition at line 295 of file property-details.h.
      : value_(
            KindField::encode(kind) | AttributesField::encode(attributes) |
            LocationField::encode(location) |
            ConstnessField::encode(constness) |
            RepresentationField::encode(EncodeRepresentation(representation)) |
            FieldIndexField::encode(field_index)) {}
PropertyDetails() [4/9]
v8::internal::PropertyDetails::PropertyDetails (Tagged< Smi > smi) [inline], [explicit]
Definition at line 78 of file objects-inl.h.
{ value_ = smi.value(); }
References v8::internal::Tagged< Smi >::value(), and value_.
PropertyDetails() [5/9]
v8::internal::PropertyDetails::PropertyDetails (int value, int pointer) [inline], [private]
Definition at line 494 of file property-details.h.
                                          {
    value_ = DescriptorPointer::update(value, pointer);
  }
References pointer(), v8::base::BitField< T, shift, size, U >::update(), v8::internal::value, and value_.
PropertyDetails() [6/9]
v8::internal::PropertyDetails::PropertyDetails (int value, Representation representation) [inline], [private]
Definition at line 497 of file property-details.h.
                                                            {
    value_ = RepresentationField::update(value,
                                         EncodeRepresentation(representation));
  }
References EncodeRepresentation(), representation(), v8::base::BitField< T, shift, size, U >::update(), v8::internal::value, and value_.
PropertyDetails() [7/9]
v8::internal::PropertyDetails::PropertyDetails (int value, PropertyConstness constness) [inline], [private]
Definition at line 501 of file property-details.h.
                                                          {
    value_ = ConstnessField::update(value, constness);
  }
References constness(), v8::base::BitField< T, shift, size, U >::update(), v8::internal::value, and value_.
PropertyDetails() [8/9]
v8::internal::PropertyDetails::PropertyDetails (int value, PropertyAttributes attributes) [inline], [private]
Definition at line 504 of file property-details.h.
                                                            {
    value_ = AttributesField::update(value, attributes);
  }
References attributes(), v8::base::BitField< T, shift, size, U >::update(), v8::internal::value, and value_.
PropertyDetails() [9/9]
v8::internal::PropertyDetails::PropertyDetails (uint32_t value) [inline], [explicit], [private]
Definition at line 508 of file property-details.h.
: value_{value} {}
Member Function Documentation
AsSmi()
Tagged< Smi > v8::internal::PropertyDetails::AsSmi () const [inline]
Definition at line 80 of file objects-inl.h.
                                         {
  // Ensure the upper 2 bits have the same value by sign extending it. This is
  // necessary to be able to use the 31st bit of the property details.
  int value = value_ << 1;
  return Smi::FromInt(value >> 1);
}
References v8::internal::Smi::FromInt(), v8::internal::value, and value_.
Referenced by v8::internal::OrderedNameDictionary::Add(), v8::internal::SmallOrderedNameDictionary::Add(), v8::internal::ApiNatives::AddAccessorProperty(), v8::internal::ApiNatives::AddDataProperty(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::Factory::NewPropertyCell(), v8::internal::LookupIterator::ReconfigureDataProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::DescriptorArray::SetDetails(), v8::internal::OrderedNameDictionary::SetEntry(), v8::internal::SmallOrderedNameDictionary::SetEntry(), and v8::internal::PropertyCell::Transition().
attributes()
PropertyAttributes v8::internal::PropertyDetails::attributes () const [inline]
Definition at line 365 of file property-details.h.
                                        {
    return AttributesField::decode(value_);
  }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::anonymous_namespace{keys.cc}::CollectOwnPropertyNamesInternal(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance(), v8::internal::MapUpdater::ConstructNewMap(), CopyAddAttributes(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::FilterKey(), v8::internal::MapUpdater::FindRootMap(), v8::internal::MapUpdater::FindSplitMap(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::TransitionsAccessor::FindTransitionToField(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetEntryForIndexImpl(), HasKindAndAttributes(), v8::internal::TransitionsAccessor::InsertHelper(), v8::internal::wasm::JSPrototypesSetup::InstallExport(), IsConfigurable(), IsDontEnum(), v8::internal::TransitionsAccessor::IsExpectedTransition(), IsReadOnly(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::Factory::NewJSGlobalObject(), v8::internal::SwissNameDictionary::NumberOfEnumerableProperties(), PrintAsFastTo(), PrintAsSlowTo(), PropertyDetails(), v8::internal::LookupIterator::ReconfigureDataProperty(), v8::internal::TransitionArray::SearchDetails(), v8::internal::TransitionArray::SearchDetailsAndGetTarget(), v8::internal::TransitionArray::Sort(), v8::internal::StoreHandler::StoreOwnTransition(), v8::internal::StoreHandler::StoreTransition(), v8::internal::Genesis::TransferNamedProperties(), v8::internal::Map::TransitionToAccessorProperty(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), v8::internal::MapUpdater::TryReconfigureToDataFieldInplace(), v8::internal::Map::TryReplayPropertyTransitions(), and v8::internal::MapUpdater::UpdateFieldType().
cell_type()
PropertyCellType v8::internal::PropertyDetails::cell_type () const [inline]
Definition at line 394 of file property-details.h.
                                     {
    return PropertyCellTypeField::decode(value_);
  }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by v8::internal::compiler::PropertyCellData::Cache(), v8::internal::PropertyCell::CheckDataIsCompatible(), v8::internal::compiler::CompilationDependencies::DependOnGlobalProperty(), Empty(), FromByte(), v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), ToByte(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore(), and v8::internal::PropertyCell::UpdatedType().
constness()
PropertyConstness v8::internal::PropertyDetails::constness () const [inline]
Definition at line 363 of file property-details.h.
{ return ConstnessField::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::anonymous_namespace{map.cc}::CanHoldValue(), v8::internal::LookupIterator::CanStayConst(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputeDictionaryProtoAccessInfo(), v8::internal::MapUpdater::ConstructNewMap(), CopyWithConstness(), v8::internal::compiler::CompilationDependencies::DependOnFieldConstness(), v8::internal::LookupIterator::DictCanStayConst(), v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord(), v8::internal::MapUpdater::FindSplitMap(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::MapUpdater::GeneralizeField(), v8::internal::Map::GetFieldCounts(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::GetHolderIfValid(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::JSObject::MigrateSlowToFast(), PrintAsFastTo(), PrintAsSlowTo(), PropertyDetails(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::MapUpdater::ReconfigureToDataField(), v8::internal::JSProxy::SetPrivateSymbol(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), v8::internal::MapUpdater::TryReconfigureToDataFieldInplace(), v8::internal::Map::TryReplayPropertyTransitions(), v8::internal::MapUpdater::UpdateFieldType(), and v8::internal::LookupIterator::WriteDataValue().
CopyAddAttributes()
PropertyDetails v8::internal::PropertyDetails::CopyAddAttributes (PropertyAttributes new_attributes) const [inline]
Definition at line 343 of file property-details.h.
                                                                             {
    new_attributes =
        static_cast<PropertyAttributes>(attributes() | new_attributes);
    return PropertyDetails(value_, new_attributes);
  }
References attributes(), PropertyDetails(), and value_.
Referenced by v8::internal::JSObject::ApplyAttributesToDictionary(), v8::internal::DescriptorArray::CopyUpToAddAttributes(), and v8::internal::LookupIterator::LookupInRegularHolder().
CopyWithConstness()
PropertyDetails v8::internal::PropertyDetails::CopyWithConstness (PropertyConstness constness) const [inline]
Definition at line 340 of file property-details.h.
                                                                       {
    return PropertyDetails(value_, constness);
  }
References constness(), PropertyDetails(), and value_.
Referenced by v8::internal::DescriptorArray::GeneralizeAllFields(), v8::internal::JSObject::OptimizeAsPrototype(), and v8::internal::LookupIterator::PrepareForDataProperty().
CopyWithRepresentation()
PropertyDetails v8::internal::PropertyDetails::CopyWithRepresentation (Representation representation) const [inline]
Definition at line 337 of file property-details.h.
                                                                              {
    return PropertyDetails(value_, representation);
  }
References PropertyDetails(), representation(), and value_.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), and v8::internal::DescriptorArray::GeneralizeAllFields().
DecodeRepresentation()
static Representation v8::internal::PropertyDetails::DecodeRepresentation (uint32_t bits) [inline], [static]
Definition at line 357 of file property-details.h.
                                                            {
    return Representation::FromKind(static_cast<Representation::Kind>(bits));
  }
References v8::internal::Representation::FromKind().
Referenced by representation().
dictionary_index()
int v8::internal::PropertyDetails::dictionary_index () const [inline]
Definition at line 374 of file property-details.h.
                               {
    return DictionaryStorageField::decode(value_);
  }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by FromByte(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::EnumIndexComparator< Dictionary >::operator()(), v8::internal::PropertyCell::PrepareForAndSetValue(), PrintAsSlowTo(), v8::internal::LookupIterator::ReconfigureDataProperty(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::ReconfigureImpl(), v8::internal::JSObject::SetNormalizedProperty(), and ToByte().
Empty()
static constexpr PropertyDetails v8::internal::PropertyDetails::Empty (PropertyCellType cell_type = PropertyCellType::kNoCell) [inline], [static], [constexpr]
Definition at line 306 of file property-details.h.
                                                            {
    return PropertyDetails(PropertyKind::kData, NONE, cell_type);
  }
References cell_type(), v8::internal::kData, v8::internal::NONE, and PropertyDetails().
Referenced by v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::anonymous_namespace{templates.cc}::CreateSlowJSObjectWithProperties(), v8::internal::OrderedNameDictionary::DeleteEntry(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::GetNameTable(), v8::internal::TransitionsAccessor::InsertHelper(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::Factory::NewProtector(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::NormalizeImpl(), v8::internal::SwissNameDictionary::Rehash(), v8::internal::LookupIterator::RestartInternal(), v8::internal::JsonStringifier::SerializeJSObject(), v8::internal::SimpleNameDictionary::Set(), v8::internal::SimpleNumberDictionary::Set(), and v8::internal::NumberDictionary::UncheckedSet().
EncodeRepresentation()
static constexpr uint8_t v8::internal::PropertyDetails::EncodeRepresentation (Representation representation) [inline], [static], [constexpr]
Definition at line 353 of file property-details.h.
                                                                               {
    return representation.kind();
  }
References v8::internal::Representation::kind(), and representation().
Referenced by PropertyDetails().
field_index()
int v8::internal::PropertyDetails::field_index () const [inline]
Definition at line 382 of file property-details.h.
{ return FieldIndexField::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::FieldIndex::ForDetails(), v8::internal::DescriptorArray::GetFieldIndex(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::Map::NextFreePropertyIndex(), PrintAsFastTo(), v8::internal::FastJsonStringifier< Char >::ResumeJSObject(), v8::internal::DescriptorArray::Search(), and v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk().
field_width_in_words()
int v8::internal::PropertyDetails::field_width_in_words () const [inline]
Definition at line 87 of file objects-inl.h.
                                                {
  DCHECK_EQ(location(), PropertyLocation::kField);
  return 1;
}
References DCHECK_EQ, v8::internal::kField, and location().
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::JSObject::MigrateSlowToFast(), and v8::internal::Map::NextFreePropertyIndex().
FromByte()
static PropertyDetails v8::internal::PropertyDetails::FromByte (uint8_t encoded_details) [inline], [static]
Definition at line 482 of file property-details.h.
                                                           {
    // The 0-extension to 32bit sets PropertyLocation to kField,
    // PropertyCellType to kNoCell, and enumeration index to 0, as intended.
    // Everything else is obtained from |encoded_details|.
    PropertyDetails details(encoded_details);
    DCHECK_EQ(PropertyLocation::kField, details.location());
    DCHECK_EQ(PropertyCellType::kNoCell, details.cell_type());
    DCHECK_EQ(0, details.dictionary_index());
    return details;
  }
References cell_type(), DCHECK_EQ, dictionary_index(), v8::internal::kField, v8::internal::kNoCell, and location().
Referenced by v8::internal::SwissNameDictionary::DetailsAt().
HasKindAndAttributes()
bool v8::internal::PropertyDetails::HasKindAndAttributes (PropertyKind kind, PropertyAttributes attributes) [inline]
Definition at line 369 of file property-details.h.
                                                                              {
    return (value_ & (KindField::kMask | AttributesField::kMask)) ==
           (KindField::encode(kind) | AttributesField::encode(attributes));
  }
References attributes(), v8::base::BitField< T, shift, size, U >::encode(), kind(), v8::base::BitField< T, shift, size, U >::kMask, and value_.
IsConfigurable()
bool v8::internal::PropertyDetails::IsConfigurable () const [inline]
Definition at line 391 of file property-details.h.
{ return (attributes() & DONT_DELETE) == 0; }
References attributes(), and v8::internal::DONT_DELETE.
Referenced by v8::internal::anonymous_namespace{ic.cc}::GetCloneModeForMap(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetLengthImpl(), v8::internal::anonymous_namespace{js-objects.cc}::TestDictionaryPropertiesIntegrityLevel(), v8::internal::anonymous_namespace{js-objects.cc}::TestFastPropertiesIntegrityLevel(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad().
IsDontEnum()
bool v8::internal::PropertyDetails::IsDontEnum () const [inline]
Definition at line 392 of file property-details.h.
{ return (attributes() & DONT_ENUM) != 0; }
References attributes(), and v8::internal::DONT_ENUM.
Referenced by v8::internal::KeyAccumulator::CollectOwnPropertyNames(), v8::internal::anonymous_namespace{keys.cc}::CommonCopyEnumKeysTo(), v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), IsEnumerable(), v8::internal::JsonParser< Char >::ParseJsonObjectProperties(), v8::internal::FastJsonStringifier< Char >::ResumeJSObject(), v8::internal::JsonStringifier::SerializeJSObject(), and v8::internal::ValueSerializer::WriteJSObject().
IsEnumerable()
bool v8::internal::PropertyDetails::IsEnumerable () const [inline]
Definition at line 393 of file property-details.h.
{ return !IsDontEnum(); }
References IsDontEnum().
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntriesImpl(), v8::internal::Descriptor::Descriptor(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), and v8::internal::anonymous_namespace{ic.cc}::GetCloneModeForMap().
IsReadOnly()
bool v8::internal::PropertyDetails::IsReadOnly () const [inline]
Definition at line 390 of file property-details.h.
{ return (attributes() & READ_ONLY) != 0; }
References attributes(), and v8::internal::READ_ONLY.
Referenced by v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::compiler::CompilationDependencies::DependOnGlobalProperty(), v8::internal::anonymous_namespace{ic.cc}::GetCloneModeForMap(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::anonymous_namespace{js-objects.cc}::TestDictionaryPropertiesIntegrityLevel(), v8::internal::anonymous_namespace{js-objects.cc}::TestFastPropertiesIntegrityLevel(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore().
IsValidIndex()
static bool v8::internal::PropertyDetails::IsValidIndex (int index) [inline], [static]
Definition at line 386 of file property-details.h.
                                      {
    return DictionaryStorageField::is_valid(index);
  }
References v8::internal::index, and v8::base::BitField< T, shift, size, U >::is_valid().
kind()
PropertyKind v8::internal::PropertyDetails::kind () const [inline]
Definition at line 361 of file property-details.h.
{ return KindField::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::JSObject::ApplyAttributesToDictionary(), v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::Map::CanBeDeprecated(), v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral(), v8::internal::anonymous_namespace{map.cc}::CanHoldValue(), v8::internal::PropertyCell::CheckDataIsCompatible(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntriesImpl(), v8::internal::LookupIterator::CompareAndSwapDataValue(), v8::internal::compiler::AccessInfoFactory::ComputeDictionaryProtoAccessInfo(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance(), v8::internal::MapUpdater::ConstructNewMap(), v8::internal::DescriptorArray::CopyUpToAddAttributes(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::LookupIterator::FetchValue(), v8::internal::MapUpdater::FindRootMap(), v8::internal::MapUpdater::FindSplitMap(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::TransitionsAccessor::FindTransitionToField(), v8::internal::DescriptorArray::GeneralizeAllFields(), v8::internal::LookupIterator::GetAccessorIndex(), v8::internal::anonymous_namespace{ic.cc}::GetCloneModeForMap(), v8::internal::LookupIterator::GetDataValue(), v8::internal::LookupIterator::GetFieldDescriptorIndex(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::GetHolderIfValid(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::HasAccessorsImpl(), HasKindAndAttributes(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl(), v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::TransitionsAccessor::InsertHelper(), v8::internal::DescriptorArray::IsEqualUpTo(), v8::internal::TransitionsAccessor::IsExpectedTransition(), v8::internal::LookupIterator::LookupInRegularHolder(), v8::internal::LookupIterator::LookupInSpecialHolder(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::Factory::NewJSGlobalObject(), v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::LookupIterator::PrepareForDataProperty(), PrintAsFastTo(), PrintAsSlowTo(), v8::internal::StringStream::PrintUsingMap(), v8::internal::LookupIterator::RecheckTypedArrayBounds(), v8::internal::MapUpdater::ReconfigureToDataField(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::FastJsonStringifier< Char >::ResumeJSObject(), v8::internal::TransitionArray::SearchDetails(), v8::internal::TransitionArray::SearchDetailsAndGetTarget(), v8::internal::JsonStringifier::SerializeJSObject(), v8::internal::JSObject::SlowReverseLookup(), v8::internal::TransitionArray::Sort(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), v8::internal::LookupIterator::SwapDataValue(), v8::internal::anonymous_namespace{js-objects.cc}::TestDictionaryPropertiesIntegrityLevel(), v8::internal::anonymous_namespace{js-objects.cc}::TestFastPropertiesIntegrityLevel(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), v8::internal::Genesis::TransferNamedProperties(), v8::internal::Map::TransitionToAccessorProperty(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), v8::internal::MapUpdater::TryReconfigureToDataFieldInplace(), v8::internal::Map::TryReplayPropertyTransitions(), v8::internal::MapUpdater::UpdateFieldType(), v8::internal::LookupIterator::WriteDataValue(), v8::internal::ValueSerializer::WriteJSObject(), and v8::internal::JSObject::WriteToField().
location()
PropertyLocation v8::internal::PropertyDetails::location () const [inline]
Definition at line 362 of file property-details.h.
{ return LocationField::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::Map::AppendDescriptor(), v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::Map::CanBeDeprecated(), v8::internal::anonymous_namespace{map.cc}::CanHoldValue(), v8::internal::LookupIterator::CanStayConst(), v8::internal::LookupIterator::CompareAndSwapDataValue(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::MapUpdater::ConstructNewMap(), v8::internal::Map::CopyReplaceDescriptor(), v8::internal::Map::EquivalentToForElementsKindTransition(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::LookupIterator::FetchValue(), field_width_in_words(), v8::internal::MapUpdater::FindRootMap(), v8::internal::MapUpdater::FindSplitMap(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::TransitionsAccessor::FindTransitionToField(), FromByte(), v8::internal::DescriptorArray::GeneralizeAllFields(), v8::internal::LookupIterator::GetAccessorIndex(), v8::internal::LookupIterator::GetDataValue(), v8::internal::Map::GetFieldCounts(), v8::internal::LookupIterator::GetFieldDescriptorIndex(), v8::internal::LookupIterator::GetFieldIndex(), v8::internal::FieldStatsCollector::GetInobjectFieldStats(), v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::Map::InstallDescriptors(), v8::internal::DescriptorArray::IsEqualUpTo(), v8::internal::TransitionsAccessor::IsExpectedTransition(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::Map::NextFreePropertyIndex(), v8::internal::JsonParser< Char >::ParseJsonObjectProperties(), PrintAsFastTo(), v8::internal::DescriptorArray::PrintDescriptorDetails(), v8::internal::StringStream::PrintUsingMap(), v8::internal::MapUpdater::ReconfigureToDataField(), v8::internal::ObjectStatsCollectorImpl::RecordPotentialDescriptorArraySavingsStats(), v8::internal::FastJsonStringifier< Char >::ResumeJSObject(), v8::internal::DescriptorArray::Search(), v8::internal::JsonStringifier::SerializeJSObject(), v8::internal::JSObject::SlowReverseLookup(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), v8::internal::LookupIterator::SwapDataValue(), ToByte(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), v8::internal::Genesis::TransferNamedProperties(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), v8::internal::MapUpdater::TryReconfigureToDataFieldInplace(), v8::internal::Map::TryReplayPropertyTransitions(), v8::internal::MapUpdater::UpdateFieldType(), v8::internal::LookupIterator::WriteDataValue(), v8::internal::ValueSerializer::WriteJSObject(), and v8::internal::JSObject::WriteToField().
operator!=()
bool v8::internal::PropertyDetails::operator!= (PropertyDetails const & other) const [inline]
Definition at line 315 of file property-details.h.
                                                      {
    return value_ != other.value_;
  }
References value_.
operator==()
bool v8::internal::PropertyDetails::operator== (PropertyDetails const & other) const [inline]
Definition at line 311 of file property-details.h.
                                                      {
    return value_ == other.value_;
  }
References value_.
pointer()
int v8::internal::PropertyDetails::pointer () const [inline]
Definition at line 319 of file property-details.h.
{ return DescriptorPointer::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::DescriptorArray::GetSortedKeyIndex(), PrintAsFastTo(), and PropertyDetails().
PrintAsFastTo()
void v8::internal::PropertyDetails::PrintAsFastTo (std::ostream & out, PrintMode mode = kPrintFull)
Definition at line 139 of file property.cc.
                                                                  {
  os << "(";
  if (constness() == PropertyConstness::kConst) os << "const ";
  os << (kind() == PropertyKind::kData ? "data" : "accessor");
  if (location() == PropertyLocation::kField) {
    os << " field";
    if (mode & kPrintFieldIndex) {
      os << " " << field_index();
    }
    if (mode & kPrintRepresentation) {
      os << ":" << representation().Mnemonic();
    }
  } else {
    os << " descriptor";
  }
  if (mode & kPrintPointer) {
    os << ", p: " << pointer();
  }
  if (mode & kPrintAttributes) {
    os << ", attrs: " << attributes();
  }
  os << ")";
}
References attributes(), constness(), field_index(), v8::internal::kConst, v8::internal::kData, v8::internal::kField, kind(), kPrintAttributes, kPrintFieldIndex, kPrintPointer, kPrintRepresentation, location(), v8::internal::Representation::Mnemonic(), mode(), pointer(), and representation().
Referenced by v8::internal::DescriptorArray::PrintDescriptorDetails().
PrintAsSlowTo()
void v8::internal::PropertyDetails::PrintAsSlowTo (std::ostream & out, bool print_dict_index)
Definition at line 128 of file property.cc.
                                                                         {
  os << "(";
  if (constness() == PropertyConstness::kConst) os << "const ";
  os << (kind() == PropertyKind::kData ? "data" : "accessor");
  if (print_dict_index) {
    os << ", dict_index: " << dictionary_index();
  }
  os << ", attrs: " << attributes() << ")";
}
References attributes(), constness(), dictionary_index(), v8::internal::kConst, v8::internal::kData, and kind().
representation()
Representation v8::internal::PropertyDetails::representation () const [inline]
Definition at line 378 of file property-details.h.
                                        {
    return DecodeRepresentation(RepresentationField::decode(value_));
  }
References v8::base::BitField< T, shift, size, U >::decode(), DecodeRepresentation(), and value_.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::JSObject::AllocateStorageForMap(), v8::internal::Map::AppendDescriptor(), v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::Map::CanBeDeprecated(), v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral(), v8::internal::anonymous_namespace{map.cc}::CanHoldValue(), v8::internal::LookupIterator::CanStayConst(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::MapUpdater::ConstructNewMap(), CopyWithRepresentation(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), EncodeRepresentation(), v8::internal::Map::EquivalentToForElementsKindTransition(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::LookupIterator::FetchValue(), v8::internal::MapUpdater::FindRootMap(), v8::internal::MapUpdater::FindSplitMap(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::FieldIndex::ForDetails(), v8::internal::MapUpdater::GeneralizeField(), v8::internal::LookupIterator::GetDataValue(), v8::internal::FieldStatsCollector::GetInobjectFieldStats(), v8::internal::DescriptorArray::IsEqualUpTo(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), PrintAsFastTo(), PropertyDetails(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::MapUpdater::ReconfigureToDataField(), v8::internal::JsonStringifier::SerializeJSObject(), v8::internal::StoreHandler::StoreOwnTransition(), v8::internal::StoreHandler::StoreTransition(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), v8::internal::Genesis::TransferNamedProperties(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), v8::internal::MapUpdater::TryReconfigureToDataFieldInplace(), v8::internal::Map::TryReplayPropertyTransitions(), v8::internal::MapUpdater::UpdateFieldType(), and v8::internal::JSObject::WriteToField().
set_cell_type()
PropertyDetails v8::internal::PropertyDetails::set_cell_type (PropertyCellType type) const [inline]
Definition at line 325 of file property-details.h.
                                                             {
    PropertyDetails details = *this;
    details.value_ = PropertyCellTypeField::update(details.value_, type);
    return details;
  }
References v8::internal::tracing::type, v8::base::BitField< T, shift, size, U >::update(), and value_.
Referenced by v8::internal::PropertyCell::ClearAndInvalidate(), v8::internal::JSGlobalObject::InvalidatePropertyCell(), v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::JSObject::SetNormalizedProperty(), and v8::internal::PropertyCell::Transition().
set_index()
PropertyDetails v8::internal::PropertyDetails::set_index (int index) const [inline]
Definition at line 331 of file property-details.h.
                                             {
    PropertyDetails details = *this;
    details.value_ = DictionaryStorageField::update(details.value_, index);
    return details;
  }
References v8::internal::index, v8::base::BitField< T, shift, size, U >::update(), and value_.
Referenced by v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::LookupIterator::ReconfigureDataProperty(), and v8::internal::JSObject::SetNormalizedProperty().
set_pointer()
PropertyDetails v8::internal::PropertyDetails::set_pointer (int i) const [inline]
Definition at line 321 of file property-details.h.
                                           {
    return PropertyDetails(value_, i);
  }
References PropertyDetails(), and value_.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), and v8::internal::DescriptorArray::SetSortedKey().
ToByte()
uint8_t v8::internal::PropertyDetails::ToByte () [inline]
Definition at line 462 of file property-details.h.
                   {
    // We only care about the value of KindField, ConstnessField, and
    // AttributesField. We've statically asserted earlier that these fields fit
    // into a byte together.
    DCHECK_EQ(PropertyLocation::kField, location());
    static_assert(static_cast<int>(PropertyLocation::kField) == 0);
    DCHECK_EQ(PropertyCellType::kNoCell, cell_type());
    static_assert(static_cast<int>(PropertyCellType::kNoCell) == 0);
    // Only to be used when the enum index isn't actually maintained
    // by the PropertyDetails:
    DCHECK_EQ(0, dictionary_index());
    return value_;
  }
References cell_type(), DCHECK_EQ, dictionary_index(), v8::internal::kField, v8::internal::kNoCell, location(), and value_.
Referenced by v8::internal::CodeStubAssembler::AddToDictionary(), and v8::internal::SwissNameDictionary::DetailsAtPut().
Member Data Documentation
kAttributesDontDeleteMask
const int v8::internal::PropertyDetails::kAttributesDontDeleteMask [static]
Initial value:
=
      (DONT_DELETE << AttributesField::kShift)
Definition at line 405 of file property-details.h.
Referenced by v8::internal::ProxiesCodeStubAssembler::CheckDeleteTrapResult(), v8::internal::ProxiesCodeStubAssembler::CheckGetSetTrapResult(), v8::internal::ProxiesCodeStubAssembler::CheckHasTrapResult(), v8::internal::DeletePropertyBaseAssembler::DeleteDictionaryProperty(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDetails(), and v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase().
kAttributesDontEnumMask
const int v8::internal::PropertyDetails::kAttributesDontEnumMask [static]
Initial value:
=
      (DONT_ENUM << AttributesField::kShift)
Definition at line 407 of file property-details.h.
Referenced by v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDetails(), and v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase().
kAttributesReadOnlyMask
const int v8::internal::PropertyDetails::kAttributesReadOnlyMask [static]
Initial value:
=
      (READ_ONLY << AttributesField::kShift)
Definition at line 403 of file property-details.h.
Referenced by v8::internal::ProxiesCodeStubAssembler::CheckGetSetTrapResult(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDetails(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::AccessorAssembler::JumpIfDataProperty(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), and v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase().
kConstIfDictConstnessTracking
constexpr PropertyConstness v8::internal::PropertyDetails::kConstIfDictConstnessTracking [static], [constexpr]
Initial value:
=
      V8_DICT_PROPERTY_CONST_TRACKING_BOOL ? PropertyConstness::kConst
                                           : PropertyConstness::kMutable
Definition at line 438 of file property-details.h.
Referenced by v8::internal::CodeStubAssembler::AddToDictionary(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::LookupIterator::PrepareTransitionToDataProperty(), and v8::internal::RUNTIME_FUNCTION().
kInitialIndex
const int v8::internal::PropertyDetails::kInitialIndex = 1 [static]
Definition at line 436 of file property-details.h.
Referenced by v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
value_
uint32_t v8::internal::PropertyDetails::value_ [private]
Definition at line 510 of file property-details.h.
Referenced by AsSmi(), attributes(), cell_type(), constness(), CopyAddAttributes(), CopyWithConstness(), CopyWithRepresentation(), dictionary_index(), field_index(), HasKindAndAttributes(), kind(), location(), operator!=(), operator==(), pointer(), PropertyDetails(), representation(), set_cell_type(), set_index(), set_pointer(), and ToByte().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/property-details.h
/mnt/V8SourceCode/src/objects/objects-inl.h
/mnt/V8SourceCode/src/objects/property.cc