v8::internal::SparseBitVector Class Reference
#include <sparse-bit-vector.h>
Classes
class Iterator
struct Segment
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (SparseBitVector)
SparseBitVector (Zone *zone)
bool Contains (int i) const
void Add (int i)
void Remove (int i)
void Union (const SparseBitVector &other)
Iterator begin () const
Iterator end () const
Private Member Functions
V8_NOINLINE void InsertBitAfter (Segment *segment, int i)
V8_NOINLINE void InsertSegmentAfter (Segment *segment, Segment *new_segment)
V8_WARN_UNUSED_RESULT bool CheckConsistency (const Segment *segment)
Static Private Member Functions
static std::pair< int, int > GetWordAndBitInWord (const Segment *segment, int i)
static bool contains (const Segment *segment, int i)
static bool set (Segment *segment, int i)
static bool unset (Segment *segment, int i)
static void insert_after (Segment *segment, Segment *new_next)
Private Attributes
Segment first_segment_
Zone * zone_
Static Private Attributes
static constexpr int kNumWordsPerSegment = 6
static constexpr int kBitsPerWord = kBitsPerByte * kSystemPointerSize
static constexpr int kNumBitsPerSegment = kBitsPerWord * kNumWordsPerSegment
Detailed Description
Definition at line 18 of file sparse-bit-vector.h.
Constructor & Destructor Documentation
SparseBitVector()
v8::internal::SparseBitVector::SparseBitVector (Zone * zone) [inline], [explicit]
Definition at line 121 of file sparse-bit-vector.h.
: zone_(zone) {}
Member Function Documentation
Add()
void v8::internal::SparseBitVector::Add (int i) [inline]
Definition at line 137 of file sparse-bit-vector.h.
                            {
    DCHECK_LE(0, i);
    Segment* last = nullptr;
    Segment* segment = &first_segment_;
    // Explicit fast path for the first segment which always starts at offset 0.
    if (V8_UNLIKELY(i >= kNumBitsPerSegment)) {
      do {
        last = segment;
        segment = segment->next;
        if (V8_UNLIKELY(!segment)) return InsertBitAfter(last, i);
      } while (segment->offset <= i - kNumBitsPerSegment);
      if (V8_UNLIKELY(segment->offset > i)) return InsertBitAfter(last, i);
    }
    set(segment, i);
  }
References DCHECK_LE, first_segment_, InsertBitAfter(), kNumBitsPerSegment, v8::internal::SparseBitVector::Segment::next, v8::internal::SparseBitVector::Segment::offset, set(), and V8_UNLIKELY.
Referenced by v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
begin()
Iterator v8::internal::SparseBitVector::begin () const [inline]
Definition at line 200 of file sparse-bit-vector.h.
{ return Iterator{&first_segment_}; }
References first_segment_.
CheckConsistency()
V8_WARN_UNUSED_RESULT bool v8::internal::SparseBitVector::CheckConsistency (const Segment * segment) [inline], [private]
Definition at line 250 of file sparse-bit-vector.h.
                                                                      {
    if ((segment->offset % kNumBitsPerSegment) != 0) return false;
    if (segment->next && segment->next->offset <= segment->offset) return false;
    return true;
  }
References kNumBitsPerSegment, v8::internal::SparseBitVector::Segment::next, and v8::internal::SparseBitVector::Segment::offset.
Referenced by InsertSegmentAfter().
contains()
static bool v8::internal::SparseBitVector::contains (const Segment * segment, int i) [inline], [static], [private]
Definition at line 228 of file sparse-bit-vector.h.
                                                      {
    auto [word, bit] = GetWordAndBitInWord(segment, i);
    return (segment->words[word] >> bit) & 1;
  }
References GetWordAndBitInWord(), and v8::internal::SparseBitVector::Segment::words.
Referenced by Contains(), v8::internal::SparseBitVector::Iterator::Iterator(), and v8::internal::SparseBitVector::Iterator::operator*().
Contains()
bool v8::internal::SparseBitVector::Contains (int i) const [inline]
Definition at line 123 of file sparse-bit-vector.h.
                                       {
    DCHECK_LE(0, i);
    const Segment* segment = &first_segment_;
    // Explicit fast path for the first segment which always starts at offset 0.
    if (V8_UNLIKELY(i >= kNumBitsPerSegment)) {
      do {
        segment = segment->next;
        if (!segment) return false;
      } while (segment->offset <= i - kNumBitsPerSegment);
      if (segment->offset > i) return false;
    }
    return contains(segment, i);
  }
References contains(), DCHECK_LE, first_segment_, kNumBitsPerSegment, v8::internal::SparseBitVector::Segment::next, v8::internal::SparseBitVector::Segment::offset, and V8_UNLIKELY.
Referenced by v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeSpecialRPO(), InsertBitAfter(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
end()
Iterator v8::internal::SparseBitVector::end () const [inline]
Definition at line 201 of file sparse-bit-vector.h.
{ return Iterator{Iterator::EndTag{}}; }
GetWordAndBitInWord()
static std::pair<int, int> v8::internal::SparseBitVector::GetWordAndBitInWord (const Segment * segment, int i) [inline], [static], [private]
Definition at line 204 of file sparse-bit-vector.h.
                                                        {
    DCHECK_LE(segment->offset, i);
    DCHECK_GT(segment->offset + kNumBitsPerSegment, i);
    int bit_in_segment = i - segment->offset;
    return {bit_in_segment / kBitsPerWord, bit_in_segment % kBitsPerWord};
  }
References DCHECK_GT, DCHECK_LE, kBitsPerWord, kNumBitsPerSegment, and v8::internal::SparseBitVector::Segment::offset.
Referenced by contains(), set(), and unset().
insert_after()
static void v8::internal::SparseBitVector::insert_after (Segment * segment, Segment * new_next) [inline], [static], [private]
Definition at line 243 of file sparse-bit-vector.h.
                                                                {
    DCHECK_NULL(new_next->next);
    DCHECK_LT(segment->offset, new_next->offset);
    new_next->next = segment->next;
    segment->next = new_next;
  }
References DCHECK_LT, DCHECK_NULL, v8::internal::SparseBitVector::Segment::next, and v8::internal::SparseBitVector::Segment::offset.
Referenced by InsertSegmentAfter().
InsertBitAfter()
V8_NOINLINE void v8::internal::SparseBitVector::InsertBitAfter (Segment * segment, int i) [inline], [private]
Definition at line 212 of file sparse-bit-vector.h.
                                                           {
    Segment* new_segment = zone_->New<Segment>();
    new_segment->offset = i / kNumBitsPerSegment * kNumBitsPerSegment;
    set(new_segment, i);
    InsertSegmentAfter(segment, new_segment);
    DCHECK(Contains(i));
  }
References Contains(), v8::internal::DCHECK(), InsertSegmentAfter(), kNumBitsPerSegment, v8::internal::Zone::New(), v8::internal::SparseBitVector::Segment::offset, set(), and zone_.
Referenced by Add().
InsertSegmentAfter()
V8_NOINLINE void v8::internal::SparseBitVector::InsertSegmentAfter (Segment * segment, Segment * new_segment) [inline], [private]
Definition at line 220 of file sparse-bit-vector.h.
                                                                              {
    DCHECK_NOT_NULL(segment);
    DCHECK_LT(segment->offset, new_segment->offset);
    insert_after(segment, new_segment);
    DCHECK(CheckConsistency(segment));
    DCHECK(CheckConsistency(new_segment));
  }
References CheckConsistency(), v8::internal::DCHECK(), DCHECK_LT, DCHECK_NOT_NULL, insert_after(), and v8::internal::SparseBitVector::Segment::offset.
Referenced by InsertBitAfter(), and Union().
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::internal::SparseBitVector::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (SparseBitVector)
Remove()
void v8::internal::SparseBitVector::Remove (int i) [inline]
Definition at line 153 of file sparse-bit-vector.h.
                               {
    DCHECK_LE(0, i);
    Segment* segment = &first_segment_;
    // Explicit fast path for the first segment which always starts at offset 0.
    if (V8_UNLIKELY(i >= kNumBitsPerSegment)) {
      do {
        segment = segment->next;
        if (V8_UNLIKELY(!segment)) return;
      } while (segment->offset <= i - kNumBitsPerSegment);
      if (V8_UNLIKELY(segment->offset > i)) return;
    }
    unset(segment, i);
  }
References DCHECK_LE, first_segment_, kNumBitsPerSegment, v8::internal::SparseBitVector::Segment::next, v8::internal::SparseBitVector::Segment::offset, unset(), and V8_UNLIKELY.
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::LiveRangeBuilder::ProcessPhis().
set()
static bool v8::internal::SparseBitVector::set (Segment * segment, int i) [inline], [static], [private]
Definition at line 233 of file sparse-bit-vector.h.
                                           {
    auto [word, bit] = GetWordAndBitInWord(segment, i);
    return segment->words[word] |= uintptr_t{1} << bit;
  }
References GetWordAndBitInWord(), and v8::internal::SparseBitVector::Segment::words.
Referenced by Add(), and InsertBitAfter().
Union()
void v8::internal::SparseBitVector::Union (const SparseBitVector & other) [inline]
Definition at line 167 of file sparse-bit-vector.h.
                                           {
    // Always remember the segment before {segment}, because we sometimes need
    // to insert *before* {segment}, but we have to backlinks.
    Segment* last = nullptr;
    Segment* segment = &first_segment_;
    // Iterate all segments in {other}, merging with with existing segments in
    // {this}, or inserting new segments when needed.
    for (const Segment* other_segment = &other.first_segment_; other_segment;
         other_segment = other_segment->next) {
      // Find the first segment whose offset is >= {other_segment}'s offset.
      while (segment && segment->offset < other_segment->offset) {
        last = segment;
        segment = segment->next;
      }
      // Now either merge {other_segment} into {segment}, or insert between
      // {last} and {segment}.
      if (segment && segment->offset == other_segment->offset) {
        std::transform(std::begin(segment->words), std::end(segment->words),
                       std::begin(other_segment->words),
                       std::begin(segment->words), std::bit_or<uintptr_t>{});
      } else if (!other_segment->empty()) {
        DCHECK_LT(last->offset, other_segment->offset);
        Segment* new_segment = zone_->New<Segment>();
        new_segment->offset = other_segment->offset;
        std::copy(std::begin(other_segment->words),
                  std::end(other_segment->words),
                  std::begin(new_segment->words));
        InsertSegmentAfter(last, new_segment);
        last = new_segment;
      }
    }
  }
References v8::internal::compiler::begin(), DCHECK_LT, v8::internal::compiler::end(), first_segment_, InsertSegmentAfter(), v8::internal::Zone::New(), v8::internal::SparseBitVector::Segment::next, v8::internal::SparseBitVector::Segment::offset, v8::internal::SparseBitVector::Segment::words, and zone_.
Referenced by v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut().
unset()
static bool v8::internal::SparseBitVector::unset (Segment * segment, int i) [inline], [static], [private]
Definition at line 238 of file sparse-bit-vector.h.
                                             {
    auto [word, bit] = GetWordAndBitInWord(segment, i);
    return segment->words[word] &= ~(uintptr_t{1} << bit);
  }
References GetWordAndBitInWord(), and v8::internal::SparseBitVector::Segment::words.
Referenced by Remove().
Member Data Documentation
first_segment_
Segment v8::internal::SparseBitVector::first_segment_ [private]
Definition at line 256 of file sparse-bit-vector.h.
Referenced by Add(), begin(), Contains(), Remove(), and Union().
kBitsPerWord
constexpr int v8::internal::SparseBitVector::kBitsPerWord = kBitsPerByte * kSystemPointerSize [static], [constexpr], [private]
Definition at line 22 of file sparse-bit-vector.h.
Referenced by GetWordAndBitInWord(), v8::internal::SparseBitVector::Iterator::Iterator(), and v8::internal::SparseBitVector::Iterator::operator++().
kNumBitsPerSegment
constexpr int v8::internal::SparseBitVector::kNumBitsPerSegment = kBitsPerWord * kNumWordsPerSegment [static], [constexpr], [private]
Definition at line 23 of file sparse-bit-vector.h.
Referenced by Add(), CheckConsistency(), Contains(), GetWordAndBitInWord(), InsertBitAfter(), and Remove().
kNumWordsPerSegment
constexpr int v8::internal::SparseBitVector::kNumWordsPerSegment = 6 [static], [constexpr], [private]
Definition at line 21 of file sparse-bit-vector.h.
Referenced by v8::internal::SparseBitVector::Iterator::Iterator(), and v8::internal::SparseBitVector::Iterator::operator++().
zone_
Zone* v8::internal::SparseBitVector::zone_ [private]
Definition at line 257 of file sparse-bit-vector.h.
Referenced by InsertBitAfter(), and Union().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/sparse-bit-vector.h