v8::PropertyCallbackInfo< T > Class Template Reference
The information passed to a property callback about the context of the property access.
#include <v8-function-callback.h>
Public Member Functions
Isolate * GetIsolate () const
Local< Value > Data () const
Local< Object > This () const
V8 will stop providing access to hidden prototype(i.e. ` `JSGlobalObject). Use HolderV2() instead. \n` `DO NOTto workaround this by accessing JSGlobalObject via ` `v8 Local< Object > HolderV2 () const
ReturnValue< T > GetReturnValue () const
bool ShouldThrowOnError () const
Private Member Functions
PropertyCallbackInfo ()=default
Private Attributes
internal::Address args_ [kArgsLength]
Static Private Attributes
static constexpr int kPropertyKeyIndex = 0
static constexpr int kShouldThrowOnErrorIndex = 1
static constexpr int kHolderIndex = 2
static constexpr int kIsolateIndex = 3
static constexpr int kHolderV2Index = 4
static constexpr int kReturnValueIndex = 5
static constexpr int kDataIndex = 6
static constexpr int kThisIndex = 7
static constexpr int kArgsLength = 8
static constexpr int kSize = kArgsLength * internal::kApiSystemPointerSize
Friends
template<typename U >
class PropertyCallbackInfo
class MacroAssembler
class internal::PropertyCallbackArguments
class internal::CustomArguments< PropertyCallbackInfo >
void internal::PrintPropertyCallbackInfo (void *)
Detailed Description
template<typename T>
class v8::PropertyCallbackInfo< T >
The information passed to a property callback about the context of the property access.
Definition at line 187 of file v8-function-callback.h.
Constructor & Destructor Documentation
PropertyCallbackInfo()
template<typename T >
v8::PropertyCallbackInfo< T >::PropertyCallbackInfo () [private], [default]
Member Function Documentation
Data()
template<typename T >
Local< Value > v8::PropertyCallbackInfo< T >::Data [inline]
Returns
The data set in the configuration, i.e., in NamedPropertyHandlerConfiguration or IndexedPropertyHandlerConfiguration.
Definition at line 670 of file v8-function-callback.h.
                                                 {
  return Local<Value>::FromSlot(&args_[kDataIndex]);
}
References v8::Local< T >::FromSlot().
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback(), and v8::internal::ValidatePropertyCallbackInfo().
GetIsolate()
template<typename T >
Isolate * v8::PropertyCallbackInfo< T >::GetIsolate [inline]
Returns
The isolate of the property access.
Definition at line 665 of file v8-function-callback.h.
                                                   {
  return *reinterpret_cast<Isolate**>(&args_[kIsolateIndex]);
}
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::GetIsolate(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::IndexedEnumerator(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedQuery(), v8::internal::InvokeAccessorGetterCallback(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::NamedGetter(), v8::Shell::RealmSharedGet(), v8::Shell::RealmSharedSet(), and v8::internal::ValidatePropertyCallbackInfo().
GetReturnValue()
template<typename T >
ReturnValue< T > v8::PropertyCallbackInfo< T >::GetReturnValue [inline]
Returns
The return value of the callback. Can be changed by calling Set().
info.GetReturnValue().Set(...)
Definition at line 702 of file v8-function-callback.h.
                                                             {
  return ReturnValue<T>(&args_[kReturnValueIndex]);
}
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedDescriptor(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedEnumerator(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::IndexedEnumerator(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedGetter(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedQuery(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::NamedEnumerator(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::NamedGetter(), v8::Shell::RealmSharedGet(), and v8::internal::ValidatePropertyCallbackInfo().
HolderV2()
template<typename T >
Local< Object > v8::PropertyCallbackInfo< T >::HolderV2 [inline]
Returns
The object in the prototype chain of the receiver that has the interceptor. Suppose you have x and its prototype is y, and y has an interceptor. Then info.This() is x and info.Holder() is y. The Holder() could be a hidden object (the global object, rather than the global proxy).
Note
For security reasons, do not pass the object back into the runtime.
Returns
The object in the prototype chain of the receiver that has the interceptor. Suppose you have x and its prototype is y, and y has an interceptor. Then info.This() is x and info.Holder() is y. In case the property is installed on the global object the Holder() would return the global proxy.
Definition at line 692 of file v8-function-callback.h.
                                                      {
  using I = internal::Internals;
  if (!I::HasHeapObjectTag(args_[kHolderV2Index])) {
    args_[kHolderV2Index] =
        api_internal::ConvertToJSGlobalProxyIfNecessary(args_[kHolderIndex]);
  }
  return Local<Object>::FromSlot(&args_[kHolderV2Index]);
}
References v8::api_internal::ConvertToJSGlobalProxyIfNecessary(), v8::Local< T >::FromSlot(), and I.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::GetHolder(), and v8::internal::ValidatePropertyCallbackInfo().
ShouldThrowOnError()
template<typename T >
bool v8::PropertyCallbackInfo< T >::ShouldThrowOnError [inline]
Returns
True if the intercepted function should throw if an error occurs. Usually, true corresponds to `'use strict'.
Note
Always false when intercepting Reflect.set() independent of the language mode.
Definition at line 707 of file v8-function-callback.h.
                                                       {
  using I = internal::Internals;
  if (args_[kShouldThrowOnErrorIndex] !=
      I::IntegralToSmi(I::kInferShouldThrowMode)) {
    return args_[kShouldThrowOnErrorIndex] != I::IntegralToSmi(I::kDontThrow);
  }
  return v8::internal::ShouldThrowOnError(
      reinterpret_cast<v8::internal::Isolate*>(GetIsolate()));
}
References I, v8::internal::kDontThrow, and v8::internal::ShouldThrowOnError().
Referenced by v8::internal::ValidatePropertyCallbackInfo().
This()
template<typename T >
Local< Object > v8::PropertyCallbackInfo< T >::This [inline]
Returns
The receiver. In many cases, this is the object on which the property access was intercepted. When using Reflect.get, Function.prototype.call, or similar functions, it is the object passed in as receiver or thisArg.
void GetterCallback(Local<Name> name,
                    const v8::PropertyCallbackInfo<v8::Value>& info) {
   auto context = info.GetIsolate()->GetCurrentContext();
   v8::Local<v8::Value> a_this =
       info.This()
           ->GetRealNamedProperty(context, v8_str("a"))
           .ToLocalChecked();
   v8::Local<v8::Value> a_holder =
       info.Holder()
           ->GetRealNamedProperty(context, v8_str("a"))
           .ToLocalChecked();
  CHECK(v8_str("r")->Equals(context, a_this).FromJust());
  CHECK(v8_str("obj")->Equals(context, a_holder).FromJust());
  info.GetReturnValue().Set(name);
}
v8::Local<v8::FunctionTemplate> templ =
v8::FunctionTemplate::New(isolate);
templ->InstanceTemplate()->SetHandler(
    v8::NamedPropertyHandlerConfiguration(GetterCallback));
LocalContext env;
env->Global()
    ->Set(env.local(), v8_str("obj"), templ->GetFunction(env.local())
                                         .ToLocalChecked()
                                         ->NewInstance(env.local())
                                         .ToLocalChecked())
    .FromJust();
CompileRun("obj.a = 'obj'; var r = {a: 'r'}; Reflect.get(obj, 'x', r)");
Definition at line 675 of file v8-function-callback.h.
                                                  {
  return Local<Object>::FromSlot(&args_[kThisIndex]);
}
References v8::Local< T >::FromSlot().
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::NamedGetter(), and v8::internal::ValidatePropertyCallbackInfo().
Friends And Related Function Documentation
internal::CustomArguments< PropertyCallbackInfo >
template<typename T >
friend class internal::CustomArguments< PropertyCallbackInfo > [friend]
Definition at line 293 of file v8-function-callback.h.
internal::PrintPropertyCallbackInfo
template<typename T >
void internal::PrintPropertyCallbackInfo (void *) [friend]
internal::PropertyCallbackArguments
template<typename T >
friend class internal::PropertyCallbackArguments [friend]
Definition at line 293 of file v8-function-callback.h.
MacroAssembler
template<typename T >
friend class MacroAssembler [friend]
Definition at line 292 of file v8-function-callback.h.
PropertyCallbackInfo
template<typename T >
template<typename U >
friend class PropertyCallbackInfo [friend]
Definition at line 291 of file v8-function-callback.h.
Member Data Documentation
args_
template<typename T >
internal::Address v8::PropertyCallbackInfo< T >::args_[kArgsLength] [mutable], [private]
Definition at line 311 of file v8-function-callback.h.
Referenced by v8::internal::PropertyCallbackArguments::GetPropertyIndex(), v8::internal::PropertyCallbackArguments::GetPropertyKey(), and v8::internal::PropertyCallbackArguments::GetPropertyKeyHandle().
kArgsLength
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kArgsLength = 8 [static], [constexpr], [private]
Definition at line 305 of file v8-function-callback.h.
kDataIndex
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kDataIndex = 6 [static], [constexpr], [private]
Definition at line 303 of file v8-function-callback.h.
Referenced by v8::internal::PropertyCallbackArguments::PropertyCallbackArguments().
kHolderIndex
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kHolderIndex = 2 [static], [constexpr], [private]
Definition at line 299 of file v8-function-callback.h.
Referenced by v8::internal::PropertyCallbackArguments::holder(), and v8::internal::PropertyCallbackArguments::PropertyCallbackArguments().
kHolderV2Index
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kHolderV2Index = 4 [static], [constexpr], [private]
Definition at line 301 of file v8-function-callback.h.
Referenced by v8::internal::PropertyCallbackArguments::PropertyCallbackArguments().
kIsolateIndex
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kIsolateIndex = 3 [static], [constexpr], [private]
Definition at line 300 of file v8-function-callback.h.
Referenced by v8::internal::PropertyCallbackArguments::PropertyCallbackArguments().
kPropertyKeyIndex
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kPropertyKeyIndex = 0 [static], [constexpr], [private]
Definition at line 297 of file v8-function-callback.h.
Referenced by v8::internal::PropertyCallbackArguments::PropertyCallbackArguments().
kReturnValueIndex
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kReturnValueIndex = 5 [static], [constexpr], [private]
Definition at line 302 of file v8-function-callback.h.
Referenced by v8::internal::PropertyCallbackArguments::PropertyCallbackArguments().
kShouldThrowOnErrorIndex
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kShouldThrowOnErrorIndex = 1 [static], [constexpr], [private]
Definition at line 298 of file v8-function-callback.h.
Referenced by v8::internal::PropertyCallbackArguments::PropertyCallbackArguments().
kSize
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kSize = kArgsLength * internal::kApiSystemPointerSize [static], [constexpr], [private]
Definition at line 307 of file v8-function-callback.h.
kThisIndex
template<typename T >
constexpr int v8::PropertyCallbackInfo< T >::kThisIndex = 7 [static], [constexpr], [private]
Definition at line 304 of file v8-function-callback.h.
Referenced by v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::GetReturnValue(), and v8::internal::PropertyCallbackArguments::PropertyCallbackArguments().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-function-callback.h