v8::internal::compiler::turboshaft::VariableReducer< AfterNext > Class Template Reference
#include <variable-reducer.h>
Classes
struct GetActiveLoopVariablesIndex
struct VariableTable
Public Member Functions
void Bind (Block *new_block)
void RestoreTemporaryVariableSnapshotAfter (const Block *block)
void CloseTemporaryVariableSnapshot ()
V< None > REDUCE() Goto (Block *destination, bool is_backedge)
OpIndex GetVariable (Variable var)
OpIndex GetPredecessorValue (Variable var, int predecessor_index)
void SetVariable (Variable var, OpIndex new_index)
template<typename Rep >
void Set (Variable var, V< Rep > value)
Variable NewLoopInvariantVariable (MaybeRegisterRepresentation rep)
Variable NewVariable (MaybeRegisterRepresentation rep)
void SealAndSaveVariableSnapshot ()
Private Types
using Next = RequiredOptimizationReducer< AfterNext >
using Snapshot = SnapshotTable< OpIndex, VariableData >::Snapshot
Private Member Functions
OpIndex MergeOpIndices (base::Vector< const OpIndex > inputs, MaybeRegisterRepresentation maybe_rep)
OpIndex MergeFrameState (base::Vector< const OpIndex > frame_states_indices)
Private Attributes
VariableTable table_ {__ phase_zone()}
const Block * current_block_ = nullptr
GrowingBlockSidetable< std::optional< Snapshot > > block_to_snapshot_mapping_
bool is_temporary_ = false
ZoneVector< Snapshot > predecessors_ {__ phase_zone()}
ZoneAbslFlatHashMap< BlockIndex, std::optional< ZoneVector< std::pair< Variable, OpIndex > > > > loop_pending_phis_ {__ phase_zone()}
Detailed Description
template<class AfterNext>
class v8::internal::compiler::turboshaft::VariableReducer< AfterNext >
Definition at line 58 of file variable-reducer.h.
Member Typedef Documentation
Next
template<class AfterNext >
using v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Next = RequiredOptimizationReducer<AfterNext> [private]
Definition at line 59 of file variable-reducer.h.
Snapshot
template<class AfterNext >
using v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Snapshot = SnapshotTable<OpIndex, VariableData>::Snapshot [private]
Definition at line 60 of file variable-reducer.h.
Member Function Documentation
Bind()
template<class AfterNext >
void v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind (Block * new_block) [inline]
Definition at line 94 of file variable-reducer.h.
                              {
    Next::Bind(new_block);
    SealAndSaveVariableSnapshot();
    predecessors_.clear();
    for (const Block* pred : new_block->PredecessorsIterable()) {
      std::optional<Snapshot> pred_snapshot =
          block_to_snapshot_mapping_[pred->index()];
      DCHECK(pred_snapshot.has_value());
      predecessors_.push_back(pred_snapshot.value());
    }
    std::reverse(predecessors_.begin(), predecessors_.end());
    auto merge_variables =
        [&](Variable var, base::Vector<const OpIndex> predecessors) -> OpIndex {
      for (OpIndex idx : predecessors) {
        if (!idx.valid()) {
          // If any of the predecessors' value is Invalid, then we shouldn't
          // merge {var}.
          return OpIndex::Invalid();
        } else if (__ output_graph()
                       .Get(idx)
                       .template Is<LoadRootRegisterOp>()) {
          // Variables that once contain the root register never contain another
          // value.
          return __ LoadRootRegister();
        }
      }
      return MergeOpIndices(predecessors, var.data().rep);
    };
    table_.StartNewSnapshot(base::VectorOf(predecessors_), merge_variables);
    current_block_ = new_block;
    if (new_block->IsLoop()) {
      // When starting a loop, we need to create a PendingLoopPhi for each
      // currently active variable (except those that are marked as
      // loop-invariant).
      auto active_loop_variables_begin = table_.active_loop_variables.begin();
      auto active_loop_variables_end = table_.active_loop_variables.end();
      if (active_loop_variables_begin != active_loop_variables_end) {
        ZoneVector<std::pair<Variable, OpIndex>> pending_phis(__ phase_zone());
        for (Variable var : table_.active_loop_variables) {
          MaybeRegisterRepresentation rep = var.data().rep;
          DCHECK_NE(rep, MaybeRegisterRepresentation::None());
          V<Any> pending_loop_phi =
              __ PendingLoopPhi(table_.Get(var), RegisterRepresentation(rep));
          SetVariable(var, pending_loop_phi);
          pending_phis.push_back({var, pending_loop_phi});
        }
        loop_pending_phis_[new_block->index()].emplace(pending_phis);
      }
    }
  }
References __, v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::VariableTable::active_loop_variables, v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::block_to_snapshot_mapping_, v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::current_block_, v8::internal::DCHECK(), DCHECK_NE, v8::internal::ZoneVector< T >::end(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::loop_pending_phis_, v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeOpIndices(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::predecessors_, v8::internal::compiler::turboshaft::Block::PredecessorsIterable(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SealAndSaveVariableSnapshot(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SetVariable(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_, and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Bind().
CloseTemporaryVariableSnapshot()
template<class AfterNext >
void v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::CloseTemporaryVariableSnapshot () [inline]
Definition at line 155 of file variable-reducer.h.
                                        {
    DCHECK(is_temporary_);
    table_.Seal();
    is_temporary_ = false;
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::is_temporary_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_.
GetPredecessorValue()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::GetPredecessorValue (Variable var, int predecessor_index) [inline]
Definition at line 189 of file variable-reducer.h.
                                                                   {
    return table_.GetPredecessorValue(var, predecessor_index);
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_.
GetVariable()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::GetVariable (Variable var) [inline]
Definition at line 187 of file variable-reducer.h.
{ return table_.Get(var); }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Goto().
Goto()
template<class AfterNext >
V<None> REDUCE() v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Goto (Block * destination, bool is_backedge) [inline]
Definition at line 161 of file variable-reducer.h.
                                                             {
    V<None> result = Next::ReduceGoto(destination, is_backedge);
    if (!destination->IsBound()) {
      return result;
    }
    // For loops, we have to "fix" the PendingLoopPhis (= replace them with
    // regular loop phis).
    DCHECK(destination->IsLoop());
    DCHECK_EQ(destination->PredecessorCount(), 2);
    if (loop_pending_phis_.contains(destination->index())) {
      for (auto [var, pending_phi_idx] :
           loop_pending_phis_[destination->index()].value()) {
        const PendingLoopPhiOp& pending_phi =
            __ Get(pending_phi_idx).template Cast<PendingLoopPhiOp>();
        __ output_graph().template Replace<PhiOp>(
            pending_phi_idx,
            base::VectorOf({pending_phi.first(), GetVariable(var)}),
            pending_phi.rep);
      }
    }
    return result;
  }
References __, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::PendingLoopPhiOp::first(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::GetVariable(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::loop_pending_phis_, v8::internal::compiler::turboshaft::PendingLoopPhiOp::rep, v8::base::internal::result, and v8::base::VectorOf().
MergeFrameState()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState (base::Vector< const OpIndex > frame_states_indices) [inline], [private]
Definition at line 245 of file variable-reducer.h.
                                                                          {
    base::SmallVector<const FrameStateOp*, 32> frame_states;
    for (OpIndex idx : frame_states_indices) {
      frame_states.push_back(
          &__ output_graph().Get(idx).template Cast<FrameStateOp>());
    }
    const FrameStateOp* first_frame = frame_states[0];
#if DEBUG
    // Making sure that all frame states have the same number of inputs, the
    // same "inlined" field, and the same data.
    for (auto frame_state : frame_states) {
      DCHECK_EQ(first_frame->input_count, frame_state->input_count);
      DCHECK_EQ(first_frame->inlined, frame_state->inlined);
      DCHECK_EQ(*first_frame->data, *frame_state->data);
    }
#endif
    base::SmallVector<OpIndex, 32> new_inputs;
    // Merging the parent frame states.
    if (first_frame->inlined) {
      ZoneVector<OpIndex> indices_to_merge(__ phase_zone());
      bool all_parent_frame_states_are_the_same = true;
      for (auto frame_state : frame_states) {
        indices_to_merge.push_back(frame_state->parent_frame_state());
        all_parent_frame_states_are_the_same =
            all_parent_frame_states_are_the_same &&
            first_frame->parent_frame_state() ==
                frame_state->parent_frame_state();
      }
      if (all_parent_frame_states_are_the_same) {
        new_inputs.push_back(first_frame->parent_frame_state());
      } else {
        OpIndex merged_parent_frame_state =
            MergeFrameState(base::VectorOf(indices_to_merge));
        new_inputs.push_back(merged_parent_frame_state);
      }
    }
    // Merging the state values.
    for (int i = 0; i < first_frame->state_values_count(); i++) {
      ZoneVector<OpIndex> indices_to_merge(__ phase_zone());
      bool all_inputs_are_the_same = true;
      for (auto frame_state : frame_states) {
        indices_to_merge.push_back(frame_state->state_value(i));
        all_inputs_are_the_same =
            all_inputs_are_the_same &&
            first_frame->state_value(i) == frame_state->state_value(i);
      }
      if (all_inputs_are_the_same) {
        // This input does not need to be merged, since its identical for all of
        // the frame states.
        new_inputs.push_back(first_frame->state_value(i));
      } else {
        RegisterRepresentation rep = first_frame->state_value_rep(i);
        OpIndex new_input =
            MergeOpIndices(base::VectorOf(indices_to_merge), rep);
        new_inputs.push_back(new_input);
      }
    }
    return __ FrameState(base::VectorOf(new_inputs), first_frame->inlined,
                         first_frame->data);
  }
References __, v8::internal::compiler::turboshaft::FrameStateOp::data, DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::FrameStateOp::inlined, v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeOpIndices(), v8::internal::compiler::turboshaft::FrameStateOp::parent_frame_state(), v8::internal::ZoneVector< T >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::FrameStateOp::state_value(), v8::internal::compiler::turboshaft::FrameStateOp::state_value_rep(), v8::internal::compiler::turboshaft::FrameStateOp::state_values_count(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeOpIndices().
MergeOpIndices()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeOpIndices (base::Vector< const OpIndex > inputs, MaybeRegisterRepresentation maybe_rep) [inline], [private]
Definition at line 230 of file variable-reducer.h.
                                                                {
    if (maybe_rep != MaybeRegisterRepresentation::None()) {
      // Every Operation that has a RegisterRepresentation can be merged with a
      // simple Phi.
      return __ Phi(base::VectorOf(inputs), RegisterRepresentation(maybe_rep));
    } else if (__ output_graph().Get(inputs[0]).template Is<FrameStateOp>()) {
      // Frame states need be be merged recursively, because they represent
      // multiple scalar values that will lead to multiple phi nodes.
      return MergeFrameState(inputs);
    } else {
      return OpIndex::Invalid();
    }
  }
References __, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None(), v8::internal::compiler::turboshaft::RequiredOptimizationReducer< AfterNext >::Phi(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState().
NewLoopInvariantVariable()
template<class AfterNext >
Variable v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewLoopInvariantVariable (MaybeRegisterRepresentation rep) [inline]
Definition at line 207 of file variable-reducer.h.
                                                                     {
    DCHECK(!is_temporary_);
    return table_.NewKey(VariableData{rep, true}, OpIndex::Invalid());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::is_temporary_, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::NewKey(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_.
NewVariable()
template<class AfterNext >
Variable v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewVariable (MaybeRegisterRepresentation rep) [inline]
Definition at line 211 of file variable-reducer.h.
                                                        {
    DCHECK(!is_temporary_);
    return table_.NewKey(VariableData{rep, false}, OpIndex::Invalid());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::is_temporary_, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::NewKey(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_.
RestoreTemporaryVariableSnapshotAfter()
template<class AfterNext >
void v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::RestoreTemporaryVariableSnapshotAfter (const Block * block) [inline]
Definition at line 149 of file variable-reducer.h.
                                                                 {
    DCHECK(table_.IsSealed());
    DCHECK(block_to_snapshot_mapping_[block->index()].has_value());
    table_.StartNewSnapshot(*block_to_snapshot_mapping_[block->index()]);
    is_temporary_ = true;
  }
References v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::block_to_snapshot_mapping_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::is_temporary_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_.
SealAndSaveVariableSnapshot()
template<class AfterNext >
void v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SealAndSaveVariableSnapshot () [inline]
Definition at line 218 of file variable-reducer.h.
                                     {
    if (table_.IsSealed()) {
      DCHECK_EQ(current_block_, nullptr);
      return;
    }
    DCHECK_NOT_NULL(current_block_);
    block_to_snapshot_mapping_[current_block_->index()] = table_.Seal();
    current_block_ = nullptr;
  }
References v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::block_to_snapshot_mapping_, v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::current_block_, DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind().
Set()
template<class AfterNext >
template<typename Rep >
void v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Set (Variable var, V< Rep > value) [inline]
Definition at line 199 of file variable-reducer.h.
                                       {
    DCHECK(!is_temporary_);
    if (V8_UNLIKELY(__ generating_unreachable_operations())) return;
    DCHECK(
        V<Rep>::allows_representation(RegisterRepresentation(var.data().rep)));
    table_.Set(var, value);
  }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::is_temporary_, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::Set(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_, V8_UNLIKELY, and v8::internal::value.
SetVariable()
template<class AfterNext >
void v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SetVariable (Variable var, OpIndex new_index) [inline]
Definition at line 193 of file variable-reducer.h.
                                                    {
    DCHECK(!is_temporary_);
    if (V8_UNLIKELY(__ generating_unreachable_operations())) return;
    table_.Set(var, new_index);
  }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::is_temporary_, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::Set(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_, and V8_UNLIKELY.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind().
Member Data Documentation
block_to_snapshot_mapping_
template<class AfterNext >
GrowingBlockSidetable<std::optional<Snapshot> > v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::block_to_snapshot_mapping_ [private]
Initial value:
{
      __ input_graph().block_count(), std::nullopt, __ phase_zone()}
Definition at line 313 of file variable-reducer.h.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::RestoreTemporaryVariableSnapshotAfter(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SealAndSaveVariableSnapshot().
current_block_
template<class AfterNext >
const Block* v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::current_block_ = nullptr [private]
Definition at line 312 of file variable-reducer.h.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SealAndSaveVariableSnapshot().
is_temporary_
template<class AfterNext >
bool v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::is_temporary_ = false [private]
Definition at line 315 of file variable-reducer.h.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::CloseTemporaryVariableSnapshot(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewLoopInvariantVariable(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewVariable(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::RestoreTemporaryVariableSnapshotAfter(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Set(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SetVariable().
loop_pending_phis_
template<class AfterNext >
ZoneAbslFlatHashMap<BlockIndex, std::optional<ZoneVector<std::pair<Variable, OpIndex> > > > v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::loop_pending_phis_ {__ phase_zone()} [private]
Definition at line 325 of file variable-reducer.h.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Goto().
predecessors_
template<class AfterNext >
ZoneVector<Snapshot> v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::predecessors_ {__ phase_zone()} [private]
Definition at line 319 of file variable-reducer.h.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind().
table_
template<class AfterNext >
VariableTable v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::table_ {__ phase_zone()} [private]
Definition at line 311 of file variable-reducer.h.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::CloseTemporaryVariableSnapshot(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::GetPredecessorValue(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::GetVariable(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewLoopInvariantVariable(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewVariable(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::RestoreTemporaryVariableSnapshotAfter(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SealAndSaveVariableSnapshot(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Set(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SetVariable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/branch-elimination-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/variable-reducer.h