v8::internal::LoadIC Class Reference
#include <ic.h>
Public Member Functions
LoadIC (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind)
bool ShouldThrowReferenceError () const
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Load (Handle< JSAny > object, Handle< Name > name, bool update_feedback=true, DirectHandle< JSAny > receiver=DirectHandle< JSAny >())
Static Public Member Functions
static bool ShouldThrowReferenceError (FeedbackSlotKind kind)
Protected Member Functions
void UpdateCaches (LookupIterator *lookup)
Private Member Functions
MaybeObjectHandle ComputeHandler (LookupIterator *lookup)
Friends
class IC
class NamedLoadHandlerCompiler
Additional Inherited Members
Detailed Description
Definition at line 185 of file ic.h.
Constructor & Destructor Documentation
LoadIC()
v8::internal::LoadIC::LoadIC (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind) [inline]
Definition at line 187 of file ic.h.
      : IC(isolate, vector, slot, kind) {
    DCHECK(IsAnyLoad() || IsAnyHas());
  }
References v8::internal::DCHECK(), v8::internal::IC::IsAnyHas(), and v8::internal::IC::IsAnyLoad().
Member Function Documentation
ComputeHandler()
MaybeObjectHandle v8::internal::LoadIC::ComputeHandler (LookupIterator * lookup) [private]
Definition at line 857 of file ic.cc.
                                                               {
  DirectHandle<Object> receiver = lookup->GetReceiver();
  ReadOnlyRoots roots(isolate());
  DirectHandle<Object> lookup_start_object = lookup->lookup_start_object();
  // `in` cannot be called on strings, and will always return true for string
  // wrapper length and function prototypes. The latter two cases are given
  // LoadHandler::LoadNativeDataProperty below.
  if (!IsAnyHas() && !lookup->IsElement()) {
    if (IsString(*lookup_start_object) &&
        *lookup->name() == roots.length_string()) {
      TRACE_HANDLER_STATS(isolate(), LoadIC_StringLength);
      return MaybeObjectHandle(BUILTIN_CODE(isolate(), LoadIC_StringLength));
    }
    if (IsStringWrapper(*lookup_start_object) &&
        *lookup->name() == roots.length_string()) {
      TRACE_HANDLER_STATS(isolate(), LoadIC_StringWrapperLength);
      return MaybeObjectHandle(
          BUILTIN_CODE(isolate(), LoadIC_StringWrapperLength));
    }
    // Use specialized code for getting prototype of functions.
    if (IsJSFunction(*lookup_start_object) &&
        *lookup->name() == roots.prototype_string() &&
        !Cast<JSFunction>(*lookup_start_object)
             ->PrototypeRequiresRuntimeLookup()) {
      TRACE_HANDLER_STATS(isolate(), LoadIC_FunctionPrototypeStub);
      return MaybeObjectHandle(
          BUILTIN_CODE(isolate(), LoadIC_FunctionPrototype));
    }
  }
  DirectHandle<Map> map = lookup_start_object_map();
  bool holder_is_lookup_start_object =
      lookup_start_object.is_identical_to(lookup->GetHolder<JSReceiver>());
  switch (lookup->state()) {
    case LookupIterator::INTERCEPTOR: {
      DirectHandle<JSObject> holder = lookup->GetHolder<JSObject>();
      Handle<Smi> smi_handler = LoadHandler::LoadInterceptor(isolate());
      if (holder->GetNamedInterceptor()->non_masking()) {
        MaybeObjectDirectHandle holder_ref(isolate()->factory()->null_value());
        if (!holder_is_lookup_start_object || IsLoadGlobalIC()) {
          holder_ref = MaybeObjectDirectHandle::Weak(holder);
        }
        TRACE_HANDLER_STATS(isolate(), LoadIC_LoadNonMaskingInterceptorDH);
        return MaybeObjectHandle(LoadHandler::LoadFullChain(
            isolate(), map, holder_ref, smi_handler));
      }
      if (holder_is_lookup_start_object) {
        DCHECK(map->has_named_interceptor());
        TRACE_HANDLER_STATS(isolate(), LoadIC_LoadInterceptorDH);
        return MaybeObjectHandle(smi_handler);
      }
      TRACE_HANDLER_STATS(isolate(), LoadIC_LoadInterceptorFromPrototypeDH);
      return MaybeObjectHandle(
          LoadHandler::LoadFromPrototype(isolate(), map, holder, *smi_handler));
    }
    case LookupIterator::ACCESSOR: {
      Handle<JSObject> holder =
          indirect_handle(lookup->GetHolder<JSObject>(), isolate());
      // Use simple field loads for some well-known callback properties.
      // The method will only return true for absolute truths based on the
      // lookup start object maps.
      FieldIndex field_index;
      if (Accessors::IsJSObjectFieldAccessor(isolate(), map, lookup->name(),
                                             &field_index)) {
        TRACE_HANDLER_STATS(isolate(), LoadIC_LoadFieldDH);
        return MaybeObjectHandle(
            LoadHandler::LoadField(isolate(), field_index));
      }
      if (IsJSModuleNamespace(*holder)) {
        DirectHandle<ObjectHashTable> exports(
            Cast<JSModuleNamespace>(holder)->module()->exports(), isolate());
        InternalIndex entry =
            exports->FindEntry(isolate(), roots, lookup->name(),
                               Smi::ToInt(Object::GetHash(*lookup->name())));
        // We found the accessor, so the entry must exist.
        DCHECK(entry.is_found());
        int value_index = ObjectHashTable::EntryToValueIndex(entry);
        Handle<Smi> smi_handler =
            LoadHandler::LoadModuleExport(isolate(), value_index);
        if (holder_is_lookup_start_object) {
          return MaybeObjectHandle(smi_handler);
        }
        return MaybeObjectHandle(LoadHandler::LoadFromPrototype(
            isolate(), map, holder, *smi_handler));
      }
      DirectHandle<Object> accessors = lookup->GetAccessors();
      if (IsAccessorPair(*accessors)) {
        DirectHandle<AccessorPair> accessor_pair =
            Cast<AccessorPair>(accessors);
        if (lookup->TryLookupCachedProperty(accessor_pair)) {
          DCHECK_EQ(LookupIterator::DATA, lookup->state());
          return MaybeObjectHandle(ComputeHandler(lookup));
        }
        Handle<Object> getter(accessor_pair->getter(), isolate());
        if (!IsCallableJSFunction(*getter) &&
            !IsFunctionTemplateInfo(*getter)) {
          // TODO(jgruber): Update counter name.
          TRACE_HANDLER_STATS(isolate(), LoadIC_SlowStub);
          return MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
        }
        set_accessor(getter);
        if ((IsFunctionTemplateInfo(*getter) &&
             Cast<FunctionTemplateInfo>(*getter)->BreakAtEntry(isolate())) ||
            (IsJSFunction(*getter) &&
             Cast<JSFunction>(*getter)->shared()->BreakAtEntry(isolate()))) {
          // Do not install an IC if the api function has a breakpoint.
          TRACE_HANDLER_STATS(isolate(), LoadIC_SlowStub);
          return MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
        }
        Handle<Smi> smi_handler;
        CallOptimization call_optimization(isolate(), getter);
        if (call_optimization.is_simple_api_call()) {
          CallOptimization::HolderLookup holder_lookup;
          DirectHandle<JSObject> api_holder =
              call_optimization.LookupHolderOfExpectedType(isolate(), map,
                                                           &holder_lookup);
          if (!call_optimization.IsCompatibleReceiverMap(api_holder, holder,
                                                         holder_lookup) ||
              !holder->HasFastProperties()) {
            TRACE_HANDLER_STATS(isolate(), LoadIC_SlowStub);
            return MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
          }
          smi_handler = LoadHandler::LoadApiGetter(isolate());
          DirectHandle<NativeContext> accessor_context =
              GetAccessorContext(call_optimization, holder->map(), isolate());
          TRACE_HANDLER_STATS(isolate(), LoadIC_LoadApiGetterFromPrototypeDH);
          return MaybeObjectHandle(LoadHandler::LoadFromPrototype(
              isolate(), map, holder, *smi_handler,
              MaybeObjectDirectHandle::Weak(call_optimization.api_call_info()),
              MaybeObjectDirectHandle::Weak(accessor_context)));
        }
        if (holder->HasFastProperties()) {
          DCHECK(IsCallableJSFunction(*getter));
          if (holder_is_lookup_start_object) {
            TRACE_HANDLER_STATS(isolate(), LoadIC_LoadAccessorDH);
            return MaybeObjectHandle::Weak(
                indirect_handle(accessor_pair, isolate()));
          }
          TRACE_HANDLER_STATS(isolate(), LoadIC_LoadAccessorFromPrototypeDH);
          return MaybeObjectHandle(LoadHandler::LoadFromPrototype(
              isolate(), map, holder,
              *LoadHandler::LoadAccessorFromPrototype(isolate()),
              MaybeObjectDirectHandle::Weak(getter)));
        }
        if (IsJSGlobalObject(*holder)) {
          TRACE_HANDLER_STATS(isolate(), LoadIC_LoadGlobalFromPrototypeDH);
          smi_handler = LoadHandler::LoadGlobal(isolate());
          return MaybeObjectHandle(LoadHandler::LoadFromPrototype(
              isolate(), map, holder, *smi_handler,
              MaybeObjectDirectHandle::Weak(lookup->GetPropertyCell())));
        } else {
          smi_handler = LoadHandler::LoadNormal(isolate());
          TRACE_HANDLER_STATS(isolate(), LoadIC_LoadNormalDH);
          if (holder_is_lookup_start_object)
            return MaybeObjectHandle(smi_handler);
          TRACE_HANDLER_STATS(isolate(), LoadIC_LoadNormalFromPrototypeDH);
        }
        return MaybeObjectHandle(LoadHandler::LoadFromPrototype(
            isolate(), map, holder, *smi_handler));
      }
      DirectHandle<AccessorInfo> info = Cast<AccessorInfo>(accessors);
      if (info->replace_on_access()) {
        set_slow_stub_reason(
            "getter needs to be reconfigured to data property");
        TRACE_HANDLER_STATS(isolate(), LoadIC_SlowStub);
        return MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
      }
      if (!info->has_getter(isolate()) || !holder->HasFastProperties() ||
          (info->is_sloppy() && !IsJSReceiver(*receiver))) {
        TRACE_HANDLER_STATS(isolate(), LoadIC_SlowStub);
        return MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
      }
      Handle<Smi> smi_handler = LoadHandler::LoadNativeDataProperty(
          isolate(), lookup->GetAccessorIndex());
      TRACE_HANDLER_STATS(isolate(), LoadIC_LoadNativeDataPropertyDH);
      if (holder_is_lookup_start_object) return MaybeObjectHandle(smi_handler);
      TRACE_HANDLER_STATS(isolate(),
                          LoadIC_LoadNativeDataPropertyFromPrototypeDH);
      return MaybeObjectHandle(
          LoadHandler::LoadFromPrototype(isolate(), map, holder, *smi_handler));
    }
    case LookupIterator::DATA: {
      DirectHandle<JSReceiver> holder = lookup->GetHolder<JSReceiver>();
      DCHECK_EQ(PropertyKind::kData, lookup->property_details().kind());
      Handle<Smi> smi_handler;
      if (lookup->is_dictionary_holder()) {
        if (IsJSGlobalObject(*holder, isolate())) {
          // TODO(verwaest): Also supporting the global object as receiver is a
          // workaround for code that leaks the global object.
          TRACE_HANDLER_STATS(isolate(), LoadIC_LoadGlobalDH);
          smi_handler = LoadHandler::LoadGlobal(isolate());
          return MaybeObjectHandle(LoadHandler::LoadFromPrototype(
              isolate(), map, holder, *smi_handler,
              MaybeObjectDirectHandle::Weak(lookup->GetPropertyCell())));
        }
        smi_handler = LoadHandler::LoadNormal(isolate());
        TRACE_HANDLER_STATS(isolate(), LoadIC_LoadNormalDH);
        if (holder_is_lookup_start_object)
          return MaybeObjectHandle(smi_handler);
        TRACE_HANDLER_STATS(isolate(), LoadIC_LoadNormalFromPrototypeDH);
      } else if (lookup->IsElement(*holder)) {
        TRACE_HANDLER_STATS(isolate(), LoadIC_SlowStub);
        return MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
      } else {
        DCHECK_EQ(PropertyLocation::kField,
                  lookup->property_details().location());
        DCHECK(IsJSObject(*holder, isolate()));
        FieldIndex field = lookup->GetFieldIndex();
        smi_handler = LoadHandler::LoadField(isolate(), field);
        TRACE_HANDLER_STATS(isolate(), LoadIC_LoadFieldDH);
        if (holder_is_lookup_start_object)
          return MaybeObjectHandle(smi_handler);
        TRACE_HANDLER_STATS(isolate(), LoadIC_LoadFieldFromPrototypeDH);
      }
      if (lookup->constness() == PropertyConstness::kConst &&
          !holder_is_lookup_start_object) {
        DCHECK_IMPLIES(!V8_DICT_PROPERTY_CONST_TRACKING_BOOL,
                       !lookup->is_dictionary_holder());
        DirectHandle<Object> value = lookup->GetDataValue();
        if (IsThinString(*value)) {
          value = direct_handle(Cast<ThinString>(*value)->actual(), isolate());
        }
        // Non internalized strings could turn into thin/cons strings
        // when internalized. Weak references to thin/cons strings are
        // not supported in the GC. If concurrent marking is running
        // and the thin/cons string is marked but the actual string is
        // not, then the weak reference could be missed.
        if (!IsString(*value) ||
            (IsString(*value) && IsInternalizedString(*value))) {
          MaybeObjectDirectHandle weak_value =
              IsSmi(*value) ? MaybeObjectHandle(*value, isolate())
                            : MaybeObjectHandle::Weak(*value, isolate());
          smi_handler = LoadHandler::LoadConstantFromPrototype(isolate());
          TRACE_HANDLER_STATS(isolate(), LoadIC_LoadConstantFromPrototypeDH);
          return MaybeObjectHandle(LoadHandler::LoadFromPrototype(
              isolate(), map, holder, *smi_handler, weak_value));
        }
      }
      return MaybeObjectHandle(
          LoadHandler::LoadFromPrototype(isolate(), map, holder, *smi_handler));
    }
    case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
      TRACE_HANDLER_STATS(isolate(), LoadIC_LoadIntegerIndexedExoticDH);
      return MaybeObjectHandle(LoadHandler::LoadNonExistent(isolate()));
    case LookupIterator::JSPROXY: {
      // Private names on JSProxy is currently not supported.
      if (lookup->name()->IsPrivate()) {
        return MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
      }
      Handle<Smi> smi_handler = LoadHandler::LoadProxy(isolate());
      if (holder_is_lookup_start_object) return MaybeObjectHandle(smi_handler);
      DirectHandle<JSProxy> holder_proxy = lookup->GetHolder<JSProxy>();
      return MaybeObjectHandle(LoadHandler::LoadFromPrototype(
          isolate(), map, holder_proxy, *smi_handler));
    }
    case LookupIterator::WASM_OBJECT:
    case LookupIterator::ACCESS_CHECK:
    case LookupIterator::NOT_FOUND:
    case LookupIterator::TRANSITION:
    case LookupIterator::STRING_LOOKUP_START_OBJECT:
      UNREACHABLE();
  }
  return MaybeObjectHandle(Handle<InstructionStream>::null());
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::CallOptimization::api_call_info(), BUILTIN_CODE, v8::internal::LookupIterator::constness(), v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::direct_handle(), v8::internal::anonymous_namespace{ic.cc}::GetAccessorContext(), v8::internal::LookupIterator::GetAccessorIndex(), v8::internal::LookupIterator::GetAccessors(), v8::internal::LookupIterator::GetDataValue(), v8::internal::LookupIterator::GetFieldIndex(), v8::internal::Object::GetHash(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetPropertyCell(), v8::internal::LookupIterator::GetReceiver(), v8::internal::indirect_handle(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::is_dictionary_holder(), v8::internal::InternalIndex::is_found(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::CallOptimization::is_simple_api_call(), v8::internal::IC::IsAnyHas(), v8::internal::CallOptimization::IsCompatibleReceiverMap(), v8::internal::LookupIterator::IsElement(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::Accessors::IsJSObjectFieldAccessor(), v8::internal::IC::IsLoadGlobalIC(), v8::internal::IC::isolate(), v8::internal::IsSmi(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::LookupIterator::JSPROXY, v8::internal::kConst, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::LoadHandler::LoadAccessorFromPrototype(), v8::internal::LoadHandler::LoadApiGetter(), v8::internal::LoadHandler::LoadConstantFromPrototype(), v8::internal::LoadHandler::LoadField(), v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::LoadHandler::LoadFullChain(), v8::internal::LoadHandler::LoadGlobal(), v8::internal::LoadHandler::LoadInterceptor(), v8::internal::LoadHandler::LoadModuleExport(), v8::internal::LoadHandler::LoadNativeDataProperty(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::LoadHandler::LoadNormal(), v8::internal::LoadHandler::LoadProxy(), v8::internal::LoadHandler::LoadSlow(), v8::internal::PropertyDetails::location(), v8::internal::LookupIterator::lookup_start_object(), v8::internal::IC::lookup_start_object_map(), v8::internal::CallOptimization::LookupHolderOfExpectedType(), v8::internal::LookupIterator::name(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::property_details(), v8::internal::IC::set_accessor(), v8::internal::IC::set_slow_stub_reason(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::Smi::ToInt(), TRACE_HANDLER_STATS, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TryLookupCachedProperty(), v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, v8::internal::value, v8::internal::LookupIterator::WASM_OBJECT, v8::internal::MaybeObjectHandle::Weak(), and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by UpdateCaches().
Load()
MaybeDirectHandle< Object > v8::internal::LoadIC::Load (Handle< JSAny > object, Handle< Name > name, bool update_feedback = true, DirectHandle< JSAny > receiver = DirectHandle<JSAny>())
Definition at line 387 of file ic.cc.
                                                                     {
  bool use_ic = (state() != NO_FEEDBACK) && v8_flags.use_ic && update_feedback;
  if (receiver.is_null()) {
    receiver = object;
  }
  // If the object is undefined or null it's illegal to try to get any
  // of its properties; throw a TypeError in that case.
  if (IsAnyHas() ? !IsJSReceiver(*object)
                 : IsNullOrUndefined(*object, isolate())) {
    if (use_ic) {
      // Ensure the IC state progresses.
      TRACE_HANDLER_STATS(isolate(), LoadIC_NonReceiver);
      update_lookup_start_object_map(object);
      SetCache(name, LoadHandler::LoadSlow(isolate()));
      TraceIC("LoadIC", name);
    }
    if (IsAnyHas()) {
      return TypeError(MessageTemplate::kInvalidInOperatorUse, object, name);
    } else {
      DCHECK(IsNullOrUndefined(*object, isolate()));
      ErrorUtils::ThrowLoadFromNullOrUndefined(isolate(), object, name);
      return MaybeDirectHandle<Object>();
    }
  }
  // If we encounter an object with a deprecated map, we want to update the
  // feedback vector with the migrated map.
  // Mark ourselves as RECOMPUTE_HANDLER so that we don't turn megamorphic due
  // to seeing the same map and handler.
  if (MigrateDeprecated(isolate(), object)) {
    UpdateState(object, name);
  }
  JSObject::MakePrototypesFast(object, kStartAtReceiver, isolate());
  update_lookup_start_object_map(object);
  PropertyKey key(isolate(), name);
  LookupIterator it = LookupIterator(isolate(), receiver, key, object);
  // Named lookup in the object.
  LookupForRead(&it, IsAnyHas());
  if (it.IsFound() || !ShouldThrowReferenceError()) {
    // Update inline cache and stub cache.
    if (use_ic) {
      UpdateCaches(&it);
    } else if (state() == NO_FEEDBACK) {
      // Tracing IC stats
      IsLoadGlobalIC() ? TraceIC("LoadGlobalIC", name)
                       : TraceIC("LoadIC", name);
    }
    if (IsAnyHas()) {
      // Named lookup in the object.
      Maybe<bool> maybe = JSReceiver::HasProperty(&it);
      if (maybe.IsNothing()) return MaybeDirectHandle<Object>();
      return isolate()->factory()->ToBoolean(maybe.FromJust());
    }
    // Get the property.
    DirectHandle<Object> result;
    ASSIGN_RETURN_ON_EXCEPTION(isolate(), result,
                               Object::GetProperty(&it, IsLoadGlobalIC()));
    if (it.IsFound()) {
      return result;
    } else if (!ShouldThrowReferenceError()) {
      return result;
    }
  }
  return ReferenceError(name);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::HasProperty(), v8::internal::if(), v8::internal::DirectHandle< T >::is_null(), v8::internal::IC::IsAnyHas(), v8::internal::LookupIterator::IsFound(), v8::internal::IC::IsLoadGlobalIC(), v8::Maybe< T >::IsNothing(), v8::internal::IsNullOrUndefined(), v8::internal::IC::isolate(), v8::internal::key, v8::internal::kStartAtReceiver, v8::internal::LoadHandler::LoadSlow(), v8::internal::LookupForRead(), v8::internal::JSObject::MakePrototypesFast(), v8::internal::anonymous_namespace{ic.cc}::MigrateDeprecated(), v8::internal::name, v8::internal::NO_FEEDBACK, v8::internal::IC::ReferenceError(), v8::base::internal::result, v8::internal::IC::SetCache(), ShouldThrowReferenceError(), v8::internal::IC::state(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), v8::internal::FactoryBase< Impl >::ToBoolean(), TRACE_HANDLER_STATS, v8::internal::IC::TraceIC(), v8::internal::IC::TypeError(), v8::internal::IC::update_lookup_start_object_map(), UpdateCaches(), v8::internal::IC::UpdateState(), and v8::internal::v8_flags.
Referenced by v8::internal::LoadGlobalIC::Load(), v8::internal::KeyedLoadIC::LoadName(), and v8::internal::RUNTIME_FUNCTION().
ShouldThrowReferenceError() [1/2]
bool v8::internal::LoadIC::ShouldThrowReferenceError () const [inline]
Definition at line 197 of file ic.h.
                                         {
    return ShouldThrowReferenceError(kind());
  }
References v8::internal::IC::kind().
Referenced by Load(), and v8::internal::RUNTIME_FUNCTION().
ShouldThrowReferenceError() [2/2]
static bool v8::internal::LoadIC::ShouldThrowReferenceError (FeedbackSlotKind kind) [inline], [static]
Definition at line 193 of file ic.h.
                                                               {
    return kind == FeedbackSlotKind::kLoadGlobalNotInsideTypeof;
  }
References v8::internal::IC::kind(), and v8::internal::kLoadGlobalNotInsideTypeof.
UpdateCaches()
void v8::internal::LoadIC::UpdateCaches (LookupIterator * lookup) [protected]
Definition at line 793 of file ic.cc.
                                                {
  MaybeObjectHandle handler;
  if (lookup->state() == LookupIterator::ACCESS_CHECK) {
    handler = MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
  } else if (!lookup->IsFound()) {
    if (lookup->IsPrivateName()) {
      handler = MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
    } else {
      TRACE_HANDLER_STATS(isolate(), LoadIC_LoadNonexistentDH);
      handler = MaybeObjectHandle(
          LoadHandler::LoadNonExistent(isolate(), lookup_start_object_map()));
    }
  } else if (IsLoadGlobalIC() && lookup->state() == LookupIterator::JSPROXY) {
    // If there is proxy just install the slow stub since we need to call the
    // HasProperty trap for global loads. The ProxyGetProperty builtin doesn't
    // handle this case.
    handler = MaybeObjectHandle(LoadHandler::LoadSlow(isolate()));
  } else {
    if (IsLoadGlobalIC()) {
      if (lookup->TryLookupCachedProperty()) {
        DCHECK_EQ(LookupIterator::DATA, lookup->state());
      }
      if (lookup->state() == LookupIterator::DATA &&
          lookup->GetReceiver().is_identical_to(lookup->GetHolder<Object>())) {
        DCHECK(IsJSGlobalObject(*lookup->GetReceiver()));
        // Now update the cell in the feedback vector.
        nexus()->ConfigurePropertyCellMode(lookup->GetPropertyCell());
        TraceIC("LoadGlobalIC", lookup->name());
        return;
      }
    }
    handler = ComputeHandler(lookup);
    CHECK(lookup->state() == LookupIterator::STRING_LOOKUP_START_OBJECT ||
          *lookup->GetHolder<Object>() == *(lookup->lookup_start_object()) ||
          LoadHandler::CanHandleHolderNotLookupStart(*handler.object()));
  }
  // Can't use {lookup->name()} because the LookupIterator might be in
  // "elements" mode for keys that are strings representing integers above
  // JSArray::kMaxIndex.
  SetCache(lookup->GetName(), handler);
  TraceIC("LoadIC", lookup->GetName());
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LoadHandler::CanHandleHolderNotLookupStart(), CHECK, ComputeHandler(), v8::internal::FeedbackNexus::ConfigurePropertyCellMode(), v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetPropertyCell(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::IsFound(), v8::internal::IC::IsLoadGlobalIC(), v8::internal::IC::isolate(), v8::internal::LookupIterator::IsPrivateName(), v8::internal::LookupIterator::JSPROXY, v8::internal::LoadHandler::LoadNonExistent(), v8::internal::LoadHandler::LoadSlow(), v8::internal::LookupIterator::lookup_start_object(), v8::internal::IC::lookup_start_object_map(), v8::internal::LookupIterator::name(), v8::internal::IC::nexus(), v8::internal::MaybeObjectHandle::object(), v8::internal::IC::SetCache(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, TRACE_HANDLER_STATS, v8::internal::IC::TraceIC(), and v8::internal::LookupIterator::TryLookupCachedProperty().
Referenced by Load().
Friends And Related Function Documentation
IC
friend class IC [friend]
Definition at line 214 of file ic.h.
NamedLoadHandlerCompiler
friend class NamedLoadHandlerCompiler [friend]
Definition at line 215 of file ic.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic.h
/mnt/V8SourceCode/src/ic/ic.cc