v8::internal::maglev::DeleteProperty Class Reference
#include <maglev-ir.h>
Public Member Functions
DeleteProperty (uint64_t bitfield, LanguageMode mode)
Input & context ()
Input & object ()
Input & key ()
LanguageMode mode () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 3, DeleteProperty >
Private Attributes
const LanguageMode mode_
Additional Inherited Members
Detailed Description
Definition at line 5161 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::DeleteProperty::Base = FixedInputValueNodeT<3, DeleteProperty> [private]
Definition at line 5162 of file maglev-ir.h.
Constructor & Destructor Documentation
DeleteProperty()
v8::internal::maglev::DeleteProperty::DeleteProperty (uint64_t bitfield, LanguageMode mode) [inline], [explicit]
Definition at line 5165 of file maglev-ir.h.
      : Base(bitfield), mode_(mode) {}
Member Function Documentation
context()
Input& v8::internal::maglev::DeleteProperty::context () [inline]
Definition at line 5174 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::DeleteProperty::GenerateCode (MaglevAssembler * , const ProcessingState &)
key()
Input& v8::internal::maglev::DeleteProperty::key () [inline]
Definition at line 5176 of file maglev-ir.h.
{ return Node::input(2); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::DeleteProperty::MaxCallStackArgs () const
mode()
LanguageMode v8::internal::maglev::DeleteProperty::mode () const [inline]
Definition at line 5178 of file maglev-ir.h.
{ return mode_; }
References mode_.
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
object()
Input& v8::internal::maglev::DeleteProperty::object () [inline]
Definition at line 5175 of file maglev-ir.h.
{ return Node::input(1); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::DeleteProperty::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7937 of file maglev-ir.cc.
                                                                            {
  os << "(" << LanguageMode2String(mode()) << ")";
}
References v8::internal::LanguageMode2String(), and mode().
SetValueLocationConstraints()
void v8::internal::maglev::DeleteProperty::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::DeleteProperty::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged}
Definition at line 5170 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::DeleteProperty::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 5169 of file maglev-ir.h.
mode_
const LanguageMode v8::internal::maglev::DeleteProperty::mode_ [private]
Definition at line 5186 of file maglev-ir.h.
Referenced by mode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc