v8::internal::InternalizedStringTableCleaner Class Reference
Public Member Functions
InternalizedStringTableCleaner (Heap *heap)
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end) override
int PointersRemoved () const
Private Attributes
Heap * heap_
int pointers_removed_ = 0
Additional Inherited Members
Detailed Description
Definition at line 1099 of file mark-compact.cc.
Constructor & Destructor Documentation
InternalizedStringTableCleaner()
v8::internal::InternalizedStringTableCleaner::InternalizedStringTableCleaner (Heap * heap) [inline], [explicit]
Definition at line 1101 of file mark-compact.cc.
: heap_(heap) {}
Member Function Documentation
PointersRemoved()
int v8::internal::InternalizedStringTableCleaner::PointersRemoved () const [inline]
Definition at line 1128 of file mark-compact.cc.
{ return pointers_removed_; }
References pointers_removed_.
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::Run().
VisitRootPointers() [1/2]
void v8::internal::InternalizedStringTableCleaner::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 1103 of file mark-compact.cc.
                                                                            {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitRootPointers() [2/2]
void v8::internal::InternalizedStringTableCleaner::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 1108 of file mark-compact.cc.
                                                         {
    DCHECK_EQ(root, Root::kStringTable);
    // Visit all HeapObject pointers in [start, end).
    Isolate* const isolate = heap_->isolate();
    for (OffHeapObjectSlot p = start; p < end; ++p) {
      Tagged<Object> o = p.load(isolate);
      if (IsHeapObject(o)) {
        Tagged<HeapObject> heap_object = Cast<HeapObject>(o);
        DCHECK(!HeapLayout::InYoungGeneration(heap_object));
        if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
                heap_, heap_->marking_state(), heap_object)) {
          pointers_removed_++;
          p.store(StringTable::deleted_element());
        }
      }
    }
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::StringTable::deleted_element(), v8::internal::compiler::end(), heap_, v8::internal::HeapLayout::InYoungGeneration(), v8::internal::IsHeapObject(), v8::internal::Heap::isolate(), v8::internal::MarkingHelper::IsUnmarkedAndNotAlwaysLive(), v8::internal::Heap::marking_state(), and pointers_removed_.
Member Data Documentation
heap_
Heap* v8::internal::InternalizedStringTableCleaner::heap_ [private]
Definition at line 1131 of file mark-compact.cc.
Referenced by VisitRootPointers().
pointers_removed_
int v8::internal::InternalizedStringTableCleaner::pointers_removed_ = 0 [private]
Definition at line 1132 of file mark-compact.cc.
Referenced by PointersRemoved(), and VisitRootPointers().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc