v8::internal::WasmArray Class Reference
#include <wasm-objects.h>
Public Member Functions
ObjectSlot ElementSlot (uint32_t index)
V8_EXPORT_PRIVATE wasm::WasmValue GetElement (uint32_t index)
void SetTaggedElement (uint32_t index, DirectHandle< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
uint32_t element_offset (uint32_t index)
Address ElementAddress (uint32_t index)
Static Public Member Functions
static wasm::CanonicalTypeIndex type_index (Tagged< Map > map)
static const wasm::CanonicalValueType GcSafeElementType (Tagged< Map > map)
static int SizeFor (Tagged< Map > map, int length)
static DirectHandle< Object > GetElement (Isolate *isolate, DirectHandle< WasmArray > array, uint32_t index)
static constexpr int MaxLength (uint32_t element_size_bytes)
static int MaxLength (const wasm::ArrayType *type)
static void EncodeElementSizeInMap (int element_size, Tagged< Map > map)
static int DecodeElementSizeFromMap (Tagged< Map > map)
Detailed Description
Definition at line 1464 of file wasm-objects.h.
Member Function Documentation
DecodeElementSizeFromMap()
int v8::internal::WasmArray::DecodeElementSizeFromMap (Tagged< Map > map) [inline], [static]
Definition at line 817 of file wasm-objects-inl.h.
                                                       {
  return map->WasmByte1();
}
Referenced by element_offset(), and SizeFor().
element_offset()
uint32_t v8::internal::WasmArray::element_offset (uint32_t index) [inline]
Definition at line 782 of file wasm-objects-inl.h.
                                                 {
  DCHECK_LE(index, length());
  int element_size = DecodeElementSizeFromMap(map());
  return WasmArray::kHeaderSize + index * element_size;
}
References DCHECK_LE, DecodeElementSizeFromMap(), v8::internal::index, and v8::internal::length.
Referenced by ElementAddress(), GetElement(), and SetTaggedElement().
ElementAddress()
Address v8::internal::WasmArray::ElementAddress (uint32_t index) [inline]
Definition at line 788 of file wasm-objects-inl.h.
                                                {
  return ptr() + element_offset(index) - kHeapObjectTag;
}
References element_offset(), v8::internal::index, and v8::internal::kHeapObjectTag.
ElementSlot()
ObjectSlot v8::internal::WasmArray::ElementSlot (uint32_t index) [inline]
Definition at line 792 of file wasm-objects-inl.h.
                                                {
  DCHECK_LE(index, length());
  DCHECK(map()->wasm_type_info()->element_type().is_reference());
  return RawField(kHeaderSize + kTaggedSize * index);
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::index, v8::internal::wasm::is_reference(), v8::internal::kTaggedSize, and v8::internal::length.
EncodeElementSizeInMap()
void v8::internal::WasmArray::EncodeElementSizeInMap (int element_size, Tagged< Map > map) [inline], [static]
Definition at line 812 of file wasm-objects-inl.h.
                                                                        {
  map->SetWasmByte1(element_size);
}
Referenced by v8::internal::CreateArrayMap().
GcSafeElementType()
const wasm::CanonicalValueType v8::internal::WasmArray::GcSafeElementType (Tagged< Map > map) [inline], [static]
Definition at line 767 of file wasm-objects-inl.h.
                                                                         {
  DCHECK_EQ(WASM_ARRAY_TYPE, map->instance_type());
  Tagged<HeapObject> raw = Cast<HeapObject>(map->constructor_or_back_pointer());
  // The {WasmTypeInfo} might be in the middle of being moved, which is why we
  // can't read its map for a checked cast. But we can rely on its native type
  // pointer being intact in the old location.
  Tagged<WasmTypeInfo> type_info = UncheckedCast<WasmTypeInfo>(raw);
  return type_info->element_type();
}
References DCHECK_EQ.
GetElement() [1/2]
DirectHandle< Object > v8::internal::WasmArray::GetElement (Isolate * isolate, DirectHandle< WasmArray > array, uint32_t index) [inline], [static]
Definition at line 799 of file wasm-objects-inl.h.
                                                           {
  if (index >= array->length()) {
    return isolate->factory()->undefined_value();
  }
  wasm::CanonicalValueType element_type =
      array->map()->wasm_type_info()->element_type();
  return ReadValueAt(isolate, array, element_type,
                     array->element_offset(index));
}
References v8::internal::Isolate::factory(), and v8::internal::index.
GetElement() [2/2]
wasm::WasmValue v8::internal::WasmArray::GetElement (uint32_t index)
Definition at line 2329 of file wasm-objects.cc.
                                                  {
  wasm::CanonicalValueType element_type =
      map()->wasm_type_info()->element_type();
  int element_offset =
      WasmArray::kHeaderSize + index * element_type.value_kind_size();
  Address element_address = GetFieldAddress(element_offset);
  switch (element_type.kind()) {
#define CASE_TYPE(value_type, ctype) \
  case wasm::value_type: \
    return wasm::WasmValue(base::ReadUnalignedValue<ctype>(element_address));
    CASE_TYPE(kI8, int8_t)
    CASE_TYPE(kI16, int16_t)
    FOREACH_WASMVALUE_CTYPES(CASE_TYPE)
#undef CASE_TYPE
    case wasm::kF16:
      return wasm::WasmValue(fp16_ieee_to_fp32_value(
          base::ReadUnalignedValue<uint16_t>(element_address)));
    case wasm::kRef:
    case wasm::kRefNull: {
      DirectHandle<Object> ref(TaggedField<Object>::load(*this, element_offset),
                               GetIsolateFromWritableObject(*this));
      return wasm::WasmValue(ref, element_type);
    }
    case wasm::kVoid:
    case wasm::kTop:
    case wasm::kBottom:
      UNREACHABLE();
  }
}
References CASE_TYPE, element_offset(), FOREACH_WASMVALUE_CTYPES, v8::internal::GetIsolateFromWritableObject(), v8::internal::index, v8::internal::kI16, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::UNREACHABLE(), and v8::internal::wasm::ValueTypeBase::value_kind_size().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::GetWasmArrayRefElement().
MaxLength() [1/2]
static int v8::internal::WasmArray::MaxLength (const wasm::ArrayType * type) [inline], [static]
Definition at line 1496 of file wasm-objects.h.
                                                  {
    return MaxLength(type->element_type().value_kind_size());
  }
References v8::internal::tracing::type.
MaxLength() [2/2]
static constexpr int v8::internal::WasmArray::MaxLength (uint32_t element_size_bytes) [inline], [static], [constexpr]
Definition at line 1489 of file wasm-objects.h.
                                                              {
    // The total object size must fit into a Smi, for filler objects. To make
    // the behavior of Wasm programs independent from the Smi configuration,
    // we hard-code the smaller of the two supported ranges.
    return (SmiTagging<4>::kSmiMaxValue - kHeaderSize) / element_size_bytes;
  }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::WasmInterpreterRuntime::ArrayNewUninitialized(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewSegment(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmAllocateArray().
SetTaggedElement()
void v8::internal::WasmArray::SetTaggedElement (uint32_t index, DirectHandle< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER)
Definition at line 2359 of file wasm-objects.cc.
                                                        {
  DCHECK(map()->wasm_type_info()->element_type().is_reference());
  TaggedField<Object>::store(*this, element_offset(index), *value);
  CONDITIONAL_WRITE_BARRIER(*this, element_offset(index), *value, mode);
}
References CONDITIONAL_WRITE_BARRIER, v8::internal::DCHECK(), element_offset(), v8::internal::index, v8::internal::wasm::is_reference(), mode(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store(), and v8::internal::value.
SizeFor()
int v8::internal::WasmArray::SizeFor (Tagged< Map > map, int length) [inline], [static]
Definition at line 777 of file wasm-objects-inl.h.
                                                  {
  int element_size = DecodeElementSizeFromMap(map);
  return kHeaderSize + RoundUp(element_size * length, kTaggedSize);
}
References DecodeElementSizeFromMap(), v8::internal::kTaggedSize, v8::internal::length, and RoundUp().
Referenced by v8::internal::HeapObject::SizeFromMap().
type_index()
static wasm::CanonicalTypeIndex v8::internal::WasmArray::type_index (Tagged< Map > map) [inline], [static]
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc