v8::internal::maglev::UncheckedNumberOrOddballToFloat64 Class Reference
#include <maglev-ir.h>
Public Member Functions
UncheckedNumberOrOddballToFloat64 (uint64_t bitfield, TaggedToFloat64ConversionType conversion_type)
Input & input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
TaggedToFloat64ConversionType conversion_type () const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, UncheckedNumberOrOddballToFloat64 >
using TaggedToFloat64ConversionTypeOffset = NextBitField< TaggedToFloat64ConversionType, 2 >
Additional Inherited Members
Detailed Description
Definition at line 4690 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::UncheckedNumberOrOddballToFloat64::Base = FixedInputValueNodeT<1, UncheckedNumberOrOddballToFloat64> [private]
Definition at line 4692 of file maglev-ir.h.
TaggedToFloat64ConversionTypeOffset
using v8::internal::maglev::UncheckedNumberOrOddballToFloat64::TaggedToFloat64ConversionTypeOffset = NextBitField<TaggedToFloat64ConversionType, 2> [private]
Definition at line 4718 of file maglev-ir.h.
Constructor & Destructor Documentation
UncheckedNumberOrOddballToFloat64()
v8::internal::maglev::UncheckedNumberOrOddballToFloat64::UncheckedNumberOrOddballToFloat64 (uint64_t bitfield, TaggedToFloat64ConversionType conversion_type) [inline], [explicit]
Definition at line 4695 of file maglev-ir.h.
      : Base(TaggedToFloat64ConversionTypeOffset::update(bitfield,
                                                         conversion_type)) {}
Member Function Documentation
conversion_type()
TaggedToFloat64ConversionType v8::internal::maglev::UncheckedNumberOrOddballToFloat64::conversion_type () const [inline]
Definition at line 4711 of file maglev-ir.h.
                                                        {
    return TaggedToFloat64ConversionTypeOffset::decode(bitfield());
  }
Referenced by options(), and PrintParams().
GenerateCode()
void v8::internal::maglev::UncheckedNumberOrOddballToFloat64::GenerateCode (MaglevAssembler * , const ProcessingState &)
input()
Input& v8::internal::maglev::UncheckedNumberOrOddballToFloat64::input () [inline]
Definition at line 4705 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
options()
auto v8::internal::maglev::UncheckedNumberOrOddballToFloat64::options () const [inline]
Definition at line 4715 of file maglev-ir.h.
{ return std::tuple{conversion_type()}; }
References conversion_type().
PrintParams()
void v8::internal::maglev::UncheckedNumberOrOddballToFloat64::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8155 of file maglev-ir.cc.
                                                               {
  os << "(" << conversion_type() << ")";
}
References conversion_type().
SetValueLocationConstraints()
void v8::internal::maglev::UncheckedNumberOrOddballToFloat64::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::UncheckedNumberOrOddballToFloat64::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 4703 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::UncheckedNumberOrOddballToFloat64::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::Float64() | OpProperties::ConversionNode()
Definition at line 4700 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc