v8::internal::RegExpNode Class Reference
#include <regexp-nodes.h>
Public Member Functions
RegExpNode (Zone *zone)
virtual ~RegExpNode ()
virtual void Accept (NodeVisitor *visitor)=0
virtual void Emit (RegExpCompiler *compiler, Trace *trace)=0
uint32_t EatsAtLeast (bool not_at_start)
virtual EatsAtLeastInfo EatsAtLeastFromLoopEntry ()
bool EmitQuickCheck (RegExpCompiler *compiler, Trace *bounds_check_trace, Trace *trace, bool preload_has_checked_bounds, Label *on_possible_success, QuickCheckDetails *details_return, bool fall_through_on_failure, ChoiceNode *predecessor)
virtual void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start)=0
virtual void GetQuickCheckDetailsFromLoopEntry (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start)
virtual int FixedLengthLoopLength ()
virtual RegExpNode * GetSuccessorOfOmnivorousTextNode (RegExpCompiler *compiler)
bool KeepRecursing (RegExpCompiler *compiler)
virtual void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start)
virtual RegExpNode * FilterOneByte (int depth, RegExpCompiler *compiler)
RegExpNode * replacement ()
RegExpNode * set_replacement (RegExpNode *replacement)
void SaveBMInfo (BoyerMooreLookahead *bm, bool not_at_start, int offset)
Label * label ()
bool on_work_list ()
void set_on_work_list (bool value)
NodeInfo * info ()
const EatsAtLeastInfo * eats_at_least_info () const
void set_eats_at_least_info (const EatsAtLeastInfo &eats_at_least)
void SetDoNotInline ()
BoyerMooreLookahead * bm_info (bool not_at_start)
virtual SeqRegExpNode * AsSeqRegExpNode ()
Zone * zone () const
Static Public Attributes
static const int kNodeIsTooComplexForFixedLengthLoops = kMinInt
static const int kRecursionBudget = 200
static const int kMaxCopiesCodeGenerated = 10
Protected Types
enum LimitResult { DONE
, CONTINUE
 }
Protected Member Functions
LimitResult LimitVersions (RegExpCompiler *compiler, Trace *trace)
void set_bm_info (bool not_at_start, BoyerMooreLookahead *bm)
Protected Attributes
RegExpNode * replacement_
Private Attributes
Label label_
bool on_work_list_
NodeInfo info_
EatsAtLeastInfo eats_at_least_
int trace_count_
BoyerMooreLookahead * bm_info_ [2]
Zone * zone_
Static Private Attributes
static const int kFirstCharBudget = 10
Detailed Description
Definition at line 133 of file regexp-nodes.h.
Member Enumeration Documentation
LimitResult
enum v8::internal::RegExpNode::LimitResult [protected]
Enumerator
DONE
CONTINUE
Definition at line 276 of file regexp-nodes.h.
{ DONE, CONTINUE };
Constructor & Destructor Documentation
RegExpNode()
v8::internal::RegExpNode::RegExpNode (Zone * zone) [inline], [explicit]
Definition at line 135 of file regexp-nodes.h.
      : replacement_(nullptr),
        on_work_list_(false),
        trace_count_(0),
        zone_(zone) {
    bm_info_[0] = bm_info_[1] = nullptr;
  }
References bm_info_.
 RegExpNode()
v8::internal::RegExpNode::~RegExpNode () [virtual], [default]
Member Function Documentation
Accept()
virtual void v8::internal::RegExpNode::Accept (NodeVisitor * visitor) [pure virtual]
Implemented in v8::internal::LoopChoiceNode, v8::internal::NegativeLookaroundChoiceNode, v8::internal::ChoiceNode, v8::internal::EndNode, v8::internal::BackReferenceNode, v8::internal::AssertionNode, v8::internal::TextNode, and v8::internal::ActionNode.
Referenced by v8::internal::Analysis< Propagators >::EnsureAnalyzed(), and v8::internal::DotPrinterImpl::Visit().
AsSeqRegExpNode()
virtual SeqRegExpNode* v8::internal::RegExpNode::AsSeqRegExpNode () [inline], [virtual]
Reimplemented in v8::internal::SeqRegExpNode.
Definition at line 271 of file regexp-nodes.h.
{ return nullptr; }
Referenced by v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative().
bm_info()
BoyerMooreLookahead* v8::internal::RegExpNode::bm_info (bool not_at_start) [inline]
Definition at line 262 of file regexp-nodes.h.
                                                  {
    return bm_info_[not_at_start ? 1 : 0];
  }
References bm_info_.
Referenced by v8::internal::AssertionNode::EmitBoundaryCheck(), and v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch().
eats_at_least_info()
const EatsAtLeastInfo* v8::internal::RegExpNode::eats_at_least_info () const [inline]
Definition at line 248 of file regexp-nodes.h.
{ return &eats_at_least_; }
References eats_at_least_.
Referenced by v8::internal::LoopChoiceNode::EatsAtLeastFromLoopEntry(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAction(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAssertion(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitBackReference(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitChoice(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitLoopChoiceContinueNode(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitNegativeLookaroundChoiceContinueNode(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitText().
EatsAtLeast()
uint32_t v8::internal::RegExpNode::EatsAtLeast (bool not_at_start)
Definition at line 1504 of file regexp-compiler.cc.
                                                  {
  return not_at_start ? eats_at_least_.eats_at_least_from_not_start
                      : eats_at_least_.eats_at_least_from_possibly_start;
}
References eats_at_least_, v8::internal::EatsAtLeastInfo::eats_at_least_from_not_start, and v8::internal::EatsAtLeastInfo::eats_at_least_from_possibly_start.
Referenced by v8::internal::LoopChoiceNode::EatsAtLeastFromLoopEntry(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch(), EmitQuickCheck(), v8::internal::LoopChoiceNode::GetQuickCheckDetails(), and v8::internal::ChoiceNode::SetUpPreLoad().
EatsAtLeastFromLoopEntry()
EatsAtLeastInfo v8::internal::RegExpNode::EatsAtLeastFromLoopEntry () [virtual]
Reimplemented in v8::internal::LoopChoiceNode.
Definition at line 1509 of file regexp-compiler.cc.
                                                     {
  // SET_REGISTER_FOR_LOOP is only used to initialize loop counters, and it
  // implies that the following node must be a LoopChoiceNode. If we need to
  // set registers to constant values for other reasons, we could introduce a
  // new action type SET_REGISTER that doesn't imply anything about its
  // successor.
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAction().
Emit()
virtual void v8::internal::RegExpNode::Emit (RegExpCompiler * compiler, Trace * trace) [pure virtual]
Implemented in v8::internal::LoopChoiceNode, v8::internal::ChoiceNode, v8::internal::NegativeSubmatchSuccess, v8::internal::EndNode, v8::internal::BackReferenceNode, v8::internal::AssertionNode, v8::internal::TextNode, and v8::internal::ActionNode.
Referenced by v8::internal::RegExpCompiler::Assemble(), v8::internal::AssertionNode::BacktrackIfPrevious(), v8::internal::ActionNode::Emit(), v8::internal::TextNode::Emit(), v8::internal::AssertionNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), and v8::internal::Trace::Flush().
EmitQuickCheck()
bool v8::internal::RegExpNode::EmitQuickCheck (RegExpCompiler * compiler, Trace * bounds_check_trace, Trace * trace, bool preload_has_checked_bounds, Label * on_possible_success, QuickCheckDetails * details_return, bool fall_through_on_failure, ChoiceNode * predecessor)
Definition at line 1573 of file regexp-compiler.cc.
                                                         {
  DCHECK_NOT_NULL(predecessor);
  if (details->characters() == 0) return false;
  GetQuickCheckDetails(details, compiler, 0,
                       trace->at_start() == Trace::FALSE_VALUE);
  if (details->cannot_match()) return false;
  if (!details->Rationalize(compiler->one_byte())) return false;
  DCHECK(details->characters() == 1 ||
         compiler->macro_assembler()->CanReadUnaligned());
  uint32_t mask = details->mask();
  uint32_t value = details->value();
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  if (trace->characters_preloaded() != details->characters()) {
    DCHECK(trace->cp_offset() == bounds_check_trace->cp_offset());
    // The bounds check is performed using the minimum number of characters
    // any choice would eat, so if the bounds check fails, then none of the
    // choices can succeed, so we can just immediately backtrack, rather
    // than go to the next choice. The number of characters preloaded may be
    // less than the number used for the bounds check.
    int eats_at_least = predecessor->EatsAtLeast(
        bounds_check_trace->at_start() == Trace::FALSE_VALUE);
    DCHECK_GE(eats_at_least, details->characters());
    assembler->LoadCurrentCharacter(
        trace->cp_offset(), bounds_check_trace->backtrack(),
        !preload_has_checked_bounds, details->characters(), eats_at_least);
  }
  bool need_mask = true;
  if (details->characters() == 1) {
    // If number of characters preloaded is 1 then we used a byte or 16 bit
    // load so the value is already masked down.
    const uint32_t char_mask = CharMask(compiler->one_byte());
    if ((mask & char_mask) == char_mask) need_mask = false;
    mask &= char_mask;
  } else {
    // For 2-character preloads in one-byte mode or 1-character preloads in
    // two-byte mode we also use a 16 bit load with zero extend.
    static const uint32_t kTwoByteMask = 0xFFFF;
    static const uint32_t kFourByteMask = 0xFFFFFFFF;
    if (details->characters() == 2 && compiler->one_byte()) {
      if ((mask & kTwoByteMask) == kTwoByteMask) need_mask = false;
    } else if (details->characters() == 1 && !compiler->one_byte()) {
      if ((mask & kTwoByteMask) == kTwoByteMask) need_mask = false;
    } else {
      if (mask == kFourByteMask) need_mask = false;
    }
  }
  if (fall_through_on_failure) {
    if (need_mask) {
      assembler->CheckCharacterAfterAnd(value, mask, on_possible_success);
    } else {
      assembler->CheckCharacter(value, on_possible_success);
    }
  } else {
    if (need_mask) {
      assembler->CheckNotCharacterAfterAnd(value, mask, trace->backtrack());
    } else {
      assembler->CheckNotCharacter(value, trace->backtrack());
    }
  }
  return true;
}
References v8::internal::Trace::at_start(), v8::internal::Trace::backtrack(), v8::internal::QuickCheckDetails::cannot_match(), v8::internal::RegExpMacroAssembler::CanReadUnaligned(), v8::internal::QuickCheckDetails::characters(), v8::internal::Trace::characters_preloaded(), v8::internal::anonymous_namespace{regexp-compiler.cc}::CharMask(), v8::internal::RegExpMacroAssembler::CheckCharacter(), v8::internal::RegExpMacroAssembler::CheckCharacterAfterAnd(), v8::internal::RegExpMacroAssembler::CheckNotCharacter(), v8::internal::RegExpMacroAssembler::CheckNotCharacterAfterAnd(), v8::internal::Trace::cp_offset(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_NOT_NULL, EatsAtLeast(), v8::internal::Trace::FALSE_VALUE, GetQuickCheckDetails(), v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::QuickCheckDetails::mask(), v8::internal::RegExpCompiler::one_byte(), v8::internal::QuickCheckDetails::Rationalize(), v8::internal::value, and v8::internal::QuickCheckDetails::value().
Referenced by v8::internal::ChoiceNode::EmitChoices().
FillInBMInfo()
virtual void v8::internal::RegExpNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [inline], [virtual]
Reimplemented in v8::internal::LoopChoiceNode, v8::internal::NegativeLookaroundChoiceNode, v8::internal::ChoiceNode, v8::internal::EndNode, v8::internal::BackReferenceNode, v8::internal::AssertionNode, v8::internal::TextNode, v8::internal::ActionNode, and v8::internal::SeqRegExpNode.
Definition at line 206 of file regexp-nodes.h.
                                                                        {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::SeqRegExpNode::FillInBMInfo(), v8::internal::ActionNode::FillInBMInfo(), v8::internal::TextNode::FillInBMInfo(), v8::internal::AssertionNode::FillInBMInfo(), and v8::internal::ChoiceNode::FillInBMInfo().
FilterOneByte()
virtual RegExpNode* v8::internal::RegExpNode::FilterOneByte (int depth, RegExpCompiler * compiler) [inline], [virtual]
Reimplemented in v8::internal::LoopChoiceNode, v8::internal::NegativeLookaroundChoiceNode, v8::internal::ChoiceNode, v8::internal::TextNode, and v8::internal::SeqRegExpNode.
Definition at line 214 of file regexp-nodes.h.
                                                                         {
    return this;
  }
Referenced by v8::internal::ChoiceNode::FilterOneByte(), v8::internal::NegativeLookaroundChoiceNode::FilterOneByte(), v8::internal::LoopChoiceNode::FilterOneByte(), v8::internal::SeqRegExpNode::FilterSuccessor(), and v8::internal::RegExpCompiler::PreprocessRegExp().
FixedLengthLoopLength()
virtual int v8::internal::RegExpNode::FixedLengthLoopLength () [inline], [virtual]
Reimplemented in v8::internal::TextNode, and v8::internal::ActionNode.
Definition at line 189 of file regexp-nodes.h.
                                      {
    return kNodeIsTooComplexForFixedLengthLoops;
  }
References kNodeIsTooComplexForFixedLengthLoops.
Referenced by v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative().
GetQuickCheckDetails()
virtual void v8::internal::RegExpNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [pure virtual]
Implemented in v8::internal::AssertionNode, v8::internal::ActionNode, v8::internal::LoopChoiceNode, v8::internal::NegativeLookaroundChoiceNode, v8::internal::ChoiceNode, v8::internal::EndNode, v8::internal::BackReferenceNode, and v8::internal::TextNode.
Referenced by EmitQuickCheck(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::ChoiceNode::GetQuickCheckDetails(), v8::internal::NegativeLookaroundChoiceNode::GetQuickCheckDetails(), v8::internal::LoopChoiceNode::GetQuickCheckDetails(), v8::internal::ActionNode::GetQuickCheckDetails(), and v8::internal::AssertionNode::GetQuickCheckDetails().
GetQuickCheckDetailsFromLoopEntry()
void v8::internal::RegExpNode::GetQuickCheckDetailsFromLoopEntry (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [virtual]
Reimplemented in v8::internal::LoopChoiceNode.
Definition at line 1518 of file regexp-compiler.cc.
                                                                      {
  // See comment in RegExpNode::EatsAtLeastFromLoopEntry.
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::ActionNode::GetQuickCheckDetails().
GetSuccessorOfOmnivorousTextNode()
virtual RegExpNode* v8::internal::RegExpNode::GetSuccessorOfOmnivorousTextNode (RegExpCompiler * compiler) [inline], [virtual]
Reimplemented in v8::internal::TextNode.
Definition at line 194 of file regexp-nodes.h.
                                {
    return nullptr;
  }
Referenced by v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch().
info()
NodeInfo* v8::internal::RegExpNode::info () [inline]
Definition at line 247 of file regexp-nodes.h.
{ return &info_; }
References info_.
Referenced by v8::internal::AnalyzeRegExp(), v8::internal::Analysis< Propagators >::EnsureAnalyzed(), v8::internal::SeqRegExpNode::FilterOneByte(), v8::internal::TextNode::FilterOneByte(), v8::internal::ChoiceNode::FilterOneByte(), v8::internal::NegativeLookaroundChoiceNode::FilterOneByte(), v8::internal::LoopChoiceNode::FilterOneByte(), v8::internal::LoopChoiceNode::GetQuickCheckDetails(), v8::internal::DotPrinterImpl::PrintAttributes(), replacement(), set_replacement(), v8::internal::DotPrinterImpl::Visit(), v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitAction(), v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitChoice(), v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitLoopChoiceContinueNode(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitLoopChoiceLoopNode().
KeepRecursing()
bool v8::internal::RegExpNode::KeepRecursing (RegExpCompiler * compiler)
Definition at line 1394 of file regexp-compiler.cc.
                                                       {
  return !compiler->limiting_recursion() &&
         compiler->recursion_depth() <= RegExpCompiler::kMaxRecursion;
}
References v8::internal::RegExpCompiler::kMaxRecursion, v8::internal::RegExpCompiler::limiting_recursion(), and v8::internal::RegExpCompiler::recursion_depth().
Referenced by v8::internal::Trace::Flush(), and LimitVersions().
label()
Label* v8::internal::RegExpNode::label () [inline]
Definition at line 236 of file regexp-nodes.h.
{ return &label_; }
References label_.
Referenced by v8::internal::RegExpCompiler::AddWork(), v8::internal::RegExpCompiler::Assemble(), v8::internal::EndNode::Emit(), v8::internal::NegativeSubmatchSuccess::Emit(), v8::internal::Trace::Flush(), and v8::internal::DotPrinterImpl::PrintAttributes().
LimitVersions()
RegExpNode::LimitResult v8::internal::RegExpNode::LimitVersions (RegExpCompiler * compiler, Trace * trace) [protected]
Definition at line 1352 of file regexp-compiler.cc.
                                                                {
  // If we are generating a fixed length loop then don't stop and don't reuse
  // code.
  if (trace->fixed_length_loop_state() != nullptr) {
    return CONTINUE;
  }
  RegExpMacroAssembler* macro_assembler = compiler->macro_assembler();
  if (trace->is_trivial()) {
    if (label_.is_bound() || on_work_list() || !KeepRecursing(compiler)) {
      // If a generic version is already scheduled to be generated or we have
      // recursed too deeply then just generate a jump to that code.
      macro_assembler->GoTo(&label_);
      // This will queue it up for generation of a generic version if it hasn't
      // already been queued.
      compiler->AddWork(this);
      return DONE;
    }
    // Generate generic version of the node and bind the label for later use.
    macro_assembler->Bind(&label_);
    return CONTINUE;
  }
  // We are being asked to make a non-generic version. Keep track of how many
  // non-generic versions we generate so as not to overdo it.
  trace_count_++;
  if (KeepRecursing(compiler) && compiler->optimize() &&
      trace_count_ < kMaxCopiesCodeGenerated) {
    return CONTINUE;
  }
  // If we get here code has been generated for this node too many times or
  // recursion is too deep. Time to switch to a generic version. The code for
  // generic versions above can handle deep recursion properly.
  bool was_limiting = compiler->limiting_recursion();
  compiler->set_limiting_recursion(true);
  trace->Flush(compiler, this);
  compiler->set_limiting_recursion(was_limiting);
  return DONE;
}
References v8::internal::RegExpCompiler::AddWork(), v8::internal::RegExpMacroAssembler::Bind(), CONTINUE, DONE, v8::internal::Trace::fixed_length_loop_state(), v8::internal::Trace::Flush(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::Label::is_bound(), v8::internal::Trace::is_trivial(), KeepRecursing(), kMaxCopiesCodeGenerated, label_, v8::internal::RegExpCompiler::limiting_recursion(), v8::internal::RegExpCompiler::macro_assembler(), on_work_list(), v8::internal::RegExpCompiler::optimize(), v8::internal::RegExpCompiler::set_limiting_recursion(), and trace_count_.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::TextNode::Emit(), v8::internal::BackReferenceNode::Emit(), and v8::internal::ChoiceNode::Emit().
on_work_list()
bool v8::internal::RegExpNode::on_work_list () [inline]
Definition at line 244 of file regexp-nodes.h.
{ return on_work_list_; }
References on_work_list_.
Referenced by v8::internal::RegExpCompiler::AddWork(), and LimitVersions().
replacement()
RegExpNode* v8::internal::RegExpNode::replacement () [inline]
Definition at line 218 of file regexp-nodes.h.
                            {
    DCHECK(info()->replacement_calculated);
    return replacement_;
  }
References v8::internal::DCHECK(), info(), and replacement_.
Referenced by v8::internal::SeqRegExpNode::FilterOneByte(), v8::internal::TextNode::FilterOneByte(), v8::internal::ChoiceNode::FilterOneByte(), v8::internal::NegativeLookaroundChoiceNode::FilterOneByte(), v8::internal::LoopChoiceNode::FilterOneByte(), and set_replacement().
SaveBMInfo()
void v8::internal::RegExpNode::SaveBMInfo (BoyerMooreLookahead * bm, bool not_at_start, int offset) [inline]
Definition at line 232 of file regexp-nodes.h.
                                                                          {
    if (offset == 0) set_bm_info(not_at_start, bm);
  }
References set_bm_info().
Referenced by v8::internal::ActionNode::FillInBMInfo(), v8::internal::AssertionNode::FillInBMInfo(), v8::internal::BackReferenceNode::FillInBMInfo(), v8::internal::ChoiceNode::FillInBMInfo(), and v8::internal::LoopChoiceNode::FillInBMInfo().
set_bm_info()
void v8::internal::RegExpNode::set_bm_info (bool not_at_start, BoyerMooreLookahead * bm) [inline], [protected]
Definition at line 281 of file regexp-nodes.h.
                                                               {
    bm_info_[not_at_start ? 1 : 0] = bm;
  }
References bm_info_.
Referenced by v8::internal::SeqRegExpNode::FillInBMInfo(), v8::internal::TextNode::FillInBMInfo(), and SaveBMInfo().
set_eats_at_least_info()
void v8::internal::RegExpNode::set_eats_at_least_info (const EatsAtLeastInfo & eats_at_least) [inline]
Definition at line 249 of file regexp-nodes.h.
                                                                    {
    eats_at_least_ = eats_at_least;
  }
References eats_at_least_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAction(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAssertion(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitBackReference(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitChoice(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitLoopChoiceContinueNode(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitNegativeLookaroundChoiceContinueNode(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitText().
set_on_work_list()
void v8::internal::RegExpNode::set_on_work_list (bool value) [inline]
Definition at line 245 of file regexp-nodes.h.
{ on_work_list_ = value; }
References on_work_list_, and v8::internal::value.
Referenced by v8::internal::RegExpCompiler::AddWork(), and v8::internal::RegExpCompiler::Assemble().
set_replacement()
RegExpNode* v8::internal::RegExpNode::set_replacement (RegExpNode * replacement) [inline]
Definition at line 222 of file regexp-nodes.h.
                                                       {
    info()->replacement_calculated = true;
    replacement_ = replacement;
    return replacement; // For convenience.
  }
References info(), replacement(), replacement_, and v8::internal::NodeInfo::replacement_calculated.
Referenced by v8::internal::TextNode::FilterOneByte(), v8::internal::ChoiceNode::FilterOneByte(), v8::internal::NegativeLookaroundChoiceNode::FilterOneByte(), v8::internal::LoopChoiceNode::FilterOneByte(), and v8::internal::SeqRegExpNode::FilterSuccessor().
SetDoNotInline()
void v8::internal::RegExpNode::SetDoNotInline () [inline]
Definition at line 260 of file regexp-nodes.h.
{ trace_count_ = kMaxCopiesCodeGenerated; }
References kMaxCopiesCodeGenerated, and trace_count_.
zone()
Zone* v8::internal::RegExpNode::zone () const [inline]
Definition at line 273 of file regexp-nodes.h.
{ return zone_; }
References zone_.
Referenced by v8::internal::ChoiceNode::AddAlternative(), v8::internal::AssertionNode::AfterNewline(), v8::internal::AssertionNode::AtBoundary(), v8::internal::AssertionNode::AtEnd(), v8::internal::AssertionNode::AtNonBoundary(), v8::internal::AssertionNode::AtStart(), v8::internal::ActionNode::BeginNegativeSubmatch(), v8::internal::ActionNode::BeginPositiveSubmatch(), v8::internal::RegExpLookaround::Builder::Builder(), v8::internal::ActionNode::ClearCaptures(), v8::internal::ActionNode::ClearPosition(), v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::TextNode::CreateForSurrogatePair(), v8::internal::ChoiceNode::Emit(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch(), v8::internal::ActionNode::EmptyMatchCheck(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::ChoiceNode::FilterOneByte(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::ActionNode::IncrementRegister(), v8::internal::TextNode::MakeCaseIndependent(), v8::internal::ActionNode::ModifyFlags(), v8::internal::ActionNode::PositiveSubmatchSuccess(), v8::internal::ActionNode::RestorePosition(), v8::internal::ActionNode::SetRegisterForLoop(), v8::internal::TextNode::TextEmitPass(), and v8::internal::TextNode::TextNode().
Member Data Documentation
bm_info_
BoyerMooreLookahead* v8::internal::RegExpNode::bm_info_[2] [private]
Definition at line 301 of file regexp-nodes.h.
Referenced by bm_info(), RegExpNode(), and set_bm_info().
eats_at_least_
EatsAtLeastInfo v8::internal::RegExpNode::eats_at_least_ [private]
Definition at line 293 of file regexp-nodes.h.
Referenced by eats_at_least_info(), EatsAtLeast(), and set_eats_at_least_info().
info_
NodeInfo v8::internal::RegExpNode::info_ [private]
Definition at line 289 of file regexp-nodes.h.
Referenced by info().
kFirstCharBudget
const int v8::internal::RegExpNode::kFirstCharBudget = 10 [static], [private]
Definition at line 286 of file regexp-nodes.h.
kMaxCopiesCodeGenerated
const int v8::internal::RegExpNode::kMaxCopiesCodeGenerated = 10 [static]
Definition at line 242 of file regexp-nodes.h.
Referenced by LimitVersions(), and SetDoNotInline().
kNodeIsTooComplexForFixedLengthLoops
const int v8::internal::RegExpNode::kNodeIsTooComplexForFixedLengthLoops = kMinInt [static]
Definition at line 188 of file regexp-nodes.h.
Referenced by v8::internal::ChoiceNode::Emit(), v8::internal::LoopChoiceNode::Emit(), FixedLengthLoopLength(), v8::internal::ActionNode::FixedLengthLoopLength(), and v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative().
kRecursionBudget
const int v8::internal::RegExpNode::kRecursionBudget = 200 [static]
Definition at line 204 of file regexp-nodes.h.
Referenced by v8::internal::AssertionNode::EmitBoundaryCheck(), and v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch().
label_
Label v8::internal::RegExpNode::label_ [private]
Definition at line 287 of file regexp-nodes.h.
Referenced by label(), and LimitVersions().
on_work_list_
bool v8::internal::RegExpNode::on_work_list_ [private]
Definition at line 288 of file regexp-nodes.h.
Referenced by on_work_list(), and set_on_work_list().
replacement_
RegExpNode* v8::internal::RegExpNode::replacement_ [protected]
Definition at line 277 of file regexp-nodes.h.
Referenced by replacement(), and set_replacement().
trace_count_
int v8::internal::RegExpNode::trace_count_ [private]
Definition at line 300 of file regexp-nodes.h.
Referenced by LimitVersions(), and SetDoNotInline().
zone_
Zone* v8::internal::RegExpNode::zone_ [private]
Definition at line 303 of file regexp-nodes.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc