v8::internal::compiler::StartNode Class Reference
#include <common-operator.h>
Public Member Functions
constexpr StartNode (Node *node)
int FormalParameterCount () const
int FormalParameterCountWithoutReceiver () const
int NewTargetParameterIndex () const
int ArgCountParameterIndex () const
int ContextParameterIndex () const
int ContextParameterIndex_MaybeNonStandardLayout () const
int LastParameterIndex_MaybeNonStandardLayout () const
int NewTargetOutputIndex () const
int ArgCountOutputIndex () const
int ContextOutputIndex () const
int LastOutputIndex () const
Static Public Member Functions
static constexpr int OutputArityForFormalParameterCount (int argc)
Static Public Attributes
static constexpr int kReceiverOutputCount = 1
static constexpr int kExtraOutputCount
Additional Inherited Members
Detailed Description
Definition at line 764 of file common-operator.h.
Constructor & Destructor Documentation
StartNode()
constexpr v8::internal::compiler::StartNode::StartNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 766 of file common-operator.h.
                                           : CommonNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kStart, node->opcode());
  }
References DCHECK_EQ, v8::kStart, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
ArgCountOutputIndex()
int v8::internal::compiler::StartNode::ArgCountOutputIndex () const [inline]
Definition at line 861 of file common-operator.h.
                                  {
    // Indices assigned to parameters are off-by-one (Parameters indices start
    // at -1). TODO(jgruber): Consider starting at 0.
    return Linkage::GetJSCallArgCountParamIndex(FormalParameterCount()) + 1;
  }
References FormalParameterCount(), and v8::internal::compiler::Linkage::GetJSCallArgCountParamIndex().
Referenced by v8::internal::compiler::JSInliner::InlineCall().
ArgCountParameterIndex()
int v8::internal::compiler::StartNode::ArgCountParameterIndex () const [inline]
Definition at line 822 of file common-operator.h.
                                     {
    return Linkage::GetJSCallArgCountParamIndex(FormalParameterCount());
  }
References FormalParameterCount(), and v8::internal::compiler::Linkage::GetJSCallArgCountParamIndex().
ContextOutputIndex()
int v8::internal::compiler::StartNode::ContextOutputIndex () const [inline]
Definition at line 866 of file common-operator.h.
                                 {
    // Indices assigned to parameters are off-by-one (Parameters indices start
    // at -1). TODO(jgruber): Consider starting at 0.
    return Linkage::GetJSCallContextParamIndex(FormalParameterCount()) + 1;
  }
References FormalParameterCount(), and v8::internal::compiler::Linkage::GetJSCallContextParamIndex().
Referenced by v8::internal::compiler::JSInliner::InlineCall(), and LastOutputIndex().
ContextParameterIndex()
int v8::internal::compiler::StartNode::ContextParameterIndex () const [inline]
Definition at line 830 of file common-operator.h.
                                    {
    return Linkage::GetJSCallContextParamIndex(FormalParameterCount());
  }
References FormalParameterCount(), and v8::internal::compiler::Linkage::GetJSCallContextParamIndex().
ContextParameterIndex_MaybeNonStandardLayout()
int v8::internal::compiler::StartNode::ContextParameterIndex_MaybeNonStandardLayout () const [inline]
Definition at line 839 of file common-operator.h.
                                                           {
    // The context is always the last parameter to a JavaScript function, and
    // {Parameter} indices start at -1, so value outputs of {Start} look like
    // this: closure, receiver, param0, ..., paramN, context.
    //
    // TODO(jgruber): This function is called from spots that operate on
    // CSA/Torque graphs; Start node layout appears to be different there.
    // These should be unified to avoid confusion. Once done, enable this
    // DCHECK: DCHECK_EQ(LastOutputIndex(), ContextOutputIndex());
    return node()->op()->ValueOutputCount() - 2;
  }
References v8::internal::compiler::NodeWrapper::node(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueOutputCount().
Referenced by LastParameterIndex_MaybeNonStandardLayout().
FormalParameterCount()
int v8::internal::compiler::StartNode::FormalParameterCount () const [inline]
Definition at line 803 of file common-operator.h.
                                   {
    DCHECK_GE(node()->op()->ValueOutputCount(),
              kExtraOutputCount + kReceiverOutputCount);
    return node()->op()->ValueOutputCount() - kExtraOutputCount;
  }
References DCHECK_GE, kExtraOutputCount, kReceiverOutputCount, v8::internal::compiler::NodeWrapper::node(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueOutputCount().
Referenced by ArgCountOutputIndex(), ArgCountParameterIndex(), ContextOutputIndex(), ContextParameterIndex(), NewTargetOutputIndex(), NewTargetParameterIndex(), and v8::internal::compiler::GraphBuilderPhase::Run().
FormalParameterCountWithoutReceiver()
int v8::internal::compiler::StartNode::FormalParameterCountWithoutReceiver () const [inline]
Definition at line 809 of file common-operator.h.
                                                  {
    DCHECK_GE(node()->op()->ValueOutputCount(),
              kExtraOutputCount + kReceiverOutputCount);
    return node()->op()->ValueOutputCount() - kExtraOutputCount -
           kReceiverOutputCount;
  }
References DCHECK_GE, kExtraOutputCount, kReceiverOutputCount, v8::internal::compiler::NodeWrapper::node(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueOutputCount().
LastOutputIndex()
int v8::internal::compiler::StartNode::LastOutputIndex () const [inline]
Definition at line 871 of file common-operator.h.
{ return ContextOutputIndex(); }
References ContextOutputIndex().
LastParameterIndex_MaybeNonStandardLayout()
int v8::internal::compiler::StartNode::LastParameterIndex_MaybeNonStandardLayout () const [inline]
Definition at line 850 of file common-operator.h.
                                                        {
    return ContextParameterIndex_MaybeNonStandardLayout();
  }
References ContextParameterIndex_MaybeNonStandardLayout().
NewTargetOutputIndex()
int v8::internal::compiler::StartNode::NewTargetOutputIndex () const [inline]
Definition at line 856 of file common-operator.h.
                                   {
    // Indices assigned to parameters are off-by-one (Parameters indices start
    // at -1). TODO(jgruber): Consider starting at 0.
    return Linkage::GetJSCallNewTargetParamIndex(FormalParameterCount()) + 1;
  }
References FormalParameterCount(), and v8::internal::compiler::Linkage::GetJSCallNewTargetParamIndex().
Referenced by v8::internal::compiler::JSInliner::InlineCall().
NewTargetParameterIndex()
int v8::internal::compiler::StartNode::NewTargetParameterIndex () const [inline]
Definition at line 819 of file common-operator.h.
                                      {
    return Linkage::GetJSCallNewTargetParamIndex(FormalParameterCount());
  }
References FormalParameterCount(), and v8::internal::compiler::Linkage::GetJSCallNewTargetParamIndex().
OutputArityForFormalParameterCount()
static constexpr int v8::internal::compiler::StartNode::OutputArityForFormalParameterCount (int argc) [inline], [static], [constexpr]
Definition at line 778 of file common-operator.h.
                                                                    {
    constexpr int kClosure = 1;
    constexpr int kNewTarget = 1;
    constexpr int kArgCount = 1;
    constexpr int kDispatchHandle =
        V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL ? 1 : 0;
    constexpr int kContext = 1;
    static_assert(kClosure + kNewTarget + kArgCount + kDispatchHandle +
                      kContext ==
                  kExtraOutputCount);
    // Checking related linkage methods here since they rely on Start node
    // layout.
    DCHECK_EQ(-1, Linkage::kJSCallClosureParamIndex);
    DCHECK_EQ(argc + 0, Linkage::GetJSCallNewTargetParamIndex(argc));
    DCHECK_EQ(argc + 1, Linkage::GetJSCallArgCountParamIndex(argc));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
    DCHECK_EQ(argc + 2, Linkage::GetJSCallDispatchHandleParamIndex(argc));
    DCHECK_EQ(argc + 3, Linkage::GetJSCallContextParamIndex(argc));
#else
    DCHECK_EQ(argc + 2, Linkage::GetJSCallContextParamIndex(argc));
#endif
    return argc + kClosure + kNewTarget + kArgCount + kDispatchHandle +
           kContext;
  }
References DCHECK_EQ, v8::internal::compiler::Linkage::GetJSCallArgCountParamIndex(), v8::internal::compiler::Linkage::GetJSCallContextParamIndex(), v8::internal::compiler::Linkage::GetJSCallNewTargetParamIndex(), kExtraOutputCount, v8::internal::compiler::Linkage::kJSCallClosureParamIndex, and V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::CreateGraph().
Member Data Documentation
kExtraOutputCount
constexpr int v8::internal::compiler::StartNode::kExtraOutputCount [static], [constexpr]
Initial value:
=
      4 + V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL
Definition at line 773 of file common-operator.h.
Referenced by FormalParameterCount(), FormalParameterCountWithoutReceiver(), and OutputArityForFormalParameterCount().
kReceiverOutputCount
constexpr int v8::internal::compiler::StartNode::kReceiverOutputCount = 1 [static], [constexpr]
Definition at line 771 of file common-operator.h.
Referenced by FormalParameterCount(), and FormalParameterCountWithoutReceiver().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h