v8::internal::Handle< T > Class Template Reference
#include <handles.h>
Classes
struct equal_to
struct hash
Public Types
using MaybeType = MaybeHandle< T >
Public Member Functions
Handle ()
Handle (Address *location)
Handle (Tagged< T > object, Isolate *isolate)
Handle (Tagged< T > object, LocalIsolate *isolate)
Handle (Tagged< T > object, LocalHeap *local_heap)
template<typename S >
Handle (Handle< S > handle) requires(is_subtype_v< S
Tagged< T > operator* () const
bool equals (Handle< T > other) const
void PatchValue (Tagged< T > new_value)
Static Public Member Functions
static Handle< T > New (Tagged< T > object, Isolate *isolate)
static const Handle< T > null ()
Public Attributes
T __pad0__: HandleBase(handle) {} inline Tagged<T> operator->() const { static_assert(is_subtype_v<T
T HeapObject
T This handle does not reference a heap object Use handle foo
return ** this
Friends
template<typename >
class Handle
template<typename >
class MaybeHandle
template<typename To , typename From >
IndirectHandle< To > UncheckedCast (IndirectHandle< From > value)
Additional Inherited Members
Detailed Description
template<typename T>
class v8::internal::Handle< T >
Definition at line 150 of file handles.h.
Member Typedef Documentation
MaybeType
template<typename T >
using v8::internal::Handle< T >::MaybeType = MaybeHandle<T>
Definition at line 233 of file handles.h.
Constructor & Destructor Documentation
Handle() [1/6]
template<typename T >
v8::internal::Handle< T >::Handle () [inline]
Definition at line 155 of file handles.h.
: HandleBase(nullptr) {}
Handle() [2/6]
template<typename T >
v8::internal::Handle< T >::Handle (Address * location) [inline], [explicit]
Definition at line 157 of file handles.h.
                                               : HandleBase(location) {
    // TODO(jkummerow): Runtime type check here as a SLOW_DCHECK?
  }
Handle() [3/6]
template<typename T >
v8::internal::Handle< T >::Handle (Tagged< T > object, Isolate * isolate) [inline]
Definition at line 60 of file handles-inl.h.
    : HandleBase(object.ptr(), isolate) {}
Handle() [4/6]
template<typename T >
v8::internal::Handle< T >::Handle (Tagged< T > object, LocalIsolate * isolate) [inline]
Definition at line 64 of file handles-inl.h.
    : HandleBase(object.ptr(), isolate) {}
Handle() [5/6]
template<typename T >
v8::internal::Handle< T >::Handle (Tagged< T > object, LocalHeap * local_heap) [inline]
Definition at line 68 of file handles-inl.h.
    : HandleBase(object.ptr(), local_heap) {}
Handle() [6/6]
template<typename T >
template<typename S >
v8::internal::Handle< T >::Handle (Handle< S > handle) [inline]
Member Function Documentation
equals()
template<typename T >
bool v8::internal::Handle< T >::equals (Handle< T > other) const [inline]
Definition at line 210 of file handles.h.
{ return address() == other.address(); }
References v8::internal::HandleBase::address().
Referenced by v8::internal::Handle< T >::equal_to::operator()(), and v8::internal::compiler::JSInliningHeuristic::Reduce().
New()
template<typename T >
Handle< T > v8::internal::Handle< T >::New (Tagged< T > object, Isolate * isolate) [inline], [static]
Definition at line 46 of file handles-inl.h.
                                                           {
  return Handle(HandleScope::CreateHandle(isolate, object.ptr()));
}
References v8::internal::HandleScope::CreateHandle().
Referenced by v8::internal::compiler::turboshaft::detail::CreateCountersArray(), v8::internal::AllocationSiteContext::InitializeTraversal(), and v8::internal::MacroAssemblerBase::MacroAssemblerBase().
null()
template<typename T >
static const Handle<T> v8::internal::Handle< T >::null () [inline], [static]
Definition at line 207 of file handles.h.
{ return Handle<T>(); }
Referenced by v8::internal::PendingCompilationErrorHandler::MessageDetails::ArgString(), v8::internal::IC::ConfigureVectorState(), v8::internal::Scope::DeserializeScopeChain(), v8::internal::wasm::FrameState::DisposeCaughtExceptionsArray(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::TransitionsAccessor::ExpectedTransition(), v8::internal::MaterializedObjectStore::Get(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetFirstWasmInstance(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmInstance(), v8::internal::Factory::GlobalConstantFor(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::Context::Lookup(), v8::internal::CallOptimization::LookupHolderOfExpectedType(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Debug::StopSideEffectCheckMode(), v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::baseline::BaselineBatchCompiler::~BaselineBatchCompiler().
operator*()
template<typename T >
Tagged<T> v8::internal::Handle< T >::operator* () const [inline]
Definition at line 193 of file handles.h.
                                        {
    // This static type check also fails for forward class declarations. We
    // check on access instead of on construction to allow Handles to forward
    // declared types.
    static_assert(is_taggable_v<T>, "static type violation");
    // Direct construction of Tagged from address, without a type check, because
    // we rather trust Handle<T> to contain a T than include all the respective
    // -inl.h headers for SLOW_DCHECKs.
    SLOW_DCHECK(IsDereferenceAllowed());
    return Tagged<T>(*location());
  }
References v8::internal::HandleBase::IsDereferenceAllowed(), v8::internal::HandleBase::location(), and SLOW_DCHECK.
PatchValue()
template<typename T >
void v8::internal::Handle< T >::PatchValue (Tagged< T > new_value) [inline]
Definition at line 214 of file handles.h.
                                       {
    SLOW_DCHECK(location_ != nullptr && IsDereferenceAllowed());
    *location_ = new_value.ptr();
  }
References v8::internal::HandleBase::IsDereferenceAllowed(), v8::internal::HandleBase::location_, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and SLOW_DCHECK.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty(), v8::internal::Factory::CodeBuilder::BuildInternal(), and v8::internal::Deserializer< IsolateT >::PostProcessNewObject().
Friends And Related Function Documentation
Handle
template<typename T >
template<typename >
friend class Handle [friend]
Definition at line 238 of file handles.h.
MaybeHandle
template<typename T >
template<typename >
friend class MaybeHandle [friend]
Definition at line 241 of file handles.h.
UncheckedCast
template<typename T >
template<typename To , typename From >
IndirectHandle<To> UncheckedCast (IndirectHandle< From > value) [friend]
Member Data Documentation
__pad0__
template<typename T >
T v8::internal::Handle< T >::__pad0__
Definition at line 172 of file handles.h.
foo
template<typename T >
T This handle does not reference a heap object Use handle v8::internal::Handle< T >::foo
Definition at line 189 of file handles.h.
HeapObject
template<typename T >
T v8::internal::Handle< T >::HeapObject
Definition at line 188 of file handles.h.
this
template<typename T >
return** v8::internal::Handle< T >::this
Definition at line 190 of file handles.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/globals.h
/mnt/V8SourceCode/src/handles/handles.h
/mnt/V8SourceCode/src/handles/handles-inl.h