v8::internal::PreParserFormalParameters Class Reference
#include <preparser.h>
Public Member Functions
PreParserFormalParameters (DeclarationScope *scope)
void set_has_duplicate ()
bool has_duplicate ()
void ValidateDuplicate (PreParser *preparser) const
void set_strict_parameter_error (const Scanner::Location &loc, MessageTemplate message)
void ValidateStrictMode (PreParser *preparser) const
Private Attributes
bool has_duplicate_ = false
bool strict_parameter_error_ = false
Additional Inherited Members
Detailed Description
Definition at line 745 of file preparser.h.
Constructor & Destructor Documentation
PreParserFormalParameters()
v8::internal::PreParserFormalParameters::PreParserFormalParameters (DeclarationScope * scope) [inline], [explicit]
Definition at line 747 of file preparser.h.
      : FormalParametersBase(scope) {}
Member Function Documentation
has_duplicate()
bool v8::internal::PreParserFormalParameters::has_duplicate () [inline]
Definition at line 751 of file preparser.h.
{ return has_duplicate_; }
References has_duplicate_.
set_has_duplicate()
void v8::internal::PreParserFormalParameters::set_has_duplicate () [inline]
Definition at line 750 of file preparser.h.
{ has_duplicate_ = true; }
References has_duplicate_.
Referenced by v8::internal::PreParser::ParseFunctionLiteral(), and v8::internal::PreParser::PreParseFunction().
set_strict_parameter_error()
void v8::internal::PreParserFormalParameters::set_strict_parameter_error (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 754 of file preparser.h.
                                                           {
    strict_parameter_error_ = loc.IsValid();
  }
References v8::internal::loc, and strict_parameter_error_.
ValidateDuplicate()
void v8::internal::PreParserFormalParameters::ValidateDuplicate (PreParser * preparser) const
Definition at line 93 of file preparser.cc.
                                                                            {
  if (has_duplicate_) preparser->ReportUnidentifiableError();
}
References has_duplicate_, and v8::internal::PreParser::ReportUnidentifiableError().
ValidateStrictMode()
void v8::internal::PreParserFormalParameters::ValidateStrictMode (PreParser * preparser) const
Definition at line 97 of file preparser.cc.
                                                                             {
  if (strict_parameter_error_) preparser->ReportUnidentifiableError();
}
References v8::internal::PreParser::ReportUnidentifiableError(), and strict_parameter_error_.
Member Data Documentation
has_duplicate_
bool v8::internal::PreParserFormalParameters::has_duplicate_ = false [private]
Definition at line 761 of file preparser.h.
Referenced by has_duplicate(), set_has_duplicate(), and ValidateDuplicate().
strict_parameter_error_
bool v8::internal::PreParserFormalParameters::strict_parameter_error_ = false [private]
Definition at line 762 of file preparser.h.
Referenced by set_strict_parameter_error(), and ValidateStrictMode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparser.h
/mnt/V8SourceCode/src/parsing/preparser.cc