v8::internal::compiler::JSProxyRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< JSProxy > object () const
bool is_revocable () const
OptionalObjectRef GetTarget (JSHeapBroker *broker) const
OptionalObjectRef GetHandler (JSHeapBroker *broker) const
Detailed Description
Definition at line 571 of file heap-refs.h.
Member Function Documentation
GetHandler()
OptionalObjectRef v8::internal::compiler::JSProxyRef::GetHandler (JSHeapBroker * broker) const
Definition at line 2064 of file heap-refs.cc.
                                                                   {
  return TryMakeRef(broker, object()->handler());
}
References broker(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo().
GetTarget()
OptionalObjectRef v8::internal::compiler::JSProxyRef::GetTarget (JSHeapBroker * broker) const
Definition at line 2061 of file heap-refs.cc.
                                                                  {
  return TryMakeRef(broker, object()->target());
}
References broker(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo().
is_revocable()
bool v8::internal::compiler::JSProxyRef::is_revocable () const
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo().
object()
IndirectHandle<JSProxy> v8::internal::compiler::JSProxyRef::object () const
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc