v8::internal::maglev::IntPtrConstant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = Register
Public Member Functions
IntPtrConstant (uint64_t bitfield, intptr_t value)
intptr_t value () const
bool ToBoolean (LocalIsolate *local_isolate) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
DirectHandle< Object > DoReify (LocalIsolate *isolate) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::IntPtr()
Private Types
using Base = FixedInputValueNodeT< 0, IntPtrConstant >
Private Attributes
const intptr_t value_
Additional Inherited Members
Detailed Description
Definition at line 3927 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::IntPtrConstant::Base = FixedInputValueNodeT<0, IntPtrConstant> [private]
Definition at line 3928 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::IntPtrConstant::OutputRegister = Register
Definition at line 3931 of file maglev-ir.h.
Constructor & Destructor Documentation
IntPtrConstant()
v8::internal::maglev::IntPtrConstant::IntPtrConstant (uint64_t bitfield, intptr_t value) [inline], [explicit]
Definition at line 3933 of file maglev-ir.h.
      : Base(bitfield), value_(value) {}
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::IntPtrConstant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
DirectHandle< Object > v8::internal::maglev::IntPtrConstant::DoReify (LocalIsolate * isolate) const
Definition at line 1223 of file maglev-ir.cc.
                                                                        {
  return isolate->factory()->NewNumberFromInt64<AllocationType::kOld>(value());
}
References v8::internal::LocalIsolate::factory(), v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewNumberFromInt64(), and value().
GenerateCode()
void v8::internal::maglev::IntPtrConstant::GenerateCode (MaglevAssembler * , const ProcessingState &)
PrintParams()
void v8::internal::maglev::IntPtrConstant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7904 of file maglev-ir.cc.
                                                                            {
  os << "(" << value() << ")";
}
References value().
SetValueLocationConstraints()
void v8::internal::maglev::IntPtrConstant::SetValueLocationConstraints ()
ToBoolean()
bool v8::internal::maglev::IntPtrConstant::ToBoolean (LocalIsolate * local_isolate) const [inline]
Definition at line 3940 of file maglev-ir.h.
{ return value_ != 0; }
References value_.
value()
intptr_t v8::internal::maglev::IntPtrConstant::value () const [inline]
Definition at line 3938 of file maglev-ir.h.
{ return value_; }
References value_.
Referenced by DoReify(), PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kProperties
constexpr OpProperties v8::internal::maglev::IntPtrConstant::kProperties = OpProperties::IntPtr() [static], [constexpr]
Definition at line 3936 of file maglev-ir.h.
value_
const intptr_t v8::internal::maglev::IntPtrConstant::value_ [private]
Definition at line 3950 of file maglev-ir.h.
Referenced by ToBoolean(), and value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc