v8::internal::LazyCompileDispatcher Class Reference
#include <lazy-compile-dispatcher.h>
Classes
struct Job
class JobTask
Public Types
using JobId = uintptr_t
Public Member Functions
LazyCompileDispatcher (Isolate *isolate, Platform *platform, size_t max_stack_size)
LazyCompileDispatcher (const LazyCompileDispatcher &)=delete
LazyCompileDispatcher & operator= (const LazyCompileDispatcher &)=delete
~LazyCompileDispatcher ()
void Enqueue (LocalIsolate *isolate, Handle< SharedFunctionInfo > shared_info, std::unique_ptr< Utf16CharacterStream > character_stream)
bool IsEnqueued (DirectHandle< SharedFunctionInfo > function) const
bool FinishNow (DirectHandle< SharedFunctionInfo > function)
void AbortJob (DirectHandle< SharedFunctionInfo > function)
void AbortAll ()
Private Types
using SharedToJobMap = IdentityMap< Job *, FreeStoreAllocationPolicy >
Private Member Functions
FRIEND_TEST (LazyCompileDispatcherTest, IdleTaskNoIdleTime)
FRIEND_TEST (LazyCompileDispatcherTest, IdleTaskSmallIdleTime)
FRIEND_TEST (LazyCompileDispatcherTest, FinishNowWithWorkerTask)
FRIEND_TEST (LazyCompileDispatcherTest, AbortJobNotStarted)
FRIEND_TEST (LazyCompileDispatcherTest, AbortJobAlreadyStarted)
FRIEND_TEST (LazyCompileDispatcherTest, AsyncAbortAllPendingWorkerTask)
FRIEND_TEST (LazyCompileDispatcherTest, AsyncAbortAllRunningWorkerTask)
FRIEND_TEST (LazyCompileDispatcherTest, CompileMultipleOnBackgroundThread)
void WaitForJobIfRunningOnBackground (Job *job, const base::MutexGuard &)
Job * GetJobFor (DirectHandle< SharedFunctionInfo > shared, const base::MutexGuard &) const
Job * PopSingleFinalizeJob ()
void ScheduleIdleTaskFromAnyThread (const base::MutexGuard &)
bool FinalizeSingleJob ()
void DoBackgroundWork (JobDelegate *delegate)
void DoIdleWork (double deadline_in_seconds)
void DeleteJob (Job *job)
void DeleteJob (Job *job, const base::MutexGuard &)
void NotifyAddedBackgroundJob (const base::MutexGuard &lock)
void NotifyRemovedBackgroundJob (const base::MutexGuard &lock)
void VerifyBackgroundTaskCount (const base::MutexGuard &)
Private Attributes
Isolate * isolate_
WorkerThreadRuntimeCallStats * worker_thread_runtime_call_stats_
TimedHistogram * background_compile_timer_
std::shared_ptr< TaskRunner > taskrunner_
Platform * platform_
size_t max_stack_size_
std::unique_ptr< JobHandle > job_handle_
bool trace_compiler_dispatcher_
std::unique_ptr< CancelableTaskManager > idle_task_manager_
base::Mutex mutex_
bool idle_task_scheduled_
std::vector< Job * > pending_background_jobs_
std::vector< Job * > finalizable_jobs_
std::atomic< size_t > num_jobs_for_background_
std::vector< Job * > jobs_to_dispose_
Job * main_thread_blocking_on_job_
base::ConditionVariable main_thread_blocking_signal_
base::AtomicValue< bool > block_for_testing_
base::Semaphore semaphore_for_testing_
Detailed Description
Definition at line 75 of file lazy-compile-dispatcher.h.
Member Typedef Documentation
JobId
using v8::internal::LazyCompileDispatcher::JobId = uintptr_t
Definition at line 77 of file lazy-compile-dispatcher.h.
SharedToJobMap
using v8::internal::LazyCompileDispatcher::SharedToJobMap = IdentityMap<Job*, FreeStoreAllocationPolicy> [private]
Definition at line 152 of file lazy-compile-dispatcher.h.
Constructor & Destructor Documentation
LazyCompileDispatcher() [1/2]
v8::internal::LazyCompileDispatcher::LazyCompileDispatcher (Isolate * isolate, Platform * platform, size_t max_stack_size)
Definition at line 61 of file lazy-compile-dispatcher.cc.
    : isolate_(isolate),
      worker_thread_runtime_call_stats_(
          isolate->counters()->worker_thread_runtime_call_stats()),
      background_compile_timer_(
          isolate->counters()->compile_function_on_background()),
      taskrunner_(platform->GetForegroundTaskRunner(
          reinterpret_cast<v8::Isolate*>(isolate))),
      platform_(platform),
      max_stack_size_(max_stack_size),
      trace_compiler_dispatcher_(v8_flags.trace_compiler_dispatcher),
      idle_task_manager_(new CancelableTaskManager()),
      idle_task_scheduled_(false),
      num_jobs_for_background_(0),
      main_thread_blocking_on_job_(nullptr),
      block_for_testing_(false),
      semaphore_for_testing_(0) {
  job_handle_ = platform_->PostJob(TaskPriority::kUserVisible,
                                   std::make_unique<JobTask>(this));
}
References job_handle_, v8::kUserVisible, platform_, and v8::Platform::PostJob().
LazyCompileDispatcher() [2/2]
v8::internal::LazyCompileDispatcher::LazyCompileDispatcher (const LazyCompileDispatcher &) [delete]
 LazyCompileDispatcher()
v8::internal::LazyCompileDispatcher::~LazyCompileDispatcher ()
Definition at line 84 of file lazy-compile-dispatcher.cc.
                                              {
  // AbortAll must be called before LazyCompileDispatcher is destroyed.
  CHECK(!job_handle_->IsValid());
}
References CHECK, and job_handle_.
Member Function Documentation
AbortAll()
void v8::internal::LazyCompileDispatcher::AbortAll ()
Definition at line 350 of file lazy-compile-dispatcher.cc.
                                     {
  idle_task_manager_->TryAbortAll();
  job_handle_->Cancel();
  {
    base::MutexGuard lock(&mutex_);
    for (Job* job : pending_background_jobs_) {
      job->task->AbortFunction();
      job->state = Job::State::kFinalized;
      DeleteJob(job, lock);
    }
    pending_background_jobs_.clear();
    for (Job* job : finalizable_jobs_) {
      job->task->AbortFunction();
      job->state = Job::State::kFinalized;
      DeleteJob(job, lock);
    }
    finalizable_jobs_.clear();
    for (Job* job : jobs_to_dispose_) {
      delete job;
    }
    jobs_to_dispose_.clear();
    DCHECK_EQ(all_jobs_.size(), 0);
    num_jobs_for_background_ = 0;
    VerifyBackgroundTaskCount(lock);
  }
  idle_task_manager_->CancelAndWait();
}
References DCHECK_EQ, DeleteJob(), finalizable_jobs_, idle_task_manager_, job_handle_, jobs_to_dispose_, v8::internal::LazyCompileDispatcher::Job::kFinalized, mutex_, num_jobs_for_background_, pending_background_jobs_, and VerifyBackgroundTaskCount().
AbortJob()
void v8::internal::LazyCompileDispatcher::AbortJob (DirectHandle< SharedFunctionInfo > function)
Definition at line 306 of file lazy-compile-dispatcher.cc.
                                                  {
  if (trace_compiler_dispatcher_) {
    PrintF("LazyCompileDispatcher: aborting job for ");
    ShortPrint(*shared_info);
    PrintF("\n");
  }
  base::LockGuard<base::Mutex> lock(&mutex_);
  Job* job = GetJobFor(shared_info, lock);
  if (job->is_running_on_background()) {
    // Job is currently running on the background thread, wait until it's done
    // and remove job then.
    job->state = Job::State::kAbortRequested;
  } else {
    if (job->state == Job::State::kPending) {
      DCHECK_EQ(std::count(pending_background_jobs_.begin(),
                           pending_background_jobs_.end(), job),
                1);
      pending_background_jobs_.erase(
          std::remove(pending_background_jobs_.begin(),
                      pending_background_jobs_.end(), job),
          pending_background_jobs_.end());
      job->state = Job::State::kAbortingNow;
      NotifyRemovedBackgroundJob(lock);
    } else if (job->state == Job::State::kReadyToFinalize) {
      DCHECK_EQ(
          std::count(finalizable_jobs_.begin(), finalizable_jobs_.end(), job),
          1);
      finalizable_jobs_.erase(
          std::remove(finalizable_jobs_.begin(), finalizable_jobs_.end(), job),
          finalizable_jobs_.end());
      job->state = Job::State::kAbortingNow;
    } else {
      UNREACHABLE();
    }
    job->task->AbortFunction();
    job->state = Job::State::kFinalized;
    DeleteJob(job, lock);
  }
}
References DCHECK_EQ, DeleteJob(), finalizable_jobs_, GetJobFor(), v8::internal::LazyCompileDispatcher::Job::is_running_on_background(), v8::internal::LazyCompileDispatcher::Job::kAbortingNow, v8::internal::LazyCompileDispatcher::Job::kAbortRequested, v8::internal::LazyCompileDispatcher::Job::kFinalized, v8::internal::LazyCompileDispatcher::Job::kPending, v8::internal::LazyCompileDispatcher::Job::kReadyToFinalize, mutex_, NotifyRemovedBackgroundJob(), pending_background_jobs_, v8::internal::PrintF(), v8::internal::ShortPrint(), v8::internal::LazyCompileDispatcher::Job::state, v8::internal::LazyCompileDispatcher::Job::task, trace_compiler_dispatcher_, and v8::internal::UNREACHABLE().
DeleteJob() [1/2]
void v8::internal::LazyCompileDispatcher::DeleteJob (Job * job) [private]
Definition at line 552 of file lazy-compile-dispatcher.cc.
                                              {
  DCHECK(job->state == Job::State::kFinalized);
  base::MutexGuard lock(&mutex_);
  DeleteJob(job, lock);
}
References v8::internal::DCHECK(), v8::internal::LazyCompileDispatcher::Job::kFinalized, mutex_, and v8::internal::LazyCompileDispatcher::Job::state.
Referenced by AbortAll(), AbortJob(), FinalizeSingleJob(), and FinishNow().
DeleteJob() [2/2]
void v8::internal::LazyCompileDispatcher::DeleteJob (Job * job, const base::MutexGuard &) [private]
Definition at line 558 of file lazy-compile-dispatcher.cc.
                                                                     {
  DCHECK(job->state == Job::State::kFinalized);
#ifdef DEBUG
  all_jobs_.erase(job);
#endif
  jobs_to_dispose_.push_back(job);
  if (jobs_to_dispose_.size() == 1) {
    num_jobs_for_background_++;
  }
}
References v8::internal::DCHECK(), jobs_to_dispose_, v8::internal::LazyCompileDispatcher::Job::kFinalized, num_jobs_for_background_, and v8::internal::LazyCompileDispatcher::Job::state.
DoBackgroundWork()
void v8::internal::LazyCompileDispatcher::DoBackgroundWork (JobDelegate * delegate) [private]
Definition at line 408 of file lazy-compile-dispatcher.cc.
                                                                  {
  base::FlushDenormalsScope flush_denormals_scope(isolate_->flush_denormals());
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.LazyCompileDispatcherDoBackgroundWork");
  LocalIsolate isolate(isolate_, ThreadKind::kBackground);
  UnparkedScope unparked_scope(&isolate);
  LocalHandleScope handle_scope(&isolate);
  ReusableUnoptimizedCompileState reusable_state(&isolate);
  while (true) {
    // Return immediately on yield, avoiding the second loop.
    if (delegate->ShouldYield()) return;
    Job* job = nullptr;
    {
      base::MutexGuard lock(&mutex_);
      if (pending_background_jobs_.empty()) break;
      job = pending_background_jobs_.back();
      pending_background_jobs_.pop_back();
      DCHECK_EQ(job->state, Job::State::kPending);
      job->state = Job::State::kRunning;
    }
    if (V8_UNLIKELY(block_for_testing_.Value())) {
      block_for_testing_.SetValue(false);
      semaphore_for_testing_.Wait();
    }
    if (trace_compiler_dispatcher_) {
      PrintF("LazyCompileDispatcher: doing background work\n");
    }
    job->task->Run(&isolate, &reusable_state);
    {
      base::MutexGuard lock(&mutex_);
      if (job->state == Job::State::kRunning) {
        job->state = Job::State::kReadyToFinalize;
        // Schedule an idle task to finalize the compilation on the main thread
        // if the job has a shared function info registered.
      } else {
        DCHECK_EQ(job->state, Job::State::kAbortRequested);
        job->state = Job::State::kAborted;
      }
      finalizable_jobs_.push_back(job);
      NotifyRemovedBackgroundJob(lock);
      if (main_thread_blocking_on_job_ == job) {
        main_thread_blocking_on_job_ = nullptr;
        main_thread_blocking_signal_.NotifyOne();
      } else {
        ScheduleIdleTaskFromAnyThread(lock);
      }
    }
  }
  while (!delegate->ShouldYield()) {
    Job* job = nullptr;
    {
      base::MutexGuard lock(&mutex_);
      if (jobs_to_dispose_.empty()) break;
      job = jobs_to_dispose_.back();
      jobs_to_dispose_.pop_back();
      if (jobs_to_dispose_.empty()) {
        num_jobs_for_background_--;
      }
    }
    delete job;
  }
  // Don't touch |this| anymore after this point, as it might have been
  // deleted.
}
References block_for_testing_, DCHECK_EQ, finalizable_jobs_, v8::internal::Isolate::flush_denormals(), isolate_, jobs_to_dispose_, v8::internal::LazyCompileDispatcher::Job::kAborted, v8::internal::LazyCompileDispatcher::Job::kAbortRequested, v8::internal::kBackground, v8::internal::LazyCompileDispatcher::Job::kPending, v8::internal::LazyCompileDispatcher::Job::kReadyToFinalize, v8::internal::LazyCompileDispatcher::Job::kRunning, main_thread_blocking_on_job_, main_thread_blocking_signal_, mutex_, v8::base::ConditionVariable::NotifyOne(), NotifyRemovedBackgroundJob(), num_jobs_for_background_, pending_background_jobs_, v8::internal::PrintF(), ScheduleIdleTaskFromAnyThread(), semaphore_for_testing_, v8::base::AtomicValue< T >::SetValue(), v8::JobDelegate::ShouldYield(), v8::internal::LazyCompileDispatcher::Job::state, v8::internal::LazyCompileDispatcher::Job::task, trace_compiler_dispatcher_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, V8_UNLIKELY, v8::base::AtomicValue< T >::Value(), and v8::base::Semaphore::Wait().
Referenced by v8::internal::LazyCompileDispatcher::JobTask::Run().
DoIdleWork()
void v8::internal::LazyCompileDispatcher::DoIdleWork (double deadline_in_seconds) [private]
Definition at line 526 of file lazy-compile-dispatcher.cc.
                                                                 {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.LazyCompilerDispatcherDoIdleWork");
  {
    base::MutexGuard lock(&mutex_);
    idle_task_scheduled_ = false;
  }
  if (trace_compiler_dispatcher_) {
    PrintF("LazyCompileDispatcher: received %0.1lfms of idle time\n",
           (deadline_in_seconds - platform_->MonotonicallyIncreasingTime()) *
               static_cast<double>(base::Time::kMillisecondsPerSecond));
  }
  while (deadline_in_seconds > platform_->MonotonicallyIncreasingTime()) {
    // Find a job which is pending finalization and has a shared function info
    auto there_was_a_job = FinalizeSingleJob();
    if (!there_was_a_job) return;
  }
  // We didn't return above so there still might be jobs to finalize.
  {
    base::MutexGuard lock(&mutex_);
    ScheduleIdleTaskFromAnyThread(lock);
  }
}
References FinalizeSingleJob(), idle_task_scheduled_, v8::base::TimeConstants::kMillisecondsPerSecond, v8::Platform::MonotonicallyIncreasingTime(), mutex_, platform_, v8::internal::PrintF(), ScheduleIdleTaskFromAnyThread(), trace_compiler_dispatcher_, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Enqueue()
void v8::internal::LazyCompileDispatcher::Enqueue (LocalIsolate * isolate, Handle< SharedFunctionInfo > shared_info, std::unique_ptr< Utf16CharacterStream > character_stream)
Definition at line 151 of file lazy-compile-dispatcher.cc.
                                                          {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.LazyCompilerDispatcherEnqueue");
  RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileEnqueueOnDispatcher);
  Job* job = new Job(std::make_unique<BackgroundCompileTask>(
      isolate_, shared_info, std::move(character_stream),
      worker_thread_runtime_call_stats_, background_compile_timer_,
      static_cast<int>(max_stack_size_)));
  SetUncompiledDataJobPointer(isolate, shared_info,
                              reinterpret_cast<Address>(job));
  // Post a background worker task to perform the compilation on the worker
  // thread.
  {
    base::MutexGuard lock(&mutex_);
    if (trace_compiler_dispatcher_) {
      PrintF("LazyCompileDispatcher: enqueued job for ");
      ShortPrint(*shared_info);
      PrintF("\n");
    }
#ifdef DEBUG
    all_jobs_.insert(job);
#endif
    pending_background_jobs_.push_back(job);
    NotifyAddedBackgroundJob(lock);
  }
  // This is not in NotifyAddedBackgroundJob to avoid being inside the mutex.
  job_handle_->NotifyConcurrencyIncrease();
}
References background_compile_timer_, isolate_, job_handle_, max_stack_size_, mutex_, NotifyAddedBackgroundJob(), pending_background_jobs_, v8::internal::PrintF(), RCS_SCOPE, v8::internal::anonymous_namespace{lazy-compile-dispatcher.cc}::SetUncompiledDataJobPointer(), v8::internal::ShortPrint(), trace_compiler_dispatcher_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and worker_thread_runtime_call_stats_.
Referenced by v8::internal::interpreter::BytecodeGenerator::AddToEagerLiteralsIfEager().
FinalizeSingleJob()
bool v8::internal::LazyCompileDispatcher::FinalizeSingleJob () [private]
Definition at line 505 of file lazy-compile-dispatcher.cc.
                                              {
  Job* job = PopSingleFinalizeJob();
  if (job == nullptr) return false;
  if (trace_compiler_dispatcher_) {
    PrintF("LazyCompileDispatcher: idle finalizing job\n");
  }
  if (job->state == Job::State::kFinalizingNow) {
    HandleScope scope(isolate_);
    Compiler::FinalizeBackgroundCompileTask(job->task.get(), isolate_,
                                            Compiler::CLEAR_EXCEPTION);
  } else {
    DCHECK_EQ(job->state, Job::State::kAbortingNow);
    job->task->AbortFunction();
  }
  job->state = Job::State::kFinalized;
  DeleteJob(job);
  return true;
}
References v8::internal::Compiler::CLEAR_EXCEPTION, DCHECK_EQ, DeleteJob(), v8::internal::Compiler::FinalizeBackgroundCompileTask(), isolate_, v8::internal::LazyCompileDispatcher::Job::kAbortingNow, v8::internal::LazyCompileDispatcher::Job::kFinalized, v8::internal::LazyCompileDispatcher::Job::kFinalizingNow, PopSingleFinalizeJob(), v8::internal::PrintF(), v8::internal::LazyCompileDispatcher::Job::state, v8::internal::LazyCompileDispatcher::Job::task, and trace_compiler_dispatcher_.
Referenced by DoIdleWork(), and FinishNow().
FinishNow()
bool v8::internal::LazyCompileDispatcher::FinishNow (DirectHandle< SharedFunctionInfo > function)
Definition at line 254 of file lazy-compile-dispatcher.cc.
                                               {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.LazyCompilerDispatcherFinishNow");
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kCompileFinishNowOnDispatcher);
  if (trace_compiler_dispatcher_) {
    PrintF("LazyCompileDispatcher: finishing ");
    ShortPrint(*function);
    PrintF(" now\n");
  }
  Job* job;
  {
    base::MutexGuard lock(&mutex_);
    job = GetJobFor(function, lock);
    WaitForJobIfRunningOnBackground(job, lock);
  }
  if (job->state == Job::State::kPendingToRunOnForeground) {
    job->task->RunOnMainThread(isolate_);
    job->state = Job::State::kFinalizingNow;
  }
  if (DEBUG_BOOL) {
    base::MutexGuard lock(&mutex_);
    DCHECK_EQ(std::count(pending_background_jobs_.begin(),
                         pending_background_jobs_.end(), job),
              0);
    DCHECK_EQ(
        std::count(finalizable_jobs_.begin(), finalizable_jobs_.end(), job), 0);
    DCHECK_EQ(job->state, Job::State::kFinalizingNow);
  }
  bool success = Compiler::FinalizeBackgroundCompileTask(
      job->task.get(), isolate_, Compiler::KEEP_EXCEPTION);
  job->state = Job::State::kFinalized;
  DCHECK_NE(success, isolate_->has_exception());
  DeleteJob(job);
  // Opportunistically finalize all other jobs for a maximum time of
  // kMaxOpportunisticFinalizeTimeMs.
  double deadline_in_seconds = platform_->MonotonicallyIncreasingTime() +
                               kMaxOpportunisticFinalizeTimeMs / 1000.0;
  while (deadline_in_seconds > platform_->MonotonicallyIncreasingTime()) {
    if (!FinalizeSingleJob()) break;
  }
  return success;
}
References DCHECK_EQ, DCHECK_NE, DEBUG_BOOL, DeleteJob(), finalizable_jobs_, v8::internal::Compiler::FinalizeBackgroundCompileTask(), FinalizeSingleJob(), GetJobFor(), v8::internal::Isolate::has_exception(), isolate_, v8::internal::Compiler::KEEP_EXCEPTION, v8::internal::LazyCompileDispatcher::Job::kFinalized, v8::internal::LazyCompileDispatcher::Job::kFinalizingNow, v8::internal::kMaxOpportunisticFinalizeTimeMs, v8::internal::LazyCompileDispatcher::Job::kPendingToRunOnForeground, v8::Platform::MonotonicallyIncreasingTime(), mutex_, pending_background_jobs_, platform_, v8::internal::PrintF(), RCS_SCOPE, v8::internal::ShortPrint(), v8::internal::LazyCompileDispatcher::Job::state, v8::internal::LazyCompileDispatcher::Job::task, trace_compiler_dispatcher_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and WaitForJobIfRunningOnBackground().
Referenced by v8::internal::Compiler::Compile().
FRIEND_TEST() [1/8]
v8::internal::LazyCompileDispatcher::FRIEND_TEST (LazyCompileDispatcherTest , AbortJobAlreadyStarted) [private]
FRIEND_TEST() [2/8]
v8::internal::LazyCompileDispatcher::FRIEND_TEST (LazyCompileDispatcherTest , AbortJobNotStarted) [private]
FRIEND_TEST() [3/8]
v8::internal::LazyCompileDispatcher::FRIEND_TEST (LazyCompileDispatcherTest , AsyncAbortAllPendingWorkerTask) [private]
FRIEND_TEST() [4/8]
v8::internal::LazyCompileDispatcher::FRIEND_TEST (LazyCompileDispatcherTest , AsyncAbortAllRunningWorkerTask) [private]
FRIEND_TEST() [5/8]
v8::internal::LazyCompileDispatcher::FRIEND_TEST (LazyCompileDispatcherTest , CompileMultipleOnBackgroundThread) [private]
FRIEND_TEST() [6/8]
v8::internal::LazyCompileDispatcher::FRIEND_TEST (LazyCompileDispatcherTest , FinishNowWithWorkerTask) [private]
FRIEND_TEST() [7/8]
v8::internal::LazyCompileDispatcher::FRIEND_TEST (LazyCompileDispatcherTest , IdleTaskNoIdleTime) [private]
FRIEND_TEST() [8/8]
v8::internal::LazyCompileDispatcher::FRIEND_TEST (LazyCompileDispatcherTest , IdleTaskSmallIdleTime) [private]
GetJobFor()
LazyCompileDispatcher::Job * v8::internal::LazyCompileDispatcher::GetJobFor (DirectHandle< SharedFunctionInfo > shared, const base::MutexGuard &) const [private]
Definition at line 381 of file lazy-compile-dispatcher.cc.
                                                                          {
  if (!shared->HasUncompiledData(isolate_)) return nullptr;
  Tagged<UncompiledData> data = shared->uncompiled_data(isolate_);
  if (IsUncompiledDataWithPreparseDataAndJob(data)) {
    return reinterpret_cast<Job*>(
        Cast<UncompiledDataWithPreparseDataAndJob>(data)->job());
  } else if (IsUncompiledDataWithoutPreparseDataWithJob(data)) {
    return reinterpret_cast<Job*>(
        Cast<UncompiledDataWithoutPreparseDataWithJob>(data)->job());
  }
  return nullptr;
}
References isolate_.
Referenced by AbortJob(), and FinishNow().
IsEnqueued()
bool v8::internal::LazyCompileDispatcher::IsEnqueued (DirectHandle< SharedFunctionInfo > function) const
Definition at line 186 of file lazy-compile-dispatcher.cc.
                                                   {
  if (!shared->HasUncompiledData(isolate_)) return false;
  Job* job = nullptr;
  Tagged<UncompiledData> data = shared->uncompiled_data(isolate_);
  if (IsUncompiledDataWithPreparseDataAndJob(data)) {
    job = reinterpret_cast<Job*>(
        Cast<UncompiledDataWithPreparseDataAndJob>(data)->job());
  } else if (IsUncompiledDataWithoutPreparseDataWithJob(data)) {
    job = reinterpret_cast<Job*>(
        Cast<UncompiledDataWithoutPreparseDataWithJob>(data)->job());
  }
  return job != nullptr;
}
References isolate_.
Referenced by v8::internal::Compiler::Compile().
NotifyAddedBackgroundJob()
void v8::internal::LazyCompileDispatcher::NotifyAddedBackgroundJob (const base::MutexGuard & lock) [inline], [private]
Definition at line 168 of file lazy-compile-dispatcher.h.
                                                            {
    ++num_jobs_for_background_;
    VerifyBackgroundTaskCount(lock);
  }
Referenced by Enqueue().
NotifyRemovedBackgroundJob()
void v8::internal::LazyCompileDispatcher::NotifyRemovedBackgroundJob (const base::MutexGuard & lock) [inline], [private]
Definition at line 172 of file lazy-compile-dispatcher.h.
                                                              {
    --num_jobs_for_background_;
    VerifyBackgroundTaskCount(lock);
  }
Referenced by AbortJob(), DoBackgroundWork(), and WaitForJobIfRunningOnBackground().
operator=()
LazyCompileDispatcher& v8::internal::LazyCompileDispatcher::operator= (const LazyCompileDispatcher &) [delete]
PopSingleFinalizeJob()
LazyCompileDispatcher::Job * v8::internal::LazyCompileDispatcher::PopSingleFinalizeJob () [private]
Definition at line 487 of file lazy-compile-dispatcher.cc.
                                                                      {
  base::MutexGuard lock(&mutex_);
  if (finalizable_jobs_.empty()) return nullptr;
  Job* job = finalizable_jobs_.back();
  finalizable_jobs_.pop_back();
  DCHECK(job->state == Job::State::kReadyToFinalize ||
         job->state == Job::State::kAborted);
  if (job->state == Job::State::kReadyToFinalize) {
    job->state = Job::State::kFinalizingNow;
  } else {
    DCHECK_EQ(job->state, Job::State::kAborted);
    job->state = Job::State::kAbortingNow;
  }
  return job;
}
References v8::internal::DCHECK(), DCHECK_EQ, finalizable_jobs_, v8::internal::LazyCompileDispatcher::Job::kAborted, v8::internal::LazyCompileDispatcher::Job::kAbortingNow, v8::internal::LazyCompileDispatcher::Job::kFinalizingNow, v8::internal::LazyCompileDispatcher::Job::kReadyToFinalize, mutex_, and v8::internal::LazyCompileDispatcher::Job::state.
Referenced by FinalizeSingleJob().
ScheduleIdleTaskFromAnyThread()
void v8::internal::LazyCompileDispatcher::ScheduleIdleTaskFromAnyThread (const base::MutexGuard &) [private]
Definition at line 395 of file lazy-compile-dispatcher.cc.
                           {
  if (!taskrunner_->IdleTasksEnabled()) return;
  if (idle_task_scheduled_) return;
  idle_task_scheduled_ = true;
  // TODO(leszeks): Using a full task manager for a single cancellable task is
  // overkill, we could probably do the cancelling ourselves.
  taskrunner_->PostIdleTask(MakeCancelableIdleTask(
      idle_task_manager_.get(),
      [this](double deadline_in_seconds) { DoIdleWork(deadline_in_seconds); }));
}
References idle_task_manager_, idle_task_scheduled_, v8::internal::MakeCancelableIdleTask(), and taskrunner_.
Referenced by DoBackgroundWork(), and DoIdleWork().
VerifyBackgroundTaskCount()
void v8::internal::LazyCompileDispatcher::VerifyBackgroundTaskCount (const base::MutexGuard &) [inline], [private]
Definition at line 180 of file lazy-compile-dispatcher.h.
{}
Referenced by AbortAll().
WaitForJobIfRunningOnBackground()
void v8::internal::LazyCompileDispatcher::WaitForJobIfRunningOnBackground (Job * job, const base::MutexGuard & lock) [private]
Definition at line 201 of file lazy-compile-dispatcher.cc.
                                          {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.LazyCompilerDispatcherWaitForBackgroundJob");
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kCompileWaitForDispatcher);
  if (!job->is_running_on_background()) {
    if (job->state == Job::State::kPending) {
      DCHECK_EQ(std::count(pending_background_jobs_.begin(),
                           pending_background_jobs_.end(), job),
                1);
      // TODO(leszeks): Remove from pending jobs without walking the whole
      // vector.
      pending_background_jobs_.erase(
          std::remove(pending_background_jobs_.begin(),
                      pending_background_jobs_.end(), job),
          pending_background_jobs_.end());
      job->state = Job::State::kPendingToRunOnForeground;
      NotifyRemovedBackgroundJob(lock);
    } else {
      DCHECK_EQ(job->state, Job::State::kReadyToFinalize);
      DCHECK_EQ(
          std::count(finalizable_jobs_.begin(), finalizable_jobs_.end(), job),
          1);
      // TODO(leszeks): Remove from finalizable jobs without walking the whole
      // vector.
      finalizable_jobs_.erase(
          std::remove(finalizable_jobs_.begin(), finalizable_jobs_.end(), job),
          finalizable_jobs_.end());
      job->state = Job::State::kFinalizingNow;
    }
    return;
  }
  DCHECK_NULL(main_thread_blocking_on_job_);
  main_thread_blocking_on_job_ = job;
  while (main_thread_blocking_on_job_ != nullptr) {
    main_thread_blocking_signal_.Wait(&mutex_);
  }
  DCHECK_EQ(job->state, Job::State::kReadyToFinalize);
  DCHECK_EQ(std::count(finalizable_jobs_.begin(), finalizable_jobs_.end(), job),
            1);
  // TODO(leszeks): Remove from finalizable jobs without walking the whole
  // vector.
  finalizable_jobs_.erase(
      std::remove(finalizable_jobs_.begin(), finalizable_jobs_.end(), job),
      finalizable_jobs_.end());
  job->state = Job::State::kFinalizingNow;
}
References DCHECK_EQ, DCHECK_NULL, finalizable_jobs_, v8::internal::LazyCompileDispatcher::Job::is_running_on_background(), isolate_, v8::internal::LazyCompileDispatcher::Job::kFinalizingNow, v8::internal::LazyCompileDispatcher::Job::kPending, v8::internal::LazyCompileDispatcher::Job::kPendingToRunOnForeground, v8::internal::LazyCompileDispatcher::Job::kReadyToFinalize, main_thread_blocking_on_job_, main_thread_blocking_signal_, mutex_, NotifyRemovedBackgroundJob(), pending_background_jobs_, RCS_SCOPE, v8::internal::LazyCompileDispatcher::Job::state, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::base::ConditionVariable::Wait().
Referenced by FinishNow().
Member Data Documentation
background_compile_timer_
TimedHistogram* v8::internal::LazyCompileDispatcher::background_compile_timer_ [private]
Definition at line 185 of file lazy-compile-dispatcher.h.
Referenced by Enqueue().
block_for_testing_
base::AtomicValue<bool> v8::internal::LazyCompileDispatcher::block_for_testing_ [private]
Definition at line 233 of file lazy-compile-dispatcher.h.
Referenced by DoBackgroundWork().
finalizable_jobs_
std::vector<Job*> v8::internal::LazyCompileDispatcher::finalizable_jobs_ [private]
Definition at line 209 of file lazy-compile-dispatcher.h.
Referenced by AbortAll(), AbortJob(), DoBackgroundWork(), FinishNow(), PopSingleFinalizeJob(), and WaitForJobIfRunningOnBackground().
idle_task_manager_
std::unique_ptr<CancelableTaskManager> v8::internal::LazyCompileDispatcher::idle_task_manager_ [private]
Definition at line 196 of file lazy-compile-dispatcher.h.
Referenced by AbortAll(), and ScheduleIdleTaskFromAnyThread().
idle_task_scheduled_
bool v8::internal::LazyCompileDispatcher::idle_task_scheduled_ [private]
Definition at line 203 of file lazy-compile-dispatcher.h.
Referenced by DoIdleWork(), and ScheduleIdleTaskFromAnyThread().
isolate_
Isolate* v8::internal::LazyCompileDispatcher::isolate_ [private]
Definition at line 183 of file lazy-compile-dispatcher.h.
Referenced by DoBackgroundWork(), Enqueue(), FinalizeSingleJob(), FinishNow(), GetJobFor(), IsEnqueued(), and WaitForJobIfRunningOnBackground().
job_handle_
std::unique_ptr<JobHandle> v8::internal::LazyCompileDispatcher::job_handle_ [private]
Definition at line 190 of file lazy-compile-dispatcher.h.
Referenced by AbortAll(), Enqueue(), LazyCompileDispatcher(), and ~LazyCompileDispatcher().
jobs_to_dispose_
std::vector<Job*> v8::internal::LazyCompileDispatcher::jobs_to_dispose_ [private]
Definition at line 225 of file lazy-compile-dispatcher.h.
Referenced by AbortAll(), DeleteJob(), and DoBackgroundWork().
main_thread_blocking_on_job_
Job* v8::internal::LazyCompileDispatcher::main_thread_blocking_on_job_ [private]
Definition at line 229 of file lazy-compile-dispatcher.h.
Referenced by DoBackgroundWork(), and WaitForJobIfRunningOnBackground().
main_thread_blocking_signal_
base::ConditionVariable v8::internal::LazyCompileDispatcher::main_thread_blocking_signal_ [private]
Definition at line 230 of file lazy-compile-dispatcher.h.
Referenced by DoBackgroundWork(), and WaitForJobIfRunningOnBackground().
max_stack_size_
size_t v8::internal::LazyCompileDispatcher::max_stack_size_ [private]
Definition at line 188 of file lazy-compile-dispatcher.h.
Referenced by Enqueue().
mutex_
base::Mutex v8::internal::LazyCompileDispatcher::mutex_ [mutable], [private]
Definition at line 200 of file lazy-compile-dispatcher.h.
Referenced by AbortAll(), AbortJob(), DeleteJob(), DoBackgroundWork(), DoIdleWork(), Enqueue(), FinishNow(), PopSingleFinalizeJob(), and WaitForJobIfRunningOnBackground().
num_jobs_for_background_
std::atomic<size_t> v8::internal::LazyCompileDispatcher::num_jobs_for_background_ [private]
Definition at line 213 of file lazy-compile-dispatcher.h.
Referenced by AbortAll(), DeleteJob(), DoBackgroundWork(), and v8::internal::LazyCompileDispatcher::JobTask::GetMaxConcurrency().
pending_background_jobs_
std::vector<Job*> v8::internal::LazyCompileDispatcher::pending_background_jobs_ [private]
Definition at line 206 of file lazy-compile-dispatcher.h.
Referenced by AbortAll(), AbortJob(), DoBackgroundWork(), Enqueue(), FinishNow(), and WaitForJobIfRunningOnBackground().
platform_
Platform* v8::internal::LazyCompileDispatcher::platform_ [private]
Definition at line 187 of file lazy-compile-dispatcher.h.
Referenced by DoIdleWork(), FinishNow(), and LazyCompileDispatcher().
semaphore_for_testing_
base::Semaphore v8::internal::LazyCompileDispatcher::semaphore_for_testing_ [private]
Definition at line 234 of file lazy-compile-dispatcher.h.
Referenced by DoBackgroundWork().
taskrunner_
std::shared_ptr<TaskRunner> v8::internal::LazyCompileDispatcher::taskrunner_ [private]
Definition at line 186 of file lazy-compile-dispatcher.h.
Referenced by ScheduleIdleTaskFromAnyThread().
trace_compiler_dispatcher_
bool v8::internal::LazyCompileDispatcher::trace_compiler_dispatcher_ [private]
Definition at line 194 of file lazy-compile-dispatcher.h.
Referenced by AbortJob(), DoBackgroundWork(), DoIdleWork(), Enqueue(), FinalizeSingleJob(), and FinishNow().
worker_thread_runtime_call_stats_
WorkerThreadRuntimeCallStats* v8::internal::LazyCompileDispatcher::worker_thread_runtime_call_stats_ [private]
Definition at line 184 of file lazy-compile-dispatcher.h.
Referenced by Enqueue().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler-dispatcher/lazy-compile-dispatcher.h
/mnt/V8SourceCode/src/compiler-dispatcher/lazy-compile-dispatcher.cc