v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver Class Reference
Public Member Functions
GlobalObjectNameResolver (V8InspectorSessionImpl *session)
const char * GetName (v8::Local< v8::Object > object) override
Returns name to be used in the heap snapshot for given node.
Private Attributes
size_t m_offset
std::vector< char > m_strings
V8InspectorSessionImpl * m_session
Additional Inherited Members
Detailed Description
Definition at line 52 of file v8-heap-profiler-agent-impl.cc.
Constructor & Destructor Documentation
GlobalObjectNameResolver()
v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GlobalObjectNameResolver (V8InspectorSessionImpl * session) [inline], [explicit]
Definition at line 55 of file v8-heap-profiler-agent-impl.cc.
      : m_offset(0), m_strings(10000), m_session(session) {}
Member Function Documentation
GetName()
const char* v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GetName (v8::Local< v8::Object > object) [inline], [override], [virtual]
Returns name to be used in the heap snapshot for given node.
Returned string must stay alive until snapshot collection is completed.
Implements v8::HeapProfiler::ObjectNameResolver.
Definition at line 58 of file v8-heap-profiler-agent-impl.cc.
                                                         {
    v8::Local<v8::Context> creationContext;
    if (!object->GetCreationContext(m_session->inspector()->isolate())
             .ToLocal(&creationContext)) {
      return "";
    }
    InspectedContext* context = m_session->inspector()->getContext(
        m_session->contextGroupId(),
        InspectedContext::contextId(creationContext));
    if (!context) return "";
    String16 name = context->origin();
    size_t length = name.length();
    if (m_offset + length + 1 >= m_strings.size()) return "";
    for (size_t i = 0; i < length; ++i) {
      UChar ch = name[i];
      m_strings[m_offset + i] = ch > 0xFF ? '?' : static_cast<char>(ch);
    }
    m_strings[m_offset + length] = '\0';
    char* result = &*m_strings.begin() + m_offset;
    m_offset += length + 1;
    return result;
  }
References v8_inspector::InspectedContext::contextId(), v8_inspector::V8InspectorImpl::getContext(), v8::Object::GetCreationContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::InspectedContext::inspector(), v8::internal::length, name, v8_inspector::InspectedContext::origin(), v8::base::internal::result, and v8::MaybeLocal< T >::ToLocal().
Member Data Documentation
m_offset
size_t v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::m_offset [private]
Definition at line 82 of file v8-heap-profiler-agent-impl.cc.
m_session
V8InspectorSessionImpl* v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::m_session [private]
Definition at line 84 of file v8-heap-profiler-agent-impl.cc.
m_strings
std::vector<char> v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::m_strings [private]
Definition at line 83 of file v8-heap-profiler-agent-impl.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/v8-heap-profiler-agent-impl.cc