v8::base::SmallVector< T, kSize, Allocator > Class Template Reference
#include <small-vector.h>
Public Types
using value_type = T
Public Member Functions
SmallVector ()=default
SmallVector (const Allocator &allocator)
SmallVector (size_t size, const Allocator &allocator=Allocator())
SmallVector (size_t size, const T &initial_value, const Allocator &allocator=Allocator())
SmallVector (const SmallVector &other) V8_NOEXCEPT
SmallVector (const SmallVector &other, const Allocator &allocator) V8_NOEXCEPT
SmallVector (SmallVector &&other) V8_NOEXCEPT
SmallVector (SmallVector &&other, const Allocator &allocator) V8_NOEXCEPT
SmallVector (std::initializer_list< T > init, const Allocator &allocator=Allocator())
SmallVector (base::Vector< const T > init, const Allocator &allocator=Allocator())
~SmallVector ()
SmallVector & operator= (const SmallVector &other) V8_NOEXCEPT
SmallVector & operator= (SmallVector &&other) V8_NOEXCEPT
T * data ()
const T * data () const
T * begin ()
const T * begin () const
T * end ()
const T * end () const
auto rbegin ()
auto rbegin () const
auto rend ()
auto rend () const
size_t size () const
bool empty () const
size_t capacity () const
T & front ()
const T & front () const
T & back ()
const T & back () const
T & at (size_t index)
T & operator[] (size_t index)
const T & at (size_t index) const
const T & operator[] (size_t index) const
template<typename... Args>
void emplace_back (Args &&... args)
void push_back (T x)
void pop_back (size_t count=1)
T * insert (T *pos, const T &value)
T * insert (T *pos, size_t count, const T &value)
template<typename It >
T * insert (T *pos, It begin, It end)
T * insert (T *pos, std::initializer_list< T > values)
T * erase (T *erase_start, T *erase_end)
T * erase (T *pos)
void resize (size_t new_size)
void resize (size_t new_size, const T &initial_value)
void reserve (size_t new_capacity)
void clear ()
Allocator get_allocator () const
Static Public Attributes
static constexpr size_t kInlineSize = kSize
Private Member Functions
V8_NOINLINE V8_PRESERVE_MOST void Grow ()
V8_NOINLINE V8_PRESERVE_MOST void Grow (size_t min_capacity)
T * AllocateDynamicStorage (size_t number_of_elements)
V8_NOINLINE V8_PRESERVE_MOST void FreeStorage ()
void reset_to_inline_storage ()
bool is_big () const
T * inline_storage_begin ()
const T * inline_storage_begin () const
Private Attributes
V8_NO_UNIQUE_ADDRESS Allocator allocator_
T * begin_ = inline_storage_begin()
T * end_ = begin_
T * end_of_storage_ = begin_ + kInlineSize
char inline_storage_ [sizeof(T) *kInlineSize]
Static Private Attributes
static constexpr bool kHasTrivialElement
Detailed Description
template<typename T, size_t kSize, typename Allocator = std::allocator<T>>
class v8::base::SmallVector< T, kSize, Allocator >
Definition at line 22 of file small-vector.h.
Member Typedef Documentation
value_type
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
using v8::base::SmallVector< T, kSize, Allocator >::value_type = T
Definition at line 25 of file small-vector.h.
Constructor & Destructor Documentation
SmallVector() [1/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector () [default]
SmallVector() [2/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (const Allocator & allocator) [inline], [explicit]
Definition at line 28 of file small-vector.h.
: allocator_(allocator) {}
SmallVector() [3/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (size_t size, const Allocator & allocator = Allocator()) [inline], [explicit]
Definition at line 29 of file small-vector.h.
      : allocator_(allocator) {
    resize(size);
  }
References v8::base::SmallVector< T, kSize, Allocator >::resize(), and v8::base::SmallVector< T, kSize, Allocator >::size().
SmallVector() [4/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (size_t size, const T & initial_value, const Allocator & allocator = Allocator()) [inline], [explicit]
Definition at line 34 of file small-vector.h.
      : allocator_(allocator) {
    resize(size, initial_value);
  }
References v8::base::SmallVector< T, kSize, Allocator >::resize(), and v8::base::SmallVector< T, kSize, Allocator >::size().
SmallVector() [5/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (const SmallVector< T, kSize, Allocator > & other) [inline]
Definition at line 39 of file small-vector.h.
      : allocator_(other.allocator_) {
    *this = other;
  }
SmallVector() [6/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (const SmallVector< T, kSize, Allocator > & other, const Allocator & allocator) [inline]
Definition at line 43 of file small-vector.h.
      : allocator_(allocator) {
    *this = other;
  }
SmallVector() [7/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (SmallVector< T, kSize, Allocator > && other) [inline]
Definition at line 47 of file small-vector.h.
      : allocator_(std::move(other.allocator_)) {
    *this = std::move(other);
  }
SmallVector() [8/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (SmallVector< T, kSize, Allocator > && other, const Allocator & allocator) [inline]
Definition at line 51 of file small-vector.h.
      : allocator_(allocator) {
    *this = std::move(other);
  }
SmallVector() [9/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (std::initializer_list< T > init, const Allocator & allocator = Allocator()) [inline]
Definition at line 55 of file small-vector.h.
      : allocator_(allocator) {
    if (init.size() > capacity()) Grow(init.size());
    DCHECK_GE(capacity(), init.size()); // Sanity check.
    std::uninitialized_move(init.begin(), init.end(), begin_);
    end_ = begin_ + init.size();
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::capacity(), DCHECK_GE, v8::base::SmallVector< T, kSize, Allocator >::end_, and v8::base::SmallVector< T, kSize, Allocator >::Grow().
SmallVector() [10/10]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::SmallVector (base::Vector< const T > init, const Allocator & allocator = Allocator()) [inline], [explicit]
Definition at line 63 of file small-vector.h.
      : allocator_(allocator) {
    if (init.size() > capacity()) Grow(init.size());
    DCHECK_GE(capacity(), init.size()); // Sanity check.
    std::uninitialized_copy(init.begin(), init.end(), begin_);
    end_ = begin_ + init.size();
  }
References v8::base::Vector< T >::begin(), v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::capacity(), DCHECK_GE, v8::base::Vector< T >::end(), v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::Grow(), and v8::base::Vector< T >::size().
 SmallVector()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
v8::base::SmallVector< T, kSize, Allocator >::~SmallVector () [inline]
Definition at line 72 of file small-vector.h.
{ FreeStorage(); }
References v8::base::SmallVector< T, kSize, Allocator >::FreeStorage().
Member Function Documentation
AllocateDynamicStorage()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::AllocateDynamicStorage (size_t number_of_elements) [inline], [private]
Definition at line 302 of file small-vector.h.
                                                       {
    return allocator_.allocate(number_of_elements);
  }
References v8::base::SmallVector< T, kSize, Allocator >::allocator_.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::Grow(), and v8::base::SmallVector< T, kSize, Allocator >::operator=().
at() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T& v8::base::SmallVector< T, kSize, Allocator >::at (size_t index) [inline]
Definition at line 166 of file small-vector.h.
                      {
    DCHECK_GT(size(), index);
    return begin_[index];
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, DCHECK_GT, v8::internal::index, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::at(), v8::base::SmallVector< T, kSize, Allocator >::operator[](), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ToCanonicalZoneList().
at() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
const T& v8::base::SmallVector< T, kSize, Allocator >::at (size_t index) const [inline]
Definition at line 176 of file small-vector.h.
                                  {
    DCHECK_GT(size(), index);
    return begin_[index];
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, DCHECK_GT, v8::internal::index, and v8::base::SmallVector< T, kSize, Allocator >::size().
back() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T& v8::base::SmallVector< T, kSize, Allocator >::back () [inline]
Definition at line 157 of file small-vector.h.
            {
    DCHECK_NE(0, size());
    return end_[-1];
  }
References DCHECK_NE, v8::base::SmallVector< T, kSize, Allocator >::end_, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddQuantifierToAtom(), v8::internal::DirectHandleSmallVector< T, kSize >::back(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_cast(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushTerms(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::JsonParser< Char >::ParseJsonValue(), v8::internal::compiler::turboshaft::Block::PrintDominatorTree(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::ToRegExp(), v8::internal::maglev::RegisterFrameState< v8::internal::DoubleRegister >::TryChooseInputRegister(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitAllBlocks().
back() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
const T& v8::base::SmallVector< T, kSize, Allocator >::back () const [inline]
Definition at line 161 of file small-vector.h.
                        {
    DCHECK_NE(0, size());
    return end_[-1];
  }
References DCHECK_NE, v8::base::SmallVector< T, kSize, Allocator >::end_, and v8::base::SmallVector< T, kSize, Allocator >::size().
begin() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::begin () [inline]
Definition at line 132 of file small-vector.h.
{ return begin_; }
References v8::base::SmallVector< T, kSize, Allocator >::begin_.
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::DirectHandleSmallVector< T, kSize >::begin(), v8::internal::compiler::WasmGraphBuilder::BuildCallNode(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComputePredecessors(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushTerms(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::ToRegExp(), and v8::internal::compiler::Revectorizer::VectorizeTree().
begin() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
const T* v8::base::SmallVector< T, kSize, Allocator >::begin () const [inline]
Definition at line 133 of file small-vector.h.
{ return begin_; }
References v8::base::SmallVector< T, kSize, Allocator >::begin_.
capacity()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
size_t v8::base::SmallVector< T, kSize, Allocator >::capacity () const [inline]
Definition at line 146 of file small-vector.h.
{ return end_of_storage_ - begin_; }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, and v8::base::SmallVector< T, kSize, Allocator >::end_of_storage_.
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::capacity(), v8::base::SmallVector< T, kSize, Allocator >::Grow(), v8::base::SmallVector< T, kSize, Allocator >::operator=(), v8::base::SmallVector< T, kSize, Allocator >::reserve(), v8::base::SmallVector< T, kSize, Allocator >::resize(), and v8::base::SmallVector< T, kSize, Allocator >::SmallVector().
clear()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
void v8::base::SmallVector< T, kSize, Allocator >::clear () [inline]
Definition at line 274 of file small-vector.h.
               {
    std::destroy_n(begin_, end_ - begin_);
    end_ = begin_;
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, and v8::base::SmallVector< T, kSize, Allocator >::end_.
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::clear(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushTerms(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessBasicBlock(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi().
data() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::data () [inline]
Definition at line 129 of file small-vector.h.
{ return begin_; }
References v8::base::SmallVector< T, kSize, Allocator >::begin_.
Referenced by v8::internal::SmallStringOptimizedAllocator< kInlineSize >::allocate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmMaybeReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::compiler::turboshaft::CreateOperation(), v8::internal::DirectHandleSmallVector< T, kSize >::data(), v8::internal::StringToBigIntHelper< IsolateT >::DecimalString(), v8::internal::SmallStringOptimizedAllocator< kInlineSize >::grow(), v8::internal::Builtins::InvokeApiFunction(), v8::internal::compiler::WasmGraphBuilder::Return(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNew(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::TryInlining(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange().
data() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
const T* v8::base::SmallVector< T, kSize, Allocator >::data () const [inline]
Definition at line 130 of file small-vector.h.
{ return begin_; }
References v8::base::SmallVector< T, kSize, Allocator >::begin_.
emplace_back()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
template<typename... Args>
void v8::base::SmallVector< T, kSize, Allocator >::emplace_back (Args &&... args) [inline]
Definition at line 184 of file small-vector.h.
                                    {
    if (V8_UNLIKELY(end_ == end_of_storage_)) Grow();
    void* storage = end_;
    end_ += 1;
    new (storage) T(std::forward<Args>(args)...);
  }
References v8::base::args, v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::end_of_storage_, v8::base::SmallVector< T, kSize, Allocator >::Grow(), T, and V8_UNLIKELY.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAssertion(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAtom(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddQuantifierToAtom(), v8::internal::UnicodeRangeSplitter::AddRange(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddTerm(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphSwitch(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), v8::internal::DirectHandleSmallVector< T, kSize >::emplace_back(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushTerms(), v8::internal::JsonParser< Char >::ParseJsonValue(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::IsolateSafepoint::SetSafepointRequestedFlags(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded(), and v8::internal::Parser::UpdateStatistics().
empty()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
bool v8::base::SmallVector< T, kSize, Allocator >::empty () const [inline]
Definition at line 145 of file small-vector.h.
{ return end_ == begin_; }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, and v8::base::SmallVector< T, kSize, Allocator >::end_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddQuantifierToAtom(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitMaterialisationsAndPushResults(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitPopMaterialisedResults(), v8::internal::DirectHandleSmallVector< T, kSize >::empty(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::is_empty(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakePhiMaybePermuteInputs(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessPhi(), v8::internal::wasm::PublishDetectedFeatures(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping(), v8::internal::Heap::ReportStatisticsAfterGC(), v8::internal::IsolateSafepoint::SetSafepointRequestedFlags(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ToCanonicalZoneList(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitAllBlocks().
end() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::end () [inline]
Definition at line 135 of file small-vector.h.
{ return end_; }
References v8::base::SmallVector< T, kSize, Allocator >::end_.
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallForwardVarargs(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallWithSpread(), v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComputePredecessors(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector(), v8::internal::DirectHandleSmallVector< T, kSize >::end(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::internal::Heap::IncrementDeferredCounts(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run().
end() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
const T* v8::base::SmallVector< T, kSize, Allocator >::end () const [inline]
Definition at line 136 of file small-vector.h.
{ return end_; }
References v8::base::SmallVector< T, kSize, Allocator >::end_.
erase() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::erase (T * erase_start, T * erase_end) [inline]
Definition at line 233 of file small-vector.h.
                                         {
    DCHECK_GE(erase_start, begin_);
    DCHECK_LE(erase_start, erase_end);
    DCHECK_LE(erase_end, end_);
    T* new_end = std::move(erase_end, end_, erase_start);
    std::destroy_n(new_end, std::distance(new_end, end_));
    end_ = new_end;
    return erase_start;
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, DCHECK_GE, DCHECK_LE, and v8::base::SmallVector< T, kSize, Allocator >::end_.
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::erase().
erase() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::erase (T * pos) [inline]
Definition at line 243 of file small-vector.h.
{ return erase(pos, pos + 1); }
References v8::base::SmallVector< T, kSize, Allocator >::erase().
Referenced by v8::base::SmallVector< T, kSize, Allocator >::erase().
FreeStorage()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
V8_NOINLINE V8_PRESERVE_MOST void v8::base::SmallVector< T, kSize, Allocator >::FreeStorage () [inline], [private]
Definition at line 306 of file small-vector.h.
                                                  {
    std::destroy_n(begin_, end_ - begin_);
    if (is_big()) allocator_.deallocate(begin_, end_of_storage_ - begin_);
  }
References v8::base::SmallVector< T, kSize, Allocator >::allocator_, v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::end_of_storage_, and v8::base::SmallVector< T, kSize, Allocator >::is_big().
Referenced by v8::base::SmallVector< T, kSize, Allocator >::Grow(), v8::base::SmallVector< T, kSize, Allocator >::operator=(), and v8::base::SmallVector< T, kSize, Allocator >::~SmallVector().
front() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T& v8::base::SmallVector< T, kSize, Allocator >::front () [inline]
Definition at line 148 of file small-vector.h.
             {
    DCHECK_NE(0, size());
    return begin_[0];
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, DCHECK_NE, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::front(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), and v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound().
front() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
const T& v8::base::SmallVector< T, kSize, Allocator >::front () const [inline]
Definition at line 152 of file small-vector.h.
                         {
    DCHECK_NE(0, size());
    return begin_[0];
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, DCHECK_NE, and v8::base::SmallVector< T, kSize, Allocator >::size().
get_allocator()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
Allocator v8::base::SmallVector< T, kSize, Allocator >::get_allocator () const [inline]
Definition at line 279 of file small-vector.h.
{ return allocator_; }
References v8::base::SmallVector< T, kSize, Allocator >::allocator_.
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::get_allocator().
Grow() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
V8_NOINLINE V8_PRESERVE_MOST void v8::base::SmallVector< T, kSize, Allocator >::Grow () [inline], [private]
Definition at line 284 of file small-vector.h.
{ Grow(0); }
References v8::base::SmallVector< T, kSize, Allocator >::Grow().
Referenced by v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::base::SmallVector< T, kSize, Allocator >::Grow(), v8::base::SmallVector< T, kSize, Allocator >::reserve(), v8::base::SmallVector< T, kSize, Allocator >::resize(), and v8::base::SmallVector< T, kSize, Allocator >::SmallVector().
Grow() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
V8_NOINLINE V8_PRESERVE_MOST void v8::base::SmallVector< T, kSize, Allocator >::Grow (size_t min_capacity) [inline], [private]
Definition at line 287 of file small-vector.h.
                                                              {
    size_t in_use = end_ - begin_;
    size_t new_capacity =
        base::bits::RoundUpToPowerOfTwo(std::max(min_capacity, 2 * capacity()));
    T* new_storage = AllocateDynamicStorage(new_capacity);
    if (new_storage == nullptr) {
      FatalOOM(OOMType::kProcess, "base::SmallVector::Grow");
    }
    std::uninitialized_move(begin_, end_, new_storage);
    FreeStorage();
    begin_ = new_storage;
    end_ = new_storage + in_use;
    end_of_storage_ = new_storage + new_capacity;
  }
References v8::base::SmallVector< T, kSize, Allocator >::AllocateDynamicStorage(), v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::capacity(), v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::end_of_storage_, v8::base::FatalOOM(), v8::base::SmallVector< T, kSize, Allocator >::FreeStorage(), v8::base::kProcess, and v8::base::bits::RoundUpToPowerOfTwo().
inline_storage_begin() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::inline_storage_begin () [inline], [private]
Definition at line 324 of file small-vector.h.
{ return reinterpret_cast<T*>(inline_storage_); }
References v8::base::SmallVector< T, kSize, Allocator >::inline_storage_.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::is_big(), and v8::base::SmallVector< T, kSize, Allocator >::reset_to_inline_storage().
inline_storage_begin() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
const T* v8::base::SmallVector< T, kSize, Allocator >::inline_storage_begin () const [inline], [private]
Definition at line 325 of file small-vector.h.
                                        {
    return reinterpret_cast<const T*>(inline_storage_);
  }
References v8::base::SmallVector< T, kSize, Allocator >::inline_storage_.
insert() [1/4]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::insert (T * pos, const T & value) [inline]
Definition at line 199 of file small-vector.h.
                                    {
    return insert(pos, static_cast<size_t>(1), value);
  }
References v8::internal::value.
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallForwardVarargs(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallWithSpread(), v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::Heap::IncrementDeferredCounts(), v8::internal::DirectHandleSmallVector< T, kSize >::insert(), and v8::base::SmallVector< T, kSize, Allocator >::insert().
insert() [2/4]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
template<typename It >
T* v8::base::SmallVector< T, kSize, Allocator >::insert (T * pos, It begin, It end) [inline]
Definition at line 215 of file small-vector.h.
                                      {
    DCHECK_LE(pos, end_);
    size_t offset = pos - begin_;
    size_t count = std::distance(begin, end);
    size_t old_size = size();
    resize(old_size + count);
    pos = begin_ + offset;
    T* old_end = begin_ + old_size;
    DCHECK_LE(old_end, end_);
    std::move_backward(pos, old_end, end_);
    std::copy(begin, end, pos);
    return pos;
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::base::SmallVector< T, kSize, Allocator >::begin_, DCHECK_LE, v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::resize(), and v8::base::SmallVector< T, kSize, Allocator >::size().
insert() [3/4]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::insert (T * pos, size_t count, const T & value) [inline]
Definition at line 202 of file small-vector.h.
                                                  {
    DCHECK_LE(pos, end_);
    size_t offset = pos - begin_;
    size_t old_size = size();
    resize(old_size + count);
    pos = begin_ + offset;
    T* old_end = begin_ + old_size;
    DCHECK_LE(old_end, end_);
    std::move_backward(pos, old_end, end_);
    std::fill_n(pos, count, value);
    return pos;
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, DCHECK_LE, v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::resize(), v8::base::SmallVector< T, kSize, Allocator >::size(), and v8::internal::value.
insert() [4/4]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::insert (T * pos, std::initializer_list< T > values) [inline]
Definition at line 229 of file small-vector.h.
                                                   {
    return insert(pos, values.begin(), values.end());
  }
References v8::base::SmallVector< T, kSize, Allocator >::insert().
is_big()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
bool v8::base::SmallVector< T, kSize, Allocator >::is_big () const [inline], [private]
Definition at line 322 of file small-vector.h.
{ return begin_ != inline_storage_begin(); }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, and v8::base::SmallVector< T, kSize, Allocator >::inline_storage_begin().
Referenced by v8::base::SmallVector< T, kSize, Allocator >::FreeStorage(), and v8::base::SmallVector< T, kSize, Allocator >::reset_to_inline_storage().
operator=() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
SmallVector& v8::base::SmallVector< T, kSize, Allocator >::operator= (const SmallVector< T, kSize, Allocator > & other) [inline]
Definition at line 74 of file small-vector.h.
                                                               {
    if (this == &other) return *this;
    size_t other_size = other.size();
    if (capacity() < other_size) {
      // Create large-enough heap-allocated storage.
      FreeStorage();
      begin_ = AllocateDynamicStorage(other_size);
      end_of_storage_ = begin_ + other_size;
      std::uninitialized_copy(other.begin_, other.end_, begin_);
    } else if constexpr (kHasTrivialElement) {
      std::copy(other.begin_, other.end_, begin_);
    } else {
      ptrdiff_t to_copy =
          std::min(static_cast<ptrdiff_t>(other_size), end_ - begin_);
      std::copy(other.begin_, other.begin_ + to_copy, begin_);
      if (other.begin_ + to_copy < other.end_) {
        std::uninitialized_copy(other.begin_ + to_copy, other.end_,
                                begin_ + to_copy);
      } else {
        std::destroy_n(begin_ + to_copy, size() - to_copy);
      }
    }
    end_ = begin_ + other_size;
    return *this;
  }
References v8::base::SmallVector< T, kSize, Allocator >::AllocateDynamicStorage(), v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::capacity(), v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::end_of_storage_, v8::base::SmallVector< T, kSize, Allocator >::FreeStorage(), v8::base::SmallVector< T, kSize, Allocator >::kHasTrivialElement, and v8::base::SmallVector< T, kSize, Allocator >::size().
operator=() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
SmallVector& v8::base::SmallVector< T, kSize, Allocator >::operator= (SmallVector< T, kSize, Allocator > && other) [inline]
Definition at line 100 of file small-vector.h.
                                                          {
    if (this == &other) return *this;
    if (other.is_big()) {
      FreeStorage();
      begin_ = other.begin_;
      end_ = other.end_;
      end_of_storage_ = other.end_of_storage_;
    } else {
      DCHECK_GE(capacity(), other.size()); // Sanity check.
      size_t other_size = other.size();
      if constexpr (kHasTrivialElement) {
        std::move(other.begin_, other.end_, begin_);
      } else {
        ptrdiff_t to_move =
            std::min(static_cast<ptrdiff_t>(other_size), end_ - begin_);
        std::move(other.begin_, other.begin_ + to_move, begin_);
        if (other.begin_ + to_move < other.end_) {
          std::uninitialized_move(other.begin_ + to_move, other.end_,
                                  begin_ + to_move);
        } else {
          std::destroy_n(begin_ + to_move, size() - to_move);
        }
      }
      end_ = begin_ + other_size;
    }
    other.reset_to_inline_storage();
    return *this;
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::capacity(), DCHECK_GE, v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::end_of_storage_, v8::base::SmallVector< T, kSize, Allocator >::FreeStorage(), v8::base::SmallVector< T, kSize, Allocator >::kHasTrivialElement, and v8::base::SmallVector< T, kSize, Allocator >::size().
operator[]() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T& v8::base::SmallVector< T, kSize, Allocator >::operator[] (size_t index) [inline]
Definition at line 171 of file small-vector.h.
                              {
    DCHECK_GT(size(), index);
    return begin_[index];
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, DCHECK_GT, v8::internal::index, and v8::base::SmallVector< T, kSize, Allocator >::size().
operator[]() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
const T& v8::base::SmallVector< T, kSize, Allocator >::operator[] (size_t index) const [inline]
Definition at line 181 of file small-vector.h.
{ return at(index); }
References v8::base::SmallVector< T, kSize, Allocator >::at(), and v8::internal::index.
pop_back()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
void v8::base::SmallVector< T, kSize, Allocator >::pop_back (size_t count = 1) [inline]
Definition at line 193 of file small-vector.h.
                                  {
    DCHECK_GE(size(), count);
    end_ -= count;
    std::destroy_n(end_, count);
  }
References DCHECK_GE, v8::base::SmallVector< T, kSize, Allocator >::end_, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddQuantifierToAtom(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::DirectHandleSmallVector< T, kSize >::pop_back(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping(), v8::internal::maglev::RegisterFrameState< v8::internal::DoubleRegister >::TryChooseInputRegister(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitAllBlocks().
push_back()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
void v8::base::SmallVector< T, kSize, Allocator >::push_back (T x) [inline]
Definition at line 191 of file small-vector.h.
{ emplace_back(std::move(x)); }
References v8::base::SmallVector< T, kSize, Allocator >::emplace_back().
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddArgumentsElements(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddArgumentsLength(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedObject(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedObjectReference(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedStringConcat(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedStringConcatReference(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddInput(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::LoopInfo::AddOutgoing(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddRestLength(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddUnusedRegister(), v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::wasm::WasmBytecodeGenerator::BeginBlock(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocation(), v8::internal::CalculateLineEndsImpl(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallForwardVarargs(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallWithSpread(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComputePredecessors(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::MapsAndHandlers::emplace_back(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FixLoopPhis(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTupleType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::LoadStrideEqualTo(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Phi(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffleOfShuffle(), v8::internal::wasm::PublishDetectedFeatures(), v8::internal::DirectHandleSmallVector< T, kSize >::push_back(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Return(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartMultiPredecessorExceptionBlock(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), v8::internal::maglev::BasicBlock::successors(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitAllBlocks(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody(), and v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >::WrapInTupleIfNeeded().
rbegin() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
auto v8::base::SmallVector< T, kSize, Allocator >::rbegin () [inline]
Definition at line 138 of file small-vector.h.
{ return std::make_reverse_iterator(end_); }
References v8::base::SmallVector< T, kSize, Allocator >::end_.
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::rbegin(), and v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors().
rbegin() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
auto v8::base::SmallVector< T, kSize, Allocator >::rbegin () const [inline]
Definition at line 139 of file small-vector.h.
{ return std::make_reverse_iterator(end_); }
References v8::base::SmallVector< T, kSize, Allocator >::end_.
rend() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
auto v8::base::SmallVector< T, kSize, Allocator >::rend () [inline]
Definition at line 141 of file small-vector.h.
{ return std::make_reverse_iterator(begin_); }
References v8::base::SmallVector< T, kSize, Allocator >::begin_.
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::rand(), v8::internal::DirectHandleSmallVector< T, kSize >::rend(), and v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors().
rend() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
auto v8::base::SmallVector< T, kSize, Allocator >::rend () const [inline]
Definition at line 142 of file small-vector.h.
{ return std::make_reverse_iterator(begin_); }
References v8::base::SmallVector< T, kSize, Allocator >::begin_.
reserve()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
void v8::base::SmallVector< T, kSize, Allocator >::reserve (size_t new_capacity) [inline]
Definition at line 269 of file small-vector.h.
                                    {
    if (new_capacity > capacity()) Grow(new_capacity);
  }
References v8::base::SmallVector< T, kSize, Allocator >::capacity(), and v8::base::SmallVector< T, kSize, Allocator >::Grow().
Referenced by v8::internal::String::CalculateLineEndsVector(), v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Phi(), and v8::internal::DirectHandleSmallVector< T, kSize >::reserve().
reset_to_inline_storage()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
void v8::base::SmallVector< T, kSize, Allocator >::reset_to_inline_storage () [inline], [private]
Definition at line 313 of file small-vector.h.
                                 {
    if constexpr (!kHasTrivialElement) {
      if (!is_big()) std::destroy_n(begin_, end_ - begin_);
    }
    begin_ = inline_storage_begin();
    end_ = begin_;
    end_of_storage_ = begin_ + kInlineSize;
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::end_of_storage_, v8::base::SmallVector< T, kSize, Allocator >::inline_storage_begin(), v8::base::SmallVector< T, kSize, Allocator >::is_big(), v8::base::SmallVector< T, kSize, Allocator >::kHasTrivialElement, and v8::base::SmallVector< T, kSize, Allocator >::kInlineSize.
resize() [1/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
void v8::base::SmallVector< T, kSize, Allocator >::resize (size_t new_size) [inline]
Definition at line 245 of file small-vector.h.
                               {
    if (new_size > capacity()) Grow(new_size);
    T* new_end = begin_ + new_size;
    if constexpr (!kHasTrivialElement) {
      if (new_end > end_) {
        std::uninitialized_default_construct(end_, new_end);
      } else {
        std::destroy_n(new_end, end_ - new_end);
      }
    }
    end_ = new_end;
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::capacity(), v8::base::SmallVector< T, kSize, Allocator >::end_, v8::base::SmallVector< T, kSize, Allocator >::Grow(), and v8::base::SmallVector< T, kSize, Allocator >::kHasTrivialElement.
Referenced by v8::internal::SmallStringOptimizedAllocator< kInlineSize >::allocate(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), v8::internal::compiler::turboshaft::CreateOperation(), v8::internal::anonymous_namespace{date.cc}::FormatDate(), v8::internal::SmallStringOptimizedAllocator< kInlineSize >::grow(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakePhiMaybePermuteInputs(), v8::internal::JsonParser< Char >::ParseJsonValue(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::DirectHandleSmallVector< T, kSize >::resize(), v8::base::SmallVector< T, kSize, Allocator >::SmallVector(), and v8::internal::compiler::Revectorizer::VectorizeTree().
resize() [2/2]
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
void v8::base::SmallVector< T, kSize, Allocator >::resize (size_t new_size, const T & initial_value) [inline]
Definition at line 258 of file small-vector.h.
                                                       {
    if (new_size > capacity()) Grow(new_size);
    T* new_end = begin_ + new_size;
    if (new_end > end_) {
      std::uninitialized_fill(end_, new_end, initial_value);
    } else {
      std::destroy_n(new_end, end_ - new_end);
    }
    end_ = new_end;
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, v8::base::SmallVector< T, kSize, Allocator >::capacity(), v8::base::SmallVector< T, kSize, Allocator >::end_, and v8::base::SmallVector< T, kSize, Allocator >::Grow().
size()
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
size_t v8::base::SmallVector< T, kSize, Allocator >::size () const [inline]
Definition at line 144 of file small-vector.h.
{ return end_ - begin_; }
References v8::base::SmallVector< T, kSize, Allocator >::begin_, and v8::base::SmallVector< T, kSize, Allocator >::end_.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::AddArgumentNodes(), v8::base::SmallVector< T, kSize, Allocator >::at(), v8::base::SmallVector< T, kSize, Allocator >::back(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocation(), v8::internal::String::CalculateLineEnds(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComputePredecessors(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::EmitSwitch(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushTerms(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::base::SmallVector< T, kSize, Allocator >::front(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::GeneratorStore(), v8::internal::anonymous_namespace{objects.cc}::GetLength(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::GetParam(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::internal::compiler::detail::GraphAssemblerHelper< kGraphAssemblerLabelDynamicCount >::InitNodeArray(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::internal::Builtins::InvokeApiFunction(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakePhiMaybePermuteInputs(), v8::base::SmallVector< T, kSize, Allocator >::operator=(), v8::base::SmallVector< T, kSize, Allocator >::operator[](), v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets(), v8::internal::wasm::WasmBytecodeGenerator::PatchLoopBeginInstructions(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushReturns(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::DirectHandleSmallVector< T, kSize >::size(), v8::base::SmallVector< T, kSize, Allocator >::SmallVector(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ToCanonicalZoneList(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::ToRegExp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), and v8::internal::IsolateSafepoint::Barrier::WaitUntilRunningThreadsInSafepoint().
Member Data Documentation
allocator_
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
V8_NO_UNIQUE_ADDRESS Allocator v8::base::SmallVector< T, kSize, Allocator >::allocator_ [private]
Definition at line 329 of file small-vector.h.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::AllocateDynamicStorage(), v8::base::SmallVector< T, kSize, Allocator >::FreeStorage(), and v8::base::SmallVector< T, kSize, Allocator >::get_allocator().
begin_
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::begin_ = inline_storage_begin() [private]
Definition at line 337 of file small-vector.h.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::at(), v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::base::SmallVector< T, kSize, Allocator >::capacity(), v8::base::SmallVector< T, kSize, Allocator >::clear(), v8::base::SmallVector< T, kSize, Allocator >::data(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::base::SmallVector< T, kSize, Allocator >::erase(), v8::base::SmallVector< T, kSize, Allocator >::FreeStorage(), v8::base::SmallVector< T, kSize, Allocator >::front(), v8::base::SmallVector< T, kSize, Allocator >::Grow(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::base::SmallVector< T, kSize, Allocator >::is_big(), v8::base::SmallVector< T, kSize, Allocator >::operator=(), v8::base::SmallVector< T, kSize, Allocator >::operator[](), v8::base::SmallVector< T, kSize, Allocator >::rend(), v8::base::SmallVector< T, kSize, Allocator >::reset_to_inline_storage(), v8::base::SmallVector< T, kSize, Allocator >::resize(), v8::base::SmallVector< T, kSize, Allocator >::size(), and v8::base::SmallVector< T, kSize, Allocator >::SmallVector().
end_
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::end_ = begin_ [private]
Definition at line 338 of file small-vector.h.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::back(), v8::base::SmallVector< T, kSize, Allocator >::clear(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::SmallVector< T, kSize, Allocator >::erase(), v8::base::SmallVector< T, kSize, Allocator >::FreeStorage(), v8::base::SmallVector< T, kSize, Allocator >::Grow(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::base::SmallVector< T, kSize, Allocator >::operator=(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), v8::base::SmallVector< T, kSize, Allocator >::rbegin(), v8::base::SmallVector< T, kSize, Allocator >::reset_to_inline_storage(), v8::base::SmallVector< T, kSize, Allocator >::resize(), v8::base::SmallVector< T, kSize, Allocator >::size(), and v8::base::SmallVector< T, kSize, Allocator >::SmallVector().
end_of_storage_
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
T* v8::base::SmallVector< T, kSize, Allocator >::end_of_storage_ = begin_ + kInlineSize [private]
Definition at line 339 of file small-vector.h.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::capacity(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::base::SmallVector< T, kSize, Allocator >::FreeStorage(), v8::base::SmallVector< T, kSize, Allocator >::Grow(), v8::base::SmallVector< T, kSize, Allocator >::operator=(), and v8::base::SmallVector< T, kSize, Allocator >::reset_to_inline_storage().
inline_storage_
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
char v8::base::SmallVector< T, kSize, Allocator >::inline_storage_[sizeof(T) *kInlineSize] [private]
Definition at line 340 of file small-vector.h.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::inline_storage_begin().
kHasTrivialElement
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
constexpr bool v8::base::SmallVector< T, kSize, Allocator >::kHasTrivialElement [static], [constexpr], [private]
Initial value:
=
      is_trivially_copyable<T>::value && is_trivially_destructible<T>::value
Definition at line 342 of file small-vector.h.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::operator=(), v8::base::SmallVector< T, kSize, Allocator >::reset_to_inline_storage(), and v8::base::SmallVector< T, kSize, Allocator >::resize().
kInlineSize
template<typename T , size_t kSize, typename Allocator = std::allocator<T>>
constexpr size_t v8::base::SmallVector< T, kSize, Allocator >::kInlineSize = kSize [static], [constexpr]
Definition at line 24 of file small-vector.h.
Referenced by v8::base::SmallVector< T, kSize, Allocator >::reset_to_inline_storage().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/small-vector.h