v8::StackFrame Class Reference
A single JavaScript stack frame.
#include <v8-debug.h>
Public Member Functions
Location GetLocation () const
Returns the source location, 0-based, for the associated function call.
int GetLineNumber () const
Returns the number, 1-based, of the line for the associate function call.
int GetColumn () const
Returns the 1-based column offset on the line for the associated function call.
int GetSourcePosition () const
Returns zero based source position (character offset) for the associated function.
int GetScriptId () const
Returns the id of the script for the function for this StackFrame.
Local< String > GetScriptName () const
Returns the name of the resource that contains the script for the function for this StackFrame.
Local< String > GetScriptNameOrSourceURL () const
Returns the name of the resource that contains the script for the function for this StackFrame or sourceURL value if the script name is undefined and its source ends with //# sourceURL=...
Local< String > GetScriptSource () const
Returns the source of the script for the function for this StackFrame.
Local< String > GetScriptSourceMappingURL () const
Returns the source mapping URL (if one is present) of the script for the function for this StackFrame.
Local< String > GetFunctionName () const
Returns the name of the function associated with this stack frame.
bool IsEval () const
Returns whether or not the associated function is compiled via a call to eval().
bool IsConstructor () const
Returns whether or not the associated function is called as a constructor via `new`.
bool IsWasm () const
Returns whether or not the associated functions is defined in wasm.
bool IsUserJavaScript () const
Returns whether or not the associated function is defined by the user.
Detailed Description
A single JavaScript stack frame.
Definition at line 21 of file v8-debug.h.
Member Function Documentation
GetColumn()
int v8::StackFrame::GetColumn () const [inline]
Returns the 1-based column offset on the line for the associated function call.
This method will return Message::kNoColumnInfo if it is unable to retrieve the column number, or if kColumnOffset was not passed as an option when capturing the StackTrace.
Definition at line 43 of file v8-debug.h.
{ return GetLocation().GetColumnNumber() + 1; }
References v8::Location::GetColumnNumber().
GetFunctionName()
Local< String > v8::StackFrame::GetFunctionName () const
Returns the name of the function associated with this stack frame.
Definition at line 3186 of file api.cc.
                                                {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DirectHandle<i::String> name(self->function_name(), i_isolate);
  if (name->length() == 0) return {};
  return Utils::ToLocal(name);
}
References v8::internal::Isolate::Current(), name, and v8::Utils::OpenDirectHandle().
GetLineNumber()
int v8::StackFrame::GetLineNumber () const [inline]
Returns the number, 1-based, of the line for the associate function call.
This method will return Message::kNoLineNumberInfo if it is unable to retrieve the line number, or if kLineNumber was not passed as an option when capturing the StackTrace.
Definition at line 34 of file v8-debug.h.
{ return GetLocation().GetLineNumber() + 1; }
References v8::Location::GetLineNumber().
GetLocation()
Location v8::StackFrame::GetLocation () const
Returns the source location, 0-based, for the associated function call.
Definition at line 3124 of file api.cc.
                                       {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DirectHandle<i::Script> script(self->script(), i_isolate);
  i::Script::PositionInfo info;
  CHECK(i::Script::GetPositionInfo(
      script, i::StackFrameInfo::GetSourcePosition(self), &info));
  if (script->HasSourceURLComment()) {
    info.line -= script->line_offset();
    if (info.line == 0) {
      info.column -= script->column_offset();
    }
  }
  return {info.line, info.column};
}
References CHECK, v8::internal::Isolate::Current(), v8::internal::Script::GetPositionInfo(), v8::internal::StackFrameInfo::GetSourcePosition(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
GetScriptId()
int v8::StackFrame::GetScriptId () const
Returns the id of the script for the function for this StackFrame.
This method will return Message::kNoScriptIdInfo if it is unable to retrieve the script id, or if kScriptId was not passed as an option when capturing the StackTrace.
Definition at line 3146 of file api.cc.
                                  {
  return Utils::OpenDirectHandle(this)->script()->id();
}
References v8::Utils::OpenDirectHandle().
GetScriptName()
Local< String > v8::StackFrame::GetScriptName () const
Returns the name of the resource that contains the script for the function for this StackFrame.
Definition at line 3150 of file api.cc.
                                              {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DirectHandle<i::Object> name(self->script()->name(), i_isolate);
  if (!IsString(*name)) return {};
  return Utils::ToLocal(i::Cast<i::String>(name));
}
References v8::internal::Isolate::Current(), name, and v8::Utils::OpenDirectHandle().
GetScriptNameOrSourceURL()
Local< String > v8::StackFrame::GetScriptNameOrSourceURL () const
Returns the name of the resource that contains the script for the function for this StackFrame or sourceURL value if the script name is undefined and its source ends with //# sourceURL=...
string or deprecated //@ sourceURL=... string.
Definition at line 3158 of file api.cc.
                                                         {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DirectHandle<i::Object> name_or_source_url(
      self->script()->GetNameOrSourceURL(), i_isolate);
  if (!IsString(*name_or_source_url)) return {};
  return Utils::ToLocal(i::Cast<i::String>(name_or_source_url));
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
GetScriptSource()
Local< String > v8::StackFrame::GetScriptSource () const
Returns the source of the script for the function for this StackFrame.
Definition at line 3167 of file api.cc.
                                                {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  if (!self->script()->HasValidSource()) return {};
  i::DirectHandle<i::PrimitiveHeapObject> source(self->script()->source(),
                                                 i_isolate);
  if (!IsString(*source)) return {};
  return Utils::ToLocal(i::Cast<i::String>(source));
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
GetScriptSourceMappingURL()
Local< String > v8::StackFrame::GetScriptSourceMappingURL () const
Returns the source mapping URL (if one is present) of the script for the function for this StackFrame.
Definition at line 3177 of file api.cc.
                                                          {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DirectHandle<i::Object> source_mapping_url(
      self->script()->source_mapping_url(), i_isolate);
  if (!IsString(*source_mapping_url)) return {};
  return Utils::ToLocal(i::Cast<i::String>(source_mapping_url));
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
GetSourcePosition()
int v8::StackFrame::GetSourcePosition () const
Returns zero based source position (character offset) for the associated function.
Definition at line 3140 of file api.cc.
                                        {
  auto self = Utils::OpenHandle(this);
  return i::StackFrameInfo::GetSourcePosition(self);
}
References v8::internal::StackFrameInfo::GetSourcePosition(), and v8::Utils::OpenHandle().
IsConstructor()
bool v8::StackFrame::IsConstructor () const
Returns whether or not the associated function is called as a constructor via `new`.
Definition at line 3200 of file api.cc.
                                     {
  return Utils::OpenDirectHandle(this)->is_constructor();
}
References v8::Utils::OpenDirectHandle().
IsEval()
bool v8::StackFrame::IsEval () const
Returns whether or not the associated function is compiled via a call to eval().
Definition at line 3194 of file api.cc.
                              {
  auto self = Utils::OpenDirectHandle(this);
  return self->script()->compilation_type() ==
         i::Script::CompilationType::kEval;
}
References v8::Utils::OpenDirectHandle().
IsUserJavaScript()
bool v8::StackFrame::IsUserJavaScript () const
Returns whether or not the associated function is defined by the user.
Definition at line 3206 of file api.cc.
                                        {
  return Utils::OpenDirectHandle(this)->script()->IsUserJavaScript();
}
References v8::Utils::OpenDirectHandle().
Referenced by IsWasm().
IsWasm()
bool v8::StackFrame::IsWasm () const
Returns whether or not the associated functions is defined in wasm.
Definition at line 3204 of file api.cc.
{ return !IsUserJavaScript(); }
References IsUserJavaScript().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-debug.h
/mnt/V8SourceCode/src/api/api.cc