v8::internal::SnapshotByteSource Class Reference
Source to read snapshot and builtins files from.
#include <snapshot-source-sink.h>
Public Member Functions
SnapshotByteSource (const char *data, int length)
SnapshotByteSource (base::Vector< const uint8_t > payload)
~SnapshotByteSource ()=default
SnapshotByteSource (const SnapshotByteSource &)=delete
SnapshotByteSource & operator= (const SnapshotByteSource &)=delete
bool HasMore ()
uint8_t Get ()
uint8_t Peek () const
void Advance (int by)
void CopyRaw (void *to, int number_of_bytes)
void CopySlots (Address *dest, int number_of_slots)
uint32_t GetUint30 ()
uint32_t GetUint32 ()
int GetBlob (const uint8_t **data)
int position () const
void set_position (int position)
const uint8_t * data () const
int length () const
Private Attributes
const uint8_t * data_
int length_
int position_
Detailed Description
Source to read snapshot and builtins files from.
Note: Memory ownership remains with callee.
Definition at line 25 of file snapshot-source-sink.h.
Constructor & Destructor Documentation
SnapshotByteSource() [1/3]
v8::internal::SnapshotByteSource::SnapshotByteSource (const char * data, int length) [inline]
Definition at line 27 of file snapshot-source-sink.h.
      : data_(reinterpret_cast<const uint8_t*>(data)),
        length_(length),
        position_(0) {}
SnapshotByteSource() [2/3]
v8::internal::SnapshotByteSource::SnapshotByteSource (base::Vector< const uint8_t > payload) [inline], [explicit]
Definition at line 32 of file snapshot-source-sink.h.
      : data_(payload.begin()), length_(payload.length()), position_(0) {}
 SnapshotByteSource()
v8::internal::SnapshotByteSource::~SnapshotByteSource () [default]
SnapshotByteSource() [3/3]
v8::internal::SnapshotByteSource::SnapshotByteSource (const SnapshotByteSource &) [delete]
Member Function Documentation
Advance()
void v8::internal::SnapshotByteSource::Advance (int by) [inline]
Definition at line 51 of file snapshot-source-sink.h.
{ position_ += by; }
References position_.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment(), GetBlob(), and GetUint30().
CopyRaw()
void v8::internal::SnapshotByteSource::CopyRaw (void * to, int number_of_bytes) [inline]
Definition at line 53 of file snapshot-source-sink.h.
                                              {
    DCHECK_LE(position_ + number_of_bytes, length_);
    memcpy(to, data_ + position_, number_of_bytes);
    position_ += number_of_bytes;
  }
References data_, DCHECK_LE, length_, and position_.
Referenced by v8::internal::ContextDeserializer::DeserializeApiWrapperFields(), v8::internal::ContextDeserializer::DeserializeEmbedderFields(), v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment(), and GetUint32().
CopySlots()
void v8::internal::SnapshotByteSource::CopySlots (Address * dest, int number_of_slots) [inline]
Definition at line 59 of file snapshot-source-sink.h.
                                                     {
    base::AtomicWord* start = reinterpret_cast<base::AtomicWord*>(dest);
    base::AtomicWord* end = start + number_of_slots;
    for (base::AtomicWord* p = start; p < end;
         ++p, position_ += sizeof(base::AtomicWord)) {
      base::AtomicWord val;
      memcpy(&val, data_ + position_, sizeof(base::AtomicWord));
      base::Relaxed_Store(p, val);
    }
  }
References data_, v8::internal::compiler::end(), position_, and v8::base::Relaxed_Store().
data()
const uint8_t* v8::internal::SnapshotByteSource::data () const [inline]
Definition at line 114 of file snapshot-source-sink.h.
{ return data_; }
References data_.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment(), and GetBlob().
Get()
uint8_t v8::internal::SnapshotByteSource::Get () [inline]
Definition at line 41 of file snapshot-source-sink.h.
                {
    DCHECK(position_ < length_);
    return data_[position_++];
  }
References data_, v8::internal::DCHECK(), length_, and position_.
Referenced by v8::internal::ContextDeserializer::DeserializeApiWrapperFields(), v8::internal::ContextDeserializer::DeserializeEmbedderFields(), v8::internal::ReadOnlyHeapImageDeserializer::DeserializeImpl(), and v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment().
GetBlob()
int v8::internal::SnapshotByteSource::GetBlob (const uint8_t ** data)
Definition at line 47 of file snapshot-source-sink.cc.
                                                    {
  int size = GetUint30();
  CHECK_LE(position_ + size, length_);
  *data = &data_[position_];
  Advance(size);
  return size;
}
References Advance(), CHECK_LE, data(), data_, GetUint30(), length_, position_, and size().
GetUint30()
uint32_t v8::internal::SnapshotByteSource::GetUint30 () [inline]
Definition at line 85 of file snapshot-source-sink.h.
                              {
    // This way of decoding variable-length encoded integers does not
    // suffer from branch mispredictions.
    DCHECK_LT(position_ + 3, length_);
    uint32_t answer = data_[position_];
    answer |= data_[position_ + 1] << 8;
    answer |= data_[position_ + 2] << 16;
    answer |= data_[position_ + 3] << 24;
    int bytes = (answer & 3) + 1;
    Advance(bytes);
    uint32_t mask = 0xffffffffu;
    mask >>= 32 - (bytes << 3);
    answer &= mask;
    answer >>= 2;
    return answer;
  }
References Advance(), data_, DCHECK_LT, length_, and position_.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::AllocatePage(), v8::internal::StartupDeserializer::DeserializeAndCheckExternalReferenceTable(), v8::internal::ContextDeserializer::DeserializeApiWrapperFields(), v8::internal::ContextDeserializer::DeserializeEmbedderFields(), v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment(), v8::internal::SharedHeapDeserializer::DeserializeStringTable(), and GetBlob().
GetUint32()
uint32_t v8::internal::SnapshotByteSource::GetUint32 () [inline]
Definition at line 102 of file snapshot-source-sink.h.
                       {
    uint32_t integer;
    CopyRaw(reinterpret_cast<uint8_t*>(&integer), sizeof(integer));
    return integer;
  }
References CopyRaw().
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::AllocatePage(), and v8::internal::ReadOnlyHeapImageDeserializer::DeserializeReadOnlyRootsTable().
HasMore()
bool v8::internal::SnapshotByteSource::HasMore () [inline]
Definition at line 39 of file snapshot-source-sink.h.
{ return position_ < length_; }
References length_, and position_.
length()
int v8::internal::SnapshotByteSource::length () const [inline]
Definition at line 115 of file snapshot-source-sink.h.
{ return length_; }
References length_.
Referenced by v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate(), and v8::internal::StartupDeserializer::DeserializeIntoIsolate().
operator=()
SnapshotByteSource& v8::internal::SnapshotByteSource::operator= (const SnapshotByteSource &) [delete]
Peek()
uint8_t v8::internal::SnapshotByteSource::Peek () const [inline]
Definition at line 46 of file snapshot-source-sink.h.
                       {
    DCHECK(position_ < length_);
    return data_[position_];
  }
References data_, v8::internal::DCHECK(), length_, and position_.
position()
int v8::internal::SnapshotByteSource::position () const [inline]
Definition at line 111 of file snapshot-source-sink.h.
{ return position_; }
References position_.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment(), and set_position().
set_position()
void v8::internal::SnapshotByteSource::set_position (int position) [inline]
Definition at line 112 of file snapshot-source-sink.h.
{ position_ = position; }
References position(), and position_.
Member Data Documentation
data_
const uint8_t* v8::internal::SnapshotByteSource::data_ [private]
Definition at line 118 of file snapshot-source-sink.h.
Referenced by CopyRaw(), CopySlots(), data(), Get(), GetBlob(), GetUint30(), and Peek().
length_
int v8::internal::SnapshotByteSource::length_ [private]
Definition at line 119 of file snapshot-source-sink.h.
Referenced by CopyRaw(), Get(), GetBlob(), GetUint30(), HasMore(), length(), and Peek().
position_
int v8::internal::SnapshotByteSource::position_ [private]
Definition at line 120 of file snapshot-source-sink.h.
Referenced by Advance(), CopyRaw(), CopySlots(), Get(), GetBlob(), GetUint30(), HasMore(), Peek(), position(), and set_position().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/snapshot-source-sink.h
/mnt/V8SourceCode/src/snapshot/snapshot-source-sink.cc