v8::internal::WasmTagObject Class Reference
#include <wasm-objects.h>
Public Member Functions
bool MatchesSignature (wasm::CanonicalTypeIndex expected_index)
Static Public Member Functions
static DirectHandle< WasmTagObject > New (Isolate *isolate, const wasm::FunctionSig *sig, wasm::CanonicalTypeIndex type_index, DirectHandle< HeapObject > tag, DirectHandle< WasmTrustedInstanceData > instance)
Detailed Description
Definition at line 759 of file wasm-objects.h.
Member Function Documentation
MatchesSignature()
bool v8::internal::WasmTagObject::MatchesSignature (wasm::CanonicalTypeIndex expected_index)
Definition at line 2411 of file wasm-objects.cc.
                                                                          {
  return wasm::CanonicalTypeIndex{static_cast<uint32_t>(
             this->canonical_type_index())} == expected_index;
}
New()
DirectHandle< WasmTagObject > v8::internal::WasmTagObject::New (Isolate * isolate, const wasm::FunctionSig * sig, wasm::CanonicalTypeIndex type_index, DirectHandle< HeapObject > tag, DirectHandle< WasmTrustedInstanceData > instance) [static]
Definition at line 2367 of file wasm-objects.cc.
                                                        {
  DirectHandle<JSFunction> tag_cons(
      isolate->native_context()->wasm_tag_constructor(), isolate);
  // Serialize the signature.
  DCHECK_EQ(0, sig->return_count());
  DCHECK_LE(sig->parameter_count(), std::numeric_limits<int>::max());
  int sig_size = static_cast<int>(sig->parameter_count());
  DirectHandle<PodArray<wasm::ValueType>> serialized_sig =
      PodArray<wasm::ValueType>::New(isolate, sig_size, AllocationType::kOld);
  int index = 0; // Index into the {PodArray} above.
  for (wasm::ValueType param : sig->parameters()) {
    serialized_sig->set(index++, param);
  }
  DirectHandle<JSObject> tag_object =
      isolate->factory()->NewJSObject(tag_cons, AllocationType::kOld);
  DirectHandle<WasmTagObject> tag_wrapper = Cast<WasmTagObject>(tag_object);
  tag_wrapper->set_serialized_signature(*serialized_sig);
  tag_wrapper->set_canonical_type_index(type_index.index);
  tag_wrapper->set_tag(*tag);
  if (!trusted_data.is_null()) {
    tag_wrapper->set_trusted_data(*trusted_data);
  } else {
    tag_wrapper->clear_trusted_data();
  }
  return tag_wrapper;
}
References DCHECK_EQ, DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::index, v8::internal::wasm::TypeIndex::index, v8::internal::DirectHandle< T >::is_null(), v8::internal::kOld, v8::internal::Isolate::native_context(), v8::internal::PodArray< T >::New(), v8::internal::Factory::NewJSObject(), and v8::internal::sig.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessExports(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc