v8::internal::maglev::CreateClosure Class Reference
#include <maglev-ir.h>
Public Member Functions
CreateClosure (uint64_t bitfield, compiler::SharedFunctionInfoRef shared_function_info, compiler::FeedbackCellRef feedback_cell, bool pretenured)
compiler::SharedFunctionInfoRef shared_function_info () const
compiler::FeedbackCellRef feedback_cell () const
bool pretenured () const
Input & context ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, CreateClosure >
Private Attributes
const compiler::SharedFunctionInfoRef shared_function_info_
const compiler::FeedbackCellRef feedback_cell_
const bool pretenured_
Additional Inherited Members
Detailed Description
Definition at line 6689 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CreateClosure::Base = FixedInputValueNodeT<1, CreateClosure> [private]
Definition at line 6690 of file maglev-ir.h.
Constructor & Destructor Documentation
CreateClosure()
v8::internal::maglev::CreateClosure::CreateClosure (uint64_t bitfield, compiler::SharedFunctionInfoRef shared_function_info, compiler::FeedbackCellRef feedback_cell, bool pretenured) [inline], [explicit]
Definition at line 6693 of file maglev-ir.h.
      : Base(bitfield),
        shared_function_info_(shared_function_info),
        feedback_cell_(feedback_cell),
        pretenured_(pretenured) {}
Member Function Documentation
context()
Input& v8::internal::maglev::CreateClosure::context () [inline]
Definition at line 6708 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback_cell()
compiler::FeedbackCellRef v8::internal::maglev::CreateClosure::feedback_cell () const [inline]
Definition at line 6705 of file maglev-ir.h.
{ return feedback_cell_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CreateClosure::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CreateClosure::MaxCallStackArgs () const
pretenured()
bool v8::internal::maglev::CreateClosure::pretenured () const [inline]
Definition at line 6706 of file maglev-ir.h.
{ return pretenured_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::CreateClosure::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7978 of file maglev-ir.cc.
                                                                           {
  os << "(" << *shared_function_info().object() << ", "
     << feedback_cell().object();
  if (pretenured()) {
    os << " [pretenured]";
  }
  os << ")";
}
References feedback_cell(), v8::internal::compiler::FeedbackCellRef::object(), v8::internal::compiler::SharedFunctionInfoRef::object(), pretenured(), and shared_function_info().
SetValueLocationConstraints()
void v8::internal::maglev::CreateClosure::SetValueLocationConstraints ()
shared_function_info()
compiler::SharedFunctionInfoRef v8::internal::maglev::CreateClosure::shared_function_info () const [inline]
Definition at line 6702 of file maglev-ir.h.
                                                             {
    return shared_function_info_;
  }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
feedback_cell_
const compiler::FeedbackCellRef v8::internal::maglev::CreateClosure::feedback_cell_ [private]
Definition at line 6724 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CreateClosure::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 6715 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CreateClosure::kProperties [static], [constexpr]
Initial value:
= OpProperties::Call() |
                                              OpProperties::CanAllocate() |
                                              OpProperties::NotIdempotent()
Definition at line 6711 of file maglev-ir.h.
pretenured_
const bool v8::internal::maglev::CreateClosure::pretenured_ [private]
Definition at line 6725 of file maglev-ir.h.
shared_function_info_
const compiler::SharedFunctionInfoRef v8::internal::maglev::CreateClosure::shared_function_info_ [private]
Definition at line 6723 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc