v8::internal::MemoryReducer::State Class Reference
#include <memory-reducer.h>
Public Member Functions
Id id () const
int started_gcs () const
double next_gc_start_ms () const
double last_gc_time_ms () const
size_t committed_memory_at_last_run () const
Static Public Member Functions
static State CreateUninitialized ()
static State CreateDone (double last_gc_time_ms, size_t committed_memory)
static State CreateWait (int started_gcs, double next_gc_time_ms, double last_gc_time_ms)
static State CreateRun (int started_gcs)
Private Member Functions
State (Id action, int started_gcs, double next_gc_start_ms, double last_gc_time_ms, size_t committed_memory_at_last_run)
Private Attributes
Id id_
int started_gcs_
double next_gc_start_ms_
double last_gc_time_ms_
size_t committed_memory_at_last_run_
Detailed Description
Definition at line 91 of file memory-reducer.h.
Constructor & Destructor Documentation
State()
v8::internal::MemoryReducer::State::State (Id action, int started_gcs, double next_gc_start_ms, double last_gc_time_ms, size_t committed_memory_at_last_run) [inline], [private]
Definition at line 131 of file memory-reducer.h.
        : id_(action),
          started_gcs_(started_gcs),
          next_gc_start_ms_(next_gc_start_ms),
          last_gc_time_ms_(last_gc_time_ms),
          committed_memory_at_last_run_(committed_memory_at_last_run) {}
Member Function Documentation
committed_memory_at_last_run()
size_t v8::internal::MemoryReducer::State::committed_memory_at_last_run () const [inline]
Definition at line 125 of file memory-reducer.h.
                                                {
      DCHECK(id() == kUninit || id() == kDone);
      return committed_memory_at_last_run_;
    }
References v8::internal::DCHECK().
Referenced by v8::internal::MemoryReducer::Step().
CreateDone()
static State v8::internal::MemoryReducer::State::CreateDone (double last_gc_time_ms, size_t committed_memory) [inline], [static]
Definition at line 95 of file memory-reducer.h.
                                                                             {
      return {kDone, 0, 0, last_gc_time_ms, committed_memory};
    }
Referenced by v8::internal::MemoryReducer::Step().
CreateRun()
static State v8::internal::MemoryReducer::State::CreateRun (int started_gcs) [inline], [static]
Definition at line 104 of file memory-reducer.h.
                                            {
      return {kRun, started_gcs, 0, 0, 0};
    }
Referenced by v8::internal::MemoryReducer::Step().
CreateUninitialized()
static State v8::internal::MemoryReducer::State::CreateUninitialized () [inline], [static]
Definition at line 93 of file memory-reducer.h.
{ return {kUninit, 0, 0, 0, 0}; }
Referenced by v8::internal::MemoryReducer::TearDown().
CreateWait()
static State v8::internal::MemoryReducer::State::CreateWait (int started_gcs, double next_gc_time_ms, double last_gc_time_ms) [inline], [static]
Definition at line 99 of file memory-reducer.h.
                                                    {
      return {kWait, started_gcs, next_gc_time_ms, last_gc_time_ms, 0};
    }
Referenced by v8::internal::MemoryReducer::Step().
id()
Id v8::internal::MemoryReducer::State::id () const [inline]
Definition at line 108 of file memory-reducer.h.
{ return id_; }
Referenced by v8::internal::MemoryReducer::NotifyMarkCompact(), v8::internal::MemoryReducer::NotifyPossibleGarbage(), v8::internal::MemoryReducer::NotifyTimer(), and v8::internal::MemoryReducer::Step().
last_gc_time_ms()
double v8::internal::MemoryReducer::State::last_gc_time_ms () const [inline]
Definition at line 120 of file memory-reducer.h.
                                   {
      DCHECK(id() == kWait || id() == kDone || id() == kUninit);
      return last_gc_time_ms_;
    }
References v8::internal::DCHECK().
Referenced by v8::internal::MemoryReducer::Step(), and v8::internal::MemoryReducer::WatchdogGC().
next_gc_start_ms()
double v8::internal::MemoryReducer::State::next_gc_start_ms () const [inline]
Definition at line 115 of file memory-reducer.h.
                                    {
      DCHECK_EQ(id(), kWait);
      return next_gc_start_ms_;
    }
References DCHECK_EQ.
Referenced by v8::internal::MemoryReducer::NotifyMarkCompact(), v8::internal::MemoryReducer::NotifyPossibleGarbage(), v8::internal::MemoryReducer::NotifyTimer(), and v8::internal::MemoryReducer::Step().
started_gcs()
int v8::internal::MemoryReducer::State::started_gcs () const [inline]
Definition at line 110 of file memory-reducer.h.
                            {
      DCHECK(id() == kWait || id() == kRun);
      return started_gcs_;
    }
References v8::internal::DCHECK().
Referenced by v8::internal::MemoryReducer::NotifyMarkCompact(), v8::internal::MemoryReducer::NotifyTimer(), and v8::internal::MemoryReducer::Step().
Member Data Documentation
committed_memory_at_last_run_
size_t v8::internal::MemoryReducer::State::committed_memory_at_last_run_ [private]
Definition at line 143 of file memory-reducer.h.
id_
Id v8::internal::MemoryReducer::State::id_ [private]
Definition at line 139 of file memory-reducer.h.
last_gc_time_ms_
double v8::internal::MemoryReducer::State::last_gc_time_ms_ [private]
Definition at line 142 of file memory-reducer.h.
next_gc_start_ms_
double v8::internal::MemoryReducer::State::next_gc_start_ms_ [private]
Definition at line 141 of file memory-reducer.h.
started_gcs_
int v8::internal::MemoryReducer::State::started_gcs_ [private]
Definition at line 140 of file memory-reducer.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/memory-reducer.h