v8::internal::DataHandler Class Reference
#include <data-handler.h>
Classes
class BodyDescriptor
Public Member Functions
Tagged< UnionOf< Smi, Code > > smi_handler () const
void set_smi_handler (Tagged< Smi > value)
void set_smi_handler (Tagged< Code > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< UnionOf< Smi, Cell > > validity_cell () const
void set_validity_cell (Tagged< UnionOf< Smi, Cell >> value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
int data_field_count () const
Tagged< MaybeObject > data1 () const
void set_data1 (Tagged< MaybeObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< MaybeObject > data2 () const
void set_data2 (Tagged< MaybeObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< MaybeObject > data3 () const
void set_data3 (Tagged< MaybeObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Static Public Member Functions
static constexpr int OffsetOf (int index)
static constexpr int SizeFor (int count)
Private Member Functions
FLEXIBLE_ARRAY_MEMBER (TaggedMember< MaybeObject >, data)
Private Attributes
TaggedMember< UnionOf< Smi, Code > > smi_handler_
TaggedMember< UnionOf< Smi, Cell > > validity_cell_
Friends
class AccessorAssembler
Additional Inherited Members
Detailed Description
Definition at line 21 of file data-handler.h.
Member Function Documentation
data1()
Tagged< MaybeObject > v8::internal::DataHandler::data1 () const [inline]
Definition at line 58 of file data-handler-inl.h.
                                                    {
  DCHECK_GT(data_field_count(), 0);
  return data()[0].load();
}
References data_field_count(), and DCHECK_GT.
Referenced by v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::LoadHandler::LoadFullChain(), v8::internal::LoadHandler::LoadNonExistent(), and v8::internal::StoreHandler::StoreThroughPrototype().
data2()
Tagged< MaybeObject > v8::internal::DataHandler::data2 () const [inline]
Definition at line 68 of file data-handler-inl.h.
                                                    {
  DCHECK_GT(data_field_count(), 1);
  return data()[1].load();
}
References data_field_count(), and DCHECK_GT.
data3()
Tagged< MaybeObject > v8::internal::DataHandler::data3 () const [inline]
Definition at line 78 of file data-handler-inl.h.
                                                    {
  DCHECK_GT(data_field_count(), 2);
  return data()[2].load();
}
References data_field_count(), and DCHECK_GT.
data_field_count()
int v8::internal::DataHandler::data_field_count () const [inline]
Definition at line 53 of file data-handler-inl.h.
                                               {
  return (map()->instance_size() - OFFSET_OF_DATA_START(DataHandler)) /
         sizeof(data()[0]);
}
References v8::internal::HeapObjectLayout::map(), and OFFSET_OF_DATA_START.
Referenced by data1(), data2(), data3(), set_data1(), set_data2(), and set_data3().
FLEXIBLE_ARRAY_MEMBER()
v8::internal::DataHandler::FLEXIBLE_ARRAY_MEMBER (TaggedMember< MaybeObject > , data) [private]
OffsetOf()
constexpr int v8::internal::DataHandler::OffsetOf (int index) [static], [constexpr]
Definition at line 24 of file data-handler-inl.h.
                                             {
  return OFFSET_OF_DATA_START(DataHandler) +
         index * sizeof(DataHandler::FlexibleDataType);
}
References v8::internal::index, and OFFSET_OF_DATA_START.
Referenced by v8::internal::AccessorAssembler::LoadHandlerDataField().
set_data1()
void v8::internal::DataHandler::set_data1 (Tagged< MaybeObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 62 of file data-handler-inl.h.
                                                          {
  DCHECK_GT(data_field_count(), 0);
  data()[0].store(this, value, mode);
}
References data_field_count(), DCHECK_GT, mode(), and v8::internal::value.
set_data2()
void v8::internal::DataHandler::set_data2 (Tagged< MaybeObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 72 of file data-handler-inl.h.
                                                          {
  DCHECK_GT(data_field_count(), 1);
  data()[1].store(this, value, mode);
}
References data_field_count(), DCHECK_GT, mode(), and v8::internal::value.
set_data3()
void v8::internal::DataHandler::set_data3 (Tagged< MaybeObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 82 of file data-handler-inl.h.
                                                          {
  DCHECK_GT(data_field_count(), 2);
  data()[2].store(this, value, mode);
}
References data_field_count(), DCHECK_GT, mode(), and v8::internal::value.
set_smi_handler() [1/2]
void v8::internal::DataHandler::set_smi_handler (Tagged< Code > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 40 of file data-handler-inl.h.
                                                                {
  smi_handler_.store(this, value, UPDATE_WRITE_BARRIER);
}
References smi_handler_, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
set_smi_handler() [2/2]
void v8::internal::DataHandler::set_smi_handler (Tagged< Smi > value) [inline]
Definition at line 37 of file data-handler-inl.h.
                                                          {
  smi_handler_.store(this, value, SKIP_WRITE_BARRIER);
}
References v8::internal::SKIP_WRITE_BARRIER, smi_handler_, and v8::internal::value.
set_validity_cell()
void v8::internal::DataHandler::set_validity_cell (Tagged< UnionOf< Smi, Cell >> value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 48 of file data-handler-inl.h.
                                                                  {
  validity_cell_.store(this, value, mode);
}
References mode(), validity_cell_, and v8::internal::value.
SizeFor()
constexpr int v8::internal::DataHandler::SizeFor (int count) [static], [constexpr]
Definition at line 29 of file data-handler-inl.h.
                                            {
  return OFFSET_OF_DATA_START(DataHandler) +
         count * sizeof(DataHandler::FlexibleDataType);
}
References OFFSET_OF_DATA_START.
Referenced by v8::internal::AccessorAssembler::LoadHandlerDataField().
smi_handler()
Tagged< UnionOf< Smi, Code > > v8::internal::DataHandler::smi_handler () const [inline]
Definition at line 34 of file data-handler-inl.h.
                                                                 {
  return smi_handler_.load();
}
References smi_handler_.
Referenced by v8::internal::LoadHandler::GetHandlerKind(), v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::LoadHandler::LoadFullChain(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::StoreHandler::StoreProxy(), and v8::internal::StoreHandler::StoreThroughPrototype().
validity_cell()
Tagged< UnionOf< Smi, Cell > > v8::internal::DataHandler::validity_cell () const [inline]
Definition at line 45 of file data-handler-inl.h.
                                                                   {
  return validity_cell_.load();
}
References validity_cell_.
Referenced by v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::LoadHandler::LoadFullChain(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::StoreHandler::StoreElementTransition(), v8::internal::StoreHandler::StoreThroughPrototype(), and v8::internal::StoreHandler::StoreTransition().
Friends And Related Function Documentation
AccessorAssembler
friend class AccessorAssembler [friend]
Definition at line 61 of file data-handler.h.
Member Data Documentation
smi_handler_
TaggedMember<UnionOf<Smi, Code> > v8::internal::DataHandler::smi_handler_ [private]
Definition at line 63 of file data-handler.h.
Referenced by v8::internal::DataHandler::BodyDescriptor::IterateBody(), set_smi_handler(), and smi_handler().
validity_cell_
TaggedMember<UnionOf<Smi, Cell> > v8::internal::DataHandler::validity_cell_ [private]
Definition at line 64 of file data-handler.h.
Referenced by set_validity_cell(), and validity_cell().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/data-handler.h
/mnt/V8SourceCode/src/objects/data-handler-inl.h