v8::bigint::Digits Class Reference
#include <bigint.h>
Public Member Functions
Digits (const digit_t *mem, int len)
Digits (digit_t *mem, int len)
Digits (Digits src, int offset, int len)
Digits ()
Digits operator+ (int i)
digit_t operator[] (int i)
digit_t msd ()
bool operator== (const Digits &other) const
void Normalize ()
void TrimOne ()
int len ()
const digit_t * digits () const
Protected Attributes
digit_t * digits_
int len_
Private Member Functions
digit_t read_4byte_aligned (int i)
Friends
class ShiftedDigits
Detailed Description
Definition at line 57 of file bigint.h.
Constructor & Destructor Documentation
Digits() [1/4]
v8::bigint::Digits::Digits (const digit_t * mem, int len) [inline]
Definition at line 60 of file bigint.h.
      : Digits(const_cast<digit_t*>(mem), len) {}
Digits() [2/4]
v8::bigint::Digits::Digits (digit_t * mem, int len) [inline]
Definition at line 66 of file bigint.h.
                                : digits_(mem), len_(len) {
    // Require 4-byte alignment (even on 64-bit platforms).
    // TODO(jkummerow): See if we can tighten BigInt alignment in V8 to
    // system pointer size, and raise this requirement to that.
    BIGINT_H_DCHECK((reinterpret_cast<uintptr_t>(mem) & 3) == 0);
  }
References BIGINT_H_DCHECK.
Digits() [3/4]
v8::bigint::Digits::Digits (Digits src, int offset, int len) [inline]
Definition at line 74 of file bigint.h.
      : digits_(src.digits_ + offset),
        len_(std::max(0, std::min(src.len_ - offset, len))) {
    BIGINT_H_DCHECK(offset >= 0);
  }
References BIGINT_H_DCHECK.
Digits() [4/4]
v8::bigint::Digits::Digits () [inline]
Definition at line 80 of file bigint.h.
: Digits(static_cast<digit_t*>(nullptr), 0) {}
Referenced by operator+().
Member Function Documentation
digits()
const digit_t* v8::bigint::Digits::digits () const [inline]
Definition at line 114 of file bigint.h.
{ return digits_; }
References digits_.
Referenced by v8::bigint::ShiftedDigits::ShiftedDigits().
len()
int v8::bigint::Digits::len () [inline]
Definition at line 113 of file bigint.h.
{ return len_; }
References len_.
Referenced by v8::bigint::Add(), v8::bigint::AddAndReturnCarry(), v8::bigint::AddAndReturnOverflow(), v8::bigint::AddOne(), v8::bigint::BitwiseAnd_NegNeg(), v8::bigint::BitwiseAnd_PosNeg(), v8::bigint::BitwiseAnd_PosPos(), v8::bigint::BitwiseOr_NegNeg(), v8::bigint::BitwiseOr_PosNeg(), v8::bigint::BitwiseOr_PosPos(), v8::bigint::BitwiseXor_NegNeg(), v8::bigint::BitwiseXor_PosNeg(), v8::bigint::BitwiseXor_PosPos(), v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::Classic(), v8::bigint::anonymous_namespace{div-helpers.cc}::Copy(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D2n1n(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n(), v8::bigint::ProcessorImpl::Divide(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::DivideBasecase(), v8::bigint::ProcessorImpl::DivideBurnikelZiegler(), v8::bigint::anonymous_namespace{tostring.cc}::DivideByMagic(), v8::bigint::ProcessorImpl::DivideSchoolbook(), v8::bigint::ProcessorImpl::DivideSingle(), v8::bigint::ProcessorImpl::FromString(), v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo(), v8::bigint::ProcessorImpl::FromStringClassic(), v8::bigint::ProcessorImpl::FromStringLarge(), v8::bigint::ProcessorImpl::KaratsubaChunk(), v8::bigint::ProcessorImpl::KaratsubaMain(), v8::bigint::ProcessorImpl::KaratsubaStart(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaSubtractionHelper(), v8::bigint::LeftShift(), v8::bigint::ProcessorImpl::Modulo(), v8::bigint::ProcessorImpl::Multiply(), v8::bigint::ProcessorImpl::MultiplyKaratsuba(), v8::bigint::MultiplyResultLength(), v8::bigint::ProcessorImpl::MultiplySchoolbook(), v8::bigint::ProcessorImpl::MultiplySingle(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::NormalizeAndRecombine(), v8::bigint::RightShift(), v8::bigint::RWDigits::set_len(), v8::bigint::SubAndReturnBorrow(), v8::bigint::Subtract(), v8::bigint::SubtractAndReturnBorrow(), and v8::bigint::SubtractOne().
msd()
digit_t v8::bigint::Digits::msd () [inline]
Definition at line 94 of file bigint.h.
                {
    BIGINT_H_DCHECK(len_ > 0);
    return read_4byte_aligned(len_ - 1);
  }
References BIGINT_H_DCHECK, len_, and read_4byte_aligned().
Referenced by Normalize(), v8::bigint::ShiftedDigits::ShiftedDigits(), and TrimOne().
Normalize()
void v8::bigint::Digits::Normalize () [inline]
Definition at line 104 of file bigint.h.
                   {
    while (len_ > 0 && msd() == 0) len_--;
  }
References len_, and msd().
Referenced by v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::Classic(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n(), v8::bigint::ProcessorImpl::DivideBurnikelZiegler(), v8::bigint::ProcessorImpl::KaratsubaChunk(), v8::bigint::ProcessorImpl::KaratsubaMain(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaSubtractionHelper(), v8::bigint::ProcessorImpl::Multiply(), and v8::bigint::Subtract().
operator+()
Digits v8::bigint::Digits::operator+ (int i) [inline]
Definition at line 83 of file bigint.h.
                          {
    BIGINT_H_DCHECK(i >= 0 && i <= len_);
    return Digits(digits_ + i, len_ - i);
  }
References BIGINT_H_DCHECK, Digits(), digits_, and len_.
operator==()
bool v8::bigint::Digits::operator== (const Digits & other) const [inline]
Definition at line 99 of file bigint.h.
                                             {
    return digits_ == other.digits_ && len_ == other.len_;
  }
References digits_, and len_.
operator[]()
digit_t v8::bigint::Digits::operator[] (int i) [inline]
Definition at line 89 of file bigint.h.
                            {
    BIGINT_H_DCHECK(i >= 0 && i < len_);
    return read_4byte_aligned(i);
  }
References BIGINT_H_DCHECK, len_, and read_4byte_aligned().
read_4byte_aligned()
digit_t v8::bigint::Digits::read_4byte_aligned (int i) [inline], [private]
Definition at line 125 of file bigint.h.
                                    {
    if (sizeof(digit_t) == 4) {
      return digits_[i];
    } else {
      digit_t result;
      memcpy(&result, static_cast<const void*>(digits_ + i), sizeof(result));
      return result;
    }
  }
References digits_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::internal::result.
Referenced by msd(), and operator[]().
TrimOne()
void v8::bigint::Digits::TrimOne () [inline]
Definition at line 108 of file bigint.h.
                 {
    BIGINT_H_DCHECK(len_ > 0 && msd() == 0);
    len_--;
  }
References BIGINT_H_DCHECK, len_, and msd().
Friends And Related Function Documentation
ShiftedDigits
friend class ShiftedDigits [friend]
Definition at line 117 of file bigint.h.
Member Data Documentation
digits_
digit_t* v8::bigint::Digits::digits_ [protected]
Definition at line 118 of file bigint.h.
Referenced by v8::bigint::RWDigits::Clear(), v8::bigint::RWDigits::digits(), digits(), operator+(), v8::bigint::RWDigits::operator+(), operator==(), v8::bigint::RWDigits::operator[](), read_4byte_aligned(), v8::bigint::ShiftedDigits::Reset(), v8::bigint::ScratchDigits::ScratchDigits(), and v8::bigint::ShiftedDigits::ShiftedDigits().
len_
int v8::bigint::Digits::len_ [protected]
Definition at line 119 of file bigint.h.
Referenced by v8::bigint::RWDigits::Clear(), len(), msd(), Normalize(), operator+(), v8::bigint::RWDigits::operator+(), operator==(), operator[](), v8::bigint::RWDigits::operator[](), v8::bigint::ShiftedDigits::Reset(), v8::bigint::RWDigits::set_len(), v8::bigint::ShiftedDigits::ShiftedDigits(), and TrimOne().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/bigint/bigint.h