v8::internal::maglev::TestInstanceOf Class Reference
#include <maglev-ir.h>
Public Member Functions
TestInstanceOf (uint64_t bitfield, const compiler::FeedbackSource &feedback)
Input & context ()
Input & object ()
Input & callable ()
const compiler::FeedbackSource & feedback () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 3, TestInstanceOf >
Private Attributes
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 5041 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TestInstanceOf::Base = FixedInputValueNodeT<3, TestInstanceOf> [private]
Definition at line 5042 of file maglev-ir.h.
Constructor & Destructor Documentation
TestInstanceOf()
v8::internal::maglev::TestInstanceOf::TestInstanceOf (uint64_t bitfield, const compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 5045 of file maglev-ir.h.
      : Base(bitfield), feedback_(feedback) {}
Member Function Documentation
callable()
Input& v8::internal::maglev::TestInstanceOf::callable () [inline]
Definition at line 5057 of file maglev-ir.h.
{ return input(2); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context()
Input& v8::internal::maglev::TestInstanceOf::context () [inline]
Definition at line 5055 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
const compiler::FeedbackSource& v8::internal::maglev::TestInstanceOf::feedback () const [inline]
Definition at line 5058 of file maglev-ir.h.
{ return feedback_; }
References feedback_.
GenerateCode()
void v8::internal::maglev::TestInstanceOf::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::TestInstanceOf::MaxCallStackArgs () const
object()
Input& v8::internal::maglev::TestInstanceOf::object () [inline]
Definition at line 5056 of file maglev-ir.h.
{ return input(1); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::TestInstanceOf::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5063 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::TestInstanceOf::SetValueLocationConstraints ()
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::TestInstanceOf::feedback_ [private]
Definition at line 5066 of file maglev-ir.h.
Referenced by feedback().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::TestInstanceOf::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged}
Definition at line 5051 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::TestInstanceOf::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 5050 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h