v8::internal::UnreachableObjectsFilter Class Reference
Classes
class MarkingVisitor
Public Member Functions
UnreachableObjectsFilter (Heap *heap)
~UnreachableObjectsFilter () override=default
bool SkipObject (Tagged< HeapObject > object) override
Private Types
using BucketType = std::unordered_set< Tagged< HeapObject >, Object::Hasher >
Private Member Functions
bool MarkAsReachable (Tagged< HeapObject > object)
void MarkReachableObjects ()
Private Attributes
Heap * heap_
std::unordered_map< MemoryChunkMetadata *, std::unique_ptr< BucketType >, base::hash< MemoryChunkMetadata * > > reachable_
Friends
class MarkingVisitor
Detailed Description
Definition at line 6691 of file heap.cc.
Member Typedef Documentation
BucketType
using v8::internal::UnreachableObjectsFilter::BucketType = std::unordered_set<Tagged<HeapObject>, Object::Hasher> [private]
Definition at line 6710 of file heap.cc.
Constructor & Destructor Documentation
UnreachableObjectsFilter()
v8::internal::UnreachableObjectsFilter::UnreachableObjectsFilter (Heap * heap) [inline], [explicit]
Definition at line 6693 of file heap.cc.
                                                : heap_(heap) {
    MarkReachableObjects();
  }
References MarkReachableObjects().
 UnreachableObjectsFilter()
v8::internal::UnreachableObjectsFilter::~UnreachableObjectsFilter () [override], [default]
Member Function Documentation
MarkAsReachable()
bool v8::internal::UnreachableObjectsFilter::MarkAsReachable (Tagged< HeapObject > object) [inline], [private]
Definition at line 6712 of file heap.cc.
                                                  {
    // If the bucket corresponding to the object's chunk does not exist, then
    // create an empty bucket.
    MemoryChunkMetadata* chunk = MemoryChunkMetadata::FromHeapObject(object);
    if (reachable_.count(chunk) == 0) {
      reachable_[chunk] = std::make_unique<BucketType>();
    }
    // Insert the object if not present; return whether it was indeed inserted.
    if (reachable_[chunk]->count(object)) return false;
    reachable_[chunk]->insert(object);
    return true;
  }
References v8::internal::MemoryChunkMetadata::FromHeapObject(), and reachable_.
Referenced by v8::internal::UnreachableObjectsFilter::MarkingVisitor::MarkHeapObject().
MarkReachableObjects()
void v8::internal::UnreachableObjectsFilter::MarkReachableObjects () [inline], [private]
Definition at line 6809 of file heap.cc.
                              {
    MarkingVisitor visitor(this);
    heap_->stack().SetMarkerIfNeededAndCallback(
        [this, &visitor]() { heap_->IterateRoots(&visitor, {}); });
    visitor.TransitiveClosure();
  }
References heap_, v8::internal::Heap::IterateRoots(), heap::base::Stack::SetMarkerIfNeededAndCallback(), v8::internal::Heap::stack(), and v8::internal::UnreachableObjectsFilter::MarkingVisitor::TransitiveClosure().
Referenced by UnreachableObjectsFilter().
SkipObject()
bool v8::internal::UnreachableObjectsFilter::SkipObject (Tagged< HeapObject > object) [inline], [override], [virtual]
Implements v8::internal::HeapObjectsFilter.
Definition at line 6699 of file heap.cc.
                                                      {
    // Space object iterators should skip free space or filler objects.
    DCHECK(!IsFreeSpaceOrFiller(object));
    // If the bucket corresponding to the object's chunk does not exist, or the
    // object is not found in the bucket, return true.
    MemoryChunkMetadata* chunk = MemoryChunkMetadata::FromHeapObject(object);
    if (reachable_.count(chunk) == 0) return true;
    return reachable_[chunk]->count(object) == 0;
  }
References v8::internal::DCHECK(), v8::internal::MemoryChunkMetadata::FromHeapObject(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), and reachable_.
Friends And Related Function Documentation
MarkingVisitor
friend class MarkingVisitor [friend]
Definition at line 6807 of file heap.cc.
Member Data Documentation
heap_
Heap* v8::internal::UnreachableObjectsFilter::heap_ [private]
Definition at line 6816 of file heap.cc.
Referenced by MarkReachableObjects(), and v8::internal::UnreachableObjectsFilter::MarkingVisitor::TransitiveClosure().
reachable_
std::unordered_map<MemoryChunkMetadata*, std::unique_ptr<BucketType>, base::hash<MemoryChunkMetadata*> > v8::internal::UnreachableObjectsFilter::reachable_ [private]
Definition at line 6820 of file heap.cc.
Referenced by MarkAsReachable(), and SkipObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/heap.cc