v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType > Class Template Reference
#include <declarable.h>
Public Types
using iterator = typename Map::const_iterator
Public Member Functions
void AddSpecialization (const TypeVector &type_arguments, SpecializationType specialization)
std::optional< SpecializationType > GetSpecialization (const TypeVector &type_arguments) const
iterator begin () const
iterator end () const
const std::string & name () const
auto declaration () const
const GenericParameters & generic_parameters () const
const std::vector< TypeConstraint > & Constraints ()
Protected Member Functions
GenericDeclarable (Declarable::Kind kind, const std::string &name, DeclarationType generic_declaration)
Private Types
using Map = std::unordered_map< TypeVector, SpecializationType, base::hash< TypeVector > >
Private Attributes
std::string name_
DeclarationType generic_declaration_
Map specializations_
std::optional< std::vector< TypeConstraint > > constraints_
Detailed Description
template<class SpecializationType, class DeclarationType>
class v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >
Definition at line 583 of file declarable.h.
Member Typedef Documentation
iterator
template<class SpecializationType , class DeclarationType >
using v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::iterator = typename Map::const_iterator
Definition at line 605 of file declarable.h.
Map
template<class SpecializationType , class DeclarationType >
using v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::Map = std::unordered_map<TypeVector, SpecializationType, base::hash<TypeVector> > [private]
Definition at line 585 of file declarable.h.
Constructor & Destructor Documentation
GenericDeclarable()
template<class SpecializationType , class DeclarationType >
v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::GenericDeclarable (Declarable::Kind kind, const std::string & name, DeclarationType generic_declaration) [inline], [protected]
Definition at line 622 of file declarable.h.
      : Declarable(kind),
        name_(name),
        generic_declaration_(generic_declaration) {
    DCHECK(!generic_declaration->generic_parameters.empty());
  }
References v8::internal::DCHECK().
Member Function Documentation
AddSpecialization()
template<class SpecializationType , class DeclarationType >
void v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::AddSpecialization (const TypeVector & type_arguments, SpecializationType specialization) [inline]
Definition at line 589 of file declarable.h.
                                                            {
    DCHECK_EQ(0, specializations_.count(type_arguments));
    if (auto violation =
            FindConstraintViolation(type_arguments, Constraints())) {
      Error(*violation).Throw();
    }
    specializations_[type_arguments] = specialization;
  }
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::Constraints(), DCHECK_EQ, v8::internal::torque::Error(), v8::internal::torque::FindConstraintViolation(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::specializations_, and v8::internal::torque::MessageBuilder::Throw().
Referenced by v8::internal::torque::TypeOracle::GetGenericTypeInstance().
begin()
template<class SpecializationType , class DeclarationType >
iterator v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::begin () const [inline]
Definition at line 606 of file declarable.h.
{ return specializations_.begin(); }
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::specializations_.
Constraints()
template<class SpecializationType , class DeclarationType >
const std::vector<TypeConstraint>& v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::Constraints () [inline]
Definition at line 615 of file declarable.h.
                                                 {
    if (!constraints_)
      constraints_ = {ComputeConstraints(ParentScope(), generic_parameters())};
    return *constraints_;
  }
References v8::internal::torque::ComputeConstraints(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::constraints_, v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::generic_parameters(), and v8::internal::torque::Declarable::ParentScope().
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::AddSpecialization().
declaration()
template<class SpecializationType , class DeclarationType >
auto v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::declaration () const [inline]
Definition at line 610 of file declarable.h.
{ return generic_declaration_->declaration; }
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::generic_declaration_.
Referenced by v8::internal::torque::TypeOracle::GetGenericTypeInstance(), and v8::internal::torque::DeclarationVisitor::Visit().
end()
template<class SpecializationType , class DeclarationType >
iterator v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::end () const [inline]
Definition at line 607 of file declarable.h.
{ return specializations_.end(); }
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::specializations_.
generic_parameters()
template<class SpecializationType , class DeclarationType >
const GenericParameters& v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::generic_parameters () const [inline]
Definition at line 611 of file declarable.h.
                                                      {
    return generic_declaration_->generic_parameters;
  }
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::generic_declaration_.
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::Constraints(), v8::internal::torque::TypeOracle::GetGenericTypeInstance(), and v8::internal::torque::operator<<().
GetSpecialization()
template<class SpecializationType , class DeclarationType >
std::optional<SpecializationType> v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::GetSpecialization (const TypeVector & type_arguments) const [inline]
Definition at line 598 of file declarable.h.
                                              {
    auto it = specializations_.find(type_arguments);
    if (it != specializations_.end()) return it->second;
    return std::nullopt;
  }
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::specializations_.
Referenced by v8::internal::torque::TypeOracle::GetGenericTypeInstance().
name()
template<class SpecializationType , class DeclarationType >
const std::string& v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::name () const [inline]
Definition at line 609 of file declarable.h.
{ return name_; }
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::name_.
Referenced by v8::internal::torque::operator<<().
Member Data Documentation
constraints_
template<class SpecializationType , class DeclarationType >
std::optional<std::vector<TypeConstraint> > v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::constraints_ [private]
Definition at line 634 of file declarable.h.
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::Constraints().
generic_declaration_
template<class SpecializationType , class DeclarationType >
DeclarationType v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::generic_declaration_ [private]
Definition at line 632 of file declarable.h.
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::declaration(), and v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::generic_parameters().
name_
template<class SpecializationType , class DeclarationType >
std::string v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::name_ [private]
Definition at line 631 of file declarable.h.
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::name().
specializations_
template<class SpecializationType , class DeclarationType >
Map v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::specializations_ [private]
Definition at line 633 of file declarable.h.
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::AddSpecialization(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::begin(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::end(), and v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::GetSpecialization().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h