v8::String Class Reference
A JavaScript string value (ECMA-262, 4.3.17).
#include <v8-primitive.h>
Classes
class ExternalOneByteStringResource
An ExternalOneByteStringResource is a wrapper around an one-byte string buffer that resides outside V8's heap.
class ExternalStringResource
An ExternalStringResource is a wrapper around a two-byte string buffer that resides outside V8's heap.
class ExternalStringResourceBase
class Utf8Value
Converts an object to a null-terminated UTF-8-encoded character array.
class Value
Converts an object to a two-byte (UTF-16-encoded) string.
class ValueView
Returns a view onto a string's contents.
struct WriteFlags
Public Types
enum Encoding { UNKNOWN_ENCODING = 0x1
, TWO_BYTE_ENCODING = 0x0
, ONE_BYTE_ENCODING = 0x8
 }
enum WriteOptions {
NO_OPTIONS = 0
, HINT_MANY_WRITES_EXPECTED = 1
, NO_NULL_TERMINATION = 2
, PRESERVE_ONE_BYTE_NULL = 4
,
REPLACE_INVALID_UTF8 = 8
 }
Write the contents of the string to an external buffer.
Public Member Functions
int Length () const
Returns the number of characters (UTF-16 code units) in this string.
int Utf8Length (Isolate *isolate) const
Returns the number of bytes in the UTF-8 encoded representation of this string.
size_t Utf8LengthV2 (Isolate *isolate) const
Returns the number of bytes needed for the Utf8 encoding of this string.
bool IsOneByte () const
Returns whether this string is known to contain only one byte data, i.e.
bool ContainsOnlyOneByte () const
Returns whether this string contain only one byte data, i.e.
int Write (Isolate *isolate, uint16_t *buffer, int start=0, int length=-1, int options=NO_OPTIONS) const
int WriteOneByte (Isolate *isolate, uint8_t *buffer, int start=0, int length=-1, int options=NO_OPTIONS) const
int WriteUtf8 (Isolate *isolate, char *buffer, int length=-1, int *nchars_ref=nullptr, int options=NO_OPTIONS) const
void WriteV2 (Isolate *isolate, uint32_t offset, uint32_t length, uint16_t *buffer, int flags=WriteFlags::kNone) const
Write the contents of the string to an external buffer.
void WriteOneByteV2 (Isolate *isolate, uint32_t offset, uint32_t length, uint8_t *buffer, int flags=WriteFlags::kNone) const
size_t WriteUtf8V2 (Isolate *isolate, char *buffer, size_t capacity, int flags=WriteFlags::kNone, size_t *processed_characters_return=nullptr) const
Encode the contents of the string as Utf8 into an external buffer.
bool IsExternal () const
Returns true if the string is external.
bool IsExternalTwoByte () const
Returns true if the string is both external and two-byte.
bool IsExternalOneByte () const
Returns true if the string is both external and one-byte.
Local< String > InternalizeString (Isolate *isolate)
Returns the internalized string.
ExternalStringResourceBase * GetExternalStringResourceBase (v8::Isolate *isolate, Encoding *encoding_out) const
If the string is an external string, return the ExternalStringResourceBase regardless of the encoding, otherwise return NULL.
ExternalStringResourceBase * GetExternalStringResourceBase (Encoding *encoding_out) const
ExternalStringResource * GetExternalStringResource () const
Get the ExternalStringResource for an external string.
const ExternalOneByteStringResource * GetExternalOneByteStringResource () const
Get the ExternalOneByteStringResource for an external one-byte string.
Use the version with the isolate argument instead bool MakeExternal (ExternalStringResource *resource)
Associate an external string resource with this string by transforming it in place so that existing references to this string in the JavaScript heap will use the external string resource.
bool MakeExternal (Isolate *isolate, ExternalStringResource *resource)
Associate an external string resource with this string by transforming it in place so that existing references to this string in the JavaScript heap will use the external string resource.
Use the version with the isolate argument instead bool MakeExternal (ExternalOneByteStringResource *resource)
Associate an external string resource with this string by transforming it in place so that existing references to this string in the JavaScript heap will use the external string resource.
bool MakeExternal (Isolate *isolate, ExternalOneByteStringResource *resource)
Associate an external string resource with this string by transforming it in place so that existing references to this string in the JavaScript heap will use the external string resource.
bool CanMakeExternal (Encoding encoding) const
Returns true if this string can be made external, given the encoding for the external string resource.
bool StringEquals (Local< String > str) const
Returns true if the strings values are equal.
template<> V8_WARN_UNUSED_RESULT Local< String > NewFromUtf8Literal (Isolate *isolate, const char(&literal)[1], NewStringType type)
Static Public Member Functions
static Local< String > Empty (Isolate *isolate)
A zero length string.
static String * Cast (v8::Data *data)
template<int N>
static V8_WARN_UNUSED_RESULT Local< String > NewFromUtf8Literal (Isolate *isolate, const char(&literal)[N], NewStringType type=NewStringType::kNormal)
Allocates a new string from a UTF-8 literal.
static V8_WARN_UNUSED_RESULT MaybeLocal< String > NewFromUtf8 (Isolate *isolate, const char *data, NewStringType type=NewStringType::kNormal, int length=-1)
Allocates a new string from UTF-8 data.
static V8_WARN_UNUSED_RESULT MaybeLocal< String > NewFromOneByte (Isolate *isolate, const uint8_t *data, NewStringType type=NewStringType::kNormal, int length=-1)
Allocates a new string from Latin-1 data.
static V8_WARN_UNUSED_RESULT MaybeLocal< String > NewFromTwoByte (Isolate *isolate, const uint16_t *data, NewStringType type=NewStringType::kNormal, int length=-1)
Allocates a new string from UTF-16 data.
static Local< String > Concat (Isolate *isolate, Local< String > left, Local< String > right)
Creates a new string by concatenating the left and the right strings passed in as parameters.
static V8_WARN_UNUSED_RESULT MaybeLocal< String > NewExternalTwoByte (Isolate *isolate, ExternalStringResource *resource)
Creates a new external string using the data defined in the given resource.
static V8_WARN_UNUSED_RESULT MaybeLocal< String > NewExternalOneByte (Isolate *isolate, ExternalOneByteStringResource *resource)
Creates a new external string using the one-byte data defined in the given resource.
Static Public Attributes
static constexpr int kMaxLength
Private Member Functions
void VerifyExternalStringResourceBase (ExternalStringResourceBase *v, Encoding encoding) const
void VerifyExternalStringResource (ExternalStringResource *val) const
ExternalStringResource * GetExternalStringResourceSlow () const
ExternalStringResourceBase * GetExternalStringResourceBaseSlow (String::Encoding *encoding_out) const
Static Private Member Functions
static Local< v8::String > NewFromUtf8Literal (Isolate *isolate, const char *literal, NewStringType type, int length)
static void CheckCast (v8::Data *that)
Detailed Description
A JavaScript string value (ECMA-262, 4.3.17).
Definition at line 124 of file v8-primitive.h.
Member Enumeration Documentation
Encoding
enum v8::String::Encoding
Enumerator
UNKNOWN_ENCODING
TWO_BYTE_ENCODING
ONE_BYTE_ENCODING
Definition at line 129 of file v8-primitive.h.
                {
    UNKNOWN_ENCODING = 0x1,
    TWO_BYTE_ENCODING = 0x0,
    ONE_BYTE_ENCODING = 0x8
  };
WriteOptions
enum v8::String::WriteOptions
Write the contents of the string to an external buffer.
If no arguments are given, expects the buffer to be large enough to hold the entire string and NULL terminator. Copies the contents of the string and the NULL terminator into the buffer.
WriteUtf8 will not write partial UTF-8 sequences, preferring to stop before the end of the buffer.
Copies up to length characters into the output buffer. Only null-terminates if there is enough space in the buffer.
Parameters
buffer The buffer into which the string will be copied.
start The starting position within the string at which copying begins.
length The number of characters to copy from the string. For WriteUtf8 the number of bytes in the buffer.
nchars_ref The number of characters written, can be NULL.
options Various options that might affect performance of this or subsequent operations.
Returns
The number of characters copied to the buffer excluding the null terminator. For WriteUtf8: The number of bytes copied to the buffer including the null terminator (if written).
Enumerator
NO_OPTIONS
HINT_MANY_WRITES_EXPECTED
NO_NULL_TERMINATION
PRESERVE_ONE_BYTE_NULL
REPLACE_INVALID_UTF8
Definition at line 191 of file v8-primitive.h.
                    {
    NO_OPTIONS = 0,
    HINT_MANY_WRITES_EXPECTED = 1,
    NO_NULL_TERMINATION = 2,
    PRESERVE_ONE_BYTE_NULL = 4,
    // Used by WriteUtf8 to replace orphan surrogate code units with the
    // unicode replacement character. Needs to be set to guarantee valid UTF-8
    // output.
    REPLACE_INVALID_UTF8 = 8
  };
Member Function Documentation
CanMakeExternal()
bool v8::String::CanMakeExternal (Encoding encoding) const
Returns true if this string can be made external, given the encoding for the external string resource.
Definition at line 7715 of file api.cc.
                                                      {
  i::Tagged<i::String> obj = *Utils::OpenDirectHandle(this);
  return obj->SupportsExternalization(encoding);
}
References v8::Utils::OpenDirectHandle().
Cast()
static String* v8::String::Cast (v8::Data * data) [inline], [static]
Definition at line 509 of file v8-primitive.h.
                                              {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<String*>(data);
  }
CheckCast()
void v8::String::CheckCast (v8::Data * that) [static], [private]
Definition at line 3886 of file api.cc.
                                     {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsString(*obj), "v8::String::Cast",
                  "Value is not a String");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Concat()
Local< String > v8::String::Concat (Isolate * isolate, Local< String > left, Local< String > right) [static]
Creates a new string by concatenating the left and the right strings passed in as parameters.
Definition at line 7587 of file api.cc.
                                                      {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto left_string = Utils::OpenHandle(*left);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_String_Concat);
  auto right_string = Utils::OpenHandle(*right);
  // If we are steering towards a range error, do not wait for the error to be
  // thrown, and return the null handle instead.
  if (left_string->length() + right_string->length() > i::String::kMaxLength) {
    return {};
  }
  i::DirectHandle<i::String> result =
      i_isolate->factory()
          ->NewConsString(left_string, right_string)
          .ToHandleChecked();
  return Utils::ToLocal(result);
}
References v8::internal::Isolate::factory(), v8::internal::String::kMaxLength, v8::internal::FactoryBase< Impl >::NewConsString(), v8::Utils::OpenHandle(), and v8::base::internal::result.
Referenced by v8::Shell::FunctionAndArgumentsToString(), v8::GetStdout(), v8::Shell::ReadFromStdin(), and v8_inspector::anonymous_namespace{custom-preview.cc}::reportError().
ContainsOnlyOneByte()
bool v8::String::ContainsOnlyOneByte () const
Returns whether this string contain only one byte data, i.e.
ISO-8859-1 code points. Will read the entire string in some cases.
Definition at line 5680 of file api.cc.
                                       {
  auto str = Utils::OpenDirectHandle(this);
  if (str->IsOneByteRepresentation()) return true;
  ContainsOnlyOneByteHelper helper;
  return helper.Check(*str);
}
References v8::ContainsOnlyOneByteHelper::Check(), and v8::Utils::OpenDirectHandle().
Empty()
Local< String > v8::String::Empty (Isolate * isolate) [inline], [static]
A zero length string.
Definition at line 980 of file v8-primitive.h.
                                            {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kEmptyStringRootIndex);
  return Local<String>::FromSlot(slot);
}
References v8::Local< T >::FromSlot(), I, and v8::internal::S.
Referenced by v8::D8Console::DisposeProfiler(), v8::GetStdout(), v8_inspector::V8DebuggerScript::hash(), v8::Shell::Main(), NewFromUtf8Literal(), v8::internal::Isolate::PrintCurrentStackTrace(), v8::D8Console::Profile(), v8::D8Console::ProfileEnd(), v8::Shell::Stringify(), v8_inspector::toV8String(), and v8_inspector::toV8StringInternalized().
GetExternalOneByteStringResource()
const v8::String::ExternalOneByteStringResource * v8::String::GetExternalOneByteStringResource () const
Get the ExternalOneByteStringResource for an external one-byte string.
Returns NULL if IsExternalOneByte() doesn't return true.
Definition at line 6146 of file api.cc.
                                                 {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::String> str = *Utils::OpenDirectHandle(this);
  if (i::StringShape(str).IsExternalOneByte()) {
    return i::Cast<i::ExternalOneByteString>(str)->resource();
  } else if (i::IsThinString(str)) {
    str = i::Cast<i::ThinString>(str)->actual();
    if (i::StringShape(str).IsExternalOneByte()) {
      return i::Cast<i::ExternalOneByteString>(str)->resource();
    }
  }
  uint32_t raw_hash_field = str->raw_hash_field(kAcquireLoad);
  if (i::String::IsExternalForwardingIndex(raw_hash_field)) {
    bool is_one_byte;
    auto resource = GetExternalResourceFromForwardingTable(str, raw_hash_field,
                                                           &is_one_byte);
    if (is_one_byte) {
      return reinterpret_cast<ExternalOneByteStringResource*>(resource);
    }
  }
  return nullptr;
}
References v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::internal::Name::IsExternalForwardingIndex(), IsExternalOneByte(), v8::internal::InstanceTypeChecker::IsThinString(), v8::kAcquireLoad, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
GetExternalStringResource()
String::ExternalStringResource * v8::String::GetExternalStringResource () const [inline]
Get the ExternalStringResource for an external string.
Returns NULL if IsExternal() doesn't return true.
Definition at line 988 of file v8-primitive.h.
                                                                      {
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
  ExternalStringResource* result;
  if (I::IsExternalTwoByteString(I::GetInstanceType(obj))) {
    Isolate* isolate = I::GetCurrentIsolateForSandbox();
    A value = I::ReadExternalPointerField<internal::kExternalStringResourceTag>(
        isolate, obj, I::kStringResourceOffset);
    result = reinterpret_cast<String::ExternalStringResource*>(value);
  } else {
    result = GetExternalStringResourceSlow();
  }
#ifdef V8_ENABLE_CHECKS
  VerifyExternalStringResource(result);
#endif
  return result;
}
References v8::internal::A, v8::internal::GetCurrentIsolateForSandbox(), GetExternalStringResourceSlow(), I, v8::base::internal::result, v8::internal::value, v8::internal::ValueHelper::ValueAsAddress(), and VerifyExternalStringResource().
GetExternalStringResourceBase() [1/2]
String::ExternalStringResourceBase * v8::String::GetExternalStringResourceBase (String::Encoding * encoding_out) const [inline]
Definition at line 1030 of file v8-primitive.h.
                                        {
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
  int type = I::GetInstanceType(obj) & I::kStringRepresentationAndEncodingMask;
  *encoding_out = static_cast<Encoding>(type & I::kStringEncodingMask);
  ExternalStringResourceBase* resource;
  if (type == I::kExternalOneByteRepresentationTag ||
      type == I::kExternalTwoByteRepresentationTag) {
    Isolate* isolate = I::GetCurrentIsolateForSandbox();
    A value = I::ReadExternalPointerField<internal::kExternalStringResourceTag>(
        isolate, obj, I::kStringResourceOffset);
    resource = reinterpret_cast<ExternalStringResourceBase*>(value);
  } else {
    resource = GetExternalStringResourceBaseSlow(encoding_out);
  }
#ifdef V8_ENABLE_CHECKS
  VerifyExternalStringResourceBase(resource, *encoding_out);
#endif
  return resource;
}
References v8::internal::A, v8::internal::GetCurrentIsolateForSandbox(), GetExternalStringResourceBaseSlow(), I, v8::internal::kStringEncodingMask, v8::internal::kStringRepresentationAndEncodingMask, v8::internal::tracing::type, v8::internal::value, v8::internal::ValueHelper::ValueAsAddress(), and VerifyExternalStringResourceBase().
GetExternalStringResourceBase() [2/2]
String::ExternalStringResourceBase * v8::String::GetExternalStringResourceBase (v8::Isolate * isolate, String::Encoding * encoding_out) const [inline]
If the string is an external string, return the ExternalStringResourceBase regardless of the encoding, otherwise return NULL.
The encoding of the string is returned in encoding_out.
Definition at line 1008 of file v8-primitive.h.
                                                            {
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
  int type = I::GetInstanceType(obj) & I::kStringRepresentationAndEncodingMask;
  *encoding_out = static_cast<Encoding>(type & I::kStringEncodingMask);
  ExternalStringResourceBase* resource;
  if (type == I::kExternalOneByteRepresentationTag ||
      type == I::kExternalTwoByteRepresentationTag) {
    A value = I::ReadExternalPointerField<internal::kExternalStringResourceTag>(
        isolate, obj, I::kStringResourceOffset);
    resource = reinterpret_cast<ExternalStringResourceBase*>(value);
  } else {
    resource = GetExternalStringResourceBaseSlow(encoding_out);
  }
#ifdef V8_ENABLE_CHECKS
  VerifyExternalStringResourceBase(resource, *encoding_out);
#endif
  return resource;
}
References v8::internal::A, GetExternalStringResourceBaseSlow(), I, v8::internal::kStringEncodingMask, v8::internal::kStringRepresentationAndEncodingMask, v8::internal::tracing::type, v8::internal::value, v8::internal::ValueHelper::ValueAsAddress(), and VerifyExternalStringResourceBase().
GetExternalStringResourceBaseSlow()
String::ExternalStringResourceBase * v8::String::GetExternalStringResourceBaseSlow (String::Encoding * encoding_out) const [private]
Definition at line 6110 of file api.cc.
                                        {
  i::DisallowGarbageCollection no_gc;
  ExternalStringResourceBase* resource = nullptr;
  i::Tagged<i::String> str = *Utils::OpenDirectHandle(this);
  if (i::IsThinString(str)) {
    str = i::Cast<i::ThinString>(str)->actual();
  }
  internal::Address string = str.ptr();
  int type = i::Internals::GetInstanceType(string) &
             i::Internals::kStringRepresentationAndEncodingMask;
  *encoding_out =
      static_cast<Encoding>(type & i::Internals::kStringEncodingMask);
  if (i::StringShape(str).IsExternalOneByte() ||
      i::StringShape(str).IsExternalTwoByte()) {
    Isolate* isolate = i::Internals::GetCurrentIsolateForSandbox();
    i::Address value =
        i::Internals::ReadExternalPointerField<i::kExternalStringResourceTag>(
            isolate, string, i::Internals::kStringResourceOffset);
    resource = reinterpret_cast<ExternalStringResourceBase*>(value);
  } else {
    uint32_t raw_hash_field = str->raw_hash_field();
    if (i::String::IsExternalForwardingIndex(raw_hash_field)) {
      bool is_one_byte;
      resource = GetExternalResourceFromForwardingTable(str, raw_hash_field,
                                                        &is_one_byte);
      *encoding_out = is_one_byte ? Encoding::ONE_BYTE_ENCODING
                                  : Encoding::TWO_BYTE_ENCODING;
    }
  }
  return resource;
}
References v8::internal::Internals::GetCurrentIsolateForSandbox(), v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::internal::Internals::GetInstanceType(), v8::internal::Name::IsExternalForwardingIndex(), v8::internal::StringShape::IsExternalOneByte(), v8::internal::StringShape::IsExternalTwoByte(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::Internals::kStringEncodingMask, v8::internal::Internals::kStringRepresentationAndEncodingMask, v8::internal::Internals::kStringResourceOffset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::tracing::type, and v8::internal::value.
Referenced by GetExternalStringResourceBase().
GetExternalStringResourceSlow()
String::ExternalStringResource * v8::String::GetExternalStringResourceSlow () const [private]
Definition at line 6064 of file api.cc.
                                                                          {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::String> str = *Utils::OpenDirectHandle(this);
  if (i::IsThinString(str)) {
    str = i::Cast<i::ThinString>(str)->actual();
  }
  if (i::StringShape(str).IsExternalTwoByte()) {
    Isolate* isolate = i::Internals::GetCurrentIsolateForSandbox();
    i::Address value =
        i::Internals::ReadExternalPointerField<i::kExternalStringResourceTag>(
            isolate, str.ptr(), i::Internals::kStringResourceOffset);
    return reinterpret_cast<String::ExternalStringResource*>(value);
  } else {
    uint32_t raw_hash_field = str->raw_hash_field(kAcquireLoad);
    if (i::String::IsExternalForwardingIndex(raw_hash_field)) {
      bool is_one_byte;
      auto resource = GetExternalResourceFromForwardingTable(
          str, raw_hash_field, &is_one_byte);
      if (!is_one_byte) {
        return reinterpret_cast<ExternalStringResource*>(resource);
      }
    }
  }
  return nullptr;
}
References v8::internal::Internals::GetCurrentIsolateForSandbox(), v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::internal::Name::IsExternalForwardingIndex(), IsExternalTwoByte(), v8::internal::InstanceTypeChecker::IsThinString(), v8::kAcquireLoad, v8::internal::Internals::kStringResourceOffset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::value.
Referenced by GetExternalStringResource().
InternalizeString()
Local< v8::String > v8::String::InternalizeString (Isolate * isolate)
Returns the internalized string.
See NewStringType::kInternalized for details on internalized strings.
Definition at line 5993 of file api.cc.
                                                               {
  auto* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto str = Utils::OpenDirectHandle(this);
  return Utils::ToLocal(isolate->factory()->InternalizeString(str));
}
References v8::Utils::OpenDirectHandle().
IsExternal()
bool v8::String::IsExternal () const
Returns true if the string is external.
Definition at line 5965 of file api.cc.
                                {
  return HasExternalStringResource(*Utils::OpenDirectHandle(this));
}
References v8::anonymous_namespace{api.cc}::HasExternalStringResource(), and v8::Utils::OpenDirectHandle().
IsExternalOneByte()
bool v8::String::IsExternalOneByte () const
Returns true if the string is both external and one-byte.
Definition at line 5981 of file api.cc.
                                       {
  auto str = Utils::OpenDirectHandle(this);
  if (i::StringShape(*str).IsExternalOneByte()) return true;
  uint32_t raw_hash_field = str->raw_hash_field(kAcquireLoad);
  if (i::String::IsExternalForwardingIndex(raw_hash_field)) {
    bool is_one_byte;
    GetExternalResourceFromForwardingTable(*str, raw_hash_field, &is_one_byte);
    return is_one_byte;
  }
  return false;
}
References v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::internal::Name::IsExternalForwardingIndex(), v8::internal::StringShape::IsExternalOneByte(), v8::kAcquireLoad, and v8::Utils::OpenDirectHandle().
Referenced by GetExternalOneByteStringResource().
IsExternalTwoByte()
bool v8::String::IsExternalTwoByte () const
Returns true if the string is both external and two-byte.
Definition at line 5969 of file api.cc.
                                       {
  auto str = Utils::OpenDirectHandle(this);
  if (i::StringShape(*str).IsExternalTwoByte()) return true;
  uint32_t raw_hash_field = str->raw_hash_field(kAcquireLoad);
  if (i::String::IsExternalForwardingIndex(raw_hash_field)) {
    bool is_one_byte;
    GetExternalResourceFromForwardingTable(*str, raw_hash_field, &is_one_byte);
    return !is_one_byte;
  }
  return false;
}
References v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::internal::Name::IsExternalForwardingIndex(), v8::internal::StringShape::IsExternalTwoByte(), v8::kAcquireLoad, and v8::Utils::OpenDirectHandle().
Referenced by GetExternalStringResourceSlow().
IsOneByte()
bool v8::String::IsOneByte () const
Returns whether this string is known to contain only one byte data, i.e.
ISO-8859-1 code points. Does not read the string. False negatives are possible.
Definition at line 5563 of file api.cc.
                             {
  return Utils::OpenDirectHandle(this)->IsOneByteRepresentation();
}
References v8::Utils::OpenDirectHandle().
Referenced by WriteOneByteV2().
Length()
int v8::String::Length () const
Returns the number of characters (UTF-16 code units) in this string.
Definition at line 5559 of file api.cc.
                         {
  return static_cast<int>(Utils::OpenDirectHandle(this)->length());
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{v8-debugger-script.cc}::calculateHash(), v8_inspector::V8Console::createTask(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::V8DebuggerScript::GetScriptName(), v8_inspector::V8DebuggerScript::Initialize(), v8_inspector::V8Console::monitorFunctionCallback(), and v8_inspector::V8DebuggerScript::source().
MakeExternal() [1/4]
bool v8::String::MakeExternal (ExternalOneByteStringResource * resource)
Associate an external string resource with this string by transforming it in place so that existing references to this string in the JavaScript heap will use the external string resource.
The external string resource's character contents need to be equivalent to this string. Returns true if the string has been changed to be an external string. The string is not modified if the operation fails. See NewExternal for information on the lifetime of the resource.
Definition at line 7685 of file api.cc.
                                                     {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  return MakeExternal(isolate, resource);
}
References v8::Isolate::GetCurrent().
MakeExternal() [2/4]
bool v8::String::MakeExternal (ExternalStringResource * resource)
Associate an external string resource with this string by transforming it in place so that existing references to this string in the JavaScript heap will use the external string resource.
The external string resource's character contents need to be equivalent to this string. Returns true if the string has been changed to be an external string. The string is not modified if the operation fails. See NewExternal for information on the lifetime of the resource.
Definition at line 7656 of file api.cc.
                                                                    {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  return MakeExternal(isolate, resource);
}
References v8::Isolate::GetCurrent().
MakeExternal() [3/4]
bool v8::String::MakeExternal (Isolate * isolate, ExternalOneByteStringResource * resource)
Associate an external string resource with this string by transforming it in place so that existing references to this string in the JavaScript heap will use the external string resource.
The external string resource's character contents need to be equivalent to this string. Returns true if the string has been changed to be an external string. The string is not modified if the operation fails. See NewExternal for information on the lifetime of the resource.
Definition at line 7691 of file api.cc.
                                                                       {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::String> obj = *Utils::OpenDirectHandle(this);
  if (i::IsThinString(obj)) {
    obj = i::Cast<i::ThinString>(obj)->actual();
  }
  if (!obj->SupportsExternalization(Encoding::ONE_BYTE_ENCODING)) {
    return false;
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  CHECK(resource && resource->data());
  bool result = obj->MakeExternal(i_isolate, resource);
  DCHECK_IMPLIES(result, HasExternalStringResource(obj));
  return result;
}
References CHECK, v8::String::ExternalOneByteStringResource::data(), DCHECK_IMPLIES, v8::anonymous_namespace{api.cc}::HasExternalStringResource(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
MakeExternal() [4/4]
bool v8::String::MakeExternal (Isolate * isolate, ExternalStringResource * resource)
Associate an external string resource with this string by transforming it in place so that existing references to this string in the JavaScript heap will use the external string resource.
The external string resource's character contents need to be equivalent to this string. Returns true if the string has been changed to be an external string. The string is not modified if the operation fails. See NewExternal for information on the lifetime of the resource.
Definition at line 7661 of file api.cc.
                                                                        {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::String> obj = *Utils::OpenDirectHandle(this);
  if (i::IsThinString(obj)) {
    obj = i::Cast<i::ThinString>(obj)->actual();
  }
  if (!obj->SupportsExternalization(Encoding::TWO_BYTE_ENCODING)) {
    return false;
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  CHECK(resource && resource->data());
  bool result = obj->MakeExternal(i_isolate, resource);
  DCHECK_IMPLIES(result, HasExternalStringResource(obj));
  return result;
}
References CHECK, v8::String::ExternalStringResource::data(), DCHECK_IMPLIES, v8::anonymous_namespace{api.cc}::HasExternalStringResource(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
NewExternalOneByte()
MaybeLocal< String > v8::String::NewExternalOneByte (Isolate * isolate, ExternalOneByteStringResource * resource) [static]
Creates a new external string using the one-byte data defined in the given resource.
When the external string is no longer live on V8's heap the resource will be disposed by calling its Dispose method. The caller of this function should not otherwise delete or modify the resource. Neither should the underlying buffer be deallocated or modified except through the destructor of the external string resource.
Definition at line 7631 of file api.cc.
                                                                          {
  CHECK_NOT_NULL(resource);
  // TODO(dcarney): throw a context free exception.
  if (resource->length() > static_cast<size_t>(i::String::kMaxLength)) {
    return {};
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_String_NewExternalOneByte);
  if (resource->length() == 0) {
    // The resource isn't going to be used, free it immediately.
    resource->Unaccount(v8_isolate);
    resource->Dispose();
    return Utils::ToLocal(i_isolate->factory()->empty_string());
  }
  CHECK_NOT_NULL(resource->data());
  i::DirectHandle<i::String> string =
      i_isolate->factory()
          ->NewExternalStringFromOneByte(resource)
          .ToHandleChecked();
  return Utils::ToLocal(string);
}
References CHECK_NOT_NULL, v8::String::ExternalOneByteStringResource::data(), v8::String::ExternalStringResourceBase::Dispose(), v8::internal::Isolate::factory(), v8::internal::String::kMaxLength, v8::String::ExternalOneByteStringResource::length(), v8::internal::Factory::NewExternalStringFromOneByte(), and v8::String::ExternalStringResourceBase::Unaccount().
Referenced by v8::Shell::ReadFile().
NewExternalTwoByte()
MaybeLocal< String > v8::String::NewExternalTwoByte (Isolate * isolate, ExternalStringResource * resource) [static]
Creates a new external string using the data defined in the given resource.
When the external string is no longer live on V8's heap the resource will be disposed by calling its Dispose method. The caller of this function should not otherwise delete or modify the resource. Neither should the underlying buffer be deallocated or modified except through the destructor of the external string resource.
Definition at line 7606 of file api.cc.
                                                                   {
  CHECK(resource && resource->data());
  // TODO(dcarney): throw a context free exception.
  if (resource->length() > static_cast<size_t>(i::String::kMaxLength)) {
    return {};
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_String_NewExternalTwoByte);
  if (resource->length() > 0) {
    i::DirectHandle<i::String> string =
        i_isolate->factory()
            ->NewExternalStringFromTwoByte(resource)
            .ToHandleChecked();
    return Utils::ToLocal(string);
  } else {
    // The resource isn't going to be used, free it immediately.
    resource->Unaccount(v8_isolate);
    resource->Dispose();
    return Utils::ToLocal(i_isolate->factory()->empty_string());
  }
}
References CHECK, v8::String::ExternalStringResource::data(), v8::String::ExternalStringResourceBase::Dispose(), v8::internal::Isolate::factory(), v8::internal::String::kMaxLength, v8::String::ExternalStringResource::length(), v8::internal::Factory::NewExternalStringFromTwoByte(), and v8::String::ExternalStringResourceBase::Unaccount().
NewFromOneByte()
MaybeLocal< String > v8::String::NewFromOneByte (Isolate * isolate, const uint8_t * data, NewStringType type = NewStringType::kNormal, int length = -1) [static]
Allocates a new string from Latin-1 data.
Only returns an empty value when length > kMaxLength.
Definition at line 7573 of file api.cc.
                                                                          {
  NEW_STRING(v8_isolate, String, NewFromOneByte, uint8_t, data, type, length);
  return result;
}
References v8::internal::length, NEW_STRING, v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::GetDotReplResultString(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::NewRangeException(), v8::InspectorFrontend::Send(), and v8_inspector::toV8String().
NewFromTwoByte()
MaybeLocal< String > v8::String::NewFromTwoByte (Isolate * isolate, const uint16_t * data, NewStringType type = NewStringType::kNormal, int length = -1) [static]
Allocates a new string from UTF-16 data.
Only returns an empty value when length > kMaxLength.
Definition at line 7580 of file api.cc.
                                                                          {
  NEW_STRING(v8_isolate, String, NewFromTwoByte, uint16_t, data, type, length);
  return result;
}
References v8::internal::length, NEW_STRING, v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::InspectorFrontend::Send(), v8_inspector::toV8String(), and v8_inspector::toV8StringInternalized().
NewFromUtf8()
MaybeLocal< String > v8::String::NewFromUtf8 (Isolate * isolate, const char * data, NewStringType type = NewStringType::kNormal, int length = -1) [static]
Allocates a new string from UTF-8 data.
Only returns an empty value when length > kMaxLength.
Definition at line 7567 of file api.cc.
                                                                       {
  NEW_STRING(v8_isolate, String, NewFromUtf8, char, data, type, length);
  return result;
}
References v8::internal::length, NEW_STRING, v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::internal::AddCounter(), v8::internal::AddNumber(), v8::internal::AddNumber64(), v8::Shell::CreateEvaluationContext(), v8::Shell::CreateOSTemplate(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::CreateTemplate(), v8::Shell::CreateTestFastCApiTemplate(), v8::Shell::CreateWorkerTemplate(), v8::SourceGroup::Execute(), v8::Shell::ExecuteFile(), v8::Worker::ExecuteInThread(), v8::Shell::FetchModuleSource(), v8::Shell::FetchModuleTree(), v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::FillTraceConfig(), v8::GetStdout(), v8::Shell::HostInitializeImportMetaObject(), v8::Shell::LoadJSON(), v8::Shell::LogGetAndStop(), v8::internal::VTuneDomainSupportExtension::Mark(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseExecution(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseFlavor(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseType(), v8::Shell::ReadFile(), v8::Shell::ReadFileData(), v8::Shell::ReadFromStdin(), v8::Shell::ReadLines(), v8::internal::anonymous_namespace{gc-extension.cc}::ReadProperty(), v8::internal::anonymous_namespace{snapshot.cc}::RunExtraCode(), v8::Template::Set(), v8::Shell::Stringify(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemoryFastCallback(), v8_inspector::toV8StringInternalized(), v8::Shell::TriggerOnProfileEndListener(), v8::anonymous_namespace{d8.cc}::TryGetValue(), v8::anonymous_namespace{d8-posix.cc}::v8_strerror(), and v8::Shell::Version().
NewFromUtf8Literal() [1/3]
Local< String > v8::String::NewFromUtf8Literal (Isolate * isolate, const char * literal, NewStringType type, int length) [static], [private]
Definition at line 7552 of file api.cc.
                                                                         {
  DCHECK_LE(length, i::String::kMaxLength);
  i::Isolate* i_isolate = reinterpret_cast<internal::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_String_NewFromUtf8Literal);
  i::DirectHandle<i::String> handle_result =
      NewString(i_isolate->factory(), type,
                base::Vector<const char>(literal, length))
          .ToHandleChecked();
  return Utils::ToLocal(handle_result);
}
References DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::String::kMaxLength, v8::internal::length, v8::anonymous_namespace{api.cc}::NewString(), and v8::internal::tracing::type.
NewFromUtf8Literal() [2/3]
template<>
V8_WARN_UNUSED_RESULT Local<String> v8::String::NewFromUtf8Literal (Isolate * isolate, const char(&) literal[1], NewStringType type) [inline]
Definition at line 761 of file v8-primitive.h.
                                                                    {
  return String::Empty(isolate);
}
References Empty().
NewFromUtf8Literal() [3/3]
template<int N>
static V8_WARN_UNUSED_RESULT Local<String> v8::String::NewFromUtf8Literal (Isolate * isolate, const char(&) literal[N], NewStringType type = NewStringType::kNormal) [inline], [static]
Allocates a new string from a UTF-8 literal.
This is equivalent to calling String::NewFromUtf(isolate, `...`).ToLocalChecked(), but without the check overhead.
When called on a string literal containing '\0', the inferred length is the length of the input array minus 1 (for the final '\0') and not the value returned by strlen.
Definition at line 526 of file v8-primitive.h.
                                                 {
    static_assert(N <= kMaxLength, "String is too long");
    return NewFromUtf8Literal(isolate, literal, type, N - 1);
  }
References v8::internal::N, and v8::internal::tracing::type.
Referenced by v8::AsyncHooks::AsyncHooks(), v8::Shell::CreateD8Template(), v8::Shell::CreateEvaluationContext(), v8::CreateFastCAPIObject(), v8::Shell::CreateGlobalTemplate(), v8::Shell::CreateLeafInterfaceTypeTemplate(), v8::Shell::CreateNodeTemplates(), v8::Shell::CreateOSTemplate(), v8::Shell::CreateRealmTemplate(), v8::Shell::CreateWorkerTemplate(), v8::SourceGroup::Execute(), v8::Worker::ExecuteInThread(), v8::Shell::FetchModuleSource(), v8::Shell::FunctionAndArgumentsToString(), v8::Shell::HostImportModuleWithPhaseDynamically(), v8::Shell::HostInitializeImportMetaObject(), v8::InspectorClient::InspectorClient(), v8::Shell::JSONModuleEvaluationSteps(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8::Worker::ProcessMessage(), v8::AsyncHooks::PromiseHookDispatch(), v8::Shell::PromiseRejectCallback(), v8::Shell::ReadFromStdin(), v8::Shell::RealmEval(), v8::OnMessageFromWorkerTask::Run(), v8::InspectorClient::runMessageLoopOnPause(), v8::Shell::RunShell(), v8::InspectorFrontend::Send(), v8::Shell::Stringify(), v8::Isolate::ThrowError(), and v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap().
StringEquals()
bool v8::String::StringEquals (Local< String > str) const
Returns true if the strings values are equal.
Same as JS ==/===.
Definition at line 7721 of file api.cc.
                                                    {
  auto self = Utils::OpenDirectHandle(this);
  auto other = Utils::OpenDirectHandle(*that);
  return self->Equals(*other);
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), and v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags().
Utf8Length()
int v8::String::Utf8Length (Isolate * isolate) const
Returns the number of bytes in the UTF-8 encoded representation of this string.
Definition at line 5687 of file api.cc.
                                                {
  auto str = Utils::OpenDirectHandle(this);
  str = i::String::Flatten(reinterpret_cast<i::Isolate*>(v8_isolate), str);
  int length = str->length();
  if (length == 0) return 0;
  i::DisallowGarbageCollection no_gc;
  i::String::FlatContent flat = str->GetFlatContent(no_gc);
  DCHECK(flat.IsFlat());
  int utf8_length = 0;
  if (flat.IsOneByte()) {
    for (uint8_t c : flat.ToOneByteVector()) {
      utf8_length += c >> 7;
    }
    utf8_length += length;
  } else {
    int last_character = unibrow::Utf16::kNoPreviousCharacter;
    for (uint16_t c : flat.ToUC16Vector()) {
      utf8_length += unibrow::Utf8::Length(c, last_character);
      last_character = c;
    }
  }
  return utf8_length;
}
References DCHECK, unibrow::Utf16::kNoPreviousCharacter, v8::internal::length, unibrow::Utf8::Length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
Utf8LengthV2()
size_t v8::String::Utf8LengthV2 (Isolate * isolate) const
Returns the number of bytes needed for the Utf8 encoding of this string.
Definition at line 5711 of file api.cc.
                                                     {
  auto str = Utils::OpenDirectHandle(this);
  return i::String::Utf8Length(reinterpret_cast<i::Isolate*>(v8_isolate), str);
}
References v8::Utils::OpenDirectHandle(), and v8::internal::String::Utf8Length().
Referenced by v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), and v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap().
VerifyExternalStringResource()
void v8::String::VerifyExternalStringResource (ExternalStringResource * val) const [private]
Definition at line 5999 of file api.cc.
                                                 {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::String> str = *Utils::OpenDirectHandle(this);
  const v8::String::ExternalStringResource* expected;
  if (i::IsThinString(str)) {
    str = i::Cast<i::ThinString>(str)->actual();
  }
  if (i::StringShape(str).IsExternalTwoByte()) {
    const void* resource = i::Cast<i::ExternalTwoByteString>(str)->resource();
    expected = reinterpret_cast<const ExternalStringResource*>(resource);
  } else {
    uint32_t raw_hash_field = str->raw_hash_field(kAcquireLoad);
    if (i::String::IsExternalForwardingIndex(raw_hash_field)) {
      bool is_one_byte;
      auto resource = GetExternalResourceFromForwardingTable(
          str, raw_hash_field, &is_one_byte);
      if (!is_one_byte) {
        expected = reinterpret_cast<const ExternalStringResource*>(resource);
      }
    } else {
      expected = nullptr;
    }
  }
  CHECK_EQ(expected, value);
}
References CHECK_EQ, v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::internal::Name::IsExternalForwardingIndex(), v8::internal::InstanceTypeChecker::IsThinString(), v8::kAcquireLoad, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by GetExternalStringResource().
VerifyExternalStringResourceBase()
void v8::String::VerifyExternalStringResourceBase (ExternalStringResourceBase * v, Encoding encoding) const [private]
Definition at line 6028 of file api.cc.
                                                                        {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::String> str = *Utils::OpenDirectHandle(this);
  const v8::String::ExternalStringResourceBase* expected;
  Encoding expectedEncoding;
  if (i::IsThinString(str)) {
    str = i::Cast<i::ThinString>(str)->actual();
  }
  if (i::StringShape(str).IsExternalOneByte()) {
    const void* resource = i::Cast<i::ExternalOneByteString>(str)->resource();
    expected = reinterpret_cast<const ExternalStringResourceBase*>(resource);
    expectedEncoding = ONE_BYTE_ENCODING;
  } else if (i::StringShape(str).IsExternalTwoByte()) {
    const void* resource = i::Cast<i::ExternalTwoByteString>(str)->resource();
    expected = reinterpret_cast<const ExternalStringResourceBase*>(resource);
    expectedEncoding = TWO_BYTE_ENCODING;
  } else {
    uint32_t raw_hash_field = str->raw_hash_field(kAcquireLoad);
    if (i::String::IsExternalForwardingIndex(raw_hash_field)) {
      bool is_one_byte;
      expected = GetExternalResourceFromForwardingTable(str, raw_hash_field,
                                                        &is_one_byte);
      expectedEncoding = is_one_byte ? ONE_BYTE_ENCODING : TWO_BYTE_ENCODING;
    } else {
      expected = nullptr;
      expectedEncoding = str->IsOneByteRepresentation() ? ONE_BYTE_ENCODING
                                                        : TWO_BYTE_ENCODING;
    }
  }
  CHECK_EQ(expected, value);
  CHECK_EQ(expectedEncoding, encoding);
}
References CHECK_EQ, v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::internal::Name::IsExternalForwardingIndex(), v8::internal::StringShape::IsExternalTwoByte(), v8::internal::InstanceTypeChecker::IsThinString(), v8::kAcquireLoad, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by GetExternalStringResourceBase().
Write()
int v8::String::Write (Isolate * isolate, uint16_t * buffer, int start = 0, int length = -1, int options = NO_OPTIONS) const
Definition at line 5889 of file api.cc.
                                     {
  return WriteHelper(reinterpret_cast<i::Isolate*>(v8_isolate), this, buffer,
                     start, length, options);
}
References v8::internal::length, and v8::WriteHelper().
WriteOneByte()
int v8::String::WriteOneByte (Isolate * isolate, uint8_t * buffer, int start = 0, int length = -1, int options = NO_OPTIONS) const
Definition at line 5883 of file api.cc.
                                                        {
  return WriteHelper(reinterpret_cast<i::Isolate*>(v8_isolate), this, buffer,
                     start, length, options);
}
References v8::internal::length, and v8::WriteHelper().
WriteOneByteV2()
void v8::String::WriteOneByteV2 (Isolate * isolate, uint32_t offset, uint32_t length, uint8_t * buffer, int flags = WriteFlags::kNone) const
Definition at line 5918 of file api.cc.
                                                                               {
  DCHECK(IsOneByte());
  WriteHelperV2(reinterpret_cast<i::Isolate*>(v8_isolate), this, buffer, offset,
                length, flags);
}
References DCHECK, flags(), IsOneByte(), v8::internal::length, and v8::WriteHelperV2().
WriteUtf8()
int v8::String::WriteUtf8 (Isolate * isolate, char * buffer, int length = -1, int * nchars_ref = nullptr, int options = NO_OPTIONS) const
Definition at line 5844 of file api.cc.
                                                          {
  auto str = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_String_WriteUtf8);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  str = i::String::Flatten(i_isolate, str);
  i::DisallowGarbageCollection no_gc;
  i::String::FlatContent content = str->GetFlatContent(no_gc);
  if (content.IsOneByte()) {
    return WriteUtf8Impl<uint8_t>(content.ToOneByteVector(), buffer, capacity,
                                  options, nchars_ref);
  } else {
    return WriteUtf8Impl<uint16_t>(content.ToUC16Vector(), buffer, capacity,
                                   options, nchars_ref);
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
WriteUtf8V2()
size_t v8::String::WriteUtf8V2 (Isolate * isolate, char * buffer, size_t capacity, int flags = WriteFlags::kNone, size_t * processed_characters_return = nullptr) const
Encode the contents of the string as Utf8 into an external buffer.
Encodes the characters of this string as Utf8 and writes them into the output buffer until either all characters were encoded or the buffer is full. Will not write partial UTF-8 sequences, preferring to stop before the end of the buffer. If null termination is requested, the output buffer will always be null terminated even if not all characters fit. In that case, the capacity must be at least one. The required size of the output buffer can be determined using Utf8Length().
Parameters
buffer The buffer into which the string will be written.
capacity The number of bytes available in the output buffer.
flags Various flags that influence the behavior of this operation.
processed_characters_return The number of processed characters from the buffer.
Returns
The number of bytes copied to the buffer including the null terminator (if written).
Definition at line 5925 of file api.cc.
                                                                      {
  auto str = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_String_WriteUtf8);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::String::Utf8EncodingFlags i_flags;
  if (flags & String::WriteFlags::kNullTerminate) {
    i_flags |= i::String::Utf8EncodingFlag::kNullTerminate;
  }
  if (flags & String::WriteFlags::kReplaceInvalidUtf8) {
    i_flags |= i::String::Utf8EncodingFlag::kReplaceInvalid;
  }
  return i::String::WriteUtf8(i_isolate, str, buffer, capacity, i_flags,
                              processed_characters_return);
}
References flags(), v8::String::WriteFlags::kNullTerminate, v8::String::WriteFlags::kReplaceInvalidUtf8, v8::Utils::OpenDirectHandle(), and v8::internal::String::WriteUtf8().
Referenced by v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), and v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap().
WriteV2()
void v8::String::WriteV2 (Isolate * isolate, uint32_t offset, uint32_t length, uint16_t * buffer, int flags = WriteFlags::kNone) const
Write the contents of the string to an external buffer.
Copies length characters into the output buffer starting at offset. The output buffer must have sufficient space for all characters and the null terminator if null termination is requested through the flags.
Parameters
offset The position within the string at which copying begins.
length The number of characters to copy from the string.
buffer The buffer into which the string will be copied.
flags Various flags that influence the behavior of this operation.
Definition at line 5912 of file api.cc.
                                                        {
  WriteHelperV2(reinterpret_cast<i::Isolate*>(v8_isolate), this, buffer, offset,
                length, flags);
}
References flags(), v8::internal::length, and v8::WriteHelperV2().
Referenced by v8_inspector::anonymous_namespace{v8-debugger-script.cc}::calculateHash(), and v8_inspector::V8DebuggerScript::source().
Member Data Documentation
kMaxLength
constexpr int v8::String::kMaxLength [static], [constexpr]
Initial value:
=
      internal::kApiSystemPointerSize == 4 ? (1 << 28) - 16 : (1 << 29) - 24
Definition at line 126 of file v8-primitive.h.
Referenced by v8::internal::Uri::Encode(), v8::Shell::ReadFileData(), v8::InspectorFrontend::Send(), v8_inspector::toV8String(), and v8_inspector::toV8StringInternalized().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc