v8::internal::compiler::WasmGraphAssembler Class Reference
#include <wasm-graph-assembler.h>
Public Member Functions
WasmGraphAssembler (MachineGraph *mcgraph, Zone *zone)
template<typename... Args>
Node * CallBuiltinThroughJumptable (Builtin builtin, Operator::Properties properties, Args... args)
Node * GetBuiltinPointerTarget (Builtin builtin)
template<typename... Args>
Node * CallBuiltin (Builtin name, Operator::Properties properties, Args... args)
template<typename... Args>
Node * CallBuiltinWithFrameState (Builtin name, Operator::Properties properties, Node *frame_state, Args... args)
Node * Branch (Node *cond, Node **true_node, Node **false_node, BranchHint hint)
Node * NumberConstant (double value)
Node * SmiConstant (Tagged_t value)
void MergeControlToEnd (Node *control)
Node * BuildTruncateIntPtrToInt32 (Node *value)
Node * BuildChangeInt32ToIntPtr (Node *value)
Node * BuildChangeIntPtrToInt64 (Node *value)
Node * BuildChangeUint32ToUintPtr (Node *node)
Node * BuildSmiShiftBitsConstant ()
Node * BuildSmiShiftBitsConstant32 ()
Node * BuildChangeInt32ToSmi (Node *value)
Node * BuildChangeUint31ToSmi (Node *value)
Node * BuildChangeSmiToInt32 (Node *value)
Node * BuildConvertUint32ToSmiWithSaturation (Node *value, uint32_t maxval)
Node * BuildChangeSmiToIntPtr (Node *value)
Node * Allocate (int size)
Node * Allocate (Node *size)
Node * LoadFromObject (MachineType type, Node *base, Node *offset)
Node * LoadFromObject (MachineType type, Node *base, int offset)
Node * LoadProtectedPointerFromObject (Node *object, Node *offset)
Node * LoadProtectedPointerFromObject (Node *object, int offset)
Node * LoadImmutableProtectedPointerFromObject (Node *object, Node *offset)
Node * LoadImmutableProtectedPointerFromObject (Node *object, int offset)
Node * LoadImmutableFromObject (MachineType type, Node *base, Node *offset)
Node * LoadImmutableFromObject (MachineType type, Node *base, int offset)
Node * LoadImmutable (LoadRepresentation rep, Node *base, Node *offset)
Node * LoadImmutable (LoadRepresentation rep, Node *base, int offset)
Node * LoadWasmCodePointer (Node *code_pointer)
Node * StoreToObject (ObjectAccess access, Node *base, Node *offset, Node *value)
Node * StoreToObject (ObjectAccess access, Node *base, int offset, Node *value)
Node * InitializeImmutableInObject (ObjectAccess access, Node *base, Node *offset, Node *value)
Node * InitializeImmutableInObject (ObjectAccess access, Node *base, int offset, Node *value)
Node * BuildDecodeSandboxedExternalPointer (Node *handle, ExternalPointerTagRange tag_range, Node *isolate_root)
Node * BuildLoadExternalPointerFromObject (Node *object, int offset, ExternalPointerTagRange tag_range, Node *isolate_root)
Node * BuildLoadExternalPointerFromObject (Node *object, int offset, Node *index, ExternalPointerTagRange tag_range, Node *isolate_root)
Node * LoadImmutableTrustedPointerFromObject (Node *object, int offset, IndirectPointerTag tag)
Node * LoadTrustedPointerFromObject (Node *object, int offset, IndirectPointerTag tag)
std::pair< Node *, Node * > LoadTrustedPointerFromObjectTrapOnNull (Node *object, int offset, IndirectPointerTag tag)
Node * BuildDecodeTrustedPointer (Node *handle, IndirectPointerTag tag)
Node * IsSmi (Node *object)
Node * LoadMap (Node *object)
void StoreMap (Node *heap_object, Node *map)
Node * LoadInstanceType (Node *map)
Node * LoadWasmTypeInfo (Node *map)
Node * LoadFixedArrayLengthAsSmi (Node *fixed_array)
Node * LoadFixedArrayElement (Node *fixed_array, Node *index_intptr, MachineType type=MachineType::AnyTagged())
Node * LoadImmutableFixedArrayElement (Node *fixed_array, Node *index_intptr, MachineType type=MachineType::AnyTagged())
Node * LoadFixedArrayElement (Node *array, int index, MachineType type)
Node * LoadFixedArrayElementSmi (Node *array, int index)
Node * LoadFixedArrayElementPtr (Node *array, int index)
Node * LoadFixedArrayElementAny (Node *array, int index)
Node * LoadProtectedFixedArrayElement (Node *array, int index)
Node * LoadProtectedFixedArrayElement (Node *array, Node *index_intptr)
Node * LoadByteArrayElement (Node *byte_array, Node *index_intptr, MachineType type)
Node * StoreFixedArrayElement (Node *array, int index, Node *value, ObjectAccess access)
Node * StoreFixedArrayElementSmi (Node *array, int index, Node *value)
Node * StoreFixedArrayElementAny (Node *array, int index, Node *value)
Node * LoadWeakFixedArrayElement (Node *fixed_array, Node *index_intptr)
Node * LoadSharedFunctionInfo (Node *js_function)
Node * LoadContextNoCellFromJSFunction (Node *js_function)
Node * LoadFunctionDataFromJSFunction (Node *js_function)
Node * LoadExportedFunctionIndexAsSmi (Node *exported_function_data)
Node * LoadExportedFunctionInstanceData (Node *exported_function_data)
Node * LoadJSArrayElements (Node *js_array)
Node * FieldOffset (const wasm::StructType *type, uint32_t field_index)
Node * WasmArrayElementOffset (Node *index, wasm::ValueType element_type)
Node * IsDataRefMap (Node *map)
Node * WasmTypeCheck (Node *object, Node *rtt, WasmTypeCheckConfig config)
Node * WasmTypeCheckAbstract (Node *object, WasmTypeCheckConfig config)
Node * WasmTypeCast (Node *object, Node *rtt, WasmTypeCheckConfig config)
Node * WasmTypeCastAbstract (Node *object, WasmTypeCheckConfig config)
Node * Null (wasm::ValueType type)
Node * IsNull (Node *object, wasm::ValueType type)
Node * IsNotNull (Node *object, wasm::ValueType type)
Node * AssertNotNull (Node *object, wasm::ValueType type, TrapId trap_id)
Node * WasmAnyConvertExtern (Node *object)
Node * WasmExternConvertAny (Node *object)
Node * StructGet (Node *object, const wasm::StructType *type, int field_index, bool is_signed, CheckForNull null_check)
void StructSet (Node *object, Node *value, const wasm::StructType *type, int field_index, CheckForNull null_check)
Node * ArrayGet (Node *array, Node *index, const wasm::ArrayType *type, bool is_signed)
void ArraySet (Node *array, Node *index, Node *value, const wasm::ArrayType *type)
Node * ArrayLength (Node *array, CheckForNull null_check)
void ArrayInitializeLength (Node *array, Node *length)
Node * LoadStringLength (Node *string)
Node * StringAsWtf16 (Node *string)
Node * StringPrepareForGetCodeunit (Node *string)
Node * HasInstanceType (Node *heap_object, InstanceType type)
void TrapIf (Node *condition, TrapId reason)
void TrapUnless (Node *condition, TrapId reason)
Node * LoadTrustedDataFromInstanceObject (Node *instance_object)
SimplifiedOperatorBuilder * simplified () override
Private Member Functions
template<typename... Args>
Node * CallBuiltinImpl (Builtin name, bool needs_frame_state, Operator::Properties properties, Args... args)
Private Attributes
SimplifiedOperatorBuilder simplified_
Additional Inherited Members
Detailed Description
Definition at line 26 of file wasm-graph-assembler.h.
Constructor & Destructor Documentation
WasmGraphAssembler()
v8::internal::compiler::WasmGraphAssembler::WasmGraphAssembler (MachineGraph * mcgraph, Zone * zone) [inline]
Definition at line 28 of file wasm-graph-assembler.h.
      : GraphAssembler(mcgraph, zone, BranchSemantics::kMachine),
        simplified_(zone) {}
References v8::internal::compiler::kMachine.
Member Function Documentation
Allocate() [1/2]
Node * v8::internal::compiler::WasmGraphAssembler::Allocate (int size)
Definition at line 130 of file wasm-graph-assembler.cc.
                                           {
  return Allocate(Int32Constant(size));
}
References v8::internal::compiler::GraphAssembler::Int32Constant(), and size().
Allocate() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::Allocate (Node * size)
Definition at line 134 of file wasm-graph-assembler.cc.
                                             {
  return AddNode(graph()->NewNode(
      simplified_.AllocateRaw(Type::Any(), AllocationType::kYoung), size,
      effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::SimplifiedOperatorBuilder::AllocateRaw(), v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::kYoung, simplified_, and size().
ArrayGet()
Node * v8::internal::compiler::WasmGraphAssembler::ArrayGet (Node * array, Node * index, const wasm::ArrayType * type, bool is_signed)
Definition at line 573 of file wasm-graph-assembler.cc.
                                                   {
  return AddNode(graph()->NewNode(simplified_.WasmArrayGet(type, is_signed),
                                  array, index, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::index, v8::internal::is_signed(), simplified_, and v8::internal::tracing::type.
ArrayInitializeLength()
void v8::internal::compiler::WasmGraphAssembler::ArrayInitializeLength (Node * array, Node * length)
Definition at line 591 of file wasm-graph-assembler.cc.
                                                                        {
  AddNode(graph()->NewNode(simplified_.WasmArrayInitializeLength(), array,
                           length, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::length, and simplified_.
ArrayLength()
Node * v8::internal::compiler::WasmGraphAssembler::ArrayLength (Node * array, CheckForNull null_check)
Definition at line 586 of file wasm-graph-assembler.cc.
                                                                          {
  return AddNode(graph()->NewNode(simplified_.WasmArrayLength(null_check),
                                  array, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
ArraySet()
void v8::internal::compiler::WasmGraphAssembler::ArraySet (Node * array, Node * index, Node * value, const wasm::ArrayType * type)
Definition at line 580 of file wasm-graph-assembler.cc.
                                                             {
  AddNode(graph()->NewNode(simplified_.WasmArraySet(type), array, index, value,
                           effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::index, simplified_, v8::internal::tracing::type, and v8::internal::value.
AssertNotNull()
Node * v8::internal::compiler::WasmGraphAssembler::AssertNotNull (Node * object, wasm::ValueType type, TrapId trap_id)
Definition at line 541 of file wasm-graph-assembler.cc.
                                                        {
  return AddNode(graph()->NewNode(simplified_.AssertNotNull(type, trap_id),
                                  object, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract().
Branch()
Node * v8::internal::compiler::WasmGraphAssembler::Branch (Node * cond, Node ** true_node, Node ** false_node, BranchHint hint)
Definition at line 45 of file wasm-graph-assembler.cc.
                                                                     {
  DCHECK_NOT_NULL(cond);
  Node* branch =
      graph()->NewNode(mcgraph()->common()->Branch(hint), cond, control());
  *true_node = graph()->NewNode(mcgraph()->common()->IfTrue(), branch);
  *false_node = graph()->NewNode(mcgraph()->common()->IfFalse(), branch);
  return branch;
}
References v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::control(), DCHECK_NOT_NULL, v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::GraphAssembler::mcgraph(), and v8::internal::compiler::TFGraph::NewNode().
BuildChangeInt32ToIntPtr()
Node * v8::internal::compiler::WasmGraphAssembler::BuildChangeInt32ToIntPtr (Node * value)
Definition at line 59 of file wasm-graph-assembler.cc.
                                                              {
  return mcgraph()->machine()->Is64() ? ChangeInt32ToInt64(value) : value;
}
References v8::internal::compiler::MachineOperatorBuilder::Is64(), v8::internal::compiler::MachineGraph::machine(), v8::internal::compiler::GraphAssembler::mcgraph(), and v8::internal::value.
Referenced by BuildChangeInt32ToSmi(), BuildChangeSmiToIntPtr(), and v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit().
BuildChangeInt32ToSmi()
Node * v8::internal::compiler::WasmGraphAssembler::BuildChangeInt32ToSmi (Node * value)
Definition at line 86 of file wasm-graph-assembler.cc.
                                                           {
  // With pointer compression, only the lower 32 bits are used.
  return COMPRESS_POINTERS_BOOL ? BitcastWord32ToWord64(Word32Shl(
                                      value, BuildSmiShiftBitsConstant32()))
                                : WordShl(BuildChangeInt32ToIntPtr(value),
                                          BuildSmiShiftBitsConstant());
}
References BuildChangeInt32ToIntPtr(), BuildSmiShiftBitsConstant(), BuildSmiShiftBitsConstant32(), COMPRESS_POINTERS_BOOL, and v8::internal::value.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern().
BuildChangeIntPtrToInt64()
Node * v8::internal::compiler::WasmGraphAssembler::BuildChangeIntPtrToInt64 (Node * value)
Definition at line 63 of file wasm-graph-assembler.cc.
                                                              {
  return mcgraph()->machine()->Is32() ? ChangeInt32ToInt64(value) : value;
}
References v8::internal::compiler::MachineOperatorBuilder::Is32(), v8::internal::compiler::MachineGraph::machine(), v8::internal::compiler::GraphAssembler::mcgraph(), and v8::internal::value.
BuildChangeSmiToInt32()
Node * v8::internal::compiler::WasmGraphAssembler::BuildChangeSmiToInt32 (Node * value)
Definition at line 101 of file wasm-graph-assembler.cc.
                                                           {
  return COMPRESS_POINTERS_BOOL
             ? Word32Sar(value, BuildSmiShiftBitsConstant32())
             : BuildTruncateIntPtrToInt32(
                   WordSar(value, BuildSmiShiftBitsConstant()));
}
References BuildSmiShiftBitsConstant(), BuildSmiShiftBitsConstant32(), BuildTruncateIntPtrToInt32(), COMPRESS_POINTERS_BOOL, and v8::internal::value.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), and v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern().
BuildChangeSmiToIntPtr()
Node * v8::internal::compiler::WasmGraphAssembler::BuildChangeSmiToIntPtr (Node * value)
Definition at line 120 of file wasm-graph-assembler.cc.
                                                            {
  return COMPRESS_POINTERS_BOOL ? BuildChangeInt32ToIntPtr(Word32Sar(
                                      value, BuildSmiShiftBitsConstant32()))
                                : WordSar(value, BuildSmiShiftBitsConstant());
}
References BuildChangeInt32ToIntPtr(), BuildSmiShiftBitsConstant(), BuildSmiShiftBitsConstant32(), COMPRESS_POINTERS_BOOL, and v8::internal::value.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck().
BuildChangeUint31ToSmi()
Node * v8::internal::compiler::WasmGraphAssembler::BuildChangeUint31ToSmi (Node * value)
Definition at line 94 of file wasm-graph-assembler.cc.
                                                            {
  return COMPRESS_POINTERS_BOOL
             ? Word32Shl(value, BuildSmiShiftBitsConstant32())
             : WordShl(BuildChangeUint32ToUintPtr(value),
                       BuildSmiShiftBitsConstant());
}
References BuildChangeUint32ToUintPtr(), BuildSmiShiftBitsConstant(), BuildSmiShiftBitsConstant32(), COMPRESS_POINTERS_BOOL, and v8::internal::value.
Referenced by BuildConvertUint32ToSmiWithSaturation().
BuildChangeUint32ToUintPtr()
Node * v8::internal::compiler::WasmGraphAssembler::BuildChangeUint32ToUintPtr (Node * node)
Definition at line 67 of file wasm-graph-assembler.cc.
                                                               {
  if (mcgraph()->machine()->Is32()) return node;
  // Fold instances of ChangeUint32ToUint64(IntConstant) directly.
  Uint32Matcher matcher(node);
  if (matcher.HasResolvedValue()) {
    uintptr_t value = matcher.ResolvedValue();
    return mcgraph()->IntPtrConstant(base::bit_cast<intptr_t>(value));
  }
  return ChangeUint32ToUint64(node);
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::MachineGraph::IntPtrConstant(), v8::internal::compiler::GraphAssembler::machine(), v8::internal::compiler::GraphAssembler::mcgraph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), and v8::internal::value.
Referenced by BuildChangeUint31ToSmi(), and LoadWasmCodePointer().
BuildConvertUint32ToSmiWithSaturation()
Node * v8::internal::compiler::WasmGraphAssembler::BuildConvertUint32ToSmiWithSaturation (Node * value, uint32_t maxval)
Definition at line 108 of file wasm-graph-assembler.cc.
                                  {
  DCHECK(Smi::IsValid(maxval));
  Node* max = mcgraph()->Uint32Constant(maxval);
  Node* check = Uint32LessThanOrEqual(value, max);
  Node* valsmi = BuildChangeUint31ToSmi(value);
  Node* maxsmi = NumberConstant(maxval);
  Diamond d(graph(), mcgraph()->common(), check, BranchHint::kTrue);
  d.Chain(control());
  return d.Phi(MachineRepresentation::kTagged, valsmi, maxsmi);
}
References BuildChangeUint31ToSmi(), v8::internal::compiler::Diamond::Chain(), v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::control(), v8::internal::DCHECK(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::Smi::IsValid(), v8::internal::kTagged, v8::internal::kTrue, v8::internal::compiler::GraphAssembler::mcgraph(), NumberConstant(), v8::internal::compiler::Diamond::Phi(), v8::internal::compiler::MachineGraph::Uint32Constant(), and v8::internal::value.
BuildDecodeSandboxedExternalPointer()
Node * v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer (Node * handle, ExternalPointerTagRange tag_range, Node * isolate_root)
Definition at line 198 of file wasm-graph-assembler.cc.
                                                                         {
#if V8_ENABLE_SANDBOX
  Node* index = Word32Shr(handle, Int32Constant(kExternalPointerIndexShift));
  Node* offset = ChangeUint32ToUint64(
      Word32Shl(index, Int32Constant(kExternalPointerTableEntrySizeLog2)));
  Node* table;
  if (IsSharedExternalPointerType(tag_range)) {
    Node* table_address =
        Load(MachineType::Pointer(), isolate_root,
             IsolateData::shared_external_pointer_table_offset());
    table = Load(MachineType::Pointer(), table_address,
                 Internals::kExternalPointerTableBasePointerOffset);
  } else {
    table = Load(MachineType::Pointer(), isolate_root,
                 IsolateData::external_pointer_table_offset() +
                     Internals::kExternalPointerTableBasePointerOffset);
  }
  // We don't expect to see empty fields here. If this is ever needed, consider
  // using an dedicated empty value entry for those tags instead (i.e. an entry
  // with the right tag and nullptr payload).
  DCHECK(!ExternalPointerCanBeEmpty(tag_range));
  Node* entry = Load(MachineType::Pointer(), table, offset);
  if (tag_range.Size() == 1) {
    // The common and simple case: we expect exactly one tag.
    Node* actual_tag = WordAnd(entry, UintPtrConstant(kExternalPointerTagMask));
    actual_tag = TruncateInt64ToInt32(
        WordShr(actual_tag, IntPtrConstant(kExternalPointerTagShift)));
    Node* expected_tag = Int32Constant(tag_range.first);
    Node* pointer = WordAnd(entry, IntPtrConstant(kExternalPointerPayloadMask));
    auto ok = MakeLabel();
    GotoIf(Word32Equal(actual_tag, expected_tag), &ok, BranchHint::kTrue);
    RuntimeAbort(AbortReason::kExternalPointerTagMismatch);
    Bind(&ok);
    return pointer;
  } else {
    // Not currently supported. Implement once needed.
    DCHECK_NE(tag_range, kAnyExternalPointerTagRange);
    UNREACHABLE();
  }
#else
  UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::compiler::GraphAssembler::Bind(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::ExternalPointerCanBeEmpty(), v8::internal::TagRange< Tag >::first, v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::handle(), v8::internal::index, v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::IsSharedExternalPointerType(), v8::internal::kAnyExternalPointerTagRange(), v8::internal::kExternalPointerPayloadMask, v8::internal::Internals::kExternalPointerTableBasePointerOffset, v8::internal::kExternalPointerTagMask, v8::internal::kExternalPointerTagShift, v8::internal::kTrue, v8::internal::compiler::GraphAssembler::Load(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::MachineType::Pointer(), v8::internal::compiler::GraphAssembler::RuntimeAbort(), v8::internal::TagRange< Tag >::Size(), v8::internal::compiler::GraphAssembler::UintPtrConstant(), v8::internal::UNREACHABLE(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by BuildLoadExternalPointerFromObject().
BuildDecodeTrustedPointer()
Node * v8::internal::compiler::WasmGraphAssembler::BuildDecodeTrustedPointer (Node * handle, IndirectPointerTag tag)
Definition at line 245 of file wasm-graph-assembler.cc.
                                                                            {
#if V8_ENABLE_SANDBOX
  Node* index = Word32Shr(handle, Int32Constant(kTrustedPointerHandleShift));
  Node* offset = ChangeUint32ToUint64(
      Word32Shl(index, Int32Constant(kTrustedPointerTableEntrySizeLog2)));
  Node* table = Load(MachineType::Pointer(), LoadRootRegister(),
                     IsolateData::trusted_pointer_table_offset() +
                         Internals::kTrustedPointerTableBasePointerOffset);
  Node* decoded_ptr = Load(MachineType::Pointer(), table, offset);
  // Untag the pointer and remove the marking bit in one operation.
  decoded_ptr = WordAnd(decoded_ptr,
                        IntPtrConstant(~(tag | kTrustedPointerTableMarkBit)));
  // We have to change the type of the result value to Tagged, so if the value
  // gets spilled on the stack, it will get processed by the GC.
  decoded_ptr = BitcastWordToTagged(decoded_ptr);
  return decoded_ptr;
#else
  UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::compiler::GraphAssembler::BitcastWordToTagged(), v8::internal::handle(), v8::internal::index, v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::kTrustedPointerHandleShift, v8::internal::Internals::kTrustedPointerTableBasePointerOffset, v8::internal::kTrustedPointerTableEntrySizeLog2, v8::internal::kTrustedPointerTableMarkBit, v8::internal::compiler::GraphAssembler::Load(), v8::internal::compiler::GraphAssembler::LoadRootRegister(), v8::internal::MachineType::Pointer(), and v8::internal::UNREACHABLE().
Referenced by LoadImmutableTrustedPointerFromObject(), LoadTrustedPointerFromObject(), and LoadTrustedPointerFromObjectTrapOnNull().
BuildLoadExternalPointerFromObject() [1/2]
Node * v8::internal::compiler::WasmGraphAssembler::BuildLoadExternalPointerFromObject (Node * object, int offset, ExternalPointerTagRange tag_range, Node * isolate_root)
Definition at line 267 of file wasm-graph-assembler.cc.
                        {
#ifdef V8_ENABLE_SANDBOX
  DCHECK(!tag_range.IsEmpty());
  Node* handle = LoadFromObject(MachineType::Uint32(), object,
                                wasm::ObjectAccess::ToTagged(field_offset));
  return BuildDecodeSandboxedExternalPointer(handle, tag_range, isolate_root);
#else
  return LoadFromObject(MachineType::Pointer(), object,
                        wasm::ObjectAccess::ToTagged(field_offset));
#endif // V8_ENABLE_SANDBOX
}
References BuildDecodeSandboxedExternalPointer(), v8::internal::DCHECK(), v8::internal::handle(), v8::internal::TagRange< Tag >::IsEmpty(), LoadFromObject(), v8::internal::MachineType::Pointer(), v8::internal::wasm::ObjectAccess::ToTagged(), and v8::internal::MachineType::Uint32().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit().
BuildLoadExternalPointerFromObject() [2/2]
Node* v8::internal::compiler::WasmGraphAssembler::BuildLoadExternalPointerFromObject (Node * object, int offset, Node * index, ExternalPointerTagRange tag_range, Node * isolate_root)
BuildSmiShiftBitsConstant()
Node * v8::internal::compiler::WasmGraphAssembler::BuildSmiShiftBitsConstant ()
Definition at line 78 of file wasm-graph-assembler.cc.
                                                    {
  return IntPtrConstant(kSmiShiftSize + kSmiTagSize);
}
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::kSmiShiftSize, and v8::internal::kSmiTagSize.
Referenced by BuildChangeInt32ToSmi(), BuildChangeSmiToInt32(), BuildChangeSmiToIntPtr(), and BuildChangeUint31ToSmi().
BuildSmiShiftBitsConstant32()
Node * v8::internal::compiler::WasmGraphAssembler::BuildSmiShiftBitsConstant32 ()
Definition at line 82 of file wasm-graph-assembler.cc.
                                                      {
  return Int32Constant(kSmiShiftSize + kSmiTagSize);
}
References v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::kSmiShiftSize, and v8::internal::kSmiTagSize.
Referenced by BuildChangeInt32ToSmi(), BuildChangeSmiToInt32(), BuildChangeSmiToIntPtr(), and BuildChangeUint31ToSmi().
BuildTruncateIntPtrToInt32()
Node * v8::internal::compiler::WasmGraphAssembler::BuildTruncateIntPtrToInt32 (Node * value)
Definition at line 55 of file wasm-graph-assembler.cc.
                                                                {
  return mcgraph()->machine()->Is64() ? TruncateInt64ToInt32(value) : value;
}
References v8::internal::compiler::MachineOperatorBuilder::Is64(), v8::internal::compiler::MachineGraph::machine(), v8::internal::compiler::GraphAssembler::mcgraph(), and v8::internal::value.
Referenced by BuildChangeSmiToInt32().
CallBuiltin()
template<typename... Args>
Node* v8::internal::compiler::WasmGraphAssembler::CallBuiltin (Builtin name, Operator::Properties properties, Args... args) [inline]
Definition at line 56 of file wasm-graph-assembler.h.
                                  {
    return CallBuiltinImpl(name, false, properties, args...);
  }
References v8::base::args, CallBuiltinImpl(), and v8::internal::name.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), and v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern().
CallBuiltinImpl()
template<typename... Args>
Node* v8::internal::compiler::WasmGraphAssembler::CallBuiltinImpl (Builtin name, bool needs_frame_state, Operator::Properties properties, Args... args) [inline], [private]
Definition at line 339 of file wasm-graph-assembler.h.
                                                                     {
    auto* call_descriptor = GetBuiltinCallDescriptor(
        name, temp_zone(), StubCallMode::kCallBuiltinPointer, needs_frame_state,
        properties);
    Node* call_target = GetBuiltinPointerTarget(name);
    return Call(call_descriptor, call_target, args...);
  }
References v8::base::args, v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::GetBuiltinCallDescriptor(), GetBuiltinPointerTarget(), v8::internal::kCallBuiltinPointer, v8::internal::name, and v8::internal::compiler::GraphAssembler::temp_zone().
Referenced by CallBuiltin(), and CallBuiltinWithFrameState().
CallBuiltinThroughJumptable()
template<typename... Args>
Node* v8::internal::compiler::WasmGraphAssembler::CallBuiltinThroughJumptable (Builtin builtin, Operator::Properties properties, Args... args) [inline]
Definition at line 38 of file wasm-graph-assembler.h.
                                                  {
    auto* call_descriptor = GetBuiltinCallDescriptor(
        builtin, temp_zone(), StubCallMode::kCallWasmRuntimeStub, false,
        properties);
    // A direct call to a wasm runtime stub defined in this module.
    // Just encode the stub index. This will be patched at relocation.
    Node* call_target = mcgraph()->RelocatableWasmBuiltinCallTarget(builtin);
    return Call(call_descriptor, call_target, args...);
  }
References v8::base::args, v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::GetBuiltinCallDescriptor(), v8::internal::compiler::GraphAssembler::mcgraph(), v8::internal::compiler::MachineGraph::RelocatableWasmBuiltinCallTarget(), and v8::internal::compiler::GraphAssembler::temp_zone().
CallBuiltinWithFrameState()
template<typename... Args>
Node* v8::internal::compiler::WasmGraphAssembler::CallBuiltinWithFrameState (Builtin name, Operator::Properties properties, Node * frame_state, Args... args) [inline]
Definition at line 62 of file wasm-graph-assembler.h.
                                                                   {
    DCHECK_EQ(frame_state->opcode(), IrOpcode::kFrameState);
    return CallBuiltinImpl(name, true, properties, frame_state, args...);
  }
References v8::base::args, CallBuiltinImpl(), DCHECK_EQ, v8::internal::name, and v8::internal::compiler::Node::opcode().
FieldOffset()
Node * v8::internal::compiler::WasmGraphAssembler::FieldOffset (const wasm::StructType * type, uint32_t field_index)
Definition at line 478 of file wasm-graph-assembler.cc.
                                                            {
  return IntPtrConstant(wasm::ObjectAccess::ToTagged(
      WasmStruct::kHeaderSize + type->field_offset(field_index)));
}
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::wasm::ObjectAccess::ToTagged(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), and v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet().
GetBuiltinPointerTarget()
Node* v8::internal::compiler::WasmGraphAssembler::GetBuiltinPointerTarget (Builtin builtin) [inline]
Definition at line 50 of file wasm-graph-assembler.h.
                                                 {
    static_assert(std::is_same_v<Smi, BuiltinPtr>, "BuiltinPtr must be Smi");
    return NumberConstant(static_cast<int>(builtin));
  }
References NumberConstant().
Referenced by CallBuiltinImpl().
HasInstanceType()
Node * v8::internal::compiler::WasmGraphAssembler::HasInstanceType (Node * heap_object, InstanceType type)
Definition at line 622 of file wasm-graph-assembler.cc.
                                                             {
  Node* map = LoadMap(heap_object);
  Node* instance_type = LoadInstanceType(map);
  return Word32Equal(instance_type, Int32Constant(type));
}
References v8::internal::compiler::GraphAssembler::Int32Constant(), LoadInstanceType(), LoadMap(), v8::internal::tracing::type, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract().
InitializeImmutableInObject() [1/2]
Node* v8::internal::compiler::WasmGraphAssembler::InitializeImmutableInObject (ObjectAccess access, Node * base, int offset, Node * value) [inline]
Definition at line 161 of file wasm-graph-assembler.h.
                                                 {
    return InitializeImmutableInObject(access, base, IntPtrConstant(offset),
                                       value);
  }
References InitializeImmutableInObject(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), and v8::internal::value.
InitializeImmutableInObject() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::InitializeImmutableInObject (ObjectAccess access, Node * base, Node * offset, Node * value)
Definition at line 190 of file wasm-graph-assembler.cc.
                                                                   {
  return AddNode(
      graph()->NewNode(simplified_.InitializeImmutableInObject(access), base,
                       offset, value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::SimplifiedOperatorBuilder::InitializeImmutableInObject(), simplified_, and v8::internal::value.
Referenced by InitializeImmutableInObject(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), and StoreMap().
IsDataRefMap()
Node * v8::internal::compiler::WasmGraphAssembler::IsDataRefMap (Node * map)
Definition at line 493 of file wasm-graph-assembler.cc.
                                                {
  Node* instance_type = LoadInstanceType(map);
  // We're going to test a range of WasmObject instance types with a single
  // unsigned comparison.
  Node* comparison_value =
      Int32Sub(instance_type, Int32Constant(FIRST_WASM_OBJECT_TYPE));
  return Uint32LessThanOrEqual(
      comparison_value,
      Int32Constant(LAST_WASM_OBJECT_TYPE - FIRST_WASM_OBJECT_TYPE));
}
References v8::internal::compiler::GraphAssembler::Int32Constant(), and LoadInstanceType().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract().
IsNotNull()
Node * v8::internal::compiler::WasmGraphAssembler::IsNotNull (Node * object, wasm::ValueType type)
Definition at line 536 of file wasm-graph-assembler.cc.
                                                                    {
  return AddNode(
      graph()->NewNode(simplified_.IsNotNull(type), object, control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::graph(), simplified_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract().
IsNull()
Node * v8::internal::compiler::WasmGraphAssembler::IsNull (Node * object, wasm::ValueType type)
Definition at line 532 of file wasm-graph-assembler.cc.
                                                                 {
  return AddNode(graph()->NewNode(simplified_.IsNull(type), object, control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::graph(), simplified_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract().
IsSmi()
Node * v8::internal::compiler::WasmGraphAssembler::IsSmi (Node * object)
Definition at line 281 of file wasm-graph-assembler.cc.
                                            {
  if (COMPRESS_POINTERS_BOOL) {
    return Word32Equal(Word32And(object, Int32Constant(kSmiTagMask)),
                       Int32Constant(kSmiTag));
  } else {
    return WordEqual(WordAnd(object, IntPtrConstant(kSmiTagMask)),
                     IntPtrConstant(kSmiTag));
  }
}
References COMPRESS_POINTERS_BOOL, v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::kSmiTag, v8::internal::kSmiTagMask, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract().
LoadByteArrayElement()
Node * v8::internal::compiler::WasmGraphAssembler::LoadByteArrayElement (Node * byte_array, Node * index_intptr, MachineType type)
Definition at line 378 of file wasm-graph-assembler.cc.
                                                                 {
  int element_size = ElementSizeInBytes(type.representation());
  Node* offset = IntAdd(IntMul(index_intptr, IntPtrConstant(element_size)),
                        IntPtrConstant(wasm::ObjectAccess::ToTagged(
                            OFFSET_OF_DATA_START(ByteArray))));
  return LoadFromObject(type, byte_array, offset);
}
References v8::internal::ElementSizeInBytes(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), LoadFromObject(), OFFSET_OF_DATA_START, v8::internal::wasm::ObjectAccess::ToTagged(), and v8::internal::tracing::type.
LoadContextNoCellFromJSFunction()
Node * v8::internal::compiler::WasmGraphAssembler::LoadContextNoCellFromJSFunction (Node * js_function)
Definition at line 439 of file wasm-graph-assembler.cc.
                                                                           {
  return LoadFromObject(MachineType::TaggedPointer(), js_function,
                        wasm::ObjectAccess::ContextOffsetInTaggedJSFunction());
}
References v8::internal::wasm::ObjectAccess::ContextOffsetInTaggedJSFunction(), LoadFromObject(), and v8::internal::MachineType::TaggedPointer().
LoadExportedFunctionIndexAsSmi()
Node * v8::internal::compiler::WasmGraphAssembler::LoadExportedFunctionIndexAsSmi (Node * exported_function_data)
Definition at line 453 of file wasm-graph-assembler.cc.
                                  {
  return LoadImmutableFromObject(
      MachineType::TaggedSigned(), exported_function_data,
      wasm::ObjectAccess::ToTagged(
          WasmExportedFunctionData::kFunctionIndexOffset));
}
References LoadImmutableFromObject(), v8::internal::MachineType::TaggedSigned(), and v8::internal::wasm::ObjectAccess::ToTagged().
LoadExportedFunctionInstanceData()
Node * v8::internal::compiler::WasmGraphAssembler::LoadExportedFunctionInstanceData (Node * exported_function_data)
Definition at line 460 of file wasm-graph-assembler.cc.
                                  {
  return LoadImmutableProtectedPointerFromObject(
      exported_function_data,
      wasm::ObjectAccess::ToTagged(
          WasmExportedFunctionData::kProtectedInstanceDataOffset));
}
References LoadImmutableProtectedPointerFromObject(), and v8::internal::wasm::ObjectAccess::ToTagged().
LoadFixedArrayElement() [1/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElement (Node * array, int index, MachineType type)
Definition at line 358 of file wasm-graph-assembler.cc.
                                                                  {
  return LoadFromObject(
      type, array, wasm::ObjectAccess::ElementOffsetInTaggedFixedArray(index));
}
References v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedFixedArray(), v8::internal::index, LoadFromObject(), and v8::internal::tracing::type.
LoadFixedArrayElement() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElement (Node * fixed_array, Node * index_intptr, MachineType type = MachineType::AnyTagged())
Definition at line 331 of file wasm-graph-assembler.cc.
                                                                  {
  DCHECK(IsSubtype(type.representation(), MachineRepresentation::kTagged));
  Node* offset = IntAdd(IntMul(index_intptr, IntPtrConstant(kTaggedSize)),
                        IntPtrConstant(wasm::ObjectAccess::ToTagged(
                            OFFSET_OF_DATA_START(FixedArray))));
  return LoadFromObject(type, fixed_array, offset);
}
References v8::internal::DCHECK(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::IsSubtype(), v8::internal::kTagged, v8::internal::kTaggedSize, LoadFromObject(), OFFSET_OF_DATA_START, v8::internal::wasm::ObjectAccess::ToTagged(), and v8::internal::tracing::type.
Referenced by LoadFixedArrayElementAny(), LoadFixedArrayElementPtr(), and LoadFixedArrayElementSmi().
LoadFixedArrayElementAny()
Node* v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElementAny (Node * array, int index) [inline]
Definition at line 222 of file wasm-graph-assembler.h.
                                                         {
    return LoadFixedArrayElement(array, index, MachineType::AnyTagged());
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::index, and LoadFixedArrayElement().
LoadFixedArrayElementPtr()
Node* v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElementPtr (Node * array, int index) [inline]
Definition at line 218 of file wasm-graph-assembler.h.
                                                         {
    return LoadFixedArrayElement(array, index, MachineType::TaggedPointer());
  }
References v8::internal::index, LoadFixedArrayElement(), and v8::internal::MachineType::TaggedPointer().
LoadFixedArrayElementSmi()
Node* v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElementSmi (Node * array, int index) [inline]
Definition at line 214 of file wasm-graph-assembler.h.
                                                         {
    return LoadFixedArrayElement(array, index, MachineType::TaggedSigned());
  }
References v8::internal::index, LoadFixedArrayElement(), and v8::internal::MachineType::TaggedSigned().
LoadFixedArrayLengthAsSmi()
Node * v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayLengthAsSmi (Node * fixed_array)
Definition at line 325 of file wasm-graph-assembler.cc.
                                                                     {
  return LoadImmutableFromObject(
      MachineType::TaggedSigned(), fixed_array,
      wasm::ObjectAccess::ToTagged(offsetof(FixedArray, length_)));
}
References LoadImmutableFromObject(), v8::internal::MachineType::TaggedSigned(), and v8::internal::wasm::ObjectAccess::ToTagged().
LoadFromObject() [1/2]
Node* v8::internal::compiler::WasmGraphAssembler::LoadFromObject (MachineType type, Node * base, int offset) [inline]
Definition at line 121 of file wasm-graph-assembler.h.
                                                                 {
    return LoadFromObject(type, base, IntPtrConstant(offset));
  }
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), LoadFromObject(), and v8::internal::tracing::type.
LoadFromObject() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadFromObject (MachineType type, Node * base, Node * offset)
Definition at line 140 of file wasm-graph-assembler.cc.
                                                       {
  return AddNode(graph()->NewNode(
      simplified_.LoadFromObject(ObjectAccess(type, kNoWriteBarrier)), base,
      offset, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::SimplifiedOperatorBuilder::LoadFromObject(), simplified_, and v8::internal::tracing::type.
Referenced by BuildLoadExternalPointerFromObject(), LoadByteArrayElement(), LoadContextNoCellFromJSFunction(), LoadFixedArrayElement(), LoadFromObject(), LoadJSArrayElements(), LoadProtectedPointerFromObject(), LoadTrustedPointerFromObject(), LoadWeakFixedArrayElement(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), and v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet().
LoadFunctionDataFromJSFunction()
Node * v8::internal::compiler::WasmGraphAssembler::LoadFunctionDataFromJSFunction (Node * js_function)
Definition at line 444 of file wasm-graph-assembler.cc.
                                                                          {
  Node* shared = LoadSharedFunctionInfo(js_function);
  return LoadImmutableTrustedPointerFromObject(
      shared,
      wasm::ObjectAccess::ToTagged(
          SharedFunctionInfo::kTrustedFunctionDataOffset),
      kWasmFunctionDataIndirectPointerTag);
}
References LoadImmutableTrustedPointerFromObject(), LoadSharedFunctionInfo(), and v8::internal::wasm::ObjectAccess::ToTagged().
LoadImmutable() [1/2]
Node* v8::internal::compiler::WasmGraphAssembler::LoadImmutable (LoadRepresentation rep, Node * base, int offset) [inline]
Definition at line 144 of file wasm-graph-assembler.h.
                                                                      {
    return LoadImmutable(rep, base, IntPtrConstant(offset));
  }
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), and LoadImmutable().
LoadImmutable() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadImmutable (LoadRepresentation rep, Node * base, Node * offset)
Definition at line 169 of file wasm-graph-assembler.cc.
                                                      {
  return AddNode(
      graph()->NewNode(mcgraph()->machine()->LoadImmutable(rep), base, offset));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::GraphAssembler::machine(), and v8::internal::compiler::GraphAssembler::mcgraph().
Referenced by LoadImmutable(), v8::internal::compiler::WasmGCLowering::Null(), and v8::internal::compiler::WasmGCLowering::ReduceRttCanon().
LoadImmutableFixedArrayElement()
Node * v8::internal::compiler::WasmGraphAssembler::LoadImmutableFixedArrayElement (Node * fixed_array, Node * index_intptr, MachineType type = MachineType::AnyTagged())
Definition at line 349 of file wasm-graph-assembler.cc.
                                                                           {
  Node* offset = IntAdd(IntMul(index_intptr, IntPtrConstant(kTaggedSize)),
                        IntPtrConstant(wasm::ObjectAccess::ToTagged(
                            OFFSET_OF_DATA_START(FixedArray))));
  return LoadImmutableFromObject(type, fixed_array, offset);
}
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::kTaggedSize, LoadImmutableFromObject(), OFFSET_OF_DATA_START, v8::internal::wasm::ObjectAccess::ToTagged(), and v8::internal::tracing::type.
LoadImmutableFromObject() [1/2]
Node* v8::internal::compiler::WasmGraphAssembler::LoadImmutableFromObject (MachineType type, Node * base, int offset) [inline]
Definition at line 138 of file wasm-graph-assembler.h.
                                                                          {
    return LoadImmutableFromObject(type, base, IntPtrConstant(offset));
  }
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), LoadImmutableFromObject(), and v8::internal::tracing::type.
LoadImmutableFromObject() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadImmutableFromObject (MachineType type, Node * base, Node * offset)
Definition at line 162 of file wasm-graph-assembler.cc.
                                                                {
  return AddNode(graph()->NewNode(
      simplified_.LoadImmutableFromObject(ObjectAccess(type, kNoWriteBarrier)),
      base, offset, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::SimplifiedOperatorBuilder::LoadImmutableFromObject(), simplified_, and v8::internal::tracing::type.
Referenced by LoadExportedFunctionIndexAsSmi(), LoadFixedArrayLengthAsSmi(), LoadImmutableFixedArrayElement(), LoadImmutableFromObject(), LoadImmutableProtectedPointerFromObject(), LoadImmutableTrustedPointerFromObject(), LoadInstanceType(), LoadMap(), LoadSharedFunctionInfo(), LoadStringLength(), LoadWasmTypeInfo(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck().
LoadImmutableProtectedPointerFromObject() [1/2]
Node* v8::internal::compiler::WasmGraphAssembler::LoadImmutableProtectedPointerFromObject (Node * object, int offset) [inline]
Definition at line 131 of file wasm-graph-assembler.h.
                                                                          {
    return LoadImmutableProtectedPointerFromObject(object,
                                                   IntPtrConstant(offset));
  }
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), and LoadImmutableProtectedPointerFromObject().
LoadImmutableProtectedPointerFromObject() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadImmutableProtectedPointerFromObject (Node * object, Node * offset)
Definition at line 154 of file wasm-graph-assembler.cc.
                                {
  return LoadImmutableFromObject(V8_ENABLE_SANDBOX_BOOL
                                     ? MachineType::ProtectedPointer()
                                     : MachineType::AnyTagged(),
                                 object, offset);
}
References v8::internal::MachineType::AnyTagged(), LoadImmutableFromObject(), v8::internal::MachineType::ProtectedPointer(), and V8_ENABLE_SANDBOX_BOOL.
Referenced by LoadExportedFunctionInstanceData(), and LoadImmutableProtectedPointerFromObject().
LoadImmutableTrustedPointerFromObject()
Node * v8::internal::compiler::WasmGraphAssembler::LoadImmutableTrustedPointerFromObject (Node * object, int offset, IndirectPointerTag tag)
Definition at line 388 of file wasm-graph-assembler.cc.
                                                            {
  Node* offset = IntPtrConstant(field_offset);
#ifdef V8_ENABLE_SANDBOX
  Node* handle = LoadImmutableFromObject(MachineType::Uint32(), object, offset);
  return BuildDecodeTrustedPointer(handle, tag);
#else
  return LoadImmutableFromObject(MachineType::TaggedPointer(), object, offset);
#endif
}
References BuildDecodeTrustedPointer(), v8::internal::handle(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), LoadImmutableFromObject(), v8::internal::MachineType::TaggedPointer(), and v8::internal::MachineType::Uint32().
Referenced by LoadFunctionDataFromJSFunction(), and LoadTrustedDataFromInstanceObject().
LoadInstanceType()
Node * v8::internal::compiler::WasmGraphAssembler::LoadInstanceType (Node * map)
Definition at line 312 of file wasm-graph-assembler.cc.
                                                    {
  return LoadImmutableFromObject(
      MachineType::Uint16(), map,
      wasm::ObjectAccess::ToTagged(Map::kInstanceTypeOffset));
}
References LoadImmutableFromObject(), v8::internal::wasm::ObjectAccess::ToTagged(), and v8::internal::MachineType::Uint16().
Referenced by HasInstanceType(), IsDataRefMap(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract().
LoadJSArrayElements()
Node * v8::internal::compiler::WasmGraphAssembler::LoadJSArrayElements (Node * js_array)
Definition at line 470 of file wasm-graph-assembler.cc.
                                                            {
  return LoadFromObject(
      MachineType::AnyTagged(), js_array,
      wasm::ObjectAccess::ToTagged(JSObject::kElementsOffset));
}
References v8::internal::MachineType::AnyTagged(), LoadFromObject(), and v8::internal::wasm::ObjectAccess::ToTagged().
LoadMap()
Node * v8::internal::compiler::WasmGraphAssembler::LoadMap (Node * object)
Definition at line 292 of file wasm-graph-assembler.cc.
                                              {
  Node* map_word =
      LoadImmutableFromObject(MachineType::TaggedPointer(), object,
                              HeapObject::kMapOffset - kHeapObjectTag);
#ifdef V8_MAP_PACKING
  return UnpackMapWord(map_word);
#else
  return map_word;
#endif
}
References v8::internal::kHeapObjectTag, v8::internal::HeapObject::kMapOffset, LoadImmutableFromObject(), and v8::internal::MachineType::TaggedPointer().
Referenced by HasInstanceType(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract().
LoadProtectedFixedArrayElement() [1/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadProtectedFixedArrayElement (Node * array, int index)
Definition at line 364 of file wasm-graph-assembler.cc.
                                                                    {
  return LoadProtectedPointerFromObject(
      array, wasm::ObjectAccess::ElementOffsetInProtectedFixedArray(index));
}
References v8::internal::wasm::ObjectAccess::ElementOffsetInProtectedFixedArray(), v8::internal::index, and LoadProtectedPointerFromObject().
LoadProtectedFixedArrayElement() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadProtectedFixedArrayElement (Node * array, Node * index_intptr)
Definition at line 370 of file wasm-graph-assembler.cc.
                                                                             {
  Node* offset = IntAdd(WordShl(index_intptr, IntPtrConstant(kTaggedSizeLog2)),
                        IntPtrConstant(wasm::ObjectAccess::ToTagged(
                            OFFSET_OF_DATA_START(ProtectedFixedArray))));
  return LoadProtectedPointerFromObject(array, offset);
}
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::kTaggedSizeLog2, LoadProtectedPointerFromObject(), OFFSET_OF_DATA_START, and v8::internal::wasm::ObjectAccess::ToTagged().
LoadProtectedPointerFromObject() [1/2]
Node* v8::internal::compiler::WasmGraphAssembler::LoadProtectedPointerFromObject (Node * object, int offset) [inline]
Definition at line 126 of file wasm-graph-assembler.h.
                                                                 {
    return LoadProtectedPointerFromObject(object, IntPtrConstant(offset));
  }
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), and LoadProtectedPointerFromObject().
LoadProtectedPointerFromObject() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::LoadProtectedPointerFromObject (Node * object, Node * offset)
Definition at line 147 of file wasm-graph-assembler.cc.
                                                                       {
  return LoadFromObject(V8_ENABLE_SANDBOX_BOOL ? MachineType::ProtectedPointer()
                                               : MachineType::AnyTagged(),
                        object, offset);
}
References v8::internal::MachineType::AnyTagged(), LoadFromObject(), v8::internal::MachineType::ProtectedPointer(), and V8_ENABLE_SANDBOX_BOOL.
Referenced by LoadProtectedFixedArrayElement(), and LoadProtectedPointerFromObject().
LoadSharedFunctionInfo()
Node * v8::internal::compiler::WasmGraphAssembler::LoadSharedFunctionInfo (Node * js_function)
Definition at line 434 of file wasm-graph-assembler.cc.
                                                                  {
  return LoadImmutableFromObject(
      MachineType::TaggedPointer(), js_function,
      wasm::ObjectAccess::SharedFunctionInfoOffsetInTaggedJSFunction());
}
References LoadImmutableFromObject(), v8::internal::wasm::ObjectAccess::SharedFunctionInfoOffsetInTaggedJSFunction(), and v8::internal::MachineType::TaggedPointer().
Referenced by LoadFunctionDataFromJSFunction().
LoadStringLength()
Node * v8::internal::compiler::WasmGraphAssembler::LoadStringLength (Node * string)
Definition at line 596 of file wasm-graph-assembler.cc.
                                                       {
  return LoadImmutableFromObject(
      MachineType::Int32(), string,
      wasm::ObjectAccess::ToTagged(AccessBuilder::ForStringLength().offset));
}
References v8::internal::compiler::AccessBuilder::ForStringLength(), v8::internal::MachineType::Int32(), LoadImmutableFromObject(), and v8::internal::wasm::ObjectAccess::ToTagged().
LoadTrustedDataFromInstanceObject()
Node * v8::internal::compiler::WasmGraphAssembler::LoadTrustedDataFromInstanceObject (Node * instance_object)
Definition at line 612 of file wasm-graph-assembler.cc.
                           {
  return LoadImmutableTrustedPointerFromObject(
      instance_object,
      wasm::ObjectAccess::ToTagged(WasmInstanceObject::kTrustedDataOffset),
      kWasmTrustedInstanceDataIndirectPointerTag);
}
References v8::internal::instance_object, LoadImmutableTrustedPointerFromObject(), and v8::internal::wasm::ObjectAccess::ToTagged().
LoadTrustedPointerFromObject()
Node * v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObject (Node * object, int offset, IndirectPointerTag tag)
Definition at line 399 of file wasm-graph-assembler.cc.
                                                                               {
  Node* offset = IntPtrConstant(field_offset);
#ifdef V8_ENABLE_SANDBOX
  Node* handle = LoadFromObject(MachineType::Uint32(), object, offset);
  return BuildDecodeTrustedPointer(handle, tag);
#else
  return LoadFromObject(MachineType::TaggedPointer(), object, offset);
#endif
}
References BuildDecodeTrustedPointer(), v8::internal::handle(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), LoadFromObject(), v8::internal::MachineType::TaggedPointer(), and v8::internal::MachineType::Uint32().
LoadTrustedPointerFromObjectTrapOnNull()
std::pair< Node *, Node * > v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObjectTrapOnNull (Node * object, int offset, IndirectPointerTag tag)
Definition at line 412 of file wasm-graph-assembler.cc.
                                                            {
  Node* offset = IntPtrConstant(field_offset);
#ifdef V8_ENABLE_SANDBOX
  Node* handle = LoadTrapOnNull(MachineType::Uint32(), object, offset);
  return {handle, BuildDecodeTrustedPointer(handle, tag)};
#else
  Node* value = LoadTrapOnNull(MachineType::TaggedPointer(), object, offset);
  return {value, value};
#endif
}
References BuildDecodeTrustedPointer(), v8::internal::handle(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::compiler::GraphAssembler::LoadTrapOnNull(), v8::internal::MachineType::TaggedPointer(), v8::internal::MachineType::Uint32(), and v8::internal::value.
LoadWasmCodePointer()
Node * v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer (Node * code_pointer)
Definition at line 175 of file wasm-graph-assembler.cc.
                                                                {
  Node* table_entry =
      IntAdd(ExternalConstant(ExternalReference::wasm_code_pointer_table()),
             IntMul(BuildChangeUint32ToUintPtr(code_pointer),
                    UintPtrConstant(sizeof(wasm::WasmCodePointerTableEntry))));
  return AddNode(graph()->NewNode(
      mcgraph()->machine()->Load(LoadRepresentation::UintPtr()), table_entry));
}
References v8::internal::compiler::GraphAssembler::AddNode(), BuildChangeUint32ToUintPtr(), v8::internal::compiler::GraphAssembler::ExternalConstant(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::GraphAssembler::Load(), v8::internal::compiler::GraphAssembler::machine(), v8::internal::compiler::GraphAssembler::mcgraph(), v8::internal::MachineType::UintPtr(), and v8::internal::compiler::GraphAssembler::UintPtrConstant().
LoadWasmTypeInfo()
Node * v8::internal::compiler::WasmGraphAssembler::LoadWasmTypeInfo (Node * map)
Definition at line 317 of file wasm-graph-assembler.cc.
                                                    {
  int offset = Map::kConstructorOrBackPointerOrNativeContextOffset;
  return LoadImmutableFromObject(MachineType::TaggedPointer(), map,
                                 wasm::ObjectAccess::ToTagged(offset));
}
References v8::internal::kConstructorOrBackPointerOrNativeContextOffset, LoadImmutableFromObject(), v8::internal::MachineType::TaggedPointer(), and v8::internal::wasm::ObjectAccess::ToTagged().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck().
LoadWeakFixedArrayElement()
Node * v8::internal::compiler::WasmGraphAssembler::LoadWeakFixedArrayElement (Node * fixed_array, Node * index_intptr)
Definition at line 341 of file wasm-graph-assembler.cc.
                                                                        {
  Node* offset = IntAdd(IntMul(index_intptr, IntPtrConstant(kTaggedSize)),
                        IntPtrConstant(wasm::ObjectAccess::ToTagged(
                            OFFSET_OF_DATA_START(WeakFixedArray))));
  return LoadFromObject(MachineType::AnyTagged(), fixed_array, offset);
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::kTaggedSize, LoadFromObject(), OFFSET_OF_DATA_START, and v8::internal::wasm::ObjectAccess::ToTagged().
MergeControlToEnd()
void v8::internal::compiler::WasmGraphAssembler::MergeControlToEnd (Node * control) [inline]
Definition at line 84 of file wasm-graph-assembler.h.
                                        {
    NodeProperties::MergeControlToEnd(graph(), common(), control);
  }
References v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::graph(), and v8::internal::compiler::NodeProperties::MergeControlToEnd().
Null()
Node * v8::internal::compiler::WasmGraphAssembler::Null (wasm::ValueType type)
Definition at line 528 of file wasm-graph-assembler.cc.
                                                 {
  return AddNode(graph()->NewNode(simplified_.Null(type)));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::graph(), simplified_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract().
NumberConstant()
Node* v8::internal::compiler::WasmGraphAssembler::NumberConstant (double value) [inline]
Definition at line 73 of file wasm-graph-assembler.h.
                                     {
    return graph()->NewNode(mcgraph()->common()->NumberConstant(value));
  }
References v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::GraphAssembler::mcgraph(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by BuildConvertUint32ToSmiWithSaturation(), and GetBuiltinPointerTarget().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::WasmGraphAssembler::simplified () [inline], [override], [virtual]
Reimplemented from v8::internal::compiler::GraphAssembler.
Definition at line 335 of file wasm-graph-assembler.h.
{ return &simplified_; }
References simplified_.
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), and v8::internal::compiler::WasmGCOperatorReducer::simplified().
SmiConstant()
Node* v8::internal::compiler::WasmGraphAssembler::SmiConstant (Tagged_t value) [inline]
Definition at line 77 of file wasm-graph-assembler.h.
                                    {
    Address tagged_value = Internals::IntegralToSmi(static_cast<int>(value));
    return kTaggedSize == kInt32Size
               ? Int32Constant(static_cast<int32_t>(tagged_value))
               : Int64Constant(static_cast<int64_t>(tagged_value));
  }
References v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::compiler::GraphAssembler::Int64Constant(), v8::internal::Internals::IntegralToSmi(), v8::internal::kInt32Size, v8::internal::kTaggedSize, and v8::internal::value.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit().
StoreFixedArrayElement()
Node * v8::internal::compiler::WasmGraphAssembler::StoreFixedArrayElement (Node * array, int index, Node * value, ObjectAccess access)
Definition at line 424 of file wasm-graph-assembler.cc.
                                                                      {
  return StoreToObject(
      access, array, wasm::ObjectAccess::ElementOffsetInTaggedFixedArray(index),
      value);
}
References v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedFixedArray(), v8::internal::index, StoreToObject(), and v8::internal::value.
Referenced by StoreFixedArrayElementAny(), and StoreFixedArrayElementSmi().
StoreFixedArrayElementAny()
Node* v8::internal::compiler::WasmGraphAssembler::StoreFixedArrayElementAny (Node * array, int index, Node * value) [inline]
Definition at line 241 of file wasm-graph-assembler.h.
                                                                       {
    return StoreFixedArrayElement(
        array, index, value,
        ObjectAccess(MachineType::AnyTagged(), kFullWriteBarrier));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::index, v8::internal::compiler::kFullWriteBarrier, StoreFixedArrayElement(), and v8::internal::value.
StoreFixedArrayElementSmi()
Node* v8::internal::compiler::WasmGraphAssembler::StoreFixedArrayElementSmi (Node * array, int index, Node * value) [inline]
Definition at line 235 of file wasm-graph-assembler.h.
                                                                       {
    return StoreFixedArrayElement(
        array, index, value,
        ObjectAccess(MachineType::TaggedSigned(), kNoWriteBarrier));
  }
References v8::internal::index, v8::internal::compiler::kNoWriteBarrier, StoreFixedArrayElement(), v8::internal::MachineType::TaggedSigned(), and v8::internal::value.
StoreMap()
void v8::internal::compiler::WasmGraphAssembler::StoreMap (Node * heap_object, Node * map)
Definition at line 303 of file wasm-graph-assembler.cc.
                                                              {
  ObjectAccess access(MachineType::TaggedPointer(), kMapWriteBarrier);
#ifdef V8_MAP_PACKING
  map = PackMapWord(TNode<Map>::UncheckedCast(map));
#endif
  InitializeImmutableInObject(access, heap_object,
                              HeapObject::kMapOffset - kHeapObjectTag, map);
}
References InitializeImmutableInObject(), v8::internal::kHeapObjectTag, v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kMapWriteBarrier, and v8::internal::MachineType::TaggedPointer().
StoreToObject() [1/2]
Node* v8::internal::compiler::WasmGraphAssembler::StoreToObject (ObjectAccess access, Node * base, int offset, Node * value) [inline]
Definition at line 153 of file wasm-graph-assembler.h.
                                   {
    return StoreToObject(access, base, IntPtrConstant(offset), value);
  }
References v8::internal::compiler::GraphAssembler::IntPtrConstant(), StoreToObject(), and v8::internal::value.
StoreToObject() [2/2]
Node * v8::internal::compiler::WasmGraphAssembler::StoreToObject (ObjectAccess access, Node * base, Node * offset, Node * value)
Definition at line 184 of file wasm-graph-assembler.cc.
                                                                   {
  return AddNode(graph()->NewNode(simplified_.StoreToObject(access), base,
                                  offset, value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified_, v8::internal::compiler::SimplifiedOperatorBuilder::StoreToObject(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), StoreFixedArrayElement(), and StoreToObject().
StringAsWtf16()
Node * v8::internal::compiler::WasmGraphAssembler::StringAsWtf16 (Node * string)
Definition at line 602 of file wasm-graph-assembler.cc.
                                                    {
  return AddNode(graph()->NewNode(simplified_.StringAsWtf16(), string, effect(),
                                  control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
StringPrepareForGetCodeunit()
Node * v8::internal::compiler::WasmGraphAssembler::StringPrepareForGetCodeunit (Node * string)
Definition at line 607 of file wasm-graph-assembler.cc.
                                                                  {
  return AddNode(graph()->NewNode(simplified_.StringPrepareForGetCodeunit(),
                                  string, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
StructGet()
Node * v8::internal::compiler::WasmGraphAssembler::StructGet (Node * object, const wasm::StructType * type, int field_index, bool is_signed, CheckForNull null_check)
Definition at line 557 of file wasm-graph-assembler.cc.
                                                             {
  return AddNode(graph()->NewNode(
      simplified_.WasmStructGet(type, field_index, is_signed, null_check),
      object, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::is_signed(), simplified_, and v8::internal::tracing::type.
StructSet()
void v8::internal::compiler::WasmGraphAssembler::StructSet (Node * object, Node * value, const wasm::StructType * type, int field_index, CheckForNull null_check)
Definition at line 565 of file wasm-graph-assembler.cc.
                                                                             {
  AddNode(
      graph()->NewNode(simplified_.WasmStructSet(type, field_index, null_check),
                       object, value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified_, v8::internal::tracing::type, and v8::internal::value.
TrapIf()
void v8::internal::compiler::WasmGraphAssembler::TrapIf (Node * condition, TrapId reason) [inline]
Definition at line 317 of file wasm-graph-assembler.h.
                                              {
    // Initially wasm traps don't have a FrameState.
    const bool has_frame_state = false;
    AddNode(
        graph()->NewNode(mcgraph()->common()->TrapIf(reason, has_frame_state),
                         condition, effect(), control()));
  }
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and v8::internal::compiler::GraphAssembler::mcgraph().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract().
TrapUnless()
void v8::internal::compiler::WasmGraphAssembler::TrapUnless (Node * condition, TrapId reason) [inline]
Definition at line 325 of file wasm-graph-assembler.h.
                                                  {
    // Initially wasm traps don't have a FrameState.
    const bool has_frame_state = false;
    AddNode(graph()->NewNode(
        mcgraph()->common()->TrapUnless(reason, has_frame_state), condition,
        effect(), control()));
  }
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and v8::internal::compiler::GraphAssembler::mcgraph().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract().
WasmAnyConvertExtern()
Node * v8::internal::compiler::WasmGraphAssembler::WasmAnyConvertExtern (Node * object)
Definition at line 547 of file wasm-graph-assembler.cc.
                                                           {
  return AddNode(graph()->NewNode(simplified_.WasmAnyConvertExtern(), object,
                                  effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
WasmArrayElementOffset()
Node * v8::internal::compiler::WasmGraphAssembler::WasmArrayElementOffset (Node * index, wasm::ValueType element_type)
Definition at line 484 of file wasm-graph-assembler.cc.
                                                                             {
  Node* index_intptr =
      mcgraph()->machine()->Is64() ? ChangeInt32ToInt64(index) : index;
  return IntAdd(
      IntPtrConstant(wasm::ObjectAccess::ToTagged(WasmArray::kHeaderSize)),
      IntMul(index_intptr, IntPtrConstant(element_type.value_kind_size())));
}
References v8::internal::index, v8::internal::compiler::GraphAssembler::IntPtrConstant(), v8::internal::compiler::MachineOperatorBuilder::Is64(), v8::internal::compiler::MachineGraph::machine(), v8::internal::compiler::GraphAssembler::mcgraph(), v8::internal::wasm::ObjectAccess::ToTagged(), and v8::internal::wasm::ValueTypeBase::value_kind_size().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), and v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet().
WasmExternConvertAny()
Node * v8::internal::compiler::WasmGraphAssembler::WasmExternConvertAny (Node * object)
Definition at line 552 of file wasm-graph-assembler.cc.
                                                           {
  return AddNode(graph()->NewNode(simplified_.WasmExternConvertAny(), object,
                                  effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
WasmTypeCast()
Node * v8::internal::compiler::WasmGraphAssembler::WasmTypeCast (Node * object, Node * rtt, WasmTypeCheckConfig config)
Definition at line 516 of file wasm-graph-assembler.cc.
                                                                   {
  return AddNode(graph()->NewNode(simplified_.WasmTypeCast(config), object, rtt,
                                  effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
WasmTypeCastAbstract()
Node * v8::internal::compiler::WasmGraphAssembler::WasmTypeCastAbstract (Node * object, WasmTypeCheckConfig config)
Definition at line 522 of file wasm-graph-assembler.cc.
                                                                           {
  return AddNode(graph()->NewNode(simplified_.WasmTypeCastAbstract(config),
                                  object, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
WasmTypeCheck()
Node * v8::internal::compiler::WasmGraphAssembler::WasmTypeCheck (Node * object, Node * rtt, WasmTypeCheckConfig config)
Definition at line 504 of file wasm-graph-assembler.cc.
                                                                    {
  return AddNode(graph()->NewNode(simplified_.WasmTypeCheck(config), object,
                                  rtt, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
WasmTypeCheckAbstract()
Node * v8::internal::compiler::WasmGraphAssembler::WasmTypeCheckAbstract (Node * object, WasmTypeCheckConfig config)
Definition at line 510 of file wasm-graph-assembler.cc.
                                                                            {
  return AddNode(graph()->NewNode(simplified_.WasmTypeCheckAbstract(config),
                                  object, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified_.
Member Data Documentation
simplified_
SimplifiedOperatorBuilder v8::internal::compiler::WasmGraphAssembler::simplified_ [private]
Definition at line 348 of file wasm-graph-assembler.h.
Referenced by Allocate(), ArrayGet(), ArrayInitializeLength(), ArrayLength(), ArraySet(), AssertNotNull(), InitializeImmutableInObject(), IsNotNull(), IsNull(), LoadFromObject(), LoadImmutableFromObject(), Null(), simplified(), StoreToObject(), StringAsWtf16(), StringPrepareForGetCodeunit(), StructGet(), StructSet(), WasmAnyConvertExtern(), WasmExternConvertAny(), WasmTypeCast(), WasmTypeCastAbstract(), WasmTypeCheck(), and WasmTypeCheckAbstract().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/wasm-graph-assembler.h
/mnt/V8SourceCode/src/compiler/wasm-graph-assembler.cc