v8::internal::SemiSpaceNewSpace Class Reference
#include <new-spaces.h>
Public Member Functions
SemiSpaceNewSpace (Heap *heap, size_t initial_semispace_capacity, size_t min_semispace_capacity_, size_t max_semispace_capacity)
~SemiSpaceNewSpace () final=default
bool ContainsSlow (Address a) const final
void Grow (size_t new_capacity) final
void Shrink (size_t new_capacity)
size_t Size () const final
size_t SizeOfObjects () const final
size_t Capacity () const final
size_t CurrentCapacitySafe () const
size_t TotalCapacity () const final
size_t CommittedMemory () const final
size_t MaximumCommittedMemory () const final
size_t CommittedPhysicalMemory () const final
size_t Available () const final
bool ReachedTargetCapacity () const
size_t ExternalBackingStoreBytes (ExternalBackingStoreType type) const final
size_t AllocatedSinceLastGC () const final
void GrowToMaximumCapacityForTesting () final
size_t MaximumCapacity () const final
size_t MinimumCapacity () const final
Address first_allocatable_address () const final
Address age_mark () const
void SetAgeMarkAndBelowAgeMarkPageFlags ()
bool AddFreshPage ()
bool AddParkedAllocationBuffer (int size_in_bytes, AllocationAlignment alignment)
void ResetParkedAllocationBuffers ()
void MakeIterable () override
void MakeAllPagesInFromSpaceIterable ()
void MakeUnusedPagesInToSpaceIterable ()
PageMetadata * first_page () final
PageMetadata * last_page () final
const PageMetadata * first_page () const final
const PageMetadata * last_page () const final
iterator begin () final
iterator end () final
const_iterator begin () const final
const_iterator end () const final
std::unique_ptr< ObjectIterator > GetObjectIterator (Heap *heap) final
SemiSpace & from_space ()
const SemiSpace & from_space () const
SemiSpace & to_space ()
const SemiSpace & to_space () const
bool ShouldPageBePromoted (const MemoryChunk *chunk) const
bool ShouldBePromoted (Address object) const
void SwapSemiSpaces ()
void GarbageCollectionPrologue () final
void GarbageCollectionEpilogue () final
void ZapUnusedMemory ()
bool IsPromotionCandidate (const MutablePageMetadata *page) const final
AllocatorPolicy * CreateAllocatorPolicy (MainAllocator *allocator) final
int GetSpaceRemainingOnCurrentPageForTesting ()
void FillCurrentPageForTesting ()
void MoveQuarantinedPage (MemoryChunk *chunk)
size_t QuarantinedSize () const
size_t QuarantinedPageCount () const
void SetQuarantinedSize (size_t quarantined_size)
bool IsAddressBelowAgeMark (Address address) const
Static Public Member Functions
static SemiSpaceNewSpace * From (NewSpace *space)
Private Types
using ParkedAllocationBuffer = std::pair< int, Address >
using ParkedAllocationBuffersVector = std::vector< ParkedAllocationBuffer >
Private Member Functions
bool IsFromSpaceCommitted () const
SemiSpace * active_space ()
std::optional< std::pair< Address, Address > > Allocate (int size_in_bytes, AllocationAlignment alignment)
std::optional< std::pair< Address, Address > > AllocateOnNewPageBeyondCapacity (int size_in_bytes, AllocationAlignment alignment)
void RemovePage (PageMetadata *page) final
void Free (Address start, Address end)
void ResetAllocationTopToCurrentPageStart ()
void SetAllocationTop (Address top)
void IncrementAllocationTop (Address new_top)
void DecrementAllocationTop (Address new_top)
Address allocation_top () const
Private Attributes
SemiSpace to_space_
SemiSpace from_space_
Address allocation_top_ = kNullAddress
ParkedAllocationBuffersVector parked_allocation_buffers_
size_t quarantined_size_ = 0
size_t size_after_last_gc_ = 0
const size_t minimum_capacity_ = 0
const size_t maximum_capacity_ = 0
Address age_mark_ = kNullAddress
size_t target_capacity_ = 0
Friends
class SemiSpaceObjectIterator
class SemiSpaceNewSpaceAllocatorPolicy
Additional Inherited Members
Detailed Description
Definition at line 254 of file new-spaces.h.
Member Typedef Documentation
ParkedAllocationBuffer
using v8::internal::SemiSpaceNewSpace::ParkedAllocationBuffer = std::pair<int, Address> [private]
Definition at line 255 of file new-spaces.h.
ParkedAllocationBuffersVector
using v8::internal::SemiSpaceNewSpace::ParkedAllocationBuffersVector = std::vector<ParkedAllocationBuffer> [private]
Definition at line 256 of file new-spaces.h.
Constructor & Destructor Documentation
SemiSpaceNewSpace()
v8::internal::SemiSpaceNewSpace::SemiSpaceNewSpace (Heap * heap, size_t initial_semispace_capacity, size_t min_semispace_capacity_, size_t max_semispace_capacity)
Definition at line 416 of file new-spaces.cc.
    : NewSpace(heap),
      to_space_(heap, kToSpace),
      from_space_(heap, kFromSpace),
      minimum_capacity_(min_semispace_capacity),
      maximum_capacity_(max_semispace_capacity),
      target_capacity_(initial_semispace_capacity) {
  DCHECK(IsAligned(initial_semispace_capacity, PageMetadata::kPageSize));
  DCHECK(IsAligned(minimum_capacity_, PageMetadata::kPageSize));
  DCHECK(IsAligned(maximum_capacity_, PageMetadata::kPageSize));
  DCHECK_LE(static_cast<size_t>(PageMetadata::kPageSize), minimum_capacity_);
  DCHECK_LE(minimum_capacity_, target_capacity_);
  DCHECK_LE(target_capacity_, maximum_capacity_);
}
References v8::internal::DCHECK(), DCHECK_LE, IsAligned(), v8::internal::MutablePageMetadata::kPageSize, maximum_capacity_, minimum_capacity_, and target_capacity_.
 SemiSpaceNewSpace()
v8::internal::SemiSpaceNewSpace::~SemiSpaceNewSpace () [final], [default]
Member Function Documentation
active_space()
SemiSpace* v8::internal::SemiSpaceNewSpace::active_space () [inline], [private]
Definition at line 439 of file new-spaces.h.
{ return &to_space_; }
AddFreshPage()
bool v8::internal::SemiSpaceNewSpace::AddFreshPage ()
Definition at line 500 of file new-spaces.cc.
                                     {
  DCHECK_IMPLIES(allocation_top(), allocation_top() == to_space_.page_high());
  if (to_space_.AdvancePage(target_capacity_)) {
    ResetAllocationTopToCurrentPageStart();
    return true;
  }
  return false;
}
References v8::internal::SemiSpace::AdvancePage(), allocation_top(), DCHECK_IMPLIES, v8::internal::SemiSpace::page_high(), ResetAllocationTopToCurrentPageStart(), target_capacity_, and to_space_.
Referenced by Allocate(), and AllocateOnNewPageBeyondCapacity().
AddParkedAllocationBuffer()
bool v8::internal::SemiSpaceNewSpace::AddParkedAllocationBuffer (int size_in_bytes, AllocationAlignment alignment)
Definition at line 518 of file new-spaces.cc.
                                                      {
  int parked_size = 0;
  Address start = 0;
  for (auto it = parked_allocation_buffers_.begin();
       it != parked_allocation_buffers_.end();) {
    parked_size = it->first;
    start = it->second;
    int filler_size = Heap::GetFillToAlign(start, alignment);
    if (size_in_bytes + filler_size <= parked_size) {
      parked_allocation_buffers_.erase(it);
      PageMetadata* page = PageMetadata::FromAddress(start);
      // We move a page with a parked allocation to the end of the pages list
      // to maintain the invariant that the last page is the used one.
      to_space_.MovePageToTheEnd(page);
      SetAllocationTop(start);
      return true;
    } else {
      it++;
    }
  }
  return false;
}
References v8::internal::PageMetadata::FromAddress(), v8::internal::Heap::GetFillToAlign(), v8::internal::SemiSpace::MovePageToTheEnd(), parked_allocation_buffers_, SetAllocationTop(), and to_space_.
Referenced by Allocate().
age_mark()
Address v8::internal::SemiSpaceNewSpace::age_mark () const [inline]
Definition at line 348 of file new-spaces.h.
{ return age_mark_; }
Referenced by IsAddressBelowAgeMark(), and IsPromotionCandidate().
Allocate()
std::optional< std::pair< Address, Address > > v8::internal::SemiSpaceNewSpace::Allocate (int size_in_bytes, AllocationAlignment alignment) [private]
Definition at line 762 of file new-spaces.cc.
                                                      {
  size_in_bytes = ALIGN_TO_ALLOCATION_ALIGNMENT(size_in_bytes);
  Address top = allocation_top();
  if (top) {
    DCHECK_SEMISPACE_ALLOCATION_TOP(allocation_top(), to_space_);
    Address high = to_space_.page_high();
    int filler_size = Heap::GetFillToAlign(top, alignment);
    int aligned_size_in_bytes = size_in_bytes + filler_size;
    if (top + aligned_size_in_bytes <= high) {
      IncrementAllocationTop(high);
      return std::pair(top, high);
    }
    int remaining_in_page = static_cast<int>(high - top);
    heap()->CreateFillerObjectAt(top, remaining_in_page);
    SetAllocationTop(high);
    // We park unused allocation buffer space of allocations happening from the
    // mutator.
    if (v8_flags.allocation_buffer_parking &&
        heap()->gc_state() == Heap::NOT_IN_GC &&
        remaining_in_page >= kAllocationBufferParkingThreshold) {
      parked_allocation_buffers_.push_back(
          ParkedAllocationBuffer(remaining_in_page, top));
    }
  }
  if (AddFreshPage()) {
    Address start = allocation_top();
    Address end = to_space_.page_high();
    IncrementAllocationTop(end);
    return std::pair(start, end);
  }
  if (v8_flags.allocation_buffer_parking &&
      AddParkedAllocationBuffer(size_in_bytes, alignment)) {
    Address start = allocation_top();
    Address end = to_space_.page_high();
    DCHECK_LT(start, end);
    IncrementAllocationTop(end);
    return std::pair(start, end);
  }
  return std::nullopt;
}
References AddFreshPage(), AddParkedAllocationBuffer(), ALIGN_TO_ALLOCATION_ALIGNMENT, allocation_top(), DCHECK_LT, DCHECK_SEMISPACE_ALLOCATION_TOP, end(), v8::internal::Heap::GetFillToAlign(), heap(), IncrementAllocationTop(), v8::internal::NewSpace::kAllocationBufferParkingThreshold, v8::internal::Heap::NOT_IN_GC, v8::internal::SemiSpace::page_high(), parked_allocation_buffers_, SetAllocationTop(), to_space_, and v8::internal::v8_flags.
Referenced by AllocateOnNewPageBeyondCapacity(), and v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation().
AllocatedSinceLastGC()
size_t v8::internal::SemiSpaceNewSpace::AllocatedSinceLastGC () const [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 697 of file new-spaces.cc.
                                                     {
  size_t current_size = Size();
  DCHECK_GE(current_size, size_after_last_gc_);
  return current_size - size_after_last_gc_;
}
References DCHECK_GE, Size(), and size_after_last_gc_.
AllocateOnNewPageBeyondCapacity()
std::optional< std::pair< Address, Address > > v8::internal::SemiSpaceNewSpace::AllocateOnNewPageBeyondCapacity (int size_in_bytes, AllocationAlignment alignment) [private]
Definition at line 510 of file new-spaces.cc.
                                                      {
  DCHECK_LT(Available(), size_in_bytes);
  DCHECK(!AddFreshPage());
  if (!to_space_.AllocateFreshPage()) return std::nullopt;
  return Allocate(size_in_bytes, alignment);
}
References AddFreshPage(), Allocate(), v8::internal::SemiSpace::AllocateFreshPage(), Available(), v8::internal::DCHECK(), DCHECK_LT, and to_space_.
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation().
allocation_top()
Address v8::internal::SemiSpaceNewSpace::allocation_top () const [inline], [private]
Definition at line 466 of file new-spaces.h.
{ return allocation_top_; }
Referenced by AddFreshPage(), Allocate(), FillCurrentPageForTesting(), Free(), GetSpaceRemainingOnCurrentPageForTesting(), SetAgeMarkAndBelowAgeMarkPageFlags(), Shrink(), and Size().
Available()
size_t v8::internal::SemiSpaceNewSpace::Available () const [final]
Definition at line 692 of file new-spaces.cc.
                                          {
  DCHECK_GE(Capacity(), Size() - QuarantinedSize());
  return Capacity() - (Size() - QuarantinedSize());
}
References Capacity(), DCHECK_GE, QuarantinedSize(), and Size().
Referenced by AllocateOnNewPageBeyondCapacity().
begin() [1/2]
const_iterator v8::internal::SemiSpaceNewSpace::begin () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 394 of file new-spaces.h.
{ return to_space_.begin(); }
begin() [2/2]
iterator v8::internal::SemiSpaceNewSpace::begin () [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 391 of file new-spaces.h.
{ return to_space_.begin(); }
Capacity()
size_t v8::internal::SemiSpaceNewSpace::Capacity () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 285 of file new-spaces.h.
                                {
    size_t actual_capacity =
        std::max(to_space_.current_capacity(), target_capacity_);
    return (actual_capacity / PageMetadata::kPageSize) *
           MemoryChunkLayout::AllocatableMemoryInDataPage();
  }
References v8::internal::MemoryChunkLayout::AllocatableMemoryInDataPage(), and v8::internal::MutablePageMetadata::kPageSize.
Referenced by Available().
CommittedMemory()
size_t v8::internal::SemiSpaceNewSpace::CommittedMemory () const [inline], [final]
Definition at line 305 of file new-spaces.h.
                                       {
    return from_space_.CommittedMemory() + to_space_.CommittedMemory();
  }
Referenced by CommittedPhysicalMemory().
CommittedPhysicalMemory()
size_t v8::internal::SemiSpaceNewSpace::CommittedPhysicalMemory () const [final]
Definition at line 491 of file new-spaces.cc.
                                                        {
  if (!base::OS::HasLazyCommits()) return CommittedMemory();
  size_t size = to_space_.CommittedPhysicalMemory();
  if (from_space_.IsCommitted()) {
    size += from_space_.CommittedPhysicalMemory();
  }
  return size;
}
References CommittedMemory(), v8::internal::SemiSpace::CommittedPhysicalMemory(), from_space_, v8::base::OS::HasLazyCommits(), v8::internal::SemiSpace::IsCommitted(), size(), and to_space_.
ContainsSlow()
bool v8::internal::SemiSpaceNewSpace::ContainsSlow (Address a) const [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 671 of file new-spaces.cc.
                                                    {
  return from_space_.ContainsSlow(a) || to_space_.ContainsSlow(a);
}
References v8::internal::SemiSpace::ContainsSlow(), from_space_, and to_space_.
CreateAllocatorPolicy()
AllocatorPolicy * v8::internal::SemiSpaceNewSpace::CreateAllocatorPolicy (MainAllocator * allocator) [final]
Definition at line 819 of file new-spaces.cc.
                              {
  return new SemiSpaceNewSpaceAllocatorPolicy(this, allocator);
}
References SemiSpaceNewSpaceAllocatorPolicy.
CurrentCapacitySafe()
size_t v8::internal::SemiSpaceNewSpace::CurrentCapacitySafe () const [inline]
Definition at line 294 of file new-spaces.h.
                                     {
    return (to_space_.current_capacity_safe() / PageMetadata::kPageSize) *
           MemoryChunkLayout::AllocatableMemoryInDataPage();
  }
References v8::internal::MemoryChunkLayout::AllocatableMemoryInDataPage(), and v8::internal::MutablePageMetadata::kPageSize.
Referenced by v8::internal::Heap::YoungGenerationConsumedBytes().
DecrementAllocationTop()
void v8::internal::SemiSpaceNewSpace::DecrementAllocationTop (Address new_top) [inline], [private]
Definition at line 90 of file new-spaces-inl.h.
                                                              {
  DCHECK_LE(new_top, allocation_top_);
  DCHECK_EQ(PageMetadata::FromAllocationAreaAddress(allocation_top_),
            PageMetadata::FromAllocationAreaAddress(new_top));
  allocation_top_ = new_top;
}
References allocation_top_, DCHECK_EQ, DCHECK_LE, and v8::internal::PageMetadata::FromAllocationAreaAddress().
Referenced by Free().
end() [1/2]
const_iterator v8::internal::SemiSpaceNewSpace::end () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 395 of file new-spaces.h.
{ return to_space_.end(); }
end() [2/2]
iterator v8::internal::SemiSpaceNewSpace::end () [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 392 of file new-spaces.h.
{ return to_space_.end(); }
Referenced by Allocate(), and Free().
ExternalBackingStoreBytes()
size_t v8::internal::SemiSpaceNewSpace::ExternalBackingStoreBytes (ExternalBackingStoreType type) const [inline], [final]
Definition at line 324 of file new-spaces.h.
                                                                              {
    if (type == ExternalBackingStoreType::kArrayBuffer)
      return heap()->YoungArrayBufferBytes();
    DCHECK_EQ(0, from_space_.ExternalBackingStoreBytes(type));
    return to_space_.ExternalBackingStoreBytes(type);
  }
References DCHECK_EQ, heap(), v8::internal::kArrayBuffer, and v8::internal::tracing::type.
FillCurrentPageForTesting()
void v8::internal::SemiSpaceNewSpace::FillCurrentPageForTesting ()
Definition at line 551 of file new-spaces.cc.
                                                  {
  int remaining = GetSpaceRemainingOnCurrentPageForTesting();
  heap()->CreateFillerObjectAt(allocation_top(), remaining);
  IncrementAllocationTop(to_space_.page_high());
}
References allocation_top(), GetSpaceRemainingOnCurrentPageForTesting(), heap(), IncrementAllocationTop(), v8::internal::SemiSpace::page_high(), and to_space_.
first_allocatable_address()
Address v8::internal::SemiSpaceNewSpace::first_allocatable_address () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 343 of file new-spaces.h.
                                                  {
    return to_space_.space_start();
  }
first_page() [1/2]
const PageMetadata* v8::internal::SemiSpaceNewSpace::first_page () const [inline], [final]
Definition at line 386 of file new-spaces.h.
                                               {
    return to_space_.first_page();
  }
first_page() [2/2]
PageMetadata* v8::internal::SemiSpaceNewSpace::first_page () [inline], [final]
Definition at line 383 of file new-spaces.h.
{ return to_space_.first_page(); }
Referenced by ZapUnusedMemory().
Free()
void v8::internal::SemiSpaceNewSpace::Free (Address start, Address end) [private]
Definition at line 810 of file new-spaces.cc.
                                                       {
  DCHECK_LE(start, end);
  heap()->CreateFillerObjectAt(start, static_cast<int>(end - start));
  if (end == allocation_top()) {
    DecrementAllocationTop(start);
  }
}
References allocation_top(), DCHECK_LE, DecrementAllocationTop(), end(), and heap().
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), and v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized().
From()
static SemiSpaceNewSpace* v8::internal::SemiSpaceNewSpace::From (NewSpace * space) [inline], [static]
Definition at line 259 of file new-spaces.h.
                                                  {
    DCHECK(!v8_flags.minor_ms);
    return static_cast<SemiSpaceNewSpace*>(space);
  }
References v8::internal::DCHECK(), space, and v8::internal::v8_flags.
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::ScavengerCollector::NumberOfScavengeTasks(), v8::internal::HeapLayoutTracer::PrintHeapLayout(), and v8::internal::Heap::semi_space_new_space().
from_space() [1/2]
SemiSpace& v8::internal::SemiSpaceNewSpace::from_space () [inline]
Definition at line 399 of file new-spaces.h.
{ return from_space_; }
Referenced by MakeAllPagesInFromSpaceIterable(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::HeapLayoutTracer::PrintHeapLayout(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), RemovePage(), ZapUnusedMemory(), and v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::~YoungGenerationConservativeStackVisitor().
from_space() [2/2]
const SemiSpace& v8::internal::SemiSpaceNewSpace::from_space () const [inline]
Definition at line 400 of file new-spaces.h.
{ return from_space_; }
GarbageCollectionEpilogue()
void v8::internal::SemiSpaceNewSpace::GarbageCollectionEpilogue () [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 724 of file new-spaces.cc.
                                                  {
  DCHECK(!heap()->allocator()->new_space_allocator()->IsLabValid());
  SetAgeMarkAndBelowAgeMarkPageFlags();
  size_after_last_gc_ = Size();
  if (heap::ShouldZapGarbage() || v8_flags.clear_free_memory) {
    ZapUnusedMemory();
  }
  // Shrink from-space down to target_capacity_ if necessary.
  from_space_.ShrinkCapacityTo(target_capacity_);
  // to-space always fits into target_capacity_ after the GC.
  DCHECK_LE(to_space_.current_capacity(), target_capacity_);
  MakeAllPagesInFromSpaceIterable();
}
References v8::internal::SemiSpace::current_capacity(), v8::internal::DCHECK(), DCHECK_LE, from_space_, heap(), MakeAllPagesInFromSpaceIterable(), SetAgeMarkAndBelowAgeMarkPageFlags(), v8::internal::heap::ShouldZapGarbage(), v8::internal::SemiSpace::ShrinkCapacityTo(), Size(), size_after_last_gc_, target_capacity_, to_space_, v8::internal::v8_flags, and ZapUnusedMemory().
GarbageCollectionPrologue()
void v8::internal::SemiSpaceNewSpace::GarbageCollectionPrologue () [final], [virtual]
Reimplemented from v8::internal::NewSpace.
Definition at line 703 of file new-spaces.cc.
                                                  {
  ResetParkedAllocationBuffers();
}
References ResetParkedAllocationBuffers().
Referenced by v8::internal::ScavengerCollector::CollectGarbage().
GetObjectIterator()
std::unique_ptr< ObjectIterator > v8::internal::SemiSpaceNewSpace::GetObjectIterator (Heap * heap) [final]
Definition at line 666 of file new-spaces.cc.
                {
  return std::unique_ptr<ObjectIterator>(new SemiSpaceObjectIterator(this));
}
References SemiSpaceObjectIterator.
GetSpaceRemainingOnCurrentPageForTesting()
int v8::internal::SemiSpaceNewSpace::GetSpaceRemainingOnCurrentPageForTesting ()
Definition at line 546 of file new-spaces.cc.
                                                                {
  if (!allocation_top()) return 0;
  return static_cast<int>(to_space_.page_high() - allocation_top());
}
References allocation_top(), v8::internal::SemiSpace::page_high(), and to_space_.
Referenced by FillCurrentPageForTesting().
Grow()
void v8::internal::SemiSpaceNewSpace::Grow (size_t new_capacity) [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 435 of file new-spaces.cc.
                                                {
  heap()->safepoint()->AssertActive();
  DCHECK(MemoryChunk::IsAligned(new_capacity));
  DCHECK_LE(target_capacity_, new_capacity);
  DCHECK_LE(new_capacity, maximum_capacity_);
  target_capacity_ = new_capacity;
}
References v8::internal::DCHECK(), DCHECK_LE, heap(), v8::internal::MemoryChunk::IsAligned(), maximum_capacity_, and target_capacity_.
Referenced by GrowToMaximumCapacityForTesting().
GrowToMaximumCapacityForTesting()
void v8::internal::SemiSpaceNewSpace::GrowToMaximumCapacityForTesting () [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 443 of file new-spaces.cc.
                                                        {
  Grow(maximum_capacity_);
}
References Grow(), and maximum_capacity_.
IncrementAllocationTop()
void v8::internal::SemiSpaceNewSpace::IncrementAllocationTop (Address new_top) [inline], [private]
Definition at line 83 of file new-spaces-inl.h.
                                                              {
  DCHECK_LE(allocation_top_, new_top);
  DCHECK_EQ(PageMetadata::FromAllocationAreaAddress(allocation_top_),
            PageMetadata::FromAllocationAreaAddress(new_top));
  allocation_top_ = new_top;
}
References allocation_top_, DCHECK_EQ, DCHECK_LE, and v8::internal::PageMetadata::FromAllocationAreaAddress().
Referenced by Allocate(), and FillCurrentPageForTesting().
IsAddressBelowAgeMark()
bool v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark (Address address) const [inline]
Definition at line 97 of file new-spaces-inl.h.
                                                                   {
  // Note that we use MemoryChunk here on purpose to avoid the page metadata
  // table lookup for performance reasons.
  MemoryChunk* chunk = MemoryChunk::FromAddress(address);
  // This method is only ever used on non-large pages in the young generation.
  // However, on page promotion (new to old) during a full GC the page flags are
  // already updated to old space before using this method.
  DCHECK(chunk->InYoungGeneration() ||
         chunk->IsFlagSet(MemoryChunk::PAGE_NEW_OLD_PROMOTION));
  DCHECK(!chunk->IsLargePage());
  if (!chunk->IsFlagSet(MemoryChunk::NEW_SPACE_BELOW_AGE_MARK)) {
    return false;
  }
  const Address age_mark = age_mark_;
  const bool on_age_mark_page =
      chunk->address() < age_mark &&
      age_mark <= chunk->address() + PageMetadata::kPageSize;
  DCHECK_EQ(chunk->Metadata()->ContainsLimit(age_mark), on_age_mark_page);
  return !on_age_mark_page || address < age_mark;
}
References v8::internal::MemoryChunk::address(), age_mark(), age_mark_, v8::internal::MemoryChunkMetadata::ContainsLimit(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryChunk::FromAddress(), v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::MemoryChunk::Metadata(), v8::internal::MemoryChunk::NEW_SPACE_BELOW_AGE_MARK, and v8::internal::MemoryChunk::PAGE_NEW_OLD_PROMOTION.
Referenced by ShouldBePromoted().
IsFromSpaceCommitted()
bool v8::internal::SemiSpaceNewSpace::IsFromSpaceCommitted () const [inline], [private]
Definition at line 437 of file new-spaces.h.
{ return from_space_.IsCommitted(); }
Referenced by MakeAllPagesInFromSpaceIterable(), and ZapUnusedMemory().
IsPromotionCandidate()
bool v8::internal::SemiSpaceNewSpace::IsPromotionCandidate (const MutablePageMetadata * page) const [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 757 of file new-spaces.cc.
                                           {
  return !page->Contains(age_mark());
}
References age_mark(), and v8::internal::MemoryChunkMetadata::Contains().
last_page() [1/2]
const PageMetadata* v8::internal::SemiSpaceNewSpace::last_page () const [inline], [final]
Definition at line 389 of file new-spaces.h.
{ return to_space_.last_page(); }
last_page() [2/2]
PageMetadata* v8::internal::SemiSpaceNewSpace::last_page () [inline], [final]
Definition at line 384 of file new-spaces.h.
{ return to_space_.last_page(); }
MakeAllPagesInFromSpaceIterable()
void v8::internal::SemiSpaceNewSpace::MakeAllPagesInFromSpaceIterable ()
Definition at line 627 of file new-spaces.cc.
                                                        {
  if (!IsFromSpaceCommitted()) return;
  // Fix all pages in the "from" semispace.
  for (PageMetadata* page : from_space()) {
    heap()->CreateFillerObjectAt(page->area_start(),
                                 static_cast<int>(page->area_size()));
  }
}
References from_space(), heap(), and IsFromSpaceCommitted().
Referenced by GarbageCollectionEpilogue(), and MakeIterable().
MakeIterable()
void v8::internal::SemiSpaceNewSpace::MakeIterable () [override], [virtual]
Implements v8::internal::NewSpace.
Definition at line 622 of file new-spaces.cc.
                                     {
  MakeAllPagesInFromSpaceIterable();
  MakeUnusedPagesInToSpaceIterable();
}
References MakeAllPagesInFromSpaceIterable(), and MakeUnusedPagesInToSpaceIterable().
MakeUnusedPagesInToSpaceIterable()
void v8::internal::SemiSpaceNewSpace::MakeUnusedPagesInToSpaceIterable ()
Definition at line 637 of file new-spaces.cc.
                                                         {
  if (!to_space().current_page()) {
    DCHECK(to_space().memory_chunk_list().Empty());
    return;
  }
  PageIterator it(to_space().current_page());
  // Fix the remaining unused pages in the "to" semispace.
  for (PageMetadata* page = *(++it); page != nullptr; page = *(++it)) {
    heap()->CreateFillerObjectAt(page->area_start(),
                                 static_cast<int>(page->area_size()));
  }
}
References v8::internal::DCHECK(), heap(), and to_space().
Referenced by MakeIterable().
MaximumCapacity()
size_t v8::internal::SemiSpaceNewSpace::MaximumCapacity () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 336 of file new-spaces.h.
{ return maximum_capacity_; }
MaximumCommittedMemory()
size_t v8::internal::SemiSpaceNewSpace::MaximumCommittedMemory () const [inline], [final]
Definition at line 309 of file new-spaces.h.
                                              {
    return from_space_.MaximumCommittedMemory() +
           to_space_.MaximumCommittedMemory();
  }
MinimumCapacity()
size_t v8::internal::SemiSpaceNewSpace::MinimumCapacity () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 339 of file new-spaces.h.
{ return minimum_capacity_; }
MoveQuarantinedPage()
void v8::internal::SemiSpaceNewSpace::MoveQuarantinedPage (MemoryChunk * chunk)
Definition at line 824 of file new-spaces.cc.
                                                              {
  to_space_.MoveQuarantinedPage(chunk);
}
References v8::internal::SemiSpace::MoveQuarantinedPage(), and to_space_.
Referenced by v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages().
QuarantinedPageCount()
size_t v8::internal::SemiSpaceNewSpace::QuarantinedPageCount () const [inline]
Definition at line 427 of file new-spaces.h.
                                      {
    return to_space_.quarantined_pages_count_;
  }
Referenced by v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration(), v8::internal::GCTracer::PrintNVP(), and v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects().
QuarantinedSize()
size_t v8::internal::SemiSpaceNewSpace::QuarantinedSize () const [inline]
Definition at line 426 of file new-spaces.h.
{ return quarantined_size_; }
Referenced by Available(), v8::internal::GCTracer::PrintNVP(), and Size().
ReachedTargetCapacity()
bool v8::internal::SemiSpaceNewSpace::ReachedTargetCapacity () const [inline]
Definition at line 320 of file new-spaces.h.
                                     {
    return to_space_.current_capacity_ >= target_capacity_;
  }
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation().
RemovePage()
void v8::internal::SemiSpaceNewSpace::RemovePage (PageMetadata * page) [final], [private], [virtual]
Implements v8::internal::NewSpace.
Definition at line 751 of file new-spaces.cc.
                                                     {
  DCHECK(!page->Chunk()->IsToPage());
  DCHECK(page->Chunk()->IsFromPage());
  from_space().RemovePage(page);
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), from_space(), v8::internal::MemoryChunk::IsFromPage(), v8::internal::MemoryChunk::IsToPage(), and v8::internal::SemiSpace::RemovePage().
ResetAllocationTopToCurrentPageStart()
void v8::internal::SemiSpaceNewSpace::ResetAllocationTopToCurrentPageStart () [inline], [private]
Definition at line 455 of file new-spaces.h.
                                              {
    allocation_top_ =
        to_space_.current_page() ? to_space_.page_low() : kNullAddress;
  }
References v8::internal::kNullAddress.
Referenced by AddFreshPage().
ResetParkedAllocationBuffers()
void v8::internal::SemiSpaceNewSpace::ResetParkedAllocationBuffers ()
Definition at line 542 of file new-spaces.cc.
                                                     {
  parked_allocation_buffers_.clear();
}
References parked_allocation_buffers_.
Referenced by GarbageCollectionPrologue().
SetAgeMarkAndBelowAgeMarkPageFlags()
void v8::internal::SemiSpaceNewSpace::SetAgeMarkAndBelowAgeMarkPageFlags ()
Definition at line 447 of file new-spaces.cc.
                                                           {
  age_mark_ = allocation_top();
  PageMetadata* current_page = to_space().first_page();
  for (size_t i = 0; i < to_space_.quarantined_pages_count_; i++) {
    DCHECK_NOT_NULL(current_page);
    current_page->Chunk()->SetFlagNonExecutable(
        MemoryChunk::NEW_SPACE_BELOW_AGE_MARK);
    current_page = current_page->next_page();
  }
  if (age_mark_) {
    PageMetadata* age_mark_page =
        PageMetadata::FromAllocationAreaAddress(age_mark_);
    DCHECK_EQ(age_mark_page->owner(), &to_space());
    // Mark all pages up to (and including) the one containing mark.
    for (; current_page != age_mark_page;
         current_page = current_page->next_page()) {
      current_page->Chunk()->SetFlagNonExecutable(
          MemoryChunk::NEW_SPACE_BELOW_AGE_MARK);
    }
    DCHECK_EQ(current_page, age_mark_page);
    current_page->Chunk()->SetFlagNonExecutable(
        MemoryChunk::NEW_SPACE_BELOW_AGE_MARK);
  }
}
References age_mark_, allocation_top(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::SemiSpace::first_page(), v8::internal::PageMetadata::FromAllocationAreaAddress(), v8::internal::MemoryChunk::NEW_SPACE_BELOW_AGE_MARK, v8::internal::PageMetadata::next_page(), v8::internal::MutablePageMetadata::owner(), v8::internal::SemiSpace::quarantined_pages_count_, v8::internal::MemoryChunk::SetFlagNonExecutable(), to_space(), and to_space_.
Referenced by GarbageCollectionEpilogue().
SetAllocationTop()
void v8::internal::SemiSpaceNewSpace::SetAllocationTop (Address top) [inline], [private]
Definition at line 460 of file new-spaces.h.
{ allocation_top_ = top; }
Referenced by AddParkedAllocationBuffer(), and Allocate().
SetQuarantinedSize()
void v8::internal::SemiSpaceNewSpace::SetQuarantinedSize (size_t quarantined_size) [inline]
Definition at line 430 of file new-spaces.h.
                                                   {
    quarantined_size_ = quarantined_size;
  }
Referenced by v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects().
ShouldBePromoted()
bool v8::internal::SemiSpaceNewSpace::ShouldBePromoted (Address object) const [inline]
Definition at line 121 of file new-spaces-inl.h.
                                                             {
  return IsAddressBelowAgeMark(object);
}
References IsAddressBelowAgeMark().
ShouldPageBePromoted()
bool v8::internal::SemiSpaceNewSpace::ShouldPageBePromoted (const MemoryChunk * chunk) const
Definition at line 652 of file new-spaces.cc.
                                                                           {
  if (!chunk->IsFlagSet(MemoryChunk::NEW_SPACE_BELOW_AGE_MARK)) {
    return false;
  }
  // If the page contains the current age mark, it contains both objects in the
  // interemediate generation (that could be promoted to old space) and new
  // objects (that should remain in new space). When pinning an intermediate
  // generation object on this page, we don't yet know whether or not the page
  // will also contain pinned new objects (that will prevent us from promoting
  // the page). Thus, we conservatively keep the page in new space. Pinned
  // objects on it will either die or be promoted in the next GC cycle.
  return !chunk->Metadata()->ContainsLimit(age_mark_);
}
References age_mark_, v8::internal::MemoryChunkMetadata::ContainsLimit(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::Metadata(), and v8::internal::MemoryChunk::NEW_SPACE_BELOW_AGE_MARK.
Shrink()
void v8::internal::SemiSpaceNewSpace::Shrink (size_t new_capacity)
Definition at line 477 of file new-spaces.cc.
                                                  {
  DCHECK(MemoryChunk::IsAligned(new_capacity));
  DCHECK_LE(minimum_capacity_, new_capacity);
  DCHECK_LE(new_capacity, target_capacity_);
  DCHECK_LE(target_capacity_, maximum_capacity_);
  target_capacity_ = new_capacity;
  to_space_.ShrinkCapacityTo(new_capacity);
  if (allocation_top()) {
    DCHECK_SEMISPACE_ALLOCATION_TOP(allocation_top(), to_space_);
  }
  from_space_.Uncommit();
}
References allocation_top(), v8::internal::DCHECK(), DCHECK_LE, DCHECK_SEMISPACE_ALLOCATION_TOP, from_space_, v8::internal::MemoryChunk::IsAligned(), maximum_capacity_, minimum_capacity_, v8::internal::SemiSpace::ShrinkCapacityTo(), target_capacity_, to_space_, and v8::internal::SemiSpace::Uncommit().
Referenced by v8::internal::Heap::ReduceNewSpaceSize().
Size()
size_t v8::internal::SemiSpaceNewSpace::Size () const [final]
Definition at line 675 of file new-spaces.cc.
                                     {
  size_t const top = allocation_top();
  size_t const quarantined = QuarantinedSize();
  if (top) {
    DCHECK_SEMISPACE_ALLOCATION_TOP(top, to_space_);
    return quarantined +
           (to_space_.current_capacity() - PageMetadata::kPageSize) /
               PageMetadata::kPageSize *
               MemoryChunkLayout::AllocatableMemoryInDataPage() +
           static_cast<size_t>(top - to_space_.page_low());
  } else {
    DCHECK_EQ(to_space_.current_capacity(), 0);
    return quarantined;
  }
}
References v8::internal::MemoryChunkLayout::AllocatableMemoryInDataPage(), allocation_top(), v8::internal::SemiSpace::current_capacity(), DCHECK_EQ, DCHECK_SEMISPACE_ALLOCATION_TOP, v8::internal::MutablePageMetadata::kPageSize, v8::internal::SemiSpace::page_low(), QuarantinedSize(), and to_space_.
Referenced by AllocatedSinceLastGC(), Available(), GarbageCollectionEpilogue(), and SwapSemiSpaces().
SizeOfObjects()
size_t v8::internal::SemiSpaceNewSpace::SizeOfObjects () const [inline], [final]
Definition at line 282 of file new-spaces.h.
{ return Size(); }
SwapSemiSpaces()
void v8::internal::SemiSpaceNewSpace::SwapSemiSpaces ()
Definition at line 707 of file new-spaces.cc.
                                       {
  // Flip the semispaces. After flipping, to space is empty and from space has
  // live objects.
  SemiSpace::Swap(&from_space_, &to_space_);
  to_space_.Reset();
  from_space_.Reset();
  quarantined_size_ = 0;
  allocation_top_ = kNullAddress;
  DCHECK_EQ(0u, Size());
#if DEBUG
  for (PageMetadata* p : to_space_) {
    DCHECK(p->IsLivenessClear());
  }
#endif // DEBUG
}
References allocation_top_, v8::internal::DCHECK(), DCHECK_EQ, from_space_, v8::internal::kNullAddress, quarantined_size_, v8::internal::SemiSpace::Reset(), Size(), v8::internal::SemiSpace::Swap(), and to_space_.
Referenced by v8::internal::ScavengerCollector::CollectGarbage().
to_space() [1/2]
SemiSpace& v8::internal::SemiSpaceNewSpace::to_space () [inline]
Definition at line 401 of file new-spaces.h.
{ return to_space_; }
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), MakeUnusedPagesInToSpaceIterable(), v8::internal::HeapLayoutTracer::PrintHeapLayout(), and SetAgeMarkAndBelowAgeMarkPageFlags().
to_space() [2/2]
const SemiSpace& v8::internal::SemiSpaceNewSpace::to_space () const [inline]
Definition at line 402 of file new-spaces.h.
{ return to_space_; }
TotalCapacity()
size_t v8::internal::SemiSpaceNewSpace::TotalCapacity () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 301 of file new-spaces.h.
{ return target_capacity_; }
Referenced by v8::internal::ScavengerCollector::NumberOfScavengeTasks().
ZapUnusedMemory()
void v8::internal::SemiSpaceNewSpace::ZapUnusedMemory ()
Definition at line 740 of file new-spaces.cc.
                                        {
  if (!IsFromSpaceCommitted()) {
    return;
  }
  for (PageMetadata* page : PageRange(from_space().first_page(), nullptr)) {
    heap::ZapBlock(page->area_start(),
                   page->HighWaterMark() - page->area_start(),
                   heap::ZapValue());
  }
}
References first_page(), from_space(), IsFromSpaceCommitted(), v8::internal::heap::ZapBlock(), and v8::internal::heap::ZapValue().
Referenced by GarbageCollectionEpilogue().
Friends And Related Function Documentation
SemiSpaceNewSpaceAllocatorPolicy
friend class SemiSpaceNewSpaceAllocatorPolicy [friend]
Definition at line 498 of file new-spaces.h.
Referenced by CreateAllocatorPolicy().
SemiSpaceObjectIterator
friend class SemiSpaceObjectIterator [friend]
Definition at line 497 of file new-spaces.h.
Referenced by GetObjectIterator().
Member Data Documentation
age_mark_
Address v8::internal::SemiSpaceNewSpace::age_mark_ = kNullAddress [private]
Definition at line 492 of file new-spaces.h.
Referenced by IsAddressBelowAgeMark(), SetAgeMarkAndBelowAgeMarkPageFlags(), and ShouldPageBePromoted().
allocation_top_
Address v8::internal::SemiSpaceNewSpace::allocation_top_ = kNullAddress [private]
Definition at line 474 of file new-spaces.h.
Referenced by DecrementAllocationTop(), IncrementAllocationTop(), and SwapSemiSpaces().
from_space_
SemiSpace v8::internal::SemiSpaceNewSpace::from_space_ [private]
Definition at line 470 of file new-spaces.h.
Referenced by CommittedPhysicalMemory(), ContainsSlow(), GarbageCollectionEpilogue(), Shrink(), and SwapSemiSpaces().
maximum_capacity_
const size_t v8::internal::SemiSpaceNewSpace::maximum_capacity_ = 0 [private]
Definition at line 489 of file new-spaces.h.
Referenced by Grow(), GrowToMaximumCapacityForTesting(), SemiSpaceNewSpace(), and Shrink().
minimum_capacity_
const size_t v8::internal::SemiSpaceNewSpace::minimum_capacity_ = 0 [private]
Definition at line 486 of file new-spaces.h.
Referenced by SemiSpaceNewSpace(), and Shrink().
parked_allocation_buffers_
ParkedAllocationBuffersVector v8::internal::SemiSpaceNewSpace::parked_allocation_buffers_ [private]
Definition at line 476 of file new-spaces.h.
Referenced by AddParkedAllocationBuffer(), Allocate(), and ResetParkedAllocationBuffers().
quarantined_size_
size_t v8::internal::SemiSpaceNewSpace::quarantined_size_ = 0 [private]
Definition at line 479 of file new-spaces.h.
Referenced by SwapSemiSpaces().
size_after_last_gc_
size_t v8::internal::SemiSpaceNewSpace::size_after_last_gc_ = 0 [private]
Definition at line 482 of file new-spaces.h.
Referenced by AllocatedSinceLastGC(), and GarbageCollectionEpilogue().
target_capacity_
size_t v8::internal::SemiSpaceNewSpace::target_capacity_ = 0 [private]
Definition at line 495 of file new-spaces.h.
Referenced by AddFreshPage(), GarbageCollectionEpilogue(), Grow(), SemiSpaceNewSpace(), and Shrink().
to_space_
SemiSpace v8::internal::SemiSpaceNewSpace::to_space_ [private]
Definition at line 469 of file new-spaces.h.
Referenced by AddFreshPage(), AddParkedAllocationBuffer(), Allocate(), AllocateOnNewPageBeyondCapacity(), CommittedPhysicalMemory(), ContainsSlow(), FillCurrentPageForTesting(), GarbageCollectionEpilogue(), GetSpaceRemainingOnCurrentPageForTesting(), MoveQuarantinedPage(), SetAgeMarkAndBelowAgeMarkPageFlags(), Shrink(), Size(), and SwapSemiSpaces().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/new-spaces.h
/mnt/V8SourceCode/src/heap/new-spaces-inl.h
/mnt/V8SourceCode/src/heap/new-spaces.cc