v8::internal::swiss_table::BitMask< T, SignificantBits, Shift > Class Template Reference
#include <swiss-hash-table-helpers.h>
Public Types
using value_type = int
using iterator = BitMask
using const_iterator = BitMask
Public Member Functions
BitMask (T mask)
BitMask & operator++ ()
operator bool () const
int operator* () const
int LowestBitSet () const
int HighestBitSet () const
BitMask begin () const
BitMask end () const
int TrailingZeros () const
int LeadingZeros () const
Private Attributes
T mask_
Friends
bool operator== (const BitMask &a, const BitMask &b)
bool operator!= (const BitMask &a, const BitMask &b)
Detailed Description
template<class T, int SignificantBits, int Shift = 0>
class v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >
Definition at line 122 of file swiss-hash-table-helpers.h.
Member Typedef Documentation
const_iterator
template<class T , int SignificantBits, int Shift = 0>
using v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::const_iterator = BitMask
Definition at line 130 of file swiss-hash-table-helpers.h.
iterator
template<class T , int SignificantBits, int Shift = 0>
using v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::iterator = BitMask
Definition at line 129 of file swiss-hash-table-helpers.h.
value_type
template<class T , int SignificantBits, int Shift = 0>
using v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::value_type = int
Definition at line 128 of file swiss-hash-table-helpers.h.
Constructor & Destructor Documentation
BitMask()
template<class T , int SignificantBits, int Shift = 0>
v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::BitMask (T mask) [inline], [explicit]
Definition at line 132 of file swiss-hash-table-helpers.h.
: mask_(mask) {}
Referenced by v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::end().
Member Function Documentation
begin()
template<class T , int SignificantBits, int Shift = 0>
BitMask v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::begin () const [inline]
Definition at line 146 of file swiss-hash-table-helpers.h.
{ return *this; }
end()
template<class T , int SignificantBits, int Shift = 0>
BitMask v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::end () const [inline]
Definition at line 147 of file swiss-hash-table-helpers.h.
{ return BitMask(0); }
References v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::BitMask().
HighestBitSet()
template<class T , int SignificantBits, int Shift = 0>
int v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::HighestBitSet () const [inline]
Definition at line 141 of file swiss-hash-table-helpers.h.
                            {
    return (sizeof(T) * CHAR_BIT - base::bits::CountLeadingZeros(mask_) - 1) >>
           Shift;
  }
References v8::base::bits::CountLeadingZeros(), and v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::mask_.
LeadingZeros()
template<class T , int SignificantBits, int Shift = 0>
int v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::LeadingZeros () const [inline]
Definition at line 154 of file swiss-hash-table-helpers.h.
                           {
    constexpr int total_significant_bits = SignificantBits << Shift;
    constexpr int extra_bits = sizeof(T) * 8 - total_significant_bits;
    return base::bits::CountLeadingZeros(mask_ << extra_bits) >> Shift;
  }
References v8::base::bits::CountLeadingZeros(), v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::mask_, and T.
LowestBitSet()
template<class T , int SignificantBits, int Shift = 0>
int v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::LowestBitSet () const [inline]
Definition at line 140 of file swiss-hash-table-helpers.h.
{ return TrailingZeros(); }
References v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::TrailingZeros().
Referenced by v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::operator*().
operator bool()
template<class T , int SignificantBits, int Shift = 0>
v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::operator bool () const [inline], [explicit]
Definition at line 138 of file swiss-hash-table-helpers.h.
{ return mask_ != 0; }
References v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::mask_.
operator*()
template<class T , int SignificantBits, int Shift = 0>
int v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::operator* () const [inline]
Definition at line 139 of file swiss-hash-table-helpers.h.
{ return LowestBitSet(); }
References v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::LowestBitSet().
operator++()
template<class T , int SignificantBits, int Shift = 0>
BitMask& v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::operator++ () [inline]
Definition at line 133 of file swiss-hash-table-helpers.h.
                        {
    // Clear the least significant bit that is set.
    mask_ &= (mask_ - 1);
    return *this;
  }
References v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::mask_.
TrailingZeros()
template<class T , int SignificantBits, int Shift = 0>
int v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::TrailingZeros () const [inline]
Definition at line 149 of file swiss-hash-table-helpers.h.
                            {
    DCHECK_NE(mask_, 0);
    return base::bits::CountTrailingZerosNonZero(mask_) >> Shift;
  }
References v8::base::bits::CountTrailingZerosNonZero(), DCHECK_NE, and v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::mask_.
Referenced by v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::LowestBitSet().
Friends And Related Function Documentation
operator!=
template<class T , int SignificantBits, int Shift = 0>
bool operator!= (const BitMask< T, SignificantBits, Shift > & a, const BitMask< T, SignificantBits, Shift > & b) [friend]
Definition at line 164 of file swiss-hash-table-helpers.h.
                                                             {
    return a.mask_ != b.mask_;
  }
operator==
template<class T , int SignificantBits, int Shift = 0>
bool operator== (const BitMask< T, SignificantBits, Shift > & a, const BitMask< T, SignificantBits, Shift > & b) [friend]
Definition at line 161 of file swiss-hash-table-helpers.h.
                                                             {
    return a.mask_ == b.mask_;
  }
Member Data Documentation
mask_
template<class T , int SignificantBits, int Shift = 0>
T v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::mask_ [private]
Definition at line 168 of file swiss-hash-table-helpers.h.
Referenced by v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::HighestBitSet(), v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::LeadingZeros(), v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::operator bool(), v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::operator++(), and v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::TrailingZeros().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/swiss-hash-table-helpers.h