v8::internal::PagedSpaceBase Class Reference
#include <paged-spaces.h>
Classes
class ConcurrentAllocationMutex
Public Types
using iterator = PageIterator
using const_iterator = ConstPageIterator
Public Member Functions
PagedSpaceBase (Heap *heap, AllocationSpace id, Executability executable, std::unique_ptr< FreeList > free_list, CompactionSpaceKind compaction_space_kind)
~PagedSpaceBase () override
bool Contains (Address a) const
bool Contains (Tagged< Object > o) const
bool ContainsSlow (Address addr) const
Executability executable () const
size_t Capacity () const
size_t CommittedPhysicalMemory () const override
void IncrementCommittedPhysicalMemory (size_t increment_value)
void DecrementCommittedPhysicalMemory (size_t decrement_value)
void ClearAllocatorState ()
size_t Available () const override
size_t Size () const override
size_t Waste () const
V8_WARN_UNUSED_RESULT std::optional< std::pair< Address, size_t > > RawAllocateBackground (LocalHeap *local_heap, size_t min_size_in_bytes, size_t max_size_in_bytes, AllocationOrigin origin)
size_t Free (Address start, size_t size_in_bytes)
size_t FreeDuringSweep (Address start, size_t size_in_bytes)
void ResetFreeList ()
void DecreaseAllocatedBytes (size_t bytes, PageMetadata *page)
void IncreaseAllocatedBytes (size_t bytes, PageMetadata *page)
void DecreaseCapacity (size_t bytes)
void IncreaseCapacity (size_t bytes)
PageMetadata * InitializePage (MutablePageMetadata *chunk) override
virtual void RemovePageFromSpace (PageMetadata *page)
virtual size_t AddPage (PageMetadata *page)
virtual void RemovePage (PageMetadata *page)
PageMetadata * RemovePageSafe (int size_in_bytes)
bool CanExpand (size_t size) const
int CountTotalPages () const
int AreaSize () const
bool is_compaction_space () const
CompactionSpaceKind compaction_space_kind () const
void MergeCompactionSpace (CompactionSpace *other)
virtual void RefillFreeList ()
base::Mutex * mutex ()
void UnlinkFreeListCategories (PageMetadata *page)
size_t RelinkFreeListCategories (PageMetadata *page)
PageMetadata * first_page () override
const PageMetadata * first_page () const override
PageMetadata * last_page () override
const PageMetadata * last_page () const override
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
std::unique_ptr< ObjectIterator > GetObjectIterator (Heap *heap) override
void AddRangeToActiveSystemPages (PageMetadata *page, Address start, Address end)
void ReduceActiveSystemPages (PageMetadata *page, ActiveSystemPages active_system_pages)
bool TryExpand (LocalHeap *local_heap, AllocationOrigin origin)
void RefineAllocatedBytesAfterSweeping (PageMetadata *page)
virtual void AdjustDifferenceInAllocatedBytes (size_t diff)
Static Public Attributes
static const size_t kCompactionMemoryWanted = 500 * KB
Protected Member Functions
virtual bool snapshotable () const
bool HasPages () const
void TearDown ()
virtual void NotifyNewPage (PageMetadata *page)
size_t committed_physical_memory () const
void RemovePageFromSpaceImpl (PageMetadata *page)
void AddPageImpl (PageMetadata *page)
Protected Attributes
Executability executable_
CompactionSpaceKind compaction_space_kind_
size_t area_size_
AllocationStats accounting_stats_
base::Mutex space_mutex_
std::atomic< size_t > committed_physical_memory_ {0}
size_t size_at_last_gc_ = 0
Private Member Functions
template<bool during_sweep>
size_t FreeInternal (Address start, size_t size_in_bytes)
bool SupportsConcurrentAllocation () const
Friends
class IncrementalMarking
class MarkCompactCollector
class PagedSpaceAllocatorPolicy
class heap::HeapTester
Detailed Description
Definition at line 111 of file paged-spaces.h.
Member Typedef Documentation
const_iterator
using v8::internal::PagedSpaceBase::const_iterator = ConstPageIterator
Definition at line 115 of file paged-spaces.h.
iterator
using v8::internal::PagedSpaceBase::iterator = PageIterator
Definition at line 114 of file paged-spaces.h.
Constructor & Destructor Documentation
PagedSpaceBase()
v8::internal::PagedSpaceBase::PagedSpaceBase (Heap * heap, AllocationSpace id, Executability executable, std::unique_ptr< FreeList > free_list, CompactionSpaceKind compaction_space_kind)
Definition at line 68 of file paged-spaces.cc.
    : SpaceWithLinearArea(heap, space, std::move(free_list)),
      executable_(executable),
      compaction_space_kind_(compaction_space_kind) {
  area_size_ = MemoryChunkLayout::AllocatableMemoryInMemoryChunk(space);
  accounting_stats_.Clear();
}
References accounting_stats_, v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), area_size_, v8::internal::AllocationStats::Clear(), and space.
 PagedSpaceBase()
v8::internal::PagedSpaceBase::~PagedSpaceBase () [inline], [override]
Definition at line 123 of file paged-spaces.h.
{ TearDown(); }
Member Function Documentation
AddPage()
size_t v8::internal::PagedSpaceBase::AddPage (PageMetadata * page) [virtual]
Reimplemented in v8::internal::PagedSpaceForNewSpace.
Definition at line 250 of file paged-spaces.cc.
                                                 {
  AddPageImpl(page);
  return RelinkFreeListCategories(page);
}
References AddPageImpl(), and RelinkFreeListCategories().
Referenced by v8::internal::PagedSpaceForNewSpace::AddPage(), MergeCompactionSpace(), v8::internal::CompactionSpace::RefillFreeList(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), and TryExpand().
AddPageImpl()
void v8::internal::PagedSpaceBase::AddPageImpl (PageMetadata * page) [protected]
Definition at line 230 of file paged-spaces.cc.
                                                   {
  DCHECK_NOT_NULL(page);
  CHECK(page->SweepingDone());
  page->set_owner(this);
  DCHECK_IMPLIES(identity() == NEW_SPACE,
                 page->Chunk()->IsFlagSet(MemoryChunk::TO_PAGE));
  DCHECK_IMPLIES(identity() != NEW_SPACE,
                 !page->Chunk()->IsFlagSet(MemoryChunk::TO_PAGE));
  memory_chunk_list_.PushBack(page);
  AccountCommitted(page->size());
  IncreaseCapacity(page->area_size());
  IncreaseAllocatedBytes(page->allocated_bytes(), page);
  ForAll<ExternalBackingStoreType>(
      [this, page](ExternalBackingStoreType type, int index) {
        IncrementExternalBackingStoreBytes(
            type, page->ExternalBackingStoreBytes(type));
      });
  IncrementCommittedPhysicalMemory(page->CommittedPhysicalMemory());
}
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MemoryChunkMetadata::area_size(), CHECK, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::MutablePageMetadata::ExternalBackingStoreBytes(), IncreaseAllocatedBytes(), IncreaseCapacity(), IncrementCommittedPhysicalMemory(), v8::internal::index, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::NEW_SPACE, v8::internal::MemoryChunkMetadata::set_owner(), v8::internal::MemoryChunkMetadata::size(), v8::internal::MutablePageMetadata::SweepingDone(), v8::internal::MemoryChunk::TO_PAGE, and v8::internal::tracing::type.
Referenced by AddPage(), and v8::internal::OldSpace::AddPromotedPage().
AddRangeToActiveSystemPages()
void v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages (PageMetadata * page, Address start, Address end)
Definition at line 497 of file paged-spaces.cc.
                                                                             {
  MemoryChunk* chunk = page->Chunk();
  DCHECK_LE(chunk->address(), start);
  DCHECK_LT(start, end);
  DCHECK_LE(end, chunk->address() + PageMetadata::kPageSize);
  const size_t added_pages = page->active_system_pages()->Add(
      chunk->Offset(start), chunk->Offset(end),
      MemoryAllocator::GetCommitPageSizeBits());
  IncrementCommittedPhysicalMemory(added_pages *
                                   MemoryAllocator::GetCommitPageSize());
}
References v8::internal::PageMetadata::active_system_pages(), heap::base::ActiveSystemPages::Add(), v8::internal::MemoryChunk::address(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_LE, DCHECK_LT, end(), v8::internal::MemoryAllocator::GetCommitPageSize(), v8::internal::MemoryAllocator::GetCommitPageSizeBits(), IncrementCommittedPhysicalMemory(), v8::internal::MutablePageMetadata::kPageSize, and v8::internal::MemoryChunk::Offset().
Referenced by v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
AdjustDifferenceInAllocatedBytes()
virtual void v8::internal::PagedSpaceBase::AdjustDifferenceInAllocatedBytes (size_t diff) [inline], [virtual]
Reimplemented in v8::internal::StickySpace.
Definition at line 293 of file paged-spaces.h.
{}
Referenced by RefineAllocatedBytesAfterSweeping().
AreaSize()
int v8::internal::PagedSpaceBase::AreaSize () const [inline]
Definition at line 239 of file paged-spaces.h.
{ return static_cast<int>(area_size_); }
Referenced by v8::internal::PagedSpaceAllocatorPolicy::RefillLab().
Available()
size_t v8::internal::PagedSpaceBase::Available () const [override]
Definition at line 323 of file paged-spaces.cc.
                                       {
  ConcurrentAllocationMutex guard(this);
  return free_list_->Available();
}
Referenced by v8::internal::PagedSpaceForNewSpace::Available(), v8::internal::Heap::PrintFreeListsStats(), and v8::internal::Heap::PrintShortHeapStatistics().
begin() [1/2]
iterator v8::internal::PagedSpaceBase::begin () [inline]
Definition at line 276 of file paged-spaces.h.
{ return iterator(first_page()); }
Referenced by CountTotalPages(), MergeCompactionSpace(), v8::internal::OldGenerationMemoryChunkIterator::next(), v8::internal::MarkCompactCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), and v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits().
begin() [2/2]
const_iterator v8::internal::PagedSpaceBase::begin () const [inline]
Definition at line 279 of file paged-spaces.h.
{ return const_iterator(first_page()); }
CanExpand()
bool v8::internal::PagedSpaceBase::CanExpand (size_t size) const
Capacity()
size_t v8::internal::PagedSpaceBase::Capacity () const [inline]
Definition at line 134 of file paged-spaces.h.
{ return accounting_stats_.Capacity(); }
Referenced by v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration(), MergeCompactionSpace(), v8::internal::Heap::NewSpaceCapacity(), v8::internal::Heap::NewSpaceTargetCapacity(), v8::internal::Heap::PrintFreeListsStats(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), v8::internal::Heap::RecordStats(), and v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded().
ClearAllocatorState()
void v8::internal::PagedSpaceBase::ClearAllocatorState () [inline]
Definition at line 151 of file paged-spaces.h.
                             {
    accounting_stats_.ClearSize();
    if (v8_flags.black_allocated_pages) {
      free_list_->ResetForNonBlackAllocatedPages();
    } else {
      free_list_->Reset();
    }
  }
References v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), and v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits().
committed_physical_memory()
size_t v8::internal::PagedSpaceBase::committed_physical_memory () const [inline], [protected]
Definition at line 309 of file paged-spaces.h.
                                           {
    return committed_physical_memory_.load(std::memory_order_relaxed);
  }
Referenced by CommittedPhysicalMemory().
CommittedPhysicalMemory()
size_t v8::internal::PagedSpaceBase::CommittedPhysicalMemory () const [override]
Definition at line 156 of file paged-spaces.cc.
                                                     {
  if (!base::OS::HasLazyCommits()) {
    DCHECK_EQ(0, committed_physical_memory());
    return CommittedMemory();
  }
  return committed_physical_memory();
}
References committed_physical_memory(), DCHECK_EQ, and v8::base::OS::HasLazyCommits().
compaction_space_kind()
CompactionSpaceKind v8::internal::PagedSpaceBase::compaction_space_kind () const [inline]
Definition at line 245 of file paged-spaces.h.
                                                    {
    return compaction_space_kind_;
  }
Contains() [1/2]
bool v8::internal::PagedSpaceBase::Contains (Address a) const [inline]
Definition at line 78 of file paged-spaces-inl.h.
                                                {
  return PageMetadata::FromAddress(addr)->owner() == this;
}
References v8::internal::PageMetadata::FromAddress(), and v8::internal::MutablePageMetadata::owner().
Referenced by v8::internal::Heap::Contains(), v8::internal::Heap::ContainsCode(), v8::internal::Heap::InOldSpace(), v8::internal::Heap::InSpace(), and v8::internal::Heap::SharedHeapContains().
Contains() [2/2]
bool v8::internal::PagedSpaceBase::Contains (Tagged< Object > o) const [inline]
Definition at line 82 of file paged-spaces-inl.h.
                                                    {
  if (!IsHeapObject(o)) return false;
  return PageMetadata::FromAddress(o.ptr())->owner() == this;
}
References v8::internal::PageMetadata::FromAddress(), v8::internal::IsHeapObject(), v8::internal::MutablePageMetadata::owner(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
ContainsSlow()
bool v8::internal::PagedSpaceBase::ContainsSlow (Address addr) const
Definition at line 193 of file paged-spaces.cc.
                                                    {
  MemoryChunk* chunk = MemoryChunk::FromAddress(addr);
  for (const PageMetadata* page : *this) {
    if (page->Chunk() == chunk) return true;
  }
  return false;
}
References v8::internal::MemoryChunkMetadata::Chunk(), and v8::internal::MemoryChunk::FromAddress().
Referenced by v8::internal::Heap::InSpaceSlow().
CountTotalPages()
int v8::internal::PagedSpaceBase::CountTotalPages () const
Definition at line 319 of file paged-spaces.cc.
                                          {
  return base::checked_cast<int>(std::distance(begin(), end()));
}
References begin(), and end().
DecreaseAllocatedBytes()
void v8::internal::PagedSpaceBase::DecreaseAllocatedBytes (size_t bytes, PageMetadata * page) [inline]
Definition at line 189 of file paged-spaces.h.
                                                                {
    accounting_stats_.DecreaseAllocatedBytes(bytes, page);
  }
Referenced by RefineAllocatedBytesAfterSweeping(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), and RemovePage().
DecreaseCapacity()
void v8::internal::PagedSpaceBase::DecreaseCapacity (size_t bytes) [inline]
Definition at line 195 of file paged-spaces.h.
                                      {
    accounting_stats_.DecreaseCapacity(bytes);
  }
Referenced by RemovePage().
DecrementCommittedPhysicalMemory()
void v8::internal::PagedSpaceBase::DecrementCommittedPhysicalMemory (size_t decrement_value)
Definition at line 172 of file paged-spaces.cc.
                                                                            {
  if (!base::OS::HasLazyCommits() || decrement_value == 0) return;
  size_t old_value = committed_physical_memory_.fetch_sub(
      decrement_value, std::memory_order_relaxed);
  USE(old_value);
  DCHECK_GT(old_value, old_value - decrement_value);
}
References committed_physical_memory_, DCHECK_GT, v8::base::OS::HasLazyCommits(), and USE.
Referenced by ReduceActiveSystemPages(), RemovePage(), and RemovePageFromSpaceImpl().
end() [1/2]
iterator v8::internal::PagedSpaceBase::end () [inline]
Definition at line 277 of file paged-spaces.h.
{ return iterator(nullptr); }
Referenced by AddRangeToActiveSystemPages(), CountTotalPages(), MergeCompactionSpace(), v8::internal::OldGenerationMemoryChunkIterator::next(), v8::internal::MarkCompactCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), and v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits().
end() [2/2]
const_iterator v8::internal::PagedSpaceBase::end () const [inline]
Definition at line 280 of file paged-spaces.h.
{ return const_iterator(nullptr); }
executable()
Executability v8::internal::PagedSpaceBase::executable () const [inline]
Definition at line 131 of file paged-spaces.h.
{ return executable_; }
Referenced by TryExpand().
first_page() [1/2]
const PageMetadata* v8::internal::PagedSpaceBase::first_page () const [inline], [override]
Definition at line 265 of file paged-spaces.h.
                                                  {
    return reinterpret_cast<const PageMetadata*>(memory_chunk_list_.front());
  }
first_page() [2/2]
PageMetadata* v8::internal::PagedSpaceBase::first_page () [inline], [override]
Definition at line 262 of file paged-spaces.h.
                                      {
    return reinterpret_cast<PageMetadata*>(memory_chunk_list_.front());
  }
Free()
size_t v8::internal::PagedSpaceBase::Free (Address start, size_t size_in_bytes) [inline]
Definition at line 115 of file paged-spaces-inl.h.
                                                               {
  return FreeInternal</*during_sweep=*/false>(start, size_in_bytes);
}
Referenced by v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), and TryExpand().
FreeDuringSweep()
size_t v8::internal::PagedSpaceBase::FreeDuringSweep (Address start, size_t size_in_bytes) [inline]
Definition at line 119 of file paged-spaces-inl.h.
                                                                          {
  return FreeInternal</*during_sweep=*/true>(start, size_in_bytes);
}
Referenced by v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::AddToFreeListFreeSpaceHandler(), and v8::internal::Sweeper::SweepEmptyNewSpacePage().
FreeInternal()
template<bool during_sweep>
size_t v8::internal::PagedSpaceBase::FreeInternal (Address start, size_t size_in_bytes) [inline], [private]
Definition at line 88 of file paged-spaces-inl.h.
                                                                       {
  if (size_in_bytes == 0) return 0;
  size_t wasted;
  if (executable_) {
    WritableJitPage jit_page(start, size_in_bytes);
    WritableFreeSpace free_space = jit_page.FreeRange(start, size_in_bytes);
    heap()->CreateFillerObjectAtBackground(free_space);
    wasted = free_list_->Free(
        free_space, during_sweep ? kDoNotLinkCategory : kLinkCategory);
  } else {
    WritableFreeSpace free_space =
        WritableFreeSpace::ForNonExecutableMemory(start, size_in_bytes);
    heap()->CreateFillerObjectAtBackground(free_space);
    wasted = free_list_->Free(
        free_space, during_sweep ? kDoNotLinkCategory : kLinkCategory);
  }
  if constexpr (!during_sweep) {
    PageMetadata* page = PageMetadata::FromAddress(start);
    accounting_stats_.DecreaseAllocatedBytes(size_in_bytes, page);
    free_list()->increase_wasted_bytes(wasted);
  }
  DCHECK_GE(size_in_bytes, wasted);
  return size_in_bytes - wasted;
}
References DCHECK_GE, v8::internal::WritableFreeSpace::ForNonExecutableMemory(), v8::internal::WritableJitPage::FreeRange(), v8::internal::PageMetadata::FromAddress(), heap(), v8::internal::kDoNotLinkCategory, and v8::internal::kLinkCategory.
GetObjectIterator()
std::unique_ptr< ObjectIterator > v8::internal::PagedSpaceBase::GetObjectIterator (Heap * heap) [override]
Definition at line 357 of file paged-spaces.cc.
                                                                          {
  return std::unique_ptr<ObjectIterator>(
      new PagedSpaceObjectIterator(heap, this));
}
HasPages()
bool v8::internal::PagedSpaceBase::HasPages () const [inline], [protected]
Definition at line 300 of file paged-spaces.h.
{ return first_page() != nullptr; }
IncreaseAllocatedBytes()
void v8::internal::PagedSpaceBase::IncreaseAllocatedBytes (size_t bytes, PageMetadata * page) [inline]
Definition at line 192 of file paged-spaces.h.
                                                                {
    accounting_stats_.IncreaseAllocatedBytes(bytes, page);
  }
Referenced by AddPageImpl(), v8::internal::Sweeper::PrepareToBeSweptPage(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), and v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList().
IncreaseCapacity()
void v8::internal::PagedSpaceBase::IncreaseCapacity (size_t bytes) [inline]
Definition at line 198 of file paged-spaces.h.
                                      {
    accounting_stats_.IncreaseCapacity(bytes);
  }
Referenced by AddPageImpl().
IncrementCommittedPhysicalMemory()
void v8::internal::PagedSpaceBase::IncrementCommittedPhysicalMemory (size_t increment_value)
Definition at line 164 of file paged-spaces.cc.
                                                                            {
  if (!base::OS::HasLazyCommits() || increment_value == 0) return;
  size_t old_value = committed_physical_memory_.fetch_add(
      increment_value, std::memory_order_relaxed);
  USE(old_value);
  DCHECK_LT(old_value, old_value + increment_value);
}
References committed_physical_memory_, DCHECK_LT, v8::base::OS::HasLazyCommits(), and USE.
Referenced by AddPageImpl(), and AddRangeToActiveSystemPages().
InitializePage()
PageMetadata * v8::internal::PagedSpaceBase::InitializePage (MutablePageMetadata * chunk) [override]
Definition at line 79 of file paged-spaces.cc.
                                                {
  MemoryChunk* chunk = mutable_page_metadata->Chunk();
  PageMetadata* page = PageMetadata::cast(mutable_page_metadata);
  DCHECK_EQ(
      MemoryChunkLayout::AllocatableMemoryInMemoryChunk(page->owner_identity()),
      page->area_size());
  // Make sure that categories are initialized before freeing the area.
  page->ResetAllocationStatistics();
  page->AllocateFreeListCategories();
  page->InitializeFreeListCategories();
  page->list_node().Initialize();
  chunk->InitializationMemoryFence();
  return page;
}
References v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), v8::internal::PageMetadata::AllocateFreeListCategories(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::PageMetadata::cast(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_EQ, v8::internal::MemoryChunk::InitializationMemoryFence(), v8::internal::PageMetadata::InitializeFreeListCategories(), v8::internal::MutablePageMetadata::list_node(), v8::internal::MutablePageMetadata::owner_identity(), and v8::internal::MutablePageMetadata::ResetAllocationStatistics().
Referenced by v8::internal::PageMetadata::ConvertNewToOld().
is_compaction_space()
bool v8::internal::PagedSpaceBase::is_compaction_space () const [inline]
Definition at line 241 of file paged-spaces.h.
                                   {
    return compaction_space_kind_ != CompactionSpaceKind::kNone;
  }
References v8::internal::kNone.
Referenced by RefillFreeList(), and v8::internal::PagedSpaceAllocatorPolicy::RefillLab().
last_page() [1/2]
const PageMetadata* v8::internal::PagedSpaceBase::last_page () const [inline], [override]
Definition at line 272 of file paged-spaces.h.
                                                 {
    return reinterpret_cast<const PageMetadata*>(memory_chunk_list_.back());
  }
last_page() [2/2]
PageMetadata* v8::internal::PagedSpaceBase::last_page () [inline], [override]
Definition at line 269 of file paged-spaces.h.
                                     {
    return reinterpret_cast<PageMetadata*>(memory_chunk_list_.back());
  }
MergeCompactionSpace()
void v8::internal::PagedSpaceBase::MergeCompactionSpace (CompactionSpace * other)
Definition at line 112 of file paged-spaces.cc.
                                                                {
  base::MutexGuard guard(mutex());
  DCHECK_NE(NEW_SPACE, identity());
  DCHECK_NE(NEW_SPACE, other->identity());
  // Move over pages.
  for (auto it = other->begin(); it != other->end();) {
    PageMetadata* p = *(it++);
    // Ensure that pages are initialized before objects on it are discovered by
    // concurrent markers.
    p->Chunk()->InitializationMemoryFence();
    // Relinking requires the category to be unlinked.
    other->RemovePage(p);
    AddPage(p);
    DCHECK_IMPLIES(
        !p->Chunk()->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE),
        p->AvailableInFreeList() == p->AvailableInFreeListFromAllocatedBytes());
    // TODO(leszeks): Here we should allocation step, but:
    // 1. Allocation groups are currently not handled properly by the sampling
    // allocation profiler, and
    // 2. Observers might try to take the space lock, which isn't reentrant.
    // We'll have to come up with a better solution for allocation stepping
    // before shipping, which will likely be using LocalHeap.
  }
  const bool is_from_client_heap =
      (other->destination_heap() ==
       CompactionSpace::DestinationHeap::kSharedSpaceHeap);
  DCHECK_IMPLIES(is_from_client_heap, identity() == SHARED_SPACE);
  for (auto p : other->GetNewPages()) {
    heap()->NotifyOldGenerationExpansion(
        heap()->main_thread_local_heap(), identity(), p,
        is_from_client_heap
            ? Heap::OldGenerationExpansionNotificationOrigin::kFromClientHeap
            : Heap::OldGenerationExpansionNotificationOrigin::kFromSameHeap);
  }
  DCHECK_EQ(0u, other->Size());
  DCHECK_EQ(0u, other->Capacity());
}
References AddPage(), v8::internal::PageMetadata::AvailableInFreeList(), v8::internal::PageMetadata::AvailableInFreeListFromAllocatedBytes(), begin(), Capacity(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::internal::CompactionSpace::destination_heap(), end(), v8::internal::CompactionSpace::GetNewPages(), heap(), v8::internal::MemoryChunk::InitializationMemoryFence(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::Heap::kFromClientHeap, v8::internal::Heap::kFromSameHeap, v8::internal::CompactionSpace::kSharedSpaceHeap, mutex(), v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE, v8::internal::NEW_SPACE, RemovePage(), v8::internal::SHARED_SPACE, and Size().
Referenced by v8::internal::EvacuationAllocator::Finalize().
mutex()
base::Mutex* v8::internal::PagedSpaceBase::mutex () [inline]
Definition at line 257 of file paged-spaces.h.
{ return &space_mutex_; }
Referenced by v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationArea(), MergeCompactionSpace(), v8::internal::CompactionSpace::RefillFreeList(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), and RemovePageSafe().
NotifyNewPage()
virtual void v8::internal::PagedSpaceBase::NotifyNewPage (PageMetadata * page) [inline], [protected], [virtual]
Reimplemented in v8::internal::CompactionSpace.
Definition at line 307 of file paged-spaces.h.
{}
Referenced by TryExpand().
RawAllocateBackground()
V8_WARN_UNUSED_RESULT std::optional<std::pair<Address, size_t> > v8::internal::PagedSpaceBase::RawAllocateBackground (LocalHeap * local_heap, size_t min_size_in_bytes, size_t max_size_in_bytes, AllocationOrigin origin)
ReduceActiveSystemPages()
void v8::internal::PagedSpaceBase::ReduceActiveSystemPages (PageMetadata * page, ActiveSystemPages active_system_pages)
Definition at line 512 of file paged-spaces.cc.
                                                               {
  const size_t reduced_pages =
      page->active_system_pages()->Reduce(active_system_pages);
  DecrementCommittedPhysicalMemory(reduced_pages *
                                   MemoryAllocator::GetCommitPageSize());
}
References v8::internal::PageMetadata::active_system_pages(), DecrementCommittedPhysicalMemory(), v8::internal::MemoryAllocator::GetCommitPageSize(), and heap::base::ActiveSystemPages::Reduce().
Referenced by v8::internal::Sweeper::RawSweep(), and v8::internal::Sweeper::SweepEmptyNewSpacePage().
RefillFreeList()
void v8::internal::PagedSpaceBase::RefillFreeList () [virtual]
Reimplemented in v8::internal::CompactionSpace.
Definition at line 542 of file paged-spaces.cc.
                                    {
  // Any PagedSpace might invoke RefillFreeList.
  DCHECK(identity() == OLD_SPACE || identity() == CODE_SPACE ||
         identity() == SHARED_SPACE || identity() == NEW_SPACE ||
         identity() == TRUSTED_SPACE || identity() == SHARED_TRUSTED_SPACE);
  DCHECK_IMPLIES(identity() == NEW_SPACE, heap_->IsMainThread());
  DCHECK(!is_compaction_space());
  for (PageMetadata* p : heap()->sweeper()->GetAllSweptPagesSafe(this)) {
    // We regularly sweep NEVER_ALLOCATE_ON_PAGE pages. We drop the freelist
    // entries here to make them unavailable for allocations.
    if (p->Chunk()->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE)) {
      free_list_->EvictFreeListItems(p);
    }
    ConcurrentAllocationMutex guard(this);
    DCHECK_EQ(this, p->owner());
    RefineAllocatedBytesAfterSweeping(p);
    RelinkFreeListCategories(p);
  }
}
References v8::internal::CODE_SPACE, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, heap(), is_compaction_space(), v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE, v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, RefineAllocatedBytesAfterSweeping(), RelinkFreeListCategories(), v8::internal::SHARED_SPACE, v8::internal::SHARED_TRUSTED_SPACE, and v8::internal::TRUSTED_SPACE.
Referenced by v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping(), v8::internal::Heap::EnsureSweepingCompleted(), v8::internal::Heap::EnsureYoungSweepingCompleted(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), and v8::internal::PagedNewSpaceAllocatorPolicy::WaitForSweepingForAllocation().
RefineAllocatedBytesAfterSweeping()
void v8::internal::PagedSpaceBase::RefineAllocatedBytesAfterSweeping (PageMetadata * page)
Definition at line 201 of file paged-spaces.cc.
                                                                         {
  CHECK(page->SweepingDone());
  // The live_byte on the page was accounted in the space allocated
  // bytes counter. After sweeping allocated_bytes() contains the
  // accurate live byte count on the page.
  size_t old_counter = page->live_bytes();
  size_t new_counter = page->allocated_bytes();
  DCHECK_GE(old_counter, new_counter);
  if (old_counter > new_counter) {
    size_t counter_diff = old_counter - new_counter;
    if (identity() == NEW_SPACE) size_at_last_gc_ -= counter_diff;
    DecreaseAllocatedBytes(counter_diff, page);
    DCHECK_EQ(new_counter, accounting_stats_.AllocatedOnPage(page));
    AdjustDifferenceInAllocatedBytes(counter_diff);
  }
  if (!v8_flags.sticky_mark_bits) {
    // With sticky mark-bits the counter is reset on unmarking.
    page->SetLiveBytes(0);
  }
}
References accounting_stats_, AdjustDifferenceInAllocatedBytes(), v8::internal::MemoryChunkMetadata::allocated_bytes(), CHECK, DCHECK_EQ, DCHECK_GE, DecreaseAllocatedBytes(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::NEW_SPACE, v8::internal::MutablePageMetadata::SetLiveBytes(), size_at_last_gc_, v8::internal::MutablePageMetadata::SweepingDone(), and v8::internal::v8_flags.
Referenced by RefillFreeList(), and v8::internal::CompactionSpace::RefillFreeList().
RelinkFreeListCategories()
size_t v8::internal::PagedSpaceBase::RelinkFreeListCategories (PageMetadata * page)
Definition at line 527 of file paged-spaces.cc.
                                                                  {
  DCHECK_EQ(this, page->owner());
  size_t added = 0;
  page->ForAllFreeListCategories([this, &added](FreeListCategory* category) {
    added += category->available();
    category->Relink(free_list());
  });
  free_list()->increase_wasted_bytes(page->wasted_memory());
  DCHECK_IMPLIES(!page->Chunk()->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE),
                 page->AvailableInFreeList() ==
                     page->AvailableInFreeListFromAllocatedBytes());
  return added;
}
References v8::internal::FreeListCategory::available(), v8::internal::PageMetadata::AvailableInFreeList(), v8::internal::PageMetadata::AvailableInFreeListFromAllocatedBytes(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::PageMetadata::ForAllFreeListCategories(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE, v8::internal::MutablePageMetadata::owner(), v8::internal::FreeListCategory::Relink(), and v8::internal::MemoryChunkMetadata::wasted_memory().
Referenced by AddPage(), v8::internal::OldSpace::AddPromotedPage(), RefillFreeList(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), and v8::internal::Sweeper::SweepEmptyNewSpacePage().
RemovePage()
void v8::internal::PagedSpaceBase::RemovePage (PageMetadata * page) [virtual]
Reimplemented in v8::internal::PagedSpaceForNewSpace.
Definition at line 255 of file paged-spaces.cc.
                                                  {
  CHECK(page->SweepingDone());
  DCHECK_IMPLIES(identity() == NEW_SPACE,
                 page->Chunk()->IsFlagSet(MemoryChunk::TO_PAGE));
  memory_chunk_list_.Remove(page);
  UnlinkFreeListCategories(page);
  // Pages are only removed from new space when they are promoted to old space
  // during a GC. This happens after sweeping as started and the allocation
  // counters have been reset.
  DCHECK_IMPLIES(identity() == NEW_SPACE,
                 heap()->gc_state() != Heap::NOT_IN_GC);
  if (identity() == NEW_SPACE) {
    page->ReleaseFreeListCategories();
  } else {
    DecreaseAllocatedBytes(page->allocated_bytes(), page);
    free_list()->decrease_wasted_bytes(page->wasted_memory());
  }
  DecreaseCapacity(page->area_size());
  AccountUncommitted(page->size());
  ForAll<ExternalBackingStoreType>(
      [this, page](ExternalBackingStoreType type, int index) {
        DecrementExternalBackingStoreBytes(
            type, page->ExternalBackingStoreBytes(type));
      });
  DecrementCommittedPhysicalMemory(page->CommittedPhysicalMemory());
}
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MemoryChunkMetadata::area_size(), CHECK, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), DCHECK_IMPLIES, DecreaseAllocatedBytes(), DecreaseCapacity(), DecrementCommittedPhysicalMemory(), v8::internal::MutablePageMetadata::ExternalBackingStoreBytes(), heap(), v8::internal::index, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::NEW_SPACE, v8::internal::Heap::NOT_IN_GC, v8::internal::PageMetadata::ReleaseFreeListCategories(), v8::internal::MemoryChunkMetadata::size(), v8::internal::MutablePageMetadata::SweepingDone(), v8::internal::MemoryChunk::TO_PAGE, v8::internal::tracing::type, UnlinkFreeListCategories(), and v8::internal::MemoryChunkMetadata::wasted_memory().
Referenced by MergeCompactionSpace(), v8::internal::CompactionSpace::RefillFreeList(), v8::internal::PagedSpaceForNewSpace::RemovePage(), and RemovePageSafe().
RemovePageFromSpace()
void v8::internal::PagedSpaceBase::RemovePageFromSpace (PageMetadata * page) [virtual]
Reimplemented in v8::internal::PagedSpaceForNewSpace.
Definition at line 332 of file paged-spaces.cc.
                                                           {
  RemovePageFromSpaceImpl(page);
}
References RemovePageFromSpaceImpl().
RemovePageFromSpaceImpl()
void v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl (PageMetadata * page) [protected]
Definition at line 336 of file paged-spaces.cc.
                                                               {
  DCHECK(page->SweepingDone());
  DCHECK_EQ(0, page->live_bytes());
  DCHECK_EQ(page->owner(), this);
  DCHECK_IMPLIES(identity() == NEW_SPACE,
                 page->Chunk()->IsFlagSet(MemoryChunk::TO_PAGE));
  memory_chunk_list_.Remove(page);
  free_list_->EvictFreeListItems(page);
  if (identity() == CODE_SPACE) {
    heap()->isolate()->RemoveCodeMemoryChunk(page);
  }
  AccountUncommitted(page->size());
  DecrementCommittedPhysicalMemory(page->CommittedPhysicalMemory());
  accounting_stats_.DecreaseCapacity(page->area_size());
}
References accounting_stats_, v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::CODE_SPACE, v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::AllocationStats::DecreaseCapacity(), DecrementCommittedPhysicalMemory(), heap(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::NEW_SPACE, v8::internal::MutablePageMetadata::owner(), v8::internal::MemoryChunkMetadata::size(), v8::internal::MutablePageMetadata::SweepingDone(), and v8::internal::MemoryChunk::TO_PAGE.
Referenced by RemovePageFromSpace(), and v8::internal::PagedSpaceForNewSpace::RemovePageFromSpace().
RemovePageSafe()
PageMetadata * v8::internal::PagedSpaceBase::RemovePageSafe (int size_in_bytes)
Definition at line 222 of file paged-spaces.cc.
                                                              {
  base::MutexGuard guard(mutex());
  PageMetadata* page = free_list()->GetPageForSize(size_in_bytes);
  if (!page) return nullptr;
  RemovePage(page);
  return page;
}
References mutex(), and RemovePage().
Referenced by v8::internal::PagedSpaceAllocatorPolicy::RefillLab().
ResetFreeList()
void v8::internal::PagedSpaceBase::ResetFreeList ()
Definition at line 282 of file paged-spaces.cc.
                                   {
  for (PageMetadata* page : *this) {
    free_list_->EvictFreeListItems(page);
  }
  DCHECK(free_list_->IsEmpty());
  DCHECK_EQ(0, free_list_->Available());
}
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::MainAllocator::FreeLinearAllocationAreaAndResetFreeList().
Size()
size_t v8::internal::PagedSpaceBase::Size () const [inline], [override]
Definition at line 170 of file paged-spaces.h.
{ return accounting_stats_.Size(); }
Referenced by v8::internal::PagedSpaceForNewSpace::AllocatedSinceLastGC(), MergeCompactionSpace(), v8::internal::Heap::PrintFreeListsStats(), and v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits().
snapshotable()
virtual bool v8::internal::PagedSpaceBase::snapshotable () const [inline], [protected], [virtual]
Reimplemented in v8::internal::CompactionSpace.
Definition at line 298 of file paged-spaces.h.
{ return true; }
SupportsConcurrentAllocation()
bool v8::internal::PagedSpaceBase::SupportsConcurrentAllocation () const [inline], [private]
Definition at line 349 of file paged-spaces.h.
                                            {
    return !is_compaction_space() && (identity() != NEW_SPACE);
  }
References v8::internal::NEW_SPACE.
TearDown()
void v8::internal::PagedSpaceBase::TearDown () [protected]
Definition at line 95 of file paged-spaces.cc.
                              {
  const bool is_marking = heap_->isolate()->isolate_data()->is_marking();
  while (!memory_chunk_list_.Empty()) {
    MutablePageMetadata* chunk = memory_chunk_list_.front();
    memory_chunk_list_.Remove(chunk);
    const auto mode = (id_ == NEW_SPACE || id_ == OLD_SPACE)
                          ? MemoryAllocator::FreeMode::kPool
                          : MemoryAllocator::FreeMode::kImmediately;
    if (mode == MemoryAllocator::FreeMode::kPool &&
        (is_marking || V8_ENABLE_STICKY_MARK_BITS_BOOL)) {
      chunk->ClearLiveness();
    }
    heap()->memory_allocator()->Free(mode, chunk);
  }
  accounting_stats_.Clear();
}
References accounting_stats_, v8::internal::AllocationStats::Clear(), v8::internal::MutablePageMetadata::ClearLiveness(), heap(), v8::internal::MemoryAllocator::kImmediately, v8::internal::MemoryAllocator::kPool, mode(), v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, and V8_ENABLE_STICKY_MARK_BITS_BOOL.
Referenced by v8::internal::PagedSpaceForNewSpace::TearDown().
TryExpand()
bool v8::internal::PagedSpaceBase::TryExpand (LocalHeap * local_heap, AllocationOrigin origin)
Definition at line 290 of file paged-spaces.cc.
                                                                             {
  DCHECK_EQ(!local_heap, origin == AllocationOrigin::kGC);
  const size_t accounted_size =
      MemoryChunkLayout::AllocatableMemoryInMemoryChunk(identity());
  if (origin != AllocationOrigin::kGC && identity() != NEW_SPACE) {
    base::MutexGuard expansion_guard(heap_->heap_expansion_mutex());
    if (!heap()->IsOldGenerationExpansionAllowed(accounted_size,
                                                 expansion_guard)) {
      return false;
    }
  }
  const MemoryAllocator::AllocationMode allocation_mode =
      (identity() == NEW_SPACE || identity() == OLD_SPACE)
          ? MemoryAllocator::AllocationMode::kUsePool
          : MemoryAllocator::AllocationMode::kRegular;
  PageMetadata* page = heap()->memory_allocator()->AllocatePage(
      allocation_mode, this, executable());
  if (page == nullptr) return false;
  DCHECK_EQ(page->area_size(), accounted_size);
  ConcurrentAllocationMutex guard(this);
  AddPage(page);
  if (origin != AllocationOrigin::kGC && identity() != NEW_SPACE) {
    heap()->NotifyOldGenerationExpansion(local_heap, identity(), page);
  }
  Free(page->area_start(), page->area_size());
  NotifyNewPage(page);
  return true;
}
References AddPage(), v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::area_start(), DCHECK_EQ, executable(), Free(), heap(), v8::internal::kGC, v8::internal::MemoryAllocator::kRegular, v8::internal::MemoryAllocator::kUsePool, v8::internal::NEW_SPACE, NotifyNewPage(), and v8::internal::OLD_SPACE.
Referenced by v8::internal::PagedSpaceForNewSpace::AllocatePage(), and v8::internal::PagedSpaceAllocatorPolicy::TryExpandAndAllocate().
UnlinkFreeListCategories()
void v8::internal::PagedSpaceBase::UnlinkFreeListCategories (PageMetadata * page)
Definition at line 520 of file paged-spaces.cc.
                                                                {
  DCHECK_EQ(this, page->owner());
  page->ForAllFreeListCategories([this](FreeListCategory* category) {
    free_list()->RemoveCategory(category);
  });
}
References DCHECK_EQ, v8::internal::PageMetadata::ForAllFreeListCategories(), and v8::internal::MutablePageMetadata::owner().
Referenced by RemovePage().
Waste()
size_t v8::internal::PagedSpaceBase::Waste () const
Definition at line 328 of file paged-spaces.cc.
                                   {
  return free_list_->wasted_bytes();
}
Referenced by v8::internal::Heap::PrintFreeListsStats(), and v8::internal::Heap::YoungGenerationWastedBytes().
Friends And Related Function Documentation
heap::HeapTester
friend class heap::HeapTester [friend]
Definition at line 358 of file paged-spaces.h.
IncrementalMarking
friend class IncrementalMarking [friend]
Definition at line 353 of file paged-spaces.h.
MarkCompactCollector
friend class MarkCompactCollector [friend]
Definition at line 354 of file paged-spaces.h.
PagedSpaceAllocatorPolicy
friend class PagedSpaceAllocatorPolicy [friend]
Definition at line 355 of file paged-spaces.h.
Referenced by v8::internal::PagedSpace::CreateAllocatorPolicy().
Member Data Documentation
accounting_stats_
AllocationStats v8::internal::PagedSpaceBase::accounting_stats_ [protected]
Definition at line 324 of file paged-spaces.h.
Referenced by PagedSpaceBase(), RefineAllocatedBytesAfterSweeping(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), RemovePageFromSpaceImpl(), and TearDown().
area_size_
size_t v8::internal::PagedSpaceBase::area_size_ [protected]
Definition at line 321 of file paged-spaces.h.
Referenced by PagedSpaceBase().
committed_physical_memory_
std::atomic<size_t> v8::internal::PagedSpaceBase::committed_physical_memory_ {0} [protected]
Definition at line 329 of file paged-spaces.h.
Referenced by DecrementCommittedPhysicalMemory(), and IncrementCommittedPhysicalMemory().
compaction_space_kind_
CompactionSpaceKind v8::internal::PagedSpaceBase::compaction_space_kind_ [protected]
Definition at line 319 of file paged-spaces.h.
executable_
Executability v8::internal::PagedSpaceBase::executable_ [protected]
Definition at line 317 of file paged-spaces.h.
kCompactionMemoryWanted
const size_t v8::internal::PagedSpaceBase::kCompactionMemoryWanted = 500 * KB [static]
Definition at line 117 of file paged-spaces.h.
Referenced by v8::internal::CompactionSpace::RefillFreeList().
size_at_last_gc_
size_t v8::internal::PagedSpaceBase::size_at_last_gc_ = 0 [protected]
Definition at line 332 of file paged-spaces.h.
Referenced by v8::internal::PagedSpaceForNewSpace::AllocatedSinceLastGC(), and RefineAllocatedBytesAfterSweeping().
space_mutex_
base::Mutex v8::internal::PagedSpaceBase::space_mutex_ [mutable], [protected]
Definition at line 327 of file paged-spaces.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/paged-spaces.h
/mnt/V8SourceCode/src/heap/paged-spaces-inl.h
/mnt/V8SourceCode/src/heap/paged-spaces.cc