v8::internal::compiler::turboshaft::Typer::BranchRefinements Class Reference
#include <typer.h>
Public Types
using type_getter_t = std::function< Type(OpIndex)>
using type_refiner_t = std::function< void(OpIndex, const Type &)>
Public Member Functions
BranchRefinements (type_getter_t type_getter, type_refiner_t type_refiner)
void RefineTypes (const Operation &condition, bool then_branch, Zone *zone)
Private Member Functions
template<bool allow_implicit_word64_truncation>
Type RefineWord32Type (const Type &type, const Type &refinement, Zone *zone)
Private Attributes
type_getter_t type_getter_
type_refiner_t type_refiner_
Detailed Description
Definition at line 1552 of file typer.h.
Member Typedef Documentation
type_getter_t
using v8::internal::compiler::turboshaft::Typer::BranchRefinements::type_getter_t = std::function<Type(OpIndex)>
Definition at line 1555 of file typer.h.
type_refiner_t
using v8::internal::compiler::turboshaft::Typer::BranchRefinements::type_refiner_t = std::function<void(OpIndex, const Type&)>
Definition at line 1560 of file typer.h.
Constructor & Destructor Documentation
BranchRefinements()
v8::internal::compiler::turboshaft::Typer::BranchRefinements::BranchRefinements (type_getter_t type_getter, type_refiner_t type_refiner) [inline]
Definition at line 1562 of file typer.h.
        : type_getter_(type_getter), type_refiner_(type_refiner) {
      DCHECK(type_getter_);
      DCHECK(type_refiner_);
    }
References v8::internal::DCHECK(), type_getter_, and type_refiner_.
Member Function Documentation
RefineTypes()
void v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes (const Operation & condition, bool then_branch, Zone * zone)
Definition at line 9 of file typer.cc.
                                                                         {
  if (const ComparisonOp* comparison = condition.TryCast<ComparisonOp>()) {
    Type lhs = type_getter_(comparison->left());
    Type rhs = type_getter_(comparison->right());
    bool is_signed, is_less_than;
    switch (comparison->kind) {
      case ComparisonOp::Kind::kEqual:
        // TODO(nicohartmann@): Add support for equality.
        return;
      case ComparisonOp::Kind::kSignedLessThan:
        is_signed = true;
        is_less_than = true;
        break;
      case ComparisonOp::Kind::kSignedLessThanOrEqual:
        is_signed = true;
        is_less_than = false;
        break;
      case ComparisonOp::Kind::kUnsignedLessThan:
        is_signed = false;
        is_less_than = true;
        break;
      case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
        is_signed = false;
        is_less_than = false;
        break;
    }
    Type l_refined;
    Type r_refined;
    if (lhs.IsNone() || rhs.IsNone()) {
      type_refiner_(comparison->left(), Type::None());
      type_refiner_(comparison->right(), Type::None());
      return;
    } else if (lhs.IsAny() || rhs.IsAny()) {
      // If either side has any type, there is not much we can do.
      return;
    }
    switch (comparison->rep.value()) {
      case RegisterRepresentation::Word32(): {
        if (is_signed) {
          // TODO(nicohartmann@): Support signed comparison.
          return;
        }
        Word32Type l = Typer::TruncateWord32Input(lhs, true, zone).AsWord32();
        Word32Type r = Typer::TruncateWord32Input(rhs, true, zone).AsWord32();
        Type l_restrict, r_restrict;
        using OpTyper = WordOperationTyper<32>;
        if (is_less_than) {
          std::tie(l_restrict, r_restrict) =
              then_branch
                  ? OpTyper::RestrictionForUnsignedLessThan_True(l, r, zone)
                  : OpTyper::RestrictionForUnsignedLessThan_False(l, r, zone);
        } else {
          std::tie(l_restrict, r_restrict) =
              then_branch
                  ? OpTyper::RestrictionForUnsignedLessThanOrEqual_True(l, r,
                                                                        zone)
                  : OpTyper::RestrictionForUnsignedLessThanOrEqual_False(l, r,
                                                                         zone);
        }
        // Special handling for word32 restriction, because the inputs might
        // have been truncated from word64 implicitly.
        l_refined = RefineWord32Type<true>(lhs, l_restrict, zone);
        r_refined = RefineWord32Type<true>(rhs, r_restrict, zone);
        break;
      }
      case RegisterRepresentation::Float64(): {
        Float64Type l = lhs.AsFloat64();
        Float64Type r = rhs.AsFloat64();
        Type l_restrict, r_restrict;
        using OpTyper = FloatOperationTyper<64>;
        if (is_less_than) {
          std::tie(l_restrict, r_restrict) =
              then_branch ? OpTyper::RestrictionForLessThan_True(l, r, zone)
                          : OpTyper::RestrictionForLessThan_False(l, r, zone);
        } else {
          std::tie(l_restrict, r_restrict) =
              then_branch
                  ? OpTyper::RestrictionForLessThanOrEqual_True(l, r, zone)
                  : OpTyper::RestrictionForLessThanOrEqual_False(l, r, zone);
        }
        l_refined = l_restrict.IsNone() ? Type::None()
                                        : Float64Type::Intersect(
                                              l, l_restrict.AsFloat64(), zone);
        r_refined = r_restrict.IsNone() ? Type::None()
                                        : Float64Type::Intersect(
                                              r, r_restrict.AsFloat64(), zone);
        break;
      }
      default:
        return;
    }
    // In some cases, the refined type is not a subtype of the old type,
    // because it cannot be represented precisely. In this case we keep the
    // old type to be stable.
    if (l_refined.IsSubtypeOf(lhs)) {
      type_refiner_(comparison->left(), l_refined);
    }
    if (r_refined.IsSubtypeOf(rhs)) {
      type_refiner_(comparison->right(), r_refined);
    }
  }
}
References v8::internal::compiler::turboshaft::Type::AsFloat64(), v8::internal::compiler::turboshaft::Type::AsWord32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::is_signed(), v8::internal::compiler::turboshaft::Type::IsAny(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), v8::internal::compiler::turboshaft::Operation::TryCast(), type_getter_, type_refiner_, and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
RefineWord32Type()
template<bool allow_implicit_word64_truncation>
Type v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineWord32Type (const Type & type, const Type & refinement, Zone * zone) [inline], [private]
Definition at line 1572 of file typer.h.
                                      {
      // If refinement is Type::None(), the operation/branch is unreachable.
      if (refinement.IsNone()) return Type::None();
      DCHECK(refinement.IsWord32());
      if constexpr (allow_implicit_word64_truncation) {
        // Turboshaft allows implicit trunction of Word64 values to Word32. When
        // an operation on Word32 representation computes a refinement type,
        // this is going to be a Type::Word32() even if the actual {type} was
        // Word64 before truncation. To correctly refine this type, we need to
        // extend the {refinement} to Word64 such that it reflects the
        // corresponding values in the original type (before truncation) before
        // we intersect.
        if (type.IsWord64()) {
          return Word64Type::Intersect(
              type.AsWord64(),
              Typer::ExtendWord32ToWord64(refinement.AsWord32(), zone),
              Type::ResolutionMode::kOverApproximate, zone);
        }
      }
      // We limit the values of {type} to those in {refinement}.
      return Word32Type::Intersect(type.AsWord32(), refinement.AsWord32(),
                                   Type::ResolutionMode::kOverApproximate,
                                   zone);
    }
References v8::internal::compiler::turboshaft::Type::AsWord32(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Typer::ExtendWord32ToWord64(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::IsWord32(), v8::internal::compiler::turboshaft::Type::kOverApproximate, v8::internal::compiler::turboshaft::Type::None(), and v8::internal::tracing::type.
Member Data Documentation
type_getter_
type_getter_t v8::internal::compiler::turboshaft::Typer::BranchRefinements::type_getter_ [private]
Definition at line 1598 of file typer.h.
Referenced by BranchRefinements(), and RefineTypes().
type_refiner_
type_refiner_t v8::internal::compiler::turboshaft::Typer::BranchRefinements::type_refiner_ [private]
Definition at line 1599 of file typer.h.
Referenced by BranchRefinements(), and RefineTypes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/typer.h
/mnt/V8SourceCode/src/compiler/turboshaft/typer.cc