v8::internal::ToDirectStringAssembler Class Reference
#include <code-stub-assembler.h>
Public Types
enum Flag { kDontUnpackSlicedStrings = 1 << 0
 }
using Flags = base::Flags< Flag >
Public Member Functions
ToDirectStringAssembler (compiler::CodeAssemblerState *state, TNode< String > string, Flags flags=Flags())
TNode< String > TryToDirect (Label *if_bailout)
TNode< String > ToDirect ()
TNode< RawPtrT > PointerToData (Label *if_bailout)
TNode< RawPtrT > PointerToString (Label *if_bailout)
TNode< BoolT > IsOneByte ()
TNode< String > string ()
TNode< IntPtrT > offset ()
TNode< Word32T > is_external ()
Private Types
enum StringPointerKind { PTR_TO_DATA
, PTR_TO_STRING
 }
Private Member Functions
TNode< RawPtrT > TryToSequential (StringPointerKind ptr_kind, Label *if_bailout)
Private Attributes
TVariable< String > var_string_
TVariable< Int32T > var_instance_type_
TVariable< IntPtrT > var_offset_
TVariable< Word32T > var_is_external_
const Flags flags_
Additional Inherited Members
Detailed Description
Definition at line 4930 of file code-stub-assembler.h.
Member Typedef Documentation
Flags
using v8::internal::ToDirectStringAssembler::Flags = base::Flags<Flag>
Definition at line 4938 of file code-stub-assembler.h.
Member Enumeration Documentation
Flag
enum v8::internal::ToDirectStringAssembler::Flag
Enumerator
kDontUnpackSlicedStrings
Definition at line 4935 of file code-stub-assembler.h.
            {
    kDontUnpackSlicedStrings = 1 << 0,
  };
StringPointerKind
enum v8::internal::ToDirectStringAssembler::StringPointerKind [private]
Enumerator
PTR_TO_DATA
PTR_TO_STRING
Definition at line 4932 of file code-stub-assembler.h.
{ PTR_TO_DATA, PTR_TO_STRING };
Constructor & Destructor Documentation
ToDirectStringAssembler()
v8::internal::ToDirectStringAssembler::ToDirectStringAssembler (compiler::CodeAssemblerState * state, TNode< String > string, Flags flags = Flags())
Definition at line 8928 of file code-stub-assembler.cc.
    : CodeStubAssembler(state),
      var_string_(string, this),
#if V8_STATIC_ROOTS_BOOL
      var_map_(LoadMap(string), this),
#else
      var_instance_type_(LoadInstanceType(string), this),
#endif
      var_offset_(IntPtrConstant(0), this),
      var_is_external_(Int32Constant(0), this),
      flags_(flags) {
}
Member Function Documentation
is_external()
TNode<Word32T> v8::internal::ToDirectStringAssembler::is_external () [inline]
Definition at line 4969 of file code-stub-assembler.h.
{ return var_is_external_.value(); }
References var_is_external_.
Referenced by v8::internal::StringBuiltinsAssembler::SubString(), and TryToSequential().
IsOneByte()
TNode< BoolT > v8::internal::ToDirectStringAssembler::IsOneByte ()
Definition at line 9118 of file code-stub-assembler.cc.
                                                {
#if V8_STATIC_ROOTS_BOOL
  return IsOneByteStringMap(var_map_.value());
#else
  return IsOneByteStringInstanceType(var_instance_type_.value());
#endif
}
References v8::internal::CodeStubAssembler::IsOneByteStringInstanceType(), v8::internal::CodeStubAssembler::IsOneByteStringMap(), and var_instance_type_.
Referenced by v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::StringBuiltinsAssembler::SubString(), and v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl().
offset()
TNode<IntPtrT> v8::internal::ToDirectStringAssembler::offset () [inline]
Definition at line 4968 of file code-stub-assembler.h.
{ return var_offset_.value(); }
References var_offset_.
Referenced by v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::StringToArray(), and v8::internal::StringBuiltinsAssembler::SubString().
PointerToData()
TNode<RawPtrT> v8::internal::ToDirectStringAssembler::PointerToData (Label * if_bailout) [inline]
Definition at line 4955 of file code-stub-assembler.h.
                                                  {
    return TryToSequential(PTR_TO_DATA, if_bailout);
  }
References PTR_TO_DATA, and TryToSequential().
Referenced by v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::CodeStubAssembler::TaggedToDirectString(), and v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl().
PointerToString()
TNode<RawPtrT> v8::internal::ToDirectStringAssembler::PointerToString (Label * if_bailout) [inline]
Definition at line 4961 of file code-stub-assembler.h.
                                                    {
    return TryToSequential(PTR_TO_STRING, if_bailout);
  }
References PTR_TO_STRING, and TryToSequential().
Referenced by v8::internal::StringBuiltinsAssembler::SubString().
string()
TNode<String> v8::internal::ToDirectStringAssembler::string () [inline]
Definition at line 4967 of file code-stub-assembler.h.
{ return var_string_.value(); }
References var_string_.
Referenced by v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl().
ToDirect()
TNode< String > v8::internal::ToDirectStringAssembler::ToDirect ()
Definition at line 9092 of file code-stub-assembler.cc.
                                                {
  Label flatten_in_runtime(this, Label::kDeferred),
      unreachable(this, Label::kDeferred), out(this);
  TryToDirect(&flatten_in_runtime);
  Goto(&out);
  BIND(&flatten_in_runtime);
  var_string_ = CAST(CallRuntime(Runtime::kFlattenString, NoContextConstant(),
                                 var_string_.value()));
#if V8_STATIC_ROOTS_BOOL
  var_map_ = LoadMap(var_string_.value());
#else
  var_instance_type_ = LoadInstanceType(var_string_.value());
#endif
  TryToDirect(&unreachable);
  Goto(&out);
  BIND(&unreachable);
  Unreachable();
  BIND(&out);
  return var_string_.value();
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::NoContextConstant(), TryToDirect(), v8::internal::compiler::CodeAssembler::Unreachable(), var_instance_type_, and var_string_.
Referenced by v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal().
TryToDirect()
TNode< String > v8::internal::ToDirectStringAssembler::TryToDirect (Label * if_bailout)
Definition at line 8942 of file code-stub-assembler.cc.
                                                                    {
  Label dispatch(this, {&var_string_, &var_offset_,
#if V8_STATIC_ROOTS_BOOL
                        &var_map_
#else
                        &var_instance_type_
#endif
                       });
  Label if_iscons(this);
  Label if_isexternal(this);
  Label if_issliced(this);
  Label if_isthin(this);
  Label out(this);
#if V8_STATIC_ROOTS_BOOL
  // The seq string check is in the dispatch.
  Goto(&dispatch);
#else
  Branch(IsSequentialStringInstanceType(var_instance_type_.value()), &out,
         &dispatch);
#endif
  // Dispatch based on string representation.
  BIND(&dispatch);
  {
#if V8_STATIC_ROOTS_BOOL
    TNode<Int32T> map_bits =
        TruncateIntPtrToInt32(BitcastTaggedToWord(var_map_.value()));
    using StringTypeRange = InstanceTypeChecker::kUniqueMapRangeOfStringType;
    // Check the string map ranges in dense increasing order, to avoid needing
    // to subtract away the lower bound. Do these couple of range checks instead
    // of a switch, since we can make them all single dense compares.
    static_assert(StringTypeRange::kSeqString.first == 0);
    GotoIf(Uint32LessThanOrEqual(
               map_bits, Int32Constant(StringTypeRange::kSeqString.second)),
           &out, GotoHint::kLabel);
    static_assert(StringTypeRange::kSeqString.second + Map::kSize ==
                  StringTypeRange::kExternalString.first);
    GotoIf(
        Uint32LessThanOrEqual(
            map_bits, Int32Constant(StringTypeRange::kExternalString.second)),
        &if_isexternal);
    static_assert(StringTypeRange::kExternalString.second + Map::kSize ==
                  StringTypeRange::kConsString.first);
    GotoIf(Uint32LessThanOrEqual(
               map_bits, Int32Constant(StringTypeRange::kConsString.second)),
           &if_iscons);
    static_assert(StringTypeRange::kConsString.second + Map::kSize ==
                  StringTypeRange::kSlicedString.first);
    GotoIf(Uint32LessThanOrEqual(
               map_bits, Int32Constant(StringTypeRange::kSlicedString.second)),
           &if_issliced);
    static_assert(StringTypeRange::kSlicedString.second + Map::kSize ==
                  StringTypeRange::kThinString.first);
    // No need to check for thin strings, they're the last string map.
    static_assert(StringTypeRange::kThinString.second ==
                  InstanceTypeChecker::kStringMapUpperBound);
    Goto(&if_isthin);
#else
    int32_t values[] = {
        kSeqStringTag, kConsStringTag, kExternalStringTag,
        kSlicedStringTag, kThinStringTag,
    };
    Label* labels[] = {
        &out, &if_iscons, &if_isexternal, &if_issliced, &if_isthin,
    };
    static_assert(arraysize(values) == arraysize(labels));
    const TNode<Int32T> representation = Word32And(
        var_instance_type_.value(), Int32Constant(kStringRepresentationMask));
    Switch(representation, if_bailout, values, labels, arraysize(values));
#endif
  }
  // Cons string. Check whether it is flat, then fetch first part.
  // Flat cons strings have an empty second part.
  BIND(&if_iscons);
  {
    const TNode<String> string = var_string_.value();
    GotoIfNot(IsEmptyString(LoadObjectField<String>(
                  string, offsetof(ConsString, second_))),
              if_bailout, GotoHint::kFallthrough);
    const TNode<String> lhs =
        LoadObjectField<String>(string, offsetof(ConsString, first_));
    var_string_ = lhs;
#if V8_STATIC_ROOTS_BOOL
    var_map_ = LoadMap(lhs);
#else
    var_instance_type_ = LoadInstanceType(lhs);
#endif
    Goto(&dispatch);
  }
  // Sliced string. Fetch parent and correct start index by offset.
  BIND(&if_issliced);
  {
    if (!v8_flags.string_slices || (flags_ & kDontUnpackSlicedStrings)) {
      Goto(if_bailout);
    } else {
      const TNode<String> string = var_string_.value();
      const TNode<IntPtrT> sliced_offset = LoadAndUntagPositiveSmiObjectField(
          string, offsetof(SlicedString, offset_));
      var_offset_ = IntPtrAdd(var_offset_.value(), sliced_offset);
      const TNode<String> parent =
          LoadObjectField<String>(string, offsetof(SlicedString, parent_));
      var_string_ = parent;
#if V8_STATIC_ROOTS_BOOL
      var_map_ = LoadMap(parent);
#else
      var_instance_type_ = LoadInstanceType(parent);
#endif
      Goto(&dispatch);
    }
  }
  // Thin string. Fetch the actual string.
  BIND(&if_isthin);
  {
    const TNode<String> string = var_string_.value();
    const TNode<String> actual_string =
        LoadObjectField<String>(string, offsetof(ThinString, actual_));
    var_string_ = actual_string;
#if V8_STATIC_ROOTS_BOOL
    var_map_ = LoadMap(actual_string);
#else
    var_instance_type_ = LoadInstanceType(actual_string);
#endif
    Goto(&dispatch);
  }
  // External string.
  BIND(&if_isexternal);
  var_is_external_ = Int32Constant(1);
  Goto(&out);
  BIND(&out);
  return var_string_.value();
}
References arraysize, v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::Branch(), flags_, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::CodeStubAssembler::IsSequentialStringInstanceType(), v8::internal::kConsStringTag, kDontUnpackSlicedStrings, v8::internal::kExternalStringTag, v8::internal::kFallthrough, v8::internal::kLabel, v8::internal::kSeqStringTag, v8::internal::kSlicedStringTag, v8::internal::kStringRepresentationMask, v8::internal::kThinStringTag, v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::compiler::CodeAssembler::Switch(), v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), v8::internal::v8_flags, var_instance_type_, var_is_external_, var_offset_, var_string_, and v8::internal::compiler::CodeAssembler::Word32And().
Referenced by v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::TaggedToDirectString(), ToDirect(), and v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl().
TryToSequential()
TNode< RawPtrT > v8::internal::ToDirectStringAssembler::TryToSequential (StringPointerKind ptr_kind, Label * if_bailout) [private]
Definition at line 9126 of file code-stub-assembler.cc.
                                                   {
  CHECK(ptr_kind == PTR_TO_DATA || ptr_kind == PTR_TO_STRING);
  TVARIABLE(RawPtrT, var_result);
  Label out(this), if_issequential(this), if_isexternal(this, Label::kDeferred);
  Branch(is_external(), &if_isexternal, &if_issequential);
  BIND(&if_issequential);
  {
    static_assert(OFFSET_OF_DATA_START(SeqOneByteString) ==
                  OFFSET_OF_DATA_START(SeqTwoByteString));
    TNode<RawPtrT> result =
        ReinterpretCast<RawPtrT>(BitcastTaggedToWord(var_string_.value()));
    if (ptr_kind == PTR_TO_DATA) {
      result = RawPtrAdd(result,
                         IntPtrConstant(OFFSET_OF_DATA_START(SeqOneByteString) -
                                        kHeapObjectTag));
    }
    var_result = result;
    Goto(&out);
  }
  BIND(&if_isexternal);
  {
#if V8_STATIC_ROOTS_BOOL
    GotoIf(IsUncachedExternalStringMap(var_map_.value()), if_bailout);
#else
    GotoIf(IsUncachedExternalStringInstanceType(var_instance_type_.value()),
           if_bailout);
#endif
    TNode<String> string = var_string_.value();
    TNode<RawPtrT> result = LoadExternalStringResourceDataPtr(CAST(string));
    if (ptr_kind == PTR_TO_STRING) {
      result = RawPtrSub(result,
                         IntPtrConstant(OFFSET_OF_DATA_START(SeqOneByteString) -
                                        kHeapObjectTag));
    }
    var_result = result;
    Goto(&out);
  }
  BIND(&out);
  return var_result.value();
}
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::Branch(), CAST, CHECK, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), is_external(), v8::internal::CodeStubAssembler::IsUncachedExternalStringInstanceType(), v8::internal::CodeStubAssembler::IsUncachedExternalStringMap(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::kHeapObjectTag, v8::internal::CodeStubAssembler::LoadExternalStringResourceDataPtr(), OFFSET_OF_DATA_START, PTR_TO_DATA, PTR_TO_STRING, v8::internal::compiler::CodeAssembler::RawPtrAdd(), v8::internal::compiler::CodeAssembler::RawPtrSub(), v8::base::internal::result, var_instance_type_, and var_string_.
Referenced by PointerToData(), and PointerToString().
Member Data Documentation
flags_
const Flags v8::internal::ToDirectStringAssembler::flags_ [private]
Definition at line 4984 of file code-stub-assembler.h.
Referenced by TryToDirect().
var_instance_type_
TVariable<Int32T> v8::internal::ToDirectStringAssembler::var_instance_type_ [private]
Definition at line 4978 of file code-stub-assembler.h.
Referenced by IsOneByte(), ToDirect(), TryToDirect(), and TryToSequential().
var_is_external_
TVariable<Word32T> v8::internal::ToDirectStringAssembler::var_is_external_ [private]
Definition at line 4982 of file code-stub-assembler.h.
Referenced by is_external(), and TryToDirect().
var_offset_
TVariable<IntPtrT> v8::internal::ToDirectStringAssembler::var_offset_ [private]
Definition at line 4981 of file code-stub-assembler.h.
Referenced by offset(), and TryToDirect().
var_string_
TVariable<String> v8::internal::ToDirectStringAssembler::var_string_ [private]
Definition at line 4974 of file code-stub-assembler.h.
Referenced by string(), ToDirect(), TryToDirect(), and TryToSequential().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/code-stub-assembler.h
/mnt/V8SourceCode/src/codegen/code-stub-assembler.cc