v8::internal::maglev::Uint32Constant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = Register
Public Member Functions
Uint32Constant (uint64_t bitfield, uint32_t value)
uint32_t value () const
bool ToBoolean (LocalIsolate *local_isolate) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
DirectHandle< Object > DoReify (LocalIsolate *isolate) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::Uint32()
Private Types
using Base = FixedInputValueNodeT< 0, Uint32Constant >
Private Attributes
const uint32_t value_
Additional Inherited Members
Detailed Description
Definition at line 3901 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Uint32Constant::Base = FixedInputValueNodeT<0, Uint32Constant> [private]
Definition at line 3902 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::Uint32Constant::OutputRegister = Register
Definition at line 3905 of file maglev-ir.h.
Constructor & Destructor Documentation
Uint32Constant()
v8::internal::maglev::Uint32Constant::Uint32Constant (uint64_t bitfield, uint32_t value) [inline], [explicit]
Definition at line 3907 of file maglev-ir.h.
      : Base(bitfield), value_(value) {}
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::Uint32Constant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
DirectHandle< Object > v8::internal::maglev::Uint32Constant::DoReify (LocalIsolate * isolate) const
Definition at line 1219 of file maglev-ir.cc.
                                                                        {
  return isolate->factory()->NewNumberFromUint<AllocationType::kOld>(value());
}
References v8::internal::LocalIsolate::factory(), v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), and value().
GenerateCode()
void v8::internal::maglev::Uint32Constant::GenerateCode (MaglevAssembler * , const ProcessingState &)
PrintParams()
void v8::internal::maglev::Uint32Constant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7899 of file maglev-ir.cc.
                                                                            {
  os << "(" << value() << ")";
}
References value().
SetValueLocationConstraints()
void v8::internal::maglev::Uint32Constant::SetValueLocationConstraints ()
ToBoolean()
bool v8::internal::maglev::Uint32Constant::ToBoolean (LocalIsolate * local_isolate) const [inline]
Definition at line 3914 of file maglev-ir.h.
{ return value_ != 0; }
References value_.
value()
uint32_t v8::internal::maglev::Uint32Constant::value () const [inline]
Definition at line 3912 of file maglev-ir.h.
{ return value_; }
References value_.
Referenced by DoReify(), PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kProperties
constexpr OpProperties v8::internal::maglev::Uint32Constant::kProperties = OpProperties::Uint32() [static], [constexpr]
Definition at line 3910 of file maglev-ir.h.
value_
const uint32_t v8::internal::maglev::Uint32Constant::value_ [private]
Definition at line 3924 of file maglev-ir.h.
Referenced by ToBoolean(), and value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc