v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector Class Reference
Public Member Functions
LocalBlocklistsCollector (Isolate *isolate, Handle< Script > script, Handle< Context > context, DeclarationScope *closure_scope)
void CollectAndStore ()
Private Member Functions
void InitializeWithClosureScope ()
void AdvanceToNextNonHiddenScope ()
void CollectCurrentLocalsIntoBlocklists ()
DirectHandle< ScopeInfo > FindScopeInfoForScope (Scope *scope) const
void StoreFunctionBlocklists (DirectHandle< ScopeInfo > outer_scope_info)
Private Attributes
Isolate * isolate_
Handle< Script > script_
Handle< Context > context_
Scope * scope_
DeclarationScope * closure_scope_
Handle< StringSet > context_blocklist_
std::map< Scope *, IndirectHandle< StringSet > > function_blocklists_
Detailed Description
Definition at line 1241 of file debug-scopes.cc.
Constructor & Destructor Documentation
LocalBlocklistsCollector()
v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::LocalBlocklistsCollector (Isolate * isolate, Handle< Script > script, Handle< Context > context, DeclarationScope * closure_scope)
Definition at line 1265 of file debug-scopes.cc.
    : isolate_(isolate),
      script_(script),
      context_(context),
      scope_(closure_scope),
      closure_scope_(closure_scope) {}
Member Function Documentation
AdvanceToNextNonHiddenScope()
void v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::AdvanceToNextNonHiddenScope () [private]
Definition at line 1280 of file debug-scopes.cc.
                                                           {
  DCHECK(scope_ && scope_->outer_scope());
  do {
    scope_ = scope_->outer_scope();
    CHECK(scope_);
  } while (scope_->is_hidden());
}
References CHECK, v8::internal::DCHECK(), v8::internal::Scope::is_hidden(), v8::internal::Scope::outer_scope(), and scope_.
Referenced by CollectAndStore().
CollectAndStore()
void v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectAndStore ()
Definition at line 1334 of file debug-scopes.cc.
                                               {
  InitializeWithClosureScope();
  while (scope_->outer_scope() && !IsNativeContext(*context_)) {
    AdvanceToNextNonHiddenScope();
    // 1. Add all stack-allocated variables of `scope_` to the various lists.
    CollectCurrentLocalsIntoBlocklists();
    // 2. If the current scope requires a context then all the blocklists "stop"
    // here and we store them. Next, advance the current context so
    // `context_` and `scope_` match again.
    if (scope_->NeedsContext()) {
      if (!context_blocklist_.is_null()) {
        // Only store the block list and advance the context if the
        // context_blocklist is set. This handles the case when we start on
        // a closure scope that doesn't require a context. In that case
        // `context_` is already the right context for `scope_` so we don't
        // need to advance `context_`.
        isolate_->LocalsBlockListCacheSet(
            direct_handle(context_->scope_info(), isolate_),
            direct_handle(context_->previous()->scope_info(), isolate_),
            context_blocklist_);
        context_ = handle(context_->previous(), isolate_);
      }
      StoreFunctionBlocklists(direct_handle(context_->scope_info(), isolate_));
      context_blocklist_ = StringSet::New(isolate_);
      function_blocklists_.clear();
    } else if (scope_->is_function_scope()) {
      // 3. If `scope` is a function scope with an SFI, start recording
      // locals for its ScopeInfo.
      CHECK(!scope_->NeedsContext());
      function_blocklists_.emplace(scope_, StringSet::New(isolate_));
    }
  }
  // In case we don't have any outer scopes we still need to record the empty
  // block list for the paused function to prevent future re-parses.
  StoreFunctionBlocklists(direct_handle(context_->scope_info(), isolate_));
}
References AdvanceToNextNonHiddenScope(), CHECK, CollectCurrentLocalsIntoBlocklists(), context_, context_blocklist_, v8::internal::direct_handle(), function_blocklists_, v8::internal::handle(), InitializeWithClosureScope(), v8::internal::Scope::is_function_scope(), isolate_, v8::internal::Isolate::LocalsBlockListCacheSet(), v8::internal::Scope::NeedsContext(), v8::internal::StringSet::New(), v8::internal::Scope::outer_scope(), scope_, and StoreFunctionBlocklists().
CollectCurrentLocalsIntoBlocklists()
void v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectCurrentLocalsIntoBlocklists () [private]
Definition at line 1288 of file debug-scopes.cc.
                                                                  {
  for (Variable* var : *scope_->locals()) {
    if (var->location() == VariableLocation::PARAMETER ||
        var->location() == VariableLocation::LOCAL) {
      if (!context_blocklist_.is_null()) {
        context_blocklist_ =
            StringSet::Add(isolate_, context_blocklist_, var->name());
      }
      for (auto& pair : function_blocklists_) {
        pair.second = StringSet::Add(isolate_, pair.second, var->name());
      }
    }
  }
}
References v8::internal::StringSet::Add(), context_blocklist_, function_blocklists_, isolate_, v8::internal::LOCAL, v8::internal::Scope::locals(), v8::internal::PARAMETER, and scope_.
Referenced by CollectAndStore().
FindScopeInfoForScope()
DirectHandle< ScopeInfo > v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::FindScopeInfoForScope (Scope * scope) const [private]
Definition at line 1303 of file debug-scopes.cc.
                        {
  DisallowGarbageCollection no_gc;
  SharedFunctionInfo::ScriptIterator iterator(isolate_, *script_);
  for (Tagged<SharedFunctionInfo> info = iterator.Next(); !info.is_null();
       info = iterator.Next()) {
    Tagged<ScopeInfo> scope_info = info->scope_info();
    if (info->is_compiled() && !scope_info.is_null() &&
        scope->start_position() == info->StartPosition() &&
        scope->end_position() == info->EndPosition() &&
        scope->scope_type() == scope_info->scope_type()) {
      return direct_handle(scope_info, isolate_);
    }
  }
  return DirectHandle<ScopeInfo>();
}
References v8::internal::direct_handle(), v8::internal::Scope::end_position(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, v8::internal::SharedFunctionInfo::ScriptIterator::Next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Scope::scope_type(), script_, and v8::internal::Scope::start_position().
Referenced by StoreFunctionBlocklists().
InitializeWithClosureScope()
void v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::InitializeWithClosureScope () [private]
Definition at line 1274 of file debug-scopes.cc.
                                                          {
  CHECK(scope_->is_declaration_scope());
  function_blocklists_.emplace(scope_, StringSet::New(isolate_));
  if (scope_->NeedsContext()) context_blocklist_ = StringSet::New(isolate_);
}
References CHECK, context_blocklist_, function_blocklists_, v8::internal::Scope::is_declaration_scope(), isolate_, v8::internal::Scope::NeedsContext(), v8::internal::StringSet::New(), and scope_.
Referenced by CollectAndStore().
StoreFunctionBlocklists()
void v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::StoreFunctionBlocklists (DirectHandle< ScopeInfo > outer_scope_info) [private]
Definition at line 1320 of file debug-scopes.cc.
                                              {
  for (const auto& pair : function_blocklists_) {
    DirectHandle<ScopeInfo> scope_info = FindScopeInfoForScope(pair.first);
    // If we don't find a ScopeInfo it's not tragic. It means we'll do
    // a full-reparse in case we pause in that function in the future.
    // The only ScopeInfo that MUST be found is for the closure_scope_.
    CHECK_IMPLIES(pair.first == closure_scope_, !scope_info.is_null());
    if (scope_info.is_null()) continue;
    isolate_->LocalsBlockListCacheSet(scope_info, outer_scope_info,
                                      pair.second);
  }
}
References CHECK_IMPLIES, closure_scope_, FindScopeInfoForScope(), function_blocklists_, v8::internal::DirectHandle< T >::is_null(), isolate_, and v8::internal::Isolate::LocalsBlockListCacheSet().
Referenced by CollectAndStore().
Member Data Documentation
closure_scope_
DeclarationScope* v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::closure_scope_ [private]
Definition at line 1259 of file debug-scopes.cc.
Referenced by StoreFunctionBlocklists().
context_
Handle<Context> v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::context_ [private]
Definition at line 1257 of file debug-scopes.cc.
Referenced by CollectAndStore().
context_blocklist_
Handle<StringSet> v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::context_blocklist_ [private]
Definition at line 1261 of file debug-scopes.cc.
Referenced by CollectAndStore(), CollectCurrentLocalsIntoBlocklists(), and InitializeWithClosureScope().
function_blocklists_
std::map<Scope*, IndirectHandle<StringSet> > v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::function_blocklists_ [private]
Definition at line 1262 of file debug-scopes.cc.
Referenced by CollectAndStore(), CollectCurrentLocalsIntoBlocklists(), InitializeWithClosureScope(), and StoreFunctionBlocklists().
isolate_
Isolate* v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::isolate_ [private]
Definition at line 1255 of file debug-scopes.cc.
Referenced by CollectAndStore(), CollectCurrentLocalsIntoBlocklists(), FindScopeInfoForScope(), InitializeWithClosureScope(), and StoreFunctionBlocklists().
scope_
Scope* v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::scope_ [private]
Definition at line 1258 of file debug-scopes.cc.
Referenced by AdvanceToNextNonHiddenScope(), CollectAndStore(), CollectCurrentLocalsIntoBlocklists(), and InitializeWithClosureScope().
script_
Handle<Script> v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::script_ [private]
Definition at line 1256 of file debug-scopes.cc.
Referenced by FindScopeInfoForScope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-scopes.cc