v8::internal::UnlinkWeakNextScope Class Reference
Public Member Functions
UnlinkWeakNextScope (Heap *heap, Tagged< HeapObject > object)
~UnlinkWeakNextScope ()
Private Attributes
Tagged< AllocationSiteWithWeakNext > object_
Tagged< UnionOf< Smi, Undefined, AllocationSiteWithWeakNext > > next_
Detailed Description
Definition at line 770 of file serializer.cc.
Constructor & Destructor Documentation
UnlinkWeakNextScope()
v8::internal::UnlinkWeakNextScope::UnlinkWeakNextScope (Heap * heap, Tagged< HeapObject > object) [inline], [explicit]
Definition at line 772 of file serializer.cc.
                                                                      {
    Isolate* isolate = heap->isolate();
    if (TryCast<AllocationSiteWithWeakNext>(object, &object_)) {
      next_ = object_->weak_next();
      object_->set_weak_next(ReadOnlyRoots(isolate).undefined_value());
    }
  }
References v8::internal::Serializer::isolate().
 UnlinkWeakNextScope()
v8::internal::UnlinkWeakNextScope::~UnlinkWeakNextScope () [inline]
Definition at line 780 of file serializer.cc.
                         {
    if (next_ == Smi::zero()) return;
    object_->set_weak_next(
        Cast<UnionOf<Undefined, AllocationSiteWithWeakNext>>(next_),
        UPDATE_WRITE_BARRIER);
  }
References v8::internal::Cast(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::Smi::zero().
Member Data Documentation
next_
Tagged<UnionOf<Smi, Undefined, AllocationSiteWithWeakNext> > v8::internal::UnlinkWeakNextScope::next_ [private]
Initial value:
=
      Smi::zero()
Definition at line 789 of file serializer.cc.
object_
Tagged<AllocationSiteWithWeakNext> v8::internal::UnlinkWeakNextScope::object_ [private]
Definition at line 788 of file serializer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/serializer.cc