v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler Class Reference
Classes
struct AsyncFromSyncIteratorCloseSyncAndRethrowContext
Public Types
enum CloseOnRejectionOption { kDoNotCloseOnRejection
, kCloseOnRejection
 }
using UndefinedMethodHandler = std::function< void(const TNode< NativeContext > native_context, const TNode< JSPromise > promise, const TNode< JSReceiver > sync_iterator, Label *if_exception)>
using SyncIteratorNodeGenerator = std::function< TNode< Object >(TNode< JSReceiver >)>
Public Member Functions
AsyncFromSyncBuiltinsAssembler (compiler::CodeAssemblerState *state)
void Generate_AsyncFromSyncIteratorMethod (CodeStubArguments *args, const TNode< Context > context, const TNode< Object > iterator, const TNode< Object > sent_value, const SyncIteratorNodeGenerator &get_method, const UndefinedMethodHandler &if_method_undefined, const char *operation_name, CloseOnRejectionOption close_on_rejection, Label::Type reject_label_type=Label::kDeferred, std::optional< TNode< Object >> initial_exception_value=std::nullopt)
void Generate_AsyncFromSyncIteratorMethod (CodeStubArguments *args, const TNode< Context > context, const TNode< Object > iterator, const TNode< Object > sent_value, Handle< String > name, const UndefinedMethodHandler &if_method_undefined, const char *operation_name, CloseOnRejectionOption close_on_rejection, Label::Type reject_label_type=Label::kDeferred, std::optional< TNode< Object >> initial_exception_value=std::nullopt)
std::pair< TNode< Object >, TNode< Boolean > > LoadIteratorResult (const TNode< Context > context, const TNode< NativeContext > native_context, const TNode< JSAny > iter_result, Label *if_exception, TVariable< Object > *var_exception)
TNode< JSFunction > CreateAsyncFromSyncIteratorCloseSyncAndRethrowClosure (TNode< NativeContext > native_context, TNode< JSReceiver > sync_iterator)
TNode< Context > AllocateAsyncFromSyncIteratorCloseSyncAndRethrowContext (TNode< NativeContext > native_context, TNode< JSReceiver > sync_iterator)
Static Public Attributes
static const int kValueOrReasonArg = 0
Additional Inherited Members
Detailed Description
Definition at line 19 of file builtins-async-iterator-gen.cc.
Member Typedef Documentation
SyncIteratorNodeGenerator
using v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::SyncIteratorNodeGenerator = std::function<TNode<Object>(TNode<JSReceiver>)>
Definition at line 31 of file builtins-async-iterator-gen.cc.
UndefinedMethodHandler
using v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::UndefinedMethodHandler = std::function<void(const TNode<NativeContext> native_context, const TNode<JSPromise> promise, const TNode<JSReceiver> sync_iterator, Label* if_exception)>
Definition at line 28 of file builtins-async-iterator-gen.cc.
Member Enumeration Documentation
CloseOnRejectionOption
enum v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::CloseOnRejectionOption
Enumerator
kDoNotCloseOnRejection
kCloseOnRejection
Definition at line 33 of file builtins-async-iterator-gen.cc.
{ kDoNotCloseOnRejection, kCloseOnRejection };
Constructor & Destructor Documentation
AsyncFromSyncBuiltinsAssembler()
v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::AsyncFromSyncBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 25 of file builtins-async-iterator-gen.cc.
      : AsyncBuiltinsAssembler(state) {}
Member Function Documentation
AllocateAsyncFromSyncIteratorCloseSyncAndRethrowContext()
TNode< Context > v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::AllocateAsyncFromSyncIteratorCloseSyncAndRethrowContext (TNode< NativeContext > native_context, TNode< JSReceiver > sync_iterator)
Definition at line 310 of file builtins-async-iterator-gen.cc.
                                                                              {
  TNode<Context> context = AllocateSyntheticFunctionContext(
      native_context, AsyncFromSyncIteratorCloseSyncAndRethrowContext::kLength);
  StoreContextElementNoWriteBarrier(
      context, AsyncFromSyncIteratorCloseSyncAndRethrowContext::kSyncIterator,
      sync_iterator);
  return context;
}
References v8::internal::native_context.
CreateAsyncFromSyncIteratorCloseSyncAndRethrowClosure()
TNode< JSFunction > v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::CreateAsyncFromSyncIteratorCloseSyncAndRethrowClosure (TNode< NativeContext > native_context, TNode< JSReceiver > sync_iterator)
Definition at line 299 of file builtins-async-iterator-gen.cc.
                                                                              {
  const TNode<Context> closure_context =
      AllocateAsyncFromSyncIteratorCloseSyncAndRethrowContext(native_context,
                                                              sync_iterator);
  return AllocateRootFunctionWithContext(
      RootIndex::kAsyncFromSyncIteratorCloseSyncAndRethrowSharedFun,
      closure_context, native_context);
}
References v8::internal::native_context.
Generate_AsyncFromSyncIteratorMethod() [1/2]
void v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::Generate_AsyncFromSyncIteratorMethod (CodeStubArguments * args, const TNode< Context > context, const TNode< Object > iterator, const TNode< Object > sent_value, const SyncIteratorNodeGenerator & get_method, const UndefinedMethodHandler & if_method_undefined, const char * operation_name, CloseOnRejectionOption close_on_rejection, Label::Type reject_label_type = Label::kDeferred, std::optional< TNode< Object >> initial_exception_value = std::nullopt)
Definition at line 88 of file builtins-async-iterator-gen.cc.
                                                        {
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  const TNode<JSPromise> promise = NewJSPromise(context);
  TVARIABLE(
      Object, var_exception,
      initial_exception_value ? *initial_exception_value : UndefinedConstant());
  Label maybe_close_sync_then_reject_promise(this, reject_label_type);
  Label maybe_close_sync_if_not_done_then_reject_promise(this,
                                                         reject_label_type);
  // At this time %AsyncFromSyncIterator% does not escape to user code, and so
  // cannot be called with an incompatible receiver.
  CSA_CHECK(this,
            HasInstanceType(CAST(iterator), JS_ASYNC_FROM_SYNC_ITERATOR_TYPE));
  TNode<JSAsyncFromSyncIterator> async_iterator = CAST(iterator);
  const TNode<JSReceiver> sync_iterator = LoadObjectField<JSReceiver>(
      async_iterator, JSAsyncFromSyncIterator::kSyncIteratorOffset);
  TNode<Object> method = get_method(sync_iterator);
  if (if_method_undefined) {
    Label if_isnotundefined(this);
    GotoIfNot(IsNullOrUndefined(method), &if_isnotundefined);
    if_method_undefined(native_context, promise, sync_iterator,
                        &maybe_close_sync_then_reject_promise);
    BIND(&if_isnotundefined);
  }
  TVARIABLE(JSAny, iter_result);
  {
    Label has_sent_value(this), no_sent_value(this), merge(this);
    ScopedExceptionHandler handler(this, &maybe_close_sync_then_reject_promise,
                                   &var_exception);
    Branch(IntPtrGreaterThan(args->GetLengthWithoutReceiver(),
                             IntPtrConstant(kValueOrReasonArg)),
           &has_sent_value, &no_sent_value);
    BIND(&has_sent_value);
    {
      iter_result = Call(context, method, sync_iterator, sent_value);
      Goto(&merge);
    }
    BIND(&no_sent_value);
    {
      iter_result = Call(context, method, sync_iterator);
      Goto(&merge);
    }
    BIND(&merge);
  }
  TNode<Object> value;
  TNode<Boolean> done;
  std::tie(value, done) =
      LoadIteratorResult(context, native_context, iter_result.value(),
                         &maybe_close_sync_then_reject_promise, &var_exception);
  const TNode<JSFunction> promise_fun = CAST(LoadContextElementNoCell(
      native_context, Context::PROMISE_FUNCTION_INDEX));
  CSA_DCHECK(this, IsConstructor(promise_fun));
  // 6. Let valueWrapper be PromiseResolve(%Promise%, « value »).
  // IfAbruptRejectPromise(valueWrapper, promiseCapability).
  TNode<Object> value_wrapper;
  {
    ScopedExceptionHandler handler(
        this, &maybe_close_sync_if_not_done_then_reject_promise,
        &var_exception);
    value_wrapper = CallBuiltin(Builtin::kPromiseResolve, native_context,
                                promise_fun, value);
  }
  // 10. Let onFulfilled be CreateBuiltinFunction(unwrap, 1, "", « »).
  const TNode<JSFunction> on_fulfilled =
      CreateUnwrapClosure(native_context, done);
  // 12. If done is true, or if closeOnRejection is false, then
  // a. Let onRejected be undefined.
  // 13. Else,
  // [...]
  // b. Let onRejected be CreateBuiltinFunction(closeIterator, 1, "", « »).
  TNode<Object> on_rejected;
  if (close_on_rejection == kCloseOnRejection) {
    on_rejected = Select<Object>(
        IsTrue(done), [=, this] { return UndefinedConstant(); },
        [=, this] {
          return CreateAsyncFromSyncIteratorCloseSyncAndRethrowClosure(
              native_context, sync_iterator);
        });
  } else {
    on_rejected = UndefinedConstant();
  }
  // 14. Perform ! PerformPromiseThen(valueWrapper,
  // onFulfilled, onRejected, promiseCapability).
  args->PopAndReturn(CallBuiltin<JSAny>(Builtin::kPerformPromiseThen, context,
                                        value_wrapper, on_fulfilled,
                                        on_rejected, promise));
  Label reject_promise(this);
  BIND(&maybe_close_sync_if_not_done_then_reject_promise);
  {
    if (close_on_rejection == kCloseOnRejection) {
      GotoIf(IsFalse(done), &maybe_close_sync_then_reject_promise);
    }
    Goto(&reject_promise);
  }
  BIND(&maybe_close_sync_then_reject_promise);
  {
    if (close_on_rejection == kCloseOnRejection) {
      // 7. If valueWrapper is an abrupt completion, done is false, and
      // closeOnRejection is true, then
      // a. Set valueWrapper to Completion(IteratorClose(syncIteratorRecord,
      // valueWrapper)).
      TorqueStructIteratorRecord sync_iterator_record = {sync_iterator, {}};
      IteratorCloseOnException(context, sync_iterator_record.object);
    }
    Goto(&reject_promise);
  }
  BIND(&reject_promise);
  {
    const TNode<Object> exception = var_exception.value();
    CallBuiltin(Builtin::kRejectPromise, context, promise, exception,
                TrueConstant());
    args->PopAndReturn(promise);
  }
}
References v8::base::args, CAST, v8::internal::compiler::IntPtrConstant(), v8::internal::IsNullOrUndefined(), v8::internal::native_context, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
Generate_AsyncFromSyncIteratorMethod() [2/2]
void v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::Generate_AsyncFromSyncIteratorMethod (CodeStubArguments * args, const TNode< Context > context, const TNode< Object > iterator, const TNode< Object > sent_value, Handle< String > name, const UndefinedMethodHandler & if_method_undefined, const char * operation_name, CloseOnRejectionOption close_on_rejection, Label::Type reject_label_type = Label::kDeferred, std::optional< TNode< Object >> initial_exception_value = std::nullopt) [inline]
Definition at line 43 of file builtins-async-iterator-gen.cc.
                                                                       {
    auto get_method = [=, this](const TNode<JSReceiver> sync_iterator) {
      return GetProperty(context, sync_iterator, name);
    };
    return Generate_AsyncFromSyncIteratorMethod(
        args, context, iterator, sent_value, get_method, if_method_undefined,
        operation_name, close_on_rejection, reject_label_type,
        initial_exception_value);
  }
References v8::base::args, and v8::internal::name.
LoadIteratorResult()
std::pair< TNode< Object >, TNode< Boolean > > v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::LoadIteratorResult (const TNode< Context > context, const TNode< NativeContext > native_context, const TNode< JSAny > iter_result, Label * if_exception, TVariable< Object > * var_exception)
Definition at line 225 of file builtins-async-iterator-gen.cc.
                                      {
  Label if_fastpath(this), if_slowpath(this), merge(this), to_boolean(this),
      done(this), if_notanobject(this, Label::kDeferred);
  GotoIf(TaggedIsSmi(iter_result), &if_notanobject);
  const TNode<Map> iter_result_map = LoadMap(CAST(iter_result));
  GotoIfNot(JSAnyIsNotPrimitiveMap(iter_result_map), &if_notanobject);
  const TNode<Object> fast_iter_result_map = LoadContextElementNoCell(
      native_context, Context::ITERATOR_RESULT_MAP_INDEX);
  TVARIABLE(Object, var_value);
  TVARIABLE(Object, var_done);
  Branch(TaggedEqual(iter_result_map, fast_iter_result_map), &if_fastpath,
         &if_slowpath);
  BIND(&if_fastpath);
  {
    TNode<JSObject> fast_iter_result = CAST(iter_result);
    var_done = LoadObjectField(fast_iter_result, JSIteratorResult::kDoneOffset);
    var_value =
        LoadObjectField(fast_iter_result, JSIteratorResult::kValueOffset);
    Goto(&merge);
  }
  BIND(&if_slowpath);
  {
    ScopedExceptionHandler handler(this, if_exception, var_exception);
    // Let nextDone be IteratorComplete(nextResult).
    // IfAbruptRejectPromise(nextDone, promiseCapability).
    const TNode<Object> iter_result_done =
        GetProperty(context, iter_result, factory()->done_string());
    // Let nextValue be IteratorValue(nextResult).
    // IfAbruptRejectPromise(nextValue, promiseCapability).
    const TNode<Object> iter_result_value =
        GetProperty(context, iter_result, factory()->value_string());
    var_value = iter_result_value;
    var_done = iter_result_done;
    Goto(&merge);
  }
  BIND(&if_notanobject);
  {
    // Sync iterator result is not an object --- Produce a TypeError and jump
    // to the `if_exception` path.
    const TNode<Object> error = MakeTypeError(
        MessageTemplate::kIteratorResultNotAnObject, context, iter_result);
    *var_exception = error;
    Goto(if_exception);
  }
  BIND(&merge);
  // Ensure `iterResult.done` is a Boolean.
  GotoIf(TaggedIsSmi(var_done.value()), &to_boolean);
  Branch(IsBoolean(CAST(var_done.value())), &done, &to_boolean);
  BIND(&to_boolean);
  {
    const TNode<Object> result =
        CallBuiltin(Builtin::kToBoolean, context, var_done.value());
    var_done = result;
    Goto(&done);
  }
  BIND(&done);
  return std::make_pair(var_value.value(), CAST(var_done.value()));
}
References CAST, v8::internal::native_context, and v8::base::internal::result.
Member Data Documentation
kValueOrReasonArg
const int v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::kValueOrReasonArg = 0 [static]
Definition at line 23 of file builtins-async-iterator-gen.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-async-iterator-gen.cc