v8::debug::ConsoleContext Class Reference
#include <interface-types.h>
Public Member Functions
ConsoleContext (int id, v8::Local< v8::String > name)
ConsoleContext ()
int id () const
v8::Local< v8::String > name () const
Private Attributes
int id_
v8::Local< v8::String > name_
Detailed Description
Definition at line 122 of file interface-types.h.
Constructor & Destructor Documentation
ConsoleContext() [1/2]
v8::debug::ConsoleContext::ConsoleContext (int id, v8::Local< v8::String > name) [inline]
Definition at line 124 of file interface-types.h.
: id_(id), name_(name) {}
ConsoleContext() [2/2]
v8::debug::ConsoleContext::ConsoleContext () [inline]
Definition at line 125 of file interface-types.h.
: id_(0) {}
Member Function Documentation
id()
int v8::debug::ConsoleContext::id () const [inline]
Definition at line 127 of file interface-types.h.
{ return id_; }
References id_.
Referenced by v8_inspector::anonymous_namespace{v8-console.cc}::consoleContextToString(), v8_inspector::V8Console::Count(), v8_inspector::V8Console::CountReset(), v8_inspector::V8Console::Time(), v8_inspector::V8Console::TimeEnd(), and v8_inspector::V8Console::TimeLog().
name()
v8::Local<v8::String> v8::debug::ConsoleContext::name () const [inline]
Definition at line 128 of file interface-types.h.
{ return name_; }
References name_.
Referenced by v8_inspector::anonymous_namespace{v8-console.cc}::consoleContextToString().
Member Data Documentation
id_
int v8::debug::ConsoleContext::id_ [private]
Definition at line 131 of file interface-types.h.
Referenced by id().
name_
v8::Local<v8::String> v8::debug::ConsoleContext::name_ [private]
Definition at line 132 of file interface-types.h.
Referenced by name().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/interface-types.h