v8::internal::UnaryOperation Class Reference
#include <ast.h>
Public Member Functions
Token::Value op () const
Expression * expression () const
Private Types
using OperatorField = Expression::NextBitField< Token::Value, 7 >
Private Member Functions
UnaryOperation (Token::Value op, Expression *expression, int pos)
Private Attributes
friend Zone
Expression * expression_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1883 of file ast.h.
Member Typedef Documentation
OperatorField
using v8::internal::UnaryOperation::OperatorField = Expression::NextBitField<Token::Value, 7> [private]
Definition at line 1900 of file ast.h.
Constructor & Destructor Documentation
UnaryOperation()
v8::internal::UnaryOperation::UnaryOperation (Token::Value op, Expression * expression, int pos) [inline], [private]
Definition at line 1892 of file ast.h.
      : Expression(pos, kUnaryOperation), expression_(expression) {
    bit_field_ |= OperatorField::encode(op);
    DCHECK(Token::IsUnaryOp(op));
  }
References v8::internal::AstNode::bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Token::IsUnaryOp(), and op().
Member Function Documentation
expression()
Expression* v8::internal::UnaryOperation::expression () const [inline]
Definition at line 1886 of file ast.h.
{ return expression_; }
References expression_.
Referenced by v8::internal::IsVoidOfLiteral(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitNot(), v8::internal::interpreter::BytecodeGenerator::VisitTypeOf(), and v8::internal::interpreter::BytecodeGenerator::VisitVoid().
op()
Token::Value v8::internal::UnaryOperation::op () const [inline]
Definition at line 1885 of file ast.h.
{ return OperatorField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::interpreter::IsTypeof(), v8::internal::IsVoidOfLiteral(), UnaryOperation(), and v8::internal::interpreter::BytecodeGenerator::VisitNot().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1889 of file ast.h.
Member Data Documentation
expression_
Expression* v8::internal::UnaryOperation::expression_ [private]
Definition at line 1898 of file ast.h.
Referenced by expression().
Zone
friend v8::internal::UnaryOperation::Zone [private]
Definition at line 1890 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h