v8::internal::UseScratchRegisterScope Class Reference
#include <assembler-arm.h>
Public Member Functions
UseScratchRegisterScope (Assembler *assembler)
~UseScratchRegisterScope ()
Register Acquire ()
SwVfpRegister AcquireS ()
LowDwVfpRegister AcquireLowD ()
DwVfpRegister AcquireD ()
QwNeonRegister AcquireQ ()
bool CanAcquire () const
bool CanAcquireS () const
bool CanAcquireD () const
bool CanAcquireQ () const
RegList Available ()
void SetAvailable (RegList available)
VfpRegList AvailableVfp ()
void SetAvailableVfp (VfpRegList available)
void Include (const Register &reg1, const Register &reg2=no_reg)
void Include (RegList list)
void Include (VfpRegList list)
void Exclude (const Register &reg1, const Register &reg2=no_reg)
void Exclude (VfpRegList list)
UseScratchRegisterScope (MacroAssembler *masm)
V8_EXPORT_PRIVATE ~UseScratchRegisterScope ()
Register AcquireW ()
Register AcquireX ()
VRegister AcquireS ()
VRegister AcquireD ()
VRegister AcquireQ ()
VRegister AcquireV (VectorFormat format)
bool CanAcquire () const
bool CanAcquireFP () const
Register AcquireSameSizeAs (const Register &reg)
V8_EXPORT_PRIVATE VRegister AcquireSameSizeAs (const VRegister &reg)
void Include (const CPURegList &list)
void IncludeFP (const CPURegList &list)
void Exclude (const CPURegList &list)
void ExcludeFP (const CPURegList &list)
void Include (const Register &reg1, const Register &reg2=NoReg)
void Exclude (const Register &reg1, const Register &reg2=NoReg)
void ExcludeFP (const VRegister &reg)
CPURegList * Available ()
void SetAvailable (const CPURegList &list)
CPURegList * AvailableFP ()
void SetAvailableFP (const CPURegList &list)
UseScratchRegisterScope (Assembler *assembler)
~UseScratchRegisterScope ()
Register Acquire ()
DoubleRegister AcquireFp ()
bool hasAvailable () const
bool hasAvailableFp () const
void Include (const RegList &list)
void IncludeFp (const DoubleRegList &list)
void Exclude (const RegList &list)
void ExcludeFp (const DoubleRegList &list)
void Include (const Register &reg1, const Register &reg2=no_reg)
void IncludeFp (const DoubleRegister &reg1, const DoubleRegister &reg2=no_dreg)
void Exclude (const Register &reg1, const Register &reg2=no_reg)
void ExcludeFp (const DoubleRegister &reg1, const DoubleRegister &reg2=no_dreg)
UseScratchRegisterScope (Assembler *assembler)
~UseScratchRegisterScope ()
Register Acquire ()
bool hasAvailable () const
void Include (const RegList &list)
void Exclude (const RegList &list)
void Include (const Register &reg1, const Register &reg2=no_reg)
void Exclude (const Register &reg1, const Register &reg2=no_reg)
UseScratchRegisterScope (Assembler *assembler)
~UseScratchRegisterScope ()
Register Acquire ()
bool CanAcquire () const
UseScratchRegisterScope (Assembler *assembler)
~UseScratchRegisterScope ()
Register Acquire ()
DoubleRegister AcquireDouble ()
bool CanAcquire () const
void Include (const Register &reg1, const Register &reg2)
void Include (const Register &reg)
void Include (RegList list)
void Exclude (const RegList &list)
void Exclude (const Register &reg1, const Register &reg2)
void Exclude (const Register &reg)
void Include (DoubleRegList list)
RegList Available ()
void SetAvailable (RegList available)
DoubleRegList AvailableDouble ()
void SetAvailableDouble (DoubleRegList available_double)
UseScratchRegisterScope (Assembler *assembler)
~UseScratchRegisterScope ()
Register Acquire ()
DoubleRegister AcquireDouble ()
bool CanAcquire () const
void Include (const Register &reg1, const Register &reg2=no_reg)
void Include (RegList list)
void Include (DoubleRegList list)
DoubleRegList AvailableDoubleRegList ()
void SetAvailableDoubleRegList (DoubleRegList available)
RegList Available ()
void SetAvailable (RegList available)
Private Member Functions
template<typename T >
bool CanAcquireVfp () const
template<typename T >
T AcquireVfp ()
Static Private Member Functions
static V8_EXPORT_PRIVATE CPURegister AcquireNextAvailable (CPURegList *available)
Private Attributes
Assembler * assembler_
RegList old_available_
VfpRegList old_available_vfp_
CPURegList * available_
CPURegList * availablefp_
uint64_t old_available_
uint64_t old_availablefp_
RegList * available_
DoubleRegList * availablefp_
DoubleRegList old_availablefp_
DoubleRegList old_available_double_
Friends
class Assembler
class MacroAssembler
Detailed Description
Definition at line 1392 of file assembler-arm.h.
Constructor & Destructor Documentation
UseScratchRegisterScope() [1/7]
v8::internal::UseScratchRegisterScope::UseScratchRegisterScope (Assembler * assembler) [inline], [explicit]
Definition at line 1394 of file assembler-arm.h.
      : assembler_(assembler),
        old_available_(*assembler->GetScratchRegisterList()),
        old_available_vfp_(*assembler->GetScratchVfpRegisterList()) {}
 UseScratchRegisterScope() [1/7]
v8::internal::UseScratchRegisterScope::~UseScratchRegisterScope () [inline]
Definition at line 1399 of file assembler-arm.h.
                             {
    *assembler_->GetScratchRegisterList() = old_available_;
    *assembler_->GetScratchVfpRegisterList() = old_available_vfp_;
  }
UseScratchRegisterScope() [2/7]
v8::internal::UseScratchRegisterScope::UseScratchRegisterScope (MacroAssembler * masm) [inline], [explicit]
Definition at line 2535 of file macro-assembler-arm64.h.
      : available_(masm->TmpList()),
        availablefp_(masm->FPTmpList()),
        old_available_(available_->bits()),
        old_availablefp_(availablefp_->bits()) {
    DCHECK_EQ(available_->type(), CPURegister::kRegister);
    DCHECK_EQ(availablefp_->type(), CPURegister::kVRegister);
  }
References DCHECK_EQ, v8::internal::CPURegister::kRegister, and v8::internal::CPURegister::kVRegister.
 UseScratchRegisterScope() [2/7]
V8_EXPORT_PRIVATE v8::internal::UseScratchRegisterScope::~UseScratchRegisterScope () [inline]
Definition at line 2544 of file macro-assembler-arm64.h.
                                               {
    available_->set_bits(old_available_);
    availablefp_->set_bits(old_availablefp_);
  }
UseScratchRegisterScope() [3/7]
v8::internal::UseScratchRegisterScope::UseScratchRegisterScope (Assembler * assembler) [inline], [explicit]
Definition at line 1128 of file assembler-loong64.h.
      : available_(assembler->GetScratchRegisterList()),
        availablefp_(assembler->GetScratchFPRegisterList()),
        old_available_(*available_),
        old_availablefp_(*availablefp_) {}
 UseScratchRegisterScope() [3/7]
v8::internal::UseScratchRegisterScope::~UseScratchRegisterScope () [inline]
Definition at line 1134 of file assembler-loong64.h.
                             {
    *available_ = old_available_;
    *availablefp_ = old_availablefp_;
  }
UseScratchRegisterScope() [4/7]
v8::internal::UseScratchRegisterScope::UseScratchRegisterScope (Assembler * assembler) [inline], [explicit]
Definition at line 1938 of file assembler-mips64.h.
      : available_(assembler->GetScratchRegisterList()),
        old_available_(*available_) {}
 UseScratchRegisterScope() [4/7]
v8::internal::UseScratchRegisterScope::~UseScratchRegisterScope () [inline]
Definition at line 1942 of file assembler-mips64.h.
{ *available_ = old_available_; }
UseScratchRegisterScope() [5/7]
v8::internal::UseScratchRegisterScope::UseScratchRegisterScope (Assembler * assembler) [inline], [explicit]
Definition at line 1550 of file assembler-ppc.h.
      : assembler_(assembler),
        old_available_(*assembler->GetScratchRegisterList()) {}
 UseScratchRegisterScope() [5/7]
v8::internal::UseScratchRegisterScope::~UseScratchRegisterScope () [inline]
Definition at line 1554 of file assembler-ppc.h.
                             {
    *assembler_->GetScratchRegisterList() = old_available_;
  }
UseScratchRegisterScope() [6/7]
v8::internal::UseScratchRegisterScope::UseScratchRegisterScope (Assembler * assembler) [inline], [explicit]
Definition at line 947 of file assembler-riscv.h.
      : assembler_(assembler),
        old_available_(*assembler->GetScratchRegisterList()),
        old_available_double_(*assembler->GetScratchDoubleRegisterList()) {}
 UseScratchRegisterScope() [6/7]
v8::internal::UseScratchRegisterScope::~UseScratchRegisterScope () [inline]
Definition at line 952 of file assembler-riscv.h.
                             {
    RegList* available = assembler_->GetScratchRegisterList();
    DoubleRegList* available_double =
        assembler_->GetScratchDoubleRegisterList();
    *available = old_available_;
    *available_double = old_available_double_;
  }
References available().
UseScratchRegisterScope() [7/7]
v8::internal::UseScratchRegisterScope::UseScratchRegisterScope (Assembler * assembler) [inline], [explicit]
Definition at line 1481 of file assembler-s390.h.
      : assembler_(assembler),
        old_available_(*assembler->GetScratchRegisterList()),
        old_available_double_(*assembler->GetScratchDoubleRegisterList()) {}
 UseScratchRegisterScope() [7/7]
v8::internal::UseScratchRegisterScope::~UseScratchRegisterScope () [inline]
Definition at line 1486 of file assembler-s390.h.
                             {
    *assembler_->GetScratchRegisterList() = old_available_;
    *assembler_->GetScratchDoubleRegisterList() = old_available_double_;
  }
Member Function Documentation
Acquire() [1/6]
Register v8::internal::UseScratchRegisterScope::Acquire () [inline]
Definition at line 1405 of file assembler-arm.h.
                     {
    return assembler_->GetScratchRegisterList()->PopFirst();
  }
Referenced by v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::AddOverflowWord(), v8::internal::MacroAssembler::AlignedLoadHelper(), v8::internal::MacroAssembler::AlignedStoreHelper(), v8::internal::MacroAssembler::Amosub_w(), v8::internal::MacroAssembler::And(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::AssembleBranchToLabels(), v8::internal::compiler::CodeGenerator::AssembleCodeStartRegisterCheck(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::MacroAssembler::AssertBoundFunction(), v8::internal::MacroAssembler::AssertCallableFunction(), v8::internal::MacroAssembler::AssertConstructor(), v8::internal::MacroAssembler::AssertFunction(), v8::internal::MacroAssembler::AssertGeneratorObject(), v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::MacroAssembler::AssertSmi(), v8::internal::MacroAssembler::AssertStackIsAligned(), v8::internal::MacroAssembler::BailoutIfDeoptimized(), v8::internal::MacroAssembler::Branch(), v8::internal::MacroAssembler::BranchAndLinkShortHelper(), v8::internal::MacroAssembler::BranchShortHelper(), v8::internal::MacroAssembler::CalcScaledAddress(), v8::internal::wasm::liftoff::CalculateActualAddress(), v8::internal::wasm::LiftoffAssembler::CallC(), v8::internal::MacroAssembler::CallCFunctionHelper(), v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::MacroAssembler::CallJSFunction(), v8::internal::MacroAssembler::CheckPageFlag(), v8::internal::MacroAssembler::Clz32(), v8::internal::MacroAssembler::CompareIsNotNanF32(), v8::internal::MacroAssembler::CompareIsNotNanF64(), v8::internal::MacroAssembler::CompareObjectTypeAndJump(), v8::internal::MacroAssembler::CompareRootAndBranch(), v8::internal::MacroAssembler::CompareTaggedAndBranch(), v8::internal::MacroAssembler::CompareTaggedRootAndBranch(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::MacroAssembler::Ctz32(), v8::internal::wasm::LiftoffAssembler::emit_f32_copysign(), v8::internal::wasm::LiftoffAssembler::emit_f64_copysign(), v8::internal::wasm::LiftoffAssembler::emit_i32_rems(), v8::internal::wasm::LiftoffAssembler::emit_i32_remu(), v8::internal::wasm::LiftoffAssembler::emit_i32_sar(), v8::internal::wasm::LiftoffAssembler::emit_i32_shl(), v8::internal::wasm::LiftoffAssembler::emit_i32_shr(), v8::internal::wasm::LiftoffAssembler::emit_i64_mul(), v8::internal::wasm::liftoff::EmitSimdShift(), v8::internal::wasm::liftoff::EnsureNoAlias(), v8::internal::MacroAssembler::EnterFrame(), v8::internal::wasm::liftoff::F64x2Compare(), v8::internal::MacroAssembler::FloatMinMaxHelper(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_AllocateSpaceAndShiftExistingArguments(), v8::internal::Builtins::Generate_CallBoundFunctionImpl(), v8::internal::Builtins::Generate_CallOrConstructForwardVarargs(), v8::internal::Builtins::Generate_CallOrConstructVarargs(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSBuiltinsConstructStubHelper(), v8::internal::Generate_JSEntryTrampolineHelper(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_PushBoundArguments(), v8::internal::MacroAssembler::GenerateSwitchTable(), v8::internal::wasm::liftoff::GetMemOp(), v8::internal::wasm::LiftoffAssembler::IncrementSmi(), v8::internal::MacroAssembler::InsertBits(), v8::internal::MacroAssembler::InsertHighWordF64(), v8::internal::MacroAssembler::InsertLowWordF64(), v8::internal::MacroAssembler::InvokeFunctionWithNewTarget(), v8::internal::MacroAssembler::InvokePrologue(), v8::internal::anonymous_namespace{builtins-riscv.cc}::JSToWasmWrapperHelper(), v8::internal::MacroAssembler::JumpIfEqual(), v8::internal::MacroAssembler::JumpIfIsInRange(), v8::internal::MacroAssembler::JumpIfLessThan(), v8::internal::MacroAssembler::JumpIfMarking(), v8::internal::MacroAssembler::JumpIfNotMarking(), v8::internal::MacroAssembler::JumpIfNotRoot(), v8::internal::MacroAssembler::JumpIfObjectType(), v8::internal::MacroAssembler::JumpIfRoot(), v8::internal::MacroAssembler::JumpJSFunction(), v8::internal::MacroAssembler::Ll(), v8::internal::MacroAssembler::LoadExternalPointerField(), v8::internal::MacroAssembler::LoadFeedbackVectorFlagsAndJumpIfNeedsProcessing(), v8::internal::MacroAssembler::LoadFPRImmediate(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::MacroAssembler::LoadZeroIfConditionNotZero(), v8::internal::MacroAssembler::LoadZeroIfConditionZero(), v8::internal::MacroAssembler::MoveIfZero(), v8::internal::MacroAssembler::near_call(), v8::internal::MacroAssembler::near_jump(), v8::internal::MacroAssembler::OptimizeCodeOrTailCallOptimizedCodeSlot(), v8::internal::MacroAssembler::Or(), v8::internal::MacroAssembler::PatchAndJump(), v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame(), v8::internal::compiler::CodeGenerator::Pop(), v8::internal::MacroAssembler::Popcnt32(), v8::internal::MacroAssembler::PopStackHandler(), v8::internal::wasm::LiftoffAssembler::PrepareTailCall(), v8::internal::compiler::CodeGenerator::Push(), v8::internal::MacroAssembler::Push(), v8::internal::MacroAssembler::PushArray(), v8::internal::MacroAssembler::PushRoot(), v8::internal::MacroAssembler::PushStackHandler(), v8::internal::MacroAssembler::RecordWrite(), v8::internal::MacroAssembler::RecordWriteField(), v8::internal::anonymous_namespace{builtins-riscv.cc}::ReloadParentStack(), v8::internal::MacroAssembler::Sc(), v8::internal::wasm::LiftoffAssembler::Spill(), v8::internal::wasm::LiftoffAssembler::StackCheck(), v8::internal::MacroAssembler::StubPrologue(), v8::internal::MacroAssembler::SubOverflowWord(), v8::internal::MacroAssembler::Trunc_w_d(), v8::internal::MacroAssembler::TryInlineTruncateDoubleToI(), v8::internal::MacroAssembler::TryLoadOptimizedOsrCode(), v8::internal::maglev::MaglevAssembler::TryTruncateDoubleToInt32(), v8::internal::maglev::MaglevAssembler::TryTruncateDoubleToUint32(), v8::internal::MacroAssembler::UnalignedLoadHelper(), v8::internal::MacroAssembler::UnalignedStoreHelper(), and v8::internal::MacroAssembler::Xor().
Acquire() [2/6]
Register v8::internal::UseScratchRegisterScope::Acquire () [inline]
Definition at line 1139 of file assembler-loong64.h.
                     {
    return available_->PopFirst();
  }
Acquire() [3/6]
Register v8::internal::UseScratchRegisterScope::Acquire () [inline]
Definition at line 1944 of file assembler-mips64.h.
                     {
    return available_->PopFirst();
  }
Acquire() [4/6]
Register v8::internal::UseScratchRegisterScope::Acquire () [inline]
Definition at line 1558 of file assembler-ppc.h.
                     {
    return assembler_->GetScratchRegisterList()->PopFirst();
  }
Acquire() [5/6]
Register v8::internal::UseScratchRegisterScope::Acquire () [inline]
Definition at line 960 of file assembler-riscv.h.
                     {
    RegList* available = assembler_->GetScratchRegisterList();
    return available->PopFirst();
  }
References available().
Acquire() [6/6]
Register v8::internal::UseScratchRegisterScope::Acquire () [inline]
Definition at line 1491 of file assembler-s390.h.
                     {
    return assembler_->GetScratchRegisterList()->PopFirst();
  }
AcquireD() [1/2]
DwVfpRegister v8::internal::UseScratchRegisterScope::AcquireD () [inline]
Definition at line 1410 of file assembler-arm.h.
                           {
    DwVfpRegister reg = AcquireVfp<DwVfpRegister>();
    DCHECK(assembler_->VfpRegisterIsAvailable(reg));
    return reg;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::liftoff::AcquireByType(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_type_conversion(), v8::internal::wasm::liftoff::EmitAnyTrue(), v8::internal::compiler::CodeGenerator::SetPendingMove(), and v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::Uint32Mod().
AcquireD() [2/2]
VRegister v8::internal::UseScratchRegisterScope::AcquireD () [inline]
Definition at line 2554 of file macro-assembler-arm64.h.
{ return AcquireNextAvailable(availablefp_).D(); }
References v8::internal::CPURegister::D().
AcquireDouble() [1/2]
DoubleRegister v8::internal::UseScratchRegisterScope::AcquireDouble () [inline]
Definition at line 965 of file assembler-riscv.h.
                                 {
    DoubleRegList* available_double =
        assembler_->GetScratchDoubleRegisterList();
    return available_double->PopFirst();
  }
References v8::internal::RegListBase< RegisterT >::PopFirst().
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble().
AcquireDouble() [2/2]
DoubleRegister v8::internal::UseScratchRegisterScope::AcquireDouble () [inline]
Definition at line 1495 of file assembler-s390.h.
                                 {
    return assembler_->GetScratchDoubleRegisterList()->PopFirst();
  }
AcquireFp()
DoubleRegister v8::internal::UseScratchRegisterScope::AcquireFp () [inline]
Definition at line 1143 of file assembler-loong64.h.
                             {
    return availablefp_->PopFirst();
  }
AcquireLowD()
LowDwVfpRegister v8::internal::UseScratchRegisterScope::AcquireLowD () [inline]
Definition at line 1409 of file assembler-arm.h.
{ return AcquireVfp<LowDwVfpRegister>(); }
Referenced by v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::maglev::MaglevAssembler::TryChangeFloat64ToIndex(), v8::internal::maglev::MaglevAssembler::TryTruncateDoubleToInt32(), v8::internal::maglev::MaglevAssembler::TryTruncateDoubleToUint32(), and v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::Uint32Mod().
AcquireNextAvailable()
static V8_EXPORT_PRIVATE CPURegister v8::internal::UseScratchRegisterScope::AcquireNextAvailable (CPURegList * available) [inline], [static], [private]
Definition at line 2612 of file macro-assembler-arm64.h.
                             {
    CHECK(!available->IsEmpty());
    CPURegister result = available->PopLowestIndex();
    DCHECK(!AreAliased(result, xzr, sp));
    return result;
  }
References v8::internal::AreAliased(), available(), CHECK, v8::internal::DCHECK(), and v8::base::internal::result.
AcquireQ() [1/2]
QwNeonRegister v8::internal::UseScratchRegisterScope::AcquireQ () [inline]
Definition at line 1415 of file assembler-arm.h.
                            {
    QwNeonRegister reg = AcquireVfp<QwNeonRegister>();
    DCHECK(assembler_->VfpRegisterIsAvailable(reg));
    return reg;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::liftoff::AcquireByType(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_pmax(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_pmin(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_qfma(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_qfms(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfma(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfms(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_dot_i8x16_i7x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i8x16_i7x16_add_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_mul(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_neg(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_shuffle(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_swizzle(), v8::internal::wasm::liftoff::EmitSimdShift(), and v8::internal::compiler::CodeGenerator::SetPendingMove().
AcquireQ() [2/2]
VRegister v8::internal::UseScratchRegisterScope::AcquireQ () [inline]
Definition at line 2555 of file macro-assembler-arm64.h.
{ return AcquireNextAvailable(availablefp_).Q(); }
References v8::internal::CPURegister::Q().
AcquireS() [1/2]
SwVfpRegister v8::internal::UseScratchRegisterScope::AcquireS () [inline]
Definition at line 1408 of file assembler-arm.h.
{ return AcquireVfp<SwVfpRegister>(); }
Referenced by v8::internal::wasm::liftoff::AcquireByType(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::wasm::LiftoffAssembler::emit_type_conversion(), v8::internal::maglev::MaglevAssembler::Int32ToDouble(), v8::internal::maglev::MaglevAssembler::LoadFloat32(), v8::internal::compiler::CodeGenerator::SetPendingMove(), v8::internal::maglev::MaglevAssembler::StoreFloat32(), and v8::internal::maglev::MaglevAssembler::Uint32ToDouble().
AcquireS() [2/2]
VRegister v8::internal::UseScratchRegisterScope::AcquireS () [inline]
Definition at line 2553 of file macro-assembler-arm64.h.
{ return AcquireNextAvailable(availablefp_).S(); }
References v8::internal::CPURegister::S().
AcquireSameSizeAs() [1/2]
Register v8::internal::UseScratchRegisterScope::AcquireSameSizeAs (const Register & reg) [inline]
Definition at line 2563 of file macro-assembler-arm64.h.
                                                  {
    int code = AcquireNextAvailable(available_).code();
    return Register::Create(code, reg.SizeInBits());
  }
References code, v8::internal::Register::Create(), and v8::internal::CPURegister::SizeInBits().
Referenced by v8::internal::MacroAssembler::Fccmp(), and v8::internal::MacroAssembler::Fcmp().
AcquireSameSizeAs() [2/2]
V8_EXPORT_PRIVATE VRegister v8::internal::UseScratchRegisterScope::AcquireSameSizeAs (const VRegister & reg) [inline]
Definition at line 2568 of file macro-assembler-arm64.h.
                                                                      {
    int code = AcquireNextAvailable(availablefp_).code();
    return VRegister::Create(code, reg.SizeInBits());
  }
References code, v8::internal::VRegister::Create(), and v8::internal::CPURegister::SizeInBits().
AcquireV()
VRegister v8::internal::UseScratchRegisterScope::AcquireV (VectorFormat format) [inline]
Definition at line 2556 of file macro-assembler-arm64.h.
                                          {
    return VRegister::Create(AcquireNextAvailable(availablefp_).code(), format);
  }
References code, v8::internal::VRegister::Create(), and v8::internal::format.
Referenced by v8::internal::wasm::liftoff::EmitAllTrue(), v8::internal::wasm::liftoff::EmitSimdShift(), v8::internal::compiler::Shuffle2Helper(), and v8::internal::compiler::Shuffle4Helper().
AcquireVfp()
template<typename T >
T v8::internal::UseScratchRegisterScope::AcquireVfp [private]
Definition at line 371 of file assembler-arm-inl.h.
                                      {
  VfpRegList* available = assembler_->GetScratchVfpRegisterList();
  DCHECK_NOT_NULL(available);
  for (int index = 0; index < T::kNumRegisters; index++) {
    T reg = T::from_code(index);
    uint64_t mask = reg.ToVfpRegList();
    if ((*available & mask) == mask) {
      *available &= ~mask;
      return reg;
    }
  }
  UNREACHABLE();
}
References assembler_, available(), DCHECK_NOT_NULL, v8::internal::Assembler::GetScratchVfpRegisterList(), v8::internal::index, v8::internal::kNumRegisters, and v8::internal::UNREACHABLE().
AcquireW()
Register v8::internal::UseScratchRegisterScope::AcquireW () [inline]
Definition at line 2551 of file macro-assembler-arm64.h.
{ return AcquireNextAvailable(available_).W(); }
References v8::internal::CPURegister::W().
Referenced by v8::internal::wasm::liftoff::AcquireByType(), v8::internal::wasm::liftoff::AtomicBinop(), v8::internal::wasm::liftoff::EmitSimdShift(), v8::internal::MacroAssembler::Fmov(), and v8::internal::wasm::liftoff::LoadToRegister().
AcquireX()
Register v8::internal::UseScratchRegisterScope::AcquireX () [inline]
Definition at line 2552 of file macro-assembler-arm64.h.
{ return AcquireNextAvailable(available_).X(); }
References v8::internal::CPURegister::X().
Referenced by v8::internal::wasm::liftoff::AcquireByType(), v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::AssertFeedbackVector(), v8::internal::wasm::liftoff::AtomicBinop(), v8::internal::wasm::liftoff::CalculateActualAddress(), v8::internal::MacroAssembler::Claim(), v8::internal::MacroAssembler::DropArguments(), v8::internal::wasm::LiftoffAssembler::emit_i64_muli(), v8::internal::wasm::liftoff::EmitSimdShift(), v8::internal::wasm::liftoff::GetEffectiveAddress(), v8::internal::wasm::liftoff::GetMemOp(), and v8::internal::wasm::liftoff::LoadToRegister().
Available() [1/4]
RegList v8::internal::UseScratchRegisterScope::Available () [inline]
Definition at line 1429 of file assembler-arm.h.
{ return *assembler_->GetScratchRegisterList(); }
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer().
Available() [2/4]
CPURegList* v8::internal::UseScratchRegisterScope::Available () [inline]
Definition at line 2605 of file macro-assembler-arm64.h.
{ return available_; }
Available() [3/4]
RegList v8::internal::UseScratchRegisterScope::Available () [inline]
Definition at line 1016 of file assembler-riscv.h.
{ return *assembler_->GetScratchRegisterList(); }
Available() [4/4]
RegList v8::internal::UseScratchRegisterScope::Available () [inline]
Definition at line 1530 of file assembler-s390.h.
{ return *assembler_->GetScratchRegisterList(); }
AvailableDouble()
DoubleRegList v8::internal::UseScratchRegisterScope::AvailableDouble () [inline]
Definition at line 1020 of file assembler-riscv.h.
                                  {
    return *assembler_->GetScratchDoubleRegisterList();
  }
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer().
AvailableDoubleRegList()
DoubleRegList v8::internal::UseScratchRegisterScope::AvailableDoubleRegList () [inline]
Definition at line 1524 of file assembler-s390.h.
                                         {
    return *assembler_->GetScratchDoubleRegisterList();
  }
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer().
AvailableFP()
CPURegList* v8::internal::UseScratchRegisterScope::AvailableFP () [inline]
Definition at line 2608 of file macro-assembler-arm64.h.
{ return availablefp_; }
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer().
AvailableVfp()
VfpRegList v8::internal::UseScratchRegisterScope::AvailableVfp () [inline]
Definition at line 1434 of file assembler-arm.h.
{ return *assembler_->GetScratchVfpRegisterList(); }
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer().
CanAcquire() [1/5]
bool v8::internal::UseScratchRegisterScope::CanAcquire () const [inline]
Definition at line 1422 of file assembler-arm.h.
                          {
    return !assembler_->GetScratchRegisterList()->is_empty();
  }
Referenced by v8::internal::MacroAssembler::li(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope(), and v8::internal::wasm::LiftoffAssembler::Spill().
CanAcquire() [2/5]
bool v8::internal::UseScratchRegisterScope::CanAcquire () const [inline]
Definition at line 2560 of file macro-assembler-arm64.h.
{ return !available_->IsEmpty(); }
CanAcquire() [3/5]
bool v8::internal::UseScratchRegisterScope::CanAcquire () const [inline]
Definition at line 1563 of file assembler-ppc.h.
                          {
    return !assembler_->GetScratchRegisterList()->is_empty();
  }
CanAcquire() [4/5]
bool v8::internal::UseScratchRegisterScope::CanAcquire () const [inline]
Definition at line 972 of file assembler-riscv.h.
                          {
    RegList* available = assembler_->GetScratchRegisterList();
    return !available->is_empty();
  }
References available().
CanAcquire() [5/5]
bool v8::internal::UseScratchRegisterScope::CanAcquire () const [inline]
Definition at line 1500 of file assembler-s390.h.
                          {
    return !assembler_->GetScratchRegisterList()->is_empty();
  }
CanAcquireD()
bool v8::internal::UseScratchRegisterScope::CanAcquireD () const [inline]
Definition at line 1426 of file assembler-arm.h.
{ return CanAcquireVfp<DwVfpRegister>(); }
Referenced by v8::internal::compiler::CodeGenerator::AssembleSwap().
CanAcquireFP()
bool v8::internal::UseScratchRegisterScope::CanAcquireFP () const [inline]
Definition at line 2561 of file macro-assembler-arm64.h.
{ return !availablefp_->IsEmpty(); }
CanAcquireQ()
bool v8::internal::UseScratchRegisterScope::CanAcquireQ () const [inline]
Definition at line 1427 of file assembler-arm.h.
{ return CanAcquireVfp<QwNeonRegister>(); }
CanAcquireS()
bool v8::internal::UseScratchRegisterScope::CanAcquireS () const [inline]
Definition at line 1425 of file assembler-arm.h.
{ return CanAcquireVfp<SwVfpRegister>(); }
CanAcquireVfp()
template<typename T >
bool v8::internal::UseScratchRegisterScope::CanAcquireVfp [private]
Definition at line 357 of file assembler-arm-inl.h.
                                                  {
  VfpRegList* available = assembler_->GetScratchVfpRegisterList();
  DCHECK_NOT_NULL(available);
  for (int index = 0; index < T::kNumRegisters; index++) {
    T reg = T::from_code(index);
    uint64_t mask = reg.ToVfpRegList();
    if ((*available & mask) == mask) {
      return true;
    }
  }
  return false;
}
References assembler_, available(), DCHECK_NOT_NULL, v8::internal::Assembler::GetScratchVfpRegisterList(), v8::internal::index, and v8::internal::kNumRegisters.
Exclude() [1/11]
void v8::internal::UseScratchRegisterScope::Exclude (const CPURegList & list) [inline]
Definition at line 2575 of file macro-assembler-arm64.h.
                                       {
#if DEBUG
    CPURegList copy(list);
    while (!copy.IsEmpty()) {
      const CPURegister& reg = copy.PopHighestIndex();
      DCHECK(available_->IncludesAliasOf(reg));
    }
#endif
    available_->Remove(list);
  }
References v8::internal::DCHECK(), v8::internal::CPURegList::IsEmpty(), and v8::internal::CPURegList::PopHighestIndex().
Exclude() [2/11]
void v8::internal::UseScratchRegisterScope::Exclude (const Register & reg) [inline]
Definition at line 1002 of file assembler-riscv.h.
                                    {
    DCHECK_NE(reg, no_reg);
    RegList list({reg});
    Exclude(list);
  }
References DCHECK_NE, and v8::internal::no_reg.
Exclude() [3/11]
void v8::internal::UseScratchRegisterScope::Exclude (const Register & reg1, const Register & reg2) [inline]
Definition at line 998 of file assembler-riscv.h.
                                                           {
    Exclude(reg1);
    Exclude(reg2);
  }
Exclude() [4/11]
void v8::internal::UseScratchRegisterScope::Exclude (const Register & reg1, const Register & reg2 = no_reg) [inline]
Definition at line 1458 of file assembler-arm.h.
                                                                    {
    RegList* available = assembler_->GetScratchRegisterList();
    DCHECK_NOT_NULL(available);
    DCHECK(available->has(reg1));
    DCHECK_IMPLIES(reg2.is_valid(), available->has(reg2));
    available->clear(RegList{reg1, reg2});
  }
References available(), v8::internal::DCHECK(), DCHECK_IMPLIES, and DCHECK_NOT_NULL.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchSimulatorStackLimit(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStackPointerAndSimulatorStackLimit().
Exclude() [5/11]
void v8::internal::UseScratchRegisterScope::Exclude (const Register & reg1, const Register & reg2 = no_reg) [inline]
Definition at line 1164 of file assembler-loong64.h.
                                                                    {
    RegList list({reg1, reg2});
    Exclude(list);
  }
Exclude() [6/11]
void v8::internal::UseScratchRegisterScope::Exclude (const Register & reg1, const Register & reg2 = no_reg) [inline]
Definition at line 1956 of file assembler-mips64.h.
                                                                    {
    RegList list({reg1, reg2});
    Exclude(list);
  }
Exclude() [7/11]
void v8::internal::UseScratchRegisterScope::Exclude (const Register & reg1, const Register & reg2 = NoReg) [inline]
Definition at line 2599 of file macro-assembler-arm64.h.
                                                                   {
    CPURegList list(reg1, reg2);
    Exclude(list);
  }
Exclude() [8/11]
void v8::internal::UseScratchRegisterScope::Exclude (const RegList & list) [inline]
Definition at line 1153 of file assembler-loong64.h.
{ available_->clear(list); }
Exclude() [9/11]
void v8::internal::UseScratchRegisterScope::Exclude (const RegList & list) [inline]
Definition at line 1951 of file assembler-mips64.h.
{ available_->clear(list); }
Exclude() [10/11]
void v8::internal::UseScratchRegisterScope::Exclude (const RegList & list) [inline]
Definition at line 993 of file assembler-riscv.h.
                                    {
    RegList* available = assembler_->GetScratchRegisterList();
    DCHECK_NOT_NULL(available);
    available->clear(list);
  }
References available(), and DCHECK_NOT_NULL.
Exclude() [11/11]
void v8::internal::UseScratchRegisterScope::Exclude (VfpRegList list) [inline]
Definition at line 1465 of file assembler-arm.h.
                                {
    VfpRegList* available = assembler_->GetScratchVfpRegisterList();
    DCHECK_NOT_NULL(available);
    DCHECK_EQ((*available | list), *available);
    *available = *available & ~list;
  }
References available(), DCHECK_EQ, and DCHECK_NOT_NULL.
ExcludeFP() [1/2]
void v8::internal::UseScratchRegisterScope::ExcludeFP (const CPURegList & list) [inline]
Definition at line 2585 of file macro-assembler-arm64.h.
                                         {
#if DEBUG
    CPURegList copy(list);
    while (!copy.IsEmpty()) {
      const CPURegister& reg = copy.PopHighestIndex();
      DCHECK(availablefp_->IncludesAliasOf(reg));
    }
#endif
    availablefp_->Remove(list);
  }
References v8::internal::DCHECK(), v8::internal::CPURegList::IsEmpty(), and v8::internal::CPURegList::PopHighestIndex().
ExcludeFp() [1/2]
void v8::internal::UseScratchRegisterScope::ExcludeFp (const DoubleRegister & reg1, const DoubleRegister & reg2 = no_dreg) [inline]
Definition at line 1168 of file assembler-loong64.h.
                                                       {
    DoubleRegList list({reg1, reg2});
    ExcludeFp(list);
  }
ExcludeFp() [2/2]
void v8::internal::UseScratchRegisterScope::ExcludeFp (const DoubleRegList & list) [inline]
Definition at line 1154 of file assembler-loong64.h.
{ availablefp_->clear(list); }
ExcludeFP() [2/2]
void v8::internal::UseScratchRegisterScope::ExcludeFP (const VRegister & reg) [inline]
Definition at line 2603 of file macro-assembler-arm64.h.
{ ExcludeFP(CPURegList(reg)); }
References ExcludeFP().
Referenced by ExcludeFP().
hasAvailable() [1/2]
bool v8::internal::UseScratchRegisterScope::hasAvailable () const [inline]
Definition at line 1147 of file assembler-loong64.h.
{ return !available_->is_empty(); }
hasAvailable() [2/2]
bool v8::internal::UseScratchRegisterScope::hasAvailable () const [inline]
Definition at line 1948 of file assembler-mips64.h.
{ return !available_->is_empty(); }
hasAvailableFp()
bool v8::internal::UseScratchRegisterScope::hasAvailableFp () const [inline]
Definition at line 1149 of file assembler-loong64.h.
{ return !availablefp_->is_empty(); }
Include() [1/16]
void v8::internal::UseScratchRegisterScope::Include (const CPURegList & list) [inline]
Definition at line 2573 of file macro-assembler-arm64.h.
{ available_->Combine(list); }
Include() [2/16]
void v8::internal::UseScratchRegisterScope::Include (const Register & reg) [inline]
Definition at line 981 of file assembler-riscv.h.
                                    {
    DCHECK_NE(reg, no_reg);
    RegList* available = assembler_->GetScratchRegisterList();
    DCHECK_NOT_NULL(available);
    DCHECK(!available->has(reg));
    available->set(reg);
  }
References available(), v8::internal::DCHECK(), DCHECK_NE, DCHECK_NOT_NULL, and v8::internal::no_reg.
Include() [3/16]
void v8::internal::UseScratchRegisterScope::Include (const Register & reg1, const Register & reg2) [inline]
Definition at line 977 of file assembler-riscv.h.
                                                           {
    Include(reg1);
    Include(reg2);
  }
Include() [4/16]
void v8::internal::UseScratchRegisterScope::Include (const Register & reg1, const Register & reg2 = no_reg) [inline]
Definition at line 1439 of file assembler-arm.h.
                                                                    {
    RegList* available = assembler_->GetScratchRegisterList();
    DCHECK_NOT_NULL(available);
    DCHECK(!available->has(reg1));
    DCHECK(!available->has(reg2));
    available->set(reg1);
    available->set(reg2);
  }
References available(), v8::internal::DCHECK(), and DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::AssembleBranchToLabels(), v8::internal::MacroAssembler::CheckPageFlag(), v8::internal::Builtins::Generate_CallOrConstructForwardVarargs(), v8::internal::Builtins::Generate_CallOrConstructVarargs(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSBuiltinsConstructStubHelper(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_PushBoundArguments(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::IncludeScratch(), v8::internal::MacroAssembler::InvokePrologue(), v8::internal::MacroAssembler::OptimizeCodeOrTailCallOptimizedCodeSlot(), v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope().
Include() [5/16]
void v8::internal::UseScratchRegisterScope::Include (const Register & reg1, const Register & reg2 = no_reg) [inline]
Definition at line 1155 of file assembler-loong64.h.
                                                                    {
    RegList list({reg1, reg2});
    Include(list);
  }
Include() [6/16]
void v8::internal::UseScratchRegisterScope::Include (const Register & reg1, const Register & reg2 = no_reg) [inline]
Definition at line 1952 of file assembler-mips64.h.
                                                                    {
    RegList list({reg1, reg2});
    Include(list);
  }
Include() [7/16]
void v8::internal::UseScratchRegisterScope::Include (const Register & reg1, const Register & reg2 = no_reg) [inline]
Definition at line 1504 of file assembler-s390.h.
                                                                    {
    RegList* available = assembler_->GetScratchRegisterList();
    DCHECK_NOT_NULL(available);
    DCHECK(!available->has(reg1));
    DCHECK(!available->has(reg2));
    available->set(reg1);
    available->set(reg2);
  }
References available(), v8::internal::DCHECK(), and DCHECK_NOT_NULL.
Include() [8/16]
void v8::internal::UseScratchRegisterScope::Include (const Register & reg1, const Register & reg2 = NoReg) [inline]
Definition at line 2595 of file macro-assembler-arm64.h.
                                                                   {
    CPURegList list(reg1, reg2);
    Include(list);
  }
Include() [9/16]
void v8::internal::UseScratchRegisterScope::Include (const RegList & list) [inline]
Definition at line 1151 of file assembler-loong64.h.
{ *available_ |= list; }
Include() [10/16]
void v8::internal::UseScratchRegisterScope::Include (const RegList & list) [inline]
Definition at line 1950 of file assembler-mips64.h.
{ *available_ |= list; }
Include() [11/16]
void v8::internal::UseScratchRegisterScope::Include (DoubleRegList list) [inline]
Definition at line 1008 of file assembler-riscv.h.
                                   {
    DoubleRegList* available_double =
        assembler_->GetScratchDoubleRegisterList();
    DCHECK_NOT_NULL(available_double);
    DCHECK_EQ((*available_double & list).bits(), 0x0);
    *available_double = *available_double | list;
  }
References DCHECK_EQ, and DCHECK_NOT_NULL.
Include() [12/16]
void v8::internal::UseScratchRegisterScope::Include (DoubleRegList list) [inline]
Definition at line 1517 of file assembler-s390.h.
                                   {
    DoubleRegList* available = assembler_->GetScratchDoubleRegisterList();
    DCHECK_NOT_NULL(available);
    DCHECK_EQ((*available & list).bits(), 0x0);
    *available = *available | list;
  }
References available(), DCHECK_EQ, and DCHECK_NOT_NULL.
Include() [13/16]
void v8::internal::UseScratchRegisterScope::Include (RegList list) [inline]
Definition at line 1447 of file assembler-arm.h.
                             {
    RegList* available = assembler_->GetScratchRegisterList();
    DCHECK_NOT_NULL(available);
    *available = *available | list;
  }
References available(), and DCHECK_NOT_NULL.
Include() [14/16]
void v8::internal::UseScratchRegisterScope::Include (RegList list) [inline]
Definition at line 988 of file assembler-riscv.h.
                             {
    RegList* available = assembler_->GetScratchRegisterList();
    DCHECK_NOT_NULL(available);
    *available = *available | list;
  }
References available(), and DCHECK_NOT_NULL.
Include() [15/16]
void v8::internal::UseScratchRegisterScope::Include (RegList list) [inline]
Definition at line 1512 of file assembler-s390.h.
                             {
    RegList* available = assembler_->GetScratchRegisterList();
    DCHECK_NOT_NULL(available);
    *available = *available | list;
  }
References available(), and DCHECK_NOT_NULL.
Include() [16/16]
void v8::internal::UseScratchRegisterScope::Include (VfpRegList list) [inline]
Definition at line 1452 of file assembler-arm.h.
                                {
    VfpRegList* available = assembler_->GetScratchVfpRegisterList();
    DCHECK_NOT_NULL(available);
    DCHECK_EQ((*available & list), 0x0);
    *available = *available | list;
  }
References available(), DCHECK_EQ, and DCHECK_NOT_NULL.
IncludeFP()
void v8::internal::UseScratchRegisterScope::IncludeFP (const CPURegList & list) [inline]
Definition at line 2574 of file macro-assembler-arm64.h.
{ availablefp_->Combine(list); }
IncludeFp() [1/2]
void v8::internal::UseScratchRegisterScope::IncludeFp (const DoubleRegister & reg1, const DoubleRegister & reg2 = no_dreg) [inline]
Definition at line 1159 of file assembler-loong64.h.
                                                       {
    DoubleRegList list({reg1, reg2});
    IncludeFp(list);
  }
IncludeFp() [2/2]
void v8::internal::UseScratchRegisterScope::IncludeFp (const DoubleRegList & list) [inline]
Definition at line 1152 of file assembler-loong64.h.
{ *availablefp_ |= list; }
SetAvailable() [1/4]
void v8::internal::UseScratchRegisterScope::SetAvailable (const CPURegList & list) [inline]
Definition at line 2606 of file macro-assembler-arm64.h.
{ *available_ = list; }
SetAvailable() [2/4]
void v8::internal::UseScratchRegisterScope::SetAvailable (RegList available) [inline]
Definition at line 1430 of file assembler-arm.h.
                                       {
    *assembler_->GetScratchRegisterList() = available;
  }
References available().
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope().
SetAvailable() [3/4]
void v8::internal::UseScratchRegisterScope::SetAvailable (RegList available) [inline]
Definition at line 1017 of file assembler-riscv.h.
                                       {
    *assembler_->GetScratchRegisterList() = available;
  }
References available().
SetAvailable() [4/4]
void v8::internal::UseScratchRegisterScope::SetAvailable (RegList available) [inline]
Definition at line 1531 of file assembler-s390.h.
                                       {
    *assembler_->GetScratchRegisterList() = available;
  }
References available().
SetAvailableDouble()
void v8::internal::UseScratchRegisterScope::SetAvailableDouble (DoubleRegList available_double) [inline]
Definition at line 1023 of file assembler-riscv.h.
                                                          {
    *assembler_->GetScratchDoubleRegisterList() = available_double;
  }
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope().
SetAvailableDoubleRegList()
void v8::internal::UseScratchRegisterScope::SetAvailableDoubleRegList (DoubleRegList available) [inline]
Definition at line 1527 of file assembler-s390.h.
                                                          {
    *assembler_->GetScratchDoubleRegisterList() = available;
  }
References available().
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope().
SetAvailableFP()
void v8::internal::UseScratchRegisterScope::SetAvailableFP (const CPURegList & list) [inline]
Definition at line 2609 of file macro-assembler-arm64.h.
{ *availablefp_ = list; }
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope().
SetAvailableVfp()
void v8::internal::UseScratchRegisterScope::SetAvailableVfp (VfpRegList available) [inline]
Definition at line 1435 of file assembler-arm.h.
                                             {
    *assembler_->GetScratchVfpRegisterList() = available;
  }
References available().
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope().
Friends And Related Function Documentation
Assembler
Assembler [friend]
Definition at line 1473 of file assembler-arm.h.
MacroAssembler
MacroAssembler [friend]
Definition at line 1474 of file assembler-arm.h.
Member Data Documentation
assembler_
Assembler * v8::internal::UseScratchRegisterScope::assembler_ [private]
Definition at line 1482 of file assembler-arm.h.
Referenced by AcquireVfp(), and CanAcquireVfp().
available_ [1/2]
RegList * v8::internal::UseScratchRegisterScope::available_ [private]
Definition at line 2621 of file macro-assembler-arm64.h.
available_ [2/2]
RegList* v8::internal::UseScratchRegisterScope::available_ [private]
Definition at line 1175 of file assembler-loong64.h.
availablefp_ [1/2]
CPURegList* v8::internal::UseScratchRegisterScope::availablefp_ [private]
Definition at line 2622 of file macro-assembler-arm64.h.
availablefp_ [2/2]
DoubleRegList* v8::internal::UseScratchRegisterScope::availablefp_ [private]
Definition at line 1176 of file assembler-loong64.h.
old_available_ [1/2]
RegList v8::internal::UseScratchRegisterScope::old_available_ [private]
Definition at line 1484 of file assembler-arm.h.
old_available_ [2/2]
uint64_t v8::internal::UseScratchRegisterScope::old_available_ [private]
Definition at line 2625 of file macro-assembler-arm64.h.
old_available_double_
DoubleRegList v8::internal::UseScratchRegisterScope::old_available_double_ [private]
Definition at line 1033 of file assembler-riscv.h.
old_available_vfp_
VfpRegList v8::internal::UseScratchRegisterScope::old_available_vfp_ [private]
Definition at line 1485 of file assembler-arm.h.
old_availablefp_ [1/2]
uint64_t v8::internal::UseScratchRegisterScope::old_availablefp_ [private]
Definition at line 2626 of file macro-assembler-arm64.h.
old_availablefp_ [2/2]
DoubleRegList v8::internal::UseScratchRegisterScope::old_availablefp_ [private]
Definition at line 1178 of file assembler-loong64.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm/assembler-arm.h
/mnt/V8SourceCode/src/codegen/arm64/macro-assembler-arm64.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.h
/mnt/V8SourceCode/src/codegen/s390/assembler-s390.h
/mnt/V8SourceCode/src/codegen/arm/assembler-arm-inl.h