v8::internal::FieldType Class Reference
#include <field-type.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE Tagged< FieldType > None ()
static V8_EXPORT_PRIVATE Tagged< FieldType > Any ()
static V8_EXPORT_PRIVATE DirectHandle< FieldType > None (Isolate *isolate)
static V8_EXPORT_PRIVATE DirectHandle< FieldType > Any (Isolate *isolate)
static V8_EXPORT_PRIVATE Tagged< FieldType > Class (Tagged< Map > map)
static V8_EXPORT_PRIVATE DirectHandle< FieldType > Class (DirectHandle< Map > map, Isolate *isolate)
static bool NowContains (Tagged< FieldType > type, Tagged< Object > value)
static bool NowContains (Tagged< FieldType > type, DirectHandle< Object > value)
static Tagged< Map > AsClass (Tagged< FieldType > type)
static DirectHandle< Map > AsClass (DirectHandle< FieldType > type)
static bool NowStable (Tagged< FieldType > type)
static bool NowIs (Tagged< FieldType > type, Tagged< FieldType > other)
static bool NowIs (Tagged< FieldType > type, DirectHandle< FieldType > other)
static V8_EXPORT_PRIVATE bool Equals (Tagged< FieldType > type, Tagged< FieldType > other)
static V8_EXPORT_PRIVATE void PrintTo (Tagged< FieldType > type, std::ostream &os)
Static Public Attributes
static constexpr bool kFieldTypesCanBeClearedOnGC = true
Detailed Description
Definition at line 17 of file field-type.h.
Member Function Documentation
Any() [1/2]
Tagged< FieldType > v8::internal::FieldType::Any () [static]
Definition at line 22 of file field-type.cc.
                                 {
  return Tagged<FieldType>(Smi::FromInt(1).ptr());
}
References v8::internal::Smi::FromInt().
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::CastTraits< FieldType >::AllowFrom(), Any(), v8::internal::AccessorAssembler::CheckFieldType(), v8::internal::AccessorAssembler::CheckHeapObjectTypeMatchesDescriptor(), v8::internal::Map::CopyWithField(), v8::internal::JSSharedStruct::CreateInstanceMap(), v8::internal::Heap::CreateLateReadOnlyJSReceiverMaps(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateLiteralObjectMapFromCache(), v8::internal::Descriptor::DataConstant(), v8::internal::Descriptor::DataField(), v8::internal::DescriptorArray::GeneralizeAllFields(), v8::internal::anonymous_namespace{map-updater.cc}::GeneralizeFieldType(), v8::internal::Map::GeneralizeIfCanHaveTransitionableFastElementsKind(), v8::internal::IsAny(), v8::internal::JSObject::MigrateSlowToFast(), NowContains(), v8::internal::Object::OptimalType(), and v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue().
Any() [2/2]
DirectHandle< FieldType > v8::internal::FieldType::Any (Isolate * isolate) [static]
Definition at line 32 of file field-type.cc.
                                                       {
  return direct_handle(Any(), isolate);
}
References Any(), and v8::internal::direct_handle().
AsClass() [1/2]
DirectHandle< Map > v8::internal::FieldType::AsClass (DirectHandle< FieldType > type) [static]
Definition at line 57 of file field-type.cc.
                                                                 {
  DCHECK(IsClass(*type));
  return Cast<Map>(type);
}
References v8::internal::DCHECK(), v8::internal::IsClass(), and v8::internal::tracing::type.
AsClass() [2/2]
Tagged< Map > v8::internal::FieldType::AsClass (Tagged< FieldType > type) [static]
Definition at line 51 of file field-type.cc.
                                                     {
  DCHECK(IsClass(type));
  return Cast<Map>(type);
}
References v8::internal::DCHECK(), v8::internal::IsClass(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), NowStable(), PrintTo(), and v8::internal::Map::WrapFieldType().
Class() [1/2]
DirectHandle< FieldType > v8::internal::FieldType::Class (DirectHandle< Map > map, Isolate * isolate) [static]
Definition at line 42 of file field-type.cc.
                                                           {
  return direct_handle(Class(*map), isolate);
}
References Class(), and v8::internal::direct_handle().
Class() [2/2]
Tagged< FieldType > v8::internal::FieldType::Class (Tagged< Map > map) [static]
Definition at line 37 of file field-type.cc.
                                                  {
  return Cast<FieldType>(Tagged<Object>(map));
}
Referenced by Class(), and v8::internal::Object::OptimalType().
Equals()
bool v8::internal::FieldType::Equals (Tagged< FieldType > type, Tagged< FieldType > other) [static]
Definition at line 79 of file field-type.cc.
                                                                      {
  if (IsAny(type) && IsAny(other)) return true;
  if (IsNone(type) && IsNone(other)) return true;
  if (IsClass(type) && IsClass(other)) {
    return type == other;
  }
  return false;
}
References v8::internal::IsAny(), v8::internal::IsClass(), v8::internal::IsNone(), and v8::internal::tracing::type.
Referenced by v8::internal::MapUpdater::GeneralizeField(), and v8::internal::MapUpdater::UpdateFieldType().
None() [1/2]
Tagged< FieldType > v8::internal::FieldType::None () [static]
Definition at line 17 of file field-type.cc.
                                  {
  return Tagged<FieldType>(Smi::FromInt(2).ptr());
}
References v8::internal::Smi::FromInt().
Referenced by v8::internal::CastTraits< FieldType >::AllowFrom(), v8::internal::AccessorAssembler::CheckFieldType(), v8::internal::AccessorAssembler::CheckHeapObjectTypeMatchesDescriptor(), v8::internal::IsNone(), None(), NowContains(), v8::internal::Object::OptimalType(), and v8::internal::MapUpdater::ReconfigureExistingProperty().
None() [2/2]
DirectHandle< FieldType > v8::internal::FieldType::None (Isolate * isolate) [static]
Definition at line 27 of file field-type.cc.
                                                        {
  return direct_handle(None(), isolate);
}
References v8::internal::direct_handle(), and None().
NowContains() [1/2]
static bool v8::internal::FieldType::NowContains (Tagged< FieldType > type, DirectHandle< Object > value) [inline], [static]
Definition at line 33 of file field-type.h.
                                                                              {
    return NowContains(type, *value);
  }
References NowContains(), v8::internal::tracing::type, and v8::internal::value.
NowContains() [2/2]
bool v8::internal::FieldType::NowContains (Tagged< FieldType > type, Tagged< Object > value) [static]
Definition at line 106 of file field-type.cc.
                                                                        {
  if (type == Any()) return true;
  if (type == None()) return false;
  if (!IsHeapObject(value)) return false;
  return Cast<HeapObject>(value)->map() == Cast<Map>(type);
}
References Any(), v8::internal::IsHeapObject(), None(), v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{map.cc}::CanHoldValue(), v8::internal::DictionaryTemplateInfo::NewInstance(), NowContains(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), and v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue().
NowIs() [1/2]
bool v8::internal::FieldType::NowIs (Tagged< FieldType > type, DirectHandle< FieldType > other) [static]
Definition at line 89 of file field-type.cc.
                                                                           {
  return NowIs(type, *other);
}
References NowIs(), and v8::internal::tracing::type.
NowIs() [2/2]
bool v8::internal::FieldType::NowIs (Tagged< FieldType > type, Tagged< FieldType > other) [static]
Definition at line 68 of file field-type.cc.
                                                                     {
  if (IsAny(other)) return true;
  if (IsNone(type)) return true;
  if (IsNone(other)) return false;
  if (IsAny(type)) return false;
  DCHECK(IsClass(type));
  DCHECK(IsClass(other));
  return type == other;
}
References v8::internal::DCHECK(), v8::internal::IsAny(), v8::internal::IsClass(), v8::internal::IsNone(), and v8::internal::tracing::type.
Referenced by v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral(), v8::internal::MapUpdater::FindSplitMap(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::MapUpdater::GeneralizeField(), v8::internal::anonymous_namespace{map-updater.cc}::GeneralizeFieldType(), NowIs(), v8::internal::MapUpdater::TryReconfigureToDataFieldInplace(), and v8::internal::Map::TryReplayPropertyTransitions().
NowStable()
bool v8::internal::FieldType::NowStable (Tagged< FieldType > type) [static]
Definition at line 63 of file field-type.cc.
                                                {
  return !IsClass(type) || AsClass(type)->is_stable();
}
References AsClass(), v8::internal::IsClass(), and v8::internal::tracing::type.
PrintTo()
void v8::internal::FieldType::PrintTo (Tagged< FieldType > type, std::ostream & os) [static]
Definition at line 94 of file field-type.cc.
                                                              {
  if (IsAny(type)) {
    os << "Any";
  } else if (IsNone(type)) {
    os << "None";
  } else {
    DCHECK(IsClass(type));
    os << "Class(" << reinterpret_cast<void*>(AsClass(type).ptr()) << ")";
  }
}
References AsClass(), v8::internal::DCHECK(), v8::internal::IsAny(), v8::internal::IsClass(), v8::internal::IsNone(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::tracing::type.
Referenced by v8::internal::DescriptorArray::PrintDescriptorDetails(), and v8::internal::anonymous_namespace{map-updater.cc}::PrintGeneralization().
Member Data Documentation
kFieldTypesCanBeClearedOnGC
constexpr bool v8::internal::FieldType::kFieldTypesCanBeClearedOnGC = true [static], [constexpr]
Definition at line 21 of file field-type.h.
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), and v8::internal::compiler::AccessInfoFactory::LookupTransition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/field-type.h
/mnt/V8SourceCode/src/objects/field-type.cc