v8::internal::HeapNumber Class Reference
#include <heap-number.h>
Classes
class BodyDescriptor
Public Member Functions
double value () const
void set_value (double value)
uint64_t value_as_bits () const
void set_value_as_bits (uint64_t bits)
V8_EXPORT_PRIVATE void HeapNumberShortPrint (std::ostream &os)
Static Public Attributes
static const uint32_t kSignMask = 0x80000000u
static const uint32_t kExponentMask = 0x7ff00000u
static const uint32_t kMantissaMask = 0xfffffu
static const int kMantissaBits = 52
static const int kExponentBits = 11
static const int kExponentBias = 1023
static const int kExponentShift = 20
static const int kInfinityOrNanExponent
static const int kMantissaBitsInTopWord = 20
static const int kNonMantissaBitsInTopWord = 12
Private Attributes
UnalignedDoubleMember value_
Friends
struct OffsetsForDebug
class CodeStubAssembler
class AccessorAssembler
class maglev::MaglevAssembler
class maglev::MaglevGraphBuilder
class compiler::AccessBuilder
class compiler::GraphAssembler
class compiler::JSContextSpecialization
class TorqueGeneratedHeapNumberAsserts
AllocationAlignment HeapObject::RequiredAlignment (InSharedSpace in_shared_space, Tagged< Map > map)
Detailed Description
Definition at line 28 of file heap-number.h.
Member Function Documentation
HeapNumberShortPrint()
void v8::internal::HeapNumber::HeapNumberShortPrint (std::ostream & os)
Definition at line 3943 of file objects-printer.cc.
                                                    {
  PrintDouble(os, value());
}
set_value()
void v8::internal::HeapNumber::set_value (double value) [inline]
Definition at line 21 of file heap-number-inl.h.
                                       {
  value_.set_value(value);
}
References v8::internal::UnalignedValueMember< T >::set_value(), value(), and value_.
set_value_as_bits()
void v8::internal::HeapNumber::set_value_as_bits (uint64_t bits) [inline]
Definition at line 27 of file heap-number-inl.h.
                                                {
  value_.set_value_as_bits(bits);
}
References v8::internal::UnalignedDoubleMember::set_value_as_bits(), and value_.
value()
double v8::internal::HeapNumber::value () const [inline]
Definition at line 20 of file heap-number-inl.h.
{ return value_.value(); }
References v8::internal::UnalignedValueMember< T >::value(), and value_.
Referenced by set_value().
value_as_bits()
uint64_t v8::internal::HeapNumber::value_as_bits () const [inline]
Definition at line 25 of file heap-number-inl.h.
{ return value_.value_as_bits(); }
References value_, and v8::internal::UnalignedDoubleMember::value_as_bits().
Friends And Related Function Documentation
AccessorAssembler
friend class AccessorAssembler [friend]
Definition at line 57 of file heap-number.h.
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 56 of file heap-number.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 60 of file heap-number.h.
compiler::GraphAssembler
friend class compiler::GraphAssembler [friend]
Definition at line 61 of file heap-number.h.
compiler::JSContextSpecialization
friend class compiler::JSContextSpecialization [friend]
Definition at line 62 of file heap-number.h.
HeapObject::RequiredAlignment
AllocationAlignment HeapObject::RequiredAlignment (InSharedSpace in_shared_space, Tagged< Map > map) [friend]
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 58 of file heap-number.h.
maglev::MaglevGraphBuilder
friend class maglev::MaglevGraphBuilder [friend]
Definition at line 59 of file heap-number.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 55 of file heap-number.h.
TorqueGeneratedHeapNumberAsserts
friend class TorqueGeneratedHeapNumberAsserts [friend]
Definition at line 63 of file heap-number.h.
Member Data Documentation
kExponentBias
const int v8::internal::HeapNumber::kExponentBias = 1023 [static]
Definition at line 41 of file heap-number.h.
kExponentBits
const int v8::internal::HeapNumber::kExponentBits = 11 [static]
Definition at line 40 of file heap-number.h.
kExponentMask
const uint32_t v8::internal::HeapNumber::kExponentMask = 0x7ff00000u [static]
Definition at line 37 of file heap-number.h.
kExponentShift
const int v8::internal::HeapNumber::kExponentShift = 20 [static]
Definition at line 42 of file heap-number.h.
kInfinityOrNanExponent
const int v8::internal::HeapNumber::kInfinityOrNanExponent [static]
Initial value:
=
      (kExponentMask >> kExponentShift) - kExponentBias
Definition at line 43 of file heap-number.h.
kMantissaBits
const int v8::internal::HeapNumber::kMantissaBits = 52 [static]
Definition at line 39 of file heap-number.h.
kMantissaBitsInTopWord
const int v8::internal::HeapNumber::kMantissaBitsInTopWord = 20 [static]
Definition at line 45 of file heap-number.h.
kMantissaMask
const uint32_t v8::internal::HeapNumber::kMantissaMask = 0xfffffu [static]
Definition at line 38 of file heap-number.h.
kNonMantissaBitsInTopWord
const int v8::internal::HeapNumber::kNonMantissaBitsInTopWord = 12 [static]
Definition at line 46 of file heap-number.h.
kSignMask
const uint32_t v8::internal::HeapNumber::kSignMask = 0x80000000u [static]
Definition at line 36 of file heap-number.h.
value_
UnalignedDoubleMember v8::internal::HeapNumber::value_ [private]
Definition at line 67 of file heap-number.h.
Referenced by set_value(), set_value_as_bits(), value(), and value_as_bits().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/heap-number.h
/mnt/V8SourceCode/src/diagnostics/objects-printer.cc
/mnt/V8SourceCode/src/objects/heap-number-inl.h