v8::internal::compiler::FlagsContinuation Class Reference
#include <instruction-selector.h>
Classes
struct ConditionalCompare
Public Types
using compare_chain_t = std::array< ConditionalCompare, kMaxCompareChainSize >
Public Member Functions
FlagsContinuation ()
bool IsNone () const
bool IsBranch () const
bool IsConditionalBranch () const
bool IsDeoptimize () const
bool IsSet () const
bool IsConditionalSet () const
bool IsTrap () const
bool IsSelect () const
FlagsCondition condition () const
FlagsCondition final_condition () const
DeoptimizeReason reason () const
uint32_t node_id () const
FeedbackSource const & feedback () const
turboshaft::OpIndex frame_state () const
turboshaft::OpIndex result () const
TrapId trap_id () const
turboshaft::Block * true_block () const
turboshaft::Block * false_block () const
BranchHint hint () const
turboshaft::OpIndex true_value () const
turboshaft::OpIndex false_value () const
const compare_chain_t & compares () const
uint32_t num_conditional_compares () const
void Negate ()
void Commute ()
void Overwrite (FlagsCondition condition)
void OverwriteAndNegateIfEqual (FlagsCondition condition)
void OverwriteUnsignedIfSigned ()
InstructionCode Encode (InstructionCode opcode)
Static Public Member Functions
static FlagsContinuation ForBranch (FlagsCondition condition, turboshaft::Block *true_block, turboshaft::Block *false_block)
static FlagsContinuation ForHintedBranch (FlagsCondition condition, turboshaft::Block *true_block, turboshaft::Block *false_block, BranchHint hint)
static FlagsContinuation ForConditionalBranch (compare_chain_t &compares, uint32_t num_conditional_compares, FlagsCondition branch_condition, turboshaft::Block *true_block, turboshaft::Block *false_block)
static FlagsContinuation ForDeoptimize (FlagsCondition condition, DeoptimizeReason reason, uint32_t node_id, FeedbackSource const &feedback, turboshaft::OpIndex frame_state)
static FlagsContinuation ForDeoptimizeForTesting (FlagsCondition condition, DeoptimizeReason reason, uint32_t node_id, FeedbackSource const &feedback, turboshaft::OpIndex frame_state)
static FlagsContinuation ForSet (FlagsCondition condition, turboshaft::OpIndex result)
static FlagsContinuation ForConditionalSet (compare_chain_t &compares, uint32_t num_conditional_compares, FlagsCondition set_condition, turboshaft::OpIndex result)
static FlagsContinuation ForTrap (FlagsCondition condition, TrapId trap_id)
static FlagsContinuation ForSelect (FlagsCondition condition, turboshaft::OpIndex result, turboshaft::OpIndex true_value, turboshaft::OpIndex false_value)
Static Public Attributes
static constexpr size_t kMaxCompareChainSize = 4
Private Member Functions
FlagsContinuation (FlagsMode mode, FlagsCondition condition, turboshaft::Block *true_block, turboshaft::Block *false_block)
FlagsContinuation (FlagsMode mode, FlagsCondition condition, turboshaft::Block *true_block, turboshaft::Block *false_block, BranchHint hint)
FlagsContinuation (compare_chain_t &compares, uint32_t num_conditional_compares, FlagsCondition branch_condition, turboshaft::Block *true_block, turboshaft::Block *false_block)
FlagsContinuation (FlagsMode mode, FlagsCondition condition, DeoptimizeReason reason, uint32_t node_id, FeedbackSource const &feedback, turboshaft::OpIndex frame_state)
FlagsContinuation (FlagsCondition condition, turboshaft::OpIndex result)
FlagsContinuation (compare_chain_t &compares, uint32_t num_conditional_compares, FlagsCondition set_condition, turboshaft::OpIndex result)
FlagsContinuation (FlagsCondition condition, TrapId trap_id)
FlagsContinuation (FlagsCondition condition, turboshaft::OpIndex result, turboshaft::OpIndex true_value, turboshaft::OpIndex false_value)
Private Attributes
FlagsMode const mode_
FlagsCondition condition_
FlagsCondition final_condition_
uint32_t num_conditional_compares_
compare_chain_t compares_
DeoptimizeReason reason_
uint32_t node_id_
FeedbackSource feedback_
turboshaft::OpIndex frame_state_or_result_
turboshaft::Block * true_block_
turboshaft::Block * false_block_
TrapId trap_id_
turboshaft::OpIndex true_value_
turboshaft::OpIndex false_value_
BranchHint hint_ = BranchHint::kNone
Detailed Description
Definition at line 53 of file instruction-selector.h.
Member Typedef Documentation
compare_chain_t
using v8::internal::compiler::FlagsContinuation::compare_chain_t = std::array<ConditionalCompare, kMaxCompareChainSize>
Definition at line 65 of file instruction-selector.h.
Constructor & Destructor Documentation
FlagsContinuation() [1/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation () [inline]
Definition at line 67 of file instruction-selector.h.
: mode_(kFlags_none) {}
Referenced by ForBranch(), ForConditionalBranch(), ForConditionalSet(), ForDeoptimize(), ForDeoptimizeForTesting(), ForHintedBranch(), ForSelect(), ForSet(), and ForTrap().
FlagsContinuation() [2/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation (FlagsMode mode, FlagsCondition condition, turboshaft::Block * true_block, turboshaft::Block * false_block) [inline], [private]
Definition at line 266 of file instruction-selector.h.
      : mode_(mode),
        condition_(condition),
        true_block_(true_block),
        false_block_(false_block) {
    DCHECK(mode == kFlags_branch);
    DCHECK_NOT_NULL(true_block);
    DCHECK_NOT_NULL(false_block);
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, false_block(), v8::internal::compiler::kFlags_branch, mode(), and true_block().
FlagsContinuation() [3/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation (FlagsMode mode, FlagsCondition condition, turboshaft::Block * true_block, turboshaft::Block * false_block, BranchHint hint) [inline], [private]
Definition at line 278 of file instruction-selector.h.
      : mode_(mode),
        condition_(condition),
        true_block_(true_block),
        false_block_(false_block),
        hint_(hint) {
    DCHECK_EQ(mode, kFlags_branch);
    DCHECK_NOT_NULL(true_block);
    DCHECK_NOT_NULL(false_block);
  }
References DCHECK_EQ, DCHECK_NOT_NULL, false_block(), v8::internal::compiler::kFlags_branch, mode(), and true_block().
FlagsContinuation() [4/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation (compare_chain_t & compares, uint32_t num_conditional_compares, FlagsCondition branch_condition, turboshaft::Block * true_block, turboshaft::Block * false_block) [inline], [private]
Definition at line 291 of file instruction-selector.h.
      : mode_(kFlags_conditional_branch),
        condition_(compares.front().compare_condition),
        final_condition_(branch_condition),
        num_conditional_compares_(num_conditional_compares),
        compares_(compares),
        true_block_(true_block),
        false_block_(false_block) {
    DCHECK_NOT_NULL(true_block);
    DCHECK_NOT_NULL(false_block);
  }
References DCHECK_NOT_NULL, false_block(), and true_block().
FlagsContinuation() [5/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation (FlagsMode mode, FlagsCondition condition, DeoptimizeReason reason, uint32_t node_id, FeedbackSource const & feedback, turboshaft::OpIndex frame_state) [inline], [private]
Definition at line 307 of file instruction-selector.h.
      : mode_(mode),
        condition_(condition),
        reason_(reason),
        node_id_(node_id),
        feedback_(feedback),
        frame_state_or_result_(frame_state) {
    DCHECK(mode == kFlags_deoptimize);
    DCHECK(frame_state.valid());
  }
References v8::internal::DCHECK(), frame_state(), v8::internal::compiler::kFlags_deoptimize, mode(), and v8::internal::compiler::turboshaft::OpIndex::valid().
FlagsContinuation() [6/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation (FlagsCondition condition, turboshaft::OpIndex result) [inline], [private]
Definition at line 321 of file instruction-selector.h.
      : mode_(kFlags_set),
        condition_(condition),
        frame_state_or_result_(result) {
    DCHECK(result.valid());
  }
References v8::internal::DCHECK(), result(), and v8::internal::compiler::turboshaft::OpIndex::valid().
FlagsContinuation() [7/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation (compare_chain_t & compares, uint32_t num_conditional_compares, FlagsCondition set_condition, turboshaft::OpIndex result) [inline], [private]
Definition at line 328 of file instruction-selector.h.
      : mode_(kFlags_conditional_set),
        condition_(compares.front().compare_condition),
        final_condition_(set_condition),
        num_conditional_compares_(num_conditional_compares),
        compares_(compares),
        frame_state_or_result_(result) {
    DCHECK(result.valid());
  }
References v8::internal::DCHECK(), result(), and v8::internal::compiler::turboshaft::OpIndex::valid().
FlagsContinuation() [8/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation (FlagsCondition condition, TrapId trap_id) [inline], [private]
Definition at line 340 of file instruction-selector.h.
      : mode_(kFlags_trap), condition_(condition), trap_id_(trap_id) {}
FlagsContinuation() [9/9]
v8::internal::compiler::FlagsContinuation::FlagsContinuation (FlagsCondition condition, turboshaft::OpIndex result, turboshaft::OpIndex true_value, turboshaft::OpIndex false_value) [inline], [private]
Definition at line 343 of file instruction-selector.h.
      : mode_(kFlags_select),
        condition_(condition),
        frame_state_or_result_(result),
        true_value_(true_value),
        false_value_(false_value) {
    DCHECK(result.valid());
    DCHECK(true_value.valid());
    DCHECK(false_value.valid());
  }
References v8::internal::DCHECK(), false_value(), result(), true_value(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Member Function Documentation
Commute()
void v8::internal::compiler::FlagsContinuation::Commute () [inline]
Definition at line 217 of file instruction-selector.h.
                 {
    DCHECK(!IsNone());
    DCHECK(!IsConditionalSet() && !IsConditionalBranch());
    condition_ = CommuteFlagsCondition(condition_);
  }
References v8::internal::compiler::CommuteFlagsCondition(), condition_, v8::internal::DCHECK(), IsConditionalBranch(), IsConditionalSet(), and IsNone().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat32Compare(), v8::internal::compiler::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare(), v8::internal::compiler::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
compares()
const compare_chain_t& v8::internal::compiler::FlagsContinuation::compares () const [inline]
Definition at line 202 of file instruction-selector.h.
                                          {
    DCHECK(IsConditionalSet() || IsConditionalBranch());
    return compares_;
  }
References compares_, v8::internal::DCHECK(), IsConditionalBranch(), and IsConditionalSet().
Referenced by ForConditionalBranch(), ForConditionalSet(), and v8::internal::compiler::turboshaft::VisitCompareChain().
condition()
FlagsCondition v8::internal::compiler::FlagsContinuation::condition () const [inline]
Definition at line 150 of file instruction-selector.h.
                                   {
    DCHECK(!IsNone());
    return condition_;
  }
References condition_, v8::internal::DCHECK(), and IsNone().
Referenced by v8::internal::compiler::CompareLogical(), ForBranch(), ForDeoptimize(), ForDeoptimizeForTesting(), ForHintedBranch(), ForSelect(), ForSet(), ForTrap(), Overwrite(), OverwriteAndNegateIfEqual(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare(), v8::internal::compiler::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare().
Encode()
InstructionCode v8::internal::compiler::FlagsContinuation::Encode (InstructionCode opcode) [inline]
Definition at line 257 of file instruction-selector.h.
                                                 {
    opcode |= FlagsModeField::encode(mode_);
    if (mode_ != kFlags_none) {
      opcode |= FlagsConditionField::encode(condition_);
    }
    return opcode;
  }
References condition_, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::kFlags_none, and mode_.
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation().
false_block()
turboshaft::Block* v8::internal::compiler::FlagsContinuation::false_block () const [inline]
Definition at line 186 of file instruction-selector.h.
                                       {
    DCHECK(IsBranch() || IsConditionalBranch());
    return false_block_;
  }
References v8::internal::DCHECK(), false_block_, IsBranch(), and IsConditionalBranch().
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), FlagsContinuation(), ForBranch(), ForConditionalBranch(), ForHintedBranch(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch().
false_value()
turboshaft::OpIndex v8::internal::compiler::FlagsContinuation::false_value () const [inline]
Definition at line 198 of file instruction-selector.h.
                                        {
    DCHECK(IsSelect());
    return false_value_;
  }
References v8::internal::DCHECK(), false_value_, and IsSelect().
Referenced by FlagsContinuation(), ForSelect(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand().
feedback()
FeedbackSource const& v8::internal::compiler::FlagsContinuation::feedback () const [inline]
Definition at line 166 of file instruction-selector.h.
                                         {
    DCHECK(IsDeoptimize());
    return feedback_;
  }
References v8::internal::DCHECK(), feedback_, and IsDeoptimize().
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), ForDeoptimize(), and ForDeoptimizeForTesting().
final_condition()
FlagsCondition v8::internal::compiler::FlagsContinuation::final_condition () const [inline]
Definition at line 154 of file instruction-selector.h.
                                         {
    DCHECK(IsConditionalSet() || IsConditionalBranch());
    return final_condition_;
  }
References v8::internal::DCHECK(), final_condition_, IsConditionalBranch(), and IsConditionalSet().
Referenced by v8::internal::compiler::turboshaft::VisitCompareChain().
ForBranch()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForBranch (FlagsCondition condition, turboshaft::Block * true_block, turboshaft::Block * false_block) [inline], [static]
Definition at line 71 of file instruction-selector.h.
                                                                   {
    return FlagsContinuation(kFlags_branch, condition, true_block, false_block);
  }
References condition(), false_block(), FlagsContinuation(), v8::internal::compiler::kFlags_branch, and true_block().
Referenced by v8::internal::compiler::InstructionSelector::VisitBranch().
ForConditionalBranch()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForConditionalBranch (compare_chain_t & compares, uint32_t num_conditional_compares, FlagsCondition branch_condition, turboshaft::Block * true_block, turboshaft::Block * false_block) [inline], [static]
Definition at line 87 of file instruction-selector.h.
                                    {
    return FlagsContinuation(compares, num_conditional_compares,
                             branch_condition, true_block, false_block);
  }
References compares(), false_block(), FlagsContinuation(), num_conditional_compares(), and true_block().
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch().
ForConditionalSet()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForConditionalSet (compare_chain_t & compares, uint32_t num_conditional_compares, FlagsCondition set_condition, turboshaft::OpIndex result) [inline], [static]
Definition at line 120 of file instruction-selector.h.
                                                                       {
    return FlagsContinuation(compares, num_conditional_compares, set_condition,
                             result);
  }
References compares(), FlagsContinuation(), num_conditional_compares(), and result().
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet().
ForDeoptimize()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForDeoptimize (FlagsCondition condition, DeoptimizeReason reason, uint32_t node_id, FeedbackSource const & feedback, turboshaft::OpIndex frame_state) [inline], [static]
Definition at line 96 of file instruction-selector.h.
                                                                        {
    return FlagsContinuation(kFlags_deoptimize, condition, reason, node_id,
                             feedback, frame_state);
  }
References condition(), feedback(), FlagsContinuation(), frame_state(), v8::internal::compiler::kFlags_deoptimize, node_id(), and reason().
Referenced by v8::internal::compiler::InstructionSelector::VisitDeoptimizeIf().
ForDeoptimizeForTesting()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForDeoptimizeForTesting (FlagsCondition condition, DeoptimizeReason reason, uint32_t node_id, FeedbackSource const & feedback, turboshaft::OpIndex frame_state) [inline], [static]
Definition at line 104 of file instruction-selector.h.
                                                                     {
    // test-instruction-scheduler.cc passes a dummy Node* as frame_state.
    // Contents don't matter as long as it's not nullptr.
    return FlagsContinuation(kFlags_deoptimize, condition, reason, node_id,
                             feedback, frame_state);
  }
References condition(), feedback(), FlagsContinuation(), frame_state(), v8::internal::compiler::kFlags_deoptimize, node_id(), and reason().
ForHintedBranch()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForHintedBranch (FlagsCondition condition, turboshaft::Block * true_block, turboshaft::Block * false_block, BranchHint hint) [inline], [static]
Definition at line 77 of file instruction-selector.h.
                                                            {
    return FlagsContinuation(kFlags_branch, condition, true_block, false_block,
                             hint);
  }
References condition(), false_block(), FlagsContinuation(), hint(), v8::internal::compiler::kFlags_branch, and true_block().
Referenced by v8::internal::compiler::InstructionSelector::VisitBranch().
ForSelect()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForSelect (FlagsCondition condition, turboshaft::OpIndex result, turboshaft::OpIndex true_value, turboshaft::OpIndex false_value) [inline], [static]
Definition at line 133 of file instruction-selector.h.
                                                                    {
    return FlagsContinuation(condition, result, true_value, false_value);
  }
References condition(), false_value(), FlagsContinuation(), result(), and true_value().
Referenced by v8::internal::compiler::InstructionSelector::VisitSelect().
ForSet()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForSet (FlagsCondition condition, turboshaft::OpIndex result) [inline], [static]
Definition at line 114 of file instruction-selector.h.
                                                            {
    return FlagsContinuation(condition, result);
  }
References condition(), FlagsContinuation(), and result().
Referenced by v8::internal::compiler::TryMatchInt32MulWithOverflow(), v8::internal::compiler::TryMatchInt32OpWithOverflow(), and v8::internal::compiler::TryMatchInt64OpWithOverflow().
ForTrap()
static FlagsContinuation v8::internal::compiler::FlagsContinuation::ForTrap (FlagsCondition condition, TrapId trap_id) [inline], [static]
Definition at line 129 of file instruction-selector.h.
                                                                             {
    return FlagsContinuation(condition, trap_id);
  }
References condition(), FlagsContinuation(), and trap_id().
Referenced by v8::internal::compiler::InstructionSelector::VisitTrapIf().
frame_state()
turboshaft::OpIndex v8::internal::compiler::FlagsContinuation::frame_state () const [inline]
Definition at line 170 of file instruction-selector.h.
                                        {
    DCHECK(IsDeoptimize());
    return frame_state_or_result_;
  }
References v8::internal::DCHECK(), frame_state_or_result_, and IsDeoptimize().
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), FlagsContinuation(), ForDeoptimize(), and ForDeoptimizeForTesting().
hint()
BranchHint v8::internal::compiler::FlagsContinuation::hint () const [inline]
Definition at line 190 of file instruction-selector.h.
                          {
    DCHECK(IsBranch());
    return hint_;
  }
References v8::internal::DCHECK(), hint_, and IsBranch().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitBranchOrDeoptimize(), ForHintedBranch(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl().
IsBranch()
bool v8::internal::compiler::FlagsContinuation::IsBranch () const [inline]
Definition at line 141 of file instruction-selector.h.
{ return mode_ == kFlags_branch; }
References v8::internal::compiler::kFlags_branch, and mode_.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitBranchOrDeoptimize(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), false_block(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), hint(), true_block(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero().
IsConditionalBranch()
bool v8::internal::compiler::FlagsContinuation::IsConditionalBranch () const [inline]
Definition at line 142 of file instruction-selector.h.
                                   {
    return mode_ == kFlags_conditional_branch;
  }
References v8::internal::compiler::kFlags_conditional_branch, and mode_.
Referenced by Commute(), compares(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), false_block(), final_condition(), Negate(), num_conditional_compares(), Overwrite(), OverwriteAndNegateIfEqual(), OverwriteUnsignedIfSigned(), true_block(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), and v8::internal::compiler::turboshaft::VisitCompareChain().
IsConditionalSet()
bool v8::internal::compiler::FlagsContinuation::IsConditionalSet () const [inline]
Definition at line 147 of file instruction-selector.h.
{ return mode_ == kFlags_conditional_set; }
References v8::internal::compiler::kFlags_conditional_set, and mode_.
Referenced by Commute(), compares(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), final_condition(), Negate(), num_conditional_compares(), Overwrite(), OverwriteAndNegateIfEqual(), OverwriteUnsignedIfSigned(), result(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), and v8::internal::compiler::turboshaft::VisitCompareChain().
IsDeoptimize()
bool v8::internal::compiler::FlagsContinuation::IsDeoptimize () const [inline]
Definition at line 145 of file instruction-selector.h.
{ return mode_ == kFlags_deoptimize; }
References v8::internal::compiler::kFlags_deoptimize, and mode_.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitBranchOrDeoptimize(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), feedback(), frame_state(), node_id(), reason(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare().
IsNone()
bool v8::internal::compiler::FlagsContinuation::IsNone () const [inline]
Definition at line 140 of file instruction-selector.h.
{ return mode_ == kFlags_none; }
References v8::internal::compiler::kFlags_none, and mode_.
Referenced by Commute(), condition(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), and Negate().
IsSelect()
bool v8::internal::compiler::FlagsContinuation::IsSelect () const [inline]
Definition at line 149 of file instruction-selector.h.
{ return mode_ == kFlags_select; }
References v8::internal::compiler::kFlags_select, and mode_.
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), false_value(), result(), true_value(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand().
IsSet()
bool v8::internal::compiler::FlagsContinuation::IsSet () const [inline]
Definition at line 146 of file instruction-selector.h.
{ return mode_ == kFlags_set; }
References v8::internal::compiler::kFlags_set, and mode_.
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), result(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare(), and v8::internal::compiler::VisitWordCompare().
IsTrap()
bool v8::internal::compiler::FlagsContinuation::IsTrap () const [inline]
Definition at line 148 of file instruction-selector.h.
{ return mode_ == kFlags_trap; }
References v8::internal::compiler::kFlags_trap, and mode_.
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), and trap_id().
Negate()
void v8::internal::compiler::FlagsContinuation::Negate () [inline]
Definition at line 211 of file instruction-selector.h.
                {
    DCHECK(!IsNone());
    DCHECK(!IsConditionalSet() && !IsConditionalBranch());
    condition_ = NegateFlagsCondition(condition_);
  }
References condition_, v8::internal::DCHECK(), IsConditionalBranch(), IsConditionalSet(), IsNone(), and v8::internal::compiler::NegateFlagsCondition().
Referenced by v8::internal::compiler::InstructionSelector::ConsumeEqualZero(), OverwriteAndNegateIfEqual(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand().
node_id()
uint32_t v8::internal::compiler::FlagsContinuation::node_id () const [inline]
Definition at line 162 of file instruction-selector.h.
                           {
    DCHECK(IsDeoptimize());
    return node_id_;
  }
References v8::internal::DCHECK(), IsDeoptimize(), and node_id_.
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), ForDeoptimize(), and ForDeoptimizeForTesting().
num_conditional_compares()
uint32_t v8::internal::compiler::FlagsContinuation::num_conditional_compares () const [inline]
Definition at line 206 of file instruction-selector.h.
                                            {
    DCHECK(IsConditionalSet() || IsConditionalBranch());
    return num_conditional_compares_;
  }
References v8::internal::DCHECK(), IsConditionalBranch(), IsConditionalSet(), and num_conditional_compares_.
Referenced by ForConditionalBranch(), ForConditionalSet(), and v8::internal::compiler::turboshaft::VisitCompareChain().
Overwrite()
void v8::internal::compiler::FlagsContinuation::Overwrite (FlagsCondition condition) [inline]
Definition at line 223 of file instruction-selector.h.
                                           {
    DCHECK(!IsConditionalSet() && !IsConditionalBranch());
    condition_ = condition;
  }
References condition(), condition_, v8::internal::DCHECK(), IsConditionalBranch(), and IsConditionalSet().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz().
OverwriteAndNegateIfEqual()
void v8::internal::compiler::FlagsContinuation::OverwriteAndNegateIfEqual (FlagsCondition condition) [inline]
Definition at line 228 of file instruction-selector.h.
                                                           {
    DCHECK(condition_ == kEqual || condition_ == kNotEqual);
    DCHECK(!IsConditionalSet() && !IsConditionalBranch());
    bool negate = condition_ == kEqual;
    condition_ = condition;
    if (negate) Negate();
  }
References condition(), condition_, v8::internal::DCHECK(), IsConditionalBranch(), IsConditionalSet(), v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, and Negate().
Referenced by v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
OverwriteUnsignedIfSigned()
void v8::internal::compiler::FlagsContinuation::OverwriteUnsignedIfSigned () [inline]
Definition at line 236 of file instruction-selector.h.
                                   {
    DCHECK(!IsConditionalSet() && !IsConditionalBranch());
    switch (condition_) {
      case kSignedLessThan:
        condition_ = kUnsignedLessThan;
        break;
      case kSignedLessThanOrEqual:
        condition_ = kUnsignedLessThanOrEqual;
        break;
      case kSignedGreaterThan:
        condition_ = kUnsignedGreaterThan;
        break;
      case kSignedGreaterThanOrEqual:
        condition_ = kUnsignedGreaterThanOrEqual;
        break;
      default:
        break;
    }
  }
References condition_, v8::internal::DCHECK(), IsConditionalBranch(), IsConditionalSet(), v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, and v8::internal::compiler::kUnsignedLessThanOrEqual.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryNarrowOpcodeSize(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryNarrowOpcodeSize().
reason()
DeoptimizeReason v8::internal::compiler::FlagsContinuation::reason () const [inline]
Definition at line 158 of file instruction-selector.h.
                                  {
    DCHECK(IsDeoptimize());
    return reason_;
  }
References v8::internal::DCHECK(), IsDeoptimize(), and reason_.
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), ForDeoptimize(), and ForDeoptimizeForTesting().
result()
turboshaft::OpIndex v8::internal::compiler::FlagsContinuation::result () const [inline]
Definition at line 174 of file instruction-selector.h.
                                   {
    DCHECK(IsSet() || IsConditionalSet() || IsSelect());
    return frame_state_or_result_;
  }
References v8::internal::DCHECK(), frame_state_or_result_, IsConditionalSet(), IsSelect(), and IsSet().
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), FlagsContinuation(), ForConditionalSet(), ForSelect(), and ForSet().
trap_id()
TrapId v8::internal::compiler::FlagsContinuation::trap_id () const [inline]
Definition at line 178 of file instruction-selector.h.
                         {
    DCHECK(IsTrap());
    return trap_id_;
  }
References v8::internal::DCHECK(), IsTrap(), and trap_id_.
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), and ForTrap().
true_block()
turboshaft::Block* v8::internal::compiler::FlagsContinuation::true_block () const [inline]
Definition at line 182 of file instruction-selector.h.
                                      {
    DCHECK(IsBranch() || IsConditionalBranch());
    return true_block_;
  }
References v8::internal::DCHECK(), IsBranch(), IsConditionalBranch(), and true_block_.
Referenced by v8::internal::compiler::InstructionSelector::EmitWithContinuation(), FlagsContinuation(), ForBranch(), ForConditionalBranch(), ForHintedBranch(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch().
true_value()
turboshaft::OpIndex v8::internal::compiler::FlagsContinuation::true_value () const [inline]
Definition at line 194 of file instruction-selector.h.
                                       {
    DCHECK(IsSelect());
    return true_value_;
  }
References v8::internal::DCHECK(), IsSelect(), and true_value_.
Referenced by FlagsContinuation(), ForSelect(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand().
Member Data Documentation
compares_
compare_chain_t v8::internal::compiler::FlagsContinuation::compares_ [private]
Definition at line 362 of file instruction-selector.h.
Referenced by compares().
condition_
FlagsCondition v8::internal::compiler::FlagsContinuation::condition_ [private]
Definition at line 357 of file instruction-selector.h.
Referenced by Commute(), condition(), Encode(), Negate(), Overwrite(), OverwriteAndNegateIfEqual(), and OverwriteUnsignedIfSigned().
false_block_
turboshaft::Block* v8::internal::compiler::FlagsContinuation::false_block_ [private]
Definition at line 370 of file instruction-selector.h.
Referenced by false_block().
false_value_
turboshaft::OpIndex v8::internal::compiler::FlagsContinuation::false_value_ [private]
Definition at line 373 of file instruction-selector.h.
Referenced by false_value().
feedback_
FeedbackSource v8::internal::compiler::FlagsContinuation::feedback_ [private]
Definition at line 365 of file instruction-selector.h.
Referenced by feedback().
final_condition_
FlagsCondition v8::internal::compiler::FlagsContinuation::final_condition_ [private]
Definition at line 358 of file instruction-selector.h.
Referenced by final_condition().
frame_state_or_result_
turboshaft::OpIndex v8::internal::compiler::FlagsContinuation::frame_state_or_result_ [private]
Definition at line 367 of file instruction-selector.h.
Referenced by frame_state(), and result().
hint_
BranchHint v8::internal::compiler::FlagsContinuation::hint_ = BranchHint::kNone [private]
Definition at line 374 of file instruction-selector.h.
Referenced by hint().
kMaxCompareChainSize
constexpr size_t v8::internal::compiler::FlagsContinuation::kMaxCompareChainSize = 4 [static], [constexpr]
Definition at line 64 of file instruction-selector.h.
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainShared(), and v8::internal::compiler::turboshaft::VisitCompareChain().
mode_
FlagsMode const v8::internal::compiler::FlagsContinuation::mode_ [private]
Definition at line 356 of file instruction-selector.h.
Referenced by Encode(), IsBranch(), IsConditionalBranch(), IsConditionalSet(), IsDeoptimize(), IsNone(), IsSelect(), IsSet(), and IsTrap().
node_id_
uint32_t v8::internal::compiler::FlagsContinuation::node_id_ [private]
Definition at line 364 of file instruction-selector.h.
Referenced by node_id().
num_conditional_compares_
uint32_t v8::internal::compiler::FlagsContinuation::num_conditional_compares_ [private]
Definition at line 360 of file instruction-selector.h.
Referenced by num_conditional_compares().
reason_
DeoptimizeReason v8::internal::compiler::FlagsContinuation::reason_ [private]
Definition at line 363 of file instruction-selector.h.
Referenced by reason().
trap_id_
TrapId v8::internal::compiler::FlagsContinuation::trap_id_ [private]
Definition at line 371 of file instruction-selector.h.
Referenced by trap_id().
true_block_
turboshaft::Block* v8::internal::compiler::FlagsContinuation::true_block_ [private]
Definition at line 369 of file instruction-selector.h.
Referenced by true_block().
true_value_
turboshaft::OpIndex v8::internal::compiler::FlagsContinuation::true_value_ [private]
Definition at line 372 of file instruction-selector.h.
Referenced by true_value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction-selector.h