v8::internal::FixedLengthLoopState Class Reference
#include <regexp-compiler.h>
Public Member Functions
FixedLengthLoopState (bool not_at_start, ChoiceNode *loop_choice_node)
void BindStepBackwardsLabel (RegExpMacroAssembler *macro_assembler)
void BindLoopTopLabel (RegExpMacroAssembler *macro_assembler)
void GoToLoopTopLabel (RegExpMacroAssembler *macro_assembler)
ChoiceNode * loop_choice_node () const
Trace * counter_backtrack_trace ()
Private Attributes
Label step_backwards_label_
Label loop_top_label_
ChoiceNode * loop_choice_node_
Trace counter_backtrack_trace_
Detailed Description
Definition at line 385 of file regexp-compiler.h.
Constructor & Destructor Documentation
FixedLengthLoopState()
v8::internal::FixedLengthLoopState::FixedLengthLoopState (bool not_at_start, ChoiceNode * loop_choice_node) [explicit]
Definition at line 3156 of file regexp-compiler.cc.
    : loop_choice_node_(loop_choice_node) {
  counter_backtrack_trace_.set_backtrack(&step_backwards_label_);
  if (not_at_start) counter_backtrack_trace_.set_at_start(Trace::FALSE_VALUE);
}
References counter_backtrack_trace_, v8::internal::Trace::FALSE_VALUE, v8::internal::Trace::set_at_start(), v8::internal::Trace::set_backtrack(), and step_backwards_label_.
Member Function Documentation
BindLoopTopLabel()
void v8::internal::FixedLengthLoopState::BindLoopTopLabel (RegExpMacroAssembler * macro_assembler)
Definition at line 3168 of file regexp-compiler.cc.
                                           {
  macro_assembler->Bind(&loop_top_label_);
}
References v8::internal::RegExpMacroAssembler::Bind(), and loop_top_label_.
Referenced by v8::internal::ChoiceNode::EmitFixedLengthLoop().
BindStepBackwardsLabel()
void v8::internal::FixedLengthLoopState::BindStepBackwardsLabel (RegExpMacroAssembler * macro_assembler)
Definition at line 3163 of file regexp-compiler.cc.
                                           {
  macro_assembler->Bind(&step_backwards_label_);
}
References v8::internal::RegExpMacroAssembler::Bind(), and step_backwards_label_.
Referenced by v8::internal::ChoiceNode::EmitFixedLengthLoop().
counter_backtrack_trace()
Trace* v8::internal::FixedLengthLoopState::counter_backtrack_trace () [inline]
Definition at line 394 of file regexp-compiler.h.
{ return &counter_backtrack_trace_; }
References counter_backtrack_trace_.
Referenced by v8::internal::ChoiceNode::EmitFixedLengthLoop().
GoToLoopTopLabel()
void v8::internal::FixedLengthLoopState::GoToLoopTopLabel (RegExpMacroAssembler * macro_assembler)
Definition at line 3173 of file regexp-compiler.cc.
                                           {
  macro_assembler->GoTo(&loop_top_label_);
}
References v8::internal::RegExpMacroAssembler::GoTo(), and loop_top_label_.
Referenced by v8::internal::LoopChoiceNode::Emit().
loop_choice_node()
ChoiceNode* v8::internal::FixedLengthLoopState::loop_choice_node () const [inline]
Definition at line 393 of file regexp-compiler.h.
{ return loop_choice_node_; }
References loop_choice_node_.
Referenced by v8::internal::LoopChoiceNode::Emit().
Member Data Documentation
counter_backtrack_trace_
Trace v8::internal::FixedLengthLoopState::counter_backtrack_trace_ [private]
Definition at line 400 of file regexp-compiler.h.
Referenced by counter_backtrack_trace(), and FixedLengthLoopState().
loop_choice_node_
ChoiceNode* v8::internal::FixedLengthLoopState::loop_choice_node_ [private]
Definition at line 399 of file regexp-compiler.h.
Referenced by loop_choice_node().
loop_top_label_
Label v8::internal::FixedLengthLoopState::loop_top_label_ [private]
Definition at line 398 of file regexp-compiler.h.
Referenced by BindLoopTopLabel(), and GoToLoopTopLabel().
step_backwards_label_
Label v8::internal::FixedLengthLoopState::step_backwards_label_ [private]
Definition at line 397 of file regexp-compiler.h.
Referenced by BindStepBackwardsLabel(), and FixedLengthLoopState().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc