v8::internal::InstructionBase Class Reference
#include <constants-loong64.h>
Public Types
enum Type {
kOp6Type
, kOp7Type
, kOp8Type
, kOp10Type
,
kOp12Type
, kOp14Type
, kOp17Type
, kOp22Type
,
kUnsupported = -1
, kRegisterType
, kImmediateType
, kJumpType
,
kUnsupported = -1
, kRType
, kR4Type
, kIType
,
kSType
, kBType
, kUType
, kJType
,
kCRType
, kCIType
, kCSSType
, kCIWType
,
kCLType
, kCSType
, kCAType
, kCBType
,
kCJType
, kVType
, kVLType
, kVSType
,
kVAMOType
, kVIVVType
, kVFVVType
, kVMVVType
,
kVIVIType
, kVIVXType
, kVFVFType
, kVMVXType
,
kVSETType
, kUnsupported = -1
 }
enum { kPCReadOffset = 0
 }
enum Type {
kOp6Type
, kOp7Type
, kOp8Type
, kOp10Type
,
kOp12Type
, kOp14Type
, kOp17Type
, kOp22Type
,
kUnsupported = -1
, kRegisterType
, kImmediateType
, kJumpType
,
kUnsupported = -1
, kRType
, kR4Type
, kIType
,
kSType
, kBType
, kUType
, kJType
,
kCRType
, kCIType
, kCSSType
, kCIWType
,
kCLType
, kCSType
, kCAType
, kCBType
,
kCJType
, kVType
, kVLType
, kVSType
,
kVAMOType
, kVIVVType
, kVFVVType
, kVMVVType
,
kVIVIType
, kVIVXType
, kVFVFType
, kVMVXType
,
kVSETType
, kUnsupported = -1
 }
enum { kPCReadOffset = 0
 }
enum Type {
kOp6Type
, kOp7Type
, kOp8Type
, kOp10Type
,
kOp12Type
, kOp14Type
, kOp17Type
, kOp22Type
,
kUnsupported = -1
, kRegisterType
, kImmediateType
, kJumpType
,
kUnsupported = -1
, kRType
, kR4Type
, kIType
,
kSType
, kBType
, kUType
, kJType
,
kCRType
, kCIType
, kCSSType
, kCIWType
,
kCLType
, kCSType
, kCAType
, kCBType
,
kCJType
, kVType
, kVLType
, kVSType
,
kVAMOType
, kVIVVType
, kVFVVType
, kVMVVType
,
kVIVIType
, kVIVXType
, kVFVFType
, kVMVXType
,
kVSETType
, kUnsupported = -1
 }
Public Member Functions
Instr InstructionBits () const
V8_EXPORT_PRIVATE void SetInstructionBits (Instr new_instr, WritableJitAllocation *jit_allocation=nullptr)
int Bit (int nr) const
int Bits (int hi, int lo) const
int RjFieldRawNoAssert () const
Type InstructionType () const
Instr InstructionBits () const
V8_EXPORT_PRIVATE void SetInstructionBits (Instr new_instr, WritableJitAllocation *jit_allocation=nullptr)
int Bit (int nr) const
int Bits (int hi, int lo) const
Opcode OpcodeValue () const
int FunctionFieldRaw () const
Opcode OpcodeFieldRaw () const
int RsFieldRawNoAssert () const
int SaFieldRaw () const
Type InstructionType () const
MSAMinorOpcode MSAMinorOpcodeField () const
bool IsIllegalInstruction () const
bool IsShortInstruction () const
uint8_t InstructionSize () const
Instr InstructionBits () const
void SetInstructionBits (Instr value)
int Bit (int nr) const
int Bits (int hi, int lo) const
BaseOpcode BaseOpcodeValue () const
BaseOpcode BaseOpcodeFieldRaw () const
int Funct7FieldRaw () const
int Funct6FieldRaw () const
int Funct3FieldRaw () const
int Rs1FieldRawNoAssert () const
int Rs2FieldRawNoAssert () const
int Rs3FieldRawNoAssert () const
int32_t ITypeBits () const
int32_t InstructionOpcodeType () const
Type InstructionType () const
Static Public Attributes
static constexpr uint64_t kOpcodeImmediateTypeMask
static const uint64_t kFunctionFieldRegisterTypeMask
Protected Member Functions
InstructionBase ()
InstructionBase ()
InstructionBase ()
Detailed Description
Definition at line 720 of file constants-loong64.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kPCReadOffset
Definition at line 1287 of file constants-mips64.h.
       {
    // On MIPS PC cannot actually be directly accessed. We behave as if PC was
    // always the value of the current instruction being executed.
    kPCReadOffset = 0
  };
anonymous enum
anonymous enum
Enumerator
kPCReadOffset
Definition at line 683 of file base-constants-riscv.h.
       {
    // On RISC-V, PC cannot actually be directly accessed. We behave as if PC
    // was always the value of the current instruction being executed.
    kPCReadOffset = 0
  };
Type [1/3]
enum v8::internal::InstructionBase::Type
Enumerator
kOp6Type
kOp7Type
kOp8Type
kOp10Type
kOp12Type
kOp14Type
kOp17Type
kOp22Type
kUnsupported
kRegisterType
kImmediateType
kJumpType
kUnsupported
kRType
kR4Type
kIType
kSType
kBType
kUType
kJType
kCRType
kCIType
kCSSType
kCIWType
kCLType
kCSType
kCAType
kCBType
kCJType
kVType
kVLType
kVSType
kVAMOType
kVIVVType
kVFVVType
kVMVVType
kVIVIType
kVIVXType
kVFVFType
kVMVXType
kVSETType
kUnsupported
Definition at line 722 of file constants-loong64.h.
            {
    kOp6Type,
    kOp7Type,
    kOp8Type,
    kOp10Type,
    kOp12Type,
    kOp14Type,
    kOp17Type,
    kOp22Type,
    kUnsupported = -1
  };
Type [2/3]
enum v8::internal::InstructionBase::Type
Enumerator
kOp6Type
kOp7Type
kOp8Type
kOp10Type
kOp12Type
kOp14Type
kOp17Type
kOp22Type
kUnsupported
kRegisterType
kImmediateType
kJumpType
kUnsupported
kRType
kR4Type
kIType
kSType
kBType
kUType
kJType
kCRType
kCIType
kCSSType
kCIWType
kCLType
kCSType
kCAType
kCBType
kCJType
kVType
kVLType
kVSType
kVAMOType
kVIVVType
kVFVVType
kVMVVType
kVIVIType
kVIVXType
kVFVFType
kVMVXType
kVSETType
kUnsupported
Definition at line 1294 of file constants-mips64.h.
{ kRegisterType, kImmediateType, kJumpType, kUnsupported = -1 };
Type [3/3]
enum v8::internal::InstructionBase::Type
Enumerator
kOp6Type
kOp7Type
kOp8Type
kOp10Type
kOp12Type
kOp14Type
kOp17Type
kOp22Type
kUnsupported
kRegisterType
kImmediateType
kJumpType
kUnsupported
kRType
kR4Type
kIType
kSType
kBType
kUType
kJType
kCRType
kCIType
kCSSType
kCIWType
kCLType
kCSType
kCAType
kCBType
kCJType
kVType
kVLType
kVSType
kVAMOType
kVIVVType
kVFVVType
kVMVVType
kVIVIType
kVIVXType
kVFVFType
kVMVXType
kVSETType
kUnsupported
Definition at line 690 of file base-constants-riscv.h.
            {
    kRType,
    kR4Type, // Special R4 for Q extension
    kIType,
    kSType,
    kBType,
    kUType,
    kJType,
    // C extension
    kCRType,
    kCIType,
    kCSSType,
    kCIWType,
    kCLType,
    kCSType,
    kCAType,
    kCBType,
    kCJType,
    // V extension
    kVType,
    kVLType,
    kVSType,
    kVAMOType,
    kVIVVType,
    kVFVVType,
    kVMVVType,
    kVIVIType,
    kVIVXType,
    kVFVFType,
    kVMVXType,
    kVSETType,
    kUnsupported = -1
  };
Constructor & Destructor Documentation
InstructionBase() [1/3]
v8::internal::InstructionBase::InstructionBase () [inline], [protected]
Definition at line 760 of file constants-loong64.h.
{}
InstructionBase() [2/3]
v8::internal::InstructionBase::InstructionBase () [inline], [protected]
Definition at line 1451 of file constants-mips64.h.
{}
InstructionBase() [3/3]
v8::internal::InstructionBase::InstructionBase () [inline], [protected]
Definition at line 807 of file base-constants-riscv.h.
{}
Member Function Documentation
BaseOpcodeFieldRaw()
BaseOpcode v8::internal::InstructionBase::BaseOpcodeFieldRaw () const [inline]
Definition at line 765 of file base-constants-riscv.h.
                                               {
    return static_cast<BaseOpcode>(InstructionBits() & kBaseOpcodeMask);
  }
References InstructionBits(), and v8::internal::kBaseOpcodeMask.
Referenced by v8::internal::Decoder< V >::DecodeUType().
BaseOpcodeValue()
BaseOpcode v8::internal::InstructionBase::BaseOpcodeValue () const [inline]
Definition at line 759 of file base-constants-riscv.h.
                                            {
    return static_cast<BaseOpcode>(
        Bits(kBaseOpcodeShift + kBaseOpcodeBits - 1, kBaseOpcodeShift));
  }
References Bits(), v8::internal::kBaseOpcodeBits, and v8::internal::kBaseOpcodeShift.
Referenced by v8::internal::Decoder< V >::DecodeJType().
Bit() [1/3]
int v8::internal::InstructionBase::Bit (int nr) const [inline]
Definition at line 744 of file constants-loong64.h.
{ return (InstructionBits() >> nr) & 1; }
References InstructionBits().
Referenced by InstructionType().
Bit() [2/3]
int v8::internal::InstructionBase::Bit (int nr) const [inline]
Definition at line 1306 of file constants-mips64.h.
{ return (InstructionBits() >> nr) & 1; }
References InstructionBits().
Bit() [3/3]
int v8::internal::InstructionBase::Bit (int nr) const [inline]
Definition at line 751 of file base-constants-riscv.h.
{ return (InstructionBits() >> nr) & 1; }
References InstructionBits().
Bits() [1/3]
int v8::internal::InstructionBase::Bits (int hi, int lo) const [inline]
Definition at line 747 of file constants-loong64.h.
                                        {
    return (InstructionBits() >> lo) & ((2U << (hi - lo)) - 1);
  }
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
Referenced by BaseOpcodeValue(), InstructionType(), and OpcodeValue().
Bits() [2/3]
int v8::internal::InstructionBase::Bits (int hi, int lo) const [inline]
Definition at line 1309 of file constants-mips64.h.
                                        {
    return (InstructionBits() >> lo) & ((2U << (hi - lo)) - 1);
  }
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
Bits() [3/3]
int v8::internal::InstructionBase::Bits (int hi, int lo) const [inline]
Definition at line 754 of file base-constants-riscv.h.
                                        {
    return (InstructionBits() >> lo) & ((2U << (hi - lo)) - 1);
  }
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
Funct3FieldRaw()
int v8::internal::InstructionBase::Funct3FieldRaw () const [inline]
Definition at line 776 of file base-constants-riscv.h.
{ return InstructionBits() & kFunct3Mask; }
References InstructionBits(), and v8::internal::kFunct3Mask.
Funct6FieldRaw()
int v8::internal::InstructionBase::Funct6FieldRaw () const [inline]
Definition at line 773 of file base-constants-riscv.h.
{ return InstructionBits() & kFunct6Mask; }
References InstructionBits(), and v8::internal::kFunct6Mask.
Referenced by v8::internal::Decoder< V >::DecodeIType().
Funct7FieldRaw()
int v8::internal::InstructionBase::Funct7FieldRaw () const [inline]
Definition at line 770 of file base-constants-riscv.h.
{ return InstructionBits() & kFunct7Mask; }
References InstructionBits(), and v8::internal::kFunct7Mask.
Referenced by v8::internal::Decoder< V >::DecodeIType().
FunctionFieldRaw()
int v8::internal::InstructionBase::FunctionFieldRaw () const [inline]
Definition at line 1375 of file constants-mips64.h.
                                      {
    return InstructionBits() & kFunctionFieldMask;
  }
References InstructionBits(), and v8::internal::kFunctionFieldMask.
Referenced by MSAMinorOpcodeField().
InstructionBits() [1/3]
Instr v8::internal::InstructionBase::InstructionBits () const [inline]
Definition at line 735 of file constants-loong64.h.
                                       {
    return *reinterpret_cast<const Instr*>(this);
  }
Referenced by BaseOpcodeFieldRaw(), Bit(), Bits(), Funct3FieldRaw(), Funct6FieldRaw(), Funct7FieldRaw(), FunctionFieldRaw(), InstructionOpcodeType(), ITypeBits(), MSAMinorOpcodeField(), OpcodeFieldRaw(), RjFieldRawNoAssert(), Rs1FieldRawNoAssert(), Rs2FieldRawNoAssert(), Rs3FieldRawNoAssert(), RsFieldRawNoAssert(), and SaFieldRaw().
InstructionBits() [2/3]
Instr v8::internal::InstructionBase::InstructionBits () const [inline]
Definition at line 1297 of file constants-mips64.h.
                                       {
    return *reinterpret_cast<const Instr*>(this);
  }
InstructionBits() [3/3]
Instr v8::internal::InstructionBase::InstructionBits () const [inline]
Definition at line 738 of file base-constants-riscv.h.
                                       {
    if (v8_flags.riscv_c_extension && this->IsShortInstruction()) {
      return 0x0000FFFF & (*reinterpret_cast<const ShortInstr*>(this));
    }
    return *reinterpret_cast<const Instr*>(this);
  }
References v8::internal::this, and v8::internal::v8_flags.
InstructionOpcodeType()
int32_t v8::internal::InstructionBase::InstructionOpcodeType () const [inline]
Definition at line 795 of file base-constants-riscv.h.
                                               {
    if (IsShortInstruction()) {
      return InstructionBits() & kRvcOpcodeMask;
    } else {
      return InstructionBits() & kBaseOpcodeMask;
    }
  }
References InstructionBits(), IsShortInstruction(), v8::internal::kBaseOpcodeMask, and v8::internal::kRvcOpcodeMask.
Referenced by v8::internal::Assembler::target_at(), and v8::internal::Assembler::target_at_put().
InstructionSize()
uint8_t v8::internal::InstructionBase::InstructionSize () const [inline]
Definition at line 731 of file base-constants-riscv.h.
                                         {
    return (v8_flags.riscv_c_extension && this->IsShortInstruction())
               ? kShortInstrSize
               : kInstrSize;
  }
References v8::internal::kInstrSize, v8::internal::kShortInstrSize, v8::internal::this, and v8::internal::v8_flags.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
InstructionType() [1/3]
InstructionBase::Type v8::internal::InstructionBase::InstructionType () const [inline]
Definition at line 939 of file constants-loong64.h.
                                                           {
  InstructionBase::Type kType = kUnsupported;
  // Check for kOp6Type
  switch (Bits(31, 26) << 26) {
    case ADDU16I_D:
    case BEQZ:
    case BNEZ:
    case BCZ:
    case JIRL:
    case B:
    case BL:
    case BEQ:
    case BNE:
    case BLT:
    case BGE:
    case BLTU:
    case BGEU:
      kType = kOp6Type;
      break;
    default:
      kType = kUnsupported;
  }
  if (kType == kUnsupported) {
    // Check for kOp7Type
    switch (Bits(31, 25) << 25) {
      case LU12I_W:
      case LU32I_D:
      case PCADDI:
      case PCALAU12I:
      case PCADDU12I:
      case PCADDU18I:
        kType = kOp7Type;
        break;
      default:
        kType = kUnsupported;
    }
  }
  if (kType == kUnsupported) {
    // Check for kOp8Type
    switch (Bits(31, 24) << 24) {
      case LDPTR_W:
      case STPTR_W:
      case LDPTR_D:
      case STPTR_D:
      case LL_W:
      case SC_W:
      case LL_D:
      case SC_D:
        kType = kOp8Type;
        break;
      default:
        kType = kUnsupported;
    }
  }
  if (kType == kUnsupported) {
    // Check for kOp10Type
    switch (Bits(31, 22) << 22) {
      case BSTR_W: {
        // If Bit(21) = 0, then the Opcode is not BSTR_W.
        if (Bit(21) == 0)
          kType = kUnsupported;
        else
          kType = kOp10Type;
        break;
      }
      case BSTRINS_D:
      case BSTRPICK_D:
      case SLTI:
      case SLTUI:
      case ADDI_W:
      case ADDI_D:
      case LU52I_D:
      case ANDI:
      case ORI:
      case XORI:
      case LD_B:
      case LD_H:
      case LD_W:
      case LD_D:
      case ST_B:
      case ST_H:
      case ST_W:
      case ST_D:
      case LD_BU:
      case LD_HU:
      case LD_WU:
      case FLD_S:
      case FST_S:
      case FLD_D:
      case FST_D:
        kType = kOp10Type;
        break;
      default:
        kType = kUnsupported;
    }
  }
  if (kType == kUnsupported) {
    // Check for kOp12Type
    switch (Bits(31, 20) << 20) {
      case FMADD_S:
      case FMADD_D:
      case FMSUB_S:
      case FMSUB_D:
      case FNMADD_S:
      case FNMADD_D:
      case FNMSUB_S:
      case FNMSUB_D:
      case FCMP_COND_S:
      case FCMP_COND_D:
      case FSEL:
        kType = kOp12Type;
        break;
      default:
        kType = kUnsupported;
    }
  }
  if (kType == kUnsupported) {
    // Check for kOp14Type
    switch (Bits(31, 18) << 18) {
      case ALSL:
      case BYTEPICK_W:
      case BYTEPICK_D:
      case ALSL_D:
      case SLLI:
      case SRLI:
      case SRAI:
      case ROTRI:
        kType = kOp14Type;
        break;
      default:
        kType = kUnsupported;
    }
  }
  if (kType == kUnsupported) {
    // Check for kOp17Type
    switch (Bits(31, 15) << 15) {
      case ADD_W:
      case ADD_D:
      case SUB_W:
      case SUB_D:
      case SLT:
      case SLTU:
      case MASKEQZ:
      case MASKNEZ:
      case NOR:
      case AND:
      case OR:
      case XOR:
      case ORN:
      case ANDN:
      case SLL_W:
      case SRL_W:
      case SRA_W:
      case SLL_D:
      case SRL_D:
      case SRA_D:
      case ROTR_D:
      case ROTR_W:
      case MUL_W:
      case MULH_W:
      case MULH_WU:
      case MUL_D:
      case MULH_D:
      case MULH_DU:
      case MULW_D_W:
      case MULW_D_WU:
      case DIV_W:
      case MOD_W:
      case DIV_WU:
      case MOD_WU:
      case DIV_D:
      case MOD_D:
      case DIV_DU:
      case MOD_DU:
      case BREAK:
      case FADD_S:
      case FADD_D:
      case FSUB_S:
      case FSUB_D:
      case FMUL_S:
      case FMUL_D:
      case FDIV_S:
      case FDIV_D:
      case FMAX_S:
      case FMAX_D:
      case FMIN_S:
      case FMIN_D:
      case FMAXA_S:
      case FMAXA_D:
      case FMINA_S:
      case FMINA_D:
      case LDX_B:
      case LDX_H:
      case LDX_W:
      case LDX_D:
      case STX_B:
      case STX_H:
      case STX_W:
      case STX_D:
      case LDX_BU:
      case LDX_HU:
      case LDX_WU:
      case FLDX_S:
      case FLDX_D:
      case FSTX_S:
      case FSTX_D:
      case AMSWAP_W:
      case AMSWAP_D:
      case AMADD_W:
      case AMADD_D:
      case AMAND_W:
      case AMAND_D:
      case AMOR_W:
      case AMOR_D:
      case AMXOR_W:
      case AMXOR_D:
      case AMMAX_W:
      case AMMAX_D:
      case AMMIN_W:
      case AMMIN_D:
      case AMMAX_WU:
      case AMMAX_DU:
      case AMMIN_WU:
      case AMMIN_DU:
      case AMSWAP_DB_W:
      case AMSWAP_DB_D:
      case AMADD_DB_W:
      case AMADD_DB_D:
      case AMAND_DB_W:
      case AMAND_DB_D:
      case AMOR_DB_W:
      case AMOR_DB_D:
      case AMXOR_DB_W:
      case AMXOR_DB_D:
      case AMMAX_DB_W:
      case AMMAX_DB_D:
      case AMMIN_DB_W:
      case AMMIN_DB_D:
      case AMMAX_DB_WU:
      case AMMAX_DB_DU:
      case AMMIN_DB_WU:
      case AMMIN_DB_DU:
      case DBAR:
      case IBAR:
      case FSCALEB_S:
      case FSCALEB_D:
      case FCOPYSIGN_S:
      case FCOPYSIGN_D:
        kType = kOp17Type;
        break;
      default:
        kType = kUnsupported;
    }
  }
  if (kType == kUnsupported) {
    // Check for kOp22Type
    switch (Bits(31, 10) << 10) {
      case CLZ_W:
      case CTZ_W:
      case CLZ_D:
      case CTZ_D:
      case REVB_2H:
      case REVB_4H:
      case REVB_2W:
      case REVB_D:
      case REVH_2W:
      case REVH_D:
      case BITREV_4B:
      case BITREV_8B:
      case BITREV_W:
      case BITREV_D:
      case EXT_W_B:
      case EXT_W_H:
      case FABS_S:
      case FABS_D:
      case FNEG_S:
      case FNEG_D:
      case FSQRT_S:
      case FSQRT_D:
      case FMOV_S:
      case FMOV_D:
      case MOVGR2FR_W:
      case MOVGR2FR_D:
      case MOVGR2FRH_W:
      case MOVFR2GR_S:
      case MOVFR2GR_D:
      case MOVFRH2GR_S:
      case MOVGR2FCSR:
      case MOVFCSR2GR:
      case FCVT_S_D:
      case FCVT_D_S:
      case FTINTRM_W_S:
      case FTINTRM_W_D:
      case FTINTRM_L_S:
      case FTINTRM_L_D:
      case FTINTRP_W_S:
      case FTINTRP_W_D:
      case FTINTRP_L_S:
      case FTINTRP_L_D:
      case FTINTRZ_W_S:
      case FTINTRZ_W_D:
      case FTINTRZ_L_S:
      case FTINTRZ_L_D:
      case FTINTRNE_W_S:
      case FTINTRNE_W_D:
      case FTINTRNE_L_S:
      case FTINTRNE_L_D:
      case FTINT_W_S:
      case FTINT_W_D:
      case FTINT_L_S:
      case FTINT_L_D:
      case FFINT_S_W:
      case FFINT_S_L:
      case FFINT_D_W:
      case FFINT_D_L:
      case FRINT_S:
      case FRINT_D:
      case MOVFR2CF:
      case MOVCF2FR:
      case MOVGR2CF:
      case MOVCF2GR:
      case FRECIP_S:
      case FRECIP_D:
      case FRSQRT_S:
      case FRSQRT_D:
      case FCLASS_S:
      case FCLASS_D:
      case FLOGB_S:
      case FLOGB_D:
      case CLO_W:
      case CTO_W:
      case CLO_D:
      case CTO_D:
        kType = kOp22Type;
        break;
      default:
        kType = kUnsupported;
    }
  }
  return kType;
}
References v8::internal::ADD_D, v8::internal::ADD_W, v8::internal::ADDI_D, v8::internal::ADDI_W, v8::internal::ADDU16I_D, v8::internal::ALSL, v8::internal::ALSL_D, v8::internal::AMADD_D, v8::internal::AMADD_DB_D, v8::internal::AMADD_DB_W, v8::internal::AMADD_W, v8::internal::AMAND_D, v8::internal::AMAND_DB_D, v8::internal::AMAND_DB_W, v8::internal::AMAND_W, v8::internal::AMMAX_D, v8::internal::AMMAX_DB_D, v8::internal::AMMAX_DB_DU, v8::internal::AMMAX_DB_W, v8::internal::AMMAX_DB_WU, v8::internal::AMMAX_DU, v8::internal::AMMAX_W, v8::internal::AMMAX_WU, v8::internal::AMMIN_D, v8::internal::AMMIN_DB_D, v8::internal::AMMIN_DB_DU, v8::internal::AMMIN_DB_W, v8::internal::AMMIN_DB_WU, v8::internal::AMMIN_DU, v8::internal::AMMIN_W, v8::internal::AMMIN_WU, v8::internal::AMOR_D, v8::internal::AMOR_DB_D, v8::internal::AMOR_DB_W, v8::internal::AMOR_W, v8::internal::AMSWAP_D, v8::internal::AMSWAP_DB_D, v8::internal::AMSWAP_DB_W, v8::internal::AMSWAP_W, v8::internal::AMXOR_D, v8::internal::AMXOR_DB_D, v8::internal::AMXOR_DB_W, v8::internal::AMXOR_W, v8::internal::AND, v8::internal::ANDI, v8::internal::ANDN, v8::internal::B, v8::internal::BCZ, v8::internal::BEQ, v8::internal::BEQZ, v8::internal::BGE, v8::internal::BGEU, Bit(), v8::internal::BITREV_4B, v8::internal::BITREV_8B, v8::internal::BITREV_D, v8::internal::BITREV_W, Bits(), v8::internal::BL, v8::internal::BLT, v8::internal::BLTU, v8::internal::BNE, v8::internal::BNEZ, v8::internal::BREAK, v8::internal::BSTR_W, v8::internal::BSTRINS_D, v8::internal::BSTRPICK_D, v8::internal::BYTEPICK_D, v8::internal::BYTEPICK_W, v8::internal::CLO_D, v8::internal::CLO_W, v8::internal::CLZ_D, v8::internal::CLZ_W, v8::internal::CTO_D, v8::internal::CTO_W, v8::internal::CTZ_D, v8::internal::CTZ_W, v8::internal::DBAR, v8::internal::DIV_D, v8::internal::DIV_DU, v8::internal::DIV_W, v8::internal::DIV_WU, v8::internal::EXT_W_B, v8::internal::EXT_W_H, v8::internal::FABS_D, v8::internal::FABS_S, v8::internal::FADD_D, v8::internal::FADD_S, v8::internal::FCLASS_D, v8::internal::FCLASS_S, v8::internal::FCMP_COND_D, v8::internal::FCMP_COND_S, v8::internal::FCOPYSIGN_D, v8::internal::FCOPYSIGN_S, v8::internal::FCVT_D_S, v8::internal::FCVT_S_D, v8::internal::FDIV_D, v8::internal::FDIV_S, v8::internal::FFINT_D_L, v8::internal::FFINT_D_W, v8::internal::FFINT_S_L, v8::internal::FFINT_S_W, v8::internal::FLD_D, v8::internal::FLD_S, v8::internal::FLDX_D, v8::internal::FLDX_S, v8::internal::FLOGB_D, v8::internal::FLOGB_S, v8::internal::FMADD_D, v8::internal::FMADD_S, v8::internal::FMAX_D, v8::internal::FMAX_S, v8::internal::FMAXA_D, v8::internal::FMAXA_S, v8::internal::FMIN_D, v8::internal::FMIN_S, v8::internal::FMINA_D, v8::internal::FMINA_S, v8::internal::FMOV_D, v8::internal::FMOV_S, v8::internal::FMSUB_D, v8::internal::FMSUB_S, v8::internal::FMUL_D, v8::internal::FMUL_S, v8::internal::FNEG_D, v8::internal::FNEG_S, v8::internal::FNMADD_D, v8::internal::FNMADD_S, v8::internal::FNMSUB_D, v8::internal::FNMSUB_S, v8::internal::FRECIP_D, v8::internal::FRECIP_S, v8::internal::FRINT_D, v8::internal::FRINT_S, v8::internal::FRSQRT_D, v8::internal::FRSQRT_S, v8::internal::FSCALEB_D, v8::internal::FSCALEB_S, v8::internal::FSEL, v8::internal::FSQRT_D, v8::internal::FSQRT_S, v8::internal::FST_D, v8::internal::FST_S, v8::internal::FSTX_D, v8::internal::FSTX_S, v8::internal::FSUB_D, v8::internal::FSUB_S, v8::internal::FTINT_L_D, v8::internal::FTINT_L_S, v8::internal::FTINT_W_D, v8::internal::FTINT_W_S, v8::internal::FTINTRM_L_D, v8::internal::FTINTRM_L_S, v8::internal::FTINTRM_W_D, v8::internal::FTINTRM_W_S, v8::internal::FTINTRNE_L_D, v8::internal::FTINTRNE_L_S, v8::internal::FTINTRNE_W_D, v8::internal::FTINTRNE_W_S, v8::internal::FTINTRP_L_D, v8::internal::FTINTRP_L_S, v8::internal::FTINTRP_W_D, v8::internal::FTINTRP_W_S, v8::internal::FTINTRZ_L_D, v8::internal::FTINTRZ_L_S, v8::internal::FTINTRZ_W_D, v8::internal::FTINTRZ_W_S, v8::internal::IBAR, v8::internal::JIRL, kOp10Type, kOp12Type, kOp14Type, kOp17Type, kOp22Type, kOp6Type, kOp7Type, kOp8Type, kUnsupported, v8::internal::LD_B, v8::internal::LD_BU, v8::internal::LD_D, v8::internal::LD_H, v8::internal::LD_HU, v8::internal::LD_W, v8::internal::LD_WU, v8::internal::LDPTR_D, v8::internal::LDPTR_W, v8::internal::LDX_B, v8::internal::LDX_BU, v8::internal::LDX_D, v8::internal::LDX_H, v8::internal::LDX_HU, v8::internal::LDX_W, v8::internal::LDX_WU, v8::internal::LL_D, v8::internal::LL_W, v8::internal::LU12I_W, v8::internal::LU32I_D, v8::internal::LU52I_D, v8::internal::MASKEQZ, v8::internal::MASKNEZ, v8::internal::MOD_D, v8::internal::MOD_DU, v8::internal::MOD_W, v8::internal::MOD_WU, v8::internal::MOVCF2FR, v8::internal::MOVCF2GR, v8::internal::MOVFCSR2GR, v8::internal::MOVFR2CF, v8::internal::MOVFR2GR_D, v8::internal::MOVFR2GR_S, v8::internal::MOVFRH2GR_S, v8::internal::MOVGR2CF, v8::internal::MOVGR2FCSR, v8::internal::MOVGR2FR_D, v8::internal::MOVGR2FR_W, v8::internal::MOVGR2FRH_W, v8::internal::MUL_D, v8::internal::MUL_W, v8::internal::MULH_D, v8::internal::MULH_DU, v8::internal::MULH_W, v8::internal::MULH_WU, v8::internal::MULW_D_W, v8::internal::MULW_D_WU, v8::internal::NOR, v8::internal::OR, v8::internal::ORI, v8::internal::ORN, v8::internal::PCADDI, v8::internal::PCADDU12I, v8::internal::PCADDU18I, v8::internal::PCALAU12I, v8::internal::REVB_2H, v8::internal::REVB_2W, v8::internal::REVB_4H, v8::internal::REVB_D, v8::internal::REVH_2W, v8::internal::REVH_D, v8::internal::ROTR_D, v8::internal::ROTR_W, v8::internal::ROTRI, v8::internal::SC_D, v8::internal::SC_W, v8::internal::SLL_D, v8::internal::SLL_W, v8::internal::SLLI, v8::internal::SLT, v8::internal::SLTI, v8::internal::SLTU, v8::internal::SLTUI, v8::internal::SRA_D, v8::internal::SRA_W, v8::internal::SRAI, v8::internal::SRL_D, v8::internal::SRL_W, v8::internal::SRLI, v8::internal::ST_B, v8::internal::ST_D, v8::internal::ST_H, v8::internal::ST_W, v8::internal::STPTR_D, v8::internal::STPTR_W, v8::internal::STX_B, v8::internal::STX_D, v8::internal::STX_H, v8::internal::STX_W, v8::internal::SUB_D, v8::internal::SUB_W, v8::internal::XOR, and v8::internal::XORI.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
InstructionType() [2/3]
Type v8::internal::InstructionBase::InstructionType () const [inline]
InstructionType() [3/3]
Type v8::internal::InstructionBase::InstructionType () const
IsIllegalInstruction()
bool v8::internal::InstructionBase::IsIllegalInstruction () const [inline]
Definition at line 724 of file base-constants-riscv.h.
                                           {
    uint16_t FirstHalfWord = *reinterpret_cast<const uint16_t*>(this);
    return FirstHalfWord == 0;
  }
IsShortInstruction()
bool v8::internal::InstructionBase::IsShortInstruction () const
Definition at line 147 of file base-constants-riscv.cc.
                                               {
  uint8_t FirstByte = *reinterpret_cast<const uint8_t*>(this);
  return (FirstByte & 0x03) <= C2;
}
References v8::internal::C2.
Referenced by v8::internal::Decoder< V >::Format(), and InstructionOpcodeType().
ITypeBits()
int32_t v8::internal::InstructionBase::ITypeBits () const [inline]
Definition at line 793 of file base-constants-riscv.h.
{ return InstructionBits() & kITypeMask; }
References InstructionBits(), and v8::internal::kITypeMask.
MSAMinorOpcodeField()
MSAMinorOpcode v8::internal::InstructionBase::MSAMinorOpcodeField () const [inline]
Definition at line 1394 of file constants-mips64.h.
                                                    {
    int op = this->FunctionFieldRaw();
    switch (op) {
      case 0:
      case 1:
      case 2:
        return kMsaMinorI8;
      case 6:
        return kMsaMinorI5;
      case 7:
        return (((this->InstructionBits() & kMsaI5I10Mask) == LDI)
                    ? kMsaMinorI10
                    : kMsaMinorI5);
      case 9:
      case 10:
        return kMsaMinorBIT;
      case 13:
      case 14:
      case 15:
      case 16:
      case 17:
      case 18:
      case 19:
      case 20:
      case 21:
        return kMsaMinor3R;
      case 25:
        return kMsaMinorELM;
      case 26:
      case 27:
      case 28:
        return kMsaMinor3RF;
      case 30:
        switch (this->RsFieldRawNoAssert()) {
          case MSA_2R_FORMAT:
            return kMsaMinor2R;
          case MSA_2RF_FORMAT:
            return kMsaMinor2RF;
          default:
            return kMsaMinorVEC;
        }
        break;
      case 32:
      case 33:
      case 34:
      case 35:
      case 36:
      case 37:
      case 38:
      case 39:
        return kMsaMinorMI10;
      default:
        return kMsaMinorUndefined;
    }
  }
References FunctionFieldRaw(), InstructionBits(), v8::internal::kMsaMinor2R, v8::internal::kMsaMinor2RF, v8::internal::kMsaMinor3R, v8::internal::kMsaMinor3RF, v8::internal::kMsaMinorBIT, v8::internal::kMsaMinorELM, v8::internal::kMsaMinorI10, v8::internal::kMsaMinorI5, v8::internal::kMsaMinorI8, v8::internal::kMsaMinorMI10, v8::internal::kMsaMinorUndefined, v8::internal::kMsaMinorVEC, v8::internal::LDI, v8::internal::MSA_2R_FORMAT, v8::internal::MSA_2RF_FORMAT, and RsFieldRawNoAssert().
OpcodeFieldRaw()
Opcode v8::internal::InstructionBase::OpcodeFieldRaw () const [inline]
Definition at line 1380 of file constants-mips64.h.
                                       {
    return static_cast<Opcode>(InstructionBits() & kOpcodeMask);
  }
References InstructionBits(), and v8::internal::kOpcodeMask.
OpcodeValue()
Opcode v8::internal::InstructionBase::OpcodeValue () const [inline]
Definition at line 1370 of file constants-mips64.h.
                                    {
    return static_cast<Opcode>(
        Bits(kOpcodeShift + kOpcodeBits - 1, kOpcodeShift));
  }
References Bits(), v8::internal::kOpcodeBits, and v8::internal::kOpcodeShift.
RjFieldRawNoAssert()
int v8::internal::InstructionBase::RjFieldRawNoAssert () const [inline]
Definition at line 752 of file constants-loong64.h.
                                        {
    return InstructionBits() & kRjFieldMask;
  }
References InstructionBits(), and v8::internal::kRjFieldMask.
Rs1FieldRawNoAssert()
int v8::internal::InstructionBase::Rs1FieldRawNoAssert () const [inline]
Definition at line 779 of file base-constants-riscv.h.
                                         {
    return InstructionBits() & kRs1FieldMask;
  }
References InstructionBits(), and v8::internal::kRs1FieldMask.
Rs2FieldRawNoAssert()
int v8::internal::InstructionBase::Rs2FieldRawNoAssert () const [inline]
Definition at line 784 of file base-constants-riscv.h.
                                         {
    return InstructionBits() & kRs2FieldMask;
  }
References InstructionBits(), and v8::internal::kRs2FieldMask.
Rs3FieldRawNoAssert()
int v8::internal::InstructionBase::Rs3FieldRawNoAssert () const [inline]
Definition at line 789 of file base-constants-riscv.h.
                                         {
    return InstructionBits() & kRs3FieldMask;
  }
References InstructionBits(), and v8::internal::kRs3FieldMask.
RsFieldRawNoAssert()
int v8::internal::InstructionBase::RsFieldRawNoAssert () const [inline]
Definition at line 1385 of file constants-mips64.h.
                                        {
    return InstructionBits() & kRsFieldMask;
  }
References InstructionBits(), and v8::internal::kRsFieldMask.
Referenced by MSAMinorOpcodeField().
SaFieldRaw()
int v8::internal::InstructionBase::SaFieldRaw () const [inline]
Definition at line 1389 of file constants-mips64.h.
{ return InstructionBits() & kSaFieldMask; }
References InstructionBits(), and v8::internal::kSaFieldMask.
SetInstructionBits() [1/3]
V8_EXPORT_PRIVATE void v8::internal::InstructionBase::SetInstructionBits (Instr new_instr, WritableJitAllocation * jit_allocation = nullptr)
SetInstructionBits() [2/3]
V8_EXPORT_PRIVATE void v8::internal::InstructionBase::SetInstructionBits (Instr new_instr, WritableJitAllocation * jit_allocation = nullptr)
SetInstructionBits() [3/3]
void v8::internal::InstructionBase::SetInstructionBits (Instr value) [inline]
Definition at line 746 of file base-constants-riscv.h.
                                              {
    *reinterpret_cast<Instr*>(this) = value;
  }
References v8::internal::value.
Member Data Documentation
kFunctionFieldRegisterTypeMask
const uint64_t v8::internal::InstructionBase::kFunctionFieldRegisterTypeMask [static]
Initial value:
=
      FunctionFieldToBitNumber(JR) | FunctionFieldToBitNumber(JALR) |
      FunctionFieldToBitNumber(BREAK) | FunctionFieldToBitNumber(SLL) |
      FunctionFieldToBitNumber(DSLL) | FunctionFieldToBitNumber(DSLL32) |
      FunctionFieldToBitNumber(SRL) | FunctionFieldToBitNumber(DSRL) |
      FunctionFieldToBitNumber(DSRL32) | FunctionFieldToBitNumber(SRA) |
      FunctionFieldToBitNumber(DSRA) | FunctionFieldToBitNumber(DSRA32) |
      FunctionFieldToBitNumber(SLLV) | FunctionFieldToBitNumber(DSLLV) |
      FunctionFieldToBitNumber(SRLV) | FunctionFieldToBitNumber(DSRLV) |
      FunctionFieldToBitNumber(SRAV) | FunctionFieldToBitNumber(DSRAV) |
      FunctionFieldToBitNumber(LSA) | FunctionFieldToBitNumber(DLSA) |
      FunctionFieldToBitNumber(MFHI) | FunctionFieldToBitNumber(MFLO) |
      FunctionFieldToBitNumber(MULT) | FunctionFieldToBitNumber(DMULT) |
      FunctionFieldToBitNumber(MULTU) | FunctionFieldToBitNumber(DMULTU) |
      FunctionFieldToBitNumber(DIV) | FunctionFieldToBitNumber(DDIV) |
      FunctionFieldToBitNumber(DIVU) | FunctionFieldToBitNumber(DDIVU) |
      FunctionFieldToBitNumber(ADD) | FunctionFieldToBitNumber(DADD) |
      FunctionFieldToBitNumber(ADDU) | FunctionFieldToBitNumber(DADDU) |
      FunctionFieldToBitNumber(SUB) | FunctionFieldToBitNumber(DSUB) |
      FunctionFieldToBitNumber(SUBU) | FunctionFieldToBitNumber(DSUBU) |
      FunctionFieldToBitNumber(AND) | FunctionFieldToBitNumber(OR) |
      FunctionFieldToBitNumber(XOR) | FunctionFieldToBitNumber(NOR) |
      FunctionFieldToBitNumber(SLT) | FunctionFieldToBitNumber(SLTU) |
      FunctionFieldToBitNumber(TGE) | FunctionFieldToBitNumber(TGEU) |
      FunctionFieldToBitNumber(TLT) | FunctionFieldToBitNumber(TLTU) |
      FunctionFieldToBitNumber(TEQ) | FunctionFieldToBitNumber(TNE) |
      FunctionFieldToBitNumber(MOVZ) | FunctionFieldToBitNumber(MOVN) |
      FunctionFieldToBitNumber(MOVCI) | FunctionFieldToBitNumber(SELEQZ_S) |
      FunctionFieldToBitNumber(SELNEZ_S) | FunctionFieldToBitNumber(SYNC)
Definition at line 1339 of file constants-mips64.h.
kOpcodeImmediateTypeMask
constexpr uint64_t v8::internal::InstructionBase::kOpcodeImmediateTypeMask [static], [constexpr]
Initial value:
=
      OpcodeToBitNumber(REGIMM) | OpcodeToBitNumber(BEQ) |
      OpcodeToBitNumber(BNE) | OpcodeToBitNumber(BLEZ) |
      OpcodeToBitNumber(BGTZ) | OpcodeToBitNumber(ADDI) |
      OpcodeToBitNumber(DADDI) | OpcodeToBitNumber(ADDIU) |
      OpcodeToBitNumber(DADDIU) | OpcodeToBitNumber(SLTI) |
      OpcodeToBitNumber(SLTIU) | OpcodeToBitNumber(ANDI) |
      OpcodeToBitNumber(ORI) | OpcodeToBitNumber(XORI) |
      OpcodeToBitNumber(LUI) | OpcodeToBitNumber(BEQL) |
      OpcodeToBitNumber(BNEL) | OpcodeToBitNumber(BLEZL) |
      OpcodeToBitNumber(BGTZL) | OpcodeToBitNumber(POP66) |
      OpcodeToBitNumber(POP76) | OpcodeToBitNumber(LB) | OpcodeToBitNumber(LH) |
      OpcodeToBitNumber(LWL) | OpcodeToBitNumber(LW) | OpcodeToBitNumber(LWU) |
      OpcodeToBitNumber(LD) | OpcodeToBitNumber(LBU) | OpcodeToBitNumber(LHU) |
      OpcodeToBitNumber(LDL) | OpcodeToBitNumber(LDR) | OpcodeToBitNumber(LWR) |
      OpcodeToBitNumber(SDL) | OpcodeToBitNumber(SB) | OpcodeToBitNumber(SH) |
      OpcodeToBitNumber(SWL) | OpcodeToBitNumber(SW) | OpcodeToBitNumber(SD) |
      OpcodeToBitNumber(SWR) | OpcodeToBitNumber(SDR) |
      OpcodeToBitNumber(LWC1) | OpcodeToBitNumber(LDC1) |
      OpcodeToBitNumber(SWC1) | OpcodeToBitNumber(SDC1) |
      OpcodeToBitNumber(PCREL) | OpcodeToBitNumber(DAUI) |
      OpcodeToBitNumber(BC) | OpcodeToBitNumber(BALC)
Definition at line 1313 of file constants-mips64.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/loong64/constants-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/constants-mips64.h
/mnt/V8SourceCode/src/codegen/riscv/base-constants-riscv.h
/mnt/V8SourceCode/src/codegen/riscv/base-constants-riscv.cc