v8::internal::compiler::GraphTrimmer Class Reference
#include <graph-trimmer.h>
Public Member Functions
GraphTrimmer (Zone *zone, TFGraph *graph)
~GraphTrimmer ()
GraphTrimmer (const GraphTrimmer &)=delete
GraphTrimmer & operator= (const GraphTrimmer &)=delete
void TrimGraph ()
template<typename ForwardIterator >
void TrimGraph (ForwardIterator begin, ForwardIterator end)
Private Member Functions
bool IsLive (Node *const node)
void MarkAsLive (Node *const node)
TFGraph * graph () const
Private Attributes
TFGraph *const graph_
NodeMarker< bool > is_live_
NodeVector live_
Detailed Description
Definition at line 18 of file graph-trimmer.h.
Constructor & Destructor Documentation
GraphTrimmer() [1/2]
v8::internal::compiler::GraphTrimmer::GraphTrimmer (Zone * zone, TFGraph * graph)
Definition at line 13 of file graph-trimmer.cc.
    : graph_(graph), is_live_(graph, 2), live_(zone) {
  live_.reserve(graph->NodeCount());
}
References graph(), live_, v8::internal::compiler::TFGraph::NodeCount(), and v8::internal::ZoneVector< T >::reserve().
 GraphTrimmer()
v8::internal::compiler::GraphTrimmer::~GraphTrimmer () [default]
GraphTrimmer() [2/2]
v8::internal::compiler::GraphTrimmer::GraphTrimmer (const GraphTrimmer &) [delete]
Member Function Documentation
graph()
TFGraph* v8::internal::compiler::GraphTrimmer::graph () const [inline], [private]
Definition at line 49 of file graph-trimmer.h.
{ return graph_; }
Referenced by GraphTrimmer(), and TrimGraph().
IsLive()
bool v8::internal::compiler::GraphTrimmer::IsLive (Node *const node) [inline], [private]
Definition at line 40 of file graph-trimmer.h.
{ return is_live_.Get(node); }
Referenced by TrimGraph().
MarkAsLive()
void v8::internal::compiler::GraphTrimmer::MarkAsLive (Node *const node) [inline], [private]
Definition at line 41 of file graph-trimmer.h.
                                              {
    DCHECK(!node->IsDead());
    if (!IsLive(node)) {
      is_live_.Set(node, true);
      live_.push_back(node);
    }
  }
References v8::internal::DCHECK(), and v8::internal::compiler::Node::IsDead().
Referenced by TrimGraph().
operator=()
GraphTrimmer& v8::internal::compiler::GraphTrimmer::operator= (const GraphTrimmer &) [delete]
TrimGraph() [1/2]
void v8::internal::compiler::GraphTrimmer::TrimGraph ()
Definition at line 21 of file graph-trimmer.cc.
                             {
  // Mark end node as live.
  MarkAsLive(graph()->end());
  // Compute transitive closure of live nodes.
  for (size_t i = 0; i < live_.size(); ++i) {
    Node* const live = live_[i];
    for (Node* const input : live->inputs()) MarkAsLive(input);
  }
  // Remove dead->live edges.
  for (Node* const live : live_) {
    DCHECK(IsLive(live));
    for (Edge edge : live->use_edges()) {
      Node* const user = edge.from();
      if (!IsLive(user)) {
        if (v8_flags.trace_turbo_trimming) {
          StdoutStream{} << "DeadLink: " << *user << "(" << edge.index()
                         << ") -> " << *live << std::endl;
        }
        edge.UpdateTo(nullptr);
      }
    }
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::end(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::inputs(), IsLive(), live_, MarkAsLive(), v8::internal::ZoneVector< T >::size(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::EarlyGraphTrimmingPhase::Run(), v8::internal::compiler::LoopPeelingPhase::Run(), and v8::internal::compiler::MemoryOptimizationPhase::Run().
TrimGraph() [2/2]
template<typename ForwardIterator >
void v8::internal::compiler::GraphTrimmer::TrimGraph (ForwardIterator begin, ForwardIterator end) [inline]
Definition at line 31 of file graph-trimmer.h.
                                                             {
    while (begin != end) {
      Node* const node = *begin++;
      if (!node->IsDead()) MarkAsLive(node);
    }
    TrimGraph();
  }
References v8::internal::compiler::begin(), v8::internal::compiler::end(), and v8::internal::compiler::Node::IsDead().
Member Data Documentation
graph_
TFGraph* const v8::internal::compiler::GraphTrimmer::graph_ [private]
Definition at line 51 of file graph-trimmer.h.
is_live_
NodeMarker<bool> v8::internal::compiler::GraphTrimmer::is_live_ [private]
Definition at line 52 of file graph-trimmer.h.
live_
NodeVector v8::internal::compiler::GraphTrimmer::live_ [private]
Definition at line 53 of file graph-trimmer.h.
Referenced by GraphTrimmer(), and TrimGraph().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/graph-trimmer.h
/mnt/V8SourceCode/src/compiler/graph-trimmer.cc