v8::internal::maglev::InterpreterFrameState Class Reference
#include <maglev-interpreter-frame-state.h>
Public Member Functions
InterpreterFrameState (const MaglevCompilationUnit &info, KnownNodeAspects *known_node_aspects, VirtualObjectList virtual_objects)
InterpreterFrameState (const MaglevCompilationUnit &info)
void CopyFrom (const MaglevCompilationUnit &info, MergePointInterpreterFrameState &state, bool preserve_known_node_aspects, Zone *zone)
void set_accumulator (ValueNode *value)
ValueNode * accumulator () const
void set (interpreter::Register reg, ValueNode *value)
ValueNode * get (interpreter::Register reg) const
const RegisterFrameArray< ValueNode * > & frame () const
KnownNodeAspects * known_node_aspects ()
const KnownNodeAspects * known_node_aspects () const
void set_known_node_aspects (KnownNodeAspects *known_node_aspects)
void clear_known_node_aspects ()
void add_object (VirtualObject *vobject)
const VirtualObjectList & virtual_objects () const
void set_virtual_objects (const VirtualObjectList &virtual_objects)
Private Attributes
RegisterFrameArray< ValueNode * > frame_
KnownNodeAspects * known_node_aspects_
VirtualObjectList virtual_objects_
Detailed Description
Definition at line 609 of file maglev-interpreter-frame-state.h.
Constructor & Destructor Documentation
InterpreterFrameState() [1/2]
v8::internal::maglev::InterpreterFrameState::InterpreterFrameState (const MaglevCompilationUnit & info, KnownNodeAspects * known_node_aspects, VirtualObjectList virtual_objects) [inline]
Definition at line 611 of file maglev-interpreter-frame-state.h.
      : frame_(info),
        known_node_aspects_(known_node_aspects),
        virtual_objects_(virtual_objects) {
    frame_[interpreter::Register::virtual_accumulator()] = nullptr;
  }
References frame_, and v8::internal::interpreter::Register::virtual_accumulator().
InterpreterFrameState() [2/2]
v8::internal::maglev::InterpreterFrameState::InterpreterFrameState (const MaglevCompilationUnit & info) [inline], [explicit]
Definition at line 620 of file maglev-interpreter-frame-state.h.
      : InterpreterFrameState(info,
                              info.zone()->New<KnownNodeAspects>(info.zone()),
                              VirtualObjectList()) {}
Member Function Documentation
accumulator()
ValueNode* v8::internal::maglev::InterpreterFrameState::accumulator () const [inline]
Definition at line 634 of file maglev-interpreter-frame-state.h.
                                 {
    return frame_[interpreter::Register::virtual_accumulator()];
  }
References frame_, and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinaryOperationNodeForToNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BitwiseNotForToNumber(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore().
add_object()
void v8::internal::maglev::InterpreterFrameState::add_object (VirtualObject * vobject) [inline]
Definition at line 671 of file maglev-interpreter-frame-state.h.
{ virtual_objects_.Add(vobject); }
References v8::internal::maglev::VirtualObjectList::Add(), and virtual_objects_.
clear_known_node_aspects()
void v8::internal::maglev::InterpreterFrameState::clear_known_node_aspects () [inline]
Definition at line 669 of file maglev-interpreter-frame-state.h.
{ known_node_aspects_ = nullptr; }
References known_node_aspects_.
CopyFrom()
void v8::internal::maglev::InterpreterFrameState::CopyFrom (const MaglevCompilationUnit & info, MergePointInterpreterFrameState & state, bool preserve_known_node_aspects = false, Zone * zone = nullptr) [inline]
Definition at line 1252 of file maglev-interpreter-frame-state.h.
                                                           {
  DCHECK_IMPLIES(preserve_known_node_aspects, zone);
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << "- Copying frame state from merge @" << &state << std::endl;
    state.PrintVirtualObjects(info.graph_labeller(), virtual_objects());
  }
  virtual_objects_.Snapshot();
  state.frame_state().ForEachValue(
      info, [&](ValueNode* value, interpreter::Register reg) {
        frame_[reg] = value;
      });
  if (preserve_known_node_aspects) {
    known_node_aspects_ = state.CloneKnownNodeAspects(zone);
  } else {
    // Move "what we know" across without copying -- we can safely mutate it
    // now, as we won't be entering this merge point again.
    known_node_aspects_ = state.TakeKnownNodeAspects();
  }
  virtual_objects_ = state.frame_state().virtual_objects();
}
References v8::internal::maglev::MergePointInterpreterFrameState::CloneKnownNodeAspects(), DCHECK_IMPLIES, v8::internal::maglev::CompactInterpreterFrameState::ForEachValue(), frame_, v8::internal::maglev::MergePointInterpreterFrameState::frame_state(), v8::internal::maglev::MaglevCompilationUnit::graph_labeller(), known_node_aspects_, v8::internal::maglev::MergePointInterpreterFrameState::PrintVirtualObjects(), v8::internal::maglev::VirtualObjectList::Snapshot(), v8::internal::maglev::MergePointInterpreterFrameState::TakeKnownNodeAspects(), v8::internal::v8_flags, v8::internal::value, virtual_objects(), v8::internal::maglev::CompactInterpreterFrameState::virtual_objects(), and virtual_objects_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::ProcessMergePoint(), and v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointAtExceptionHandlerStart().
frame()
const RegisterFrameArray<ValueNode*>& v8::internal::maglev::InterpreterFrameState::frame () const [inline]
Definition at line 657 of file maglev-interpreter-frame-state.h.
{ return frame_; }
References frame_.
get()
ValueNode* v8::internal::maglev::InterpreterFrameState::get (interpreter::Register reg) const [inline]
Definition at line 648 of file maglev-interpreter-frame-state.h.
                                                {
    DCHECK_IMPLIES(reg.is_parameter(),
                   reg == interpreter::Register::current_context() ||
                       reg == interpreter::Register::function_closure() ||
                       reg == interpreter::Register::virtual_accumulator() ||
                       reg.ToParameterIndex() >= 0);
    return frame_[reg];
  }
References v8::internal::interpreter::Register::current_context(), DCHECK_IMPLIES, frame_, v8::internal::interpreter::Register::function_closure(), v8::internal::interpreter::Register::is_parameter(), v8::internal::interpreter::Register::ToParameterIndex(), and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinaryOperationNodeForToNumber(), v8::internal::maglev::CallArguments::CallArguments(), v8::internal::maglev::CompactInterpreterFrameState::CompactInterpreterFrameState(), v8::internal::maglev::MaglevGraphBuilder::GetArgument(), v8::internal::maglev::MaglevGraphBuilder::GetInternalizedString(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MaglevSubGraphBuilder(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergePhis(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), v8::internal::maglev::MergePointInterpreterFrameState::New(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
known_node_aspects() [1/2]
KnownNodeAspects* v8::internal::maglev::InterpreterFrameState::known_node_aspects () [inline]
Definition at line 659 of file maglev-interpreter-frame-state.h.
{ return known_node_aspects_; }
References known_node_aspects_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AttachExceptionHandlerInfo(), v8::internal::maglev::MergePointInterpreterFrameState::InitializeLoop(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MaglevSubGraphBuilder(), v8::internal::maglev::MergePointInterpreterFrameState::Merge(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergePhis(), v8::internal::maglev::MergePointInterpreterFrameState::New(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointAtExceptionHandlerStart(), set_known_node_aspects(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
known_node_aspects() [2/2]
const KnownNodeAspects* v8::internal::maglev::InterpreterFrameState::known_node_aspects () const [inline]
Definition at line 660 of file maglev-interpreter-frame-state.h.
                                                     {
    return known_node_aspects_;
  }
References known_node_aspects_.
set()
void v8::internal::maglev::InterpreterFrameState::set (interpreter::Register reg, ValueNode * value) [inline]
Definition at line 638 of file maglev-interpreter-frame-state.h.
                                                      {
    DCHECK_IMPLIES(reg.is_parameter(),
                   reg == interpreter::Register::current_context() ||
                       reg == interpreter::Register::function_closure() ||
                       reg == interpreter::Register::virtual_accumulator() ||
                       reg.ToParameterIndex() >= 0);
    // Conversions should be stored in known_node_aspects/NodeInfo.
    DCHECK(!value->properties().is_conversion());
    frame_[reg] = value;
  }
References v8::internal::interpreter::Register::current_context(), v8::internal::DCHECK(), DCHECK_IMPLIES, frame_, v8::internal::interpreter::Register::function_closure(), v8::internal::interpreter::Register::is_parameter(), v8::internal::interpreter::Register::ToParameterIndex(), v8::internal::value, and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::maglev::MaglevGraphBuilder::GetInternalizedString(), v8::internal::maglev::MaglevGraphBuilder::InitializeRegister(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MaglevSubGraphBuilder(), and v8::internal::maglev::MaglevGraphBuilder::SetArgument().
set_accumulator()
void v8::internal::maglev::InterpreterFrameState::set_accumulator (ValueNode * value) [inline]
Definition at line 629 of file maglev-interpreter-frame-state.h.
                                         {
    // Conversions should be stored in known_node_aspects/NodeInfo.
    DCHECK(!value->properties().is_conversion());
    frame_[interpreter::Register::virtual_accumulator()] = value;
  }
References v8::internal::DCHECK(), frame_, v8::internal::value, and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadContextSlot(), and v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinarySmiOperationNodeForToNumber().
set_known_node_aspects()
void v8::internal::maglev::InterpreterFrameState::set_known_node_aspects (KnownNodeAspects * known_node_aspects) [inline]
Definition at line 664 of file maglev-interpreter-frame-state.h.
                                                                    {
    DCHECK_NOT_NULL(known_node_aspects);
    known_node_aspects_ = known_node_aspects;
  }
References DCHECK_NOT_NULL, known_node_aspects(), and known_node_aspects_.
set_virtual_objects()
void v8::internal::maglev::InterpreterFrameState::set_virtual_objects (const VirtualObjectList & virtual_objects) [inline]
Definition at line 673 of file maglev-interpreter-frame-state.h.
                                                                     {
    virtual_objects_ = virtual_objects;
  }
References virtual_objects(), and virtual_objects_.
virtual_objects()
const VirtualObjectList& v8::internal::maglev::InterpreterFrameState::virtual_objects () const [inline]
Definition at line 672 of file maglev-interpreter-frame-state.h.
{ return virtual_objects_; }
References virtual_objects_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AttachExceptionHandlerInfo(), v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges(), v8::internal::maglev::CompactInterpreterFrameState::CompactInterpreterFrameState(), CopyFrom(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame(), v8::internal::maglev::MaglevGraphBuilder::GetModifiableObjectFromAllocation(), v8::internal::maglev::MaglevGraphBuilder::GetObjectFromAllocation(), v8::internal::maglev::MergePointInterpreterFrameState::InitializeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::Merge(), v8::internal::maglev::MergePointInterpreterFrameState::New(), v8::internal::maglev::MaglevGraphBuilder::PrintVirtualObjects(), and set_virtual_objects().
Member Data Documentation
frame_
RegisterFrameArray<ValueNode*> v8::internal::maglev::InterpreterFrameState::frame_ [private]
Definition at line 678 of file maglev-interpreter-frame-state.h.
Referenced by accumulator(), CopyFrom(), frame(), get(), InterpreterFrameState(), set(), and set_accumulator().
known_node_aspects_
KnownNodeAspects* v8::internal::maglev::InterpreterFrameState::known_node_aspects_ [private]
Definition at line 679 of file maglev-interpreter-frame-state.h.
Referenced by clear_known_node_aspects(), CopyFrom(), known_node_aspects(), and set_known_node_aspects().
virtual_objects_
VirtualObjectList v8::internal::maglev::InterpreterFrameState::virtual_objects_ [private]
Definition at line 680 of file maglev-interpreter-frame-state.h.
Referenced by add_object(), CopyFrom(), set_virtual_objects(), and virtual_objects().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.h