v8::internal::Isolate::PerIsolateThreadData Class Reference
#include <isolate.h>
Public Member Functions
PerIsolateThreadData (Isolate *isolate, ThreadId thread_id)
~PerIsolateThreadData ()
PerIsolateThreadData (const PerIsolateThreadData &)=delete
PerIsolateThreadData & operator= (const PerIsolateThreadData &)=delete
Isolate * isolate () const
ThreadId thread_id () const
bool Matches (Isolate *isolate, ThreadId thread_id) const
Private Attributes
Isolate * isolate_
ThreadId thread_id_
uintptr_t stack_limit_
ThreadState * thread_state_
Friends
class Isolate
class ThreadDataTable
class EntryStackItem
Detailed Description
Definition at line 612 of file isolate.h.
Constructor & Destructor Documentation
PerIsolateThreadData() [1/2]
v8::internal::Isolate::PerIsolateThreadData::PerIsolateThreadData (Isolate * isolate, ThreadId thread_id) [inline]
Definition at line 614 of file isolate.h.
        : isolate_(isolate),
          thread_id_(thread_id),
          stack_limit_(0),
          thread_state_(nullptr)
#if USE_SIMULATOR
          ,
          simulator_(nullptr)
#endif
    {
    }
 PerIsolateThreadData()
v8::internal::Isolate::PerIsolateThreadData::~PerIsolateThreadData ()
Definition at line 3994 of file isolate.cc.
                                                   {
#if defined(USE_SIMULATOR)
  delete simulator_;
#endif
}
PerIsolateThreadData() [2/2]
v8::internal::Isolate::PerIsolateThreadData::PerIsolateThreadData (const PerIsolateThreadData &) [delete]
Member Function Documentation
isolate()
Isolate* v8::internal::Isolate::PerIsolateThreadData::isolate () const [inline]
Definition at line 628 of file isolate.h.
{ return isolate_; }
Referenced by v8::internal::Isolate::Init().
Matches()
bool v8::internal::Isolate::PerIsolateThreadData::Matches (Isolate * isolate, ThreadId thread_id) const [inline]
Definition at line 637 of file isolate.h.
                                                             {
      return isolate_ == isolate && thread_id_ == thread_id;
    }
References v8::internal::anonymous_namespace{thread-id.cc}::thread_id.
operator=()
PerIsolateThreadData& v8::internal::Isolate::PerIsolateThreadData::operator= (const PerIsolateThreadData &) [delete]
thread_id()
ThreadId v8::internal::Isolate::PerIsolateThreadData::thread_id () const [inline]
Definition at line 629 of file isolate.h.
{ return thread_id_; }
Referenced by v8::internal::Isolate::Enter(), v8::internal::CpuSampler::SampleStack(), and v8::internal::Ticker::SampleStack().
Friends And Related Function Documentation
EntryStackItem
friend class EntryStackItem [friend]
Definition at line 653 of file isolate.h.
Isolate
friend class Isolate [friend]
Definition at line 651 of file isolate.h.
ThreadDataTable
friend class ThreadDataTable [friend]
Definition at line 652 of file isolate.h.
Member Data Documentation
isolate_
Isolate* v8::internal::Isolate::PerIsolateThreadData::isolate_ [private]
Definition at line 642 of file isolate.h.
Referenced by v8::internal::Isolate::Enter().
stack_limit_
uintptr_t v8::internal::Isolate::PerIsolateThreadData::stack_limit_ [private]
Definition at line 644 of file isolate.h.
thread_id_
ThreadId v8::internal::Isolate::PerIsolateThreadData::thread_id_ [private]
Definition at line 643 of file isolate.h.
Referenced by v8::internal::Isolate::ThreadDataTable::Insert(), and v8::internal::Isolate::ThreadDataTable::Remove().
thread_state_
ThreadState* v8::internal::Isolate::PerIsolateThreadData::thread_state_ [private]
Definition at line 645 of file isolate.h.
Referenced by v8::internal::Isolate::DiscardPerThreadDataForThisThread().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/isolate.h
/mnt/V8SourceCode/src/execution/isolate.cc