v8::debug::ScriptSource Class Reference
An internal representation of the source for a given v8::debug::Script, which can be a v8::String, in which case it represents JavaScript source, or it can be a managed pointer to a native Wasm module, or it can be undefined to indicate that source is unavailable.
#include <debug-interface.h>
Public Member Functions
size_t Length () const
size_t Size () const
MaybeLocal< String > JavaScriptCode () const
Detailed Description
An internal representation of the source for a given v8::debug::Script, which can be a v8::String, in which case it represents JavaScript source, or it can be a managed pointer to a native Wasm module, or it can be undefined to indicate that source is unavailable.
Definition at line 188 of file debug-interface.h.
Member Function Documentation
JavaScriptCode()
MaybeLocal< String > v8::debug::ScriptSource::JavaScriptCode () const
Definition at line 462 of file debug-interface.cc.
                                                      {
  i::DirectHandle<i::HeapObject> source = Utils::OpenDirectHandle(this);
  if (!IsString(*source)) return MaybeLocal<String>();
  return Utils::ToLocal(i::Cast<i::String>(source));
}
References v8::Utils::OpenDirectHandle().
Length()
size_t v8::debug::ScriptSource::Length () const
Definition at line 441 of file debug-interface.cc.
                                  {
  auto source = Utils::OpenDirectHandle(this);
  if (IsString(*source)) {
    return i::Cast<i::String>(source)->length();
  }
  return Size();
}
References v8::Utils::OpenDirectHandle(), and Size().
Size()
size_t v8::debug::ScriptSource::Size () const
Definition at line 449 of file debug-interface.cc.
                                {
#if V8_ENABLE_WEBASSEMBLY
  MemorySpan<const uint8_t> wasm_bytecode;
  if (WasmBytecode().To(&wasm_bytecode)) {
    return wasm_bytecode.size();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  auto source = Utils::OpenDirectHandle(this);
  if (!IsString(*source)) return 0;
  auto string = i::Cast<i::String>(source);
  return string->length() * (string->IsTwoByteRepresentation() ? 2 : 1);
}
References v8::Utils::OpenDirectHandle(), and v8::MemorySpan< T >::size().
Referenced by Length().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc