cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences Class Reference
Public Member Functions
MovableReferences (HeapBase &heap)
void AddOrFilter (MovableReference *)
void Relocate (Address from, Address to, size_t size_including_header)
void RelocateInteriorReferences (Address from, Address to, size_t size)
void UpdateCallbacks ()
Private Types
using MovableReference = CompactionWorklists::MovableReference
Private Attributes
HeapBase & heap_
std::unordered_map< MovableReference, MovableReference * > movable_references_
std::map< MovableReference *, Address > interior_movable_references_
const bool heap_has_move_listeners_
Detailed Description
Definition at line 38 of file compactor.cc.
Member Typedef Documentation
MovableReference
using cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::MovableReference = CompactionWorklists::MovableReference [private]
Definition at line 39 of file compactor.cc.
Constructor & Destructor Documentation
MovableReferences()
cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::MovableReferences (HeapBase & heap) [inline], [explicit]
Definition at line 42 of file compactor.cc.
      : heap_(heap), heap_has_move_listeners_(heap.HasMoveListeners()) {}
Member Function Documentation
AddOrFilter()
void cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::AddOrFilter (MovableReference * slot)
Definition at line 85 of file compactor.cc.
                                                          {
  const BasePage* slot_page = BasePage::FromInnerAddress(&heap_, slot);
  CHECK_NOT_NULL(slot_page);
  const void* value = *slot;
  if (!value) return;
  // All slots and values are part of Oilpan's heap.
  // - Slots may be contained within dead objects if e.g. the write barrier
  // registered the slot while backing itself has not been marked live in
  // time. Slots in dead objects are filtered below.
  // - Values may only be contained in or point to live objects.
  const HeapObjectHeader& slot_header =
      slot_page->ObjectHeaderFromInnerAddress(slot);
  // Filter the slot since the object that contains the slot is dead.
  if (!slot_header.IsMarked()) return;
  const BasePage* value_page = BasePage::FromInnerAddress(&heap_, value);
  CHECK_NOT_NULL(value_page);
  // The following cases are not compacted and do not require recording:
  // - Compactable object on large pages.
  // - Compactable object on non-compactable spaces.
  if (value_page->is_large() || !value_page->space().is_compactable()) return;
  // Slots must reside in and values must point to live objects at this
  // point. |value| usually points to a separate object but can also point
  // to the an interior pointer in the same object storage which is why the
  // dynamic header lookup is required.
  const HeapObjectHeader& value_header =
      value_page->ObjectHeaderFromInnerAddress(value);
  CHECK(value_header.IsMarked());
  // Slots may have been recorded already but must point to the same value.
  auto reference_it = movable_references_.find(value);
  if (V8_UNLIKELY(reference_it != movable_references_.end())) {
    CHECK_EQ(slot, reference_it->second);
    return;
  }
  // Add regular movable reference.
  movable_references_.emplace(value, slot);
  // Check whether the slot itself resides on a page that is compacted.
  if (V8_LIKELY(!slot_page->space().is_compactable())) return;
  CHECK_EQ(interior_movable_references_.end(),
           interior_movable_references_.find(slot));
  interior_movable_references_.emplace(slot, nullptr);
#if DEBUG
  interior_slot_to_object_.emplace(slot, slot_header.ObjectStart());
#endif // DEBUG
}
References CHECK, CHECK_EQ, CHECK_NOT_NULL, cppgc::internal::BasePage::FromInnerAddress(), cppgc::internal::BaseSpace::is_compactable(), cppgc::internal::BasePage::is_large(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::BasePage::ObjectHeaderFromInnerAddress(), cppgc::internal::HeapObjectHeader::ObjectStart(), cppgc::internal::BasePage::space(), V8_LIKELY, V8_UNLIKELY, and v8::internal::value.
Relocate()
void cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::Relocate (Address from, Address to, size_t size_including_header)
Definition at line 140 of file compactor.cc.
                                                               {
#if DEBUG
  moved_objects_.insert(from);
#endif // DEBUG
  if (V8_UNLIKELY(heap_has_move_listeners_)) {
    heap_.CallMoveListeners(from - sizeof(HeapObjectHeader),
                            to - sizeof(HeapObjectHeader),
                            size_including_header);
  }
  // Interior slots always need to be processed for moved objects.
  // Consider an object A with slot A.x pointing to value B where A is
  // allocated on a movable page itself. When B is finally moved, it needs to
  // find the corresponding slot A.x. Object A may be moved already and the
  // memory may have been freed, which would result in a crash.
  if (!interior_movable_references_.empty()) {
    const HeapObjectHeader& header = HeapObjectHeader::FromObject(to);
    const size_t size = header.ObjectSize();
    RelocateInteriorReferences(from, to, size);
  }
  auto it = movable_references_.find(from);
  // This means that there is no corresponding slot for a live object.
  // This may happen because a mutator may change the slot to point to a
  // different object because e.g. incremental marking marked an object
  // as live that was later on replaced.
  if (it == movable_references_.end()) {
    return;
  }
  // If the object is referenced by a slot that is contained on a compacted
  // area itself, check whether it can be updated already.
  MovableReference* slot = it->second;
  auto interior_it = interior_movable_references_.find(slot);
  if (interior_it != interior_movable_references_.end()) {
    MovableReference* slot_location =
        reinterpret_cast<MovableReference*>(interior_it->second);
    if (!slot_location) {
      interior_it->second = to;
#if DEBUG
      // Check that the containing object has not been moved yet.
      auto reverse_it = interior_slot_to_object_.find(slot);
      DCHECK_NE(interior_slot_to_object_.end(), reverse_it);
      DCHECK_EQ(moved_objects_.end(), moved_objects_.find(reverse_it->second));
#endif // DEBUG
    } else {
      slot = slot_location;
    }
  }
  // Compaction is atomic so slot should not be updated during compaction.
  DCHECK_EQ(from, *slot);
  // Update the slots new value.
  *slot = to;
}
References DCHECK_EQ, DCHECK_NE, cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::HeapObjectHeader::ObjectSize(), size(), and V8_UNLIKELY.
RelocateInteriorReferences()
void cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::RelocateInteriorReferences (Address from, Address to, size_t size)
Definition at line 199 of file compactor.cc.
                                                                {
  // |from| is a valid address for a slot.
  auto interior_it = interior_movable_references_.lower_bound(
      reinterpret_cast<MovableReference*>(from));
  if (interior_it == interior_movable_references_.end()) return;
  DCHECK_GE(reinterpret_cast<Address>(interior_it->first), from);
  size_t offset = reinterpret_cast<Address>(interior_it->first) - from;
  while (offset < size) {
    if (!interior_it->second) {
      // Update the interior reference value, so that when the object the slot
      // is pointing to is moved, it can reuse this value.
      Address reference = to + offset;
      interior_it->second = reference;
      // If the |slot|'s content is pointing into the region [from, from +
      // size) we are dealing with an interior pointer that does not point to
      // a valid HeapObjectHeader. Such references need to be fixed up
      // immediately.
      Address& reference_contents = *reinterpret_cast<Address*>(reference);
      if (reference_contents > from && reference_contents < (from + size)) {
        reference_contents = reference_contents - from + to;
      }
    }
    interior_it++;
    if (interior_it == interior_movable_references_.end()) return;
    offset = reinterpret_cast<Address>(interior_it->first) - from;
  }
}
References DCHECK_GE, and size().
UpdateCallbacks()
void cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::UpdateCallbacks ()
Member Data Documentation
heap_
HeapBase& cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::heap_ [private]
Definition at line 59 of file compactor.cc.
heap_has_move_listeners_
const bool cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::heap_has_move_listeners_ [private]
Definition at line 74 of file compactor.cc.
interior_movable_references_
std::map<MovableReference*, Address> cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::interior_movable_references_ [private]
Definition at line 72 of file compactor.cc.
movable_references_
std::unordered_map<MovableReference, MovableReference*> cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::movable_references_ [private]
Definition at line 64 of file compactor.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/compactor.cc