v8::internal::PlatformEmbeddedFileWriterWin Class Reference
#include <platform-embedded-file-writer-win.h>
Public Member Functions
PlatformEmbeddedFileWriterWin (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os)
void SectionText () override
void SectionRoData () override
void AlignToCodeAlignment () override
void AlignToDataAlignment () override
void DeclareUint32 (const char *name, uint32_t value) override
void DeclareSymbolGlobal (const char *name) override
void DeclareLabel (const char *name) override
void SourceInfo (int fileid, const char *filename, int line) override
void DeclareFunctionBegin (const char *name, uint32_t size) override
void DeclareFunctionEnd (const char *name) override
int HexLiteral (uint64_t value) override
void Comment (const char *string) override
void FilePrologue () override
void DeclareExternalFilename (int fileid, const char *filename) override
void FileEpilogue () override
int IndentedDataDirective (DataDirective directive) override
DataDirective ByteChunkDataDirective () const override
int WriteByteChunk (const uint8_t *data) override
void StartPdataSection ()
void EndPdataSection ()
void StartXdataSection ()
void EndXdataSection ()
void DeclareExternalFunction (const char *name)
void DeclareRvaToSymbol (const char *name, uint64_t offset=0)
void MaybeEmitUnwindData (const char *unwind_info_symbol, const char *embedded_blob_data_symbol, const EmbeddedData *blob, const void *unwind_infos) override
Private Member Functions
const char * DirectiveAsString (DataDirective directive)
Private Attributes
const EmbeddedTargetArch target_arch_
const EmbeddedTargetOs target_os_
Additional Inherited Members
Detailed Description
Definition at line 14 of file platform-embedded-file-writer-win.h.
Constructor & Destructor Documentation
PlatformEmbeddedFileWriterWin()
v8::internal::PlatformEmbeddedFileWriterWin::PlatformEmbeddedFileWriterWin (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os) [inline]
Definition at line 16 of file platform-embedded-file-writer-win.h.
      : target_arch_(target_arch), target_os_(target_os) {
    USE(target_os_);
    DCHECK_EQ(target_os_, EmbeddedTargetOs::kWin);
  }
References DCHECK_EQ, v8::internal::kWin, target_os_, and USE.
Member Function Documentation
AlignToCodeAlignment()
void v8::internal::PlatformEmbeddedFileWriterWin::AlignToCodeAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 611 of file platform-embedded-file-writer-win.cc.
                                                         {
#if V8_TARGET_ARCH_X64
  // On x64 use 64-bytes code alignment to allow 64-bytes loop header alignment.
  static_assert(64 >= kCodeAlignment);
  fprintf(fp_, ".balign 64\n");
#elif V8_TARGET_ARCH_PPC64
  // 64 byte alignment is needed on ppc64 to make sure p10 prefixed instructions
  // don't cross 64-byte boundaries.
  static_assert(64 >= kCodeAlignment);
  fprintf(fp_, ".balign 64\n");
#else
  static_assert(32 >= kCodeAlignment);
  fprintf(fp_, ".balign 32\n");
#endif
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::kCodeAlignment.
AlignToDataAlignment()
void v8::internal::PlatformEmbeddedFileWriterWin::AlignToDataAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 627 of file platform-embedded-file-writer-win.cc.
                                                         {
  // On Windows ARM64, s390, PPC and possibly more platforms, aligned load
  // instructions are used to retrieve v8_Default_embedded_blob_ and/or
  // v8_Default_embedded_blob_size_. The generated instructions require the
  // load target to be aligned at 8 bytes (2^3).
  fprintf(fp_, ".balign 8\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
ByteChunkDataDirective()
DataDirective v8::internal::PlatformEmbeddedFileWriterWin::ByteChunkDataDirective () const [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 697 of file platform-embedded-file-writer-win.cc.
                                                                          {
#if defined(V8_COMPILER_IS_MSVC)
  // Windows MASM doesn't have an .octa directive, use QWORDs instead.
  // Note: MASM *really* does not like large data streams. It takes over 5
  // minutes to assemble the ~350K lines of embedded.S produced when using
  // BYTE directives in a debug build. QWORD produces roughly 120KLOC and
  // reduces assembly time to ~40 seconds. Still terrible, but much better
  // than before. See also: https://crbug.com/v8/8475.
  return kQuad;
#else
  return PlatformEmbeddedFileWriterBase::ByteChunkDataDirective();
#endif
}
References v8::internal::PlatformEmbeddedFileWriterBase::ByteChunkDataDirective(), and v8::internal::kQuad.
Referenced by WriteByteChunk().
Comment()
void v8::internal::PlatformEmbeddedFileWriterWin::Comment (const char * string) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 635 of file platform-embedded-file-writer-win.cc.
                                                              {
  fprintf(fp_, "// %s\n", string);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
DeclareExternalFilename()
void v8::internal::PlatformEmbeddedFileWriterWin::DeclareExternalFilename (int fileid, const char * filename) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 682 of file platform-embedded-file-writer-win.cc.
                                      {
  // BUG(9944): Use .cv_filename to ensure CodeView information is used on
  // Windows.
}
DeclareExternalFunction()
void v8::internal::PlatformEmbeddedFileWriterWin::DeclareExternalFunction (const char * name)
Definition at line 596 of file platform-embedded-file-writer-win.cc.
{}
DeclareFunctionBegin()
void v8::internal::PlatformEmbeddedFileWriterWin::DeclareFunctionBegin (const char * name, uint32_t size) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 650 of file platform-embedded-file-writer-win.cc.
                                                                        {
  DeclareLabel(name);
  if (target_arch_ == EmbeddedTargetArch::kArm64
#if V8_ENABLE_DRUMBRAKE
      || IsDrumBrakeInstructionHandler(name)
#endif // V8_ENABLE_DRUMBRAKE
  ) {
    // Windows ARM64 assembly is in GAS syntax, but ".type" is invalid directive
    // in PE/COFF for Windows.
    DeclareSymbolGlobal(name);
  } else {
    // The directives for inserting debugging information on Windows come
    // from the PE (Portable Executable) and COFF (Common Object File Format)
    // standards. Documented here:
    // https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format
    //
    // .scl 2 means StorageClass external.
    // .type 32 means Type Representation Function.
    fprintf(fp_, ".def %s%s; .scl 2; .type 32; .endef;\n", SYMBOL_PREFIX, name);
  }
}
References DeclareLabel(), DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::kArm64, v8::internal::name, SYMBOL_PREFIX, and target_arch_.
DeclareFunctionEnd()
void v8::internal::PlatformEmbeddedFileWriterWin::DeclareFunctionEnd (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 674 of file platform-embedded-file-writer-win.cc.
{}
DeclareLabel()
void v8::internal::PlatformEmbeddedFileWriterWin::DeclareLabel (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 639 of file platform-embedded-file-writer-win.cc.
                                                                 {
  fprintf(fp_, "%s%s:\n", SYMBOL_PREFIX, name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::name, and SYMBOL_PREFIX.
Referenced by DeclareFunctionBegin(), and DeclareUint32().
DeclareRvaToSymbol()
void v8::internal::PlatformEmbeddedFileWriterWin::DeclareRvaToSymbol (const char * name, uint64_t offset = 0)
Definition at line 598 of file platform-embedded-file-writer-win.cc.
                                                                        {
  if (offset > 0) {
    fprintf(fp_, ".rva %s + %" PRIu64 "\n", name, offset);
  } else {
    fprintf(fp_, ".rva %s\n", name);
  }
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::name.
DeclareSymbolGlobal()
void v8::internal::PlatformEmbeddedFileWriterWin::DeclareSymbolGlobal (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 607 of file platform-embedded-file-writer-win.cc.
                                                                        {
  fprintf(fp_, ".global %s%s\n", SYMBOL_PREFIX, name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::name, and SYMBOL_PREFIX.
Referenced by DeclareFunctionBegin(), and DeclareUint32().
DeclareUint32()
void v8::internal::PlatformEmbeddedFileWriterWin::DeclareUint32 (const char * name, uint32_t value) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 575 of file platform-embedded-file-writer-win.cc.
                                                                  {
  DeclareSymbolGlobal(name);
  DeclareLabel(name);
  IndentedDataDirective(kLong);
  fprintf(fp_, "%d", value);
  Newline();
}
References DeclareLabel(), DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterBase::fp_, IndentedDataDirective(), v8::internal::kLong, v8::internal::name, v8::internal::PlatformEmbeddedFileWriterBase::Newline(), and v8::internal::value.
DirectiveAsString()
const char * v8::internal::PlatformEmbeddedFileWriterWin::DirectiveAsString (DataDirective directive) [private]
Definition at line 275 of file platform-embedded-file-writer-win.cc.
                             {
#if defined(V8_COMPILER_IS_MSVC)
  if (target_arch_ != EmbeddedTargetArch::kArm64) {
    switch (directive) {
      case kByte:
        return "BYTE";
      case kLong:
        return "DWORD";
      case kQuad:
        return "QWORD";
      default:
        UNREACHABLE();
    }
  } else {
    switch (directive) {
      case kByte:
        return "DCB";
      case kLong:
        return "DCDU";
      case kQuad:
        return "DCQU";
      default:
        UNREACHABLE();
    }
  }
#else
  switch (directive) {
    case kByte:
      return ".byte";
    case kLong:
      return ".long";
    case kQuad:
      return ".quad";
    case kOcta:
      return ".octa";
  }
  UNREACHABLE();
#endif
}
References v8::internal::kArm64, v8::internal::kByte, v8::internal::kLong, v8::internal::kOcta, v8::internal::kQuad, target_arch_, and v8::internal::UNREACHABLE().
Referenced by IndentedDataDirective().
EndPdataSection()
void v8::internal::PlatformEmbeddedFileWriterWin::EndPdataSection ()
Definition at line 588 of file platform-embedded-file-writer-win.cc.
{}
EndXdataSection()
void v8::internal::PlatformEmbeddedFileWriterWin::EndXdataSection ()
Definition at line 594 of file platform-embedded-file-writer-win.cc.
{}
FileEpilogue()
void v8::internal::PlatformEmbeddedFileWriterWin::FileEpilogue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 688 of file platform-embedded-file-writer-win.cc.
{}
FilePrologue()
void v8::internal::PlatformEmbeddedFileWriterWin::FilePrologue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 680 of file platform-embedded-file-writer-win.cc.
{}
HexLiteral()
int v8::internal::PlatformEmbeddedFileWriterWin::HexLiteral (uint64_t value) [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 676 of file platform-embedded-file-writer-win.cc.
                                                            {
  return fprintf(fp_, "0x%" PRIx64, value);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::value.
Referenced by WriteByteChunk().
IndentedDataDirective()
int v8::internal::PlatformEmbeddedFileWriterWin::IndentedDataDirective (DataDirective directive) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 690 of file platform-embedded-file-writer-win.cc.
                             {
  return fprintf(fp_, " %s ", DirectiveAsString(directive));
}
References DirectiveAsString(), and v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Referenced by DeclareUint32().
MaybeEmitUnwindData()
void v8::internal::PlatformEmbeddedFileWriterWin::MaybeEmitUnwindData (const char * unwind_info_symbol, const char * embedded_blob_data_symbol, const EmbeddedData * blob, const void * unwind_infos) [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 316 of file platform-embedded-file-writer-win.cc.
                                                        {
// Windows ARM64 supports cross build which could require unwind info for
// host_os. Ignore this case because it is only used in build time.
#if defined(V8_OS_WIN_ARM64)
  if (target_arch_ != EmbeddedTargetArch::kArm64) {
    return;
  }
#endif // V8_OS_WIN_ARM64
#if defined(V8_OS_WIN64)
  if (win64_unwindinfo::CanEmitUnwindInfoForBuiltins()) {
    EmitUnwindData(this, unwind_info_symbol, embedded_blob_data_symbol, blob,
                   reinterpret_cast<const win64_unwindinfo::BuiltinUnwindInfo*>(
                       unwind_infos));
  }
#endif // V8_OS_WIN64
}
References v8::internal::win64_unwindinfo::CanEmitUnwindInfoForBuiltins(), v8::internal::kArm64, and target_arch_.
SectionRoData()
void v8::internal::PlatformEmbeddedFileWriterWin::SectionRoData () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 571 of file platform-embedded-file-writer-win.cc.
                                                  {
  fprintf(fp_, ".section .rdata\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
SectionText()
void v8::internal::PlatformEmbeddedFileWriterWin::SectionText () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 567 of file platform-embedded-file-writer-win.cc.
                                                {
  fprintf(fp_, ".section .text$hot,\"xr\"\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
SourceInfo()
void v8::internal::PlatformEmbeddedFileWriterWin::SourceInfo (int fileid, const char * filename, int line) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 643 of file platform-embedded-file-writer-win.cc.
                                                         {
  // BUG(9944): Use .cv_loc to ensure CodeView information is used on
  // Windows.
}
StartPdataSection()
void v8::internal::PlatformEmbeddedFileWriterWin::StartPdataSection ()
Definition at line 584 of file platform-embedded-file-writer-win.cc.
                                                      {
  fprintf(fp_, ".section .pdata\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
StartXdataSection()
void v8::internal::PlatformEmbeddedFileWriterWin::StartXdataSection ()
Definition at line 590 of file platform-embedded-file-writer-win.cc.
                                                      {
  fprintf(fp_, ".section .xdata\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
WriteByteChunk()
int v8::internal::PlatformEmbeddedFileWriterWin::WriteByteChunk (const uint8_t * data) [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 711 of file platform-embedded-file-writer-win.cc.
                                                                     {
#if defined(V8_COMPILER_IS_MSVC)
  DCHECK_EQ(ByteChunkDataDirective(), kQuad);
  const uint64_t* quad_ptr = reinterpret_cast<const uint64_t*>(data);
  return HexLiteral(*quad_ptr);
#else
  return PlatformEmbeddedFileWriterBase::WriteByteChunk(data);
#endif
}
References ByteChunkDataDirective(), DCHECK_EQ, HexLiteral(), v8::internal::kQuad, and v8::internal::PlatformEmbeddedFileWriterBase::WriteByteChunk().
Member Data Documentation
target_arch_
const EmbeddedTargetArch v8::internal::PlatformEmbeddedFileWriterWin::target_arch_ [private]
Definition at line 70 of file platform-embedded-file-writer-win.h.
Referenced by DeclareFunctionBegin(), DirectiveAsString(), and MaybeEmitUnwindData().
target_os_
const EmbeddedTargetOs v8::internal::PlatformEmbeddedFileWriterWin::target_os_ [private]
Definition at line 71 of file platform-embedded-file-writer-win.h.
Referenced by PlatformEmbeddedFileWriterWin().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-win.h
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-win.cc