v8::CallDepthScope< do_callback > Class Template Reference
#include <api-inl.h>
Public Member Functions
CallDepthScope (i::Isolate *isolate, Local< Context > context)
CallDepthScope (i::Isolate *isolate)
~CallDepthScope ()
CallDepthScope (const CallDepthScope &)=delete
CallDepthScope & operator= (const CallDepthScope &)=delete
Private Attributes
i::Isolate *const isolate_
i::Handle< i::Context > saved_context_
i::Address previous_stack_height_
Friends
class i::ThreadLocalTop
Detailed Description
template<bool do_callback>
class v8::CallDepthScope< do_callback >
Definition at line 153 of file api-inl.h.
Constructor & Destructor Documentation
CallDepthScope() [1/3]
template<bool do_callback>
v8::CallDepthScope< do_callback >::CallDepthScope (i::Isolate * isolate, Local< Context > context) [inline]
Definition at line 155 of file api-inl.h.
      : isolate_(isolate), saved_context_(isolate->context(), isolate_) {
    isolate_->thread_local_top()->IncrementCallDepth<do_callback>(this);
    i::Tagged<i::NativeContext> env = *Utils::OpenDirectHandle(*context);
    isolate->set_context(env);
    if (do_callback) isolate_->FireBeforeCallEnteredCallback();
  }
References v8::Utils::OpenDirectHandle(), and v8::internal::Isolate::set_context().
CallDepthScope() [2/3]
template<bool do_callback>
v8::CallDepthScope< do_callback >::CallDepthScope (i::Isolate * isolate) [inline], [explicit]
Definition at line 163 of file api-inl.h.
                                             : isolate_(isolate) {
    isolate_->thread_local_top()->IncrementCallDepth<do_callback>(this);
    if (do_callback) isolate_->FireBeforeCallEnteredCallback();
  }
 CallDepthScope()
template<bool do_callback>
v8::CallDepthScope< do_callback >::~CallDepthScope () [inline]
Definition at line 168 of file api-inl.h.
                    {
    i::MicrotaskQueue* microtask_queue =
        i::Cast<i::NativeContext>(isolate_->context())
            ->microtask_queue(isolate_);
    isolate_->thread_local_top()->DecrementCallDepth(this);
    // Clear the exception when exiting V8 to avoid memory leaks.
    // Also clear termination exceptions iff there's no TryCatch handler.
    // TODO(verwaest): Drop this once we propagate exceptions to external
    // TryCatch on Throw. This should be debug-only.
    if (isolate_->thread_local_top()->CallDepthIsZero() &&
        (isolate_->thread_local_top()->try_catch_handler_ == nullptr ||
         !isolate_->is_execution_terminating())) {
      isolate_->clear_internal_exception();
    }
    if (do_callback) isolate_->FireCallCompletedCallback(microtask_queue);
#ifdef DEBUG
    if (do_callback) {
      if (microtask_queue && microtask_queue->microtasks_policy() ==
                                 v8::MicrotasksPolicy::kScoped) {
        DCHECK(microtask_queue->GetMicrotasksScopeDepth() ||
               !microtask_queue->DebugMicrotasksScopeDepthIsZero());
      }
    }
    DCHECK(CheckKeptObjectsClearedAfterMicrotaskCheckpoint(microtask_queue));
#endif
    if (!saved_context_.is_null()) isolate_->set_context(*saved_context_);
  }
References DCHECK, v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth(), v8::kScoped, and v8::internal::MicrotaskQueue::microtasks_policy().
CallDepthScope() [3/3]
template<bool do_callback>
v8::CallDepthScope< do_callback >::CallDepthScope (const CallDepthScope< do_callback > &) [delete]
Member Function Documentation
operator=()
template<bool do_callback>
CallDepthScope& v8::CallDepthScope< do_callback >::operator= (const CallDepthScope< do_callback > &) [delete]
References v8::kAuto, and v8::internal::MicrotaskQueue::microtasks_policy().
Friends And Related Function Documentation
i::ThreadLocalTop
template<bool do_callback>
friend class i::ThreadLocalTop [friend]
Definition at line 220 of file api-inl.h.
Member Data Documentation
isolate_
template<bool do_callback>
i::Isolate* const v8::CallDepthScope< do_callback >::isolate_ [private]
Definition at line 215 of file api-inl.h.
previous_stack_height_
template<bool do_callback>
i::Address v8::CallDepthScope< do_callback >::previous_stack_height_ [private]
Definition at line 218 of file api-inl.h.
saved_context_
template<bool do_callback>
i::Handle<i::Context> v8::CallDepthScope< do_callback >::saved_context_ [private]
Definition at line 216 of file api-inl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/api/api-inl.h