v8::internal::compiler::GrowFastElementsParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
GrowFastElementsParameters (GrowFastElementsMode mode, const FeedbackSource &feedback)
GrowFastElementsMode mode () const
const FeedbackSource & feedback () const
Private Attributes
GrowFastElementsMode mode_
FeedbackSource feedback_
Detailed Description
Definition at line 499 of file simplified-operator.h.
Constructor & Destructor Documentation
GrowFastElementsParameters()
v8::internal::compiler::GrowFastElementsParameters::GrowFastElementsParameters (GrowFastElementsMode mode, const FeedbackSource & feedback) [inline]
Definition at line 501 of file simplified-operator.h.
      : mode_(mode), feedback_(feedback) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::GrowFastElementsParameters::feedback () const [inline]
Definition at line 506 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
mode()
GrowFastElementsMode v8::internal::compiler::GrowFastElementsParameters::mode () const [inline]
Definition at line 505 of file simplified-operator.h.
{ return mode_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::GrowFastElementsParameters::feedback_ [private]
Definition at line 510 of file simplified-operator.h.
mode_
GrowFastElementsMode v8::internal::compiler::GrowFastElementsParameters::mode_ [private]
Definition at line 509 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h