v8::internal::torque::ls::JsonGrammar Class Reference
Public Member Functions
JsonGrammar ()
Public Attributes
Symbol trueLiteral = {Rule({Token(`true`)})}
Symbol falseLiteral = {Rule({Token(`false`)})}
Symbol nullLiteral = {Rule({Token(`null`)})}
Symbol decimalLiteral
Symbol stringLiteral
Symbol * elementList = List<JsonValue>(&value, Token(`,`))
Symbol array = {Rule({Token(`[`), elementList, Token(`]`)})}
Symbol member = {Rule({&stringLiteral, Token(`:`), &value}, MakeMember)}
Symbol * memberList = List<JsonMember>(&member, Token(`,`))
Symbol object = {Rule({Token(`{`), memberList, Token(`}`)})}
Symbol value
Symbol file = {Rule({&value})}
Static Private Member Functions
static bool MatchWhitespace (InputPosition *pos)
static bool MatchStringLiteral (InputPosition *pos)
static bool MatchHexLiteral (InputPosition *pos)
static bool MatchDecimalLiteral (InputPosition *pos)
Additional Inherited Members
Detailed Description
Definition at line 84 of file json-parser.cc.
Constructor & Destructor Documentation
JsonGrammar()
v8::internal::torque::ls::JsonGrammar::JsonGrammar () [inline]
Definition at line 150 of file json-parser.cc.
: Grammar(&file) { SetWhitespace(MatchWhitespace); }
References MatchWhitespace(), and v8::internal::torque::Grammar::SetWhitespace().
Member Function Documentation
MatchDecimalLiteral()
static bool v8::internal::torque::ls::JsonGrammar::MatchDecimalLiteral (InputPosition * pos) [inline], [static], [private]
Definition at line 129 of file json-parser.cc.
                                                      {
    InputPosition current = *pos;
    bool found_digit = false;
    MatchString("-", &current);
    while (MatchChar(std::isdigit, &current)) found_digit = true;
    MatchString(".", &current);
    while (MatchChar(std::isdigit, &current)) found_digit = true;
    if (!found_digit) return false;
    *pos = current;
    if ((MatchString("e", &current) || MatchString("E", &current)) &&
        (MatchString("+", &current) || MatchString("-", &current) || true) &&
        MatchChar(std::isdigit, &current)) {
      while (MatchChar(std::isdigit, &current)) {
      }
      *pos = current;
      return true;
    }
    return true;
  }
References v8::internal::torque::Grammar::MatchChar(), and v8::internal::torque::Grammar::MatchString().
MatchHexLiteral()
static bool v8::internal::torque::ls::JsonGrammar::MatchHexLiteral (InputPosition * pos) [inline], [static], [private]
Definition at line 117 of file json-parser.cc.
                                                  {
    InputPosition current = *pos;
    MatchString("-", &current);
    if (MatchString("0x", &current) && MatchChar(std::isxdigit, &current)) {
      while (MatchChar(std::isxdigit, &current)) {
      }
      *pos = current;
      return true;
    }
    return false;
  }
References v8::internal::torque::Grammar::MatchChar(), and v8::internal::torque::Grammar::MatchString().
MatchStringLiteral()
static bool v8::internal::torque::ls::JsonGrammar::MatchStringLiteral (InputPosition * pos) [inline], [static], [private]
Definition at line 91 of file json-parser.cc.
                                                     {
    InputPosition current = *pos;
    if (MatchString("\"", &current)) {
      while (
          (MatchString("\\", &current) && MatchAnyChar(&current)) ||
          MatchChar([](char c) { return c != '"' && c != '\n'; }, &current)) {
      }
      if (MatchString("\"", &current)) {
        *pos = current;
        return true;
      }
    }
    current = *pos;
    if (MatchString("'", &current)) {
      while (
          (MatchString("\\", &current) && MatchAnyChar(&current)) ||
          MatchChar([](char c) { return c != '\'' && c != '\n'; }, &current)) {
      }
      if (MatchString("'", &current)) {
        *pos = current;
        return true;
      }
    }
    return false;
  }
References v8::internal::torque::Grammar::MatchAnyChar(), v8::internal::torque::Grammar::MatchChar(), and v8::internal::torque::Grammar::MatchString().
MatchWhitespace()
static bool v8::internal::torque::ls::JsonGrammar::MatchWhitespace (InputPosition * pos) [inline], [static], [private]
Definition at line 85 of file json-parser.cc.
                                                  {
    while (MatchChar(std::isspace, pos)) {
    }
    return true;
  }
References v8::internal::torque::Grammar::MatchChar().
Referenced by JsonGrammar().
Member Data Documentation
array
Symbol v8::internal::torque::ls::JsonGrammar::array = {Rule({Token(`[`), elementList, Token(`]`)})}
Definition at line 164 of file json-parser.cc.
decimalLiteral
Symbol v8::internal::torque::ls::JsonGrammar::decimalLiteral
Initial value:
= {
      Rule({Pattern(MatchDecimalLiteral)}, YieldMatchedInput),
      Rule({Pattern(MatchHexLiteral)}, YieldMatchedInput)}
Definition at line 156 of file json-parser.cc.
elementList
Symbol* v8::internal::torque::ls::JsonGrammar::elementList = List<JsonValue>(&value, Token(`,`))
Definition at line 163 of file json-parser.cc.
falseLiteral
Symbol v8::internal::torque::ls::JsonGrammar::falseLiteral = {Rule({Token(`false`)})}
Definition at line 153 of file json-parser.cc.
file
Symbol v8::internal::torque::ls::JsonGrammar::file = {Rule({&value})}
Definition at line 178 of file json-parser.cc.
member
Symbol v8::internal::torque::ls::JsonGrammar::member = {Rule({&stringLiteral, Token(`:`), &value}, MakeMember)}
Definition at line 166 of file json-parser.cc.
memberList
Symbol* v8::internal::torque::ls::JsonGrammar::memberList = List<JsonMember>(&member, Token(`,`))
Definition at line 167 of file json-parser.cc.
nullLiteral
Symbol v8::internal::torque::ls::JsonGrammar::nullLiteral = {Rule({Token(`null`)})}
Definition at line 154 of file json-parser.cc.
object
Symbol v8::internal::torque::ls::JsonGrammar::object = {Rule({Token(`{`), memberList, Token(`}`)})}
Definition at line 168 of file json-parser.cc.
stringLiteral
Symbol v8::internal::torque::ls::JsonGrammar::stringLiteral
Initial value:
= {
      Rule({Pattern(MatchStringLiteral)}, YieldMatchedInput)}
Definition at line 160 of file json-parser.cc.
trueLiteral
Symbol v8::internal::torque::ls::JsonGrammar::trueLiteral = {Rule({Token(`true`)})}
Definition at line 152 of file json-parser.cc.
value
Symbol v8::internal::torque::ls::JsonGrammar::value
Initial value:
= {Rule({&trueLiteral}, MakeBoolLiteral<true>),
                  Rule({&falseLiteral}, MakeBoolLiteral<false>),
                  Rule({&nullLiteral}, MakeNullLiteral),
                  Rule({&decimalLiteral}, MakeNumberLiteral),
                  Rule({&stringLiteral}, MakeStringLiteral),
                  Rule({&object}, MakeObject),
                  Rule({&array}, MakeArray)}
Definition at line 170 of file json-parser.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/ls/json-parser.cc