v8::internal::FieldStatsCollector Class Reference
Classes
struct JSObjectFieldStats
Public Member Functions
FieldStatsCollector (Heap *heap, size_t *tagged_fields_count, size_t *embedder_fields_count, size_t *inobject_smi_fields_count, size_t *boxed_double_fields_count, size_t *string_data_count, size_t *raw_fields_count)
void RecordStats (Tagged< HeapObject > host)
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) override
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitMapPointer (Tagged< HeapObject > host) override
Private Member Functions
JSObjectFieldStats GetInobjectFieldStats (Tagged< Map > map)
Private Attributes
std::unordered_map< Tagged< Map >, JSObjectFieldStats, Object::Hasher > field_stats_cache_
Heap *const heap_
size_t *const tagged_fields_count_
size_t *const embedder_fields_count_
size_t *const inobject_smi_fields_count_
size_t *const boxed_double_fields_count_
size_t *const string_data_count_
size_t *const raw_fields_count_
Detailed Description
Definition at line 41 of file object-stats.cc.
Constructor & Destructor Documentation
FieldStatsCollector()
v8::internal::FieldStatsCollector::FieldStatsCollector (Heap * heap, size_t * tagged_fields_count, size_t * embedder_fields_count, size_t * inobject_smi_fields_count, size_t * boxed_double_fields_count, size_t * string_data_count, size_t * raw_fields_count) [inline]
Definition at line 43 of file object-stats.cc.
      : ObjectVisitorWithCageBases(heap),
        heap_(heap),
        tagged_fields_count_(tagged_fields_count),
        embedder_fields_count_(embedder_fields_count),
        inobject_smi_fields_count_(inobject_smi_fields_count),
        boxed_double_fields_count_(boxed_double_fields_count),
        string_data_count_(string_data_count),
        raw_fields_count_(raw_fields_count) {}
Member Function Documentation
GetInobjectFieldStats()
FieldStatsCollector::JSObjectFieldStats v8::internal::FieldStatsCollector::GetInobjectFieldStats (Tagged< Map > map) [private]
Definition at line 147 of file object-stats.cc.
                                                          {
  auto iter = field_stats_cache_.find(map);
  if (iter != field_stats_cache_.end()) {
    return iter->second;
  }
  // Iterate descriptor array and calculate stats.
  JSObjectFieldStats stats;
  stats.embedded_fields_count_ = JSObject::GetEmbedderFieldCount(map);
  if (!map->is_dictionary_map()) {
    Tagged<DescriptorArray> descriptors = map->instance_descriptors();
    for (InternalIndex descriptor : map->IterateOwnDescriptors()) {
      PropertyDetails details = descriptors->GetDetails(descriptor);
      if (details.location() == PropertyLocation::kField) {
        FieldIndex index = FieldIndex::ForDetails(map, details);
        // Stop on first out-of-object field.
        if (!index.is_inobject()) break;
        if (details.representation().IsSmi()) {
          ++stats.smi_fields_count_;
        }
      }
    }
  }
  field_stats_cache_.insert(std::make_pair(map, stats));
  return stats;
}
References v8::internal::FieldStatsCollector::JSObjectFieldStats::embedded_fields_count_, field_stats_cache_, v8::internal::FieldIndex::ForDetails(), v8::internal::JSObject::GetEmbedderFieldCount(), v8::internal::index, v8::internal::Representation::IsSmi(), v8::internal::kField, v8::internal::PropertyDetails::location(), v8::internal::PropertyDetails::representation(), and v8::internal::FieldStatsCollector::JSObjectFieldStats::smi_fields_count_.
Referenced by RecordStats().
RecordStats()
void v8::internal::FieldStatsCollector::RecordStats (Tagged< HeapObject > host) [inline]
Definition at line 57 of file object-stats.cc.
                                            {
    size_t old_pointer_fields_count = *tagged_fields_count_;
    VisitObject(heap_->isolate(), host, this);
    size_t tagged_fields_count_in_object =
        *tagged_fields_count_ - old_pointer_fields_count;
    int object_size_in_words = host->Size(cage_base()) / kTaggedSize;
    DCHECK_LE(tagged_fields_count_in_object, object_size_in_words);
    size_t raw_fields_count_in_object =
        object_size_in_words - tagged_fields_count_in_object;
    if (IsJSObject(host, cage_base())) {
      JSObjectFieldStats field_stats = GetInobjectFieldStats(host->map());
      // Embedder fields are already included into pointer words.
      DCHECK_LE(field_stats.embedded_fields_count_,
                tagged_fields_count_in_object);
      tagged_fields_count_in_object -= field_stats.embedded_fields_count_;
      *tagged_fields_count_ -= field_stats.embedded_fields_count_;
      *embedder_fields_count_ += field_stats.embedded_fields_count_;
      // Smi fields are also included into pointer words.
      tagged_fields_count_in_object -= field_stats.smi_fields_count_;
      *tagged_fields_count_ -= field_stats.smi_fields_count_;
      *inobject_smi_fields_count_ += field_stats.smi_fields_count_;
    } else if (IsHeapNumber(host, cage_base())) {
      DCHECK_LE(kDoubleSize / kTaggedSize, raw_fields_count_in_object);
      raw_fields_count_in_object -= kDoubleSize / kTaggedSize;
      *boxed_double_fields_count_ += 1;
    } else if (IsSeqString(host, cage_base())) {
      int string_data =
          Cast<SeqString>(host)->length(kAcquireLoad) *
          (Cast<String>(host)->IsOneByteRepresentation() ? 1 : 2) / kTaggedSize;
      DCHECK_LE(string_data, raw_fields_count_in_object);
      raw_fields_count_in_object -= string_data;
      *string_data_count_ += string_data;
    }
    *raw_fields_count_ += raw_fields_count_in_object;
  }
References boxed_double_fields_count_, v8::internal::ObjectVisitorWithCageBases::cage_base(), DCHECK_LE, v8::internal::FieldStatsCollector::JSObjectFieldStats::embedded_fields_count_, embedder_fields_count_, GetInobjectFieldStats(), heap_, inobject_smi_fields_count_, v8::internal::Heap::isolate(), v8::internal::InstanceTypeChecker::IsSeqString(), v8::kAcquireLoad, v8::internal::kDoubleSize, v8::internal::kTaggedSize, raw_fields_count_, v8::internal::FieldStatsCollector::JSObjectFieldStats::smi_fields_count_, string_data_count_, tagged_fields_count_, and v8::internal::VisitObject().
Referenced by v8::internal::ObjectStatsCollectorImpl::CollectStatistics().
VisitCodeTarget()
void v8::internal::FieldStatsCollector::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 110 of file object-stats.cc.
                                                  {
    // InstructionStream target is most likely encoded as a relative 32-bit
    // offset and not as a full tagged value, so there's nothing to count.
  }
VisitEmbeddedPointer()
void v8::internal::FieldStatsCollector::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 116 of file object-stats.cc.
                                                       {
    *tagged_fields_count_ += 1;
  }
References tagged_fields_count_.
VisitInstructionStreamPointer()
void v8::internal::FieldStatsCollector::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 105 of file object-stats.cc.
                                                              {
    *tagged_fields_count_ += 1;
  }
References tagged_fields_count_.
VisitMapPointer()
void v8::internal::FieldStatsCollector::VisitMapPointer (Tagged< HeapObject > host) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 121 of file object-stats.cc.
                                                         {
    // Just do nothing, but avoid the inherited UNREACHABLE implementation.
  }
VisitPointers() [1/2]
void v8::internal::FieldStatsCollector::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 100 of file object-stats.cc.
                                                   {
    *tagged_fields_count_ += (end - start);
  }
References v8::internal::compiler::end(), and tagged_fields_count_.
VisitPointers() [2/2]
void v8::internal::FieldStatsCollector::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 96 of file object-stats.cc.
                                              {
    *tagged_fields_count_ += (end - start);
  }
References v8::internal::compiler::end(), and tagged_fields_count_.
Member Data Documentation
boxed_double_fields_count_
size_t* const v8::internal::FieldStatsCollector::boxed_double_fields_count_ [private]
Definition at line 141 of file object-stats.cc.
Referenced by RecordStats().
embedder_fields_count_
size_t* const v8::internal::FieldStatsCollector::embedder_fields_count_ [private]
Definition at line 139 of file object-stats.cc.
Referenced by RecordStats().
field_stats_cache_
std::unordered_map<Tagged<Map>, JSObjectFieldStats, Object::Hasher> v8::internal::FieldStatsCollector::field_stats_cache_ [private]
Definition at line 133 of file object-stats.cc.
Referenced by GetInobjectFieldStats().
heap_
Heap* const v8::internal::FieldStatsCollector::heap_ [private]
Definition at line 137 of file object-stats.cc.
Referenced by RecordStats().
inobject_smi_fields_count_
size_t* const v8::internal::FieldStatsCollector::inobject_smi_fields_count_ [private]
Definition at line 140 of file object-stats.cc.
Referenced by RecordStats().
raw_fields_count_
size_t* const v8::internal::FieldStatsCollector::raw_fields_count_ [private]
Definition at line 143 of file object-stats.cc.
Referenced by RecordStats().
string_data_count_
size_t* const v8::internal::FieldStatsCollector::string_data_count_ [private]
Definition at line 142 of file object-stats.cc.
Referenced by RecordStats().
tagged_fields_count_
size_t* const v8::internal::FieldStatsCollector::tagged_fields_count_ [private]
Definition at line 138 of file object-stats.cc.
Referenced by RecordStats(), VisitEmbeddedPointer(), VisitInstructionStreamPointer(), and VisitPointers().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/object-stats.cc