v8_inspector::InjectedScript::ObjectScope Class Reference
#include <injected-script.h>
Public Member Functions
ObjectScope (V8InspectorSessionImpl *, const String16 &remoteObjectId)
~ObjectScope () override
ObjectScope (const ObjectScope &)=delete
ObjectScope & operator= (const ObjectScope &)=delete
const String16 & objectGroupName () const
v8::Local< v8::Value > object () const
Private Member Functions
Response findInjectedScript (V8InspectorSessionImpl *) override
Private Attributes
String16 m_remoteObjectId
String16 m_objectGroupName
v8::Local< v8::Value > m_object
Additional Inherited Members
Detailed Description
Definition at line 203 of file injected-script.h.
Constructor & Destructor Documentation
ObjectScope() [1/2]
v8_inspector::InjectedScript::ObjectScope::ObjectScope (V8InspectorSessionImpl * session, const String16 & remoteObjectId)
Definition at line 1106 of file injected-script.cc.
    : InjectedScript::Scope(session), m_remoteObjectId(remoteObjectId) {}
 ObjectScope()
v8_inspector::InjectedScript::ObjectScope::~ObjectScope () [override], [default]
ObjectScope() [2/2]
v8_inspector::InjectedScript::ObjectScope::ObjectScope (const ObjectScope &) [delete]
Member Function Documentation
findInjectedScript()
Response v8_inspector::InjectedScript::ObjectScope::findInjectedScript (V8InspectorSessionImpl * session) [override], [private], [virtual]
Implements v8_inspector::InjectedScript::Scope.
Definition at line 1112 of file injected-script.cc.
                                     {
  std::unique_ptr<RemoteObjectId> remoteId;
  Response response = RemoteObjectId::parse(m_remoteObjectId, &remoteId);
  if (!response.IsSuccess()) return response;
  InjectedScript* injectedScript = nullptr;
  response = session->findInjectedScript(remoteId.get(), injectedScript);
  if (!response.IsSuccess()) return response;
  m_objectGroupName = injectedScript->objectGroupName(*remoteId);
  response = injectedScript->findObject(*remoteId, &m_object);
  if (!response.IsSuccess()) return response;
  m_injectedScript = injectedScript;
  return Response::Success();
}
References v8_inspector::V8InspectorSessionImpl::findInjectedScript(), v8_inspector::InjectedScript::findObject(), v8_inspector::InjectedScript::objectGroupName(), and v8_inspector::RemoteObjectId::parse().
object()
v8::Local<v8::Value> v8_inspector::InjectedScript::ObjectScope::object () const [inline]
Definition at line 210 of file injected-script.h.
{ return m_object; }
References m_object.
Referenced by v8_inspector::V8RuntimeAgentImpl::awaitPromise(), v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8_inspector::V8RuntimeAgentImpl::getExceptionDetails(), v8_inspector::V8RuntimeAgentImpl::getProperties(), v8_inspector::V8RuntimeAgentImpl::queryObjects(), and v8_inspector::V8DebuggerAgentImpl::setBreakpointOnFunctionCall().
objectGroupName()
const String16& v8_inspector::InjectedScript::ObjectScope::objectGroupName () const [inline]
Definition at line 209 of file injected-script.h.
{ return m_objectGroupName; }
References m_objectGroupName.
Referenced by v8_inspector::V8RuntimeAgentImpl::awaitPromise(), v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8_inspector::V8RuntimeAgentImpl::getExceptionDetails(), v8_inspector::V8RuntimeAgentImpl::getProperties(), and v8_inspector::V8RuntimeAgentImpl::queryObjects().
operator=()
ObjectScope& v8_inspector::InjectedScript::ObjectScope::operator= (const ObjectScope &) [delete]
Member Data Documentation
m_object
v8::Local<v8::Value> v8_inspector::InjectedScript::ObjectScope::m_object [private]
Definition at line 216 of file injected-script.h.
Referenced by object().
m_objectGroupName
String16 v8_inspector::InjectedScript::ObjectScope::m_objectGroupName [private]
Definition at line 215 of file injected-script.h.
Referenced by objectGroupName().
m_remoteObjectId
String16 v8_inspector::InjectedScript::ObjectScope::m_remoteObjectId [private]
Definition at line 214 of file injected-script.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/injected-script.h
/mnt/V8SourceCode/src/inspector/injected-script.cc