v8::internal::Assembler::Trampoline Class Reference
Public Member Functions
Trampoline ()
Trampoline (int start, int slot_count)
int start ()
int end ()
int take_slot ()
Trampoline ()
Trampoline (int start, int slot_count)
int start ()
int end ()
int take_slot ()
Trampoline ()
Trampoline (int start, int slot_count)
int take_slot ()
Trampoline ()
Trampoline (int start, int slot_count)
int start ()
int end ()
int take_slot ()
Private Attributes
int start_
int end_
int next_slot_
int free_slot_count_
Detailed Description
Definition at line 1037 of file assembler-loong64.h.
Constructor & Destructor Documentation
Trampoline() [1/8]
v8::internal::Assembler::Trampoline::Trampoline () [inline]
Definition at line 1039 of file assembler-loong64.h.
                 {
      start_ = 0;
      next_slot_ = 0;
      free_slot_count_ = 0;
      end_ = 0;
    }
Trampoline() [2/8]
v8::internal::Assembler::Trampoline::Trampoline (int start, int slot_count) [inline]
Definition at line 1045 of file assembler-loong64.h.
                                          {
      start_ = start;
      next_slot_ = start;
      free_slot_count_ = slot_count;
      end_ = start + slot_count * kTrampolineSlotsSize;
    }
Trampoline() [3/8]
v8::internal::Assembler::Trampoline::Trampoline () [inline]
Definition at line 1851 of file assembler-mips64.h.
                 {
      start_ = 0;
      next_slot_ = 0;
      free_slot_count_ = 0;
      end_ = 0;
    }
Trampoline() [4/8]
v8::internal::Assembler::Trampoline::Trampoline (int start, int slot_count) [inline]
Definition at line 1857 of file assembler-mips64.h.
                                          {
      start_ = start;
      next_slot_ = start;
      free_slot_count_ = slot_count;
      end_ = start + slot_count * kTrampolineSlotsSize;
    }
Trampoline() [5/8]
v8::internal::Assembler::Trampoline::Trampoline () [inline]
Definition at line 1480 of file assembler-ppc.h.
                 {
      next_slot_ = 0;
      free_slot_count_ = 0;
    }
References free_slot_count_, and next_slot_.
Trampoline() [6/8]
v8::internal::Assembler::Trampoline::Trampoline (int start, int slot_count) [inline]
Definition at line 1484 of file assembler-ppc.h.
                                          {
      next_slot_ = start;
      free_slot_count_ = slot_count;
    }
References free_slot_count_, next_slot_, and start().
Trampoline() [7/8]
v8::internal::Assembler::Trampoline::Trampoline () [inline]
Definition at line 853 of file assembler-riscv.h.
                 {
      start_ = 0;
      next_slot_ = 0;
      free_slot_count_ = 0;
      end_ = 0;
    }
Trampoline() [8/8]
v8::internal::Assembler::Trampoline::Trampoline (int start, int slot_count) [inline]
Definition at line 859 of file assembler-riscv.h.
                                          {
      start_ = start;
      next_slot_ = start;
      free_slot_count_ = slot_count;
      end_ = start + slot_count * kTrampolineSlotsSize;
    }
Member Function Documentation
end() [1/3]
int v8::internal::Assembler::Trampoline::end () [inline]
Definition at line 1052 of file assembler-loong64.h.
{ return end_; }
end() [2/3]
int v8::internal::Assembler::Trampoline::end () [inline]
Definition at line 1864 of file assembler-mips64.h.
{ return end_; }
end() [3/3]
int v8::internal::Assembler::Trampoline::end () [inline]
Definition at line 866 of file assembler-riscv.h.
{ return end_; }
start() [1/3]
int v8::internal::Assembler::Trampoline::start () [inline]
Definition at line 1051 of file assembler-loong64.h.
{ return start_; }
Referenced by v8::internal::Assembler::get_trampoline_entry(), and Trampoline().
start() [2/3]
int v8::internal::Assembler::Trampoline::start () [inline]
Definition at line 1863 of file assembler-mips64.h.
{ return start_; }
start() [3/3]
int v8::internal::Assembler::Trampoline::start () [inline]
Definition at line 865 of file assembler-riscv.h.
{ return start_; }
take_slot() [1/4]
int v8::internal::Assembler::Trampoline::take_slot () [inline]
Definition at line 1053 of file assembler-loong64.h.
                    {
      int trampoline_slot = kInvalidSlotPos;
      if (free_slot_count_ <= 0) {
        // We have run out of space on trampolines.
        // Make sure we fail in debug mode, so we become aware of each case
        // when this happens.
        DCHECK(0);
        // Internal exception will be caught.
      } else {
        trampoline_slot = next_slot_;
        free_slot_count_--;
        next_slot_ += kTrampolineSlotsSize;
      }
      return trampoline_slot;
    }
References v8::internal::DCHECK().
Referenced by v8::internal::Assembler::get_trampoline_entry().
take_slot() [2/4]
int v8::internal::Assembler::Trampoline::take_slot () [inline]
Definition at line 1865 of file assembler-mips64.h.
                    {
      int trampoline_slot = kInvalidSlotPos;
      if (free_slot_count_ <= 0) {
        // We have run out of space on trampolines.
        // Make sure we fail in debug mode, so we become aware of each case
        // when this happens.
        DCHECK(0);
        // Internal exception will be caught.
      } else {
        trampoline_slot = next_slot_;
        free_slot_count_--;
        next_slot_ += kTrampolineSlotsSize;
      }
      return trampoline_slot;
    }
References v8::internal::DCHECK().
take_slot() [3/4]
int v8::internal::Assembler::Trampoline::take_slot () [inline]
Definition at line 1488 of file assembler-ppc.h.
                    {
      int trampoline_slot = kInvalidSlotPos;
      if (free_slot_count_ <= 0) {
        // We have run out of space on trampolines.
        // Make sure we fail in debug mode, so we become aware of each case
        // when this happens.
        DCHECK(0);
        // Internal exception will be caught.
      } else {
        trampoline_slot = next_slot_;
        free_slot_count_--;
        next_slot_ += kTrampolineSlotsSize;
      }
      return trampoline_slot;
    }
References v8::internal::DCHECK(), free_slot_count_, v8::internal::Assembler::kInvalidSlotPos, v8::internal::Assembler::kTrampolineSlotsSize, and next_slot_.
take_slot() [4/4]
int v8::internal::Assembler::Trampoline::take_slot () [inline]
Definition at line 867 of file assembler-riscv.h.
                    {
      int trampoline_slot = kInvalidSlotPos;
      if (free_slot_count_ <= 0) {
        // We have run out of space on trampolines.
        // Make sure we fail in debug mode, so we become aware of each case
        // when this happens.
        DCHECK(0);
        // Internal exception will be caught.
      } else {
        trampoline_slot = next_slot_;
        free_slot_count_--;
        next_slot_ += kTrampolineSlotsSize;
        DEBUG_PRINTF("\ttrampoline slot %d next %d free %d\n", trampoline_slot,
                     next_slot_, free_slot_count_)
      }
      return trampoline_slot;
    }
References v8::internal::DCHECK(), and DEBUG_PRINTF.
Member Data Documentation
end_
int v8::internal::Assembler::Trampoline::end_ [private]
Definition at line 1071 of file assembler-loong64.h.
free_slot_count_
int v8::internal::Assembler::Trampoline::free_slot_count_ [private]
Definition at line 1073 of file assembler-loong64.h.
Referenced by take_slot(), and Trampoline().
next_slot_
int v8::internal::Assembler::Trampoline::next_slot_ [private]
Definition at line 1072 of file assembler-loong64.h.
Referenced by take_slot(), and Trampoline().
start_
int v8::internal::Assembler::Trampoline::start_ [private]
Definition at line 1070 of file assembler-loong64.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.h