v8::base::ContextualVariable< Derived, VarType > Class Template Reference
#include <contextual.h>
Classes
class Scope
Public Types
using VarT = VarType
Static Public Member Functions
static VarType & Get ()
static bool HasScope ()
Static Private Member Functions
static Scope *& Top ()
static Scope *& ExportedTop ()
Static Private Attributes
static thread_local Scope * top_ = nullptr
Detailed Description
template<class Derived, class VarType>
class v8::base::ContextualVariable< Derived, VarType >
Definition at line 27 of file contextual.h.
Member Typedef Documentation
VarT
template<class Derived , class VarType >
using v8::base::ContextualVariable< Derived, VarType >::VarT = VarType
Definition at line 29 of file contextual.h.
Member Function Documentation
ExportedTop()
template<class Derived , class VarType >
static Scope*& v8::base::ContextualVariable< Derived, VarType >::ExportedTop () [static], [private]
Get()
template<class Derived , class VarType >
static VarType& v8::base::ContextualVariable< Derived, VarType >::Get () [inline], [static]
Definition at line 64 of file contextual.h.
                        {
    DCHECK(HasScope());
    return Top()->Value();
  }
References DCHECK.
Referenced by v8::internal::torque::SourceFileMap::AbsolutePath(), v8::internal::torque::KytheData::AddBindingDefinitionImpl(), v8::internal::torque::KytheData::AddBindingUse(), v8::internal::torque::KytheData::AddCall(), v8::internal::torque::KytheData::AddClassFieldDefinition(), v8::internal::torque::KytheData::AddClassFieldUse(), v8::internal::torque::KytheData::AddConstantDefinition(), v8::internal::torque::KytheData::AddConstantUse(), v8::internal::torque::GlobalContext::AddCppInclude(), v8::internal::torque::LanguageServerData::AddDefinition(), v8::internal::torque::KytheData::AddFunctionDefinition(), v8::internal::torque::SourceFileMap::AddSource(), v8::internal::torque::KytheData::AddTypeDefinition(), v8::internal::torque::KytheData::AddTypeUse(), v8::internal::torque::TypeOracle::AllBuiltinPointerTypes(), v8::internal::torque::GlobalContext::AllDeclarables(), v8::internal::torque::GlobalContext::AllMacrosForCCDebugOutput(), v8::internal::torque::GlobalContext::AllMacrosForCCOutput(), v8::internal::torque::SourceFileMap::AllSources(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Analyze(), v8::internal::torque::GlobalContext::annotate_ir(), v8::internal::torque::GlobalContext::ast(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::GlobalContext::collect_language_server_data(), v8::internal::torque::ls::CompilationFinished(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), v8::internal::torque::CompileTorque(), v8::internal::torque::CompileTorqueForKythe(), v8::internal::torque::TargetArchitecture::CppHeapPointerSize(), v8::internal::torque::GlobalContext::CppIncludes(), v8::internal::torque::Logger::Enable(), v8::internal::torque::Logger::Enabled(), v8::internal::torque::GlobalContext::EnsureInCCDebugOutputList(), v8::internal::torque::GlobalContext::EnsureInCCOutputList(), v8::internal::torque::TargetArchitecture::ExternalPointerSize(), v8::internal::torque::SourceFileMap::FileRelativeToV8RootExists(), v8::internal::torque::TypeOracle::FinalizeAggregateTypes(), v8::internal::torque::LanguageServerData::FindDefinition(), v8::internal::torque::Logger::Flush(), v8::internal::torque::GlobalContext::force_assert_statements(), v8::internal::torque::TypeOracle::FreshTypeId(), v8::internal::torque::GlobalContext::GeneratedPerFile(), v8::internal::torque::TypeOracle::GetAbstractType(), v8::internal::torque::TypeOracle::GetAggregateTypes(), v8::internal::torque::TypeOracle::GetArgumentsType(), v8::internal::torque::TypeOracle::GetBitFieldStructType(), v8::internal::torque::TypeOracle::GetBitFieldStructTypes(), v8::internal::torque::TypeOracle::GetBoolType(), v8::internal::torque::TypeOracle::GetBuiltinPointerType(), v8::internal::torque::TypeOracle::GetClassType(), v8::internal::torque::TypeOracle::GetConstexprBoolType(), v8::internal::torque::TypeOracle::GetConstexprInstanceTypeType(), v8::internal::torque::TypeOracle::GetConstexprIntPtrType(), v8::internal::torque::TypeOracle::GetConstexprStringType(), v8::internal::torque::TypeOracle::GetConstFloat64Type(), v8::internal::torque::TypeOracle::GetConstInt31Type(), v8::internal::torque::TypeOracle::GetConstInt32Type(), v8::internal::torque::TypeOracle::GetConstStringType(), v8::internal::torque::TypeOracle::GetContextType(), v8::internal::torque::TypeOracle::GetCppHeapPointerType(), v8::internal::torque::GlobalContext::GetDefaultNamespace(), v8::internal::torque::TypeOracle::GetDispatchHandleType(), v8::internal::torque::TypeOracle::GetExternalPointerType(), v8::internal::torque::TypeOracle::GetFixedArrayBaseType(), v8::internal::torque::BuildFlags::GetFlag(), v8::internal::torque::TypeOracle::GetFloat64OrUndefinedOrHoleType(), v8::internal::torque::TypeOracle::GetFloat64Type(), v8::internal::torque::TypeOracle::GetHeapObjectType(), v8::internal::torque::TypeOracle::GetInt16Type(), v8::internal::torque::TypeOracle::GetInt32Type(), v8::internal::torque::TypeOracle::GetInt64Type(), v8::internal::torque::TypeOracle::GetInt8Type(), v8::internal::torque::TypeOracle::GetIntegerLiteralType(), v8::internal::torque::TypeOracle::GetIntPtrType(), v8::internal::torque::TypeOracle::GetJSAnyType(), v8::internal::torque::TypeOracle::GetJSFunctionType(), v8::internal::torque::TypeOracle::GetJSObjectType(), v8::internal::torque::TypeOracle::GetMapType(), v8::internal::torque::TypeOracle::GetNativeContextType(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::TypeOracle::GetNoContextType(), v8::internal::torque::TypeOracle::GetNumberType(), v8::internal::torque::TypeOracle::GetObjectType(), v8::internal::torque::TypeOracle::GetProtectedPointerType(), v8::internal::torque::TypeOracle::GetRawPtrType(), v8::internal::torque::TypeOracle::GetSmiType(), v8::internal::torque::SourceFileMap::GetSourceId(), v8::internal::torque::TypeOracle::GetStringType(), v8::internal::torque::TypeOracle::GetStrongTaggedType(), v8::internal::torque::TypeOracle::GetStructType(), v8::internal::torque::TypeOracle::GetTaggedType(), v8::internal::torque::TypeOracle::GetTaggedZeroPatternType(), v8::internal::torque::TypeOracle::GetTopType(), v8::internal::torque::TypeOracle::GetTrustedPointerType(), v8::internal::torque::TypeOracle::GetUint16Type(), v8::internal::torque::TypeOracle::GetUint31Type(), v8::internal::torque::TypeOracle::GetUint32Type(), v8::internal::torque::TypeOracle::GetUint64Type(), v8::internal::torque::TypeOracle::GetUint8Type(), v8::internal::torque::TypeOracle::GetUIntPtrType(), v8::internal::torque::TypeOracle::GetUninitializedHeapObjectType(), v8::internal::torque::TypeOracle::GetUninitializedIteratorType(), v8::internal::torque::TypeOracle::GetUnionType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::GlobalContext::IsInstanceTypesInitialized(), v8::internal::torque::GlobalContext::MakeUniqueName(), v8::internal::torque::SourceFileMap::PathFromV8Root(), v8::internal::torque::TargetArchitecture::RawPtrSize(), v8::internal::torque::RegisterDeclarable(), v8::internal::torque::GlobalContext::SetAnnotateIR(), v8::internal::torque::GlobalContext::SetCollectKytheData(), v8::internal::torque::GlobalContext::SetCollectLanguageServerData(), v8::internal::torque::KytheData::SetConsumer(), v8::internal::torque::GlobalContext::SetForceAssertStatements(), v8::internal::torque::LanguageServerData::SetGlobalContext(), v8::internal::torque::GlobalContext::SetInstanceTypesInitialized(), v8::internal::torque::LanguageServerData::SetTypeOracle(), v8::internal::torque::TargetArchitecture::SmiTagAndShiftSize(), v8::internal::torque::Logger::Stream(), v8::internal::torque::LanguageServerData::SymbolsForSourceId(), v8::internal::torque::TargetArchitecture::TaggedSize(), and v8::internal::torque::TargetArchitecture::TrustedPointerSize().
HasScope()
template<class Derived , class VarType >
static bool v8::base::ContextualVariable< Derived, VarType >::HasScope () [inline], [static]
Definition at line 69 of file contextual.h.
{ return Top() != nullptr; }
Top()
template<class Derived , class VarType >
static Scope*& v8::base::ContextualVariable< Derived, VarType >::Top () [inline], [static], [private]
Definition at line 79 of file contextual.h.
{ return top_; }
Member Data Documentation
top_
template<class Derived , class VarType >
thread_local Scope* v8::base::ContextualVariable< Derived, VarType >::top_ = nullptr [inline], [static], [private]
Definition at line 72 of file contextual.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/contextual.h