v8::internal::compiler::InductionVariable Class Reference
#include <loop-variable-optimizer.h>
Classes
struct Bound
Public Types
enum ConstraintKind { kStrict
, kNonStrict
 }
enum ArithmeticType { kAddition
, kSubtraction
 }
Public Member Functions
Node * phi () const
Node * effect_phi () const
Node * arith () const
Node * increment () const
Node * init_value () const
const ZoneVector< Bound > & lower_bounds ()
const ZoneVector< Bound > & upper_bounds ()
ArithmeticType Type ()
Private Member Functions
InductionVariable (Node *phi, Node *effect_phi, Node *arith, Node *increment, Node *init_value, Zone *zone, ArithmeticType arithmeticType)
void AddUpperBound (Node *bound, ConstraintKind kind)
void AddLowerBound (Node *bound, ConstraintKind kind)
Private Attributes
friend Zone
Node * phi_
Node * effect_phi_
Node * arith_
Node * increment_
Node * init_value_
ZoneVector< Bound > lower_bounds_
ZoneVector< Bound > upper_bounds_
ArithmeticType arithmeticType_
Friends
class LoopVariableOptimizer
Detailed Description
Definition at line 20 of file loop-variable-optimizer.h.
Member Enumeration Documentation
ArithmeticType
enum v8::internal::compiler::InductionVariable::ArithmeticType
Enumerator
kAddition
kSubtraction
Definition at line 29 of file loop-variable-optimizer.h.
{ kAddition, kSubtraction };
ConstraintKind
enum v8::internal::compiler::InductionVariable::ConstraintKind
Enumerator
kStrict
kNonStrict
Definition at line 28 of file loop-variable-optimizer.h.
{ kStrict, kNonStrict };
Constructor & Destructor Documentation
InductionVariable()
v8::internal::compiler::InductionVariable::InductionVariable (Node * phi, Node * effect_phi, Node * arith, Node * increment, Node * init_value, Zone * zone, ArithmeticType arithmeticType) [inline], [private]
Definition at line 46 of file loop-variable-optimizer.h.
      : phi_(phi),
        effect_phi_(effect_phi),
        arith_(arith),
        increment_(increment),
        init_value_(init_value),
        lower_bounds_(zone),
        upper_bounds_(zone),
        arithmeticType_(arithmeticType) {}
Member Function Documentation
AddLowerBound()
void v8::internal::compiler::InductionVariable::AddLowerBound (Node * bound, InductionVariable::ConstraintKind kind) [private]
Definition at line 87 of file loop-variable-optimizer.cc.
                                                                            {
  if (v8_flags.trace_turbo_loop) {
    StdoutStream{} << "New lower bound for " << phi()->id() << " (loop "
                   << NodeProperties::GetControlInput(phi())->id()
                   << "): " << *bound;
  }
  lower_bounds_.push_back(Bound(bound, kind));
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::id(), lower_bounds_, phi(), and v8::internal::v8_flags.
AddUpperBound()
void v8::internal::compiler::InductionVariable::AddUpperBound (Node * bound, InductionVariable::ConstraintKind kind) [private]
Definition at line 77 of file loop-variable-optimizer.cc.
                                                                            {
  if (v8_flags.trace_turbo_loop) {
    StdoutStream{} << "New upper bound for " << phi()->id() << " (loop "
                   << NodeProperties::GetControlInput(phi())->id()
                   << "): " << *bound << std::endl;
  }
  upper_bounds_.push_back(Bound(bound, kind));
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::id(), phi(), upper_bounds_, and v8::internal::v8_flags.
arith()
Node* v8::internal::compiler::InductionVariable::arith () const [inline]
Definition at line 24 of file loop-variable-optimizer.h.
{ return arith_; }
References arith_.
effect_phi()
Node* v8::internal::compiler::InductionVariable::effect_phi () const [inline]
Definition at line 23 of file loop-variable-optimizer.h.
{ return effect_phi_; }
References effect_phi_.
Referenced by v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards().
increment()
Node* v8::internal::compiler::InductionVariable::increment () const [inline]
Definition at line 25 of file loop-variable-optimizer.h.
{ return increment_; }
References increment_.
Referenced by v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis().
init_value()
Node* v8::internal::compiler::InductionVariable::init_value () const [inline]
Definition at line 26 of file loop-variable-optimizer.h.
{ return init_value_; }
References init_value_.
lower_bounds()
const ZoneVector<Bound>& v8::internal::compiler::InductionVariable::lower_bounds () [inline]
Definition at line 37 of file loop-variable-optimizer.h.
{ return lower_bounds_; }
References lower_bounds_.
Referenced by v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis(), and v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint().
phi()
Node* v8::internal::compiler::InductionVariable::phi () const [inline]
Definition at line 22 of file loop-variable-optimizer.h.
{ return phi_; }
References phi_.
Referenced by AddLowerBound(), AddUpperBound(), v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::LoopVariableOptimizer::DetectInductionVariables(), and v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint().
Type()
ArithmeticType v8::internal::compiler::InductionVariable::Type () [inline]
Definition at line 40 of file loop-variable-optimizer.h.
{ return arithmeticType_; }
References arithmeticType_.
upper_bounds()
const ZoneVector<Bound>& v8::internal::compiler::InductionVariable::upper_bounds () [inline]
Definition at line 38 of file loop-variable-optimizer.h.
{ return upper_bounds_; }
References upper_bounds_.
Referenced by v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis(), and v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint().
Friends And Related Function Documentation
LoopVariableOptimizer
friend class LoopVariableOptimizer [friend]
Definition at line 43 of file loop-variable-optimizer.h.
Member Data Documentation
arith_
Node* v8::internal::compiler::InductionVariable::arith_ [private]
Definition at line 62 of file loop-variable-optimizer.h.
Referenced by arith().
arithmeticType_
ArithmeticType v8::internal::compiler::InductionVariable::arithmeticType_ [private]
Definition at line 67 of file loop-variable-optimizer.h.
Referenced by Type().
effect_phi_
Node* v8::internal::compiler::InductionVariable::effect_phi_ [private]
Definition at line 61 of file loop-variable-optimizer.h.
Referenced by effect_phi().
increment_
Node* v8::internal::compiler::InductionVariable::increment_ [private]
Definition at line 63 of file loop-variable-optimizer.h.
Referenced by increment().
init_value_
Node* v8::internal::compiler::InductionVariable::init_value_ [private]
Definition at line 64 of file loop-variable-optimizer.h.
Referenced by init_value().
lower_bounds_
ZoneVector<Bound> v8::internal::compiler::InductionVariable::lower_bounds_ [private]
Definition at line 65 of file loop-variable-optimizer.h.
Referenced by AddLowerBound(), and lower_bounds().
phi_
Node* v8::internal::compiler::InductionVariable::phi_ [private]
Definition at line 60 of file loop-variable-optimizer.h.
Referenced by phi().
upper_bounds_
ZoneVector<Bound> v8::internal::compiler::InductionVariable::upper_bounds_ [private]
Definition at line 66 of file loop-variable-optimizer.h.
Referenced by AddUpperBound(), and upper_bounds().
Zone
friend v8::internal::compiler::InductionVariable::Zone [private]
Definition at line 44 of file loop-variable-optimizer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/loop-variable-optimizer.h
/mnt/V8SourceCode/src/compiler/loop-variable-optimizer.cc