v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState Class Reference
Classes
struct IteratorsStates
Public Member Functions
OsrIteratorState (BytecodeGraphBuilder *graph_builder)
void ProcessOsrPrelude ()
void RestoreState (int target_offset, int new_parent_offset)
Private Attributes
BytecodeGraphBuilder * graph_builder_
ZoneStack< IteratorsStates > saved_states_
Detailed Description
Definition at line 1261 of file bytecode-graph-builder.cc.
Constructor & Destructor Documentation
OsrIteratorState()
v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::OsrIteratorState (BytecodeGraphBuilder * graph_builder) [inline], [explicit]
Definition at line 1263 of file bytecode-graph-builder.cc.
      : graph_builder_(graph_builder),
        saved_states_(graph_builder->local_zone()) {}
Member Function Documentation
ProcessOsrPrelude()
void v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::ProcessOsrPrelude () [inline]
Definition at line 1267 of file bytecode-graph-builder.cc.
                           {
    ZoneVector<int> outer_loop_offsets(graph_builder_->local_zone());
    int osr_entry = graph_builder_->bytecode_analysis().osr_entry_point();
    // We find here the outermost loop which contains the OSR loop.
    int outermost_loop_offset = osr_entry;
    while ((outermost_loop_offset = graph_builder_->bytecode_analysis()
                                        .GetLoopInfoFor(outermost_loop_offset)
                                        .parent_offset()) != -1) {
      outer_loop_offsets.push_back(outermost_loop_offset);
    }
    outermost_loop_offset =
        outer_loop_offsets.empty() ? osr_entry : outer_loop_offsets.back();
    graph_builder_->AdvanceIteratorsTo(outermost_loop_offset);
    // We save some iterators states at the offsets of the loop headers of the
    // outer loops (the ones containing the OSR loop). They will be used for
    // jumping back in the bytecode.
    for (ZoneVector<int>::const_reverse_iterator it =
             outer_loop_offsets.crbegin();
         it != outer_loop_offsets.crend(); ++it) {
      graph_builder_->AdvanceIteratorsTo(*it);
      graph_builder_->ExitThenEnterExceptionHandlers(
          graph_builder_->bytecode_iterator().current_offset());
      saved_states_.push(IteratorsStates(
          graph_builder_->current_exception_handler(),
          graph_builder_->source_position_iterator().GetState()));
    }
    // Finishing by advancing to the OSR entry
    graph_builder_->AdvanceIteratorsTo(osr_entry);
    // Enters all remaining exception handler which end before the OSR loop
    // so that on next call of VisitSingleBytecode they will get popped from
    // the exception handlers stack.
    graph_builder_->ExitThenEnterExceptionHandlers(osr_entry);
    graph_builder_->set_currently_peeled_loop_offset(
        graph_builder_->bytecode_analysis()
            .GetLoopInfoFor(osr_entry)
            .parent_offset());
  }
References v8::internal::ZoneVector< T >::back(), v8::internal::ZoneVector< T >::crbegin(), v8::internal::ZoneVector< T >::crend(), v8::internal::ZoneVector< T >::empty(), and v8::internal::ZoneVector< T >::push_back().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::AdvanceToOsrEntryAndPeelLoops().
RestoreState()
void v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::RestoreState (int target_offset, int new_parent_offset) [inline]
Definition at line 1309 of file bytecode-graph-builder.cc.
                                                              {
    graph_builder_->bytecode_iterator().SetOffset(target_offset);
    // In case of a return, we must not build loop exits for
    // not-yet-built outer loops.
    graph_builder_->set_currently_peeled_loop_offset(new_parent_offset);
    IteratorsStates saved_state = saved_states_.top();
    graph_builder_->source_position_iterator().RestoreState(
        saved_state.source_iterator_state_);
    graph_builder_->set_current_exception_handler(
        saved_state.exception_handler_index_);
    saved_states_.pop();
  }
References v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::IteratorsStates::exception_handler_index_, and v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::IteratorsStates::source_iterator_state_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::AdvanceToOsrEntryAndPeelLoops().
Member Data Documentation
graph_builder_
BytecodeGraphBuilder* v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::graph_builder_ [private]
Definition at line 1334 of file bytecode-graph-builder.cc.
saved_states_
ZoneStack<IteratorsStates> v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::saved_states_ [private]
Definition at line 1335 of file bytecode-graph-builder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/bytecode-graph-builder.cc