v8::base::RecursiveMutex Class Reference
#include <mutex.h>
Public Member Functions
RecursiveMutex ()=default
RecursiveMutex (const RecursiveMutex &)=delete
RecursiveMutex & operator= (const RecursiveMutex &)=delete
~RecursiveMutex ()
void Lock ()
void Unlock ()
bool TryLock () V8_WARN_UNUSED_RESULT
void AssertHeld () const
Private Attributes
std::atomic< int > thread_id_ = 0
int level_ = 0
Mutex mutex_
Detailed Description
Definition at line 126 of file mutex.h.
Constructor & Destructor Documentation
RecursiveMutex() [1/2]
v8::base::RecursiveMutex::RecursiveMutex () [default]
RecursiveMutex() [2/2]
v8::base::RecursiveMutex::RecursiveMutex (const RecursiveMutex &) [delete]
 RecursiveMutex()
v8::base::RecursiveMutex::~RecursiveMutex ()
Definition at line 12 of file mutex.cc.
                                {
  DCHECK_EQ(0, level_);
}
References DCHECK_EQ, and level_.
Member Function Documentation
AssertHeld()
void v8::base::RecursiveMutex::AssertHeld () const [inline]
Definition at line 153 of file mutex.h.
                                    {
    // If this access results in a race condition being detected by TSan, this
    // mean that you in fact did *not* hold the mutex.
    DCHECK_LT(0, level_);
  }
References DCHECK_LT.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::GlobalSafepoint::AppendClient(), v8::internal::IsolateSafepoint::AssertActive(), v8::internal::GlobalSafepoint::AssertActive(), v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), v8::internal::wasm::NativeModule::FindJumpTablesForRegionLocked(), v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation(), v8::internal::IsolateSafepoint::LeaveGlobalSafepointScope(), v8::internal::GlobalSafepoint::LeaveGlobalSafepointScope(), v8::internal::IsolateSafepoint::LeaveLocalSafepointScope(), v8::internal::wasm::NativeModule::PatchJumpTableLocked(), v8::internal::wasm::NativeModule::PatchJumpTablesLocked(), v8::internal::wasm::NativeModule::PublishCodeLocked(), v8::internal::wasm::NativeModule::TransferNewOwnedCodeLocked(), and v8::internal::wasm::NativeModule::UseLazyStubLocked().
Lock()
void v8::base::RecursiveMutex::Lock ()
Definition at line 16 of file mutex.cc.
                          {
  int own_id = v8::base::OS::GetCurrentThreadId();
  if (thread_id_ == own_id) {
    level_++;
    return;
  }
  mutex_.Lock();
  DCHECK_EQ(0, level_);
  thread_id_ = own_id;
  level_ = 1;
}
References DCHECK_EQ, v8::base::OS::GetCurrentThreadId(), level_, v8::base::Mutex::Lock(), mutex_, and thread_id_.
Referenced by v8::internal::Isolate::Deinit(), v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::ExecutionAccess::Lock(), v8::internal::IsolateSafepoint::LockMutex(), and v8::internal::ParkedRecursiveMutexGuard::ParkedRecursiveMutexGuard().
operator=()
RecursiveMutex& v8::base::RecursiveMutex::operator= (const RecursiveMutex &) [delete]
TryLock()
bool v8::base::RecursiveMutex::TryLock ()
Definition at line 39 of file mutex.cc.
                             {
  int own_id = v8::base::OS::GetCurrentThreadId();
  if (thread_id_ == own_id) {
    level_++;
    return true;
  }
  if (mutex_.TryLock()) {
    DCHECK_EQ(0, level_);
    thread_id_ = own_id;
    level_ = 1;
    return true;
  }
  return false;
}
References DCHECK_EQ, v8::base::OS::GetCurrentThreadId(), level_, mutex_, thread_id_, and v8::base::Mutex::TryLock().
Referenced by v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::GlobalSafepoint::IsRequestedForTesting(), v8::internal::IsolateSafepoint::LockMutex(), v8::internal::ParkedRecursiveMutexGuard::ParkedRecursiveMutexGuard(), v8::internal::IsolateSafepoint::TryInitiateGlobalSafepointScope(), and v8::internal::ExecutionAccess::TryLock().
Unlock()
void v8::base::RecursiveMutex::Unlock ()
Definition at line 28 of file mutex.cc.
                            {
#ifdef DEBUG
  int own_id = v8::base::OS::GetCurrentThreadId();
  CHECK_EQ(thread_id_, own_id);
#endif
  if ((--level_) == 0) {
    thread_id_ = 0;
    mutex_.Unlock();
  }
}
References CHECK_EQ, v8::base::OS::GetCurrentThreadId(), level_, mutex_, thread_id_, and v8::base::Mutex::Unlock().
Referenced by v8::internal::Isolate::Deinit(), v8::internal::GlobalSafepoint::IsRequestedForTesting(), v8::internal::IsolateSafepoint::LeaveGlobalSafepointScope(), v8::internal::GlobalSafepoint::LeaveGlobalSafepointScope(), v8::internal::IsolateSafepoint::LeaveLocalSafepointScope(), and v8::internal::ExecutionAccess::Unlock().
Member Data Documentation
level_
int v8::base::RecursiveMutex::level_ = 0 [private]
Definition at line 161 of file mutex.h.
Referenced by Lock(), TryLock(), Unlock(), and ~RecursiveMutex().
mutex_
Mutex v8::base::RecursiveMutex::mutex_ [private]
Definition at line 162 of file mutex.h.
Referenced by Lock(), TryLock(), and Unlock().
thread_id_
std::atomic<int> v8::base::RecursiveMutex::thread_id_ = 0 [private]
Definition at line 160 of file mutex.h.
Referenced by Lock(), TryLock(), and Unlock().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/mutex.h
/mnt/V8SourceCode/src/base/platform/mutex.cc