v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen Class Reference
Public Types
enum SigKind { kFunctionSig
, kExceptionSig
 }
Public Member Functions
ModuleGen (Zone *zone, WasmModuleGenerationOptions options, WasmModuleBuilder *fn, DataRange *module_range, uint8_t num_functions, uint8_t num_structs, uint8_t num_arrays, uint8_t num_signatures)
void GenerateRandomMemories ()
std::map< uint8_t, uint8_t > GenerateRandomRecursiveGroups (uint8_t kNumDefaultArrayTypes)
void GenerateRandomStructs (const std::map< uint8_t, uint8_t > &explicit_rec_groups, std::vector< ModuleTypeIndex > &struct_types, uint8_t &current_type_index, uint8_t kNumDefaultArrayTypes)
void GenerateRandomArrays (const std::map< uint8_t, uint8_t > &explicit_rec_groups, std::vector< ModuleTypeIndex > &array_types, uint8_t &current_type_index)
FunctionSig * GenerateSig (SigKind sig_kind, int num_types)
void GenerateRandomFunctionSigs (const std::map< uint8_t, uint8_t > &explicit_rec_groups, std::vector< ModuleTypeIndex > &function_signatures, uint8_t &current_type_index, bool kIsFinal)
void GenerateRandomExceptions (uint8_t num_exceptions)
StringImports AddImportedStringImports ()
void GenerateRandomTables (const std::vector< ModuleTypeIndex > &array_types, const std::vector< ModuleTypeIndex > &struct_types)
std::tuple< std::vector< ValueType >, std::vector< uint8_t > > GenerateRandomGlobals (const std::vector< ModuleTypeIndex > &array_types, const std::vector< ModuleTypeIndex > &struct_types)
Private Attributes
Zone *const zone_
const WasmModuleGenerationOptions options_
WasmModuleBuilder *const builder_
DataRange *const module_range_
const uint8_t num_functions_
const uint8_t num_structs_
const uint8_t num_arrays_
const uint16_t num_types_
Detailed Description
Definition at line 3682 of file random-module-generation.cc.
Member Enumeration Documentation
SigKind
enum v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::SigKind
Enumerator
kFunctionSig
kExceptionSig
Definition at line 3867 of file random-module-generation.cc.
{ kFunctionSig, kExceptionSig };
Constructor & Destructor Documentation
ModuleGen()
v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::ModuleGen (Zone * zone, WasmModuleGenerationOptions options, WasmModuleBuilder * fn, DataRange * module_range, uint8_t num_functions, uint8_t num_structs, uint8_t num_arrays, uint8_t num_signatures) [inline], [explicit]
Definition at line 3684 of file random-module-generation.cc.
      : zone_(zone),
        options_(options),
        builder_(fn),
        module_range_(module_range),
        num_functions_(num_functions),
        num_structs_(num_structs),
        num_arrays_(num_arrays),
        num_types_(num_signatures + num_structs + num_arrays) {}
Member Function Documentation
AddImportedStringImports()
StringImports v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::AddImportedStringImports () [inline]
Definition at line 3916 of file random-module-generation.cc.
                                           {
    static constexpr ModuleTypeIndex kArrayI8{0};
    static constexpr ModuleTypeIndex kArrayI16{1};
    StringImports strings;
    strings.array_i8 = kArrayI8;
    strings.array_i16 = kArrayI16;
    static constexpr ValueType kRefExtern = kWasmRefExtern;
    static constexpr ValueType kExternRef = kWasmExternRef;
    static constexpr ValueType kI32 = kWasmI32;
    static constexpr ValueType kRefA8 =
        ValueType::Ref(kArrayI8, kNotShared, RefTypeKind::kArray);
    static constexpr ValueType kRefNullA8 =
        ValueType::RefNull(kArrayI8, kNotShared, RefTypeKind::kArray);
    static constexpr ValueType kRefNullA16 =
        ValueType::RefNull(kArrayI16, kNotShared, RefTypeKind::kArray);
    // Shorthands: "r" = nullable "externref",
    // "e" = non-nullable "ref extern".
    static constexpr ValueType kReps_e_i[] = {kRefExtern, kI32};
    static constexpr ValueType kReps_e_rr[] = {kRefExtern, kExternRef,
                                               kExternRef};
    static constexpr ValueType kReps_e_rii[] = {kRefExtern, kExternRef, kI32,
                                                kI32};
    static constexpr ValueType kReps_i_ri[] = {kI32, kExternRef, kI32};
    static constexpr ValueType kReps_i_rr[] = {kI32, kExternRef, kExternRef};
    static constexpr ValueType kReps_from_a16[] = {kRefExtern, kRefNullA16,
                                                   kI32, kI32};
    static constexpr ValueType kReps_from_a8[] = {kRefExtern, kRefNullA8, kI32,
                                                  kI32};
    static constexpr ValueType kReps_into_a16[] = {kI32, kExternRef,
                                                   kRefNullA16, kI32};
    static constexpr ValueType kReps_into_a8[] = {kI32, kExternRef, kRefNullA8,
                                                  kI32};
    static constexpr ValueType kReps_to_a8[] = {kRefA8, kExternRef};
    static constexpr FunctionSig kSig_e_i(1, 1, kReps_e_i);
    static constexpr FunctionSig kSig_e_r(1, 1, kReps_e_rr);
    static constexpr FunctionSig kSig_e_rr(1, 2, kReps_e_rr);
    static constexpr FunctionSig kSig_e_rii(1, 3, kReps_e_rii);
    static constexpr FunctionSig kSig_i_r(1, 1, kReps_i_ri);
    static constexpr FunctionSig kSig_i_ri(1, 2, kReps_i_ri);
    static constexpr FunctionSig kSig_i_rr(1, 2, kReps_i_rr);
    static constexpr FunctionSig kSig_from_a16(1, 3, kReps_from_a16);
    static constexpr FunctionSig kSig_from_a8(1, 3, kReps_from_a8);
    static constexpr FunctionSig kSig_into_a16(1, 3, kReps_into_a16);
    static constexpr FunctionSig kSig_into_a8(1, 3, kReps_into_a8);
    static constexpr FunctionSig kSig_to_a8(1, 1, kReps_to_a8);
    static constexpr base::Vector<const char> kJsString =
        base::StaticCharVector("wasm:js-string");
    static constexpr base::Vector<const char> kTextDecoder =
        base::StaticCharVector("wasm:text-decoder");
    static constexpr base::Vector<const char> kTextEncoder =
        base::StaticCharVector("wasm:text-encoder");
#define STRINGFUNC(name, sig, group) \
  strings.name = builder_->AddImport(base::CStrVector(#name), &sig, group)
    STRINGFUNC(cast, kSig_e_r, kJsString);
    STRINGFUNC(test, kSig_i_r, kJsString);
    STRINGFUNC(fromCharCode, kSig_e_i, kJsString);
    STRINGFUNC(fromCodePoint, kSig_e_i, kJsString);
    STRINGFUNC(charCodeAt, kSig_i_ri, kJsString);
    STRINGFUNC(codePointAt, kSig_i_ri, kJsString);
    STRINGFUNC(length, kSig_i_r, kJsString);
    STRINGFUNC(concat, kSig_e_rr, kJsString);
    STRINGFUNC(substring, kSig_e_rii, kJsString);
    STRINGFUNC(equals, kSig_i_rr, kJsString);
    STRINGFUNC(compare, kSig_i_rr, kJsString);
    STRINGFUNC(fromCharCodeArray, kSig_from_a16, kJsString);
    STRINGFUNC(intoCharCodeArray, kSig_into_a16, kJsString);
    STRINGFUNC(measureStringAsUTF8, kSig_i_r, kTextEncoder);
    STRINGFUNC(encodeStringIntoUTF8Array, kSig_into_a8, kTextEncoder);
    STRINGFUNC(encodeStringToUTF8Array, kSig_to_a8, kTextEncoder);
    STRINGFUNC(decodeStringFromUTF8Array, kSig_from_a8, kTextDecoder);
#undef STRINGFUNC
    return strings;
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::StringImports::array_i16, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::StringImports::array_i8, v8::internal::wasm::kArray, v8::internal::kI32, v8::internal::wasm::kJsString, v8::internal::kNotShared, v8::internal::wasm::kTextDecoder, v8::internal::wasm::kTextEncoder, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmRefExtern, v8::internal::length, v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::ValueType::RefNull(), v8::base::StaticCharVector(), and STRINGFUNC.
GenerateRandomArrays()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomArrays (const std::map< uint8_t, uint8_t > & explicit_rec_groups, std::vector< ModuleTypeIndex > & array_types, uint8_t & current_type_index) [inline]
Definition at line 3832 of file random-module-generation.cc.
                                                                            {
    uint32_t last_struct_type_index = current_type_index + num_structs_;
    for (; current_type_index < num_structs_ + num_arrays_;
         current_type_index++) {
      auto rec_group = explicit_rec_groups.find(current_type_index);
      uint8_t current_rec_group_end = rec_group != explicit_rec_groups.end()
                                          ? rec_group->second
                                          : current_type_index;
      ValueType type =
          GetValueTypeHelper(options_, module_range_, current_rec_group_end + 1,
                             current_type_index, kIncludeNumericTypes,
                             kIncludePackedTypes, kExcludeSomeGenerics);
      ModuleTypeIndex supertype = kNoSuperType;
      if (current_type_index > last_struct_type_index &&
          module_range_->get<bool>()) {
        // Do not include the default array types, because they are final.
        uint8_t existing_array_types =
            current_type_index - last_struct_type_index;
        supertype = ModuleTypeIndex{
            last_struct_type_index +
            (module_range_->get<uint8_t>() % existing_array_types)};
        // TODO(14034): This could also be any sub type of the supertype's
        // element type.
        type = builder_->GetArrayType(supertype)->element_type();
      }
      ArrayType* array_fuz = zone_->New<ArrayType>(type, true);
      // TODO(14034): Generate some final types too.
      ModuleTypeIndex index =
          builder_->AddArrayType(array_fuz, false, supertype);
      array_types.push_back(index);
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::index, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kExcludeSomeGenerics, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kIncludeNumericTypes, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kIncludePackedTypes, v8::internal::wasm::kNoSuperType, and v8::internal::tracing::type.
GenerateRandomExceptions()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomExceptions (uint8_t num_exceptions) [inline]
Definition at line 3908 of file random-module-generation.cc.
                                                        {
    for (int i = 0; i < num_exceptions; ++i) {
      FunctionSig* sig = GenerateSig(kExceptionSig, num_types_);
      builder_->AddTag(sig);
    }
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::sig.
GenerateRandomFunctionSigs()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomFunctionSigs (const std::map< uint8_t, uint8_t > & explicit_rec_groups, std::vector< ModuleTypeIndex > & function_signatures, uint8_t & current_type_index, bool kIsFinal) [inline]
Definition at line 3888 of file random-module-generation.cc.
                                                  {
    // Recursive groups consist of recursive types that came with the WasmGC
    // proposal.
    DCHECK_IMPLIES(!options_.generate_wasm_gc(), explicit_rec_groups.empty());
    for (; current_type_index < num_types_; current_type_index++) {
      auto rec_group = explicit_rec_groups.find(current_type_index);
      uint8_t current_rec_group_end = rec_group != explicit_rec_groups.end()
                                          ? rec_group->second
                                          : current_type_index;
      FunctionSig* sig = GenerateSig(kFunctionSig, current_rec_group_end + 1);
      ModuleTypeIndex signature_index =
          builder_->ForceAddSignature(sig, kIsFinal);
      function_signatures.push_back(signature_index);
    }
  }
References DCHECK_IMPLIES, and v8::internal::sig.
GenerateRandomGlobals()
std::tuple<std::vector<ValueType>, std::vector<uint8_t> > v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomGlobals (const std::vector< ModuleTypeIndex > & array_types, const std::vector< ModuleTypeIndex > & struct_types) [inline]
Definition at line 4064 of file random-module-generation.cc.
                                                                        {
    int num_globals = module_range_->get<uint8_t>() % (kMaxGlobals + 1);
    std::vector<ValueType> globals;
    std::vector<uint8_t> mutable_globals;
    globals.reserve(num_globals);
    mutable_globals.reserve(num_globals);
    for (int i = 0; i < num_globals; ++i) {
      ValueType type = GetValueType(options_, module_range_, num_types_);
      // 1/8 of globals are immutable.
      const bool mutability = (module_range_->get<uint8_t>() % 8) != 0;
      builder_->AddGlobal(type, mutability,
                          GenerateInitExpr(zone_, *module_range_, builder_,
                                           type, struct_types, array_types, 0));
      globals.push_back(type);
      if (mutability) mutable_globals.push_back(static_cast<uint8_t>(i));
    }
    return {globals, mutable_globals};
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxGlobals, and v8::internal::tracing::type.
GenerateRandomMemories()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomMemories () [inline]
Definition at line 3698 of file random-module-generation.cc.
                                {
    int num_memories = 1 + (module_range_->get<uint8_t>() % kMaxMemories);
    for (int i = 0; i < num_memories; i++) {
      uint8_t random_byte = module_range_->get<uint8_t>();
      bool mem64 = random_byte & 1;
      bool has_maximum = random_byte & 2;
      static_assert(kV8MaxWasmMemory64Pages <= kMaxUInt32);
      uint32_t max_supported_pages =
          mem64 ? max_mem64_pages() : max_mem32_pages();
      uint32_t min_pages =
          module_range_->get<uint32_t>() % (max_supported_pages + 1);
      if (has_maximum) {
        uint32_t max_pages =
            std::max(min_pages, module_range_->get<uint32_t>() %
                                    (max_supported_pages + 1));
        if (mem64) {
          builder_->AddMemory64(min_pages, max_pages);
        } else {
          builder_->AddMemory(min_pages, max_pages);
        }
      } else {
        if (mem64) {
          builder_->AddMemory64(min_pages);
        } else {
          builder_->AddMemory(min_pages);
        }
      }
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxMemories, v8::internal::kMaxUInt32, v8::internal::wasm::kV8MaxWasmMemory64Pages, v8::internal::wasm::max_mem32_pages(), and v8::internal::wasm::max_mem64_pages().
GenerateRandomRecursiveGroups()
std::map<uint8_t, uint8_t> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomRecursiveGroups (uint8_t kNumDefaultArrayTypes) [inline]
Definition at line 3729 of file random-module-generation.cc.
                                     {
    // (Type_index -> end of explicit rec group).
    std::map<uint8_t, uint8_t> explicit_rec_groups;
    uint8_t current_type_index = 0;
    // The default array types are each in their own recgroup.
    for (uint8_t i = 0; i < kNumDefaultArrayTypes; i++) {
      explicit_rec_groups.emplace(current_type_index, current_type_index);
      builder_->AddRecursiveTypeGroup(current_type_index++, 1);
    }
    while (current_type_index < num_types_) {
      // First, pick a random start for the next group. We allow it to be
      // beyond the end of types (i.e., we add no further recursive groups).
      uint8_t group_start = module_range_->get<uint8_t>() %
                                (num_types_ - current_type_index + 1) +
                            current_type_index;
      DCHECK_GE(group_start, current_type_index);
      current_type_index = group_start;
      if (group_start < num_types_) {
        // If we did not reach the end of the types, pick a random group size.
        uint8_t group_size =
            module_range_->get<uint8_t>() % (num_types_ - group_start) + 1;
        DCHECK_LE(group_start + group_size, num_types_);
        for (uint8_t i = group_start; i < group_start + group_size; i++) {
          explicit_rec_groups.emplace(i, group_start + group_size - 1);
        }
        builder_->AddRecursiveTypeGroup(group_start, group_size);
        current_type_index += group_size;
      }
    }
    return explicit_rec_groups;
  }
References DCHECK_GE, and DCHECK_LE.
GenerateRandomStructs()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs (const std::map< uint8_t, uint8_t > & explicit_rec_groups, std::vector< ModuleTypeIndex > & struct_types, uint8_t & current_type_index, uint8_t kNumDefaultArrayTypes) [inline]
Definition at line 3765 of file random-module-generation.cc.
                                     {
    uint8_t last_struct_type_index = current_type_index + num_structs_;
    for (; current_type_index < last_struct_type_index; current_type_index++) {
      auto rec_group = explicit_rec_groups.find(current_type_index);
      uint8_t current_rec_group_end = rec_group != explicit_rec_groups.end()
                                          ? rec_group->second
                                          : current_type_index;
      ModuleTypeIndex supertype = kNoSuperType;
      uint8_t num_fields =
          module_range_->get<uint8_t>() % (kMaxStructFields + 1);
      uint32_t existing_struct_types =
          current_type_index - kNumDefaultArrayTypes;
      if (existing_struct_types > 0 && module_range_->get<bool>()) {
        supertype = ModuleTypeIndex{module_range_->get<uint8_t>() %
                                        existing_struct_types +
                                    kNumDefaultArrayTypes};
        num_fields += builder_->GetStructType(supertype)->field_count();
      }
      // TODO(403372470): Add support for custom descriptors.
      // TODO(42204563): Add support for shared structs.
      StructType::Builder struct_builder(zone_, num_fields, false, false);
      // Add all fields from super type.
      uint32_t field_index = 0;
      if (supertype != kNoSuperType) {
        const StructType* parent = builder_->GetStructType(supertype);
        for (; field_index < parent->field_count(); ++field_index) {
          // TODO(14034): This could also be any sub type of the supertype's
          // element type.
          struct_builder.AddField(parent->field(field_index),
                                  parent->mutability(field_index));
        }
      }
      for (; field_index < num_fields; field_index++) {
        // Notes:
        // - We allow a type to only have non-nullable fields of types that
        // are defined earlier. This way we avoid infinite non-nullable
        // constructions. Also relevant for arrays and functions.
        // - On the other hand, nullable fields can be picked up to the end of
        // the current recursive group.
        // - We exclude the non-nullable generic types arrayref, anyref,
        // structref, eqref and externref from the fields of structs and
        // arrays. This is so that GenerateInitExpr has a way to break a
        // recursion between a struct/array field and those types
        // ((ref extern) gets materialized through (ref any)).
        ValueType type = GetValueTypeHelper(
            options_, module_range_, current_rec_group_end + 1,
            current_type_index, kIncludeNumericTypes, kIncludePackedTypes,
            kExcludeSomeGenerics);
        bool mutability = module_range_->get<bool>();
        struct_builder.AddField(type, mutability);
      }
      StructType* struct_fuz = struct_builder.Build();
      // TODO(14034): Generate some final types too.
      ModuleTypeIndex index =
          builder_->AddStructType(struct_fuz, false, supertype);
      struct_types.push_back(index);
    }
  }
References v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::index, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kExcludeSomeGenerics, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kIncludeNumericTypes, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kIncludePackedTypes, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxStructFields, v8::internal::wasm::kNoSuperType, v8::internal::wasm::StructTypeBase::mutability(), and v8::internal::tracing::type.
GenerateRandomTables()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomTables (const std::vector< ModuleTypeIndex > & array_types, const std::vector< ModuleTypeIndex > & struct_types) [inline]
Definition at line 3999 of file random-module-generation.cc.
                                                                            {
    int num_tables = module_range_->get<uint8_t>() % kMaxTables + 1;
    int are_table64 = module_range_->get<uint8_t>();
    static_assert(
        kMaxTables <= 8,
        "Too many tables. Use more random bits to choose their address type.");
    const int max_table_size = MaxTableSize();
    for (int i = 0; i < num_tables; i++) {
      uint32_t min_size = i == 0
                              ? num_functions_
                              : module_range_->get<uint8_t>() % max_table_size;
      uint32_t max_size =
          module_range_->get<uint8_t>() % (max_table_size - min_size) +
          min_size;
      // Table 0 is always funcref. This guarantees that
      // - call_indirect has at least one funcref table to work with,
      // - we have a place to reference all functions in the program, so they
      // count as "declared" for ref.func.
      bool force_funcref = i == 0;
      ValueType type =
          force_funcref
              ? kWasmFuncRef
              : GetValueTypeHelper(options_, module_range_, num_types_,
                                   num_types_, kExcludeNumericTypes,
                                   kExcludePackedTypes, kIncludeAllGenerics);
      bool use_initializer =
          !type.is_defaultable() || module_range_->get<bool>();
      bool use_table64 = are_table64 & 1;
      are_table64 >>= 1;
      AddressType address_type =
          use_table64 ? AddressType::kI64 : AddressType::kI32;
      uint32_t table_index =
          use_initializer
              ? builder_->AddTable(
                    type, min_size, max_size,
                    GenerateInitExpr(zone_, *module_range_, builder_, type,
                                     struct_types, array_types, 0),
                    address_type)
              : builder_->AddTable(type, min_size, max_size, address_type);
      if (type.is_reference_to(HeapType::kFunc)) {
        // For function tables, initialize them with functions from the program.
        // Currently, the fuzzer assumes that every funcref/(ref func) table
        // contains the functions in the program in the order they are defined.
        // TODO(11954): Consider generalizing this.
        WasmInitExpr init_expr = builder_->IsTable64(table_index)
                                     ? WasmInitExpr(static_cast<int64_t>(0))
                                     : WasmInitExpr(static_cast<int32_t>(0));
        WasmModuleBuilder::WasmElemSegment segment(zone_, type, table_index,
                                                   init_expr);
        for (int entry_index = 0; entry_index < static_cast<int>(min_size);
             entry_index++) {
          segment.entries.emplace_back(
              WasmModuleBuilder::WasmElemSegment::Entry::kRefFuncEntry,
              builder_->NumImportedFunctions() +
                  (entry_index % num_functions_));
        }
        builder_->AddElementSegment(std::move(segment));
      }
    }
  }
References v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::entries, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kExcludeNumericTypes, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kExcludePackedTypes, v8::internal::wasm::HeapType::kFunc, v8::internal::wasm::kI32, v8::internal::wasm::kI64, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kIncludeAllGenerics, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxTables, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::Entry::kRefFuncEntry, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::max_table_size(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::MaxTableSize(), and v8::internal::tracing::type.
GenerateSig()
FunctionSig* v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateSig (SigKind sig_kind, int num_types) [inline]
Definition at line 3869 of file random-module-generation.cc.
                                                            {
    // Generate enough parameters to spill some to the stack.
    int num_params = int{module_range_->get<uint8_t>()} % (kMaxParameters + 1);
    int num_returns =
        sig_kind == kFunctionSig
            ? int{module_range_->get<uint8_t>()} % (kMaxReturns + 1)
            : 0;
    FunctionSig::Builder builder(zone_, num_returns, num_params);
    for (int i = 0; i < num_returns; ++i) {
      builder.AddReturn(GetValueType(options_, module_range_, num_types));
    }
    for (int i = 0; i < num_params; ++i) {
      builder.AddParam(GetValueType(options_, module_range_, num_types));
    }
    return builder.Get();
  }
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxParameters, and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxReturns.
Member Data Documentation
builder_
WasmModuleBuilder* const v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::builder_ [private]
Definition at line 4089 of file random-module-generation.cc.
module_range_
DataRange* const v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::module_range_ [private]
Definition at line 4090 of file random-module-generation.cc.
num_arrays_
const uint8_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::num_arrays_ [private]
Definition at line 4093 of file random-module-generation.cc.
num_functions_
const uint8_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::num_functions_ [private]
Definition at line 4091 of file random-module-generation.cc.
num_structs_
const uint8_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::num_structs_ [private]
Definition at line 4092 of file random-module-generation.cc.
num_types_
const uint16_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::num_types_ [private]
Definition at line 4094 of file random-module-generation.cc.
options_
const WasmModuleGenerationOptions v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::options_ [private]
Definition at line 4088 of file random-module-generation.cc.
zone_
Zone* const v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::zone_ [private]
Definition at line 4087 of file random-module-generation.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/fuzzing/random-module-generation.cc