v8::internal::StringSearchBase Class Reference
#include <string-search.h>
Static Protected Member Functions
static bool IsOneByteString (base::Vector< const uint8_t > string)
static bool IsOneByteString (base::Vector< const base::uc16 > string)
Static Protected Attributes
static const int kBMMaxShift = Isolate::kBMMaxShift
static const int kLatin1AlphabetSize = 256
static const int kUC16AlphabetSize = Isolate::kUC16AlphabetSize
static const int kBMMinPatternLength = 7
Friends
class Isolate
Detailed Description
Definition at line 22 of file string-search.h.
Member Function Documentation
IsOneByteString() [1/2]
static bool v8::internal::StringSearchBase::IsOneByteString (base::Vector< const base::uc16 > string) [inline], [static], [protected]
Definition at line 49 of file string-search.h.
                                                                        {
    return String::IsOneByte(string.begin(), string.length());
  }
References v8::internal::compiler::begin(), v8::internal::String::IsOneByte(), and v8::internal::length.
IsOneByteString() [2/2]
static bool v8::internal::StringSearchBase::IsOneByteString (base::Vector< const uint8_t > string) [inline], [static], [protected]
Definition at line 45 of file string-search.h.
                                                                       {
    return true;
  }
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch().
Friends And Related Function Documentation
Isolate
friend class Isolate [friend]
Definition at line 53 of file string-search.h.
Member Data Documentation
kBMMaxShift
const int v8::internal::StringSearchBase::kBMMaxShift = Isolate::kBMMaxShift [static], [protected]
Definition at line 28 of file string-search.h.
kBMMinPatternLength
const int v8::internal::StringSearchBase::kBMMinPatternLength = 7 [static], [protected]
Definition at line 43 of file string-search.h.
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch().
kLatin1AlphabetSize
const int v8::internal::StringSearchBase::kLatin1AlphabetSize = 256 [static], [protected]
Definition at line 37 of file string-search.h.
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::AlphabetSize().
kUC16AlphabetSize
const int v8::internal::StringSearchBase::kUC16AlphabetSize = Isolate::kUC16AlphabetSize [static], [protected]
Definition at line 38 of file string-search.h.
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::AlphabetSize(), and v8::internal::StringSearch< PatternChar, SubjectChar >::CharOccurrence().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/strings/string-search.h