v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor Class Reference
Static Public Member Functions
static uint32_t GetMaxIndex (Tagged< JSObject > receiver, Tagged< FixedArrayBase > elements)
static uint32_t GetMaxNumberOfEntries (Isolate *isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store)
static uint32_t NumberOfElementsImpl (Isolate *isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store)
static Maybe< bool > SetLengthImpl (Isolate *isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store)
static void CopyElementsImpl (Isolate *isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size)
static void DeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, InternalIndex entry)
static bool HasAccessorsImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store)
static Tagged< Object > GetRaw (Tagged< FixedArrayBase > store, InternalIndex entry)
static Handle< Object > GetImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static Handle< Object > GetAtomicInternalImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, SeqCstAccessTag tag)
static void SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value)
static void SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value)
static void SetAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag)
static Handle< Object > SwapAtomicInternalImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag)
static Tagged< Object > CompareAndSwapAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)
static void ReconfigureImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes)
static Maybe< bool > AddImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)
static bool HasEntryImpl (Isolate *isolate, Tagged< FixedArrayBase > store, InternalIndex entry)
static InternalIndex GetEntryForIndexImpl (Isolate *isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > store, size_t index, PropertyFilter filter)
static PropertyDetails GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry)
static PropertyDetails GetDetailsImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static uint32_t FilterKey (DirectHandle< NumberDictionary > dictionary, InternalIndex entry, Tagged< Object > raw_key, PropertyFilter filter)
static uint32_t GetKeyForEntryImpl (Isolate *isolate, DirectHandle< NumberDictionary > dictionary, InternalIndex entry, PropertyFilter filter)
static V8_WARN_UNUSED_RESULT ExceptionStatus CollectElementIndicesImpl (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator *keys)
static Handle< FixedArray > DirectCollectElementIndicesImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, GetKeysConversion convert, PropertyFilter filter, Handle< FixedArray > list, uint32_t *nof_indices, uint32_t insertion_index=0)
static V8_WARN_UNUSED_RESULT ExceptionStatus AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator *accumulator, AddKeyConversion convert)
static bool IncludesValueFastPath (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length, Maybe< bool > *result)
static Maybe< bool > IncludesValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
static Maybe< int64_t > IndexOfValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
static void ValidateContents (Isolate *isolate, Tagged< JSObject > holder, size_t length)
Additional Inherited Members
Detailed Description
Definition at line 1552 of file elements.cc.
Member Function Documentation
AddElementsToKeyAccumulatorImpl()
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator * accumulator, AddKeyConversion convert) [inline], [static]
Definition at line 1858 of file elements.cc.
                                {
    Isolate* isolate = accumulator->isolate();
    DirectHandle<NumberDictionary> dictionary(
        Cast<NumberDictionary>(receiver->elements()), isolate);
    ReadOnlyRoots roots(isolate);
    for (InternalIndex i : dictionary->IterateEntries()) {
      Tagged<Object> k = dictionary->KeyAt(isolate, i);
      if (!dictionary->IsKey(roots, k)) continue;
      Tagged<Object> value = dictionary->ValueAt(isolate, i);
      DCHECK(!IsTheHole(value, isolate));
      DCHECK(!IsAccessorPair(value));
      DCHECK(!IsAccessorInfo(value));
      RETURN_FAILURE_IF_NOT_SUCCESSFUL(accumulator->AddKey(value, convert));
    }
    return ExceptionStatus::kSuccess;
  }
References v8::internal::KeyAccumulator::AddKey(), v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), v8::internal::KeyAccumulator::isolate(), v8::internal::kSuccess, RETURN_FAILURE_IF_NOT_SUCCESSFUL, and v8::internal::value.
AddImpl()
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::AddImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [static]
Definition at line 1729 of file elements.cc.
                                                    {
    PropertyDetails details(PropertyKind::kData, attributes,
                            PropertyCellType::kNoCell);
    DirectHandle<NumberDictionary> dictionary =
        object->HasFastElements() || object->HasFastStringWrapperElements()
            ? JSObject::NormalizeElements(isolate, object)
            : direct_handle(Cast<NumberDictionary>(object->elements()),
                            isolate);
    DirectHandle<NumberDictionary> new_dictionary =
        NumberDictionary::Add(isolate, dictionary, index, value, details);
    new_dictionary->UpdateMaxNumberKey(index, object);
    if (attributes != NONE) object->RequireSlowElements(*new_dictionary);
    if (dictionary.is_identical_to(new_dictionary)) return Just(true);
    object->set_elements(*new_dictionary);
    return Just(true);
  }
References v8::bigint::Add(), v8::internal::Cast< NumberDictionary >(), v8::internal::direct_handle(), v8::internal::index, v8::internal::DirectHandle< T >::is_identical_to(), v8::Just(), v8::internal::kData, v8::internal::kNoCell, v8::internal::NONE, v8::internal::JSObject::NormalizeElements(), and v8::internal::value.
CollectElementIndicesImpl()
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CollectElementIndicesImpl (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator * keys) [inline], [static]
Definition at line 1808 of file elements.cc.
                            {
    if (keys->filter() & SKIP_STRINGS) return ExceptionStatus::kSuccess;
    Isolate* isolate = keys->isolate();
    auto dictionary = Cast<NumberDictionary>(backing_store);
    DirectHandle<FixedArray> elements = isolate->factory()->NewFixedArray(
        GetMaxNumberOfEntries(isolate, *object, *backing_store));
    int insertion_index = 0;
    PropertyFilter filter = keys->filter();
    ReadOnlyRoots roots(isolate);
    for (InternalIndex i : dictionary->IterateEntries()) {
      AllowGarbageCollection allow_gc;
      Tagged<Object> raw_key = dictionary->KeyAt(isolate, i);
      if (!dictionary->IsKey(roots, raw_key)) continue;
      uint32_t key = FilterKey(dictionary, i, raw_key, filter);
      if (key == kMaxUInt32) {
        // This might allocate, but {raw_key} is not used afterwards.
        keys->AddShadowingKey(raw_key, &allow_gc);
        continue;
      }
      elements->set(insertion_index, raw_key);
      insertion_index++;
    }
    SortIndices(isolate, elements, insertion_index);
    for (int i = 0; i < insertion_index; i++) {
      RETURN_FAILURE_IF_NOT_SUCCESSFUL(keys->AddKey(elements->get(i)));
    }
    return ExceptionStatus::kSuccess;
  }
References v8::internal::KeyAccumulator::AddKey(), v8::internal::KeyAccumulator::AddShadowingKey(), v8::internal::Cast< NumberDictionary >(), v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::filter(), v8::internal::KeyAccumulator::isolate(), v8::internal::key, v8::internal::kMaxUInt32, v8::internal::kSuccess, v8::internal::FactoryBase< Impl >::NewFixedArray(), RETURN_FAILURE_IF_NOT_SUCCESSFUL, v8::internal::SKIP_STRINGS, and v8::internal::anonymous_namespace{elements.cc}::SortIndices().
CompareAndSwapAtomicInternalImpl()
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CompareAndSwapAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 1707 of file elements.cc.
                                                                          {
    return Cast<NumberDictionary>(backing_store)
        ->ValueAtCompareAndSwap(entry, expected, value, tag);
  }
References v8::internal::Cast< NumberDictionary >(), and v8::internal::value.
CopyElementsImpl()
static void v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CopyElementsImpl (Isolate * isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size) [inline], [static]
Definition at line 1633 of file elements.cc.
                                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DeleteImpl()
static void v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::DeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, InternalIndex entry) [inline], [static]
Definition at line 1640 of file elements.cc.
                                              {
    DirectHandle<NumberDictionary> dict(Cast<NumberDictionary>(obj->elements()),
                                        isolate);
    dict = NumberDictionary::DeleteEntry(isolate, dict, entry);
    obj->set_elements(*dict);
  }
References v8::internal::Cast< NumberDictionary >().
DirectCollectElementIndicesImpl()
static Handle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::DirectCollectElementIndicesImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, GetKeysConversion convert, PropertyFilter filter, Handle< FixedArray > list, uint32_t * nof_indices, uint32_t insertion_index = 0) [inline], [static]
Definition at line 1839 of file elements.cc.
                                    {
    if (filter & SKIP_STRINGS) return list;
    auto dictionary = Cast<NumberDictionary>(backing_store);
    for (InternalIndex i : dictionary->IterateEntries()) {
      uint32_t key = GetKeyForEntryImpl(isolate, dictionary, i, filter);
      if (key == kMaxUInt32) continue;
      DirectHandle<Object> index = isolate->factory()->NewNumberFromUint(key);
      list->set(insertion_index, *index);
      insertion_index++;
    }
    *nof_indices = insertion_index;
    return list;
  }
References v8::internal::Cast< NumberDictionary >(), v8::internal::Isolate::factory(), v8::internal::index, v8::internal::key, v8::internal::kMaxUInt32, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), and v8::internal::SKIP_STRINGS.
FilterKey()
static uint32_t v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::FilterKey (DirectHandle< NumberDictionary > dictionary, InternalIndex entry, Tagged< Object > raw_key, PropertyFilter filter) [inline], [static]
Definition at line 1787 of file elements.cc.
                                                   {
    DCHECK(IsNumber(raw_key));
    DCHECK_LE(Object::NumberValue(raw_key), kMaxUInt32);
    PropertyDetails details = dictionary->DetailsAt(entry);
    PropertyAttributes attr = details.attributes();
    if ((int{attr} & filter) != 0) return kMaxUInt32;
    return static_cast<uint32_t>(Object::NumberValue(raw_key));
  }
References v8::internal::PropertyDetails::attributes(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::IsNumber(), v8::internal::kMaxUInt32, and v8::internal::Object::NumberValue().
GetAtomicInternalImpl()
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetAtomicInternalImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, SeqCstAccessTag tag) [inline], [static]
Definition at line 1676 of file elements.cc.
                                                {
    return handle(Cast<NumberDictionary>(backing_store)->ValueAt(entry, tag),
                  isolate);
  }
References v8::internal::Cast< NumberDictionary >(), and v8::internal::handle().
GetDetailsImpl() [1/2]
static PropertyDetails v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetDetailsImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 1782 of file elements.cc.
                                                             {
    return Cast<NumberDictionary>(backing_store)->DetailsAt(entry);
  }
References v8::internal::Cast< NumberDictionary >().
GetDetailsImpl() [2/2]
static PropertyDetails v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 1777 of file elements.cc.
                                                             {
    return GetDetailsImpl(holder->elements(), entry);
  }
GetEntryForIndexImpl()
static InternalIndex v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetEntryForIndexImpl (Isolate * isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > store, size_t index, PropertyFilter filter) [inline], [static]
Definition at line 1757 of file elements.cc.
                                                                   {
    DisallowGarbageCollection no_gc;
    Tagged<NumberDictionary> dictionary = Cast<NumberDictionary>(store);
    DCHECK_LE(index, std::numeric_limits<uint32_t>::max());
    InternalIndex entry =
        dictionary->FindEntry(isolate, static_cast<uint32_t>(index));
    if (entry.is_not_found()) return entry;
    if (filter != ALL_PROPERTIES) {
      PropertyDetails details = dictionary->DetailsAt(entry);
      PropertyAttributes attr = details.attributes();
      if ((int{attr} & filter) != 0) return InternalIndex::NotFound();
    }
    return entry;
  }
References v8::internal::ALL_PROPERTIES, v8::internal::PropertyDetails::attributes(), v8::internal::Cast< NumberDictionary >(), DCHECK_LE, v8::internal::index, v8::internal::InternalIndex::is_not_found(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::InternalIndex::NotFound(), and store().
GetImpl()
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 1670 of file elements.cc.
                                                     {
    return handle(GetRaw(backing_store, entry), isolate);
  }
References v8::internal::handle().
GetKeyForEntryImpl()
static uint32_t v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetKeyForEntryImpl (Isolate * isolate, DirectHandle< NumberDictionary > dictionary, InternalIndex entry, PropertyFilter filter) [inline], [static]
Definition at line 1798 of file elements.cc.
                                                            {
    DisallowGarbageCollection no_gc;
    Tagged<Object> raw_key = dictionary->KeyAt(isolate, entry);
    if (!dictionary->IsKey(ReadOnlyRoots(isolate), raw_key)) return kMaxUInt32;
    return FilterKey(dictionary, entry, raw_key, filter);
  }
References v8::internal::kMaxUInt32, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetMaxIndex()
static uint32_t v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetMaxIndex (Tagged< JSObject > receiver, Tagged< FixedArrayBase > elements) [inline], [static]
Definition at line 1556 of file elements.cc.
                                                               {
    // We cannot properly estimate this for dictionaries.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
GetMaxNumberOfEntries()
static uint32_t v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetMaxNumberOfEntries (Isolate * isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 1562 of file elements.cc.
                                                                              {
    return NumberOfElementsImpl(isolate, receiver, backing_store);
  }
GetRaw()
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetRaw (Tagged< FixedArrayBase > store, InternalIndex entry) [inline], [static]
Definition at line 1664 of file elements.cc.
                                                    {
    Tagged<NumberDictionary> backing_store = Cast<NumberDictionary>(store);
    return backing_store->ValueAt(entry);
  }
References v8::internal::Cast< NumberDictionary >(), and store().
HasAccessorsImpl()
static bool v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::HasAccessorsImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 1648 of file elements.cc.
                                                                     {
    DisallowGarbageCollection no_gc;
    Tagged<NumberDictionary> dict = Cast<NumberDictionary>(backing_store);
    if (!dict->requires_slow_elements()) return false;
    PtrComprCageBase cage_base = GetPtrComprCageBase(holder);
    ReadOnlyRoots roots = GetReadOnlyRoots();
    for (InternalIndex i : dict->IterateEntries()) {
      Tagged<Object> key = dict->KeyAt(cage_base, i);
      if (!dict->IsKey(roots, key)) continue;
      PropertyDetails details = dict->DetailsAt(i);
      if (details.kind() == PropertyKind::kAccessor) return true;
    }
    return false;
  }
References v8::internal::Cast< NumberDictionary >(), v8::internal::GetPtrComprCageBase(), v8::internal::GetReadOnlyRoots(), v8::internal::kAccessor, v8::internal::key, v8::internal::PropertyDetails::kind(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
HasEntryImpl()
static bool v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::HasEntryImpl (Isolate * isolate, Tagged< FixedArrayBase > store, InternalIndex entry) [inline], [static]
Definition at line 1749 of file elements.cc.
                                                {
    DisallowGarbageCollection no_gc;
    Tagged<NumberDictionary> dict = Cast<NumberDictionary>(store);
    Tagged<Object> index = dict->KeyAt(isolate, entry);
    return !IsTheHole(index, isolate);
  }
References v8::internal::Cast< NumberDictionary >(), v8::internal::index, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and store().
IncludesValueFastPath()
static bool v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueFastPath (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length, Maybe< bool > * result) [inline], [static]
Definition at line 1877 of file elements.cc.
                                                         {
    DisallowGarbageCollection no_gc;
    Tagged<NumberDictionary> dictionary =
        Cast<NumberDictionary>(receiver->elements());
    Tagged<Object> the_hole = ReadOnlyRoots(isolate).the_hole_value();
    Tagged<Object> undefined = ReadOnlyRoots(isolate).undefined_value();
    // Scan for accessor properties. If accessors are present, then elements
    // must be accessed in order via the slow path.
    bool found = false;
    for (InternalIndex i : dictionary->IterateEntries()) {
      Tagged<Object> k = dictionary->KeyAt(isolate, i);
      if (k == the_hole) continue;
      if (k == undefined) continue;
      uint32_t index;
      if (!Object::ToArrayIndex(k, &index) || index < start_from ||
          index >= length) {
        continue;
      }
      if (dictionary->DetailsAt(i).kind() == PropertyKind::kAccessor) {
        // Restart from beginning in slow path, otherwise we may observably
        // access getters out of order
        return false;
      } else if (!found) {
        Tagged<Object> element_k = dictionary->ValueAt(isolate, i);
        if (Object::SameValueZero(*value, element_k)) found = true;
      }
    }
    *result = Just(found);
    return true;
  }
References v8::internal::Cast< NumberDictionary >(), v8::internal::index, v8::Just(), v8::internal::kAccessor, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::Object::SameValueZero(), v8::internal::Object::ToArrayIndex(), v8::internal::undefined, and v8::internal::value.
IncludesValueImpl()
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [static]
Definition at line 1916 of file elements.cc.
                                                                         {
    DCHECK(JSObject::PrototypeHasNoElements(isolate, *receiver));
    bool search_for_hole = IsUndefined(*value, isolate);
    if (!search_for_hole) {
      Maybe<bool> result = Nothing<bool>();
      if (DictionaryElementsAccessor::IncludesValueFastPath(
              isolate, receiver, value, start_from, length, &result)) {
        return result;
      }
    }
    ElementsKind original_elements_kind = receiver->GetElementsKind();
    USE(original_elements_kind);
    DirectHandle<NumberDictionary> dictionary(
        Cast<NumberDictionary>(receiver->elements()), isolate);
    // Iterate through the entire range, as accessing elements out of order is
    // observable.
    for (size_t k = start_from; k < length; ++k) {
      DCHECK_EQ(receiver->GetElementsKind(), original_elements_kind);
      InternalIndex entry =
          dictionary->FindEntry(isolate, static_cast<uint32_t>(k));
      if (entry.is_not_found()) {
        if (search_for_hole) return Just(true);
        continue;
      }
      PropertyDetails details = GetDetailsImpl(*dictionary, entry);
      switch (details.kind()) {
        case PropertyKind::kData: {
          Tagged<Object> element_k = dictionary->ValueAt(entry);
          if (Object::SameValueZero(*value, element_k)) return Just(true);
          break;
        }
        case PropertyKind::kAccessor: {
          LookupIterator it(isolate, receiver, k,
                            LookupIterator::OWN_SKIP_INTERCEPTOR);
          DCHECK(it.IsFound());
          DCHECK_EQ(it.state(), LookupIterator::ACCESSOR);
          DirectHandle<Object> element_k;
          ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, element_k,
                                           Object::GetPropertyWithAccessor(&it),
                                           Nothing<bool>());
          if (Object::SameValueZero(*value, *element_k)) return Just(true);
          // Bailout to slow path if elements on prototype changed
          if (!JSObject::PrototypeHasNoElements(isolate, *receiver)) {
            return IncludesValueSlowPath(isolate, receiver, value, k + 1,
                                         length);
          }
          // Continue if elements unchanged
          if (*dictionary == receiver->elements()) continue;
          // Otherwise, bailout or update elements
          // If switched to initial elements, return true if searching for
          // undefined, and false otherwise.
          if (receiver->map()->GetInitialElements() == receiver->elements()) {
            return Just(search_for_hole);
          }
          // If switched to fast elements, continue with the correct accessor.
          if (receiver->GetElementsKind() != DICTIONARY_ELEMENTS) {
            ElementsAccessor* accessor = receiver->GetElementsAccessor();
            return accessor->IncludesValue(isolate, receiver, value, k + 1,
                                           length);
          }
          dictionary = direct_handle(
              Cast<NumberDictionary>(receiver->elements()), isolate);
          break;
        }
      }
    }
    return Just(false);
  }
References v8::internal::LookupIterator::ACCESSOR, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DICTIONARY_ELEMENTS, v8::internal::direct_handle(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::ElementsAccessor::IncludesValue(), v8::internal::anonymous_namespace{elements.cc}::IncludesValueSlowPath(), v8::internal::InternalIndex::is_not_found(), v8::internal::LookupIterator::IsFound(), v8::Just(), v8::internal::kAccessor, v8::internal::kData, v8::internal::PropertyDetails::kind(), v8::internal::length, v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::JSObject::PrototypeHasNoElements(), v8::base::internal::result, v8::internal::Object::SameValueZero(), v8::internal::LookupIterator::state(), USE, and v8::internal::value.
IndexOfValueImpl()
static Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [static]
Definition at line 1997 of file elements.cc.
                                                                           {
    DCHECK(JSObject::PrototypeHasNoElements(isolate, *receiver));
    ElementsKind original_elements_kind = receiver->GetElementsKind();
    USE(original_elements_kind);
    DirectHandle<NumberDictionary> dictionary(
        Cast<NumberDictionary>(receiver->elements()), isolate);
    // Iterate through entire range, as accessing elements out of order is
    // observable.
    for (size_t k = start_from; k < length; ++k) {
      DCHECK_EQ(receiver->GetElementsKind(), original_elements_kind);
      DCHECK_LE(k, std::numeric_limits<uint32_t>::max());
      InternalIndex entry =
          dictionary->FindEntry(isolate, static_cast<uint32_t>(k));
      if (entry.is_not_found()) continue;
      PropertyDetails details =
          GetDetailsImpl(*dictionary, InternalIndex(entry));
      switch (details.kind()) {
        case PropertyKind::kData: {
          Tagged<Object> element_k = dictionary->ValueAt(entry);
          if (Object::StrictEquals(*value, element_k)) {
            return Just<int64_t>(k);
          }
          break;
        }
        case PropertyKind::kAccessor: {
          LookupIterator it(isolate, receiver, k,
                            LookupIterator::OWN_SKIP_INTERCEPTOR);
          DCHECK(it.IsFound());
          DCHECK_EQ(it.state(), LookupIterator::ACCESSOR);
          DirectHandle<Object> element_k;
          ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, element_k,
                                           Object::GetPropertyWithAccessor(&it),
                                           Nothing<int64_t>());
          if (Object::StrictEquals(*value, *element_k)) return Just<int64_t>(k);
          // Bailout to slow path if elements on prototype changed.
          if (!JSObject::PrototypeHasNoElements(isolate, *receiver)) {
            return IndexOfValueSlowPath(isolate, receiver, value, k + 1,
                                        length);
          }
          // Continue if elements unchanged.
          if (*dictionary == receiver->elements()) continue;
          // Otherwise, bailout or update elements.
          if (receiver->GetElementsKind() != DICTIONARY_ELEMENTS) {
            // Otherwise, switch to slow path.
            return IndexOfValueSlowPath(isolate, receiver, value, k + 1,
                                        length);
          }
          dictionary = direct_handle(
              Cast<NumberDictionary>(receiver->elements()), isolate);
          break;
        }
      }
    }
    return Just<int64_t>(-1);
  }
References v8::internal::LookupIterator::ACCESSOR, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::DICTIONARY_ELEMENTS, v8::internal::direct_handle(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::anonymous_namespace{elements.cc}::IndexOfValueSlowPath(), v8::internal::InternalIndex::is_not_found(), v8::internal::LookupIterator::IsFound(), v8::internal::kAccessor, v8::internal::kData, v8::internal::PropertyDetails::kind(), v8::internal::length, v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::JSObject::PrototypeHasNoElements(), v8::internal::LookupIterator::state(), v8::internal::Object::StrictEquals(), USE, and v8::internal::value.
NumberOfElementsImpl()
static uint32_t v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::NumberOfElementsImpl (Isolate * isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 1568 of file elements.cc.
                                                                             {
    Tagged<NumberDictionary> dict = Cast<NumberDictionary>(backing_store);
    return dict->NumberOfElements();
  }
References v8::internal::Cast< NumberDictionary >().
ReconfigureImpl()
static void v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::ReconfigureImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [inline], [static]
Definition at line 1714 of file elements.cc.
                                                             {
    Tagged<NumberDictionary> dictionary = Cast<NumberDictionary>(*store);
    if (attributes != NONE) object->RequireSlowElements(dictionary);
    dictionary->ValueAtPut(entry, *value);
    PropertyDetails details = dictionary->DetailsAt(entry);
    details =
        PropertyDetails(PropertyKind::kData, attributes,
                        PropertyCellType::kNoCell, details.dictionary_index());
    dictionary->DetailsAtPut(entry, details);
  }
References v8::internal::Cast< NumberDictionary >(), v8::internal::PropertyDetails::dictionary_index(), v8::internal::kData, v8::internal::kNoCell, v8::internal::NONE, store(), and v8::internal::value.
SetAtomicInternalImpl()
static void v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 1693 of file elements.cc.
                                                         {
    Cast<NumberDictionary>(backing_store)->ValueAtPut(entry, value, tag);
  }
References v8::internal::Cast< NumberDictionary >(), and v8::internal::value.
SetImpl() [1/2]
static void v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 1683 of file elements.cc.
                                                   {
    SetImpl(holder->elements(), entry, value);
  }
References v8::internal::value.
SetImpl() [2/2]
static void v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 1688 of file elements.cc.
                                                                        {
    Cast<NumberDictionary>(backing_store)->ValueAtPut(entry, value);
  }
References v8::internal::Cast< NumberDictionary >(), and v8::internal::value.
SetLengthImpl()
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetLengthImpl (Isolate * isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store) [inline], [static]
Definition at line 1575 of file elements.cc.
                                                                               {
    auto dict = Cast<NumberDictionary>(backing_store);
    uint32_t old_length = 0;
    CHECK(Object::ToArrayLength(array->length(), &old_length));
    {
      DisallowGarbageCollection no_gc;
      ReadOnlyRoots roots(isolate);
      if (length < old_length) {
        if (dict->requires_slow_elements()) {
          // Find last non-deletable element in range of elements to be
          // deleted and adjust range accordingly.
          for (InternalIndex entry : dict->IterateEntries()) {
            Tagged<Object> index = dict->KeyAt(isolate, entry);
            if (dict->IsKey(roots, index)) {
              uint32_t number =
                  static_cast<uint32_t>(Object::NumberValue(index));
              if (length <= number && number < old_length) {
                PropertyDetails details = dict->DetailsAt(entry);
                if (!details.IsConfigurable()) length = number + 1;
              }
            }
          }
        }
        if (length == 0) {
          // Flush the backing store.
          array->initialize_elements();
        } else {
          // Remove elements that should be deleted.
          int removed_entries = 0;
          for (InternalIndex entry : dict->IterateEntries()) {
            Tagged<Object> index = dict->KeyAt(isolate, entry);
            if (dict->IsKey(roots, index)) {
              uint32_t number =
                  static_cast<uint32_t>(Object::NumberValue(index));
              if (length <= number && number < old_length) {
                dict->ClearEntry(entry);
                removed_entries++;
              }
            }
          }
          if (removed_entries > 0) {
            // Update the number of elements.
            dict->ElementsRemoved(removed_entries);
          }
        }
      }
    }
    DirectHandle<Number> length_obj =
        isolate->factory()->NewNumberFromUint(length);
    array->set_length(*length_obj);
    return Just(true);
  }
References v8::internal::Cast< NumberDictionary >(), CHECK, v8::internal::Isolate::factory(), v8::internal::index, v8::internal::PropertyDetails::IsConfigurable(), v8::Just(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), and v8::internal::Object::ToArrayLength().
SwapAtomicInternalImpl()
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SwapAtomicInternalImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 1699 of file elements.cc.
                                                                      {
    return handle(
        Cast<NumberDictionary>(backing_store)->ValueAtSwap(entry, value, tag),
        isolate);
  }
References v8::internal::Cast< NumberDictionary >(), v8::internal::handle(), and v8::internal::value.
ValidateContents()
static void v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::ValidateContents (Isolate * isolate, Tagged< JSObject > holder, size_t length) [inline], [static]
Definition at line 2063 of file elements.cc.
                                              {
    DisallowGarbageCollection no_gc;
#if DEBUG
    DCHECK_EQ(holder->map()->elements_kind(), DICTIONARY_ELEMENTS);
    if (!v8_flags.enable_slow_asserts) return;
    ReadOnlyRoots roots = GetReadOnlyRoots();
    Tagged<NumberDictionary> dictionary =
        Cast<NumberDictionary>(holder->elements());
    // Validate the requires_slow_elements and max_number_key values.
    bool requires_slow_elements = false;
    int max_key = 0;
    for (InternalIndex i : dictionary->IterateEntries()) {
      Tagged<Object> k;
      if (!dictionary->ToKey(roots, i, &k)) continue;
      DCHECK_LE(0.0, Object::NumberValue(k));
      if (Object::NumberValue(k) >
          NumberDictionary::kRequiresSlowElementsLimit) {
        requires_slow_elements = true;
      } else {
        max_key = std::max(max_key, Smi::ToInt(k));
      }
    }
    if (requires_slow_elements) {
      DCHECK(dictionary->requires_slow_elements());
    } else if (!dictionary->requires_slow_elements()) {
      DCHECK_LE(max_key, dictionary->max_number_key());
    }
#endif
  }
References v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::DICTIONARY_ELEMENTS, v8::internal::GetReadOnlyRoots(), v8::internal::NumberDictionary::kRequiresSlowElementsLimit, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), v8::internal::Smi::ToInt(), and v8::internal::v8_flags.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc