v8::internal::torque::NamespaceConstant Class Reference
#include <declarable.h>
Public Member Functions
const std::string & external_name () const
Expression * body () const
Private Member Functions
NamespaceConstant (Identifier *constant_name, std::string external_name, const Type *type, Expression *body)
Private Attributes
std::string external_name_
Expression * body_
Friends
class Declarations
Additional Inherited Members
Detailed Description
Definition at line 263 of file declarable.h.
Constructor & Destructor Documentation
NamespaceConstant()
v8::internal::torque::NamespaceConstant::NamespaceConstant (Identifier * constant_name, std::string external_name, const Type * type, Expression * body) [inline], [explicit], [private]
Definition at line 272 of file declarable.h.
      : Value(Declarable::kNamespaceConstant, type, constant_name),
        external_name_(std::move(external_name)),
        body_(body) {}
Member Function Documentation
body()
Expression* v8::internal::torque::NamespaceConstant::body () const [inline]
Definition at line 268 of file declarable.h.
{ return body_; }
References body_.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
external_name()
const std::string& v8::internal::torque::NamespaceConstant::external_name () const [inline]
Definition at line 267 of file declarable.h.
{ return external_name_; }
References external_name_.
Referenced by v8::internal::torque::operator<<(), and v8::internal::torque::ImplementationVisitor::Visit().
Friends And Related Function Documentation
Declarations
friend class Declarations [friend]
Definition at line 271 of file declarable.h.
Member Data Documentation
body_
Expression* v8::internal::torque::NamespaceConstant::body_ [private]
Definition at line 280 of file declarable.h.
Referenced by body().
external_name_
std::string v8::internal::torque::NamespaceConstant::external_name_ [private]
Definition at line 279 of file declarable.h.
Referenced by external_name().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h