v8::internal::wasm::WasmInterpreterRuntime Class Reference
#include <wasm-interpreter-runtime.h>
Classes
struct IndirectCallValue
Public Types
using PackedArgsSizeField = base::BitField< uint32_t, 0, 14 >
using HasRefArgsField = base::BitField< bool, 14, 1 >
using HasRefRetsField = base::BitField< bool, 15, 1 >
Public Member Functions
WasmInterpreterRuntime (const WasmModule *module, Isolate *isolate, IndirectHandle< WasmInstanceObject > instance_object, WasmInterpreter::CodeMap *codemap)
WasmBytecode * GetFunctionBytecode (uint32_t func_index)
std::vector< WasmInterpreterStackEntry > GetInterpretedStack (Address frame_pointer)
int GetFunctionIndex (Address frame_pointer, int index) const
void SetTrapFunctionIndex (int32_t func_index)
Isolate * GetIsolate () const
uint8_t * GetGlobalAddress (uint32_t index)
DirectHandle< Object > GetGlobalRef (uint32_t index) const
void SetGlobalRef (uint32_t index, DirectHandle< Object > ref) const
int32_t MemoryGrow (uint32_t delta_pages)
uint64_t MemorySize () const
bool IsMemory64 () const
uint8_t * GetMemoryStart () const
size_t GetMemorySize () const
bool MemoryInit (const uint8_t *&current_code, uint32_t data_segment_index, uint64_t dst, uint64_t src, uint64_t size)
bool MemoryCopy (const uint8_t *&current_code, uint64_t dst, uint64_t src, uint64_t size)
bool MemoryFill (const uint8_t *&current_code, uint64_t dst, uint32_t value, uint64_t size)
bool AllowsAtomicsWait () const
int32_t AtomicNotify (uint64_t effective_index, int32_t val)
int32_t I32AtomicWait (uint64_t effective_index, int32_t val, int64_t timeout)
int32_t I64AtomicWait (uint64_t effective_index, int64_t val, int64_t timeout)
bool WasmStackCheck (const uint8_t *current_bytecode, const uint8_t *&code)
bool TableGet (const uint8_t *&current_code, uint32_t table_index, uint32_t entry_index, DirectHandle< Object > *result)
void TableSet (const uint8_t *&current_code, uint32_t table_index, uint32_t entry_index, DirectHandle< Object > ref)
void TableInit (const uint8_t *&current_code, uint32_t table_index, uint32_t element_segment_index, uint32_t dst, uint32_t src, uint32_t size)
void TableCopy (const uint8_t *&current_code, uint32_t dst_table_index, uint32_t src_table_index, uint32_t dst, uint32_t src, uint32_t size)
uint32_t TableGrow (uint32_t table_index, uint32_t delta, DirectHandle< Object > value)
uint32_t TableSize (uint32_t table_index)
void TableFill (const uint8_t *&current_code, uint32_t table_index, uint32_t count, DirectHandle< Object > value, uint32_t start)
void DataDrop (uint32_t index)
void ElemDrop (uint32_t index)
const WasmTag & GetWasmTag (uint32_t tag_index) const
DirectHandle< WasmExceptionPackage > CreateWasmExceptionPackage (uint32_t tag_index) const
void UnpackException (uint32_t *sp, const WasmTag &tag, DirectHandle< Object > exception_object, uint32_t first_param_slot_index, uint32_t first_param_ref_stack_index)
void ThrowException (const uint8_t *&code, uint32_t *sp, Tagged< Object > exception_object)
void RethrowException (const uint8_t *&code, uint32_t *sp, uint32_t catch_block_index)
void BeginExecution (WasmInterpreterThread *thread, uint32_t function_index, Address frame_pointer, uint8_t *interpreter_fp, uint32_t ref_stack_offset, const std::vector< WasmValue > *argument_values=nullptr)
void ContinueExecution (WasmInterpreterThread *thread, bool called_from_js)
void ExecuteImportedFunction (const uint8_t *&code, uint32_t func_index, uint32_t current_stack_size, uint32_t ref_stack_fp_offset, uint32_t slot_offset, uint32_t return_slot_offset, bool is_tail_call=false)
void PrepareTailCall (const uint8_t *&code, uint32_t func_index, uint32_t current_stack_size, uint32_t return_slot_offset)
void ExecuteFunction (const uint8_t *&code, uint32_t function_index, uint32_t current_stack_size, uint32_t ref_stack_fp_offset, uint32_t slot_offset, uint32_t return_slot_offset)
void ExecuteIndirectCall (const uint8_t *&current_code, uint32_t table_index, uint32_t sig_index, uint32_t entry_index, uint32_t stack_pos, uint32_t *sp, uint32_t ref_stack_fp_offset, uint32_t slot_offset, uint32_t return_slot_offset, bool is_tail_call)
void ExecuteCallRef (const uint8_t *&current_code, WasmRef func_ref, uint32_t sig_index, uint32_t stack_pos, uint32_t *sp, uint32_t ref_stack_fp_offset, uint32_t slot_offset, uint32_t return_slot_offset, bool is_tail_call)
const WasmValue & GetReturnValue (size_t index) const
bool IsRefNull (DirectHandle< Object > ref) const
DirectHandle< Object > GetFunctionRef (uint32_t index) const
void StoreWasmRef (uint32_t ref_stack_index, const WasmRef &ref)
WasmRef ExtractWasmRef (uint32_t ref_stack_index)
void UnwindCurrentStackFrame (uint32_t *sp, uint32_t slot_offset, uint32_t rets_size, uint32_t args_size, uint32_t rets_refs, uint32_t args_refs, uint32_t ref_stack_fp_offset)
void PrintStack (uint32_t *sp, RegMode reg_mode, int64_t r0, double fp0)
void SetTrap (TrapReason trap_reason, pc_t trap_pc)
void SetTrap (TrapReason trap_reason, const uint8_t *&current_code)
DirectHandle< Map > RttCanon (uint32_t type_index) const
std::pair< DirectHandle< WasmStruct >, const StructType * > StructNewUninitialized (uint32_t index) const
std::pair< DirectHandle< WasmArray >, const ArrayType * > ArrayNewUninitialized (uint32_t length, uint32_t array_index) const
WasmRef WasmArrayNewSegment (uint32_t array_index, uint32_t segment_index, uint32_t offset, uint32_t length)
bool WasmArrayInitSegment (uint32_t segment_index, WasmRef wasm_array, uint32_t array_offset, uint32_t segment_offset, uint32_t length)
bool WasmArrayCopy (WasmRef dest_wasm_array, uint32_t dest_index, WasmRef src_wasm_array, uint32_t src_index, uint32_t length)
WasmRef WasmJSToWasmObject (WasmRef extern_ref, ValueType value_type, uint32_t canonical_index) const
WasmRef JSToWasmObject (WasmRef extern_ref, ValueType value_type) const
WasmRef WasmToJSObject (WasmRef ref) const
const ArrayType * GetArrayType (uint32_t array_index) const
DirectHandle< Object > GetWasmArrayRefElement (Tagged< WasmArray > array, uint32_t index) const
bool SubtypeCheck (const WasmRef obj, const ValueType obj_type, const DirectHandle< Map > rtt, const ModuleTypeIndex target_type, bool null_succeeds) const
bool RefIsEq (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
bool RefIsI31 (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
bool RefIsStruct (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
bool RefIsArray (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
bool RefIsString (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
bool IsNullTypecheck (const WasmRef obj, const ValueType obj_type) const
Tagged< Object > GetNullValue (const ValueType obj_type) const
size_t TotalBytecodeSize () const
void ResetCurrentHandleScope ()
WasmInterpreterRuntime (const WasmInterpreterRuntime &)=delete
WasmInterpreterRuntime & operator= (const WasmInterpreterRuntime &)=delete
Static Public Member Functions
static void UpdateIndirectCallTable (Isolate *isolate, DirectHandle< WasmInstanceObject > instance, uint32_t table_index)
static void ClearIndirectCallCacheEntry (Isolate *isolate, DirectHandle< WasmInstanceObject > instance, uint32_t table_index, uint32_t entry_index)
static void UpdateMemoryAddress (DirectHandle< WasmInstanceObject > instance)
static bool IsNull (Isolate *isolate, const WasmRef obj, const ValueType obj_type)
static int memory_start_offset ()
static int instruction_table_offset ()
Private Types
typedef std::vector< IndirectCallValue > IndirectCallTable
using WasmToJSCallSig = Address(Address js_function, Address packed_args, Address saved_c_entry_fp, const FunctionSig *sig, Address c_entry_fp, Address callable)
Private Member Functions
ExternalCallResult CallImportedFunction (const uint8_t *&current_code, uint32_t function_index, uint32_t *sp, uint32_t current_stack_size, uint32_t ref_stack_fp_index, uint32_t current_slot_offset)
void PurgeIndirectCallCache (uint32_t table_index)
ExternalCallResult CallExternalJSFunction (const uint8_t *&current_code, const WasmModule *module, DirectHandle< Object > object_ref, const FunctionSig *sig, uint32_t *sp, uint32_t return_slot_offset)
Address EffectiveAddress (uint64_t index) const
bool BoundsCheckMemRange (uint64_t index, uint64_t *size, Address *out_address) const
void InitGlobalAddressCache ()
void InitMemoryAddresses ()
void InitIndirectFunctionTables ()
bool CheckIndirectCallSignature (uint32_t table_index, uint32_t entry_index, uint32_t sig_index) const
void StoreRefArgsIntoStackSlots (uint8_t *sp, uint32_t ref_stack_fp_offset, const FunctionSig *sig)
void StoreRefResultsIntoRefStack (uint8_t *sp, uint32_t ref_stack_fp_offset, const FunctionSig *sig)
void InitializeRefLocalsRefs (const WasmBytecode *target_function)
WasmInterpreterThread::ExceptionHandlingResult HandleException (uint32_t *sp, const uint8_t *&current_code)
bool MatchingExceptionTag (DirectHandle< Object > exception_object, uint32_t index) const
bool SubtypeCheck (Tagged< Map > rtt, Tagged< Map > formal_rtt, uint32_t type_index) const
WasmInterpreterThread * thread () const
WasmInterpreterThread::State state () const
DirectHandle< FixedArray > reference_stack () const
void CallWasmToJSBuiltin (Isolate *isolate, DirectHandle< Object > object_ref, Address packed_args, const FunctionSig *sig)
DirectHandle< WasmTrustedInstanceData > wasm_trusted_instance_data () const
Private Attributes
Isolate * isolate_
const WasmModule * module_
IndirectHandle< WasmInstanceObject > instance_object_
WasmInterpreter::CodeMap * codemap_
uint32_t start_function_index_
FrameState current_frame_
std::vector< WasmValue > function_result_
int trap_function_index_
pc_t trap_pc_
WasmInterpreterThread * current_thread_
base::TimeTicks fuzzer_start_time_
uint8_t * memory_start_
PWasmOp *const * instruction_table_
std::vector< uint8_t * > global_addresses_
std::vector< IndirectCallTable > indirect_call_tables_
GeneratedCode< WasmToJSCallSig > generic_wasm_to_js_interpreter_wrapper_fn_
Detailed Description
Definition at line 29 of file wasm-interpreter-runtime.h.
Member Typedef Documentation
HasRefArgsField
using v8::internal::wasm::WasmInterpreterRuntime::HasRefArgsField = base::BitField<bool, 14, 1>
Definition at line 224 of file wasm-interpreter-runtime.h.
HasRefRetsField
using v8::internal::wasm::WasmInterpreterRuntime::HasRefRetsField = base::BitField<bool, 15, 1>
Definition at line 225 of file wasm-interpreter-runtime.h.
IndirectCallTable
typedef std::vector<IndirectCallValue> v8::internal::wasm::WasmInterpreterRuntime::IndirectCallTable [private]
Definition at line 349 of file wasm-interpreter-runtime.h.
PackedArgsSizeField
using v8::internal::wasm::WasmInterpreterRuntime::PackedArgsSizeField = base::BitField<uint32_t, 0, 14>
Definition at line 223 of file wasm-interpreter-runtime.h.
WasmToJSCallSig
using v8::internal::wasm::WasmInterpreterRuntime::WasmToJSCallSig = Address(Address js_function, Address packed_args, Address saved_c_entry_fp, const FunctionSig* sig, Address c_entry_fp, Address callable) [private]
Definition at line 352 of file wasm-interpreter-runtime.h.
Constructor & Destructor Documentation
WasmInterpreterRuntime() [1/2]
v8::internal::wasm::WasmInterpreterRuntime::WasmInterpreterRuntime (const WasmModule * module, Isolate * isolate, IndirectHandle< WasmInstanceObject > instance_object, WasmInterpreter::CodeMap * codemap)
Definition at line 308 of file wasm-interpreter-runtime.cc.
    : isolate_(isolate),
      module_(module),
      instance_object_(instance_object),
      codemap_(codemap),
      start_function_index_(UINT_MAX),
      trap_function_index_(-1),
      trap_pc_(0),
      current_thread_(nullptr),
      fuzzer_start_time_(base::TimeTicks::Now()),
      memory_start_(nullptr),
      instruction_table_(kInstructionTable),
      generic_wasm_to_js_interpreter_wrapper_fn_(
          GeneratedCode<WasmToJSCallSig>::FromAddress(isolate, {}))
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      ,
      shadow_stack_(nullptr)
#endif // V8_ENABLE_DRUMBRAKE_TRACING
{
  DCHECK(v8_flags.wasm_jitless);
  InitGlobalAddressCache();
  InitMemoryAddresses();
  InitIndirectFunctionTables();
  // Initialize address of GenericWasmToJSInterpreterWrapper builtin.
  Address wasm_to_js_code_addr_addr =
      isolate->isolate_root() +
      IsolateData::BuiltinEntrySlotOffset(Builtin::kWasmInterpreterCWasmEntry);
  Address wasm_to_js_code_addr =
      *reinterpret_cast<Address*>(wasm_to_js_code_addr_addr);
  generic_wasm_to_js_interpreter_wrapper_fn_ =
      GeneratedCode<WasmToJSCallSig>::FromAddress(isolate,
                                                  wasm_to_js_code_addr);
}
WasmInterpreterRuntime() [2/2]
v8::internal::wasm::WasmInterpreterRuntime::WasmInterpreterRuntime (const WasmInterpreterRuntime &) [delete]
Member Function Documentation
AllowsAtomicsWait()
bool v8::internal::wasm::WasmInterpreterRuntime::AllowsAtomicsWait () const
Definition at line 836 of file wasm-interpreter-runtime.cc.
                                                     {
  return !module_->memories.empty() && module_->memories[0].is_shared &&
         isolate_->allow_atomics_wait();
}
References v8::internal::Isolate::allow_atomics_wait(), isolate_, v8::internal::wasm::WasmModule::memories, and module_.
ArrayNewUninitialized()
std::pair< DirectHandle< WasmArray >, const ArrayType * > v8::internal::wasm::WasmInterpreterRuntime::ArrayNewUninitialized (uint32_t length, uint32_t array_index) const
Definition at line 2405 of file wasm-interpreter-runtime.cc.
                                                                          {
  const ArrayType* array_type = GetArrayType(array_index);
  if (V8_UNLIKELY(static_cast<int>(length) < 0 ||
                  static_cast<int>(length) >
                      WasmArray::MaxLength(array_type))) {
    return {};
  }
  DirectHandle<Map> rtt = RttCanon(array_index);
  return {
      {isolate_->factory()->NewWasmArrayUninitialized(length, rtt), isolate_},
      array_type};
}
References v8::internal::Isolate::factory(), GetArrayType(), isolate_, v8::internal::length, v8::internal::WasmArray::MaxLength(), RttCanon(), and V8_UNLIKELY.
AtomicNotify()
int32_t v8::internal::wasm::WasmInterpreterRuntime::AtomicNotify (uint64_t effective_index, int32_t val)
Definition at line 841 of file wasm-interpreter-runtime.cc.
                                                          {
  if (module_->memories.empty() || !module_->memories[0].is_shared) {
    return 0;
  } else {
    HandleScope handle_scope(isolate_);
    // TODO(paolosev@microsoft.com): Support multiple memories.
    uint32_t memory_index = 0;
    DirectHandle<JSArrayBuffer> array_buffer(wasm_trusted_instance_data()
                                                 ->memory_object(memory_index)
                                                 ->array_buffer(),
                                             isolate_);
    int result = FutexEmulation::Wake(*array_buffer, buffer_offset, val);
    return result;
  }
}
References isolate_, v8::internal::wasm::WasmModule::memories, module_, v8::base::internal::result, v8::internal::FutexEmulation::Wake(), and wasm_trusted_instance_data().
BeginExecution()
void v8::internal::wasm::WasmInterpreterRuntime::BeginExecution (WasmInterpreterThread * thread, uint32_t function_index, Address frame_pointer, uint8_t * interpreter_fp, uint32_t ref_stack_offset, const std::vector< WasmValue > * argument_values = nullptr)
Definition at line 894 of file wasm-interpreter-runtime.cc.
                                                 {
  current_thread_ = thread;
  start_function_index_ = func_index;
  thread->StartActivation(this, frame_pointer, interpreter_fp, current_frame_);
  current_frame_.current_function_ = nullptr;
  current_frame_.previous_frame_ = nullptr;
  current_frame_.current_bytecode_ = nullptr;
  current_frame_.current_sp_ = interpreter_fp;
  current_frame_.ref_array_current_sp_ = ref_stack_offset;
  current_frame_.thread_ = thread;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  current_frame_.current_stack_start_args_ = thread->CurrentStackFrameStart();
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  const FunctionSig* sig = module_->functions[func_index].sig;
  size_t args_count = 0;
  uint32_t rets_slots_size = 0;
  uint32_t ref_rets_count = 0;
  uint32_t ref_args_count = 0;
  WasmBytecode* target_function = GetFunctionBytecode(func_index);
  if (target_function) {
    args_count = target_function->args_count();
    rets_slots_size = target_function->rets_slots_size();
    ref_rets_count = target_function->ref_rets_count();
    ref_args_count = target_function->ref_args_count();
  } else {
    // We begin execution by calling an imported function.
    args_count = sig->parameter_count();
    rets_slots_size = WasmBytecode::RetsSizeInSlots(sig);
    ref_rets_count = WasmBytecode::RefRetsCount(sig);
    ref_args_count = WasmBytecode::RefArgsCount(sig);
  }
  // Here GC is disabled, we cannot "resize" the reference_stack_ FixedArray
  // before having created Handles for the Ref arguments passed in
  // argument_values.
  HandleScope handle_scope(isolate_); // Avoid leaking handles.
  DirectHandleVector<Object> ref_args(isolate_);
  if (ref_args_count > 0) {
    ref_args.reserve(ref_args_count);
  }
  uint8_t* p = interpreter_fp + rets_slots_size * kSlotSize;
  // Check stack overflow.
  const uint8_t* stack_limit = thread->StackLimitAddress();
  if (V8_UNLIKELY(p + (ref_rets_count + ref_args_count) * sizeof(WasmRef) >=
                  stack_limit)) {
    size_t additional_required_size =
        p + (ref_rets_count + ref_args_count) * sizeof(WasmRef) - stack_limit;
    if (!thread->ExpandStack(additional_required_size)) {
      // TODO(paolosev@microsoft.com) - Calculate initial function offset.
      ClearThreadInWasmScope clear_wasm_flag(isolate_);
      SealHandleScope shs(isolate_);
      isolate_->StackOverflow();
      const pc_t trap_pc = 0;
      SetTrap(TrapReason::kTrapUnreachable, trap_pc);
      thread->FinishActivation();
      return;
    }
  }
  if (argument_values) {
    // We are being called from JS, arguments are passed in the
    // {argument_values} vector.
    for (size_t i = 0; i < argument_values->size(); i++) {
      const WasmValue& value = (*argument_values)[i];
      switch (value.type().kind()) {
        case kI32:
          base::WriteUnalignedValue<int32_t>(reinterpret_cast<Address>(p),
                                             value.to<int32_t>());
          p += sizeof(int32_t);
          break;
        case kI64:
          base::WriteUnalignedValue<int64_t>(reinterpret_cast<Address>(p),
                                             value.to<int64_t>());
          p += sizeof(int64_t);
          break;
        case kF32:
          base::WriteUnalignedValue<float>(reinterpret_cast<Address>(p),
                                           value.to<float>());
          p += sizeof(float);
          break;
        case kF64:
          base::WriteUnalignedValue<double>(reinterpret_cast<Address>(p),
                                            value.to<double>());
          p += sizeof(double);
          break;
        case kRef:
        case kRefNull:
          ref_args.push_back(value.to_ref());
          base::WriteUnalignedValue<uint64_t>(reinterpret_cast<Address>(p),
                                              kSlotsZapValue);
          p += sizeof(WasmRef);
          break;
        case kS128:
        default:
          UNREACHABLE();
      }
    }
  } else {
    // We are being called from Wasm, arguments are already in the stack.
    for (size_t i = 0; i < args_count; i++) {
      switch (sig->GetParam(i).kind()) {
        case kI32:
          p += sizeof(int32_t);
          break;
        case kI64:
          p += sizeof(int64_t);
          break;
        case kF32:
          p += sizeof(float);
          break;
        case kF64:
          p += sizeof(double);
          break;
        case kS128:
          p += sizeof(Simd128);
          break;
        case kRef:
        case kRefNull: {
          DirectHandle<Object> ref =
              base::ReadUnalignedValue<DirectHandle<Object>>(
                  reinterpret_cast<Address>(p));
          ref_args.push_back(ref);
          p += sizeof(WasmRef);
          break;
        }
        default:
          UNREACHABLE();
      }
    }
  }
  {
    // Once we have read ref argument passed on the stack and we have stored
    // them into the ref_args vector of Handles, we can re-enable the GC.
    AllowHeapAllocation allow_gc;
    if (ref_rets_count + ref_args_count > 0) {
      // Reserve space for reference args and return values in the
      // reference_stack_.
      current_thread_->EnsureRefStackSpace(
          current_frame_.ref_array_current_sp_ + ref_rets_count +
          ref_args_count);
      uint32_t ref_stack_arg_index = ref_rets_count;
      for (uint32_t ref_arg_index = 0; ref_arg_index < ref_args_count;
           ref_arg_index++) {
        StoreWasmRef(ref_stack_arg_index++, ref_args[ref_arg_index]);
      }
    }
  }
}
References v8::internal::wasm::WasmBytecode::args_count(), current_frame_, current_thread_, v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), v8::internal::wasm::WasmInterpreterThread::ExpandStack(), v8::internal::wasm::WasmInterpreterThread::FinishActivation(), v8::internal::wasm::WasmModule::functions, GetFunctionBytecode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::kSlotSize, v8::internal::kSlotsZapValue, module_, v8::internal::DirectHandleVector< T >::push_back(), v8::internal::wasm::WasmBytecode::ref_args_count(), v8::internal::wasm::WasmBytecode::ref_rets_count(), v8::internal::wasm::WasmBytecode::RefArgsCount(), v8::internal::wasm::WasmBytecode::RefRetsCount(), v8::internal::DirectHandleVector< T >::reserve(), v8::internal::wasm::WasmBytecode::rets_slots_size(), v8::internal::wasm::WasmBytecode::RetsSizeInSlots(), SetTrap(), v8::internal::sig, v8::internal::wasm::WasmInterpreterThread::StackLimitAddress(), v8::internal::Isolate::StackOverflow(), start_function_index_, v8::internal::wasm::WasmInterpreterThread::StartActivation(), StoreWasmRef(), thread(), v8::internal::UNREACHABLE(), V8_UNLIKELY, and v8::internal::value.
BoundsCheckMemRange()
bool v8::internal::wasm::WasmInterpreterRuntime::BoundsCheckMemRange (uint64_t index, uint64_t * size, Address * out_address) const [inline], [private]
Definition at line 35 of file wasm-interpreter-runtime-inl.h.
                                                                {
  DirectHandle<WasmTrustedInstanceData> trusted_data =
      wasm_trusted_instance_data();
  DCHECK_GE(std::numeric_limits<uintptr_t>::max(),
            trusted_data->memory0_size());
  if (!base::ClampToBounds<uint64_t>(index, size,
                                     trusted_data->memory0_size())) {
    return false;
  }
  *out_address = EffectiveAddress(index);
  return true;
}
References DCHECK_GE, EffectiveAddress(), v8::internal::index, size(), and wasm_trusted_instance_data().
Referenced by MemoryCopy(), MemoryFill(), and MemoryInit().
CallExternalJSFunction()
ExternalCallResult v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction (const uint8_t *& current_code, const WasmModule * module, DirectHandle< Object > object_ref, const FunctionSig * sig, uint32_t * sp, uint32_t return_slot_offset) [private]
Definition at line 2234 of file wasm-interpreter-runtime.cc.
                                 {
  // TODO(paolosev@microsoft.com) Cache IsJSCompatibleSignature result?
  if (!IsJSCompatibleSignature(
          reinterpret_cast<const wasm::CanonicalSig*>(sig))) {
    AllowHeapAllocation allow_gc;
    ClearThreadInWasmScope clear_wasm_flag(isolate_);
    isolate_->Throw(*isolate_->factory()->NewTypeError(
        MessageTemplate::kWasmTrapJSTypeError));
    return ExternalCallResult::EXTERNAL_EXCEPTION;
  }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (v8_flags.trace_drumbrake_execution) {
    Trace(" => Calling external function\n");
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  CWasmArgumentsPacker packer(CWasmArgumentsPacker::TotalSize(
      reinterpret_cast<const wasm::CanonicalSig*>(sig)));
  uint32_t* p = sp + WasmBytecode::RetsSizeInSlots(sig);
  for (size_t i = 0; i < sig->parameter_count(); ++i) {
    switch (sig->GetParam(i).kind()) {
      case kI32:
        packer.Push(
            base::ReadUnalignedValue<int32_t>(reinterpret_cast<Address>(p)));
        p += sizeof(int32_t) / kSlotSize;
        break;
      case kI64:
        packer.Push(
            base::ReadUnalignedValue<int64_t>(reinterpret_cast<Address>(p)));
        p += sizeof(int64_t) / kSlotSize;
        break;
      case kF32:
        packer.Push(
            base::ReadUnalignedValue<float>(reinterpret_cast<Address>(p)));
        p += sizeof(float) / kSlotSize;
        break;
      case kF64:
        packer.Push(
            base::ReadUnalignedValue<double>(reinterpret_cast<Address>(p)));
        p += sizeof(double) / kSlotSize;
        break;
      case kRef:
      case kRefNull: {
        DirectHandle<Object> ref =
            base::ReadUnalignedValue<WasmRef>(reinterpret_cast<Address>(p));
        ref = WasmToJSObject(ref);
        packer.Push(*ref);
        p += sizeof(WasmRef) / kSlotSize;
        break;
      }
      case kS128:
      default:
        UNREACHABLE();
    }
  }
  DCHECK_NOT_NULL(current_thread_);
  current_thread_->StopExecutionTimer();
  {
    // If there were Ref values passed as arguments they have already been read
    // in BeginExecution(), so we can re-enable GC.
    AllowHeapAllocation allow_gc;
    CallWasmToJSBuiltin(isolate_, object_ref, packer.argv(), sig);
  }
  current_thread_->StartExecutionTimer();
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (v8_flags.trace_drumbrake_execution) {
    Trace(" => External wasm function returned%s\n",
          isolate_->has_exception() ? " with exception" : "");
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  if (V8_UNLIKELY(isolate_->has_exception())) {
    return ExternalCallResult::EXTERNAL_EXCEPTION;
  }
  // Push return values.
  if (sig->return_count() > 0) {
    packer.Reset();
    for (size_t i = 0; i < sig->return_count(); i++) {
      switch (sig->GetReturn(i).kind()) {
        case kI32:
          base::WriteUnalignedValue<int32_t>(reinterpret_cast<Address>(sp),
                                             packer.Pop<uint32_t>());
          sp += sizeof(uint32_t) / kSlotSize;
          break;
        case kI64:
          base::WriteUnalignedValue<uint64_t>(reinterpret_cast<Address>(sp),
                                              packer.Pop<uint64_t>());
          sp += sizeof(uint64_t) / kSlotSize;
          break;
        case kF32:
          base::WriteUnalignedValue<float>(reinterpret_cast<Address>(sp),
                                           packer.Pop<float>());
          sp += sizeof(float) / kSlotSize;
          break;
        case kF64:
          base::WriteUnalignedValue<double>(reinterpret_cast<Address>(sp),
                                            packer.Pop<double>());
          sp += sizeof(double) / kSlotSize;
          break;
        case kRef:
        case kRefNull:
          // TODO(paolosev@microsoft.com): Handle WasmNull case?
#ifdef V8_COMPRESS_POINTERS
        {
          Address address = packer.Pop<Address>();
          DirectHandle<Object> ref(Tagged<Object>(address), isolate_);
          if (sig->GetReturn(i).value_type_code() == wasm::kFuncRefCode &&
              i::IsNull(*ref, isolate_)) {
            ref = isolate_->factory()->wasm_null();
          }
          ref = JSToWasmObject(ref, sig->GetReturn(i));
          if (isolate_->has_exception()) {
            return ExternalCallResult::EXTERNAL_EXCEPTION;
          }
          base::WriteUnalignedValue<DirectHandle<Object>>(
              reinterpret_cast<Address>(sp), ref);
          sp += sizeof(WasmRef) / kSlotSize;
        }
#else
          CHECK(false); // Not supported.
#endif // V8_COMPRESS_POINTERS
        break;
        case kS128:
        default:
          UNREACHABLE();
      }
    }
  }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (v8_flags.trace_drumbrake_execution && shadow_stack_ != nullptr) {
    for (size_t i = 0; i < sig->parameter_count(); i++) {
      TracePop();
    }
    for (size_t i = 0; i < sig->return_count(); i++) {
      return_slot_offset +=
          TracePush(sig->GetReturn(i).kind(), return_slot_offset);
    }
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  return ExternalCallResult::EXTERNAL_RETURNED;
}
References v8::internal::wasm::CWasmArgumentsPacker::argv(), CallWasmToJSBuiltin(), CHECK, current_thread_, DCHECK_NOT_NULL, v8::internal::wasm::EXTERNAL_EXCEPTION, v8::internal::wasm::EXTERNAL_RETURNED, v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::IsJSCompatibleSignature(), v8::internal::IsNull(), isolate_, JSToWasmObject(), v8::internal::kF32, v8::internal::kF64, v8::internal::wasm::kFuncRefCode, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::kSlotSize, v8::internal::wasm::CWasmArgumentsPacker::Pop(), v8::internal::wasm::CWasmArgumentsPacker::Push(), v8::internal::wasm::CWasmArgumentsPacker::Reset(), v8::internal::wasm::WasmBytecode::RetsSizeInSlots(), v8::internal::sig, v8::internal::wasm::WasmInterpreterThread::StartExecutionTimer(), v8::internal::wasm::WasmInterpreterThread::StopExecutionTimer(), v8::internal::Isolate::Throw(), v8::internal::wasm::CWasmArgumentsPacker::TotalSize(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, V8_UNLIKELY, and WasmToJSObject().
Referenced by CallImportedFunction(), ExecuteCallRef(), and ExecuteIndirectCall().
CallImportedFunction()
ExternalCallResult v8::internal::wasm::WasmInterpreterRuntime::CallImportedFunction (const uint8_t *& current_code, uint32_t function_index, uint32_t * sp, uint32_t current_stack_size, uint32_t ref_stack_fp_index, uint32_t current_slot_offset) [private]
Definition at line 2040 of file wasm-interpreter-runtime.cc.
                                  {
  DCHECK_GT(module_->num_imported_functions, function_index);
  HandleScope handle_scope(isolate_); // Avoid leaking handles.
  const FunctionSig* sig = module_->functions[function_index].sig;
  ImportedFunctionEntry entry(wasm_trusted_instance_data(), function_index);
  int target_function_index = entry.function_index_in_called_module();
  if (target_function_index >= 0) {
    // WasmToWasm call.
    DCHECK(IsWasmTrustedInstanceData(entry.implicit_arg()));
    DirectHandle<WasmInstanceObject> target_instance(
        Cast<WasmInstanceObject>(
            Cast<WasmTrustedInstanceData>(entry.implicit_arg())
                ->instance_object()),
        isolate_);
    // Make sure the WasmInterpreterObject and InterpreterHandle for this
    // instance exist.
    DirectHandle<Tuple2> interpreter_object =
        WasmTrustedInstanceData::GetOrCreateInterpreterObject(target_instance);
    GetOrCreateInterpreterHandle(isolate_, interpreter_object);
    Address frame_pointer = FindInterpreterEntryFramePointer(isolate_);
    {
      // We should not allocate anything in the heap and avoid GCs after we
      // store ref arguments into stack slots.
      DisallowHeapAllocation no_gc;
      uint8_t* fp = reinterpret_cast<uint8_t*>(sp);
      StoreRefArgsIntoStackSlots(fp, ref_stack_fp_offset, sig);
      // Note that tail calls across WebAssembly module boundaries should
      // guarantee tail behavior, so this implementation does not conform to the
      // spec for a tail call. But it is really difficult to implement
      // cross-instance calls in the interpreter without recursively adding C++
      // stack frames.
      // TODO(paolosev@microsoft.com) - Is it possible to short-circuit this in
      // the case where we are calling a function in the same Wasm instance,
      // with a simple call to WasmInterpreterRuntime::ExecuteFunction()?
      bool success = WasmInterpreterObject::RunInterpreter(
          isolate_, frame_pointer, target_instance, target_function_index, fp);
      if (success) {
        StoreRefResultsIntoRefStack(fp, ref_stack_fp_offset, sig);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
        // Update shadow stack
        if (v8_flags.trace_drumbrake_execution && shadow_stack_ != nullptr) {
          for (size_t i = 0; i < sig->parameter_count(); i++) {
            TracePop();
          }
          for (size_t i = 0; i < sig->return_count(); i++) {
            current_slot_offset +=
                TracePush(sig->GetReturn(i).kind(), current_slot_offset);
          }
        }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
        return ExternalCallResult::EXTERNAL_RETURNED;
      }
      return ExternalCallResult::EXTERNAL_EXCEPTION;
    }
  } else {
    // WasmToJS call.
    // Note that tail calls to host functions do not have to guarantee tail
    // behaviour, so it is ok to recursively allocate C++ stack frames here.
    DirectHandle<Object> object_implicit_arg(entry.implicit_arg(), isolate_);
    // We should not allocate anything in the heap and avoid GCs after we store
    // ref arguments into stack slots.
    DisallowHeapAllocation no_gc;
    uint8_t* fp = reinterpret_cast<uint8_t*>(sp);
    StoreRefArgsIntoStackSlots(fp, ref_stack_fp_offset, sig);
    ExternalCallResult result =
        CallExternalJSFunction(current_code, module_, object_implicit_arg, sig,
                               sp, current_slot_offset);
    if (result == ExternalCallResult::EXTERNAL_RETURNED) {
      StoreRefResultsIntoRefStack(fp, ref_stack_fp_offset, sig);
    }
    return result;
  }
}
References CallExternalJSFunction(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::wasm::EXTERNAL_EXCEPTION, v8::internal::wasm::EXTERNAL_RETURNED, v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc}::FindInterpreterEntryFramePointer(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::GetOrCreateInterpreterHandle(), v8::internal::ImportedFunctionEntry::implicit_arg(), isolate_, module_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::WasmModule::num_imported_functions, v8::base::internal::result, v8::internal::WasmInterpreterObject::RunInterpreter(), v8::internal::sig, StoreRefArgsIntoStackSlots(), StoreRefResultsIntoRefStack(), v8::internal::v8_flags, and wasm_trusted_instance_data().
Referenced by ExecuteImportedFunction().
CallWasmToJSBuiltin()
void v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin (Isolate * isolate, DirectHandle< Object > object_ref, Address packed_args, const FunctionSig * sig) [private]
Definition at line 2145 of file wasm-interpreter-runtime.cc.
                            {
  DCHECK(!WasmBytecode::ContainsSimd(sig));
  DirectHandle<Object> callable;
  if (IsWasmImportData(*object_ref)) {
    callable =
        direct_handle(Cast<WasmImportData>(*object_ref)->callable(), isolate);
  } else {
    callable = object_ref;
    DCHECK(!IsUndefined(*callable));
  }
  // TODO(paolosev@microsoft.com) - Can callable be a JSProxy?
  DirectHandle<Object> js_function = callable;
  while (IsJSBoundFunction(*js_function, isolate_)) {
    if (IsJSBoundFunction(*js_function, isolate_)) {
      js_function = direct_handle(
          Cast<JSBoundFunction>(js_function)->bound_target_function(), isolate);
    }
  }
  if (IsJSProxy(*js_function, isolate_)) {
    do {
      Tagged<HeapObject> target = Cast<JSProxy>(js_function)->target(isolate);
      js_function = DirectHandle<Object>(target, isolate);
    } while (IsJSProxy(*js_function, isolate_));
  }
  if (!IsJSFunction(*js_function, isolate_)) {
    AllowHeapAllocation allow_gc;
    trap_handler::ClearThreadInWasm();
    isolate->set_exception(*isolate_->factory()->NewTypeError(
        MessageTemplate::kWasmTrapJSTypeError));
    return;
  }
  // Save and restore context around invocation and block the
  // allocation of handles without explicit handle scopes.
  SaveContext save(isolate);
  SealHandleScope shs(isolate);
  Address saved_c_entry_fp = *isolate->c_entry_fp_address();
  Address saved_js_entry_sp = *isolate->js_entry_sp_address();
  if (saved_js_entry_sp == kNullAddress) {
    *isolate->js_entry_sp_address() = GetCurrentStackPosition();
  }
  StackHandlerMarker stack_handler;
  stack_handler.next = isolate->thread_local_top()->handler_;
#ifdef V8_USE_ADDRESS_SANITIZER
  stack_handler.padding = GetCurrentStackPosition();
#else
  stack_handler.padding = 0;
#endif
  // {saved_c_entry_fp} can be null if we run the interpreter directly from the
  // fuzzer, not from JS. In this case, we need to break the handler chain.
  isolate->thread_local_top()->handler_ =
      saved_c_entry_fp ? reinterpret_cast<Address>(&stack_handler)
                       : kNullAddress;
  if (trap_handler::IsThreadInWasm()) {
    trap_handler::ClearThreadInWasm();
  }
  {
    RCS_SCOPE(isolate, RuntimeCallCounterId::kJS_Execution);
    Address result = generic_wasm_to_js_interpreter_wrapper_fn_.Call(
        (*js_function).ptr(), packed_args, isolate->isolate_root(), sig,
        saved_c_entry_fp, (*callable).ptr());
    if (result != WasmToJSInterpreterFrameConstants::kSuccess) {
      isolate->set_exception(Tagged<Object>(result));
      if (trap_handler::IsThreadInWasm()) {
        trap_handler::ClearThreadInWasm();
      }
    } else {
      current_thread_->Run();
      if (!trap_handler::IsThreadInWasm()) {
        trap_handler::SetThreadInWasm();
      }
    }
  }
  isolate->thread_local_top()->handler_ = stack_handler.next;
  if (saved_js_entry_sp == kNullAddress) {
    *isolate->js_entry_sp_address() = saved_js_entry_sp;
  }
  *isolate->c_entry_fp_address() = saved_c_entry_fp;
}
References v8::internal::Isolate::c_entry_fp_address(), v8::internal::GeneratedCode< Return, Args >::Call(), v8::internal::trap_handler::ClearThreadInWasm(), v8::internal::wasm::WasmBytecode::ContainsSimd(), current_thread_, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), generic_wasm_to_js_interpreter_wrapper_fn_, v8::internal::GetCurrentStackPosition(), v8::internal::ThreadLocalTop::handler_, isolate_, v8::internal::Isolate::isolate_root(), v8::internal::trap_handler::IsThreadInWasm(), v8::internal::Isolate::js_entry_sp_address(), v8::internal::kNullAddress, v8::internal::detail::kSuccess, v8::internal::wasm::StackHandlerMarker::next, v8::internal::wasm::StackHandlerMarker::padding, RCS_SCOPE, v8::base::internal::result, v8::internal::wasm::WasmInterpreterThread::Run(), v8::internal::Isolate::set_exception(), v8::internal::trap_handler::SetThreadInWasm(), v8::internal::sig, and v8::internal::Isolate::thread_local_top().
Referenced by CallExternalJSFunction().
CheckIndirectCallSignature()
bool v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature (uint32_t table_index, uint32_t entry_index, uint32_t sig_index) const [private]
Definition at line 1743 of file wasm-interpreter-runtime.cc.
                                                                          {
  const WasmTable& table = module_->tables[table_index];
  bool needs_type_check =
      !EquivalentTypes(table.type.AsNonNull(),
                       ValueType::Ref(ModuleTypeIndex({sig_index}), false,
                                      RefTypeKind::kFunction),
                       module_, module_);
  bool needs_null_check = table.type.is_nullable();
  // Copied from Liftoff.
  // We do both the type check and the null check by checking the signature,
  // so this shares most code. For the null check we then only check if the
  // stored signature is != -1.
  if (needs_type_check || needs_null_check) {
    const IndirectCallTable& dispatch_table =
        indirect_call_tables_[table_index];
    const wasm::CanonicalTypeIndex real_sig_id =
        dispatch_table[entry_index].sig_index;
    wasm::CanonicalTypeIndex canonical_sig_id =
        module_->canonical_sig_id(ModuleTypeIndex({sig_index}));
    if (!needs_type_check) {
      // Only check for -1 (nulled table entry).
      if (!real_sig_id.valid()) return false;
    } else if (!module_->types[sig_index].is_final) {
      if (real_sig_id == canonical_sig_id) return true;
      if (needs_null_check && !real_sig_id.valid()) return false;
      Tagged<Map> rtt = Tagged<Map>::cast(isolate_->heap()
                                              ->wasm_canonical_rtts()
                                              ->get(real_sig_id.index)
                                              .GetHeapObjectAssumeWeak());
      DirectHandle<Map> formal_rtt = RttCanon(sig_index);
      return SubtypeCheck(rtt, *formal_rtt, sig_index);
    } else {
      if (real_sig_id != canonical_sig_id) return false;
    }
  }
  return true;
}
References v8::internal::wasm::ValueType::AsNonNull(), v8::internal::wasm::WasmModule::canonical_sig_id(), v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::cast(), v8::internal::wasm::EquivalentTypes(), v8::internal::Isolate::heap(), v8::internal::wasm::TypeIndex::index, indirect_call_tables_, v8::internal::wasm::ValueTypeBase::is_nullable(), isolate_, v8::internal::wasm::kFunction, module_, v8::internal::wasm::ValueType::Ref(), RttCanon(), SubtypeCheck(), v8::internal::wasm::WasmModule::tables, v8::internal::wasm::WasmTable::type, v8::internal::wasm::WasmModule::types, and v8::internal::wasm::TypeIndex::valid().
Referenced by ExecuteIndirectCall().
ClearIndirectCallCacheEntry()
void v8::internal::wasm::WasmInterpreterRuntime::ClearIndirectCallCacheEntry (Isolate * isolate, DirectHandle< WasmInstanceObject > instance, uint32_t table_index, uint32_t entry_index) [static]
Definition at line 1715 of file wasm-interpreter-runtime.cc.
                                                {
  DirectHandle<Tuple2> interpreter_object =
      WasmTrustedInstanceData::GetOrCreateInterpreterObject(instance);
  InterpreterHandle* handle =
      GetOrCreateInterpreterHandle(isolate, interpreter_object);
  WasmInterpreterRuntime* wasm_runtime =
      handle->interpreter()->GetWasmRuntime();
  DCHECK_LT(table_index, wasm_runtime->indirect_call_tables_.size());
  DCHECK_LT(entry_index,
            wasm_runtime->indirect_call_tables_[table_index].size());
  wasm_runtime->indirect_call_tables_[table_index][entry_index] = {};
}
References DCHECK_LT, v8::internal::wasm::GetOrCreateInterpreterHandle(), and v8::internal::handle().
Referenced by v8::internal::WasmTableObject::ClearDispatchTable().
ContinueExecution()
void v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution (WasmInterpreterThread * thread, bool called_from_js)
Definition at line 1055 of file wasm-interpreter-runtime.cc.
                                                                    {
  DCHECK_NE(start_function_index_, UINT_MAX);
  uint32_t start_function_index = start_function_index_;
  FrameState current_frame = current_frame_;
  const uint8_t* code = nullptr;
  const FunctionSig* sig = nullptr;
  const CanonicalSig* canonicalized_sig = nullptr;
  uint32_t return_count = 0;
  WasmBytecode* target_function = GetFunctionBytecode(start_function_index_);
  if (target_function) {
    sig = target_function->GetFunctionSignature();
    canonicalized_sig = target_function->GetCanonicalFunctionSignature();
    return_count = target_function->return_count();
    ExecuteFunction(code, start_function_index_, target_function->args_count(),
                    0, 0, 0);
  } else {
    sig = module_->functions[start_function_index_].sig;
    CanonicalTypeIndex canonical_sig_index = module_->canonical_sig_id(
        module_->functions[start_function_index_].sig_index);
    canonicalized_sig =
        GetTypeCanonicalizer()->LookupFunctionSignature(canonical_sig_index);
    return_count = static_cast<uint32_t>(sig->return_count());
    ExecuteImportedFunction(code, start_function_index_,
                            static_cast<uint32_t>(sig->parameter_count()), 0, 0,
                            0);
  }
  // If there are Ref types in the set of result types defined in the function
  // signature, they are located from the first ref_stack_ slot of the current
  // Activation.
  uint32_t ref_result_slot_index = 0;
  if (state() == WasmInterpreterThread::State::RUNNING) {
    if (return_count > 0) {
      uint32_t* dst = reinterpret_cast<uint32_t*>(current_frame_.current_sp_);
      if (called_from_js) {
        // We are returning the results to a JS caller, we need to store them
        // into the {function_result_} vector and they will be retrieved via
        // {GetReturnValue}.
        function_result_.resize(return_count);
        for (size_t index = 0; index < return_count; index++) {
          CanonicalValueType ret_value_type =
              canonicalized_sig->GetReturn(index);
          switch (ret_value_type.kind()) {
            case kI32:
              function_result_[index] =
                  WasmValue(base::ReadUnalignedValue<int32_t>(
                      reinterpret_cast<Address>(dst)));
              dst += sizeof(uint32_t) / kSlotSize;
              break;
            case kI64:
              function_result_[index] =
                  WasmValue(base::ReadUnalignedValue<int64_t>(
                      reinterpret_cast<Address>(dst)));
              dst += sizeof(uint64_t) / kSlotSize;
              break;
            case kF32:
              function_result_[index] =
                  WasmValue(base::ReadUnalignedValue<float>(
                      reinterpret_cast<Address>(dst)));
              dst += sizeof(float) / kSlotSize;
              break;
            case kF64:
              function_result_[index] =
                  WasmValue(base::ReadUnalignedValue<double>(
                      reinterpret_cast<Address>(dst)));
              dst += sizeof(double) / kSlotSize;
              break;
            case kRef:
            case kRefNull: {
              DirectHandle<Object> ref =
                  ExtractWasmRef(ref_result_slot_index++);
              ref = WasmToJSObject(ref);
              function_result_[index] = WasmValue(ref, ret_value_type);
              dst += sizeof(WasmRef) / kSlotSize;
              break;
            }
            case kS128:
            default:
              UNREACHABLE();
          }
        }
      } else {
        // We are returning the results on the stack
        for (size_t index = 0; index < return_count; index++) {
          switch (sig->GetReturn(index).kind()) {
            case kI32:
              dst += sizeof(uint32_t) / kSlotSize;
              break;
            case kI64:
              dst += sizeof(uint64_t) / kSlotSize;
              break;
            case kF32:
              dst += sizeof(float) / kSlotSize;
              break;
            case kF64:
              dst += sizeof(double) / kSlotSize;
              break;
            case kS128:
              dst += sizeof(Simd128) / kSlotSize;
              break;
            case kRef:
            case kRefNull: {
              // Make sure the ref result is termporarily stored in a stack
              // slot, to be retrieved by the caller.
              DirectHandle<Object> ref =
                  ExtractWasmRef(ref_result_slot_index++);
              base::WriteUnalignedValue<WasmRef>(reinterpret_cast<Address>(dst),
                                                 ref);
              dst += sizeof(WasmRef) / kSlotSize;
              break;
            }
            default:
              UNREACHABLE();
          }
        }
      }
    }
    if (ref_result_slot_index > 0) {
      current_thread_->ClearRefStackValues(current_frame_.ref_array_current_sp_,
                                           ref_result_slot_index);
    }
    DCHECK(current_frame_.caught_exceptions_.is_null());
    start_function_index_ = start_function_index;
    current_frame_ = current_frame;
  } else if (state() == WasmInterpreterThread::State::TRAPPED) {
    MessageTemplate message_id =
        WasmOpcodes::TrapReasonToMessageId(thread->GetTrapReason());
    thread->RaiseException(isolate_, message_id);
  } else if (state() == WasmInterpreterThread::State::EH_UNWINDING) {
    // Uncaught exception.
    thread->Stop();
  } else {
    DCHECK_EQ(state(), WasmInterpreterThread::State::STOPPED);
  }
  thread->FinishActivation();
  const FrameState* frame_state = thread->GetCurrentActivationFor(this);
  current_frame_ = frame_state ? *frame_state : FrameState();
}
References v8::internal::wasm::WasmBytecode::args_count(), v8::internal::wasm::WasmModule::canonical_sig_id(), v8::internal::wasm::WasmInterpreterThread::ClearRefStackValues(), code, current_frame_, current_thread_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, ExecuteFunction(), ExecuteImportedFunction(), ExtractWasmRef(), v8::internal::wasm::WasmInterpreterThread::FinishActivation(), function_result_, v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WasmBytecode::GetCanonicalFunctionSignature(), v8::internal::wasm::WasmInterpreterThread::GetCurrentActivationFor(), GetFunctionBytecode(), v8::internal::wasm::WasmBytecode::GetFunctionSignature(), v8::internal::Signature< T >::GetReturn(), v8::internal::wasm::WasmInterpreterThread::GetTrapReason(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::index, isolate_, v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::kSlotSize, v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), module_, v8::internal::wasm::WasmInterpreterThread::RaiseException(), v8::internal::wasm::WasmBytecode::return_count(), v8::internal::sig, start_function_index_, state(), v8::internal::wasm::WasmInterpreterThread::Stop(), thread(), v8::internal::wasm::WasmOpcodes::TrapReasonToMessageId(), v8::internal::UNREACHABLE(), and WasmToJSObject().
CreateWasmExceptionPackage()
DirectHandle< WasmExceptionPackage > v8::internal::wasm::WasmInterpreterRuntime::CreateWasmExceptionPackage (uint32_t tag_index) const
Definition at line 668 of file wasm-interpreter-runtime.cc.
                                                                           {
  DirectHandle<WasmTrustedInstanceData> trusted_data =
      wasm_trusted_instance_data();
  DirectHandle<WasmExceptionTag> exception_tag(
      Cast<WasmExceptionTag>(trusted_data->tags_table()->get(tag_index)),
      isolate_);
  const WasmTag& tag = GetWasmTag(tag_index);
  uint32_t encoded_size = WasmExceptionPackage::GetEncodedSize(&tag);
  DirectHandle<WasmExceptionPackage> exception_object =
      WasmExceptionPackage::New(isolate_, exception_tag, encoded_size);
  return exception_object;
}
References v8::internal::WasmExceptionPackage::GetEncodedSize(), GetWasmTag(), isolate_, v8::internal::WasmExceptionPackage::New(), and wasm_trusted_instance_data().
DataDrop()
void v8::internal::wasm::WasmInterpreterRuntime::DataDrop (uint32_t index) [inline]
Definition at line 94 of file wasm-interpreter-runtime-inl.h.
                                                           {
  wasm_trusted_instance_data()->data_segment_sizes()->set(index, 0);
}
References v8::internal::index, and wasm_trusted_instance_data().
EffectiveAddress()
Address v8::internal::wasm::WasmInterpreterRuntime::EffectiveAddress (uint64_t index) const [inline], [private]
Definition at line 24 of file wasm-interpreter-runtime-inl.h.
                                                                            {
  DirectHandle<WasmTrustedInstanceData> trusted_data =
      wasm_trusted_instance_data();
  DCHECK_GE(std::numeric_limits<uintptr_t>::max(),
            trusted_data->memory0_size());
  DCHECK_GE(trusted_data->memory0_size(), index);
  // Compute the effective address of the access, making sure to condition
  // the index even in the in-bounds case.
  return reinterpret_cast<Address>(trusted_data->memory0_start()) + index;
}
References DCHECK_GE, v8::internal::index, and wasm_trusted_instance_data().
Referenced by BoundsCheckMemRange().
ElemDrop()
void v8::internal::wasm::WasmInterpreterRuntime::ElemDrop (uint32_t index) [inline]
Definition at line 98 of file wasm-interpreter-runtime-inl.h.
                                                           {
  wasm_trusted_instance_data()->element_segments()->set(
      index, *isolate_->factory()->empty_fixed_array());
}
References v8::internal::Isolate::factory(), v8::internal::index, isolate_, and wasm_trusted_instance_data().
ExecuteCallRef()
void v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef (const uint8_t *& current_code, WasmRef func_ref, uint32_t sig_index, uint32_t stack_pos, uint32_t * sp, uint32_t ref_stack_fp_offset, uint32_t slot_offset, uint32_t return_slot_offset, bool is_tail_call)
Definition at line 1972 of file wasm-interpreter-runtime.cc.
                                                                          {
  if (IsWasmFuncRef(*func_ref)) {
    func_ref = direct_handle(Cast<WasmFuncRef>(*func_ref)->internal(isolate_),
                             isolate_);
  }
  if (IsWasmInternalFunction(*func_ref)) {
    Tagged<WasmInternalFunction> wasm_internal_function =
        Cast<WasmInternalFunction>(*func_ref);
    Tagged<Object> implicit_arg = wasm_internal_function->implicit_arg();
    if (IsWasmImportData(implicit_arg)) {
      func_ref = direct_handle(implicit_arg, isolate_);
    } else {
      DCHECK(IsWasmTrustedInstanceData(implicit_arg));
      func_ref = WasmInternalFunction::GetOrCreateExternal(
          direct_handle(wasm_internal_function, isolate_));
      DCHECK(IsJSFunction(*func_ref) || IsUndefined(*func_ref));
    }
  }
  const FunctionSig* signature = module_->signature({sig_index});
  // ExternalCall
  HandleScope handle_scope(isolate_); // Avoid leaking handles.
  // Store a pointer to the current FrameState before leaving the current
  // Activation.
  WasmInterpreterThread* thread = this->thread();
  current_frame_.current_bytecode_ = current_code;
  thread->SetCurrentFrame(current_frame_);
  thread->SetCurrentActivationFrame(
      sp, slot_offset, stack_pos,
      current_frame_.ref_array_current_sp_ + ref_stack_fp_offset,
      ref_stack_fp_offset);
  // We should not allocate anything in the heap and avoid GCs after we
  // store ref arguments into stack slots.
  DisallowHeapAllocation no_gc;
  // Note that tail calls to host functions do not have to guarantee tail
  // behaviour, so it is ok to recursively allocate C++ stack frames here.
  uint8_t* fp = reinterpret_cast<uint8_t*>(sp) + slot_offset;
  StoreRefArgsIntoStackSlots(fp, ref_stack_fp_offset, signature);
  ExternalCallResult result =
      CallExternalJSFunction(current_code, module_, func_ref, signature,
                             sp + slot_offset / kSlotSize, return_slot_offset);
  if (result == ExternalCallResult::EXTERNAL_RETURNED) {
    StoreRefResultsIntoRefStack(fp, ref_stack_fp_offset, signature);
  } else { // ExternalCallResult::EXTERNAL_EXCEPTION
    AllowHeapAllocation allow_gc;
    if (HandleException(sp, current_code) ==
        WasmInterpreterThread::ExceptionHandlingResult::UNWOUND) {
      DCHECK(!trap_handler::IsThreadInWasm());
      thread->Stop();
      RedirectCodeToUnwindHandler(current_code);
    } else {
      thread->Run();
    }
  }
  if (is_tail_call) {
    RedirectCodeToUnwindHandler(current_code);
  }
}
References CallExternalJSFunction(), current_frame_, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::wasm::EXTERNAL_RETURNED, v8::internal::WasmInternalFunction::GetOrCreateExternal(), HandleException(), isolate_, v8::internal::trap_handler::IsThreadInWasm(), v8::internal::wasm::kSlotSize, module_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler(), v8::base::internal::result, v8::internal::wasm::WasmInterpreterThread::Run(), v8::internal::wasm::WasmInterpreterThread::SetCurrentActivationFrame(), v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), v8::internal::wasm::WasmModule::signature(), v8::internal::wasm::WasmInterpreterThread::Stop(), StoreRefArgsIntoStackSlots(), StoreRefResultsIntoRefStack(), and thread().
ExecuteFunction()
void v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction (const uint8_t *& code, uint32_t function_index, uint32_t current_stack_size, uint32_t ref_stack_fp_offset, uint32_t slot_offset, uint32_t return_slot_offset)
Definition at line 1521 of file wasm-interpreter-runtime.cc.
                                                                          {
  // Execute an internal call.
  WasmBytecode* target_function = GetFunctionBytecode(func_index);
  DCHECK_NOT_NULL(target_function);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  ShadowStack* prev_shadow_stack = shadow_stack_;
  ShadowStack shadow_stack;
  if (v8_flags.trace_drumbrake_execution) {
    shadow_stack_ = &shadow_stack;
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  // This HandleScope is used for all handles created in instruction handlers.
  // We reset it every time we get to a backward jump in a loop.
  HandleScope handle_scope(GetIsolate());
  // Update the current (caller) frame setting current_bytecode_ to the current
  // call instruction.
  current_frame_.current_bytecode_ = code;
  FrameState prev_frame_state = current_frame_;
  current_frame_.current_sp_ += slot_offset;
  current_frame_.handle_scope_ = &handle_scope;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  current_frame_.current_stack_start_args_ +=
      (current_stack_size - target_function->args_count());
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  current_frame_.current_function_ = target_function;
  current_frame_.previous_frame_ = &prev_frame_state;
  current_frame_.caught_exceptions_ = Handle<FixedArray>::null();
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  current_frame_.current_stack_height_++;
  current_frame_.current_stack_start_locals_ =
      current_frame_.current_stack_start_args_ + target_function->args_count();
  current_frame_.current_stack_start_stack_ =
      current_frame_.current_stack_start_locals_ +
      target_function->locals_count();
  if (v8_flags.trace_drumbrake_execution) {
    Trace("\nCallFunction: %d\n", func_index);
    Trace("= > PushFrame #%d(#%d @%d)\n", current_frame_.current_stack_height_,
          func_index, 0);
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  if (!WasmStackCheck(target_function->GetCode(), code)) {
    return;
  }
  const uint8_t* stack_limit = current_frame_.thread_->StackLimitAddress();
  if (V8_UNLIKELY(stack_limit <= current_frame_.current_sp_ ||
                  !target_function->InitializeSlots(
                      current_frame_.current_sp_,
                      stack_limit - current_frame_.current_sp_))) {
    // Try to resize the stack.
    size_t additional_required_space =
        target_function->frame_size() -
        (stack_limit - current_frame_.current_sp_);
    // Try again.
    if (!current_frame_.thread_->ExpandStack(additional_required_space) ||
        !target_function->InitializeSlots(
            current_frame_.current_sp_,
            (stack_limit = current_frame_.thread_->StackLimitAddress()) -
                current_frame_.current_sp_)) {
      ClearThreadInWasmScope clear_wasm_flag(isolate_);
      SealHandleScope shs(isolate_);
      SetTrap(TrapReason::kTrapUnreachable, code);
      isolate_->StackOverflow();
      return;
    }
  }
  uint32_t ref_slots_count = target_function->ref_slots_count();
  current_frame_.ref_array_current_sp_ += ref_stack_fp_offset;
  if (V8_UNLIKELY(ref_slots_count > 0)) {
    uint32_t ref_array_length =
        current_frame_.ref_array_current_sp_ + ref_slots_count;
    current_thread_->EnsureRefStackSpace(ref_array_length);
    InitializeRefLocalsRefs(target_function);
  }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  uint32_t shadow_stack_offset = 0;
  if (v8_flags.trace_drumbrake_execution) {
    shadow_stack_offset = target_function->rets_slots_size() * kSlotSize;
    for (uint32_t i = 0; i < target_function->args_count(); i++) {
      shadow_stack_offset +=
          TracePush(target_function->arg_type(i).kind(), shadow_stack_offset);
    }
    // Make room for locals in shadow stack
    shadow_stack_offset += target_function->const_slots_size_in_bytes();
    for (size_t i = 0; i < target_function->locals_count(); i++) {
      shadow_stack_offset +=
          TracePush(target_function->local_type(i).kind(), shadow_stack_offset);
    }
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  const uint8_t* callee_code = target_function->GetCode();
  int64_t r0 = 0;
  double fp0 = .0;
  // Execute function
  CallThroughDispatchTable(
      callee_code, reinterpret_cast<uint32_t*>(current_frame_.current_sp_),
      this, r0, fp0);
  uint32_t ref_slots_to_clear =
      ref_slots_count - target_function->ref_rets_count();
  if (V8_UNLIKELY(ref_slots_to_clear > 0)) {
    current_thread_->ClearRefStackValues(current_frame_.ref_array_current_sp_ +
                                             target_function->ref_rets_count(),
                                         ref_slots_to_clear);
  }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  shadow_stack_ = prev_shadow_stack;
  if (v8_flags.trace_drumbrake_execution && shadow_stack_ != nullptr &&
      prev_frame_state.current_function_) {
    for (size_t i = 0; i < target_function->args_count(); i++) {
      TracePop();
    }
    for (size_t i = 0; i < target_function->return_count(); i++) {
      return_slot_offset +=
          TracePush(target_function->return_type(i).kind(), return_slot_offset);
    }
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  current_frame_.handle_scope_ = nullptr;
  current_frame_.DisposeCaughtExceptionsArray(isolate_);
  current_frame_ = prev_frame_state;
  // Check state.
  WasmInterpreterThread::State current_state = state();
  if (V8_UNLIKELY(current_state != WasmInterpreterThread::State::RUNNING)) {
    switch (current_state) {
      case WasmInterpreterThread::State::EH_UNWINDING:
        DCHECK(isolate_->has_exception());
        if (!current_frame_.current_function_) {
          // We unwound the whole call stack without finding a catch handler.
          current_frame_.thread_->Stop();
          RedirectCodeToUnwindHandler(code);
        } else if (HandleException(
                       reinterpret_cast<uint32_t*>(current_frame_.current_sp_),
                       code) == WasmInterpreterThread::HANDLED) {
          current_frame_.thread_->Run();
        } else {
          // UNWOUND
          DCHECK(!trap_handler::IsThreadInWasm());
          RedirectCodeToUnwindHandler(code);
        }
        break;
      case WasmInterpreterThread::State::TRAPPED:
      case WasmInterpreterThread::State::STOPPED:
        RedirectCodeToUnwindHandler(code);
        break;
      default:
        UNREACHABLE();
    }
  }
  // TODO(paolosev@microsoft.com): StackCheck.
}
References v8::internal::wasm::WasmBytecode::arg_type(), v8::internal::wasm::WasmBytecode::args_count(), v8::internal::wasm::CallThroughDispatchTable(), v8::internal::wasm::WasmInterpreterThread::ClearRefStackValues(), code, v8::internal::wasm::WasmBytecode::const_slots_size_in_bytes(), current_frame_, current_thread_, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), v8::internal::wasm::WasmBytecode::frame_size(), v8::internal::wasm::WasmBytecode::GetCode(), GetFunctionBytecode(), GetIsolate(), v8::internal::wasm::WasmInterpreterThread::HANDLED, HandleException(), v8::internal::Isolate::has_exception(), InitializeRefLocalsRefs(), v8::internal::wasm::WasmBytecode::InitializeSlots(), isolate_, v8::internal::trap_handler::IsThreadInWasm(), v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kSlotSize, v8::internal::wasm::WasmBytecode::local_type(), v8::internal::wasm::WasmBytecode::locals_count(), v8::internal::Handle< T >::null(), v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler(), v8::internal::wasm::WasmBytecode::ref_rets_count(), v8::internal::wasm::WasmBytecode::ref_slots_count(), v8::internal::wasm::WasmBytecode::rets_slots_size(), v8::internal::wasm::WasmBytecode::return_count(), v8::internal::wasm::WasmBytecode::return_type(), SetTrap(), v8::internal::Isolate::StackOverflow(), state(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, V8_UNLIKELY, and WasmStackCheck().
Referenced by ContinueExecution(), and ExecuteIndirectCall().
ExecuteImportedFunction()
void v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction (const uint8_t *& code, uint32_t func_index, uint32_t current_stack_size, uint32_t ref_stack_fp_offset, uint32_t slot_offset, uint32_t return_slot_offset, bool is_tail_call = false)
Definition at line 1359 of file wasm-interpreter-runtime.cc.
                                                    {
  WasmInterpreterThread* thread = this->thread();
  DCHECK_NOT_NULL(thread);
  // Store a pointer to the current FrameState before leaving the current
  // Activation.
  current_frame_.current_bytecode_ = code;
  thread->SetCurrentFrame(current_frame_);
  thread->SetCurrentActivationFrame(
      reinterpret_cast<uint32_t*>(current_frame_.current_sp_ + slot_offset),
      slot_offset, current_stack_size,
      current_frame_.ref_array_current_sp_ + ref_stack_fp_offset,
      ref_stack_fp_offset);
  ExternalCallResult result = CallImportedFunction(
      code, func_index,
      reinterpret_cast<uint32_t*>(current_frame_.current_sp_ + slot_offset),
      current_stack_size, ref_stack_fp_offset, slot_offset);
  if (result == ExternalCallResult::EXTERNAL_EXCEPTION) {
    WasmInterpreterThread::ExceptionHandlingResult exception_handling_result =
        HandleException(reinterpret_cast<uint32_t*>(current_frame_.current_sp_),
                        code);
    if (exception_handling_result ==
        WasmInterpreterThread::ExceptionHandlingResult::HANDLED) {
      // The exception was caught by Wasm EH. Resume execution,
      // {HandleException} has already updated {code} to point to the first
      // instruction in the catch handler.
      thread->Run();
    } else {
      DCHECK(!trap_handler::IsThreadInWasm());
      DCHECK_EQ(exception_handling_result,
                WasmInterpreterThread::ExceptionHandlingResult::UNWOUND);
      if (thread->state() != WasmInterpreterThread::State::EH_UNWINDING) {
        thread->Stop();
      }
      // Resume execution from s2s_Unwind, which unwinds the Wasm stack frames.
      RedirectCodeToUnwindHandler(code);
    }
  }
  if (is_tail_call) {
    RedirectCodeToUnwindHandler(code);
  }
}
References CallImportedFunction(), code, current_frame_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::wasm::EXTERNAL_EXCEPTION, HandleException(), v8::internal::trap_handler::IsThreadInWasm(), v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler(), v8::base::internal::result, v8::internal::wasm::WasmInterpreterThread::Run(), v8::internal::wasm::WasmInterpreterThread::SetCurrentActivationFrame(), v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), v8::internal::wasm::WasmInterpreterThread::state(), v8::internal::wasm::WasmInterpreterThread::Stop(), and thread().
Referenced by ContinueExecution().
ExecuteIndirectCall()
void v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall (const uint8_t *& current_code, uint32_t table_index, uint32_t sig_index, uint32_t entry_index, uint32_t stack_pos, uint32_t * sp, uint32_t ref_stack_fp_offset, uint32_t slot_offset, uint32_t return_slot_offset, bool is_tail_call)
Definition at line 1785 of file wasm-interpreter-runtime.cc.
                                                    {
  DCHECK_LT(table_index, indirect_call_tables_.size());
  IndirectCallTable& table = indirect_call_tables_[table_index];
  // Bounds check against table size.
  DCHECK_GE(
      table.size(),
      Tagged<WasmDispatchTable>::cast(
          wasm_trusted_instance_data()->dispatch_tables()->get(table_index))
          ->length());
  if (entry_index >= table.size()) {
    SetTrap(TrapReason::kTrapTableOutOfBounds, current_code);
    return;
  }
  if (!table[entry_index]) {
    HandleScope handle_scope(isolate_); // Avoid leaking handles.
    IndirectFunctionTableEntry entry(instance_object_, table_index,
                                     entry_index);
    const FunctionSig* signature = module_->signature({sig_index});
    DirectHandle<Object> object_implicit_arg(entry.implicit_arg(), isolate_);
    if (IsWasmTrustedInstanceData(*object_implicit_arg)) {
      Tagged<WasmTrustedInstanceData> trusted_instance_object =
          Cast<WasmTrustedInstanceData>(*object_implicit_arg);
      DirectHandle<WasmInstanceObject> instance_object(
          Cast<WasmInstanceObject>(trusted_instance_object->instance_object()),
          isolate_);
      if (instance_object_.is_identical_to(instance_object)) {
        // Call to an import.
        uint32_t func_index = entry.function_index();
        DCHECK(func_index != IndirectCallValue::kInvalidFunctionIndex);
        table[entry_index] = IndirectCallValue(func_index, entry.sig_id());
      } else {
        // Cross-instance call.
        table[entry_index] = IndirectCallValue(signature, entry.sig_id());
      }
    } else {
      // Call JS function.
      table[entry_index] = IndirectCallValue(signature, entry.sig_id());
    }
  }
  if (!CheckIndirectCallSignature(table_index, entry_index, sig_index)) {
    SetTrap(TrapReason::kTrapFuncSigMismatch, current_code);
    return;
  }
  IndirectCallValue indirect_call = table[entry_index];
  DCHECK(indirect_call);
  if (indirect_call.mode == IndirectCallValue::Mode::kInternalCall) {
    if (is_tail_call) {
      PrepareTailCall(current_code, indirect_call.func_index, stack_pos,
                      return_slot_offset);
    } else {
      ExecuteFunction(current_code, indirect_call.func_index, stack_pos,
                      ref_stack_fp_offset, slot_offset, return_slot_offset);
      if (state() == WasmInterpreterThread::State::TRAPPED ||
          state() == WasmInterpreterThread::State::STOPPED ||
          state() == WasmInterpreterThread::State::EH_UNWINDING) {
        RedirectCodeToUnwindHandler(current_code);
      }
    }
  } else {
    // ExternalCall
    HandleScope handle_scope(isolate_); // Avoid leaking handles.
    DCHECK_NOT_NULL(indirect_call.signature);
    // Store a pointer to the current FrameState before leaving the current
    // Activation.
    WasmInterpreterThread* thread = this->thread();
    current_frame_.current_bytecode_ = current_code;
    thread->SetCurrentFrame(current_frame_);
    thread->SetCurrentActivationFrame(
        sp, slot_offset, stack_pos,
        current_frame_.ref_array_current_sp_ + ref_stack_fp_offset,
        ref_stack_fp_offset);
    // TODO(paolosev@microsoft.com): Optimize this code.
    IndirectFunctionTableEntry entry(instance_object_, table_index,
                                     entry_index);
    DirectHandle<Object> object_implicit_arg(entry.implicit_arg(), isolate_);
    if (IsWasmTrustedInstanceData(*object_implicit_arg)) {
      // Call Wasm function in a different instance.
      // Note that tail calls across WebAssembly module boundaries should
      // guarantee tail behavior, so this implementation does not conform to the
      // spec for a tail call. But it is really difficult to implement
      // cross-instance calls in the interpreter without recursively adding C++
      // stack frames.
      DirectHandle<WasmInstanceObject> target_instance(
          Cast<WasmInstanceObject>(
              Cast<WasmTrustedInstanceData>(*object_implicit_arg)
                  ->instance_object()),
          isolate_);
      // Make sure the target WasmInterpreterObject and InterpreterHandle exist.
      DirectHandle<Tuple2> interpreter_object =
          WasmTrustedInstanceData::GetOrCreateInterpreterObject(
              target_instance);
      GetOrCreateInterpreterHandle(isolate_, interpreter_object);
      Address frame_pointer = FindInterpreterEntryFramePointer(isolate_);
      {
        // We should not allocate anything in the heap and avoid GCs after we
        // store ref arguments into stack slots.
        DisallowHeapAllocation no_gc;
        uint8_t* fp = reinterpret_cast<uint8_t*>(sp) + slot_offset;
        StoreRefArgsIntoStackSlots(fp, ref_stack_fp_offset,
                                   indirect_call.signature);
        bool success = WasmInterpreterObject::RunInterpreter(
            isolate_, frame_pointer, target_instance, entry.function_index(),
            fp);
        if (success) {
          StoreRefResultsIntoRefStack(fp, ref_stack_fp_offset,
                                      indirect_call.signature);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
          // Update shadow stack
          if (v8_flags.trace_drumbrake_execution && shadow_stack_ != nullptr) {
            for (size_t i = 0; i < indirect_call.signature->parameter_count();
                 i++) {
              TracePop();
            }
            for (size_t i = 0; i < indirect_call.signature->return_count();
                 i++) {
              return_slot_offset +=
                  TracePush(indirect_call.signature->GetReturn(i).kind(),
                            return_slot_offset);
            }
          }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
        } else {
          thread->Stop();
          RedirectCodeToUnwindHandler(current_code);
        }
      }
    } else {
      // We should not allocate anything in the heap and avoid GCs after we
      // store ref arguments into stack slots.
      DisallowHeapAllocation no_gc;
      // Note that tail calls to host functions do not have to guarantee tail
      // behaviour, so it is ok to recursively allocate C++ stack frames here.
      uint8_t* fp = reinterpret_cast<uint8_t*>(sp) + slot_offset;
      StoreRefArgsIntoStackSlots(fp, ref_stack_fp_offset,
                                 indirect_call.signature);
      ExternalCallResult result = CallExternalJSFunction(
          current_code, module_, object_implicit_arg, indirect_call.signature,
          sp + slot_offset / kSlotSize, slot_offset);
      if (result == ExternalCallResult::EXTERNAL_RETURNED) {
        StoreRefResultsIntoRefStack(fp, ref_stack_fp_offset,
                                    indirect_call.signature);
      } else { // ExternalCallResult::EXTERNAL_EXCEPTION
        AllowHeapAllocation allow_gc;
        if (HandleException(sp, current_code) ==
            WasmInterpreterThread::ExceptionHandlingResult::UNWOUND) {
          DCHECK(!trap_handler::IsThreadInWasm());
          thread->Stop();
          RedirectCodeToUnwindHandler(current_code);
        } else {
          thread->Run();
        }
      }
    }
    if (is_tail_call) {
      // For tail calls to external functions, we need to unwind the callee
      // frame.
      RedirectCodeToUnwindHandler(current_code);
    }
  }
}
References CallExternalJSFunction(), CheckIndirectCallSignature(), current_frame_, v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, DCHECK_NOT_NULL, ExecuteFunction(), v8::internal::wasm::EXTERNAL_RETURNED, v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc}::FindInterpreterEntryFramePointer(), v8::internal::wasm::WasmInterpreterRuntime::IndirectCallValue::func_index, v8::internal::wasm::IndirectFunctionTableEntry::function_index(), v8::internal::wasm::GetOrCreateInterpreterHandle(), v8::internal::Signature< T >::GetReturn(), HandleException(), v8::internal::wasm::IndirectFunctionTableEntry::implicit_arg(), indirect_call_tables_, v8::internal::instance_object, instance_object_, isolate_, v8::internal::trap_handler::IsThreadInWasm(), v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::WasmInterpreterRuntime::IndirectCallValue::kInternalCall, v8::internal::wasm::WasmInterpreterRuntime::IndirectCallValue::kInvalidFunctionIndex, v8::internal::wasm::kSlotSize, v8::internal::length, v8::internal::wasm::WasmInterpreterRuntime::IndirectCallValue::mode, module_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Signature< T >::parameter_count(), PrepareTailCall(), v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler(), v8::base::internal::result, v8::internal::Signature< T >::return_count(), v8::internal::wasm::WasmInterpreterThread::Run(), v8::internal::WasmInterpreterObject::RunInterpreter(), v8::internal::wasm::WasmInterpreterThread::SetCurrentActivationFrame(), v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), SetTrap(), v8::internal::wasm::IndirectFunctionTableEntry::sig_id(), v8::internal::wasm::WasmInterpreterRuntime::IndirectCallValue::signature, v8::internal::wasm::WasmModule::signature(), state(), v8::internal::wasm::WasmInterpreterThread::Stop(), StoreRefArgsIntoStackSlots(), StoreRefResultsIntoRefStack(), thread(), v8::internal::v8_flags, and wasm_trusted_instance_data().
ExtractWasmRef()
WasmRef v8::internal::wasm::WasmInterpreterRuntime::ExtractWasmRef (uint32_t ref_stack_index)
Definition at line 1213 of file wasm-interpreter-runtime.cc.
                                                                       {
  int index =
      static_cast<int>(ref_stack_index) + current_frame_.ref_array_current_sp_;
  DirectHandle<Object> ref(reference_stack()->get(index), isolate_);
  DCHECK(!IsTheHole(*ref, isolate_));
  return WasmRef(ref);
}
References current_frame_, v8::internal::DCHECK(), v8::internal::index, isolate_, and reference_stack().
Referenced by ContinueExecution(), StoreRefArgsIntoStackSlots(), and UnwindCurrentStackFrame().
GetArrayType()
const ArrayType * v8::internal::wasm::WasmInterpreterRuntime::GetArrayType (uint32_t array_index) const [inline]
Definition at line 146 of file wasm-interpreter-runtime-inl.h.
                                {
  return module_->array_type(ModuleTypeIndex{array_index});
}
References v8::internal::wasm::WasmModule::array_type(), and module_.
Referenced by ArrayNewUninitialized().
GetFunctionBytecode()
WasmBytecode * v8::internal::wasm::WasmInterpreterRuntime::GetFunctionBytecode (uint32_t func_index) [inline]
Definition at line 103 of file wasm-interpreter-runtime-inl.h.
                         {
  return codemap_->GetFunctionBytecode(func_index);
}
References codemap_, and v8::internal::wasm::WasmInterpreter::CodeMap::GetFunctionBytecode().
Referenced by BeginExecution(), ContinueExecution(), ExecuteFunction(), and PrepareTailCall().
GetFunctionIndex()
int v8::internal::wasm::WasmInterpreterRuntime::GetFunctionIndex (Address frame_pointer, int index) const
Definition at line 2783 of file wasm-interpreter-runtime.cc.
                                                              {
  if (current_thread_) {
    WasmInterpreterThread::Activation* activation =
        current_thread_->GetActivation(frame_pointer);
    if (activation) {
      return activation->GetFunctionIndex(index);
    }
  }
  return -1;
}
References current_thread_, v8::internal::wasm::WasmInterpreterThread::GetActivation(), v8::internal::wasm::WasmInterpreterThread::Activation::GetFunctionIndex(), and v8::internal::index.
GetFunctionRef()
DirectHandle< Object > v8::internal::wasm::WasmInterpreterRuntime::GetFunctionRef (uint32_t index) const [inline]
Definition at line 139 of file wasm-interpreter-runtime-inl.h.
                          {
  // This function assumes that it is executed in a HandleScope.
  return WasmTrustedInstanceData::GetOrCreateFuncRef(
      isolate_, wasm_trusted_instance_data(), index);
}
References v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::index, isolate_, and wasm_trusted_instance_data().
GetGlobalAddress()
uint8_t * v8::internal::wasm::WasmInterpreterRuntime::GetGlobalAddress (uint32_t index) [inline]
Definition at line 49 of file wasm-interpreter-runtime-inl.h.
                                                                       {
  DCHECK_LT(index, module_->globals.size());
  return global_addresses_[index];
}
References DCHECK_LT, global_addresses_, v8::internal::wasm::WasmModule::globals, v8::internal::index, and module_.
GetGlobalRef()
DirectHandle< Object > v8::internal::wasm::WasmInterpreterRuntime::GetGlobalRef (uint32_t index) const [inline]
Definition at line 54 of file wasm-interpreter-runtime-inl.h.
                          {
  // This function assumes that it is executed in a HandleScope.
  const wasm::WasmGlobal& global = module_->globals[index];
  DCHECK(global.type.is_reference());
  Tagged<FixedArray> global_buffer; // The buffer of the global.
  uint32_t global_index = 0; // The index into the buffer.
  std::tie(global_buffer, global_index) =
      wasm_trusted_instance_data()->GetGlobalBufferAndIndex(global);
  return DirectHandle<Object>(global_buffer->get(global_index), isolate_);
}
References v8::internal::DCHECK(), v8::internal::wasm::WasmModule::globals, v8::internal::index, v8::internal::wasm::ValueTypeBase::is_reference(), isolate_, module_, v8::internal::wasm::WasmGlobal::type, and wasm_trusted_instance_data().
GetInterpretedStack()
std::vector< WasmInterpreterStackEntry > v8::internal::wasm::WasmInterpreterRuntime::GetInterpretedStack (Address frame_pointer)
Definition at line 2757 of file wasm-interpreter-runtime.cc.
                                                                 {
  // The current thread can be nullptr if we throw an exception before calling
  // {BeginExecution}.
  if (current_thread_) {
    WasmInterpreterThread::Activation* activation =
        current_thread_->GetActivation(frame_pointer);
    if (activation) {
      return activation->GetStackTrace();
    }
    if (trap_function_index_ < 0) {
      // It is possible to have a trap before starting to execute Wasm code.
      // This can happen if the JSToWasmObject fails for a type mismatch in the
      // JSToWasmInterpreterWrapper. In this case we know that we were going to
      // execute the initial function {start_function_index_}.
      trap_function_index_ = start_function_index_;
    }
    return {{trap_function_index_, static_cast<int>(trap_pc_)}};
  }
  // It is possible to throw before entering a Wasm function, while converting
  // the args from JS to Wasm, with JSToWasmObject.
  return {{0, 0}};
}
References current_thread_, v8::internal::wasm::WasmInterpreterThread::GetActivation(), v8::internal::wasm::WasmInterpreterThread::Activation::GetStackTrace(), start_function_index_, trap_function_index_, and trap_pc_.
GetIsolate()
Isolate* v8::internal::wasm::WasmInterpreterRuntime::GetIsolate () const [inline]
Definition at line 44 of file wasm-interpreter-runtime.h.
{ return isolate_; }
References isolate_.
Referenced by ExecuteFunction().
GetMemorySize()
size_t v8::internal::wasm::WasmInterpreterRuntime::GetMemorySize () const [inline]
Definition at line 90 of file wasm-interpreter-runtime-inl.h.
                                                          {
  return wasm_trusted_instance_data()->memory0_size();
}
References wasm_trusted_instance_data().
GetMemoryStart()
uint8_t* v8::internal::wasm::WasmInterpreterRuntime::GetMemoryStart () const [inline]
Definition at line 53 of file wasm-interpreter-runtime.h.
{ return memory_start_; }
References memory_start_.
GetNullValue()
Tagged< Object > v8::internal::wasm::WasmInterpreterRuntime::GetNullValue (const ValueType obj_type) const [inline]
Definition at line 114 of file wasm-interpreter-runtime-inl.h.
                                    {
  if (obj_type == kWasmExternRef || obj_type == kWasmNullExternRef) {
    return *isolate_->factory()->null_value();
  } else {
    return *isolate_->factory()->wasm_null();
  }
}
References v8::internal::Isolate::factory(), isolate_, v8::internal::wasm::kWasmExternRef, and v8::internal::wasm::kWasmNullExternRef.
GetReturnValue()
const WasmValue& v8::internal::wasm::WasmInterpreterRuntime::GetReturnValue (size_t index) const [inline]
Definition at line 146 of file wasm-interpreter-runtime.h.
                                                      {
    DCHECK_LT(index, function_result_.size());
    return function_result_[index];
  }
References DCHECK_LT, function_result_, and v8::internal::index.
GetWasmArrayRefElement()
DirectHandle< Object > v8::internal::wasm::WasmInterpreterRuntime::GetWasmArrayRefElement (Tagged< WasmArray > array, uint32_t index) const [inline]
Definition at line 151 of file wasm-interpreter-runtime-inl.h.
                                                   {
  return WasmArray::GetElement(isolate_, handle(array, isolate_), index);
}
References v8::internal::WasmArray::GetElement(), v8::internal::handle(), v8::internal::index, and isolate_.
GetWasmTag()
const WasmTag& v8::internal::wasm::WasmInterpreterRuntime::GetWasmTag (uint32_t tag_index) const [inline]
Definition at line 99 of file wasm-interpreter-runtime.h.
                                                             {
    return module_->tags[tag_index];
  }
References module_, and v8::internal::wasm::WasmModule::tags.
Referenced by CreateWasmExceptionPackage().
HandleException()
WasmInterpreterThread::ExceptionHandlingResult v8::internal::wasm::WasmInterpreterRuntime::HandleException (uint32_t * sp, const uint8_t *& current_code) [private]
Definition at line 715 of file wasm-interpreter-runtime.cc.
                                                                      {
  DCHECK_IMPLIES(current_code, current_frame_.current_function_);
  DCHECK_IMPLIES(!current_code, !current_frame_.current_function_);
  DCHECK(isolate_->has_exception());
  bool catchable = current_frame_.current_function_ &&
                   isolate_->is_catchable_by_wasm(isolate_->exception());
  if (catchable) {
    HandleScope scope(isolate_);
    DirectHandle<Object> exception(isolate_->exception(), isolate_);
    Tagged<WasmTrustedInstanceData> trusted_data =
        *wasm_trusted_instance_data();
    // We might need to allocate a new FixedArray<Object> to store the caught
    // exception.
    DCHECK(AllowHeapAllocation::IsAllowed());
    size_t current_code_offset =
        current_code - current_frame_.current_function_->GetCode();
    const WasmEHData::TryBlock* try_block =
        current_frame_.current_function_->GetTryBlock(current_code_offset);
    while (try_block) {
      for (const auto& catch_handler : try_block->catch_handlers) {
        if (catch_handler.tag_index < 0) {
          // Catch all.
          current_code = current_frame_.current_function_->GetCode() +
                         catch_handler.code_offset;
          current_frame_.SetCaughtException(
              isolate_, catch_handler.catch_block_index, exception);
          isolate_->clear_exception();
          return WasmInterpreterThread::HANDLED;
        } else if (IsWasmExceptionPackage(*exception, isolate_)) {
          // The exception was thrown by Wasm code and it's wrapped in a
          // WasmExceptionPackage.
          DirectHandle<Object> caught_tag =
              WasmExceptionPackage::GetExceptionTag(
                  isolate_, Cast<WasmExceptionPackage>(exception));
          DirectHandle<Object> expected_tag(
              trusted_data->tags_table()->get(catch_handler.tag_index),
              isolate_);
          DCHECK(IsWasmExceptionTag(*expected_tag));
          // Determines whether the given exception has a tag matching the
          // expected tag for the given index within the exception table of the
          // current instance.
          if (expected_tag.is_identical_to(caught_tag)) {
            current_code = current_frame_.current_function_->GetCode() +
                           catch_handler.code_offset;
            DCHECK_LT(catch_handler.tag_index, module_->tags.size());
            const WasmTag& tag = module_->tags[catch_handler.tag_index];
            auto exception_payload_slot_offsets =
                current_frame_.current_function_
                    ->GetExceptionPayloadStartSlotOffsets(
                        catch_handler.catch_block_index);
            UnpackException(
                sp, tag, exception,
                exception_payload_slot_offsets.first_param_slot_offset,
                exception_payload_slot_offsets.first_param_ref_stack_index);
            current_frame_.SetCaughtException(
                isolate_, catch_handler.catch_block_index, exception);
            isolate_->clear_exception();
            return WasmInterpreterThread::HANDLED;
          }
        } else {
          // Check for the special case where the tag is WebAssembly.JSTag and
          // the exception is not a WebAssembly.Exception. In this case the
          // exception is caught and pushed on the operand stack.
          // Only perform this check if the tag signature is the same as
          // the JSTag signature, i.e. a single externref, otherwise we know
          // statically that it cannot be the JSTag.
          DCHECK_LT(catch_handler.tag_index, module_->tags.size());
          const WasmTagSig* sig = module_->tags[catch_handler.tag_index].sig;
          if (sig->return_count() != 0 || sig->parameter_count() != 1 ||
              (sig->GetParam(0).kind() != kRefNull &&
               sig->GetParam(0).kind() != kRef)) {
            continue;
          }
          DirectHandle<JSObject> js_tag_object(
              isolate_->native_context()->wasm_js_tag(), isolate_);
          DirectHandle<WasmTagObject> wasm_tag_object(
              Cast<WasmTagObject>(*js_tag_object), isolate_);
          DirectHandle<Object> caught_tag(wasm_tag_object->tag(), isolate_);
          DirectHandle<Object> expected_tag(
              trusted_data->tags_table()->get(catch_handler.tag_index),
              isolate_);
          if (!expected_tag.is_identical_to(caught_tag)) {
            continue;
          }
          current_code = current_frame_.current_function_->GetCode() +
                         catch_handler.code_offset;
          // Push exception on the operand stack.
          auto exception_payload_slot_offsets =
              current_frame_.current_function_
                  ->GetExceptionPayloadStartSlotOffsets(
                      catch_handler.catch_block_index);
          StoreWasmRef(
              exception_payload_slot_offsets.first_param_ref_stack_index,
              exception);
          base::WriteUnalignedValue<WasmRef>(
              reinterpret_cast<Address>(
                  sp + exception_payload_slot_offsets.first_param_slot_offset),
              exception);
          current_frame_.SetCaughtException(
              isolate_, catch_handler.catch_block_index, exception);
          isolate_->clear_exception();
          return WasmInterpreterThread::HANDLED;
        }
      }
      try_block =
          current_frame_.current_function_->GetParentTryBlock(try_block);
    }
  }
  DCHECK_NOT_NULL(current_thread_);
  current_thread_->Unwinding();
  return WasmInterpreterThread::UNWOUND;
}
References v8::internal::wasm::WasmEHData::TryBlock::catch_handlers, v8::internal::Isolate::clear_exception(), current_frame_, current_thread_, v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::Isolate::exception(), v8::internal::WasmExceptionPackage::GetExceptionTag(), v8::internal::wasm::WasmInterpreterThread::HANDLED, v8::internal::Isolate::has_exception(), v8::internal::Isolate::is_catchable_by_wasm(), v8::internal::DirectHandle< T >::is_identical_to(), isolate_, v8::internal::kRef, v8::internal::kRefNull, module_, v8::internal::Isolate::native_context(), v8::internal::sig, StoreWasmRef(), v8::internal::wasm::WasmModule::tags, UnpackException(), v8::internal::wasm::WasmInterpreterThread::Unwinding(), v8::internal::wasm::WasmInterpreterThread::UNWOUND, and wasm_trusted_instance_data().
Referenced by ExecuteCallRef(), ExecuteFunction(), ExecuteImportedFunction(), ExecuteIndirectCall(), and ThrowException().
I32AtomicWait()
int32_t v8::internal::wasm::WasmInterpreterRuntime::I32AtomicWait (uint64_t effective_index, int32_t val, int64_t timeout)
Definition at line 858 of file wasm-interpreter-runtime.cc.
                                                                            {
  // We might handle interrupts (for example from a debugger) here while we are
  // locked in the futex. We need to make sure that the current activation is
  // up-to-date, if we need to traverse the call stack.
  current_thread_->SetCurrentFrame(current_frame_);
  HandleScope handle_scope(isolate_);
  // TODO(paolosev@microsoft.com): Support multiple memories.
  uint32_t memory_index = 0;
  DirectHandle<JSArrayBuffer> array_buffer(
      wasm_trusted_instance_data()->memory_object(memory_index)->array_buffer(),
      isolate_);
  auto result = FutexEmulation::WaitWasm32(isolate_, array_buffer,
                                           buffer_offset, val, timeout);
  return result.ToSmi().value();
}
References current_frame_, current_thread_, isolate_, v8::base::internal::result, v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), v8::internal::FutexEmulation::WaitWasm32(), and wasm_trusted_instance_data().
I64AtomicWait()
int32_t v8::internal::wasm::WasmInterpreterRuntime::I64AtomicWait (uint64_t effective_index, int64_t val, int64_t timeout)
Definition at line 876 of file wasm-interpreter-runtime.cc.
                                                                            {
  // We might handle interrupts (for example from a debugger) here while we are
  // locked in the futex. We need to make sure that the current activation is
  // up-to-date, if we need to traverse the call stack.
  current_thread_->SetCurrentFrame(current_frame_);
  HandleScope handle_scope(isolate_);
  // TODO(paolosev@microsoft.com): Support multiple memories.
  uint32_t memory_index = 0;
  DirectHandle<JSArrayBuffer> array_buffer(
      wasm_trusted_instance_data()->memory_object(memory_index)->array_buffer(),
      isolate_);
  auto result = FutexEmulation::WaitWasm64(isolate_, array_buffer,
                                           buffer_offset, val, timeout);
  return result.ToSmi().value();
}
References current_frame_, current_thread_, isolate_, v8::base::internal::result, v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), v8::internal::FutexEmulation::WaitWasm64(), and wasm_trusted_instance_data().
InitGlobalAddressCache()
void v8::internal::wasm::WasmInterpreterRuntime::InitGlobalAddressCache () [private]
Definition at line 347 of file wasm-interpreter-runtime.cc.
                                                    {
  global_addresses_.resize(module_->globals.size());
  for (size_t index = 0; index < module_->globals.size(); index++) {
    const WasmGlobal& global = module_->globals[index];
    if (!global.type.is_reference()) {
      global_addresses_[index] =
          wasm_trusted_instance_data()->GetGlobalStorage(global);
    }
  }
}
References global_addresses_, v8::internal::wasm::WasmModule::globals, v8::internal::index, v8::internal::wasm::ValueTypeBase::is_reference(), module_, v8::internal::wasm::WasmGlobal::type, and wasm_trusted_instance_data().
InitializeRefLocalsRefs()
void v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs (const WasmBytecode * target_function) [private]
Definition at line 1415 of file wasm-interpreter-runtime.cc.
                                         {
  if (V8_UNLIKELY(target_function->ref_locals_count() > 0)) {
    uint32_t ref_stack_index =
        target_function->ref_rets_count() + target_function->ref_args_count();
    for (uint32_t i = 0; i < target_function->locals_count(); i++) {
      ValueType local_type = target_function->local_type(i);
      if (local_type == kWasmExternRef || local_type == kWasmNullExternRef) {
        StoreWasmRef(ref_stack_index++,
                     WasmRef(isolate_->factory()->null_value()));
      } else if (local_type.is_reference()) {
        StoreWasmRef(ref_stack_index++,
                     WasmRef(isolate_->factory()->wasm_null()));
      }
    }
  }
}
References v8::internal::Isolate::factory(), v8::internal::wasm::ValueTypeBase::is_reference(), isolate_, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmNullExternRef, v8::internal::wasm::WasmBytecode::local_type(), v8::internal::wasm::WasmBytecode::locals_count(), v8::internal::wasm::WasmBytecode::ref_args_count(), v8::internal::wasm::WasmBytecode::ref_locals_count(), v8::internal::wasm::WasmBytecode::ref_rets_count(), StoreWasmRef(), and V8_UNLIKELY.
Referenced by ExecuteFunction(), and PrepareTailCall().
InitIndirectFunctionTables()
void v8::internal::wasm::WasmInterpreterRuntime::InitIndirectFunctionTables () [private]
Definition at line 382 of file wasm-interpreter-runtime.cc.
                                                        {
  int table_count = static_cast<int>(module_->tables.size());
  indirect_call_tables_.resize(table_count);
  for (int table_index = 0; table_index < table_count; ++table_index) {
    PurgeIndirectCallCache(table_index);
  }
}
References indirect_call_tables_, module_, PurgeIndirectCallCache(), and v8::internal::wasm::WasmModule::tables.
InitMemoryAddresses()
void v8::internal::wasm::WasmInterpreterRuntime::InitMemoryAddresses () [inline], [private]
Definition at line 78 of file wasm-interpreter-runtime-inl.h.
                                                        {
  memory_start_ = wasm_trusted_instance_data()->memory0_start();
}
References memory_start_, and wasm_trusted_instance_data().
Referenced by MemoryGrow().
instruction_table_offset()
int v8::internal::wasm::WasmInterpreterRuntime::instruction_table_offset () [static]
Definition at line 2136 of file wasm-interpreter-runtime.cc.
                                                     {
  return OFFSET_OF(WasmInterpreterRuntime, instruction_table_);
}
References instruction_table_, and OFFSET_OF.
IsMemory64()
bool v8::internal::wasm::WasmInterpreterRuntime::IsMemory64 () const [inline]
Definition at line 86 of file wasm-interpreter-runtime-inl.h.
                                                     {
  return !module_->memories.empty() && module_->memories[0].is_memory64();
}
References v8::internal::wasm::WasmModule::memories, and module_.
IsNull()
bool v8::internal::wasm::WasmInterpreterRuntime::IsNull (Isolate * isolate, const WasmRef obj, const ValueType obj_type) [inline], [static]
Definition at line 124 of file wasm-interpreter-runtime-inl.h.
                                                                     {
  if (obj_type == kWasmExternRef || obj_type == kWasmNullExternRef) {
    return i::IsNull(*obj, isolate);
  } else {
    return i::IsWasmNull(*obj, isolate);
  }
}
References v8::internal::IsNull(), v8::internal::wasm::kWasmExternRef, and v8::internal::wasm::kWasmNullExternRef.
Referenced by v8::internal::wasm::AbstractTypeCast(), and IsNullTypecheck().
IsNullTypecheck()
bool v8::internal::wasm::WasmInterpreterRuntime::IsNullTypecheck (const WasmRef obj, const ValueType obj_type) const [inline]
Definition at line 108 of file wasm-interpreter-runtime-inl.h.
                                                       {
  return IsNull(isolate_, obj, obj_type);
}
References IsNull(), and isolate_.
IsRefNull()
bool v8::internal::wasm::WasmInterpreterRuntime::IsRefNull (DirectHandle< Object > ref) const [inline]
Definition at line 133 of file wasm-interpreter-runtime-inl.h.
                                       {
  // This function assumes that it is executed in a HandleScope.
  return i::IsNull(*object, isolate_) || IsWasmNull(*object, isolate_);
}
References v8::internal::IsNull(), and isolate_.
JSToWasmObject()
WasmRef v8::internal::wasm::WasmInterpreterRuntime::JSToWasmObject (WasmRef extern_ref, ValueType value_type) const
Definition at line 2537 of file wasm-interpreter-runtime.cc.
                                                                     {
  DirectHandle<Object> result;
  const char* error_message;
  if (wasm::JSToWasmObject(isolate_, module_, extern_ref, type, &error_message)
          .ToHandle(&result)) {
    return result;
  }
  {
    // Only in case of exception it can allocate.
    AllowHeapAllocation allow_gc;
    if (v8_flags.wasm_jitless && trap_handler::IsThreadInWasm()) {
      trap_handler::ClearThreadInWasm();
    }
    Tagged<Object> error = isolate_->Throw(*isolate_->factory()->NewTypeError(
        MessageTemplate::kWasmTrapJSTypeError));
    return direct_handle(error, isolate_);
  }
}
References v8::internal::trap_handler::ClearThreadInWasm(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), isolate_, v8::internal::trap_handler::IsThreadInWasm(), v8::internal::wasm::JSToWasmObject(), module_, v8::base::internal::result, v8::internal::Isolate::Throw(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::tracing::type, and v8::internal::v8_flags.
Referenced by CallExternalJSFunction(), and v8::internal::RUNTIME_FUNCTION().
MatchingExceptionTag()
bool v8::internal::wasm::WasmInterpreterRuntime::MatchingExceptionTag (DirectHandle< Object > exception_object, uint32_t index) const [private]
memory_start_offset()
int v8::internal::wasm::WasmInterpreterRuntime::memory_start_offset () [static]
Definition at line 2131 of file wasm-interpreter-runtime.cc.
                                                {
  return OFFSET_OF(WasmInterpreterRuntime, memory_start_);
}
References memory_start_, and OFFSET_OF.
MemoryCopy()
bool v8::internal::wasm::WasmInterpreterRuntime::MemoryCopy (const uint8_t *& current_code, uint64_t dst, uint64_t src, uint64_t size)
Definition at line 545 of file wasm-interpreter-runtime.cc.
                                                       {
  Address dst_addr;
  Address src_addr;
  if (!BoundsCheckMemRange(dst, &size, &dst_addr) ||
      !BoundsCheckMemRange(src, &size, &src_addr)) {
    SetTrap(TrapReason::kTrapMemOutOfBounds, current_code);
    return false;
  }
  std::memmove(reinterpret_cast<void*>(dst_addr),
               reinterpret_cast<void*>(src_addr), size);
  return true;
}
References BoundsCheckMemRange(), SetTrap(), and size().
MemoryFill()
bool v8::internal::wasm::WasmInterpreterRuntime::MemoryFill (const uint8_t *& current_code, uint64_t dst, uint32_t value, uint64_t size)
Definition at line 561 of file wasm-interpreter-runtime.cc.
                                                       {
  Address dst_addr;
  if (!BoundsCheckMemRange(dst, &size, &dst_addr)) {
    SetTrap(TrapReason::kTrapMemOutOfBounds, current_code);
    return false;
  }
  std::memset(reinterpret_cast<void*>(dst_addr), value, size);
  return true;
}
References BoundsCheckMemRange(), SetTrap(), size(), and v8::internal::value.
MemoryGrow()
int32_t v8::internal::wasm::WasmInterpreterRuntime::MemoryGrow (uint32_t delta_pages)
Definition at line 371 of file wasm-interpreter-runtime.cc.
                                                               {
  HandleScope handle_scope(isolate_); // Avoid leaking handles.
  // TODO(paolosev@microsoft.com): Support multiple memories.
  uint32_t memory_index = 0;
  DirectHandle<WasmMemoryObject> memory(
      wasm_trusted_instance_data()->memory_object(memory_index), isolate_);
  int32_t result = WasmMemoryObject::Grow(isolate_, memory, delta_pages);
  InitMemoryAddresses();
  return result;
}
References v8::internal::WasmMemoryObject::Grow(), InitMemoryAddresses(), isolate_, v8::base::internal::result, and wasm_trusted_instance_data().
MemoryInit()
bool v8::internal::wasm::WasmInterpreterRuntime::MemoryInit (const uint8_t *& current_code, uint32_t data_segment_index, uint64_t dst, uint64_t src, uint64_t size)
Definition at line 523 of file wasm-interpreter-runtime.cc.
                                                       {
  DirectHandle<WasmTrustedInstanceData> trusted_data =
      wasm_trusted_instance_data();
  Address dst_addr;
  uint64_t src_max =
      trusted_data->data_segment_sizes()->get(data_segment_index);
  if (!BoundsCheckMemRange(dst, &size, &dst_addr) ||
      !base::IsInBounds(src, size, src_max)) {
    SetTrap(TrapReason::kTrapMemOutOfBounds, current_code);
    return false;
  }
  Address src_addr =
      trusted_data->data_segment_starts()->get(data_segment_index) + src;
  std::memmove(reinterpret_cast<void*>(dst_addr),
               reinterpret_cast<void*>(src_addr), size);
  return true;
}
References BoundsCheckMemRange(), SetTrap(), size(), and wasm_trusted_instance_data().
MemorySize()
uint64_t v8::internal::wasm::WasmInterpreterRuntime::MemorySize () const [inline]
Definition at line 82 of file wasm-interpreter-runtime-inl.h.
                                                         {
  return wasm_trusted_instance_data()->memory0_size() / kWasmPageSize;
}
References v8::internal::wasm::kWasmPageSize, and wasm_trusted_instance_data().
operator=()
WasmInterpreterRuntime& v8::internal::wasm::WasmInterpreterRuntime::operator= (const WasmInterpreterRuntime &) [delete]
PrepareTailCall()
void v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall (const uint8_t *& code, uint32_t func_index, uint32_t current_stack_size, uint32_t return_slot_offset)
Definition at line 1437 of file wasm-interpreter-runtime.cc.
                                                                          {
  // TODO(paolosev@microsoft.com): avoid to duplicate code from ExecuteFunction?
  WasmBytecode* target_function = GetFunctionBytecode(func_index);
  DCHECK_NOT_NULL(target_function);
  // Update the current (caller) frame setting current_bytecode_ to the initial
  // instruction of the callee.
  current_frame_.current_function_ = target_function;
  current_frame_.DisposeCaughtExceptionsArray(isolate_);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  current_frame_.current_stack_start_locals_ =
      current_frame_.current_stack_start_args_ + target_function->args_count();
  current_frame_.current_stack_start_stack_ =
      current_frame_.current_stack_start_locals_ +
      target_function->locals_count();
  if (v8_flags.trace_drumbrake_execution) {
    Trace("\nTailCallFunction: %d\n", func_index);
    Trace("= > PushFrame #%d(#%d @%d)\n", current_frame_.current_stack_height_,
          func_index, 0);
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  if (!WasmStackCheck(target_function->GetCode(), code)) {
    return;
  }
  const uint8_t* stack_limit = current_frame_.thread_->StackLimitAddress();
  if (V8_UNLIKELY(stack_limit <= current_frame_.current_sp_ ||
                  !target_function->InitializeSlots(
                      current_frame_.current_sp_,
                      stack_limit - current_frame_.current_sp_))) {
    // Try to resize the stack.
    size_t additional_required_space =
        target_function->frame_size() -
        (stack_limit - current_frame_.current_sp_);
    // Try again.
    if (!current_frame_.thread_->ExpandStack(additional_required_space) ||
        !target_function->InitializeSlots(
            current_frame_.current_sp_,
            (stack_limit = current_frame_.thread_->StackLimitAddress()) -
                current_frame_.current_sp_)) {
      ClearThreadInWasmScope clear_wasm_flag(isolate_);
      SealHandleScope shs(isolate_);
      SetTrap(TrapReason::kTrapUnreachable, code);
      isolate_->StackOverflow();
      return;
    }
  }
  uint32_t ref_slots_count = target_function->ref_slots_count();
  if (V8_UNLIKELY(ref_slots_count > 0)) {
    uint32_t ref_array_length =
        current_frame_.ref_array_current_sp_ + ref_slots_count;
    current_thread_->EnsureRefStackSpace(ref_array_length);
    InitializeRefLocalsRefs(target_function);
  }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  uint32_t shadow_stack_offset = 0;
  if (v8_flags.trace_drumbrake_execution) {
    shadow_stack_offset = target_function->rets_slots_size() * kSlotSize;
    for (uint32_t i = 0; i < target_function->args_count(); i++) {
      shadow_stack_offset +=
          TracePush(target_function->arg_type(i).kind(), shadow_stack_offset);
    }
    // Make room for locals in shadow stack
    shadow_stack_offset += target_function->const_slots_size_in_bytes();
    for (size_t i = 0; i < target_function->locals_count(); i++) {
      shadow_stack_offset +=
          TracePush(target_function->local_type(i).kind(), shadow_stack_offset);
    }
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  code = target_function->GetCode();
}
References v8::internal::wasm::WasmBytecode::arg_type(), v8::internal::wasm::WasmBytecode::args_count(), code, v8::internal::wasm::WasmBytecode::const_slots_size_in_bytes(), current_frame_, current_thread_, DCHECK_NOT_NULL, v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), v8::internal::wasm::WasmBytecode::frame_size(), v8::internal::wasm::WasmBytecode::GetCode(), GetFunctionBytecode(), InitializeRefLocalsRefs(), v8::internal::wasm::WasmBytecode::InitializeSlots(), isolate_, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kSlotSize, v8::internal::wasm::WasmBytecode::local_type(), v8::internal::wasm::WasmBytecode::locals_count(), v8::internal::wasm::WasmBytecode::ref_slots_count(), v8::internal::wasm::WasmBytecode::rets_slots_size(), SetTrap(), v8::internal::Isolate::StackOverflow(), v8::internal::v8_flags, V8_UNLIKELY, and WasmStackCheck().
Referenced by ExecuteIndirectCall().
PrintStack()
void v8::internal::wasm::WasmInterpreterRuntime::PrintStack (uint32_t * sp, RegMode reg_mode, int64_t r0, double fp0)
Definition at line 2800 of file wasm-interpreter-runtime.cc.
                                                                {
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (tracer_ && tracer_->ShouldTraceFunction(
                     current_frame_.current_function_->GetFunctionIndex())) {
    shadow_stack_->Print(this, sp, current_frame_.current_stack_start_args_,
                         current_frame_.current_stack_start_locals_,
                         current_frame_.current_stack_start_stack_, reg_mode,
                         r0, fp0);
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
}
References current_frame_.
PurgeIndirectCallCache()
void v8::internal::wasm::WasmInterpreterRuntime::PurgeIndirectCallCache (uint32_t table_index) [private]
Definition at line 1699 of file wasm-interpreter-runtime.cc.
                                                                        {
  DCHECK_LT(table_index, indirect_call_tables_.size());
  const WasmTable& table = module_->tables[table_index];
  if (IsSubtypeOf(table.type, kWasmFuncRef, module_)) {
    size_t length =
        Tagged<WasmDispatchTable>::cast(
            wasm_trusted_instance_data()->dispatch_tables()->get(table_index))
            ->length();
    indirect_call_tables_[table_index].resize(length);
    for (size_t i = 0; i < length; i++) {
      indirect_call_tables_[table_index][i] = {};
    }
  }
}
References v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::cast(), DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, indirect_call_tables_, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmFuncRef, v8::internal::length, module_, v8::internal::wasm::WasmModule::tables, v8::internal::wasm::WasmTable::type, and wasm_trusted_instance_data().
Referenced by InitIndirectFunctionTables(), TableCopy(), and TableInit().
reference_stack()
DirectHandle<FixedArray> v8::internal::wasm::WasmInterpreterRuntime::reference_stack () const [inline], [private]
Definition at line 280 of file wasm-interpreter-runtime.h.
                                                   {
    return thread()->reference_stack();
  }
References v8::internal::wasm::WasmInterpreterThread::reference_stack(), and thread().
Referenced by ExtractWasmRef(), and StoreWasmRef().
RefIsArray()
bool v8::internal::wasm::WasmInterpreterRuntime::RefIsArray (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
Definition at line 2710 of file wasm-interpreter-runtime.cc.
                                                                  {
  return AbstractTypeCast<&ArrayCheck>(isolate_, obj, obj_type, null_succeeds);
}
References isolate_.
RefIsEq()
bool v8::internal::wasm::WasmInterpreterRuntime::RefIsEq (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
Definition at line 2675 of file wasm-interpreter-runtime.cc.
                                                               {
  return AbstractTypeCast<&EqCheck>(isolate_, obj, obj_type, null_succeeds);
}
References isolate_.
RefIsI31()
bool v8::internal::wasm::WasmInterpreterRuntime::RefIsI31 (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
Definition at line 2682 of file wasm-interpreter-runtime.cc.
                                                                {
  return AbstractTypeCast<&I31Check>(isolate_, obj, obj_type, null_succeeds);
}
References isolate_.
RefIsString()
bool v8::internal::wasm::WasmInterpreterRuntime::RefIsString (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
Definition at line 2724 of file wasm-interpreter-runtime.cc.
                                                                   {
  return AbstractTypeCast<&StringCheck>(isolate_, obj, obj_type, null_succeeds);
}
References isolate_.
RefIsStruct()
bool v8::internal::wasm::WasmInterpreterRuntime::RefIsStruct (const WasmRef obj, const ValueType obj_type, bool null_succeeds) const
Definition at line 2696 of file wasm-interpreter-runtime.cc.
                                                                   {
  return AbstractTypeCast<&StructCheck>(isolate_, obj, obj_type, null_succeeds);
}
References isolate_.
ResetCurrentHandleScope()
void v8::internal::wasm::WasmInterpreterRuntime::ResetCurrentHandleScope ()
Definition at line 2752 of file wasm-interpreter-runtime.cc.
                                                     {
  current_frame_.ResetHandleScope(isolate_);
}
References current_frame_, and isolate_.
RethrowException()
void v8::internal::wasm::WasmInterpreterRuntime::RethrowException (const uint8_t *& code, uint32_t * sp, uint32_t catch_block_index)
Definition at line 703 of file wasm-interpreter-runtime.cc.
                                                                          {
  DirectHandle<Object> exception_object =
      current_frame_.GetCaughtException(isolate_, catch_block_index);
  DCHECK(!IsTheHole(*exception_object));
  ThrowException(code, sp, *exception_object);
}
References code, current_frame_, v8::internal::DCHECK(), isolate_, and ThrowException().
RttCanon()
DirectHandle< Map > v8::internal::wasm::WasmInterpreterRuntime::RttCanon (uint32_t type_index) const
Definition at line 2388 of file wasm-interpreter-runtime.cc.
                                                                            {
  DirectHandle<Map> rtt{
      Cast<Map>(
          wasm_trusted_instance_data()->managed_object_maps()->get(type_index)),
      isolate_};
  return rtt;
}
References isolate_, and wasm_trusted_instance_data().
Referenced by ArrayNewUninitialized(), CheckIndirectCallSignature(), StructNewUninitialized(), and WasmArrayNewSegment().
SetGlobalRef()
void v8::internal::wasm::WasmInterpreterRuntime::SetGlobalRef (uint32_t index, DirectHandle< Object > ref) const [inline]
Definition at line 66 of file wasm-interpreter-runtime-inl.h.
                                                    {
  // This function assumes that it is executed in a HandleScope.
  const wasm::WasmGlobal& global = module_->globals[index];
  DCHECK(global.type.is_reference());
  Tagged<FixedArray> global_buffer; // The buffer of the global.
  uint32_t global_index = 0; // The index into the buffer.
  std::tie(global_buffer, global_index) =
      wasm_trusted_instance_data()->GetGlobalBufferAndIndex(global);
  global_buffer->set(global_index, *ref);
}
References v8::internal::DCHECK(), v8::internal::wasm::WasmModule::globals, v8::internal::index, v8::internal::wasm::ValueTypeBase::is_reference(), module_, v8::internal::wasm::WasmGlobal::type, and wasm_trusted_instance_data().
SetTrap() [1/2]
void v8::internal::wasm::WasmInterpreterRuntime::SetTrap (TrapReason trap_reason, const uint8_t *& current_code)
Definition at line 2743 of file wasm-interpreter-runtime.cc.
                                                           {
  SetTrap(trap_reason,
          current_frame_.current_function_
              ? current_frame_.current_function_->GetPcFromTrapCode(code)
              : 0);
  RedirectCodeToUnwindHandler(code);
}
References code, current_frame_, v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler(), and SetTrap().
SetTrap() [2/2]
void v8::internal::wasm::WasmInterpreterRuntime::SetTrap (TrapReason trap_reason, pc_t trap_pc)
Definition at line 2730 of file wasm-interpreter-runtime.cc.
                                                                         {
  trap_function_index_ =
      current_frame_.current_function_
          ? current_frame_.current_function_->GetFunctionIndex()
          : 0;
  DCHECK_GE(trap_function_index_, 0);
  DCHECK_LT(trap_function_index_, module_->functions.size());
  trap_pc_ = trap_pc;
  thread()->Trap(trap_reason, trap_function_index_, static_cast<int>(trap_pc_),
                 current_frame_);
}
References current_frame_, DCHECK_GE, DCHECK_LT, v8::internal::wasm::WasmModule::functions, module_, thread(), v8::internal::wasm::WasmInterpreterThread::Trap(), trap_function_index_, and trap_pc_.
Referenced by BeginExecution(), ExecuteFunction(), ExecuteIndirectCall(), MemoryCopy(), MemoryFill(), MemoryInit(), PrepareTailCall(), SetTrap(), TableCopy(), TableFill(), TableGet(), TableInit(), TableSet(), and WasmStackCheck().
SetTrapFunctionIndex()
void v8::internal::wasm::WasmInterpreterRuntime::SetTrapFunctionIndex (int32_t func_index)
Definition at line 2795 of file wasm-interpreter-runtime.cc.
                                                                    {
  trap_function_index_ = func_index;
  trap_pc_ = 0;
}
References trap_function_index_, and trap_pc_.
state()
WasmInterpreterThread::State v8::internal::wasm::WasmInterpreterRuntime::state () const [inline], [private]
Definition at line 278 of file wasm-interpreter-runtime.h.
{ return thread()->state(); }
References v8::internal::wasm::WasmInterpreterThread::state(), and thread().
Referenced by ContinueExecution(), ExecuteFunction(), and ExecuteIndirectCall().
StoreRefArgsIntoStackSlots()
void v8::internal::wasm::WasmInterpreterRuntime::StoreRefArgsIntoStackSlots (uint8_t * sp, uint32_t ref_stack_fp_offset, const FunctionSig * sig) [private]
Definition at line 1290 of file wasm-interpreter-runtime.cc.
                                                                       {
  // Argument values of type Ref, if present, are already stored in the thread's
  // reference_stack_ starting at index ref_stack_fp_offset + RefRetsCount(sig).
  // We want to temporarily copy the pointers to these object also in the stack
  // slots, because functions WasmInterpreter::RunInterpreter() and
  // WasmInterpreter::CallExternalJSFunction gets all arguments from the stack.
  // TODO(paolosev@microsoft.com) - Too slow?
  ref_stack_fp_offset += WasmBytecode::RefRetsCount(sig);
  size_t args_count = sig->parameter_count();
  sp += WasmBytecode::RetsSizeInSlots(sig) * kSlotSize;
  for (size_t i = 0; i < args_count; i++) {
    switch (sig->GetParam(i).kind()) {
      case kI32:
      case kF32:
        sp += sizeof(int32_t);
        break;
      case kI64:
      case kF64:
        sp += sizeof(int64_t);
        break;
      case kS128:
        sp += sizeof(Simd128);
        break;
      case kRef:
      case kRefNull: {
        WasmRef ref = ExtractWasmRef(ref_stack_fp_offset++);
        base::WriteUnalignedValue<WasmRef>(reinterpret_cast<Address>(sp), ref);
        sp += sizeof(WasmRef);
        break;
      }
      default:
        UNREACHABLE();
    }
  }
}
References ExtractWasmRef(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::kSlotSize, v8::internal::wasm::WasmBytecode::RefRetsCount(), v8::internal::wasm::WasmBytecode::RetsSizeInSlots(), v8::internal::sig, and v8::internal::UNREACHABLE().
Referenced by CallImportedFunction(), ExecuteCallRef(), and ExecuteIndirectCall().
StoreRefResultsIntoRefStack()
void v8::internal::wasm::WasmInterpreterRuntime::StoreRefResultsIntoRefStack (uint8_t * sp, uint32_t ref_stack_fp_offset, const FunctionSig * sig) [private]
Definition at line 1329 of file wasm-interpreter-runtime.cc.
                                                                       {
  size_t rets_count = sig->return_count();
  for (size_t i = 0; i < rets_count; i++) {
    switch (sig->GetReturn(i).kind()) {
      case kI32:
      case kF32:
        sp += sizeof(int32_t);
        break;
      case kI64:
      case kF64:
        sp += sizeof(int64_t);
        break;
      case kS128:
        sp += sizeof(Simd128);
        break;
      case kRef:
      case kRefNull:
        StoreWasmRef(ref_stack_fp_offset++, base::ReadUnalignedValue<WasmRef>(
                                                reinterpret_cast<Address>(sp)));
        base::WriteUnalignedValue<uint64_t>(reinterpret_cast<Address>(sp),
                                            kSlotsZapValue);
        sp += sizeof(WasmRef);
        break;
      default:
        UNREACHABLE();
    }
  }
}
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::kSlotsZapValue, v8::internal::sig, StoreWasmRef(), and v8::internal::UNREACHABLE().
Referenced by CallImportedFunction(), ExecuteCallRef(), and ExecuteIndirectCall().
StoreWasmRef()
void v8::internal::wasm::WasmInterpreterRuntime::StoreWasmRef (uint32_t ref_stack_index, const WasmRef & ref)
Definition at line 1203 of file wasm-interpreter-runtime.cc.
                                                              {
  uint32_t index = ref_stack_index + current_frame_.ref_array_current_sp_;
  if (ref.is_null()) {
    reference_stack()->set_the_hole(isolate_, index);
  } else {
    reference_stack()->set(index, *ref);
  }
}
References current_frame_, v8::internal::index, v8::internal::DirectHandle< T >::is_null(), isolate_, and reference_stack().
Referenced by BeginExecution(), HandleException(), InitializeRefLocalsRefs(), StoreRefResultsIntoRefStack(), UnpackException(), and UnwindCurrentStackFrame().
StructNewUninitialized()
std::pair< DirectHandle< WasmStruct >, const StructType * > v8::internal::wasm::WasmInterpreterRuntime::StructNewUninitialized (uint32_t index) const
Definition at line 2397 of file wasm-interpreter-runtime.cc.
                                                                   {
  const StructType* struct_type = module_->struct_type({index});
  DirectHandle<Map> rtt = RttCanon(index);
  return {isolate_->factory()->NewWasmStructUninitialized(struct_type, rtt),
          struct_type};
}
References v8::internal::Isolate::factory(), v8::internal::index, isolate_, module_, RttCanon(), and v8::internal::wasm::WasmModule::struct_type().
SubtypeCheck() [1/2]
bool v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck (const WasmRef obj, const ValueType obj_type, const DirectHandle< Map > rtt, const ModuleTypeIndex target_type, bool null_succeeds) const
Definition at line 2601 of file wasm-interpreter-runtime.cc.
                                                                    {
  bool is_cast_from_any = obj_type.is_reference_to(HeapType::kAny);
  // Skip the null check if casting from any and not {null_succeeds}.
  // In that case the instance type check will identify null as not being a
  // wasm object and fail.
  if (obj_type.is_nullable() && (!is_cast_from_any || null_succeeds)) {
    if (obj_type == kWasmExternRef || obj_type == kWasmNullExternRef) {
      if (i::IsNull(*obj, isolate_)) return null_succeeds;
    } else {
      if (i::IsWasmNull(*obj, isolate_)) return null_succeeds;
    }
  }
  // Add Smi check if the source type may store a Smi (i31ref or JS Smi).
  if (IsSubtypeOf(kWasmRefI31, obj_type, module_) && IsSmi(*obj)) {
    return false;
  }
  if (!IsHeapObject(*obj)) return false;
  Tagged<Map> obj_map = Cast<HeapObject>(obj)->map();
  if (module_->types[target_type.index].is_final) {
    // In this case, simply check for map equality.
    if (*obj_map != *rtt) {
      return false;
    }
  } else {
    // Check for rtt equality, and if not, check if the rtt is a struct/array
    // rtt.
    if (*obj_map == *rtt) {
      return true;
    }
    if (is_cast_from_any) {
      // Check for map being a map for a wasm object (struct, array, func).
      InstanceType obj_type1 = obj_map->instance_type();
      if (obj_type1 < FIRST_WASM_OBJECT_TYPE ||
          obj_type1 > LAST_WASM_OBJECT_TYPE) {
        return false;
      }
    }
    return SubtypeCheck(obj_map, *rtt, target_type.index);
  }
  return true;
}
References v8::internal::wasm::TypeIndex::index, v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueType::is_reference_to(), v8::internal::IsHeapObject(), v8::internal::IsNull(), isolate_, v8::internal::IsSmi(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmNullExternRef, v8::internal::wasm::kWasmRefI31, module_, and v8::internal::wasm::WasmModule::types.
Referenced by CheckIndirectCallSignature().
SubtypeCheck() [2/2]
bool v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck (Tagged< Map > rtt, Tagged< Map > formal_rtt, uint32_t type_index) const [private]
Definition at line 2577 of file wasm-interpreter-runtime.cc.
                                                                     {
  // Constant-time subtyping check: load exactly one candidate RTT from the
  // supertypes list.
  // Step 1: load the WasmTypeInfo.
  Tagged<WasmTypeInfo> type_info = rtt->wasm_type_info();
  // Step 2: check the list's length if needed.
  uint32_t rtt_depth =
      GetSubtypingDepth(module_, ModuleTypeIndex({type_index}));
  if (rtt_depth >= kMinimumSupertypeArraySize &&
      static_cast<uint32_t>(type_info->supertypes_length()) <= rtt_depth) {
    return false;
  }
  // Step 3: load the candidate list slot into {tmp1}, and compare it.
  Tagged<Object> supertype = type_info->supertypes(rtt_depth);
  if (formal_rtt != supertype) return false;
  return true;
}
References v8::internal::wasm::GetSubtypingDepth(), v8::internal::wasm::kMinimumSupertypeArraySize, and module_.
TableCopy()
void v8::internal::wasm::WasmInterpreterRuntime::TableCopy (const uint8_t *& current_code, uint32_t dst_table_index, uint32_t src_table_index, uint32_t dst, uint32_t src, uint32_t size)
Definition at line 457 of file wasm-interpreter-runtime.cc.
                                                                    {
  HandleScope scope(isolate_); // Avoid leaking handles.
  DirectHandle<WasmTrustedInstanceData> trusted_data =
      wasm_trusted_instance_data();
  auto table_dst = direct_handle(
      Cast<WasmTableObject>(trusted_data->tables()->get(dst_table_index)),
      isolate_);
  if (IsSubtypeOf(table_dst->type(module_), kWasmFuncRef, module_)) {
    PurgeIndirectCallCache(dst_table_index);
  }
  if (!WasmTrustedInstanceData::CopyTableEntries(
          isolate_, trusted_data, dst_table_index, src_table_index, dst, src,
          size)) {
    SetTrap(TrapReason::kTrapTableOutOfBounds, current_code);
  }
}
References v8::internal::WasmTrustedInstanceData::CopyTableEntries(), v8::internal::direct_handle(), isolate_, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmFuncRef, module_, PurgeIndirectCallCache(), SetTrap(), size(), and wasm_trusted_instance_data().
TableFill()
void v8::internal::wasm::WasmInterpreterRuntime::TableFill (const uint8_t *& current_code, uint32_t table_index, uint32_t count, DirectHandle< Object > value, uint32_t start)
Definition at line 499 of file wasm-interpreter-runtime.cc.
                                                       {
  // This function assumes that it is executed in a HandleScope.
  auto table = direct_handle(
      Cast<WasmTableObject>(
          wasm_trusted_instance_data()->tables()->get(table_index)),
      isolate_);
  uint32_t table_size = table->current_length();
  if (start + count < start || // Check for overflow.
      start + count > table_size) {
    SetTrap(TrapReason::kTrapTableOutOfBounds, current_code);
    return;
  }
  if (count == 0) {
    return;
  }
  WasmTableObject::Fill(isolate_, table, start, value, count);
}
References v8::internal::direct_handle(), v8::internal::WasmTableObject::Fill(), isolate_, SetTrap(), v8::internal::tables, v8::internal::value, and wasm_trusted_instance_data().
TableGet()
bool v8::internal::wasm::WasmInterpreterRuntime::TableGet (const uint8_t *& current_code, uint32_t table_index, uint32_t entry_index, DirectHandle< Object > * result)
Definition at line 390 of file wasm-interpreter-runtime.cc.
                                                                    {
  // This function assumes that it is executed in a HandleScope.
  auto table = direct_handle(
      Cast<WasmTableObject>(
          wasm_trusted_instance_data()->tables()->get(table_index)),
      isolate_);
  uint32_t table_size = table->current_length();
  if (entry_index >= table_size) {
    SetTrap(TrapReason::kTrapTableOutOfBounds, current_code);
    return false;
  }
  *result = WasmTableObject::Get(isolate_, table, entry_index);
  return true;
}
References v8::internal::direct_handle(), v8::internal::WasmTableObject::Get(), isolate_, v8::base::internal::result, SetTrap(), v8::internal::tables, and wasm_trusted_instance_data().
TableGrow()
uint32_t v8::internal::wasm::WasmInterpreterRuntime::TableGrow (uint32_t table_index, uint32_t delta, DirectHandle< Object > value)
Definition at line 479 of file wasm-interpreter-runtime.cc.
                                                                       {
  // This function assumes that it is executed in a HandleScope.
  auto table = direct_handle(
      Cast<WasmTableObject>(
          wasm_trusted_instance_data()->tables()->get(table_index)),
      isolate_);
  return WasmTableObject::Grow(isolate_, table, delta, value);
}
References v8::internal::direct_handle(), v8::internal::WasmTableObject::Grow(), isolate_, v8::internal::tables, v8::internal::value, and wasm_trusted_instance_data().
TableInit()
void v8::internal::wasm::WasmInterpreterRuntime::TableInit (const uint8_t *& current_code, uint32_t table_index, uint32_t element_segment_index, uint32_t dst, uint32_t src, uint32_t size)
Definition at line 428 of file wasm-interpreter-runtime.cc.
                                                      {
  HandleScope scope(isolate_); // Avoid leaking handles.
  DirectHandle<WasmTrustedInstanceData> trusted_data =
      wasm_trusted_instance_data();
  auto table = direct_handle(
      Cast<WasmTableObject>(trusted_data->tables()->get(table_index)),
      isolate_);
  if (IsSubtypeOf(table->type(module_), kWasmFuncRef, module_)) {
    PurgeIndirectCallCache(table_index);
  }
  std::optional<MessageTemplate> msg_template =
      WasmTrustedInstanceData::InitTableEntries(
          Isolate::Current(), trusted_data, trusted_data, table_index,
          element_segment_index, dst, src, size);
  // See WasmInstanceObject::InitTableEntries.
  if (msg_template == MessageTemplate::kWasmTrapTableOutOfBounds) {
    SetTrap(TrapReason::kTrapTableOutOfBounds, current_code);
  } else if (msg_template ==
             MessageTemplate::kWasmTrapElementSegmentOutOfBounds) {
    SetTrap(TrapReason::kTrapElementSegmentOutOfBounds, current_code);
  }
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::WasmTrustedInstanceData::InitTableEntries(), isolate_, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmFuncRef, module_, PurgeIndirectCallCache(), SetTrap(), size(), and wasm_trusted_instance_data().
TableSet()
void v8::internal::wasm::WasmInterpreterRuntime::TableSet (const uint8_t *& current_code, uint32_t table_index, uint32_t entry_index, DirectHandle< Object > ref)
Definition at line 410 of file wasm-interpreter-runtime.cc.
                                                                {
  // This function assumes that it is executed in a HandleScope.
  auto table = direct_handle(
      Cast<WasmTableObject>(
          wasm_trusted_instance_data()->tables()->get(table_index)),
      isolate_);
  uint32_t table_size = table->current_length();
  if (entry_index >= table_size) {
    SetTrap(TrapReason::kTrapTableOutOfBounds, current_code);
  } else {
    WasmTableObject::Set(isolate_, table, entry_index, ref);
  }
}
References v8::internal::direct_handle(), isolate_, v8::internal::WasmTableObject::Set(), SetTrap(), v8::internal::tables, and wasm_trusted_instance_data().
TableSize()
uint32_t v8::internal::wasm::WasmInterpreterRuntime::TableSize (uint32_t table_index)
Definition at line 490 of file wasm-interpreter-runtime.cc.
                                                               {
  HandleScope handle_scope(isolate_); // Avoid leaking handles.
  auto table = direct_handle(
      Cast<WasmTableObject>(
          wasm_trusted_instance_data()->tables()->get(table_index)),
      isolate_);
  return table->current_length();
}
References v8::internal::direct_handle(), isolate_, v8::internal::tables, and wasm_trusted_instance_data().
thread()
WasmInterpreterThread* v8::internal::wasm::WasmInterpreterRuntime::thread () const [inline], [private]
Definition at line 274 of file wasm-interpreter-runtime.h.
                                        {
    DCHECK_NOT_NULL(current_thread_);
    return current_thread_;
  }
References current_thread_, and DCHECK_NOT_NULL.
Referenced by BeginExecution(), ContinueExecution(), ExecuteCallRef(), ExecuteImportedFunction(), ExecuteIndirectCall(), reference_stack(), SetTrap(), and state().
ThrowException()
void v8::internal::wasm::WasmInterpreterRuntime::ThrowException (const uint8_t *& code, uint32_t * sp, Tagged< Object > exception_object)
Definition at line 682 of file wasm-interpreter-runtime.cc.
                                                                             {
  // Keep track of the code offset of the current instruction, which we'll need
  // to calculate the stack trace from Isolate::Throw.
  current_frame_.current_bytecode_ = code;
  DCHECK_NOT_NULL(current_thread_);
  current_thread_->SetCurrentFrame(current_frame_);
  // Now that the exception is ready, set it as pending.
  {
    wasm::ClearThreadInWasmScope clear_wasm_flag(isolate_);
    isolate_->Throw(exception_object);
    if (HandleException(sp, code) != WasmInterpreterThread::HANDLED) {
      RedirectCodeToUnwindHandler(code);
    }
  }
  DCHECK(trap_handler::IsThreadInWasm() || isolate_->has_exception());
}
References code, current_frame_, current_thread_, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::wasm::WasmInterpreterThread::HANDLED, HandleException(), v8::internal::Isolate::has_exception(), isolate_, v8::internal::trap_handler::IsThreadInWasm(), v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler(), v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), and v8::internal::Isolate::Throw().
Referenced by RethrowException().
TotalBytecodeSize()
size_t v8::internal::wasm::WasmInterpreterRuntime::TotalBytecodeSize () const [inline]
Definition at line 210 of file wasm-interpreter-runtime.h.
{ return codemap_->TotalBytecodeSize(); }
References codemap_, and v8::internal::wasm::WasmInterpreter::CodeMap::TotalBytecodeSize().
UnpackException()
void v8::internal::wasm::WasmInterpreterRuntime::UnpackException (uint32_t * sp, const WasmTag & tag, DirectHandle< Object > exception_object, uint32_t first_param_slot_index, uint32_t first_param_ref_stack_index)
Definition at line 576 of file wasm-interpreter-runtime.cc.
                                                                           {
  DirectHandle<FixedArray> encoded_values =
      Cast<FixedArray>(WasmExceptionPackage::GetExceptionValues(
          isolate_, Cast<WasmExceptionPackage>(exception_object)));
  // Decode the exception values from the given exception package and push
  // them onto the operand stack. This encoding has to be in sync with other
  // backends so that exceptions can be passed between them.
  const WasmTagSig* sig = tag.sig;
  uint32_t encoded_index = 0;
  uint32_t* p = sp + first_param_slot_index;
  for (size_t i = 0; i < sig->parameter_count(); ++i) {
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      TracePush(sig->GetParam(i).kind(), static_cast<uint32_t>(p - sp));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    WasmValue value;
    switch (sig->GetParam(i).kind()) {
      case kI32: {
        uint32_t u32 = 0;
        DecodeI32ExceptionValue(encoded_values, &encoded_index, &u32);
        base::WriteUnalignedValue<uint32_t>(reinterpret_cast<Address>(p), u32);
        p += sizeof(uint32_t) / kSlotSize;
        break;
      }
      case kF32: {
        uint32_t f32_bits = 0;
        DecodeI32ExceptionValue(encoded_values, &encoded_index, &f32_bits);
        float f32 = Float32::FromBits(f32_bits).get_scalar();
        base::WriteUnalignedValue<float>(reinterpret_cast<Address>(p), f32);
        p += sizeof(float) / kSlotSize;
        break;
      }
      case kI64: {
        uint64_t u64 = 0;
        DecodeI64ExceptionValue(encoded_values, &encoded_index, &u64);
        base::WriteUnalignedValue<uint64_t>(reinterpret_cast<Address>(p), u64);
        p += sizeof(uint64_t) / kSlotSize;
        break;
      }
      case kF64: {
        uint64_t f64_bits = 0;
        DecodeI64ExceptionValue(encoded_values, &encoded_index, &f64_bits);
        float f64 = Float64::FromBits(f64_bits).get_scalar();
        base::WriteUnalignedValue<double>(reinterpret_cast<Address>(p), f64);
        p += sizeof(double) / kSlotSize;
        break;
      }
      case kS128: {
        int32x4 s128 = {0, 0, 0, 0};
        uint32_t* vals = reinterpret_cast<uint32_t*>(s128.val);
        DecodeI32ExceptionValue(encoded_values, &encoded_index, &vals[0]);
        DecodeI32ExceptionValue(encoded_values, &encoded_index, &vals[1]);
        DecodeI32ExceptionValue(encoded_values, &encoded_index, &vals[2]);
        DecodeI32ExceptionValue(encoded_values, &encoded_index, &vals[3]);
        base::WriteUnalignedValue<Simd128>(reinterpret_cast<Address>(p),
                                           Simd128(s128));
        p += sizeof(Simd128) / kSlotSize;
        break;
      }
      case kRef:
      case kRefNull: {
        DirectHandle<Object> ref(encoded_values->get(encoded_index++),
                                 isolate_);
        if (sig->GetParam(i).value_type_code() == wasm::kFuncRefCode &&
            i::IsNull(*ref, isolate_)) {
          ref = isolate_->factory()->wasm_null();
        }
        StoreWasmRef(first_param_ref_stack_index++, ref);
        base::WriteUnalignedValue<WasmRef>(reinterpret_cast<Address>(p), ref);
        p += sizeof(WasmRef) / kSlotSize;
        break;
      }
      default:
        UNREACHABLE();
    }
  }
  DCHECK_EQ(WasmExceptionPackage::GetEncodedSize(&tag), encoded_index);
}
References DCHECK_EQ, v8::internal::DecodeI32ExceptionValue(), v8::internal::DecodeI64ExceptionValue(), v8::internal::Isolate::factory(), v8::internal::Float32::FromBits(), v8::internal::Float64::FromBits(), v8::internal::Float32::get_scalar(), v8::internal::Float64::get_scalar(), v8::internal::WasmExceptionPackage::GetEncodedSize(), v8::internal::WasmExceptionPackage::GetExceptionValues(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsNull(), isolate_, v8::internal::kF32, v8::internal::kF64, v8::internal::wasm::kFuncRefCode, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::kSlotSize, v8::internal::wasm::WasmTag::sig, v8::internal::sig, StoreWasmRef(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::value.
Referenced by HandleException().
UnwindCurrentStackFrame()
void v8::internal::wasm::WasmInterpreterRuntime::UnwindCurrentStackFrame (uint32_t * sp, uint32_t slot_offset, uint32_t rets_size, uint32_t args_size, uint32_t rets_refs, uint32_t args_refs, uint32_t ref_stack_fp_offset)
Definition at line 1224 of file wasm-interpreter-runtime.cc.
                                                                          {
  // At the moment of the call the interpreter stack is as in the diagram below.
  // A new interpreter frame for the callee function has been initialized, with
  // `R` slots to contain the R return values, followed by {args_size} slots to
  // contain the callee arguments.
  //
  // In order to unwind an interpreter stack frame we just copy the content of
  // the slots that contain the callee arguments into the caller stack frame,
  // just after the slots of the return values. Note that the return call is
  // invalid if the number and types of the return values of the callee function
  // do not exactly match the number and types of the return values of the
  // caller function. Instead, the number of types of the caller and callee
  // functions arguments can differ.
  //
  // The other slots in the caller frame, for const values and locals, will be
  // initialized later in ExecuteFunction().
  //
  // +----------------------+
  // | argA-1 | ^ ^
  // | ... | | | ->-----+
  // | ... | | | |
  // | arg0 | callee v |
  // | retR-1 | frame |
  // | ... | | |
  // | ret0 | v | copy
  // +----------------------+ (slot_offset) |
  // | ... | ^ V
  // | <stack slots> | | |
  // | <locals slots> | | |
  // | <const slots> | | ^ |
  // | argN-1 | caller | <------+
  // | ... | frame |
  // | arg0 | | v
  // | retR-1 | |
  // | ... | |
  // | ret0 | v
  // +----------------------+ (0)
  uint8_t* next_sp = reinterpret_cast<uint8_t*>(sp);
  uint8_t* prev_sp = next_sp + slot_offset;
  // Here {args_size} is the number of arguments expected by the function we are
  // calling, which can be different from the number of args of the caller
  // function.
  ::memmove(next_sp + rets_size, prev_sp, args_size);
  // If some of the argument-slots contain Ref values, we need to move them
  // accordingly, in the thread {reference_stack_}.
  if (rets_refs) {
    current_thread_->ClearRefStackValues(current_frame_.ref_array_current_sp_,
                                         rets_refs);
  }
  // Here {args_refs} is the number of reference args expected by the function
  // we are calling, which can be different from the number of reference args of
  // the caller function.
  for (uint32_t i = 0; i < args_refs; i++) {
    StoreWasmRef(rets_refs + i, ExtractWasmRef(ref_stack_fp_offset + i));
  }
  if (ref_stack_fp_offset > rets_refs + args_refs) {
    current_thread_->ClearRefStackValues(
        current_frame_.ref_array_current_sp_ + rets_refs + args_refs,
        ref_stack_fp_offset - rets_refs - args_refs);
  }
}
References v8::internal::wasm::WasmInterpreterThread::ClearRefStackValues(), current_frame_, current_thread_, ExtractWasmRef(), and StoreWasmRef().
UpdateIndirectCallTable()
void v8::internal::wasm::WasmInterpreterRuntime::UpdateIndirectCallTable (Isolate * isolate, DirectHandle< WasmInstanceObject > instance, uint32_t table_index) [static]
Definition at line 1731 of file wasm-interpreter-runtime.cc.
                          {
  DirectHandle<Tuple2> interpreter_object =
      WasmTrustedInstanceData::GetOrCreateInterpreterObject(instance);
  InterpreterHandle* handle =
      GetOrCreateInterpreterHandle(isolate, interpreter_object);
  WasmInterpreterRuntime* wasm_runtime =
      handle->interpreter()->GetWasmRuntime();
  wasm_runtime->PurgeIndirectCallCache(table_index);
}
References v8::internal::wasm::GetOrCreateInterpreterHandle(), and v8::internal::handle().
Referenced by v8::internal::WasmTableObject::Grow(), and v8::internal::WasmTableObject::UpdateDispatchTable().
UpdateMemoryAddress()
void v8::internal::wasm::WasmInterpreterRuntime::UpdateMemoryAddress (DirectHandle< WasmInstanceObject > instance) [static]
Definition at line 359 of file wasm-interpreter-runtime.cc.
                                               {
  Isolate* isolate = Isolate::Current();
  DirectHandle<Tuple2> interpreter_object =
      WasmTrustedInstanceData::GetOrCreateInterpreterObject(instance);
  InterpreterHandle* handle =
      GetOrCreateInterpreterHandle(isolate, interpreter_object);
  WasmInterpreterRuntime* wasm_runtime =
      handle->interpreter()->GetWasmRuntime();
  wasm_runtime->InitMemoryAddresses();
}
References v8::internal::Isolate::Current(), v8::internal::wasm::GetOrCreateInterpreterHandle(), and v8::internal::handle().
Referenced by v8::internal::anonymous_namespace{wasm-objects.cc}::SetInstanceMemory().
wasm_trusted_instance_data()
DirectHandle< WasmTrustedInstanceData > v8::internal::wasm::WasmInterpreterRuntime::wasm_trusted_instance_data () const [inline], [private]
Definition at line 198 of file wasm-interpreter-runtime-inl.h.
                                                         {
  return direct_handle(instance_object_->trusted_data(isolate_), isolate_);
}
References v8::internal::direct_handle(), instance_object_, and isolate_.
Referenced by AtomicNotify(), BoundsCheckMemRange(), CallImportedFunction(), CreateWasmExceptionPackage(), DataDrop(), EffectiveAddress(), ElemDrop(), ExecuteIndirectCall(), GetFunctionRef(), GetGlobalRef(), GetMemorySize(), HandleException(), I32AtomicWait(), I64AtomicWait(), InitGlobalAddressCache(), InitMemoryAddresses(), MemoryGrow(), MemoryInit(), MemorySize(), PurgeIndirectCallCache(), RttCanon(), SetGlobalRef(), TableCopy(), TableFill(), TableGet(), TableGrow(), TableInit(), TableSet(), TableSize(), WasmArrayInitSegment(), and WasmArrayNewSegment().
WasmArrayCopy()
bool v8::internal::wasm::WasmInterpreterRuntime::WasmArrayCopy (WasmRef dest_wasm_array, uint32_t dest_index, WasmRef src_wasm_array, uint32_t src_index, uint32_t length)
Definition at line 2483 of file wasm-interpreter-runtime.cc.
                                                            {
  // Call runtime function Runtime_WasmArrayCopy. Store the arguments in reverse
  // order and pass a pointer to the first argument, which is the last on the
  // stack.
  //
  // args[args_length] -> | length |
  // | src_index |
  // | src_array |
  // | dest_index |
  // first_arg_addr -> | dest_array |
  //
  constexpr size_t kArgsLength = 5;
  Address args[kArgsLength] = {IntToSmi(length), IntToSmi(src_index),
                               (*src_wasm_array).ptr(), IntToSmi(dest_index),
                               (*dest_wasm_array).ptr()};
  Address* first_arg_addr = &args[kArgsLength - 1];
  // A runtime function can throw, therefore we need to make sure that the
  // current activation is up-to-date, if we need to traverse the call stack.
  current_thread_->SetCurrentFrame(current_frame_);
  Runtime_WasmArrayCopy(kArgsLength, first_arg_addr, isolate_);
  return (!isolate_->has_exception());
}
References v8::base::args, current_frame_, current_thread_, v8::internal::Isolate::has_exception(), v8::internal::IntToSmi(), isolate_, v8::internal::length, and v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame().
WasmArrayInitSegment()
bool v8::internal::wasm::WasmInterpreterRuntime::WasmArrayInitSegment (uint32_t segment_index, WasmRef wasm_array, uint32_t array_offset, uint32_t segment_offset, uint32_t length)
Definition at line 2452 of file wasm-interpreter-runtime.cc.
                                                                   {
  // Call runtime function Runtime_WasmArrayInitSegment. Store the arguments in
  // reverse order and pass a pointer to the first argument, which is the last
  // on the stack.
  //
  // args[args_length] -> | length |
  // | segment_offset |
  // | array_offset |
  // | wasm_array |
  // | segment_index |
  // first_arg_addr -> | trusted_instance |
  //
  constexpr size_t kArgsLength = 6;
  Address args[kArgsLength] = {
      IntToSmi(length), IntToSmi(segment_offset),
      IntToSmi(array_offset), (*wasm_array).ptr(),
      IntToSmi(segment_index), wasm_trusted_instance_data()->ptr()};
  Address* first_arg_addr = &args[kArgsLength - 1];
  // A runtime function can throw, therefore we need to make sure that the
  // current activation is up-to-date, if we need to traverse the call stack.
  current_thread_->SetCurrentFrame(current_frame_);
  Runtime_WasmArrayInitSegment(kArgsLength, first_arg_addr, isolate_);
  return (!isolate_->has_exception());
}
References v8::base::args, current_frame_, current_thread_, v8::internal::Isolate::has_exception(), v8::internal::IntToSmi(), isolate_, v8::internal::length, v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), and wasm_trusted_instance_data().
WasmArrayNewSegment()
WasmRef v8::internal::wasm::WasmInterpreterRuntime::WasmArrayNewSegment (uint32_t array_index, uint32_t segment_index, uint32_t offset, uint32_t length)
Definition at line 2420 of file wasm-interpreter-runtime.cc.
                                                                     {
  DirectHandle<Map> rtt = RttCanon(array_index);
  // Call runtime function Runtime_WasmArrayNewSegment. Store the arguments in
  // reverse order and pass a pointer to the first argument, which is the last
  // on the stack.
  //
  // args[args_length] -> | rtt |
  // | length |
  // | offset |
  // | segment_index |
  // first_arg_addr -> | trusted_instance |
  //
  constexpr size_t kArgsLength = 5;
  Address args[kArgsLength] = {rtt->ptr(), IntToSmi(length), IntToSmi(offset),
                               IntToSmi(segment_index),
                               wasm_trusted_instance_data()->ptr()};
  Address* first_arg_addr = &args[kArgsLength - 1];
  // A runtime function can throw, therefore we need to make sure that the
  // current activation is up-to-date, if we need to traverse the call stack.
  current_thread_->SetCurrentFrame(current_frame_);
  Address result =
      Runtime_WasmArrayNewSegment(kArgsLength, first_arg_addr, isolate_);
  if (isolate_->has_exception()) return {};
  return direct_handle(Tagged<Object>(result), isolate_);
}
References v8::base::args, current_frame_, current_thread_, v8::internal::direct_handle(), v8::internal::Isolate::has_exception(), v8::internal::IntToSmi(), isolate_, v8::internal::length, v8::base::internal::result, RttCanon(), v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), and wasm_trusted_instance_data().
WasmJSToWasmObject()
WasmRef v8::internal::wasm::WasmInterpreterRuntime::WasmJSToWasmObject (WasmRef extern_ref, ValueType value_type, uint32_t canonical_index) const
Definition at line 2512 of file wasm-interpreter-runtime.cc.
                                                                              {
  // Call runtime function Runtime_WasmJSToWasmObject. Store the arguments in
  // reverse order and pass a pointer to the first argument, which is the last
  // on the stack.
  //
  // args[args_length] -> | value_type represent.|
  // first_arg_addr -> | extern_ref |
  //
  constexpr size_t kArgsLength = 2;
  Address args[kArgsLength] = {
      IntToSmi(value_type.raw_bit_field()), (*extern_ref).ptr()};
  Address* first_arg_addr = &args[kArgsLength - 1];
  // A runtime function can throw, therefore we need to make sure that the
  // current activation is up-to-date, if we need to traverse the call stack.
  current_thread_->SetCurrentFrame(current_frame_);
  Address result =
      Runtime_WasmJSToWasmObject(kArgsLength, first_arg_addr, isolate_);
  if (isolate_->has_exception()) return {};
  return direct_handle(Tagged<Object>(result), isolate_);
}
References v8::base::args, current_frame_, current_thread_, v8::internal::direct_handle(), v8::internal::Isolate::has_exception(), v8::internal::IntToSmi(), isolate_, v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::base::internal::result, v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), and v8::internal::wasm::value_type().
WasmStackCheck()
bool v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck (const uint8_t * current_bytecode, const uint8_t *& code) [inline]
Definition at line 156 of file wasm-interpreter-runtime-inl.h.
                                                           {
  StackLimitCheck stack_check(isolate_);
  current_frame_.current_bytecode_ = current_bytecode;
  current_thread_->SetCurrentFrame(current_frame_);
  if (stack_check.InterruptRequested()) {
    if (stack_check.HasOverflowed()) {
      ClearThreadInWasmScope clear_wasm_flag(isolate_);
      SealHandleScope shs(isolate_);
      current_frame_.current_function_ = nullptr;
      SetTrap(TrapReason::kTrapUnreachable, code);
      isolate_->StackOverflow();
      return false;
    }
    if (isolate_->stack_guard()->HasTerminationRequest()) {
      ClearThreadInWasmScope clear_wasm_flag(isolate_);
      SealHandleScope shs(isolate_);
      current_frame_.current_function_ = nullptr;
      SetTrap(TrapReason::kTrapUnreachable, code);
      isolate_->TerminateExecution();
      return false;
    }
    isolate_->stack_guard()->HandleInterrupts();
  }
  if (V8_UNLIKELY(v8_flags.drumbrake_fuzzer_timeout &&
                  base::TimeTicks::Now() - fuzzer_start_time_ >
                      base::TimeDelta::FromMilliseconds(
                          v8_flags.drumbrake_fuzzer_timeout_limit_ms))) {
    ClearThreadInWasmScope clear_wasm_flag(isolate_);
    SealHandleScope shs(isolate_);
    current_frame_.current_function_ = nullptr;
    SetTrap(TrapReason::kTrapUnreachable, code);
    return false;
  }
  return true;
}
References code, current_frame_, current_thread_, v8::base::TimeDelta::FromMilliseconds(), fuzzer_start_time_, v8::internal::StackGuard::HandleInterrupts(), v8::internal::StackLimitCheck::HasOverflowed(), v8::internal::StackGuard::HasTerminationRequest(), v8::internal::StackLimitCheck::InterruptRequested(), isolate_, v8::base::TimeTicks::Now(), v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame(), SetTrap(), v8::internal::Isolate::stack_guard(), v8::internal::Isolate::StackOverflow(), v8::internal::Isolate::TerminateExecution(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by ExecuteFunction(), and PrepareTailCall().
WasmToJSObject()
WasmRef v8::internal::wasm::WasmInterpreterRuntime::WasmToJSObject (WasmRef ref) const
Definition at line 2559 of file wasm-interpreter-runtime.cc.
                                                                  {
  if (IsWasmFuncRef(*value)) {
    value =
        direct_handle(Cast<WasmFuncRef>(*value)->internal(isolate_), isolate_);
  }
  if (IsWasmInternalFunction(*value)) {
    DirectHandle<WasmInternalFunction> internal =
        Cast<WasmInternalFunction>(value);
    return WasmInternalFunction::GetOrCreateExternal(internal);
  }
  if (IsWasmNull(*value)) {
    return direct_handle(ReadOnlyRoots(isolate_).null_value(), isolate_);
  }
  return value;
}
References v8::internal::direct_handle(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), isolate_, and v8::internal::value.
Referenced by CallExternalJSFunction(), and ContinueExecution().
Member Data Documentation
codemap_
WasmInterpreter::CodeMap* v8::internal::wasm::WasmInterpreterRuntime::codemap_ [private]
Definition at line 293 of file wasm-interpreter-runtime.h.
Referenced by GetFunctionBytecode(), and TotalBytecodeSize().
current_frame_
FrameState v8::internal::wasm::WasmInterpreterRuntime::current_frame_ [private]
Definition at line 296 of file wasm-interpreter-runtime.h.
Referenced by BeginExecution(), ContinueExecution(), ExecuteCallRef(), ExecuteFunction(), ExecuteImportedFunction(), ExecuteIndirectCall(), ExtractWasmRef(), HandleException(), I32AtomicWait(), I64AtomicWait(), PrepareTailCall(), PrintStack(), ResetCurrentHandleScope(), RethrowException(), SetTrap(), StoreWasmRef(), ThrowException(), UnwindCurrentStackFrame(), WasmArrayCopy(), WasmArrayInitSegment(), WasmArrayNewSegment(), WasmJSToWasmObject(), and WasmStackCheck().
current_thread_
WasmInterpreterThread* v8::internal::wasm::WasmInterpreterRuntime::current_thread_ [private]
Definition at line 302 of file wasm-interpreter-runtime.h.
Referenced by BeginExecution(), CallExternalJSFunction(), CallWasmToJSBuiltin(), ContinueExecution(), ExecuteFunction(), GetFunctionIndex(), GetInterpretedStack(), HandleException(), I32AtomicWait(), I64AtomicWait(), PrepareTailCall(), thread(), ThrowException(), UnwindCurrentStackFrame(), WasmArrayCopy(), WasmArrayInitSegment(), WasmArrayNewSegment(), WasmJSToWasmObject(), and WasmStackCheck().
function_result_
std::vector<WasmValue> v8::internal::wasm::WasmInterpreterRuntime::function_result_ [private]
Definition at line 297 of file wasm-interpreter-runtime.h.
Referenced by ContinueExecution(), and GetReturnValue().
fuzzer_start_time_
base::TimeTicks v8::internal::wasm::WasmInterpreterRuntime::fuzzer_start_time_ [private]
Definition at line 304 of file wasm-interpreter-runtime.h.
Referenced by WasmStackCheck().
generic_wasm_to_js_interpreter_wrapper_fn_
GeneratedCode<WasmToJSCallSig> v8::internal::wasm::WasmInterpreterRuntime::generic_wasm_to_js_interpreter_wrapper_fn_ [private]
Definition at line 357 of file wasm-interpreter-runtime.h.
Referenced by CallWasmToJSBuiltin().
global_addresses_
std::vector<uint8_t*> v8::internal::wasm::WasmInterpreterRuntime::global_addresses_ [private]
Definition at line 317 of file wasm-interpreter-runtime.h.
Referenced by GetGlobalAddress(), and InitGlobalAddressCache().
indirect_call_tables_
std::vector<IndirectCallTable> v8::internal::wasm::WasmInterpreterRuntime::indirect_call_tables_ [private]
Definition at line 350 of file wasm-interpreter-runtime.h.
Referenced by CheckIndirectCallSignature(), ExecuteIndirectCall(), InitIndirectFunctionTables(), and PurgeIndirectCallCache().
instance_object_
IndirectHandle<WasmInstanceObject> v8::internal::wasm::WasmInterpreterRuntime::instance_object_ [private]
Definition at line 292 of file wasm-interpreter-runtime.h.
Referenced by ExecuteIndirectCall(), and wasm_trusted_instance_data().
instruction_table_
PWasmOp* const* v8::internal::wasm::WasmInterpreterRuntime::instruction_table_ [private]
Definition at line 312 of file wasm-interpreter-runtime.h.
Referenced by instruction_table_offset().
isolate_
Isolate* v8::internal::wasm::WasmInterpreterRuntime::isolate_ [private]
Definition at line 290 of file wasm-interpreter-runtime.h.
Referenced by AllowsAtomicsWait(), ArrayNewUninitialized(), AtomicNotify(), BeginExecution(), CallExternalJSFunction(), CallImportedFunction(), CallWasmToJSBuiltin(), CheckIndirectCallSignature(), ContinueExecution(), CreateWasmExceptionPackage(), ElemDrop(), ExecuteCallRef(), ExecuteFunction(), ExecuteIndirectCall(), ExtractWasmRef(), GetFunctionRef(), GetGlobalRef(), GetIsolate(), GetNullValue(), GetWasmArrayRefElement(), HandleException(), I32AtomicWait(), I64AtomicWait(), InitializeRefLocalsRefs(), IsNullTypecheck(), IsRefNull(), JSToWasmObject(), MemoryGrow(), PrepareTailCall(), RefIsArray(), RefIsEq(), RefIsI31(), RefIsString(), RefIsStruct(), ResetCurrentHandleScope(), RethrowException(), RttCanon(), StoreWasmRef(), StructNewUninitialized(), SubtypeCheck(), TableCopy(), TableFill(), TableGet(), TableGrow(), TableInit(), TableSet(), TableSize(), ThrowException(), UnpackException(), wasm_trusted_instance_data(), WasmArrayCopy(), WasmArrayInitSegment(), WasmArrayNewSegment(), WasmJSToWasmObject(), WasmStackCheck(), and WasmToJSObject().
memory_start_
uint8_t* v8::internal::wasm::WasmInterpreterRuntime::memory_start_ [private]
Definition at line 306 of file wasm-interpreter-runtime.h.
Referenced by GetMemoryStart(), InitMemoryAddresses(), and memory_start_offset().
module_
const WasmModule* v8::internal::wasm::WasmInterpreterRuntime::module_ [private]
Definition at line 291 of file wasm-interpreter-runtime.h.
Referenced by AllowsAtomicsWait(), AtomicNotify(), BeginExecution(), CallImportedFunction(), CheckIndirectCallSignature(), ContinueExecution(), ExecuteCallRef(), ExecuteIndirectCall(), GetArrayType(), GetGlobalAddress(), GetGlobalRef(), GetWasmTag(), HandleException(), InitGlobalAddressCache(), InitIndirectFunctionTables(), IsMemory64(), JSToWasmObject(), PurgeIndirectCallCache(), SetGlobalRef(), SetTrap(), StructNewUninitialized(), SubtypeCheck(), TableCopy(), and TableInit().
start_function_index_
uint32_t v8::internal::wasm::WasmInterpreterRuntime::start_function_index_ [private]
Definition at line 295 of file wasm-interpreter-runtime.h.
Referenced by BeginExecution(), ContinueExecution(), and GetInterpretedStack().
trap_function_index_
int v8::internal::wasm::WasmInterpreterRuntime::trap_function_index_ [private]
Definition at line 299 of file wasm-interpreter-runtime.h.
Referenced by GetInterpretedStack(), SetTrap(), and SetTrapFunctionIndex().
trap_pc_
pc_t v8::internal::wasm::WasmInterpreterRuntime::trap_pc_ [private]
Definition at line 300 of file wasm-interpreter-runtime.h.
Referenced by GetInterpretedStack(), SetTrap(), and SetTrapFunctionIndex().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-runtime.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-runtime-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-runtime.cc