v8::internal::ExternalReferenceTable Class Reference
#include <external-reference-table.h>
Public Member Functions
Address address (uint32_t i) const
const char * name (uint32_t i) const
bool is_initialized () const
const char * NameFromOffset (uint32_t offset)
ExternalReferenceTable ()=default
ExternalReferenceTable (const ExternalReferenceTable &)=delete
ExternalReferenceTable & operator= (const ExternalReferenceTable &)=delete
void InitIsolateIndependent (MemorySpan< Address > shared_external_references)
void Init (Isolate *isolate)
Static Public Member Functions
static const char * ResolveSymbol (void *address)
static constexpr uint32_t OffsetOfEntry (uint32_t i)
static void InitializeOncePerIsolateGroup (MemorySpan< Address > shared_external_references)
static const char * NameOfIsolateIndependentAddress (Address address, MemorySpan< Address > shared_external_references)
Static Public Attributes
static constexpr int kSpecialReferenceCount = 1
static constexpr int kExternalReferenceCountIsolateIndependent
static constexpr int kExternalReferenceCountIsolateDependent
static constexpr int kBuiltinsReferenceCount
static constexpr int kRuntimeReferenceCount
static constexpr int kIsolateAddressReferenceCount = kIsolateAddressCount
static constexpr int kAccessorReferenceCount
static constexpr int kStubCacheReferenceCount = 6 * 3
static constexpr int kStatsCountersReferenceCount
static constexpr int kSizeIsolateIndependent
static constexpr int kSize
static constexpr uint32_t kEntrySize
static constexpr uint32_t kSizeInBytes = kSize * kEntrySize + 2 * kUInt32Size
Private Types
enum InitializationState : uint32_t { kUninitialized
, kInitializedIsolateIndependent
, kInitialized
 }
Private Member Functions
void Add (Address address, int *index)
void CopyIsolateIndependentReferences (int *index, MemorySpan< Address > shared_external_references)
void AddIsolateDependentReferences (Isolate *isolate, int *index)
void AddIsolateAddresses (Isolate *isolate, int *index)
void AddStubCache (Isolate *isolate, int *index)
Address GetStatsCounterAddress (StatsCounter *counter)
void AddNativeCodeStatsCounters (Isolate *isolate, int *index)
Static Private Member Functions
static void AddIsolateIndependent (Address address, int *index, MemorySpan< Address > shared_external_references)
static void AddIsolateIndependentReferences (int *index, MemorySpan< Address > shared_external_references)
static void AddBuiltins (int *index, MemorySpan< Address > shared_external_references)
static void AddRuntimeFunctions (int *index, MemorySpan< Address > shared_external_references)
static void AddAccessors (int *index, MemorySpan< Address > shared_external_references)
Private Attributes
Address ref_addr_ [kSize]
InitializationState is_initialized_ = kUninitialized
uint32_t dummy_stats_counter_ = 0
Static Private Attributes
static const char *const ref_name_ [kSize]
Detailed Description
Definition at line 22 of file external-reference-table.h.
Member Enumeration Documentation
InitializationState
enum v8::internal::ExternalReferenceTable::InitializationState : uint32_t [private]
Enumerator
kUninitialized
kInitializedIsolateIndependent
kInitialized
Definition at line 125 of file external-reference-table.h.
                           : uint32_t {
    kUninitialized,
    kInitializedIsolateIndependent,
    kInitialized,
  };
Constructor & Destructor Documentation
ExternalReferenceTable() [1/2]
v8::internal::ExternalReferenceTable::ExternalReferenceTable () [default]
ExternalReferenceTable() [2/2]
v8::internal::ExternalReferenceTable::ExternalReferenceTable (const ExternalReferenceTable &) [delete]
Member Function Documentation
Add()
void v8::internal::ExternalReferenceTable::Add (Address address, int * index) [private]
Definition at line 155 of file external-reference-table.cc.
                                                            {
  ref_addr_[(*index)++] = address;
}
References address(), and ref_addr_.
Referenced by AddIsolateAddresses(), and AddStubCache().
AddAccessors()
void v8::internal::ExternalReferenceTable::AddAccessors (int * index, MemorySpan< Address > shared_external_references) [static], [private]
Definition at line 263 of file external-reference-table.cc.
                                                                {
  CHECK_EQ(kSpecialReferenceCount + kExternalReferenceCountIsolateIndependent +
               kBuiltinsReferenceCount + kRuntimeReferenceCount,
           *index);
#define ACCESSOR_INFO_DECLARATION(_, __, AccessorName, ...) \
  FUNCTION_ADDR(&Accessors::AccessorName##Getter),
#define ACCESSOR_GETTER_DECLARATION(name) FUNCTION_ADDR(&Accessors::name),
#define ACCESSOR_SETTER_DECLARATION(name) FUNCTION_ADDR(&Accessors::name),
#define ACCESSOR_CALLBACK_DECLARATION(_, AccessorName, ...) \
  FUNCTION_ADDR(&Accessors::AccessorName),
  static const Address accessors[] = {
      // Getters:
      ACCESSOR_INFO_LIST_GENERATOR(ACCESSOR_INFO_DECLARATION, /* not used */)
      // More getters:
      ACCESSOR_GETTER_LIST(ACCESSOR_GETTER_DECLARATION)
      // Setters:
      ACCESSOR_SETTER_LIST(ACCESSOR_SETTER_DECLARATION)
      // Callbacks:
      ACCESSOR_CALLBACK_LIST_GENERATOR(ACCESSOR_CALLBACK_DECLARATION,
                                       /* not used */)};
#undef ACCESSOR_INFO_DECLARATION
#undef ACCESSOR_GETTER_DECLARATION
#undef ACCESSOR_SETTER_DECLARATION
#undef ACCESSOR_CALLBACK_DECLARATION
  for (Address addr : accessors) {
    AddIsolateIndependent(addr, index, shared_external_references);
  }
  CHECK_EQ(kSpecialReferenceCount + kExternalReferenceCountIsolateIndependent +
               kBuiltinsReferenceCount + kRuntimeReferenceCount +
               kAccessorReferenceCount,
           *index);
}
References ACCESSOR_CALLBACK_DECLARATION, ACCESSOR_CALLBACK_LIST_GENERATOR, ACCESSOR_GETTER_DECLARATION, ACCESSOR_GETTER_LIST, ACCESSOR_INFO_DECLARATION, ACCESSOR_INFO_LIST_GENERATOR, ACCESSOR_SETTER_DECLARATION, ACCESSOR_SETTER_LIST, AddIsolateIndependent(), CHECK_EQ, v8::internal::index, kAccessorReferenceCount, kBuiltinsReferenceCount, kExternalReferenceCountIsolateIndependent, kRuntimeReferenceCount, and kSpecialReferenceCount.
Referenced by InitializeOncePerIsolateGroup().
AddBuiltins()
void v8::internal::ExternalReferenceTable::AddBuiltins (int * index, MemorySpan< Address > shared_external_references) [static], [private]
Definition at line 195 of file external-reference-table.cc.
                                                                {
  CHECK_EQ(kSpecialReferenceCount + kExternalReferenceCountIsolateIndependent,
           *index);
  static const Address c_builtins[] = {
#define DEF_ENTRY(Name, ...) FUNCTION_ADDR(&Builtin_##Name),
      BUILTIN_LIST_C(DEF_ENTRY)
#undef DEF_ENTRY
  };
  for (Address addr : c_builtins) {
    AddIsolateIndependent(ExternalReference::Create(addr).address(), index,
                          shared_external_references);
  }
  CHECK_EQ(kSpecialReferenceCount + kExternalReferenceCountIsolateIndependent +
               kBuiltinsReferenceCount,
           *index);
}
References AddIsolateIndependent(), address(), BUILTIN_LIST_C, CHECK_EQ, v8::internal::ExternalReference::Create(), DEF_ENTRY, v8::internal::index, kBuiltinsReferenceCount, kExternalReferenceCountIsolateIndependent, and kSpecialReferenceCount.
Referenced by InitializeOncePerIsolateGroup().
AddIsolateAddresses()
void v8::internal::ExternalReferenceTable::AddIsolateAddresses (Isolate * isolate, int * index) [private]
Definition at line 249 of file external-reference-table.cc.
                                                                             {
  CHECK_EQ(kSizeIsolateIndependent + kExternalReferenceCountIsolateDependent,
           *index);
  for (int i = 0; i < IsolateAddressId::kIsolateAddressCount; ++i) {
    Add(isolate->get_address_from_id(static_cast<IsolateAddressId>(i)), index);
  }
  CHECK_EQ(kSizeIsolateIndependent + kExternalReferenceCountIsolateDependent +
               kIsolateAddressReferenceCount,
           *index);
}
References Add(), CHECK_EQ, v8::internal::Isolate::get_address_from_id(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, kExternalReferenceCountIsolateDependent, v8::internal::kIsolateAddressCount, kIsolateAddressReferenceCount, and kSizeIsolateIndependent.
Referenced by Init().
AddIsolateDependentReferences()
void v8::internal::ExternalReferenceTable::AddIsolateDependentReferences (Isolate * isolate, int * index) [private]
Definition at line 181 of file external-reference-table.cc.
                                                                       {
  CHECK_EQ(kSizeIsolateIndependent, *index);
#define ADD_EXTERNAL_REFERENCE(name, desc) \
  Add(ExternalReference::name(isolate).address(), index);
  EXTERNAL_REFERENCE_LIST_WITH_ISOLATE(ADD_EXTERNAL_REFERENCE)
#undef ADD_EXTERNAL_REFERENCE
  CHECK_EQ(kSizeIsolateIndependent + kExternalReferenceCountIsolateDependent,
           *index);
}
References ADD_EXTERNAL_REFERENCE, CHECK_EQ, EXTERNAL_REFERENCE_LIST_WITH_ISOLATE, v8::internal::index, kExternalReferenceCountIsolateDependent, and kSizeIsolateIndependent.
Referenced by Init().
AddIsolateIndependent()
void v8::internal::ExternalReferenceTable::AddIsolateIndependent (Address address, int * index, MemorySpan< Address > shared_external_references) [static], [private]
Definition at line 160 of file external-reference-table.cc.
                                                    {
  shared_external_references[(*index)++] = address;
}
References address().
Referenced by AddAccessors(), AddBuiltins(), AddRuntimeFunctions(), and InitializeOncePerIsolateGroup().
AddIsolateIndependentReferences()
void v8::internal::ExternalReferenceTable::AddIsolateIndependentReferences (int * index, MemorySpan< Address > shared_external_references) [static], [private]
Definition at line 167 of file external-reference-table.cc.
                                                                {
  CHECK_EQ(kSpecialReferenceCount, *index);
#define ADD_EXTERNAL_REFERENCE(name, desc) \
  AddIsolateIndependent(ExternalReference::name().address(), index, \
                        shared_external_references);
  EXTERNAL_REFERENCE_LIST(ADD_EXTERNAL_REFERENCE)
#undef ADD_EXTERNAL_REFERENCE
  CHECK_EQ(kSpecialReferenceCount + kExternalReferenceCountIsolateIndependent,
           *index);
}
References ADD_EXTERNAL_REFERENCE, CHECK_EQ, EXTERNAL_REFERENCE_LIST, v8::internal::index, kExternalReferenceCountIsolateIndependent, and kSpecialReferenceCount.
Referenced by InitializeOncePerIsolateGroup().
AddNativeCodeStatsCounters()
void v8::internal::ExternalReferenceTable::AddNativeCodeStatsCounters (Isolate * isolate, int * index) [private]
Definition at line 334 of file external-reference-table.cc.
                                                                    {
  CHECK_EQ(kSizeIsolateIndependent + kExternalReferenceCountIsolateDependent +
               kIsolateAddressReferenceCount + kStubCacheReferenceCount,
           *index);
  Counters* counters = isolate->counters();
#define SC(name, caption) Add(GetStatsCounterAddress(counters->name()), index);
  STATS_COUNTER_NATIVE_CODE_LIST(SC)
#undef SC
  CHECK_EQ(kSizeIsolateIndependent + kExternalReferenceCountIsolateDependent +
               kIsolateAddressReferenceCount + kStubCacheReferenceCount +
               kStatsCountersReferenceCount,
           *index);
  CHECK_EQ(kSize, *index);
}
References CHECK_EQ, v8::internal::Isolate::counters(), v8::internal::index, kExternalReferenceCountIsolateDependent, kIsolateAddressReferenceCount, kSize, kSizeIsolateIndependent, kStatsCountersReferenceCount, kStubCacheReferenceCount, v8::internal::SC, and STATS_COUNTER_NATIVE_CODE_LIST.
Referenced by Init().
address()
Address v8::internal::ExternalReferenceTable::address (uint32_t i) const [inline]
Definition at line 59 of file external-reference-table.h.
{ return ref_addr_[i]; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and ref_addr_.
Referenced by Add(), AddBuiltins(), AddIsolateIndependent(), AddRuntimeFunctions(), v8::internal::StartupDeserializer::DeserializeAndCheckExternalReferenceTable(), v8::internal::ExternalReferenceEncoder::ExternalReferenceEncoder(), v8::internal::ObjectPostProcessor::GetAnyExternalReferenceAt(), GetStatsCounterAddress(), NameOfIsolateIndependentAddress(), ResolveSymbol(), and v8::internal::StartupSerializer::StartupSerializer().
AddRuntimeFunctions()
void v8::internal::ExternalReferenceTable::AddRuntimeFunctions (int * index, MemorySpan< Address > shared_external_references) [static], [private]
Definition at line 216 of file external-reference-table.cc.
                                                                {
  CHECK_EQ(kSpecialReferenceCount + kExternalReferenceCountIsolateIndependent +
               kBuiltinsReferenceCount,
           *index);
  static constexpr Runtime::FunctionId runtime_functions[] = {
#define RUNTIME_ENTRY(name, ...) Runtime::k##name,
      FOR_EACH_INTRINSIC(RUNTIME_ENTRY)
#undef RUNTIME_ENTRY
  };
  for (Runtime::FunctionId fId : runtime_functions) {
    AddIsolateIndependent(ExternalReference::Create(fId).address(), index,
                          shared_external_references);
  }
  CHECK_EQ(kSpecialReferenceCount + kExternalReferenceCountIsolateIndependent +
               kBuiltinsReferenceCount + kRuntimeReferenceCount,
           *index);
}
References AddIsolateIndependent(), address(), CHECK_EQ, v8::internal::ExternalReference::Create(), FOR_EACH_INTRINSIC, v8::internal::index, kBuiltinsReferenceCount, kExternalReferenceCountIsolateIndependent, kRuntimeReferenceCount, kSpecialReferenceCount, and RUNTIME_ENTRY.
Referenced by InitializeOncePerIsolateGroup().
AddStubCache()
void v8::internal::ExternalReferenceTable::AddStubCache (Isolate * isolate, int * index) [private]
Definition at line 301 of file external-reference-table.cc.
                                                                      {
  CHECK_EQ(kSizeIsolateIndependent + kExternalReferenceCountIsolateDependent +
               kIsolateAddressReferenceCount,
           *index);
  // Stub cache tables
  std::array<StubCache*, 3> stub_caches{isolate->load_stub_cache(),
                                        isolate->store_stub_cache(),
                                        isolate->define_own_stub_cache()};
  for (StubCache* stub_cache : stub_caches) {
    Add(stub_cache->key_reference(StubCache::kPrimary).address(), index);
    Add(stub_cache->value_reference(StubCache::kPrimary).address(), index);
    Add(stub_cache->map_reference(StubCache::kPrimary).address(), index);
    Add(stub_cache->key_reference(StubCache::kSecondary).address(), index);
    Add(stub_cache->value_reference(StubCache::kSecondary).address(), index);
    Add(stub_cache->map_reference(StubCache::kSecondary).address(), index);
  }
  CHECK_EQ(kSizeIsolateIndependent + kExternalReferenceCountIsolateDependent +
               kIsolateAddressReferenceCount + kStubCacheReferenceCount,
           *index);
}
References Add(), CHECK_EQ, v8::internal::Isolate::define_own_stub_cache(), v8::internal::index, kExternalReferenceCountIsolateDependent, kIsolateAddressReferenceCount, v8::internal::StubCache::kPrimary, v8::internal::StubCache::kSecondary, kSizeIsolateIndependent, kStubCacheReferenceCount, v8::internal::Isolate::load_stub_cache(), and v8::internal::Isolate::store_stub_cache().
Referenced by Init().
CopyIsolateIndependentReferences()
void v8::internal::ExternalReferenceTable::CopyIsolateIndependentReferences (int * index, MemorySpan< Address > shared_external_references) [private]
Definition at line 238 of file external-reference-table.cc.
                                                                {
  CHECK_EQ(0, *index);
  DCHECK_GE(shared_external_references.size(), kSizeIsolateIndependent);
  std::copy(shared_external_references.data(),
            shared_external_references.data() + kSizeIsolateIndependent,
            ref_addr_);
  *index += kSizeIsolateIndependent;
}
References CHECK_EQ, v8::MemorySpan< T >::data(), DCHECK_GE, v8::internal::index, kSizeIsolateIndependent, ref_addr_, and v8::MemorySpan< T >::size().
Referenced by InitIsolateIndependent().
GetStatsCounterAddress()
Address v8::internal::ExternalReferenceTable::GetStatsCounterAddress (StatsCounter * counter) [private]
Definition at line 325 of file external-reference-table.cc.
                                                                            {
  if (!counter->Enabled()) {
    return reinterpret_cast<Address>(&dummy_stats_counter_);
  }
  std::atomic<int>* address = counter->GetInternalPointer();
  static_assert(sizeof(address) == sizeof(Address));
  return reinterpret_cast<Address>(address);
}
References address(), dummy_stats_counter_, v8::internal::StatsCounter::Enabled(), and v8::internal::StatsCounter::GetInternalPointer().
Init()
void v8::internal::ExternalReferenceTable::Init (Isolate * isolate)
Definition at line 103 of file external-reference-table.cc.
                                                  {
  DCHECK_EQ(is_initialized_, kInitializedIsolateIndependent);
  int index = kSizeIsolateIndependent;
  AddIsolateDependentReferences(isolate, &index);
  AddIsolateAddresses(isolate, &index);
  AddStubCache(isolate, &index);
  AddNativeCodeStatsCounters(isolate, &index);
  CHECK_EQ(kSize, index);
  is_initialized_ = kInitialized;
}
References AddIsolateAddresses(), AddIsolateDependentReferences(), AddNativeCodeStatsCounters(), AddStubCache(), CHECK_EQ, DCHECK_EQ, v8::internal::index, is_initialized_, kInitialized, kInitializedIsolateIndependent, kSize, and kSizeIsolateIndependent.
Referenced by v8::internal::Isolate::Init().
InitializeOncePerIsolateGroup()
void v8::internal::ExternalReferenceTable::InitializeOncePerIsolateGroup (MemorySpan< Address > shared_external_references) [static]
Definition at line 130 of file external-reference-table.cc.
                                                    {
  int index = 0;
  // kNullAddress is preserved through serialization/deserialization.
  AddIsolateIndependent(kNullAddress, &index, shared_external_references);
  AddIsolateIndependentReferences(&index, shared_external_references);
  AddBuiltins(&index, shared_external_references);
  AddRuntimeFunctions(&index, shared_external_references);
  AddAccessors(&index, shared_external_references);
  CHECK_EQ(kSizeIsolateIndependent, index);
}
References AddAccessors(), AddBuiltins(), AddIsolateIndependent(), AddIsolateIndependentReferences(), AddRuntimeFunctions(), CHECK_EQ, v8::internal::index, v8::internal::kNullAddress, and kSizeIsolateIndependent.
Referenced by v8::internal::V8::Initialize(), and v8::internal::IsolateGroup::New().
InitIsolateIndependent()
void v8::internal::ExternalReferenceTable::InitIsolateIndependent (MemorySpan< Address > shared_external_references)
Definition at line 92 of file external-reference-table.cc.
                                                    {
  DCHECK_EQ(is_initialized_, kUninitialized);
  int index = 0;
  CopyIsolateIndependentReferences(&index, shared_external_references);
  CHECK_EQ(kSizeIsolateIndependent, index);
  is_initialized_ = kInitializedIsolateIndependent;
}
References CHECK_EQ, CopyIsolateIndependentReferences(), DCHECK_EQ, v8::internal::index, is_initialized_, kInitializedIsolateIndependent, kSizeIsolateIndependent, and kUninitialized.
Referenced by v8::internal::Isolate::Init().
is_initialized()
bool v8::internal::ExternalReferenceTable::is_initialized () const [inline]
Definition at line 62 of file external-reference-table.h.
{ return is_initialized_ == kInitialized; }
References is_initialized_, and kInitialized.
name()
const char* v8::internal::ExternalReferenceTable::name (uint32_t i) const [inline]
Definition at line 60 of file external-reference-table.h.
{ return ref_name_[i]; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and ref_name_.
Referenced by NameFromOffset(), v8::internal::ExternalReferenceEncoder::NameOfAddress(), and ResolveSymbol().
NameFromOffset()
const char* v8::internal::ExternalReferenceTable::NameFromOffset (uint32_t offset) [inline]
Definition at line 76 of file external-reference-table.h.
                                              {
    DCHECK_EQ(offset % kEntrySize, 0);
    DCHECK_LT(offset, kSizeInBytes);
    int index = offset / kEntrySize;
    return name(index);
  }
References DCHECK_EQ, DCHECK_LT, v8::internal::index, kEntrySize, kSizeInBytes, and name().
NameOfIsolateIndependentAddress()
const char * v8::internal::ExternalReferenceTable::NameOfIsolateIndependentAddress (Address address, MemorySpan< Address > shared_external_references) [static]
Definition at line 145 of file external-reference-table.cc.
                                                                     {
  for (int i = 0; i < kSizeIsolateIndependent; i++) {
    if (shared_external_references[i] == address) {
      return ref_name_[i];
    }
  }
  return "<unknown>";
}
References address(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kSizeIsolateIndependent, and ref_name_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCall(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCallWithStackBuffer().
OffsetOfEntry()
static constexpr uint32_t v8::internal::ExternalReferenceTable::OffsetOfEntry (uint32_t i) [inline], [static], [constexpr]
Definition at line 66 of file external-reference-table.h.
                                                      {
    // Used in CodeAssembler::LookupExternalReference.
    return i * kEntrySize;
  }
References kEntrySize.
Referenced by v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReferenceTableEntry().
operator=()
ExternalReferenceTable& v8::internal::ExternalReferenceTable::operator= (const ExternalReferenceTable &) [delete]
ResolveSymbol()
const char * v8::internal::ExternalReferenceTable::ResolveSymbol (void * address) [static]
Definition at line 116 of file external-reference-table.cc.
                                                               {
#ifdef SYMBOLIZE_FUNCTION
  char** names = backtrace_symbols(&address, 1);
  const char* name = names[0];
  // The array of names is malloc'ed. However, each name string is static
  // and do not need to be freed.
  base::Free(names);
  return name;
#else
  return "<unresolved>";
#endif // SYMBOLIZE_FUNCTION
}
References address(), v8::base::Free(), and name().
Referenced by v8::internal::ExternalReferenceEncoder::Encode(), and v8::internal::Serializer::EncodeExternalReference().
Member Data Documentation
dummy_stats_counter_
uint32_t v8::internal::ExternalReferenceTable::dummy_stats_counter_ = 0 [private]
Definition at line 137 of file external-reference-table.h.
Referenced by GetStatsCounterAddress().
is_initialized_
InitializationState v8::internal::ExternalReferenceTable::is_initialized_ = kUninitialized [private]
Definition at line 130 of file external-reference-table.h.
Referenced by Init(), InitIsolateIndependent(), and is_initialized().
kAccessorReferenceCount
constexpr int v8::internal::ExternalReferenceTable::kAccessorReferenceCount [static], [constexpr]
Initial value:
=
      Accessors::kAccessorInfoCount + Accessors::kAccessorGetterCount +
      Accessors::kAccessorSetterCount + Accessors::kAccessorCallbackCount
Definition at line 38 of file external-reference-table.h.
Referenced by AddAccessors().
kBuiltinsReferenceCount
constexpr int v8::internal::ExternalReferenceTable::kBuiltinsReferenceCount [static], [constexpr]
Initial value:
=
#define COUNT_C_BUILTIN(...)
      BUILTIN_LIST_C(COUNT_C_BUILTIN)
Definition at line 30 of file external-reference-table.h.
Referenced by AddAccessors(), AddBuiltins(), and AddRuntimeFunctions().
kEntrySize
constexpr uint32_t v8::internal::ExternalReferenceTable::kEntrySize [static], [constexpr]
Initial value:
=
      static_cast<uint32_t>(kSystemPointerSize)
Definition at line 55 of file external-reference-table.h.
Referenced by NameFromOffset(), and OffsetOfEntry().
kExternalReferenceCountIsolateDependent
constexpr int v8::internal::ExternalReferenceTable::kExternalReferenceCountIsolateDependent [static], [constexpr]
Initial value:
=
      ExternalReference::kExternalReferenceCountIsolateDependent
Definition at line 28 of file external-reference-table.h.
Referenced by AddIsolateAddresses(), AddIsolateDependentReferences(), AddNativeCodeStatsCounters(), and AddStubCache().
kExternalReferenceCountIsolateIndependent
constexpr int v8::internal::ExternalReferenceTable::kExternalReferenceCountIsolateIndependent [static], [constexpr]
Initial value:
=
      ExternalReference::kExternalReferenceCountIsolateIndependent
Definition at line 26 of file external-reference-table.h.
Referenced by AddAccessors(), AddBuiltins(), AddIsolateIndependentReferences(), and AddRuntimeFunctions().
kIsolateAddressReferenceCount
constexpr int v8::internal::ExternalReferenceTable::kIsolateAddressReferenceCount = kIsolateAddressCount [static], [constexpr]
Definition at line 37 of file external-reference-table.h.
Referenced by AddIsolateAddresses(), AddNativeCodeStatsCounters(), and AddStubCache().
kRuntimeReferenceCount
constexpr int v8::internal::ExternalReferenceTable::kRuntimeReferenceCount [static], [constexpr]
Initial value:
=
      Runtime::kNumFunctions -
      Runtime::kNumInlineFunctions
Definition at line 34 of file external-reference-table.h.
Referenced by AddAccessors(), and AddRuntimeFunctions().
kSize
constexpr int v8::internal::ExternalReferenceTable::kSize [static], [constexpr]
Initial value:
=
      kSizeIsolateIndependent + kExternalReferenceCountIsolateDependent +
      kIsolateAddressReferenceCount + kStubCacheReferenceCount +
      kStatsCountersReferenceCount
Definition at line 51 of file external-reference-table.h.
Referenced by AddNativeCodeStatsCounters(), v8::internal::ExternalReferenceEncoder::ExternalReferenceEncoder(), Init(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitExternalPointer().
kSizeInBytes
constexpr uint32_t v8::internal::ExternalReferenceTable::kSizeInBytes = kSize * kEntrySize + 2 * kUInt32Size [static], [constexpr]
Definition at line 57 of file external-reference-table.h.
Referenced by NameFromOffset().
kSizeIsolateIndependent
constexpr int v8::internal::ExternalReferenceTable::kSizeIsolateIndependent [static], [constexpr]
Initial value:
=
      kSpecialReferenceCount + kExternalReferenceCountIsolateIndependent +
      kBuiltinsReferenceCount + kRuntimeReferenceCount +
      kAccessorReferenceCount
Definition at line 47 of file external-reference-table.h.
Referenced by AddIsolateAddresses(), AddIsolateDependentReferences(), AddNativeCodeStatsCounters(), AddStubCache(), CopyIsolateIndependentReferences(), v8::internal::StartupDeserializer::DeserializeAndCheckExternalReferenceTable(), Init(), InitializeOncePerIsolateGroup(), InitIsolateIndependent(), NameOfIsolateIndependentAddress(), and v8::internal::StartupSerializer::StartupSerializer().
kSpecialReferenceCount
constexpr int v8::internal::ExternalReferenceTable::kSpecialReferenceCount = 1 [static], [constexpr]
Definition at line 25 of file external-reference-table.h.
Referenced by AddAccessors(), AddBuiltins(), AddIsolateIndependentReferences(), and AddRuntimeFunctions().
kStatsCountersReferenceCount
constexpr int v8::internal::ExternalReferenceTable::kStatsCountersReferenceCount [static], [constexpr]
Initial value:
=
#define SC(...)
      STATS_COUNTER_NATIVE_CODE_LIST(SC)
Definition at line 43 of file external-reference-table.h.
Referenced by AddNativeCodeStatsCounters().
kStubCacheReferenceCount
constexpr int v8::internal::ExternalReferenceTable::kStubCacheReferenceCount = 6 * 3 [static], [constexpr]
Definition at line 42 of file external-reference-table.h.
Referenced by AddNativeCodeStatsCounters(), and AddStubCache().
ref_addr_
Address v8::internal::ExternalReferenceTable::ref_addr_[kSize] [private]
Definition at line 121 of file external-reference-table.h.
Referenced by Add(), address(), and CopyIsolateIndependentReferences().
ref_name_
const char *const v8::internal::ExternalReferenceTable::ref_name_ [static], [private]
Definition at line 123 of file external-reference-table.h.
Referenced by name(), and NameOfIsolateIndependentAddress().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/external-reference-table.h
/mnt/V8SourceCode/src/codegen/external-reference-table.cc