v8::internal::Accessors Class Reference
#include <accessors.h>
Public Types
using AccessorNameBooleanSetterCallback = void(*)(Local< v8::Name > property, Local< v8::Value > value, const PropertyCallbackInfo< v8::Boolean > &info)
Public Member Functions
ACCESSOR_CALLBACK_LIST_GENERATOR (ACCESSOR_CALLBACK_DECLARATION,) static const expr int kAccessorInfoCount
Static Public Member Functions
static DirectHandle< AccessorInfo > MakeModuleNamespaceEntryInfo (Isolate *isolate, DirectHandle< String > name)
static Handle< JSObject > FunctionGetArguments (JavaScriptFrame *frame, int inlined_jsframe_index)
static DirectHandle< Object > GetLegacyFunctionArguments (Isolate *isolate, DirectHandle< JSFunction > function)
static DirectHandle< Object > GetLegacyFunctionCaller (Isolate *isolate, DirectHandle< JSFunction > function)
static bool IsJSObjectFieldAccessor (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Name > name, FieldIndex *field_index)
static MaybeDirectHandle< Object > ReplaceAccessorWithDataProperty (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< JSObject > holder, DirectHandle< Name > name, DirectHandle< Object > value)
static V8_EXPORT_PRIVATE DirectHandle< AccessorInfo > MakeAccessor (Isolate *isolate, DirectHandle< Name > name, AccessorNameGetterCallback getter, AccessorNameBooleanSetterCallback setter)
Static Public Attributes
static constexpr int kAccessorGetterCount
static constexpr int kAccessorSetterCount
static constexpr int kAccessorCallbackCount
Friends
class Heap
Detailed Description
Definition at line 68 of file accessors.h.
Member Typedef Documentation
AccessorNameBooleanSetterCallback
using v8::internal::Accessors::AccessorNameBooleanSetterCallback = void (*)(Local<v8::Name> property, Local<v8::Value> value, const PropertyCallbackInfo<v8::Boolean>& info)
Definition at line 147 of file accessors.h.
Member Function Documentation
ACCESSOR_CALLBACK_LIST_GENERATOR()
v8::internal::Accessors::ACCESSOR_CALLBACK_LIST_GENERATOR (ACCESSOR_CALLBACK_DECLARATION) const
FunctionGetArguments()
Handle< JSObject > v8::internal::Accessors::FunctionGetArguments (JavaScriptFrame * frame, int inlined_jsframe_index) [static]
Definition at line 508 of file accessors.cc.
                                                                            {
  Isolate* isolate = frame->isolate();
  Address requested_frame_fp = frame->fp();
  // Forward a frame iterator to the requested frame. This is needed because we
  // potentially need for advance it to the inlined arguments frame later.
  for (JavaScriptStackFrameIterator it(isolate); !it.done(); it.Advance()) {
    if (it.frame()->fp() != requested_frame_fp) continue;
    return GetFrameArguments(isolate, &it, inlined_jsframe_index);
  }
  UNREACHABLE(); // Requested frame not found.
}
References v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::StackFrame::fp(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), v8::internal::StackFrame::isolate(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::ScopeIterator::VisitLocalScope(), and v8::internal::DebugEvaluate::WithTopmostArguments().
GetLegacyFunctionArguments()
DirectHandle< Object > v8::internal::Accessors::GetLegacyFunctionArguments (Isolate * isolate, DirectHandle< JSFunction > function) [static]
Definition at line 522 of file accessors.cc.
                                                         {
  DirectHandle<Object> result = isolate->factory()->null_value();
  if (!function->shared()->native()) {
    // Find the top invocation of the function by traversing frames.
    for (JavaScriptStackFrameIterator it(isolate); !it.done(); it.Advance()) {
      JavaScriptFrame* frame = it.frame();
      int function_index = FindFunctionInFrame(frame, function);
      if (function_index >= 0) {
        result = GetFrameArguments(isolate, &it, function_index);
        break;
      }
    }
  }
  return result;
}
References v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{accessors.cc}::FindFunctionInFrame(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), and v8::base::internal::result.
Referenced by v8::internal::BUILTIN().
GetLegacyFunctionCaller()
DirectHandle< Object > v8::internal::Accessors::GetLegacyFunctionCaller (Isolate * isolate, DirectHandle< JSFunction > function) [static]
Definition at line 700 of file accessors.cc.
                                                         {
  DirectHandle<Object> result;
  MaybeDirectHandle<JSFunction> maybe_caller;
  maybe_caller = FindCaller(isolate, function);
  DirectHandle<JSFunction> caller;
  // We don't support caller access with correctness fuzzing.
  if (!v8_flags.correctness_fuzzer_suppressions &&
      maybe_caller.ToHandle(&caller)) {
    result = caller;
  } else {
    result = isolate->factory()->null_value();
  }
  return result;
}
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{accessors.cc}::FindCaller(), v8::base::internal::result, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::v8_flags.
Referenced by v8::internal::BUILTIN().
IsJSObjectFieldAccessor()
bool v8::internal::Accessors::IsJSObjectFieldAccessor (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Name > name, FieldIndex * field_index) [static]
Definition at line 64 of file accessors.cc.
                                                           {
  if (map->is_dictionary_map()) {
    // There are not descriptors in a dictionary mode map.
    return false;
  }
  switch (map->instance_type()) {
    case JS_ARRAY_TYPE:
      return CheckForName(isolate, name, isolate->factory()->length_string(),
                          JSArray::kLengthOffset, FieldIndex::kTagged, index);
    default:
      if (map->instance_type() < FIRST_NONSTRING_TYPE) {
        return CheckForName(isolate, name, isolate->factory()->length_string(),
                            offsetof(String, length_), FieldIndex::kWord32,
                            index);
      }
      return false;
  }
}
References v8::internal::CheckForName(), v8::internal::Isolate::factory(), v8::internal::FIRST_NONSTRING_TYPE, v8::internal::index, v8::internal::FieldIndex::kTagged, v8::internal::FieldIndex::kWord32, and v8::internal::name.
Referenced by v8::internal::LoadIC::ComputeHandler(), and v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor().
MakeAccessor()
DirectHandle< AccessorInfo > v8::internal::Accessors::MakeAccessor (Isolate * isolate, DirectHandle< Name > name, AccessorNameGetterCallback getter, AccessorNameBooleanSetterCallback setter) [static]
Definition at line 29 of file accessors.cc.
                                              {
  Factory* factory = isolate->factory();
  name = factory->InternalizeName(name);
  DirectHandle<AccessorInfo> info = factory->NewAccessorInfo();
  {
    DisallowGarbageCollection no_gc;
    Tagged<AccessorInfo> raw = *info;
    raw->set_is_sloppy(false);
    raw->set_replace_on_access(false);
    raw->set_getter_side_effect_type(SideEffectType::kHasSideEffect);
    raw->set_setter_side_effect_type(SideEffectType::kHasSideEffect);
    raw->set_name(*name);
    raw->set_getter(isolate, reinterpret_cast<Address>(getter));
    if (setter == nullptr) setter = &ReconfigureToDataProperty;
    raw->set_setter(isolate, reinterpret_cast<Address>(setter));
  }
  return info;
}
References v8::internal::Isolate::factory(), v8::kHasSideEffect, v8::internal::name, v8::internal::Factory::NewAccessorInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::setter.
Referenced by MakeModuleNamespaceEntryInfo().
MakeModuleNamespaceEntryInfo()
DirectHandle< AccessorInfo > v8::internal::Accessors::MakeModuleNamespaceEntryInfo (Isolate * isolate, DirectHandle< String > name) [static]
Definition at line 274 of file accessors.cc.
                                                 {
  return MakeAccessor(isolate, name, &ModuleNamespaceEntryGetter,
                      &ModuleNamespaceEntrySetter);
}
References MakeAccessor(), and v8::internal::name.
Referenced by v8::internal::Module::GetModuleNamespace().
ReplaceAccessorWithDataProperty()
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > v8::internal::Accessors::ReplaceAccessorWithDataProperty (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< JSObject > holder, DirectHandle< Name > name, DirectHandle< Object > value) [static]
Definition at line 88 of file accessors.cc.
                                                                       {
  LookupIterator it(isolate, receiver, PropertyKey(isolate, name), holder,
                    LookupIterator::OWN_SKIP_INTERCEPTOR);
  // Skip any access checks we might hit. This accessor should never hit in a
  // situation where the caller does not have access.
  while (it.state() == LookupIterator::ACCESS_CHECK) {
    CHECK(it.HasAccess());
    it.Next();
  }
  DCHECK(holder.is_identical_to(it.GetHolder<JSObject>()));
  CHECK_EQ(LookupIterator::ACCESSOR, it.state());
  it.ReconfigureDataProperty(value, it.property_attributes());
  return value;
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, CHECK, CHECK_EQ, v8::internal::DCHECK(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::HasAccess(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::name, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::LookupIterator::property_attributes(), v8::internal::LookupIterator::ReconfigureDataProperty(), v8::internal::LookupIterator::state(), and v8::internal::value.
Referenced by v8::internal::Object::GetPropertyWithAccessor().
Friends And Related Function Documentation
Heap
friend class Heap [friend]
Definition at line 162 of file accessors.h.
Member Data Documentation
kAccessorCallbackCount
constexpr int v8::internal::Accessors::kAccessorCallbackCount [static], [constexpr]
Initial value:
=
      ACCESSOR_CALLBACK_LIST_GENERATOR(COUNT_ACCESSOR,)
Definition at line 106 of file accessors.h.
kAccessorGetterCount
constexpr int v8::internal::Accessors::kAccessorGetterCount [static], [constexpr]
Initial value:
=
      ACCESSOR_GETTER_LIST(COUNT_ACCESSOR)
Definition at line 100 of file accessors.h.
kAccessorSetterCount
constexpr int v8::internal::Accessors::kAccessorSetterCount [static], [constexpr]
Initial value:
=
      ACCESSOR_SETTER_LIST(COUNT_ACCESSOR)
Definition at line 103 of file accessors.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/accessors.h
/mnt/V8SourceCode/src/builtins/accessors.cc