v8::internal::ObjectVisitorWithCageBases Class Reference
#include <visitors.h>
Public Member Functions
ObjectVisitorWithCageBases (PtrComprCageBase cage_base, PtrComprCageBase code_cage_base)
ObjectVisitorWithCageBases (Isolate *isolate)
ObjectVisitorWithCageBases (Heap *heap)
PtrComprCageBase cage_base () const
PtrComprCageBase code_cage_base () const
Detailed Description
Definition at line 216 of file visitors.h.
Constructor & Destructor Documentation
ObjectVisitorWithCageBases() [1/3]
v8::internal::ObjectVisitorWithCageBases::ObjectVisitorWithCageBases (PtrComprCageBase cage_base, PtrComprCageBase code_cage_base) [inline]
Definition at line 20 of file visitors-inl.h.
    : cage_base_(cage_base)
#ifdef V8_EXTERNAL_CODE_SPACE
      ,
      code_cage_base_(code_cage_base)
#endif // V8_EXTERNAL_CODE_SPACE
#endif // V8_COMPRESS_POINTERS
{
}
ObjectVisitorWithCageBases() [2/3]
v8::internal::ObjectVisitorWithCageBases::ObjectVisitorWithCageBases (Isolate * isolate) [inline], [explicit]
Definition at line 32 of file visitors-inl.h.
    : ObjectVisitorWithCageBases(PtrComprCageBase(isolate->cage_base()),
                                 PtrComprCageBase(isolate->code_cage_base()))
#else
    : ObjectVisitorWithCageBases(PtrComprCageBase(), PtrComprCageBase())
#endif // V8_COMPRESS_POINTERS
{
}
ObjectVisitorWithCageBases() [3/3]
v8::internal::ObjectVisitorWithCageBases::ObjectVisitorWithCageBases (Heap * heap) [inline], [explicit]
Definition at line 42 of file visitors-inl.h.
    : ObjectVisitorWithCageBases(Isolate::FromHeap(heap)) {}
Member Function Documentation
cage_base()
PtrComprCageBase v8::internal::ObjectVisitorWithCageBases::cage_base () const [inline]
Definition at line 225 of file visitors.h.
                                     {
#ifdef V8_COMPRESS_POINTERS
    return cage_base_;
#else
    return PtrComprCageBase{};
#endif // V8_COMPRESS_POINTERS
  }
Referenced by v8::internal::ObjectStatsCollectorImpl::cage_base(), code_cage_base(), v8::internal::UnreachableObjectsFilter::MarkingVisitor::MarkPointersImpl(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), v8::internal::FieldStatsCollector::RecordStats(), v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitEmbeddedPointer(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEmbeddedPointer(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitEmbeddedPointer(), v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer(), v8::internal::IndexedReferencesExtractor::VisitEmbeddedPointer(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitMapPointer(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitMapPointer(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitMapPointer(), v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitMapPointer(), v8::internal::IndexedReferencesExtractor::VisitMapPointer(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitPointer(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitPointer(), v8::internal::RecordMigratedSlotVisitor::VisitPointer(), v8::internal::ClientObjectVisitor< Visitor >::VisitPointer(), v8::internal::IndexedReferencesExtractor::VisitPointers(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitPointers(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitPointers(), v8::internal::ClientObjectVisitor< Visitor >::VisitPointers(), and v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitPointersImpl().
code_cage_base()
PtrComprCageBase v8::internal::ObjectVisitorWithCageBases::code_cage_base () const [inline]
Definition at line 235 of file visitors.h.
                                          {
#ifdef V8_EXTERNAL_CODE_SPACE
    return code_cage_base_;
#else
    return cage_base();
#endif // V8_EXTERNAL_CODE_SPACE
  }
References cage_base().
Referenced by v8::internal::RecordMigratedSlotVisitor::VisitInstructionStreamPointer(), v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitInstructionStreamPointer(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitInstructionStreamPointer(), and v8::internal::IndexedReferencesExtractor::VisitInstructionStreamPointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/visitors.h
/mnt/V8SourceCode/src/objects/visitors-inl.h