v8::internal::compiler::Scheduler Class Reference
#include <scheduler.h>
Classes
struct SchedulerData
Public Types
enum Flag { kNoFlags = 0u
, kSplitNodes = 1u << 1
, kTempSchedule = 1u << 2
 }
using Flags = base::Flags< Flag >
Public Member Functions
const ProfileDataFromFile * profile_data () const
Static Public Member Functions
static Schedule * ComputeSchedule (Zone *temp_zone, TFGraph *graph, Flags flags, TickCounter *tick_counter, const ProfileDataFromFile *profile_data)
static BasicBlockVector * ComputeSpecialRPO (Zone *zone, Schedule *schedule)
static void GenerateDominatorTree (Schedule *schedule)
Private Types
enum Placement {
kUnknown
, kSchedulable
, kFixed
, kCoupled
,
kScheduled
 }
using CommonDominatorCache = ZoneMap< int, ZoneMap< int, BasicBlock * > * >
Private Member Functions
Scheduler (Zone *zone, TFGraph *graph, Schedule *schedule, Flags flags, size_t node_count_hint_, TickCounter *tick_counter, const ProfileDataFromFile *profile_data)
SchedulerData DefaultSchedulerData ()
SchedulerData * GetData (Node *node)
Placement GetPlacement (Node *node)
Placement InitializePlacement (Node *node)
void UpdatePlacement (Node *node, Placement placement)
bool IsLive (Node *node)
std::optional< int > GetCoupledControlEdge (Node *node)
void IncrementUnscheduledUseCount (Node *node, Node *from)
void DecrementUnscheduledUseCount (Node *node, Node *from)
BasicBlock * GetCommonDominator (BasicBlock *b1, BasicBlock *b2)
BasicBlock * GetCommonDominatorIfCached (BasicBlock *b1, BasicBlock *b2)
void BuildCFG ()
void ComputeSpecialRPONumbering ()
void GenerateDominatorTree ()
void PrepareUses ()
void ScheduleEarly ()
void ScheduleLate ()
void SealFinalSchedule ()
void FuseFloatingControl (BasicBlock *block, Node *node)
void MovePlannedNodes (BasicBlock *from, BasicBlock *to)
Static Private Member Functions
static void PropagateImmediateDominators (BasicBlock *block)
Private Attributes
Zone * zone_
TFGraph * graph_
Schedule * schedule_
Flags flags_
ZoneVector< NodeVector * > scheduled_nodes_
NodeVector schedule_root_nodes_
ZoneQueue< Node * > schedule_queue_
ZoneVector< SchedulerData > node_data_
CFGBuilder * control_flow_builder_
SpecialRPONumberer * special_rpo_
ControlEquivalence * equivalence_
TickCounter *const tick_counter_
const ProfileDataFromFile * profile_data_
CommonDominatorCache common_dominator_cache_
Friends
class CFGBuilder
class SpecialRPONumberer
class PrepareUsesVisitor
class ScheduleEarlyNodeVisitor
class ScheduleLateNodeVisitor
Detailed Description
Definition at line 31 of file scheduler.h.
Member Typedef Documentation
CommonDominatorCache
using v8::internal::compiler::Scheduler::CommonDominatorCache = ZoneMap<int, ZoneMap<int, BasicBlock*>*> [private]
Definition at line 71 of file scheduler.h.
Flags
using v8::internal::compiler::Scheduler::Flags = base::Flags<Flag>
Definition at line 35 of file scheduler.h.
Member Enumeration Documentation
Flag
enum v8::internal::compiler::Scheduler::Flag
Enumerator
kNoFlags
kSplitNodes
kTempSchedule
Definition at line 34 of file scheduler.h.
{ kNoFlags = 0u, kSplitNodes = 1u << 1, kTempSchedule = 1u << 2 };
Placement
enum v8::internal::compiler::Scheduler::Placement [private]
Enumerator
kUnknown
kSchedulable
kFixed
kCoupled
kScheduled
Definition at line 68 of file scheduler.h.
{ kUnknown, kSchedulable, kFixed, kCoupled, kScheduled };
Constructor & Destructor Documentation
Scheduler()
v8::internal::compiler::Scheduler::Scheduler (Zone * zone, TFGraph * graph, Schedule * schedule, Flags flags, size_t node_count_hint_, TickCounter * tick_counter, const ProfileDataFromFile * profile_data) [private]
Definition at line 31 of file scheduler.cc.
    : zone_(zone),
      graph_(graph),
      schedule_(schedule),
      flags_(flags),
      scheduled_nodes_(zone),
      schedule_root_nodes_(zone),
      schedule_queue_(zone),
      node_data_(zone),
      tick_counter_(tick_counter),
      profile_data_(profile_data),
      common_dominator_cache_(zone) {
  node_data_.reserve(node_count_hint);
  node_data_.resize(graph->NodeCount(), DefaultSchedulerData());
}
References DefaultSchedulerData(), graph(), and node_data_.
Member Function Documentation
BuildCFG()
void v8::internal::compiler::Scheduler::BuildCFG () [private]
Definition at line 628 of file scheduler.cc.
                         {
  TRACE("--- CREATING CFG -------------------------------------------\n");
  // Instantiate a new control equivalence algorithm for the graph.
  equivalence_ = zone_->New<ControlEquivalence>(zone_, graph_);
  // Build a control-flow graph for the main control-connected component that
  // is being spanned by the graph's start and end nodes.
  control_flow_builder_ = zone_->New<CFGBuilder>(zone_, this);
  control_flow_builder_->Run();
  // Initialize per-block data.
  // Reserve an extra 10% to avoid resizing vector when fusing floating control.
  scheduled_nodes_.reserve(schedule_->BasicBlockCount() * 1.1);
  scheduled_nodes_.resize(schedule_->BasicBlockCount());
}
References v8::internal::compiler::Schedule::BasicBlockCount(), control_flow_builder_, equivalence_, graph_, v8::internal::Zone::New(), v8::internal::compiler::CFGBuilder::Run(), schedule_, scheduled_nodes_, v8::internal::TRACE(), and zone_.
ComputeSchedule()
Schedule * v8::internal::compiler::Scheduler::ComputeSchedule (Zone * temp_zone, TFGraph * graph, Flags flags, TickCounter * tick_counter, const ProfileDataFromFile * profile_data) [static]
Definition at line 50 of file scheduler.cc.
                                                                              {
  Zone* schedule_zone =
      (flags & Scheduler::kTempSchedule) ? zone : graph->zone();
  // Reserve 10% more space for nodes if node splitting is enabled to try to
  // avoid resizing the vector since that would triple its zone memory usage.
  float node_hint_multiplier = (flags & Scheduler::kSplitNodes) ? 1.1 : 1;
  size_t node_count_hint = node_hint_multiplier * graph->NodeCount();
  Schedule* schedule =
      schedule_zone->New<Schedule>(schedule_zone, node_count_hint);
  Scheduler scheduler(zone, graph, schedule, flags, node_count_hint,
                      tick_counter, profile_data);
  scheduler.BuildCFG();
  scheduler.ComputeSpecialRPONumbering();
  scheduler.GenerateDominatorTree();
  scheduler.PrepareUses();
  scheduler.ScheduleEarly();
  scheduler.ScheduleLate();
  scheduler.SealFinalSchedule();
  return schedule;
}
References v8::internal::flags, graph(), kSplitNodes, kTempSchedule, v8::internal::Zone::New(), and profile_data().
Referenced by v8::internal::compiler::TypeAssertionsPhase::Run(), v8::internal::compiler::ComputeSchedulePhase::Run(), and v8::internal::compiler::PrintGraphPhase::Run().
ComputeSpecialRPO()
BasicBlockVector * v8::internal::compiler::Scheduler::ComputeSpecialRPO (Zone * zone, Schedule * schedule) [static]
Definition at line 1142 of file scheduler.cc.
                                                                             {
  SpecialRPONumberer numberer(zone, schedule);
  numberer.ComputeSpecialRPO();
  numberer.SerializeRPOIntoSchedule();
  numberer.PrintAndVerifySpecialRPO();
  return schedule->rpo_order();
}
References v8::internal::compiler::SpecialRPONumberer::ComputeSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::PrintAndVerifySpecialRPO(), v8::internal::compiler::Schedule::rpo_order(), and v8::internal::compiler::SpecialRPONumberer::SerializeRPOIntoSchedule().
Referenced by v8::internal::compiler::RawMachineAssembler::ExportForOptimization(), and v8::internal::compiler::RawMachineAssembler::ExportForTest().
ComputeSpecialRPONumbering()
void v8::internal::compiler::Scheduler::ComputeSpecialRPONumbering () [private]
Definition at line 1151 of file scheduler.cc.
                                           {
  TRACE("--- COMPUTING SPECIAL RPO ----------------------------------\n");
  // Compute the special reverse-post-order for basic blocks.
  special_rpo_ = zone_->New<SpecialRPONumberer>(zone_, schedule_);
  special_rpo_->ComputeSpecialRPO();
}
References v8::internal::compiler::SpecialRPONumberer::ComputeSpecialRPO(), v8::internal::Zone::New(), schedule_, special_rpo_, v8::internal::TRACE(), and zone_.
DecrementUnscheduledUseCount()
void v8::internal::compiler::Scheduler::DecrementUnscheduledUseCount (Node * node, Node * from) [private]
Definition at line 207 of file scheduler.cc.
                                                                   {
  // Tracking use counts for fixed nodes is useless.
  if (GetPlacement(node) == kFixed) return;
  // Use count for coupled nodes is summed up on their control.
  if (GetPlacement(node) == kCoupled) {
    node = NodeProperties::GetControlInput(node);
    DCHECK_NE(GetPlacement(node), Placement::kFixed);
    DCHECK_NE(GetPlacement(node), Placement::kCoupled);
  }
  DCHECK_LT(0, GetData(node)->unscheduled_count_);
  --(GetData(node)->unscheduled_count_);
  if (v8_flags.trace_turbo_scheduler) {
    TRACE(" Use count of #%d:%s (used by #%d:%s)-- = %d\n", node->id(),
          node->op()->mnemonic(), from->id(), from->op()->mnemonic(),
          GetData(node)->unscheduled_count_);
  }
  if (GetData(node)->unscheduled_count_ == 0) {
    TRACE(" newly eligible #%d:%s\n", node->id(), node->op()->mnemonic());
    schedule_queue_.push(node);
  }
}
References DCHECK_LT, DCHECK_NE, v8::internal::compiler::NodeProperties::GetControlInput(), GetData(), GetPlacement(), v8::internal::compiler::Node::id(), kCoupled, kFixed, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), schedule_queue_, v8::internal::TRACE(), v8::internal::compiler::Scheduler::SchedulerData::unscheduled_count_, and v8::internal::v8_flags.
Referenced by UpdatePlacement().
DefaultSchedulerData()
Scheduler::SchedulerData v8::internal::compiler::Scheduler::DefaultSchedulerData () [inline], [private]
Definition at line 79 of file scheduler.cc.
                                                       {
  SchedulerData def = {schedule_->start(), 0, kUnknown};
  return def;
}
References kUnknown, schedule_, and v8::internal::compiler::Schedule::start().
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), and Scheduler().
FuseFloatingControl()
void v8::internal::compiler::Scheduler::FuseFloatingControl (BasicBlock * block, Node * node) [private]
Definition at line 1900 of file scheduler.cc.
                                                                 {
  TRACE("--- FUSE FLOATING CONTROL ----------------------------------\n");
  if (v8_flags.trace_turbo_scheduler) {
    StdoutStream{} << "Schedule before control flow fusion:\n" << *schedule_;
  }
  // Iterate on phase 1: Build control-flow graph.
  control_flow_builder_->Run(block, node);
  // Iterate on phase 2: Compute special RPO and dominator tree.
  special_rpo_->UpdateSpecialRPO(block, schedule_->block(node));
  // TODO(turbofan): Currently "iterate on" means "re-run". Fix that.
  for (BasicBlock* b = block->rpo_next(); b != nullptr; b = b->rpo_next()) {
    b->set_dominator_depth(-1);
    b->set_dominator(nullptr);
  }
  PropagateImmediateDominators(block->rpo_next());
  // Iterate on phase 4: Schedule nodes early.
  // TODO(turbofan): The following loop gathering the propagation roots is a
  // temporary solution and should be merged into the rest of the scheduler as
  // soon as the approach settled for all floating loops.
  NodeVector propagation_roots(control_flow_builder_->control_);
  for (Node* control : control_flow_builder_->control_) {
    for (Node* use : control->uses()) {
      if (NodeProperties::IsPhi(use) && IsLive(use)) {
        propagation_roots.push_back(use);
      }
    }
  }
  if (v8_flags.trace_turbo_scheduler) {
    TRACE("propagation roots: ");
    for (Node* r : propagation_roots) {
      TRACE("#%d:%s ", r->id(), r->op()->mnemonic());
    }
    TRACE("\n");
  }
  ScheduleEarlyNodeVisitor schedule_early_visitor(zone_, this);
  schedule_early_visitor.Run(&propagation_roots);
  // Move previously planned nodes.
  // TODO(turbofan): Improve that by supporting bulk moves.
  scheduled_nodes_.resize(schedule_->BasicBlockCount());
  MovePlannedNodes(block, schedule_->block(node));
  if (v8_flags.trace_turbo_scheduler) {
    StdoutStream{} << "Schedule after control flow fusion:\n" << *schedule_;
  }
}
References v8::internal::compiler::Schedule::BasicBlockCount(), v8::internal::compiler::Schedule::block(), v8::internal::compiler::CFGBuilder::control_, control_flow_builder_, IsLive(), v8::internal::compiler::NodeProperties::IsPhi(), MovePlannedNodes(), PropagateImmediateDominators(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::BasicBlock::rpo_next(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::ScheduleEarlyNodeVisitor::Run(), schedule_, scheduled_nodes_, special_rpo_, v8::internal::TRACE(), v8::internal::compiler::SpecialRPONumberer::UpdateSpecialRPO(), use(), v8::internal::compiler::Node::uses(), v8::internal::v8_flags, and zone_.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleFloatingControl().
GenerateDominatorTree() [1/2]
void v8::internal::compiler::Scheduler::GenerateDominatorTree () [private]
Definition at line 1292 of file scheduler.cc.
                                      {
  TRACE("--- IMMEDIATE BLOCK DOMINATORS -----------------------------\n");
  GenerateDominatorTree(schedule_);
}
References schedule_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::RawMachineAssembler::ExportForTest().
GenerateDominatorTree() [2/2]
void v8::internal::compiler::Scheduler::GenerateDominatorTree (Schedule * schedule) [static]
Definition at line 1284 of file scheduler.cc.
                                                        {
  // Seed start block to be the first dominator.
  schedule->start()->set_dominator_depth(0);
  // Build the block dominator tree resulting from the above seed.
  PropagateImmediateDominators(schedule->start()->rpo_next());
}
References PropagateImmediateDominators(), v8::internal::compiler::BasicBlock::rpo_next(), v8::internal::compiler::BasicBlock::set_dominator_depth(), and v8::internal::compiler::Schedule::start().
GetCommonDominator()
BasicBlock * v8::internal::compiler::Scheduler::GetCommonDominator (BasicBlock * b1, BasicBlock * b2) [private]
Definition at line 1168 of file scheduler.cc.
                                                                        {
  // A very common fast case:
  if (b1 == b2) return b1;
  // Try to find the common dominator by walking, if there is a chance of
  // finding it quickly.
  constexpr int kCacheGranularity = 63;
  static_assert((kCacheGranularity & (kCacheGranularity + 1)) == 0);
  int depth_difference = b1->dominator_depth() - b2->dominator_depth();
  if (depth_difference > -kCacheGranularity &&
      depth_difference < kCacheGranularity) {
    for (int i = 0; i < kCacheGranularity; i++) {
      if (b1->dominator_depth() < b2->dominator_depth()) {
        b2 = b2->dominator();
      } else {
        b1 = b1->dominator();
      }
      if (b1 == b2) return b1;
    }
    // We might fall out of the loop here if the dominator tree has several
    // deep "parallel" subtrees.
  }
  // If it'd be a long walk, take the bus instead (i.e. use the cache).
  // To keep memory consumption low, there'll be a bus stop every 64 blocks.
  // First, walk to the nearest bus stop.
  if (b1->dominator_depth() < b2->dominator_depth()) std::swap(b1, b2);
  while ((b1->dominator_depth() & kCacheGranularity) != 0) {
    if (V8_LIKELY(b1->dominator_depth() > b2->dominator_depth())) {
      b1 = b1->dominator();
    } else {
      b2 = b2->dominator();
    }
    if (b1 == b2) return b1;
  }
  // Then, walk from bus stop to bus stop until we either find a bus (i.e. an
  // existing cache entry) or the result. Make a list of any empty bus stops
  // we'd like to populate for next time.
  constexpr int kMaxNewCacheEntries = 2 * 50; // Must be even.
  // This array stores a flattened list of pairs, e.g. if after finding the
  // {result}, we want to cache [(B11, B12) -> result, (B21, B22) -> result],
  // then we store [11, 12, 21, 22] here.
  int new_cache_entries[kMaxNewCacheEntries];
  // Next free slot in {new_cache_entries}.
  int new_cache_entries_cursor = 0;
  while (b1 != b2) {
    if ((b1->dominator_depth() & kCacheGranularity) == 0) {
      BasicBlock* maybe_cache_hit = GetCommonDominatorIfCached(b1, b2);
      if (maybe_cache_hit != nullptr) {
        b1 = b2 = maybe_cache_hit;
        break;
      } else if (new_cache_entries_cursor < kMaxNewCacheEntries) {
        new_cache_entries[new_cache_entries_cursor++] = b1->id().ToInt();
        new_cache_entries[new_cache_entries_cursor++] = b2->id().ToInt();
      }
    }
    if (V8_LIKELY(b1->dominator_depth() > b2->dominator_depth())) {
      b1 = b1->dominator();
    } else {
      b2 = b2->dominator();
    }
  }
  // Lastly, create new cache entries we noted down earlier.
  BasicBlock* result = b1;
  for (int i = 0; i < new_cache_entries_cursor;) {
    int id1 = new_cache_entries[i++];
    int id2 = new_cache_entries[i++];
    ZoneMap<int, BasicBlock*>* mapping;
    auto entry = common_dominator_cache_.find(id1);
    if (entry == common_dominator_cache_.end()) {
      mapping = zone_->New<ZoneMap<int, BasicBlock*>>(zone_);
      common_dominator_cache_[id1] = mapping;
    } else {
      mapping = entry->second;
    }
    // If there was an existing entry, we would have found it earlier.
    DCHECK_EQ(mapping->find(id2), mapping->end());
    mapping->insert({id2, result});
  }
  return result;
}
References common_dominator_cache_, DCHECK_EQ, v8::internal::compiler::BasicBlock::dominator(), v8::internal::compiler::BasicBlock::dominator_depth(), GetCommonDominatorIfCached(), v8::internal::compiler::BasicBlock::id(), v8::internal::Zone::New(), v8::base::internal::result, v8::internal::compiler::BasicBlock::Id::ToInt(), V8_LIKELY, and zone_.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::GetCommonDominatorOfUses(), and v8::internal::compiler::ScheduleLateNodeVisitor::GetHoistBlock().
GetCommonDominatorIfCached()
BasicBlock * v8::internal::compiler::Scheduler::GetCommonDominatorIfCached (BasicBlock * b1, BasicBlock * b2) [private]
Definition at line 1159 of file scheduler.cc.
                                                                  {
  auto entry1 = common_dominator_cache_.find(b1->id().ToInt());
  if (entry1 == common_dominator_cache_.end()) return nullptr;
  auto entry2 = entry1->second->find(b2->id().ToInt());
  if (entry2 == entry1->second->end()) return nullptr;
  return entry2->second;
}
References common_dominator_cache_, v8::internal::compiler::BasicBlock::id(), and v8::internal::compiler::BasicBlock::Id::ToInt().
Referenced by GetCommonDominator().
GetCoupledControlEdge()
std::optional< int > v8::internal::compiler::Scheduler::GetCoupledControlEdge (Node * node) [inline], [private]
Definition at line 181 of file scheduler.cc.
                                                            {
  if (GetPlacement(node) == kCoupled) {
    return NodeProperties::FirstControlIndex(node);
  }
  return {};
}
References v8::internal::compiler::NodeProperties::FirstControlIndex(), GetPlacement(), and kCoupled.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), UpdatePlacement(), and v8::internal::compiler::PrepareUsesVisitor::VisitInputs().
GetData()
Scheduler::SchedulerData * v8::internal::compiler::Scheduler::GetData (Node * node) [inline], [private]
Definition at line 85 of file scheduler.cc.
                                                     {
  return &node_data_[node->id()];
}
References v8::internal::compiler::Node::id(), and node_data_.
Referenced by DecrementUnscheduledUseCount(), GetPlacement(), IncrementUnscheduledUseCount(), InitializePlacement(), v8::internal::compiler::ScheduleLateNodeVisitor::ProcessQueue(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), UpdatePlacement(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
GetPlacement()
Scheduler::Placement v8::internal::compiler::Scheduler::GetPlacement (Node * node) [private]
Definition at line 119 of file scheduler.cc.
                                                     {
  return GetData(node)->placement_;
}
References GetData(), and v8::internal::compiler::Scheduler::SchedulerData::placement_.
Referenced by DecrementUnscheduledUseCount(), v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), GetCoupledControlEdge(), IncrementUnscheduledUseCount(), InitializePlacement(), IsLive(), v8::internal::compiler::ScheduleLateNodeVisitor::ProcessQueue(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), UpdatePlacement(), v8::internal::compiler::PrepareUsesVisitor::VisitInputs(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
IncrementUnscheduledUseCount()
void v8::internal::compiler::Scheduler::IncrementUnscheduledUseCount (Node * node, Node * from) [private]
Definition at line 188 of file scheduler.cc.
                                                                   {
  // Tracking use counts for fixed nodes is useless.
  if (GetPlacement(node) == kFixed) return;
  // Use count for coupled nodes is summed up on their control.
  if (GetPlacement(node) == kCoupled) {
    node = NodeProperties::GetControlInput(node);
    DCHECK_NE(GetPlacement(node), Placement::kFixed);
    DCHECK_NE(GetPlacement(node), Placement::kCoupled);
  }
  ++(GetData(node)->unscheduled_count_);
  if (v8_flags.trace_turbo_scheduler) {
    TRACE(" Use count of #%d:%s (used by #%d:%s)++ = %d\n", node->id(),
          node->op()->mnemonic(), from->id(), from->op()->mnemonic(),
          GetData(node)->unscheduled_count_);
  }
}
References DCHECK_NE, v8::internal::compiler::NodeProperties::GetControlInput(), GetData(), GetPlacement(), v8::internal::compiler::Node::id(), kCoupled, kFixed, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::TRACE(), v8::internal::compiler::Scheduler::SchedulerData::unscheduled_count_, and v8::internal::v8_flags.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), and v8::internal::compiler::PrepareUsesVisitor::VisitInputs().
InitializePlacement()
Scheduler::Placement v8::internal::compiler::Scheduler::InitializePlacement (Node * node) [private]
Definition at line 89 of file scheduler.cc.
                                                            {
  SchedulerData* data = GetData(node);
  if (data->placement_ == kFixed) {
    // Nothing to do for control nodes that have been already fixed in
    // the schedule.
    return data->placement_;
  }
  DCHECK_EQ(kUnknown, data->placement_);
  switch (node->opcode()) {
    case IrOpcode::kParameter:
    case IrOpcode::kOsrValue:
      // Parameters and OSR values are always fixed to the start block.
      data->placement_ = kFixed;
      break;
    case IrOpcode::kPhi:
    case IrOpcode::kEffectPhi: {
      // Phis and effect phis are fixed if their control inputs are, whereas
      // otherwise they are coupled to a floating control node.
      Placement p = GetPlacement(NodeProperties::GetControlInput(node));
      data->placement_ = (p == kFixed ? kFixed : kCoupled);
      break;
    }
    default:
      // Control nodes that were not control-reachable from end may float.
      data->placement_ = kSchedulable;
      break;
  }
  return data->placement_;
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), GetData(), GetPlacement(), kCoupled, kFixed, kSchedulable, kUnknown, v8::internal::compiler::Node::opcode(), and v8::internal::compiler::Scheduler::SchedulerData::placement_.
Referenced by v8::internal::compiler::PrepareUsesVisitor::InitializePlacement().
IsLive()
bool v8::internal::compiler::Scheduler::IsLive (Node * node) [private]
Definition at line 123 of file scheduler.cc.
{ return GetPlacement(node) != kUnknown; }
References GetPlacement(), and kUnknown.
Referenced by FuseFloatingControl(), v8::internal::compiler::ScheduleLateNodeVisitor::GetCommonDominatorOfUses(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), and v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode().
MovePlannedNodes()
void v8::internal::compiler::Scheduler::MovePlannedNodes (BasicBlock * from, BasicBlock * to) [private]
Definition at line 1951 of file scheduler.cc.
                                                                 {
  TRACE("Move planned nodes from id:%d to id:%d\n", from->id().ToInt(),
        to->id().ToInt());
  NodeVector* from_nodes = scheduled_nodes_[from->id().ToSize()];
  NodeVector* to_nodes = scheduled_nodes_[to->id().ToSize()];
  if (!from_nodes) return;
  for (Node* const node : *from_nodes) {
    schedule_->SetBlockForNode(to, node);
  }
  if (to_nodes) {
    to_nodes->insert(to_nodes->end(), from_nodes->begin(), from_nodes->end());
    from_nodes->clear();
  } else {
    std::swap(scheduled_nodes_[from->id().ToSize()],
              scheduled_nodes_[to->id().ToSize()]);
  }
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::clear(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::BasicBlock::id(), v8::internal::ZoneVector< T >::insert(), schedule_, scheduled_nodes_, v8::internal::compiler::Schedule::SetBlockForNode(), v8::internal::compiler::BasicBlock::Id::ToInt(), v8::internal::compiler::BasicBlock::Id::ToSize(), and v8::internal::TRACE().
Referenced by FuseFloatingControl().
PrepareUses()
void v8::internal::compiler::Scheduler::PrepareUses () [private]
Definition at line 1373 of file scheduler.cc.
                            {
  TRACE("--- PREPARE USES -------------------------------------------\n");
  // Count the uses of every node, which is used to ensure that all of a
  // node's uses are scheduled before the node itself.
  PrepareUsesVisitor prepare_uses(this, graph_, zone_);
  prepare_uses.Run();
}
References graph_, v8::internal::compiler::PrepareUsesVisitor::Run(), v8::internal::TRACE(), and zone_.
profile_data()
const ProfileDataFromFile* v8::internal::compiler::Scheduler::profile_data () const [inline]
Definition at line 49 of file scheduler.h.
{ return profile_data_; }
Referenced by ComputeSchedule(), v8::internal::compiler::CFGBuilder::ConnectBranch(), and SealFinalSchedule().
PropagateImmediateDominators()
void v8::internal::compiler::Scheduler::PropagateImmediateDominators (BasicBlock * block) [static], [private]
Definition at line 1248 of file scheduler.cc.
                                                              {
  for (/*nop*/; block != nullptr; block = block->rpo_next()) {
    auto pred = block->predecessors().begin();
    auto end = block->predecessors().end();
    DCHECK(pred != end); // All blocks except start have predecessors.
    BasicBlock* dominator = *pred;
    bool deferred = dominator->deferred();
    // For multiple predecessors, walk up the dominator tree until a common
    // dominator is found. Visitation order guarantees that all predecessors
    // except for backwards edges have been visited.
    // We use a one-element cache for previously-seen dominators. This gets
    // hit a lot for functions that have long chains of diamonds, and in
    // those cases turns quadratic into linear complexity.
    BasicBlock* cache = nullptr;
    for (++pred; pred != end; ++pred) {
      // Don't examine backwards edges.
      if ((*pred)->dominator_depth() < 0) continue;
      if ((*pred)->dominator_depth() > 3 &&
          ((*pred)->dominator()->dominator() == cache ||
           (*pred)->dominator()->dominator()->dominator() == cache)) {
        // Nothing to do, the last iteration covered this case.
        DCHECK_EQ(dominator, BasicBlock::GetCommonDominator(dominator, *pred));
      } else {
        dominator = BasicBlock::GetCommonDominator(dominator, *pred);
      }
      cache = (*pred)->dominator();
      deferred = deferred & (*pred)->deferred();
    }
    block->set_dominator(dominator);
    block->set_dominator_depth(dominator->dominator_depth() + 1);
    block->set_deferred(deferred | block->deferred());
    TRACE("Block id:%d's idom is id:%d, depth = %d\n", block->id().ToInt(),
          dominator->id().ToInt(), block->dominator_depth());
  }
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::BasicBlock::deferred(), v8::internal::compiler::BasicBlock::dominator(), v8::internal::compiler::BasicBlock::dominator_depth(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::end(), v8::internal::compiler::BasicBlock::GetCommonDominator(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::BasicBlock::predecessors(), v8::internal::compiler::BasicBlock::rpo_next(), v8::internal::compiler::BasicBlock::set_deferred(), v8::internal::compiler::BasicBlock::set_dominator(), v8::internal::compiler::BasicBlock::set_dominator_depth(), v8::internal::compiler::BasicBlock::Id::ToInt(), and v8::internal::TRACE().
Referenced by FuseFloatingControl(), and GenerateDominatorTree().
ScheduleEarly()
void v8::internal::compiler::Scheduler::ScheduleEarly () [private]
Definition at line 1474 of file scheduler.cc.
                              {
  if (!special_rpo_->HasLoopBlocks()) {
    TRACE("--- NO LOOPS SO SKIPPING SCHEDULE EARLY --------------------\n");
    return;
  }
  TRACE("--- SCHEDULE EARLY -----------------------------------------\n");
  if (v8_flags.trace_turbo_scheduler) {
    TRACE("roots: ");
    for (Node* node : schedule_root_nodes_) {
      TRACE("#%d:%s ", node->id(), node->op()->mnemonic());
    }
    TRACE("\n");
  }
  // Compute the minimum block for each node thereby determining the earliest
  // position each node could be placed within a valid schedule.
  ScheduleEarlyNodeVisitor schedule_early_visitor(zone_, this);
  schedule_early_visitor.Run(&schedule_root_nodes_);
}
References v8::internal::compiler::SpecialRPONumberer::HasLoopBlocks(), v8::internal::compiler::ScheduleEarlyNodeVisitor::Run(), schedule_root_nodes_, special_rpo_, v8::internal::TRACE(), v8::internal::v8_flags, and zone_.
ScheduleLate()
void v8::internal::compiler::Scheduler::ScheduleLate () [private]
Definition at line 1847 of file scheduler.cc.
                             {
  TRACE("--- SCHEDULE LATE ------------------------------------------\n");
  if (v8_flags.trace_turbo_scheduler) {
    TRACE("roots: ");
    for (Node* node : schedule_root_nodes_) {
      TRACE("#%d:%s ", node->id(), node->op()->mnemonic());
    }
    TRACE("\n");
  }
  // Schedule: Places nodes in dominator block of all their uses.
  ScheduleLateNodeVisitor schedule_late_visitor(zone_, this);
  schedule_late_visitor.Run(&schedule_root_nodes_);
}
References v8::internal::compiler::ScheduleLateNodeVisitor::Run(), schedule_root_nodes_, v8::internal::TRACE(), v8::internal::v8_flags, and zone_.
SealFinalSchedule()
void v8::internal::compiler::Scheduler::SealFinalSchedule () [private]
Definition at line 1867 of file scheduler.cc.
                                  {
  TRACE("--- SEAL FINAL SCHEDULE ------------------------------------\n");
  // Serialize the assembly order and reverse-post-order numbering.
  special_rpo_->SerializeRPOIntoSchedule();
  special_rpo_->PrintAndVerifySpecialRPO();
  // Add collected nodes for basic blocks to their blocks in the right order.
  int block_num = 0;
  for (NodeVector* nodes : scheduled_nodes_) {
    BasicBlock::Id id = BasicBlock::Id::FromInt(block_num++);
    BasicBlock* block = schedule_->GetBlockById(id);
    if (nodes) {
      for (Node* node : base::Reversed(*nodes)) {
        schedule_->AddNode(block, node);
      }
    }
  }
#ifdef LOG_BUILTIN_BLOCK_COUNT
  if (const ProfileDataFromFile* profile_data = this->profile_data()) {
    for (BasicBlock* block : *schedule_->all_blocks()) {
      uint64_t executed_count =
          profile_data->GetExecutedCount(block->id().ToSize());
      block->set_pgo_execution_count(executed_count);
    }
  }
#endif
}
References v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::Schedule::all_blocks(), v8::internal::compiler::BasicBlock::Id::FromInt(), v8::internal::compiler::Schedule::GetBlockById(), v8::internal::compiler::SpecialRPONumberer::PrintAndVerifySpecialRPO(), profile_data(), v8::base::Reversed(), schedule_, scheduled_nodes_, v8::internal::compiler::SpecialRPONumberer::SerializeRPOIntoSchedule(), special_rpo_, and v8::internal::TRACE().
UpdatePlacement()
void v8::internal::compiler::Scheduler::UpdatePlacement (Node * node, Placement placement) [private]
Definition at line 125 of file scheduler.cc.
                                                               {
  SchedulerData* data = GetData(node);
  if (data->placement_ == kUnknown) {
    // We only update control nodes from {kUnknown} to {kFixed}. Ideally, we
    // should check that {node} is a control node (including exceptional calls),
    // but that is expensive.
    DCHECK_EQ(Scheduler::kFixed, placement);
    data->placement_ = placement;
    return;
  }
  switch (node->opcode()) {
    case IrOpcode::kParameter:
      // Parameters are fixed once and for all.
      UNREACHABLE();
    case IrOpcode::kPhi:
    case IrOpcode::kEffectPhi: {
      // Phis and effect phis are coupled to their respective blocks.
      DCHECK_EQ(Scheduler::kCoupled, data->placement_);
      DCHECK_EQ(Scheduler::kFixed, placement);
      Node* control = NodeProperties::GetControlInput(node);
      BasicBlock* block = schedule_->block(control);
      schedule_->AddNode(block, node);
      break;
    }
#define DEFINE_CONTROL_CASE(V) case IrOpcode::k##V:
      CONTROL_OP_LIST(DEFINE_CONTROL_CASE)
#undef DEFINE_CONTROL_CASE
      {
        // Control nodes force coupled uses to be placed.
        for (auto use : node->uses()) {
          if (GetPlacement(use) == Scheduler::kCoupled) {
            DCHECK_EQ(node, NodeProperties::GetControlInput(use));
            UpdatePlacement(use, placement);
          }
      }
      break;
    }
    default:
      DCHECK_EQ(Scheduler::kSchedulable, data->placement_);
      DCHECK_EQ(Scheduler::kScheduled, placement);
      break;
  }
  // Reduce the use count of the node's inputs to potentially make them
  // schedulable. If all the uses of a node have been scheduled, then the node
  // itself can be scheduled.
  std::optional<int> coupled_control_edge = GetCoupledControlEdge(node);
  for (Edge const edge : node->input_edges()) {
    DCHECK_EQ(node, edge.from());
    if (edge.index() != coupled_control_edge) {
      DecrementUnscheduledUseCount(edge.to(), node);
    }
  }
  data->placement_ = placement;
}
References v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::Schedule::block(), CONTROL_OP_LIST, DCHECK_EQ, DecrementUnscheduledUseCount(), DEFINE_CONTROL_CASE, v8::internal::compiler::NodeProperties::GetControlInput(), GetCoupledControlEdge(), GetData(), GetPlacement(), v8::internal::compiler::Node::input_edges(), kCoupled, kFixed, kSchedulable, kScheduled, kUnknown, v8::internal::compiler::Node::opcode(), v8::internal::compiler::Scheduler::SchedulerData::placement_, schedule_, v8::internal::UNREACHABLE(), use(), and v8::internal::compiler::Node::uses().
Referenced by v8::internal::compiler::CFGBuilder::ConnectBlocks(), v8::internal::compiler::CFGBuilder::FixNode(), and v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleNode().
Friends And Related Function Documentation
CFGBuilder
friend class CFGBuilder [friend]
Definition at line 124 of file scheduler.h.
PrepareUsesVisitor
friend class PrepareUsesVisitor [friend]
Definition at line 133 of file scheduler.h.
ScheduleEarlyNodeVisitor
friend class ScheduleEarlyNodeVisitor [friend]
Definition at line 137 of file scheduler.h.
ScheduleLateNodeVisitor
friend class ScheduleLateNodeVisitor [friend]
Definition at line 141 of file scheduler.h.
SpecialRPONumberer
friend class SpecialRPONumberer [friend]
Definition at line 128 of file scheduler.h.
Member Data Documentation
common_dominator_cache_
CommonDominatorCache v8::internal::compiler::Scheduler::common_dominator_cache_ [private]
Definition at line 95 of file scheduler.h.
Referenced by GetCommonDominator(), and GetCommonDominatorIfCached().
control_flow_builder_
CFGBuilder* v8::internal::compiler::Scheduler::control_flow_builder_ [private]
Definition at line 90 of file scheduler.h.
Referenced by BuildCFG(), v8::internal::compiler::ScheduleLateNodeVisitor::FindPredecessorBlock(), and FuseFloatingControl().
equivalence_
ControlEquivalence* v8::internal::compiler::Scheduler::equivalence_ [private]
Definition at line 92 of file scheduler.h.
Referenced by BuildCFG(), v8::internal::compiler::CFGBuilder::IsSingleEntrySingleExitRegion(), and v8::internal::compiler::CFGBuilder::Run().
flags_
Flags v8::internal::compiler::Scheduler::flags_ [private]
Definition at line 84 of file scheduler.h.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
graph_
TFGraph* v8::internal::compiler::Scheduler::graph_ [private]
Definition at line 82 of file scheduler.h.
Referenced by BuildCFG(), v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), v8::internal::compiler::CFGBuilder::IsFinalMerge(), PrepareUses(), and v8::internal::compiler::CFGBuilder::Run().
node_data_
ZoneVector<SchedulerData> v8::internal::compiler::Scheduler::node_data_ [private]
Definition at line 89 of file scheduler.h.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), GetData(), and Scheduler().
profile_data_
const ProfileDataFromFile* v8::internal::compiler::Scheduler::profile_data_ [private]
Definition at line 94 of file scheduler.h.
schedule_
Schedule* v8::internal::compiler::Scheduler::schedule_ [private]
Definition at line 83 of file scheduler.h.
Referenced by BuildCFG(), ComputeSpecialRPONumbering(), DefaultSchedulerData(), FuseFloatingControl(), GenerateDominatorTree(), MovePlannedNodes(), SealFinalSchedule(), and UpdatePlacement().
schedule_queue_
ZoneQueue<Node*> v8::internal::compiler::Scheduler::schedule_queue_ [private]
Definition at line 88 of file scheduler.h.
Referenced by DecrementUnscheduledUseCount(), v8::internal::compiler::ScheduleLateNodeVisitor::ProcessQueue(), and v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode().
schedule_root_nodes_
NodeVector v8::internal::compiler::Scheduler::schedule_root_nodes_ [private]
Definition at line 87 of file scheduler.h.
Referenced by v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), ScheduleEarly(), and ScheduleLate().
scheduled_nodes_
ZoneVector<NodeVector*> v8::internal::compiler::Scheduler::scheduled_nodes_ [private]
Definition at line 86 of file scheduler.h.
Referenced by BuildCFG(), FuseFloatingControl(), MovePlannedNodes(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleNode(), and SealFinalSchedule().
special_rpo_
SpecialRPONumberer* v8::internal::compiler::Scheduler::special_rpo_ [private]
Definition at line 91 of file scheduler.h.
Referenced by ComputeSpecialRPONumbering(), FuseFloatingControl(), v8::internal::compiler::ScheduleLateNodeVisitor::GetHoistBlock(), ScheduleEarly(), SealFinalSchedule(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
tick_counter_
TickCounter* const v8::internal::compiler::Scheduler::tick_counter_ [private]
Definition at line 93 of file scheduler.h.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::ProcessQueue(), v8::internal::compiler::CFGBuilder::Run(), and v8::internal::compiler::ScheduleEarlyNodeVisitor::Run().
zone_
Zone* v8::internal::compiler::Scheduler::zone_ [private]
Definition at line 81 of file scheduler.h.
Referenced by BuildCFG(), ComputeSpecialRPONumbering(), FuseFloatingControl(), GetCommonDominator(), PrepareUses(), ScheduleEarly(), ScheduleLate(), and v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/scheduler.h
/mnt/V8SourceCode/src/compiler/scheduler.cc