v8::internal::MarkingBitmap Class Reference
#include <marking.h>
Public Types
using CellType = MarkBit::CellType
using CellIndex = uint32_t
using MarkBitIndex = uint32_t
Public Member Functions
MarkingBitmap ()=default
MarkingBitmap (const MarkingBitmap &)=delete
MarkingBitmap & operator= (const MarkingBitmap &)=delete
CellType * cells ()
const CellType * cells () const
bool AllBitsClearInRange (MarkBitIndex start_index, MarkBitIndex end_index) const
bool AllBitsSetInRange (MarkBitIndex start_index, MarkBitIndex end_index) const
template<AccessMode mode>
void Clear ()
template<AccessMode mode>
void SetRange (MarkBitIndex start_index, MarkBitIndex end_index)
template<AccessMode mode>
void ClearRange (MarkBitIndex start_index, MarkBitIndex end_index)
bool IsClean () const
void Print () const
MarkBit MarkBitFromIndexForTesting (uint32_t index)
Static Public Member Functions
static constexpr MarkBitIndex AddressToIndex (Address address)
static constexpr MarkBitIndex LimitAddressToIndex (Address address)
static constexpr CellIndex IndexToCell (MarkBitIndex index)
static constexpr Address IndexToAddressOffset (MarkBitIndex index)
static constexpr Address CellToBase (CellIndex cell_index)
static constexpr uint32_t IndexInCell (MarkBitIndex index)
static constexpr CellType IndexInCellMask (MarkBitIndex index)
static constexpr uint32_t CellAlignIndex (uint32_t index)
static MarkingBitmap * Cast (Address addr)
static MarkBit MarkBitFromAddress (Address address)
static MarkBit MarkBitFromAddress (MarkingBitmap *bitmap, Address address)
static Address FindPreviousValidObject (const PageMetadata *page, Address maybe_inner_ptr)
Static Public Attributes
static constexpr uint32_t kBitsPerCell = sizeof(CellType) * kBitsPerByte
static constexpr uint32_t kBitsPerCellLog2
static constexpr uint32_t kBitIndexMask = kBitsPerCell - 1
static constexpr uint32_t kBytesPerCell = kBitsPerCell / kBitsPerByte
static constexpr uint32_t kBytesPerCellLog2
static constexpr size_t kLength = ((1 << kPageSizeBits) >> kTaggedSizeLog2)
static constexpr size_t kCellsCount
static constexpr size_t kSize = kCellsCount * kBytesPerCell
Private Member Functions
template<AccessMode mode>
void SetBitsInCell (uint32_t cell_index, MarkBit::CellType mask)
template<AccessMode mode>
void ClearBitsInCell (uint32_t cell_index, MarkBit::CellType mask)
template<AccessMode mode>
void SetCellRangeRelaxed (uint32_t start_cell_index, uint32_t end_cell_index)
template<AccessMode mode>
void ClearCellRangeRelaxed (uint32_t start_cell_index, uint32_t end_cell_index)
Static Private Member Functions
static MarkingBitmap * FromAddress (Address address)
Private Attributes
CellType cells_ [kCellsCount] = {0}
Detailed Description
Definition at line 92 of file marking.h.
Member Typedef Documentation
CellIndex
using v8::internal::MarkingBitmap::CellIndex = uint32_t
Definition at line 95 of file marking.h.
CellType
using v8::internal::MarkingBitmap::CellType = MarkBit::CellType
Definition at line 94 of file marking.h.
MarkBitIndex
using v8::internal::MarkingBitmap::MarkBitIndex = uint32_t
Definition at line 96 of file marking.h.
Constructor & Destructor Documentation
MarkingBitmap() [1/2]
v8::internal::MarkingBitmap::MarkingBitmap () [default]
MarkingBitmap() [2/2]
v8::internal::MarkingBitmap::MarkingBitmap (const MarkingBitmap &) [delete]
Member Function Documentation
AddressToIndex()
constexpr MarkingBitmap::MarkBitIndex v8::internal::MarkingBitmap::AddressToIndex (Address address) [inline], [static], [constexpr]
Definition at line 174 of file marking-inl.h.
                     {
  return MemoryChunk::AddressToOffset(address) >> kTaggedSizeLog2;
}
References v8::internal::MemoryChunk::AddressToOffset(), and v8::internal::kTaggedSizeLog2.
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), v8::internal::PageMetadata::CreateBlackArea(), v8::internal::PageMetadata::DestroyBlackArea(), FindPreviousValidObject(), v8::internal::Sweeper::FreeAndProcessFreedMemory(), LimitAddressToIndex(), MarkBitFromAddress(), and v8::internal::Heap::RightTrimArray().
AllBitsClearInRange()
bool v8::internal::MarkingBitmap::AllBitsClearInRange (MarkBitIndex start_index, MarkBitIndex end_index) const
Definition at line 44 of file marking.cc.
                                                                      {
  if (start_index >= end_index) return true;
  end_index--;
  const CellIndex start_cell_index = IndexToCell(start_index);
  MarkBit::CellType start_index_mask = IndexInCellMask(start_index);
  const CellIndex end_cell_index = IndexToCell(end_index);
  MarkBit::CellType end_index_mask = IndexInCellMask(end_index);
  MarkBit::CellType matching_mask;
  if (start_cell_index != end_cell_index) {
    matching_mask = ~(start_index_mask - 1);
    if ((cells()[start_cell_index] & matching_mask)) return false;
    for (size_t i = start_cell_index + 1; i < end_cell_index; i++) {
      if (cells()[i]) return false;
    }
    matching_mask = end_index_mask | (end_index_mask - 1);
    return !(cells()[end_cell_index] & matching_mask);
  } else {
    matching_mask = end_index_mask | (end_index_mask - start_index_mask);
    return !(cells()[end_cell_index] & matching_mask);
  }
}
References cells(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, IndexInCellMask(), and IndexToCell().
AllBitsSetInRange()
bool v8::internal::MarkingBitmap::AllBitsSetInRange (MarkBitIndex start_index, MarkBitIndex end_index) const
Definition at line 17 of file marking.cc.
                                                                    {
  if (start_index >= end_index) return false;
  end_index--;
  const CellIndex start_cell_index = IndexToCell(start_index);
  MarkBit::CellType start_index_mask = IndexInCellMask(start_index);
  const CellIndex end_cell_index = IndexToCell(end_index);
  MarkBit::CellType end_index_mask = IndexInCellMask(end_index);
  MarkBit::CellType matching_mask;
  if (start_cell_index != end_cell_index) {
    matching_mask = ~(start_index_mask - 1);
    if ((cells()[start_cell_index] & matching_mask) != matching_mask) {
      return false;
    }
    for (unsigned int i = start_cell_index + 1; i < end_cell_index; i++) {
      if (cells()[i] != kAllBitsSetInCellValue) return false;
    }
    matching_mask = end_index_mask | (end_index_mask - 1);
    return ((cells()[end_cell_index] & matching_mask) == matching_mask);
  } else {
    matching_mask = end_index_mask | (end_index_mask - start_index_mask);
    return (cells()[end_cell_index] & matching_mask) == matching_mask;
  }
}
References cells(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, IndexInCellMask(), IndexToCell(), and v8::internal::anonymous_namespace{marking.cc}::kAllBitsSetInCellValue.
Cast()
static MarkingBitmap* v8::internal::MarkingBitmap::Cast (Address addr) [inline], [static]
Definition at line 144 of file marking.h.
                                                     {
    return reinterpret_cast<MarkingBitmap*>(addr);
  }
Referenced by FromAddress().
CellAlignIndex()
static constexpr uint32_t v8::internal::MarkingBitmap::CellAlignIndex (uint32_t index) [inline], [static], [constexpr]
Definition at line 140 of file marking.h.
                                                                     {
    return index & ~kBitIndexMask;
  }
References v8::internal::index.
cells() [1/2]
CellType* v8::internal::MarkingBitmap::cells () [inline]
Definition at line 158 of file marking.h.
{ return cells_; }
Referenced by AllBitsClearInRange(), AllBitsSetInRange(), FindPreviousValidObject(), IsClean(), MarkBitFromAddress(), and Print().
cells() [2/2]
const CellType* v8::internal::MarkingBitmap::cells () const [inline]
Definition at line 159 of file marking.h.
{ return cells_; }
CellToBase()
static constexpr Address v8::internal::MarkingBitmap::CellToBase (CellIndex cell_index) [inline], [static], [constexpr]
Definition at line 127 of file marking.h.
                                                                      {
    return IndexToAddressOffset(cell_index << kBitsPerCellLog2);
  }
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject().
Clear()
template<AccessMode mode>
void v8::internal::MarkingBitmap::Clear [inline]
Definition at line 81 of file marking-inl.h.
                          {
  ClearCellRangeRelaxed<mode>(0, kCellsCount);
  if constexpr (mode == AccessMode::ATOMIC) {
    // This fence prevents re-ordering of publishing stores with the mark-bit
    // setting stores.
    base::SeqCst_MemoryFence();
  }
}
References v8::internal::ATOMIC, kCellsCount, mode(), and v8::base::SeqCst_MemoryFence().
Referenced by v8::internal::MutablePageMetadata::ClearLiveness(), v8::internal::Sweeper::ClearMarkBitsAndHandleLivenessStatistics(), and v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::~YoungGenerationConservativeStackVisitor().
ClearBitsInCell()
template<AccessMode mode>
void v8::internal::MarkingBitmap::ClearBitsInCell (uint32_t cell_index, MarkBit::CellType mask) [inline], [private]
ClearCellRangeRelaxed()
template<AccessMode mode>
void v8::internal::MarkingBitmap::ClearCellRangeRelaxed (uint32_t start_cell_index, uint32_t end_cell_index) [inline], [private]
ClearRange()
template<AccessMode mode>
void v8::internal::MarkingBitmap::ClearRange (MarkBitIndex start_index, MarkBitIndex end_index) [inline]
Definition at line 121 of file marking-inl.h.
                                                              {
  if (start_index >= end_index) return;
  end_index--;
  const CellIndex start_cell_index = IndexToCell(start_index);
  const MarkBit::CellType start_index_mask = IndexInCellMask(start_index);
  const CellIndex end_cell_index = IndexToCell(end_index);
  const MarkBit::CellType end_index_mask = IndexInCellMask(end_index);
  if (start_cell_index != end_cell_index) {
    // Firstly, fill all bits from the start address to the end of the first
    // cell with 0s.
    ClearBitsInCell<mode>(start_cell_index, ~(start_index_mask - 1));
    // Then fill all in between cells with 0s.
    ClearCellRangeRelaxed<mode>(start_cell_index + 1, end_cell_index);
    // Finally, set all bits until the end address in the last cell with 0s.
    ClearBitsInCell<mode>(end_cell_index,
                          end_index_mask | (end_index_mask - 1));
  } else {
    ClearBitsInCell<mode>(start_cell_index,
                          end_index_mask | (end_index_mask - start_index_mask));
  }
  if (mode == AccessMode::ATOMIC) {
    // This fence prevents re-ordering of publishing stores with the mark-bit
    // clearing stores.
    base::SeqCst_MemoryFence();
  }
}
References v8::internal::ATOMIC, IndexInCellMask(), IndexToCell(), mode(), and v8::base::SeqCst_MemoryFence().
Referenced by v8::internal::PageMetadata::DestroyBlackArea(), v8::internal::Sweeper::FreeAndProcessFreedMemory(), v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage(), and v8::internal::Heap::RightTrimArray().
FindPreviousValidObject()
Address v8::internal::MarkingBitmap::FindPreviousValidObject (const PageMetadata * page, Address maybe_inner_ptr) [inline], [static]
Definition at line 187 of file marking-inl.h.
                                                                               {
  DCHECK(page->Contains(maybe_inner_ptr));
  const auto* bitmap = page->marking_bitmap();
  const MarkBit::CellType* cells = bitmap->cells();
  // The first actual bit of the bitmap, corresponding to page->area_start(),
  // is at start_index which is somewhere in (not necessarily at the start of)
  // start_cell_index.
  const auto start_index = MarkingBitmap::AddressToIndex(page->area_start());
  const auto start_cell_index = MarkingBitmap::IndexToCell(start_index);
  // We assume that all markbits before start_index are clear:
  // SLOW_DCHECK(bitmap->AllBitsClearInRange(0, start_index));
  // This has already been checked for the entire bitmap before starting marking
  // by MarkCompactCollector::VerifyMarkbitsAreClean.
  const auto index = MarkingBitmap::AddressToIndex(maybe_inner_ptr);
  auto cell_index = MarkingBitmap::IndexToCell(index);
  const auto index_in_cell = MarkingBitmap::IndexInCell(index);
  DCHECK_GT(MarkingBitmap::kBitsPerCell, index_in_cell);
  auto cell = cells[cell_index];
  // Clear the bits corresponding to higher addresses in the cell.
  cell &= ((~static_cast<MarkBit::CellType>(0)) >>
           (MarkingBitmap::kBitsPerCell - index_in_cell - 1));
  // Traverse the bitmap backwards, until we find a markbit that is set and
  // whose previous markbit (if it exists) is unset.
  // First, iterate backwards to find a cell with any set markbit.
  while (cell == 0 && cell_index > start_cell_index) cell = cells[--cell_index];
  if (cell == 0) {
    DCHECK_EQ(start_cell_index, cell_index);
    // We have reached the start of the page.
    return page->area_start();
  }
  // We have found such a cell.
  const auto leading_zeros = base::bits::CountLeadingZeros(cell);
  const auto leftmost_ones =
      base::bits::CountLeadingZeros(~(cell << leading_zeros));
  const auto index_of_last_leftmost_one =
      MarkingBitmap::kBitsPerCell - leading_zeros - leftmost_ones;
  const MemoryChunk* chunk = page->Chunk();
  // If the leftmost sequence of set bits does not reach the start of the cell,
  // we found it.
  if (index_of_last_leftmost_one > 0) {
    return chunk->address() + MarkingBitmap::IndexToAddressOffset(
                                  cell_index * MarkingBitmap::kBitsPerCell +
                                  index_of_last_leftmost_one);
  }
  // The leftmost sequence of set bits reaches the start of the cell. We must
  // keep traversing backwards until we find the first unset markbit.
  if (cell_index == start_cell_index) {
    // We have reached the start of the page.
    return page->area_start();
  }
  // Iterate backwards to find a cell with any unset markbit.
  do {
    cell = cells[--cell_index];
  } while (~cell == 0 && cell_index > start_cell_index);
  if (~cell == 0) {
    DCHECK_EQ(start_cell_index, cell_index);
    // We have reached the start of the page.
    return page->area_start();
  }
  // We have found such a cell.
  const auto leading_ones = base::bits::CountLeadingZeros(~cell);
  const auto index_of_last_leading_one =
      MarkingBitmap::kBitsPerCell - leading_ones;
  DCHECK_LT(0, index_of_last_leading_one);
  return chunk->address() + MarkingBitmap::IndexToAddressOffset(
                                cell_index * MarkingBitmap::kBitsPerCell +
                                index_of_last_leading_one);
}
References v8::internal::MemoryChunk::address(), AddressToIndex(), v8::internal::MemoryChunkMetadata::area_start(), cells(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunkMetadata::Contains(), v8::base::bits::CountLeadingZeros(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_LT, v8::internal::index, IndexInCell(), IndexToAddressOffset(), IndexToCell(), kBitsPerCell, v8::base::leading_zeros, and v8::internal::MutablePageMetadata::marking_bitmap().
Referenced by v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr().
FromAddress()
MarkingBitmap * v8::internal::MarkingBitmap::FromAddress (Address address) [inline], [static], [private]
Definition at line 152 of file marking-inl.h.
                                                         {
  Address metadata_address =
      MutablePageMetadata::FromAddress(address)->MetadataAddress();
  return Cast(metadata_address + MutablePageMetadata::MarkingBitmapOffset());
}
References Cast(), v8::internal::MutablePageMetadata::FromAddress(), v8::internal::MutablePageMetadata::MarkingBitmapOffset(), and v8::internal::MemoryChunkMetadata::MetadataAddress().
Referenced by MarkBitFromAddress().
IndexInCell()
static constexpr uint32_t v8::internal::MarkingBitmap::IndexInCell (MarkBitIndex index) [inline], [static], [constexpr]
Definition at line 131 of file marking.h.
                                                                      {
    return index & kBitIndexMask;
  }
References v8::internal::index.
Referenced by FindPreviousValidObject().
IndexInCellMask()
static constexpr CellType v8::internal::MarkingBitmap::IndexInCellMask (MarkBitIndex index) [inline], [static], [constexpr]
Definition at line 135 of file marking.h.
                                                                          {
    return static_cast<CellType>(1u) << IndexInCell(index);
  }
References v8::internal::index.
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), AllBitsClearInRange(), AllBitsSetInRange(), ClearRange(), MarkBitFromAddress(), and SetRange().
IndexToAddressOffset()
static constexpr Address v8::internal::MarkingBitmap::IndexToAddressOffset (MarkBitIndex index) [inline], [static], [constexpr]
Definition at line 123 of file marking.h.
                                                                              {
    return index << kTaggedSizeLog2;
  }
References v8::internal::index, and v8::internal::kTaggedSizeLog2.
Referenced by FindPreviousValidObject().
IndexToCell()
static constexpr CellIndex v8::internal::MarkingBitmap::IndexToCell (MarkBitIndex index) [inline], [static], [constexpr]
Definition at line 119 of file marking.h.
                                                                       {
    return index >> kBitsPerCellLog2;
  }
References v8::internal::index.
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), AllBitsClearInRange(), AllBitsSetInRange(), ClearRange(), FindPreviousValidObject(), MarkBitFromAddress(), and SetRange().
IsClean()
bool v8::internal::MarkingBitmap::IsClean () const
Definition at line 132 of file marking.cc.
                                  {
  for (size_t i = 0; i < kCellsCount; i++) {
    if (cells()[i] != 0) {
      return false;
    }
  }
  return true;
}
References cells(), and kCellsCount.
Referenced by v8::internal::MutablePageMetadata::IsLivenessClear(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage(), and v8::internal::Sweeper::SweepEmptyNewSpacePage().
LimitAddressToIndex()
constexpr MarkingBitmap::MarkBitIndex v8::internal::MarkingBitmap::LimitAddressToIndex (Address address) [inline], [static], [constexpr]
Definition at line 180 of file marking-inl.h.
                     {
  if (MemoryChunk::IsAligned(address)) return kLength;
  return AddressToIndex(address);
}
References AddressToIndex(), v8::internal::MemoryChunk::IsAligned(), and kLength.
Referenced by v8::internal::PageMetadata::CreateBlackArea(), v8::internal::PageMetadata::DestroyBlackArea(), and v8::internal::Heap::RightTrimArray().
MarkBitFromAddress() [1/2]
MarkBit v8::internal::MarkingBitmap::MarkBitFromAddress (Address address) [inline], [static]
Definition at line 159 of file marking-inl.h.
                                                         {
  return MarkBitFromAddress(FromAddress(address), address);
}
References FromAddress().
Referenced by v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterNormalObject(), v8::internal::MarkBit::From(), v8::internal::MarkBit::FromForTesting(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::HandleObjectFound(), and v8::internal::HeapLayout::InYoungGenerationForStickyMarkbits().
MarkBitFromAddress() [2/2]
MarkBit v8::internal::MarkingBitmap::MarkBitFromAddress (MarkingBitmap * bitmap, Address address) [inline], [static]
Definition at line 164 of file marking-inl.h.
                                                           {
  DCHECK_EQ(bitmap, FromAddress(address));
  const auto index = AddressToIndex(address);
  const auto mask = IndexInCellMask(index);
  MarkBit::CellType* cell = bitmap->cells() + IndexToCell(index);
  return MarkBit(cell, mask);
}
References AddressToIndex(), cells(), DCHECK_EQ, FromAddress(), v8::internal::index, IndexInCellMask(), and IndexToCell().
MarkBitFromIndexForTesting()
MarkBit v8::internal::MarkingBitmap::MarkBitFromIndexForTesting (uint32_t index) [inline]
Definition at line 190 of file marking.h.
                                                               {
    const auto mask = IndexInCellMask(index);
    MarkBit::CellType* cell = cells() + IndexToCell(index);
    return MarkBit(cell, mask);
  }
References v8::internal::index.
operator=()
MarkingBitmap& v8::internal::MarkingBitmap::operator= (const MarkingBitmap &) [delete]
Print()
void v8::internal::MarkingBitmap::Print () const
Definition at line 123 of file marking.cc.
                                {
  CellPrinter printer;
  for (size_t i = 0; i < kCellsCount; i++) {
    printer.Print(i, cells()[i]);
  }
  printer.Flush();
  PrintF("\n");
}
References cells(), kCellsCount, and v8::internal::PrintF().
SetBitsInCell()
template<AccessMode mode>
void v8::internal::MarkingBitmap::SetBitsInCell (uint32_t cell_index, MarkBit::CellType mask) [inline], [private]
SetCellRangeRelaxed()
template<AccessMode mode>
void v8::internal::MarkingBitmap::SetCellRangeRelaxed (uint32_t start_cell_index, uint32_t end_cell_index) [private]
SetRange()
template<AccessMode mode>
void v8::internal::MarkingBitmap::SetRange (MarkBitIndex start_index, MarkBitIndex end_index) [inline]
Definition at line 91 of file marking-inl.h.
                                                            {
  if (start_index >= end_index) return;
  end_index--;
  const CellIndex start_cell_index = IndexToCell(start_index);
  const MarkBit::CellType start_index_mask = IndexInCellMask(start_index);
  const CellIndex end_cell_index = IndexToCell(end_index);
  const MarkBit::CellType end_index_mask = IndexInCellMask(end_index);
  if (start_cell_index != end_cell_index) {
    // Firstly, fill all bits from the start address to the end of the first
    // cell with 1s.
    SetBitsInCell<mode>(start_cell_index, ~(start_index_mask - 1));
    // Then fill all in between cells with 1s.
    SetCellRangeRelaxed<mode>(start_cell_index + 1, end_cell_index);
    // Finally, fill all bits until the end address in the last cell with 1s.
    SetBitsInCell<mode>(end_cell_index, end_index_mask | (end_index_mask - 1));
  } else {
    SetBitsInCell<mode>(start_cell_index,
                        end_index_mask | (end_index_mask - start_index_mask));
  }
  if (mode == AccessMode::ATOMIC) {
    // This fence prevents re-ordering of publishing stores with the mark-bit
    // setting stores.
    base::SeqCst_MemoryFence();
  }
}
References v8::internal::ATOMIC, IndexInCellMask(), IndexToCell(), mode(), and v8::base::SeqCst_MemoryFence().
Referenced by v8::internal::PageMetadata::CreateBlackArea().
Member Data Documentation
cells_
CellType v8::internal::MarkingBitmap::cells_[kCellsCount] = {0} [private]
Definition at line 230 of file marking.h.
kBitIndexMask
constexpr uint32_t v8::internal::MarkingBitmap::kBitIndexMask = kBitsPerCell - 1 [static], [constexpr]
Definition at line 101 of file marking.h.
kBitsPerCell
constexpr uint32_t v8::internal::MarkingBitmap::kBitsPerCell = sizeof(CellType) * kBitsPerByte [static], [constexpr]
Definition at line 98 of file marking.h.
Referenced by FindPreviousValidObject(), and v8::internal::anonymous_namespace{marking.cc}::CellPrinter::Flush().
kBitsPerCellLog2
constexpr uint32_t v8::internal::MarkingBitmap::kBitsPerCellLog2 [static], [constexpr]
Initial value:
=
      base::bits::CountTrailingZeros(kBitsPerCell)
Definition at line 99 of file marking.h.
Referenced by v8::internal::CodeStubAssembler::GetMarkBit().
kBytesPerCell
constexpr uint32_t v8::internal::MarkingBitmap::kBytesPerCell = kBitsPerCell / kBitsPerByte [static], [constexpr]
Definition at line 102 of file marking.h.
Referenced by v8::internal::CodeStubAssembler::GetMarkBit().
kBytesPerCellLog2
constexpr uint32_t v8::internal::MarkingBitmap::kBytesPerCellLog2 [static], [constexpr]
Initial value:
=
      kBitsPerCellLog2 - kBitsPerByteLog2
Definition at line 103 of file marking.h.
Referenced by v8::internal::CodeStubAssembler::GetMarkBit().
kCellsCount
constexpr size_t v8::internal::MarkingBitmap::kCellsCount [static], [constexpr]
Initial value:
=
      (kLength + kBitsPerCell - 1) >> kBitsPerCellLog2
Definition at line 109 of file marking.h.
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), Clear(), IsClean(), and Print().
kLength
constexpr size_t v8::internal::MarkingBitmap::kLength = ((1 << kPageSizeBits) >> kTaggedSizeLog2) [static], [constexpr]
Definition at line 107 of file marking.h.
Referenced by LimitAddressToIndex().
kSize
constexpr size_t v8::internal::MarkingBitmap::kSize = kCellsCount * kBytesPerCell [static], [constexpr]
Definition at line 113 of file marking.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/marking.h
/mnt/V8SourceCode/src/heap/marking-inl.h
/mnt/V8SourceCode/src/heap/marking.cc