v8::internal::baseline::BaselineCompilerTask Class Reference
Public Member Functions
BaselineCompilerTask (Isolate *isolate, PersistentHandles *handles, Tagged< SharedFunctionInfo > sfi)
BaselineCompilerTask (const BaselineCompilerTask &) V8_NOEXCEPT=delete
BaselineCompilerTask (BaselineCompilerTask &&) V8_NOEXCEPT=default
void Compile (LocalIsolate *local_isolate)
void Install (Isolate *isolate)
Private Attributes
IndirectHandle< SharedFunctionInfo > shared_function_info_
IndirectHandle< BytecodeArray > bytecode_
MaybeIndirectHandle< Code > maybe_code_
base::TimeDelta time_taken_
Detailed Description
Definition at line 31 of file baseline-batch-compiler.cc.
Constructor & Destructor Documentation
BaselineCompilerTask() [1/3]
v8::internal::baseline::BaselineCompilerTask::BaselineCompilerTask (Isolate * isolate, PersistentHandles * handles, Tagged< SharedFunctionInfo > sfi) [inline]
Definition at line 33 of file baseline-batch-compiler.cc.
      : shared_function_info_(handles->NewHandle(sfi)),
        bytecode_(handles->NewHandle(sfi->GetBytecodeArray(isolate))) {
    DCHECK(sfi->is_compiled());
    shared_function_info_->set_is_sparkplug_compiling(true);
  }
References v8::internal::DCHECK(), and shared_function_info_.
BaselineCompilerTask() [2/3]
v8::internal::baseline::BaselineCompilerTask::BaselineCompilerTask (const BaselineCompilerTask &) [delete]
BaselineCompilerTask() [3/3]
v8::internal::baseline::BaselineCompilerTask::BaselineCompilerTask (BaselineCompilerTask &&) [default]
Member Function Documentation
Compile()
void v8::internal::baseline::BaselineCompilerTask::Compile (LocalIsolate * local_isolate) [inline]
Definition at line 45 of file baseline-batch-compiler.cc.
                                            {
    RCS_SCOPE(local_isolate, RuntimeCallCounterId::kCompileBackgroundBaseline);
    base::ScopedTimer timer(v8_flags.log_function_events ? &time_taken_
                                                         : nullptr);
    BaselineCompiler compiler(local_isolate, shared_function_info_, bytecode_);
    compiler.GenerateCode();
    maybe_code_ =
        local_isolate->heap()->NewPersistentMaybeHandle(compiler.Build());
  }
References v8::internal::baseline::BaselineCompiler::Build(), bytecode_, v8::internal::baseline::BaselineCompiler::GenerateCode(), maybe_code_, RCS_SCOPE, shared_function_info_, time_taken_, and v8::internal::v8_flags.
Install()
void v8::internal::baseline::BaselineCompilerTask::Install (Isolate * isolate) [inline]
Definition at line 56 of file baseline-batch-compiler.cc.
                                 {
    shared_function_info_->set_is_sparkplug_compiling(false);
    Handle<Code> code;
    if (!maybe_code_.ToHandle(&code)) return;
    if (v8_flags.print_code) {
      Print(*code);
    }
    // Don't install the code if the bytecode has been flushed or has
    // already some baseline code installed.
    if (!CanCompileWithConcurrentBaseline(*shared_function_info_, isolate)) {
      return;
    }
    shared_function_info_->set_baseline_code(*code, kReleaseStore);
    shared_function_info_->set_age(0);
    if (v8_flags.trace_baseline) {
      CodeTracer::Scope scope(isolate->GetCodeTracer());
      std::stringstream ss;
      ss << "[Concurrent Sparkplug Off Thread] Function ";
      ShortPrint(*shared_function_info_, ss);
      ss << " installed\n";
      OFStream os(scope.file());
      os << ss.str();
    }
    if (IsScript(shared_function_info_->script())) {
      Compiler::LogFunctionCompilation(
          isolate, LogEventListener::CodeTag::kFunction,
          direct_handle(Cast<Script>(shared_function_info_->script()), isolate),
          shared_function_info_, DirectHandle<FeedbackVector>(),
          Cast<AbstractCode>(code), CodeKind::BASELINE,
          time_taken_.InMillisecondsF());
    }
  }
References v8::internal::baseline::CanCompileWithConcurrentBaseline(), code, v8::internal::direct_handle(), v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::torque::ls::kFunction, v8::kReleaseStore, v8::internal::Compiler::LogFunctionCompilation(), maybe_code_, v8::internal::Print(), shared_function_info_, v8::internal::ShortPrint(), time_taken_, and v8::internal::v8_flags.
Member Data Documentation
bytecode_
IndirectHandle<BytecodeArray> v8::internal::baseline::BaselineCompilerTask::bytecode_ [private]
Definition at line 92 of file baseline-batch-compiler.cc.
Referenced by Compile().
maybe_code_
MaybeIndirectHandle<Code> v8::internal::baseline::BaselineCompilerTask::maybe_code_ [private]
Definition at line 93 of file baseline-batch-compiler.cc.
Referenced by Compile(), and Install().
shared_function_info_
IndirectHandle<SharedFunctionInfo> v8::internal::baseline::BaselineCompilerTask::shared_function_info_ [private]
Definition at line 91 of file baseline-batch-compiler.cc.
Referenced by BaselineCompilerTask(), Compile(), and Install().
time_taken_
base::TimeDelta v8::internal::baseline::BaselineCompilerTask::time_taken_ [private]
Definition at line 94 of file baseline-batch-compiler.cc.
Referenced by Compile(), and Install().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/baseline/baseline-batch-compiler.cc