v8::internal::FunctionTemplateInfo Class Reference
#include <templates.h>
Classes
class BodyDescriptor
Public Member Functions
DECL_RARE_ACCESSORS (prototype_template, PrototypeTemplate, UnionOf< Undefined, ObjectTemplateInfo >) DECL_RARE_ACCESSORS(prototype_provider_template
UnionOf< Undefined, FunctionTemplateInfo > DECL_RARE_ACCESSORS (parent_template, ParentTemplate, UnionOf< Undefined, FunctionTemplateInfo >) DECL_RARE_ACCESSORS(named_property_handler
UnionOf< Undefined, FunctionTemplateInfo > UnionOf< Undefined, InterceptorInfo > DECL_RARE_ACCESSORS (indexed_property_handler, IndexedPropertyHandler, UnionOf< Undefined, InterceptorInfo >) DECL_RARE_ACCESSORS(instance_template
UnionOf< Undefined, FunctionTemplateInfo > UnionOf< Undefined, InterceptorInfo > UnionOf< Undefined, ObjectTemplateInfo > DECL_RARE_ACCESSORS (instance_call_handler, InstanceCallHandler, UnionOf< Undefined, FunctionTemplateInfo >) DECL_RARE_ACCESSORS(access_check_info
UnionOf< Undefined, FunctionTemplateInfo > UnionOf< Undefined, InterceptorInfo > UnionOf< Undefined, ObjectTemplateInfo > UnionOf< Undefined, AccessCheckInfo > DECL_PRIMITIVE_GETTER (allowed_receiver_instance_type_range_start, InstanceType) inline InstanceType GetInstanceType() const
void SetInstanceType (int api_instance_type)
void SetAllowedReceiverInstanceTypeRange (int api_instance_type_start, int api_instance_type_end)
Tagged< FunctionTemplateInfo > GetParent (Isolate *isolate)
bool IsTemplateFor (Tagged< JSObject > object) const
bool IsTemplateFor (Tagged< Map > map) const
bool IsLeafTemplateForApiObject (Tagged< Object > object) const
bool instantiated ()
bool BreakAtEntry (Isolate *isolate)
bool HasInstanceType ()
int GetCFunctionsCount () const
Address GetCFunction (Isolate *isolate, int index) const
const CFunctionInfo * GetCSignature (Isolate *isolate, int index) const
void init_callback_redirection (i::IsolateForSandbox isolate)
void remove_callback_redirection (i::IsolateForSandbox isolate)
template<class IsolateT >
bool has_callback (IsolateT *isolate) const
Static Public Member Functions
static Handle< SharedFunctionInfo > GetOrCreateSharedFunctionInfo (Isolate *isolate, DirectHandle< FunctionTemplateInfo > info, MaybeDirectHandle< Name > maybe_name)
static Handle< SharedFunctionInfo > GetOrCreateSharedFunctionInfo (LocalIsolate *isolate, DirectHandle< FunctionTemplateInfo > info, DirectHandle< Name > maybe_name)
static void SealAndPrepareForPromotionToReadOnly (Isolate *isolate, DirectHandle< FunctionTemplateInfo > info)
static std::optional< Tagged< Name > > TryGetCachedPropertyName (Isolate *isolate, Tagged< Object > getter)
Public Attributes
PrototypeProviderTemplate
UnionOf< Undefined, FunctionTemplateInfo > NamedPropertyHandler
UnionOf< Undefined, FunctionTemplateInfo > UnionOf< Undefined, InterceptorInfo > InstanceTemplate
UnionOf< Undefined, FunctionTemplateInfo > UnionOf< Undefined, InterceptorInfo > UnionOf< Undefined, ObjectTemplateInfo > AccessCheckInfo
Static Public Attributes
static const int kFunctionOverloadEntrySize = 2
Private Member Functions
DECL_EXTERNAL_POINTER_ACCESSORS_MAYBE_READ_ONLY_HOST (maybe_redirected_callback, Address) inline int32_t relaxed_flag() const
void set_relaxed_flag (int32_t flags)
DECL_PRIMITIVE_SETTER (allowed_receiver_instance_type_range_start, InstanceType) static const expr int kNoJSApiObjectType=0
Static Private Member Functions
static Tagged< FunctionTemplateRareData > EnsureFunctionTemplateRareData (Isolate *isolate, DirectHandle< FunctionTemplateInfo > function_template_info)
static Tagged< FunctionTemplateRareData > AllocateFunctionTemplateRareData (Isolate *isolate, DirectHandle< FunctionTemplateInfo > function_template_info)
Detailed Description
Definition at line 117 of file templates.h.
Member Function Documentation
AllocateFunctionTemplateRareData()
Tagged< FunctionTemplateRareData > v8::internal::FunctionTemplateInfo::AllocateFunctionTemplateRareData (Isolate * isolate, DirectHandle< FunctionTemplateInfo > function_template_info) [static], [private]
Definition at line 143 of file templates.cc.
                                                               {
  DCHECK(IsUndefined(function_template_info->rare_data(kAcquireLoad), isolate));
  DirectHandle<FunctionTemplateRareData> rare_data =
      isolate->factory()->NewFunctionTemplateRareData();
  function_template_info->set_rare_data(*rare_data, kReleaseStore);
  return *rare_data;
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::kAcquireLoad, v8::kReleaseStore, and v8::internal::FactoryBase< Impl >::NewFunctionTemplateRareData().
BreakAtEntry()
bool v8::internal::FunctionTemplateInfo::BreakAtEntry (Isolate * isolate) [inline]
Definition at line 230 of file templates-inl.h.
                                                               {
  Tagged<Object> maybe_shared = shared_function_info();
  if (IsSharedFunctionInfo(maybe_shared)) {
    Tagged<SharedFunctionInfo> shared = Cast<SharedFunctionInfo>(maybe_shared);
    return shared->BreakAtEntry(isolate);
  }
  return false;
}
DECL_EXTERNAL_POINTER_ACCESSORS_MAYBE_READ_ONLY_HOST()
v8::internal::FunctionTemplateInfo::DECL_EXTERNAL_POINTER_ACCESSORS_MAYBE_READ_ONLY_HOST (maybe_redirected_callback , Address) const [private]
DECL_PRIMITIVE_GETTER()
UnionOf<Undefined, FunctionTemplateInfo> UnionOf<Undefined, InterceptorInfo> UnionOf<Undefined, ObjectTemplateInfo> UnionOf<Undefined, AccessCheckInfo> v8::internal::FunctionTemplateInfo::DECL_PRIMITIVE_GETTER (allowed_receiver_instance_type_range_start , InstanceType) const
DECL_PRIMITIVE_SETTER()
v8::internal::FunctionTemplateInfo::DECL_PRIMITIVE_SETTER (allowed_receiver_instance_type_range_start , InstanceType) const [private], [pure virtual]
DECL_RARE_ACCESSORS() [1/4]
UnionOf<Undefined, FunctionTemplateInfo> UnionOf<Undefined, InterceptorInfo> v8::internal::FunctionTemplateInfo::DECL_RARE_ACCESSORS (indexed_property_handler , IndexedPropertyHandler , UnionOf< Undefined, InterceptorInfo >)
DECL_RARE_ACCESSORS() [2/4]
UnionOf<Undefined, FunctionTemplateInfo> UnionOf<Undefined, InterceptorInfo> UnionOf<Undefined, ObjectTemplateInfo> v8::internal::FunctionTemplateInfo::DECL_RARE_ACCESSORS (instance_call_handler , InstanceCallHandler , UnionOf< Undefined, FunctionTemplateInfo >)
DECL_RARE_ACCESSORS() [3/4]
UnionOf<Undefined, FunctionTemplateInfo> v8::internal::FunctionTemplateInfo::DECL_RARE_ACCESSORS (parent_template , ParentTemplate , UnionOf< Undefined, FunctionTemplateInfo >)
DECL_RARE_ACCESSORS() [4/4]
v8::internal::FunctionTemplateInfo::DECL_RARE_ACCESSORS (prototype_template , PrototypeTemplate , UnionOf< Undefined, ObjectTemplateInfo >)
EnsureFunctionTemplateRareData()
static Tagged<FunctionTemplateRareData> v8::internal::FunctionTemplateInfo::EnsureFunctionTemplateRareData (Isolate * isolate, DirectHandle< FunctionTemplateInfo > function_template_info) [inline], [static], [private]
GetCFunction()
Address v8::internal::FunctionTemplateInfo::GetCFunction (Isolate * isolate, int index) const
Definition at line 175 of file templates.cc.
                                                                            {
  i::DisallowHeapAllocation no_gc;
  return v8::ToCData<kCFunctionTag>(
      isolate, Cast<FixedArray>(GetCFunctionOverloads())
                   ->get(index * kFunctionOverloadEntrySize));
}
References v8::internal::index, kFunctionOverloadEntrySize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetCFunctionsCount()
int v8::internal::FunctionTemplateInfo::GetCFunctionsCount () const
Definition at line 169 of file templates.cc.
                                                   {
  i::DisallowHeapAllocation no_gc;
  return Cast<FixedArray>(GetCFunctionOverloads())->length() /
         kFunctionOverloadEntrySize;
}
References kFunctionOverloadEntrySize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetCSignature()
const CFunctionInfo * v8::internal::FunctionTemplateInfo::GetCSignature (Isolate * isolate, int index) const
Definition at line 182 of file templates.cc.
                                                                          {
  i::DisallowHeapAllocation no_gc;
  return v8::ToCData<CFunctionInfo*, kCFunctionInfoTag>(
      isolate, Cast<FixedArray>(GetCFunctionOverloads())
                   ->get(index * kFunctionOverloadEntrySize + 1));
}
References v8::internal::index, kFunctionOverloadEntrySize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetOrCreateSharedFunctionInfo() [1/2]
Handle< SharedFunctionInfo > v8::internal::FunctionTemplateInfo::GetOrCreateSharedFunctionInfo (Isolate * isolate, DirectHandle< FunctionTemplateInfo > info, MaybeDirectHandle< Name > maybe_name) [static]
Definition at line 32 of file templates.cc.
                                        {
  Tagged<Object> current_info = info->shared_function_info();
  if (IsSharedFunctionInfo(current_info)) {
    return handle(Cast<SharedFunctionInfo>(current_info), isolate);
  }
  DirectHandle<Name> name;
  DirectHandle<String> name_string;
  if (maybe_name.ToHandle(&name) && IsString(*name)) {
    name_string = Cast<String>(name);
  } else if (IsString(info->class_name())) {
    name_string = direct_handle(Cast<String>(info->class_name()), isolate);
  } else {
    name_string = isolate->factory()->empty_string();
  }
  FunctionKind function_kind;
  if (info->remove_prototype()) {
    function_kind = FunctionKind::kConciseMethod;
  } else {
    function_kind = FunctionKind::kNormalFunction;
  }
  Handle<SharedFunctionInfo> sfi =
      isolate->factory()->NewSharedFunctionInfoForApiFunction(name_string, info,
                                                              function_kind);
  DCHECK(sfi->IsApiFunction());
  info->set_shared_function_info(*sfi);
  return sfi;
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::kConciseMethod, v8::internal::kNormalFunction, v8::internal::name, v8::internal::Factory::NewSharedFunctionInfoForApiFunction(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants(), v8::internal::ApiNatives::CreateApiFunction(), and SealAndPrepareForPromotionToReadOnly().
GetOrCreateSharedFunctionInfo() [2/2]
static Handle<SharedFunctionInfo> v8::internal::FunctionTemplateInfo::GetOrCreateSharedFunctionInfo (LocalIsolate * isolate, DirectHandle< FunctionTemplateInfo > info, DirectHandle< Name > maybe_name) [inline], [static]
Definition at line 220 of file templates.h.
                                     {
    // We don't support streaming compilation of scripts with natives, so we
    // don't need an off-thread implementation of this.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
GetParent()
Tagged< FunctionTemplateInfo > v8::internal::FunctionTemplateInfo::GetParent (Isolate * isolate) [inline]
Definition at line 239 of file templates-inl.h.
                                                                             {
  Tagged<Object> parent = GetParentTemplate();
  return IsUndefined(parent, isolate) ? Tagged<FunctionTemplateInfo>{}
                                      : Cast<FunctionTemplateInfo>(parent);
}
has_callback()
template<class IsolateT >
bool v8::internal::FunctionTemplateInfo::has_callback (IsolateT * isolate) const [inline]
HasInstanceType()
bool v8::internal::FunctionTemplateInfo::HasInstanceType ()
Definition at line 28 of file templates.cc.
                                           {
  return instance_type() != kNoJSApiObjectType;
}
init_callback_redirection()
void v8::internal::FunctionTemplateInfo::init_callback_redirection (i::IsolateForSandbox isolate) [inline]
Definition at line 102 of file templates-inl.h.
                                {
  CHECK(USE_SIMULATOR_BOOL);
  Address value = maybe_redirected_callback(isolate);
  if (value == kNullAddress) return;
  value =
      ExternalReference::Redirect(value, ExternalReference::DIRECT_API_CALL);
  set_maybe_redirected_callback(isolate, value);
}
References CHECK, v8::internal::ExternalReference::DIRECT_API_CALL, v8::internal::kNullAddress, v8::internal::ExternalReference::Redirect(), USE_SIMULATOR_BOOL, and v8::internal::value.
instantiated()
bool v8::internal::FunctionTemplateInfo::instantiated () [inline]
Definition at line 226 of file templates-inl.h.
                                        {
  return IsSharedFunctionInfo(shared_function_info());
}
IsLeafTemplateForApiObject()
bool v8::internal::FunctionTemplateInfo::IsLeafTemplateForApiObject (Tagged< Object > object) const
Definition at line 105 of file templates.cc.
                                 {
  i::DisallowGarbageCollection no_gc;
  if (!IsJSApiObject(object)) {
    return false;
  }
  bool result = false;
  Tagged<Map> map = Cast<HeapObject>(object)->map();
  Tagged<Object> constructor_obj = map->GetConstructor();
  if (IsJSFunction(constructor_obj)) {
    Tagged<JSFunction> fun = Cast<JSFunction>(constructor_obj);
    result = (*this == fun->shared()->api_func_data());
  } else if (IsFunctionTemplateInfo(constructor_obj)) {
    result = (*this == constructor_obj);
  }
  DCHECK_IMPLIES(result, IsTemplateFor(map));
  return result;
}
References DCHECK_IMPLIES, IsTemplateFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
IsTemplateFor() [1/2]
bool v8::internal::FunctionTemplateInfo::IsTemplateFor (Tagged< JSObject > object) const [inline]
Definition at line 286 of file templates-inl.h.
                                                                      {
  return IsTemplateFor(object->map());
}
Referenced by IsLeafTemplateForApiObject().
IsTemplateFor() [2/2]
bool v8::internal::FunctionTemplateInfo::IsTemplateFor (Tagged< Map > map) const
Definition at line 62 of file templates.cc.
                                                              {
  RCS_SCOPE(
      LocalHeap::Current() == nullptr
          ? GetIsolateChecked()->counters()->runtime_call_stats()
          : LocalIsolate::FromHeap(LocalHeap::Current())->runtime_call_stats(),
      RuntimeCallCounterId::kIsTemplateFor);
  // There is a constraint on the object; check.
  if (!IsJSObjectMap(map)) return false;
  if (v8_flags.experimental_embedder_instance_types) {
    DCHECK_IMPLIES(allowed_receiver_instance_type_range_start() == 0,
                   allowed_receiver_instance_type_range_end() == 0);
    if (base::IsInRange(map->instance_type(),
                        allowed_receiver_instance_type_range_start(),
                        allowed_receiver_instance_type_range_end())) {
      return true;
    }
  }
  // Fetch the constructor function of the object.
  Tagged<Object> cons_obj = map->GetConstructor();
  Tagged<Object> type;
  if (IsJSFunction(cons_obj)) {
    Tagged<JSFunction> fun = Cast<JSFunction>(cons_obj);
    if (!fun->shared()->IsApiFunction()) return false;
    type = fun->shared()->api_func_data();
  } else if (IsFunctionTemplateInfo(cons_obj)) {
    type = Cast<FunctionTemplateInfo>(cons_obj);
  } else {
    return false;
  }
  DCHECK(IsFunctionTemplateInfo(type));
  // Iterate through the chain of inheriting function templates to
  // see if the required one occurs.
  while (IsFunctionTemplateInfo(type)) {
    if (type == *this) return true;
    type = Cast<FunctionTemplateInfo>(type)->GetParentTemplate();
  }
  // Didn't find the required type in the inheritance chain.
  return false;
}
References v8::internal::allowed_receiver_instance_type_range_end, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::LocalIsolate::FromHeap(), RCS_SCOPE, v8::internal::tracing::type, and v8::internal::v8_flags.
remove_callback_redirection()
void v8::internal::FunctionTemplateInfo::remove_callback_redirection (i::IsolateForSandbox isolate) [inline]
Definition at line 112 of file templates-inl.h.
                                {
  CHECK(USE_SIMULATOR_BOOL);
  Address value = callback(isolate);
  set_maybe_redirected_callback(isolate, value);
}
References CHECK, USE_SIMULATOR_BOOL, and v8::internal::value.
SealAndPrepareForPromotionToReadOnly()
void v8::internal::FunctionTemplateInfo::SealAndPrepareForPromotionToReadOnly (Isolate * isolate, DirectHandle< FunctionTemplateInfo > info) [static]
Definition at line 127 of file templates.cc.
                                                               {
  if (info->should_promote_to_read_only()) return;
  CHECK(!HeapLayout::InReadOnlySpace(*info));
  info->EnsureHasSerialNumber(isolate);
  GetOrCreateSharedFunctionInfo(isolate, info,
                                isolate->factory()->empty_string());
  info->set_should_promote_to_read_only(true);
  info->set_published(true);
}
References CHECK, v8::internal::Isolate::factory(), GetOrCreateSharedFunctionInfo(), and v8::internal::HeapLayout::InReadOnlySpace().
Referenced by v8::internal::Heap::CreateInitialMutableObjects(), and v8::FunctionTemplate::SealAndPrepareForPromotionToReadOnly().
set_relaxed_flag()
void v8::internal::FunctionTemplateInfo::set_relaxed_flag (int32_t flags) [inline], [private]
SetAllowedReceiverInstanceTypeRange()
void v8::internal::FunctionTemplateInfo::SetAllowedReceiverInstanceTypeRange (int api_instance_type_start, int api_instance_type_end) [inline]
Definition at line 199 of file templates-inl.h.
                                                            {
  // Translate |api_instance_type_start| and |api_instance_type_end| values
  // from range [Internals::kFirstEmbedderJSApiObjectType,
  // Internals::kLastEmbedderJSApiObjectType] to range
  // [Internals::kFirstJSApiObjectType, Internals::kLastJSApiObjectType].
  DCHECK_LE(Internals::kFirstEmbedderJSApiObjectType, api_instance_type_start);
  DCHECK_LE(api_instance_type_start, api_instance_type_end);
  DCHECK_LE(api_instance_type_end, Internals::kLastEmbedderJSApiObjectType);
  // kNoJSApiObjectType must correspond to JS_API_OBJECT_TYPE.
  static_assert(kNoJSApiObjectType == 0);
  static_assert(JS_API_OBJECT_TYPE == Internals::kFirstJSApiObjectType);
  set_allowed_receiver_instance_type_range_start(static_cast<InstanceType>(
      api_instance_type_start + Internals::kFirstJSApiObjectType));
  set_allowed_receiver_instance_type_range_end(static_cast<InstanceType>(
      api_instance_type_end + Internals::kFirstJSApiObjectType));
}
References DCHECK_LE, v8::internal::Internals::kFirstEmbedderJSApiObjectType, v8::internal::Internals::kFirstJSApiObjectType, and v8::internal::Internals::kLastEmbedderJSApiObjectType.
SetInstanceType()
void v8::internal::FunctionTemplateInfo::SetInstanceType (int api_instance_type) [inline]
TryGetCachedPropertyName()
std::optional< Tagged< Name > > v8::internal::FunctionTemplateInfo::TryGetCachedPropertyName (Isolate * isolate, Tagged< Object > getter) [static]
Definition at line 153 of file templates.cc.
                                             {
  DisallowGarbageCollection no_gc;
  if (!IsFunctionTemplateInfo(getter)) {
    if (!IsJSFunction(getter)) return {};
    Tagged<SharedFunctionInfo> info = Cast<JSFunction>(getter)->shared();
    if (!info->IsApiFunction()) return {};
    getter = info->api_func_data();
  }
  // Check if the accessor uses a cached property.
  Tagged<Object> maybe_name =
      Cast<FunctionTemplateInfo>(getter)->cached_property_name();
  if (IsTheHole(maybe_name, isolate)) return {};
  return Cast<Name>(maybe_name);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::LookupIterator::LookupCachedProperty(), and v8::internal::ConcurrentLookupIterator::TryGetPropertyCell().
Member Data Documentation
AccessCheckInfo
UnionOf<Undefined, FunctionTemplateInfo> UnionOf<Undefined, InterceptorInfo> UnionOf<Undefined, ObjectTemplateInfo> v8::internal::FunctionTemplateInfo::AccessCheckInfo
Definition at line 165 of file templates.h.
InstanceTemplate
UnionOf<Undefined, FunctionTemplateInfo> UnionOf<Undefined, InterceptorInfo> v8::internal::FunctionTemplateInfo::InstanceTemplate
Definition at line 156 of file templates.h.
kFunctionOverloadEntrySize
const int v8::internal::FunctionTemplateInfo::kFunctionOverloadEntrySize = 2 [static]
Definition at line 255 of file templates.h.
Referenced by GetCFunction(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetCFunctions(), GetCFunctionsCount(), GetCSignature(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetCSignatures(), and v8::FunctionTemplate::SetCallHandler().
NamedPropertyHandler
UnionOf<Undefined, FunctionTemplateInfo> v8::internal::FunctionTemplateInfo::NamedPropertyHandler
Definition at line 146 of file templates.h.
PrototypeProviderTemplate
v8::internal::FunctionTemplateInfo::PrototypeProviderTemplate
Definition at line 136 of file templates.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/templates.h
/mnt/V8SourceCode/src/objects/templates-inl.h
/mnt/V8SourceCode/src/objects/templates.cc