v8::internal::compiler::turboshaft::InputsRepFactory Class Reference
#include <operations.h>
Static Public Member Functions
constexpr static base::Vector< const MaybeRegisterRepresentation > SingleRep (RegisterRepresentation rep)
constexpr static base::Vector< const MaybeRegisterRepresentation > PairOf (RegisterRepresentation rep)
Static Protected Member Functions
constexpr static const MaybeRegisterRepresentation * ToMaybeRepPointer (RegisterRepresentation rep)
Static Private Attributes
constexpr static MaybeRegisterRepresentation rep_map []
Detailed Description
Definition at line 482 of file operations.h.
Member Function Documentation
PairOf()
constexpr static base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::InputsRepFactory::PairOf (RegisterRepresentation rep) [inline], [static], [constexpr]
Definition at line 489 of file operations.h.
                                  {
    return base::VectorOf(ToMaybeRepPointer(rep), 2);
  }
References v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::WordBinopOp::inputs_rep(), v8::internal::compiler::turboshaft::FloatBinopOp::inputs_rep(), v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::inputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::inputs_rep(), and v8::internal::compiler::turboshaft::ComparisonOp::inputs_rep().
SingleRep()
constexpr static base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep (RegisterRepresentation rep) [inline], [static], [constexpr]
Definition at line 484 of file operations.h.
                                  {
    return base::VectorOf(ToMaybeRepPointer(rep), 1);
  }
References v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::WordUnaryOp::inputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::inputs_rep(), v8::internal::compiler::turboshaft::FloatUnaryOp::inputs_rep(), v8::internal::compiler::turboshaft::ChangeOp::inputs_rep(), v8::internal::compiler::turboshaft::TryChangeOp::inputs_rep(), v8::internal::compiler::turboshaft::TaggedBitcastOp::inputs_rep(), v8::internal::compiler::turboshaft::PendingLoopPhiOp::inputs_rep(), v8::internal::compiler::turboshaft::CheckTurboshaftTypeOfOp::inputs_rep(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::inputs_rep(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::inputs_rep(), and v8::internal::compiler::turboshaft::DebugPrintOp::inputs_rep().
ToMaybeRepPointer()
constexpr static const MaybeRegisterRepresentation* v8::internal::compiler::turboshaft::InputsRepFactory::ToMaybeRepPointer (RegisterRepresentation rep) [inline], [static], [constexpr], [protected]
Definition at line 495 of file operations.h.
                                  {
    size_t index = static_cast<size_t>(rep.value()) * 2;
    DCHECK_LT(index, arraysize(rep_map));
    return &rep_map[index];
  }
References arraysize, DCHECK_LT, v8::internal::index, and v8::internal::compiler::turboshaft::RegisterRepresentation::value().
Member Data Documentation
rep_map
constexpr static MaybeRegisterRepresentation v8::internal::compiler::turboshaft::InputsRepFactory::rep_map[] [static], [constexpr], [private]
Initial value:
= {
      MaybeRegisterRepresentation::Word32(),
      MaybeRegisterRepresentation::Word32(),
      MaybeRegisterRepresentation::Word64(),
      MaybeRegisterRepresentation::Word64(),
      MaybeRegisterRepresentation::Float32(),
      MaybeRegisterRepresentation::Float32(),
      MaybeRegisterRepresentation::Float64(),
      MaybeRegisterRepresentation::Float64(),
      MaybeRegisterRepresentation::Tagged(),
      MaybeRegisterRepresentation::Tagged(),
      MaybeRegisterRepresentation::Compressed(),
      MaybeRegisterRepresentation::Compressed(),
      MaybeRegisterRepresentation::Simd128(),
      MaybeRegisterRepresentation::Simd128(),
  
  }
Definition at line 503 of file operations.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h