v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder Class Reference
Public Member Functions
RegExpBuilder (Zone *zone, RegExpFlags flags)
void AddCharacter (base::uc16 character)
void AddUnicodeCharacter (base::uc32 character)
void AddEscapedUnicodeCharacter (base::uc32 character)
void AddEmpty ()
void AddClassRanges (RegExpClassRanges *cc)
void AddAtom (RegExpTree *tree)
void AddTerm (RegExpTree *tree)
void AddAssertion (RegExpTree *tree)
void NewAlternative ()
bool AddQuantifierToAtom (int min, int max, int index, RegExpQuantifier::QuantifierType type)
void FlushText ()
RegExpTree * ToRegExp ()
RegExpFlags flags () const
bool ignore_case () const
bool multiline () const
bool dotall () const
Private Types
using SmallRegExpTreeVector = SmallZoneVector< RegExpTree *, 8 >
Private Member Functions
void FlushTerms ()
bool IsUnicodeMode () const
Zone * zone () const
RegExpTextBuilder & text_builder ()
Private Attributes
Zone *const zone_
bool pending_empty_ = false
const RegExpFlags flags_
SmallRegExpTreeVector terms_
SmallRegExpTreeVector alternatives_
RegExpTextBuilder text_builder_
Detailed Description
Definition at line 290 of file regexp-parser.cc.
Member Typedef Documentation
SmallRegExpTreeVector
using v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::SmallRegExpTreeVector = SmallZoneVector<RegExpTree*, 8> [private]
Definition at line 333 of file regexp-parser.cc.
Constructor & Destructor Documentation
RegExpBuilder()
v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::RegExpBuilder (Zone * zone, RegExpFlags flags) [inline]
Definition at line 292 of file regexp-parser.cc.
      : zone_(zone),
        flags_(flags),
        terms_(zone),
        alternatives_(zone),
        text_builder_(RegExpTextBuilder{zone, &terms_, flags}) {}
Member Function Documentation
AddAssertion()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAssertion (RegExpTree * tree)
Definition at line 3170 of file regexp-parser.cc.
                                                   {
  FlushText();
  pending_empty_ = false;
  terms_.emplace_back(assert);
}
References v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), FlushText(), pending_empty_, and terms_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
AddAtom()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAtom (RegExpTree * tree)
Definition at line 3145 of file regexp-parser.cc.
                                            {
  if (term->IsEmpty()) {
    AddEmpty();
    return;
  }
  pending_empty_ = false;
  if (term->IsTextElement()) {
    text_builder().AddAtom(term);
  } else {
    FlushText();
    terms_.emplace_back(term);
  }
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddAtom(), AddEmpty(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), FlushText(), v8::internal::RegExpTree::IsTextElement(), pending_empty_, terms_, and text_builder().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseNamedBackReference().
AddCharacter()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddCharacter (base::uc16 character)
Definition at line 3120 of file regexp-parser.cc.
                                           {
  pending_empty_ = false;
  text_builder().AddCharacter(c);
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddCharacter(), pending_empty_, and text_builder().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
AddClassRanges()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddClassRanges (RegExpClassRanges * cc)
Definition at line 3140 of file regexp-parser.cc.
                                                        {
  pending_empty_ = false;
  text_builder().AddClassRanges(cc);
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddClassRanges(), v8::internal::cc, pending_empty_, and text_builder().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
AddEmpty()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddEmpty ()
Definition at line 3135 of file regexp-parser.cc.
                             {
  text_builder().FlushPendingSurrogate();
  pending_empty_ = true;
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::FlushPendingSurrogate(), pending_empty_, and text_builder().
Referenced by AddAtom(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseNamedBackReference().
AddEscapedUnicodeCharacter()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddEscapedUnicodeCharacter (base::uc32 character)
Definition at line 3130 of file regexp-parser.cc.
                                                                 {
  pending_empty_ = false;
  text_builder().AddEscapedUnicodeCharacter(character);
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddEscapedUnicodeCharacter(), v8::internal::character, pending_empty_, and text_builder().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
AddQuantifierToAtom()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddQuantifierToAtom (int min, int max, int index, RegExpQuantifier::QuantifierType type)
Definition at line 3204 of file regexp-parser.cc.
                                                    {
  if (pending_empty_) {
    pending_empty_ = false;
    return true;
  }
  RegExpTree* atom = text_builder().PopLastAtom();
  if (atom != nullptr) {
    FlushText();
  } else if (!terms_.empty()) {
    atom = terms_.back();
    terms_.pop_back();
    if (atom->IsLookaround()) {
      // With /u or /v, lookarounds are not quantifiable.
      if (IsUnicodeMode()) return false;
      // Lookbehinds are not quantifiable.
      if (atom->AsLookaround()->type() == RegExpLookaround::LOOKBEHIND) {
        return false;
      }
    }
    if (atom->max_match() == 0) {
      // Guaranteed to only match an empty string.
      if (min == 0) {
        return true;
      }
      terms_.emplace_back(atom);
      return true;
    }
  } else {
    // Only call immediately after adding an atom or character!
    UNREACHABLE();
  }
  terms_.emplace_back(
      zone()->New<RegExpQuantifier>(min, max, quantifier_type, index, atom));
  return true;
}
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::base::SmallVector< T, kSize, Allocator >::empty(), FlushText(), v8::internal::index, IsUnicodeMode(), v8::internal::RegExpLookaround::LOOKBEHIND, v8::internal::RegExpTree::max_match(), pending_empty_, v8::base::SmallVector< T, kSize, Allocator >::pop_back(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::PopLastAtom(), terms_, text_builder(), v8::internal::UNREACHABLE(), and zone().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
AddTerm()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddTerm (RegExpTree * tree)
Definition at line 3159 of file regexp-parser.cc.
                                            {
  DCHECK(!term->IsEmpty());
  pending_empty_ = false;
  if (term->IsTextElement()) {
    text_builder().AddTerm(term);
  } else {
    FlushText();
    terms_.emplace_back(term);
  }
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTerm(), v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), FlushText(), v8::internal::RegExpTree::IsTextElement(), pending_empty_, terms_, and text_builder().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
AddUnicodeCharacter()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddUnicodeCharacter (base::uc32 character)
Definition at line 3125 of file regexp-parser.cc.
                                                  {
  pending_empty_ = false;
  text_builder().AddUnicodeCharacter(c);
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddUnicodeCharacter(), pending_empty_, and text_builder().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
dotall()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::dotall () const [inline]
Definition at line 317 of file regexp-parser.cc.
{ return IsDotAll(flags_); }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
flags()
RegExpFlags v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::flags () const [inline]
Definition at line 313 of file regexp-parser.cc.
{ return flags_; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseOpenParenthesis().
FlushTerms()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushTerms () [private]
Definition at line 3178 of file regexp-parser.cc.
                               {
  FlushText();
  size_t num_terms = terms_.size();
  RegExpTree* alternative;
  if (num_terms == 0) {
    alternative = zone()->New<RegExpEmpty>();
  } else if (num_terms == 1) {
    alternative = terms_.back();
  } else {
    alternative =
        zone()->New<RegExpAlternative>(zone()->New<ZoneList<RegExpTree*>>(
            base::VectorOf(terms_.begin(), terms_.size()), zone()));
  }
  alternatives_.emplace_back(alternative);
  terms_.clear();
}
References alternatives_, v8::base::SmallVector< T, kSize, Allocator >::back(), v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::base::SmallVector< T, kSize, Allocator >::clear(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), FlushText(), v8::internal::Zone::New(), v8::base::SmallVector< T, kSize, Allocator >::size(), terms_, v8::base::VectorOf(), and zone().
Referenced by NewAlternative(), and ToRegExp().
FlushText()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushText ()
Definition at line 3118 of file regexp-parser.cc.
{ text_builder().FlushText(); }
References v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::FlushText(), and text_builder().
Referenced by AddAssertion(), AddAtom(), AddQuantifierToAtom(), AddTerm(), and FlushTerms().
ignore_case()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::ignore_case () const [inline]
Definition at line 315 of file regexp-parser.cc.
{ return IsIgnoreCase(flags_); }
IsUnicodeMode()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::IsUnicodeMode () const [inline], [private]
Definition at line 321 of file regexp-parser.cc.
                             {
    // Either /v or /u enable UnicodeMode
    // https://tc39.es/ecma262/#sec-parsepattern
    return IsUnicode(flags_) || IsUnicodeSets(flags_);
  }
Referenced by AddQuantifierToAtom().
multiline()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::multiline () const [inline]
Definition at line 316 of file regexp-parser.cc.
{ return IsMultiline(flags_); }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
NewAlternative()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::NewAlternative ()
Definition at line 3176 of file regexp-parser.cc.
{ FlushTerms(); }
References FlushTerms().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
text_builder()
RegExpTextBuilder& v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::text_builder () [inline], [private]
Definition at line 327 of file regexp-parser.cc.
{ return text_builder_; }
Referenced by AddAtom(), AddCharacter(), AddClassRanges(), AddEmpty(), AddEscapedUnicodeCharacter(), AddQuantifierToAtom(), AddTerm(), AddUnicodeCharacter(), and FlushText().
ToRegExp()
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::ToRegExp ()
Definition at line 3195 of file regexp-parser.cc.
                                    {
  FlushTerms();
  size_t num_alternatives = alternatives_.size();
  if (num_alternatives == 0) return zone()->New<RegExpEmpty>();
  if (num_alternatives == 1) return alternatives_.back();
  return zone()->New<RegExpDisjunction>(zone()->New<ZoneList<RegExpTree*>>(
      base::VectorOf(alternatives_.begin(), alternatives_.size()), zone()));
}
References alternatives_, v8::base::SmallVector< T, kSize, Allocator >::back(), v8::base::SmallVector< T, kSize, Allocator >::begin(), FlushTerms(), v8::internal::Zone::New(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::base::VectorOf(), and zone().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
zone()
Zone* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::zone () const [inline], [private]
Definition at line 326 of file regexp-parser.cc.
{ return zone_; }
Referenced by AddQuantifierToAtom(), FlushTerms(), and ToRegExp().
Member Data Documentation
alternatives_
SmallRegExpTreeVector v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::alternatives_ [private]
Definition at line 335 of file regexp-parser.cc.
Referenced by FlushTerms(), and ToRegExp().
flags_
const RegExpFlags v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::flags_ [private]
Definition at line 331 of file regexp-parser.cc.
pending_empty_
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::pending_empty_ = false [private]
Definition at line 330 of file regexp-parser.cc.
Referenced by AddAssertion(), AddAtom(), AddCharacter(), AddClassRanges(), AddEmpty(), AddEscapedUnicodeCharacter(), AddQuantifierToAtom(), AddTerm(), and AddUnicodeCharacter().
terms_
SmallRegExpTreeVector v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::terms_ [private]
Definition at line 334 of file regexp-parser.cc.
Referenced by AddAssertion(), AddAtom(), AddQuantifierToAtom(), AddTerm(), and FlushTerms().
text_builder_
RegExpTextBuilder v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::text_builder_ [private]
Definition at line 336 of file regexp-parser.cc.
zone_
Zone* const v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::zone_ [private]
Definition at line 329 of file regexp-parser.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-parser.cc