v8::internal::EmbedderGraphEntriesAllocator Class Reference
Public Member Functions
EmbedderGraphEntriesAllocator (HeapSnapshot *snapshot)
HeapEntry * AllocateEntry (HeapThing ptr) override
HeapEntry * AllocateEntry (Tagged< Smi > smi) override
Private Attributes
HeapSnapshot * snapshot_
StringsStorage * names_
HeapObjectsMap * heap_object_map_
Detailed Description
Definition at line 3066 of file heap-snapshot-generator.cc.
Constructor & Destructor Documentation
EmbedderGraphEntriesAllocator()
v8::internal::EmbedderGraphEntriesAllocator::EmbedderGraphEntriesAllocator (HeapSnapshot * snapshot) [inline], [explicit]
Definition at line 3068 of file heap-snapshot-generator.cc.
      : snapshot_(snapshot),
        names_(snapshot_->profiler()->names()),
        heap_object_map_(snapshot_->profiler()->heap_object_map()) {}
Member Function Documentation
AllocateEntry() [1/2]
HeapEntry * v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry (HeapThing ptr) [override], [virtual]
Implements v8::internal::HeapEntriesAllocator.
Definition at line 3107 of file heap-snapshot-generator.cc.
                                                                     {
  EmbedderGraphImpl::Node* node =
      reinterpret_cast<EmbedderGraphImpl::Node*>(ptr);
  DCHECK(node->IsEmbedderNode());
  size_t size = node->SizeInBytes();
  Address lookup_address = reinterpret_cast<Address>(node->GetNativeObject());
  HeapObjectsMap::MarkEntryAccessed accessed =
      HeapObjectsMap::MarkEntryAccessed::kYes;
  HeapObjectsMap::IsNativeObject is_native_object =
      HeapObjectsMap::IsNativeObject::kNo;
  if (!lookup_address) {
    // If there is not a native object associated with this embedder object,
    // then request the address of the embedder object.
    lookup_address = reinterpret_cast<Address>(node->GetAddress());
    is_native_object = HeapObjectsMap::IsNativeObject::kYes;
  }
  if (!lookup_address) {
    // If the Node implementation did not provide either a native address or an
    // embedder address, then use the address of the Node itself for the lookup.
    // In this case, we'll set the "accessed" flag on the newly created
    // HeapEntry to false, to indicate that this entry should not persist for
    // future snapshots.
    lookup_address = reinterpret_cast<Address>(node);
    accessed = HeapObjectsMap::MarkEntryAccessed::kNo;
  }
  SnapshotObjectId id = heap_object_map_->FindOrAddEntry(
      lookup_address, 0, accessed, is_native_object);
  auto* heap_entry = snapshot_->AddEntry(EmbedderGraphNodeType(node),
                                         EmbedderGraphNodeName(names_, node),
                                         id, static_cast<int>(size), 0);
  heap_entry->set_detachedness(node->GetDetachedness());
  return heap_entry;
}
References v8::internal::HeapSnapshot::AddEntry(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeName(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeType(), v8::internal::HeapObjectsMap::FindOrAddEntry(), v8::EmbedderGraph::Node::GetAddress(), v8::EmbedderGraph::Node::GetDetachedness(), v8::EmbedderGraph::Node::GetNativeObject(), heap_object_map_, v8::EmbedderGraph::Node::IsEmbedderNode(), v8::internal::HeapObjectsMap::kNo, v8::internal::HeapObjectsMap::kYes, names_, v8::internal::HeapEntry::set_detachedness(), size(), v8::EmbedderGraph::Node::SizeInBytes(), and snapshot_.
AllocateEntry() [2/2]
HeapEntry * v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry (Tagged< Smi > smi) [override], [virtual]
Implements v8::internal::HeapEntriesAllocator.
Definition at line 3141 of file heap-snapshot-generator.cc.
                                                                       {
  DCHECK(false);
  return nullptr;
}
References v8::internal::DCHECK().
Member Data Documentation
heap_object_map_
HeapObjectsMap* v8::internal::EmbedderGraphEntriesAllocator::heap_object_map_ [private]
Definition at line 3078 of file heap-snapshot-generator.cc.
Referenced by AllocateEntry().
names_
StringsStorage* v8::internal::EmbedderGraphEntriesAllocator::names_ [private]
Definition at line 3077 of file heap-snapshot-generator.cc.
Referenced by AllocateEntry().
snapshot_
HeapSnapshot* v8::internal::EmbedderGraphEntriesAllocator::snapshot_ [private]
Definition at line 3076 of file heap-snapshot-generator.cc.
Referenced by AllocateEntry().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc