v8::internal::SnapshotCompression Class Reference
#include <snapshot-compression.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE SnapshotData Compress (const SnapshotData *uncompressed_data)
static V8_EXPORT_PRIVATE SnapshotData Decompress (base::Vector< const uint8_t > compressed_data)
Detailed Description
Definition at line 14 of file snapshot-compression.h.
Member Function Documentation
Compress()
SnapshotData v8::internal::SnapshotCompression::Compress (const SnapshotData * uncompressed_data) [static]
Definition at line 21 of file snapshot-compression.cc.
                                           {
  SnapshotData snapshot_data;
  base::ElapsedTimer timer;
  if (v8_flags.profile_deserialization) timer.Start();
  static_assert(sizeof(Bytef) == 1, "");
  const uLongf input_size =
      static_cast<uLongf>(uncompressed_data->RawData().size());
  uint32_t payload_length =
      static_cast<uint32_t>(uncompressed_data->RawData().size());
  uLongf compressed_data_size = compressBound(input_size);
  // Allocating >= the final amount we will need.
  snapshot_data.AllocateData(
      static_cast<uint32_t>(sizeof(payload_length) + compressed_data_size));
  uint8_t* compressed_data =
      const_cast<uint8_t*>(snapshot_data.RawData().begin());
  // Since we are doing raw compression (no zlib or gzip headers), we need to
  // manually store the uncompressed size.
  MemCopy(compressed_data, &payload_length, sizeof(payload_length));
  CHECK_EQ(
      zlib_internal::CompressHelper(
          zlib_internal::ZRAW, compressed_data + sizeof(payload_length),
          &compressed_data_size,
          reinterpret_cast<const Bytef*>(uncompressed_data->RawData().begin()),
          input_size, Z_DEFAULT_COMPRESSION, nullptr, nullptr),
      Z_OK);
  // Reallocating to exactly the size we need.
  snapshot_data.Resize(static_cast<uint32_t>(compressed_data_size) +
                       sizeof(payload_length));
  DCHECK_EQ(payload_length,
            GetUncompressedSize(snapshot_data.RawData().begin()));
  if (v8_flags.profile_deserialization) {
    double ms = timer.Elapsed().InMillisecondsF();
    PrintF("[Compressing %d bytes took %0.3f ms]\n", payload_length, ms);
  }
  return snapshot_data;
}
References v8::internal::SerializedData::AllocateData(), v8::base::Vector< T >::begin(), CHECK_EQ, DCHECK_EQ, v8::base::ElapsedTimer::Elapsed(), v8::internal::GetUncompressedSize(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::MemCopy(), v8::internal::PrintF(), v8::internal::SnapshotData::RawData(), v8::internal::SnapshotData::Resize(), v8::base::Vector< T >::size(), v8::base::ElapsedTimer::Start(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::CreateSnapshotBlob().
Decompress()
SnapshotData v8::internal::SnapshotCompression::Decompress (base::Vector< const uint8_t > compressed_data) [static]
Definition at line 66 of file snapshot-compression.cc.
                                               {
  SnapshotData snapshot_data;
  base::ElapsedTimer timer;
  if (v8_flags.profile_deserialization) timer.Start();
  const Bytef* input_bytef =
      reinterpret_cast<const Bytef*>(compressed_data.begin());
  // Since we are doing raw compression (no zlib or gzip headers), we need to
  // manually retrieve the uncompressed size.
  uint32_t uncompressed_payload_length = GetUncompressedSize(input_bytef);
  input_bytef += sizeof(uncompressed_payload_length);
  snapshot_data.AllocateData(uncompressed_payload_length);
  uLongf uncompressed_size = uncompressed_payload_length;
  CHECK_EQ(zlib_internal::UncompressHelper(
               zlib_internal::ZRAW,
               const_cast<Bytef*>(snapshot_data.RawData().begin()),
               &uncompressed_size, input_bytef,
               static_cast<uLong>(compressed_data.size() -
                                  sizeof(uncompressed_payload_length))),
           Z_OK);
  if (v8_flags.profile_deserialization) {
    double ms = timer.Elapsed().InMillisecondsF();
    PrintF("[Decompressing %d bytes took %0.3f ms]\n",
           uncompressed_payload_length, ms);
  }
  return snapshot_data;
}
References v8::internal::SerializedData::AllocateData(), v8::base::Vector< T >::begin(), CHECK_EQ, v8::base::ElapsedTimer::Elapsed(), v8::internal::GetUncompressedSize(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::PrintF(), v8::internal::SnapshotData::RawData(), v8::base::Vector< T >::size(), v8::base::ElapsedTimer::Start(), and v8::internal::v8_flags.
Referenced by v8::internal::MaybeDecompress().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/snapshot-compression.h
/mnt/V8SourceCode/src/snapshot/snapshot-compression.cc