v8::internal::Scope Class Reference
#include <scopes.h>
Classes
class Snapshot
Public Types
enum class DeserializationMode { kIncludingVariables
, kScopesOnly
 }
enum Iteration { kContinue
, kDescend
 }
Public Member Functions
Scope (Zone *zone, Scope *outer_scope, ScopeType scope_type)
int UniqueIdInScript () const
DeclarationScope * AsDeclarationScope ()
const DeclarationScope * AsDeclarationScope () const
ModuleScope * AsModuleScope ()
const ModuleScope * AsModuleScope () const
ClassScope * AsClassScope ()
const ClassScope * AsClassScope () const
bool is_reparsed () const
void RewriteReplGlobalVariables ()
Scope * FinalizeBlockScope ()
Zone * zone () const
void SetMustUsePreparseData ()
bool must_use_preparsed_scope_data () const
Variable * LookupLocal (const AstRawString *name)
Variable * LookupInScopeInfo (const AstRawString *name, Scope *cache)
Variable * DeclareLocal (const AstRawString *name, VariableMode mode, VariableKind kind, bool *was_added, InitializationFlag init_flag=kCreatedInitialized)
Variable * DeclareVariable (Declaration *declaration, const AstRawString *name, int pos, VariableMode mode, VariableKind kind, InitializationFlag init, bool *was_added, bool *sloppy_mode_block_scope_function_redefinition, bool *ok)
Variable * DeclareVariableName (const AstRawString *name, VariableMode mode, bool *was_added, VariableKind kind=NORMAL_VARIABLE)
Variable * DeclareCatchVariableName (const AstRawString *name)
Variable * DeclareHomeObjectVariable (AstValueFactory *ast_value_factory)
Variable * DeclareStaticHomeObjectVariable (AstValueFactory *ast_value_factory)
base::ThreadedList< Declaration > * declarations ()
base::ThreadedList< Variable > * locals ()
VariableProxy * NewUnresolved (AstNodeFactory *factory, const AstRawString *name, int start_pos, VariableKind kind=NORMAL_VARIABLE)
void AddUnresolved (VariableProxy *proxy)
void DeleteUnresolved (VariableProxy *var)
Variable * NewTemporary (const AstRawString *name)
const AstRawString * FindVariableDeclaredIn (Scope *scope, VariableMode mode_limit)
void RecordEvalCall ()
void RecordInnerScopeEvalCall ()
void SetLanguageMode (LanguageMode language_mode)
void SetNonlinear ()
int start_position () const
void set_start_position (int statement_pos)
int end_position () const
void set_end_position (int statement_pos)
bool is_hidden () const
void set_is_hidden ()
void ForceContextAllocationForParameters ()
bool has_forced_context_allocation_for_parameters () const
bool is_eval_scope () const
bool is_function_scope () const
bool is_module_scope () const
bool is_script_scope () const
bool is_catch_scope () const
bool is_block_scope () const
bool is_with_scope () const
bool is_declaration_scope () const
bool is_class_scope () const
bool is_home_object_scope () const
bool is_block_scope_for_object_literal () const
void set_is_block_scope_for_object_literal ()
bool inner_scope_calls_eval () const
bool private_name_lookup_skips_outer_class () const
bool has_using_declaration () const
bool has_await_using_declaration () const
bool has_context_cells () const
bool is_wrapped_function () const
void set_is_wrapped_function ()
bool is_nonlinear () const
bool ForceContextForLanguageMode () const
bool NeedsContext () const
template<typename FunctionType >
void ForEach (FunctionType callback)
bool IsConstructorScope () const
bool IsOuterScopeOf (Scope *other) const
ScopeType scope_type () const
LanguageMode language_mode () const
Scope * inner_scope () const
Scope * sibling () const
Scope * outer_scope () const
Variable * catch_variable () const
bool ShouldBanArguments ()
int num_stack_slots () const
int num_heap_slots () const
bool HasContextExtensionSlot () const
int ContextHeaderLength () const
int ContextLocalCount () const
bool AllowsLazyParsingWithoutUnresolvedVariables (const Scope *outer) const
int ContextChainLength (Scope *scope) const
int ContextChainLengthUntilOutermostSloppyEval () const
DeclarationScope * GetDeclarationScope ()
DeclarationScope * GetNonEvalDeclarationScope ()
DeclarationScope * GetClosureScope ()
const DeclarationScope * GetClosureScope () const
DeclarationScope * GetReceiverScope ()
DeclarationScope * GetConstructorScope ()
Scope * GetHomeObjectScope ()
DeclarationScope * GetScriptScope ()
Scope * GetOuterScopeWithContext ()
bool HasReceiverToDeserialize () const
bool HasThisReference () const
Handle< ScopeInfo > scope_info () const
int num_var () const
bool HasSimpleParameters ()
void set_is_dynamic_scope ()
bool is_debug_evaluate_scope () const
bool IsSkippableFunctionScope ()
bool is_repl_mode_scope () const
bool needs_home_object () const
void set_needs_home_object ()
bool RemoveInnerScope (Scope *inner_scope)
Variable * LookupInScopeOrScopeInfo (const AstRawString *name, Scope *cache)
Variable * LookupForTesting (const AstRawString *name)
void ForceDynamicLookup (VariableProxy *proxy)
void RemoveDynamic ()
template<typename IsolateT >
void AllocateScopeInfosRecursively (IsolateT *isolate, MaybeHandle< ScopeInfo > outer_scope, std::unordered_map< int, Handle< ScopeInfo >> &scope_infos_to_reuse)
Static Public Member Functions
template<typename IsolateT >
static Scope * DeserializeScopeChain (IsolateT *isolate, Zone *zone, Tagged< ScopeInfo > scope_info, DeclarationScope *script_scope, AstValueFactory *ast_value_factory, DeserializationMode deserialization_mode, ParseInfo *info=nullptr)
template<typename IsolateT >
static void SetScriptScopeInfo (IsolateT *isolate, DeclarationScope *script_scope)
Protected Member Functions
Scope (Zone *zone, ScopeType scope_type)
void set_language_mode (LanguageMode language_mode)
Private Types
enum ScopeLookupMode { kParsedScope
, kDeserializedScope
 }
Private Member Functions
Variable * Declare (Zone *zone, const AstRawString *name, VariableMode mode, VariableKind kind, InitializationFlag initialization_flag, MaybeAssignedFlag maybe_assigned_flag, bool *was_added)
bool NeedsScopeInfo () const
Variable * NewTemporary (const AstRawString *name, MaybeAssignedFlag maybe_assigned)
void SavePreparseData (Parser *parser)
Variable * NonLocal (const AstRawString *name, VariableMode mode)
void ResolveTo (VariableProxy *proxy, Variable *var)
void ResolveVariable (VariableProxy *proxy)
V8_WARN_UNUSED_RESULT bool ResolveVariablesRecursively (Scope *end)
void AnalyzePartially (DeclarationScope *max_outer_scope, AstNodeFactory *ast_node_factory, UnresolvedList *new_unresolved_list, bool maybe_in_arrowhead)
bool MustAllocate (Variable *var)
bool MustAllocateInContext (Variable *var)
void AllocateStackSlot (Variable *var)
void AllocateHeapSlot (Variable *var)
void AllocateNonParameterLocal (Variable *var)
void AllocateDeclaredGlobal (Variable *var)
void AllocateNonParameterLocalsAndDeclaredGlobals ()
void AllocateVariablesRecursively ()
template<typename IsolateT >
void AllocateScopeInfosRecursively (IsolateT *isolate, MaybeHandle< ScopeInfo > outer_scope, std::unordered_map< int, IndirectHandle< ScopeInfo >> &scope_infos_to_reuse)
Scope (Zone *zone, ScopeType type, AstValueFactory *ast_value_factory, Handle< ScopeInfo > scope_info)
Scope (Zone *zone, const AstRawString *catch_variable_name, MaybeAssignedFlag maybe_assigned, Handle< ScopeInfo > scope_info)
void AddInnerScope (Scope *inner_scope)
void SetDefaults ()
Static Private Member Functions
template<ScopeLookupMode mode>
static Variable * Lookup (VariableProxy *proxy, Scope *scope, Scope *outer_scope_end, Scope *cache_scope=nullptr, bool force_context_allocation=false)
static Variable * LookupWith (VariableProxy *proxy, Scope *scope, Scope *outer_scope_end, Scope *cache_scope, bool force_context_allocation)
static Variable * LookupSloppyEval (VariableProxy *proxy, Scope *scope, Scope *outer_scope_end, Scope *cache_scope, bool force_context_allocation)
static void ResolvePreparsedVariable (VariableProxy *proxy, Scope *scope, Scope *end)
Private Attributes
friend Zone
Scope * outer_scope_
Scope * inner_scope_
Scope * sibling_
VariableMap variables_
base::ThreadedList< Variable > locals_
UnresolvedList unresolved_list_
base::ThreadedList< Declaration > decls_
IndirectHandle< ScopeInfo > scope_info_
int start_position_
int end_position_
int num_stack_slots_
int num_heap_slots_
const ScopeType scope_type_
bool is_strict_: 1
bool calls_eval_: 1
bool sloppy_eval_can_extend_vars_: 1
bool scope_nonlinear_: 1
bool is_hidden_: 1
bool is_dynamic_scope_: 1
bool inner_scope_calls_eval_: 1
bool force_context_allocation_for_parameters_: 1
bool is_declaration_scope_: 1
bool private_name_lookup_skips_outer_class_: 1
bool must_use_preparsed_scope_data_: 1
bool needs_home_object_: 1
bool is_block_scope_for_object_literal_: 1
bool has_using_declaration_: 1
bool has_await_using_declaration_: 1
bool is_wrapped_function_: 1
bool has_context_cells_: 1
Friends
class DeclarationScope
class ClassScope
class ScopeTestHelper
Detailed Description
Definition at line 91 of file scopes.h.
Member Enumeration Documentation
DeserializationMode
enum v8::internal::Scope::DeserializationMode [strong]
Enumerator
kIncludingVariables
kScopesOnly
Definition at line 160 of file scopes.h.
{ kIncludingVariables, kScopesOnly };
Iteration
enum v8::internal::Scope::Iteration
Enumerator
kContinue
kDescend
Definition at line 461 of file scopes.h.
                 {
    // Continue the iteration on the same level, do not recurse/descent into
    // inner scopes.
    kContinue,
    // Recurse/descend into inner scopes.
    kDescend
  };
ScopeLookupMode
enum v8::internal::Scope::ScopeLookupMode [private]
Enumerator
kParsedScope
kDeserializedScope
Definition at line 699 of file scopes.h.
                       {
    kParsedScope,
    kDeserializedScope,
  };
Constructor & Destructor Documentation
Scope() [1/4]
v8::internal::Scope::Scope (Zone * zone, Scope * outer_scope, ScopeType scope_type)
Definition at line 115 of file scopes.cc.
    : outer_scope_(outer_scope), variables_(zone), scope_type_(scope_type) {
  DCHECK(!is_script_scope());
  SetDefaults();
  set_language_mode(outer_scope->language_mode());
  private_name_lookup_skips_outer_class_ =
      outer_scope->is_class_scope() &&
      outer_scope->AsClassScope()->IsParsingHeritage();
  outer_scope_->AddInnerScope(this);
}
References AddInnerScope(), AsClassScope(), v8::internal::DCHECK(), is_class_scope(), is_script_scope(), v8::internal::ClassScope::IsParsingHeritage(), language_mode(), outer_scope(), outer_scope_, private_name_lookup_skips_outer_class_, set_language_mode(), and SetDefaults().
Scope() [2/4]
v8::internal::Scope::Scope (Zone * zone, ScopeType scope_type) [protected]
Definition at line 109 of file scopes.cc.
    : outer_scope_(nullptr), variables_(zone), scope_type_(scope_type) {
  DCHECK(is_script_scope());
  SetDefaults();
}
References v8::internal::DCHECK(), is_script_scope(), and SetDefaults().
Scope() [3/4]
v8::internal::Scope::Scope (Zone * zone, ScopeType type, AstValueFactory * ast_value_factory, Handle< ScopeInfo > scope_info) [private]
Definition at line 247 of file scopes.cc.
    : outer_scope_(nullptr),
      variables_(zone),
      scope_info_(scope_info),
      scope_type_(scope_type) {
  DCHECK(!scope_info.is_null());
  SetDefaults();
#ifdef DEBUG
  already_resolved_ = true;
#endif
  set_language_mode(scope_info->language_mode());
  DCHECK_EQ(ContextHeaderLength(), num_heap_slots_);
  private_name_lookup_skips_outer_class_ =
      scope_info->PrivateNameLookupSkipsOuterClass();
  // We don't really need to use the preparsed scope data; this is just to
  // shorten the recursion in SetMustUsePreparseData.
  must_use_preparsed_scope_data_ = true;
  if (scope_type == BLOCK_SCOPE) {
    // Set is_block_scope_for_object_literal_ based on the existence of the home
    // object variable (we don't store it explicitly).
    DCHECK_NOT_NULL(ast_value_factory);
    int home_object_index = scope_info->ContextSlotIndex(
        *ast_value_factory->dot_home_object_string()->string());
    DCHECK_IMPLIES(home_object_index >= 0,
                   scope_type == CLASS_SCOPE || scope_type == BLOCK_SCOPE);
    if (home_object_index >= 0) {
      is_block_scope_for_object_literal_ = true;
    }
  }
  has_context_cells_ = scope_info->HasContextCells();
}
References v8::internal::BLOCK_SCOPE, v8::internal::CLASS_SCOPE, ContextHeaderLength(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, has_context_cells_, is_block_scope_for_object_literal_, must_use_preparsed_scope_data_, num_heap_slots_, private_name_lookup_skips_outer_class_, scope_info(), scope_type(), set_language_mode(), and SetDefaults().
Scope() [4/4]
v8::internal::Scope::Scope (Zone * zone, const AstRawString * catch_variable_name, MaybeAssignedFlag maybe_assigned, Handle< ScopeInfo > scope_info) [private]
Definition at line 300 of file scopes.cc.
    : outer_scope_(nullptr),
      variables_(zone),
      scope_info_(scope_info),
      scope_type_(CATCH_SCOPE) {
  SetDefaults();
#ifdef DEBUG
  already_resolved_ = true;
#endif
  // Cache the catch variable, even though it's also available via the
  // scope_info, as the parser expects that a catch scope always has the catch
  // variable as first and only variable.
  bool was_added;
  Variable* variable =
      Declare(zone, catch_variable_name, VariableMode::kVar, NORMAL_VARIABLE,
              kCreatedInitialized, maybe_assigned, &was_added);
  DCHECK(was_added);
  AllocateHeapSlot(variable);
}
References AllocateHeapSlot(), v8::internal::DCHECK(), Declare(), v8::internal::kCreatedInitialized, v8::internal::kVar, v8::internal::NORMAL_VARIABLE, SetDefaults(), and zone().
Member Function Documentation
AddInnerScope()
void v8::internal::Scope::AddInnerScope (Scope * inner_scope) [inline], [private]
Definition at line 757 of file scopes.h.
                                         {
    inner_scope->sibling_ = inner_scope_;
    inner_scope_ = inner_scope;
    inner_scope->outer_scope_ = this;
  }
References outer_scope_, and sibling_.
Referenced by DeserializeScopeChain(), and Scope().
AddUnresolved()
void v8::internal::Scope::AddUnresolved (VariableProxy * proxy)
Definition at line 1250 of file scopes.cc.
                                              {
  // The scope is only allowed to already be resolved if we're reparsing a class
  // initializer. Class initializers will manually resolve these references
  // separate from regular variable resolution.
  DCHECK_IMPLIES(already_resolved_, reparsing_for_class_initializer_);
  DCHECK(!proxy->is_resolved());
  unresolved_list_.Add(proxy);
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::VariableProxy::is_resolved(), and unresolved_list_.
AllocateDeclaredGlobal()
void v8::internal::Scope::AllocateDeclaredGlobal (Variable * var) [private]
AllocateHeapSlot()
void v8::internal::Scope::AllocateHeapSlot (Variable * var) [inline], [private]
Definition at line 2441 of file scopes.cc.
                                          {
  var->AllocateTo(VariableLocation::CONTEXT, num_heap_slots_++);
}
References v8::internal::Variable::AllocateTo(), v8::internal::CONTEXT, and num_heap_slots_.
Referenced by AllocateNonParameterLocal(), v8::internal::DeclarationScope::AllocateParameter(), and Scope().
AllocateNonParameterLocal()
void v8::internal::Scope::AllocateNonParameterLocal (Variable * var) [private]
Definition at line 2509 of file scopes.cc.
                                                   {
  DCHECK_EQ(var->scope(), this);
  if (var->IsUnallocated() && MustAllocate(var)) {
    if (MustAllocateInContext(var)) {
      AllocateHeapSlot(var);
      DCHECK_IMPLIES(is_catch_scope(),
                     var->index() == Context::THROWN_OBJECT_INDEX);
    } else {
      AllocateStackSlot(var);
    }
  }
}
References AllocateHeapSlot(), AllocateStackSlot(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Variable::index(), is_catch_scope(), v8::internal::Variable::IsUnallocated(), MustAllocate(), MustAllocateInContext(), v8::internal::Variable::scope(), and v8::internal::Context::THROWN_OBJECT_INDEX.
Referenced by v8::internal::DeclarationScope::AllocateLocals(), and AllocateNonParameterLocalsAndDeclaredGlobals().
AllocateNonParameterLocalsAndDeclaredGlobals()
void v8::internal::Scope::AllocateNonParameterLocalsAndDeclaredGlobals () [inline], [private]
Definition at line 2522 of file scopes.cc.
                                                         {
  if (is_declaration_scope() && AsDeclarationScope()->is_arrow_scope()) {
    // In arrow functions, allocate non-temporaries first and then all the
    // temporaries to make the local variable ordering stable when reparsing to
    // collect source positions.
    for (Variable* local : locals_) {
      if (local->mode() != VariableMode::kTemporary)
        AllocateNonParameterLocal(local);
    }
    for (Variable* local : locals_) {
      if (local->mode() == VariableMode::kTemporary)
        AllocateNonParameterLocal(local);
    }
  } else {
    for (Variable* local : locals_) {
      AllocateNonParameterLocal(local);
    }
  }
  if (is_declaration_scope()) {
    AsDeclarationScope()->AllocateLocals();
  }
}
References v8::internal::DeclarationScope::AllocateLocals(), AllocateNonParameterLocal(), AsDeclarationScope(), is_declaration_scope(), v8::internal::kTemporary, and locals_.
Referenced by AllocateVariablesRecursively().
AllocateScopeInfosRecursively() [1/2]
template<typename IsolateT >
void v8::internal::Scope::AllocateScopeInfosRecursively (IsolateT * isolate, MaybeHandle< ScopeInfo > outer_scope, std::unordered_map< int, Handle< ScopeInfo >> & scope_infos_to_reuse)
Definition at line 2665 of file scopes.cc.
                                                                    {
  DCHECK(scope_info_.is_null());
  MaybeHandle<ScopeInfo> next_outer_scope = outer_scope;
  auto it = scope_infos_to_reuse.find(UniqueIdInScript());
  if (it != scope_infos_to_reuse.end()) {
    scope_info_ = it->second;
    DCHECK(!scope_info_.is_null());
    CHECK_EQ(scope_info_->scope_type(), scope_type_);
    CHECK_EQ(scope_info_->HasContext(), NeedsContext());
    CHECK_EQ(scope_info_->ContextLength(), num_heap_slots_);
#ifdef DEBUG
    // Consume the scope info.
    it->second = {};
#endif
  } else if (NeedsScopeInfo()) {
    scope_info_ = ScopeInfo::Create(isolate, zone(), this, outer_scope);
#ifdef DEBUG
    // Mark this ID as being used.
    if (v8_flags.reuse_scope_infos) {
      scope_infos_to_reuse[UniqueIdInScript()] = {};
      DCHECK_EQ(UniqueIdInScript(), scope_info_->UniqueIdInScript());
    }
#endif
  }
  // The ScopeInfo chain mirrors the context chain, so we only link to the
  // next outer scope that needs a context.
  if (NeedsContext()) next_outer_scope = scope_info_;
  // Allocate ScopeInfos for inner scopes.
  for (Scope* scope = inner_scope_; scope != nullptr; scope = scope->sibling_) {
#ifdef DEBUG
    DCHECK_GT(scope->UniqueIdInScript(), UniqueIdInScript());
    DCHECK_IMPLIES(scope->sibling_, scope->sibling_->UniqueIdInScript() !=
                                        scope->UniqueIdInScript());
#endif
    if (!scope->is_function_scope() ||
        scope->AsDeclarationScope()->ShouldEagerCompile()) {
      scope->AllocateScopeInfosRecursively(isolate, next_outer_scope,
                                           scope_infos_to_reuse);
    } else if (v8_flags.reuse_scope_infos) {
      auto scope_it = scope_infos_to_reuse.find(scope->UniqueIdInScript());
      if (scope_it != scope_infos_to_reuse.end()) {
        scope->scope_info_ = scope_it->second;
#ifdef DEBUG
        // Consume the scope info
        scope_it->second = {};
#endif
      }
    }
  }
}
References CHECK_EQ, v8::internal::ScopeInfo::Create(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_IMPLIES, inner_scope_, NeedsContext(), NeedsScopeInfo(), num_heap_slots_, outer_scope(), scope_info_, scope_type_, sibling_, UniqueIdInScript(), v8::internal::v8_flags, and zone().
AllocateScopeInfosRecursively() [2/2]
template<typename IsolateT >
void v8::internal::Scope::AllocateScopeInfosRecursively (IsolateT * isolate, MaybeHandle< ScopeInfo > outer_scope, std::unordered_map< int, IndirectHandle< ScopeInfo >> & scope_infos_to_reuse) [private]
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos().
AllocateStackSlot()
void v8::internal::Scope::AllocateStackSlot (Variable * var) [private]
Definition at line 2432 of file scopes.cc.
                                           {
  if (is_block_scope()) {
    outer_scope()->GetDeclarationScope()->AllocateStackSlot(var);
  } else {
    var->AllocateTo(VariableLocation::LOCAL, num_stack_slots_++);
  }
}
References AllocateStackSlot(), v8::internal::Variable::AllocateTo(), GetDeclarationScope(), is_block_scope(), v8::internal::LOCAL, num_stack_slots_, and outer_scope().
Referenced by AllocateNonParameterLocal(), and AllocateStackSlot().
AllocateVariablesRecursively()
void v8::internal::Scope::AllocateVariablesRecursively () [private]
Definition at line 2607 of file scopes.cc.
                                         {
  this->ForEach([](Scope* scope) -> Iteration {
    DCHECK(!scope->already_resolved_);
    if (WasLazilyParsed(scope)) return Iteration::kContinue;
    if (scope->sloppy_eval_can_extend_vars_) {
      scope->num_heap_slots_ = Context::MIN_CONTEXT_EXTENDED_SLOTS;
    }
    DCHECK_EQ(scope->ContextHeaderLength(), scope->num_heap_slots_);
    // Allocate variables for this scope.
    // Parameters must be allocated first, if any.
    if (scope->is_declaration_scope()) {
      scope->AsDeclarationScope()->AllocateReceiver();
      if (scope->is_function_scope()) {
        scope->AsDeclarationScope()->AllocateParameterLocals();
      }
    }
    scope->AllocateNonParameterLocalsAndDeclaredGlobals();
    // Force allocation of a context for this scope if necessary. For a 'with'
    // scope and for a function scope that makes an 'eval' call we need a
    // context, even if no local variables were statically allocated in the
    // scope. Likewise for modules and function scopes representing asm.js
    // modules. Also force a context, if the scope is stricter than the outer
    // scope.
    bool must_have_context =
        scope->is_with_scope() || scope->is_module_scope() ||
#if V8_ENABLE_WEBASSEMBLY
        scope->IsAsmModule() ||
#endif // V8_ENABLE_WEBASSEMBLY
        scope->ForceContextForLanguageMode() ||
        (scope->is_function_scope() &&
         scope->AsDeclarationScope()->sloppy_eval_can_extend_vars()) ||
        (scope->is_block_scope() && scope->is_declaration_scope() &&
         scope->AsDeclarationScope()->sloppy_eval_can_extend_vars());
    // If we didn't allocate any locals in the local context, then we only
    // need the minimal number of slots if we must have a context.
    if (scope->num_heap_slots_ == scope->ContextHeaderLength() &&
        !must_have_context) {
      scope->num_heap_slots_ = 0;
    }
    // If the number of context slots are over the function context threshold,
    // do not allocate context cells.
    if (scope->is_function_scope() &&
        scope->ContextLocalCount() > v8_flags.function_context_cells_max_size) {
      scope->has_context_cells_ = false;
    }
    // Allocation done.
    DCHECK(scope->num_heap_slots_ == 0 ||
           scope->num_heap_slots_ >= scope->ContextHeaderLength());
    return Iteration::kDescend;
  });
}
References AllocateNonParameterLocalsAndDeclaredGlobals(), v8::internal::DeclarationScope::AllocateParameterLocals(), v8::internal::DeclarationScope::AllocateReceiver(), AsDeclarationScope(), ContextHeaderLength(), ContextLocalCount(), v8::internal::DCHECK(), DCHECK_EQ, ForceContextForLanguageMode(), ForEach(), has_context_cells_, is_block_scope(), is_declaration_scope(), is_function_scope(), is_module_scope(), is_with_scope(), v8::internal::Context::MIN_CONTEXT_EXTENDED_SLOTS, num_heap_slots_, v8::internal::DeclarationScope::sloppy_eval_can_extend_vars(), sloppy_eval_can_extend_vars_, v8::internal::v8_flags, and v8::internal::anonymous_namespace{scopes.cc}::WasLazilyParsed().
Referenced by v8::internal::DeclarationScope::AllocateVariables().
AllowsLazyParsingWithoutUnresolvedVariables()
bool v8::internal::Scope::AllowsLazyParsingWithoutUnresolvedVariables (const Scope * outer) const
Definition at line 1425 of file scopes.cc.
                              {
  // If none of the outer scopes need to decide whether to context allocate
  // specific variables, we can preparse inner functions without unresolved
  // variables. Otherwise we need to find unresolved variables to force context
  // allocation of the matching declarations. We can stop at the outer scope for
  // the parse, since context allocation of those variables is already
  // guaranteed to be correct.
  for (const Scope* s = this; s != outer; s = s->outer_scope_) {
    // Eval forces context allocation on all outer scopes, so we don't need to
    // look at those scopes. Sloppy eval makes top-level non-lexical variables
    // dynamic, whereas strict-mode requires context allocation.
    if (s->is_eval_scope()) return is_sloppy(s->language_mode());
    // Catch scopes force context allocation of all variables.
    if (s->is_catch_scope()) continue;
    // With scopes do not introduce variables that need allocation.
    if (s->is_with_scope()) continue;
    DCHECK(s->is_module_scope() || s->is_block_scope() ||
           s->is_function_scope());
    return false;
  }
  return true;
}
References v8::internal::DCHECK(), v8::internal::is_sloppy(), and outer_scope_.
AnalyzePartially()
void v8::internal::Scope::AnalyzePartially (DeclarationScope * max_outer_scope, AstNodeFactory * ast_node_factory, UnresolvedList * new_unresolved_list, bool maybe_in_arrowhead) [private]
Definition at line 1625 of file scopes.cc.
                                                      {
  this->ForEach([max_outer_scope, ast_node_factory, new_unresolved_list,
                 maybe_in_arrowhead](Scope* scope) {
    // Skip already lazily parsed scopes. This can only happen to functions
    // inside arrowheads.
    if (WasLazilyParsed(scope)) {
      DCHECK(max_outer_scope->is_arrow_scope());
      return Iteration::kContinue;
    }
    for (VariableProxy* proxy = scope->unresolved_list_.first();
         proxy != nullptr; proxy = proxy->next_unresolved()) {
      if (proxy->is_removed_from_unresolved()) continue;
      DCHECK(!proxy->is_resolved());
      Variable* var =
          Lookup<kParsedScope>(proxy, scope, max_outer_scope->outer_scope());
      if (var == nullptr) {
        // Don't copy unresolved references to the script scope, unless it's a
        // reference to a private name or method. In that case keep it so we
        // can fail later.
        if (!max_outer_scope->outer_scope()->is_script_scope() ||
            maybe_in_arrowhead) {
          VariableProxy* copy = ast_node_factory->CopyVariableProxy(proxy);
          new_unresolved_list->Add(copy);
        }
      } else {
        var->set_is_used();
        if (proxy->is_assigned()) var->SetMaybeAssigned();
      }
    }
    // Clear unresolved_list_ as it's in an inconsistent state.
    scope->unresolved_list_.Clear();
    return Iteration::kDescend;
  });
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::internal::AstNodeFactory::CopyVariableProxy(), v8::internal::DCHECK(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first(), ForEach(), v8::internal::DeclarationScope::is_arrow_scope(), is_script_scope(), outer_scope(), v8::internal::Variable::set_is_used(), v8::internal::Variable::SetMaybeAssigned(), unresolved_list_, and v8::internal::anonymous_namespace{scopes.cc}::WasLazilyParsed().
Referenced by v8::internal::DeclarationScope::AnalyzePartially().
AsClassScope() [1/2]
ClassScope * v8::internal::Scope::AsClassScope ()
Definition at line 589 of file scopes.cc.
                                {
  SBXCHECK(is_class_scope());
  return static_cast<ClassScope*>(this);
}
References is_class_scope(), and SBXCHECK.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::ScopeInfo::Create(), v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody(), v8::internal::ParserBase< Impl >::ParseClassLiteralBody(), v8::internal::PrivateNameScopeIterator::PrivateNameScopeIterator(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::PreparseDataBuilder::SaveDataForScope(), and Scope().
AsClassScope() [2/2]
const ClassScope * v8::internal::Scope::AsClassScope () const
Definition at line 594 of file scopes.cc.
                                            {
  SBXCHECK(is_class_scope());
  return static_cast<const ClassScope*>(this);
}
References is_class_scope(), and SBXCHECK.
AsDeclarationScope() [1/2]
DeclarationScope* v8::internal::Scope::AsDeclarationScope ()
Referenced by AllocateNonParameterLocalsAndDeclaredGlobals(), AllocateVariablesRecursively(), ContextLocalCount(), v8::internal::ScopeInfo::Create(), DeserializeScopeChain(), v8::internal::Parser::DoParseProgram(), FinalizeBlockScope(), GetClosureScope(), GetConstructorScope(), GetDeclarationScope(), GetHomeObjectScope(), GetNonEvalDeclarationScope(), GetReceiverScope(), GetScriptScope(), HasThisReference(), IsConstructorScope(), IsSkippableFunctionScope(), Lookup(), LookupInScopeInfo(), LookupSloppyEval(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveClosureScope(), v8::internal::Rewriter::RewriteBody(), v8::internal::PreparseDataBuilder::SaveDataForScope(), SavePreparseData(), v8::internal::ParserBase< Impl >::FunctionState::scope(), v8::internal::PreparseDataBuilder::ScopeNeedsData(), UniqueIdInScript(), v8::internal::ScopeIterator::VisitLocals(), and v8::internal::anonymous_namespace{scopes.cc}::WasLazilyParsed().
AsDeclarationScope() [2/2]
const DeclarationScope * v8::internal::Scope::AsDeclarationScope () const
Definition at line 574 of file scopes.cc.
                                                        {
  SBXCHECK(is_declaration_scope());
  return static_cast<const DeclarationScope*>(this);
}
References is_declaration_scope(), and SBXCHECK.
AsModuleScope() [1/2]
ModuleScope * v8::internal::Scope::AsModuleScope ()
Definition at line 579 of file scopes.cc.
                                  {
  SBXCHECK(is_module_scope());
  return static_cast<ModuleScope*>(this);
}
References is_module_scope(), and SBXCHECK.
Referenced by v8::internal::DeclarationScope::AllocateVariables(), v8::internal::ScopeInfo::Create(), v8::internal::ParserBase< Impl >::module(), and v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports().
AsModuleScope() [2/2]
const ModuleScope * v8::internal::Scope::AsModuleScope () const
Definition at line 584 of file scopes.cc.
                                              {
  SBXCHECK(is_module_scope());
  return static_cast<const ModuleScope*>(this);
}
References is_module_scope(), and SBXCHECK.
catch_variable()
Variable* v8::internal::Scope::catch_variable () const [inline]
Definition at line 494 of file scopes.h.
                                   {
    DCHECK(is_catch_scope());
    DCHECK_EQ(1, num_var());
    return static_cast<Variable*>(variables_.Start()->value);
  }
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalCatchContext().
ContextChainLength()
int v8::internal::Scope::ContextChainLength (Scope * scope) const
Definition at line 1456 of file scopes.cc.
                                                {
  int n = 0;
  for (const Scope* s = this; s != scope; s = s->outer_scope_) {
    DCHECK_NOT_NULL(s); // scope must be in the scope chain
    if (s->NeedsContext()) n++;
  }
  return n;
}
References DCHECK_NOT_NULL, and outer_scope_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization().
ContextChainLengthUntilOutermostSloppyEval()
int v8::internal::Scope::ContextChainLengthUntilOutermostSloppyEval () const
Definition at line 1465 of file scopes.cc.
                                                            {
  int result = 0;
  int length = 0;
  for (const Scope* s = this; s != nullptr; s = s->outer_scope()) {
    if (!s->NeedsContext()) continue;
    length++;
    if (s->is_declaration_scope() &&
        s->AsDeclarationScope()->sloppy_eval_can_extend_vars()) {
      result = length;
    }
  }
  return result;
}
References v8::internal::length, outer_scope(), and v8::base::internal::result.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
ContextHeaderLength()
int v8::internal::Scope::ContextHeaderLength () const [inline]
Definition at line 524 of file scopes.h.
                                  {
    return HasContextExtensionSlot() ? Context::MIN_CONTEXT_EXTENDED_SLOTS
                                     : Context::MIN_CONTEXT_SLOTS;
  }
References v8::internal::Context::MIN_CONTEXT_EXTENDED_SLOTS, and v8::internal::Context::MIN_CONTEXT_SLOTS.
Referenced by AllocateVariablesRecursively(), ContextLocalCount(), v8::internal::ScopeInfo::Create(), Scope(), and SetDefaults().
ContextLocalCount()
int v8::internal::Scope::ContextLocalCount () const
Definition at line 2961 of file scopes.cc.
                                   {
  DCHECK(!is_reparsed());
  if (num_heap_slots() == 0) return 0;
  Variable* function =
      is_function_scope() ? AsDeclarationScope()->function_var() : nullptr;
  bool is_function_var_in_context =
      function != nullptr && function->IsContextSlot();
  return num_heap_slots() - ContextHeaderLength() -
         (is_function_var_in_context ? 1 : 0);
}
References AsDeclarationScope(), ContextHeaderLength(), v8::internal::DCHECK(), v8::internal::DeclarationScope::function_var(), is_function_scope(), is_reparsed(), v8::internal::Variable::IsContextSlot(), and num_heap_slots().
Referenced by AllocateVariablesRecursively(), and v8::internal::ScopeInfo::Create().
declarations()
base::ThreadedList<Declaration>* v8::internal::Scope::declarations () [inline]
Definition at line 231 of file scopes.h.
{ return &decls_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::Parser::DeclareClassVariable(), v8::internal::PreParser::DeclareVariableName(), v8::internal::Parser::InsertShadowingVarBindingInitializers(), v8::internal::ParserBase< Impl >::ParseFormalParameter(), v8::internal::ParserBase< Impl >::ParseTryStatement(), v8::internal::ParserBase< Impl >::ParseVariableDeclarations(), v8::internal::Parser::ReportVarRedeclarationIn(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), and v8::internal::interpreter::BytecodeGenerator::VisitInScope().
Declare()
Variable* v8::internal::Scope::Declare (Zone * zone, const AstRawString * name, VariableMode mode, VariableKind kind, InitializationFlag initialization_flag, MaybeAssignedFlag maybe_assigned_flag, bool * was_added) [inline], [private]
Definition at line 669 of file scopes.h.
                                                                            {
    // Static variables can only be declared using ClassScope methods.
    Variable* result = variables_.Declare(
        zone, this, name, mode, kind, initialization_flag, maybe_assigned_flag,
        IsStaticFlag::kNotStatic, was_added);
    if (mode == VariableMode::kUsing) has_using_declaration_ = true;
    if (mode == VariableMode::kAwaitUsing) has_await_using_declaration_ = true;
    if (*was_added) locals_.Add(result);
    return result;
  }
References v8::internal::kAwaitUsing, v8::internal::kNotStatic, v8::internal::kUsing, mode(), v8::internal::name, and v8::base::internal::result.
Referenced by v8::internal::DeclarationScope::DeclareArguments(), v8::internal::ClassScope::DeclareBrandVariable(), DeclareCatchVariableName(), v8::internal::ClassScope::DeclareClassVariable(), v8::internal::DeclarationScope::DeclareDefaultFunctionVariables(), DeclareHomeObjectVariable(), DeclareLocal(), DeclareStaticHomeObjectVariable(), and Scope().
DeclareCatchVariableName()
Variable * v8::internal::Scope::DeclareCatchVariableName (const AstRawString * name)
Definition at line 1238 of file scopes.cc.
                                                                  {
  DCHECK(!already_resolved_);
  DCHECK(is_catch_scope());
  DCHECK(scope_info_.is_null());
  bool was_added;
  Variable* result = Declare(zone(), name, VariableMode::kVar, NORMAL_VARIABLE,
                             kCreatedInitialized, kNotAssigned, &was_added);
  DCHECK(was_added);
  return result;
}
References v8::internal::DCHECK(), Declare(), is_catch_scope(), v8::internal::kCreatedInitialized, v8::internal::kNotAssigned, v8::internal::kVar, v8::internal::name, v8::internal::NORMAL_VARIABLE, v8::base::internal::result, scope_info_, and zone().
Referenced by v8::internal::Parser::DeclareCatchVariableName(), v8::internal::PreParser::DeclareCatchVariableName(), and v8::internal::ParserBase< Impl >::ParseTryStatement().
DeclareHomeObjectVariable()
Variable * v8::internal::Scope::DeclareHomeObjectVariable (AstValueFactory * ast_value_factory)
Definition at line 126 of file scopes.cc.
                                                                             {
  bool was_added;
  Variable* home_object_variable = Declare(
      zone(), ast_value_factory->dot_home_object_string(), VariableMode::kConst,
      NORMAL_VARIABLE, InitializationFlag::kCreatedInitialized,
      MaybeAssignedFlag::kNotAssigned, &was_added);
  DCHECK(was_added);
  home_object_variable->set_is_used();
  home_object_variable->ForceContextAllocation();
  return home_object_variable;
}
References v8::internal::DCHECK(), Declare(), v8::internal::Variable::ForceContextAllocation(), v8::internal::kConst, v8::internal::kCreatedInitialized, v8::internal::kNotAssigned, v8::internal::NORMAL_VARIABLE, v8::internal::Variable::set_is_used(), and zone().
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral(), and v8::internal::ParserBase< Impl >::ParseObjectLiteral().
DeclareLocal()
Variable * v8::internal::Scope::DeclareLocal (const AstRawString * name, VariableMode mode, VariableKind kind, bool * was_added, InitializationFlag init_flag = kCreatedInitialized)
Definition at line 1080 of file scopes.cc.
                                                            {
  DCHECK(!already_resolved_);
  // Private methods should be declared with ClassScope::DeclarePrivateName()
  DCHECK(!IsPrivateMethodOrAccessorVariableMode(mode));
  // This function handles VariableMode::kVar, VariableMode::kLet,
  // VariableMode::kConst, VariableMode::kUsing, and VariableMode::kAwaitUsing
  // modes. VariableMode::kDynamic variables are introduced during variable
  // allocation, and VariableMode::kTemporary variables are allocated via
  // NewTemporary().
  DCHECK(IsDeclaredVariableMode(mode));
  DCHECK_IMPLIES(GetDeclarationScope()->is_being_lazily_parsed(),
                 mode == VariableMode::kVar || mode == VariableMode::kLet ||
                     mode == VariableMode::kConst ||
                     mode == VariableMode::kUsing ||
                     mode == VariableMode::kAwaitUsing);
  DCHECK(!GetDeclarationScope()->was_lazily_parsed());
  Variable* var =
      Declare(zone(), name, mode, kind, init_flag, kNotAssigned, was_added);
  // Pessimistically assume that top-level variables will be assigned and used.
  //
  // Top-level variables in a script can be accessed by other scripts or even
  // become global properties. While this does not apply to top-level variables
  // in a module (assuming they are not exported), we must still mark these as
  // assigned because they might be accessed by a lazily parsed top-level
  // function, which, for efficiency, we preparse without variable tracking.
  if (is_script_scope() || is_module_scope()) {
    if (mode != VariableMode::kConst) var->SetMaybeAssigned();
    var->set_is_used();
  }
  return var;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, Declare(), GetDeclarationScope(), is_module_scope(), is_script_scope(), v8::internal::IsDeclaredVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::kAwaitUsing, v8::internal::kConst, v8::internal::kLet, v8::internal::kNotAssigned, v8::internal::kUsing, v8::internal::kVar, mode(), v8::internal::name, v8::internal::Variable::set_is_used(), v8::internal::Variable::SetMaybeAssigned(), and zone().
Referenced by DeclareVariable(), and DeclareVariableName().
DeclareStaticHomeObjectVariable()
Variable * v8::internal::Scope::DeclareStaticHomeObjectVariable (AstValueFactory * ast_value_factory)
Definition at line 138 of file scopes.cc.
                                        {
  bool was_added;
  Variable* static_home_object_variable =
      Declare(zone(), ast_value_factory->dot_static_home_object_string(),
              VariableMode::kConst, NORMAL_VARIABLE,
              InitializationFlag::kCreatedInitialized,
              MaybeAssignedFlag::kNotAssigned, &was_added);
  DCHECK(was_added);
  static_home_object_variable->set_is_used();
  static_home_object_variable->ForceContextAllocation();
  return static_home_object_variable;
}
References v8::internal::DCHECK(), Declare(), v8::internal::Variable::ForceContextAllocation(), v8::internal::kConst, v8::internal::kCreatedInitialized, v8::internal::kNotAssigned, v8::internal::NORMAL_VARIABLE, v8::internal::Variable::set_is_used(), and zone().
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral().
DeclareVariable()
Variable * v8::internal::Scope::DeclareVariable (Declaration * declaration, const AstRawString * name, int pos, VariableMode mode, VariableKind kind, InitializationFlag init, bool * was_added, bool * sloppy_mode_block_scope_function_redefinition, bool * ok)
Definition at line 1116 of file scopes.cc.
              {
  // Private methods should be declared with ClassScope::DeclarePrivateName()
  DCHECK(!IsPrivateMethodOrAccessorVariableMode(mode));
  DCHECK(IsDeclaredVariableMode(mode));
  DCHECK(!already_resolved_);
  DCHECK(!GetDeclarationScope()->is_being_lazily_parsed());
  DCHECK(!GetDeclarationScope()->was_lazily_parsed());
  if (mode == VariableMode::kVar && !is_declaration_scope()) {
    return GetDeclarationScope()->DeclareVariable(
        declaration, name, pos, mode, kind, init, was_added,
        sloppy_mode_block_scope_function_redefinition, ok);
  }
  DCHECK(!is_catch_scope());
  DCHECK(!is_with_scope());
  DCHECK(is_declaration_scope() ||
         (IsLexicalVariableMode(mode) && is_block_scope()));
  DCHECK_NOT_NULL(name);
  Variable* var = LookupLocal(name);
  // Declare the variable in the declaration scope.
  *was_added = var == nullptr;
  if (V8_LIKELY(*was_added)) {
    if (V8_UNLIKELY(is_eval_scope() && is_sloppy(language_mode()) &&
                    mode == VariableMode::kVar)) {
      // In a var binding in a sloppy direct eval, pollute the enclosing scope
      // with this new binding by doing the following:
      // The proxy is bound to a lookup variable to force a dynamic declaration
      // using the DeclareEvalVar or DeclareEvalFunction runtime functions.
      DCHECK_EQ(NORMAL_VARIABLE, kind);
      var = NonLocal(name, VariableMode::kDynamic);
      // Mark the var as used in case anyone outside the eval wants to use it.
      var->set_is_used();
    } else {
      // Declare the name.
      var = DeclareLocal(name, mode, kind, was_added, init);
      DCHECK(*was_added);
    }
  } else {
    var->SetMaybeAssigned();
    if (V8_UNLIKELY(IsLexicalVariableMode(mode) ||
                    IsLexicalVariableMode(var->mode()))) {
      // The name was declared in this scope before; check for conflicting
      // re-declarations. We have a conflict if either of the declarations is
      // not a var (in script scope, we also have to ignore legacy const for
      // compatibility). There is similar code in runtime.cc in the Declare
      // functions. The function CheckConflictingVarDeclarations checks for
      // var and let bindings from different scopes whereas this is a check
      // for conflicting declarations within the same scope. This check also
      // covers the special case
      //
      // function () { let x; { var x; } }
      //
      // because the var declaration is hoisted to the function scope where
      // 'x' is already bound.
      //
      // In harmony we treat re-declarations as early errors. See ES5 16 for a
      // definition of early errors.
      //
      // Allow duplicate function decls for web compat, see bug 4693.
      *ok = var->is_sloppy_block_function() &&
            kind == SLOPPY_BLOCK_FUNCTION_VARIABLE;
      *sloppy_mode_block_scope_function_redefinition = *ok;
    }
  }
  DCHECK_NOT_NULL(var);
  // We add a declaration node for every declaration. The compiler
  // will only generate code if necessary. In particular, declarations
  // for inner local variables that do not represent functions won't
  // result in any generated code.
  //
  // This will lead to multiple declaration nodes for the
  // same variable if it is declared several times. This is not a
  // semantic issue, but it may be a performance issue since it may
  // lead to repeated DeclareEvalVar or DeclareEvalFunction calls.
  decls_.Add(declaration);
  declaration->set_var(var);
  return var;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, DeclareLocal(), DeclareVariable(), decls_, GetDeclarationScope(), is_block_scope(), is_catch_scope(), is_declaration_scope(), is_eval_scope(), v8::internal::is_sloppy(), v8::internal::Variable::is_sloppy_block_function(), is_with_scope(), v8::internal::IsDeclaredVariableMode(), v8::internal::IsLexicalVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::kDynamic, v8::internal::kVar, language_mode(), LookupLocal(), v8::internal::Variable::mode(), mode(), v8::internal::name, NonLocal(), v8::internal::NORMAL_VARIABLE, v8::internal::Variable::set_is_used(), v8::internal::Declaration::set_var(), v8::internal::Variable::SetMaybeAssigned(), v8::internal::SLOPPY_BLOCK_FUNCTION_VARIABLE, V8_LIKELY, and V8_UNLIKELY.
Referenced by v8::internal::Parser::Declare(), DeclareVariable(), and v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
DeclareVariableName()
Variable * v8::internal::Scope::DeclareVariableName (const AstRawString * name, VariableMode mode, bool * was_added, VariableKind kind = NORMAL_VARIABLE)
Definition at line 1202 of file scopes.cc.
                                                        {
  DCHECK(IsDeclaredVariableMode(mode));
  DCHECK(!already_resolved_);
  DCHECK(GetDeclarationScope()->is_being_lazily_parsed());
  // Private methods should be declared with ClassScope::DeclarePrivateName()
  DCHECK(!IsPrivateMethodOrAccessorVariableMode(mode));
  if (mode == VariableMode::kVar && !is_declaration_scope()) {
    return GetDeclarationScope()->DeclareVariableName(name, mode, was_added,
                                                      kind);
  }
  DCHECK(!is_with_scope());
  DCHECK(!is_eval_scope());
  DCHECK(is_declaration_scope() || IsLexicalVariableMode(mode));
  DCHECK(scope_info_.is_null());
  // Declare the variable in the declaration scope.
  Variable* var = DeclareLocal(name, mode, kind, was_added);
  if (!*was_added) {
    if (IsLexicalVariableMode(mode) || IsLexicalVariableMode(var->mode())) {
      if (!var->is_sloppy_block_function() ||
          kind != SLOPPY_BLOCK_FUNCTION_VARIABLE) {
        // Duplicate functions are allowed in the sloppy mode, but if this is
        // not a function declaration, it's an error. This is an error PreParser
        // hasn't previously detected.
        return nullptr;
      }
      // Sloppy block function redefinition.
    }
    var->SetMaybeAssigned();
  }
  var->set_is_used();
  return var;
}
References v8::internal::DCHECK(), DeclareLocal(), DeclareVariableName(), GetDeclarationScope(), is_declaration_scope(), is_eval_scope(), v8::internal::Variable::is_sloppy_block_function(), is_with_scope(), v8::internal::IsDeclaredVariableMode(), v8::internal::IsLexicalVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::kVar, v8::internal::Variable::mode(), mode(), v8::internal::name, scope_info_, v8::internal::Variable::set_is_used(), v8::internal::Variable::SetMaybeAssigned(), and v8::internal::SLOPPY_BLOCK_FUNCTION_VARIABLE.
Referenced by DeclareVariableName(), v8::internal::PreParser::DeclareVariableName(), and v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
DeleteUnresolved()
void v8::internal::Scope::DeleteUnresolved (VariableProxy * var)
Definition at line 1270 of file scopes.cc.
                                               {
  DCHECK(unresolved_list_.Contains(var));
  var->mark_removed_from_unresolved();
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Contains(), v8::internal::DCHECK(), v8::internal::VariableProxy::mark_removed_from_unresolved(), and unresolved_list_.
Referenced by v8::internal::ParserBase< Impl >::ParseExpressionOrLabelledStatement().
DeserializeScopeChain()
template<typename IsolateT >
Scope * v8::internal::Scope::DeserializeScopeChain (IsolateT * isolate, Zone * zone, Tagged< ScopeInfo > scope_info, DeclarationScope * script_scope, AstValueFactory * ast_value_factory, DeserializationMode deserialization_mode, ParseInfo * info = nullptr) [static]
Definition at line 437 of file scopes.cc.
                                                           {
  // Reconstruct the outer scope chain from a closure's context chain.
  Scope* current_scope = nullptr;
  Scope* innermost_scope = nullptr;
  Scope* outer_scope = nullptr;
  while (!scope_info.is_null()) {
    if (scope_info->scope_type() == WITH_SCOPE) {
      if (scope_info->IsDebugEvaluateScope()) {
        outer_scope =
            zone->New<DeclarationScope>(zone, FUNCTION_SCOPE, ast_value_factory,
                                        handle(scope_info, isolate));
        outer_scope->set_is_dynamic_scope();
      } else {
        // For scope analysis, debug-evaluate is equivalent to a with scope.
        outer_scope = zone->New<Scope>(zone, WITH_SCOPE, ast_value_factory,
                                       handle(scope_info, isolate));
      }
    } else if (scope_info->is_script_scope()) {
      // If we reach a script scope, it's the outermost scope. Install the
      // scope info of this script context onto the existing script scope to
      // avoid nesting script scopes.
      if (deserialization_mode == DeserializationMode::kIncludingVariables) {
        script_scope->SetScriptScopeInfo(handle(scope_info, isolate));
      }
      DCHECK(!scope_info->HasOuterScopeInfo());
      break;
    } else if (scope_info->scope_type() == FUNCTION_SCOPE) {
      outer_scope = zone->New<DeclarationScope>(
          zone, FUNCTION_SCOPE, ast_value_factory, handle(scope_info, isolate));
#if V8_ENABLE_WEBASSEMBLY
      if (scope_info->IsAsmModule()) {
        outer_scope->AsDeclarationScope()->set_is_asm_module();
      }
#endif // V8_ENABLE_WEBASSEMBLY
    } else if (scope_info->scope_type() == EVAL_SCOPE) {
      outer_scope = zone->New<DeclarationScope>(
          zone, EVAL_SCOPE, ast_value_factory, handle(scope_info, isolate));
    } else if (scope_info->scope_type() == CLASS_SCOPE) {
      outer_scope = zone->New<ClassScope>(isolate, zone, ast_value_factory,
                                          handle(scope_info, isolate));
    } else if (scope_info->scope_type() == BLOCK_SCOPE) {
      if (scope_info->is_declaration_scope()) {
        outer_scope = zone->New<DeclarationScope>(
            zone, BLOCK_SCOPE, ast_value_factory, handle(scope_info, isolate));
      } else {
        outer_scope = zone->New<Scope>(zone, BLOCK_SCOPE, ast_value_factory,
                                       handle(scope_info, isolate));
      }
    } else if (scope_info->scope_type() == MODULE_SCOPE) {
      outer_scope = zone->New<ModuleScope>(handle(scope_info, isolate),
                                           ast_value_factory);
      if (parse_info) {
        parse_info->set_has_module_in_scope_chain();
      }
    } else {
      DCHECK_EQ(scope_info->scope_type(), CATCH_SCOPE);
      DCHECK_EQ(scope_info->ContextLocalCount(), 1);
      DCHECK_EQ(scope_info->ContextLocalMode(0), VariableMode::kVar);
      DCHECK_EQ(scope_info->ContextLocalInitFlag(0), kCreatedInitialized);
      DCHECK(scope_info->HasInlinedLocalNames());
      Tagged<String> name = scope_info->ContextInlinedLocalName(0);
      MaybeAssignedFlag maybe_assigned =
          scope_info->ContextLocalMaybeAssignedFlag(0);
      outer_scope =
          zone->New<Scope>(zone,
                           ast_value_factory->GetString(
                               name, SharedStringAccessGuardIfNeeded(isolate)),
                           maybe_assigned, handle(scope_info, isolate));
    }
    if (deserialization_mode == DeserializationMode::kScopesOnly) {
      outer_scope->scope_info_ = Handle<ScopeInfo>::null();
    }
    if (current_scope != nullptr) {
      outer_scope->AddInnerScope(current_scope);
    }
    outer_scope->set_start_position(scope_info->StartPosition());
    outer_scope->set_end_position(scope_info->EndPosition());
    current_scope = outer_scope;
    if (innermost_scope == nullptr) innermost_scope = current_scope;
    scope_info = scope_info->HasOuterScopeInfo() ? scope_info->OuterScopeInfo()
                                                 : Tagged<ScopeInfo>();
  }
  if (deserialization_mode == DeserializationMode::kIncludingVariables) {
    SetScriptScopeInfo(isolate, script_scope);
  }
  if (innermost_scope == nullptr) return script_scope;
  script_scope->AddInnerScope(current_scope);
  return innermost_scope;
}
References AddInnerScope(), AsDeclarationScope(), v8::internal::BLOCK_SCOPE, v8::internal::CATCH_SCOPE, v8::internal::CLASS_SCOPE, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::EVAL_SCOPE, v8::internal::FUNCTION_SCOPE, v8::internal::AstValueFactory::GetString(), v8::internal::handle(), v8::internal::kCreatedInitialized, kIncludingVariables, kScopesOnly, v8::internal::kVar, v8::internal::MODULE_SCOPE, v8::internal::name, v8::internal::Zone::New(), v8::internal::Handle< T >::null(), outer_scope(), scope_info(), scope_info_, set_end_position(), v8::internal::ParseInfo::set_has_module_in_scope_chain(), set_is_dynamic_scope(), set_start_position(), v8::internal::DeclarationScope::SetScriptScopeInfo(), SetScriptScopeInfo(), v8::internal::WITH_SCOPE, and zone().
Referenced by v8::internal::Parser::DeserializeScopeChain().
end_position()
int v8::internal::Scope::end_position () const [inline]
Definition at line 344 of file scopes.h.
{ return end_position_; }
Referenced by v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::ContainsPosition(), v8::internal::ScopeInfo::Create(), v8::internal::ScopeIterator::end_position(), v8::internal::FunctionLiteral::end_position(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::FindScopeInfoForScope(), v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), v8::internal::Parser::ParseFunction(), v8::internal::Parser::ParseFunctionLiteral(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::BaseConsumedPreparseData< Data >::RestoreScopeAllocationData(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveClosureScope(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveStartScope(), v8::internal::Parser::RewriteClassLiteral(), v8::internal::Parser::RewriteSwitchStatement(), v8::internal::PreparseDataBuilder::SaveDataForScope(), v8::internal::PreparseDataBuilder::SaveDataForSkippableFunction(), v8::internal::PreparseDataBuilder::SaveScopeAllocationData(), and v8::internal::Parser::SkipFunction().
FinalizeBlockScope()
Scope * v8::internal::Scope::FinalizeBlockScope ()
Definition at line 871 of file scopes.cc.
                                 {
  DCHECK(is_block_scope());
#ifdef DEBUG
  DCHECK_NE(sibling_, this);
#endif
  if (variables_.occupancy() > 0 ||
      (is_declaration_scope() &&
       AsDeclarationScope()->sloppy_eval_can_extend_vars())) {
    return this;
  }
  DCHECK(!is_class_scope());
  // Remove this scope from outer scope.
  outer_scope()->RemoveInnerScope(this);
  // Reparent inner scopes.
  if (inner_scope_ != nullptr) {
    Scope* scope = inner_scope_;
    scope->outer_scope_ = outer_scope();
    while (scope->sibling_ != nullptr) {
      scope = scope->sibling_;
      scope->outer_scope_ = outer_scope();
    }
    scope->sibling_ = outer_scope()->inner_scope_;
    outer_scope()->inner_scope_ = inner_scope_;
    inner_scope_ = nullptr;
  }
  // Move unresolved variables
  if (!unresolved_list_.is_empty()) {
    outer_scope()->unresolved_list_.Prepend(std::move(unresolved_list_));
    unresolved_list_.Clear();
  }
  if (inner_scope_calls_eval_) outer_scope()->inner_scope_calls_eval_ = true;
  // No need to propagate sloppy_eval_can_extend_vars_, since if it was relevant
  // to this scope we would have had to bail out at the top.
  DCHECK(!is_declaration_scope() ||
         !AsDeclarationScope()->sloppy_eval_can_extend_vars());
  // This block does not need a context.
  num_heap_slots_ = 0;
  // Mark scope as removed by making it its own sibling.
#ifdef DEBUG
  sibling_ = this;
#endif
  return nullptr;
}
References AsDeclarationScope(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::internal::DCHECK(), DCHECK_NE, inner_scope_, inner_scope_calls_eval_, is_block_scope(), is_class_scope(), is_declaration_scope(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::is_empty(), num_heap_slots_, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::occupancy(), outer_scope(), outer_scope_, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Prepend(), RemoveInnerScope(), sibling_, unresolved_list_, and variables_.
Referenced by v8::internal::ParserBase< Impl >::ParseForAwaitStatement(), v8::internal::ParserBase< Impl >::ParseForStatement(), v8::internal::ParserBase< Impl >::ParseFunctionBody(), v8::internal::ParserBase< Impl >::ParseObjectLiteral(), v8::internal::ParserBase< Impl >::ParseStandardForLoopWithLexicalDeclarations(), v8::internal::ParserBase< Impl >::ParseSwitchStatement(), and v8::internal::PreParser::PreParseFunction().
FindVariableDeclaredIn()
const AstRawString * v8::internal::Scope::FindVariableDeclaredIn (Scope * scope, VariableMode mode_limit)
Definition at line 1356 of file scopes.cc.
                                                                           {
  const VariableMap& variables = scope->variables_;
  for (ZoneHashMap::Entry* p = variables.Start(); p != nullptr;
       p = variables.Next(p)) {
    const AstRawString* name = static_cast<const AstRawString*>(p->key);
    Variable* var = LookupLocal(name);
    if (var != nullptr && var->mode() <= mode_limit) return name;
  }
  return nullptr;
}
References LookupLocal(), v8::internal::Variable::mode(), v8::internal::name, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Next(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Start(), and variables_.
Referenced by v8::internal::ParserBase< Impl >::ParseFunctionBody(), v8::internal::ParserBase< Impl >::ParseTryStatement(), and v8::internal::PreParser::PreParseFunction().
ForceContextAllocationForParameters()
void v8::internal::Scope::ForceContextAllocationForParameters () [inline]
Definition at line 351 of file scopes.h.
                                             {
    DCHECK(!already_resolved_);
    force_context_allocation_for_parameters_ = true;
  }
References v8::internal::DCHECK().
ForceContextForLanguageMode()
bool v8::internal::Scope::ForceContextForLanguageMode () const [inline]
Definition at line 423 of file scopes.h.
                                           {
    // For function scopes we need not force a context since the language mode
    // can be obtained from the closure. Script scopes always have a context.
    if (scope_type_ == FUNCTION_SCOPE || is_script_scope()) {
      return false;
    }
    DCHECK_NOT_NULL(outer_scope_);
    return (language_mode() > outer_scope_->language_mode());
  }
References DCHECK_NOT_NULL, and v8::internal::FUNCTION_SCOPE.
Referenced by AllocateVariablesRecursively(), and v8::internal::ScopeInfo::Create().
ForceDynamicLookup()
void v8::internal::Scope::ForceDynamicLookup (VariableProxy * proxy)
Definition at line 2085 of file scopes.cc.
                                                   {
  // At the moment this is only used for looking up private names dynamically
  // in debug-evaluate from top-level scope.
  DCHECK(proxy->IsPrivateName());
  DCHECK(is_script_scope() || is_module_scope() || is_eval_scope());
  Variable* dynamic = NonLocal(proxy->raw_name(), VariableMode::kDynamic);
  proxy->BindTo(dynamic);
}
References v8::internal::VariableProxy::BindTo(), v8::internal::DCHECK(), is_eval_scope(), is_module_scope(), is_script_scope(), v8::internal::VariableProxy::IsPrivateName(), v8::internal::kDynamic, NonLocal(), and v8::internal::VariableProxy::raw_name().
Referenced by v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName().
ForEach()
template<typename FunctionType >
void v8::internal::Scope::ForEach (FunctionType callback) [inline]
Definition at line 1592 of file scopes.cc.
                                         {
  Scope* scope = this;
  while (true) {
    Iteration iteration = callback(scope);
    // Try to descend into inner scopes first.
    if ((iteration == Iteration::kDescend) && scope->inner_scope_ != nullptr) {
      scope = scope->inner_scope_;
    } else {
      // Find the next outer scope with a sibling.
      while (scope->sibling_ == nullptr) {
        if (scope == this) return;
        scope = scope->outer_scope_;
      }
      if (scope == this) return;
      scope = scope->sibling_;
    }
  }
}
References inner_scope_, outer_scope_, and sibling_.
Referenced by AllocateVariablesRecursively(), AnalyzePartially(), and SavePreparseData().
GetClosureScope() [1/2]
DeclarationScope * v8::internal::Scope::GetClosureScope ()
Definition at line 1505 of file scopes.cc.
                                         {
  Scope* scope = this;
  while (!scope->is_declaration_scope() || scope->is_block_scope()) {
    scope = scope->outer_scope();
  }
  return scope->AsDeclarationScope();
}
References AsDeclarationScope(), is_block_scope(), is_declaration_scope(), and outer_scope().
Referenced by v8::internal::DeclarationScope::AddLocal(), v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), v8::internal::Parser::DoParseFunction(), v8::internal::ParserBase< Impl >::GetClosureScope(), HasSimpleParameters(), NeedsScopeInfo(), NewTemporary(), v8::internal::Processor::Processor(), v8::internal::DeclarationScope::RecordNeedsPrivateNameContextChainRecalc(), v8::internal::Scope::Snapshot::Reparent(), v8::internal::Rewriter::Rewrite(), v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck(), and v8::internal::ParserBase< Impl >::UseThis().
GetClosureScope() [2/2]
const DeclarationScope * v8::internal::Scope::GetClosureScope () const
Definition at line 1497 of file scopes.cc.
                                                     {
  const Scope* scope = this;
  while (!scope->is_declaration_scope() || scope->is_block_scope()) {
    scope = scope->outer_scope();
  }
  return scope->AsDeclarationScope();
}
References AsDeclarationScope(), is_block_scope(), is_declaration_scope(), and outer_scope().
GetConstructorScope()
DeclarationScope * v8::internal::Scope::GetConstructorScope ()
Definition at line 1536 of file scopes.cc.
                                             {
  Scope* scope = this;
  while (scope != nullptr && !scope->IsConstructorScope()) {
    scope = scope->outer_scope();
  }
  if (scope == nullptr) {
    return nullptr;
  }
  DCHECK(scope->IsConstructorScope());
  return scope->AsDeclarationScope();
}
References AsDeclarationScope(), v8::internal::DCHECK(), IsConstructorScope(), and outer_scope().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall().
GetDeclarationScope()
DeclarationScope * v8::internal::Scope::GetDeclarationScope ()
Definition at line 1481 of file scopes.cc.
                                             {
  Scope* scope = this;
  while (!scope->is_declaration_scope()) {
    scope = scope->outer_scope();
  }
  return scope->AsDeclarationScope();
}
References AsDeclarationScope(), is_declaration_scope(), and outer_scope().
Referenced by AllocateStackSlot(), DeclareLocal(), DeclareVariable(), DeclareVariableName(), v8::internal::PreParser::DeclareVariableName(), v8::internal::ParserBase< Impl >::GetDeclarationScope(), v8::internal::Parser::ParseClassForMemberInitialization(), v8::internal::ParserBase< Impl >::ParseVariableDeclarations(), v8::internal::DeclarationScope::RecordDeclarationScopeEvalCall(), RecordEvalCall(), and v8::internal::DeclarationScope::SetDefaults().
GetHomeObjectScope()
Scope * v8::internal::Scope::GetHomeObjectScope ()
Definition at line 1548 of file scopes.cc.
                                 {
  Scope* scope = GetReceiverScope();
  DCHECK(scope->is_function_scope());
  FunctionKind kind = scope->AsDeclarationScope()->function_kind();
  // "super" in arrow functions binds outside the arrow function. Arrow
  // functions are also never receiver scopes since they close over the
  // receiver.
  DCHECK(!IsArrowFunction(kind));
  // If we find a function which doesn't bind "super" (is not a method etc.), we
  // know "super" here doesn't bind anywhere and we can return nullptr.
  if (!BindsSuper(kind)) return nullptr;
  // Functions that bind "super" can only syntactically occur nested inside home
  // object scopes (i.e. class scopes and object literal scopes), so directly
  // return the outer scope.
  Scope* outer_scope = scope->outer_scope();
  CHECK(outer_scope->is_home_object_scope());
  return outer_scope;
}
References AsDeclarationScope(), v8::internal::BindsSuper(), CHECK, v8::internal::DCHECK(), v8::internal::DeclarationScope::function_kind(), GetReceiverScope(), is_function_scope(), is_home_object_scope(), v8::internal::IsArrowFunction(), and outer_scope().
Referenced by ResolveVariable().
GetNonEvalDeclarationScope()
DeclarationScope * v8::internal::Scope::GetNonEvalDeclarationScope ()
Definition at line 1489 of file scopes.cc.
                                                    {
  Scope* scope = this;
  while (!scope->is_declaration_scope() || scope->is_eval_scope()) {
    scope = scope->outer_scope();
  }
  return scope->AsDeclarationScope();
}
References AsDeclarationScope(), is_declaration_scope(), is_eval_scope(), and outer_scope().
Referenced by v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), and v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
GetOuterScopeWithContext()
Scope * v8::internal::Scope::GetOuterScopeWithContext ()
Definition at line 1575 of file scopes.cc.
                                       {
  Scope* scope = outer_scope_;
  while (scope && !scope->NeedsContext()) {
    scope = scope->outer_scope();
  }
  return scope;
}
References NeedsContext(), outer_scope(), and outer_scope_.
Referenced by v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::SharedFunctionInfo::UpdateFromFunctionLiteralForLiveEdit().
GetReceiverScope()
DeclarationScope * v8::internal::Scope::GetReceiverScope ()
Definition at line 1526 of file scopes.cc.
                                          {
  Scope* scope = this;
  while (!scope->is_declaration_scope() ||
         (!scope->is_script_scope() &&
          !scope->AsDeclarationScope()->has_this_declaration())) {
    scope = scope->outer_scope();
  }
  return scope->AsDeclarationScope();
}
References AsDeclarationScope(), v8::internal::DeclarationScope::has_this_declaration(), is_declaration_scope(), is_script_scope(), and outer_scope().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::interpreter::BytecodeGenerator::BuildThisVariableLoad(), v8::internal::Parser::DeserializeScopeChain(), GetHomeObjectScope(), v8::internal::ParserBase< Impl >::GetReceiverScope(), RecordEvalCall(), ShouldBanArguments(), and v8::internal::ParserBase< Impl >::UseThis().
GetScriptScope()
DeclarationScope * v8::internal::Scope::GetScriptScope ()
Definition at line 1567 of file scopes.cc.
                                        {
  Scope* scope = this;
  while (!scope->is_script_scope()) {
    scope = scope->outer_scope();
  }
  return scope->AsDeclarationScope();
}
References AsDeclarationScope(), is_script_scope(), and outer_scope().
Referenced by RewriteReplGlobalVariables().
has_await_using_declaration()
bool v8::internal::Scope::has_await_using_declaration () const [inline]
Definition at line 395 of file scopes.h.
                                           {
    return has_await_using_declaration_;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatementsWithoutImplicitFinalReturn(), and v8::internal::ParserBase< Impl >::ParseVariableDeclarations().
has_context_cells()
bool v8::internal::Scope::has_context_cells () const [inline]
Definition at line 399 of file scopes.h.
{ return has_context_cells_; }
Referenced by v8::internal::ScopeInfo::Create(), and v8::internal::interpreter::BytecodeArrayBuilder::CreateFunctionContext().
has_forced_context_allocation_for_parameters()
bool v8::internal::Scope::has_forced_context_allocation_for_parameters () const [inline]
Definition at line 355 of file scopes.h.
                                                            {
    return force_context_allocation_for_parameters_;
  }
Referenced by v8::internal::DeclarationScope::AllocateParameter().
has_using_declaration()
bool v8::internal::Scope::has_using_declaration () const [inline]
Definition at line 394 of file scopes.h.
{ return has_using_declaration_; }
HasContextExtensionSlot()
bool v8::internal::Scope::HasContextExtensionSlot () const [inline]
Definition at line 509 of file scopes.h.
                                       {
    switch (scope_type_) {
      case MODULE_SCOPE:
      case WITH_SCOPE: // DebugEvaluateContext as well
        return true;
      default:
        DCHECK_IMPLIES(sloppy_eval_can_extend_vars_,
                       scope_type_ == FUNCTION_SCOPE ||
                           scope_type_ == EVAL_SCOPE ||
                           scope_type_ == BLOCK_SCOPE);
        DCHECK_IMPLIES(sloppy_eval_can_extend_vars_, is_declaration_scope());
        return sloppy_eval_can_extend_vars_;
    }
    UNREACHABLE();
  }
References v8::internal::BLOCK_SCOPE, DCHECK_IMPLIES, v8::internal::EVAL_SCOPE, v8::internal::FUNCTION_SCOPE, v8::internal::MODULE_SCOPE, v8::internal::UNREACHABLE(), and v8::internal::WITH_SCOPE.
Referenced by v8::internal::ScopeInfo::Create().
HasReceiverToDeserialize()
bool v8::internal::Scope::HasReceiverToDeserialize () const
Definition at line 1406 of file scopes.cc.
                                           {
  return !scope_info_.is_null() && scope_info_->HasAllocatedReceiver();
}
References scope_info_.
Referenced by v8::internal::Parser::DeserializeScopeChain().
HasSimpleParameters()
bool v8::internal::Scope::HasSimpleParameters ()
Definition at line 400 of file scopes.cc.
                                {
  DeclarationScope* scope = GetClosureScope();
  return !scope->is_function_scope() || scope->has_simple_parameters();
}
References GetClosureScope(), v8::internal::DeclarationScope::has_simple_parameters(), and is_function_scope().
Referenced by v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
HasThisReference()
bool v8::internal::Scope::HasThisReference () const
Definition at line 1410 of file scopes.cc.
                                   {
  if (is_declaration_scope() && AsDeclarationScope()->has_this_reference()) {
    return true;
  }
  for (Scope* scope = inner_scope_; scope != nullptr; scope = scope->sibling_) {
    if (!scope->is_declaration_scope() ||
        !scope->AsDeclarationScope()->has_this_declaration()) {
      if (scope->HasThisReference()) return true;
    }
  }
  return false;
}
References AsDeclarationScope(), inner_scope_, is_declaration_scope(), and sibling_.
Referenced by v8::internal::ScopeIterator::ClosureScopeHasThisReference(), and v8::internal::ScopeIterator::VisitLocalScope().
inner_scope()
Scope* v8::internal::Scope::inner_scope () const [inline]
Definition at line 488 of file scopes.h.
{ return inner_scope_; }
Referenced by v8::internal::Scope::Snapshot::Reparent(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForInnerScopes(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveClosureScope(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveStartScope(), v8::internal::PreparseDataBuilder::SaveDataForInnerScopes(), and v8::internal::PreparseDataBuilder::ScopeNeedsData().
inner_scope_calls_eval()
bool v8::internal::Scope::inner_scope_calls_eval () const [inline]
Definition at line 389 of file scopes.h.
{ return inner_scope_calls_eval_; }
Referenced by v8::internal::PreparseDataBuilder::SaveDataForScope().
is_block_scope()
bool v8::internal::Scope::is_block_scope () const [inline]
Definition at line 370 of file scopes.h.
                              {
    return scope_type_ == BLOCK_SCOPE || scope_type_ == CLASS_SCOPE;
  }
References v8::internal::BLOCK_SCOPE, and v8::internal::CLASS_SCOPE.
Referenced by AllocateStackSlot(), AllocateVariablesRecursively(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalBlockContext(), v8::internal::Parser::DeclareVariable(), DeclareVariable(), FinalizeBlockScope(), GetClosureScope(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), and v8::internal::Parser::RewriteSwitchStatement().
is_block_scope_for_object_literal()
bool v8::internal::Scope::is_block_scope_for_object_literal () const [inline]
Definition at line 380 of file scopes.h.
                                                 {
    DCHECK_IMPLIES(is_block_scope_for_object_literal_, is_block_scope());
    return is_block_scope_for_object_literal_;
  }
References DCHECK_IMPLIES.
is_catch_scope()
bool v8::internal::Scope::is_catch_scope () const [inline]
Definition at line 369 of file scopes.h.
{ return scope_type_ == CATCH_SCOPE; }
References v8::internal::CATCH_SCOPE.
Referenced by AllocateNonParameterLocal(), v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), DeclareCatchVariableName(), DeclareVariable(), MustAllocate(), and MustAllocateInContext().
is_class_scope()
bool v8::internal::Scope::is_class_scope () const [inline]
Definition at line 375 of file scopes.h.
{ return scope_type_ == CLASS_SCOPE; }
References v8::internal::CLASS_SCOPE.
Referenced by AsClassScope(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::ContainsPosition(), v8::internal::ScopeInfo::Create(), FinalizeBlockScope(), v8::internal::PrivateNameScopeIterator::Next(), v8::internal::PrivateNameScopeIterator::PrivateNameScopeIterator(), v8::internal::PreparseDataBuilder::SaveDataForScope(), and Scope().
is_debug_evaluate_scope()
bool v8::internal::Scope::is_debug_evaluate_scope () const
Definition at line 432 of file scopes.cc.
                                          {
  return is_dynamic_scope_ && scope_info_->IsDebugEvaluateScope();
}
References is_dynamic_scope_, and scope_info_.
Referenced by v8::internal::DeclarationScope::DeserializeReceiver(), Lookup(), and v8::internal::DeclarationScope::RecordDeclarationScopeEvalCall().
is_declaration_scope()
bool v8::internal::Scope::is_declaration_scope () const [inline]
Definition at line 374 of file scopes.h.
{ return is_declaration_scope_; }
Referenced by AllocateNonParameterLocalsAndDeclaredGlobals(), AllocateVariablesRecursively(), AsDeclarationScope(), v8::internal::ScopeInfo::Create(), v8::internal::Parser::DeclareVariable(), DeclareVariable(), DeclareVariableName(), FinalizeBlockScope(), GetClosureScope(), GetDeclarationScope(), GetNonEvalDeclarationScope(), GetReceiverScope(), HasThisReference(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::InitializeWithClosureScope(), v8::internal::Parser::InsertShadowingVarBindingInitializers(), IsConstructorScope(), Lookup(), LookupSloppyEval(), v8::internal::ParserBase< Impl >::ParseHoistableDeclaration(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::PreparseDataBuilder::SaveDataForScope(), UniqueIdInScript(), v8::internal::ScopeIterator::VisitLocals(), and v8::internal::anonymous_namespace{scopes.cc}::WasLazilyParsed().
is_eval_scope()
bool v8::internal::Scope::is_eval_scope () const [inline]
Definition at line 363 of file scopes.h.
{ return scope_type_ == EVAL_SCOPE; }
References v8::internal::EVAL_SCOPE.
Referenced by v8::internal::DeclarationScope::Analyze(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), v8::internal::ScopeInfo::Create(), v8::internal::DeclarationScope::DeclarationScope(), DeclareVariable(), DeclareVariableName(), ForceDynamicLookup(), GetNonEvalDeclarationScope(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::Parser::InsertSloppyBlockFunctionVarBindings(), MustAllocateInContext(), v8::internal::Parser::ParseWrapped(), v8::internal::DeclarationScope::RecordDeclarationScopeEvalCall(), and v8::internal::Rewriter::Rewrite().
is_function_scope()
bool v8::internal::Scope::is_function_scope () const [inline]
Definition at line 364 of file scopes.h.
{ return scope_type_ == FUNCTION_SCOPE; }
References v8::internal::FUNCTION_SCOPE.
Referenced by v8::internal::DeclarationScope::AllocateParameterLocals(), AllocateVariablesRecursively(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectAndStore(), ContextLocalCount(), v8::internal::ScopeInfo::Create(), v8::internal::DeclarationScope::DeclareArguments(), v8::internal::DeclarationScope::DeclareDefaultFunctionVariables(), v8::internal::DeclarationScope::DeclareFunctionVar(), v8::internal::DeclarationScope::DeclareGeneratorObjectVar(), v8::internal::DeclarationScope::DeclareParameter(), GetHomeObjectScope(), HasSimpleParameters(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::Parser::InsertShadowingVarBindingInitializers(), IsSkippableFunctionScope(), Lookup(), v8::internal::ScopeIterator::NeedsContext(), NeedsScopeInfo(), v8::internal::DeclarationScope::RecordParameter(), v8::internal::DeclarationScope::ResetAfterPreparsing(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::PreparseDataBuilder::SaveDataForScope(), v8::internal::PreparseDataBuilder::ScopeNeedsData(), SetDefaults(), v8::internal::DeclarationScope::SetDefaults(), and v8::internal::ScopeIterator::VisitLocals().
is_hidden()
bool v8::internal::Scope::is_hidden () const [inline]
Definition at line 348 of file scopes.h.
{ return is_hidden_; }
Referenced by v8::internal::ScopeIterator::AdvanceScope(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::AdvanceToNextNonHiddenScope(), v8::internal::ScopeInfo::Create(), and v8::internal::PreparseDataBuilder::ScopeNeedsData().
is_home_object_scope()
bool v8::internal::Scope::is_home_object_scope () const [inline]
Definition at line 376 of file scopes.h.
                                    {
    return is_class_scope() ||
           (is_block_scope() && is_block_scope_for_object_literal_);
  }
Referenced by GetHomeObjectScope().
is_module_scope()
bool v8::internal::Scope::is_module_scope () const [inline]
Definition at line 365 of file scopes.h.
{ return scope_type_ == MODULE_SCOPE; }
References v8::internal::MODULE_SCOPE.
Referenced by v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations(), v8::internal::DeclarationScope::AllocateVariables(), AllocateVariablesRecursively(), AsModuleScope(), v8::internal::ScopeInfo::Create(), v8::internal::DeclarationScope::DeclareGeneratorObjectVar(), DeclareLocal(), v8::internal::DeclarationScope::DeclareParameter(), ForceDynamicLookup(), LookupInScopeInfo(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::NeedsContextInitialization(), v8::internal::ParserBase< Impl >::ParseHoistableDeclaration(), v8::internal::DeclarationScope::RecordParameter(), and v8::internal::DeclarationScope::SetDefaults().
is_nonlinear()
bool v8::internal::Scope::is_nonlinear () const [inline]
Definition at line 418 of file scopes.h.
{ return scope_nonlinear_; }
Referenced by v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck().
is_reparsed()
bool v8::internal::Scope::is_reparsed () const [inline]
Definition at line 117 of file scopes.h.
{ return !scope_info_.is_null(); }
Referenced by ContextLocalCount(), v8::internal::Parser::CreateSyntheticContextVariableProxy(), v8::internal::Parser::DeclarePrivateClassMember(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::ParserBase< Impl >::UseThis().
is_repl_mode_scope()
bool v8::internal::Scope::is_repl_mode_scope () const [inline]
Definition at line 612 of file scopes.h.
{ return scope_type_ == REPL_MODE_SCOPE; }
References v8::internal::REPL_MODE_SCOPE.
Referenced by v8::internal::DeclarationScope::DeclareGeneratorObjectVar(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::Variable::IsReplGlobal(), v8::internal::Rewriter::Rewrite(), v8::internal::Variable::RewriteLocationForRepl(), and RewriteReplGlobalVariables().
is_script_scope()
bool v8::internal::Scope::is_script_scope () const [inline]
Definition at line 366 of file scopes.h.
                               {
    return scope_type_ == SCRIPT_SCOPE || scope_type_ == REPL_MODE_SCOPE;
  }
References v8::internal::REPL_MODE_SCOPE, and v8::internal::SCRIPT_SCOPE.
Referenced by v8::internal::DeclarationScope::Analyze(), AnalyzePartially(), v8::internal::DeclarationScope::AnalyzePartially(), v8::internal::ScopeInfo::Create(), v8::internal::DeclarationScope::DeclarationScope(), v8::internal::DeclarationScope::DeclareDynamicGlobal(), DeclareLocal(), v8::internal::DeclarationScope::DeserializeReceiver(), ForceDynamicLookup(), v8::internal::DeclarationScope::ForceEagerCompilation(), GetReceiverScope(), GetScriptScope(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), v8::internal::Variable::IsGlobalObjectProperty(), Lookup(), MustAllocate(), MustAllocateInContext(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::NeedsContextInitialization(), v8::internal::ScopeIterator::Next(), v8::internal::DeclarationScope::RecordDeclarationScopeEvalCall(), v8::internal::ClassScope::ResolvePrivateNames(), v8::internal::Rewriter::Rewrite(), Scope(), SetDefaults(), and UniqueIdInScript().
is_with_scope()
bool v8::internal::Scope::is_with_scope () const [inline]
Definition at line 373 of file scopes.h.
{ return scope_type_ == WITH_SCOPE; }
References v8::internal::WITH_SCOPE.
Referenced by AllocateVariablesRecursively(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::ContainsPosition(), v8::internal::Parser::DeclareVariable(), DeclareVariable(), DeclareVariableName(), Lookup(), and LookupWith().
is_wrapped_function()
bool v8::internal::Scope::is_wrapped_function () const [inline]
Definition at line 401 of file scopes.h.
                                   {
    DCHECK_IMPLIES(is_wrapped_function_, is_function_scope());
    return is_wrapped_function_;
  }
References DCHECK_IMPLIES.
Referenced by v8::internal::ScopeInfo::Create(), and UniqueIdInScript().
IsConstructorScope()
bool v8::internal::Scope::IsConstructorScope () const
Definition at line 1611 of file scopes.cc.
                                     {
  return is_declaration_scope() &&
         IsClassConstructor(AsDeclarationScope()->function_kind());
}
References AsDeclarationScope(), is_declaration_scope(), and v8::internal::IsClassConstructor().
Referenced by v8::internal::ScopeInfo::Create(), and GetConstructorScope().
IsOuterScopeOf()
bool v8::internal::Scope::IsOuterScopeOf (Scope * other) const
Definition at line 1616 of file scopes.cc.
                                             {
  Scope* scope = other;
  while (scope) {
    if (scope == this) return true;
    scope = scope->outer_scope();
  }
  return false;
}
References outer_scope().
Referenced by v8::internal::DeclarationScope::DeclareFunctionVar(), and LookupInScopeInfo().
IsSkippableFunctionScope()
bool v8::internal::Scope::IsSkippableFunctionScope ()
Definition at line 1707 of file scopes.cc.
                                     {
  // Lazy non-arrow function scopes are skippable. Lazy functions are exactly
  // those Scopes which have their own PreparseDataBuilder object. This
  // logic ensures that the scope allocation data is consistent with the
  // skippable function data (both agree on where the lazy function boundaries
  // are).
  if (!is_function_scope()) return false;
  DeclarationScope* declaration_scope = AsDeclarationScope();
  return !declaration_scope->is_arrow_scope() &&
         declaration_scope->preparse_data_builder() != nullptr;
}
References AsDeclarationScope(), v8::internal::DeclarationScope::is_arrow_scope(), is_function_scope(), and v8::internal::DeclarationScope::preparse_data_builder().
Referenced by SavePreparseData().
language_mode()
LanguageMode v8::internal::Scope::language_mode () const [inline]
Definition at line 481 of file scopes.h.
                                     {
    return is_strict_ ? LanguageMode::kStrict : LanguageMode::kSloppy;
  }
References v8::internal::kSloppy, and v8::internal::kStrict.
Referenced by v8::internal::DeclarationScope::Analyze(), v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), v8::internal::ScopeInfo::Create(), v8::internal::DeclarationScope::DeclareFunctionVar(), DeclareVariable(), v8::internal::Parser::DoParseFunction(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::ParserBase< Impl >::language_mode(), v8::internal::FunctionLiteral::language_mode(), v8::internal::interpreter::BytecodeGenerator::language_mode(), v8::internal::ParserBase< Impl >::ParseFunctionBody(), v8::internal::Parser::ParseFunctionLiteral(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::PreParser::PreParseFunction(), v8::internal::ParserBase< Impl >::RaiseLanguageMode(), RecordEvalCall(), v8::internal::Parser::RewriteClassLiteral(), v8::internal::PreparseDataBuilder::SaveDataForSkippableFunction(), and Scope().
locals()
base::ThreadedList<Variable>* v8::internal::Scope::locals () [inline]
Definition at line 233 of file scopes.h.
{ return &locals_; }
Referenced by v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectCurrentLocalsIntoBlocklists(), v8::internal::ScopeIterator::CollectLocalsFromCurrentScope(), v8::internal::ScopeInfo::Create(), v8::internal::anonymous_namespace{liveedit.cc}::HasChangedScope(), v8::internal::Scope::Snapshot::Reparent(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::PreparseDataBuilder::SaveDataForScope(), v8::internal::PreparseDataBuilder::ScopeNeedsData(), v8::internal::ScopeIterator::SetLocalVariableValue(), and v8::internal::ScopeIterator::VisitLocals().
Lookup()
template<Scope::ScopeLookupMode mode>
Variable * v8::internal::Scope::Lookup (VariableProxy * proxy, Scope * scope, Scope * outer_scope_end, Scope * cache_scope = nullptr, bool force_context_allocation = false) [static], [private]
Definition at line 2096 of file scopes.cc.
                                                       {
  // If we have already passed the cache scope in earlier recursions, we should
  // first quickly check if the current scope uses the cache scope before
  // continuing.
  if (mode == kDeserializedScope) {
    Variable* var = cache_scope->variables_.Lookup(proxy->raw_name());
    if (var != nullptr) return var;
  }
  while (true) {
    // Try to find the variable in this scope.
    Variable* var;
    if (mode == kParsedScope) {
      var = scope->LookupLocal(proxy->raw_name());
    } else {
      DCHECK_EQ(mode, kDeserializedScope);
      var = scope->LookupInScopeInfo(proxy->raw_name(), cache_scope);
    }
    // We found a variable and we are done. (Even if there is an 'eval' in this
    // scope which introduces the same variable again, the resulting variable
    // remains the same.)
    if (var != nullptr) {
      if (mode == kParsedScope && force_context_allocation &&
          !var->is_dynamic()) {
        var->ForceContextAllocation();
      }
      return var;
    }
    if (scope->outer_scope_ == outer_scope_end) break;
    if (V8_UNLIKELY(scope->is_dynamic_scope_)) {
      DCHECK(!scope->is_script_scope());
      if (scope->is_declaration_scope() &&
          scope->AsDeclarationScope()->sloppy_eval_can_extend_vars()) {
        return LookupSloppyEval(proxy, scope, outer_scope_end, cache_scope,
                                force_context_allocation);
      }
      if (scope->is_with_scope()) {
        return LookupWith(proxy, scope, outer_scope_end, cache_scope,
                          force_context_allocation);
      }
      CHECK_EQ(mode, kDeserializedScope);
      CHECK(scope->is_debug_evaluate_scope());
      return cache_scope->NonLocal(proxy->raw_name(), VariableMode::kDynamic);
    }
    force_context_allocation |= scope->is_function_scope();
    scope = scope->outer_scope_;
    // TODO(verwaest): Separate through AnalyzePartially.
    if (mode == kParsedScope && !scope->scope_info_.is_null()) {
      DCHECK_NULL(cache_scope);
      return Lookup<kDeserializedScope>(proxy, scope, outer_scope_end, scope);
    }
  }
  // We may just be trying to find all free variables. In that case, don't
  // declare them in the outer scope.
  // TODO(marja): Separate Lookup for preparsed scopes better.
  if (mode == kParsedScope && !scope->is_script_scope()) {
    return nullptr;
  }
  // No binding has been found. Declare a variable on the global object.
  return scope->AsDeclarationScope()->DeclareDynamicGlobal(
      proxy->raw_name(), NORMAL_VARIABLE,
      mode == kDeserializedScope ? cache_scope : scope);
}
References AsDeclarationScope(), CHECK, CHECK_EQ, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::DeclarationScope::DeclareDynamicGlobal(), v8::internal::Variable::ForceContextAllocation(), is_debug_evaluate_scope(), is_declaration_scope(), v8::internal::Variable::is_dynamic(), is_dynamic_scope_, is_function_scope(), is_script_scope(), is_with_scope(), kDeserializedScope, v8::internal::kDynamic, kParsedScope, v8::internal::VariableMap::Lookup(), LookupInScopeInfo(), LookupLocal(), LookupSloppyEval(), LookupWith(), mode(), NonLocal(), v8::internal::NORMAL_VARIABLE, outer_scope_, v8::internal::VariableProxy::raw_name(), scope_info_, v8::internal::DeclarationScope::sloppy_eval_can_extend_vars(), V8_UNLIKELY, and variables_.
LookupForTesting()
Variable* v8::internal::Scope::LookupForTesting (const AstRawString * name) [inline]
Definition at line 646 of file scopes.h.
                                                       {
    for (Scope* scope = this; scope != nullptr; scope = scope->outer_scope()) {
      Variable* var = scope->LookupInScopeOrScopeInfo(name, scope);
      if (var != nullptr) return var;
    }
    return nullptr;
  }
References v8::internal::name, and outer_scope().
LookupInScopeInfo()
Variable * v8::internal::Scope::LookupInScopeInfo (const AstRawString * name, Scope * cache)
Definition at line 983 of file scopes.cc.
                                                                         {
  DCHECK(!scope_info_.is_null());
  DCHECK(this->IsOuterScopeOf(cache));
  DCHECK_NULL(cache->variables_.Lookup(name));
  DisallowGarbageCollection no_gc;
  Tagged<String> name_handle = *name->string();
  Tagged<ScopeInfo> scope_info = *scope_info_;
  // The Scope is backed up by ScopeInfo. This means it cannot operate in a
  // heap-independent mode, and all strings must be internalized immediately. So
  // it's ok to get the Handle<String> here.
  bool found = false;
  VariableLocation location;
  int index;
  VariableLookupResult lookup_result;
  {
    location = VariableLocation::CONTEXT;
    index = scope_info->ContextSlotIndex(name_handle, &lookup_result);
    found = index >= 0;
  }
  if (!found && is_module_scope()) {
    location = VariableLocation::MODULE;
    index = scope_info->ModuleIndex(name_handle, &lookup_result.mode,
                                    &lookup_result.init_flag,
                                    &lookup_result.maybe_assigned_flag);
    found = index != 0;
  }
  if (!found) {
    index = scope_info->FunctionContextSlotIndex(name_handle);
    if (index < 0) return nullptr; // Nowhere found.
    Variable* var = AsDeclarationScope()->DeclareFunctionVar(name, cache);
    DCHECK_EQ(VariableMode::kConst, var->mode());
    var->AllocateTo(VariableLocation::CONTEXT, index);
    return cache->variables_.Lookup(name);
  }
  if (!is_module_scope()) {
    DCHECK_NE(index, scope_info->ReceiverContextSlotIndex());
  }
  bool was_added;
  Variable* var = cache->variables_.Declare(
      zone(), this, name, lookup_result.mode, NORMAL_VARIABLE,
      lookup_result.init_flag, lookup_result.maybe_assigned_flag,
      IsStaticFlag::kNotStatic, &was_added);
  DCHECK(was_added);
  var->AllocateTo(location, index);
  return var;
}
References v8::internal::Variable::AllocateTo(), AsDeclarationScope(), v8::internal::CONTEXT, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, DCHECK_NULL, v8::internal::VariableMap::Declare(), v8::internal::DeclarationScope::DeclareFunctionVar(), v8::internal::index, v8::internal::VariableLookupResult::init_flag, is_module_scope(), IsOuterScopeOf(), v8::internal::kConst, v8::internal::kNotStatic, v8::internal::VariableMap::Lookup(), v8::internal::VariableLookupResult::maybe_assigned_flag, v8::internal::Variable::mode(), v8::internal::VariableLookupResult::mode, v8::internal::MODULE, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NORMAL_VARIABLE, scope_info(), scope_info_, variables_, and zone().
Referenced by v8::internal::ClassScope::ClassScope(), and Lookup().
LookupInScopeOrScopeInfo()
Variable* v8::internal::Scope::LookupInScopeOrScopeInfo (const AstRawString * name, Scope * cache) [inline]
Definition at line 640 of file scopes.h.
                                                                             {
    Variable* var = variables_.Lookup(name);
    if (var != nullptr || scope_info_.is_null()) return var;
    return LookupInScopeInfo(name, cache);
  }
References v8::internal::name.
Referenced by v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), and v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
LookupLocal()
Variable* v8::internal::Scope::LookupLocal (const AstRawString * name) [inline]
Definition at line 202 of file scopes.h.
                                                  {
    DCHECK(scope_info_.is_null());
    return variables_.Lookup(name);
  }
References v8::internal::DCHECK(), and v8::internal::name.
Referenced by v8::internal::ModuleScope::AllocateModuleVariables(), v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), v8::internal::Parser::DeclareFunctionNameVar(), v8::internal::PreParser::DeclareFunctionNameVar(), v8::internal::DeclarationScope::DeclareParameter(), DeclareVariable(), v8::internal::PreParser::DeclareVariableName(), FindVariableDeclaredIn(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::Parser::InsertShadowingVarBindingInitializers(), Lookup(), v8::internal::ParserBase< Impl >::ParseTryStatement(), ResolvePreparsedVariable(), and v8::internal::SourceTextModuleDescriptor::Validate().
LookupSloppyEval()
Variable * v8::internal::Scope::LookupSloppyEval (VariableProxy * proxy, Scope * scope, Scope * outer_scope_end, Scope * cache_scope, bool force_context_allocation) [static], [private]
Definition at line 2209 of file scopes.cc.
                                                                 {
  DCHECK(scope->is_declaration_scope() &&
         scope->AsDeclarationScope()->sloppy_eval_can_extend_vars());
  // If we're compiling eval, it's possible that the outer scope is the first
  // ScopeInfo-backed scope. We use the next declaration scope as the cache for
  // this case, to avoid complexity around sloppy block function hoisting and
  // conflict detection through catch scopes in the eval.
  Scope* entry_cache =
      cache_scope == nullptr ? scope->outer_scope() : cache_scope;
  Variable* var =
      scope->outer_scope_->scope_info_.is_null()
          ? Lookup<kParsedScope>(proxy, scope->outer_scope_, outer_scope_end,
                                 nullptr, force_context_allocation)
          : Lookup<kDeserializedScope>(proxy, scope->outer_scope_,
                                       outer_scope_end, entry_cache);
  if (var == nullptr) return var;
  // A variable binding may have been found in an outer scope, but the current
  // scope makes a sloppy 'eval' call, so the found variable may not be the
  // correct one (the 'eval' may introduce a binding with the same name). In
  // that case, change the lookup result to reflect this situation. Only
  // scopes that can host var bindings (declaration scopes) need be considered
  // here (this excludes block and catch scopes), and variable lookups at
  // script scope are always dynamic.
  if (var->IsGlobalObjectProperty()) {
    Scope* target = cache_scope == nullptr ? scope : cache_scope;
    var = target->NonLocal(proxy->raw_name(), VariableMode::kDynamicGlobal);
  }
  if (var->is_dynamic()) return var;
  Variable* invalidated = var;
  if (cache_scope != nullptr) cache_scope->variables_.Remove(invalidated);
  Scope* target = cache_scope == nullptr ? scope : cache_scope;
  var = target->NonLocal(proxy->raw_name(), VariableMode::kDynamicLocal);
  var->set_local_if_not_shadowed(invalidated);
  return var;
}
References AsDeclarationScope(), v8::internal::DCHECK(), is_declaration_scope(), v8::internal::Variable::is_dynamic(), v8::internal::Variable::IsGlobalObjectProperty(), v8::internal::kDynamicGlobal, v8::internal::kDynamicLocal, NonLocal(), outer_scope(), outer_scope_, v8::internal::VariableProxy::raw_name(), v8::internal::VariableMap::Remove(), scope_info_, v8::internal::Variable::set_local_if_not_shadowed(), v8::internal::DeclarationScope::sloppy_eval_can_extend_vars(), and variables_.
Referenced by Lookup().
LookupWith()
Variable * v8::internal::Scope::LookupWith (VariableProxy * proxy, Scope * scope, Scope * outer_scope_end, Scope * cache_scope, bool force_context_allocation) [static], [private]
Definition at line 2175 of file scopes.cc.
                                                           {
  DCHECK(scope->is_with_scope());
  Variable* var =
      scope->outer_scope_->scope_info_.is_null()
          ? Lookup<kParsedScope>(proxy, scope->outer_scope_, outer_scope_end,
                                 nullptr, force_context_allocation)
          : Lookup<kDeserializedScope>(proxy, scope->outer_scope_,
                                       outer_scope_end, cache_scope);
  if (var == nullptr) return var;
  // The current scope is a with scope, so the variable binding can not be
  // statically resolved. However, note that it was necessary to do a lookup
  // in the outer scope anyway, because if a binding exists in an outer
  // scope, the associated variable has to be marked as potentially being
  // accessed from inside of an inner with scope (the property may not be in
  // the 'with' object).
  if (!var->is_dynamic() && var->IsUnallocated()) {
    DCHECK(!scope->already_resolved_);
    var->set_is_used();
    var->ForceContextAllocation();
    if (proxy->is_assigned()) var->SetMaybeAssigned();
  }
  if (cache_scope) cache_scope->variables_.Remove(var);
  Scope* target = cache_scope == nullptr ? scope : cache_scope;
  Variable* dynamic =
      target->NonLocal(proxy->raw_name(), VariableMode::kDynamic);
  dynamic->set_local_if_not_shadowed(var);
  return dynamic;
}
References v8::internal::DCHECK(), v8::internal::Variable::ForceContextAllocation(), v8::internal::VariableProxy::is_assigned(), v8::internal::Variable::is_dynamic(), is_with_scope(), v8::internal::Variable::IsUnallocated(), v8::internal::kDynamic, NonLocal(), outer_scope_, v8::internal::VariableProxy::raw_name(), v8::internal::VariableMap::Remove(), scope_info_, v8::internal::Variable::set_is_used(), v8::internal::Variable::set_local_if_not_shadowed(), v8::internal::Variable::SetMaybeAssigned(), and variables_.
Referenced by Lookup().
must_use_preparsed_scope_data()
bool v8::internal::Scope::must_use_preparsed_scope_data () const [inline]
Definition at line 193 of file scopes.h.
                                             {
    return must_use_preparsed_scope_data_;
  }
MustAllocate()
bool v8::internal::Scope::MustAllocate (Variable * var) [private]
Definition at line 2397 of file scopes.cc.
                                      {
  DCHECK(var->location() != VariableLocation::MODULE);
  // Give var a read/write use if there is a chance it might be accessed
  // via an eval() call. This is only possible if the variable has a
  // visible name.
  if (!var->raw_name()->IsEmpty() &&
      (inner_scope_calls_eval_ || is_catch_scope() || is_script_scope())) {
    var->set_is_used();
    if (inner_scope_calls_eval_ && !var->is_this()) var->SetMaybeAssigned();
  }
  CHECK(!var->has_forced_context_allocation() || var->is_used());
  // Global variables do not need to be allocated.
  return !var->IsGlobalObjectProperty() && var->is_used();
}
References CHECK, v8::internal::DCHECK(), v8::internal::Variable::has_forced_context_allocation(), inner_scope_calls_eval_, is_catch_scope(), is_script_scope(), v8::internal::Variable::is_this(), v8::internal::Variable::is_used(), v8::internal::AstRawString::IsEmpty(), v8::internal::Variable::IsGlobalObjectProperty(), v8::internal::Variable::location(), v8::internal::MODULE, v8::internal::Variable::raw_name(), v8::internal::Variable::set_is_used(), and v8::internal::Variable::SetMaybeAssigned().
Referenced by v8::internal::DeclarationScope::AllocateLocals(), AllocateNonParameterLocal(), v8::internal::DeclarationScope::AllocateParameter(), and v8::internal::DeclarationScope::AllocateParameterLocals().
MustAllocateInContext()
bool v8::internal::Scope::MustAllocateInContext (Variable * var) [private]
Definition at line 2413 of file scopes.cc.
                                               {
  // If var is accessed from an inner scope, or if there is a possibility
  // that it might be accessed from the current or an inner scope (through
  // an eval() call or a runtime with lookup), it must be allocated in the
  // context.
  //
  // Temporary variables are always stack-allocated. Catch-bound variables are
  // always context-allocated.
  VariableMode mode = var->mode();
  if (mode == VariableMode::kTemporary) return false;
  if (is_catch_scope()) return true;
  if (is_script_scope() || is_eval_scope()) {
    if (IsLexicalVariableMode(mode)) {
      return true;
    }
  }
  return var->has_forced_context_allocation() || inner_scope_calls_eval_;
}
References v8::internal::Variable::has_forced_context_allocation(), inner_scope_calls_eval_, is_catch_scope(), is_eval_scope(), is_script_scope(), v8::internal::IsLexicalVariableMode(), v8::internal::kTemporary, v8::internal::Variable::mode(), and mode().
Referenced by AllocateNonParameterLocal(), and v8::internal::DeclarationScope::AllocateParameter().
needs_home_object()
bool v8::internal::Scope::needs_home_object () const [inline]
Definition at line 614 of file scopes.h.
                                 {
    DCHECK(is_home_object_scope());
    return needs_home_object_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral(), and v8::internal::ParserBase< Impl >::ParseObjectLiteral().
NeedsContext()
bool v8::internal::Scope::NeedsContext () const [inline]
Definition at line 434 of file scopes.h.
                            {
    // Catch scopes always have heap slots.
    DCHECK_IMPLIES(is_catch_scope(), num_heap_slots() > 0);
    DCHECK_IMPLIES(is_with_scope(), num_heap_slots() > 0);
    DCHECK_IMPLIES(ForceContextForLanguageMode(), num_heap_slots() > 0);
    return num_heap_slots() > 0;
  }
References DCHECK_IMPLIES.
Referenced by AllocateScopeInfosRecursively(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectAndStore(), v8::internal::interpreter::BytecodeGenerator::ContextScope::ContextScope(), GetOuterScopeWithContext(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::InitializeWithClosureScope(), v8::internal::ScopeIterator::NeedsContext(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::NeedsContextInitialization(), NeedsScopeInfo(), and v8::internal::ScopeIterator::TryParseAndRetrieveScopes().
NeedsScopeInfo()
bool v8::internal::Scope::NeedsScopeInfo () const [private]
Definition at line 1513 of file scopes.cc.
                                 {
  DCHECK(!already_resolved_);
  DCHECK(GetClosureScope()->ShouldEagerCompile());
  // The debugger expects all functions to have scope infos.
  // TODO(yangguo): Remove this requirement.
  if (is_function_scope()) return true;
  return NeedsContext();
}
References v8::internal::DCHECK(), GetClosureScope(), is_function_scope(), and NeedsContext().
Referenced by AllocateScopeInfosRecursively().
NewTemporary() [1/2]
Variable * v8::internal::Scope::NewTemporary (const AstRawString * name)
Definition at line 1275 of file scopes.cc.
                                                      {
  return NewTemporary(name, kMaybeAssigned);
}
References v8::internal::kMaybeAssigned, and v8::internal::name.
Referenced by v8::internal::DeclarationScope::DeclareGeneratorObjectVar(), v8::internal::DeclarationScope::DeclareParameter(), and v8::internal::Rewriter::RewriteBody().
NewTemporary() [2/2]
Variable * v8::internal::Scope::NewTemporary (const AstRawString * name, MaybeAssignedFlag maybe_assigned) [private]
Definition at line 1279 of file scopes.cc.
                                                                {
  DeclarationScope* scope = GetClosureScope();
  Variable* var = zone()->New<Variable>(scope, name, VariableMode::kTemporary,
                                        NORMAL_VARIABLE, kCreatedInitialized);
  scope->AddLocal(var);
  if (maybe_assigned == kMaybeAssigned) var->SetMaybeAssigned();
  return var;
}
References v8::internal::DeclarationScope::AddLocal(), GetClosureScope(), v8::internal::kCreatedInitialized, v8::internal::kMaybeAssigned, v8::internal::kTemporary, v8::internal::name, v8::internal::Zone::New(), v8::internal::NORMAL_VARIABLE, v8::internal::Variable::SetMaybeAssigned(), and zone().
NewUnresolved()
VariableProxy* v8::internal::Scope::NewUnresolved (AstNodeFactory * factory, const AstRawString * name, int start_pos, VariableKind kind = NORMAL_VARIABLE) [inline]
Definition at line 236 of file scopes.h.
                                                                    {
    DCHECK_IMPLIES(already_resolved_, reparsing_for_class_initializer_);
    DCHECK_EQ(factory->zone(), zone());
    VariableProxy* proxy = factory->NewVariableProxy(name, kind, start_pos);
    AddUnresolved(proxy);
    return proxy;
  }
References DCHECK_EQ, DCHECK_IMPLIES, v8::internal::name, v8::internal::AstNodeFactory::NewVariableProxy(), and v8::internal::AstNodeFactory::zone().
Referenced by v8::internal::Parser::CreateSyntheticContextVariableProxy(), v8::internal::PreParser::NewSuperCallReference(), and v8::internal::ParserBase< Impl >::NewUnresolved().
NonLocal()
Variable * v8::internal::Scope::NonLocal (const AstRawString * name, VariableMode mode) [private]
Definition at line 2073 of file scopes.cc.
                                                                     {
  // Declare a new non-local.
  DCHECK(IsDynamicVariableMode(mode));
  bool was_added;
  Variable* var = variables_.Declare(zone(), this, name, mode, NORMAL_VARIABLE,
                                     kCreatedInitialized, kNotAssigned,
                                     IsStaticFlag::kNotStatic, &was_added);
  // Allocate it by giving it a dynamic lookup.
  var->AllocateTo(VariableLocation::LOOKUP, -1);
  return var;
}
References v8::internal::Variable::AllocateTo(), v8::internal::DCHECK(), v8::internal::VariableMap::Declare(), v8::internal::IsDynamicVariableMode(), v8::internal::kCreatedInitialized, v8::internal::kNotAssigned, v8::internal::kNotStatic, v8::internal::LOOKUP, mode(), v8::internal::name, v8::internal::NORMAL_VARIABLE, variables_, and zone().
Referenced by v8::internal::DeclarationScope::DeclareFunctionVar(), DeclareVariable(), ForceDynamicLookup(), Lookup(), LookupSloppyEval(), and LookupWith().
num_heap_slots()
int v8::internal::Scope::num_heap_slots () const [inline]
Definition at line 507 of file scopes.h.
{ return num_heap_slots_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), ContextLocalCount(), and v8::internal::ScopeInfo::Create().
num_stack_slots()
int v8::internal::Scope::num_stack_slots () const [inline]
Definition at line 506 of file scopes.h.
{ return num_stack_slots_; }
num_var()
int v8::internal::Scope::num_var () const [inline]
Definition at line 588 of file scopes.h.
{ return variables_.occupancy(); }
outer_scope()
Scope* v8::internal::Scope::outer_scope () const [inline]
Definition at line 492 of file scopes.h.
{ return outer_scope_; }
Referenced by v8::internal::ScopeIterator::AdvanceOneScope(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::AdvanceToNextNonHiddenScope(), v8::internal::DeclarationScope::AllocateScopeInfos(), AllocateScopeInfosRecursively(), AllocateStackSlot(), v8::internal::DeclarationScope::Analyze(), AnalyzePartially(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectAndStore(), ContextChainLengthUntilOutermostSloppyEval(), v8::internal::interpreter::BytecodeGenerator::CurrentScope::CurrentScope(), DeserializeScopeChain(), FinalizeBlockScope(), v8::internal::DeclarationScope::ForceEagerCompilation(), v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody(), GetClosureScope(), GetConstructorScope(), GetDeclarationScope(), GetHomeObjectScope(), GetNonEvalDeclarationScope(), GetOuterScopeWithContext(), GetReceiverScope(), GetScriptScope(), v8::internal::anonymous_namespace{liveedit.cc}::HasChangedScope(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::Parser::InsertShadowingVarBindingInitializers(), v8::internal::Parser::InsertSloppyBlockFunctionVarBindings(), v8::internal::ParserBase< Impl >::IsExtraordinaryPrivateNameAccessAllowed(), IsOuterScopeOf(), LookupForTesting(), LookupSloppyEval(), v8::internal::PrivateNameScopeIterator::Next(), v8::internal::ParserBase< Impl >::ParseFunctionBody(), v8::internal::ParserBase< Impl >::ParseObjectPropertyDefinition(), RecordInnerScopeEvalCall(), v8::internal::DeclarationScope::RecordNeedsPrivateNameContextChainRecalc(), ResolveVariablesRecursively(), Scope(), and v8::internal::Parser::SkipFunction().
private_name_lookup_skips_outer_class()
bool v8::internal::Scope::private_name_lookup_skips_outer_class () const [inline]
Definition at line 390 of file scopes.h.
                                                     {
    return private_name_lookup_skips_outer_class_;
  }
Referenced by v8::internal::ScopeInfo::Create(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), v8::internal::PrivateNameScopeIterator::Next(), and v8::internal::FunctionLiteral::private_name_lookup_skips_outer_class().
RecordEvalCall()
void v8::internal::Scope::RecordEvalCall () [inline]
Definition at line 1351 of file scopes.h.
                           {
  calls_eval_ = true;
  if (is_sloppy(language_mode())) {
    GetDeclarationScope()->RecordDeclarationScopeEvalCall();
  }
  RecordInnerScopeEvalCall();
  // The eval contents might access "super" (if it's inside a function that
  // binds super).
  DeclarationScope* receiver_scope = GetReceiverScope();
  DCHECK(!receiver_scope->is_arrow_scope());
  FunctionKind function_kind = receiver_scope->function_kind();
  if (BindsSuper(function_kind)) {
    receiver_scope->RecordSuperPropertyUsage();
  }
}
References v8::internal::BindsSuper(), calls_eval_, v8::internal::DCHECK(), v8::internal::DeclarationScope::function_kind(), GetDeclarationScope(), GetReceiverScope(), v8::internal::DeclarationScope::is_arrow_scope(), v8::internal::is_sloppy(), language_mode(), v8::internal::DeclarationScope::RecordDeclarationScopeEvalCall(), RecordInnerScopeEvalCall(), and v8::internal::DeclarationScope::RecordSuperPropertyUsage().
Referenced by v8::internal::ParserBase< Impl >::CheckPossibleEvalCall(), v8::internal::Scope::Snapshot::Reparent(), and v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
RecordInnerScopeEvalCall()
void v8::internal::Scope::RecordInnerScopeEvalCall () [inline]
Definition at line 280 of file scopes.h.
                                  {
    inner_scope_calls_eval_ = true;
    for (Scope* scope = outer_scope(); scope != nullptr;
         scope = scope->outer_scope()) {
      if (scope->inner_scope_calls_eval_) return;
      scope->inner_scope_calls_eval_ = true;
    }
  }
References outer_scope().
Referenced by RecordEvalCall(), and v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
RemoveDynamic()
void v8::internal::Scope::RemoveDynamic () [inline]
Definition at line 656 of file scopes.h.
                       {
    DCHECK_EQ(scope_type_, EVAL_SCOPE);
    variables_.RemoveDynamic();
  }
References DCHECK_EQ, and v8::internal::EVAL_SCOPE.
Referenced by v8::internal::DeclarationScope::Analyze(), and v8::internal::Parser::DoParseProgram().
RemoveInnerScope()
bool v8::internal::Scope::RemoveInnerScope (Scope * inner_scope) [inline]
Definition at line 624 of file scopes.h.
                                            {
    DCHECK_NOT_NULL(inner_scope);
    if (inner_scope == inner_scope_) {
      inner_scope_ = inner_scope_->sibling_;
      return true;
    }
    for (Scope* scope = inner_scope_; scope != nullptr;
         scope = scope->sibling_) {
      if (scope->sibling_ == inner_scope) {
        scope->sibling_ = scope->sibling_->sibling_;
        return true;
      }
    }
    return false;
  }
References DCHECK_NOT_NULL, and sibling_.
Referenced by FinalizeBlockScope().
ResolvePreparsedVariable()
void v8::internal::Scope::ResolvePreparsedVariable (VariableProxy * proxy, Scope * scope, Scope * end) [static], [private]
Definition at line 2354 of file scopes.cc.
                                                 {
  // Resolve the variable in all parsed scopes to force context allocation.
  for (; scope != end; scope = scope->outer_scope_) {
    Variable* var = scope->LookupLocal(proxy->raw_name());
    if (var != nullptr) {
      var->set_is_used();
      if (!var->is_dynamic()) {
        var->ForceContextAllocation();
        if (proxy->is_assigned()) var->SetMaybeAssigned();
        return;
      }
    }
  }
}
References v8::internal::compiler::end(), v8::internal::Variable::ForceContextAllocation(), v8::internal::VariableProxy::is_assigned(), v8::internal::Variable::is_dynamic(), LookupLocal(), outer_scope_, v8::internal::VariableProxy::raw_name(), v8::internal::Variable::set_is_used(), and v8::internal::Variable::SetMaybeAssigned().
Referenced by ResolveVariablesRecursively().
ResolveTo()
void v8::internal::Scope::ResolveTo (VariableProxy * proxy, Variable * var) [private]
Definition at line 2348 of file scopes.cc.
                                                         {
  DCHECK_NOT_NULL(var);
  UpdateNeedsHoleCheck(var, proxy, this);
  proxy->BindTo(var);
}
References v8::internal::VariableProxy::BindTo(), DCHECK_NOT_NULL, and v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck().
Referenced by ResolveVariable().
ResolveVariable()
void v8::internal::Scope::ResolveVariable (VariableProxy * proxy) [private]
Definition at line 2253 of file scopes.cc.
                                                {
  DCHECK(!proxy->is_resolved());
  Variable* var;
  if (V8_UNLIKELY(proxy->is_home_object())) {
    // VariableProxies of the home object cannot be resolved like a normal
    // variable. Consider the case of a super.property usage in heritage
    // position:
    //
    // class C extends super.foo { m() { super.bar(); } }
    //
    // The super.foo property access is logically nested under C's class scope,
    // which also has a home object due to its own method m's usage of
    // super.bar(). However, super.foo must resolve super in C's outer scope.
    //
    // Because of the above, start resolving home objects directly at the home
    // object scope instead of the current scope.
    Scope* scope = GetHomeObjectScope();
    DCHECK_NOT_NULL(scope);
    if (scope->scope_info_.is_null()) {
      var = Lookup<kParsedScope>(proxy, scope, nullptr);
    } else {
      var = Lookup<kDeserializedScope>(proxy, scope, nullptr, scope);
    }
  } else {
    var = Lookup<kParsedScope>(proxy, this, nullptr);
  }
  DCHECK_NOT_NULL(var);
  ResolveTo(proxy, var);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, GetHomeObjectScope(), v8::internal::VariableProxy::is_home_object(), v8::internal::VariableProxy::is_resolved(), ResolveTo(), scope_info_, and V8_UNLIKELY.
Referenced by ResolveVariablesRecursively().
ResolveVariablesRecursively()
bool v8::internal::Scope::ResolveVariablesRecursively (Scope * end) [private]
Definition at line 2370 of file scopes.cc.
                                                  {
  // Lazy parsed declaration scopes are already partially analyzed. If there are
  // unresolved references remaining, they just need to be resolved in outer
  // scopes.
  if (WasLazilyParsed(this)) {
    DCHECK_EQ(variables_.occupancy(), 0);
    // Resolve in all parsed scopes except for the script scope.
    if (!end->is_script_scope()) end = end->outer_scope();
    for (VariableProxy* proxy : unresolved_list_) {
      ResolvePreparsedVariable(proxy, outer_scope(), end);
    }
  } else {
    // Resolve unresolved variables for this scope.
    for (VariableProxy* proxy : unresolved_list_) {
      ResolveVariable(proxy);
    }
    // Resolve unresolved variables for inner scopes.
    for (Scope* scope = inner_scope_; scope != nullptr;
         scope = scope->sibling_) {
      if (!scope->ResolveVariablesRecursively(end)) return false;
    }
  }
  return true;
}
References DCHECK_EQ, v8::internal::compiler::end(), inner_scope_, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::occupancy(), outer_scope(), ResolvePreparsedVariable(), ResolveVariable(), sibling_, unresolved_list_, variables_, and v8::internal::anonymous_namespace{scopes.cc}::WasLazilyParsed().
Referenced by v8::internal::DeclarationScope::AllocateVariables().
RewriteReplGlobalVariables()
void v8::internal::Scope::RewriteReplGlobalVariables ()
Definition at line 1789 of file scopes.cc.
                                       {
  if (!GetScriptScope()->is_repl_mode_scope()) return;
  for (Scope* scope = this; scope != nullptr; scope = scope->outer_scope_) {
    for (VariableMap::Entry* p = scope->variables_.Start(); p != nullptr;
         p = scope->variables_.Next(p)) {
      Variable* var = reinterpret_cast<Variable*>(p->value);
      if (var->scope()->is_repl_mode_scope()) var->RewriteLocationForRepl();
    }
  }
}
References GetScriptScope(), is_repl_mode_scope(), outer_scope_, v8::internal::Variable::RewriteLocationForRepl(), and v8::internal::Variable::scope().
Referenced by v8::internal::DeclarationScope::Analyze().
SavePreparseData()
void v8::internal::Scope::SavePreparseData (Parser * parser) [private]
Definition at line 1719 of file scopes.cc.
                                           {
  this->ForEach([parser](Scope* scope) {
    // Save preparse data for every skippable scope, unless it was already
    // previously saved (this can happen with functions inside arrowheads).
    if (scope->IsSkippableFunctionScope() &&
        !scope->AsDeclarationScope()->was_lazily_parsed()) {
      scope->AsDeclarationScope()->SavePreparseDataForDeclarationScope(parser);
    }
    return Iteration::kDescend;
  });
}
References AsDeclarationScope(), ForEach(), IsSkippableFunctionScope(), and v8::internal::DeclarationScope::was_lazily_parsed().
Referenced by v8::internal::DeclarationScope::AnalyzePartially().
scope_info()
Handle<ScopeInfo> v8::internal::Scope::scope_info () const [inline]
Definition at line 583 of file scopes.h.
                                       {
    DCHECK(!scope_info_.is_null());
    return scope_info_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::ClassScope::ClassScope(), v8::internal::DeclarationScope::DeclarationScope(), DeserializeScopeChain(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), LookupInScopeInfo(), Scope(), v8::internal::interpreter::ConstantArrayBuilder::Entry::ToHandle(), v8::internal::SharedFunctionInfo::UpdateFromFunctionLiteralForLiveEdit(), and v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation().
scope_type()
ScopeType v8::internal::Scope::scope_type () const [inline]
Definition at line 478 of file scopes.h.
{ return scope_type_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), v8::internal::ScopeInfo::Create(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::FindScopeInfoForScope(), v8::internal::ParserBase< Impl >::IsExtraordinaryPrivateNameAccessAllowed(), v8::internal::PreParser::PreParseFunction(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::BaseConsumedPreparseData< Data >::RestoreScopeAllocationData(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveClosureScope(), v8::internal::Parser::RewriteClassLiteral(), v8::internal::PreparseDataBuilder::SaveDataForScope(), Scope(), v8::internal::ScopeIterator::Type(), and UniqueIdInScript().
set_end_position()
void v8::internal::Scope::set_end_position (int statement_pos) [inline]
Definition at line 345 of file scopes.h.
{ end_position_ = statement_pos; }
Referenced by v8::internal::PreParser::AddSyntheticFunctionDeclaration(), v8::internal::ClassScope::ClassScope(), v8::internal::Parser::DefaultConstructor(), DeserializeScopeChain(), v8::internal::Parser::DoParseProgram(), v8::internal::Parser::MakeAutoAccessorGetter(), v8::internal::Parser::MakeAutoAccessorSetter(), v8::internal::ParserBase< Impl >::ParseBlock(), v8::internal::ParserBase< Impl >::ParseClassLiteralBody(), v8::internal::ParserBase< Impl >::ParseClassStaticBlock(), v8::internal::ParserBase< Impl >::ParseForAwaitStatement(), v8::internal::ParserBase< Impl >::ParseForEachStatementWithDeclarations(), v8::internal::ParserBase< Impl >::ParseFunctionBody(), v8::internal::ParserBase< Impl >::ParseMemberInitializer(), v8::internal::ParserBase< Impl >::ParseObjectLiteral(), v8::internal::ParserBase< Impl >::ParseScopedStatement(), v8::internal::ParserBase< Impl >::ParseStandardForLoopWithLexicalDeclarations(), v8::internal::ParserBase< Impl >::ParseSwitchStatement(), v8::internal::ParserBase< Impl >::ParseTryStatement(), v8::internal::ParserBase< Impl >::ParseWithStatement(), v8::internal::PreParser::PreParseFunction(), and v8::internal::Parser::SkipFunction().
set_is_block_scope_for_object_literal()
void v8::internal::Scope::set_is_block_scope_for_object_literal () [inline]
Definition at line 384 of file scopes.h.
                                               {
    DCHECK(is_block_scope());
    is_block_scope_for_object_literal_ = true;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::ParserBase< Impl >::NewBlockScopeForObjectLiteral().
set_is_dynamic_scope()
void v8::internal::Scope::set_is_dynamic_scope () [inline]
Definition at line 609 of file scopes.h.
{ is_dynamic_scope_ = true; }
Referenced by DeserializeScopeChain().
set_is_hidden()
void v8::internal::Scope::set_is_hidden () [inline]
Definition at line 349 of file scopes.h.
{ is_hidden_ = true; }
Referenced by v8::internal::ParserBase< Impl >::ParseForAwaitStatement(), v8::internal::ParserBase< Impl >::ParseForEachStatementWithDeclarations(), v8::internal::ParserBase< Impl >::ParseForStatement(), and v8::internal::ParserBase< Impl >::ParseStandardForLoopWithLexicalDeclarations().
set_is_wrapped_function()
void v8::internal::Scope::set_is_wrapped_function () [inline]
Definition at line 405 of file scopes.h.
                                 {
    DCHECK(is_function_scope());
    is_wrapped_function_ = true;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Parser::ParseFunctionLiteral().
set_language_mode()
void v8::internal::Scope::set_language_mode (LanguageMode language_mode) [inline], [protected]
Definition at line 664 of file scopes.h.
                                                     {
    is_strict_ = is_strict(language_mode);
  }
References v8::internal::is_strict().
Referenced by v8::internal::ClassScope::ClassScope(), v8::internal::ModuleScope::ModuleScope(), Scope(), and SetDefaults().
set_needs_home_object()
void v8::internal::Scope::set_needs_home_object () [inline]
Definition at line 619 of file scopes.h.
                               {
    DCHECK(is_home_object_scope());
    needs_home_object_ = true;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::DeclarationScope::RecordSuperPropertyUsage().
set_start_position()
void v8::internal::Scope::set_start_position (int statement_pos) [inline]
Definition at line 341 of file scopes.h.
                                             {
    start_position_ = statement_pos;
  }
Referenced by v8::internal::PreParser::AddSyntheticFunctionDeclaration(), v8::internal::ClassScope::ClassScope(), v8::internal::Parser::DefaultConstructor(), DeserializeScopeChain(), v8::internal::Parser::DoParseFunction(), v8::internal::Parser::DoParseProgram(), v8::internal::ParserBase< Impl >::ClassInfo::EnsureInstanceMembersScope(), v8::internal::ParserBase< Impl >::ClassInfo::EnsureStaticElementsScope(), v8::internal::Parser::MakeAutoAccessorGetter(), v8::internal::Parser::MakeAutoAccessorSetter(), v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation(), v8::internal::ParserBase< Impl >::ParseBlock(), v8::internal::ParserBase< Impl >::ParseClassLiteral(), v8::internal::ParserBase< Impl >::ParseForAwaitStatement(), v8::internal::ParserBase< Impl >::ParseForEachStatementWithDeclarations(), v8::internal::ParserBase< Impl >::ParseForStatement(), v8::internal::ParserBase< Impl >::ParseFunctionBody(), v8::internal::Parser::ParseFunctionLiteral(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::ParserBase< Impl >::ParseObjectLiteral(), v8::internal::ParserBase< Impl >::ParseScopedStatement(), v8::internal::ParserBase< Impl >::ParseStandardForLoopWithLexicalDeclarations(), v8::internal::ParserBase< Impl >::ParseSwitchStatement(), v8::internal::ParserBase< Impl >::ParseTryStatement(), v8::internal::ParserBase< Impl >::ParseWithStatement(), and v8::internal::PreParser::PreParseFunction().
SetDefaults()
void v8::internal::Scope::SetDefaults () [private]
Definition at line 355 of file scopes.cc.
                        {
#ifdef DEBUG
  scope_name_ = nullptr;
  already_resolved_ = false;
  needs_migration_ = false;
#endif
  inner_scope_ = nullptr;
  sibling_ = nullptr;
  unresolved_list_.Clear();
  start_position_ = kNoSourcePosition;
  end_position_ = kNoSourcePosition;
  calls_eval_ = false;
  sloppy_eval_can_extend_vars_ = false;
  scope_nonlinear_ = false;
  is_hidden_ = false;
  is_dynamic_scope_ = scope_type_ == WITH_SCOPE;
  inner_scope_calls_eval_ = false;
  force_context_allocation_for_parameters_ = false;
  is_declaration_scope_ = false;
  private_name_lookup_skips_outer_class_ = false;
  must_use_preparsed_scope_data_ = false;
  needs_home_object_ = false;
  is_block_scope_for_object_literal_ = false;
  has_using_declaration_ = false;
  has_await_using_declaration_ = false;
  is_wrapped_function_ = false;
  has_context_cells_ = (is_script_scope() && v8_flags.script_context_cells) ||
                       (is_function_scope() && v8_flags.function_context_cells);
  num_stack_slots_ = 0;
  num_heap_slots_ = ContextHeaderLength();
  set_language_mode(LanguageMode::kSloppy);
}
References calls_eval_, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), ContextHeaderLength(), end_position_, force_context_allocation_for_parameters_, has_await_using_declaration_, has_context_cells_, has_using_declaration_, inner_scope_, inner_scope_calls_eval_, is_block_scope_for_object_literal_, is_declaration_scope_, is_dynamic_scope_, is_function_scope(), is_hidden_, is_script_scope(), is_wrapped_function_, v8::internal::kNoSourcePosition, v8::internal::kSloppy, must_use_preparsed_scope_data_, needs_home_object_, num_heap_slots_, num_stack_slots_, private_name_lookup_skips_outer_class_, scope_nonlinear_, scope_type_, set_language_mode(), sibling_, sloppy_eval_can_extend_vars_, start_position_, unresolved_list_, v8::internal::v8_flags, and v8::internal::WITH_SCOPE.
Referenced by Scope().
SetLanguageMode()
void v8::internal::Scope::SetLanguageMode (LanguageMode language_mode) [inline]
Definition at line 290 of file scopes.h.
                                                   {
    DCHECK(!is_module_scope() || is_strict(language_mode));
    set_language_mode(language_mode);
  }
References v8::internal::DCHECK(), and v8::internal::is_strict().
Referenced by v8::internal::Parser::DoParseProgram(), v8::internal::ParserBase< Impl >::ClassInfo::EnsureInstanceMembersScope(), v8::internal::ParserBase< Impl >::ClassInfo::EnsureStaticElementsScope(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::Parser::ParseREPLProgram(), v8::internal::Parser::SetLanguageMode(), and v8::internal::PreParser::SetLanguageMode().
SetMustUsePreparseData()
void v8::internal::Scope::SetMustUsePreparseData () [inline]
Definition at line 183 of file scopes.h.
                                {
    if (must_use_preparsed_scope_data_) {
      return;
    }
    must_use_preparsed_scope_data_ = true;
    if (outer_scope_) {
      outer_scope_->SetMustUsePreparseData();
    }
  }
Referenced by v8::internal::Parser::SkipFunction().
SetNonlinear()
void v8::internal::Scope::SetNonlinear () [inline]
Definition at line 304 of file scopes.h.
{ scope_nonlinear_ = true; }
Referenced by v8::internal::ParserBase< Impl >::ParseSwitchStatement().
SetScriptScopeInfo()
template<typename IsolateT >
void v8::internal::Scope::SetScriptScopeInfo (IsolateT * isolate, DeclarationScope * script_scope) [static]
Definition at line 538 of file scopes.cc.
                                                               {
  if (script_scope->scope_info_.is_null()) {
    script_scope->SetScriptScopeInfo(
        isolate->factory()->global_this_binding_scope_info());
  }
}
References scope_info_, and v8::internal::DeclarationScope::SetScriptScopeInfo().
Referenced by DeserializeScopeChain().
ShouldBanArguments()
bool v8::internal::Scope::ShouldBanArguments ()
Definition at line 1522 of file scopes.cc.
                               {
  return GetReceiverScope()->should_ban_arguments();
}
References GetReceiverScope(), and v8::internal::DeclarationScope::should_ban_arguments().
sibling()
Scope* v8::internal::Scope::sibling () const [inline]
Definition at line 489 of file scopes.h.
{ return sibling_; }
Referenced by v8::internal::Scope::Snapshot::Reparent(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForInnerScopes(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveClosureScope(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveStartScope(), v8::internal::PreparseDataBuilder::SaveDataForInnerScopes(), and v8::internal::PreparseDataBuilder::ScopeNeedsData().
start_position()
int v8::internal::Scope::start_position () const [inline]
Definition at line 340 of file scopes.h.
{ return start_position_; }
Referenced by v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::ContainsPosition(), v8::internal::ScopeInfo::Create(), v8::internal::Parser::CreateInitializerFunction(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::FindScopeInfoForScope(), v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), v8::internal::Parser::ParseFunction(), v8::internal::Parser::ParseFunctionLiteral(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::PreParser::PreParseFunction(), v8::internal::BaseConsumedPreparseData< Data >::RestoreScopeAllocationData(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveClosureScope(), v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveStartScope(), v8::internal::Parser::RewriteSwitchStatement(), v8::internal::PreparseDataBuilder::SaveDataForSkippableFunction(), v8::internal::PreparseDataBuilder::SaveScopeAllocationData(), v8::internal::Parser::SkipFunction(), v8::internal::ScopeIterator::start_position(), v8::internal::FunctionLiteral::start_position(), and UniqueIdInScript().
UniqueIdInScript()
int v8::internal::Scope::UniqueIdInScript () const
Definition at line 2586 of file scopes.cc.
                                  {
  // Script scopes start "before" the script to avoid clashing with a scope that
  // starts on character 0.
  if (is_script_scope() || scope_type() == EVAL_SCOPE ||
      scope_type() == MODULE_SCOPE) {
    return -2;
  }
  // Wrapped functions start before the function body, but after the script
  // start, to avoid clashing with a scope starting on character 0.
  if (is_wrapped_function()) {
    return -1;
  }
  if (is_declaration_scope()) {
    // Default constructors have the same start position as their parent class
    // scope. Use the next char position to distinguish this scope.
    return start_position() +
           IsDefaultConstructor(AsDeclarationScope()->function_kind());
  }
  return start_position();
}
References AsDeclarationScope(), v8::internal::EVAL_SCOPE, is_declaration_scope(), is_script_scope(), is_wrapped_function(), v8::internal::IsDefaultConstructor(), v8::internal::MODULE_SCOPE, scope_type(), and start_position().
Referenced by AllocateScopeInfosRecursively(), v8::internal::ScopeIterator::HasContext(), and v8::internal::ScopeIterator::Next().
zone()
Zone* v8::internal::Scope::zone () const [inline]
Definition at line 181 of file scopes.h.
{ return variables_.zone(); }
Referenced by v8::internal::Parser::AddFormalParameter(), v8::internal::DeclarationScope::AllocateScopeInfos(), AllocateScopeInfosRecursively(), v8::internal::DeclarationScope::DeclareArguments(), v8::internal::ClassScope::DeclareBrandVariable(), DeclareCatchVariableName(), v8::internal::ClassScope::DeclareClassVariable(), v8::internal::DeclarationScope::DeclareDefaultFunctionVariables(), v8::internal::DeclarationScope::DeclareDynamicGlobal(), v8::internal::DeclarationScope::DeclareFunctionVar(), DeclareHomeObjectVariable(), DeclareLocal(), v8::internal::DeclarationScope::DeclareParameter(), v8::internal::ClassScope::DeclarePrivateName(), DeclareStaticHomeObjectVariable(), v8::internal::DeclarationScope::DeclareThis(), DeserializeScopeChain(), v8::internal::ClassScope::EnsureRareData(), LookupInScopeInfo(), NewTemporary(), NonLocal(), v8::internal::DeclarationScope::ResetAfterPreparsing(), and Scope().
Friends And Related Function Documentation
ClassScope
friend class ClassScope [friend]
Definition at line 766 of file scopes.h.
DeclarationScope
friend class DeclarationScope [friend]
Definition at line 765 of file scopes.h.
ScopeTestHelper
friend class ScopeTestHelper [friend]
Definition at line 767 of file scopes.h.
Member Data Documentation
calls_eval_
bool v8::internal::Scope::calls_eval_ [private]
Definition at line 822 of file scopes.h.
Referenced by RecordEvalCall(), v8::internal::Scope::Snapshot::Reparent(), SetDefaults(), and v8::internal::Scope::Snapshot::Snapshot().
decls_
base::ThreadedList<Declaration> v8::internal::Scope::decls_ [private]
Definition at line 788 of file scopes.h.
Referenced by v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), DeclareVariable(), and v8::internal::DeclarationScope::ResetAfterPreparsing().
end_position_
int v8::internal::Scope::end_position_ [private]
Definition at line 807 of file scopes.h.
Referenced by SetDefaults().
force_context_allocation_for_parameters_
bool v8::internal::Scope::force_context_allocation_for_parameters_ [private]
Definition at line 835 of file scopes.h.
Referenced by SetDefaults().
has_await_using_declaration_
bool v8::internal::Scope::has_await_using_declaration_ [private]
Definition at line 852 of file scopes.h.
Referenced by SetDefaults().
has_context_cells_
bool v8::internal::Scope::has_context_cells_ [private]
Definition at line 859 of file scopes.h.
Referenced by v8::internal::DeclarationScope::AllocateParameterLocals(), AllocateVariablesRecursively(), Scope(), and SetDefaults().
has_using_declaration_
bool v8::internal::Scope::has_using_declaration_ [private]
Definition at line 851 of file scopes.h.
Referenced by SetDefaults().
inner_scope_
Scope* v8::internal::Scope::inner_scope_ [private]
Definition at line 772 of file scopes.h.
Referenced by AllocateScopeInfosRecursively(), FinalizeBlockScope(), ForEach(), HasThisReference(), v8::internal::Scope::Snapshot::Reparent(), v8::internal::DeclarationScope::ResetAfterPreparsing(), ResolveVariablesRecursively(), and SetDefaults().
inner_scope_calls_eval_
bool v8::internal::Scope::inner_scope_calls_eval_ [private]
Definition at line 834 of file scopes.h.
Referenced by FinalizeBlockScope(), MustAllocate(), MustAllocateInContext(), v8::internal::Scope::Snapshot::Reparent(), SetDefaults(), and v8::internal::ClassScope::should_save_class_variable().
is_block_scope_for_object_literal_
bool v8::internal::Scope::is_block_scope_for_object_literal_ [private]
Definition at line 848 of file scopes.h.
Referenced by Scope(), and SetDefaults().
is_declaration_scope_
bool v8::internal::Scope::is_declaration_scope_ [private]
Definition at line 838 of file scopes.h.
Referenced by SetDefaults(), and v8::internal::DeclarationScope::SetDefaults().
is_dynamic_scope_
bool v8::internal::Scope::is_dynamic_scope_ [private]
Definition at line 831 of file scopes.h.
Referenced by v8::internal::DeclarationScope::DeclarationScope(), is_debug_evaluate_scope(), Lookup(), v8::internal::Scope::Snapshot::Reparent(), and SetDefaults().
is_hidden_
bool v8::internal::Scope::is_hidden_ [private]
Definition at line 828 of file scopes.h.
Referenced by SetDefaults().
is_strict_
bool v8::internal::Scope::is_strict_ [private]
Definition at line 820 of file scopes.h.
is_wrapped_function_
bool v8::internal::Scope::is_wrapped_function_ [private]
Definition at line 856 of file scopes.h.
Referenced by SetDefaults().
locals_
base::ThreadedList<Variable> v8::internal::Scope::locals_ [private]
Definition at line 783 of file scopes.h.
Referenced by v8::internal::DeclarationScope::AddLocal(), AllocateNonParameterLocalsAndDeclaredGlobals(), v8::internal::ClassScope::DeclarePrivateName(), v8::internal::DeclarationScope::DeclareThis(), v8::internal::Scope::Snapshot::Reparent(), and v8::internal::DeclarationScope::ResetAfterPreparsing().
must_use_preparsed_scope_data_
bool v8::internal::Scope::must_use_preparsed_scope_data_ [private]
Definition at line 845 of file scopes.h.
Referenced by v8::internal::DeclarationScope::Analyze(), Scope(), and SetDefaults().
needs_home_object_
bool v8::internal::Scope::needs_home_object_ [private]
Definition at line 847 of file scopes.h.
Referenced by SetDefaults().
num_heap_slots_
int v8::internal::Scope::num_heap_slots_ [private]
Definition at line 811 of file scopes.h.
Referenced by AllocateHeapSlot(), AllocateScopeInfosRecursively(), AllocateVariablesRecursively(), FinalizeBlockScope(), Scope(), and SetDefaults().
num_stack_slots_
int v8::internal::Scope::num_stack_slots_ [private]
Definition at line 810 of file scopes.h.
Referenced by AllocateStackSlot(), and SetDefaults().
outer_scope_
Scope* v8::internal::Scope::outer_scope_ [private]
Definition at line 771 of file scopes.h.
Referenced by AddInnerScope(), v8::internal::DeclarationScope::AllocateScopeInfos(), AllowsLazyParsingWithoutUnresolvedVariables(), v8::internal::DeclarationScope::AnalyzePartially(), v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), ContextChainLength(), FinalizeBlockScope(), ForEach(), GetOuterScopeWithContext(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), Lookup(), LookupSloppyEval(), LookupWith(), v8::internal::Scope::Snapshot::Reparent(), ResolvePreparsedVariable(), v8::internal::ClassScope::ResolvePrivateNames(), RewriteReplGlobalVariables(), Scope(), v8::internal::DeclarationScope::SetDefaults(), and v8::internal::DeclarationScope::TakeUnresolvedReferencesFromParent().
private_name_lookup_skips_outer_class_
bool v8::internal::Scope::private_name_lookup_skips_outer_class_ [private]
Definition at line 843 of file scopes.h.
Referenced by Scope(), and SetDefaults().
scope_info_
IndirectHandle<ScopeInfo> v8::internal::Scope::scope_info_ [private]
Definition at line 791 of file scopes.h.
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), AllocateScopeInfosRecursively(), v8::internal::DeclarationScope::Analyze(), DeclareCatchVariableName(), DeclareVariableName(), v8::internal::DeclarationScope::DeserializeReceiver(), DeserializeScopeChain(), HasReceiverToDeserialize(), is_debug_evaluate_scope(), Lookup(), LookupInScopeInfo(), v8::internal::ClassScope::LookupPrivateName(), v8::internal::ClassScope::LookupPrivateNameInScopeInfo(), LookupSloppyEval(), LookupWith(), ResolveVariable(), and SetScriptScopeInfo().
scope_nonlinear_
bool v8::internal::Scope::scope_nonlinear_ [private]
Definition at line 827 of file scopes.h.
Referenced by SetDefaults().
scope_type_
const ScopeType v8::internal::Scope::scope_type_ [private]
Definition at line 814 of file scopes.h.
Referenced by AllocateScopeInfosRecursively(), v8::internal::DeclarationScope::Analyze(), and SetDefaults().
sibling_
Scope* v8::internal::Scope::sibling_ [private]
Definition at line 773 of file scopes.h.
Referenced by AddInnerScope(), AllocateScopeInfosRecursively(), FinalizeBlockScope(), ForEach(), HasThisReference(), RemoveInnerScope(), v8::internal::Scope::Snapshot::Reparent(), ResolveVariablesRecursively(), and SetDefaults().
sloppy_eval_can_extend_vars_
bool v8::internal::Scope::sloppy_eval_can_extend_vars_ [private]
Definition at line 825 of file scopes.h.
Referenced by AllocateVariablesRecursively(), v8::internal::DeclarationScope::DeclarationScope(), v8::internal::DeclarationScope::RecordDeclarationScopeEvalCall(), v8::internal::Scope::Snapshot::Reparent(), SetDefaults(), and v8::internal::Scope::Snapshot::Snapshot().
start_position_
int v8::internal::Scope::start_position_ [private]
Definition at line 806 of file scopes.h.
Referenced by SetDefaults().
unresolved_list_
UnresolvedList v8::internal::Scope::unresolved_list_ [private]
Definition at line 786 of file scopes.h.
Referenced by AddUnresolved(), AnalyzePartially(), v8::internal::DeclarationScope::AnalyzePartially(), DeleteUnresolved(), FinalizeBlockScope(), v8::internal::Scope::Snapshot::Reparent(), v8::internal::DeclarationScope::ResetAfterPreparsing(), ResolveVariablesRecursively(), SetDefaults(), and v8::internal::DeclarationScope::TakeUnresolvedReferencesFromParent().
variables_
VariableMap v8::internal::Scope::variables_ [private]
Definition at line 780 of file scopes.h.
Referenced by v8::internal::DeclarationScope::DeclareDynamicGlobal(), v8::internal::DeclarationScope::DeclareFunctionVar(), FinalizeBlockScope(), FindVariableDeclaredIn(), Lookup(), LookupInScopeInfo(), LookupSloppyEval(), LookupWith(), NonLocal(), v8::internal::DeclarationScope::ResetAfterPreparsing(), and ResolveVariablesRecursively().
Zone
friend v8::internal::Scope::Zone [private]
Definition at line 768 of file scopes.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/scopes.h
/mnt/V8SourceCode/src/ast/scopes.cc