v8::internal::wasm::WasmDeoptDataProcessor Class Reference
#include <wasm-deopt-data.h>
Static Public Member Functions
static base::OwnedVector< uint8_t > Serialize (int deopt_exit_start_offset, int eager_deopt_count, base::Vector< const uint8_t > translation_array, base::Vector< wasm::WasmDeoptEntry > deopt_entries, const ZoneDeque< DeoptimizationLiteral > &deopt_literals)
Detailed Description
Definition at line 86 of file wasm-deopt-data.h.
Member Function Documentation
Serialize()
base::OwnedVector< uint8_t > v8::internal::wasm::WasmDeoptDataProcessor::Serialize (int deopt_exit_start_offset, int eager_deopt_count, base::Vector< const uint8_t > translation_array, base::Vector< wasm::WasmDeoptEntry > deopt_entries, const ZoneDeque< DeoptimizationLiteral > & deopt_literals) [static]
Definition at line 27 of file wasm-deopt-data.cc.
                                                            {
  wasm::WasmDeoptData data;
  data.entry_count = eager_deopt_count;
  data.deopt_exit_start_offset = deopt_exit_start_offset;
  data.eager_deopt_count = eager_deopt_count;
  data.deopt_literals_size = static_cast<uint32_t>(deopt_literals.size());
  data.translation_array_size = static_cast<uint32_t>(translation_array.size());
  size_t translation_array_byte_size =
      translation_array.size() * sizeof(translation_array[0]);
  size_t deopt_entries_byte_size =
      deopt_entries.size() * sizeof(deopt_entries[0]);
  size_t deopt_literals_byte_size =
      deopt_literals.size() * sizeof(deopt_literals[0]);
  size_t byte_size = sizeof(data) + translation_array_byte_size +
                     deopt_entries_byte_size + deopt_literals_byte_size;
  auto result = base::OwnedVector<uint8_t>::New(byte_size);
  uint8_t* result_iter = result.begin();
  std::memcpy(result_iter, &data, sizeof(data));
  result_iter += sizeof(data);
  std::memcpy(result_iter, translation_array.data(),
              translation_array_byte_size);
  result_iter += translation_array_byte_size;
  std::memcpy(result_iter, deopt_entries.data(), deopt_entries_byte_size);
  result_iter += deopt_entries_byte_size;
  static_assert(std::is_trivially_copyable_v<
                std::remove_reference<decltype(deopt_literals[0])>>);
  for (const auto& literal : deopt_literals) {
    // We can't serialize objects. Wasm should never contain object literals as
    // it is isolate-independent.
    CHECK_NE(literal.kind(), DeoptimizationLiteralKind::kObject);
    std::memcpy(result_iter, &literal, sizeof(literal));
    result_iter += sizeof(literal);
  }
  DCHECK_EQ(result_iter, result.end());
  return result;
}
References CHECK_NE, v8::base::Vector< T >::data(), DCHECK_EQ, v8::internal::wasm::WasmDeoptData::deopt_exit_start_offset, v8::internal::wasm::WasmDeoptData::deopt_literals_size, v8::internal::wasm::WasmDeoptData::eager_deopt_count, v8::internal::wasm::WasmDeoptData::entry_count, v8::internal::kObject, v8::base::OwnedVector< T >::New(), v8::base::internal::result, v8::base::Vector< T >::size(), and v8::internal::wasm::WasmDeoptData::translation_array_size.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-deopt-data.h
/mnt/V8SourceCode/src/wasm/wasm-deopt-data.cc