v8::internal::compiler::DescriptorArrayRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< DescriptorArray > object () const
PropertyDetails GetPropertyDetails (InternalIndex descriptor_index) const
NameRef GetPropertyKey (JSHeapBroker *broker, InternalIndex descriptor_index) const
OptionalObjectRef GetStrongValue (JSHeapBroker *broker, InternalIndex descriptor_index) const
Detailed Description
Definition at line 822 of file heap-refs.h.
Member Function Documentation
GetPropertyDetails()
PropertyDetails v8::internal::compiler::DescriptorArrayRef::GetPropertyDetails (InternalIndex descriptor_index) const
Definition at line 2305 of file heap-refs.cc.
                                          {
  return object()->GetDetails(descriptor_index);
}
References object().
Referenced by v8::internal::compiler::MapRef::GetPropertyDetails().
GetPropertyKey()
NameRef v8::internal::compiler::DescriptorArrayRef::GetPropertyKey (JSHeapBroker * broker, InternalIndex descriptor_index) const
Definition at line 2310 of file heap-refs.cc.
                                                                {
  // A property key that has been written to a descriptor array must be being
  // read because it was observed in a map, which means this write must have
  // been published.
  NameRef result =
      MakeRefAssumeMemoryFence(broker, object()->GetKey(descriptor_index));
  CHECK(result.IsUniqueName());
  return result;
}
References broker(), CHECK, v8::internal::compiler::MakeRefAssumeMemoryFence(), and v8::base::internal::result.
Referenced by v8::internal::compiler::MapRef::GetPropertyKey(), and v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty().
GetStrongValue()
OptionalObjectRef v8::internal::compiler::DescriptorArrayRef::GetStrongValue (JSHeapBroker * broker, InternalIndex descriptor_index) const
Definition at line 2321 of file heap-refs.cc.
                                                                {
  Tagged<HeapObject> heap_object;
  if (!object()
           ->GetValue(descriptor_index)
           .GetHeapObjectIfStrong(&heap_object)) {
    return {};
  }
  // Since the descriptors in the descriptor array can be changed in-place
  // via DescriptorArray::Replace, we might get a value that we haven't seen
  // before.
  return TryMakeRef(broker, heap_object);
}
References broker(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::MapRef::GetStrongValue().
object()
IndirectHandle<DescriptorArray> v8::internal::compiler::DescriptorArrayRef::object () const
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), GetPropertyDetails(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), and v8::internal::compiler::AccessInfoFactory::TryLoadPropertyDetails().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc