v8::internal::compiler::MoveOperands Class Reference
#include <instruction.h>
Public Member Functions
MoveOperands (const InstructionOperand &source, const InstructionOperand &destination)
MoveOperands (const MoveOperands &)=delete
MoveOperands & operator= (const MoveOperands &)=delete
void CheckPointerCompressionConsistency ()
const InstructionOperand & source () const
InstructionOperand & source ()
void set_source (const InstructionOperand &operand)
const InstructionOperand & destination () const
InstructionOperand & destination ()
void set_destination (const InstructionOperand &operand)
bool IsPending () const
void SetPending ()
bool IsRedundant () const
void Eliminate ()
bool IsEliminated () const
void Print () const
bool Equals (const MoveOperands &that) const
Private Attributes
InstructionOperand source_
InstructionOperand destination_
Detailed Description
Definition at line 768 of file instruction.h.
Constructor & Destructor Documentation
MoveOperands() [1/2]
v8::internal::compiler::MoveOperands::MoveOperands (const InstructionOperand & source, const InstructionOperand & destination) [inline]
Definition at line 771 of file instruction.h.
      : source_(source), destination_(destination) {
    DCHECK(!source.IsInvalid() && !destination.IsInvalid());
    CheckPointerCompressionConsistency();
  }
References v8::internal::DCHECK().
MoveOperands() [2/2]
v8::internal::compiler::MoveOperands::MoveOperands (const MoveOperands &) [delete]
Member Function Documentation
CheckPointerCompressionConsistency()
void v8::internal::compiler::MoveOperands::CheckPointerCompressionConsistency () [inline]
Definition at line 781 of file instruction.h.
                                            {
#if DEBUG && V8_COMPRESS_POINTERS
    if (!source_.IsLocationOperand()) return;
    if (!destination_.IsLocationOperand()) return;
    using MR = MachineRepresentation;
    MR dest_rep = LocationOperand::cast(&destination_)->representation();
    if (dest_rep == MR::kTagged || dest_rep == MR::kTaggedPointer) {
      MR src_rep = LocationOperand::cast(&source_)->representation();
      DCHECK_NE(src_rep, MR::kCompressedPointer);
      // TODO(dmercadier): it would be nice to insert a DEBUG runtime check here
      // to make sure that if `src_rep` is kCompressed, then the value is a Smi.
    }
#endif
  }
References v8::internal::compiler::LocationOperand::cast(), DCHECK_NE, and v8::internal::compiler::LocationOperand::representation().
destination() [1/2]
InstructionOperand& v8::internal::compiler::MoveOperands::destination () [inline]
Definition at line 804 of file instruction.h.
{ return destination_; }
destination() [2/2]
const InstructionOperand& v8::internal::compiler::MoveOperands::destination () const [inline]
Definition at line 803 of file instruction.h.
{ return destination_; }
Referenced by v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::IsSwap(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::LoadCompare(), v8::internal::compiler::operator<<(), v8::internal::compiler::GapResolver::PerformCycle(), v8::internal::compiler::GapResolver::PerformMoveHelper(), v8::internal::compiler::ParallelMove::PrepareInsertAfter(), Print(), v8::internal::compiler::GapResolver::Resolve(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), and v8::internal::compiler::CodeGenerator::SetPendingMove().
Eliminate()
void v8::internal::compiler::MoveOperands::Eliminate () [inline]
Definition at line 825 of file instruction.h.
{ source_ = destination_ = InstructionOperand(); }
References v8::internal::compiler::InstructionOperand::InstructionOperand().
Referenced by v8::internal::compiler::ParallelMove::Eliminate(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::GapResolver::PerformCycle(), and v8::internal::compiler::GapResolver::PerformMoveHelper().
Equals()
bool v8::internal::compiler::MoveOperands::Equals (const MoveOperands & that) const [inline]
Definition at line 834 of file instruction.h.
                                              {
    if (IsRedundant() && that.IsRedundant()) return true;
    return source_.Equals(that.source_) &&
           destination_.Equals(that.destination_);
  }
References destination_, IsRedundant(), and source_.
IsEliminated()
bool v8::internal::compiler::MoveOperands::IsEliminated () const [inline]
Definition at line 826 of file instruction.h.
                            {
    DCHECK_IMPLIES(source_.IsInvalid(), destination_.IsInvalid());
    return source_.IsInvalid();
  }
References DCHECK_IMPLIES.
Referenced by v8::internal::compiler::ParallelMove::PrepareInsertAfter().
IsPending()
bool v8::internal::compiler::MoveOperands::IsPending () const [inline]
Definition at line 812 of file instruction.h.
                         {
    return destination_.IsInvalid() && !source_.IsInvalid();
  }
Referenced by v8::internal::compiler::GapResolver::PerformMoveHelper().
IsRedundant()
bool v8::internal::compiler::MoveOperands::IsRedundant () const [inline]
Definition at line 819 of file instruction.h.
                           {
    DCHECK_IMPLIES(!destination_.IsInvalid(), !destination_.IsConstant());
    return IsEliminated() || source_.EqualsCanonicalized(destination_);
  }
References DCHECK_IMPLIES.
Referenced by Equals(), v8::internal::compiler::ParallelMove::IsRedundant(), v8::internal::compiler::GapResolver::PerformMoveHelper(), and v8::internal::compiler::GapResolver::Resolve().
operator=()
MoveOperands& v8::internal::compiler::MoveOperands::operator= (const MoveOperands &) [delete]
Print()
void v8::internal::compiler::MoveOperands::Print () const
Definition at line 316 of file instruction.cc.
                               {
  StdoutStream{} << destination() << " = " << source() << std::endl;
}
References destination(), and source().
set_destination()
void v8::internal::compiler::MoveOperands::set_destination (const InstructionOperand & operand) [inline]
Definition at line 805 of file instruction.h.
                                                          {
    destination_ = operand;
    CheckPointerCompressionConsistency();
  }
Referenced by v8::internal::compiler::GapResolver::PerformMoveHelper().
set_source()
void v8::internal::compiler::MoveOperands::set_source (const InstructionOperand & operand) [inline]
Definition at line 798 of file instruction.h.
                                                     {
    source_ = operand;
    CheckPointerCompressionConsistency();
  }
Referenced by v8::internal::compiler::ParallelMove::PrepareInsertAfter().
SetPending()
void v8::internal::compiler::MoveOperands::SetPending () [inline]
Definition at line 815 of file instruction.h.
{ destination_ = InstructionOperand(); }
References v8::internal::compiler::InstructionOperand::InstructionOperand().
Referenced by v8::internal::compiler::GapResolver::PerformMoveHelper().
source() [1/2]
InstructionOperand& v8::internal::compiler::MoveOperands::source () [inline]
Definition at line 797 of file instruction.h.
{ return source_; }
source() [2/2]
const InstructionOperand& v8::internal::compiler::MoveOperands::source () const [inline]
Definition at line 796 of file instruction.h.
{ return source_; }
Referenced by v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::IsSwap(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::LoadCompare(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::operator<<(), v8::internal::compiler::GapResolver::PerformCycle(), v8::internal::compiler::GapResolver::PerformMoveHelper(), v8::internal::compiler::ParallelMove::PrepareInsertAfter(), Print(), v8::internal::compiler::GapResolver::Resolve(), and v8::internal::compiler::CodeGenerator::SetPendingMove().
Member Data Documentation
destination_
InstructionOperand v8::internal::compiler::MoveOperands::destination_ [private]
Definition at line 842 of file instruction.h.
Referenced by Equals().
source_
InstructionOperand v8::internal::compiler::MoveOperands::source_ [private]
Definition at line 841 of file instruction.h.
Referenced by Equals().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc