v8::internal::maglev::Float64Compare Class Reference
#include <maglev-ir.h>
Public Member Functions
Float64Compare (uint64_t bitfield, Operation operation)
Input & left_input ()
Input & right_input ()
constexpr Operation operation () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes
static constexpr int kLeftIndex = 0
static constexpr int kRightIndex = 1
Private Types
using Base = FixedInputValueNodeT< 2, Float64Compare >
using OperationBitField = NextBitField< Operation, 5 >
Additional Inherited Members
Detailed Description
Definition at line 3481 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Float64Compare::Base = FixedInputValueNodeT<2, Float64Compare> [private]
Definition at line 3482 of file maglev-ir.h.
OperationBitField
using v8::internal::maglev::Float64Compare::OperationBitField = NextBitField<Operation, 5> [private]
Definition at line 3507 of file maglev-ir.h.
Constructor & Destructor Documentation
Float64Compare()
v8::internal::maglev::Float64Compare::Float64Compare (uint64_t bitfield, Operation operation) [inline], [explicit]
Definition at line 3485 of file maglev-ir.h.
      : Base(OperationBitField::update(bitfield, operation)) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::Float64Compare::GenerateCode (MaglevAssembler * , const ProcessingState &)
left_input()
Input& v8::internal::maglev::Float64Compare::left_input () [inline]
Definition at line 3493 of file maglev-ir.h.
{ return Node::input(kLeftIndex); }
References v8::internal::maglev::NodeBase::input(), and kLeftIndex.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
operation()
constexpr Operation v8::internal::maglev::Float64Compare::operation () const [inline], [constexpr]
Definition at line 3496 of file maglev-ir.h.
                                        {
    return OperationBitField::decode(bitfield());
  }
Referenced by options(), PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::Float64Compare::options () const [inline]
Definition at line 3504 of file maglev-ir.h.
{ return std::tuple{operation()}; }
References operation().
PrintParams()
void v8::internal::maglev::Float64Compare::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8306 of file maglev-ir.cc.
                                                                            {
  os << "(" << operation() << ")";
}
References operation().
right_input()
Input& v8::internal::maglev::Float64Compare::right_input () [inline]
Definition at line 3494 of file maglev-ir.h.
{ return Node::input(kRightIndex); }
References v8::internal::maglev::NodeBase::input(), and kRightIndex.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::Float64Compare::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::Float64Compare::kInputTypes [static], [constexpr]
Initial value:
{ValueRepresentation::kFloat64,
                                                ValueRepresentation::kFloat64}
Definition at line 3488 of file maglev-ir.h.
kLeftIndex
constexpr int v8::internal::maglev::Float64Compare::kLeftIndex = 0 [static], [constexpr]
Definition at line 3491 of file maglev-ir.h.
Referenced by left_input().
kRightIndex
constexpr int v8::internal::maglev::Float64Compare::kRightIndex = 1 [static], [constexpr]
Definition at line 3492 of file maglev-ir.h.
Referenced by right_input().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc