v8::internal::wasm::gdb_server::wasm_addr_t Class Reference
#include <gdb-remote-util.h>
Public Member Functions
wasm_addr_t (uint32_t module_id, uint32_t offset)
wasm_addr_t (uint64_t address)
uint32_t ModuleId () const
uint32_t Offset () const
operator uint64_t () const
Private Attributes
uint32_t module_id_
uint32_t offset_
Detailed Description
Definition at line 48 of file gdb-remote-util.h.
Constructor & Destructor Documentation
wasm_addr_t() [1/2]
v8::internal::wasm::gdb_server::wasm_addr_t::wasm_addr_t (uint32_t module_id, uint32_t offset) [inline]
Definition at line 50 of file gdb-remote-util.h.
      : module_id_(module_id), offset_(offset) {}
wasm_addr_t() [2/2]
v8::internal::wasm::gdb_server::wasm_addr_t::wasm_addr_t (uint64_t address) [inline], [explicit]
Definition at line 52 of file gdb-remote-util.h.
      : module_id_(address >> 32), offset_(address & 0xffffffff) {}
Member Function Documentation
ModuleId()
uint32_t v8::internal::wasm::gdb_server::wasm_addr_t::ModuleId () const [inline]
Definition at line 55 of file gdb-remote-util.h.
{ return module_id_; }
References module_id_.
Referenced by v8::internal::wasm::gdb_server::GdbServer::GetWasmModuleBytes(), v8::internal::wasm::gdb_server::GdbServer::PrepareStep(), and v8::internal::wasm::gdb_server::Target::ProcessPacket().
Offset()
uint32_t v8::internal::wasm::gdb_server::wasm_addr_t::Offset () const [inline]
Definition at line 56 of file gdb-remote-util.h.
{ return offset_; }
References offset_.
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmModuleBytes(), and v8::internal::wasm::gdb_server::Target::ProcessPacket().
operator uint64_t()
v8::internal::wasm::gdb_server::wasm_addr_t::operator uint64_t () const [inline]
Definition at line 58 of file gdb-remote-util.h.
                                   {
    return static_cast<uint64_t>(module_id_) << 32 | offset_;
  }
References module_id_, and offset_.
Member Data Documentation
module_id_
uint32_t v8::internal::wasm::gdb_server::wasm_addr_t::module_id_ [private]
Definition at line 63 of file gdb-remote-util.h.
Referenced by ModuleId(), and operator uint64_t().
offset_
uint32_t v8::internal::wasm::gdb_server::wasm_addr_t::offset_ [private]
Definition at line 64 of file gdb-remote-util.h.
Referenced by Offset(), and operator uint64_t().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/gdb-remote-util.h