v8::internal::wasm::WasmInterpreter::CodeMap Class Reference
#include <wasm-interpreter.h>
Public Member Functions
CodeMap (Isolate *isolate, const WasmModule *module, const uint8_t *module_start, Zone *zone)
const WasmModule * module () const
InterpreterCode * GetCode (uint32_t function_index)
WasmBytecode * GetFunctionBytecode (uint32_t func_index)
void AddFunction (const WasmFunction *function, const uint8_t *code_start, const uint8_t *code_end)
size_t TotalBytecodeSize ()
Private Member Functions
void Preprocess (uint32_t function_index)
Private Attributes
Zone * zone_
Isolate * isolate_
const WasmModule * module_
ZoneVector< InterpreterCode > interpreter_code_
base::TimeDelta bytecode_generation_time_
std::atomic< size_t > generated_code_size_
Detailed Description
Definition at line 589 of file wasm-interpreter.h.
Constructor & Destructor Documentation
CodeMap()
v8::internal::wasm::WasmInterpreter::CodeMap::CodeMap (Isolate * isolate, const WasmModule * module, const uint8_t * module_start, Zone * zone)
Definition at line 92 of file wasm-interpreter.cc.
    : zone_(zone),
      isolate_(isolate),
      module_(module),
      interpreter_code_(zone),
      bytecode_generation_time_(),
      generated_code_size_(0) {
  if (module == nullptr) return;
  interpreter_code_.reserve(module->functions.size());
  for (const WasmFunction& function : module->functions) {
    if (function.imported) {
      DCHECK(!function.code.is_set());
      AddFunction(&function, nullptr, nullptr);
    } else {
      AddFunction(&function, module_start + function.code.offset(),
                  module_start + function.code.end_offset());
    }
  }
}
References AddFunction(), code, v8::internal::DCHECK(), v8::internal::wasm::WasmModule::functions, interpreter_code_, and module().
Member Function Documentation
AddFunction()
void v8::internal::wasm::WasmInterpreter::CodeMap::AddFunction (const WasmFunction * function, const uint8_t * code_start, const uint8_t * code_end) [inline]
Definition at line 40 of file wasm-interpreter-inl.h.
                                                                           {
  DCHECK_EQ(interpreter_code_.size(), function->func_index);
  interpreter_code_.emplace_back(function, BodyLocalDecls(),
                                 const_cast<uint8_t*>(code_start),
                                 const_cast<uint8_t*>(code_end));
}
References DCHECK_EQ.
Referenced by CodeMap().
GetCode()
InterpreterCode * v8::internal::wasm::WasmInterpreter::CodeMap::GetCode (uint32_t function_index) [inline]
Definition at line 21 of file wasm-interpreter-inl.h.
                             {
  DCHECK_LT(function_index, interpreter_code_.size());
  InterpreterCode* code = &interpreter_code_[function_index];
  if (V8_UNLIKELY(!code->bytecode && code->start)) {
    Preprocess(function_index);
  }
  return code;
}
References code, DCHECK_LT, interpreter_code_, Preprocess(), and V8_UNLIKELY.
Referenced by v8::internal::wasm::WasmInterpreter::BeginExecution().
GetFunctionBytecode()
WasmBytecode * v8::internal::wasm::WasmInterpreter::CodeMap::GetFunctionBytecode (uint32_t func_index) [inline]
Definition at line 31 of file wasm-interpreter-inl.h.
                         {
  DCHECK_LT(func_index, interpreter_code_.size());
  // This precompiles the target function.
  InterpreterCode* code = GetCode(func_index);
  return code->bytecode.get();
}
References code, and DCHECK_LT.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::GetFunctionBytecode().
module()
const WasmModule* v8::internal::wasm::WasmInterpreter::CodeMap::module () const [inline]
Definition at line 594 of file wasm-interpreter.h.
{ return module_; }
Referenced by CodeMap().
Preprocess()
void v8::internal::wasm::WasmInterpreter::CodeMap::Preprocess (uint32_t function_index) [private]
Definition at line 113 of file wasm-interpreter.cc.
                                                               {
  InterpreterCode* code = &interpreter_code_[function_index];
  DCHECK_EQ(code->function->imported, code->start == nullptr);
  DCHECK(!code->bytecode && code->start);
  base::TimeTicks start_time = base::TimeTicks::Now();
  // Compute the control targets map and the local declarations.
  BytecodeIterator it(code->start, code->end, &code->locals, zone_);
  WasmBytecodeGenerator bytecode_generator(function_index, code, module_);
  code->bytecode = bytecode_generator.GenerateBytecode();
  // Generate histogram sample to measure the time spent generating the
  // bytecode. Reuse the WasmCompileModuleMicroSeconds.wasm that is currently
  // obsolete.
  if (base::TimeTicks::IsHighResolution()) {
    base::TimeDelta duration = base::TimeTicks::Now() - start_time;
    bytecode_generation_time_ += duration;
    int bytecode_generation_time_usecs =
        static_cast<int>(bytecode_generation_time_.InMicroseconds());
    // TODO(paolosev@microsoft.com) Do not add a sample for each function!
    isolate_->counters()->wasm_compile_wasm_module_time()->AddSample(
        bytecode_generation_time_usecs);
  }
  // Generate histogram sample to measure the bytecode size. Reuse the
  // V8.WasmModuleCodeSizeMiB (see {NativeModule::SampleCodeSize}).
  int prev_code_size_mb = generated_code_size_ == 0
                              ? -1
                              : static_cast<int>(generated_code_size_ / MB);
  generated_code_size_.fetch_add(code->bytecode->GetCodeSize());
  int code_size_mb = static_cast<int>(generated_code_size_ / MB);
  if (prev_code_size_mb < code_size_mb) {
    Histogram* histogram = isolate_->counters()->wasm_module_code_size_mb();
    histogram->AddSample(code_size_mb);
  }
}
References v8::internal::Histogram::AddSample(), code, v8::internal::Histogram::counters(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::duration, v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), v8::base::TimeTicks::IsHighResolution(), v8::internal::MB, v8::base::TimeTicks::Now(), and v8::internal::wasm::WasmInterpreter::zone_.
Referenced by GetCode().
TotalBytecodeSize()
size_t v8::internal::wasm::WasmInterpreter::CodeMap::TotalBytecodeSize () [inline]
Definition at line 603 of file wasm-interpreter.h.
                               {
      return generated_code_size_.load(std::memory_order_relaxed);
    }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::TotalBytecodeSize().
Member Data Documentation
bytecode_generation_time_
base::TimeDelta v8::internal::wasm::WasmInterpreter::CodeMap::bytecode_generation_time_ [private]
Definition at line 615 of file wasm-interpreter.h.
generated_code_size_
std::atomic<size_t> v8::internal::wasm::WasmInterpreter::CodeMap::generated_code_size_ [private]
Definition at line 616 of file wasm-interpreter.h.
interpreter_code_
ZoneVector<InterpreterCode> v8::internal::wasm::WasmInterpreter::CodeMap::interpreter_code_ [private]
Definition at line 613 of file wasm-interpreter.h.
Referenced by CodeMap(), and GetCode().
isolate_
Isolate* v8::internal::wasm::WasmInterpreter::CodeMap::isolate_ [private]
Definition at line 611 of file wasm-interpreter.h.
module_
const WasmModule* v8::internal::wasm::WasmInterpreter::CodeMap::module_ [private]
Definition at line 612 of file wasm-interpreter.h.
zone_
Zone* v8::internal::wasm::WasmInterpreter::CodeMap::zone_ [private]
Definition at line 610 of file wasm-interpreter.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc