v8::internal::PerfettoLogger Class Reference
#include <perfetto-logger.h>
Public Member Functions
PerfettoLogger (Isolate *isolate)
~PerfettoLogger () override
void LogExistingCode ()
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char *name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name, int line, int column) override
void CallbackEvent (DirectHandle< Name > name, Address entry_point) override
void GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) override
void CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) override
void BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) override
void SharedFunctionInfoMoveEvent (Address from, Address to) override
void NativeContextMoveEvent (Address from, Address to) override
void CodeMovingGCEvent () override
void CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) override
void CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) override
void CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > shared, const char *reason) override
void WeakCodeClearEvent () override
bool is_listening_to_code_events () override
Static Public Member Functions
static void RegisterIsolate (Isolate *isolate)
static void UnregisterIsolate (Isolate *isolate)
static void OnCodeDataSourceStart ()
static void OnCodeDataSourceStop ()
Private Attributes
Isolate & isolate_
Additional Inherited Members
Detailed Description
Definition at line 16 of file perfetto-logger.h.
Constructor & Destructor Documentation
PerfettoLogger()
v8::internal::PerfettoLogger::PerfettoLogger (Isolate * isolate) [explicit]
Definition at line 253 of file perfetto-logger.cc.
: isolate_(*isolate) {}
 PerfettoLogger()
v8::internal::PerfettoLogger::~PerfettoLogger () [override]
Definition at line 254 of file perfetto-logger.cc.
{}
Member Function Documentation
BytecodeMoveEvent()
void v8::internal::PerfettoLogger::BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 437 of file perfetto-logger.cc.
                                                                 {
  CodeDataSource::Trace(
      [&](v8::internal::CodeDataSource::TraceContext trace_context) {
        CodeTraceContext ctx = NewCodeTraceContext(trace_context);
        auto* code_move = ctx.set_code_move();
        code_move->set_isolate_iid(ctx.InternIsolate(isolate_));
        code_move->set_from_instruction_start_address(
            from->GetFirstBytecodeAddress());
        code_move->set_to_instruction_start_address(
            to->GetFirstBytecodeAddress());
        code_move->set_instruction_size_bytes(to->length());
        if (ctx.log_instructions()) {
          code_move->set_to_bytecode(
              reinterpret_cast<const uint8_t*>(to->GetFirstBytecodeAddress()),
              to->length());
        }
      });
}
References v8::internal::CodeTraceContext::InternIsolate(), isolate_, v8::internal::CodeTraceContext::log_instructions(), v8::internal::anonymous_namespace{perfetto-logger.cc}::NewCodeTraceContext(), and v8::internal::CodeTraceContext::set_code_move().
CallbackEvent()
void v8::internal::PerfettoLogger::CallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 384 of file perfetto-logger.cc.
                                                        {}
CodeCreateEvent() [1/4]
void v8::internal::PerfettoLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char * name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 256 of file perfetto-logger.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  if (!IsCode(*abstract_code)) return;
  Tagged<Code> code = abstract_code->GetCode();
  V8InternalCode::Type type = V8InternalCode::TYPE_UNKNOWN;
  switch (code->kind()) {
    case CodeKind::REGEXP:
      RegExpCodeCreateEvent(abstract_code, DirectHandle<String>(), {});
      break;
    case CodeKind::BYTECODE_HANDLER:
      type = V8InternalCode::TYPE_BYTECODE_HANDLER;
      break;
    case CodeKind::FOR_TESTING:
      type = V8InternalCode::TYPE_FOR_TESTING;
      break;
    case CodeKind::BUILTIN:
      type = V8InternalCode::TYPE_BUILTIN;
      break;
    case CodeKind::WASM_FUNCTION:
      type = V8InternalCode::TYPE_WASM_FUNCTION;
      break;
    case CodeKind::WASM_TO_CAPI_FUNCTION:
      type = V8InternalCode::TYPE_WASM_TO_CAPI_FUNCTION;
      break;
    case CodeKind::WASM_TO_JS_FUNCTION:
      type = V8InternalCode::TYPE_WASM_TO_JS_FUNCTION;
      break;
    case CodeKind::JS_TO_WASM_FUNCTION:
      type = V8InternalCode::TYPE_JS_TO_WASM_FUNCTION;
      break;
    case CodeKind::C_WASM_ENTRY:
      type = V8InternalCode::TYPE_C_WASM_ENTRY;
      break;
    case CodeKind::INTERPRETED_FUNCTION:
    case CodeKind::BASELINE:
    case CodeKind::MAGLEV:
    case CodeKind::TURBOFAN_JS:
      UNREACHABLE();
  }
  CodeDataSource::Trace(
      [&](v8::internal::CodeDataSource::TraceContext trace_context) {
        CodeTraceContext ctx = NewCodeTraceContext(trace_context);
        auto* code_proto = ctx.set_v8_internal_code();
        code_proto->set_v8_isolate_iid(ctx.InternIsolate(isolate_));
        code_proto->set_name(name);
        code_proto->set_type(type);
        if (code->is_builtin()) {
          code_proto->set_builtin_id(static_cast<int32_t>(code->builtin_id()));
        }
        code_proto->set_instruction_start(code->instruction_start());
        code_proto->set_instruction_size_bytes(code->instruction_size());
        if (ctx.log_instructions()) {
          code_proto->set_machine_code(
              reinterpret_cast<const uint8_t*>(code->instruction_start()),
              code->instruction_size());
        }
      });
}
References BUILTIN, code, v8::internal::CodeTraceContext::InternIsolate(), isolate_, v8::internal::CodeTraceContext::log_instructions(), v8::internal::name, v8::internal::anonymous_namespace{perfetto-logger.cc}::NewCodeTraceContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RegExpCodeCreateEvent(), v8::internal::CodeTraceContext::set_v8_internal_code(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by CodeCreateEvent().
CodeCreateEvent() [2/4]
void v8::internal::PerfettoLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 321 of file perfetto-logger.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  if (!IsString(*name)) return;
  CodeCreateEvent(tag, abstract_code, Cast<String>(*name)->ToCString().get());
}
References CodeCreateEvent(), v8::internal::name, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
CodeCreateEvent() [3/4]
void v8::internal::PerfettoLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 329 of file perfetto-logger.cc.
                                                                     {
  CodeCreateEvent(tag, abstract_code, info, script_name, 0, 0);
}
References CodeCreateEvent().
CodeCreateEvent() [4/4]
void v8::internal::PerfettoLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name, int line, int column) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 336 of file perfetto-logger.cc.
                                                 {
  DisallowGarbageCollection no_gc;
  DCHECK(IsScript(info->script()));
  CodeDataSource::Trace(
      [&](v8::internal::CodeDataSource::TraceContext trace_context) {
        CodeTraceContext ctx = NewCodeTraceContext(trace_context);
        auto* code_proto = ctx.set_v8_js_code();
        code_proto->set_v8_isolate_iid(ctx.InternIsolate(isolate_));
        code_proto->set_v8_js_function_iid(ctx.InternJsFunction(
            isolate_, info,
            ctx.InternJsScript(isolate_, Cast<Script>(info->script())), line,
            column));
        WriteJsCode(&isolate_, ctx, *abstract_code, *code_proto);
      });
}
References v8::internal::DCHECK(), v8::internal::CodeTraceContext::InternIsolate(), v8::internal::CodeTraceContext::InternJsFunction(), v8::internal::CodeTraceContext::InternJsScript(), isolate_, v8::internal::anonymous_namespace{perfetto-logger.cc}::NewCodeTraceContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::CodeTraceContext::set_v8_js_code(), and v8::internal::anonymous_namespace{perfetto-logger.cc}::WriteJsCode().
CodeDeoptEvent()
void v8::internal::PerfettoLogger::CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 462 of file perfetto-logger.cc.
                                                        {}
CodeDependencyChangeEvent()
void v8::internal::PerfettoLogger::CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > shared, const char * reason) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 465 of file perfetto-logger.cc.
                        {}
CodeDisableOptEvent()
void v8::internal::PerfettoLogger::CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 460 of file perfetto-logger.cc.
                                                                              {}
CodeMoveEvent()
void v8::internal::PerfettoLogger::CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 418 of file perfetto-logger.cc.
                                                                 {
  CodeDataSource::Trace(
      [&](v8::internal::CodeDataSource::TraceContext trace_context) {
        CodeTraceContext ctx = NewCodeTraceContext(trace_context);
        auto* code_move = ctx.set_code_move();
        code_move->set_isolate_iid(ctx.InternIsolate(isolate_));
        code_move->set_from_instruction_start_address(
            from->instruction_start());
        code_move->set_to_instruction_start_address(to->instruction_start());
        Tagged<Code> code = to->code(AcquireLoadTag());
        code_move->set_instruction_size_bytes(code->instruction_size());
        if (ctx.log_instructions()) {
          code_move->set_to_machine_code(
              reinterpret_cast<const uint8_t*>(code->instruction_start()),
              code->instruction_size());
        }
      });
}
References code, v8::internal::CodeTraceContext::InternIsolate(), isolate_, v8::internal::CodeTraceContext::log_instructions(), v8::internal::anonymous_namespace{perfetto-logger.cc}::NewCodeTraceContext(), and v8::internal::CodeTraceContext::set_code_move().
CodeMovingGCEvent()
void v8::internal::PerfettoLogger::CodeMovingGCEvent () [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 459 of file perfetto-logger.cc.
{}
GetterCallbackEvent()
void v8::internal::PerfettoLogger::GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 386 of file perfetto-logger.cc.
                                                              {}
is_listening_to_code_events()
bool v8::internal::PerfettoLogger::is_listening_to_code_events () [override], [virtual]
Reimplemented from v8::internal::LogEventListener.
Definition at line 470 of file perfetto-logger.cc.
{ return true; }
LogExistingCode()
void v8::internal::PerfettoLogger::LogExistingCode ()
Definition at line 245 of file perfetto-logger.cc.
                                     {
  HandleScope scope(&isolate_);
  ExistingCodeLogger logger(&isolate_, this);
  logger.LogBuiltins();
  logger.LogCodeObjects();
  logger.LogCompiledFunctions();
}
References isolate_, v8::internal::ExistingCodeLogger::LogBuiltins(), v8::internal::ExistingCodeLogger::LogCodeObjects(), and v8::internal::ExistingCodeLogger::LogCompiledFunctions().
Referenced by v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::LogExistingCodeForAllIsolates().
NativeContextMoveEvent()
void v8::internal::PerfettoLogger::NativeContextMoveEvent (Address from, Address to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 458 of file perfetto-logger.cc.
{}
OnCodeDataSourceStart()
void v8::internal::PerfettoLogger::OnCodeDataSourceStart () [static]
Definition at line 236 of file perfetto-logger.cc.
                                           {
  IsolateRegistry::GetInstance().OnCodeDataSourceStart();
}
References wasm::anonymous_namespace{c-api.cc}::GetInstance().
Referenced by v8::internal::CodeDataSource::OnStart().
OnCodeDataSourceStop()
void v8::internal::PerfettoLogger::OnCodeDataSourceStop () [static]
Definition at line 241 of file perfetto-logger.cc.
                                          {
  IsolateRegistry::GetInstance().OnCodeDataSourceStop();
}
References wasm::anonymous_namespace{c-api.cc}::GetInstance().
Referenced by v8::internal::CodeDataSource::OnStop().
RegExpCodeCreateEvent()
void v8::internal::PerfettoLogger::RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 390 of file perfetto-logger.cc.
                       {
  DisallowGarbageCollection no_gc;
  DCHECK(IsCode(*abstract_code));
  Tagged<Code> code = abstract_code->GetCode();
  DCHECK(code->kind() == CodeKind::REGEXP);
  CodeDataSource::Trace(
      [&](v8::internal::CodeDataSource::TraceContext trace_context) {
        CodeTraceContext ctx = NewCodeTraceContext(trace_context);
        auto* code_proto = ctx.set_v8_reg_exp_code();
        code_proto->set_v8_isolate_iid(ctx.InternIsolate(isolate_));
        if (!pattern.is_null()) {
          PerfettoV8String(*pattern).WriteToProto(*code_proto->set_pattern());
        }
        code_proto->set_instruction_start(code->instruction_start());
        code_proto->set_instruction_size_bytes(code->instruction_size());
        if (ctx.log_instructions()) {
          code_proto->set_machine_code(
              reinterpret_cast<const uint8_t*>(code->instruction_start()),
              code->instruction_size());
        }
      });
}
References code, v8::internal::DCHECK(), v8::internal::CodeTraceContext::InternIsolate(), v8::internal::DirectHandle< T >::is_null(), isolate_, v8::internal::CodeTraceContext::log_instructions(), v8::internal::anonymous_namespace{perfetto-logger.cc}::NewCodeTraceContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::CodeTraceContext::set_v8_reg_exp_code(), and v8::internal::PerfettoV8String::WriteToProto().
Referenced by CodeCreateEvent().
RegisterIsolate()
void v8::internal::PerfettoLogger::RegisterIsolate (Isolate * isolate) [static]
Definition at line 220 of file perfetto-logger.cc.
                                                     {
  IsolateRegistry::GetInstance().Register(isolate);
  // TODO(carlscab): Actually if both perfetto and file logging are active the
  // builtins will be logged twice to the file (EmitCodeCreateEvents is called
  // somewhere in the isolate setup code). Probably not very likely to happen
  // but we should find a better way.
  CodeDataSource::CallIfEnabled(
      [isolate](uint32_t) { Builtins::EmitCodeCreateEvents(isolate); });
}
References v8::internal::Builtins::EmitCodeCreateEvents(), and wasm::anonymous_namespace{c-api.cc}::GetInstance().
Referenced by v8::internal::Isolate::Init().
SetterCallbackEvent()
void v8::internal::PerfettoLogger::SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 388 of file perfetto-logger.cc.
                                                              {}
SharedFunctionInfoMoveEvent()
void v8::internal::PerfettoLogger::SharedFunctionInfoMoveEvent (Address from, Address to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 457 of file perfetto-logger.cc.
{}
UnregisterIsolate()
void v8::internal::PerfettoLogger::UnregisterIsolate (Isolate * isolate) [static]
Definition at line 231 of file perfetto-logger.cc.
                                                       {
  IsolateRegistry::GetInstance().Unregister(isolate);
}
References wasm::anonymous_namespace{c-api.cc}::GetInstance().
Referenced by v8::internal::Isolate::Deinit().
WeakCodeClearEvent()
void v8::internal::PerfettoLogger::WeakCodeClearEvent () [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 468 of file perfetto-logger.cc.
{}
Member Data Documentation
isolate_
Isolate& v8::internal::PerfettoLogger::isolate_ [private]
Definition at line 71 of file perfetto-logger.h.
Referenced by BytecodeMoveEvent(), CodeCreateEvent(), CodeMoveEvent(), LogExistingCode(), and RegExpCodeCreateEvent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/tracing/perfetto-logger.h
/mnt/V8SourceCode/src/tracing/perfetto-logger.cc