v8::internal::RegExpCompiler Class Reference
#include <regexp-compiler.h>
Classes
struct CompilationResult
Public Member Functions
RegExpCompiler (Isolate *isolate, Zone *zone, int capture_count, RegExpFlags flags, bool is_one_byte)
int AllocateRegister ()
int UnicodeLookaroundStackRegister ()
int UnicodeLookaroundPositionRegister ()
CompilationResult Assemble (Isolate *isolate, RegExpMacroAssembler *assembler, RegExpNode *start, int capture_count, DirectHandle< String > pattern)
RegExpNode * PreprocessRegExp (RegExpCompileData *data, bool is_one_byte)
RegExpNode * OptionallyStepBackToLeadSurrogate (RegExpNode *on_success)
void AddWork (RegExpNode *node)
RegExpMacroAssembler * macro_assembler ()
EndNode * accept ()
int recursion_depth ()
void IncrementRecursionDepth ()
void DecrementRecursionDepth ()
RegExpFlags flags () const
void set_flags (RegExpFlags flags)
void SetRegExpTooBig ()
bool one_byte ()
bool optimize ()
void set_optimize (bool value)
bool limiting_recursion ()
void set_limiting_recursion (bool value)
bool read_backward ()
void set_read_backward (bool value)
FrequencyCollator * frequency_collator ()
int current_expansion_factor ()
void set_current_expansion_factor (int value)
void ToNodeMaybeCheckForStackOverflow ()
void ToNodeCheckForStackOverflow ()
Isolate * isolate () const
Zone * zone () const
Static Public Attributes
static const int kImplementationOffset = 0
static const int kNumberOfRegistersOffset = 0
static const int kCodeOffset = 1
static constexpr int kMaxRecursion = 100
static const int kNoRegister = -1
Private Attributes
EndNode * accept_
int next_register_
int unicode_lookaround_stack_register_
int unicode_lookaround_position_register_
ZoneVector< RegExpNode * > * work_list_
int recursion_depth_
RegExpFlags flags_
RegExpMacroAssembler * macro_assembler_
bool one_byte_
bool reg_exp_too_big_
bool limiting_recursion_
int to_node_overflow_check_ticks_ = 0
bool optimize_
bool read_backward_
int current_expansion_factor_
FrequencyCollator frequency_collator_
Isolate * isolate_
Zone * zone_
Detailed Description
Definition at line 463 of file regexp-compiler.h.
Constructor & Destructor Documentation
RegExpCompiler()
v8::internal::RegExpCompiler::RegExpCompiler (Isolate * isolate, Zone * zone, int capture_count, RegExpFlags flags, bool is_one_byte)
Definition at line 242 of file regexp-compiler.cc.
    : next_register_(JSRegExp::RegistersForCaptureCount(capture_count)),
      unicode_lookaround_stack_register_(kNoRegister),
      unicode_lookaround_position_register_(kNoRegister),
      work_list_(nullptr),
      recursion_depth_(0),
      flags_(flags),
      one_byte_(one_byte),
      reg_exp_too_big_(false),
      limiting_recursion_(false),
      optimize_(v8_flags.regexp_optimization),
      read_backward_(false),
      current_expansion_factor_(1),
      frequency_collator_(),
      isolate_(isolate),
      zone_(zone) {
  accept_ = zone->New<EndNode>(EndNode::ACCEPT, zone);
  DCHECK_GE(RegExpMacroAssembler::kMaxRegister, next_register_ - 1);
}
References v8::internal::EndNode::ACCEPT, accept_, DCHECK_GE, v8::internal::RegExpMacroAssembler::kMaxRegister, v8::internal::Zone::New(), next_register_, and zone().
Member Function Documentation
accept()
EndNode* v8::internal::RegExpCompiler::accept () [inline]
Definition at line 536 of file regexp-compiler.h.
{ return accept_; }
References accept_.
Referenced by PreprocessRegExp().
AddWork()
void v8::internal::RegExpCompiler::AddWork (RegExpNode * node) [inline]
Definition at line 524 of file regexp-compiler.h.
                                        {
    if (!node->on_work_list() && !node->label()->is_bound()) {
      node->set_on_work_list(true);
      work_list_->push_back(node);
    }
  }
References v8::internal::Label::is_bound(), v8::internal::RegExpNode::label(), v8::internal::RegExpNode::on_work_list(), v8::internal::RegExpNode::set_on_work_list(), and work_list_.
Referenced by v8::internal::Trace::Flush(), and v8::internal::RegExpNode::LimitVersions().
AllocateRegister()
int v8::internal::RegExpCompiler::AllocateRegister () [inline]
Definition at line 468 of file regexp-compiler.h.
                         {
    if (next_register_ >= RegExpMacroAssembler::kMaxRegister) {
      reg_exp_too_big_ = true;
      return next_register_;
    }
    return next_register_++;
  }
References v8::internal::RegExpMacroAssembler::kMaxRegister, next_register_, and reg_exp_too_big_.
Referenced by UnicodeLookaroundPositionRegister(), and UnicodeLookaroundStackRegister().
Assemble()
RegExpCompiler::CompilationResult v8::internal::RegExpCompiler::Assemble (Isolate * isolate, RegExpMacroAssembler * assembler, RegExpNode * start, int capture_count, DirectHandle< String > pattern)
Definition at line 263 of file regexp-compiler.cc.
                                                     {
  macro_assembler_ = macro_assembler;
  ZoneVector<RegExpNode*> work_list(zone());
  work_list_ = &work_list;
  Label fail;
  macro_assembler_->PushBacktrack(&fail);
  Trace new_trace;
  start->Emit(this, &new_trace);
  macro_assembler_->BindJumpTarget(&fail);
  macro_assembler_->Fail();
  while (!work_list.empty()) {
    RegExpNode* node = work_list.back();
    work_list.pop_back();
    node->set_on_work_list(false);
    if (!node->label()->is_bound()) node->Emit(this, &new_trace);
  }
  if (reg_exp_too_big_) {
    if (v8_flags.correctness_fuzzer_suppressions) {
      FATAL("Aborting on excess zone allocation");
    }
    macro_assembler_->AbortedCodeGeneration();
    return CompilationResult::RegExpTooBig();
  }
  DirectHandle<HeapObject> code = macro_assembler_->GetCode(pattern, flags_);
  isolate->IncreaseTotalRegexpCodeGenerated(code);
  work_list_ = nullptr;
  return {code, next_register_};
}
References v8::internal::RegExpMacroAssembler::AbortedCodeGeneration(), v8::internal::ZoneVector< T >::back(), v8::internal::RegExpMacroAssembler::BindJumpTarget(), code, v8::internal::RegExpNode::Emit(), v8::internal::ZoneVector< T >::empty(), v8::internal::RegExpMacroAssembler::Fail(), FATAL, flags_, v8::internal::RegExpMacroAssembler::GetCode(), v8::internal::Isolate::IncreaseTotalRegexpCodeGenerated(), v8::internal::Label::is_bound(), isolate(), v8::internal::RegExpNode::label(), macro_assembler(), macro_assembler_, next_register_, v8::internal::ZoneVector< T >::pop_back(), v8::internal::RegExpMacroAssembler::PushBacktrack(), reg_exp_too_big_, v8::internal::RegExpCompiler::CompilationResult::RegExpTooBig(), v8::internal::RegExpNode::set_on_work_list(), v8::internal::v8_flags, work_list_, and zone().
Referenced by v8::internal::RegExpImpl::Compile().
current_expansion_factor()
int v8::internal::RegExpCompiler::current_expansion_factor () [inline]
Definition at line 566 of file regexp-compiler.h.
{ return current_expansion_factor_; }
References current_expansion_factor_.
DecrementRecursionDepth()
void v8::internal::RegExpCompiler::DecrementRecursionDepth () [inline]
Definition at line 548 of file regexp-compiler.h.
{ recursion_depth_--; }
References recursion_depth_.
flags()
RegExpFlags v8::internal::RegExpCompiler::flags () const [inline]
Definition at line 550 of file regexp-compiler.h.
{ return flags_; }
References flags_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::TextNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::ActionNode::FillInBMInfo(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::ActionNode::GetQuickCheckDetails(), PreprocessRegExp(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), set_flags(), v8::internal::RegExpDisjunction::SortConsecutiveAtoms(), and v8::internal::TextNode::TextEmitPass().
frequency_collator()
FrequencyCollator* v8::internal::RegExpCompiler::frequency_collator () [inline]
Definition at line 564 of file regexp-compiler.h.
{ return &frequency_collator_; }
References frequency_collator_.
Referenced by v8::internal::RegExpImpl::Compile(), and v8::internal::BoyerMooreLookahead::FindBestInterval().
IncrementRecursionDepth()
void v8::internal::RegExpCompiler::IncrementRecursionDepth () [inline]
Definition at line 547 of file regexp-compiler.h.
{ recursion_depth_++; }
References recursion_depth_.
Referenced by v8::internal::RecursionCheck::RecursionCheck().
isolate()
Isolate* v8::internal::RegExpCompiler::isolate () const [inline]
Definition at line 583 of file regexp-compiler.h.
{ return isolate_; }
References isolate_.
Referenced by Assemble(), v8::internal::TextNode::FilterOneByte(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::RegExpDisjunction::SortConsecutiveAtoms(), and ToNodeCheckForStackOverflow().
limiting_recursion()
bool v8::internal::RegExpCompiler::limiting_recursion () [inline]
Definition at line 558 of file regexp-compiler.h.
{ return limiting_recursion_; }
References limiting_recursion_.
Referenced by v8::internal::RegExpNode::KeepRecursing(), and v8::internal::RegExpNode::LimitVersions().
macro_assembler()
RegExpMacroAssembler* v8::internal::RegExpCompiler::macro_assembler () [inline]
Definition at line 535 of file regexp-compiler.h.
{ return macro_assembler_; }
References macro_assembler_.
Referenced by Assemble(), v8::internal::AssertionNode::BacktrackIfPrevious(), v8::internal::ChoiceNode::CalculatePreloadCharacters(), v8::internal::ActionNode::Emit(), v8::internal::AssertionNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::EndNode::Emit(), v8::internal::NegativeSubmatchSuccess::Emit(), v8::internal::LoopChoiceNode::Emit(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomNonLetter(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::ChoiceNode::EmitFixedLengthLoop(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::RegExpNode::EmitQuickCheck(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitSimpleCharacter(), v8::internal::Trace::Flush(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::RegExpNode::LimitVersions(), and v8::internal::TextNode::TextEmitPass().
one_byte()
bool v8::internal::RegExpCompiler::one_byte () [inline]
Definition at line 555 of file regexp-compiler.h.
{ return one_byte_; }
References one_byte_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::Trace::AdvanceCurrentPositionInTrace(), v8::internal::ChoiceNode::CalculatePreloadCharacters(), v8::internal::TextNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomNonLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::RegExpNode::EmitQuickCheck(), v8::internal::BoyerMooreLookahead::FindBestInterval(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), and v8::internal::TextNode::TextEmitPass().
optimize()
bool v8::internal::RegExpCompiler::optimize () [inline]
Definition at line 556 of file regexp-compiler.h.
{ return optimize_; }
References optimize_.
Referenced by v8::internal::RegExpImpl::Compile(), and v8::internal::RegExpNode::LimitVersions().
OptionallyStepBackToLeadSurrogate()
RegExpNode * v8::internal::RegExpCompiler::OptionallyStepBackToLeadSurrogate (RegExpNode * on_success)
Definition at line 4030 of file regexp-compiler.cc.
                            {
  DCHECK(!read_backward());
  ZoneList<CharacterRange>* lead_surrogates = CharacterRange::List(
      zone(), CharacterRange::Range(kLeadSurrogateStart, kLeadSurrogateEnd));
  ZoneList<CharacterRange>* trail_surrogates = CharacterRange::List(
      zone(), CharacterRange::Range(kTrailSurrogateStart, kTrailSurrogateEnd));
  ChoiceNode* optional_step_back = zone()->New<ChoiceNode>(2, zone());
  int stack_register = UnicodeLookaroundStackRegister();
  int position_register = UnicodeLookaroundPositionRegister();
  RegExpNode* step_back = TextNode::CreateForCharacterRanges(
      zone(), lead_surrogates, true, on_success);
  RegExpLookaround::Builder builder(true, step_back, stack_register,
                                    position_register);
  RegExpNode* match_trail = TextNode::CreateForCharacterRanges(
      zone(), trail_surrogates, false, builder.on_match_success());
  optional_step_back->AddAlternative(
      GuardedAlternative(builder.ForMatch(match_trail)));
  optional_step_back->AddAlternative(GuardedAlternative(on_success));
  return optional_step_back;
}
References v8::internal::ChoiceNode::AddAlternative(), v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::DCHECK(), v8::internal::RegExpLookaround::Builder::ForMatch(), v8::internal::kLeadSurrogateEnd, v8::internal::kLeadSurrogateStart, v8::internal::kTrailSurrogateEnd, v8::internal::kTrailSurrogateStart, v8::internal::CharacterRange::List(), v8::internal::Zone::New(), v8::internal::RegExpLookaround::Builder::on_match_success(), v8::internal::CharacterRange::Range(), read_backward(), UnicodeLookaroundPositionRegister(), UnicodeLookaroundStackRegister(), and zone().
Referenced by PreprocessRegExp().
PreprocessRegExp()
RegExpNode * v8::internal::RegExpCompiler::PreprocessRegExp (RegExpCompileData * data, bool is_one_byte)
Definition at line 4056 of file regexp-compiler.cc.
                                                               {
  // Wrap the body of the regexp in capture #0.
  RegExpNode* captured_body =
      RegExpCapture::ToNode(data->tree, 0, this, accept());
  RegExpNode* node = captured_body;
  if (!data->tree->IsAnchoredAtStart() && !IsSticky(flags())) {
    // Add a .*? at the beginning, outside the body capture, unless
    // this expression is anchored at the beginning or sticky.
    RegExpNode* loop_node = RegExpQuantifier::ToNode(
        0, RegExpTree::kInfinity, false,
        zone()->New<RegExpClassRanges>(StandardCharacterSet::kEverything), this,
        captured_body, data->contains_anchor);
    if (data->contains_anchor) {
      // Unroll loop once, to take care of the case that might start
      // at the start of input.
      ChoiceNode* first_step_node = zone()->New<ChoiceNode>(2, zone());
      first_step_node->AddAlternative(GuardedAlternative(captured_body));
      first_step_node->AddAlternative(GuardedAlternative(zone()->New<TextNode>(
          zone()->New<RegExpClassRanges>(StandardCharacterSet::kEverything),
          false, loop_node)));
      node = first_step_node;
    } else {
      node = loop_node;
    }
  }
  if (is_one_byte) {
    node = node->FilterOneByte(RegExpCompiler::kMaxRecursion, this);
    // Do it again to propagate the new nodes to places where they were not
    // put because they had not been calculated yet.
    if (node != nullptr) {
      node = node->FilterOneByte(RegExpCompiler::kMaxRecursion, this);
    }
  } else if (IsEitherUnicode(flags()) &&
             (IsGlobal(flags()) || IsSticky(flags()))) {
    node = OptionallyStepBackToLeadSurrogate(node);
  }
  if (node == nullptr) node = zone()->New<EndNode>(EndNode::BACKTRACK, zone());
  // We can run out of registers during preprocessing. Indicate an error in case
  // we do.
  if (reg_exp_too_big_) {
    data->error = RegExpError::kTooLarge;
  }
  return node;
}
References accept(), v8::internal::ChoiceNode::AddAlternative(), v8::internal::EndNode::BACKTRACK, v8::internal::RegExpCompileData::contains_anchor, v8::internal::RegExpCompileData::error, v8::internal::RegExpNode::FilterOneByte(), flags(), v8::internal::RegExpTree::IsAnchoredAtStart(), v8::internal::IsEitherUnicode(), v8::internal::kEverything, v8::internal::RegExpTree::kInfinity, kMaxRecursion, v8::internal::Zone::New(), OptionallyStepBackToLeadSurrogate(), reg_exp_too_big_, v8::internal::RegExpQuantifier::ToNode(), v8::internal::RegExpCapture::ToNode(), v8::internal::RegExpCompileData::tree, and zone().
Referenced by v8::internal::RegExpImpl::Compile().
read_backward()
bool v8::internal::RegExpCompiler::read_backward () [inline]
Definition at line 562 of file regexp-compiler.h.
{ return read_backward_; }
References read_backward_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddBmpCharacters(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneLeadSurrogates(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneTrailSurrogates(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), OptionallyStepBackToLeadSurrogate(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::UnanchoredAdvance().
recursion_depth()
int v8::internal::RegExpCompiler::recursion_depth () [inline]
Definition at line 546 of file regexp-compiler.h.
{ return recursion_depth_; }
References recursion_depth_.
Referenced by v8::internal::RegExpNode::KeepRecursing().
set_current_expansion_factor()
void v8::internal::RegExpCompiler::set_current_expansion_factor (int value) [inline]
Definition at line 567 of file regexp-compiler.h.
                                               {
    current_expansion_factor_ = value;
  }
References current_expansion_factor_, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::RegExpExpansionLimiter::RegExpExpansionLimiter().
set_flags()
void v8::internal::RegExpCompiler::set_flags (RegExpFlags flags) [inline]
Definition at line 551 of file regexp-compiler.h.
{ flags_ = flags; }
References flags(), and flags_.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::ActionNode::FillInBMInfo(), v8::internal::ActionNode::GetQuickCheckDetails(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ModifiersScope::ModifiersScope().
set_limiting_recursion()
void v8::internal::RegExpCompiler::set_limiting_recursion (bool value) [inline]
Definition at line 559 of file regexp-compiler.h.
                                                 {
    limiting_recursion_ = value;
  }
References limiting_recursion_, and v8::internal::value.
Referenced by v8::internal::RegExpNode::LimitVersions().
set_optimize()
void v8::internal::RegExpCompiler::set_optimize (bool value) [inline]
Definition at line 557 of file regexp-compiler.h.
{ optimize_ = value; }
References optimize_, and v8::internal::value.
Referenced by v8::internal::RegExpImpl::Compile().
set_read_backward()
void v8::internal::RegExpCompiler::set_read_backward (bool value) [inline]
Definition at line 563 of file regexp-compiler.h.
{ read_backward_ = value; }
References read_backward_, and v8::internal::value.
SetRegExpTooBig()
void v8::internal::RegExpCompiler::SetRegExpTooBig () [inline]
Definition at line 553 of file regexp-compiler.h.
{ reg_exp_too_big_ = true; }
References reg_exp_too_big_.
Referenced by v8::internal::Trace::AdvanceCurrentPositionInTrace(), and v8::internal::TextNode::Emit().
ToNodeCheckForStackOverflow()
void v8::internal::RegExpCompiler::ToNodeCheckForStackOverflow ()
Definition at line 4104 of file regexp-compiler.cc.
                                                 {
  if (StackLimitCheck{isolate()}.HasOverflowed()) {
    V8::FatalProcessOutOfMemory(isolate(), "RegExpCompiler");
  }
}
References v8::internal::V8::FatalProcessOutOfMemory(), and isolate().
Referenced by ToNodeMaybeCheckForStackOverflow().
ToNodeMaybeCheckForStackOverflow()
void v8::internal::RegExpCompiler::ToNodeMaybeCheckForStackOverflow () [inline]
Definition at line 576 of file regexp-compiler.h.
                                          {
    if ((to_node_overflow_check_ticks_++ % 16 == 0)) {
      ToNodeCheckForStackOverflow();
    }
  }
References to_node_overflow_check_ticks_, and ToNodeCheckForStackOverflow().
UnicodeLookaroundPositionRegister()
int v8::internal::RegExpCompiler::UnicodeLookaroundPositionRegister () [inline]
Definition at line 485 of file regexp-compiler.h.
                                          {
    if (unicode_lookaround_position_register_ == kNoRegister) {
      unicode_lookaround_position_register_ = AllocateRegister();
    }
    return unicode_lookaround_position_register_;
  }
References AllocateRegister(), kNoRegister, and unicode_lookaround_position_register_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MatchAndNegativeLookaroundInReadDirection(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::NegativeLookaroundAgainstReadDirectionAndMatch(), and OptionallyStepBackToLeadSurrogate().
UnicodeLookaroundStackRegister()
int v8::internal::RegExpCompiler::UnicodeLookaroundStackRegister () [inline]
Definition at line 478 of file regexp-compiler.h.
                                       {
    if (unicode_lookaround_stack_register_ == kNoRegister) {
      unicode_lookaround_stack_register_ = AllocateRegister();
    }
    return unicode_lookaround_stack_register_;
  }
References AllocateRegister(), kNoRegister, and unicode_lookaround_stack_register_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MatchAndNegativeLookaroundInReadDirection(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::NegativeLookaroundAgainstReadDirectionAndMatch(), and OptionallyStepBackToLeadSurrogate().
zone()
Zone* v8::internal::RegExpCompiler::zone () const [inline]
Definition at line 584 of file regexp-compiler.h.
{ return zone_; }
References zone_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddBmpCharacters(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneLeadSurrogates(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneTrailSurrogates(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), Assemble(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::Trace::Flush(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MatchAndNegativeLookaroundInReadDirection(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::NegativeLookaroundAgainstReadDirectionAndMatch(), OptionallyStepBackToLeadSurrogate(), PreprocessRegExp(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), RegExpCompiler(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::UnanchoredAdvance().
Member Data Documentation
accept_
EndNode* v8::internal::RegExpCompiler::accept_ [private]
Definition at line 589 of file regexp-compiler.h.
Referenced by accept(), and RegExpCompiler().
current_expansion_factor_
int v8::internal::RegExpCompiler::current_expansion_factor_ [private]
Definition at line 603 of file regexp-compiler.h.
Referenced by current_expansion_factor(), and set_current_expansion_factor().
flags_
RegExpFlags v8::internal::RegExpCompiler::flags_ [private]
Definition at line 595 of file regexp-compiler.h.
Referenced by Assemble(), flags(), and set_flags().
frequency_collator_
FrequencyCollator v8::internal::RegExpCompiler::frequency_collator_ [private]
Definition at line 604 of file regexp-compiler.h.
Referenced by frequency_collator().
isolate_
Isolate* v8::internal::RegExpCompiler::isolate_ [private]
Definition at line 605 of file regexp-compiler.h.
Referenced by isolate().
kCodeOffset
const int v8::internal::RegExpCompiler::kCodeOffset = 1 [static]
Definition at line 533 of file regexp-compiler.h.
kImplementationOffset
const int v8::internal::RegExpCompiler::kImplementationOffset = 0 [static]
Definition at line 531 of file regexp-compiler.h.
kMaxRecursion
constexpr int v8::internal::RegExpCompiler::kMaxRecursion = 100 [static], [constexpr]
Definition at line 544 of file regexp-compiler.h.
Referenced by v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative(), v8::internal::RegExpNode::KeepRecursing(), and PreprocessRegExp().
kNoRegister
const int v8::internal::RegExpCompiler::kNoRegister = -1 [static]
Definition at line 586 of file regexp-compiler.h.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::Trace::FindAffectedRegisters(), UnicodeLookaroundPositionRegister(), and UnicodeLookaroundStackRegister().
kNumberOfRegistersOffset
const int v8::internal::RegExpCompiler::kNumberOfRegistersOffset = 0 [static]
Definition at line 532 of file regexp-compiler.h.
limiting_recursion_
bool v8::internal::RegExpCompiler::limiting_recursion_ [private]
Definition at line 599 of file regexp-compiler.h.
Referenced by limiting_recursion(), and set_limiting_recursion().
macro_assembler_
RegExpMacroAssembler* v8::internal::RegExpCompiler::macro_assembler_ [private]
Definition at line 596 of file regexp-compiler.h.
Referenced by Assemble(), and macro_assembler().
next_register_
int v8::internal::RegExpCompiler::next_register_ [private]
Definition at line 590 of file regexp-compiler.h.
Referenced by AllocateRegister(), Assemble(), and RegExpCompiler().
one_byte_
bool v8::internal::RegExpCompiler::one_byte_ [private]
Definition at line 597 of file regexp-compiler.h.
Referenced by one_byte().
optimize_
bool v8::internal::RegExpCompiler::optimize_ [private]
Definition at line 601 of file regexp-compiler.h.
Referenced by optimize(), and set_optimize().
read_backward_
bool v8::internal::RegExpCompiler::read_backward_ [private]
Definition at line 602 of file regexp-compiler.h.
Referenced by read_backward(), and set_read_backward().
recursion_depth_
int v8::internal::RegExpCompiler::recursion_depth_ [private]
Definition at line 594 of file regexp-compiler.h.
Referenced by DecrementRecursionDepth(), IncrementRecursionDepth(), and recursion_depth().
reg_exp_too_big_
bool v8::internal::RegExpCompiler::reg_exp_too_big_ [private]
Definition at line 598 of file regexp-compiler.h.
Referenced by AllocateRegister(), Assemble(), PreprocessRegExp(), and SetRegExpTooBig().
to_node_overflow_check_ticks_
int v8::internal::RegExpCompiler::to_node_overflow_check_ticks_ = 0 [private]
Definition at line 600 of file regexp-compiler.h.
Referenced by ToNodeMaybeCheckForStackOverflow().
unicode_lookaround_position_register_
int v8::internal::RegExpCompiler::unicode_lookaround_position_register_ [private]
Definition at line 592 of file regexp-compiler.h.
Referenced by UnicodeLookaroundPositionRegister().
unicode_lookaround_stack_register_
int v8::internal::RegExpCompiler::unicode_lookaround_stack_register_ [private]
Definition at line 591 of file regexp-compiler.h.
Referenced by UnicodeLookaroundStackRegister().
work_list_
ZoneVector<RegExpNode*>* v8::internal::RegExpCompiler::work_list_ [private]
Definition at line 593 of file regexp-compiler.h.
Referenced by AddWork(), and Assemble().
zone_
Zone* v8::internal::RegExpCompiler::zone_ [private]
Definition at line 606 of file regexp-compiler.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc