v8::internal::compiler::ProcessedFeedback Class Reference
#include <processed-feedback.h>
Public Types
enum Kind {
kInsufficient
, kBinaryOperation
, kCall
, kCompareOperation
,
kElementAccess
, kForIn
, kGlobalAccess
, kInstanceOf
,
kTypeOf
, kLiteral
, kMegaDOMPropertyAccess
, kNamedAccess
,
kRegExpLiteral
, kTemplateObject
 }
Public Member Functions
Kind kind () const
FeedbackSlotKind slot_kind () const
bool IsInsufficient () const
BinaryOperationFeedback const & AsBinaryOperation () const
TypeOfOpFeedback const & AsTypeOf () const
CallFeedback const & AsCall () const
CompareOperationFeedback const & AsCompareOperation () const
ElementAccessFeedback const & AsElementAccess () const
ForInFeedback const & AsForIn () const
GlobalAccessFeedback const & AsGlobalAccess () const
InstanceOfFeedback const & AsInstanceOf () const
NamedAccessFeedback const & AsNamedAccess () const
MegaDOMPropertyAccessFeedback const & AsMegaDOMPropertyAccess () const
LiteralFeedback const & AsLiteral () const
RegExpLiteralFeedback const & AsRegExpLiteral () const
TemplateObjectFeedback const & AsTemplateObject () const
Protected Member Functions
ProcessedFeedback (Kind kind, FeedbackSlotKind slot_kind)
Private Attributes
Kind const kind_
FeedbackSlotKind const slot_kind_
Detailed Description
Definition at line 28 of file processed-feedback.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::ProcessedFeedback::Kind
Enumerator
kInsufficient
kBinaryOperation
kCall
kCompareOperation
kElementAccess
kForIn
kGlobalAccess
kInstanceOf
kTypeOf
kLiteral
kMegaDOMPropertyAccess
kNamedAccess
kRegExpLiteral
kTemplateObject
Definition at line 30 of file processed-feedback.h.
            {
    kInsufficient,
    kBinaryOperation,
    kCall,
    kCompareOperation,
    kElementAccess,
    kForIn,
    kGlobalAccess,
    kInstanceOf,
    kTypeOf,
    kLiteral,
    kMegaDOMPropertyAccess,
    kNamedAccess,
    kRegExpLiteral,
    kTemplateObject,
  };
Constructor & Destructor Documentation
ProcessedFeedback()
v8::internal::compiler::ProcessedFeedback::ProcessedFeedback (Kind kind, FeedbackSlotKind slot_kind) [protected]
Definition at line 180 of file js-heap-broker.cc.
    : kind_(kind), slot_kind_(slot_kind) {}
Member Function Documentation
AsBinaryOperation()
BinaryOperationFeedback const & v8::internal::compiler::ProcessedFeedback::AsBinaryOperation () const
Definition at line 957 of file js-heap-broker.cc.
                                                                          {
  CHECK_EQ(kBinaryOperation, kind());
  return *static_cast<BinaryOperationFeedback const*>(this);
}
References CHECK_EQ, kBinaryOperation, and kind().
Referenced by v8::internal::compiler::JSHeapBroker::GetFeedbackForBinaryOperation().
AsCall()
CallFeedback const & v8::internal::compiler::ProcessedFeedback::AsCall () const
Definition at line 962 of file js-heap-broker.cc.
                                                    {
  CHECK_EQ(kCall, kind());
  return *static_cast<CallFeedback const*>(this);
}
References CHECK_EQ, kCall, and kind().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::BuildConstruct(), v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFeedbackRelation(), v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFrequency(), v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::GetSpeculationMode(), v8::internal::compiler::BytecodeGraphBuilder::GetSpeculationMode(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
AsCompareOperation()
CompareOperationFeedback const & v8::internal::compiler::ProcessedFeedback::AsCompareOperation () const
Definition at line 967 of file js-heap-broker.cc.
                                                                            {
  CHECK_EQ(kCompareOperation, kind());
  return *static_cast<CompareOperationFeedback const*>(this);
}
References CHECK_EQ, kCompareOperation, and kind().
Referenced by v8::internal::compiler::JSHeapBroker::GetFeedbackForCompareOperation().
AsElementAccess()
ElementAccessFeedback const & v8::internal::compiler::ProcessedFeedback::AsElementAccess () const
Definition at line 972 of file js-heap-broker.cc.
                                                                      {
  CHECK_EQ(kElementAccess, kind());
  return *static_cast<ElementAccessFeedback const*>(this);
}
References CHECK_EQ, kElementAccess, and kind().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildGetKeyedProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), and v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::ShouldUseMegamorphicAccessBuiltin().
AsForIn()
ForInFeedback const & v8::internal::compiler::ProcessedFeedback::AsForIn () const
Definition at line 977 of file js-heap-broker.cc.
                                                      {
  CHECK_EQ(kForIn, kind());
  return *static_cast<ForInFeedback const*>(this);
}
References CHECK_EQ, kForIn, and kind().
Referenced by v8::internal::compiler::JSHeapBroker::GetFeedbackForForIn().
AsGlobalAccess()
GlobalAccessFeedback const & v8::internal::compiler::ProcessedFeedback::AsGlobalAccess () const
Definition at line 982 of file js-heap-broker.cc.
                                                                    {
  CHECK_EQ(kGlobalAccess, kind());
  return *static_cast<GlobalAccessFeedback const*>(this);
}
References CHECK_EQ, kGlobalAccess, and kind().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal().
AsInstanceOf()
InstanceOfFeedback const & v8::internal::compiler::ProcessedFeedback::AsInstanceOf () const
Definition at line 987 of file js-heap-broker.cc.
                                                                {
  CHECK_EQ(kInstanceOf, kind());
  return *static_cast<InstanceOfFeedback const*>(this);
}
References CHECK_EQ, kind(), and kInstanceOf.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOfWithFeedback().
AsLiteral()
LiteralFeedback const & v8::internal::compiler::ProcessedFeedback::AsLiteral () const
Definition at line 1003 of file js-heap-broker.cc.
                                                          {
  CHECK_EQ(kLiteral, kind());
  return *static_cast<LiteralFeedback const*>(this);
}
References CHECK_EQ, kind(), and kLiteral.
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject().
AsMegaDOMPropertyAccess()
MegaDOMPropertyAccessFeedback const & v8::internal::compiler::ProcessedFeedback::AsMegaDOMPropertyAccess () const
Definition at line 998 of file js-heap-broker.cc.
                                                 {
  CHECK_EQ(kMegaDOMPropertyAccess, kind());
  return *static_cast<MegaDOMPropertyAccessFeedback const*>(this);
}
References CHECK_EQ, kind(), and kMegaDOMPropertyAccess.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess().
AsNamedAccess()
NamedAccessFeedback const & v8::internal::compiler::ProcessedFeedback::AsNamedAccess () const
Definition at line 992 of file js-heap-broker.cc.
                                                                  {
  CHECK_EQ(kNamedAccess, kind());
  return *static_cast<NamedAccessFeedback const*>(this);
}
References CHECK_EQ, kind(), and kNamedAccess.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildGetKeyedProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::ShouldUseMegamorphicAccessBuiltin(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildLoadNamedProperty().
AsRegExpLiteral()
RegExpLiteralFeedback const & v8::internal::compiler::ProcessedFeedback::AsRegExpLiteral () const
Definition at line 1008 of file js-heap-broker.cc.
                                                                      {
  CHECK_EQ(kRegExpLiteral, kind());
  return *static_cast<RegExpLiteralFeedback const*>(this);
}
References CHECK_EQ, kind(), and kRegExpLiteral.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp().
AsTemplateObject()
TemplateObjectFeedback const & v8::internal::compiler::ProcessedFeedback::AsTemplateObject () const
Definition at line 1013 of file js-heap-broker.cc.
                                                                        {
  CHECK_EQ(kTemplateObject, kind());
  return *static_cast<TemplateObjectFeedback const*>(this);
}
References CHECK_EQ, kind(), and kTemplateObject.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSGetTemplateObject().
AsTypeOf()
TypeOfOpFeedback const & v8::internal::compiler::ProcessedFeedback::AsTypeOf () const
Definition at line 952 of file js-heap-broker.cc.
                                                          {
  CHECK_EQ(kTypeOf, kind());
  return *static_cast<TypeOfOpFeedback const*>(this);
}
References CHECK_EQ, kind(), and kTypeOf.
Referenced by v8::internal::compiler::JSHeapBroker::GetFeedbackForTypeOf().
IsInsufficient()
bool v8::internal::compiler::ProcessedFeedback::IsInsufficient () const [inline]
Definition at line 49 of file processed-feedback.h.
{ return kind() == kInsufficient; }
References kind(), and kInsufficient.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::BuildConstruct(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadGlobal(), v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFeedbackRelation(), v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFrequency(), v8::internal::compiler::JSHeapBroker::FeedbackIsInsufficient(), v8::internal::compiler::JSHeapBroker::GetFeedbackForBinaryOperation(), v8::internal::compiler::JSHeapBroker::GetFeedbackForCompareOperation(), v8::internal::compiler::JSHeapBroker::GetFeedbackForForIn(), v8::internal::compiler::JSHeapBroker::GetFeedbackForTypeOf(), v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::GetSpeculationMode(), v8::internal::compiler::BytecodeGraphBuilder::GetSpeculationMode(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSGetTemplateObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOfWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
kind()
Kind v8::internal::compiler::ProcessedFeedback::kind () const [inline]
Definition at line 46 of file processed-feedback.h.
{ return kind_; }
References kind_.
Referenced by AsBinaryOperation(), AsCall(), AsCompareOperation(), AsElementAccess(), AsForIn(), AsGlobalAccess(), AsInstanceOf(), AsLiteral(), AsMegaDOMPropertyAccess(), AsNamedAccess(), AsRegExpLiteral(), AsTemplateObject(), AsTypeOf(), v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::BuildConstruct(), v8::internal::maglev::MaglevGraphBuilder::BuildGetKeyedProperty(), IsInsufficient(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::ShouldUseMegamorphicAccessBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TryBuildGetKeyedPropertyWithEnumeratedKey(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildLoadNamedProperty().
slot_kind()
FeedbackSlotKind v8::internal::compiler::ProcessedFeedback::slot_kind () const [inline]
Definition at line 48 of file processed-feedback.h.
{ return slot_kind_; }
References slot_kind_.
Referenced by v8::internal::compiler::ElementAccessFeedback::ElementAccessFeedback(), v8::internal::compiler::JSHeapBroker::GetFeedbackSlotKind(), v8::internal::compiler::GlobalAccessFeedback::GlobalAccessFeedback(), v8::internal::compiler::MegaDOMPropertyAccessFeedback::MegaDOMPropertyAccessFeedback(), v8::internal::compiler::NamedAccessFeedback::NamedAccessFeedback(), v8::internal::compiler::ElementAccessFeedback::Refine(), and v8::internal::compiler::SingleValueFeedback< T, K >::SingleValueFeedback().
Member Data Documentation
kind_
Kind const v8::internal::compiler::ProcessedFeedback::kind_ [private]
Definition at line 69 of file processed-feedback.h.
Referenced by kind().
slot_kind_
FeedbackSlotKind const v8::internal::compiler::ProcessedFeedback::slot_kind_ [private]
Definition at line 70 of file processed-feedback.h.
Referenced by slot_kind().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/processed-feedback.h
/mnt/V8SourceCode/src/compiler/js-heap-broker.cc