v8::ReturnValue< T > Class Template Reference
#include <v8-function-callback.h>
Public Member Functions
template<class S >
ReturnValue (const ReturnValue< S > &that)
template<typename S >
void Set (const Global< S > &handle)
template<typename S >
void SetNonEmpty (const Global< S > &handle)
template<typename S >
void Set (const BasicTracedReference< S > &handle)
template<typename S >
void SetNonEmpty (const BasicTracedReference< S > &handle)
template<typename S >
void Set (const Local< S > handle)
template<typename S >
void SetNonEmpty (const Local< S > handle)
void Set (bool value)
void Set (double i)
void Set (int16_t i)
void Set (int32_t i)
void Set (int64_t i)
void Set (uint16_t i)
void Set (uint32_t i)
void Set (uint64_t i)
void SetNull ()
void SetUndefined ()
void SetFalse ()
void SetEmptyString ()
Isolate * GetIsolate () const
template<typename S >
void Set (S *whatever)
Local< Value > Get () const
Private Member Functions
void SetInternal (internal::Address value)
void SetDefaultValue ()
ReturnValue (internal::Address *slot)
Private Attributes
internal::Address * value_
Static Private Attributes
static constexpr int kIsolateValueIndex = -2
Friends
template<class F >
class ReturnValue
template<class F >
class FunctionCallbackInfo
template<class F >
class PropertyCallbackInfo
template<class F , class G , class H >
class PersistentValueMapBase
Detailed Description
template<typename T>
class v8::ReturnValue< T >
Definition at line 41 of file v8-function-callback.h.
Constructor & Destructor Documentation
ReturnValue() [1/2]
template<typename T >
template<class S >
v8::ReturnValue< T >::ReturnValue (const ReturnValue< S > & that) [inline]
Definition at line 44 of file v8-function-callback.h.
                                                    : value_(that.value_) {
    static_assert(std::is_base_of_v<T, S>, "type check");
  }
ReturnValue() [2/2]
template<typename T >
v8::ReturnValue< T >::ReturnValue (internal::Address * slot) [inline], [explicit], [private]
Definition at line 319 of file v8-function-callback.h.
: value_(slot) {}
Member Function Documentation
Get()
template<typename T >
Local< Value > v8::ReturnValue< T >::Get [inline]
Definition at line 603 of file v8-function-callback.h.
                                       {
  return Local<Value>::New(GetIsolate(),
                           internal::ValueHelper::SlotAsValue<Value>(value_));
}
References v8::Local< T >::New().
GetIsolate()
template<typename T >
Isolate * v8::ReturnValue< T >::GetIsolate [inline]
Definition at line 598 of file v8-function-callback.h.
                                          {
  return *reinterpret_cast<Isolate**>(&value_[kIsolateValueIndex]);
}
Set() [1/12]
template<typename T >
void v8::ReturnValue< T >::Set (bool value) [inline]
Definition at line 497 of file v8-function-callback.h.
                                   {
  static_assert(std::is_void_v<T> || std::is_base_of_v<T, Boolean>,
                "type check");
  using I = internal::Internals;
#if V8_STATIC_ROOTS_BOOL
#ifdef V8_ENABLE_CHECKS
  internal::PerformCastCheck(
      internal::ValueHelper::SlotAsValue<Value, true>(value_));
#endif // V8_ENABLE_CHECKS
  SetInternal(value ? I::StaticReadOnlyRoot::kTrueValue
                    : I::StaticReadOnlyRoot::kFalseValue);
#else
  int root_index;
  if (value) {
    root_index = I::kTrueValueRootIndex;
  } else {
    root_index = I::kFalseValueRootIndex;
  }
  *value_ = I::GetRoot(GetIsolate(), root_index);
#endif // V8_STATIC_ROOTS_BOOL
}
References I, v8::internal::PerformCastCheck(), and v8::internal::value.
Set() [2/12]
template<typename T >
template<typename S >
void v8::ReturnValue< T >::Set (const BasicTracedReference< S > & handle) [inline]
Definition at line 358 of file v8-function-callback.h.
                                                              {
  static_assert(std::is_base_of_v<T, S>, "type check");
  if (V8_UNLIKELY(handle.IsEmpty())) {
    SetDefaultValue();
  } else {
    SetInternal(handle.ptr());
  }
}
References v8::internal::handle(), and V8_UNLIKELY.
Set() [3/12]
template<typename T >
template<typename S >
void v8::ReturnValue< T >::Set (const Global< S > & handle) [inline]
Definition at line 337 of file v8-function-callback.h.
                                                {
  static_assert(std::is_base_of_v<T, S>, "type check");
  if (V8_UNLIKELY(handle.IsEmpty())) {
    SetDefaultValue();
  } else {
    SetInternal(handle.ptr());
  }
}
References v8::internal::handle(), and V8_UNLIKELY.
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::WasmObjectToJSReturnValue(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalGetValueCommon(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryToFixedLengthBufferImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryToResizableBufferImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl().
Set() [4/12]
template<typename T >
template<typename S >
void v8::ReturnValue< T >::Set (const Local< S > handle) [inline]
Definition at line 379 of file v8-function-callback.h.
                                              {
  // "V8_DEPRECATE_SOON" this method if |T| is |void|.
#ifdef V8_IMMINENT_DEPRECATION_WARNINGS
  static constexpr bool is_allowed_void = false;
  static_assert(!std::is_void_v<T>,
                "ReturnValue<void>::Set(const Local<S>) is deprecated. "
                "Do nothing to indicate that the operation succeeded or use "
                "SetFalse() to indicate that the operation failed (don't "
                "forget to handle info.ShouldThrowOnError()). "
                "See http://crbug.com/348660658 for details.");
#else
  static constexpr bool is_allowed_void = std::is_void_v<T>;
#endif // V8_IMMINENT_DEPRECATION_WARNINGS
  static_assert(is_allowed_void || std::is_base_of_v<T, S>, "type check");
  if (V8_UNLIKELY(handle.IsEmpty())) {
    SetDefaultValue();
  } else if constexpr (is_allowed_void) {
    // Simulate old behaviour for "v8::AccessorSetterCallback" for which
    // it was possible to set the return value even for ReturnValue<void>.
    Set(handle->BooleanValue(GetIsolate()));
  } else {
    SetInternal(handle.ptr());
  }
}
References v8::internal::handle(), and V8_UNLIKELY.
Set() [5/12]
template<typename T >
void v8::ReturnValue< T >::Set (double i) [inline]
Definition at line 433 of file v8-function-callback.h.
                                 {
  static_assert(std::is_base_of_v<T, Number>, "type check");
  SetNonEmpty(Number::New(GetIsolate(), i));
}
References v8::Number::New().
Set() [6/12]
template<typename T >
void v8::ReturnValue< T >::Set (int16_t i) [inline]
Definition at line 439 of file v8-function-callback.h.
                                  {
  static_assert(std::is_base_of_v<T, Integer>, "type check");
  using I = internal::Internals;
  static_assert(I::IsValidSmi(std::numeric_limits<int16_t>::min()));
  static_assert(I::IsValidSmi(std::numeric_limits<int16_t>::max()));
  SetInternal(I::IntegralToSmi(i));
}
References I, and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::IsValidSmi().
Set() [7/12]
template<typename T >
void v8::ReturnValue< T >::Set (int32_t i) [inline]
Definition at line 448 of file v8-function-callback.h.
                                  {
  static_assert(std::is_base_of_v<T, Integer>, "type check");
  if (const auto result = internal::Internals::TryIntegralToSmi(i)) {
    SetInternal(*result);
    return;
  }
  SetNonEmpty(Integer::New(GetIsolate(), i));
}
References v8::Integer::New(), v8::base::internal::result, and v8::internal::Internals::TryIntegralToSmi().
Set() [8/12]
template<typename T >
void v8::ReturnValue< T >::Set (int64_t i) [inline]
Definition at line 458 of file v8-function-callback.h.
                                  {
  static_assert(std::is_base_of_v<T, Integer>, "type check");
  if (const auto result = internal::Internals::TryIntegralToSmi(i)) {
    SetInternal(*result);
    return;
  }
  SetNonEmpty(Number::New(GetIsolate(), static_cast<double>(i)));
}
References v8::Number::New(), v8::base::internal::result, and v8::internal::Internals::TryIntegralToSmi().
Set() [9/12]
template<typename T >
template<typename S >
void v8::ReturnValue< T >::Set (S * whatever) [inline]
Definition at line 610 of file v8-function-callback.h.
                                    {
  static_assert(sizeof(S) < 0, "incompilable to prevent inadvertent misuse");
}
References v8::internal::S.
Set() [10/12]
template<typename T >
void v8::ReturnValue< T >::Set (uint16_t i) [inline]
Definition at line 468 of file v8-function-callback.h.
                                   {
  static_assert(std::is_base_of_v<T, Integer>, "type check");
  using I = internal::Internals;
  static_assert(I::IsValidSmi(std::numeric_limits<uint16_t>::min()));
  static_assert(I::IsValidSmi(std::numeric_limits<uint16_t>::max()));
  SetInternal(I::IntegralToSmi(i));
}
References I, and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::IsValidSmi().
Set() [11/12]
template<typename T >
void v8::ReturnValue< T >::Set (uint32_t i) [inline]
Definition at line 477 of file v8-function-callback.h.
                                   {
  static_assert(std::is_base_of_v<T, Integer>, "type check");
  if (const auto result = internal::Internals::TryIntegralToSmi(i)) {
    SetInternal(*result);
    return;
  }
  SetNonEmpty(Integer::NewFromUnsigned(GetIsolate(), i));
}
References v8::Integer::NewFromUnsigned(), v8::base::internal::result, and v8::internal::Internals::TryIntegralToSmi().
Set() [12/12]
template<typename T >
void v8::ReturnValue< T >::Set (uint64_t i) [inline]
Definition at line 487 of file v8-function-callback.h.
                                   {
  static_assert(std::is_base_of_v<T, Integer>, "type check");
  if (const auto result = internal::Internals::TryIntegralToSmi(i)) {
    SetInternal(*result);
    return;
  }
  SetNonEmpty(Number::New(GetIsolate(), static_cast<double>(i)));
}
References v8::Number::New(), v8::base::internal::result, and v8::internal::Internals::TryIntegralToSmi().
SetDefaultValue()
template<typename T >
void v8::ReturnValue< T >::SetDefaultValue [inline], [private]
Definition at line 520 of file v8-function-callback.h.
                                     {
  using I = internal::Internals;
  if constexpr (std::is_same_v<void, T> || std::is_same_v<v8::Boolean, T>) {
    Set(true);
  } else if constexpr (std::is_same_v<v8::Integer, T>) {
    SetInternal(I::IntegralToSmi(0));
  } else {
    static_assert(std::is_same_v<v8::Value, T> || std::is_same_v<v8::Array, T>);
#if V8_STATIC_ROOTS_BOOL
    SetInternal(I::StaticReadOnlyRoot::kUndefinedValue);
#else
    *value_ = I::GetRoot(GetIsolate(), I::kUndefinedValueRootIndex);
#endif // V8_STATIC_ROOTS_BOOL
  }
}
References I.
SetEmptyString()
template<typename T >
void v8::ReturnValue< T >::SetEmptyString [inline]
Definition at line 583 of file v8-function-callback.h.
                                    {
  static_assert(std::is_base_of_v<T, String>, "type check");
  using I = internal::Internals;
#if V8_STATIC_ROOTS_BOOL
#ifdef V8_ENABLE_CHECKS
  internal::PerformCastCheck(
      internal::ValueHelper::SlotAsValue<Value, true>(value_));
#endif // V8_ENABLE_CHECKS
  SetInternal(I::StaticReadOnlyRoot::kEmptyString);
#else
  *value_ = I::GetRoot(GetIsolate(), I::kEmptyStringRootIndex);
#endif // V8_STATIC_ROOTS_BOOL
}
References I, and v8::internal::PerformCastCheck().
SetFalse()
template<typename T >
void v8::ReturnValue< T >::SetFalse [inline]
Definition at line 567 of file v8-function-callback.h.
                              {
  static_assert(std::is_void_v<T> || std::is_base_of_v<T, Boolean>,
                "type check");
  using I = internal::Internals;
#if V8_STATIC_ROOTS_BOOL
#ifdef V8_ENABLE_CHECKS
  internal::PerformCastCheck(
      internal::ValueHelper::SlotAsValue<Value, true>(value_));
#endif // V8_ENABLE_CHECKS
  SetInternal(I::StaticReadOnlyRoot::kFalseValue);
#else
  *value_ = I::GetRoot(GetIsolate(), I::kFalseValueRootIndex);
#endif // V8_STATIC_ROOTS_BOOL
}
References I, and v8::internal::PerformCastCheck().
SetInternal()
template<typename T >
void v8::ReturnValue< T >::SetInternal (internal::Address value) [inline], [private]
Definition at line 322 of file v8-function-callback.h.
                                                      {
#if V8_STATIC_ROOTS_BOOL
  using I = internal::Internals;
  // Ensure that the upper 32-bits are not modified. Compiler should be
  // able to optimize this to a store of a lower 32-bits of the value.
  // This is fine since the callback can return only JavaScript values which
  // are either Smis or heap objects allocated in the main cage.
  *value_ = I::DecompressTaggedField(*value_, I::CompressTagged(value));
#else
  *value_ = value;
#endif // V8_STATIC_ROOTS_BOOL
}
References I, and v8::internal::value.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::SetReturnValueFromVal().
SetNonEmpty() [1/3]
template<typename T >
template<typename S >
void v8::ReturnValue< T >::SetNonEmpty (const BasicTracedReference< S > & handle) [inline]
Definition at line 369 of file v8-function-callback.h.
                                                                      {
  static_assert(std::is_base_of_v<T, S>, "type check");
#ifdef V8_ENABLE_CHECKS
  internal::VerifyHandleIsNonEmpty(handle.IsEmpty());
#endif // V8_ENABLE_CHECKS
  SetInternal(handle.ptr());
}
References v8::internal::handle(), and v8::internal::VerifyHandleIsNonEmpty().
SetNonEmpty() [2/3]
template<typename T >
template<typename S >
void v8::ReturnValue< T >::SetNonEmpty (const Global< S > & handle) [inline]
Definition at line 348 of file v8-function-callback.h.
                                                        {
  static_assert(std::is_base_of_v<T, S>, "type check");
#ifdef V8_ENABLE_CHECKS
  internal::VerifyHandleIsNonEmpty(handle.IsEmpty());
#endif // V8_ENABLE_CHECKS
  SetInternal(handle.ptr());
}
References v8::internal::handle(), and v8::internal::VerifyHandleIsNonEmpty().
SetNonEmpty() [3/3]
template<typename T >
template<typename S >
void v8::ReturnValue< T >::SetNonEmpty (const Local< S > handle) [inline]
Definition at line 406 of file v8-function-callback.h.
                                                      {
  // "V8_DEPRECATE_SOON" this method if |T| is |void|.
#ifdef V8_IMMINENT_DEPRECATION_WARNINGS
  static constexpr bool is_allowed_void = false;
  static_assert(!std::is_void_v<T>,
                "ReturnValue<void>::SetNonEmpty(const Local<S>) is deprecated. "
                "Do nothing to indicate that the operation succeeded or use "
                "SetFalse() to indicate that the operation failed (don't "
                "forget to handle info.ShouldThrowOnError()). "
                "See http://crbug.com/348660658 for details.");
#else
  static constexpr bool is_allowed_void = std::is_void_v<T>;
#endif // V8_IMMINENT_DEPRECATION_WARNINGS
  static_assert(is_allowed_void || std::is_base_of_v<T, S>, "type check");
#ifdef V8_ENABLE_CHECKS
  internal::VerifyHandleIsNonEmpty(handle.IsEmpty());
#endif // V8_ENABLE_CHECKS
  if constexpr (is_allowed_void) {
    // Simulate old behaviour for "v8::AccessorSetterCallback" for which
    // it was possible to set the return value even for ReturnValue<void>.
    Set(handle->BooleanValue(GetIsolate()));
  } else {
    SetInternal(handle.ptr());
  }
}
References v8::internal::handle(), and v8::internal::VerifyHandleIsNonEmpty().
SetNull()
template<typename T >
void v8::ReturnValue< T >::SetNull [inline]
Definition at line 537 of file v8-function-callback.h.
                             {
  static_assert(std::is_base_of_v<T, Primitive>, "type check");
  using I = internal::Internals;
#if V8_STATIC_ROOTS_BOOL
#ifdef V8_ENABLE_CHECKS
  internal::PerformCastCheck(
      internal::ValueHelper::SlotAsValue<Value, true>(value_));
#endif // V8_ENABLE_CHECKS
  SetInternal(I::StaticReadOnlyRoot::kNullValue);
#else
  *value_ = I::GetRoot(GetIsolate(), I::kNullValueRootIndex);
#endif // V8_STATIC_ROOTS_BOOL
}
References I, and v8::internal::PerformCastCheck().
SetUndefined()
template<typename T >
void v8::ReturnValue< T >::SetUndefined [inline]
Definition at line 552 of file v8-function-callback.h.
                                  {
  static_assert(std::is_base_of_v<T, Primitive>, "type check");
  using I = internal::Internals;
#if V8_STATIC_ROOTS_BOOL
#ifdef V8_ENABLE_CHECKS
  internal::PerformCastCheck(
      internal::ValueHelper::SlotAsValue<Value, true>(value_));
#endif // V8_ENABLE_CHECKS
  SetInternal(I::StaticReadOnlyRoot::kUndefinedValue);
#else
  *value_ = I::GetRoot(GetIsolate(), I::kUndefinedValueRootIndex);
#endif // V8_STATIC_ROOTS_BOOL
}
References I, and v8::internal::PerformCastCheck().
Friends And Related Function Documentation
FunctionCallbackInfo
template<typename T >
template<class F >
friend class FunctionCallbackInfo [friend]
Definition at line 90 of file v8-function-callback.h.
PersistentValueMapBase
template<typename T >
template<class F , class G , class H >
friend class PersistentValueMapBase [friend]
Definition at line 94 of file v8-function-callback.h.
PropertyCallbackInfo
template<typename T >
template<class F >
friend class PropertyCallbackInfo [friend]
Definition at line 92 of file v8-function-callback.h.
ReturnValue
template<typename T >
template<class F >
friend class ReturnValue [friend]
Definition at line 88 of file v8-function-callback.h.
Member Data Documentation
kIsolateValueIndex
template<typename T >
constexpr int v8::ReturnValue< T >::kIsolateValueIndex = -2 [static], [constexpr], [private]
Definition at line 106 of file v8-function-callback.h.
value_
template<typename T >
internal::Address* v8::ReturnValue< T >::value_ [private]
Definition at line 108 of file v8-function-callback.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-function-callback.h