v8::internal::wasm::gdb_server::TaskRunner Class Reference
Classes
class Task
Public Member Functions
TaskRunner ()
TaskRunner (const TaskRunner &)=delete
TaskRunner & operator= (const TaskRunner &)=delete
void Run ()
void Terminate ()
template<typename Functor >
auto Append (base::Semaphore *ready_semaphore, Functor &&task)
Private Member Functions
std::shared_ptr< Task > GetNext ()
Private Attributes
LockedQueue< std::shared_ptr< Task > > queue_
v8::base::Semaphore process_queue_semaphore_
int nested_loop_count_
std::atomic< bool > is_terminated_
Detailed Description
Definition at line 25 of file gdb-server.cc.
Constructor & Destructor Documentation
TaskRunner() [1/2]
v8::internal::wasm::gdb_server::TaskRunner::TaskRunner () [inline]
Definition at line 49 of file gdb-server.cc.
      : process_queue_semaphore_(0),
        nested_loop_count_(0),
        is_terminated_(false) {}
TaskRunner() [2/2]
v8::internal::wasm::gdb_server::TaskRunner::TaskRunner (const TaskRunner &) [delete]
Member Function Documentation
Append()
template<typename Functor >
auto v8::internal::wasm::gdb_server::TaskRunner::Append (base::Semaphore * ready_semaphore, Functor && task) [inline]
Definition at line 82 of file gdb-server.cc.
                                                              {
    queue_.Enqueue(std::make_shared<Task>(ready_semaphore, task));
    process_queue_semaphore_.Signal();
  }
References process_queue_semaphore_, queue_, and v8::base::Semaphore::Signal().
GetNext()
std::shared_ptr<Task> v8::internal::wasm::gdb_server::TaskRunner::GetNext () [inline], [private]
Definition at line 88 of file gdb-server.cc.
                                {
    while (!is_terminated_) {
      if (queue_.IsEmpty()) {
        process_queue_semaphore_.Wait();
      }
      std::shared_ptr<Task> task;
      if (queue_.Dequeue(&task)) {
        return task;
      }
    }
    return nullptr;
  }
References is_terminated_, process_queue_semaphore_, queue_, and v8::base::Semaphore::Wait().
Referenced by Run().
operator=()
TaskRunner& v8::internal::wasm::gdb_server::TaskRunner::operator= (const TaskRunner &) [delete]
Run()
void v8::internal::wasm::gdb_server::TaskRunner::Run () [inline]
Definition at line 59 of file gdb-server.cc.
             {
    is_terminated_ = false;
    int loop_number = ++nested_loop_count_;
    while (nested_loop_count_ == loop_number && !is_terminated_) {
      std::shared_ptr<Task> task = GetNext();
      if (task) {
        task->Run();
      }
    }
  }
References GetNext(), is_terminated_, and nested_loop_count_.
Terminate()
void v8::internal::wasm::gdb_server::TaskRunner::Terminate () [inline]
Definition at line 72 of file gdb-server.cc.
                   {
    DCHECK_LT(0, nested_loop_count_);
    --nested_loop_count_;
    is_terminated_ = true;
    process_queue_semaphore_.Signal();
  }
References DCHECK_LT, is_terminated_, nested_loop_count_, process_queue_semaphore_, and v8::base::Semaphore::Signal().
Member Data Documentation
is_terminated_
std::atomic<bool> v8::internal::wasm::gdb_server::TaskRunner::is_terminated_ [private]
Definition at line 105 of file gdb-server.cc.
Referenced by GetNext(), Run(), and Terminate().
nested_loop_count_
int v8::internal::wasm::gdb_server::TaskRunner::nested_loop_count_ [private]
Definition at line 104 of file gdb-server.cc.
Referenced by Run(), and Terminate().
process_queue_semaphore_
v8::base::Semaphore v8::internal::wasm::gdb_server::TaskRunner::process_queue_semaphore_ [private]
Definition at line 103 of file gdb-server.cc.
Referenced by Append(), GetNext(), and Terminate().
queue_
LockedQueue<std::shared_ptr<Task> > v8::internal::wasm::gdb_server::TaskRunner::queue_ [private]
Definition at line 102 of file gdb-server.cc.
Referenced by Append(), and GetNext().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/gdb-server.cc