cppgc::internal::StatsCollector Class Reference
#include <stats-collector.h>
Classes
class AllocationObserver
struct Event
class InternalScope
Public Types
enum ScopeId { kNumHistogramScopeIds
, kNumScopeIds
 }
enum ConcurrentScopeId { kNumHistogramConcurrentScopeIds
, kNumConcurrentScopeIds
 }
using MarkingType = GCConfig::MarkingType
using SweepingType = GCConfig::SweepingType
using DisabledScope = InternalScope< kDisabled, kMutatorThread >
using EnabledScope = InternalScope< kEnabled, kMutatorThread >
using DisabledConcurrentScope = InternalScope< kDisabled, kConcurrentThread >
using EnabledConcurrentScope = InternalScope< kEnabled, kConcurrentThread >
Public Member Functions
StatsCollector (Platform *)
StatsCollector (const StatsCollector &)=delete
StatsCollector & operator= (const StatsCollector &)=delete
void RegisterObserver (AllocationObserver *)
void UnregisterObserver (AllocationObserver *)
void NotifyAllocation (size_t)
void NotifyExplicitFree (size_t)
void NotifySafePointForConservativeCollection ()
void NotifySafePointForTesting ()
void NotifyUnmarkingStarted (CollectionType)
void NotifyMarkingStarted (CollectionType, MarkingType, IsForcedGC)
void NotifyMarkingCompleted (size_t marked_bytes)
void NotifySweepingCompleted (SweepingType)
size_t allocated_memory_size () const
size_t allocated_object_size () const
size_t marked_bytes () const
size_t marked_bytes_on_current_cycle () const
v8::base::TimeDelta marking_time () const
double GetRecentAllocationSpeedInBytesPerMs () const
const Event & GetPreviousEventForTesting () const
void NotifyAllocatedMemory (int64_t)
void NotifyFreedMemory (int64_t)
void IncrementDiscardedMemory (size_t)
void DecrementDiscardedMemory (size_t)
void ResetDiscardedMemory ()
size_t discarded_memory_size () const
size_t resident_memory_size () const
void SetMetricRecorder (std::unique_ptr< MetricRecorder > histogram_recorder)
MetricRecorder * GetMetricRecorder () const
Static Public Attributes
static constexpr size_t kAllocationThresholdBytes = 1024
Private Types
enum TraceCategory { kEnabled
, kDisabled
 }
enum ScopeContext { kMutatorThread
, kConcurrentThread
 }
enum class GarbageCollectionState : uint8_t { kNotRunning
, kUnmarking
, kMarking
, kSweeping
 }
using IsForcedGC = GCConfig::IsForcedGC
Private Member Functions
void RecordHistogramSample (ScopeId, v8::base::TimeDelta)
void RecordHistogramSample (ConcurrentScopeId, v8::base::TimeDelta)
template<typename Callback >
void ForAllAllocationObservers (Callback callback)
void AllocatedObjectSizeSafepointImpl ()
Static Private Member Functions
constexpr static const char * GetScopeName (ScopeId id, CollectionType type)
constexpr static const char * GetScopeName (ConcurrentScopeId id, CollectionType type)
Private Attributes
int64_t allocated_bytes_since_end_of_marking_ = 0
v8::base::TimeTicks time_of_last_end_of_marking_ = v8::base::TimeTicks::Now()
int64_t allocated_bytes_since_safepoint_ = 0
int64_t explicitly_freed_bytes_since_safepoint_ = 0
size_t marked_bytes_so_far_ = 0
int64_t memory_allocated_bytes_ = 0
int64_t memory_freed_bytes_since_end_of_marking_ = 0
std::atomic< size_t > discarded_bytes_ {0}
std::vector< AllocationObserver * > allocation_observers_
bool allocation_observer_deleted_ = false
GarbageCollectionState gc_state_ = GarbageCollectionState::kNotRunning
Event current_
Event previous_
std::unique_ptr< MetricRecorder > metric_recorder_
Platform * platform_
Detailed Description
Definition at line 84 of file stats-collector.h.
Member Typedef Documentation
DisabledConcurrentScope
using cppgc::internal::StatsCollector::DisabledConcurrentScope = InternalScope<kDisabled, kConcurrentThread>
Definition at line 238 of file stats-collector.h.
DisabledScope
using cppgc::internal::StatsCollector::DisabledScope = InternalScope<kDisabled, kMutatorThread>
Definition at line 236 of file stats-collector.h.
EnabledConcurrentScope
using cppgc::internal::StatsCollector::EnabledConcurrentScope = InternalScope<kEnabled, kConcurrentThread>
Definition at line 239 of file stats-collector.h.
EnabledScope
using cppgc::internal::StatsCollector::EnabledScope = InternalScope<kEnabled, kMutatorThread>
Definition at line 237 of file stats-collector.h.
IsForcedGC
using cppgc::internal::StatsCollector::IsForcedGC = GCConfig::IsForcedGC [private]
Definition at line 85 of file stats-collector.h.
MarkingType
using cppgc::internal::StatsCollector::MarkingType = GCConfig::MarkingType
Definition at line 88 of file stats-collector.h.
SweepingType
using cppgc::internal::StatsCollector::SweepingType = GCConfig::SweepingType
Definition at line 89 of file stats-collector.h.
Member Enumeration Documentation
ConcurrentScopeId
enum cppgc::internal::StatsCollector::ConcurrentScopeId
Enumerator
kNumHistogramConcurrentScopeIds
kNumConcurrentScopeIds
Definition at line 104 of file stats-collector.h.
                         {
#define CPPGC_DECLARE_ENUM(name) k##name,
    CPPGC_FOR_ALL_HISTOGRAM_CONCURRENT_SCOPES(CPPGC_DECLARE_ENUM)
        kNumHistogramConcurrentScopeIds,
    CPPGC_FOR_ALL_CONCURRENT_SCOPES(CPPGC_DECLARE_ENUM)
#undef CPPGC_DECLARE_ENUM
        kNumConcurrentScopeIds
  };
GarbageCollectionState
enum cppgc::internal::StatsCollector::GarbageCollectionState : uint8_t [strong], [private]
Enumerator
kNotRunning
kUnmarking
kMarking
kSweeping
Definition at line 341 of file stats-collector.h.
                                    : uint8_t {
    kNotRunning,
    kUnmarking,
    kMarking,
    kSweeping
  };
ScopeContext
enum cppgc::internal::StatsCollector::ScopeContext [private]
Enumerator
kMutatorThread
kConcurrentThread
Definition at line 170 of file stats-collector.h.
{ kMutatorThread, kConcurrentThread };
ScopeId
enum cppgc::internal::StatsCollector::ScopeId
Enumerator
kNumHistogramScopeIds
kNumScopeIds
Definition at line 95 of file stats-collector.h.
               {
#define CPPGC_DECLARE_ENUM(name) k##name,
    CPPGC_FOR_ALL_HISTOGRAM_SCOPES(CPPGC_DECLARE_ENUM)
        kNumHistogramScopeIds,
    CPPGC_FOR_ALL_SCOPES(CPPGC_DECLARE_ENUM)
#undef CPPGC_DECLARE_ENUM
        kNumScopeIds,
  };
TraceCategory
enum cppgc::internal::StatsCollector::TraceCategory [private]
Enumerator
kEnabled
kDisabled
Definition at line 169 of file stats-collector.h.
{ kEnabled, kDisabled };
Constructor & Destructor Documentation
StatsCollector() [1/2]
cppgc::internal::StatsCollector::StatsCollector (Platform * platform) [explicit]
Definition at line 22 of file stats-collector.cc.
                                                 : platform_(platform) {
  USE(platform_);
}
References platform_, and USE.
StatsCollector() [2/2]
cppgc::internal::StatsCollector::StatsCollector (const StatsCollector &) [delete]
Member Function Documentation
allocated_memory_size()
size_t cppgc::internal::StatsCollector::allocated_memory_size () const
Definition at line 296 of file stats-collector.cc.
                                                   {
  return memory_allocated_bytes_ - memory_freed_bytes_since_end_of_marking_;
}
References memory_allocated_bytes_, and memory_freed_bytes_since_end_of_marking_.
Referenced by resident_memory_size().
allocated_object_size()
size_t cppgc::internal::StatsCollector::allocated_object_size () const
Definition at line 300 of file stats-collector.cc.
                                                   {
  return marked_bytes_so_far_ + allocated_bytes_since_end_of_marking_;
}
References allocated_bytes_since_end_of_marking_, and marked_bytes_so_far_.
Referenced by v8::internal::MinorGCHeapGrowing::LimitReached().
AllocatedObjectSizeSafepointImpl()
void cppgc::internal::StatsCollector::AllocatedObjectSizeSafepointImpl () [private]
Definition at line 72 of file stats-collector.cc.
                                                      {
  allocated_bytes_since_end_of_marking_ +=
      static_cast<int64_t>(allocated_bytes_since_safepoint_) -
      static_cast<int64_t>(explicitly_freed_bytes_since_safepoint_);
  // Save the epoch to avoid clearing counters when a GC happened, see below.
  const auto saved_epoch = current_.epoch;
  // These observer methods may start or finalize GC. In case they trigger a
  // final GC pause, the delta counters are reset there and the following
  // observer calls are called with '0' updates.
  ForAllAllocationObservers([this](AllocationObserver* observer) {
    // Recompute delta here so that a GC finalization is able to clear the
    // delta for other observer calls.
    int64_t delta = allocated_bytes_since_safepoint_ -
                    explicitly_freed_bytes_since_safepoint_;
    if (delta < 0) {
      observer->AllocatedObjectSizeDecreased(static_cast<size_t>(-delta));
    } else {
      observer->AllocatedObjectSizeIncreased(static_cast<size_t>(delta));
    }
  });
  // Only clear the counters when no garbage collection happened. In case of a
  // garbage collection in the callbacks, the counters have been cleared by
  // `NotifyMarkingFinished()`. In addition, atomic sweeping may have already
  // allocated new memory which would be dropped from accounting in case
  // of clearing here.
  if (saved_epoch == current_.epoch) {
    allocated_bytes_since_safepoint_ = 0;
    explicitly_freed_bytes_since_safepoint_ = 0;
  }
}
References allocated_bytes_since_end_of_marking_, allocated_bytes_since_safepoint_, cppgc::internal::StatsCollector::AllocationObserver::AllocatedObjectSizeDecreased(), cppgc::internal::StatsCollector::AllocationObserver::AllocatedObjectSizeIncreased(), current_, cppgc::internal::StatsCollector::Event::epoch, explicitly_freed_bytes_since_safepoint_, and ForAllAllocationObservers().
Referenced by NotifySafePointForConservativeCollection(), and NotifySafePointForTesting().
DecrementDiscardedMemory()
void cppgc::internal::StatsCollector::DecrementDiscardedMemory (size_t value)
Definition at line 361 of file stats-collector.cc.
                                                          {
  const size_t old =
      discarded_bytes_.fetch_sub(value, std::memory_order_relaxed);
  DCHECK_GE(old, old - value);
  USE(old);
}
References DCHECK_GE, discarded_bytes_, USE, and v8::internal::value.
Referenced by cppgc::internal::BasePage::Destroy(), and cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBufferFromFreeList().
discarded_memory_size()
size_t cppgc::internal::StatsCollector::discarded_memory_size () const
Definition at line 372 of file stats-collector.cc.
                                                   {
  return discarded_bytes_.load(std::memory_order_relaxed);
}
References discarded_bytes_.
Referenced by resident_memory_size().
ForAllAllocationObservers()
template<typename Callback >
void cppgc::internal::StatsCollector::ForAllAllocationObservers (Callback callback) [private]
Definition at line 402 of file stats-collector.h.
                                                                {
  // Iterate using indices to allow push_back() of new observers.
  for (size_t i = 0; i < allocation_observers_.size(); ++i) {
    auto* observer = allocation_observers_[i];
    if (observer) {
      callback(observer);
    }
  }
  if (allocation_observer_deleted_) {
    allocation_observers_.erase(
        std::remove(allocation_observers_.begin(), allocation_observers_.end(),
                    nullptr),
        allocation_observers_.end());
    allocation_observer_deleted_ = false;
  }
}
References allocation_observer_deleted_, allocation_observers_, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by AllocatedObjectSizeSafepointImpl(), NotifyAllocatedMemory(), NotifyFreedMemory(), and NotifyMarkingCompleted().
GetMetricRecorder()
MetricRecorder* cppgc::internal::StatsCollector::GetMetricRecorder () const [inline]
Definition at line 338 of file stats-collector.h.
{ return metric_recorder_.get(); }
GetPreviousEventForTesting()
const Event& cppgc::internal::StatsCollector::GetPreviousEventForTesting () const [inline]
Definition at line 323 of file stats-collector.h.
{ return previous_; }
GetRecentAllocationSpeedInBytesPerMs()
double cppgc::internal::StatsCollector::GetRecentAllocationSpeedInBytesPerMs () const
Definition at line 162 of file stats-collector.cc.
                                                                  {
  v8::base::TimeTicks current_time = v8::base::TimeTicks::Now();
  DCHECK_LE(time_of_last_end_of_marking_, current_time);
  if (time_of_last_end_of_marking_ == current_time) return 0;
  return allocated_bytes_since_end_of_marking_ /
         (current_time - time_of_last_end_of_marking_).InMillisecondsF();
}
References allocated_bytes_since_end_of_marking_, DCHECK_LE, v8::base::TimeTicks::Now(), and time_of_last_end_of_marking_.
GetScopeName() [1/2]
constexpr static const char* cppgc::internal::StatsCollector::GetScopeName (ConcurrentScopeId id, CollectionType type) [inline], [static], [constexpr], [private]
Definition at line 154 of file stats-collector.h.
                                                                 {
    switch (id) {
#define CPPGC_CASE(name) \
  case k##name: \
    return type == CollectionType::kMajor ? "CppGC." #name \
                                          : "CppGC." #name ".Minor";
      CPPGC_FOR_ALL_HISTOGRAM_CONCURRENT_SCOPES(CPPGC_CASE)
      CPPGC_FOR_ALL_CONCURRENT_SCOPES(CPPGC_CASE)
#undef CPPGC_CASE
      default:
        return nullptr;
    }
  }
References CPPGC_CASE, CPPGC_FOR_ALL_CONCURRENT_SCOPES, and CPPGC_FOR_ALL_HISTOGRAM_CONCURRENT_SCOPES.
GetScopeName() [2/2]
constexpr static const char* cppgc::internal::StatsCollector::GetScopeName (ScopeId id, CollectionType type) [inline], [static], [constexpr], [private]
Definition at line 140 of file stats-collector.h.
                                                                             {
    switch (id) {
#define CPPGC_CASE(name) \
  case k##name: \
    return type == CollectionType::kMajor ? "CppGC." #name \
                                          : "CppGC." #name ".Minor";
      CPPGC_FOR_ALL_HISTOGRAM_SCOPES(CPPGC_CASE)
      CPPGC_FOR_ALL_SCOPES(CPPGC_CASE)
#undef CPPGC_CASE
      default:
        return nullptr;
    }
  }
References CPPGC_CASE, CPPGC_FOR_ALL_HISTOGRAM_SCOPES, and CPPGC_FOR_ALL_SCOPES.
IncrementDiscardedMemory()
void cppgc::internal::StatsCollector::IncrementDiscardedMemory (size_t value)
Definition at line 354 of file stats-collector.cc.
                                                          {
  const size_t old =
      discarded_bytes_.fetch_add(value, std::memory_order_relaxed);
  DCHECK_GE(old + value, old);
  USE(old);
}
References DCHECK_GE, discarded_bytes_, USE, and v8::internal::value.
marked_bytes()
size_t cppgc::internal::StatsCollector::marked_bytes () const
Definition at line 304 of file stats-collector.cc.
                                          {
  DCHECK_NE(GarbageCollectionState::kMarking, gc_state_);
  return marked_bytes_so_far_;
}
References DCHECK_NE, gc_state_, kMarking, and marked_bytes_so_far_.
Referenced by NotifyMarkingCompleted().
marked_bytes_on_current_cycle()
size_t cppgc::internal::StatsCollector::marked_bytes_on_current_cycle () const
Definition at line 309 of file stats-collector.cc.
                                                           {
  DCHECK_NE(GarbageCollectionState::kNotRunning, gc_state_);
  return current_.marked_bytes;
}
References current_, DCHECK_NE, gc_state_, kNotRunning, and cppgc::internal::StatsCollector::Event::marked_bytes.
marking_time()
v8::base::TimeDelta cppgc::internal::StatsCollector::marking_time () const
Definition at line 314 of file stats-collector.cc.
                                                   {
  DCHECK_NE(GarbageCollectionState::kMarking, gc_state_);
  // During sweeping we refer to the current Event as that already holds the
  // correct marking information. In all other phases, the previous event holds
  // the most up-to-date marking information.
  const Event& event =
      gc_state_ == GarbageCollectionState::kSweeping ? current_ : previous_;
  return event.scope_data[kAtomicMark] + event.scope_data[kIncrementalMark] +
         v8::base::TimeDelta::FromMicroseconds(v8::base::Relaxed_Load(
             &event.concurrent_scope_data[kConcurrentMark]));
}
References current_, DCHECK_NE, v8::base::TimeDelta::FromMicroseconds(), gc_state_, kMarking, kSweeping, previous_, v8::base::Relaxed_Load(), and cppgc::internal::StatsCollector::Event::scope_data.
NotifyAllocatedMemory()
void cppgc::internal::StatsCollector::NotifyAllocatedMemory (int64_t size)
Definition at line 326 of file stats-collector.cc.
                                                       {
  memory_allocated_bytes_ += size;
#ifdef DEBUG
  const auto saved_epoch = current_.epoch;
#endif // DEBUG
  ForAllAllocationObservers([size](AllocationObserver* observer) {
    observer->AllocatedSizeIncreased(static_cast<size_t>(size));
  });
#ifdef DEBUG
  // AllocatedSizeIncreased() must not trigger GC.
  DCHECK_EQ(saved_epoch, current_.epoch);
#endif // DEBUG
}
References cppgc::internal::StatsCollector::AllocationObserver::AllocatedSizeIncreased(), current_, DCHECK_EQ, cppgc::internal::StatsCollector::Event::epoch, ForAllAllocationObservers(), memory_allocated_bytes_, and size().
Referenced by cppgc::internal::LargePage::TryCreate().
NotifyAllocation()
void cppgc::internal::StatsCollector::NotifyAllocation (size_t bytes)
Definition at line 41 of file stats-collector.cc.
                                                  {
  // The current GC may not have been started. This is ok as recording considers
  // the whole time range between garbage collections.
  allocated_bytes_since_safepoint_ += bytes;
#ifdef CPPGC_VERIFY_HEAP
  DCHECK_GE(tracked_live_bytes_ + bytes, tracked_live_bytes_);
  tracked_live_bytes_ += bytes;
#endif // CPPGC_VERIFY_HEAP
}
References allocated_bytes_since_safepoint_, and DCHECK_GE.
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), and cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject().
NotifyExplicitFree()
void cppgc::internal::StatsCollector::NotifyExplicitFree (size_t bytes)
Definition at line 51 of file stats-collector.cc.
                                                    {
  // See IncreaseAllocatedObjectSize for lifetime of the counter.
  explicitly_freed_bytes_since_safepoint_ += bytes;
#ifdef CPPGC_VERIFY_HEAP
  DCHECK_GE(tracked_live_bytes_, bytes);
  tracked_live_bytes_ -= bytes;
#endif // CPPGC_VERIFY_HEAP
}
References DCHECK_GE, and explicitly_freed_bytes_since_safepoint_.
Referenced by cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
NotifyFreedMemory()
void cppgc::internal::StatsCollector::NotifyFreedMemory (int64_t size)
Definition at line 340 of file stats-collector.cc.
                                                   {
  memory_freed_bytes_since_end_of_marking_ += size;
#ifdef DEBUG
  const auto saved_epoch = current_.epoch;
#endif // DEBUG
  ForAllAllocationObservers([size](AllocationObserver* observer) {
    observer->AllocatedSizeDecreased(static_cast<size_t>(size));
  });
#ifdef DEBUG
  // AllocatedSizeDecreased() must not trigger GC.
  DCHECK_EQ(saved_epoch, current_.epoch);
#endif // DEBUG
}
References cppgc::internal::StatsCollector::AllocationObserver::AllocatedSizeDecreased(), current_, DCHECK_EQ, cppgc::internal::StatsCollector::Event::epoch, ForAllAllocationObservers(), memory_freed_bytes_since_end_of_marking_, and size().
NotifyMarkingCompleted()
void cppgc::internal::StatsCollector::NotifyMarkingCompleted (size_t marked_bytes)
Definition at line 128 of file stats-collector.cc.
                                                               {
  DCHECK_EQ(GarbageCollectionState::kMarking, gc_state_);
  gc_state_ = GarbageCollectionState::kSweeping;
  current_.marked_bytes = marked_bytes;
  current_.object_size_before_sweep_bytes =
      marked_bytes_so_far_ + allocated_bytes_since_end_of_marking_ +
      allocated_bytes_since_safepoint_ -
      explicitly_freed_bytes_since_safepoint_;
  allocated_bytes_since_safepoint_ = 0;
  explicitly_freed_bytes_since_safepoint_ = 0;
  if (current_.collection_type == CollectionType::kMajor)
    marked_bytes_so_far_ = 0;
  marked_bytes_so_far_ += marked_bytes;
#ifdef CPPGC_VERIFY_HEAP
  tracked_live_bytes_ = marked_bytes_so_far_;
#endif // CPPGC_VERIFY_HEAP
  DCHECK_LE(memory_freed_bytes_since_end_of_marking_, memory_allocated_bytes_);
  memory_allocated_bytes_ -= memory_freed_bytes_since_end_of_marking_;
  current_.memory_size_before_sweep_bytes = memory_allocated_bytes_;
  memory_freed_bytes_since_end_of_marking_ = 0;
  ForAllAllocationObservers([this](AllocationObserver* observer) {
    observer->ResetAllocatedObjectSize(marked_bytes_so_far_);
  });
  // HeapGrowing would use the below fields to estimate allocation rate during
  // execution of ResetAllocatedObjectSize.
  allocated_bytes_since_end_of_marking_ = 0;
  time_of_last_end_of_marking_ = v8::base::TimeTicks::Now();
}
References allocated_bytes_since_end_of_marking_, allocated_bytes_since_safepoint_, cppgc::internal::StatsCollector::Event::collection_type, current_, DCHECK_EQ, DCHECK_LE, explicitly_freed_bytes_since_safepoint_, ForAllAllocationObservers(), gc_state_, cppgc::internal::kMajor, kMarking, kSweeping, cppgc::internal::StatsCollector::Event::marked_bytes, marked_bytes(), marked_bytes_so_far_, memory_allocated_bytes_, memory_freed_bytes_since_end_of_marking_, cppgc::internal::StatsCollector::Event::memory_size_before_sweep_bytes, v8::base::TimeTicks::Now(), cppgc::internal::StatsCollector::Event::object_size_before_sweep_bytes, cppgc::internal::StatsCollector::AllocationObserver::ResetAllocatedObjectSize(), and time_of_last_end_of_marking_.
Referenced by cppgc::internal::MarkerBase::LeaveAtomicPause(), and cppgc::internal::HeapBase::Terminate().
NotifyMarkingStarted()
void cppgc::internal::StatsCollector::NotifyMarkingStarted (CollectionType collection_type, MarkingType marking_type, IsForcedGC is_forced_gc)
Definition at line 116 of file stats-collector.cc.
                                                                   {
  DCHECK_IMPLIES(gc_state_ != GarbageCollectionState::kNotRunning,
                 (gc_state_ == GarbageCollectionState::kUnmarking &&
                  collection_type == CollectionType::kMajor));
  current_.collection_type = collection_type;
  current_.is_forced_gc = is_forced_gc;
  current_.marking_type = marking_type;
  gc_state_ = GarbageCollectionState::kMarking;
}
References cppgc::internal::StatsCollector::Event::collection_type, current_, DCHECK_IMPLIES, gc_state_, cppgc::internal::StatsCollector::Event::is_forced_gc, cppgc::internal::kMajor, kMarking, kNotRunning, kUnmarking, and cppgc::internal::StatsCollector::Event::marking_type.
Referenced by cppgc::internal::MarkerBase::StartMarking(), and cppgc::internal::HeapBase::Terminate().
NotifySafePointForConservativeCollection()
void cppgc::internal::StatsCollector::NotifySafePointForConservativeCollection ()
Definition at line 60 of file stats-collector.cc.
                                                              {
  if (std::abs(allocated_bytes_since_safepoint_ -
               explicitly_freed_bytes_since_safepoint_) >=
      static_cast<int64_t>(kAllocationThresholdBytes)) {
    AllocatedObjectSizeSafepointImpl();
  }
}
References allocated_bytes_since_safepoint_, AllocatedObjectSizeSafepointImpl(), explicitly_freed_bytes_since_safepoint_, and kAllocationThresholdBytes.
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint().
NotifySafePointForTesting()
void cppgc::internal::StatsCollector::NotifySafePointForTesting ()
Definition at line 68 of file stats-collector.cc.
                                               {
  AllocatedObjectSizeSafepointImpl();
}
References AllocatedObjectSizeSafepointImpl().
NotifySweepingCompleted()
void cppgc::internal::StatsCollector::NotifySweepingCompleted (SweepingType sweeping_type)
Definition at line 261 of file stats-collector.cc.
                                                                       {
  DCHECK_EQ(GarbageCollectionState::kSweeping, gc_state_);
  gc_state_ = GarbageCollectionState::kNotRunning;
  current_.sweeping_type = sweeping_type;
  previous_ = std::move(current_);
  current_ = Event();
  DCHECK_IMPLIES(previous_.marking_type == StatsCollector::MarkingType::kAtomic,
                 previous_.scope_data[kIncrementalMark].IsZero());
  DCHECK_IMPLIES(
      previous_.sweeping_type == StatsCollector::SweepingType::kAtomic,
      previous_.scope_data[kIncrementalSweep].IsZero());
  if (metric_recorder_) {
    MetricRecorder::GCCycle event = GetCycleEventForMetricRecorder(
        previous_.collection_type, previous_.marking_type,
        previous_.sweeping_type,
        previous_.scope_data[kAtomicMark].InMicroseconds(),
        previous_.scope_data[kAtomicWeak].InMicroseconds(),
        previous_.scope_data[kAtomicCompact].InMicroseconds(),
        previous_.scope_data[kAtomicSweep].InMicroseconds(),
        previous_.scope_data[kIncrementalMark].InMicroseconds(),
        previous_.scope_data[kIncrementalSweep].InMicroseconds(),
        previous_.concurrent_scope_data[kConcurrentMark],
        previous_.concurrent_scope_data[kConcurrentSweep],
        previous_.object_size_before_sweep_bytes /* objects_before */,
        marked_bytes_so_far_ /* objects_after */,
        previous_.object_size_before_sweep_bytes -
            marked_bytes_so_far_ /* objects_freed */,
        previous_.memory_size_before_sweep_bytes /* memory_before */,
        previous_.memory_size_before_sweep_bytes -
            memory_freed_bytes_since_end_of_marking_ /* memory_after */,
        memory_freed_bytes_since_end_of_marking_ /* memory_freed */);
    metric_recorder_->AddMainThreadEvent(event);
  }
}
References cppgc::internal::StatsCollector::Event::collection_type, cppgc::internal::StatsCollector::Event::concurrent_scope_data, current_, DCHECK_EQ, DCHECK_IMPLIES, gc_state_, cppgc::internal::anonymous_namespace{stats-collector.cc}::GetCycleEventForMetricRecorder(), v8::base::TimeDelta::InMicroseconds(), v8::base::TimeDelta::IsZero(), cppgc::Heap::kAtomic, kNotRunning, kSweeping, marked_bytes_so_far_, cppgc::internal::StatsCollector::Event::marking_type, memory_freed_bytes_since_end_of_marking_, cppgc::internal::StatsCollector::Event::memory_size_before_sweep_bytes, metric_recorder_, cppgc::internal::StatsCollector::Event::object_size_before_sweep_bytes, previous_, cppgc::internal::StatsCollector::Event::scope_data, and cppgc::internal::StatsCollector::Event::sweeping_type.
Referenced by cppgc::internal::Sweeper::SweeperImpl::NotifyDone().
NotifyUnmarkingStarted()
void cppgc::internal::StatsCollector::NotifyUnmarkingStarted (CollectionType collection_type)
Definition at line 110 of file stats-collector.cc.
                                                                          {
  DCHECK_EQ(GarbageCollectionState::kNotRunning, gc_state_);
  DCHECK_EQ(CollectionType::kMajor, collection_type);
  gc_state_ = GarbageCollectionState::kUnmarking;
}
References DCHECK_EQ, gc_state_, cppgc::internal::kMajor, kNotRunning, and kUnmarking.
Referenced by v8::internal::CppHeap::InitializeMarking(), and cppgc::internal::Heap::StartGarbageCollection().
operator=()
StatsCollector& cppgc::internal::StatsCollector::operator= (const StatsCollector &) [delete]
RecordHistogramSample() [1/2]
void cppgc::internal::StatsCollector::RecordHistogramSample (ConcurrentScopeId , v8::base::TimeDelta) [inline], [private]
Definition at line 349 of file stats-collector.h.
{}
RecordHistogramSample() [2/2]
void cppgc::internal::StatsCollector::RecordHistogramSample (ScopeId scope_id_, v8::base::TimeDelta time) [private]
Definition at line 384 of file stats-collector.cc.
                                                                 {
  switch (scope_id_) {
    case kIncrementalMark: {
      MetricRecorder::MainThreadIncrementalMark event{time.InMicroseconds()};
      metric_recorder_->AddMainThreadEvent(event);
      break;
    }
    case kIncrementalSweep: {
      MetricRecorder::MainThreadIncrementalSweep event{time.InMicroseconds()};
      metric_recorder_->AddMainThreadEvent(event);
      break;
    }
    default:
      break;
  }
}
References metric_recorder_, and time().
RegisterObserver()
void cppgc::internal::StatsCollector::RegisterObserver (AllocationObserver * observer)
Definition at line 26 of file stats-collector.cc.
                                                                  {
  DCHECK_EQ(allocation_observers_.end(),
            std::find(allocation_observers_.begin(),
                      allocation_observers_.end(), observer));
  allocation_observers_.push_back(observer);
}
References allocation_observers_, and DCHECK_EQ.
Referenced by v8::internal::CppHeap::CppHeap(), cppgc::internal::HeapGrowing::HeapGrowingImpl::HeapGrowingImpl(), v8::internal::MinorGCHeapGrowing::MinorGCHeapGrowing(), and cppgc::internal::MarkerBase::StartMarking().
ResetDiscardedMemory()
void cppgc::internal::StatsCollector::ResetDiscardedMemory ()
Definition at line 368 of file stats-collector.cc.
                                          {
  discarded_bytes_.store(0, std::memory_order_relaxed);
}
References discarded_bytes_.
Referenced by cppgc::internal::Sweeper::SweeperImpl::Start().
resident_memory_size()
size_t cppgc::internal::StatsCollector::resident_memory_size () const
Definition at line 376 of file stats-collector.cc.
                                                  {
  const auto allocated = allocated_memory_size();
  const auto discarded = discarded_memory_size();
  DCHECK_IMPLIES(allocated == 0, discarded == 0);
  DCHECK_IMPLIES(allocated > 0, allocated > discarded);
  return allocated - discarded;
}
References allocated_memory_size(), DCHECK_IMPLIES, and discarded_memory_size().
SetMetricRecorder()
void cppgc::internal::StatsCollector::SetMetricRecorder (std::unique_ptr< MetricRecorder > histogram_recorder) [inline]
Definition at line 334 of file stats-collector.h.
                                                                           {
    metric_recorder_ = std::move(histogram_recorder);
  }
UnregisterObserver()
void cppgc::internal::StatsCollector::UnregisterObserver (AllocationObserver * observer)
Definition at line 33 of file stats-collector.cc.
                                                                    {
  auto it = std::find(allocation_observers_.begin(),
                      allocation_observers_.end(), observer);
  DCHECK_NE(allocation_observers_.end(), it);
  *it = nullptr;
  allocation_observer_deleted_ = true;
}
References allocation_observer_deleted_, allocation_observers_, and DCHECK_NE.
Referenced by cppgc::internal::MarkerBase::EnterAtomicPause().
Member Data Documentation
allocated_bytes_since_end_of_marking_
int64_t cppgc::internal::StatsCollector::allocated_bytes_since_end_of_marking_ = 0 [private]
Definition at line 361 of file stats-collector.h.
Referenced by allocated_object_size(), AllocatedObjectSizeSafepointImpl(), GetRecentAllocationSpeedInBytesPerMs(), and NotifyMarkingCompleted().
allocated_bytes_since_safepoint_
int64_t cppgc::internal::StatsCollector::allocated_bytes_since_safepoint_ = 0 [private]
Definition at line 367 of file stats-collector.h.
Referenced by AllocatedObjectSizeSafepointImpl(), NotifyAllocation(), NotifyMarkingCompleted(), and NotifySafePointForConservativeCollection().
allocation_observer_deleted_
bool cppgc::internal::StatsCollector::allocation_observer_deleted_ = false [private]
Definition at line 385 of file stats-collector.h.
Referenced by ForAllAllocationObservers(), and UnregisterObserver().
allocation_observers_
std::vector<AllocationObserver*> cppgc::internal::StatsCollector::allocation_observers_ [private]
Definition at line 384 of file stats-collector.h.
Referenced by ForAllAllocationObservers(), RegisterObserver(), and UnregisterObserver().
current_
Event cppgc::internal::StatsCollector::current_ [private]
Definition at line 391 of file stats-collector.h.
Referenced by AllocatedObjectSizeSafepointImpl(), marked_bytes_on_current_cycle(), marking_time(), NotifyAllocatedMemory(), NotifyFreedMemory(), NotifyMarkingCompleted(), NotifyMarkingStarted(), and NotifySweepingCompleted().
discarded_bytes_
std::atomic<size_t> cppgc::internal::StatsCollector::discarded_bytes_ {0} [private]
Definition at line 380 of file stats-collector.h.
Referenced by DecrementDiscardedMemory(), discarded_memory_size(), IncrementDiscardedMemory(), and ResetDiscardedMemory().
explicitly_freed_bytes_since_safepoint_
int64_t cppgc::internal::StatsCollector::explicitly_freed_bytes_since_safepoint_ = 0 [private]
Definition at line 368 of file stats-collector.h.
Referenced by AllocatedObjectSizeSafepointImpl(), NotifyExplicitFree(), NotifyMarkingCompleted(), and NotifySafePointForConservativeCollection().
gc_state_
GarbageCollectionState cppgc::internal::StatsCollector::gc_state_ = GarbageCollectionState::kNotRunning [private]
Definition at line 387 of file stats-collector.h.
Referenced by marked_bytes(), marked_bytes_on_current_cycle(), marking_time(), NotifyMarkingCompleted(), NotifyMarkingStarted(), NotifySweepingCompleted(), and NotifyUnmarkingStarted().
kAllocationThresholdBytes
constexpr size_t cppgc::internal::StatsCollector::kAllocationThresholdBytes = 1024 [static], [constexpr]
Definition at line 272 of file stats-collector.h.
Referenced by NotifySafePointForConservativeCollection().
marked_bytes_so_far_
size_t cppgc::internal::StatsCollector::marked_bytes_so_far_ = 0 [private]
Definition at line 376 of file stats-collector.h.
Referenced by allocated_object_size(), marked_bytes(), NotifyMarkingCompleted(), and NotifySweepingCompleted().
memory_allocated_bytes_
int64_t cppgc::internal::StatsCollector::memory_allocated_bytes_ = 0 [private]
Definition at line 378 of file stats-collector.h.
Referenced by allocated_memory_size(), NotifyAllocatedMemory(), and NotifyMarkingCompleted().
memory_freed_bytes_since_end_of_marking_
int64_t cppgc::internal::StatsCollector::memory_freed_bytes_since_end_of_marking_ = 0 [private]
Definition at line 379 of file stats-collector.h.
Referenced by allocated_memory_size(), NotifyFreedMemory(), NotifyMarkingCompleted(), and NotifySweepingCompleted().
metric_recorder_
std::unique_ptr<MetricRecorder> cppgc::internal::StatsCollector::metric_recorder_ [private]
Definition at line 395 of file stats-collector.h.
Referenced by NotifySweepingCompleted(), and RecordHistogramSample().
platform_
Platform* cppgc::internal::StatsCollector::platform_ [private]
Definition at line 398 of file stats-collector.h.
Referenced by StatsCollector().
previous_
Event cppgc::internal::StatsCollector::previous_ [private]
Definition at line 393 of file stats-collector.h.
Referenced by marking_time(), and NotifySweepingCompleted().
time_of_last_end_of_marking_
v8::base::TimeTicks cppgc::internal::StatsCollector::time_of_last_end_of_marking_ = v8::base::TimeTicks::Now() [private]
Definition at line 362 of file stats-collector.h.
Referenced by GetRecentAllocationSpeedInBytesPerMs(), and NotifyMarkingCompleted().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/stats-collector.h
/mnt/V8SourceCode/src/heap/cppgc/stats-collector.cc