v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateJSAPIObjectWithEmbedderSlotsHeader (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
template<typename ConcreteType , typename ObjectVisitor >
static void IterateJSAPIObjectWithEmbedderSlotsTail (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
template<typename ConcreteType , typename ObjectVisitor >
static void IterateJSAPIObjectWithoutEmbedderSlotsTail (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
Static Public Attributes
static constexpr int kHeaderSize = JSSpecialObject::kHeaderSize
Additional Inherited Members
Detailed Description
Definition at line 120 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateJSAPIObjectWithEmbedderSlotsHeader()
template<typename ObjectVisitor >
static void v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithEmbedderSlotsHeader (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 124 of file objects-body-descriptors-inl.h.
                        {
    // Visit JSObject header.
    IteratePointers(obj, JSObject::kPropertiesOrHashOffset,
                    JSObject::kEndOfStrongFieldsOffset, v);
    // Visit JSAPIObjectWithEmbedderSlots or JSSpecialObject header.
    static_assert(JSObject::kEndOfStrongFieldsOffset ==
                  JSAPIObjectWithEmbedderSlots::kCppHeapWrappableOffset);
    static_assert(JSAPIObjectWithEmbedderSlots::kCppHeapWrappableOffset ==
                  JSSpecialObject::kCppHeapWrappableOffset);
    static_assert(JSAPIObjectWithEmbedderSlots::kCppHeapWrappableOffsetEnd +
                      1 ==
                  JSAPIObjectWithEmbedderSlots::kHeaderSize);
    v->VisitCppHeapPointer(
        obj, obj->RawCppHeapPointerField(
                 JSAPIObjectWithEmbedderSlots::kCppHeapWrappableOffset));
  }
References v8::internal::BodyDescriptorBase::IteratePointers(), and v8::internal::ObjectVisitor::VisitCppHeapPointer().
Referenced by v8::internal::JSAPIObjectWithEmbedderSlots::BodyDescriptor::IterateBody(), v8::internal::JSArrayBuffer::BodyDescriptor::IterateBody(), and v8::internal::JSArrayBufferView::BodyDescriptor::IterateBody().
IterateJSAPIObjectWithEmbedderSlotsTail()
template<typename ConcreteType , typename ObjectVisitor >
static void v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithEmbedderSlotsTail (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 145 of file objects-body-descriptors-inl.h.
                        {
    // Visit the tail of JSObject with possible embedder fields and in-object
    // properties. Note that embedder fields are processed in the JSObject base
    // class as there's other object hierarchies that contain embedder fields as
    // well.
    IterateJSObjectBodyImpl(map, obj, ConcreteType::kHeaderSize, object_size,
                            v);
  }
References v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl().
Referenced by v8::internal::JSAPIObjectWithEmbedderSlots::BodyDescriptor::IterateBody().
IterateJSAPIObjectWithoutEmbedderSlotsTail()
template<typename ConcreteType , typename ObjectVisitor >
static void v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithoutEmbedderSlotsTail (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 157 of file objects-body-descriptors-inl.h.
                        {
    IterateJSObjectBodyWithoutEmbedderFieldsImpl(
        map, obj, ConcreteType::kHeaderSize, object_size, v);
  }
References v8::internal::BodyDescriptorBase::IterateJSObjectBodyWithoutEmbedderFieldsImpl().
Member Data Documentation
kHeaderSize
constexpr int v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::kHeaderSize = JSSpecialObject::kHeaderSize [static], [constexpr]
Definition at line 164 of file objects-body-descriptors-inl.h.
Referenced by v8::internal::JSObject::GetHeaderSize().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h