v8::internal::maglev::VirtualObjectList Class Reference
#include <maglev-ir.h>
Classes
class Iterator
Public Member Functions
VirtualObjectList ()
bool operator== (const VirtualObjectList &other) const
void Add (VirtualObject *object)
bool is_empty () const
VirtualObject * FindAllocatedWith (const InlinedAllocation *allocation) const
void Print (std::ostream &os, const char *prefix, MaglevGraphLabeller *labeller) const
void Snapshot () const
bool IsSnapshot () const
Iterator begin () const
Iterator end () const
Static Public Member Functions
template<typename Function >
static VirtualObject * WalkUntilCommon (const VirtualObjectList &list1, const VirtualObjectList &list2, Function &&f)
Private Attributes
VirtualObject * head_
Detailed Description
Definition at line 6159 of file maglev-ir.h.
Constructor & Destructor Documentation
VirtualObjectList()
v8::internal::maglev::VirtualObjectList::VirtualObjectList () [inline]
Definition at line 6161 of file maglev-ir.h.
: head_(nullptr) {}
Member Function Documentation
Add()
void v8::internal::maglev::VirtualObjectList::Add (VirtualObject * object) [inline]
Definition at line 6188 of file maglev-ir.h.
                                  {
    DCHECK_NOT_NULL(object);
    DCHECK_NULL(object->next_);
    object->next_ = head_;
    head_ = object;
  }
References DCHECK_NOT_NULL, DCHECK_NULL, head_, and v8::internal::maglev::VirtualObject::next_.
Referenced by v8::internal::maglev::InterpreterFrameState::add_object(), and v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject().
begin()
Iterator v8::internal::maglev::VirtualObjectList::begin () const [inline]
Definition at line 6251 of file maglev-ir.h.
{ return Iterator(head_); }
References head_.
end()
Iterator v8::internal::maglev::VirtualObjectList::end () const [inline]
Definition at line 6252 of file maglev-ir.h.
{ return Iterator(nullptr); }
FindAllocatedWith()
VirtualObject* v8::internal::maglev::VirtualObjectList::FindAllocatedWith (const InlinedAllocation * allocation) const [inline]
Definition at line 6197 of file maglev-ir.h.
                                                                              {
    VirtualObject* result = nullptr;
    for (VirtualObject* vo : *this) {
      if (vo->allocation() == allocation) {
        result = vo;
        break;
      }
    }
    return result;
  }
References v8::internal::maglev::VirtualObject::allocation(), and v8::base::internal::result.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameSingleValue(), v8::internal::maglev::MaglevGraphBuilder::GetModifiableObjectFromAllocation(), v8::internal::maglev::MaglevGraphBuilder::GetObjectFromAllocation(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects(), and v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::VisitSingleFrame().
is_empty()
bool v8::internal::maglev::VirtualObjectList::is_empty () const [inline]
Definition at line 6195 of file maglev-ir.h.
{ return head_ == nullptr; }
References head_.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects().
IsSnapshot()
bool v8::internal::maglev::VirtualObjectList::IsSnapshot () const [inline]
Definition at line 6244 of file maglev-ir.h.
                          {
    for (VirtualObject* vo : *this) {
      if (!vo->IsSnapshot()) return false;
    }
    return true;
  }
References v8::internal::maglev::VirtualObject::IsSnapshot().
Referenced by Snapshot().
operator==()
bool v8::internal::maglev::VirtualObjectList::operator== (const VirtualObjectList & other) const [inline]
Definition at line 6184 of file maglev-ir.h.
                                                        {
    return head_ == other.head_;
  }
References head_.
Print()
void v8::internal::maglev::VirtualObjectList::Print (std::ostream & os, const char * prefix, MaglevGraphLabeller * labeller) const
Definition at line 330 of file maglev-ir.cc.
                                                                   {
  CHECK_NOT_NULL(labeller);
  os << prefix;
  for (const VirtualObject* vo : *this) {
    labeller->PrintNodeLabel(os, vo);
    os << "; ";
  }
  os << std::endl;
}
References CHECK_NOT_NULL, and v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel().
Referenced by v8::internal::maglev::MaglevGraphBuilder::PrintVirtualObjects(), and v8::internal::maglev::MergePointInterpreterFrameState::PrintVirtualObjects().
Snapshot()
void v8::internal::maglev::VirtualObjectList::Snapshot () const [inline]
Definition at line 6232 of file maglev-ir.h.
                        {
    for (VirtualObject* vo : *this) {
      if (vo->IsSnapshot()) {
        // Stop processing once a snapshotted object is found, as all remaining
        // objects must be snapshotted.
        break;
      }
      vo->Snapshot();
    }
    SLOW_DCHECK(IsSnapshot());
  }
References v8::internal::maglev::VirtualObject::IsSnapshot(), IsSnapshot(), SLOW_DCHECK, and v8::internal::maglev::VirtualObject::Snapshot().
Referenced by v8::internal::maglev::InterpreterFrameState::CopyFrom(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame(), v8::internal::maglev::MergePointInterpreterFrameState::InitializeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects(), and v8::internal::maglev::MergePointInterpreterFrameState::New().
WalkUntilCommon()
template<typename Function >
static VirtualObject* v8::internal::maglev::VirtualObjectList::WalkUntilCommon (const VirtualObjectList & list1, const VirtualObjectList & list2, Function && f) [inline], [static]
Definition at line 6213 of file maglev-ir.h.
                                                      {
    VirtualObject* vo1 = list1.head_;
    VirtualObject* vo2 = list2.head_;
    while (vo1 != nullptr && vo2 != nullptr && vo1 != vo2) {
      DCHECK_NE(vo1->id(), vo2->id());
      if (vo1->id() > vo2->id()) {
        f(vo1, list1);
        vo1 = vo1->next_;
      } else {
        f(vo2, list2);
        vo2 = vo2->next_;
      }
    }
    if (vo1 == vo2) return vo1;
    return nullptr;
  }
References DCHECK_NE, head_, v8::internal::maglev::VirtualObject::id(), and v8::internal::maglev::VirtualObject::next_.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects().
Member Data Documentation
head_
VirtualObject* v8::internal::maglev::VirtualObjectList::head_ [private]
Definition at line 6255 of file maglev-ir.h.
Referenced by Add(), begin(), is_empty(), operator==(), and WalkUntilCommon().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc