v8::internal::WasmMemoryMapDescriptor Class Reference
#include <wasm-objects.h>
Public Member Functions
V8_EXPORT_PRIVATE size_t MapDescriptor (DirectHandle< WasmMemoryObject > memory, size_t offset)
V8_EXPORT_PRIVATE bool UnmapDescriptor ()
Static Public Member Functions
static V8_EXPORT_PRIVATE MaybeDirectHandle< WasmMemoryMapDescriptor > NewFromAnonymous (Isolate *isolate, size_t length)
static V8_EXPORT_PRIVATE DirectHandle< WasmMemoryMapDescriptor > NewFromFileDescriptor (Isolate *isolate, v8::WasmMemoryMapDescriptor::WasmFileDescriptor file_descriptor)
Detailed Description
Definition at line 323 of file wasm-objects.h.
Member Function Documentation
MapDescriptor()
size_t v8::internal::WasmMemoryMapDescriptor::MapDescriptor (DirectHandle< WasmMemoryObject > memory, size_t offset)
Definition at line 1345 of file wasm-objects.cc.
                                                          {
#if V8_TARGET_OS_LINUX
  CHECK(v8_flags.experimental_wasm_memory_control);
  if (memory->array_buffer()->is_shared()) {
    // TODO(ahaas): Handle concurrent calls to `MapDescriptor`. To prevent
    // concurrency issues, we disable `MapDescriptor` for shared wasm memories
    // so far.
    return 0;
  }
  if (memory->is_memory64()) {
    // TODO(ahaas): Handle memory64. So far the offset in the
    // MemoryMapDescriptor is only an uint32. Either the offset has to be
    // interpreted as a wasm memory page, or be extended to an uint64.
    return 0;
  }
  uint8_t* target =
      reinterpret_cast<uint8_t*>(memory->array_buffer()->backing_store()) +
      offset;
  struct stat stat_for_size;
  if (fstat(this->file_descriptor(), &stat_for_size) == -1) {
    // Could not determine file size.
    return 0;
  }
  size_t size = RoundUp(stat_for_size.st_size,
                        GetArrayBufferPageAllocator()->AllocatePageSize());
  if (size + offset < size) {
    // Overflow
    return 0;
  }
  if (size + offset > memory->array_buffer()->GetByteLength()) {
    return 0;
  }
  void* ret_val = mmap(target, size, PROT_READ | PROT_WRITE,
                       MAP_FIXED | MAP_SHARED, this->file_descriptor(), 0);
  CHECK_NE(ret_val, MAP_FAILED);
  CHECK_EQ(ret_val, target);
  return size;
#else
  return 0;
#endif
}
References v8::internal::AllocatePageSize(), CHECK, CHECK_EQ, CHECK_NE, v8::internal::GetArrayBufferPageAllocator(), RoundUp(), size(), and v8::internal::v8_flags.
NewFromAnonymous()
MaybeDirectHandle< WasmMemoryMapDescriptor > v8::internal::WasmMemoryMapDescriptor::NewFromAnonymous (Isolate * isolate, size_t length) [static]
Definition at line 1304 of file wasm-objects.cc.
                                                                         {
#if V8_TARGET_OS_LINUX
  CHECK(v8_flags.experimental_wasm_memory_control);
  DirectHandle<JSFunction> descriptor_ctor(
      isolate->native_context()->wasm_memory_map_descriptor_constructor(),
      isolate);
  int file_descriptor = memfd_create("wasm_memory_map_descriptor", MFD_CLOEXEC);
  if (file_descriptor == -1) {
    return {};
  }
  int ret_val = ftruncate(file_descriptor, length);
  if (ret_val == -1) {
    return {};
  }
  return NewFromFileDescriptor(isolate, file_descriptor);
#else // V8_TARGET_OS_LINUX
  return {};
#endif // V8_TARGET_OS_LINUX
}
References CHECK, v8::internal::length, v8::internal::Isolate::native_context(), NewFromFileDescriptor(), and v8::internal::v8_flags.
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl().
NewFromFileDescriptor()
DirectHandle< WasmMemoryMapDescriptor > v8::internal::WasmMemoryMapDescriptor::NewFromFileDescriptor (Isolate * isolate, v8::WasmMemoryMapDescriptor::WasmFileDescriptor file_descriptor) [static]
Definition at line 1327 of file wasm-objects.cc.
                                                                    {
  CHECK(v8_flags.experimental_wasm_memory_control);
  DirectHandle<JSFunction> descriptor_ctor(
      isolate->native_context()->wasm_memory_map_descriptor_constructor(),
      isolate);
  auto descriptor_object = Cast<WasmMemoryMapDescriptor>(
      isolate->factory()->NewJSObject(descriptor_ctor, AllocationType::kOld));
  descriptor_object->set_file_descriptor(file_descriptor);
  descriptor_object->set_memory(ClearedValue(isolate));
  descriptor_object->set_offset(0);
  descriptor_object->set_size(0);
  return descriptor_object;
}
References CHECK, v8::internal::ClearedValue(), v8::internal::Isolate::factory(), v8::internal::kOld, v8::internal::Isolate::native_context(), v8::internal::Factory::NewJSObject(), and v8::internal::v8_flags.
Referenced by v8::WasmMemoryMapDescriptor::New(), and NewFromAnonymous().
UnmapDescriptor()
bool v8::internal::WasmMemoryMapDescriptor::UnmapDescriptor ()
Definition at line 1392 of file wasm-objects.cc.
                                              {
#if V8_TARGET_OS_LINUX
  CHECK(v8_flags.experimental_wasm_memory_control);
  DisallowGarbageCollection no_gc;
  i::Tagged<i::WasmMemoryObject> memory =
      Cast<i::WasmMemoryObject>(MakeStrong(this->memory()));
  if (memory.is_null()) {
    return true;
  }
  uint32_t offset = this->offset();
  uint32_t size = this->size();
  // The following checks already passed during `MapDescriptor`, and they should
  // still pass.
  CHECK(!memory->is_memory64());
  CHECK(!memory->array_buffer()->is_shared());
  CHECK_EQ(size % GetArrayBufferPageAllocator()->AllocatePageSize(), 0);
  CHECK_GE(size + offset, size);
  CHECK_LE(size + offset, memory->array_buffer()->byte_length());
  uint8_t* target =
      reinterpret_cast<uint8_t*>(memory->array_buffer()->backing_store()) +
      offset;
  void* ret_val = mmap(target, size, PROT_READ | PROT_WRITE,
                       MAP_FIXED | MAP_SHARED | MAP_ANONYMOUS, -1, 0);
  CHECK_NE(ret_val, MAP_FAILED);
  CHECK_EQ(ret_val, target);
  return true;
#else
  return false;
#endif
}
References v8::internal::AllocatePageSize(), CHECK, CHECK_EQ, CHECK_GE, CHECK_LE, CHECK_NE, v8::internal::GetArrayBufferPageAllocator(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::MakeStrong(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::v8_flags.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc