v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID Class Reference
Public Member Functions
DecodeSectionID (uint32_t module_offset)
base::Vector< uint8_t > buffer () override
bool is_finishing_allowed () const override
std::unique_ptr< DecodingState > Next (AsyncStreamingDecoder *streaming) override
Private Attributes
uint8_t id_ = 0
const uint32_t module_offset_
Detailed Description
Definition at line 452 of file streaming-decoder.cc.
Constructor & Destructor Documentation
DecodeSectionID()
v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::DecodeSectionID (uint32_t module_offset) [inline], [explicit]
Definition at line 454 of file streaming-decoder.cc.
      : module_offset_(module_offset) {}
Member Function Documentation
buffer()
base::Vector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::buffer () [inline], [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 457 of file streaming-decoder.cc.
{ return {&id_, 1}; }
is_finishing_allowed()
bool v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::is_finishing_allowed () const [inline], [override], [virtual]
Reimplemented from v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 458 of file streaming-decoder.cc.
{ return true; }
Next()
std::unique_ptr< AsyncStreamingDecoder::DecodingState > v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::Next (AsyncStreamingDecoder * streaming) [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 617 of file streaming-decoder.cc.
                                                                           {
  TRACE_STREAMING("DecodeSectionID: %u (%s)\n", id_,
                  SectionName(static_cast<SectionCode>(id_)));
  if (!IsValidSectionCode(id_)) return streaming->ToErrorState();
  if (id_ == SectionCode::kCodeSectionCode) {
    // Explicitly check for multiple code sections as module decoder never
    // sees the code section and hence cannot track this section.
    if (streaming->code_section_processed_) return streaming->ToErrorState();
    streaming->code_section_processed_ = true;
  }
  return std::make_unique<DecodeSectionLength>(id_, module_offset_);
}
References v8::internal::wasm::AsyncStreamingDecoder::code_section_processed_, v8::internal::wasm::IsValidSectionCode(), v8::internal::wasm::kCodeSectionCode, v8::internal::wasm::AsyncStreamingDecoder::module_offset_, v8::internal::wasm::SectionName(), v8::internal::wasm::AsyncStreamingDecoder::ToErrorState(), and TRACE_STREAMING.
Member Data Documentation
id_
uint8_t v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::id_ = 0 [private]
Definition at line 464 of file streaming-decoder.cc.
module_offset_
const uint32_t v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::module_offset_ [private]
Definition at line 466 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc