v8::internal::Processor Class Reference
Classes
class BreakableScope
Public Member Functions
Processor (uintptr_t stack_limit, DeclarationScope *closure_scope, Variable *result, AstValueFactory *ast_value_factory, Zone *zone)
void Process (ZonePtrList< Statement > *statements)
bool result_assigned () const
Zone * zone ()
DeclarationScope * closure_scope ()
AstNodeFactory * factory ()
Expression * SetResult (Expression *value)
Statement * AssignUndefinedBefore (Statement *s)
Private Member Functions
void VisitIterationStatement (IterationStatement *stmt)
DEFINE_AST_VISITOR_SUBCLASS_MEMBERS ()
Private Attributes
Variable * result_
Statement * replacement_
Zone * zone_
DeclarationScope * closure_scope_
AstNodeFactory factory_
bool result_assigned_
bool is_set_
bool breakable_
Additional Inherited Members
Detailed Description
Definition at line 25 of file rewriter.cc.
Constructor & Destructor Documentation
Processor()
v8::internal::Processor::Processor (uintptr_t stack_limit, DeclarationScope * closure_scope, Variable * result, AstValueFactory * ast_value_factory, Zone * zone) [inline]
Definition at line 27 of file rewriter.cc.
      : result_(result),
        replacement_(nullptr),
        zone_(zone),
        closure_scope_(closure_scope),
        factory_(ast_value_factory, zone),
        result_assigned_(false),
        is_set_(false),
        breakable_(false) {
    DCHECK_EQ(closure_scope, closure_scope->GetClosureScope());
    InitializeAstVisitor(stack_limit);
  }
References closure_scope(), DCHECK_EQ, and v8::internal::Scope::GetClosureScope().
Member Function Documentation
AssignUndefinedBefore()
Statement * v8::internal::Processor::AssignUndefinedBefore (Statement * s)
Definition at line 109 of file rewriter.cc.
                                                        {
  Expression* undef = factory()->NewUndefinedLiteral(kNoSourcePosition);
  Expression* assignment = SetResult(undef);
  Block* b = factory()->NewBlock(2, false);
  b->statements()->Add(
      factory()->NewExpressionStatement(assignment, kNoSourcePosition), zone());
  b->statements()->Add(s, zone());
  return b;
}
References factory(), v8::internal::kNoSourcePosition, v8::internal::AstNodeFactory::NewBlock(), v8::internal::AstNodeFactory::NewUndefinedLiteral(), SetResult(), v8::internal::Block::statements(), and zone().
Referenced by VisitIterationStatement().
closure_scope()
DeclarationScope* v8::internal::Processor::closure_scope () [inline]
Definition at line 45 of file rewriter.cc.
{ return closure_scope_; }
References closure_scope_.
Referenced by Processor().
DEFINE_AST_VISITOR_SUBCLASS_MEMBERS()
v8::internal::Processor::DEFINE_AST_VISITOR_SUBCLASS_MEMBERS () [private]
factory()
AstNodeFactory* v8::internal::Processor::factory () [inline]
Definition at line 46 of file rewriter.cc.
{ return &factory_; }
References factory_.
Referenced by AssignUndefinedBefore(), v8::internal::Rewriter::RewriteBody(), and SetResult().
Process()
void v8::internal::Processor::Process (ZonePtrList< Statement > * statements)
Definition at line 119 of file rewriter.cc.
                                                          {
  // If we're in a breakable scope (named block, iteration, or switch), we walk
  // all statements. The last value producing statement before the break needs
  // to assign to .result. If we're not in a breakable scope, only the last
  // value producing statement in the block assigns to .result, so we can stop
  // early.
  for (int i = statements->length() - 1; i >= 0 && (breakable_ || !is_set_);
       --i) {
    Visit(statements->at(i));
    statements->Set(i, replacement_);
  }
}
References v8::internal::ZoneList< T >::at(), breakable_, is_set_, v8::internal::ZoneList< T >::length(), replacement_, v8::internal::ZoneList< T >::Set(), and v8::internal::AstVisitor< Processor >::Visit().
Referenced by v8::internal::Rewriter::RewriteBody().
result_assigned()
bool v8::internal::Processor::result_assigned () const [inline]
Definition at line 42 of file rewriter.cc.
{ return result_assigned_; }
References result_assigned_.
Referenced by v8::internal::Rewriter::RewriteBody().
SetResult()
Expression* v8::internal::Processor::SetResult (Expression * value) [inline]
Definition at line 49 of file rewriter.cc.
                                           {
    result_assigned_ = true;
    VariableProxy* result_proxy = factory()->NewVariableProxy(result_);
    return factory()->NewAssignment(Token::kAssign, result_proxy, value,
                                    kNoSourcePosition);
  }
References factory(), v8::internal::kNoSourcePosition, v8::internal::AstNodeFactory::NewAssignment(), v8::internal::AstNodeFactory::NewVariableProxy(), result_, result_assigned_, and v8::internal::value.
Referenced by AssignUndefinedBefore().
VisitIterationStatement()
void v8::internal::Processor::VisitIterationStatement (IterationStatement * stmt) [private]
Definition at line 177 of file rewriter.cc.
                                                                {
  // The statement may have to produce a value, so always assign undefined
  // before.
  // TODO(verwaest): Omit it if we know that there's no break/continue leaving
  // it early.
  DCHECK(breakable_ || !is_set_);
  BreakableScope scope(this);
  Visit(node->body());
  node->set_body(replacement_);
  replacement_ = AssignUndefinedBefore(node);
  is_set_ = true;
}
References AssignUndefinedBefore(), v8::internal::IterationStatement::body(), breakable_, v8::internal::DCHECK(), is_set_, replacement_, v8::internal::IterationStatement::set_body(), and v8::internal::AstVisitor< Processor >::Visit().
zone()
Zone* v8::internal::Processor::zone () [inline]
Definition at line 44 of file rewriter.cc.
{ return zone_; }
References zone_.
Referenced by AssignUndefinedBefore().
Member Data Documentation
breakable_
bool v8::internal::Processor::breakable_ [private]
Definition at line 105 of file rewriter.cc.
Referenced by v8::internal::Processor::BreakableScope::BreakableScope(), Process(), and VisitIterationStatement().
closure_scope_
DeclarationScope* v8::internal::Processor::closure_scope_ [private]
Definition at line 81 of file rewriter.cc.
Referenced by closure_scope().
factory_
AstNodeFactory v8::internal::Processor::factory_ [private]
Definition at line 82 of file rewriter.cc.
Referenced by factory().
is_set_
bool v8::internal::Processor::is_set_ [private]
Definition at line 103 of file rewriter.cc.
Referenced by Process(), and VisitIterationStatement().
replacement_
Statement* v8::internal::Processor::replacement_ [private]
Definition at line 64 of file rewriter.cc.
Referenced by Process(), and VisitIterationStatement().
result_
Variable* v8::internal::Processor::result_ [private]
Definition at line 60 of file rewriter.cc.
Referenced by SetResult().
result_assigned_
bool v8::internal::Processor::result_assigned_ [private]
Definition at line 97 of file rewriter.cc.
Referenced by result_assigned(), and SetResult().
zone_
Zone* v8::internal::Processor::zone_ [private]
Definition at line 80 of file rewriter.cc.
Referenced by zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/rewriter.cc