v8::internal::ConditionalChainSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
ConditionalChainSourceRanges (Zone *zone)
SourceRange GetRangeAtIndex (SourceRangeKind kind, size_t index)
void AddThenRanges (const SourceRange &range)
void AddElseRange (const SourceRange &else_range)
size_t RangeCount () const
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
Private Attributes
ZoneVector< SourceRange > then_ranges_
ZoneVector< SourceRange > else_ranges_
Detailed Description
Definition at line 146 of file ast-source-ranges.h.
Constructor & Destructor Documentation
ConditionalChainSourceRanges()
v8::internal::ConditionalChainSourceRanges::ConditionalChainSourceRanges (Zone * zone) [inline], [explicit]
Definition at line 148 of file ast-source-ranges.h.
      : then_ranges_(zone), else_ranges_(zone) {}
Member Function Documentation
AddElseRange()
void v8::internal::ConditionalChainSourceRanges::AddElseRange (const SourceRange & else_range) [inline]
Definition at line 165 of file ast-source-ranges.h.
                                                   {
    else_ranges_.push_back(else_range);
  }
References else_ranges_.
Referenced by v8::internal::Parser::AppendConditionalChainElseSourceRange().
AddThenRanges()
void v8::internal::ConditionalChainSourceRanges::AddThenRanges (const SourceRange & range) [inline]
Definition at line 161 of file ast-source-ranges.h.
                                               {
    then_ranges_.push_back(range);
  }
References then_ranges_.
Referenced by v8::internal::Parser::AppendConditionalChainSourceRange().
GetRange()
SourceRange v8::internal::ConditionalChainSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 171 of file ast-source-ranges.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
GetRangeAtIndex()
SourceRange v8::internal::ConditionalChainSourceRanges::GetRangeAtIndex (SourceRangeKind kind, size_t index) [inline]
Definition at line 151 of file ast-source-ranges.h.
                                                                  {
    if (kind == SourceRangeKind::kThen) {
      DCHECK_LT(index, then_ranges_.size());
      return then_ranges_[index];
    }
    DCHECK_EQ(kind, SourceRangeKind::kElse);
    DCHECK_LT(index, else_ranges_.size());
    return else_ranges_[index];
  }
References DCHECK_EQ, DCHECK_LT, else_ranges_, v8::internal::index, v8::internal::kElse, v8::internal::kThen, and then_ranges_.
Referenced by v8::internal::interpreter::BlockCoverageBuilder::AllocateConditionalChainBlockCoverageSlot().
HasRange()
bool v8::internal::ConditionalChainSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 172 of file ast-source-ranges.h.
{ return false; }
RangeCount()
size_t v8::internal::ConditionalChainSourceRanges::RangeCount () const [inline]
Definition at line 169 of file ast-source-ranges.h.
{ return then_ranges_.size(); }
References then_ranges_.
Referenced by v8::internal::Parser::AppendConditionalChainSourceRange().
Member Data Documentation
else_ranges_
ZoneVector<SourceRange> v8::internal::ConditionalChainSourceRanges::else_ranges_ [private]
Definition at line 176 of file ast-source-ranges.h.
Referenced by AddElseRange(), and GetRangeAtIndex().
then_ranges_
ZoneVector<SourceRange> v8::internal::ConditionalChainSourceRanges::then_ranges_ [private]
Definition at line 175 of file ast-source-ranges.h.
Referenced by AddThenRanges(), GetRangeAtIndex(), and RangeCount().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h