v8::Set Class Reference
An instance of the built-in Set constructor (ECMA-262, 6th Edition, 23.2.1).
#include <v8-container.h>
Public Member Functions
size_t Size () const
void Clear ()
V8_WARN_UNUSED_RESULT MaybeLocal< Set > Add (Local< Context > context, Local< Value > key)
V8_WARN_UNUSED_RESULT Maybe< bool > Has (Local< Context > context, Local< Value > key)
V8_WARN_UNUSED_RESULT Maybe< bool > Delete (Local< Context > context, Local< Value > key)
Local< Array > AsArray () const
Returns an array of the keys in this Set.
Static Public Member Functions
static Local< Set > New (Isolate *isolate)
Creates a new empty Set.
static Set * Cast (Value *value)
Private Member Functions
Set ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of the built-in Set constructor (ECMA-262, 6th Edition, 23.2.1).
Definition at line 148 of file v8-container.h.
Constructor & Destructor Documentation
Set()
v8::Set::Set () [private]
Member Function Documentation
Add()
MaybeLocal< Set > v8::Set::Add (Local< Context > context, Local< Value > key)
Definition at line 8529 of file api.cc.
                                                                 {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Set_Add};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*key)};
  return api_scope.EscapeMaybe(i::Cast<i::JSSet>(i::Execution::CallBuiltin(
      i_isolate, i_isolate->set_add(), self, base::VectorOf(args))));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::key, v8::Utils::OpenDirectHandle(), and v8::base::VectorOf().
AsArray()
Local< Array > v8::Set::AsArray () const
Returns an array of the keys in this Set.
Definition at line 8600 of file api.cc.
                                {
  auto obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Set_AsArray);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return Utils::ToLocal(
      SetAsArray(i_isolate, obj->table(), 0, SetAsArrayKind::kValues));
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), and v8::anonymous_namespace{api.cc}::SetAsArray().
Referenced by v8::Object::PreviewEntries().
Cast()
static Set* v8::Set::Cast (Value * value) [inline], [static]
Definition at line 169 of file v8-container.h.
                                           {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<Set*>(value);
  }
References v8::internal::value.
Referenced by v8::Object::PreviewEntries().
CheckCast()
void v8::Set::CheckCast (Value * obj) [static], [private]
Definition at line 3972 of file api.cc.
                                 {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSSet(*obj), "v8_Set_Cast", "Value is not a Set");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Clear()
void v8::Set::Clear ()
Definition at line 8521 of file api.cc.
                {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Set_Clear);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::JSSet::Clear(i_isolate, self);
}
References v8::internal::JSSet::Clear(), v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
Delete()
Maybe< bool > v8::Set::Delete (Local< Context > context, Local< Value > key)
Definition at line 8552 of file api.cc.
                                                                {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Set_Delete};
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> result;
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*key)};
  if (!i::Execution::CallBuiltin(i_isolate, i_isolate->set_delete(), self,
                                 base::VectorOf(args))
           .ToHandle(&result)) {
    return {};
  }
  return Just(i::IsTrue(*result, i_isolate));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::Isolate::Current(), v8::Just(), v8::internal::key, v8::Utils::OpenDirectHandle(), v8::base::internal::result, and v8::base::VectorOf().
Has()
Maybe< bool > v8::Set::Has (Local< Context > context, Local< Value > key)
Definition at line 8538 of file api.cc.
                                                             {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Set_Has};
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> result;
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*key)};
  if (!i::Execution::CallBuiltin(i_isolate, i_isolate->set_has(), self,
                                 base::VectorOf(args))
           .ToHandle(&result)) {
    return {};
  }
  return Just(i::IsTrue(*result, i_isolate));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::Isolate::Current(), v8::Just(), v8::internal::key, v8::Utils::OpenDirectHandle(), v8::base::internal::result, and v8::base::VectorOf().
New()
Local< v8::Set > v8::Set::New (Isolate * isolate) [static]
Creates a new empty Set.
Definition at line 8508 of file api.cc.
                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Set_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::JSSet> obj = i_isolate->factory()->NewJSSet();
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewJSSet().
Referenced by v8_inspector::ValueMirror::getProperties().
Size()
size_t v8::Set::Size () const
Definition at line 8516 of file api.cc.
                         {
  auto obj = Utils::OpenDirectHandle(this);
  return i::Cast<i::OrderedHashSet>(obj->table())->NumberOfElements();
}
References v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-container.h
/mnt/V8SourceCode/src/api/api.cc