v8::internal::BinaryOperation Class Reference
#include <ast.h>
Public Member Functions
Token::Value op () const
Expression * left () const
Expression * right () const
void UpdateRight (Expression *expr)
bool IsSmiLiteralOperation (Expression **subexpr, Tagged< Smi > *literal)
Private Types
using OperatorField = Expression::NextBitField< Token::Value, 7 >
Private Member Functions
BinaryOperation (Token::Value op, Expression *left, Expression *right, int pos)
Private Attributes
friend Zone
Expression * left_
Expression * right_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1904 of file ast.h.
Member Typedef Documentation
OperatorField
using v8::internal::BinaryOperation::OperatorField = Expression::NextBitField<Token::Value, 7> [private]
Definition at line 1929 of file ast.h.
Constructor & Destructor Documentation
BinaryOperation()
v8::internal::BinaryOperation::BinaryOperation (Token::Value op, Expression * left, Expression * right, int pos) [inline], [private]
Definition at line 1920 of file ast.h.
      : Expression(pos, kBinaryOperation), left_(left), right_(right) {
    bit_field_ |= OperatorField::encode(op);
    DCHECK(Token::IsBinaryOp(op));
  }
References v8::internal::AstNode::bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Token::IsBinaryOp(), and op().
Member Function Documentation
IsSmiLiteralOperation()
bool v8::internal::BinaryOperation::IsSmiLiteralOperation (Expression ** subexpr, Tagged< Smi > * literal)
Definition at line 876 of file ast.cc.
                                                                  {
  return MatchSmiLiteralOperation(left_, right_, subexpr, literal) ||
         (IsCommutativeOperationWithSmiLiteral(op()) &&
          MatchSmiLiteralOperation(right_, left_, subexpr, literal));
}
References v8::internal::IsCommutativeOperationWithSmiLiteral(), left_, v8::internal::MatchSmiLiteralOperation(), op(), and right_.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression().
left()
Expression* v8::internal::BinaryOperation::left () const [inline]
Definition at line 1907 of file ast.h.
{ return left_; }
References left_.
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), v8::internal::Parser::CollapseNaryExpression(), v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression(), v8::internal::interpreter::BytecodeGenerator::VisitCommaExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression().
op()
Token::Value v8::internal::BinaryOperation::op () const [inline]
Definition at line 1906 of file ast.h.
{ return OperatorField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), BinaryOperation(), v8::internal::Parser::CollapseNaryExpression(), IsSmiLiteralOperation(), and v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression().
right()
Expression* v8::internal::BinaryOperation::right () const [inline]
Definition at line 1908 of file ast.h.
{ return right_; }
References right_.
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), v8::internal::Parser::CollapseNaryExpression(), v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression(), v8::internal::interpreter::BytecodeGenerator::VisitCommaExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression().
UpdateRight()
void v8::internal::BinaryOperation::UpdateRight (Expression * expr) [inline]
Definition at line 1910 of file ast.h.
{ right_ = expr; }
References right_.
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1917 of file ast.h.
Member Data Documentation
left_
Expression* v8::internal::BinaryOperation::left_ [private]
Definition at line 1926 of file ast.h.
Referenced by IsSmiLiteralOperation(), and left().
right_
Expression* v8::internal::BinaryOperation::right_ [private]
Definition at line 1927 of file ast.h.
Referenced by IsSmiLiteralOperation(), right(), and UpdateRight().
Zone
friend v8::internal::BinaryOperation::Zone [private]
Definition at line 1918 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc