v8::internal::wasm::WasmImportWrapperHandle Class Reference
#include <wasm-import-wrapper-cache.h>
Public Member Functions
WasmImportWrapperHandle (Address addr, uint64_t signature_hash)
WasmImportWrapperHandle (WasmCode *code, Address addr, uint64_t signature_hash)
WasmImportWrapperHandle (const WasmImportWrapperHandle &)=delete
WasmImportWrapperHandle & operator= (const WasmImportWrapperHandle &)=delete
~WasmImportWrapperHandle ()
WasmCodePointer code_pointer () const
const WasmCode & code () const
bool has_code () const
Private Member Functions
void set_code (WasmCode *code)
Private Attributes
const WasmCodePointer code_pointer_
std::atomic< WasmCode * > code_ = nullptr
Friends
class WasmImportWrapperCache::ModificationScope
Detailed Description
Definition at line 124 of file wasm-import-wrapper-cache.h.
Constructor & Destructor Documentation
WasmImportWrapperHandle() [1/3]
v8::internal::wasm::WasmImportWrapperHandle::WasmImportWrapperHandle (Address addr, uint64_t signature_hash)
Definition at line 31 of file wasm-import-wrapper-cache.cc.
    : code_pointer_(
          GetProcessWideWasmCodePointerTable()->AllocateAndInitializeEntry(
              addr, signature_hash)) {}
WasmImportWrapperHandle() [2/3]
v8::internal::wasm::WasmImportWrapperHandle::WasmImportWrapperHandle (WasmCode * code, Address addr, uint64_t signature_hash)
Definition at line 22 of file wasm-import-wrapper-cache.cc.
    : code_pointer_(
          GetProcessWideWasmCodePointerTable()->AllocateAndInitializeEntry(
              addr, signature_hash)),
      code_(code) {
  if (code) code->IncRef();
}
References code(), and v8::internal::wasm::WasmCode::IncRef().
WasmImportWrapperHandle() [3/3]
v8::internal::wasm::WasmImportWrapperHandle::WasmImportWrapperHandle (const WasmImportWrapperHandle &) [delete]
 WasmImportWrapperHandle()
v8::internal::wasm::WasmImportWrapperHandle::~WasmImportWrapperHandle ()
Definition at line 37 of file wasm-import-wrapper-cache.cc.
                                                  {
  WasmCode* wasm_code = code_.load(std::memory_order_relaxed);
  if (wasm_code) {
    bool should_free = wasm_code->DecRef();
    USE(should_free);
    DCHECK(!should_free);
  }
  GetProcessWideWasmCodePointerTable()->FreeEntry(code_pointer_);
}
References code_, code_pointer_, v8::internal::DCHECK(), v8::internal::wasm::WasmCode::DecRef(), v8::internal::wasm::WasmCodePointerTable::FreeEntry(), v8::internal::wasm::GetProcessWideWasmCodePointerTable(), and USE.
Member Function Documentation
code()
const WasmCode& v8::internal::wasm::WasmImportWrapperHandle::code () const [inline]
Definition at line 135 of file wasm-import-wrapper-cache.h.
                               {
    return *code_.load(std::memory_order_relaxed);
  }
References code_.
Referenced by set_code(), and WasmImportWrapperHandle().
code_pointer()
WasmCodePointer v8::internal::wasm::WasmImportWrapperHandle::code_pointer () const [inline]
Definition at line 134 of file wasm-import-wrapper-cache.h.
{ return code_pointer_; }
References code_pointer_.
has_code()
bool v8::internal::wasm::WasmImportWrapperHandle::has_code () const [inline]
Definition at line 138 of file wasm-import-wrapper-cache.h.
                        {
    return code_.load(std::memory_order_relaxed) != nullptr;
  }
References code_.
Referenced by set_code().
operator=()
WasmImportWrapperHandle& v8::internal::wasm::WasmImportWrapperHandle::operator= (const WasmImportWrapperHandle &) [delete]
set_code()
void v8::internal::wasm::WasmImportWrapperHandle::set_code (WasmCode * code) [private]
Definition at line 47 of file wasm-import-wrapper-cache.cc.
                                                     {
  GetWasmImportWrapperCache()->mutex_.AssertHeld();
  // We're taking ownership of a WasmCode object that has just been allocated
  // and should have a refcount of 1.
  code->DcheckRefCountIsOne();
  DCHECK(!has_code());
  code_.store(code, std::memory_order_relaxed);
}
References v8::base::Mutex::AssertHeld(), code(), code_, v8::internal::DCHECK(), v8::internal::wasm::WasmCode::DcheckRefCountIsOne(), v8::internal::wasm::GetWasmImportWrapperCache(), has_code(), and v8::internal::wasm::WasmImportWrapperCache::mutex_.
Friends And Related Function Documentation
WasmImportWrapperCache::ModificationScope
friend class WasmImportWrapperCache::ModificationScope [friend]
Definition at line 148 of file wasm-import-wrapper-cache.h.
Member Data Documentation
code_
std::atomic<WasmCode*> v8::internal::wasm::WasmImportWrapperHandle::code_ = nullptr [private]
Definition at line 146 of file wasm-import-wrapper-cache.h.
Referenced by code(), has_code(), set_code(), and ~WasmImportWrapperHandle().
code_pointer_
const WasmCodePointer v8::internal::wasm::WasmImportWrapperHandle::code_pointer_ [private]
Definition at line 145 of file wasm-import-wrapper-cache.h.
Referenced by code_pointer(), and ~WasmImportWrapperHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-import-wrapper-cache.h
/mnt/V8SourceCode/src/wasm/wasm-import-wrapper-cache.cc