v8::internal::ClassLiteral Class Reference
#include <ast.h>
Public Types
using Property = ClassLiteralProperty
using StaticElement = ClassLiteralStaticElement
Public Member Functions
ClassScope * scope () const
Expression * extends () const
FunctionLiteral * constructor () const
ZonePtrList< Property > * public_members () const
ZonePtrList< Property > * private_members () const
int start_position () const
int end_position () const
bool has_static_computed_names () const
bool is_anonymous_expression () const
bool IsAnonymousFunctionDefinition () const
FunctionLiteral * static_initializer () const
FunctionLiteral * instance_members_initializer_function () const
Variable * home_object () const
Variable * static_home_object () const
Private Types
using HasStaticComputedNames = Expression::NextBitField< bool, 1 >
using IsAnonymousExpression = HasStaticComputedNames::Next< bool, 1 >
Private Member Functions
ClassLiteral (ClassScope *scope, Expression *extends, FunctionLiteral *constructor, ZonePtrList< Property > *public_members, ZonePtrList< Property > *private_members, FunctionLiteral *static_initializer, FunctionLiteral *instance_members_initializer_function, int start_position, int end_position, bool has_static_computed_names, bool is_anonymous, Variable *home_object, Variable *static_home_object)
Private Attributes
friend Zone
int end_position_
ClassScope * scope_
Expression * extends_
FunctionLiteral * constructor_
ZonePtrList< Property > * public_members_
ZonePtrList< Property > * private_members_
FunctionLiteral * static_initializer_
FunctionLiteral * instance_members_initializer_function_
Variable * home_object_
Variable * static_home_object_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 2700 of file ast.h.
Member Typedef Documentation
HasStaticComputedNames
using v8::internal::ClassLiteral::HasStaticComputedNames = Expression::NextBitField<bool, 1> [private]
Definition at line 2770 of file ast.h.
IsAnonymousExpression
using v8::internal::ClassLiteral::IsAnonymousExpression = HasStaticComputedNames::Next<bool, 1> [private]
Definition at line 2771 of file ast.h.
Property
using v8::internal::ClassLiteral::Property = ClassLiteralProperty
Definition at line 2702 of file ast.h.
StaticElement
using v8::internal::ClassLiteral::StaticElement = ClassLiteralStaticElement
Definition at line 2703 of file ast.h.
Constructor & Destructor Documentation
ClassLiteral()
v8::internal::ClassLiteral::ClassLiteral (ClassScope * scope, Expression * extends, FunctionLiteral * constructor, ZonePtrList< Property > * public_members, ZonePtrList< Property > * private_members, FunctionLiteral * static_initializer, FunctionLiteral * instance_members_initializer_function, int start_position, int end_position, bool has_static_computed_names, bool is_anonymous, Variable * home_object, Variable * static_home_object) [inline], [private]
Definition at line 2737 of file ast.h.
      : Expression(start_position, kClassLiteral),
        end_position_(end_position),
        scope_(scope),
        extends_(extends),
        constructor_(constructor),
        public_members_(public_members),
        private_members_(private_members),
        static_initializer_(static_initializer),
        instance_members_initializer_function_(
            instance_members_initializer_function),
        home_object_(home_object),
        static_home_object_(static_home_object) {
    bit_field_ |= HasStaticComputedNames::encode(has_static_computed_names) |
                  IsAnonymousExpression::encode(is_anonymous);
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::encode(), and has_static_computed_names().
Member Function Documentation
constructor()
FunctionLiteral* v8::internal::ClassLiteral::constructor () const [inline]
Definition at line 2707 of file ast.h.
{ return constructor_; }
References constructor_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
end_position()
int v8::internal::ClassLiteral::end_position () const [inline]
Definition at line 2711 of file ast.h.
{ return end_position_; }
References end_position_.
Referenced by v8::internal::ClassBoilerplate::New().
extends()
Expression* v8::internal::ClassLiteral::extends () const [inline]
Definition at line 2706 of file ast.h.
{ return extends_; }
References extends_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
has_static_computed_names()
bool v8::internal::ClassLiteral::has_static_computed_names () const [inline]
Definition at line 2712 of file ast.h.
                                         {
    return HasStaticComputedNames::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by ClassLiteral().
home_object()
Variable* v8::internal::ClassLiteral::home_object () const [inline]
Definition at line 2729 of file ast.h.
{ return home_object_; }
References home_object_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral().
instance_members_initializer_function()
FunctionLiteral* v8::internal::ClassLiteral::instance_members_initializer_function () const [inline]
Definition at line 2725 of file ast.h.
                                                                 {
    return instance_members_initializer_function_;
  }
References instance_members_initializer_function_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
is_anonymous_expression()
bool v8::internal::ClassLiteral::is_anonymous_expression () const [inline]
Definition at line 2716 of file ast.h.
                                       {
    return IsAnonymousExpression::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by IsAnonymousFunctionDefinition().
IsAnonymousFunctionDefinition()
bool v8::internal::ClassLiteral::IsAnonymousFunctionDefinition () const [inline]
Definition at line 2719 of file ast.h.
                                             {
    return is_anonymous_expression();
  }
References is_anonymous_expression().
private_members()
ZonePtrList<Property>* v8::internal::ClassLiteral::private_members () const [inline]
Definition at line 2709 of file ast.h.
{ return private_members_; }
References private_members_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
public_members()
ZonePtrList<Property>* v8::internal::ClassLiteral::public_members () const [inline]
Definition at line 2708 of file ast.h.
{ return public_members_; }
References public_members_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::ClassBoilerplate::New(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
scope()
ClassScope* v8::internal::ClassLiteral::scope () const [inline]
Definition at line 2705 of file ast.h.
{ return scope_; }
References scope_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral().
start_position()
int v8::internal::ClassLiteral::start_position () const [inline]
Definition at line 2710 of file ast.h.
{ return position(); }
References v8::internal::AstNode::position().
Referenced by v8::internal::ClassBoilerplate::New().
static_home_object()
Variable* v8::internal::ClassLiteral::static_home_object () const [inline]
Definition at line 2731 of file ast.h.
{ return static_home_object_; }
References static_home_object_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral().
static_initializer()
FunctionLiteral* v8::internal::ClassLiteral::static_initializer () const [inline]
Definition at line 2723 of file ast.h.
{ return static_initializer_; }
References static_initializer_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2734 of file ast.h.
Member Data Documentation
constructor_
FunctionLiteral* v8::internal::ClassLiteral::constructor_ [private]
Definition at line 2765 of file ast.h.
Referenced by constructor().
end_position_
int v8::internal::ClassLiteral::end_position_ [private]
Definition at line 2762 of file ast.h.
Referenced by end_position().
extends_
Expression* v8::internal::ClassLiteral::extends_ [private]
Definition at line 2764 of file ast.h.
Referenced by extends().
home_object_
Variable* v8::internal::ClassLiteral::home_object_ [private]
Definition at line 2772 of file ast.h.
Referenced by home_object().
instance_members_initializer_function_
FunctionLiteral* v8::internal::ClassLiteral::instance_members_initializer_function_ [private]
Definition at line 2769 of file ast.h.
Referenced by instance_members_initializer_function().
private_members_
ZonePtrList<Property>* v8::internal::ClassLiteral::private_members_ [private]
Definition at line 2767 of file ast.h.
Referenced by private_members().
public_members_
ZonePtrList<Property>* v8::internal::ClassLiteral::public_members_ [private]
Definition at line 2766 of file ast.h.
Referenced by public_members().
scope_
ClassScope* v8::internal::ClassLiteral::scope_ [private]
Definition at line 2763 of file ast.h.
Referenced by scope().
static_home_object_
Variable* v8::internal::ClassLiteral::static_home_object_ [private]
Definition at line 2773 of file ast.h.
Referenced by static_home_object().
static_initializer_
FunctionLiteral* v8::internal::ClassLiteral::static_initializer_ [private]
Definition at line 2768 of file ast.h.
Referenced by static_initializer().
Zone
friend v8::internal::ClassLiteral::Zone [private]
Definition at line 2735 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h