v8::internal::PageEvacuationJob Class Reference
Public Member Functions
PageEvacuationJob (Isolate *isolate, MarkCompactCollector *collector, std::vector< std::unique_ptr< Evacuator >> *evacuators, std::vector< std::pair< ParallelWorkItem, MutablePageMetadata * >> evacuation_items)
void Run (JobDelegate *delegate) override
void ProcessItems (JobDelegate *delegate, Evacuator *evacuator)
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
uint64_t trace_id () const
Private Attributes
MarkCompactCollector * collector_
std::vector< std::unique_ptr< Evacuator > > * evacuators_
std::vector< std::pair< ParallelWorkItem, MutablePageMetadata * > > evacuation_items_
std::atomic< size_t > remaining_evacuation_items_ {0}
IndexGenerator generator_
GCTracer * tracer_
const uint64_t trace_id_
Detailed Description
Definition at line 4689 of file mark-compact.cc.
Constructor & Destructor Documentation
PageEvacuationJob()
v8::internal::PageEvacuationJob::PageEvacuationJob (Isolate * isolate, MarkCompactCollector * collector, std::vector< std::unique_ptr< Evacuator >> * evacuators, std::vector< std::pair< ParallelWorkItem, MutablePageMetadata * >> evacuation_items) [inline]
Definition at line 4691 of file mark-compact.cc.
      : collector_(collector),
        evacuators_(evacuators),
        evacuation_items_(std::move(evacuation_items)),
        remaining_evacuation_items_(evacuation_items_.size()),
        generator_(evacuation_items_.size()),
        tracer_(isolate->heap()->tracer()),
        trace_id_(reinterpret_cast<uint64_t>(this) ^
                  tracer_->CurrentEpoch(GCTracer::Scope::MC_EVACUATE)) {}
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::PageEvacuationJob::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 4739 of file mark-compact.cc.
                                                               {
    const size_t kItemsPerWorker = std::max(1, MB / PageMetadata::kPageSize);
    // Ceiling division to ensure enough workers for all
    // |remaining_evacuation_items_|
    size_t wanted_num_workers =
        (remaining_evacuation_items_.load(std::memory_order_relaxed) +
         kItemsPerWorker - 1) /
        kItemsPerWorker;
    wanted_num_workers =
        std::min<size_t>(wanted_num_workers, evacuators_->size());
    if (!collector_->UseBackgroundThreadsInCycle()) {
      return std::min<size_t>(wanted_num_workers, 1);
    }
    return wanted_num_workers;
  }
References cppgc::internal::kPageSize, and MB.
ProcessItems()
void v8::internal::PageEvacuationJob::ProcessItems (JobDelegate * delegate, Evacuator * evacuator) [inline]
Definition at line 4723 of file mark-compact.cc.
                                                                 {
    while (remaining_evacuation_items_.load(std::memory_order_relaxed) > 0) {
      std::optional<size_t> index = generator_.GetNext();
      if (!index) return;
      for (size_t i = *index; i < evacuation_items_.size(); ++i) {
        auto& work_item = evacuation_items_[i];
        if (!work_item.first.TryAcquire()) break;
        evacuator->EvacuatePage(work_item.second);
        if (remaining_evacuation_items_.fetch_sub(
                1, std::memory_order_relaxed) <= 1) {
          return;
        }
      }
    }
  }
References v8::internal::Evacuator::EvacuatePage(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::index.
Run()
void v8::internal::PageEvacuationJob::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 4705 of file mark-compact.cc.
                                           {
    // Set the current isolate such that trusted pointer tables etc are
    // available and the cage base is set correctly for multi-cage mode.
    SetCurrentIsolateScope isolate_scope(collector_->heap()->isolate());
    Evacuator* evacuator = (*evacuators_)[delegate->GetTaskId()].get();
    if (delegate->IsJoiningThread()) {
      TRACE_GC_WITH_FLOW(tracer_, GCTracer::Scope::MC_EVACUATE_COPY_PARALLEL,
                         trace_id_, TRACE_EVENT_FLAG_FLOW_IN);
      ProcessItems(delegate, evacuator);
    } else {
      TRACE_GC_EPOCH_WITH_FLOW(
          tracer_, GCTracer::Scope::MC_BACKGROUND_EVACUATE_COPY,
          ThreadKind::kBackground, trace_id_, TRACE_EVENT_FLAG_FLOW_IN);
      ProcessItems(delegate, evacuator);
    }
  }
References v8::JobDelegate::GetTaskId(), v8::JobDelegate::IsJoiningThread(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, and TRACE_GC_WITH_FLOW.
trace_id()
uint64_t v8::internal::PageEvacuationJob::trace_id () const [inline]
Definition at line 4755 of file mark-compact.cc.
{ return trace_id_; }
Member Data Documentation
collector_
MarkCompactCollector* v8::internal::PageEvacuationJob::collector_ [private]
Definition at line 4758 of file mark-compact.cc.
evacuation_items_
std::vector<std::pair<ParallelWorkItem, MutablePageMetadata*> > v8::internal::PageEvacuationJob::evacuation_items_ [private]
Definition at line 4761 of file mark-compact.cc.
evacuators_
std::vector<std::unique_ptr<Evacuator> >* v8::internal::PageEvacuationJob::evacuators_ [private]
Definition at line 4759 of file mark-compact.cc.
generator_
IndexGenerator v8::internal::PageEvacuationJob::generator_ [private]
Definition at line 4763 of file mark-compact.cc.
remaining_evacuation_items_
std::atomic<size_t> v8::internal::PageEvacuationJob::remaining_evacuation_items_ {0} [private]
Definition at line 4762 of file mark-compact.cc.
trace_id_
const uint64_t v8::internal::PageEvacuationJob::trace_id_ [private]
Definition at line 4766 of file mark-compact.cc.
tracer_
GCTracer* v8::internal::PageEvacuationJob::tracer_ [private]
Definition at line 4765 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc