v8::internal::StringSet Class Reference
#include <string-set.h>
Public Member Functions
V8_EXPORT_PRIVATE bool Has (Isolate *isolate, DirectHandle< String > name)
Static Public Member Functions
static V8_EXPORT_PRIVATE Handle< StringSet > New (Isolate *isolate)
static V8_EXPORT_PRIVATE Handle< StringSet > Add (Isolate *isolate, Handle< StringSet > stringset, DirectHandle< String > name)
Detailed Description
Definition at line 32 of file string-set.h.
Member Function Documentation
Add()
Handle< StringSet > v8::internal::StringSet::Add (Isolate * isolate, Handle< StringSet > stringset, DirectHandle< String > name) [static]
Definition at line 5650 of file objects.cc.
                                                            {
  if (!stringset->Has(isolate, name)) {
    stringset = EnsureCapacity(isolate, stringset);
    uint32_t hash = TodoShape::Hash(ReadOnlyRoots(isolate), *name);
    InternalIndex entry = stringset->FindInsertionEntry(isolate, hash);
    stringset->set(EntryToIndex(entry), *name);
    stringset->ElementAdded();
  }
  return stringset;
}
References v8::internal::Hash(), and v8::internal::name.
Referenced by v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectCurrentLocalsIntoBlocklists(), and v8::internal::ScopeIterator::CollectLocalsFromCurrentScope().
Has()
bool v8::internal::StringSet::Has (Isolate * isolate, DirectHandle< String > name)
Definition at line 5662 of file objects.cc.
                                                               {
  return FindEntry(isolate, *name).is_found();
}
References v8::internal::name.
New()
Handle< StringSet > v8::internal::StringSet::New (Isolate * isolate) [static]
Definition at line 5646 of file objects.cc.
                                                 {
  return HashTable::New(isolate, 0);
}
References v8::internal::anonymous_namespace{intl-objects.cc}::New().
Referenced by v8::internal::ScopeIterator::AdvanceOneContext(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectAndStore(), and v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::InitializeWithClosureScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string-set.h
/mnt/V8SourceCode/src/objects/objects.cc