v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader Class Reference
Public Member Functions
base::Vector< uint8_t > buffer () override
std::unique_ptr< DecodingState > Next (AsyncStreamingDecoder *streaming) override
Private Member Functions
void CheckHeader (Decoder *decoder)
Private Attributes
uint8_t byte_buffer_ [kModuleHeaderSize]
Static Private Attributes
static constexpr size_t kModuleHeaderSize = 8
Detailed Description
Definition at line 434 of file streaming-decoder.cc.
Member Function Documentation
buffer()
base::Vector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::buffer () [inline], [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 436 of file streaming-decoder.cc.
                                        {
    return base::ArrayVector(byte_buffer_);
  }
References v8::base::ArrayVector().
CheckHeader()
void v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::CheckHeader (Decoder * decoder) [private]
Next()
std::unique_ptr< AsyncStreamingDecoder::DecodingState > v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::Next (AsyncStreamingDecoder * streaming) [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 608 of file streaming-decoder.cc.
                                      {
  TRACE_STREAMING("DecodeModuleHeader\n");
  streaming->ProcessModuleHeader();
  if (!streaming->ok()) return nullptr;
  return std::make_unique<DecodeSectionID>(streaming->module_offset());
}
References v8::internal::wasm::AsyncStreamingDecoder::module_offset(), v8::internal::wasm::AsyncStreamingDecoder::ok(), v8::internal::wasm::AsyncStreamingDecoder::ProcessModuleHeader(), and TRACE_STREAMING.
Member Data Documentation
byte_buffer_
uint8_t v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::byte_buffer_[kModuleHeaderSize] [private]
Definition at line 449 of file streaming-decoder.cc.
kModuleHeaderSize
constexpr size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::kModuleHeaderSize = 8 [static], [constexpr], [private]
Definition at line 448 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc