v8::internal::maglev::MaybeReduceResult Class Reference
#include <maglev-graph-builder.h>
Public Types
enum Kind { kDoneWithValue = 0
, kDoneWithAbort
, kDoneWithoutValue
, kFail
 }
Public Member Functions
MaybeReduceResult ()
MaybeReduceResult (ValueNode *value)
MaybeReduceResult (const MaybeReduceResult &) V8_NOEXCEPT=default
MaybeReduceResult & operator= (const MaybeReduceResult &) V8_NOEXCEPT=default
ValueNode * value () const
bool HasValue () const
bool IsDone () const
bool IsFail () const
bool IsDoneWithValue () const
bool IsDoneWithoutValue () const
bool IsDoneWithAbort () const
Kind kind () const
ReduceResult Checked ()
base::PointerWithPayload< ValueNode, Kind, 3 > GetPayload () const
Static Public Member Functions
static MaybeReduceResult Fail ()
Protected Member Functions
MaybeReduceResult (Kind kind)
MaybeReduceResult (base::PointerWithPayload< ValueNode, Kind, 3 > payload)
Protected Attributes
base::PointerWithPayload< ValueNode, Kind, 3 > payload_
Detailed Description
Definition at line 54 of file maglev-graph-builder.h.
Member Enumeration Documentation
Kind
enum v8::internal::maglev::MaybeReduceResult::Kind
Enumerator
kDoneWithValue
kDoneWithAbort
kDoneWithoutValue
kFail
Definition at line 56 of file maglev-graph-builder.h.
            {
    kDoneWithValue = 0, // No need to mask while returning the pointer.
    kDoneWithAbort,
    kDoneWithoutValue,
    kFail,
  };
Constructor & Destructor Documentation
MaybeReduceResult() [1/5]
v8::internal::maglev::MaybeReduceResult::MaybeReduceResult () [inline]
Definition at line 63 of file maglev-graph-builder.h.
: payload_(kFail) {}
References v8::kFail.
MaybeReduceResult() [2/5]
v8::internal::maglev::MaybeReduceResult::MaybeReduceResult (ValueNode * value) [inline]
Definition at line 66 of file maglev-graph-builder.h.
                                      : payload_(value) {
    DCHECK_NOT_NULL(value);
  }
References DCHECK_NOT_NULL, and v8::internal::value.
MaybeReduceResult() [3/5]
v8::internal::maglev::MaybeReduceResult::MaybeReduceResult (const MaybeReduceResult &) [default]
MaybeReduceResult() [4/5]
v8::internal::maglev::MaybeReduceResult::MaybeReduceResult (Kind kind) [inline], [explicit], [protected]
Definition at line 106 of file maglev-graph-builder.h.
: payload_(kind) {}
MaybeReduceResult() [5/5]
v8::internal::maglev::MaybeReduceResult::MaybeReduceResult (base::PointerWithPayload< ValueNode, Kind, 3 > payload) [inline], [explicit], [protected]
Definition at line 107 of file maglev-graph-builder.h.
      : payload_(payload) {}
Member Function Documentation
Checked()
ReduceResult v8::internal::maglev::MaybeReduceResult::Checked () [inline]
Definition at line 134 of file maglev-graph-builder.h.
{ return ReduceResult(*this); }
Fail()
static MaybeReduceResult v8::internal::maglev::MaybeReduceResult::Fail () [inline], [static]
Definition at line 70 of file maglev-graph-builder.h.
{ return MaybeReduceResult(kFail); }
References v8::kFail.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildNewConsString().
GetPayload()
base::PointerWithPayload<ValueNode, Kind, 3> v8::internal::maglev::MaybeReduceResult::GetPayload () const [inline]
Definition at line 101 of file maglev-graph-builder.h.
                                                                {
    return payload_;
  }
HasValue()
bool v8::internal::maglev::MaybeReduceResult::HasValue () const [inline]
Definition at line 79 of file maglev-graph-builder.h.
{ return kind() == kDoneWithValue; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryBuildNewConsString(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
IsDone()
bool v8::internal::maglev::MaybeReduceResult::IsDone () const [inline]
Definition at line 82 of file maglev-graph-builder.h.
{ return !IsFail(); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Branch(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadElements(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSArrayLength(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore().
IsDoneWithAbort()
bool v8::internal::maglev::MaybeReduceResult::IsDoneWithAbort () const [inline]
Definition at line 95 of file maglev-graph-builder.h.
{ return kind() == kDoneWithAbort; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Branch(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNewConsString(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator().
IsDoneWithoutValue()
bool v8::internal::maglev::MaybeReduceResult::IsDoneWithoutValue () const [inline]
Definition at line 91 of file maglev-graph-builder.h.
{ return kind() == kDoneWithoutValue; }
IsDoneWithValue()
bool v8::internal::maglev::MaybeReduceResult::IsDoneWithValue () const [inline]
Definition at line 88 of file maglev-graph-builder.h.
{ return HasValue(); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadElements(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSArrayLength(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator().
IsFail()
bool v8::internal::maglev::MaybeReduceResult::IsFail () const [inline]
Definition at line 85 of file maglev-graph-builder.h.
{ return kind() == kFail; }
References v8::kFail.
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator().
kind()
Kind v8::internal::maglev::MaybeReduceResult::kind () const [inline]
Definition at line 97 of file maglev-graph-builder.h.
{ return payload_.GetPayload(); }
operator=()
MaybeReduceResult& v8::internal::maglev::MaybeReduceResult::operator= (const MaybeReduceResult &) [default]
value()
ValueNode* v8::internal::maglev::MaybeReduceResult::value () const [inline]
Definition at line 75 of file maglev-graph-builder.h.
                           {
    DCHECK(HasValue());
    return payload_.GetPointerWithKnownPayload(kDoneWithValue);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadElements(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSArrayLength(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNewConsString(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator().
Member Data Documentation
payload_
base::PointerWithPayload<ValueNode, Kind, 3> v8::internal::maglev::MaybeReduceResult::payload_ [protected]
Definition at line 110 of file maglev-graph-builder.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.h