v8::TypedArray Class Reference
A base class for an instance of TypedArray series of constructors (ES6 draft 15.13.6).
#include <v8-typed-array.h>
Public Member Functions
size_t Length ()
Number of elements in this typed array (e.g.
Static Public Member Functions
static TypedArray * Cast (Value *value)
Static Public Attributes
static constexpr size_t kMaxByteLength = ArrayBuffer::kMaxByteLength
Private Member Functions
TypedArray ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
A base class for an instance of TypedArray series of constructors (ES6 draft 15.13.6).
Definition at line 20 of file v8-typed-array.h.
Constructor & Destructor Documentation
TypedArray()
v8::TypedArray::TypedArray () [private]
Member Function Documentation
Cast()
static TypedArray* v8::TypedArray::Cast (Value * value) [inline], [static]
Definition at line 39 of file v8-typed-array.h.
                                                  {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<TypedArray*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::TypedArray::CheckCast (Value * obj) [static], [private]
Definition at line 4089 of file api.cc.
                                        {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSTypedArray(obj), "v8::TypedArray::Cast()",
                  "Value is not a TypedArray");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Length()
size_t v8::TypedArray::Length ()
Number of elements in this typed array (e.g.
for Int16Array, |ByteLength|/2).
Definition at line 9235 of file api.cc.
                            {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::JSTypedArray> obj = *Utils::OpenDirectHandle(this);
  return obj->IsDetachedOrOutOfBounds() ? 0 : obj->GetLength();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
Member Data Documentation
kMaxByteLength
constexpr size_t v8::TypedArray::kMaxByteLength = ArrayBuffer::kMaxByteLength [static], [constexpr]
Definition at line 26 of file v8-typed-array.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-typed-array.h
/mnt/V8SourceCode/src/api/api.cc