v8::internal::compiler::BytecodeLivenessState Class Reference
#include <bytecode-liveness-map.h>
Classes
class Iterator
Public Member Functions
BytecodeLivenessState (int register_count, Zone *zone)
BytecodeLivenessState (const BytecodeLivenessState &)=delete
BytecodeLivenessState & operator= (const BytecodeLivenessState &)=delete
BytecodeLivenessState (const BytecodeLivenessState &other, Zone *zone)
bool RegisterIsLive (int index) const
bool AccumulatorIsLive () const
bool Equals (const BytecodeLivenessState &other) const
void MarkRegisterLive (int index)
void MarkRegisterDead (int index)
void MarkAccumulatorLive ()
void MarkAccumulatorDead ()
void MarkAllLive ()
void Union (const BytecodeLivenessState &other)
bool UnionIsChanged (const BytecodeLivenessState &other)
void CopyFrom (const BytecodeLivenessState &other)
int register_count () const
int live_value_count () const
Iterator begin () const
Iterator end () const
Private Attributes
BitVector bit_vector_
Detailed Description
Definition at line 20 of file bytecode-liveness-map.h.
Constructor & Destructor Documentation
BytecodeLivenessState() [1/3]
v8::internal::compiler::BytecodeLivenessState::BytecodeLivenessState (int register_count, Zone * zone) [inline]
Definition at line 54 of file bytecode-liveness-map.h.
      : bit_vector_(register_count + 1, zone) {}
BytecodeLivenessState() [2/3]
v8::internal::compiler::BytecodeLivenessState::BytecodeLivenessState (const BytecodeLivenessState &) [delete]
BytecodeLivenessState() [3/3]
v8::internal::compiler::BytecodeLivenessState::BytecodeLivenessState (const BytecodeLivenessState & other, Zone * zone) [inline]
Definition at line 59 of file bytecode-liveness-map.h.
      : bit_vector_(other.bit_vector_, zone) {}
Member Function Documentation
AccumulatorIsLive()
bool v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive () const [inline]
Definition at line 68 of file bytecode-liveness-map.h.
{ return bit_vector_.Contains(0); }
References bit_vector_, and v8::internal::BitVector::Contains().
Referenced by v8::internal::maglev::CompactInterpreterFrameState::accumulator(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint(), v8::internal::maglev::CompactInterpreterFrameState::ForEachValue(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Merge(), v8::internal::maglev::MaglevGraphBuilder::MergeIntoInlinedReturnFrameState(), v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoop(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit(), v8::internal::compiler::ToString(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
begin()
Iterator v8::internal::compiler::BytecodeLivenessState::begin () const [inline]
Definition at line 109 of file bytecode-liveness-map.h.
{ return Iterator(*this, Iterator::kStartTag); }
References v8::internal::compiler::BytecodeLivenessState::Iterator::kStartTag.
CopyFrom()
void v8::internal::compiler::BytecodeLivenessState::CopyFrom (const BytecodeLivenessState & other) [inline]
Definition at line 100 of file bytecode-liveness-map.h.
                                                    {
    bit_vector_.CopyFrom(other.bit_vector_);
  }
References bit_vector_, and v8::internal::BitVector::CopyFrom().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateLiveness().
end()
Iterator v8::internal::compiler::BytecodeLivenessState::end () const [inline]
Definition at line 111 of file bytecode-liveness-map.h.
{ return Iterator(*this, Iterator::kEndTag); }
References v8::internal::compiler::BytecodeLivenessState::Iterator::kEndTag.
Equals()
bool v8::internal::compiler::BytecodeLivenessState::Equals (const BytecodeLivenessState & other) const [inline]
Definition at line 70 of file bytecode-liveness-map.h.
                                                        {
    return bit_vector_.Equals(other.bit_vector_);
  }
References bit_vector_, and v8::internal::BitVector::Equals().
live_value_count()
int v8::internal::compiler::BytecodeLivenessState::live_value_count () const [inline]
Definition at line 107 of file bytecode-liveness-map.h.
{ return bit_vector_.Count(); }
References bit_vector_, and v8::internal::BitVector::Count().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MergeIntoInlinedReturnFrameState(), and v8::internal::maglev::CompactInterpreterFrameState::SizeFor().
MarkAccumulatorDead()
void v8::internal::compiler::BytecodeLivenessState::MarkAccumulatorDead () [inline]
Definition at line 88 of file bytecode-liveness-map.h.
{ bit_vector_.Remove(0); }
References bit_vector_, and v8::internal::BitVector::Remove().
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
MarkAccumulatorLive()
void v8::internal::compiler::BytecodeLivenessState::MarkAccumulatorLive () [inline]
Definition at line 86 of file bytecode-liveness-map.h.
{ bit_vector_.Add(0); }
References v8::internal::BitVector::Add(), and bit_vector_.
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness().
MarkAllLive()
void v8::internal::compiler::BytecodeLivenessState::MarkAllLive () [inline]
Definition at line 90 of file bytecode-liveness-map.h.
{ bit_vector_.AddAll(); }
References v8::internal::BitVector::AddAll(), and bit_vector_.
MarkRegisterDead()
void v8::internal::compiler::BytecodeLivenessState::MarkRegisterDead (int index) [inline]
Definition at line 80 of file bytecode-liveness-map.h.
                                   {
    DCHECK_GE(index, 0);
    DCHECK_LT(index, bit_vector_.length() - 1);
    bit_vector_.Remove(index + 1);
  }
References bit_vector_, DCHECK_GE, DCHECK_LT, v8::internal::index, v8::internal::BitVector::length(), and v8::internal::BitVector::Remove().
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForOutOperand().
MarkRegisterLive()
void v8::internal::compiler::BytecodeLivenessState::MarkRegisterLive (int index) [inline]
Definition at line 74 of file bytecode-liveness-map.h.
                                   {
    DCHECK_GE(index, 0);
    DCHECK_LT(index, bit_vector_.length() - 1);
    bit_vector_.Add(index + 1);
  }
References v8::internal::BitVector::Add(), bit_vector_, DCHECK_GE, DCHECK_LT, v8::internal::index, and v8::internal::BitVector::length().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::BeginLoop(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForInOperand(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
operator=()
BytecodeLivenessState& v8::internal::compiler::BytecodeLivenessState::operator= (const BytecodeLivenessState &) [delete]
register_count()
int v8::internal::compiler::BytecodeLivenessState::register_count () const [inline]
Definition at line 104 of file bytecode-liveness-map.h.
{ return bit_vector_.length() - 1; }
References bit_vector_, and v8::internal::BitVector::length().
Referenced by v8::internal::compiler::StateValuesCache::GetNodeForValues(), and v8::internal::compiler::ToString().
RegisterIsLive()
bool v8::internal::compiler::BytecodeLivenessState::RegisterIsLive (int index) const [inline]
Definition at line 62 of file bytecode-liveness-map.h.
                                       {
    DCHECK_GE(index, 0);
    DCHECK_LT(index, bit_vector_.length() - 1);
    return bit_vector_.Contains(index + 1);
  }
References bit_vector_, v8::internal::BitVector::Contains(), DCHECK_GE, DCHECK_LT, v8::internal::index, and v8::internal::BitVector::length().
Referenced by v8::internal::compiler::StateValuesCache::FillBufferWithValues(), v8::internal::compiler::StateValuesCache::GetNodeForValues(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Merge(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoop(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit(), v8::internal::compiler::ToString(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
Union()
void v8::internal::compiler::BytecodeLivenessState::Union (const BytecodeLivenessState & other) [inline]
Definition at line 92 of file bytecode-liveness-map.h.
                                                 {
    bit_vector_.Union(other.bit_vector_);
  }
References bit_vector_, and v8::internal::BitVector::Union().
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
UnionIsChanged()
bool v8::internal::compiler::BytecodeLivenessState::UnionIsChanged (const BytecodeLivenessState & other) [inline]
Definition at line 96 of file bytecode-liveness-map.h.
                                                          {
    return bit_vector_.UnionIsChanged(other.bit_vector_);
  }
References bit_vector_, and v8::internal::BitVector::UnionIsChanged().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
Member Data Documentation
bit_vector_
BitVector v8::internal::compiler::BytecodeLivenessState::bit_vector_ [private]
Definition at line 114 of file bytecode-liveness-map.h.
Referenced by AccumulatorIsLive(), CopyFrom(), Equals(), v8::internal::compiler::BytecodeLivenessState::Iterator::Iterator(), live_value_count(), MarkAccumulatorDead(), MarkAccumulatorLive(), MarkAllLive(), MarkRegisterDead(), MarkRegisterLive(), register_count(), RegisterIsLive(), Union(), and UnionIsChanged().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/bytecode-liveness-map.h