v8::internal::RegExpStack Class Reference
#include <regexp-stack.h>
Classes
struct ThreadLocal
Public Member Functions
RegExpStack ()
~RegExpStack ()
RegExpStack (const RegExpStack &)=delete
RegExpStack & operator= (const RegExpStack &)=delete
Address begin () const
Address end () const
Address memory_top () const
Address stack_pointer () const
size_t memory_size () const
Address * limit_address_address ()
Address EnsureCapacity (size_t size)
char * ArchiveStack (char *to)
char * RestoreStack (char *from)
void FreeThreadResources ()
Static Public Member Functions
static constexpr int ArchiveSpacePerThread ()
Static Public Attributes
static constexpr int kSlotSize = kInt32Size
static constexpr int kStackLimitSlackSlotCount = 32
static constexpr int kStackLimitSlackSize
static constexpr size_t kMaximumStackSize = 64 * MB
Private Member Functions
Address memory_top_address_address ()
Address stack_pointer_address ()
ptrdiff_t sp_top_delta () const
void ResetIfEmpty ()
bool IsValid () const
Private Attributes
uint8_t static_stack_ [kStaticStackSize] = {0}
ThreadLocal thread_local_
Static Private Attributes
static const Address kMemoryTop
static constexpr size_t kStaticStackSize = 1 * KB
static constexpr size_t kMinimumDynamicStackSize = 2 * KB
static constexpr size_t kThreadLocalSize = sizeof(ThreadLocal)
Friends
class ExternalReference
class RegExpStackScope
Detailed Description
Definition at line 36 of file regexp-stack.h.
Constructor & Destructor Documentation
RegExpStack() [1/2]
v8::internal::RegExpStack::RegExpStack ()
Definition at line 24 of file regexp-stack.cc.
: thread_local_(this) {}
 RegExpStack()
v8::internal::RegExpStack::~RegExpStack ()
Definition at line 26 of file regexp-stack.cc.
{ thread_local_.FreeAndInvalidate(); }
References v8::internal::RegExpStack::ThreadLocal::FreeAndInvalidate(), and thread_local_.
RegExpStack() [2/2]
v8::internal::RegExpStack::RegExpStack (const RegExpStack &) [delete]
Member Function Documentation
ArchiveSpacePerThread()
static constexpr int v8::internal::RegExpStack::ArchiveSpacePerThread () [inline], [static], [constexpr]
Definition at line 83 of file regexp-stack.h.
                                               {
    return static_cast<int>(kThreadLocalSize);
  }
References kThreadLocalSize.
Referenced by v8::internal::ArchiveSpacePerThread().
ArchiveStack()
char * v8::internal::RegExpStack::ArchiveStack (char * to)
Definition at line 28 of file regexp-stack.cc.
                                        {
  if (!thread_local_.owns_memory_) {
    // Force dynamic stacks prior to archiving. Any growth will do. A dynamic
    // stack is needed because stack archival & restoration rely on `memory_`
    // pointing at a fixed-location backing store, whereas the static stack is
    // tied to a RegExpStack instance.
    EnsureCapacity(thread_local_.memory_size_ + 1);
    DCHECK(thread_local_.owns_memory_);
  }
  MemCopy(reinterpret_cast<void*>(to), &thread_local_, kThreadLocalSize);
  thread_local_ = ThreadLocal(this);
  return to + kThreadLocalSize;
}
References v8::internal::DCHECK(), EnsureCapacity(), kThreadLocalSize, v8::internal::MemCopy(), v8::internal::RegExpStack::ThreadLocal::memory_size_, v8::internal::RegExpStack::ThreadLocal::owns_memory_, and thread_local_.
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread().
begin()
Address v8::internal::RegExpStack::begin () const [inline]
Definition at line 54 of file regexp-stack.h.
                        {
    return reinterpret_cast<Address>(thread_local_.memory_);
  }
References v8::internal::RegExpStack::ThreadLocal::memory_, and thread_local_.
end()
Address v8::internal::RegExpStack::end () const [inline]
Definition at line 57 of file regexp-stack.h.
                      {
    DCHECK_NE(0, thread_local_.memory_size_);
    DCHECK_EQ(thread_local_.memory_top_,
              thread_local_.memory_ + thread_local_.memory_size_);
    return reinterpret_cast<Address>(thread_local_.memory_top_);
  }
References DCHECK_EQ, DCHECK_NE, v8::internal::RegExpStack::ThreadLocal::memory_, v8::internal::RegExpStack::ThreadLocal::memory_size_, v8::internal::RegExpStack::ThreadLocal::memory_top_, and thread_local_.
Referenced by memory_top().
EnsureCapacity()
Address v8::internal::RegExpStack::EnsureCapacity (size_t size)
Definition at line 73 of file regexp-stack.cc.
                                               {
  if (size > kMaximumStackSize) return kNullAddress;
  if (thread_local_.memory_size_ < size) {
    if (size < kMinimumDynamicStackSize) size = kMinimumDynamicStackSize;
    uint8_t* new_memory = NewArray<uint8_t>(size);
    if (thread_local_.memory_size_ > 0) {
      // Copy original memory into top of new memory.
      MemCopy(new_memory + size - thread_local_.memory_size_,
              thread_local_.memory_, thread_local_.memory_size_);
      if (thread_local_.owns_memory_) DeleteArray(thread_local_.memory_);
    }
    ptrdiff_t delta = sp_top_delta();
    thread_local_.memory_ = new_memory;
    thread_local_.memory_top_ = new_memory + size;
    thread_local_.memory_size_ = size;
    thread_local_.stack_pointer_ = thread_local_.memory_top_ + delta;
    thread_local_.limit_ =
        reinterpret_cast<Address>(new_memory) + kStackLimitSlackSize;
    thread_local_.owns_memory_ = true;
  }
  return reinterpret_cast<Address>(thread_local_.memory_top_);
}
References kMaximumStackSize, kMinimumDynamicStackSize, v8::internal::kNullAddress, kStackLimitSlackSize, v8::internal::RegExpStack::ThreadLocal::limit_, v8::internal::MemCopy(), v8::internal::RegExpStack::ThreadLocal::memory_, v8::internal::RegExpStack::ThreadLocal::memory_size_, v8::internal::RegExpStack::ThreadLocal::memory_top_, v8::internal::RegExpStack::ThreadLocal::owns_memory_, size(), sp_top_delta(), v8::internal::RegExpStack::ThreadLocal::stack_pointer_, and thread_local_.
Referenced by ArchiveStack(), and v8::internal::NativeRegExpMacroAssembler::GrowStack().
FreeThreadResources()
void v8::internal::RegExpStack::FreeThreadResources () [inline]
Definition at line 88 of file regexp-stack.h.
{ thread_local_.ResetToStaticStack(this); }
References v8::internal::RegExpStack::ThreadLocal::ResetToStaticStack(), and thread_local_.
Referenced by v8::internal::ThreadManager::FreeThreadResources().
IsValid()
bool v8::internal::RegExpStack::IsValid () const [inline], [private]
Definition at line 162 of file regexp-stack.h.
{ return thread_local_.memory_ != nullptr; }
References v8::internal::RegExpStack::ThreadLocal::memory_, and thread_local_.
Referenced by v8::internal::RegExpStackScope::RegExpStackScope().
limit_address_address()
Address* v8::internal::RegExpStack::limit_address_address () [inline]
Definition at line 76 of file regexp-stack.h.
{ return &thread_local_.limit_; }
References v8::internal::RegExpStack::ThreadLocal::limit_, and thread_local_.
memory_size()
size_t v8::internal::RegExpStack::memory_size () const [inline]
Definition at line 69 of file regexp-stack.h.
{ return thread_local_.memory_size_; }
References v8::internal::RegExpStack::ThreadLocal::memory_size_, and thread_local_.
Referenced by v8::internal::NativeRegExpMacroAssembler::GrowStack().
memory_top()
Address v8::internal::RegExpStack::memory_top () const [inline]
Definition at line 63 of file regexp-stack.h.
{ return end(); }
References end().
Referenced by v8::internal::NativeRegExpMacroAssembler::GrowStack().
memory_top_address_address()
Address v8::internal::RegExpStack::memory_top_address_address () [inline], [private]
Definition at line 140 of file regexp-stack.h.
                                       {
    return reinterpret_cast<Address>(&thread_local_.memory_top_);
  }
References v8::internal::RegExpStack::ThreadLocal::memory_top_, and thread_local_.
operator=()
RegExpStack& v8::internal::RegExpStack::operator= (const RegExpStack &) [delete]
ResetIfEmpty()
void v8::internal::RegExpStack::ResetIfEmpty () [inline], [private]
Definition at line 159 of file regexp-stack.h.
{ thread_local_.ResetToStaticStackIfEmpty(this); }
References v8::internal::RegExpStack::ThreadLocal::ResetToStaticStackIfEmpty(), and thread_local_.
Referenced by v8::internal::RegExpStackScope::~RegExpStackScope().
RestoreStack()
char * v8::internal::RegExpStack::RestoreStack (char * from)
Definition at line 44 of file regexp-stack.cc.
                                          {
  MemCopy(&thread_local_, reinterpret_cast<void*>(from), kThreadLocalSize);
  return from + kThreadLocalSize;
}
References kThreadLocalSize, v8::internal::MemCopy(), and thread_local_.
Referenced by v8::internal::ThreadManager::RestoreThread().
sp_top_delta()
ptrdiff_t v8::internal::RegExpStack::sp_top_delta () const [inline], [private]
Definition at line 149 of file regexp-stack.h.
                                 {
    ptrdiff_t result =
        reinterpret_cast<intptr_t>(thread_local_.stack_pointer_) -
        reinterpret_cast<intptr_t>(thread_local_.memory_top_);
    DCHECK_LE(result, 0);
    return result;
  }
References DCHECK_LE, v8::internal::RegExpStack::ThreadLocal::memory_top_, v8::base::internal::result, v8::internal::RegExpStack::ThreadLocal::stack_pointer_, and thread_local_.
Referenced by EnsureCapacity(), and v8::internal::RegExpStackScope::~RegExpStackScope().
stack_pointer()
Address v8::internal::RegExpStack::stack_pointer () const [inline]
Definition at line 65 of file regexp-stack.h.
                                {
    return reinterpret_cast<Address>(thread_local_.stack_pointer_);
  }
References v8::internal::RegExpStack::ThreadLocal::stack_pointer_, and thread_local_.
Referenced by v8::internal::NativeRegExpMacroAssembler::GrowStack().
stack_pointer_address()
Address v8::internal::RegExpStack::stack_pointer_address () [inline], [private]
Definition at line 144 of file regexp-stack.h.
                                  {
    return reinterpret_cast<Address>(&thread_local_.stack_pointer_);
  }
References v8::internal::RegExpStack::ThreadLocal::stack_pointer_, and thread_local_.
Friends And Related Function Documentation
ExternalReference
friend class ExternalReference [friend]
Definition at line 166 of file regexp-stack.h.
RegExpStackScope
friend class RegExpStackScope [friend]
Definition at line 167 of file regexp-stack.h.
Member Data Documentation
kMaximumStackSize
constexpr size_t v8::internal::RegExpStack::kMaximumStackSize = 64 * MB [static], [constexpr]
Definition at line 91 of file regexp-stack.h.
Referenced by EnsureCapacity().
kMemoryTop
const Address v8::internal::RegExpStack::kMemoryTop [static], [private]
Initial value:
=
      static_cast<Address>(static_cast<uintptr_t>(-1))
Definition at line 95 of file regexp-stack.h.
Referenced by v8::internal::RegExpStack::ThreadLocal::FreeAndInvalidate().
kMinimumDynamicStackSize
constexpr size_t v8::internal::RegExpStack::kMinimumDynamicStackSize = 2 * KB [static], [constexpr], [private]
Definition at line 111 of file regexp-stack.h.
Referenced by EnsureCapacity().
kSlotSize
constexpr int v8::internal::RegExpStack::kSlotSize = kInt32Size [static], [constexpr]
Definition at line 46 of file regexp-stack.h.
kStackLimitSlackSize
constexpr int v8::internal::RegExpStack::kStackLimitSlackSize [static], [constexpr]
Initial value:
=
      kStackLimitSlackSlotCount * kSlotSize
Definition at line 51 of file regexp-stack.h.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::AssertAboveStackLimitMinusSlack(), EnsureCapacity(), and v8::internal::RegExpStack::ThreadLocal::ResetToStaticStack().
kStackLimitSlackSlotCount
constexpr int v8::internal::RegExpStack::kStackLimitSlackSlotCount = 32 [static], [constexpr]
Definition at line 50 of file regexp-stack.h.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::stack_limit_slack_slot_count().
kStaticStackSize
constexpr size_t v8::internal::RegExpStack::kStaticStackSize = 1 * KB [static], [constexpr], [private]
Definition at line 102 of file regexp-stack.h.
Referenced by v8::internal::RegExpStack::ThreadLocal::ResetToStaticStack().
kThreadLocalSize
constexpr size_t v8::internal::RegExpStack::kThreadLocalSize = sizeof(ThreadLocal) [static], [constexpr], [private]
Definition at line 138 of file regexp-stack.h.
Referenced by ArchiveSpacePerThread(), ArchiveStack(), and RestoreStack().
static_stack_
uint8_t v8::internal::RegExpStack::static_stack_[kStaticStackSize] = {0} [private]
Definition at line 108 of file regexp-stack.h.
Referenced by v8::internal::RegExpStack::ThreadLocal::ResetToStaticStack().
thread_local_
ThreadLocal v8::internal::RegExpStack::thread_local_ [private]
Definition at line 164 of file regexp-stack.h.
Referenced by ArchiveStack(), begin(), end(), EnsureCapacity(), FreeThreadResources(), IsValid(), limit_address_address(), memory_size(), memory_top_address_address(), ResetIfEmpty(), RestoreStack(), sp_top_delta(), stack_pointer(), stack_pointer_address(), and ~RegExpStack().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-stack.h
/mnt/V8SourceCode/src/regexp/regexp-stack.cc