v8::internal::maglev::UpdateJSArrayLength Class Reference
#include <maglev-ir.h>
Public Member Functions
UpdateJSArrayLength (uint64_t bitfield)
Input & length_input ()
Input & object_input ()
Input & index_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::CanWrite()
static constexpr Base::InputTypes kInputTypes
static constexpr int kLengthIndex = 0
static constexpr int kObjectIndex = 1
static constexpr int kIndexIndex = 2
Private Types
using Base = FixedInputValueNodeT< 3, UpdateJSArrayLength >
Additional Inherited Members
Detailed Description
Definition at line 9296 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::UpdateJSArrayLength::Base = FixedInputValueNodeT<3, UpdateJSArrayLength> [private]
Definition at line 9298 of file maglev-ir.h.
Constructor & Destructor Documentation
UpdateJSArrayLength()
v8::internal::maglev::UpdateJSArrayLength::UpdateJSArrayLength (uint64_t bitfield) [inline], [explicit]
Definition at line 9301 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::UpdateJSArrayLength::GenerateCode (MaglevAssembler * , const ProcessingState &)
index_input()
Input& v8::internal::maglev::UpdateJSArrayLength::index_input () [inline]
Definition at line 9317 of file maglev-ir.h.
{ return input(kIndexIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
length_input()
Input& v8::internal::maglev::UpdateJSArrayLength::length_input () [inline]
Definition at line 9315 of file maglev-ir.h.
{ return input(kLengthIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
object_input()
Input& v8::internal::maglev::UpdateJSArrayLength::object_input () [inline]
Definition at line 9316 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::UpdateJSArrayLength::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 9321 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::UpdateJSArrayLength::SetValueLocationConstraints ()
Member Data Documentation
kIndexIndex
constexpr int v8::internal::maglev::UpdateJSArrayLength::kIndexIndex = 2 [static], [constexpr]
Definition at line 9314 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::UpdateJSArrayLength::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kInt32, ValueRepresentation::kTagged,
      ValueRepresentation::kInt32}
Definition at line 9304 of file maglev-ir.h.
kLengthIndex
constexpr int v8::internal::maglev::UpdateJSArrayLength::kLengthIndex = 0 [static], [constexpr]
Definition at line 9312 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::UpdateJSArrayLength::kObjectIndex = 1 [static], [constexpr]
Definition at line 9313 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::UpdateJSArrayLength::kProperties = OpProperties::CanWrite() [static], [constexpr]
Definition at line 9303 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h