v8::internal::SimpleNumberDictionary Class Reference
#include <dictionary.h>
Static Public Member Functions
static DirectHandle< Map > GetMap (RootsTable &roots)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Handle< SimpleNumberDictionary > Set (Isolate *isolate, Handle< SimpleNumberDictionary > dictionary, uint32_t key, DirectHandle< Object > value)
Static Public Attributes
static const int kEntryValueIndex = 1
Detailed Description
Definition at line 408 of file dictionary.h.
Member Function Documentation
GetMap()
DirectHandle< Map > v8::internal::SimpleNumberDictionary::GetMap (RootsTable & roots) [inline], [static]
Definition at line 322 of file dictionary-inl.h.
                                                                  {
  return roots.simple_number_dictionary_map();
}
Set()
Handle< SimpleNumberDictionary > v8::internal::SimpleNumberDictionary::Set (Isolate * isolate, Handle< SimpleNumberDictionary > dictionary, uint32_t key, DirectHandle< Object > value) [static]
Definition at line 5883 of file objects.cc.
                                {
  return AtPut(isolate, dictionary, key, value, PropertyDetails::Empty());
}
References v8::internal::PropertyDetails::Empty(), v8::internal::key, and v8::internal::value.
Referenced by v8::internal::BIT_FIELD_ACCESSORS(), and v8::internal::ValueDeserializer::TransferArrayBuffer().
Member Data Documentation
kEntryValueIndex
const int v8::internal::SimpleNumberDictionary::kEntryValueIndex = 1 [static]
Definition at line 418 of file dictionary.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/dictionary.h
/mnt/V8SourceCode/src/objects/dictionary-inl.h
/mnt/V8SourceCode/src/objects/objects.cc