v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis Class Reference
Public Member Functions
BlockPhis (FullDecoder *decoder, Merge< Value > *merge)
void AllocatePhiInputs (Zone *zone)
BlockPhis (Zone *zone)
void InitReturnPhis (base::Vector< const ValueType > return_types)
void AddInputForPhi (size_t phi_i, OpIndex input)
uint32_t phi_count () const
ValueType phi_type (size_t phi_i) const
base::Vector< const OpIndex > phi_inputs (size_t phi_i) const
void AddIncomingException (OpIndex exception)
base::Vector< const OpIndex > incoming_exceptions () const
Private Member Functions
Zone * zone ()
V8_NOINLINE V8_PRESERVE_MOST void GrowInputsVector ()
Private Attributes
ValueType * phi_types_ = nullptr
OpIndex * phi_inputs_ = nullptr
uint32_t phi_inputs_capacity_total_ = 0
uint32_t phi_inputs_total_ = 0
uint32_t next_phi_input_add_offset_ = 0
uint32_t phi_count_ = 0
uint32_t inputs_per_phi_ = 0
uint32_t input_capacity_per_phi_ = kInitialInputCapacityPerPhi
ZoneVector< OpIndex > incoming_exceptions_
Static Private Attributes
static constexpr uint32_t kInitialInputCapacityPerPhi = 2
Detailed Description
Definition at line 6196 of file turboshaft-graph-interface.cc.
Constructor & Destructor Documentation
BlockPhis() [1/2]
v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::BlockPhis (FullDecoder * decoder, Merge< Value > * merge) [inline]
Definition at line 6199 of file turboshaft-graph-interface.cc.
        : incoming_exceptions_(decoder -> zone()) {
      // Allocate space and initialize the types of all phis.
      uint32_t num_locals = decoder->num_locals();
      uint32_t merge_arity = merge != nullptr ? merge->arity : 0;
      phi_count_ = num_locals + merge_arity;
      phi_types_ = decoder->zone()->AllocateArray<ValueType>(phi_count_);
      base::Vector<ValueType> locals = decoder->local_types();
      std::uninitialized_copy(locals.begin(), locals.end(), phi_types_);
      for (uint32_t i = 0; i < merge_arity; i++) {
        new (&phi_types_[num_locals + i]) ValueType((*merge)[i].type);
      }
      AllocatePhiInputs(decoder->zone());
    }
References v8::internal::Zone::AllocateArray(), v8::internal::wasm::Merge< Value >::arity, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::zone().
BlockPhis() [2/2]
v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::BlockPhis (Zone * zone) [inline], [explicit]
Definition at line 6230 of file turboshaft-graph-interface.cc.
: incoming_exceptions_(zone) {}
Member Function Documentation
AddIncomingException()
void v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::AddIncomingException (OpIndex exception) [inline]
Definition at line 6283 of file turboshaft-graph-interface.cc.
                                                 {
      incoming_exceptions_.push_back(exception);
    }
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Delegate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::SetupControlFlowEdge().
AddInputForPhi()
void v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::AddInputForPhi (size_t phi_i, OpIndex input) [inline]
Definition at line 6246 of file turboshaft-graph-interface.cc.
                                                     {
      if (V8_UNLIKELY(phi_inputs_total_ >= phi_inputs_capacity_total_)) {
        GrowInputsVector();
      }
#ifdef DEBUG
      // We rely on adding inputs in the order of phis, i.e.,
      // `AddInputForPhi(0, ...); AddInputForPhi(1, ...); ...`.
      size_t phi_inputs_start = phi_i * input_capacity_per_phi_;
      size_t phi_input_offset_from_start = inputs_per_phi_;
      CHECK_EQ(input_count_per_phi_[phi_i]++, phi_input_offset_from_start);
      size_t phi_input_offset = phi_inputs_start + phi_input_offset_from_start;
      CHECK_EQ(next_phi_input_add_offset_, phi_input_offset);
#endif
      new (&phi_inputs_[next_phi_input_add_offset_]) OpIndex(input);
      phi_inputs_total_++;
      next_phi_input_add_offset_ += input_capacity_per_phi_;
      if (next_phi_input_add_offset_ >= phi_inputs_capacity_total_) {
        // We have finished adding the last input for all phis.
        inputs_per_phi_++;
        next_phi_input_add_offset_ = inputs_per_phi_;
#ifdef DEBUG
        EnsureAllPhisHaveSameInputCount();
#endif
      }
    }
References CHECK_EQ, and V8_UNLIKELY.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmMaybeReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::SetupControlFlowEdge().
AllocatePhiInputs()
void v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::AllocatePhiInputs (Zone * zone) [inline]
Definition at line 6218 of file turboshaft-graph-interface.cc.
                                       {
      // Only reserve some space for the inputs to be added later.
      phi_inputs_capacity_total_ = phi_count_ * input_capacity_per_phi_;
      phi_inputs_ = zone->AllocateArray<OpIndex>(phi_inputs_capacity_total_);
#ifdef DEBUG
      constexpr uint32_t kNoInputs = 0;
      input_count_per_phi_ = std::vector(phi_count_, kNoInputs);
#endif
    }
References v8::internal::Zone::AllocateArray().
GrowInputsVector()
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::GrowInputsVector () [inline], [private]
Definition at line 6350 of file turboshaft-graph-interface.cc.
                                                         {
      // We should have always initialized some storage, see
      // `kInitialInputCapacityPerPhi`.
      DCHECK_NOT_NULL(phi_inputs_);
      DCHECK_NE(phi_inputs_capacity_total_, 0);
      OpIndex* old_phi_inputs = phi_inputs_;
      uint32_t old_input_capacity_per_phi = input_capacity_per_phi_;
      uint32_t old_phi_inputs_capacity_total = phi_inputs_capacity_total_;
      input_capacity_per_phi_ *= 2;
      phi_inputs_capacity_total_ *= 2;
      phi_inputs_ = zone()->AllocateArray<OpIndex>(phi_inputs_capacity_total_);
      // This is essentially a strided copy, where we expand the storage by
      // "inserting" unitialized elements in between contiguous stretches of
      // inputs belonging to the same phi.
#ifdef DEBUG
      EnsureAllPhisHaveSameInputCount();
#endif
      for (size_t phi_i = 0; phi_i < phi_count(); ++phi_i) {
        const OpIndex* old_begin =
            &old_phi_inputs[phi_i * old_input_capacity_per_phi];
        const OpIndex* old_end = old_begin + inputs_per_phi_;
        OpIndex* begin = &phi_inputs_[phi_i * input_capacity_per_phi_];
        std::uninitialized_copy(old_begin, old_end, begin);
      }
      zone()->DeleteArray(old_phi_inputs, old_phi_inputs_capacity_total);
    }
References v8::internal::compiler::begin(), DCHECK_NE, and DCHECK_NOT_NULL.
incoming_exceptions()
base::Vector<const OpIndex> v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::incoming_exceptions () const [inline]
Definition at line 6287 of file turboshaft-graph-interface.cc.
                                                          {
      return base::VectorOf(incoming_exceptions_);
    }
References v8::base::VectorOf().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BindBlockAndGeneratePhis(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall().
InitReturnPhis()
void v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::InitReturnPhis (base::Vector< const ValueType > return_types) [inline]
Definition at line 6231 of file turboshaft-graph-interface.cc.
                                                                  {
      // For `return_phis_`, nobody should have inserted into `this` before
      // calling `InitReturnPhis`.
      DCHECK_EQ(phi_count_, 0);
      DCHECK_EQ(inputs_per_phi_, 0);
      uint32_t return_count = static_cast<uint32_t>(return_types.size());
      phi_count_ = return_count;
      phi_types_ = zone()->AllocateArray<ValueType>(phi_count_);
      std::uninitialized_copy(return_types.begin(), return_types.end(),
                              phi_types_);
      AllocatePhiInputs(zone());
    }
References v8::base::Vector< T >::begin(), DCHECK_EQ, v8::base::Vector< T >::end(), and v8::base::Vector< T >::size().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
phi_count()
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_count () const [inline]
Definition at line 6274 of file turboshaft-graph-interface.cc.
{ return phi_count_; }
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BindBlockAndGeneratePhis(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::SetupControlFlowEdge().
phi_inputs()
base::Vector<const OpIndex> v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_inputs (size_t phi_i) const [inline]
Definition at line 6278 of file turboshaft-graph-interface.cc.
                                                             {
      size_t phi_inputs_start = phi_i * input_capacity_per_phi_;
      return base::VectorOf(&phi_inputs_[phi_inputs_start], inputs_per_phi_);
    }
References v8::base::VectorOf().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BindBlockAndGeneratePhis(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall().
phi_type()
ValueType v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_type (size_t phi_i) const [inline]
Definition at line 6276 of file turboshaft-graph-interface.cc.
{ return phi_types_[phi_i]; }
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BindBlockAndGeneratePhis(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall().
zone()
Zone* v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::zone () [inline], [private]
Definition at line 6348 of file turboshaft-graph-interface.cc.
{ return incoming_exceptions_.zone(); }
References v8::internal::ZoneVector< T >::zone().
Member Data Documentation
incoming_exceptions_
ZoneVector<OpIndex> v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::incoming_exceptions_ [private]
Definition at line 6346 of file turboshaft-graph-interface.cc.
input_capacity_per_phi_
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::input_capacity_per_phi_ = kInitialInputCapacityPerPhi [private]
Definition at line 6328 of file turboshaft-graph-interface.cc.
inputs_per_phi_
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::inputs_per_phi_ = 0 [private]
Definition at line 6326 of file turboshaft-graph-interface.cc.
kInitialInputCapacityPerPhi
constexpr uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::kInitialInputCapacityPerPhi = 2 [static], [constexpr], [private]
Definition at line 6327 of file turboshaft-graph-interface.cc.
next_phi_input_add_offset_
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::next_phi_input_add_offset_ = 0 [private]
Definition at line 6322 of file turboshaft-graph-interface.cc.
phi_count_
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_count_ = 0 [private]
Definition at line 6325 of file turboshaft-graph-interface.cc.
phi_inputs_
OpIndex* v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_inputs_ = nullptr [private]
Definition at line 6316 of file turboshaft-graph-interface.cc.
phi_inputs_capacity_total_
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_inputs_capacity_total_ = 0 [private]
Definition at line 6320 of file turboshaft-graph-interface.cc.
phi_inputs_total_
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_inputs_total_ = 0 [private]
Definition at line 6321 of file turboshaft-graph-interface.cc.
phi_types_
ValueType* v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_types_ = nullptr [private]
Definition at line 6310 of file turboshaft-graph-interface.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/turboshaft-graph-interface.cc