v8::internal::AllocationStats Class Reference
#include <allocation-stats.h>
Public Member Functions
AllocationStats ()
AllocationStats & operator= (const AllocationStats &stats) V8_NOEXCEPT
void Clear ()
void ClearSize ()
size_t Capacity () const
size_t MaxCapacity () const
size_t Size () const
void IncreaseAllocatedBytes (size_t bytes, const MemoryChunkMetadata *page)
void DecreaseAllocatedBytes (size_t bytes, const MemoryChunkMetadata *page)
void DecreaseCapacity (size_t bytes)
void IncreaseCapacity (size_t bytes)
Private Attributes
std::atomic< size_t > capacity_
size_t max_capacity_
std::atomic< size_t > size_
Detailed Description
Definition at line 24 of file allocation-stats.h.
Constructor & Destructor Documentation
AllocationStats()
v8::internal::AllocationStats::AllocationStats () [inline]
Definition at line 26 of file allocation-stats.h.
{ Clear(); }
References Clear().
Member Function Documentation
Capacity()
size_t v8::internal::AllocationStats::Capacity () const [inline]
Definition at line 53 of file allocation-stats.h.
{ return capacity_; }
References capacity_.
Clear()
void v8::internal::AllocationStats::Clear () [inline]
Definition at line 39 of file allocation-stats.h.
               {
    capacity_ = 0;
    max_capacity_ = 0;
    ClearSize();
  }
References capacity_, ClearSize(), and max_capacity_.
Referenced by AllocationStats(), v8::internal::PagedSpaceBase::PagedSpaceBase(), v8::internal::PagedSpaceBase::TearDown(), v8::internal::ReadOnlySpace::TearDown(), and v8::internal::SharedReadOnlySpace::TearDown().
ClearSize()
void v8::internal::AllocationStats::ClearSize () [inline]
Definition at line 45 of file allocation-stats.h.
                   {
    size_ = 0;
#ifdef DEBUG
    allocated_on_page_.clear();
#endif
  }
References size_.
Referenced by Clear().
DecreaseAllocatedBytes()
void v8::internal::AllocationStats::DecreaseAllocatedBytes (size_t bytes, const MemoryChunkMetadata * page) [inline]
Definition at line 75 of file allocation-stats.h.
                                                                             {
    DCHECK_GE(size_, bytes);
    size_.fetch_sub(bytes);
#ifdef DEBUG
    DCHECK_GE(allocated_on_page_[page], bytes);
    allocated_on_page_[page] -= bytes;
#endif
  }
References DCHECK_GE, and size_.
DecreaseCapacity()
void v8::internal::AllocationStats::DecreaseCapacity (size_t bytes) [inline]
Definition at line 84 of file allocation-stats.h.
                                      {
    DCHECK_GE(capacity_, bytes);
    DCHECK_GE(capacity_ - bytes, size_);
    capacity_ -= bytes;
  }
References capacity_, DCHECK_GE, and size_.
Referenced by v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), and v8::internal::ReadOnlySpace::ShrinkPages().
IncreaseAllocatedBytes()
void v8::internal::AllocationStats::IncreaseAllocatedBytes (size_t bytes, const MemoryChunkMetadata * page) [inline]
Definition at line 62 of file allocation-stats.h.
                                                                             {
    DCHECK_IMPLIES(V8_COMPRESS_POINTERS_8GB_BOOL,
                   IsAligned(bytes, kObjectAlignment8GbHeap));
#ifdef DEBUG
    size_t size = size_;
    DCHECK_GE(size + bytes, size);
#endif
    size_.fetch_add(bytes);
#ifdef DEBUG
    allocated_on_page_[page] += bytes;
#endif
  }
References DCHECK_GE, DCHECK_IMPLIES, IsAligned(), v8::internal::kObjectAlignment8GbHeap, size(), size_, and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by v8::internal::ReadOnlySpace::AllocateRawUnaligned(), v8::internal::ReadOnlySpace::FinalizeSpaceForDeserialization(), and v8::internal::ReadOnlySpace::TryAllocateLinearlyAligned().
IncreaseCapacity()
void v8::internal::AllocationStats::IncreaseCapacity (size_t bytes) [inline]
Definition at line 90 of file allocation-stats.h.
                                      {
    DCHECK_GE(capacity_ + bytes, capacity_);
    capacity_ += bytes;
    if (capacity_ > max_capacity_) {
      max_capacity_ = capacity_;
    }
  }
References capacity_, DCHECK_GE, and max_capacity_.
Referenced by v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), and v8::internal::ReadOnlySpace::FinalizeSpaceForDeserialization().
MaxCapacity()
size_t v8::internal::AllocationStats::MaxCapacity () const [inline]
Definition at line 54 of file allocation-stats.h.
{ return max_capacity_; }
References max_capacity_.
operator=()
AllocationStats& v8::internal::AllocationStats::operator= (const AllocationStats & stats) [inline]
Definition at line 28 of file allocation-stats.h.
                                                                       {
    capacity_ = stats.capacity_.load();
    max_capacity_ = stats.max_capacity_;
    size_.store(stats.size_);
#ifdef DEBUG
    allocated_on_page_ = stats.allocated_on_page_;
#endif
    return *this;
  }
References capacity_, max_capacity_, and size_.
Size()
size_t v8::internal::AllocationStats::Size () const [inline]
Definition at line 55 of file allocation-stats.h.
{ return size_; }
References size_.
Referenced by v8::internal::ReadOnlySpace::Size().
Member Data Documentation
capacity_
std::atomic<size_t> v8::internal::AllocationStats::capacity_ [private]
Definition at line 103 of file allocation-stats.h.
Referenced by Capacity(), Clear(), DecreaseCapacity(), IncreaseCapacity(), and operator=().
max_capacity_
size_t v8::internal::AllocationStats::max_capacity_ [private]
Definition at line 106 of file allocation-stats.h.
Referenced by Clear(), IncreaseCapacity(), MaxCapacity(), and operator=().
size_
std::atomic<size_t> v8::internal::AllocationStats::size_ [private]
Definition at line 109 of file allocation-stats.h.
Referenced by ClearSize(), DecreaseAllocatedBytes(), DecreaseCapacity(), IncreaseAllocatedBytes(), operator=(), and Size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/allocation-stats.h