v8::internal::compiler::CreateLiteralParameters Class Reference
#include <js-operator.h>
Public Member Functions
CreateLiteralParameters (HeapObjectRef constant, FeedbackSource const &feedback, int length, int flags)
HeapObjectRef constant () const
FeedbackSource const & feedback () const
int length () const
int flags () const
Private Attributes
const HeapObjectRef constant_
FeedbackSource const feedback_
int const length_
int const flags_
Friends
bool operator== (CreateLiteralParameters const &, CreateLiteralParameters const &)
bool operator!= (CreateLiteralParameters const &, CreateLiteralParameters const &)
size_t hash_value (CreateLiteralParameters const &)
std::ostream & operator<< (std::ostream &, CreateLiteralParameters const &)
Detailed Description
Definition at line 737 of file js-operator.h.
Constructor & Destructor Documentation
CreateLiteralParameters()
v8::internal::compiler::CreateLiteralParameters::CreateLiteralParameters (HeapObjectRef constant, FeedbackSource const & feedback, int length, int flags) [inline]
Definition at line 739 of file js-operator.h.
      : constant_(constant),
        feedback_(feedback),
        length_(length),
        flags_(flags) {}
Member Function Documentation
constant()
HeapObjectRef v8::internal::compiler::CreateLiteralParameters::constant () const [inline]
Definition at line 746 of file js-operator.h.
{ return constant_; }
References constant_.
feedback()
FeedbackSource const& v8::internal::compiler::CreateLiteralParameters::feedback () const [inline]
Definition at line 747 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp().
flags()
int v8::internal::compiler::CreateLiteralParameters::flags () const [inline]
Definition at line 749 of file js-operator.h.
{ return flags_; }
References flags_.
length()
int v8::internal::compiler::CreateLiteralParameters::length () const [inline]
Definition at line 748 of file js-operator.h.
{ return length_; }
References length_.
Friends And Related Function Documentation
hash_value
size_t hash_value (CreateLiteralParameters const & p) [friend]
Definition at line 600 of file js-operator.cc.
                                                    {
  return base::hash_combine(p.constant_.object().location(),
                            FeedbackSource::Hash()(p.feedback()), p.length(),
                            p.flags());
}
operator!=
bool operator!= (CreateLiteralParameters const & lhs, CreateLiteralParameters const & rhs) [friend]
Definition at line 594 of file js-operator.cc.
                                                    {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, CreateLiteralParameters const & p) [friend]
Definition at line 607 of file js-operator.cc.
                                                                         {
  return os << Brief(*p.constant_.object()) << ", " << p.length() << ", "
            << p.flags();
}
operator==
bool operator== (CreateLiteralParameters const & lhs, CreateLiteralParameters const & rhs) [friend]
Definition at line 585 of file js-operator.cc.
                                                    {
  return lhs.constant_.object().location() ==
             rhs.constant_.object().location() &&
         lhs.feedback() == rhs.feedback() && lhs.length() == rhs.length() &&
         lhs.flags() == rhs.flags();
}
Member Data Documentation
constant_
const HeapObjectRef v8::internal::compiler::CreateLiteralParameters::constant_ [private]
Definition at line 752 of file js-operator.h.
Referenced by constant().
feedback_
FeedbackSource const v8::internal::compiler::CreateLiteralParameters::feedback_ [private]
Definition at line 753 of file js-operator.h.
Referenced by feedback().
flags_
int const v8::internal::compiler::CreateLiteralParameters::flags_ [private]
Definition at line 755 of file js-operator.h.
Referenced by flags().
length_
int const v8::internal::compiler::CreateLiteralParameters::length_ [private]
Definition at line 754 of file js-operator.h.
Referenced by length().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h