v8::internal::compiler::JSCallReducer Class Reference
#include <js-call-reducer.h>
Public Types
enum Flag { kNoFlags = 0u
, kBailoutOnUninitialized = 1u << 0
, kInlineJSToWasmCalls = 1u << 1
 }
using Flags = base::Flags< Flag >
Public Member Functions
JSCallReducer (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker, Zone *temp_zone, Flags flags)
const char * reducer_name () const override
Reduction Reduce (Node *node) final
void Finalize () final
void RevisitForGraphAssembler (Node *node)
Zone * ZoneForGraphAssembler () const
JSGraph * JSGraphForGraphAssembler () const
CompilationDependencies * dependencies () const
JSHeapBroker * broker () const
Static Public Attributes
static constexpr int kMaxInlineMatchSequence = 3
Private Types
enum class ArrayIteratorKind { kArrayLike
, kTypedArray
 }
enum class StringIndexOfIncludesVariant { kIncludes
, kIndexOf
 }
enum class DataViewAccess { kGet
, kSet
 }
Private Member Functions
Reduction ReduceBooleanConstructor (Node *node)
Reduction ReduceCallApiFunction (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceCallWasmFunction (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceFunctionPrototypeApply (Node *node)
Reduction ReduceFunctionPrototypeBind (Node *node)
Reduction ReduceFunctionPrototypeCall (Node *node)
Reduction ReduceFunctionPrototypeHasInstance (Node *node)
Reduction ReduceObjectConstructor (Node *node)
Reduction ReduceObjectGetPrototype (Node *node, Node *object)
Reduction ReduceObjectGetPrototypeOf (Node *node)
Reduction ReduceObjectIs (Node *node)
Reduction ReduceObjectPrototypeGetProto (Node *node)
Reduction ReduceObjectPrototypeHasOwnProperty (Node *node)
Reduction ReduceObjectPrototypeIsPrototypeOf (Node *node)
Reduction ReduceObjectCreate (Node *node)
Reduction ReduceReflectApply (Node *node)
Reduction ReduceReflectConstruct (Node *node)
Reduction ReduceReflectGet (Node *node)
Reduction ReduceReflectGetPrototypeOf (Node *node)
Reduction ReduceReflectHas (Node *node)
Reduction ReduceArrayConstructor (Node *node)
Reduction ReduceArrayEvery (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArrayFilter (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArrayFindIndex (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArrayFind (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArrayForEach (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArrayIncludes (Node *node)
Reduction ReduceArrayIndexOf (Node *node)
Reduction ReduceArrayIsArray (Node *node)
Reduction ReduceArrayMap (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArrayPrototypeAt (Node *node)
Reduction ReduceArrayPrototypePop (Node *node)
Reduction ReduceArrayPrototypePush (Node *node)
Reduction ReduceArrayPrototypeShift (Node *node)
Reduction ReduceArrayPrototypeSlice (Node *node)
Reduction ReduceArrayReduce (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArrayReduceRight (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArraySome (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceArrayIterator (Node *node, ArrayIteratorKind array_kind, IterationKind iteration_kind)
Reduction ReduceArrayIteratorPrototypeNext (Node *node)
Reduction ReduceFastArrayIteratorNext (InstanceType type, Node *node, IterationKind kind)
Reduction ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments (Node *node, Node *arguments_list, int arraylike_or_spread_index, CallFrequency const &frequency, FeedbackSource const &feedback, SpeculationMode speculation_mode, CallFeedbackRelation feedback_relation)
Reduction ReduceCallOrConstructWithArrayLikeOrSpread (Node *node, int argument_count, int arraylike_or_spread_index, CallFrequency const &frequency, FeedbackSource const &feedback_source, SpeculationMode speculation_mode, CallFeedbackRelation feedback_relation, Node *target, Effect effect, Control control)
Reduction ReduceJSConstruct (Node *node)
Reduction ReduceJSConstructWithArrayLike (Node *node)
Reduction ReduceJSConstructWithSpread (Node *node)
Reduction ReduceJSConstructForwardAllArgs (Node *node)
Reduction ReduceJSCall (Node *node)
Reduction ReduceJSCall (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceJSCallWithArrayLike (Node *node)
Reduction ReduceJSCallWithSpread (Node *node)
Reduction ReduceRegExpPrototypeTest (Node *node)
Reduction ReduceReturnReceiver (Node *node)
Reduction ReduceStringConstructor (Node *node, JSFunctionRef constructor)
Reduction ReduceStringPrototypeIndexOfIncludes (Node *node, StringIndexOfIncludesVariant variant)
Reduction ReduceStringPrototypeSubstring (Node *node)
Reduction ReduceStringPrototypeSlice (Node *node)
Reduction ReduceStringPrototypeSubstr (Node *node)
Reduction ReduceStringPrototypeStringCharCodeAt (Node *node)
Reduction ReduceStringPrototypeStringCodePointAt (Node *node)
Reduction ReduceStringPrototypeCharAt (Node *node)
Reduction ReduceStringPrototypeStartsWith (Node *node)
Reduction ReduceStringPrototypeEndsWith (Node *node)
Reduction ReduceStringFromCharCode (Node *node)
Reduction ReduceStringFromCodePoint (Node *node)
Reduction ReduceStringPrototypeIterator (Node *node)
Reduction ReduceStringIteratorPrototypeNext (Node *node)
Reduction ReduceStringPrototypeConcat (Node *node)
Reduction ReducePromiseConstructor (Node *node)
Reduction ReducePromiseInternalConstructor (Node *node)
Reduction ReducePromiseInternalReject (Node *node)
Reduction ReducePromiseInternalResolve (Node *node)
Reduction ReducePromisePrototypeCatch (Node *node)
Reduction ReducePromisePrototypeFinally (Node *node)
Reduction ReducePromisePrototypeThen (Node *node)
Reduction ReducePromiseResolveTrampoline (Node *node)
Reduction ReduceTypedArrayConstructor (Node *node, SharedFunctionInfoRef shared)
Reduction ReduceTypedArrayPrototypeToStringTag (Node *node)
Reduction ReduceArrayBufferViewByteLengthAccessor (Node *node, InstanceType instance_type, Builtin builtin)
Reduction ReduceArrayBufferViewByteOffsetAccessor (Node *node, InstanceType instance_type, Builtin builtin)
Reduction ReduceTypedArrayPrototypeLength (Node *node)
Reduction ReduceForInsufficientFeedback (Node *node, DeoptimizeReason reason)
Reduction ReduceMathUnary (Node *node, const Operator *op)
Reduction ReduceMathBinary (Node *node, const Operator *op)
Reduction ReduceMathImul (Node *node)
Reduction ReduceMathClz32 (Node *node)
Reduction ReduceMathMinMax (Node *node, const Operator *op, Node *empty_value)
Reduction ReduceNumberIsFinite (Node *node)
Reduction ReduceNumberIsInteger (Node *node)
Reduction ReduceNumberIsSafeInteger (Node *node)
Reduction ReduceNumberIsNaN (Node *node)
Reduction ReduceGlobalIsFinite (Node *node)
Reduction ReduceGlobalIsNaN (Node *node)
Reduction ReduceMapPrototypeHas (Node *node)
Reduction ReduceMapPrototypeGet (Node *node)
Reduction ReduceSetPrototypeHas (Node *node)
Reduction ReduceCollectionPrototypeHas (Node *node, CollectionKind collection_kind)
Reduction ReduceCollectionIteration (Node *node, CollectionKind collection_kind, IterationKind iteration_kind)
Reduction ReduceCollectionPrototypeSize (Node *node, CollectionKind collection_kind)
Reduction ReduceCollectionIteratorPrototypeNext (Node *node, int entry_size, Handle< HeapObject > empty_collection, InstanceType collection_iterator_instance_type_first, InstanceType collection_iterator_instance_type_last)
Reduction ReduceArrayBufferIsView (Node *node)
Reduction ReduceArrayBufferViewAccessor (Node *node, InstanceType instance_type, FieldAccess const &access, Builtin builtin)
Reduction ReduceDataViewAccess (Node *node, DataViewAccess access, ExternalArrayType element_type)
Reduction ReduceDatePrototypeGetTime (Node *node)
Reduction ReduceDatePrototypeGetField (Node *node, JSDate::FieldIndex field)
Reduction ReduceDateNow (Node *node)
Reduction ReduceNumberParseInt (Node *node)
Reduction ReduceNumberConstructor (Node *node)
Reduction ReduceBigIntConstructor (Node *node)
Reduction ReduceBigIntAsN (Node *node, Builtin builtin)
std::optional< Reduction > TryReduceJSCallMathMinMaxWithArrayLike (Node *node)
Reduction ReduceJSCallMathMinMaxWithArrayLike (Node *node, Builtin builtin)
Reduction ReplaceWithSubgraph (JSCallReducerAssembler *gasm, Node *subgraph)
std::pair< Node *, Node * > ReleaseEffectAndControlFromAssembler (JSCallReducerAssembler *gasm)
bool DoPromiseChecks (MapInference *inference)
Node * CreateClosureFromBuiltinSharedFunctionInfo (SharedFunctionInfoRef shared, Node *context, Node *effect, Node *control)
void CheckIfElementsKind (Node *receiver_elements_kind, ElementsKind kind, Node *control, Node **if_true, Node **if_false)
Node * LoadReceiverElementsKind (Node *receiver, Effect *effect, Control control)
bool IsBuiltinOrApiFunction (JSFunctionRef target_ref) const
Node * CheckArrayLength (Node *array, ElementsKind elements_kind, uint32_t array_length, const FeedbackSource &feedback_source, Effect effect, Control control)
void CheckIfConstructor (Node *call)
Node * ConvertHoleToUndefined (Node *value, ElementsKind elements_kind)
TFGraph * graph () const
JSGraph * jsgraph () const
Zone * temp_zone () const
Isolate * isolate () const
Factory * factory () const
NativeContextRef native_context () const
CommonOperatorBuilder * common () const
JSOperatorBuilder * javascript () const
SimplifiedOperatorBuilder * simplified () const
Flags flags () const
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker *const broker_
Zone *const temp_zone_
Flags const flags_
std::set< Node * > waitlist_
std::unordered_set< Node * > generated_calls_with_array_like_or_spread_
Additional Inherited Members
Detailed Description
Definition at line 41 of file js-call-reducer.h.
Member Typedef Documentation
Flags
using v8::internal::compiler::JSCallReducer::Flags = base::Flags<Flag>
Definition at line 49 of file js-call-reducer.h.
Member Enumeration Documentation
ArrayIteratorKind
enum v8::internal::compiler::JSCallReducer::ArrayIteratorKind [strong], [private]
Enumerator
kArrayLike
kTypedArray
Definition at line 129 of file js-call-reducer.h.
{ kArrayLike, kTypedArray };
DataViewAccess
enum v8::internal::compiler::JSCallReducer::DataViewAccess [strong], [private]
Enumerator
kGet
kSet
Definition at line 238 of file js-call-reducer.h.
{ kGet, kSet };
Flag
enum v8::internal::compiler::JSCallReducer::Flag
Enumerator
kNoFlags
kBailoutOnUninitialized
kInlineJSToWasmCalls
Definition at line 44 of file js-call-reducer.h.
            {
    kNoFlags = 0u,
    kBailoutOnUninitialized = 1u << 0,
    kInlineJSToWasmCalls = 1u << 1,
  };
StringIndexOfIncludesVariant
enum v8::internal::compiler::JSCallReducer::StringIndexOfIncludesVariant [strong], [private]
Enumerator
kIncludes
kIndexOf
Definition at line 157 of file js-call-reducer.h.
{ kIncludes, kIndexOf };
Constructor & Destructor Documentation
JSCallReducer()
v8::internal::compiler::JSCallReducer::JSCallReducer (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker, Zone * temp_zone, Flags flags) [inline]
Definition at line 51 of file js-call-reducer.h.
      : AdvancedReducer(editor),
        jsgraph_(jsgraph),
        broker_(broker),
        temp_zone_(temp_zone),
        flags_(flags) {}
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::JSCallReducer::broker () const [inline]
Definition at line 86 of file js-call-reducer.h.
{ return broker_; }
Referenced by CreateClosureFromBuiltinSharedFunctionInfo(), dependencies(), DoPromiseChecks(), IsBuiltinOrApiFunction(), native_context(), ReduceArrayBufferViewAccessor(), ReduceArrayBufferViewByteLengthAccessor(), ReduceArrayBufferViewByteOffsetAccessor(), ReduceArrayEvery(), ReduceArrayFilter(), ReduceArrayFind(), ReduceArrayFindIndex(), ReduceArrayForEach(), ReduceArrayIncludes(), ReduceArrayIndexOf(), ReduceArrayIterator(), ReduceArrayIteratorPrototypeNext(), ReduceArrayMap(), ReduceArrayPrototypeAt(), ReduceArrayPrototypePop(), ReduceArrayPrototypePush(), ReduceArrayPrototypeShift(), ReduceArrayPrototypeSlice(), ReduceArrayReduce(), ReduceArrayReduceRight(), ReduceArraySome(), ReduceBigIntConstructor(), ReduceCallApiFunction(), ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), ReduceCollectionIteration(), ReduceCollectionIteratorPrototypeNext(), ReduceCollectionPrototypeHas(), ReduceCollectionPrototypeSize(), ReduceDataViewAccess(), ReduceDatePrototypeGetField(), ReduceDatePrototypeGetTime(), ReduceFunctionPrototypeApply(), ReduceFunctionPrototypeBind(), ReduceFunctionPrototypeCall(), ReduceJSCall(), ReduceJSCallWithArrayLike(), ReduceJSCallWithSpread(), ReduceJSConstruct(), ReduceMapPrototypeGet(), ReduceNumberConstructor(), ReduceNumberParseInt(), ReduceObjectConstructor(), ReduceObjectGetPrototype(), ReduceObjectPrototypeHasOwnProperty(), ReduceObjectPrototypeIsPrototypeOf(), ReducePromisePrototypeCatch(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReducePromiseResolveTrampoline(), ReduceRegExpPrototypeTest(), ReduceStringIteratorPrototypeNext(), ReduceStringPrototypeCharAt(), ReduceStringPrototypeEndsWith(), ReduceStringPrototypeStartsWith(), ReduceTypedArrayPrototypeLength(), and TryReduceJSCallMathMinMaxWithArrayLike().
CheckArrayLength()
Node * v8::internal::compiler::JSCallReducer::CheckArrayLength (Node * array, ElementsKind elements_kind, uint32_t array_length, const FeedbackSource & feedback_source, Effect effect, Control control) [private]
Definition at line 4350 of file js-call-reducer.cc.
                                                                      {
  Node* length = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSArrayLength(elements_kind)),
      array, effect, control);
  Node* check = graph()->NewNode(simplified()->NumberEqual(), length,
                                 jsgraph()->ConstantNoHole(array_length));
  return graph()->NewNode(
      simplified()->CheckIf(DeoptimizeReason::kArrayLengthChanged,
                            feedback_source),
      check, effect, control);
}
References v8::internal::compiler::AccessBuilder::ForJSArrayLength(), graph(), jsgraph(), v8::internal::length, v8::internal::compiler::TFGraph::NewNode(), and simplified().
Referenced by ReduceCallOrConstructWithArrayLikeOrSpread().
CheckIfConstructor()
void v8::internal::compiler::JSCallReducer::CheckIfConstructor (Node * call) [private]
Definition at line 4273 of file js-call-reducer.cc.
                                                      {
  JSConstructNode n(construct);
  Node* new_target = n.new_target();
  Control control = n.control();
  Node* check =
      graph()->NewNode(simplified()->ObjectIsConstructor(), new_target);
  Node* check_branch =
      graph()->NewNode(common()->Branch(BranchHint::kTrue), check, control);
  Node* check_fail = graph()->NewNode(common()->IfFalse(), check_branch);
  Node* check_throw = check_fail = graph()->NewNode(
      javascript()->CallRuntime(Runtime::kThrowTypeError, 2),
      jsgraph()->ConstantNoHole(
          static_cast<int>(MessageTemplate::kNotConstructor)),
      new_target, n.context(), n.frame_state(), n.effect(), check_fail);
  control = graph()->NewNode(common()->IfTrue(), check_branch);
  NodeProperties::ReplaceControlInput(construct, control);
  // Rewire potential exception edges.
  Node* on_exception = nullptr;
  if (NodeProperties::IsExceptionalCall(construct, &on_exception)) {
    // Create appropriate {IfException} and {IfSuccess} nodes.
    Node* if_exception =
        graph()->NewNode(common()->IfException(), check_throw, check_fail);
    check_fail = graph()->NewNode(common()->IfSuccess(), check_fail);
    // Join the exception edges.
    Node* merge =
        graph()->NewNode(common()->Merge(2), if_exception, on_exception);
    Node* ephi = graph()->NewNode(common()->EffectPhi(2), if_exception,
                                  on_exception, merge);
    Node* phi =
        graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                         if_exception, on_exception, merge);
    ReplaceWithValue(on_exception, phi, ephi, merge);
    merge->ReplaceInput(1, on_exception);
    ephi->ReplaceInput(1, on_exception);
    phi->ReplaceInput(1, on_exception);
  }
  // The above %ThrowTypeError runtime call is an unconditional throw,
  // making it impossible to return a successful completion in this case. We
  // simply connect the successful completion to the graph end.
  Node* throw_node =
      graph()->NewNode(common()->Throw(), check_throw, check_fail);
  MergeControlToEnd(graph(), common(), throw_node);
}
References common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), graph(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), javascript(), jsgraph(), v8::internal::kTagged, v8::internal::kTrue, v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), and simplified().
Referenced by ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), and ReduceJSConstructForwardAllArgs().
CheckIfElementsKind()
void v8::internal::compiler::JSCallReducer::CheckIfElementsKind (Node * receiver_elements_kind, ElementsKind kind, Node * control, Node ** if_true, Node ** if_false) [private]
Definition at line 6015 of file js-call-reducer.cc.
                                                                         {
  Node* is_packed_kind =
      graph()->NewNode(simplified()->NumberEqual(), receiver_elements_kind,
                       jsgraph()->ConstantNoHole(GetPackedElementsKind(kind)));
  Node* packed_branch =
      graph()->NewNode(common()->Branch(), is_packed_kind, control);
  Node* if_packed = graph()->NewNode(common()->IfTrue(), packed_branch);
  if (IsHoleyElementsKind(kind)) {
    Node* if_not_packed = graph()->NewNode(common()->IfFalse(), packed_branch);
    Node* is_holey_kind =
        graph()->NewNode(simplified()->NumberEqual(), receiver_elements_kind,
                         jsgraph()->ConstantNoHole(GetHoleyElementsKind(kind)));
    Node* holey_branch =
        graph()->NewNode(common()->Branch(), is_holey_kind, if_not_packed);
    Node* if_holey = graph()->NewNode(common()->IfTrue(), holey_branch);
    Node* if_not_packed_not_holey =
        graph()->NewNode(common()->IfFalse(), holey_branch);
    *if_true = graph()->NewNode(common()->Merge(2), if_packed, if_holey);
    *if_false = if_not_packed_not_holey;
  } else {
    *if_true = if_packed;
    *if_false = graph()->NewNode(common()->IfFalse(), packed_branch);
  }
}
References common(), v8::internal::GetHoleyElementsKind(), v8::internal::GetPackedElementsKind(), graph(), v8::internal::IsHoleyElementsKind(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), and simplified().
Referenced by ReduceArrayPrototypePop(), and ReduceArrayPrototypeShift().
common()
CommonOperatorBuilder * v8::internal::compiler::JSCallReducer::common () const [private]
Definition at line 9276 of file js-call-reducer.cc.
                                                   {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by CheckIfConstructor(), CheckIfElementsKind(), ReduceArrayIteratorPrototypeNext(), ReduceArrayPrototypePop(), ReduceArrayPrototypeShift(), ReduceArrayPrototypeSlice(), ReduceCallApiFunction(), ReduceCollectionIteratorPrototypeNext(), ReduceForInsufficientFeedback(), ReduceFunctionPrototypeApply(), ReduceJSConstruct(), ReduceMapPrototypeGet(), ReduceNumberParseInt(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReduceReflectGet(), ReduceReflectHas(), ReduceStringConstructor(), ReduceStringIteratorPrototypeNext(), ReduceStringPrototypeSubstr(), ReduceTypedArrayConstructor(), and ReduceTypedArrayPrototypeToStringTag().
ConvertHoleToUndefined()
Node * v8::internal::compiler::JSCallReducer::ConvertHoleToUndefined (Node * value, ElementsKind elements_kind) [private]
Definition at line 4260 of file js-call-reducer.cc.
                                                                          {
  DCHECK(IsHoleyElementsKind(kind));
  if (kind == HOLEY_DOUBLE_ELEMENTS) {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    return graph()->NewNode(
        simplified()->ChangeFloat64OrUndefinedOrHoleToTagged(), value);
#else
    return graph()->NewNode(simplified()->ChangeFloat64HoleToTagged(), value);
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  }
  return graph()->NewNode(simplified()->ConvertTaggedHoleToUndefined(), value);
}
References v8::internal::DCHECK(), graph(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::IsHoleyElementsKind(), v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
Referenced by ReduceArrayIteratorPrototypeNext(), and ReduceCallOrConstructWithArrayLikeOrSpread().
CreateClosureFromBuiltinSharedFunctionInfo()
Node * v8::internal::compiler::JSCallReducer::CreateClosureFromBuiltinSharedFunctionInfo (SharedFunctionInfoRef shared, Node * context, Node * effect, Node * control) [private]
Definition at line 7551 of file js-call-reducer.cc.
                                                                              {
  DCHECK(shared.HasBuiltinId());
  Handle<FeedbackCell> feedback_cell =
      isolate()->factory()->many_closures_cell();
  Callable const callable =
      Builtins::CallableFor(isolate(), shared.builtin_id());
  CodeRef code = MakeRef(broker(), *callable.code());
  return graph()->NewNode(javascript()->CreateClosure(shared, code),
                          jsgraph()->HeapConstantNoHole(feedback_cell), context,
                          effect, control);
}
References broker(), v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), code, v8::internal::DCHECK(), v8::internal::Isolate::factory(), graph(), v8::internal::compiler::HeapConstantNoHole(), isolate(), javascript(), jsgraph(), v8::internal::compiler::MakeRef(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by ReducePromisePrototypeFinally().
dependencies()
CompilationDependencies * v8::internal::compiler::JSCallReducer::dependencies () const
Definition at line 9262 of file js-call-reducer.cc.
                                                           {
  return broker()->dependencies();
}
References broker(), and v8::internal::compiler::JSHeapBroker::dependencies().
Referenced by ReduceArrayBufferViewAccessor(), ReduceArrayBufferViewByteLengthAccessor(), ReduceArrayEvery(), ReduceArrayFilter(), ReduceArrayFind(), ReduceArrayFindIndex(), ReduceArrayForEach(), ReduceArrayIncludes(), ReduceArrayIndexOf(), ReduceArrayIterator(), ReduceArrayIteratorPrototypeNext(), ReduceArrayMap(), ReduceArrayPrototypeAt(), ReduceArrayPrototypePop(), ReduceArrayPrototypePush(), ReduceArrayPrototypeShift(), ReduceArrayPrototypeSlice(), ReduceArrayReduce(), ReduceArrayReduceRight(), ReduceArraySome(), ReduceCallApiFunction(), ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), ReduceCollectionIteratorPrototypeNext(), ReduceDataViewAccess(), ReduceDatePrototypeGetField(), ReduceFunctionPrototypeBind(), ReduceObjectGetPrototype(), ReduceObjectPrototypeHasOwnProperty(), ReducePromiseConstructor(), ReducePromisePrototypeCatch(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReduceRegExpPrototypeTest(), ReduceTypedArrayPrototypeLength(), and TryReduceJSCallMathMinMaxWithArrayLike().
DoPromiseChecks()
bool v8::internal::compiler::JSCallReducer::DoPromiseChecks (MapInference * inference) [private]
Definition at line 7494 of file js-call-reducer.cc.
                                                           {
  if (!inference->HaveMaps()) return false;
  ZoneRefSet<Map> const& receiver_maps = inference->GetMaps();
  // Check whether all {receiver_maps} are JSPromise maps and
  // have the initial Promise.prototype as their [[Prototype]].
  for (MapRef receiver_map : receiver_maps) {
    if (!receiver_map.IsJSPromiseMap()) return false;
    HeapObjectRef prototype = receiver_map.prototype(broker());
    if (!prototype.equals(native_context().promise_prototype(broker()))) {
      return false;
    }
  }
  return true;
}
References broker(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::MapInference::HaveMaps(), native_context(), and v8::internal::prototype.
Referenced by ReducePromisePrototypeCatch(), ReducePromisePrototypeFinally(), and ReducePromisePrototypeThen().
factory()
Factory * v8::internal::compiler::JSCallReducer::factory () const [private]
Definition at line 9270 of file js-call-reducer.cc.
{ return isolate()->factory(); }
References v8::internal::Isolate::factory(), and isolate().
Referenced by ReduceArrayPrototypeSlice(), ReduceJSCall(), ReduceNumberParseInt(), ReducePromisePrototypeFinally(), ReduceReflectGet(), and ReduceReflectHas().
Finalize()
void v8::internal::compiler::JSCallReducer::Finalize () [final], [virtual]
Reimplemented from v8::internal::compiler::Reducer.
Definition at line 2788 of file js-call-reducer.cc.
                             {
  // TODO(turbofan): This is not the best solution; ideally we would be able
  // to teach the GraphReducer about arbitrary dependencies between different
  // nodes, even if they don't show up in the use list of the other node.
  std::set<Node*> const waitlist = std::move(waitlist_);
  for (Node* node : waitlist) {
    if (!node->IsDead()) {
      // Remember the max node id before reduction.
      NodeId const max_id = static_cast<NodeId>(graph()->NodeCount() - 1);
      Reduction const reduction = Reduce(node);
      if (reduction.Changed()) {
        Node* replacement = reduction.replacement();
        if (replacement != node) {
          Replace(node, replacement, max_id);
        }
      }
    }
  }
}
References v8::internal::compiler::Reduction::Changed(), graph(), v8::internal::compiler::TFGraph::NodeCount(), Reduce(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::Reduction::replacement(), and waitlist_.
flags()
Flags v8::internal::compiler::JSCallReducer::flags () const [inline], [private]
Definition at line 300 of file js-call-reducer.h.
{ return flags_; }
Referenced by ReduceForInsufficientFeedback(), and ReduceJSCall().
graph()
TFGraph * v8::internal::compiler::JSCallReducer::graph () const [private]
Definition at line 9266 of file js-call-reducer.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by CheckArrayLength(), CheckIfConstructor(), CheckIfElementsKind(), ConvertHoleToUndefined(), CreateClosureFromBuiltinSharedFunctionInfo(), Finalize(), LoadReceiverElementsKind(), ReduceArrayIteratorPrototypeNext(), ReduceArrayPrototypePop(), ReduceArrayPrototypeShift(), ReduceArrayPrototypeSlice(), ReduceBigIntAsN(), ReduceBooleanConstructor(), ReduceCallApiFunction(), ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), ReduceCollectionIteration(), ReduceCollectionIteratorPrototypeNext(), ReduceCollectionPrototypeHas(), ReduceCollectionPrototypeSize(), ReduceDataViewAccess(), ReduceDateNow(), ReduceDatePrototypeGetTime(), ReduceForInsufficientFeedback(), ReduceFunctionPrototypeApply(), ReduceFunctionPrototypeBind(), ReduceFunctionPrototypeCall(), ReduceGlobalIsFinite(), ReduceGlobalIsNaN(), ReduceJSCall(), ReduceJSConstruct(), ReduceJSConstructForwardAllArgs(), ReduceMapPrototypeGet(), ReduceMathClz32(), ReduceMathImul(), ReduceMathMinMax(), ReduceNumberIsFinite(), ReduceNumberIsInteger(), ReduceNumberIsNaN(), ReduceNumberIsSafeInteger(), ReduceNumberParseInt(), ReduceObjectIs(), ReduceObjectPrototypeHasOwnProperty(), ReducePromisePrototypeCatch(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReduceReflectApply(), ReduceReflectConstruct(), ReduceReflectGet(), ReduceReflectHas(), ReduceRegExpPrototypeTest(), ReduceStringConstructor(), ReduceStringFromCharCode(), ReduceStringFromCodePoint(), ReduceStringIteratorPrototypeNext(), ReduceStringPrototypeConcat(), ReduceStringPrototypeIndexOfIncludes(), ReduceStringPrototypeIterator(), ReduceStringPrototypeStringCodePointAt(), ReduceStringPrototypeSubstr(), ReduceTypedArrayConstructor(), ReduceTypedArrayPrototypeToStringTag(), and TryReduceJSCallMathMinMaxWithArrayLike().
IsBuiltinOrApiFunction()
bool v8::internal::compiler::JSCallReducer::IsBuiltinOrApiFunction (JSFunctionRef target_ref) const [private]
Definition at line 4692 of file js-call-reducer.cc.
                                                                       {
  // TODO(neis): Add a way to check if function template info isn't serialized
  // and add a warning in such cases. Currently we can't tell if function
  // template info doesn't exist or wasn't serialized.
  return function.shared(broker()).HasBuiltinId() ||
         function.shared(broker()).function_template_info(broker()).has_value();
}
References broker().
isolate()
Isolate * v8::internal::compiler::JSCallReducer::isolate () const [private]
Definition at line 9268 of file js-call-reducer.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
Referenced by CreateClosureFromBuiltinSharedFunctionInfo(), factory(), ReduceArrayPrototypeSlice(), ReduceCallApiFunction(), ReduceCollectionIteratorPrototypeNext(), ReduceJSCall(), and ReduceReflectGet().
javascript()
JSOperatorBuilder * v8::internal::compiler::JSCallReducer::javascript () const [private]
Definition at line 9280 of file js-call-reducer.cc.
                                                   {
  return jsgraph()->javascript();
}
References v8::internal::compiler::JSGraph::javascript(), and jsgraph().
Referenced by CheckIfConstructor(), CreateClosureFromBuiltinSharedFunctionInfo(), ReduceArrayConstructor(), ReduceArrayIsArray(), ReduceArrayIterator(), ReduceArrayIteratorPrototypeNext(), ReduceBigIntConstructor(), ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), ReduceCollectionIteration(), ReduceCollectionIteratorPrototypeNext(), ReduceFunctionPrototypeApply(), ReduceFunctionPrototypeBind(), ReduceFunctionPrototypeCall(), ReduceFunctionPrototypeHasInstance(), ReduceJSCall(), ReduceJSConstruct(), ReduceJSConstructForwardAllArgs(), ReduceNumberConstructor(), ReduceNumberParseInt(), ReduceObjectConstructor(), ReduceObjectCreate(), ReduceObjectPrototypeIsPrototypeOf(), ReducePromisePrototypeCatch(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReducePromiseResolveTrampoline(), ReduceReflectApply(), ReduceReflectConstruct(), ReduceReflectGet(), ReduceReflectHas(), ReduceRegExpPrototypeTest(), ReduceStringConstructor(), ReduceStringIteratorPrototypeNext(), ReduceStringPrototypeIterator(), and ReduceTypedArrayConstructor().
jsgraph()
JSGraph* v8::internal::compiler::JSCallReducer::jsgraph () const [inline], [private]
Definition at line 292 of file js-call-reducer.h.
{ return jsgraph_; }
Referenced by CheckArrayLength(), CheckIfConstructor(), CheckIfElementsKind(), common(), CreateClosureFromBuiltinSharedFunctionInfo(), graph(), isolate(), javascript(), LoadReceiverElementsKind(), ReduceArrayBufferIsView(), ReduceArrayBufferViewByteLengthAccessor(), ReduceArrayEvery(), ReduceArrayFilter(), ReduceArrayFind(), ReduceArrayFindIndex(), ReduceArrayForEach(), ReduceArrayIncludes(), ReduceArrayIndexOf(), ReduceArrayIsArray(), ReduceArrayIterator(), ReduceArrayIteratorPrototypeNext(), ReduceArrayMap(), ReduceArrayPrototypeAt(), ReduceArrayPrototypePop(), ReduceArrayPrototypePush(), ReduceArrayPrototypeShift(), ReduceArrayPrototypeSlice(), ReduceArrayReduce(), ReduceArrayReduceRight(), ReduceArraySome(), ReduceBigIntAsN(), ReduceBigIntConstructor(), ReduceBooleanConstructor(), ReduceCallApiFunction(), ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceCollectionIteratorPrototypeNext(), ReduceCollectionPrototypeHas(), ReduceDataViewAccess(), ReduceDatePrototypeGetField(), ReduceForInsufficientFeedback(), ReduceFunctionPrototypeApply(), ReduceFunctionPrototypeBind(), ReduceFunctionPrototypeCall(), ReduceFunctionPrototypeHasInstance(), ReduceGlobalIsFinite(), ReduceGlobalIsNaN(), ReduceJSCall(), ReduceJSConstruct(), ReduceMapPrototypeGet(), ReduceMathBinary(), ReduceMathClz32(), ReduceMathImul(), ReduceMathUnary(), ReduceNumberConstructor(), ReduceNumberIsFinite(), ReduceNumberIsInteger(), ReduceNumberIsNaN(), ReduceNumberIsSafeInteger(), ReduceNumberParseInt(), ReduceObjectCreate(), ReduceObjectGetPrototype(), ReduceObjectGetPrototypeOf(), ReduceObjectIs(), ReduceObjectPrototypeHasOwnProperty(), ReduceObjectPrototypeIsPrototypeOf(), ReducePromisePrototypeCatch(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReducePromiseResolveTrampoline(), ReduceReflectApply(), ReduceReflectConstruct(), ReduceReflectGet(), ReduceReflectGetPrototypeOf(), ReduceReflectHas(), ReduceRegExpPrototypeTest(), ReduceStringConstructor(), ReduceStringFromCodePoint(), ReduceStringIteratorPrototypeNext(), ReduceStringPrototypeCharAt(), ReduceStringPrototypeConcat(), ReduceStringPrototypeEndsWith(), ReduceStringPrototypeIndexOfIncludes(), ReduceStringPrototypeIterator(), ReduceStringPrototypeStartsWith(), ReduceStringPrototypeStringCodePointAt(), ReduceStringPrototypeSubstr(), ReduceTypedArrayConstructor(), ReduceTypedArrayPrototypeToStringTag(), simplified(), and TryReduceJSCallMathMinMaxWithArrayLike().
JSGraphForGraphAssembler()
JSGraph* v8::internal::compiler::JSCallReducer::JSGraphForGraphAssembler () const [inline]
Definition at line 74 of file js-call-reducer.h.
{ return jsgraph(); }
LoadReceiverElementsKind()
Node * v8::internal::compiler::JSCallReducer::LoadReceiverElementsKind (Node * receiver, Effect * effect, Control control) [private]
Definition at line 5996 of file js-call-reducer.cc.
                                                               {
  Node* effect_node = *effect;
  Node* receiver_map = effect_node =
      graph()->NewNode(simplified()->LoadField(AccessBuilder::ForMap()),
                       receiver, effect_node, control);
  Node* receiver_bit_field2 = effect_node = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForMapBitField2()), receiver_map,
      effect_node, control);
  Node* receiver_elements_kind = graph()->NewNode(
      simplified()->NumberShiftRightLogical(),
      graph()->NewNode(
          simplified()->NumberBitwiseAnd(), receiver_bit_field2,
          jsgraph()->ConstantNoHole(Map::Bits2::ElementsKindBits::kMask)),
      jsgraph()->ConstantNoHole(Map::Bits2::ElementsKindBits::kShift));
  *effect = effect_node;
  return receiver_elements_kind;
}
References v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::AccessBuilder::ForMapBitField2(), graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), and simplified().
Referenced by ReduceArrayPrototypePop(), and ReduceArrayPrototypeShift().
native_context()
NativeContextRef v8::internal::compiler::JSCallReducer::native_context () const [private]
Definition at line 9272 of file js-call-reducer.cc.
                                                     {
  return broker()->target_native_context();
}
References broker(), and v8::internal::compiler::JSHeapBroker::target_native_context().
Referenced by DoPromiseChecks(), ReduceArrayEvery(), ReduceArrayFilter(), ReduceArrayFind(), ReduceArrayFindIndex(), ReduceArrayMap(), ReduceArraySome(), ReduceBigIntConstructor(), ReduceCallApiFunction(), ReduceFunctionPrototypeBind(), ReduceJSCall(), ReduceJSConstruct(), ReduceNumberConstructor(), ReducePromiseConstructor(), ReducePromisePrototypeCatch(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReduceRegExpPrototypeTest(), ReduceStringConstructor(), and TryReduceJSCallMathMinMaxWithArrayLike().
Reduce()
Reduction v8::internal::compiler::JSCallReducer::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 2766 of file js-call-reducer.cc.
                                          {
  switch (node->opcode()) {
    case IrOpcode::kJSConstruct:
      return ReduceJSConstruct(node);
    case IrOpcode::kJSConstructWithArrayLike:
      return ReduceJSConstructWithArrayLike(node);
    case IrOpcode::kJSConstructWithSpread:
      return ReduceJSConstructWithSpread(node);
    case IrOpcode::kJSConstructForwardAllArgs:
      return ReduceJSConstructForwardAllArgs(node);
    case IrOpcode::kJSCall:
      return ReduceJSCall(node);
    case IrOpcode::kJSCallWithArrayLike:
      return ReduceJSCallWithArrayLike(node);
    case IrOpcode::kJSCallWithSpread:
      return ReduceJSCallWithSpread(node);
    default:
      break;
  }
  return NoChange();
}
References v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), ReduceJSCall(), ReduceJSCallWithArrayLike(), ReduceJSCallWithSpread(), ReduceJSConstruct(), ReduceJSConstructForwardAllArgs(), ReduceJSConstructWithArrayLike(), and ReduceJSConstructWithSpread().
Referenced by Finalize().
ReduceArrayBufferIsView()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayBufferIsView (Node * node) [private]
Definition at line 8534 of file js-call-reducer.cc.
                                                           {
  JSCallNode n(node);
  Node* value = n.ArgumentOrUndefined(0, jsgraph());
  RelaxEffectsAndControls(node);
  node->ReplaceInput(0, value);
  node->TrimInputCount(1);
  NodeProperties::ChangeOp(node, simplified()->ObjectIsArrayBufferView());
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), jsgraph(), v8::internal::compiler::AdvancedReducer::RelaxEffectsAndControls(), v8::internal::compiler::Node::ReplaceInput(), simplified(), v8::internal::compiler::Node::TrimInputCount(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceArrayBufferViewAccessor()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor (Node * node, InstanceType instance_type, FieldAccess const & access, Builtin builtin) [private]
Definition at line 8544 of file js-call-reducer.cc.
                     {
  // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
  TNode<JSArrayBufferView> receiver = TNode<JSArrayBufferView>::UncheckedCast(
      NodeProperties::GetValueInput(node, 1));
  Effect effect{NodeProperties::GetEffectInput(node)};
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() ||
      !inference.AllOfInstanceTypesAre(instance_type)) {
    return inference.NoChange();
  }
  DCHECK_IMPLIES((builtin == Builtin::kTypedArrayPrototypeLength ||
                  builtin == Builtin::kTypedArrayPrototypeByteLength),
                 base::none_of(inference.GetMaps(), [](MapRef map) {
                   return IsRabGsabTypedArrayElementsKind(map.elements_kind());
                 }));
  if (!inference.RelyOnMapsViaStability(dependencies())) {
    return inference.NoChange();
  }
  const bool depended_on_detaching_protector =
      dependencies()->DependOnArrayBufferDetachingProtector();
  if (!depended_on_detaching_protector && instance_type == JS_DATA_VIEW_TYPE) {
    // DataView prototype accessors throw on detached ArrayBuffers instead of
    // return 0, so skip the optimization.
    //
    // TODO(turbofan): Ideally we would bail out if the buffer is actually
    // detached.
    return inference.NoChange();
  }
  JSCallReducerAssembler a(this, node, effect);
  // Load the {receiver}s field.
  DCHECK_EQ(access.machine_type.representation(),
            MachineType::PointerRepresentation());
  TNode<UintPtrT> value = a.EnterMachineGraph<UintPtrT>(
      a.LoadField<UintPtrT>(access, receiver), UseInfo::Word());
  // See if we can skip the detaching check.
  if (!depended_on_detaching_protector) {
    // Check whether {receiver}s JSArrayBuffer was detached.
    //
    // TODO(turbofan): Ideally we would bail out here if the {receiver}s
    // JSArrayBuffer was detached, but there's no way to guard against
    // deoptimization loops right now, since the JSCall {node} is usually
    // created from a LOAD_IC inlining, and so there's no CALL_IC slot
    // from which we could use the speculation bit.
    value = a.MachineSelect<UintPtrT>(a.ArrayBufferViewDetachedBit(receiver),
                                      a.UintPtrConstant(0), value,
                                      BranchHint::kFalse);
  }
  if (builtin == Builtin::kTypedArrayPrototypeLength) {
    TNode<UintPtrT> byte_length = value;
    // Divide the byte length by element size.
    TNode<Map> map = a.LoadMap(TNode<HeapObject>::UncheckedCast(receiver));
    TNode<Uint32T> elements_kind = a.LoadElementsKind(map);
    TNode<Uint32T> shift = a.LookupByteShiftForElementsKind(elements_kind);
    value = TNode<UintPtrT>::UncheckedCast(
        a.WordShr(byte_length, a.ChangeUint32ToUintPtr(shift)));
  }
  TNode<Number> result =
      a.ExitMachineGraph<Number>(value, MachineType::PointerRepresentation(),
                                 TypeCache::Get()->kJSTypedArrayLengthType);
  return ReplaceWithSubgraph(&a, result);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), v8::internal::compiler::JSGraphAssembler::ArrayBufferViewDetachedBit(), broker(), v8::internal::compiler::GraphAssembler::ChangeUint32ToUintPtr(), DCHECK_EQ, DCHECK_IMPLIES, dependencies(), v8::internal::compiler::CompilationDependencies::DependOnArrayBufferDetachingProtector(), v8::internal::compiler::JSCallReducerAssembler::EnterMachineGraph(), v8::internal::compiler::JSCallReducerAssembler::ExitMachineGraph(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::kFalse, v8::internal::compiler::TypeCache::kJSTypedArrayLengthType, v8::internal::compiler::JSGraphAssembler::LoadElementsKind(), v8::internal::compiler::JSGraphAssembler::LoadField(), v8::internal::compiler::JSGraphAssembler::LoadMap(), v8::internal::compiler::JSGraphAssembler::LookupByteShiftForElementsKind(), v8::internal::compiler::FieldAccess::machine_type, v8::internal::compiler::JSGraphAssembler::MachineSelect(), v8::internal::compiler::MapInference::NoChange(), v8::base::none_of(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::MapInference::RelyOnMapsViaStability(), ReplaceWithSubgraph(), v8::internal::MachineType::representation(), v8::base::internal::result, v8::internal::compiler::GraphAssembler::UintPtrConstant(), v8::internal::TNode< T >::UncheckedCast(), v8::internal::value, and v8::internal::compiler::UseInfo::Word().
Referenced by ReduceArrayBufferViewByteLengthAccessor(), ReduceArrayBufferViewByteOffsetAccessor(), and ReduceTypedArrayPrototypeLength().
ReduceArrayBufferViewByteLengthAccessor()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor (Node * node, InstanceType instance_type, Builtin builtin) [private]
Definition at line 7883 of file js-call-reducer.cc.
                                                             {
  // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
  DCHECK(instance_type == JS_TYPED_ARRAY_TYPE ||
         instance_type == JS_DATA_VIEW_TYPE);
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() ||
      !inference.AllOfInstanceTypesAre(instance_type)) {
    return inference.NoChange();
  }
  std::set<ElementsKind> elements_kinds;
  bool maybe_rab_gsab = false;
  if (instance_type == JS_TYPED_ARRAY_TYPE) {
    for (MapRef map : inference.GetMaps()) {
      ElementsKind kind = map.elements_kind();
      elements_kinds.insert(kind);
      if (IsRabGsabTypedArrayElementsKind(kind)) maybe_rab_gsab = true;
    }
  }
  if (!maybe_rab_gsab) {
    // We do not perform any change depending on this inference.
    Reduction unused_reduction = inference.NoChange();
    USE(unused_reduction);
    // Call default implementation for non-rab/gsab TAs.
    return ReduceArrayBufferViewAccessor(
        node, instance_type, AccessBuilder::ForJSArrayBufferViewByteLength(),
        builtin);
  }
  const CallParameters& p = CallParametersOf(node->op());
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return inference.NoChange();
  }
  DCHECK(p.feedback().IsValid());
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  const bool depended_on_detaching_protector =
      dependencies()->DependOnArrayBufferDetachingProtector();
  if (!depended_on_detaching_protector && instance_type == JS_DATA_VIEW_TYPE) {
    // DataView prototype accessors throw on detached ArrayBuffers instead of
    // return 0, so skip the optimization.
    //
    // TODO(turbofan): Ideally we would bail out if the buffer is actually
    // detached.
    return inference.NoChange();
  }
  JSCallReducerAssembler a(this, node);
  TNode<JSTypedArray> typed_array =
      TNode<JSTypedArray>::UncheckedCast(receiver);
  TNode<Number> length = a.ArrayBufferViewByteLength(
      typed_array, instance_type, std::move(elements_kinds), a.ContextInput());
  return ReplaceWithSubgraph(&a, length);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), v8::internal::compiler::JSGraphAssembler::ArrayBufferViewByteLength(), broker(), v8::internal::compiler::CallParametersOf(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::DCHECK(), dependencies(), v8::internal::compiler::CompilationDependencies::DependOnArrayBufferDetachingProtector(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteLength(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::internal::compiler::FeedbackSource::IsValid(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::length, v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::Node::op(), ReduceArrayBufferViewAccessor(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), ReplaceWithSubgraph(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::TNode< T >::UncheckedCast(), and USE.
Referenced by ReduceJSCall().
ReduceArrayBufferViewByteOffsetAccessor()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor (Node * node, InstanceType instance_type, Builtin builtin) [private]
Definition at line 7947 of file js-call-reducer.cc.
                                                             {
  // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
  DCHECK(instance_type == JS_TYPED_ARRAY_TYPE ||
         instance_type == JS_DATA_VIEW_TYPE);
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() ||
      !inference.AllOfInstanceTypesAre(instance_type)) {
    return inference.NoChange();
  }
  std::set<ElementsKind> elements_kinds;
  bool maybe_rab_gsab = false;
  if (instance_type == JS_TYPED_ARRAY_TYPE) {
    for (MapRef map : inference.GetMaps()) {
      ElementsKind kind = map.elements_kind();
      elements_kinds.insert(kind);
      if (IsRabGsabTypedArrayElementsKind(kind)) maybe_rab_gsab = true;
    }
  }
  if (!maybe_rab_gsab) {
    // We do not perform any change depending on this inference.
    Reduction unused_reduction = inference.NoChange();
    USE(unused_reduction);
    // Call default implementation for non-rab/gsab TAs.
    return ReduceArrayBufferViewAccessor(
        node, instance_type, AccessBuilder::ForJSArrayBufferViewByteOffset(),
        builtin);
  }
  // TODO(v8:11111): Optimize for RAG/GSAB TypedArray/DataView.
  return inference.NoChange();
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), broker(), v8::internal::DCHECK(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteOffset(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::internal::compiler::MapInference::NoChange(), ReduceArrayBufferViewAccessor(), and USE.
Referenced by ReduceJSCall().
ReduceArrayConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayConstructor (Node * node) [private]
Definition at line 2809 of file js-call-reducer.cc.
                                                          {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() == SpeculationMode::kDisallowSpeculation) {
    return NoChange();
  }
  // Turn the {node} into a {JSCreateArray} call.
  Node* target = n.target();
  size_t const arity = p.arity_without_implicit_args();
  node->RemoveInput(n.FeedbackVectorIndex());
  NodeProperties::ReplaceValueInput(node, target, 0);
  NodeProperties::ReplaceValueInput(node, target, 1);
  NodeProperties::ChangeOp(
      node, javascript()->CreateArray(arity, std::nullopt,
                                      n.Parameters().feedback()));
  return Changed(node);
}
References v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::JSCallOrConstructNode::FeedbackVectorIndex(), javascript(), v8::internal::kDisallowSpeculation, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceArrayEvery()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayEvery (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3845 of file js-call-reducer.cc.
                                                                        {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeEverySome(
      h.inference(), h.has_stability_dependency(), h.elements_kind(), shared,
      native_context(), ArrayEverySomeVariant::kEvery);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kEvery, native_context(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayFilter()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayFilter (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3798 of file js-call-reducer.cc.
                                                                         {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  // Calls CreateArray and thus requires this additional protector dependency.
  if (!dependencies()->DependOnArraySpeciesProtector()) {
    return h.inference()->NoChange();
  }
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph =
      a.ReduceArrayPrototypeFilter(h.inference(), h.has_stability_dependency(),
                                   h.elements_kind(), shared, native_context());
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), native_context(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayFind()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayFind (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3817 of file js-call-reducer.cc.
                                                                       {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeFind(
      h.inference(), h.has_stability_dependency(), h.elements_kind(), shared,
      native_context(), ArrayFindVariant::kFind);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kFind, native_context(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayFindIndex()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayFindIndex (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3831 of file js-call-reducer.cc.
                                                                            {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeFind(
      h.inference(), h.has_stability_dependency(), h.elements_kind(), shared,
      native_context(), ArrayFindVariant::kFindIndex);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kFindIndex, native_context(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayForEach()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayForEach (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3741 of file js-call-reducer.cc.
                                                                          {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeForEach(
      h.inference(), h.has_stability_dependency(), h.elements_kind(), shared);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayIncludes()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayIncludes (Node * node) [private]
Definition at line 3861 of file js-call-reducer.cc.
                                                       {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeIndexOfIncludes(
      h.elements_kind(), ArrayIndexOfIncludesVariant::kIncludes);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kIncludes, v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayIndexOf()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayIndexOf (Node * node) [private]
Definition at line 3875 of file js-call-reducer.cc.
                                                      {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeIndexOfIncludes(
      h.elements_kind(), ArrayIndexOfIncludesVariant::kIndexOf);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kIndexOf, v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayIsArray()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayIsArray (Node * node) [private]
Definition at line 6604 of file js-call-reducer.cc.
                                                      {
  // We certainly know that undefined is not an array.
  JSCallNode n(node);
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Node* object = n.Argument(0);
  node->ReplaceInput(0, object);
  node->ReplaceInput(1, context);
  node->ReplaceInput(2, frame_state);
  node->ReplaceInput(3, effect);
  node->ReplaceInput(4, control);
  node->TrimInputCount(5);
  NodeProperties::ChangeOp(node, javascript()->ObjectIsArray());
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), javascript(), jsgraph(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::Node::TrimInputCount(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceArrayIterator()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayIterator (Node * node, ArrayIteratorKind array_kind, IterationKind iteration_kind) [private]
Definition at line 6628 of file js-call-reducer.cc.
                                                                           {
  JSCallNode n(node);
  Node* receiver = n.receiver();
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  // Check if we know that {receiver} is a valid JSReceiver.
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() || !inference.AllOfInstanceTypesAreJSReceiver()) {
    return NoChange();
  }
  // TypedArray iteration is stricter: it throws if the receiver is not a typed
  // array. So don't bother optimizing in that case.
  if (array_kind == ArrayIteratorKind::kTypedArray &&
      !inference.AllOfInstanceTypesAre(InstanceType::JS_TYPED_ARRAY_TYPE)) {
    return NoChange();
  }
  if (array_kind == ArrayIteratorKind::kTypedArray) {
    // Make sure we deopt when the JSArrayBuffer is detached.
    if (!dependencies()->DependOnArrayBufferDetachingProtector()) {
      CallParameters const& p = CallParametersOf(node->op());
      if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
        return NoChange();
      }
      std::set<ElementsKind> elements_kinds;
      for (MapRef map : inference.GetMaps()) {
        elements_kinds.insert(map.elements_kind());
      }
      // The following detach check is built with the given {elements_kinds} in
      // mind, so we have to install dependency on those.
      inference.RelyOnMapsPreferStability(
          dependencies(), jsgraph(), &effect, control,
          CallParametersOf(node->op()).feedback());
      JSCallReducerAssembler a(this, node);
      a.CheckIfTypedArrayWasDetachedOrOutOfBounds(
          TNode<JSTypedArray>::UncheckedCast(receiver),
          std::move(elements_kinds), p.feedback());
      std::tie(effect, control) = ReleaseEffectAndControlFromAssembler(&a);
    }
  }
  // JSCreateArrayIterator doesn't have control output, so we bypass the old
  // JSCall node on the control chain.
  ReplaceWithValue(node, node, node, control);
  // Morph the {node} into a JSCreateArrayIterator with the given {kind}.
  node->ReplaceInput(0, receiver);
  node->ReplaceInput(1, context);
  node->ReplaceInput(2, effect);
  node->ReplaceInput(3, control);
  node->TrimInputCount(4);
  NodeProperties::ChangeOp(node,
                           javascript()->CreateArrayIterator(iteration_kind));
  return Changed(node);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), v8::internal::compiler::MapInference::AllOfInstanceTypesAreJSReceiver(), broker(), v8::internal::compiler::CallParametersOf(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSGraphAssembler::CheckIfTypedArrayWasDetachedOrOutOfBounds(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::MapInference::HaveMaps(), javascript(), jsgraph(), v8::internal::kAllowSpeculation, kTypedArray, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by ReduceJSCall().
ReduceArrayIteratorPrototypeNext()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext (Node * node) [private]
Definition at line 6693 of file js-call-reducer.cc.
                                                                    {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  Node* iterator = n.receiver();
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (iterator->opcode() != IrOpcode::kJSCreateArrayIterator) return NoChange();
  IterationKind const iteration_kind =
      CreateArrayIteratorParametersOf(iterator->op()).kind();
  Node* iterated_object = NodeProperties::GetValueInput(iterator, 0);
  Effect iterator_effect{NodeProperties::GetEffectInput(iterator)};
  MapInference inference(broker(), iterated_object, iterator_effect);
  if (!inference.HaveMaps()) return NoChange();
  ZoneRefSet<Map> const& iterated_object_maps = inference.GetMaps();
  // Check that various {iterated_object_maps} have compatible elements kinds.
  ElementsKind elements_kind = iterated_object_maps[0].elements_kind();
  if (IsTypedArrayElementsKind(elements_kind)) {
    // TurboFan doesn't support loading from BigInt typed arrays yet.
    if (elements_kind == BIGUINT64_ELEMENTS ||
        elements_kind == BIGINT64_ELEMENTS) {
      return inference.NoChange();
    }
    for (MapRef iterated_object_map : iterated_object_maps) {
      if (iterated_object_map.elements_kind() != elements_kind) {
        return inference.NoChange();
      }
    }
  } else {
    if (!CanInlineArrayIteratingBuiltin(broker(), iterated_object_maps,
                                        &elements_kind)) {
      return inference.NoChange();
    }
  }
  if (IsHoleyElementsKind(elements_kind) &&
      !dependencies()->DependOnNoElementsProtector()) {
    return inference.NoChange();
  }
  // Since the map inference was done relative to {iterator_effect} rather than
  // {effect}, we need to guard the use of the map(s) even when the inference
  // was reliable.
  inference.InsertMapChecks(jsgraph(), &effect, control, p.feedback());
  if (IsTypedArrayElementsKind(elements_kind)) {
    // See if we can skip the detaching check.
    if (!dependencies()->DependOnArrayBufferDetachingProtector()) {
      // Bail out if the {iterated_object}s JSArrayBuffer was detached.
      Node* buffer = effect = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForJSArrayBufferViewBuffer()),
          iterated_object, effect, control);
      Node* buffer_bit_field = effect = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForJSArrayBufferBitField()),
          buffer, effect, control);
      Node* check = graph()->NewNode(
          simplified()->NumberEqual(),
          graph()->NewNode(
              simplified()->NumberBitwiseAnd(), buffer_bit_field,
              jsgraph()->ConstantNoHole(JSArrayBuffer::WasDetachedBit::kMask)),
          jsgraph()->ZeroConstant());
      effect = graph()->NewNode(
          simplified()->CheckIf(DeoptimizeReason::kArrayBufferWasDetached,
                                p.feedback()),
          check, effect, control);
    }
  }
  // Load the [[NextIndex]] from the {iterator} and leverage the fact
  // that we definitely know that it's in Unsigned32 range since the
  // {iterated_object} is either a JSArray or a JSTypedArray. For the
  // latter case we even know that it's a Smi in UnsignedSmall range.
  FieldAccess index_access = AccessBuilder::ForJSArrayIteratorNextIndex();
  if (IsTypedArrayElementsKind(elements_kind)) {
    index_access.type = TypeCache::Get()->kJSTypedArrayLengthType;
  } else {
    index_access.type = TypeCache::Get()->kJSArrayLengthType;
  }
  Node* index = effect = graph()->NewNode(simplified()->LoadField(index_access),
                                          iterator, effect, control);
  // Load the elements of the {iterated_object}. While it feels
  // counter-intuitive to place the elements pointer load before
  // the condition below, as it might not be needed (if the {index}
  // is out of bounds for the {iterated_object}), it's better this
  // way as it allows the LoadElimination to eliminate redundant
  // reloads of the elements pointer.
  Node* elements = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSObjectElements()),
      iterated_object, effect, control);
  // Load the length of the {iterated_object}. Due to the map checks we
  // already know something about the length here, which we can leverage
  // to generate Word32 operations below without additional checking.
  Node* length;
  if (IsTypedArrayElementsKind(elements_kind)) {
    Node* byte_length = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSTypedArrayByteLength()),
        iterated_object, effect, control);
    Node* byte_length_shifted = graph()->NewNode(
        jsgraph()->machine()->WordShr(), byte_length,
        jsgraph()->UintPtrConstant(ElementsKindToShiftSize(elements_kind)));
    length = graph()->NewNode(
        common()->ExitMachineGraph(MachineType::PointerRepresentation(),
                                   TypeCache::Get()->kJSTypedArrayLengthType),
        byte_length_shifted);
  } else {
    length = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSArrayLength(elements_kind)),
        iterated_object, effect, control);
  }
  // Check whether {index} is within the valid range for the {iterated_object}.
  Node* check = graph()->NewNode(simplified()->NumberLessThan(), index, length);
  Node* branch =
      graph()->NewNode(common()->Branch(BranchHint::kNone), check, control);
  Node* done_true;
  Node* value_true;
  Node* etrue = effect;
  Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
  {
    // This extra check exists to refine the type of {index} but also to break
    // an exploitation technique that abuses typer mismatches.
    if (v8_flags.turbo_typer_hardening) {
      index = etrue = graph()->NewNode(
          simplified()->CheckBounds(
              p.feedback(), CheckBoundsFlag::kAbortOnOutOfBounds |
                                (IsTypedArrayElementsKind(elements_kind)
                                     ? CheckBoundsFlag::kAllow64BitBounds
                                     : CheckBoundsFlag(0))),
          index, length, etrue, if_true);
    }
    done_true = jsgraph()->FalseConstant();
    if (iteration_kind == IterationKind::kKeys) {
      // Just return the {index}.
      value_true = index;
    } else {
      DCHECK(iteration_kind == IterationKind::kEntries ||
             iteration_kind == IterationKind::kValues);
      if (IsTypedArrayElementsKind(elements_kind)) {
        Node* base_ptr = etrue =
            graph()->NewNode(simplified()->LoadField(
                                 AccessBuilder::ForJSTypedArrayBasePointer()),
                             iterated_object, etrue, if_true);
        Node* external_ptr = etrue = graph()->NewNode(
            simplified()->LoadField(
                AccessBuilder::ForJSTypedArrayExternalPointer()),
            iterated_object, etrue, if_true);
        ExternalArrayType array_type = kExternalInt8Array;
        switch (elements_kind) {
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  case TYPE##_ELEMENTS: \
    array_type = kExternal##Type##Array; \
    break;
          TYPED_ARRAYS(TYPED_ARRAY_CASE)
          default:
            UNREACHABLE();
#undef TYPED_ARRAY_CASE
        }
        Node* buffer = etrue =
            graph()->NewNode(simplified()->LoadField(
                                 AccessBuilder::ForJSArrayBufferViewBuffer()),
                             iterated_object, etrue, if_true);
        value_true = etrue =
            graph()->NewNode(simplified()->LoadTypedElement(array_type), buffer,
                             base_ptr, external_ptr, index, etrue, if_true);
      } else {
        value_true = etrue = graph()->NewNode(
            simplified()->LoadElement(
                AccessBuilder::ForFixedArrayElement(elements_kind)),
            elements, index, etrue, if_true);
        // Convert hole to undefined if needed.
        if (IsHoleyElementsKind(elements_kind)) {
          value_true = ConvertHoleToUndefined(value_true, elements_kind);
        }
      }
      if (iteration_kind == IterationKind::kEntries) {
        // Allocate elements for key/value pair
        value_true = etrue =
            graph()->NewNode(javascript()->CreateKeyValueArray(), index,
                             value_true, context, etrue);
      } else {
        DCHECK_EQ(IterationKind::kValues, iteration_kind);
      }
    }
    // Increment the [[NextIndex]] field in the {iterator}. The TypeGuards
    // above guarantee that the {next_index} is in the UnsignedSmall range.
    Node* next_index = graph()->NewNode(simplified()->NumberAdd(), index,
                                        jsgraph()->OneConstant());
    etrue = graph()->NewNode(simplified()->StoreField(index_access), iterator,
                             next_index, etrue, if_true);
  }
  Node* done_false;
  Node* value_false;
  Node* efalse = effect;
  Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
  {
    // iterator.[[NextIndex]] >= array.length, stop iterating.
    done_false = jsgraph()->TrueConstant();
    value_false = jsgraph()->UndefinedConstant();
    if (!IsTypedArrayElementsKind(elements_kind)) {
      // Mark the {iterator} as exhausted by setting the [[NextIndex]] to a
      // value that will never pass the length check again (aka the maximum
      // value possible for the specific iterated object). Note that this is
      // different from what the specification says, which is changing the
      // [[IteratedObject]] field to undefined, but that makes it difficult
      // to eliminate the map checks and "length" accesses in for..of loops.
      //
      // This is not necessary for JSTypedArray's, since the length of those
      // cannot change later and so if we were ever out of bounds for them
      // we will stay out-of-bounds forever.
      Node* end_index = jsgraph()->ConstantNoHole(index_access.type.Max());
      efalse = graph()->NewNode(simplified()->StoreField(index_access),
                                iterator, end_index, efalse, if_false);
    }
  }
  control = graph()->NewNode(common()->Merge(2), if_true, if_false);
  effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
  Node* value =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                       value_true, value_false, control);
  Node* done =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                       done_true, done_false, control);
  // Create IteratorResult object.
  value = effect = graph()->NewNode(javascript()->CreateIterResultObject(),
                                    value, done, context, effect);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References broker(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayIteratingBuiltin(), common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), ConvertHoleToUndefined(), v8::internal::compiler::CreateArrayIteratorParametersOf(), v8::internal::DCHECK(), DCHECK_EQ, dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::ElementsKindToShiftSize(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferBitField(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer(), v8::internal::compiler::AccessBuilder::ForJSArrayIteratorNextIndex(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayBasePointer(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayByteLength(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayExternalPointer(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::index, v8::internal::compiler::MapInference::InsertMapChecks(), v8::internal::IsHoleyElementsKind(), v8::internal::IsTypedArrayElementsKind(), javascript(), jsgraph(), v8::internal::compiler::kAbortOnOutOfBounds, v8::internal::compiler::kAllow64BitBounds, v8::internal::kAllowSpeculation, v8::internal::kEntries, v8::internal::kExternalInt8Array, v8::internal::compiler::CreateArrayIteratorParameters::kind(), v8::internal::compiler::TypeCache::kJSArrayLengthType, v8::internal::compiler::TypeCache::kJSTypedArrayLengthType, v8::internal::kKeys, v8::internal::kNone, v8::internal::kTagged, v8::internal::kValues, v8::internal::length, v8::internal::compiler::Type::Max(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::compiler::FieldAccess::type, TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::value.
Referenced by ReduceJSCall().
ReduceArrayMap()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayMap (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3779 of file js-call-reducer.cc.
                                                                      {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  // Calls CreateArray and thus requires this additional protector dependency.
  if (!dependencies()->DependOnArraySpeciesProtector()) {
    return h.inference()->NoChange();
  }
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph =
      a.ReduceArrayPrototypeMap(h.inference(), h.has_stability_dependency(),
                                h.elements_kind(), shared, native_context());
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), native_context(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayPrototypeAt()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt (Node * node) [private]
Definition at line 6046 of file js-call-reducer.cc.
                                                          {
  if (!v8_flags.turbo_inline_array_builtins) return NoChange();
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Node* receiver = n.receiver();
  Effect effect = n.effect();
  Control control = n.control();
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps()) return NoChange();
  // Collecting maps, and checking if a fallback builtin call will be required
  // (it is required if at least one map doesn't support fast array iteration).
  ZoneVector<MapRef> maps(broker()->zone());
  bool needs_fallback_builtin_call = false;
  for (MapRef map : inference.GetMaps()) {
    if (map.supports_fast_array_iteration(broker())) {
      maps.push_back(map);
    } else {
      needs_fallback_builtin_call = true;
    }
  }
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  if (maps.empty()) {
    // No map in the feedback supports fast iteration. Keeping the builtin call.
    return NoChange();
  }
  if (!dependencies()->DependOnNoElementsProtector()) {
    return NoChange();
  }
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(effect, control);
  TNode<Object> subgraph =
      a.ReduceArrayPrototypeAt(maps, needs_fallback_builtin_call);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), ReplaceWithSubgraph(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::v8_flags.
Referenced by ReduceJSCall().
ReduceArrayPrototypePop()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop (Node * node) [private]
Definition at line 6129 of file js-call-reducer.cc.
                                                           {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* receiver = n.receiver();
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps()) return NoChange();
  ZoneRefSet<Map> const& receiver_maps = inference.GetMaps();
  std::vector<ElementsKind> kinds;
  if (!CanInlineArrayResizingBuiltin(broker(), receiver_maps, &kinds)) {
    return inference.NoChange();
  }
  if (!dependencies()->DependOnNoElementsProtector()) {
    return inference.NoChange();
  }
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  std::vector<Node*> controls_to_merge;
  std::vector<Node*> effects_to_merge;
  std::vector<Node*> values_to_merge;
  Node* value = jsgraph()->UndefinedConstant();
  Node* receiver_elements_kind =
      LoadReceiverElementsKind(receiver, &effect, control);
  Node* next_control = control;
  Node* next_effect = effect;
  for (size_t i = 0; i < kinds.size(); i++) {
    ElementsKind kind = kinds[i];
    control = next_control;
    effect = next_effect;
    // We do not need branch for the last elements kind.
    if (i != kinds.size() - 1) {
      Node* control_node = control;
      CheckIfElementsKind(receiver_elements_kind, kind, control_node,
                          &control_node, &next_control);
      control = control_node;
    }
    // Load the "length" property of the {receiver}.
    Node* length = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSArrayLength(kind)),
        receiver, effect, control);
    // Check if the {receiver} has any elements.
    Node* check = graph()->NewNode(simplified()->NumberEqual(), length,
                                   jsgraph()->ZeroConstant());
    Node* branch =
        graph()->NewNode(common()->Branch(BranchHint::kFalse), check, control);
    Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
    Node* etrue = effect;
    Node* vtrue = jsgraph()->UndefinedConstant();
    Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
    Node* efalse = effect;
    Node* vfalse;
    {
      // TODO(turbofan): We should trim the backing store if the capacity is too
      // big, as implemented in elements.cc:ElementsAccessorBase::SetLengthImpl.
      // Load the elements backing store from the {receiver}.
      Node* elements = efalse = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForJSObjectElements()),
          receiver, efalse, if_false);
      // Ensure that we aren't popping from a copy-on-write backing store.
      if (IsSmiOrObjectElementsKind(kind)) {
        elements = efalse =
            graph()->NewNode(simplified()->EnsureWritableFastElements(),
                             receiver, elements, efalse, if_false);
      }
      // Compute the new {length}.
      Node* new_length = graph()->NewNode(simplified()->NumberSubtract(),
                                          length, jsgraph()->OneConstant());
      if (v8_flags.turbo_typer_hardening) {
        new_length = efalse = graph()->NewNode(
            simplified()->CheckBounds(p.feedback(),
                                      CheckBoundsFlag::kAbortOnOutOfBounds),
            new_length, length, efalse, if_false);
      }
      // Store the new {length} to the {receiver}.
      efalse = graph()->NewNode(
          simplified()->StoreField(AccessBuilder::ForJSArrayLength(kind)),
          receiver, new_length, efalse, if_false);
      // Load the last entry from the {elements}.
      vfalse = efalse = graph()->NewNode(
          simplified()->LoadElement(AccessBuilder::ForFixedArrayElement(kind)),
          elements, new_length, efalse, if_false);
      // Store a hole to the element we just removed from the {receiver}.
      efalse = graph()->NewNode(
          simplified()->StoreElement(
              AccessBuilder::ForFixedArrayElement(GetHoleyElementsKind(kind))),
          elements, new_length, jsgraph()->TheHoleConstant(), efalse, if_false);
    }
    control = graph()->NewNode(common()->Merge(2), if_true, if_false);
    effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
    value = graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                             vtrue, vfalse, control);
    // Convert the hole to undefined. Do this last, so that we can optimize
    // conversion operator via some smart strength reduction in many cases.
    if (IsHoleyElementsKind(kind)) {
      value =
          graph()->NewNode(simplified()->ConvertTaggedHoleToUndefined(), value);
    }
    controls_to_merge.push_back(control);
    effects_to_merge.push_back(effect);
    values_to_merge.push_back(value);
  }
  if (controls_to_merge.size() > 1) {
    int const count = static_cast<int>(controls_to_merge.size());
    control = graph()->NewNode(common()->Merge(count), count,
                               &controls_to_merge.front());
    effects_to_merge.push_back(control);
    effect = graph()->NewNode(common()->EffectPhi(count), count + 1,
                              &effects_to_merge.front());
    values_to_merge.push_back(control);
    value =
        graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, count),
                         count + 1, &values_to_merge.front());
  }
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References broker(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayResizingBuiltin(), CheckIfElementsKind(), common(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::GetHoleyElementsKind(), v8::internal::compiler::MapInference::GetMaps(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsHoleyElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), jsgraph(), v8::internal::compiler::kAbortOnOutOfBounds, v8::internal::kAllowSpeculation, v8::internal::kFalse, v8::internal::kTagged, v8::internal::length, LoadReceiverElementsKind(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::v8_flags, and v8::internal::value.
Referenced by ReduceJSCall().
ReduceArrayPrototypePush()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush (Node * node) [private]
Definition at line 6095 of file js-call-reducer.cc.
                                                            {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Node* receiver = n.receiver();
  Effect effect = n.effect();
  Control control = n.control();
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps()) return NoChange();
  ZoneRefSet<Map> const& receiver_maps = inference.GetMaps();
  std::vector<ElementsKind> kinds;
  if (!CanInlineArrayResizingBuiltin(broker(), receiver_maps, &kinds, true)) {
    return inference.NoChange();
  }
  if (!dependencies()->DependOnNoElementsProtector()) {
    return inference.NoChange();
  }
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(effect, control);
  TNode<Object> subgraph = a.ReduceArrayPrototypePush(&inference);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayResizingBuiltin(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), ReplaceWithSubgraph(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceArrayPrototypeShift()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift (Node * node) [private]
Definition at line 6274 of file js-call-reducer.cc.
                                                             {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Node* target = n.target();
  Node* receiver = n.receiver();
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Effect effect = n.effect();
  Control control = n.control();
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps()) return NoChange();
  ZoneRefSet<Map> const& receiver_maps = inference.GetMaps();
  std::vector<ElementsKind> kinds;
  if (!CanInlineArrayResizingBuiltin(broker(), receiver_maps, &kinds)) {
    return inference.NoChange();
  }
  if (!dependencies()->DependOnNoElementsProtector()) {
    return inference.NoChange();
  }
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  std::vector<Node*> controls_to_merge;
  std::vector<Node*> effects_to_merge;
  std::vector<Node*> values_to_merge;
  Node* value = jsgraph()->UndefinedConstant();
  Node* receiver_elements_kind =
      LoadReceiverElementsKind(receiver, &effect, control);
  Node* next_control = control;
  Node* next_effect = effect;
  for (size_t i = 0; i < kinds.size(); i++) {
    ElementsKind kind = kinds[i];
    control = next_control;
    effect = next_effect;
    // We do not need branch for the last elements kind.
    if (i != kinds.size() - 1) {
      Node* control_node = control;
      CheckIfElementsKind(receiver_elements_kind, kind, control_node,
                          &control_node, &next_control);
      control = control_node;
    }
    // Load length of the {receiver}.
    Node* length = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSArrayLength(kind)),
        receiver, effect, control);
    // Return undefined if {receiver} has no elements.
    Node* check0 = graph()->NewNode(simplified()->NumberEqual(), length,
                                    jsgraph()->ZeroConstant());
    Node* branch0 =
        graph()->NewNode(common()->Branch(BranchHint::kFalse), check0, control);
    Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
    Node* etrue0 = effect;
    Node* vtrue0 = jsgraph()->UndefinedConstant();
    Node* if_false0 = graph()->NewNode(common()->IfFalse(), branch0);
    Node* efalse0 = effect;
    Node* vfalse0;
    {
      // Check if we should take the fast-path.
      Node* check1 = graph()->NewNode(
          simplified()->NumberLessThanOrEqual(), length,
          jsgraph()->ConstantNoHole(JSArray::kMaxCopyElements));
      Node* branch1 = graph()->NewNode(common()->Branch(BranchHint::kTrue),
                                       check1, if_false0);
      Node* if_true1 = graph()->NewNode(common()->IfTrue(), branch1);
      Node* etrue1 = efalse0;
      Node* vtrue1;
      {
        Node* elements = etrue1 = graph()->NewNode(
            simplified()->LoadField(AccessBuilder::ForJSObjectElements()),
            receiver, etrue1, if_true1);
        // Load the first element here, which we return below.
        vtrue1 = etrue1 = graph()->NewNode(
            simplified()->LoadElement(
                AccessBuilder::ForFixedArrayElement(kind)),
            elements, jsgraph()->ZeroConstant(), etrue1, if_true1);
        // Ensure that we aren't shifting a copy-on-write backing store.
        if (IsSmiOrObjectElementsKind(kind)) {
          elements = etrue1 =
              graph()->NewNode(simplified()->EnsureWritableFastElements(),
                               receiver, elements, etrue1, if_true1);
        }
        // Shift the remaining {elements} by one towards the start.
        Node* loop = graph()->NewNode(common()->Loop(2), if_true1, if_true1);
        Node* eloop =
            graph()->NewNode(common()->EffectPhi(2), etrue1, etrue1, loop);
        Node* terminate = graph()->NewNode(common()->Terminate(), eloop, loop);
        MergeControlToEnd(graph(), common(), terminate);
        Node* index = graph()->NewNode(
            common()->Phi(MachineRepresentation::kTagged, 2),
            jsgraph()->OneConstant(),
            jsgraph()->ConstantNoHole(JSArray::kMaxCopyElements - 1), loop);
        {
          Node* check2 =
              graph()->NewNode(simplified()->NumberLessThan(), index, length);
          Node* branch2 = graph()->NewNode(common()->Branch(), check2, loop);
          if_true1 = graph()->NewNode(common()->IfFalse(), branch2);
          etrue1 = eloop;
          Node* control2 = graph()->NewNode(common()->IfTrue(), branch2);
          Node* effect2 = etrue1;
          ElementAccess const access =
              AccessBuilder::ForFixedArrayElement(kind);
          // When disable v8_flags.turbo_loop_variable, typer cannot infer index
          // is in [1, kMaxCopyElements-1], and will break in representing
          // kRepFloat64 (Range(1, inf)) to kRepWord64 when converting
          // input for kLoadElement. So we need to add type guard here.
          // And we need to use index when using NumberLessThan to check
          // terminate and updating index, otherwise which will break inducing
          // variables in LoopVariableOptimizer.
          static_assert(JSArray::kMaxCopyElements < kSmiMaxValue);
          Node* index_retyped = effect2 =
              graph()->NewNode(common()->TypeGuard(Type::UnsignedSmall()),
                               index, effect2, control2);
          Node* value2 = effect2 =
              graph()->NewNode(simplified()->LoadElement(access), elements,
                               index_retyped, effect2, control2);
          effect2 = graph()->NewNode(
              simplified()->StoreElement(access), elements,
              graph()->NewNode(simplified()->NumberSubtract(), index_retyped,
                               jsgraph()->OneConstant()),
              value2, effect2, control2);
          loop->ReplaceInput(1, control2);
          eloop->ReplaceInput(1, effect2);
          index->ReplaceInput(1,
                              graph()->NewNode(simplified()->NumberAdd(), index,
                                               jsgraph()->OneConstant()));
        }
        // Compute the new {length}.
        Node* new_length = graph()->NewNode(simplified()->NumberSubtract(),
                                            length, jsgraph()->OneConstant());
        if (v8_flags.turbo_typer_hardening) {
          new_length = etrue1 = graph()->NewNode(
              simplified()->CheckBounds(p.feedback(),
                                        CheckBoundsFlag::kAbortOnOutOfBounds),
              new_length, length, etrue1, if_true1);
        }
        // Store the new {length} to the {receiver}.
        etrue1 = graph()->NewNode(
            simplified()->StoreField(AccessBuilder::ForJSArrayLength(kind)),
            receiver, new_length, etrue1, if_true1);
        // Store a hole to the element we just removed from the {receiver}.
        etrue1 = graph()->NewNode(
            simplified()->StoreElement(AccessBuilder::ForFixedArrayElement(
                GetHoleyElementsKind(kind))),
            elements, new_length, jsgraph()->TheHoleConstant(), etrue1,
            if_true1);
      }
      Node* if_false1 = graph()->NewNode(common()->IfFalse(), branch1);
      Node* efalse1 = efalse0;
      Node* vfalse1;
      {
        // Call the generic C++ implementation.
        const Builtin builtin = Builtin::kArrayShift;
        auto call_descriptor = Linkage::GetCEntryStubCallDescriptor(
            graph()->zone(), 1, BuiltinArguments::kNumExtraArgsWithReceiver,
            Builtins::name(builtin), node->op()->properties(),
            CallDescriptor::kNeedsFrameState);
        const bool has_builtin_exit_frame = true;
        Node* stub_code = jsgraph()->CEntryStubConstant(1, ArgvMode::kStack,
                                                        has_builtin_exit_frame);
        Address builtin_entry = Builtins::CppEntryOf(builtin);
        Node* entry = jsgraph()->ExternalConstant(
            ExternalReference::Create(builtin_entry));
        Node* argc = jsgraph()->ConstantNoHole(
            BuiltinArguments::kNumExtraArgsWithReceiver);
        static_assert(BuiltinArguments::kNewTargetIndex == 0);
        static_assert(BuiltinArguments::kTargetIndex == 1);
        static_assert(BuiltinArguments::kArgcIndex == 2);
        static_assert(BuiltinArguments::kPaddingIndex == 3);
        if_false1 = efalse1 = vfalse1 =
            graph()->NewNode(common()->Call(call_descriptor), stub_code,
                             receiver, jsgraph()->PaddingConstant(), argc,
                             target, jsgraph()->UndefinedConstant(), entry,
                             argc, context, frame_state, efalse1, if_false1);
      }
      if_false0 = graph()->NewNode(common()->Merge(2), if_true1, if_false1);
      efalse0 =
          graph()->NewNode(common()->EffectPhi(2), etrue1, efalse1, if_false0);
      vfalse0 =
          graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                           vtrue1, vfalse1, if_false0);
    }
    control = graph()->NewNode(common()->Merge(2), if_true0, if_false0);
    effect = graph()->NewNode(common()->EffectPhi(2), etrue0, efalse0, control);
    value = graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                             vtrue0, vfalse0, control);
    // Convert the hole to undefined. Do this last, so that we can optimize
    // conversion operator via some smart strength reduction in many cases.
    if (IsHoleyElementsKind(kind)) {
      value =
          graph()->NewNode(simplified()->ConvertTaggedHoleToUndefined(), value);
    }
    controls_to_merge.push_back(control);
    effects_to_merge.push_back(effect);
    values_to_merge.push_back(value);
  }
  if (controls_to_merge.size() > 1) {
    int const count = static_cast<int>(controls_to_merge.size());
    control = graph()->NewNode(common()->Merge(count), count,
                               &controls_to_merge.front());
    effects_to_merge.push_back(control);
    effect = graph()->NewNode(common()->EffectPhi(count), count + 1,
                              &effects_to_merge.front());
    values_to_merge.push_back(control);
    value =
        graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, count),
                         count + 1, &values_to_merge.front());
  }
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References broker(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayResizingBuiltin(), v8::internal::compiler::JSGraph::CEntryStubConstant(), CheckIfElementsKind(), common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::Builtins::CppEntryOf(), v8::internal::ExternalReference::Create(), dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::MachineGraph::ExternalConstant(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::GetHoleyElementsKind(), v8::internal::compiler::MapInference::GetMaps(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::IsHoleyElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), jsgraph(), v8::internal::compiler::kAbortOnOutOfBounds, v8::internal::kAllowSpeculation, v8::internal::BuiltinArguments::kArgcIndex, v8::internal::kFalse, v8::internal::JSArray::kMaxCopyElements, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::BuiltinArguments::kNewTargetIndex, v8::internal::BuiltinArguments::kNumExtraArgsWithReceiver, v8::internal::BuiltinArguments::kPaddingIndex, v8::internal::kSmiMaxValue, v8::internal::kStack, v8::internal::kTagged, v8::internal::BuiltinArguments::kTargetIndex, v8::internal::kTrue, v8::internal::length, LoadReceiverElementsKind(), v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::Builtins::name(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::Operator::properties(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::Terminate(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::compiler::Type::UnsignedSmall(), v8::internal::v8_flags, and v8::internal::value.
ReduceArrayPrototypeSlice()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice (Node * node) [private]
Definition at line 6521 of file js-call-reducer.cc.
                                                             {
  if (!v8_flags.turbo_inline_array_builtins) return NoChange();
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Node* receiver = n.receiver();
  Node* start = n.ArgumentOr(0, jsgraph()->ZeroConstant());
  Node* end = n.ArgumentOrUndefined(1, jsgraph());
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  // Optimize for the case where we simply clone the {receiver}, i.e. when the
  // {start} is zero and the {end} is undefined (meaning it will be set to
  // {receiver}s "length" property).
  // This logic should be in sync with ArrayPrototypeSlice (to a reasonable
  // degree). This is because CloneFastJSArray produces arrays which are
  // potentially COW. If there's a discrepancy, TF generates code which produces
  // a COW array and then expects it to be non-COW (or the other way around) ->
  // immediate deopt.
  // LINT.IfChange(ArrayPrototypeSlice)
  if (!NumberMatcher(start).Is(0) ||
      !HeapObjectMatcher(end).Is(factory()->undefined_value())) {
    return NoChange();
  }
  // LINT.ThenChange(/src/builtins/array-slice.tq:ArrayPrototypeSlice)
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps()) return NoChange();
  ZoneRefSet<Map> const& receiver_maps = inference.GetMaps();
  // Check that the maps are of JSArray (and more).
  // TODO(turbofan): Consider adding special case for the common pattern
  // `slice.call(arguments)`, for example jQuery makes heavy use of that.
  bool can_be_holey = false;
  for (MapRef receiver_map : receiver_maps) {
    if (!receiver_map.supports_fast_array_iteration(broker())) {
      return inference.NoChange();
    }
    if (IsHoleyElementsKind(receiver_map.elements_kind())) {
      can_be_holey = true;
    }
  }
  if (!dependencies()->DependOnArraySpeciesProtector()) {
    return inference.NoChange();
  }
  if (can_be_holey && !dependencies()->DependOnNoElementsProtector()) {
    return inference.NoChange();
  }
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  // TODO(turbofan): We can do even better here, either adding a CloneArray
  // simplified operator, whose output type indicates that it's an Array,
  // saving subsequent checks, or yet better, by introducing new operators
  // CopySmiOrObjectElements / CopyDoubleElements and inlining the JSArray
  // allocation in here. That way we'd even get escape analysis and scalar
  // replacement to help in some cases.
  Callable callable =
      Builtins::CallableFor(isolate(), Builtin::kCloneFastJSArray);
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      graph()->zone(), callable.descriptor(),
      callable.descriptor().GetStackParameterCount(), CallDescriptor::kNoFlags,
      Operator::kNoThrow | Operator::kNoDeopt);
  // Calls to Builtin::kCloneFastJSArray produce COW arrays
  // if the original array is COW
  Node* clone = effect =
      graph()->NewNode(common()->Call(call_descriptor),
                       jsgraph()->HeapConstantNoHole(callable.code()), receiver,
                       context, effect, control);
  ReplaceWithValue(node, clone, effect, control);
  return Replace(clone);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOr(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::Callable::descriptor(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::end(), factory(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::Is(), v8::internal::IsHoleyElementsKind(), isolate(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::Operator::kNoDeopt, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::v8_flags.
Referenced by ReduceJSCall().
ReduceArrayReduce()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayReduce (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3753 of file js-call-reducer.cc.
                                                                         {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeReduce(
      h.inference(), h.has_stability_dependency(), h.elements_kind(),
      ArrayReduceDirection::kLeft, shared);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kLeft, v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArrayReduceRight()
Reduction v8::internal::compiler::JSCallReducer::ReduceArrayReduceRight (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3766 of file js-call-reducer.cc.
                                                                              {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeReduce(
      h.inference(), h.has_stability_dependency(), h.elements_kind(),
      ArrayReduceDirection::kRight, shared);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kRight, v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceArraySome()
Reduction v8::internal::compiler::JSCallReducer::ReduceArraySome (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 3887 of file js-call-reducer.cc.
                                                                       {
  IteratingArrayBuiltinHelper h(node, broker(), jsgraph(), dependencies());
  if (!h.can_reduce()) return h.inference()->NoChange();
  IteratingArrayBuiltinReducerAssembler a(this, node);
  a.InitializeEffectControl(h.effect(), h.control());
  TNode<Object> subgraph = a.ReduceArrayPrototypeEverySome(
      h.inference(), h.has_stability_dependency(), h.elements_kind(), shared,
      native_context(), ArrayEverySomeVariant::kSome);
  return ReplaceWithSubgraph(&a, subgraph);
}
References broker(), dependencies(), h(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kSome, native_context(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), and ReplaceWithSubgraph().
Referenced by ReduceJSCall().
ReduceBigIntAsN()
Reduction v8::internal::compiler::JSCallReducer::ReduceBigIntAsN (Node * node, Builtin builtin) [private]
Definition at line 9084 of file js-call-reducer.cc.
                                                                    {
  DCHECK(builtin == Builtin::kBigIntAsIntN ||
         builtin == Builtin::kBigIntAsUintN);
  if (!jsgraph()->machine()->Is64()) return NoChange();
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() < 2) {
    return NoChange();
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* bits = n.Argument(0);
  Node* value = n.Argument(1);
  NumberMatcher matcher(bits);
  if (matcher.IsInteger() && matcher.IsInRange(0, 64)) {
    const int bits_value = static_cast<int>(matcher.ResolvedValue());
    value = effect = graph()->NewNode(
        (builtin == Builtin::kBigIntAsIntN
             ? simplified()->SpeculativeBigIntAsIntN(bits_value, p.feedback())
             : simplified()->SpeculativeBigIntAsUintN(bits_value,
                                                      p.feedback())),
        value, effect, control);
    ReplaceWithValue(node, value, effect);
    return Replace(value);
  }
  return NoChange();
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::DCHECK(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), v8::internal::Is64(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInRange(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInteger(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceBigIntConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor (Node * node) [private]
Definition at line 9057 of file js-call-reducer.cc.
                                                           {
  if (!jsgraph()->machine()->Is64()) return NoChange();
  JSCallNode n(node);
  if (n.ArgumentCount() < 1) {
    return NoChange();
  }
  Node* target = n.target();
  Node* receiver = n.receiver();
  Node* value = n.Argument(0);
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  // Create the artificial frame state in the middle of the BigInt constructor.
  SharedFunctionInfoRef shared_info =
      native_context().bigint_function(broker()).shared(broker());
  Node* continuation_frame_state = CreateGenericLazyDeoptContinuationFrameState(
      jsgraph(), shared_info, target, context, receiver, frame_state);
  // Convert the {value} to a BigInt.
  NodeProperties::ReplaceValueInputs(node, value);
  NodeProperties::ChangeOp(node, javascript()->ToBigIntConvertNumber());
  NodeProperties::ReplaceFrameStateInput(node, continuation_frame_state);
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::CreateGenericLazyDeoptContinuationFrameState(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::Is64(), javascript(), jsgraph(), native_context(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::NodeProperties::ReplaceFrameStateInput(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceBooleanConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReduceBooleanConstructor (Node * node) [private]
Definition at line 2829 of file js-call-reducer.cc.
                                                            {
  // Replace the {node} with a proper {ToBoolean} operator.
  JSCallNode n(node);
  Node* value = n.ArgumentOrUndefined(0, jsgraph());
  value = graph()->NewNode(simplified()->ToBoolean(), value);
  ReplaceWithValue(node, value);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceCallApiFunction()
Reduction v8::internal::compiler::JSCallReducer::ReduceCallApiFunction (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 4006 of file js-call-reducer.cc.
                                                                             {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  int const argc = p.arity_without_implicit_args();
  Node* target = n.target();
  Node* global_proxy = jsgraph()->ConstantNoHole(
      native_context().global_proxy_object(broker()), broker());
  Node* receiver = (p.convert_mode() == ConvertReceiverMode::kNullOrUndefined)
                       ? global_proxy
                       : n.receiver();
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  FrameState frame_state = n.frame_state();
  if (!shared.function_template_info(broker()).has_value()) {
    TRACE_BROKER_MISSING(
        broker(), "FunctionTemplateInfo for function with SFI " << shared);
    return NoChange();
  }
  // See if we can optimize this API call to {shared}.
  FunctionTemplateInfoRef function_template_info(
      shared.function_template_info(broker()).value());
  if (function_template_info.accept_any_receiver() &&
      function_template_info.is_signature_undefined(broker())) {
    // We might be able to
    // optimize the API call depending on the {function_template_info}.
    // If the API function accepts any kind of {receiver}, we only need to
    // ensure that the {receiver} is actually a JSReceiver at this point,
    // and also pass that as the {holder}. There are two independent bits
    // here:
    //
    // a. When the "accept any receiver" bit is set, it means we don't
    // need to perform access checks, even if the {receiver}'s map
    // has the "needs access check" bit set.
    // b. When the {function_template_info} has no signature, we don't
    // need to do the compatible receiver check, since all receivers
    // are considered compatible at that point, and the {receiver}
    // will be pass as the {holder}.
    //
    receiver = effect = graph()->NewNode(
        simplified()->ConvertReceiver(p.convert_mode()), receiver,
        jsgraph()->ConstantNoHole(native_context(), broker()), global_proxy,
        effect, control);
  } else {
    // Try to infer the {receiver} maps from the graph.
    MapInference inference(broker(), receiver, effect);
    if (inference.HaveMaps()) {
      ZoneRefSet<Map> const& receiver_maps = inference.GetMaps();
      MapRef first_receiver_map = receiver_maps[0];
      // See if we can constant-fold the compatible receiver checks.
      HolderLookupResult api_holder =
          function_template_info.LookupHolderOfExpectedType(broker(),
                                                            first_receiver_map);
      if (api_holder.lookup == CallOptimization::kHolderNotFound) {
        return inference.NoChange();
      }
      // Check that all {receiver_maps} are actually JSReceiver maps and
      // that the {function_template_info} accepts them without access
      // checks (even if "access check needed" is set for {receiver}).
      //
      // Note that we don't need to know the concrete {receiver} maps here,
      // meaning it's fine if the {receiver_maps} are unreliable, and we also
      // don't need to install any stability dependencies, since the only
      // relevant information regarding the {receiver} is the Map::constructor
      // field on the root map (which is different from the JavaScript exposed
      // "constructor" property) and that field cannot change.
      //
      // So if we know that {receiver} had a certain constructor at some point
      // in the past (i.e. it had a certain map), then this constructor is going
      // to be the same later, since this information cannot change with map
      // transitions.
      //
      // The same is true for the instance type, e.g. we still know that the
      // instance type is JSObject even if that information is unreliable, and
      // the "access check needed" bit, which also cannot change later.
      CHECK(first_receiver_map.IsJSReceiverMap());
      CHECK(!first_receiver_map.is_access_check_needed() ||
            function_template_info.accept_any_receiver());
      for (size_t i = 1; i < receiver_maps.size(); ++i) {
        MapRef receiver_map = receiver_maps[i];
        HolderLookupResult holder_i =
            function_template_info.LookupHolderOfExpectedType(broker(),
                                                              receiver_map);
        if (api_holder.lookup != holder_i.lookup) return inference.NoChange();
        DCHECK(holder_i.lookup == CallOptimization::kHolderFound ||
               holder_i.lookup == CallOptimization::kHolderIsReceiver);
        if (holder_i.lookup == CallOptimization::kHolderFound) {
          DCHECK(api_holder.holder.has_value() && holder_i.holder.has_value());
          if (!api_holder.holder->equals(*holder_i.holder)) {
            return inference.NoChange();
          }
        }
        CHECK(receiver_map.IsJSReceiverMap());
        CHECK(!receiver_map.is_access_check_needed() ||
              function_template_info.accept_any_receiver());
      }
      if (p.speculation_mode() != SpeculationMode::kAllowSpeculation &&
          !inference.RelyOnMapsViaStability(dependencies())) {
        // We were not able to make the receiver maps reliable without map
        // checks but doing map checks would lead to deopt loops, so give up.
        return inference.NoChange();
      }
      // TODO(neis): The maps were used in a way that does not actually require
      // map checks or stability dependencies.
      inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                          control, p.feedback());
    } else {
      // We don't have enough information to eliminate the access check
      // and/or the compatible receiver check, so use the generic builtin
      // that does those checks dynamically. This is still significantly
      // faster than the generic call sequence.
      Builtin builtin_name;
      if (function_template_info.accept_any_receiver()) {
        DCHECK(!function_template_info.is_signature_undefined(broker()));
        builtin_name = Builtin::kCallFunctionTemplate_CheckCompatibleReceiver;
      } else if (function_template_info.is_signature_undefined(broker())) {
        builtin_name = Builtin::kCallFunctionTemplate_CheckAccess;
      } else {
        builtin_name =
            Builtin::kCallFunctionTemplate_CheckAccessAndCompatibleReceiver;
      }
      // The CallFunctionTemplate builtin requires the {receiver} to be
      // an actual JSReceiver, so make sure we do the proper conversion
      // first if necessary.
      receiver = effect = graph()->NewNode(
          simplified()->ConvertReceiver(p.convert_mode()), receiver,
          jsgraph()->ConstantNoHole(native_context(), broker()), global_proxy,
          effect, control);
      Callable callable = Builtins::CallableFor(isolate(), builtin_name);
      auto call_descriptor = Linkage::GetStubCallDescriptor(
          graph()->zone(), callable.descriptor(),
          argc + 1 /* implicit receiver */, CallDescriptor::kNeedsFrameState);
      node->RemoveInput(n.FeedbackVectorIndex());
      node->InsertInput(graph()->zone(), 0,
                        jsgraph()->HeapConstantNoHole(callable.code()));
      node->ReplaceInput(
          1, jsgraph()->ConstantNoHole(function_template_info, broker()));
      node->InsertInput(graph()->zone(), 2,
                        jsgraph()->Int32Constant(JSParameterCount(argc)));
      node->ReplaceInput(3, receiver); // Update receiver input.
      node->ReplaceInput(6 + argc, effect); // Update effect input.
      NodeProperties::ChangeOp(node, common()->Call(call_descriptor));
      return Changed(node);
    }
  }
  // TODO(turbofan): Consider introducing a JSCallApiCallback operator for
  // this and lower it during JSGenericLowering, and unify this with the
  // JSNativeContextSpecialization::InlineApiCall method a bit.
  compiler::OptionalObjectRef maybe_callback_data =
      function_template_info.callback_data(broker());
  // Check if the function has an associated C++ code to execute.
  if (!maybe_callback_data.has_value()) {
    // TODO(ishell): consider generating "return undefined" for empty function
    // instead of failing.
    TRACE_BROKER_MISSING(broker(), "call code for function template info "
                                       << function_template_info);
    return NoChange();
  }
  // Handles overloaded functions.
  FastApiCallFunction c_function = fast_api_call::GetFastApiCallTarget(
      broker(), function_template_info, argc);
  if (c_function.address) {
    FastApiCallReducerAssembler a(this, node, function_template_info,
                                  c_function, receiver, shared, target, argc,
                                  effect);
    Node* fast_call_subgraph = a.ReduceFastApiCall();
    return Replace(fast_call_subgraph);
  }
  // Slow call
  bool no_profiling = broker()->dependencies()->DependOnNoProfilingProtector();
  Callable call_api_callback = Builtins::CallableFor(
      isolate(), no_profiling ? Builtin::kCallApiCallbackOptimizedNoProfiling
                              : Builtin::kCallApiCallbackOptimized);
  CallInterfaceDescriptor cid = call_api_callback.descriptor();
  auto call_descriptor =
      Linkage::GetStubCallDescriptor(graph()->zone(), cid, argc + 1 /*
     implicit receiver */, CallDescriptor::kNeedsFrameState);
  ApiFunction api_function(function_template_info.callback(broker()));
  ExternalReference function_reference = ExternalReference::Create(
      &api_function, ExternalReference::DIRECT_API_CALL);
  Node* continuation_frame_state = CreateInlinedApiFunctionFrameState(
      jsgraph(), shared, target, context, receiver, frame_state);
  node->RemoveInput(n.FeedbackVectorIndex());
  node->InsertInput(graph()->zone(), 0,
                    jsgraph()->HeapConstantNoHole(call_api_callback.code()));
  node->ReplaceInput(1, jsgraph()->ExternalConstant(function_reference));
  node->InsertInput(graph()->zone(), 2, jsgraph()->ConstantNoHole(argc));
  node->InsertInput(
      graph()->zone(), 3,
      jsgraph()->HeapConstantNoHole(function_template_info.object()));
  node->ReplaceInput(4, receiver); // Update receiver input.
  // 6 + argc is context input.
  node->ReplaceInput(5 + argc + 1, continuation_frame_state);
  node->ReplaceInput(5 + argc + 2, effect);
  NodeProperties::ChangeOp(node, common()->Call(call_descriptor));
  return Changed(node);
}
References v8::internal::compiler::FunctionTemplateInfoRef::accept_any_receiver(), v8::internal::compiler::FastApiCallFunction::address, v8::internal::compiler::CallParameters::arity_without_implicit_args(), broker(), v8::internal::Builtins::CallableFor(), v8::internal::compiler::FunctionTemplateInfoRef::callback(), v8::internal::compiler::FunctionTemplateInfoRef::callback_data(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), CHECK, v8::internal::Callable::code(), common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::CallParameters::convert_mode(), v8::internal::ExternalReference::Create(), v8::internal::compiler::CreateInlinedApiFunctionFrameState(), v8::internal::DCHECK(), dependencies(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnNoProfilingProtector(), v8::internal::Callable::descriptor(), v8::internal::ExternalReference::DIRECT_API_CALL, v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::JSCallOrConstructNode::FeedbackVectorIndex(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::SharedFunctionInfoRef::function_template_info(), v8::internal::compiler::fast_api_call::GetFastApiCallTarget(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::HolderLookupResult::holder, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::MapRef::is_access_check_needed(), v8::internal::compiler::FunctionTemplateInfoRef::is_signature_undefined(), isolate(), jsgraph(), v8::internal::JSParameterCount(), v8::internal::kAllowSpeculation, v8::internal::CallOptimization::kHolderFound, v8::internal::CallOptimization::kHolderIsReceiver, v8::internal::CallOptimization::kHolderNotFound, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::kNullOrUndefined, v8::internal::compiler::HolderLookupResult::lookup, v8::internal::compiler::FunctionTemplateInfoRef::LookupHolderOfExpectedType(), native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::FunctionTemplateInfoRef::object(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::MapInference::RelyOnMapsViaStability(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::Node::ReplaceInput(), simplified(), v8::internal::ZoneCompactSet< T >::size(), v8::internal::compiler::CallParameters::speculation_mode(), TRACE_BROKER_MISSING, and v8::internal::value.
Referenced by ReduceJSCall().
ReduceCallOrConstructWithArrayLikeOrSpread()
Reduction v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread (Node * node, int argument_count, int arraylike_or_spread_index, CallFrequency const & frequency, FeedbackSource const & feedback_source, SpeculationMode speculation_mode, CallFeedbackRelation feedback_relation, Node * target, Effect effect, Control control) [private]
Definition at line 4542 of file js-call-reducer.cc.
                                                  {
  DCHECK(IsCallOrConstructWithArrayLike(node) ||
         IsCallOrConstructWithSpread(node));
  DCHECK_IMPLIES(speculation_mode == SpeculationMode::kAllowSpeculation,
                 feedback_source.IsValid());
  // Let's not add instructions to the graph (like e.g., CheckIfConstructor
  // does) if the resulting call might be dead.
  if (feedback_source.IsValid()) {
    ProcessedFeedback const& call_feedback =
        broker()->GetFeedbackForCall(feedback_source);
    if (call_feedback.IsInsufficient()) {
      return ReduceForInsufficientFeedback(
          node, DeoptimizeReason::kInsufficientTypeFeedbackForCall);
    }
  }
  Node* arguments_list =
      NodeProperties::GetValueInput(node, arraylike_or_spread_index);
  if (arguments_list->opcode() == IrOpcode::kJSCreateArguments) {
    return ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(
        node, arguments_list, arraylike_or_spread_index, frequency,
        feedback_source, speculation_mode, feedback_relation);
  }
  if (!v8_flags.turbo_optimize_apply) return NoChange();
  // Optimization of construct nodes not supported yet.
  if (!IsCallWithArrayLikeOrSpread(node)) return NoChange();
  // Avoid deoptimization loops.
  if (speculation_mode != SpeculationMode::kAllowSpeculation) return NoChange();
  // Only optimize with array literals.
  if (arguments_list->opcode() != IrOpcode::kJSCreateLiteralArray &&
      arguments_list->opcode() != IrOpcode::kJSCreateEmptyLiteralArray) {
    return NoChange();
  }
  // For call/construct with spread, we need to also install a code
  // dependency on the array iterator lookup protector cell to ensure
  // that no one messed with the %ArrayIteratorPrototype%.next method.
  if (IsCallOrConstructWithSpread(node)) {
    if (!dependencies()->DependOnArrayIteratorProtector()) return NoChange();
  }
  if (arguments_list->opcode() == IrOpcode::kJSCreateEmptyLiteralArray) {
    if (generated_calls_with_array_like_or_spread_.count(node)) {
      return NoChange(); // Avoid infinite recursion.
    }
    JSCallReducerAssembler a(this, node);
    Node* subgraph = a.ReduceJSCallWithArrayLikeOrSpreadOfEmpty(
        &generated_calls_with_array_like_or_spread_);
    return ReplaceWithSubgraph(&a, subgraph);
  }
  DCHECK_EQ(arguments_list->opcode(), IrOpcode::kJSCreateLiteralArray);
  // Find array length and elements' kind from the feedback's allocation
  // site's boilerplate JSArray.
  JSCreateLiteralOpNode args_node(arguments_list);
  CreateLiteralParameters const& args_params = args_node.Parameters();
  const FeedbackSource& array_feedback = args_params.feedback();
  const ProcessedFeedback& feedback =
      broker()->GetFeedbackForArrayOrObjectLiteral(array_feedback);
  if (feedback.IsInsufficient()) return NoChange();
  AllocationSiteRef site = feedback.AsLiteral().value();
  if (!site.boilerplate(broker()).has_value()) return NoChange();
  JSArrayRef boilerplate_array = site.boilerplate(broker())->AsJSArray();
  int const array_length =
      boilerplate_array.GetBoilerplateLength(broker()).AsSmi();
  SBXCHECK_GE(array_length, 0);
  // We'll replace the arguments_list input with {array_length} element loads.
  uint32_t new_argument_count =
      static_cast<uint32_t>(array_length) + argument_count - 1;
  // Do not optimize calls with a large number of arguments.
  // Arbitrarily sets the limit to 32 arguments.
  const uint32_t kMaxArityForOptimizedFunctionApply = 32;
  if (new_argument_count > kMaxArityForOptimizedFunctionApply) {
    return NoChange();
  }
  // Determine the array's map.
  MapRef array_map = boilerplate_array.map(broker());
  if (!array_map.supports_fast_array_iteration(broker())) {
    return NoChange();
  }
  // Check and depend on NoElementsProtector.
  if (!dependencies()->DependOnNoElementsProtector()) {
    return NoChange();
  }
  // Remove the {arguments_list} node which will be replaced by a sequence of
  // LoadElement nodes.
  node->RemoveInput(arraylike_or_spread_index);
  // Speculate on that array's map is still equal to the dynamic map of
  // arguments_list; generate a map check.
  effect = graph()->NewNode(
      simplified()->CheckMaps(CheckMapsFlag::kNone, ZoneRefSet<Map>(array_map),
                              feedback_source),
      arguments_list, effect, control);
  // Speculate on that array's length being equal to the dynamic length of
  // arguments_list; generate a deopt check.
  ElementsKind elements_kind = array_map.elements_kind();
  effect = CheckArrayLength(arguments_list, elements_kind, array_length,
                            feedback_source, effect, control);
  // Generate N element loads to replace the {arguments_list} node with a set
  // of arguments loaded from it.
  Node* elements = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSObjectElements()),
      arguments_list, effect, control);
  for (int i = 0; i < array_length; i++) {
    // Load the i-th element from the array.
    Node* index = jsgraph()->ConstantNoHole(i);
    Node* load = effect = graph()->NewNode(
        simplified()->LoadElement(
            AccessBuilder::ForFixedArrayElement(elements_kind)),
        elements, index, effect, control);
    // In "holey" arrays some arguments might be missing and we pass
    // 'undefined' instead.
    if (IsHoleyElementsKind(elements_kind)) {
      load = ConvertHoleToUndefined(load, elements_kind);
    }
    node->InsertInput(graph()->zone(), arraylike_or_spread_index + i, load);
  }
  NodeProperties::ChangeOp(
      node, javascript()->Call(
                JSCallNode::ArityForArgc(static_cast<int>(new_argument_count)),
                frequency, feedback_source, ConvertReceiverMode::kAny,
                speculation_mode, CallFeedbackRelation::kUnrelated));
  NodeProperties::ReplaceEffectInput(node, effect);
  return Changed(node).FollowedBy(ReduceJSCall(node));
}
References v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::ProcessedFeedback::AsLiteral(), v8::internal::compiler::AllocationSiteRef::boilerplate(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), CheckArrayLength(), v8::internal::compiler::JSGraph::ConstantNoHole(), ConvertHoleToUndefined(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, dependencies(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::compiler::CreateLiteralParameters::feedback(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), generated_calls_with_array_like_or_spread_, v8::internal::compiler::JSArrayRef::GetBoilerplateLength(), v8::internal::compiler::JSHeapBroker::GetFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::JSHeapBroker::GetFeedbackForCall(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::index, v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsCallOrConstructWithSpread(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsCallWithArrayLikeOrSpread(), v8::internal::IsHoleyElementsKind(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::FeedbackSource::IsValid(), javascript(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::kAny, v8::internal::compiler::kNone, v8::internal::compiler::kUnrelated, v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSCreateLiteralOpNode::Parameters(), ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), ReduceForInsufficientFeedback(), ReduceJSCall(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), ReplaceWithSubgraph(), SBXCHECK_GE, simplified(), v8::internal::compiler::MapRef::supports_fast_array_iteration(), v8::internal::v8_flags, and v8::internal::compiler::SingleValueFeedback< T, K >::value().
Referenced by ReduceJSCallWithArrayLike(), ReduceJSCallWithSpread(), ReduceJSConstructWithArrayLike(), and ReduceJSConstructWithSpread().
ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments()
Reduction v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments (Node * node, Node * arguments_list, int arraylike_or_spread_index, CallFrequency const & frequency, FeedbackSource const & feedback, SpeculationMode speculation_mode, CallFeedbackRelation feedback_relation) [private]
Definition at line 4366 of file js-call-reducer.cc.
                                                                              {
  DCHECK_EQ(arguments_list->opcode(), IrOpcode::kJSCreateArguments);
  // Check if {node} is the only value user of {arguments_list} (except for
  // value uses in frame states). If not, we give up for now.
  for (Edge edge : arguments_list->use_edges()) {
    if (!NodeProperties::IsValueEdge(edge)) continue;
    Node* const user = edge.from();
    switch (user->opcode()) {
      case IrOpcode::kCheckMaps:
      case IrOpcode::kFrameState:
      case IrOpcode::kStateValues:
      case IrOpcode::kReferenceEqual:
      case IrOpcode::kReturn:
        // Ignore safe uses that definitely don't mess with the arguments.
        continue;
      case IrOpcode::kLoadField: {
        DCHECK_EQ(arguments_list, user->InputAt(0));
        FieldAccess const& access = FieldAccessOf(user->op());
        if (access.offset == JSArray::kLengthOffset) {
          // Ignore uses for arguments#length.
          static_assert(
              static_cast<int>(JSArray::kLengthOffset) ==
              static_cast<int>(JSStrictArgumentsObject::kLengthOffset));
          static_assert(
              static_cast<int>(JSArray::kLengthOffset) ==
              static_cast<int>(JSSloppyArgumentsObject::kLengthOffset));
          continue;
        } else if (access.offset == JSObject::kElementsOffset) {
          // Ignore safe uses for arguments#elements.
          if (IsSafeArgumentsElements(user)) continue;
        }
        break;
      }
      case IrOpcode::kJSCallWithArrayLike: {
        // Ignore uses as argumentsList input to calls with array like.
        JSCallWithArrayLikeNode n(user);
        if (edge.index() == n.ArgumentIndex(0)) continue;
        break;
      }
      case IrOpcode::kJSConstructWithArrayLike: {
        // Ignore uses as argumentsList input to calls with array like.
        JSConstructWithArrayLikeNode n(user);
        if (edge.index() == n.ArgumentIndex(0)) continue;
        break;
      }
      case IrOpcode::kJSCallWithSpread: {
        // Ignore uses as spread input to calls with spread.
        JSCallWithSpreadNode n(user);
        if (edge.index() == n.LastArgumentIndex()) continue;
        break;
      }
      case IrOpcode::kJSConstructWithSpread: {
        // Ignore uses as spread input to construct with spread.
        JSConstructWithSpreadNode n(user);
        if (edge.index() == n.LastArgumentIndex()) continue;
        break;
      }
      default:
        break;
    }
    // We cannot currently reduce the {node} to something better than what
    // it already is, but we might be able to do something about the {node}
    // later, so put it on the waitlist and try again during finalization.
    waitlist_.insert(node);
    return NoChange();
  }
  // Get to the actual frame state from which to extract the arguments;
  // we can only optimize this in case the {node} was already inlined into
  // some other function (and same for the {arguments_list}).
  CreateArgumentsType const type = CreateArgumentsTypeOf(arguments_list->op());
  FrameState frame_state =
      FrameState{NodeProperties::GetFrameStateInput(arguments_list)};
  int formal_parameter_count;
  {
    Handle<SharedFunctionInfo> shared;
    if (!frame_state.frame_state_info().shared_info().ToHandle(&shared)) {
      return NoChange();
    }
    formal_parameter_count =
        MakeRef(broker(), shared)
            .internal_formal_parameter_count_without_receiver_deprecated();
  }
  if (type == CreateArgumentsType::kMappedArguments) {
    // Mapped arguments (sloppy mode) that are aliased can only be handled
    // here if there's no side-effect between the {node} and the {arg_array}.
    // TODO(turbofan): Further relax this constraint.
    if (formal_parameter_count != 0) {
      Node* effect = NodeProperties::GetEffectInput(node);
      if (!NodeProperties::NoObservableSideEffectBetween(effect,
                                                         arguments_list)) {
        return NoChange();
      }
    }
  }
  // For call/construct with spread, we need to also install a code
  // dependency on the array iterator lookup protector cell to ensure
  // that no one messed with the %ArrayIteratorPrototype%.next method.
  if (IsCallOrConstructWithSpread(node)) {
    if (!dependencies()->DependOnArrayIteratorProtector()) return NoChange();
  }
  // Remove the {arguments_list} input from the {node}.
  node->RemoveInput(arraylike_or_spread_index);
  // The index of the first relevant parameter. Only non-zero when looking at
  // rest parameters, in which case it is set to the index of the first rest
  // parameter.
  const int start_index = (type == CreateArgumentsType::kRestParameter)
                              ? formal_parameter_count
                              : 0;
  // After removing the arraylike or spread object, the argument count is:
  int argc =
      arraylike_or_spread_index - JSCallOrConstructNode::FirstArgumentIndex();
  // Check if are spreading to inlined arguments or to the arguments of
  // the outermost function.
  if (frame_state.outer_frame_state()->opcode() != IrOpcode::kFrameState) {
    Operator const* op;
    if (IsCallWithArrayLikeOrSpread(node)) {
      static constexpr int kTargetAndReceiver = 2;
      op = javascript()->CallForwardVarargs(argc + kTargetAndReceiver,
                                            start_index);
    } else {
      static constexpr int kTargetAndNewTarget = 2;
      op = javascript()->ConstructForwardVarargs(argc + kTargetAndNewTarget,
                                                 start_index);
    }
    node->RemoveInput(JSCallOrConstructNode::FeedbackVectorIndexForArgc(argc));
    NodeProperties::ChangeOp(node, op);
    return Changed(node);
  }
  // Get to the actual frame state from which to extract the arguments;
  // we can only optimize this in case the {node} was already inlined into
  // some other function (and same for the {arg_array}).
  FrameState outer_state{frame_state.outer_frame_state()};
  FrameStateInfo outer_info = outer_state.frame_state_info();
  if (outer_info.type() == FrameStateType::kInlinedExtraArguments) {
    // Need to take the parameters from the inlined extra arguments frame state.
    frame_state = outer_state;
  }
  // Add the actual parameters to the {node}, skipping the receiver.
  StateValuesAccess parameters_access(frame_state.parameters());
  for (auto it = parameters_access.begin_without_receiver_and_skip(start_index);
       !it.done(); ++it) {
    DCHECK_NOT_NULL(it.node());
    node->InsertInput(graph()->zone(),
                      JSCallOrConstructNode::ArgumentIndex(argc++), it.node());
  }
  if (IsCallWithArrayLikeOrSpread(node)) {
    NodeProperties::ChangeOp(
        node, javascript()->Call(JSCallNode::ArityForArgc(argc), frequency,
                                 feedback, ConvertReceiverMode::kAny,
                                 speculation_mode, feedback_relation));
    return Changed(node).FollowedBy(ReduceJSCall(node));
  } else {
    NodeProperties::ChangeOp(
        node, javascript()->Construct(JSConstructNode::ArityForArgc(argc),
                                      frequency, feedback));
    // Check whether the given new target value is a constructor function. The
    // replacement {JSConstruct} operator only checks the passed target value
    // but relies on the new target value to be implicitly valid.
    CheckIfConstructor(node);
    return Changed(node).FollowedBy(ReduceJSConstruct(node));
  }
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentIndex(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::StateValuesAccess::begin_without_receiver_and_skip(), broker(), v8::internal::compiler::JSOperatorBuilder::CallForwardVarargs(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), CheckIfConstructor(), v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::internal::compiler::JSOperatorBuilder::ConstructForwardVarargs(), v8::internal::compiler::CreateArgumentsTypeOf(), DCHECK_EQ, DCHECK_NOT_NULL, dependencies(), v8::internal::compiler::StateValuesAccess::iterator::done(), v8::internal::compiler::JSCallOrConstructNode::FeedbackVectorIndexForArgc(), v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::JSCallOrConstructNode::FirstArgumentIndex(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::FrameState::frame_state_info(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsCallOrConstructWithSpread(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsCallWithArrayLikeOrSpread(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsSafeArgumentsElements(), v8::internal::compiler::NodeProperties::IsValueEdge(), javascript(), v8::internal::kAny, v8::internal::compiler::kInlinedExtraArguments, v8::internal::kMappedArguments, v8::internal::kRestParameter, v8::internal::compiler::JSCallOrConstructNode::LastArgumentIndex(), v8::internal::compiler::MakeRef(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::NodeProperties::NoObservableSideEffectBetween(), v8::internal::compiler::FieldAccess::offset, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::FrameState::outer_frame_state(), v8::internal::compiler::FrameState::parameters(), ReduceJSCall(), ReduceJSConstruct(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::FrameStateInfo::shared_info(), v8::internal::compiler::FrameStateInfo::type(), v8::internal::tracing::type, v8::internal::compiler::Node::use_edges(), and waitlist_.
Referenced by ReduceCallOrConstructWithArrayLikeOrSpread().
ReduceCallWasmFunction()
Reduction v8::internal::compiler::JSCallReducer::ReduceCallWasmFunction (Node * node, SharedFunctionInfoRef shared) [private]
Referenced by ReduceJSCall().
ReduceCollectionIteration()
Reduction v8::internal::compiler::JSCallReducer::ReduceCollectionIteration (Node * node, CollectionKind collection_kind, IterationKind iteration_kind) [private]
Definition at line 8196 of file js-call-reducer.cc.
                                                                              {
  DCHECK_EQ(IrOpcode::kJSCall, node->opcode());
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Node* context = NodeProperties::GetContextInput(node);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  InstanceType type = InstanceTypeForCollectionKind(collection_kind);
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() || !inference.AllOfInstanceTypesAre(type)) {
    return NoChange();
  }
  Node* js_create_iterator = effect = graph()->NewNode(
      javascript()->CreateCollectionIterator(collection_kind, iteration_kind),
      receiver, context, effect, control);
  ReplaceWithValue(node, js_create_iterator, effect);
  return Replace(js_create_iterator);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), broker(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::InstanceTypeForCollectionKind(), javascript(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), and v8::internal::tracing::type.
Referenced by ReduceJSCall().
ReduceCollectionIteratorPrototypeNext()
Reduction v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext (Node * node, int entry_size, Handle< HeapObject > empty_collection, InstanceType collection_iterator_instance_type_first, InstanceType collection_iterator_instance_type_last) [private]
Definition at line 8241 of file js-call-reducer.cc.
                                                         {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Node* receiver = n.receiver();
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  // A word of warning to begin with: This whole method might look a bit
  // strange at times, but that's mostly because it was carefully handcrafted
  // to allow for full escape analysis and scalar replacement of both the
  // collection iterator object and the iterator results, including the
  // key-value arrays in case of Set/Map entry iteration.
  //
  // TODO(turbofan): Currently the escape analysis (and the store-load
  // forwarding) is unable to eliminate the allocations for the key-value
  // arrays in case of Set/Map entry iteration, and we should investigate
  // how to update the escape analysis / arrange the graph in a way that
  // this becomes possible.
  InstanceType receiver_instance_type;
  {
    MapInference inference(broker(), receiver, effect);
    if (!inference.HaveMaps()) return NoChange();
    ZoneRefSet<Map> const& receiver_maps = inference.GetMaps();
    receiver_instance_type = receiver_maps[0].instance_type();
    for (size_t i = 1; i < receiver_maps.size(); ++i) {
      if (receiver_maps[i].instance_type() != receiver_instance_type) {
        return inference.NoChange();
      }
    }
    if (receiver_instance_type < collection_iterator_instance_type_first ||
        receiver_instance_type > collection_iterator_instance_type_last) {
      return inference.NoChange();
    }
    inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                        control, p.feedback());
  }
  // Transition the JSCollectionIterator {receiver} if necessary
  // (i.e. there were certain mutations while we're iterating).
  {
    Node* done_loop;
    Node* done_eloop;
    Node* loop = control =
        graph()->NewNode(common()->Loop(2), control, control);
    Node* eloop = effect =
        graph()->NewNode(common()->EffectPhi(2), effect, effect, loop);
    Node* terminate = graph()->NewNode(common()->Terminate(), eloop, loop);
    MergeControlToEnd(graph(), common(), terminate);
    // Check if reached the final table of the {receiver}.
    Node* table = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSCollectionIteratorTable()),
        receiver, effect, control);
    Node* next_table = effect =
        graph()->NewNode(simplified()->LoadField(
                             AccessBuilder::ForOrderedHashMapOrSetNextTable()),
                         table, effect, control);
    Node* check = graph()->NewNode(simplified()->ObjectIsSmi(), next_table);
    control =
        graph()->NewNode(common()->Branch(BranchHint::kTrue), check, control);
    // Abort the {loop} when we reach the final table.
    done_loop = graph()->NewNode(common()->IfTrue(), control);
    done_eloop = effect;
    // Migrate to the {next_table} otherwise.
    control = graph()->NewNode(common()->IfFalse(), control);
    // Self-heal the {receiver}s index.
    Node* index = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSCollectionIteratorIndex()),
        receiver, effect, control);
    Callable const callable =
        Builtins::CallableFor(isolate(), Builtin::kOrderedHashTableHealIndex);
    auto call_descriptor = Linkage::GetStubCallDescriptor(
        graph()->zone(), callable.descriptor(),
        callable.descriptor().GetStackParameterCount(),
        CallDescriptor::kNoFlags, Operator::kEliminatable);
    index = effect =
        graph()->NewNode(common()->Call(call_descriptor),
                         jsgraph()->HeapConstantNoHole(callable.code()), table,
                         index, jsgraph()->NoContextConstant(), effect);
    index = effect = graph()->NewNode(
        common()->TypeGuard(TypeCache::Get()->kFixedArrayLengthType), index,
        effect, control);
    // Update the {index} and {table} on the {receiver}.
    effect = graph()->NewNode(
        simplified()->StoreField(AccessBuilder::ForJSCollectionIteratorIndex()),
        receiver, index, effect, control);
    effect = graph()->NewNode(
        simplified()->StoreField(AccessBuilder::ForJSCollectionIteratorTable()),
        receiver, next_table, effect, control);
    // Tie the knot.
    loop->ReplaceInput(1, control);
    eloop->ReplaceInput(1, effect);
    control = done_loop;
    effect = done_eloop;
  }
  // Get current index and table from the JSCollectionIterator {receiver}.
  Node* index = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSCollectionIteratorIndex()),
      receiver, effect, control);
  Node* table = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSCollectionIteratorTable()),
      receiver, effect, control);
  // Create the {JSIteratorResult} first to ensure that we always have
  // a dominating Allocate node for the allocation folding phase.
  Node* iterator_result = effect = graph()->NewNode(
      javascript()->CreateIterResultObject(), jsgraph()->UndefinedConstant(),
      jsgraph()->TrueConstant(), context, effect);
  // Look for the next non-holey key, starting from {index} in the {table}.
  Node* controls[2];
  Node* effects[3];
  {
    // Compute the currently used capacity.
    Node* number_of_buckets = effect = graph()->NewNode(
        simplified()->LoadField(
            AccessBuilder::ForOrderedHashMapOrSetNumberOfBuckets()),
        table, effect, control);
    Node* number_of_elements = effect = graph()->NewNode(
        simplified()->LoadField(
            AccessBuilder::ForOrderedHashMapOrSetNumberOfElements()),
        table, effect, control);
    Node* number_of_deleted_elements = effect = graph()->NewNode(
        simplified()->LoadField(
            AccessBuilder::ForOrderedHashMapOrSetNumberOfDeletedElements()),
        table, effect, control);
    Node* used_capacity =
        graph()->NewNode(simplified()->NumberAdd(), number_of_elements,
                         number_of_deleted_elements);
    // Skip holes and update the {index}.
    Node* loop = graph()->NewNode(common()->Loop(2), control, control);
    Node* eloop =
        graph()->NewNode(common()->EffectPhi(2), effect, effect, loop);
    Node* terminate = graph()->NewNode(common()->Terminate(), eloop, loop);
    MergeControlToEnd(graph(), common(), terminate);
    Node* iloop = graph()->NewNode(
        common()->Phi(MachineRepresentation::kTagged, 2), index, index, loop);
    index = effect = graph()->NewNode(
        common()->TypeGuard(TypeCache::Get()->kFixedArrayLengthType), iloop,
        eloop, control);
    {
      Node* check0 = graph()->NewNode(simplified()->NumberLessThan(), index,
                                      used_capacity);
      Node* branch0 =
          graph()->NewNode(common()->Branch(BranchHint::kTrue), check0, loop);
      Node* if_false0 = graph()->NewNode(common()->IfFalse(), branch0);
      Node* efalse0 = effect;
      {
        // Mark the {receiver} as exhausted.
        efalse0 = graph()->NewNode(
            simplified()->StoreField(
                AccessBuilder::ForJSCollectionIteratorTable()),
            receiver, jsgraph()->HeapConstantNoHole(empty_collection), efalse0,
            if_false0);
        controls[0] = if_false0;
        effects[0] = efalse0;
      }
      Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
      Node* etrue0 = effect;
      {
        // Load the key of the entry.
        static_assert(OrderedHashMap::HashTableStartIndex() ==
                      OrderedHashSet::HashTableStartIndex());
        Node* entry_start_position = graph()->NewNode(
            simplified()->NumberAdd(),
            graph()->NewNode(
                simplified()->NumberAdd(),
                graph()->NewNode(simplified()->NumberMultiply(), index,
                                 jsgraph()->ConstantNoHole(entry_size)),
                number_of_buckets),
            jsgraph()->ConstantNoHole(OrderedHashMap::HashTableStartIndex()));
        Node* entry_key = etrue0 = graph()->NewNode(
            simplified()->LoadElement(AccessBuilder::ForFixedArrayElement()),
            table, entry_start_position, etrue0, if_true0);
        // Advance the index.
        index = graph()->NewNode(simplified()->NumberAdd(), index,
                                 jsgraph()->OneConstant());
        Node* check1 =
            graph()->NewNode(simplified()->ReferenceEqual(), entry_key,
                             jsgraph()->HashTableHoleConstant());
        Node* branch1 = graph()->NewNode(common()->Branch(BranchHint::kFalse),
                                         check1, if_true0);
        {
          // Abort loop with resulting value.
          control = graph()->NewNode(common()->IfFalse(), branch1);
          effect = etrue0;
          Node* value = effect =
              graph()->NewNode(common()->TypeGuard(Type::NonInternal()),
                               entry_key, effect, control);
          Node* done = jsgraph()->FalseConstant();
          // Advance the index on the {receiver}.
          effect = graph()->NewNode(
              simplified()->StoreField(
                  AccessBuilder::ForJSCollectionIteratorIndex()),
              receiver, index, effect, control);
          // The actual {value} depends on the {receiver} iteration type.
          switch (receiver_instance_type) {
            case JS_MAP_KEY_ITERATOR_TYPE:
            case JS_SET_VALUE_ITERATOR_TYPE:
              break;
            case JS_SET_KEY_VALUE_ITERATOR_TYPE:
              value = effect =
                  graph()->NewNode(javascript()->CreateKeyValueArray(), value,
                                   value, context, effect);
              break;
            case JS_MAP_VALUE_ITERATOR_TYPE:
              value = effect = graph()->NewNode(
                  simplified()->LoadElement(
                      AccessBuilder::ForFixedArrayElement()),
                  table,
                  graph()->NewNode(
                      simplified()->NumberAdd(), entry_start_position,
                      jsgraph()->ConstantNoHole(OrderedHashMap::kValueOffset)),
                  effect, control);
              break;
            case JS_MAP_KEY_VALUE_ITERATOR_TYPE:
              value = effect = graph()->NewNode(
                  simplified()->LoadElement(
                      AccessBuilder::ForFixedArrayElement()),
                  table,
                  graph()->NewNode(
                      simplified()->NumberAdd(), entry_start_position,
                      jsgraph()->ConstantNoHole(OrderedHashMap::kValueOffset)),
                  effect, control);
              value = effect =
                  graph()->NewNode(javascript()->CreateKeyValueArray(),
                                   entry_key, value, context, effect);
              break;
            default:
              UNREACHABLE();
          }
          // Store final {value} and {done} into the {iterator_result}.
          effect =
              graph()->NewNode(simplified()->StoreField(
                                   AccessBuilder::ForJSIteratorResultValue()),
                               iterator_result, value, effect, control);
          effect =
              graph()->NewNode(simplified()->StoreField(
                                   AccessBuilder::ForJSIteratorResultDone()),
                               iterator_result, done, effect, control);
          controls[1] = control;
          effects[1] = effect;
        }
        // Continue with next loop index.
        loop->ReplaceInput(1, graph()->NewNode(common()->IfTrue(), branch1));
        eloop->ReplaceInput(1, etrue0);
        iloop->ReplaceInput(1, index);
      }
    }
    control = effects[2] = graph()->NewNode(common()->Merge(2), 2, controls);
    effect = graph()->NewNode(common()->EffectPhi(2), 3, effects);
  }
  // Yield the final {iterator_result}.
  ReplaceWithValue(node, iterator_result, effect, control);
  return Replace(iterator_result);
}
References broker(), v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::Callable::descriptor(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForJSCollectionIteratorIndex(), v8::internal::compiler::AccessBuilder::ForJSCollectionIteratorTable(), v8::internal::compiler::AccessBuilder::ForJSIteratorResultDone(), v8::internal::compiler::AccessBuilder::ForJSIteratorResultValue(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNextTable(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfBuckets(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfDeletedElements(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfElements(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::HashTableStartIndex(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::HashTableStartIndex(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, isolate(), javascript(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::Operator::kEliminatable, v8::internal::kFalse, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::kTagged, v8::internal::kTrue, v8::internal::OrderedHashMap::kValueOffset, v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::ZoneCompactSet< T >::size(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::Terminate(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceCollectionPrototypeHas()
Reduction v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas (Node * node, CollectionKind collection_kind) [private]
Definition at line 8155 of file js-call-reducer.cc.
                                                {
  // We only optimize if we have target, receiver and key parameters.
  JSCallNode n(node);
  if (n.ArgumentCount() != 1) return NoChange();
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  Node* key = NodeProperties::GetValueInput(node, 2);
  InstanceType instance_type = InstanceTypeForCollectionKind(collection_kind);
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() ||
      !inference.AllOfInstanceTypesAre(instance_type)) {
    return NoChange();
  }
  Node* table = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSCollectionTable()), receiver,
      effect, control);
  Node* index = effect = graph()->NewNode(
      simplified()->FindOrderedCollectionEntry(collection_kind), table, key,
      effect, control);
  Node* value = graph()->NewNode(simplified()->NumberEqual(), index,
                                 jsgraph()->MinusOneConstant());
  value = graph()->NewNode(simplified()->BooleanNot(), value);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), broker(), v8::internal::compiler::AccessBuilder::ForJSCollectionTable(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::index, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::InstanceTypeForCollectionKind(), jsgraph(), v8::internal::key, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceMapPrototypeHas(), and ReduceSetPrototypeHas().
ReduceCollectionPrototypeSize()
Reduction v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize (Node * node, CollectionKind collection_kind) [private]
Definition at line 8217 of file js-call-reducer.cc.
                                                {
  DCHECK_EQ(IrOpcode::kJSCall, node->opcode());
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  InstanceType type = InstanceTypeForCollectionKind(collection_kind);
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() || !inference.AllOfInstanceTypesAre(type)) {
    return NoChange();
  }
  Node* table = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSCollectionTable()), receiver,
      effect, control);
  Node* value = effect = graph()->NewNode(
      simplified()->LoadField(
          AccessBuilder::ForOrderedHashMapOrSetNumberOfElements()),
      table, effect, control);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), broker(), DCHECK_EQ, v8::internal::compiler::AccessBuilder::ForJSCollectionTable(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfElements(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::InstanceTypeForCollectionKind(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::tracing::type, and v8::internal::value.
Referenced by ReduceJSCall().
ReduceDataViewAccess()
Reduction v8::internal::compiler::JSCallReducer::ReduceDataViewAccess (Node * node, DataViewAccess access, ExternalArrayType element_type) [private]
Definition at line 8617 of file js-call-reducer.cc.
                                                                              {
  // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  size_t const element_size = ExternalArrayElementSize(element_type);
  Effect effect = n.effect();
  Control control = n.control();
  Node* receiver = n.receiver();
  Node* offset = n.ArgumentOr(0, jsgraph()->ZeroConstant());
  Node* value = nullptr;
  if (!Is64() && (element_type == kExternalBigInt64Array ||
                  element_type == kExternalBigUint64Array)) {
    return NoChange();
  }
  if (access == DataViewAccess::kSet) {
    value = n.ArgumentOrUndefined(1, jsgraph());
  }
  const int endian_index = (access == DataViewAccess::kGet ? 1 : 2);
  Node* is_little_endian =
      n.ArgumentOr(endian_index, jsgraph()->FalseConstant());
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  // Only do stuff if the {receiver} is really a DataView.
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() ||
      !inference.AllOfInstanceTypesAre(JS_DATA_VIEW_TYPE)) {
    return NoChange();
  }
  // Check that the {offset} is within range for the {receiver}.
  HeapObjectMatcher m(receiver);
  if (m.HasResolvedValue() && m.Ref(broker()).IsJSDataView()) {
    // We only deal with DataViews here whose [[ByteLength]] is at least
    // {element_size}, as for all other DataViews it'll be out-of-bounds.
    JSDataViewRef dataview = m.Ref(broker()).AsJSDataView();
    size_t length = dataview.byte_length();
    if (length < element_size) return NoChange();
    // Check that the {offset} is within range of the {length}.
    Node* byte_length = jsgraph()->ConstantNoHole(length - (element_size - 1));
    offset = effect =
        graph()->NewNode(simplified()->CheckBounds(
                             p.feedback(), CheckBoundsFlag::kAllow64BitBounds),
                         offset, byte_length, effect, control);
  } else {
    // We only deal with DataViews here that have Smi [[ByteLength]]s.
    Node* byte_length = effect =
        graph()->NewNode(simplified()->LoadField(
                             AccessBuilder::ForJSArrayBufferViewByteLength()),
                         receiver, effect, control);
    if (element_size > 1) {
      // For non-byte accesses we also need to check that the {offset}
      // plus the {element_size}-1 fits within the given {byte_length}.
      // So to keep this as a single check on the {offset}, we subtract
      // the {element_size}-1 from the {byte_length} here (clamped to
      // positive safe integer range), and perform a check against that
      // with the {offset} below.
      byte_length = graph()->NewNode(
          simplified()->NumberMax(), jsgraph()->ZeroConstant(),
          graph()->NewNode(simplified()->NumberSubtract(), byte_length,
                           jsgraph()->ConstantNoHole(element_size - 1)));
    }
    // Check that the {offset} is within range of the {byte_length}.
    offset = effect =
        graph()->NewNode(simplified()->CheckBounds(
                             p.feedback(), CheckBoundsFlag::kAllow64BitBounds),
                         offset, byte_length, effect, control);
  }
  // Coerce {is_little_endian} to boolean.
  is_little_endian =
      graph()->NewNode(simplified()->ToBoolean(), is_little_endian);
  // Coerce {value} to Number.
  if (access == DataViewAccess::kSet) {
    if (element_type == kExternalBigInt64Array ||
        element_type == kExternalBigUint64Array) {
      value = effect =
          graph()->NewNode(simplified()->SpeculativeToBigInt(
                               BigIntOperationHint::kBigInt, p.feedback()),
                           value, effect, control);
    } else {
      value = effect = graph()->NewNode(
          simplified()->SpeculativeToNumber(
              NumberOperationHint::kNumberOrOddball, p.feedback()),
          value, effect, control);
    }
  }
  // We need to retain either the {receiver} itself or its backing
  // JSArrayBuffer to make sure that the GC doesn't collect the raw
  // memory. We default to {receiver} here, and only use the buffer
  // if we anyways have to load it (to reduce register pressure).
  Node* buffer_or_receiver = receiver;
  if (!dependencies()->DependOnArrayBufferDetachingProtector()) {
    // Get the underlying buffer and check that it has not been detached.
    Node* buffer = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSArrayBufferViewBuffer()),
        receiver, effect, control);
    // Bail out if the {buffer} was detached.
    Node* buffer_bit_field = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSArrayBufferBitField()),
        buffer, effect, control);
    Node* check = graph()->NewNode(
        simplified()->NumberEqual(),
        graph()->NewNode(
            simplified()->NumberBitwiseAnd(), buffer_bit_field,
            jsgraph()->ConstantNoHole(JSArrayBuffer::WasDetachedBit::kMask)),
        jsgraph()->ZeroConstant());
    effect = graph()->NewNode(
        simplified()->CheckIf(DeoptimizeReason::kArrayBufferWasDetached,
                              p.feedback()),
        check, effect, control);
    // We can reduce register pressure by holding on to the {buffer}
    // now to retain the backing store memory.
    buffer_or_receiver = buffer;
  }
  // Load the {receiver}s data pointer.
  Node* data_pointer = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSDataViewDataPointer()),
      receiver, effect, control);
  switch (access) {
    case DataViewAccess::kGet:
      // Perform the load.
      value = effect = graph()->NewNode(
          simplified()->LoadDataViewElement(element_type), buffer_or_receiver,
          data_pointer, offset, is_little_endian, effect, control);
      break;
    case DataViewAccess::kSet:
      // Perform the store.
      effect = graph()->NewNode(
          simplified()->StoreDataViewElement(element_type), buffer_or_receiver,
          data_pointer, offset, value, is_little_endian, effect, control);
      value = jsgraph()->UndefinedConstant();
      break;
  }
  ReplaceWithValue(node, value, effect, control);
  return Changed(value);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOr(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), v8::internal::compiler::JSDataViewRef::byte_length(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::ExternalArrayElementSize(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferBitField(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteLength(), v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer(), graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::Is64(), jsgraph(), v8::internal::compiler::kAllow64BitBounds, v8::internal::kAllowSpeculation, v8::internal::compiler::kBigInt, v8::internal::kExternalBigInt64Array, v8::internal::kExternalBigUint64Array, kGet, v8::internal::compiler::kNumberOrOddball, kSet, v8::internal::length, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceDateNow()
Reduction v8::internal::compiler::JSCallReducer::ReduceDateNow (Node * node) [private]
Definition at line 8881 of file js-call-reducer.cc.
                                                 {
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* value = effect =
      graph()->NewNode(simplified()->DateNow(), effect, control);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceDatePrototypeGetField()
Reduction v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField (Node * node, JSDate::FieldIndex field) [private]
Definition at line 8848 of file js-call-reducer.cc.
                                                                             {
  DCHECK_LT(field, JSDate::kFirstUncachedField);
  if (!v8_flags.turbofan_inline_date_accessors) return NoChange();
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() || !inference.AllOfInstanceTypesAre(JS_DATE_TYPE)) {
    return NoChange();
  }
  if (!dependencies()->DependOnNoDateTimeConfigurationChangeProtector()) {
    return NoChange();
  }
#define __ gasm.
  JSGraphAssembler gasm(broker(), jsgraph(), jsgraph()->zone(),
                        BranchSemantics::kJS);
  gasm.InitializeEffectControl(effect, control);
  Node* value =
      __ LoadField<Object>(AccessBuilder::ForJSDateField(field),
                           TNode<HeapObject>::UncheckedCast(receiver));
  ReplaceWithValue(node, value, gasm.effect(), gasm.control());
  return Replace(value);
#undef __
}
References __, v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), broker(), v8::internal::compiler::GraphAssembler::control(), DCHECK_LT, dependencies(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::AccessBuilder::ForJSDateField(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::JSDate::kFirstUncachedField, v8::internal::compiler::kJS, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::v8_flags, and v8::internal::value.
Referenced by ReduceJSCall().
ReduceDatePrototypeGetTime()
Reduction v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime (Node * node) [private]
Definition at line 8824 of file js-call-reducer.cc.
                                                              {
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() || !inference.AllOfInstanceTypesAre(JS_DATE_TYPE)) {
    return NoChange();
  }
  Node* value = effect =
      graph()->NewNode(simplified()->LoadField(AccessBuilder::ForJSDateValue()),
                       receiver, effect, control);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), broker(), v8::internal::compiler::AccessBuilder::ForJSDateValue(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceFastArrayIteratorNext()
Reduction v8::internal::compiler::JSCallReducer::ReduceFastArrayIteratorNext (InstanceType type, Node * node, IterationKind kind) [private]
ReduceForInsufficientFeedback()
Reduction v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback (Node * node, DeoptimizeReason reason) [private]
Definition at line 5973 of file js-call-reducer.cc.
                                         {
  DCHECK(node->opcode() == IrOpcode::kJSCall ||
         node->opcode() == IrOpcode::kJSCallWithSpread ||
         node->opcode() == IrOpcode::kJSCallWithArrayLike ||
         node->opcode() == IrOpcode::kJSConstruct ||
         node->opcode() == IrOpcode::kJSConstructWithSpread ||
         node->opcode() == IrOpcode::kJSConstructWithArrayLike);
  if (!(flags() & kBailoutOnUninitialized)) return NoChange();
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* frame_state =
      NodeProperties::FindFrameStateBefore(node, jsgraph()->Dead());
  Node* deoptimize =
      graph()->NewNode(common()->Deoptimize(reason, FeedbackSource()),
                       frame_state, effect, control);
  MergeControlToEnd(graph(), common(), deoptimize);
  node->TrimInputCount(0);
  NodeProperties::ChangeOp(node, common()->Dead());
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::FindFrameStateBefore(), flags(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), jsgraph(), kBailoutOnUninitialized, v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceJSCall(), and ReduceJSConstruct().
ReduceFunctionPrototypeApply()
Reduction v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply (Node * node) [private]
Definition at line 2863 of file js-call-reducer.cc.
                                                                {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  CallFeedbackRelation new_feedback_relation =
      p.feedback_relation() == CallFeedbackRelation::kReceiver
          ? CallFeedbackRelation::kTarget
          : CallFeedbackRelation::kUnrelated;
  int arity = p.arity_without_implicit_args();
  if (arity < 2) {
    // Degenerate cases.
    ConvertReceiverMode convert_mode;
    if (arity == 0) {
      // Neither thisArg nor argArray was provided.
      convert_mode = ConvertReceiverMode::kNullOrUndefined;
      node->ReplaceInput(n.TargetIndex(), n.receiver());
      node->ReplaceInput(n.ReceiverIndex(), jsgraph()->UndefinedConstant());
    } else {
      DCHECK_EQ(arity, 1);
      // The argArray was not provided, just remove the {target}.
      convert_mode = ConvertReceiverMode::kAny;
      node->RemoveInput(n.TargetIndex());
      --arity;
    }
    // Change {node} to a {JSCall} and try to reduce further.
    NodeProperties::ChangeOp(
        node, javascript()->Call(JSCallNode::ArityForArgc(arity), p.frequency(),
                                 p.feedback(), convert_mode,
                                 p.speculation_mode(), new_feedback_relation));
    return Changed(node).FollowedBy(ReduceJSCall(node));
  }
  // Turn the JSCall into a JSCallWithArrayLike.
  // If {argArray} can be null or undefined, we have to generate branches since
  // JSCallWithArrayLike would throw for null or undefined.
  Node* target = n.receiver();
  Node* this_argument = n.Argument(0);
  Node* arguments_list = n.Argument(1);
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Effect effect = n.effect();
  Control control = n.control();
  // If {arguments_list} cannot be null or undefined, we don't need
  // to expand this {node} to control-flow.
  if (!NodeProperties::CanBeNullOrUndefined(broker(), arguments_list, effect)) {
    // Massage the value inputs appropriately.
    node->ReplaceInput(n.TargetIndex(), target);
    node->ReplaceInput(n.ReceiverIndex(), this_argument);
    node->ReplaceInput(n.ArgumentIndex(0), arguments_list);
    while (arity-- > 1) node->RemoveInput(n.ArgumentIndex(1));
    // Morph the {node} to a {JSCallWithArrayLike}.
    NodeProperties::ChangeOp(
        node, javascript()->CallWithArrayLike(p.frequency(), p.feedback(),
                                              p.speculation_mode(),
                                              new_feedback_relation));
    return Changed(node).FollowedBy(ReduceJSCallWithArrayLike(node));
  }
  // Check whether {arguments_list} is null.
  Node* check_null =
      graph()->NewNode(simplified()->ReferenceEqual(), arguments_list,
                       jsgraph()->NullConstant());
  control = graph()->NewNode(common()->Branch(BranchHint::kFalse), check_null,
                             control);
  Node* if_null = graph()->NewNode(common()->IfTrue(), control);
  control = graph()->NewNode(common()->IfFalse(), control);
  // Check whether {arguments_list} is undefined.
  Node* check_undefined =
      graph()->NewNode(simplified()->ReferenceEqual(), arguments_list,
                       jsgraph()->UndefinedConstant());
  control = graph()->NewNode(common()->Branch(BranchHint::kFalse),
                             check_undefined, control);
  Node* if_undefined = graph()->NewNode(common()->IfTrue(), control);
  control = graph()->NewNode(common()->IfFalse(), control);
  // Lower to {JSCallWithArrayLike} if {arguments_list} is neither null
  // nor undefined.
  Node* effect0 = effect;
  Node* control0 = control;
  Node* value0 = effect0 = control0 = graph()->NewNode(
      javascript()->CallWithArrayLike(p.frequency(), p.feedback(),
                                      p.speculation_mode(),
                                      new_feedback_relation),
      target, this_argument, arguments_list, n.feedback_vector(), context,
      frame_state, effect0, control0);
  // Lower to {JSCall} if {arguments_list} is either null or undefined.
  Node* effect1 = effect;
  Node* control1 = graph()->NewNode(common()->Merge(2), if_null, if_undefined);
  Node* value1 = effect1 = control1 = graph()->NewNode(
      javascript()->Call(JSCallNode::ArityForArgc(0)), target, this_argument,
      n.feedback_vector(), context, frame_state, effect1, control1);
  // Rewire potential exception edges.
  Node* if_exception = nullptr;
  if (NodeProperties::IsExceptionalCall(node, &if_exception)) {
    // Create appropriate {IfException} and {IfSuccess} nodes.
    Node* if_exception0 =
        graph()->NewNode(common()->IfException(), control0, effect0);
    control0 = graph()->NewNode(common()->IfSuccess(), control0);
    Node* if_exception1 =
        graph()->NewNode(common()->IfException(), control1, effect1);
    control1 = graph()->NewNode(common()->IfSuccess(), control1);
    // Join the exception edges.
    Node* merge =
        graph()->NewNode(common()->Merge(2), if_exception0, if_exception1);
    Node* ephi = graph()->NewNode(common()->EffectPhi(2), if_exception0,
                                  if_exception1, merge);
    Node* phi =
        graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                         if_exception0, if_exception1, merge);
    ReplaceWithValue(if_exception, phi, ephi, merge);
  }
  // Join control paths.
  control = graph()->NewNode(common()->Merge(2), control0, control1);
  effect = graph()->NewNode(common()->EffectPhi(2), effect0, effect1, control);
  Node* value =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2), value0,
                       value1, control);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallOrConstructNode::ArgumentIndex(), v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), broker(), v8::internal::compiler::NodeProperties::CanBeNullOrUndefined(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), DCHECK_EQ, v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::compiler::JSCallOrConstructNode::feedback_vector(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::CallParameters::frequency(), graph(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), javascript(), jsgraph(), v8::internal::kAny, v8::internal::kFalse, v8::internal::kNullOrUndefined, v8::internal::compiler::kReceiver, v8::internal::kTagged, v8::internal::compiler::kTarget, v8::internal::compiler::kUnrelated, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReduceJSCall(), ReduceJSCallWithArrayLike(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceFunctionPrototypeBind()
Reduction v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind (Node * node) [private]
Definition at line 2993 of file js-call-reducer.cc.
                                                               {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  // Value inputs to the {node} are as follows:
  //
  // - target, which is Function.prototype.bind JSFunction
  // - receiver, which is the [[BoundTargetFunction]]
  // - bound_this (optional), which is the [[BoundThis]]
  // - and all the remaining value inputs are [[BoundArguments]]
  Node* receiver = n.receiver();
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  // Ensure that the {receiver} is known to be a JSBoundFunction or
  // a JSFunction with the same [[Prototype]], and all maps we've
  // seen for the {receiver} so far indicate that {receiver} is
  // definitely a constructor or not a constructor.
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps()) return NoChange();
  ZoneRefSet<Map> const& receiver_maps = inference.GetMaps();
  MapRef first_receiver_map = receiver_maps[0];
  bool const is_constructor = first_receiver_map.is_constructor();
  HeapObjectRef prototype = first_receiver_map.prototype(broker());
  for (MapRef receiver_map : receiver_maps) {
    HeapObjectRef map_prototype = receiver_map.prototype(broker());
    // Check for consistency among the {receiver_maps}.
    if (!map_prototype.equals(prototype) ||
        receiver_map.is_constructor() != is_constructor ||
        !InstanceTypeChecker::IsJSFunctionOrBoundFunctionOrWrappedFunction(
            receiver_map.instance_type())) {
      return inference.NoChange();
    }
    // Disallow binding of slow-mode functions. We need to figure out
    // whether the length and name property are in the original state.
    if (receiver_map.is_dictionary_map()) return inference.NoChange();
    // Check whether the length and name properties are still present
    // as AccessorInfo objects. In that case, their values can be
    // recomputed even if the actual value of the object changes.
    // This mirrors the checks done in builtins-function-gen.cc at
    // runtime otherwise.
    int minimum_nof_descriptors =
        std::max(
            {JSFunctionOrBoundFunctionOrWrappedFunction::kLengthDescriptorIndex,
             JSFunctionOrBoundFunctionOrWrappedFunction::
                 kNameDescriptorIndex}) +
        1;
    if (receiver_map.NumberOfOwnDescriptors() < minimum_nof_descriptors) {
      return inference.NoChange();
    }
    const InternalIndex kLengthIndex(
        JSFunctionOrBoundFunctionOrWrappedFunction::kLengthDescriptorIndex);
    const InternalIndex kNameIndex(
        JSFunctionOrBoundFunctionOrWrappedFunction::kNameDescriptorIndex);
    StringRef length_string = broker()->length_string();
    StringRef name_string = broker()->name_string();
    OptionalObjectRef length_value(
        receiver_map.GetStrongValue(broker(), kLengthIndex));
    OptionalObjectRef name_value(
        receiver_map.GetStrongValue(broker(), kNameIndex));
    if (!length_value || !name_value) {
      TRACE_BROKER_MISSING(
          broker(), "name or length descriptors on map " << receiver_map);
      return inference.NoChange();
    }
    if (!receiver_map.GetPropertyKey(broker(), kLengthIndex)
             .equals(length_string) ||
        !length_value->IsAccessorInfo() ||
        !receiver_map.GetPropertyKey(broker(), kNameIndex)
             .equals(name_string) ||
        !name_value->IsAccessorInfo()) {
      return inference.NoChange();
    }
  }
  // Choose the map for the resulting JSBoundFunction (but bail out in case of a
  // custom prototype).
  MapRef map =
      is_constructor
          ? native_context().bound_function_with_constructor_map(broker())
          : native_context().bound_function_without_constructor_map(broker());
  if (!map.prototype(broker()).equals(prototype)) return inference.NoChange();
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  // Replace the {node} with a JSCreateBoundFunction.
  static constexpr int kBoundThis = 1;
  static constexpr int kReceiverContextEffectAndControl = 4;
  int const arity = n.ArgumentCount();
  if (arity > 0) {
    MapRef fixed_array_map = broker()->fixed_array_map();
    AllocationBuilder ab(jsgraph(), broker(), effect, control);
    if (!ab.CanAllocateArray(arity, fixed_array_map)) {
      return NoChange();
    }
  }
  int const arity_with_bound_this = std::max(arity, kBoundThis);
  int const input_count =
      arity_with_bound_this + kReceiverContextEffectAndControl;
  Node** inputs = graph()->zone()->AllocateArray<Node*>(input_count);
  int cursor = 0;
  inputs[cursor++] = receiver;
  inputs[cursor++] = n.ArgumentOrUndefined(0, jsgraph()); // bound_this.
  for (int i = 1; i < arity; ++i) {
    inputs[cursor++] = n.Argument(i);
  }
  inputs[cursor++] = context;
  inputs[cursor++] = effect;
  inputs[cursor++] = control;
  DCHECK_EQ(cursor, input_count);
  Node* value = effect =
      graph()->NewNode(javascript()->CreateBoundFunction(
                           arity_with_bound_this - kBoundThis, map),
                       input_count, inputs);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::anonymous_namespace{builtins-intl.cc}::CreateBoundFunction(), DCHECK_EQ, dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::MapInference::GetMaps(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::MapRef::is_constructor(), v8::internal::is_constructor, javascript(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::kLengthDescriptorIndex, v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::kNameDescriptorIndex, native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::MapRef::prototype(), v8::internal::prototype, v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::CallParameters::speculation_mode(), TRACE_BROKER_MISSING, v8::internal::value, and v8::internal::compiler::TFGraph::zone().
Referenced by ReduceJSCall().
ReduceFunctionPrototypeCall()
Reduction v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall (Node * node) [private]
Definition at line 3126 of file js-call-reducer.cc.
                                                               {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  Node* target = n.target();
  Effect effect = n.effect();
  Control control = n.control();
  // Change context of {node} to the Function.prototype.call context,
  // to ensure any exception is thrown in the correct context.
  Node* context;
  HeapObjectMatcher m(target);
  if (m.HasResolvedValue() && m.Ref(broker()).IsJSFunction()) {
    JSFunctionRef function = m.Ref(broker()).AsJSFunction();
    context = jsgraph()->ConstantNoHole(function.context(broker()), broker());
  } else {
    context = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSFunctionContext()), target,
        effect, control);
  }
  NodeProperties::ReplaceContextInput(node, context);
  NodeProperties::ReplaceEffectInput(node, effect);
  // Remove the target from {node} and use the receiver as target instead, and
  // the thisArg becomes the new target. If thisArg was not provided, insert
  // undefined instead.
  int arity = p.arity_without_implicit_args();
  ConvertReceiverMode convert_mode;
  if (arity == 0) {
    // The thisArg was not provided, use undefined as receiver.
    convert_mode = ConvertReceiverMode::kNullOrUndefined;
    node->ReplaceInput(n.TargetIndex(), n.receiver());
    node->ReplaceInput(n.ReceiverIndex(), jsgraph()->UndefinedConstant());
  } else {
    // Just remove the target, which is the first value input.
    convert_mode = ConvertReceiverMode::kAny;
    node->RemoveInput(n.TargetIndex());
    --arity;
  }
  NodeProperties::ChangeOp(
      node, javascript()->Call(JSCallNode::ArityForArgc(arity), p.frequency(),
                               p.feedback(), convert_mode, p.speculation_mode(),
                               CallFeedbackRelation::kUnrelated));
  // Try to further reduce the JSCall {node}.
  return Changed(node).FollowedBy(ReduceJSCall(node));
}
References v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::AccessBuilder::ForJSFunctionContext(), v8::internal::compiler::CallParameters::frequency(), graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), javascript(), jsgraph(), v8::internal::kAny, v8::internal::kNullOrUndefined, v8::internal::compiler::kUnrelated, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReduceJSCall(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::ReplaceContextInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCall().
ReduceFunctionPrototypeHasInstance()
Reduction v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance (Node * node) [private]
Definition at line 3173 of file js-call-reducer.cc.
                                                                      {
  JSCallNode n(node);
  Node* receiver = n.receiver();
  Node* object = n.ArgumentOrUndefined(0, jsgraph());
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Effect effect = n.effect();
  Control control = n.control();
  // TODO(turbofan): If JSOrdinaryToInstance raises an exception, the
  // stack trace doesn't contain the @@hasInstance call; we have the
  // corresponding bug in the baseline case. Some massaging of the frame
  // state would be necessary here.
  // Morph this {node} into a JSOrdinaryHasInstance node.
  node->ReplaceInput(0, receiver);
  node->ReplaceInput(1, object);
  node->ReplaceInput(2, context);
  node->ReplaceInput(3, frame_state);
  node->ReplaceInput(4, effect);
  node->ReplaceInput(5, control);
  node->TrimInputCount(6);
  NodeProperties::ChangeOp(node, javascript()->OrdinaryHasInstance());
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), javascript(), jsgraph(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by ReduceJSCall().
ReduceGlobalIsFinite()
Reduction v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite (Node * node) [private]
Definition at line 8772 of file js-call-reducer.cc.
                                                        {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* input = n.Argument(0);
  input = effect =
      graph()->NewNode(simplified()->SpeculativeToNumber(
                           NumberOperationHint::kNumberOrOddball, p.feedback()),
                       input, effect, control);
  Node* value = graph()->NewNode(simplified()->NumberIsFinite(), input);
  ReplaceWithValue(node, value, effect);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceGlobalIsNaN()
Reduction v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN (Node * node) [private]
Definition at line 8798 of file js-call-reducer.cc.
                                                     {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->TrueConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* input = n.Argument(0);
  input = effect =
      graph()->NewNode(simplified()->SpeculativeToNumber(
                           NumberOperationHint::kNumberOrOddball, p.feedback()),
                       input, effect, control);
  Node* value = graph()->NewNode(simplified()->NumberIsNaN(), input);
  ReplaceWithValue(node, value, effect);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceJSCall() [1/2]
Reduction v8::internal::compiler::JSCallReducer::ReduceJSCall (Node * node) [private]
Definition at line 4700 of file js-call-reducer.cc.
                                                {
  if (broker()->StackHasOverflowed()) return NoChange();
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  Node* target = n.target();
  Effect effect = n.effect();
  Control control = n.control();
  int arity = p.arity_without_implicit_args();
  auto NoChangeOrSoftDeopt = [&]() {
    if (p.feedback().IsValid()) {
      ProcessedFeedback const& feedback =
          broker()->GetFeedbackForCall(p.feedback());
      if (feedback.IsInsufficient()) {
        return ReduceForInsufficientFeedback(
            node, DeoptimizeReason::kInsufficientTypeFeedbackForCall);
      }
    }
    return NoChange();
  };
  // Try to specialize JSCall {node}s with constant {target}s.
  HeapObjectMatcher m(target);
  if (m.HasResolvedValue()) {
    ObjectRef target_ref = m.Ref(broker());
    if (target_ref.IsJSFunction()) {
      JSFunctionRef function = target_ref.AsJSFunction();
      // Don't inline cross native context.
      if (!function.native_context(broker()).equals(native_context())) {
        return NoChange();
      }
      Reduction res = ReduceJSCall(node, function.shared(broker()));
      if (!res.Changed()) return NoChangeOrSoftDeopt();
      return res;
    } else if (target_ref.IsJSBoundFunction()) {
      JSBoundFunctionRef function = target_ref.AsJSBoundFunction();
      ObjectRef bound_this = function.bound_this(broker());
      ConvertReceiverMode const convert_mode =
          bound_this.IsNullOrUndefined()
              ? ConvertReceiverMode::kNullOrUndefined
              : ConvertReceiverMode::kNotNullOrUndefined;
      // TODO(jgruber): Inline this block below once TryGet is guaranteed to
      // succeed.
      FixedArrayRef bound_arguments = function.bound_arguments(broker());
      const uint32_t bound_arguments_length = bound_arguments.length();
      if (arity + bound_arguments_length + /* receiver */ 1 >
          Code::kMaxArguments) {
        return NoChange();
      }
      static constexpr int kInlineSize = 16; // Arbitrary.
      base::SmallVector<Node*, kInlineSize> args;
      for (uint32_t i = 0; i < bound_arguments_length; ++i) {
        OptionalObjectRef maybe_arg = bound_arguments.TryGet(broker(), i);
        if (!maybe_arg.has_value()) {
          TRACE_BROKER_MISSING(broker(), "bound argument");
          return NoChangeOrSoftDeopt();
        }
        args.emplace_back(
            jsgraph()->ConstantNoHole(maybe_arg.value(), broker()));
      }
      // Patch {node} to use [[BoundTargetFunction]] and [[BoundThis]].
      NodeProperties::ReplaceValueInput(
          node,
          jsgraph()->ConstantNoHole(function.bound_target_function(broker()),
                                    broker()),
          JSCallNode::TargetIndex());
      NodeProperties::ReplaceValueInput(
          node, jsgraph()->ConstantNoHole(bound_this, broker()),
          JSCallNode::ReceiverIndex());
      // Insert the [[BoundArguments]] for {node}.
      for (uint32_t i = 0; i < bound_arguments_length; ++i) {
        node->InsertInput(graph()->zone(), i + 2, args[i]);
        arity++;
      }
      NodeProperties::ChangeOp(
          node,
          javascript()->Call(JSCallNode::ArityForArgc(arity), p.frequency(),
                             p.feedback(), convert_mode, p.speculation_mode(),
                             CallFeedbackRelation::kUnrelated));
      // Try to further reduce the JSCall {node}.
      return Changed(node).FollowedBy(ReduceJSCall(node));
    }
    // Don't mess with other {node}s that have a constant {target}.
    // TODO(bmeurer): Also support proxies here.
    return NoChangeOrSoftDeopt();
  }
  // If {target} is the result of a JSCreateClosure operation, we can
  // just immediately try to inline based on the SharedFunctionInfo,
  // since TurboFan generally doesn't inline cross-context, and hence
  // the {target} must have the same native context as the call site.
  // Same if the {target} is the result of a CheckClosure operation.
  if (target->opcode() == IrOpcode::kJSCreateClosure) {
    CreateClosureParameters const& params =
        JSCreateClosureNode{target}.Parameters();
    Reduction res = ReduceJSCall(node, params.shared_info());
    if (!res.Changed()) return NoChangeOrSoftDeopt();
    return res;
  } else if (target->opcode() == IrOpcode::kCheckClosure) {
    FeedbackCellRef cell = MakeRef(broker(), FeedbackCellOf(target->op()));
    OptionalSharedFunctionInfoRef shared = cell.shared_function_info(broker());
    if (!shared.has_value()) {
      TRACE_BROKER_MISSING(broker(), "Unable to reduce JSCall. FeedbackCell "
                                         << cell << " has no FeedbackVector");
      return NoChangeOrSoftDeopt();
    }
    Reduction res = ReduceJSCall(node, *shared);
    if (!res.Changed()) return NoChangeOrSoftDeopt();
    return res;
  }
  // If {target} is the result of a JSCreateBoundFunction operation,
  // we can just fold the construction and call the bound target
  // function directly instead.
  if (target->opcode() == IrOpcode::kJSCreateBoundFunction) {
    Node* bound_target_function = NodeProperties::GetValueInput(target, 0);
    Node* bound_this = NodeProperties::GetValueInput(target, 1);
    uint32_t const bound_arguments_length =
        static_cast<int>(CreateBoundFunctionParametersOf(target->op()).arity());
    // Patch the {node} to use [[BoundTargetFunction]] and [[BoundThis]].
    NodeProperties::ReplaceValueInput(node, bound_target_function,
                                      n.TargetIndex());
    NodeProperties::ReplaceValueInput(node, bound_this, n.ReceiverIndex());
    // Insert the [[BoundArguments]] for {node}.
    for (uint32_t i = 0; i < bound_arguments_length; ++i) {
      Node* value = NodeProperties::GetValueInput(target, 2 + i);
      node->InsertInput(graph()->zone(), n.ArgumentIndex(i), value);
      arity++;
    }
    // Update the JSCall operator on {node}.
    ConvertReceiverMode const convert_mode =
        NodeProperties::CanBeNullOrUndefined(broker(), bound_this, effect)
            ? ConvertReceiverMode::kAny
            : ConvertReceiverMode::kNotNullOrUndefined;
    NodeProperties::ChangeOp(
        node,
        javascript()->Call(JSCallNode::ArityForArgc(arity), p.frequency(),
                           p.feedback(), convert_mode, p.speculation_mode(),
                           CallFeedbackRelation::kUnrelated));
    // Try to further reduce the JSCall {node}.
    return Changed(node).FollowedBy(ReduceJSCall(node));
  }
  if (!ShouldUseCallICFeedback(target) ||
      p.feedback_relation() == CallFeedbackRelation::kUnrelated ||
      !p.feedback().IsValid()) {
    return NoChange();
  }
  ProcessedFeedback const& feedback =
      broker()->GetFeedbackForCall(p.feedback());
  if (feedback.IsInsufficient()) {
    return ReduceForInsufficientFeedback(
        node, DeoptimizeReason::kInsufficientTypeFeedbackForCall);
  }
  OptionalHeapObjectRef feedback_target;
  if (p.feedback_relation() == CallFeedbackRelation::kTarget) {
    feedback_target = feedback.AsCall().target();
  } else {
    DCHECK_EQ(p.feedback_relation(), CallFeedbackRelation::kReceiver);
    feedback_target = native_context().function_prototype_apply(broker());
  }
  if (feedback_target.has_value() &&
      feedback_target->map(broker()).is_callable()) {
    Node* target_function =
        jsgraph()->ConstantNoHole(*feedback_target, broker());
    // Check that the {target} is still the {target_function}.
    Node* check = graph()->NewNode(simplified()->ReferenceEqual(), target,
                                   target_function);
    effect = graph()->NewNode(
        simplified()->CheckIf(DeoptimizeReason::kWrongCallTarget), check,
        effect, control);
    // Specialize the JSCall node to the {target_function}.
    NodeProperties::ReplaceValueInput(node, target_function, n.TargetIndex());
    NodeProperties::ReplaceEffectInput(node, effect);
    // Try to further reduce the JSCall {node}.
    return Changed(node).FollowedBy(ReduceJSCall(node));
  } else if (feedback_target.has_value() && feedback_target->IsFeedbackCell()) {
    FeedbackCellRef feedback_cell = feedback_target.value().AsFeedbackCell();
    // TODO(neis): This check seems unnecessary.
    if (feedback_cell.feedback_vector(broker()).has_value()) {
      // Check that {target} is a closure with given {feedback_cell},
      // which uniquely identifies a given function inside a native context.
      Node* target_closure = effect =
          graph()->NewNode(simplified()->CheckClosure(feedback_cell.object()),
                           target, effect, control);
      // Specialize the JSCall node to the {target_closure}.
      NodeProperties::ReplaceValueInput(node, target_closure, n.TargetIndex());
      NodeProperties::ReplaceEffectInput(node, effect);
      // Try to further reduce the JSCall {node}.
      return Changed(node).FollowedBy(ReduceJSCall(node));
    }
  }
  return NoChange();
}
References v8::base::args, v8::internal::compiler::JSCallOrConstructNode::ArgumentIndex(), v8::internal::compiler::CreateBoundFunctionParameters::arity(), v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), v8::internal::compiler::NodeProperties::CanBeNullOrUndefined(), v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::CreateBoundFunctionParametersOf(), DCHECK_EQ, v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::compiler::FeedbackCellRef::feedback_vector(), v8::internal::compiler::FeedbackCellOf(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::JSHeapBroker::GetFeedbackForCall(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::FeedbackSource::IsValid(), javascript(), jsgraph(), v8::internal::kAny, v8::internal::Code::kMaxArguments, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, v8::internal::compiler::kReceiver, v8::internal::compiler::kTarget, v8::internal::compiler::kUnrelated, v8::internal::compiler::FixedArrayBaseRef::length(), v8::internal::compiler::MakeRef(), native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::FeedbackCellRef::object(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReduceForInsufficientFeedback(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::FeedbackCellRef::shared_function_info(), v8::internal::compiler::CreateClosureParameters::shared_info(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::compiler::CallFeedback::target(), TRACE_BROKER_MISSING, v8::internal::compiler::FixedArrayRef::TryGet(), v8::internal::compiler::FeedbackCellRef::value(), and v8::internal::value.
Referenced by Reduce(), ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), ReduceFunctionPrototypeApply(), and ReduceFunctionPrototypeCall().
ReduceJSCall() [2/2]
Reduction v8::internal::compiler::JSCallReducer::ReduceJSCall (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 4916 of file js-call-reducer.cc.
                                                                    {
  JSCallNode n(node);
  Node* target = n.target();
  // Do not reduce calls to functions with break points.
  // If this state changes during background compilation, the compilation
  // job will be aborted from the main thread (see
  // Debug::PrepareFunctionForDebugExecution()).
  if (shared.HasBreakInfo(broker())) return NoChange();
  // Class constructors are callable, but [[Call]] will raise an exception.
  // See ES6 section 9.2.1 [[Call]] (thisArgument, argumentsList).
  if (IsClassConstructor(shared.kind())) {
    NodeProperties::ReplaceValueInputs(node, target);
    NodeProperties::ChangeOp(
        node, javascript()->CallRuntime(
                  Runtime::kThrowConstructorNonCallableError, 1));
    return Changed(node);
  }
  // Check for known builtin functions.
  Builtin builtin =
      shared.HasBuiltinId() ? shared.builtin_id() : Builtin::kNoBuiltinId;
  switch (builtin) {
    case Builtin::kArrayConstructor:
      return ReduceArrayConstructor(node);
    case Builtin::kBooleanConstructor:
      return ReduceBooleanConstructor(node);
    case Builtin::kFunctionPrototypeApply:
      return ReduceFunctionPrototypeApply(node);
    case Builtin::kFastFunctionPrototypeBind:
      return ReduceFunctionPrototypeBind(node);
    case Builtin::kFunctionPrototypeCall:
      return ReduceFunctionPrototypeCall(node);
    case Builtin::kFunctionPrototypeHasInstance:
      return ReduceFunctionPrototypeHasInstance(node);
    case Builtin::kObjectConstructor:
      return ReduceObjectConstructor(node);
    case Builtin::kObjectCreate:
      return ReduceObjectCreate(node);
    case Builtin::kObjectGetPrototypeOf:
      return ReduceObjectGetPrototypeOf(node);
    case Builtin::kObjectIs:
      return ReduceObjectIs(node);
    case Builtin::kObjectPrototypeGetProto:
      return ReduceObjectPrototypeGetProto(node);
    case Builtin::kObjectPrototypeHasOwnProperty:
      return ReduceObjectPrototypeHasOwnProperty(node);
    case Builtin::kObjectPrototypeIsPrototypeOf:
      return ReduceObjectPrototypeIsPrototypeOf(node);
    case Builtin::kReflectApply:
      return ReduceReflectApply(node);
    case Builtin::kReflectConstruct:
      return ReduceReflectConstruct(node);
    case Builtin::kReflectGet:
      return ReduceReflectGet(node);
    case Builtin::kReflectGetPrototypeOf:
      return ReduceReflectGetPrototypeOf(node);
    case Builtin::kReflectHas:
      return ReduceReflectHas(node);
    case Builtin::kArrayForEach:
      return ReduceArrayForEach(node, shared);
    case Builtin::kArrayMap:
      return ReduceArrayMap(node, shared);
    case Builtin::kArrayFilter:
      return ReduceArrayFilter(node, shared);
    case Builtin::kArrayReduce:
      return ReduceArrayReduce(node, shared);
    case Builtin::kArrayReduceRight:
      return ReduceArrayReduceRight(node, shared);
    case Builtin::kArrayPrototypeFind:
      return ReduceArrayFind(node, shared);
    case Builtin::kArrayPrototypeFindIndex:
      return ReduceArrayFindIndex(node, shared);
    case Builtin::kArrayEvery:
      return ReduceArrayEvery(node, shared);
    case Builtin::kArrayIndexOf:
      return ReduceArrayIndexOf(node);
    case Builtin::kArrayIncludes:
      return ReduceArrayIncludes(node);
    case Builtin::kArraySome:
      return ReduceArraySome(node, shared);
    case Builtin::kArrayPrototypeAt:
      return ReduceArrayPrototypeAt(node);
    case Builtin::kArrayPrototypePush:
      return ReduceArrayPrototypePush(node);
    case Builtin::kArrayPrototypePop:
      return ReduceArrayPrototypePop(node);
    // TODO(v8:14409): The current implementation of the inlined
    // ArrayPrototypeShift version doesn't seem to be beneficial and even
    // counter-productive at least for Object ElementsKinds. Disable it until
    // improvements/better heuristics have been implemented.
    // case Builtin::kArrayPrototypeShift:
    // return ReduceArrayPrototypeShift(node);
    case Builtin::kArrayPrototypeSlice:
      return ReduceArrayPrototypeSlice(node);
    case Builtin::kArrayPrototypeEntries:
      return ReduceArrayIterator(node, ArrayIteratorKind::kArrayLike,
                                 IterationKind::kEntries);
    case Builtin::kArrayPrototypeKeys:
      return ReduceArrayIterator(node, ArrayIteratorKind::kArrayLike,
                                 IterationKind::kKeys);
    case Builtin::kArrayPrototypeValues:
      return ReduceArrayIterator(node, ArrayIteratorKind::kArrayLike,
                                 IterationKind::kValues);
    case Builtin::kArrayIteratorPrototypeNext:
      return ReduceArrayIteratorPrototypeNext(node);
    case Builtin::kArrayIsArray:
      return ReduceArrayIsArray(node);
    case Builtin::kArrayBufferIsView:
      return ReduceArrayBufferIsView(node);
    case Builtin::kDataViewPrototypeGetByteLength:
      // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
      return ReduceArrayBufferViewByteLengthAccessor(node, JS_DATA_VIEW_TYPE,
                                                     builtin);
    case Builtin::kDataViewPrototypeGetByteOffset:
      // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
      return ReduceArrayBufferViewByteOffsetAccessor(node, JS_DATA_VIEW_TYPE,
                                                     builtin);
    case Builtin::kDataViewPrototypeGetUint8:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalUint8Array);
    case Builtin::kDataViewPrototypeGetInt8:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalInt8Array);
    case Builtin::kDataViewPrototypeGetUint16:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalUint16Array);
    case Builtin::kDataViewPrototypeGetInt16:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalInt16Array);
    case Builtin::kDataViewPrototypeGetUint32:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalUint32Array);
    case Builtin::kDataViewPrototypeGetInt32:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalInt32Array);
    case Builtin::kDataViewPrototypeGetFloat16:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalFloat16Array);
    case Builtin::kDataViewPrototypeGetFloat32:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalFloat32Array);
    case Builtin::kDataViewPrototypeGetFloat64:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalFloat64Array);
    case Builtin::kDataViewPrototypeGetBigInt64:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalBigInt64Array);
    case Builtin::kDataViewPrototypeGetBigUint64:
      return ReduceDataViewAccess(node, DataViewAccess::kGet,
                                  ExternalArrayType::kExternalBigUint64Array);
    case Builtin::kDataViewPrototypeSetUint8:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalUint8Array);
    case Builtin::kDataViewPrototypeSetInt8:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalInt8Array);
    case Builtin::kDataViewPrototypeSetUint16:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalUint16Array);
    case Builtin::kDataViewPrototypeSetInt16:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalInt16Array);
    case Builtin::kDataViewPrototypeSetUint32:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalUint32Array);
    case Builtin::kDataViewPrototypeSetInt32:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalInt32Array);
    case Builtin::kDataViewPrototypeSetFloat16:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalFloat16Array);
    case Builtin::kDataViewPrototypeSetFloat32:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalFloat32Array);
    case Builtin::kDataViewPrototypeSetFloat64:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalFloat64Array);
    case Builtin::kDataViewPrototypeSetBigInt64:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalBigInt64Array);
    case Builtin::kDataViewPrototypeSetBigUint64:
      return ReduceDataViewAccess(node, DataViewAccess::kSet,
                                  ExternalArrayType::kExternalBigUint64Array);
    case Builtin::kDatePrototypeGetFullYear:
      return ReduceDatePrototypeGetField(node, JSDate::kYear);
    case Builtin::kDatePrototypeGetMonth:
      return ReduceDatePrototypeGetField(node, JSDate::kMonth);
    case Builtin::kDatePrototypeGetDate:
      return ReduceDatePrototypeGetField(node, JSDate::kDay);
    case Builtin::kDatePrototypeGetDay:
      return ReduceDatePrototypeGetField(node, JSDate::kWeekday);
    case Builtin::kDatePrototypeGetHours:
      return ReduceDatePrototypeGetField(node, JSDate::kHour);
    case Builtin::kDatePrototypeGetMinutes:
      return ReduceDatePrototypeGetField(node, JSDate::kMinute);
    case Builtin::kDatePrototypeGetSeconds:
      return ReduceDatePrototypeGetField(node, JSDate::kSecond);
    case Builtin::kTypedArrayPrototypeByteLength:
      return ReduceArrayBufferViewByteLengthAccessor(node, JS_TYPED_ARRAY_TYPE,
                                                     builtin);
    case Builtin::kTypedArrayPrototypeByteOffset:
      return ReduceArrayBufferViewByteOffsetAccessor(node, JS_TYPED_ARRAY_TYPE,
                                                     builtin);
    case Builtin::kTypedArrayPrototypeLength:
      return ReduceTypedArrayPrototypeLength(node);
    case Builtin::kTypedArrayPrototypeToStringTag:
      return ReduceTypedArrayPrototypeToStringTag(node);
    case Builtin::kMathAbs:
      return ReduceMathUnary(node, simplified()->NumberAbs());
    case Builtin::kMathAcos:
      return ReduceMathUnary(node, simplified()->NumberAcos());
    case Builtin::kMathAcosh:
      return ReduceMathUnary(node, simplified()->NumberAcosh());
    case Builtin::kMathAsin:
      return ReduceMathUnary(node, simplified()->NumberAsin());
    case Builtin::kMathAsinh:
      return ReduceMathUnary(node, simplified()->NumberAsinh());
    case Builtin::kMathAtan:
      return ReduceMathUnary(node, simplified()->NumberAtan());
    case Builtin::kMathAtanh:
      return ReduceMathUnary(node, simplified()->NumberAtanh());
    case Builtin::kMathCbrt:
      return ReduceMathUnary(node, simplified()->NumberCbrt());
    case Builtin::kMathCeil:
      return ReduceMathUnary(node, simplified()->NumberCeil());
    case Builtin::kMathCos:
      return ReduceMathUnary(node, simplified()->NumberCos());
    case Builtin::kMathCosh:
      return ReduceMathUnary(node, simplified()->NumberCosh());
    case Builtin::kMathExp:
      return ReduceMathUnary(node, simplified()->NumberExp());
    case Builtin::kMathExpm1:
      return ReduceMathUnary(node, simplified()->NumberExpm1());
    case Builtin::kMathFloor:
      return ReduceMathUnary(node, simplified()->NumberFloor());
    case Builtin::kMathFround:
      return ReduceMathUnary(node, simplified()->NumberFround());
    case Builtin::kMathLog:
      return ReduceMathUnary(node, simplified()->NumberLog());
    case Builtin::kMathLog1p:
      return ReduceMathUnary(node, simplified()->NumberLog1p());
    case Builtin::kMathLog10:
      return ReduceMathUnary(node, simplified()->NumberLog10());
    case Builtin::kMathLog2:
      return ReduceMathUnary(node, simplified()->NumberLog2());
    case Builtin::kMathRound:
      return ReduceMathUnary(node, simplified()->NumberRound());
    case Builtin::kMathSign:
      return ReduceMathUnary(node, simplified()->NumberSign());
    case Builtin::kMathSin:
      return ReduceMathUnary(node, simplified()->NumberSin());
    case Builtin::kMathSinh:
      return ReduceMathUnary(node, simplified()->NumberSinh());
    case Builtin::kMathSqrt:
      return ReduceMathUnary(node, simplified()->NumberSqrt());
    case Builtin::kMathTan:
      return ReduceMathUnary(node, simplified()->NumberTan());
    case Builtin::kMathTanh:
      return ReduceMathUnary(node, simplified()->NumberTanh());
    case Builtin::kMathTrunc:
      return ReduceMathUnary(node, simplified()->NumberTrunc());
    case Builtin::kMathAtan2:
      return ReduceMathBinary(node, simplified()->NumberAtan2());
    case Builtin::kMathPow:
      return ReduceMathBinary(node, simplified()->NumberPow());
    case Builtin::kMathClz32:
      return ReduceMathClz32(node);
    case Builtin::kMathImul:
      return ReduceMathImul(node);
    case Builtin::kMathMax:
      return ReduceMathMinMax(node, simplified()->NumberMax(),
                              jsgraph()->ConstantNoHole(-V8_INFINITY));
    case Builtin::kMathMin:
      return ReduceMathMinMax(node, simplified()->NumberMin(),
                              jsgraph()->ConstantNoHole(V8_INFINITY));
    case Builtin::kNumberIsFinite:
      return ReduceNumberIsFinite(node);
    case Builtin::kNumberIsInteger:
      return ReduceNumberIsInteger(node);
    case Builtin::kNumberIsSafeInteger:
      return ReduceNumberIsSafeInteger(node);
    case Builtin::kNumberIsNaN:
      return ReduceNumberIsNaN(node);
    case Builtin::kNumberParseInt:
      return ReduceNumberParseInt(node);
    case Builtin::kGlobalIsFinite:
      return ReduceGlobalIsFinite(node);
    case Builtin::kGlobalIsNaN:
      return ReduceGlobalIsNaN(node);
    case Builtin::kMapPrototypeGet:
      return ReduceMapPrototypeGet(node);
    case Builtin::kMapPrototypeHas:
      return ReduceMapPrototypeHas(node);
    case Builtin::kSetPrototypeHas:
      return ReduceSetPrototypeHas(node);
    case Builtin::kRegExpPrototypeTest:
      return ReduceRegExpPrototypeTest(node);
    case Builtin::kReturnReceiver:
      return ReduceReturnReceiver(node);
    case Builtin::kStringPrototypeIndexOf:
      return ReduceStringPrototypeIndexOfIncludes(
          node, StringIndexOfIncludesVariant::kIndexOf);
    case Builtin::kStringPrototypeIncludes:
      return ReduceStringPrototypeIndexOfIncludes(
          node, StringIndexOfIncludesVariant::kIncludes);
    case Builtin::kStringPrototypeCharAt:
      return ReduceStringPrototypeCharAt(node);
    case Builtin::kStringPrototypeCharCodeAt:
      return ReduceStringPrototypeStringCharCodeAt(node);
    case Builtin::kStringPrototypeCodePointAt:
      return ReduceStringPrototypeStringCodePointAt(node);
    case Builtin::kStringPrototypeSubstring:
      return ReduceStringPrototypeSubstring(node);
    case Builtin::kStringPrototypeSlice:
      return ReduceStringPrototypeSlice(node);
    case Builtin::kStringPrototypeSubstr:
      return ReduceStringPrototypeSubstr(node);
    case Builtin::kStringPrototypeStartsWith:
      return ReduceStringPrototypeStartsWith(node);
    case Builtin::kStringPrototypeEndsWith:
      return ReduceStringPrototypeEndsWith(node);
#ifdef V8_INTL_SUPPORT
    case Builtin::kStringPrototypeLocaleCompareIntl:
      return ReduceStringPrototypeLocaleCompareIntl(node);
    case Builtin::kStringPrototypeToLowerCaseIntl:
      return ReduceStringPrototypeToLowerCaseIntl(node);
    case Builtin::kStringPrototypeToUpperCaseIntl:
      return ReduceStringPrototypeToUpperCaseIntl(node);
#endif // V8_INTL_SUPPORT
    case Builtin::kStringFromCharCode:
      return ReduceStringFromCharCode(node);
    case Builtin::kStringFromCodePoint:
      return ReduceStringFromCodePoint(node);
    case Builtin::kStringPrototypeIterator:
      return ReduceStringPrototypeIterator(node);
    case Builtin::kStringIteratorPrototypeNext:
      return ReduceStringIteratorPrototypeNext(node);
    case Builtin::kStringPrototypeConcat:
      return ReduceStringPrototypeConcat(node);
    case Builtin::kTypedArrayPrototypeEntries:
      return ReduceArrayIterator(node, ArrayIteratorKind::kTypedArray,
                                 IterationKind::kEntries);
    case Builtin::kTypedArrayPrototypeKeys:
      return ReduceArrayIterator(node, ArrayIteratorKind::kTypedArray,
                                 IterationKind::kKeys);
    case Builtin::kTypedArrayPrototypeValues:
      return ReduceArrayIterator(node, ArrayIteratorKind::kTypedArray,
                                 IterationKind::kValues);
    case Builtin::kPromisePrototypeCatch:
      return ReducePromisePrototypeCatch(node);
    case Builtin::kPromisePrototypeFinally:
      return ReducePromisePrototypeFinally(node);
    case Builtin::kPromisePrototypeThen:
      return ReducePromisePrototypeThen(node);
    case Builtin::kPromiseResolveTrampoline:
      return ReducePromiseResolveTrampoline(node);
    case Builtin::kMapPrototypeEntries:
      return ReduceCollectionIteration(node, CollectionKind::kMap,
                                       IterationKind::kEntries);
    case Builtin::kMapPrototypeKeys:
      return ReduceCollectionIteration(node, CollectionKind::kMap,
                                       IterationKind::kKeys);
    case Builtin::kMapPrototypeGetSize:
      return ReduceCollectionPrototypeSize(node, CollectionKind::kMap);
    case Builtin::kMapPrototypeValues:
      return ReduceCollectionIteration(node, CollectionKind::kMap,
                                       IterationKind::kValues);
    case Builtin::kMapIteratorPrototypeNext:
      return ReduceCollectionIteratorPrototypeNext(
          node, OrderedHashMap::kEntrySize, factory()->empty_ordered_hash_map(),
          FIRST_JS_MAP_ITERATOR_TYPE, LAST_JS_MAP_ITERATOR_TYPE);
    case Builtin::kSetPrototypeEntries:
      return ReduceCollectionIteration(node, CollectionKind::kSet,
                                       IterationKind::kEntries);
    case Builtin::kSetPrototypeGetSize:
      return ReduceCollectionPrototypeSize(node, CollectionKind::kSet);
    case Builtin::kSetPrototypeValues:
      return ReduceCollectionIteration(node, CollectionKind::kSet,
                                       IterationKind::kValues);
    case Builtin::kSetIteratorPrototypeNext:
      return ReduceCollectionIteratorPrototypeNext(
          node, OrderedHashSet::kEntrySize, factory()->empty_ordered_hash_set(),
          FIRST_JS_SET_ITERATOR_TYPE, LAST_JS_SET_ITERATOR_TYPE);
    case Builtin::kDatePrototypeGetTime:
      return ReduceDatePrototypeGetTime(node);
    case Builtin::kDateNow:
      return ReduceDateNow(node);
    case Builtin::kNumberConstructor:
      return ReduceNumberConstructor(node);
    case Builtin::kBigIntConstructor:
      return ReduceBigIntConstructor(node);
    case Builtin::kBigIntAsIntN:
    case Builtin::kBigIntAsUintN:
      return ReduceBigIntAsN(node, builtin);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    case Builtin::kGetContinuationPreservedEmbedderData:
      return ReduceGetContinuationPreservedEmbedderData(node);
    case Builtin::kSetContinuationPreservedEmbedderData:
      return ReduceSetContinuationPreservedEmbedderData(node);
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    default:
      break;
  }
  if (shared.function_template_info(broker()).has_value()) {
    return ReduceCallApiFunction(node, shared);
  }
#if V8_ENABLE_WEBASSEMBLY
  if ((flags() & kInlineJSToWasmCalls) &&
      // Peek at the trusted object; ReduceCallWasmFunction will do that again
      // and crash if this is not a WasmExportedFunctionData any more then.
      IsWasmExportedFunctionData(shared.object()->GetTrustedData(isolate()))) {
    return ReduceCallWasmFunction(node, shared);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return NoChange();
}
References broker(), v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), factory(), flags(), v8::internal::compiler::SharedFunctionInfoRef::function_template_info(), v8::internal::compiler::SharedFunctionInfoRef::HasBreakInfo(), v8::internal::IsClassConstructor(), isolate(), javascript(), jsgraph(), kArrayLike, v8::internal::JSDate::kDay, v8::internal::kEntries, v8::internal::OrderedHashTable< OrderedHashSet, 1 >::kEntrySize, v8::internal::OrderedHashTable< OrderedHashMap, 2 >::kEntrySize, v8::internal::kExternalBigInt64Array, v8::internal::kExternalBigUint64Array, v8::internal::kExternalFloat16Array, v8::internal::kExternalFloat32Array, v8::internal::kExternalFloat64Array, v8::internal::kExternalInt16Array, v8::internal::kExternalInt32Array, v8::internal::kExternalInt8Array, v8::internal::kExternalUint16Array, v8::internal::kExternalUint32Array, v8::internal::kExternalUint8Array, kGet, v8::internal::JSDate::kHour, kIncludes, kIndexOf, kInlineJSToWasmCalls, v8::internal::kKeys, v8::internal::kMap, v8::internal::JSDate::kMinute, v8::internal::JSDate::kMonth, v8::internal::kNoBuiltinId, v8::internal::JSDate::kSecond, v8::internal::kSet, kSet, kTypedArray, v8::internal::kValues, v8::internal::JSDate::kWeekday, v8::internal::JSDate::kYear, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::SharedFunctionInfoRef::object(), ReduceArrayBufferIsView(), ReduceArrayBufferViewByteLengthAccessor(), ReduceArrayBufferViewByteOffsetAccessor(), ReduceArrayConstructor(), ReduceArrayEvery(), ReduceArrayFilter(), ReduceArrayFind(), ReduceArrayFindIndex(), ReduceArrayForEach(), ReduceArrayIncludes(), ReduceArrayIndexOf(), ReduceArrayIsArray(), ReduceArrayIterator(), ReduceArrayIteratorPrototypeNext(), ReduceArrayMap(), ReduceArrayPrototypeAt(), ReduceArrayPrototypePop(), ReduceArrayPrototypePush(), ReduceArrayPrototypeSlice(), ReduceArrayReduce(), ReduceArrayReduceRight(), ReduceArraySome(), ReduceBigIntAsN(), ReduceBigIntConstructor(), ReduceBooleanConstructor(), ReduceCallApiFunction(), ReduceCallWasmFunction(), ReduceCollectionIteration(), ReduceCollectionIteratorPrototypeNext(), ReduceCollectionPrototypeSize(), ReduceDataViewAccess(), ReduceDateNow(), ReduceDatePrototypeGetField(), ReduceDatePrototypeGetTime(), ReduceFunctionPrototypeApply(), ReduceFunctionPrototypeBind(), ReduceFunctionPrototypeCall(), ReduceFunctionPrototypeHasInstance(), ReduceGlobalIsFinite(), ReduceGlobalIsNaN(), ReduceMapPrototypeGet(), ReduceMapPrototypeHas(), ReduceMathBinary(), ReduceMathClz32(), ReduceMathImul(), ReduceMathMinMax(), ReduceMathUnary(), ReduceNumberConstructor(), ReduceNumberIsFinite(), ReduceNumberIsInteger(), ReduceNumberIsNaN(), ReduceNumberIsSafeInteger(), ReduceNumberParseInt(), ReduceObjectConstructor(), ReduceObjectCreate(), ReduceObjectGetPrototypeOf(), ReduceObjectIs(), ReduceObjectPrototypeGetProto(), ReduceObjectPrototypeHasOwnProperty(), ReduceObjectPrototypeIsPrototypeOf(), ReducePromisePrototypeCatch(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReducePromiseResolveTrampoline(), ReduceReflectApply(), ReduceReflectConstruct(), ReduceReflectGet(), ReduceReflectGetPrototypeOf(), ReduceReflectHas(), ReduceRegExpPrototypeTest(), ReduceReturnReceiver(), ReduceSetPrototypeHas(), ReduceStringFromCharCode(), ReduceStringFromCodePoint(), ReduceStringIteratorPrototypeNext(), ReduceStringPrototypeCharAt(), ReduceStringPrototypeConcat(), ReduceStringPrototypeEndsWith(), ReduceStringPrototypeIndexOfIncludes(), ReduceStringPrototypeIterator(), ReduceStringPrototypeSlice(), ReduceStringPrototypeStartsWith(), ReduceStringPrototypeStringCharCodeAt(), ReduceStringPrototypeStringCodePointAt(), ReduceStringPrototypeSubstr(), ReduceStringPrototypeSubstring(), ReduceTypedArrayPrototypeLength(), ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), simplified(), and V8_INFINITY.
ReduceJSCallMathMinMaxWithArrayLike()
Reduction v8::internal::compiler::JSCallReducer::ReduceJSCallMathMinMaxWithArrayLike (Node * node, Builtin builtin) [private]
Definition at line 9217 of file js-call-reducer.cc.
                                                                              {
  JSCallWithArrayLikeNode n(node);
  DCHECK_NE(n.Parameters().speculation_mode(),
            SpeculationMode::kDisallowSpeculation);
  DCHECK_EQ(n.ArgumentCount(), 1);
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceJSCallMathMinMaxWithArrayLike(builtin);
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), DCHECK_EQ, DCHECK_NE, v8::internal::kDisallowSpeculation, v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), ReplaceWithSubgraph(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by TryReduceJSCallMathMinMaxWithArrayLike().
ReduceJSCallWithArrayLike()
Reduction v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike (Node * node) [private]
Definition at line 5432 of file js-call-reducer.cc.
                                                             {
  JSCallWithArrayLikeNode n(node);
  CallParameters const& p = n.Parameters();
  DCHECK_EQ(p.arity_without_implicit_args(), 1); // The arraylike object.
  // Class constructors are callable, but [[Call]] will raise an exception.
  // See ES6 section 9.2.1 [[Call]] (thisArgument, argumentsList).
  if (TargetIsClassConstructor(node, broker())) {
    return NoChange();
  }
  std::optional<Reduction> maybe_result =
      TryReduceJSCallMathMinMaxWithArrayLike(node);
  if (maybe_result.has_value()) {
    return maybe_result.value();
  }
  return ReduceCallOrConstructWithArrayLikeOrSpread(
      node, n.ArgumentCount(), n.LastArgumentIndex(), p.frequency(),
      p.feedback(), p.speculation_mode(), p.feedback_relation(), n.target(),
      n.effect(), n.control());
}
References v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::CallParameters::arity_without_implicit_args(), broker(), v8::internal::compiler::JSNodeWrapperBase::control(), DCHECK_EQ, v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::JSCallOrConstructNode::LastArgumentIndex(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor(), and TryReduceJSCallMathMinMaxWithArrayLike().
Referenced by Reduce(), ReduceFunctionPrototypeApply(), and ReduceReflectApply().
ReduceJSCallWithSpread()
Reduction v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread (Node * node) [private]
Definition at line 5454 of file js-call-reducer.cc.
                                                          {
  JSCallWithSpreadNode n(node);
  CallParameters const& p = n.Parameters();
  DCHECK_GE(p.arity_without_implicit_args(), 1); // At least the spread.
  // Class constructors are callable, but [[Call]] will raise an exception.
  // See ES6 section 9.2.1 [[Call]] (thisArgument, argumentsList).
  if (TargetIsClassConstructor(node, broker())) {
    return NoChange();
  }
  return ReduceCallOrConstructWithArrayLikeOrSpread(
      node, n.ArgumentCount(), n.LastArgumentIndex(), p.frequency(),
      p.feedback(), p.speculation_mode(), p.feedback_relation(), n.target(),
      n.effect(), n.control());
}
References v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::CallParameters::arity_without_implicit_args(), broker(), v8::internal::compiler::JSNodeWrapperBase::control(), DCHECK_GE, v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::JSCallOrConstructNode::LastArgumentIndex(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor().
Referenced by Reduce().
ReduceJSConstruct()
Reduction v8::internal::compiler::JSCallReducer::ReduceJSConstruct (Node * node) [private]
Definition at line 5469 of file js-call-reducer.cc.
                                                     {
  if (broker()->StackHasOverflowed()) return NoChange();
  JSConstructNode n(node);
  ConstructParameters const& p = n.Parameters();
  int arity = p.arity_without_implicit_args();
  Node* target = n.target();
  Node* new_target = n.new_target();
  Effect effect = n.effect();
  Control control = n.control();
  if (p.feedback().IsValid()) {
    ProcessedFeedback const& feedback =
        broker()->GetFeedbackForCall(p.feedback());
    if (feedback.IsInsufficient()) {
      return ReduceForInsufficientFeedback(
          node, DeoptimizeReason::kInsufficientTypeFeedbackForConstruct);
    }
    OptionalHeapObjectRef feedback_target = feedback.AsCall().target();
    if (feedback_target.has_value() && feedback_target->IsAllocationSite()) {
      // The feedback is an AllocationSite, which means we have called the
      // Array function and collected transition (and pretenuring) feedback
      // for the resulting arrays. This has to be kept in sync with the
      // implementation in Ignition.
      Node* array_function = jsgraph()->ConstantNoHole(
          native_context().array_function(broker()), broker());
      // Check that the {target} is still the {array_function}.
      Node* check = graph()->NewNode(simplified()->ReferenceEqual(), target,
                                     array_function);
      effect = graph()->NewNode(
          simplified()->CheckIf(DeoptimizeReason::kWrongCallTarget), check,
          effect, control);
      // Turn the {node} into a {JSCreateArray} call.
      NodeProperties::ReplaceEffectInput(node, effect);
      static_assert(JSConstructNode::NewTargetIndex() == 1);
      node->ReplaceInput(n.NewTargetIndex(), array_function);
      node->RemoveInput(n.FeedbackVectorIndex());
      NodeProperties::ChangeOp(
          node,
          javascript()->CreateArray(arity, feedback_target->AsAllocationSite(),
                                    FeedbackSource()));
      return Changed(node);
    } else if (feedback_target.has_value() &&
               !HeapObjectMatcher(new_target).HasResolvedValue() &&
               feedback_target->map(broker()).is_constructor()) {
      Node* new_target_feedback =
          jsgraph()->ConstantNoHole(*feedback_target, broker());
      // Check that the {new_target} is still the {new_target_feedback}.
      Node* check = graph()->NewNode(simplified()->ReferenceEqual(), new_target,
                                     new_target_feedback);
      effect = graph()->NewNode(
          simplified()->CheckIf(DeoptimizeReason::kWrongCallTarget), check,
          effect, control);
      // Specialize the JSConstruct node to the {new_target_feedback}.
      node->ReplaceInput(n.NewTargetIndex(), new_target_feedback);
      NodeProperties::ReplaceEffectInput(node, effect);
      if (target == new_target) {
        node->ReplaceInput(n.TargetIndex(), new_target_feedback);
      }
      // Try to further reduce the JSConstruct {node}.
      return Changed(node).FollowedBy(ReduceJSConstruct(node));
    }
  }
  // Try to specialize JSConstruct {node}s with constant {target}s.
  HeapObjectMatcher m(target);
  if (m.HasResolvedValue()) {
    HeapObjectRef target_ref = m.Ref(broker());
    // Raise a TypeError if the {target} is not a constructor.
    if (!target_ref.map(broker()).is_constructor()) {
      NodeProperties::ReplaceValueInputs(node, target);
      NodeProperties::ChangeOp(node,
                               javascript()->CallRuntime(
                                   Runtime::kThrowConstructedNonConstructable));
      return Changed(node);
    }
    if (target_ref.IsJSFunction()) {
      JSFunctionRef function = target_ref.AsJSFunction();
      // Do not reduce constructors with break points.
      // If this state changes during background compilation, the compilation
      // job will be aborted from the main thread (see
      // Debug::PrepareFunctionForDebugExecution()).
      SharedFunctionInfoRef sfi = function.shared(broker());
      if (sfi.HasBreakInfo(broker())) return NoChange();
      // Don't inline cross native context.
      if (!function.native_context(broker()).equals(native_context())) {
        return NoChange();
      }
      // Check for known builtin functions.
      Builtin builtin =
          sfi.HasBuiltinId() ? sfi.builtin_id() : Builtin::kNoBuiltinId;
      switch (builtin) {
        case Builtin::kArrayConstructor: {
          // TODO(bmeurer): Deal with Array subclasses here.
          // Turn the {node} into a {JSCreateArray} call.
          static_assert(JSConstructNode::NewTargetIndex() == 1);
          node->ReplaceInput(n.NewTargetIndex(), new_target);
          node->RemoveInput(n.FeedbackVectorIndex());
          NodeProperties::ChangeOp(
              node,
              javascript()->CreateArray(arity, std::nullopt, FeedbackSource()));
          return Changed(node);
        }
        case Builtin::kObjectConstructor: {
          // If no value is passed, we can immediately lower to a simple
          // JSCreate and don't need to do any massaging of the {node}.
          if (arity == 0) {
            node->RemoveInput(n.FeedbackVectorIndex());
            NodeProperties::ChangeOp(node, javascript()->Create());
            return Changed(node);
          }
          // If {target} is not the same as {new_target} (i.e. the Object
          // constructor), {value} will be ignored and therefore we can lower
          // to {JSCreate}. See https://tc39.es/ecma262/#sec-object-value.
          HeapObjectMatcher mnew_target(new_target);
          if (mnew_target.HasResolvedValue() &&
              !mnew_target.Ref(broker()).equals(function)) {
            // Drop the value inputs.
            node->RemoveInput(n.FeedbackVectorIndex());
            for (int i = n.ArgumentCount() - 1; i >= 0; i--) {
              node->RemoveInput(n.ArgumentIndex(i));
            }
            NodeProperties::ChangeOp(node, javascript()->Create());
            return Changed(node);
          }
          break;
        }
        case Builtin::kPromiseConstructor:
          return ReducePromiseConstructor(node);
        case Builtin::kStringConstructor:
          return ReduceStringConstructor(node, function);
        case Builtin::kTypedArrayConstructor:
          return ReduceTypedArrayConstructor(node, function.shared(broker()));
        default:
          break;
      }
    } else if (target_ref.IsJSBoundFunction()) {
      JSBoundFunctionRef function = target_ref.AsJSBoundFunction();
      JSReceiverRef bound_target_function =
          function.bound_target_function(broker());
      FixedArrayRef bound_arguments = function.bound_arguments(broker());
      const uint32_t bound_arguments_length = bound_arguments.length();
      // TODO(jgruber): Inline this block below once TryGet is guaranteed to
      // succeed.
      static constexpr int kInlineSize = 16; // Arbitrary.
      base::SmallVector<Node*, kInlineSize> args;
      for (uint32_t i = 0; i < bound_arguments_length; ++i) {
        OptionalObjectRef maybe_arg = bound_arguments.TryGet(broker(), i);
        if (!maybe_arg.has_value()) {
          TRACE_BROKER_MISSING(broker(), "bound argument");
          return NoChange();
        }
        args.emplace_back(
            jsgraph()->ConstantNoHole(maybe_arg.value(), broker()));
      }
      // Patch {node} to use [[BoundTargetFunction]].
      node->ReplaceInput(n.TargetIndex(), jsgraph()->ConstantNoHole(
                                              bound_target_function, broker()));
      // Patch {node} to use [[BoundTargetFunction]]
      // as new.target if {new_target} equals {target}.
      if (target == new_target) {
        node->ReplaceInput(
            n.NewTargetIndex(),
            jsgraph()->ConstantNoHole(bound_target_function, broker()));
      } else {
        node->ReplaceInput(
            n.NewTargetIndex(),
            graph()->NewNode(
                common()->Select(MachineRepresentation::kTagged),
                graph()->NewNode(simplified()->ReferenceEqual(), target,
                                 new_target),
                jsgraph()->ConstantNoHole(bound_target_function, broker()),
                new_target));
      }
      // Insert the [[BoundArguments]] for {node}.
      for (uint32_t i = 0; i < bound_arguments_length; ++i) {
        node->InsertInput(graph()->zone(), n.ArgumentIndex(i), args[i]);
        arity++;
      }
      // Update the JSConstruct operator on {node}.
      NodeProperties::ChangeOp(
          node, javascript()->Construct(JSConstructNode::ArityForArgc(arity),
                                        p.frequency(), FeedbackSource()));
      // Try to further reduce the JSConstruct {node}.
      return Changed(node).FollowedBy(ReduceJSConstruct(node));
    }
    // TODO(bmeurer): Also support optimizing proxies here.
  }
  // If {target} is the result of a JSCreateBoundFunction operation,
  // we can just fold the construction and construct the bound target
  // function directly instead.
  if (target->opcode() == IrOpcode::kJSCreateBoundFunction) {
    Node* bound_target_function = NodeProperties::GetValueInput(target, 0);
    uint32_t const bound_arguments_length =
        static_cast<int>(CreateBoundFunctionParametersOf(target->op()).arity());
    // Patch the {node} to use [[BoundTargetFunction]].
    node->ReplaceInput(n.TargetIndex(), bound_target_function);
    // Patch {node} to use [[BoundTargetFunction]]
    // as new.target if {new_target} equals {target}.
    if (target == new_target) {
      node->ReplaceInput(n.NewTargetIndex(), bound_target_function);
    } else {
      node->ReplaceInput(
          n.NewTargetIndex(),
          graph()->NewNode(common()->Select(MachineRepresentation::kTagged),
                           graph()->NewNode(simplified()->ReferenceEqual(),
                                            target, new_target),
                           bound_target_function, new_target));
    }
    // Insert the [[BoundArguments]] for {node}.
    for (uint32_t i = 0; i < bound_arguments_length; ++i) {
      Node* value = NodeProperties::GetValueInput(target, 2 + i);
      node->InsertInput(graph()->zone(), n.ArgumentIndex(i), value);
      arity++;
    }
    // Update the JSConstruct operator on {node}.
    NodeProperties::ChangeOp(
        node, javascript()->Construct(JSConstructNode::ArityForArgc(arity),
                                      p.frequency(), FeedbackSource()));
    // Try to further reduce the JSConstruct {node}.
    return Changed(node).FollowedBy(ReduceJSConstruct(node));
  }
  return NoChange();
}
References v8::base::args, v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount(), v8::internal::compiler::JSCallOrConstructNode::ArgumentIndex(), v8::internal::compiler::CreateBoundFunctionParameters::arity(), v8::internal::compiler::ConstructParameters::arity_without_implicit_args(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::compiler::CreateBoundFunctionParametersOf(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::ConstructParameters::feedback(), v8::internal::compiler::JSCallOrConstructNode::FeedbackVectorIndex(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::ConstructParameters::frequency(), v8::internal::compiler::JSHeapBroker::GetFeedbackForCall(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::SharedFunctionInfoRef::HasBreakInfo(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InsertInput(), v8::internal::is_constructor, v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::FeedbackSource::IsValid(), javascript(), jsgraph(), v8::internal::kNoBuiltinId, v8::internal::kTagged, v8::internal::compiler::FixedArrayBaseRef::length(), v8::internal::compiler::HeapObjectRef::map(), native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters(), ReduceForInsufficientFeedback(), ReducePromiseConstructor(), ReduceStringConstructor(), ReduceTypedArrayConstructor(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), simplified(), v8::internal::compiler::CallFeedback::target(), TRACE_BROKER_MISSING, v8::internal::compiler::FixedArrayRef::TryGet(), and v8::internal::value.
Referenced by Reduce(), ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), and ReduceJSConstructForwardAllArgs().
ReduceJSConstructForwardAllArgs()
Reduction v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs (Node * node) [private]
Definition at line 5932 of file js-call-reducer.cc.
                                                                   {
  JSConstructForwardAllArgsNode n(node);
  DCHECK_EQ(n.ArgumentCount(), 0);
  // If this frame is not being inlined, JSConstructForwardAllArgs will be
  // lowered later in JSGenericLowering to a builtin call.
  FrameState frame_state = n.frame_state();
  if (frame_state.outer_frame_state()->opcode() != IrOpcode::kFrameState) {
    return NoChange();
  }
  // Hook up the arguments directly when forwarding arguments of inlined frames.
  FrameState outer_state{frame_state.outer_frame_state()};
  FrameStateInfo outer_info = outer_state.frame_state_info();
  if (outer_info.type() == FrameStateType::kInlinedExtraArguments) {
    frame_state = outer_state;
  }
  int argc = 0;
  StateValuesAccess parameters_access(frame_state.parameters());
  for (auto it = parameters_access.begin_without_receiver(); !it.done(); ++it) {
    DCHECK_NOT_NULL(it.node());
    node->InsertInput(graph()->zone(),
                      JSCallOrConstructNode::ArgumentIndex(argc++), it.node());
  }
  ConstructParameters const& p = n.Parameters();
  NodeProperties::ChangeOp(
      node, javascript()->Construct(JSConstructNode::ArityForArgc(argc),
                                    p.frequency(), p.feedback()));
  CheckIfConstructor(node);
  return Changed(node).FollowedBy(ReduceJSConstruct(node));
}
References v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount(), v8::internal::compiler::JSCallOrConstructNode::ArgumentIndex(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::StateValuesAccess::begin_without_receiver(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), CheckIfConstructor(), v8::internal::anonymous_namespace{js-locale.cc}::Construct(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::compiler::StateValuesAccess::iterator::done(), v8::internal::compiler::ConstructParameters::feedback(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::ConstructParameters::frequency(), graph(), v8::internal::compiler::Node::InsertInput(), javascript(), v8::internal::compiler::kInlinedExtraArguments, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::FrameState::outer_frame_state(), v8::internal::compiler::FrameState::parameters(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters(), ReduceJSConstruct(), and v8::internal::compiler::FrameStateInfo::type().
Referenced by Reduce().
ReduceJSConstructWithArrayLike()
Reduction v8::internal::compiler::JSCallReducer::ReduceJSConstructWithArrayLike (Node * node) [private]
Definition at line 5910 of file js-call-reducer.cc.
                                                                  {
  JSConstructWithArrayLikeNode n(node);
  ConstructParameters const& p = n.Parameters();
  const int arraylike_index = n.LastArgumentIndex();
  DCHECK_EQ(n.ArgumentCount(), 1); // The arraylike object.
  return ReduceCallOrConstructWithArrayLikeOrSpread(
      node, n.ArgumentCount(), arraylike_index, p.frequency(), p.feedback(),
      SpeculationMode::kDisallowSpeculation, CallFeedbackRelation::kTarget,
      n.target(), n.effect(), n.control());
}
References v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount(), v8::internal::compiler::JSNodeWrapperBase::control(), DCHECK_EQ, v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::ConstructParameters::feedback(), v8::internal::compiler::ConstructParameters::frequency(), v8::internal::kDisallowSpeculation, v8::internal::compiler::kTarget, v8::internal::compiler::JSCallOrConstructNode::LastArgumentIndex(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters(), and ReduceCallOrConstructWithArrayLikeOrSpread().
Referenced by Reduce(), and ReduceReflectConstruct().
ReduceJSConstructWithSpread()
Reduction v8::internal::compiler::JSCallReducer::ReduceJSConstructWithSpread (Node * node) [private]
Definition at line 5921 of file js-call-reducer.cc.
                                                               {
  JSConstructWithSpreadNode n(node);
  ConstructParameters const& p = n.Parameters();
  const int spread_index = n.LastArgumentIndex();
  DCHECK_GE(n.ArgumentCount(), 1); // At least the spread.
  return ReduceCallOrConstructWithArrayLikeOrSpread(
      node, n.ArgumentCount(), spread_index, p.frequency(), p.feedback(),
      SpeculationMode::kDisallowSpeculation, CallFeedbackRelation::kTarget,
      n.target(), n.effect(), n.control());
}
References v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount(), v8::internal::compiler::JSNodeWrapperBase::control(), DCHECK_GE, v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::ConstructParameters::feedback(), v8::internal::compiler::ConstructParameters::frequency(), v8::internal::kDisallowSpeculation, v8::internal::compiler::kTarget, v8::internal::compiler::JSCallOrConstructNode::LastArgumentIndex(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters(), and ReduceCallOrConstructWithArrayLikeOrSpread().
Referenced by Reduce().
ReduceMapPrototypeGet()
Reduction v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet (Node * node) [private]
Definition at line 8093 of file js-call-reducer.cc.
                                                         {
  // We only optimize if we have target, receiver and key parameters.
  JSCallNode n(node);
  if (n.ArgumentCount() != 1) return NoChange();
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  Node* key = NodeProperties::GetValueInput(node, 2);
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() || !inference.AllOfInstanceTypesAre(JS_MAP_TYPE)) {
    return NoChange();
  }
  Node* table = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSCollectionTable()), receiver,
      effect, control);
  Node* entry = effect = graph()->NewNode(
      simplified()->FindOrderedCollectionEntry(CollectionKind::kMap), table,
      key, effect, control);
  Node* check = graph()->NewNode(simplified()->NumberEqual(), entry,
                                 jsgraph()->MinusOneConstant());
  Node* branch = graph()->NewNode(common()->Branch(), check, control);
  // Key not found.
  Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
  Node* etrue = effect;
  Node* vtrue = jsgraph()->UndefinedConstant();
  // Key found.
  Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
  Node* efalse = effect;
  Node* vfalse = efalse = graph()->NewNode(
      simplified()->LoadElement(AccessBuilder::ForOrderedHashMapEntryValue()),
      table, entry, efalse, if_false);
  control = graph()->NewNode(common()->Merge(2), if_true, if_false);
  Node* value = graph()->NewNode(
      common()->Phi(MachineRepresentation::kTagged, 2), vtrue, vfalse, control);
  effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), broker(), common(), v8::internal::compiler::AccessBuilder::ForJSCollectionTable(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapEntryValue(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MapInference::HaveMaps(), jsgraph(), v8::internal::key, v8::internal::kMap, v8::internal::kTagged, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceMapPrototypeHas()
Reduction v8::internal::compiler::JSCallReducer::ReduceMapPrototypeHas (Node * node) [private]
Definition at line 8188 of file js-call-reducer.cc.
                                                         {
  return ReduceCollectionPrototypeHas(node, CollectionKind::kMap);
}
References v8::internal::kMap, and ReduceCollectionPrototypeHas().
Referenced by ReduceJSCall().
ReduceMathBinary()
Reduction v8::internal::compiler::JSCallReducer::ReduceMathBinary (Node * node, const Operator * op) [private]
Definition at line 2659 of file js-call-reducer.cc.
                                                                        {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->NaNConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceMathBinary(op);
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceMathBinary(), v8::internal::compiler::AdvancedReducer::Replace(), ReplaceWithSubgraph(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceMathClz32()
Reduction v8::internal::compiler::JSCallReducer::ReduceMathClz32 (Node * node) [private]
Definition at line 2709 of file js-call-reducer.cc.
                                                   {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->ConstantNoHole(32);
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Node* input = n.Argument(0);
  Effect effect = n.effect();
  Control control = n.control();
  input = effect =
      graph()->NewNode(simplified()->SpeculativeToNumber(
                           NumberOperationHint::kNumberOrOddball, p.feedback()),
                       input, effect, control);
  input = graph()->NewNode(simplified()->NumberToUint32(), input);
  Node* value = graph()->NewNode(simplified()->NumberClz32(), input);
  ReplaceWithValue(node, value, effect);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::NumberToUint32(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceMathImul()
Reduction v8::internal::compiler::JSCallReducer::ReduceMathImul (Node * node) [private]
Definition at line 2677 of file js-call-reducer.cc.
                                                  {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->ZeroConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Node* left = n.Argument(0);
  Node* right = n.ArgumentOr(1, jsgraph()->ZeroConstant());
  Effect effect = n.effect();
  Control control = n.control();
  left = effect =
      graph()->NewNode(simplified()->SpeculativeToNumber(
                           NumberOperationHint::kNumberOrOddball, p.feedback()),
                       left, effect, control);
  right = effect =
      graph()->NewNode(simplified()->SpeculativeToNumber(
                           NumberOperationHint::kNumberOrOddball, p.feedback()),
                       right, effect, control);
  left = graph()->NewNode(simplified()->NumberToUint32(), left);
  right = graph()->NewNode(simplified()->NumberToUint32(), right);
  Node* value = graph()->NewNode(simplified()->NumberImul(), left, right);
  ReplaceWithValue(node, value, effect);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOr(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::NumberToUint32(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceMathMinMax()
Reduction v8::internal::compiler::JSCallReducer::ReduceMathMinMax (Node * node, const Operator * op, Node * empty_value) [private]
Definition at line 2736 of file js-call-reducer.cc.
                                                             {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() < 1) {
    ReplaceWithValue(node, empty_value);
    return Replace(empty_value);
  }
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* value = effect =
      graph()->NewNode(simplified()->SpeculativeToNumber(
                           NumberOperationHint::kNumberOrOddball, p.feedback()),
                       n.Argument(0), effect, control);
  for (int i = 1; i < n.ArgumentCount(); i++) {
    Node* input = effect = graph()->NewNode(
        simplified()->SpeculativeToNumber(NumberOperationHint::kNumberOrOddball,
                                          p.feedback()),
        n.Argument(i), effect, control);
    value = graph()->NewNode(op, value, input);
  }
  ReplaceWithValue(node, value, effect);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::kAllowSpeculation, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceMathUnary()
Reduction v8::internal::compiler::JSCallReducer::ReduceMathUnary (Node * node, const Operator * op) [private]
Definition at line 2642 of file js-call-reducer.cc.
                                                                       {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->NaNConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceMathUnary(op);
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceMathUnary(), v8::internal::compiler::AdvancedReducer::Replace(), ReplaceWithSubgraph(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceNumberConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReduceNumberConstructor (Node * node) [private]
Definition at line 9035 of file js-call-reducer.cc.
                                                           {
  JSCallNode n(node);
  Node* target = n.target();
  Node* receiver = n.receiver();
  Node* value = n.ArgumentOr(0, jsgraph()->ZeroConstant());
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  // Create the artificial frame state in the middle of the Number constructor.
  SharedFunctionInfoRef shared_info =
      native_context().number_function(broker()).shared(broker());
  Node* continuation_frame_state = CreateGenericLazyDeoptContinuationFrameState(
      jsgraph(), shared_info, target, context, receiver, frame_state);
  // Convert the {value} to a Number.
  NodeProperties::ReplaceValueInputs(node, value);
  NodeProperties::ChangeOp(node, javascript()->ToNumberConvertBigInt());
  NodeProperties::ReplaceFrameStateInput(node, continuation_frame_state);
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOr(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::CreateGenericLazyDeoptContinuationFrameState(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), javascript(), jsgraph(), native_context(), v8::internal::compiler::NodeProperties::ReplaceFrameStateInput(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceNumberIsFinite()
Reduction v8::internal::compiler::JSCallReducer::ReduceNumberIsFinite (Node * node) [private]
Definition at line 8038 of file js-call-reducer.cc.
                                                        {
  JSCallNode n(node);
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Node* input = n.Argument(0);
  Node* value = graph()->NewNode(simplified()->ObjectIsFiniteNumber(), input);
  ReplaceWithValue(node, value);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceNumberIsInteger()
Reduction v8::internal::compiler::JSCallReducer::ReduceNumberIsInteger (Node * node) [private]
Definition at line 8052 of file js-call-reducer.cc.
                                                         {
  JSCallNode n(node);
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Node* input = n.Argument(0);
  Node* value = graph()->NewNode(simplified()->ObjectIsInteger(), input);
  ReplaceWithValue(node, value);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceNumberIsNaN()
Reduction v8::internal::compiler::JSCallReducer::ReduceNumberIsNaN (Node * node) [private]
Definition at line 8080 of file js-call-reducer.cc.
                                                     {
  JSCallNode n(node);
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Node* input = n.Argument(0);
  Node* value = graph()->NewNode(simplified()->ObjectIsNaN(), input);
  ReplaceWithValue(node, value);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceNumberIsSafeInteger()
Reduction v8::internal::compiler::JSCallReducer::ReduceNumberIsSafeInteger (Node * node) [private]
Definition at line 8066 of file js-call-reducer.cc.
                                                             {
  JSCallNode n(node);
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Node* input = n.Argument(0);
  Node* value = graph()->NewNode(simplified()->ObjectIsSafeInteger(), input);
  ReplaceWithValue(node, value);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceNumberParseInt()
Reduction v8::internal::compiler::JSCallReducer::ReduceNumberParseInt (Node * node) [private]
Definition at line 8891 of file js-call-reducer.cc.
                                                        {
  JSCallNode n(node);
  if (n.ArgumentCount() < 1) {
    Node* value = jsgraph()->NaNConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Node* object = n.Argument(0);
  Node* radix = n.ArgumentOrUndefined(1, jsgraph());
  // Try constant-folding when input is a string constant.
  HeapObjectMatcher object_matcher(object);
  HeapObjectMatcher radix_object_matcher(radix);
  NumberMatcher radix_number_matcher(radix);
  if (object_matcher.HasResolvedValue() &&
      object_matcher.Ref(broker()).IsString() &&
      (radix_object_matcher.Is(factory()->undefined_value()) ||
       radix_number_matcher.HasResolvedValue())) {
    StringRef input_value = object_matcher.Ref(broker()).AsString();
    // {undefined} is treated same as 0.
    int radix_value = radix_object_matcher.Is(factory()->undefined_value())
                          ? 0
                          : DoubleToInt32(radix_number_matcher.ResolvedValue());
    if (radix_value != 0 && (radix_value < 2 || radix_value > 36)) {
      Node* value = jsgraph()->NaNConstant();
      ReplaceWithValue(node, value);
      return Replace(value);
    }
    std::optional<double> number = input_value.ToInt(broker(), radix_value);
    if (number.has_value()) {
      Node* result = graph()->NewNode(common()->NumberConstant(number.value()));
      ReplaceWithValue(node, result);
      return Replace(result);
    }
  }
  node->ReplaceInput(0, object);
  node->ReplaceInput(1, radix);
  node->ReplaceInput(2, context);
  node->ReplaceInput(3, frame_state);
  node->ReplaceInput(4, effect);
  node->ReplaceInput(5, control);
  node->TrimInputCount(6);
  NodeProperties::ChangeOp(node, javascript()->ParseInt());
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::DoubleToInt32(), v8::internal::compiler::JSNodeWrapperBase::effect(), factory(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Is(), javascript(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NumberConstant(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::base::internal::result, v8::internal::compiler::StringRef::ToInt(), v8::internal::compiler::Node::TrimInputCount(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceObjectConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReduceObjectConstructor (Node * node) [private]
Definition at line 2839 of file js-call-reducer.cc.
                                                           {
  JSCallNode n(node);
  if (n.ArgumentCount() < 1) return NoChange();
  Node* value = n.Argument(0);
  Effect effect = n.effect();
  // We can fold away the Tagged<Object>(x) call if |x| is definitely not a
  // primitive.
  if (NodeProperties::CanBePrimitive(broker(), value, effect)) {
    if (!NodeProperties::CanBeNullOrUndefined(broker(), value, effect)) {
      // Turn the {node} into a {JSToObject} call if we know that
      // the {value} cannot be null or undefined.
      NodeProperties::ReplaceValueInputs(node, value);
      NodeProperties::ChangeOp(node, javascript()->ToObject());
      return Changed(node);
    }
  } else {
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  return NoChange();
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), broker(), v8::internal::compiler::NodeProperties::CanBeNullOrUndefined(), v8::internal::compiler::NodeProperties::CanBePrimitive(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::effect(), javascript(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::anonymous_namespace{api.cc}::ToObject(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceObjectCreate()
Reduction v8::internal::compiler::JSCallReducer::ReduceObjectCreate (Node * node) [private]
Definition at line 3485 of file js-call-reducer.cc.
                                                      {
  JSCallNode n(node);
  Node* properties = n.ArgumentOrUndefined(1, jsgraph());
  if (properties != jsgraph()->UndefinedConstant()) return NoChange();
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Effect effect = n.effect();
  Control control = n.control();
  Node* prototype = n.ArgumentOrUndefined(0, jsgraph());
  node->ReplaceInput(0, prototype);
  node->ReplaceInput(1, context);
  node->ReplaceInput(2, frame_state);
  node->ReplaceInput(3, effect);
  node->ReplaceInput(4, control);
  node->TrimInputCount(5);
  NodeProperties::ChangeOp(node, javascript()->CreateObject());
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), javascript(), jsgraph(), v8::internal::compiler::Reducer::NoChange(), v8::internal::prototype, v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::Node::TrimInputCount(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCall().
ReduceObjectGetPrototype()
Reduction v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype (Node * node, Node * object) [private]
Definition at line 3199 of file js-call-reducer.cc.
                                                                          {
  Effect effect{NodeProperties::GetEffectInput(node)};
  // Try to determine the {object} map.
  MapInference inference(broker(), object, effect);
  if (!inference.HaveMaps()) return NoChange();
  ZoneRefSet<Map> const& object_maps = inference.GetMaps();
  MapRef candidate_map = object_maps[0];
  HeapObjectRef candidate_prototype = candidate_map.prototype(broker());
  // Check if we can constant-fold the {candidate_prototype}.
  for (size_t i = 0; i < object_maps.size(); ++i) {
    MapRef object_map = object_maps[i];
    HeapObjectRef map_prototype = object_map.prototype(broker());
    if (IsSpecialReceiverInstanceType(object_map.instance_type()) ||
        !map_prototype.equals(candidate_prototype)) {
      // We exclude special receivers, like JSProxy or API objects that
      // might require access checks here; we also don't want to deal
      // with hidden prototypes at this point.
      return inference.NoChange();
    }
    // The above check also excludes maps for primitive values, which is
    // important because we are not applying [[ToObject]] here as expected.
    DCHECK(!object_map.IsPrimitiveMap() && object_map.IsJSReceiverMap());
  }
  if (!inference.RelyOnMapsViaStability(dependencies())) {
    return inference.NoChange();
  }
  Node* value = jsgraph()->ConstantNoHole(candidate_prototype, broker());
  ReplaceWithValue(node, value);
  return Replace(value);
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), dependencies(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::IsPrimitiveMap(), v8::internal::IsSpecialReceiverInstanceType(), jsgraph(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::MapRef::prototype(), v8::internal::compiler::MapInference::RelyOnMapsViaStability(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::ZoneCompactSet< T >::size(), and v8::internal::value.
Referenced by ReduceObjectGetPrototypeOf(), ReduceObjectPrototypeGetProto(), and ReduceReflectGetPrototypeOf().
ReduceObjectGetPrototypeOf()
Reduction v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototypeOf (Node * node) [private]
Definition at line 3234 of file js-call-reducer.cc.
                                                              {
  JSCallNode n(node);
  Node* object = n.ArgumentOrUndefined(0, jsgraph());
  return ReduceObjectGetPrototype(node, object);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), jsgraph(), and ReduceObjectGetPrototype().
Referenced by ReduceJSCall().
ReduceObjectIs()
Reduction v8::internal::compiler::JSCallReducer::ReduceObjectIs (Node * node) [private]
Definition at line 3241 of file js-call-reducer.cc.
                                                  {
  JSCallNode n(node);
  Node* lhs = n.ArgumentOrUndefined(0, jsgraph());
  Node* rhs = n.ArgumentOrUndefined(1, jsgraph());
  Node* value = graph()->NewNode(simplified()->SameValue(), lhs, rhs);
  ReplaceWithValue(node, value);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::SameValue(), simplified(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceObjectPrototypeGetProto()
Reduction v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeGetProto (Node * node) [private]
Definition at line 3251 of file js-call-reducer.cc.
                                                                 {
  JSCallNode n(node);
  return ReduceObjectGetPrototype(node, n.receiver());
}
References ReduceObjectGetPrototype().
Referenced by ReduceJSCall().
ReduceObjectPrototypeHasOwnProperty()
Reduction v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty (Node * node) [private]
Definition at line 3257 of file js-call-reducer.cc.
                                                                       {
  JSCallNode call_node(node);
  Node* receiver = call_node.receiver();
  Node* name = call_node.ArgumentOrUndefined(0, jsgraph());
  Effect effect = call_node.effect();
  Control control = call_node.control();
  // We can optimize a call to Object.prototype.hasOwnProperty if it's being
  // used inside a fast-mode for..in, so for code like this:
  //
  // for (name in receiver) {
  // if (receiver.hasOwnProperty(name)) {
  // ...
  // }
  // }
  //
  // If the for..in is in fast-mode, we know that the {receiver} has {name}
  // as own property, otherwise the enumeration wouldn't include it. The graph
  // constructed by the BytecodeGraphBuilder in this case looks like this:
  // receiver
  // ^ ^
  // | |
  // | +-+
  // | |
  // | JSToObject
  // | ^
  // | |
  // | JSForInNext
  // | ^
  // +----+ |
  // | |
  // JSCall[hasOwnProperty]
  // We can constant-fold the {node} to True in this case, and insert
  // a (potentially redundant) map check to guard the fact that the
  // {receiver} map didn't change since the dominating JSForInNext. This
  // map check is only necessary when TurboFan cannot prove that there
  // is no observable side effect between the {JSForInNext} and the
  // {JSCall} to Object.prototype.hasOwnProperty.
  //
  // Also note that it's safe to look through the {JSToObject}, since the
  // Object.prototype.hasOwnProperty does an implicit ToObject anyway, and
  // these operations are not observable.
  if (name->opcode() == IrOpcode::kJSForInNext) {
    JSForInNextNode n(name);
    if (n.Parameters().mode() != ForInMode::kGeneric) {
      Node* object = n.receiver();
      Node* cache_type = n.cache_type();
      if (object->opcode() == IrOpcode::kJSToObject) {
        object = NodeProperties::GetValueInput(object, 0);
      }
      if (object == receiver) {
        // No need to repeat the map check if we can prove that there's no
        // observable side effect between {effect} and {name].
        if (!NodeProperties::NoObservableSideEffectBetween(effect, name)) {
          Node* receiver_map = effect =
              graph()->NewNode(simplified()->LoadField(AccessBuilder::ForMap()),
                               receiver, effect, control);
          Node* check = graph()->NewNode(simplified()->ReferenceEqual(),
                                         receiver_map, cache_type);
          effect = graph()->NewNode(
              simplified()->CheckIf(DeoptimizeReason::kWrongMap), check, effect,
              control);
        }
        Node* value = jsgraph()->TrueConstant();
        ReplaceWithValue(node, value, effect, control);
        return Replace(value);
      }
      // We can also optimize for this case below:
      // receiver(is a heap constant with fast map)
      // ^
      // | object(all keys are enumerable)
      // | ^
      // | |
      // | JSForInNext
      // | ^
      // +----+ |
      // | |
      // JSCall[hasOwnProperty]
      // We can replace the {JSCall} with several internalized string
      // comparisons.
      if (receiver->opcode() == IrOpcode::kHeapConstant) {
        MapInference inference(broker(), receiver, effect);
        if (!inference.HaveMaps()) {
          return inference.NoChange();
        }
        const ZoneRefSet<Map>& receiver_maps = inference.GetMaps();
        if (receiver_maps.size() == 1) {
          const MapRef receiver_map = *receiver_maps.begin();
          InstanceType instance_type = receiver_map.instance_type();
          int const nof = receiver_map.NumberOfOwnDescriptors();
          // We set a heuristic value to limit the compare instructions number.
          if (nof > 4 || instance_type <= LAST_SPECIAL_RECEIVER_TYPE ||
              receiver_map.is_dictionary_map()) {
            return inference.NoChange();
          }
          // Replace builtin call with several internalized string comparisons.
          CallParameters const& p = call_node.Parameters();
          inference.RelyOnMapsPreferStability(dependencies(), jsgraph(),
                                              &effect, control, p.feedback());
#define __ gasm.
          JSGraphAssembler gasm(broker(), jsgraph(), jsgraph()->zone(),
                                BranchSemantics::kJS);
          gasm.InitializeEffectControl(effect, control);
          auto done = __ MakeLabel(MachineRepresentation::kTagged);
          const DescriptorArrayRef descriptor_array =
              receiver_map.instance_descriptors(broker());
          for (InternalIndex key_index : InternalIndex::Range(nof)) {
            NameRef receiver_key =
                descriptor_array.GetPropertyKey(broker(), key_index);
            Node* lhs = jsgraph()->HeapConstantNoHole(receiver_key.object());
            __ GotoIf(__ ReferenceEqual(TNode<Object>::UncheckedCast(lhs),
                                        TNode<Object>::UncheckedCast(name)),
                      &done, __ TrueConstant());
          }
          __ Goto(&done, __ FalseConstant());
          __ Bind(&done);
          Node* value = done.PhiAt(0);
          ReplaceWithValue(node, value, gasm.effect(), gasm.control());
          return Replace(value);
#undef __
        }
        return inference.NoChange();
      }
    }
  }
  return NoChange();
}
References __, v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), v8::internal::ZoneCompactSet< T >::begin(), broker(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::DescriptorArrayRef::GetPropertyKey(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::MapRef::instance_descriptors(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::is_dictionary_map(), jsgraph(), v8::internal::compiler::kGeneric, v8::internal::compiler::kJS, v8::internal::kTagged, v8::internal::LAST_SPECIAL_RECEIVER_TYPE, v8::internal::compiler::ForInParameters::mode(), v8::internal::name, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::NodeProperties::NoObservableSideEffectBetween(), v8::internal::compiler::MapRef::NumberOfOwnDescriptors(), v8::internal::compiler::NameRef::object(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSForInNextNode::Parameters(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::ZoneCompactSet< T >::size(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceObjectPrototypeIsPrototypeOf()
Reduction v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf (Node * node) [private]
Definition at line 3394 of file js-call-reducer.cc.
                                                                      {
  JSCallNode n(node);
  Node* receiver = n.receiver();
  Node* value = n.ArgumentOrUndefined(0, jsgraph());
  Effect effect = n.effect();
  // Ensure that the {receiver} is known to be a JSReceiver (so that
  // the ToObject step of Object.prototype.isPrototypeOf is a no-op).
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() || !inference.AllOfInstanceTypesAreJSReceiver()) {
    return NoChange();
  }
  // We don't check whether {value} is a proper JSReceiver here explicitly,
  // and don't explicitly rule out Primitive {value}s, since all of them
  // have null as their prototype, so the prototype chain walk inside the
  // JSHasInPrototypeChain operator immediately aborts and yields false.
  NodeProperties::ReplaceValueInput(node, value, n.TargetIndex());
  for (int i = node->op()->ValueInputCount(); i > 2; i--) {
    node->RemoveInput(2);
  }
  NodeProperties::ChangeOp(node, javascript()->HasInPrototypeChain());
  return Changed(node);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAreJSReceiver(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::MapInference::HaveMaps(), javascript(), jsgraph(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::value, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by ReduceJSCall().
ReducePromiseConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReducePromiseConstructor (Node * node) [private]
Definition at line 7481 of file js-call-reducer.cc.
                                                            {
  PromiseBuiltinReducerAssembler a(this, node);
  // We only inline when we have the executor.
  if (a.ConstructArity() < 1) return NoChange();
  // Only handle builtins Promises, not subclasses.
  if (a.TargetInput() != a.NewTargetInput()) return NoChange();
  if (!dependencies()->DependOnPromiseHookProtector()) return NoChange();
  TNode<Object> subgraph = a.ReducePromiseConstructor(native_context());
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::PromiseBuiltinReducerAssembler::ConstructArity(), dependencies(), native_context(), v8::internal::compiler::PromiseBuiltinReducerAssembler::NewTargetInput(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), ReplaceWithSubgraph(), and v8::internal::compiler::PromiseBuiltinReducerAssembler::TargetInput().
Referenced by ReduceJSConstruct().
ReducePromiseInternalConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReducePromiseInternalConstructor (Node * node) [private]
ReducePromiseInternalReject()
Reduction v8::internal::compiler::JSCallReducer::ReducePromiseInternalReject (Node * node) [private]
ReducePromiseInternalResolve()
Reduction v8::internal::compiler::JSCallReducer::ReducePromiseInternalResolve (Node * node) [private]
ReducePromisePrototypeCatch()
Reduction v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch (Node * node) [private]
Definition at line 7512 of file js-call-reducer.cc.
                                                               {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  int arity = p.arity_without_implicit_args();
  Node* receiver = n.receiver();
  Effect effect = n.effect();
  Control control = n.control();
  MapInference inference(broker(), receiver, effect);
  if (!DoPromiseChecks(&inference)) return inference.NoChange();
  if (!dependencies()->DependOnPromiseThenProtector()) {
    return inference.NoChange();
  }
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  // Massage the {node} to call "then" instead by first removing all inputs
  // following the onRejected parameter, and then filling up the parameters
  // to two inputs from the left with undefined.
  Node* target = jsgraph()->ConstantNoHole(
      native_context().promise_then(broker()), broker());
  NodeProperties::ReplaceValueInput(node, target, 0);
  NodeProperties::ReplaceEffectInput(node, effect);
  for (; arity > 1; --arity) node->RemoveInput(3);
  for (; arity < 2; ++arity) {
    node->InsertInput(graph()->zone(), 2, jsgraph()->UndefinedConstant());
  }
  NodeProperties::ChangeOp(
      node, javascript()->Call(
                JSCallNode::ArityForArgc(arity), p.frequency(), p.feedback(),
                ConvertReceiverMode::kNotNullOrUndefined, p.speculation_mode(),
                CallFeedbackRelation::kUnrelated));
  return Changed(node).FollowedBy(ReducePromisePrototypeThen(node));
}
References v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), DoPromiseChecks(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::CallParameters::frequency(), graph(), v8::internal::compiler::Node::InsertInput(), javascript(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::kNotNullOrUndefined, v8::internal::compiler::kUnrelated, native_context(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReducePromisePrototypeThen(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCall().
ReducePromisePrototypeFinally()
Reduction v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally (Node * node) [private]
Definition at line 7565 of file js-call-reducer.cc.
                                                                 {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  int arity = p.arity_without_implicit_args();
  Node* receiver = n.receiver();
  Node* on_finally = n.ArgumentOrUndefined(0, jsgraph());
  Effect effect = n.effect();
  Control control = n.control();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  MapInference inference(broker(), receiver, effect);
  if (!DoPromiseChecks(&inference)) return inference.NoChange();
  ZoneRefSet<Map> const& receiver_maps = inference.GetMaps();
  if (!dependencies()->DependOnPromiseHookProtector()) {
    return inference.NoChange();
  }
  if (!dependencies()->DependOnPromiseThenProtector()) {
    return inference.NoChange();
  }
  if (!dependencies()->DependOnPromiseSpeciesProtector()) {
    return inference.NoChange();
  }
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  // Check if {on_finally} is callable, and if so wrap it into appropriate
  // closures that perform the finalization.
  Node* check = graph()->NewNode(simplified()->ObjectIsCallable(), on_finally);
  Node* branch =
      graph()->NewNode(common()->Branch(BranchHint::kTrue), check, control);
  Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
  Node* etrue = effect;
  Node* catch_true;
  Node* then_true;
  {
    Node* context = jsgraph()->ConstantNoHole(native_context(), broker());
    Node* constructor = jsgraph()->ConstantNoHole(
        native_context().promise_function(broker()), broker());
    // Allocate shared context for the closures below.
    context = etrue = graph()->NewNode(
        javascript()->CreateFunctionContext(
            native_context().scope_info(broker()),
            int{PromiseBuiltins::kPromiseFinallyContextLength} -
                Context::MIN_CONTEXT_SLOTS,
            FUNCTION_SCOPE),
        context, etrue, if_true);
    etrue = graph()->NewNode(
        simplified()->StoreField(
            AccessBuilder::ForContextSlot(PromiseBuiltins::kOnFinallySlot)),
        context, on_finally, etrue, if_true);
    etrue = graph()->NewNode(
        simplified()->StoreField(
            AccessBuilder::ForContextSlot(PromiseBuiltins::kConstructorSlot)),
        context, constructor, etrue, if_true);
    // Allocate the closure for the reject case.
    SharedFunctionInfoRef promise_catch_finally =
        MakeRef(broker(), factory()->promise_catch_finally_shared_fun());
    catch_true = etrue = CreateClosureFromBuiltinSharedFunctionInfo(
        promise_catch_finally, context, etrue, if_true);
    // Allocate the closure for the fulfill case.
    SharedFunctionInfoRef promise_then_finally =
        MakeRef(broker(), factory()->promise_then_finally_shared_fun());
    then_true = etrue = CreateClosureFromBuiltinSharedFunctionInfo(
        promise_then_finally, context, etrue, if_true);
  }
  Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
  Node* efalse = effect;
  Node* catch_false = on_finally;
  Node* then_false = on_finally;
  control = graph()->NewNode(common()->Merge(2), if_true, if_false);
  effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
  Node* catch_finally =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                       catch_true, catch_false, control);
  Node* then_finally =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                       then_true, then_false, control);
  // At this point we definitely know that {receiver} has one of the
  // {receiver_maps}, so insert a MapGuard as a hint for the lowering
  // of the call to "then" below.
  {
    effect = graph()->NewNode(simplified()->MapGuard(receiver_maps), receiver,
                              effect, control);
  }
  // Massage the {node} to call "then" instead by first removing all inputs
  // following the onFinally parameter, and then replacing the only parameter
  // input with the {on_finally} value.
  Node* target = jsgraph()->ConstantNoHole(
      native_context().promise_then(broker()), broker());
  NodeProperties::ReplaceValueInput(node, target, n.TargetIndex());
  NodeProperties::ReplaceEffectInput(node, effect);
  NodeProperties::ReplaceControlInput(node, control);
  for (; arity > 2; --arity) node->RemoveInput(2);
  for (; arity < 2; ++arity) {
    node->InsertInput(graph()->zone(), 2, then_finally);
  }
  node->ReplaceInput(2, then_finally);
  node->ReplaceInput(3, catch_finally);
  NodeProperties::ChangeOp(
      node, javascript()->Call(
                JSCallNode::ArityForArgc(arity), p.frequency(), p.feedback(),
                ConvertReceiverMode::kNotNullOrUndefined, p.speculation_mode(),
                CallFeedbackRelation::kUnrelated));
  return Changed(node).FollowedBy(ReducePromisePrototypeThen(node));
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), CreateClosureFromBuiltinSharedFunctionInfo(), dependencies(), DoPromiseChecks(), v8::internal::compiler::JSNodeWrapperBase::effect(), factory(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::CallParameters::frequency(), v8::internal::FUNCTION_SCOPE, v8::internal::compiler::MapInference::GetMaps(), graph(), v8::internal::compiler::Node::InsertInput(), javascript(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::PromiseBuiltins::kConstructorSlot, v8::internal::kNotNullOrUndefined, v8::internal::PromiseBuiltins::kOnFinallySlot, v8::internal::PromiseBuiltins::kPromiseFinallyContextLength, v8::internal::kTagged, v8::internal::kTrue, v8::internal::compiler::kUnrelated, v8::internal::compiler::MakeRef(), v8::internal::Context::MIN_CONTEXT_SLOTS, native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReducePromisePrototypeThen(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), simplified(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReducePromisePrototypeThen()
Reduction v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen (Node * node) [private]
Definition at line 7682 of file js-call-reducer.cc.
                                                              {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Node* receiver = n.receiver();
  Node* on_fulfilled = n.ArgumentOrUndefined(0, jsgraph());
  Node* on_rejected = n.ArgumentOrUndefined(1, jsgraph());
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  FrameState frame_state = n.frame_state();
  MapInference inference(broker(), receiver, effect);
  if (!DoPromiseChecks(&inference)) return inference.NoChange();
  if (!dependencies()->DependOnPromiseHookProtector()) {
    return inference.NoChange();
  }
  if (!dependencies()->DependOnPromiseSpeciesProtector()) {
    return inference.NoChange();
  }
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  // Check that {on_fulfilled} is callable.
  on_fulfilled = graph()->NewNode(
      common()->Select(MachineRepresentation::kTagged, BranchHint::kTrue),
      graph()->NewNode(simplified()->ObjectIsCallable(), on_fulfilled),
      on_fulfilled, jsgraph()->UndefinedConstant());
  // Check that {on_rejected} is callable.
  on_rejected = graph()->NewNode(
      common()->Select(MachineRepresentation::kTagged, BranchHint::kTrue),
      graph()->NewNode(simplified()->ObjectIsCallable(), on_rejected),
      on_rejected, jsgraph()->UndefinedConstant());
  // Create the resulting JSPromise.
  Node* promise = effect =
      graph()->NewNode(javascript()->CreatePromise(), context, effect);
  // Chain {result} onto {receiver}.
  promise = effect = graph()->NewNode(
      javascript()->PerformPromiseThen(), receiver, on_fulfilled, on_rejected,
      promise, context, frame_state, effect, control);
  // At this point we know that {promise} is going to have the
  // initial Promise map, since even if {PerformPromiseThen}
  // above called into the host rejection tracker, the {promise}
  // doesn't escape to user JavaScript. So bake this information
  // into the graph such that subsequent passes can use the
  // information for further optimizations.
  MapRef promise_map =
      native_context().promise_function(broker()).initial_map(broker());
  effect =
      graph()->NewNode(simplified()->MapGuard(ZoneRefSet<Map>(promise_map)),
                       promise, effect, control);
  ReplaceWithValue(node, promise, effect, control);
  return Replace(promise);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), DoPromiseChecks(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), graph(), javascript(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::kTagged, v8::internal::kTrue, native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::PerformPromiseThen(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCall(), ReducePromisePrototypeCatch(), and ReducePromisePrototypeFinally().
ReducePromiseResolveTrampoline()
Reduction v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline (Node * node) [private]
Definition at line 7747 of file js-call-reducer.cc.
                                                                  {
  JSCallNode n(node);
  Node* receiver = n.receiver();
  Node* value = n.ArgumentOrUndefined(0, jsgraph());
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  FrameState frame_state = n.frame_state();
  // Only reduce when the receiver is guaranteed to be a JSReceiver.
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() || !inference.AllOfInstanceTypesAreJSReceiver()) {
    return NoChange();
  }
  // Morph the {node} into a JSPromiseResolve operation.
  node->ReplaceInput(0, receiver);
  node->ReplaceInput(1, value);
  node->ReplaceInput(2, context);
  node->ReplaceInput(3, frame_state);
  node->ReplaceInput(4, effect);
  node->ReplaceInput(5, control);
  node->TrimInputCount(6);
  NodeProperties::ChangeOp(node, javascript()->PromiseResolve());
  return Changed(node);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAreJSReceiver(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::MapInference::HaveMaps(), javascript(), jsgraph(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::Node::TrimInputCount(), and v8::internal::value.
Referenced by ReduceJSCall().
reducer_name()
const char* v8::internal::compiler::JSCallReducer::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 63 of file js-call-reducer.h.
{ return "JSCallReducer"; }
ReduceReflectApply()
Reduction v8::internal::compiler::JSCallReducer::ReduceReflectApply (Node * node) [private]
Definition at line 3420 of file js-call-reducer.cc.
                                                      {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  int arity = p.arity_without_implicit_args();
  // Massage value inputs appropriately.
  static_assert(n.ReceiverIndex() > n.TargetIndex());
  node->RemoveInput(n.ReceiverIndex());
  node->RemoveInput(n.TargetIndex());
  while (arity < 3) {
    node->InsertInput(graph()->zone(), arity++, jsgraph()->UndefinedConstant());
  }
  while (arity-- > 3) {
    node->RemoveInput(arity);
  }
  NodeProperties::ChangeOp(
      node, javascript()->CallWithArrayLike(p.frequency(), p.feedback(),
                                            p.speculation_mode(),
                                            CallFeedbackRelation::kUnrelated));
  return Changed(node).FollowedBy(ReduceJSCallWithArrayLike(node));
}
References v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::CallParameters::frequency(), graph(), v8::internal::compiler::Node::InsertInput(), javascript(), jsgraph(), v8::internal::compiler::kUnrelated, v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReduceJSCallWithArrayLike(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCall().
ReduceReflectConstruct()
Reduction v8::internal::compiler::JSCallReducer::ReduceReflectConstruct (Node * node) [private]
Definition at line 3442 of file js-call-reducer.cc.
                                                          {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  int arity = p.arity_without_implicit_args();
  // Massage value inputs appropriately.
  TNode<Object> arg_target = n.ArgumentOrUndefined(0, jsgraph());
  TNode<Object> arg_argument_list = n.ArgumentOrUndefined(1, jsgraph());
  TNode<Object> arg_new_target = n.ArgumentOr(2, arg_target);
  static_assert(n.ReceiverIndex() > n.TargetIndex());
  node->RemoveInput(n.ReceiverIndex());
  node->RemoveInput(n.TargetIndex());
  // TODO(jgruber): This pattern essentially ensures that we have the correct
  // number of inputs for a given argument count. Wrap it in a helper function.
  static_assert(JSConstructNode::FirstArgumentIndex() == 2);
  while (arity < 3) {
    node->InsertInput(graph()->zone(), arity++, jsgraph()->UndefinedConstant());
  }
  while (arity-- > 3) {
    node->RemoveInput(arity);
  }
  static_assert(JSConstructNode::TargetIndex() == 0);
  static_assert(JSConstructNode::NewTargetIndex() == 1);
  static_assert(JSConstructNode::kFeedbackVectorIsLastInput);
  node->ReplaceInput(JSConstructNode::TargetIndex(), arg_target);
  node->ReplaceInput(JSConstructNode::NewTargetIndex(), arg_new_target);
  node->ReplaceInput(JSConstructNode::ArgumentIndex(0), arg_argument_list);
  NodeProperties::ChangeOp(
      node, javascript()->ConstructWithArrayLike(p.frequency(), p.feedback()));
  return Changed(node).FollowedBy(ReduceJSConstructWithArrayLike(node));
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentIndex(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOr(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::JSCallOrConstructNode::FirstArgumentIndex(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::CallParameters::frequency(), graph(), v8::internal::compiler::Node::InsertInput(), javascript(), jsgraph(), v8::internal::compiler::JSCallOrConstructNode::kFeedbackVectorIsLastInput, v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReduceJSConstructWithArrayLike(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCall().
ReduceReflectGet()
Reduction v8::internal::compiler::JSCallReducer::ReduceReflectGet (Node * node) [private]
Definition at line 3506 of file js-call-reducer.cc.
                                                    {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  int arity = p.arity_without_implicit_args();
  if (arity != 2) return NoChange();
  Node* target = n.Argument(0);
  Node* key = n.Argument(1);
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Effect effect = n.effect();
  Control control = n.control();
  // Check whether {target} is a JSReceiver.
  Node* check = graph()->NewNode(simplified()->ObjectIsReceiver(), target);
  Node* branch =
      graph()->NewNode(common()->Branch(BranchHint::kTrue), check, control);
  // Throw an appropriate TypeError if the {target} is not a JSReceiver.
  Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
  Node* efalse = effect;
  {
    if_false = efalse = graph()->NewNode(
        javascript()->CallRuntime(Runtime::kThrowTypeError, 2),
        jsgraph()->ConstantNoHole(
            static_cast<int>(MessageTemplate::kCalledOnNonObject)),
        jsgraph()->HeapConstantNoHole(factory()->ReflectGet_string()), context,
        frame_state, efalse, if_false);
  }
  // Otherwise just use the existing GetPropertyStub.
  Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
  Node* etrue = effect;
  Node* vtrue;
  {
    Callable callable = Builtins::CallableFor(isolate(), Builtin::kGetProperty);
    auto call_descriptor = Linkage::GetStubCallDescriptor(
        graph()->zone(), callable.descriptor(),
        callable.descriptor().GetStackParameterCount(),
        CallDescriptor::kNeedsFrameState, Operator::kNoProperties);
    Node* stub_code = jsgraph()->HeapConstantNoHole(callable.code());
    vtrue = etrue = if_true =
        graph()->NewNode(common()->Call(call_descriptor), stub_code, target,
                         key, context, frame_state, etrue, if_true);
  }
  // Rewire potential exception edges.
  Node* on_exception = nullptr;
  if (NodeProperties::IsExceptionalCall(node, &on_exception)) {
    // Create appropriate {IfException} and {IfSuccess} nodes.
    Node* extrue = graph()->NewNode(common()->IfException(), etrue, if_true);
    if_true = graph()->NewNode(common()->IfSuccess(), if_true);
    Node* exfalse = graph()->NewNode(common()->IfException(), efalse, if_false);
    if_false = graph()->NewNode(common()->IfSuccess(), if_false);
    // Join the exception edges.
    Node* merge = graph()->NewNode(common()->Merge(2), extrue, exfalse);
    Node* ephi =
        graph()->NewNode(common()->EffectPhi(2), extrue, exfalse, merge);
    Node* phi =
        graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                         extrue, exfalse, merge);
    ReplaceWithValue(on_exception, phi, ephi, merge);
  }
  // Connect the throwing path to end.
  if_false = graph()->NewNode(common()->Throw(), efalse, if_false);
  MergeControlToEnd(graph(), common(), if_false);
  // Continue on the regular path.
  ReplaceWithValue(node, vtrue, etrue, if_true);
  return Changed(vtrue);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::Builtins::CallableFor(), v8::internal::compiler::Reducer::Changed(), v8::internal::Callable::code(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::Callable::descriptor(), v8::internal::compiler::JSNodeWrapperBase::effect(), factory(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), isolate(), javascript(), jsgraph(), v8::internal::key, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Operator::kNoProperties, v8::internal::kTagged, v8::internal::kTrue, v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), and simplified().
Referenced by ReduceJSCall().
ReduceReflectGetPrototypeOf()
Reduction v8::internal::compiler::JSCallReducer::ReduceReflectGetPrototypeOf (Node * node) [private]
Definition at line 3478 of file js-call-reducer.cc.
                                                               {
  JSCallNode n(node);
  Node* target = n.ArgumentOrUndefined(0, jsgraph());
  return ReduceObjectGetPrototype(node, target);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), jsgraph(), and ReduceObjectGetPrototype().
Referenced by ReduceJSCall().
ReduceReflectHas()
Reduction v8::internal::compiler::JSCallReducer::ReduceReflectHas (Node * node) [private]
Definition at line 3580 of file js-call-reducer.cc.
                                                    {
  JSCallNode n(node);
  Node* target = n.ArgumentOrUndefined(0, jsgraph());
  Node* key = n.ArgumentOrUndefined(1, jsgraph());
  Node* context = n.context();
  Effect effect = n.effect();
  Control control = n.control();
  FrameState frame_state = n.frame_state();
  // Check whether {target} is a JSReceiver.
  Node* check = graph()->NewNode(simplified()->ObjectIsReceiver(), target);
  Node* branch =
      graph()->NewNode(common()->Branch(BranchHint::kTrue), check, control);
  // Throw an appropriate TypeError if the {target} is not a JSReceiver.
  Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
  Node* efalse = effect;
  {
    if_false = efalse = graph()->NewNode(
        javascript()->CallRuntime(Runtime::kThrowTypeError, 2),
        jsgraph()->ConstantNoHole(
            static_cast<int>(MessageTemplate::kCalledOnNonObject)),
        jsgraph()->HeapConstantNoHole(factory()->ReflectHas_string()), context,
        frame_state, efalse, if_false);
  }
  // Otherwise just use the existing {JSHasProperty} logic.
  Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
  Node* etrue = effect;
  Node* vtrue;
  {
    // TODO(magardn): collect feedback so this can be optimized
    vtrue = etrue = if_true = graph()->NewNode(
        javascript()->HasProperty(FeedbackSource()), target, key,
        jsgraph()->UndefinedConstant(), context, frame_state, etrue, if_true);
  }
  // Rewire potential exception edges.
  Node* on_exception = nullptr;
  if (NodeProperties::IsExceptionalCall(node, &on_exception)) {
    // Create appropriate {IfException} and {IfSuccess} nodes.
    Node* extrue = graph()->NewNode(common()->IfException(), etrue, if_true);
    if_true = graph()->NewNode(common()->IfSuccess(), if_true);
    Node* exfalse = graph()->NewNode(common()->IfException(), efalse, if_false);
    if_false = graph()->NewNode(common()->IfSuccess(), if_false);
    // Join the exception edges.
    Node* merge = graph()->NewNode(common()->Merge(2), extrue, exfalse);
    Node* ephi =
        graph()->NewNode(common()->EffectPhi(2), extrue, exfalse, merge);
    Node* phi =
        graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                         extrue, exfalse, merge);
    ReplaceWithValue(on_exception, phi, ephi, merge);
  }
  // Connect the throwing path to end.
  if_false = graph()->NewNode(common()->Throw(), efalse, if_false);
  MergeControlToEnd(graph(), common(), if_false);
  // Continue on the regular path.
  ReplaceWithValue(node, vtrue, etrue, if_true);
  return Changed(vtrue);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), v8::internal::compiler::Reducer::Changed(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), factory(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), javascript(), jsgraph(), v8::internal::key, v8::internal::kTagged, v8::internal::kTrue, v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCall().
ReduceRegExpPrototypeTest()
Reduction v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest (Node * node) [private]
Definition at line 8944 of file js-call-reducer.cc.
                                                             {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (v8_flags.force_slow_path) return NoChange();
  if (n.ArgumentCount() < 1) return NoChange();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* regexp = n.receiver();
  // Only the initial JSRegExp map is valid here, since the following lastIndex
  // check as well as the lowered builtin call rely on a known location of the
  // lastIndex field.
  MapRef regexp_initial_map =
      native_context().regexp_function(broker()).initial_map(broker());
  MapInference inference(broker(), regexp, effect);
  if (!inference.Is(regexp_initial_map)) return inference.NoChange();
  ZoneRefSet<Map> const& regexp_maps = inference.GetMaps();
  ZoneVector<PropertyAccessInfo> access_infos(graph()->zone());
  AccessInfoFactory access_info_factory(broker(), graph()->zone());
  for (MapRef map : regexp_maps) {
    access_infos.push_back(broker()->GetPropertyAccessInfo(
        map, broker()->exec_string(), AccessMode::kLoad));
  }
  PropertyAccessInfo ai_exec =
      access_info_factory.FinalizePropertyAccessInfosAsOne(access_infos,
                                                           AccessMode::kLoad);
  if (ai_exec.IsInvalid()) return inference.NoChange();
  if (!ai_exec.IsFastDataConstant()) return inference.NoChange();
  // Do not reduce if the exec method is not on the prototype chain.
  OptionalJSObjectRef holder = ai_exec.holder();
  if (!holder.has_value()) return inference.NoChange();
  // Bail out if the exec method is not the original one.
  if (ai_exec.field_representation().IsDouble()) return inference.NoChange();
  OptionalObjectRef constant = holder->GetOwnFastConstantDataProperty(
      broker(), ai_exec.field_representation(), ai_exec.field_index(),
      dependencies());
  if (!constant.has_value() ||
      !constant->equals(native_context().regexp_exec_function(broker()))) {
    return inference.NoChange();
  }
  // Add proper dependencies on the {regexp}s [[Prototype]]s.
  dependencies()->DependOnStablePrototypeChains(
      ai_exec.lookup_start_object_maps(), kStartAtPrototype, holder.value());
  inference.RelyOnMapsPreferStability(dependencies(), jsgraph(), &effect,
                                      control, p.feedback());
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Node* search = n.Argument(0);
  Node* search_string = effect = graph()->NewNode(
      simplified()->CheckString(p.feedback()), search, effect, control);
  Node* lastIndex = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSRegExpLastIndex()), regexp,
      effect, control);
  Node* lastIndexSmi = effect = graph()->NewNode(
      simplified()->CheckSmi(p.feedback()), lastIndex, effect, control);
  Node* is_positive = graph()->NewNode(simplified()->NumberLessThanOrEqual(),
                                       jsgraph()->ZeroConstant(), lastIndexSmi);
  effect = graph()->NewNode(
      simplified()->CheckIf(DeoptimizeReason::kNotASmi, p.feedback()),
      is_positive, effect, control);
  node->ReplaceInput(0, regexp);
  node->ReplaceInput(1, search_string);
  node->ReplaceInput(2, context);
  node->ReplaceInput(3, frame_state);
  node->ReplaceInput(4, effect);
  node->ReplaceInput(5, control);
  node->TrimInputCount(6);
  NodeProperties::ChangeOp(node, javascript()->RegExpTest());
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChains(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_representation(), v8::internal::compiler::AccessInfoFactory::FinalizePropertyAccessInfosAsOne(), v8::internal::compiler::AccessBuilder::ForJSRegExpLastIndex(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::MapInference::GetMaps(), graph(), v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::compiler::MapInference::Is(), v8::internal::Representation::IsDouble(), v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant(), v8::internal::compiler::PropertyAccessInfo::IsInvalid(), javascript(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::kLoad, v8::internal::kStartAtPrototype, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::MapInference::RelyOnMapsPreferStability(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::anonymous_namespace{simd.cc}::search(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::compiler::Node::TrimInputCount(), and v8::internal::v8_flags.
Referenced by ReduceJSCall().
ReduceReturnReceiver()
Reduction v8::internal::compiler::JSCallReducer::ReduceReturnReceiver (Node * node) [private]
Definition at line 5966 of file js-call-reducer.cc.
                                                        {
  JSCallNode n(node);
  Node* receiver = n.receiver();
  ReplaceWithValue(node, receiver);
  return Replace(receiver);
}
References v8::internal::compiler::AdvancedReducer::Replace(), and v8::internal::compiler::AdvancedReducer::ReplaceWithValue().
Referenced by ReduceJSCall().
ReduceSetPrototypeHas()
Reduction v8::internal::compiler::JSCallReducer::ReduceSetPrototypeHas (Node * node) [private]
Definition at line 8192 of file js-call-reducer.cc.
                                                         {
  return ReduceCollectionPrototypeHas(node, CollectionKind::kSet);
}
References v8::internal::kSet, and ReduceCollectionPrototypeHas().
Referenced by ReduceJSCall().
ReduceStringConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringConstructor (Node * node, JSFunctionRef constructor) [private]
Definition at line 7415 of file js-call-reducer.cc.
                                                                            {
  JSConstructNode n(node);
  if (n.target() != n.new_target()) return NoChange();
  DCHECK_EQ(constructor, native_context().string_function(broker_));
  DCHECK(constructor.initial_map(broker_).IsJSPrimitiveWrapperMap());
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Effect effect = n.effect();
  Control control = n.control();
  Node* primitive_value;
  if (n.ArgumentCount() == 0) {
    primitive_value = jsgraph()->EmptyStringConstant();
  } else {
    // Insert a construct stub frame into the chain of frame states. This will
    // reconstruct the proper frame when deoptimizing within the constructor.
    frame_state = CreateConstructInvokeStubFrameState(
        node, frame_state, constructor.shared(broker_), context, common(),
        graph());
    // This continuation takes the newly created primitive string, and wraps it
    // in a string wrapper, matching CreateStringWrapper.
    Node* continuation_frame_state =
        CreateStringCreateLazyDeoptContinuationFrameState(
            jsgraph(), constructor.shared(broker_), n.target(), context,
            frame_state);
    primitive_value = effect = control =
        graph()->NewNode(javascript()->ToString(), n.Argument(0), context,
                         continuation_frame_state, effect, control);
    // Rewire potential exception edges.
    Node* on_exception = nullptr;
    if (NodeProperties::IsExceptionalCall(node, &on_exception)) {
      // Create appropriate {IfException} and {IfSuccess} nodes.
      Node* if_exception =
          graph()->NewNode(common()->IfException(), effect, control);
      control = graph()->NewNode(common()->IfSuccess(), control);
      // Join the exception edges.
      Node* merge =
          graph()->NewNode(common()->Merge(2), if_exception, on_exception);
      Node* ephi = graph()->NewNode(common()->EffectPhi(2), if_exception,
                                    on_exception, merge);
      Node* phi =
          graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                           if_exception, on_exception, merge);
      ReplaceWithValue(on_exception, phi, ephi, merge);
      merge->ReplaceInput(1, on_exception);
      ephi->ReplaceInput(1, on_exception);
      phi->ReplaceInput(1, on_exception);
    }
  }
  RelaxControls(node, control);
  node->ReplaceInput(0, primitive_value);
  node->ReplaceInput(1, context);
  node->ReplaceInput(2, effect);
  node->TrimInputCount(3);
  NodeProperties::ChangeOp(node, javascript()->CreateStringWrapper());
  return Changed(node);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount(), broker_, v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateStringCreateLazyDeoptContinuationFrameState(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), graph(), v8::internal::compiler::JSFunctionRef::initial_map(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), javascript(), jsgraph(), v8::internal::kTagged, native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::AdvancedReducer::RelaxControls(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::JSFunctionRef::shared(), v8::internal::compiler::ToString(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by ReduceJSConstruct().
ReduceStringFromCharCode()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode (Node * node) [private]
Definition at line 7161 of file js-call-reducer.cc.
                                                            {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() == 1) {
    Effect effect = n.effect();
    Control control = n.control();
    Node* input = n.Argument(0);
    input = effect = graph()->NewNode(
        simplified()->SpeculativeToNumber(NumberOperationHint::kNumberOrOddball,
                                          p.feedback()),
        input, effect, control);
    Node* value =
        graph()->NewNode(simplified()->StringFromSingleCharCode(), input);
    ReplaceWithValue(node, value, effect);
    return Replace(value);
  }
  return NoChange();
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), v8::internal::kAllowSpeculation, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceStringFromCodePoint()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint (Node * node) [private]
Definition at line 7186 of file js-call-reducer.cc.
                                                             {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  if (n.ArgumentCount() != 1) return NoChange();
  Effect effect = n.effect();
  Control control = n.control();
  Node* input = n.Argument(0);
  input = effect = graph()->NewNode(
      simplified()->CheckBounds(p.feedback(),
                                CheckBoundsFlag::kConvertStringAndMinusZero),
      input, jsgraph()->ConstantNoHole(0x10FFFF + 1), effect, control);
  Node* value =
      graph()->NewNode(simplified()->StringFromSingleCodePoint(), input);
  ReplaceWithValue(node, value, effect);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::kConvertStringAndMinusZero, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceStringIteratorPrototypeNext()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext (Node * node) [private]
Definition at line 7292 of file js-call-reducer.cc.
                                                                     {
  JSCallNode n(node);
  Node* receiver = n.receiver();
  Effect effect = n.effect();
  Control control = n.control();
  Node* context = n.context();
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() ||
      !inference.AllOfInstanceTypesAre(JS_STRING_ITERATOR_TYPE)) {
    return NoChange();
  }
  Node* string = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSStringIteratorString()),
      receiver, effect, control);
  Node* index = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSStringIteratorIndex()),
      receiver, effect, control);
  Node* length = graph()->NewNode(simplified()->StringLength(), string);
  // branch0: if (index < length)
  Node* check0 =
      graph()->NewNode(simplified()->NumberLessThan(), index, length);
  Node* branch0 =
      graph()->NewNode(common()->Branch(BranchHint::kNone), check0, control);
  Node* etrue0 = effect;
  Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
  Node* done_true;
  Node* vtrue0;
  {
    done_true = jsgraph()->FalseConstant();
    vtrue0 = etrue0 = graph()->NewNode(simplified()->StringFromCodePointAt(),
                                       string, index, etrue0, if_true0);
    // Update iterator.[[NextIndex]]
    Node* char_length = graph()->NewNode(simplified()->StringLength(), vtrue0);
    index = graph()->NewNode(simplified()->NumberAdd(), index, char_length);
    etrue0 = graph()->NewNode(
        simplified()->StoreField(AccessBuilder::ForJSStringIteratorIndex()),
        receiver, index, etrue0, if_true0);
  }
  Node* if_false0 = graph()->NewNode(common()->IfFalse(), branch0);
  Node* done_false;
  Node* vfalse0;
  {
    vfalse0 = jsgraph()->UndefinedConstant();
    done_false = jsgraph()->TrueConstant();
  }
  control = graph()->NewNode(common()->Merge(2), if_true0, if_false0);
  effect = graph()->NewNode(common()->EffectPhi(2), etrue0, effect, control);
  Node* value =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2), vtrue0,
                       vfalse0, control);
  Node* done =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                       done_true, done_false, control);
  value = effect = graph()->NewNode(javascript()->CreateIterResultObject(),
                                    value, done, context, effect);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), broker(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::AccessBuilder::ForJSStringIteratorIndex(), v8::internal::compiler::AccessBuilder::ForJSStringIteratorString(), graph(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::index, javascript(), jsgraph(), v8::internal::kNone, v8::internal::kTagged, v8::internal::length, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::anonymous_namespace{api.cc}::StringLength(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceStringPrototypeCharAt()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt (Node * node) [private]
Definition at line 7075 of file js-call-reducer.cc.
                                                               {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation &&
      p.speculation_mode() !=
          SpeculationMode::kDisallowBoundsCheckSpeculation) {
    return NoChange();
  }
  Node* receiver = n.receiver();
  Node* index = n.ArgumentOr(0, jsgraph()->ZeroConstant());
  // Attempt to constant fold the operation when we know
  // that receiver is a string and index is a number.
  HeapObjectMatcher receiver_matcher(receiver);
  NumberMatcher index_matcher(index);
  if (receiver_matcher.HasResolvedValue()) {
    HeapObjectRef receiver_ref = receiver_matcher.Ref(broker());
    if (!receiver_ref.IsString()) return NoChange();
    StringRef receiver_string = receiver_ref.AsString();
    bool is_content_accessible = receiver_string.IsContentAccessible();
    bool is_integer_in_max_range =
        index_matcher.IsInteger() &&
        index_matcher.IsInRange(
            0.0, static_cast<double>(JSObject::kMaxElementIndex));
    if (is_content_accessible && is_integer_in_max_range) {
      JSCallReducerAssembler a(this, node);
      Node* subgraph = a.ReduceStringPrototypeCharAt(
          receiver_string,
          static_cast<uint32_t>(index_matcher.ResolvedValue()));
      return ReplaceWithSubgraph(&a, subgraph);
    }
  }
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceStringPrototypeCharAt(p.speculation_mode());
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOr(), broker(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::index, v8::internal::compiler::StringRef::IsContentAccessible(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInRange(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInteger(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::kDisallowBoundsCheckSpeculation, v8::internal::JSObject::kMaxElementIndex, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), ReplaceWithSubgraph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceStringPrototypeConcat()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat (Node * node) [private]
Definition at line 7361 of file js-call-reducer.cc.
                                                               {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  const int parameter_count = n.ArgumentCount();
  if (parameter_count > 1) return NoChange();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* receiver = effect = graph()->NewNode(
      simplified()->CheckString(p.feedback()), n.receiver(), effect, control);
  if (parameter_count == 0) {
    ReplaceWithValue(node, receiver, effect, control);
    return Replace(receiver);
  }
  Node* argument = effect = graph()->NewNode(
      simplified()->CheckString(p.feedback()), n.Argument(0), effect, control);
  Node* receiver_length =
      graph()->NewNode(simplified()->StringLength(), receiver);
  Node* argument_length =
      graph()->NewNode(simplified()->StringLength(), argument);
  Node* length = graph()->NewNode(simplified()->NumberAdd(), receiver_length,
                                  argument_length);
  length = effect = graph()->NewNode(
      simplified()->CheckBounds(p.feedback()), length,
      jsgraph()->ConstantNoHole(String::kMaxLength + 1), effect, control);
  Node* value = graph()->NewNode(simplified()->StringConcat(), length, receiver,
                                 argument);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::String::kMaxLength, v8::internal::length, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::anonymous_namespace{api.cc}::StringLength(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceStringPrototypeEndsWith()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith (Node * node) [private]
Definition at line 7036 of file js-call-reducer.cc.
                                                                 {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  TNode<Object> search_element = n.ArgumentOrUndefined(0, jsgraph());
  // Here are three conditions:
  // First, If search_element is definitely not a string, we make no change.
  // Second, If search_element is definitely a string and its length is less
  // or equal than max inline matching sequence threshold, we could inline
  // the entire matching sequence.
  // Third, we try to inline, and have a runtime deopt if search_element is
  // not a string.
  HeapObjectMatcher search_element_matcher(search_element);
  if (search_element_matcher.HasResolvedValue()) {
    ObjectRef target_ref = search_element_matcher.Ref(broker());
    if (!target_ref.IsString()) return NoChange();
    StringRef search_element_string = target_ref.AsString();
    if (!search_element_string.IsContentAccessible()) return NoChange();
    int length = search_element_string.length();
    // If search_element's length is less or equal than
    // kMaxInlineMatchSequence, we inline the entire
    // matching sequence.
    if (length <= kMaxInlineMatchSequence) {
      JSCallReducerAssembler a(this, node);
      Node* subgraph = a.ReduceStringPrototypeEndsWith(search_element_string);
      return ReplaceWithSubgraph(&a, subgraph);
    }
  }
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceStringPrototypeEndsWith();
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::StringRef::IsContentAccessible(), jsgraph(), v8::internal::kAllowSpeculation, kMaxInlineMatchSequence, v8::internal::length, v8::internal::compiler::StringRef::length(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), ReplaceWithSubgraph(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceStringPrototypeIndexOfIncludes()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes (Node * node, StringIndexOfIncludesVariant variant) [private]
Definition at line 5723 of file js-call-reducer.cc.
                                                      {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Effect effect = n.effect();
  Control control = n.control();
  if (n.ArgumentCount() > 0) {
    Node* receiver = n.receiver();
    Node* new_receiver = effect = graph()->NewNode(
        simplified()->CheckString(p.feedback()), receiver, effect, control);
    Node* search_string = n.Argument(0);
    Node* new_search_string = effect =
        graph()->NewNode(simplified()->CheckString(p.feedback()), search_string,
                         effect, control);
    Node* new_position = jsgraph()->ZeroConstant();
    if (n.ArgumentCount() > 1) {
      Node* position = n.Argument(1);
      new_position = effect = graph()->NewNode(
          simplified()->CheckSmi(p.feedback()), position, effect, control);
      Node* receiver_length =
          graph()->NewNode(simplified()->StringLength(), new_receiver);
      new_position = graph()->NewNode(
          simplified()->NumberMin(),
          graph()->NewNode(simplified()->NumberMax(), new_position,
                           jsgraph()->ZeroConstant()),
          receiver_length);
    }
    NodeProperties::ReplaceEffectInput(node, effect);
    RelaxEffectsAndControls(node);
    node->ReplaceInput(0, new_receiver);
    node->ReplaceInput(1, new_search_string);
    node->ReplaceInput(2, new_position);
    node->TrimInputCount(3);
    NodeProperties::ChangeOp(node, simplified()->StringIndexOf());
    if (variant == StringIndexOfIncludesVariant::kIndexOf) {
      return Changed(node);
    } else {
      DCHECK(variant == StringIndexOfIncludesVariant::kIncludes);
      Node* result =
          graph()->NewNode(simplified()->BooleanNot(),
                           graph()->NewNode(simplified()->NumberEqual(), node,
                                            jsgraph()->SmiConstant(-1)));
      return Replace(result);
    }
  }
  return NoChange();
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::DCHECK(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), jsgraph(), v8::internal::kAllowSpeculation, kIncludes, kIndexOf, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::RelaxEffectsAndControls(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::base::internal::result, simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::anonymous_namespace{api.cc}::StringLength(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by ReduceJSCall().
ReduceStringPrototypeIterator()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator (Node * node) [private]
Definition at line 7209 of file js-call-reducer.cc.
                                                                 {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* receiver = effect = graph()->NewNode(
      simplified()->CheckString(p.feedback()), n.receiver(), effect, control);
  Node* iterator = effect =
      graph()->NewNode(javascript()->CreateStringIterator(), receiver,
                       jsgraph()->NoContextConstant(), effect);
  ReplaceWithValue(node, iterator, effect, control);
  return Replace(iterator);
}
References v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), javascript(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceStringPrototypeSlice()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSlice (Node * node) [private]
Definition at line 5795 of file js-call-reducer.cc.
                                                              {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (n.ArgumentCount() < 1) return NoChange();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceStringPrototypeSlice();
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::kAllowSpeculation, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), ReplaceWithSubgraph(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceStringPrototypeStartsWith()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith (Node * node) [private]
Definition at line 6996 of file js-call-reducer.cc.
                                                                   {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  TNode<Object> search_element = n.ArgumentOrUndefined(0, jsgraph());
  // Here are three conditions:
  // First, If search_element is definitely not a string, we make no change.
  // Second, If search_element is definitely a string and its length is less
  // or equal than max inline matching sequence threshold, we could inline
  // the entire matching sequence.
  // Third, we try to inline, and have a runtime deopt if search_element is
  // not a string.
  HeapObjectMatcher search_element_matcher(search_element);
  if (search_element_matcher.HasResolvedValue()) {
    ObjectRef target_ref = search_element_matcher.Ref(broker());
    if (!target_ref.IsString()) return NoChange();
    StringRef search_element_string = target_ref.AsString();
    if (!search_element_string.IsContentAccessible()) return NoChange();
    int length = search_element_string.length();
    // If search_element's length is less or equal than
    // kMaxInlineMatchSequence, we inline the entire
    // matching sequence.
    if (length <= kMaxInlineMatchSequence) {
      JSCallReducerAssembler a(this, node);
      Node* subgraph = a.ReduceStringPrototypeStartsWith(search_element_string);
      return ReplaceWithSubgraph(&a, subgraph);
    }
  }
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceStringPrototypeStartsWith();
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), broker(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::StringRef::IsContentAccessible(), jsgraph(), v8::internal::kAllowSpeculation, kMaxInlineMatchSequence, v8::internal::length, v8::internal::compiler::StringRef::length(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), ReplaceWithSubgraph(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceStringPrototypeStringCharCodeAt()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCharCodeAt (Node * node) [private]
Definition at line 6946 of file js-call-reducer.cc.
                                                                         {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation &&
      p.speculation_mode() !=
          SpeculationMode::kDisallowBoundsCheckSpeculation) {
    return NoChange();
  }
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceStringPrototypeCharCodeAt(p.speculation_mode());
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::kAllowSpeculation, v8::internal::kDisallowBoundsCheckSpeculation, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharCodeAt(), ReplaceWithSubgraph(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceStringPrototypeStringCodePointAt()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt (Node * node) [private]
Definition at line 6961 of file js-call-reducer.cc.
                                                                          {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Node* receiver = n.receiver();
  Node* index = n.ArgumentOr(0, jsgraph()->ZeroConstant());
  Effect effect = n.effect();
  Control control = n.control();
  // Ensure that the {receiver} is actually a String.
  receiver = effect = graph()->NewNode(simplified()->CheckString(p.feedback()),
                                       receiver, effect, control);
  // Determine the {receiver} length.
  Node* receiver_length =
      graph()->NewNode(simplified()->StringLength(), receiver);
  // TODO(olivf): Support SpeculationMode::kOutOfBands.
  // Check that the {index} is within range.
  index = effect = graph()->NewNode(simplified()->CheckBounds(p.feedback()),
                                    index, receiver_length, effect, control);
  // Return the character from the {receiver} as single character string.
  Node* value = effect = graph()->NewNode(simplified()->StringCodePointAt(),
                                          receiver, index, effect, control);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOr(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), graph(), v8::internal::index, jsgraph(), v8::internal::kAllowSpeculation, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::anonymous_namespace{api.cc}::StringLength(), and v8::internal::value.
Referenced by ReduceJSCall().
ReduceStringPrototypeSubstr()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr (Node * node) [private]
Definition at line 5809 of file js-call-reducer.cc.
                                                               {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (n.ArgumentCount() < 1) return NoChange();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  Effect effect = n.effect();
  Control control = n.control();
  Node* receiver = n.receiver();
  Node* start = n.Argument(0);
  Node* end = n.ArgumentOrUndefined(1, jsgraph());
  receiver = effect = graph()->NewNode(simplified()->CheckString(p.feedback()),
                                       receiver, effect, control);
  start = effect = graph()->NewNode(simplified()->CheckSmi(p.feedback()), start,
                                    effect, control);
  Node* length = graph()->NewNode(simplified()->StringLength(), receiver);
  // Replace {end} argument with {length} if it is undefined.
  {
    Node* check = graph()->NewNode(simplified()->ReferenceEqual(), end,
                                   jsgraph()->UndefinedConstant());
    Node* branch =
        graph()->NewNode(common()->Branch(BranchHint::kFalse), check, control);
    Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
    Node* etrue = effect;
    Node* vtrue = length;
    Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
    Node* efalse = effect;
    Node* vfalse = efalse = graph()->NewNode(
        simplified()->CheckSmi(p.feedback()), end, efalse, if_false);
    control = graph()->NewNode(common()->Merge(2), if_true, if_false);
    effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
    end = graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                           vtrue, vfalse, control);
  }
  Node* initStart = graph()->NewNode(
      common()->Select(MachineRepresentation::kTagged, BranchHint::kFalse),
      graph()->NewNode(simplified()->NumberLessThan(), start,
                       jsgraph()->ZeroConstant()),
      graph()->NewNode(
          simplified()->NumberMax(),
          graph()->NewNode(simplified()->NumberAdd(), length, start),
          jsgraph()->ZeroConstant()),
      start);
  // The select above guarantees that initStart is non-negative, but
  // our typer can't figure that out yet.
  initStart = effect = graph()->NewNode(
      common()->TypeGuard(Type::UnsignedSmall()), initStart, effect, control);
  Node* resultLength = graph()->NewNode(
      simplified()->NumberMin(),
      graph()->NewNode(simplified()->NumberMax(), end,
                       jsgraph()->ZeroConstant()),
      graph()->NewNode(simplified()->NumberSubtract(), length, initStart));
  // The the select below uses {resultLength} only if {resultLength > 0},
  // but our typer can't figure that out yet.
  Node* to = effect = graph()->NewNode(
      common()->TypeGuard(Type::UnsignedSmall()),
      graph()->NewNode(simplified()->NumberAdd(), initStart, resultLength),
      effect, control);
  Node* result_string = nullptr;
  // Return empty string if {from} is smaller than {to}.
  {
    Node* check = graph()->NewNode(simplified()->NumberLessThan(),
                                   jsgraph()->ZeroConstant(), resultLength);
    Node* branch =
        graph()->NewNode(common()->Branch(BranchHint::kTrue), check, control);
    Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
    Node* etrue = effect;
    Node* vtrue = etrue =
        graph()->NewNode(simplified()->StringSubstring(), receiver, initStart,
                         to, etrue, if_true);
    Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
    Node* efalse = effect;
    Node* vfalse = jsgraph()->EmptyStringConstant();
    control = graph()->NewNode(common()->Merge(2), if_true, if_false);
    effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
    result_string =
        graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                         vtrue, vfalse, control);
  }
  ReplaceWithValue(node, result_string, effect, control);
  return Replace(result_string);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), common(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::end(), v8::internal::compiler::CallParameters::feedback(), graph(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::kFalse, v8::internal::kTagged, v8::internal::kTrue, v8::internal::length, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::anonymous_namespace{api.cc}::StringLength(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::compiler::Type::UnsignedSmall().
Referenced by ReduceJSCall().
ReduceStringPrototypeSubstring()
Reduction v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstring (Node * node) [private]
Definition at line 5781 of file js-call-reducer.cc.
                                                                  {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  if (n.ArgumentCount() < 1) return NoChange();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return NoChange();
  }
  JSCallReducerAssembler a(this, node);
  Node* subgraph = a.ReduceStringPrototypeSubstring();
  return ReplaceWithSubgraph(&a, subgraph);
}
References v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::kAllowSpeculation, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSubstring(), ReplaceWithSubgraph(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by ReduceJSCall().
ReduceTypedArrayConstructor()
Reduction v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor (Node * node, SharedFunctionInfoRef shared) [private]
Definition at line 7775 of file js-call-reducer.cc.
                                              {
  JSConstructNode n(node);
  Node* target = n.target();
  Node* arg0 = n.ArgumentOrUndefined(0, jsgraph());
  Node* arg1 = n.ArgumentOrUndefined(1, jsgraph());
  Node* arg2 = n.ArgumentOrUndefined(2, jsgraph());
  Node* new_target = n.new_target();
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Effect effect = n.effect();
  Control control = n.control();
  // Insert a construct stub frame into the chain of frame states. This will
  // reconstruct the proper frame when deoptimizing within the constructor.
  frame_state = CreateConstructInvokeStubFrameState(node, frame_state, shared,
                                                    context, common(), graph());
  // This continuation just returns the newly created JSTypedArray. We
  // pass the_hole as the receiver, just like the builtin construct stub
  // does in this case.
  Node* const receiver = jsgraph()->TheHoleConstant();
  Node* continuation_frame_state = CreateGenericLazyDeoptContinuationFrameState(
      jsgraph(), shared, target, context, receiver, frame_state);
  Node* result = graph()->NewNode(javascript()->CreateTypedArray(), target,
                                  new_target, arg0, arg1, arg2, context,
                                  continuation_frame_state, effect, control);
  return Replace(result);
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), v8::internal::compiler::CreateGenericLazyDeoptContinuationFrameState(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), graph(), javascript(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::AdvancedReducer::Replace(), and v8::base::internal::result.
Referenced by ReduceJSConstruct().
ReduceTypedArrayPrototypeLength()
Reduction v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength (Node * node) [private]
Definition at line 7986 of file js-call-reducer.cc.
                                                                   {
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  MapInference inference(broker(), receiver, effect);
  if (!inference.HaveMaps() ||
      !inference.AllOfInstanceTypesAre(JS_TYPED_ARRAY_TYPE)) {
    return inference.NoChange();
  }
  std::set<ElementsKind> elements_kinds;
  bool maybe_rab_gsab = false;
  for (MapRef map : inference.GetMaps()) {
    ElementsKind kind = map.elements_kind();
    elements_kinds.insert(kind);
    if (IsRabGsabTypedArrayElementsKind(kind)) maybe_rab_gsab = true;
  }
  if (!maybe_rab_gsab) {
    // We do not perform any change depending on this inference.
    Reduction unused_reduction = inference.NoChange();
    USE(unused_reduction);
    // Call default implementation for non-rab/gsab TAs.
    return ReduceArrayBufferViewAccessor(
        node, JS_TYPED_ARRAY_TYPE, AccessBuilder::ForJSTypedArrayByteLength(),
        Builtin::kTypedArrayPrototypeLength);
  }
  if (!inference.RelyOnMapsViaStability(dependencies())) {
    return inference.NoChange();
  }
  JSCallReducerAssembler a(this, node);
  TNode<JSTypedArray> typed_array =
      TNode<JSTypedArray>::UncheckedCast(receiver);
  TNode<Number> length = a.TypedArrayLength(
      typed_array, std::move(elements_kinds), a.ContextInput());
  if (!dependencies()->DependOnArrayBufferDetachingProtector()) {
    length =
        a.MachineSelectIf<Number>(a.ArrayBufferViewDetachedBit(typed_array))
            .Then([&]() { return a.NumberConstant(0); })
            .Else([&]() { return length; })
            .ExpectFalse()
            .Value();
  }
  return ReplaceWithSubgraph(&a, length);
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAre(), v8::internal::compiler::JSGraphAssembler::ArrayBufferViewDetachedBit(), broker(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), dependencies(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayByteLength(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::MapInference::HaveMaps(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::internal::length, v8::internal::compiler::JSGraphAssembler::MachineSelectIf(), v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), ReduceArrayBufferViewAccessor(), v8::internal::compiler::MapInference::RelyOnMapsViaStability(), ReplaceWithSubgraph(), v8::internal::compiler::JSGraphAssembler::TypedArrayLength(), v8::internal::TNode< T >::UncheckedCast(), and USE.
Referenced by ReduceJSCall().
ReduceTypedArrayPrototypeToStringTag()
Reduction v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag (Node * node) [private]
Definition at line 7807 of file js-call-reducer.cc.
                                                                        {
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  NodeVector values(graph()->zone());
  NodeVector effects(graph()->zone());
  NodeVector controls(graph()->zone());
  Node* smi_check = graph()->NewNode(simplified()->ObjectIsSmi(), receiver);
  control = graph()->NewNode(common()->Branch(BranchHint::kFalse), smi_check,
                             control);
  values.push_back(jsgraph()->UndefinedConstant());
  effects.push_back(effect);
  controls.push_back(graph()->NewNode(common()->IfTrue(), control));
  control = graph()->NewNode(common()->IfFalse(), control);
  Node* receiver_map = effect =
      graph()->NewNode(simplified()->LoadField(AccessBuilder::ForMap()),
                       receiver, effect, control);
  Node* receiver_bit_field2 = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForMapBitField2()), receiver_map,
      effect, control);
  Node* receiver_elements_kind = graph()->NewNode(
      simplified()->NumberShiftRightLogical(),
      graph()->NewNode(
          simplified()->NumberBitwiseAnd(), receiver_bit_field2,
          jsgraph()->ConstantNoHole(Map::Bits2::ElementsKindBits::kMask)),
      jsgraph()->ConstantNoHole(Map::Bits2::ElementsKindBits::kShift));
  // Offset the elements kind by FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND,
  // so that the branch cascade below is turned into a simple table
  // switch by the ControlFlowOptimizer later.
  receiver_elements_kind = graph()->NewNode(
      simplified()->NumberSubtract(), receiver_elements_kind,
      jsgraph()->ConstantNoHole(FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND));
  // To be converted into a switch by the ControlFlowOptimizer, the below
  // code requires that TYPED_ARRAYS and RAB_GSAB_TYPED_ARRAYS are consecutive.
  static_assert(LAST_FIXED_TYPED_ARRAY_ELEMENTS_KIND + 1 ==
                FIRST_RAB_GSAB_FIXED_TYPED_ARRAY_ELEMENTS_KIND);
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  do { \
    Node* check = graph()->NewNode(\
        simplified()->NumberEqual(), receiver_elements_kind, \
        jsgraph()->ConstantNoHole(TYPE##_ELEMENTS - \
                                  FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND)); \
    control = graph()->NewNode(common()->Branch(), check, control); \
    values.push_back(jsgraph()->ConstantNoHole(\
        broker()->GetTypedArrayStringTag(TYPE##_ELEMENTS), broker())); \
    effects.push_back(effect); \
    controls.push_back(graph()->NewNode(common()->IfTrue(), control)); \
    control = graph()->NewNode(common()->IfFalse(), control); \
  } while (false);
  TYPED_ARRAYS(TYPED_ARRAY_CASE)
  RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
  values.push_back(jsgraph()->UndefinedConstant());
  effects.push_back(effect);
  controls.push_back(control);
  int const count = static_cast<int>(controls.size());
  control = graph()->NewNode(common()->Merge(count), count, &controls.front());
  effects.push_back(control);
  effect =
      graph()->NewNode(common()->EffectPhi(count), count + 1, &effects.front());
  values.push_back(control);
  Node* value =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, count),
                       count + 1, &values.front());
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References common(), v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::FIRST_RAB_GSAB_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::AccessBuilder::ForMapBitField2(), v8::internal::ZoneVector< T >::front(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), jsgraph(), v8::internal::kFalse, v8::internal::kTagged, v8::internal::LAST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::compiler::TFGraph::NewNode(), v8::internal::ZoneVector< T >::push_back(), RAB_GSAB_TYPED_ARRAYS, v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), simplified(), v8::internal::ZoneVector< T >::size(), TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
Referenced by ReduceJSCall().
ReleaseEffectAndControlFromAssembler()
std::pair< Node *, Node * > v8::internal::compiler::JSCallReducer::ReleaseEffectAndControlFromAssembler (JSCallReducerAssembler * gasm) [private]
Definition at line 2591 of file js-call-reducer.cc.
                                  {
  auto catch_scope = gasm->catch_scope();
  DCHECK(catch_scope->is_outermost());
  if (catch_scope->has_handler() &&
      catch_scope->has_exceptional_control_flow()) {
    TNode<Object> handler_exception;
    Effect handler_effect{nullptr};
    Control handler_control{nullptr};
    gasm->catch_scope()->MergeExceptionalPaths(
        &handler_exception, &handler_effect, &handler_control);
    ReplaceWithValue(gasm->outermost_handler(), handler_exception,
                     handler_effect, handler_control);
  }
  return {gasm->effect(), gasm->control()};
}
References v8::internal::compiler::JSGraphAssembler::catch_scope(), v8::internal::compiler::GraphAssembler::control(), v8::internal::DCHECK(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::JSGraphAssembler::CatchScope::MergeExceptionalPaths(), v8::internal::compiler::JSGraphAssembler::outermost_handler(), and v8::internal::compiler::AdvancedReducer::ReplaceWithValue().
Referenced by ReduceArrayIterator().
ReplaceWithSubgraph()
Reduction v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph (JSCallReducerAssembler * gasm, Node * subgraph) [private]
Definition at line 2611 of file js-call-reducer.cc.
                                                             {
  // TODO(jgruber): Consider a less fiddly way of integrating the new subgraph
  // into the outer graph. For instance, the subgraph could be created in
  // complete isolation, and then plugged into the outer graph in one go.
  // Instead of manually tracking IfException nodes, we could iterate the
  // subgraph.
  // Replace the Call node with the newly-produced subgraph.
  ReplaceWithValue(gasm->node_ptr(), subgraph, gasm->effect(), gasm->control());
  // Wire exception edges contained in the newly-produced subgraph into the
  // outer graph.
  auto catch_scope = gasm->catch_scope();
  DCHECK(catch_scope->is_outermost());
  if (catch_scope->has_handler() &&
      catch_scope->has_exceptional_control_flow()) {
    TNode<Object> handler_exception;
    Effect handler_effect{nullptr};
    Control handler_control{nullptr};
    gasm->catch_scope()->MergeExceptionalPaths(
        &handler_exception, &handler_effect, &handler_control);
    ReplaceWithValue(gasm->outermost_handler(), handler_exception,
                     handler_effect, handler_control);
  }
  return Replace(subgraph);
}
References v8::internal::compiler::JSGraphAssembler::catch_scope(), v8::internal::compiler::GraphAssembler::control(), v8::internal::DCHECK(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::JSGraphAssembler::CatchScope::MergeExceptionalPaths(), v8::internal::compiler::JSCallReducerAssembler::node_ptr(), v8::internal::compiler::JSGraphAssembler::outermost_handler(), v8::internal::compiler::AdvancedReducer::Replace(), and v8::internal::compiler::AdvancedReducer::ReplaceWithValue().
Referenced by ReduceArrayBufferViewAccessor(), ReduceArrayBufferViewByteLengthAccessor(), ReduceArrayEvery(), ReduceArrayFilter(), ReduceArrayFind(), ReduceArrayFindIndex(), ReduceArrayForEach(), ReduceArrayIncludes(), ReduceArrayIndexOf(), ReduceArrayMap(), ReduceArrayPrototypeAt(), ReduceArrayPrototypePush(), ReduceArrayReduce(), ReduceArrayReduceRight(), ReduceArraySome(), ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceJSCallMathMinMaxWithArrayLike(), ReduceMathBinary(), ReduceMathUnary(), ReducePromiseConstructor(), ReduceStringPrototypeCharAt(), ReduceStringPrototypeEndsWith(), ReduceStringPrototypeSlice(), ReduceStringPrototypeStartsWith(), ReduceStringPrototypeStringCharCodeAt(), ReduceStringPrototypeSubstring(), and ReduceTypedArrayPrototypeLength().
RevisitForGraphAssembler()
void v8::internal::compiler::JSCallReducer::RevisitForGraphAssembler (Node * node) [inline]
Definition at line 72 of file js-call-reducer.h.
{ Revisit(node); }
Referenced by v8::internal::compiler::JSCallReducerAssembler::JSCallReducerAssembler().
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::JSCallReducer::simplified () const [private]
Definition at line 9284 of file js-call-reducer.cc.
                                                           {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by CheckArrayLength(), CheckIfConstructor(), CheckIfElementsKind(), ConvertHoleToUndefined(), LoadReceiverElementsKind(), ReduceArrayBufferIsView(), ReduceArrayIteratorPrototypeNext(), ReduceArrayPrototypePop(), ReduceArrayPrototypeShift(), ReduceBigIntAsN(), ReduceBooleanConstructor(), ReduceCallApiFunction(), ReduceCallOrConstructWithArrayLikeOrSpread(), ReduceCollectionIteratorPrototypeNext(), ReduceCollectionPrototypeHas(), ReduceCollectionPrototypeSize(), ReduceDataViewAccess(), ReduceDateNow(), ReduceDatePrototypeGetTime(), ReduceFunctionPrototypeApply(), ReduceFunctionPrototypeCall(), ReduceGlobalIsFinite(), ReduceGlobalIsNaN(), ReduceJSCall(), ReduceJSConstruct(), ReduceMapPrototypeGet(), ReduceMathClz32(), ReduceMathImul(), ReduceMathMinMax(), ReduceNumberIsFinite(), ReduceNumberIsInteger(), ReduceNumberIsNaN(), ReduceNumberIsSafeInteger(), ReduceObjectIs(), ReduceObjectPrototypeHasOwnProperty(), ReducePromisePrototypeFinally(), ReducePromisePrototypeThen(), ReduceReflectGet(), ReduceReflectHas(), ReduceRegExpPrototypeTest(), ReduceStringFromCharCode(), ReduceStringFromCodePoint(), ReduceStringIteratorPrototypeNext(), ReduceStringPrototypeConcat(), ReduceStringPrototypeIndexOfIncludes(), ReduceStringPrototypeIterator(), ReduceStringPrototypeStringCodePointAt(), ReduceStringPrototypeSubstr(), ReduceTypedArrayPrototypeToStringTag(), and TryReduceJSCallMathMinMaxWithArrayLike().
temp_zone()
Zone* v8::internal::compiler::JSCallReducer::temp_zone () const [inline], [private]
Definition at line 293 of file js-call-reducer.h.
{ return temp_zone_; }
TryReduceJSCallMathMinMaxWithArrayLike()
std::optional< Reduction > v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike (Node * node) [private]
Definition at line 9120 of file js-call-reducer.cc.
                {
  if (!v8_flags.turbo_optimize_math_minmax) return std::nullopt;
  JSCallWithArrayLikeNode n(node);
  CallParameters const& p = n.Parameters();
  Node* target = n.target();
  Effect effect = n.effect();
  Control control = n.control();
  if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
    return std::nullopt;
  }
  if (n.ArgumentCount() != 1) {
    return std::nullopt;
  }
  if (!dependencies()->DependOnNoElementsProtector()) {
    return std::nullopt;
  }
  // These ops are handled by ReduceCallOrConstructWithArrayLikeOrSpread.
  // IrOpcode::kJSCreateEmptyLiteralArray is not included, since arguments_list
  // for Math.min/min is not likely to keep empty.
  Node* arguments_list = n.Argument(0);
  if (arguments_list->opcode() == IrOpcode::kJSCreateLiteralArray ||
      arguments_list->opcode() == IrOpcode::kJSCreateArguments) {
    return std::nullopt;
  }
  HeapObjectMatcher m(target);
  if (m.HasResolvedValue()) {
    ObjectRef target_ref = m.Ref(broker());
    if (target_ref.IsJSFunction()) {
      JSFunctionRef function = target_ref.AsJSFunction();
      // Don't inline cross native context.
      if (!function.native_context(broker()).equals(native_context())) {
        return std::nullopt;
      }
      SharedFunctionInfoRef shared = function.shared(broker());
      Builtin builtin =
          shared.HasBuiltinId() ? shared.builtin_id() : Builtin::kNoBuiltinId;
      if (builtin == Builtin::kMathMax || builtin == Builtin::kMathMin) {
        return ReduceJSCallMathMinMaxWithArrayLike(node, builtin);
      } else {
        return std::nullopt;
      }
    }
  }
  // Try specialize the JSCallWithArrayLike node with feedback target.
  if (ShouldUseCallICFeedback(target) &&
      p.feedback_relation() == CallFeedbackRelation::kTarget &&
      p.feedback().IsValid()) {
    ProcessedFeedback const& feedback =
        broker()->GetFeedbackForCall(p.feedback());
    if (feedback.IsInsufficient()) {
      return std::nullopt;
    }
    OptionalHeapObjectRef feedback_target = feedback.AsCall().target();
    if (feedback_target.has_value() &&
        feedback_target->map(broker()).is_callable()) {
      Node* target_function =
          jsgraph()->ConstantNoHole(*feedback_target, broker());
      ObjectRef target_ref = feedback_target.value();
      if (!target_ref.IsJSFunction()) {
        return std::nullopt;
      }
      JSFunctionRef function = target_ref.AsJSFunction();
      SharedFunctionInfoRef shared = function.shared(broker());
      Builtin builtin =
          shared.HasBuiltinId() ? shared.builtin_id() : Builtin::kNoBuiltinId;
      if (builtin == Builtin::kMathMax || builtin == Builtin::kMathMin) {
        // Check that the {target} is still the {target_function}.
        Node* check = graph()->NewNode(simplified()->ReferenceEqual(), target,
                                       target_function);
        effect = graph()->NewNode(
            simplified()->CheckIf(DeoptimizeReason::kWrongCallTarget), check,
            effect, control);
        // Specialize the JSCallWithArrayLike node to the {target_function}.
        NodeProperties::ReplaceValueInput(node, target_function,
                                          n.TargetIndex());
        NodeProperties::ReplaceEffectInput(node, effect);
        // Try to further reduce the Call MathMin/Max with double array.
        return Changed(node).FollowedBy(
            ReduceJSCallMathMinMaxWithArrayLike(node, builtin));
      }
    }
  }
  return std::nullopt;
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), dependencies(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::JSHeapBroker::GetFeedbackForCall(), graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::FeedbackSource::IsValid(), jsgraph(), v8::internal::kAllowSpeculation, v8::internal::kNoBuiltinId, v8::internal::compiler::kTarget, native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::compiler::CallFeedback::target(), and v8::internal::v8_flags.
Referenced by ReduceJSCallWithArrayLike().
ZoneForGraphAssembler()
Zone* v8::internal::compiler::JSCallReducer::ZoneForGraphAssembler () const [inline]
Definition at line 73 of file js-call-reducer.h.
{ return temp_zone(); }
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::JSCallReducer::broker_ [private]
Definition at line 303 of file js-call-reducer.h.
Referenced by ReduceStringConstructor().
flags_
Flags const v8::internal::compiler::JSCallReducer::flags_ [private]
Definition at line 305 of file js-call-reducer.h.
generated_calls_with_array_like_or_spread_
std::unordered_set<Node*> v8::internal::compiler::JSCallReducer::generated_calls_with_array_like_or_spread_ [private]
Definition at line 309 of file js-call-reducer.h.
Referenced by ReduceCallOrConstructWithArrayLikeOrSpread().
jsgraph_
JSGraph* const v8::internal::compiler::JSCallReducer::jsgraph_ [private]
Definition at line 302 of file js-call-reducer.h.
kMaxInlineMatchSequence
constexpr int v8::internal::compiler::JSCallReducer::kMaxInlineMatchSequence = 3 [static], [constexpr]
Definition at line 61 of file js-call-reducer.h.
Referenced by ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), ReduceStringPrototypeStartsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
temp_zone_
Zone* const v8::internal::compiler::JSCallReducer::temp_zone_ [private]
Definition at line 304 of file js-call-reducer.h.
waitlist_
std::set<Node*> v8::internal::compiler::JSCallReducer::waitlist_ [private]
Definition at line 306 of file js-call-reducer.h.
Referenced by Finalize(), and ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-call-reducer.h
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc