v8::internal::ConcurrentMarking::JobTaskMajor Class Reference
Public Member Functions
JobTaskMajor (ConcurrentMarking *concurrent_marking, unsigned mark_compact_epoch, base::EnumSet< CodeFlushMode > code_flush_mode, bool should_keep_ages_unchanged)
~JobTaskMajor () override=default
JobTaskMajor (const JobTaskMajor &)=delete
JobTaskMajor & operator= (const JobTaskMajor &)=delete
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
uint64_t trace_id () const
Private Attributes
ConcurrentMarking * concurrent_marking_
const unsigned mark_compact_epoch_
base::EnumSet< CodeFlushMode > code_flush_mode_
const bool should_keep_ages_unchanged_
const uint64_t trace_id_
Detailed Description
Definition at line 229 of file concurrent-marking.cc.
Constructor & Destructor Documentation
JobTaskMajor() [1/2]
v8::internal::ConcurrentMarking::JobTaskMajor::JobTaskMajor (ConcurrentMarking * concurrent_marking, unsigned mark_compact_epoch, base::EnumSet< CodeFlushMode > code_flush_mode, bool should_keep_ages_unchanged) [inline]
Definition at line 231 of file concurrent-marking.cc.
      : concurrent_marking_(concurrent_marking),
        mark_compact_epoch_(mark_compact_epoch),
        code_flush_mode_(code_flush_mode),
        should_keep_ages_unchanged_(should_keep_ages_unchanged),
        trace_id_(reinterpret_cast<uint64_t>(concurrent_marking) ^
                  concurrent_marking->heap_->tracer()->CurrentEpoch(
                      GCTracer::Scope::MC_BACKGROUND_MARKING)) {}
 JobTaskMajor()
v8::internal::ConcurrentMarking::JobTaskMajor::~JobTaskMajor () [override], [default]
JobTaskMajor() [2/2]
v8::internal::ConcurrentMarking::JobTaskMajor::JobTaskMajor (const JobTaskMajor &) [delete]
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::ConcurrentMarking::JobTaskMajor::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 269 of file concurrent-marking.cc.
                                                               {
    return concurrent_marking_->GetMajorMaxConcurrency(worker_count);
  }
References concurrent_marking_, and v8::internal::ConcurrentMarking::GetMajorMaxConcurrency().
operator=()
JobTaskMajor& v8::internal::ConcurrentMarking::JobTaskMajor::operator= (const JobTaskMajor &) [delete]
Run()
void v8::internal::ConcurrentMarking::JobTaskMajor::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 248 of file concurrent-marking.cc.
                                           {
    // Set the current isolate such that trusted pointer tables etc are
    // available and the cage base is set correctly for multi-cage mode.
    SetCurrentIsolateScope isolate_scope(concurrent_marking_->heap_->isolate());
    if (delegate->IsJoiningThread()) {
      // TRACE_GC is not needed here because the caller opens the right scope.
      concurrent_marking_->RunMajor(delegate, code_flush_mode_,
                                    mark_compact_epoch_,
                                    should_keep_ages_unchanged_);
    } else {
      TRACE_GC_EPOCH_WITH_FLOW(concurrent_marking_->heap_->tracer(),
                               GCTracer::Scope::MC_BACKGROUND_MARKING,
                               ThreadKind::kBackground, trace_id_,
                               TRACE_EVENT_FLAG_FLOW_IN);
      concurrent_marking_->RunMajor(delegate, code_flush_mode_,
                                    mark_compact_epoch_,
                                    should_keep_ages_unchanged_);
    }
  }
References code_flush_mode_, concurrent_marking_, v8::internal::ConcurrentMarking::heap_, v8::JobDelegate::IsJoiningThread(), v8::internal::Heap::isolate(), v8::internal::kBackground, mark_compact_epoch_, v8::internal::ConcurrentMarking::RunMajor(), should_keep_ages_unchanged_, TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, trace_id_, and v8::internal::Heap::tracer().
trace_id()
uint64_t v8::internal::ConcurrentMarking::JobTaskMajor::trace_id () const [inline]
Definition at line 273 of file concurrent-marking.cc.
{ return trace_id_; }
References trace_id_.
Member Data Documentation
code_flush_mode_
base::EnumSet<CodeFlushMode> v8::internal::ConcurrentMarking::JobTaskMajor::code_flush_mode_ [private]
Definition at line 278 of file concurrent-marking.cc.
Referenced by Run().
concurrent_marking_
ConcurrentMarking* v8::internal::ConcurrentMarking::JobTaskMajor::concurrent_marking_ [private]
Definition at line 276 of file concurrent-marking.cc.
Referenced by GetMaxConcurrency(), and Run().
mark_compact_epoch_
const unsigned v8::internal::ConcurrentMarking::JobTaskMajor::mark_compact_epoch_ [private]
Definition at line 277 of file concurrent-marking.cc.
Referenced by Run().
should_keep_ages_unchanged_
const bool v8::internal::ConcurrentMarking::JobTaskMajor::should_keep_ages_unchanged_ [private]
Definition at line 279 of file concurrent-marking.cc.
Referenced by Run().
trace_id_
const uint64_t v8::internal::ConcurrentMarking::JobTaskMajor::trace_id_ [private]
Definition at line 280 of file concurrent-marking.cc.
Referenced by Run(), and trace_id().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/concurrent-marking.cc