v8::ScriptOrigin Class Reference
The origin, within a file, of a script.
#include <v8-message.h>
Public Member Functions
ScriptOrigin (Local< Value > resource_name, int resource_line_offset=0, int resource_column_offset=0, bool resource_is_shared_cross_origin=false, int script_id=-1, Local< Value > source_map_url=Local< Value >(), bool resource_is_opaque=false, bool is_wasm=false, bool is_module=false, Local< Data > host_defined_options=Local< Data >())
Local< Value > ResourceName () const
int LineOffset () const
int ColumnOffset () const
int ScriptId () const
Local< Value > SourceMapUrl () const
Local< Data > GetHostDefinedOptions () const
ScriptOriginOptions Options () const
Private Member Functions
void VerifyHostDefinedOptions () const
Private Attributes
Local< Value > resource_name_
int resource_line_offset_
int resource_column_offset_
ScriptOriginOptions options_
int script_id_
Local< Value > source_map_url_
Local< Data > host_defined_options_
Detailed Description
The origin, within a file, of a script.
Definition at line 63 of file v8-message.h.
Constructor & Destructor Documentation
ScriptOrigin()
v8::ScriptOrigin::ScriptOrigin (Local< Value > resource_name, int resource_line_offset = 0, int resource_column_offset = 0, bool resource_is_shared_cross_origin = false, int script_id = -1, Local< Value > source_map_url = Local<Value>(), bool resource_is_opaque = false, bool is_wasm = false, bool is_module = false, Local< Data > host_defined_options = Local<Data>()) [inline]
Definition at line 65 of file v8-message.h.
      : resource_name_(resource_name),
        resource_line_offset_(resource_line_offset),
        resource_column_offset_(resource_column_offset),
        options_(resource_is_shared_cross_origin, resource_is_opaque, is_wasm,
                 is_module),
        script_id_(script_id),
        source_map_url_(source_map_url),
        host_defined_options_(host_defined_options) {
    VerifyHostDefinedOptions();
  }
Member Function Documentation
ColumnOffset()
int v8::ScriptOrigin::ColumnOffset () const [inline]
Definition at line 215 of file v8-message.h.
{ return resource_column_offset_; }
Referenced by v8::anonymous_namespace{api.cc}::CompileStreamedSource(), and v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable().
GetHostDefinedOptions()
Local< Data > v8::ScriptOrigin::GetHostDefinedOptions () const [inline]
Definition at line 209 of file v8-message.h.
                                                      {
  return host_defined_options_;
}
Referenced by v8::anonymous_namespace{api.cc}::CompileStreamedSource(), v8::Shell::ExecuteString(), and v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable().
LineOffset()
int v8::ScriptOrigin::LineOffset () const [inline]
Definition at line 213 of file v8-message.h.
{ return resource_line_offset_; }
Referenced by v8::anonymous_namespace{api.cc}::CompileStreamedSource(), and v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable().
Options()
ScriptOriginOptions v8::ScriptOrigin::Options () const [inline]
Definition at line 91 of file v8-message.h.
{ return options_; }
Referenced by v8::anonymous_namespace{api.cc}::CompileStreamedSource(), and v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable().
ResourceName()
Local< Value > v8::ScriptOrigin::ResourceName () const [inline]
Definition at line 207 of file v8-message.h.
{ return resource_name_; }
Referenced by v8_inspector::V8Debugger::BreakpointConditionEvaluated(), v8::anonymous_namespace{api.cc}::CompileStreamedSource(), v8::Message::GetScriptResourceName(), and v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable().
ScriptId()
int v8::ScriptOrigin::ScriptId () const [inline]
Definition at line 217 of file v8-message.h.
{ return script_id_; }
Referenced by v8_inspector::V8Debugger::BreakpointConditionEvaluated().
SourceMapUrl()
Local< Value > v8::ScriptOrigin::SourceMapUrl () const [inline]
Definition at line 219 of file v8-message.h.
{ return source_map_url_; }
Referenced by v8::anonymous_namespace{api.cc}::CompileStreamedSource(), and v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable().
VerifyHostDefinedOptions()
void v8::ScriptOrigin::VerifyHostDefinedOptions () const [private]
Definition at line 2925 of file api.cc.
                                                  {
  // TODO(cbruni, chromium:1244145): Remove checks once we allow arbitrary
  // host-defined options.
  if (host_defined_options_.IsEmpty()) return;
  Utils::ApiCheck(host_defined_options_->IsFixedArray(), "ScriptOrigin()",
                  "Host-defined options has to be a PrimitiveArray");
  auto options =
      Utils::OpenDirectHandle(*host_defined_options_.As<FixedArray>());
  for (int i = 0; i < options->length(); i++) {
    Utils::ApiCheck(i::IsPrimitive(options->get(i)), "ScriptOrigin()",
                    "PrimitiveArray can only contain primtive values");
  }
}
References v8::Utils::ApiCheck(), host_defined_options_, v8::internal::IsPrimitive(), and v8::Utils::OpenDirectHandle().
Member Data Documentation
host_defined_options_
Local<Data> v8::ScriptOrigin::host_defined_options_ [private]
Definition at line 101 of file v8-message.h.
Referenced by VerifyHostDefinedOptions().
options_
ScriptOriginOptions v8::ScriptOrigin::options_ [private]
Definition at line 98 of file v8-message.h.
resource_column_offset_
int v8::ScriptOrigin::resource_column_offset_ [private]
Definition at line 97 of file v8-message.h.
resource_line_offset_
int v8::ScriptOrigin::resource_line_offset_ [private]
Definition at line 96 of file v8-message.h.
resource_name_
Local<Value> v8::ScriptOrigin::resource_name_ [private]
Definition at line 95 of file v8-message.h.
script_id_
int v8::ScriptOrigin::script_id_ [private]
Definition at line 99 of file v8-message.h.
source_map_url_
Local<Value> v8::ScriptOrigin::source_map_url_ [private]
Definition at line 100 of file v8-message.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-message.h
/mnt/V8SourceCode/src/api/api.cc