v8::internal::CPURegList Class Reference
#include <reglist-arm64.h>
Public Member Functions
template<typename... CPURegisters>
CPURegList (CPURegister reg0, CPURegisters... regs)
CPURegList (int size, RegList list)
CPURegList (int size, DoubleRegList list)
CPURegList (CPURegister::RegisterType type, int size, int first_reg, int last_reg)
CPURegister::RegisterType type () const
uint64_t bits () const
void set_bits (uint64_t new_bits)
void Combine (const CPURegList &other)
void Remove (const CPURegList &other)
void Combine (const CPURegister &other)
void Remove (const CPURegister &other1, const CPURegister &other2=NoCPUReg, const CPURegister &other3=NoCPUReg, const CPURegister &other4=NoCPUReg)
void Combine (int code)
void Remove (int code)
void Align ()
CPURegister PopLowestIndex ()
CPURegister PopHighestIndex ()
bool IsEmpty () const
bool IncludesAliasOf (const CPURegister &other1, const CPURegister &other2=NoCPUReg, const CPURegister &other3=NoCPUReg, const CPURegister &other4=NoCPUReg) const
int Count () const
int RegisterSizeInBits () const
int RegisterSizeInBytes () const
int TotalSizeInBytes () const
Static Public Member Functions
static CPURegList GetCalleeSaved (int size=kXRegSizeInBits)
static CPURegList GetCalleeSavedV (int size=kDRegSizeInBits)
static CPURegList GetCallerSaved (int size=kXRegSizeInBits)
static CPURegList GetCallerSavedV (int size=kDRegSizeInBits)
Private Member Functions
bool is_valid () const
Private Attributes
uint64_t list_
int size_
CPURegister::RegisterType type_
Detailed Description
Definition at line 25 of file reglist-arm64.h.
Constructor & Destructor Documentation
CPURegList() [1/4]
template<typename... CPURegisters>
v8::internal::CPURegList::CPURegList (CPURegister reg0, CPURegisters... regs) [inline], [explicit]
Definition at line 28 of file reglist-arm64.h.
      : list_(((uint64_t{1} << reg0.code()) | ... |
               (regs.is_valid() ? uint64_t{1} << regs.code() : 0))),
        size_(reg0.SizeInBits()),
        type_(reg0.type()) {
    DCHECK(AreSameSizeAndType(reg0, regs...));
    DCHECK(is_valid());
  }
References v8::internal::AreSameSizeAndType(), and v8::internal::DCHECK().
CPURegList() [2/4]
v8::internal::CPURegList::CPURegList (int size, RegList list) [inline]
Definition at line 37 of file reglist-arm64.h.
      : list_(list.bits()), size_(size), type_(CPURegister::kRegister) {
    DCHECK(is_valid());
  }
References v8::internal::DCHECK().
CPURegList() [3/4]
v8::internal::CPURegList::CPURegList (int size, DoubleRegList list) [inline]
Definition at line 42 of file reglist-arm64.h.
      : list_(list.bits()), size_(size), type_(CPURegister::kVRegister) {
    DCHECK(is_valid());
  }
References v8::internal::DCHECK().
CPURegList() [4/4]
v8::internal::CPURegList::CPURegList (CPURegister::RegisterType type, int size, int first_reg, int last_reg) [inline]
Definition at line 47 of file reglist-arm64.h.
      : size_(size), type_(type) {
    DCHECK(
        ((type == CPURegister::kRegister) && (last_reg < kNumberOfRegisters)) ||
        ((type == CPURegister::kVRegister) &&
         (last_reg < kNumberOfVRegisters)));
    DCHECK(last_reg >= first_reg);
    list_ = (1ULL << (last_reg + 1)) - 1;
    list_ &= ~((1ULL << first_reg) - 1);
    DCHECK(is_valid());
  }
References v8::internal::DCHECK(), v8::internal::kNumberOfRegisters, v8::internal::kNumberOfVRegisters, v8::internal::CPURegister::kRegister, v8::internal::CPURegister::kVRegister, and v8::internal::tracing::type.
Member Function Documentation
Align()
void v8::internal::CPURegList::Align ()
bits()
uint64_t v8::internal::CPURegList::bits () const [inline]
Definition at line 62 of file reglist-arm64.h.
{ return list_; }
Combine() [1/3]
void v8::internal::CPURegList::Combine (const CPURegister & other) [inline]
Definition at line 72 of file assembler-arm64-inl.h.
                                                        {
  DCHECK(other.type() == type_);
  DCHECK(other.SizeInBits() == size_);
  Combine(other.code());
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), Combine(), v8::internal::DCHECK(), size_, v8::internal::CPURegister::SizeInBits(), v8::internal::CPURegister::type(), and type_.
Combine() [2/3]
void v8::internal::CPURegList::Combine (const CPURegList & other) [inline]
Definition at line 60 of file assembler-arm64-inl.h.
                                                       {
  DCHECK(other.type() == type_);
  DCHECK(other.RegisterSizeInBits() == size_);
  list_ |= other.list_;
}
References v8::internal::DCHECK(), list_, RegisterSizeInBits(), size_, type(), and type_.
Referenced by Combine().
Combine() [3/3]
void v8::internal::CPURegList::Combine (int code) [inline]
Definition at line 88 of file assembler-arm64-inl.h.
                                        {
  DCHECK(CPURegister::Create(code, size_, type_).is_valid());
  list_ |= (1ULL << code);
  DCHECK(is_valid());
}
References code, v8::internal::CPURegister::Create(), v8::internal::DCHECK(), is_valid(), list_, size_, and type_.
Count()
int v8::internal::CPURegList::Count () const [inline]
Definition at line 128 of file reglist-arm64.h.
{ return CountSetBits(list_, kRegListSizeInBits); }
References v8::internal::CountSetBits(), and v8::internal::kRegListSizeInBits.
GetCalleeSaved()
static CPURegList v8::internal::CPURegList::GetCalleeSaved (int size = kXRegSizeInBits) [static]
GetCalleeSavedV()
static CPURegList v8::internal::CPURegList::GetCalleeSavedV (int size = kDRegSizeInBits) [static]
GetCallerSaved()
static CPURegList v8::internal::CPURegList::GetCallerSaved (int size = kXRegSizeInBits) [static]
GetCallerSavedV()
static CPURegList v8::internal::CPURegList::GetCallerSavedV (int size = kDRegSizeInBits) [static]
IncludesAliasOf()
bool v8::internal::CPURegList::IncludesAliasOf (const CPURegister & other1, const CPURegister & other2 = NoCPUReg, const CPURegister & other3 = NoCPUReg, const CPURegister & other4 = NoCPUReg) const [inline]
Definition at line 108 of file reglist-arm64.h.
                                                                   {
    uint64_t list = 0;
    if (!other1.IsNone() && (other1.type() == type_)) {
      list |= (uint64_t{1} << other1.code());
    }
    if (!other2.IsNone() && (other2.type() == type_)) {
      list |= (uint64_t{1} << other2.code());
    }
    if (!other3.IsNone() && (other3.type() == type_)) {
      list |= (uint64_t{1} << other3.code());
    }
    if (!other4.IsNone() && (other4.type() == type_)) {
      list |= (uint64_t{1} << other4.code());
    }
    return (list_ & list) != 0;
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::CPURegister::IsNone(), and v8::internal::CPURegister::type().
is_valid()
bool v8::internal::CPURegList::is_valid () const [inline], [private]
Definition at line 145 of file reglist-arm64.h.
                        {
    constexpr uint64_t kValidRegisters{0x8000000ffffffff};
    constexpr uint64_t kValidVRegisters{0x0000000ffffffff};
    switch (type_) {
      case CPURegister::kRegister:
        return (list_ & kValidRegisters) == list_;
      case CPURegister::kVRegister:
        return (list_ & kValidVRegisters) == list_;
      case CPURegister::kNoRegister:
        return list_ == 0;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::CPURegister::kNoRegister, v8::internal::CPURegister::kRegister, v8::internal::CPURegister::kVRegister, and v8::internal::UNREACHABLE().
Referenced by Combine(), and Remove().
IsEmpty()
bool v8::internal::CPURegList::IsEmpty () const [inline]
Definition at line 106 of file reglist-arm64.h.
{ return list_ == 0; }
Referenced by v8::internal::UseScratchRegisterScope::Exclude(), and v8::internal::UseScratchRegisterScope::ExcludeFP().
PopHighestIndex()
CPURegister v8::internal::CPURegList::PopHighestIndex ()
Referenced by v8::internal::UseScratchRegisterScope::Exclude(), and v8::internal::UseScratchRegisterScope::ExcludeFP().
PopLowestIndex()
CPURegister v8::internal::CPURegList::PopLowestIndex ()
RegisterSizeInBits()
int v8::internal::CPURegList::RegisterSizeInBits () const [inline]
Definition at line 130 of file reglist-arm64.h.
{ return size_; }
Referenced by Combine().
RegisterSizeInBytes()
int v8::internal::CPURegList::RegisterSizeInBytes () const [inline]
Definition at line 132 of file reglist-arm64.h.
                                  {
    int size_in_bits = RegisterSizeInBits();
    DCHECK_EQ(size_in_bits % kBitsPerByte, 0);
    return size_in_bits / kBitsPerByte;
  }
References DCHECK_EQ, and v8::internal::kBitsPerByte.
Remove() [1/3]
void v8::internal::CPURegList::Remove (const CPURegister & other1, const CPURegister & other2 = NoCPUReg, const CPURegister & other3 = NoCPUReg, const CPURegister & other4 = NoCPUReg) [inline]
Definition at line 78 of file assembler-arm64-inl.h.
                                                          {
  if (!other1.IsNone() && (other1.type() == type_)) Remove(other1.code());
  if (!other2.IsNone() && (other2.type() == type_)) Remove(other2.code());
  if (!other3.IsNone() && (other3.type() == type_)) Remove(other3.code());
  if (!other4.IsNone() && (other4.type() == type_)) Remove(other4.code());
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::CPURegister::IsNone(), Remove(), v8::internal::CPURegister::type(), and type_.
Remove() [2/3]
void v8::internal::CPURegList::Remove (const CPURegList & other) [inline]
Definition at line 66 of file assembler-arm64-inl.h.
                                                      {
  if (other.type() == type_) {
    list_ &= ~other.list_;
  }
}
References list_, type(), and type_.
Referenced by Remove().
Remove() [3/3]
void v8::internal::CPURegList::Remove (int code) [inline]
Definition at line 94 of file assembler-arm64-inl.h.
                                       {
  DCHECK(CPURegister::Create(code, size_, type_).is_valid());
  list_ &= ~(1ULL << code);
}
References code, v8::internal::CPURegister::Create(), v8::internal::DCHECK(), is_valid(), list_, size_, and type_.
set_bits()
void v8::internal::CPURegList::set_bits (uint64_t new_bits) [inline]
Definition at line 64 of file reglist-arm64.h.
                                          {
    list_ = new_bits;
    DCHECK(is_valid());
  }
References v8::internal::DCHECK().
TotalSizeInBytes()
int v8::internal::CPURegList::TotalSizeInBytes () const [inline]
Definition at line 138 of file reglist-arm64.h.
{ return RegisterSizeInBytes() * Count(); }
type()
CPURegister::RegisterType v8::internal::CPURegList::type () const [inline]
Definition at line 60 of file reglist-arm64.h.
{ return type_; }
Referenced by Combine(), and Remove().
Member Data Documentation
list_
uint64_t v8::internal::CPURegList::list_ [private]
Definition at line 141 of file reglist-arm64.h.
Referenced by Combine(), and Remove().
size_
int v8::internal::CPURegList::size_ [private]
Definition at line 142 of file reglist-arm64.h.
Referenced by Combine(), and Remove().
type_
CPURegister::RegisterType v8::internal::CPURegList::type_ [private]
Definition at line 143 of file reglist-arm64.h.
Referenced by Combine(), and Remove().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm64/reglist-arm64.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h