v8::internal::DeoptTranslationIterator Class Reference
#include <deoptimization-data.h>
Public Member Functions
DeoptTranslationIterator (base::Vector< const uint8_t > buffer, int index)
int32_t NextOperand ()
uint32_t NextOperandUnsigned ()
DeoptimizationFrameTranslation::FrameCount EnterBeginOpcode ()
TranslationOpcode NextOpcode ()
TranslationOpcode SeekNextJSFrame ()
TranslationOpcode SeekNextFrame ()
bool HasNextOpcode () const
void SkipOperands (int n)
Private Member Functions
TranslationOpcode NextOpcodeAtPreviousIndex ()
uint32_t NextUnsignedOperandAtPreviousIndex ()
void SkipOpcodeAndItsOperandsAtPreviousIndex ()
Private Attributes
std::vector< int32_t > uncompressed_contents_
const base::Vector< const uint8_t > buffer_
int index_
int remaining_ops_to_use_from_previous_translation_ = 0
int previous_index_ = 0
int ops_since_previous_index_was_updated_ = 0
Detailed Description
Definition at line 205 of file deoptimization-data.h.
Constructor & Destructor Documentation
DeoptTranslationIterator()
v8::internal::DeoptTranslationIterator::DeoptTranslationIterator (base::Vector< const uint8_t > buffer, int index)
Definition at line 189 of file deoptimization-data.cc.
    : buffer_(buffer), index_(index) {
#ifdef V8_USE_ZLIB
  if (V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)) {
    const int size =
        base::ReadUnalignedValue<uint32_t>(reinterpret_cast<Address>(
            &buffer_[DeoptimizationFrameTranslation::kUncompressedSizeOffset]));
    uncompressed_contents_.insert(uncompressed_contents_.begin(), size, 0);
    uLongf uncompressed_size = size *
                               DeoptimizationFrameTranslation::
                                   kDeoptimizationFrameTranslationElementSize;
    CHECK_EQ(zlib_internal::UncompressHelper(
                 zlib_internal::ZRAW,
                 reinterpret_cast<Bytef*>(uncompressed_contents_.data()),
                 &uncompressed_size,
                 buffer_.begin() +
                     DeoptimizationFrameTranslation::kCompressedDataOffset,
                 buffer_.length()),
             Z_OK);
    DCHECK(index >= 0 && index < size);
    return;
  }
#endif // V8_USE_ZLIB
  DCHECK(!v8_flags.turbo_compress_frame_translations);
  DCHECK(index >= 0 && index < buffer_.length());
  // Starting at a location other than a BEGIN would make
  // MATCH_PREVIOUS_TRANSLATION instructions not work.
  DCHECK(
      TranslationOpcodeIsBegin(static_cast<TranslationOpcode>(buffer_[index])));
}
References v8::base::Vector< T >::begin(), buffer_, CHECK_EQ, v8::internal::DCHECK(), v8::internal::index, v8::base::Vector< T >::length(), size(), v8::internal::TranslationOpcodeIsBegin(), uncompressed_contents_, v8::internal::v8_flags, and V8_UNLIKELY.
Member Function Documentation
EnterBeginOpcode()
DeoptimizationFrameTranslation::FrameCount v8::internal::DeoptTranslationIterator::EnterBeginOpcode ()
Definition at line 329 of file deoptimization-data.cc.
                                           {
  TranslationOpcode opcode = NextOpcode();
  DCHECK(TranslationOpcodeIsBegin(opcode));
  USE(opcode);
  NextOperand(); // Skip lookback distance.
  int frame_count = NextOperand();
  int jsframe_count = NextOperand();
  return {frame_count, jsframe_count};
}
References v8::internal::DCHECK(), v8::internal::TranslationOpcodeIsBegin(), and USE.
Referenced by v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), and v8::internal::OptimizedJSFrame::GetFunctions().
HasNextOpcode()
bool v8::internal::DeoptTranslationIterator::HasNextOpcode () const
Definition at line 367 of file deoptimization-data.cc.
                                                   {
  if (V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)) {
    return index_ < static_cast<int>(uncompressed_contents_.size());
  } else {
    return index_ < buffer_.length() ||
           remaining_ops_to_use_from_previous_translation_ > 1;
  }
}
References v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::FrameTranslationBuilder::ValidateBytes().
NextOpcode()
TranslationOpcode v8::internal::DeoptTranslationIterator::NextOpcode ()
Definition at line 269 of file deoptimization-data.cc.
                                                       {
  if (V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)) {
    return static_cast<TranslationOpcode>(NextOperandUnsigned());
  }
  if (remaining_ops_to_use_from_previous_translation_) {
    --remaining_ops_to_use_from_previous_translation_;
  }
  if (remaining_ops_to_use_from_previous_translation_) {
    return NextOpcodeAtPreviousIndex();
  }
  CHECK_LT(index_, buffer_.length());
  uint8_t opcode_byte = buffer_[index_++];
  // If the opcode byte is greater than any valid opcode, then the opcode is
  // implicitly MATCH_PREVIOUS_TRANSLATION and the operand is the opcode byte
  // minus kNumTranslationOpcodes. This special-case encoding of the most common
  // opcode saves some memory.
  if (opcode_byte >= kNumTranslationOpcodes) {
    remaining_ops_to_use_from_previous_translation_ =
        opcode_byte - kNumTranslationOpcodes;
    opcode_byte =
        static_cast<uint8_t>(TranslationOpcode::MATCH_PREVIOUS_TRANSLATION);
  } else if (opcode_byte ==
             static_cast<uint8_t>(
                 TranslationOpcode::MATCH_PREVIOUS_TRANSLATION)) {
    remaining_ops_to_use_from_previous_translation_ = NextOperandUnsigned();
  }
  TranslationOpcode opcode = static_cast<TranslationOpcode>(opcode_byte);
  DCHECK_LE(index_, buffer_.length());
  DCHECK_LT(static_cast<uint32_t>(opcode), kNumTranslationOpcodes);
  if (TranslationOpcodeIsBegin(opcode)) {
    int temp_index = index_;
    // The first argument for BEGIN is the distance, in bytes, since the
    // previous BEGIN, or zero to indicate that MATCH_PREVIOUS_TRANSLATION will
    // not be used in this translation.
    uint32_t lookback_distance =
        base::VLQDecodeUnsigned(buffer_.begin(), &temp_index);
    if (lookback_distance) {
      previous_index_ = index_ - 1 - lookback_distance;
      DCHECK(TranslationOpcodeIsBegin(
          static_cast<TranslationOpcode>(buffer_[previous_index_])));
      // The previous BEGIN should specify zero as its lookback distance,
      // meaning it won't use MATCH_PREVIOUS_TRANSLATION.
      DCHECK_EQ(buffer_[previous_index_ + 1], 0);
    }
    ops_since_previous_index_was_updated_ = 1;
  } else if (opcode == TranslationOpcode::MATCH_PREVIOUS_TRANSLATION) {
    for (int i = 0; i < ops_since_previous_index_was_updated_; ++i) {
      SkipOpcodeAndItsOperandsAtPreviousIndex();
    }
    ops_since_previous_index_was_updated_ = 0;
    opcode = NextOpcodeAtPreviousIndex();
  } else {
    ++ops_since_previous_index_was_updated_;
  }
  return opcode;
}
References CHECK_LT, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kNumTranslationOpcodes, v8::internal::TranslationOpcodeIsBegin(), v8::internal::v8_flags, V8_UNLIKELY, and v8::base::VLQDecodeUnsigned().
Referenced by v8::internal::FrameTranslationBuilder::ValidateBytes().
NextOpcodeAtPreviousIndex()
TranslationOpcode v8::internal::DeoptTranslationIterator::NextOpcodeAtPreviousIndex () [private]
Definition at line 242 of file deoptimization-data.cc.
                                                                      {
  TranslationOpcode opcode =
      static_cast<TranslationOpcode>(buffer_[previous_index_++]);
  DCHECK_LT(static_cast<uint32_t>(opcode), kNumTranslationOpcodes);
  DCHECK_NE(opcode, TranslationOpcode::MATCH_PREVIOUS_TRANSLATION);
  DCHECK_LT(previous_index_, index_);
  return opcode;
}
References DCHECK_LT, DCHECK_NE, and v8::internal::kNumTranslationOpcodes.
NextOperand()
int32_t v8::internal::DeoptTranslationIterator::NextOperand ()
Definition at line 228 of file deoptimization-data.cc.
                                              {
  if (V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)) {
    return uncompressed_contents_[index_++];
  } else if (remaining_ops_to_use_from_previous_translation_) {
    int32_t value = base::VLQDecode(buffer_.begin(), &previous_index_);
    DCHECK_LT(previous_index_, index_);
    return value;
  } else {
    int32_t value = base::VLQDecode(buffer_.begin(), &index_);
    DCHECK_LE(index_, buffer_.length());
    return value;
  }
}
References DCHECK_LE, DCHECK_LT, v8::internal::v8_flags, V8_UNLIKELY, v8::internal::value, and v8::base::VLQDecode().
Referenced by v8::internal::DeoptimizationFrameTranslationPrintSingleOpcode(), v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), v8::internal::OptimizedJSFrame::GetFunctions(), SkipOperands(), and v8::internal::FrameTranslationBuilder::ValidateBytes().
NextOperandUnsigned()
uint32_t v8::internal::DeoptTranslationIterator::NextOperandUnsigned ()
Definition at line 257 of file deoptimization-data.cc.
                                                       {
  if (V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)) {
    return uncompressed_contents_[index_++];
  } else if (remaining_ops_to_use_from_previous_translation_) {
    return NextUnsignedOperandAtPreviousIndex();
  } else {
    uint32_t value = base::VLQDecodeUnsigned(buffer_.begin(), &index_);
    DCHECK_LE(index_, buffer_.length());
    return value;
  }
}
References DCHECK_LE, v8::internal::v8_flags, V8_UNLIKELY, v8::internal::value, and v8::base::VLQDecodeUnsigned().
Referenced by v8::internal::DeoptimizationFrameTranslationPrintSingleOpcode(), and v8::internal::FrameTranslationBuilder::ValidateBytes().
NextUnsignedOperandAtPreviousIndex()
uint32_t v8::internal::DeoptTranslationIterator::NextUnsignedOperandAtPreviousIndex () [private]
Definition at line 251 of file deoptimization-data.cc.
                                                                      {
  uint32_t value = base::VLQDecodeUnsigned(buffer_.begin(), &previous_index_);
  DCHECK_LT(previous_index_, index_);
  return value;
}
References DCHECK_LT, v8::internal::value, and v8::base::VLQDecodeUnsigned().
SeekNextFrame()
TranslationOpcode v8::internal::DeoptTranslationIterator::SeekNextFrame ()
Definition at line 353 of file deoptimization-data.cc.
                                                          {
  while (HasNextOpcode()) {
    TranslationOpcode opcode = NextOpcode();
    DCHECK(!TranslationOpcodeIsBegin(opcode));
    if (IsTranslationFrameOpcode(opcode)) {
      return opcode;
    } else {
      // Skip over operands to advance to the next opcode.
      SkipOperands(TranslationOpcodeOperandCount(opcode));
    }
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::IsTranslationFrameOpcode(), v8::internal::TranslationOpcodeIsBegin(), v8::internal::TranslationOpcodeOperandCount(), and v8::internal::UNREACHABLE().
SeekNextJSFrame()
TranslationOpcode v8::internal::DeoptTranslationIterator::SeekNextJSFrame ()
Definition at line 339 of file deoptimization-data.cc.
                                                            {
  while (HasNextOpcode()) {
    TranslationOpcode opcode = NextOpcode();
    DCHECK(!TranslationOpcodeIsBegin(opcode));
    if (IsTranslationJsFrameOpcode(opcode)) {
      return opcode;
    } else {
      // Skip over operands to advance to the next opcode.
      SkipOperands(TranslationOpcodeOperandCount(opcode));
    }
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::IsTranslationJsFrameOpcode(), v8::internal::TranslationOpcodeIsBegin(), v8::internal::TranslationOpcodeOperandCount(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), and v8::internal::OptimizedJSFrame::GetFunctions().
SkipOpcodeAndItsOperandsAtPreviousIndex()
void v8::internal::DeoptTranslationIterator::SkipOpcodeAndItsOperandsAtPreviousIndex () [private]
Definition at line 376 of file deoptimization-data.cc.
                                                                       {
  TranslationOpcode opcode = NextOpcodeAtPreviousIndex();
  for (int count = TranslationOpcodeOperandCount(opcode); count != 0; --count) {
    NextUnsignedOperandAtPreviousIndex();
  }
}
References v8::internal::TranslationOpcodeOperandCount().
SkipOperands()
void v8::internal::DeoptTranslationIterator::SkipOperands (int n) [inline]
Definition at line 222 of file deoptimization-data.h.
                           {
    for (int i = 0; i < n; i++) NextOperand();
  }
References NextOperand().
Referenced by v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), and v8::internal::OptimizedJSFrame::GetFunctions().
Member Data Documentation
buffer_
const base::Vector<const uint8_t> v8::internal::DeoptTranslationIterator::buffer_ [private]
Definition at line 232 of file deoptimization-data.h.
Referenced by DeoptTranslationIterator().
index_
int v8::internal::DeoptTranslationIterator::index_ [private]
Definition at line 233 of file deoptimization-data.h.
ops_since_previous_index_was_updated_
int v8::internal::DeoptTranslationIterator::ops_since_previous_index_was_updated_ = 0 [private]
Definition at line 245 of file deoptimization-data.h.
previous_index_
int v8::internal::DeoptTranslationIterator::previous_index_ = 0 [private]
Definition at line 241 of file deoptimization-data.h.
remaining_ops_to_use_from_previous_translation_
int v8::internal::DeoptTranslationIterator::remaining_ops_to_use_from_previous_translation_ = 0 [private]
Definition at line 237 of file deoptimization-data.h.
uncompressed_contents_
std::vector<int32_t> v8::internal::DeoptTranslationIterator::uncompressed_contents_ [private]
Definition at line 231 of file deoptimization-data.h.
Referenced by DeoptTranslationIterator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/deoptimization-data.h
/mnt/V8SourceCode/src/objects/deoptimization-data.cc