v8::internal::compiler::HeapObjectRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< HeapObject > object () const
V8_EXPORT_PRIVATE MapRef map (JSHeapBroker *broker) const
OptionalMapRef map_direct_read (JSHeapBroker *broker) const
HeapObjectType GetHeapObjectType (JSHeapBroker *broker) const
Detailed Description
Definition at line 530 of file heap-refs.h.
Member Function Documentation
GetHeapObjectType()
HeapObjectType v8::internal::compiler::HeapObjectRef::GetHeapObjectType (JSHeapBroker * broker) const
Definition at line 2272 of file heap-refs.cc.
                                                                          {
  if (data_->should_access_heap()) {
    Tagged<Map> map = Cast<HeapObject>(object())->map(broker->cage_base());
    HeapObjectType::Flags flags(0);
    if (map->is_undetectable()) flags |= HeapObjectType::kUndetectable;
    if (map->is_callable()) flags |= HeapObjectType::kCallable;
    return HeapObjectType(map->instance_type(), map->elements_kind(), flags,
                          GetOddballType(broker->isolate(), map), HoleType());
  }
  HeapObjectType::Flags flags(0);
  if (map(broker).is_undetectable()) flags |= HeapObjectType::kUndetectable;
  if (map(broker).is_callable()) flags |= HeapObjectType::kCallable;
  return HeapObjectType(map(broker).instance_type(),
                        map(broker).elements_kind(), flags,
                        map(broker).oddball_type(broker), HoleType());
}
References broker(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::flags, v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOddballType(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::is_callable(), v8::internal::compiler::MapRef::is_undetectable(), v8::internal::is_undetectable, v8::internal::compiler::HeapObjectType::kCallable, v8::internal::compiler::HeapObjectType::kUndetectable, and map().
map()
V8_EXPORT_PRIVATE MapRef v8::internal::compiler::HeapObjectRef::map (JSHeapBroker * broker) const
Referenced by v8::internal::compiler::AnyMapIsHeapNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckInternalizedStringValueOrByReference(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckValueByReference(), v8::internal::compiler::AccessInfoFactory::ComputeDictionaryProtoAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChain(), v8::internal::compiler::JSTypedArrayRef::elements_kind(), v8::internal::compiler::NativeContextRef::GetConstructorFunction(), GetHeapObjectType(), v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::compiler::JSObjectRef::GetObjectCreateMap(), v8::internal::compiler::JSArrayRef::GetOwnCowElement(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::maglev::MaglevGraphBuilder::HasValidInitialMap(), v8::internal::compiler::JSNativeContextSpecialization::InferHasInPrototypeChain(), v8::internal::maglev::MaglevGraphBuilder::InferHasInPrototypeChain(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::compiler::JSNativeContextSpecialization::InferRootMap(), v8::internal::compiler::JSPrimitiveWrapperRef::IsStringWrapper(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), map_direct_read(), v8::internal::compiler::MapRef::PrototypesElementsDoNotHaveAccessorsOrThrow(), v8::internal::compiler::JSObjectRef::RawInobjectPropertyAt(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFindNonDefaultConstructorOrConstruct(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), v8::internal::maglev::MaglevGraphBuilder::TryGetNonEscapingArgumentsObject(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceConstruct().
map_direct_read()
OptionalMapRef v8::internal::compiler::HeapObjectRef::map_direct_read (JSHeapBroker * broker) const
Definition at line 2245 of file heap-refs.cc.
                                                                        {
  PtrComprCageBase cage_base = broker->cage_base();
  return TryMakeRef(broker, object()->map(cage_base, kAcquireLoad),
                    kAssumeMemoryFence);
}
References broker(), v8::kAcquireLoad, v8::internal::compiler::kAssumeMemoryFence, map(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
object()
IndirectHandle<HeapObject> v8::internal::compiler::HeapObjectRef::object () const
Referenced by v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), v8::internal::maglev::Constant::DoReify(), v8::internal::maglev::TrustedConstant::DoReify(), v8::internal::maglev::Graph::GetConstant(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::GetDeoptLiteral(), v8::internal::maglev::Constant::PrintParams(), v8::internal::maglev::TrustedConstant::PrintParams(), v8::internal::maglev::CheckValue::PrintParams(), v8::internal::maglev::HasInPrototypeChain::PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::Constant::ToBoolean(), and v8::internal::compiler::HeapConstantType::Value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc