v8::internal::compiler::OutputFrameStateCombine Class Reference
#include <frame-states.h>
Public Member Functions
size_t GetOffsetToPokeAt () const
bool IsOutputIgnored () const
size_t ConsumedOutputCount () const
bool operator== (OutputFrameStateCombine const &other) const
bool operator!= (OutputFrameStateCombine const &other) const
Static Public Member Functions
static OutputFrameStateCombine Ignore ()
static OutputFrameStateCombine PokeAt (size_t index)
Static Public Attributes
static const size_t kInvalidIndex = SIZE_MAX
Private Member Functions
OutputFrameStateCombine (size_t parameter)
Private Attributes
size_t const parameter_
Friends
size_t hash_value (OutputFrameStateCombine const &)
std::ostream & operator<< (std::ostream &, OutputFrameStateCombine const &)
Detailed Description
Definition at line 30 of file frame-states.h.
Constructor & Destructor Documentation
OutputFrameStateCombine()
v8::internal::compiler::OutputFrameStateCombine::OutputFrameStateCombine (size_t parameter) [inline], [explicit], [private]
Definition at line 62 of file frame-states.h.
: parameter_(parameter) {}
Referenced by Ignore(), and PokeAt().
Member Function Documentation
ConsumedOutputCount()
size_t v8::internal::compiler::OutputFrameStateCombine::ConsumedOutputCount () const [inline]
Definition at line 48 of file frame-states.h.
{ return IsOutputIgnored() ? 0 : 1; }
References IsOutputIgnored().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
GetOffsetToPokeAt()
size_t v8::internal::compiler::OutputFrameStateCombine::GetOffsetToPokeAt () const [inline]
Definition at line 41 of file frame-states.h.
                                   {
    DCHECK_NE(parameter_, kInvalidIndex);
    return parameter_;
  }
References DCHECK_NE, kInvalidIndex, and parameter_.
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct().
Ignore()
static OutputFrameStateCombine v8::internal::compiler::OutputFrameStateCombine::Ignore () [inline], [static]
Definition at line 34 of file frame-states.h.
                                          {
    return OutputFrameStateCombine(kInvalidIndex);
  }
References kInvalidIndex, and OutputFrameStateCombine().
Referenced by v8::internal::compiler::CodeGenerator::AddDeoptimizationExit(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForFunctionEntryStackCheck(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForOSREntryStackCheck(), and v8::internal::compiler::BytecodeGraphBuilder::Environment::RecordAfterState().
IsOutputIgnored()
bool v8::internal::compiler::OutputFrameStateCombine::IsOutputIgnored () const [inline]
Definition at line 46 of file frame-states.h.
{ return parameter_ == kInvalidIndex; }
References kInvalidIndex, and parameter_.
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor(), and ConsumedOutputCount().
operator!=()
bool v8::internal::compiler::OutputFrameStateCombine::operator!= (OutputFrameStateCombine const & other) const [inline]
Definition at line 53 of file frame-states.h.
                                                              {
    return !(*this == other);
  }
operator==()
bool v8::internal::compiler::OutputFrameStateCombine::operator== (OutputFrameStateCombine const & other) const [inline]
Definition at line 50 of file frame-states.h.
                                                              {
    return parameter_ == other.parameter_;
  }
References parameter_.
PokeAt()
static OutputFrameStateCombine v8::internal::compiler::OutputFrameStateCombine::PokeAt (size_t index) [inline], [static]
Definition at line 37 of file frame-states.h.
                                                      {
    return OutputFrameStateCombine(index);
  }
References v8::internal::index, and OutputFrameStateCombine().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::BindAccumulator(), v8::internal::compiler::BytecodeGraphBuilder::Environment::BindRegister(), v8::internal::compiler::BytecodeGraphBuilder::Environment::BindRegistersToProjections(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct().
Friends And Related Function Documentation
hash_value
size_t hash_value (OutputFrameStateCombine const & sc) [friend]
Definition at line 25 of file frame-states.cc.
                                                     {
  return base::hash_value(sc.parameter_);
}
operator<<
std::ostream& operator<< (std::ostream & os, OutputFrameStateCombine const & sc) [friend]
Definition at line 29 of file frame-states.cc.
                                                                          {
  if (sc.parameter_ == OutputFrameStateCombine::kInvalidIndex)
    return os << "Ignore";
  return os << "PokeAt(" << sc.parameter_ << ")";
}
Member Data Documentation
kInvalidIndex
const size_t v8::internal::compiler::OutputFrameStateCombine::kInvalidIndex = SIZE_MAX [static]
Definition at line 32 of file frame-states.h.
Referenced by GetOffsetToPokeAt(), Ignore(), and IsOutputIgnored().
parameter_
size_t const v8::internal::compiler::OutputFrameStateCombine::parameter_ [private]
Definition at line 64 of file frame-states.h.
Referenced by GetOffsetToPokeAt(), IsOutputIgnored(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/frame-states.h