v8::internal::compiler::turboshaft::SaturatedUint8 Class Reference
#include <operations.h>
Public Member Functions
SaturatedUint8 ()=default
void Incr ()
void Decr ()
void SetToZero ()
void SetToOne ()
bool IsZero () const
bool IsOne () const
bool IsSaturated () const
uint8_t Get () const
SaturatedUint8 & operator+= (const SaturatedUint8 &other)
Static Public Member Functions
static SaturatedUint8 FromSize (size_t value)
Private Member Functions
SaturatedUint8 (uint8_t val)
Private Attributes
uint8_t val = 0
Static Private Attributes
static constexpr uint8_t kMax = std::numeric_limits<uint8_t>::max()
Detailed Description
Definition at line 868 of file operations.h.
Constructor & Destructor Documentation
SaturatedUint8() [1/2]
v8::internal::compiler::turboshaft::SaturatedUint8::SaturatedUint8 () [default]
SaturatedUint8() [2/2]
v8::internal::compiler::turboshaft::SaturatedUint8::SaturatedUint8 (uint8_t val) [inline], [explicit], [private]
Definition at line 904 of file operations.h.
: val(val) {}
Member Function Documentation
Decr()
void v8::internal::compiler::turboshaft::SaturatedUint8::Decr () [inline]
Definition at line 877 of file operations.h.
              {
    if (V8_LIKELY(val != 0 && val != kMax)) {
      val--;
    }
  }
References v8::internal::kMax, and V8_LIKELY.
Referenced by v8::internal::compiler::turboshaft::Graph::DecrementInputUses().
FromSize()
static SaturatedUint8 v8::internal::compiler::turboshaft::SaturatedUint8::FromSize (size_t value) [inline], [static]
Definition at line 898 of file operations.h.
                                               {
    uint8_t val = static_cast<uint8_t>(std::min<size_t>(value, kMax));
    return SaturatedUint8{val};
  }
References v8::internal::kMax, and v8::internal::value.
Get()
uint8_t v8::internal::compiler::turboshaft::SaturatedUint8::Get () const [inline]
Definition at line 889 of file operations.h.
{ return val; }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::compiler::InstructionSelector::IsOnlyUserOfNodeInSameBlock(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::RecordAllocateUse(), and v8::internal::compiler::turboshaft::UseMap::UseMap().
Incr()
void v8::internal::compiler::turboshaft::SaturatedUint8::Incr () [inline]
Definition at line 872 of file operations.h.
              {
    if (V8_LIKELY(val != kMax)) {
      val++;
    }
  }
References v8::internal::kMax, and V8_LIKELY.
Referenced by v8::internal::compiler::turboshaft::Graph::IncrementInputUses().
IsOne()
bool v8::internal::compiler::turboshaft::SaturatedUint8::IsOne () const [inline]
Definition at line 887 of file operations.h.
{ return val == 1; }
Referenced by v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddBinaryOp(), v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddUnaryOp(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), and v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond().
IsSaturated()
bool v8::internal::compiler::turboshaft::SaturatedUint8::IsSaturated () const [inline]
Definition at line 888 of file operations.h.
{ return val == kMax; }
References v8::internal::kMax.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), and v8::internal::compiler::turboshaft::UseMap::UseMap().
IsZero()
bool v8::internal::compiler::turboshaft::SaturatedUint8::IsZero () const [inline]
Definition at line 886 of file operations.h.
{ return val == 0; }
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
operator+=()
SaturatedUint8& v8::internal::compiler::turboshaft::SaturatedUint8::operator+= (const SaturatedUint8 & other) [inline]
Definition at line 891 of file operations.h.
                                                          {
    uint32_t sum = val;
    sum += other.val;
    val = static_cast<uint8_t>(std::min<uint32_t>(sum, kMax));
    return *this;
  }
References v8::internal::kMax, and val.
SetToOne()
void v8::internal::compiler::turboshaft::SaturatedUint8::SetToOne () [inline]
Definition at line 884 of file operations.h.
{ val = 1; }
SetToZero()
void v8::internal::compiler::turboshaft::SaturatedUint8::SetToZero () [inline]
Definition at line 883 of file operations.h.
{ val = 0; }
Member Data Documentation
kMax
constexpr uint8_t v8::internal::compiler::turboshaft::SaturatedUint8::kMax = std::numeric_limits<uint8_t>::max() [static], [constexpr], [private]
Definition at line 906 of file operations.h.
val
uint8_t v8::internal::compiler::turboshaft::SaturatedUint8::val = 0 [private]
Definition at line 905 of file operations.h.
Referenced by operator+=().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h