v8::Int32 Class Reference
A JavaScript value representing a 32-bit signed integer.
#include <v8-primitive.h>
Public Member Functions
int32_t Value () const
Static Public Member Functions
static Int32 * Cast (v8::Data *data)
Private Member Functions
Int32 ()
Static Private Member Functions
static void CheckCast (v8::Data *that)
Detailed Description
A JavaScript value representing a 32-bit signed integer.
Definition at line 887 of file v8-primitive.h.
Constructor & Destructor Documentation
Int32()
v8::Int32::Int32 () [private]
Member Function Documentation
Cast()
static Int32* v8::Int32::Cast (v8::Data * data) [inline], [static]
Definition at line 890 of file v8-primitive.h.
                                             {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<Int32*>(data);
  }
CheckCast()
void v8::Int32::CheckCast (v8::Data * that) [static], [private]
Definition at line 3940 of file api.cc.
                                    {
  Utils::ApiCheck(Value::Cast(that)->IsInt32(), "v8::Int32::Cast",
                  "Value is not a 32-bit signed integer");
}
References v8::Utils::ApiCheck(), and v8::Value::Cast().
Value()
int32_t v8::Int32::Value () const
Definition at line 6201 of file api.cc.
                           {
  auto obj = *Utils::OpenDirectHandle(this);
  if (i::IsSmi(obj)) {
    return i::Smi::ToInt(obj);
  } else {
    return static_cast<int32_t>(i::Object::NumberValue(obj));
  }
}
References v8::internal::IsSmi(), v8::internal::Object::NumberValue(), v8::Utils::OpenDirectHandle(), and v8::internal::Smi::ToInt().
Referenced by v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), and v8_inspector::clientMirror().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc