v8::internal::Symbol Class Reference
#include <name.h>
Public Types
using IsPrivateBit = base::BitField< bool, 0, 1 >
using IsWellKnownSymbolBit = IsPrivateBit::Next< bool, 1 >
using IsInPublicSymbolTableBit = IsWellKnownSymbolBit::Next< bool, 1 >
using IsInterestingSymbolBit = IsInPublicSymbolTableBit::Next< bool, 1 >
using IsPrivateNameBit = IsInterestingSymbolBit::Next< bool, 1 >
using IsPrivateBrandBit = IsPrivateNameBit::Next< bool, 1 >
Public Member Functions
Tagged< PrimitiveHeapObject > description () const
void set_description (Tagged< PrimitiveHeapObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
bool is_private () const
void set_is_private (bool value)
bool is_well_known_symbol () const
void set_is_well_known_symbol (bool value)
bool is_interesting_symbol () const
void set_is_interesting_symbol (bool value)
bool is_in_public_symbol_table () const
void set_is_in_public_symbol_table (bool value)
bool is_private_name () const
void set_is_private_name ()
bool is_private_brand () const
void set_is_private_brand ()
void SymbolShortPrint (std::ostream &os)
Private Member Functions
uint32_t flags () const
void set_flags (uint32_t value)
const char * PrivateSymbolToName () const
Private Attributes
uint32_t flags_
TaggedMember< PrimitiveHeapObject > description_
Friends
class Factory
struct ObjectTraits< Symbol >
struct OffsetsForDebug
class V8HeapExplorer
class CodeStubAssembler
class maglev::MaglevAssembler
class TorqueGeneratedSymbolAsserts
class Name
Additional Inherited Members
Detailed Description
Definition at line 248 of file name.h.
Member Typedef Documentation
IsInPublicSymbolTableBit
using v8::internal::Symbol::IsInPublicSymbolTableBit = IsWellKnownSymbolBit::Next<bool, 1>
Definition at line 252 of file name.h.
IsInterestingSymbolBit
using v8::internal::Symbol::IsInterestingSymbolBit = IsInPublicSymbolTableBit::Next<bool, 1>
Definition at line 253 of file name.h.
IsPrivateBit
using v8::internal::Symbol::IsPrivateBit = base::BitField<bool, 0, 1>
Definition at line 250 of file name.h.
IsPrivateBrandBit
using v8::internal::Symbol::IsPrivateBrandBit = IsPrivateNameBit::Next<bool, 1>
Definition at line 255 of file name.h.
IsPrivateNameBit
using v8::internal::Symbol::IsPrivateNameBit = IsInterestingSymbolBit::Next<bool, 1>
Definition at line 254 of file name.h.
IsWellKnownSymbolBit
using v8::internal::Symbol::IsWellKnownSymbolBit = IsPrivateBit::Next<bool, 1>
Definition at line 251 of file name.h.
Member Function Documentation
description()
Tagged< PrimitiveHeapObject > v8::internal::Symbol::description () const [inline]
Definition at line 25 of file name-inl.h.
                                                      {
  return description_.load();
}
References description_.
flags()
uint32_t v8::internal::Symbol::flags () const [inline], [private]
Definition at line 319 of file name.h.
{ return flags_; }
References flags_.
Referenced by is_private_name(), and set_is_private_name().
is_in_public_symbol_table()
bool v8::internal::Symbol::is_in_public_symbol_table () const [inline]
is_interesting_symbol()
bool v8::internal::Symbol::is_interesting_symbol () const [inline]
is_private()
bool v8::internal::Symbol::is_private () const [inline]
Referenced by is_private_name().
is_private_brand()
bool v8::internal::Symbol::is_private_brand () const [inline]
is_private_name()
bool v8::internal::Symbol::is_private_name () const [inline]
Definition at line 54 of file name-inl.h.
                                   {
  bool value = Symbol::IsPrivateNameBit::decode(flags());
  DCHECK_IMPLIES(value, is_private());
  return value;
}
References DCHECK_IMPLIES, v8::base::BitField< T, shift, size, U >::decode(), flags(), is_private(), and v8::internal::value.
is_well_known_symbol()
bool v8::internal::Symbol::is_well_known_symbol () const [inline]
PrivateSymbolToName()
const char * v8::internal::Symbol::PrivateSymbolToName () const [private]
Definition at line 5015 of file objects.cc.
                                              {
  ReadOnlyRoots roots = GetReadOnlyRoots();
#define SYMBOL_CHECK_AND_PRINT(_, name) \
  if (this == roots.name()) return #name;
  PRIVATE_SYMBOL_LIST_GENERATOR(SYMBOL_CHECK_AND_PRINT, /* not used */)
#undef SYMBOL_CHECK_AND_PRINT
  return "UNKNOWN";
}
References v8::internal::GetReadOnlyRoots(), PRIVATE_SYMBOL_LIST_GENERATOR, and SYMBOL_CHECK_AND_PRINT.
set_description()
void v8::internal::Symbol::set_description (Tagged< PrimitiveHeapObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 28 of file name-inl.h.
                                                    {
  SLOW_DCHECK(IsString(value) || IsUndefined(value));
  description_.store(this, value, mode);
}
References description_, mode(), SLOW_DCHECK, and v8::internal::value.
set_flags()
void v8::internal::Symbol::set_flags (uint32_t value) [inline], [private]
Definition at line 320 of file name.h.
{ flags_ = value; }
References flags_, and v8::internal::value.
Referenced by set_is_private_name().
set_is_in_public_symbol_table()
void v8::internal::Symbol::set_is_in_public_symbol_table (bool value) [inline]
set_is_interesting_symbol()
void v8::internal::Symbol::set_is_interesting_symbol (bool value) [inline]
set_is_private()
void v8::internal::Symbol::set_is_private (bool value) [inline]
set_is_private_brand()
void v8::internal::Symbol::set_is_private_brand () [inline]
set_is_private_name()
void v8::internal::Symbol::set_is_private_name () [inline]
Definition at line 60 of file name-inl.h.
                                 {
  // TODO(gsathya): Re-order the bits to have these next to each other
  // and just do the bit shifts once.
  set_flags(Symbol::IsPrivateBit::update(flags(), true));
  set_flags(Symbol::IsPrivateNameBit::update(flags(), true));
}
References flags(), set_flags(), and v8::base::BitField< T, shift, size, U >::update().
set_is_well_known_symbol()
void v8::internal::Symbol::set_is_well_known_symbol (bool value) [inline]
SymbolShortPrint()
void v8::internal::Symbol::SymbolShortPrint (std::ostream & os)
Definition at line 3978 of file objects-printer.cc.
                                            {
  os << "<Symbol:";
  if (!IsUndefined(description())) {
    os << " ";
    Tagged<String> description_as_string = Cast<String>(description());
    description_as_string->PrintUC16(os, 0, description_as_string->length());
  } else {
    os << " (" << PrivateSymbolToName() << ")";
  }
  os << ">";
}
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 312 of file name.h.
Factory
friend class Factory [friend]
Definition at line 308 of file name.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 313 of file name.h.
Name
friend class Name [friend]
Definition at line 317 of file name.h.
ObjectTraits< Symbol >
friend struct ObjectTraits< Symbol > [friend]
Definition at line 308 of file name.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 310 of file name.h.
TorqueGeneratedSymbolAsserts
friend class TorqueGeneratedSymbolAsserts [friend]
Definition at line 314 of file name.h.
V8HeapExplorer
friend class V8HeapExplorer [friend]
Definition at line 311 of file name.h.
Member Data Documentation
description_
TaggedMember<PrimitiveHeapObject> v8::internal::Symbol::description_ [private]
Definition at line 327 of file name.h.
Referenced by description(), and set_description().
flags_
uint32_t v8::internal::Symbol::flags_ [private]
Definition at line 324 of file name.h.
Referenced by flags(), and set_flags().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/name.h
/mnt/V8SourceCode/src/diagnostics/objects-printer.cc
/mnt/V8SourceCode/src/objects/name-inl.h
/mnt/V8SourceCode/src/objects/objects.cc