v8::internal::Genesis::ExtensionStates Class Reference
Public Member Functions
ExtensionStates ()
ExtensionStates (const ExtensionStates &)=delete
ExtensionStates & operator= (const ExtensionStates &)=delete
ExtensionTraversalState get_state (RegisteredExtension *extension)
void set_state (RegisteredExtension *extension, ExtensionTraversalState state)
Private Attributes
base::HashMap map_
Detailed Description
Definition at line 284 of file bootstrapper.cc.
Constructor & Destructor Documentation
ExtensionStates() [1/2]
v8::internal::Genesis::ExtensionStates::ExtensionStates ()
Definition at line 6550 of file bootstrapper.cc.
: map_(8) {}
ExtensionStates() [2/2]
v8::internal::Genesis::ExtensionStates::ExtensionStates (const ExtensionStates &) [delete]
Member Function Documentation
get_state()
Genesis::ExtensionTraversalState v8::internal::Genesis::ExtensionStates::get_state (RegisteredExtension * extension)
Definition at line 6552 of file bootstrapper.cc.
                                    {
  base::HashMap::Entry* entry = map_.Lookup(extension, Hash(extension));
  if (entry == nullptr) {
    return UNVISITED;
  }
  return static_cast<ExtensionTraversalState>(
      reinterpret_cast<intptr_t>(entry->value));
}
References v8::internal::Hash(), and v8::internal::Genesis::UNVISITED.
Referenced by v8::internal::Genesis::InstallExtension().
operator=()
ExtensionStates& v8::internal::Genesis::ExtensionStates::operator= (const ExtensionStates &) [delete]
set_state()
void v8::internal::Genesis::ExtensionStates::set_state (RegisteredExtension * extension, ExtensionTraversalState state)
Definition at line 6562 of file bootstrapper.cc.
                                                                        {
  map_.LookupOrInsert(extension, Hash(extension))->value =
      reinterpret_cast<void*>(static_cast<intptr_t>(state));
}
References v8::internal::Hash().
Referenced by v8::internal::Genesis::InstallExtension().
Member Data Documentation
map_
base::HashMap v8::internal::Genesis::ExtensionStates::map_ [private]
Definition at line 294 of file bootstrapper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/init/bootstrapper.cc