v8::internal::WeakFixedArray Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Static Public Member Functions
template<class IsolateT >
static Handle< WeakFixedArray > New (IsolateT *isolate, int capacity, AllocationType allocation=AllocationType::kYoung, MaybeDirectHandle< Object > initial_value={})
Private Types
using Super = TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >
Additional Inherited Members
Detailed Description
Definition at line 506 of file fixed-array.h.
Member Typedef Documentation
Super
using v8::internal::WeakFixedArray::Super = TaggedArrayBase<WeakFixedArray, WeakFixedArrayShape> [private]
Definition at line 508 of file fixed-array.h.
Member Function Documentation
New()
template<class IsolateT >
Handle< WeakFixedArray > v8::internal::WeakFixedArray::New (IsolateT * isolate, int capacity, AllocationType allocation = AllocationType::kYoung, MaybeDirectHandle< Object > initial_value = {}) [inline], [static]
Definition at line 624 of file fixed-array-inl.h.
                                             {
  CHECK_LE(static_cast<unsigned>(capacity), kMaxCapacity);
  if (V8_UNLIKELY(capacity == 0)) {
    return isolate->factory()->empty_weak_fixed_array();
  }
  std::optional<DisallowGarbageCollection> no_gc;
  Handle<WeakFixedArray> result =
      Cast<WeakFixedArray>(Allocate(isolate, capacity, &no_gc, allocation));
  ReadOnlyRoots roots{isolate};
  MemsetTagged((*result)->RawFieldOfFirstElement(),
               initial_value.is_null() ? roots.undefined_value()
                                       : *initial_value.ToHandleChecked(),
               capacity);
  return result;
}
References v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::Allocate(), CHECK_LE, v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::kMaxCapacity, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), and V8_UNLIKELY.
Referenced by v8::internal::TransitionArray::CreateSideStepTransitions(), v8::internal::wasm::WasmExportWrapperCache::New(), v8::internal::FactoryBase< Impl >::NewWeakFixedArray(), and v8::internal::wasm::TypeCanonicalizer::PrepareForCanonicalTypeId().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h