v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject > Class Template Reference
Public Member Functions
JSObjectWalkVisitor (ContextObject *site_context)
V8_WARN_UNUSED_RESULT MaybeHandle< JSObject > StructureWalk (Handle< JSObject > object)
Protected Member Functions
V8_WARN_UNUSED_RESULT MaybeHandle< JSObject > VisitElementOrProperty (DirectHandle< JSObject > object, Handle< JSObject > value)
ContextObject * site_context ()
Isolate * isolate ()
Private Attributes
ContextObject * site_context_
Detailed Description
template<class ContextObject>
class v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >
Definition at line 35 of file runtime-literals.cc.
Constructor & Destructor Documentation
JSObjectWalkVisitor()
template<class ContextObject >
v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::JSObjectWalkVisitor (ContextObject * site_context) [inline], [explicit]
Definition at line 37 of file runtime-literals.cc.
      : site_context_(site_context) {}
Member Function Documentation
isolate()
template<class ContextObject >
Isolate* v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::isolate () [inline], [protected]
Definition at line 58 of file runtime-literals.cc.
{ return site_context()->isolate(); }
References v8::internal::Factory::isolate().
site_context()
template<class ContextObject >
ContextObject* v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::site_context () [inline], [protected]
Definition at line 57 of file runtime-literals.cc.
{ return site_context_; }
StructureWalk()
template<class ContextObject >
MaybeHandle< JSObject > v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk (Handle< JSObject > object)
Definition at line 65 of file runtime-literals.cc.
                             {
  Isolate* isolate = this->isolate();
  bool copying = ContextObject::kCopying;
  {
    StackLimitCheck check(isolate);
    if (check.HasOverflowed()) {
      isolate->StackOverflow();
      return MaybeHandle<JSObject>();
    }
  }
  if (object->map(isolate)->is_deprecated()) {
    base::MutexGuard mutex_guard(isolate->boilerplate_migration_access());
    JSObject::MigrateInstance(isolate, object);
  }
  Handle<JSObject> copy;
  if (copying) {
    // JSFunction objects are not allowed to be in normal boilerplates at all.
    DCHECK(!IsJSFunction(*object, isolate));
    DirectHandle<AllocationSite> site_to_pass;
    if (site_context()->ShouldCreateMemento(object)) {
      site_to_pass = site_context()->current();
    }
    copy = isolate->factory()->CopyJSObjectWithAllocationSite(object,
                                                              site_to_pass);
  } else {
    copy = object;
  }
  DCHECK(copying || copy.is_identical_to(object));
  HandleScope scope(isolate);
  // Deep copy own properties. Arrays only have 1 property "length".
  if (!IsJSArray(*copy, isolate)) {
    if (copy->HasFastProperties(isolate)) {
      DirectHandle<DescriptorArray> descriptors(
          copy->map(isolate)->instance_descriptors(isolate), isolate);
      for (InternalIndex i : copy->map(isolate)->IterateOwnDescriptors()) {
        PropertyDetails details = descriptors->GetDetails(i);
        DCHECK_EQ(PropertyLocation::kField, details.location());
        DCHECK_EQ(PropertyKind::kData, details.kind());
        FieldIndex index = FieldIndex::ForPropertyIndex(
            copy->map(isolate), details.field_index(),
            details.representation());
        Tagged<Object> raw = copy->RawFastPropertyAt(isolate, index);
        if (IsJSObject(raw, isolate)) {
          Handle<JSObject> value(Cast<JSObject>(raw), isolate);
          ASSIGN_RETURN_ON_EXCEPTION(isolate, value,
                                     VisitElementOrProperty(copy, value));
          if (copying) copy->FastPropertyAtPut(index, *value);
        } else if (copying && details.representation().IsDouble()) {
          uint64_t double_value = Cast<HeapNumber>(raw)->value_as_bits();
          auto value = isolate->factory()->NewHeapNumberFromBits(double_value);
          copy->FastPropertyAtPut(index, *value);
        }
      }
    } else {
      if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
        DirectHandle<SwissNameDictionary> dict(
            copy->property_dictionary_swiss(isolate), isolate);
        for (InternalIndex i : dict->IterateEntries()) {
          Tagged<Object> raw = dict->ValueAt(i);
          if (!IsJSObject(raw, isolate)) continue;
          DCHECK(IsName(dict->KeyAt(i)));
          Handle<JSObject> value(Cast<JSObject>(raw), isolate);
          ASSIGN_RETURN_ON_EXCEPTION(isolate, value,
                                     VisitElementOrProperty(copy, value));
          if (copying) dict->ValueAtPut(i, *value);
        }
      } else {
        DirectHandle<NameDictionary> dict(copy->property_dictionary(isolate),
                                          isolate);
        for (InternalIndex i : dict->IterateEntries()) {
          Tagged<Object> raw = dict->ValueAt(isolate, i);
          if (!IsJSObject(raw, isolate)) continue;
          DCHECK(IsName(dict->KeyAt(isolate, i)));
          Handle<JSObject> value(Cast<JSObject>(raw), isolate);
          ASSIGN_RETURN_ON_EXCEPTION(isolate, value,
                                     VisitElementOrProperty(copy, value));
          if (copying) dict->ValueAtPut(i, *value);
        }
      }
    }
    // Assume non-arrays don't end up having elements.
    if (copy->elements(isolate)->length() == 0) return copy;
  }
  // Deep copy own elements.
  switch (copy->GetElementsKind(isolate)) {
    case PACKED_ELEMENTS:
    case PACKED_FROZEN_ELEMENTS:
    case PACKED_SEALED_ELEMENTS:
    case PACKED_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_FROZEN_ELEMENTS:
    case HOLEY_SEALED_ELEMENTS:
    case HOLEY_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_ELEMENTS:
    case SHARED_ARRAY_ELEMENTS: {
      DirectHandle<FixedArray> elements(
          Cast<FixedArray>(copy->elements(isolate)), isolate);
      if (elements->map() == ReadOnlyRoots(isolate).fixed_cow_array_map()) {
#ifdef DEBUG
        for (int i = 0; i < elements->length(); i++) {
          DCHECK(!IsJSObject(elements->get(i)));
        }
#endif
      } else {
        for (int i = 0; i < elements->length(); i++) {
          Tagged<Object> raw = elements->get(i);
          if (!IsJSObject(raw, isolate)) continue;
          Handle<JSObject> value(Cast<JSObject>(raw), isolate);
          ASSIGN_RETURN_ON_EXCEPTION(isolate, value,
                                     VisitElementOrProperty(copy, value));
          if (copying) elements->set(i, *value);
        }
      }
      break;
    }
    case DICTIONARY_ELEMENTS: {
      DirectHandle<NumberDictionary> element_dictionary(
          copy->element_dictionary(isolate), isolate);
      for (InternalIndex i : element_dictionary->IterateEntries()) {
        Tagged<Object> raw = element_dictionary->ValueAt(isolate, i);
        if (!IsJSObject(raw, isolate)) continue;
        Handle<JSObject> value(Cast<JSObject>(raw), isolate);
        ASSIGN_RETURN_ON_EXCEPTION(isolate, value,
                                   VisitElementOrProperty(copy, value));
        if (copying) element_dictionary->ValueAtPut(i, *value);
      }
      break;
    }
    case FAST_SLOPPY_ARGUMENTS_ELEMENTS:
    case SLOW_SLOPPY_ARGUMENTS_ELEMENTS:
      UNIMPLEMENTED();
      break;
    case FAST_STRING_WRAPPER_ELEMENTS:
    case SLOW_STRING_WRAPPER_ELEMENTS:
    case WASM_ARRAY_ELEMENTS:
      UNREACHABLE();
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) case TYPE##_ELEMENTS:
      TYPED_ARRAYS(TYPED_ARRAY_CASE)
      RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
      // Typed elements cannot be created using an object literal.
      UNREACHABLE();
    case PACKED_SMI_ELEMENTS:
    case HOLEY_SMI_ELEMENTS:
    case PACKED_DOUBLE_ELEMENTS:
    case HOLEY_DOUBLE_ELEMENTS:
    case NO_ELEMENTS:
      // No contained objects, nothing to do.
      break;
  }
  return copy;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::boilerplate_migration_access(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DICTIONARY_ELEMENTS, v8::internal::element_dictionary, v8::internal::Isolate::factory(), v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::PropertyDetails::field_index(), v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::StackLimitCheck::HasOverflowed(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::index, v8::internal::HandleBase::is_identical_to(), v8::internal::Representation::IsDouble(), v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::JSObject::MigrateInstance(), v8::internal::FactoryBase< Impl >::NewHeapNumberFromBits(), v8::internal::NO_ELEMENTS, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RAB_GSAB_TYPED_ARRAYS, v8::internal::PropertyDetails::representation(), v8::internal::SHARED_ARRAY_ELEMENTS, v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, v8::internal::Isolate::StackOverflow(), TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::internal::value, and v8::internal::WASM_ARRAY_ELEMENTS.
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::DeepCopy(), and v8::internal::anonymous_namespace{runtime-literals.cc}::DeepWalk().
VisitElementOrProperty()
template<class ContextObject >
V8_WARN_UNUSED_RESULT MaybeHandle<JSObject> v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::VisitElementOrProperty (DirectHandle< JSObject > object, Handle< JSObject > value) [inline], [protected]
Definition at line 44 of file runtime-literals.cc.
                                                             {
    // Dont create allocation sites for nested object literals
    if (!IsJSArray(*value)) {
      return StructureWalk(value);
    }
    DirectHandle<AllocationSite> current_site = site_context()->EnterNewScope();
    MaybeHandle<JSObject> copy_of_value = StructureWalk(value);
    site_context()->ExitScope(current_site, value);
    return copy_of_value;
  }
References v8::internal::value.
Member Data Documentation
site_context_
template<class ContextObject >
ContextObject* v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::site_context_ [private]
Definition at line 61 of file runtime-literals.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/runtime/runtime-literals.cc