v8::internal::JavaScriptBuiltinContinuationFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
Tagged< JSFunction > function () const override
int ComputeParametersCount () const override
intptr_t GetSPToFPDelta () const
Tagged< Object > context () const override
Static Public Member Functions
static JavaScriptBuiltinContinuationFrame * cast (StackFrame *frame)
Protected Member Functions
JavaScriptBuiltinContinuationFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1562 of file frames.h.
Constructor & Destructor Documentation
JavaScriptBuiltinContinuationFrame()
v8::internal::JavaScriptBuiltinContinuationFrame::JavaScriptBuiltinContinuationFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 375 of file frames-inl.h.
    : TypedFrameWithJSLinkage(iterator) {}
Member Function Documentation
cast()
static JavaScriptBuiltinContinuationFrame* v8::internal::JavaScriptBuiltinContinuationFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1566 of file frames.h.
                                                                     {
    DCHECK(frame->is_javascript_builtin_continuation());
    return static_cast<JavaScriptBuiltinContinuationFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_javascript_builtin_continuation().
ComputeParametersCount()
int v8::internal::JavaScriptBuiltinContinuationFrame::ComputeParametersCount () const [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 2653 of file frames.cc.
                                                                     {
  // Assert that the first allocatable register is also the argument count
  // register.
  DCHECK_EQ(RegisterConfiguration::Default()->GetAllocatableGeneralCode(0),
            kJavaScriptCallArgCountRegister.code());
  Tagged<Object> argc_object(
      Memory<Address>(fp() + BuiltinContinuationFrameConstants::kArgCOffset));
  return Smi::ToInt(argc_object) - kJSArgcReceiverSlots;
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), DCHECK_EQ, v8::internal::RegisterConfiguration::Default(), v8::internal::StackFrame::fp(), v8::internal::BuiltinContinuationFrameConstants::kArgCOffset, v8::internal::kJavaScriptCallArgCountRegister, v8::internal::kJSArgcReceiverSlots, and v8::internal::Smi::ToInt().
Referenced by v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::SetException().
context()
Tagged< Object > v8::internal::JavaScriptBuiltinContinuationFrame::context () const [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 2670 of file frames.cc.
                                                                 {
  return Tagged<Object>(Memory<Address>(
      fp() + BuiltinContinuationFrameConstants::kBuiltinContextOffset));
}
References v8::internal::StackFrame::fp(), v8::internal::BuiltinContinuationFrameConstants::kBuiltinContextOffset, and v8::internal::Tagged< Object >.
function()
Tagged< JSFunction > v8::internal::JavaScriptBuiltinContinuationFrame::function () const [override], [virtual]
Implements v8::internal::CommonFrameWithJSLinkage.
Definition at line 2648 of file frames.cc.
                                                                      {
  const int offset = BuiltinContinuationFrameConstants::kFunctionOffset;
  return Cast<JSFunction>(Tagged<Object>(base::Memory<Address>(fp() + offset)));
}
References v8::internal::StackFrame::fp(), and v8::internal::BuiltinContinuationFrameConstants::kFunctionOffset.
GetSPToFPDelta()
intptr_t v8::internal::JavaScriptBuiltinContinuationFrame::GetSPToFPDelta () const
Definition at line 2663 of file frames.cc.
                                                                  {
  Address height_slot =
      fp() + BuiltinContinuationFrameConstants::kFrameSPtoFPDeltaAtDeoptimize;
  intptr_t height = Smi::ToInt(Tagged<Smi>(Memory<Address>(height_slot)));
  return height;
}
References v8::internal::StackFrame::fp(), v8::internal::BuiltinContinuationFrameConstants::kFrameSPtoFPDeltaAtDeoptimize, and v8::internal::Smi::ToInt().
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
type()
Type v8::internal::JavaScriptBuiltinContinuationFrame::type () const [inline], [override], [virtual]
Implements v8::internal::StackFrame.
Reimplemented in v8::internal::JavaScriptBuiltinContinuationWithCatchFrame.
Definition at line 1564 of file frames.h.
{ return JAVASCRIPT_BUILTIN_CONTINUATION; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1582 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc