v8::internal::HeapVisitor< ConcreteVisitor > Class Template Reference
#include <heap-visitor.h>
Public Member Functions
HeapVisitor (LocalIsolate *isolate)
HeapVisitor (Isolate *isolate)
HeapVisitor (Heap *heap)
Protected Member Functions
size_t Visit (Tagged< Map > map, Tagged< HeapObject > object, MaybeObjectSize maybe_object_size)
template<VisitorId visitor_id>
void VisitMapPointerIfNeeded (Tagged< HeapObject > host)
ConcreteVisitor * concrete_visitor ()
const ConcreteVisitor * concrete_visitor () const
size_t VisitShortcutCandidate (Tagged< Map > map, Tagged< ConsString > object, MaybeObjectSize maybe_object_size)
size_t VisitJSObjectFast (Tagged< Map > map, Tagged< JSObject > object, MaybeObjectSize maybe_object_size)
size_t VisitJSApiObject (Tagged< Map > map, Tagged< JSObject > object, MaybeObjectSize maybe_object_size)
size_t VisitCppHeapExternalObject (Tagged< Map > map, Tagged< CppHeapExternalObject > object, MaybeObjectSize maybe_object_size)
size_t VisitStruct (Tagged< Map > map, Tagged< HeapObject > object, MaybeObjectSize maybe_object_size)
size_t VisitFiller (Tagged< Map > map, Tagged< HeapObject > object, MaybeObjectSize maybe_object_size)
size_t VisitFreeSpace (Tagged< Map > map, Tagged< FreeSpace > object, MaybeObjectSize maybe_object_size)
template<typename T , typename TBodyDescriptor = typename T::BodyDescriptor>
size_t VisitJSObjectSubclass (Tagged< Map > map, Tagged< T > object, MaybeObjectSize maybe_object_size)
template<VisitorId visitor_id, typename T , typename TBodyDescriptor = typename T::BodyDescriptor>
size_t VisitWithBodyDescriptor (Tagged< Map > map, Tagged< T > object, MaybeObjectSize maybe_object_size)
template<typename TSlot >
std::optional< Tagged< Object > > GetObjectFilterReadOnlyAndSmiFast (TSlot slot) const
Static Protected Member Functions
static constexpr bool ShouldVisitMapPointer ()
static constexpr bool ShouldVisitReadOnlyMapPointer ()
static constexpr bool CanEncounterFillerOrFreeSpace ()
static constexpr bool ShouldUseUncheckedCast ()
static constexpr bool EnableConcurrentVisitation ()
static constexpr bool UsePrecomputedObjectSize ()
static constexpr bool ShouldVisitFullJSObject ()
template<typename T >
static Tagged< T > Cast (Tagged< HeapObject > object, const Heap *heap)
Protected Attributes
const Heap * heap_
Detailed Description
template<typename ConcreteVisitor>
class v8::internal::HeapVisitor< ConcreteVisitor >
Definition at line 197 of file heap-visitor.h.
Constructor & Destructor Documentation
HeapVisitor() [1/3]
template<typename ConcreteVisitor >
v8::internal::HeapVisitor< ConcreteVisitor >::HeapVisitor (LocalIsolate * isolate) [inline], [explicit]
Definition at line 69 of file heap-visitor-inl.h.
    : ObjectVisitorWithCageBases(PtrComprCageBase(isolate->cage_base()),
                                 PtrComprCageBase(isolate->code_cage_base())),
HeapVisitor() [2/3]
template<typename ConcreteVisitor >
v8::internal::HeapVisitor< ConcreteVisitor >::HeapVisitor (Isolate * isolate) [inline], [explicit]
Definition at line 75 of file heap-visitor-inl.h.
    : ObjectVisitorWithCageBases(isolate), heap_(isolate->heap()) {}
HeapVisitor() [3/3]
template<typename ConcreteVisitor >
v8::internal::HeapVisitor< ConcreteVisitor >::HeapVisitor (Heap * heap) [inline], [explicit]
Definition at line 79 of file heap-visitor-inl.h.
    : ObjectVisitorWithCageBases(heap), heap_(heap) {}
Member Function Documentation
CanEncounterFillerOrFreeSpace()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::HeapVisitor< ConcreteVisitor >::CanEncounterFillerOrFreeSpace () [inline], [static], [constexpr], [protected]
Definition at line 227 of file heap-visitor.h.
                                                                  {
    return true;
  }
Cast()
template<typename ConcreteVisitor >
template<typename T >
Tagged< T > v8::internal::HeapVisitor< ConcreteVisitor >::Cast (Tagged< HeapObject > object, const Heap * heap) [inline], [static], [protected]
Definition at line 84 of file heap-visitor-inl.h.
                                                               {
  if constexpr (ConcreteVisitor::ShouldUseUncheckedCast()) {
    return i::UncheckedCast<T>(object);
  }
  return i::Cast<T>(object);
concrete_visitor() [1/2]
template<typename ConcreteVisitor >
ConcreteVisitor* v8::internal::HeapVisitor< ConcreteVisitor >::concrete_visitor () [inline], [protected]
Definition at line 249 of file heap-visitor.h.
                                      {
    return static_cast<ConcreteVisitor*>(this);
  }
concrete_visitor() [2/2]
template<typename ConcreteVisitor >
const ConcreteVisitor* v8::internal::HeapVisitor< ConcreteVisitor >::concrete_visitor () const [inline], [protected]
Definition at line 253 of file heap-visitor.h.
                                                  {
    return static_cast<const ConcreteVisitor*>(this);
  }
EnableConcurrentVisitation()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::HeapVisitor< ConcreteVisitor >::EnableConcurrentVisitation () [inline], [static], [constexpr], [protected]
Definition at line 236 of file heap-visitor.h.
{ return false; }
GetObjectFilterReadOnlyAndSmiFast()
template<typename ConcreteVisitor >
template<typename TSlot >
std::optional< Tagged< Object > > v8::internal::HeapVisitor< ConcreteVisitor >::GetObjectFilterReadOnlyAndSmiFast (TSlot slot) const [protected]
Definition at line 387 of file heap-visitor-inl.h.
                       : TBodyDescriptor::SizeOf(map, object);
  TBodyDescriptor::IterateBody(map, object, size, visitor);
  return size;
}
template <typename ConcreteVisitor>
Referenced by v8::internal::ScavengeVisitor::VisitPointersImpl().
ShouldUseUncheckedCast()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::HeapVisitor< ConcreteVisitor >::ShouldUseUncheckedCast () [inline], [static], [constexpr], [protected]
Definition at line 232 of file heap-visitor.h.
{ return false; }
ShouldVisitFullJSObject()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::HeapVisitor< ConcreteVisitor >::ShouldVisitFullJSObject () [inline], [static], [constexpr], [protected]
Definition at line 247 of file heap-visitor.h.
{ return false; }
ShouldVisitMapPointer()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::HeapVisitor< ConcreteVisitor >::ShouldVisitMapPointer () [inline], [static], [constexpr], [protected]
Definition at line 219 of file heap-visitor.h.
{ return true; }
ShouldVisitReadOnlyMapPointer()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::HeapVisitor< ConcreteVisitor >::ShouldVisitReadOnlyMapPointer () [inline], [static], [constexpr], [protected]
Definition at line 222 of file heap-visitor.h.
                                                                  {
    return true;
  }
UsePrecomputedObjectSize()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::HeapVisitor< ConcreteVisitor >::UsePrecomputedObjectSize () [inline], [static], [constexpr], [protected]
Definition at line 239 of file heap-visitor.h.
{ return false; }
Visit()
template<typename ConcreteVisitor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::Visit (Tagged< Map > map, Tagged< HeapObject > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 93 of file heap-visitor-inl.h.
{
  return Visit(object->map(cage_base()), object);
Referenced by v8::internal::Scavenger::IterateAndScavengePromotedObject(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::Scavenger::Process(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::ConcurrentMarking::RunMinorImpl(), v8::internal::EvacuateNewToOldSpacePageVisitor::Visit(), v8::internal::EvacuateRecordOnlyVisitor::Visit(), v8::internal::VisitObject(), v8::internal::VisitObjectBody(), and v8::internal::Scavenger::VisitPinnedObjects().
VisitCppHeapExternalObject()
template<typename ConcreteVisitor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitCppHeapExternalObject (Tagged< Map > map, Tagged< CppHeapExternalObject > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 292 of file heap-visitor-inl.h.
                                       {
  return static_cast<ConcreteVisitor*>(this)
      ->template VisitJSObjectSubclass<
          JSObject, JSAPIObjectWithEmbedderSlots::BodyDescriptor>(
          map, object, maybe_object_size);
}
template <typename ConcreteVisitor>
size_t HeapVisitor<ConcreteVisitor>::VisitCppHeapExternalObject(
    Tagged<Map> map, Tagged<CppHeapExternalObject> object,
VisitFiller()
template<typename ConcreteVisitor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitFiller (Tagged< Map > map, Tagged< HeapObject > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 247 of file heap-visitor-inl.h.
                                       {
  return static_cast<ConcreteVisitor*>(this)->VisitConsString(
      map, object, maybe_object_size);
}
template <typename ConcreteVisitor>
VisitFreeSpace()
template<typename ConcreteVisitor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitFreeSpace (Tagged< Map > map, Tagged< FreeSpace > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 261 of file heap-visitor-inl.h.
                                       {
  if constexpr (!ConcreteVisitor::CanEncounterFillerOrFreeSpace()) {
    UNREACHABLE();
  }
  ConcreteVisitor* visitor = static_cast<ConcreteVisitor*>(this);
  visitor->template VisitMapPointerIfNeeded<VisitorId::kVisitFiller>(object);
  return ConcreteVisitor::UsePrecomputedObjectSize()
             ? maybe_object_size.AssumeSize()
             : map->instance_size();
}
References v8::internal::UNREACHABLE().
VisitJSApiObject()
template<typename ConcreteVisitor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitJSApiObject (Tagged< Map > map, Tagged< JSObject > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 282 of file heap-visitor-inl.h.
                                       {
  return static_cast<ConcreteVisitor*>(this)
      ->template VisitJSObjectSubclass<JSObject, JSObject::FastBodyDescriptor>(
VisitJSObjectFast()
template<typename ConcreteVisitor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitJSObjectFast (Tagged< Map > map, Tagged< JSObject > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 273 of file heap-visitor-inl.h.
                                       {
  if constexpr (!ConcreteVisitor::CanEncounterFillerOrFreeSpace()) {
    UNREACHABLE();
  }
  ConcreteVisitor* visitor = static_cast<ConcreteVisitor*>(this);
VisitJSObjectSubclass()
template<typename ConcreteVisitor >
template<typename T , typename TBodyDescriptor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitJSObjectSubclass (Tagged< Map > map, Tagged< T > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 322 of file heap-visitor-inl.h.
                                       {
  ConcreteVisitor* visitor = static_cast<ConcreteVisitor*>(this);
  int size = ConcreteVisitor::UsePrecomputedObjectSize()
                 ? static_cast<int>(maybe_object_size.AssumeSize())
                 : map->instance_size();
  visitor->template VisitMapPointerIfNeeded<VisitorId::kVisitStruct>(object);
  StructBodyDescriptor::IterateBody(map, object, size, visitor);
  return size;
}
template <typename ConcreteVisitor>
template <typename T, typename TBodyDescriptor>
size_t HeapVisitor<ConcreteVisitor>::VisitJSObjectSubclass(
    Tagged<Map> map, Tagged<T> object, MaybeObjectSize maybe_object_size) {
  // JSObject types are subject to slack tracking. At the end of slack tracking
  // a Map's instance size is adjusted properly. Since this changes the instance
  // size, we cannot DCHECK that `SizeFromMap()` is consistent with
  // `TBodyDescriptor::SizeOf()` as that would require taking a snapshot of the
  // Map.
  ConcreteVisitor* visitor = static_cast<ConcreteVisitor*>(this);
  visitor->template VisitMapPointerIfNeeded<VisitorId::kVisitJSObject>(object);
  const size_t size = ConcreteVisitor::UsePrecomputedObjectSize()
                          ? maybe_object_size.AssumeSize()
                          : TBodyDescriptor::SizeOf(map, object);
  int visitation_size = static_cast<int>(size);
  if (!ConcreteVisitor::ShouldVisitFullJSObject()) {
    // It is important to visit only the used field and ignore the slack fields
    // because the slack fields may be trimmed concurrently and we don't want to
References v8::internal::MaybeObjectSize::AssumeSize(), v8::internal::SuffixRangeBodyDescriptor< start_offset >::IterateBody(), and size().
VisitMapPointerIfNeeded()
template<typename ConcreteVisitor >
template<VisitorId visitor_id>
void v8::internal::HeapVisitor< ConcreteVisitor >::VisitMapPointerIfNeeded (Tagged< HeapObject > host) [inline], [protected]
Definition at line 195 of file heap-visitor-inl.h.
                                                    {
      isolate->PushParamsAndDie(
          reinterpret_cast<void*>(object.ptr()),
          reinterpret_cast<void*>(map.ptr()),
          reinterpret_cast<void*>(static_cast<intptr_t>(map->visitor_id())));
    }
  }
  UNREACHABLE();
}
template <typename ConcreteVisitor>
template <VisitorId visitor_id>
VisitShortcutCandidate()
template<typename ConcreteVisitor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitShortcutCandidate (Tagged< Map > map, Tagged< ConsString > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 239 of file heap-visitor-inl.h.
                                         { \
    return static_cast<ConcreteVisitor*>(this) \
        ->template VisitJSObjectSubclass<TypeName, TypeName::BodyDescriptor>(\
            map, object, maybe_object_size); \
VisitStruct()
template<typename ConcreteVisitor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitStruct (Tagged< Map > map, Tagged< HeapObject > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 308 of file heap-visitor-inl.h.
          : CppHeapExternalObject::BodyDescriptor::SizeOf(map, object);
  visitor->template VisitMapPointerIfNeeded<
      VisitorId::kVisitCppHeapExternalObject>(object);
  CppHeapExternalObject::BodyDescriptor::IterateBody(
      map, object, static_cast<int>(size), visitor);
  return size;
}
VisitWithBodyDescriptor()
template<typename ConcreteVisitor >
template<VisitorId visitor_id, typename T , typename TBodyDescriptor >
size_t v8::internal::HeapVisitor< ConcreteVisitor >::VisitWithBodyDescriptor (Tagged< Map > map, Tagged< T > object, MaybeObjectSize maybe_object_size) [inline], [protected]
Definition at line 357 of file heap-visitor-inl.h.
                                                                          {
  // If you see the following DCHECK fail, then the size computation of
  // BodyDescriptor doesn't match the size return via obj.Size(). This is
  // problematic as the GC requires those sizes to match for accounting reasons.
  // The fix likely involves adding a padding field in the object definitions.
  //
  // We can only perform this check for types that do not support right trimming
  // when running concurrently. `RefineAllocatedBytesAfterSweeping()` ensures
  // that we only see sizes that get smaller during marking.
#ifdef DEBUG
  if (!SupportsRightTrim<visitor_id>() ||
      !ConcreteVisitor::EnableConcurrentVisitation()) {
    DCHECK_EQ(object->SizeFromMap(map), TBodyDescriptor::SizeOf(map, object));
Member Data Documentation
heap_
template<typename ConcreteVisitor >
const Heap* v8::internal::HeapVisitor< ConcreteVisitor >::heap_ [protected]
Definition at line 301 of file heap-visitor.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap-visitor.h
/mnt/V8SourceCode/src/heap/heap-visitor-inl.h