v8::internal::wasm::WasmCode Class Reference
#include <wasm-code-manager.h>
Public Types
enum Kind { kWasmFunction
, kWasmToCapiWrapper
, kWasmToJsWrapper
, kJumpTable
 }
enum FlushICache : bool { kFlushICache = true
, kNoFlushICache = false
 }
Public Member Functions
base::Vector< uint8_t > instructions () const
Address instruction_start () const
size_t instructions_size () const
base::Vector< const uint8_t > reloc_info () const
base::Vector< const uint8_t > source_positions () const
base::Vector< const uint8_t > inlining_positions () const
base::Vector< const uint8_t > deopt_data () const
int index () const
bool IsAnonymous () const
Kind kind () const
NativeModule * native_module () const
ExecutionTier tier () const
Address constant_pool () const
Address handler_table () const
int handler_table_size () const
Address code_comments () const
int code_comments_size () const
Address jump_table_info () const
int jump_table_info_size () const
bool has_jump_table_info () const
int constant_pool_offset () const
int safepoint_table_offset () const
int handler_table_offset () const
int code_comments_offset () const
int jump_table_info_offset () const
int unpadded_binary_size () const
int stack_slots () const
int ool_spills () const
uint64_t signature_hash () const
uint16_t first_tagged_parameter_slot () const
uint16_t num_tagged_parameter_slots () const
uint32_t raw_tagged_parameter_slots_for_serialization () const
bool is_liftoff () const
bool is_turbofan () const
bool contains (Address pc) const
bool is_inspectable () const
base::Vector< const uint8_t > protected_instructions_data () const
base::Vector< const trap_handler::ProtectedInstructionData > protected_instructions () const
bool IsProtectedInstruction (Address pc)
void Validate () const
void Print (const char *name=nullptr) const
void MaybePrint () const
void Disassemble (const char *name, std::ostream &os, Address current_pc=kNullAddress) const
void LogCode (Isolate *isolate, const char *source_url, int script_id) const
WasmCode (const WasmCode &)=delete
WasmCode & operator= (const WasmCode &)=delete
~WasmCode ()
void IncRef ()
bool IncRefIfNotDying ()
V8_WARN_UNUSED_RESULT bool DecRef ()
void DecRefOnLiveCode ()
V8_WARN_UNUSED_RESULT bool DecRefOnDeadCode ()
void DcheckRefCountIsOne ()
SourcePosition GetSourcePositionBefore (int code_offset)
int GetSourceOffsetBefore (int code_offset)
std::tuple< int, bool, SourcePosition > GetInliningPosition (int inlining_id) const
ForDebugging for_debugging () const
bool is_dying () const
bool frame_has_feedback_slot () const
size_t EstimateCurrentMemoryConsumption () const
std::string DebugName () const
Static Public Member Functions
static constexpr Builtin GetRecordWriteBuiltin (SaveFPRegsMode fp_mode)
static bool ShouldBeLogged (Isolate *isolate)
static void DecrementRefCount (base::Vector< WasmCode *const >)
static bool is_dying (uint32_t bit_field_value)
static uint32_t refcount (uint32_t bit_field_value)
Private Types
using KindField = base::BitField8< Kind, 0, 2 >
using ExecutionTierField = KindField::Next< ExecutionTier, 2 >
using ForDebuggingField = ExecutionTierField::Next< ForDebugging, 2 >
using FrameHasFeedbackSlotField = ForDebuggingField::Next< bool, 1 >
Private Member Functions
WasmCode (NativeModule *native_module, int index, base::Vector< uint8_t > instructions, int stack_slots, int ool_spills, uint32_t tagged_parameter_slots, int safepoint_table_offset, int handler_table_offset, int constant_pool_offset, int code_comments_offset, int jump_table_info_offset, int unpadded_binary_size, base::Vector< const uint8_t > protected_instructions_data, base::Vector< const uint8_t > reloc_info, base::Vector< const uint8_t > source_position_table, base::Vector< const uint8_t > inlining_positions, base::Vector< const uint8_t > deopt_data, Kind kind, ExecutionTier tier, ForDebugging for_debugging, uint64_t signature_hash, bool frame_has_feedback_slot=false)
std::unique_ptr< const uint8_t[]> ConcatenateBytes (std::initializer_list< base::Vector< const uint8_t >>)
int trap_handler_index () const
void set_trap_handler_index (int value)
bool has_trap_handler_index () const
void RegisterTrapHandlerData ()
V8_NOINLINE void DecRefOnPotentiallyDeadCode ()
Private Attributes
NativeModule *const native_module_ = nullptr
uint8_t *const instructions_
const uint64_t signature_hash_
std::unique_ptr< const uint8_t[]> meta_data_
const int instructions_size_
const int reloc_info_size_
const int source_positions_size_
const int inlining_positions_size_
const int deopt_data_size_
const int protected_instructions_size_
const int index_
const int constant_pool_offset_
const int stack_slots_
const int ool_spills_
const uint32_t tagged_parameter_slots_
const int safepoint_table_offset_
const int handler_table_offset_
const int code_comments_offset_
const int jump_table_info_offset_
const int unpadded_binary_size_
int trap_handler_index_ = -1
const uint8_t flags_
std::atomic< uint32_t > ref_count_bitfield_ {1}
Static Private Attributes
static constexpr uint32_t kIsDyingMask = 0x8000'0000u
Friends
class NativeModule
class WasmImportWrapperCache
Detailed Description
Definition at line 91 of file wasm-code-manager.h.
Member Typedef Documentation
ExecutionTierField
using v8::internal::wasm::WasmCode::ExecutionTierField = KindField::Next<ExecutionTier, 2> [private]
Definition at line 500 of file wasm-code-manager.h.
ForDebuggingField
using v8::internal::wasm::WasmCode::ForDebuggingField = ExecutionTierField::Next<ForDebugging, 2> [private]
Definition at line 501 of file wasm-code-manager.h.
FrameHasFeedbackSlotField
using v8::internal::wasm::WasmCode::FrameHasFeedbackSlotField = ForDebuggingField::Next<bool, 1> [private]
Definition at line 502 of file wasm-code-manager.h.
KindField
using v8::internal::wasm::WasmCode::KindField = base::BitField8<Kind, 0, 2> [private]
Definition at line 495 of file wasm-code-manager.h.
Member Enumeration Documentation
FlushICache
enum v8::internal::wasm::WasmCode::FlushICache : bool
Enumerator
kFlushICache
kNoFlushICache
Definition at line 378 of file wasm-code-manager.h.
: bool { kFlushICache = true, kNoFlushICache = false };
Kind
enum v8::internal::wasm::WasmCode::Kind
Enumerator
kWasmFunction
kWasmToCapiWrapper
kWasmToJsWrapper
kJumpTable
Definition at line 93 of file wasm-code-manager.h.
            {
    kWasmFunction,
    kWasmToCapiWrapper,
    kWasmToJsWrapper,
#if V8_ENABLE_DRUMBRAKE
    kInterpreterEntry,
#endif // V8_ENABLE_DRUMBRAKE
    kJumpTable
  };
Constructor & Destructor Documentation
WasmCode() [1/2]
v8::internal::wasm::WasmCode::WasmCode (const WasmCode &) [delete]
Referenced by EstimateCurrentMemoryConsumption().
 WasmCode()
v8::internal::wasm::WasmCode::~WasmCode ()
Definition at line 565 of file wasm-code-manager.cc.
                    {
  if (has_trap_handler_index()) {
    trap_handler::ReleaseHandlerData(trap_handler_index());
  }
}
References has_trap_handler_index(), v8::internal::trap_handler::ReleaseHandlerData(), and trap_handler_index().
WasmCode() [2/2]
v8::internal::wasm::WasmCode::WasmCode (NativeModule * native_module, int index, base::Vector< uint8_t > instructions, int stack_slots, int ool_spills, uint32_t tagged_parameter_slots, int safepoint_table_offset, int handler_table_offset, int constant_pool_offset, int code_comments_offset, int jump_table_info_offset, int unpadded_binary_size, base::Vector< const uint8_t > protected_instructions_data, base::Vector< const uint8_t > reloc_info, base::Vector< const uint8_t > source_position_table, base::Vector< const uint8_t > inlining_positions, base::Vector< const uint8_t > deopt_data, Kind kind, ExecutionTier tier, ForDebugging for_debugging, uint64_t signature_hash, bool frame_has_feedback_slot = false) [inline], [private]
Definition at line 390 of file wasm-code-manager.h.
      : native_module_(native_module),
        instructions_(instructions.begin()),
        signature_hash_(signature_hash),
        meta_data_(ConcatenateBytes({protected_instructions_data, reloc_info,
                                     source_position_table, inlining_positions,
                                     deopt_data})),
        instructions_size_(instructions.length()),
        reloc_info_size_(reloc_info.length()),
        source_positions_size_(source_position_table.length()),
        inlining_positions_size_(inlining_positions.length()),
        deopt_data_size_(deopt_data.length()),
        protected_instructions_size_(protected_instructions_data.length()),
        index_(index),
        constant_pool_offset_(constant_pool_offset),
        stack_slots_(stack_slots),
        ool_spills_(ool_spills),
        tagged_parameter_slots_(tagged_parameter_slots),
        safepoint_table_offset_(safepoint_table_offset),
        handler_table_offset_(handler_table_offset),
        code_comments_offset_(code_comments_offset),
        jump_table_info_offset_(jump_table_info_offset),
        unpadded_binary_size_(unpadded_binary_size),
        flags_(KindField::encode(kind) | ExecutionTierField::encode(tier) |
               ForDebuggingField::encode(for_debugging) |
               FrameHasFeedbackSlotField::encode(frame_has_feedback_slot)) {
    DCHECK_LE(safepoint_table_offset, unpadded_binary_size);
    DCHECK_LE(handler_table_offset, unpadded_binary_size);
    DCHECK_LE(code_comments_offset, unpadded_binary_size);
    DCHECK_LE(constant_pool_offset, unpadded_binary_size);
    DCHECK_LE(jump_table_info_offset, unpadded_binary_size);
  }
Member Function Documentation
code_comments()
Address v8::internal::wasm::WasmCode::code_comments () const
Definition at line 193 of file wasm-code-manager.cc.
                                      {
  return instruction_start() + code_comments_offset_;
}
References code_comments_offset_, and instruction_start().
code_comments_offset()
int v8::internal::wasm::WasmCode::code_comments_offset () const [inline]
Definition at line 213 of file wasm-code-manager.h.
{ return code_comments_offset_; }
code_comments_size()
int v8::internal::wasm::WasmCode::code_comments_size () const
Definition at line 197 of file wasm-code-manager.cc.
                                       {
  DCHECK_GE(jump_table_info_offset_, code_comments_offset_);
  return static_cast<int>(jump_table_info_offset_ - code_comments_offset_);
}
References code_comments_offset_, DCHECK_GE, and jump_table_info_offset_.
ConcatenateBytes()
std::unique_ptr< const uint8_t[]> v8::internal::wasm::WasmCode::ConcatenateBytes (std::initializer_list< base::Vector< const uint8_t >> vectors) [private]
Definition at line 211 of file wasm-code-manager.cc.
                                                            {
  size_t total_size = 0;
  for (auto& vec : vectors) total_size += vec.size();
  // Use default-initialization (== no initialization).
  std::unique_ptr<uint8_t[]> result{new uint8_t[total_size]};
  uint8_t* ptr = result.get();
  for (auto& vec : vectors) {
    if (vec.empty()) continue; // Avoid nullptr in {memcpy}.
    memcpy(ptr, vec.begin(), vec.size());
    ptr += vec.size();
  }
  return result;
}
References v8::base::internal::result.
constant_pool()
Address v8::internal::wasm::WasmCode::constant_pool () const
Definition at line 175 of file wasm-code-manager.cc.
                                      {
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    if (constant_pool_offset_ < code_comments_offset_) {
      return instruction_start() + constant_pool_offset_;
    }
  }
  return kNullAddress;
}
References code_comments_offset_, constant_pool_offset_, instruction_start(), v8::internal::kNullAddress, and V8_EMBEDDED_CONSTANT_POOL_BOOL.
Referenced by Disassemble(), v8::internal::Isolate::UnwindAndFindHandler(), and Validate().
constant_pool_offset()
int v8::internal::wasm::WasmCode::constant_pool_offset () const [inline]
Definition at line 210 of file wasm-code-manager.h.
{ return constant_pool_offset_; }
contains()
bool v8::internal::wasm::WasmCode::contains (Address pc) const [inline]
Definition at line 233 of file wasm-code-manager.h.
                                  {
    return reinterpret_cast<Address>(instructions_) <= pc &&
           pc < reinterpret_cast<Address>(instructions_ + instructions_size_);
  }
Referenced by v8::internal::wasm::WasmImportWrapperCache::Lookup(), v8::internal::wasm::NativeModule::Lookup(), and Validate().
DcheckRefCountIsOne()
void v8::internal::wasm::WasmCode::DcheckRefCountIsOne () [inline]
Definition at line 343 of file wasm-code-manager.h.
                             {
    DCHECK_EQ(1, refcount(ref_count_bitfield_.load(std::memory_order_acquire)));
  }
References DCHECK_EQ.
Referenced by v8::internal::wasm::WasmImportWrapperHandle::set_code().
DebugName()
std::string v8::internal::wasm::WasmCode::DebugName () const
Definition at line 252 of file wasm-code-manager.cc.
                                    {
  switch (kind()) {
    case kWasmToCapiWrapper:
      return "wasm-to-c";
    case kJumpTable:
      return "jump-table";
    case kWasmToJsWrapper:
      return "wasm-to-js";
#if V8_ENABLE_DRUMBRAKE
    case kInterpreterEntry:
      return "interpreter entry";
#endif // V8_ENABLE_DRUMBRAKE
    case kWasmFunction:
      // Gets handled below
      break;
  }
  ModuleWireBytes wire_bytes(native_module()->wire_bytes());
  const WasmModule* module = native_module()->module();
  WireBytesRef name_ref =
      module->lazily_generated_names.LookupFunctionName(wire_bytes, index());
  WasmName name = wire_bytes.GetNameOrNull(name_ref);
  std::string name_buffer;
  if (name.empty()) {
    name_buffer.resize(32);
    name_buffer.resize(
        SNPrintF(base::VectorOf(&name_buffer.front(), name_buffer.size()),
                 "wasm-function[%d]", index()));
  } else {
    name_buffer.append(name.begin(), name.end());
  }
  return name_buffer;
}
References v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), index(), kind(), kJumpTable, kWasmFunction, kWasmToCapiWrapper, kWasmToJsWrapper, v8::internal::wasm::WasmModule::lazily_generated_names, v8::internal::wasm::LazilyGeneratedNames::LookupFunctionName(), v8::internal::wasm::NativeModule::module(), v8::internal::wasm::name(), native_module(), v8::base::SNPrintF(), v8::internal::string, and v8::base::VectorOf().
Referenced by LogCode(), and MaybePrint().
DecRef()
V8_WARN_UNUSED_RESULT bool v8::internal::wasm::WasmCode::DecRef () [inline]
Definition at line 289 of file wasm-code-manager.h.
                                      {
    uint32_t old_field = ref_count_bitfield_.load(std::memory_order_acquire);
    while (true) {
      DCHECK_LE(1, refcount(old_field));
      if (V8_UNLIKELY(refcount(old_field) == 1)) {
        if (is_dying(old_field)) {
          // The code was already on the path to deletion, only temporary
          // C++ references to it are left. Decrement the refcount, and
          // return true if it drops to zero.
          return DecRefOnDeadCode();
        }
        // Otherwise, the code enters the path to destruction now.
        if (ref_count_bitfield_.compare_exchange_weak(
                old_field, old_field | kIsDyingMask,
                std::memory_order_acq_rel)) {
          // No other thread got in the way. Commit to the decision.
          DecRefOnPotentiallyDeadCode();
          return false;
        }
        // Another thread interfered. Re-evaluate what to do.
        continue;
      }
      DCHECK_LT(1, refcount(old_field));
      if (ref_count_bitfield_.compare_exchange_weak(
              old_field, old_field - 1, std::memory_order_acq_rel)) {
        return false;
      }
    }
  }
References DCHECK_LE, DCHECK_LT, and V8_UNLIKELY.
Referenced by v8::internal::wasm::WasmImportWrapperHandle::~WasmImportWrapperHandle().
DecRefOnDeadCode()
V8_WARN_UNUSED_RESULT bool v8::internal::wasm::WasmCode::DecRefOnDeadCode () [inline]
Definition at line 330 of file wasm-code-manager.h.
                                                {
    uint32_t old_bitfield_value =
        ref_count_bitfield_.fetch_sub(1, std::memory_order_acq_rel);
    return refcount(old_bitfield_value) == 1;
  }
DecRefOnLiveCode()
void v8::internal::wasm::WasmCode::DecRefOnLiveCode () [inline]
Definition at line 321 of file wasm-code-manager.h.
                          {
    [[maybe_unused]] uint32_t old_bitfield_value =
        ref_count_bitfield_.fetch_sub(1, std::memory_order_acq_rel);
    DCHECK_LE(2, refcount(old_bitfield_value));
  }
References DCHECK_LE.
Referenced by v8::internal::wasm::NativeModule::PublishCodeLocked().
DecRefOnPotentiallyDeadCode()
void v8::internal::wasm::WasmCode::DecRefOnPotentiallyDeadCode () [private]
Definition at line 571 of file wasm-code-manager.cc.
                                           {
  GetWasmEngine()->AddPotentiallyDeadCode(this);
}
References v8::internal::wasm::WasmEngine::AddPotentiallyDeadCode(), and v8::internal::wasm::GetWasmEngine().
DecrementRefCount()
void v8::internal::wasm::WasmCode::DecrementRefCount (base::Vector< WasmCode *const > code_vec) [static]
Definition at line 576 of file wasm-code-manager.cc.
                                                                     {
  // Decrement the ref counter of all given code objects. Keep the ones whose
  // ref count drops to zero.
  WasmEngine::DeadCodeMap dead_code;
  std::vector<WasmCode*> dead_wrappers;
  for (WasmCode* code : code_vec) {
    if (!code->DecRef()) continue; // Remaining references.
    NativeModule* native_module = code->native_module();
    if (native_module != nullptr) {
      dead_code[native_module].push_back(code);
    } else {
      dead_wrappers.push_back(code);
    }
  }
  if (dead_code.empty() && dead_wrappers.empty()) return;
  GetWasmEngine()->FreeDeadCode(dead_code, dead_wrappers);
}
References code, v8::internal::wasm::WasmEngine::FreeDeadCode(), v8::internal::wasm::GetWasmEngine(), and native_module().
Referenced by v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), and v8::internal::wasm::WasmCodeRefScope::~WasmCodeRefScope().
deopt_data()
base::Vector<const uint8_t> v8::internal::wasm::WasmCode::deopt_data () const [inline]
Definition at line 192 of file wasm-code-manager.h.
                                               {
    return {inlining_positions().end(), static_cast<size_t>(deopt_data_size_)};
  }
References v8::base::Vector< T >::end().
Referenced by Disassemble(), and v8::internal::wasm::NativeModule::should_update_code_table().
Disassemble()
void v8::internal::wasm::WasmCode::Disassemble (const char * name, std::ostream & os, Address current_pc = kNullAddress) const
Definition at line 444 of file wasm-code-manager.cc.
                                                     {
  if (name) os << "name: " << name << "\n";
  if (!IsAnonymous()) os << "index: " << index() << "\n";
  os << "kind: " << GetWasmCodeKindAsString(kind()) << "\n";
  if (kind() == kWasmFunction) {
    DCHECK(is_liftoff() || tier() == ExecutionTier::kTurbofan);
    const char* compiler =
        is_liftoff() ? (for_debugging() ? "Liftoff (debug)" : "Liftoff")
                     : "TurboFan";
    os << "compiler: " << compiler << "\n";
  }
  size_t padding = instructions().size() - unpadded_binary_size_;
  os << "Body (size = " << instructions().size() << " = "
     << unpadded_binary_size_ << " + " << padding << " padding)\n";
  int instruction_size = unpadded_binary_size_;
  if (constant_pool_offset_ < instruction_size) {
    instruction_size = constant_pool_offset_;
  }
  if (safepoint_table_offset_ && safepoint_table_offset_ < instruction_size) {
    instruction_size = safepoint_table_offset_;
  }
  if (handler_table_offset_ < instruction_size) {
    instruction_size = handler_table_offset_;
  }
  DCHECK_LT(0, instruction_size);
#ifdef ENABLE_DISASSEMBLER
  os << "Instructions (size = " << instruction_size << ")\n";
  Disassembler::Decode(nullptr, os, instructions().begin(),
                       instructions().begin() + instruction_size,
                       CodeReference(this), current_pc);
  os << "\n";
  if (handler_table_size() > 0) {
    HandlerTable table(this);
    os << "Exception Handler Table (size = " << table.NumberOfReturnEntries()
       << "):\n";
    table.HandlerTableReturnPrint(os);
    os << "\n";
  }
  if (protected_instructions_size_ > 0) {
    os << "Protected instructions:\n pc offset\n";
    for (auto& data : protected_instructions()) {
      os << std::setw(10) << std::hex << data.instr_offset << std::setw(10)
         << "\n";
    }
    os << "\n";
  }
  if (!source_positions().empty()) {
    os << "Source positions:\n pc offset position\n";
    for (SourcePositionTableIterator it(source_positions()); !it.done();
         it.Advance()) {
      os << std::setw(10) << std::hex << it.code_offset() << std::dec
         << std::setw(10) << it.source_position().ScriptOffset()
         << (it.is_statement() ? " statement" : "") << "\n";
    }
    os << "\n";
  }
  if (deopt_data_size_ > 0) {
    WasmDeoptView view(deopt_data());
    const WasmDeoptData data = view.GetDeoptData();
    os << "Deopt exits (entries = " << data.entry_count
       << ", byte size = " << deopt_data_size_ << ")\n";
    constexpr char pc_offset[] = "pc-offset";
    constexpr char source_offset[] = " source-offset";
    constexpr char translation_index[] = " translation-index";
    os << pc_offset << source_offset << translation_index << '\n';
    uint32_t code_offset = data.deopt_exit_start_offset;
    for (uint32_t i = 0; i < data.entry_count; ++i) {
      WasmDeoptEntry entry = view.GetDeoptEntry(i);
      os << std::setw(sizeof pc_offset - 1) << std::hex << code_offset
         << std::dec << std::setw(sizeof source_offset - 1)
         << entry.bytecode_offset << std::setw(sizeof translation_index - 1)
         << entry.translation_index << '\n';
      code_offset += Deoptimizer::kEagerDeoptExitSize;
    }
    os << '\n';
  }
  if (safepoint_table_offset_ > 0) {
    SafepointTable table(this);
    table.Print(os);
    os << "\n";
  }
  os << "RelocInfo (size = " << reloc_info().size() << ")\n";
  for (RelocIterator it(instructions(), reloc_info(), constant_pool());
       !it.done(); it.next()) {
    it.rinfo()->Print(nullptr, os);
  }
  os << "\n";
#else // !ENABLE_DISASSEMBLER
  os << "Instructions (size = " << instruction_size << ", "
     << static_cast<void*>(instructions().begin()) << "-"
     << static_cast<void*>(instructions().begin() + instruction_size) << ")\n";
#endif // !ENABLE_DISASSEMBLER
}
References v8::base::Vector< T >::begin(), v8::internal::compiler::begin(), v8::internal::wasm::WasmDeoptEntry::bytecode_offset, constant_pool(), constant_pool_offset_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::Disassembler::Decode(), deopt_data(), deopt_data_size_, v8::internal::wasm::WasmDeoptData::deopt_exit_start_offset, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::SourcePositionTableIterator::done(), v8::internal::wasm::WasmDeoptData::entry_count, for_debugging(), v8::internal::wasm::WasmDeoptView::GetDeoptData(), v8::internal::wasm::WasmDeoptView::GetDeoptEntry(), v8::internal::wasm::GetWasmCodeKindAsString(), handler_table_offset_, handler_table_size(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, index(), instructions(), is_liftoff(), IsAnonymous(), v8::internal::Deoptimizer::kEagerDeoptExitSize, kind(), v8::internal::wasm::kTurbofan, kWasmFunction, v8::internal::wasm::name(), v8::internal::HandlerTable::NumberOfReturnEntries(), v8::internal::SafepointTable::Print(), protected_instructions(), protected_instructions_size_, reloc_info(), safepoint_table_offset_, v8::base::Vector< T >::size(), source_positions(), tier(), v8::internal::wasm::WasmDeoptEntry::translation_index, and unpadded_binary_size_.
Referenced by Print().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::WasmCode::EstimateCurrentMemoryConsumption () const
Definition at line 625 of file wasm-code-manager.cc.
                                                        {
  UPDATE_WHEN_CLASS_CHANGES(WasmCode, 112);
  size_t result = sizeof(WasmCode);
  // For meta_data_.
  result += protected_instructions_size_ + reloc_info_size_ +
            source_positions_size_ + inlining_positions_size_ +
            deopt_data_size_;
  return result;
}
References deopt_data_size_, inlining_positions_size_, protected_instructions_size_, reloc_info_size_, v8::base::internal::result, source_positions_size_, UPDATE_WHEN_CLASS_CHANGES, and WasmCode().
first_tagged_parameter_slot()
uint16_t v8::internal::wasm::WasmCode::first_tagged_parameter_slot () const [inline]
Definition at line 219 of file wasm-code-manager.h.
                                               {
    return tagged_parameter_slots_ >> 16;
  }
for_debugging()
ForDebugging v8::internal::wasm::WasmCode::for_debugging () const [inline]
Definition at line 357 of file wasm-code-manager.h.
                                     {
    return ForDebuggingField::decode(flags_);
  }
Referenced by Disassemble(), and v8::internal::wasm::NativeModule::should_update_code_table().
frame_has_feedback_slot()
bool v8::internal::wasm::WasmCode::frame_has_feedback_slot () const [inline]
Definition at line 374 of file wasm-code-manager.h.
                                       {
    return FrameHasFeedbackSlotField::decode(flags_);
  }
GetInliningPosition()
std::tuple< int, bool, SourcePosition > v8::internal::wasm::WasmCode::GetInliningPosition (int inlining_id) const
Definition at line 610 of file wasm-code-manager.cc.
                           {
  const size_t elem_size = sizeof(int) + sizeof(bool) + sizeof(SourcePosition);
  const uint8_t* start = inlining_positions().begin() + elem_size * inlining_id;
  DCHECK_LE(start, inlining_positions().end());
  std::tuple<int, bool, SourcePosition> result;
  std::memcpy(&std::get<0>(result), start, sizeof std::get<0>(result));
  std::memcpy(&std::get<1>(result), start + sizeof std::get<0>(result),
              sizeof std::get<1>(result));
  std::memcpy(&std::get<2>(result),
              start + sizeof std::get<0>(result) + sizeof std::get<1>(result),
              sizeof std::get<2>(result));
  return result;
}
References v8::base::Vector< T >::begin(), DCHECK_LE, v8::internal::compiler::end(), inlining_positions(), and v8::base::internal::result.
GetRecordWriteBuiltin()
static constexpr Builtin v8::internal::wasm::WasmCode::GetRecordWriteBuiltin (SaveFPRegsMode fp_mode) [inline], [static], [constexpr]
Definition at line 103 of file wasm-code-manager.h.
                                                                         {
    switch (fp_mode) {
      case SaveFPRegsMode::kIgnore:
        return Builtin::kRecordWriteIgnoreFP;
      case SaveFPRegsMode::kSave:
        return Builtin::kRecordWriteSaveFP;
    }
  }
References v8::internal::kIgnore, and v8::internal::kSave.
Referenced by v8::internal::MacroAssembler::CallRecordWriteStub().
GetSourceOffsetBefore()
int v8::internal::wasm::WasmCode::GetSourceOffsetBefore (int code_offset)
Definition at line 606 of file wasm-code-manager.cc.
                                                   {
  return GetSourcePositionBefore(code_offset).ScriptOffset();
}
References GetSourcePositionBefore(), and v8::internal::SourcePosition::ScriptOffset().
GetSourcePositionBefore()
SourcePosition v8::internal::wasm::WasmCode::GetSourcePositionBefore (int code_offset)
Definition at line 596 of file wasm-code-manager.cc.
                                                                {
  SourcePosition position;
  for (SourcePositionTableIterator iterator(source_positions());
       !iterator.done() && iterator.code_offset() < code_offset;
       iterator.Advance()) {
    position = iterator.source_position();
  }
  return position;
}
References v8::internal::SourcePositionTableIterator::done(), and source_positions().
Referenced by GetSourceOffsetBefore().
handler_table()
Address v8::internal::wasm::WasmCode::handler_table () const
Definition at line 184 of file wasm-code-manager.cc.
                                      {
  return instruction_start() + handler_table_offset_;
}
References handler_table_offset_, and instruction_start().
handler_table_offset()
int v8::internal::wasm::WasmCode::handler_table_offset () const [inline]
Definition at line 212 of file wasm-code-manager.h.
{ return handler_table_offset_; }
handler_table_size()
int v8::internal::wasm::WasmCode::handler_table_size () const
Definition at line 188 of file wasm-code-manager.cc.
                                       {
  DCHECK_GE(constant_pool_offset_, handler_table_offset_);
  return static_cast<int>(constant_pool_offset_ - handler_table_offset_);
}
References constant_pool_offset_, DCHECK_GE, and handler_table_offset_.
Referenced by Disassemble().
has_jump_table_info()
bool v8::internal::wasm::WasmCode::has_jump_table_info () const [inline]
Definition at line 209 of file wasm-code-manager.h.
{ return jump_table_info_size() > 0; }
has_trap_handler_index()
bool v8::internal::wasm::WasmCode::has_trap_handler_index () const [inline], [private]
Definition at line 449 of file wasm-code-manager.h.
{ return trap_handler_index_ >= 0; }
Referenced by RegisterTrapHandlerData(), and ~WasmCode().
IncRef()
void v8::internal::wasm::WasmCode::IncRef () [inline]
Definition at line 268 of file wasm-code-manager.h.
                {
    [[maybe_unused]] uint32_t old_field =
        ref_count_bitfield_.fetch_add(1, std::memory_order_acq_rel);
    DCHECK_LE(1, refcount(old_field));
    DCHECK_GT(kMaxInt, refcount(old_field));
  }
References DCHECK_GT, DCHECK_LE, and v8::internal::kMaxInt.
Referenced by v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), and v8::internal::wasm::WasmImportWrapperHandle::WasmImportWrapperHandle().
IncRefIfNotDying()
bool v8::internal::wasm::WasmCode::IncRefIfNotDying () [inline]
Definition at line 276 of file wasm-code-manager.h.
                          {
    uint32_t old_field = ref_count_bitfield_.load(std::memory_order_acquire);
    while (true) {
      if (is_dying(old_field)) return false;
      if (ref_count_bitfield_.compare_exchange_weak(
              old_field, old_field + 1, std::memory_order_acq_rel)) {
        return true;
      }
    }
  }
index()
int v8::internal::wasm::WasmCode::index () const [inline]
Definition at line 196 of file wasm-code-manager.h.
{ return index_; }
Referenced by DebugName(), Disassemble(), v8::internal::wasm::DebugInfoImpl::GetFunctionAtAddress(), MaybePrint(), RegisterTrapHandlerData(), v8::internal::wasm::DebugInfoImpl::UpdateReturnAddress(), and v8::internal::wasm::DebugInfoImpl::UpdateReturnAddresses().
inlining_positions()
base::Vector<const uint8_t> v8::internal::wasm::WasmCode::inlining_positions () const [inline]
Definition at line 188 of file wasm-code-manager.h.
                                                       {
    return {source_positions().end(),
            static_cast<size_t>(inlining_positions_size_)};
  }
References v8::base::Vector< T >::end().
Referenced by GetInliningPosition().
instruction_start()
Address v8::internal::wasm::WasmCode::instruction_start () const [inline]
Definition at line 175 of file wasm-code-manager.h.
                                    {
    return reinterpret_cast<Address>(instructions_);
  }
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), code_comments(), constant_pool(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), handler_table(), v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation(), IsProtectedInstruction(), jump_table_info(), LogCode(), v8::internal::wasm::WasmImportWrapperCache::Lookup(), v8::internal::wasm::NativeModule::Lookup(), v8::internal::wasm::NativeModule::PatchJumpTableLocked(), RegisterTrapHandlerData(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::wasm::NativeModule::UseLazyStubLocked().
instructions()
base::Vector<uint8_t> v8::internal::wasm::WasmCode::instructions () const [inline]
Definition at line 171 of file wasm-code-manager.h.
                                           {
    return base::VectorOf(instructions_,
                          static_cast<size_t>(instructions_size_));
  }
References v8::base::VectorOf().
Referenced by v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), v8::internal::wasm::WasmImportWrapperCache::CompileWrapper(), Disassemble(), IsProtectedInstruction(), v8::internal::wasm::NativeModule::PatchJumpTableLocked(), RegisterTrapHandlerData(), and Validate().
instructions_size()
size_t v8::internal::wasm::WasmCode::instructions_size () const [inline]
Definition at line 178 of file wasm-code-manager.h.
                                   {
    return static_cast<size_t>(instructions_size_);
  }
is_dying() [1/2]
bool v8::internal::wasm::WasmCode::is_dying () const [inline]
Definition at line 361 of file wasm-code-manager.h.
                        {
    return is_dying(ref_count_bitfield_.load(std::memory_order_acquire));
  }
is_dying() [2/2]
static bool v8::internal::wasm::WasmCode::is_dying (uint32_t bit_field_value) [inline], [static]
Definition at line 364 of file wasm-code-manager.h.
                                                 {
    return (bit_field_value & kIsDyingMask) != 0;
  }
is_inspectable()
bool v8::internal::wasm::WasmCode::is_inspectable () const [inline]
Definition at line 240 of file wasm-code-manager.h.
{ return is_liftoff() && for_debugging(); }
Referenced by v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints().
is_liftoff()
bool v8::internal::wasm::WasmCode::is_liftoff () const [inline]
Definition at line 229 of file wasm-code-manager.h.
{ return tier() == ExecutionTier::kLiftoff; }
References v8::internal::wasm::kLiftoff.
Referenced by Disassemble(), and v8::internal::wasm::DebugInfoImpl::UpdateReturnAddress().
is_turbofan()
bool v8::internal::wasm::WasmCode::is_turbofan () const [inline]
Definition at line 231 of file wasm-code-manager.h.
{ return tier() == ExecutionTier::kTurbofan; }
References v8::internal::wasm::kTurbofan.
IsAnonymous()
bool v8::internal::wasm::WasmCode::IsAnonymous () const [inline]
Definition at line 198 of file wasm-code-manager.h.
{ return index_ == kAnonymousFuncIndex; }
References v8::internal::wasm::kAnonymousFuncIndex.
Referenced by Disassemble(), LogCode(), and MaybePrint().
IsProtectedInstruction()
bool v8::internal::wasm::WasmCode::IsProtectedInstruction (Address pc)
Definition at line 336 of file wasm-code-manager.cc.
                                                {
  base::Vector<const trap_handler::ProtectedInstructionData> instructions =
      protected_instructions();
  ProtectedInstructionData offset{
      static_cast<uint32_t>(pc - instruction_start())};
  return std::binary_search(instructions.begin(), instructions.end(), offset,
                            ProtectedInstructionDataCompare);
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), instruction_start(), instructions(), protected_instructions(), and v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ProtectedInstructionDataCompare().
jump_table_info()
Address v8::internal::wasm::WasmCode::jump_table_info () const
Definition at line 202 of file wasm-code-manager.cc.
                                        {
  return instruction_start() + jump_table_info_offset_;
}
References instruction_start(), and jump_table_info_offset_.
jump_table_info_offset()
int v8::internal::wasm::WasmCode::jump_table_info_offset () const [inline]
Definition at line 214 of file wasm-code-manager.h.
{ return jump_table_info_offset_; }
jump_table_info_size()
int v8::internal::wasm::WasmCode::jump_table_info_size () const
Definition at line 206 of file wasm-code-manager.cc.
                                         {
  DCHECK_GE(unpadded_binary_size_, jump_table_info_offset_);
  return static_cast<int>(unpadded_binary_size_ - jump_table_info_offset_);
}
References DCHECK_GE, jump_table_info_offset_, and unpadded_binary_size_.
kind()
Kind v8::internal::wasm::WasmCode::kind () const [inline]
Definition at line 199 of file wasm-code-manager.h.
{ return KindField::decode(flags_); }
Referenced by DebugName(), Disassemble(), LogCode(), MaybePrint(), and RegisterTrapHandlerData().
LogCode()
void v8::internal::wasm::WasmCode::LogCode (Isolate * isolate, const char * source_url, int script_id) const
Definition at line 286 of file wasm-code-manager.cc.
                                            {
  DCHECK(ShouldBeLogged(isolate));
  if (IsAnonymous() && kind() != WasmCode::Kind::kWasmToJsWrapper) return;
  std::string fn_name = DebugName();
  WasmName name = base::VectorOf(fn_name);
  if (native_module_) {
    const WasmModule* module = native_module_->module();
    const WasmDebugSymbols& symbol =
        module->debug_symbols[WasmDebugSymbols::Type::SourceMap];
    auto load_wasm_source_map = isolate->wasm_load_source_map_callback();
    auto source_map = native_module_->GetWasmSourceMap();
    if (!source_map && symbol.type == WasmDebugSymbols::Type::SourceMap &&
        !symbol.external_url.is_empty() && load_wasm_source_map) {
      ModuleWireBytes wire_bytes(native_module_->wire_bytes());
      WasmName external_url = wire_bytes.GetNameOrNull(symbol.external_url);
      std::string external_url_string(external_url.data(), external_url.size());
      HandleScope scope(isolate);
      v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
      Local<v8::String> source_map_str =
          load_wasm_source_map(v8_isolate, external_url_string.c_str());
      native_module_->SetWasmSourceMap(
          std::make_unique<WasmModuleSourceMap>(v8_isolate, source_map_str));
    }
  }
  // Record source positions before adding code, otherwise when code is added,
  // there are no source positions to associate with the added code.
  if (!source_positions().empty()) {
    LOG_CODE_EVENT(isolate, WasmCodeLinePosInfoRecordEvent(instruction_start(),
                                                           source_positions()));
  }
  int code_offset = 0;
  if (!IsAnonymous()) {
    code_offset = native_module_->module()->functions[index_].code.offset();
  }
  PROFILE(isolate, CodeCreateEvent(LogEventListener::CodeTag::kFunction, this,
                                   name, source_url, code_offset, script_id));
}
References v8::base::Vector< T >::data(), v8::internal::DCHECK(), v8::internal::wasm::WasmModule::debug_symbols, DebugName(), v8::internal::wasm::WasmDebugSymbols::external_url, v8::internal::wasm::WasmModule::functions, v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::wasm::NativeModule::GetWasmSourceMap(), index_, instruction_start(), v8::internal::wasm::WireBytesRef::is_empty(), IsAnonymous(), v8::internal::torque::ls::kFunction, kind(), LOG_CODE_EVENT, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::name(), native_module_, PROFILE, v8::internal::wasm::NativeModule::SetWasmSourceMap(), ShouldBeLogged(), v8::base::Vector< T >::size(), source_positions(), v8::internal::string, v8::internal::wasm::WasmDebugSymbols::type, v8::base::VectorOf(), and v8::internal::wasm::NativeModule::wire_bytes().
MaybePrint()
void v8::internal::wasm::WasmCode::MaybePrint () const
Definition at line 417 of file wasm-code-manager.cc.
                                {
  // Determines whether flags want this code to be printed.
  bool function_index_matches =
      (!IsAnonymous() &&
       v8_flags.print_wasm_code_function_index == static_cast<int>(index()));
  if (v8_flags.print_code ||
      (kind() == kWasmFunction
           ? (v8_flags.print_wasm_code || function_index_matches)
           : v8_flags.print_wasm_stub_code.value())) {
    std::string name = DebugName();
    Print(name.c_str());
  }
}
References DebugName(), index(), IsAnonymous(), kind(), kWasmFunction, v8::internal::wasm::name(), Print(), v8::internal::string, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), v8::internal::wasm::WasmImportWrapperCache::CompileWrapper(), and v8::internal::wasm::NativeModuleDeserializer::Publish().
native_module()
NativeModule* v8::internal::wasm::WasmCode::native_module () const [inline]
Definition at line 200 of file wasm-code-manager.h.
{ return native_module_; }
Referenced by DebugName(), DecrementRefCount(), v8::internal::wasm::DebugInfoImpl::UpdateReturnAddress(), and v8::internal::wasm::DebugInfoImpl::UpdateReturnAddresses().
num_tagged_parameter_slots()
uint16_t v8::internal::wasm::WasmCode::num_tagged_parameter_slots () const [inline]
Definition at line 222 of file wasm-code-manager.h.
                                              {
    return tagged_parameter_slots_ & 0xFFFF;
  }
ool_spills()
int v8::internal::wasm::WasmCode::ool_spills () const [inline]
Definition at line 217 of file wasm-code-manager.h.
{ return ool_spills_; }
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
operator=()
WasmCode& v8::internal::wasm::WasmCode::operator= (const WasmCode &) [delete]
Print()
void v8::internal::wasm::WasmCode::Print (const char * name = nullptr) const
Definition at line 431 of file wasm-code-manager.cc.
                                           {
  StdoutStream os;
  os << "--- WebAssembly code ---\n";
  Disassemble(name, os);
  if (native_module_ && native_module_->HasDebugInfo()) {
    if (auto* debug_side_table =
            native_module_->GetDebugInfo()->GetDebugSideTableIfExists(this)) {
      debug_side_table->Print(os);
    }
  }
  os << "--- End code ---\n";
}
References Disassemble(), v8::internal::wasm::NativeModule::GetDebugInfo(), v8::internal::wasm::DebugInfo::GetDebugSideTableIfExists(), v8::internal::wasm::NativeModule::HasDebugInfo(), v8::internal::wasm::name(), and native_module_.
Referenced by MaybePrint().
protected_instructions()
base::Vector<const trap_handler::ProtectedInstructionData> v8::internal::wasm::WasmCode::protected_instructions () const [inline]
Definition at line 248 of file wasm-code-manager.h.
                                 {
    return base::Vector<const trap_handler::ProtectedInstructionData>::cast(
        protected_instructions_data());
  }
Referenced by Disassemble(), IsProtectedInstruction(), and RegisterTrapHandlerData().
protected_instructions_data()
base::Vector<const uint8_t> v8::internal::wasm::WasmCode::protected_instructions_data () const [inline]
Definition at line 242 of file wasm-code-manager.h.
                                                                {
    return {meta_data_.get(),
            static_cast<size_t>(protected_instructions_size_)};
  }
raw_tagged_parameter_slots_for_serialization()
uint32_t v8::internal::wasm::WasmCode::raw_tagged_parameter_slots_for_serialization () const [inline]
Definition at line 225 of file wasm-code-manager.h.
                                                                {
    return tagged_parameter_slots_;
  }
refcount()
static uint32_t v8::internal::wasm::WasmCode::refcount (uint32_t bit_field_value) [inline], [static]
Definition at line 367 of file wasm-code-manager.h.
                                                     {
    return bit_field_value & ~kIsDyingMask;
  }
Referenced by v8::internal::wasm::NativeModule::FreeCode().
RegisterTrapHandlerData()
void v8::internal::wasm::WasmCode::RegisterTrapHandlerData () [private]
Definition at line 226 of file wasm-code-manager.cc.
                                       {
  DCHECK(!has_trap_handler_index());
  if (kind() != WasmCode::kWasmFunction) return;
  if (protected_instructions_size_ == 0) return;
  Address base = instruction_start();
  size_t size = instructions().size();
  auto protected_instruction_data = this->protected_instructions();
  const int index =
      RegisterHandlerData(base, size, protected_instruction_data.size(),
                          protected_instruction_data.begin());
  // TODO(eholk): if index is negative, fail.
  CHECK_LE(0, index);
  set_trap_handler_index(index);
  DCHECK(has_trap_handler_index());
}
References CHECK_LE, v8::internal::DCHECK(), has_trap_handler_index(), index(), instruction_start(), instructions(), kind(), kWasmFunction, protected_instructions(), protected_instructions_size_, v8::internal::trap_handler::RegisterHandlerData(), set_trap_handler_index(), v8::base::Vector< T >::size(), and size().
reloc_info()
base::Vector<const uint8_t> v8::internal::wasm::WasmCode::reloc_info () const [inline]
Definition at line 181 of file wasm-code-manager.h.
                                               {
    return {protected_instructions_data().end(),
            static_cast<size_t>(reloc_info_size_)};
  }
References v8::base::Vector< T >::end().
Referenced by v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), v8::internal::wasm::WasmImportWrapperCache::CompileWrapper(), Disassemble(), and Validate().
safepoint_table_offset()
int v8::internal::wasm::WasmCode::safepoint_table_offset () const [inline]
Definition at line 211 of file wasm-code-manager.h.
{ return safepoint_table_offset_; }
set_trap_handler_index()
void v8::internal::wasm::WasmCode::set_trap_handler_index (int value) [inline], [private]
Definition at line 445 of file wasm-code-manager.h.
                                         {
    CHECK(!has_trap_handler_index());
    trap_handler_index_ = value;
  }
References CHECK, and v8::internal::value.
Referenced by RegisterTrapHandlerData().
ShouldBeLogged()
bool v8::internal::wasm::WasmCode::ShouldBeLogged (Isolate * isolate) [static]
Definition at line 245 of file wasm-code-manager.cc.
                                              {
  // The return value is cached in {WasmEngine::IsolateData::log_codes}. Ensure
  // to call {WasmEngine::EnableCodeLogging} if this return value would change
  // for any isolate. Otherwise we might lose code events.
  return isolate->IsLoggingCodeCreation();
}
References v8::internal::Isolate::IsLoggingCodeCreation().
Referenced by v8::internal::wasm::WasmEngine::AddIsolate(), LogCode(), v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), and v8::internal::wasm::NativeModule::LogWasmCodes().
signature_hash()
uint64_t v8::internal::wasm::WasmCode::signature_hash () const [inline]
Definition at line 218 of file wasm-code-manager.h.
{ return signature_hash_; }
source_positions()
base::Vector<const uint8_t> v8::internal::wasm::WasmCode::source_positions () const [inline]
Definition at line 185 of file wasm-code-manager.h.
                                                     {
    return {reloc_info().end(), static_cast<size_t>(source_positions_size_)};
  }
References v8::base::Vector< T >::end().
Referenced by Disassemble(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), GetSourcePositionBefore(), and LogCode().
stack_slots()
int v8::internal::wasm::WasmCode::stack_slots () const [inline]
Definition at line 216 of file wasm-code-manager.h.
{ return stack_slots_; }
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
tier()
ExecutionTier v8::internal::wasm::WasmCode::tier () const [inline]
Definition at line 201 of file wasm-code-manager.h.
{ return ExecutionTierField::decode(flags_); }
Referenced by Disassemble(), and v8::internal::wasm::NativeModule::should_update_code_table().
trap_handler_index()
int v8::internal::wasm::WasmCode::trap_handler_index () const [inline], [private]
Definition at line 441 of file wasm-code-manager.h.
                                 {
    CHECK(has_trap_handler_index());
    return trap_handler_index_;
  }
References CHECK.
Referenced by ~WasmCode().
unpadded_binary_size()
int v8::internal::wasm::WasmCode::unpadded_binary_size () const [inline]
Definition at line 215 of file wasm-code-manager.h.
{ return unpadded_binary_size_; }
Validate()
void v8::internal::wasm::WasmCode::Validate () const
Definition at line 345 of file wasm-code-manager.cc.
                              {
  // The packing strategy for {tagged_parameter_slots} only works if both the
  // max number of parameters and their max combined stack slot usage fits into
  // their respective half of the result value.
  static_assert(wasm::kV8MaxWasmFunctionParams <
                std::numeric_limits<uint16_t>::max());
  static constexpr int kMaxSlotsPerParam = 4; // S128 on 32-bit platforms.
  static_assert(wasm::kV8MaxWasmFunctionParams * kMaxSlotsPerParam <
                std::numeric_limits<uint16_t>::max());
#ifdef DEBUG
  NativeModule::CallIndirectTargetMap function_index_map;
  if (native_module_) {
    function_index_map =
        native_module_->CreateIndirectCallTargetToFunctionIndexMap();
  }
  // Scope for foreign WasmCode pointers.
  WasmCodeRefScope code_ref_scope;
  // We expect certain relocation info modes to never appear in {WasmCode}
  // objects or to be restricted to a small set of valid values. Hence the
  // iteration below does not use a mask, but visits all relocation data.
  for (RelocIterator it(instructions(), reloc_info(), constant_pool());
       !it.done(); it.next()) {
    RelocInfo::Mode mode = it.rinfo()->rmode();
    switch (mode) {
      case RelocInfo::WASM_CALL: {
        Address target = it.rinfo()->wasm_call_address();
        WasmCode* code = native_module_->Lookup(target);
        CHECK_NOT_NULL(code);
        CHECK_EQ(WasmCode::kJumpTable, code->kind());
        CHECK(code->contains(target));
        break;
      }
      case RelocInfo::WASM_STUB_CALL: {
        Address target = it.rinfo()->wasm_stub_call_address();
        WasmCode* code = native_module_->Lookup(target);
        CHECK_NOT_NULL(code);
        CHECK_EQ(WasmCode::kJumpTable, code->kind());
        CHECK(code->contains(target));
        break;
      }
      case RelocInfo::WASM_CANONICAL_SIG_ID: {
        uint32_t sig_id = it.rinfo()->wasm_canonical_sig_id();
        CHECK_LE(sig_id, GetTypeCanonicalizer()->GetCurrentNumberOfTypes());
        break;
      }
      case RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY: {
        WasmCodePointer call_target =
            it.rinfo()->wasm_code_pointer_table_entry();
        uint32_t function_index = function_index_map.at(call_target);
        CHECK_EQ(call_target,
                 native_module_->GetCodePointerHandle(function_index));
        break;
      }
      case RelocInfo::INTERNAL_REFERENCE:
      case RelocInfo::INTERNAL_REFERENCE_ENCODED: {
        Address target = it.rinfo()->target_internal_reference();
        CHECK(contains(target));
        break;
      }
      case RelocInfo::EXTERNAL_REFERENCE:
      case RelocInfo::CONST_POOL:
      case RelocInfo::VENEER_POOL:
        // These are OK to appear.
        break;
      default:
        FATAL("Unexpected mode: %d", mode);
    }
  }
#endif
}
References CHECK, CHECK_EQ, CHECK_LE, CHECK_NOT_NULL, code, v8::internal::RelocInfo::CONST_POOL, constant_pool(), contains(), v8::internal::wasm::NativeModule::CreateIndirectCallTargetToFunctionIndexMap(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::RelocInfo::EXTERNAL_REFERENCE, FATAL, v8::internal::wasm::NativeModule::GetCodePointerHandle(), v8::internal::wasm::GetTypeCanonicalizer(), instructions(), v8::internal::RelocInfo::INTERNAL_REFERENCE, v8::internal::RelocInfo::INTERNAL_REFERENCE_ENCODED, kJumpTable, v8::internal::wasm::kV8MaxWasmFunctionParams, v8::internal::wasm::NativeModule::Lookup(), mode(), native_module_, reloc_info(), v8::internal::RelocInfo::VENEER_POOL, v8::internal::RelocInfo::WASM_CALL, v8::internal::RelocInfo::WASM_CANONICAL_SIG_ID, v8::internal::RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY, and v8::internal::RelocInfo::WASM_STUB_CALL.
Friends And Related Function Documentation
NativeModule
friend class NativeModule [friend]
Definition at line 387 of file wasm-code-manager.h.
WasmImportWrapperCache
friend class WasmImportWrapperCache [friend]
Definition at line 388 of file wasm-code-manager.h.
Member Data Documentation
code_comments_offset_
const int v8::internal::wasm::WasmCode::code_comments_offset_ [private]
Definition at line 487 of file wasm-code-manager.h.
Referenced by code_comments(), code_comments_size(), and constant_pool().
constant_pool_offset_
const int v8::internal::wasm::WasmCode::constant_pool_offset_ [private]
Definition at line 476 of file wasm-code-manager.h.
Referenced by constant_pool(), Disassemble(), and handler_table_size().
deopt_data_size_
const int v8::internal::wasm::WasmCode::deopt_data_size_ [private]
Definition at line 473 of file wasm-code-manager.h.
Referenced by Disassemble(), and EstimateCurrentMemoryConsumption().
flags_
const uint8_t v8::internal::wasm::WasmCode::flags_ [private]
Definition at line 492 of file wasm-code-manager.h.
handler_table_offset_
const int v8::internal::wasm::WasmCode::handler_table_offset_ [private]
Definition at line 486 of file wasm-code-manager.h.
Referenced by Disassemble(), handler_table(), and handler_table_size().
index_
const int v8::internal::wasm::WasmCode::index_ [private]
Definition at line 475 of file wasm-code-manager.h.
Referenced by LogCode().
inlining_positions_size_
const int v8::internal::wasm::WasmCode::inlining_positions_size_ [private]
Definition at line 472 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption().
instructions_
uint8_t* const v8::internal::wasm::WasmCode::instructions_ [private]
Definition at line 460 of file wasm-code-manager.h.
instructions_size_
const int v8::internal::wasm::WasmCode::instructions_size_ [private]
Definition at line 469 of file wasm-code-manager.h.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked().
jump_table_info_offset_
const int v8::internal::wasm::WasmCode::jump_table_info_offset_ [private]
Definition at line 488 of file wasm-code-manager.h.
Referenced by code_comments_size(), jump_table_info(), and jump_table_info_size().
kIsDyingMask
constexpr uint32_t v8::internal::wasm::WasmCode::kIsDyingMask = 0x8000'0000u [static], [constexpr], [private]
Definition at line 517 of file wasm-code-manager.h.
Referenced by v8::internal::wasm::WasmImportWrapperCache::Free().
meta_data_
std::unique_ptr<const uint8_t[]> v8::internal::wasm::WasmCode::meta_data_ [private]
Definition at line 468 of file wasm-code-manager.h.
native_module_
NativeModule* const v8::internal::wasm::WasmCode::native_module_ = nullptr [private]
Definition at line 459 of file wasm-code-manager.h.
Referenced by LogCode(), Print(), and Validate().
ool_spills_
const int v8::internal::wasm::WasmCode::ool_spills_ [private]
Definition at line 478 of file wasm-code-manager.h.
protected_instructions_size_
const int v8::internal::wasm::WasmCode::protected_instructions_size_ [private]
Definition at line 474 of file wasm-code-manager.h.
Referenced by Disassemble(), EstimateCurrentMemoryConsumption(), and RegisterTrapHandlerData().
ref_count_bitfield_
std::atomic<uint32_t> v8::internal::wasm::WasmCode::ref_count_bitfield_ {1} [private]
Definition at line 518 of file wasm-code-manager.h.
reloc_info_size_
const int v8::internal::wasm::WasmCode::reloc_info_size_ [private]
Definition at line 470 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption().
safepoint_table_offset_
const int v8::internal::wasm::WasmCode::safepoint_table_offset_ [private]
Definition at line 485 of file wasm-code-manager.h.
Referenced by Disassemble().
signature_hash_
const uint64_t v8::internal::wasm::WasmCode::signature_hash_ [private]
Definition at line 461 of file wasm-code-manager.h.
source_positions_size_
const int v8::internal::wasm::WasmCode::source_positions_size_ [private]
Definition at line 471 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption().
stack_slots_
const int v8::internal::wasm::WasmCode::stack_slots_ [private]
Definition at line 477 of file wasm-code-manager.h.
tagged_parameter_slots_
const uint32_t v8::internal::wasm::WasmCode::tagged_parameter_slots_ [private]
Definition at line 482 of file wasm-code-manager.h.
trap_handler_index_
int v8::internal::wasm::WasmCode::trap_handler_index_ = -1 [private]
Definition at line 490 of file wasm-code-manager.h.
unpadded_binary_size_
const int v8::internal::wasm::WasmCode::unpadded_binary_size_ [private]
Definition at line 489 of file wasm-code-manager.h.
Referenced by Disassemble(), and jump_table_info_size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-code-manager.h
/mnt/V8SourceCode/src/wasm/wasm-code-manager.cc