v8::internal::torque::TypeOracle Class Reference
#include <type-oracle.h>
Static Public Member Functions
static const AbstractType * GetAbstractType (const Type *parent, std::string name, AbstractTypeFlags flags, std::string generated, const Type *non_constexpr_version, MaybeSpecializationKey specialized_from)
static StructType * GetStructType (const StructDeclaration *decl, MaybeSpecializationKey specialized_from)
static BitFieldStructType * GetBitFieldStructType (const Type *parent, const BitFieldStructDeclaration *decl)
static ClassType * GetClassType (const Type *parent, const std::string &name, ClassFlags flags, const std::string &generates, ClassDeclaration *decl, const TypeAlias *alias)
static const BuiltinPointerType * GetBuiltinPointerType (TypeVector argument_types, const Type *return_type)
static const Type * GetGenericTypeInstance (GenericType *generic_type, TypeVector arg_types)
static GenericType * GetReferenceGeneric (bool is_const)
static GenericType * GetConstReferenceGeneric ()
static GenericType * GetMutableReferenceGeneric ()
static std::optional< const Type * > MatchReferenceGeneric (const Type *reference_type, bool *is_const=nullptr)
static GenericType * GetMutableSliceGeneric ()
static GenericType * GetConstSliceGeneric ()
static GenericType * GetWeakGeneric ()
static GenericType * GetSmiTaggedGeneric ()
static GenericType * GetLazyGeneric ()
static const Type * GetReferenceType (const Type *referenced_type, bool is_const)
static const Type * GetConstReferenceType (const Type *referenced_type)
static const Type * GetMutableReferenceType (const Type *referenced_type)
static const Type * GetMutableSliceType (const Type *referenced_type)
static const Type * GetConstSliceType (const Type *referenced_type)
static const std::vector< const BuiltinPointerType * > & AllBuiltinPointerTypes ()
static const Type * GetUnionType (UnionType type)
static const Type * GetUnionType (const Type *a, const Type *b)
static const TopType * GetTopType (std::string reason, const Type *source_type)
static const Type * GetArgumentsType ()
static const Type * GetBoolType ()
static const Type * GetConstexprBoolType ()
static const Type * GetConstexprStringType ()
static const Type * GetConstexprIntPtrType ()
static const Type * GetConstexprInstanceTypeType ()
static const Type * GetVoidType ()
static const Type * GetRawPtrType ()
static const Type * GetExternalPointerType ()
static const Type * GetCppHeapPointerType ()
static const Type * GetTrustedPointerType ()
static const Type * GetProtectedPointerType ()
static const Type * GetDispatchHandleType ()
static const Type * GetMapType ()
static const Type * GetObjectType ()
static const Type * GetHeapObjectType ()
static const Type * GetTaggedZeroPatternType ()
static const Type * GetJSAnyType ()
static const Type * GetJSObjectType ()
static const Type * GetTaggedType ()
static const Type * GetStrongTaggedType ()
static const Type * GetUninitializedHeapObjectType ()
static const Type * GetSmiType ()
static const Type * GetConstStringType ()
static const Type * GetStringType ()
static const Type * GetNumberType ()
static const Type * GetIntPtrType ()
static const Type * GetUIntPtrType ()
static const Type * GetInt64Type ()
static const Type * GetUint64Type ()
static const Type * GetInt32Type ()
static const Type * GetUint32Type ()
static const Type * GetUint31Type ()
static const Type * GetInt16Type ()
static const Type * GetUint16Type ()
static const Type * GetInt8Type ()
static const Type * GetUint8Type ()
static const Type * GetFloat64Type ()
static const Type * GetFloat64OrUndefinedOrHoleType ()
static const Type * GetConstFloat64Type ()
static const Type * GetIntegerLiteralType ()
static const Type * GetNeverType ()
static const Type * GetConstInt31Type ()
static const Type * GetConstInt32Type ()
static const Type * GetContextType ()
static const Type * GetNoContextType ()
static const Type * GetNativeContextType ()
static const Type * GetJSFunctionType ()
static const Type * GetUninitializedIteratorType ()
static const Type * GetFixedArrayBaseType ()
static std::optional< const Type * > ImplicitlyConvertableFrom (const Type *to, const Type *from)
static const std::vector< std::unique_ptr< AggregateType > > & GetAggregateTypes ()
static const std::vector< std::unique_ptr< BitFieldStructType > > & GetBitFieldStructTypes ()
static std::vector< const ClassType * > GetClasses ()
static void FinalizeAggregateTypes ()
static size_t FreshTypeId ()
static Namespace * CreateGenericTypeInstantiationNamespace ()
Private Member Functions
const Type * GetBuiltinType (const QualifiedName &name)
const Type * GetBuiltinType (const std::string &name)
Private Attributes
Deduplicator< BuiltinPointerType > function_pointer_types_
std::vector< const BuiltinPointerType * > all_builtin_pointer_types_
Deduplicator< UnionType > union_types_
std::vector< std::unique_ptr< Type > > nominal_types_
std::vector< std::unique_ptr< AggregateType > > aggregate_types_
std::vector< std::unique_ptr< BitFieldStructType > > bit_field_struct_types_
std::vector< std::unique_ptr< Type > > top_types_
std::vector< std::unique_ptr< Namespace > > generic_type_instantiation_namespaces_
size_t next_type_id_ = 0
Additional Inherited Members
Detailed Description
Definition at line 20 of file type-oracle.h.
Member Function Documentation
AllBuiltinPointerTypes()
static const std::vector<const BuiltinPointerType*>& v8::internal::torque::TypeOracle::AllBuiltinPointerTypes () [inline], [static]
Definition at line 141 of file type-oracle.h.
                           {
    return Get().all_builtin_pointer_types_;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
CreateGenericTypeInstantiationNamespace()
Namespace * v8::internal::torque::TypeOracle::CreateGenericTypeInstantiationNamespace () [static]
Definition at line 65 of file type-oracle.cc.
                                                               {
  Get().generic_type_instantiation_namespaces_.push_back(
      std::make_unique<Namespace>(GENERIC_TYPE_INSTANTIATION_NAMESPACE_STRING));
  return Get().generic_type_instantiation_namespaces_.back().get();
}
References v8::internal::torque::GENERIC_TYPE_INSTANTIATION_NAMESPACE_STRING, and v8::internal::compiler::turboshaft::Get().
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
FinalizeAggregateTypes()
void v8::internal::torque::TypeOracle::FinalizeAggregateTypes () [static]
Definition at line 27 of file type-oracle.cc.
                                        {
  size_t current = 0;
  while (current != Get().aggregate_types_.size()) {
    auto& p = Get().aggregate_types_[current++];
    p->Finalize();
  }
}
References aggregate_types_, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
FreshTypeId()
static size_t v8::internal::torque::TypeOracle::FreshTypeId () [inline], [static]
Definition at line 398 of file type-oracle.h.
{ return Get().next_type_id_++; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
GetAbstractType()
static const AbstractType* v8::internal::torque::TypeOracle::GetAbstractType (const Type * parent, std::string name, AbstractTypeFlags flags, std::string generated, const Type * non_constexpr_version, MaybeSpecializationKey specialized_from) [inline], [static]
Definition at line 22 of file type-oracle.h.
                                               {
    auto ptr = std::unique_ptr<AbstractType>(
        new AbstractType(parent, flags, std::move(name), std::move(generated),
                         non_constexpr_version, specialized_from));
    const AbstractType* result = ptr.get();
    if (non_constexpr_version) {
      DCHECK(ptr->IsConstexpr());
      non_constexpr_version->SetConstexprVersion(result);
    }
    Get().nominal_types_.push_back(std::move(ptr));
    return result;
  }
References v8::internal::DCHECK(), v8::internal::flags, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::name, v8::base::internal::result, and v8::internal::torque::Type::SetConstexprVersion().
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
GetAggregateTypes()
const std::vector< std::unique_ptr< AggregateType > > & v8::internal::torque::TypeOracle::GetAggregateTypes () [static]
Definition at line 16 of file type-oracle.cc.
                              {
  return Get().aggregate_types_;
}
References v8::base::ContextualVariable< Derived, VarType >::Get().
GetArgumentsType()
static const Type* v8::internal::torque::TypeOracle::GetArgumentsType () [inline], [static]
Definition at line 168 of file type-oracle.h.
                                        {
    return Get().GetBuiltinType(ARGUMENTS_TYPE_STRING);
  }
References v8::internal::torque::ARGUMENTS_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetBitFieldStructType()
static BitFieldStructType* v8::internal::torque::TypeOracle::GetBitFieldStructType (const Type * parent, const BitFieldStructDeclaration * decl) [inline], [static]
Definition at line 47 of file type-oracle.h.
                                                                 {
    auto ptr = std::unique_ptr<BitFieldStructType>(
        new BitFieldStructType(CurrentNamespace(), parent, decl));
    BitFieldStructType* result = ptr.get();
    Get().bit_field_struct_types_.push_back(std::move(ptr));
    return result;
  }
References v8::internal::torque::CurrentNamespace(), v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::base::internal::result.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
GetBitFieldStructTypes()
const std::vector< std::unique_ptr< BitFieldStructType > > & v8::internal::torque::TypeOracle::GetBitFieldStructTypes () [static]
Definition at line 22 of file type-oracle.cc.
                                   {
  return Get().bit_field_struct_types_;
}
References v8::base::ContextualVariable< Derived, VarType >::Get().
GetBoolType()
static const Type* v8::internal::torque::TypeOracle::GetBoolType () [inline], [static]
Definition at line 172 of file type-oracle.h.
                                   {
    return Get().GetBuiltinType(BOOL_TYPE_STRING);
  }
References v8::internal::torque::BOOL_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::Is32BitIntegralType(), and v8::internal::torque::ImplementationVisitor::Visit().
GetBuiltinPointerType()
static const BuiltinPointerType* v8::internal::torque::TypeOracle::GetBuiltinPointerType (TypeVector argument_types, const Type * return_type) [inline], [static]
Definition at line 67 of file type-oracle.h.
                                                          {
    TypeOracle& self = Get();
    const Type* builtin_type = self.GetBuiltinType(BUILTIN_POINTER_TYPE_STRING);
    const BuiltinPointerType* result = self.function_pointer_types_.Add(
        BuiltinPointerType(builtin_type, std::move(argument_types), return_type,
                           self.all_builtin_pointer_types_.size()));
    if (result->function_pointer_type_id() ==
        self.all_builtin_pointer_types_.size()) {
      self.all_builtin_pointer_types_.push_back(result);
    }
    return result;
  }
References all_builtin_pointer_types_, v8::internal::torque::BUILTIN_POINTER_TYPE_STRING, v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::base::internal::result.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::ImplementationVisitor::GetBuiltinCode().
GetBuiltinType() [1/2]
const Type* v8::internal::torque::TypeOracle::GetBuiltinType (const QualifiedName & name) [inline], [private]
Definition at line 403 of file type-oracle.h.
                                                        {
    return Declarations::LookupGlobalType(name);
  }
References v8::internal::torque::Declarations::LookupGlobalType(), and v8::internal::name.
Referenced by GetBuiltinType().
GetBuiltinType() [2/2]
const Type* v8::internal::torque::TypeOracle::GetBuiltinType (const std::string & name) [inline], [private]
Definition at line 406 of file type-oracle.h.
                                                    {
    return GetBuiltinType(QualifiedName(name));
  }
References GetBuiltinType(), and v8::internal::name.
GetClasses()
std::vector< const ClassType * > v8::internal::torque::TypeOracle::GetClasses () [static]
Definition at line 72 of file type-oracle.cc.
                                                   {
  std::vector<const ClassType*> result;
  for (const std::unique_ptr<AggregateType>& t : Get().aggregate_types_) {
    if (auto* class_type = ClassType::DynamicCast(t.get())) {
      result.push_back(class_type);
    }
  }
  return result;
}
References v8::internal::compiler::turboshaft::Get(), and v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), v8::internal::torque::ImplementationVisitor::GenerateClassDebugReaders(), and v8::internal::torque::ImplementationVisitor::GenerateInstanceTypes().
GetClassType()
static ClassType* v8::internal::torque::TypeOracle::GetClassType (const Type * parent, const std::string & name, ClassFlags flags, const std::string & generates, ClassDeclaration * decl, const TypeAlias * alias) [inline], [static]
Definition at line 56 of file type-oracle.h.
                                                         {
    std::unique_ptr<ClassType> type(new ClassType(
        parent, CurrentNamespace(), name, flags, generates, decl, alias));
    ClassType* result = type.get();
    Get().aggregate_types_.push_back(std::move(type));
    return result;
  }
References v8::internal::torque::CurrentNamespace(), v8::internal::flags, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::name, v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
GetConstexprBoolType()
static const Type* v8::internal::torque::TypeOracle::GetConstexprBoolType () [inline], [static]
Definition at line 176 of file type-oracle.h.
                                            {
    return Get().GetBuiltinType(CONSTEXPR_BOOL_TYPE_STRING);
  }
References v8::internal::torque::CONSTEXPR_BOOL_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetConstexprInstanceTypeType()
static const Type* v8::internal::torque::TypeOracle::GetConstexprInstanceTypeType () [inline], [static]
Definition at line 188 of file type-oracle.h.
                                                    {
    return Get().GetBuiltinType(CONSTEXPR_INSTANCE_TYPE_TYPE_STRING);
  }
References v8::internal::torque::CONSTEXPR_INSTANCE_TYPE_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetConstexprIntPtrType()
static const Type* v8::internal::torque::TypeOracle::GetConstexprIntPtrType () [inline], [static]
Definition at line 184 of file type-oracle.h.
                                              {
    return Get().GetBuiltinType(CONSTEXPR_INTPTR_TYPE_STRING);
  }
References v8::internal::torque::CONSTEXPR_INTPTR_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
GetConstexprStringType()
static const Type* v8::internal::torque::TypeOracle::GetConstexprStringType () [inline], [static]
Definition at line 180 of file type-oracle.h.
                                              {
    return Get().GetBuiltinType(CONSTEXPR_STRING_TYPE_STRING);
  }
References v8::internal::torque::CONSTEXPR_STRING_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetConstFloat64Type()
static const Type* v8::internal::torque::TypeOracle::GetConstFloat64Type () [inline], [static]
Definition at line 326 of file type-oracle.h.
                                           {
    return Get().GetBuiltinType(CONST_FLOAT64_TYPE_STRING);
  }
References v8::internal::torque::CONST_FLOAT64_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetConstInt31Type()
static const Type* v8::internal::torque::TypeOracle::GetConstInt31Type () [inline], [static]
Definition at line 338 of file type-oracle.h.
                                         {
    return Get().GetBuiltinType(CONST_INT31_TYPE_STRING);
  }
References v8::internal::torque::CONST_INT31_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldReference(), v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization(), and v8::internal::torque::ImplementationVisitor::Visit().
GetConstInt32Type()
static const Type* v8::internal::torque::TypeOracle::GetConstInt32Type () [inline], [static]
Definition at line 342 of file type-oracle.h.
                                         {
    return Get().GetBuiltinType(CONST_INT32_TYPE_STRING);
  }
References v8::internal::torque::CONST_INT32_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetConstReferenceGeneric()
static GenericType* v8::internal::torque::TypeOracle::GetConstReferenceGeneric () [inline], [static]
Definition at line 90 of file type-oracle.h.
                                                 {
    return GetReferenceGeneric(true);
  }
References GetReferenceGeneric().
GetConstReferenceType()
static const Type* v8::internal::torque::TypeOracle::GetConstReferenceType (const Type * referenced_type) [inline], [static]
Definition at line 126 of file type-oracle.h.
                                                                        {
    return GetReferenceType(referenced_type, true);
  }
References GetReferenceType().
GetConstSliceGeneric()
static GenericType* v8::internal::torque::TypeOracle::GetConstSliceGeneric () [inline], [static]
Definition at line 104 of file type-oracle.h.
                                             {
    return Declarations::LookupUniqueGenericType(
        QualifiedName(CONST_SLICE_TYPE_STRING));
  }
References v8::internal::torque::CONST_SLICE_TYPE_STRING, and v8::internal::torque::Declarations::LookupUniqueGenericType().
Referenced by GetConstSliceType(), v8::internal::torque::LocationReference::HeapSlice(), and v8::internal::torque::LocationReference::ReferencedType().
GetConstSliceType()
static const Type* v8::internal::torque::TypeOracle::GetConstSliceType (const Type * referenced_type) [inline], [static]
Definition at line 136 of file type-oracle.h.
                                                                    {
    return GetGenericTypeInstance(GetConstSliceGeneric(), {referenced_type});
  }
References GetConstSliceGeneric(), and GetGenericTypeInstance().
Referenced by v8::internal::torque::ClassType::GenerateSliceAccessor().
GetConstStringType()
static const Type* v8::internal::torque::TypeOracle::GetConstStringType () [inline], [static]
Definition at line 262 of file type-oracle.h.
                                          {
    return Get().GetBuiltinType(CONST_STRING_TYPE_STRING);
  }
References v8::internal::torque::CONST_STRING_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetContextType()
static const Type* v8::internal::torque::TypeOracle::GetContextType () [inline], [static]
Definition at line 346 of file type-oracle.h.
                                      {
    return Get().GetBuiltinType(CONTEXT_TYPE_STRING);
  }
References v8::internal::torque::CONTEXT_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{types.cc}::FirstTypeIsContext(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::DeclarationVisitor::Visit().
GetCppHeapPointerType()
static const Type* v8::internal::torque::TypeOracle::GetCppHeapPointerType () [inline], [static]
Definition at line 204 of file type-oracle.h.
                                             {
    return Get().GetBuiltinType(CPPHEAPPTR_TYPE_STRING);
  }
References v8::internal::torque::CPPHEAPPTR_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
GetDispatchHandleType()
static const Type* v8::internal::torque::TypeOracle::GetDispatchHandleType () [inline], [static]
Definition at line 216 of file type-oracle.h.
                                             {
    return Get().GetBuiltinType(DISPATCH_HANDLE_TYPE_STRING);
  }
References v8::internal::torque::DISPATCH_HANDLE_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetExternalPointerType()
static const Type* v8::internal::torque::TypeOracle::GetExternalPointerType () [inline], [static]
Definition at line 200 of file type-oracle.h.
                                              {
    return Get().GetBuiltinType(EXTERNALPTR_TYPE_STRING);
  }
References v8::internal::torque::EXTERNALPTR_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
GetFixedArrayBaseType()
static const Type* v8::internal::torque::TypeOracle::GetFixedArrayBaseType () [inline], [static]
Definition at line 366 of file type-oracle.h.
                                             {
    return Get().GetBuiltinType(FIXED_ARRAY_BASE_TYPE_STRING);
  }
References v8::internal::torque::FIXED_ARRAY_BASE_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
GetFloat64OrUndefinedOrHoleType()
static const Type* v8::internal::torque::TypeOracle::GetFloat64OrUndefinedOrHoleType () [inline], [static]
Definition at line 322 of file type-oracle.h.
                                                       {
    return Get().GetBuiltinType(FLOAT64_OR_UNDEFINED_OR_HOLE_TYPE_STRING);
  }
References v8::internal::torque::FLOAT64_OR_UNDEFINED_OR_HOLE_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::StructType::AlignmentLog2(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldsRange::end(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::SizeOf(), and v8::internal::torque::Field::ValidateAlignment().
GetFloat64Type()
static const Type* v8::internal::torque::TypeOracle::GetFloat64Type () [inline], [static]
Definition at line 318 of file type-oracle.h.
                                      {
    return Get().GetBuiltinType(FLOAT64_TYPE_STRING);
  }
References v8::internal::torque::FLOAT64_TYPE_STRING, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::StructType::AlignmentLog2(), and v8::internal::torque::SizeOf().
GetGenericTypeInstance()
const Type * v8::internal::torque::TypeOracle::GetGenericTypeInstance (GenericType * generic_type, TypeVector arg_types) [static]
Definition at line 36 of file type-oracle.cc.
                                                                     {
  auto& params = generic_type->generic_parameters();
  if (params.size() != arg_types.size()) {
    ReportError("Generic struct takes ", params.size(), " parameters, but ",
                arg_types.size(), " were given");
  }
  if (auto specialization = generic_type->GetSpecialization(arg_types)) {
    return *specialization;
  } else {
    const Type* type = nullptr;
    // AddSpecialization can raise an error, which should be reported in the
    // scope of the code requesting the specialization, not the generic type's
    // parent scope, hence the following block.
    {
      v8::internal::torque::Scope* requester_scope = CurrentScope::Get();
      CurrentScope::Scope generic_scope(generic_type->ParentScope());
      type = TypeVisitor::ComputeType(generic_type->declaration(),
                                      {{generic_type, arg_types}},
                                      requester_scope);
    }
    generic_type->AddSpecialization(arg_types, type);
    return type;
  }
}
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::AddSpecialization(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::declaration(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::generic_parameters(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::GetSpecialization(), v8::internal::torque::Declarable::ParentScope(), v8::internal::torque::ReportError(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression(), GetConstSliceType(), GetMutableSliceType(), and GetReferenceType().
GetHeapObjectType()
static const Type* v8::internal::torque::TypeOracle::GetHeapObjectType () [inline], [static]
Definition at line 228 of file type-oracle.h.
                                         {
    return Get().GetBuiltinType(HEAP_OBJECT_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::HEAP_OBJECT_TYPE_STRING.
GetInt16Type()
static const Type* v8::internal::torque::TypeOracle::GetInt16Type () [inline], [static]
Definition at line 302 of file type-oracle.h.
                                    {
    return Get().GetBuiltinType(INT16_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::INT16_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
GetInt32Type()
static const Type* v8::internal::torque::TypeOracle::GetInt32Type () [inline], [static]
Definition at line 290 of file type-oracle.h.
                                    {
    return Get().GetBuiltinType(INT32_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::INT32_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::Is32BitIntegralType(), v8::internal::torque::SizeOf(), and v8::internal::torque::ImplementationVisitor::Visit().
GetInt64Type()
static const Type* v8::internal::torque::TypeOracle::GetInt64Type () [inline], [static]
Definition at line 282 of file type-oracle.h.
                                    {
    return Get().GetBuiltinType(INT64_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::INT64_TYPE_STRING.
GetInt8Type()
static const Type* v8::internal::torque::TypeOracle::GetInt8Type () [inline], [static]
Definition at line 310 of file type-oracle.h.
                                   {
    return Get().GetBuiltinType(INT8_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::INT8_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
GetIntegerLiteralType()
static const Type* v8::internal::torque::TypeOracle::GetIntegerLiteralType () [inline], [static]
Definition at line 330 of file type-oracle.h.
                                             {
    return Get().GetBuiltinType(INTEGER_LITERAL_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::INTEGER_LITERAL_TYPE_STRING.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetIntPtrType()
static const Type* v8::internal::torque::TypeOracle::GetIntPtrType () [inline], [static]
Definition at line 274 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(INTPTR_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::INTPTR_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::ImplementationVisitor::GenerateArrayLength(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit(), v8::internal::torque::IsPointerSizeIntegralType(), and v8::internal::torque::SizeOf().
GetJSAnyType()
static const Type* v8::internal::torque::TypeOracle::GetJSAnyType () [inline], [static]
Definition at line 236 of file type-oracle.h.
                                    {
    return Get().GetBuiltinType(JSANY_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::JSANY_TYPE_STRING.
Referenced by v8::internal::torque::DeclarationVisitor::CreateBuiltin(), and v8::internal::torque::ImplementationVisitor::Visit().
GetJSFunctionType()
static const Type* v8::internal::torque::TypeOracle::GetJSFunctionType () [inline], [static]
Definition at line 358 of file type-oracle.h.
                                         {
    return Get().GetBuiltinType(JS_FUNCTION_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::JS_FUNCTION_TYPE_STRING.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GetJSObjectType()
static const Type* v8::internal::torque::TypeOracle::GetJSObjectType () [inline], [static]
Definition at line 240 of file type-oracle.h.
                                       {
    return Get().GetBuiltinType(JSOBJECT_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::JSOBJECT_TYPE_STRING.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::ClassType::HasStaticSize().
GetLazyGeneric()
static GenericType* v8::internal::torque::TypeOracle::GetLazyGeneric () [inline], [static]
Definition at line 117 of file type-oracle.h.
                                       {
    return Declarations::LookupGlobalUniqueGenericType(LAZY_TYPE_STRING);
  }
References v8::internal::torque::LAZY_TYPE_STRING, and v8::internal::torque::Declarations::LookupGlobalUniqueGenericType().
GetMapType()
static const Type* v8::internal::torque::TypeOracle::GetMapType () [inline], [static]
Definition at line 220 of file type-oracle.h.
                                  {
    return Get().GetBuiltinType(MAP_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::MAP_TYPE_STRING.
Referenced by v8::internal::torque::ClassType::HasNoPointerSlotsExceptMap().
GetMutableReferenceGeneric()
static GenericType* v8::internal::torque::TypeOracle::GetMutableReferenceGeneric () [inline], [static]
Definition at line 93 of file type-oracle.h.
                                                   {
    return GetReferenceGeneric(false);
  }
References GetReferenceGeneric().
GetMutableReferenceType()
static const Type* v8::internal::torque::TypeOracle::GetMutableReferenceType (const Type * referenced_type) [inline], [static]
Definition at line 129 of file type-oracle.h.
                                                                          {
    return GetReferenceType(referenced_type, false);
  }
References GetReferenceType().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit().
GetMutableSliceGeneric()
static GenericType* v8::internal::torque::TypeOracle::GetMutableSliceGeneric () [inline], [static]
Definition at line 100 of file type-oracle.h.
                                               {
    return Declarations::LookupUniqueGenericType(
        QualifiedName(MUTABLE_SLICE_TYPE_STRING));
  }
References v8::internal::torque::Declarations::LookupUniqueGenericType(), and v8::internal::torque::MUTABLE_SLICE_TYPE_STRING.
Referenced by GetMutableSliceType(), v8::internal::torque::LocationReference::HeapSlice(), and v8::internal::torque::LocationReference::ReferencedType().
GetMutableSliceType()
static const Type* v8::internal::torque::TypeOracle::GetMutableSliceType (const Type * referenced_type) [inline], [static]
Definition at line 133 of file type-oracle.h.
                                                                      {
    return GetGenericTypeInstance(GetMutableSliceGeneric(), {referenced_type});
  }
References GetGenericTypeInstance(), and GetMutableSliceGeneric().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit(), and v8::internal::torque::ClassType::GenerateSliceAccessor().
GetNativeContextType()
static const Type* v8::internal::torque::TypeOracle::GetNativeContextType () [inline], [static]
Definition at line 354 of file type-oracle.h.
                                            {
    return Get().GetBuiltinType(NATIVE_CONTEXT_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::NATIVE_CONTEXT_TYPE_STRING.
Referenced by v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::DeclarationVisitor::Visit().
GetNeverType()
static const Type* v8::internal::torque::TypeOracle::GetNeverType () [inline], [static]
Definition at line 334 of file type-oracle.h.
                                    {
    return Get().GetBuiltinType(NEVER_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::NEVER_TYPE_STRING.
Referenced by v8::internal::torque::CallCsaMacroAndBranchInstruction::GetValueDefinitionCount(), v8::internal::torque::CallRuntimeInstruction::GetValueDefinitionCount(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::torque::CallRuntimeInstruction::IsBlockTerminator(), v8::internal::torque::VisitResult::NeverResult(), v8::internal::torque::DeclarationVisitor::Visit(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
GetNoContextType()
static const Type* v8::internal::torque::TypeOracle::GetNoContextType () [inline], [static]
Definition at line 350 of file type-oracle.h.
                                        {
    return Get().GetBuiltinType(NO_CONTEXT_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::NO_CONTEXT_TYPE_STRING.
Referenced by v8::internal::torque::anonymous_namespace{types.cc}::FirstTypeIsContext(), and v8::internal::torque::DeclarationVisitor::Visit().
GetNumberType()
static const Type* v8::internal::torque::TypeOracle::GetNumberType () [inline], [static]
Definition at line 270 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(NUMBER_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::NUMBER_TYPE_STRING.
GetObjectType()
static const Type* v8::internal::torque::TypeOracle::GetObjectType () [inline], [static]
Definition at line 224 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(OBJECT_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::OBJECT_TYPE_STRING.
Referenced by v8::internal::torque::anonymous_namespace{types.cc}::ComputeSlotKindsHelper(), v8::internal::torque::LowerParameterTypes(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
GetProtectedPointerType()
static const Type* v8::internal::torque::TypeOracle::GetProtectedPointerType () [inline], [static]
Definition at line 212 of file type-oracle.h.
                                               {
    return Get().GetBuiltinType(PROTECTEDPTR_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::PROTECTEDPTR_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
GetRawPtrType()
static const Type* v8::internal::torque::TypeOracle::GetRawPtrType () [inline], [static]
Definition at line 196 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(RAWPTR_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::RAWPTR_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
GetReferenceGeneric()
static GenericType* v8::internal::torque::TypeOracle::GetReferenceGeneric (bool is_const) [inline], [static]
Definition at line 84 of file type-oracle.h.
                                                         {
    return Declarations::LookupUniqueGenericType(
        QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING},
                      is_const ? CONST_REFERENCE_TYPE_STRING
                               : MUTABLE_REFERENCE_TYPE_STRING));
  }
References v8::internal::torque::CONST_REFERENCE_TYPE_STRING, v8::internal::torque::Declarations::LookupUniqueGenericType(), v8::internal::torque::MUTABLE_REFERENCE_TYPE_STRING, and v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING.
Referenced by GetConstReferenceGeneric(), GetMutableReferenceGeneric(), and GetReferenceType().
GetReferenceType()
static const Type* v8::internal::torque::TypeOracle::GetReferenceType (const Type * referenced_type, bool is_const) [inline], [static]
Definition at line 121 of file type-oracle.h.
                                                     {
    return GetGenericTypeInstance(GetReferenceGeneric(is_const),
                                  {referenced_type});
  }
References GetGenericTypeInstance(), and GetReferenceGeneric().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), GetConstReferenceType(), and GetMutableReferenceType().
GetSmiTaggedGeneric()
static GenericType* v8::internal::torque::TypeOracle::GetSmiTaggedGeneric () [inline], [static]
Definition at line 113 of file type-oracle.h.
                                            {
    return Declarations::LookupGlobalUniqueGenericType(SMI_TAGGED_TYPE_STRING);
  }
References v8::internal::torque::Declarations::LookupGlobalUniqueGenericType(), and v8::internal::torque::SMI_TAGGED_TYPE_STRING.
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldsRange::end(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::anonymous_namespace{csa-generator.cc}::GetBitFieldSpecialization(), and v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::operator*().
GetSmiType()
static const Type* v8::internal::torque::TypeOracle::GetSmiType () [inline], [static]
Definition at line 258 of file type-oracle.h.
                                  {
    return Get().GetBuiltinType(SMI_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::SMI_TYPE_STRING.
GetStringType()
static const Type* v8::internal::torque::TypeOracle::GetStringType () [inline], [static]
Definition at line 266 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(STRING_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::STRING_TYPE_STRING.
GetStrongTaggedType()
static const Type* v8::internal::torque::TypeOracle::GetStrongTaggedType () [inline], [static]
Definition at line 248 of file type-oracle.h.
                                           {
    return Get().GetBuiltinType(STRONG_TAGGED_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::STRONG_TAGGED_TYPE_STRING.
Referenced by v8::internal::torque::StructType::ClassifyContents(), v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::DeclarationVisitor::Visit().
GetStructType()
static StructType* v8::internal::torque::TypeOracle::GetStructType (const StructDeclaration * decl, MaybeSpecializationKey specialized_from) [inline], [static]
Definition at line 38 of file type-oracle.h.
                                                                            {
    auto ptr = std::unique_ptr<StructType>(
        new StructType(CurrentNamespace(), decl, specialized_from));
    StructType* result = ptr.get();
    Get().aggregate_types_.push_back(std::move(ptr));
    return result;
  }
References v8::internal::torque::CurrentNamespace(), v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::base::internal::result.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
GetTaggedType()
static const Type* v8::internal::torque::TypeOracle::GetTaggedType () [inline], [static]
Definition at line 244 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(TAGGED_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::TAGGED_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::StructType::ClassifyContents(), v8::internal::torque::anonymous_namespace{types.cc}::ComputeSlotKindsHelper(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::IsTagged(), and v8::internal::torque::SizeOf().
GetTaggedZeroPatternType()
static const Type* v8::internal::torque::TypeOracle::GetTaggedZeroPatternType () [inline], [static]
Definition at line 232 of file type-oracle.h.
                                                {
    return Get().GetBuiltinType(TAGGED_ZERO_PATTERN_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::TAGGED_ZERO_PATTERN_TYPE_STRING.
GetTopType()
static const TopType* v8::internal::torque::TypeOracle::GetTopType (std::string reason, const Type * source_type) [inline], [static]
Definition at line 160 of file type-oracle.h.
                                                            {
    std::unique_ptr<TopType> type(new TopType(std::move(reason), source_type));
    TopType* result = type.get();
    Get().top_types_.push_back(std::move(type));
    return result;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::internal::torque::InstructionBase::InvalidateTransientTypes(), v8::internal::torque::VisitResult::TopTypeResult(), and v8::internal::torque::ImplementationVisitor::Visit().
GetTrustedPointerType()
static const Type* v8::internal::torque::TypeOracle::GetTrustedPointerType () [inline], [static]
Definition at line 208 of file type-oracle.h.
                                             {
    return Get().GetBuiltinType(TRUSTEDPTR_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::TRUSTEDPTR_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
GetUint16Type()
static const Type* v8::internal::torque::TypeOracle::GetUint16Type () [inline], [static]
Definition at line 306 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(UINT16_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::UINT16_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::IsAnyUnsignedInteger(), and v8::internal::torque::SizeOf().
GetUint31Type()
static const Type* v8::internal::torque::TypeOracle::GetUint31Type () [inline], [static]
Definition at line 298 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(UINT31_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::UINT31_TYPE_STRING.
Referenced by v8::internal::torque::IsAnyUnsignedInteger().
GetUint32Type()
static const Type* v8::internal::torque::TypeOracle::GetUint32Type () [inline], [static]
Definition at line 294 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(UINT32_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::UINT32_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::Is32BitIntegralType(), v8::internal::torque::IsAnyUnsignedInteger(), and v8::internal::torque::SizeOf().
GetUint64Type()
static const Type* v8::internal::torque::TypeOracle::GetUint64Type () [inline], [static]
Definition at line 286 of file type-oracle.h.
                                     {
    return Get().GetBuiltinType(UINT64_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::UINT64_TYPE_STRING.
GetUint8Type()
static const Type* v8::internal::torque::TypeOracle::GetUint8Type () [inline], [static]
Definition at line 314 of file type-oracle.h.
                                    {
    return Get().GetBuiltinType(UINT8_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::UINT8_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::IsAnyUnsignedInteger(), and v8::internal::torque::SizeOf().
GetUIntPtrType()
static const Type* v8::internal::torque::TypeOracle::GetUIntPtrType () [inline], [static]
Definition at line 278 of file type-oracle.h.
                                      {
    return Get().GetBuiltinType(UINTPTR_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::UINTPTR_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::IsAnyUnsignedInteger(), v8::internal::torque::IsPointerSizeIntegralType(), and v8::internal::torque::SizeOf().
GetUninitializedHeapObjectType()
static const Type* v8::internal::torque::TypeOracle::GetUninitializedHeapObjectType () [inline], [static]
Definition at line 252 of file type-oracle.h.
                                                      {
    return Get().GetBuiltinType(
        QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING},
                      UNINITIALIZED_HEAP_OBJECT_TYPE_STRING));
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING, and v8::internal::torque::UNINITIALIZED_HEAP_OBJECT_TYPE_STRING.
GetUninitializedIteratorType()
static const Type* v8::internal::torque::TypeOracle::GetUninitializedIteratorType () [inline], [static]
Definition at line 362 of file type-oracle.h.
                                                    {
    return Get().GetBuiltinType(UNINITIALIZED_ITERATOR_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::UNINITIALIZED_ITERATOR_TYPE_STRING.
GetUnionType() [1/2]
static const Type* v8::internal::torque::TypeOracle::GetUnionType (const Type * a, const Type * b) [inline], [static]
Definition at line 152 of file type-oracle.h.
                                                                {
    if (a->IsSubtypeOf(b)) return b;
    if (b->IsSubtypeOf(a)) return a;
    UnionType result = UnionType::FromType(a);
    result.Extend(b);
    return GetUnionType(std::move(result));
  }
References v8::internal::torque::UnionType::FromType(), GetUnionType(), v8::internal::torque::Type::IsSubtypeOf(), and v8::base::internal::result.
GetUnionType() [2/2]
static const Type* v8::internal::torque::TypeOracle::GetUnionType (UnionType type) [inline], [static]
Definition at line 145 of file type-oracle.h.
                                                  {
    if (std::optional<const Type*> single = type.GetSingleMember()) {
      return *single;
    }
    return Get().union_types_.Add(std::move(type));
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::ImplementationVisitor::GetCommonType(), GetUnionType(), and v8::internal::torque::Block::SetInputTypes().
GetVoidType()
static const Type* v8::internal::torque::TypeOracle::GetVoidType () [inline], [static]
Definition at line 192 of file type-oracle.h.
                                   {
    return Get().GetBuiltinType(VOID_TYPE_STRING);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::VOID_TYPE_STRING.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::DeclarationVisitor::CreateBuiltin(), v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateClassDebugReader(), v8::internal::torque::SizeOf(), v8::internal::torque::DeclarationVisitor::Visit(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
GetWeakGeneric()
static GenericType* v8::internal::torque::TypeOracle::GetWeakGeneric () [inline], [static]
Definition at line 109 of file type-oracle.h.
                                       {
    return Declarations::LookupGlobalUniqueGenericType(WEAK_TYPE_STRING);
  }
References v8::internal::torque::Declarations::LookupGlobalUniqueGenericType(), and v8::internal::torque::WEAK_TYPE_STRING.
ImplicitlyConvertableFrom()
static std::optional<const Type*> v8::internal::torque::TypeOracle::ImplicitlyConvertableFrom (const Type * to, const Type * from) [inline], [static]
Definition at line 370 of file type-oracle.h.
                                        {
    while (from != nullptr) {
      for (GenericCallable* from_constexpr :
           Declarations::LookupGeneric(kFromConstexprMacroName)) {
        if (std::optional<const Callable*> specialization =
                from_constexpr->GetSpecialization({to, from})) {
          if ((*specialization)->signature().GetExplicitTypes() ==
              TypeVector{from}) {
            return from;
          }
        }
      }
      from = from->parent();
    }
    return std::nullopt;
  }
References v8::internal::torque::kFromConstexprMacroName, v8::internal::torque::Declarations::LookupGeneric(), and v8::internal::torque::Type::parent().
Referenced by v8::internal::torque::IsAssignableFrom().
MatchReferenceGeneric()
std::optional< const Type * > v8::internal::torque::TypeOracle::MatchReferenceGeneric (const Type * reference_type, bool * is_const = nullptr) [static]
Definition at line 82 of file type-oracle.cc.
                                                {
  if (auto type = Type::MatchUnaryGeneric(reference_type,
                                          GetMutableReferenceGeneric())) {
    if (is_const) *is_const = false;
    return type;
  }
  if (auto type =
          Type::MatchUnaryGeneric(reference_type, GetConstReferenceGeneric())) {
    if (is_const) *is_const = true;
    return type;
  }
  return std::nullopt;
}
References v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::LocationReference::HeapReference(), v8::internal::torque::LocationReference::IsConst(), and v8::internal::torque::LocationReference::ReferencedType().
Member Data Documentation
aggregate_types_
std::vector<std::unique_ptr<AggregateType> > v8::internal::torque::TypeOracle::aggregate_types_ [private]
Definition at line 414 of file type-oracle.h.
Referenced by FinalizeAggregateTypes().
all_builtin_pointer_types_
std::vector<const BuiltinPointerType*> v8::internal::torque::TypeOracle::all_builtin_pointer_types_ [private]
Definition at line 411 of file type-oracle.h.
Referenced by GetBuiltinPointerType().
bit_field_struct_types_
std::vector<std::unique_ptr<BitFieldStructType> > v8::internal::torque::TypeOracle::bit_field_struct_types_ [private]
Definition at line 415 of file type-oracle.h.
function_pointer_types_
Deduplicator<BuiltinPointerType> v8::internal::torque::TypeOracle::function_pointer_types_ [private]
Definition at line 410 of file type-oracle.h.
generic_type_instantiation_namespaces_
std::vector<std::unique_ptr<Namespace> > v8::internal::torque::TypeOracle::generic_type_instantiation_namespaces_ [private]
Definition at line 418 of file type-oracle.h.
next_type_id_
size_t v8::internal::torque::TypeOracle::next_type_id_ = 0 [private]
Definition at line 419 of file type-oracle.h.
nominal_types_
std::vector<std::unique_ptr<Type> > v8::internal::torque::TypeOracle::nominal_types_ [private]
Definition at line 413 of file type-oracle.h.
top_types_
std::vector<std::unique_ptr<Type> > v8::internal::torque::TypeOracle::top_types_ [private]
Definition at line 416 of file type-oracle.h.
union_types_
Deduplicator<UnionType> v8::internal::torque::TypeOracle::union_types_ [private]
Definition at line 412 of file type-oracle.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/type-oracle.h
/mnt/V8SourceCode/src/torque/type-oracle.cc