v8::internal::DebuggableStackFrameIterator Class Reference
#include <frames.h>
Public Member Functions
DebuggableStackFrameIterator (Isolate *isolate)
DebuggableStackFrameIterator (Isolate *isolate, StackFrameId id)
bool done () const
void Advance ()
int FrameFunctionCount () const
CommonFrame * frame () const
CommonFrame * Reframe ()
bool is_javascript () const
JavaScriptFrame * javascript_frame () const
FrameSummary GetTopValidFrame () const
Static Private Member Functions
static bool IsValidFrame (StackFrame *frame)
Private Attributes
StackFrameIterator iterator_
Detailed Description
Definition at line 1761 of file frames.h.
Constructor & Destructor Documentation
DebuggableStackFrameIterator() [1/2]
v8::internal::DebuggableStackFrameIterator::DebuggableStackFrameIterator (Isolate * isolate) [explicit]
Definition at line 364 of file frames.cc.
    : iterator_(isolate) {
  if (!done() && !IsValidFrame(iterator_.frame())) Advance();
}
References Advance(), done(), v8::internal::StackFrameIterator::frame(), IsValidFrame(), and iterator_.
DebuggableStackFrameIterator() [2/2]
v8::internal::DebuggableStackFrameIterator::DebuggableStackFrameIterator (Isolate * isolate, StackFrameId id)
Definition at line 369 of file frames.cc.
    : DebuggableStackFrameIterator(isolate) {
  while (!done() && frame()->id() != id) Advance();
}
References Advance(), done(), and frame().
Member Function Documentation
Advance()
void v8::internal::DebuggableStackFrameIterator::Advance ()
Definition at line 375 of file frames.cc.
                                           {
  do {
    iterator_.Advance();
  } while (!done() && !IsValidFrame(iterator_.frame()));
}
References v8::internal::StackFrameIterator::Advance(), done(), v8::internal::StackFrameIterator::frame(), IsValidFrame(), and iterator_.
Referenced by v8::internal::DebugStackTraceIterator::Advance(), v8::internal::Debug::CurrentFrameCount(), DebuggableStackFrameIterator(), v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame(), v8::internal::Debug::PrepareStep(), and v8::internal::Debug::RestoreDebug().
done()
bool v8::internal::DebuggableStackFrameIterator::done () const [inline]
Definition at line 1767 of file frames.h.
{ return iterator_.done(); }
Referenced by Advance(), v8::internal::DebugStackTraceIterator::Advance(), v8::internal::Isolate::ComputeLocation(), v8::internal::Debug::CurrentFrameCount(), v8::internal::wasm::DebugInfoImpl::DeadBreakpoint(), DebuggableStackFrameIterator(), v8::internal::DebugScope::DebugScope(), v8::internal::DebugStackTraceIterator::DebugStackTraceIterator(), v8::internal::DebugStackTraceIterator::Done(), v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame(), FrameFunctionCount(), v8::internal::Compiler::GetFunctionFromEval(), GetTopValidFrame(), v8::internal::Debug::HandleDebugBreak(), v8::internal::Debug::PrepareStep(), v8::internal::JsonParser< Char >::ReportUnexpectedToken(), v8::internal::RUNTIME_FUNCTION(), v8::internal::DebugStackTraceIterator::UpdateInlineFrameIndexAndResumableFnOnStack(), v8::internal::wasm::DebugInfoImpl::UpdateReturnAddresses(), and v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmStackSize().
frame()
CommonFrame * v8::internal::DebuggableStackFrameIterator::frame () const [inline]
Definition at line 387 of file frames-inl.h.
                                                              {
  StackFrame* frame = iterator_.frame();
#if V8_ENABLE_WEBASSEMBLY
  DCHECK(frame->is_javascript() || frame->is_wasm());
#else
  DCHECK(frame->is_javascript());
#endif // V8_ENABLE_WEBASSEMBLY
  return static_cast<CommonFrame*>(frame);
}
References v8::internal::DCHECK(), v8::internal::StackFrameIterator::frame(), v8::internal::StackFrame::is_javascript(), and iterator_.
Referenced by v8::internal::DebugStackTraceIterator::Advance(), v8::internal::DebugStackTraceIterator::CanBeRestarted(), v8::internal::Debug::CurrentFrameCount(), v8::internal::wasm::DebugInfoImpl::DeadBreakpoint(), DebuggableStackFrameIterator(), v8::internal::DebugScope::DebugScope(), v8::internal::DebugStackTraceIterator::Evaluate(), v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame(), v8::internal::DebugStackTraceIterator::GetFunctionLocation(), v8::internal::wasm::InterpreterHandle::GetInstanceObject(), v8::internal::DebugStackTraceIterator::GetReturnValue(), v8::internal::DebugStackTraceIterator::GetScopeIterator(), GetTopValidFrame(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue(), v8::internal::Debug::HandleDebugBreak(), is_javascript(), IsValidFrame(), javascript_frame(), v8::internal::DebugEvaluate::Local(), v8::internal::Debug::PrepareStep(), Reframe(), v8::internal::Debug::RestoreDebug(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::DebugStackTraceIterator::UpdateInlineFrameIndexAndResumableFnOnStack().
FrameFunctionCount()
int v8::internal::DebuggableStackFrameIterator::FrameFunctionCount () const
Definition at line 381 of file frames.cc.
                                                           {
  DCHECK(!done());
  if (!iterator_.frame()->is_optimized_js()) return 1;
  std::vector<Tagged<SharedFunctionInfo>> infos;
  TurbofanJSFrame::cast(iterator_.frame())->GetFunctions(&infos);
  return static_cast<int>(infos.size());
}
References v8::internal::JavaScriptFrame::cast(), v8::internal::DCHECK(), done(), v8::internal::StackFrameIterator::frame(), v8::internal::JavaScriptFrame::GetFunctions(), v8::internal::StackFrame::is_optimized_js(), and iterator_.
Referenced by v8::internal::Debug::CurrentFrameCount(), and v8::internal::Debug::RestoreDebug().
GetTopValidFrame()
FrameSummary v8::internal::DebuggableStackFrameIterator::GetTopValidFrame () const
Definition at line 389 of file frames.cc.
                                                                  {
  DCHECK(!done());
  // Like FrameSummary::GetTop, but additionally observes
  // DebuggableStackFrameIterator filtering semantics.
  FrameSummaries summaries = frame()->Summarize();
  if (is_javascript()) {
    for (int i = summaries.size() - 1; i >= 0; i--) {
      const FrameSummary& summary = summaries.frames[i];
      if (summary.is_subject_to_debugging()) {
        return summary;
      }
    }
    UNREACHABLE();
  }
#if V8_ENABLE_WEBASSEMBLY
  if (is_wasm()) return summaries.frames.back();
#endif // V8_ENABLE_WEBASSEMBLY
  UNREACHABLE();
}
References v8::internal::DCHECK(), done(), frame(), v8::internal::FrameSummaries::frames, v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_javascript(), v8::internal::FrameSummary::is_subject_to_debugging(), v8::internal::FrameSummaries::size(), v8::internal::CommonFrame::Summarize(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::Isolate::ComputeLocation(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::JsonParser< Char >::ReportUnexpectedToken(), and v8::internal::Debug::ShouldBeSkipped().
is_javascript()
bool v8::internal::DebuggableStackFrameIterator::is_javascript () const [inline]
Definition at line 402 of file frames-inl.h.
                                                       {
  return frame()->is_javascript();
}
References frame(), and v8::internal::StackFrame::is_javascript().
Referenced by v8::internal::Compiler::GetFunctionFromEval(), GetTopValidFrame(), v8::internal::DebugEvaluate::Local(), and v8::internal::JsonParser< Char >::ReportUnexpectedToken().
IsValidFrame()
bool v8::internal::DebuggableStackFrameIterator::IsValidFrame (StackFrame * frame) [static], [private]
Definition at line 410 of file frames.cc.
                                                                 {
  if (frame->is_javascript()) {
    Tagged<JSFunction> function =
        static_cast<JavaScriptFrame*>(frame)->function();
    return function->shared()->IsSubjectToDebugging();
  }
#if V8_ENABLE_WEBASSEMBLY
  if (frame->is_wasm()) return true;
#endif // V8_ENABLE_WEBASSEMBLY
  return false;
}
References frame(), and v8::internal::StackFrame::is_javascript().
Referenced by Advance(), and DebuggableStackFrameIterator().
javascript_frame()
JavaScriptFrame * v8::internal::DebuggableStackFrameIterator::javascript_frame () const [inline]
Definition at line 419 of file frames-inl.h.
                                                                      {
  return JavaScriptFrame::cast(frame());
}
References v8::internal::JavaScriptFrame::cast(), and frame().
Referenced by v8::internal::DebugStackTraceIterator::GetReturnValue(), v8::internal::DebugEvaluate::Local(), and v8::internal::DebugStackTraceIterator::PrepareRestart().
Reframe()
CommonFrame * v8::internal::DebuggableStackFrameIterator::Reframe () [inline]
Definition at line 397 of file frames-inl.h.
                                                          {
  iterator_.Reframe();
  return frame();
}
References frame(), iterator_, and v8::internal::StackFrameIterator::Reframe().
Referenced by v8::internal::Debug::PrepareStep().
Member Data Documentation
iterator_
StackFrameIterator v8::internal::DebuggableStackFrameIterator::iterator_ [private]
Definition at line 1789 of file frames.h.
Referenced by Advance(), DebuggableStackFrameIterator(), frame(), FrameFunctionCount(), and Reframe().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc