v8::internal::compiler::CallForwardVarargsParameters Class Reference
#include <js-operator.h>
Public Member Functions
CallForwardVarargsParameters (size_t arity, uint32_t start_index)
size_t arity () const
uint32_t start_index () const
bool operator== (CallForwardVarargsParameters const &that) const
bool operator!= (CallForwardVarargsParameters const &that) const
Private Types
using ArityField = base::BitField< size_t, 0, 15 >
using StartIndexField = base::BitField< uint32_t, 15, 15 >
Private Attributes
uint32_t const bit_field_
Friends
size_t hash_value (CallForwardVarargsParameters const &p)
Detailed Description
Definition at line 196 of file js-operator.h.
Member Typedef Documentation
ArityField
using v8::internal::compiler::CallForwardVarargsParameters::ArityField = base::BitField<size_t, 0, 15> [private]
Definition at line 217 of file js-operator.h.
StartIndexField
using v8::internal::compiler::CallForwardVarargsParameters::StartIndexField = base::BitField<uint32_t, 15, 15> [private]
Definition at line 218 of file js-operator.h.
Constructor & Destructor Documentation
CallForwardVarargsParameters()
v8::internal::compiler::CallForwardVarargsParameters::CallForwardVarargsParameters (size_t arity, uint32_t start_index) [inline]
Definition at line 198 of file js-operator.h.
      : bit_field_(ArityField::encode(arity) |
                   StartIndexField::encode(start_index)) {}
Member Function Documentation
arity()
size_t v8::internal::compiler::CallForwardVarargsParameters::arity () const [inline]
Definition at line 202 of file js-operator.h.
{ return ArityField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::JSOperatorBuilder::CallForwardVarargs(), v8::internal::compiler::operator<<(), and v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs().
operator!=()
bool v8::internal::compiler::CallForwardVarargsParameters::operator!= (CallForwardVarargsParameters const & that) const [inline]
Definition at line 208 of file js-operator.h.
                                                                  {
    return !(*this == that);
  }
operator==()
bool v8::internal::compiler::CallForwardVarargsParameters::operator== (CallForwardVarargsParameters const & that) const [inline]
Definition at line 205 of file js-operator.h.
                                                                  {
    return this->bit_field_ == that.bit_field_;
  }
References bit_field_.
start_index()
uint32_t v8::internal::compiler::CallForwardVarargsParameters::start_index () const [inline]
Definition at line 203 of file js-operator.h.
{ return StartIndexField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs().
Friends And Related Function Documentation
hash_value
size_t hash_value (CallForwardVarargsParameters const & p) [friend]
Definition at line 213 of file js-operator.h.
                                                                  {
    return p.bit_field_;
  }
Member Data Documentation
bit_field_
uint32_t const v8::internal::compiler::CallForwardVarargsParameters::bit_field_ [private]
Definition at line 220 of file js-operator.h.
Referenced by arity(), operator==(), and start_index().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h