v8::internal::wasm::WasmExportWrapperCache Class Reference
#include <wasm-export-wrapper-cache.h>
Static Public Member Functions
static void Put (Isolate *isolate, CanonicalTypeIndex sig_index, bool receiver_is_first_param, DirectHandle< Code > code)
static Tagged< CodeWrapper > Get (Isolate *isolate, CanonicalTypeIndex sig_index, bool receiver_is_first_param)
static int CountWrappersForTesting (Isolate *isolate)
Static Private Member Functions
static DirectHandle< WeakFixedArray > New (Isolate *isolate, int capacity)
static uint32_t Capacity (Tagged< WeakFixedArray > cache)
static uint32_t Hash (CanonicalTypeIndex sig_index, bool receiver_is_first_param)
static int ToArraySlot (InternalIndex entry)
static InternalIndex FirstProbe (uint32_t hash, uint32_t capacity)
static InternalIndex NextProbe (InternalIndex last, uint32_t number, uint32_t capacity)
static V8_WARN_UNUSED_RESULT Tagged< WeakFixedArray > EnsureCapacity (Isolate *isolate)
template<bool entry_may_exist>
static void PutInternal (Tagged< WeakFixedArray > cache, uint32_t hash, Tagged< MaybeWeak< Object >> value)
Static Private Attributes
static constexpr int kUnused = -1
static constexpr int kNumUsedElementsIndex = 0
static constexpr int kReservedSlots = 1
static constexpr int kSlotsPerEntry = 2
Detailed Description
Definition at line 28 of file wasm-export-wrapper-cache.h.
Member Function Documentation
Capacity()
uint32_t v8::internal::wasm::WasmExportWrapperCache::Capacity (Tagged< WeakFixedArray > cache) [static], [private]
Definition at line 61 of file wasm-export-wrapper-cache.cc.
                                                                      {
  // If we ever add more reserved slots, we'll have to subtract them properly
  // rather than just shifting them out implicitly.
  static_assert((kReservedSlots >> 1) == 0);
  return cache->length() >> 1;
}
References kReservedSlots.
Referenced by EnsureCapacity(), Get(), and PutInternal().
CountWrappersForTesting()
static int v8::internal::wasm::WasmExportWrapperCache::CountWrappersForTesting (Isolate * isolate) [static]
EnsureCapacity()
Tagged< WeakFixedArray > v8::internal::wasm::WasmExportWrapperCache::EnsureCapacity (Isolate * isolate) [static], [private]
Definition at line 69 of file wasm-export-wrapper-cache.cc.
                      {
  Tagged<WeakFixedArray> cache = isolate->heap()->js_to_wasm_wrappers();
  if (cache->length() == 0) {
    // Lazy initialization.
    static constexpr int kInitialCapacity = 16;
    DirectHandle<WeakFixedArray> new_cache = New(isolate, kInitialCapacity);
    isolate->heap()->SetJSToWasmWrappers(*new_cache);
    return *new_cache;
  }
  uint32_t capacity = Capacity(cache);
  uint32_t used = cache->get(kNumUsedElementsIndex).ToSmi().value();
  // We allow a maximum usage of 50% plus one entry, otherwise grow.
  // It can happen that we find many cleared entries during growing, so the
  // returned grown cache may be nearly empty. That's unlikely to happen
  // often, and if it happens a few times that's not a problem.
  if (used < capacity / 2) return cache;
  DirectHandle<WeakFixedArray> old_cache(cache, isolate);
  Tagged<WeakFixedArray> grown = *New(isolate, capacity * 2);
  DisallowGarbageCollection no_gc;
  cache = *old_cache;
  int num_used_entries = 0;
  for (int i = kReservedSlots; i < cache->length(); i += kSlotsPerEntry) {
    Tagged<MaybeWeak<Object>> raw_key = cache->get(i);
    DCHECK(raw_key.IsSmi());
    int key = raw_key.ToSmi().value();
    if (key == kUnused) continue;
    Tagged<MaybeWeak<Object>> value = cache->get(i + 1);
    if (value.IsCleared()) continue;
    num_used_entries++;
    PutInternal<false>(grown, key, value);
  }
  grown->set(kNumUsedElementsIndex, Smi::FromInt(num_used_entries));
  isolate->heap()->SetJSToWasmWrappers(grown);
  return grown;
}
References Capacity(), v8::internal::DCHECK(), v8::internal::Smi::FromInt(), v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::IsSmi(), v8::internal::key, kNumUsedElementsIndex, kReservedSlots, kSlotsPerEntry, kUnused, New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi(), and v8::internal::value.
Referenced by Put().
FirstProbe()
static InternalIndex v8::internal::wasm::WasmExportWrapperCache::FirstProbe (uint32_t hash, uint32_t capacity) [inline], [static], [private]
Definition at line 72 of file wasm-export-wrapper-cache.h.
                                                                    {
    // {New()} ensures that {capacity} is always a power of two.
    return InternalIndex(hash & (capacity - 1));
  }
Referenced by Get(), and PutInternal().
Get()
Tagged< CodeWrapper > v8::internal::wasm::WasmExportWrapperCache::Get (Isolate * isolate, CanonicalTypeIndex sig_index, bool receiver_is_first_param) [static]
Definition at line 36 of file wasm-export-wrapper-cache.cc.
                                                                              {
  Tagged<WeakFixedArray> cache = isolate->heap()->js_to_wasm_wrappers();
  uint32_t hash = Hash(sig_index, receiver_is_first_param);
  uint32_t capacity = Capacity(cache);
  if (capacity == 0) return {}; // Not found (cache is uninitialized).
  uint32_t count = 1;
  for (InternalIndex entry = FirstProbe(hash, capacity);;
       entry = NextProbe(entry, count++, capacity)) {
    DCHECK(count < capacity);
    int index = ToArraySlot(entry);
    Tagged<MaybeWeak<Object>> raw_key = cache->get(index);
    DCHECK(raw_key.IsSmi());
    int key = raw_key.ToSmi().value();
    if (key == kUnused) return {}; // Not found.
    DCHECK_GE(key, 0);
    if (static_cast<uint32_t>(key) != hash) continue;
    Tagged<MaybeWeak<Object>> value = cache->get(index + 1);
    if (value.IsCleared()) return {}; // Not found.
    return Cast<CodeWrapper>(value.GetHeapObjectAssumeWeak());
  }
}
References Capacity(), v8::internal::DCHECK(), DCHECK_GE, FirstProbe(), Hash(), v8::internal::Isolate::heap(), v8::internal::index, v8::internal::Tagged< HeapObject >::IsSmi(), v8::internal::key, kUnused, NextProbe(), ToArraySlot(), v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi(), and v8::internal::value.
Referenced by v8::internal::WasmExportedFunction::GetWrapper(), and v8::internal::RUNTIME_FUNCTION().
Hash()
static uint32_t v8::internal::wasm::WasmExportWrapperCache::Hash (CanonicalTypeIndex sig_index, bool receiver_is_first_param) [inline], [static], [private]
Definition at line 58 of file wasm-export-wrapper-cache.h.
                                                     {
    // We expect most signatures to get only one wrapper, so putting the
    // {receiver_is_first_param} bit at the top should give good distribution
    // of hash values.
    static_assert(kMaxCanonicalTypes < (1u << 20));
    return ((receiver_is_first_param ? 1 : 0) << 20) | sig_index.index;
  }
References v8::internal::wasm::TypeIndex::index, and v8::internal::wasm::kMaxCanonicalTypes.
Referenced by Get(), and Put().
New()
DirectHandle< WeakFixedArray > v8::internal::wasm::WasmExportWrapperCache::New (Isolate * isolate, int capacity) [static], [private]
Definition at line 13 of file wasm-export-wrapper-cache.cc.
                                                                       {
  // Probing depends on bit-masking the hashes, so the capacity needs to be
  // a power of two.
  DCHECK(base::bits::IsPowerOfTwo(capacity));
  capacity = capacity * kSlotsPerEntry + kReservedSlots;
  DirectHandle<WeakFixedArray> cache =
      WeakFixedArray::New(isolate, capacity, AllocationType::kOld,
                          direct_handle(Smi::FromInt(kUnused), isolate));
  cache->set(kNumUsedElementsIndex, Smi::zero());
  return cache;
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Smi::FromInt(), v8::base::bits::IsPowerOfTwo(), kNumUsedElementsIndex, v8::internal::kOld, kReservedSlots, kSlotsPerEntry, kUnused, v8::internal::WeakFixedArray::New(), and v8::internal::Smi::zero().
Referenced by EnsureCapacity().
NextProbe()
static InternalIndex v8::internal::wasm::WasmExportWrapperCache::NextProbe (InternalIndex last, uint32_t number, uint32_t capacity) [inline], [static], [private]
Definition at line 77 of file wasm-export-wrapper-cache.h.
                                                    {
    // {New()} ensures that {capacity} is always a power of two.
    return InternalIndex((last.as_uint32() + number) & (capacity - 1));
  }
References v8::internal::InternalIndex::as_uint32().
Referenced by Get(), and PutInternal().
Put()
void v8::internal::wasm::WasmExportWrapperCache::Put (Isolate * isolate, CanonicalTypeIndex sig_index, bool receiver_is_first_param, DirectHandle< Code > code) [static]
Definition at line 27 of file wasm-export-wrapper-cache.cc.
                                                          {
  uint32_t hash = Hash(sig_index, receiver_is_first_param);
  Tagged<WeakFixedArray> cache = EnsureCapacity(isolate);
  PutInternal<true>(cache, hash, code->wrapper());
}
References code, EnsureCapacity(), and Hash().
Referenced by v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize().
PutInternal()
template<bool entry_may_exist>
void v8::internal::wasm::WasmExportWrapperCache::PutInternal (Tagged< WeakFixedArray > cache, uint32_t hash, Tagged< MaybeWeak< Object >> value) [static], [private]
Definition at line 108 of file wasm-export-wrapper-cache.cc.
                                                                          {
  uint32_t capacity = Capacity(cache);
  uint32_t count = 1;
  for (InternalIndex entry = FirstProbe(hash, capacity);;
       entry = NextProbe(entry, count++, capacity)) {
    DCHECK(count < capacity);
    int index = ToArraySlot(entry);
    Tagged<MaybeWeak<Object>> raw_key = cache->get(index);
    DCHECK(raw_key.IsSmi());
    int current_key = raw_key.ToSmi().value();
    if (current_key == kUnused) {
      cache->set(index, Smi::FromInt(hash));
      int used_elements = cache->get(kNumUsedElementsIndex).ToSmi().value();
      cache->set(kNumUsedElementsIndex, Smi::FromInt(used_elements + 1));
    } else if constexpr (entry_may_exist) {
      if (static_cast<uint32_t>(current_key) != hash) continue;
      // Key exists; value must be cleared, otherwise we shouldn't be
      // trying to put a new value.
      DCHECK(cache->get(index + 1).IsCleared());
    } else {
      DCHECK_NE(static_cast<uint32_t>(current_key), hash);
      continue;
    }
    // We get here when we've found the right entry (unused or cleared).
    cache->set(index + 1, MakeWeak(value));
    return;
  }
}
References Capacity(), v8::internal::DCHECK(), DCHECK_NE, FirstProbe(), v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::Tagged< HeapObject >::IsSmi(), kNumUsedElementsIndex, kUnused, v8::internal::MakeWeak(), NextProbe(), ToArraySlot(), v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi(), and v8::internal::value.
ToArraySlot()
static int v8::internal::wasm::WasmExportWrapperCache::ToArraySlot (InternalIndex entry) [inline], [static], [private]
Definition at line 68 of file wasm-export-wrapper-cache.h.
                                              {
    return kReservedSlots + entry.as_int() * kSlotsPerEntry;
  }
References v8::internal::InternalIndex::as_int(), kReservedSlots, and kSlotsPerEntry.
Referenced by Get(), and PutInternal().
Member Data Documentation
kNumUsedElementsIndex
constexpr int v8::internal::wasm::WasmExportWrapperCache::kNumUsedElementsIndex = 0 [static], [constexpr], [private]
Definition at line 48 of file wasm-export-wrapper-cache.h.
Referenced by EnsureCapacity(), New(), and PutInternal().
kReservedSlots
constexpr int v8::internal::wasm::WasmExportWrapperCache::kReservedSlots = 1 [static], [constexpr], [private]
Definition at line 49 of file wasm-export-wrapper-cache.h.
Referenced by Capacity(), EnsureCapacity(), New(), and ToArraySlot().
kSlotsPerEntry
constexpr int v8::internal::wasm::WasmExportWrapperCache::kSlotsPerEntry = 2 [static], [constexpr], [private]
Definition at line 52 of file wasm-export-wrapper-cache.h.
Referenced by EnsureCapacity(), New(), and ToArraySlot().
kUnused
constexpr int v8::internal::wasm::WasmExportWrapperCache::kUnused = -1 [static], [constexpr], [private]
Definition at line 46 of file wasm-export-wrapper-cache.h.
Referenced by EnsureCapacity(), Get(), New(), and PutInternal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-export-wrapper-cache.h
/mnt/V8SourceCode/src/wasm/wasm-export-wrapper-cache.cc