v8::internal::compiler::S390OperandGenerator Class Reference
Public Member Functions
S390OperandGenerator (InstructionSelector *selector)
InstructionOperand UseOperand (OpIndex node, OperandModes mode)
InstructionOperand UseAnyExceptImmediate (OpIndex node)
int64_t GetImmediate (OpIndex node)
bool CanBeImmediate (OpIndex node, OperandModes mode)
bool CanBeImmediate (int64_t value, OperandModes mode)
bool CanBeMemoryOperand (InstructionCode opcode, OpIndex user, OpIndex input, int effect_level)
AddressingMode GenerateMemoryOperandInputs (OptionalOpIndex index, OpIndex base, int64_t displacement, DisplacementMode displacement_mode, InstructionOperand inputs[], size_t *input_count, RegisterUseKind reg_kind=RegisterUseKind::kUseRegister)
AddressingMode GetEffectiveAddressMemoryOperand (OpIndex operand, InstructionOperand inputs[], size_t *input_count, OperandModes immediate_mode=OperandMode::kInt20Imm)
bool CanBeBetterLeftOperand (OpIndex node) const
Additional Inherited Members
Detailed Description
Definition at line 158 of file instruction-selector-s390.cc.
Constructor & Destructor Documentation
S390OperandGenerator()
v8::internal::compiler::S390OperandGenerator::S390OperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 160 of file instruction-selector-s390.cc.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeBetterLeftOperand()
bool v8::internal::compiler::S390OperandGenerator::CanBeBetterLeftOperand (OpIndex node) const [inline]
Definition at line 316 of file instruction-selector-s390.cc.
                                                  {
    return !selector()->IsLive(node);
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp().
CanBeImmediate() [1/2]
bool v8::internal::compiler::S390OperandGenerator::CanBeImmediate (int64_t value, OperandModes mode) [inline]
Definition at line 197 of file instruction-selector-s390.cc.
                                                        {
    if (mode & OperandMode::kShift32Imm)
      return 0 <= value && value < 32;
    else if (mode & OperandMode::kShift64Imm)
      return 0 <= value && value < 64;
    else if (mode & OperandMode::kInt32Imm)
      return is_int32(value);
    else if (mode & OperandMode::kInt32Imm_Negate)
      return is_int32(-value);
    else if (mode & OperandMode::kUint32Imm)
      return is_uint32(value);
    else if (mode & OperandMode::kInt20Imm)
      return is_int20(value);
    else if (mode & OperandMode::kUint12Imm)
      return is_uint12(value);
    else
      return false;
  }
References v8::internal::compiler::kInt20Imm, v8::internal::compiler::kInt32Imm, v8::internal::compiler::kInt32Imm_Negate, v8::internal::compiler::kShift32Imm, v8::internal::compiler::kShift64Imm, v8::internal::compiler::kUint12Imm, v8::internal::compiler::kUint32Imm, mode(), and v8::internal::value.
CanBeImmediate() [2/2]
bool v8::internal::compiler::S390OperandGenerator::CanBeImmediate (OpIndex node, OperandModes mode) [inline]
Definition at line 191 of file instruction-selector-s390.cc.
                                                       {
    int64_t value;
    if (!selector()->MatchSignedIntegralConstant(node, &value)) return false;
    return CanBeImmediate(value, mode);
  }
References v8::internal::compiler::CanBeImmediate(), mode(), and v8::internal::value.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTestUnderMask(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
CanBeMemoryOperand()
bool v8::internal::compiler::S390OperandGenerator::CanBeMemoryOperand (InstructionCode opcode, OpIndex user, OpIndex input, int effect_level) [inline]
Definition at line 216 of file instruction-selector-s390.cc.
                                            {
    if (!selector()->IsLoadOrLoadImmutable(input)) return false;
    if (!selector()->CanCover(user, input)) return false;
    if (effect_level != selector()->GetEffectLevel(input)) {
      return false;
    }
    MachineRepresentation rep =
        selector()->load_view(input).loaded_rep().representation();
    switch (opcode) {
      case kS390_Cmp64:
      case kS390_LoadAndTestWord64:
        if (rep == MachineRepresentation::kWord64 ||
            (!COMPRESS_POINTERS_BOOL && IsAnyTagged(rep))) {
          DCHECK_EQ(ElementSizeInBits(rep), 64);
          return true;
        }
        break;
      case kS390_LoadAndTestWord32:
      case kS390_Cmp32:
        if (rep == MachineRepresentation::kWord32 ||
            (COMPRESS_POINTERS_BOOL && IsAnyCompressed(rep))) {
          DCHECK_EQ(ElementSizeInBits(rep), 32);
          return true;
        }
        break;
      default:
        break;
    }
    return false;
  }
References COMPRESS_POINTERS_BOOL, DCHECK_EQ, v8::internal::ElementSizeInBits(), v8::internal::IsAnyCompressed(), v8::internal::IsAnyTagged(), v8::internal::kWord32, and v8::internal::kWord64.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
GenerateMemoryOperandInputs()
AddressingMode v8::internal::compiler::S390OperandGenerator::GenerateMemoryOperandInputs (OptionalOpIndex index, OpIndex base, int64_t displacement, DisplacementMode displacement_mode, InstructionOperand inputs[], size_t * input_count, RegisterUseKind reg_kind = RegisterUseKind::kUseRegister) [inline]
Definition at line 249 of file instruction-selector-s390.cc.
                                                              {
    AddressingMode mode = kMode_MRI;
    if (base.valid()) {
      inputs[(*input_count)++] = UseRegister(base, reg_kind);
      if (index.valid()) {
        inputs[(*input_count)++] = UseRegister(index.value(), reg_kind);
        if (displacement != 0) {
          inputs[(*input_count)++] = UseImmediate(
              displacement_mode == kNegativeDisplacement ? -displacement
                                                         : displacement);
          mode = kMode_MRRI;
        } else {
          mode = kMode_MRR;
        }
      } else {
        if (displacement == 0) {
          mode = kMode_MR;
        } else {
          inputs[(*input_count)++] = UseImmediate(
              displacement_mode == kNegativeDisplacement ? -displacement
                                                         : displacement);
          mode = kMode_MRI;
        }
      }
    } else {
      DCHECK(index.valid());
      inputs[(*input_count)++] = UseRegister(index.value(), reg_kind);
      if (displacement != 0) {
        inputs[(*input_count)++] = UseImmediate(
            displacement_mode == kNegativeDisplacement ? -displacement
                                                       : displacement);
        mode = kMode_MRI;
      } else {
        mode = kMode_MR;
      }
    }
    return mode;
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::kNegativeDisplacement, mode(), v8::internal::maglev::UseRegister(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::VisitGeneralStore().
GetEffectiveAddressMemoryOperand()
AddressingMode v8::internal::compiler::S390OperandGenerator::GetEffectiveAddressMemoryOperand (OpIndex operand, InstructionOperand inputs[], size_t * input_count, OperandModes immediate_mode = OperandMode::kInt20Imm) [inline]
Definition at line 292 of file instruction-selector-s390.cc.
                                                          {
    auto m = TryMatchBaseWithScaledIndexAndDisplacement64(selector(), operand);
    DCHECK(m.has_value());
    if (m->base.valid() && selector()->Get(m->base).Is<LoadRootRegisterOp>() &&
        !m->index.valid()) {
      DCHECK_EQ(m->scale, 0);
      inputs[(*input_count)++] =
          UseImmediate(static_cast<int>(m->displacement));
      return kMode_Root;
    } else if (CanBeImmediate(m->displacement, immediate_mode)) {
      DCHECK_EQ(m->scale, 0);
      return GenerateMemoryOperandInputs(m->index, m->base, m->displacement,
                                         m->displacement_mode, inputs,
                                         input_count);
    } else {
      DCHECK_EQ(m->displacement, 0);
      inputs[(*input_count)++] = UseRegister(m->base);
      inputs[(*input_count)++] = UseRegister(m->index);
      return kMode_MRR;
    }
  }
References v8::internal::compiler::CanBeImmediate(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64(), and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
GetImmediate()
int64_t v8::internal::compiler::S390OperandGenerator::GetImmediate (OpIndex node) [inline]
Definition at line 178 of file instruction-selector-s390.cc.
                                     {
    ConstantOp* op =
        this->turboshaft_graph()->Get(node).template TryCast<ConstantOp>();
    switch (op->kind) {
      case ConstantOp::Kind::kWord32:
        return op->word32();
      case ConstantOp::Kind::kWord64:
        return op->word64();
      default:
        UNIMPLEMENTED();
    }
  }
References v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::kWord64, v8::internal::compiler::UNIMPLEMENTED(), v8::internal::compiler::turboshaft::ConstantOp::word32(), and v8::internal::compiler::turboshaft::ConstantOp::word64().
Referenced by v8::internal::compiler::TryMatchShiftFromMul(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
UseAnyExceptImmediate()
InstructionOperand v8::internal::compiler::S390OperandGenerator::UseAnyExceptImmediate (OpIndex node) [inline]
Definition at line 170 of file instruction-selector-s390.cc.
                                                         {
    int64_t value;
    if (MatchSignedIntegralConstant(node, &value))
      return UseRegister(node);
    else
      return this->Use(node);
  }
References v8::internal::maglev::UseRegister(), and v8::internal::value.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
UseOperand()
InstructionOperand v8::internal::compiler::S390OperandGenerator::UseOperand (OpIndex node, OperandModes mode) [inline]
Definition at line 163 of file instruction-selector-s390.cc.
                                                                 {
    if (CanBeImmediate(node, mode)) {
      return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::compiler::CanBeImmediate(), mode(), and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTestUnderMask().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/s390/instruction-selector-s390.cc