v8::internal::GlobalHandleVector< T > Class Template Reference
#include <global-handles.h>
Classes
class Iterator
Public Member Functions
GlobalHandleVector (Heap *heap)
GlobalHandleVector (LocalHeap *local_heap)
IndirectHandle< T > operator[] (size_t i)
size_t size () const
bool empty () const
void Reserve (size_t size)
void Push (Tagged< T > val)
Tagged< T > Pop ()
Iterator begin ()
Iterator end ()
Private Attributes
std::vector< Address, StrongRootAllocator< Address > > locations_
Detailed Description
template<typename T>
class v8::internal::GlobalHandleVector< T >
Definition at line 239 of file global-handles.h.
Constructor & Destructor Documentation
GlobalHandleVector() [1/2]
template<typename T >
v8::internal::GlobalHandleVector< T >::GlobalHandleVector (Heap * heap) [inline], [explicit]
Definition at line 38 of file global-handles-inl.h.
    : locations_(StrongRootAllocator<Address>(heap)) {}
GlobalHandleVector() [2/2]
template<typename T >
v8::internal::GlobalHandleVector< T >::GlobalHandleVector (LocalHeap * local_heap) [inline], [explicit]
Definition at line 34 of file global-handles-inl.h.
    : GlobalHandleVector(local_heap->AsHeap()) {}
Member Function Documentation
begin()
template<typename T >
Iterator v8::internal::GlobalHandleVector< T >::begin () [inline]
Definition at line 277 of file global-handles.h.
{ return Iterator(locations_.begin()); }
References v8::internal::GlobalHandleVector< T >::locations_.
Referenced by v8::internal::Heap::WeakenDescriptorArrays().
empty()
template<typename T >
bool v8::internal::GlobalHandleVector< T >::empty () const [inline]
Definition at line 269 of file global-handles.h.
{ return locations_.empty(); }
References v8::internal::GlobalHandleVector< T >::locations_.
end()
template<typename T >
Iterator v8::internal::GlobalHandleVector< T >::end () [inline]
Definition at line 278 of file global-handles.h.
{ return Iterator(locations_.end()); }
References v8::internal::GlobalHandleVector< T >::locations_.
Referenced by v8::internal::Heap::WeakenDescriptorArrays().
operator[]()
template<typename T >
IndirectHandle<T> v8::internal::GlobalHandleVector< T >::operator[] (size_t i) [inline]
Definition at line 264 of file global-handles.h.
                                         {
    return IndirectHandle<T>(&locations_[i]);
  }
References v8::internal::GlobalHandleVector< T >::locations_.
Pop()
template<typename T >
Tagged< T > v8::internal::GlobalHandleVector< T >::Pop [inline]
Definition at line 27 of file global-handles-inl.h.
                                     {
  Tagged<T> obj = Cast<T>(Tagged<Object>(locations_.back()));
  locations_.pop_back();
  return obj;
}
Push()
template<typename T >
void v8::internal::GlobalHandleVector< T >::Push (Tagged< T > val) [inline]
Definition at line 272 of file global-handles.h.
{ locations_.push_back(val.ptr()); }
References v8::internal::GlobalHandleVector< T >::locations_, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::maglev::MaglevCodeGenerator::CollectRetainedMaps(), v8::internal::OptimizedCompilationJob::CollectRetainedMaps(), and v8::internal::maglev::MaglevCodeGenerator::RetainedMaps().
Reserve()
template<typename T >
void v8::internal::GlobalHandleVector< T >::Reserve (size_t size) [inline]
Definition at line 271 of file global-handles.h.
{ locations_.reserve(size); }
References v8::internal::GlobalHandleVector< T >::locations_, and v8::internal::GlobalHandleVector< T >::size().
Referenced by v8::internal::maglev::MaglevCodeGenerator::RetainedMaps().
size()
template<typename T >
size_t v8::internal::GlobalHandleVector< T >::size () const [inline]
Definition at line 268 of file global-handles.h.
{ return locations_.size(); }
References v8::internal::GlobalHandleVector< T >::locations_.
Referenced by v8::internal::Heap::AddRetainedMaps(), and v8::internal::GlobalHandleVector< T >::Reserve().
Member Data Documentation
locations_
template<typename T >
std::vector<Address, StrongRootAllocator<Address> > v8::internal::GlobalHandleVector< T >::locations_ [private]
Definition at line 281 of file global-handles.h.
Referenced by v8::internal::GlobalHandleVector< T >::begin(), v8::internal::GlobalHandleVector< T >::empty(), v8::internal::GlobalHandleVector< T >::end(), v8::internal::GlobalHandleVector< T >::operator[](), v8::internal::GlobalHandleVector< T >::Push(), v8::internal::GlobalHandleVector< T >::Reserve(), and v8::internal::GlobalHandleVector< T >::size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/global-handles.h
/mnt/V8SourceCode/src/handles/global-handles-inl.h