v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super > Class Template Reference
#include <fixed-array.h>
Public Types
using Shape = ShapeT
using Header = detail::ArrayHeaderBase< Super, true >
Public Member Functions
ElementMemberT get (int index) const
void set (int index, ElementMemberT value)
int AllocatedSize () const
ElementMemberT * begin ()
const ElementMemberT * begin () const
ElementMemberT * end ()
const ElementMemberT * end () const
int DataSize () const
template<class IsolateT >
Handle< D > Allocate (IsolateT *isolate, int length, std::optional< DisallowGarbageCollection > *no_gc_out, AllocationType allocation)
Static Public Member Functions
static constexpr int SizeFor (int length)
static constexpr int OffsetOfElementAt (int index)
static Tagged< Derived > FromAddressOfFirstElement (Address address)
Static Public Attributes
static constexpr bool kElementsAreMaybeObject = false
static constexpr int kElementSize = sizeof(ElementMemberT)
static constexpr int kMaxLength = kMaxFixedArrayCapacity
static constexpr int kMaxRegularLength
Protected Member Functions
bool IsInBounds (int index) const
FLEXIBLE_ARRAY_MEMBER (ElementMemberT, values)
Static Protected Member Functions
template<class IsolateT >
static Handle< Derived > Allocate (IsolateT *isolate, int length, std::optional< DisallowGarbageCollection > *no_gc_out, AllocationType allocation=AllocationType::kYoung)
Private Types
using ElementT = typename ShapeT::ElementT
using ElementMemberT = std::conditional_t< std::is_same_v< ElementT, double >, UnalignedDoubleMember, ElementT >
Detailed Description
template<class Derived, class ShapeT, class Super = HeapObjectLayout>
class v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >
Definition at line 386 of file fixed-array.h.
Member Typedef Documentation
ElementMemberT
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::ElementMemberT = std::conditional_t<std::is_same_v<ElementT, double>, UnalignedDoubleMember, ElementT> [private]
Definition at line 393 of file fixed-array.h.
ElementT
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::ElementT = typename ShapeT::ElementT [private]
Definition at line 389 of file fixed-array.h.
Header
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::Header = detail::ArrayHeaderBase<Super, true>
Definition at line 401 of file fixed-array.h.
Shape
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::Shape = ShapeT
Definition at line 398 of file fixed-array.h.
Member Function Documentation
Allocate() [1/2]
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
template<class IsolateT >
Handle<D> v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::Allocate (IsolateT * isolate, int length, std::optional< DisallowGarbageCollection > * no_gc_out, AllocationType allocation)
Definition at line 525 of file fixed-array-inl.h.
                               {
  // Note 0-length is explicitly allowed since not all subtypes can be
  // assumed to have canonical 0-length instances.
  DCHECK_GE(length, 0);
  DCHECK_LE(length, kMaxLength);
  DCHECK(!no_gc_out->has_value());
  Tagged<D> xs = UncheckedCast<D>(
      isolate->factory()->AllocateRawArray(SizeFor(length), allocation));
  ReadOnlyRoots roots{isolate};
  if (DEBUG_BOOL) no_gc_out->emplace();
  Tagged<Map> map = Cast<Map>(roots.object_at(S::kMapRootIndex));
  DCHECK(ReadOnlyHeap::Contains(map));
  xs->set_map_after_allocation(isolate, map, SKIP_WRITE_BARRIER);
  xs->set_length(length);
  return handle(xs, isolate);
}
References v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, DEBUG_BOOL, v8::internal::handle(), v8::internal::length, and v8::internal::SKIP_WRITE_BARRIER.
Allocate() [2/2]
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
template<class IsolateT >
static Handle<Derived> v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::Allocate (IsolateT * isolate, int length, std::optional< DisallowGarbageCollection > * no_gc_out, AllocationType allocation = AllocationType::kYoung) [static], [protected]
AllocatedSize()
template<class D , class S , class P >
int v8::internal::PrimitiveArrayBase< D, S, P >::AllocatedSize [inline]
Definition at line 468 of file fixed-array-inl.h.
                                                     {
  return SizeFor(this->length(kAcquireLoad));
}
References v8::kAcquireLoad, and v8::internal::length.
begin() [1/2]
template<class D , class S , class P >
auto v8::internal::PrimitiveArrayBase< D, S, P >::begin [inline]
Definition at line 473 of file fixed-array-inl.h.
                                                           {
  return &values()[0];
}
begin() [2/2]
template<class D , class S , class P >
auto v8::internal::PrimitiveArrayBase< D, S, P >::begin [inline]
Definition at line 478 of file fixed-array-inl.h.
                                                                       {
  return &values()[0];
}
DataSize()
template<class D , class S , class P >
int v8::internal::PrimitiveArrayBase< D, S, P >::DataSize [inline]
Definition at line 493 of file fixed-array-inl.h.
                                                {
  int data_size = SizeFor(this->length()) - sizeof(Header);
  DCHECK_EQ(data_size, OBJECT_POINTER_ALIGN(this->length() * kElementSize));
  return data_size;
}
References DCHECK_EQ, v8::internal::ETWJITInterface::Header(), v8::internal::length, and OBJECT_POINTER_ALIGN.
end() [1/2]
template<class D , class S , class P >
auto v8::internal::PrimitiveArrayBase< D, S, P >::end [inline]
Definition at line 483 of file fixed-array-inl.h.
                                                         {
  return &values()[this->length()];
}
References v8::internal::length.
end() [2/2]
template<class D , class S , class P >
auto v8::internal::PrimitiveArrayBase< D, S, P >::end [inline]
Definition at line 488 of file fixed-array-inl.h.
                                                                     {
  return &values()[this->length()];
}
References v8::internal::length.
FLEXIBLE_ARRAY_MEMBER()
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::FLEXIBLE_ARRAY_MEMBER (ElementMemberT , values) [protected]
FromAddressOfFirstElement()
template<class D , class S , class P >
Tagged< D > v8::internal::PrimitiveArrayBase< D, S, P >::FromAddressOfFirstElement (Address address) [inline], [static]
Definition at line 501 of file fixed-array-inl.h.
                     {
  DCHECK_TAG_ALIGNED(address);
  return Cast<D>(Tagged<Object>(address - S::kHeaderSize + kHeapObjectTag));
}
References DCHECK_TAG_ALIGNED, and v8::internal::kHeapObjectTag.
get()
template<class D , class S , class P >
auto v8::internal::PrimitiveArrayBase< D, S, P >::get (int index) const [inline]
Definition at line 453 of file fixed-array-inl.h.
                                                                       {
  DCHECK(IsInBounds(index));
  return values()[index];
}
References v8::internal::DCHECK(), and v8::internal::index.
IsInBounds()
template<class D , class S , class P >
bool v8::internal::PrimitiveArrayBase< D, S, P >::IsInBounds (int index) const [inline], [protected]
Definition at line 448 of file fixed-array-inl.h.
                                                            {
  return static_cast<unsigned>(index) < static_cast<unsigned>(this->length());
}
References v8::internal::index, and v8::internal::length.
OffsetOfElementAt()
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
static constexpr int v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::OffsetOfElementAt (int index) [inline], [static], [constexpr]
Definition at line 410 of file fixed-array.h.
                                                           {
    return sizeof(Header) + index * kElementSize;
  }
References v8::internal::FixedArray::index, and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::kElementSize.
set()
template<class D , class S , class P >
void v8::internal::PrimitiveArrayBase< D, S, P >::set (int index, ElementMemberT value) [inline]
Definition at line 459 of file fixed-array-inl.h.
                                                                     {
  DCHECK(IsInBounds(index));
  values()[index] = value;
}
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::value.
SizeFor()
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
static constexpr int v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::SizeFor (int length) [inline], [static], [constexpr]
Definition at line 407 of file fixed-array.h.
                                                  {
    return OBJECT_POINTER_ALIGN(OffsetOfElementAt(length));
  }
References v8::internal::length, OBJECT_POINTER_ALIGN, and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
Member Data Documentation
kElementsAreMaybeObject
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr bool v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::kElementsAreMaybeObject = false [static], [constexpr]
Definition at line 399 of file fixed-array.h.
kElementSize
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr int v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::kElementSize = sizeof(ElementMemberT) [static], [constexpr]
Definition at line 400 of file fixed-array.h.
kMaxLength
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr int v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::kMaxLength = kMaxFixedArrayCapacity [static], [constexpr]
Definition at line 428 of file fixed-array.h.
kMaxRegularLength
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr int v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::kMaxRegularLength [static], [constexpr]
Initial value:
=
      (kMaxRegularHeapObjectSize - sizeof(Header)) / kElementSize
Definition at line 432 of file fixed-array.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h