v8_inspector::String16Builder Class Reference
#include <string-16.h>
Public Member Functions
String16Builder ()
void append (const String16 &)
void append (UChar)
void append (char)
void append (const UChar *, size_t)
void append (const char *, size_t)
void appendNumber (int)
void appendNumber (size_t)
void appendUnsignedAsHex (uint64_t)
void appendUnsignedAsHex (uint32_t)
void appendUnsignedAsHex (uint8_t)
String16 toString ()
void reserveCapacity (size_t)
template<typename T , typename... R>
void appendAll (T first, R... rest)
void appendAll ()
Private Attributes
std::vector< UChar > m_buffer
Detailed Description
Definition at line 130 of file string-16.h.
Constructor & Destructor Documentation
String16Builder()
v8_inspector::String16Builder::String16Builder () [default]
Member Function Documentation
append() [1/5]
void v8_inspector::String16Builder::append (char c)
Definition at line 163 of file string-16.cc.
                                   {
  UChar u = c;
  m_buffer.push_back(u);
}
References m_buffer.
append() [2/5]
void v8_inspector::String16Builder::append (const char * characters, size_t length)
Definition at line 172 of file string-16.cc.
                                                                  {
  m_buffer.insert(m_buffer.end(), characters, characters + length);
}
References v8::internal::length, and m_buffer.
append() [3/5]
void v8_inspector::String16Builder::append (const String16 & s)
Definition at line 156 of file string-16.cc.
                                              {
  m_buffer.insert(m_buffer.end(), s.characters16(),
                  s.characters16() + s.length());
}
References v8_inspector::String16::characters16(), v8_inspector::String16::length(), and m_buffer.
Referenced by appendAll(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForRegExp(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::DescriptionForRegExpFlags(), v8_inspector::String16::fromUTF16LE(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateInstrumentationBreakpointId(), v8_inspector::V8Console::monitorFunctionCallback(), v8_inspector::V8DebuggerAgentImpl::setBlackboxPatterns(), and v8_inspector::V8StackTraceImpl::toString().
append() [4/5]
void v8_inspector::String16Builder::append (const UChar * characters, size_t length)
Definition at line 168 of file string-16.cc.
                                                                   {
  m_buffer.insert(m_buffer.end(), characters, characters + length);
}
References v8::internal::length, and m_buffer.
append() [5/5]
void v8_inspector::String16Builder::append (UChar c)
Definition at line 161 of file string-16.cc.
{ m_buffer.push_back(c); }
References m_buffer.
appendAll() [1/2]
void v8_inspector::String16Builder::appendAll () [inline]
Definition at line 151 of file string-16.h.
{}
Referenced by appendAll().
appendAll() [2/2]
template<typename T , typename... R>
void v8_inspector::String16Builder::appendAll (T first, R... rest) [inline]
Definition at line 147 of file string-16.h.
                                     {
    append(first);
    appendAll(rest...);
  }
References append(), and appendAll().
Referenced by v8_inspector::String16::concat().
appendNumber() [1/2]
void v8_inspector::String16Builder::appendNumber (int number)
Definition at line 176 of file string-16.cc.
                                             {
  constexpr int kBufferSize = 11;
  char buffer[kBufferSize];
  int chars = v8::base::OS::SNPrintF(buffer, kBufferSize, "%d", number);
  DCHECK_LE(0, chars);
  m_buffer.insert(m_buffer.end(), buffer, buffer + chars);
}
References DCHECK_LE, v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, m_buffer, and v8::base::SNPrintF().
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateInstrumentationBreakpointId(), and v8_inspector::stackTraceIdToString().
appendNumber() [2/2]
void v8_inspector::String16Builder::appendNumber (size_t number)
Definition at line 184 of file string-16.cc.
                                                {
  constexpr int kBufferSize = 20;
  char buffer[kBufferSize];
#if defined(V8_OS_WIN)
  int chars = v8::base::OS::SNPrintF(buffer, kBufferSize, "%Iu", number);
#else
  int chars = v8::base::OS::SNPrintF(buffer, kBufferSize, "%zu", number);
#endif
  DCHECK_LE(0, chars);
  m_buffer.insert(m_buffer.end(), buffer, buffer + chars);
}
References DCHECK_LE, v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, m_buffer, and v8::base::SNPrintF().
appendUnsignedAsHex() [1/3]
void v8_inspector::String16Builder::appendUnsignedAsHex (uint32_t number)
Definition at line 205 of file string-16.cc.
                                                         {
  constexpr int kBufferSize = 9;
  char buffer[kBufferSize];
  int chars = v8::base::OS::SNPrintF(buffer, kBufferSize, "%08" PRIx32, number);
  DCHECK_LE(0, chars);
  m_buffer.insert(m_buffer.end(), buffer, buffer + chars);
}
References DCHECK_LE, v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, m_buffer, and v8::base::SNPrintF().
appendUnsignedAsHex() [2/3]
void v8_inspector::String16Builder::appendUnsignedAsHex (uint64_t number)
Definition at line 196 of file string-16.cc.
                                                         {
  constexpr int kBufferSize = 17;
  char buffer[kBufferSize];
  int chars =
      v8::base::OS::SNPrintF(buffer, kBufferSize, "%016" PRIx64, number);
  DCHECK_LE(0, chars);
  m_buffer.insert(m_buffer.end(), buffer, buffer + chars);
}
References DCHECK_LE, v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, m_buffer, and v8::base::SNPrintF().
Referenced by v8_inspector::V8DebuggerScript::buildId(), and v8_inspector::anonymous_namespace{v8-debugger-script.cc}::calculateHash().
appendUnsignedAsHex() [3/3]
void v8_inspector::String16Builder::appendUnsignedAsHex (uint8_t number)
Definition at line 213 of file string-16.cc.
                                                        {
  constexpr int kBufferSize = 3;
  char buffer[kBufferSize];
  int chars = v8::base::OS::SNPrintF(buffer, kBufferSize, "%02" PRIx8, number);
  DCHECK_LE(0, chars);
  m_buffer.insert(m_buffer.end(), buffer, buffer + chars);
}
References DCHECK_LE, v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, m_buffer, and v8::base::SNPrintF().
reserveCapacity()
void v8_inspector::String16Builder::reserveCapacity (size_t capacity)
Definition at line 225 of file string-16.cc.
                                                     {
  m_buffer.reserve(capacity);
}
References m_buffer.
Referenced by v8_inspector::String16::fromUTF16LE().
toString()
String16 v8_inspector::String16Builder::toString ()
Definition at line 221 of file string-16.cc.
                                   {
  return String16(m_buffer.data(), m_buffer.size());
}
References m_buffer.
Referenced by v8_inspector::V8DebuggerScript::buildId(), v8_inspector::anonymous_namespace{v8-debugger-script.cc}::calculateHash(), v8_inspector::String16::concat(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForRegExp(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::DescriptionForRegExpFlags(), v8_inspector::String16::fromUTF16LE(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateInstrumentationBreakpointId(), v8_inspector::V8Console::monitorFunctionCallback(), v8_inspector::V8DebuggerAgentImpl::setBlackboxPatterns(), v8_inspector::stackTraceIdToString(), and v8_inspector::V8StackTraceImpl::toString().
Member Data Documentation
m_buffer
std::vector<UChar> v8_inspector::String16Builder::m_buffer [private]
Definition at line 154 of file string-16.h.
Referenced by append(), appendNumber(), appendUnsignedAsHex(), reserveCapacity(), and toString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/string-16.h
/mnt/V8SourceCode/src/inspector/string-16.cc