v8::internal::UnoptimizedFrameInfo Class Reference
#include <frames.h>
Public Member Functions
uint32_t register_stack_slot_count () const
uint32_t frame_size_in_bytes_without_fixed () const
uint32_t frame_size_in_bytes () const
Static Public Member Functions
static UnoptimizedFrameInfo Precise (int parameters_count_with_receiver, int translation_height, bool is_topmost, bool pad_arguments)
static UnoptimizedFrameInfo Conservative (int parameters_count_with_receiver, int locals_count)
static uint32_t GetStackSizeForAdditionalArguments (int parameters_count)
Private Member Functions
UnoptimizedFrameInfo (int parameters_count_with_receiver, int translation_height, bool is_topmost, bool pad_arguments, FrameInfoKind frame_info_kind)
Private Attributes
uint32_t register_stack_slot_count_
uint32_t frame_size_in_bytes_without_fixed_
uint32_t frame_size_in_bytes_
Detailed Description
Definition at line 1891 of file frames.h.
Constructor & Destructor Documentation
UnoptimizedFrameInfo()
v8::internal::UnoptimizedFrameInfo::UnoptimizedFrameInfo (int parameters_count_with_receiver, int translation_height, bool is_topmost, bool pad_arguments, FrameInfoKind frame_info_kind) [private]
Definition at line 4198 of file frames.cc.
                                                                          {
  const int locals_count = translation_height;
  register_stack_slot_count_ =
      UnoptimizedFrameConstants::RegisterStackSlotCount(locals_count);
  static constexpr int kTheAccumulator = 1;
  static constexpr int kTopOfStackPadding = TopOfStackRegisterPaddingSlots();
  int maybe_additional_slots =
      (is_topmost || frame_info_kind == FrameInfoKind::kConservative)
          ? (kTheAccumulator + kTopOfStackPadding)
          : 0;
  frame_size_in_bytes_without_fixed_ =
      (register_stack_slot_count_ + maybe_additional_slots) *
      kSystemPointerSize;
  // The 'fixed' part of the frame consists of the incoming parameters and
  // the part described by InterpreterFrameConstants. This will include
  // argument padding, when needed.
  const int parameter_padding_slots =
      pad_arguments ? ArgumentPaddingSlots(parameters_count_with_receiver) : 0;
  const int fixed_frame_size =
      InterpreterFrameConstants::kFixedFrameSize +
      (parameters_count_with_receiver + parameter_padding_slots) *
          kSystemPointerSize;
  frame_size_in_bytes_ = frame_size_in_bytes_without_fixed_ + fixed_frame_size;
}
References v8::internal::ArgumentPaddingSlots(), v8::internal::kConservative, v8::internal::StandardFrameConstants::kFixedFrameSize, v8::internal::kSystemPointerSize, v8::internal::UnoptimizedFrameConstants::RegisterStackSlotCount(), and v8::internal::anonymous_namespace{frames.cc}::TopOfStackRegisterPaddingSlots().
Member Function Documentation
Conservative()
static UnoptimizedFrameInfo v8::internal::UnoptimizedFrameInfo::Conservative (int parameters_count_with_receiver, int locals_count) [inline], [static]
Definition at line 1900 of file frames.h.
                                                             {
    return {parameters_count_with_receiver, locals_count, false, true,
            FrameInfoKind::kConservative};
  }
References v8::internal::kConservative.
Referenced by v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), and v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes().
frame_size_in_bytes()
uint32_t v8::internal::UnoptimizedFrameInfo::frame_size_in_bytes () const [inline]
Definition at line 1914 of file frames.h.
{ return frame_size_in_bytes_; }
References frame_size_in_bytes_.
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
frame_size_in_bytes_without_fixed()
uint32_t v8::internal::UnoptimizedFrameInfo::frame_size_in_bytes_without_fixed () const [inline]
Definition at line 1911 of file frames.h.
                                                     {
    return frame_size_in_bytes_without_fixed_;
  }
References frame_size_in_bytes_without_fixed_.
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
GetStackSizeForAdditionalArguments()
uint32_t v8::internal::UnoptimizedFrameInfo::GetStackSizeForAdditionalArguments (int parameters_count) [static]
Definition at line 4230 of file frames.cc.
                          {
  return (parameters_count + ArgumentPaddingSlots(parameters_count)) *
         kSystemPointerSize;
}
References v8::internal::ArgumentPaddingSlots(), and v8::internal::kSystemPointerSize.
Referenced by v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes().
Precise()
static UnoptimizedFrameInfo v8::internal::UnoptimizedFrameInfo::Precise (int parameters_count_with_receiver, int translation_height, bool is_topmost, bool pad_arguments) [inline], [static]
Definition at line 1893 of file frames.h.
                                                          {
    return {parameters_count_with_receiver, translation_height, is_topmost,
            pad_arguments, FrameInfoKind::kPrecise};
  }
References v8::internal::kPrecise.
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
register_stack_slot_count()
uint32_t v8::internal::UnoptimizedFrameInfo::register_stack_slot_count () const [inline]
Definition at line 1908 of file frames.h.
                                             {
    return register_stack_slot_count_;
  }
References register_stack_slot_count_.
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
Member Data Documentation
frame_size_in_bytes_
uint32_t v8::internal::UnoptimizedFrameInfo::frame_size_in_bytes_ [private]
Definition at line 1923 of file frames.h.
Referenced by frame_size_in_bytes().
frame_size_in_bytes_without_fixed_
uint32_t v8::internal::UnoptimizedFrameInfo::frame_size_in_bytes_without_fixed_ [private]
Definition at line 1922 of file frames.h.
Referenced by frame_size_in_bytes_without_fixed().
register_stack_slot_count_
uint32_t v8::internal::UnoptimizedFrameInfo::register_stack_slot_count_ [private]
Definition at line 1921 of file frames.h.
Referenced by register_stack_slot_count().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc