v8_inspector::V8Inspector::Channel Class Reference
#include <v8-inspector.h>
Public Member Functions
virtual ~Channel ()=default
virtual void sendResponse (int callId, std::unique_ptr< StringBuffer > message)=0
virtual void sendNotification (std::unique_ptr< StringBuffer > message)=0
virtual void flushProtocolNotifications ()=0
Detailed Description
Definition at line 400 of file v8-inspector.h.
Constructor & Destructor Documentation
 Channel()
virtual v8_inspector::V8Inspector::Channel::~Channel () [virtual], [default]
Member Function Documentation
flushProtocolNotifications()
virtual void v8_inspector::V8Inspector::Channel::flushProtocolNotifications () [pure virtual]
Implemented in v8::InspectorFrontend.
Referenced by v8_inspector::V8InspectorSessionImpl::FlushProtocolNotifications().
sendNotification()
virtual void v8_inspector::V8Inspector::Channel::sendNotification (std::unique_ptr< StringBuffer > message) [pure virtual]
Implemented in v8::InspectorFrontend.
Referenced by v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(), and v8_inspector::V8InspectorSessionImpl::SendProtocolNotification().
sendResponse()
virtual void v8_inspector::V8Inspector::Channel::sendResponse (int callId, std::unique_ptr< StringBuffer > message) [pure virtual]
Implemented in v8::InspectorFrontend.
Referenced by v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(), and v8_inspector::V8InspectorSessionImpl::SendProtocolResponse().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-inspector.h