v8::internal::interpreter::BytecodeLabel Class Reference
#include <bytecode-label.h>
Public Member Functions
BytecodeLabel ()
bool is_bound () const
size_t jump_offset () const
bool has_referrer_jump () const
Private Member Functions
void bind ()
void set_referrer (size_t offset)
Private Attributes
bool bound_
size_t jump_offset_
Static Private Attributes
static const size_t kInvalidOffset = static_cast<size_t>(-1)
Friends
class BytecodeArrayWriter
Detailed Description
Definition at line 48 of file bytecode-label.h.
Constructor & Destructor Documentation
BytecodeLabel()
v8::internal::interpreter::BytecodeLabel::BytecodeLabel () [inline]
Definition at line 50 of file bytecode-label.h.
: bound_(false), jump_offset_(kInvalidOffset) {}
Member Function Documentation
bind()
void v8::internal::interpreter::BytecodeLabel::bind () [inline], [private]
Definition at line 63 of file bytecode-label.h.
              {
    DCHECK(!bound_);
    bound_ = true;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindLabel().
has_referrer_jump()
bool v8::internal::interpreter::BytecodeLabel::has_referrer_jump () const [inline]
Definition at line 58 of file bytecode-label.h.
{ return jump_offset_ != kInvalidOffset; }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::Bind(), and v8::internal::interpreter::BytecodeArrayWriter::BindLabel().
is_bound()
bool v8::internal::interpreter::BytecodeLabel::is_bound () const [inline]
Definition at line 52 of file bytecode-label.h.
{ return bound_; }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfFalse(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfForInDone(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfJSReceiver(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNotNull(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNotUndefined(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNull(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefined(), and v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull().
jump_offset()
size_t v8::internal::interpreter::BytecodeLabel::jump_offset () const [inline]
Definition at line 53 of file bytecode-label.h.
                             {
    DCHECK_NE(jump_offset_, kInvalidOffset);
    return jump_offset_;
  }
References DCHECK_NE.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindLabel().
set_referrer()
void v8::internal::interpreter::BytecodeLabel::set_referrer (size_t offset) [inline], [private]
Definition at line 68 of file bytecode-label.h.
                                   {
    DCHECK(!bound_);
    DCHECK_NE(offset, kInvalidOffset);
    DCHECK_EQ(jump_offset_, kInvalidOffset);
    jump_offset_ = offset;
  }
References v8::internal::DCHECK(), DCHECK_EQ, and DCHECK_NE.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitJump().
Friends And Related Function Documentation
BytecodeArrayWriter
friend class BytecodeArrayWriter [friend]
Definition at line 80 of file bytecode-label.h.
Member Data Documentation
bound_
bool v8::internal::interpreter::BytecodeLabel::bound_ [private]
Definition at line 76 of file bytecode-label.h.
jump_offset_
size_t v8::internal::interpreter::BytecodeLabel::jump_offset_ [private]
Definition at line 78 of file bytecode-label.h.
kInvalidOffset
const size_t v8::internal::interpreter::BytecodeLabel::kInvalidOffset = static_cast<size_t>(-1) [static], [private]
Definition at line 61 of file bytecode-label.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-label.h