v8::internal::StatisticsExtension Class Reference
#include <statistics-extension.h>
Public Member Functions
StatisticsExtension ()
v8::Local< v8::FunctionTemplate > GetNativeFunctionTemplate (v8::Isolate *isolate, v8::Local< v8::String > name) override
Static Public Member Functions
static void GetCounters (const v8::FunctionCallbackInfo< v8::Value > &info)
Static Private Attributes
static const char *const kSource
Detailed Description
Definition at line 17 of file statistics-extension.h.
Constructor & Destructor Documentation
StatisticsExtension()
v8::internal::StatisticsExtension::StatisticsExtension () [inline]
Definition at line 19 of file statistics-extension.h.
: v8::Extension("v8/statistics", kSource) {}
Member Function Documentation
GetCounters()
void v8::internal::StatisticsExtension::GetCounters (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 63 of file statistics-extension.cc.
                                                 {
  DCHECK(ValidateCallbackInfo(info));
  Isolate* isolate = reinterpret_cast<Isolate*>(info.GetIsolate());
  Heap* heap = isolate->heap();
  if (info.Length() > 0) { // GC if first argument evaluates to true.
    if (info[0]->IsBoolean() && info[0]->BooleanValue(info.GetIsolate())) {
      heap->CollectAllGarbage(GCFlag::kNoFlags,
                              GarbageCollectionReason::kCountersExtension);
    }
  }
  Counters* counters = isolate->counters();
  v8::Local<v8::Object> result = v8::Object::New(info.GetIsolate());
  heap->FreeMainThreadLinearAllocationAreas();
  struct StatisticsCounter {
    v8::internal::StatsCounter* counter;
    const char* name;
  };
  // clang-format off
  const StatisticsCounter counter_list[] = {
#define ADD_COUNTER(name, caption) {counters->name(), #name},
      STATS_COUNTER_LIST(ADD_COUNTER)
      STATS_COUNTER_NATIVE_CODE_LIST(ADD_COUNTER)
#undef ADD_COUNTER
  }; // End counter_list array.
  // clang-format on
  for (size_t i = 0; i < arraysize(counter_list); i++) {
    AddCounter(info.GetIsolate(), result, counter_list[i].counter,
               counter_list[i].name);
  }
  struct StatisticNumber {
    size_t number;
    const char* name;
  };
  size_t new_space_size = 0;
  size_t new_space_available = 0;
  size_t new_space_committed_memory = 0;
  if (heap->new_space()) {
    new_space_size = heap->new_space()->Size();
    new_space_available = heap->new_space()->Available();
    new_space_committed_memory = heap->new_space()->CommittedMemory();
  }
  const StatisticNumber numbers[] = {
      {heap->memory_allocator()->Size(), "total_committed_bytes"},
      {new_space_size, "new_space_live_bytes"},
      {new_space_available, "new_space_available_bytes"},
      {new_space_committed_memory, "new_space_commited_bytes"},
      {heap->old_space()->Size(), "old_space_live_bytes"},
      {heap->old_space()->Available(), "old_space_available_bytes"},
      {heap->old_space()->CommittedMemory(), "old_space_commited_bytes"},
      {heap->code_space()->Size(), "code_space_live_bytes"},
      {heap->code_space()->Available(), "code_space_available_bytes"},
      {heap->code_space()->CommittedMemory(), "code_space_commited_bytes"},
      {heap->lo_space()->Size(), "lo_space_live_bytes"},
      {heap->lo_space()->Available(), "lo_space_available_bytes"},
      {heap->lo_space()->CommittedMemory(), "lo_space_commited_bytes"},
      {heap->code_lo_space()->Size(), "code_lo_space_live_bytes"},
      {heap->code_lo_space()->Available(), "code_lo_space_available_bytes"},
      {heap->code_lo_space()->CommittedMemory(),
       "code_lo_space_commited_bytes"},
      {heap->trusted_space()->Size(), "trusted_space_live_bytes"},
      {heap->trusted_space()->Available(), "trusted_space_available_bytes"},
      {heap->trusted_space()->CommittedMemory(),
       "trusted_space_commited_bytes"},
      {heap->trusted_lo_space()->Size(), "trusted_lo_space_live_bytes"},
      {heap->trusted_lo_space()->Available(),
       "trusted_lo_space_available_bytes"},
      {heap->trusted_lo_space()->CommittedMemory(),
       "trusted_lo_space_commited_bytes"},
  };
  for (size_t i = 0; i < arraysize(numbers); i++) {
    AddNumber(info.GetIsolate(), result, numbers[i].number, numbers[i].name);
  }
  AddNumber64(info.GetIsolate(), result, heap->external_memory(),
              "amount_of_external_allocated_memory");
  int reloc_info_total = 0;
  int source_position_table_total = 0;
  {
    HeapObjectIterator iterator(
        reinterpret_cast<Isolate*>(info.GetIsolate())->heap());
    DCHECK(!AllowGarbageCollection::IsAllowed());
    for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
         obj = iterator.Next()) {
      Tagged<Object> maybe_source_positions;
      if (IsCode(obj)) {
        Tagged<Code> code = Cast<Code>(obj);
        reloc_info_total += code->relocation_size();
        if (!code->has_source_position_table()) continue;
        maybe_source_positions = code->source_position_table();
      } else if (IsBytecodeArray(obj)) {
        maybe_source_positions =
            Cast<BytecodeArray>(obj)->raw_source_position_table(kAcquireLoad);
      } else {
        continue;
      }
      if (!IsTrustedByteArray(maybe_source_positions)) continue;
      Tagged<TrustedByteArray> source_positions =
          Cast<TrustedByteArray>(maybe_source_positions);
      if (source_positions->length() == 0) continue;
      source_position_table_total += source_positions->AllocatedSize();
    }
  }
  AddNumber(info.GetIsolate(), result, reloc_info_total,
            "reloc_info_total_size");
  AddNumber(info.GetIsolate(), result, source_position_table_total,
            "source_position_table_total_size");
  info.GetReturnValue().Set(result);
}
References ADD_COUNTER, v8::internal::AddCounter(), v8::internal::AddNumber(), v8::internal::AddNumber64(), arraysize, code, v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), v8::kAcquireLoad, v8::internal::kCountersExtension, v8::internal::kNoFlags, v8::FunctionCallbackInfo< T >::Length(), v8::Extension::name(), v8::Object::New(), v8::internal::HeapObjectIterator::Next(), v8::base::internal::result, STATS_COUNTER_LIST, STATS_COUNTER_NATIVE_CODE_LIST, and v8::internal::ValidateCallbackInfo().
Referenced by GetNativeFunctionTemplate().
GetNativeFunctionTemplate()
v8::Local< v8::FunctionTemplate > v8::internal::StatisticsExtension::GetNativeFunctionTemplate (v8::Isolate * isolate, v8::Local< v8::String > name) [override], [virtual]
Reimplemented from v8::Extension.
Definition at line 22 of file statistics-extension.cc.
                                               {
  DCHECK_EQ(strcmp(*v8::String::Utf8Value(isolate, str), "getV8Statistics"), 0);
  return v8::FunctionTemplate::New(isolate, StatisticsExtension::GetCounters);
}
References DCHECK_EQ, GetCounters(), and v8::FunctionTemplate::New().
Member Data Documentation
kSource
const char *const v8::internal::StatisticsExtension::kSource [static], [private]
Initial value:
=
    "native function getV8Statistics();"
Definition at line 25 of file statistics-extension.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/extensions/statistics-extension.h
/mnt/V8SourceCode/src/extensions/statistics-extension.cc