v8::internal::FeedbackMetadata Class Reference
#include <feedback-vector.h>
Classes
class BodyDescriptor
Public Member Functions
int32_t slot_count (AcquireLoadTag) const
int32_t create_closure_slot_count (AcquireLoadTag) const
bool SpecDiffersFrom (const FeedbackVectorSpec *other_spec) const
bool is_empty () const
V8_EXPORT_PRIVATE FeedbackSlotKind GetKind (FeedbackSlot slot) const
V8_EXPORT_PRIVATE uint16_t GetCreateClosureParameterCount (int index) const
int AllocatedSize ()
template<typename IsolateT >
Handle< FeedbackMetadata > New (IsolateT *isolate, const FeedbackVectorSpec *spec)
Static Public Member Functions
static int GetSlotSize (FeedbackSlotKind kind)
template<typename IsolateT >
static V8_EXPORT_PRIVATE Handle< FeedbackMetadata > New (IsolateT *isolate, const FeedbackVectorSpec *spec)
static const char * Kind2String (FeedbackSlotKind kind)
static int SizeFor (int slot_count, int create_closure_slot_count)
Private Types
using VectorICComputer = base::BitSetComputer< FeedbackSlotKind, kFeedbackSlotKindBits, kInt32Size *kBitsPerByte, uint32_t >
Private Member Functions
int32_t get (int index) const
void set (int index, int32_t value)
int word_count () const
void SetKind (FeedbackSlot slot, FeedbackSlotKind kind)
void SetCreateClosureParameterCount (int index, uint16_t parameter_count)
OBJECT_CONSTRUCTORS (FeedbackMetadata, HeapObject)
Static Private Member Functions
static int word_count (int slot_count)
Static Private Attributes
static const int kFeedbackSlotKindBits = 5
Friends
class AccessorAssembler
Additional Inherited Members
Detailed Description
Definition at line 732 of file feedback-vector.h.
Member Typedef Documentation
VectorICComputer
using v8::internal::FeedbackMetadata::VectorICComputer = base::BitSetComputer<FeedbackSlotKind, kFeedbackSlotKindBits, kInt32Size * kBitsPerByte, uint32_t> [private]
Definition at line 815 of file feedback-vector.h.
Member Function Documentation
AllocatedSize()
int v8::internal::FeedbackMetadata::AllocatedSize () [inline]
Definition at line 80 of file feedback-vector-inl.h.
                                    {
  return SizeFor(slot_count(kAcquireLoad),
                 create_closure_slot_count(kAcquireLoad));
}
References create_closure_slot_count(), v8::kAcquireLoad, SizeFor(), and slot_count().
create_closure_slot_count()
int32_t v8::internal::FeedbackMetadata::create_closure_slot_count (AcquireLoadTag) const [inline]
Referenced by AllocatedSize(), GetCreateClosureParameterCount(), is_empty(), New(), SetCreateClosureParameterCount(), and SizeFor().
get()
int32_t v8::internal::FeedbackMetadata::get (int index) const [inline], [private]
Referenced by GetKind(), and SetKind().
GetCreateClosureParameterCount()
uint16_t v8::internal::FeedbackMetadata::GetCreateClosureParameterCount (int index) const
Definition at line 68 of file feedback-vector.cc.
                                                                         {
  DCHECK_LT(index, create_closure_slot_count());
  int offset = kHeaderSize + word_count() * kInt32Size + index * kUInt16Size;
  return ReadField<uint16_t>(offset);
}
References create_closure_slot_count(), DCHECK_LT, v8::internal::index, v8::internal::HeapObject::kHeaderSize, v8::internal::kInt32Size, v8::internal::kUInt16Size, and word_count().
GetKind()
FeedbackSlotKind v8::internal::FeedbackMetadata::GetKind (FeedbackSlot slot) const
Definition at line 55 of file feedback-vector.cc.
                                                                  {
  int index = VectorICComputer::index(0, slot.ToInt());
  int data = get(index);
  return VectorICComputer::decode(data, slot.ToInt());
}
References v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::decode(), get(), v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::index(), v8::internal::index, and v8::internal::FeedbackSlot::ToInt().
Referenced by SpecDiffersFrom().
GetSlotSize()
int v8::internal::FeedbackMetadata::GetSlotSize (FeedbackSlotKind kind) [inline], [static]
Definition at line 89 of file feedback-vector-inl.h.
                                                       {
  switch (kind) {
    case FeedbackSlotKind::kForIn:
    case FeedbackSlotKind::kInstanceOf:
    case FeedbackSlotKind::kTypeOf:
    case FeedbackSlotKind::kCompareOp:
    case FeedbackSlotKind::kBinaryOp:
    case FeedbackSlotKind::kLiteral:
    case FeedbackSlotKind::kJumpLoop:
      return 1;
    case FeedbackSlotKind::kCall:
    case FeedbackSlotKind::kCloneObject:
    case FeedbackSlotKind::kLoadProperty:
    case FeedbackSlotKind::kLoadGlobalInsideTypeof:
    case FeedbackSlotKind::kLoadGlobalNotInsideTypeof:
    case FeedbackSlotKind::kLoadKeyed:
    case FeedbackSlotKind::kHasKeyed:
    case FeedbackSlotKind::kSetNamedSloppy:
    case FeedbackSlotKind::kSetNamedStrict:
    case FeedbackSlotKind::kDefineNamedOwn:
    case FeedbackSlotKind::kDefineKeyedOwn:
    case FeedbackSlotKind::kStoreGlobalSloppy:
    case FeedbackSlotKind::kStoreGlobalStrict:
    case FeedbackSlotKind::kSetKeyedSloppy:
    case FeedbackSlotKind::kSetKeyedStrict:
    case FeedbackSlotKind::kStoreInArrayLiteral:
    case FeedbackSlotKind::kDefineKeyedOwnPropertyInLiteral:
    case FeedbackSlotKind::kStringAddAndInternalize:
      return 2;
    case FeedbackSlotKind::kInvalid:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::kBinaryOp, v8::internal::kCall, v8::internal::kCloneObject, v8::internal::kCompareOp, v8::internal::kDefineKeyedOwn, v8::internal::kDefineKeyedOwnPropertyInLiteral, v8::internal::kDefineNamedOwn, v8::internal::kForIn, v8::internal::kHasKeyed, v8::internal::kInstanceOf, v8::internal::kInvalid, v8::internal::kJumpLoop, v8::internal::kLiteral, v8::internal::kLoadGlobalInsideTypeof, v8::internal::kLoadGlobalNotInsideTypeof, v8::internal::kLoadKeyed, v8::internal::kLoadProperty, v8::internal::kSetKeyedSloppy, v8::internal::kSetKeyedStrict, v8::internal::kSetNamedSloppy, v8::internal::kSetNamedStrict, v8::internal::kStoreGlobalSloppy, v8::internal::kStoreGlobalStrict, v8::internal::kStoreInArrayLiteral, v8::internal::kStringAddAndInternalize, v8::internal::kTypeOf, and v8::internal::UNREACHABLE().
Referenced by v8::internal::FeedbackVectorSpec::AddSlot(), v8::internal::FeedbackMetadataIterator::entry_size(), v8::internal::FeedbackNexus::GetFeedbackPair(), v8::internal::FeedbackVector::New(), New(), and SpecDiffersFrom().
is_empty()
bool v8::internal::FeedbackMetadata::is_empty () const [inline]
Definition at line 75 of file feedback-vector-inl.h.
                                      {
  DCHECK_IMPLIES(slot_count() == 0, create_closure_slot_count() == 0);
  return slot_count() == 0;
}
References create_closure_slot_count(), DCHECK_IMPLIES, and slot_count().
Kind2String()
const char * v8::internal::FeedbackMetadata::Kind2String (FeedbackSlotKind kind) [static]
Definition at line 148 of file feedback-vector.cc.
                                                               {
  switch (kind) {
    case FeedbackSlotKind::kInvalid:
      return "Invalid";
    case FeedbackSlotKind::kCall:
      return "Call";
    case FeedbackSlotKind::kLoadProperty:
      return "LoadProperty";
    case FeedbackSlotKind::kLoadGlobalInsideTypeof:
      return "LoadGlobalInsideTypeof";
    case FeedbackSlotKind::kLoadGlobalNotInsideTypeof:
      return "LoadGlobalNotInsideTypeof";
    case FeedbackSlotKind::kLoadKeyed:
      return "LoadKeyed";
    case FeedbackSlotKind::kHasKeyed:
      return "HasKeyed";
    case FeedbackSlotKind::kSetNamedSloppy:
      return "SetNamedSloppy";
    case FeedbackSlotKind::kSetNamedStrict:
      return "SetNamedStrict";
    case FeedbackSlotKind::kDefineNamedOwn:
      return "DefineNamedOwn";
    case FeedbackSlotKind::kDefineKeyedOwn:
      return "DefineKeyedOwn";
    case FeedbackSlotKind::kStoreGlobalSloppy:
      return "StoreGlobalSloppy";
    case FeedbackSlotKind::kStoreGlobalStrict:
      return "StoreGlobalStrict";
    case FeedbackSlotKind::kSetKeyedSloppy:
      return "StoreKeyedSloppy";
    case FeedbackSlotKind::kSetKeyedStrict:
      return "StoreKeyedStrict";
    case FeedbackSlotKind::kStoreInArrayLiteral:
      return "StoreInArrayLiteral";
    case FeedbackSlotKind::kBinaryOp:
      return "BinaryOp";
    case FeedbackSlotKind::kCompareOp:
      return "CompareOp";
    case FeedbackSlotKind::kDefineKeyedOwnPropertyInLiteral:
      return "DefineKeyedOwnPropertyInLiteral";
    case FeedbackSlotKind::kLiteral:
      return "Literal";
    case FeedbackSlotKind::kForIn:
      return "ForIn";
    case FeedbackSlotKind::kInstanceOf:
      return "InstanceOf";
    case FeedbackSlotKind::kTypeOf:
      return "TypeOf";
    case FeedbackSlotKind::kCloneObject:
      return "CloneObject";
    case FeedbackSlotKind::kJumpLoop:
      return "JumpLoop";
    case FeedbackSlotKind::kStringAddAndInternalize:
      return "StringAddAndInternalize";
  }
}
References v8::internal::kBinaryOp, v8::internal::kCall, v8::internal::kCloneObject, v8::internal::kCompareOp, v8::internal::kDefineKeyedOwn, v8::internal::kDefineKeyedOwnPropertyInLiteral, v8::internal::kDefineNamedOwn, v8::internal::kForIn, v8::internal::kHasKeyed, v8::internal::kInstanceOf, v8::internal::kInvalid, v8::internal::kJumpLoop, v8::internal::kLiteral, v8::internal::kLoadGlobalInsideTypeof, v8::internal::kLoadGlobalNotInsideTypeof, v8::internal::kLoadKeyed, v8::internal::kLoadProperty, v8::internal::kSetKeyedSloppy, v8::internal::kSetKeyedStrict, v8::internal::kSetNamedSloppy, v8::internal::kSetNamedStrict, v8::internal::kStoreGlobalSloppy, v8::internal::kStoreGlobalStrict, v8::internal::kStoreInArrayLiteral, v8::internal::kStringAddAndInternalize, and v8::internal::kTypeOf.
Referenced by v8::internal::operator<<().
New() [1/2]
template<typename IsolateT >
Handle<FeedbackMetadata> v8::internal::FeedbackMetadata::New (IsolateT * isolate, const FeedbackVectorSpec * spec)
Definition at line 83 of file feedback-vector.cc.
                                                                               {
  auto* factory = isolate->factory();
  const int slot_count = spec->slot_count();
  const int create_closure_slot_count = spec->create_closure_slot_count();
  if (slot_count == 0 && create_closure_slot_count == 0) {
    return factory->empty_feedback_metadata();
  }
#ifdef DEBUG
  for (int i = 0; i < slot_count;) {
    FeedbackSlotKind kind = spec->GetKind(FeedbackSlot(i));
    int entry_size = FeedbackMetadata::GetSlotSize(kind);
    for (int j = 1; j < entry_size; j++) {
      kind = spec->GetKind(FeedbackSlot(i + j));
      DCHECK_EQ(FeedbackSlotKind::kInvalid, kind);
    }
    i += entry_size;
  }
#endif
  Handle<FeedbackMetadata> metadata =
      factory->NewFeedbackMetadata(slot_count, create_closure_slot_count);
  // Initialize the slots. The raw data section has already been pre-zeroed in
  // NewFeedbackMetadata.
  for (int i = 0; i < slot_count; i++) {
    FeedbackSlot slot(i);
    FeedbackSlotKind kind = spec->GetKind(slot);
    metadata->SetKind(slot, kind);
  }
  for (int i = 0; i < create_closure_slot_count; i++) {
    uint16_t parameter_count = spec->GetCreateClosureParameterCount(i);
    metadata->SetCreateClosureParameterCount(i, parameter_count);
  }
  return metadata;
}
References v8::internal::FeedbackVectorSpec::create_closure_slot_count(), create_closure_slot_count(), DCHECK_EQ, v8::internal::FeedbackVectorSpec::GetCreateClosureParameterCount(), v8::internal::FeedbackVectorSpec::GetKind(), GetSlotSize(), v8::internal::kInvalid, v8::internal::FeedbackVectorSpec::slot_count(), and slot_count().
New() [2/2]
template<typename IsolateT >
static V8_EXPORT_PRIVATE Handle<FeedbackMetadata> v8::internal::FeedbackMetadata::New (IsolateT * isolate, const FeedbackVectorSpec * spec) [static]
Referenced by v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode(), and v8::internal::FeedbackVector::NewForTesting().
OBJECT_CONSTRUCTORS()
v8::internal::FeedbackMetadata::OBJECT_CONSTRUCTORS (FeedbackMetadata , HeapObject) [private]
set()
void v8::internal::FeedbackMetadata::set (int index, int32_t value) [inline], [private]
Referenced by SetKind().
SetCreateClosureParameterCount()
void v8::internal::FeedbackMetadata::SetCreateClosureParameterCount (int index, uint16_t parameter_count) [private]
Definition at line 74 of file feedback-vector.cc.
                                         {
  DCHECK_LT(index, create_closure_slot_count());
  int offset = kHeaderSize + word_count() * kInt32Size + index * kUInt16Size;
  return WriteField<uint16_t>(offset, parameter_count);
}
References create_closure_slot_count(), DCHECK_LT, v8::internal::index, v8::internal::HeapObject::kHeaderSize, v8::internal::kInt32Size, v8::internal::kUInt16Size, and word_count().
SetKind()
void v8::internal::FeedbackMetadata::SetKind (FeedbackSlot slot, FeedbackSlotKind kind) [private]
Definition at line 61 of file feedback-vector.cc.
                                                                       {
  int index = VectorICComputer::index(0, slot.ToInt());
  int data = get(index);
  int new_data = VectorICComputer::encode(data, slot.ToInt(), kind);
  set(index, new_data);
}
References v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::encode(), get(), v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::index(), v8::internal::index, set(), and v8::internal::FeedbackSlot::ToInt().
SizeFor()
static int v8::internal::FeedbackMetadata::SizeFor (int slot_count, int create_closure_slot_count) [inline], [static]
Definition at line 778 of file feedback-vector.h.
                                                                    {
    return OBJECT_POINTER_ALIGN(kHeaderSize +
                                word_count(slot_count) * kInt32Size +
                                create_closure_slot_count * kUInt16Size);
  }
References create_closure_slot_count(), v8::internal::HeapObject::kHeaderSize, v8::internal::kInt32Size, v8::internal::kUInt16Size, OBJECT_POINTER_ALIGN, slot_count(), and word_count().
Referenced by AllocatedSize(), and v8::internal::FactoryBase< Impl >::NewFeedbackMetadata().
slot_count()
int32_t v8::internal::FeedbackMetadata::slot_count (AcquireLoadTag) const [inline]
Referenced by AllocatedSize(), is_empty(), New(), SizeFor(), SpecDiffersFrom(), and word_count().
SpecDiffersFrom()
bool v8::internal::FeedbackMetadata::SpecDiffersFrom (const FeedbackVectorSpec * other_spec) const
Definition at line 128 of file feedback-vector.cc.
                                                {
  if (other_spec->slot_count() != slot_count()) {
    return true;
  }
  int slots = slot_count();
  for (int i = 0; i < slots;) {
    FeedbackSlot slot(i);
    FeedbackSlotKind kind = GetKind(slot);
    int entry_size = FeedbackMetadata::GetSlotSize(kind);
    if (kind != other_spec->GetKind(slot)) {
      return true;
    }
    i += entry_size;
  }
  return false;
}
References v8::internal::FeedbackVectorSpec::GetKind(), GetKind(), GetSlotSize(), v8::internal::FeedbackVectorSpec::slot_count(), and slot_count().
word_count() [1/2]
int v8::internal::FeedbackMetadata::word_count () const [inline], [private]
Definition at line 85 of file feedback-vector-inl.h.
                                       {
  return FeedbackMetadata::word_count(slot_count());
}
References slot_count().
Referenced by GetCreateClosureParameterCount(), SetCreateClosureParameterCount(), and SizeFor().
word_count() [2/2]
static int v8::internal::FeedbackMetadata::word_count (int slot_count) [inline], [static], [private]
Definition at line 803 of file feedback-vector.h.
                                        {
    return VectorICComputer::word_count(slot_count);
  }
References slot_count(), and v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::word_count().
Friends And Related Function Documentation
AccessorAssembler
friend class AccessorAssembler [friend]
Definition at line 795 of file feedback-vector.h.
Member Data Documentation
kFeedbackSlotKindBits
const int v8::internal::FeedbackMetadata::kFeedbackSlotKindBits = 5 [static], [private]
Definition at line 808 of file feedback-vector.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-vector.h
/mnt/V8SourceCode/src/objects/feedback-vector-inl.h
/mnt/V8SourceCode/src/objects/feedback-vector.cc