v8::internal::compiler::JSOperatorBuilder Class Reference
#include <js-operator.h>
Public Member Functions
JSOperatorBuilder (Zone *zone)
JSOperatorBuilder (const JSOperatorBuilder &)=delete
JSOperatorBuilder & operator= (const JSOperatorBuilder &)=delete
const Operator * Equal (FeedbackSource const &feedback)
const Operator * StrictEqual (FeedbackSource const &feedback)
const Operator * LessThan (FeedbackSource const &feedback)
const Operator * GreaterThan (FeedbackSource const &feedback)
const Operator * LessThanOrEqual (FeedbackSource const &feedback)
const Operator * GreaterThanOrEqual (FeedbackSource const &feedback)
const Operator * BitwiseOr (FeedbackSource const &feedback)
const Operator * BitwiseXor (FeedbackSource const &feedback)
const Operator * BitwiseAnd (FeedbackSource const &feedback)
const Operator * ShiftLeft (FeedbackSource const &feedback)
const Operator * ShiftRight (FeedbackSource const &feedback)
const Operator * ShiftRightLogical (FeedbackSource const &feedback)
const Operator * Add (FeedbackSource const &feedback)
const Operator * Subtract (FeedbackSource const &feedback)
const Operator * Multiply (FeedbackSource const &feedback)
const Operator * Divide (FeedbackSource const &feedback)
const Operator * Modulus (FeedbackSource const &feedback)
const Operator * Exponentiate (FeedbackSource const &feedback)
const Operator * BitwiseNot (FeedbackSource const &feedback)
const Operator * Decrement (FeedbackSource const &feedback)
const Operator * Increment (FeedbackSource const &feedback)
const Operator * Negate (FeedbackSource const &feedback)
const Operator * ToLength ()
const Operator * ToName ()
const Operator * ToNumber ()
const Operator * ToNumberConvertBigInt ()
const Operator * ToBigInt ()
const Operator * ToBigIntConvertNumber ()
const Operator * ToNumeric ()
const Operator * ToObject ()
const Operator * ToString ()
const Operator * Create ()
const Operator * CreateArguments (CreateArgumentsType type)
const Operator * CreateArray (size_t arity, OptionalAllocationSiteRef site, const FeedbackSource &feedback)
const Operator * CreateArrayIterator (IterationKind)
const Operator * CreateAsyncFunctionObject (int register_count)
const Operator * CreateCollectionIterator (CollectionKind, IterationKind)
const Operator * CreateBoundFunction (size_t arity, MapRef map)
const Operator * CreateClosure (SharedFunctionInfoRef shared_info, CodeRef code, AllocationType allocation=AllocationType::kYoung)
const Operator * CreateIterResultObject ()
const Operator * CreateStringIterator ()
const Operator * CreateKeyValueArray ()
const Operator * CreateObject ()
const Operator * CreateStringWrapper ()
const Operator * CreatePromise ()
const Operator * CreateTypedArray ()
const Operator * CreateLiteralArray (ArrayBoilerplateDescriptionRef constant, FeedbackSource const &feedback, int literal_flags, int number_of_elements)
const Operator * CreateEmptyLiteralArray (FeedbackSource const &feedback)
const Operator * CreateArrayFromIterable ()
const Operator * CreateEmptyLiteralObject ()
const Operator * CreateLiteralObject (ObjectBoilerplateDescriptionRef constant, FeedbackSource const &feedback, int literal_flags, int number_of_properties)
const Operator * CloneObject (FeedbackSource const &feedback, int literal_flags)
const Operator * CreateLiteralRegExp (StringRef constant_pattern, FeedbackSource const &feedback, int literal_flags)
const Operator * GetTemplateObject (TemplateObjectDescriptionRef description, SharedFunctionInfoRef shared, FeedbackSource const &feedback)
const Operator * CallForwardVarargs (size_t arity, uint32_t start_index)
const Operator * Call (size_t arity, CallFrequency const &frequency=CallFrequency(), FeedbackSource const &feedback=FeedbackSource(), ConvertReceiverMode convert_mode=ConvertReceiverMode::kAny, SpeculationMode speculation_mode=SpeculationMode::kDisallowSpeculation, CallFeedbackRelation feedback_relation=CallFeedbackRelation::kUnrelated)
const Operator * CallWithArrayLike (CallFrequency const &frequency, const FeedbackSource &feedback=FeedbackSource{}, SpeculationMode speculation_mode=SpeculationMode::kDisallowSpeculation, CallFeedbackRelation feedback_relation=CallFeedbackRelation::kTarget)
const Operator * CallWithSpread (uint32_t arity, CallFrequency const &frequency=CallFrequency(), FeedbackSource const &feedback=FeedbackSource(), SpeculationMode speculation_mode=SpeculationMode::kDisallowSpeculation, CallFeedbackRelation feedback_relation=CallFeedbackRelation::kTarget)
const Operator * CallRuntime (Runtime::FunctionId id)
const Operator * CallRuntime (Runtime::FunctionId id, size_t arity, Operator::Properties properties=Operator::kNoProperties)
const Operator * CallRuntime (const Runtime::Function *function, size_t arity, Operator::Properties properties=Operator::kNoProperties)
const Operator * ConstructForwardVarargs (size_t arity, uint32_t start_index)
const Operator * Construct (uint32_t arity, CallFrequency const &frequency=CallFrequency(), FeedbackSource const &feedback=FeedbackSource())
const Operator * ConstructWithArrayLike (CallFrequency const &frequency, FeedbackSource const &feedback)
const Operator * ConstructWithSpread (uint32_t arity, CallFrequency const &frequency=CallFrequency(), FeedbackSource const &feedback=FeedbackSource())
const Operator * ConstructForwardAllArgs (CallFrequency const &frequency=CallFrequency(), FeedbackSource const &feedback=FeedbackSource())
const Operator * LoadProperty (FeedbackSource const &feedback)
const Operator * LoadNamed (NameRef name, FeedbackSource const &feedback)
const Operator * LoadNamedFromSuper (NameRef name, FeedbackSource const &feedback)
const Operator * SetKeyedProperty (LanguageMode language_mode, FeedbackSource const &feedback)
const Operator * DefineKeyedOwnProperty (LanguageMode language_mode, FeedbackSource const &feedback)
const Operator * SetNamedProperty (LanguageMode language_mode, NameRef name, FeedbackSource const &feedback)
const Operator * DefineNamedOwnProperty (NameRef name, FeedbackSource const &feedback)
const Operator * DefineKeyedOwnPropertyInLiteral (const FeedbackSource &feedback)
const Operator * StoreInArrayLiteral (const FeedbackSource &feedback)
const Operator * DeleteProperty ()
const Operator * HasProperty (FeedbackSource const &feedback)
const Operator * GetSuperConstructor ()
const Operator * FindNonDefaultConstructorOrConstruct ()
const Operator * CreateGeneratorObject ()
const Operator * LoadGlobal (NameRef name, const FeedbackSource &feedback, TypeofMode typeof_mode=TypeofMode::kNotInside)
const Operator * StoreGlobal (LanguageMode language_mode, NameRef name, const FeedbackSource &feedback)
const Operator * HasContextExtension (size_t depth)
const Operator * LoadContextNoCell (size_t depth, size_t index, bool immutable)
const Operator * LoadContext (size_t depth, size_t index)
const Operator * StoreContextNoCell (size_t depth, size_t index)
const Operator * StoreContext (size_t depth, size_t index)
const Operator * LoadModule (int32_t cell_index)
const Operator * StoreModule (int32_t cell_index)
const Operator * GetImportMeta ()
const Operator * HasInPrototypeChain ()
const Operator * InstanceOf (const FeedbackSource &feedback)
const Operator * OrdinaryHasInstance ()
const Operator * AsyncFunctionEnter ()
const Operator * AsyncFunctionReject ()
const Operator * AsyncFunctionResolve ()
const Operator * DetachContextCell (int index)
const Operator * ForInEnumerate ()
const Operator * ForInNext (ForInMode mode, const FeedbackSource &feedback)
const Operator * ForInPrepare (ForInMode mode, const FeedbackSource &feedback)
const Operator * LoadMessage ()
const Operator * StoreMessage ()
const Operator * GeneratorStore (int value_count)
const Operator * GeneratorRestoreContinuation ()
const Operator * GeneratorRestoreContextNoCell ()
const Operator * GeneratorRestoreRegister (int index)
const Operator * GeneratorRestoreInputOrDebugPos ()
const Operator * StackCheck (StackCheckKind kind)
const Operator * Debugger ()
const Operator * FulfillPromise ()
const Operator * PerformPromiseThen ()
const Operator * PromiseResolve ()
const Operator * RejectPromise ()
const Operator * ResolvePromise ()
const Operator * CreateFunctionContext (ScopeInfoRef scope_info, int slot_count, ScopeType scope_type)
const Operator * CreateCatchContext (ScopeInfoRef scope_info)
const Operator * CreateWithContext (ScopeInfoRef scope_info)
const Operator * CreateBlockContext (ScopeInfoRef scpope_info)
const Operator * ObjectIsArray ()
const Operator * ParseInt ()
const Operator * RegExpTest ()
const Operator * GetIterator (FeedbackSource const &load_feedback, FeedbackSource const &call_feedback)
Private Member Functions
Zone * zone () const
Private Attributes
const JSOperatorGlobalCache & cache_
Zone *const zone_
Detailed Description
Definition at line 897 of file js-operator.h.
Constructor & Destructor Documentation
JSOperatorBuilder() [1/2]
v8::internal::compiler::JSOperatorBuilder::JSOperatorBuilder (Zone * zone) [explicit]
Definition at line 828 of file js-operator.cc.
    : cache_(*GetJSOperatorGlobalCache()), zone_(zone) {}
JSOperatorBuilder() [2/2]
v8::internal::compiler::JSOperatorBuilder::JSOperatorBuilder (const JSOperatorBuilder &) [delete]
Member Function Documentation
Add()
const Operator* v8::internal::compiler::JSOperatorBuilder::Add (FeedbackSource const & feedback)
AsyncFunctionEnter()
const Operator* v8::internal::compiler::JSOperatorBuilder::AsyncFunctionEnter ()
AsyncFunctionReject()
const Operator* v8::internal::compiler::JSOperatorBuilder::AsyncFunctionReject ()
AsyncFunctionResolve()
const Operator* v8::internal::compiler::JSOperatorBuilder::AsyncFunctionResolve ()
BitwiseAnd()
const Operator* v8::internal::compiler::JSOperatorBuilder::BitwiseAnd (FeedbackSource const & feedback)
BitwiseNot()
const Operator* v8::internal::compiler::JSOperatorBuilder::BitwiseNot (FeedbackSource const & feedback)
BitwiseOr()
const Operator* v8::internal::compiler::JSOperatorBuilder::BitwiseOr (FeedbackSource const & feedback)
BitwiseXor()
const Operator* v8::internal::compiler::JSOperatorBuilder::BitwiseXor (FeedbackSource const & feedback)
Call()
const Operator * v8::internal::compiler::JSOperatorBuilder::Call (size_t arity, CallFrequency const & frequency = CallFrequency(), FeedbackSource const & feedback = FeedbackSource(), ConvertReceiverMode convert_mode = ConvertReceiverMode::kAny, SpeculationMode speculation_mode = SpeculationMode::kDisallowSpeculation, CallFeedbackRelation feedback_relation = CallFeedbackRelation::kUnrelated)
Definition at line 903 of file js-operator.cc.
                                                                              {
  CallParameters parameters(arity, frequency, feedback, convert_mode,
                            speculation_mode, feedback_relation);
  return zone()->New<Operator1<CallParameters>>(// --
      IrOpcode::kJSCall, Operator::kNoProperties, // opcode
      "JSCall", // name
      parameters.arity(), 1, 1, 1, 1, 2, // inputs/outputs
      parameters); // parameter
}
References v8::internal::compiler::CallParameters::arity(), v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
CallForwardVarargs()
const Operator * v8::internal::compiler::JSOperatorBuilder::CallForwardVarargs (size_t arity, uint32_t start_index)
Definition at line 893 of file js-operator.cc.
                                                                            {
  CallForwardVarargsParameters parameters(arity, start_index);
  return zone()->New<Operator1<CallForwardVarargsParameters>>(// --
      IrOpcode::kJSCallForwardVarargs, Operator::kNoProperties, // opcode
      "JSCallForwardVarargs", // name
      parameters.arity(), 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::CallForwardVarargsParameters::arity(), v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments().
CallRuntime() [1/3]
const Operator * v8::internal::compiler::JSOperatorBuilder::CallRuntime (const Runtime::Function * function, size_t arity, Operator::Properties properties = Operator::kNoProperties)
Definition at line 957 of file js-operator.cc.
                                                                           {
  CallRuntimeParameters parameters(f->function_id, arity);
  DCHECK(f->nargs == -1 || f->nargs == static_cast<int>(parameters.arity()));
  return zone()->New<Operator1<CallRuntimeParameters>>(// --
      IrOpcode::kJSCallRuntime, properties, // opcode
      "JSCallRuntime", // name
      parameters.arity(), 1, 1, f->result_size, 1, 2, // inputs/outputs
      parameters); // parameter
}
References v8::internal::compiler::CallRuntimeParameters::arity(), v8::internal::DCHECK(), v8::internal::Runtime::Function::function_id, v8::internal::Runtime::Function::nargs, v8::internal::Zone::New(), v8::internal::Runtime::Function::result_size, and zone().
CallRuntime() [2/3]
const Operator * v8::internal::compiler::JSOperatorBuilder::CallRuntime (Runtime::FunctionId id)
Definition at line 946 of file js-operator.cc.
                                                                   {
  const Runtime::Function* f = Runtime::FunctionForId(id);
  return CallRuntime(f, f->nargs);
}
References v8::internal::Runtime::FunctionForId(), and v8::internal::Runtime::Function::nargs.
Referenced by CallRuntime().
CallRuntime() [3/3]
const Operator * v8::internal::compiler::JSOperatorBuilder::CallRuntime (Runtime::FunctionId id, size_t arity, Operator::Properties properties = Operator::kNoProperties)
Definition at line 951 of file js-operator.cc.
                                                                       {
  const Runtime::Function* f = Runtime::FunctionForId(id);
  return CallRuntime(f, arity, properties);
}
References CallRuntime(), and v8::internal::Runtime::FunctionForId().
CallWithArrayLike()
const Operator * v8::internal::compiler::JSOperatorBuilder::CallWithArrayLike (CallFrequency const & frequency, const FeedbackSource & feedback = FeedbackSource{}, SpeculationMode speculation_mode = SpeculationMode::kDisallowSpeculation, CallFeedbackRelation feedback_relation = CallFeedbackRelation::kTarget)
Definition at line 916 of file js-operator.cc.
                                                                              {
  static constexpr int kTheArrayLikeObject = 1;
  CallParameters parameters(
      JSCallWithArrayLikeNode::ArityForArgc(kTheArrayLikeObject), frequency,
      feedback, ConvertReceiverMode::kAny, speculation_mode, feedback_relation);
  return zone()->New<Operator1<CallParameters>>(// --
      IrOpcode::kJSCallWithArrayLike, Operator::kNoProperties, // opcode
      "JSCallWithArrayLike", // name
      parameters.arity(), 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::CallParameters::arity(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::kAny, v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CallWithSpread()
const Operator * v8::internal::compiler::JSOperatorBuilder::CallWithSpread (uint32_t arity, CallFrequency const & frequency = CallFrequency(), FeedbackSource const & feedback = FeedbackSource(), SpeculationMode speculation_mode = SpeculationMode::kDisallowSpeculation, CallFeedbackRelation feedback_relation = CallFeedbackRelation::kTarget)
Definition at line 930 of file js-operator.cc.
                                            {
  DCHECK_IMPLIES(speculation_mode == SpeculationMode::kAllowSpeculation,
                 feedback.IsValid());
  CallParameters parameters(arity, frequency, feedback,
                            ConvertReceiverMode::kAny, speculation_mode,
                            feedback_relation);
  return zone()->New<Operator1<CallParameters>>(// --
      IrOpcode::kJSCallWithSpread, Operator::kNoProperties, // opcode
      "JSCallWithSpread", // name
      parameters.arity(), 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::CallParameters::arity(), DCHECK_IMPLIES, v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::kAllowSpeculation, v8::internal::kAny, v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CloneObject()
const Operator * v8::internal::compiler::JSOperatorBuilder::CloneObject (FeedbackSource const & feedback, int literal_flags)
Definition at line 1463 of file js-operator.cc.
                                                                  {
  CloneObjectParameters parameters(feedback, literal_flags);
  return zone()->New<Operator1<CloneObjectParameters>>(// --
      IrOpcode::kJSCloneObject, // opcode
      Operator::kNoProperties, // properties
      "JSCloneObject", // name
      2, 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
Construct()
const Operator * v8::internal::compiler::JSOperatorBuilder::Construct (uint32_t arity, CallFrequency const & frequency = CallFrequency(), FeedbackSource const & feedback = FeedbackSource())
Definition at line 999 of file js-operator.cc.
                                                                             {
  ConstructParameters parameters(arity, frequency, feedback);
  return zone()->New<Operator1<ConstructParameters>>(// --
      IrOpcode::kJSConstruct, Operator::kNoProperties, // opcode
      "JSConstruct", // name
      parameters.arity(), 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::ConstructParameters::arity(), v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
ConstructForwardAllArgs()
const Operator * v8::internal::compiler::JSOperatorBuilder::ConstructForwardAllArgs (CallFrequency const & frequency = CallFrequency(), FeedbackSource const & feedback = FeedbackSource())
Definition at line 1035 of file js-operator.cc.
                                                                    {
  // Use 0 as a fake arity. This operator will be reduced away to either a call
  // to Builtin::kConstructForwardAllArgs or an ordinary
  // JSConstruct.
  ConstructParameters parameters(JSConstructForwardAllArgsNode::ArityForArgc(0),
                                 frequency, feedback);
  return zone()->New<Operator1<ConstructParameters>>(// --
      IrOpcode::kJSConstructForwardAllArgs, Operator::kNoProperties, // opcode
      "JSConstructForwardAllArgs", // name
      parameters.arity(), 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::ConstructParameters::arity(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
ConstructForwardVarargs()
const Operator * v8::internal::compiler::JSOperatorBuilder::ConstructForwardVarargs (size_t arity, uint32_t start_index)
Definition at line 987 of file js-operator.cc.
                                        {
  ConstructForwardVarargsParameters parameters(arity, start_index);
  return zone()->New<Operator1<ConstructForwardVarargsParameters>>(// --
      IrOpcode::kJSConstructForwardVarargs, Operator::kNoProperties, // opcode
      "JSConstructForwardVarargs", // name
      parameters.arity(), 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::ConstructForwardVarargsParameters::arity(), v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments().
ConstructWithArrayLike()
const Operator * v8::internal::compiler::JSOperatorBuilder::ConstructWithArrayLike (CallFrequency const & frequency, FeedbackSource const & feedback)
Definition at line 1010 of file js-operator.cc.
                                                                    {
  static constexpr int kTheArrayLikeObject = 1;
  ConstructParameters parameters(
      JSConstructWithArrayLikeNode::ArityForArgc(kTheArrayLikeObject),
      frequency, feedback);
  return zone()->New<Operator1<ConstructParameters>>(// --
      IrOpcode::kJSConstructWithArrayLike, // opcode
      Operator::kNoProperties, // properties
      "JSConstructWithArrayLike", // name
      parameters.arity(), 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::ConstructParameters::arity(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
ConstructWithSpread()
const Operator * v8::internal::compiler::JSOperatorBuilder::ConstructWithSpread (uint32_t arity, CallFrequency const & frequency = CallFrequency(), FeedbackSource const & feedback = FeedbackSource())
Definition at line 1024 of file js-operator.cc.
                                    {
  ConstructParameters parameters(arity, frequency, feedback);
  return zone()->New<Operator1<ConstructParameters>>(// --
      IrOpcode::kJSConstructWithSpread, Operator::kNoProperties, // opcode
      "JSConstructWithSpread", // name
      parameters.arity(), 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::ConstructParameters::arity(), v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
Create()
const Operator* v8::internal::compiler::JSOperatorBuilder::Create ()
CreateArguments()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateArguments (CreateArgumentsType type)
Definition at line 1329 of file js-operator.cc.
                                                                           {
  return zone()->New<Operator1<CreateArgumentsType>>(// --
      IrOpcode::kJSCreateArguments, Operator::kEliminatable, // opcode
      "JSCreateArguments", // name
      1, 1, 0, 1, 1, 0, // counts
      type); // parameter
}
References v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), v8::internal::tracing::type, and zone().
CreateArray()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateArray (size_t arity, OptionalAllocationSiteRef site, const FeedbackSource & feedback)
Definition at line 1337 of file js-operator.cc.
                                                                               {
  // constructor, new_target, arg1, ..., argN
  int const value_input_count = static_cast<int>(arity) + 2;
  CreateArrayParameters parameters(arity, site, feedback);
  return zone()->New<Operator1<CreateArrayParameters>>(// --
      IrOpcode::kJSCreateArray, Operator::kNoProperties, // opcode
      "JSCreateArray", // name
      value_input_count, 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateArrayFromIterable()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateArrayFromIterable ()
Definition at line 1429 of file js-operator.cc.
                                                           {
  return zone()->New<Operator>(// --
      IrOpcode::kJSCreateArrayFromIterable, // opcode
      Operator::kNoProperties, // properties
      "JSCreateArrayFromIterable", // name
      1, 1, 1, 1, 1, 2); // counts
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateArrayIterator()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateArrayIterator (IterationKind kind)
Definition at line 1350 of file js-operator.cc.
                                                                         {
  CreateArrayIteratorParameters parameters(kind);
  return zone()->New<Operator1<CreateArrayIteratorParameters>>(// --
      IrOpcode::kJSCreateArrayIterator, Operator::kEliminatable, // opcode
      "JSCreateArrayIterator", // name
      1, 1, 1, 1, 1, 0, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), and zone().
CreateAsyncFunctionObject()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateAsyncFunctionObject (int register_count)
Definition at line 1359 of file js-operator.cc.
                        {
  return zone()->New<Operator1<int>>(// --
      IrOpcode::kJSCreateAsyncFunctionObject, // opcode
      Operator::kEliminatable, // flags
      "JSCreateAsyncFunctionObject", // name
      3, 1, 1, 1, 1, 0, // counts
      register_count); // parameter
}
References v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), and zone().
CreateBlockContext()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateBlockContext (ScopeInfoRef scpope_info)
Definition at line 1542 of file js-operator.cc.
                                                                             {
  return zone()->New<Operator1<ScopeInfoRef>>(// --
      IrOpcode::kJSCreateBlockContext, Operator::kNoProperties, // opcode
      "JSCreateBlockContext", // name
      0, 1, 1, 1, 1, 2, // counts
      ScopeInfoRef{scope_info}); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateBoundFunction()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateBoundFunction (size_t arity, MapRef map)
Definition at line 1378 of file js-operator.cc.
                                                                   {
  // bound_target_function, bound_this, arg1, ..., argN
  int const value_input_count = static_cast<int>(arity) + 2;
  CreateBoundFunctionParameters parameters(arity, map);
  return zone()->New<Operator1<CreateBoundFunctionParameters>>(// --
      IrOpcode::kJSCreateBoundFunction, Operator::kEliminatable, // opcode
      "JSCreateBoundFunction", // name
      value_input_count, 1, 1, 1, 1, 0, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), and zone().
CreateCatchContext()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateCatchContext (ScopeInfoRef scope_info)
Definition at line 1526 of file js-operator.cc.
                                                                             {
  return zone()->New<Operator1<ScopeInfoRef>>(
      IrOpcode::kJSCreateCatchContext, Operator::kNoProperties, // opcode
      "JSCreateCatchContext", // name
      1, 1, 1, 1, 1, 2, // counts
      ScopeInfoRef{scope_info}); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateClosure()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateClosure (SharedFunctionInfoRef shared_info, CodeRef code, AllocationType allocation = AllocationType::kYoung)
Definition at line 1390 of file js-operator.cc.
                               {
  static constexpr int kFeedbackCell = 1;
  static constexpr int kArity = kFeedbackCell;
  CreateClosureParameters parameters(shared_info, code, allocation);
  return zone()->New<Operator1<CreateClosureParameters>>(// --
      IrOpcode::kJSCreateClosure, Operator::kEliminatable, // opcode
      "JSCreateClosure", // name
      kArity, 1, 1, 1, 1, 0, // counts
      parameters); // parameter
}
References code, v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), and zone().
CreateCollectionIterator()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateCollectionIterator (CollectionKind collection_kind, IterationKind iteration_kind)
Definition at line 1369 of file js-operator.cc.
                                                                  {
  CreateCollectionIteratorParameters parameters(collection_kind,
                                                iteration_kind);
  return zone()->New<Operator1<CreateCollectionIteratorParameters>>(
      IrOpcode::kJSCreateCollectionIterator, Operator::kEliminatable,
      "JSCreateCollectionIterator", 1, 1, 1, 1, 1, 0, parameters);
}
References v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), and zone().
CreateEmptyLiteralArray()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateEmptyLiteralArray (FeedbackSource const & feedback)
Definition at line 1416 of file js-operator.cc.
                                    {
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity = kFeedbackVector;
  FeedbackParameter parameters(feedback);
  return zone()->New<Operator1<FeedbackParameter>>(// --
      IrOpcode::kJSCreateEmptyLiteralArray, // opcode
      Operator::kEliminatable, // properties
      "JSCreateEmptyLiteralArray", // name
      kArity, 1, 1, 1, 1, 0, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), and zone().
CreateEmptyLiteralObject()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateEmptyLiteralObject ()
Definition at line 1494 of file js-operator.cc.
                                                            {
  return zone()->New<Operator>(// --
      IrOpcode::kJSCreateEmptyLiteralObject, // opcode
      Operator::kNoProperties, // properties
      "JSCreateEmptyLiteralObject", // name
      0, 1, 1, 1, 1, 2); // counts
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateFunctionContext()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateFunctionContext (ScopeInfoRef scope_info, int slot_count, ScopeType scope_type)
Definition at line 1515 of file js-operator.cc.
                                                                   {
  CreateFunctionContextParameters parameters(scope_info, slot_count,
                                             scope_type);
  return zone()->New<Operator1<CreateFunctionContextParameters>>(// --
      IrOpcode::kJSCreateFunctionContext, Operator::kNoProperties, // opcode
      "JSCreateFunctionContext", // name
      0, 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateGeneratorObject()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateGeneratorObject ()
Definition at line 1218 of file js-operator.cc.
                                                         {
  return zone()->New<Operator>(// --
      IrOpcode::kJSCreateGeneratorObject, Operator::kEliminatable, // opcode
      "JSCreateGeneratorObject", // name
      2, 1, 1, 1, 1, 0); // counts
}
References v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSIntrinsicLowering::ReduceCreateJSGeneratorObject().
CreateIterResultObject()
const Operator* v8::internal::compiler::JSOperatorBuilder::CreateIterResultObject ()
CreateKeyValueArray()
const Operator* v8::internal::compiler::JSOperatorBuilder::CreateKeyValueArray ()
CreateLiteralArray()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateLiteralArray (ArrayBoilerplateDescriptionRef constant, FeedbackSource const & feedback, int literal_flags, int number_of_elements)
Definition at line 1403 of file js-operator.cc.
                                               {
  CreateLiteralParameters parameters(description, feedback, number_of_elements,
                                     literal_flags);
  return zone()->New<Operator1<CreateLiteralParameters>>(// --
      IrOpcode::kJSCreateLiteralArray, // opcode
      Operator::kNoProperties, // properties
      "JSCreateLiteralArray", // name
      1, 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateLiteralObject()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateLiteralObject (ObjectBoilerplateDescriptionRef constant, FeedbackSource const & feedback, int literal_flags, int number_of_properties)
Definition at line 1437 of file js-operator.cc.
                              {
  CreateLiteralParameters parameters(constant_properties, feedback,
                                     number_of_properties, literal_flags);
  return zone()->New<Operator1<CreateLiteralParameters>>(// --
      IrOpcode::kJSCreateLiteralObject, // opcode
      Operator::kNoProperties, // properties
      "JSCreateLiteralObject", // name
      1, 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateLiteralRegExp()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateLiteralRegExp (StringRef constant_pattern, FeedbackSource const & feedback, int literal_flags)
Definition at line 1502 of file js-operator.cc.
                       {
  CreateLiteralParameters parameters(constant_pattern, feedback, -1,
                                     literal_flags);
  return zone()->New<Operator1<CreateLiteralParameters>>(// --
      IrOpcode::kJSCreateLiteralRegExp, // opcode
      Operator::kNoProperties, // properties
      "JSCreateLiteralRegExp", // name
      1, 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
CreateObject()
const Operator* v8::internal::compiler::JSOperatorBuilder::CreateObject ()
CreatePromise()
const Operator* v8::internal::compiler::JSOperatorBuilder::CreatePromise ()
CreateStringIterator()
const Operator* v8::internal::compiler::JSOperatorBuilder::CreateStringIterator ()
CreateStringWrapper()
const Operator* v8::internal::compiler::JSOperatorBuilder::CreateStringWrapper ()
CreateTypedArray()
const Operator* v8::internal::compiler::JSOperatorBuilder::CreateTypedArray ()
CreateWithContext()
const Operator * v8::internal::compiler::JSOperatorBuilder::CreateWithContext (ScopeInfoRef scope_info)
Definition at line 1534 of file js-operator.cc.
                                                                            {
  return zone()->New<Operator1<ScopeInfoRef>>(
      IrOpcode::kJSCreateWithContext, Operator::kNoProperties, // opcode
      "JSCreateWithContext", // name
      1, 1, 1, 1, 1, 2, // counts
      ScopeInfoRef{scope_info}); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
Debugger()
const Operator* v8::internal::compiler::JSOperatorBuilder::Debugger ()
Decrement()
const Operator* v8::internal::compiler::JSOperatorBuilder::Decrement (FeedbackSource const & feedback)
DefineKeyedOwnProperty()
const Operator * v8::internal::compiler::JSOperatorBuilder::DefineKeyedOwnProperty (LanguageMode language_mode, FeedbackSource const & feedback)
Definition at line 1187 of file js-operator.cc.
                                                                {
  PropertyAccess access(language_mode, feedback);
  return zone()->New<Operator1<PropertyAccess>>(// --
      IrOpcode::kJSDefineKeyedOwnProperty, Operator::kNoProperties, // opcode
      "JSDefineKeyedOwnProperty", // name
      5, 1, 1, 0, 1, 2, // counts
      access); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
DefineKeyedOwnPropertyInLiteral()
const Operator * v8::internal::compiler::JSOperatorBuilder::DefineKeyedOwnPropertyInLiteral (const FeedbackSource & feedback)
Definition at line 859 of file js-operator.cc.
                                    {
  static constexpr int kObject = 1;
  static constexpr int kName = 1;
  static constexpr int kValue = 1;
  static constexpr int kFlags = 1;
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity =
      kObject + kName + kValue + kFlags + kFeedbackVector;
  FeedbackParameter parameters(feedback);
  return zone()->New<Operator1<FeedbackParameter>>(// --
      IrOpcode::kJSDefineKeyedOwnPropertyInLiteral,
      Operator::kNoThrow, // opcode
      "JSDefineKeyedOwnPropertyInLiteral", // name
      kArity, 1, 1, 0, 1, 1, // counts
      parameters); // parameter
}
References v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::compiler::Operator::kNoThrow, v8::internal::kObject, v8::internal::kValue, v8::internal::Zone::New(), and zone().
DefineNamedOwnProperty()
const Operator * v8::internal::compiler::JSOperatorBuilder::DefineNamedOwnProperty (NameRef name, FeedbackSource const & feedback)
Definition at line 1197 of file js-operator.cc.
                                                  {
  static constexpr int kObject = 1;
  static constexpr int kValue = 1;
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity = kObject + kValue + kFeedbackVector;
  DefineNamedOwnPropertyParameters parameters(name, feedback);
  return zone()->New<Operator1<DefineNamedOwnPropertyParameters>>(// --
      IrOpcode::kJSDefineNamedOwnProperty, Operator::kNoProperties, // opcode
      "JSDefineNamedOwnProperty", // name
      kArity, 1, 1, 0, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::kObject, v8::internal::kValue, v8::internal::name, v8::internal::Zone::New(), and zone().
DeleteProperty()
const Operator * v8::internal::compiler::JSOperatorBuilder::DeleteProperty ()
Definition at line 1211 of file js-operator.cc.
                                                  {
  return zone()->New<Operator>(// --
      IrOpcode::kJSDeleteProperty, Operator::kNoProperties, // opcode
      "JSDeleteProperty", // name
      3, 1, 1, 1, 1, 2); // counts
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
DetachContextCell()
const Operator * v8::internal::compiler::JSOperatorBuilder::DetachContextCell (int index)
Definition at line 1132 of file js-operator.cc.
                                                              {
  return zone()->New<Operator1<int>>(// --
      IrOpcode::kJSDetachContextCell, Operator::kNoThrow, // opcode
      "JSDetachContextCell", // name
      2, 1, 1, 0, 1, 0, // counts
      index); // parameter
}
References v8::internal::index, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
Divide()
const Operator* v8::internal::compiler::JSOperatorBuilder::Divide (FeedbackSource const & feedback)
Equal()
const Operator* v8::internal::compiler::JSOperatorBuilder::Equal (FeedbackSource const & feedback)
Exponentiate()
const Operator* v8::internal::compiler::JSOperatorBuilder::Exponentiate (FeedbackSource const & feedback)
FindNonDefaultConstructorOrConstruct()
const Operator* v8::internal::compiler::JSOperatorBuilder::FindNonDefaultConstructorOrConstruct ()
ForInEnumerate()
const Operator* v8::internal::compiler::JSOperatorBuilder::ForInEnumerate ()
ForInNext()
const Operator * v8::internal::compiler::JSOperatorBuilder::ForInNext (ForInMode mode, const FeedbackSource & feedback)
Definition at line 1105 of file js-operator.cc.
                                                                             {
  return zone()->New<Operator1<ForInParameters>>(// --
      IrOpcode::kJSForInNext, Operator::kNoProperties, // opcode
      "JSForInNext", // name
      5, 1, 1, 1, 1, 2, // counts
      ForInParameters{feedback, mode}); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, mode(), v8::internal::Zone::New(), and zone().
ForInPrepare()
const Operator * v8::internal::compiler::JSOperatorBuilder::ForInPrepare (ForInMode mode, const FeedbackSource & feedback)
Definition at line 1114 of file js-operator.cc.
                                                    {
  return zone()->New<Operator1<ForInParameters>>(// --
      IrOpcode::kJSForInPrepare, // opcode
      Operator::kNoWrite | Operator::kNoThrow, // flags
      "JSForInPrepare", // name
      2, 1, 1, 3, 1, 1, // counts
      ForInParameters{feedback, mode}); // parameter
}
References v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::Operator::kNoWrite, mode(), v8::internal::Zone::New(), and zone().
FulfillPromise()
const Operator* v8::internal::compiler::JSOperatorBuilder::FulfillPromise ()
GeneratorRestoreContextNoCell()
const Operator* v8::internal::compiler::JSOperatorBuilder::GeneratorRestoreContextNoCell ()
GeneratorRestoreContinuation()
const Operator* v8::internal::compiler::JSOperatorBuilder::GeneratorRestoreContinuation ()
GeneratorRestoreInputOrDebugPos()
const Operator* v8::internal::compiler::JSOperatorBuilder::GeneratorRestoreInputOrDebugPos ()
GeneratorRestoreRegister()
const Operator * v8::internal::compiler::JSOperatorBuilder::GeneratorRestoreRegister (int index)
Definition at line 1150 of file js-operator.cc.
                                                                     {
  return zone()->New<Operator1<int>>(// --
      IrOpcode::kJSGeneratorRestoreRegister, Operator::kNoThrow, // opcode
      "JSGeneratorRestoreRegister", // name
      1, 1, 1, 1, 1, 0, // counts
      index); // parameter
}
References v8::internal::index, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
GeneratorStore()
const Operator * v8::internal::compiler::JSOperatorBuilder::GeneratorStore (int value_count)
Definition at line 1124 of file js-operator.cc.
                                                                    {
  return zone()->New<Operator1<int>>(// --
      IrOpcode::kJSGeneratorStore, Operator::kNoThrow, // opcode
      "JSGeneratorStore", // name
      3 + register_count, 1, 1, 0, 1, 0, // counts
      register_count); // parameter
}
References v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
GetImportMeta()
const Operator * v8::internal::compiler::JSOperatorBuilder::GetImportMeta ()
Definition at line 1312 of file js-operator.cc.
                                                 {
  return zone()->New<Operator>(// --
      IrOpcode::kJSGetImportMeta, // opcode
      Operator::kNoProperties, // flags
      "JSGetImportMeta", // name
      0, 1, 1, 1, 1, 2); // counts
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
GetIterator()
const Operator * v8::internal::compiler::JSOperatorBuilder::GetIterator (FeedbackSource const & load_feedback, FeedbackSource const & call_feedback)
Definition at line 1086 of file js-operator.cc.
                                                                              {
  GetIteratorParameters access(load_feedback, call_feedback);
  return zone()->New<Operator1<GetIteratorParameters>>(// --
      IrOpcode::kJSGetIterator, Operator::kNoProperties, // opcode
      "JSGetIterator", // name
      2, 1, 1, 1, 1, 2, // counts
      access); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
GetSuperConstructor()
const Operator* v8::internal::compiler::JSOperatorBuilder::GetSuperConstructor ()
GetTemplateObject()
const Operator * v8::internal::compiler::JSOperatorBuilder::GetTemplateObject (TemplateObjectDescriptionRef description, SharedFunctionInfoRef shared, FeedbackSource const & feedback)
Definition at line 1451 of file js-operator.cc.
                                    {
  GetTemplateObjectParameters parameters(description, shared, feedback);
  return zone()->New<Operator1<GetTemplateObjectParameters>>(// --
      IrOpcode::kJSGetTemplateObject, // opcode
      Operator::kEliminatable, // properties
      "JSGetTemplateObject", // name
      1, 1, 1, 1, 1, 0, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kEliminatable, v8::internal::Zone::New(), and zone().
GreaterThan()
const Operator* v8::internal::compiler::JSOperatorBuilder::GreaterThan (FeedbackSource const & feedback)
GreaterThanOrEqual()
const Operator* v8::internal::compiler::JSOperatorBuilder::GreaterThanOrEqual (FeedbackSource const & feedback)
HasContextExtension()
const Operator * v8::internal::compiler::JSOperatorBuilder::HasContextExtension (size_t depth)
Definition at line 1252 of file js-operator.cc.
                                                                   {
  return zone()->New<Operator1<size_t>>(// --
      IrOpcode::kJSHasContextExtension, // opcode
      Operator::kNoWrite | Operator::kNoThrow, // flags
      "JSHasContextExtension", // name
      0, 1, 0, 1, 1, 0, // counts
      depth); // parameter
}
References v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::Operator::kNoWrite, v8::internal::Zone::New(), and zone().
HasInPrototypeChain()
const Operator* v8::internal::compiler::JSOperatorBuilder::HasInPrototypeChain ()
HasProperty()
const Operator * v8::internal::compiler::JSOperatorBuilder::HasProperty (FeedbackSource const & feedback)
Definition at line 1096 of file js-operator.cc.
                                                                             {
  PropertyAccess access(LanguageMode::kSloppy, feedback);
  return zone()->New<Operator1<PropertyAccess>>(// --
      IrOpcode::kJSHasProperty, Operator::kNoProperties, // opcode
      "JSHasProperty", // name
      3, 1, 1, 1, 1, 2, // counts
      access); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::kSloppy, v8::internal::Zone::New(), and zone().
Increment()
const Operator* v8::internal::compiler::JSOperatorBuilder::Increment (FeedbackSource const & feedback)
InstanceOf()
const Operator* v8::internal::compiler::JSOperatorBuilder::InstanceOf (const FeedbackSource & feedback)
LessThan()
const Operator* v8::internal::compiler::JSOperatorBuilder::LessThan (FeedbackSource const & feedback)
LessThanOrEqual()
const Operator* v8::internal::compiler::JSOperatorBuilder::LessThanOrEqual (FeedbackSource const & feedback)
LoadContext()
const Operator * v8::internal::compiler::JSOperatorBuilder::LoadContext (size_t depth, size_t index)
Definition at line 1272 of file js-operator.cc.
                                                                         {
  ContextAccess access(depth, index, false);
  return zone()->New<Operator1<ContextAccess>>(// --
      IrOpcode::kJSLoadContext, // opcode
      Operator::kNoWrite | Operator::kNoThrow, // flags
      "JSLoadContext", // name
      0, 1, 1, 1, 1, 1, // counts
      access); // parameter
}
References v8::internal::index, v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::Operator::kNoWrite, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext().
LoadContextNoCell()
const Operator * v8::internal::compiler::JSOperatorBuilder::LoadContextNoCell (size_t depth, size_t index, bool immutable)
Definition at line 1261 of file js-operator.cc.
                                                                     {
  ContextAccess access(depth, index, immutable);
  return zone()->New<Operator1<ContextAccess>>(// --
      IrOpcode::kJSLoadContextNoCell, // opcode
      Operator::kNoWrite | Operator::kNoThrow, // flags
      "JSLoadContextNoCell", // name
      0, 1, 0, 1, 1, 0, // counts
      access); // parameter
}
References v8::internal::index, v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::Operator::kNoWrite, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell().
LoadGlobal()
const Operator * v8::internal::compiler::JSOperatorBuilder::LoadGlobal (NameRef name, const FeedbackSource & feedback, TypeofMode typeof_mode = TypeofMode::kNotInside)
Definition at line 1225 of file js-operator.cc.
                                                                      {
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity = kFeedbackVector;
  LoadGlobalParameters parameters(name, feedback, typeof_mode);
  return zone()->New<Operator1<LoadGlobalParameters>>(// --
      IrOpcode::kJSLoadGlobal, Operator::kNoProperties, // opcode
      "JSLoadGlobal", // name
      kArity, 1, 1, 1, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::name, v8::internal::Zone::New(), and zone().
LoadMessage()
const Operator* v8::internal::compiler::JSOperatorBuilder::LoadMessage ()
LoadModule()
const Operator * v8::internal::compiler::JSOperatorBuilder::LoadModule (int32_t cell_index)
Definition at line 1303 of file js-operator.cc.
                                                                {
  return zone()->New<Operator1<int32_t>>(// --
      IrOpcode::kJSLoadModule, // opcode
      Operator::kNoWrite | Operator::kNoThrow, // flags
      "JSLoadModule", // name
      1, 1, 1, 1, 1, 0, // counts
      cell_index); // parameter
}
References v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::Operator::kNoWrite, v8::internal::Zone::New(), and zone().
LoadNamed()
const Operator * v8::internal::compiler::JSOperatorBuilder::LoadNamed (NameRef name, FeedbackSource const & feedback)
Definition at line 1049 of file js-operator.cc.
                                                                             {
  static constexpr int kObject = 1;
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity = kObject + kFeedbackVector;
  NamedAccess access(LanguageMode::kSloppy, name, feedback);
  return zone()->New<Operator1<NamedAccess>>(// --
      IrOpcode::kJSLoadNamed, Operator::kNoProperties, // opcode
      "JSLoadNamed", // name
      kArity, 1, 1, 1, 1, 2, // counts
      access); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::kObject, v8::internal::kSloppy, v8::internal::name, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
LoadNamedFromSuper()
const Operator * v8::internal::compiler::JSOperatorBuilder::LoadNamedFromSuper (NameRef name, FeedbackSource const & feedback)
Definition at line 1062 of file js-operator.cc.
                                                  {
  static constexpr int kReceiver = 1;
  static constexpr int kHomeObject = 1;
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity = kReceiver + kHomeObject + kFeedbackVector;
  NamedAccess access(LanguageMode::kSloppy, name, feedback);
  return zone()->New<Operator1<NamedAccess>>(// --
      IrOpcode::kJSLoadNamedFromSuper, Operator::kNoProperties, // opcode
      "JSLoadNamedFromSuper", // name
      kArity, 1, 1, 1, 1, 2, // counts
      access); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::kReceiver, v8::internal::kSloppy, v8::internal::name, v8::internal::Zone::New(), and zone().
LoadProperty()
const Operator * v8::internal::compiler::JSOperatorBuilder::LoadProperty (FeedbackSource const & feedback)
Definition at line 1076 of file js-operator.cc.
                                    {
  PropertyAccess access(LanguageMode::kSloppy, feedback);
  return zone()->New<Operator1<PropertyAccess>>(// --
      IrOpcode::kJSLoadProperty, Operator::kNoProperties, // opcode
      "JSLoadProperty", // name
      3, 1, 1, 1, 1, 2, // counts
      access); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::kSloppy, v8::internal::Zone::New(), and zone().
Modulus()
const Operator* v8::internal::compiler::JSOperatorBuilder::Modulus (FeedbackSource const & feedback)
Multiply()
const Operator* v8::internal::compiler::JSOperatorBuilder::Multiply (FeedbackSource const & feedback)
Negate()
const Operator* v8::internal::compiler::JSOperatorBuilder::Negate (FeedbackSource const & feedback)
ObjectIsArray()
const Operator* v8::internal::compiler::JSOperatorBuilder::ObjectIsArray ()
operator=()
JSOperatorBuilder& v8::internal::compiler::JSOperatorBuilder::operator= (const JSOperatorBuilder &) [delete]
OrdinaryHasInstance()
const Operator* v8::internal::compiler::JSOperatorBuilder::OrdinaryHasInstance ()
ParseInt()
const Operator* v8::internal::compiler::JSOperatorBuilder::ParseInt ()
PerformPromiseThen()
const Operator* v8::internal::compiler::JSOperatorBuilder::PerformPromiseThen ()
PromiseResolve()
const Operator* v8::internal::compiler::JSOperatorBuilder::PromiseResolve ()
RegExpTest()
const Operator* v8::internal::compiler::JSOperatorBuilder::RegExpTest ()
RejectPromise()
const Operator* v8::internal::compiler::JSOperatorBuilder::RejectPromise ()
ResolvePromise()
const Operator* v8::internal::compiler::JSOperatorBuilder::ResolvePromise ()
SetKeyedProperty()
const Operator * v8::internal::compiler::JSOperatorBuilder::SetKeyedProperty (LanguageMode language_mode, FeedbackSource const & feedback)
Definition at line 1177 of file js-operator.cc.
                                                                {
  PropertyAccess access(language_mode, feedback);
  return zone()->New<Operator1<PropertyAccess>>(// --
      IrOpcode::kJSSetKeyedProperty, Operator::kNoProperties, // opcode
      "JSSetKeyedProperty", // name
      4, 1, 1, 0, 1, 2, // counts
      access); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
SetNamedProperty()
const Operator * v8::internal::compiler::JSOperatorBuilder::SetNamedProperty (LanguageMode language_mode, NameRef name, FeedbackSource const & feedback)
Definition at line 1163 of file js-operator.cc.
                                                                              {
  static constexpr int kObject = 1;
  static constexpr int kValue = 1;
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity = kObject + kValue + kFeedbackVector;
  NamedAccess access(language_mode, name, feedback);
  return zone()->New<Operator1<NamedAccess>>(// --
      IrOpcode::kJSSetNamedProperty, Operator::kNoProperties, // opcode
      "JSSetNamedProperty", // name
      kArity, 1, 1, 0, 1, 2, // counts
      access); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::kObject, v8::internal::kValue, v8::internal::name, v8::internal::Zone::New(), and zone().
ShiftLeft()
const Operator* v8::internal::compiler::JSOperatorBuilder::ShiftLeft (FeedbackSource const & feedback)
ShiftRight()
const Operator* v8::internal::compiler::JSOperatorBuilder::ShiftRight (FeedbackSource const & feedback)
ShiftRightLogical()
const Operator* v8::internal::compiler::JSOperatorBuilder::ShiftRightLogical (FeedbackSource const & feedback)
StackCheck()
const Operator * v8::internal::compiler::JSOperatorBuilder::StackCheck (StackCheckKind kind)
Definition at line 1474 of file js-operator.cc.
                                                                 {
  Operator::Properties properties;
  switch (kind) {
    case StackCheckKind::kJSFunctionEntry:
    case StackCheckKind::kCodeStubAssembler:
    case StackCheckKind::kWasm:
      properties = Operator::kNoProperties;
      break;
    case StackCheckKind::kJSIterationBody:
      properties = Operator::kNoWrite;
      break;
  }
  return zone()->New<Operator1<StackCheckKind>>(// --
      IrOpcode::kJSStackCheck, // opcode
      properties, // properties
      "JSStackCheck", // name
      0, 1, 1, 0, 1, 2, // counts
      kind); // parameter
}
References v8::internal::compiler::kCodeStubAssembler, v8::internal::compiler::kJSFunctionEntry, v8::internal::compiler::kJSIterationBody, v8::internal::compiler::Operator::kNoProperties, v8::internal::compiler::Operator::kNoWrite, v8::internal::compiler::kWasm, v8::internal::Zone::New(), and zone().
StoreContext()
const Operator * v8::internal::compiler::JSOperatorBuilder::StoreContext (size_t depth, size_t index)
Definition at line 1293 of file js-operator.cc.
                                                                          {
  ContextAccess access(depth, index, false);
  return zone()->New<Operator1<ContextAccess>>(// --
      IrOpcode::kJSStoreContext, // opcode
      Operator::kNoRead | Operator::kNoThrow, // flags
      "JSStoreContext", // name
      1, 1, 1, 0, 1, 1, // counts
      access); // parameter
}
References v8::internal::index, v8::internal::compiler::Operator::kNoRead, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext().
StoreContextNoCell()
const Operator * v8::internal::compiler::JSOperatorBuilder::StoreContextNoCell (size_t depth, size_t index)
Definition at line 1282 of file js-operator.cc.
                                                                    {
  ContextAccess access(depth, index, false);
  return zone()->New<Operator1<ContextAccess>>(// --
      IrOpcode::kJSStoreContextNoCell, // opcode
      Operator::kNoRead | Operator::kNoThrow, // flags
      "JSStoreContextNoCell", // name
      1, 1, 1, 0, 1, 0, // counts
      access); // parameter
}
References v8::internal::index, v8::internal::compiler::Operator::kNoRead, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell().
StoreGlobal()
const Operator * v8::internal::compiler::JSOperatorBuilder::StoreGlobal (LanguageMode language_mode, NameRef name, const FeedbackSource & feedback)
Definition at line 1238 of file js-operator.cc.
                                                                               {
  static constexpr int kValue = 1;
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity = kValue + kFeedbackVector;
  StoreGlobalParameters parameters(language_mode, feedback, name);
  return zone()->New<Operator1<StoreGlobalParameters>>(// --
      IrOpcode::kJSStoreGlobal, Operator::kNoProperties, // opcode
      "JSStoreGlobal", // name
      kArity, 1, 1, 0, 1, 2, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::kValue, v8::internal::name, v8::internal::Zone::New(), and zone().
StoreInArrayLiteral()
const Operator * v8::internal::compiler::JSOperatorBuilder::StoreInArrayLiteral (const FeedbackSource & feedback)
Definition at line 877 of file js-operator.cc.
                                    {
  static constexpr int kArray = 1;
  static constexpr int kIndex = 1;
  static constexpr int kValue = 1;
  static constexpr int kFeedbackVector = 1;
  static constexpr int kArity = kArray + kIndex + kValue + kFeedbackVector;
  FeedbackParameter parameters(feedback);
  return zone()->New<Operator1<FeedbackParameter>>(// --
      IrOpcode::kJSStoreInArrayLiteral,
      Operator::kNoThrow, // opcode
      "JSStoreInArrayLiteral", // name
      kArity, 1, 1, 0, 1, 1, // counts
      parameters); // parameter
}
References v8::internal::compiler::Operator::kNoThrow, v8::internal::kValue, v8::internal::Zone::New(), and zone().
StoreMessage()
const Operator* v8::internal::compiler::JSOperatorBuilder::StoreMessage ()
StoreModule()
const Operator * v8::internal::compiler::JSOperatorBuilder::StoreModule (int32_t cell_index)
Definition at line 1320 of file js-operator.cc.
                                                                 {
  return zone()->New<Operator1<int32_t>>(// --
      IrOpcode::kJSStoreModule, // opcode
      Operator::kNoRead | Operator::kNoThrow, // flags
      "JSStoreModule", // name
      2, 1, 1, 0, 1, 0, // counts
      cell_index); // parameter
}
References v8::internal::compiler::Operator::kNoRead, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
StrictEqual()
const Operator* v8::internal::compiler::JSOperatorBuilder::StrictEqual (FeedbackSource const & feedback)
Subtract()
const Operator* v8::internal::compiler::JSOperatorBuilder::Subtract (FeedbackSource const & feedback)
ToBigInt()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToBigInt ()
ToBigIntConvertNumber()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToBigIntConvertNumber ()
ToLength()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToLength ()
ToName()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToName ()
ToNumber()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToNumber ()
ToNumberConvertBigInt()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToNumberConvertBigInt ()
ToNumeric()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToNumeric ()
ToObject()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToObject ()
ToString()
const Operator* v8::internal::compiler::JSOperatorBuilder::ToString ()
zone()
Zone* v8::internal::compiler::JSOperatorBuilder::zone () const [inline], [private]
Definition at line 1120 of file js-operator.h.
{ return zone_; }
Referenced by Call(), CallForwardVarargs(), CallRuntime(), CallWithArrayLike(), CallWithSpread(), CloneObject(), Construct(), ConstructForwardAllArgs(), ConstructForwardVarargs(), ConstructWithArrayLike(), ConstructWithSpread(), CreateArguments(), CreateArray(), CreateArrayFromIterable(), CreateArrayIterator(), CreateAsyncFunctionObject(), CreateBlockContext(), CreateBoundFunction(), CreateCatchContext(), CreateClosure(), CreateCollectionIterator(), CreateEmptyLiteralArray(), CreateEmptyLiteralObject(), CreateFunctionContext(), CreateGeneratorObject(), CreateLiteralArray(), CreateLiteralObject(), CreateLiteralRegExp(), CreateWithContext(), DefineKeyedOwnProperty(), DefineKeyedOwnPropertyInLiteral(), DefineNamedOwnProperty(), DeleteProperty(), DetachContextCell(), ForInNext(), ForInPrepare(), GeneratorRestoreRegister(), GeneratorStore(), GetImportMeta(), GetIterator(), GetTemplateObject(), HasContextExtension(), HasProperty(), LoadContext(), LoadContextNoCell(), LoadGlobal(), LoadModule(), LoadNamed(), LoadNamedFromSuper(), LoadProperty(), SetKeyedProperty(), SetNamedProperty(), StackCheck(), StoreContext(), StoreContextNoCell(), StoreGlobal(), StoreInArrayLiteral(), and StoreModule().
Member Data Documentation
cache_
const JSOperatorGlobalCache& v8::internal::compiler::JSOperatorBuilder::cache_ [private]
Definition at line 1122 of file js-operator.h.
zone_
Zone* const v8::internal::compiler::JSOperatorBuilder::zone_ [private]
Definition at line 1123 of file js-operator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-operator.h
/mnt/V8SourceCode/src/compiler/js-operator.cc