v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter Class Reference
Public Member Functions
void Rewrite (int from, int to)
void ReplaceSequenceWithFailure (int from, int to)
Static Public Member Functions
static void MaybeRewrite (ZoneList< RegExpTree * > *terms, Zone *zone)
Private Member Functions
AssertionSequenceRewriter (ZoneList< RegExpTree * > *terms, Zone *zone)
Private Attributes
Zone * zone_
ZoneList< RegExpTree * > * terms_
Detailed Description
Definition at line 1295 of file regexp-compiler-tonode.cc.
Constructor & Destructor Documentation
AssertionSequenceRewriter()
v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::AssertionSequenceRewriter (ZoneList< RegExpTree * > * terms, Zone * zone) [inline], [private]
Definition at line 1370 of file regexp-compiler-tonode.cc.
      : zone_(zone), terms_(terms) {}
Member Function Documentation
MaybeRewrite()
static void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::MaybeRewrite (ZoneList< RegExpTree * > * terms, Zone * zone) [inline], [static]
Definition at line 1299 of file regexp-compiler-tonode.cc.
                                                                     {
    AssertionSequenceRewriter rewriter(terms, zone);
    static constexpr int kNoIndex = -1;
    int from = kNoIndex;
    for (int i = 0; i < terms->length(); i++) {
      RegExpTree* t = terms->at(i);
      if (from == kNoIndex && t->IsAssertion()) {
        from = i; // Start a sequence.
      } else if (from != kNoIndex && !t->IsAssertion()) {
        // Terminate and process the sequence.
        if (i - from > 1) rewriter.Rewrite(from, i);
        from = kNoIndex;
      }
    }
    if (from != kNoIndex && terms->length() - from > 1) {
      rewriter.Rewrite(from, terms->length());
    }
  }
References v8::internal::ZoneList< T >::at(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ZoneList< T >::length(), and Rewrite().
ReplaceSequenceWithFailure()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::ReplaceSequenceWithFailure (int from, int to) [inline]
Definition at line 1355 of file regexp-compiler-tonode.cc.
                                                    {
    // Replace the entire sequence with a single node that always fails.
    // TODO(jgruber): Consider adding an explicit Fail kind. Until then, the
    // negated '*' (everything) range serves the purpose.
    ZoneList<CharacterRange>* ranges =
        zone_->New<ZoneList<CharacterRange>>(0, zone_);
    RegExpClassRanges* cc = zone_->New<RegExpClassRanges>(zone_, ranges);
    terms_->Set(from, cc);
    // Zero out the rest.
    RegExpEmpty* empty = zone_->New<RegExpEmpty>();
    for (int i = from + 1; i < to; i++) terms_->Set(i, empty);
  }
References v8::internal::cc.
Rewrite()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::Rewrite (int from, int to) [inline]
Definition at line 1326 of file regexp-compiler-tonode.cc.
                                 {
    DCHECK_GT(to, from + 1);
    // Bitfield of all seen assertions.
    uint32_t seen_assertions = 0;
    static_assert(static_cast<int>(RegExpAssertion::Type::LAST_ASSERTION_TYPE) <
                  kUInt32Size * kBitsPerByte);
    for (int i = from; i < to; i++) {
      RegExpAssertion* t = terms_->at(i)->AsAssertion();
      const uint32_t bit = 1 << static_cast<int>(t->assertion_type());
      if (seen_assertions & bit) {
        // Fold duplicates.
        terms_->Set(i, zone_->New<RegExpEmpty>());
      }
      seen_assertions |= bit;
    }
    // Collapse failures.
    const uint32_t always_fails_mask =
        1 << static_cast<int>(RegExpAssertion::Type::BOUNDARY) |
        1 << static_cast<int>(RegExpAssertion::Type::NON_BOUNDARY);
    if ((seen_assertions & always_fails_mask) == always_fails_mask) {
      ReplaceSequenceWithFailure(from, to);
    }
  }
References v8::internal::RegExpAssertion::assertion_type(), v8::internal::RegExpAssertion::BOUNDARY, DCHECK_GT, v8::internal::kBitsPerByte, v8::internal::kUInt32Size, v8::internal::RegExpAssertion::LAST_ASSERTION_TYPE, and v8::internal::RegExpAssertion::NON_BOUNDARY.
Referenced by MaybeRewrite().
Member Data Documentation
terms_
ZoneList<RegExpTree*>* v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::terms_ [private]
Definition at line 1374 of file regexp-compiler-tonode.cc.
zone_
Zone* v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::zone_ [private]
Definition at line 1373 of file regexp-compiler-tonode.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc