v8::internal::compiler::PromiseBuiltinReducerAssembler Class Reference
Public Member Functions
PromiseBuiltinReducerAssembler (JSCallReducer *reducer, Node *node)
TNode< Object > ReducePromiseConstructor (NativeContextRef native_context)
int ConstructArity () const
TNode< Object > TargetInput () const
TNode< Object > NewTargetInput () const
Private Member Functions
TNode< JSPromise > CreatePromise (TNode< Context > context)
TNode< Context > CreateFunctionContext (NativeContextRef native_context, TNode< Context > outer_context, int slot_count)
void StoreContextNoCellSlot (TNode< Context > context, size_t slot_index, TNode< Object > value)
TNode< JSFunction > CreateClosureFromBuiltinSharedFunctionInfo (SharedFunctionInfoRef shared, TNode< Context > context)
void CallPromiseExecutor (TNode< Object > executor, TNode< JSFunction > resolve, TNode< JSFunction > reject, FrameState frame_state)
void CallPromiseReject (TNode< JSFunction > reject, TNode< Object > exception, FrameState frame_state)
Additional Inherited Members
Detailed Description
Definition at line 548 of file js-call-reducer.cc.
Constructor & Destructor Documentation
PromiseBuiltinReducerAssembler()
v8::internal::compiler::PromiseBuiltinReducerAssembler::PromiseBuiltinReducerAssembler (JSCallReducer * reducer, Node * node) [inline]
Definition at line 550 of file js-call-reducer.cc.
      : JSCallReducerAssembler(reducer, node) {
    DCHECK_EQ(IrOpcode::kJSConstruct, node->opcode());
  }
References DCHECK_EQ, and v8::internal::compiler::Node::opcode().
Member Function Documentation
CallPromiseExecutor()
void v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor (TNode< Object > executor, TNode< JSFunction > resolve, TNode< JSFunction > reject, FrameState frame_state) [inline], [private]
Definition at line 603 of file js-call-reducer.cc.
                                                                             {
    JSConstructNode n(node_ptr());
    const ConstructParameters& p = n.Parameters();
    FeedbackSource no_feedback_source{};
    Node* no_feedback = UndefinedConstant();
    MayThrow(_ {
      return AddNode<Object>(graph()->NewNode(
          javascript()->Call(JSCallNode::ArityForArgc(2), p.frequency(),
                             no_feedback_source,
                             ConvertReceiverMode::kNullOrUndefined),
          executor, UndefinedConstant(), resolve, reject, no_feedback,
          n.context(), frame_state, effect(), control()));
    });
  }
References _, v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::ConstructParameters::frequency(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::javascript(), v8::internal::kNullOrUndefined, v8::internal::compiler::JSGraphAssembler::MayThrow(), v8::internal::compiler::JSCallReducerAssembler::node_ptr(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReducePromiseConstructor().
CallPromiseReject()
void v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject (TNode< JSFunction > reject, TNode< Object > exception, FrameState frame_state) [inline], [private]
Definition at line 619 of file js-call-reducer.cc.
                                                 {
    JSConstructNode n(node_ptr());
    const ConstructParameters& p = n.Parameters();
    FeedbackSource no_feedback_source{};
    Node* no_feedback = UndefinedConstant();
    MayThrow(_ {
      return AddNode<Object>(graph()->NewNode(
          javascript()->Call(JSCallNode::ArityForArgc(1), p.frequency(),
                             no_feedback_source,
                             ConvertReceiverMode::kNullOrUndefined),
          reject, UndefinedConstant(), exception, no_feedback, n.context(),
          frame_state, effect(), control()));
    });
  }
References _, v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::ConstructParameters::frequency(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::javascript(), v8::internal::kNullOrUndefined, v8::internal::compiler::JSGraphAssembler::MayThrow(), v8::internal::compiler::JSCallReducerAssembler::node_ptr(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReducePromiseConstructor().
ConstructArity()
int v8::internal::compiler::PromiseBuiltinReducerAssembler::ConstructArity () const [inline]
Definition at line 557 of file js-call-reducer.cc.
                             {
    return JSConstructNode{node_ptr()}.ArgumentCount();
  }
References v8::internal::compiler::JSCallReducerAssembler::node_ptr().
Referenced by ReducePromiseConstructor(), and v8::internal::compiler::JSCallReducer::ReducePromiseConstructor().
CreateClosureFromBuiltinSharedFunctionInfo()
TNode<JSFunction> v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo (SharedFunctionInfoRef shared, TNode< Context > context) [inline], [private]
Definition at line 590 of file js-call-reducer.cc.
                                                            {
    DCHECK(shared.HasBuiltinId());
    Handle<FeedbackCell> feedback_cell =
        isolate()->factory()->many_closures_cell();
    Callable const callable =
        Builtins::CallableFor(isolate(), shared.builtin_id());
    CodeRef code = MakeRef(broker(), *callable.code());
    return AddNode<JSFunction>(graph()->NewNode(
        javascript()->CreateClosure(shared, code), HeapConstant(feedback_cell),
        context, effect(), control()));
  }
References v8::internal::compiler::JSGraphAssembler::broker(), v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), code, v8::internal::compiler::GraphAssembler::control(), v8::internal::DCHECK(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::Isolate::factory(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::HeapConstant(), v8::internal::compiler::JSGraphAssembler::isolate(), v8::internal::compiler::JSGraphAssembler::javascript(), and v8::internal::compiler::MakeRef().
Referenced by ReducePromiseConstructor().
CreateFunctionContext()
TNode<Context> v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateFunctionContext (NativeContextRef native_context, TNode< Context > outer_context, int slot_count) [inline], [private]
Definition at line 575 of file js-call-reducer.cc.
                                                       {
    return AddNode<Context>(graph()->NewNode(
        javascript()->CreateFunctionContext(
            native_context.scope_info(broker()),
            slot_count - Context::MIN_CONTEXT_SLOTS, FUNCTION_SCOPE),
        outer_context, effect(), control()));
  }
References v8::internal::compiler::JSGraphAssembler::broker(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::FUNCTION_SCOPE, v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::javascript(), v8::internal::Context::MIN_CONTEXT_SLOTS, and v8::internal::native_context.
Referenced by ReducePromiseConstructor().
CreatePromise()
TNode<JSPromise> v8::internal::compiler::PromiseBuiltinReducerAssembler::CreatePromise (TNode< Context > context) [inline], [private]
Definition at line 570 of file js-call-reducer.cc.
                                                         {
    return AddNode<JSPromise>(
        graph()->NewNode(javascript()->CreatePromise(), context, effect()));
  }
References v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and v8::internal::compiler::JSGraphAssembler::javascript().
Referenced by ReducePromiseConstructor().
NewTargetInput()
TNode<Object> v8::internal::compiler::PromiseBuiltinReducerAssembler::NewTargetInput () const [inline]
Definition at line 565 of file js-call-reducer.cc.
                                       {
    return JSConstructNode{node_ptr()}.new_target();
  }
References v8::internal::compiler::JSCallReducerAssembler::node_ptr().
Referenced by ReducePromiseConstructor(), and v8::internal::compiler::JSCallReducer::ReducePromiseConstructor().
ReducePromiseConstructor()
TNode< Object > v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor (NativeContextRef native_context)
Definition at line 2505 of file js-call-reducer.cc.
                                     {
  DCHECK_GE(ConstructArity(), 1);
  JSConstructNode n(node_ptr());
  FrameState outer_frame_state = FrameStateInput();
  TNode<Context> context = ContextInput();
  TNode<Object> target = TargetInput();
  TNode<Object> executor = n.Argument(0);
  DCHECK_EQ(target, NewTargetInput());
  SharedFunctionInfoRef promise_shared =
      native_context.promise_function(broker()).shared(broker());
  PromiseCtorFrameStateParams frame_state_params{jsgraph(), promise_shared,
                                                 node_ptr(), context,
                                                 target, outer_frame_state};
  // Insert a construct stub frame into the chain of frame states. This will
  // reconstruct the proper frame when deoptimizing within the constructor.
  // For the frame state, we only provide the executor parameter, even if more
  // arguments were passed. This is not observable from JS.
  FrameState constructor_frame_state =
      PromiseConstructorFrameState(frame_state_params, common(), graph());
  IfNot(ObjectIsCallable(executor))
      .Then((_ {
        JSCallRuntime2(
            Runtime::kThrowTypeError,
            SmiConstant(
                Smi::FromEnum(MessageTemplate::kResolverNotAFunction).value()),
            executor, context,
            PromiseConstructorLazyFrameState(frame_state_params,
                                             constructor_frame_state));
      }))
      .ExpectTrue();
  TNode<JSPromise> promise = CreatePromise(context);
  // 8. CreatePromiseResolvingFunctions
  // Allocate a promise context for the closures below.
  TNode<Context> promise_context = CreateFunctionContext(
      native_context, context, PromiseBuiltins::kPromiseContextLength);
  StoreContextNoCellSlot(promise_context, PromiseBuiltins::kPromiseSlot,
                         promise);
  StoreContextNoCellSlot(promise_context, PromiseBuiltins::kAlreadyResolvedSlot,
                         FalseConstant());
  StoreContextNoCellSlot(promise_context, PromiseBuiltins::kDebugEventSlot,
                         TrueConstant());
  // Allocate closures for the resolve and reject cases.
  SharedFunctionInfoRef resolve_sfi =
      MakeRef(broker(), broker()
                            ->isolate()
                            ->factory()
                            ->promise_capability_default_resolve_shared_fun());
  TNode<JSFunction> resolve =
      CreateClosureFromBuiltinSharedFunctionInfo(resolve_sfi, promise_context);
  SharedFunctionInfoRef reject_sfi =
      MakeRef(broker(), broker()
                            ->isolate()
                            ->factory()
                            ->promise_capability_default_reject_shared_fun());
  TNode<JSFunction> reject =
      CreateClosureFromBuiltinSharedFunctionInfo(reject_sfi, promise_context);
  FrameState lazy_with_catch_frame_state =
      PromiseConstructorLazyWithCatchFrameState(
          frame_state_params, constructor_frame_state, promise, reject);
  // 9. Call executor with both resolving functions.
  // 10a. Call reject if the call to executor threw.
  Try(_ {
    CallPromiseExecutor(executor, resolve, reject, lazy_with_catch_frame_state);
  }).Catch([&](TNode<Object> exception) {
    // Clear pending message since the exception is not going to be rethrown.
    ClearPendingMessage();
    CallPromiseReject(reject, exception, lazy_with_catch_frame_state);
  });
  return promise;
}
References _, v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSGraphAssembler::broker(), CallPromiseExecutor(), CallPromiseReject(), v8::internal::compiler::JSGraphAssembler::ClearPendingMessage(), v8::internal::compiler::GraphAssembler::common(), ConstructArity(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), CreateClosureFromBuiltinSharedFunctionInfo(), CreateFunctionContext(), CreatePromise(), DCHECK_EQ, DCHECK_GE, v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), v8::internal::Smi::FromEnum(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::IfNot(), v8::internal::compiler::JSGraphAssembler::isolate(), v8::internal::compiler::JSGraphAssembler::JSCallRuntime2(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::PromiseBuiltins::kAlreadyResolvedSlot, v8::internal::PromiseBuiltins::kDebugEventSlot, v8::internal::PromiseBuiltins::kPromiseContextLength, v8::internal::PromiseBuiltins::kPromiseSlot, v8::internal::compiler::MakeRef(), v8::internal::native_context, NewTargetInput(), v8::internal::compiler::JSCallReducerAssembler::node_ptr(), v8::internal::compiler::JSGraphAssembler::ObjectIsCallable(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseConstructorFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseConstructorLazyFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseConstructorLazyWithCatchFrameState(), v8::internal::compiler::JSGraphAssembler::SmiConstant(), StoreContextNoCellSlot(), TargetInput(), v8::internal::compiler::JSCallReducerAssembler::Try(), and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducer::ReducePromiseConstructor().
StoreContextNoCellSlot()
void v8::internal::compiler::PromiseBuiltinReducerAssembler::StoreContextNoCellSlot (TNode< Context > context, size_t slot_index, TNode< Object > value) [inline], [private]
Definition at line 585 of file js-call-reducer.cc.
                                                   {
    StoreField(AccessBuilder::ForContextSlot(slot_index), context, value);
  }
References v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::JSGraphAssembler::StoreField(), and v8::internal::value.
Referenced by ReducePromiseConstructor().
TargetInput()
TNode<Object> v8::internal::compiler::PromiseBuiltinReducerAssembler::TargetInput () const [inline]
Definition at line 561 of file js-call-reducer.cc.
                                    {
    return JSConstructNode{node_ptr()}.target();
  }
References v8::internal::compiler::JSCallReducerAssembler::node_ptr().
Referenced by ReducePromiseConstructor(), and v8::internal::compiler::JSCallReducer::ReducePromiseConstructor().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc