v8::internal::compiler::turboshaft::PackNode Class Reference
#include <wasm-revec-reducer.h>
Public Types
enum NodeType {
kDefault
, kForcePackNode
, kShufflePackNode
, kBundlePackNode
,
kIntersectPackNode
 }
Public Member Functions
PackNode (Zone *zone, const NodeGroup &node_group, NodeType node_type=kDefault)
const NodeGroup & nodes () const
bool IsSame (const NodeGroup &node_group) const
bool IsSame (const PackNode &other) const
V< Simd256 > RevectorizedNode () const
void SetRevectorizedNode (V< Simd256 > node)
bool IsDefaultPackNode () const
bool IsForcePackNode () const
bool IsShufflePackNode () const
bool IsBundlePackNode () const
bool is_force_packing () const
ForcePackNode * AsForcePackNode ()
ShufflePackNode * AsShufflePackNode ()
BundlePackNode * AsBundlePackNode ()
PackNode * GetOperand (int index) const
void SetOperand (int index, PackNode *pnode)
ZoneVector< PackNode * >::size_type GetOperandsSize () const
void Print (Graph *graph) const
Private Attributes
NodeGroup nodes_
V< Simd256 > revectorized_node_
ZoneVector< PackNode * > operands_
NodeType node_type_
Friends
class ForcePackNode
Detailed Description
Definition at line 249 of file wasm-revec-reducer.h.
Member Enumeration Documentation
NodeType
enum v8::internal::compiler::turboshaft::PackNode::NodeType
Enumerator
kDefault
kForcePackNode
kShufflePackNode
kBundlePackNode
kIntersectPackNode
Definition at line 251 of file wasm-revec-reducer.h.
                {
    kDefault, // Nodes are naturally packed without special attributes.
    kForcePackNode, // Nodes do not satisfy some packing rule, but can be
                     // forcely coalesced with a Pack128To256 operation. E.g.
                     // inconsecutive loads. In x64, we can use the vinsertf128
                     // instruction to forcely coalescing two 128-bit values.
    kShufflePackNode, // Nodes are Simd128Shuffle operations with specific
                       // info.
    kBundlePackNode, // Nodes representing a i8x16/i16x8 to f32x4 conversion.
    kIntersectPackNode, // One or more nodes already packed by an existing
                         // PackNode.
  };
Constructor & Destructor Documentation
PackNode()
v8::internal::compiler::turboshaft::PackNode::PackNode (Zone * zone, const NodeGroup & node_group, NodeType node_type = kDefault) [inline], [explicit]
Definition at line 264 of file wasm-revec-reducer.h.
      : nodes_(node_group),
        revectorized_node_(),
        operands_(zone),
        node_type_(node_type) {}
Member Function Documentation
AsBundlePackNode()
BundlePackNode* v8::internal::compiler::turboshaft::PackNode::AsBundlePackNode () [inline]
Definition at line 295 of file wasm-revec-reducer.h.
                                     {
    DCHECK(IsBundlePackNode());
    return reinterpret_cast<BundlePackNode*>(this);
  }
References v8::internal::DCHECK(), and IsBundlePackNode().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane().
AsForcePackNode()
ForcePackNode* v8::internal::compiler::turboshaft::PackNode::AsForcePackNode () [inline]
Definition at line 287 of file wasm-revec-reducer.h.
                                   {
    DCHECK(IsForcePackNode());
    return reinterpret_cast<ForcePackNode*>(this);
  }
References v8::internal::DCHECK(), and IsForcePackNode().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation().
AsShufflePackNode()
ShufflePackNode* v8::internal::compiler::turboshaft::PackNode::AsShufflePackNode () [inline]
Definition at line 291 of file wasm-revec-reducer.h.
                                       {
    DCHECK(IsShufflePackNode());
    return reinterpret_cast<ShufflePackNode*>(this);
  }
References v8::internal::DCHECK(), and IsShufflePackNode().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle().
GetOperand()
PackNode* v8::internal::compiler::turboshaft::PackNode::GetOperand (int index) const [inline]
Definition at line 300 of file wasm-revec-reducer.h.
                                        {
    DCHECK_LT(index, operands_.size());
    DCHECK(operands_[index]);
    return operands_[index];
  }
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::index, and operands_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput().
GetOperandsSize()
ZoneVector<PackNode*>::size_type v8::internal::compiler::turboshaft::PackNode::GetOperandsSize () const [inline]
Definition at line 314 of file wasm-revec-reducer.h.
                                                         {
    return operands_.size();
  }
References operands_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop().
is_force_packing()
bool v8::internal::compiler::turboshaft::PackNode::is_force_packing () const [inline]
Definition at line 283 of file wasm-revec-reducer.h.
                                {
    return node_type_ == kForcePackNode || node_type_ == kIntersectPackNode;
  }
References kForcePackNode, kIntersectPackNode, and node_type_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize().
IsBundlePackNode()
bool v8::internal::compiler::turboshaft::PackNode::IsBundlePackNode () const [inline]
Definition at line 281 of file wasm-revec-reducer.h.
{ return node_type_ == kBundlePackNode; }
References kBundlePackNode, and node_type_.
Referenced by AsBundlePackNode(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane().
IsDefaultPackNode()
bool v8::internal::compiler::turboshaft::PackNode::IsDefaultPackNode () const [inline]
Definition at line 278 of file wasm-revec-reducer.h.
{ return node_type_ == kDefault; }
References kDefault, and node_type_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary().
IsForcePackNode()
bool v8::internal::compiler::turboshaft::PackNode::IsForcePackNode () const [inline]
Definition at line 279 of file wasm-revec-reducer.h.
{ return node_type_ == kForcePackNode; }
References kForcePackNode, and node_type_.
Referenced by AsForcePackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation().
IsSame() [1/2]
bool v8::internal::compiler::turboshaft::PackNode::IsSame (const NodeGroup & node_group) const [inline]
Definition at line 271 of file wasm-revec-reducer.h.
                                                 {
    return nodes_ == node_group;
  }
References nodes_.
IsSame() [2/2]
bool v8::internal::compiler::turboshaft::PackNode::IsSame (const PackNode & other) const [inline]
Definition at line 274 of file wasm-revec-reducer.h.
{ return nodes_ == other.nodes_; }
References nodes_.
IsShufflePackNode()
bool v8::internal::compiler::turboshaft::PackNode::IsShufflePackNode () const [inline]
Definition at line 280 of file wasm-revec-reducer.h.
{ return node_type_ == kShufflePackNode; }
References kShufflePackNode, and node_type_.
Referenced by AsShufflePackNode().
nodes()
const NodeGroup& v8::internal::compiler::turboshaft::PackNode::nodes () const [inline]
Definition at line 270 of file wasm-revec-reducer.h.
{ return nodes_; }
References nodes_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetStartOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceForceOrIntersectPackNode(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Constant(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
Print()
void v8::internal::compiler::turboshaft::PackNode::Print (Graph * graph) const
Definition at line 228 of file wasm-revec-reducer.cc.
                                       {
  Operation& op = graph->Get(nodes_[0]);
  TRACE("%s(#%d, #%d)\n", GetSimdOpcodeName(op).c_str(), nodes_[0].id(),
        nodes_[1].id());
}
References v8::internal::compiler::turboshaft::GetSimdOpcodeName(), graph(), nodes_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::turboshaft::SLPTree::Print(), and v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Print().
RevectorizedNode()
V<Simd256> v8::internal::compiler::turboshaft::PackNode::RevectorizedNode () const [inline]
Definition at line 275 of file wasm-revec-reducer.h.
{ return revectorized_node_; }
References revectorized_node_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Constant(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Splat(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
SetOperand()
void v8::internal::compiler::turboshaft::PackNode::SetOperand (int index, PackNode * pnode) [inline]
Definition at line 306 of file wasm-revec-reducer.h.
                                              {
    DCHECK_GE(index, 0);
    if (operands_.size() < static_cast<size_t>(index + 1)) {
      operands_.resize(index + 1);
    }
    operands_[index] = pnode;
  }
References DCHECK_GE, v8::internal::index, and operands_.
Referenced by v8::internal::compiler::turboshaft::SLPTree::NewCommutativePackNodeAndRecurs(), and v8::internal::compiler::turboshaft::SLPTree::NewPackNodeAndRecurs().
SetRevectorizedNode()
void v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode (V< Simd256 > node) [inline]
Definition at line 276 of file wasm-revec-reducer.h.
{ revectorized_node_ = node; }
References revectorized_node_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceForceOrIntersectPackNode(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Constant(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Splat(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
Friends And Related Function Documentation
ForcePackNode
friend class ForcePackNode [friend]
Definition at line 321 of file wasm-revec-reducer.h.
Member Data Documentation
node_type_
NodeType v8::internal::compiler::turboshaft::PackNode::node_type_ [private]
Definition at line 325 of file wasm-revec-reducer.h.
Referenced by is_force_packing(), IsBundlePackNode(), IsDefaultPackNode(), IsForcePackNode(), and IsShufflePackNode().
nodes_
NodeGroup v8::internal::compiler::turboshaft::PackNode::nodes_ [private]
Definition at line 322 of file wasm-revec-reducer.h.
Referenced by IsSame(), nodes(), and Print().
operands_
ZoneVector<PackNode*> v8::internal::compiler::turboshaft::PackNode::operands_ [private]
Definition at line 324 of file wasm-revec-reducer.h.
Referenced by GetOperand(), GetOperandsSize(), and SetOperand().
revectorized_node_
V<Simd256> v8::internal::compiler::turboshaft::PackNode::revectorized_node_ [private]
Definition at line 323 of file wasm-revec-reducer.h.
Referenced by RevectorizedNode(), and SetRevectorizedNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.cc