v8::internal::IrRegExpData Class Reference
#include <js-regexp.h>
Classes
class BodyDescriptor
Public Member Functions
bool has_code (bool is_one_byte) const
void set_code (bool is_one_byte, Tagged< Code > code)
Tagged< Code > code (IsolateForSandbox isolate, bool is_one_byte) const
bool has_bytecode (bool is_one_byte) const
void clear_bytecode (bool is_one_byte)
void set_bytecode (bool is_one_byte, Tagged< TrustedByteArray > bytecode)
Tagged< TrustedByteArray > bytecode (bool is_one_byte) const
void set_capture_name_map (DirectHandle< FixedArray > capture_name_map)
bool CanTierUp ()
bool MarkedForTierUp ()
void ResetLastTierUpTick ()
void TierUpTick ()
void MarkTierUpForNextExec ()
bool ShouldProduceBytecode ()
void DiscardCompiledCodeForSerialization ()
void SetBytecodeForExperimental (Isolate *isolate, Tagged< TrustedByteArray > bytecode)
OBJECT_CONSTRUCTORS (IrRegExpData, RegExpData)
Additional Inherited Members
Detailed Description
Definition at line 245 of file js-regexp.h.
Member Function Documentation
bytecode()
Tagged< TrustedByteArray > v8::internal::IrRegExpData::bytecode (bool is_one_byte) const [inline]
Definition at line 141 of file js-regexp-inl.h.
                                                                      {
  return is_one_byte ? latin1_bytecode() : uc16_bytecode();
}
References v8::internal::uc16_bytecode.
Referenced by set_bytecode(), and SetBytecodeForExperimental().
CanTierUp()
bool v8::internal::IrRegExpData::CanTierUp ()
Definition at line 383 of file js-regexp.cc.
                             {
  return v8_flags.regexp_tier_up && type_tag() == Type::IRREGEXP;
}
References v8::internal::RegExpData::IRREGEXP, v8::internal::RegExpData::type_tag(), and v8::internal::v8_flags.
Referenced by MarkedForTierUp().
clear_bytecode()
void v8::internal::IrRegExpData::clear_bytecode (bool is_one_byte) [inline]
Definition at line 126 of file js-regexp-inl.h.
                                                  {
  if (is_one_byte) {
    clear_latin1_bytecode();
  } else {
    clear_uc16_bytecode();
  }
}
code()
Tagged< Code > v8::internal::IrRegExpData::code (IsolateForSandbox isolate, bool is_one_byte) const [inline]
Definition at line 115 of file js-regexp-inl.h.
                                                        {
  return is_one_byte ? latin1_code(isolate) : uc16_code(isolate);
}
DiscardCompiledCodeForSerialization()
void v8::internal::IrRegExpData::DiscardCompiledCodeForSerialization ()
Definition at line 422 of file js-regexp.cc.
                                                       {
  DCHECK(HasCompiledCode());
  clear_latin1_code();
  clear_uc16_code();
  clear_latin1_bytecode();
  clear_uc16_bytecode();
}
References v8::internal::DCHECK(), and v8::internal::RegExpData::HasCompiledCode().
has_bytecode()
kUc16BytecodeOffset bool v8::internal::IrRegExpData::has_bytecode (bool is_one_byte) const [inline]
Definition at line 123 of file js-regexp-inl.h.
                                                      {
  return is_one_byte ? has_latin1_bytecode() : has_uc16_bytecode();
}
has_code()
bool v8::internal::IrRegExpData::has_code (bool is_one_byte) const [inline]
MarkedForTierUp()
bool v8::internal::IrRegExpData::MarkedForTierUp ()
Definition at line 389 of file js-regexp.cc.
                                   {
  if (!CanTierUp()) {
    return false;
  }
  return ticks_until_tier_up() == 0;
}
References CanTierUp().
Referenced by ShouldProduceBytecode().
MarkTierUpForNextExec()
void v8::internal::IrRegExpData::MarkTierUpForNextExec ()
Definition at line 412 of file js-regexp.cc.
                                         {
  DCHECK(v8_flags.regexp_tier_up);
  set_ticks_until_tier_up(0);
}
References v8::internal::DCHECK(), and v8::internal::v8_flags.
OBJECT_CONSTRUCTORS()
v8::internal::IrRegExpData::OBJECT_CONSTRUCTORS (IrRegExpData , RegExpData)
ResetLastTierUpTick()
void v8::internal::IrRegExpData::ResetLastTierUpTick ()
Definition at line 397 of file js-regexp.cc.
                                       {
  DCHECK(v8_flags.regexp_tier_up);
  int tier_up_ticks = ticks_until_tier_up();
  set_ticks_until_tier_up(tier_up_ticks + 1);
}
References v8::internal::DCHECK(), and v8::internal::v8_flags.
set_bytecode()
void v8::internal::IrRegExpData::set_bytecode (bool is_one_byte, Tagged< TrustedByteArray > bytecode) [inline]
Definition at line 133 of file js-regexp-inl.h.
                                                                   {
  if (is_one_byte) {
    set_latin1_bytecode(bytecode);
  } else {
    set_uc16_bytecode(bytecode);
  }
}
References bytecode().
set_capture_name_map()
void v8::internal::IrRegExpData::set_capture_name_map (DirectHandle< FixedArray > capture_name_map) [inline]
Definition at line 145 of file js-regexp-inl.h.
                                               {
  if (capture_name_map.is_null()) {
    set_capture_name_map(Smi::zero());
  } else {
    set_capture_name_map(*capture_name_map);
  }
}
References v8::internal::Smi::zero().
set_code()
void v8::internal::IrRegExpData::set_code (bool is_one_byte, Tagged< Code > code) [inline]
SetBytecodeForExperimental()
void v8::internal::IrRegExpData::SetBytecodeForExperimental (Isolate * isolate, Tagged< TrustedByteArray > bytecode)
Definition at line 430 of file js-regexp.cc.
                                                         {
  set_latin1_bytecode(bytecode);
  set_uc16_bytecode(bytecode);
  Tagged<Code> trampoline =
      *BUILTIN_CODE(isolate, RegExpExperimentalTrampoline);
  set_latin1_code(trampoline);
  set_uc16_code(trampoline);
}
References BUILTIN_CODE, and bytecode().
ShouldProduceBytecode()
bool v8::internal::IrRegExpData::ShouldProduceBytecode ()
Definition at line 417 of file js-regexp.cc.
                                         {
  return v8_flags.regexp_interpret_all ||
         (v8_flags.regexp_tier_up && !MarkedForTierUp());
}
References MarkedForTierUp(), and v8::internal::v8_flags.
TierUpTick()
void v8::internal::IrRegExpData::TierUpTick ()
Definition at line 403 of file js-regexp.cc.
                              {
  int tier_up_ticks = ticks_until_tier_up();
  if (tier_up_ticks == 0) {
    return;
  }
  set_ticks_until_tier_up(tier_up_ticks - 1);
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-regexp.h
/mnt/V8SourceCode/src/objects/js-regexp-inl.h
/mnt/V8SourceCode/src/objects/js-regexp.cc