v8::internal::PreParser Class Reference
#include <preparser.h>
Classes
struct TemplateLiteralState
Public Types
enum PreParseResult { kPreParseStackOverflow
, kPreParseNotIdentifiableError
, kPreParseSuccess
 }
using Identifier = PreParserIdentifier
using Expression = PreParserExpression
using Statement = PreParserStatement
Public Member Functions
PreParser (Zone *zone, Scanner *scanner, uintptr_t stack_limit, AstValueFactory *ast_value_factory, PendingCompilationErrorHandler *pending_error_handler, RuntimeCallStats *runtime_call_stats, V8FileLogger *v8_file_logger, UnoptimizedCompileFlags flags, bool parsing_on_main_thread=true)
PreParserLogger * logger ()
V8_EXPORT_PRIVATE PreParseResult PreParseProgram ()
PreParseResult PreParseFunction (const AstRawString *function_name, FunctionKind kind, FunctionSyntaxKind function_syntax_kind, DeclarationScope *function_scope, int *use_counts, ProducedPreparseData **produced_preparser_scope_data)
PreparseDataBuilder * preparse_data_builder () const
void set_preparse_data_builder (PreparseDataBuilder *preparse_data_builder)
std::vector< void * > * preparse_data_builder_buffer ()
Static Public Member Functions
static bool IsPreParser ()
Private Member Functions
bool AllowsLazyParsingWithoutUnresolvedVariables () const
bool parse_lazily () const
PendingCompilationErrorHandler * pending_error_handler ()
bool SkipFunction (const AstRawString *name, FunctionKind kind, FunctionSyntaxKind function_syntax_kind, DeclarationScope *function_scope, int *num_parameters, int *function_length, ProducedPreparseData **produced_preparse_data)
Expression ParseFunctionLiteral (Identifier name, Scanner::Location function_name_location, FunctionNameValidity function_name_validity, FunctionKind kind, int function_token_pos, FunctionSyntaxKind function_syntax_kind, LanguageMode language_mode, ZonePtrList< const AstRawString > *arguments_for_wrapped_function)
PreParserExpression InitializeObjectLiteral (PreParserExpression literal)
bool HasCheckedSyntax ()
void ParseStatementListAndLogFunction (PreParserFormalParameters *formals)
TemplateLiteralState OpenTemplateLiteral (int pos)
void AddTemplateExpression (TemplateLiteralState *state, const PreParserExpression &expression)
void AddTemplateSpan (TemplateLiteralState *state, bool should_cook, bool tail)
PreParserExpression CloseTemplateLiteral (TemplateLiteralState *state, int start, const PreParserExpression &tag)
bool IsPrivateReference (const PreParserExpression &expression)
void SetLanguageMode (Scope *scope, LanguageMode mode)
void SetAsmModule ()
void PrepareGeneratorVariables ()
PreParserStatement RewriteSwitchStatement (PreParserStatement switch_statement, Scope *scope)
Variable * DeclareVariable (const AstRawString *name, VariableKind kind, VariableMode mode, InitializationFlag init, Scope *scope, bool *was_added, int position)
void DeclareAndBindVariable (const VariableProxy *proxy, VariableKind kind, VariableMode mode, Scope *scope, bool *was_added, int initializer_position)
Variable * DeclarePrivateVariableName (const AstRawString *name, ClassScope *scope, VariableMode mode, IsStaticFlag is_static_flag, bool *was_added)
Variable * DeclareVariableName (const AstRawString *name, VariableMode mode, Scope *scope, bool *was_added, int position=kNoSourcePosition, VariableKind kind=NORMAL_VARIABLE)
PreParserBlock RewriteCatchPattern (CatchInfo *catch_info)
void ReportVarRedeclarationIn (const AstRawString *name, Scope *scope)
PreParserStatement RewriteTryStatement (PreParserStatement try_block, PreParserStatement catch_block, const SourceRange &catch_range, PreParserStatement finally_block, const SourceRange &finally_range, const CatchInfo &catch_info, int pos)
void ReportUnexpectedTokenAt (Scanner::Location location, Token::Value token, MessageTemplate message=MessageTemplate::kUnexpectedToken)
void ParseGeneratorFunctionBody (int pos, FunctionKind kind, PreParserScopedStatementList *body)
void ParseAsyncGeneratorFunctionBody (int pos, FunctionKind kind, PreParserScopedStatementList *body)
void DeclareFunctionNameVar (const AstRawString *function_name, FunctionSyntaxKind function_syntax_kind, DeclarationScope *function_scope)
void DeclareFunctionNameVar (const PreParserIdentifier &function_name, FunctionSyntaxKind function_syntax_kind, DeclarationScope *function_scope)
bool IdentifierEquals (const PreParserIdentifier &identifier, const AstRawString *other)
PreParserStatement DeclareFunction (const PreParserIdentifier &variable_name, const PreParserExpression &function, VariableMode mode, VariableKind kind, int beg_pos, int end_pos, ZonePtrList< const AstRawString > *names)
PreParserStatement DeclareClass (const PreParserIdentifier &variable_name, const PreParserExpression &value, ZonePtrList< const AstRawString > *names, int class_token_pos, int end_pos)
void DeclareClassVariable (ClassScope *scope, const PreParserIdentifier &name, ClassInfo *class_info, int class_token_pos)
void DeclarePublicClassMethod (const PreParserIdentifier &class_name, const PreParserExpression &property, bool is_constructor, ClassInfo *class_info)
void AddInstanceFieldOrStaticElement (const PreParserExpression &property, ClassInfo *class_info, bool is_static)
void DeclarePublicClassField (ClassScope *scope, const PreParserExpression &property, bool is_static, bool is_computed_name, ClassInfo *class_info)
void DeclarePrivateClassMember (ClassScope *scope, const PreParserIdentifier &property_name, const PreParserExpression &property, ClassLiteralProperty::Kind kind, bool is_static, ClassInfo *class_info)
void AddClassStaticBlock (PreParserBlock block, ClassInfo *class_info)
void AddSyntheticFunctionDeclaration (FunctionKind kind, int pos)
PreParserExpression RewriteClassLiteral (ClassScope *scope, const PreParserIdentifier &name, ClassInfo *class_info, int pos)
PreParserStatement DeclareNative (const PreParserIdentifier &name, int pos)
bool IsEval (const PreParserIdentifier &identifier) const
bool IsAsync (const PreParserIdentifier &identifier) const
bool IsArguments (const PreParserIdentifier &identifier) const
bool IsEvalOrArguments (const PreParserIdentifier &identifier) const
bool IsConstructor (const PreParserIdentifier &identifier) const
bool ParsingExtension () const
bool IsNative (const PreParserExpression &expr) const
bool IsStringLiteral (PreParserStatement statement) const
void PushPropertyName (const PreParserExpression &expression)
void PushEnclosingName (const PreParserIdentifier &name)
bool ShortcutLiteralBinaryExpression (PreParserExpression *x, const PreParserExpression &y, Token::Value op, int pos)
bool CollapseConditionalChain (PreParserExpression *x, PreParserExpression cond, PreParserExpression then_expression, PreParserExpression else_expression, int pos, const SourceRange &then_range)
void AppendConditionalChainElse (PreParserExpression *x, const SourceRange &else_range)
bool CollapseNaryExpression (PreParserExpression *x, PreParserExpression y, Token::Value op, int pos, const SourceRange &range)
PreParserExpression BuildUnaryExpression (const PreParserExpression &expression, Token::Value op, int pos)
PreParserStatement BuildInitializationBlock (DeclarationParsingResult *parsing_result)
PreParserBlock RewriteForVarInLegacy (const ForInfo &for_info)
void DesugarBindingInForEachStatement (ForInfo *for_info, PreParserStatement *body_block, PreParserExpression *each_variable)
PreParserBlock CreateForEachStatementTDZ (PreParserBlock init_block, const ForInfo &for_info)
StatementT DesugarLexicalBindingsInForStatement (PreParserStatement loop, PreParserStatement init, const PreParserExpression &cond, PreParserStatement next, PreParserStatement body, Scope *inner_scope, const ForInfo &for_info)
PreParserBlock BuildParameterInitializationBlock (const PreParserFormalParameters &parameters)
void InsertSloppyBlockFunctionVarBindings (DeclarationScope *scope)
void InsertShadowingVarBindingInitializers (PreParserStatement block)
PreParserExpression NewThrowReferenceError (MessageTemplate message, int pos)
const AstRawString * PreParserIdentifierToAstRawString (const PreParserIdentifier &x)
void ReportUnidentifiableError ()
const AstRawString * GetRawNameFromIdentifier (const PreParserIdentifier &arg)
PreParserStatement AsIterationStatement (PreParserStatement s)
PreParserIdentifier EmptyIdentifierString () const
bool IsEmptyIdentifier (PreParserIdentifier subject)
PreParserIdentifier GetSymbol () const
PreParserIdentifier GetIdentifier () const
PreParserIdentifier GetNextSymbol () const
PreParserIdentifier GetNumberAsSymbol () const
PreParserIdentifier GetBigIntAsSymbol () const
PreParserExpression ThisExpression ()
PreParserExpression NewThisExpression (int pos)
PreParserExpression NewSuperPropertyReference (int pos)
PreParserExpression NewSuperCallReference (int pos)
PreParserExpression NewTargetExpression (int pos)
PreParserExpression ImportMetaExpression (int pos)
PreParserExpression ExpressionFromLiteral (Token::Value token, int pos)
PreParserExpression ExpressionFromPrivateName (PrivateNameScopeIterator *private_name_scope, const PreParserIdentifier &name, int start_position)
PreParserExpression ExpressionFromIdentifier (const PreParserIdentifier &name, int start_position, InferName infer=InferName::kYes)
void DeclareIdentifier (const PreParserIdentifier &name, int start_position)
Variable * DeclareCatchVariableName (Scope *scope, const PreParserIdentifier &identifier)
PreParserPropertyList NewClassPropertyList (int size) const
PreParserPropertyList NewClassStaticElementList (int size) const
PreParserStatementList NewStatementList (int size) const
PreParserExpression NewClassLiteralPropertyWithAccessorInfo (ClassScope *scope, ClassInfo *class_info, const PreParserIdentifier &name, const PreParserExpression &key, const PreParserExpression &value, bool is_static, bool is_computed_name, bool is_private, int pos)
PreParserExpression NewV8Intrinsic (const PreParserIdentifier &name, const PreParserExpressionList &arguments, int pos)
PreParserStatement NewThrowStatement (const PreParserExpression &exception, int pos)
void AddFormalParameter (PreParserFormalParameters *parameters, const PreParserExpression &pattern, const PreParserExpression &initializer, int initializer_end_position, bool is_rest)
void ReindexArrowFunctionFormalParameters (PreParserFormalParameters *parameters)
void ReindexComputedMemberName (const PreParserExpression &expression)
void DeclareFormalParameters (const PreParserFormalParameters *parameters)
void DeclareArrowFunctionFormalParameters (PreParserFormalParameters *parameters, const PreParserExpression &params, const Scanner::Location &params_loc)
PreParserExpression ExpressionListToExpression (const PreParserExpressionList &args)
void SetFunctionNameFromPropertyName (const PreParserExpression &property, const PreParserIdentifier &name, const AstRawString *prefix=nullptr)
void SetFunctionNameFromIdentifierRef (const PreParserExpression &value, const PreParserExpression &identifier)
void CountUsage (v8::Isolate::UseCounterFeature feature)
bool ParsingDynamicFunctionDeclaration () const
FunctionLiteral::EagerCompileHint GetEmbedderCompileHint (FunctionLiteral::EagerCompileHint current_compile_hint, int position)
Static Private Member Functions
static bool IsThisProperty (const PreParserExpression &expression)
static bool IsIdentifier (const PreParserExpression &expression)
static PreParserIdentifier AsIdentifier (const PreParserExpression &expression)
static PreParserExpression AsIdentifierExpression (const PreParserExpression &expression)
static bool IsBoilerplateProperty (const PreParserExpression &property)
static bool IsArrayIndex (const PreParserIdentifier &string, uint32_t *index)
static void GetDefaultStrings (PreParserIdentifier *default_string, PreParserIdentifier *dot_default_string)
static void PushLiteralName (const PreParserIdentifier &id)
static void PushVariableName (const PreParserIdentifier &id)
static void AddFunctionForNameInference (const PreParserExpression &expression)
static void InferFunctionName ()
static void CheckAssigningFunctionLiteralToProperty (const PreParserExpression &left, const PreParserExpression &right)
static PreParserIdentifier NullIdentifier ()
static PreParserExpression NullExpression ()
static PreParserExpression FailureExpression ()
static PreParserExpression NullLiteralProperty ()
static PreParserStatementList NullStatementList ()
static PreParserStatement NullStatement ()
static PreParserBlock NullBlock ()
template<typename T >
static bool IsNull (T subject)
static bool IsIterationStatement (PreParserStatement subject)
Private Attributes
int * use_counts_
PreParserLogger log_
PreparseDataBuilder * preparse_data_builder_
std::vector< void * > preparse_data_builder_buffer_
Friends
class ParserBase< PreParser >
class i::ExpressionScope< ParserTypes< PreParser > >
class i::VariableDeclarationParsingScope< ParserTypes< PreParser > >
class i::ParameterDeclarationParsingScope< ParserTypes< PreParser > >
class i::ArrowHeadParsingScope< ParserTypes< PreParser > >
class PreParserFormalParameters
Additional Inherited Members
Detailed Description
Definition at line 855 of file preparser.h.
Member Typedef Documentation
Expression
using v8::internal::PreParser::Expression = PreParserExpression
Definition at line 860 of file preparser.h.
Identifier
using v8::internal::PreParser::Identifier = PreParserIdentifier
Definition at line 859 of file preparser.h.
Statement
using v8::internal::PreParser::Statement = PreParserStatement
Definition at line 861 of file preparser.h.
Member Enumeration Documentation
PreParseResult
enum v8::internal::PreParser::PreParseResult
Enumerator
kPreParseStackOverflow
kPreParseNotIdentifiableError
kPreParseSuccess
Definition at line 863 of file preparser.h.
                      {
    kPreParseStackOverflow,
    kPreParseNotIdentifiableError,
    kPreParseSuccess
  };
Constructor & Destructor Documentation
PreParser()
v8::internal::PreParser::PreParser (Zone * zone, Scanner * scanner, uintptr_t stack_limit, AstValueFactory * ast_value_factory, PendingCompilationErrorHandler * pending_error_handler, RuntimeCallStats * runtime_call_stats, V8FileLogger * v8_file_logger, UnoptimizedCompileFlags flags, bool parsing_on_main_thread = true) [inline]
Definition at line 869 of file preparser.h.
      : ParserBase<PreParser>(
            zone, scanner, stack_limit, ast_value_factory,
            pending_error_handler, runtime_call_stats, v8_file_logger, flags,
            parsing_on_main_thread,
            /*compile_hints_magic_enabled=*/false,
            /*compile_hints_per_function_magic_enabled=*/false),
        use_counts_(nullptr),
        preparse_data_builder_(nullptr),
        preparse_data_builder_buffer_() {
    preparse_data_builder_buffer_.reserve(16);
  }
References preparse_data_builder_buffer_.
Member Function Documentation
AddClassStaticBlock()
void v8::internal::PreParser::AddClassStaticBlock (PreParserBlock block, ClassInfo * class_info) [inline], [private]
Definition at line 1173 of file preparser.h.
                                                            {
    DCHECK(class_info->has_static_elements());
  }
References v8::internal::DCHECK().
AddFormalParameter()
void v8::internal::PreParser::AddFormalParameter (PreParserFormalParameters * parameters, const PreParserExpression & pattern, const PreParserExpression & initializer, int initializer_end_position, bool is_rest) [inline], [private]
Definition at line 1568 of file preparser.h.
                                                  {
    DeclarationScope* scope = parameters->scope;
    scope->RecordParameter(is_rest);
    parameters->UpdateArityAndFunctionLength(!initializer.IsNull(), is_rest);
  }
References v8::internal::PreParserExpression::IsNull(), v8::internal::FormalParametersBase::scope, v8::internal::ParserBase< PreParser >::scope(), and v8::internal::FormalParametersBase::UpdateArityAndFunctionLength().
AddFunctionForNameInference()
static void v8::internal::PreParser::AddFunctionForNameInference (const PreParserExpression & expression) [inline], [static], [private]
Definition at line 1293 of file preparser.h.
                                             {}
AddInstanceFieldOrStaticElement()
void v8::internal::PreParser::AddInstanceFieldOrStaticElement (const PreParserExpression & property, ClassInfo * class_info, bool is_static) [inline], [private]
Definition at line 1140 of file preparser.h.
                      {}
AddSyntheticFunctionDeclaration()
void v8::internal::PreParser::AddSyntheticFunctionDeclaration (FunctionKind kind, int pos) [inline], [private]
Definition at line 1178 of file preparser.h.
                                                                             {
    // Creating and disposing of a FunctionState makes tracking of
    // next_function_is_likely_called match what Parser does. TODO(marja):
    // Make the lazy function + next_function_is_likely_called + default ctor
    // logic less surprising. Default ctors shouldn't affect the laziness of
    // functions.
    DeclarationScope* function_scope = NewFunctionScope(kind);
    SetLanguageMode(function_scope, LanguageMode::kStrict);
    function_scope->set_start_position(pos);
    function_scope->set_end_position(pos);
    FunctionState function_state(&function_state_, &scope_, function_scope);
    GetNextInfoId();
  }
References v8::internal::ParserBase< PreParser >::function_state_, v8::internal::ParserBase< PreParser >::GetNextInfoId(), v8::internal::kStrict, v8::internal::ParserBase< PreParser >::NewFunctionScope(), v8::internal::ParserBase< PreParser >::scope_, v8::internal::Scope::set_end_position(), v8::internal::Scope::set_start_position(), and SetLanguageMode().
Referenced by NewClassLiteralPropertyWithAccessorInfo(), and RewriteClassLiteral().
AddTemplateExpression()
void v8::internal::PreParser::AddTemplateExpression (TemplateLiteralState * state, const PreParserExpression & expression) [inline], [private]
Definition at line 977 of file preparser.h.
                                                                              {}
AddTemplateSpan()
void v8::internal::PreParser::AddTemplateSpan (TemplateLiteralState * state, bool should_cook, bool tail) [inline], [private]
Definition at line 979 of file preparser.h.
                                            {}
AllowsLazyParsingWithoutUnresolvedVariables()
bool v8::internal::PreParser::AllowsLazyParsingWithoutUnresolvedVariables () const [inline], [private]
Definition at line 942 of file preparser.h.
{ return false; }
AppendConditionalChainElse()
void v8::internal::PreParser::AppendConditionalChainElse (PreParserExpression * x, const SourceRange & else_range) [inline], [private]
Definition at line 1315 of file preparser.h.
                                                                           {}
AsIdentifier()
static PreParserIdentifier v8::internal::PreParser::AsIdentifier (const PreParserExpression & expression) [inline], [static], [private]
Definition at line 1238 of file preparser.h.
                                             {
    return expression.AsIdentifier();
  }
References v8::internal::PreParserExpression::AsIdentifier().
AsIdentifierExpression()
static PreParserExpression v8::internal::PreParser::AsIdentifierExpression (const PreParserExpression & expression) [inline], [static], [private]
Definition at line 1243 of file preparser.h.
                                             {
    return expression;
  }
AsIterationStatement()
PreParserStatement v8::internal::PreParser::AsIterationStatement (PreParserStatement s) [inline], [private]
Definition at line 1398 of file preparser.h.
{ return s; }
BuildInitializationBlock()
PreParserStatement v8::internal::PreParser::BuildInitializationBlock (DeclarationParsingResult * parsing_result) [inline], [private]
Definition at line 1331 of file preparser.h.
                                                                     {
    return PreParserStatement::Default();
  }
References v8::internal::PreParserStatement::Default().
BuildParameterInitializationBlock()
PreParserBlock v8::internal::PreParser::BuildParameterInitializationBlock (const PreParserFormalParameters & parameters) [private]
Definition at line 372 of file preparser.cc.
                                                 {
  DCHECK(!parameters.is_simple);
  DCHECK(scope()->is_function_scope());
  if (scope()->AsDeclarationScope()->sloppy_eval_can_extend_vars() &&
      preparse_data_builder_ != nullptr) {
    // We cannot replicate the Scope structure constructed by the Parser,
    // because we've lost information whether each individual parameter was
    // simple or not. Give up trying to produce data to skip inner functions.
    if (preparse_data_builder_->parent() != nullptr) {
      // Lazy parsing started before the current function; the function which
      // cannot contain skippable functions is the parent function. (Its inner
      // functions cannot either; they are implicitly bailed out.)
      preparse_data_builder_->parent()->Bailout();
    } else {
      // Lazy parsing started at the current function; it cannot contain
      // skippable functions.
      preparse_data_builder_->Bailout();
    }
  }
  return PreParserBlock::Default();
}
References v8::internal::PreparseDataBuilder::Bailout(), v8::internal::DCHECK(), v8::internal::PreParserBlock::Default(), v8::internal::FormalParametersBase::is_simple, v8::internal::PreparseDataBuilder::parent(), preparse_data_builder_, and v8::internal::ParserBase< PreParser >::scope().
Referenced by PreParseFunction().
BuildUnaryExpression()
PreParserExpression v8::internal::PreParser::BuildUnaryExpression (const PreParserExpression & expression, Token::Value op, int pos) [inline], [private]
Definition at line 1325 of file preparser.h.
                                                                     {
    return PreParserExpression::Default();
  }
References v8::internal::PreParserExpression::Default().
CheckAssigningFunctionLiteralToProperty()
static void v8::internal::PreParser::CheckAssigningFunctionLiteralToProperty (const PreParserExpression & left, const PreParserExpression & right) [inline], [static], [private]
Definition at line 1297 of file preparser.h.
                                                                         {}
CloseTemplateLiteral()
PreParserExpression v8::internal::PreParser::CloseTemplateLiteral (TemplateLiteralState * state, int start, const PreParserExpression & tag) [inline], [private]
Definition at line 981 of file preparser.h.
                                                                              {
    return PreParserExpression::Default();
  }
References v8::internal::PreParserExpression::Default().
CollapseConditionalChain()
bool v8::internal::PreParser::CollapseConditionalChain (PreParserExpression * x, PreParserExpression cond, PreParserExpression then_expression, PreParserExpression else_expression, int pos, const SourceRange & then_range) [inline], [private]
Definition at line 1306 of file preparser.h.
                                                                         {
    return false;
  }
CollapseNaryExpression()
bool v8::internal::PreParser::CollapseNaryExpression (PreParserExpression * x, PreParserExpression y, Token::Value op, int pos, const SourceRange & range) [inline], [private]
Definition at line 1318 of file preparser.h.
                                                                           {
    x->clear_parenthesized();
    return false;
  }
References v8::internal::PreParserExpression::clear_parenthesized().
CountUsage()
void v8::internal::PreParser::CountUsage (v8::Isolate::UseCounterFeature feature) [inline], [private]
Definition at line 1604 of file preparser.h.
                                                                {
    if (use_counts_ != nullptr) ++use_counts_[feature];
  }
References use_counts_.
CreateForEachStatementTDZ()
PreParserBlock v8::internal::PreParser::CreateForEachStatementTDZ (PreParserBlock init_block, const ForInfo & for_info) [inline], [private]
Definition at line 1344 of file preparser.h.
                                                                              {
    if (IsLexicalVariableMode(for_info.parsing_result.descriptor.mode)) {
      for (auto name : for_info.bound_names) {
        bool was_added;
        DeclareVariableName(name, VariableMode::kLet, scope(), &was_added);
      }
      return PreParserBlock::Default();
    }
    return init_block;
  }
References DeclareVariableName(), v8::internal::PreParserBlock::Default(), v8::internal::IsLexicalVariableMode(), v8::internal::kLet, v8::internal::name, and v8::internal::ParserBase< PreParser >::scope().
DeclareAndBindVariable()
void v8::internal::PreParser::DeclareAndBindVariable (const VariableProxy * proxy, VariableKind kind, VariableMode mode, Scope * scope, bool * was_added, int initializer_position) [inline], [private]
Definition at line 1006 of file preparser.h.
                                                        {
    Variable* var = DeclareVariableName(proxy->raw_name(), mode, scope,
                                        was_added, proxy->position(), kind);
    var->set_initializer_position(initializer_position);
    // Don't bother actually binding the proxy.
  }
References DeclareVariableName(), mode(), v8::internal::AstNode::position(), v8::internal::VariableProxy::raw_name(), v8::internal::ParserBase< PreParser >::scope(), and v8::internal::Variable::set_initializer_position().
DeclareArrowFunctionFormalParameters()
void v8::internal::PreParser::DeclareArrowFunctionFormalParameters (PreParserFormalParameters * parameters, const PreParserExpression & params, const Scanner::Location & params_loc) [inline], [private]
Definition at line 1587 of file preparser.h.
                                         {
  }
DeclareCatchVariableName()
Variable* v8::internal::PreParser::DeclareCatchVariableName (Scope * scope, const PreParserIdentifier & identifier) [inline], [private]
Definition at line 1517 of file preparser.h.
                                                           {
    return scope->DeclareCatchVariableName(identifier.string_);
  }
References v8::internal::Scope::DeclareCatchVariableName(), v8::internal::ParserBase< PreParser >::scope(), and v8::internal::PreParserIdentifier::string_.
DeclareClass()
PreParserStatement v8::internal::PreParser::DeclareClass (const PreParserIdentifier & variable_name, const PreParserExpression & value, ZonePtrList< const AstRawString > * names, int class_token_pos, int end_pos) [inline], [private]
Definition at line 1114 of file preparser.h.
                                        {
    // Preparser shouldn't be used in contexts where we need to track the names.
    DCHECK_NULL(names);
    bool was_added;
    DeclareVariableName(variable_name.string_, VariableMode::kLet, scope(),
                        &was_added);
    return PreParserStatement::Default();
  }
References DCHECK_NULL, DeclareVariableName(), v8::internal::PreParserStatement::Default(), v8::internal::kLet, v8::internal::ParserBase< PreParser >::scope(), and v8::internal::PreParserIdentifier::string_.
DeclareClassVariable()
void v8::internal::PreParser::DeclareClassVariable (ClassScope * scope, const PreParserIdentifier & name, ClassInfo * class_info, int class_token_pos) [inline], [private]
Definition at line 1125 of file preparser.h.
                                                           {
    DCHECK_IMPLIES(IsEmptyIdentifier(name), class_info->is_anonymous);
    // Declare a special class variable for anonymous classes with the dot
    // if we need to save it for static private method access.
    scope->DeclareClassVariable(ast_value_factory(), name.string_,
                                class_token_pos);
  }
References v8::internal::ParserBase< PreParser >::ast_value_factory(), DCHECK_IMPLIES, IsEmptyIdentifier(), v8::internal::name, and v8::internal::ParserBase< PreParser >::scope().
DeclareFormalParameters()
void v8::internal::PreParser::DeclareFormalParameters (const PreParserFormalParameters * parameters) [inline], [private]
Definition at line 1582 of file preparser.h.
                                                   {
    if (!parameters->is_simple) parameters->scope->SetHasNonSimpleParameters();
  }
References v8::internal::FormalParametersBase::is_simple, v8::internal::FormalParametersBase::scope, and v8::internal::DeclarationScope::SetHasNonSimpleParameters().
DeclareFunction()
PreParserStatement v8::internal::PreParser::DeclareFunction (const PreParserIdentifier & variable_name, const PreParserExpression & function, VariableMode mode, VariableKind kind, int beg_pos, int end_pos, ZonePtrList< const AstRawString > * names) [inline], [private]
Definition at line 1095 of file preparser.h.
                                                                        {
    DCHECK_NULL(names);
    bool was_added;
    Variable* var = DeclareVariableName(variable_name.string_, mode, scope(),
                                        &was_added, beg_pos, kind);
    if (kind == SLOPPY_BLOCK_FUNCTION_VARIABLE) {
      Token::Value init =
          loop_nesting_depth() > 0 ? Token::kAssign : Token::kInit;
      SloppyBlockFunctionStatement* statement =
          factory()->ast_node_factory()->NewSloppyBlockFunctionStatement(
              end_pos, var, init);
      GetDeclarationScope()->DeclareSloppyBlockFunction(statement);
    }
    return Statement::Default();
  }
References v8::internal::PreParserFactory::ast_node_factory(), DCHECK_NULL, v8::internal::DeclarationScope::DeclareSloppyBlockFunction(), DeclareVariableName(), v8::internal::PreParserStatement::Default(), v8::internal::ParserBase< PreParser >::factory(), v8::internal::ParserBase< PreParser >::GetDeclarationScope(), v8::internal::ParserBase< PreParser >::loop_nesting_depth(), mode(), v8::internal::AstNodeFactory::NewSloppyBlockFunctionStatement(), v8::internal::ParserBase< PreParser >::scope(), v8::internal::SLOPPY_BLOCK_FUNCTION_VARIABLE, and v8::internal::PreParserIdentifier::string_.
DeclareFunctionNameVar() [1/2]
void v8::internal::PreParser::DeclareFunctionNameVar (const AstRawString * function_name, FunctionSyntaxKind function_syntax_kind, DeclarationScope * function_scope) [inline], [private]
Definition at line 1074 of file preparser.h.
                                                                          {
    if (function_syntax_kind == FunctionSyntaxKind::kNamedExpression &&
        function_scope->LookupLocal(function_name) == nullptr) {
      DCHECK_EQ(function_scope, scope());
      function_scope->DeclareFunctionVar(function_name);
    }
  }
References DCHECK_EQ, v8::internal::DeclarationScope::DeclareFunctionVar(), v8::internal::kNamedExpression, v8::internal::Scope::LookupLocal(), and v8::internal::ParserBase< PreParser >::scope().
Referenced by DeclareFunctionNameVar(), and PreParseFunction().
DeclareFunctionNameVar() [2/2]
void v8::internal::PreParser::DeclareFunctionNameVar (const PreParserIdentifier & function_name, FunctionSyntaxKind function_syntax_kind, DeclarationScope * function_scope) [inline], [private]
Definition at line 1084 of file preparser.h.
                                        {
    DeclareFunctionNameVar(function_name.string_, function_syntax_kind,
                           function_scope);
  }
References DeclareFunctionNameVar(), and v8::internal::PreParserIdentifier::string_.
DeclareIdentifier()
void v8::internal::PreParser::DeclareIdentifier (const PreParserIdentifier & name, int start_position) [inline], [private]
Definition at line 1512 of file preparser.h.
                                                       {
    expression_scope()->Declare(name.string_, start_position);
  }
References v8::internal::ParserBase< PreParser >::expression_scope(), and v8::internal::name.
DeclareNative()
PreParserStatement v8::internal::PreParser::DeclareNative (const PreParserIdentifier & name, int pos) [inline], [private]
Definition at line 1206 of file preparser.h.
                                                      {
    return PreParserStatement::Default();
  }
References v8::internal::PreParserStatement::Default().
DeclarePrivateClassMember()
void v8::internal::PreParser::DeclarePrivateClassMember (ClassScope * scope, const PreParserIdentifier & property_name, const PreParserExpression & property, ClassLiteralProperty::Kind kind, bool is_static, ClassInfo * class_info) [inline], [private]
Definition at line 1156 of file preparser.h.
                                             {
    bool was_added;
    DeclarePrivateVariableName(
        property_name.string_, scope, GetVariableMode(kind),
        is_static ? IsStaticFlag::kStatic : IsStaticFlag::kNotStatic,
        &was_added);
    if (!was_added) {
      Scanner::Location loc(property.position(), property.position() + 1);
      ReportMessageAt(loc, MessageTemplate::kVarRedeclaration,
                      property_name.string_);
    }
  }
References DeclarePrivateVariableName(), v8::internal::ParserBase< PreParser >::GetVariableMode(), v8::internal::kNotStatic, v8::internal::kStatic, v8::internal::loc, v8::internal::PreParserExpression::position(), v8::internal::ParserBase< PreParser >::ReportMessageAt(), v8::internal::ParserBase< PreParser >::scope(), and v8::internal::PreParserIdentifier::string_.
DeclarePrivateVariableName()
Variable* v8::internal::PreParser::DeclarePrivateVariableName (const AstRawString * name, ClassScope * scope, VariableMode mode, IsStaticFlag is_static_flag, bool * was_added) [inline], [private]
Definition at line 1015 of file preparser.h.
                                                        {
    DCHECK(IsImmutableLexicalOrPrivateVariableMode(mode));
    return scope->DeclarePrivateName(name, mode, is_static_flag, was_added);
  }
References v8::internal::DCHECK(), v8::internal::IsImmutableLexicalOrPrivateVariableMode(), mode(), v8::internal::name, and v8::internal::ParserBase< PreParser >::scope().
Referenced by DeclarePrivateClassMember().
DeclarePublicClassField()
void v8::internal::PreParser::DeclarePublicClassField (ClassScope * scope, const PreParserExpression & property, bool is_static, bool is_computed_name, ClassInfo * class_info) [inline], [private]
Definition at line 1143 of file preparser.h.
                                                                {
    if (is_computed_name) {
      bool was_added;
      DeclareVariableName(
          ClassFieldVariableName(ast_value_factory(),
                                 class_info->computed_field_count),
          VariableMode::kConst, scope, &was_added);
    }
  }
References v8::internal::ParserBase< PreParser >::ast_value_factory(), v8::internal::ParserBase< PreParser >::ClassFieldVariableName(), DeclareVariableName(), v8::internal::kConst, and v8::internal::ParserBase< PreParser >::scope().
DeclarePublicClassMethod()
void v8::internal::PreParser::DeclarePublicClassMethod (const PreParserIdentifier & class_name, const PreParserExpression & property, bool is_constructor, ClassInfo * class_info) [inline], [private]
Definition at line 1135 of file preparser.h.
                                                                 {}
DeclareVariable()
Variable* v8::internal::PreParser::DeclareVariable (const AstRawString * name, VariableKind kind, VariableMode mode, InitializationFlag init, Scope * scope, bool * was_added, int position) [inline], [private]
Definition at line 1000 of file preparser.h.
                                                                         {
    return DeclareVariableName(name, mode, scope, was_added, position, kind);
  }
References DeclareVariableName(), mode(), v8::internal::name, v8::internal::ParserBase< PreParser >::position(), and v8::internal::ParserBase< PreParser >::scope().
DeclareVariableName()
Variable* v8::internal::PreParser::DeclareVariableName (const AstRawString * name, VariableMode mode, Scope * scope, bool * was_added, int position = kNoSourcePosition, VariableKind kind = NORMAL_VARIABLE) [inline], [private]
Definition at line 1023 of file preparser.h.
                                                                     {
    DCHECK(!IsPrivateMethodOrAccessorVariableMode(mode));
    Variable* var = scope->DeclareVariableName(name, mode, was_added, kind);
    if (var == nullptr) {
      ReportUnidentifiableError();
      if (!IsLexicalVariableMode(mode)) scope = scope->GetDeclarationScope();
      var = scope->LookupLocal(name);
    } else if (var->scope() != scope) {
      DCHECK_NE(kNoSourcePosition, position);
      DCHECK_EQ(VariableMode::kVar, mode);
      Declaration* nested_declaration =
          factory()->ast_node_factory()->NewNestedVariableDeclaration(scope,
                                                                      position);
      nested_declaration->set_var(var);
      var->scope()->declarations()->Add(nested_declaration);
    }
    return var;
  }
References v8::internal::PreParserFactory::ast_node_factory(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::Scope::declarations(), v8::internal::Scope::DeclareVariableName(), v8::internal::ParserBase< PreParser >::factory(), v8::internal::Scope::GetDeclarationScope(), v8::internal::IsLexicalVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::kNoSourcePosition, v8::internal::kVar, v8::internal::Scope::LookupLocal(), mode(), v8::internal::name, v8::internal::AstNodeFactory::NewNestedVariableDeclaration(), v8::internal::ParserBase< PreParser >::position(), ReportUnidentifiableError(), v8::internal::Variable::scope(), v8::internal::ParserBase< PreParser >::scope(), and v8::internal::Declaration::set_var().
Referenced by CreateForEachStatementTDZ(), DeclareAndBindVariable(), DeclareClass(), DeclareFunction(), DeclarePublicClassField(), DeclareVariable(), DesugarLexicalBindingsInForStatement(), and NewClassLiteralPropertyWithAccessorInfo().
DesugarBindingInForEachStatement()
void v8::internal::PreParser::DesugarBindingInForEachStatement (ForInfo * for_info, PreParserStatement * body_block, PreParserExpression * each_variable) [inline], [private]
Definition at line 1339 of file preparser.h.
                                          {
  }
DesugarLexicalBindingsInForStatement()
StatementT v8::internal::PreParser::DesugarLexicalBindingsInForStatement (PreParserStatement loop, PreParserStatement init, const PreParserExpression & cond, PreParserStatement next, PreParserStatement body, Scope * inner_scope, const ForInfo & for_info) [inline], [private]
Definition at line 1356 of file preparser.h.
                                                                            {
    // See Parser::DesugarLexicalBindingsInForStatement.
    for (auto name : for_info.bound_names) {
      bool was_added;
      DeclareVariableName(name, for_info.parsing_result.descriptor.mode,
                          inner_scope, &was_added);
    }
    return loop;
  }
References DeclareVariableName(), and v8::internal::name.
EmptyIdentifierString()
PreParserIdentifier v8::internal::PreParser::EmptyIdentifierString () const [inline], [private]
Definition at line 1430 of file preparser.h.
                                                              {
    PreParserIdentifier result = PreParserIdentifier::Default();
    result.string_ = ast_value_factory()->empty_string();
    return result;
  }
References v8::internal::ParserBase< PreParser >::ast_value_factory(), v8::internal::PreParserIdentifier::Default(), and v8::base::internal::result.
ExpressionFromIdentifier()
PreParserExpression v8::internal::PreParser::ExpressionFromIdentifier (const PreParserIdentifier & name, int start_position, InferName infer = InferName::kYes) [inline], [private]
Definition at line 1505 of file preparser.h.
                                       {
    expression_scope()->NewVariable(name.string_, start_position);
    return PreParserExpression::FromIdentifier(name);
  }
References v8::internal::ParserBase< PreParser >::expression_scope(), v8::internal::PreParserExpression::FromIdentifier(), and v8::internal::name.
ExpressionFromLiteral()
PreParserExpression v8::internal::PreParser::ExpressionFromLiteral (Token::Value token, int pos) [inline], [private]
Definition at line 1490 of file preparser.h.
                                                               {
    if (token != Token::kString) return PreParserExpression::Default();
    return PreParserExpression::StringLiteral();
  }
References v8::internal::PreParserExpression::Default(), and v8::internal::PreParserExpression::StringLiteral().
ExpressionFromPrivateName()
PreParserExpression v8::internal::PreParser::ExpressionFromPrivateName (PrivateNameScopeIterator * private_name_scope, const PreParserIdentifier & name, int start_position) [inline], [private]
Definition at line 1496 of file preparser.h.
                                                           {
    VariableProxy* proxy = factory()->ast_node_factory()->NewVariableProxy(
        name.string_, NORMAL_VARIABLE, start_position);
    private_name_scope->AddUnresolvedPrivateName(proxy);
    return PreParserExpression::FromIdentifier(name);
  }
References v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), v8::internal::PreParserFactory::ast_node_factory(), v8::internal::ParserBase< PreParser >::factory(), v8::internal::PreParserExpression::FromIdentifier(), v8::internal::name, v8::internal::AstNodeFactory::NewVariableProxy(), and v8::internal::NORMAL_VARIABLE.
ExpressionListToExpression()
PreParserExpression v8::internal::PreParser::ExpressionListToExpression (const PreParserExpressionList & args) [inline], [private]
Definition at line 1593 of file preparser.h.
                                                                  {
    return PreParserExpression::Default();
  }
References v8::internal::PreParserExpression::Default().
FailureExpression()
static PreParserExpression v8::internal::PreParser::FailureExpression () [inline], [static], [private]
Definition at line 1407 of file preparser.h.
                                                           {
    return PreParserExpression::Failure();
  }
References v8::internal::PreParserExpression::Failure().
GetBigIntAsSymbol()
PreParserIdentifier v8::internal::PreParser::GetBigIntAsSymbol () const [inline], [private]
Definition at line 1454 of file preparser.h.
                                                          {
    return PreParserIdentifier::Default();
  }
References v8::internal::PreParserIdentifier::Default().
GetDefaultStrings()
static void v8::internal::PreParser::GetDefaultStrings (PreParserIdentifier * default_string, PreParserIdentifier * dot_default_string) [inline], [static], [private]
Definition at line 1283 of file preparser.h.
                                               {}
GetEmbedderCompileHint()
FunctionLiteral::EagerCompileHint v8::internal::PreParser::GetEmbedderCompileHint (FunctionLiteral::EagerCompileHint current_compile_hint, int position) [inline], [private]
Definition at line 1610 of file preparser.h.
                                                                          {
    return current_compile_hint;
  }
GetIdentifier()
PreParserIdentifier v8::internal::PreParser::GetIdentifier () const [private]
Definition at line 58 of file preparser.cc.
                                                   {
  const AstRawString* result = scanner()->CurrentSymbol(ast_value_factory());
  PreParserIdentifier symbol =
      GetIdentifierHelper(scanner(), result, ast_value_factory());
  DCHECK_NOT_NULL(result);
  symbol.string_ = result;
  return symbol;
}
References v8::internal::ParserBase< PreParser >::ast_value_factory(), v8::internal::Scanner::CurrentSymbol(), DCHECK_NOT_NULL, v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper(), v8::base::internal::result, v8::internal::ParserBase< PreParser >::scanner(), and v8::internal::PreParserIdentifier::string_.
GetNextSymbol()
PreParserIdentifier v8::internal::PreParser::GetNextSymbol () const [inline], [private]
Definition at line 1446 of file preparser.h.
                                                      {
    return PreParserIdentifier::Default();
  }
References v8::internal::PreParserIdentifier::Default().
GetNumberAsSymbol()
PreParserIdentifier v8::internal::PreParser::GetNumberAsSymbol () const [inline], [private]
Definition at line 1450 of file preparser.h.
                                                          {
    return PreParserIdentifier::Default();
  }
References v8::internal::PreParserIdentifier::Default().
GetRawNameFromIdentifier()
const AstRawString* v8::internal::PreParser::GetRawNameFromIdentifier (const PreParserIdentifier & arg) [inline], [private]
Definition at line 1394 of file preparser.h.
                                                                               {
    return arg.string_;
  }
References v8::internal::PreParserIdentifier::string_.
GetSymbol()
PreParserIdentifier v8::internal::PreParser::GetSymbol () const [inline], [private]
Definition at line 1440 of file preparser.h.
                                        {
    return PreParserIdentifier::Default();
  }
References v8::internal::PreParserIdentifier::Default().
HasCheckedSyntax()
bool v8::internal::PreParser::HasCheckedSyntax () [inline], [private]
Definition at line 968 of file preparser.h.
{ return false; }
IdentifierEquals()
bool v8::internal::PreParser::IdentifierEquals (const PreParserIdentifier & identifier, const AstRawString * other) [private]
Definition at line 396 of file preparser.cc.
                                                            {
  return identifier.string_ == other;
}
References v8::internal::PreParserIdentifier::string_.
ImportMetaExpression()
PreParserExpression v8::internal::PreParser::ImportMetaExpression (int pos) [inline], [private]
Definition at line 1486 of file preparser.h.
                                                              {
    return PreParserExpression::Default();
  }
References v8::internal::PreParserExpression::Default().
InferFunctionName()
static void v8::internal::PreParser::InferFunctionName () [inline], [static], [private]
Definition at line 1295 of file preparser.h.
{}
InitializeObjectLiteral()
PreParserExpression v8::internal::PreParser::InitializeObjectLiteral (PreParserExpression literal) [inline], [private]
Definition at line 964 of file preparser.h.
                                                                           {
    return literal;
  }
InsertShadowingVarBindingInitializers()
void v8::internal::PreParser::InsertShadowingVarBindingInitializers (PreParserStatement block) [inline], [private]
Definition at line 1376 of file preparser.h.
                                {}
InsertSloppyBlockFunctionVarBindings()
void v8::internal::PreParser::InsertSloppyBlockFunctionVarBindings (DeclarationScope * scope) [inline], [private]
Definition at line 1372 of file preparser.h.
                                                                               {
    scope->HoistSloppyBlockFunctions(nullptr);
  }
References v8::internal::ParserBase< PreParser >::scope().
IsArguments()
bool v8::internal::PreParser::IsArguments (const PreParserIdentifier & identifier) const [inline], [private]
Definition at line 1220 of file preparser.h.
                                                                          {
    return identifier.IsArguments();
  }
References v8::internal::PreParserIdentifier::IsArguments().
IsArrayIndex()
static bool v8::internal::PreParser::IsArrayIndex (const PreParserIdentifier & string, uint32_t * index) [inline], [static], [private]
Definition at line 1274 of file preparser.h.
                                                      {
    return false;
  }
IsAsync()
bool v8::internal::PreParser::IsAsync (const PreParserIdentifier & identifier) const [inline], [private]
Definition at line 1216 of file preparser.h.
                                                                      {
    return identifier.IsAsync();
  }
References v8::internal::PreParserIdentifier::IsAsync().
IsBoilerplateProperty()
static bool v8::internal::PreParser::IsBoilerplateProperty (const PreParserExpression & property) [inline], [static], [private]
Definition at line 1252 of file preparser.h.
                                           {
    // PreParser doesn't count boilerplate properties.
    return false;
  }
IsConstructor()
bool v8::internal::PreParser::IsConstructor (const PreParserIdentifier & identifier) const [inline], [private]
Definition at line 1248 of file preparser.h.
                                                                            {
    return identifier.IsConstructor();
  }
References v8::internal::PreParserIdentifier::IsConstructor().
IsEmptyIdentifier()
bool v8::internal::PreParser::IsEmptyIdentifier (PreParserIdentifier subject) [inline], [private]
Definition at line 1435 of file preparser.h.
                                                                {
    return subject.string_->IsEmpty();
  }
References v8::internal::AstRawString::IsEmpty(), and v8::internal::PreParserIdentifier::string_.
Referenced by DeclareClassVariable().
IsEval()
bool v8::internal::PreParser::IsEval (const PreParserIdentifier & identifier) const [inline], [private]
Definition at line 1212 of file preparser.h.
                                                                     {
    return identifier.IsEval();
  }
References v8::internal::PreParserIdentifier::IsEval().
IsEvalOrArguments()
bool v8::internal::PreParser::IsEvalOrArguments (const PreParserIdentifier & identifier) const [inline], [private]
Definition at line 1224 of file preparser.h.
                                                   {
    return identifier.IsEvalOrArguments();
  }
References v8::internal::PreParserIdentifier::IsEvalOrArguments().
IsIdentifier()
static bool v8::internal::PreParser::IsIdentifier (const PreParserExpression & expression) [inline], [static], [private]
Definition at line 1234 of file preparser.h.
                                                                            {
    return expression.IsIdentifier();
  }
References v8::internal::PreParserExpression::IsIdentifier().
IsIterationStatement()
static bool v8::internal::PreParser::IsIterationStatement (PreParserStatement subject) [inline], [static], [private]
Definition at line 1426 of file preparser.h.
                                                                         {
    return subject.IsIterationStatement();
  }
References v8::internal::PreParserStatement::IsIterationStatement().
IsNative()
bool v8::internal::PreParser::IsNative (const PreParserExpression & expr) const [inline], [private]
Definition at line 1266 of file preparser.h.
                                                                 {
    // Preparsing is disabled for extensions (because the extension
    // details aren't passed to lazily compiled functions), so we
    // don't accept "native function" in the preparser and there is
    // no need to keep track of "native".
    return false;
  }
IsNull()
template<typename T >
static bool v8::internal::PreParser::IsNull (T subject) [inline], [static], [private]
Definition at line 1422 of file preparser.h.
                                          {
    return subject.IsNull();
  }
IsPreParser()
static bool v8::internal::PreParser::IsPreParser () [inline], [static]
Definition at line 889 of file preparser.h.
{ return true; }
IsPrivateReference()
bool v8::internal::PreParser::IsPrivateReference (const PreParserExpression & expression) [inline], [private]
Definition at line 985 of file preparser.h.
                                                                           {
    return expression.IsPrivateReference();
  }
References v8::internal::PreParserExpression::IsPrivateReference().
IsStringLiteral()
bool v8::internal::PreParser::IsStringLiteral (PreParserStatement statement) const [inline], [private]
Definition at line 1279 of file preparser.h.
                                                                     {
    return statement.IsStringLiteral();
  }
References v8::internal::PreParserStatement::IsStringLiteral().
IsThisProperty()
static bool v8::internal::PreParser::IsThisProperty (const PreParserExpression & expression) [inline], [static], [private]
Definition at line 1230 of file preparser.h.
                                                                              {
    return expression.IsThisProperty();
  }
References v8::internal::PreParserExpression::IsThisProperty().
logger()
PreParserLogger* v8::internal::PreParser::logger () [inline]
Definition at line 891 of file preparser.h.
{ return &log_; }
References log_.
Referenced by v8::internal::Parser::SkipFunction().
NewClassLiteralPropertyWithAccessorInfo()
PreParserExpression v8::internal::PreParser::NewClassLiteralPropertyWithAccessorInfo (ClassScope * scope, ClassInfo * class_info, const PreParserIdentifier & name, const PreParserExpression & key, const PreParserExpression & value, bool is_static, bool is_computed_name, bool is_private, int pos) [inline], [private]
Definition at line 1534 of file preparser.h.
                                                                       {
    // Declare the accessor storage name variable and generated getter and
    // setter.
    bool was_added;
    DeclareVariableName(
        AutoAccessorVariableName(ast_value_factory(),
                                 class_info->autoaccessor_count++),
        VariableMode::kConst, scope, &was_added);
    DCHECK(was_added);
    FunctionKind kind = is_static ? FunctionKind::kGetterFunction
                                  : FunctionKind::kStaticGetterFunction;
    AddSyntheticFunctionDeclaration(kind, pos + 1);
    kind = is_static ? FunctionKind::kSetterFunction
                     : FunctionKind::kStaticSetterFunction;
    AddSyntheticFunctionDeclaration(kind, pos + 2);
    return factory()->NewClassLiteralProperty(
        key, value, ClassLiteralProperty::Kind::AUTO_ACCESSOR, is_static,
        is_computed_name, is_private);
  }
References AddSyntheticFunctionDeclaration(), v8::internal::ParserBase< PreParser >::ast_value_factory(), v8::internal::ParserBase< PreParser >::AutoAccessorVariableName(), v8::internal::DCHECK(), DeclareVariableName(), v8::internal::ParserBase< PreParser >::factory(), v8::internal::kConst, v8::internal::key, v8::internal::kGetterFunction, v8::internal::kSetterFunction, v8::internal::kStaticGetterFunction, v8::internal::kStaticSetterFunction, v8::internal::PreParserFactory::NewClassLiteralProperty(), v8::internal::ParserBase< PreParser >::scope(), and v8::internal::value.
NewClassPropertyList()
PreParserPropertyList v8::internal::PreParser::NewClassPropertyList (int size) const [inline], [private]
Definition at line 1522 of file preparser.h.
                                                                       {
    return PreParserPropertyList();
  }
NewClassStaticElementList()
PreParserPropertyList v8::internal::PreParser::NewClassStaticElementList (int size) const [inline], [private]
Definition at line 1526 of file preparser.h.
                                                                            {
    return PreParserPropertyList();
  }
NewStatementList()
PreParserStatementList v8::internal::PreParser::NewStatementList (int size) const [inline], [private]
Definition at line 1530 of file preparser.h.
                                                                    {
    return PreParserStatementList();
  }
NewSuperCallReference()
PreParserExpression v8::internal::PreParser::NewSuperCallReference (int pos) [inline], [private]
Definition at line 1472 of file preparser.h.
                                                               {
    scope()->NewUnresolved(factory()->ast_node_factory(),
                           ast_value_factory()->this_function_string(), pos,
                           NORMAL_VARIABLE);
    scope()->NewUnresolved(factory()->ast_node_factory(),
                           ast_value_factory()->new_target_string(), pos,
                           NORMAL_VARIABLE);
    return PreParserExpression::SuperCallReference();
  }
References v8::internal::ParserBase< PreParser >::ast_value_factory(), v8::internal::ParserBase< PreParser >::factory(), v8::internal::Scope::NewUnresolved(), v8::internal::NORMAL_VARIABLE, v8::internal::ParserBase< PreParser >::scope(), and v8::internal::PreParserExpression::SuperCallReference().
NewSuperPropertyReference()
PreParserExpression v8::internal::PreParser::NewSuperPropertyReference (int pos) [inline], [private]
Definition at line 1468 of file preparser.h.
                                                                   {
    return PreParserExpression::Default();
  }
References v8::internal::PreParserExpression::Default().
NewTargetExpression()
PreParserExpression v8::internal::PreParser::NewTargetExpression (int pos) [inline], [private]
Definition at line 1482 of file preparser.h.
                                                             {
    return PreParserExpression::Default();
  }
References v8::internal::PreParserExpression::Default().
NewThisExpression()
PreParserExpression v8::internal::PreParser::NewThisExpression (int pos) [inline], [private]
Definition at line 1463 of file preparser.h.
                                                           {
    UseThis();
    return PreParserExpression::This();
  }
References v8::internal::PreParserExpression::This(), and v8::internal::ParserBase< PreParser >::UseThis().
NewThrowReferenceError()
PreParserExpression v8::internal::PreParser::NewThrowReferenceError (MessageTemplate message, int pos) [inline], [private]
Definition at line 1379 of file preparser.h.
                                                                {
    return PreParserExpression::Default();
  }
References v8::internal::PreParserExpression::Default().
NewThrowStatement()
PreParserStatement v8::internal::PreParser::NewThrowStatement (const PreParserExpression & exception, int pos) [inline], [private]
Definition at line 1564 of file preparser.h.
                                                                   {
    return PreParserStatement::Jump();
  }
References v8::internal::PreParserStatement::Jump().
NewV8Intrinsic()
PreParserExpression v8::internal::PreParser::NewV8Intrinsic (const PreParserIdentifier & name, const PreParserExpressionList & arguments, int pos) [inline], [private]
Definition at line 1558 of file preparser.h.
                                                                    {
    return PreParserExpression::Default();
  }
References v8::internal::PreParserExpression::Default().
NullBlock()
static PreParserBlock v8::internal::PreParser::NullBlock () [inline], [static], [private]
Definition at line 1419 of file preparser.h.
{ return PreParserBlock::Null(); }
References v8::internal::PreParserBlock::Null().
NullExpression()
static PreParserExpression v8::internal::PreParser::NullExpression () [inline], [static], [private]
Definition at line 1404 of file preparser.h.
                                                        {
    return PreParserExpression::Null();
  }
References v8::internal::PreParserExpression::Null().
NullIdentifier()
static PreParserIdentifier v8::internal::PreParser::NullIdentifier () [inline], [static], [private]
Definition at line 1401 of file preparser.h.
                                                        {
    return PreParserIdentifier::Null();
  }
References v8::internal::PreParserIdentifier::Null().
NullLiteralProperty()
static PreParserExpression v8::internal::PreParser::NullLiteralProperty () [inline], [static], [private]
Definition at line 1410 of file preparser.h.
                                                             {
    return PreParserExpression::Null();
  }
References v8::internal::PreParserExpression::Null().
NullStatement()
static PreParserStatement v8::internal::PreParser::NullStatement () [inline], [static], [private]
Definition at line 1416 of file preparser.h.
                                                      {
    return PreParserStatement::Null();
  }
References v8::internal::PreParserStatement::Null().
NullStatementList()
static PreParserStatementList v8::internal::PreParser::NullStatementList () [inline], [static], [private]
Definition at line 1413 of file preparser.h.
                                                              {
    return PreParserStatementList::Null();
  }
References v8::internal::PreParserStatementList::Null().
OpenTemplateLiteral()
TemplateLiteralState v8::internal::PreParser::OpenTemplateLiteral (int pos) [inline], [private]
Definition at line 974 of file preparser.h.
                                                              {
    return TemplateLiteralState();
  }
parse_lazily()
bool v8::internal::PreParser::parse_lazily () const [inline], [private]
Definition at line 943 of file preparser.h.
{ return false; }
ParseAsyncGeneratorFunctionBody()
void v8::internal::PreParser::ParseAsyncGeneratorFunctionBody (int pos, FunctionKind kind, PreParserScopedStatementList * body) [inline], [private]
Definition at line 1070 of file preparser.h.
                                                                      {
    ParseStatementList(body, Token::kRightBrace);
  }
References v8::internal::ParserBase< PreParser >::ParseStatementList().
ParseFunctionLiteral()
PreParser::Expression v8::internal::PreParser::ParseFunctionLiteral (Identifier name, Scanner::Location function_name_location, FunctionNameValidity function_name_validity, FunctionKind kind, int function_token_pos, FunctionSyntaxKind function_syntax_kind, LanguageMode language_mode, ZonePtrList< const AstRawString > * arguments_for_wrapped_function) [private]
Definition at line 259 of file preparser.cc.
                                                                     {
  FunctionParsingScope function_parsing_scope(this);
  // Wrapped functions are not parsed in the preparser.
  DCHECK_NULL(arguments_for_wrapped_function);
  DCHECK_NE(FunctionSyntaxKind::kWrapped, function_syntax_kind);
  // Function ::
  // '(' FormalParameterList? ')' '{' FunctionBody '}'
  RCS_SCOPE(runtime_call_stats_,
            RuntimeCallCounterId::kPreParseWithVariableResolution,
            RuntimeCallStats::kThreadSpecific);
  base::ElapsedTimer timer;
  if (V8_UNLIKELY(v8_flags.log_function_events)) timer.Start();
  DeclarationScope* function_scope = NewFunctionScope(kind);
  function_scope->SetLanguageMode(language_mode);
  int func_id = GetNextInfoId();
  bool skippable_function = false;
  // Start collecting data for a new function which might contain skippable
  // functions.
  {
    PreparseDataBuilder::DataGatheringScope preparse_data_builder_scope(this);
    skippable_function = !function_state_->next_function_is_likely_called() &&
                         preparse_data_builder_ != nullptr;
    if (skippable_function) {
      preparse_data_builder_scope.Start(function_scope);
    }
    FunctionState function_state(&function_state_, &scope_, function_scope);
    Expect(Token::kLeftParen);
    int start_position = position();
    function_scope->set_start_position(start_position);
    PreParserFormalParameters formals(function_scope);
    {
      ParameterDeclarationParsingScope formals_scope(this);
      ParseFormalParameterList(&formals);
      if (formals_scope.has_duplicate()) formals.set_has_duplicate();
    }
    Expect(Token::kRightParen);
    int formals_end_position = scanner()->location().end_pos;
    CheckArityRestrictions(formals.arity, kind, formals.has_rest,
                           start_position, formals_end_position);
    Expect(Token::kLeftBrace);
    // Parse function body.
    PreParserScopedStatementList body(pointer_buffer());
    int pos = function_token_pos == kNoSourcePosition ? peek_position()
                                                      : function_token_pos;
    AcceptINScope scope(this, true);
    ParseFunctionBody(&body, function_name, pos, formals, kind,
                      function_syntax_kind, FunctionBodyType::kBlock);
    // Parsing the body may change the language mode in our scope.
    language_mode = function_scope->language_mode();
    // Validate name and parameter names. We can do this only after parsing the
    // function, since the function can declare itself strict.
    CheckFunctionName(language_mode, function_name, function_name_validity,
                      function_name_location);
    if (is_strict(language_mode)) {
      CheckStrictOctalLiteral(start_position, end_position());
    }
    if (skippable_function) {
      preparse_data_builder_scope.SetSkippableFunction(
          function_scope, formals.function_length, GetLastInfoId() - func_id);
    }
  }
  if (V8_UNLIKELY(v8_flags.log_function_events)) {
    double ms = timer.Elapsed().InMillisecondsF();
    const char* event_name = "preparse-resolution";
    // We might not always get a function name here. However, it can be easily
    // reconstructed from the script id and the byte range in the log processor.
    const char* name = "";
    size_t name_byte_length = 0;
    bool is_one_byte = true;
    const AstRawString* string = function_name.string_;
    if (string != nullptr) {
      name = reinterpret_cast<const char*>(string->raw_data());
      name_byte_length = string->byte_length();
      is_one_byte = string->is_one_byte();
    }
    v8_file_logger_->FunctionEvent(
        event_name, flags().script_id(), ms, function_scope->start_position(),
        function_scope->end_position(), name, name_byte_length, is_one_byte);
  }
  return Expression::Default();
}
References v8::internal::FormalParametersBase::arity, v8::internal::ParserBase< PreParser >::CheckArityRestrictions(), v8::internal::ParserBase< PreParser >::CheckFunctionName(), v8::internal::ParserBase< PreParser >::CheckStrictOctalLiteral(), DCHECK_NE, DCHECK_NULL, v8::internal::PreParserExpression::Default(), v8::base::ElapsedTimer::Elapsed(), v8::internal::Scanner::Location::end_pos, v8::internal::Scope::end_position(), v8::internal::ParserBase< PreParser >::end_position(), v8::internal::ParserBase< PreParser >::Expect(), v8::internal::ParserBase< PreParser >::flags(), v8::internal::FormalParametersBase::function_length, v8::internal::ParserBase< PreParser >::function_state_, v8::internal::V8FileLogger::FunctionEvent(), v8::internal::ParserBase< PreParser >::GetLastInfoId(), v8::internal::ParserBase< PreParser >::GetNextInfoId(), v8::internal::FormalParametersBase::has_rest, v8::base::TimeDelta::InMillisecondsF(), v8::internal::is_strict(), v8::internal::kNoSourcePosition, v8::internal::kWrapped, v8::internal::ParserBase< PreParser >::language_mode(), v8::internal::Scope::language_mode(), v8::internal::Scanner::location(), v8::internal::name, v8::internal::ParserBase< PreParser >::NewFunctionScope(), v8::internal::ParserBase< PreParser >::ParseFormalParameterList(), v8::internal::ParserBase< PreParser >::ParseFunctionBody(), v8::internal::ParserBase< PreParser >::peek_position(), v8::internal::ParserBase< PreParser >::pointer_buffer(), v8::internal::ParserBase< PreParser >::position(), preparse_data_builder_, RCS_SCOPE, v8::internal::ParserBase< PreParser >::runtime_call_stats_, v8::internal::ParserBase< PreParser >::scanner(), v8::internal::ParserBase< PreParser >::scope(), v8::internal::ParserBase< PreParser >::scope_, v8::internal::UnoptimizedCompileFlags::script_id(), v8::internal::PreParserFormalParameters::set_has_duplicate(), v8::internal::Scope::set_start_position(), v8::internal::Scope::SetLanguageMode(), v8::internal::PreparseDataBuilder::DataGatheringScope::SetSkippableFunction(), v8::base::ElapsedTimer::Start(), v8::internal::PreparseDataBuilder::DataGatheringScope::Start(), v8::internal::Scope::start_position(), v8::internal::PreParserIdentifier::string_, v8::internal::ParserBase< PreParser >::v8_file_logger_, v8::internal::v8_flags, and V8_UNLIKELY.
ParseGeneratorFunctionBody()
void v8::internal::PreParser::ParseGeneratorFunctionBody (int pos, FunctionKind kind, PreParserScopedStatementList * body) [inline], [private]
Definition at line 1066 of file preparser.h.
                                                                      {
    ParseStatementList(body, Token::kRightBrace);
  }
References v8::internal::ParserBase< PreParser >::ParseStatementList().
ParseStatementListAndLogFunction()
void v8::internal::PreParser::ParseStatementListAndLogFunction (PreParserFormalParameters * formals) [private]
Definition at line 359 of file preparser.cc.
                                        {
  PreParserScopedStatementList body(pointer_buffer());
  ParseStatementList(&body, Token::kRightBrace);
  // Position right after terminal '}'.
  DCHECK_IMPLIES(!has_error(), scanner()->peek() == Token::kRightBrace);
  int body_end = scanner()->peek_location().end_pos;
  DCHECK_EQ(this->scope()->is_function_scope(), formals->is_simple);
  log_.LogFunction(body_end, formals->num_parameters(),
                   formals->function_length, GetLastInfoId());
}
References DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Scanner::Location::end_pos, v8::internal::FormalParametersBase::function_length, v8::internal::ParserBase< PreParser >::GetLastInfoId(), v8::internal::ParserBase< PreParser >::has_error(), v8::internal::FormalParametersBase::is_simple, log_, v8::internal::PreParserLogger::LogFunction(), v8::internal::FormalParametersBase::num_parameters(), v8::internal::ParserBase< PreParser >::ParseStatementList(), v8::internal::ParserBase< PreParser >::peek(), v8::internal::Scanner::peek_location(), v8::internal::ParserBase< PreParser >::pointer_buffer(), v8::internal::ParserBase< PreParser >::scanner(), and v8::internal::ParserBase< PreParser >::scope().
Referenced by PreParseFunction().
ParsingDynamicFunctionDeclaration()
bool v8::internal::PreParser::ParsingDynamicFunctionDeclaration () const [inline], [private]
Definition at line 1608 of file preparser.h.
{ return false; }
ParsingExtension()
bool v8::internal::PreParser::ParsingExtension () const [inline], [private]
Definition at line 1258 of file preparser.h.
                                          {
    // Preparsing is disabled for extensions (because the extension
    // details aren't passed to lazily compiled functions), so we
    // don't accept "native function" in the preparser and there is
    // no need to keep track of "native".
    return false;
  }
pending_error_handler()
PendingCompilationErrorHandler* v8::internal::PreParser::pending_error_handler () [inline], [private]
Definition at line 945 of file preparser.h.
                                                          {
    return pending_error_handler_;
  }
References v8::internal::ParserBase< PreParser >::pending_error_handler_.
Referenced by PreParseFunction(), and ReportUnidentifiableError().
PrepareGeneratorVariables()
void v8::internal::PreParser::PrepareGeneratorVariables () [inline], [private]
Definition at line 993 of file preparser.h.
{}
preparse_data_builder()
PreparseDataBuilder* v8::internal::PreParser::preparse_data_builder () const [inline]
Definition at line 912 of file preparser.h.
                                                     {
    return preparse_data_builder_;
  }
References preparse_data_builder_.
Referenced by set_preparse_data_builder(), and v8::internal::PreparseDataBuilder::DataGatheringScope::Start().
preparse_data_builder_buffer()
std::vector<void*>* v8::internal::PreParser::preparse_data_builder_buffer () [inline]
Definition at line 920 of file preparser.h.
                                                   {
    return &preparse_data_builder_buffer_;
  }
Referenced by v8::internal::PreparseDataBuilder::DataGatheringScope::Start().
PreParseFunction()
PreParser::PreParseResult v8::internal::PreParser::PreParseFunction (const AstRawString * function_name, FunctionKind kind, FunctionSyntaxKind function_syntax_kind, DeclarationScope * function_scope, int * use_counts, ProducedPreparseData ** produced_preparser_scope_data)
Definition at line 101 of file preparser.cc.
                                                                    {
  DCHECK_EQ(FUNCTION_SCOPE, function_scope->scope_type());
  use_counts_ = use_counts;
#ifdef DEBUG
  function_scope->set_is_being_lazily_parsed(true);
#endif
  PreParserFormalParameters formals(function_scope);
  // In the preparser, we use the function literal ids to count how many
  // FunctionLiterals were encountered. The PreParser doesn't actually persist
  // FunctionLiterals, so there IDs don't matter.
  ResetInfoId();
  // The caller passes the function_scope which is not yet inserted into the
  // scope stack. All scopes above the function_scope are ignored by the
  // PreParser.
  DCHECK_NULL(function_state_);
  DCHECK_NULL(scope_);
  FunctionState function_state(&function_state_, &scope_, function_scope);
  // Start collecting data for a new function which might contain skippable
  // functions.
  PreparseDataBuilder::DataGatheringScope preparse_data_builder_scope(this);
  if (IsArrowFunction(kind)) {
    formals.is_simple = function_scope->has_simple_parameters();
  } else {
    preparse_data_builder_scope.Start(function_scope);
    // Parse non-arrow function parameters. For arrow functions, the parameters
    // have already been parsed.
    ParameterDeclarationParsingScope formals_scope(this);
    // We return kPreParseSuccess in failure cases too - errors are retrieved
    // separately by Parser::SkipLazyFunctionBody.
    ParseFormalParameterList(&formals);
    if (formals_scope.has_duplicate()) formals.set_has_duplicate();
    if (!formals.is_simple) {
      BuildParameterInitializationBlock(formals);
    }
    Expect(Token::kRightParen);
    int formals_end_position = scanner()->location().end_pos;
    CheckArityRestrictions(formals.arity, kind, formals.has_rest,
                           function_scope->start_position(),
                           formals_end_position);
  }
  Expect(Token::kLeftBrace);
  DeclarationScope* inner_scope = function_scope;
  if (!formals.is_simple) {
    inner_scope = NewVarblockScope();
    inner_scope->set_start_position(position());
  }
  {
    BlockState block_state(&scope_, inner_scope);
    ParseStatementListAndLogFunction(&formals);
  }
  bool allow_duplicate_parameters = false;
  CheckConflictingVarDeclarations(inner_scope);
  if (!has_error()) {
    if (formals.is_simple) {
      if (is_sloppy(function_scope->language_mode())) {
        function_scope->HoistSloppyBlockFunctions(nullptr);
      }
      allow_duplicate_parameters =
          is_sloppy(function_scope->language_mode()) && !IsConciseMethod(kind);
    } else {
      if (is_sloppy(inner_scope->language_mode())) {
        inner_scope->HoistSloppyBlockFunctions(nullptr);
      }
      SetLanguageMode(function_scope, inner_scope->language_mode());
      inner_scope->set_end_position(scanner()->peek_location().end_pos);
      if (inner_scope->FinalizeBlockScope() != nullptr) {
        const AstRawString* conflict = inner_scope->FindVariableDeclaredIn(
            function_scope, VariableMode::kLastLexicalVariableMode);
        if (conflict != nullptr)
          ReportVarRedeclarationIn(conflict, inner_scope);
      }
    }
  }
  use_counts_ = nullptr;
  if (stack_overflow()) {
    return kPreParseStackOverflow;
  } else if (pending_error_handler()->has_error_unidentifiable_by_preparser()) {
    return kPreParseNotIdentifiableError;
  } else if (has_error()) {
    DCHECK(pending_error_handler()->has_pending_error());
  } else {
    DCHECK_EQ(Token::kRightBrace, scanner()->peek());
    if (!IsArrowFunction(kind)) {
      // Validate parameter names. We can do this only after parsing the
      // function, since the function can declare itself strict.
      ValidateFormalParameters(language_mode(), formals,
                               allow_duplicate_parameters);
      if (has_error()) {
        if (pending_error_handler()->has_error_unidentifiable_by_preparser()) {
          return kPreParseNotIdentifiableError;
        } else {
          return kPreParseSuccess;
        }
      }
      // Declare arguments after parsing the function since lexical
      // 'arguments' masks the arguments object. Declare arguments before
      // declaring the function var since the arguments object masks 'function
      // arguments'.
      function_scope->DeclareArguments(ast_value_factory());
      DeclareFunctionNameVar(function_name, function_syntax_kind,
                             function_scope);
      if (preparse_data_builder_->HasData()) {
        *produced_preparse_data =
            ProducedPreparseData::For(preparse_data_builder_, main_zone());
      }
    }
    if (pending_error_handler()->has_error_unidentifiable_by_preparser()) {
      return kPreParseNotIdentifiableError;
    }
    if (is_strict(function_scope->language_mode())) {
      int end_pos = scanner()->location().end_pos;
      CheckStrictOctalLiteral(function_scope->start_position(), end_pos);
    }
  }
  DCHECK(!pending_error_handler()->has_error_unidentifiable_by_preparser());
  return kPreParseSuccess;
}
References v8::internal::FormalParametersBase::arity, v8::internal::ParserBase< PreParser >::ast_value_factory(), BuildParameterInitializationBlock(), v8::internal::ParserBase< PreParser >::CheckArityRestrictions(), v8::internal::ParserBase< PreParser >::CheckConflictingVarDeclarations(), v8::internal::ParserBase< PreParser >::CheckStrictOctalLiteral(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::DeclarationScope::DeclareArguments(), DeclareFunctionNameVar(), v8::internal::Scanner::Location::end_pos, v8::internal::ParserBase< PreParser >::Expect(), v8::internal::Scope::FinalizeBlockScope(), v8::internal::Scope::FindVariableDeclaredIn(), v8::internal::ProducedPreparseData::For(), v8::internal::FUNCTION_SCOPE, v8::internal::ParserBase< PreParser >::function_state_, v8::internal::ParserBase< PreParser >::has_error(), v8::internal::FormalParametersBase::has_rest, v8::internal::DeclarationScope::has_simple_parameters(), v8::internal::PreparseDataBuilder::HasData(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::FormalParametersBase::is_simple, v8::internal::is_sloppy(), v8::internal::is_strict(), v8::internal::IsArrowFunction(), v8::internal::IsConciseMethod(), v8::internal::kLastLexicalVariableMode, kPreParseNotIdentifiableError, kPreParseStackOverflow, kPreParseSuccess, v8::internal::ParserBase< PreParser >::language_mode(), v8::internal::Scope::language_mode(), v8::internal::Scanner::location(), v8::internal::ParserBase< PreParser >::main_zone(), v8::internal::ParserBase< PreParser >::NewVarblockScope(), v8::internal::ParserBase< PreParser >::ParseFormalParameterList(), ParseStatementListAndLogFunction(), v8::internal::ParserBase< PreParser >::peek(), pending_error_handler(), v8::internal::ParserBase< PreParser >::position(), preparse_data_builder_, ReportVarRedeclarationIn(), v8::internal::ParserBase< PreParser >::ResetInfoId(), v8::internal::ParserBase< PreParser >::scanner(), v8::internal::ParserBase< PreParser >::scope_, v8::internal::Scope::scope_type(), v8::internal::Scope::set_end_position(), v8::internal::PreParserFormalParameters::set_has_duplicate(), v8::internal::Scope::set_start_position(), SetLanguageMode(), v8::internal::ParserBase< PreParser >::stack_overflow(), v8::internal::PreparseDataBuilder::DataGatheringScope::Start(), v8::internal::Scope::start_position(), use_counts_, and v8::internal::ParserBase< PreParser >::ValidateFormalParameters().
Referenced by v8::internal::Parser::SkipFunction().
PreParseProgram()
PreParser::PreParseResult v8::internal::PreParser::PreParseProgram ()
Definition at line 67 of file preparser.cc.
                                                   {
  DCHECK_NULL(scope_);
  DeclarationScope* scope = NewScriptScope(REPLMode::kNo);
#ifdef DEBUG
  scope->set_is_being_lazily_parsed(true);
#endif
  // ModuleDeclarationInstantiation for Source Text Module Records creates a
  // new Module Environment Record whose outer lexical environment record is
  // the global scope.
  if (flags().is_module()) scope = NewModuleScope(scope);
  FunctionState top_scope(&function_state_, &scope_, scope);
  original_scope_ = scope_;
  int start_position = peek_position();
  PreParserScopedStatementList body(pointer_buffer());
  ParseStatementList(&body, Token::kEos);
  CheckConflictingVarDeclarations(scope);
  original_scope_ = nullptr;
  if (stack_overflow()) return kPreParseStackOverflow;
  if (is_strict(language_mode())) {
    CheckStrictOctalLiteral(start_position, scanner()->location().end_pos);
  }
  return kPreParseSuccess;
}
References v8::internal::ParserBase< PreParser >::CheckConflictingVarDeclarations(), v8::internal::ParserBase< PreParser >::CheckStrictOctalLiteral(), DCHECK_NULL, v8::internal::ParserBase< PreParser >::flags(), v8::internal::ParserBase< PreParser >::function_state_, v8::internal::is_strict(), v8::internal::kNo, kPreParseStackOverflow, kPreParseSuccess, v8::internal::ParserBase< PreParser >::language_mode(), v8::internal::ParserBase< PreParser >::NewModuleScope(), v8::internal::ParserBase< PreParser >::NewScriptScope(), v8::internal::ParserBase< PreParser >::original_scope_, v8::internal::ParserBase< PreParser >::ParseStatementList(), v8::internal::ParserBase< PreParser >::peek_position(), v8::internal::ParserBase< PreParser >::pointer_buffer(), v8::internal::ParserBase< PreParser >::scanner(), v8::internal::ParserBase< PreParser >::scope(), v8::internal::ParserBase< PreParser >::scope_, and v8::internal::ParserBase< PreParser >::stack_overflow().
PreParserIdentifierToAstRawString()
const AstRawString* v8::internal::PreParser::PreParserIdentifierToAstRawString (const PreParserIdentifier & x) [inline], [private]
Definition at line 1384 of file preparser.h.
                                    {
    return x.string_;
  }
References v8::internal::PreParserIdentifier::string_.
PushEnclosingName()
void v8::internal::PreParser::PushEnclosingName (const PreParserIdentifier & name) [inline], [private]
Definition at line 1292 of file preparser.h.
{}
PushLiteralName()
static void v8::internal::PreParser::PushLiteralName (const PreParserIdentifier & id) [inline], [static], [private]
Definition at line 1289 of file preparser.h.
{}
PushPropertyName()
void v8::internal::PreParser::PushPropertyName (const PreParserExpression & expression) [inline], [private]
Definition at line 1291 of file preparser.h.
{}
PushVariableName()
static void v8::internal::PreParser::PushVariableName (const PreParserIdentifier & id) [inline], [static], [private]
Definition at line 1290 of file preparser.h.
{}
ReindexArrowFunctionFormalParameters()
void v8::internal::PreParser::ReindexArrowFunctionFormalParameters (PreParserFormalParameters * parameters) [inline], [private]
Definition at line 1578 of file preparser.h.
                                             {}
ReindexComputedMemberName()
void v8::internal::PreParser::ReindexComputedMemberName (const PreParserExpression & expression) [inline], [private]
Definition at line 1580 of file preparser.h.
                                             {}
ReportUnexpectedTokenAt()
void v8::internal::PreParser::ReportUnexpectedTokenAt (Scanner::Location location, Token::Value token, MessageTemplate message = MessageTemplate::kUnexpectedToken) [inline], [private]
Definition at line 1061 of file preparser.h.
                                                                 {
    ReportUnidentifiableError();
  }
References ReportUnidentifiableError().
ReportUnidentifiableError()
void v8::internal::PreParser::ReportUnidentifiableError () [inline], [private]
Definition at line 1389 of file preparser.h.
                                             {
    pending_error_handler()->set_unidentifiable_error();
    scanner()->set_parser_error();
  }
References pending_error_handler(), v8::internal::ParserBase< PreParser >::scanner(), v8::internal::Scanner::set_parser_error(), and v8::internal::PendingCompilationErrorHandler::set_unidentifiable_error().
Referenced by DeclareVariableName(), ReportUnexpectedTokenAt(), ReportVarRedeclarationIn(), v8::internal::PreParserFormalParameters::ValidateDuplicate(), and v8::internal::PreParserFormalParameters::ValidateStrictMode().
ReportVarRedeclarationIn()
void v8::internal::PreParser::ReportVarRedeclarationIn (const AstRawString * name, Scope * scope) [inline], [private]
Definition at line 1049 of file preparser.h.
                                                        {
    ReportUnidentifiableError();
  }
References ReportUnidentifiableError().
Referenced by PreParseFunction().
RewriteCatchPattern()
PreParserBlock v8::internal::PreParser::RewriteCatchPattern (CatchInfo * catch_info) [inline], [private]
Definition at line 1045 of file preparser.h.
                                                                      {
    return PreParserBlock::Default();
  }
References v8::internal::PreParserBlock::Default().
RewriteClassLiteral()
PreParserExpression v8::internal::PreParser::RewriteClassLiteral (ClassScope * scope, const PreParserIdentifier & name, ClassInfo * class_info, int pos) [inline], [private]
Definition at line 1193 of file preparser.h.
                                                      {
    bool has_default_constructor = !class_info->has_seen_constructor;
    // Account for the default constructor.
    if (has_default_constructor) {
      bool has_extends = class_info->extends.IsNull();
      FunctionKind kind = has_extends ? FunctionKind::kDefaultDerivedConstructor
                                      : FunctionKind::kDefaultBaseConstructor;
      AddSyntheticFunctionDeclaration(kind, pos);
    }
    return PreParserExpression::Default();
  }
References AddSyntheticFunctionDeclaration(), v8::internal::PreParserExpression::Default(), v8::internal::PreParserExpression::IsNull(), v8::internal::kDefaultBaseConstructor, and v8::internal::kDefaultDerivedConstructor.
RewriteForVarInLegacy()
PreParserBlock v8::internal::PreParser::RewriteForVarInLegacy (const ForInfo & for_info) [inline], [private]
Definition at line 1335 of file preparser.h.
                                                                          {
    return PreParserBlock::Null();
  }
References v8::internal::PreParserBlock::Null().
RewriteSwitchStatement()
PreParserStatement v8::internal::PreParser::RewriteSwitchStatement (PreParserStatement switch_statement, Scope * scope) [inline], [private]
Definition at line 996 of file preparser.h.
                                                                            {
    return PreParserStatement::Default();
  }
References v8::internal::PreParserStatement::Default().
RewriteTryStatement()
PreParserStatement v8::internal::PreParser::RewriteTryStatement (PreParserStatement try_block, PreParserStatement catch_block, const SourceRange & catch_range, PreParserStatement finally_block, const SourceRange & finally_range, const CatchInfo & catch_info, int pos) [inline], [private]
Definition at line 1054 of file preparser.h.
                                                                              {
    return PreParserStatement::Default();
  }
References v8::internal::PreParserStatement::Default().
set_preparse_data_builder()
void v8::internal::PreParser::set_preparse_data_builder (PreparseDataBuilder * preparse_data_builder) [inline]
Definition at line 916 of file preparser.h.
                                                                             {
    preparse_data_builder_ = preparse_data_builder;
  }
References preparse_data_builder(), and preparse_data_builder_.
Referenced by v8::internal::PreparseDataBuilder::DataGatheringScope::Start().
SetAsmModule()
void v8::internal::PreParser::SetAsmModule () [inline], [private]
Definition at line 991 of file preparser.h.
{}
SetFunctionNameFromIdentifierRef()
void v8::internal::PreParser::SetFunctionNameFromIdentifierRef (const PreParserExpression & value, const PreParserExpression & identifier) [inline], [private]
Definition at line 1600 of file preparser.h.
                                                                               {
  }
SetFunctionNameFromPropertyName()
void v8::internal::PreParser::SetFunctionNameFromPropertyName (const PreParserExpression & property, const PreParserIdentifier & name, const AstRawString * prefix = nullptr) [inline], [private]
Definition at line 1597 of file preparser.h.
                                            {}
SetLanguageMode()
void v8::internal::PreParser::SetLanguageMode (Scope * scope, LanguageMode mode) [inline], [private]
Definition at line 988 of file preparser.h.
                                                                  {
    scope->SetLanguageMode(mode);
  }
References mode(), v8::internal::ParserBase< PreParser >::scope(), and v8::internal::Scope::SetLanguageMode().
Referenced by AddSyntheticFunctionDeclaration(), and PreParseFunction().
ShortcutLiteralBinaryExpression()
bool v8::internal::PreParser::ShortcutLiteralBinaryExpression (PreParserExpression * x, const PreParserExpression & y, Token::Value op, int pos) [inline], [private]
Definition at line 1300 of file preparser.h.
                                                                         {
    return false;
  }
SkipFunction()
bool v8::internal::PreParser::SkipFunction (const AstRawString * name, FunctionKind kind, FunctionSyntaxKind function_syntax_kind, DeclarationScope * function_scope, int * num_parameters, int * function_length, ProducedPreparseData ** produced_preparse_data) [inline], [private]
Definition at line 949 of file preparser.h.
                                                                             {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
ThisExpression()
PreParserExpression v8::internal::PreParser::ThisExpression () [inline], [private]
Definition at line 1458 of file preparser.h.
                                                 {
    UseThis();
    return PreParserExpression::This();
  }
References v8::internal::PreParserExpression::This(), and v8::internal::ParserBase< PreParser >::UseThis().
Friends And Related Function Documentation
i::ArrowHeadParsingScope< ParserTypes< PreParser > >
friend class i::ArrowHeadParsingScope< ParserTypes< PreParser > > [friend]
Definition at line 920 of file preparser.h.
i::ExpressionScope< ParserTypes< PreParser > >
friend class i::ExpressionScope< ParserTypes< PreParser > > [friend]
Definition at line 920 of file preparser.h.
i::ParameterDeclarationParsingScope< ParserTypes< PreParser > >
friend class i::ParameterDeclarationParsingScope< ParserTypes< PreParser > > [friend]
Definition at line 920 of file preparser.h.
i::VariableDeclarationParsingScope< ParserTypes< PreParser > >
friend class i::VariableDeclarationParsingScope< ParserTypes< PreParser > > [friend]
Definition at line 920 of file preparser.h.
ParserBase< PreParser >
friend class ParserBase< PreParser > [friend]
Definition at line 803 of file preparser.h.
PreParserFormalParameters
friend class PreParserFormalParameters [friend]
Definition at line 929 of file preparser.h.
Member Data Documentation
log_
PreParserLogger v8::internal::PreParser::log_ [private]
Definition at line 1626 of file preparser.h.
Referenced by logger(), and ParseStatementListAndLogFunction().
preparse_data_builder_
PreparseDataBuilder* v8::internal::PreParser::preparse_data_builder_ [private]
Definition at line 1628 of file preparser.h.
Referenced by BuildParameterInitializationBlock(), ParseFunctionLiteral(), preparse_data_builder(), PreParseFunction(), and set_preparse_data_builder().
preparse_data_builder_buffer_
std::vector<void*> v8::internal::PreParser::preparse_data_builder_buffer_ [private]
Definition at line 1629 of file preparser.h.
Referenced by PreParser().
use_counts_
int* v8::internal::PreParser::use_counts_ [private]
Definition at line 1625 of file preparser.h.
Referenced by CountUsage(), and PreParseFunction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparser.h
/mnt/V8SourceCode/src/parsing/preparser.cc