v8::internal::ScopeIterator Class Reference
#include <debug-scopes.h>
Public Types
enum ScopeType {
ScopeTypeGlobal = 0
, ScopeTypeLocal
, ScopeTypeWith
, ScopeTypeClosure
,
ScopeTypeCatch
, ScopeTypeBlock
, ScopeTypeScript
, ScopeTypeEval
,
ScopeTypeModule
 }
enum class ReparseStrategy { kFunctionLiteral
, kScriptIfNeeded
 }
enum class Mode { STACK
, ALL
 }
Public Member Functions
ScopeIterator (Isolate *isolate, FrameInspector *frame_inspector, ReparseStrategy strategy)
ScopeIterator (Isolate *isolate, DirectHandle< JSFunction > function)
ScopeIterator (Isolate *isolate, Handle< JSGeneratorObject > generator)
~ScopeIterator ()
DirectHandle< JSObject > MaterializeScopeDetails ()
bool Done () const
void Next ()
void Restart ()
ScopeType Type () const
Handle< JSObject > ScopeObject (Mode mode)
bool DeclaresLocals (Mode mode) const
bool SetVariableValue (Handle< String > variable_name, DirectHandle< Object > new_value)
bool ClosureScopeHasThisReference () const
DirectHandle< StringSet > GetLocals ()
DirectHandle< Object > GetFunctionDebugName () const
DirectHandle< Script > GetScript () const
bool HasPositionInfo ()
int start_position ()
int end_position ()
bool InInnerScope () const
bool HasContext () const
bool NeedsContext () const
bool NeedsAndHasContext () const
Handle< Context > CurrentContext () const
Static Public Attributes
static const int kScopeDetailsTypeIndex = 0
static const int kScopeDetailsObjectIndex = 1
static const int kScopeDetailsNameIndex = 2
static const int kScopeDetailsStartPositionIndex = 3
static const int kScopeDetailsEndPositionIndex = 4
static const int kScopeDetailsFunctionIndex = 5
static const int kScopeDetailsSize = 6
Private Types
using Visitor = std::function< bool(Handle< String > name, Handle< Object > value, ScopeType scope_type)>
Private Member Functions
JavaScriptFrame * GetFrame () const
bool AdvanceOneScope ()
void AdvanceOneContext ()
void AdvanceScope ()
void AdvanceContext ()
void CollectLocalsFromCurrentScope ()
void MaybeCollectAndStoreLocalBlocklists () const
int GetSourcePosition () const
void TryParseAndRetrieveScopes (ReparseStrategy strategy)
void UnwrapEvaluationContext ()
Handle< JSObject > WithContextExtension ()
bool SetLocalVariableValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value)
bool SetContextVariableValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value)
bool SetContextExtensionValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value)
bool SetScriptVariableValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value)
bool SetModuleVariableValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value)
void VisitScope (const Visitor &visitor, Mode mode) const
void VisitLocalScope (const Visitor &visitor, Mode mode, ScopeType scope_type) const
void VisitScriptScope (const Visitor &visitor) const
void VisitModuleScope (const Visitor &visitor) const
bool VisitLocals (const Visitor &visitor, Mode mode, ScopeType scope_type) const
bool VisitContextLocals (const Visitor &visitor, DirectHandle< ScopeInfo > scope_info, DirectHandle< Context > context, ScopeType scope_type) const
DISALLOW_IMPLICIT_CONSTRUCTORS (ScopeIterator)
Private Attributes
Isolate * isolate_
std::unique_ptr< ReusableUnoptimizedCompileState > reusable_compile_state_
std::unique_ptr< ParseInfo > info_
FrameInspector *const frame_inspector_ = nullptr
Handle< JSGeneratorObject > generator_
Handle< JSFunction > function_
Handle< Context > context_
Handle< Script > script_
Handle< StringSet > locals_
DeclarationScope * closure_scope_ = nullptr
Scope * start_scope_ = nullptr
Scope * current_scope_ = nullptr
bool seen_script_scope_ = false
bool calculate_blocklists_ = false
Detailed Description
Definition at line 21 of file debug-scopes.h.
Member Typedef Documentation
Visitor
using v8::internal::ScopeIterator::Visitor = std::function<bool(Handle<String> name, Handle<Object> value, ScopeType scope_type)> [private]
Definition at line 159 of file debug-scopes.h.
Member Enumeration Documentation
Mode
enum v8::internal::ScopeIterator::Mode [strong]
Enumerator
STACK
ALL
Definition at line 74 of file debug-scopes.h.
{ STACK, ALL };
ReparseStrategy
enum v8::internal::ScopeIterator::ReparseStrategy [strong]
Enumerator
kFunctionLiteral
kScriptIfNeeded
Definition at line 43 of file debug-scopes.h.
                             {
    kFunctionLiteral,
    // Checks whether the paused function (and its scope chain) already has
    // its blocklist calculated and re-parses the whole script if not.
    // Otherwise only the function literal is re-parsed.
    kScriptIfNeeded,
  };
ScopeType
enum v8::internal::ScopeIterator::ScopeType
Enumerator
ScopeTypeGlobal
ScopeTypeLocal
ScopeTypeWith
ScopeTypeClosure
ScopeTypeCatch
ScopeTypeBlock
ScopeTypeScript
ScopeTypeEval
ScopeTypeModule
Definition at line 23 of file debug-scopes.h.
                 {
    ScopeTypeGlobal = 0,
    ScopeTypeLocal,
    ScopeTypeWith,
    ScopeTypeClosure,
    ScopeTypeCatch,
    ScopeTypeBlock,
    ScopeTypeScript,
    ScopeTypeEval,
    ScopeTypeModule
  };
Constructor & Destructor Documentation
ScopeIterator() [1/3]
v8::internal::ScopeIterator::ScopeIterator (Isolate * isolate, FrameInspector * frame_inspector, ReparseStrategy strategy)
Definition at line 23 of file debug-scopes.cc.
    : isolate_(isolate),
      frame_inspector_(frame_inspector),
      function_(frame_inspector_->GetFunction()),
      script_(frame_inspector_->GetScript()),
      locals_(StringSet::New(isolate)) {
  if (!IsContext(*frame_inspector->GetContext())) {
    // Optimized frame, context or function cannot be materialized. Give up.
    return;
  }
  context_ = Cast<Context>(frame_inspector->GetContext());
#if V8_ENABLE_WEBASSEMBLY
  // We should not instantiate a ScopeIterator for wasm frames.
  DCHECK_NE(Script::Type::kWasm, frame_inspector->GetScript()->type());
#endif // V8_ENABLE_WEBASSEMBLY
  TryParseAndRetrieveScopes(strategy);
}
References context_, DCHECK_NE, v8::internal::FrameInspector::GetContext(), v8::internal::FrameInspector::GetScript(), and TryParseAndRetrieveScopes().
ScopeIterator() [2/3]
v8::internal::ScopeIterator::ScopeIterator (Isolate * isolate, DirectHandle< JSFunction > function)
Definition at line 60 of file debug-scopes.cc.
    : isolate_(isolate),
      context_(function->context(), isolate),
      locals_(StringSet::New(isolate)) {
  if (!function->shared()->IsSubjectToDebugging()) {
    context_ = Handle<Context>();
    return;
  }
  script_ = handle(Cast<Script>(function->shared()->script()), isolate);
  UnwrapEvaluationContext();
}
References context_, v8::internal::handle(), script_, and UnwrapEvaluationContext().
ScopeIterator() [3/3]
v8::internal::ScopeIterator::ScopeIterator (Isolate * isolate, Handle< JSGeneratorObject > generator)
Definition at line 73 of file debug-scopes.cc.
    : isolate_(isolate),
      generator_(generator),
      function_(generator->function(), isolate),
      context_(generator->context(), isolate),
      script_(Cast<Script>(function_->shared()->script()), isolate),
      locals_(StringSet::New(isolate)) {
  CHECK(function_->shared()->IsSubjectToDebugging());
  TryParseAndRetrieveScopes(ReparseStrategy::kFunctionLiteral);
}
References CHECK, function_, kFunctionLiteral, and TryParseAndRetrieveScopes().
 ScopeIterator()
v8::internal::ScopeIterator::~ScopeIterator () [default]
Member Function Documentation
AdvanceContext()
void v8::internal::ScopeIterator::AdvanceContext () [private]
Definition at line 499 of file debug-scopes.cc.
                                   {
  AdvanceOneContext();
  // While advancing one context, we need to advance at least one
  // scope, but until we hit the next scope that actually requires
  // a context. All the locals collected along the way build the
  // blocklist for debug-evaluate for this context.
  while (AdvanceOneScope() && !NeedsContext()) {
  }
}
References AdvanceOneContext(), AdvanceOneScope(), and NeedsContext().
Referenced by Next().
AdvanceOneContext()
void v8::internal::ScopeIterator::AdvanceOneContext () [private]
Definition at line 475 of file debug-scopes.cc.
                                      {
  DCHECK(!IsNativeContext(*context_));
  DCHECK(!context_->previous().is_null());
  context_ = handle(context_->previous(), isolate_);
  // The locals blocklist is always associated with a context. So when we
  // move one context up, we also reset the locals_ blocklist.
  locals_ = StringSet::New(isolate_);
}
References context_, v8::internal::DCHECK(), v8::internal::handle(), isolate_, locals_, and v8::internal::StringSet::New().
Referenced by AdvanceContext(), and AdvanceScope().
AdvanceOneScope()
bool v8::internal::ScopeIterator::AdvanceOneScope () [private]
Definition at line 467 of file debug-scopes.cc.
                                    {
  if (!current_scope_ || !current_scope_->outer_scope()) return false;
  current_scope_ = current_scope_->outer_scope();
  CollectLocalsFromCurrentScope();
  return true;
}
References CollectLocalsFromCurrentScope(), current_scope_, and v8::internal::Scope::outer_scope().
Referenced by AdvanceContext(), AdvanceScope(), and Next().
AdvanceScope()
void v8::internal::ScopeIterator::AdvanceScope () [private]
Definition at line 485 of file debug-scopes.cc.
                                 {
  DCHECK(InInnerScope());
  do {
    if (NeedsAndHasContext()) {
      // current_scope_ needs a context so moving one scope up requires us to
      // also move up one context.
      AdvanceOneContext();
    }
    CHECK(AdvanceOneScope());
  } while (current_scope_->is_hidden());
}
References AdvanceOneContext(), AdvanceOneScope(), CHECK, current_scope_, v8::internal::DCHECK(), InInnerScope(), v8::internal::Scope::is_hidden(), and NeedsAndHasContext().
Referenced by Next().
ClosureScopeHasThisReference()
bool v8::internal::ScopeIterator::ClosureScopeHasThisReference () const
Definition at line 734 of file debug-scopes.cc.
                                                       {
  // closure_scope_ can be nullptr if parsing failed. See the TODO in
  // TryParseAndRetrieveScopes.
  return closure_scope_ && !closure_scope_->has_this_declaration() &&
         closure_scope_->HasThisReference();
}
References closure_scope_, v8::internal::DeclarationScope::has_this_declaration(), and v8::internal::Scope::HasThisReference().
Referenced by v8::internal::DebugStackTraceIterator::GetReceiver().
CollectLocalsFromCurrentScope()
void v8::internal::ScopeIterator::CollectLocalsFromCurrentScope () [private]
Definition at line 741 of file debug-scopes.cc.
                                                  {
  DCHECK(IsStringSet(*locals_));
  for (Variable* var : *current_scope_->locals()) {
    if (var->location() == VariableLocation::PARAMETER ||
        var->location() == VariableLocation::LOCAL) {
      locals_ = StringSet::Add(isolate_, locals_, var->name());
    }
  }
}
References v8::internal::StringSet::Add(), current_scope_, v8::internal::DCHECK(), isolate_, v8::internal::LOCAL, v8::internal::Scope::locals(), locals_, and v8::internal::PARAMETER.
Referenced by AdvanceOneScope().
CurrentContext()
Handle<Context> v8::internal::ScopeIterator::CurrentContext () const [inline]
Definition at line 110 of file debug-scopes.h.
                                         {
    DCHECK(HasContext());
    return context_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder().
DeclaresLocals()
bool v8::internal::ScopeIterator::DeclaresLocals (Mode mode) const
Definition at line 417 of file debug-scopes.cc.
                                                  {
  ScopeType type = Type();
  if (type == ScopeTypeWith) return mode == Mode::ALL;
  if (type == ScopeTypeGlobal) return mode == Mode::ALL;
  bool declares_local = false;
  auto visitor = [&](DirectHandle<String> name, DirectHandle<Object> value,
                     ScopeType scope_type) {
    declares_local = true;
    return true;
  };
  VisitScope(visitor, mode);
  return declares_local;
}
References ALL, mode(), v8::internal::name, ScopeTypeGlobal, ScopeTypeWith, Type(), v8::internal::tracing::type, v8::internal::value, and VisitScope().
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), and v8::internal::DebugScopeIterator::ShouldIgnore().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::ScopeIterator::DISALLOW_IMPLICIT_CONSTRUCTORS (ScopeIterator) [private]
Done()
bool v8::internal::ScopeIterator::Done () const [inline]
Definition at line 61 of file debug-scopes.h.
{ return context_.is_null(); }
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), v8::internal::DebugScopeIterator::Done(), Next(), v8::internal::RUNTIME_FUNCTION(), ScopeObject(), v8::internal::SetScopeVariableValue(), SetVariableValue(), and Type().
end_position()
int v8::internal::ScopeIterator::end_position ()
Definition at line 411 of file debug-scopes.cc.
                                {
  if (InInnerScope()) return current_scope_->end_position();
  if (IsNativeContext(*context_)) return 0;
  return context_->closure_context()->scope_info()->EndPosition();
}
References context_, current_scope_, v8::internal::Scope::end_position(), and InInnerScope().
Referenced by v8::internal::DebugScopeIterator::GetEndLocation(), and MaterializeScopeDetails().
GetFrame()
JavaScriptFrame* v8::internal::ScopeIterator::GetFrame () const [inline], [private]
Definition at line 135 of file debug-scopes.h.
                                           {
    return frame_inspector_->javascript_frame();
  }
References v8::internal::FrameInspector::javascript_frame().
Referenced by SetLocalVariableValue(), TryParseAndRetrieveScopes(), and VisitLocalScope().
GetFunctionDebugName()
DirectHandle< Object > v8::internal::ScopeIterator::GetFunctionDebugName () const
Definition at line 46 of file debug-scopes.cc.
                                                               {
  if (!function_.is_null())
    return JSFunction::GetDebugName(isolate_, function_);
  if (!IsNativeContext(*context_)) {
    DisallowGarbageCollection no_gc;
    Tagged<ScopeInfo> closure_info = context_->closure_context()->scope_info();
    DirectHandle<String> debug_name(closure_info->FunctionDebugName(),
                                    isolate_);
    if (debug_name->length() > 0) return debug_name;
  }
  return isolate_->factory()->undefined_value();
}
References context_, v8::internal::Isolate::factory(), function_, v8::internal::JSFunction::GetDebugName(), isolate_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::DebugScopeIterator::GetFunctionDebugName(), and MaterializeScopeDetails().
GetLocals()
DirectHandle<StringSet> v8::internal::ScopeIterator::GetLocals () [inline]
Definition at line 89 of file debug-scopes.h.
{ return locals_; }
GetScript()
DirectHandle<Script> v8::internal::ScopeIterator::GetScript () const [inline]
Definition at line 95 of file debug-scopes.h.
{ return script_; }
Referenced by v8::internal::DebugScopeIterator::GetEndLocation(), v8::internal::DebugScopeIterator::GetScriptId(), and v8::internal::DebugScopeIterator::GetStartLocation().
GetSourcePosition()
int v8::internal::ScopeIterator::GetSourcePosition () const [private]
Definition at line 808 of file debug-scopes.cc.
                                           {
  if (frame_inspector_) {
    return frame_inspector_->GetSourcePosition();
  } else {
    DCHECK(!generator_.is_null());
    SharedFunctionInfo::EnsureSourcePositionsAvailable(
        isolate_, direct_handle(generator_->function()->shared(), isolate_));
    return generator_->source_position();
  }
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), frame_inspector_, generator_, v8::internal::FrameInspector::GetSourcePosition(), and isolate_.
Referenced by TryParseAndRetrieveScopes(), and VisitLocals().
HasContext()
bool v8::internal::ScopeIterator::HasContext () const
Definition at line 433 of file debug-scopes.cc.
                                     {
  // In rare cases we pause in a scope that doesn't have its context pushed yet.
  // E.g. when pausing in for-of loop headers (see https://crbug.com/399002824).
  //
  // We can detect this by comparing the scope ID of the parsed scope and the
  // runtime scope.
  if (current_scope_ && NeedsContext() &&
      current_scope_->UniqueIdInScript() !=
          context_->scope_info()->UniqueIdInScript()) {
    return false;
  }
  return !InInnerScope() || NeedsContext();
}
References context_, current_scope_, InInnerScope(), NeedsContext(), and v8::internal::Scope::UniqueIdInScript().
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), MaterializeScopeDetails(), VisitLocals(), and VisitLocalScope().
HasPositionInfo()
bool v8::internal::ScopeIterator::HasPositionInfo ()
Definition at line 401 of file debug-scopes.cc.
                                    {
  return InInnerScope() || !IsNativeContext(*context_);
}
References context_, and InInnerScope().
Referenced by v8::internal::DebugScopeIterator::HasLocationInfo().
InInnerScope()
bool v8::internal::ScopeIterator::InInnerScope () const [inline]
Definition at line 106 of file debug-scopes.h.
{ return !function_.is_null(); }
Referenced by AdvanceScope(), v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), end_position(), HasContext(), HasPositionInfo(), MaterializeScopeDetails(), Next(), SetVariableValue(), start_position(), Type(), VisitLocalScope(), and VisitScope().
MaterializeScopeDetails()
DirectHandle< JSObject > v8::internal::ScopeIterator::MaterializeScopeDetails ()
Definition at line 378 of file debug-scopes.cc.
                                                              {
  // Calculate the size of the result.
  DirectHandle<FixedArray> details =
      isolate_->factory()->NewFixedArray(kScopeDetailsSize);
  // Fill in scope details.
  details->set(kScopeDetailsTypeIndex, Smi::FromInt(Type()));
  DirectHandle<JSObject> scope_object = ScopeObject(Mode::ALL);
  details->set(kScopeDetailsObjectIndex, *scope_object);
  if (Type() == ScopeTypeGlobal || Type() == ScopeTypeScript) {
    return isolate_->factory()->NewJSArrayWithElements(details);
  } else if (HasContext()) {
    DirectHandle<Object> closure_name = GetFunctionDebugName();
    details->set(kScopeDetailsNameIndex, *closure_name);
    details->set(kScopeDetailsStartPositionIndex,
                 Smi::FromInt(start_position()));
    details->set(kScopeDetailsEndPositionIndex, Smi::FromInt(end_position()));
    if (InInnerScope()) {
      details->set(kScopeDetailsFunctionIndex, *function_);
    }
  }
  return isolate_->factory()->NewJSArrayWithElements(details);
}
References ALL, end_position(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), function_, GetFunctionDebugName(), HasContext(), InInnerScope(), isolate_, kScopeDetailsEndPositionIndex, kScopeDetailsFunctionIndex, kScopeDetailsNameIndex, kScopeDetailsObjectIndex, kScopeDetailsSize, kScopeDetailsStartPositionIndex, kScopeDetailsTypeIndex, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), ScopeObject(), ScopeTypeGlobal, ScopeTypeScript, start_position(), and Type().
Referenced by v8::internal::RUNTIME_FUNCTION().
MaybeCollectAndStoreLocalBlocklists()
void v8::internal::ScopeIterator::MaybeCollectAndStoreLocalBlocklists () const [private]
Definition at line 1378 of file debug-scopes.cc.
                                                              {
  if (!calculate_blocklists_ || current_scope_ != closure_scope_ ||
      Type() == ScopeTypeScript) {
    return;
  }
  DCHECK(IsTheHole(isolate_->LocalsBlockListCacheGet(
      direct_handle(function_->shared()->scope_info(), isolate_))));
  LocalBlocklistsCollector collector(isolate_, script_, context_,
                                     closure_scope_);
  collector.CollectAndStore();
}
References v8::internal::DCHECK(), and v8::internal::direct_handle().
Referenced by Next(), and TryParseAndRetrieveScopes().
NeedsAndHasContext()
bool v8::internal::ScopeIterator::NeedsAndHasContext () const [inline]
Definition at line 109 of file debug-scopes.h.
{ return NeedsContext() && HasContext(); }
Referenced by AdvanceScope(), Next(), and Type().
NeedsContext()
bool v8::internal::ScopeIterator::NeedsContext () const
Definition at line 448 of file debug-scopes.cc.
                                       {
  const bool needs_context = current_scope_->NeedsContext();
  // We try very hard to ensure that a function's context is already
  // available when we pause right at the beginning of that function.
  // This can be tricky when we pause via stack check or via
  // `BreakOnNextFunctionCall`, which happens normally in the middle of frame
  // construction and we have to "step into" the function first.
  //
  // We check this by ensuring that the current context is not the closure
  // context should the function need one. In that case the function has already
  // pushed the context and we are good.
  CHECK_IMPLIES(needs_context && current_scope_ == closure_scope_ &&
                    current_scope_->is_function_scope() && !function_.is_null(),
                function_->context() != *context_);
  return needs_context;
}
References CHECK_IMPLIES, closure_scope_, context_, current_scope_, function_, v8::internal::Scope::is_function_scope(), and v8::internal::Scope::NeedsContext().
Referenced by AdvanceContext(), HasContext(), Next(), and SetVariableValue().
Next()
void v8::internal::ScopeIterator::Next ()
Definition at line 510 of file debug-scopes.cc.
                         {
  DCHECK(!Done());
  ScopeType scope_type = Type();
  if (scope_type == ScopeTypeGlobal) {
    // The global scope is always the last in the chain.
    DCHECK(IsNativeContext(*context_));
    context_ = Handle<Context>();
    DCHECK(Done());
    return;
  }
  bool leaving_closure = current_scope_ == closure_scope_;
  if (scope_type == ScopeTypeScript) {
    DCHECK_IMPLIES(InInnerScope() && !leaving_closure,
                   current_scope_->is_script_scope());
    seen_script_scope_ = true;
    if (context_->IsScriptContext()) {
      context_ = handle(context_->previous(), isolate_);
    }
  } else if (!InInnerScope()) {
    AdvanceContext();
  } else {
    DCHECK_NOT_NULL(current_scope_);
    AdvanceScope();
    if (leaving_closure) {
      DCHECK(current_scope_ != closure_scope_);
      // If the current_scope_ doesn't need a context, we advance the scopes
      // and collect the blocklist along the way until we find the scope
      // that should match `context_`.
      // But only do this if we have complete scope information.
      while (!NeedsContext() && AdvanceOneScope()) {
      }
    }
  }
  MaybeCollectAndStoreLocalBlocklists();
  UnwrapEvaluationContext();
  DCHECK_IMPLIES(current_scope_ && NeedsAndHasContext(),
                 current_scope_->UniqueIdInScript() ==
                     context_->scope_info()->UniqueIdInScript());
  if (leaving_closure) function_ = Handle<JSFunction>();
}
References AdvanceContext(), AdvanceOneScope(), AdvanceScope(), closure_scope_, context_, current_scope_, v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NOT_NULL, Done(), function_, v8::internal::handle(), InInnerScope(), v8::internal::Scope::is_script_scope(), isolate_, MaybeCollectAndStoreLocalBlocklists(), NeedsAndHasContext(), NeedsContext(), ScopeTypeGlobal, ScopeTypeScript, seen_script_scope_, Type(), v8::internal::Scope::UniqueIdInScript(), and UnwrapEvaluationContext().
Referenced by v8::internal::DebugScopeIterator::Advance(), v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), and v8::internal::RUNTIME_FUNCTION().
Restart()
void v8::internal::ScopeIterator::Restart ()
Definition at line 85 of file debug-scopes.cc.
                            {
  DCHECK_NOT_NULL(frame_inspector_);
  function_ = frame_inspector_->GetFunction();
  context_ = Cast<Context>(frame_inspector_->GetContext());
  current_scope_ = start_scope_;
  DCHECK_NOT_NULL(current_scope_);
  UnwrapEvaluationContext();
  seen_script_scope_ = false;
  calculate_blocklists_ = false;
}
References calculate_blocklists_, context_, current_scope_, DCHECK_NOT_NULL, frame_inspector_, function_, v8::internal::FrameInspector::GetContext(), v8::internal::FrameInspector::GetFunction(), seen_script_scope_, start_scope_, and UnwrapEvaluationContext().
ScopeObject()
Handle< JSObject > v8::internal::ScopeIterator::ScopeObject (Mode mode)
Definition at line 623 of file debug-scopes.cc.
                                                     {
  DCHECK(!Done());
  ScopeType type = Type();
  if (type == ScopeTypeGlobal) {
    DCHECK_EQ(Mode::ALL, mode);
    return handle(context_->global_proxy(), isolate_);
  }
  if (type == ScopeTypeWith) {
    DCHECK_EQ(Mode::ALL, mode);
    return WithContextExtension();
  }
  Handle<JSObject> scope = isolate_->factory()->NewSlowJSObjectWithNullProto();
  auto visitor = [=, this](DirectHandle<String> name,
                           DirectHandle<Object> value, ScopeType scope_type) {
    if (IsOptimizedOut(*value, isolate_)) {
      JSObject::SetAccessor(
          scope, name, isolate_->factory()->value_unavailable_accessor(), NONE)
          .Check();
    } else if (IsTheHole(*value, isolate_)) {
      const bool is_overriden_repl_let =
          scope_type == ScopeTypeScript &&
          JSReceiver::HasOwnProperty(isolate_, scope, name).FromMaybe(true);
      if (!is_overriden_repl_let) {
        // We also use the hole to represent overridden let-declarations via
        // REPL mode in a script context. Don't install the unavailable accessor
        // in that case.
        JSObject::SetAccessor(scope, name,
                              isolate_->factory()->value_unavailable_accessor(),
                              NONE)
            .Check();
      }
    } else {
      // Overwrite properties. Sometimes names in the same scope can collide,
      // e.g. with extension objects introduced via local eval.
      Object::SetPropertyOrElement(isolate_, scope, name, value,
                                   Just(ShouldThrow::kDontThrow))
          .Check();
    }
    return false;
  };
  VisitScope(visitor, mode);
  return scope;
}
References ALL, context_, v8::internal::DCHECK(), DCHECK_EQ, Done(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::JSReceiver::HasOwnProperty(), isolate_, v8::Just(), v8::internal::kDontThrow, mode(), v8::internal::name, v8::internal::Factory::NewSlowJSObjectWithNullProto(), v8::internal::NONE, ScopeTypeGlobal, ScopeTypeScript, ScopeTypeWith, v8::internal::JSObject::SetAccessor(), v8::internal::Object::SetPropertyOrElement(), Type(), v8::internal::tracing::type, v8::internal::value, VisitScope(), and WithContextExtension().
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), v8::internal::DebugScopeIterator::GetObject(), and MaterializeScopeDetails().
SetContextExtensionValue()
bool v8::internal::ScopeIterator::SetContextExtensionValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value) [private]
Definition at line 1162 of file debug-scopes.cc.
                                                                             {
  if (!context_->has_extension()) return false;
  DCHECK(IsJSContextExtensionObject(context_->extension_object()));
  DirectHandle<JSObject> ext(context_->extension_object(), isolate_);
  LookupIterator it(isolate_, ext, variable_name, LookupIterator::OWN);
  Maybe<bool> maybe = JSReceiver::HasProperty(&it);
  DCHECK(maybe.IsJust());
  if (!maybe.FromJust()) return false;
  CHECK(Object::SetDataProperty(&it, new_value).ToChecked());
  return true;
}
References CHECK, context_, v8::internal::DCHECK(), v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::HasProperty(), v8::Maybe< T >::IsJust(), isolate_, v8::internal::LookupIterator::OWN, and v8::internal::Object::SetDataProperty().
Referenced by SetVariableValue().
SetContextVariableValue()
bool v8::internal::ScopeIterator::SetContextVariableValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value) [private]
Definition at line 1177 of file debug-scopes.cc.
                                                                            {
  int slot_index = context_->scope_info()->ContextSlotIndex(*variable_name);
  if (slot_index < 0) return false;
  Context::Set(context_, slot_index, new_value, isolate_);
  return true;
}
References context_, isolate_, and v8::internal::Context::Set().
Referenced by SetVariableValue().
SetLocalVariableValue()
bool v8::internal::ScopeIterator::SetLocalVariableValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value) [private]
Definition at line 1078 of file debug-scopes.cc.
                                                                          {
  // TODO(verwaest): Walk parameters backwards, not forwards.
  // TODO(verwaest): Use VariableMap rather than locals() list for lookup.
  for (Variable* var : *current_scope_->locals()) {
    if (String::Equals(isolate_, var->name(), variable_name)) {
      int index = var->index();
      switch (var->location()) {
        case VariableLocation::LOOKUP:
        case VariableLocation::UNALLOCATED:
          // Drop assignments to unallocated locals.
          DCHECK(var->is_this() ||
                 *variable_name == ReadOnlyRoots(isolate_).arguments_string());
          return false;
        case VariableLocation::REPL_GLOBAL:
          // Assignments to REPL declared variables are ignored for now.
          return false;
        case VariableLocation::PARAMETER: {
          if (var->is_this()) return false;
          if (frame_inspector_ == nullptr) {
            // Set the variable in the suspended generator.
            DCHECK(!generator_.is_null());
            DirectHandle<FixedArray> parameters_and_registers(
                generator_->parameters_and_registers(), isolate_);
            DCHECK_LT(index, parameters_and_registers->length());
            parameters_and_registers->set(index, *new_value);
          } else {
            JavaScriptFrame* frame = GetFrame();
            if (!frame->is_unoptimized()) return false;
            frame->SetParameterValue(index, *new_value);
          }
          return true;
        }
        case VariableLocation::LOCAL:
          if (frame_inspector_ == nullptr) {
            // Set the variable in the suspended generator.
            DCHECK(!generator_.is_null());
            int parameter_count =
                function_->shared()->scope_info()->ParameterCount();
            index += parameter_count;
            DirectHandle<FixedArray> parameters_and_registers(
                generator_->parameters_and_registers(), isolate_);
            DCHECK_LT(index, parameters_and_registers->length());
            parameters_and_registers->set(index, *new_value);
          } else {
            // Set the variable on the stack.
            JavaScriptFrame* frame = GetFrame();
            if (!frame->is_unoptimized()) return false;
            frame->SetExpression(index, *new_value);
          }
          return true;
        case VariableLocation::CONTEXT:
          DCHECK(var->IsContextSlot());
          // We know of at least one open bug where the context and scope chain
          // don't match (https://crbug.com/753338).
          // Skip the write if the context's ScopeInfo doesn't know anything
          // about this variable.
          if (context_->scope_info()->ContextSlotIndex(*variable_name) !=
              index) {
            return false;
          }
          Context::Set(context_, index, new_value, isolate_);
          return true;
        case VariableLocation::MODULE:
          if (!var->IsExport()) return false;
          DirectHandle<SourceTextModule> module(context_->module(), isolate_);
          SourceTextModule::StoreVariable(module, var->index(), new_value);
          return true;
      }
      UNREACHABLE();
    }
  }
  return false;
}
References v8::internal::CONTEXT, context_, current_scope_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::String::Equals(), frame_inspector_, function_, generator_, GetFrame(), v8::internal::index, v8::internal::JavaScriptFrame::is_unoptimized(), isolate_, v8::internal::LOCAL, v8::internal::Scope::locals(), v8::internal::LOOKUP, v8::internal::MODULE, v8::internal::PARAMETER, v8::internal::REPL_GLOBAL, v8::internal::Context::Set(), v8::internal::CommonFrame::SetExpression(), v8::internal::JavaScriptFrame::SetParameterValue(), v8::internal::SourceTextModule::StoreVariable(), v8::internal::UNALLOCATED, and v8::internal::UNREACHABLE().
Referenced by SetVariableValue().
SetModuleVariableValue()
bool v8::internal::ScopeIterator::SetModuleVariableValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value) [private]
Definition at line 1185 of file debug-scopes.cc.
                                                                           {
  DisallowGarbageCollection no_gc;
  int cell_index;
  VariableMode mode;
  InitializationFlag init_flag;
  MaybeAssignedFlag maybe_assigned_flag;
  cell_index = context_->scope_info()->ModuleIndex(
      *variable_name, &mode, &init_flag, &maybe_assigned_flag);
  // Setting imports is currently not supported.
  if (SourceTextModuleDescriptor::GetCellIndexKind(cell_index) !=
      SourceTextModuleDescriptor::kExport) {
    return false;
  }
  DirectHandle<SourceTextModule> module(context_->module(), isolate_);
  SourceTextModule::StoreVariable(module, cell_index, new_value);
  return true;
}
References context_, v8::internal::SourceTextModuleDescriptor::GetCellIndexKind(), isolate_, v8::internal::SourceTextModuleDescriptor::kExport, mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SourceTextModule::StoreVariable().
Referenced by SetVariableValue().
SetScriptVariableValue()
bool v8::internal::ScopeIterator::SetScriptVariableValue (DirectHandle< String > variable_name, DirectHandle< Object > new_value) [private]
Definition at line 1206 of file debug-scopes.cc.
                                                                           {
  DirectHandle<ScriptContextTable> script_contexts(
      context_->native_context()->script_context_table(), isolate_);
  VariableLookupResult lookup_result;
  if (script_contexts->Lookup(variable_name, &lookup_result)) {
    DirectHandle<Context> script_context(
        script_contexts->get(lookup_result.context_index), isolate_);
    Context::Set(script_context, lookup_result.slot_index, new_value, isolate_);
    return true;
  }
  return false;
}
References context_, v8::internal::VariableLookupResult::context_index, isolate_, v8::internal::Context::Set(), and v8::internal::VariableLookupResult::slot_index.
Referenced by SetVariableValue().
SetVariableValue()
bool v8::internal::ScopeIterator::SetVariableValue (Handle< String > variable_name, DirectHandle< Object > new_value)
Definition at line 693 of file debug-scopes.cc.
                                                                 {
  DCHECK(!Done());
  name = isolate_->factory()->InternalizeString(name);
  switch (Type()) {
    case ScopeTypeGlobal:
    case ScopeTypeWith:
      break;
    case ScopeTypeEval:
    case ScopeTypeBlock:
    case ScopeTypeCatch:
    case ScopeTypeModule:
      if (InInnerScope()) return SetLocalVariableValue(name, value);
      if (Type() == ScopeTypeModule && SetModuleVariableValue(name, value)) {
        return true;
      }
      return SetContextVariableValue(name, value);
    case ScopeTypeLocal:
    case ScopeTypeClosure:
      if (InInnerScope()) {
        DCHECK_EQ(ScopeTypeLocal, Type());
        if (SetLocalVariableValue(name, value)) return true;
        // There may not be an associated context since we're InInnerScope().
        if (!NeedsContext()) return false;
      } else {
        DCHECK_EQ(ScopeTypeClosure, Type());
        if (SetContextVariableValue(name, value)) return true;
      }
      // The above functions only set variables statically declared in the
      // function. There may be eval-introduced variables. Check them in
      // SetContextExtensionValue.
      return SetContextExtensionValue(name, value);
    case ScopeTypeScript:
      return SetScriptVariableValue(name, value);
  }
  return false;
}
References v8::internal::DCHECK(), DCHECK_EQ, Done(), v8::internal::Isolate::factory(), InInnerScope(), v8::internal::Factory::InternalizeString(), isolate_, v8::internal::name, NeedsContext(), ScopeTypeBlock, ScopeTypeCatch, ScopeTypeClosure, ScopeTypeEval, ScopeTypeGlobal, ScopeTypeLocal, ScopeTypeModule, ScopeTypeScript, ScopeTypeWith, SetContextExtensionValue(), SetContextVariableValue(), SetLocalVariableValue(), SetModuleVariableValue(), SetScriptVariableValue(), Type(), and v8::internal::value.
Referenced by v8::internal::SetScopeVariableValue(), and v8::internal::DebugScopeIterator::SetVariableValue().
start_position()
int v8::internal::ScopeIterator::start_position ()
Definition at line 405 of file debug-scopes.cc.
                                  {
  if (InInnerScope()) return current_scope_->start_position();
  if (IsNativeContext(*context_)) return 0;
  return context_->closure_context()->scope_info()->StartPosition();
}
References context_, current_scope_, InInnerScope(), and v8::internal::Scope::start_position().
Referenced by v8::internal::DebugScopeIterator::GetStartLocation(), and MaterializeScopeDetails().
TryParseAndRetrieveScopes()
void v8::internal::ScopeIterator::TryParseAndRetrieveScopes (ReparseStrategy strategy) [private]
Definition at line 221 of file debug-scopes.cc.
                                                                      {
  // Catch the case when the debugger stops in an internal function.
  DirectHandle<SharedFunctionInfo> shared_info(function_->shared(), isolate_);
  DirectHandle<ScopeInfo> scope_info(shared_info->scope_info(), isolate_);
  if (IsUndefined(shared_info->script(), isolate_)) {
    current_scope_ = closure_scope_ = nullptr;
    context_ = handle(function_->context(), isolate_);
    function_ = Handle<JSFunction>();
    return;
  }
  bool ignore_nested_scopes = false;
  if (shared_info->HasBreakInfo(isolate_) && frame_inspector_ != nullptr) {
    // The source position at return is always the end of the function,
    // which is not consistent with the current scope chain. Therefore all
    // nested with, catch and block contexts are skipped, and we can only
    // inspect the function scope.
    // This can only happen if we set a break point inside right before the
    // return, which requires a debug info to be available.
    Handle<DebugInfo> debug_info(shared_info->GetDebugInfo(isolate_), isolate_);
    // Find the break point where execution has stopped.
    BreakLocation location = BreakLocation::FromFrame(debug_info, GetFrame());
    ignore_nested_scopes = location.IsReturn();
  }
  if (strategy == ReparseStrategy::kScriptIfNeeded) {
    Tagged<Object> maybe_block_list =
        isolate_->LocalsBlockListCacheGet(scope_info);
    calculate_blocklists_ = IsTheHole(maybe_block_list);
    strategy = calculate_blocklists_ ? ReparseStrategy::kScriptIfNeeded
                                     : ReparseStrategy::kFunctionLiteral;
  }
  // Reparse the code and analyze the scopes.
  // Depending on the chosen strategy, the whole script or just
  // the closure is re-parsed for function scopes.
  DirectHandle<Script> script(Cast<Script>(shared_info->script()), isolate_);
  // Pick between flags for a single function compilation, or an eager
  // compilation of the whole script.
  UnoptimizedCompileFlags flags =
      (scope_info->scope_type() == FUNCTION_SCOPE &&
       strategy == ReparseStrategy::kFunctionLiteral)
          ? UnoptimizedCompileFlags::ForFunctionCompile(isolate_, *shared_info)
          : UnoptimizedCompileFlags::ForScriptCompile(isolate_, *script)
                .set_is_eager(true);
  flags.set_is_reparse(true);
  MaybeDirectHandle<ScopeInfo> maybe_outer_scope;
  if (flags.is_toplevel() &&
      script->compilation_type() == Script::CompilationType::kEval) {
    // Re-parsing a full eval script requires us to correctly set the outer
    // language mode and potentially an outer scope info.
    //
    // We walk the runtime scope chain and look for an EVAL scope. If we don't
    // find one, we assume sloppy mode and no outer scope info.
    DCHECK(flags.is_eval());
    DirectHandle<ScopeInfo> eval_scope;
    if (FindEvalScope(isolate_, *scope_info).ToHandle(&eval_scope)) {
      flags.set_outer_language_mode(eval_scope->language_mode());
      if (eval_scope->HasOuterScopeInfo()) {
        maybe_outer_scope =
            direct_handle(eval_scope->OuterScopeInfo(), isolate_);
      }
    } else {
      DCHECK_EQ(flags.outer_language_mode(), LanguageMode::kSloppy);
      DCHECK(maybe_outer_scope.is_null());
    }
  } else if (scope_info->scope_type() == EVAL_SCOPE || script->is_wrapped()) {
    flags.set_is_eval(true);
    if (!IsNativeContext(*context_)) {
      maybe_outer_scope = direct_handle(context_->scope_info(), isolate_);
    }
    // Language mode may be inherited from the eval caller.
    // Retrieve it from shared function info.
    flags.set_outer_language_mode(shared_info->language_mode());
  } else if (scope_info->scope_type() == MODULE_SCOPE) {
    DCHECK(script->origin_options().IsModule());
    DCHECK(flags.is_module());
  } else {
    DCHECK(scope_info->is_script_scope() ||
           scope_info->scope_type() == FUNCTION_SCOPE);
  }
  UnoptimizedCompileState compile_state;
  reusable_compile_state_ =
      std::make_unique<ReusableUnoptimizedCompileState>(isolate_);
  info_ = std::make_unique<ParseInfo>(isolate_, flags, &compile_state,
                                      reusable_compile_state_.get());
  const bool parse_result =
      flags.is_toplevel()
          ? parsing::ParseProgram(info_.get(), script, maybe_outer_scope,
                                  isolate_, parsing::ReportStatisticsMode::kNo)
          : parsing::ParseFunction(info_.get(), shared_info, isolate_,
                                   parsing::ReportStatisticsMode::kNo);
  if (parse_result) {
    DeclarationScope* literal_scope = info_->literal()->scope();
    ScopeChainRetriever scope_chain_retriever(literal_scope, function_,
                                              GetSourcePosition());
    start_scope_ = scope_chain_retriever.StartScope();
    current_scope_ = start_scope_;
    // In case of a FUNCTION_SCOPE, the ScopeIterator expects
    // {closure_scope_} to be set to the scope of the function.
    closure_scope_ = scope_info->scope_type() == FUNCTION_SCOPE
                         ? scope_chain_retriever.ClosureScope()
                         : literal_scope;
    if (ignore_nested_scopes) {
      current_scope_ = closure_scope_;
      start_scope_ = current_scope_;
      // ignore_nested_scopes is only used for the return-position breakpoint,
      // so we can safely assume that the closure context for the current
      // function exists if it needs one.
      if (closure_scope_->NeedsContext()) {
        context_ = handle(context_->closure_context(), isolate_);
      }
    }
    MaybeCollectAndStoreLocalBlocklists();
    UnwrapEvaluationContext();
  } else {
    // A failed reparse indicates that the preparser has diverged from the
    // parser, that the preparse data given to the initial parse was faulty, or
    // a stack overflow.
    // TODO(leszeks): This error is pretty unexpected, so we could report the
    // error in debug mode. Better to not fail in release though, in case it's
    // just a stack overflow.
    // Silently fail by presenting an empty context chain.
    context_ = Handle<Context>();
  }
}
References calculate_blocklists_, closure_scope_, context_, current_scope_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::EVAL_SCOPE, v8::internal::anonymous_namespace{debug-scopes.cc}::FindEvalScope(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForFunctionCompile(), v8::internal::UnoptimizedCompileFlags::ForScriptCompile(), frame_inspector_, v8::internal::BreakLocation::FromFrame(), function_, v8::internal::FUNCTION_SCOPE, GetFrame(), GetSourcePosition(), v8::internal::handle(), info_, v8::internal::MaybeDirectHandle< T >::is_null(), isolate_, v8::internal::BreakLocation::IsReturn(), v8::internal::Script::kEval, kFunctionLiteral, v8::internal::parsing::kNo, kScriptIfNeeded, v8::internal::kSloppy, v8::internal::Isolate::LocalsBlockListCacheGet(), MaybeCollectAndStoreLocalBlocklists(), v8::internal::MODULE_SCOPE, v8::internal::Scope::NeedsContext(), v8::internal::parsing::ParseFunction(), v8::internal::parsing::ParseProgram(), reusable_compile_state_, v8::internal::script, start_scope_, v8::anonymous_namespace{api.cc}::ToHandle(), and UnwrapEvaluationContext().
Referenced by ScopeIterator().
Type()
ScopeIterator::ScopeType v8::internal::ScopeIterator::Type () const
Definition at line 560 of file debug-scopes.cc.
                                                 {
  DCHECK(!Done());
  if (InInnerScope()) {
    switch (current_scope_->scope_type()) {
      case FUNCTION_SCOPE:
        DCHECK_IMPLIES(NeedsAndHasContext(),
                       context_->IsFunctionContext() ||
                           context_->IsDebugEvaluateContext());
        return ScopeTypeLocal;
      case MODULE_SCOPE:
        DCHECK_IMPLIES(NeedsAndHasContext(), context_->IsModuleContext());
        return ScopeTypeModule;
      case SCRIPT_SCOPE:
      case REPL_MODE_SCOPE:
        DCHECK_IMPLIES(NeedsAndHasContext(), context_->IsScriptContext() ||
                                                 IsNativeContext(*context_));
        return ScopeTypeScript;
      case WITH_SCOPE:
        DCHECK_IMPLIES(NeedsAndHasContext(), context_->IsWithContext());
        return ScopeTypeWith;
      case CATCH_SCOPE:
        DCHECK(context_->IsCatchContext());
        return ScopeTypeCatch;
      case BLOCK_SCOPE:
      case CLASS_SCOPE:
        DCHECK_IMPLIES(NeedsAndHasContext(), context_->IsBlockContext());
        return ScopeTypeBlock;
      case EVAL_SCOPE:
        DCHECK_IMPLIES(NeedsAndHasContext(), context_->IsEvalContext());
        return ScopeTypeEval;
      case SHADOW_REALM_SCOPE:
        DCHECK_IMPLIES(NeedsAndHasContext(), IsNativeContext(*context_));
        // TODO(v8:11989): New ScopeType for ShadowRealms?
        return ScopeTypeScript;
    }
    UNREACHABLE();
  }
  if (IsNativeContext(*context_)) {
    DCHECK(IsJSGlobalObject(context_->global_object()));
    // If we are at the native context and have not yet seen script scope,
    // fake it.
    return seen_script_scope_ ? ScopeTypeGlobal : ScopeTypeScript;
  }
  if (context_->IsFunctionContext() || context_->IsEvalContext() ||
      context_->IsDebugEvaluateContext()) {
    return ScopeTypeClosure;
  }
  if (context_->IsCatchContext()) {
    return ScopeTypeCatch;
  }
  if (context_->IsBlockContext()) {
    return ScopeTypeBlock;
  }
  if (context_->IsModuleContext()) {
    return ScopeTypeModule;
  }
  if (context_->IsScriptContext()) {
    return ScopeTypeScript;
  }
  DCHECK(context_->IsWithContext());
  return ScopeTypeWith;
}
References v8::internal::BLOCK_SCOPE, v8::internal::CATCH_SCOPE, v8::internal::CLASS_SCOPE, context_, current_scope_, v8::internal::DCHECK(), DCHECK_IMPLIES, Done(), v8::internal::EVAL_SCOPE, v8::internal::FUNCTION_SCOPE, InInnerScope(), v8::internal::MODULE_SCOPE, NeedsAndHasContext(), v8::internal::REPL_MODE_SCOPE, v8::internal::Scope::scope_type(), ScopeTypeBlock, ScopeTypeCatch, ScopeTypeClosure, ScopeTypeEval, ScopeTypeGlobal, ScopeTypeLocal, ScopeTypeModule, ScopeTypeScript, ScopeTypeWith, v8::internal::SCRIPT_SCOPE, seen_script_scope_, v8::internal::SHADOW_REALM_SCOPE, v8::internal::UNREACHABLE(), and v8::internal::WITH_SCOPE.
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), DeclaresLocals(), v8::internal::DebugScopeIterator::GetType(), MaterializeScopeDetails(), Next(), ScopeObject(), SetVariableValue(), VisitLocalScope(), and VisitScope().
UnwrapEvaluationContext()
void v8::internal::ScopeIterator::UnwrapEvaluationContext () [private]
Definition at line 363 of file debug-scopes.cc.
                                            {
  if (!context_->IsDebugEvaluateContext()) return;
  Tagged<Context> current = *context_;
  do {
    Tagged<Object> wrapped = current->GetNoCell(Context::WRAPPED_CONTEXT_INDEX);
    if (IsContext(wrapped)) {
      current = Cast<Context>(wrapped);
    } else {
      DCHECK(!current->previous().is_null());
      current = current->previous();
    }
  } while (current->IsDebugEvaluateContext());
  context_ = handle(current, isolate_);
}
References context_, v8::internal::DCHECK(), v8::internal::handle(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, and v8::internal::Context::WRAPPED_CONTEXT_INDEX.
Referenced by Next(), Restart(), ScopeIterator(), and TryParseAndRetrieveScopes().
VisitContextLocals()
bool v8::internal::ScopeIterator::VisitContextLocals (const Visitor & visitor, DirectHandle< ScopeInfo > scope_info, DirectHandle< Context > context, ScopeType scope_type) const [private]
Definition at line 861 of file debug-scopes.cc.
                                                                   {
  // Fill all context locals to the context extension.
  for (auto it : ScopeInfo::IterateLocalNames(scope_info)) {
    Handle<String> name(it->name(), isolate_);
    if (ScopeInfo::VariableIsSynthetic(*name)) continue;
    int context_index = scope_info->ContextHeaderLength() + it->index();
    Handle<Object> value = indirect_handle(
        Context::Get(context, context_index, isolate_), isolate_);
    if (visitor(name, value, scope_type)) return true;
  }
  return false;
}
References v8::internal::Context::Get(), v8::internal::indirect_handle(), isolate_, v8::internal::ScopeInfo::IterateLocalNames(), v8::internal::name, v8::internal::value, and v8::internal::ScopeInfo::VariableIsSynthetic().
Referenced by VisitLocalScope(), VisitModuleScope(), and VisitScriptScope().
VisitLocals()
bool v8::internal::ScopeIterator::VisitLocals (const Visitor & visitor, Mode mode, ScopeType scope_type) const [private]
Definition at line 877 of file debug-scopes.cc.
                                                            {
  if (mode == Mode::STACK && current_scope_->is_declaration_scope() &&
      current_scope_->AsDeclarationScope()->has_this_declaration()) {
    // TODO(bmeurer): We should refactor the general variable lookup
    // around "this", since the current way is rather hacky when the
    // receiver is context-allocated.
    auto this_var = current_scope_->AsDeclarationScope()->receiver();
    Handle<Object> receiver =
        this_var->location() == VariableLocation::CONTEXT
            ? handle(context_->GetNoCell(this_var->index()), isolate_)
        : frame_inspector_ == nullptr ? handle(generator_->receiver(), isolate_)
                                      : frame_inspector_->GetReceiver();
    if (visitor(isolate_->factory()->this_string(), receiver, scope_type))
      return true;
  }
  if (current_scope_->is_function_scope()) {
    Variable* function_var =
        current_scope_->AsDeclarationScope()->function_var();
    if (function_var != nullptr) {
      Handle<JSFunction> function = frame_inspector_ == nullptr
                                        ? function_
                                        : frame_inspector_->GetFunction();
      Handle<String> name = function_var->name();
      if (visitor(name, function, scope_type)) return true;
    }
  }
  for (Variable* var : *current_scope_->locals()) {
    if (ScopeInfo::VariableIsSynthetic(*var->name())) {
      // We want to materialize "new.target" for debug-evaluate.
      if (mode != Mode::STACK ||
          !var->name()->Equals(*isolate_->factory()->dot_new_target_string())) {
        continue;
      }
    }
    int index = var->index();
    Handle<Object> value;
    switch (var->location()) {
      case VariableLocation::LOOKUP:
        UNREACHABLE();
      case VariableLocation::REPL_GLOBAL:
        // REPL declared variables are ignored for now.
      case VariableLocation::UNALLOCATED:
        continue;
      case VariableLocation::PARAMETER: {
        if (frame_inspector_ == nullptr) {
          // Get the variable from the suspended generator.
          DCHECK(!generator_.is_null());
          Tagged<FixedArray> parameters_and_registers =
              generator_->parameters_and_registers();
          DCHECK_LT(index, parameters_and_registers->length());
          value = handle(parameters_and_registers->get(index), isolate_);
        } else if (var->IsReceiver()) {
          value = frame_inspector_->GetReceiver();
        } else {
          value = frame_inspector_->GetParameter(index);
        }
        break;
      }
      case VariableLocation::LOCAL:
        if (frame_inspector_ == nullptr) {
          // Get the variable from the suspended generator.
          DCHECK(!generator_.is_null());
          Tagged<FixedArray> parameters_and_registers =
              generator_->parameters_and_registers();
          int parameter_count =
              function_->shared()->scope_info()->ParameterCount();
          index += parameter_count;
          DCHECK_LT(index, parameters_and_registers->length());
          value = handle(parameters_and_registers->get(index), isolate_);
        } else {
          value = frame_inspector_->GetExpression(index);
          if (IsOptimizedOut(*value, isolate_)) {
            // We'll rematerialize this later.
            if (current_scope_->is_declaration_scope() &&
                current_scope_->AsDeclarationScope()->arguments() == var) {
              continue;
            }
          } else if (IsLexicalVariableMode(var->mode()) &&
                     IsUndefined(*value, isolate_) &&
                     GetSourcePosition() != kNoSourcePosition &&
                     GetSourcePosition() <= var->initializer_position()) {
            // Variables that are `undefined` could also mean an elided hole
            // write. We explicitly check the static scope information if we
            // are currently stopped before the variable is actually initialized
            // which means we are in the middle of that var's TDZ.
            value = isolate_->factory()->the_hole_value();
          }
        }
        break;
      case VariableLocation::CONTEXT:
        if (mode == Mode::STACK) continue;
        if (!HasContext()) {
          // If the context was not yet pushed we report the variable as
          // unavailable.
          value = isolate_->factory()->the_hole_value();
          break;
        }
        DCHECK(var->IsContextSlot());
        DCHECK_EQ(context_->scope_info()->ContextSlotIndex(*var->name()),
                  index);
        value =
            indirect_handle(Context::Get(context_, index, isolate_), isolate_);
        break;
      case VariableLocation::MODULE: {
        if (mode == Mode::STACK) continue;
        // if (var->IsExport()) continue;
        DirectHandle<SourceTextModule> module(context_->module(), isolate_);
        value = SourceTextModule::LoadVariable(isolate_, module, var->index());
        break;
      }
    }
    if (visitor(var->name(), value, scope_type)) return true;
  }
  return false;
}
References v8::internal::DeclarationScope::arguments(), v8::internal::Scope::AsDeclarationScope(), v8::internal::CONTEXT, context_, current_scope_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::Isolate::factory(), frame_inspector_, function_, v8::internal::DeclarationScope::function_var(), generator_, v8::internal::Context::Get(), v8::internal::FrameInspector::GetExpression(), v8::internal::FrameInspector::GetFunction(), v8::internal::FrameInspector::GetParameter(), v8::internal::FrameInspector::GetReceiver(), GetSourcePosition(), v8::internal::handle(), v8::internal::DeclarationScope::has_this_declaration(), HasContext(), v8::internal::index, v8::internal::indirect_handle(), v8::internal::Scope::is_declaration_scope(), v8::internal::Scope::is_function_scope(), v8::internal::IsLexicalVariableMode(), isolate_, v8::internal::kNoSourcePosition, v8::internal::SourceTextModule::LoadVariable(), v8::internal::LOCAL, v8::internal::Scope::locals(), v8::internal::HandleBase::location(), v8::internal::LOOKUP, mode(), v8::internal::MODULE, v8::internal::Variable::name(), v8::internal::name, v8::internal::PARAMETER, v8::internal::DeclarationScope::receiver(), v8::internal::REPL_GLOBAL, STACK, v8::internal::UNALLOCATED, v8::internal::UNREACHABLE(), v8::internal::value, and v8::internal::ScopeInfo::VariableIsSynthetic().
Referenced by VisitLocalScope().
VisitLocalScope()
void v8::internal::ScopeIterator::VisitLocalScope (const Visitor & visitor, Mode mode, ScopeType scope_type) const [private]
Definition at line 1017 of file debug-scopes.cc.
                                                                {
  if (InInnerScope()) {
    if (VisitLocals(visitor, mode, scope_type)) return;
    if (mode == Mode::STACK && Type() == ScopeTypeLocal) {
      // Hide |this| in arrow functions that may be embedded in other functions
      // but don't force |this| to be context-allocated. Otherwise we'd find the
      // wrong |this| value.
      if (!closure_scope_->has_this_declaration() &&
          !closure_scope_->HasThisReference()) {
        if (visitor(isolate_->factory()->this_string(),
                    isolate_->factory()->undefined_value(), scope_type))
          return;
      }
      // Add |arguments| to the function scope even if it wasn't used.
      // Currently we don't yet support materializing the arguments object of
      // suspended generators. We'd need to read the arguments out from the
      // suspended generator rather than from an activation as
      // FunctionGetArguments does.
      if (frame_inspector_ != nullptr && !closure_scope_->is_arrow_scope() &&
          (closure_scope_->arguments() == nullptr ||
           IsOptimizedOut(*frame_inspector_->GetExpression(
                              closure_scope_->arguments()->index()),
                          isolate_))) {
        JavaScriptFrame* frame = GetFrame();
        Handle<JSObject> arguments = Accessors::FunctionGetArguments(
            frame, frame_inspector_->inlined_frame_index());
        if (visitor(isolate_->factory()->arguments_string(), arguments,
                    scope_type))
          return;
      }
    }
  } else {
    DCHECK_EQ(Mode::ALL, mode);
    DirectHandle<ScopeInfo> scope_info(context_->scope_info(), isolate_);
    if (VisitContextLocals(visitor, scope_info, context_, scope_type)) return;
  }
  if (mode == Mode::ALL && HasContext()) {
    DCHECK(!context_->IsScriptContext());
    DCHECK(!IsNativeContext(*context_));
    DCHECK(!context_->IsWithContext());
    if (!context_->scope_info()->SloppyEvalCanExtendVars()) return;
    if (context_->extension_object().is_null()) return;
    DirectHandle<JSObject> extension(context_->extension_object(), isolate_);
    DirectHandle<FixedArray> keys =
        KeyAccumulator::GetKeys(isolate_, extension,
                                KeyCollectionMode::kOwnOnly, ENUMERABLE_STRINGS)
            .ToHandleChecked();
    for (int i = 0; i < keys->length(); i++) {
      // Names of variables introduced by eval are strings.
      DCHECK(IsString(keys->get(i)));
      Handle<String> key(Cast<String>(keys->get(i)), isolate_);
      Handle<Object> value =
          JSReceiver::GetDataProperty(isolate_, extension, key);
      if (visitor(key, value, scope_type)) return;
    }
  }
}
References ALL, v8::internal::DeclarationScope::arguments(), closure_scope_, context_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ENUMERABLE_STRINGS, v8::internal::Isolate::factory(), frame_inspector_, v8::internal::Accessors::FunctionGetArguments(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::FrameInspector::GetExpression(), GetFrame(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::DeclarationScope::has_this_declaration(), HasContext(), v8::internal::Scope::HasThisReference(), v8::internal::Variable::index(), InInnerScope(), v8::internal::FrameInspector::inlined_frame_index(), v8::internal::DeclarationScope::is_arrow_scope(), isolate_, v8::internal::key, v8::internal::kOwnOnly, mode(), ScopeTypeLocal, STACK, Type(), v8::internal::value, VisitContextLocals(), and VisitLocals().
Referenced by VisitScope().
VisitModuleScope()
void v8::internal::ScopeIterator::VisitModuleScope (const Visitor & visitor) const [private]
Definition at line 833 of file debug-scopes.cc.
                                                                 {
  DCHECK(context_->IsModuleContext());
  DirectHandle<ScopeInfo> scope_info(context_->scope_info(), isolate_);
  if (VisitContextLocals(visitor, scope_info, context_, ScopeTypeModule)) {
    return;
  }
  int module_variable_count = scope_info->ModuleVariableCount();
  DirectHandle<SourceTextModule> module(context_->module(), isolate_);
  for (int i = 0; i < module_variable_count; ++i) {
    int index;
    Handle<String> name;
    {
      Tagged<String> raw_name;
      scope_info->ModuleVariable(i, &raw_name, &index);
      if (ScopeInfo::VariableIsSynthetic(raw_name)) continue;
      name = handle(raw_name, isolate_);
    }
    Handle<Object> value =
        SourceTextModule::LoadVariable(isolate_, module, index);
    if (visitor(name, value, ScopeTypeModule)) return;
  }
}
References context_, v8::internal::DCHECK(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, isolate_, v8::internal::SourceTextModule::LoadVariable(), v8::internal::name, ScopeTypeModule, v8::internal::value, v8::internal::ScopeInfo::VariableIsSynthetic(), and VisitContextLocals().
Referenced by VisitScope().
VisitScope()
void v8::internal::ScopeIterator::VisitScope (const Visitor & visitor, Mode mode) const [private]
Definition at line 670 of file debug-scopes.cc.
                                                                      {
  switch (Type()) {
    case ScopeTypeLocal:
    case ScopeTypeClosure:
    case ScopeTypeCatch:
    case ScopeTypeBlock:
    case ScopeTypeEval:
      return VisitLocalScope(visitor, mode, Type());
    case ScopeTypeModule:
      if (InInnerScope()) {
        return VisitLocalScope(visitor, mode, Type());
      }
      DCHECK_EQ(Mode::ALL, mode);
      return VisitModuleScope(visitor);
    case ScopeTypeScript:
      DCHECK_EQ(Mode::ALL, mode);
      return VisitScriptScope(visitor);
    case ScopeTypeWith:
    case ScopeTypeGlobal:
      UNREACHABLE();
  }
}
References ALL, DCHECK_EQ, InInnerScope(), mode(), ScopeTypeBlock, ScopeTypeCatch, ScopeTypeClosure, ScopeTypeEval, ScopeTypeGlobal, ScopeTypeLocal, ScopeTypeModule, ScopeTypeScript, ScopeTypeWith, Type(), v8::internal::UNREACHABLE(), VisitLocalScope(), VisitModuleScope(), and VisitScriptScope().
Referenced by DeclaresLocals(), and ScopeObject().
VisitScriptScope()
void v8::internal::ScopeIterator::VisitScriptScope (const Visitor & visitor) const [private]
Definition at line 819 of file debug-scopes.cc.
                                                                 {
  DirectHandle<ScriptContextTable> script_contexts(
      context_->native_context()->script_context_table(), isolate_);
  // Skip the first script since that just declares 'this'.
  for (int i = 1; i < script_contexts->length(kAcquireLoad); i++) {
    DirectHandle<Context> context(script_contexts->get(i), isolate_);
    DirectHandle<ScopeInfo> scope_info(context->scope_info(), isolate_);
    if (VisitContextLocals(visitor, scope_info, context, ScopeTypeScript)) {
      return;
    }
  }
}
References context_, isolate_, v8::kAcquireLoad, ScopeTypeScript, and VisitContextLocals().
Referenced by VisitScope().
WithContextExtension()
Handle< JSObject > v8::internal::ScopeIterator::WithContextExtension () [private]
Definition at line 1005 of file debug-scopes.cc.
                                                     {
  DCHECK(context_->IsWithContext());
  if (!IsJSObject(context_->extension_receiver())) {
    DCHECK(IsJSProxy(context_->extension_receiver()) ||
           IsWasmObject(context_->extension_receiver()));
    return isolate_->factory()->NewSlowJSObjectWithNullProto();
  }
  return handle(Cast<JSObject>(context_->extension_receiver()), isolate_);
}
References context_, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::handle(), isolate_, v8::internal::IsWasmObject(), and v8::internal::Factory::NewSlowJSObjectWithNullProto().
Referenced by ScopeObject().
Member Data Documentation
calculate_blocklists_
bool v8::internal::ScopeIterator::calculate_blocklists_ = false [private]
Definition at line 133 of file debug-scopes.h.
Referenced by Restart(), and TryParseAndRetrieveScopes().
closure_scope_
DeclarationScope* v8::internal::ScopeIterator::closure_scope_ = nullptr [private]
Definition at line 129 of file debug-scopes.h.
Referenced by ClosureScopeHasThisReference(), NeedsContext(), Next(), TryParseAndRetrieveScopes(), and VisitLocalScope().
context_
Handle<Context> v8::internal::ScopeIterator::context_ [private]
Definition at line 126 of file debug-scopes.h.
Referenced by AdvanceOneContext(), end_position(), GetFunctionDebugName(), HasContext(), HasPositionInfo(), NeedsContext(), Next(), Restart(), ScopeIterator(), ScopeObject(), SetContextExtensionValue(), SetContextVariableValue(), SetLocalVariableValue(), SetModuleVariableValue(), SetScriptVariableValue(), start_position(), TryParseAndRetrieveScopes(), Type(), UnwrapEvaluationContext(), VisitLocals(), VisitLocalScope(), VisitModuleScope(), VisitScriptScope(), and WithContextExtension().
current_scope_
Scope* v8::internal::ScopeIterator::current_scope_ = nullptr [private]
Definition at line 131 of file debug-scopes.h.
Referenced by AdvanceOneScope(), AdvanceScope(), CollectLocalsFromCurrentScope(), end_position(), HasContext(), NeedsContext(), Next(), Restart(), SetLocalVariableValue(), start_position(), TryParseAndRetrieveScopes(), Type(), and VisitLocals().
frame_inspector_
FrameInspector* const v8::internal::ScopeIterator::frame_inspector_ = nullptr [private]
Definition at line 119 of file debug-scopes.h.
Referenced by GetSourcePosition(), Restart(), SetLocalVariableValue(), TryParseAndRetrieveScopes(), VisitLocals(), and VisitLocalScope().
function_
Handle<JSFunction> v8::internal::ScopeIterator::function_ [private]
Definition at line 124 of file debug-scopes.h.
Referenced by GetFunctionDebugName(), MaterializeScopeDetails(), NeedsContext(), Next(), Restart(), ScopeIterator(), SetLocalVariableValue(), TryParseAndRetrieveScopes(), and VisitLocals().
generator_
Handle<JSGeneratorObject> v8::internal::ScopeIterator::generator_ [private]
Definition at line 120 of file debug-scopes.h.
Referenced by GetSourcePosition(), SetLocalVariableValue(), and VisitLocals().
info_
std::unique_ptr<ParseInfo> v8::internal::ScopeIterator::info_ [private]
Definition at line 118 of file debug-scopes.h.
Referenced by TryParseAndRetrieveScopes().
isolate_
Isolate* v8::internal::ScopeIterator::isolate_ [private]
Definition at line 116 of file debug-scopes.h.
Referenced by AdvanceOneContext(), CollectLocalsFromCurrentScope(), GetFunctionDebugName(), GetSourcePosition(), MaterializeScopeDetails(), Next(), ScopeObject(), SetContextExtensionValue(), SetContextVariableValue(), SetLocalVariableValue(), SetModuleVariableValue(), SetScriptVariableValue(), SetVariableValue(), TryParseAndRetrieveScopes(), UnwrapEvaluationContext(), VisitContextLocals(), VisitLocals(), VisitLocalScope(), VisitModuleScope(), VisitScriptScope(), and WithContextExtension().
kScopeDetailsEndPositionIndex
const int v8::internal::ScopeIterator::kScopeDetailsEndPositionIndex = 4 [static]
Definition at line 39 of file debug-scopes.h.
Referenced by MaterializeScopeDetails().
kScopeDetailsFunctionIndex
const int v8::internal::ScopeIterator::kScopeDetailsFunctionIndex = 5 [static]
Definition at line 40 of file debug-scopes.h.
Referenced by MaterializeScopeDetails().
kScopeDetailsNameIndex
const int v8::internal::ScopeIterator::kScopeDetailsNameIndex = 2 [static]
Definition at line 37 of file debug-scopes.h.
Referenced by MaterializeScopeDetails().
kScopeDetailsObjectIndex
const int v8::internal::ScopeIterator::kScopeDetailsObjectIndex = 1 [static]
Definition at line 36 of file debug-scopes.h.
Referenced by MaterializeScopeDetails().
kScopeDetailsSize
const int v8::internal::ScopeIterator::kScopeDetailsSize = 6 [static]
Definition at line 41 of file debug-scopes.h.
Referenced by MaterializeScopeDetails().
kScopeDetailsStartPositionIndex
const int v8::internal::ScopeIterator::kScopeDetailsStartPositionIndex = 3 [static]
Definition at line 38 of file debug-scopes.h.
Referenced by MaterializeScopeDetails().
kScopeDetailsTypeIndex
const int v8::internal::ScopeIterator::kScopeDetailsTypeIndex = 0 [static]
Definition at line 35 of file debug-scopes.h.
Referenced by MaterializeScopeDetails().
locals_
Handle<StringSet> v8::internal::ScopeIterator::locals_ [private]
Definition at line 128 of file debug-scopes.h.
Referenced by AdvanceOneContext(), and CollectLocalsFromCurrentScope().
reusable_compile_state_
std::unique_ptr<ReusableUnoptimizedCompileState> v8::internal::ScopeIterator::reusable_compile_state_ [private]
Definition at line 117 of file debug-scopes.h.
Referenced by TryParseAndRetrieveScopes().
script_
Handle<Script> v8::internal::ScopeIterator::script_ [private]
Definition at line 127 of file debug-scopes.h.
Referenced by ScopeIterator().
seen_script_scope_
bool v8::internal::ScopeIterator::seen_script_scope_ = false [private]
Definition at line 132 of file debug-scopes.h.
Referenced by Next(), Restart(), and Type().
start_scope_
Scope* v8::internal::ScopeIterator::start_scope_ = nullptr [private]
Definition at line 130 of file debug-scopes.h.
Referenced by Restart(), and TryParseAndRetrieveScopes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-scopes.h
/mnt/V8SourceCode/src/debug/debug-scopes.cc