v8::internal::ObjectStats Class Reference
#include <object-stats.h>
Public Types
enum class VirtualInstanceType { DEFINE_VIRTUAL_INSTANCE_TYPE
, LAST_VIRTUAL_TYPE = WEAK_NEW_SPACE_OBJECT_TO_CODE_TYPE
 }
Public Member Functions
ObjectStats (Heap *heap)
void ClearObjectStats (bool clear_last_time_stats=false)
void PrintJSON (const char *key)
void Dump (std::stringstream &stream)
void CheckpointObjectStats ()
void RecordObjectStats (InstanceType type, size_t size, size_t over_allocated=kNoOverAllocation)
void RecordVirtualObjectStats (VirtualInstanceType type, size_t size, size_t over_allocated)
size_t object_count_last_gc (size_t index)
size_t object_size_last_gc (size_t index)
Isolate * isolate ()
Heap * heap ()
Static Public Attributes
static const size_t kNoOverAllocation = 0
static constexpr int FIRST_VIRTUAL_TYPE = LAST_TYPE + 1
static constexpr int OBJECT_STATS_COUNT
Private Member Functions
void PrintKeyAndId (const char *key, int gc_count)
V8_NOINLINE void PrintInstanceTypeJSON (const char *key, int gc_count, const char *name, int index)
V8_NOINLINE void DumpInstanceTypeData (std::stringstream &stream, const char *name, int index)
int HistogramIndexFromSize (size_t size)
Private Attributes
Heap * heap_
size_t object_counts_ [OBJECT_STATS_COUNT]
size_t object_counts_last_time_ [OBJECT_STATS_COUNT]
size_t object_sizes_ [OBJECT_STATS_COUNT]
size_t object_sizes_last_time_ [OBJECT_STATS_COUNT]
size_t over_allocated_ [OBJECT_STATS_COUNT]
size_t size_histogram_ [OBJECT_STATS_COUNT][kNumberOfBuckets]
size_t over_allocated_histogram_ [OBJECT_STATS_COUNT][kNumberOfBuckets]
size_t tagged_fields_count_
size_t embedder_fields_count_
size_t inobject_smi_fields_count_
size_t boxed_double_fields_count_
size_t string_data_count_
size_t raw_fields_count_
Static Private Attributes
static const int kFirstBucketShift = 5
static const int kLastBucketShift = 20
static const int kFirstBucket = 1 << kFirstBucketShift
static const int kLastBucket = 1 << kLastBucketShift
static const int kNumberOfBuckets = kLastBucketShift - kFirstBucketShift + 1
static const int kLastValueBucketIndex = kLastBucketShift - kFirstBucketShift
Friends
class ObjectStatsCollectorImpl
Detailed Description
Definition at line 94 of file object-stats.h.
Member Enumeration Documentation
VirtualInstanceType
enum v8::internal::ObjectStats::VirtualInstanceType [strong]
Enumerator
DEFINE_VIRTUAL_INSTANCE_TYPE
LAST_VIRTUAL_TYPE
Definition at line 101 of file object-stats.h.
                                 {
#define DEFINE_VIRTUAL_INSTANCE_TYPE(type) type,
    VIRTUAL_INSTANCE_TYPE_LIST(DEFINE_VIRTUAL_INSTANCE_TYPE)
#undef DEFINE_FIXED_ARRAY_SUB_INSTANCE_TYPE
        LAST_VIRTUAL_TYPE = WEAK_NEW_SPACE_OBJECT_TO_CODE_TYPE,
  };
Constructor & Destructor Documentation
ObjectStats()
v8::internal::ObjectStats::ObjectStats (Heap * heap) [inline], [explicit]
Definition at line 98 of file object-stats.h.
: heap_(heap) { ClearObjectStats(true); }
References ClearObjectStats().
Member Function Documentation
CheckpointObjectStats()
void v8::internal::ObjectStats::CheckpointObjectStats ()
Definition at line 338 of file object-stats.cc.
                                        {
  base::MutexGuard lock_guard(object_stats_mutex.Pointer());
  MemCopy(object_counts_last_time_, object_counts_, sizeof(object_counts_));
  MemCopy(object_sizes_last_time_, object_sizes_, sizeof(object_sizes_));
  ClearObjectStats();
}
References ClearObjectStats(), v8::internal::MemCopy(), object_counts_, object_counts_last_time_, object_sizes_, object_sizes_last_time_, v8::internal::object_stats_mutex, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
ClearObjectStats()
void v8::internal::ObjectStats::ClearObjectStats (bool clear_last_time_stats = false)
Definition at line 173 of file object-stats.cc.
                                                             {
  memset(object_counts_, 0, sizeof(object_counts_));
  memset(object_sizes_, 0, sizeof(object_sizes_));
  memset(over_allocated_, 0, sizeof(over_allocated_));
  memset(size_histogram_, 0, sizeof(size_histogram_));
  memset(over_allocated_histogram_, 0, sizeof(over_allocated_histogram_));
  if (clear_last_time_stats) {
    memset(object_counts_last_time_, 0, sizeof(object_counts_last_time_));
    memset(object_sizes_last_time_, 0, sizeof(object_sizes_last_time_));
  }
  tagged_fields_count_ = 0;
  embedder_fields_count_ = 0;
  inobject_smi_fields_count_ = 0;
  boxed_double_fields_count_ = 0;
  string_data_count_ = 0;
  raw_fields_count_ = 0;
}
References boxed_double_fields_count_, embedder_fields_count_, inobject_smi_fields_count_, object_counts_, object_counts_last_time_, object_sizes_, object_sizes_last_time_, over_allocated_, over_allocated_histogram_, raw_fields_count_, size_histogram_, string_data_count_, and tagged_fields_count_.
Referenced by CheckpointObjectStats(), and ObjectStats().
Dump()
void v8::internal::ObjectStats::Dump (std::stringstream & stream)
Definition at line 292 of file object-stats.cc.
                                              {
  double time = isolate()->time_millis_since_init();
  int gc_count = heap()->gc_count();
  stream << "{";
  stream << "\"isolate\":\"" << reinterpret_cast<void*>(isolate()) << "\",";
  stream << "\"id\":" << gc_count << ",";
  stream << "\"time\":" << time << ",";
  // field_data
  stream << "\"field_data\":{";
  stream << "\"tagged_fields\":" << (tagged_fields_count_ * kTaggedSize);
  stream << ",\"embedder_fields\":"
         << (embedder_fields_count_ * kEmbedderDataSlotSize);
  stream << ",\"inobject_smi_fields\": "
         << (inobject_smi_fields_count_ * kTaggedSize);
  stream << ",\"boxed_double_fields\": "
         << (boxed_double_fields_count_ * kDoubleSize);
  stream << ",\"string_data\": " << (string_data_count_ * kTaggedSize);
  stream << ",\"other_raw_fields\":"
         << (raw_fields_count_ * kSystemPointerSize);
  stream << "}, ";
  stream << "\"bucket_sizes\":[";
  for (int i = 0; i < kNumberOfBuckets; i++) {
    stream << (1 << (kFirstBucketShift + i));
    if (i != (kNumberOfBuckets - 1)) stream << ",";
  }
  stream << "],";
  stream << "\"type_data\":{";
#define INSTANCE_TYPE_WRAPPER(name) DumpInstanceTypeData(stream, #name, name);
#define VIRTUAL_INSTANCE_TYPE_WRAPPER(name) \
  DumpInstanceTypeData(\
      stream, #name, \
      FIRST_VIRTUAL_TYPE + static_cast<int>(VirtualInstanceType::name));
  INSTANCE_TYPE_LIST(INSTANCE_TYPE_WRAPPER);
  VIRTUAL_INSTANCE_TYPE_LIST(VIRTUAL_INSTANCE_TYPE_WRAPPER)
  stream << "\"END\":{}}}";
#undef INSTANCE_TYPE_WRAPPER
#undef VIRTUAL_INSTANCE_TYPE_WRAPPER
}
References boxed_double_fields_count_, embedder_fields_count_, v8::internal::Heap::gc_count(), heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, inobject_smi_fields_count_, INSTANCE_TYPE_LIST, INSTANCE_TYPE_WRAPPER, isolate(), v8::internal::kDoubleSize, v8::internal::kEmbedderDataSlotSize, kFirstBucketShift, kNumberOfBuckets, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, raw_fields_count_, string_data_count_, tagged_fields_count_, v8::internal::time, v8::internal::Isolate::time_millis_since_init(), VIRTUAL_INSTANCE_TYPE_LIST, and VIRTUAL_INSTANCE_TYPE_WRAPPER.
DumpInstanceTypeData()
void v8::internal::ObjectStats::DumpInstanceTypeData (std::stringstream & stream, const char * name, int index) [private]
Definition at line 278 of file object-stats.cc.
                                                                    {
  stream << "\"" << name << "\":{";
  stream << "\"type\":" << static_cast<int>(index) << ",";
  stream << "\"overall\":" << object_sizes_[index] << ",";
  stream << "\"count\":" << object_counts_[index] << ",";
  stream << "\"over_allocated\":" << over_allocated_[index] << ",";
  stream << "\"histogram\":";
  DumpJSONArray(stream, size_histogram_[index], kNumberOfBuckets);
  stream << ",\"over_allocated_histogram\":";
  DumpJSONArray(stream, over_allocated_histogram_[index], kNumberOfBuckets);
  stream << "},";
}
References v8::internal::DumpJSONArray(), v8::internal::index, kNumberOfBuckets, v8::internal::name, object_counts_, object_sizes_, over_allocated_, over_allocated_histogram_, and size_histogram_.
heap()
Heap* v8::internal::ObjectStats::heap () [inline]
Definition at line 136 of file object-stats.h.
{ return heap_; }
References heap_.
Referenced by Dump(), isolate(), and PrintJSON().
HistogramIndexFromSize()
int v8::internal::ObjectStats::HistogramIndexFromSize (size_t size) [private]
Definition at line 354 of file object-stats.cc.
                                                   {
  if (size == 0) return 0;
  return std::min({std::max(Log2ForSize(size) + 1 - kFirstBucketShift, 0),
                   kLastValueBucketIndex});
}
References kFirstBucketShift, kLastValueBucketIndex, v8::internal::anonymous_namespace{object-stats.cc}::Log2ForSize(), and size().
Referenced by RecordObjectStats(), and RecordVirtualObjectStats().
isolate()
Isolate * v8::internal::ObjectStats::isolate ()
Definition at line 382 of file object-stats.cc.
{ return heap()->isolate(); }
References heap(), and v8::internal::Heap::isolate().
Referenced by Dump(), PrintJSON(), and PrintKeyAndId().
object_count_last_gc()
size_t v8::internal::ObjectStats::object_count_last_gc (size_t index) [inline]
Definition at line 127 of file object-stats.h.
                                            {
    return object_counts_last_time_[index];
  }
References v8::internal::index, and object_counts_last_time_.
object_size_last_gc()
size_t v8::internal::ObjectStats::object_size_last_gc (size_t index) [inline]
Definition at line 131 of file object-stats.h.
                                           {
    return object_sizes_last_time_[index];
  }
References v8::internal::index, and object_sizes_last_time_.
PrintInstanceTypeJSON()
void v8::internal::ObjectStats::PrintInstanceTypeJSON (const char * key, int gc_count, const char * name, int index) [private]
Definition at line 213 of file object-stats.cc.
                                                                     {
  PrintF("{ ");
  PrintKeyAndId(key, gc_count);
  PrintF("\"type\": \"instance_type_data\", ");
  PrintF("\"instance_type\": %d, ", index);
  PrintF("\"instance_type_name\": \"%s\", ", name);
  PrintF("\"overall\": %zu, ", object_sizes_[index]);
  PrintF("\"count\": %zu, ", object_counts_[index]);
  PrintF("\"over_allocated\": %zu, ", over_allocated_[index]);
  PrintF("\"histogram\": ");
  PrintJSONArray(size_histogram_[index], kNumberOfBuckets);
  PrintF(",");
  PrintF("\"over_allocated_histogram\": ");
  PrintJSONArray(over_allocated_histogram_[index], kNumberOfBuckets);
  PrintF(" }\n");
}
References v8::internal::index, v8::internal::key, kNumberOfBuckets, v8::internal::name, object_counts_, object_sizes_, over_allocated_, over_allocated_histogram_, v8::internal::PrintF(), v8::internal::PrintJSONArray(), PrintKeyAndId(), and size_histogram_.
PrintJSON()
void v8::internal::ObjectStats::PrintJSON (const char * key)
Definition at line 231 of file object-stats.cc.
                                           {
  double time = isolate()->time_millis_since_init();
  int gc_count = heap()->gc_count();
  // gc_descriptor
  PrintF("{ ");
  PrintKeyAndId(key, gc_count);
  PrintF("\"type\": \"gc_descriptor\", \"time\": %f }\n", time);
  // field_data
  PrintF("{ ");
  PrintKeyAndId(key, gc_count);
  PrintF("\"type\": \"field_data\"");
  PrintF(", \"tagged_fields\": %zu", tagged_fields_count_ * kTaggedSize);
  PrintF(", \"embedder_fields\": %zu",
         embedder_fields_count_ * kEmbedderDataSlotSize);
  PrintF(", \"inobject_smi_fields\": %zu",
         inobject_smi_fields_count_ * kTaggedSize);
  PrintF(", \"boxed_double_fields\": %zu",
         boxed_double_fields_count_ * kDoubleSize);
  PrintF(", \"string_data\": %zu", string_data_count_ * kTaggedSize);
  PrintF(", \"other_raw_fields\": %zu", raw_fields_count_ * kSystemPointerSize);
  PrintF(" }\n");
  // bucket_sizes
  PrintF("{ ");
  PrintKeyAndId(key, gc_count);
  PrintF("\"type\": \"bucket_sizes\", \"sizes\": [ ");
  for (int i = 0; i < kNumberOfBuckets; i++) {
    PrintF("%d", 1 << (kFirstBucketShift + i));
    if (i != (kNumberOfBuckets - 1)) PrintF(", ");
  }
  PrintF(" ] }\n");
#define INSTANCE_TYPE_WRAPPER(name) \
  PrintInstanceTypeJSON(key, gc_count, #name, name);
#define VIRTUAL_INSTANCE_TYPE_WRAPPER(name) \
  PrintInstanceTypeJSON(\
      key, gc_count, #name, \
      FIRST_VIRTUAL_TYPE + static_cast<int>(VirtualInstanceType::name));
  INSTANCE_TYPE_LIST(INSTANCE_TYPE_WRAPPER)
  VIRTUAL_INSTANCE_TYPE_LIST(VIRTUAL_INSTANCE_TYPE_WRAPPER)
#undef INSTANCE_TYPE_WRAPPER
#undef VIRTUAL_INSTANCE_TYPE_WRAPPER
}
References boxed_double_fields_count_, embedder_fields_count_, v8::internal::Heap::gc_count(), heap(), inobject_smi_fields_count_, INSTANCE_TYPE_LIST, INSTANCE_TYPE_WRAPPER, isolate(), v8::internal::kDoubleSize, v8::internal::kEmbedderDataSlotSize, v8::internal::key, kFirstBucketShift, kNumberOfBuckets, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, v8::internal::PrintF(), PrintKeyAndId(), raw_fields_count_, string_data_count_, tagged_fields_count_, v8::internal::time, v8::internal::Isolate::time_millis_since_init(), VIRTUAL_INSTANCE_TYPE_LIST, and VIRTUAL_INSTANCE_TYPE_WRAPPER.
PrintKeyAndId()
void v8::internal::ObjectStats::PrintKeyAndId (const char * key, int gc_count) [private]
Definition at line 208 of file object-stats.cc.
                                                             {
  PrintF("\"isolate\": \"%p\", \"id\": %d, \"key\": \"%s\", ",
         reinterpret_cast<void*>(isolate()), gc_count, key);
}
References isolate(), v8::internal::key, and v8::internal::PrintF().
Referenced by PrintInstanceTypeJSON(), and PrintJSON().
RecordObjectStats()
void v8::internal::ObjectStats::RecordObjectStats (InstanceType type, size_t size, size_t over_allocated = kNoOverAllocation)
Definition at line 360 of file object-stats.cc.
                                                           {
  DCHECK_LE(type, LAST_TYPE);
  object_counts_[type]++;
  object_sizes_[type] += size;
  size_histogram_[type][HistogramIndexFromSize(size)]++;
  over_allocated_[type] += over_allocated;
  over_allocated_histogram_[type][HistogramIndexFromSize(size)]++;
}
References DCHECK_LE, HistogramIndexFromSize(), v8::internal::LAST_TYPE, object_counts_, object_sizes_, over_allocated_, over_allocated_histogram_, size(), size_histogram_, and v8::internal::tracing::type.
Referenced by v8::internal::ObjectStatsCollectorImpl::RecordObjectStats().
RecordVirtualObjectStats()
void v8::internal::ObjectStats::RecordVirtualObjectStats (VirtualInstanceType type, size_t size, size_t over_allocated)
Definition at line 370 of file object-stats.cc.
                                                                               {
  DCHECK_LE(typeEnum, VirtualInstanceType::LAST_VIRTUAL_TYPE);
  int type = static_cast<int>(typeEnum);
  object_counts_[FIRST_VIRTUAL_TYPE + type]++;
  object_sizes_[FIRST_VIRTUAL_TYPE + type] += size;
  size_histogram_[FIRST_VIRTUAL_TYPE + type][HistogramIndexFromSize(size)]++;
  over_allocated_[FIRST_VIRTUAL_TYPE + type] += over_allocated;
  over_allocated_histogram_[FIRST_VIRTUAL_TYPE + type]
                           [HistogramIndexFromSize(size)]++;
}
References DCHECK_LE, FIRST_VIRTUAL_TYPE, HistogramIndexFromSize(), LAST_VIRTUAL_TYPE, object_counts_, object_sizes_, over_allocated_, over_allocated_histogram_, size(), size_histogram_, and v8::internal::tracing::type.
Referenced by v8::internal::ObjectStatsCollectorImpl::RecordExternalResourceStats(), v8::internal::ObjectStatsCollectorImpl::RecordPotentialDescriptorArraySavingsStats(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), and v8::internal::ObjectStatsCollectorImpl::RecordVirtualObjectStats().
Friends And Related Function Documentation
ObjectStatsCollectorImpl
friend class ObjectStatsCollectorImpl [friend]
Definition at line 175 of file object-stats.h.
Member Data Documentation
boxed_double_fields_count_
size_t v8::internal::ObjectStats::boxed_double_fields_count_ [private]
Definition at line 171 of file object-stats.h.
Referenced by ClearObjectStats(), Dump(), and PrintJSON().
embedder_fields_count_
size_t v8::internal::ObjectStats::embedder_fields_count_ [private]
Definition at line 169 of file object-stats.h.
Referenced by ClearObjectStats(), Dump(), and PrintJSON().
FIRST_VIRTUAL_TYPE
constexpr int v8::internal::ObjectStats::FIRST_VIRTUAL_TYPE = LAST_TYPE + 1 [static], [constexpr]
Definition at line 111 of file object-stats.h.
Referenced by RecordVirtualObjectStats().
heap_
Heap* v8::internal::ObjectStats::heap_ [private]
Definition at line 156 of file object-stats.h.
Referenced by heap().
inobject_smi_fields_count_
size_t v8::internal::ObjectStats::inobject_smi_fields_count_ [private]
Definition at line 170 of file object-stats.h.
Referenced by ClearObjectStats(), Dump(), and PrintJSON().
kFirstBucket
const int v8::internal::ObjectStats::kFirstBucket = 1 << kFirstBucketShift [static], [private]
Definition at line 141 of file object-stats.h.
kFirstBucketShift
const int v8::internal::ObjectStats::kFirstBucketShift = 5 [static], [private]
Definition at line 139 of file object-stats.h.
Referenced by Dump(), HistogramIndexFromSize(), and PrintJSON().
kLastBucket
const int v8::internal::ObjectStats::kLastBucket = 1 << kLastBucketShift [static], [private]
Definition at line 142 of file object-stats.h.
kLastBucketShift
const int v8::internal::ObjectStats::kLastBucketShift = 20 [static], [private]
Definition at line 140 of file object-stats.h.
kLastValueBucketIndex
const int v8::internal::ObjectStats::kLastValueBucketIndex = kLastBucketShift - kFirstBucketShift [static], [private]
Definition at line 144 of file object-stats.h.
Referenced by HistogramIndexFromSize().
kNoOverAllocation
const size_t v8::internal::ObjectStats::kNoOverAllocation = 0 [static]
Definition at line 96 of file object-stats.h.
Referenced by v8::internal::ObjectStatsCollectorImpl::CollectStatistics(), v8::internal::ObjectStatsCollectorImpl::RecordPotentialDescriptorArraySavingsStats(), v8::internal::ObjectStatsCollectorImpl::RecordSimpleVirtualObjectStats(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualAllocationSiteDetails(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), and v8::internal::ObjectStatsCollectorImpl::RecordVirtualFixedArrayDetails().
kNumberOfBuckets
const int v8::internal::ObjectStats::kNumberOfBuckets = kLastBucketShift - kFirstBucketShift + 1 [static], [private]
Definition at line 143 of file object-stats.h.
Referenced by Dump(), DumpInstanceTypeData(), PrintInstanceTypeJSON(), and PrintJSON().
object_counts_
size_t v8::internal::ObjectStats::object_counts_[OBJECT_STATS_COUNT] [private]
Definition at line 158 of file object-stats.h.
Referenced by CheckpointObjectStats(), ClearObjectStats(), DumpInstanceTypeData(), PrintInstanceTypeJSON(), RecordObjectStats(), and RecordVirtualObjectStats().
object_counts_last_time_
size_t v8::internal::ObjectStats::object_counts_last_time_[OBJECT_STATS_COUNT] [private]
Definition at line 159 of file object-stats.h.
Referenced by CheckpointObjectStats(), ClearObjectStats(), and object_count_last_gc().
object_sizes_
size_t v8::internal::ObjectStats::object_sizes_[OBJECT_STATS_COUNT] [private]
Definition at line 160 of file object-stats.h.
Referenced by CheckpointObjectStats(), ClearObjectStats(), DumpInstanceTypeData(), PrintInstanceTypeJSON(), RecordObjectStats(), and RecordVirtualObjectStats().
object_sizes_last_time_
size_t v8::internal::ObjectStats::object_sizes_last_time_[OBJECT_STATS_COUNT] [private]
Definition at line 161 of file object-stats.h.
Referenced by CheckpointObjectStats(), ClearObjectStats(), and object_size_last_gc().
OBJECT_STATS_COUNT
constexpr int v8::internal::ObjectStats::OBJECT_STATS_COUNT [static], [constexpr]
Initial value:
=
      FIRST_VIRTUAL_TYPE +
      static_cast<int>(VirtualInstanceType::LAST_VIRTUAL_TYPE) + 1
Definition at line 112 of file object-stats.h.
Referenced by v8::internal::Heap::GetObjectTypeName(), v8::internal::Heap::NumberOfTrackedHeapObjectTypes(), v8::internal::Heap::ObjectCountAtLastGC(), and v8::internal::Heap::ObjectSizeAtLastGC().
over_allocated_
size_t v8::internal::ObjectStats::over_allocated_[OBJECT_STATS_COUNT] [private]
Definition at line 163 of file object-stats.h.
Referenced by ClearObjectStats(), DumpInstanceTypeData(), PrintInstanceTypeJSON(), RecordObjectStats(), and RecordVirtualObjectStats().
over_allocated_histogram_
size_t v8::internal::ObjectStats::over_allocated_histogram_[OBJECT_STATS_COUNT][kNumberOfBuckets] [private]
Definition at line 166 of file object-stats.h.
Referenced by ClearObjectStats(), DumpInstanceTypeData(), PrintInstanceTypeJSON(), RecordObjectStats(), and RecordVirtualObjectStats().
raw_fields_count_
size_t v8::internal::ObjectStats::raw_fields_count_ [private]
Definition at line 173 of file object-stats.h.
Referenced by ClearObjectStats(), Dump(), and PrintJSON().
size_histogram_
size_t v8::internal::ObjectStats::size_histogram_[OBJECT_STATS_COUNT][kNumberOfBuckets] [private]
Definition at line 165 of file object-stats.h.
Referenced by ClearObjectStats(), DumpInstanceTypeData(), PrintInstanceTypeJSON(), RecordObjectStats(), and RecordVirtualObjectStats().
string_data_count_
size_t v8::internal::ObjectStats::string_data_count_ [private]
Definition at line 172 of file object-stats.h.
Referenced by ClearObjectStats(), Dump(), and PrintJSON().
tagged_fields_count_
size_t v8::internal::ObjectStats::tagged_fields_count_ [private]
Definition at line 168 of file object-stats.h.
Referenced by ClearObjectStats(), Dump(), and PrintJSON().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/object-stats.h
/mnt/V8SourceCode/src/heap/object-stats.cc