v8::internal::wasm::WireBytesStorage Class Reference
#include <compilation-environment.h>
Public Member Functions
virtual ~WireBytesStorage ()=default
virtual base::Vector< const uint8_t > GetCode (WireBytesRef) const =0
virtual std::optional< ModuleWireBytes > GetModuleBytes () const =0
Detailed Description
Definition at line 86 of file compilation-environment.h.
Constructor & Destructor Documentation
 WireBytesStorage()
virtual v8::internal::wasm::WireBytesStorage::~WireBytesStorage () [virtual], [default]
Member Function Documentation
GetCode()
virtual base::Vector<const uint8_t> v8::internal::wasm::WireBytesStorage::GetCode (WireBytesRef) const [pure virtual]
Implemented in v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::NativeModuleWireBytesStorage, and v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer.
Referenced by v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall().
GetModuleBytes()
virtual std::optional<ModuleWireBytes> v8::internal::wasm::WireBytesStorage::GetModuleBytes () const [pure virtual]
Implemented in v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::NativeModuleWireBytesStorage, and v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer.
Referenced by v8::internal::compiler::GetDebugName().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/compilation-environment.h