v8::internal::wasm::WasmError Class Reference
#include <wasm-result.h>
Public Member Functions
WasmError ()=default
WasmError (uint32_t offset, std::string message)
WasmError (uint32_t offset, const char *format,...)
bool has_error () const
operator bool () const
uint32_t offset () const
const std::string & message () const &
std::string && message () &&
Static Protected Member Functions
static std::string FormatError (const char *format, va_list args)
Private Attributes
uint32_t offset_ = kNoErrorOffset
std::string message_
Static Private Attributes
static constexpr uint32_t kNoErrorOffset = kMaxUInt32
Detailed Description
Definition at line 26 of file wasm-result.h.
Constructor & Destructor Documentation
WasmError() [1/3]
v8::internal::wasm::WasmError::WasmError () [default]
WasmError() [2/3]
v8::internal::wasm::WasmError::WasmError (uint32_t offset, std::string message) [inline]
Definition at line 30 of file wasm-result.h.
      : offset_(offset), message_(std::move(message)) {
    DCHECK_NE(kNoErrorOffset, offset);
    DCHECK(!message_.empty());
  }
References v8::internal::DCHECK(), and DCHECK_NE.
WasmError() [3/3]
v8::internal::wasm::WasmError::WasmError (uint32_t offset, const char * format, ...) [inline]
Definition at line 37 of file wasm-result.h.
                                                      : offset_(offset) {
    DCHECK_NE(kNoErrorOffset, offset);
    va_list args;
    va_start(args, format);
    message_ = FormatError(format, args);
    va_end(args);
    DCHECK(!message_.empty());
  }
References v8::base::args, v8::internal::DCHECK(), DCHECK_NE, and v8::internal::format.
Member Function Documentation
FormatError()
std::string v8::internal::wasm::WasmError::FormatError (const char * format, va_list args) [static], [protected]
Definition at line 52 of file wasm-result.cc.
                                                                 {
  std::string result;
  VPrintFToString(&result, 0, format, args);
  return result;
}
References v8::base::args, v8::internal::format, v8::base::internal::result, v8::internal::string, and v8::internal::wasm::anonymous_namespace{wasm-result.cc}::VPrintFToString().
has_error()
bool v8::internal::wasm::WasmError::has_error () const [inline]
Definition at line 46 of file wasm-result.h.
                         {
    DCHECK_EQ(offset_ == kNoErrorOffset, message_.empty());
    return offset_ != kNoErrorOffset;
  }
References DCHECK_EQ.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule(), v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::Result< T >::failed(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), v8::internal::wasm::WasmEngine::SyncValidate(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::ValidateFunctionsTask().
message() [1/2]
std::string&& v8::internal::wasm::WasmError::message () && [inline]
Definition at line 55 of file wasm-result.h.
{ return std::move(message_); }
message() [2/2]
const std::string& v8::internal::wasm::WasmError::message () const & [inline]
Definition at line 54 of file wasm-result.h.
{ return message_; }
Referenced by v8::internal::wasm::Disassemble(), v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::GetWasmErrorWithName(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::wasm::Decoder::toResult(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TraceFailed().
offset()
uint32_t v8::internal::wasm::WasmError::offset () const [inline]
Definition at line 53 of file wasm-result.h.
{ return offset_; }
Referenced by v8::internal::wasm::Disassemble(), v8::internal::wasm::GetWasmErrorWithName(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::SetError(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TraceFailed().
operator bool()
v8::internal::wasm::WasmError::operator bool () const [inline]
Definition at line 51 of file wasm-result.h.
{ return has_error(); }
Member Data Documentation
kNoErrorOffset
constexpr uint32_t v8::internal::wasm::WasmError::kNoErrorOffset = kMaxUInt32 [static], [constexpr], [private]
Definition at line 61 of file wasm-result.h.
message_
std::string v8::internal::wasm::WasmError::message_ [private]
Definition at line 63 of file wasm-result.h.
offset_
uint32_t v8::internal::wasm::WasmError::offset_ = kNoErrorOffset [private]
Definition at line 62 of file wasm-result.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-result.h
/mnt/V8SourceCode/src/wasm/wasm-result.cc