v8::internal::compiler::UnwindingInfoWriter Class Reference
#include <unwinding-info-writer-arm.h>
Classes
class BlockInitialState
Public Member Functions
UnwindingInfoWriter (Zone *zone)
void SetNumberOfInstructionBlocks (int number)
void BeginInstructionBlock (int pc_offset, const InstructionBlock *block)
void EndInstructionBlock (const InstructionBlock *block)
void MarkLinkRegisterOnTopOfStack (int pc_offset)
void MarkPopLinkRegisterFromTopOfStack (int pc_offset)
void MarkFrameConstructed (int at_pc)
void MarkFrameDeconstructed (int at_pc)
void MarkBlockWillExit ()
void Finish (int code_size)
EhFrameWriter * eh_frame_writer ()
UnwindingInfoWriter (Zone *zone)
void SetNumberOfInstructionBlocks (int number)
void BeginInstructionBlock (int pc_offset, const InstructionBlock *block)
void EndInstructionBlock (const InstructionBlock *block)
void MarkLinkRegisterOnTopOfStack (int pc_offset, const Register &sp)
void MarkPopLinkRegisterFromTopOfStack (int pc_offset)
void MarkFrameConstructed (int at_pc)
void MarkFrameDeconstructed (int at_pc)
void MarkBlockWillExit ()
void Finish (int code_size)
EhFrameWriter * eh_frame_writer ()
UnwindingInfoWriter (Zone *zone)
void SetNumberOfInstructionBlocks (int number)
void BeginInstructionBlock (int pc_offset, const InstructionBlock *block)
void EndInstructionBlock (const InstructionBlock *block)
void MarkLinkRegisterOnTopOfStack (int pc_offset)
void MarkPopLinkRegisterFromTopOfStack (int pc_offset)
void MarkFrameConstructed (int at_pc)
void MarkFrameDeconstructed (int at_pc)
void MarkBlockWillExit ()
void Finish (int code_size)
EhFrameWriter * eh_frame_writer ()
UnwindingInfoWriter (Zone *zone)
void SetNumberOfInstructionBlocks (int number)
void BeginInstructionBlock (int pc_offset, const InstructionBlock *block)
void EndInstructionBlock (const InstructionBlock *block)
void MarkLinkRegisterOnTopOfStack (int pc_offset)
void MarkPopLinkRegisterFromTopOfStack (int pc_offset)
void MarkFrameConstructed (int at_pc)
void MarkFrameDeconstructed (int at_pc)
void MarkBlockWillExit ()
void Finish (int code_size)
EhFrameWriter * eh_frame_writer ()
UnwindingInfoWriter (Zone *)
void SetNumberOfInstructionBlocks (int number)
void BeginInstructionBlock (int pc_offset, const InstructionBlock *)
void EndInstructionBlock (const InstructionBlock *)
void Finish (int code_size)
EhFrameWriter * eh_frame_writer ()
UnwindingInfoWriter (Zone *zone)
void MaybeIncreaseBaseOffsetAt (int pc_offset, int base_delta)
void SetNumberOfInstructionBlocks (int number)
void BeginInstructionBlock (int pc_offset, const InstructionBlock *block)
void EndInstructionBlock (const InstructionBlock *block)
void MarkFrameConstructed (int pc_base)
void MarkFrameDeconstructed (int pc_base)
void MarkBlockWillExit ()
void Finish (int code_size)
EhFrameWriter * eh_frame_writer ()
Private Member Functions
bool enabled () const
bool enabled () const
bool enabled () const
bool enabled () const
bool enabled () const
Private Attributes
Zone * zone_
EhFrameWriter eh_frame_writer_
bool saved_lr_
bool block_will_exit_
ZoneVector< const BlockInitialState * > block_initial_states_
bool tracking_fp_
Detailed Description
Definition at line 17 of file unwinding-info-writer-arm.h.
Constructor & Destructor Documentation
UnwindingInfoWriter() [1/6]
v8::internal::compiler::UnwindingInfoWriter::UnwindingInfoWriter (Zone * zone) [inline], [explicit]
Definition at line 19 of file unwinding-info-writer-arm.h.
      : zone_(zone),
        eh_frame_writer_(zone),
        saved_lr_(false),
        block_will_exit_(false),
        block_initial_states_(zone) {
    if (enabled()) eh_frame_writer_.Initialize();
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Initialize().
UnwindingInfoWriter() [2/6]
v8::internal::compiler::UnwindingInfoWriter::UnwindingInfoWriter (Zone * zone) [inline], [explicit]
Definition at line 19 of file unwinding-info-writer-arm64.h.
      : zone_(zone),
        eh_frame_writer_(zone),
        saved_lr_(false),
        block_will_exit_(false),
        block_initial_states_(zone) {
    if (enabled()) eh_frame_writer_.Initialize();
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Initialize().
UnwindingInfoWriter() [3/6]
v8::internal::compiler::UnwindingInfoWriter::UnwindingInfoWriter (Zone * zone) [inline], [explicit]
Definition at line 19 of file unwinding-info-writer-ppc.h.
      : zone_(zone),
        eh_frame_writer_(zone),
        saved_lr_(false),
        block_will_exit_(false),
        block_initial_states_(zone) {
    if (enabled()) eh_frame_writer_.Initialize();
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Initialize().
UnwindingInfoWriter() [4/6]
v8::internal::compiler::UnwindingInfoWriter::UnwindingInfoWriter (Zone * zone) [inline], [explicit]
Definition at line 19 of file unwinding-info-writer-s390.h.
      : zone_(zone),
        eh_frame_writer_(zone),
        saved_lr_(false),
        block_will_exit_(false),
        block_initial_states_(zone) {
    if (enabled()) eh_frame_writer_.Initialize();
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Initialize().
UnwindingInfoWriter() [5/6]
v8::internal::compiler::UnwindingInfoWriter::UnwindingInfoWriter (Zone *) [inline], [explicit]
Definition at line 42 of file unwinding-info-writer.h.
{}
UnwindingInfoWriter() [6/6]
v8::internal::compiler::UnwindingInfoWriter::UnwindingInfoWriter (Zone * zone) [inline], [explicit]
Definition at line 19 of file unwinding-info-writer-x64.h.
      : zone_(zone),
        eh_frame_writer_(zone),
        tracking_fp_(false),
        block_will_exit_(false),
        block_initial_states_(zone) {
    if (enabled()) eh_frame_writer_.Initialize();
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Initialize().
Member Function Documentation
BeginInstructionBlock() [1/6]
void v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock (int pc_offset, const InstructionBlock *) [inline]
Definition at line 46 of file unwinding-info-writer.h.
{}
BeginInstructionBlock() [2/6]
void v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock (int pc_offset, const InstructionBlock * block)
Definition at line 12 of file unwinding-info-writer-arm.cc.
                                                                               {
  if (!enabled()) return;
  block_will_exit_ = false;
  DCHECK_LT(block->rpo_number().ToInt(),
            static_cast<int>(block_initial_states_.size()));
  const BlockInitialState* initial_state =
      block_initial_states_[block->rpo_number().ToInt()];
  if (!initial_state) return;
  if (initial_state->saved_lr_ != saved_lr_) {
    eh_frame_writer_.AdvanceLocation(pc_offset);
    if (initial_state->saved_lr_) {
      eh_frame_writer_.RecordRegisterSavedToStack(lr, kSystemPointerSize);
    } else {
      eh_frame_writer_.RecordRegisterFollowsInitialRule(lr);
    }
    saved_lr_ = initial_state->saved_lr_;
  }
}
References v8::internal::EhFrameWriter::AdvanceLocation(), block_initial_states_, block_will_exit_, DCHECK_LT, eh_frame_writer_, enabled(), v8::internal::kSystemPointerSize, v8::internal::EhFrameWriter::RecordRegisterFollowsInitialRule(), v8::internal::EhFrameWriter::RecordRegisterSavedToStack(), v8::internal::compiler::InstructionBlock::rpo_number(), v8::internal::compiler::UnwindingInfoWriter::BlockInitialState::saved_lr_, saved_lr_, and v8::internal::compiler::RpoNumber::ToInt().
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode().
BeginInstructionBlock() [3/6]
void v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock (int pc_offset, const InstructionBlock * block)
BeginInstructionBlock() [4/6]
void v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock (int pc_offset, const InstructionBlock * block)
BeginInstructionBlock() [5/6]
void v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock (int pc_offset, const InstructionBlock * block)
BeginInstructionBlock() [6/6]
void v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock (int pc_offset, const InstructionBlock * block)
eh_frame_writer() [1/6]
EhFrameWriter* v8::internal::compiler::UnwindingInfoWriter::eh_frame_writer () [inline]
Definition at line 47 of file unwinding-info-writer-arm.h.
                                   {
    return enabled() ? &eh_frame_writer_ : nullptr;
  }
References eh_frame_writer_, and enabled().
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
eh_frame_writer() [2/6]
EhFrameWriter* v8::internal::compiler::UnwindingInfoWriter::eh_frame_writer () [inline]
Definition at line 47 of file unwinding-info-writer-arm64.h.
                                   {
    return enabled() ? &eh_frame_writer_ : nullptr;
  }
References eh_frame_writer_, and enabled().
eh_frame_writer() [3/6]
EhFrameWriter* v8::internal::compiler::UnwindingInfoWriter::eh_frame_writer () [inline]
Definition at line 47 of file unwinding-info-writer-ppc.h.
                                   {
    return enabled() ? &eh_frame_writer_ : nullptr;
  }
References eh_frame_writer_, and enabled().
eh_frame_writer() [4/6]
EhFrameWriter* v8::internal::compiler::UnwindingInfoWriter::eh_frame_writer () [inline]
Definition at line 47 of file unwinding-info-writer-s390.h.
                                   {
    return enabled() ? &eh_frame_writer_ : nullptr;
  }
References eh_frame_writer_, and enabled().
eh_frame_writer() [5/6]
EhFrameWriter* v8::internal::compiler::UnwindingInfoWriter::eh_frame_writer () [inline]
Definition at line 52 of file unwinding-info-writer.h.
{ return nullptr; }
eh_frame_writer() [6/6]
EhFrameWriter* v8::internal::compiler::UnwindingInfoWriter::eh_frame_writer () [inline]
Definition at line 51 of file unwinding-info-writer-x64.h.
                                   {
    return enabled() ? &eh_frame_writer_ : nullptr;
  }
References eh_frame_writer_, and enabled().
enabled() [1/5]
bool v8::internal::compiler::UnwindingInfoWriter::enabled () const [inline], [private]
Definition at line 52 of file unwinding-info-writer-arm.h.
{ return v8_flags.perf_prof_unwinding_info; }
References v8::internal::v8_flags.
Referenced by BeginInstructionBlock(), eh_frame_writer(), EndInstructionBlock(), Finish(), MarkFrameConstructed(), MarkFrameDeconstructed(), MarkLinkRegisterOnTopOfStack(), MarkPopLinkRegisterFromTopOfStack(), MaybeIncreaseBaseOffsetAt(), SetNumberOfInstructionBlocks(), and UnwindingInfoWriter().
enabled() [2/5]
bool v8::internal::compiler::UnwindingInfoWriter::enabled () const [inline], [private]
Definition at line 52 of file unwinding-info-writer-arm64.h.
{ return v8_flags.perf_prof_unwinding_info; }
References v8::internal::v8_flags.
enabled() [3/5]
bool v8::internal::compiler::UnwindingInfoWriter::enabled () const [inline], [private]
Definition at line 52 of file unwinding-info-writer-ppc.h.
{ return v8_flags.perf_prof_unwinding_info; }
References v8::internal::v8_flags.
enabled() [4/5]
bool v8::internal::compiler::UnwindingInfoWriter::enabled () const [inline], [private]
Definition at line 52 of file unwinding-info-writer-s390.h.
{ return v8_flags.perf_prof_unwinding_info; }
References v8::internal::v8_flags.
enabled() [5/5]
bool v8::internal::compiler::UnwindingInfoWriter::enabled () const [inline], [private]
Definition at line 56 of file unwinding-info-writer-x64.h.
{ return v8_flags.perf_prof_unwinding_info; }
References v8::internal::v8_flags.
EndInstructionBlock() [1/6]
void v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock (const InstructionBlock *) [inline]
Definition at line 48 of file unwinding-info-writer.h.
{}
EndInstructionBlock() [2/6]
void v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock (const InstructionBlock * block)
Definition at line 34 of file unwinding-info-writer-arm.cc.
                                                                           {
  if (!enabled() || block_will_exit_) return;
  for (const RpoNumber& successor : block->successors()) {
    int successor_index = successor.ToInt();
    DCHECK_LT(successor_index, static_cast<int>(block_initial_states_.size()));
    const BlockInitialState* existing_state =
        block_initial_states_[successor_index];
    // If we already had an entry for this BB, check that the values are the
    // same we are trying to insert.
    if (existing_state) {
      DCHECK_EQ(existing_state->saved_lr_, saved_lr_);
    } else {
      block_initial_states_[successor_index] =
          zone_->New<BlockInitialState>(saved_lr_);
    }
  }
}
References block_initial_states_, block_will_exit_, DCHECK_EQ, DCHECK_LT, enabled(), v8::internal::Zone::New(), v8::internal::compiler::UnwindingInfoWriter::BlockInitialState::saved_lr_, saved_lr_, v8::internal::compiler::InstructionBlock::successors(), and zone_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode().
EndInstructionBlock() [3/6]
void v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock (const InstructionBlock * block)
EndInstructionBlock() [4/6]
void v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock (const InstructionBlock * block)
EndInstructionBlock() [5/6]
void v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock (const InstructionBlock * block)
EndInstructionBlock() [6/6]
void v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock (const InstructionBlock * block)
Finish() [1/6]
void v8::internal::compiler::UnwindingInfoWriter::Finish (int code_size) [inline]
Definition at line 43 of file unwinding-info-writer-arm.h.
                             {
    if (enabled()) eh_frame_writer_.Finish(code_size);
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Finish().
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode().
Finish() [2/6]
void v8::internal::compiler::UnwindingInfoWriter::Finish (int code_size) [inline]
Definition at line 43 of file unwinding-info-writer-arm64.h.
                             {
    if (enabled()) eh_frame_writer_.Finish(code_size);
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Finish().
Finish() [3/6]
void v8::internal::compiler::UnwindingInfoWriter::Finish (int code_size) [inline]
Definition at line 43 of file unwinding-info-writer-ppc.h.
                             {
    if (enabled()) eh_frame_writer_.Finish(code_size);
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Finish().
Finish() [4/6]
void v8::internal::compiler::UnwindingInfoWriter::Finish (int code_size) [inline]
Definition at line 43 of file unwinding-info-writer-s390.h.
                             {
    if (enabled()) eh_frame_writer_.Finish(code_size);
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Finish().
Finish() [5/6]
void v8::internal::compiler::UnwindingInfoWriter::Finish (int code_size) [inline]
Definition at line 50 of file unwinding-info-writer.h.
{}
Finish() [6/6]
void v8::internal::compiler::UnwindingInfoWriter::Finish (int code_size) [inline]
Definition at line 47 of file unwinding-info-writer-x64.h.
                             {
    if (enabled()) eh_frame_writer_.Finish(code_size);
  }
References eh_frame_writer_, enabled(), and v8::internal::EhFrameWriter::Finish().
MarkBlockWillExit() [1/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkBlockWillExit () [inline]
Definition at line 41 of file unwinding-info-writer-arm.h.
{ block_will_exit_ = true; }
References block_will_exit_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), and v8::internal::compiler::CodeGenerator::AssembleReturn().
MarkBlockWillExit() [2/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkBlockWillExit () [inline]
Definition at line 41 of file unwinding-info-writer-arm64.h.
{ block_will_exit_ = true; }
References block_will_exit_.
MarkBlockWillExit() [3/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkBlockWillExit () [inline]
Definition at line 41 of file unwinding-info-writer-ppc.h.
{ block_will_exit_ = true; }
References block_will_exit_.
MarkBlockWillExit() [4/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkBlockWillExit () [inline]
Definition at line 41 of file unwinding-info-writer-s390.h.
{ block_will_exit_ = true; }
References block_will_exit_.
MarkBlockWillExit() [5/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkBlockWillExit () [inline]
Definition at line 45 of file unwinding-info-writer-x64.h.
{ block_will_exit_ = true; }
References block_will_exit_.
MarkFrameConstructed() [1/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameConstructed (int at_pc)
Definition at line 54 of file unwinding-info-writer-arm.cc.
                                                        {
  if (!enabled()) return;
  // Regardless of the type of frame constructed, the relevant part of the
  // layout is always the one in the diagram:
  //
  // | .... | higher addresses
  // +----------+ ^
  // | LR | | |
  // +----------+ | |
  // | saved FP | | |
  // +----------+ <-- FP v
  // | .... | stack growth
  //
  // The LR is pushed on the stack, and we can record this fact at the end of
  // the construction, since the LR itself is not modified in the process.
  eh_frame_writer_.AdvanceLocation(at_pc);
  eh_frame_writer_.RecordRegisterSavedToStack(lr, kSystemPointerSize);
  saved_lr_ = true;
}
References v8::internal::EhFrameWriter::AdvanceLocation(), eh_frame_writer_, enabled(), v8::internal::kSystemPointerSize, v8::internal::EhFrameWriter::RecordRegisterSavedToStack(), and saved_lr_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleConstructFrame().
MarkFrameConstructed() [2/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameConstructed (int at_pc)
MarkFrameConstructed() [3/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameConstructed (int at_pc)
MarkFrameConstructed() [4/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameConstructed (int at_pc)
MarkFrameConstructed() [5/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameConstructed (int pc_base)
MarkFrameDeconstructed() [1/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameDeconstructed (int at_pc)
Definition at line 75 of file unwinding-info-writer-arm.cc.
                                                          {
  if (!enabled()) return;
  // The lr is restored by the last operation in LeaveFrame().
  eh_frame_writer_.AdvanceLocation(at_pc);
  eh_frame_writer_.RecordRegisterFollowsInitialRule(lr);
  saved_lr_ = false;
}
References v8::internal::EhFrameWriter::AdvanceLocation(), eh_frame_writer_, enabled(), v8::internal::EhFrameWriter::RecordRegisterFollowsInitialRule(), and saved_lr_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeconstructFrame().
MarkFrameDeconstructed() [2/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameDeconstructed (int at_pc)
MarkFrameDeconstructed() [3/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameDeconstructed (int at_pc)
MarkFrameDeconstructed() [4/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameDeconstructed (int at_pc)
MarkFrameDeconstructed() [5/5]
void v8::internal::compiler::UnwindingInfoWriter::MarkFrameDeconstructed (int pc_base)
MarkLinkRegisterOnTopOfStack() [1/4]
void v8::internal::compiler::UnwindingInfoWriter::MarkLinkRegisterOnTopOfStack (int pc_offset)
Definition at line 84 of file unwinding-info-writer-arm.cc.
                                                                    {
  if (!enabled()) return;
  eh_frame_writer_.AdvanceLocation(pc_offset);
  eh_frame_writer_.SetBaseAddressRegisterAndOffset(sp, 0);
  eh_frame_writer_.RecordRegisterSavedToStack(lr, 0);
}
References v8::internal::EhFrameWriter::AdvanceLocation(), eh_frame_writer_, enabled(), v8::internal::EhFrameWriter::RecordRegisterSavedToStack(), and v8::internal::EhFrameWriter::SetBaseAddressRegisterAndOffset().
MarkLinkRegisterOnTopOfStack() [2/4]
void v8::internal::compiler::UnwindingInfoWriter::MarkLinkRegisterOnTopOfStack (int pc_offset)
MarkLinkRegisterOnTopOfStack() [3/4]
void v8::internal::compiler::UnwindingInfoWriter::MarkLinkRegisterOnTopOfStack (int pc_offset)
MarkLinkRegisterOnTopOfStack() [4/4]
void v8::internal::compiler::UnwindingInfoWriter::MarkLinkRegisterOnTopOfStack (int pc_offset, const Register & sp)
Definition at line 89 of file unwinding-info-writer-arm64.cc.
                                                                           {
  if (!enabled()) return;
  eh_frame_writer_.AdvanceLocation(pc_offset);
  eh_frame_writer_.SetBaseAddressRegisterAndOffset(sp, 0);
  eh_frame_writer_.RecordRegisterSavedToStack(lr, 0);
}
References v8::internal::EhFrameWriter::AdvanceLocation(), eh_frame_writer_, enabled(), v8::internal::EhFrameWriter::RecordRegisterSavedToStack(), and v8::internal::EhFrameWriter::SetBaseAddressRegisterAndOffset().
MarkPopLinkRegisterFromTopOfStack() [1/4]
void v8::internal::compiler::UnwindingInfoWriter::MarkPopLinkRegisterFromTopOfStack (int pc_offset)
Definition at line 92 of file unwinding-info-writer-arm.cc.
                                                                         {
  if (!enabled()) return;
  eh_frame_writer_.AdvanceLocation(pc_offset);
  eh_frame_writer_.SetBaseAddressRegisterAndOffset(fp, 0);
  eh_frame_writer_.RecordRegisterFollowsInitialRule(lr);
}
References v8::internal::EhFrameWriter::AdvanceLocation(), eh_frame_writer_, enabled(), v8::internal::EhFrameWriter::RecordRegisterFollowsInitialRule(), and v8::internal::EhFrameWriter::SetBaseAddressRegisterAndOffset().
MarkPopLinkRegisterFromTopOfStack() [2/4]
void v8::internal::compiler::UnwindingInfoWriter::MarkPopLinkRegisterFromTopOfStack (int pc_offset)
MarkPopLinkRegisterFromTopOfStack() [3/4]
void v8::internal::compiler::UnwindingInfoWriter::MarkPopLinkRegisterFromTopOfStack (int pc_offset)
MarkPopLinkRegisterFromTopOfStack() [4/4]
void v8::internal::compiler::UnwindingInfoWriter::MarkPopLinkRegisterFromTopOfStack (int pc_offset)
MaybeIncreaseBaseOffsetAt()
void v8::internal::compiler::UnwindingInfoWriter::MaybeIncreaseBaseOffsetAt (int pc_offset, int base_delta) [inline]
Definition at line 28 of file unwinding-info-writer-x64.h.
                                                                {
    if (enabled() && !tracking_fp_) {
      eh_frame_writer_.AdvanceLocation(pc_offset);
      eh_frame_writer_.IncreaseBaseAddressOffset(base_delta);
    }
  }
References v8::internal::EhFrameWriter::AdvanceLocation(), eh_frame_writer_, enabled(), v8::internal::EhFrameWriter::IncreaseBaseAddressOffset(), and tracking_fp_.
SetNumberOfInstructionBlocks() [1/6]
void v8::internal::compiler::UnwindingInfoWriter::SetNumberOfInstructionBlocks (int number) [inline]
Definition at line 28 of file unwinding-info-writer-arm.h.
                                                {
    if (enabled()) block_initial_states_.resize(number);
  }
References block_initial_states_, and enabled().
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode().
SetNumberOfInstructionBlocks() [2/6]
void v8::internal::compiler::UnwindingInfoWriter::SetNumberOfInstructionBlocks (int number) [inline]
Definition at line 28 of file unwinding-info-writer-arm64.h.
                                                {
    if (enabled()) block_initial_states_.resize(number);
  }
References block_initial_states_, and enabled().
SetNumberOfInstructionBlocks() [3/6]
void v8::internal::compiler::UnwindingInfoWriter::SetNumberOfInstructionBlocks (int number) [inline]
Definition at line 28 of file unwinding-info-writer-ppc.h.
                                                {
    if (enabled()) block_initial_states_.resize(number);
  }
References block_initial_states_, and enabled().
SetNumberOfInstructionBlocks() [4/6]
void v8::internal::compiler::UnwindingInfoWriter::SetNumberOfInstructionBlocks (int number) [inline]
Definition at line 28 of file unwinding-info-writer-s390.h.
                                                {
    if (enabled()) block_initial_states_.resize(number);
  }
References block_initial_states_, and enabled().
SetNumberOfInstructionBlocks() [5/6]
void v8::internal::compiler::UnwindingInfoWriter::SetNumberOfInstructionBlocks (int number) [inline]
Definition at line 44 of file unwinding-info-writer.h.
{}
SetNumberOfInstructionBlocks() [6/6]
void v8::internal::compiler::UnwindingInfoWriter::SetNumberOfInstructionBlocks (int number) [inline]
Definition at line 35 of file unwinding-info-writer-x64.h.
                                                {
    if (enabled()) block_initial_states_.resize(number);
  }
References block_initial_states_, and enabled().
Member Data Documentation
block_initial_states_
ZoneVector< const BlockInitialState * > v8::internal::compiler::UnwindingInfoWriter::block_initial_states_ [private]
Definition at line 66 of file unwinding-info-writer-arm.h.
Referenced by BeginInstructionBlock(), EndInstructionBlock(), and SetNumberOfInstructionBlocks().
block_will_exit_
bool v8::internal::compiler::UnwindingInfoWriter::block_will_exit_ [private]
Definition at line 64 of file unwinding-info-writer-arm.h.
Referenced by BeginInstructionBlock(), EndInstructionBlock(), and MarkBlockWillExit().
eh_frame_writer_
EhFrameWriter v8::internal::compiler::UnwindingInfoWriter::eh_frame_writer_ [private]
Definition at line 62 of file unwinding-info-writer-arm.h.
Referenced by BeginInstructionBlock(), eh_frame_writer(), Finish(), MarkFrameConstructed(), MarkFrameDeconstructed(), MarkLinkRegisterOnTopOfStack(), MarkPopLinkRegisterFromTopOfStack(), MaybeIncreaseBaseOffsetAt(), and UnwindingInfoWriter().
saved_lr_
bool v8::internal::compiler::UnwindingInfoWriter::saved_lr_ [private]
Definition at line 63 of file unwinding-info-writer-arm.h.
Referenced by BeginInstructionBlock(), EndInstructionBlock(), MarkFrameConstructed(), and MarkFrameDeconstructed().
tracking_fp_
bool v8::internal::compiler::UnwindingInfoWriter::tracking_fp_ [private]
Definition at line 70 of file unwinding-info-writer-x64.h.
Referenced by MaybeIncreaseBaseOffsetAt().
zone_
Zone * v8::internal::compiler::UnwindingInfoWriter::zone_ [private]
Definition at line 61 of file unwinding-info-writer-arm.h.
Referenced by EndInstructionBlock().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/arm/unwinding-info-writer-arm.h
/mnt/V8SourceCode/src/compiler/backend/arm64/unwinding-info-writer-arm64.h
/mnt/V8SourceCode/src/compiler/backend/ppc/unwinding-info-writer-ppc.h
/mnt/V8SourceCode/src/compiler/backend/s390/unwinding-info-writer-s390.h
/mnt/V8SourceCode/src/compiler/backend/x64/unwinding-info-writer-x64.h
/mnt/V8SourceCode/src/compiler/backend/unwinding-info-writer.h
/mnt/V8SourceCode/src/compiler/backend/arm/unwinding-info-writer-arm.cc
/mnt/V8SourceCode/src/compiler/backend/arm64/unwinding-info-writer-arm64.cc
/mnt/V8SourceCode/src/compiler/backend/ppc/unwinding-info-writer-ppc.cc
/mnt/V8SourceCode/src/compiler/backend/s390/unwinding-info-writer-s390.cc
/mnt/V8SourceCode/src/compiler/backend/x64/unwinding-info-writer-x64.cc