v8::internal::wasm::CompilationState Class Reference
#include <compilation-environment.h>
Public Member Functions
~CompilationState ()
void operator delete (void *ptr)
CompilationState ()=delete
void InitCompileJob ()
void CancelCompilation ()
void CancelInitialCompilation ()
void SetError ()
void SetWireBytesStorage (std::shared_ptr< WireBytesStorage >)
std::shared_ptr< WireBytesStorage > GetWireBytesStorage () const
void AddCallback (std::unique_ptr< CompilationEventCallback > callback)
void InitializeAfterDeserialization (base::Vector< const int > lazy_functions, base::Vector< const int > eager_functions)
void SetHighPriority ()
void TierUpAllFunctions ()
void AllowAnotherTopTierJob (uint32_t func_index)
void AllowAnotherTopTierJobForAllFunctions ()
bool failed () const
bool baseline_compilation_finished () const
void set_compilation_id (int compilation_id)
size_t EstimateCurrentMemoryConsumption () const
std::vector< WasmCode * > PublishCode (base::Vector< UnpublishedWasmCode > unpublished_code)
WasmDetectedFeatures detected_features () const
V8_WARN_UNUSED_RESULT WasmDetectedFeatures UpdateDetectedFeatures (WasmDetectedFeatures)
Static Private Member Functions
static std::unique_ptr< CompilationState > New (const std::shared_ptr< NativeModule > &, std::shared_ptr< Counters >, WasmDetectedFeatures detected_features)
Friends
class NativeModule
Detailed Description
Definition at line 125 of file compilation-environment.h.
Constructor & Destructor Documentation
 CompilationState()
v8::internal::wasm::CompilationState::~CompilationState ()
Definition at line 889 of file module-compiler.cc.
{ Impl(this)->~CompilationStateImpl(); }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::~CompilationStateImpl().
CompilationState()
v8::internal::wasm::CompilationState::CompilationState () [delete]
Member Function Documentation
AddCallback()
void v8::internal::wasm::CompilationState::AddCallback (std::unique_ptr< CompilationEventCallback > callback)
Definition at line 914 of file module-compiler.cc.
                                                      {
  return Impl(this)->AddCallback(std::move(callback));
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AddCallback(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
AllowAnotherTopTierJob()
void v8::internal::wasm::CompilationState::AllowAnotherTopTierJob (uint32_t func_index)
Definition at line 923 of file module-compiler.cc.
                                                                 {
  Impl(this)->AllowAnotherTopTierJob(func_index);
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AllowAnotherTopTierJob(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
AllowAnotherTopTierJobForAllFunctions()
void v8::internal::wasm::CompilationState::AllowAnotherTopTierJobForAllFunctions ()
Definition at line 927 of file module-compiler.cc.
                                                             {
  Impl(this)->AllowAnotherTopTierJobForAllFunctions();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AllowAnotherTopTierJobForAllFunctions(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
baseline_compilation_finished()
bool v8::internal::wasm::CompilationState::baseline_compilation_finished () const
Definition at line 940 of file module-compiler.cc.
                                                           {
  return Impl(this)->baseline_compilation_finished();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::baseline_compilation_finished(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
CancelCompilation()
void v8::internal::wasm::CompilationState::CancelCompilation ()
Definition at line 893 of file module-compiler.cc.
                                         {
  Impl(this)->CancelCompilation(CompilationStateImpl::kCancelUnconditionally);
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::CancelCompilation(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
CancelInitialCompilation()
void v8::internal::wasm::CompilationState::CancelInitialCompilation ()
Definition at line 897 of file module-compiler.cc.
                                                {
  Impl(this)->CancelCompilation(
      CompilationStateImpl::kCancelInitialCompilation);
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::CancelCompilation(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
detected_features()
WasmDetectedFeatures v8::internal::wasm::CompilationState::detected_features () const
Definition at line 967 of file module-compiler.cc.
                                                               {
  return Impl(this)->detected_features();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::detected_features(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
Referenced by New(), UpdateDetectedFeatures(), and v8::internal::wasm::NativeModuleSerializer::WriteHeader().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::CompilationState::EstimateCurrentMemoryConsumption () const
Definition at line 948 of file module-compiler.cc.
                                                                {
  return Impl(this)->EstimateCurrentMemoryConsumption();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::EstimateCurrentMemoryConsumption(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
failed()
bool v8::internal::wasm::CompilationState::failed () const
Definition at line 938 of file module-compiler.cc.
{ return Impl(this)->failed(); }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::failed(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
Referenced by v8::internal::wasm::TierUpNowForTesting().
GetWireBytesStorage()
std::shared_ptr< WireBytesStorage > v8::internal::wasm::CompilationState::GetWireBytesStorage () const
Definition at line 909 of file module-compiler.cc.
          {
  return Impl(this)->GetWireBytesStorage();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::GetWireBytesStorage(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
Referenced by v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction().
InitCompileJob()
void v8::internal::wasm::CompilationState::InitCompileJob ()
Definition at line 891 of file module-compiler.cc.
{ Impl(this)->InitCompileJob(); }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitCompileJob().
InitializeAfterDeserialization()
void v8::internal::wasm::CompilationState::InitializeAfterDeserialization (base::Vector< const int > lazy_functions, base::Vector< const int > eager_functions)
Definition at line 931 of file module-compiler.cc.
                                           {
  Impl(this)->InitializeCompilationProgressAfterDeserialization(
      lazy_functions, eager_functions);
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization().
New()
std::unique_ptr< CompilationState > v8::internal::wasm::CompilationState::New (const std::shared_ptr< NativeModule > & native_module, std::shared_ptr< Counters > async_counters, WasmDetectedFeatures detected_features) [static], [private]
Definition at line 958 of file module-compiler.cc.
                                            {
  return std::unique_ptr<CompilationState>(reinterpret_cast<CompilationState*>(
      new CompilationStateImpl(std::move(native_module),
                               std::move(async_counters), detected_features)));
}
References detected_features().
Referenced by v8::internal::wasm::NativeModule::NativeModule().
operator delete()
void v8::internal::wasm::CompilationState::operator delete (void * ptr) [inline]
Definition at line 131 of file compilation-environment.h.
{ ::operator delete(ptr); }
PublishCode()
std::vector< WasmCode * > v8::internal::wasm::CompilationState::PublishCode (base::Vector< UnpublishedWasmCode > unpublished_code)
Definition at line 952 of file module-compiler.cc.
                                                      {
  return Impl(this)->PublishCode(unpublished_code);
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishCode().
set_compilation_id()
void v8::internal::wasm::CompilationState::set_compilation_id (int compilation_id)
Definition at line 944 of file module-compiler.cc.
                                                            {
  Impl(this)->set_compilation_id(compilation_id);
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::set_compilation_id().
SetError()
void v8::internal::wasm::CompilationState::SetError ()
Definition at line 902 of file module-compiler.cc.
{ Impl(this)->SetError(); }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::SetError().
Referenced by v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction().
SetHighPriority()
void v8::internal::wasm::CompilationState::SetHighPriority ()
SetWireBytesStorage()
void v8::internal::wasm::CompilationState::SetWireBytesStorage (std::shared_ptr< WireBytesStorage > wire_bytes_storage)
Definition at line 904 of file module-compiler.cc.
                                                        {
  Impl(this)->SetWireBytesStorage(std::move(wire_bytes_storage));
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::SetWireBytesStorage().
TierUpAllFunctions()
void v8::internal::wasm::CompilationState::TierUpAllFunctions ()
Definition at line 919 of file module-compiler.cc.
                                          {
  Impl(this)->TierUpAllFunctions();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions().
UpdateDetectedFeatures()
WasmDetectedFeatures v8::internal::wasm::CompilationState::UpdateDetectedFeatures (WasmDetectedFeatures detected_features)
Definition at line 971 of file module-compiler.cc.
                                            {
  return Impl(this)->UpdateDetectedFeatures(detected_features);
}
References detected_features(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::UpdateDetectedFeatures().
Referenced by v8::internal::wasm::NativeModuleDeserializer::ReadHeader(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions().
Friends And Related Function Documentation
NativeModule
friend class NativeModule [friend]
Definition at line 182 of file compilation-environment.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/compilation-environment.h
/mnt/V8SourceCode/src/wasm/module-compiler.cc