v8::internal::PerClientSafepointData Class Reference
Public Member Functions
PerClientSafepointData (Isolate *isolate)
void set_locked ()
IsolateSafepoint * safepoint () const
Heap * heap () const
Isolate * isolate () const
bool is_locked () const
IsolateSafepoint::RunningLocalHeaps & running ()
const IsolateSafepoint::RunningLocalHeaps & running () const
Private Attributes
Isolate *const isolate_
IsolateSafepoint::RunningLocalHeaps running_
bool locked_ = false
Detailed Description
Definition at line 51 of file safepoint.cc.
Constructor & Destructor Documentation
PerClientSafepointData()
v8::internal::PerClientSafepointData::PerClientSafepointData (Isolate * isolate) [inline], [explicit]
Definition at line 53 of file safepoint.cc.
: isolate_(isolate) {}
Member Function Documentation
heap()
Heap* v8::internal::PerClientSafepointData::heap () const [inline]
Definition at line 58 of file safepoint.cc.
{ return isolate_->heap(); }
References v8::internal::Isolate::heap(), and isolate_.
Referenced by safepoint().
is_locked()
bool v8::internal::PerClientSafepointData::is_locked () const [inline]
Definition at line 61 of file safepoint.cc.
{ return locked_; }
References locked_.
isolate()
Isolate* v8::internal::PerClientSafepointData::isolate () const [inline]
Definition at line 59 of file safepoint.cc.
{ return isolate_; }
References isolate_.
running() [1/2]
IsolateSafepoint::RunningLocalHeaps& v8::internal::PerClientSafepointData::running () [inline]
Definition at line 63 of file safepoint.cc.
{ return running_; }
References running_.
Referenced by v8::internal::IsolateSafepoint::InitiateGlobalSafepointScopeRaw(), and v8::internal::IsolateSafepoint::WaitUntilRunningThreadsInSafepoint().
running() [2/2]
const IsolateSafepoint::RunningLocalHeaps& v8::internal::PerClientSafepointData::running () const [inline]
Definition at line 64 of file safepoint.cc.
                                                           {
    return running_;
  }
References running_.
safepoint()
IsolateSafepoint* v8::internal::PerClientSafepointData::safepoint () const [inline]
Definition at line 57 of file safepoint.cc.
{ return heap()->safepoint(); }
References heap(), and v8::internal::Heap::safepoint().
set_locked()
void v8::internal::PerClientSafepointData::set_locked () [inline]
Definition at line 55 of file safepoint.cc.
{ locked_ = true; }
References locked_.
Referenced by v8::internal::IsolateSafepoint::InitiateGlobalSafepointScopeRaw().
Member Data Documentation
isolate_
Isolate* const v8::internal::PerClientSafepointData::isolate_ [private]
Definition at line 69 of file safepoint.cc.
Referenced by heap(), and isolate().
locked_
bool v8::internal::PerClientSafepointData::locked_ = false [private]
Definition at line 71 of file safepoint.cc.
Referenced by is_locked(), and set_locked().
running_
IsolateSafepoint::RunningLocalHeaps v8::internal::PerClientSafepointData::running_ [private]
Definition at line 70 of file safepoint.cc.
Referenced by running().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/safepoint.cc