v8::internal::FuzzilliExtension Class Reference
#include <fuzzilli.h>
Public Member Functions
FuzzilliExtension (const char *fun_name)
v8::Local< v8::FunctionTemplate > GetNativeFunctionTemplate (v8::Isolate *isolate, v8::Local< v8::String > name) override
Static Public Member Functions
static void Fuzzilli (const v8::FunctionCallbackInfo< v8::Value > &info)
Static Private Member Functions
static const char * BuildSource (char *buf, size_t size, const char *fun_name)
Private Attributes
char buffer_ [50]
Detailed Description
Definition at line 23 of file fuzzilli.h.
Constructor & Destructor Documentation
FuzzilliExtension()
v8::internal::FuzzilliExtension::FuzzilliExtension (const char * fun_name) [inline], [explicit]
Definition at line 25 of file fuzzilli.h.
      : v8::Extension("v8/fuzzilli",
                      BuildSource(buffer_, sizeof(buffer_), fun_name)) {}
Member Function Documentation
BuildSource()
static const char* v8::internal::FuzzilliExtension::BuildSource (char * buf, size_t size, const char * fun_name) [inline], [static], [private]
Definition at line 33 of file fuzzilli.h.
                                                                               {
    base::SNPrintF(base::VectorOf(buf, size), "native function %s();",
                   fun_name);
    return buf;
  }
References size(), v8::base::SNPrintF(), and v8::base::VectorOf().
Fuzzilli()
void v8::internal::FuzzilliExtension::Fuzzilli (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 36 of file fuzzilli.cc.
                                                                        {
  v8::Isolate* isolate = info.GetIsolate();
  v8::String::Utf8Value operation(isolate, info[0]);
  if (*operation == nullptr) {
    return;
  }
  if (strcmp(*operation, "FUZZILLI_CRASH") == 0) {
    auto arg = info[1]
                   ->Int32Value(info.GetIsolate()->GetCurrentContext())
                   .FromMaybe(0);
    switch (arg) {
      case 0:
        IMMEDIATE_CRASH();
        break;
      case 1:
        CHECK(false);
        break;
      case 2:
        DCHECK(false);
        break;
      case 3: {
        // Access an invalid address.
        // We want to use an "interesting" address for the access (instead of
        // e.g. nullptr). In the (unlikely) case that the address is actually
        // mapped, simply increment the pointer until it crashes.
        // The cast ensures that this works correctly on both 32-bit and 64-bit.
        Address addr = static_cast<Address>(0x414141414141ull);
        char* ptr = reinterpret_cast<char*>(addr);
        for (int i = 0; i < 1024; i++) {
          *ptr = 'A';
          ptr += 1 * i::MB;
        }
        break;
      }
      case 4: {
        // Use-after-free, likely only crashes in ASan builds.
        auto* vec = new std::vector<int>(4);
        delete vec;
        USE(vec->at(0));
        break;
      }
      case 5: {
        // Out-of-bounds access (1), likely only crashes in ASan or
        // "hardened"/"safe" libc++ builds.
        std::vector<int> vec(5);
        USE(vec[5]);
        break;
      }
      case 6: {
        // Out-of-bounds access (2), likely only crashes in ASan builds.
        std::vector<int> vec(6);
        memset(vec.data(), 42, 0x100);
        break;
      }
      case 7: {
        if (i::v8_flags.hole_fuzzing) {
          // This should crash with a segmentation fault only
          // when --hole-fuzzing is used.
          char* ptr = reinterpret_cast<char*>(0x414141414141ull);
          for (int i = 0; i < 1024; i++) {
            *ptr = 'A';
            ptr += 1 * i::GB;
          }
        }
        break;
      }
      case 8: {
        // This allows Fuzzilli to check that DEBUG is defined, which should be
        // the case if dcheck_always_on is set. This is useful for fuzzing as
        // there are some integrity checks behind DEBUG.
#ifdef DEBUG
        IMMEDIATE_CRASH();
#endif
        break;
      }
      default:
        break;
    }
  } else if (strcmp(*operation, "FUZZILLI_PRINT") == 0) {
    static FILE* fzliout = fdopen(REPRL_DWFD, "w");
    if (!fzliout) {
      fprintf(
          stderr,
          "Fuzzer output channel not available, printing to stdout instead\n");
      fzliout = stdout;
    }
    v8::String::Utf8Value string(isolate, info[1]);
    if (*string == nullptr) {
      return;
    }
    fprintf(fzliout, "%s\n", *string);
    fflush(fzliout);
  }
}
References CHECK, v8::internal::DCHECK(), v8::internal::GB, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), IMMEDIATE_CRASH, MB, REPRL_DWFD, v8::internal::string, USE, and v8::internal::v8_flags.
Referenced by GetNativeFunctionTemplate().
GetNativeFunctionTemplate()
v8::Local< v8::FunctionTemplate > v8::internal::FuzzilliExtension::GetNativeFunctionTemplate (v8::Isolate * isolate, v8::Local< v8::String > name) [override], [virtual]
Reimplemented from v8::Extension.
Definition at line 25 of file fuzzilli.cc.
                                               {
  return v8::FunctionTemplate::New(isolate, FuzzilliExtension::Fuzzilli);
}
References Fuzzilli(), and v8::FunctionTemplate::New().
Member Data Documentation
buffer_
char v8::internal::FuzzilliExtension::buffer_[50] [private]
Definition at line 39 of file fuzzilli.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/fuzzilli/fuzzilli.h
/mnt/V8SourceCode/src/fuzzilli/fuzzilli.cc