v8::internal::compiler::turboshaft::UseMap Class Reference
#include <use-map.h>
Classes
struct PerOperationUses
Public Member Functions
UseMap (const Graph &graph, Zone *zone, FunctionType filter)
UseMap (const Graph &graph, Zone *zone)
base::Vector< const OpIndex > uses (OpIndex index) const
Private Member Functions
void AddUse (const Graph *graph, OpIndex node, OpIndex use)
Private Attributes
FixedOpIndexSidetable< PerOperationUses > table_
ZoneVector< OpIndex > uses_
ZoneVector< ZoneVector< OpIndex > > saturated_uses_
Detailed Description
Definition at line 18 of file use-map.h.
Constructor & Destructor Documentation
UseMap() [1/2]
v8::internal::compiler::turboshaft::UseMap::UseMap (const Graph & graph, Zone * zone, FunctionType filter)
Definition at line 9 of file use-map.cc.
    : table_(graph.op_id_count(), zone, &graph),
      uses_(zone),
      saturated_uses_(zone) {
  ZoneVector<std::pair<OpIndex, OpIndex>> delayed_phi_uses(zone);
  // We preallocate for 2 uses per operation.
  uses_.reserve(graph.op_id_count() * 2);
  // We skip {offset:0} to use {offset == 0} as uninitialized.
  uint32_t offset = 1;
  for (uint32_t index = 0; index < graph.block_count(); ++index) {
    BlockIndex block_index(index);
    const Block& block = graph.Get(block_index);
    auto block_ops = graph.OperationIndices(block);
    for (OpIndex op_index : block_ops) {
      const Operation& op = graph.Get(op_index);
      // When we see a definition, we allocate space in the {uses_}.
      DCHECK_EQ(table_[op_index].offset, 0);
      DCHECK_EQ(table_[op_index].count, 0);
      if (op.saturated_use_count.IsSaturated()) {
        table_[op_index].offset =
            -static_cast<int32_t>(saturated_uses_.size()) - 1;
        saturated_uses_.emplace_back(zone);
        saturated_uses_.back().reserve(std::numeric_limits<uint8_t>::max());
      } else {
        table_[op_index].offset = offset;
        offset += op.saturated_use_count.Get();
        uses_.resize(offset);
      }
      if (filter(graph, op, zone)) continue;
      if (block.IsLoop()) {
        if (op.Is<PhiOp>()) {
          DCHECK_EQ(op.input_count, 2);
          DCHECK_EQ(PhiOp::kLoopPhiBackEdgeIndex, 1);
          AddUse(&graph, op.input(0), op_index);
          // Delay back edge of loop Phis.
          delayed_phi_uses.emplace_back(op.input(1), op_index);
          continue;
        }
      }
      // Add uses.
      for (OpIndex input_index : op.inputs()) {
        AddUse(&graph, input_index, op_index);
      }
    }
  }
  for (auto [input_index, op_index] : delayed_phi_uses) {
    AddUse(&graph, input_index, op_index);
  }
}
References AddUse(), DCHECK_EQ, v8::internal::ZoneVector< T >::emplace_back(), v8::internal::compiler::turboshaft::SaturatedUint8::Get(), graph(), v8::internal::index, v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::Operation::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::SaturatedUint8::IsSaturated(), v8::internal::compiler::turboshaft::PhiOp::kLoopPhiBackEdgeIndex, v8::internal::compiler::turboshaft::Operation::saturated_use_count, saturated_uses_, table_, and uses_.
UseMap() [2/2]
v8::internal::compiler::turboshaft::UseMap::UseMap (const Graph & graph, Zone * zone) [inline]
Definition at line 31 of file use-map.h.
      : UseMap(graph, zone,
               [](const Graph& graph, const Operation& op, Zone* zone) {
                 return false;
               }) {}
Member Function Documentation
AddUse()
void v8::internal::compiler::turboshaft::UseMap::AddUse (const Graph * graph, OpIndex node, OpIndex use) [private]
Definition at line 81 of file use-map.cc.
                                                                 {
  int32_t input_offset = table_[node].offset;
  uint32_t& input_count = table_[node].count;
  DCHECK_NE(input_offset, 0);
  if (V8_LIKELY(input_offset > 0)) {
    DCHECK_LT(input_count, graph->Get(node).saturated_use_count.Get());
    DCHECK(!uses_[input_offset + input_count].valid());
    uses_[input_offset + input_count] = use;
  } else {
    ZoneVector<OpIndex>& uses = saturated_uses_[-input_offset - 1];
    DCHECK_EQ(uses.size(), input_count);
    uses.emplace_back(use);
  }
  ++input_count;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, DCHECK_NE, graph(), v8::internal::compiler::turboshaft::detail::input_count(), saturated_uses_, table_, use(), uses(), uses_, and V8_LIKELY.
Referenced by UseMap().
uses()
base::Vector< const OpIndex > v8::internal::compiler::turboshaft::UseMap::uses (OpIndex index) const
Definition at line 67 of file use-map.cc.
                                                          {
  DCHECK(index.valid());
  int32_t offset = table_[index].offset;
  uint32_t count = table_[index].count;
  DCHECK_NE(offset, 0);
  if (V8_LIKELY(offset > 0)) {
    return base::Vector<const OpIndex>(uses_.data() + offset, count);
  } else {
    DCHECK_EQ(count, saturated_uses_[-offset - 1].size());
    return base::Vector<const OpIndex>(saturated_uses_[-offset - 1].data(),
                                       count);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::index, saturated_uses_, size(), table_, uses_, and V8_LIKELY.
Referenced by AddUse(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), and v8::internal::compiler::turboshaft::WasmRevecAnalyzer::uses().
Member Data Documentation
saturated_uses_
ZoneVector<ZoneVector<OpIndex> > v8::internal::compiler::turboshaft::UseMap::saturated_uses_ [private]
Definition at line 44 of file use-map.h.
Referenced by AddUse(), UseMap(), and uses().
table_
FixedOpIndexSidetable<PerOperationUses> v8::internal::compiler::turboshaft::UseMap::table_ [private]
Definition at line 42 of file use-map.h.
Referenced by AddUse(), UseMap(), and uses().
uses_
ZoneVector<OpIndex> v8::internal::compiler::turboshaft::UseMap::uses_ [private]
Definition at line 43 of file use-map.h.
Referenced by AddUse(), UseMap(), and uses().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/use-map.h
/mnt/V8SourceCode/src/compiler/turboshaft/use-map.cc