v8::internal::ObjectHashSet Class Reference
#include <hash-table.h>
Public Member Functions
bool Has (Isolate *isolate, DirectHandle< Object > key, int32_t hash)
bool Has (Isolate *isolate, DirectHandle< Object > key)
Static Public Member Functions
static Handle< ObjectHashSet > Add (Isolate *isolate, Handle< ObjectHashSet > set, DirectHandle< Object > key)
Detailed Description
Definition at line 516 of file hash-table.h.
Member Function Documentation
Add()
Handle< ObjectHashSet > v8::internal::ObjectHashSet::Add (Isolate * isolate, Handle< ObjectHashSet > set, DirectHandle< Object > key) [static]
Definition at line 6296 of file objects.cc.
                                                                   {
  int32_t hash = Object::GetOrCreateHash(*key, isolate).value();
  if (!set->Has(isolate, key, hash)) {
    set = EnsureCapacity(isolate, set);
    InternalIndex entry = set->FindInsertionEntry(isolate, hash);
    set->set(EntryToIndex(entry), *key);
    set->ElementAdded();
  }
  return set;
}
References v8::internal::Object::GetOrCreateHash(), v8::internal::key, and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::KeyAccumulator::AddShadowingKey().
Has() [1/2]
bool v8::internal::ObjectHashSet::Has (Isolate * isolate, DirectHandle< Object > key) [inline]
Definition at line 253 of file hash-table-inl.h.
                                                                  {
  Tagged<Object> hash = Object::GetHash(*key);
  if (!IsSmi(hash)) return false;
  return FindEntry(isolate, ReadOnlyRoots(isolate), key, Smi::ToInt(hash))
      .is_found();
}
References v8::internal::Object::GetHash(), v8::internal::IsSmi(), v8::internal::key, and v8::internal::Smi::ToInt().
Has() [2/2]
bool v8::internal::ObjectHashSet::Has (Isolate * isolate, DirectHandle< Object > key, int32_t hash) [inline]
Definition at line 248 of file hash-table-inl.h.
                                      {
  return FindEntry(isolate, ReadOnlyRoots(isolate), key, hash).is_found();
}
References v8::internal::key.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/hash-table.h
/mnt/V8SourceCode/src/objects/hash-table-inl.h
/mnt/V8SourceCode/src/objects/objects.cc