v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder Class Reference
Classes
class BorrowParentKnownNodeAspectsAndVOs
class Label
class LoopLabel
class Variable
Public Member Functions
MaglevSubGraphBuilder (MaglevGraphBuilder *builder, int variable_count)
LoopLabel BeginLoop (std::initializer_list< Variable * > loop_vars)
template<typename ControlNodeT , typename... Args>
void GotoIfTrue (Label *true_target, std::initializer_list< ValueNode * > control_inputs, Args &&... args)
template<typename ControlNodeT , typename... Args>
void GotoIfFalse (Label *false_target, std::initializer_list< ValueNode * > control_inputs, Args &&... args)
void GotoOrTrim (Label *label)
void Goto (Label *label)
void ReducePredecessorCount (Label *label, unsigned num=1)
void EndLoop (LoopLabel *loop_label)
void Bind (Label *label)
ReduceResult TrimPredecessorsAndBind (Label *label)
void set (Variable &var, ValueNode *value)
ValueNode * get (const Variable &var) const
template<typename FCond , typename FTrue , typename FFalse >
ReduceResult Branch (std::initializer_list< Variable * > vars, FCond cond, FTrue if_true, FFalse if_false)
void MergeIntoLabel (Label *label, BasicBlock *predecessor)
template<typename FCond , typename FTrue , typename FFalse >
ReduceResult Branch (std::initializer_list< MaglevSubGraphBuilder::Variable * > vars, FCond cond, FTrue if_true, FFalse if_false)
Private Member Functions
void TakeKnownNodeAspectsAndVOsFromParent ()
void MoveKnownNodeAspectsAndVOsToParent ()
Private Attributes
MaglevGraphBuilder * builder_
MaglevCompilationUnit * compilation_unit_
InterpreterFrameState pseudo_frame_
Detailed Description
Definition at line 478 of file maglev-graph-builder.h.
Constructor & Destructor Documentation
MaglevSubGraphBuilder()
v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MaglevSubGraphBuilder (MaglevGraphBuilder * builder, int variable_count)
Definition at line 640 of file maglev-graph-builder.cc.
    : builder_(builder),
      compilation_unit_(MaglevCompilationUnit::NewDummy(
          builder->zone(), builder->compilation_unit(), variable_count, 0, 0)),
      pseudo_frame_(*compilation_unit_, nullptr, VirtualObjectList()) {
  // We need to set a context, since this is unconditional in the frame state,
  // so set it to the real context.
  pseudo_frame_.set(interpreter::Register::current_context(),
                    builder_->current_interpreter_frame().get(
                        interpreter::Register::current_context()));
  DCHECK_NULL(pseudo_frame_.known_node_aspects());
}
References builder_, v8::internal::interpreter::Register::current_context(), v8::internal::maglev::MaglevGraphBuilder::current_interpreter_frame(), DCHECK_NULL, v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::InterpreterFrameState::known_node_aspects(), pseudo_frame_, and v8::internal::maglev::InterpreterFrameState::set().
Member Function Documentation
BeginLoop()
MaglevGraphBuilder::MaglevSubGraphBuilder::LoopLabel v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::BeginLoop (std::initializer_list< Variable * > loop_vars)
Definition at line 655 of file maglev-graph-builder.cc.
                                              {
  // Create fake liveness and loop info for the loop, with all given loop vars
  // set to be live and assigned inside the loop.
  compiler::BytecodeLivenessState* loop_header_liveness =
      builder_->zone()->New<compiler::BytecodeLivenessState>(
          compilation_unit_->register_count(), builder_->zone());
  compiler::LoopInfo* loop_info = builder_->zone()->New<compiler::LoopInfo>(
      -1, 0, kMaxInt, compilation_unit_->parameter_count(),
      compilation_unit_->register_count(), builder_->zone());
  for (Variable* var : loop_vars) {
    loop_header_liveness->MarkRegisterLive(var->pseudo_register_.index());
    loop_info->assignments().Add(var->pseudo_register_);
  }
  // Finish the current block, jumping (as a fallthrough) to the loop header.
  BasicBlockRef loop_header_ref;
  BasicBlock* loop_predecessor =
      builder_->FinishBlock<Jump>({}, &loop_header_ref);
  // Create a state for the loop header, with two predecessors (the above jump
  // and the back edge), and initialise with the current state.
  MergePointInterpreterFrameState* loop_state =
      MergePointInterpreterFrameState::NewForLoop(
          pseudo_frame_, builder_->graph(), *compilation_unit_, 0, 2,
          loop_header_liveness, loop_info);
  {
    BorrowParentKnownNodeAspectsAndVOs borrow(this);
    loop_state->Merge(builder_, *compilation_unit_, pseudo_frame_,
                      loop_predecessor);
  }
  // Start a new basic block for the loop.
  DCHECK_NULL(pseudo_frame_.known_node_aspects());
  pseudo_frame_.CopyFrom(*compilation_unit_, *loop_state);
  MoveKnownNodeAspectsAndVOsToParent();
  builder_->ProcessMergePointPredecessors(*loop_state, loop_header_ref);
  builder_->StartNewBlock(nullptr, loop_state, loop_header_ref);
  return LoopLabel{loop_state, loop_header_ref.block_ptr()};
}
References v8::internal::maglev::BasicBlockRef::block_ptr(), v8::internal::maglev::MaglevGraphBuilder::compilation_unit_, DCHECK_NULL, v8::internal::kMaxInt, v8::internal::compiler::BytecodeLivenessState::MarkRegisterLive(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::maglev::MaglevCompilationUnit::parameter_count(), and v8::internal::maglev::MaglevCompilationUnit::register_count().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
Bind()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind (Label * label)
Definition at line 793 of file maglev-graph-builder.cc.
                                                               {
  DCHECK_NULL(builder_->current_block_);
  DCHECK_NULL(pseudo_frame_.known_node_aspects());
  pseudo_frame_.CopyFrom(*compilation_unit_, *label->merge_state_);
  MoveKnownNodeAspectsAndVOsToParent();
  CHECK_EQ(label->merge_state_->predecessors_so_far(),
           label->predecessor_count_);
  builder_->ProcessMergePointPredecessors(*label->merge_state_, label->ref_);
  builder_->StartNewBlock(nullptr, label->merge_state_, label->ref_);
}
References CHECK_EQ, v8::internal::maglev::MaglevGraphBuilder::compilation_unit_, DCHECK_NULL, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::merge_state_, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::predecessor_count_, v8::internal::maglev::MergePointInterpreterFrameState::predecessors_so_far(), and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::ref_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildJSArrayBuiltinMapSwitchOnElementsKind(), v8::internal::maglev::MaglevGraphBuilder::Select(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
Branch() [1/2]
template<typename FCond , typename FTrue , typename FFalse >
ReduceResult v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Branch (std::initializer_list< MaglevSubGraphBuilder::Variable * > vars, FCond cond, FTrue if_true, FFalse if_false)
Definition at line 817 of file maglev-graph-builder.cc.
                                    {
  MaglevSubGraphBuilder::Label else_branch(this, 1);
  BranchBuilder builder(builder_, this, BranchType::kBranchIfFalse,
                        &else_branch);
  BranchResult branch_result = cond(builder);
  if (branch_result == BranchResult::kAlwaysTrue) {
    return if_true();
  }
  if (branch_result == BranchResult::kAlwaysFalse) {
    return if_false();
  }
  DCHECK(branch_result == BranchResult::kDefault);
  MaglevSubGraphBuilder::Label done(this, 2, vars);
  MaybeReduceResult result_if_true = if_true();
  CHECK(result_if_true.IsDone());
  GotoOrTrim(&done);
  Bind(&else_branch);
  MaybeReduceResult result_if_false = if_false();
  CHECK(result_if_false.IsDone());
  if (result_if_true.IsDoneWithAbort() && result_if_false.IsDoneWithAbort()) {
    return ReduceResult::DoneWithAbort();
  }
  GotoOrTrim(&done);
  Bind(&done);
  return ReduceResult::Done();
}
References CHECK, v8::internal::DCHECK(), v8::internal::maglev::ReduceResult::Done(), v8::internal::maglev::ReduceResult::DoneWithAbort(), v8::internal::maglev::MaybeReduceResult::IsDone(), v8::internal::maglev::MaybeReduceResult::IsDoneWithAbort(), v8::internal::maglev::MaglevGraphBuilder::kAlwaysFalse, v8::internal::maglev::MaglevGraphBuilder::kAlwaysTrue, v8::internal::maglev::MaglevGraphBuilder::kBranchIfFalse, and v8::internal::maglev::MaglevGraphBuilder::kDefault.
Branch() [2/2]
template<typename FCond , typename FTrue , typename FFalse >
ReduceResult v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Branch (std::initializer_list< Variable * > vars, FCond cond, FTrue if_true, FFalse if_false)
EndLoop()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::EndLoop (LoopLabel * loop_label)
Definition at line 763 of file maglev-graph-builder.cc.
                                                                           {
  if (builder_->current_block_ == nullptr) {
    loop_label->merge_state_->MergeDeadLoop(*compilation_unit_);
    return;
  }
  BasicBlock* block =
      builder_->FinishBlock<JumpLoop>({}, loop_label->loop_header_);
  {
    BorrowParentKnownNodeAspectsAndVOs borrow(this);
    loop_label->merge_state_->MergeLoop(builder_, *compilation_unit_,
                                        pseudo_frame_, block);
  }
  block->set_predecessor_id(loop_label->merge_state_->predecessor_count() - 1);
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit_, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::LoopLabel::loop_header_, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::LoopLabel::merge_state_, v8::internal::maglev::MergePointInterpreterFrameState::MergeDeadLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::predecessor_count(), and v8::internal::maglev::BasicBlock::set_predecessor_id().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
get()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::get (const Variable & var) const
Definition at line 811 of file maglev-graph-builder.cc.
                               {
  return pseudo_frame_.get(var.pseudo_register_);
}
References v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Variable::pseudo_register_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::Select(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
Goto()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Goto (Label * label)
Definition at line 745 of file maglev-graph-builder.cc.
                                                               {
  CHECK_NOT_NULL(builder_->current_block_);
  BasicBlock* block = builder_->FinishBlock<Jump>({}, &label->ref_);
  MergeIntoLabel(label, block);
}
References CHECK_NOT_NULL, and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::ref_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildJSArrayBuiltinMapSwitchOnElementsKind(), v8::internal::maglev::MaglevGraphBuilder::Select(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess().
GotoIfFalse()
template<typename ControlNodeT , typename... Args>
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfFalse (Label * false_target, std::initializer_list< ValueNode * > control_inputs, Args &&... args)
Definition at line 719 of file maglev-graph-builder.cc.
                    {
  static_assert(IsConditionalControlNode(Node::opcode_of<ControlNodeT>));
  BasicBlockRef fallthrough_ref;
  // Pass through to FinishBlock, converting Labels to BasicBlockRefs and the
  // fallthrough label to the fallthrough ref.
  BasicBlock* block = builder_->FinishBlock<ControlNodeT>(
      control_inputs, std::forward<Args>(args)..., &fallthrough_ref,
      &false_target->ref_);
  MergeIntoLabel(false_target, block);
  builder_->StartNewBlock(block, nullptr, fallthrough_ref);
}
References v8::base::args, v8::internal::maglev::IsConditionalControlNode(), and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::ref_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildJSArrayBuiltinMapSwitchOnElementsKind(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
GotoIfTrue()
template<typename ControlNodeT , typename... Args>
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfTrue (Label * true_target, std::initializer_list< ValueNode * > control_inputs, Args &&... args)
Definition at line 700 of file maglev-graph-builder.cc.
                    {
  static_assert(IsConditionalControlNode(Node::opcode_of<ControlNodeT>));
  BasicBlockRef fallthrough_ref;
  // Pass through to FinishBlock, converting Labels to BasicBlockRefs and the
  // fallthrough label to the fallthrough ref.
  BasicBlock* block = builder_->FinishBlock<ControlNodeT>(
      control_inputs, std::forward<Args>(args)..., &true_target->ref_,
      &fallthrough_ref);
  MergeIntoLabel(true_target, block);
  builder_->StartNewBlock(block, nullptr, fallthrough_ref);
}
References v8::base::args, v8::internal::maglev::IsConditionalControlNode(), and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::ref_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildJSArrayBuiltinMapSwitchOnElementsKind(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
GotoOrTrim()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoOrTrim (Label * label)
Definition at line 737 of file maglev-graph-builder.cc.
                                                                     {
  if (builder_->current_block_ == nullptr) {
    ReducePredecessorCount(label);
    return;
  }
  Goto(label);
}
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildJSArrayBuiltinMapSwitchOnElementsKind(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
MergeIntoLabel()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MergeIntoLabel (Label * label, BasicBlock * predecessor)
Definition at line 935 of file maglev-graph-builder.cc.
                                           {
  BorrowParentKnownNodeAspectsAndVOs borrow(this);
  if (label->merge_state_ == nullptr) {
    // If there's no merge state, allocate a new one.
    label->merge_state_ = MergePointInterpreterFrameState::New(
        *compilation_unit_, pseudo_frame_, 0, label->predecessor_count_,
        predecessor, label->liveness_);
  } else {
    // If there already is a frame state, merge.
    label->merge_state_->Merge(builder_, *compilation_unit_, pseudo_frame_,
                               predecessor);
  }
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit_, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::liveness_, v8::internal::maglev::MergePointInterpreterFrameState::Merge(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::merge_state_, v8::internal::maglev::MergePointInterpreterFrameState::New(), and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::predecessor_count_.
MoveKnownNodeAspectsAndVOsToParent()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MoveKnownNodeAspectsAndVOsToParent () [private]
Definition at line 924 of file maglev-graph-builder.cc.
                                         {
  DCHECK_NOT_NULL(pseudo_frame_.known_node_aspects());
  builder_->current_interpreter_frame_.set_known_node_aspects(
      pseudo_frame_.known_node_aspects());
  pseudo_frame_.clear_known_node_aspects();
  builder_->current_interpreter_frame_.set_virtual_objects(
      pseudo_frame_.virtual_objects());
  pseudo_frame_.set_virtual_objects(VirtualObjectList());
}
References DCHECK_NOT_NULL.
ReducePredecessorCount()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::ReducePredecessorCount (Label * label, unsigned num = 1)
Definition at line 751 of file maglev-graph-builder.cc.
                                {
  DCHECK_GE(label->predecessor_count_, num);
  if (num == 0) {
    return;
  }
  label->predecessor_count_ -= num;
  if (label->merge_state_ != nullptr) {
    label->merge_state_->MergeDead(*compilation_unit_, num);
  }
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit_, DCHECK_GE, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::merge_state_, v8::internal::maglev::MergePointInterpreterFrameState::MergeDead(), and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::predecessor_count_.
set()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::set (Variable & var, ValueNode * value)
Definition at line 807 of file maglev-graph-builder.cc.
                                                                      {
  pseudo_frame_.set(var.pseudo_register_, value);
}
References v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Variable::pseudo_register_, and v8::internal::value.
Referenced by v8::internal::maglev::MaglevGraphBuilder::Select(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
TakeKnownNodeAspectsAndVOsFromParent()
void v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::TakeKnownNodeAspectsAndVOsFromParent () [private]
Definition at line 914 of file maglev-graph-builder.cc.
                                           {
  DCHECK_NULL(pseudo_frame_.known_node_aspects());
  DCHECK(pseudo_frame_.virtual_objects().is_empty());
  pseudo_frame_.set_known_node_aspects(
      builder_->current_interpreter_frame_.known_node_aspects());
  pseudo_frame_.set_virtual_objects(
      builder_->current_interpreter_frame_.virtual_objects());
}
References v8::internal::DCHECK(), and DCHECK_NULL.
TrimPredecessorsAndBind()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::TrimPredecessorsAndBind (Label * label)
Definition at line 779 of file maglev-graph-builder.cc.
                  {
  int predecessors_so_far = label->merge_state_ == nullptr
                                ? 0
                                : label->merge_state_->predecessors_so_far();
  DCHECK_LE(predecessors_so_far, label->predecessor_count_);
  builder_->current_block_ = nullptr;
  ReducePredecessorCount(label,
                         label->predecessor_count_ - predecessors_so_far);
  if (predecessors_so_far == 0) return ReduceResult::DoneWithAbort();
  Bind(label);
  return ReduceResult::Done();
}
References DCHECK_LE, v8::internal::maglev::ReduceResult::Done(), v8::internal::maglev::ReduceResult::DoneWithAbort(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::merge_state_, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Label::predecessor_count_, and v8::internal::maglev::MergePointInterpreterFrameState::predecessors_so_far().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess().
Member Data Documentation
builder_
MaglevGraphBuilder* v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::builder_ [private]
Definition at line 514 of file maglev-graph-builder.h.
Referenced by MaglevSubGraphBuilder().
compilation_unit_
MaglevCompilationUnit* v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::compilation_unit_ [private]
Definition at line 515 of file maglev-graph-builder.h.
pseudo_frame_
InterpreterFrameState v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::pseudo_frame_ [private]
Definition at line 516 of file maglev-graph-builder.h.
Referenced by MaglevSubGraphBuilder().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.h
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc