v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl Class Reference
Public Member Functions
UnaryOpAssemblerImpl (compiler::CodeAssemblerState *state)
TNode< Object > BitwiseNot (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
TNode< Object > Decrement (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
TNode< Object > Increment (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
TNode< Object > Negate (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
Private Types
using SmiOperation = std::function< TNode< Number >(TNode< Smi >, TVariable< Smi > *, Label *, TVariable< Float64T > *)>
using FloatOperation = std::function< TNode< Float64T >(TNode< Float64T >)>
using BigIntOperation = std::function< TNode< HeapObject >(TNode< Context >, TNode< HeapObject >)>
Private Member Functions
TNode< Object > UnaryOpWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, const SmiOperation &smi_op, const FloatOperation &float_op, const BigIntOperation &bigint_op, UpdateFeedbackMode update_feedback_mode)
template<Operation kOperation>
TNode< Object > IncrementOrDecrement (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
Additional Inherited Members
Detailed Description
Definition at line 17 of file unary-op-assembler.cc.
Member Typedef Documentation
BigIntOperation
using v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::BigIntOperation = std::function<TNode<HeapObject>(TNode<Context> , TNode<HeapObject>)> [private]
Definition at line 132 of file unary-op-assembler.cc.
FloatOperation
using v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::FloatOperation = std::function<TNode<Float64T>(TNode<Float64T>)> [private]
Definition at line 130 of file unary-op-assembler.cc.
SmiOperation
using v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::SmiOperation = std::function<TNode<Number>(TNode<Smi> , TVariable<Smi>* , Label* , TVariable<Float64T>*)> [private]
Definition at line 127 of file unary-op-assembler.cc.
Constructor & Destructor Documentation
UnaryOpAssemblerImpl()
v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::UnaryOpAssemblerImpl (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 19 of file unary-op-assembler.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
BitwiseNot()
TNode<Object> v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::BitwiseNot (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode) [inline]
Definition at line 22 of file unary-op-assembler.cc.
                                                                    {
    // TODO(jgruber): Make this implementation more consistent with other unary
    // ops (i.e. have them all use UnaryOpWithFeedback or some other common
    // mechanism).
    TVARIABLE(Word32T, var_word32);
    TVARIABLE(Smi, var_feedback);
    TVARIABLE(BigInt, var_bigint);
    TVARIABLE(Object, var_result);
    Label if_number(this), if_bigint(this, Label::kDeferred), out(this);
    LazyNode<HeapObject> get_vector = [&]() { return maybe_feedback_vector; };
    FeedbackValues feedback = {&var_feedback, &get_vector, &slot,
                               update_feedback_mode};
    TaggedToWord32OrBigIntWithFeedback(context, value, &if_number, &var_word32,
                                       &if_bigint, nullptr, &var_bigint,
                                       feedback);
    // Number case.
    BIND(&if_number);
    var_result =
        ChangeInt32ToTagged(Signed(Word32BitwiseNot(var_word32.value())));
    TNode<Smi> result_type = SelectSmiConstant(
        TaggedIsSmi(var_result.value()), BinaryOperationFeedback::kSignedSmall,
        BinaryOperationFeedback::kNumber);
    UpdateFeedback(SmiOr(result_type, var_feedback.value()),
                   maybe_feedback_vector, slot, update_feedback_mode);
    Goto(&out);
    // BigInt case.
    BIND(&if_bigint);
    UpdateFeedback(SmiConstant(BinaryOperationFeedback::kBigInt),
                   maybe_feedback_vector, slot, update_feedback_mode);
    var_result =
        CallRuntime(Runtime::kBigIntUnaryOp, context, var_bigint.value(),
                    SmiConstant(Operation::kBitwiseNot));
    Goto(&out);
    BIND(&out);
    return var_result.value();
  }
References v8::internal::BinaryOperationFeedback::kBigInt, v8::internal::BinaryOperationFeedback::kNumber, v8::internal::BinaryOperationFeedback::kSignedSmall, v8::base::bits::Signed(), and v8::internal::value.
Decrement()
TNode<Object> v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::Decrement (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode) [inline]
Definition at line 65 of file unary-op-assembler.cc.
                                                                   {
    return IncrementOrDecrement<Operation::kDecrement>(
        context, value, slot, maybe_feedback_vector, update_feedback_mode);
  }
References v8::internal::value.
Increment()
TNode<Object> v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::Increment (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode) [inline]
Definition at line 73 of file unary-op-assembler.cc.
                                                                   {
    return IncrementOrDecrement<Operation::kIncrement>(
        context, value, slot, maybe_feedback_vector, update_feedback_mode);
  }
References v8::internal::value.
IncrementOrDecrement()
template<Operation kOperation>
TNode<Object> v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::IncrementOrDecrement (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode) [inline], [private]
Definition at line 241 of file unary-op-assembler.cc.
                                                                              {
    static_assert(kOperation == Operation::kIncrement ||
                  kOperation == Operation::kDecrement);
    static constexpr int kAddValue =
        (kOperation == Operation::kIncrement) ? 1 : -1;
    SmiOperation smi_op = [=, this](TNode<Smi> smi_value,
                                    TVariable<Smi>* var_feedback,
                                    Label* do_float_op,
                                    TVariable<Float64T>* var_float) {
      Label if_overflow(this), out(this);
      TNode<Smi> result =
          TrySmiAdd(smi_value, SmiConstant(kAddValue), &if_overflow);
      CombineFeedback(var_feedback, BinaryOperationFeedback::kSignedSmall);
      Goto(&out);
      BIND(&if_overflow);
      *var_float = SmiToFloat64(smi_value);
      Goto(do_float_op);
      BIND(&out);
      return result;
    };
    FloatOperation float_op = [=, this](TNode<Float64T> float_value) {
      return Float64Add(float_value, Float64Constant(kAddValue));
    };
    BigIntOperation bigint_op = [=, this](TNode<Context> context,
                                          TNode<HeapObject> bigint_value) {
      return CAST(CallRuntime(Runtime::kBigIntUnaryOp, context, bigint_value,
                              SmiConstant(kOperation)));
    };
    return UnaryOpWithFeedback(context, value, slot, maybe_feedback_vector,
                               smi_op, float_op, bigint_op,
                               update_feedback_mode);
  }
References CAST, v8::internal::compiler::Float64Add(), v8::kOperation, v8::internal::BinaryOperationFeedback::kSignedSmall, v8::base::internal::result, and v8::internal::value.
Negate()
TNode<Object> v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::Negate (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode) [inline]
Definition at line 81 of file unary-op-assembler.cc.
                                                                {
    SmiOperation smi_op =
        [=, this](TNode<Smi> smi_value, TVariable<Smi>* var_feedback,
                  Label* do_float_op, TVariable<Float64T>* var_float) {
          TVARIABLE(Number, var_result);
          Label if_zero(this), if_min_smi(this), end(this);
          // Return -0 if operand is 0.
          GotoIf(SmiEqual(smi_value, SmiConstant(0)), &if_zero);
          // Special-case the minimum Smi to avoid overflow.
          GotoIf(SmiEqual(smi_value, SmiConstant(Smi::kMinValue)), &if_min_smi);
          // Else simply subtract operand from 0.
          CombineFeedback(var_feedback, BinaryOperationFeedback::kSignedSmall);
          var_result = SmiSub(SmiConstant(0), smi_value);
          Goto(&end);
          BIND(&if_zero);
          CombineFeedback(var_feedback, BinaryOperationFeedback::kNumber);
          var_result = MinusZeroConstant();
          Goto(&end);
          BIND(&if_min_smi);
          *var_float = SmiToFloat64(smi_value);
          Goto(do_float_op);
          BIND(&end);
          return var_result.value();
        };
    FloatOperation float_op = [=, this](TNode<Float64T> float_value) {
      return Float64Neg(float_value);
    };
    BigIntOperation bigint_op = [=, this](TNode<Context> context,
                                          TNode<HeapObject> bigint_value) {
      return CAST(CallRuntime(Runtime::kBigIntUnaryOp, context, bigint_value,
                              SmiConstant(Operation::kNegate)));
    };
    return UnaryOpWithFeedback(context, value, slot, maybe_feedback_vector,
                               smi_op, float_op, bigint_op,
                               update_feedback_mode);
  }
References CAST, v8::internal::compiler::end(), v8::internal::Smi::kMinValue, v8::internal::BinaryOperationFeedback::kNumber, v8::internal::BinaryOperationFeedback::kSignedSmall, and v8::internal::value.
UnaryOpWithFeedback()
TNode<Object> v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::UnaryOpWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, const SmiOperation & smi_op, const FloatOperation & float_op, const BigIntOperation & bigint_op, UpdateFeedbackMode update_feedback_mode) [inline], [private]
Definition at line 135 of file unary-op-assembler.cc.
                                                                             {
    TVARIABLE(Object, var_value, value);
    TVARIABLE(Object, var_result);
    TVARIABLE(Float64T, var_float_value);
    TVARIABLE(Smi, var_feedback, SmiConstant(BinaryOperationFeedback::kNone));
    TVARIABLE(Object, var_exception);
    Label start(this, {&var_value, &var_feedback}), end(this);
    Label do_float_op(this, &var_float_value);
    Label if_exception(this, Label::kDeferred);
    Goto(&start);
    // We might have to try again after ToNumeric conversion.
    BIND(&start);
    {
      Label if_smi(this), if_heapnumber(this), if_oddball(this);
      Label if_bigint(this, Label::kDeferred);
      Label if_other(this, Label::kDeferred);
      value = var_value.value();
      GotoIf(TaggedIsSmi(value), &if_smi);
      TNode<HeapObject> value_heap_object = CAST(value);
      TNode<Map> map = LoadMap(value_heap_object);
      GotoIf(IsHeapNumberMap(map), &if_heapnumber);
      TNode<Uint16T> instance_type = LoadMapInstanceType(map);
      GotoIf(IsBigIntInstanceType(instance_type), &if_bigint);
      Branch(InstanceTypeEqual(instance_type, ODDBALL_TYPE), &if_oddball,
             &if_other);
      BIND(&if_smi);
      {
        var_result =
            smi_op(CAST(value), &var_feedback, &do_float_op, &var_float_value);
        Goto(&end);
      }
      BIND(&if_heapnumber);
      {
        var_float_value = LoadHeapNumberValue(value_heap_object);
        Goto(&do_float_op);
      }
      BIND(&if_bigint);
      {
        var_result = bigint_op(context, value_heap_object);
        CombineFeedback(&var_feedback, BinaryOperationFeedback::kBigInt);
        Goto(&end);
      }
      BIND(&if_oddball);
      {
        // We do not require an Or with earlier feedback here because once we
        // convert the value to a number, we cannot reach this path. We can
        // only reach this path on the first pass when the feedback is kNone.
        CSA_DCHECK(this, SmiEqual(var_feedback.value(),
                                  SmiConstant(BinaryOperationFeedback::kNone)));
        OverwriteFeedback(&var_feedback,
                          BinaryOperationFeedback::kNumberOrOddball);
        var_value = LoadOddballToNumber(CAST(value_heap_object));
        Goto(&start);
      }
      BIND(&if_other);
      {
        // We do not require an Or with earlier feedback here because once we
        // convert the value to a number, we cannot reach this path. We can
        // only reach this path on the first pass when the feedback is kNone.
        CSA_DCHECK(this, SmiEqual(var_feedback.value(),
                                  SmiConstant(BinaryOperationFeedback::kNone)));
        OverwriteFeedback(&var_feedback, BinaryOperationFeedback::kAny);
        {
          ScopedExceptionHandler handler(this, &if_exception, &var_exception);
          var_value = CallBuiltin(Builtin::kNonNumberToNumeric, context,
                                  value_heap_object);
        }
        Goto(&start);
      }
    }
    BIND(&if_exception);
    {
      UpdateFeedback(var_feedback.value(), maybe_feedback_vector, slot,
                     update_feedback_mode);
      CallRuntime(Runtime::kReThrow, context, var_exception.value());
      Unreachable();
    }
    BIND(&do_float_op);
    {
      CombineFeedback(&var_feedback, BinaryOperationFeedback::kNumber);
      var_result =
          AllocateHeapNumberWithValue(float_op(var_float_value.value()));
      Goto(&end);
    }
    BIND(&end);
    UpdateFeedback(var_feedback.value(), maybe_feedback_vector, slot,
                   update_feedback_mode);
    return var_result.value();
  }
References CAST, v8::internal::compiler::end(), v8::internal::BinaryOperationFeedback::kAny, v8::internal::BinaryOperationFeedback::kBigInt, v8::internal::BinaryOperationFeedback::kNone, v8::internal::BinaryOperationFeedback::kNumber, v8::internal::BinaryOperationFeedback::kNumberOrOddball, and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ic/unary-op-assembler.cc