v8::internal::baseline::BytecodeOffsetIterator Class Reference
#include <bytecode-offset-iterator.h>
Public Member Functions
BytecodeOffsetIterator (Handle< TrustedByteArray > mapping_table, Handle< BytecodeArray > bytecodes)
BytecodeOffsetIterator (Tagged< TrustedByteArray > mapping_table, Tagged< BytecodeArray > bytecodes)
~BytecodeOffsetIterator ()
void Advance ()
void AdvanceToBytecodeOffset (int bytecode_offset)
void AdvanceToPCOffset (Address pc_offset)
bool done () const
Address current_pc_start_offset () const
Address current_pc_end_offset () const
int current_bytecode_offset () const
void UpdatePointers ()
Static Public Member Functions
static void UpdatePointersCallback (void *iterator)
Private Member Functions
void Initialize ()
int ReadPosition ()
Private Attributes
Handle< TrustedByteArray > mapping_table_
uint8_t * data_start_address_
int data_length_
int current_index_
Address current_pc_start_offset_
Address current_pc_end_offset_
int current_bytecode_offset_
Tagged< BytecodeArray > bytecode_handle_storage_
interpreter::BytecodeArrayIterator bytecode_iterator_
LocalHeap * local_heap_
std::optional< DisallowGarbageCollection > no_gc_
Detailed Description
Definition at line 22 of file bytecode-offset-iterator.h.
Constructor & Destructor Documentation
BytecodeOffsetIterator() [1/2]
v8::internal::baseline::BytecodeOffsetIterator::BytecodeOffsetIterator (Handle< TrustedByteArray > mapping_table, Handle< BytecodeArray > bytecodes) [explicit]
Definition at line 15 of file bytecode-offset-iterator.cc.
    : mapping_table_(mapping_table),
      data_start_address_(mapping_table_->begin()),
      data_length_(mapping_table_->length()),
      current_index_(0),
      bytecode_iterator_(bytecodes),
      local_heap_(LocalHeap::Current()
                      ? LocalHeap::Current()
                      : Isolate::Current()->main_thread_local_heap()) {
  local_heap_->AddGCEpilogueCallback(UpdatePointersCallback, this);
  Initialize();
}
References v8::internal::LocalHeap::AddGCEpilogueCallback(), Initialize(), local_heap_, and UpdatePointersCallback().
BytecodeOffsetIterator() [2/2]
v8::internal::baseline::BytecodeOffsetIterator::BytecodeOffsetIterator (Tagged< TrustedByteArray > mapping_table, Tagged< BytecodeArray > bytecodes) [explicit]
Definition at line 29 of file bytecode-offset-iterator.cc.
    : data_start_address_(mapping_table->begin()),
      data_length_(mapping_table->length()),
      current_index_(0),
      bytecode_handle_storage_(bytecodes),
      // In the non-handlified version, no GC is allowed. We use a "dummy"
      // handle to pass the BytecodeArray to the BytecodeArrayIterator, which
      // is fine since no objects will be moved.
      bytecode_iterator_(Handle<BytecodeArray>(
          reinterpret_cast<Address*>(&bytecode_handle_storage_))),
      local_heap_(nullptr) {
  no_gc_.emplace();
  Initialize();
}
References Initialize(), and no_gc_.
 BytecodeOffsetIterator()
v8::internal::baseline::BytecodeOffsetIterator::~BytecodeOffsetIterator ()
Definition at line 45 of file bytecode-offset-iterator.cc.
                                                {
  if (local_heap_ != nullptr) {
    local_heap_->RemoveGCEpilogueCallback(UpdatePointersCallback, this);
  }
}
References local_heap_, v8::internal::LocalHeap::RemoveGCEpilogueCallback(), and UpdatePointersCallback().
Member Function Documentation
Advance()
void v8::internal::baseline::BytecodeOffsetIterator::Advance () [inline]
Definition at line 31 of file bytecode-offset-iterator.h.
                        {
    DCHECK(!done());
    current_pc_start_offset_ = current_pc_end_offset_;
    current_pc_end_offset_ += ReadPosition();
    current_bytecode_offset_ = bytecode_iterator_.current_offset();
    bytecode_iterator_.Advance();
  }
References v8::internal::DCHECK().
AdvanceToBytecodeOffset()
void v8::internal::baseline::BytecodeOffsetIterator::AdvanceToBytecodeOffset (int bytecode_offset) [inline]
Definition at line 39 of file bytecode-offset-iterator.h.
                                                           {
    while (current_bytecode_offset() < bytecode_offset) {
      Advance();
    }
    DCHECK_EQ(bytecode_offset, current_bytecode_offset());
  }
References DCHECK_EQ.
Referenced by v8::internal::Code::GetBaselinePCForBytecodeOffset().
AdvanceToPCOffset()
void v8::internal::baseline::BytecodeOffsetIterator::AdvanceToPCOffset (Address pc_offset) [inline]
Definition at line 46 of file bytecode-offset-iterator.h.
                                                   {
    while (current_pc_end_offset() < pc_offset) {
      Advance();
    }
    DCHECK_GT(pc_offset, current_pc_start_offset());
    DCHECK_LE(pc_offset, current_pc_end_offset());
  }
References DCHECK_GT, and DCHECK_LE.
Referenced by v8::internal::Code::GetBytecodeOffsetForBaselinePC().
current_bytecode_offset()
int v8::internal::baseline::BytecodeOffsetIterator::current_bytecode_offset () const [inline]
Definition at line 66 of file bytecode-offset-iterator.h.
                                             {
    return current_bytecode_offset_;
  }
Referenced by v8::internal::Code::GetBytecodeOffsetForBaselinePC().
current_pc_end_offset()
Address v8::internal::baseline::BytecodeOffsetIterator::current_pc_end_offset () const [inline]
Definition at line 62 of file bytecode-offset-iterator.h.
                                               {
    return current_pc_end_offset_;
  }
Referenced by v8::internal::Code::GetBaselinePCForBytecodeOffset().
current_pc_start_offset()
Address v8::internal::baseline::BytecodeOffsetIterator::current_pc_start_offset () const [inline]
Definition at line 58 of file bytecode-offset-iterator.h.
                                                 {
    return current_pc_start_offset_;
  }
Referenced by v8::internal::Code::GetBaselinePCForBytecodeOffset().
done()
bool v8::internal::baseline::BytecodeOffsetIterator::done () const [inline]
Definition at line 56 of file bytecode-offset-iterator.h.
{ return current_index_ >= data_length_; }
Initialize()
void v8::internal::baseline::BytecodeOffsetIterator::Initialize () [private]
Definition at line 51 of file bytecode-offset-iterator.cc.
                                        {
  // Initialize values for the prologue.
  // The first recorded position is at the start of the first bytecode.
  current_pc_start_offset_ = 0;
  current_pc_end_offset_ = ReadPosition();
  current_bytecode_offset_ = kFunctionEntryBytecodeOffset;
}
References current_bytecode_offset_, current_pc_end_offset_, current_pc_start_offset_, v8::internal::kFunctionEntryBytecodeOffset, and ReadPosition().
Referenced by BytecodeOffsetIterator().
ReadPosition()
int v8::internal::baseline::BytecodeOffsetIterator::ReadPosition () [inline], [private]
Definition at line 78 of file bytecode-offset-iterator.h.
                            {
    return base::VLQDecodeUnsigned(data_start_address_, &current_index_);
  }
References v8::base::VLQDecodeUnsigned().
Referenced by Initialize().
UpdatePointers()
void v8::internal::baseline::BytecodeOffsetIterator::UpdatePointers ()
Definition at line 59 of file bytecode-offset-iterator.cc.
                                            {
  DisallowGarbageCollection no_gc;
  DCHECK(!mapping_table_.is_null());
  data_start_address_ = mapping_table_->begin();
}
References data_start_address_, v8::internal::DCHECK(), mapping_table_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
UpdatePointersCallback()
static void v8::internal::baseline::BytecodeOffsetIterator::UpdatePointersCallback (void * iterator) [inline], [static]
Definition at line 70 of file bytecode-offset-iterator.h.
                                                     {
    reinterpret_cast<BytecodeOffsetIterator*>(iterator)->UpdatePointers();
  }
Referenced by BytecodeOffsetIterator(), and ~BytecodeOffsetIterator().
Member Data Documentation
bytecode_handle_storage_
Tagged<BytecodeArray> v8::internal::baseline::BytecodeOffsetIterator::bytecode_handle_storage_ [private]
Definition at line 89 of file bytecode-offset-iterator.h.
bytecode_iterator_
interpreter::BytecodeArrayIterator v8::internal::baseline::BytecodeOffsetIterator::bytecode_iterator_ [private]
Definition at line 90 of file bytecode-offset-iterator.h.
current_bytecode_offset_
int v8::internal::baseline::BytecodeOffsetIterator::current_bytecode_offset_ [private]
Definition at line 88 of file bytecode-offset-iterator.h.
Referenced by Initialize().
current_index_
int v8::internal::baseline::BytecodeOffsetIterator::current_index_ [private]
Definition at line 85 of file bytecode-offset-iterator.h.
current_pc_end_offset_
Address v8::internal::baseline::BytecodeOffsetIterator::current_pc_end_offset_ [private]
Definition at line 87 of file bytecode-offset-iterator.h.
Referenced by Initialize().
current_pc_start_offset_
Address v8::internal::baseline::BytecodeOffsetIterator::current_pc_start_offset_ [private]
Definition at line 86 of file bytecode-offset-iterator.h.
Referenced by Initialize().
data_length_
int v8::internal::baseline::BytecodeOffsetIterator::data_length_ [private]
Definition at line 84 of file bytecode-offset-iterator.h.
data_start_address_
uint8_t* v8::internal::baseline::BytecodeOffsetIterator::data_start_address_ [private]
Definition at line 83 of file bytecode-offset-iterator.h.
Referenced by UpdatePointers().
local_heap_
LocalHeap* v8::internal::baseline::BytecodeOffsetIterator::local_heap_ [private]
Definition at line 91 of file bytecode-offset-iterator.h.
Referenced by BytecodeOffsetIterator(), and ~BytecodeOffsetIterator().
mapping_table_
Handle<TrustedByteArray> v8::internal::baseline::BytecodeOffsetIterator::mapping_table_ [private]
Definition at line 82 of file bytecode-offset-iterator.h.
Referenced by UpdatePointers().
no_gc_
std::optional<DisallowGarbageCollection> v8::internal::baseline::BytecodeOffsetIterator::no_gc_ [private]
Definition at line 92 of file bytecode-offset-iterator.h.
Referenced by BytecodeOffsetIterator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/baseline/bytecode-offset-iterator.h
/mnt/V8SourceCode/src/baseline/bytecode-offset-iterator.cc