v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector Class Reference
Public Member Functions
void AddTorqueMessage (const TorqueMessage &message)
std::map< SourceId, PublishDiagnosticsNotification > & notifications ()
Private Member Functions
PublishDiagnosticsNotification & GetOrCreateNotificationForSource (SourceId id)
bool ShouldAddMessageOfKind (TorqueMessage::Kind kind)
void PopulateRangeFromSourcePosition (Range range, const SourcePosition &position)
Diagnostic::DiagnosticSeverity ServerityFor (TorqueMessage::Kind kind)
Private Attributes
std::map< SourceId, PublishDiagnosticsNotification > notifications_
bool suppress_lint_messages_ = false
Detailed Description
Definition at line 85 of file message-handler.cc.
Member Function Documentation
AddTorqueMessage()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::AddTorqueMessage (const TorqueMessage & message) [inline]
Definition at line 87 of file message-handler.cc.
                                                      {
    if (!ShouldAddMessageOfKind(message.kind)) return;
    SourceId id =
        message.position ? message.position->source : SourceId::Invalid();
    auto& notification = GetOrCreateNotificationForSource(id);
    Diagnostic diagnostic = notification.params().add_diagnostics();
    diagnostic.set_severity(ServerityFor(message.kind));
    diagnostic.set_message(message.message);
    diagnostic.set_source("Torque Compiler");
    if (message.position) {
      PopulateRangeFromSourcePosition(diagnostic.range(), *message.position);
    }
  }
References v8::internal::torque::SourceId::Invalid(), v8::internal::torque::TorqueMessage::kind, v8::internal::torque::TorqueMessage::message, and v8::internal::torque::TorqueMessage::position.
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::SendCompilationDiagnostics().
GetOrCreateNotificationForSource()
PublishDiagnosticsNotification& v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::GetOrCreateNotificationForSource (SourceId id) [inline], [private]
Definition at line 109 of file message-handler.cc.
                   {
    auto iter = notifications_.find(id);
    if (iter != notifications_.end()) return iter->second;
    PublishDiagnosticsNotification& notification = notifications_[id];
    notification.set_method("textDocument/publishDiagnostics");
    std::string file =
        id.IsValid() ? SourceFileMap::AbsolutePath(id) : "<unknown>";
    notification.params().set_uri(file);
    return notification;
  }
References v8::internal::torque::SourceFileMap::AbsolutePath(), file(), and v8::internal::string.
notifications()
std::map<SourceId, PublishDiagnosticsNotification>& v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::notifications () [inline]
Definition at line 104 of file message-handler.cc.
                                                                    {
    return notifications_;
  }
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::SendCompilationDiagnostics().
PopulateRangeFromSourcePosition()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::PopulateRangeFromSourcePosition (Range range, const SourcePosition & position) [inline], [private]
Definition at line 137 of file message-handler.cc.
                                                                       {
    range.start().set_line(position.start.line);
    range.start().set_character(position.start.column);
    range.end().set_line(position.end.line);
    range.end().set_character(position.end.column);
  }
References v8::internal::torque::LineAndColumn::column, v8::internal::torque::SourcePosition::end, v8::internal::torque::LineAndColumn::line, and v8::internal::torque::SourcePosition::start.
ServerityFor()
Diagnostic::DiagnosticSeverity v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::ServerityFor (TorqueMessage::Kind kind) [inline], [private]
Definition at line 145 of file message-handler.cc.
                                                                    {
    switch (kind) {
      case TorqueMessage::Kind::kError:
        return Diagnostic::kError;
      case TorqueMessage::Kind::kLint:
        return Diagnostic::kWarning;
    }
  }
References v8::internal::torque::ls::Diagnostic::kError, v8::internal::torque::TorqueMessage::kError, v8::internal::torque::TorqueMessage::kLint, and v8::internal::torque::ls::Diagnostic::kWarning.
ShouldAddMessageOfKind()
bool v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::ShouldAddMessageOfKind (TorqueMessage::Kind kind) [inline], [private]
Definition at line 123 of file message-handler.cc.
                                                      {
    // An error can easily cause a lot of false positive lint messages, due to
    // unused variables, macros, etc. Thus we suppress subsequent lint messages
    // when there are errors.
    switch (kind) {
      case TorqueMessage::Kind::kError:
        suppress_lint_messages_ = true;
        return true;
      case TorqueMessage::Kind::kLint:
        if (suppress_lint_messages_) return false;
        return true;
    }
  }
References v8::internal::torque::TorqueMessage::kError, and v8::internal::torque::TorqueMessage::kLint.
Member Data Documentation
notifications_
std::map<SourceId, PublishDiagnosticsNotification> v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::notifications_ [private]
Definition at line 154 of file message-handler.cc.
suppress_lint_messages_
bool v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::suppress_lint_messages_ = false [private]
Definition at line 155 of file message-handler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/ls/message-handler.cc