v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded > Class Template Reference
Classes
struct DummyNeedsDecompression
struct GapMoveTargets
Public Member Functions
ParallelMoveResolver (MaglevAssembler *masm)
void RecordMove (ValueNode *source_node, compiler::InstructionOperand source, compiler::AllocatedOperand target, bool target_needs_to_be_decompressed)
void RecordMove (ValueNode *source_node, compiler::InstructionOperand source, RegisterT target_reg, NeedsDecompression target_needs_to_be_decompressed)
void EmitMoves (RegisterT scratch)
ParallelMoveResolver (ParallelMoveResolver &&)=delete
ParallelMoveResolver operator= (ParallelMoveResolver &&)=delete
ParallelMoveResolver (const ParallelMoveResolver &)=delete
ParallelMoveResolver operator= (const ParallelMoveResolver &)=delete
Private Member Functions
void CheckNoExistingMoveToRegister (RegisterT target_reg)
void CheckNoExistingMoveToStackSlot (int32_t target_slot)
void RecordMoveToRegister (ValueNode *node, compiler::InstructionOperand source, RegisterT target_reg, bool target_needs_to_be_decompressed)
void RecordMoveToStackSlot (ValueNode *node, compiler::InstructionOperand source, int32_t target_slot, bool target_needs_to_be_decompressed)
GapMoveTargets PopTargets (RegisterT source_reg)
GapMoveTargets PopTargets (int32_t source_slot)
template<typename SourceT >
void StartEmitMoveChain (SourceT source)
template<typename ChainStartT , typename SourceT >
bool ContinueEmitMoveChain (ChainStartT chain_start, SourceT source)
template<typename ChainStartT >
bool RecursivelyEmitMoveChainTargets (ChainStartT chain_start, GapMoveTargets &targets)
void EmitMovesFromSource (RegisterT source_reg, GapMoveTargets &&targets)
void EmitMovesFromSource (int32_t source_slot, GapMoveTargets &&targets)
void Push (Register reg)
void Push (DoubleRegister reg)
void Pop (Register reg)
void Pop (DoubleRegister reg)
MaglevAssembler * masm () const
Private Attributes
MaglevAssembler *const masm_
RegisterT scratch_
std::array< GapMoveTargets, RegisterT::kNumRegisters > moves_from_register_
std::unordered_map< int32_t, GapMoveTargets > moves_from_stack_slot_
std::array< ValueNode *, RegisterT::kNumRegisters > materializing_register_moves_ = {}
std::vector< std::pair< int32_t, ValueNode * > > materializing_stack_slot_moves_
bool scratch_has_cycle_start_ = false
Static Private Attributes
static constexpr auto kAllocatableRegistersT
Detailed Description
template<typename RegisterT, bool DecompressIfNeeded>
class v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >
Definition at line 98 of file maglev-code-generator.cc.
Constructor & Destructor Documentation
ParallelMoveResolver() [1/3]
template<typename RegisterT , bool DecompressIfNeeded>
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::ParallelMoveResolver (MaglevAssembler * masm) [inline], [explicit]
Definition at line 105 of file maglev-code-generator.cc.
      : masm_(masm), scratch_(RegisterT::no_reg()) {}
ParallelMoveResolver() [2/3]
template<typename RegisterT , bool DecompressIfNeeded>
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::ParallelMoveResolver (ParallelMoveResolver< RegisterT, DecompressIfNeeded > &&) [delete]
ParallelMoveResolver() [3/3]
template<typename RegisterT , bool DecompressIfNeeded>
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::ParallelMoveResolver (const ParallelMoveResolver< RegisterT, DecompressIfNeeded > &) [delete]
Member Function Documentation
CheckNoExistingMoveToRegister()
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::CheckNoExistingMoveToRegister (RegisterT target_reg) [inline], [private]
Definition at line 234 of file maglev-code-generator.cc.
{}
CheckNoExistingMoveToStackSlot()
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::CheckNoExistingMoveToStackSlot (int32_t target_slot) [inline], [private]
Definition at line 235 of file maglev-code-generator.cc.
{}
ContinueEmitMoveChain()
template<typename RegisterT , bool DecompressIfNeeded>
template<typename ChainStartT , typename SourceT >
bool v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::ContinueEmitMoveChain (ChainStartT chain_start, SourceT source) [inline], [private]
Definition at line 378 of file maglev-code-generator.cc.
                                                                      {
    if constexpr (std::is_same_v<ChainStartT, SourceT>) {
      // If the recursion has returned to the start of the chain, then this must
      // be a cycle.
      if (chain_start == source) {
        __ RecordComment("-- * Cycle");
        DCHECK(!scratch_has_cycle_start_);
        if constexpr (std::is_same_v<ChainStartT, int32_t>) {
          __ Move(scratch_, StackSlot{chain_start});
        } else {
          __ Move(scratch_, chain_start);
        }
        scratch_has_cycle_start_ = true;
        return true;
      }
    }
    GapMoveTargets targets = PopTargets(source);
    if (targets.is_empty()) {
      __ RecordComment("-- * End of chain");
      return false;
    }
    bool has_cycle = RecursivelyEmitMoveChainTargets(chain_start, targets);
    EmitMovesFromSource(source, std::move(targets));
    return has_cycle;
  }
References __, v8::internal::DCHECK(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::is_empty().
EmitMoves()
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::EmitMoves (RegisterT scratch) [inline]
Definition at line 128 of file maglev-code-generator.cc.
                                    {
    DCHECK(!scratch_.is_valid());
    scratch_ = scratch;
    for (RegisterT reg : kAllocatableRegistersT) {
      StartEmitMoveChain(reg);
      ValueNode* materializing_register_move =
          materializing_register_moves_[reg.code()];
      if (materializing_register_move) {
        materializing_register_move->LoadToRegister(masm_, reg);
      }
    }
    // Emit stack moves until the move set is empty -- each EmitMoveChain will
    // pop entries off the moves_from_stack_slot map so we can't use a simple
    // iteration here.
    while (!moves_from_stack_slot_.empty()) {
      StartEmitMoveChain(moves_from_stack_slot_.begin()->first);
    }
    for (auto [stack_slot, node] : materializing_stack_slot_moves_) {
      node->LoadToRegister(masm_, scratch_);
      __ Move(StackSlot{stack_slot}, scratch_);
    }
  }
References __, v8::internal::DCHECK(), and v8::internal::maglev::ValueNode::LoadToRegister().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor().
EmitMovesFromSource() [1/2]
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::EmitMovesFromSource (int32_t source_slot, GapMoveTargets && targets) [inline], [private]
Definition at line 446 of file maglev-code-generator.cc.
                                                                          {
    DCHECK_EQ(moves_from_stack_slot_.find(source_slot),
              moves_from_stack_slot_.end());
    // Cache the slot value on a register.
    RegisterT register_with_slot_value = RegisterT::no_reg();
    if (!targets.registers.is_empty()) {
      // If one of the targets is a register, we can move our value into it and
      // optimize the moves from this stack slot to always be via that register.
      register_with_slot_value = targets.registers.PopFirst();
    } else {
      DCHECK(!targets.stack_slots.empty());
      // Otherwise, cache the slot value on the scratch register, clobbering it
      // if necessary.
      if (scratch_has_cycle_start_) {
        Push(scratch_);
        scratch_has_cycle_start_ = false;
      }
      register_with_slot_value = scratch_;
    }
    // Now emit moves from that cached register instead of from the stack slot.
    DCHECK(register_with_slot_value.is_valid());
    DCHECK(moves_from_register_[register_with_slot_value.code()].is_empty());
    __ Move(register_with_slot_value, StackSlot{source_slot});
    // Decompress after the first move, subsequent moves reuse this register so
    // they're guaranteed to be decompressed.
    if constexpr (DecompressIfNeeded) {
      // The DecompressIfNeeded clause is redundant with the if-constexpr above,
      // but otherwise this code cannot be compiled by compilers not yet
      // implementing CWG2518.
      static_assert(DecompressIfNeeded && COMPRESS_POINTERS_BOOL);
      if (targets.needs_decompression == kNeedsDecompression) {
        __ DecompressTagged(register_with_slot_value, register_with_slot_value);
        targets.needs_decompression = kDoesNotNeedDecompression;
      }
    }
    EmitMovesFromSource(register_with_slot_value, std::move(targets));
  }
References __, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kDoesNotNeedDecompression, v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kNeedsDecompression, and v8::internal::no_reg.
EmitMovesFromSource() [2/2]
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::EmitMovesFromSource (RegisterT source_reg, GapMoveTargets && targets) [inline], [private]
Definition at line 423 of file maglev-code-generator.cc.
                                                                           {
    DCHECK(moves_from_register_[source_reg.code()].is_empty());
    if constexpr (DecompressIfNeeded) {
      // The DecompressIfNeeded clause is redundant with the if-constexpr above,
      // but otherwise this code cannot be compiled by compilers not yet
      // implementing CWG2518.
      static_assert(DecompressIfNeeded && COMPRESS_POINTERS_BOOL);
      if (targets.needs_decompression == kNeedsDecompression) {
        __ DecompressTagged(source_reg, source_reg);
      }
    }
    for (RegisterT target_reg : targets.registers) {
      DCHECK(moves_from_register_[target_reg.code()].is_empty());
      __ Move(target_reg, source_reg);
    }
    for (int32_t target_slot : targets.stack_slots) {
      DCHECK_EQ(moves_from_stack_slot_.find(target_slot),
                moves_from_stack_slot_.end());
      __ Move(StackSlot{target_slot}, source_reg);
    }
  }
References __, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kNeedsDecompression.
masm()
template<typename RegisterT , bool DecompressIfNeeded>
MaglevAssembler* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::masm () const [inline], [private]
Definition at line 491 of file maglev-code-generator.cc.
{ return masm_; }
operator=() [1/2]
template<typename RegisterT , bool DecompressIfNeeded>
ParallelMoveResolver v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::operator= (const ParallelMoveResolver< RegisterT, DecompressIfNeeded > &) [delete]
operator=() [2/2]
template<typename RegisterT , bool DecompressIfNeeded>
ParallelMoveResolver v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::operator= (ParallelMoveResolver< RegisterT, DecompressIfNeeded > &&) [delete]
Pop() [1/2]
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::Pop (DoubleRegister reg) [inline], [private]
Definition at line 489 of file maglev-code-generator.cc.
{ __ PopAll({reg}); }
References __.
Pop() [2/2]
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::Pop (Register reg) [inline], [private]
Definition at line 488 of file maglev-code-generator.cc.
{ __ Pop(reg); }
References __, and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::Pop().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::Pop().
PopTargets() [1/2]
template<typename RegisterT , bool DecompressIfNeeded>
GapMoveTargets v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::PopTargets (int32_t source_slot) [inline], [private]
Definition at line 337 of file maglev-code-generator.cc.
                                                 {
    auto handle = moves_from_stack_slot_.extract(source_slot);
    if (handle.empty()) return {};
    DCHECK(!handle.mapped().is_empty());
    return std::move(handle.mapped());
  }
References v8::internal::DCHECK(), and v8::internal::handle().
PopTargets() [2/2]
template<typename RegisterT , bool DecompressIfNeeded>
GapMoveTargets v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::PopTargets (RegisterT source_reg) [inline], [private]
Definition at line 333 of file maglev-code-generator.cc.
                                                  {
    return std::exchange(moves_from_register_[source_reg.code()],
                         GapMoveTargets{});
  }
Push() [1/2]
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::Push (DoubleRegister reg) [inline], [private]
Definition at line 487 of file maglev-code-generator.cc.
{ __ PushAll({reg}); }
References __, and v8::internal::baseline::detail::PushAll().
Push() [2/2]
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::Push (Register reg) [inline], [private]
Definition at line 486 of file maglev-code-generator.cc.
{ __ Push(reg); }
References __, and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::Push().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::Push().
RecordMove() [1/2]
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMove (ValueNode * source_node, compiler::InstructionOperand source, compiler::AllocatedOperand target, bool target_needs_to_be_decompressed) [inline]
Definition at line 108 of file maglev-code-generator.cc.
                                                        {
    if (target.IsAnyRegister()) {
      RecordMoveToRegister(source_node, source, ToRegisterT<RegisterT>(target),
                           target_needs_to_be_decompressed);
    } else {
      RecordMoveToStackSlot(source_node, source,
                            masm_->GetFramePointerOffsetForStackSlot(target),
                            target_needs_to_be_decompressed);
    }
  }
References v8::internal::compiler::InstructionOperand::IsAnyRegister().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves().
RecordMove() [2/2]
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMove (ValueNode * source_node, compiler::InstructionOperand source, RegisterT target_reg, NeedsDecompression target_needs_to_be_decompressed) [inline]
Definition at line 121 of file maglev-code-generator.cc.
                                                                      {
    RecordMoveToRegister(source_node, source, target_reg,
                         target_needs_to_be_decompressed);
  }
RecordMoveToRegister()
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister (ValueNode * node, compiler::InstructionOperand source, RegisterT target_reg, bool target_needs_to_be_decompressed) [inline], [private]
Definition at line 238 of file maglev-code-generator.cc.
                                                                  {
    // There shouldn't have been another move to this register already.
    CheckNoExistingMoveToRegister(target_reg);
    NeedsDecompression needs_decompression = kDoesNotNeedDecompression;
    if constexpr (DecompressIfNeeded) {
      if (target_needs_to_be_decompressed &&
          !node->decompresses_tagged_result()) {
        needs_decompression = kNeedsDecompression;
      }
    } else {
      DCHECK_IMPLIES(target_needs_to_be_decompressed,
                     node->decompresses_tagged_result());
    }
    GapMoveTargets* targets;
    if (source.IsAnyRegister()) {
      RegisterT source_reg = ToRegisterT<RegisterT>(source);
      if (target_reg == source_reg) {
        // We should never have a register aliasing case that needs
        // decompression, since this path is only used by exception phis and
        // they have no reg->reg moves.
        DCHECK_EQ(needs_decompression, kDoesNotNeedDecompression);
        return;
      }
      targets = &moves_from_register_[source_reg.code()];
    } else if (source.IsAnyStackSlot()) {
      int32_t source_slot = masm_->GetFramePointerOffsetForStackSlot(
          compiler::AllocatedOperand::cast(source));
      targets = &moves_from_stack_slot_[source_slot];
    } else {
      DCHECK(source.IsConstant());
      DCHECK(IsConstantNode(node->opcode()));
      materializing_register_moves_[target_reg.code()] = node;
      // No need to update `targets.needs_decompression`, materialization is
      // always decompressed.
      return;
    }
    targets->registers.set(target_reg);
    if (needs_decompression == kNeedsDecompression) {
      targets->needs_decompression = kNeedsDecompression;
    }
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::maglev::ValueNode::decompresses_tagged_result(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kDoesNotNeedDecompression, v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kNeedsDecompression, v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::needs_decompression, v8::internal::maglev::NodeBase::opcode(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::registers.
RecordMoveToStackSlot()
template<typename RegisterT , bool DecompressIfNeeded>
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot (ValueNode * node, compiler::InstructionOperand source, int32_t target_slot, bool target_needs_to_be_decompressed) [inline], [private]
Definition at line 286 of file maglev-code-generator.cc.
                                                                   {
    // There shouldn't have been another move to this stack slot already.
    CheckNoExistingMoveToStackSlot(target_slot);
    NeedsDecompression needs_decompression = kDoesNotNeedDecompression;
    if constexpr (DecompressIfNeeded) {
      if (target_needs_to_be_decompressed &&
          !node->decompresses_tagged_result()) {
        needs_decompression = kNeedsDecompression;
      }
    } else {
      DCHECK_IMPLIES(target_needs_to_be_decompressed,
                     node->decompresses_tagged_result());
    }
    GapMoveTargets* targets;
    if (source.IsAnyRegister()) {
      RegisterT source_reg = ToRegisterT<RegisterT>(source);
      targets = &moves_from_register_[source_reg.code()];
    } else if (source.IsAnyStackSlot()) {
      int32_t source_slot = masm_->GetFramePointerOffsetForStackSlot(
          compiler::AllocatedOperand::cast(source));
      if (source_slot == target_slot &&
          needs_decompression == kDoesNotNeedDecompression) {
        return;
      }
      targets = &moves_from_stack_slot_[source_slot];
    } else {
      DCHECK(source.IsConstant());
      DCHECK(IsConstantNode(node->opcode()));
      materializing_stack_slot_moves_.emplace_back(target_slot, node);
      // No need to update `targets.needs_decompression`, materialization is
      // always decompressed.
      return;
    }
    targets->stack_slots.push_back(target_slot);
    if (needs_decompression == kNeedsDecompression) {
      targets->needs_decompression = kNeedsDecompression;
    }
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::maglev::ValueNode::decompresses_tagged_result(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kDoesNotNeedDecompression, v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kNeedsDecompression, v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::needs_decompression, v8::internal::maglev::NodeBase::opcode(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::stack_slots.
RecursivelyEmitMoveChainTargets()
template<typename RegisterT , bool DecompressIfNeeded>
template<typename ChainStartT >
bool v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecursivelyEmitMoveChainTargets (ChainStartT chain_start, GapMoveTargets & targets) [inline], [private]
Definition at line 411 of file maglev-code-generator.cc.
                                                                {
    bool has_cycle = false;
    for (auto target : targets.registers) {
      has_cycle |= ContinueEmitMoveChain(chain_start, target);
    }
    for (int32_t target_slot : targets.stack_slots) {
      has_cycle |= ContinueEmitMoveChain(chain_start, target_slot);
    }
    return has_cycle;
  }
References v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::registers, and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::stack_slots.
StartEmitMoveChain()
template<typename RegisterT , bool DecompressIfNeeded>
template<typename SourceT >
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::StartEmitMoveChain (SourceT source) [inline], [private]
Definition at line 349 of file maglev-code-generator.cc.
                                          {
    DCHECK(!scratch_has_cycle_start_);
    GapMoveTargets targets = PopTargets(source);
    if (targets.is_empty()) return;
    // Start recursively emitting the move chain, with this source as the start
    // of the chain.
    bool has_cycle = RecursivelyEmitMoveChainTargets(source, targets);
    // Each connected component in the move graph can only have one cycle
    // (proof: each target can only have one incoming edge, so cycles in the
    // graph can only have outgoing edges, so there's no way to connect two
    // cycles). This means that if there's a cycle, the saved value must be the
    // chain start.
    if (has_cycle) {
      if (!scratch_has_cycle_start_) {
        Pop(scratch_);
        scratch_has_cycle_start_ = true;
      }
      EmitMovesFromSource(scratch_, std::move(targets));
      scratch_has_cycle_start_ = false;
      __ RecordComment("-- * End of cycle");
    } else {
      EmitMovesFromSource(source, std::move(targets));
      __ RecordComment("-- * Chain emitted with no cycles");
    }
  }
References __, v8::internal::DCHECK(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::is_empty().
Member Data Documentation
kAllocatableRegistersT
template<typename RegisterT , bool DecompressIfNeeded>
constexpr auto v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::kAllocatableRegistersT [static], [constexpr], [private]
Initial value:
=
      RegisterTHelper<RegisterT>::kAllocatableRegisters
Definition at line 99 of file maglev-code-generator.cc.
masm_
template<typename RegisterT , bool DecompressIfNeeded>
MaglevAssembler* const v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::masm_ [private]
Definition at line 493 of file maglev-code-generator.cc.
materializing_register_moves_
template<typename RegisterT , bool DecompressIfNeeded>
std::array<ValueNode*, RegisterT::kNumRegisters> v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::materializing_register_moves_ = {} [private]
Definition at line 511 of file maglev-code-generator.cc.
materializing_stack_slot_moves_
template<typename RegisterT , bool DecompressIfNeeded>
std::vector<std::pair<int32_t, ValueNode*> > v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::materializing_stack_slot_moves_ [private]
Definition at line 514 of file maglev-code-generator.cc.
moves_from_register_
template<typename RegisterT , bool DecompressIfNeeded>
std::array<GapMoveTargets, RegisterT::kNumRegisters> v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::moves_from_register_ [private]
Initial value:
=
      {}
Definition at line 502 of file maglev-code-generator.cc.
moves_from_stack_slot_
template<typename RegisterT , bool DecompressIfNeeded>
std::unordered_map<int32_t, GapMoveTargets> v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::moves_from_stack_slot_ [private]
Definition at line 507 of file maglev-code-generator.cc.
scratch_
template<typename RegisterT , bool DecompressIfNeeded>
RegisterT v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::scratch_ [private]
Definition at line 494 of file maglev-code-generator.cc.
scratch_has_cycle_start_
template<typename RegisterT , bool DecompressIfNeeded>
bool v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::scratch_has_cycle_start_ = false [private]
Definition at line 516 of file maglev-code-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-code-generator.cc