v8::internal::MutableBigInt Class Reference
Public Types
enum Rounding { kRoundDown
, kTie
, kRoundUp
 }
Public Member Functions
void InitializeDigits (uint32_t length, uint8_t value=0)
bigint::RWDigits rw_digits ()
void set_sign (bool new_sign)
void set_length (uint32_t new_length, ReleaseStoreTag)
void initialize_bitfield (bool sign, uint32_t length)
void set_digit (uint32_t n, digit_t value)
void set_64_bits (uint64_t bits)
Static Public Member Functions
static MaybeHandle< BigInt > MakeImmutable (MaybeHandle< MutableBigInt > maybe)
template<typename Isolate = v8::internal::Isolate>
static Handle< BigInt > MakeImmutable (Handle< MutableBigInt > result)
static void Canonicalize (Tagged< MutableBigInt > result)
template<typename IsolateT >
static MaybeHandle< MutableBigInt > New (IsolateT *isolate, uint32_t length, AllocationType allocation=AllocationType::kYoung)
static Handle< BigInt > NewFromInt (Isolate *isolate, int value)
static Handle< BigInt > NewFromDouble (Isolate *isolate, double value)
static Handle< MutableBigInt > Copy (Isolate *isolate, DirectHandle< BigIntBase > source)
template<typename IsolateT >
static Handle< BigInt > Zero (IsolateT *isolate, AllocationType allocation=AllocationType::kYoung)
static MaybeHandle< MutableBigInt > AbsoluteAddOne (Isolate *isolate, DirectHandle< BigIntBase > x, bool sign, Tagged< MutableBigInt > result_storage={})
static Handle< MutableBigInt > AbsoluteSubOne (Isolate *isolate, DirectHandle< BigIntBase > x)
static MaybeDirectHandle< BigInt > LeftShiftByAbsolute (Isolate *isolate, Handle< BigIntBase > x, Handle< BigIntBase > y)
static DirectHandle< BigInt > RightShiftByAbsolute (Isolate *isolate, Handle< BigIntBase > x, Handle< BigIntBase > y)
static DirectHandle< BigInt > RightShiftByMaximum (Isolate *isolate, bool sign)
static Maybe< digit_t > ToShiftAmount (Handle< BigIntBase > x)
static double ToDouble (DirectHandle< BigIntBase > x)
static Rounding DecideRounding (DirectHandle< BigIntBase > x, int mantissa_bits_unset, int digit_index, uint64_t current_digit)
static uint64_t GetRawBits (BigIntBase *x, bool *lossless)
static bool digit_ismax (digit_t x)
static bool IsMutableBigInt (Tagged< MutableBigInt > o)
Additional Inherited Members
Detailed Description
Definition at line 52 of file bigint.cc.
Member Enumeration Documentation
Rounding
enum v8::internal::MutableBigInt::Rounding
Enumerator
kRoundDown
kTie
kRoundUp
Definition at line 97 of file bigint.cc.
{ kRoundDown, kTie, kRoundUp };
Member Function Documentation
AbsoluteAddOne()
MaybeHandle< MutableBigInt > v8::internal::MutableBigInt::AbsoluteAddOne (Isolate * isolate, DirectHandle< BigIntBase > x, bool sign, Tagged< MutableBigInt > result_storage = {}) [static]
Definition at line 1138 of file bigint.cc.
                                          {
  uint32_t input_length = x->length();
  // The addition will overflow into a new digit if all existing digits are
  // at maximum.
  bool will_overflow = true;
  for (uint32_t i = 0; i < input_length; i++) {
    if (!digit_ismax(x->digit(i))) {
      will_overflow = false;
      break;
    }
  }
  uint32_t result_length = input_length + will_overflow;
  Handle<MutableBigInt> result(result_storage, isolate);
  if (result_storage.is_null()) {
    if (!New(isolate, result_length).ToHandle(&result)) return {};
  } else {
    DCHECK(result->length() == result_length);
  }
  if (input_length == 0) {
    result->set_digit(0, 1);
  } else if (input_length == 1 && !will_overflow) {
    result->set_digit(0, x->digit(0) + 1);
  } else {
    bigint::AddOne(result->rw_digits(), x->digits());
  }
  result->set_sign(sign);
  return result;
}
References v8::bigint::AddOne(), v8::internal::DCHECK(), digit_ismax(), v8::internal::Tagged< HeapObject >::is_null(), New(), v8::base::internal::result, v8::internal::BigIntBase::sign(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::BigInt::BitwiseNot(), v8::internal::BigInt::Decrement(), and v8::internal::BigInt::Increment().
AbsoluteSubOne()
Handle< MutableBigInt > v8::internal::MutableBigInt::AbsoluteSubOne (Isolate * isolate, DirectHandle< BigIntBase > x) [static]
Definition at line 1170 of file bigint.cc.
                                                  {
  DCHECK(!x->is_zero());
  uint32_t length = x->length();
  Handle<MutableBigInt> result = New(isolate, length).ToHandleChecked();
  if (length == 1) {
    result->set_digit(0, x->digit(0) - 1);
  } else {
    bigint::SubtractOne(result->rw_digits(), x->digits());
  }
  return result;
}
References v8::internal::DCHECK(), v8::internal::BigIntBase::length(), New(), v8::base::internal::result, and v8::bigint::SubtractOne().
Referenced by v8::internal::BigInt::BitwiseNot(), v8::internal::BigInt::Decrement(), and v8::internal::BigInt::Increment().
Canonicalize()
void v8::internal::MutableBigInt::Canonicalize (Tagged< MutableBigInt > result) [static]
Definition at line 298 of file bigint.cc.
                                                             {
  // Check if we need to right-trim any leading zero-digits.
  uint32_t old_length = result->length();
  uint32_t new_length = old_length;
  while (new_length > 0 && result->digit(new_length - 1) == 0) new_length--;
  uint32_t to_trim = old_length - new_length;
  if (to_trim != 0) {
    Heap* heap = Isolate::Current()->heap();
    if (!heap->IsLargeObject(result)) {
      uint32_t old_size =
          ALIGN_TO_ALLOCATION_ALIGNMENT(BigInt::SizeFor(old_length));
      uint32_t new_size =
          ALIGN_TO_ALLOCATION_ALIGNMENT(BigInt::SizeFor(new_length));
      heap->NotifyObjectSizeChange(result, old_size, new_size,
                                   ClearRecordedSlots::kNo);
    }
    result->set_length(new_length, kReleaseStore);
    // Canonicalize -0n.
    if (new_length == 0) {
      result->set_sign(false);
      // TODO(jkummerow): If we cache a canonical 0n, return that here.
    }
  }
  DCHECK_IMPLIES(result->length() > 0,
                 result->digit(result->length() - 1) != 0); // MSD is non-zero.
  // Callers that don't require trimming must ensure this themselves.
  DCHECK_IMPLIES(result->length() == 0, result->sign() == false);
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::Isolate::Current(), DCHECK_IMPLIES, v8::internal::Isolate::heap(), v8::internal::kNo, v8::kReleaseStore, v8::base::internal::result, and v8::internal::BigInt::SizeFor().
Referenced by MakeImmutable(), v8::internal::MutableBigInt_AbsoluteAddAndCanonicalize(), v8::internal::MutableBigInt_AbsoluteDivAndCanonicalize(), v8::internal::MutableBigInt_AbsoluteModAndCanonicalize(), v8::internal::MutableBigInt_AbsoluteMulAndCanonicalize(), v8::internal::MutableBigInt_AbsoluteSubAndCanonicalize(), v8::internal::MutableBigInt_BitwiseAndNegNegAndCanonicalize(), v8::internal::MutableBigInt_BitwiseAndPosNegAndCanonicalize(), v8::internal::MutableBigInt_BitwiseAndPosPosAndCanonicalize(), v8::internal::MutableBigInt_BitwiseOrNegNegAndCanonicalize(), v8::internal::MutableBigInt_BitwiseOrPosNegAndCanonicalize(), v8::internal::MutableBigInt_BitwiseOrPosPosAndCanonicalize(), v8::internal::MutableBigInt_BitwiseXorNegNegAndCanonicalize(), v8::internal::MutableBigInt_BitwiseXorPosNegAndCanonicalize(), v8::internal::MutableBigInt_BitwiseXorPosPosAndCanonicalize(), v8::internal::MutableBigInt_LeftShiftAndCanonicalize(), and v8::internal::MutableBigInt_RightShiftAndCanonicalize().
Copy()
Handle< MutableBigInt > v8::internal::MutableBigInt::Copy (Isolate * isolate, DirectHandle< BigIntBase > source) [static]
Definition at line 272 of file bigint.cc.
                                                                           {
  uint32_t length = source->length();
  // Allocating a BigInt of the same length as an existing BigInt cannot throw.
  Handle<MutableBigInt> result = New(isolate, length).ToHandleChecked();
  memcpy(result->raw_digits(), source->raw_digits(), length * kDigitSize);
  return result;
}
References v8::internal::BigIntBase::kDigitSize, v8::internal::BigIntBase::length(), New(), and v8::base::internal::result.
Referenced by v8::internal::BigInt::UnaryMinus().
DecideRounding()
MutableBigInt::Rounding v8::internal::MutableBigInt::DecideRounding (DirectHandle< BigIntBase > x, int mantissa_bits_unset, int digit_index, uint64_t current_digit) [static]
Definition at line 1089 of file bigint.cc.
                            {
  if (mantissa_bits_unset > 0) return kRoundDown;
  int top_unconsumed_bit;
  if (mantissa_bits_unset < 0) {
    // There are unconsumed bits in {current_digit}.
    top_unconsumed_bit = -mantissa_bits_unset - 1;
  } else {
    DCHECK_EQ(mantissa_bits_unset, 0);
    // {current_digit} fit the mantissa exactly; look at the next digit.
    if (digit_index == 0) return kRoundDown;
    digit_index--;
    current_digit = static_cast<uint64_t>(x->digit(digit_index));
    top_unconsumed_bit = kDigitBits - 1;
  }
  // If the most significant remaining bit is 0, round down.
  uint64_t bitmask = static_cast<uint64_t>(1) << top_unconsumed_bit;
  if ((current_digit & bitmask) == 0) {
    return kRoundDown;
  }
  // If any other remaining bit is set, round up.
  bitmask -= 1;
  if ((current_digit & bitmask) != 0) return kRoundUp;
  while (digit_index > 0) {
    digit_index--;
    if (x->digit(digit_index) != 0) return kRoundUp;
  }
  return kTie;
}
References DCHECK_EQ, v8::internal::BigIntBase::kDigitBits, kRoundDown, kRoundUp, and kTie.
Referenced by ToDouble().
digit_ismax()
static bool v8::internal::MutableBigInt::digit_ismax (digit_t x) [inline], [static]
Definition at line 106 of file bigint.cc.
                                            {
    return static_cast<digit_t>(~x) == 0;
  }
Referenced by AbsoluteAddOne().
GetRawBits()
uint64_t v8::internal::MutableBigInt::GetRawBits (BigIntBase * x, bool * lossless) [static]
Definition at line 1424 of file bigint.cc.
                                                                {
  if (lossless != nullptr) *lossless = true;
  if (x->is_zero()) return 0;
  uint32_t len = x->length();
  static_assert(kDigitBits == 64 || kDigitBits == 32);
  if (lossless != nullptr && len > 64 / kDigitBits) *lossless = false;
  uint64_t raw = static_cast<uint64_t>(x->digit(0));
  if (kDigitBits == 32 && len > 1) {
    raw |= static_cast<uint64_t>(x->digit(1)) << 32;
  }
  // Simulate two's complement. MSVC dislikes "-raw".
  return x->sign() ? ((~raw) + 1u) : raw;
}
References v8::internal::BigIntBase::digit(), v8::internal::BigIntBase::is_zero(), v8::internal::BigIntBase::kDigitBits, v8::internal::BigIntBase::length(), and v8::internal::BigIntBase::sign().
Referenced by v8::internal::BigInt::AsInt64(), and v8::internal::BigInt::AsUint64().
initialize_bitfield()
void v8::internal::MutableBigInt::initialize_bitfield (bool sign, uint32_t length) [inline]
Definition at line 122 of file bigint.cc.
                                                              {
    bitfield_.store(LengthBits::encode(length) | SignBits::encode(sign),
                    std::memory_order_relaxed);
  }
References v8::internal::BigIntBase::bitfield_, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::BigIntBase::length(), and v8::internal::BigIntBase::sign().
InitializeDigits()
void v8::internal::MutableBigInt::InitializeDigits (uint32_t length, uint8_t value = 0)
Definition at line 281 of file bigint.cc.
                                                                   {
  memset(raw_digits(), value, length * kDigitSize);
}
References v8::internal::BigIntBase::kDigitSize, v8::internal::BigIntBase::length(), and v8::internal::value.
IsMutableBigInt()
static bool v8::internal::MutableBigInt::IsMutableBigInt (Tagged< MutableBigInt > o) [inline], [static]
Definition at line 133 of file bigint.cc.
{ return IsBigInt(o); }
LeftShiftByAbsolute()
static MaybeDirectHandle<BigInt> v8::internal::MutableBigInt::LeftShiftByAbsolute (Isolate * isolate, Handle< BigIntBase > x, Handle< BigIntBase > y) [static]
MakeImmutable() [1/2]
template<typename IsolateT >
Handle< BigInt > v8::internal::MutableBigInt::MakeImmutable (Handle< MutableBigInt > result) [static]
Definition at line 293 of file bigint.cc.
                                                                        {
  MutableBigInt::Canonicalize(*result);
  return Cast<BigInt>(result);
}
References Canonicalize(), and v8::base::internal::result.
MakeImmutable() [2/2]
MaybeHandle< BigInt > v8::internal::MutableBigInt::MakeImmutable (MaybeHandle< MutableBigInt > maybe) [static]
Definition at line 285 of file bigint.cc.
                                      {
  Handle<MutableBigInt> result;
  if (!maybe.ToHandle(&result)) return {};
  return MakeImmutable(result);
}
References v8::base::internal::result, and v8::internal::MaybeHandle< T >::ToHandle().
Referenced by v8::internal::BigInt::Add(), v8::internal::BigInt::Allocate(), v8::internal::BigInt::AsIntN(), v8::internal::BigInt::AsUintN(), v8::internal::BigInt::BitwiseNot(), v8::internal::BigInt::Decrement(), v8::internal::BigInt::Divide(), v8::internal::BigInt::Exponentiate(), v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::BigInt::FromUint64(), v8::internal::BigInt::FromWords64(), v8::internal::BigInt::Increment(), v8::internal::BigInt::Multiply(), NewFromDouble(), NewFromInt(), v8::internal::BigInt::Remainder(), v8::internal::BigInt::Subtract(), and v8::internal::BigInt::UnaryMinus().
New()
template<typename IsolateT >
MaybeHandle< MutableBigInt > v8::internal::MutableBigInt::New (IsolateT * isolate, uint32_t length, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 166 of file bigint.cc.
                                                                         {
  if (length > BigInt::kMaxLength) {
    return ThrowBigIntTooBig<MutableBigInt>(isolate);
  }
  Handle<MutableBigInt> result =
      Cast<MutableBigInt>(isolate->factory()->NewBigInt(length, allocation));
  result->initialize_bitfield(false, length);
#if DEBUG
  result->InitializeDigits(length, 0xBF);
#endif
  return result;
}
References v8::internal::BigIntBase::kMaxLength, v8::internal::BigIntBase::length(), and v8::base::internal::result.
Referenced by AbsoluteAddOne(), AbsoluteSubOne(), v8::internal::BigInt::Add(), v8::internal::BigInt::Allocate(), v8::internal::BigInt::AsIntN(), v8::internal::BigInt::AsUintN(), Copy(), v8::internal::BigInt::Divide(), v8::internal::BigInt::Exponentiate(), v8::internal::BigInt::FromWords64(), v8::internal::BigInt::Multiply(), v8::internal::BigInt::Remainder(), v8::internal::BigInt::Subtract(), and Zero().
NewFromDouble()
Handle< BigInt > v8::internal::MutableBigInt::NewFromDouble (Isolate * isolate, double value) [static]
Definition at line 200 of file bigint.cc.
                                                                          {
  DCHECK_EQ(value, std::floor(value));
  if (value == 0) return Zero(isolate);
  bool sign = value < 0; // -0 was already handled above.
  uint64_t double_bits = base::bit_cast<uint64_t>(value);
  int32_t raw_exponent =
      static_cast<int32_t>(double_bits >>
                           base::Double::kPhysicalSignificandSize) &
      0x7FF;
  DCHECK_NE(raw_exponent, 0x7FF);
  DCHECK_GE(raw_exponent, 0x3FF);
  uint32_t exponent = raw_exponent - 0x3FF;
  uint32_t digits = exponent / kDigitBits + 1;
  Handle<MutableBigInt> result =
      Cast<MutableBigInt>(isolate->factory()->NewBigInt(digits));
  result->initialize_bitfield(sign, digits);
  // We construct a BigInt from the double {value} by shifting its mantissa
  // according to its exponent and mapping the bit pattern onto digits.
  //
  // <----------- bitlength = exponent + 1 ----------->
  // <----- 52 ------> <------ trailing zeroes ------>
  // mantissa: 1yyyyyyyyyyyyyyyyy 0000000000000000000000000000000
  // digits: 0001xxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx
  // <--> <------>
  // msd_topbit kDigitBits
  //
  uint64_t mantissa =
      (double_bits & base::Double::kSignificandMask) | base::Double::kHiddenBit;
  const uint32_t kMantissaTopBit =
      base::Double::kSignificandSize - 1; // 0-indexed.
  // 0-indexed position of most significant bit in the most significant digit.
  uint32_t msd_topbit = exponent % kDigitBits;
  // Number of unused bits in {mantissa}. We'll keep them shifted to the
  // left (i.e. most significant part) of the underlying uint64_t.
  uint32_t remaining_mantissa_bits = 0;
  // Next digit under construction.
  digit_t digit;
  // First, build the MSD by shifting the mantissa appropriately.
  if (msd_topbit < kMantissaTopBit) {
    remaining_mantissa_bits = kMantissaTopBit - msd_topbit;
    digit = mantissa >> remaining_mantissa_bits;
    mantissa = mantissa << (64 - remaining_mantissa_bits);
  } else {
    DCHECK_GE(msd_topbit, kMantissaTopBit);
    digit = mantissa << (msd_topbit - kMantissaTopBit);
    mantissa = 0;
  }
  result->set_digit(digits - 1, digit);
  // Then fill in the rest of the digits.
  static_assert(BigInt::kMaxLength < kMaxInt);
  for (int32_t digit_index = digits - 2; digit_index >= 0; digit_index--) {
    if (remaining_mantissa_bits > 0) {
      remaining_mantissa_bits -= kDigitBits;
      if (sizeof(digit) == 4) {
        digit = mantissa >> 32;
        mantissa = mantissa << 32;
      } else {
        DCHECK_EQ(sizeof(digit), 8);
        digit = mantissa;
        mantissa = 0;
      }
    } else {
      digit = 0;
    }
    result->set_digit(digit_index, digit);
  }
  return MakeImmutable(result);
}
References DCHECK_EQ, DCHECK_GE, DCHECK_NE, v8::internal::BigIntBase::digit(), v8::internal::BigIntBase::digits(), v8::internal::Isolate::factory(), v8::internal::BigIntBase::kDigitBits, v8::base::Double::kHiddenBit, v8::internal::kMaxInt, v8::internal::BigIntBase::kMaxLength, v8::base::Double::kPhysicalSignificandSize, v8::base::Double::kSignificandMask, v8::base::Double::kSignificandSize, MakeImmutable(), v8::internal::FactoryBase< Impl >::NewBigInt(), v8::base::internal::result, v8::internal::BigIntBase::sign(), v8::internal::value, and Zero().
Referenced by v8::internal::BigInt::FromNumber().
NewFromInt()
Handle< BigInt > v8::internal::MutableBigInt::NewFromInt (Isolate * isolate, int value) [static]
Definition at line 181 of file bigint.cc.
                                                                    {
  if (value == 0) return Zero(isolate);
  Handle<MutableBigInt> result =
      Cast<MutableBigInt>(isolate->factory()->NewBigInt(1));
  bool sign = value < 0;
  result->initialize_bitfield(sign, 1);
  if (!sign) {
    result->set_digit(0, value);
  } else {
    if (value == kMinInt) {
      static_assert(kMinInt == -kMaxInt - 1);
      result->set_digit(0, static_cast<BigInt::digit_t>(kMaxInt) + 1);
    } else {
      result->set_digit(0, -value);
    }
  }
  return MakeImmutable(result);
}
References v8::internal::Isolate::factory(), v8::internal::kMaxInt, v8::internal::kMinInt, MakeImmutable(), v8::internal::FactoryBase< Impl >::NewBigInt(), v8::base::internal::result, v8::internal::BigIntBase::sign(), v8::internal::value, and Zero().
Referenced by v8::internal::BigInt::Decrement(), v8::internal::BigInt::Exponentiate(), v8::internal::BigInt::FromNumber(), and v8::internal::requires().
RightShiftByAbsolute()
static DirectHandle<BigInt> v8::internal::MutableBigInt::RightShiftByAbsolute (Isolate * isolate, Handle< BigIntBase > x, Handle< BigIntBase > y) [static]
RightShiftByMaximum()
static DirectHandle<BigInt> v8::internal::MutableBigInt::RightShiftByMaximum (Isolate * isolate, bool sign) [static]
rw_digits()
bigint::RWDigits v8::internal::MutableBigInt::rw_digits ()
Definition at line 147 of file bigint.cc.
                                        {
  return bigint::RWDigits(reinterpret_cast<digit_t*>(raw_digits()), length());
}
References v8::internal::BigIntBase::length().
set_64_bits()
void v8::internal::MutableBigInt::set_64_bits (uint64_t bits)
Definition at line 1451 of file bigint.cc.
                                             {
  static_assert(kDigitBits == 64 || kDigitBits == 32);
  if (kDigitBits == 64) {
    set_digit(0, static_cast<digit_t>(bits));
  } else {
    set_digit(0, static_cast<digit_t>(bits & 0xFFFFFFFFu));
    set_digit(1, static_cast<digit_t>(bits >> 32));
  }
}
References v8::internal::BigIntBase::kDigitBits, and set_digit().
set_digit()
void v8::internal::MutableBigInt::set_digit (uint32_t n, digit_t value) [inline]
Definition at line 126 of file bigint.cc.
                                                   {
    SLOW_DCHECK(n < length());
    raw_digits()[n].set_value(value);
  }
References v8::internal::BigIntBase::length(), SLOW_DCHECK, and v8::internal::value.
Referenced by set_64_bits().
set_length()
void v8::internal::MutableBigInt::set_length (uint32_t new_length, ReleaseStoreTag) [inline]
Definition at line 117 of file bigint.cc.
                                                               {
    bitfield_.store(LengthBits::update(
                        bitfield_.load(std::memory_order_relaxed), new_length),
                    std::memory_order_relaxed);
  }
References v8::internal::BigIntBase::bitfield_, and v8::base::BitField< T, shift, size, U >::update().
set_sign()
void v8::internal::MutableBigInt::set_sign (bool new_sign) [inline]
Definition at line 112 of file bigint.cc.
                                      {
    bitfield_.store(
        SignBits::update(bitfield_.load(std::memory_order_relaxed), new_sign),
        std::memory_order_relaxed);
  }
References v8::internal::BigIntBase::bitfield_, and v8::base::BitField< T, shift, size, U >::update().
ToDouble()
double v8::internal::MutableBigInt::ToDouble (DirectHandle< BigIntBase > x) [static]
Definition at line 1031 of file bigint.cc.
                                                         {
  if (x->is_zero()) return 0.0;
  uint32_t x_length = x->length();
  digit_t x_msd = x->digit(x_length - 1);
  uint32_t msd_leading_zeros = base::bits::CountLeadingZeros(x_msd);
  uint32_t x_bitlength = x_length * kDigitBits - msd_leading_zeros;
  if (x_bitlength > 1024) return x->sign() ? -V8_INFINITY : V8_INFINITY;
  uint64_t exponent = x_bitlength - 1;
  // We need the most significant bit shifted to the position of a double's
  // "hidden bit". We also need to hide that MSB, so we shift it out.
  uint64_t current_digit = x_msd;
  uint32_t digit_index = x_length - 1;
  uint32_t shift = msd_leading_zeros + 1 + (64 - kDigitBits);
  DCHECK_LE(1, shift);
  DCHECK_LE(shift, 64);
  uint64_t mantissa = (shift == 64) ? 0 : current_digit << shift;
  mantissa >>= 12;
  int32_t mantissa_bits_unset = shift - 12;
  // If not all mantissa bits are defined yet, get more digits as needed.
  if (mantissa_bits_unset >= static_cast<int32_t>(kDigitBits) &&
      digit_index > 0) {
    digit_index--;
    current_digit = static_cast<uint64_t>(x->digit(digit_index));
    mantissa |= (current_digit << (mantissa_bits_unset - kDigitBits));
    mantissa_bits_unset -= kDigitBits;
  }
  if (mantissa_bits_unset > 0 && digit_index > 0) {
    DCHECK_LT(mantissa_bits_unset, kDigitBits);
    digit_index--;
    current_digit = static_cast<uint64_t>(x->digit(digit_index));
    mantissa |= (current_digit >> (kDigitBits - mantissa_bits_unset));
    mantissa_bits_unset -= kDigitBits;
  }
  // If there are unconsumed digits left, we may have to round.
  Rounding rounding =
      DecideRounding(x, mantissa_bits_unset, digit_index, current_digit);
  if (rounding == kRoundUp || (rounding == kTie && (mantissa & 1) == 1)) {
    mantissa++;
    // Incrementing the mantissa can overflow the mantissa bits. In that case
    // the new mantissa will be all zero (plus hidden bit).
    if ((mantissa >> base::Double::kPhysicalSignificandSize) != 0) {
      mantissa = 0;
      exponent++;
      // Incrementing the exponent can overflow too.
      if (exponent > 1023) {
        return x->sign() ? -V8_INFINITY : V8_INFINITY;
      }
    }
  }
  // Assemble the result.
  uint64_t sign_bit = x->sign() ? (static_cast<uint64_t>(1) << 63) : 0;
  exponent = (exponent + 0x3FF) << base::Double::kPhysicalSignificandSize;
  uint64_t double_bits = sign_bit | exponent | mantissa;
  return base::bit_cast<double>(double_bits);
}
References v8::base::bits::CountLeadingZeros(), DCHECK_LE, DCHECK_LT, DecideRounding(), v8::internal::BigIntBase::kDigitBits, v8::base::Double::kPhysicalSignificandSize, kRoundUp, kTie, and V8_INFINITY.
Referenced by v8::internal::BigInt::ToNumber().
ToShiftAmount()
static Maybe<digit_t> v8::internal::MutableBigInt::ToShiftAmount (Handle< BigIntBase > x) [static]
Zero()
template<typename IsolateT >
static Handle<BigInt> v8::internal::MutableBigInt::Zero (IsolateT * isolate, AllocationType allocation = AllocationType::kYoung) [inline], [static]
Definition at line 72 of file bigint.cc.
                                                                           {
    // TODO(jkummerow): Consider caching a canonical zero-BigInt.
    return MakeImmutable<IsolateT>(
        New(isolate, 0, allocation).ToHandleChecked());
  }
References New().
Referenced by v8::internal::BigInt::AsIntN(), v8::internal::BigInt::AsUintN(), v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromUint64(), v8::internal::BigInt::FromWords64(), NewFromDouble(), NewFromInt(), and v8::internal::BigInt::Zero().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/bigint.cc