v8::internal::PropertyKey Class Reference
#include <lookup.h>
Public Member Functions
PropertyKey (Isolate *isolate, double index)
template<template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< Name >, DirectHandle< Name >>) inline PropertyKey(Isolate *isolate
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>) inline PropertyKey(Isolate *isolate
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>) PropertyKey(Isolate *isolate
bool is_element () const
DirectHandle< Name > name () const
size_t index () const
DirectHandle< Name > GetName (Isolate *isolate)
Public Attributes
HandleType< Name > name
HandleType< T > valid_key
HandleType< T > key
HandleType< T > bool * success
Private Member Functions
template<template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< Name >, DirectHandle< Name >>) inline PropertyKey(Isolate *isolate
Private Attributes
friend LookupIterator
HandleType< Name > size_t index
DirectHandle< Name > name_
size_t index_
Detailed Description
Definition at line 20 of file lookup.h.
Constructor & Destructor Documentation
PropertyKey()
v8::internal::PropertyKey::PropertyKey (Isolate * isolate, double index) [inline]
Definition at line 136 of file lookup-inl.h.
                                                       {
  DCHECK_EQ(index, static_cast<uint64_t>(index));
#if V8_TARGET_ARCH_32_BIT
  if (index <= JSObject::kMaxElementIndex) {
    static_assert(JSObject::kMaxElementIndex <=
                  std::numeric_limits<size_t>::max());
    index_ = static_cast<size_t>(index);
  } else {
    index_ = LookupIterator::kInvalidIndex;
    name_ = isolate->factory()->InternalizeString(
        isolate->factory()->DoubleToString(index));
  }
#else
  index_ = static_cast<size_t>(index);
#endif
}
References DCHECK_EQ, v8::internal::FactoryBase< Impl >::DoubleToString(), v8::internal::Isolate::factory(), index, index_, v8::internal::Factory::InternalizeString(), v8::internal::LookupIterator::kInvalidIndex, v8::internal::JSObject::kMaxElementIndex, and name_.
Member Function Documentation
GetName()
DirectHandle< Name > v8::internal::PropertyKey::GetName (Isolate * isolate) [inline]
Definition at line 232 of file lookup-inl.h.
                                                        {
  if (name_.is_null()) {
    DCHECK(is_element());
    name_ = isolate->factory()->SizeToString(index_);
  }
  return name_;
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), index_, is_element(), name_, and v8::internal::Factory::SizeToString().
index()
size_t v8::internal::PropertyKey::index () const [inline]
Definition at line 38 of file lookup.h.
{ return index_; }
References index_.
is_element()
bool v8::internal::PropertyKey::is_element () const [inline]
Definition at line 228 of file lookup-inl.h.
                                   {
  return index_ != LookupIterator::kInvalidIndex;
}
References index_, and v8::internal::LookupIterator::kInvalidIndex.
Referenced by v8::internal::anonymous_namespace{js-array-buffer.cc}::CanonicalNumericIndexString(), v8::internal::JSTypedArray::DefineOwnProperty(), GetName(), and v8::internal::LookupIterator::is_js_array_element().
name()
DirectHandle<Name> v8::internal::PropertyKey::name () const [inline]
Definition at line 37 of file lookup.h.
{ return name_; }
References name_.
requires() [1/4]
template<template< typename > typename HandleType>
v8::internal::PropertyKey::requires (std::is_convertible_v< HandleType< Name >, DirectHandle< Name >>)
requires() [2/4]
template<template< typename > typename HandleType>
v8::internal::PropertyKey::requires (std::is_convertible_v< HandleType< Name >, DirectHandle< Name >>) [private]
requires() [3/4]
template<typename T , template< typename > typename HandleType>
v8::internal::PropertyKey::requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>)
requires() [4/4]
template<typename T , template< typename > typename HandleType>
v8::internal::PropertyKey::requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>)
Member Data Documentation
index
HandleType<Name> size_t v8::internal::PropertyKey::index [private]
Definition at line 47 of file lookup.h.
Referenced by v8::internal::JSTypedArray::DefineOwnProperty(), and PropertyKey().
index_
size_t v8::internal::PropertyKey::index_ [private]
Definition at line 50 of file lookup.h.
Referenced by v8::internal::LookupIterator::array_index(), GetName(), index(), v8::internal::LookupIterator::index(), is_element(), v8::internal::LookupIterator::is_js_array_element(), v8::internal::LookupIterator::IsElement(), and PropertyKey().
key
HandleType<T> v8::internal::PropertyKey::key
Definition at line 34 of file lookup.h.
LookupIterator
friend v8::internal::PropertyKey::LookupIterator [private]
Definition at line 42 of file lookup.h.
name
HandleType< Name > v8::internal::PropertyKey::name
Definition at line 26 of file lookup.h.
Referenced by v8::internal::anonymous_namespace{js-array-buffer.cc}::CanonicalNumericIndexString().
name_
DirectHandle<Name> v8::internal::PropertyKey::name_ [private]
Definition at line 49 of file lookup.h.
Referenced by GetName(), name(), and PropertyKey().
success
HandleType<T> bool* v8::internal::PropertyKey::success
Definition at line 34 of file lookup.h.
valid_key
HandleType<T> v8::internal::PropertyKey::valid_key
Definition at line 30 of file lookup.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/lookup.h
/mnt/V8SourceCode/src/objects/lookup-inl.h