v8::internal::torque::BlockBindings< T > Class Template Reference
#include <implementation-visitor.h>
Public Member Functions
BlockBindings (BindingsManager< T > *manager)
Binding< T > * Add (std::string name, T value, bool mark_as_used=false)
Binding< T > * Add (const Identifier *name, T value, bool mark_as_used=false)
std::vector< Binding< T > * > bindings () const
Private Member Functions
void ReportErrorIfAlreadyBound (const std::string &name)
Private Attributes
BindingsManager< T > * manager_
std::vector< std::unique_ptr< Binding< T > > > bindings_
Detailed Description
template<class T>
class v8::internal::torque::BlockBindings< T >
Definition at line 328 of file implementation-visitor.h.
Constructor & Destructor Documentation
BlockBindings()
template<class T >
v8::internal::torque::BlockBindings< T >::BlockBindings (BindingsManager< T > * manager) [inline], [explicit]
Definition at line 330 of file implementation-visitor.h.
: manager_(manager) {}
Member Function Documentation
Add() [1/2]
template<class T >
Binding<T>* v8::internal::torque::BlockBindings< T >::Add (const Identifier * name, T value, bool mark_as_used = false) [inline]
Definition at line 341 of file implementation-visitor.h.
                                                                              {
    ReportErrorIfAlreadyBound(name->value);
    auto binding =
        std::make_unique<Binding<T>>(manager_, name, std::move(value));
    Binding<T>* result = binding.get();
    if (mark_as_used) binding->SetUsed();
    bindings_.push_back(std::move(binding));
    return result;
  }
References v8::internal::torque::BlockBindings< T >::bindings_, v8::internal::torque::BlockBindings< T >::manager_, v8::internal::name, v8::internal::torque::BlockBindings< T >::ReportErrorIfAlreadyBound(), v8::base::internal::result, and v8::internal::value.
Add() [2/2]
template<class T >
Binding<T>* v8::internal::torque::BlockBindings< T >::Add (std::string name, T value, bool mark_as_used = false) [inline]
Definition at line 331 of file implementation-visitor.h.
                                                                      {
    ReportErrorIfAlreadyBound(name);
    auto binding =
        std::make_unique<Binding<T>>(manager_, name, std::move(value));
    Binding<T>* result = binding.get();
    if (mark_as_used) binding->SetUsed();
    bindings_.push_back(std::move(binding));
    return result;
  }
References v8::internal::torque::BlockBindings< T >::bindings_, v8::internal::torque::BlockBindings< T >::manager_, v8::internal::name, v8::internal::torque::BlockBindings< T >::ReportErrorIfAlreadyBound(), v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), v8::internal::torque::ImplementationVisitor::GenerateArrayLength(), v8::internal::torque::ImplementationVisitor::InlineMacro(), and v8::internal::torque::ImplementationVisitor::Visit().
bindings()
template<class T >
std::vector<Binding<T>*> v8::internal::torque::BlockBindings< T >::bindings () const [inline]
Definition at line 351 of file implementation-visitor.h.
                                          {
    std::vector<Binding<T>*> result;
    result.reserve(bindings_.size());
    for (auto& b : bindings_) {
      result.push_back(b.get());
    }
    return result;
  }
References v8::internal::torque::BlockBindings< T >::bindings_, and v8::base::internal::result.
ReportErrorIfAlreadyBound()
template<class T >
void v8::internal::torque::BlockBindings< T >::ReportErrorIfAlreadyBound (const std::string & name) [inline], [private]
Definition at line 361 of file implementation-visitor.h.
                                                        {
    for (const auto& binding : bindings_) {
      if (binding->name() == name) {
        ReportError(
            "redeclaration of name \"", name,
            "\" in the same block is illegal, previous declaration at: ",
            binding->declaration_position());
      }
    }
  }
References v8::internal::torque::BlockBindings< T >::bindings_, v8::internal::name, and v8::internal::torque::ReportError().
Referenced by v8::internal::torque::BlockBindings< T >::Add().
Member Data Documentation
bindings_
template<class T >
std::vector<std::unique_ptr<Binding<T> > > v8::internal::torque::BlockBindings< T >::bindings_ [private]
Definition at line 373 of file implementation-visitor.h.
Referenced by v8::internal::torque::BlockBindings< T >::Add(), v8::internal::torque::BlockBindings< T >::bindings(), and v8::internal::torque::BlockBindings< T >::ReportErrorIfAlreadyBound().
manager_
template<class T >
BindingsManager<T>* v8::internal::torque::BlockBindings< T >::manager_ [private]
Definition at line 372 of file implementation-visitor.h.
Referenced by v8::internal::torque::BlockBindings< T >::Add().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/implementation-visitor.h