v8::internal::maglev::EagerDeoptInfo Class Reference
#include <maglev-ir.h>
Public Member Functions
EagerDeoptInfo (Zone *zone, const DeoptFrame top_frame, compiler::FeedbackSource feedback_to_update)
DeoptimizeReason reason () const
void set_reason (DeoptimizeReason reason)
template<typename Function >
void ForEachInput (Function &&f)
template<typename Function >
void ForEachInput (Function &&f) const
Private Attributes
DeoptimizeReason reason_ = DeoptimizeReason::kUnknown
Additional Inherited Members
Detailed Description
Definition at line 1867 of file maglev-ir.h.
Constructor & Destructor Documentation
EagerDeoptInfo()
v8::internal::maglev::EagerDeoptInfo::EagerDeoptInfo (Zone * zone, const DeoptFrame top_frame, compiler::FeedbackSource feedback_to_update) [inline]
Definition at line 1869 of file maglev-ir.h.
      : DeoptInfo(zone, top_frame, feedback_to_update) {}
Member Function Documentation
ForEachInput() [1/2]
template<typename Function >
void v8::internal::maglev::EagerDeoptInfo::ForEachInput (Function && f)
Definition at line 113 of file maglev-deopt-frame-visitor.h.
                                              {
  DeoptInfoVisitor<EagerDeoptInfo>::ForEager(this, f);
}
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateEagerDeopt(), v8::internal::maglev::SweepIdentityNodes::Process(), and v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot().
ForEachInput() [2/2]
template<typename Function >
void v8::internal::maglev::EagerDeoptInfo::ForEachInput (Function && f) const
Definition at line 118 of file maglev-deopt-frame-visitor.h.
                                                    {
  DeoptInfoVisitor<const EagerDeoptInfo>::ForEager(this, f);
}
reason()
DeoptimizeReason v8::internal::maglev::EagerDeoptInfo::reason () const [inline]
Definition at line 1873 of file maglev-ir.h.
{ return reason_; }
References reason_.
Referenced by v8::internal::maglev::MaglevAssembler::GetDeoptLabel(), and set_reason().
set_reason()
void v8::internal::maglev::EagerDeoptInfo::set_reason (DeoptimizeReason reason) [inline]
Definition at line 1874 of file maglev-ir.h.
{ reason_ = reason; }
References reason(), and reason_.
Referenced by v8::internal::maglev::MaglevAssembler::GetDeoptLabel().
Member Data Documentation
reason_
DeoptimizeReason v8::internal::maglev::EagerDeoptInfo::reason_ = DeoptimizeReason::kUnknown [private]
Definition at line 1882 of file maglev-ir.h.
Referenced by reason(), and set_reason().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-deopt-frame-visitor.h