v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator Class Reference
#include <turboshaft-builtins-assembler-inl.h>
Public Types
using iterator_type = V< WordPtr >
using value_type = V< Object >
Public Member Functions
Iterator (const BuiltinArgumentsTS *args, ConstOrV< WordPtr > begin_index, ConstOrV< WordPtr > end_index)
template<typename A >
iterator_type Begin (A &assembler)
template<typename A >
OptionalV< Word32 > IsEnd (A &assembler, iterator_type current_iterator) const
template<typename A >
iterator_type Advance (A &assembler, iterator_type current_iterator) const
template<typename A >
value_type Dereference (A &assembler, iterator_type current_iterator) const
Private Attributes
const BuiltinArgumentsTS * args_
ConstOrV< WordPtr > begin_index_
ConstOrV< WordPtr > end_index_
V< WordPtr > end_offset_
Detailed Description
template<typename Assembler>
class v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator
Definition at line 105 of file turboshaft-builtins-assembler-inl.h.
Member Typedef Documentation
iterator_type
template<typename Assembler >
using v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::iterator_type = V<WordPtr>
Definition at line 107 of file turboshaft-builtins-assembler-inl.h.
value_type
template<typename Assembler >
using v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::value_type = V<Object>
Definition at line 108 of file turboshaft-builtins-assembler-inl.h.
Constructor & Destructor Documentation
Iterator()
template<typename Assembler >
v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Iterator (const BuiltinArgumentsTS * args, ConstOrV< WordPtr > begin_index, ConstOrV< WordPtr > end_index) [inline]
Definition at line 111 of file turboshaft-builtins-assembler-inl.h.
        : args_(args), begin_index_(begin_index), end_index_(end_index) {}
Member Function Documentation
Advance()
template<typename Assembler >
template<typename A >
iterator_type v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Advance (A & assembler, iterator_type current_iterator) const [inline]
Definition at line 130 of file turboshaft-builtins-assembler-inl.h.
                                                                              {
      return assembler.WordPtrAdd(
          current_iterator, ElementsKindToByteSize(SYSTEM_POINTER_ELEMENTS));
    }
References v8::internal::ElementsKindToByteSize(), and v8::internal::SYSTEM_POINTER_ELEMENTS.
Begin()
template<typename Assembler >
template<typename A >
iterator_type v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Begin (A & assembler) [inline]
Definition at line 116 of file turboshaft-builtins-assembler-inl.h.
                                      {
      DCHECK(!end_offset_.valid());
      // Pre-compute the end offset.
      end_offset_ = args_->AtIndexPtr(assembler.resolve(end_index_));
      return args_->AtIndexPtr(assembler.resolve(begin_index_));
    }
References v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::args_, v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndexPtr(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::begin_index_, v8::internal::DCHECK(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::end_index_, v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::end_offset_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Dereference()
template<typename Assembler >
template<typename A >
value_type v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Dereference (A & assembler, iterator_type current_iterator) const [inline]
Definition at line 136 of file turboshaft-builtins-assembler-inl.h.
                                                                               {
      return V<Object>::Cast(assembler.LoadOffHeap(
          current_iterator, MemoryRepresentation::AnyTagged()));
    }
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), and v8::internal::compiler::turboshaft::V< T >::Cast().
IsEnd()
template<typename Assembler >
template<typename A >
OptionalV<Word32> v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::IsEnd (A & assembler, iterator_type current_iterator) const [inline]
Definition at line 124 of file turboshaft-builtins-assembler-inl.h.
                                                                  {
      return assembler.UintPtrLessThanOrEqual(end_offset_, current_iterator);
    }
References v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::end_offset_.
Member Data Documentation
args_
template<typename Assembler >
const BuiltinArgumentsTS* v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::args_ [private]
Definition at line 142 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Begin().
begin_index_
template<typename Assembler >
ConstOrV<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::begin_index_ [private]
Definition at line 143 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Begin().
end_index_
template<typename Assembler >
ConstOrV<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::end_index_ [private]
Definition at line 144 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Begin().
end_offset_
template<typename Assembler >
V<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::end_offset_ [private]
Definition at line 145 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Begin(), and v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::IsEnd().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/turboshaft-builtins-assembler-inl.h