cppgc::internal::Heap Class Reference
#include <heap.h>
Public Member Functions
Heap (std::shared_ptr< cppgc::Platform > platform, cppgc::Heap::HeapOptions options)
~Heap () final
HeapBase & AsBase ()
const HeapBase & AsBase () const
void CollectGarbage (GCConfig) final
void StartIncrementalGarbageCollection (GCConfig) final
void FinalizeIncrementalGarbageCollectionIfRunning (GCConfig)
size_t epoch () const final
std::optional< EmbedderStackState > overridden_stack_state () const final
void set_override_stack_state (EmbedderStackState state) final
void clear_overridden_stack_state () final
void EnableGenerationalGC ()
void DisableHeapGrowingForTesting ()
Static Public Member Functions
static Heap * From (cppgc::Heap *heap)
static const Heap * From (const cppgc::Heap *heap)
Private Member Functions
void StartGarbageCollection (GCConfig)
void FinalizeGarbageCollection (StackState)
void FinalizeGarbageCollectionImpl (StackState)
void FinalizeIncrementalGarbageCollectionIfNeeded (StackState) final
void StartIncrementalGarbageCollectionForTesting () final
void FinalizeIncrementalGarbageCollectionForTesting (EmbedderStackState) final
Private Attributes
GCConfig config_
GCInvoker gc_invoker_
HeapGrowing growing_
bool generational_gc_enabled_ = false
size_t epoch_ = 0
std::optional< cppgc::EmbedderStackState > override_stack_state_
Additional Inherited Members
Detailed Description
Definition at line 21 of file heap.h.
Constructor & Destructor Documentation
Heap()
cppgc::internal::Heap::Heap (std::shared_ptr< cppgc::Platform > platform, cppgc::Heap::HeapOptions options)
Definition at line 75 of file heap.cc.
    : HeapBase(platform, options.custom_spaces, options.stack_support,
               options.marking_support, options.sweeping_support, gc_invoker_),
      gc_invoker_(this, platform_.get(), options.stack_support),
      growing_(&gc_invoker_, stats_collector_.get(),
               options.resource_constraints, options.marking_support,
               options.sweeping_support) {
  CHECK_IMPLIES(options.marking_support != HeapBase::MarkingType::kAtomic,
                platform_->GetForegroundTaskRunner());
  CHECK_IMPLIES(options.sweeping_support != HeapBase::SweepingType::kAtomic,
                platform_->GetForegroundTaskRunner());
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  object_allocator().UpdateAllocationTimeout();
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
}
References CHECK_IMPLIES, cppgc::Heap::kAtomic, cppgc::Heap::HeapOptions::marking_support, cppgc::internal::HeapBase::object_allocator(), cppgc::internal::HeapBase::platform_, and cppgc::Heap::HeapOptions::sweeping_support.
 Heap()
cppgc::internal::Heap::~Heap () [final], [virtual]
Reimplemented from cppgc::Heap.
Definition at line 92 of file heap.cc.
            {
  // Gracefully finish already running GC if any, but don't finalize live
  // objects.
  FinalizeIncrementalGarbageCollectionIfRunning(
      {CollectionType::kMajor, StackState::kMayContainHeapPointers,
       GCConfig::MarkingType::kAtomic, GCConfig::SweepingType::kAtomic});
  {
    subtle::NoGarbageCollectionScope no_gc(*this);
    sweeper_.FinishIfRunning();
  }
}
References FinalizeIncrementalGarbageCollectionIfRunning(), cppgc::internal::Sweeper::FinishIfRunning(), cppgc::Heap::kAtomic, cppgc::internal::kMajor, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and cppgc::internal::HeapBase::sweeper_.
Member Function Documentation
AsBase() [1/2]
HeapBase& cppgc::internal::Heap::AsBase () [inline]
Definition at line 34 of file heap.h.
{ return *this; }
Referenced by StartGarbageCollection().
AsBase() [2/2]
const HeapBase& cppgc::internal::Heap::AsBase () const [inline]
Definition at line 35 of file heap.h.
{ return *this; }
clear_overridden_stack_state()
void cppgc::internal::Heap::clear_overridden_stack_state () [inline], [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 50 of file heap.h.
{ override_stack_state_.reset(); }
CollectGarbage()
void cppgc::internal::Heap::CollectGarbage (GCConfig config) [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 104 of file heap.cc.
                                         {
  DCHECK_EQ(GCConfig::MarkingType::kAtomic, config.marking_type);
  CheckConfig(config, marking_support_, sweeping_support_);
  if (!IsGCAllowed()) {
    return;
  }
  config_ = config;
  if (!IsMarking()) {
    StartGarbageCollection(config);
  }
  DCHECK(IsMarking());
  FinalizeGarbageCollection(config.stack_state);
}
References cppgc::internal::anonymous_namespace{heap.cc}::CheckConfig(), config_, DCHECK, DCHECK_EQ, FinalizeGarbageCollection(), cppgc::internal::HeapBase::IsGCAllowed(), cppgc::internal::HeapBase::IsMarking(), cppgc::Heap::kAtomic, cppgc::internal::HeapBase::marking_support_, cppgc::internal::GCConfig::marking_type, cppgc::internal::GCConfig::stack_state, StartGarbageCollection(), and cppgc::internal::HeapBase::sweeping_support_.
Referenced by cppgc::Heap::ForceGarbageCollectionSlow().
DisableHeapGrowingForTesting()
void cppgc::internal::Heap::DisableHeapGrowingForTesting ()
Definition at line 230 of file heap.cc.
{ growing_.DisableForTesting(); }
References cppgc::internal::HeapGrowing::DisableForTesting(), and growing_.
EnableGenerationalGC()
void cppgc::internal::Heap::EnableGenerationalGC ()
Definition at line 224 of file heap.cc.
                                {
  DCHECK(!IsMarking());
  DCHECK(!generational_gc_enabled_);
  generational_gc_enabled_ = true;
}
References DCHECK, generational_gc_enabled_, and cppgc::internal::HeapBase::IsMarking().
epoch()
size_t cppgc::internal::Heap::epoch () const [inline], [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 41 of file heap.h.
{ return epoch_; }
FinalizeGarbageCollection()
void cppgc::internal::Heap::FinalizeGarbageCollection (StackState stack_state) [private]
Definition at line 170 of file heap.cc.
                                                           {
  stack()->SetMarkerIfNeededAndCallback(
      [this, stack_state]() { FinalizeGarbageCollectionImpl(stack_state); });
}
References FinalizeGarbageCollectionImpl(), heap::base::Stack::SetMarkerIfNeededAndCallback(), and cppgc::internal::HeapBase::stack().
Referenced by CollectGarbage(), FinalizeIncrementalGarbageCollectionForTesting(), FinalizeIncrementalGarbageCollectionIfNeeded(), and FinalizeIncrementalGarbageCollectionIfRunning().
FinalizeGarbageCollectionImpl()
void cppgc::internal::Heap::FinalizeGarbageCollectionImpl (StackState stack_state) [private]
Definition at line 175 of file heap.cc.
                                                               {
  DCHECK(IsMarking());
  DCHECK(!in_no_gc_scope());
  CHECK(!IsGCForbidden());
  config_.stack_state = stack_state;
  in_atomic_pause_ = true;
#if defined(CPPGC_YOUNG_GENERATION)
  // Check if the young generation was enabled. We must enable young generation
  // before calling the custom weak callbacks to make sure that the callbacks
  // for old objects are registered in the remembered set.
  if (generational_gc_enabled_) {
    HeapBase::EnableGenerationalGC();
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  {
    // This guards atomic pause marking, meaning that no internal method or
    // external callbacks are allowed to allocate new objects.
    cppgc::subtle::DisallowGarbageCollectionScope no_gc_scope(*this);
    marker_->FinishMarking(config_.stack_state);
  }
  marker_.reset();
  const size_t bytes_allocated_in_prefinalizers = ExecutePreFinalizers();
#if CPPGC_VERIFY_HEAP
  MarkingVerifier verifier(*this, config_.collection_type);
  verifier.Run(config_.stack_state,
               stats_collector()->marked_bytes_on_current_cycle() +
                   bytes_allocated_in_prefinalizers);
#endif // CPPGC_VERIFY_HEAP
#ifndef CPPGC_ALLOW_ALLOCATIONS_IN_PREFINALIZERS
  DCHECK_EQ(0u, bytes_allocated_in_prefinalizers);
#endif
  USE(bytes_allocated_in_prefinalizers);
#if defined(CPPGC_YOUNG_GENERATION)
  ResetRememberedSet();
#endif // defined(CPPGC_YOUNG_GENERATION)
  subtle::NoGarbageCollectionScope no_gc(*this);
  const SweepingConfig sweeping_config{
      config_.sweeping_type, SweepingConfig::CompactableSpaceHandling::kSweep,
      config_.free_memory_handling};
  sweeper_.Start(sweeping_config);
  if (config_.sweeping_type == SweepingConfig::SweepingType::kAtomic) {
    sweeper_.FinishIfRunning();
  }
  in_atomic_pause_ = false;
}
References CHECK, cppgc::internal::GCConfig::collection_type, config_, DCHECK, DCHECK_EQ, cppgc::internal::HeapBase::ExecutePreFinalizers(), cppgc::internal::Sweeper::FinishIfRunning(), cppgc::internal::GCConfig::free_memory_handling, generational_gc_enabled_, cppgc::internal::HeapBase::in_atomic_pause_, cppgc::internal::HeapBase::in_no_gc_scope(), cppgc::internal::HeapBase::IsGCForbidden(), cppgc::internal::HeapBase::IsMarking(), cppgc::Heap::kAtomic, cppgc::internal::SweepingConfig::kSweep, cppgc::internal::HeapBase::marker_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, cppgc::internal::MarkingVerifierBase::Run(), cppgc::internal::GCConfig::stack_state, cppgc::internal::Sweeper::Start(), cppgc::internal::HeapBase::stats_collector(), cppgc::internal::HeapBase::sweeper_, cppgc::internal::GCConfig::sweeping_type, and USE.
Referenced by FinalizeGarbageCollection().
FinalizeIncrementalGarbageCollectionForTesting()
void cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionForTesting (EmbedderStackState stack_state) [final], [private], [virtual]
Implements cppgc::internal::HeapBase.
Definition at line 247 of file heap.cc.
                                    {
  DCHECK(!in_no_gc_scope());
  DCHECK(IsMarking());
  FinalizeGarbageCollection(stack_state);
  sweeper_.FinishIfRunning();
}
References DCHECK, FinalizeGarbageCollection(), cppgc::internal::Sweeper::FinishIfRunning(), cppgc::internal::HeapBase::in_no_gc_scope(), cppgc::internal::HeapBase::IsMarking(), and cppgc::internal::HeapBase::sweeper_.
FinalizeIncrementalGarbageCollectionIfNeeded()
void cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionIfNeeded (StackState stack_state) [final], [private], [virtual]
Implements cppgc::internal::HeapBase.
Definition at line 232 of file heap.cc.
                            {
  StatsCollector::EnabledScope stats_scope(
      stats_collector(), StatsCollector::kMarkIncrementalFinalize);
  FinalizeGarbageCollection(stack_state);
}
References FinalizeGarbageCollection(), and cppgc::internal::HeapBase::stats_collector().
FinalizeIncrementalGarbageCollectionIfRunning()
void cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionIfRunning (GCConfig config)
Definition at line 133 of file heap.cc.
                                                                        {
  CheckConfig(config, marking_support_, sweeping_support_);
  if (!IsMarking()) return;
  DCHECK(!in_no_gc_scope());
  DCHECK_NE(GCConfig::MarkingType::kAtomic, config_.marking_type);
  config_ = config;
  FinalizeGarbageCollection(config.stack_state);
}
References cppgc::internal::anonymous_namespace{heap.cc}::CheckConfig(), config_, DCHECK, DCHECK_NE, FinalizeGarbageCollection(), cppgc::internal::HeapBase::in_no_gc_scope(), cppgc::internal::HeapBase::IsMarking(), cppgc::Heap::kAtomic, cppgc::internal::HeapBase::marking_support_, cppgc::internal::GCConfig::marking_type, cppgc::internal::GCConfig::stack_state, and cppgc::internal::HeapBase::sweeping_support_.
Referenced by ~Heap().
From() [1/2]
static const Heap* cppgc::internal::Heap::From (const cppgc::Heap * heap) [inline], [static]
Definition at line 26 of file heap.h.
                                                 {
    return static_cast<const Heap*>(heap);
  }
References heap().
From() [2/2]
static Heap* cppgc::internal::Heap::From (cppgc::Heap * heap) [inline], [static]
Definition at line 25 of file heap.h.
{ return static_cast<Heap*>(heap); }
References heap().
Referenced by cppgc::Heap::ForceGarbageCollectionSlow(), cppgc::Heap::GetAllocationHandle(), and cppgc::Heap::GetHeapHandle().
overridden_stack_state()
std::optional<EmbedderStackState> cppgc::internal::Heap::overridden_stack_state () const [inline], [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 43 of file heap.h.
                                                                       {
    return override_stack_state_;
  }
set_override_stack_state()
void cppgc::internal::Heap::set_override_stack_state (EmbedderStackState state) [inline], [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 46 of file heap.h.
                                                                {
    CHECK(!override_stack_state_);
    override_stack_state_ = state;
  }
References CHECK.
StartGarbageCollection()
void cppgc::internal::Heap::StartGarbageCollection (GCConfig config) [private]
Definition at line 145 of file heap.cc.
                                                 {
  DCHECK(!IsMarking());
  DCHECK(!in_no_gc_scope());
  // Finish sweeping in case it is still running.
  sweeper_.FinishIfRunning();
  epoch_++;
#if defined(CPPGC_YOUNG_GENERATION)
  if (config.collection_type == CollectionType::kMajor &&
      generational_gc_supported()) {
    stats_collector()->NotifyUnmarkingStarted(config.collection_type);
    cppgc::internal::StatsCollector::EnabledScope stats_scope(
        stats_collector(), cppgc::internal::StatsCollector::kUnmark);
    SequentialUnmarker unmarker(raw_heap());
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  const MarkingConfig marking_config{config.collection_type, config.stack_state,
                                     config.marking_type, config.is_forced_gc};
  marker_ = std::make_unique<Marker>(AsBase(), platform_.get(), marking_config);
  marker_->StartMarking();
}
References AsBase(), cppgc::internal::GCConfig::collection_type, DCHECK, epoch_, cppgc::internal::Sweeper::FinishIfRunning(), cppgc::internal::HeapBase::generational_gc_supported(), cppgc::internal::HeapBase::in_no_gc_scope(), cppgc::internal::GCConfig::is_forced_gc, cppgc::internal::HeapBase::IsMarking(), cppgc::internal::kMajor, cppgc::internal::HeapBase::marker_, cppgc::internal::GCConfig::marking_type, cppgc::internal::StatsCollector::NotifyUnmarkingStarted(), cppgc::internal::HeapBase::platform_, cppgc::internal::HeapBase::raw_heap(), cppgc::internal::GCConfig::stack_state, cppgc::internal::HeapBase::stats_collector(), and cppgc::internal::HeapBase::sweeper_.
Referenced by CollectGarbage(), StartIncrementalGarbageCollection(), and StartIncrementalGarbageCollectionForTesting().
StartIncrementalGarbageCollection()
void cppgc::internal::Heap::StartIncrementalGarbageCollection (GCConfig config) [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 121 of file heap.cc.
                                                            {
  DCHECK_NE(GCConfig::MarkingType::kAtomic, config.marking_type);
  DCHECK_NE(marking_support_, GCConfig::MarkingType::kAtomic);
  CheckConfig(config, marking_support_, sweeping_support_);
  if (IsMarking() || in_no_gc_scope()) return;
  config_ = config;
  StartGarbageCollection(config);
}
References cppgc::internal::anonymous_namespace{heap.cc}::CheckConfig(), config_, DCHECK_NE, cppgc::internal::HeapBase::in_no_gc_scope(), cppgc::internal::HeapBase::IsMarking(), cppgc::Heap::kAtomic, cppgc::internal::HeapBase::marking_support_, cppgc::internal::GCConfig::marking_type, StartGarbageCollection(), and cppgc::internal::HeapBase::sweeping_support_.
StartIncrementalGarbageCollectionForTesting()
void cppgc::internal::Heap::StartIncrementalGarbageCollectionForTesting () [final], [private], [virtual]
Implements cppgc::internal::HeapBase.
Definition at line 239 of file heap.cc.
                                                       {
  DCHECK(!IsMarking());
  DCHECK(!in_no_gc_scope());
  StartGarbageCollection({CollectionType::kMajor, StackState::kNoHeapPointers,
                          GCConfig::MarkingType::kIncrementalAndConcurrent,
                          GCConfig::SweepingType::kIncrementalAndConcurrent});
}
References DCHECK, cppgc::internal::HeapBase::in_no_gc_scope(), cppgc::internal::HeapBase::IsMarking(), cppgc::Heap::kIncrementalAndConcurrent, cppgc::internal::kMajor, and StartGarbageCollection().
Member Data Documentation
config_
GCConfig cppgc::internal::Heap::config_ [private]
Definition at line 70 of file heap.h.
Referenced by CollectGarbage(), FinalizeGarbageCollectionImpl(), FinalizeIncrementalGarbageCollectionIfRunning(), and StartIncrementalGarbageCollection().
epoch_
size_t cppgc::internal::Heap::epoch_ = 0 [private]
Definition at line 75 of file heap.h.
Referenced by StartGarbageCollection().
gc_invoker_
GCInvoker cppgc::internal::Heap::gc_invoker_ [private]
Definition at line 71 of file heap.h.
generational_gc_enabled_
bool cppgc::internal::Heap::generational_gc_enabled_ = false [private]
Definition at line 73 of file heap.h.
Referenced by EnableGenerationalGC(), and FinalizeGarbageCollectionImpl().
growing_
HeapGrowing cppgc::internal::Heap::growing_ [private]
Definition at line 72 of file heap.h.
Referenced by DisableHeapGrowingForTesting().
override_stack_state_
std::optional<cppgc::EmbedderStackState> cppgc::internal::Heap::override_stack_state_ [private]
Definition at line 77 of file heap.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap.h
/mnt/V8SourceCode/src/heap/cppgc/heap.cc