v8::SharedArrayBuffer Class Reference
An instance of the built-in SharedArrayBuffer constructor.
#include <v8-array-buffer.h>
Public Member Functions
size_t ByteLength () const
Data length in bytes.
size_t MaxByteLength () const
Maximum length in bytes.
std::shared_ptr< BackingStore > GetBackingStore ()
Get a shared pointer to the backing store of this array buffer.
void * Data () const
More efficient shortcut for GetBackingStore()->Data().
Static Public Member Functions
static Local< SharedArrayBuffer > New (Isolate *isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode=BackingStoreInitializationMode::kZeroInitialized)
Create a new SharedArrayBuffer.
static MaybeLocal< SharedArrayBuffer > MaybeNew (Isolate *isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode=BackingStoreInitializationMode::kZeroInitialized)
Create a new SharedArrayBuffer.
static Local< SharedArrayBuffer > New (Isolate *isolate, std::shared_ptr< BackingStore > backing_store)
Create a new SharedArrayBuffer with an existing backing store.
static std::unique_ptr< BackingStore > NewBackingStore (Isolate *isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode=BackingStoreInitializationMode::kZeroInitialized, BackingStoreOnFailureMode on_failure=BackingStoreOnFailureMode::kOutOfMemory)
Returns a new standalone BackingStore that is allocated using the array buffer allocator of the isolate.
static std::unique_ptr< BackingStore > NewBackingStore (void *data, size_t byte_length, v8::BackingStore::DeleterCallback deleter, void *deleter_data)
Returns a new standalone BackingStore that takes over the ownership of the given buffer.
static SharedArrayBuffer * Cast (Value *value)
Static Public Attributes
static constexpr int kInternalFieldCount
Private Member Functions
SharedArrayBuffer ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of the built-in SharedArrayBuffer constructor.
Definition at line 499 of file v8-array-buffer.h.
Constructor & Destructor Documentation
SharedArrayBuffer()
v8::SharedArrayBuffer::SharedArrayBuffer () [private]
Member Function Documentation
ByteLength()
size_t v8::SharedArrayBuffer::ByteLength () const
Data length in bytes.
Definition at line 9351 of file api.cc.
                                             {
  return Utils::OpenDirectHandle(this)->GetByteLength();
}
References v8::Utils::OpenDirectHandle().
Cast()
static SharedArrayBuffer* v8::SharedArrayBuffer::Cast (Value * value) [inline], [static]
Definition at line 598 of file v8-array-buffer.h.
                                                         {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<SharedArrayBuffer*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::SharedArrayBuffer::CheckCast (Value * obj) [static], [private]
Definition at line 4123 of file api.cc.
                                               {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(
      IsJSArrayBuffer(obj) && i::Cast<i::JSArrayBuffer>(obj)->is_shared(),
      "v8::SharedArrayBuffer::Cast()", "Value is not a SharedArrayBuffer");
}
References v8::Utils::ApiCheck(), v8::internal::is_shared, and v8::Utils::OpenDirectHandle().
Data()
void * v8::SharedArrayBuffer::Data () const
More efficient shortcut for GetBackingStore()->Data().
The returned pointer is valid as long as the ArrayBuffer is alive.
Definition at line 4072 of file api.cc.
                                      {
  return Utils::OpenDirectHandle(this)->backing_store();
}
References v8::Utils::OpenDirectHandle().
GetBackingStore()
std::shared_ptr< v8::BackingStore > v8::SharedArrayBuffer::GetBackingStore ()
Get a shared pointer to the backing store of this array buffer.
This pointer coordinates the lifetime management of the internal storage with any live ArrayBuffers on the heap, even across isolates. The embedder should not attempt to manage lifetime of the storage through other means.
Definition at line 4062 of file api.cc.
                                                                   {
  auto self = Utils::OpenDirectHandle(this);
  std::shared_ptr<i::BackingStore> backing_store = self->GetBackingStore();
  if (!backing_store) {
    backing_store = i::BackingStore::EmptyBackingStore(i::SharedFlag::kShared);
  }
  std::shared_ptr<i::BackingStoreBase> bs_base = backing_store;
  return std::static_pointer_cast<v8::BackingStore>(bs_base);
}
References v8::internal::BackingStore::EmptyBackingStore(), v8::internal::kShared, and v8::Utils::OpenDirectHandle().
MaxByteLength()
size_t v8::SharedArrayBuffer::MaxByteLength () const
Maximum length in bytes.
Definition at line 9355 of file api.cc.
                                                {
  return Utils::OpenDirectHandle(this)->max_byte_length();
}
References v8::Utils::OpenDirectHandle().
MaybeNew()
MaybeLocal< SharedArrayBuffer > v8::SharedArrayBuffer::MaybeNew (Isolate * isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode = BackingStoreInitializationMode::kZeroInitialized) [static]
Create a new SharedArrayBuffer.
Allocate |byte_length| bytes, which are either zero-initialized or uninitialized. Allocated memory will be owned by a created SharedArrayBuffer and will be deallocated when it is garbage-collected, unless the object is externalized. If allocation fails, the Maybe returned will be empty.
Definition at line 9380 of file api.cc.
                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_SharedArrayBuffer_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  std::unique_ptr<i::BackingStore> backing_store =
      i::BackingStore::Allocate(i_isolate, byte_length, i::SharedFlag::kShared,
                                GetInitializedFlag(initialization_mode));
  if (!backing_store) return {};
  i::DirectHandle<i::JSArrayBuffer> obj =
      i_isolate->factory()->NewJSSharedArrayBuffer(std::move(backing_store));
  return Utils::ToLocalShared(obj);
}
References v8::internal::BackingStore::Allocate(), v8::internal::Isolate::factory(), v8::anonymous_namespace{api.cc}::GetInitializedFlag(), v8::internal::kShared, and v8::internal::Factory::NewJSSharedArrayBuffer().
New() [1/2]
Local< SharedArrayBuffer > v8::SharedArrayBuffer::New (Isolate * isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode = BackingStoreInitializationMode::kZeroInitialized) [static]
Create a new SharedArrayBuffer.
Allocate |byte_length| bytes, which are either zero-initialized or uninitialized. Allocated memory will be owned by a created SharedArrayBuffer and will be deallocated when it is garbage-collected, unless the object is externalized.
Definition at line 9359 of file api.cc.
                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_SharedArrayBuffer_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  std::unique_ptr<i::BackingStore> backing_store =
      i::BackingStore::Allocate(i_isolate, byte_length, i::SharedFlag::kShared,
                                GetInitializedFlag(initialization_mode));
  if (!backing_store) {
    i::V8::FatalProcessOutOfMemory(i_isolate, "v8::SharedArrayBuffer::New");
  }
  i::DirectHandle<i::JSArrayBuffer> obj =
      i_isolate->factory()->NewJSSharedArrayBuffer(std::move(backing_store));
  return Utils::ToLocalShared(obj);
}
References v8::internal::BackingStore::Allocate(), v8::internal::Isolate::factory(), v8::internal::V8::FatalProcessOutOfMemory(), v8::anonymous_namespace{api.cc}::GetInitializedFlag(), v8::internal::kShared, and v8::internal::Factory::NewJSSharedArrayBuffer().
Referenced by v8::Deserializer::GetSharedArrayBufferFromId().
New() [2/2]
Local< SharedArrayBuffer > v8::SharedArrayBuffer::New (Isolate * isolate, std::shared_ptr< BackingStore > backing_store) [static]
Create a new SharedArrayBuffer with an existing backing store.
The created array keeps a reference to the backing store until the array is garbage collected. Note that the IsExternal bit does not affect this reference from the array to the backing store.
In future IsExternal bit will be removed. Until then the bit is set as follows. If the backing store does not own the underlying buffer, then the array is created in externalized state. Otherwise, the array is created in internalized state. In the latter case the array can be transitioned to the externalized state using Externalize(backing_store).
Definition at line 9399 of file api.cc.
                                                                    {
  CHECK_IMPLIES(backing_store->ByteLength() != 0,
                backing_store->Data() != nullptr);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_SharedArrayBuffer_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  std::shared_ptr<i::BackingStore> i_backing_store(ToInternal(backing_store));
  Utils::ApiCheck(
      i_backing_store->is_shared(), "v8::SharedArrayBuffer::New",
      "Cannot construct SharedArrayBuffer with BackingStore of ArrayBuffer");
  i::DirectHandle<i::JSArrayBuffer> obj =
      i_isolate->factory()->NewJSSharedArrayBuffer(std::move(i_backing_store));
  return Utils::ToLocalShared(obj);
}
References v8::Utils::ApiCheck(), CHECK_IMPLIES, v8::internal::Isolate::factory(), v8::internal::Factory::NewJSSharedArrayBuffer(), and v8::ToInternal().
NewBackingStore() [1/2]
std::unique_ptr< v8::BackingStore > v8::SharedArrayBuffer::NewBackingStore (Isolate * isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode = BackingStoreInitializationMode::kZeroInitialized, BackingStoreOnFailureMode on_failure = BackingStoreOnFailureMode::kOutOfMemory) [static]
Returns a new standalone BackingStore that is allocated using the array buffer allocator of the isolate.
The allocation can either be zero initialized, or uninitialized. The result can be later passed to SharedArrayBuffer::New.
If the allocator returns nullptr, then the function may cause GCs in the given isolate and re-try the allocation.
If on_failure is kOutOfMemory and GCs do not help, then the function will crash with an out-of-memory error.
Otherwise, if on_failure is kReturnNull and GCs do not help (or the byte_length is so large that the allocation cannot succeed), then a null result is returned.
Definition at line 9416 of file api.cc.
                                          {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(
      i_isolate, RCCId::kAPI_SharedArrayBuffer_NewBackingStore);
  if (on_failure == BackingStoreOnFailureMode::kOutOfMemory) {
    Utils::ApiCheck(
        byte_length <= i::JSArrayBuffer::kMaxByteLength,
        "v8::SharedArrayBuffer::NewBackingStore",
        "Cannot construct SharedArrayBuffer, requested length is too big");
  } else {
    DCHECK(on_failure == BackingStoreOnFailureMode::kReturnNull);
    if (byte_length > i::JSArrayBuffer::kMaxByteLength) return {};
  }
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  std::unique_ptr<i::BackingStoreBase> backing_store =
      i::BackingStore::Allocate(i_isolate, byte_length, i::SharedFlag::kShared,
                                GetInitializedFlag(initialization_mode));
  if (!backing_store) {
    if (on_failure == BackingStoreOnFailureMode::kOutOfMemory) {
      i::V8::FatalProcessOutOfMemory(i_isolate,
                                     "v8::SharedArrayBuffer::NewBackingStore");
    } else {
      DCHECK(on_failure == BackingStoreOnFailureMode::kReturnNull);
      return {};
    }
  }
  return std::unique_ptr<v8::BackingStore>(
      static_cast<v8::BackingStore*>(backing_store.release()));
}
References v8::internal::BackingStore::Allocate(), v8::Utils::ApiCheck(), DCHECK, v8::internal::V8::FatalProcessOutOfMemory(), v8::anonymous_namespace{api.cc}::GetInitializedFlag(), v8::internal::JSArrayBuffer::kMaxByteLength, v8::kOutOfMemory, v8::kReturnNull, and v8::internal::kShared.
NewBackingStore() [2/2]
std::unique_ptr< v8::BackingStore > v8::SharedArrayBuffer::NewBackingStore (void * data, size_t byte_length, v8::BackingStore::DeleterCallback deleter, void * deleter_data) [static]
Returns a new standalone BackingStore that takes over the ownership of the given buffer.
The destructor of the BackingStore invokes the given deleter callback.
The result can be later passed to SharedArrayBuffer::New. The raw pointer to the buffer must not be passed again to any V8 functions.
Definition at line 9449 of file api.cc.
                        {
  CHECK_LE(byte_length, i::JSArrayBuffer::kMaxByteLength);
  std::unique_ptr<i::BackingStoreBase> backing_store =
      i::BackingStore::WrapAllocation(data, byte_length, deleter, deleter_data,
                                      i::SharedFlag::kShared);
  return std::unique_ptr<v8::BackingStore>(
      static_cast<v8::BackingStore*>(backing_store.release()));
}
References CHECK_LE, v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::kShared, and v8::internal::BackingStore::WrapAllocation().
Member Data Documentation
kInternalFieldCount
constexpr int v8::SharedArrayBuffer::kInternalFieldCount [static], [constexpr]
Initial value:
=
      V8_ARRAY_BUFFER_INTERNAL_FIELD_COUNT
Definition at line 605 of file v8-array-buffer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-array-buffer.h
/mnt/V8SourceCode/src/api/api.cc