v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0 Class Reference
Public Types
using TryFunction = VoidGenerator0
using CatchFunction = std::function< void(TNode< Object >)>
Public Member Functions
TryCatchBuilder0 (JSCallReducerAssembler *gasm, const TryFunction &try_body)
void Catch (const CatchFunction &catch_body)
Private Attributes
JSCallReducerAssembler *const gasm_
const VoidGenerator0 try_body_
Detailed Description
Definition at line 189 of file js-call-reducer.cc.
Member Typedef Documentation
CatchFunction
using v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::CatchFunction = std::function<void(TNode<Object>)>
Definition at line 192 of file js-call-reducer.cc.
TryFunction
using v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::TryFunction = VoidGenerator0
Definition at line 191 of file js-call-reducer.cc.
Constructor & Destructor Documentation
TryCatchBuilder0()
v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::TryCatchBuilder0 (JSCallReducerAssembler * gasm, const TryFunction & try_body) [inline]
Definition at line 194 of file js-call-reducer.cc.
        : gasm_(gasm), try_body_(try_body) {}
Member Function Documentation
Catch()
void v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch (const CatchFunction & catch_body) [inline]
Definition at line 197 of file js-call-reducer.cc.
                                                {
      TNode<Object> handler_exception;
      Effect handler_effect{nullptr};
      Control handler_control{nullptr};
      auto continuation = gasm_->MakeLabel();
      // Try.
      {
        CatchScope catch_scope = CatchScope::Inner(gasm_->temp_zone(), gasm_);
        try_body_();
        gasm_->Goto(&continuation);
        catch_scope.MergeExceptionalPaths(&handler_exception, &handler_effect,
                                          &handler_control);
      }
      // Catch.
      {
        gasm_->InitializeEffectControl(handler_effect, handler_control);
        catch_body(handler_exception);
        gasm_->Goto(&continuation);
      }
      gasm_->Bind(&continuation);
    }
References v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::JSGraphAssembler::catch_scope(), gasm_, v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::JSGraphAssembler::CatchScope::Inner(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::JSGraphAssembler::CatchScope::MergeExceptionalPaths(), v8::internal::compiler::GraphAssembler::temp_zone(), and try_body_.
Member Data Documentation
gasm_
JSCallReducerAssembler* const v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::gasm_ [private]
Definition at line 225 of file js-call-reducer.cc.
Referenced by Catch().
try_body_
const VoidGenerator0 v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::try_body_ [private]
Definition at line 226 of file js-call-reducer.cc.
Referenced by Catch().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc