v8::internal::wasm::InstanceBuilder Class Reference
Public Member Functions
InstanceBuilder (Isolate *isolate, v8::metrics::Recorder::ContextId context_id, ErrorThrower *thrower, DirectHandle< WasmModuleObject > module_object, MaybeDirectHandle< JSReceiver > ffi, MaybeDirectHandle< JSArrayBuffer > memory_buffer)
MaybeDirectHandle< WasmInstanceObject > Build ()
bool ExecuteStartFunction ()
bool ConfigurePrototypes_Modular ()
void FinalizeExportsObject (MaybeDirectHandle< WasmInstanceObject > instance)
Private Member Functions
DirectHandle< WasmTrustedInstanceData > trusted_data (bool shared) const
std::string ImportName (uint32_t index)
std::string ImportName (uint32_t index, DirectHandle< String > module_name)
MaybeDirectHandle< Object > LookupImport (uint32_t index, DirectHandle< String > module_name, DirectHandle< String > import_name)
MaybeDirectHandle< Object > LookupImportAsm (uint32_t index, DirectHandle< String > import_name)
void LoadDataSegments ()
void WriteGlobalValue (const WasmGlobal &global, const WasmValue &value)
void SanitizeImports ()
Maybe< bool > Build_Phase1 (const DisallowJavascriptExecution &no_js)
void Build_Phase1_Infallible ()
Maybe< bool > Build_Phase2 ()
MaybeDirectHandle< WasmMemoryObject > AllocateMemory (uint32_t memory_index)
bool ProcessImportedFunction (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int import_index, int func_index, DirectHandle< Object > value, WellKnownImport preknown_import)
bool ProcessImportedTable (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int import_index, int table_index, DirectHandle< Object > value)
bool ProcessImportedGlobal (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int import_index, int global_index, DirectHandle< Object > value)
bool ProcessImportedWasmGlobalObject (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int import_index, const WasmGlobal &global, DirectHandle< WasmGlobalObject > global_object)
int ProcessImports ()
bool ProcessImportedMemories (DirectHandle< FixedArray > imported_memory_objects)
template<typename T >
T * GetRawUntaggedGlobalPtr (const WasmGlobal &global)
void InitGlobals ()
void ProcessExports ()
void SetTableInitialValues ()
void LoadTableSegments ()
void InitializeTags ()
Private Attributes
Isolate * isolate_
v8::metrics::Recorder::ContextId context_id_
const WasmEnabledFeatures enabled_
const WasmModule *const module_
ErrorThrower * thrower_
DirectHandle< WasmModuleObject > module_object_
DirectHandle< WasmTrustedInstanceData > trusted_data_
DirectHandle< WasmTrustedInstanceData > shared_trusted_data_
MaybeDirectHandle< JSReceiver > ffi_
MaybeDirectHandle< JSArrayBuffer > asmjs_memory_buffer_
DirectHandle< JSArrayBuffer > untagged_globals_
DirectHandle< JSArrayBuffer > shared_untagged_globals_
DirectHandle< FixedArray > tagged_globals_
DirectHandle< FixedArray > shared_tagged_globals_
DirectHandleVector< WasmTagObject > tags_wrappers_
DirectHandleVector< WasmTagObject > shared_tags_wrappers_
DirectHandle< JSFunction > start_function_
DirectHandleVector< Object > sanitized_imports_
std::vector< WellKnownImport > well_known_imports_
std::optional< JSPrototypesSetup > js_prototypes_setup_
Zone init_expr_zone_
Detailed Description
Definition at line 1208 of file module-instantiate.cc.
Constructor & Destructor Documentation
InstanceBuilder()
v8::internal::wasm::InstanceBuilder::InstanceBuilder (Isolate * isolate, v8::metrics::Recorder::ContextId context_id, ErrorThrower * thrower, DirectHandle< WasmModuleObject > module_object, MaybeDirectHandle< JSReceiver > ffi, MaybeDirectHandle< JSArrayBuffer > memory_buffer)
Definition at line 1431 of file module-instantiate.cc.
    : isolate_(isolate),
      context_id_(context_id),
      enabled_(module_object->native_module()->enabled_features()),
      module_(module_object->module()),
      thrower_(thrower),
      module_object_(module_object),
      ffi_(ffi),
      asmjs_memory_buffer_(asmjs_memory_buffer),
      tags_wrappers_(isolate),
      shared_tags_wrappers_(isolate),
      sanitized_imports_(isolate),
      init_expr_zone_(isolate_->allocator(), "constant expression zone") {
  sanitized_imports_.reserve(module_->import_table.size());
  well_known_imports_.reserve(module_->num_imported_functions);
}
References v8::internal::wasm::WasmModule::import_table, module_, v8::internal::wasm::WasmModule::num_imported_functions, sanitized_imports_, and well_known_imports_.
Member Function Documentation
AllocateMemory()
MaybeDirectHandle< WasmMemoryObject > v8::internal::wasm::InstanceBuilder::AllocateMemory (uint32_t memory_index) [private]
Definition at line 2871 of file module-instantiate.cc.
                           {
  const WasmMemory& memory = module_->memories[memory_index];
  int initial_pages = static_cast<int>(memory.initial_pages);
  int maximum_pages = memory.has_maximum_pages
                          ? static_cast<int>(memory.maximum_pages)
                          : WasmMemoryObject::kNoMaximum;
  auto shared = memory.is_shared ? SharedFlag::kShared : SharedFlag::kNotShared;
  MaybeDirectHandle<WasmMemoryObject> maybe_memory_object =
      WasmMemoryObject::New(isolate_, initial_pages, maximum_pages, shared,
                            memory.address_type);
  if (maybe_memory_object.is_null()) {
    thrower_->RangeError(
        "Out of memory: Cannot allocate Wasm memory for new instance");
    return {};
  }
  return maybe_memory_object;
}
References v8::internal::wasm::WasmMemory::address_type, v8::internal::wasm::WasmMemory::has_maximum_pages, v8::internal::wasm::WasmMemory::initial_pages, v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::wasm::WasmMemory::is_shared, isolate_, v8::internal::WasmMemoryObject::kNoMaximum, v8::internal::kNotShared, v8::internal::kShared, v8::internal::wasm::WasmMemory::maximum_pages, v8::internal::wasm::WasmModule::memories, module_, v8::internal::WasmMemoryObject::New(), and thrower_.
Referenced by Build_Phase1().
Build()
MaybeDirectHandle< WasmInstanceObject > v8::internal::wasm::InstanceBuilder::Build ()
Definition at line 1453 of file module-instantiate.cc.
                                                             {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.InstanceBuilder.Build");
  // Will check whether {ffi_} is available.
  SanitizeImports();
  if (thrower_->error()) return {};
  // From here on, we expect the build pipeline to run without exiting to JS.
  DisallowJavascriptExecution no_js(isolate_);
  // Start a timer for instantiation time, if we have a high resolution timer.
  base::ElapsedTimer timer;
  if (base::TimeTicks::IsHighResolution()) {
    timer.Start();
  }
  v8::metrics::WasmModuleInstantiated wasm_module_instantiated;
  // Phase 1: uses a {TrustedPointerPublishingScope} to make the new,
  // partially-initialized instance inaccessible in case of failure.
  if (Build_Phase1(no_js).IsNothing()) return {};
  // Phase 2: assumes that the new instance is already sufficiently
  // consistently initialized to be exposed to user code.
  if (Build_Phase2().IsNothing()) return {};
  wasm_module_instantiated.success = true;
  wasm_module_instantiated.imported_function_count =
      module_->num_imported_functions;
  if (timer.IsStarted()) {
    base::TimeDelta instantiation_time = timer.Elapsed();
    wasm_module_instantiated.wall_clock_duration_in_us =
        instantiation_time.InMicroseconds();
    SELECT_WASM_COUNTER(isolate_->counters(), module_->origin, wasm_instantiate,
                        module_time)
        ->AddTimedSample(instantiation_time);
    isolate_->metrics_recorder()->DelayMainThreadEvent(wasm_module_instantiated,
                                                       context_id_);
  }
  return direct_handle(trusted_data_->instance_object(), isolate_);
}
References Build_Phase1(), Build_Phase2(), context_id_, v8::internal::Isolate::counters(), v8::internal::direct_handle(), v8::base::ElapsedTimer::Elapsed(), v8::internal::wasm::ErrorThrower::error(), v8::metrics::WasmModuleInstantiated::imported_function_count, v8::base::TimeDelta::InMicroseconds(), v8::base::TimeTicks::IsHighResolution(), isolate_, v8::base::ElapsedTimer::IsStarted(), v8::internal::Isolate::metrics_recorder(), module_, v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::wasm::WasmModule::origin, SanitizeImports(), SELECT_WASM_COUNTER, v8::base::ElapsedTimer::Start(), v8::metrics::WasmModuleInstantiated::success, thrower_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, trusted_data_, and v8::metrics::WasmModuleInstantiated::wall_clock_duration_in_us.
Referenced by v8::internal::wasm::InstantiateToInstanceObject().
Build_Phase1()
Maybe< bool > v8::internal::wasm::InstanceBuilder::Build_Phase1 (const DisallowJavascriptExecution & no_js) [private]
Definition at line 1493 of file module-instantiate.cc.
                                              {
  // Any trusted pointers created here will be zapped unless instantiation
  // successfully runs to completion, to prevent trusted objects that violate
  // their own internal invariants because they're only partially-initialized
  // from becoming accessible to untrusted code.
  // We assume failure for now, and will update to success later.
  TrustedPointerPublishingScope publish_trusted_objects(isolate_, no_js);
  publish_trusted_objects.MarkFailure();
  NativeModule* native_module = module_object_->native_module();
  //--------------------------------------------------------------------------
  // Create the WebAssembly.Instance object.
  //--------------------------------------------------------------------------
  TRACE("New module instantiation for %p\n", native_module);
  trusted_data_ = WasmTrustedInstanceData::New(isolate_, module_object_, false);
  bool shared = module_object_->module()->has_shared_part;
  if (shared) {
    // For now, allocate the shared part in non-shared space. We do not need it
    // in shared space yet since no shared objects point to it.
    // TODO(42204563): This will change once we introduce shared globals,
    // tables, or functions.
    shared_trusted_data_ =
        WasmTrustedInstanceData::New(isolate_, module_object_, false);
    trusted_data_->set_shared_part(*shared_trusted_data_);
  }
  //--------------------------------------------------------------------------
  // Set up the memory buffers and memory objects and attach them to the
  // instance.
  //--------------------------------------------------------------------------
  if (is_asmjs_module(module_)) {
    CHECK_EQ(1, module_->memories.size());
    DirectHandle<JSArrayBuffer> buffer;
    if (!asmjs_memory_buffer_.ToHandle(&buffer)) {
      // Use an empty JSArrayBuffer for degenerate asm.js modules.
      MaybeDirectHandle<JSArrayBuffer> new_buffer =
          isolate_->factory()->NewJSArrayBufferAndBackingStore(
              0, InitializedFlag::kUninitialized);
      if (!new_buffer.ToHandle(&buffer)) {
        thrower_->RangeError("Out of memory: asm.js memory");
        return {};
      }
      buffer->set_is_detachable(false);
    }
    // asm.js instantiation should have changed the state of the buffer (or we
    // set it above).
    CHECK(!buffer->is_detachable());
    // The maximum number of pages isn't strictly necessary for memory
    // objects used for asm.js, as they are never visible, but we might
    // as well make it accurate.
    auto maximum_pages =
        static_cast<int>(RoundUp(buffer->byte_length(), wasm::kWasmPageSize) /
                         wasm::kWasmPageSize);
    DirectHandle<WasmMemoryObject> memory_object = WasmMemoryObject::New(
        isolate_, buffer, maximum_pages, AddressType::kI32);
    constexpr int kMemoryIndexZero = 0;
    trusted_data_->memory_objects()->set(kMemoryIndexZero, *memory_object);
  } else {
    CHECK(asmjs_memory_buffer_.is_null());
    DirectHandle<FixedArray> memory_objects{trusted_data_->memory_objects(),
                                            isolate_};
    // First process all imported memories, then allocate non-imported ones.
    if (!ProcessImportedMemories(memory_objects)) {
      return {};
    }
    // Actual Wasm modules can have multiple memories.
    static_assert(kV8MaxWasmMemories <= kMaxUInt32);
    uint32_t num_memories = static_cast<uint32_t>(module_->memories.size());
    for (uint32_t memory_index = 0; memory_index < num_memories;
         ++memory_index) {
      if (!IsUndefined(memory_objects->get(memory_index))) continue;
      DirectHandle<WasmMemoryObject> memory_object;
      if (AllocateMemory(memory_index).ToHandle(&memory_object)) {
        memory_objects->set(memory_index, *memory_object);
      } else {
        DCHECK(isolate_->has_exception() || thrower_->error());
        return {};
      }
    }
  }
  //--------------------------------------------------------------------------
  // Set up the globals for the new instance.
  //--------------------------------------------------------------------------
  uint32_t untagged_globals_buffer_size = module_->untagged_globals_buffer_size;
  if (untagged_globals_buffer_size > 0) {
    MaybeDirectHandle<JSArrayBuffer> result =
        isolate_->factory()->NewJSArrayBufferAndBackingStore(
            untagged_globals_buffer_size, InitializedFlag::kZeroInitialized,
            AllocationType::kOld);
    if (!result.ToHandle(&untagged_globals_)) {
      thrower_->RangeError("Out of memory: wasm globals");
      return {};
    }
    trusted_data_->set_untagged_globals_buffer(*untagged_globals_);
    trusted_data_->set_globals_start(
        reinterpret_cast<uint8_t*>(untagged_globals_->backing_store()));
    // TODO(42204563): Do this only if we have a shared untagged global.
    // TODO(42204563): Reinstate once we support shared globals.
    /* if (shared) {
      MaybeDirectHandle<JSArrayBuffer> shared_result =
          isolate_->factory()->NewJSArrayBufferAndBackingStore(
              untagged_globals_buffer_size, InitializedFlag::kZeroInitialized,
              AllocationType::kSharedOld);
      if (!shared_result.ToHandle(&shared_untagged_globals_)) {
        thrower_->RangeError("Out of memory: wasm globals");
        return {};
      }
      shared_trusted_data->set_untagged_globals_buffer(
          *shared_untagged_globals_);
      shared_trusted_data->set_globals_start(reinterpret_cast<uint8_t*>(
          shared_untagged_globals_->backing_store()));
    }*/
  }
  uint32_t tagged_globals_buffer_size = module_->tagged_globals_buffer_size;
  if (tagged_globals_buffer_size > 0) {
    tagged_globals_ = isolate_->factory()->NewFixedArray(
        static_cast<int>(tagged_globals_buffer_size));
    trusted_data_->set_tagged_globals_buffer(*tagged_globals_);
    if (shared) {
      shared_tagged_globals_ = isolate_->factory()->NewFixedArray(
          static_cast<int>(tagged_globals_buffer_size),
          AllocationType::kSharedOld);
      shared_trusted_data_->set_tagged_globals_buffer(*shared_tagged_globals_);
    }
  }
  //--------------------------------------------------------------------------
  // Set up the array of references to imported globals' array buffers.
  //--------------------------------------------------------------------------
  if (module_->num_imported_mutable_globals > 0) {
    // TODO(binji): This allocates one slot for each mutable global, which is
    // more than required if multiple globals are imported from the same
    // module.
    DirectHandle<FixedArray> buffers_array = isolate_->factory()->NewFixedArray(
        module_->num_imported_mutable_globals, AllocationType::kOld);
    trusted_data_->set_imported_mutable_globals_buffers(*buffers_array);
    if (shared) {
      DirectHandle<FixedArray> shared_buffers_array =
          isolate_->factory()->NewFixedArray(
              module_->num_imported_mutable_globals,
              AllocationType::kSharedOld);
      shared_trusted_data_->set_imported_mutable_globals_buffers(
          *shared_buffers_array);
    }
  }
  //--------------------------------------------------------------------------
  // Set up the tag table used for exception tag checks.
  //--------------------------------------------------------------------------
  int tags_count = static_cast<int>(module_->tags.size());
  if (tags_count > 0) {
    DirectHandle<FixedArray> tag_table =
        isolate_->factory()->NewFixedArray(tags_count, AllocationType::kOld);
    trusted_data_->set_tags_table(*tag_table);
    tags_wrappers_.resize(tags_count);
    if (shared) {
      DirectHandle<FixedArray> shared_tag_table =
          isolate_->factory()->NewFixedArray(tags_count,
                                             AllocationType::kSharedOld);
      shared_trusted_data_->set_tags_table(*shared_tag_table);
      shared_tags_wrappers_.resize(tags_count);
    }
  }
  //--------------------------------------------------------------------------
  // Set up table storage space, and initialize it for non-imported tables.
  //--------------------------------------------------------------------------
  int table_count = static_cast<int>(module_->tables.size());
  if (table_count == 0) {
    trusted_data_->set_tables(*isolate_->factory()->empty_fixed_array());
    if (shared) {
      shared_trusted_data_->set_tables(
          *isolate_->factory()->empty_fixed_array());
    }
  } else {
    DirectHandle<FixedArray> tables =
        isolate_->factory()->NewFixedArray(table_count);
    DirectHandle<ProtectedFixedArray> dispatch_tables =
        isolate_->factory()->NewProtectedFixedArray(table_count);
    trusted_data_->set_tables(*tables);
    trusted_data_->set_dispatch_tables(*dispatch_tables);
    DirectHandle<FixedArray> shared_tables;
    DirectHandle<ProtectedFixedArray> shared_dispatch_tables;
    if (shared) {
      shared_tables = isolate_->factory()->NewFixedArray(
          table_count, AllocationType::kSharedOld);
      shared_dispatch_tables =
          isolate_->factory()->NewProtectedFixedArray(table_count);
      shared_trusted_data_->set_tables(*shared_tables);
      shared_trusted_data_->set_dispatch_tables(*shared_dispatch_tables);
    }
    for (int i = module_->num_imported_tables; i < table_count; i++) {
      const WasmTable& table = module_->tables[i];
      CanonicalValueType canonical_type = module_->canonical_type(table.type);
      // Initialize tables with null for now. We will initialize non-defaultable
      // tables later, in {SetTableInitialValues}.
      DirectHandle<WasmDispatchTable> dispatch_table;
      DirectHandle<WasmTableObject> table_obj = WasmTableObject::New(
          isolate_, trusted_data(table.shared), table.type, canonical_type,
          table.initial_size, table.has_maximum_size, table.maximum_size,
          table.type.use_wasm_null()
              ? DirectHandle<HeapObject>{isolate_->factory()->wasm_null()}
              : DirectHandle<HeapObject>{isolate_->factory()->null_value()},
          table.address_type, &dispatch_table);
      (table.shared ? shared_tables : tables)->set(i, *table_obj);
      if (!dispatch_table.is_null()) {
        (table.shared ? shared_dispatch_tables : dispatch_tables)
            ->set(i, *dispatch_table);
        if (i == 0) {
          trusted_data(table.shared)->set_dispatch_table0(*dispatch_table);
        }
      }
    }
  }
  //--------------------------------------------------------------------------
  // Process the imports for the module.
  //--------------------------------------------------------------------------
  if (!module_->import_table.empty()) {
    int num_imported_functions = ProcessImports();
    if (num_imported_functions < 0) return {};
  }
  //--------------------------------------------------------------------------
  // Create maps for managed objects (GC proposal).
  // Must happen before {InitGlobals} because globals can refer to these maps.
  //--------------------------------------------------------------------------
  if (!module_->isorecursive_canonical_type_ids.empty()) {
    // Make sure all canonical indices have been set.
    DCHECK(module_->MaxCanonicalTypeIndex().valid());
    TypeCanonicalizer::PrepareForCanonicalTypeId(
        isolate_, module_->MaxCanonicalTypeIndex());
  }
  DirectHandle<FixedArray> non_shared_maps = isolate_->factory()->NewFixedArray(
      static_cast<int>(module_->types.size()));
  DirectHandle<FixedArray> shared_maps =
      shared ? isolate_->factory()->NewFixedArray(
                   static_cast<int>(module_->types.size()),
                   AllocationType::kSharedOld)
             : DirectHandle<FixedArray>();
  for (uint32_t index = 0; index < module_->types.size(); index++) {
    bool map_is_shared = module_->types[index].is_shared;
    CreateMapForType(isolate_, module_, ModuleTypeIndex{index},
                     map_is_shared ? shared_maps : non_shared_maps);
  }
  trusted_data_->set_managed_object_maps(*non_shared_maps);
  if (shared) shared_trusted_data_->set_managed_object_maps(*shared_maps);
#if DEBUG
  for (uint32_t i = 0; i < module_->types.size(); i++) {
    DirectHandle<FixedArray> maps =
        module_->types[i].is_shared ? shared_maps : non_shared_maps;
    Tagged<Object> o = maps->get(i);
    DCHECK(IsMap(o));
    Tagged<Map> map = Cast<Map>(o);
    ModuleTypeIndex index{i};
    if (module_->has_signature(index)) {
      DCHECK_EQ(map->instance_type(), WASM_FUNC_REF_TYPE);
    } else if (module_->has_array(index)) {
      DCHECK_EQ(map->instance_type(), WASM_ARRAY_TYPE);
    } else if (module_->has_struct(index)) {
      DCHECK_EQ(map->instance_type(), WASM_STRUCT_TYPE);
    }
  }
#endif
  //--------------------------------------------------------------------------
  // Allocate the array that will hold type feedback vectors.
  //--------------------------------------------------------------------------
  if (v8_flags.wasm_inlining) {
    int num_functions = static_cast<int>(module_->num_declared_functions);
    // Zero-fill the array so we can do a quick Smi-check to test if a given
    // slot was initialized.
    DirectHandle<FixedArray> vectors =
        isolate_->factory()->NewFixedArrayWithZeroes(num_functions,
                                                     AllocationType::kOld);
    trusted_data_->set_feedback_vectors(*vectors);
    if (shared) {
      DirectHandle<FixedArray> shared_vectors =
          isolate_->factory()->NewFixedArrayWithZeroes(
              num_functions, AllocationType::kSharedOld);
      shared_trusted_data_->set_feedback_vectors(*shared_vectors);
    }
  }
  //--------------------------------------------------------------------------
  // Process the initialization for the module's globals.
  //--------------------------------------------------------------------------
  InitGlobals();
  //--------------------------------------------------------------------------
  // Initialize non-defaultable tables.
  //--------------------------------------------------------------------------
  SetTableInitialValues();
  //--------------------------------------------------------------------------
  // Initialize the tags table.
  //--------------------------------------------------------------------------
  if (tags_count > 0) {
    InitializeTags();
  }
  //--------------------------------------------------------------------------
  // Set up the exports object for the new instance.
  //--------------------------------------------------------------------------
  ProcessExports();
  if (thrower_->error()) return {};
  //--------------------------------------------------------------------------
  // Set up uninitialized element segments.
  //--------------------------------------------------------------------------
  if (!module_->elem_segments.empty()) {
    DirectHandle<FixedArray> elements = isolate_->factory()->NewFixedArray(
        static_cast<int>(module_->elem_segments.size()));
    DirectHandle<FixedArray> shared_elements =
        shared ? isolate_->factory()->NewFixedArray(
                     static_cast<int>(module_->elem_segments.size()),
                     AllocationType::kSharedOld)
               : DirectHandle<FixedArray>();
    for (uint32_t i = 0; i < module_->elem_segments.size(); i++) {
      // Initialize declarative segments as empty. The rest remain
      // uninitialized.
      bool is_declarative = module_->elem_segments[i].status ==
                            WasmElemSegment::kStatusDeclarative;
      (module_->elem_segments[i].shared ? shared_elements : elements)
          ->set(i, is_declarative
                       ? Cast<Object>(*isolate_->factory()->empty_fixed_array())
                       : *isolate_->factory()->undefined_value());
    }
    trusted_data_->set_element_segments(*elements);
    if (shared) shared_trusted_data_->set_element_segments(*shared_elements);
  }
  //--------------------------------------------------------------------------
  // Create a wrapper for the start function.
  //--------------------------------------------------------------------------
  if (module_->start_function_index >= 0) {
    int start_index = module_->start_function_index;
    auto& function = module_->functions[start_index];
    DCHECK(start_function_.is_null());
    if (function.imported) {
      ImportedFunctionEntry entry(trusted_data_, module_->start_function_index);
      Tagged<Object> callable = entry.maybe_callable();
      if (IsJSFunction(callable)) {
        // If the start function was imported and calls into Blink, we have
        // to pretend that the V8 API was used to enter its correct context.
        // In order to simplify entering the context in {ExecuteStartFunction}
        // below, we just record the callable as the start function.
        start_function_ = direct_handle(Cast<JSFunction>(callable), isolate_);
      }
    }
    if (start_function_.is_null()) {
      // TODO(clemensb): Don't generate an exported function for the start
      // function. Use CWasmEntry instead.
      bool function_is_shared = module_->type(function.sig_index).is_shared;
      DirectHandle<WasmFuncRef> func_ref =
          WasmTrustedInstanceData::GetOrCreateFuncRef(
              isolate_, trusted_data(function_is_shared), start_index);
      DirectHandle<WasmInternalFunction> internal{func_ref->internal(isolate_),
                                                  isolate_};
      start_function_ = WasmInternalFunction::GetOrCreateExternal(internal);
    }
  }
  DCHECK(!isolate_->has_exception());
  TRACE("Successfully built instance for module %p\n",
        module_object_->native_module());
#if V8_ENABLE_DRUMBRAKE
  // Skip this event because not (yet) supported by Chromium.
  // v8::metrics::WasmInterpreterJitStatus jit_status;
  // jit_status.jitless = v8_flags.wasm_jitless;
  // isolate_->metrics_recorder()->DelayMainThreadEvent(jit_status,
  // context_id_);
#endif // V8_ENABLE_DRUMBRAKE
  publish_trusted_objects.MarkSuccess();
  Build_Phase1_Infallible();
  return Just(true);
}
References v8::internal::wasm::WasmTable::address_type, AllocateMemory(), asmjs_memory_buffer_, Build_Phase1_Infallible(), v8::internal::wasm::WasmModule::canonical_type(), CHECK, CHECK_EQ, v8::internal::wasm::CreateMapForType(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::wasm::WasmModule::elem_segments, v8::internal::wasm::ErrorThrower::error(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmModule::functions, v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::wasm::WasmModule::has_array(), v8::internal::Isolate::has_exception(), v8::internal::wasm::WasmTable::has_maximum_size, v8::internal::wasm::WasmModule::has_signature(), v8::internal::wasm::WasmModule::has_struct(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmModule::import_table, v8::internal::index, InitGlobals(), v8::internal::wasm::WasmTable::initial_size, InitializeTags(), v8::internal::wasm::is_asmjs_module(), v8::internal::DirectHandle< T >::is_null(), v8::internal::wasm::TypeDefinition::is_shared, isolate_, v8::internal::wasm::WasmModule::isorecursive_canonical_type_ids, v8::Just(), v8::internal::wasm::kI32, v8::internal::kMaxUInt32, v8::internal::kOld, v8::internal::kSharedOld, v8::internal::wasm::WasmElemSegment::kStatusDeclarative, v8::internal::kUninitialized, v8::internal::wasm::kV8MaxWasmMemories, v8::internal::wasm::kWasmPageSize, v8::internal::kZeroInitialized, v8::internal::TrustedPointerPublishingScope::MarkFailure(), v8::internal::TrustedPointerPublishingScope::MarkSuccess(), v8::internal::wasm::WasmModule::MaxCanonicalTypeIndex(), v8::internal::wasm::WasmTable::maximum_size, v8::internal::ImportedFunctionEntry::maybe_callable(), v8::internal::wasm::WasmModule::memories, v8::internal::memory_objects, module_, module_object_, v8::internal::WasmTrustedInstanceData::New(), v8::internal::WasmMemoryObject::New(), v8::internal::WasmTableObject::New(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewFixedArrayWithZeroes(), v8::internal::Factory::NewJSArrayBufferAndBackingStore(), v8::internal::FactoryBase< Impl >::NewProtectedFixedArray(), v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::num_imported_mutable_globals, v8::internal::wasm::WasmModule::num_imported_tables, v8::internal::wasm::TypeCanonicalizer::PrepareForCanonicalTypeId(), ProcessExports(), ProcessImportedMemories(), ProcessImports(), v8::base::internal::result, RoundUp(), SetTableInitialValues(), v8::internal::wasm::WasmTable::shared, shared_tagged_globals_, shared_tags_wrappers_, shared_trusted_data_, start_function_, v8::internal::wasm::WasmModule::start_function_index, v8::internal::wasm::WasmModule::tables, v8::internal::tables, tagged_globals_, v8::internal::wasm::WasmModule::tagged_globals_buffer_size, v8::internal::wasm::WasmModule::tags, tags_wrappers_, thrower_, v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::TRACE(), trusted_data(), trusted_data_, v8::internal::wasm::WasmTable::type, v8::internal::wasm::WasmModule::type(), v8::internal::wasm::WasmModule::types, untagged_globals_, v8::internal::wasm::WasmModule::untagged_globals_buffer_size, v8::internal::wasm::ValueTypeBase::use_wasm_null(), v8::internal::v8_flags, and v8::internal::wasm::TypeIndex::valid().
Referenced by Build().
Build_Phase1_Infallible()
void v8::internal::wasm::InstanceBuilder::Build_Phase1_Infallible () [private]
Definition at line 1884 of file module-instantiate.cc.
                                              {
  //--------------------------------------------------------------------------
  // Register with memories.
  //--------------------------------------------------------------------------
  size_t num_memories = module_->memories.size();
  DirectHandle<FixedArray> memory_objects{trusted_data_->memory_objects(),
                                          isolate_};
  for (uint32_t i = 0; i < num_memories; i++) {
    DirectHandle<WasmMemoryObject> memory{
        Cast<WasmMemoryObject>(memory_objects->get(i)), isolate_};
    WasmMemoryObject::UseInInstance(isolate_, memory, trusted_data_,
                                    shared_trusted_data_, i);
  }
  //--------------------------------------------------------------------------
  // Register with tables.
  //--------------------------------------------------------------------------
  size_t num_tables = module_->tables.size();
  for (uint32_t i = 0; i < num_tables; i++) {
    const WasmTable& table = module_->tables[i];
    DirectHandle<WasmTrustedInstanceData> data_part =
        trusted_data(table.shared);
    Tagged<Object> maybe_dispatch_table = data_part->dispatch_tables()->get(i);
    if (maybe_dispatch_table == Smi::zero()) continue; // Not a function table.
    DirectHandle<WasmDispatchTable> dispatch_table{
        Cast<WasmDispatchTable>(maybe_dispatch_table), isolate_};
    WasmDispatchTable::AddUse(isolate_, dispatch_table, data_part, i);
  }
}
References v8::internal::WasmDispatchTable::AddUse(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::wasm::WasmModule::memories, v8::internal::memory_objects, module_, v8::internal::wasm::WasmTable::shared, shared_trusted_data_, v8::internal::wasm::WasmModule::tables, trusted_data(), trusted_data_, v8::internal::WasmMemoryObject::UseInInstance(), and v8::internal::Smi::zero().
Referenced by Build_Phase1().
Build_Phase2()
Maybe< bool > v8::internal::wasm::InstanceBuilder::Build_Phase2 () [private]
Definition at line 1914 of file module-instantiate.cc.
                                          {
  //--------------------------------------------------------------------------
  // Install JS prototypes on Custom Descriptors ("direct" design).
  //--------------------------------------------------------------------------
  if (js_prototypes_setup_.has_value()) {
    js_prototypes_setup_->SetInstanceData(trusted_data_, shared_trusted_data_);
    js_prototypes_setup_->ConfigurePrototypes_Direct();
  }
  //--------------------------------------------------------------------------
  // Load element segments into tables.
  //--------------------------------------------------------------------------
  if (module_->tables.size() > 0) {
    LoadTableSegments();
    if (thrower_->error()) return {};
  }
  //--------------------------------------------------------------------------
  // Initialize the memory by loading data segments.
  //--------------------------------------------------------------------------
  if (!module_->data_segments.empty()) {
    LoadDataSegments();
    if (thrower_->error()) return {};
  }
  return Just(true);
}
References v8::internal::wasm::WasmModule::data_segments, v8::internal::wasm::ErrorThrower::error(), js_prototypes_setup_, v8::Just(), LoadDataSegments(), LoadTableSegments(), module_, shared_trusted_data_, v8::internal::wasm::WasmModule::tables, thrower_, and trusted_data_.
Referenced by Build().
ConfigurePrototypes_Modular()
bool v8::internal::wasm::InstanceBuilder::ConfigurePrototypes_Modular ()
Definition at line 2203 of file module-instantiate.cc.
                                                  {
  if (!v8_flags.wasm_explicit_prototypes) return true;
  if (!js_prototypes_setup_) return true;
  js_prototypes_setup_->ConfigurePrototypes_Modular();
  return !thrower_->error() && !isolate_->has_exception();
}
References v8::internal::wasm::ErrorThrower::error(), v8::internal::Isolate::has_exception(), isolate_, js_prototypes_setup_, thrower_, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::InstantiateToInstanceObject().
ExecuteStartFunction()
bool v8::internal::wasm::InstanceBuilder::ExecuteStartFunction ()
Definition at line 1942 of file module-instantiate.cc.
                                           {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.ExecuteStartFunction");
  if (start_function_.is_null()) return true; // No start function.
  HandleScope scope(isolate_);
  // In case the start function calls out to Blink, we have to make sure that
  // the correct "entered context" is available. This is the equivalent of
  // v8::Context::Enter() and must happen in addition to the function call
  // sequence doing the compiled version of "isolate->set_context(...)".
  HandleScopeImplementer* hsi = isolate_->handle_scope_implementer();
  hsi->EnterContext(start_function_->native_context());
  // Call the JS function.
  DirectHandle<Object> undefined = isolate_->factory()->undefined_value();
  MaybeDirectHandle<Object> retval =
      Execution::Call(isolate_, start_function_, undefined, {});
  hsi->LeaveContext();
  // {start_function_} has to be called only once.
  start_function_ = {};
  if (retval.is_null()) {
    DCHECK(isolate_->has_exception());
    return false;
  }
  return true;
}
References v8::internal::Execution::Call(), v8::internal::DCHECK(), v8::internal::HandleScopeImplementer::EnterContext(), v8::internal::Isolate::factory(), v8::internal::Isolate::handle_scope_implementer(), v8::internal::Isolate::has_exception(), v8::internal::MaybeDirectHandle< T >::is_null(), isolate_, v8::internal::HandleScopeImplementer::LeaveContext(), start_function_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::undefined.
Referenced by v8::internal::wasm::InstantiateToInstanceObject().
FinalizeExportsObject()
void v8::internal::wasm::InstanceBuilder::FinalizeExportsObject (MaybeDirectHandle< WasmInstanceObject > instance)
Definition at line 2210 of file module-instantiate.cc.
                                                    {
  DirectHandle<JSObject> exports_object(
      instance.ToHandleChecked()->exports_object(), isolate_);
  // Switch back to fast properties if possible.
  JSObject::MigrateSlowToFast(exports_object, 0, "WasmExportsObjectFinished");
  if (module_->origin == kWasmOrigin) {
    CHECK(JSReceiver::SetIntegrityLevel(isolate_, exports_object, FROZEN,
                                        kDontThrow)
              .FromMaybe(false));
  }
}
References CHECK, v8::internal::FROZEN, isolate_, v8::internal::kDontThrow, v8::internal::wasm::kWasmOrigin, v8::internal::JSObject::MigrateSlowToFast(), module_, v8::internal::wasm::WasmModule::origin, v8::internal::JSReceiver::SetIntegrityLevel(), and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by v8::internal::wasm::InstantiateToInstanceObject().
GetRawUntaggedGlobalPtr()
template<typename T >
T * v8::internal::wasm::InstanceBuilder::GetRawUntaggedGlobalPtr (const WasmGlobal & global) [private]
Definition at line 2844 of file module-instantiate.cc.
                                                                    {
  return reinterpret_cast<T*>(raw_buffer_ptr(
      global.shared ? shared_untagged_globals_ : untagged_globals_,
      global.offset));
}
References v8::internal::wasm::WasmGlobal::offset, v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::raw_buffer_ptr(), v8::internal::wasm::WasmGlobal::shared, shared_untagged_globals_, and untagged_globals_.
ImportName() [1/2]
std::string v8::internal::wasm::InstanceBuilder::ImportName (uint32_t index) [inline], [private]
Definition at line 1257 of file module-instantiate.cc.
                                       {
    const WasmImport& import = module_->import_table[index];
    const char* wire_bytes_start = reinterpret_cast<const char*>(
        module_object_->native_module()->wire_bytes().data());
    std::ostringstream oss;
    oss << "Import #" << index << " \"";
    oss.write(wire_bytes_start + import.module_name.offset(),
              import.module_name.length());
    oss << "\" \"";
    oss.write(wire_bytes_start + import.field_name.offset(),
              import.field_name.length());
    oss << "\"";
    return oss.str();
  }
References v8::internal::wasm::WasmModule::import_table, v8::internal::index, module_, and module_object_.
Referenced by LookupImport(), LookupImportAsm(), ProcessImportedFunction(), ProcessImportedGlobal(), ProcessImportedMemories(), ProcessImportedTable(), ProcessImportedWasmGlobalObject(), and ProcessImports().
ImportName() [2/2]
std::string v8::internal::wasm::InstanceBuilder::ImportName (uint32_t index, DirectHandle< String > module_name) [inline], [private]
Definition at line 1272 of file module-instantiate.cc.
                                                                         {
    std::ostringstream oss;
    oss << "Import #" << index << " \"" << module_name->ToCString().get()
        << "\"";
    return oss.str();
  }
References v8::internal::index.
InitGlobals()
void v8::internal::wasm::InstanceBuilder::InitGlobals () [private]
Definition at line 2851 of file module-instantiate.cc.
                                  {
  for (const WasmGlobal& global : module_->globals) {
    DCHECK_IMPLIES(global.imported, !global.init.is_set());
    if (!global.init.is_set()) continue;
    ValueOrError result = EvaluateConstantExpression(
        &init_expr_zone_, global.init, global.type, module_, isolate_,
        trusted_data_, shared_trusted_data_);
    if (MaybeMarkError(result, thrower_)) return;
    if (global.type.is_reference()) {
      (global.shared ? shared_tagged_globals_ : tagged_globals_)
          ->set(global.offset, *to_value(result).to_ref());
    } else {
      to_value(result).CopyTo(GetRawUntaggedGlobalPtr<uint8_t>(global));
    }
  }
}
References v8::internal::wasm::WasmValue::CopyTo(), DCHECK_IMPLIES, v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::WasmModule::globals, v8::internal::wasm::WasmGlobal::imported, v8::internal::wasm::WasmGlobal::init, init_expr_zone_, v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::ConstantExpression::is_set(), isolate_, v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::MaybeMarkError(), module_, v8::internal::wasm::WasmGlobal::offset, v8::base::internal::result, v8::internal::wasm::WasmGlobal::shared, shared_tagged_globals_, shared_trusted_data_, tagged_globals_, thrower_, v8::internal::wasm::WasmValue::to_ref(), v8::internal::wasm::to_value(), trusted_data_, and v8::internal::wasm::WasmGlobal::type.
Referenced by Build_Phase1().
InitializeTags()
void v8::internal::wasm::InstanceBuilder::InitializeTags () [private]
Definition at line 3381 of file module-instantiate.cc.
                                     {
  DirectHandle<FixedArray> tags_table(trusted_data_->tags_table(), isolate_);
  for (int index = 0; index < tags_table->length(); ++index) {
    if (!IsUndefined(tags_table->get(index), isolate_)) continue;
    DirectHandle<WasmExceptionTag> tag = WasmExceptionTag::New(isolate_, index);
    tags_table->set(index, *tag);
  }
}
References v8::internal::index, isolate_, v8::internal::WasmExceptionTag::New(), and trusted_data_.
Referenced by Build_Phase1().
LoadDataSegments()
void v8::internal::wasm::InstanceBuilder::LoadDataSegments () [private]
Definition at line 2095 of file module-instantiate.cc.
                                       {
  base::Vector<const uint8_t> wire_bytes =
      module_object_->native_module()->wire_bytes();
  for (const WasmDataSegment& segment : module_->data_segments) {
    uint32_t size = segment.source.length();
    // Passive segments are not copied during instantiation.
    if (!segment.active) continue;
    const WasmMemory& dst_memory = module_->memories[segment.memory_index];
    size_t dest_offset;
    ValueOrError result = EvaluateConstantExpression(
        &init_expr_zone_, segment.dest_addr,
        dst_memory.is_memory64() ? kWasmI64 : kWasmI32, module_, isolate_,
        trusted_data_, shared_trusted_data_);
    if (MaybeMarkError(result, thrower_)) return;
    if (dst_memory.is_memory64()) {
      uint64_t dest_offset_64 = to_value(result).to_u64();
      // Clamp to {std::numeric_limits<size_t>::max()}, which is always an
      // invalid offset, so we always fail the bounds check below.
      DCHECK_GT(std::numeric_limits<size_t>::max(), dst_memory.max_memory_size);
      dest_offset = static_cast<size_t>(std::min(
          dest_offset_64, uint64_t{std::numeric_limits<size_t>::max()}));
    } else {
      dest_offset = to_value(result).to_u32();
    }
    size_t memory_size = trusted_data_->memory_size(segment.memory_index);
    if (!base::IsInBounds<size_t>(dest_offset, size, memory_size)) {
      size_t segment_index = &segment - module_->data_segments.data();
      thrower_->RuntimeError(
          "data segment %zu is out of bounds (offset %zu, "
          "length %u, memory size %zu)",
          segment_index, dest_offset, size, memory_size);
      return;
    }
    uint8_t* memory_base = trusted_data_->memory_base(segment.memory_index);
    std::memcpy(memory_base + dest_offset,
                wire_bytes.begin() + segment.source.offset(), size);
  }
}
References v8::internal::wasm::WasmDataSegment::active, v8::base::Vector< T >::begin(), v8::internal::wasm::WasmModule::data_segments, DCHECK_GT, v8::internal::wasm::WasmDataSegment::dest_addr, v8::internal::wasm::EvaluateConstantExpression(), init_expr_zone_, v8::internal::wasm::WasmMemory::is_memory64(), isolate_, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::WireBytesRef::length(), v8::internal::wasm::WasmMemory::max_memory_size, v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::MaybeMarkError(), v8::internal::wasm::WasmModule::memories, v8::internal::wasm::WasmDataSegment::memory_index, module_, module_object_, v8::internal::wasm::WireBytesRef::offset(), v8::base::internal::result, shared_trusted_data_, size(), v8::internal::wasm::WasmDataSegment::source, thrower_, v8::internal::wasm::to_value(), and trusted_data_.
Referenced by Build_Phase2().
LoadTableSegments()
void v8::internal::wasm::InstanceBuilder::LoadTableSegments () [private]
Definition at line 3290 of file module-instantiate.cc.
                                        {
  for (uint32_t segment_index = 0;
       segment_index < module_->elem_segments.size(); ++segment_index) {
    const WasmElemSegment& elem_segment = module_->elem_segments[segment_index];
    // Passive segments are not copied during instantiation.
    if (elem_segment.status != WasmElemSegment::kStatusActive) continue;
    const uint32_t table_index = elem_segment.table_index;
    const WasmTable* table = &module_->tables[table_index];
    size_t dest_offset;
    ValueOrError result = EvaluateConstantExpression(
        &init_expr_zone_, elem_segment.offset,
        table->is_table64() ? kWasmI64 : kWasmI32, module_, isolate_,
        trusted_data_, shared_trusted_data_);
    if (MaybeMarkError(result, thrower_)) return;
    if (table->is_table64()) {
      uint64_t dest_offset_64 = to_value(result).to_u64();
      // Clamp to {std::numeric_limits<size_t>::max()}, which is always an
      // invalid offset, so we always fail the bounds check below.
      DCHECK_GT(std::numeric_limits<size_t>::max(), wasm::max_table_size());
      dest_offset = static_cast<size_t>(std::min(
          dest_offset_64, uint64_t{std::numeric_limits<size_t>::max()}));
    } else {
      dest_offset = to_value(result).to_u32();
    }
    const size_t count = elem_segment.element_count;
    DirectHandle<WasmTableObject> table_object(
        Cast<WasmTableObject>(
            trusted_data(table->shared)->tables()->get(table_index)),
        isolate_);
    if (!base::IsInBounds<size_t>(dest_offset, count,
                                  table_object->current_length())) {
      thrower_->RuntimeError("%s",
                             MessageFormatter::TemplateString(
                                 MessageTemplate::kWasmTrapTableOutOfBounds));
      return;
    }
    base::Vector<const uint8_t> module_bytes =
        trusted_data_->native_module()->wire_bytes();
    Decoder decoder(module_bytes);
    decoder.consume_bytes(elem_segment.elements_wire_bytes_offset);
    bool is_function_table =
        IsSubtypeOf(module_->tables[table_index].type, kWasmFuncRef, module_);
    if (is_function_table) {
      for (size_t i = 0; i < count; i++) {
        int entry_index = static_cast<int>(dest_offset + i);
        ValueOrError computed_element = ConsumeElementSegmentEntry(
            &init_expr_zone_, isolate_, trusted_data_, shared_trusted_data_,
            elem_segment, decoder, kLazyFunctionsAndNull);
        if (MaybeMarkError(computed_element, thrower_)) return;
        WasmValue computed_value = to_value(computed_element);
        if (computed_value.type() == kWasmI32) {
          if (computed_value.to_i32() >= 0) {
            // TODO(42204563): Should this use trusted_data(table->shared)?
            SetFunctionTablePlaceholder(isolate_, trusted_data_, table_object,
                                        entry_index, computed_value.to_i32());
          } else {
            SetFunctionTableNullEntry(isolate_, table_object, entry_index);
          }
        } else {
          WasmTableObject::Set(isolate_, table_object, entry_index,
                               computed_value.to_ref());
        }
      }
    } else {
      for (size_t i = 0; i < count; i++) {
        int entry_index = static_cast<int>(dest_offset + i);
        ValueOrError computed_element = ConsumeElementSegmentEntry(
            &init_expr_zone_, isolate_, trusted_data_, shared_trusted_data_,
            elem_segment, decoder, kStrictFunctionsAndNull);
        if (MaybeMarkError(computed_element, thrower_)) return;
        WasmTableObject::Set(isolate_, table_object, entry_index,
                             to_value(computed_element).to_ref());
      }
    }
    // Active segment have to be set to empty after instance initialization
    // (much like passive segments after dropping).
    trusted_data(elem_segment.shared)
        ->element_segments()
        ->set(segment_index, *isolate_->factory()->empty_fixed_array());
  }
}
References v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), DCHECK_GT, v8::internal::wasm::WasmModule::elem_segments, v8::internal::wasm::WasmElemSegment::element_count, v8::internal::wasm::WasmElemSegment::elements_wire_bytes_offset, v8::internal::wasm::EvaluateConstantExpression(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, init_expr_zone_, v8::internal::wasm::WasmTable::is_table64(), isolate_, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::kLazyFunctionsAndNull, v8::internal::wasm::WasmElemSegment::kStatusActive, v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::kStrictFunctionsAndNull, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::max_table_size(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::MaybeMarkError(), module_, v8::internal::wasm::WasmElemSegment::offset, v8::base::internal::result, v8::internal::WasmTableObject::Set(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTableNullEntry(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTablePlaceholder(), v8::internal::wasm::WasmElemSegment::shared, v8::internal::wasm::WasmTable::shared, shared_trusted_data_, v8::internal::wasm::WasmElemSegment::status, v8::internal::wasm::WasmElemSegment::table_index, v8::internal::wasm::WasmModule::tables, v8::internal::MessageFormatter::TemplateString(), thrower_, v8::internal::wasm::WasmValue::to_ref(), v8::internal::wasm::to_value(), trusted_data(), trusted_data_, and v8::internal::wasm::WasmValue::type().
Referenced by Build_Phase2().
LookupImport()
MaybeDirectHandle< Object > v8::internal::wasm::InstanceBuilder::LookupImport (uint32_t index, DirectHandle< String > module_name, DirectHandle< String > import_name) [private]
Definition at line 1971 of file module-instantiate.cc.
                                      {
  // The caller checked that the ffi object is present; and we checked in
  // the JS-API layer that the ffi object, if present, is a JSObject.
  DCHECK(!ffi_.is_null());
  // Look up the module first.
  DirectHandle<Object> module;
  DirectHandle<JSReceiver> module_recv;
  if (!Object::GetPropertyOrElement(isolate_, ffi_.ToHandleChecked(),
                                    module_name)
           .ToHandle(&module) ||
      !TryCast<JSReceiver>(module, &module_recv)) {
    const char* error = module.is_null()
                            ? "module not found"
                            : "module is not an object or function";
    thrower_->TypeError("%s: %s", ImportName(index, module_name).c_str(),
                        error);
    return {};
  }
  MaybeDirectHandle<Object> value =
      Object::GetPropertyOrElement(isolate_, module_recv, import_name);
  if (value.is_null()) {
    thrower_->LinkError("%s: import not found", ImportName(index).c_str());
    return {};
  }
  return value;
}
References v8::internal::DCHECK(), ffi_, v8::internal::Object::GetPropertyOrElement(), ImportName(), v8::internal::index, v8::internal::DirectHandle< T >::is_null(), isolate_, thrower_, and v8::internal::value.
Referenced by SanitizeImports().
LookupImportAsm()
MaybeDirectHandle< Object > v8::internal::wasm::InstanceBuilder::LookupImportAsm (uint32_t index, DirectHandle< String > import_name) [private]
Definition at line 2048 of file module-instantiate.cc.
                                                      {
  // The caller checked that the ffi object is present.
  DCHECK(!ffi_.is_null());
  // Perform lookup of the given {import_name} without causing any observable
  // side-effect. We only accept accesses that resolve to data properties,
  // which is indicated by the asm.js spec in section 7 ("Linking") as well.
  PropertyKey key(isolate_, Cast<Name>(import_name));
  LookupIterator it(isolate_, ffi_.ToHandleChecked(), key);
  switch (it.state()) {
    case LookupIterator::ACCESS_CHECK:
    case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
    case LookupIterator::INTERCEPTOR:
    case LookupIterator::JSPROXY:
    case LookupIterator::WASM_OBJECT:
    case LookupIterator::ACCESSOR:
    case LookupIterator::TRANSITION:
      thrower_->LinkError("%s: not a data property",
                          ImportName(index, import_name).c_str());
      return {};
    case LookupIterator::NOT_FOUND:
      // Accepting missing properties as undefined does not cause any
      // observable difference from JavaScript semantics, we are lenient.
      return isolate_->factory()->undefined_value();
    case LookupIterator::DATA: {
      DirectHandle<Object> value = it.GetDataValue();
      // For legacy reasons, we accept functions for imported globals (see
      // {ProcessImportedGlobal}), but only if we can easily determine that
      // their Number-conversion is side effect free and returns NaN (which is
      // the case as long as "valueOf" (or others) are not overwritten).
      if (IsJSFunction(*value) &&
          module_->import_table[index].kind == kExternalGlobal &&
          !HasDefaultToNumberBehaviour(isolate_, Cast<JSFunction>(value))) {
        thrower_->LinkError("%s: function has special ToNumber behaviour",
                            ImportName(index, import_name).c_str());
        return {};
      }
      return value;
    }
    case LookupIterator::STRING_LOOKUP_START_OBJECT:
      UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), v8::internal::Isolate::factory(), ffi_, v8::internal::LookupIterator::GetDataValue(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::HasDefaultToNumberBehaviour(), v8::internal::wasm::WasmModule::import_table, ImportName(), v8::internal::index, v8::internal::LookupIterator::INTERCEPTOR, isolate_, v8::internal::LookupIterator::JSPROXY, v8::internal::wasm::kExternalGlobal, v8::internal::key, module_, v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, thrower_, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), v8::internal::value, and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by SanitizeImports().
ProcessExports()
void v8::internal::wasm::InstanceBuilder::ProcessExports () [private]
Definition at line 2893 of file module-instantiate.cc.
                                     {
  std::unordered_map<int, IndirectHandle<Object>> imported_globals;
  // If an imported WebAssembly global gets exported, the export has to be
  // identical to to import. Therefore we cache all re-exported globals
  // in a map here.
  // Note: re-exported functions must also preserve their identity; they
  // have already been cached in the instance by {ProcessImportedFunction}.
  for (size_t index = 0, end = module_->import_table.size(); index < end;
       ++index) {
    const WasmImport& import = module_->import_table[index];
    if (import.kind == kExternalGlobal &&
        module_->globals[import.index].exported) {
      DirectHandle<Object> value = sanitized_imports_[index];
      if (IsWasmGlobalObject(*value)) {
        imported_globals[import.index] = indirect_handle(value, isolate_);
      }
    }
  }
  DirectHandle<WasmInstanceObject> instance_object{
      trusted_data_->instance_object(), isolate_};
  DirectHandle<JSObject> exports_object =
      direct_handle(instance_object->exports_object(), isolate_);
  MaybeDirectHandle<String> single_function_name;
  bool is_asm_js = is_asmjs_module(module_);
  if (is_asm_js) {
    DirectHandle<JSFunction> object_function = DirectHandle<JSFunction>(
        isolate_->native_context()->object_function(), isolate_);
    exports_object = isolate_->factory()->NewJSObject(object_function);
    single_function_name =
        isolate_->factory()->InternalizeUtf8String(AsmJs::kSingleFunctionName);
    instance_object->set_exports_object(*exports_object);
  }
  // Switch the exports object to dictionary mode and allocate enough storage
  // for the expected number of exports.
  DCHECK(exports_object->HasFastProperties());
  JSObject::NormalizeProperties(
      isolate_, exports_object, KEEP_INOBJECT_PROPERTIES,
      static_cast<int>(module_->export_table.size()), "WasmExportsObject");
  PropertyDescriptor desc;
  desc.set_writable(is_asm_js);
  desc.set_enumerable(true);
  desc.set_configurable(is_asm_js);
  const PropertyDetails details{PropertyKind::kData, desc.ToAttributes(),
                                PropertyConstness::kMutable};
  // Process each export in the export table.
  for (const WasmExport& exp : module_->export_table) {
    DirectHandle<String> name =
        WasmModuleObject::ExtractUtf8StringFromModuleBytes(
            isolate_, module_object_, exp.name, kInternalize);
    DirectHandle<JSAny> value;
    switch (exp.kind) {
      case kExternalFunction: {
        // Wrap and export the code as a JSFunction.
        bool shared = module_->function_is_shared(exp.index);
        DirectHandle<WasmFuncRef> func_ref =
            WasmTrustedInstanceData::GetOrCreateFuncRef(
                isolate_, trusted_data(shared), exp.index);
        DirectHandle<WasmInternalFunction> internal_function{
            func_ref->internal(isolate_), isolate_};
        DirectHandle<JSFunction> wasm_external_function =
            WasmInternalFunction::GetOrCreateExternal(internal_function);
        value = wasm_external_function;
        if (is_asm_js &&
            String::Equals(isolate_, name,
                           single_function_name.ToHandleChecked())) {
          desc.set_value(value);
          CHECK(JSReceiver::DefineOwnProperty(isolate_, instance_object, name,
                                              &desc, Just(kThrowOnError))
                    .FromMaybe(false));
          continue;
        }
        break;
      }
      case kExternalTable: {
        bool shared = module_->tables[exp.index].shared;
        DirectHandle<WasmTrustedInstanceData> data = trusted_data(shared);
        value = direct_handle(Cast<JSAny>(data->tables()->get(exp.index)),
                              isolate_);
        break;
      }
      case kExternalMemory: {
        // Export the memory as a WebAssembly.Memory object. A WasmMemoryObject
        // should already be available if the module has memory, since we always
        // create or import it when building an WasmInstanceObject.
        value =
            direct_handle(trusted_data_->memory_object(exp.index), isolate_);
        break;
      }
      case kExternalGlobal: {
        const WasmGlobal& global = module_->globals[exp.index];
        DirectHandle<WasmTrustedInstanceData> maybe_shared_data =
            trusted_data(global.shared);
        if (global.imported) {
          auto cached_global = imported_globals.find(exp.index);
          if (cached_global != imported_globals.end()) {
            value = Cast<JSAny>(cached_global->second);
            break;
          }
        }
        DirectHandle<JSArrayBuffer> untagged_buffer;
        DirectHandle<FixedArray> tagged_buffer;
        uint32_t offset;
        if (global.mutability && global.imported) {
          DirectHandle<FixedArray> buffers_array(
              maybe_shared_data->imported_mutable_globals_buffers(), isolate_);
          if (global.type.is_reference()) {
            tagged_buffer = direct_handle(
                Cast<FixedArray>(buffers_array->get(global.index)), isolate_);
            // For externref globals we store the relative offset in the
            // imported_mutable_globals array instead of an absolute address.
            offset = static_cast<uint32_t>(
                maybe_shared_data->imported_mutable_globals()->get(
                    global.index));
          } else {
            untagged_buffer = direct_handle(
                Cast<JSArrayBuffer>(buffers_array->get(global.index)),
                isolate_);
            Address global_addr = maybe_shared_data->imported_mutable_globals()
                                      ->get_sandboxed_pointer(global.index);
            size_t buffer_size = untagged_buffer->GetByteLength();
            Address backing_store =
                reinterpret_cast<Address>(untagged_buffer->backing_store());
            CHECK(global_addr >= backing_store &&
                  global_addr < backing_store + buffer_size);
            offset = static_cast<uint32_t>(global_addr - backing_store);
          }
        } else {
          if (global.type.is_reference()) {
            tagged_buffer = direct_handle(
                maybe_shared_data->tagged_globals_buffer(), isolate_);
          } else {
            untagged_buffer = direct_handle(
                maybe_shared_data->untagged_globals_buffer(), isolate_);
          }
          offset = global.offset;
        }
        // Since the global's array untagged_buffer is always provided,
        // allocation should never fail.
        DirectHandle<WasmGlobalObject> global_obj =
            WasmGlobalObject::New(isolate_, maybe_shared_data, untagged_buffer,
                                  tagged_buffer, global.type, offset,
                                  global.mutability)
                .ToHandleChecked();
        value = global_obj;
        break;
      }
      case kExternalTag: {
        const WasmTag& tag = module_->tags[exp.index];
        DirectHandle<WasmTagObject> wrapper = tags_wrappers_[exp.index];
        if (wrapper.is_null()) {
          DirectHandle<HeapObject> tag_object(
              Cast<HeapObject>(trusted_data_->tags_table()->get(exp.index)),
              isolate_);
          CanonicalTypeIndex sig_index =
              module_->canonical_sig_id(tag.sig_index);
          // TODO(42204563): Support shared tags.
          wrapper = WasmTagObject::New(isolate_, tag.sig, sig_index, tag_object,
                                       trusted_data_);
          tags_wrappers_[exp.index] = wrapper;
        }
        value = wrapper;
        break;
      }
      default:
        UNREACHABLE();
    }
    uint32_t index;
    if (V8_UNLIKELY(name->AsArrayIndex(&index))) {
      // Add a data element.
      JSObject::AddDataElement(isolate_, exports_object, index, value,
                               details.attributes());
    } else {
      // Add a property to the dictionary.
      JSObject::SetNormalizedProperty(exports_object, name, value, details);
    }
  }
}
References v8::internal::JSObject::AddDataElement(), v8::internal::wasm::WasmModule::canonical_sig_id(), CHECK, v8::internal::DCHECK(), v8::internal::JSReceiver::DefineOwnProperty(), v8::internal::direct_handle(), v8::internal::compiler::end(), v8::internal::String::Equals(), v8::base::ieee754::exp(), v8::internal::wasm::WasmModule::export_table, v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmModule::function_is_shared(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::wasm::WasmModule::globals, v8::internal::wasm::WasmModule::import_table, v8::internal::wasm::WasmGlobal::imported, v8::internal::index, v8::internal::wasm::WasmGlobal::index, v8::internal::indirect_handle(), v8::internal::instance_object, v8::internal::Factory::InternalizeUtf8String(), v8::internal::wasm::is_asmjs_module(), v8::internal::DirectHandle< T >::is_null(), v8::internal::wasm::ValueTypeBase::is_reference(), isolate_, v8::Just(), v8::internal::kData, v8::internal::KEEP_INOBJECT_PROPERTIES, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kExternalTable, v8::internal::wasm::kExternalTag, v8::internal::kInternalize, v8::internal::kMutable, v8::internal::AsmJs::kSingleFunctionName, v8::internal::kThrowOnError, module_, module_object_, v8::internal::wasm::WasmGlobal::mutability, v8::internal::wasm::name(), v8::internal::Isolate::native_context(), v8::internal::WasmTagObject::New(), v8::internal::WasmGlobalObject::New(), v8::internal::Factory::NewJSObject(), v8::internal::JSObject::NormalizeProperties(), v8::internal::wasm::WasmGlobal::offset, sanitized_imports_, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::wasm::WasmGlobal::shared, v8::internal::wasm::WasmTag::sig, v8::internal::wasm::WasmTag::sig_index, v8::internal::wasm::WasmModule::tables, v8::internal::tagged_buffer, v8::internal::wasm::WasmModule::tags, tags_wrappers_, v8::internal::PropertyDescriptor::ToAttributes(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), trusted_data(), trusted_data_, v8::internal::wasm::WasmGlobal::type, v8::internal::UNREACHABLE(), V8_UNLIKELY, and v8::internal::value.
Referenced by Build_Phase1().
ProcessImportedFunction()
bool v8::internal::wasm::InstanceBuilder::ProcessImportedFunction (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int import_index, int func_index, DirectHandle< Object > value, WellKnownImport preknown_import) [private]
Definition at line 2297 of file module-instantiate.cc.
                                     {
  // Function imports must be callable.
  if (!IsCallable(*value)) {
    if (!IsWasmSuspendingObject(*value)) {
      thrower_->LinkError("%s: function import requires a callable",
                          ImportName(import_index).c_str());
      return false;
    }
    DCHECK(IsCallable(Cast<WasmSuspendingObject>(*value)->callable()));
  }
  // Store any {WasmExternalFunction} callable in the instance before the call
  // is resolved to preserve its identity. This handles exported functions as
  // well as functions constructed via other means (e.g. WebAssembly.Function).
  if (WasmExternalFunction::IsWasmExternalFunction(*value)) {
    trusted_instance_data->func_refs()->set(
        func_index, Cast<WasmExternalFunction>(*value)->func_ref());
  }
  auto callable = Cast<JSReceiver>(value);
  CanonicalTypeIndex sig_index =
      module_->canonical_sig_id(module_->functions[func_index].sig_index);
  const CanonicalSig* expected_sig =
      GetTypeCanonicalizer()->LookupFunctionSignature(sig_index);
  ResolvedWasmImport resolved(trusted_instance_data, func_index, callable,
                              expected_sig, sig_index, preknown_import);
  if (resolved.well_known_status() != WellKnownImport::kGeneric &&
      v8_flags.trace_wasm_inlining) {
    PrintF("[import %d is well-known built-in %s]\n", import_index,
           WellKnownImportName(resolved.well_known_status()));
  }
  well_known_imports_.push_back(resolved.well_known_status());
  ImportCallKind kind = resolved.kind();
  callable = resolved.callable();
  DirectHandle<WasmFunctionData> trusted_function_data =
      resolved.trusted_function_data();
  ImportedFunctionEntry imported_entry(trusted_instance_data, func_index);
  switch (kind) {
    case ImportCallKind::kLinkError:
      thrower_->LinkError(
          "%s: imported function does not match the expected type",
          ImportName(import_index).c_str());
      return false;
    case ImportCallKind::kWasmToWasm: {
      // The imported function is a Wasm function from another instance.
      auto function_data =
          Cast<WasmExportedFunctionData>(trusted_function_data);
      // The import reference is the trusted instance data itself.
      Tagged<WasmTrustedInstanceData> instance_data =
          function_data->instance_data();
      CHECK_GE(function_data->function_index(),
               instance_data->module()->num_imported_functions);
      WasmCodePointer imported_target =
          instance_data->GetCallTarget(function_data->function_index());
      imported_entry.SetWasmToWasm(instance_data, imported_target, sig_index
#if V8_ENABLE_DRUMBRAKE
                                   ,
                                   function_data->function_index()
#endif // V8_ENABLE_DRUMBRAKE
      );
      return true;
    }
    case ImportCallKind::kWasmToJSFastApi: {
      DCHECK(IsJSFunction(*callable) || IsJSBoundFunction(*callable));
      std::shared_ptr<wasm::WasmImportWrapperHandle> wrapper_handle =
          GetWasmImportWrapperCache()->CompileWasmJsFastCallWrapper(
              isolate_, callable, expected_sig);
      imported_entry.SetWasmToWrapper(isolate_, callable,
                                      std::move(wrapper_handle), kNoSuspend,
                                      expected_sig, sig_index);
      return true;
    }
    case ImportCallKind::kRuntimeTypeError:
    case ImportCallKind::kJSFunction:
    case ImportCallKind::kUseCallBuiltin:
    case ImportCallKind::kWasmToCapi:
      // These cases are handled below.
      break;
  }
  if (v8_flags.wasm_jitless) {
    imported_entry.SetWasmToWrapper(isolate_, callable, {}, kNoSuspend,
                                    expected_sig, sig_index);
    return true;
  }
  int expected_arity = static_cast<int>(expected_sig->parameter_count());
  if (kind == ImportCallKind::kJSFunction) {
    auto function = Cast<JSFunction>(callable);
    Tagged<SharedFunctionInfo> shared = function->shared();
    expected_arity = shared->internal_formal_parameter_count_without_receiver();
  }
  WasmImportWrapperCache* cache = GetWasmImportWrapperCache();
  std::shared_ptr<wasm::WasmImportWrapperHandle> wrapper_handle =
      cache->Get(isolate_, kind, sig_index, expected_arity, resolved.suspend(),
                 expected_sig);
  imported_entry.SetWasmToWrapper(isolate_, callable, std::move(wrapper_handle),
                                  resolved.suspend(), expected_sig, sig_index);
  return true;
}
References v8::internal::wasm::ResolvedWasmImport::callable(), v8::internal::wasm::WasmModule::canonical_sig_id(), CHECK_GE, v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), v8::internal::DCHECK(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WasmImportWrapperCache::Get(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::GetWasmImportWrapperCache(), ImportName(), v8::internal::instance_data, isolate_, v8::internal::WasmExternalFunction::IsWasmExternalFunction(), v8::internal::wasm::kGeneric, v8::internal::wasm::ResolvedWasmImport::kind(), v8::internal::wasm::kJSFunction, v8::internal::wasm::kLinkError, v8::internal::wasm::kNoSuspend, v8::internal::wasm::kRuntimeTypeError, v8::internal::wasm::kUseCallBuiltin, v8::internal::wasm::kWasmToCapi, v8::internal::wasm::kWasmToJSFastApi, v8::internal::wasm::kWasmToWasm, v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), module_, v8::internal::Signature< T >::parameter_count(), v8::internal::PrintF(), v8::internal::ImportedFunctionEntry::SetWasmToWasm(), v8::internal::ImportedFunctionEntry::SetWasmToWrapper(), v8::internal::wasm::ResolvedWasmImport::suspend(), thrower_, v8::internal::wasm::ResolvedWasmImport::trusted_function_data(), v8::internal::v8_flags, v8::internal::value, well_known_imports_, v8::internal::wasm::ResolvedWasmImport::well_known_status(), and v8::internal::wasm::WellKnownImportName().
Referenced by ProcessImports().
ProcessImportedGlobal()
bool v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int import_index, int global_index, DirectHandle< Object > value) [private]
Definition at line 2586 of file module-instantiate.cc.
                                                                    {
  // Immutable global imports are converted to numbers and written into
  // the {untagged_globals_} array buffer.
  //
  // Mutable global imports instead have their backing array buffers
  // referenced by this instance, and store the address of the imported
  // global in the {imported_mutable_globals_} array.
  const WasmGlobal& global = module_->globals[global_index];
  // SIMD proposal allows modules to define an imported v128 global, and only
  // supports importing a WebAssembly.Global object for this global, but also
  // defines constructing a WebAssembly.Global of v128 to be a TypeError.
  // We *should* never hit this case in the JS API, but the module should should
  // be allowed to declare such a global (no validation error).
  if (global.type == kWasmS128 && !IsWasmGlobalObject(*value)) {
    thrower_->LinkError(
        "%s: global import of type v128 must be a WebAssembly.Global",
        ImportName(import_index).c_str());
    return false;
  }
  if (is_asmjs_module(module_)) {
    // Accepting {JSFunction} on top of just primitive values here is a
    // workaround to support legacy asm.js code with broken binding. Note
    // that using {NaN} (or Smi::zero()) here is what using the observable
    // conversion via {ToPrimitive} would produce as well. {LookupImportAsm}
    // checked via {HasDefaultToNumberBehaviour} that "valueOf" or friends have
    // not been patched.
    if (IsJSFunction(*value)) value = isolate_->factory()->nan_value();
    if (IsPrimitive(*value)) {
      MaybeDirectHandle<Object> converted =
          global.type == kWasmI32 ? Object::ToInt32(isolate_, value)
                                  : Object::ToNumber(isolate_, value);
      if (!converted.ToHandle(&value)) {
        // Conversion is known to fail for Symbols and BigInts.
        thrower_->LinkError("%s: global import must be a number",
                            ImportName(import_index).c_str());
        return false;
      }
    }
  }
  if (IsWasmGlobalObject(*value)) {
    auto global_object = Cast<WasmGlobalObject>(value);
    return ProcessImportedWasmGlobalObject(trusted_instance_data, import_index,
                                           global, global_object);
  }
  if (global.mutability) {
    thrower_->LinkError(
        "%s: imported mutable global must be a WebAssembly.Global object",
        ImportName(import_index).c_str());
    return false;
  }
  if (global.type.is_reference()) {
    const char* error_message;
    DirectHandle<Object> wasm_value;
    if (!wasm::JSToWasmObject(isolate_, module_, value, global.type,
                              &error_message)
             .ToHandle(&wasm_value)) {
      thrower_->LinkError("%s: %s", ImportName(import_index).c_str(),
                          error_message);
      return false;
    }
    WriteGlobalValue(
        global, WasmValue(wasm_value, module_->canonical_type(global.type)));
    return true;
  }
  if (IsNumber(*value) && global.type != kWasmI64) {
    double number_value = Object::NumberValue(*value);
    // The Wasm-BigInt proposal currently says that i64 globals may
    // only be initialized with BigInts. See:
    // https://github.com/WebAssembly/JS-BigInt-integration/issues/12
    WasmValue wasm_value =
        global.type == kWasmI32 ? WasmValue(DoubleToInt32(number_value))
        : global.type == kWasmF32 ? WasmValue(DoubleToFloat32(number_value))
                                  : WasmValue(number_value);
    WriteGlobalValue(global, wasm_value);
    return true;
  }
  if (global.type == kWasmI64 && IsBigInt(*value)) {
    WriteGlobalValue(global, WasmValue(Cast<BigInt>(*value)->AsInt64()));
    return true;
  }
  thrower_->LinkError(
      "%s: global import must be a number, valid Wasm reference, or "
      "WebAssembly.Global object",
      ImportName(import_index).c_str());
  return false;
}
References v8::internal::wasm::WasmModule::canonical_type(), v8::internal::DoubleToFloat32(), v8::internal::DoubleToInt32(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmModule::globals, ImportName(), v8::internal::wasm::is_asmjs_module(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::IsNumber(), isolate_, v8::internal::IsPrimitive(), v8::internal::wasm::JSToWasmObject(), v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::kWasmS128, module_, v8::internal::wasm::WasmGlobal::mutability, v8::internal::Object::NumberValue(), ProcessImportedWasmGlobalObject(), thrower_, v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::Object::ToInt32(), v8::Value::ToNumber(), v8::internal::wasm::WasmGlobal::type, v8::internal::value, and WriteGlobalValue().
Referenced by ProcessImports().
ProcessImportedMemories()
bool v8::internal::wasm::InstanceBuilder::ProcessImportedMemories (DirectHandle< FixedArray > imported_memory_objects) [private]
Definition at line 2770 of file module-instantiate.cc.
                                                      {
  DCHECK_EQ(module_->import_table.size(), sanitized_imports_.size());
  int num_imports = static_cast<int>(module_->import_table.size());
  for (int import_index = 0; import_index < num_imports; ++import_index) {
    const WasmImport& import = module_->import_table[import_index];
    if (import.kind != kExternalMemory) continue;
    DirectHandle<Object> value = sanitized_imports_[import_index];
    if (!IsWasmMemoryObject(*value)) {
      thrower_->LinkError(
          "%s: memory import must be a WebAssembly.Memory object",
          ImportName(import_index).c_str());
      return false;
    }
    uint32_t memory_index = import.index;
    auto memory_object = Cast<WasmMemoryObject>(value);
    DirectHandle<JSArrayBuffer> buffer{memory_object->array_buffer(), isolate_};
    uint32_t imported_cur_pages =
        static_cast<uint32_t>(buffer->GetByteLength() / kWasmPageSize);
    const WasmMemory* memory = &module_->memories[memory_index];
    if (memory->address_type != memory_object->address_type()) {
      thrower_->LinkError("cannot import %s memory as %s",
                          AddressTypeToStr(memory_object->address_type()),
                          AddressTypeToStr(memory->address_type));
      return false;
    }
    if (imported_cur_pages < memory->initial_pages) {
      thrower_->LinkError(
          "%s: memory import has %u pages which is smaller than the declared "
          "initial of %u",
          ImportName(import_index).c_str(), imported_cur_pages,
          memory->initial_pages);
      return false;
    }
    int32_t imported_maximum_pages = memory_object->maximum_pages();
    if (memory->has_maximum_pages) {
      if (imported_maximum_pages < 0) {
        thrower_->LinkError(
            "%s: memory import has no maximum limit, expected at most %u",
            ImportName(import_index).c_str(), imported_maximum_pages);
        return false;
      }
      if (static_cast<uint64_t>(imported_maximum_pages) >
          memory->maximum_pages) {
        thrower_->LinkError(
            "%s: memory import has a larger maximum size %u than the "
            "module's declared maximum %" PRIu64,
            ImportName(import_index).c_str(), imported_maximum_pages,
            memory->maximum_pages);
        return false;
      }
    }
    if (memory->is_shared != buffer->is_shared()) {
      thrower_->LinkError(
          "%s: mismatch in shared state of memory, declared = %d, imported = "
          "%d",
          ImportName(import_index).c_str(), memory->is_shared,
          buffer->is_shared());
      return false;
    }
    DCHECK_EQ(ReadOnlyRoots{isolate_}.undefined_value(),
              imported_memory_objects->get(memory_index));
    imported_memory_objects->set(memory_index, *memory_object);
  }
  return true;
}
References v8::internal::wasm::WasmMemory::address_type, v8::internal::wasm::AddressTypeToStr(), DCHECK_EQ, v8::internal::wasm::WasmMemory::has_maximum_pages, v8::internal::wasm::WasmModule::import_table, ImportName(), v8::internal::wasm::WasmMemory::initial_pages, v8::internal::wasm::WasmMemory::is_shared, isolate_, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kWasmPageSize, v8::internal::wasm::WasmMemory::maximum_pages, v8::internal::wasm::WasmModule::memories, module_, sanitized_imports_, thrower_, and v8::internal::value.
Referenced by Build_Phase1().
ProcessImportedTable()
bool v8::internal::wasm::InstanceBuilder::ProcessImportedTable (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int import_index, int table_index, DirectHandle< Object > value) [private]
Definition at line 2406 of file module-instantiate.cc.
                                                                   {
  if (!IsWasmTableObject(*value)) {
    thrower_->LinkError("%s: table import requires a WebAssembly.Table",
                        ImportName(import_index).c_str());
    return false;
  }
  const WasmTable& table = module_->tables[table_index];
  DirectHandle<WasmTableObject> table_object = Cast<WasmTableObject>(value);
  uint32_t imported_table_size =
      static_cast<uint32_t>(table_object->current_length());
  if (imported_table_size < table.initial_size) {
    thrower_->LinkError("table import %d is smaller than initial %u, got %u",
                        import_index, table.initial_size, imported_table_size);
    return false;
  }
  if (table.has_maximum_size) {
    std::optional<uint64_t> max_size = table_object->maximum_length_u64();
    if (!max_size) {
      thrower_->LinkError(
          "table import %d has no maximum length; required: %" PRIu64,
          import_index, table.maximum_size);
      return false;
    }
    if (*max_size > table.maximum_size) {
      thrower_->LinkError("table import %d has a larger maximum size %" PRIx64
                          " than the module's declared maximum %" PRIu64,
                          import_index, *max_size, table.maximum_size);
      return false;
    }
  }
  if (table.address_type != table_object->address_type()) {
    thrower_->LinkError("cannot import %s table as %s",
                        AddressTypeToStr(table_object->address_type()),
                        AddressTypeToStr(table.address_type));
    return false;
  }
  const WasmModule* table_type_module =
      table_object->has_trusted_data()
          ? table_object->trusted_data(isolate_)->module()
          : nullptr;
  // The security-relevant aspect of this DCHECK is covered by the SBXCHECK_EQ
  // below.
  DCHECK_IMPLIES(table_object->unsafe_type().has_index(),
                 table_type_module != nullptr);
  // We need to check type equivalence (rather than subtyping) because tables
  // are mutable: we cannot allow the importing module to write supertyped
  // values into a subtyped table.
  if (!EquivalentTypes(table.type, table_object->type(table_type_module),
                       module_, table_type_module)) {
    thrower_->LinkError("%s: imported table does not match the expected type",
                        ImportName(import_index).c_str());
    return false;
  }
  // Note: {trusted_instance_data} is selected by the caller to be the
  // shared or non-shared part, depending on {table.shared}.
  trusted_instance_data->tables()->set(table_index, *table_object);
  if (table_object->has_trusted_dispatch_table()) {
    Tagged<WasmDispatchTable> dispatch_table =
        table_object->trusted_dispatch_table(isolate_);
    SBXCHECK_EQ(dispatch_table->table_type(),
                module_->canonical_type(table.type));
    SBXCHECK_GE(dispatch_table->length(), table.initial_size);
    trusted_instance_data->dispatch_tables()->set(table_index, dispatch_table);
    if (table_index == 0) {
      trusted_instance_data->set_dispatch_table0(dispatch_table);
    }
  } else {
    // Function tables are required to have a WasmDispatchTable.
    SBXCHECK(!IsSubtypeOf(table.type, kWasmFuncRef, module_));
  }
  return true;
}
References v8::internal::wasm::WasmTable::address_type, v8::internal::wasm::AddressTypeToStr(), v8::internal::wasm::WasmModule::canonical_type(), DCHECK_IMPLIES, v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::WasmTable::has_maximum_size, ImportName(), v8::internal::wasm::WasmTable::initial_size, isolate_, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::WasmTable::maximum_size, module_, SBXCHECK, SBXCHECK_EQ, SBXCHECK_GE, v8::internal::wasm::WasmModule::tables, thrower_, v8::internal::wasm::WasmTable::type, and v8::internal::value.
Referenced by ProcessImports().
ProcessImportedWasmGlobalObject()
bool v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int import_index, const WasmGlobal & global, DirectHandle< WasmGlobalObject > global_object) [private]
Definition at line 2488 of file module-instantiate.cc.
                                                  {
  if (static_cast<bool>(global_object->is_mutable()) != global.mutability) {
    thrower_->LinkError(
        "%s: imported global does not match the expected mutability",
        ImportName(import_index).c_str());
    return false;
  }
  wasm::ValueType actual_type = global_object->type();
  const WasmModule* source_module = nullptr;
  if (global_object->has_trusted_data()) {
    source_module = global_object->trusted_data(isolate_)->module();
    SBXCHECK(!actual_type.has_index() ||
             source_module->has_type(actual_type.ref_index()));
  } else {
    // We don't have a module, so we wouldn't know what to do with a
    // module-relative type index.
    // Note: since we just read a type from the untrusted heap, this can't
    // be a real security boundary; we just use SBXCHECK to make it obvious
    // to fuzzers that crashing here due to corruption is safe.
    SBXCHECK(!actual_type.has_index());
  }
  bool valid_type =
      global.mutability
          ? EquivalentTypes(actual_type, global.type, source_module, module_)
          : IsSubtypeOf(actual_type, global.type, source_module, module_);
  if (!valid_type) {
    thrower_->LinkError("%s: imported global does not match the expected type",
                        ImportName(import_index).c_str());
    return false;
  }
  if (global.mutability) {
    DCHECK_LT(global.index, module_->num_imported_mutable_globals);
    DirectHandle<Object> buffer;
    if (global.type.is_reference()) {
      static_assert(sizeof(global_object->offset()) <= sizeof(Address),
                    "The offset into the globals buffer does not fit into "
                    "the imported_mutable_globals array");
      buffer = direct_handle(global_object->tagged_buffer(), isolate_);
      // For externref globals we use a relative offset, not an absolute
      // address.
      trusted_instance_data->imported_mutable_globals()->set(
          global.index, global_object->offset());
    } else {
      buffer = direct_handle(global_object->untagged_buffer(), isolate_);
      // It is safe in this case to store the raw pointer to the buffer
      // since the backing store of the JSArrayBuffer will not be
      // relocated.
      Address address = reinterpret_cast<Address>(
          raw_buffer_ptr(Cast<JSArrayBuffer>(buffer), global_object->offset()));
      trusted_instance_data->imported_mutable_globals()->set_sandboxed_pointer(
          global.index, address);
    }
    trusted_instance_data->imported_mutable_globals_buffers()->set(global.index,
                                                                   *buffer);
    return true;
  }
  WasmValue value;
  switch (global.type.kind()) {
    case kI32:
      value = WasmValue(global_object->GetI32());
      break;
    case kI64:
      value = WasmValue(global_object->GetI64());
      break;
    case kF32:
      value = WasmValue(global_object->GetF32());
      break;
    case kF64:
      value = WasmValue(global_object->GetF64());
      break;
    case kS128:
      value = WasmValue(global_object->GetS128RawBytes(), kWasmS128);
      break;
    case kRef:
    case kRefNull:
      value = WasmValue(global_object->GetRef(),
                        module_->canonical_type(global.type));
      break;
    case kVoid:
    case kTop:
    case kBottom:
    case kI8:
    case kI16:
    case kF16:
      UNREACHABLE();
  }
  WriteGlobalValue(global, value);
  return true;
}
References v8::internal::wasm::WasmModule::canonical_type(), DCHECK_LT, v8::internal::direct_handle(), v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::has_type(), ImportName(), v8::internal::wasm::WasmGlobal::index, v8::internal::wasm::ValueTypeBase::is_reference(), isolate_, v8::internal::wasm::IsSubtypeOf(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::kWasmS128, module_, v8::internal::wasm::WasmGlobal::mutability, v8::internal::wasm::WasmModule::num_imported_mutable_globals, v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::raw_buffer_ptr(), v8::internal::wasm::ValueType::ref_index(), SBXCHECK, thrower_, v8::internal::wasm::WasmGlobal::type, v8::internal::UNREACHABLE(), v8::internal::value, and WriteGlobalValue().
Referenced by ProcessImportedGlobal().
ProcessImports()
int v8::internal::wasm::InstanceBuilder::ProcessImports () [private]
Definition at line 2686 of file module-instantiate.cc.
                                    {
  int num_imported_functions = 0;
  int num_imported_tables = 0;
  DCHECK_EQ(module_->import_table.size(), sanitized_imports_.size());
  const WellKnownImportsList& preknown_imports =
      module_->type_feedback.well_known_imports;
  int num_imports = static_cast<int>(module_->import_table.size());
  for (int index = 0; index < num_imports; ++index) {
    const WasmImport& import = module_->import_table[index];
    DirectHandle<Object> value = sanitized_imports_[index];
    switch (import.kind) {
      case kExternalFunction: {
        uint32_t func_index = import.index;
        DCHECK_EQ(num_imported_functions, func_index);
        ModuleTypeIndex sig_index = module_->functions[func_index].sig_index;
        bool function_is_shared = module_->type(sig_index).is_shared;
        if (!ProcessImportedFunction(trusted_data(function_is_shared), index,
                                     func_index, value,
                                     preknown_imports.get(func_index))) {
          return -1;
        }
        num_imported_functions++;
        break;
      }
      case kExternalTable: {
        uint32_t table_index = import.index;
        DCHECK_EQ(table_index, num_imported_tables);
        bool table_is_shared = module_->tables[table_index].shared;
        if (!ProcessImportedTable(trusted_data(table_is_shared), index,
                                  table_index, value)) {
          return -1;
        }
        num_imported_tables++;
        USE(num_imported_tables);
        break;
      }
      case kExternalMemory:
        // Imported memories are already handled earlier via
        // {ProcessImportedMemories}.
        break;
      case kExternalGlobal: {
        bool global_is_shared = module_->globals[import.index].shared;
        if (!ProcessImportedGlobal(trusted_data(global_is_shared), index,
                                   import.index, value)) {
          return -1;
        }
        break;
      }
      case kExternalTag: {
        // TODO(14616): Implement shared tags.
        if (!IsWasmTagObject(*value)) {
          thrower_->LinkError("%s: tag import requires a WebAssembly.Tag",
                              ImportName(index).c_str());
          return -1;
        }
        DirectHandle<WasmTagObject> imported_tag = Cast<WasmTagObject>(value);
        if (!imported_tag->MatchesSignature(module_->canonical_sig_id(
                module_->tags[import.index].sig_index))) {
          thrower_->LinkError(
              "%s: imported tag does not match the expected type",
              ImportName(index).c_str());
          return -1;
        }
        Tagged<Object> tag = imported_tag->tag();
        DCHECK(IsUndefined(trusted_data_->tags_table()->get(import.index)));
        trusted_data_->tags_table()->set(import.index, tag);
        tags_wrappers_[import.index] = imported_tag;
        break;
      }
      default:
        UNREACHABLE();
    }
  }
  if (num_imported_functions > 0) {
    module_object_->native_module()->UpdateWellKnownImports(
        base::VectorOf(well_known_imports_));
  }
  return num_imported_functions;
}
References v8::internal::wasm::WasmModule::canonical_sig_id(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WellKnownImportsList::get(), v8::internal::wasm::WasmModule::globals, v8::internal::wasm::WasmModule::import_table, ImportName(), v8::internal::index, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kExternalTable, v8::internal::wasm::kExternalTag, module_, module_object_, ProcessImportedFunction(), ProcessImportedGlobal(), ProcessImportedTable(), sanitized_imports_, v8::internal::wasm::WasmModule::tables, v8::internal::wasm::WasmModule::tags, tags_wrappers_, thrower_, trusted_data(), trusted_data_, v8::internal::wasm::WasmModule::type(), v8::internal::wasm::WasmModule::type_feedback, v8::internal::UNREACHABLE(), USE, v8::internal::value, v8::base::VectorOf(), v8::internal::wasm::TypeFeedbackStorage::well_known_imports, and well_known_imports_.
Referenced by Build_Phase1().
SanitizeImports()
void v8::internal::wasm::InstanceBuilder::SanitizeImports () [private]
Definition at line 2224 of file module-instantiate.cc.
                                      {
  NativeModule* native_module = module_object_->native_module();
  base::Vector<const uint8_t> wire_bytes = native_module->wire_bytes();
  const WellKnownImportsList& well_known_imports =
      module_->type_feedback.well_known_imports;
  const std::string& magic_string_constants =
      native_module->compile_imports().constants_module();
  const bool has_magic_string_constants =
      native_module->compile_imports().contains(
          CompileTimeImport::kStringConstants);
  const std::vector<WasmImport>& import_table = module_->import_table;
  sanitized_imports_.resize(import_table.size());
  if (v8_flags.experimental_wasm_custom_descriptors &&
      !module_->descriptors_section.is_empty()) {
    js_prototypes_setup_.emplace(isolate_, wire_bytes, module_, thrower_,
                                 sanitized_imports_);
    js_prototypes_setup_->MaterializeDescriptorOptions(ffi_);
    if (thrower_->error()) return;
  }
  for (uint32_t index = 0; index < import_table.size(); ++index) {
    if (!sanitized_imports_[index].is_null()) continue;
    const WasmImport& import = import_table[index];
    if (import.kind == kExternalGlobal && has_magic_string_constants &&
        import.module_name.length() == magic_string_constants.size() &&
        std::equal(magic_string_constants.begin(), magic_string_constants.end(),
                   wire_bytes.begin() + import.module_name.offset())) {
      DirectHandle<String> value =
          WasmModuleObject::ExtractUtf8StringFromModuleBytes(
              isolate_, wire_bytes, import.field_name, kNoInternalize);
      sanitized_imports_[index] = value;
      continue;
    }
    if (import.kind == kExternalFunction) {
      WellKnownImport wki = well_known_imports.get(import.index);
      if (IsCompileTimeImport(wki)) {
        DirectHandle<JSFunction> fun =
            CreateFunctionForCompileTimeImport(isolate_, wki);
        sanitized_imports_[index] = fun;
        continue;
      }
    }
    if (ffi_.is_null()) {
      // No point in continuing if we don't have an imports object.
      thrower_->TypeError(
          "Imports argument must be present and must be an object");
      return;
    }
    DirectHandle<String> module_name =
        WasmModuleObject::ExtractUtf8StringFromModuleBytes(
            isolate_, wire_bytes, import.module_name, kInternalize);
    DirectHandle<String> import_name =
        WasmModuleObject::ExtractUtf8StringFromModuleBytes(
            isolate_, wire_bytes, import.field_name, kInternalize);
    MaybeDirectHandle<Object> result =
        is_asmjs_module(module_)
            ? LookupImportAsm(index, import_name)
            : LookupImport(index, module_name, import_name);
    if (thrower_->error()) {
      return;
    }
    DirectHandle<Object> value = result.ToHandleChecked();
    sanitized_imports_[index] = value;
  }
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::NativeModule::compile_imports(), v8::internal::wasm::CompileTimeImports::constants_module(), v8::internal::wasm::CompileTimeImports::contains(), v8::internal::wasm::CreateFunctionForCompileTimeImport(), v8::internal::wasm::WasmModule::descriptors_section, v8::internal::equal, v8::internal::wasm::ErrorThrower::error(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), ffi_, v8::internal::wasm::WellKnownImportsList::get(), v8::internal::wasm::WasmModule::import_table, v8::internal::index, v8::internal::wasm::is_asmjs_module(), v8::internal::wasm::WireBytesRef::is_empty(), v8::internal::wasm::IsCompileTimeImport(), isolate_, js_prototypes_setup_, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::kInternalize, v8::internal::kNoInternalize, v8::internal::wasm::kStringConstants, LookupImport(), LookupImportAsm(), module_, module_object_, v8::base::internal::result, sanitized_imports_, v8::internal::string, thrower_, v8::internal::wasm::WasmModule::type_feedback, v8::internal::v8_flags, v8::internal::value, v8::internal::wasm::TypeFeedbackStorage::well_known_imports, and v8::internal::wasm::NativeModule::wire_bytes().
Referenced by Build().
SetTableInitialValues()
void v8::internal::wasm::InstanceBuilder::SetTableInitialValues () [private]
Definition at line 3114 of file module-instantiate.cc.
                                            {
  for (int table_index = 0;
       table_index < static_cast<int>(module_->tables.size()); ++table_index) {
    const WasmTable& table = module_->tables[table_index];
    DirectHandle<WasmTrustedInstanceData> maybe_shared_data =
        trusted_data(table.shared);
    // We must not modify imported tables yet when this is run, because
    // we can't know yet whether the new instance can be successfully
    // initialized.
    DCHECK_IMPLIES(table.imported, !table.initial_value.is_set());
    if (!table.initial_value.is_set()) continue;
    DirectHandle<WasmTableObject> table_object(
        Cast<WasmTableObject>(maybe_shared_data->tables()->get(table_index)),
        isolate_);
    bool is_function_table = IsSubtypeOf(table.type, kWasmFuncRef, module_);
    if (is_function_table &&
        table.initial_value.kind() == ConstantExpression::Kind::kRefFunc) {
      for (uint32_t entry_index = 0; entry_index < table.initial_size;
           entry_index++) {
        SetFunctionTablePlaceholder(isolate_, maybe_shared_data, table_object,
                                    entry_index, table.initial_value.index());
      }
    } else if (is_function_table && table.initial_value.kind() ==
                                        ConstantExpression::Kind::kRefNull) {
      for (uint32_t entry_index = 0; entry_index < table.initial_size;
           entry_index++) {
        SetFunctionTableNullEntry(isolate_, table_object, entry_index);
      }
    } else {
      ValueOrError result = EvaluateConstantExpression(
          &init_expr_zone_, table.initial_value, table.type, module_, isolate_,
          maybe_shared_data, shared_trusted_data_);
      if (MaybeMarkError(result, thrower_)) return;
      for (uint32_t entry_index = 0; entry_index < table.initial_size;
           entry_index++) {
        WasmTableObject::Set(isolate_, table_object, entry_index,
                             to_value(result).to_ref());
      }
    }
  }
}
References DCHECK_IMPLIES, v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::WasmTable::imported, v8::internal::wasm::ConstantExpression::index(), init_expr_zone_, v8::internal::wasm::WasmTable::initial_size, v8::internal::wasm::WasmTable::initial_value, v8::internal::wasm::ConstantExpression::is_set(), isolate_, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::ConstantExpression::kind(), v8::internal::wasm::ConstantExpression::kRefFunc, v8::internal::wasm::ConstantExpression::kRefNull, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::MaybeMarkError(), module_, v8::base::internal::result, v8::internal::WasmTableObject::Set(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTableNullEntry(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTablePlaceholder(), v8::internal::wasm::WasmTable::shared, shared_trusted_data_, v8::internal::wasm::WasmModule::tables, thrower_, v8::internal::wasm::to_value(), trusted_data(), and v8::internal::wasm::WasmTable::type.
Referenced by Build_Phase1().
trusted_data()
DirectHandle<WasmTrustedInstanceData> v8::internal::wasm::InstanceBuilder::trusted_data (bool shared) const [inline], [private]
Definition at line 1253 of file module-instantiate.cc.
                                                                        {
    return shared ? shared_trusted_data_ : trusted_data_;
  }
References shared_trusted_data_, and trusted_data_.
Referenced by Build_Phase1(), Build_Phase1_Infallible(), LoadTableSegments(), ProcessExports(), ProcessImports(), and SetTableInitialValues().
WriteGlobalValue()
void v8::internal::wasm::InstanceBuilder::WriteGlobalValue (const WasmGlobal & global, const WasmValue & value) [private]
Definition at line 2139 of file module-instantiate.cc.
                                                               {
  TRACE("init [globals_start=%p + %u] = %s, type = %s\n",
        global.type.is_reference()
            ? reinterpret_cast<uint8_t*>(tagged_globals_->address())
            : raw_buffer_ptr(untagged_globals_, 0),
        global.offset, value.to_string().c_str(), global.type.name().c_str());
  DCHECK(global.mutability
             ? (value.type() == module_->canonical_type(global.type))
             : IsSubtypeOf(value.type(), module_->canonical_type(global.type)));
  if (global.type.is_numeric()) {
    value.CopyTo(GetRawUntaggedGlobalPtr<uint8_t>(global));
  } else {
    tagged_globals_->set(global.offset, *value.to_ref());
  }
}
References v8::internal::wasm::WasmModule::canonical_type(), v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::is_numeric(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::IsSubtypeOf(), module_, v8::internal::wasm::WasmGlobal::mutability, v8::internal::wasm::ValueTypeBase::name(), v8::internal::wasm::WasmGlobal::offset, v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::raw_buffer_ptr(), tagged_globals_, v8::internal::TRACE(), v8::internal::wasm::WasmGlobal::type, untagged_globals_, and v8::internal::value.
Referenced by ProcessImportedGlobal(), and ProcessImportedWasmGlobalObject().
Member Data Documentation
asmjs_memory_buffer_
MaybeDirectHandle<JSArrayBuffer> v8::internal::wasm::InstanceBuilder::asmjs_memory_buffer_ [private]
Definition at line 1236 of file module-instantiate.cc.
Referenced by Build_Phase1().
context_id_
v8::metrics::Recorder::ContextId v8::internal::wasm::InstanceBuilder::context_id_ [private]
Definition at line 1228 of file module-instantiate.cc.
Referenced by Build().
enabled_
const WasmEnabledFeatures v8::internal::wasm::InstanceBuilder::enabled_ [private]
Definition at line 1229 of file module-instantiate.cc.
ffi_
MaybeDirectHandle<JSReceiver> v8::internal::wasm::InstanceBuilder::ffi_ [private]
Definition at line 1235 of file module-instantiate.cc.
Referenced by LookupImport(), LookupImportAsm(), and SanitizeImports().
init_expr_zone_
Zone v8::internal::wasm::InstanceBuilder::init_expr_zone_ [private]
Definition at line 1251 of file module-instantiate.cc.
Referenced by InitGlobals(), LoadDataSegments(), LoadTableSegments(), and SetTableInitialValues().
isolate_
Isolate* v8::internal::wasm::InstanceBuilder::isolate_ [private]
Definition at line 1227 of file module-instantiate.cc.
Referenced by AllocateMemory(), Build(), Build_Phase1(), Build_Phase1_Infallible(), ConfigurePrototypes_Modular(), ExecuteStartFunction(), FinalizeExportsObject(), InitGlobals(), InitializeTags(), LoadDataSegments(), LoadTableSegments(), LookupImport(), LookupImportAsm(), ProcessExports(), ProcessImportedFunction(), ProcessImportedGlobal(), ProcessImportedMemories(), ProcessImportedTable(), ProcessImportedWasmGlobalObject(), SanitizeImports(), and SetTableInitialValues().
js_prototypes_setup_
std::optional<JSPrototypesSetup> v8::internal::wasm::InstanceBuilder::js_prototypes_setup_ [private]
Definition at line 1246 of file module-instantiate.cc.
Referenced by Build_Phase2(), ConfigurePrototypes_Modular(), and SanitizeImports().
module_
const WasmModule* const v8::internal::wasm::InstanceBuilder::module_ [private]
Definition at line 1230 of file module-instantiate.cc.
Referenced by AllocateMemory(), Build(), Build_Phase1(), Build_Phase1_Infallible(), Build_Phase2(), FinalizeExportsObject(), ImportName(), InitGlobals(), InstanceBuilder(), LoadDataSegments(), LoadTableSegments(), LookupImportAsm(), ProcessExports(), ProcessImportedFunction(), ProcessImportedGlobal(), ProcessImportedMemories(), ProcessImportedTable(), ProcessImportedWasmGlobalObject(), ProcessImports(), SanitizeImports(), SetTableInitialValues(), and WriteGlobalValue().
module_object_
DirectHandle<WasmModuleObject> v8::internal::wasm::InstanceBuilder::module_object_ [private]
Definition at line 1232 of file module-instantiate.cc.
Referenced by Build_Phase1(), ImportName(), LoadDataSegments(), ProcessExports(), ProcessImports(), and SanitizeImports().
sanitized_imports_
DirectHandleVector<Object> v8::internal::wasm::InstanceBuilder::sanitized_imports_ [private]
Definition at line 1244 of file module-instantiate.cc.
Referenced by InstanceBuilder(), ProcessExports(), ProcessImportedMemories(), ProcessImports(), and SanitizeImports().
shared_tagged_globals_
DirectHandle<FixedArray> v8::internal::wasm::InstanceBuilder::shared_tagged_globals_ [private]
Definition at line 1240 of file module-instantiate.cc.
Referenced by Build_Phase1(), and InitGlobals().
shared_tags_wrappers_
DirectHandleVector<WasmTagObject> v8::internal::wasm::InstanceBuilder::shared_tags_wrappers_ [private]
Definition at line 1242 of file module-instantiate.cc.
Referenced by Build_Phase1().
shared_trusted_data_
DirectHandle<WasmTrustedInstanceData> v8::internal::wasm::InstanceBuilder::shared_trusted_data_ [private]
Definition at line 1234 of file module-instantiate.cc.
Referenced by Build_Phase1(), Build_Phase1_Infallible(), Build_Phase2(), InitGlobals(), LoadDataSegments(), LoadTableSegments(), SetTableInitialValues(), and trusted_data().
shared_untagged_globals_
DirectHandle<JSArrayBuffer> v8::internal::wasm::InstanceBuilder::shared_untagged_globals_ [private]
Definition at line 1238 of file module-instantiate.cc.
Referenced by GetRawUntaggedGlobalPtr().
start_function_
DirectHandle<JSFunction> v8::internal::wasm::InstanceBuilder::start_function_ [private]
Definition at line 1243 of file module-instantiate.cc.
Referenced by Build_Phase1(), and ExecuteStartFunction().
tagged_globals_
DirectHandle<FixedArray> v8::internal::wasm::InstanceBuilder::tagged_globals_ [private]
Definition at line 1239 of file module-instantiate.cc.
Referenced by Build_Phase1(), InitGlobals(), and WriteGlobalValue().
tags_wrappers_
DirectHandleVector<WasmTagObject> v8::internal::wasm::InstanceBuilder::tags_wrappers_ [private]
Definition at line 1241 of file module-instantiate.cc.
Referenced by Build_Phase1(), ProcessExports(), and ProcessImports().
thrower_
ErrorThrower* v8::internal::wasm::InstanceBuilder::thrower_ [private]
Definition at line 1231 of file module-instantiate.cc.
Referenced by AllocateMemory(), Build(), Build_Phase1(), Build_Phase2(), ConfigurePrototypes_Modular(), InitGlobals(), LoadDataSegments(), LoadTableSegments(), LookupImport(), LookupImportAsm(), ProcessImportedFunction(), ProcessImportedGlobal(), ProcessImportedMemories(), ProcessImportedTable(), ProcessImportedWasmGlobalObject(), ProcessImports(), SanitizeImports(), and SetTableInitialValues().
trusted_data_
DirectHandle<WasmTrustedInstanceData> v8::internal::wasm::InstanceBuilder::trusted_data_ [private]
Definition at line 1233 of file module-instantiate.cc.
Referenced by Build(), Build_Phase1(), Build_Phase1_Infallible(), Build_Phase2(), InitGlobals(), InitializeTags(), LoadDataSegments(), LoadTableSegments(), ProcessExports(), ProcessImports(), and trusted_data().
untagged_globals_
DirectHandle<JSArrayBuffer> v8::internal::wasm::InstanceBuilder::untagged_globals_ [private]
Definition at line 1237 of file module-instantiate.cc.
Referenced by Build_Phase1(), GetRawUntaggedGlobalPtr(), and WriteGlobalValue().
well_known_imports_
std::vector<WellKnownImport> v8::internal::wasm::InstanceBuilder::well_known_imports_ [private]
Definition at line 1245 of file module-instantiate.cc.
Referenced by InstanceBuilder(), ProcessImportedFunction(), and ProcessImports().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-instantiate.cc