v8::internal::maglev::StoreInt32 Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreInt32 (uint64_t bitfield, int offset)
int offset () const
Input & object_input ()
Input & value_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::CanWrite()
static constexpr Base::InputTypes kInputTypes
static constexpr int kObjectIndex = 0
static constexpr int kValueIndex = 1
Private Types
using Base = FixedInputNodeT< 2, StoreInt32 >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
Definition at line 8949 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreInt32::Base = FixedInputNodeT<2, StoreInt32> [private]
Definition at line 8950 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreInt32()
v8::internal::maglev::StoreInt32::StoreInt32 (uint64_t bitfield, int offset) [inline], [explicit]
Definition at line 8953 of file maglev-ir.h.
      : Base(bitfield), offset_(offset) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::StoreInt32::GenerateCode (MaglevAssembler * , const ProcessingState &)
object_input()
Input& v8::internal::maglev::StoreInt32::object_input () [inline]
Definition at line 8964 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
int v8::internal::maglev::StoreInt32::offset () const [inline]
Definition at line 8960 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreInt32::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8229 of file maglev-ir.cc.
                                                                        {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::StoreInt32::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::StoreInt32::value_input () [inline]
Definition at line 8965 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreInt32::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kInt32}
Definition at line 8957 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::StoreInt32::kObjectIndex = 0 [static], [constexpr]
Definition at line 8962 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreInt32::kProperties = OpProperties::CanWrite() [static], [constexpr]
Definition at line 8956 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreInt32::kValueIndex = 1 [static], [constexpr]
Definition at line 8963 of file maglev-ir.h.
offset_
const int v8::internal::maglev::StoreInt32::offset_ [private]
Definition at line 8972 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc