v8::internal::ZoneConsumedPreparseData Class Reference
#include <preparse-data-impl.h>
Public Member Functions
ZoneConsumedPreparseData (Zone *zone, ZonePreparseData *data)
ZoneVectorWrapper GetScopeData () final
ProducedPreparseData * GetChildData (Zone *zone, int child_index) final
Private Attributes
ZonePreparseData * data_
ZoneVectorWrapper scope_data_wrapper_
Additional Inherited Members
Detailed Description
Definition at line 242 of file preparse-data-impl.h.
Constructor & Destructor Documentation
ZoneConsumedPreparseData()
v8::internal::ZoneConsumedPreparseData::ZoneConsumedPreparseData (Zone * zone, ZonePreparseData * data)
Definition at line 824 of file preparse-data.cc.
    : data_(data), scope_data_wrapper_(data_->byte_data()) {
  DCHECK(VerifyDataStart());
}
References v8::internal::DCHECK().
Member Function Documentation
GetChildData()
ProducedPreparseData * v8::internal::ZoneConsumedPreparseData::GetChildData (Zone * zone, int child_index) [final], [virtual]
Implements v8::internal::BaseConsumedPreparseData< ZoneVectorWrapper >.
Definition at line 834 of file preparse-data.cc.
                                                                              {
  CHECK_GT(data_->children_length(), child_index);
  ZonePreparseData* child_data = data_->get_child(child_index);
  if (child_data == nullptr) return nullptr;
  return ProducedPreparseData::For(child_data, zone);
}
References CHECK_GT, v8::internal::ZonePreparseData::children_length(), data_, v8::internal::ProducedPreparseData::For(), and v8::internal::ZonePreparseData::get_child().
GetScopeData()
ZoneVectorWrapper v8::internal::ZoneConsumedPreparseData::GetScopeData () [final], [virtual]
Implements v8::internal::BaseConsumedPreparseData< ZoneVectorWrapper >.
Definition at line 830 of file preparse-data.cc.
                                                         {
  return scope_data_wrapper_;
}
References scope_data_wrapper_.
Member Data Documentation
data_
ZonePreparseData* v8::internal::ZoneConsumedPreparseData::data_ [private]
Definition at line 251 of file preparse-data-impl.h.
Referenced by GetChildData().
scope_data_wrapper_
ZoneVectorWrapper v8::internal::ZoneConsumedPreparseData::scope_data_wrapper_ [private]
Definition at line 252 of file preparse-data-impl.h.
Referenced by GetScopeData().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparse-data-impl.h
/mnt/V8SourceCode/src/parsing/preparse-data.cc