v8::internal::compiler::EffectGraphReducer Class Reference
#include <escape-analysis.h>
Classes
struct NodeState
class Reduction
Public Member Functions
EffectGraphReducer (TFGraph *graph, std::function< void(Node *, Reduction *)> reduce, TickCounter *tick_counter, Zone *zone)
void ReduceGraph ()
void Revisit (Node *node)
void AddRoot (Node *node)
bool Complete ()
TickCounter * tick_counter () const
Private Types
enum class State : uint8_t { kUnvisited = 0
, kRevisit
, kOnStack
, kVisited
 }
Private Member Functions
void ReduceFrom (Node *node)
Private Attributes
const uint8_t kNumStates = static_cast<uint8_t>(State::kVisited) + 1
TFGraph * graph_
NodeMarker< State > state_
ZoneStack< Node * > revisit_
ZoneStack< NodeState > stack_
std::function< void(Node *, Reduction *)> reduce_
TickCounter *const tick_counter_
Detailed Description
Definition at line 29 of file escape-analysis.h.
Member Enumeration Documentation
State
enum v8::internal::compiler::EffectGraphReducer::State : uint8_t [strong], [private]
Enumerator
kUnvisited
kRevisit
kOnStack
kVisited
Definition at line 71 of file escape-analysis.h.
: uint8_t { kUnvisited = 0, kRevisit, kOnStack, kVisited };
Constructor & Destructor Documentation
EffectGraphReducer()
v8::internal::compiler::EffectGraphReducer::EffectGraphReducer (TFGraph * graph, std::function< void(Node *, Reduction *)> reduce, TickCounter * tick_counter, Zone * zone)
Definition at line 326 of file escape-analysis.cc.
    : graph_(graph),
      state_(graph, kNumStates),
      revisit_(zone),
      stack_(zone),
      reduce_(std::move(reduce)),
      tick_counter_(tick_counter) {}
Member Function Documentation
AddRoot()
void v8::internal::compiler::EffectGraphReducer::AddRoot (Node * node) [inline]
Definition at line 55 of file escape-analysis.h.
                           {
    DCHECK_EQ(State::kUnvisited, state_.Get(node));
    state_.Set(node, State::kRevisit);
    revisit_.push(node);
  }
References DCHECK_EQ, kRevisit, kUnvisited, revisit_, and state_.
Referenced by v8::internal::compiler::VariableTracker::MergeInputs().
Complete()
bool v8::internal::compiler::EffectGraphReducer::Complete () [inline]
Definition at line 61 of file escape-analysis.h.
{ return stack_.empty() && revisit_.empty(); }
References revisit_, and stack_.
ReduceFrom()
void v8::internal::compiler::EffectGraphReducer::ReduceFrom (Node * node) [private]
Definition at line 336 of file escape-analysis.cc.
                                              {
  // Perform DFS and eagerly trigger revisitation as soon as possible.
  // A stack element {node, i} indicates that input i of node should be visited
  // next.
  DCHECK(stack_.empty());
  stack_.push({node, 0});
  while (!stack_.empty()) {
    tick_counter_->TickAndMaybeEnterSafepoint();
    Node* current = stack_.top().node;
    int& input_index = stack_.top().input_index;
    if (input_index < current->InputCount()) {
      Node* input = current->InputAt(input_index);
      input_index++;
      switch (state_.Get(input)) {
        case State::kVisited:
          // The input is already reduced.
          break;
        case State::kOnStack:
          // The input is on the DFS stack right now, so it will be revisited
          // later anyway.
          break;
        case State::kUnvisited:
        case State::kRevisit: {
          state_.Set(input, State::kOnStack);
          stack_.push({input, 0});
          break;
        }
      }
    } else {
      stack_.pop();
      Reduction reduction;
      reduce_(current, &reduction);
      for (Edge edge : current->use_edges()) {
        // Mark uses for revisitation.
        Node* use = edge.from();
        if (NodeProperties::IsEffectEdge(edge)) {
          if (reduction.effect_changed()) Revisit(use);
        } else {
          if (reduction.value_changed()) Revisit(use);
        }
      }
      state_.Set(current, State::kVisited);
      // Process the revisitation buffer immediately. This improves performance
      // of escape analysis. Using a stack for {revisit_} reverses the order in
      // which the revisitation happens. This also seems to improve performance.
      while (!revisit_.empty()) {
        Node* revisit = revisit_.top();
        if (state_.Get(revisit) == State::kRevisit) {
          state_.Set(revisit, State::kOnStack);
          stack_.push({revisit, 0});
        }
        revisit_.pop();
      }
    }
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::EffectGraphReducer::Reduction::effect_changed(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeProperties::IsEffectEdge(), kOnStack, kRevisit, kUnvisited, kVisited, reduce_, Revisit(), revisit_, stack_, state_, tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), use(), v8::internal::compiler::Node::use_edges(), and v8::internal::compiler::EffectGraphReducer::Reduction::value_changed().
Referenced by ReduceGraph().
ReduceGraph()
void v8::internal::compiler::EffectGraphReducer::ReduceGraph () [inline]
Definition at line 47 of file escape-analysis.h.
{ ReduceFrom(graph_->end()); }
References v8::internal::compiler::TFGraph::end(), graph_, and ReduceFrom().
Revisit()
void v8::internal::compiler::EffectGraphReducer::Revisit (Node * node)
Definition at line 393 of file escape-analysis.cc.
                                           {
  if (state_.Get(node) == State::kVisited) {
    TRACE(" Queueing for revisit: %s#%d\n", node->op()->mnemonic(),
          node->id());
    state_.Set(node, State::kRevisit);
    revisit_.push(node);
  }
}
References v8::internal::compiler::Node::id(), kRevisit, kVisited, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), revisit_, state_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::VariableTracker::MergeInputs(), ReduceFrom(), and v8::internal::compiler::Dependable::RevisitDependants().
tick_counter()
TickCounter* v8::internal::compiler::EffectGraphReducer::tick_counter () const [inline]
Definition at line 63 of file escape-analysis.h.
{ return tick_counter_; }
References tick_counter_.
Member Data Documentation
graph_
TFGraph* v8::internal::compiler::EffectGraphReducer::graph_ [private]
Definition at line 73 of file escape-analysis.h.
Referenced by ReduceGraph().
kNumStates
const uint8_t v8::internal::compiler::EffectGraphReducer::kNumStates = static_cast<uint8_t>(State::kVisited) + 1 [private]
Definition at line 72 of file escape-analysis.h.
reduce_
std::function<void(Node*, Reduction*)> v8::internal::compiler::EffectGraphReducer::reduce_ [private]
Definition at line 77 of file escape-analysis.h.
Referenced by ReduceFrom().
revisit_
ZoneStack<Node*> v8::internal::compiler::EffectGraphReducer::revisit_ [private]
Definition at line 75 of file escape-analysis.h.
Referenced by AddRoot(), Complete(), ReduceFrom(), and Revisit().
stack_
ZoneStack<NodeState> v8::internal::compiler::EffectGraphReducer::stack_ [private]
Definition at line 76 of file escape-analysis.h.
Referenced by Complete(), and ReduceFrom().
state_
NodeMarker<State> v8::internal::compiler::EffectGraphReducer::state_ [private]
Definition at line 74 of file escape-analysis.h.
Referenced by AddRoot(), ReduceFrom(), and Revisit().
tick_counter_
TickCounter* const v8::internal::compiler::EffectGraphReducer::tick_counter_ [private]
Definition at line 78 of file escape-analysis.h.
Referenced by ReduceFrom(), and tick_counter().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/escape-analysis.h
/mnt/V8SourceCode/src/compiler/escape-analysis.cc