v8::SnapshotCreator Class Reference
Helper class to create a snapshot data blob.
#include <v8-snapshot.h>
Public Types
enum class FunctionCodeHandling { kClear
, kKeep
 }
Public Member Functions
Use the version that passes CreateParams instead SnapshotCreator (Isolate *isolate, const intptr_t *external_references=nullptr, const StartupData *existing_blob=nullptr, bool owns_isolate=true)
Initialize and enter an isolate, and set it up for serialization.
Use the version that passes CreateParams instead SnapshotCreator (const intptr_t *external_references=nullptr, const StartupData *existing_blob=nullptr)
Create and enter an isolate, and set it up for serialization.
SnapshotCreator (const v8::Isolate::CreateParams &params)
Creates an Isolate for serialization and enters it.
SnapshotCreator (v8::Isolate *isolate, const v8::Isolate::CreateParams &params)
Initializes an Isolate for serialization and enters it.
~SnapshotCreator ()
Destroy the snapshot creator, and exit and dispose of the Isolate associated with it.
Isolate * GetIsolate ()
void SetDefaultContext (Local< Context > context, SerializeInternalFieldsCallback internal_fields_serializer=SerializeInternalFieldsCallback(), SerializeContextDataCallback context_data_serializer=SerializeContextDataCallback(), SerializeAPIWrapperCallback api_wrapper_serializer=SerializeAPIWrapperCallback())
Set the default context to be included in the snapshot blob.
size_t AddContext (Local< Context > context, SerializeInternalFieldsCallback internal_fields_serializer=SerializeInternalFieldsCallback(), SerializeContextDataCallback context_data_serializer=SerializeContextDataCallback(), SerializeAPIWrapperCallback api_wrapper_serializer=SerializeAPIWrapperCallback())
Add additional context to be included in the snapshot blob.
template<class T >
size_t AddData (Local< Context > context, Local< T > object)
Attach arbitrary V8::Data to the context snapshot, which can be retrieved via Context::GetDataFromSnapshotOnce after deserialization.
template<class T >
size_t AddData (Local< T > object)
Attach arbitrary V8::Data to the isolate snapshot, which can be retrieved via Isolate::GetDataFromSnapshotOnce after deserialization.
StartupData CreateBlob (FunctionCodeHandling function_code_handling)
Created a snapshot data blob.
SnapshotCreator (const SnapshotCreator &)=delete
void operator= (const SnapshotCreator &)=delete
Private Member Functions
size_t AddData (Local< Context > context, internal::Address object)
size_t AddData (internal::Address object)
Private Attributes
internal::SnapshotCreatorImpl * impl_
Friends
class internal::SnapshotCreatorImpl
Detailed Description
Helper class to create a snapshot data blob.
The Isolate used by a SnapshotCreator is owned by it, and will be entered and exited by the constructor and destructor, respectively; The destructor will also destroy the Isolate. Experimental language features, including those available by default, are not available while creating a snapshot.
Definition at line 135 of file v8-snapshot.h.
Member Enumeration Documentation
FunctionCodeHandling
enum v8::SnapshotCreator::FunctionCodeHandling [strong]
Enumerator
kClear
kKeep
Definition at line 137 of file v8-snapshot.h.
{ kClear, kKeep };
Constructor & Destructor Documentation
SnapshotCreator() [1/5]
v8::SnapshotCreator::SnapshotCreator (Isolate * isolate, const intptr_t * external_references = nullptr, const StartupData * existing_blob = nullptr, bool owns_isolate = true) [explicit]
Initialize and enter an isolate, and set it up for serialization.
The isolate is either created from scratch or from an existing snapshot. The caller keeps ownership of the argument snapshot.
Parameters
existing_blob existing snapshot from which to create this one.
external_references a null-terminated array of external references that must be equivalent to CreateParams::external_references.
owns_isolate whether this SnapshotCreator should call v8::Isolate::Dispose() during its destructor.
Definition at line 355 of file api.cc.
    : impl_(new i::SnapshotCreatorImpl(
          reinterpret_cast<i::Isolate*>(v8_isolate), external_references,
          existing_snapshot, owns_isolate)) {}
SnapshotCreator() [2/5]
v8::SnapshotCreator::SnapshotCreator (const intptr_t * external_references = nullptr, const StartupData * existing_blob = nullptr) [explicit]
Create and enter an isolate, and set it up for serialization.
The isolate is either created from scratch or from an existing snapshot. The caller keeps ownership of the argument snapshot.
Parameters
existing_blob existing snapshot from which to create this one.
external_references a null-terminated array of external references that must be equivalent to CreateParams::external_references.
Definition at line 363 of file api.cc.
    : SnapshotCreator(nullptr, external_references, existing_snapshot) {}
SnapshotCreator() [3/5]
v8::SnapshotCreator::SnapshotCreator (const v8::Isolate::CreateParams & params) [explicit]
Creates an Isolate for serialization and enters it.
The creator fully owns the Isolate and will invoke v8::Isolate::Dispose() during destruction.
Parameters
params The parameters to initialize the Isolate for. Details:
params.external_references are expected to be a null-terminated array of external references.
params.existing_blob is an optional snapshot blob from which can be used to initialize the new blob.
Definition at line 367 of file api.cc.
    : impl_(new i::SnapshotCreatorImpl(params)) {}
SnapshotCreator() [4/5]
v8::SnapshotCreator::SnapshotCreator (v8::Isolate * isolate, const v8::Isolate::CreateParams & params)
Initializes an Isolate for serialization and enters it.
The creator does not own the Isolate but merely initialize it properly.
Parameters
isolate The isolate that was allocated by IsolateAllocate()~.
params The parameters to initialize the Isolate for. Details:
params.external_references are expected to be a null-terminated array of external references.
params.existing_blob is an optional snapshot blob from which can be used to initialize the new blob.
Definition at line 370 of file api.cc.
    : impl_(new i::SnapshotCreatorImpl(reinterpret_cast<i::Isolate*>(isolate),
                                       params)) {}
 SnapshotCreator()
v8::SnapshotCreator::~SnapshotCreator ()
Destroy the snapshot creator, and exit and dispose of the Isolate associated with it.
Definition at line 375 of file api.cc.
                                  {
  DCHECK_NOT_NULL(impl_);
  delete impl_;
}
References DCHECK_NOT_NULL, and impl_.
SnapshotCreator() [5/5]
v8::SnapshotCreator::SnapshotCreator (const SnapshotCreator &) [delete]
Member Function Documentation
AddContext()
size_t v8::SnapshotCreator::AddContext (Local< Context > context, SerializeInternalFieldsCallback internal_fields_serializer = SerializeInternalFieldsCallback(), SerializeContextDataCallback context_data_serializer = SerializeContextDataCallback(), SerializeAPIWrapperCallback api_wrapper_serializer = SerializeAPIWrapperCallback())
Add additional context to be included in the snapshot blob.
The snapshot will include the global proxy.
Parameters
internal_fields_serializer Similar to internal_fields_serializer in SetDefaultContext() but only applies to the context being added.
context_data_serializer Similar to context_data_serializer in SetDefaultContext() but only applies to the context being added.
api_wrapper_serializer Similar to api_wrapper_serializer in SetDefaultContext() but only applies to the context being added.
Definition at line 396 of file api.cc.
                                                        {
  return impl_->AddContext(
      Utils::OpenDirectHandle(*context),
      i::SerializeEmbedderFieldsCallback(internal_fields_serializer,
                                         context_data_serializer,
                                         api_wrapper_serializer));
}
References v8::internal::SnapshotCreatorImpl::AddContext(), impl_, and v8::Utils::OpenDirectHandle().
AddData() [1/4]
size_t v8::SnapshotCreator::AddData (internal::Address object) [private]
Definition at line 408 of file api.cc.
                                               {
  return impl_->AddData(object);
}
References v8::internal::SnapshotCreatorImpl::AddData(), and impl_.
AddData() [2/4]
size_t v8::SnapshotCreator::AddData (Local< Context > context, internal::Address object) [private]
Definition at line 412 of file api.cc.
                                                                       {
  return impl_->AddData(Utils::OpenDirectHandle(*context), object);
}
References v8::internal::SnapshotCreatorImpl::AddData(), impl_, and v8::Utils::OpenDirectHandle().
AddData() [3/4]
template<class T >
size_t v8::SnapshotCreator::AddData (Local< Context > context, Local< T > object) [inline]
Attach arbitrary V8::Data to the context snapshot, which can be retrieved via Context::GetDataFromSnapshotOnce after deserialization.
This data does not survive when a new snapshot is created from an existing snapshot.
Returns
the index for retrieval.
Definition at line 291 of file v8-snapshot.h.
                                                                       {
  return AddData(context, internal::ValueHelper::ValueAsAddress(*object));
}
References v8::internal::ValueHelper::ValueAsAddress().
AddData() [4/4]
template<class T >
size_t v8::SnapshotCreator::AddData (Local< T > object) [inline]
Attach arbitrary V8::Data to the isolate snapshot, which can be retrieved via Isolate::GetDataFromSnapshotOnce after deserialization.
This data does not survive when a new snapshot is created from an existing snapshot.
Returns
the index for retrieval.
Definition at line 296 of file v8-snapshot.h.
                                               {
  return AddData(internal::ValueHelper::ValueAsAddress(*object));
}
References v8::internal::ValueHelper::ValueAsAddress().
CreateBlob()
StartupData v8::SnapshotCreator::CreateBlob (SnapshotCreator::FunctionCodeHandling function_code_handling)
Created a snapshot data blob.
This must not be called from within a handle scope.
Parameters
function_code_handling whether to include compiled function code in the snapshot.
Returns
{ nullptr, 0 } on failure, and a startup snapshot on success. The caller acquires ownership of the data array in the return value.
Definition at line 416 of file api.cc.
                                                                {
  return impl_->CreateBlob(function_code_handling);
}
References v8::internal::SnapshotCreatorImpl::CreateBlob(), and impl_.
Referenced by v8::internal::WarmUpSnapshotDataBlobInternal().
GetIsolate()
Isolate * v8::SnapshotCreator::GetIsolate ()
Returns
the isolate prepared by the snapshot creator.
Definition at line 380 of file api.cc.
                                     {
  return reinterpret_cast<v8::Isolate*>(impl_->isolate());
}
References impl_, and v8::internal::SnapshotCreatorImpl::isolate().
Referenced by v8::internal::WarmUpSnapshotDataBlobInternal().
operator=()
void v8::SnapshotCreator::operator= (const SnapshotCreator &) [delete]
SetDefaultContext()
void v8::SnapshotCreator::SetDefaultContext (Local< Context > context, SerializeInternalFieldsCallback internal_fields_serializer = SerializeInternalFieldsCallback(), SerializeContextDataCallback context_data_serializer = SerializeContextDataCallback(), SerializeAPIWrapperCallback api_wrapper_serializer = SerializeAPIWrapperCallback())
Set the default context to be included in the snapshot blob.
The snapshot will not contain the global proxy, and we expect one or a global object template to create one, to be provided upon deserialization.
Parameters
internal_fields_serializer An optional callback used to serialize internal pointer fields set by v8::Object::SetAlignedPointerInInternalField().
context_data_serializer An optional callback used to serialize context embedder data set by v8::Context::SetAlignedPointerInEmbedderData().
api_wrapper_serializer An optional callback used to serialize API wrapper references set via v8::Object::Wrap().
Definition at line 384 of file api.cc.
                                                        {
  impl_->SetDefaultContext(
      Utils::OpenDirectHandle(*context),
      i::SerializeEmbedderFieldsCallback(internal_fields_serializer,
                                         context_data_serializer,
                                         api_wrapper_serializer));
}
References impl_, v8::Utils::OpenDirectHandle(), and v8::internal::SnapshotCreatorImpl::SetDefaultContext().
Referenced by v8::internal::WarmUpSnapshotDataBlobInternal().
Friends And Related Function Documentation
internal::SnapshotCreatorImpl
friend class internal::SnapshotCreatorImpl [friend]
Definition at line 287 of file v8-snapshot.h.
Member Data Documentation
impl_
internal::SnapshotCreatorImpl* v8::SnapshotCreator::impl_ [private]
Definition at line 286 of file v8-snapshot.h.
Referenced by AddContext(), AddData(), CreateBlob(), v8::internal::SnapshotCreatorImpl::FromSnapshotCreator(), GetIsolate(), SetDefaultContext(), and ~SnapshotCreator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-snapshot.h
/mnt/V8SourceCode/src/api/api.cc