v8::internal::FieldIndex Class Reference
#include <field-index.h>
Public Types
enum Encoding { kTagged
, kDouble
, kWord32
 }
Public Member Functions
FieldIndex ()
int GetLoadByFieldIndex () const
bool is_inobject () const
bool is_double () const
int offset () const
uint64_t bit_field () const
int index () const
int outobject_array_index () const
int property_index () const
int GetFieldAccessStubKey () const
bool operator== (FieldIndex const &other) const
bool operator!= (FieldIndex const &other) const
Static Public Member Functions
static FieldIndex ForPropertyIndex (Tagged< Map > map, int index, Representation representation=Representation::Tagged())
static FieldIndex ForInObjectOffset (int offset, Encoding encoding)
static FieldIndex ForSmiLoadHandler (Tagged< Map > map, int32_t handler)
static FieldIndex ForDescriptor (Tagged< Map > map, InternalIndex descriptor_index)
static FieldIndex ForDescriptor (PtrComprCageBase cage_base, Tagged< Map > map, InternalIndex descriptor_index)
static FieldIndex ForDetails (Tagged< Map > map, PropertyDetails details)
Private Types
using OffsetBits = base::BitField64< int, 0, kOffsetBitsSize >
using IsInObjectBits = OffsetBits::Next< bool, 1 >
using EncodingBits = IsInObjectBits::Next< Encoding, 2 >
using InObjectPropertyBits = EncodingBits::Next< int, kDescriptorIndexBitCount >
using FirstInobjectPropertyOffsetBits = InObjectPropertyBits::Next< int, kFirstInobjectPropertyOffsetBitCount >
Private Member Functions
FieldIndex (bool is_inobject, int offset, Encoding encoding, int inobject_properties, int first_inobject_property_offset)
int first_inobject_property_offset () const
Static Private Member Functions
static Encoding FieldEncoding (Representation representation)
Private Attributes
uint64_t bit_field_
Static Private Attributes
static const int kOffsetBitsSize
Detailed Description
Definition at line 22 of file field-index.h.
Member Typedef Documentation
EncodingBits
using v8::internal::FieldIndex::EncodingBits = IsInObjectBits::Next<Encoding, 2> [private]
Definition at line 120 of file field-index.h.
FirstInobjectPropertyOffsetBits
using v8::internal::FieldIndex::FirstInobjectPropertyOffsetBits = InObjectPropertyBits::Next<int, kFirstInobjectPropertyOffsetBitCount> [private]
Definition at line 125 of file field-index.h.
InObjectPropertyBits
using v8::internal::FieldIndex::InObjectPropertyBits = EncodingBits::Next<int, kDescriptorIndexBitCount> [private]
Definition at line 122 of file field-index.h.
IsInObjectBits
using v8::internal::FieldIndex::IsInObjectBits = OffsetBits::Next<bool, 1> [private]
Definition at line 119 of file field-index.h.
OffsetBits
using v8::internal::FieldIndex::OffsetBits = base::BitField64<int, 0, kOffsetBitsSize> [private]
Definition at line 118 of file field-index.h.
Member Enumeration Documentation
Encoding
enum v8::internal::FieldIndex::Encoding
Enumerator
kTagged
kDouble
kWord32
Definition at line 24 of file field-index.h.
{ kTagged, kDouble, kWord32 };
Constructor & Destructor Documentation
FieldIndex() [1/2]
v8::internal::FieldIndex::FieldIndex () [inline]
Definition at line 26 of file field-index.h.
: bit_field_(0) {}
Referenced by ForInObjectOffset(), ForPropertyIndex(), and ForSmiLoadHandler().
FieldIndex() [2/2]
v8::internal::FieldIndex::FieldIndex (bool is_inobject, int offset, Encoding encoding, int inobject_properties, int first_inobject_property_offset) [inline], [private]
Definition at line 82 of file field-index.h.
                                                                          {
    DCHECK(IsAligned(first_inobject_property_offset, kTaggedSize));
    bit_field_ = IsInObjectBits::encode(is_inobject) |
                 EncodingBits::encode(encoding) |
                 FirstInobjectPropertyOffsetBits::encode(
                     first_inobject_property_offset) |
                 OffsetBits::encode(offset) |
                 InObjectPropertyBits::encode(inobject_properties);
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), first_inobject_property_offset(), is_inobject(), IsAligned(), v8::internal::kTaggedSize, and offset().
Member Function Documentation
bit_field()
uint64_t v8::internal::FieldIndex::bit_field () const [inline]
Definition at line 48 of file field-index.h.
{ return bit_field_; }
References bit_field_.
FieldEncoding()
static Encoding v8::internal::FieldIndex::FieldEncoding (Representation representation) [inline], [static], [private]
Definition at line 93 of file field-index.h.
                                                               {
    switch (representation.kind()) {
      case Representation::kNone:
      case Representation::kSmi:
      case Representation::kHeapObject:
      case Representation::kTagged:
        return kTagged;
      case Representation::kDouble:
        return kDouble;
      default:
        break;
    }
    PrintF("%s\n", representation.Mnemonic());
    UNREACHABLE();
    return kTagged;
  }
References kDouble, v8::internal::Representation::kDouble, v8::internal::Representation::kHeapObject, v8::internal::Representation::kind(), v8::internal::Representation::kNone, v8::internal::Representation::kSmi, kTagged, v8::internal::Representation::kTagged, v8::internal::Representation::Mnemonic(), v8::internal::PrintF(), and v8::internal::UNREACHABLE().
Referenced by ForPropertyIndex().
first_inobject_property_offset()
int v8::internal::FieldIndex::first_inobject_property_offset () const [inline], [private]
Definition at line 110 of file field-index.h.
                                             {
    return FirstInobjectPropertyOffsetBits::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by FieldIndex(), outobject_array_index(), and property_index().
ForDescriptor() [1/2]
FieldIndex v8::internal::FieldIndex::ForDescriptor (PtrComprCageBase cage_base, Tagged< Map > map, InternalIndex descriptor_index) [inline], [static]
Definition at line 91 of file field-index-inl.h.
                                                                     {
  PropertyDetails details = map->instance_descriptors(cage_base, kRelaxedLoad)
                                ->GetDetails(descriptor_index);
  return ForDetails(map, details);
}
References ForDetails(), and v8::kRelaxedLoad.
ForDescriptor() [2/2]
FieldIndex v8::internal::FieldIndex::ForDescriptor (Tagged< Map > map, InternalIndex descriptor_index) [inline], [static]
Definition at line 85 of file field-index-inl.h.
                                                                     {
  PtrComprCageBase cage_base = GetPtrComprCageBase(map);
  return ForDescriptor(cage_base, map, descriptor_index);
}
References v8::internal::GetPtrComprCageBase().
Referenced by v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::LookupIterator::CompareAndSwapDataValue(), v8::internal::TranslatedState::EnsureJSObjectAllocated(), v8::internal::TranslatedState::EnsurePropertiesAllocatedAndMarked(), v8::internal::compiler::MapRef::GetFieldIndexFor(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::Factory::NewJSModuleNamespace(), v8::internal::Factory::NewJSSharedArray(), v8::internal::StringStream::PrintUsingMap(), v8::internal::LookupIterator::SwapDataValue(), and v8::internal::LookupIterator::WriteDataValue().
ForDetails()
FieldIndex v8::internal::FieldIndex::ForDetails (Tagged< Map > map, PropertyDetails details) [inline], [static]
Definition at line 99 of file field-index-inl.h.
                                                                          {
  int field_index = details.field_index();
  return ForPropertyIndex(map, field_index, details.representation());
}
References v8::internal::PropertyDetails::field_index(), ForPropertyIndex(), and v8::internal::PropertyDetails::representation().
Referenced by v8::internal::JSObject::AllocateStorageForMap(), v8::internal::LookupIterator::CanStayConst(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::LookupIterator::FetchValue(), ForDescriptor(), v8::internal::LookupIterator::GetDataValue(), v8::internal::LookupIterator::GetFieldIndex(), v8::internal::FieldStatsCollector::GetInobjectFieldStats(), v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::JsonStringifier::SerializeJSObject(), v8::internal::JSObject::SlowReverseLookup(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), v8::internal::Genesis::TransferNamedProperties(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), and v8::internal::ValueSerializer::WriteJSObject().
ForInObjectOffset()
FieldIndex v8::internal::FieldIndex::ForInObjectOffset (int offset, Encoding encoding) [inline], [static]
Definition at line 20 of file field-index-inl.h.
                                                                      {
  DCHECK_IMPLIES(encoding == kWord32, IsAligned(offset, kInt32Size));
  DCHECK_IMPLIES(encoding == kTagged, IsAligned(offset, kTaggedSize));
  DCHECK_IMPLIES(encoding == kDouble, IsAligned(offset, kDoubleSize));
  return FieldIndex(true, offset, encoding, 0, 0);
}
References DCHECK_IMPLIES, FieldIndex(), IsAligned(), kDouble, v8::internal::kDoubleSize, v8::internal::kInt32Size, kTagged, v8::internal::kTaggedSize, kWord32, and offset().
Referenced by v8::internal::CheckForName(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
ForPropertyIndex()
FieldIndex v8::internal::FieldIndex::ForPropertyIndex (Tagged< Map > map, int index, Representation representation = Representation::Tagged()) [inline], [static]
Definition at line 44 of file field-index-inl.h.
                                                                       {
  DCHECK(map->instance_type() >= FIRST_NONSTRING_TYPE);
  int inobject_properties = map->GetInObjectProperties();
  bool is_inobject = property_index < inobject_properties;
  int first_inobject_offset;
  int offset;
  if (is_inobject) {
    first_inobject_offset = map->GetInObjectPropertyOffset(0);
    offset = map->GetInObjectPropertyOffset(property_index);
  } else {
    first_inobject_offset = OFFSET_OF_DATA_START(FixedArray);
    property_index -= inobject_properties;
    offset = PropertyArray::OffsetOfElementAt(property_index);
  }
  Encoding encoding = FieldEncoding(representation);
  return FieldIndex(is_inobject, offset, encoding, inobject_properties,
                    first_inobject_offset);
}
References v8::internal::DCHECK(), FieldEncoding(), FieldIndex(), v8::internal::FIRST_NONSTRING_TYPE, is_inobject(), offset(), OFFSET_OF_DATA_START, v8::internal::PropertyArray::OffsetOfElementAt(), and property_index().
Referenced by v8::internal::JSObject::AllocateStorageForMap(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), ForDetails(), v8::internal::anonymous_namespace{call-site-info.cc}::InferMethodNameFromFastObject(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::DictionaryTemplateInfo::NewInstance(), and v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk().
ForSmiLoadHandler()
FieldIndex v8::internal::FieldIndex::ForSmiLoadHandler (Tagged< Map > map, int32_t handler) [inline], [static]
Definition at line 27 of file field-index-inl.h.
                                                                         {
  DCHECK_EQ(LoadHandler::KindBits::decode(handler), LoadHandler::Kind::kField);
  bool is_inobject = LoadHandler::IsInobjectBits::decode(handler);
  int inobject_properties = map->GetInObjectProperties();
  int first_inobject_offset;
  if (is_inobject) {
    first_inobject_offset = map->GetInObjectPropertyOffset(0);
  } else {
    first_inobject_offset = OFFSET_OF_DATA_START(FixedArray);
  }
  return FieldIndex(
      is_inobject, LoadHandler::FieldIndexBits::decode(handler) * kTaggedSize,
      LoadHandler::IsDoubleBits::decode(handler) ? kDouble : kTagged,
      inobject_properties, first_inobject_offset);
}
References DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), FieldIndex(), is_inobject(), kDouble, v8::internal::LoadHandler::kField, kTagged, v8::internal::kTaggedSize, and OFFSET_OF_DATA_START.
GetFieldAccessStubKey()
int v8::internal::FieldIndex::GetFieldAccessStubKey () const [inline]
Definition at line 71 of file field-index.h.
                                    {
    return bit_field_ &
           (IsInObjectBits::kMask | EncodingBits::kMask | OffsetBits::kMask);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::kMask.
Referenced by v8::internal::compiler::PropertyAccessInfo::Merge().
GetLoadByFieldIndex()
int v8::internal::FieldIndex::GetLoadByFieldIndex () const [inline]
Definition at line 67 of file field-index-inl.h.
                                          {
  // For efficiency, the LoadByFieldIndex instruction takes an index that is
  // optimized for quick access. If the property is inline, the index is
  // positive. If it's out-of-line, the encoded index is -raw_index - 1 to
  // disambiguate the zero out-of-line index from the zero inobject case.
  // The index itself is shifted up by one bit, the lower-most bit
  // signifying if the field is a mutable double box (1) or not (0).
  int result = index();
  if (is_inobject()) {
    result -= JSObject::kHeaderSize / kTaggedSize;
  } else {
    result -= OFFSET_OF_DATA_START(FixedArray) / kTaggedSize;
    result = -result - 1;
  }
  result = static_cast<uint32_t>(result) << 1;
  return is_double() ? (result | 1) : result;
}
References index(), is_double(), is_inobject(), v8::internal::kTaggedSize, OFFSET_OF_DATA_START, and v8::base::internal::result.
Referenced by v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache().
index()
int v8::internal::FieldIndex::index () const [inline]
Definition at line 51 of file field-index.h.
                    {
    DCHECK(IsAligned(offset(), kTaggedSize));
    return offset() / kTaggedSize;
  }
References v8::internal::DCHECK(), IsAligned(), v8::internal::kTaggedSize, and offset().
Referenced by GetLoadByFieldIndex(), v8::internal::LoadHandler::LoadField(), outobject_array_index(), property_index(), and v8::internal::StoreHandler::StoreField().
is_double()
bool v8::internal::FieldIndex::is_double () const [inline]
Definition at line 44 of file field-index.h.
{ return EncodingBits::decode(bit_field_) == kDouble; }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), and kDouble.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::LookupIterator::FetchValue(), GetLoadByFieldIndex(), v8::internal::LoadHandler::LoadField(), and v8::internal::JSObject::SlowReverseLookup().
is_inobject()
bool v8::internal::FieldIndex::is_inobject () const [inline]
Definition at line 42 of file field-index.h.
{ return IsInObjectBits::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::LookupIterator::FetchValue(), FieldIndex(), ForPropertyIndex(), ForSmiLoadHandler(), GetLoadByFieldIndex(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::maglev::MaglevAssembler::LoadDataField(), v8::internal::LoadHandler::LoadField(), outobject_array_index(), property_index(), v8::internal::StoreHandler::StoreField(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
offset()
int v8::internal::FieldIndex::offset () const [inline]
Definition at line 46 of file field-index.h.
{ return OffsetBits::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), FieldIndex(), ForInObjectOffset(), ForPropertyIndex(), index(), v8::internal::maglev::MaglevAssembler::LoadDataField(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
operator!=()
bool v8::internal::FieldIndex::operator!= (FieldIndex const & other) const [inline]
Definition at line 79 of file field-index.h.
{ return !(*this == other); }
operator==()
bool v8::internal::FieldIndex::operator== (FieldIndex const & other) const [inline]
Definition at line 76 of file field-index.h.
                                                 {
    return bit_field_ == other.bit_field_;
  }
References bit_field_.
outobject_array_index()
int v8::internal::FieldIndex::outobject_array_index () const [inline]
Definition at line 56 of file field-index.h.
                                    {
    DCHECK(!is_inobject());
    return index() - first_inobject_property_offset() / kTaggedSize;
  }
References v8::internal::DCHECK(), first_inobject_property_offset(), index(), is_inobject(), and v8::internal::kTaggedSize.
Referenced by v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap().
property_index()
int v8::internal::FieldIndex::property_index () const [inline]
Definition at line 63 of file field-index.h.
                             {
    int result = index() - first_inobject_property_offset() / kTaggedSize;
    if (!is_inobject()) {
      result += InObjectPropertyBits::decode(bit_field_);
    }
    return result;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), first_inobject_property_offset(), index(), is_inobject(), v8::internal::kTaggedSize, and v8::base::internal::result.
Referenced by ForPropertyIndex(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
Member Data Documentation
bit_field_
uint64_t v8::internal::FieldIndex::bit_field_ [private]
Definition at line 129 of file field-index.h.
Referenced by bit_field(), FieldIndex(), first_inobject_property_offset(), GetFieldAccessStubKey(), is_double(), is_inobject(), offset(), operator==(), and property_index().
kOffsetBitsSize
const int v8::internal::FieldIndex::kOffsetBitsSize [static], [private]
Initial value:
=
      (kDescriptorIndexBitCount + 1 + kTaggedSizeLog2)
Definition at line 114 of file field-index.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/field-index.h
/mnt/V8SourceCode/src/objects/field-index-inl.h