v8::internal::compiler::TFPipelineData Class Reference
#include <pipeline-data-inl.h>
Public Types
template<typename T >
using GraphZonePointer = turboshaft::ZoneWithNamePointer< T, kGraphZoneName >
Public Member Functions
TFPipelineData (ZoneStats *zone_stats, Isolate *isolate, OptimizedCompilationInfo *info, TurbofanPipelineStatistics *pipeline_statistics)
TFPipelineData (ZoneStats *zone_stats, OptimizedCompilationInfo *info, Isolate *isolate, AccountingAllocator *allocator, TFGraph *graph, JSGraph *jsgraph, Schedule *schedule, SourcePositionTable *source_positions, NodeOriginTable *node_origins, JumpOptimizationInfo *jump_opt, const AssemblerOptions &assembler_options, const ProfileDataFromFile *profile_data)
TFPipelineData (ZoneStats *zone_stats, OptimizedCompilationInfo *info, Isolate *isolate, InstructionSequence *sequence)
~TFPipelineData ()
TFPipelineData (const TFPipelineData &)=delete
TFPipelineData & operator= (const TFPipelineData &)=delete
Isolate * isolate () const
AccountingAllocator * allocator () const
OptimizedCompilationInfo * info () const
ZoneStats * zone_stats () const
CompilationDependencies * dependencies () const
TurbofanPipelineStatistics * pipeline_statistics ()
OsrHelper * osr_helper ()
std::shared_ptr< OsrHelper > osr_helper_ptr () const
bool verify_graph () const
void set_verify_graph (bool value)
MaybeIndirectHandle< Code > code ()
void set_code (MaybeIndirectHandle< Code > code)
CodeGenerator * code_generator () const
bool MayHaveUnverifiableGraph () const
Zone * graph_zone ()
TFGraph * graph () const
void set_graph (TFGraph *graph)
void InitializeWithGraphZone (turboshaft::ZoneWithName< kGraphZoneName > graph_zone, GraphZonePointer< SourcePositionTable > source_positions, GraphZonePointer< NodeOriginTable > node_origins, size_t node_count_hint=0)
turboshaft::ZoneWithName< kGraphZoneName > ReleaseGraphZone ()
SourcePositionTable * source_positions () const
void set_source_positions (SourcePositionTable *source_positions)
NodeOriginTable * node_origins () const
void set_node_origins (NodeOriginTable *node_origins)
MachineOperatorBuilder * machine () const
SimplifiedOperatorBuilder * simplified () const
CommonOperatorBuilder * common () const
JSOperatorBuilder * javascript () const
JSGraph * jsgraph () const
MachineGraph * mcgraph () const
DirectHandle< NativeContext > native_context () const
DirectHandle< JSGlobalObject > global_object () const
JSHeapBroker * broker () const
std::shared_ptr< JSHeapBroker > broker_ptr ()
Schedule * schedule () const
void set_schedule (Schedule *schedule)
void reset_schedule ()
ObserveNodeManager * observe_node_manager () const
Zone * instruction_zone () const
Zone * codegen_zone () const
InstructionSequence * sequence () const
Frame * frame () const
Zone * register_allocation_zone () const
RegisterAllocationData * register_allocation_data () const
std::string const & source_position_output () const
void set_source_position_output (std::string const &source_position_output)
JumpOptimizationInfo * jump_optimization_info () const
const AssemblerOptions & assembler_options () const
void ChooseSpecializationContext ()
Maybe< OuterContext > specialization_context () const
size_t * address_of_max_unoptimized_frame_height ()
size_t max_unoptimized_frame_height () const
size_t * address_of_max_pushed_argument_count ()
size_t max_pushed_argument_count () const
CodeTracer * GetCodeTracer () const
Typer * CreateTyper ()
void AddTyperFlag (Typer::Flag flag)
void DeleteTyper ()
void DeleteGraphZone ()
void DeleteInstructionZone ()
void DeleteCodegenZone ()
void DeleteRegisterAllocationZone ()
void InitializeInstructionSequence (const CallDescriptor *call_descriptor)
void InitializeFrameData (CallDescriptor *call_descriptor)
void InitializeRegisterAllocationData (const RegisterConfiguration *config, CallDescriptor *call_descriptor)
void InitializeOsrHelper ()
void set_start_source_position (int position)
int start_source_position () const
void InitializeCodeGenerator (Linkage *linkage)
void BeginPhaseKind (const char *phase_kind_name)
void EndPhaseKind ()
const char * debug_name () const
const ProfileDataFromFile * profile_data () const
void set_profile_data (const ProfileDataFromFile *profile_data)
RuntimeCallStats * runtime_call_stats () const
void set_runtime_call_stats (RuntimeCallStats *stats)
Private Attributes
Isolate *const isolate_
AccountingAllocator *const allocator_
OptimizedCompilationInfo *const info_
std::unique_ptr< char[]> debug_name_
bool may_have_unverifiable_graph_ = true
ZoneStats *const zone_stats_
TurbofanPipelineStatistics * pipeline_statistics_ = nullptr
bool verify_graph_ = false
int start_source_position_ = kNoSourcePosition
std::shared_ptr< OsrHelper > osr_helper_
MaybeIndirectHandle< Code > code_
CodeGenerator * code_generator_ = nullptr
Typer * typer_ = nullptr
Typer::Flags typer_flags_ = Typer::kNoFlags
turboshaft::ZoneWithName< kGraphZoneName > graph_zone_
TFGraph * graph_ = nullptr
SourcePositionTable * source_positions_ = nullptr
NodeOriginTable * node_origins_ = nullptr
SimplifiedOperatorBuilder * simplified_ = nullptr
MachineOperatorBuilder * machine_ = nullptr
CommonOperatorBuilder * common_ = nullptr
JSOperatorBuilder * javascript_ = nullptr
JSGraph * jsgraph_ = nullptr
MachineGraph * mcgraph_ = nullptr
Schedule * schedule_ = nullptr
ObserveNodeManager * observe_node_manager_ = nullptr
std::unique_ptr< turboshaft::PipelineData > ts_data_
ZoneStats::Scope instruction_zone_scope_
Zone * instruction_zone_
InstructionSequence * sequence_ = nullptr
ZoneStats::Scope codegen_zone_scope_
Zone * codegen_zone_
CompilationDependencies * dependencies_ = nullptr
std::shared_ptr< JSHeapBroker > broker_
Frame * frame_ = nullptr
ZoneStats::Scope register_allocation_zone_scope_
Zone * register_allocation_zone_
RegisterAllocationData * register_allocation_data_ = nullptr
std::string source_position_output_
JumpOptimizationInfo * jump_optimization_info_ = nullptr
AssemblerOptions assembler_options_
Maybe< OuterContext > specialization_context_ = Nothing<OuterContext>()
size_t max_unoptimized_frame_height_ = 0
size_t max_pushed_argument_count_ = 0
RuntimeCallStats * runtime_call_stats_ = nullptr
const ProfileDataFromFile * profile_data_ = nullptr
Detailed Description
Definition at line 61 of file pipeline-data-inl.h.
Member Typedef Documentation
GraphZonePointer
template<typename T >
using v8::internal::compiler::TFPipelineData::GraphZonePointer = turboshaft::ZoneWithNamePointer<T, kGraphZoneName>
Definition at line 259 of file pipeline-data-inl.h.
Constructor & Destructor Documentation
TFPipelineData() [1/4]
v8::internal::compiler::TFPipelineData::TFPipelineData (ZoneStats * zone_stats, Isolate * isolate, OptimizedCompilationInfo * info, TurbofanPipelineStatistics * pipeline_statistics) [inline]
Definition at line 64 of file pipeline-data-inl.h.
      : isolate_(isolate),
        allocator_(isolate->allocator()),
        info_(info),
        debug_name_(info_->GetDebugName()),
        may_have_unverifiable_graph_(v8_flags.turboshaft),
        zone_stats_(zone_stats),
        pipeline_statistics_(pipeline_statistics),
        graph_zone_(zone_stats_, kGraphZoneName),
        instruction_zone_scope_(zone_stats_, kInstructionZoneName),
        instruction_zone_(instruction_zone_scope_.zone()),
        codegen_zone_scope_(zone_stats_, kCodegenZoneName),
        codegen_zone_(codegen_zone_scope_.zone()),
        broker_(new JSHeapBroker(isolate_, info_->zone(),
                                 info_->trace_heap_broker(),
                                 info->code_kind())),
        register_allocation_zone_scope_(zone_stats_,
                                        kRegisterAllocationZoneName),
        register_allocation_zone_(register_allocation_zone_scope_.zone()),
        assembler_options_(AssemblerOptions::Default(isolate)) {
    PhaseScope scope(pipeline_statistics, "V8.TFInitPipelineData");
    graph_ = graph_zone_->New<TFGraph>(graph_zone_);
    source_positions_ = graph_zone_->New<SourcePositionTable>(graph_);
    node_origins_ = info->trace_turbo_json()
                        ? graph_zone_->New<NodeOriginTable>(graph_)
                        : nullptr;
#if V8_ENABLE_WEBASSEMBLY
    js_wasm_calls_sidetable_ =
        graph_zone_->New<JsWasmCallsSidetable>(graph_zone_);
#endif // V8_ENABLE_WEBASSEMBLY
    simplified_ = graph_zone_->New<SimplifiedOperatorBuilder>(graph_zone_);
    machine_ = graph_zone_->New<MachineOperatorBuilder>(
        graph_zone_, MachineType::PointerRepresentation(),
        InstructionSelector::SupportedMachineOperatorFlags(),
        InstructionSelector::AlignmentRequirements());
    common_ = graph_zone_->New<CommonOperatorBuilder>(graph_zone_);
    javascript_ = graph_zone_->New<JSOperatorBuilder>(graph_zone_);
    jsgraph_ = graph_zone_->New<JSGraph>(isolate_, graph_, common_, javascript_,
                                         simplified_, machine_);
    observe_node_manager_ =
        info->node_observer()
            ? graph_zone_->New<ObserveNodeManager>(graph_zone_)
            : nullptr;
    dependencies_ = info_->zone()->New<CompilationDependencies>(broker_.get(),
                                                                info_->zone());
  }
References v8::internal::compiler::InstructionSelector::AlignmentRequirements(), broker_, common_, dependencies_, graph_, graph_zone_, info(), info_, isolate_, javascript_, jsgraph_, machine_, v8::internal::Zone::New(), v8::internal::OptimizedCompilationInfo::node_observer(), node_origins_, observe_node_manager_, pipeline_statistics(), v8::internal::MachineType::PointerRepresentation(), simplified_, source_positions_, v8::internal::compiler::InstructionSelector::SupportedMachineOperatorFlags(), and v8::internal::OptimizedCompilationInfo::zone().
TFPipelineData() [2/4]
v8::internal::compiler::TFPipelineData::TFPipelineData (ZoneStats * zone_stats, OptimizedCompilationInfo * info, Isolate * isolate, AccountingAllocator * allocator, TFGraph * graph, JSGraph * jsgraph, Schedule * schedule, SourcePositionTable * source_positions, NodeOriginTable * node_origins, JumpOptimizationInfo * jump_opt, const AssemblerOptions & assembler_options, const ProfileDataFromFile * profile_data) [inline]
Definition at line 151 of file pipeline-data-inl.h.
      : isolate_(isolate),
        allocator_(allocator),
        info_(info),
        debug_name_(info_->GetDebugName()),
        zone_stats_(zone_stats),
        graph_zone_(zone_stats_, kGraphZoneName),
        graph_(graph),
        source_positions_(source_positions),
        node_origins_(node_origins),
        schedule_(schedule),
        instruction_zone_scope_(zone_stats_, kInstructionZoneName),
        instruction_zone_(instruction_zone_scope_.zone()),
        codegen_zone_scope_(zone_stats_, kCodegenZoneName),
        codegen_zone_(codegen_zone_scope_.zone()),
        register_allocation_zone_scope_(zone_stats_,
                                        kRegisterAllocationZoneName),
        register_allocation_zone_(register_allocation_zone_scope_.zone()),
        jump_optimization_info_(jump_opt),
        assembler_options_(assembler_options),
        profile_data_(profile_data) {
    if (jsgraph) {
      jsgraph_ = jsgraph;
      simplified_ = jsgraph->simplified();
      machine_ = jsgraph->machine();
      common_ = jsgraph->common();
      javascript_ = jsgraph->javascript();
    } else if (graph_) {
      simplified_ = graph_zone_->New<SimplifiedOperatorBuilder>(graph_zone_);
      machine_ = graph_zone_->New<MachineOperatorBuilder>(
          graph_zone_, MachineType::PointerRepresentation(),
          InstructionSelector::SupportedMachineOperatorFlags(),
          InstructionSelector::AlignmentRequirements());
      common_ = graph_zone_->New<CommonOperatorBuilder>(graph_zone_);
      javascript_ = graph_zone_->New<JSOperatorBuilder>(graph_zone_);
      jsgraph_ = graph_zone_->New<JSGraph>(isolate_, graph_, common_,
                                           javascript_, simplified_, machine_);
    }
  }
References v8::internal::compiler::InstructionSelector::AlignmentRequirements(), v8::internal::compiler::MachineGraph::common(), common_, graph_, graph_zone_, isolate_, v8::internal::compiler::JSGraph::javascript(), javascript_, jsgraph(), jsgraph_, v8::internal::compiler::MachineGraph::machine(), machine_, v8::internal::Zone::New(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::JSGraph::simplified(), simplified_, and v8::internal::compiler::InstructionSelector::SupportedMachineOperatorFlags().
TFPipelineData() [3/4]
v8::internal::compiler::TFPipelineData::TFPipelineData (ZoneStats * zone_stats, OptimizedCompilationInfo * info, Isolate * isolate, InstructionSequence * sequence) [inline]
Definition at line 198 of file pipeline-data-inl.h.
      : isolate_(isolate),
        allocator_(isolate->allocator()),
        info_(info),
        debug_name_(info_->GetDebugName()),
        zone_stats_(zone_stats),
        graph_zone_(zone_stats_, kGraphZoneName),
        instruction_zone_scope_(zone_stats_, kInstructionZoneName),
        instruction_zone_(sequence->zone()),
        sequence_(sequence),
        codegen_zone_scope_(zone_stats_, kCodegenZoneName),
        codegen_zone_(codegen_zone_scope_.zone()),
        register_allocation_zone_scope_(zone_stats_,
                                        kRegisterAllocationZoneName),
        register_allocation_zone_(register_allocation_zone_scope_.zone()),
        assembler_options_(AssemblerOptions::Default(isolate)) {}
 TFPipelineData()
v8::internal::compiler::TFPipelineData::~TFPipelineData () [inline]
Definition at line 216 of file pipeline-data-inl.h.
                    {
    // Must happen before zones are destroyed.
    delete code_generator_;
    code_generator_ = nullptr;
    DeleteTyper();
    DeleteRegisterAllocationZone();
    DeleteInstructionZone();
    DeleteCodegenZone();
    DeleteGraphZone();
  }
References code_generator_, DeleteCodegenZone(), DeleteGraphZone(), DeleteInstructionZone(), DeleteRegisterAllocationZone(), and DeleteTyper().
TFPipelineData() [4/4]
v8::internal::compiler::TFPipelineData::TFPipelineData (const TFPipelineData &) [delete]
Member Function Documentation
address_of_max_pushed_argument_count()
size_t* v8::internal::compiler::TFPipelineData::address_of_max_pushed_argument_count () [inline]
Definition at line 374 of file pipeline-data-inl.h.
                                                 {
    return &max_pushed_argument_count_;
  }
References max_pushed_argument_count_.
address_of_max_unoptimized_frame_height()
size_t* v8::internal::compiler::TFPipelineData::address_of_max_unoptimized_frame_height () [inline]
Definition at line 368 of file pipeline-data-inl.h.
                                                    {
    return &max_unoptimized_frame_height_;
  }
References max_unoptimized_frame_height_.
AddTyperFlag()
void v8::internal::compiler::TFPipelineData::AddTyperFlag (Typer::Flag flag) [inline]
Definition at line 397 of file pipeline-data-inl.h.
                                    {
    DCHECK_NULL(typer_);
    typer_flags_ |= flag;
  }
References DCHECK_NULL, typer_, and typer_flags_.
Referenced by v8::internal::compiler::PipelineImpl::CreateGraph().
allocator()
AccountingAllocator* v8::internal::compiler::TFPipelineData::allocator () const [inline]
Definition at line 231 of file pipeline-data-inl.h.
{ return allocator_; }
References allocator_.
assembler_options()
const AssemblerOptions& v8::internal::compiler::TFPipelineData::assembler_options () const [inline]
Definition at line 350 of file pipeline-data-inl.h.
                                                    {
    return assembler_options_;
  }
References assembler_options_.
Referenced by InitializeCodeGenerator().
BeginPhaseKind()
void v8::internal::compiler::TFPipelineData::BeginPhaseKind (const char * phase_kind_name) [inline]
Definition at line 510 of file pipeline-data-inl.h.
                                                   {
    if (pipeline_statistics() != nullptr) {
      pipeline_statistics()->BeginPhaseKind(phase_kind_name);
    }
  }
References v8::internal::compiler::TurbofanPipelineStatistics::BeginPhaseKind(), and pipeline_statistics().
Referenced by v8::internal::compiler::PipelineImpl::CreateGraph(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), and v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph().
broker()
JSHeapBroker* v8::internal::compiler::TFPipelineData::broker () const [inline]
Definition at line 314 of file pipeline-data-inl.h.
{ return broker_.get(); }
References broker_.
Referenced by v8::internal::compiler::PipelineImpl::CreateGraph(), CreateTyper(), v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), and v8::internal::compiler::TraceSchedule().
broker_ptr()
std::shared_ptr<JSHeapBroker> v8::internal::compiler::TFPipelineData::broker_ptr () [inline]
Definition at line 315 of file pipeline-data-inl.h.
{ return broker_; }
References broker_.
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
ChooseSpecializationContext()
void v8::internal::compiler::TFPipelineData::ChooseSpecializationContext () [inline]
Definition at line 354 of file pipeline-data-inl.h.
                                     {
    if (info()->function_context_specializing()) {
      DCHECK(info()->has_context());
      specialization_context_ = Just(OuterContext(
          info()->CanonicalHandle(info()->context(), isolate()), 0));
    } else {
      specialization_context_ = GetModuleContext(info());
    }
  }
References v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::CanonicalHandle(), v8::internal::DCHECK(), v8::internal::compiler::GetModuleContext(), info(), isolate(), v8::Just(), and specialization_context_.
Referenced by v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl().
code()
MaybeIndirectHandle<Code> v8::internal::compiler::TFPipelineData::code () [inline]
Definition at line 244 of file pipeline-data-inl.h.
{ return code_; }
References code_.
Referenced by set_code().
code_generator()
CodeGenerator* v8::internal::compiler::TFPipelineData::code_generator () const [inline]
Definition at line 250 of file pipeline-data-inl.h.
{ return code_generator_; }
References code_generator_.
codegen_zone()
Zone* v8::internal::compiler::TFPipelineData::codegen_zone () const [inline]
Definition at line 329 of file pipeline-data-inl.h.
{ return codegen_zone_; }
References codegen_zone_.
Referenced by InitializeCodeGenerator(), and InitializeFrameData().
common()
CommonOperatorBuilder* v8::internal::compiler::TFPipelineData::common () const [inline]
Definition at line 303 of file pipeline-data-inl.h.
{ return common_; }
References common_.
CreateTyper()
Typer* v8::internal::compiler::TFPipelineData::CreateTyper () [inline]
Definition at line 390 of file pipeline-data-inl.h.
                       {
    DCHECK_NULL(typer_);
    typer_ =
        new Typer(broker(), typer_flags_, graph(), &info()->tick_counter());
    return typer_;
  }
References broker(), DCHECK_NULL, graph(), info(), typer_, and typer_flags_.
Referenced by v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph().
debug_name()
const char* v8::internal::compiler::TFPipelineData::debug_name () const [inline]
Definition at line 522 of file pipeline-data-inl.h.
{ return debug_name_.get(); }
References debug_name_.
Referenced by InitializeRegisterAllocationData().
DeleteCodegenZone()
void v8::internal::compiler::TFPipelineData::DeleteCodegenZone () [inline]
Definition at line 431 of file pipeline-data-inl.h.
                           {
    if (codegen_zone_ == nullptr) return;
    codegen_zone_scope_.Destroy();
    codegen_zone_ = nullptr;
    dependencies_ = nullptr;
    broker_.reset();
    broker_ = nullptr;
    frame_ = nullptr;
  }
References broker_, codegen_zone_, codegen_zone_scope_, dependencies_, v8::internal::compiler::ZoneStats::Scope::Destroy(), and frame_.
Referenced by ~TFPipelineData().
DeleteGraphZone()
void v8::internal::compiler::TFPipelineData::DeleteGraphZone () [inline]
Definition at line 407 of file pipeline-data-inl.h.
                         {
#ifdef V8_ENABLE_WEBASSEMBLY
    js_wasm_calls_sidetable_ = nullptr;
#endif // V8_ENABLE_WEBASSEMBLY
    graph_ = nullptr;
    source_positions_ = nullptr;
    node_origins_ = nullptr;
    simplified_ = nullptr;
    machine_ = nullptr;
    common_ = nullptr;
    javascript_ = nullptr;
    jsgraph_ = nullptr;
    mcgraph_ = nullptr;
    schedule_ = nullptr;
    graph_zone_.Destroy();
  }
References common_, v8::internal::compiler::turboshaft::ZoneWithName< Name >::Destroy(), graph_, graph_zone_, javascript_, jsgraph_, machine_, mcgraph_, node_origins_, schedule_, simplified_, and source_positions_.
Referenced by InitializeWithGraphZone(), ReleaseGraphZone(), and ~TFPipelineData().
DeleteInstructionZone()
void v8::internal::compiler::TFPipelineData::DeleteInstructionZone () [inline]
Definition at line 424 of file pipeline-data-inl.h.
                               {
    if (instruction_zone_ == nullptr) return;
    instruction_zone_scope_.Destroy();
    instruction_zone_ = nullptr;
    sequence_ = nullptr;
  }
References v8::internal::compiler::ZoneStats::Scope::Destroy(), instruction_zone_, instruction_zone_scope_, and sequence_.
Referenced by ~TFPipelineData().
DeleteRegisterAllocationZone()
void v8::internal::compiler::TFPipelineData::DeleteRegisterAllocationZone () [inline]
Definition at line 441 of file pipeline-data-inl.h.
                                      {
    if (register_allocation_zone_ == nullptr) return;
    register_allocation_zone_scope_.Destroy();
    register_allocation_zone_ = nullptr;
    register_allocation_data_ = nullptr;
  }
References v8::internal::compiler::ZoneStats::Scope::Destroy(), register_allocation_data_, register_allocation_zone_, and register_allocation_zone_scope_.
Referenced by ~TFPipelineData().
DeleteTyper()
void v8::internal::compiler::TFPipelineData::DeleteTyper () [inline]
Definition at line 402 of file pipeline-data-inl.h.
                     {
    delete typer_;
    typer_ = nullptr;
  }
References typer_.
Referenced by v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), and ~TFPipelineData().
dependencies()
CompilationDependencies* v8::internal::compiler::TFPipelineData::dependencies () const [inline]
Definition at line 234 of file pipeline-data-inl.h.
{ return dependencies_; }
References dependencies_.
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
EndPhaseKind()
void v8::internal::compiler::TFPipelineData::EndPhaseKind () [inline]
Definition at line 516 of file pipeline-data-inl.h.
                      {
    if (pipeline_statistics() != nullptr) {
      pipeline_statistics()->EndPhaseKind();
    }
  }
References v8::internal::compiler::TurbofanPipelineStatistics::EndPhaseKind(), and pipeline_statistics().
Referenced by v8::internal::compiler::PipelineImpl::CreateGraph(), v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and v8::internal::compiler::PipelineImpl::InitializeHeapBroker().
frame()
Frame* v8::internal::compiler::TFPipelineData::frame () const [inline]
Definition at line 331 of file pipeline-data-inl.h.
{ return frame_; }
References frame_.
Referenced by InitializeCodeGenerator(), InitializeFrameData(), and InitializeRegisterAllocationData().
GetCodeTracer()
CodeTracer* v8::internal::compiler::TFPipelineData::GetCodeTracer () const [inline]
Definition at line 381 of file pipeline-data-inl.h.
                                    {
#if V8_ENABLE_WEBASSEMBLY
    if (info_->IsWasm() || info_->IsWasmBuiltin()) {
      return wasm::GetWasmEngine()->GetCodeTracer();
    }
#endif // V8_ENABLE_WEBASSEMBLY
    return isolate_->GetCodeTracer();
  }
References v8::internal::Isolate::GetCodeTracer(), v8::internal::wasm::WasmEngine::GetCodeTracer(), v8::internal::wasm::GetWasmEngine(), info_, and isolate_.
Referenced by v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), and v8::internal::compiler::TraceSchedule().
global_object()
DirectHandle<JSGlobalObject> v8::internal::compiler::TFPipelineData::global_object () const [inline]
Definition at line 310 of file pipeline-data-inl.h.
                                                     {
    return direct_handle(info()->global_object(), isolate());
  }
References v8::internal::direct_handle(), info(), and isolate().
graph()
TFGraph* v8::internal::compiler::TFPipelineData::graph () const [inline]
Definition at line 256 of file pipeline-data-inl.h.
{ return graph_; }
References graph_.
Referenced by CreateTyper(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), and set_graph().
graph_zone()
Zone* v8::internal::compiler::TFPipelineData::graph_zone () [inline]
Definition at line 255 of file pipeline-data-inl.h.
{ return graph_zone_; }
References graph_zone_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer(), and InitializeWithGraphZone().
info()
OptimizedCompilationInfo* v8::internal::compiler::TFPipelineData::info () const [inline]
Definition at line 232 of file pipeline-data-inl.h.
{ return info_; }
References info_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer(), ChooseSpecializationContext(), v8::internal::compiler::PipelineImpl::ComputeScheduledGraph(), CreateTyper(), v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), global_object(), InitializeCodeGenerator(), InitializeFrameData(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), InitializeOsrHelper(), InitializeRegisterAllocationData(), native_context(), v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), and TFPipelineData().
InitializeCodeGenerator()
void v8::internal::compiler::TFPipelineData::InitializeCodeGenerator (Linkage * linkage) [inline]
Definition at line 494 of file pipeline-data-inl.h.
                                                 {
    DCHECK_NULL(code_generator_);
#if V8_ENABLE_WEBASSEMBLY
    assembler_options_.is_wasm =
        this->info()->IsWasm() || this->info()->IsWasmBuiltin();
#endif
    std::optional<OsrHelper> osr_helper;
    if (osr_helper_) osr_helper = *osr_helper_;
    code_generator_ = new CodeGenerator(
        codegen_zone(), frame(), linkage, sequence(), info(), isolate(),
        std::move(osr_helper), start_source_position_, jump_optimization_info_,
        assembler_options(), info_->builtin(), max_unoptimized_frame_height(),
        max_pushed_argument_count(),
        v8_flags.trace_turbo_stack_accesses ? debug_name_.get() : nullptr);
  }
References assembler_options(), assembler_options_, v8::internal::OptimizedCompilationInfo::builtin(), code_generator_, codegen_zone(), DCHECK_NULL, debug_name_, frame(), info(), info_, v8::internal::AssemblerOptions::is_wasm, isolate(), jump_optimization_info_, max_pushed_argument_count(), max_unoptimized_frame_height(), osr_helper(), osr_helper_, sequence(), start_source_position_, and v8::internal::v8_flags.
InitializeFrameData()
void v8::internal::compiler::TFPipelineData::InitializeFrameData (CallDescriptor * call_descriptor) [inline]
Definition at line 462 of file pipeline-data-inl.h.
                                                            {
    DCHECK_NULL(frame_);
    int fixed_frame_size = 0;
    if (call_descriptor != nullptr) {
      fixed_frame_size =
          call_descriptor->CalculateFixedFrameSize(info()->code_kind());
    }
    frame_ = codegen_zone()->New<Frame>(fixed_frame_size, codegen_zone());
    if (osr_helper_) osr_helper()->SetupFrame(frame());
  }
References v8::internal::compiler::CallDescriptor::CalculateFixedFrameSize(), codegen_zone(), DCHECK_NULL, frame(), frame_, info(), v8::internal::Zone::New(), osr_helper(), osr_helper_, and v8::internal::compiler::OsrHelper::SetupFrame().
Referenced by v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph().
InitializeInstructionSequence()
void v8::internal::compiler::TFPipelineData::InitializeInstructionSequence (const CallDescriptor * call_descriptor) [inline]
Definition at line 448 of file pipeline-data-inl.h.
                                                                            {
    DCHECK_NULL(sequence_);
    InstructionBlocks* instruction_blocks =
        InstructionSequence::InstructionBlocksFor(instruction_zone(),
                                                  schedule());
    sequence_ = instruction_zone()->New<InstructionSequence>(
        isolate(), instruction_zone(), instruction_blocks);
    if (call_descriptor && call_descriptor->RequiresFrameAsIncoming()) {
      sequence_->instruction_blocks()[0]->mark_needs_frame();
    } else {
      DCHECK(call_descriptor->CalleeSavedFPRegisters().is_empty());
    }
  }
References v8::internal::compiler::CallDescriptor::CalleeSavedFPRegisters(), v8::internal::DCHECK(), DCHECK_NULL, v8::internal::compiler::InstructionSequence::instruction_blocks(), instruction_zone(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::RegListBase< RegisterT >::is_empty(), isolate(), v8::internal::Zone::New(), v8::internal::compiler::CallDescriptor::RequiresFrameAsIncoming(), schedule(), and sequence_.
InitializeOsrHelper()
void v8::internal::compiler::TFPipelineData::InitializeOsrHelper () [inline]
Definition at line 482 of file pipeline-data-inl.h.
                             {
    DCHECK_NULL(osr_helper_);
    osr_helper_ = std::make_shared<OsrHelper>(info());
  }
References DCHECK_NULL, info(), and osr_helper_.
Referenced by v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl().
InitializeRegisterAllocationData()
void v8::internal::compiler::TFPipelineData::InitializeRegisterAllocationData (const RegisterConfiguration * config, CallDescriptor * call_descriptor) [inline]
Definition at line 473 of file pipeline-data-inl.h.
                                                                         {
    DCHECK_NULL(register_allocation_data_);
    register_allocation_data_ =
        register_allocation_zone()->New<RegisterAllocationData>(
            config, register_allocation_zone(), frame(), sequence(),
            &info()->tick_counter(), debug_name());
  }
References DCHECK_NULL, debug_name(), frame(), info(), v8::internal::Zone::New(), register_allocation_data_, register_allocation_zone(), sequence(), and v8::internal::OptimizedCompilationInfo::tick_counter().
InitializeWithGraphZone()
void v8::internal::compiler::TFPipelineData::InitializeWithGraphZone (turboshaft::ZoneWithName< kGraphZoneName > graph_zone, GraphZonePointer< SourcePositionTable > source_positions, GraphZonePointer< NodeOriginTable > node_origins, size_t node_count_hint = 0) [inline]
Definition at line 260 of file pipeline-data-inl.h.
                                  {
    // Delete the old zone first.
    DeleteGraphZone();
    // Take ownership of the new zone and the existing pointers.
    graph_zone_ = std::move(graph_zone);
    source_positions_ = source_positions;
    node_origins_ = node_origins;
    // Allocate a new graph and schedule.
    graph_ = graph_zone_.New<TFGraph>(graph_zone_);
    schedule_ = graph_zone_.New<Schedule>(graph_zone_, node_count_hint);
    // Initialize node builders.
    javascript_ = graph_zone_.New<JSOperatorBuilder>(graph_zone_);
    common_ = graph_zone_.New<CommonOperatorBuilder>(graph_zone_);
    simplified_ = graph_zone_.New<SimplifiedOperatorBuilder>(graph_zone_);
    machine_ = graph_zone_.New<MachineOperatorBuilder>(
        graph_zone_, MachineType::PointerRepresentation(),
        InstructionSelector::SupportedMachineOperatorFlags(),
        InstructionSelector::AlignmentRequirements());
  }
References v8::internal::compiler::InstructionSelector::AlignmentRequirements(), common_, DeleteGraphZone(), graph_, graph_zone(), graph_zone_, javascript_, machine_, v8::internal::compiler::turboshaft::ZoneWithName< Name >::New(), node_origins(), node_origins_, v8::internal::MachineType::PointerRepresentation(), schedule_, simplified_, source_positions(), source_positions_, and v8::internal::compiler::InstructionSelector::SupportedMachineOperatorFlags().
instruction_zone()
Zone* v8::internal::compiler::TFPipelineData::instruction_zone () const [inline]
Definition at line 328 of file pipeline-data-inl.h.
{ return instruction_zone_; }
References instruction_zone_.
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and InitializeInstructionSequence().
isolate()
Isolate* v8::internal::compiler::TFPipelineData::isolate () const [inline]
Definition at line 230 of file pipeline-data-inl.h.
{ return isolate_; }
References isolate_.
Referenced by ChooseSpecializationContext(), global_object(), InitializeCodeGenerator(), InitializeInstructionSequence(), and native_context().
javascript()
JSOperatorBuilder* v8::internal::compiler::TFPipelineData::javascript () const [inline]
Definition at line 304 of file pipeline-data-inl.h.
{ return javascript_; }
References javascript_.
jsgraph()
JSGraph* v8::internal::compiler::TFPipelineData::jsgraph () const [inline]
Definition at line 305 of file pipeline-data-inl.h.
{ return jsgraph_; }
References jsgraph_.
Referenced by v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), and TFPipelineData().
jump_optimization_info()
JumpOptimizationInfo* v8::internal::compiler::TFPipelineData::jump_optimization_info () const [inline]
Definition at line 346 of file pipeline-data-inl.h.
                                                       {
    return jump_optimization_info_;
  }
References jump_optimization_info_.
machine()
MachineOperatorBuilder* v8::internal::compiler::TFPipelineData::machine () const [inline]
Definition at line 301 of file pipeline-data-inl.h.
{ return machine_; }
References machine_.
max_pushed_argument_count()
size_t v8::internal::compiler::TFPipelineData::max_pushed_argument_count () const [inline]
Definition at line 377 of file pipeline-data-inl.h.
                                           {
    return max_pushed_argument_count_;
  }
References max_pushed_argument_count_.
Referenced by InitializeCodeGenerator().
max_unoptimized_frame_height()
size_t v8::internal::compiler::TFPipelineData::max_unoptimized_frame_height () const [inline]
Definition at line 371 of file pipeline-data-inl.h.
                                              {
    return max_unoptimized_frame_height_;
  }
References max_unoptimized_frame_height_.
Referenced by InitializeCodeGenerator().
MayHaveUnverifiableGraph()
bool v8::internal::compiler::TFPipelineData::MayHaveUnverifiableGraph () const [inline]
Definition at line 253 of file pipeline-data-inl.h.
{ return may_have_unverifiable_graph_; }
References may_have_unverifiable_graph_.
mcgraph()
MachineGraph* v8::internal::compiler::TFPipelineData::mcgraph () const [inline]
Definition at line 306 of file pipeline-data-inl.h.
{ return mcgraph_; }
References mcgraph_.
native_context()
DirectHandle<NativeContext> v8::internal::compiler::TFPipelineData::native_context () const [inline]
Definition at line 307 of file pipeline-data-inl.h.
                                                     {
    return direct_handle(info()->native_context(), isolate());
  }
References v8::internal::direct_handle(), info(), and isolate().
node_origins()
NodeOriginTable* v8::internal::compiler::TFPipelineData::node_origins () const [inline]
Definition at line 297 of file pipeline-data-inl.h.
{ return node_origins_; }
References node_origins_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), InitializeWithGraphZone(), v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), v8::internal::compiler::turboshaft::BuildGraphPhase::Run(), and set_node_origins().
observe_node_manager()
ObserveNodeManager* v8::internal::compiler::TFPipelineData::observe_node_manager () const [inline]
Definition at line 324 of file pipeline-data-inl.h.
                                                   {
    return observe_node_manager_;
  }
References observe_node_manager_.
operator=()
TFPipelineData& v8::internal::compiler::TFPipelineData::operator= (const TFPipelineData &) [delete]
osr_helper()
OsrHelper* v8::internal::compiler::TFPipelineData::osr_helper () [inline]
Definition at line 238 of file pipeline-data-inl.h.
{ return osr_helper_.get(); }
References osr_helper_.
Referenced by InitializeCodeGenerator(), and InitializeFrameData().
osr_helper_ptr()
std::shared_ptr<OsrHelper> v8::internal::compiler::TFPipelineData::osr_helper_ptr () const [inline]
Definition at line 239 of file pipeline-data-inl.h.
{ return osr_helper_; }
References osr_helper_.
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
pipeline_statistics()
TurbofanPipelineStatistics* v8::internal::compiler::TFPipelineData::pipeline_statistics () [inline]
Definition at line 235 of file pipeline-data-inl.h.
                                                    {
    return pipeline_statistics_;
  }
References pipeline_statistics_.
Referenced by BeginPhaseKind(), EndPhaseKind(), and TFPipelineData().
profile_data()
const ProfileDataFromFile* v8::internal::compiler::TFPipelineData::profile_data () const [inline]
Definition at line 524 of file pipeline-data-inl.h.
{ return profile_data_; }
References profile_data_.
Referenced by set_profile_data().
register_allocation_data()
RegisterAllocationData* v8::internal::compiler::TFPipelineData::register_allocation_data () const [inline]
Definition at line 335 of file pipeline-data-inl.h.
                                                           {
    return register_allocation_data_;
  }
References register_allocation_data_.
register_allocation_zone()
Zone* v8::internal::compiler::TFPipelineData::register_allocation_zone () const [inline]
Definition at line 333 of file pipeline-data-inl.h.
{ return register_allocation_zone_; }
References register_allocation_zone_.
Referenced by InitializeRegisterAllocationData().
ReleaseGraphZone()
turboshaft::ZoneWithName<kGraphZoneName> v8::internal::compiler::TFPipelineData::ReleaseGraphZone () [inline]
Definition at line 286 of file pipeline-data-inl.h.
                                                            {
    turboshaft::ZoneWithName<kGraphZoneName> temp = std::move(graph_zone_);
    // Call `DeleteGraphZone` to reset all pointers. The actual zone is not
    // released because we moved it away.
    DeleteGraphZone();
    return temp;
  }
References DeleteGraphZone(), and graph_zone_.
Referenced by v8::internal::compiler::turboshaft::BuildGraphPhase::Run().
reset_schedule()
void v8::internal::compiler::TFPipelineData::reset_schedule () [inline]
Definition at line 322 of file pipeline-data-inl.h.
{ schedule_ = nullptr; }
References schedule_.
Referenced by v8::internal::compiler::turboshaft::BuildGraphPhase::Run().
runtime_call_stats()
RuntimeCallStats* v8::internal::compiler::TFPipelineData::runtime_call_stats () const [inline]
Definition at line 534 of file pipeline-data-inl.h.
{ return runtime_call_stats_; }
References runtime_call_stats_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::TraceScheduleAndVerify().
schedule()
Schedule* v8::internal::compiler::TFPipelineData::schedule () const [inline]
Definition at line 317 of file pipeline-data-inl.h.
{ return schedule_; }
References schedule_.
Referenced by v8::internal::compiler::PipelineImpl::ComputeScheduledGraph(), InitializeInstructionSequence(), v8::internal::compiler::turboshaft::BuildGraphPhase::Run(), and set_schedule().
sequence()
InstructionSequence* v8::internal::compiler::TFPipelineData::sequence () const [inline]
Definition at line 330 of file pipeline-data-inl.h.
{ return sequence_; }
References sequence_.
Referenced by InitializeCodeGenerator(), and InitializeRegisterAllocationData().
set_code()
void v8::internal::compiler::TFPipelineData::set_code (MaybeIndirectHandle< Code > code) [inline]
Definition at line 245 of file pipeline-data-inl.h.
                                                {
    DCHECK(code_.is_null());
    code_ = code;
  }
References code(), code_, and v8::internal::DCHECK().
set_graph()
void v8::internal::compiler::TFPipelineData::set_graph (TFGraph * graph) [inline]
Definition at line 257 of file pipeline-data-inl.h.
{ graph_ = graph; }
References graph(), and graph_.
set_node_origins()
void v8::internal::compiler::TFPipelineData::set_node_origins (NodeOriginTable * node_origins) [inline]
Definition at line 298 of file pipeline-data-inl.h.
                                                       {
    node_origins_ = node_origins;
  }
References node_origins(), and node_origins_.
set_profile_data()
void v8::internal::compiler::TFPipelineData::set_profile_data (const ProfileDataFromFile * profile_data) [inline]
Definition at line 525 of file pipeline-data-inl.h.
                                                                 {
    profile_data_ = profile_data;
  }
References profile_data(), and profile_data_.
Referenced by v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl().
set_runtime_call_stats()
void v8::internal::compiler::TFPipelineData::set_runtime_call_stats (RuntimeCallStats * stats) [inline]
Definition at line 535 of file pipeline-data-inl.h.
                                                       {
    runtime_call_stats_ = stats;
  }
References runtime_call_stats_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::PipelineJobScope(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::~PipelineJobScope().
set_schedule()
void v8::internal::compiler::TFPipelineData::set_schedule (Schedule * schedule) [inline]
Definition at line 318 of file pipeline-data-inl.h.
                                        {
    DCHECK(!schedule_);
    schedule_ = schedule;
  }
References v8::internal::DCHECK(), schedule(), and schedule_.
set_source_position_output()
void v8::internal::compiler::TFPipelineData::set_source_position_output (std::string const & source_position_output) [inline]
Definition at line 342 of file pipeline-data-inl.h.
                                                                           {
    source_position_output_ = source_position_output;
  }
References source_position_output(), and source_position_output_.
set_source_positions()
void v8::internal::compiler::TFPipelineData::set_source_positions (SourcePositionTable * source_positions) [inline]
Definition at line 294 of file pipeline-data-inl.h.
                                                                   {
    source_positions_ = source_positions;
  }
References source_positions(), and source_positions_.
set_start_source_position()
void v8::internal::compiler::TFPipelineData::set_start_source_position (int position) [inline]
Definition at line 487 of file pipeline-data-inl.h.
                                               {
    DCHECK_EQ(start_source_position_, kNoSourcePosition);
    start_source_position_ = position;
  }
References DCHECK_EQ, v8::internal::kNoSourcePosition, and start_source_position_.
Referenced by v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl().
set_verify_graph()
void v8::internal::compiler::TFPipelineData::set_verify_graph (bool value) [inline]
Definition at line 242 of file pipeline-data-inl.h.
{ verify_graph_ = value; }
References v8::internal::value, and verify_graph_.
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::TFPipelineData::simplified () const [inline]
Definition at line 302 of file pipeline-data-inl.h.
{ return simplified_; }
References simplified_.
source_position_output()
std::string const& v8::internal::compiler::TFPipelineData::source_position_output () const [inline]
Definition at line 339 of file pipeline-data-inl.h.
                                                  {
    return source_position_output_;
  }
References source_position_output_.
Referenced by set_source_position_output().
source_positions()
SourcePositionTable* v8::internal::compiler::TFPipelineData::source_positions () const [inline]
Definition at line 293 of file pipeline-data-inl.h.
{ return source_positions_; }
References source_positions_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), InitializeWithGraphZone(), v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), v8::internal::compiler::turboshaft::BuildGraphPhase::Run(), and set_source_positions().
specialization_context()
Maybe<OuterContext> v8::internal::compiler::TFPipelineData::specialization_context () const [inline]
Definition at line 364 of file pipeline-data-inl.h.
                                                     {
    return specialization_context_;
  }
References specialization_context_.
start_source_position()
int v8::internal::compiler::TFPipelineData::start_source_position () const [inline]
Definition at line 492 of file pipeline-data-inl.h.
{ return start_source_position_; }
References start_source_position_.
verify_graph()
bool v8::internal::compiler::TFPipelineData::verify_graph () const [inline]
Definition at line 241 of file pipeline-data-inl.h.
{ return verify_graph_; }
References verify_graph_.
zone_stats()
ZoneStats* v8::internal::compiler::TFPipelineData::zone_stats () const [inline]
Definition at line 233 of file pipeline-data-inl.h.
{ return zone_stats_; }
References zone_stats_.
Member Data Documentation
allocator_
AccountingAllocator* const v8::internal::compiler::TFPipelineData::allocator_ [private]
Definition at line 574 of file pipeline-data-inl.h.
Referenced by allocator().
assembler_options_
AssemblerOptions v8::internal::compiler::TFPipelineData::assembler_options_ [private]
Definition at line 631 of file pipeline-data-inl.h.
Referenced by assembler_options(), and InitializeCodeGenerator().
broker_
std::shared_ptr<JSHeapBroker> v8::internal::compiler::TFPipelineData::broker_ [private]
Definition at line 617 of file pipeline-data-inl.h.
Referenced by broker(), broker_ptr(), DeleteCodegenZone(), and TFPipelineData().
code_
MaybeIndirectHandle<Code> v8::internal::compiler::TFPipelineData::code_ [private]
Definition at line 583 of file pipeline-data-inl.h.
Referenced by code(), and set_code().
code_generator_
CodeGenerator* v8::internal::compiler::TFPipelineData::code_generator_ = nullptr [private]
Definition at line 584 of file pipeline-data-inl.h.
Referenced by code_generator(), InitializeCodeGenerator(), and ~TFPipelineData().
codegen_zone_
Zone* v8::internal::compiler::TFPipelineData::codegen_zone_ [private]
Definition at line 615 of file pipeline-data-inl.h.
Referenced by codegen_zone(), and DeleteCodegenZone().
codegen_zone_scope_
ZoneStats::Scope v8::internal::compiler::TFPipelineData::codegen_zone_scope_ [private]
Definition at line 614 of file pipeline-data-inl.h.
Referenced by DeleteCodegenZone().
common_
CommonOperatorBuilder* v8::internal::compiler::TFPipelineData::common_ = nullptr [private]
Definition at line 596 of file pipeline-data-inl.h.
Referenced by common(), DeleteGraphZone(), InitializeWithGraphZone(), and TFPipelineData().
debug_name_
std::unique_ptr<char[]> v8::internal::compiler::TFPipelineData::debug_name_ [private]
Definition at line 576 of file pipeline-data-inl.h.
Referenced by debug_name(), and InitializeCodeGenerator().
dependencies_
CompilationDependencies* v8::internal::compiler::TFPipelineData::dependencies_ = nullptr [private]
Definition at line 616 of file pipeline-data-inl.h.
Referenced by DeleteCodegenZone(), dependencies(), and TFPipelineData().
frame_
Frame* v8::internal::compiler::TFPipelineData::frame_ = nullptr [private]
Definition at line 618 of file pipeline-data-inl.h.
Referenced by DeleteCodegenZone(), frame(), and InitializeFrameData().
graph_
TFGraph* v8::internal::compiler::TFPipelineData::graph_ = nullptr [private]
Definition at line 591 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), graph(), InitializeWithGraphZone(), set_graph(), and TFPipelineData().
graph_zone_
turboshaft::ZoneWithName<kGraphZoneName> v8::internal::compiler::TFPipelineData::graph_zone_ [private]
Definition at line 590 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), graph_zone(), InitializeWithGraphZone(), ReleaseGraphZone(), and TFPipelineData().
info_
OptimizedCompilationInfo* const v8::internal::compiler::TFPipelineData::info_ [private]
Definition at line 575 of file pipeline-data-inl.h.
Referenced by GetCodeTracer(), info(), InitializeCodeGenerator(), and TFPipelineData().
instruction_zone_
Zone* v8::internal::compiler::TFPipelineData::instruction_zone_ [private]
Definition at line 608 of file pipeline-data-inl.h.
Referenced by DeleteInstructionZone(), and instruction_zone().
instruction_zone_scope_
ZoneStats::Scope v8::internal::compiler::TFPipelineData::instruction_zone_scope_ [private]
Definition at line 607 of file pipeline-data-inl.h.
Referenced by DeleteInstructionZone().
isolate_
Isolate* const v8::internal::compiler::TFPipelineData::isolate_ [private]
Definition at line 557 of file pipeline-data-inl.h.
Referenced by GetCodeTracer(), isolate(), and TFPipelineData().
javascript_
JSOperatorBuilder* v8::internal::compiler::TFPipelineData::javascript_ = nullptr [private]
Definition at line 597 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), InitializeWithGraphZone(), javascript(), and TFPipelineData().
jsgraph_
JSGraph* v8::internal::compiler::TFPipelineData::jsgraph_ = nullptr [private]
Definition at line 598 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), jsgraph(), and TFPipelineData().
jump_optimization_info_
JumpOptimizationInfo* v8::internal::compiler::TFPipelineData::jump_optimization_info_ = nullptr [private]
Definition at line 630 of file pipeline-data-inl.h.
Referenced by InitializeCodeGenerator(), and jump_optimization_info().
machine_
MachineOperatorBuilder* v8::internal::compiler::TFPipelineData::machine_ = nullptr [private]
Definition at line 595 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), InitializeWithGraphZone(), machine(), and TFPipelineData().
max_pushed_argument_count_
size_t v8::internal::compiler::TFPipelineData::max_pushed_argument_count_ = 0 [private]
Definition at line 638 of file pipeline-data-inl.h.
Referenced by address_of_max_pushed_argument_count(), and max_pushed_argument_count().
max_unoptimized_frame_height_
size_t v8::internal::compiler::TFPipelineData::max_unoptimized_frame_height_ = 0 [private]
Definition at line 637 of file pipeline-data-inl.h.
Referenced by address_of_max_unoptimized_frame_height(), and max_unoptimized_frame_height().
may_have_unverifiable_graph_
bool v8::internal::compiler::TFPipelineData::may_have_unverifiable_graph_ = true [private]
Definition at line 577 of file pipeline-data-inl.h.
Referenced by MayHaveUnverifiableGraph().
mcgraph_
MachineGraph* v8::internal::compiler::TFPipelineData::mcgraph_ = nullptr [private]
Definition at line 599 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), and mcgraph().
node_origins_
NodeOriginTable* v8::internal::compiler::TFPipelineData::node_origins_ = nullptr [private]
Definition at line 593 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), InitializeWithGraphZone(), node_origins(), set_node_origins(), and TFPipelineData().
observe_node_manager_
ObserveNodeManager* v8::internal::compiler::TFPipelineData::observe_node_manager_ = nullptr [private]
Definition at line 601 of file pipeline-data-inl.h.
Referenced by observe_node_manager(), and TFPipelineData().
osr_helper_
std::shared_ptr<OsrHelper> v8::internal::compiler::TFPipelineData::osr_helper_ [private]
Definition at line 582 of file pipeline-data-inl.h.
Referenced by InitializeCodeGenerator(), InitializeFrameData(), InitializeOsrHelper(), osr_helper(), and osr_helper_ptr().
pipeline_statistics_
TurbofanPipelineStatistics* v8::internal::compiler::TFPipelineData::pipeline_statistics_ = nullptr [private]
Definition at line 579 of file pipeline-data-inl.h.
Referenced by pipeline_statistics().
profile_data_
const ProfileDataFromFile* v8::internal::compiler::TFPipelineData::profile_data_ = nullptr [private]
Definition at line 641 of file pipeline-data-inl.h.
Referenced by profile_data(), and set_profile_data().
register_allocation_data_
RegisterAllocationData* v8::internal::compiler::TFPipelineData::register_allocation_data_ = nullptr [private]
Definition at line 625 of file pipeline-data-inl.h.
Referenced by DeleteRegisterAllocationZone(), InitializeRegisterAllocationData(), and register_allocation_data().
register_allocation_zone_
Zone* v8::internal::compiler::TFPipelineData::register_allocation_zone_ [private]
Definition at line 624 of file pipeline-data-inl.h.
Referenced by DeleteRegisterAllocationZone(), and register_allocation_zone().
register_allocation_zone_scope_
ZoneStats::Scope v8::internal::compiler::TFPipelineData::register_allocation_zone_scope_ [private]
Definition at line 623 of file pipeline-data-inl.h.
Referenced by DeleteRegisterAllocationZone().
runtime_call_stats_
RuntimeCallStats* v8::internal::compiler::TFPipelineData::runtime_call_stats_ = nullptr [private]
Definition at line 640 of file pipeline-data-inl.h.
Referenced by runtime_call_stats(), and set_runtime_call_stats().
schedule_
Schedule* v8::internal::compiler::TFPipelineData::schedule_ = nullptr [private]
Definition at line 600 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), InitializeWithGraphZone(), reset_schedule(), schedule(), and set_schedule().
sequence_
InstructionSequence* v8::internal::compiler::TFPipelineData::sequence_ = nullptr [private]
Definition at line 609 of file pipeline-data-inl.h.
Referenced by DeleteInstructionZone(), InitializeInstructionSequence(), and sequence().
simplified_
SimplifiedOperatorBuilder* v8::internal::compiler::TFPipelineData::simplified_ = nullptr [private]
Definition at line 594 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), InitializeWithGraphZone(), simplified(), and TFPipelineData().
source_position_output_
std::string v8::internal::compiler::TFPipelineData::source_position_output_ [private]
Definition at line 628 of file pipeline-data-inl.h.
Referenced by set_source_position_output(), and source_position_output().
source_positions_
SourcePositionTable* v8::internal::compiler::TFPipelineData::source_positions_ = nullptr [private]
Definition at line 592 of file pipeline-data-inl.h.
Referenced by DeleteGraphZone(), InitializeWithGraphZone(), set_source_positions(), source_positions(), and TFPipelineData().
specialization_context_
Maybe<OuterContext> v8::internal::compiler::TFPipelineData::specialization_context_ = Nothing<OuterContext>() [private]
Definition at line 632 of file pipeline-data-inl.h.
Referenced by ChooseSpecializationContext(), and specialization_context().
start_source_position_
int v8::internal::compiler::TFPipelineData::start_source_position_ = kNoSourcePosition [private]
Definition at line 581 of file pipeline-data-inl.h.
Referenced by InitializeCodeGenerator(), set_start_source_position(), and start_source_position().
ts_data_
std::unique_ptr<turboshaft::PipelineData> v8::internal::compiler::TFPipelineData::ts_data_ [private]
Definition at line 602 of file pipeline-data-inl.h.
typer_
Typer* v8::internal::compiler::TFPipelineData::typer_ = nullptr [private]
Definition at line 585 of file pipeline-data-inl.h.
Referenced by AddTyperFlag(), CreateTyper(), and DeleteTyper().
typer_flags_
Typer::Flags v8::internal::compiler::TFPipelineData::typer_flags_ = Typer::kNoFlags [private]
Definition at line 586 of file pipeline-data-inl.h.
Referenced by AddTyperFlag(), and CreateTyper().
verify_graph_
bool v8::internal::compiler::TFPipelineData::verify_graph_ = false [private]
Definition at line 580 of file pipeline-data-inl.h.
Referenced by set_verify_graph(), and verify_graph().
zone_stats_
ZoneStats* const v8::internal::compiler::TFPipelineData::zone_stats_ [private]
Definition at line 578 of file pipeline-data-inl.h.
Referenced by zone_stats().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline-data-inl.h