v8::internal::WasmObject Class Reference
#include <wasm-objects.h>
Static Protected Member Functions
static DirectHandle< Object > ReadValueAt (Isolate *isolate, DirectHandle< HeapObject > obj, wasm::CanonicalValueType type, uint32_t offset)
Static Private Member Functions
template<typename ElementType >
static ElementType FromNumber (Tagged< Object > value)
Detailed Description
Definition at line 1392 of file wasm-objects.h.
Member Function Documentation
FromNumber()
template<typename ElementType >
ElementType v8::internal::WasmObject::FromNumber (Tagged< Object > value) [static], [private]
Definition at line 699 of file wasm-objects-inl.h.
                                                       {
  // The value must already be prepared for storing to numeric fields.
  DCHECK(IsNumber(value));
  if (IsSmi(value)) {
    return static_cast<ElementType>(Smi::ToInt(value));
  } else if (IsHeapNumber(value)) {
    double double_value = Cast<HeapNumber>(value)->value();
    if (std::is_same_v<ElementType, double> ||
        std::is_same_v<ElementType, float>) {
      return static_cast<ElementType>(double_value);
    } else {
      CHECK(std::is_integral_v<ElementType>);
      return static_cast<ElementType>(DoubleToInt32(double_value));
    }
  }
  UNREACHABLE();
}
References CHECK, v8::internal::DCHECK(), v8::internal::DoubleToInt32(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::Smi::ToInt(), v8::internal::UNREACHABLE(), and v8::internal::value.
ReadValueAt()
DirectHandle< Object > v8::internal::WasmObject::ReadValueAt (Isolate * isolate, DirectHandle< HeapObject > obj, wasm::CanonicalValueType type, uint32_t offset) [inline], [static], [protected]
Definition at line 645 of file wasm-objects-inl.h.
                                                              {
  Address field_address = obj->GetFieldAddress(offset);
  switch (type.kind()) {
    case wasm::kI8: {
      int8_t value = base::Memory<int8_t>(field_address);
      return direct_handle(Smi::FromInt(value), isolate);
    }
    case wasm::kI16: {
      int16_t value = base::Memory<int16_t>(field_address);
      return direct_handle(Smi::FromInt(value), isolate);
    }
    case wasm::kI32: {
      int32_t value = base::Memory<int32_t>(field_address);
      return isolate->factory()->NewNumberFromInt(value);
    }
    case wasm::kI64: {
      int64_t value = base::ReadUnalignedValue<int64_t>(field_address);
      return BigInt::FromInt64(isolate, value);
    }
    case wasm::kF16: {
      uint16_t value = base::Memory<uint16_t>(field_address);
      return isolate->factory()->NewNumber(fp16_ieee_to_fp32_value(value));
    }
    case wasm::kF32: {
      float value = base::Memory<float>(field_address);
      return isolate->factory()->NewNumber(value);
    }
    case wasm::kF64: {
      double value = base::ReadUnalignedValue<double>(field_address);
      return isolate->factory()->NewNumber(value);
    }
    case wasm::kS128:
      // TODO(v8:11804): implement
      UNREACHABLE();
    case wasm::kRef:
    case wasm::kRefNull: {
      ObjectSlot slot(field_address);
      return direct_handle(slot.load(isolate), isolate);
    }
    case wasm::kVoid:
    case wasm::kTop:
    case wasm::kBottom:
      UNREACHABLE();
  }
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::BigInt::FromInt64(), v8::internal::FullObjectSlot::load(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h