v8::internal::maglev::CallBuiltin Class Reference
#include <maglev-ir.h>
Public Types
enum FeedbackSlotType { kTaggedIndex
, kSmi
 }
Public Member Functions
CallBuiltin (uint64_t bitfield, Builtin builtin)
CallBuiltin (uint64_t bitfield, Builtin builtin, ValueNode *context)
bool has_feedback () const
compiler::FeedbackSource feedback () const
FeedbackSlotType slot_type () const
void set_feedback (compiler::FeedbackSource const &feedback, FeedbackSlotType slot_type)
Builtin builtin () const
Input & context_input ()
int InputCountWithoutContext () const
int InputsInRegisterCount () const
auto stack_args ()
void set_arg (int i, ValueNode *node)
int ReturnCount () const
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< CallBuiltin >
Private Member Functions
template<typename... Args>
void PushArguments (MaglevAssembler *masm, Args... extra_args)
void PassFeedbackSlotInRegister (MaglevAssembler *)
void PushFeedbackAndArguments (MaglevAssembler *)
Private Attributes
Builtin builtin_
std::optional< compiler::FeedbackSource > feedback_
FeedbackSlotType slot_type_ = kTaggedIndex
Additional Inherited Members
Detailed Description
Definition at line 10110 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallBuiltin::Base = ValueNodeT<CallBuiltin> [private]
Definition at line 10111 of file maglev-ir.h.
Member Enumeration Documentation
FeedbackSlotType
enum v8::internal::maglev::CallBuiltin::FeedbackSlotType
Enumerator
kTaggedIndex
kSmi
Definition at line 10114 of file maglev-ir.h.
{ kTaggedIndex, kSmi };
Constructor & Destructor Documentation
CallBuiltin() [1/2]
v8::internal::maglev::CallBuiltin::CallBuiltin (uint64_t bitfield, Builtin builtin) [inline]
Definition at line 10118 of file maglev-ir.h.
      : Base(bitfield), builtin_(builtin) {
    DCHECK(
        !Builtins::CallInterfaceDescriptorFor(builtin).HasContextParameter());
  }
References DCHECK.
CallBuiltin() [2/2]
v8::internal::maglev::CallBuiltin::CallBuiltin (uint64_t bitfield, Builtin builtin, ValueNode * context) [inline]
Definition at line 10126 of file maglev-ir.h.
      : Base(bitfield), builtin_(builtin) {
    DCHECK(Builtins::CallInterfaceDescriptorFor(builtin).HasContextParameter());
    // We use the last valid input for the context.
    set_input(input_count() - 1, context);
  }
References DCHECK, and v8::internal::compiler::turboshaft::detail::input_count().
Member Function Documentation
builtin()
Builtin v8::internal::maglev::CallBuiltin::builtin () const [inline]
Definition at line 10151 of file maglev-ir.h.
{ return builtin_; }
Referenced by PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and VerifyInputs().
context_input()
Input& v8::internal::maglev::CallBuiltin::context_input () [inline]
Definition at line 10152 of file maglev-ir.h.
                         {
    DCHECK(
        Builtins::CallInterfaceDescriptorFor(builtin()).HasContextParameter());
    return input(input_count() - 1);
  }
References DCHECK, and v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::CallBuiltin::feedback () const [inline]
Definition at line 10137 of file maglev-ir.h.
                                          {
    DCHECK(has_feedback());
    return feedback_.value();
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CallBuiltin::GenerateCode (MaglevAssembler * , const ProcessingState &)
has_feedback()
bool v8::internal::maglev::CallBuiltin::has_feedback () const [inline]
Definition at line 10136 of file maglev-ir.h.
{ return feedback_.has_value(); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and VerifyInputs().
InputCountWithoutContext()
int v8::internal::maglev::CallBuiltin::InputCountWithoutContext () const [inline]
Definition at line 10158 of file maglev-ir.h.
                                       {
    auto descriptor = Builtins::CallInterfaceDescriptorFor(builtin_);
    bool has_context = descriptor.HasContextParameter();
    int extra_input_count = has_context ? 1 : 0;
    return input_count() - extra_input_count;
  }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallBuiltin(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
InputsInRegisterCount()
int v8::internal::maglev::CallBuiltin::InputsInRegisterCount () const [inline]
Definition at line 10165 of file maglev-ir.h.
                                    {
    auto descriptor = Builtins::CallInterfaceDescriptorFor(builtin_);
    if (has_feedback()) {
      int slot_index = InputCountWithoutContext();
      int vector_index = slot_index + 1;
      // There are three possibilities:
      // 1. Feedback slot and vector are in register.
      // 2. Feedback slot is in register and vector is on stack.
      // 3. Feedback slot and vector are on stack.
      if (vector_index < descriptor.GetRegisterParameterCount()) {
        return descriptor.GetRegisterParameterCount() - 2;
      } else if (vector_index == descriptor.GetRegisterParameterCount()) {
        return descriptor.GetRegisterParameterCount() - 1;
      } else {
        return descriptor.GetRegisterParameterCount();
      }
    }
    return descriptor.GetRegisterParameterCount();
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::CallBuiltin::MaxCallStackArgs () const
PassFeedbackSlotInRegister()
void v8::internal::maglev::CallBuiltin::PassFeedbackSlotInRegister (MaglevAssembler *) [private]
PrintParams()
void v8::internal::maglev::CallBuiltin::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8407 of file maglev-ir.cc.
                                                                         {
  os << "(" << Builtins::name(builtin()) << ")";
}
References builtin(), and v8::internal::Builtins::name().
PushArguments()
template<typename... Args>
void v8::internal::maglev::CallBuiltin::PushArguments (MaglevAssembler * masm, Args... extra_args) [private]
PushFeedbackAndArguments()
void v8::internal::maglev::CallBuiltin::PushFeedbackAndArguments (MaglevAssembler *) [private]
ReturnCount()
int v8::internal::maglev::CallBuiltin::ReturnCount () const [inline]
Definition at line 10194 of file maglev-ir.h.
                          {
    return Builtins::CallInterfaceDescriptorFor(builtin_).GetReturnCount();
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetSecondValue().
set_arg()
void v8::internal::maglev::CallBuiltin::set_arg (int i, ValueNode * node) [inline]
Definition at line 10192 of file maglev-ir.h.
{ set_input(i, node); }
set_feedback()
void v8::internal::maglev::CallBuiltin::set_feedback (compiler::FeedbackSource const & feedback, FeedbackSlotType slot_type) [inline]
Definition at line 10145 of file maglev-ir.h.
                                                {
    feedback_ = feedback;
    slot_type_ = slot_type;
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallBuiltin().
SetValueLocationConstraints()
void v8::internal::maglev::CallBuiltin::SetValueLocationConstraints ()
slot_type()
FeedbackSlotType v8::internal::maglev::CallBuiltin::slot_type () const [inline]
Definition at line 10141 of file maglev-ir.h.
                                     {
    DCHECK(has_feedback());
    return slot_type_;
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
stack_args()
auto v8::internal::maglev::CallBuiltin::stack_args () [inline]
Definition at line 10186 of file maglev-ir.h.
                    {
    return base::make_iterator_range(
        std::make_reverse_iterator(&input(InputsInRegisterCount() - 1)),
        std::make_reverse_iterator(&input(InputCountWithoutContext() - 1)));
  }
References v8::base::make_iterator_range().
VerifyInputs()
void v8::internal::maglev::CallBuiltin::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 1052 of file maglev-ir.cc.
                                                                        {
  auto descriptor = Builtins::CallInterfaceDescriptorFor(builtin());
  int count = input_count();
  // Verify context.
  if (descriptor.HasContextParameter()) {
    CheckValueInputIs(this, count - 1, ValueRepresentation::kTagged,
                      graph_labeller);
    count--;
  }
// {all_input_count} includes the feedback slot and vector.
#ifdef DEBUG
  int all_input_count = count + (has_feedback() ? 2 : 0);
  if (descriptor.AllowVarArgs()) {
    DCHECK_GE(all_input_count, descriptor.GetParameterCount());
  } else {
    DCHECK_EQ(all_input_count, descriptor.GetParameterCount());
  }
#endif
  int i = 0;
  // Check the rest of inputs.
  for (; i < count; ++i) {
    MachineType type = i < descriptor.GetParameterCount()
                           ? descriptor.GetParameterType(i)
                           : MachineType::AnyTagged();
    CheckValueInputIs(this, i, ToValueRepresentation(type), graph_labeller);
  }
}
References v8::internal::MachineType::AnyTagged(), builtin(), v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::maglev::CheckValueInputIs(), DCHECK_EQ, DCHECK_GE, has_feedback(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::maglev::kTagged, v8::internal::maglev::ToValueRepresentation(), and v8::internal::tracing::type.
Member Data Documentation
builtin_
Builtin v8::internal::maglev::CallBuiltin::builtin_ [private]
Definition at line 10213 of file maglev-ir.h.
feedback_
std::optional<compiler::FeedbackSource> v8::internal::maglev::CallBuiltin::feedback_ [private]
Definition at line 10214 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CallBuiltin::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10134 of file maglev-ir.h.
slot_type_
FeedbackSlotType v8::internal::maglev::CallBuiltin::slot_type_ = kTaggedIndex [private]
Definition at line 10215 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc