v8::internal::CollectionBarrier Class Reference
#include <collection-barrier.h>
Public Member Functions
CollectionBarrier (Heap *heap, std::shared_ptr< v8::TaskRunner > foreground_task_runner)
bool WasGCRequested ()
bool TryRequestGC ()
void NotifyShutdownRequested ()
void StopTimeToCollectionTimer ()
void ResumeThreadsAwaitingCollection ()
void CancelCollectionAndResumeThreads ()
bool AwaitCollectionBackground (LocalHeap *local_heap)
Private Attributes
Heap * heap_
base::Mutex mutex_
base::ConditionVariable cv_wakeup_
base::ElapsedTimer timer_
std::atomic< bool > collection_requested_ {false}
bool block_for_collection_ = false
bool collection_performed_ = false
bool shutdown_requested_ = false
std::shared_ptr< v8::TaskRunner > foreground_task_runner_
Detailed Description
Definition at line 22 of file collection-barrier.h.
Constructor & Destructor Documentation
CollectionBarrier()
v8::internal::CollectionBarrier::CollectionBarrier (Heap * heap, std::shared_ptr< v8::TaskRunner > foreground_task_runner)
Definition at line 22 of file collection-barrier.cc.
    : heap_(heap), foreground_task_runner_(foreground_task_runner) {}
Member Function Documentation
AwaitCollectionBackground()
bool v8::internal::CollectionBarrier::AwaitCollectionBackground (LocalHeap * local_heap)
Definition at line 91 of file collection-barrier.cc.
                                                                       {
  bool first_thread;
  {
    // Update flag before parking this thread, this guarantees that the flag is
    // set before the next GC.
    base::MutexGuard guard(&mutex_);
    if (shutdown_requested_) return false;
    // Collection was cancelled by the main thread.
    if (!collection_requested_.load()) return false;
    first_thread = !block_for_collection_;
    block_for_collection_ = true;
    CHECK(timer_.IsStarted());
  }
  // The first thread needs to activate the stack guard and post the task.
  if (first_thread) {
    Isolate* isolate = heap_->isolate();
    ExecutionAccess access(isolate);
    isolate->stack_guard()->RequestGC();
    foreground_task_runner_->PostTask(
        std::make_unique<BackgroundCollectionInterruptTask>(heap_));
  }
  bool collection_performed = false;
  local_heap->ExecuteWhileParked([this, &collection_performed]() {
    base::MutexGuard guard(&mutex_);
    while (block_for_collection_) {
      if (shutdown_requested_) {
        collection_performed = false;
        return;
      }
      cv_wakeup_.Wait(&mutex_);
    }
    // Collection may have been cancelled while blocking for it.
    collection_performed = collection_performed_;
  });
  return collection_performed;
}
References block_for_collection_, CHECK, collection_performed_, collection_requested_, cv_wakeup_, v8::internal::LocalHeap::ExecuteWhileParked(), foreground_task_runner_, heap_, v8::internal::Heap::isolate(), v8::base::ElapsedTimer::IsStarted(), mutex_, shutdown_requested_, v8::internal::Isolate::stack_guard(), timer_, and v8::base::ConditionVariable::Wait().
CancelCollectionAndResumeThreads()
void v8::internal::CollectionBarrier::CancelCollectionAndResumeThreads ()
Definition at line 82 of file collection-barrier.cc.
                                                         {
  base::MutexGuard guard(&mutex_);
  if (timer_.IsStarted()) timer_.Stop();
  collection_requested_.store(false);
  block_for_collection_ = false;
  collection_performed_ = false;
  cv_wakeup_.NotifyAll();
}
References block_for_collection_, collection_performed_, collection_requested_, cv_wakeup_, v8::base::ElapsedTimer::IsStarted(), mutex_, v8::base::ConditionVariable::NotifyAll(), v8::base::ElapsedTimer::Stop(), and timer_.
NotifyShutdownRequested()
void v8::internal::CollectionBarrier::NotifyShutdownRequested ()
Definition at line 66 of file collection-barrier.cc.
                                                {
  base::MutexGuard guard(&mutex_);
  if (timer_.IsStarted()) timer_.Stop();
  shutdown_requested_ = true;
  cv_wakeup_.NotifyAll();
}
References cv_wakeup_, v8::base::ElapsedTimer::IsStarted(), mutex_, v8::base::ConditionVariable::NotifyAll(), shutdown_requested_, v8::base::ElapsedTimer::Stop(), and timer_.
ResumeThreadsAwaitingCollection()
void v8::internal::CollectionBarrier::ResumeThreadsAwaitingCollection ()
Definition at line 73 of file collection-barrier.cc.
                                                        {
  base::MutexGuard guard(&mutex_);
  DCHECK(!timer_.IsStarted());
  collection_requested_.store(false);
  block_for_collection_ = false;
  collection_performed_ = true;
  cv_wakeup_.NotifyAll();
}
References block_for_collection_, collection_performed_, collection_requested_, cv_wakeup_, v8::internal::DCHECK(), v8::base::ElapsedTimer::IsStarted(), mutex_, v8::base::ConditionVariable::NotifyAll(), and timer_.
StopTimeToCollectionTimer()
void v8::internal::CollectionBarrier::StopTimeToCollectionTimer ()
Definition at line 137 of file collection-barrier.cc.
                                                  {
  if (collection_requested_.load()) {
    base::MutexGuard guard(&mutex_);
    // The first thread that requests the GC, starts the timer first and *then*
    // parks itself. Since we are in a safepoint here, the timer is always
    // initialized here already.
    CHECK(timer_.IsStarted());
    base::TimeDelta delta = timer_.Elapsed();
    TRACE_EVENT_INSTANT1(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                         "V8.GC.TimeToCollectionOnBackground",
                         TRACE_EVENT_SCOPE_THREAD, "duration",
                         delta.InMillisecondsF());
    heap_->isolate()
        ->counters()
        ->gc_time_to_collection_on_background()
        ->AddTimedSample(delta);
    timer_.Stop();
  }
}
References CHECK, collection_requested_, v8::internal::Isolate::counters(), v8::base::ElapsedTimer::Elapsed(), heap_, v8::base::TimeDelta::InMillisecondsF(), v8::internal::Heap::isolate(), v8::base::ElapsedTimer::IsStarted(), mutex_, v8::base::ElapsedTimer::Stop(), timer_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_INSTANT1, and TRACE_EVENT_SCOPE_THREAD.
TryRequestGC()
bool v8::internal::CollectionBarrier::TryRequestGC ()
Definition at line 30 of file collection-barrier.cc.
                                     {
  base::MutexGuard guard(&mutex_);
  if (shutdown_requested_) return false;
  bool was_already_requested = collection_requested_.exchange(true);
  if (!was_already_requested) {
    CHECK(!timer_.IsStarted());
    timer_.Start();
  }
  return true;
}
References CHECK, collection_requested_, v8::base::ElapsedTimer::IsStarted(), mutex_, shutdown_requested_, v8::base::ElapsedTimer::Start(), and timer_.
WasGCRequested()
bool v8::internal::CollectionBarrier::WasGCRequested ()
Definition at line 26 of file collection-barrier.cc.
                                       {
  return collection_requested_.load();
}
References collection_requested_.
Member Data Documentation
block_for_collection_
bool v8::internal::CollectionBarrier::block_for_collection_ = false [private]
Definition at line 64 of file collection-barrier.h.
Referenced by AwaitCollectionBackground(), CancelCollectionAndResumeThreads(), and ResumeThreadsAwaitingCollection().
collection_performed_
bool v8::internal::CollectionBarrier::collection_performed_ = false [private]
Definition at line 68 of file collection-barrier.h.
Referenced by AwaitCollectionBackground(), CancelCollectionAndResumeThreads(), and ResumeThreadsAwaitingCollection().
collection_requested_
std::atomic<bool> v8::internal::CollectionBarrier::collection_requested_ {false} [private]
Definition at line 59 of file collection-barrier.h.
Referenced by AwaitCollectionBackground(), CancelCollectionAndResumeThreads(), ResumeThreadsAwaitingCollection(), StopTimeToCollectionTimer(), TryRequestGC(), and WasGCRequested().
cv_wakeup_
base::ConditionVariable v8::internal::CollectionBarrier::cv_wakeup_ [private]
Definition at line 54 of file collection-barrier.h.
Referenced by AwaitCollectionBackground(), CancelCollectionAndResumeThreads(), NotifyShutdownRequested(), and ResumeThreadsAwaitingCollection().
foreground_task_runner_
std::shared_ptr<v8::TaskRunner> v8::internal::CollectionBarrier::foreground_task_runner_ [private]
Definition at line 74 of file collection-barrier.h.
Referenced by AwaitCollectionBackground().
heap_
Heap* v8::internal::CollectionBarrier::heap_ [private]
Definition at line 52 of file collection-barrier.h.
Referenced by AwaitCollectionBackground(), and StopTimeToCollectionTimer().
mutex_
base::Mutex v8::internal::CollectionBarrier::mutex_ [private]
Definition at line 53 of file collection-barrier.h.
Referenced by AwaitCollectionBackground(), CancelCollectionAndResumeThreads(), NotifyShutdownRequested(), ResumeThreadsAwaitingCollection(), StopTimeToCollectionTimer(), and TryRequestGC().
shutdown_requested_
bool v8::internal::CollectionBarrier::shutdown_requested_ = false [private]
Definition at line 71 of file collection-barrier.h.
Referenced by AwaitCollectionBackground(), NotifyShutdownRequested(), and TryRequestGC().
timer_
base::ElapsedTimer v8::internal::CollectionBarrier::timer_ [private]
Definition at line 55 of file collection-barrier.h.
Referenced by AwaitCollectionBackground(), CancelCollectionAndResumeThreads(), NotifyShutdownRequested(), ResumeThreadsAwaitingCollection(), StopTimeToCollectionTimer(), and TryRequestGC().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/collection-barrier.h
/mnt/V8SourceCode/src/heap/collection-barrier.cc