v8::internal::ParserBase< Impl >::FunctionState Class Reference
#include <parser-base.h>
Classes
class FunctionOrEvalRecordingScope
class LoopScope
Public Member Functions
FunctionState (FunctionState **function_state_stack, Scope **scope_stack, DeclarationScope *scope)
~FunctionState ()
DeclarationScope * scope () const
void AddProperty ()
int expected_property_count ()
void DisableOptimization (BailoutReason reason)
BailoutReason dont_optimize_reason ()
void AddSuspend ()
int suspend_count () const
bool CanSuspend () const
FunctionKind kind () const
bool next_function_is_likely_called () const
bool previous_function_was_likely_called () const
void set_next_function_is_likely_called ()
void RecordFunctionOrEvalCall ()
bool contains_function_or_eval () const
int loop_nesting_depth () const
Target ** target_stack_address ()
Private Attributes
int expected_property_count_
int suspend_count_
int loop_nesting_depth_ = 0
FunctionState ** function_state_stack_
FunctionState * outer_function_state_
DeclarationScope * scope_
Target * target_stack_ = nullptr
BailoutReason dont_optimize_reason_
bool next_function_is_likely_called_
bool previous_function_was_likely_called_
bool contains_function_or_eval_
friend Impl
Detailed Description
template<typename Impl>
class v8::internal::ParserBase< Impl >::FunctionState
Definition at line 446 of file parser-base.h.
Constructor & Destructor Documentation
FunctionState()
template<typename Impl >
v8::internal::ParserBase< Impl >::FunctionState::FunctionState (FunctionState ** function_state_stack, Scope ** scope_stack, DeclarationScope * scope)
Definition at line 1819 of file parser-base.h.
    : BlockState(scope_stack, scope),
      expected_property_count_(0),
      suspend_count_(0),
      function_state_stack_(function_state_stack),
      outer_function_state_(*function_state_stack),
      scope_(scope),
      dont_optimize_reason_(BailoutReason::kNoReason),
      next_function_is_likely_called_(false),
      previous_function_was_likely_called_(false),
      contains_function_or_eval_(false) {
  *function_state_stack = this;
  if (outer_function_state_) {
    outer_function_state_->previous_function_was_likely_called_ =
        outer_function_state_->next_function_is_likely_called_;
    outer_function_state_->next_function_is_likely_called_ = false;
  }
}
References v8::internal::ParserBase< Impl >::FunctionState::next_function_is_likely_called_, v8::internal::ParserBase< Impl >::FunctionState::outer_function_state_, and v8::internal::ParserBase< Impl >::FunctionState::previous_function_was_likely_called_.
 FunctionState()
template<typename Impl >
v8::internal::ParserBase< Impl >::FunctionState::~FunctionState
Definition at line 1841 of file parser-base.h.
                                              {
  *function_state_stack_ = outer_function_state_;
}
Member Function Documentation
AddProperty()
template<typename Impl >
void v8::internal::ParserBase< Impl >::FunctionState::AddProperty () [inline]
Definition at line 454 of file parser-base.h.
{ expected_property_count_++; }
References v8::internal::ParserBase< Impl >::FunctionState::expected_property_count_.
Referenced by v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation().
AddSuspend()
template<typename Impl >
void v8::internal::ParserBase< Impl >::FunctionState::AddSuspend () [inline]
Definition at line 462 of file parser-base.h.
{ suspend_count_++; }
References v8::internal::ParserBase< Impl >::FunctionState::suspend_count_.
Referenced by v8::internal::ParserBase< Impl >::BuildReturnStatement(), v8::internal::ParserBase< Impl >::ParseAwaitExpression(), v8::internal::ParserBase< Impl >::ParseForAwaitStatement(), v8::internal::ParserBase< Impl >::ParseVariableDeclarations(), and v8::internal::ParserBase< Impl >::ParseYieldExpression().
CanSuspend()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::FunctionState::CanSuspend () const [inline]
Definition at line 464 of file parser-base.h.
{ return suspend_count_ > 0; }
References v8::internal::ParserBase< Impl >::FunctionState::suspend_count_.
contains_function_or_eval()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::FunctionState::contains_function_or_eval () const [inline]
Definition at line 481 of file parser-base.h.
                                           {
      return contains_function_or_eval_;
    }
References v8::internal::ParserBase< Impl >::FunctionState::contains_function_or_eval_.
Referenced by v8::internal::ParserBase< Impl >::ParseStandardForLoopWithLexicalDeclarations().
DisableOptimization()
template<typename Impl >
void v8::internal::ParserBase< Impl >::FunctionState::DisableOptimization (BailoutReason reason) [inline]
Definition at line 457 of file parser-base.h.
                                                   {
      dont_optimize_reason_ = reason;
    }
References v8::internal::ParserBase< Impl >::FunctionState::dont_optimize_reason_.
Referenced by v8::internal::ParserBase< Impl >::ParseNativeDeclaration().
dont_optimize_reason()
template<typename Impl >
BailoutReason v8::internal::ParserBase< Impl >::FunctionState::dont_optimize_reason () [inline]
Definition at line 460 of file parser-base.h.
{ return dont_optimize_reason_; }
References v8::internal::ParserBase< Impl >::FunctionState::dont_optimize_reason_.
expected_property_count()
template<typename Impl >
int v8::internal::ParserBase< Impl >::FunctionState::expected_property_count () [inline]
Definition at line 455 of file parser-base.h.
{ return expected_property_count_; }
References v8::internal::ParserBase< Impl >::FunctionState::expected_property_count_.
Referenced by v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral().
kind()
template<typename Impl >
FunctionKind v8::internal::ParserBase< Impl >::FunctionState::kind () const [inline]
Definition at line 466 of file parser-base.h.
{ return scope()->function_kind(); }
References v8::internal::DeclarationScope::function_kind(), and v8::internal::ParserBase< Impl >::FunctionState::scope().
Referenced by v8::internal::ParserBase< Impl >::is_async_function(), v8::internal::ParserBase< Impl >::is_async_generator(), v8::internal::ParserBase< Impl >::is_await_allowed(), v8::internal::ParserBase< Impl >::is_await_as_identifier_disallowed(), v8::internal::ParserBase< Impl >::is_generator(), v8::internal::ParserBase< Impl >::is_resumable(), v8::internal::ParserBase< Impl >::IsAwaitAsIdentifierDisallowed(), v8::internal::ParserBase< Impl >::ParseAwaitExpression(), v8::internal::ParserBase< Impl >::ParseIdentifier(), v8::internal::ParserBase< Impl >::ParseReturnStatement(), and v8::internal::ParserBase< Impl >::ParseYieldExpression().
loop_nesting_depth()
template<typename Impl >
int v8::internal::ParserBase< Impl >::FunctionState::loop_nesting_depth () const [inline]
Definition at line 516 of file parser-base.h.
{ return loop_nesting_depth_; }
References v8::internal::ParserBase< Impl >::FunctionState::loop_nesting_depth_.
Referenced by v8::internal::ParserBase< Impl >::loop_nesting_depth().
next_function_is_likely_called()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::FunctionState::next_function_is_likely_called () const [inline]
Definition at line 468 of file parser-base.h.
                                                {
      return next_function_is_likely_called_;
    }
References v8::internal::ParserBase< Impl >::FunctionState::next_function_is_likely_called_.
previous_function_was_likely_called()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::FunctionState::previous_function_was_likely_called () const [inline]
Definition at line 472 of file parser-base.h.
                                                     {
      return previous_function_was_likely_called_;
    }
References v8::internal::ParserBase< Impl >::FunctionState::previous_function_was_likely_called_.
Referenced by v8::internal::ParserBase< Impl >::ParseExpressionCoverGrammar().
RecordFunctionOrEvalCall()
template<typename Impl >
void v8::internal::ParserBase< Impl >::FunctionState::RecordFunctionOrEvalCall () [inline]
Definition at line 480 of file parser-base.h.
{ contains_function_or_eval_ = true; }
References v8::internal::ParserBase< Impl >::FunctionState::contains_function_or_eval_.
Referenced by v8::internal::ParserBase< Impl >::CheckPossibleEvalCall(), and v8::internal::ParserBase< Impl >::NewFunctionScope().
scope()
template<typename Impl >
DeclarationScope* v8::internal::ParserBase< Impl >::FunctionState::scope () const [inline]
Definition at line 452 of file parser-base.h.
{ return scope_->AsDeclarationScope(); }
References v8::internal::Scope::AsDeclarationScope(), and v8::internal::ParserBase< Impl >::FunctionState::scope_.
Referenced by v8::internal::ParserBase< Impl >::IsAwaitAsIdentifierDisallowed(), and v8::internal::ParserBase< Impl >::FunctionState::kind().
set_next_function_is_likely_called()
template<typename Impl >
void v8::internal::ParserBase< Impl >::FunctionState::set_next_function_is_likely_called () [inline]
Definition at line 476 of file parser-base.h.
                                              {
      next_function_is_likely_called_ = !v8_flags.max_lazy;
    }
References v8::internal::ParserBase< Impl >::FunctionState::next_function_is_likely_called_, and v8::internal::v8_flags.
Referenced by v8::internal::ParserBase< Impl >::ParseExpressionCoverGrammar(), v8::internal::ParserBase< Impl >::ParsePrimaryExpression(), and v8::internal::ParserBase< Impl >::ParseUnaryOrPrefixExpression().
suspend_count()
template<typename Impl >
int v8::internal::ParserBase< Impl >::FunctionState::suspend_count () const [inline]
Definition at line 463 of file parser-base.h.
{ return suspend_count_; }
References v8::internal::ParserBase< Impl >::FunctionState::suspend_count_.
Referenced by v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral().
target_stack_address()
template<typename Impl >
Target** v8::internal::ParserBase< Impl >::FunctionState::target_stack_address () [inline]
Definition at line 518 of file parser-base.h.
{ return &target_stack_; }
References v8::internal::ParserBase< Impl >::FunctionState::target_stack_.
Referenced by v8::internal::ParserBase< Impl >::target_stack().
Member Data Documentation
contains_function_or_eval_
template<typename Impl >
bool v8::internal::ParserBase< Impl >::FunctionState::contains_function_or_eval_ [private]
Definition at line 547 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::contains_function_or_eval(), v8::internal::ParserBase< Impl >::FunctionState::FunctionOrEvalRecordingScope::FunctionOrEvalRecordingScope(), and v8::internal::ParserBase< Impl >::FunctionState::RecordFunctionOrEvalCall().
dont_optimize_reason_
template<typename Impl >
BailoutReason v8::internal::ParserBase< Impl >::FunctionState::dont_optimize_reason_ [private]
Definition at line 536 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::DisableOptimization(), and v8::internal::ParserBase< Impl >::FunctionState::dont_optimize_reason().
expected_property_count_
template<typename Impl >
int v8::internal::ParserBase< Impl >::FunctionState::expected_property_count_ [private]
Definition at line 522 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::AddProperty(), and v8::internal::ParserBase< Impl >::FunctionState::expected_property_count().
function_state_stack_
template<typename Impl >
FunctionState** v8::internal::ParserBase< Impl >::FunctionState::function_state_stack_ [private]
Definition at line 530 of file parser-base.h.
Impl
template<typename Impl >
friend v8::internal::ParserBase< Impl >::FunctionState::Impl [private]
Definition at line 549 of file parser-base.h.
loop_nesting_depth_
template<typename Impl >
int v8::internal::ParserBase< Impl >::FunctionState::loop_nesting_depth_ = 0 [private]
Definition at line 528 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::loop_nesting_depth(), v8::internal::ParserBase< Impl >::FunctionState::LoopScope::LoopScope(), and v8::internal::ParserBase< Impl >::FunctionState::LoopScope::~LoopScope().
next_function_is_likely_called_
template<typename Impl >
bool v8::internal::ParserBase< Impl >::FunctionState::next_function_is_likely_called_ [private]
Definition at line 543 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::FunctionState(), v8::internal::ParserBase< Impl >::FunctionState::next_function_is_likely_called(), and v8::internal::ParserBase< Impl >::FunctionState::set_next_function_is_likely_called().
outer_function_state_
template<typename Impl >
FunctionState* v8::internal::ParserBase< Impl >::FunctionState::outer_function_state_ [private]
Definition at line 531 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::FunctionState().
previous_function_was_likely_called_
template<typename Impl >
bool v8::internal::ParserBase< Impl >::FunctionState::previous_function_was_likely_called_ [private]
Definition at line 544 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::FunctionState(), and v8::internal::ParserBase< Impl >::FunctionState::previous_function_was_likely_called().
scope_
template<typename Impl >
DeclarationScope* v8::internal::ParserBase< Impl >::FunctionState::scope_ [private]
Definition at line 532 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::scope().
suspend_count_
template<typename Impl >
int v8::internal::ParserBase< Impl >::FunctionState::suspend_count_ [private]
Definition at line 525 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::AddSuspend(), v8::internal::ParserBase< Impl >::FunctionState::CanSuspend(), and v8::internal::ParserBase< Impl >::FunctionState::suspend_count().
target_stack_
template<typename Impl >
Target* v8::internal::ParserBase< Impl >::FunctionState::target_stack_ = nullptr [private]
Definition at line 533 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::FunctionState::target_stack_address().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/parser-base.h