v8::internal::V8HeapCompressionSchemeImpl< Cage > Class Template Reference
#include <ptr-compr.h>
Static Public Member Functions
static constexpr Address GetPtrComprCageBaseAddress (Address on_heap_addr)
static Address GetPtrComprCageBaseAddress (PtrComprCageBase cage_base)
static Tagged_t CompressObject (Address tagged)
static constexpr Tagged_t CompressAny (Address tagged)
static Address DecompressTaggedSigned (Tagged_t raw_value)
static Address DecompressTagged (Tagged_t raw_value)
template<typename ProcessPointerCallback >
static void ProcessIntermediatePointers (Address raw_value, ProcessPointerCallback callback)
static void InitBase (Address base)
static V8_CONST Address base ()
Detailed Description
template<typename Cage>
class v8::internal::V8HeapCompressionSchemeImpl< Cage >
Definition at line 23 of file ptr-compr.h.
Member Function Documentation
base()
template<typename Cage >
static V8_CONST Address v8::internal::V8HeapCompressionSchemeImpl< Cage >::base () [inline], [static]
Referenced by v8::internal::Isolate::Init(), v8::internal::IsolateGroup::InitializeOncePerProcess(), and v8::internal::InstructionStream::main_cage_base().
CompressAny()
template<typename Cage >
constexpr Tagged_t v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressAny (Address tagged) [inline], [static], [constexpr]
Definition at line 293 of file ptr-compr-inl.h.
                    {
  UNREACHABLE();
  return {};
}
References UNREACHABLE.
Referenced by v8::internal::Heap::CreateReadOnlyHeapObjects(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitAllocatePage(), v8::internal::FastInReadOnlySpaceOrSmallSmi(), and v8::internal::MemsetTagged().
CompressObject()
template<typename Cage >
Tagged_t v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject (Address tagged) [inline], [static]
Definition at line 287 of file ptr-compr-inl.h.
                                                                         {
  UNREACHABLE();
}
References UNREACHABLE.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DecodeTaggedSlots(), v8::internal::StringShape::DispatchToSpecificType(), v8::internal::InstanceTypeChecker::IsOneByteString(), v8::internal::InstanceTypeChecker::IsTwoByteString(), v8::internal::JsonStringifier::SimplePropertyKeyCache::MaybeCompress(), v8::internal::Factory::NewMapImpl(), v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), v8::internal::UpdateTypedSlotHelper::UpdateTypedSlot(), v8::internal::Isolate::VerifyStaticRoots(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
DecompressTagged()
template<typename Cage >
Address v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged (Tagged_t raw_value) [inline], [static]
Definition at line 308 of file ptr-compr-inl.h.
                        {
  UNREACHABLE();
}
References UNREACHABLE.
Referenced by v8::internal::ReadOnlyRoots::address_at(), v8::internal::ClearedTrustedValue(), v8::internal::ClearedValue(), v8::internal::TranslatedState::DecompressIfNeeded(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeStrong(), anonymous_namespace{objects-printer.cc}::GetObjectFromRaw(), v8::internal::UpdateTypedSlotHelper::GetTargetObject(), v8::internal::ReadOnlyRoots::InitFromStaticRootsTable(), v8::internal::wasm::Handlers< Compressed >::s2s_RefStructGet(), v8::internal::anonymous_namespace{elements.cc}::SortIndices(), v8::internal::TaggedValue::ToMaybeObject(), v8::internal::StrongTaggedValue::ToObject(), v8::internal::UpdateTypedSlotHelper::UpdateTypedSlot(), v8::internal::Isolate::VerifyStaticRoots(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
DecompressTaggedSigned()
template<typename Cage >
Address v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTaggedSigned (Tagged_t raw_value) [inline], [static]
Definition at line 301 of file ptr-compr-inl.h.
                        {
  UNREACHABLE();
}
References UNREACHABLE.
Referenced by v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
GetPtrComprCageBaseAddress() [1/2]
template<typename Cage >
constexpr Address v8::internal::V8HeapCompressionSchemeImpl< Cage >::GetPtrComprCageBaseAddress (Address on_heap_addr) [inline], [static], [constexpr]
Definition at line 279 of file ptr-compr-inl.h.
                          {
  UNREACHABLE();
  return {};
}
References UNREACHABLE.
Referenced by v8::internal::EmbedderDataSlot::store_tagged(), and v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::VisitConservativelyIfPointer().
GetPtrComprCageBaseAddress() [2/2]
template<typename Cage >
static Address v8::internal::V8HeapCompressionSchemeImpl< Cage >::GetPtrComprCageBaseAddress (PtrComprCageBase cage_base) [inline], [static]
InitBase()
template<typename Cage >
static void v8::internal::V8HeapCompressionSchemeImpl< Cage >::InitBase (Address base) [inline], [static]
Referenced by v8::internal::IsolateGroup::InitializeOncePerProcess(), and v8::internal::Isolate::SetIsolateThreadLocals().
ProcessIntermediatePointers()
template<typename Cage >
template<typename ProcessPointerCallback >
void v8::internal::V8HeapCompressionSchemeImpl< Cage >::ProcessIntermediatePointers (Address raw_value, ProcessPointerCallback callback) [inline], [static]
Definition at line 316 of file ptr-compr-inl.h.
                                                        {
  UNREACHABLE();
}
References UNREACHABLE.
Referenced by v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::VisitPointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/globals.h
/mnt/V8SourceCode/src/common/ptr-compr.h
/mnt/V8SourceCode/src/common/ptr-compr-inl.h