v8::internal::Smi Class Reference
#include <smi.h>
Static Public Member Functions
static constexpr Tagged< Smi > ToUint32Smi (Tagged< Smi > smi)
static constexpr int ToInt (const Tagged< Object > object)
static constexpr Tagged< Smi > FromInt (int value)
static constexpr Tagged< Smi > FromIntptr (intptr_t value)
static constexpr Tagged< Smi > From31BitPattern (int value)
template<typename E >
static constexpr Tagged< Smi > FromEnum (E value) requires std
template<typename T >
static constexpr bool IsValid (T value) requires(std
static V8_EXPORT_PRIVATE Address LexicographicCompare (Isolate *isolate, Tagged< Smi > x, Tagged< Smi > y)
static V8_EXPORT_PRIVATE void SmiPrint (Tagged< Smi > smi, std::ostream &os)
static constexpr Tagged< Smi > zero ()
static constexpr Tagged< Smi > uninitialized_deserialization_value ()
Static Public Attributes
static constexpr int kMinValue = kSmiMinValue
static constexpr int kMaxValue = kSmiMaxValue
Detailed Description
Definition at line 25 of file smi.h.
Member Function Documentation
From31BitPattern()
static constexpr Tagged<Smi> v8::internal::Smi::From31BitPattern (int value) [inline], [static], [constexpr]
Definition at line 52 of file smi.h.
                                                                  {
    return Smi::FromInt((value << (32 - kSmiValueSize)) >>
                        (32 - kSmiValueSize));
  }
References FromInt(), v8::internal::kSmiValueSize, and v8::internal::value.
Referenced by v8::internal::FeedbackNexus::ConfigureLexicalVarMode(), and v8::internal::anonymous_namespace{compilation-cache-table.cc}::ScriptHash().
FromEnum()
template<typename E >
static constexpr Tagged<Smi> v8::internal::Smi::FromEnum (E value) [inline], [static], [constexpr]
Definition at line 58 of file smi.h.
  {
    static_assert(sizeof(E) <= sizeof(int));
    return FromInt(static_cast<int>(value));
  }
  // Returns whether value can be represented in a Smi.
  template <typename T>
  static inline bool constexpr IsValid(T value)
    requires(std::is_integral_v<T> && std::is_signed_v<T>)
  {
    DCHECK_EQ(Internals::IsValidSmi(value),
              value >= kMinValue && value <= kMaxValue);
    return Internals::IsValidSmi(value);
  }
References FromInt(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::AsHandle(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_BigIntUnaryOp(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), v8::internal::RELEASE_ACQUIRE_ACCESSORS_CHECKED2(), v8::internal::SharedFunctionInfo::set_bytecode_array(), and v8::internal::SharedFunctionInfo::set_uncompiled_data_with_preparse_data().
FromInt()
static constexpr Tagged<Smi> v8::internal::Smi::FromInt (int value) [inline], [static], [constexpr]
Definition at line 38 of file smi.h.
                                                         {
    DCHECK(Smi::IsValid(value));
    return Tagged<Smi>(Internals::IntegralToSmi(value));
  }
References v8::internal::DCHECK(), v8::internal::Internals::IntegralToSmi(), IsValid(), v8::internal::Tagged< Smi >, and v8::internal::value.
Referenced by v8::internal::MacroAssembler::Abort(), v8::internal::OrderedHashMap::Add(), v8::internal::OrderedNameDictionary::Add(), v8::internal::NameToIndexHashTable::Add(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddArguments(), v8::internal::ObjectDescriptor< IsolateT >::AddComputed(), v8::internal::ApiNatives::AddDataProperty(), v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::ObjectDescriptor< IsolateT >::AddIndexedProperty(), v8::Isolate::AddMessageListenerWithErrorLevel(), v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty(), v8::internal::Heap::AddRetainedMaps(), v8::internal::ReplacementStringBuilder::AddSubjectSlice(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::OrderedHashTable< Derived, entrysize >::Allocate(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::FieldType::Any(), v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::ApplyDeferredCommands(), v8::internal::ArrayConstructInitializeElements(), v8::internal::anonymous_namespace{simd.cc}::ArrayIndexOfIncludes(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayInitSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewSegment(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::AsHandle(), v8::internal::ScriptCacheKey::AsHandle(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::PropertyDetails::AsSmi(), v8::internal::Literal::AsSmiLiteral(), v8::internal::interpreter::BytecodeArrayWriter::BindJumpTableEntry(), v8::internal::BIT_FIELD_ACCESSORS(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildFixedDoubleArray(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::Literal::BuildValue(), v8::internal::BUILTIN(), v8::internal::JsonParser< Char >::CalculateFileLocation(), v8::internal::PropertyCallbackArguments::CallIndexedQuery(), v8::internal::PropertyCallbackArguments::CallNamedQuery(), v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeHeapNumber(), v8::internal::Isolate::CheckDetachedContextsAfterGC(), v8::internal::CheckObjectType(), v8::internal::ContextCell::clear_tagged_value(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::FeedbackCollectorReducer< Next >::CombineFeedback(), v8::internal::FeedbackCollectorReducer< Next >::CombineFeedbackOnException(), v8::internal::anonymous_namespace{keys.cc}::CommonCopyEnumKeysTo(), v8::internal::JSTemporalPlainTime::Compare(), v8::internal::Compiler::Compile(), v8::internal::FeedbackNexus::ConfigureMegamorphic(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCaseHelper(), v8::internal::Object::ConvertToLength(), v8::internal::ScopeInfo::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::Create(), v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::ScopeInfo::CreateForBootstrapping(), v8::internal::JSReceiver::CreateIdentityHash(), v8::internal::Heap::CreateInitialMutableObjects(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::Isolate::date_cache_stamp(), v8::internal::SharedStructTypeRegistry::deleted_element(), v8::internal::OffHeapHashTableBase< Derived >::deleted_element(), v8::internal::StringForwardingTable::deleted_element(), v8::internal::StringTable::deleted_element(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DirectCollectElementIndicesImpl(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::JSDate::DoGetField(), v8::internal::FactoryBase< Impl >::DoubleToString(), v8::internal::Operand::EmbeddedNumber(), v8::internal::OffHeapHashTableBase< Derived >::empty_element(), v8::internal::StringTable::empty_element(), v8::internal::EncodeI32ExceptionValue(), v8::internal::wasm::WasmExportWrapperCache::EnsureCapacity(), v8::internal::FeedbackCollectorReducer< Next >::FeedbackIs(), v8::internal::baseline::BaselineCompiler::Flag16AsSmi(), v8::internal::baseline::BaselineCompiler::Flag8AsSmi(), From31BitPattern(), FromEnum(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::GeneratorStore(), v8::internal::Context::Get(), v8::internal::wasm::WasmGraphBuilderBase::GetBuiltinPointerTarget(), v8::internal::wasm::GetCustomSections(), v8::internal::wasm::GetExports(), v8::internal::OrderedHashMap::GetHash(), v8::internal::JSReceiver::GetIdentityHash(), v8::internal::wasm::GetImports(), v8::internal::anonymous_namespace{runtime-debug.cc}::GetJSPositionInfo(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::GetNameTable(), v8::internal::Heap::GetNextTemplateSerialNumber(), v8::internal::JSReceiver::GetOrCreateIdentityHash(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::Object::GetSimpleHash(), v8::internal::Debug::GetSourceBreakLocations(), v8::internal::LookupIterator::GetStringPropertyValue(), v8::internal::Genesis::GetThrowTypeErrorIntrinsic(), v8::internal::JSDate::GetUTCField(), v8::internal::JSLocale::GetWeekInfo(), v8::internal::CompilationCacheShape::HashForObject(), v8::internal::FeedbackNexus::ic_state(), v8::internal::NativeContext::IncrementErrorsThrown(), v8::internal::wasm::LiftoffAssembler::IncrementSmi(), v8::internal::baseline::BaselineAssembler::IncrementSmi(), v8::internal::baseline::BaselineCompiler::IndexAsSmi(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedEnumerator(), v8::internal::JSRegExp::Initialize(), v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), v8::internal::JSMessageObject::InitializeSourcePositions(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::DependentCode::InsertWeakCode(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::Genesis::InstallSpecialObjects(), v8::internal::Genesis::InstallTypedArray(), v8::internal::InstallWithIntrinsicDefaultProto(), v8::internal::baseline::BaselineCompiler::IntAsSmi(), v8::internal::anonymous_namespace{js-objects.cc}::InvalidateOnePrototypeValidityCellInternal(), v8::internal::PropertyCell::InvalidateProtector(), v8::internal::Map::IsPrototypeValidityCellValid(), v8::internal::CodeStubAssembler::IsSetSmi(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::IsValid(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::IsValidSmi(), v8::internal::baseline::BaselineCompiler::JumpIfToBoolean(), v8::internal::Heap::LeftTrimFixedArray(), LexicographicCompare(), v8::internal::LoadHandler::LoadAccessorFromPrototype(), v8::internal::LoadHandler::LoadApiGetter(), v8::internal::LoadHandler::LoadConstantFromPrototype(), v8::internal::LoadHandler::LoadElement(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorOrUndefinedIfJitless(), v8::internal::LoadHandler::LoadField(), v8::internal::LoadHandler::LoadGeneric(), v8::internal::LoadHandler::LoadGlobal(), v8::internal::LoadHandler::LoadIndexedString(), v8::internal::LoadHandler::LoadInterceptor(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::LoadHandler::LoadModuleExport(), v8::internal::LoadHandler::LoadNativeDataProperty(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::LoadHandler::LoadNormal(), v8::internal::LoadHandler::LoadProxy(), v8::internal::LoadHandler::LoadSlow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadSmi(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadSmiConstant(), v8::internal::LoadHandler::LoadWasmArrayElement(), v8::internal::LoadHandler::LoadWasmStructField(), v8::internal::maglev::MaglevAssembler::MaterialiseValueNode(), v8::internal::ScopeIterator::MaterializeScopeDetails(), v8::internal::OrderedHashTableIterator< Derived, TableType >::MoveNext(), v8::internal::wasm::WasmExportWrapperCache::New(), v8::Integer::New(), v8::internal::ClassBoilerplate::New(), v8::internal::Factory::NewArgumentsObject(), v8::internal::Factory::NewExperimentalRegExpData(), v8::internal::Factory::NewIrRegExpData(), v8::internal::Factory::NewJSArrayStorage(), v8::internal::Factory::NewJSArrayWithUnverifiedElements(), v8::internal::Factory::NewJSMessageObject(), v8::internal::Factory::NewJSSharedArray(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::FactoryBase< Impl >::NewNumberFromInt64(), v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::Factory::NewProtector(), v8::internal::anonymous_namespace{runtime-scopes.cc}::NewSloppyArguments(), v8::internal::Factory::NewTransitionArray(), v8::internal::JSSegmentIterator::Next(), v8::internal::Heap::NextDebuggingId(), v8::internal::Heap::NextScriptId(), v8::internal::Heap::NextStackTraceId(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::NoContextConstant(), v8::internal::FieldType::None(), v8::internal::JSSynchronizationPrimitive::NumWaitersForTesting(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::FeedbackCollectorReducer< Next >::OverwriteFeedback(), v8::internal::JsonParser< Char >::ParseJsonArray(), v8::internal::JsonParser< Char >::ParseJsonNumber(), v8::internal::InterpretedFrame::PatchBytecodeOffset(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand(), v8::internal::anonymous_namespace{runtime-literals.cc}::PreInitializeLiteralSite(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::PropertyCallbackArguments::PropertyCallbackArguments(), v8::internal::wasm::WasmExportWrapperCache::PutInternal(), v8::internal::WasmObject::ReadValueAt(), v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::RecordCommand(), v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::RecordFallThroughPath(), v8::internal::MathRandom::RefillCache(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), v8::internal::RELEASE_ACQUIRE_ACCESSORS(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement(), v8::internal::JsonParser< Char >::ReportUnexpectedToken(), v8::internal::NativeContext::ResetErrorsThrown(), v8::internal::JSDurationFormat::ResolvedOptions(), v8::internal::RUNTIME_FUNCTION(), v8::internal::RUNTIME_FUNCTION_RETURN_PAIR(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::internal::CodeStubAssembler::SelectSmiConstant(), v8::internal::SourceTextModuleDescriptor::AstModuleRequest::Serialize(), v8::internal::JsonStringifier::SerializeElement(), v8::internal::SourceTextModuleDescriptor::SerializeRegularExports(), v8::internal::ObjectBoilerplateDescription::set_backing_store_size(), v8::internal::RegExpMatchInfo::set_capture(), v8::internal::PrototypeUsers::set_empty_slot_index(), v8::internal::ClassPositions::set_end(), v8::internal::ObjectBoilerplateDescription::set_flags(), v8::internal::RegExpData::set_flags(), v8::internal::NameDictionary::set_flags(), v8::internal::Script::set_flags(), v8::internal::Oddball::set_kind(), v8::internal::ArrayList::set_length(), v8::internal::ScriptContextTable::set_length(), v8::internal::RegExpMatchInfo::set_number_of_capture_registers(), v8::internal::SlicedString::set_offset(), v8::internal::NumberDictionary::set_requires_slow_elements(), v8::internal::ClassPositions::set_start(), v8::internal::AllocationSite::set_transition_info(), v8::internal::RegExpData::set_type_tag(), v8::internal::anonymous_namespace{literal-objects.cc}::SetAccessorPlaceholderIndices(), v8::internal::anonymous_namespace{handler-configuration.cc}::SetBitFieldValue(), v8::internal::JSDate::SetCachedFields(), v8::internal::Heap::SetConstructStubCreateDeoptPCOffset(), v8::internal::Heap::SetConstructStubInvokeDeoptPCOffset(), v8::internal::JSArray::SetContent(), v8::debug::SetContextId(), v8::internal::Heap::SetDeoptPCOffsetAfterAdaptShadowStack(), v8::internal::anonymous_namespace{wasm-objects.cc}::SetEntry(), v8::internal::FeedbackCollectorReducer< Next >::SetFeedbackVector(), v8::internal::WasmTableObject::SetFunctionTablePlaceholder(), v8::internal::OrderedNameDictionary::SetHash(), v8::internal::anonymous_namespace{js-objects.cc}::SetHashAndUpdateProperties(), v8::internal::HashTableBase::SetInitialNumberOfElements(), v8::internal::Heap::SetInterpreterEntryReturnPCOffset(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetLengthImpl(), v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfBuckets(), v8::internal::HashTableBase::SetNumberOfDeletedElements(), v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfDeletedElements(), v8::internal::HashTableBase::SetNumberOfElements(), v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfElements(), v8::internal::TransitionArray::SetNumberOfPrototypeTransitions(), v8::internal::TransitionArray::SetNumberOfTransitions(), v8::internal::OrderedHashTable< Derived, entrysize >::SetRemovedIndexAt(), v8::internal::FreeSpace::SetSize(), v8::internal::FeedbackNexus::SetSpeculationMode(), v8::internal::anonymous_namespace{wasm-objects.cc}::SetUsedLength(), v8::internal::JSTemporalDuration::Sign(), v8::internal::Factory::SizeToString(), v8::internal::maglev::MaglevAssembler::SmiAddConstant(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::maglev::MaglevAssembler::SmiSubConstant(), v8::internal::StoreHandler::StoreAccessorFromPrototype(), v8::internal::StoreHandler::StoreApiSetter(), v8::internal::StoreHandler::StoreField(), v8::internal::StoreHandler::StoreGeneric(), v8::internal::StoreHandler::StoreGlobalProxy(), v8::internal::StoreHandler::StoreInterceptor(), v8::internal::StoreHandler::StoreNativeDataProperty(), v8::internal::StoreHandler::StoreNormal(), v8::internal::StoreHandler::StoreOwnTransition(), v8::internal::StoreHandler::StoreProxy(), v8::internal::StoreHandler::StoreSlow(), v8::internal::StoreHandler::StoreTransition(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEncodeWtf8ArrayImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8ArrayImpl(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewWtf16Encode(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewWtf8Encode(), v8::internal::TF_BUILTIN(), v8::internal::Isolate::ThrowAt(), v8::Value::ToArrayIndex(), v8::internal::maglev::SmiConstant::ToBoolean(), v8::internal::maglev::MaglevAssembler::ToBoolean(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle(), v8::internal::Object::ToLength(), v8::internal::BigInt::ToNumber(), ToUint32Smi(), v8::internal::LoadHandler::TransitionAndLoadElement(), v8::internal::Map::TryGetConstructor(), v8::internal::RegExpResultsCache_MatchGlobalAtom::TryInsert(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), v8::internal::baseline::BaselineCompiler::UintAsSmi(), v8::internal::StringForwardingTable::unused_element(), v8::internal::NumberDictionary::UpdateMaxNumberKey(), v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::FutexEmulation::WaitSync(), and zero().
FromIntptr()
static constexpr Tagged<Smi> v8::internal::Smi::FromIntptr (intptr_t value) [inline], [static], [constexpr]
Definition at line 43 of file smi.h.
                                                                 {
    DCHECK(Smi::IsValid(value));
    int smi_shift_bits = kSmiTagSize + kSmiShiftSize;
    return Tagged<Smi>((static_cast<Address>(value) << smi_shift_bits) |
                       kSmiTag);
  }
References v8::internal::DCHECK(), IsValid(), v8::internal::kSmiShiftSize, v8::internal::kSmiTag, v8::internal::kSmiTagSize, v8::internal::Tagged< Smi >, and v8::internal::value.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildMultiReturnFixedArrayFromIterable(), v8::internal::MapWord::FromForwardingAddress(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::FactoryBase< Impl >::NewNumberFromSize(), and v8::internal::FreeSpace::SetNext().
IsValid()
template<typename T >
static constexpr bool v8::internal::Smi::IsValid (T value) [inline], [static], [constexpr]
Definition at line 75 of file smi.h.
  {
    DCHECK_EQ(Internals::IsValidSmi(value), value <= kMaxValue);
    return Internals::IsValidSmi(value);
  }
References DCHECK_EQ, v8::internal::Internals::IsValidSmi(), kMaxValue, and v8::internal::value.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildConvertUint32ToSmiWithSaturation(), v8::internal::DoubleToSmiInteger(), FromInt(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), FromIntptr(), v8::internal::Context::Get(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::maglev::Graph::GetSmiConstant(), v8::internal::maglev::MaglevGraphBuilder::GetTaggedValue(), v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), v8::internal::maglev::MaglevGraphBuilder::GetUint32ElementIndex(), v8::internal::maglev::MaglevAssembler::MaterialiseValueNode(), v8::Integer::New(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::FactoryBase< Impl >::NewNumberFromInt64(), v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::RegExp::NewWithBacktrackLimit(), v8::internal::JSSegmentIterator::Next(), v8::internal::Isolate::NextOptimizationId(), v8::internal::JsonParser< Char >::ParseJsonNumberAsDoubleOrSmi(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitSegment(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewSegment(), v8::internal::ScriptCacheKey::ScriptCacheKey(), v8::internal::SourceTextModuleDescriptor::Entry::Serialize(), v8::internal::interpreter::HandlerTableBuilder::SetHandlerTarget(), v8::ObjectTemplate::SetInternalFieldCount(), v8::internal::interpreter::HandlerTableBuilder::SetTryRegionEnd(), v8::internal::interpreter::HandlerTableBuilder::SetTryRegionStart(), v8::internal::compiler::JSGraph::SmiConstant(), v8::internal::maglev::SmiConstant::SmiConstant(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast(), v8::internal::RegExpResultsCache_MatchGlobalAtom::TryInsert(), v8::internal::DateParser::TimeZoneComposer::Write(), and v8::internal::DateParser::DayComposer::Write().
LexicographicCompare()
Address v8::internal::Smi::LexicographicCompare (Isolate * isolate, Tagged< Smi > x, Tagged< Smi > y) [static]
Definition at line 6653 of file objects.cc.
                                                 {
  DisallowGarbageCollection no_gc;
  DisallowJavascriptExecution no_js(isolate);
  int x_value = Smi::ToInt(x);
  int y_value = Smi::ToInt(y);
  // If the integers are equal so are the string representations.
  if (x_value == y_value) return Smi::FromInt(0).ptr();
  // If one of the integers is zero the normal integer order is the
  // same as the lexicographic order of the string representations.
  if (x_value == 0 || y_value == 0) {
    return Smi::FromInt(x_value < y_value ? -1 : 1).ptr();
  }
  // If only one of the integers is negative the negative number is
  // smallest because the char code of '-' is less than the char code
  // of any digit. Otherwise, we make both values positive.
  // Use unsigned values otherwise the logic is incorrect for -MIN_INT on
  // architectures using 32-bit Smis.
  uint32_t x_scaled = x_value;
  uint32_t y_scaled = y_value;
  if (x_value < 0) {
    if (y_value >= 0) {
      return Smi::FromInt(-1).ptr();
    } else {
      y_scaled = base::NegateWithWraparound(y_value);
    }
    x_scaled = base::NegateWithWraparound(x_value);
  } else if (y_value < 0) {
    return Smi::FromInt(1).ptr();
  }
  // clang-format off
  static const uint32_t kPowersOf10[] = {
      1, 10, 100, 1000,
      10 * 1000, 100 * 1000, 1000 * 1000, 10 * 1000 * 1000,
      100 * 1000 * 1000, 1000 * 1000 * 1000};
  // clang-format on
  // If the integers have the same number of decimal digits they can be
  // compared directly as the numeric order is the same as the
  // lexicographic order. If one integer has fewer digits, it is scaled
  // by some power of 10 to have the same number of digits as the longer
  // integer. If the scaled integers are equal it means the shorter
  // integer comes first in the lexicographic order.
  // From http://graphics.stanford.edu/~seander/bithacks.html#IntegerLog10
  int x_log2 = 31 - base::bits::CountLeadingZeros(x_scaled);
  int x_log10 = ((x_log2 + 1) * 1233) >> 12;
  x_log10 -= x_scaled < kPowersOf10[x_log10];
  int y_log2 = 31 - base::bits::CountLeadingZeros(y_scaled);
  int y_log10 = ((y_log2 + 1) * 1233) >> 12;
  y_log10 -= y_scaled < kPowersOf10[y_log10];
  int tie = 0;
  if (x_log10 < y_log10) {
    // X has fewer digits. We would like to simply scale up X but that
    // might overflow, e.g when comparing 9 with 1_000_000_000, 9 would
    // be scaled up to 9_000_000_000. So we scale up by the next
    // smallest power and scale down Y to drop one digit. It is OK to
    // drop one digit from the longer integer since the final digit is
    // past the length of the shorter integer.
    x_scaled *= kPowersOf10[y_log10 - x_log10 - 1];
    y_scaled /= 10;
    tie = -1;
  } else if (y_log10 < x_log10) {
    y_scaled *= kPowersOf10[x_log10 - y_log10 - 1];
    x_scaled /= 10;
    tie = 1;
  }
  if (x_scaled < y_scaled) return Smi::FromInt(-1).ptr();
  if (x_scaled > y_scaled) return Smi::FromInt(1).ptr();
  return Smi::FromInt(tie).ptr();
}
References v8::base::bits::CountLeadingZeros(), FromInt(), v8::base::NegateWithWraparound(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), ToInt(), and v8::internal::y.
Referenced by v8::internal::LexicographicCompareWrapper().
SmiPrint()
void v8::internal::Smi::SmiPrint (Tagged< Smi > smi, std::ostream & os) [static]
Definition at line 1917 of file objects.cc.
{ os << smi.value(); }
References v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::operator<<().
ToInt()
static constexpr int v8::internal::Smi::ToInt (const Tagged< Object > object) [inline], [static], [constexpr]
Definition at line 33 of file smi.h.
                                                                 {
    return Tagged<Smi>(object.ptr()).value();
  }
References v8::internal::Tagged< Smi >.
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::PrototypeUsers::Add(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddArguments(), v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendPromiseCombinatorFrame(), v8::internal::Object::BooleanValue(), v8::internal::BUILTIN(), v8::internal::JSGeneratorObject::code_offset(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::BigInt::CompareToNumber(), v8::internal::LoadIC::ComputeHandler(), v8::internal::BuiltinExitFrame::ComputeParametersCount(), v8::internal::BuiltinFrame::ComputeParametersCount(), v8::internal::JavaScriptBuiltinContinuationFrame::ComputeParametersCount(), v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject(), v8::debug::Script::ContextId(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity(), v8::internal::Object::ConvertToLength(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElements(), v8::internal::anonymous_namespace{keys.cc}::CopyEnumKeysTo(), v8::internal::anonymous_namespace{elements.cc}::CopyPackedSmiToDoubleElements(), v8::internal::anonymous_namespace{elements.cc}::CopySmiToDoubleElements(), v8::internal::ScopeInfo::Create(), v8::internal::CreateElementDictionary(), v8::internal::OrderedHashTableIterator< Derived, TableType >::CurrentKey(), v8::internal::BigInt::EqualToNumber(), v8::internal::V8HeapExplorer::ExtractElementReferences(), v8::internal::V8HeapExplorer::ExtractNumberReference(), v8::internal::anonymous_namespace{builtins-array.cc}::Fast_ArrayConcat(), v8::internal::OrderedHashTable< Derived, entrysize >::FindEntry(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::FindName(), v8::internal::CodeStubAssembler::FixedArrayBoundsCheck(), v8::internal::NameDictionary::flags(), v8::internal::BigInt::FromNumber(), v8::internal::WasmObject::FromNumber(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FromObject(), v8::internal::Genesis::Genesis(), v8::internal::InterpretedFrame::GetBytecodeOffset(), v8::internal::FeedbackNexus::GetCallCount(), v8::internal::FeedbackNexus::GetCallFeedbackContent(), v8::CompileHintsCollector::GetCompileHints(), v8::internal::DebugStackTraceIterator::GetContextId(), v8::debug::GetContextId(), v8::internal::JSFunction::GetDerivedMap(), v8::internal::anonymous_namespace{literal-objects.cc}::GetExistingValueIndex(), v8::internal::JSObject::GetFastElementsUsage(), v8::internal::anonymous_namespace{isolate.cc}::GetGeneratorBytecodeOffset(), v8::internal::anonymous_namespace{js-objects.cc}::GetIdentityHashHelper(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetImpl(), v8::internal::FeedbackNexus::GetKeyType(), v8::internal::anonymous_namespace{objects.cc}::GetLineEnd(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetMaxIndex(), v8::internal::anonymous_namespace{runtime-classes.cc}::GetMethodWithSharedName(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::GetName(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), v8::internal::anonymous_namespace{liveedit.cc}::LineEndsWrapper::GetPosAfterNewLine(), v8::Script::GetProducedCompileHints(), v8::internal::Object::GetSimpleHash(), v8::debug::anonymous_namespace{debug-interface.cc}::GetSmiValue(), v8::internal::FeedbackNexus::GetSpeculationMode(), v8::internal::JavaScriptBuiltinContinuationFrame::GetSPToFPDelta(), v8::internal::ObjectHashSet::Has(), v8::internal::SharedFunctionInfo::HasBuiltinId(), v8::internal::JSObject::HasEnumerableElements(), v8::internal::OrderedNameDictionary::Hash(), v8::internal::ObjectHashTableShapeBase::Hash(), v8::internal::CompilationCacheShape::HashForObject(), v8::internal::ObjectHashTableShapeBase::HashForObject(), v8::internal::OrderedHashTable< Derived, entrysize >::HashToEntryRaw(), v8::internal::HoleyElementsUsage(), v8::internal::V8FileLogger::ICEvent(), v8::internal::NameToIndexHashTable::IndexAt(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::Value::Int32Value(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::IsMatch(), v8::Value::IsUint32(), v8::internal::RegExpUtils::IsUnmodifiedRegExp(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::IsValidSmi(), LexicographicCompare(), v8::internal::ObjectMultiHashTableBase< Derived, N >::Lookup(), v8::internal::anonymous_namespace{runtime-regexp.cc}::LookupNamedCapture(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::OrderedHashTableIterator< Derived, TableType >::MoveNext(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::NamedEnumerator(), v8::internal::OrderedHashTable< Derived, entrysize >::NextChainEntryRaw(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBuckets(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElements(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElements(), v8::internal::NumberToInt32(), v8::internal::NumberToInt64(), v8::internal::NumberToUint32(), v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator*(), v8::internal::PositiveNumberToUint32(), v8::internal::PositiveNumberToUint64(), v8::Object::PreviewEntries(), v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl(), v8::internal::SourceTextModuleInfo::RegularExportCellIndex(), v8::internal::JSFinalizationRegistry::RemoveCellFromUnregisterTokenMap(), v8::internal::OrderedHashTable< Derived, entrysize >::RemovedIndexAt(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement(), v8::internal::JSFinalizationRegistry::RemoveUnregisterToken(), v8::internal::MessageHandler::ReportMessageNoExceptions(), v8::internal::NumberDictionary::requires_slow_elements(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_I31GetS(), v8::internal::wasm::Handlers< Compressed >::s2s_I31GetU(), v8::internal::anonymous_namespace{runtime-debug.cc}::ScriptLinePosition(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::internal::anonymous_namespace{literal-objects.cc}::SetAccessorPlaceholderIndices(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SetImpl(), v8::internal::FeedbackNexus::SetSpeculationMode(), v8::internal::ShouldConvertToFastElements(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), v8::internal::Arguments< arguments_type >::smi_value_at(), v8::internal::StoreInArrayLiteralIC::Store(), v8::internal::StringBuilderConcatHelper(), v8::internal::StringBuilderConcatLength(), v8::Value::ToArrayIndex(), v8::internal::Object::ToInt32(), v8::internal::Object::ToIntegerIndex(), v8::internal::Object::ToLength(), v8::internal::Object::ToUint32(), v8::internal::Script::TraceScriptRundown(), v8::internal::Genesis::TransferNamedProperties(), v8::internal::anonymous_namespace{ic.cc}::TryConvertKey(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::TryCopyElementsFastNumber(), v8::internal::RegExpResultsCache_MatchGlobalAtom::TryGet(), v8::internal::CodeStubAssembler::TryGetIntPtrOrSmiConstantValue(), v8::internal::TryNumberToSize(), v8::Value::Uint32Value(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::ValidateContents(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ValidateImpl(), v8::Integer::Value(), v8::Int32::Value(), v8::Uint32::Value(), and v8::internal::anonymous_namespace{futex-emulation.cc}::WaitJsTranslateReturn().
ToUint32Smi()
static constexpr Tagged<Smi> v8::internal::Smi::ToUint32Smi (Tagged< Smi > smi) [inline], [static], [constexpr]
Definition at line 27 of file smi.h.
                                                                   {
    if (smi.value() <= 0) return Smi::FromInt(0);
    return Smi::FromInt(static_cast<uint32_t>(smi.value()));
  }
References FromInt(), and v8::internal::Tagged< Smi >::value().
uninitialized_deserialization_value()
static constexpr Tagged<Smi> v8::internal::Smi::uninitialized_deserialization_value () [inline], [static], [constexpr]
Definition at line 114 of file smi.h.
                                                                     {
    return Tagged<Smi>(kNullAddress);
  }
References v8::internal::kNullAddress, and v8::internal::Tagged< Smi >.
Referenced by v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays(), v8::internal::TransitionArray::GetTargetIfExists(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorsForMap().
zero()
static constexpr Tagged<Smi> v8::internal::Smi::zero () [inline], [static], [constexpr]
Definition at line 99 of file smi.h.
{ return Smi::FromInt(0); }
References FromInt().
Referenced by v8::internal::Isolate::AddDetachedContext(), v8::internal::KeyAccumulator::AddKey(), v8::internal::anonymous_namespace{runtime-wasm.cc}::AllocateFeedbackVector(), v8::internal::maglev::MaglevAssembler::AllocateTwoByteString(), v8::internal::wasm::InstanceBuilder::Build_Phase1_Infallible(), v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder(), v8::internal::BUILTIN(), v8::internal::MicrotaskQueue::CallEnqueueMicrotask(), v8::internal::PropertyCallbackArguments::CallIndexedDefiner(), v8::internal::PropertyCallbackArguments::CallIndexedDeleter(), v8::internal::PropertyCallbackArguments::CallIndexedDescriptor(), v8::internal::PropertyCallbackArguments::CallIndexedGetter(), v8::internal::PropertyCallbackArguments::CallIndexedQuery(), v8::internal::PropertyCallbackArguments::CallIndexedSetter(), v8::internal::PropertyCallbackArguments::CallPropertyEnumerator(), v8::internal::Isolate::CheckDetachedContextsAfterGC(), v8::internal::StubCache::Clear(), v8::internal::JsonStringifier::SimplePropertyKeyCache::Clear(), v8::internal::FeedbackNexus::Clear(), v8::internal::RegExpResultsCache_MatchGlobalAtom::Clear(), v8::internal::RegExpResultsCache::Clear(), v8::internal::Code::clear_source_position_table_and_bytecode_offset_table(), v8::internal::Debug::clear_suspended_generator(), v8::internal::ClearStaleLeftTrimmedPointerVisitor::ClearLeftTrimmedOrForward(), v8::internal::Debug::ClearMutedLocation(), v8::internal::TrustedObject::ClearProtectedPointerField(), v8::internal::Debug::ClearStepping(), v8::internal::HeapObject::ClearTrustedPointerField(), v8::internal::Factory::CloneScript(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::FeedbackNexus::ConfigureUninitialized(), v8::internal::Object::ConvertToLength(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::ScopeInfo::Create(), v8::internal::ScopeInfo::CreateForBootstrapping(), v8::internal::Heap::CreateInitialMutableObjects(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::Heap::InsertIntoRememberedSetFromCode::DebugGetCoverageInfo(), v8::internal::DEF_ACQUIRE_GETTER(), v8::internal::DEF_GETTER(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::RegExpResultsCache::Enter(), v8::internal::Heap::FinalizePartialMap(), v8::internal::IntlMathematicalValue::From(), v8::FromCData(), v8::internal::Generate_InterpreterEnterBytecode(), v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::SharedFunctionInfo::GetCode(), v8::internal::WasmDispatchTable::Grow(), v8::internal::WasmTrustedInstanceData::has_dispatch_table(), v8::internal::Script::has_line_ends(), v8::internal::Code::has_source_position_table_or_bytecode_offset_table(), v8::internal::Debug::has_suspended_generator(), v8::internal::TransitionArray::HasPrototypeTransitions(), v8::internal::TransitionArray::HasSideStepTransitions(), v8::internal::Heap::Heap(), v8::internal::FeedbackNexus::ic_state(), v8::internal::AllocationSite::Initialize(), v8::internal::InstructionStream::Initialize(), v8::internal::EmbedderDataSlot::Initialize(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Factory::InitializeMap(), v8::internal::JSMessageObject::InitializeSourcePositions(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::anonymous_namespace{js-objects.cc}::InvalidateOnePrototypeValidityCellInternal(), v8::internal::JSTypedArray::is_on_heap(), v8::internal::InstructionStream::IsFullyInitialized(), v8::internal::TrustedObject::IsProtectedPointerFieldEmpty(), v8::internal::PrototypeInfo::IsPrototypeInfoFast(), v8::internal::anonymous_namespace{runtime-literals.cc}::IsUninitializedLiteralSite(), v8::internal::Isolate::IsWasmJSPIEnabled(), v8::internal::IsZero(), v8::internal::anonymous_namespace{serializer-deserializer.cc}::IterateObjectCache(), v8::internal::ObjectDeserializer::LinkAllocationSites(), v8::internal::RegExpResultsCache::Lookup(), v8::internal::TracedHandles::MarkConservatively(), v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::FeedbackVector::New(), v8::internal::wasm::WasmExportWrapperCache::New(), v8::internal::RegExpMatchInfo::New(), v8::internal::TrustedWeakFixedArray::New(), v8::internal::ProtectedWeakFixedArray::New(), v8::internal::TrustedFixedArray::New(), v8::internal::ProtectedFixedArray::New(), v8::internal::Factory::NewCodeObjectForEmbeddedBuiltin(), v8::internal::Factory::NewJSArrayBufferView(), v8::internal::Factory::NewJSArrayStorage(), v8::internal::Factory::NewJSPromiseWithoutHook(), v8::internal::Factory::NewNativeContext(), v8::internal::Factory::NewPrototypeInfo(), v8::internal::Factory::NewTransitionArray(), v8::internal::Map::Normalize(), v8::internal::anonymous_namespace{builtins-riscv.cc}::OnStackReplacement(), v8::internal::Debug::PrepareStepIn(), v8::internal::PropertyCallbackArguments::PropertyCallbackArguments(), v8::internal::MacroAssembler::PushStackHandler(), v8::internal::JSFunction::raw_code(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), v8::internal::MathRandom::ResetContext(), v8::internal::IndirectPointerSlot::ResolveHandle(), v8::internal::MarkCompactWeakObjectRetainer::RetainAs(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), v8::internal::IrRegExpData::set_capture_name_map(), v8::ObjectTemplate::SetAccessCheckCallback(), v8::internal::Heap::SetConstructStubCreateDeoptPCOffset(), v8::internal::Heap::SetConstructStubInvokeDeoptPCOffset(), v8::internal::Heap::SetDeoptPCOffsetAfterAdaptShadowStack(), v8::internal::WasmDispatchTable::SetForNonWrapper(), v8::internal::WasmDispatchTable::SetForWrapper(), v8::internal::Heap::SetInterpreterEntryReturnPCOffset(), v8::internal::FreeSpace::SetNext(), v8::internal::JSTypedArray::SetOffHeapDataPtr(), v8::internal::Script::SetSource(), v8::internal::BytecodeArray::SetSourcePositionsFailedToCollect(), v8::internal::JSArrayBuffer::Setup(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SmiZeroConstant(), v8::internal::EmbedderDataSlot::store_aligned_pointer(), v8::internal::EmbedderDataSlot::store_smi(), v8::internal::EmbedderDataSlot::store_tagged(), v8::internal::Debug::ThreadInit(), v8::ToCData(), v8::internal::BigInt::ToNumber(), v8::internal::JSPromise::TriggerPromiseReactions(), v8::internal::InstructionStream::TryGetCode(), v8::internal::InstructionStream::TryGetCodeUnchecked(), v8::internal::maglev::MaglevAssembler::TryMigrateInstance(), v8::TypecheckWitness::Update(), v8::internal::JSObject::UpdatePrototypeUserRegistration(), v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer(), v8::internal::RootMarkingVisitor::VisitRunningCode(), v8::internal::RootsReferencesExtractor::VisitRunningCode(), v8::internal::ClientRootVisitor< Visitor >::VisitRunningCode(), v8::internal::PromiseBuiltinsAssembler::ZeroOutEmbedderOffsets(), and v8::internal::UnlinkWeakNextScope::~UnlinkWeakNextScope().
Member Data Documentation
kMaxValue
constexpr int v8::internal::Smi::kMaxValue = kSmiMaxValue [static], [constexpr]
Definition at line 101 of file smi.h.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddArguments(), v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::CircularStructureMessageBuilder::AppendSmi(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::BUILTIN(), v8::internal::CodeStubAssembler::ChangeUint32ToTagged(), v8::internal::CodeStubAssembler::ChangeUintPtrToTagged(), v8::internal::maglev::MaglevAssembler::CheckIntPtrIsSmi(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitiveOrDeopt(), v8::internal::OrderedHashTable< Derived, entrysize >::FindEntry(), v8::internal::TemplateInfo::GetHash(), v8::internal::JSBoundFunction::GetLength(), v8::internal::Heap::GetNextTemplateSerialNumber(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::Object::GetSimpleHash(), v8::internal::LookupIterator::GetStringPropertyValue(), v8::internal::Isolate::IncreaseDateCacheStampAndInvalidateProtector(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::IsSmiDouble(), IsValid(), v8::internal::CodeStubAssembler::IsValidPositiveSmi(), v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash(), v8::internal::SwissNameDictionary::MaxCapacity(), v8::internal::FactoryBase< Impl >::NewNumberFromSize(), v8::internal::Factory::NewSourceTextModule(), v8::internal::Factory::NewSyntheticModule(), v8::internal::Heap::NextScriptId(), v8::internal::Heap::NextStackTraceId(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Scanner::ScanNumber(), v8::internal::JsonStringifier::SerializeSmi(), v8::internal::FastJsonStringifier< Char >::SerializeSmi(), v8::internal::ShouldConvertToFastElements(), v8::internal::WasmStruct::Size(), v8::internal::Factory::SizeToString(), v8::internal::CodeStubAssembler::SmiFromUint32(), v8::internal::maglev::MaglevAssembler::SmiTagUint32AndJumpIfFail(), v8::internal::FactoryBase< Impl >::SmiToString(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8ArrayImpl(), v8::Value::ToArrayIndex(), v8::internal::BigInt::ToNumber(), v8::internal::TryNumberToSize(), v8::internal::maglev::MaglevAssembler::UncheckedSmiTagUint32(), and v8::internal::DateParser::TimeZoneComposer::Write().
kMinValue
constexpr int v8::internal::Smi::kMinValue = kSmiMinValue [static], [constexpr]
Definition at line 100 of file smi.h.
Referenced by v8::internal::CircularStructureMessageBuilder::AppendSmi(), v8::internal::maglev::MaglevAssembler::CheckIntPtrIsSmi(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::IsSmiDouble(), v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::Negate(), v8::internal::JsonStringifier::SerializeSmi(), and v8::internal::FastJsonStringifier< Char >::SerializeSmi().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/smi.h
/mnt/V8SourceCode/src/objects/objects.cc