v8::internal::compiler::ZoneStats::StatsScope Class Reference
#include <zone-stats.h>
Public Member Functions
StatsScope (ZoneStats *zone_stats)
~StatsScope ()
StatsScope (const StatsScope &)=delete
StatsScope & operator= (const StatsScope &)=delete
size_t GetMaxAllocatedBytes ()
size_t GetCurrentAllocatedBytes ()
size_t GetTotalAllocatedBytes ()
Private Types
using InitialValues = std::map< Zone *, size_t >
Private Member Functions
void ZoneReturned (Zone *zone)
Private Attributes
ZoneStats *const zone_stats_
InitialValues initial_values_
size_t total_allocated_bytes_at_start_
size_t max_allocated_bytes_
Friends
class ZoneStats
Detailed Description
Definition at line 66 of file zone-stats.h.
Member Typedef Documentation
InitialValues
using v8::internal::compiler::ZoneStats::StatsScope::InitialValues = std::map<Zone*, size_t> [private]
Definition at line 81 of file zone-stats.h.
Constructor & Destructor Documentation
StatsScope() [1/2]
v8::internal::compiler::ZoneStats::StatsScope::StatsScope (ZoneStats * zone_stats) [explicit]
Definition at line 13 of file zone-stats.cc.
    : zone_stats_(zone_stats),
      total_allocated_bytes_at_start_(zone_stats->GetTotalAllocatedBytes()),
      max_allocated_bytes_(0) {
  zone_stats_->stats_.push_back(this);
  for (Zone* zone : zone_stats_->zones_) {
    size_t size = static_cast<size_t>(zone->allocation_size());
    std::pair<InitialValues::iterator, bool> res =
        initial_values_.insert(std::make_pair(zone, size));
    USE(res);
    DCHECK(res.second);
  }
}
References v8::internal::Zone::allocation_size(), v8::internal::DCHECK(), initial_values_, size(), v8::internal::compiler::ZoneStats::stats_, USE, zone_stats_, and v8::internal::compiler::ZoneStats::zones_.
 StatsScope()
v8::internal::compiler::ZoneStats::StatsScope::~StatsScope ()
Definition at line 27 of file zone-stats.cc.
                                 {
  DCHECK_EQ(zone_stats_->stats_.back(), this);
  zone_stats_->stats_.pop_back();
}
References DCHECK_EQ.
StatsScope() [2/2]
v8::internal::compiler::ZoneStats::StatsScope::StatsScope (const StatsScope &) [delete]
Member Function Documentation
GetCurrentAllocatedBytes()
size_t v8::internal::compiler::ZoneStats::StatsScope::GetCurrentAllocatedBytes ()
Definition at line 36 of file zone-stats.cc.
                                                     {
  size_t total = 0;
  for (Zone* zone : zone_stats_->zones_) {
    total += static_cast<size_t>(zone->allocation_size());
    // Adjust for initial values.
    InitialValues::iterator it = initial_values_.find(zone);
    if (it != initial_values_.end()) {
      total -= it->second;
    }
  }
  return total;
}
References v8::internal::Zone::allocation_size().
GetMaxAllocatedBytes()
size_t v8::internal::compiler::ZoneStats::StatsScope::GetMaxAllocatedBytes ()
Definition at line 32 of file zone-stats.cc.
                                                 {
  return std::max(max_allocated_bytes_, GetCurrentAllocatedBytes());
}
References v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes(), and v8::internal::compiler::ZoneStats::max_allocated_bytes_.
GetTotalAllocatedBytes()
size_t v8::internal::compiler::ZoneStats::StatsScope::GetTotalAllocatedBytes ()
Definition at line 49 of file zone-stats.cc.
                                                   {
  return zone_stats_->GetTotalAllocatedBytes() -
         total_allocated_bytes_at_start_;
}
operator=()
StatsScope& v8::internal::compiler::ZoneStats::StatsScope::operator= (const StatsScope &) [delete]
ZoneReturned()
void v8::internal::compiler::ZoneStats::StatsScope::ZoneReturned (Zone * zone) [private]
Definition at line 54 of file zone-stats.cc.
                                                 {
  size_t current_total = GetCurrentAllocatedBytes();
  // Update max.
  max_allocated_bytes_ = std::max(max_allocated_bytes_, current_total);
  // Drop zone from initial value map.
  InitialValues::iterator it = initial_values_.find(zone);
  if (it != initial_values_.end()) {
    initial_values_.erase(it);
  }
}
References v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes(), and v8::internal::compiler::ZoneStats::max_allocated_bytes_.
Friends And Related Function Documentation
ZoneStats
friend class ZoneStats [friend]
Definition at line 78 of file zone-stats.h.
Member Data Documentation
initial_values_
InitialValues v8::internal::compiler::ZoneStats::StatsScope::initial_values_ [private]
Definition at line 84 of file zone-stats.h.
Referenced by StatsScope().
max_allocated_bytes_
size_t v8::internal::compiler::ZoneStats::StatsScope::max_allocated_bytes_ [private]
Definition at line 86 of file zone-stats.h.
total_allocated_bytes_at_start_
size_t v8::internal::compiler::ZoneStats::StatsScope::total_allocated_bytes_at_start_ [private]
Definition at line 85 of file zone-stats.h.
zone_stats_
ZoneStats* const v8::internal::compiler::ZoneStats::StatsScope::zone_stats_ [private]
Definition at line 83 of file zone-stats.h.
Referenced by StatsScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/zone-stats.h
/mnt/V8SourceCode/src/compiler/zone-stats.cc