v8::internal::interpreter::BytecodeJumpTable Class Reference
#include <bytecode-jump-table.h>
Public Member Functions
BytecodeJumpTable (size_t constant_pool_index, int size, int case_value_base, Zone *zone)
size_t constant_pool_index () const
size_t switch_bytecode_offset () const
int case_value_base () const
int size () const
size_t ConstantPoolEntryFor (int case_value)
Private Member Functions
void mark_bound (int case_value)
void set_switch_bytecode_offset (size_t offset)
Private Attributes
size_t constant_pool_index_
size_t switch_bytecode_offset_
int size_
int case_value_base_
Static Private Attributes
static const size_t kInvalidIndex = static_cast<size_t>(-1)
static const size_t kInvalidOffset = static_cast<size_t>(-1)
Friends
class BytecodeArrayWriter
Detailed Description
Definition at line 20 of file bytecode-jump-table.h.
Constructor & Destructor Documentation
BytecodeJumpTable()
v8::internal::interpreter::BytecodeJumpTable::BytecodeJumpTable (size_t constant_pool_index, int size, int case_value_base, Zone * zone) [inline]
Definition at line 25 of file bytecode-jump-table.h.
      :
#ifdef DEBUG
        bound_(size, zone),
#endif
        constant_pool_index_(constant_pool_index),
        switch_bytecode_offset_(kInvalidOffset),
        size_(size),
        case_value_base_(case_value_base) {
  }
Member Function Documentation
case_value_base()
int v8::internal::interpreter::BytecodeJumpTable::case_value_base () const [inline]
Definition at line 39 of file bytecode-jump-table.h.
{ return case_value_base_; }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::OutputSwitchOnSmiNoFeedback(), and v8::internal::interpreter::BytecodeArrayBuilder::SwitchOnGeneratorState().
constant_pool_index()
size_t v8::internal::interpreter::BytecodeJumpTable::constant_pool_index () const [inline]
Definition at line 37 of file bytecode-jump-table.h.
{ return constant_pool_index_; }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::OutputSwitchOnSmiNoFeedback(), and v8::internal::interpreter::BytecodeArrayBuilder::SwitchOnGeneratorState().
ConstantPoolEntryFor()
size_t v8::internal::interpreter::BytecodeJumpTable::ConstantPoolEntryFor (int case_value) [inline]
Definition at line 49 of file bytecode-jump-table.h.
                                              {
    DCHECK_GE(case_value, case_value_base_);
    return constant_pool_index_ + case_value - case_value_base_;
  }
References DCHECK_GE.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindJumpTableEntry().
mark_bound()
void v8::internal::interpreter::BytecodeJumpTable::mark_bound (int case_value) [inline], [private]
Definition at line 58 of file bytecode-jump-table.h.
                                  {
#ifdef DEBUG
    DCHECK_GE(case_value, case_value_base_);
    DCHECK_LT(case_value, case_value_base_ + size());
    bound_.Add(case_value - case_value_base_);
#endif
  }
References DCHECK_GE, DCHECK_LT, and size().
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindJumpTableEntry().
set_switch_bytecode_offset()
void v8::internal::interpreter::BytecodeJumpTable::set_switch_bytecode_offset (size_t offset) [inline], [private]
Definition at line 66 of file bytecode-jump-table.h.
                                                 {
    DCHECK_EQ(switch_bytecode_offset_, kInvalidOffset);
    switch_bytecode_offset_ = offset;
  }
References DCHECK_EQ.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitSwitch().
size()
int v8::internal::interpreter::BytecodeJumpTable::size () const [inline]
Definition at line 40 of file bytecode-jump-table.h.
{ return size_; }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::OutputSwitchOnSmiNoFeedback(), and v8::internal::interpreter::BytecodeArrayBuilder::SwitchOnGeneratorState().
switch_bytecode_offset()
size_t v8::internal::interpreter::BytecodeJumpTable::switch_bytecode_offset () const [inline]
Definition at line 38 of file bytecode-jump-table.h.
{ return switch_bytecode_offset_; }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindJumpTableEntry().
Friends And Related Function Documentation
BytecodeArrayWriter
friend class BytecodeArrayWriter [friend]
Definition at line 81 of file bytecode-jump-table.h.
Member Data Documentation
case_value_base_
int v8::internal::interpreter::BytecodeJumpTable::case_value_base_ [private]
Definition at line 79 of file bytecode-jump-table.h.
constant_pool_index_
size_t v8::internal::interpreter::BytecodeJumpTable::constant_pool_index_ [private]
Definition at line 76 of file bytecode-jump-table.h.
kInvalidIndex
const size_t v8::internal::interpreter::BytecodeJumpTable::kInvalidIndex = static_cast<size_t>(-1) [static], [private]
Definition at line 55 of file bytecode-jump-table.h.
kInvalidOffset
const size_t v8::internal::interpreter::BytecodeJumpTable::kInvalidOffset = static_cast<size_t>(-1) [static], [private]
Definition at line 56 of file bytecode-jump-table.h.
size_
int v8::internal::interpreter::BytecodeJumpTable::size_ [private]
Definition at line 78 of file bytecode-jump-table.h.
switch_bytecode_offset_
size_t v8::internal::interpreter::BytecodeJumpTable::switch_bytecode_offset_ [private]
Definition at line 77 of file bytecode-jump-table.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-jump-table.h