v8::PropertyDescriptor Class Reference
An instance of a Property Descriptor, see Ecma-262 6.2.4.
#include <v8-object.h>
Classes
struct PrivateData
Public Member Functions
PropertyDescriptor ()
PropertyDescriptor (Local< Value > value)
PropertyDescriptor (Local< Value > value, bool writable)
PropertyDescriptor (Local< Value > get, Local< Value > set)
~PropertyDescriptor ()
Local< Value > value () const
bool has_value () const
Local< Value > get () const
bool has_get () const
Local< Value > set () const
bool has_set () const
void set_enumerable (bool enumerable)
bool enumerable () const
bool has_enumerable () const
void set_configurable (bool configurable)
bool configurable () const
bool has_configurable () const
bool writable () const
bool has_writable () const
PrivateData * get_private () const
PropertyDescriptor (const PropertyDescriptor &)=delete
void operator= (const PropertyDescriptor &)=delete
Private Attributes
PrivateData * private_
Detailed Description
An instance of a Property Descriptor, see Ecma-262 6.2.4.
Properties in a descriptor are present or absent. If you do not set enumerable, configurable, and writable, they are absent. If value, get, or set are absent, but you must specify them in the constructor, use empty handles.
Accessors get and set must be callable or undefined if they are present.
Note
Only query properties if they are present, i.e., call x() only if has_x() returns true.
// var desc = {writable: false}
v8::PropertyDescriptor d(Local<Value>()), false);
d.value(); // error, value not set
if (d.has_writable()) {
  d.writable(); // false
}
// var desc = {value: undefined}
v8::PropertyDescriptor d(v8::Undefined(isolate));
// var desc = {get: undefined}
v8::PropertyDescriptor d(v8::Undefined(isolate), Local<Value>()));
Definition at line 93 of file v8-object.h.
Constructor & Destructor Documentation
PropertyDescriptor() [1/5]
v8::PropertyDescriptor::PropertyDescriptor ()
Definition at line 4401 of file api.cc.
: private_(new PrivateData()) {}
PropertyDescriptor() [2/5]
v8::PropertyDescriptor::PropertyDescriptor (Local< Value > value) [explicit]
Definition at line 4404 of file api.cc.
    : private_(new PrivateData()) {
  private_->desc.set_value(
      Cast<i::JSAny>(Utils::OpenDirectHandle(*value, true)));
}
References v8::PropertyDescriptor::PrivateData::desc, v8::Utils::OpenDirectHandle(), private_, v8::internal::PropertyDescriptor::set_value(), and value().
PropertyDescriptor() [3/5]
v8::PropertyDescriptor::PropertyDescriptor (Local< Value > value, bool writable)
Definition at line 4411 of file api.cc.
    : private_(new PrivateData()) {
  private_->desc.set_value(
      Cast<i::JSAny>(Utils::OpenDirectHandle(*value, true)));
  private_->desc.set_writable(writable);
}
References v8::PropertyDescriptor::PrivateData::desc, v8::Utils::OpenDirectHandle(), private_, v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), value(), and writable().
PropertyDescriptor() [4/5]
v8::PropertyDescriptor::PropertyDescriptor (Local< Value > get, Local< Value > set)
Definition at line 4420 of file api.cc.
    : private_(new PrivateData()) {
  DCHECK(get.IsEmpty() || get->IsUndefined() || get->IsFunction());
  DCHECK(set.IsEmpty() || set->IsUndefined() || set->IsFunction());
  private_->desc.set_get(Cast<i::JSAny>(Utils::OpenDirectHandle(*get, true)));
  private_->desc.set_set(Cast<i::JSAny>(Utils::OpenDirectHandle(*set, true)));
}
References DCHECK, v8::PropertyDescriptor::PrivateData::desc, get(), v8::Utils::OpenDirectHandle(), private_, set(), v8::internal::PropertyDescriptor::set_get(), and v8::internal::PropertyDescriptor::set_set().
 PropertyDescriptor()
v8::PropertyDescriptor::~PropertyDescriptor ()
Definition at line 4429 of file api.cc.
{ delete private_; }
PropertyDescriptor() [5/5]
v8::PropertyDescriptor::PropertyDescriptor (const PropertyDescriptor &) [delete]
Member Function Documentation
configurable()
bool v8::PropertyDescriptor::configurable () const
Definition at line 4482 of file api.cc.
                                              {
  DCHECK(private_->desc.has_configurable());
  return private_->desc.configurable();
}
References DCHECK.
enumerable()
bool v8::PropertyDescriptor::enumerable () const
Definition at line 4469 of file api.cc.
                                            {
  DCHECK(private_->desc.has_enumerable());
  return private_->desc.enumerable();
}
References DCHECK.
get()
v8::Local< Value > v8::PropertyDescriptor::get () const
Definition at line 4436 of file api.cc.
                                               {
  DCHECK(private_->desc.has_get());
  return Utils::ToLocal(private_->desc.get());
}
References DCHECK.
Referenced by PropertyDescriptor().
get_private()
PrivateData* v8::PropertyDescriptor::get_private () const [inline]
Definition at line 129 of file v8-object.h.
{ return private_; }
Referenced by v8::Object::DefineProperty().
has_configurable()
bool v8::PropertyDescriptor::has_configurable () const
Definition at line 4487 of file api.cc.
                                                  {
  return private_->desc.has_configurable();
}
has_enumerable()
bool v8::PropertyDescriptor::has_enumerable () const
Definition at line 4474 of file api.cc.
                                                {
  return private_->desc.has_enumerable();
}
has_get()
bool v8::PropertyDescriptor::has_get () const
Definition at line 4449 of file api.cc.
                                         {
  return private_->desc.has_get();
}
has_set()
bool v8::PropertyDescriptor::has_set () const
Definition at line 4452 of file api.cc.
                                         {
  return private_->desc.has_set();
}
has_value()
bool v8::PropertyDescriptor::has_value () const
Definition at line 4446 of file api.cc.
                                           {
  return private_->desc.has_value();
}
has_writable()
bool v8::PropertyDescriptor::has_writable () const
Definition at line 4461 of file api.cc.
                                              {
  return private_->desc.has_writable();
}
operator=()
void v8::PropertyDescriptor::operator= (const PropertyDescriptor &) [delete]
set()
v8::Local< Value > v8::PropertyDescriptor::set () const
Definition at line 4441 of file api.cc.
                                               {
  DCHECK(private_->desc.has_set());
  return Utils::ToLocal(private_->desc.set());
}
References DCHECK.
Referenced by PropertyDescriptor().
set_configurable()
void v8::PropertyDescriptor::set_configurable (bool configurable)
Definition at line 4478 of file api.cc.
                                                             {
  private_->desc.set_configurable(configurable);
}
set_enumerable()
void v8::PropertyDescriptor::set_enumerable (bool enumerable)
Definition at line 4465 of file api.cc.
                                                         {
  private_->desc.set_enumerable(enumerable);
}
value()
v8::Local< Value > v8::PropertyDescriptor::value () const
Definition at line 4431 of file api.cc.
                                                 {
  DCHECK(private_->desc.has_value());
  return Utils::ToLocal(private_->desc.value());
}
References DCHECK.
Referenced by PropertyDescriptor().
writable()
bool v8::PropertyDescriptor::writable () const
Definition at line 4456 of file api.cc.
                                          {
  DCHECK(private_->desc.has_writable());
  return private_->desc.writable();
}
References DCHECK.
Referenced by PropertyDescriptor().
Member Data Documentation
private_
PrivateData* v8::PropertyDescriptor::private_ [private]
Definition at line 135 of file v8-object.h.
Referenced by PropertyDescriptor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-object.h
/mnt/V8SourceCode/src/api/api.cc