v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange Class Reference
Public Member Functions
DataRange (base::Vector< const uint8_t > data, int64_t seed=-1)
DataRange (const DataRange &)=delete
DataRange & operator= (const DataRange &)=delete
DataRange clone () const
DataRange (DataRange &&other) V8_NOEXCEPT
DataRange & operator= (DataRange &&other) V8_NOEXCEPT
size_t size () const
DataRange split ()
template<typename T , size_t max_bytes = sizeof(T)>
T getPseudoRandom ()
template<typename T >
T get ()
template<> bool get ()
Private Attributes
base::Vector< const uint8_t > data_
base::RandomNumberGenerator rng_
Detailed Description
Definition at line 104 of file random-module-generation.cc.
Constructor & Destructor Documentation
DataRange() [1/3]
v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::DataRange (base::Vector< const uint8_t > data, int64_t seed = -1) [inline], [explicit]
Definition at line 112 of file random-module-generation.cc.
      : data_(data), rng_(seed == -1 ? get<int64_t>() : seed) {}
DataRange() [2/3]
v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::DataRange (const DataRange &) [delete]
DataRange() [3/3]
v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::DataRange (DataRange && other) [inline]
Definition at line 124 of file random-module-generation.cc.
                                           : data_(other.data_),
                                             rng_(other.rng_) {
    other.data_ = {};
  }
Member Function Documentation
clone()
DataRange v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::clone () const [inline]
Definition at line 118 of file random-module-generation.cc.
{ return DataRange(data_, rng_.initial_seed()); }
References v8::base::RandomNumberGenerator::initial_seed().
get() [1/2]
template<typename T >
T v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get () [inline]
Definition at line 178 of file random-module-generation.cc.
          {
    // Bool needs special handling (see template specialization below).
    static_assert(!std::is_same_v<T, bool>, "bool needs special handling");
    // We want to support the case where we have less than sizeof(T) bytes
    // remaining in the slice. We'll just use what we have, so we get a bit of
    // randomness when there are still some bytes left. If size == 0, get<T>()
    // returns the type's value-initialized value.
    const size_t num_bytes = std::min(sizeof(T), data_.size());
    T result{};
    memcpy(&result, data_.begin(), num_bytes);
    data_ += num_bytes;
    return result;
  }
References v8::base::Vector< T >::begin(), v8::base::internal::result, and v8::base::Vector< T >::size().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::any_block(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_fill(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BodyGen(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_if(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_cast(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_non_null(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_null(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_table(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::choose_function_table_index(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::choose_sub_type(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ConsumeAndGenerate(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateOneOf(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateTypes(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::get_local_ref(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GetRandomGlobal(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GetRandomLocal(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::grow_memory(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::i31_get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::memop(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::memory_size(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_test(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::select_random_table(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::shift_locals_to(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::simd_lane_memop(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::simd_lane_op(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::simd_shuffle(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::throw_or_rethrow(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_block_helper(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_block_helper().
get() [2/2]
template<>
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get ()
Definition at line 196 of file random-module-generation.cc.
                    {
  // The general implementation above is not instantiable for bool, as that
  // would cause undefinied behaviour when memcpy'ing random bytes to the
  // bool. This can result in different observable side effects when invoking
  // get<bool> between debug and release version, which eventually makes the
  // code output different as well as raising various unrecoverable errors on
  // runtime.
  // Hence we specialize get<bool> to consume a full byte and use the least
  // significant bit only (0 == false, 1 == true).
  return get<uint8_t>() % 2;
}
getPseudoRandom()
template<typename T , size_t max_bytes = sizeof(T)>
T v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom () [inline]
Definition at line 150 of file random-module-generation.cc.
                      {
    static_assert(!std::is_same_v<T, bool>, "bool needs special handling");
    static_assert(max_bytes <= sizeof(T));
    // Special handling for signed integers: Calling getPseudoRandom<int32_t, 1>
    // () should be equal to getPseudoRandom<int8_t>(). (The NextBytes() below
    // does not achieve that due to depending on endianness and either never
    // generating negative values or filling in the highest significant bits
    // which would be unexpected).
    if constexpr (std::is_integral_v<T> && std::is_signed_v<T>) {
      switch (max_bytes) {
        case 1:
          return static_cast<int8_t>(getPseudoRandom<uint8_t>());
        case 2:
          return static_cast<int16_t>(getPseudoRandom<uint16_t>());
        case 4:
          return static_cast<int32_t>(getPseudoRandom<uint32_t>());
        default:
          return static_cast<T>(
              getPseudoRandom<std::make_unsigned_t<T>, max_bytes>());
      }
    }
    T result{};
    rng_.NextBytes(&result, max_bytes);
    return result;
  }
References v8::base::RandomNumberGenerator::NextBytes(), and v8::base::internal::result.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateF32(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateF64(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI32(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI64(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::i32_const(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::i64_const(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::memop(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::simd_const().
operator=() [1/2]
DataRange& v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::operator= (const DataRange &) [delete]
operator=() [2/2]
DataRange& v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::operator= (DataRange && other) [inline]
Definition at line 128 of file random-module-generation.cc.
                                                      {
    data_ = other.data_;
    rng_ = other.rng_;
    other.data_ = {};
    return *this;
  }
size()
size_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size () const [inline]
Definition at line 135 of file random-module-generation.cc.
{ return data_.size(); }
References v8::base::Vector< T >::size().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateF32(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateF64(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI32(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI64(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateS128(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateVoid(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object().
split()
DataRange v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::split () [inline]
Definition at line 137 of file random-module-generation.cc.
                    {
    // As we might split many times, only use 2 bytes if the data size is large.
    uint16_t random_choice = data_.size() > std::numeric_limits<uint8_t>::max()
                                 ? get<uint16_t>()
                                 : get<uint8_t>();
    uint16_t num_bytes = random_choice % std::max(size_t{1}, data_.size());
    int64_t new_seed = rng_.initial_seed() ^ rng_.NextInt64();
    DataRange split(data_.SubVector(0, num_bytes), new_seed);
    data_ += num_bytes;
    return split;
  }
References v8::base::RandomNumberGenerator::initial_seed(), v8::base::RandomNumberGenerator::NextInt64(), v8::base::Vector< T >::size(), v8::internal::libvtune::split(), and v8::base::Vector< T >::SubVector().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate().
Member Data Documentation
data_
base::Vector<const uint8_t> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::data_ [private]
Definition at line 106 of file random-module-generation.cc.
rng_
base::RandomNumberGenerator v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::rng_ [private]
Definition at line 109 of file random-module-generation.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/fuzzing/random-module-generation.cc