v8::internal::ExistingCodeLogger Class Reference
#include <log.h>
Public Types
using CodeTag = LogEventListener::CodeTag
Public Member Functions
ExistingCodeLogger (Isolate *isolate, LogEventListener *listener=nullptr)
void LogCodeObjects ()
void LogBuiltins ()
void LogCompiledFunctions (bool ensure_source_positions_available=true)
void LogExistingFunction (DirectHandle< SharedFunctionInfo > shared, DirectHandle< AbstractCode > code, LogEventListener::CodeTag tag=LogEventListener::CodeTag::kFunction)
void LogCodeObject (Tagged< AbstractCode > object)
Private Attributes
Isolate * isolate_
LogEventListener * listener_
Detailed Description
Definition at line 89 of file log.h.
Member Typedef Documentation
CodeTag
using v8::internal::ExistingCodeLogger::CodeTag = LogEventListener::CodeTag
Definition at line 91 of file log.h.
Constructor & Destructor Documentation
ExistingCodeLogger()
v8::internal::ExistingCodeLogger::ExistingCodeLogger (Isolate * isolate, LogEventListener * listener = nullptr) [inline], [explicit]
Definition at line 92 of file log.h.
      : isolate_(isolate), listener_(listener) {}
Member Function Documentation
LogBuiltins()
void v8::internal::ExistingCodeLogger::LogBuiltins ()
Definition at line 2583 of file log.cc.
                                     {
  DCHECK(isolate_->builtins()->is_initialized());
  // The main "copy" of used builtins are logged by LogCodeObjects() while
  // iterating Code objects.
  // TODO(v8:11880): Log other copies of remapped builtins once we
  // decide to remap them multiple times into the code range (for example
  // for arm64).
}
References v8::internal::Isolate::builtins(), v8::internal::DCHECK(), v8::internal::Builtins::is_initialized(), and isolate_.
Referenced by v8::internal::V8FileLogger::LogBuiltins(), v8::internal::ExternalLogEventListener::LogExistingCode(), and v8::internal::PerfettoLogger::LogExistingCode().
LogCodeObject()
void v8::internal::ExistingCodeLogger::LogCodeObject (Tagged< AbstractCode > object)
Definition at line 2508 of file log.cc.
                                                                  {
  HandleScope scope(isolate_);
  DirectHandle<AbstractCode> abstract_code(object, isolate_);
  CodeTag tag = CodeTag::kStub;
  const char* description = "Unknown code from before profiling";
  PtrComprCageBase cage_base(isolate_);
  switch (abstract_code->kind(cage_base)) {
    case CodeKind::INTERPRETED_FUNCTION:
    case CodeKind::TURBOFAN_JS:
    case CodeKind::BASELINE:
    case CodeKind::MAGLEV:
      return; // We log this later using LogCompiledFunctions.
    case CodeKind::FOR_TESTING:
      description = "STUB code";
      tag = CodeTag::kStub;
      break;
    case CodeKind::REGEXP:
      description = "Regular expression code";
      tag = CodeTag::kRegExp;
      break;
    case CodeKind::BYTECODE_HANDLER:
      description =
          isolate_->builtins()->name(abstract_code->builtin_id(cage_base));
      tag = CodeTag::kBytecodeHandler;
      break;
    case CodeKind::BUILTIN:
      if (abstract_code->has_instruction_stream(cage_base)) {
        DCHECK_EQ(abstract_code->builtin_id(cage_base),
                  Builtin::kInterpreterEntryTrampoline);
        // We treat interpreter trampoline builtin copies as
        // INTERPRETED_FUNCTION, which are logged using LogCompiledFunctions.
        return;
      }
      description = Builtins::name(abstract_code->builtin_id(cage_base));
      tag = CodeTag::kBuiltin;
      break;
    case CodeKind::WASM_FUNCTION:
      description = "A Wasm function";
      tag = CodeTag::kFunction;
      break;
    case CodeKind::JS_TO_WASM_FUNCTION:
      description = "A JavaScript to Wasm adapter";
      tag = CodeTag::kStub;
      break;
    case CodeKind::WASM_TO_CAPI_FUNCTION:
      description = "A Wasm to C-API adapter";
      tag = CodeTag::kStub;
      break;
    case CodeKind::WASM_TO_JS_FUNCTION:
      description = "A Wasm to JavaScript adapter";
      tag = CodeTag::kStub;
      break;
    case CodeKind::C_WASM_ENTRY:
      description = "A C to Wasm entry stub";
      tag = CodeTag::kStub;
      break;
  }
  CALL_CODE_EVENT_HANDLER(CodeCreateEvent(tag, abstract_code, description))
}
References BUILTIN, v8::internal::Isolate::builtins(), CALL_CODE_EVENT_HANDLER, DCHECK_EQ, isolate_, v8::internal::torque::ls::kFunction, and v8::internal::Builtins::name().
Referenced by LogCodeObjects().
LogCodeObjects()
void v8::internal::ExistingCodeLogger::LogCodeObjects ()
Definition at line 2568 of file log.cc.
                                        {
  Heap* heap = isolate_->heap();
  CombinedHeapObjectIterator iterator(heap);
  DisallowGarbageCollection no_gc;
  PtrComprCageBase cage_base(isolate_);
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    InstanceType instance_type = obj->map(cage_base)->instance_type();
    if (InstanceTypeChecker::IsCode(instance_type) ||
        InstanceTypeChecker::IsBytecodeArray(instance_type)) {
      LogCodeObject(Cast<AbstractCode>(obj));
    }
  }
}
References v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, LogCodeObject(), v8::internal::CombinedHeapObjectIterator::Next(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::V8FileLogger::LogCodeObjects(), v8::internal::ExternalLogEventListener::LogExistingCode(), and v8::internal::PerfettoLogger::LogExistingCode().
LogCompiledFunctions()
void v8::internal::ExistingCodeLogger::LogCompiledFunctions (bool ensure_source_positions_available = true)
Definition at line 2592 of file log.cc.
                                            {
  Heap* heap = isolate_->heap();
  HandleScope scope(isolate_);
  std::vector<std::pair<Handle<SharedFunctionInfo>, Handle<AbstractCode>>>
      compiled_funcs = EnumerateCompiledFunctions(heap);
  // During iteration, there can be heap allocation due to
  // GetScriptLineNumber call.
  for (auto& pair : compiled_funcs) {
    DirectHandle<SharedFunctionInfo> shared = pair.first;
    // If the script is a Smi, then the SharedFunctionInfo is in
    // the process of being deserialized.
    Tagged<Object> script = shared->raw_script(kAcquireLoad);
    if (IsSmi(script)) {
      DCHECK_EQ(script, Smi::uninitialized_deserialization_value());
      continue;
    }
    if (ensure_source_positions_available) {
      SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate_, shared);
    }
    if (shared->HasInterpreterData(isolate_)) {
      LogExistingFunction(
          shared, direct_handle(Cast<AbstractCode>(
                                    shared->InterpreterTrampoline(isolate_)),
                                isolate_));
    }
    if (shared->HasBaselineCode()) {
      LogExistingFunction(
          shared,
          direct_handle(Cast<AbstractCode>(shared->baseline_code(kAcquireLoad)),
                        isolate_));
    }
    // TODO(saelo): remove the "!IsTrustedSpaceObject" once builtin Code
    // objects are also in trusted space. Currently this breaks because we must
    // not compare objects in trusted space with ones inside the sandbox.
    static_assert(!kAllCodeObjectsLiveInTrustedSpace);
    if (!HeapLayout::InTrustedSpace(*pair.second) &&
        pair.second.is_identical_to(BUILTIN_CODE(isolate_, CompileLazy))) {
      continue;
    }
    LogExistingFunction(pair.first, pair.second);
  }
#if V8_ENABLE_WEBASSEMBLY
  HeapObjectIterator iterator(heap);
  DisallowGarbageCollection no_gc;
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    if (!IsWasmModuleObject(obj)) continue;
    auto module_object = Cast<WasmModuleObject>(obj);
    module_object->native_module()->LogWasmCodes(isolate_,
                                                 module_object->script());
  }
  wasm::GetWasmImportWrapperCache()->LogForIsolate(isolate_);
#endif // V8_ENABLE_WEBASSEMBLY
}
References BUILTIN_CODE, v8::internal::wasm::CompileLazy(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::EnumerateCompiledFunctions(), v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::Isolate::heap(), v8::internal::HeapLayout::InTrustedSpace(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, v8::internal::IsSmi(), v8::kAcquireLoad, v8::internal::kAllCodeObjectsLiveInTrustedSpace, LogExistingFunction(), v8::internal::wasm::WasmImportWrapperCache::LogForIsolate(), v8::internal::HeapObjectIterator::Next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::script, and v8::internal::Smi::uninitialized_deserialization_value().
Referenced by v8::internal::V8FileLogger::LogCompiledFunctions(), v8::internal::ExternalLogEventListener::LogExistingCode(), and v8::internal::PerfettoLogger::LogExistingCode().
LogExistingFunction()
void v8::internal::ExistingCodeLogger::LogExistingFunction (DirectHandle< SharedFunctionInfo > shared, DirectHandle< AbstractCode > code, LogEventListener::CodeTag tag = LogEventListener::CodeTag::kFunction)
Definition at line 2653 of file log.cc.
                 {
  if (IsScript(shared->script())) {
    DirectHandle<Script> script(Cast<Script>(shared->script()), isolate_);
    Script::PositionInfo info;
    Script::GetPositionInfo(script, shared->StartPosition(), &info);
    int line_num = info.line + 1;
    int column_num = info.column + 1;
    if (IsString(script->name())) {
      DirectHandle<String> script_name(Cast<String>(script->name()), isolate_);
      if (!shared->is_toplevel()) {
        CALL_CODE_EVENT_HANDLER(
            CodeCreateEvent(V8FileLogger::ToNativeByScript(tag, *script), code,
                            shared, script_name, line_num, column_num))
      } else {
        // Can't distinguish eval and script here, so always use Script.
        CALL_CODE_EVENT_HANDLER(CodeCreateEvent(
            V8FileLogger::ToNativeByScript(CodeTag::kScript, *script), code,
            shared, script_name))
      }
    } else {
      CALL_CODE_EVENT_HANDLER(CodeCreateEvent(
          V8FileLogger::ToNativeByScript(tag, *script), code, shared,
          isolate_->factory()->empty_string(), line_num, column_num))
    }
  } else if (shared->IsApiFunction()) {
    // API function.
    DirectHandle<FunctionTemplateInfo> fun_data(shared->api_func_data(),
                                                isolate_);
    if (fun_data->has_callback(isolate_)) {
      Address entry_point = fun_data->callback(isolate_);
#if USES_FUNCTION_DESCRIPTORS
      entry_point = *FUNCTION_ENTRYPOINT_ADDRESS(entry_point);
#endif
      DirectHandle<String> fun_name =
          SharedFunctionInfo::DebugName(isolate_, shared);
      CALL_CODE_EVENT_HANDLER(CallbackEvent(fun_name, entry_point))
      // Fast API function.
      int c_functions_count = fun_data->GetCFunctionsCount();
      for (int i = 0; i < c_functions_count; i++) {
        CALL_CODE_EVENT_HANDLER(
            CallbackEvent(fun_name, fun_data->GetCFunction(isolate_, i)))
      }
    }
#if V8_ENABLE_WEBASSEMBLY
  } else if (shared->HasWasmJSFunctionData(isolate_)) {
    CALL_CODE_EVENT_HANDLER(
        CodeCreateEvent(CodeTag::kFunction, code, "wasm-to-js"));
#endif // V8_ENABLE_WEBASSEMBLY
  }
}
References CALL_CODE_EVENT_HANDLER, code, v8::internal::Script::PositionInfo::column, v8::internal::SharedFunctionInfo::DebugName(), v8::internal::Isolate::factory(), v8::internal::Script::GetPositionInfo(), isolate_, v8::internal::torque::ls::kFunction, v8::internal::Script::PositionInfo::line, v8::internal::script, and v8::internal::V8FileLogger::ToNativeByScript().
Referenced by LogCompiledFunctions(), and v8::internal::V8FileLogger::LogExistingFunction().
Member Data Documentation
isolate_
Isolate* v8::internal::ExistingCodeLogger::isolate_ [private]
Definition at line 110 of file log.h.
Referenced by LogBuiltins(), LogCodeObject(), LogCodeObjects(), LogCompiledFunctions(), and LogExistingFunction().
listener_
LogEventListener* v8::internal::ExistingCodeLogger::listener_ [private]
Definition at line 111 of file log.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/log.h
/mnt/V8SourceCode/src/logging/log.cc