v8::internal::SuperCallReference Class Reference
#include <ast.h>
Public Member Functions
VariableProxy * new_target_var () const
VariableProxy * this_function_var () const
Private Member Functions
SuperCallReference (VariableProxy *new_target_var, VariableProxy *this_function_var, int pos)
Private Attributes
friend Zone
VariableProxy * new_target_var_
VariableProxy * this_function_var_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 2812 of file ast.h.
Constructor & Destructor Documentation
SuperCallReference()
v8::internal::SuperCallReference::SuperCallReference (VariableProxy * new_target_var, VariableProxy * this_function_var, int pos) [inline], [private]
Definition at line 2822 of file ast.h.
      : Expression(pos, kSuperCallReference),
        new_target_var_(new_target_var),
        this_function_var_(this_function_var) {
    DCHECK(new_target_var->raw_name()->IsOneByteEqualTo(".new.target"));
    DCHECK(this_function_var->raw_name()->IsOneByteEqualTo(".this_function"));
  }
References v8::internal::DCHECK(), v8::internal::AstRawString::IsOneByteEqualTo(), new_target_var(), v8::internal::VariableProxy::raw_name(), and this_function_var().
Member Function Documentation
new_target_var()
VariableProxy* v8::internal::SuperCallReference::new_target_var () const [inline]
Definition at line 2814 of file ast.h.
{ return new_target_var_; }
References new_target_var_.
Referenced by SuperCallReference(), and v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
this_function_var()
VariableProxy* v8::internal::SuperCallReference::this_function_var () const [inline]
Definition at line 2815 of file ast.h.
{ return this_function_var_; }
References this_function_var_.
Referenced by SuperCallReference(), and v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2818 of file ast.h.
Member Data Documentation
new_target_var_
VariableProxy* v8::internal::SuperCallReference::new_target_var_ [private]
Definition at line 2831 of file ast.h.
Referenced by new_target_var().
this_function_var_
VariableProxy* v8::internal::SuperCallReference::this_function_var_ [private]
Definition at line 2832 of file ast.h.
Referenced by this_function_var().
Zone
friend v8::internal::SuperCallReference::Zone [private]
Definition at line 2819 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h