v8::internal::maglev::MaglevCompilationInfo Class Reference
#include <maglev-compilation-info.h>
Public Member Functions
~MaglevCompilationInfo ()
Zone * zone ()
compiler::JSHeapBroker * broker () const
MaglevCompilationUnit * toplevel_compilation_unit () const
IndirectHandle< JSFunction > toplevel_function () const
BytecodeOffset toplevel_osr_offset () const
bool toplevel_is_osr () const
void set_code (IndirectHandle< Code > code)
MaybeIndirectHandle< Code > get_code ()
bool is_turbolev () const
bool has_graph_labeller () const
void set_graph_labeller (MaglevGraphLabeller *graph_labeller)
MaglevGraphLabeller * graph_labeller () const
bool collect_source_positions () const
bool specialize_to_function_context () const
void ReopenAndCanonicalizeHandlesInNewScope (Isolate *isolate)
void set_persistent_handles (std::unique_ptr< PersistentHandles > &&persistent_handles)
std::unique_ptr< PersistentHandles > DetachPersistentHandles ()
void set_canonical_handles (std::unique_ptr< CanonicalHandlesMap > &&canonical_handles)
std::unique_ptr< CanonicalHandlesMap > DetachCanonicalHandles ()
bool is_detached ()
bool could_not_inline_all_candidates ()
void set_could_not_inline_all_candidates ()
Static Public Member Functions
static std::unique_ptr< MaglevCompilationInfo > NewForTurboshaft (Isolate *isolate, compiler::JSHeapBroker *broker, IndirectHandle< JSFunction > function, BytecodeOffset osr_offset, bool specialize_to_function_context)
static std::unique_ptr< MaglevCompilationInfo > New (Isolate *isolate, IndirectHandle< JSFunction > function, BytecodeOffset osr_offset)
Private Member Functions
MaglevCompilationInfo (Isolate *isolate, IndirectHandle< JSFunction > function, BytecodeOffset osr_offset, std::optional< compiler::JSHeapBroker * > broker=std::nullopt, std::optional< bool > specialize_to_function_context=std::nullopt, bool for_turboshaft_frontend=false)
CanonicalHandlesMap * canonical_handles ()
Private Attributes
Zone zone_
compiler::JSHeapBroker * broker_
MaglevCompilationUnit * toplevel_compilation_unit_ = nullptr
IndirectHandle< JSFunction > toplevel_function_
IndirectHandle< Code > code_
BytecodeOffset osr_offset_
bool owns_broker_ = true
bool is_turbolev_ = false
bool could_not_inline_all_candidates_ = false
std::unique_ptr< MaglevGraphLabeller > graph_labeller_
bool collect_source_positions_
const bool specialize_to_function_context_
std::unique_ptr< PersistentHandles > ph_
std::unique_ptr< CanonicalHandlesMap > canonical_handles_
Detailed Description
Definition at line 48 of file maglev-compilation-info.h.
Constructor & Destructor Documentation
 MaglevCompilationInfo()
v8::internal::maglev::MaglevCompilationInfo::~MaglevCompilationInfo ()
Definition at line 120 of file maglev-compilation-info.cc.
                                              {
  if (owns_broker_) {
    delete broker_;
  }
}
References broker_, and owns_broker_.
MaglevCompilationInfo()
v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo (Isolate * isolate, IndirectHandle< JSFunction > function, BytecodeOffset osr_offset, std::optional< compiler::JSHeapBroker * > broker = std::nullopt, std::optional< bool > specialize_to_function_context = std::nullopt, bool for_turboshaft_frontend = false) [private]
Definition at line 67 of file maglev-compilation-info.cc.
    : zone_(isolate->allocator(), kMaglevZoneName),
      broker_(js_broker.has_value()
                  ? js_broker.value()
                  : new compiler::JSHeapBroker(isolate, zone(),
                                               v8_flags.trace_heap_broker,
                                               CodeKind::MAGLEV)),
      toplevel_function_(function),
      osr_offset_(osr_offset),
      owns_broker_(!js_broker.has_value()),
      is_turbolev_(for_turboshaft_frontend)
#define V(Name) , Name##_(v8_flags.Name)
          MAGLEV_COMPILATION_FLAG_LIST(V)
#undef V
      ,
      specialize_to_function_context_(SpecializeToFunctionContext(
          isolate, osr_offset, function, specialize_to_function_context)) {
  if (owns_broker_) {
    canonical_handles_ = std::make_unique<CanonicalHandlesMap>(
        isolate->heap(), ZoneAllocationPolicy(&zone_));
    compiler::CurrentHeapBrokerScope current_broker(broker_);
    MaglevCompilationHandleScope compilation(isolate, this);
    compiler::CompilationDependencies* deps =
        zone()->New<compiler::CompilationDependencies>(broker(), zone());
    USE(deps); // The deps register themselves in the heap broker.
    broker()->AttachCompilationInfo(this);
    // Heap broker initialization may already use IsPendingAllocation.
    isolate->heap()->PublishMainThreadPendingAllocations();
    broker()->InitializeAndStartSerializing(
        direct_handle(function->native_context(), isolate));
    broker()->StopSerializing();
    // Serialization may have allocated.
    isolate->heap()->PublishMainThreadPendingAllocations();
    toplevel_compilation_unit_ =
        MaglevCompilationUnit::New(zone(), this, function);
  } else {
    toplevel_compilation_unit_ =
        MaglevCompilationUnit::New(zone(), this, function);
  }
  collect_source_positions_ = isolate->NeedsDetailedOptimizedCodeLineInfo();
}
References v8::internal::compiler::JSHeapBroker::AttachCompilationInfo(), broker(), broker_, canonical_handles_, collect_source_positions_, v8::internal::direct_handle(), v8::internal::Isolate::heap(), v8::internal::compiler::JSHeapBroker::InitializeAndStartSerializing(), v8::internal::Isolate::NeedsDetailedOptimizedCodeLineInfo(), v8::internal::Zone::New(), v8::internal::maglev::MaglevCompilationUnit::New(), owns_broker_, v8::internal::Heap::PublishMainThreadPendingAllocations(), v8::internal::compiler::JSHeapBroker::StopSerializing(), toplevel_compilation_unit_, USE, zone(), and zone_.
Referenced by New(), and NewForTurboshaft().
Member Function Documentation
broker()
compiler::JSHeapBroker* v8::internal::maglev::MaglevCompilationInfo::broker () const [inline]
Definition at line 69 of file maglev-compilation-info.h.
{ return broker_; }
References broker_.
Referenced by v8::internal::maglev::MaglevCodeGenState::broker(), v8::internal::maglev::MaglevCompilationUnit::broker(), v8::internal::maglev::Graph::broker(), v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::maglev::MaglevCompiler::GenerateCode(), MaglevCompilationInfo(), and NewForTurboshaft().
canonical_handles()
CanonicalHandlesMap* v8::internal::maglev::MaglevCompilationInfo::canonical_handles () [inline], [private]
Definition at line 145 of file maglev-compilation-info.h.
{ return canonical_handles_.get(); }
References canonical_handles_.
Referenced by set_canonical_handles().
collect_source_positions()
bool v8::internal::maglev::MaglevCompilationInfo::collect_source_positions () const [inline]
Definition at line 104 of file maglev-compilation-info.h.
{ return collect_source_positions_; }
References collect_source_positions_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitDeopts().
could_not_inline_all_candidates()
bool v8::internal::maglev::MaglevCompilationInfo::could_not_inline_all_candidates () [inline]
Definition at line 125 of file maglev-compilation-info.h.
                                         {
    return could_not_inline_all_candidates_;
  }
References could_not_inline_all_candidates_.
DetachCanonicalHandles()
std::unique_ptr< CanonicalHandlesMap > v8::internal::maglev::MaglevCompilationInfo::DetachCanonicalHandles ()
Definition at line 183 of file maglev-compilation-info.cc.
                                              {
  DCHECK_NOT_NULL(canonical_handles_);
  return std::move(canonical_handles_);
}
References canonical_handles_, and DCHECK_NOT_NULL.
DetachPersistentHandles()
std::unique_ptr< PersistentHandles > v8::internal::maglev::MaglevCompilationInfo::DetachPersistentHandles ()
Definition at line 166 of file maglev-compilation-info.cc.
                                               {
  DCHECK_NOT_NULL(ph_);
  return std::move(ph_);
}
References DCHECK_NOT_NULL, and ph_.
Referenced by v8::internal::compiler::JSHeapBroker::AttachLocalIsolateForMaglev().
get_code()
MaybeIndirectHandle<Code> v8::internal::maglev::MaglevCompilationInfo::get_code () [inline]
Definition at line 82 of file maglev-compilation-info.h.
{ return code_; }
References code_.
graph_labeller()
MaglevGraphLabeller* v8::internal::maglev::MaglevCompilationInfo::graph_labeller () const [inline]
Definition at line 88 of file maglev-compilation-info.h.
                                              {
    DCHECK(has_graph_labeller());
    return graph_labeller_.get();
  }
References v8::internal::DCHECK(), graph_labeller_, and has_graph_labeller().
Referenced by v8::internal::maglev::MaglevCodeGenState::graph_labeller(), v8::internal::maglev::MaglevCompilationUnit::graph_labeller(), v8::internal::maglev::Graph::graph_labeller(), v8::internal::maglev::MaglevGraphVerifier::MaglevGraphVerifier(), and set_graph_labeller().
has_graph_labeller()
bool v8::internal::maglev::MaglevCompilationInfo::has_graph_labeller () const [inline]
Definition at line 86 of file maglev-compilation-info.h.
{ return !!graph_labeller_; }
References graph_labeller_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), graph_labeller(), v8::internal::maglev::MaglevCompilationUnit::has_graph_labeller(), v8::internal::maglev::Graph::has_graph_labeller(), and v8::internal::maglev::MaglevGraphVerifier::MaglevGraphVerifier().
is_detached()
bool v8::internal::maglev::MaglevCompilationInfo::is_detached ()
Definition at line 178 of file maglev-compilation-info.cc.
                                        {
  return toplevel_function_->context()->IsDetached(Isolate::Current());
}
References v8::internal::Isolate::Current(), and toplevel_function_.
Referenced by v8::internal::maglev::MaglevCompiler::GenerateCode().
is_turbolev()
bool v8::internal::maglev::MaglevCompilationInfo::is_turbolev () const [inline]
Definition at line 84 of file maglev-compilation-info.h.
{ return is_turbolev_; }
References is_turbolev_.
New()
static std::unique_ptr<MaglevCompilationInfo> v8::internal::maglev::MaglevCompilationInfo::New (Isolate * isolate, IndirectHandle< JSFunction > function, BytecodeOffset osr_offset) [inline], [static]
Definition at line 59 of file maglev-compilation-info.h.
                                 {
    // Doesn't use make_unique due to the private ctor.
    return std::unique_ptr<MaglevCompilationInfo>(
        new MaglevCompilationInfo(isolate, function, osr_offset));
  }
References MaglevCompilationInfo().
NewForTurboshaft()
static std::unique_ptr<MaglevCompilationInfo> v8::internal::maglev::MaglevCompilationInfo::NewForTurboshaft (Isolate * isolate, compiler::JSHeapBroker * broker, IndirectHandle< JSFunction > function, BytecodeOffset osr_offset, bool specialize_to_function_context) [inline], [static]
Definition at line 50 of file maglev-compilation-info.h.
                                           {
    // Doesn't use make_unique due to the private ctor.
    return std::unique_ptr<MaglevCompilationInfo>(new MaglevCompilationInfo(
        isolate, function, osr_offset, broker, specialize_to_function_context,
        /*for_turboshaft_frontend*/ true));
  }
References broker(), MaglevCompilationInfo(), and specialize_to_function_context().
ReopenAndCanonicalizeHandlesInNewScope()
void v8::internal::maglev::MaglevCompilationInfo::ReopenAndCanonicalizeHandlesInNewScope (Isolate * isolate)
Definition at line 152 of file maglev-compilation-info.cc.
                      {
  toplevel_function_ =
      CanonicalHandle(canonical_handles_.get(), *toplevel_function_, isolate);
}
References canonical_handles_, v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::CanonicalHandle(), and toplevel_function_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::MaglevCompilationHandleScope::MaglevCompilationHandleScope().
set_canonical_handles()
void v8::internal::maglev::MaglevCompilationInfo::set_canonical_handles (std::unique_ptr< CanonicalHandlesMap > && canonical_handles)
Definition at line 171 of file maglev-compilation-info.cc.
                                                            {
  DCHECK_NULL(canonical_handles_);
  canonical_handles_ = std::move(canonical_handles);
  DCHECK_NOT_NULL(canonical_handles_);
}
References canonical_handles(), canonical_handles_, DCHECK_NOT_NULL, and DCHECK_NULL.
set_code()
void v8::internal::maglev::MaglevCompilationInfo::set_code (IndirectHandle< Code > code) [inline]
Definition at line 78 of file maglev-compilation-info.h.
                                           {
    DCHECK(code_.is_null());
    code_ = code;
  }
References code, code_, and v8::internal::DCHECK().
set_could_not_inline_all_candidates()
void v8::internal::maglev::MaglevCompilationInfo::set_could_not_inline_all_candidates () [inline]
Definition at line 128 of file maglev-compilation-info.h.
                                             {
    could_not_inline_all_candidates_ = true;
  }
References could_not_inline_all_candidates_.
set_graph_labeller()
void v8::internal::maglev::MaglevCompilationInfo::set_graph_labeller (MaglevGraphLabeller * graph_labeller)
Definition at line 126 of file maglev-compilation-info.cc.
                                         {
  graph_labeller_.reset(graph_labeller);
}
References graph_labeller(), and graph_labeller_.
Referenced by v8::internal::maglev::MaglevCompiler::Compile().
set_persistent_handles()
void v8::internal::maglev::MaglevCompilationInfo::set_persistent_handles (std::unique_ptr< PersistentHandles > && persistent_handles)
Definition at line 158 of file maglev-compilation-info.cc.
                                                           {
  DCHECK_NULL(ph_);
  ph_ = std::move(persistent_handles);
  DCHECK_NOT_NULL(ph_);
}
References DCHECK_NOT_NULL, DCHECK_NULL, and ph_.
Referenced by v8::internal::compiler::JSHeapBroker::DetachLocalIsolateForMaglev().
specialize_to_function_context()
bool v8::internal::maglev::MaglevCompilationInfo::specialize_to_function_context () const [inline]
Definition at line 106 of file maglev-compilation-info.h.
                                              {
    return specialize_to_function_context_;
  }
References specialize_to_function_context_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadContextSlot(), v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), NewForTurboshaft(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlotToFunctionContext(), and v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::FunctionContextSpecialization::TryToRef().
toplevel_compilation_unit()
MaglevCompilationUnit* v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit () const [inline]
Definition at line 70 of file maglev-compilation-info.h.
                                                           {
    return toplevel_compilation_unit_;
  }
References toplevel_compilation_unit_.
Referenced by v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::maglev::MaglevCompiler::GenerateCode(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), v8::internal::maglev::Graph::is_osr(), v8::internal::maglev::LoopOptimizationProcessor::LoopOptimizationProcessor(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MaglevCodeGenState::parameter_count(), and v8::internal::maglev::MaglevCodeGenState::stack_check_offset().
toplevel_function()
IndirectHandle<JSFunction> v8::internal::maglev::MaglevCompilationInfo::toplevel_function () const [inline]
Definition at line 73 of file maglev-compilation-info.h.
                                                       {
    return toplevel_function_;
  }
References toplevel_function_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::maglev::MaglevCompiler::Compile(), and v8::internal::maglev::MaglevCompiler::GenerateCode().
toplevel_is_osr()
bool v8::internal::maglev::MaglevCompilationInfo::toplevel_is_osr () const [inline]
Definition at line 77 of file maglev-compilation-info.h.
{ return osr_offset_ != BytecodeOffset::None(); }
References v8::internal::BytecodeOffset::None(), and osr_offset_.
Referenced by v8::internal::maglev::MaglevCompilationUnit::is_osr(), v8::internal::maglev::MaglevCodeGenerator::MaglevCodeGenerator(), and v8::internal::maglev::MergePointInterpreterFrameState::MergeValue().
toplevel_osr_offset()
BytecodeOffset v8::internal::maglev::MaglevCompilationInfo::toplevel_osr_offset () const [inline]
Definition at line 76 of file maglev-compilation-info.h.
{ return osr_offset_; }
References osr_offset_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::BuildCodeObject(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), and v8::internal::maglev::MaglevCompilationUnit::osr_offset().
zone()
Zone* v8::internal::maglev::MaglevCompilationInfo::zone () [inline]
Definition at line 68 of file maglev-compilation-info.h.
{ return &zone_; }
References zone_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), MaglevCompilationInfo(), v8::internal::maglev::MaglevAssembler::MakeDeferredCode(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkCheckpointNodes(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::Graph::New(), v8::internal::maglev::MaglevCompilationUnit::zone(), and v8::internal::maglev::Graph::zone().
Member Data Documentation
broker_
compiler::JSHeapBroker* v8::internal::maglev::MaglevCompilationInfo::broker_ [private]
Definition at line 149 of file maglev-compilation-info.h.
Referenced by broker(), MaglevCompilationInfo(), and ~MaglevCompilationInfo().
canonical_handles_
std::unique_ptr<CanonicalHandlesMap> v8::internal::maglev::MaglevCompilationInfo::canonical_handles_ [private]
Definition at line 203 of file maglev-compilation-info.h.
Referenced by canonical_handles(), DetachCanonicalHandles(), MaglevCompilationInfo(), ReopenAndCanonicalizeHandlesInNewScope(), and set_canonical_handles().
code_
IndirectHandle<Code> v8::internal::maglev::MaglevCompilationInfo::code_ [private]
Definition at line 153 of file maglev-compilation-info.h.
Referenced by get_code(), and set_code().
collect_source_positions_
bool v8::internal::maglev::MaglevCompilationInfo::collect_source_positions_ [private]
Definition at line 178 of file maglev-compilation-info.h.
Referenced by collect_source_positions(), and MaglevCompilationInfo().
could_not_inline_all_candidates_
bool v8::internal::maglev::MaglevCompilationInfo::could_not_inline_all_candidates_ = false [private]
Definition at line 166 of file maglev-compilation-info.h.
Referenced by could_not_inline_all_candidates(), and set_could_not_inline_all_candidates().
graph_labeller_
std::unique_ptr<MaglevGraphLabeller> v8::internal::maglev::MaglevCompilationInfo::graph_labeller_ [private]
Definition at line 168 of file maglev-compilation-info.h.
Referenced by graph_labeller(), has_graph_labeller(), and set_graph_labeller().
is_turbolev_
bool v8::internal::maglev::MaglevCompilationInfo::is_turbolev_ = false [private]
Definition at line 163 of file maglev-compilation-info.h.
Referenced by is_turbolev().
osr_offset_
BytecodeOffset v8::internal::maglev::MaglevCompilationInfo::osr_offset_ [private]
Definition at line 154 of file maglev-compilation-info.h.
Referenced by toplevel_is_osr(), and toplevel_osr_offset().
owns_broker_
bool v8::internal::maglev::MaglevCompilationInfo::owns_broker_ = true [private]
Definition at line 159 of file maglev-compilation-info.h.
Referenced by MaglevCompilationInfo(), and ~MaglevCompilationInfo().
ph_
std::unique_ptr<PersistentHandles> v8::internal::maglev::MaglevCompilationInfo::ph_ [private]
Definition at line 198 of file maglev-compilation-info.h.
Referenced by DetachPersistentHandles(), and set_persistent_handles().
specialize_to_function_context_
const bool v8::internal::maglev::MaglevCompilationInfo::specialize_to_function_context_ [private]
Definition at line 184 of file maglev-compilation-info.h.
Referenced by specialize_to_function_context().
toplevel_compilation_unit_
MaglevCompilationUnit* v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit_ = nullptr [private]
Definition at line 151 of file maglev-compilation-info.h.
Referenced by MaglevCompilationInfo(), and toplevel_compilation_unit().
toplevel_function_
IndirectHandle<JSFunction> v8::internal::maglev::MaglevCompilationInfo::toplevel_function_ [private]
Definition at line 152 of file maglev-compilation-info.h.
Referenced by is_detached(), ReopenAndCanonicalizeHandlesInNewScope(), and toplevel_function().
zone_
Zone v8::internal::maglev::MaglevCompilationInfo::zone_ [private]
Definition at line 148 of file maglev-compilation-info.h.
Referenced by MaglevCompilationInfo(), and zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-compilation-info.h
/mnt/V8SourceCode/src/maglev/maglev-compilation-info.cc