v8::internal::BasicBlockProfiler Class Reference
#include <basic-block-profiler.h>
Public Types
using DataList = std::list< std::unique_ptr< BasicBlockProfilerData > >
Public Member Functions
BasicBlockProfiler ()=default
~BasicBlockProfiler ()=default
BasicBlockProfiler (const BasicBlockProfiler &)=delete
BasicBlockProfiler & operator= (const BasicBlockProfiler &)=delete
BasicBlockProfilerData * NewData (size_t n_blocks)
V8_EXPORT_PRIVATE void ResetCounts (Isolate *isolate)
V8_EXPORT_PRIVATE bool HasData (Isolate *isolate)
V8_EXPORT_PRIVATE void Print (Isolate *isolate, std::ostream &os)
V8_EXPORT_PRIVATE void Log (Isolate *isolate, std::ostream &os)
V8_EXPORT_PRIVATE std::vector< bool > GetCoverageBitmap (Isolate *isolate)
const DataList * data_list ()
Static Public Member Functions
static V8_EXPORT_PRIVATE BasicBlockProfiler * Get ()
Private Attributes
DataList data_list_
base::Mutex data_list_mutex_
Detailed Description
Definition at line 75 of file basic-block-profiler.h.
Member Typedef Documentation
DataList
using v8::internal::BasicBlockProfiler::DataList = std::list<std::unique_ptr<BasicBlockProfilerData> >
Definition at line 77 of file basic-block-profiler.h.
Constructor & Destructor Documentation
BasicBlockProfiler() [1/2]
v8::internal::BasicBlockProfiler::BasicBlockProfiler () [default]
 BasicBlockProfiler()
v8::internal::BasicBlockProfiler::~BasicBlockProfiler () [default]
BasicBlockProfiler() [2/2]
v8::internal::BasicBlockProfiler::BasicBlockProfiler (const BasicBlockProfiler &) [delete]
Member Function Documentation
data_list()
const DataList* v8::internal::BasicBlockProfiler::data_list () [inline]
Definition at line 96 of file basic-block-profiler.h.
{ return &data_list_; }
References data_list_.
Get()
static V8_EXPORT_PRIVATE BasicBlockProfiler* v8::internal::BasicBlockProfiler::Get () [static]
Referenced by v8::internal::Isolate::DumpAndResetBuiltinsProfileData(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::Shell::Main(), v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection(), and v8::internal::RUNTIME_FUNCTION().
GetCoverageBitmap()
std::vector< bool > v8::internal::BasicBlockProfiler::GetCoverageBitmap (Isolate * isolate)
Definition at line 206 of file basic-block-profiler.cc.
                                                                      {
  DisallowGarbageCollection no_gc;
  Tagged<ArrayList> list(isolate->heap()->basic_block_profiling_data());
  std::vector<bool> out;
  int list_length = list->length();
  for (int i = 0; i < list_length; ++i) {
    BasicBlockProfilerData data(
        Cast<OnHeapBasicBlockProfilerData>(list->get(i)));
    for (size_t j = 0; j < data.n_blocks(); ++j) {
      out.push_back(data.counts_[j] > 0);
    }
  }
  return out;
}
References v8::internal::BasicBlockProfilerData::counts_, v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::BasicBlockProfilerData::n_blocks(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::Shell::Main().
HasData()
bool v8::internal::BasicBlockProfiler::HasData (Isolate * isolate)
Definition at line 162 of file basic-block-profiler.cc.
                                                 {
  return !data_list_.empty() ||
         isolate->heap()->basic_block_profiling_data()->length() > 0;
}
References data_list_, and v8::internal::Isolate::heap().
Log()
void v8::internal::BasicBlockProfiler::Log (Isolate * isolate, std::ostream & os)
Definition at line 189 of file basic-block-profiler.cc.
                                                             {
  HandleScope scope(isolate);
  DirectHandle<ArrayList> list(isolate->heap()->basic_block_profiling_data(),
                               isolate);
  std::unordered_set<std::string> builtin_names;
  for (int i = 0; i < list->length(); ++i) {
    BasicBlockProfilerData data(
        direct_handle(Cast<OnHeapBasicBlockProfilerData>(list->get(i)),
                      isolate),
        isolate);
    data.Log(isolate, os);
    // Ensure that all builtin names are unique; otherwise profile-guided
    // optimization might get confused.
    CHECK(builtin_names.insert(data.function_name_).second);
  }
}
References CHECK, v8::internal::direct_handle(), v8::internal::BasicBlockProfilerData::function_name_, v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::BasicBlockProfilerData::Log().
Referenced by v8::internal::Isolate::DumpAndResetBuiltinsProfileData(), and v8::internal::RUNTIME_FUNCTION().
NewData()
BasicBlockProfilerData * v8::internal::BasicBlockProfiler::NewData (size_t n_blocks)
Definition at line 55 of file basic-block-profiler.cc.
                                                                   {
  base::MutexGuard lock(&data_list_mutex_);
  auto data = std::make_unique<BasicBlockProfilerData>(n_blocks);
  BasicBlockProfilerData* data_ptr = data.get();
  data_list_.push_back(std::move(data));
  return data_ptr;
}
References data_list_, and data_list_mutex_.
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), and v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection().
operator=()
BasicBlockProfiler& v8::internal::BasicBlockProfiler::operator= (const BasicBlockProfiler &) [delete]
Print()
void v8::internal::BasicBlockProfiler::Print (Isolate * isolate, std::ostream & os)
Definition at line 167 of file basic-block-profiler.cc.
                                                               {
  os << "---- Start Profiling Data ----" << '\n';
  for (const auto& data : data_list_) {
    os << *data;
  }
  HandleScope scope(isolate);
  DirectHandle<ArrayList> list(isolate->heap()->basic_block_profiling_data(),
                               isolate);
  std::unordered_set<std::string> builtin_names;
  for (int i = 0; i < list->length(); ++i) {
    BasicBlockProfilerData data(
        direct_handle(Cast<OnHeapBasicBlockProfilerData>(list->get(i)),
                      isolate),
        isolate);
    os << data;
    // Ensure that all builtin names are unique; otherwise profile-guided
    // optimization might get confused.
    CHECK(builtin_names.insert(data.function_name_).second);
  }
  os << "---- End Profiling Data ----" << '\n';
}
References CHECK, data_list_, v8::internal::direct_handle(), v8::internal::BasicBlockProfilerData::function_name_, v8::internal::Isolate::heap(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::Isolate::DumpAndResetBuiltinsProfileData().
ResetCounts()
void v8::internal::BasicBlockProfiler::ResetCounts (Isolate * isolate)
Definition at line 146 of file basic-block-profiler.cc.
                                                     {
  for (const auto& data : data_list_) {
    data->ResetCounts();
  }
  HandleScope scope(isolate);
  DirectHandle<ArrayList> list(isolate->heap()->basic_block_profiling_data(),
                               isolate);
  for (int i = 0; i < list->length(); ++i) {
    DirectHandle<FixedUInt32Array> counts(
        Cast<OnHeapBasicBlockProfilerData>(list->get(i))->counts(), isolate);
    for (int j = 0; j < counts->length() / kBlockCountSlotSize; ++j) {
      counts->set(j, 0);
    }
  }
}
References data_list_, v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::anonymous_namespace{basic-block-profiler.cc}::kBlockCountSlotSize.
Referenced by v8::internal::Isolate::DumpAndResetBuiltinsProfileData(), v8::Shell::Main(), and v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
data_list_
DataList v8::internal::BasicBlockProfiler::data_list_ [private]
Definition at line 99 of file basic-block-profiler.h.
Referenced by data_list(), HasData(), NewData(), Print(), and ResetCounts().
data_list_mutex_
base::Mutex v8::internal::BasicBlockProfiler::data_list_mutex_ [private]
Definition at line 100 of file basic-block-profiler.h.
Referenced by NewData().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/basic-block-profiler.h
/mnt/V8SourceCode/src/diagnostics/basic-block-profiler.cc