v8::internal::Heap::AllocationTrackerForDebugging Class Reference
Public Member Functions
AllocationTrackerForDebugging (Heap *heap)
~AllocationTrackerForDebugging () final
void AllocationEvent (Address addr, int size) final
void MoveEvent (Address source, Address target, int size) final
void UpdateObjectSizeEvent (Address, int) final
Static Public Member Functions
static bool IsNeeded ()
Private Member Functions
void UpdateAllocationsHash (Tagged< HeapObject > object)
void UpdateAllocationsHash (uint32_t value)
void PrintAllocationsHash ()
Private Attributes
Heap *const heap_
std::atomic< size_t > allocations_count_ {0}
RunningStringHasher raw_allocations_hash_ {0}
Detailed Description
Definition at line 821 of file heap.cc.
Constructor & Destructor Documentation
AllocationTrackerForDebugging()
v8::internal::Heap::AllocationTrackerForDebugging::AllocationTrackerForDebugging (Heap * heap) [inline], [explicit]
Definition at line 829 of file heap.cc.
                                                     : heap_(heap) {
    CHECK(IsNeeded());
    heap_->AddHeapObjectAllocationTracker(this);
  }
References v8::internal::Heap::AddHeapObjectAllocationTracker(), CHECK, heap_, and IsNeeded().
 AllocationTrackerForDebugging()
v8::internal::Heap::AllocationTrackerForDebugging::~AllocationTrackerForDebugging () [inline], [final]
Definition at line 834 of file heap.cc.
                                         {
    heap_->RemoveHeapObjectAllocationTracker(this);
    if (v8_flags.verify_predictable || v8_flags.fuzzer_gc_analysis) {
      PrintAllocationsHash();
    }
  }
References heap_, PrintAllocationsHash(), v8::internal::Heap::RemoveHeapObjectAllocationTracker(), and v8::internal::v8_flags.
Member Function Documentation
AllocationEvent()
void v8::internal::Heap::AllocationTrackerForDebugging::AllocationEvent (Address addr, int size) [inline], [final], [virtual]
Implements v8::internal::HeapObjectAllocationTracker.
Definition at line 841 of file heap.cc.
                                                     {
    if (v8_flags.verify_predictable) {
      allocations_count_.fetch_add(1, std::memory_order_relaxed);
      // Advance synthetic time by making a time request.
      heap_->MonotonicallyIncreasingTimeInMs();
      UpdateAllocationsHash(HeapObject::FromAddress(addr));
      UpdateAllocationsHash(size);
      if (allocations_count_ % v8_flags.dump_allocations_digest_at_alloc == 0) {
        PrintAllocationsHash();
      }
    } else if (v8_flags.fuzzer_gc_analysis) {
      allocations_count_.fetch_add(1, std::memory_order_relaxed);
    } else if (v8_flags.trace_allocation_stack_interval > 0) {
      allocations_count_.fetch_add(1, std::memory_order_relaxed);
      if (allocations_count_ % v8_flags.trace_allocation_stack_interval == 0) {
        heap_->isolate()->PrintStack(stdout, Isolate::kPrintStackConcise);
      }
    }
  }
References allocations_count_, v8::internal::HeapObject::FromAddress(), heap_, v8::internal::Heap::isolate(), v8::internal::Isolate::kPrintStackConcise, v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), PrintAllocationsHash(), v8::internal::Isolate::PrintStack(), size(), UpdateAllocationsHash(), and v8::internal::v8_flags.
IsNeeded()
static bool v8::internal::Heap::AllocationTrackerForDebugging::IsNeeded () [inline], [static]
Definition at line 824 of file heap.cc.
                         {
    return v8_flags.verify_predictable || v8_flags.fuzzer_gc_analysis ||
           (v8_flags.trace_allocation_stack_interval > 0);
  }
References v8::internal::v8_flags.
Referenced by AllocationTrackerForDebugging(), and v8::internal::Heap::SetUpSpaces().
MoveEvent()
void v8::internal::Heap::AllocationTrackerForDebugging::MoveEvent (Address source, Address target, int size) [inline], [final], [virtual]
Reimplemented from v8::internal::HeapObjectAllocationTracker.
Definition at line 863 of file heap.cc.
                                                                 {
    if (v8_flags.verify_predictable) {
      allocations_count_.fetch_add(1, std::memory_order_relaxed);
      // Advance synthetic time by making a time request.
      heap_->MonotonicallyIncreasingTimeInMs();
      UpdateAllocationsHash(HeapObject::FromAddress(source));
      UpdateAllocationsHash(HeapObject::FromAddress(target));
      UpdateAllocationsHash(size);
      if (allocations_count_ % v8_flags.dump_allocations_digest_at_alloc == 0) {
        PrintAllocationsHash();
      }
    } else if (v8_flags.fuzzer_gc_analysis) {
      allocations_count_.fetch_add(1, std::memory_order_relaxed);
    }
  }
References allocations_count_, v8::internal::HeapObject::FromAddress(), heap_, v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), PrintAllocationsHash(), size(), UpdateAllocationsHash(), and v8::internal::v8_flags.
PrintAllocationsHash()
void v8::internal::Heap::AllocationTrackerForDebugging::PrintAllocationsHash () [inline], [private]
Definition at line 905 of file heap.cc.
                              {
    uint32_t hash = raw_allocations_hash_.Finalize();
    PrintF("\n### Allocations = %zu, hash = 0x%08x\n",
           allocations_count_.load(std::memory_order_relaxed), hash);
  }
References allocations_count_, v8::internal::RunningStringHasher::Finalize(), v8::internal::PrintF(), and raw_allocations_hash_.
Referenced by AllocationEvent(), MoveEvent(), and ~AllocationTrackerForDebugging().
UpdateAllocationsHash() [1/2]
void v8::internal::Heap::AllocationTrackerForDebugging::UpdateAllocationsHash (Tagged< HeapObject > object) [inline], [private]
Definition at line 884 of file heap.cc.
                                                        {
    Address object_address = object.address();
    MemoryChunk* memory_chunk = MemoryChunk::FromAddress(object_address);
    AllocationSpace allocation_space =
        MutablePageMetadata::cast(memory_chunk->Metadata())->owner_identity();
    static_assert(kSpaceTagSize + kPageSizeBits <= 32);
    uint32_t value =
        static_cast<uint32_t>(memory_chunk->Offset(object_address)) |
        (static_cast<uint32_t>(allocation_space) << kPageSizeBits);
    UpdateAllocationsHash(value);
  }
References v8::internal::MutablePageMetadata::cast(), v8::internal::MemoryChunk::FromAddress(), kPageSizeBits, v8::internal::kSpaceTagSize, v8::internal::MemoryChunk::Metadata(), v8::internal::MemoryChunk::Offset(), v8::internal::MutablePageMetadata::owner_identity(), and v8::internal::value.
Referenced by AllocationEvent(), and MoveEvent().
UpdateAllocationsHash() [2/2]
void v8::internal::Heap::AllocationTrackerForDebugging::UpdateAllocationsHash (uint32_t value) [inline], [private]
Definition at line 898 of file heap.cc.
                                             {
    const uint16_t c1 = static_cast<uint16_t>(value);
    const uint16_t c2 = static_cast<uint16_t>(value >> 16);
    raw_allocations_hash_.AddCharacter(c1);
    raw_allocations_hash_.AddCharacter(c2);
  }
References v8::internal::RunningStringHasher::AddCharacter(), raw_allocations_hash_, and v8::internal::value.
UpdateObjectSizeEvent()
void v8::internal::Heap::AllocationTrackerForDebugging::UpdateObjectSizeEvent (Address , int) [inline], [final], [virtual]
Reimplemented from v8::internal::HeapObjectAllocationTracker.
Definition at line 881 of file heap.cc.
{}
Member Data Documentation
allocations_count_
std::atomic<size_t> v8::internal::Heap::AllocationTrackerForDebugging::allocations_count_ {0} [private]
Definition at line 915 of file heap.cc.
Referenced by AllocationEvent(), MoveEvent(), and PrintAllocationsHash().
heap_
Heap* const v8::internal::Heap::AllocationTrackerForDebugging::heap_ [private]
Definition at line 911 of file heap.cc.
Referenced by AllocationEvent(), AllocationTrackerForDebugging(), MoveEvent(), and ~AllocationTrackerForDebugging().
raw_allocations_hash_
RunningStringHasher v8::internal::Heap::AllocationTrackerForDebugging::raw_allocations_hash_ {0} [private]
Definition at line 917 of file heap.cc.
Referenced by PrintAllocationsHash(), and UpdateAllocationsHash().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/heap.cc