v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency Class Reference
Public Member Functions
FieldTypeDependency (MapRef map, MapRef owner, InternalIndex descriptor, ObjectRef type)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const MapRef map_
const MapRef owner_
const InternalIndex descriptor_
const ObjectRef type_
Additional Inherited Members
Detailed Description
Definition at line 776 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
FieldTypeDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::FieldTypeDependency (MapRef map, MapRef owner, InternalIndex descriptor, ObjectRef type) [inline]
Definition at line 778 of file compilation-dependencies.cc.
      : CompilationDependency(kFieldType),
        map_(map),
        owner_(owner),
        descriptor_(descriptor),
        type_(type) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 810 of file compilation-dependencies.cc.
                                                                {
    const FieldTypeDependency* const zat = that->AsFieldType();
    return map_.equals(zat->map_) && descriptor_ == zat->descriptor_ &&
           type_.equals(zat->type_);
  }
References descriptor_, map_, and type_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 805 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(map_), descriptor_.as_int(), h(type_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 794 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    Isolate* isolate = broker->isolate();
    Handle<Map> owner = owner_.object();
    CHECK(!owner->is_deprecated());
    CHECK_EQ(*type_.object(),
             owner->instance_descriptors(isolate)->GetFieldType(descriptor_));
    deps->Register(owner, DependentCode::kFieldTypeGroup);
  }
References broker(), CHECK, CHECK_EQ, v8::internal::DependentCode::kFieldTypeGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 786 of file compilation-dependencies.cc.
                                                    {
    DisallowGarbageCollection no_heap_allocation;
    if (map_.object()->is_deprecated()) return false;
    return *type_.object() == map_.object()
                                  ->instance_descriptors(broker->isolate())
                                  ->GetFieldType(descriptor_);
  }
References broker().
Member Data Documentation
descriptor_
const InternalIndex v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::descriptor_ [private]
Definition at line 818 of file compilation-dependencies.cc.
Referenced by Equals().
map_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::map_ [private]
Definition at line 816 of file compilation-dependencies.cc.
Referenced by Equals().
owner_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::owner_ [private]
Definition at line 817 of file compilation-dependencies.cc.
type_
const ObjectRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::type_ [private]
Definition at line 819 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc