v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor Class Reference
Public Member Functions
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) final
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
Private Member Functions
void UpdatePointer (FullObjectSlot p)
Additional Inherited Members
Detailed Description
Definition at line 312 of file scavenger.cc.
Member Function Documentation
UpdatePointer()
void v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer (FullObjectSlot p) [inline], [private]
Definition at line 326 of file scavenger.cc.
                                       {
    Tagged<Object> object = *p;
    DCHECK(!HasWeakHeapObjectTag(object));
    // The object may be in the old generation as global handles over
    // approximates the list of young nodes. This checks also bails out for
    // Smis.
    if (!HeapLayout::InYoungGeneration(object)) {
      return;
    }
    Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
    // TODO(chromium:1336158): Turn the following CHECKs into DCHECKs after
    // flushing out potential issues.
    CHECK(Heap::InFromPage(heap_object));
    MapWord first_word = heap_object->map_word(kRelaxedLoad);
    CHECK(first_word.IsForwardingAddress());
    Tagged<HeapObject> dest = first_word.ToForwardingAddress(heap_object);
    if (heap_object == dest) {
      DCHECK(Heap::IsLargeObject(heap_object) ||
             MemoryChunk::FromHeapObject(heap_object)->IsQuarantined());
      return;
    }
    UpdateHeapObjectReferenceSlot(FullHeapObjectSlot(p), dest);
    // The destination object should be in the "to" space. However, it could
    // also be a large string if the original object was a shortcut candidate.
    DCHECK_IMPLIES(HeapLayout::InYoungGeneration(dest),
                   Heap::InToPage(dest) ||
                       (Heap::IsLargeObject(dest) && Heap::InFromPage(dest) &&
                        dest->map_word(kRelaxedLoad).IsForwardingAddress()));
  }
References CHECK, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HasWeakHeapObjectTag(), v8::internal::Heap::InFromPage(), v8::internal::Heap::InToPage(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MapWord::IsForwardingAddress(), v8::internal::Heap::IsLargeObject(), v8::kRelaxedLoad, v8::internal::MapWord::ToForwardingAddress(), and v8::internal::UpdateHeapObjectReferenceSlot().
VisitRootPointer()
void v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 314 of file scavenger.cc.
                                                {
    UpdatePointer(p);
  }
VisitRootPointers()
void v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 318 of file scavenger.cc.
                                                                         {
    for (FullObjectSlot p = start; p < end; ++p) {
      UpdatePointer(p);
    }
  }
References v8::internal::compiler::end().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/scavenger.cc