v8::internal::MapsAndHandlers Class Reference
#include <feedback-vector.h>
Classes
class Iterator
Public Member Functions
MapsAndHandlers (Isolate *isolate)
bool empty () const
size_t size () const
void reserve (size_t capacity)
MapAndHandler operator[] (size_t i) const
void set_map (size_t i, DirectHandle< Map > map)
void set_handler (size_t i, MaybeObjectDirectHandle handler)
void emplace_back (DirectHandle< Map > map, MaybeObjectDirectHandle handler)
Iterator begin () const
Iterator end () const
base::Vector< DirectHandle< Map > > maps ()
Private Attributes
DirectHandleSmallVector< Map, DEFAULT_MAX_POLYMORPHIC_MAP_COUNT > maps_
DirectHandleSmallVector< Object, DEFAULT_MAX_POLYMORPHIC_MAP_COUNT > handlers_
base::SmallVector< HeapObjectReferenceType, DEFAULT_MAX_POLYMORPHIC_MAP_COUNT > handlers_reference_types_
Detailed Description
Definition at line 88 of file feedback-vector.h.
Constructor & Destructor Documentation
MapsAndHandlers()
v8::internal::MapsAndHandlers::MapsAndHandlers (Isolate * isolate) [inline], [explicit]
Definition at line 90 of file feedback-vector.h.
      : maps_(isolate), handlers_(isolate) {}
Member Function Documentation
begin()
Iterator v8::internal::MapsAndHandlers::begin () const [inline]
Definition at line 171 of file feedback-vector.h.
{ return Iterator(this, 0); }
emplace_back()
void v8::internal::MapsAndHandlers::emplace_back (DirectHandle< Map > map, MaybeObjectDirectHandle handler) [inline]
Definition at line 164 of file feedback-vector.h.
                                                                            {
    maps_.push_back(map);
    handlers_.push_back(handler.is_null() ? DirectHandle<Object>()
                                          : handler.object());
    handlers_reference_types_.push_back(handler.reference_type());
  }
References handlers_, handlers_reference_types_, v8::internal::MaybeObjectDirectHandle::is_null(), maps_, v8::internal::MaybeObjectDirectHandle::object(), v8::internal::DirectHandleSmallVector< T, kSize >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::internal::MaybeObjectDirectHandle::reference_type().
Referenced by v8::internal::anonymous_namespace{ic.cc}::AddOneReceiverMapIfMissing(), v8::internal::IC::ConfigureVectorState(), v8::internal::FeedbackNexus::ExtractMapsAndHandlers(), and v8::internal::IC::UpdatePolymorphicIC().
empty()
bool v8::internal::MapsAndHandlers::empty () const [inline]
Definition at line 93 of file feedback-vector.h.
{ return maps_.empty(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::empty(), and maps_.
Referenced by v8::internal::KeyedStoreIC::UpdateStoreElement().
end()
Iterator v8::internal::MapsAndHandlers::end () const [inline]
Definition at line 172 of file feedback-vector.h.
{ return Iterator(this, size()); }
References size().
maps()
base::Vector<DirectHandle<Map> > v8::internal::MapsAndHandlers::maps () [inline]
Definition at line 174 of file feedback-vector.h.
{ return base::VectorOf(maps_); }
References maps_, and v8::base::VectorOf().
Referenced by v8::internal::anonymous_namespace{ic.cc}::AddOneReceiverMapIfMissing(), v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers(), v8::internal::IC::UpdatePolymorphicIC(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
operator[]()
MapAndHandler v8::internal::MapsAndHandlers::operator[] (size_t i) const [inline]
Definition at line 100 of file feedback-vector.h.
                                           {
    DCHECK_LT(i, size());
    MaybeObjectDirectHandle handler;
    switch (handlers_reference_types_[i]) {
      case HeapObjectReferenceType::STRONG:
        handler = MaybeObjectDirectHandle(handlers_[i]);
        break;
      case HeapObjectReferenceType::WEAK:
        handler = MaybeObjectDirectHandle::Weak(handlers_[i]);
        break;
    }
    return MapAndHandler(maps_[i], handler);
  }
References DCHECK_LT, handlers_, handlers_reference_types_, maps_, size(), STRONG, WEAK, and v8::internal::MaybeObjectDirectHandle::Weak().
reserve()
void v8::internal::MapsAndHandlers::reserve (size_t capacity) [inline]
Definition at line 95 of file feedback-vector.h.
                                {
    maps_.reserve(capacity);
    handlers_.reserve(capacity);
  }
References handlers_, maps_, and v8::internal::DirectHandleSmallVector< T, kSize >::reserve().
Referenced by v8::internal::IC::ConfigureVectorState(), and v8::internal::IC::UpdatePolymorphicIC().
set_handler()
void v8::internal::MapsAndHandlers::set_handler (size_t i, MaybeObjectDirectHandle handler) [inline]
Definition at line 119 of file feedback-vector.h.
                                                              {
    DCHECK_LT(i, size());
    handlers_[i] =
        handler.is_null() ? DirectHandle<Object>() : handler.object();
    handlers_reference_types_[i] = handler.reference_type();
  }
References DCHECK_LT, handlers_, handlers_reference_types_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MaybeObjectDirectHandle::is_null(), v8::internal::MaybeObjectDirectHandle::object(), v8::internal::MaybeObjectDirectHandle::reference_type(), and size().
Referenced by v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers(), and v8::internal::IC::UpdatePolymorphicIC().
set_map()
void v8::internal::MapsAndHandlers::set_map (size_t i, DirectHandle< Map > map) [inline]
Definition at line 114 of file feedback-vector.h.
                                                {
    DCHECK_LT(i, size());
    maps_[i] = map;
  }
References DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, maps_, and size().
Referenced by v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers(), and v8::internal::IC::UpdatePolymorphicIC().
size()
size_t v8::internal::MapsAndHandlers::size () const [inline]
Definition at line 94 of file feedback-vector.h.
{ return maps_.size(); }
References maps_, and v8::internal::DirectHandleSmallVector< T, kSize >::size().
Referenced by v8::internal::FeedbackNexus::ConfigurePolymorphic(), end(), operator[](), set_handler(), set_map(), v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers(), v8::internal::IC::UpdatePolymorphicIC(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
Member Data Documentation
handlers_
DirectHandleSmallVector<Object, DEFAULT_MAX_POLYMORPHIC_MAP_COUNT> v8::internal::MapsAndHandlers::handlers_ [private]
Definition at line 178 of file feedback-vector.h.
Referenced by emplace_back(), operator[](), reserve(), and set_handler().
handlers_reference_types_
base::SmallVector<HeapObjectReferenceType, DEFAULT_MAX_POLYMORPHIC_MAP_COUNT> v8::internal::MapsAndHandlers::handlers_reference_types_ [private]
Definition at line 180 of file feedback-vector.h.
Referenced by emplace_back(), operator[](), and set_handler().
maps_
DirectHandleSmallVector<Map, DEFAULT_MAX_POLYMORPHIC_MAP_COUNT> v8::internal::MapsAndHandlers::maps_ [private]
Definition at line 177 of file feedback-vector.h.
Referenced by emplace_back(), empty(), maps(), operator[](), reserve(), set_map(), and size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/feedback-vector.h