v8::internal::compiler::PipelineImpl Class Reference
Public Member Functions
PipelineImpl (TFPipelineData *data)
template<turboshaft::TurbofanPhase Phase, typename... Args>
V8_WARN_UNUSED_RESULT bool Run (Args &&... args)
V8_WARN_UNUSED_RESULT bool InitializeHeapBroker ()
V8_WARN_UNUSED_RESULT bool CreateGraph (Linkage *linkage)
bool OptimizeTurbofanGraph (Linkage *linkage)
V8_WARN_UNUSED_RESULT bool ComputeScheduledGraph ()
V8_WARN_UNUSED_RESULT bool AllocateRegisters (CallDescriptor *call_descriptor, bool has_dummy_end_block)
MaybeDirectHandle< Code > FinalizeCode (bool retire_broker=true)
bool CommitDependencies (Handle< Code > code)
void RunPrintAndVerify (const char *phase, bool untyped=false)
TFPipelineData * data () const
OptimizedCompilationInfo * info () const
Isolate * isolate () const
CodeGenerator * code_generator () const
ObserveNodeManager * observe_node_manager () const
template<turboshaft::TurbofanPhase Phase, typename... Args>
bool Run (Args &&... args)
Private Attributes
TFPipelineData *const data_
Detailed Description
Definition at line 158 of file pipeline.cc.
Constructor & Destructor Documentation
PipelineImpl()
v8::internal::compiler::PipelineImpl::PipelineImpl (TFPipelineData * data) [inline], [explicit]
Definition at line 160 of file pipeline.cc.
: data_(data) {}
Member Function Documentation
AllocateRegisters()
V8_WARN_UNUSED_RESULT bool v8::internal::compiler::PipelineImpl::AllocateRegisters (CallDescriptor * call_descriptor, bool has_dummy_end_block)
code_generator()
CodeGenerator * v8::internal::compiler::PipelineImpl::code_generator () const
Definition at line 3306 of file pipeline.cc.
                                                  {
  return data_->code_generator();
}
CommitDependencies()
bool v8::internal::compiler::PipelineImpl::CommitDependencies (Handle< Code > code)
ComputeScheduledGraph()
bool v8::internal::compiler::PipelineImpl::ComputeScheduledGraph ()
Definition at line 3287 of file pipeline.cc.
                                         {
  TFPipelineData* data = this->data_;
  // We should only schedule the graph if it is not scheduled yet.
  DCHECK_NULL(data->schedule());
  RUN_MAYBE_ABORT(ComputeSchedulePhase);
  TraceScheduleAndVerify(data->info(), data, data->schedule(), "schedule");
  return true;
}
References DCHECK_NULL, v8::internal::compiler::TFPipelineData::info(), RUN_MAYBE_ABORT, v8::internal::compiler::TFPipelineData::schedule(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::TraceScheduleAndVerify().
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting().
CreateGraph()
bool v8::internal::compiler::PipelineImpl::CreateGraph (Linkage * linkage)
Definition at line 1967 of file pipeline.cc.
                                               {
  DCHECK(!v8_flags.turbolev);
  TFPipelineData* data = this->data_;
  UnparkedScopeIfNeeded unparked_scope(data->broker());
  data->BeginPhaseKind("V8.TFGraphCreation");
  RUN_MAYBE_ABORT(GraphBuilderPhase, linkage);
  RunPrintAndVerify(GraphBuilderPhase::phase_name(), true);
  // Perform function context specialization and inlining (if enabled).
  RUN_MAYBE_ABORT(InliningPhase);
  RunPrintAndVerify(InliningPhase::phase_name(), true);
  // Determine the Typer operation flags.
  {
    SharedFunctionInfoRef shared_info =
        MakeRef(data->broker(), info()->shared_info());
    if (is_sloppy(shared_info.language_mode()) &&
        shared_info.IsUserJavaScript()) {
      // Sloppy mode functions always have an Object for this.
      data->AddTyperFlag(Typer::kThisIsReceiver);
    }
    if (IsClassConstructor(shared_info.kind())) {
      // Class constructors cannot be [[Call]]ed.
      data->AddTyperFlag(Typer::kNewTargetIsReceiver);
    }
  }
  data->EndPhaseKind();
  return !info()->was_cancelled();
}
References v8::internal::compiler::TFPipelineData::AddTyperFlag(), v8::internal::compiler::TFPipelineData::BeginPhaseKind(), v8::internal::compiler::TFPipelineData::broker(), v8::internal::compiler::PipelineCompilationJob::data_, v8::internal::DCHECK(), v8::internal::compiler::TFPipelineData::EndPhaseKind(), v8::internal::is_sloppy(), v8::internal::IsClassConstructor(), v8::internal::compiler::Typer::kNewTargetIsReceiver, v8::internal::compiler::Typer::kThisIsReceiver, v8::internal::compiler::MakeRef(), RUN_MAYBE_ABORT, and v8::internal::v8_flags.
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
data()
TFPipelineData* v8::internal::compiler::PipelineImpl::data () const [inline]
Definition at line 194 of file pipeline.cc.
{ return data_; }
References data_.
Referenced by v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl().
FinalizeCode()
MaybeDirectHandle<Code> v8::internal::compiler::PipelineImpl::FinalizeCode (bool retire_broker = true)
info()
OptimizedCompilationInfo * v8::internal::compiler::PipelineImpl::info () const
Definition at line 3302 of file pipeline.cc.
{ return data_->info(); }
InitializeHeapBroker()
bool v8::internal::compiler::PipelineImpl::InitializeHeapBroker ()
Definition at line 1934 of file pipeline.cc.
                                        {
  TFPipelineData* data = data_;
  data->BeginPhaseKind("V8.TFBrokerInitAndSerialization");
  if (info()->trace_turbo_json() || info()->trace_turbo_graph()) {
    CodeTracer::StreamScope tracing_scope(data->GetCodeTracer());
    tracing_scope.stream()
        << "---------------------------------------------------\n"
        << "Begin compiling method " << info()->GetDebugName().get()
        << " using TurboFan" << std::endl;
  }
  if (info()->trace_turbo_json()) {
    TurboCfgFile tcf(isolate());
    tcf << AsC1VCompilation(info());
  }
  if (data->info()->has_bytecode_array()) {
    if (data->info()->bytecode_array()->SourcePositionTable()->DataSize() ==
        0) {
      data->source_positions()->Disable();
    }
    data->source_positions()->AddDecorator();
  }
  if (data->info()->trace_turbo_json()) {
    data->node_origins()->AddDecorator();
  }
  RUN_MAYBE_ABORT(HeapBrokerInitializationPhase);
  data->broker()->StopSerializing();
  data->EndPhaseKind();
  return !info()->was_cancelled();
}
References v8::internal::compiler::SourcePositionTable::AddDecorator(), v8::internal::compiler::NodeOriginTable::AddDecorator(), v8::internal::compiler::TFPipelineData::BeginPhaseKind(), v8::internal::compiler::TFPipelineData::broker(), v8::internal::OptimizedCompilationInfo::bytecode_array(), v8::internal::compiler::PipelineCompilationJob::data_, v8::internal::compiler::SourcePositionTable::Disable(), v8::internal::compiler::TFPipelineData::EndPhaseKind(), v8::internal::compiler::TFPipelineData::GetCodeTracer(), v8::internal::OptimizedCompilationInfo::has_bytecode_array(), v8::internal::compiler::TFPipelineData::info(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::TFPipelineData::node_origins(), RUN_MAYBE_ABORT, v8::internal::compiler::TFPipelineData::source_positions(), v8::internal::compiler::JSHeapBroker::StopSerializing(), and v8::internal::CodeTracer::StreamScope::stream().
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl().
isolate()
Isolate * v8::internal::compiler::PipelineImpl::isolate () const
Definition at line 3304 of file pipeline.cc.
{ return data_->isolate(); }
References v8::internal::Factory::isolate().
observe_node_manager()
ObserveNodeManager * v8::internal::compiler::PipelineImpl::observe_node_manager () const
Definition at line 3310 of file pipeline.cc.
                                                             {
  return data_->observe_node_manager();
}
OptimizeTurbofanGraph()
bool v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph (Linkage * linkage)
Definition at line 2001 of file pipeline.cc.
                                                         {
  DCHECK(!v8_flags.turbolev);
  TFPipelineData* data = this->data_;
  data->BeginPhaseKind("V8.TFLowering");
  // Trim the graph before typing to ensure all nodes are typed.
  RUN_MAYBE_ABORT(EarlyGraphTrimmingPhase);
  RunPrintAndVerify(EarlyGraphTrimmingPhase::phase_name(), true);
  // Type the graph and keep the Typer running such that new nodes get
  // automatically typed when they are created.
  RUN_MAYBE_ABORT(TyperPhase, data->CreateTyper());
  RunPrintAndVerify(TyperPhase::phase_name());
  RUN_MAYBE_ABORT(TypedLoweringPhase);
  RunPrintAndVerify(TypedLoweringPhase::phase_name());
  if (data->info()->loop_peeling()) {
    RUN_MAYBE_ABORT(LoopPeelingPhase);
    RunPrintAndVerify(LoopPeelingPhase::phase_name(), true);
  } else {
    RUN_MAYBE_ABORT(LoopExitEliminationPhase);
    RunPrintAndVerify(LoopExitEliminationPhase::phase_name(), true);
  }
  if (v8_flags.turbo_load_elimination) {
    RUN_MAYBE_ABORT(LoadEliminationPhase);
    RunPrintAndVerify(LoadEliminationPhase::phase_name());
  }
  data->DeleteTyper();
  if (v8_flags.turbo_escape) {
    RUN_MAYBE_ABORT(EscapeAnalysisPhase);
    RunPrintAndVerify(EscapeAnalysisPhase::phase_name());
  }
  if (v8_flags.assert_types) {
    RUN_MAYBE_ABORT(TypeAssertionsPhase);
    RunPrintAndVerify(TypeAssertionsPhase::phase_name());
  }
  // Perform simplified lowering. This has to run w/o the Typer decorator,
  // because we cannot compute meaningful types anyways, and the computed
  // types might even conflict with the representation/truncation logic.
  RUN_MAYBE_ABORT(SimplifiedLoweringPhase, linkage);
  RunPrintAndVerify(SimplifiedLoweringPhase::phase_name(), true);
#if V8_ENABLE_WEBASSEMBLY
  if (data->has_js_wasm_calls()) {
    DCHECK(data->info()->inline_js_wasm_calls());
    RUN_MAYBE_ABORT(JSWasmInliningPhase);
    RunPrintAndVerify(JSWasmInliningPhase::phase_name(), true);
    RUN_MAYBE_ABORT(WasmTypingPhase, -1);
    RunPrintAndVerify(WasmTypingPhase::phase_name(), true);
    if (v8_flags.wasm_opt) {
      RUN_MAYBE_ABORT(WasmGCOptimizationPhase, data->wasm_module_for_inlining(),
                      data->jsgraph());
      RunPrintAndVerify(WasmGCOptimizationPhase::phase_name(), true);
    }
    RUN_MAYBE_ABORT(JSWasmLoweringPhase);
    RunPrintAndVerify(JSWasmLoweringPhase::phase_name(), true);
    if (v8_flags.turbo_optimize_inlined_js_wasm_wrappers && v8_flags.wasm_opt) {
      wasm::WasmDetectedFeatures detected({wasm::WasmDetectedFeature::gc});
      RUN_MAYBE_ABORT(WasmOptimizationPhase,
                      MachineOperatorReducer::kSilenceSignallingNan, detected);
      RunPrintAndVerify(WasmOptimizationPhase::phase_name(), true);
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
  // From now on it is invalid to look at types on the nodes, because the
  // types on the nodes might not make sense after representation selection
  // due to the way we handle truncations; if we'd want to look at types
  // afterwards we'd essentially need to re-type (large portions of) the
  // graph.
  // In order to catch bugs related to type access after this point, we now
  // remove the types from the nodes (currently only in Debug builds).
#ifdef DEBUG
  RUN_MAYBE_ABORT(UntyperPhase);
  RunPrintAndVerify(UntyperPhase::phase_name(), true);
#endif
  // Run generic lowering pass.
  RUN_MAYBE_ABORT(GenericLoweringPhase);
  RunPrintAndVerify(GenericLoweringPhase::phase_name(), true);
  data->BeginPhaseKind("V8.TFBlockBuilding");
  data->InitializeFrameData(linkage->GetIncomingDescriptor());
  // Run early optimization pass.
  RUN_MAYBE_ABORT(EarlyOptimizationPhase);
  RunPrintAndVerify(EarlyOptimizationPhase::phase_name(), true);
  data->source_positions()->RemoveDecorator();
  if (data->info()->trace_turbo_json()) {
    data->node_origins()->RemoveDecorator();
  }
  if (!ComputeScheduledGraph()) return false;
  return !info()->was_cancelled();
}
References v8::internal::compiler::TFPipelineData::BeginPhaseKind(), v8::internal::compiler::TFPipelineData::CreateTyper(), v8::internal::compiler::PipelineCompilationJob::data_, v8::internal::DCHECK(), v8::internal::compiler::TFPipelineData::DeleteTyper(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::compiler::TFPipelineData::info(), v8::internal::compiler::TFPipelineData::InitializeFrameData(), v8::internal::compiler::TFPipelineData::jsgraph(), v8::internal::compiler::MachineOperatorReducer::kSilenceSignallingNan, v8::internal::compiler::TFPipelineData::node_origins(), v8::internal::compiler::SourcePositionTable::RemoveDecorator(), v8::internal::compiler::NodeOriginTable::RemoveDecorator(), RUN_MAYBE_ABORT, v8::internal::compiler::TFPipelineData::source_positions(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
Run() [1/2]
template<turboshaft::TurbofanPhase Phase, typename... Args>
V8_WARN_UNUSED_RESULT bool v8::internal::compiler::PipelineImpl::Run (Args &&... args)
Referenced by v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl().
Run() [2/2]
template<turboshaft::TurbofanPhase Phase, typename... Args>
bool v8::internal::compiler::PipelineImpl::Run (Args &&... args)
Definition at line 841 of file pipeline.cc.
                                     {
#ifdef V8_RUNTIME_CALL_STATS
  PipelineRunScope scope(this->data_, Phase::phase_name(),
                         Phase::kRuntimeCallCounterId, Phase::kCounterMode);
#else
  PipelineRunScope scope(this->data_, Phase::phase_name());
#endif
  Phase phase;
  static_assert(Phase::kKind == PhaseKind::kTurbofan);
  phase.Run(this->data_, scope.zone(), std::forward<Args>(args)...);
  return !info()->was_cancelled();
}
References v8::base::args, v8::internal::compiler::PipelineCompilationJob::data_, v8::internal::compiler::kTurbofan, and v8::internal::OptimizedCompilationInfo::was_cancelled().
RunPrintAndVerify()
void v8::internal::compiler::PipelineImpl::RunPrintAndVerify (const char * phase, bool untyped = false)
Definition at line 1925 of file pipeline.cc.
                                                                    {
  if (info()->trace_turbo_json() || info()->trace_turbo_graph()) {
    USE(Run<PrintGraphPhase>(phase));
  }
  if (v8_flags.turbo_verify) {
    USE(Run<VerifyGraphPhase>(untyped));
  }
}
References USE, and v8::internal::v8_flags.
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting().
Member Data Documentation
data_
TFPipelineData* const v8::internal::compiler::PipelineImpl::data_ [private]
Definition at line 202 of file pipeline.cc.
Referenced by data().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc