v8::platform::DefaultJobState Class Reference
#include <default-job.h>
Classes
class JobDelegate
Public Member Functions
DefaultJobState (Platform *platform, std::unique_ptr< JobTask > job_task, TaskPriority priority, size_t num_worker_threads)
virtual ~DefaultJobState ()
void NotifyConcurrencyIncrease ()
uint8_t AcquireTaskId ()
void ReleaseTaskId (uint8_t task_id)
void Join ()
void CancelAndWait ()
void CancelAndDetach ()
bool IsActive ()
bool CanRunFirstTask ()
bool DidRunTask ()
void UpdatePriority (TaskPriority)
Private Member Functions
size_t CappedMaxConcurrency (size_t worker_count) const
void CallOnWorkerThread (TaskPriority priority, std::unique_ptr< Task > task)
Private Attributes
Platform *const platform_
std::unique_ptr< JobTask > job_task_
base::Mutex mutex_
TaskPriority priority_
size_t active_workers_ = 0
size_t pending_tasks_ = 0
std::atomic_bool is_canceled_ {false}
size_t num_worker_threads_
base::ConditionVariable worker_released_condition_
std::atomic< uint32_t > assigned_task_ids_ {0}
Detailed Description
Definition at line 19 of file default-job.h.
Constructor & Destructor Documentation
DefaultJobState()
v8::platform::DefaultJobState::DefaultJobState (Platform * platform, std::unique_ptr< JobTask > job_task, TaskPriority priority, size_t num_worker_threads)
Definition at line 31 of file default-job.cc.
    : platform_(platform),
      job_task_(std::move(job_task)),
      priority_(priority),
      num_worker_threads_(std::min(num_worker_threads, kMaxWorkersPerJob)) {}
 DefaultJobState()
v8::platform::DefaultJobState::~DefaultJobState () [virtual]
Definition at line 40 of file default-job.cc.
{ DCHECK_EQ(0U, active_workers_); }
References active_workers_, DCHECK_EQ, and v8::base::internal::U.
Member Function Documentation
AcquireTaskId()
uint8_t v8::platform::DefaultJobState::AcquireTaskId ()
Definition at line 64 of file default-job.cc.
                                       {
  static_assert(kMaxWorkersPerJob <= sizeof(assigned_task_ids_) * 8,
                "TaskId bitfield isn't big enough to fit kMaxWorkersPerJob.");
  uint32_t assigned_task_ids =
      assigned_task_ids_.load(std::memory_order_relaxed);
  DCHECK_LE(v8::base::bits::CountPopulation(assigned_task_ids) + 1,
            kMaxWorkersPerJob);
  uint32_t new_assigned_task_ids = 0;
  uint8_t task_id = 0;
  // memory_order_acquire on success, matched with memory_order_release in
  // ReleaseTaskId() so that operations done by previous threads that had
  // the same task_id become visible to the current thread.
  do {
    // Count trailing one bits. This is the id of the right-most 0-bit in
    // |assigned_task_ids|.
    task_id = v8::base::bits::CountTrailingZeros32(~assigned_task_ids);
    new_assigned_task_ids = assigned_task_ids | (uint32_t(1) << task_id);
  } while (!assigned_task_ids_.compare_exchange_weak(
      assigned_task_ids, new_assigned_task_ids, std::memory_order_acquire,
      std::memory_order_relaxed));
  return task_id;
}
References assigned_task_ids_, v8::base::bits::CountPopulation(), v8::base::bits::CountTrailingZeros32(), DCHECK_LE, and v8::platform::anonymous_namespace{default-job.cc}::kMaxWorkersPerJob.
CallOnWorkerThread()
void v8::platform::DefaultJobState::CallOnWorkerThread (TaskPriority priority, std::unique_ptr< Task > task) [private]
Definition at line 215 of file default-job.cc.
                                                                   {
  platform_->PostTaskOnWorkerThread(priority, std::move(task));
}
References platform_, and v8::Platform::PostTaskOnWorkerThread().
Referenced by DidRunTask(), Join(), and NotifyConcurrencyIncrease().
CancelAndDetach()
void v8::platform::DefaultJobState::CancelAndDetach ()
Definition at line 158 of file default-job.cc.
                                      {
  is_canceled_.store(true, std::memory_order_relaxed);
}
References is_canceled_.
CancelAndWait()
void v8::platform::DefaultJobState::CancelAndWait ()
Definition at line 148 of file default-job.cc.
                                    {
  {
    base::MutexGuard guard(&mutex_);
    is_canceled_.store(true, std::memory_order_relaxed);
    while (active_workers_ > 0) {
      worker_released_condition_.Wait(&mutex_);
    }
  }
}
References active_workers_, is_canceled_, mutex_, v8::base::ConditionVariable::Wait(), and worker_released_condition_.
CanRunFirstTask()
bool v8::platform::DefaultJobState::CanRunFirstTask ()
Definition at line 168 of file default-job.cc.
                                      {
  base::MutexGuard guard(&mutex_);
  --pending_tasks_;
  if (is_canceled_.load(std::memory_order_relaxed)) return false;
  if (active_workers_ >= CappedMaxConcurrency(active_workers_)) return false;
  // Acquire current worker.
  ++active_workers_;
  return true;
}
References active_workers_, CappedMaxConcurrency(), is_canceled_, mutex_, and pending_tasks_.
CappedMaxConcurrency()
size_t v8::platform::DefaultJobState::CappedMaxConcurrency (size_t worker_count) const [private]
Definition at line 210 of file default-job.cc.
                                                                      {
  return std::min(job_task_->GetMaxConcurrency(worker_count),
                  num_worker_threads_);
}
References job_task_, and num_worker_threads_.
Referenced by CanRunFirstTask(), DidRunTask(), Join(), and NotifyConcurrencyIncrease().
DidRunTask()
bool v8::platform::DefaultJobState::DidRunTask ()
Definition at line 178 of file default-job.cc.
                                 {
  size_t num_tasks_to_post = 0;
  TaskPriority priority;
  {
    base::MutexGuard guard(&mutex_);
    const size_t max_concurrency = CappedMaxConcurrency(active_workers_ - 1);
    if (is_canceled_.load(std::memory_order_relaxed) ||
        active_workers_ > max_concurrency) {
      // Release current worker and notify.
      --active_workers_;
      worker_released_condition_.NotifyOne();
      return false;
    }
    // Consider |pending_tasks_| to avoid posting too many tasks.
    if (max_concurrency > active_workers_ + pending_tasks_) {
      num_tasks_to_post = max_concurrency - active_workers_ - pending_tasks_;
      pending_tasks_ += num_tasks_to_post;
    }
    priority = priority_;
  }
  // Post additional worker tasks to reach |max_concurrency| in the case that
  // max concurrency increased. This is not strictly necessary, since
  // NotifyConcurrencyIncrease() should eventually be invoked. However, some
  // users of PostJob() batch work and tend to call NotifyConcurrencyIncrease()
  // late. Posting here allows us to spawn new workers sooner.
  for (size_t i = 0; i < num_tasks_to_post; ++i) {
    CallOnWorkerThread(priority, std::make_unique<DefaultJobWorker>(
                                     shared_from_this(), job_task_.get()));
  }
  return true;
}
References active_workers_, CallOnWorkerThread(), CappedMaxConcurrency(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_canceled_, job_task_, mutex_, v8::base::ConditionVariable::NotifyOne(), pending_tasks_, priority_, and worker_released_condition_.
IsActive()
bool v8::platform::DefaultJobState::IsActive ()
Definition at line 162 of file default-job.cc.
                               {
  base::MutexGuard guard(&mutex_);
  return job_task_->GetMaxConcurrency(active_workers_) != 0 ||
         active_workers_ != 0;
}
References active_workers_, job_task_, and mutex_.
Join()
void v8::platform::DefaultJobState::Join ()
Definition at line 95 of file default-job.cc.
                           {
  auto WaitForParticipationOpportunity = [this]() -> size_t {
    // Subtract one from active_workers_ since the current thread is not
    // participating yet.
    size_t max_concurrency = CappedMaxConcurrency(active_workers_ - 1);
    // Wait until we can participate in the job.
    while (active_workers_ > max_concurrency && active_workers_ > 1) {
      worker_released_condition_.Wait(&mutex_);
      max_concurrency = CappedMaxConcurrency(active_workers_ - 1);
    }
    DCHECK_LE(0, max_concurrency);
    if (max_concurrency != 0) return max_concurrency;
    // The job is done (max_concurrency dropped to zero).
    DCHECK_EQ(1, active_workers_);
    active_workers_ = 0;
    is_canceled_.store(true, std::memory_order_relaxed);
    return 0;
  };
  size_t num_tasks_to_post = 0;
  {
    base::MutexGuard guard(&mutex_);
    priority_ = TaskPriority::kUserBlocking;
    // Reserve a worker for the joining (current) thread.
    // GetMaxConcurrency() is ignored here, but if necessary we wait below
    // for workers to return so we don't exceed GetMaxConcurrency().
    ++num_worker_threads_;
    ++active_workers_;
    size_t max_concurrency = WaitForParticipationOpportunity();
    if (max_concurrency == 0) return;
    // Compute the number of additional worker tasks to spawn.
    if (max_concurrency > active_workers_ + pending_tasks_) {
      num_tasks_to_post = max_concurrency - active_workers_ - pending_tasks_;
      pending_tasks_ += num_tasks_to_post;
    }
  }
  // Spawn more worker tasks if needed.
  for (size_t i = 0; i < num_tasks_to_post; ++i) {
    CallOnWorkerThread(TaskPriority::kUserBlocking,
                       std::make_unique<DefaultJobWorker>(shared_from_this(),
                                                          job_task_.get()));
  }
  DefaultJobState::JobDelegate delegate(this, true);
  while (true) {
    // Participate in job execution, as one active worker.
    job_task_->Run(&delegate);
    base::MutexGuard guard(&mutex_);
    if (WaitForParticipationOpportunity() == 0) return;
  }
}
References active_workers_, CallOnWorkerThread(), CappedMaxConcurrency(), DCHECK_EQ, DCHECK_LE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_canceled_, job_task_, v8::kUserBlocking, mutex_, num_worker_threads_, pending_tasks_, priority_, v8::base::ConditionVariable::Wait(), and worker_released_condition_.
NotifyConcurrencyIncrease()
void v8::platform::DefaultJobState::NotifyConcurrencyIncrease ()
Definition at line 42 of file default-job.cc.
                                                {
  if (is_canceled_.load(std::memory_order_relaxed)) return;
  size_t num_tasks_to_post = 0;
  TaskPriority priority;
  {
    base::MutexGuard guard(&mutex_);
    const size_t max_concurrency = CappedMaxConcurrency(active_workers_);
    // Consider |pending_tasks_| to avoid posting too many tasks.
    if (max_concurrency > active_workers_ + pending_tasks_) {
      num_tasks_to_post = max_concurrency - active_workers_ - pending_tasks_;
      pending_tasks_ += num_tasks_to_post;
    }
    priority = priority_;
  }
  // Post additional worker tasks to reach |max_concurrency|.
  for (size_t i = 0; i < num_tasks_to_post; ++i) {
    CallOnWorkerThread(priority, std::make_unique<DefaultJobWorker>(
                                     shared_from_this(), job_task_.get()));
  }
}
References active_workers_, CallOnWorkerThread(), CappedMaxConcurrency(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_canceled_, job_task_, mutex_, pending_tasks_, and priority_.
ReleaseTaskId()
void v8::platform::DefaultJobState::ReleaseTaskId (uint8_t task_id)
Definition at line 87 of file default-job.cc.
                                                   {
  // memory_order_release to match AcquireTaskId().
  uint32_t previous_task_ids = assigned_task_ids_.fetch_and(
      ~(uint32_t(1) << task_id), std::memory_order_release);
  DCHECK(previous_task_ids & (uint32_t(1) << task_id));
  USE(previous_task_ids);
}
References assigned_task_ids_, DCHECK, and USE.
Referenced by v8::platform::DefaultJobState::JobDelegate::~JobDelegate().
UpdatePriority()
void v8::platform::DefaultJobState::UpdatePriority (TaskPriority priority)
Definition at line 220 of file default-job.cc.
                                                          {
  base::MutexGuard guard(&mutex_);
  priority_ = priority;
}
References mutex_, and priority_.
Member Data Documentation
active_workers_
size_t v8::platform::DefaultJobState::active_workers_ = 0 [private]
Definition at line 91 of file default-job.h.
Referenced by CancelAndWait(), CanRunFirstTask(), DidRunTask(), IsActive(), Join(), NotifyConcurrencyIncrease(), and ~DefaultJobState().
assigned_task_ids_
std::atomic<uint32_t> v8::platform::DefaultJobState::assigned_task_ids_ {0} [private]
Definition at line 101 of file default-job.h.
Referenced by AcquireTaskId(), and ReleaseTaskId().
is_canceled_
std::atomic_bool v8::platform::DefaultJobState::is_canceled_ {false} [private]
Definition at line 95 of file default-job.h.
Referenced by CancelAndDetach(), CancelAndWait(), CanRunFirstTask(), DidRunTask(), Join(), and NotifyConcurrencyIncrease().
job_task_
std::unique_ptr<JobTask> v8::platform::DefaultJobState::job_task_ [private]
Definition at line 85 of file default-job.h.
Referenced by CappedMaxConcurrency(), DidRunTask(), IsActive(), Join(), and NotifyConcurrencyIncrease().
mutex_
base::Mutex v8::platform::DefaultJobState::mutex_ [private]
Definition at line 88 of file default-job.h.
Referenced by CancelAndWait(), CanRunFirstTask(), DidRunTask(), IsActive(), Join(), NotifyConcurrencyIncrease(), and UpdatePriority().
num_worker_threads_
size_t v8::platform::DefaultJobState::num_worker_threads_ [private]
Definition at line 97 of file default-job.h.
Referenced by CappedMaxConcurrency(), and Join().
pending_tasks_
size_t v8::platform::DefaultJobState::pending_tasks_ = 0 [private]
Definition at line 93 of file default-job.h.
Referenced by CanRunFirstTask(), DidRunTask(), Join(), and NotifyConcurrencyIncrease().
platform_
Platform* const v8::platform::DefaultJobState::platform_ [private]
Definition at line 84 of file default-job.h.
Referenced by CallOnWorkerThread().
priority_
TaskPriority v8::platform::DefaultJobState::priority_ [private]
Definition at line 89 of file default-job.h.
Referenced by DidRunTask(), Join(), NotifyConcurrencyIncrease(), and UpdatePriority().
worker_released_condition_
base::ConditionVariable v8::platform::DefaultJobState::worker_released_condition_ [private]
Definition at line 99 of file default-job.h.
Referenced by CancelAndWait(), DidRunTask(), and Join().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/libplatform/default-job.h
/mnt/V8SourceCode/src/libplatform/default-job.cc