v8::internal::maglev::LoadNamedFromSuperGeneric Class Reference
#include <maglev-ir.h>
Public Member Functions
LoadNamedFromSuperGeneric (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource &feedback)
compiler::NameRef name () const
compiler::FeedbackSource feedback () const
Input & context ()
Input & receiver ()
Input & lookup_start_object ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
static constexpr int kContextIndex = 0
static constexpr int kReceiverIndex = 1
static constexpr int kLookupStartObjectIndex = 2
Private Types
using Base = FixedInputValueNodeT< 3, LoadNamedFromSuperGeneric >
Private Attributes
const compiler::NameRef name_
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 9355 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::LoadNamedFromSuperGeneric::Base = FixedInputValueNodeT<3, LoadNamedFromSuperGeneric> [private]
Definition at line 9357 of file maglev-ir.h.
Constructor & Destructor Documentation
LoadNamedFromSuperGeneric()
v8::internal::maglev::LoadNamedFromSuperGeneric::LoadNamedFromSuperGeneric (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 9360 of file maglev-ir.h.
      : Base(bitfield), name_(name), feedback_(feedback) {}
Member Function Documentation
context()
Input& v8::internal::maglev::LoadNamedFromSuperGeneric::context () [inline]
Definition at line 9376 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::LoadNamedFromSuperGeneric::feedback () const [inline]
Definition at line 9371 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::LoadNamedFromSuperGeneric::GenerateCode (MaglevAssembler * , const ProcessingState &)
lookup_start_object()
Input& v8::internal::maglev::LoadNamedFromSuperGeneric::lookup_start_object () [inline]
Definition at line 9378 of file maglev-ir.h.
{ return input(kLookupStartObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::LoadNamedFromSuperGeneric::MaxCallStackArgs () const
name()
compiler::NameRef v8::internal::maglev::LoadNamedFromSuperGeneric::name () const [inline]
Definition at line 9370 of file maglev-ir.h.
{ return name_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::LoadNamedFromSuperGeneric::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8274 of file maglev-ir.cc.
                                                               {
  os << "(" << *name_.object() << ")";
}
References name_, and v8::internal::compiler::NameRef::object().
receiver()
Input& v8::internal::maglev::LoadNamedFromSuperGeneric::receiver () [inline]
Definition at line 9377 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::LoadNamedFromSuperGeneric::SetValueLocationConstraints ()
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::LoadNamedFromSuperGeneric::feedback_ [private]
Definition at line 9387 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::LoadNamedFromSuperGeneric::kContextIndex = 0 [static], [constexpr]
Definition at line 9373 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::LoadNamedFromSuperGeneric::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged}
Definition at line 9366 of file maglev-ir.h.
kLookupStartObjectIndex
constexpr int v8::internal::maglev::LoadNamedFromSuperGeneric::kLookupStartObjectIndex = 2 [static], [constexpr]
Definition at line 9375 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::LoadNamedFromSuperGeneric::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 9365 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::LoadNamedFromSuperGeneric::kReceiverIndex = 1 [static], [constexpr]
Definition at line 9374 of file maglev-ir.h.
name_
const compiler::NameRef v8::internal::maglev::LoadNamedFromSuperGeneric::name_ [private]
Definition at line 9386 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc