v8::internal::wasm::WasmBytecode Class Reference
#include <wasm-interpreter.h>
Public Member Functions
WasmBytecode (int func_index, const uint8_t *code_data, size_t code_length, uint32_t stack_frame_size, const FunctionSig *signature, const CanonicalSig *canonical_signature, const InterpreterCode *interpreter_code, size_t blocks_count, const uint8_t *const_slots_data, size_t const_slots_length, uint32_t ref_slots_count, const WasmEHData &&eh_data, const std::map< CodeOffset, pc_t > &&code_pc_map)
const uint8_t * GetCode () const
size_t GetCodeSize () const
bool InitializeSlots (uint8_t *sp, size_t stack_space) const
pc_t GetPcFromTrapCode (const uint8_t *current_code) const
int GetFunctionIndex () const
uint32_t GetBlocksCount () const
const FunctionSig * GetFunctionSignature () const
const CanonicalSig * GetCanonicalFunctionSignature () const
ValueType return_type (size_t index) const
ValueType arg_type (size_t index) const
ValueType local_type (size_t index) const
uint32_t args_count () const
uint32_t args_slots_size () const
uint32_t return_count () const
uint32_t rets_slots_size () const
uint32_t locals_count () const
uint32_t locals_slots_size () const
uint32_t const_slots_size_in_bytes () const
uint32_t ref_args_count () const
uint32_t ref_rets_count () const
uint32_t ref_locals_count () const
uint32_t ref_slots_count () const
uint32_t internal_ref_slots_count () const
uint32_t frame_size ()
const WasmEHData::TryBlock * GetTryBlock (CodeOffset code_offset) const
const WasmEHData::TryBlock * GetParentTryBlock (const WasmEHData::TryBlock *try_block) const
WasmEHData::ExceptionPayloadSlotOffsets GetExceptionPayloadStartSlotOffsets (WasmEHData::BlockIndex catch_block_index) const
DirectHandle< Object > GetCaughtException (Isolate *isolate, uint32_t catch_block_index) const
Static Public Member Functions
static uint32_t ArgsSizeInSlots (const FunctionSig *sig)
static uint32_t RetsSizeInSlots (const FunctionSig *sig)
static uint32_t RefArgsCount (const FunctionSig *sig)
static uint32_t RefRetsCount (const FunctionSig *sig)
static bool ContainsSimd (const FunctionSig *sig)
static bool HasRefOrSimdArgs (const FunctionSig *sig)
static uint32_t JSToWasmWrapperPackedArraySize (const FunctionSig *sig)
static uint32_t RefLocalsCount (const InterpreterCode *wasm_code)
static uint32_t LocalsSizeInSlots (const InterpreterCode *wasm_code)
Private Attributes
std::vector< uint8_t > code_
const uint8_t * code_bytes_
const FunctionSig * signature_
const CanonicalSig * canonical_signature_
const InterpreterCode * interpreter_code_
std::vector< uint8_t > const_slots_values_
int func_index_
uint32_t blocks_count_
uint32_t args_count_
uint32_t args_slots_size_
uint32_t return_count_
uint32_t rets_slots_size_
uint32_t locals_count_
uint32_t locals_slots_size_
uint32_t total_frame_size_in_bytes_
uint32_t ref_args_count_
uint32_t ref_rets_count_
uint32_t ref_locals_count_
uint32_t ref_slots_count_
WasmEHData eh_data_
std::map< CodeOffset, pc_t > code_pc_map_
Detailed Description
Definition at line 1344 of file wasm-interpreter.h.
Constructor & Destructor Documentation
WasmBytecode()
v8::internal::wasm::WasmBytecode::WasmBytecode (int func_index, const uint8_t * code_data, size_t code_length, uint32_t stack_frame_size, const FunctionSig * signature, const CanonicalSig * canonical_signature, const InterpreterCode * interpreter_code, size_t blocks_count, const uint8_t * const_slots_data, size_t const_slots_length, uint32_t ref_slots_count, const WasmEHData && eh_data, const std::map< CodeOffset, pc_t > && code_pc_map)
Definition at line 7323 of file wasm-interpreter.cc.
    : code_(code_data, code_data + code_length),
      code_bytes_(code_.data()),
      signature_(signature),
      canonical_signature_(canonical_signature),
      interpreter_code_(interpreter_code),
      const_slots_values_(const_slots_data,
                          const_slots_data + const_slots_length),
      func_index_(func_index),
      blocks_count_(static_cast<uint32_t>(blocks_count)),
      args_count_(static_cast<uint32_t>(signature_->parameter_count())),
      args_slots_size_(ArgsSizeInSlots(signature_)),
      return_count_(static_cast<uint32_t>(signature_->return_count())),
      rets_slots_size_(RetsSizeInSlots(signature_)),
      locals_count_(
          static_cast<uint32_t>(interpreter_code_->locals.num_locals)),
      locals_slots_size_(LocalsSizeInSlots(interpreter_code_)),
      total_frame_size_in_bytes_(stack_frame_size * kSlotSize +
                                 args_slots_size_ * kSlotSize +
                                 rets_slots_size_ * kSlotSize),
      ref_args_count_(RefArgsCount(signature_)),
      ref_rets_count_(RefRetsCount(signature_)),
      ref_locals_count_(RefLocalsCount(interpreter_code)),
      ref_slots_count_(ref_slots_count),
      eh_data_(eh_data),
      code_pc_map_(code_pc_map) {}
Member Function Documentation
arg_type()
ValueType v8::internal::wasm::WasmBytecode::arg_type (size_t index) const [inline]
Definition at line 125 of file wasm-interpreter-inl.h.
                                                          {
  DCHECK_LT(index, args_count());
  return signature_->GetParam(index);
}
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
args_count()
uint32_t v8::internal::wasm::WasmBytecode::args_count () const [inline]
Definition at line 1373 of file wasm-interpreter.h.
{ return args_count_; }
References args_count_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
args_slots_size()
uint32_t v8::internal::wasm::WasmBytecode::args_slots_size () const [inline]
Definition at line 1374 of file wasm-interpreter.h.
{ return args_slots_size_; }
References args_slots_size_.
ArgsSizeInSlots()
uint32_t v8::internal::wasm::WasmBytecode::ArgsSizeInSlots (const FunctionSig * sig) [inline], [static]
Definition at line 166 of file wasm-interpreter-inl.h.
                                                                    {
  uint32_t args_slots_size = 0;
  size_t args_count = sig->parameter_count();
  for (size_t i = 0; i < args_count; i++) {
    args_slots_size += GetValueSizeInSlots(sig->GetParam(i).kind());
  }
  return args_slots_size;
}
References v8::internal::wasm::GetValueSizeInSlots(), and v8::internal::sig.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), and v8::internal::wasm::WasmBytecodeGenerator::WasmBytecodeGenerator().
const_slots_size_in_bytes()
uint32_t v8::internal::wasm::WasmBytecode::const_slots_size_in_bytes () const [inline]
Definition at line 1379 of file wasm-interpreter.h.
                                                    {
    return static_cast<uint32_t>(const_slots_values_.size());
  }
References const_slots_values_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
ContainsSimd()
bool v8::internal::wasm::WasmBytecode::ContainsSimd (const FunctionSig * sig) [inline], [static]
Definition at line 204 of file wasm-interpreter-inl.h.
                                                             {
  size_t args_count = static_cast<uint32_t>(sig->parameter_count());
  for (size_t i = 0; i < args_count; i++) {
    if (sig->GetParam(i).kind() == kS128) return true;
  }
  size_t return_count = static_cast<uint32_t>(sig->return_count());
  for (size_t i = 0; i < return_count; i++) {
    if (sig->GetReturn(i).kind() == kS128) return true;
  }
  return false;
}
References v8::internal::kS128, and v8::internal::sig.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), and v8::internal::RUNTIME_FUNCTION().
frame_size()
uint32_t v8::internal::wasm::WasmBytecode::frame_size () [inline]
Definition at line 1393 of file wasm-interpreter.h.
{ return total_frame_size_in_bytes_; }
References total_frame_size_in_bytes_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
GetBlocksCount()
uint32_t v8::internal::wasm::WasmBytecode::GetBlocksCount () const [inline]
Definition at line 1363 of file wasm-interpreter.h.
{ return blocks_count_; }
References blocks_count_.
GetCanonicalFunctionSignature()
const CanonicalSig* v8::internal::wasm::WasmBytecode::GetCanonicalFunctionSignature () const [inline]
Definition at line 1366 of file wasm-interpreter.h.
                                                                   {
    return canonical_signature_;
  }
References canonical_signature_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution().
GetCaughtException()
DirectHandle<Object> v8::internal::wasm::WasmBytecode::GetCaughtException (Isolate * isolate, uint32_t catch_block_index) const [inline]
Definition at line 1416 of file wasm-interpreter.h.
                                                                            {
    return eh_data_.GetCaughtException(isolate, catch_block_index);
  }
References eh_data_, and v8::internal::wasm::WasmEHData::GetCaughtException().
GetCode()
const uint8_t* v8::internal::wasm::WasmBytecode::GetCode () const [inline]
Definition at line 1354 of file wasm-interpreter.h.
{ return code_bytes_; }
References code_bytes_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
GetCodeSize()
size_t v8::internal::wasm::WasmBytecode::GetCodeSize () const [inline]
Definition at line 1355 of file wasm-interpreter.h.
{ return code_.size(); }
References code_.
GetExceptionPayloadStartSlotOffsets()
WasmEHData::ExceptionPayloadSlotOffsets v8::internal::wasm::WasmBytecode::GetExceptionPayloadStartSlotOffsets (WasmEHData::BlockIndex catch_block_index) const [inline]
Definition at line 1412 of file wasm-interpreter.h.
                                                    {
    return eh_data_.GetExceptionPayloadStartSlotOffsets(catch_block_index);
  }
References eh_data_, and v8::internal::wasm::WasmEHData::GetExceptionPayloadStartSlotOffsets().
GetFunctionIndex()
int v8::internal::wasm::WasmBytecode::GetFunctionIndex () const [inline]
Definition at line 1361 of file wasm-interpreter.h.
{ return func_index_; }
References func_index_.
GetFunctionSignature()
const FunctionSig* v8::internal::wasm::WasmBytecode::GetFunctionSignature () const [inline]
Definition at line 1365 of file wasm-interpreter.h.
{ return signature_; }
References signature_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution().
GetParentTryBlock()
const WasmEHData::TryBlock* v8::internal::wasm::WasmBytecode::GetParentTryBlock (const WasmEHData::TryBlock * try_block) const [inline]
Definition at line 1408 of file wasm-interpreter.h.
                                                 {
    return eh_data_.GetParentTryBlock(try_block);
  }
References eh_data_, and v8::internal::wasm::WasmEHData::GetParentTryBlock().
GetPcFromTrapCode()
pc_t v8::internal::wasm::WasmBytecode::GetPcFromTrapCode (const uint8_t * current_code) const
Definition at line 7358 of file wasm-interpreter.cc.
                                                                      {
  DCHECK_GE(current_code, code_bytes_);
  size_t code_offset = current_code - code_bytes_;
  auto it = code_pc_map_.lower_bound(code_offset);
  if (it == code_pc_map_.begin()) return 0;
  it--;
  return it->second;
}
References code_bytes_, code_pc_map_, and DCHECK_GE.
GetTryBlock()
const WasmEHData::TryBlock* v8::internal::wasm::WasmBytecode::GetTryBlock (CodeOffset code_offset) const [inline]
Definition at line 1405 of file wasm-interpreter.h.
                                                                      {
    return eh_data_.GetTryBlock(code_offset);
  }
References eh_data_, and v8::internal::wasm::WasmEHData::GetTryBlock().
HasRefOrSimdArgs()
bool v8::internal::wasm::WasmBytecode::HasRefOrSimdArgs (const FunctionSig * sig) [inline], [static]
Definition at line 218 of file wasm-interpreter-inl.h.
                                                                 {
  size_t args_count = static_cast<uint32_t>(sig->parameter_count());
  for (size_t i = 0; i < args_count; i++) {
    ValueKind kind = sig->GetParam(i).kind();
    if (wasm::is_reference(kind) || kind == kS128) return true;
  }
  return false;
}
References v8::internal::wasm::is_reference(), v8::internal::kS128, and v8::internal::sig.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::InitSlotsForFunctionArgs().
InitializeSlots()
bool v8::internal::wasm::WasmBytecode::InitializeSlots (uint8_t * sp, size_t stack_space) const [inline]
Definition at line 312 of file wasm-interpreter-inl.h.
                                                                    {
  // Check for overflow
  if (total_frame_size_in_bytes_ > stack_space) {
    return false;
  }
  uint32_t args_slots_size_in_bytes = args_slots_size() * kSlotSize;
  uint32_t rets_slots_size_in_bytes = rets_slots_size() * kSlotSize;
  uint32_t const_slots_size_in_bytes = this->const_slots_size_in_bytes();
  uint8_t* start_const_area =
      sp + args_slots_size_in_bytes + rets_slots_size_in_bytes;
  // Initialize const slots
  if (const_slots_size_in_bytes) {
    memcpy(start_const_area, const_slots_values_.data(),
           const_slots_size_in_bytes);
  }
  // Initialize local slots
  memset(start_const_area + const_slots_size_in_bytes, 0,
         locals_slots_size() * kSlotSize);
  return true;
}
References v8::internal::wasm::kSlotSize.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
internal_ref_slots_count()
uint32_t v8::internal::wasm::WasmBytecode::internal_ref_slots_count () const [inline]
Definition at line 1387 of file wasm-interpreter.h.
                                                   {
    // Ref slots for arguments and return value are allocated by the caller and
    // not counted in internal_ref_slots_count().
    return ref_slots_count_ - ref_rets_count_ - ref_args_count_;
  }
References ref_args_count_, ref_rets_count_, and ref_slots_count_.
JSToWasmWrapperPackedArraySize()
uint32_t v8::internal::wasm::WasmBytecode::JSToWasmWrapperPackedArraySize (const FunctionSig * sig) [inline], [static]
Definition at line 227 of file wasm-interpreter-inl.h.
                            {
  static_assert(kSystemPointerSize == 8);
  uint32_t args_size = 0;
  size_t args_count = static_cast<uint32_t>(sig->parameter_count());
  for (size_t i = 0; i < args_count; i++) {
    switch (sig->GetParam(i).kind()) {
      case kI32:
      case kF32:
        args_size += sizeof(int32_t);
        break;
      case kI64:
      case kF64:
        args_size += sizeof(int64_t);
        break;
      case kS128:
        args_size += sizeof(Simd128);
        break;
      case kRef:
      case kRefNull:
        // Make sure Ref slots are 64-bit aligned.
        args_size += (args_size & 0x04);
        args_size += sizeof(WasmRef);
        break;
      default:
        UNREACHABLE();
    }
  }
  uint32_t rets_size = 0;
  size_t rets_count = static_cast<uint32_t>(sig->return_count());
  for (size_t i = 0; i < rets_count; i++) {
    switch (sig->GetReturn(i).kind()) {
      case kI32:
      case kF32:
        rets_size += sizeof(int32_t);
        break;
      case kI64:
      case kF64:
        rets_size += sizeof(int64_t);
        break;
      case kS128:
        rets_size += sizeof(Simd128);
        break;
      case kRef:
      case kRefNull:
        // Make sure Ref slots are 64-bit aligned.
        rets_size += (rets_size & 0x04);
        rets_size += sizeof(WasmRef);
        break;
      default:
        UNREACHABLE();
    }
  }
  uint32_t size = std::max(args_size, rets_size);
  // Make sure final size is 64-bit aligned.
  size += (size & 0x04);
  return size;
}
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::kSystemPointerSize, v8::internal::sig, size(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::WasmExportedFunction::New().
local_type()
ValueType v8::internal::wasm::WasmBytecode::local_type (size_t index) const [inline]
Definition at line 130 of file wasm-interpreter-inl.h.
                                                            {
  DCHECK_LT(index, locals_count());
  DCHECK_LT(index, interpreter_code_->locals.num_locals);
  return interpreter_code_->locals.local_types[index];
}
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
locals_count()
uint32_t v8::internal::wasm::WasmBytecode::locals_count () const [inline]
Definition at line 1377 of file wasm-interpreter.h.
{ return locals_count_; }
References locals_count_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
locals_slots_size()
uint32_t v8::internal::wasm::WasmBytecode::locals_slots_size () const [inline]
Definition at line 1378 of file wasm-interpreter.h.
{ return locals_slots_size_; }
References locals_slots_size_.
LocalsSizeInSlots()
uint32_t v8::internal::wasm::WasmBytecode::LocalsSizeInSlots (const InterpreterCode * wasm_code) [inline], [static]
Definition at line 301 of file wasm-interpreter-inl.h.
                                      {
  uint32_t locals_slots_size = 0;
  size_t locals_count = wasm_code->locals.num_locals;
  for (size_t i = 0; i < locals_count; i++) {
    locals_slots_size +=
        GetValueSizeInSlots(wasm_code->locals.local_types[i].kind());
  }
  return locals_slots_size;
}
References v8::internal::wasm::GetValueSizeInSlots(), v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::BodyLocalDecls::local_types, v8::internal::wasm::InterpreterCode::locals, and v8::internal::wasm::BodyLocalDecls::num_locals.
ref_args_count()
uint32_t v8::internal::wasm::WasmBytecode::ref_args_count () const [inline]
Definition at line 1383 of file wasm-interpreter.h.
{ return ref_args_count_; }
References ref_args_count_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), and v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs().
ref_locals_count()
uint32_t v8::internal::wasm::WasmBytecode::ref_locals_count () const [inline]
Definition at line 1385 of file wasm-interpreter.h.
{ return ref_locals_count_; }
References ref_locals_count_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs().
ref_rets_count()
uint32_t v8::internal::wasm::WasmBytecode::ref_rets_count () const [inline]
Definition at line 1384 of file wasm-interpreter.h.
{ return ref_rets_count_; }
References ref_rets_count_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs().
ref_slots_count()
uint32_t v8::internal::wasm::WasmBytecode::ref_slots_count () const [inline]
Definition at line 1386 of file wasm-interpreter.h.
{ return ref_slots_count_; }
References ref_slots_count_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
RefArgsCount()
uint32_t v8::internal::wasm::WasmBytecode::RefArgsCount (const FunctionSig * sig) [inline], [static]
Definition at line 184 of file wasm-interpreter-inl.h.
                                                                 {
  uint32_t refs_args_count = 0;
  size_t args_count = static_cast<uint32_t>(sig->parameter_count());
  for (size_t i = 0; i < args_count; i++) {
    ValueKind kind = sig->GetParam(i).kind();
    if (wasm::is_reference(kind)) refs_args_count++;
  }
  return refs_args_count;
}
References v8::internal::wasm::is_reference(), and v8::internal::sig.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), and v8::internal::WasmExportedFunction::New().
RefLocalsCount()
uint32_t v8::internal::wasm::WasmBytecode::RefLocalsCount (const InterpreterCode * wasm_code) [inline], [static]
Definition at line 289 of file wasm-interpreter-inl.h.
                                                                             {
  uint32_t refs_locals_count = 0;
  size_t locals_count = wasm_code->locals.num_locals;
  for (size_t i = 0; i < locals_count; i++) {
    ValueKind kind = wasm_code->locals.local_types[i].kind();
    if (wasm::is_reference(kind)) {
      refs_locals_count++;
    }
  }
  return refs_locals_count;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::is_reference(), v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::BodyLocalDecls::local_types, v8::internal::wasm::InterpreterCode::locals, and v8::internal::wasm::BodyLocalDecls::num_locals.
RefRetsCount()
uint32_t v8::internal::wasm::WasmBytecode::RefRetsCount (const FunctionSig * sig) [inline], [static]
Definition at line 194 of file wasm-interpreter-inl.h.
                                                                 {
  uint32_t refs_rets_count = 0;
  size_t return_count = static_cast<uint32_t>(sig->return_count());
  for (size_t i = 0; i < return_count; i++) {
    ValueKind kind = sig->GetReturn(i).kind();
    if (wasm::is_reference(kind)) refs_rets_count++;
  }
  return refs_rets_count;
}
References v8::internal::wasm::is_reference(), and v8::internal::sig.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::WasmExportedFunction::New(), and v8::internal::wasm::WasmInterpreterRuntime::StoreRefArgsIntoStackSlots().
rets_slots_size()
uint32_t v8::internal::wasm::WasmBytecode::rets_slots_size () const [inline]
Definition at line 1376 of file wasm-interpreter.h.
{ return rets_slots_size_; }
References rets_slots_size_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
RetsSizeInSlots()
uint32_t v8::internal::wasm::WasmBytecode::RetsSizeInSlots (const FunctionSig * sig) [inline], [static]
Definition at line 175 of file wasm-interpreter-inl.h.
                                                                    {
  uint32_t rets_slots_size = 0;
  size_t return_count = static_cast<uint32_t>(sig->return_count());
  for (size_t i = 0; i < return_count; i++) {
    rets_slots_size += GetValueSizeInSlots(sig->GetReturn(i).kind());
  }
  return rets_slots_size;
}
References v8::internal::wasm::GetValueSizeInSlots(), and v8::internal::sig.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmInterpreterRuntime::StoreRefArgsIntoStackSlots(), and v8::internal::wasm::WasmBytecodeGenerator::WasmBytecodeGenerator().
return_count()
uint32_t v8::internal::wasm::WasmBytecode::return_count () const [inline]
Definition at line 1375 of file wasm-interpreter.h.
{ return return_count_; }
References return_count_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), and v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction().
return_type()
ValueType v8::internal::wasm::WasmBytecode::return_type (size_t index) const [inline]
Definition at line 120 of file wasm-interpreter-inl.h.
                                                             {
  DCHECK_LT(index, return_count());
  return signature_->GetReturn(index);
}
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction().
Member Data Documentation
args_count_
uint32_t v8::internal::wasm::WasmBytecode::args_count_ [private]
Definition at line 1431 of file wasm-interpreter.h.
Referenced by args_count().
args_slots_size_
uint32_t v8::internal::wasm::WasmBytecode::args_slots_size_ [private]
Definition at line 1432 of file wasm-interpreter.h.
Referenced by args_slots_size().
blocks_count_
uint32_t v8::internal::wasm::WasmBytecode::blocks_count_ [private]
Definition at line 1430 of file wasm-interpreter.h.
Referenced by GetBlocksCount().
canonical_signature_
const CanonicalSig* v8::internal::wasm::WasmBytecode::canonical_signature_ [private]
Definition at line 1425 of file wasm-interpreter.h.
Referenced by GetCanonicalFunctionSignature().
code_
std::vector<uint8_t> v8::internal::wasm::WasmBytecode::code_ [private]
Definition at line 1422 of file wasm-interpreter.h.
Referenced by GetCodeSize().
code_bytes_
const uint8_t* v8::internal::wasm::WasmBytecode::code_bytes_ [private]
Definition at line 1423 of file wasm-interpreter.h.
Referenced by GetCode(), and GetPcFromTrapCode().
code_pc_map_
std::map<CodeOffset, pc_t> v8::internal::wasm::WasmBytecode::code_pc_map_ [private]
Definition at line 1446 of file wasm-interpreter.h.
Referenced by GetPcFromTrapCode().
const_slots_values_
std::vector<uint8_t> v8::internal::wasm::WasmBytecode::const_slots_values_ [private]
Definition at line 1427 of file wasm-interpreter.h.
Referenced by const_slots_size_in_bytes().
eh_data_
WasmEHData v8::internal::wasm::WasmBytecode::eh_data_ [private]
Definition at line 1443 of file wasm-interpreter.h.
Referenced by GetCaughtException(), GetExceptionPayloadStartSlotOffsets(), GetParentTryBlock(), and GetTryBlock().
func_index_
int v8::internal::wasm::WasmBytecode::func_index_ [private]
Definition at line 1429 of file wasm-interpreter.h.
Referenced by GetFunctionIndex().
interpreter_code_
const InterpreterCode* v8::internal::wasm::WasmBytecode::interpreter_code_ [private]
Definition at line 1426 of file wasm-interpreter.h.
locals_count_
uint32_t v8::internal::wasm::WasmBytecode::locals_count_ [private]
Definition at line 1435 of file wasm-interpreter.h.
Referenced by locals_count().
locals_slots_size_
uint32_t v8::internal::wasm::WasmBytecode::locals_slots_size_ [private]
Definition at line 1436 of file wasm-interpreter.h.
Referenced by locals_slots_size().
ref_args_count_
uint32_t v8::internal::wasm::WasmBytecode::ref_args_count_ [private]
Definition at line 1438 of file wasm-interpreter.h.
Referenced by internal_ref_slots_count(), and ref_args_count().
ref_locals_count_
uint32_t v8::internal::wasm::WasmBytecode::ref_locals_count_ [private]
Definition at line 1440 of file wasm-interpreter.h.
Referenced by ref_locals_count().
ref_rets_count_
uint32_t v8::internal::wasm::WasmBytecode::ref_rets_count_ [private]
Definition at line 1439 of file wasm-interpreter.h.
Referenced by internal_ref_slots_count(), and ref_rets_count().
ref_slots_count_
uint32_t v8::internal::wasm::WasmBytecode::ref_slots_count_ [private]
Definition at line 1441 of file wasm-interpreter.h.
Referenced by internal_ref_slots_count(), and ref_slots_count().
rets_slots_size_
uint32_t v8::internal::wasm::WasmBytecode::rets_slots_size_ [private]
Definition at line 1434 of file wasm-interpreter.h.
Referenced by rets_slots_size().
return_count_
uint32_t v8::internal::wasm::WasmBytecode::return_count_ [private]
Definition at line 1433 of file wasm-interpreter.h.
Referenced by return_count().
signature_
const FunctionSig* v8::internal::wasm::WasmBytecode::signature_ [private]
Definition at line 1424 of file wasm-interpreter.h.
Referenced by GetFunctionSignature().
total_frame_size_in_bytes_
uint32_t v8::internal::wasm::WasmBytecode::total_frame_size_in_bytes_ [private]
Definition at line 1437 of file wasm-interpreter.h.
Referenced by frame_size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc