v8::internal::LookupIterator Class Reference
#include <lookup.h>
Public Types
enum Configuration {
kInterceptor = 1 << 0
, kPrototypeChain = 1 << 1
, OWN_SKIP_INTERCEPTOR = 0
, OWN = kInterceptor
,
PROTOTYPE_CHAIN_SKIP_INTERCEPTOR = kPrototypeChain
, PROTOTYPE_CHAIN = kPrototypeChain | kInterceptor
, DEFAULT = PROTOTYPE_CHAIN
 }
enum State {
NOT_FOUND
, STRING_LOOKUP_START_OBJECT
, TYPED_ARRAY_INDEX_NOT_FOUND
, ACCESS_CHECK
,
INTERCEPTOR
, JSPROXY
, ACCESSOR
, DATA
,
WASM_OBJECT
, TRANSITION
, BEFORE_PROPERTY = INTERCEPTOR
 }
Public Member Functions
LookupIterator (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name, Configuration configuration=DEFAULT)
LookupIterator (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name, DirectHandle< JSAny > lookup_start_object, Configuration configuration=DEFAULT)
LookupIterator (Isolate *isolate, DirectHandle< JSAny > receiver, size_t index, Configuration configuration=DEFAULT)
LookupIterator (Isolate *isolate, DirectHandle< JSAny > receiver, size_t index, DirectHandle< JSAny > lookup_start_object, Configuration configuration=DEFAULT)
LookupIterator (Isolate *isolate, DirectHandle< JSAny > receiver, const PropertyKey &key, Configuration configuration=DEFAULT)
LookupIterator (Isolate *isolate, DirectHandle< JSAny > receiver, const PropertyKey &key, DirectHandle< JSAny > lookup_start_object, Configuration configuration=DEFAULT)
LookupIterator (Isolate *isolate, Configuration configuration, DirectHandle< JSAny > receiver, DirectHandle< Symbol > name)
void Restart ()
void RecheckTypedArrayBounds ()
Isolate * isolate () const
State state () const
DirectHandle< Name > name () const
DirectHandle< Name > GetName ()
size_t index () const
uint32_t array_index () const
PropertyKey GetKey () const
bool IsElement () const
bool IsElement (Tagged< JSReceiver > object) const
bool IsPrivateName () const
bool IsFound () const
void Next ()
void NotFound ()
Heap * heap () const
Factory * factory () const
DirectHandle< JSAny > GetReceiver () const
template<class T >
DirectHandle< T > GetStoreTarget () const
bool is_dictionary_holder () const
DirectHandle< Map > transition_map () const
DirectHandle< PropertyCell > transition_cell () const
template<class T >
DirectHandle< T > GetHolder () const
DirectHandle< JSAny > lookup_start_object () const
bool HolderIsReceiver () const
bool HolderIsReceiverOrHiddenPrototype () const
bool check_prototype_chain () const
bool HasAccess () const
bool ExtendingNonExtensible (DirectHandle< JSReceiver > receiver)
void PrepareForDataProperty (DirectHandle< Object > value)
void PrepareTransitionToDataProperty (DirectHandle< JSReceiver > receiver, DirectHandle< Object > value, PropertyAttributes attributes, StoreOrigin store_origin)
bool IsCacheableTransition ()
void ApplyTransitionToDataProperty (DirectHandle< JSReceiver > receiver)
void ReconfigureDataProperty (DirectHandle< Object > value, PropertyAttributes attributes)
void Delete ()
void TransitionToAccessorProperty (DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes)
void TransitionToAccessorPair (DirectHandle< Object > pair, PropertyAttributes attributes)
PropertyDetails property_details () const
PropertyAttributes property_attributes () const
bool IsConfigurable () const
bool IsReadOnly () const
bool IsEnumerable () const
Representation representation () const
PropertyLocation location () const
PropertyConstness constness () const
FieldIndex GetFieldIndex () const
int GetFieldDescriptorIndex () const
int GetAccessorIndex () const
DirectHandle< PropertyCell > GetPropertyCell () const
DirectHandle< Object > GetAccessors () const
DirectHandle< InterceptorInfo > GetInterceptor () const
DirectHandle< InterceptorInfo > GetInterceptorForFailedAccessCheck () const
Handle< Object > GetStringPropertyValue (AllocationPolicy allocation_policy=AllocationPolicy::kAllocationAllowed) const
Handle< Object > GetDataValue (AllocationPolicy allocation_policy=AllocationPolicy::kAllocationAllowed) const
void WriteDataValue (DirectHandle< Object > value, bool initializing_store)
DirectHandle< Object > GetDataValue (SeqCstAccessTag tag) const
void WriteDataValue (DirectHandle< Object > value, SeqCstAccessTag tag)
DirectHandle< Object > SwapDataValue (DirectHandle< Object > value, SeqCstAccessTag tag)
DirectHandle< Object > CompareAndSwapDataValue (DirectHandle< Object > expected, DirectHandle< Object > value, SeqCstAccessTag tag)
void UpdateProtector ()
bool TryLookupCachedProperty (DirectHandle< AccessorPair > accessor)
bool TryLookupCachedProperty ()
template<bool is_element>
void Start ()
Static Public Member Functions
static void UpdateProtector (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name)
static bool HasInternalMarkerProperty (Isolate *isolate, Tagged< JSReceiver > object, DirectHandle< Symbol > marker)
Private Types
enum class InterceptorState { kUninitialized
, kSkipNonMasking
, kProcessNonMasking
 }
Private Member Functions
bool LookupCachedProperty (DirectHandle< AccessorPair > accessor)
LookupIterator (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name, size_t index, DirectHandle< JSAny > lookup_start_object, Configuration configuration)
LookupIterator (Isolate *isolate, Configuration configuration, DirectHandle< JSAny > receiver, DirectHandle< Symbol > name, DirectHandle< JSAny > lookup_start_object)
DirectHandle< Map > GetReceiverMap () const
V8_WARN_UNUSED_RESULT Tagged< JSReceiver > NextHolder (Tagged< Map > map)
bool is_js_array_element (bool is_element) const
template<bool is_element>
V8_EXPORT_PRIVATE void Start ()
template<bool is_element>
void NextInternal (Tagged< Map > map, Tagged< JSReceiver > holder)
template<bool is_element>
State LookupInHolder (Tagged< Map > map, Tagged< JSReceiver > holder)
template<bool is_element>
State LookupInRegularHolder (Tagged< Map > map, Tagged< JSReceiver > holder)
template<bool is_element>
State LookupInSpecialHolder (Tagged< Map > map, Tagged< JSReceiver > holder)
template<bool is_element>
void RestartLookupForNonMaskingInterceptors ()
template<bool is_element>
void RestartInternal (InterceptorState interceptor_state)
DirectHandle< Object > FetchValue (AllocationPolicy allocation_policy=AllocationPolicy::kAllocationAllowed) const
bool CanStayConst (Tagged< Object > value) const
bool DictCanStayConst (Tagged< Object > value) const
template<bool is_element>
void ReloadPropertyInformation ()
template<bool is_element>
bool SkipInterceptor (Tagged< JSObject > holder)
template<bool is_element>
Tagged< InterceptorInfo > GetInterceptor (Tagged< JSObject > holder) const
bool check_interceptor () const
InternalIndex descriptor_number () const
InternalIndex dictionary_entry () const
Tagged< JSReceiver > GetRootForNonJSReceiver () const
State NotFound (Tagged< JSReceiver > const holder) const
Static Private Member Functions
static void InternalUpdateProtector (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name)
static Configuration ComputeConfiguration (Isolate *isolate, Configuration configuration, DirectHandle< Name > name)
Private Attributes
friend PropertyKey
const Configuration configuration_
State state_ = NOT_FOUND
bool has_property_ = false
InterceptorState interceptor_state_ = InterceptorState::kUninitialized
PropertyDetails property_details_ = PropertyDetails::Empty()
Isolate *const isolate_
DirectHandle< Name > name_
DirectHandle< UnionOf< Map, PropertyCell > > transition_
const DirectHandle< JSAny > receiver_
DirectHandle< JSReceiver > holder_
const DirectHandle< JSAny > lookup_start_object_
const size_t index_
InternalIndex number_ = InternalIndex::NotFound()
Static Private Attributes
static const size_t kInvalidIndex = std::numeric_limits<size_t>::max()
Detailed Description
Definition at line 53 of file lookup.h.
Member Enumeration Documentation
Configuration
enum v8::internal::LookupIterator::Configuration
Enumerator
kInterceptor
kPrototypeChain
OWN_SKIP_INTERCEPTOR
OWN
PROTOTYPE_CHAIN_SKIP_INTERCEPTOR
PROTOTYPE_CHAIN
DEFAULT
Definition at line 55 of file lookup.h.
                     {
    // Configuration bits.
    kInterceptor = 1 << 0,
    kPrototypeChain = 1 << 1,
    // Convenience combinations of bits.
    OWN_SKIP_INTERCEPTOR = 0,
    OWN = kInterceptor,
    PROTOTYPE_CHAIN_SKIP_INTERCEPTOR = kPrototypeChain,
    PROTOTYPE_CHAIN = kPrototypeChain | kInterceptor,
    DEFAULT = PROTOTYPE_CHAIN
  };
InterceptorState
enum v8::internal::LookupIterator::InterceptorState [strong], [private]
Enumerator
kUninitialized
kSkipNonMasking
kProcessNonMasking
Definition at line 300 of file lookup.h.
                              {
    kUninitialized,
    kSkipNonMasking,
    kProcessNonMasking
  };
State
enum v8::internal::LookupIterator::State
Enumerator
NOT_FOUND
STRING_LOOKUP_START_OBJECT
TYPED_ARRAY_INDEX_NOT_FOUND
ACCESS_CHECK
INTERCEPTOR
JSPROXY
ACCESSOR
DATA
WASM_OBJECT
TRANSITION
BEFORE_PROPERTY
Definition at line 68 of file lookup.h.
             {
    // The property was not found by the iterator (this is a terminal state,
    // iteration should not continue after hitting a not-found state).
    NOT_FOUND,
    // This is an initial state of a lookup starting from primitive String.
    // This case requires special handling since String is not a JSReceiver
    // and we don't want to create a wrapper object just for this case.
    STRING_LOOKUP_START_OBJECT,
    // Typed arrays have special handling for "canonical numeric index string"
    // (https://tc39.es/ecma262/#sec-canonicalnumericindexstring), where not
    // finding such an index (either because of OOB, or because it's not a valid
    // integer index) immediately returns undefined, without walking the
    // prototype (https://tc39.es/ecma262/#sec-typedarray-get).
    TYPED_ARRAY_INDEX_NOT_FOUND,
    // The next lookup requires an access check -- we can continue iteration on
    // a successful check, otherwise we should abort.
    ACCESS_CHECK,
    // Interceptors are API-level hooks for optionally handling a lookup in
    // embedder code -- if their handling returns false, then we should continue
    // the iteration, though we should be conscious that an interceptor may have
    // side effects despite returning false and might invalidate the lookup
    // iterator state.
    INTERCEPTOR,
    // Proxies are user-space hooks for handling lookups in JS code.
    // https://tc39.es/ecma262/#proxy-exotic-object
    JSPROXY,
    // Accessors are hooks for property getters/setters -- these can be
    // user-space accessors (AccessorPair), or API accessors (AccessorInfo).
    ACCESSOR,
    // Data properties are stored as data fields on an object (either properties
    // or elements).
    DATA,
    // WasmGC objects are opaque in JS, and appear to have no properties.
    WASM_OBJECT,
    // A LookupIterator in the transition state is in the middle of performing
    // a data transition (that is, as part of a data property write, updating
    // the receiver and its map to allow the write).
    //
    // This state is not expected to be observed while performing a lookup.
    TRANSITION,
    // Set state_ to BEFORE_PROPERTY to ensure that the next lookup will be a
    // PROPERTY lookup.
    BEFORE_PROPERTY = INTERCEPTOR
  };
Constructor & Destructor Documentation
LookupIterator() [1/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name, Configuration configuration = DEFAULT) [inline]
Definition at line 26 of file lookup-inl.h.
    : LookupIterator(isolate, receiver, name, kInvalidIndex, receiver,
                     configuration) {}
LookupIterator() [2/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name, DirectHandle< JSAny > lookup_start_object, Configuration configuration = DEFAULT) [inline]
Definition at line 32 of file lookup-inl.h.
    : LookupIterator(isolate, receiver, name, kInvalidIndex,
                     Cast<JSAny>(lookup_start_object), configuration) {}
LookupIterator() [3/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, DirectHandle< JSAny > receiver, size_t index, Configuration configuration = DEFAULT) [inline]
Definition at line 39 of file lookup-inl.h.
    : LookupIterator(isolate, receiver, DirectHandle<Name>(), index, receiver,
                     configuration) {
  DCHECK_NE(index, kInvalidIndex);
}
References DCHECK_NE, index(), and kInvalidIndex.
LookupIterator() [4/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, DirectHandle< JSAny > receiver, size_t index, DirectHandle< JSAny > lookup_start_object, Configuration configuration = DEFAULT) [inline]
Definition at line 46 of file lookup-inl.h.
    : LookupIterator(isolate, receiver, DirectHandle<Name>(), index,
                     Cast<JSAny>(lookup_start_object), configuration) {
  DCHECK_NE(index, kInvalidIndex);
}
References DCHECK_NE, index(), and kInvalidIndex.
LookupIterator() [5/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, DirectHandle< JSAny > receiver, const PropertyKey & key, Configuration configuration = DEFAULT) [inline]
Definition at line 55 of file lookup-inl.h.
    : LookupIterator(isolate, receiver, key.name(), key.index(), receiver,
                     configuration) {}
LookupIterator() [6/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, DirectHandle< JSAny > receiver, const PropertyKey & key, DirectHandle< JSAny > lookup_start_object, Configuration configuration = DEFAULT) [inline]
Definition at line 61 of file lookup-inl.h.
    : LookupIterator(isolate, receiver, key.name(), key.index(),
                     Cast<JSAny>(lookup_start_object), configuration) {}
LookupIterator() [7/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, Configuration configuration, DirectHandle< JSAny > receiver, DirectHandle< Symbol > name) [inline]
Definition at line 118 of file lookup-inl.h.
    : configuration_(configuration),
      isolate_(isolate),
      name_(name),
      receiver_(receiver),
      lookup_start_object_(receiver),
      index_(kInvalidIndex) {
  // This is the only lookup configuration allowed by this constructor because
  // it's special case allowing lookup of the private symbols on the prototype
  // chain. Usually private symbols are limited to OWN_SKIP_INTERCEPTOR lookups.
  DCHECK(*name_ == *isolate->factory()->error_stack_symbol() ||
         *name_ == *isolate->factory()->error_message_symbol());
  DCHECK_EQ(configuration, PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
  Start<false>();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), isolate(), name_, and PROTOTYPE_CHAIN_SKIP_INTERCEPTOR.
LookupIterator() [8/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name, size_t index, DirectHandle< JSAny > lookup_start_object, Configuration configuration) [inline], [private]
Definition at line 70 of file lookup-inl.h.
    : configuration_(ComputeConfiguration(isolate, configuration, name)),
      isolate_(isolate),
      name_(name),
      receiver_(receiver),
      lookup_start_object_(lookup_start_object),
      index_(index) {
  if (IsElement()) {
    // If we're not looking at a TypedArray, we will need the key represented
    // as an internalized string.
    if (index_ > JSObject::kMaxElementIndex &&
        !IsJSTypedArray(*lookup_start_object, isolate_)
#if V8_ENABLE_WEBASSEMBLY
        && !IsWasmArray(*lookup_start_object, isolate_)
#endif // V8_ENABLE_WEBASSEMBLY
    ) {
      if (name_.is_null()) {
        name_ = isolate->factory()->SizeToString(index_);
      }
      name_ = isolate->factory()->InternalizeName(name_);
    } else if (!name_.is_null() && !IsInternalizedString(*name_)) {
      // Maintain the invariant that if name_ is present, it is internalized.
      name_ = DirectHandle<Name>();
    }
    Start<true>();
  } else {
    DCHECK(!name_.is_null());
    name_ = isolate->factory()->InternalizeName(name_);
#ifdef DEBUG
    // Assert that the name is not an index.
    // If we're not looking at the prototype chain and the lookup start object
    // is not a typed array, then this means "array index", otherwise we need to
    // ensure the full generality so that typed arrays are handled correctly.
    if (!check_prototype_chain() && !IsJSTypedArray(*lookup_start_object)) {
      uint32_t array_index;
      DCHECK(!name_->AsArrayIndex(&array_index));
    } else {
      size_t integer_index;
      DCHECK(!name_->AsIntegerIndex(&integer_index));
    }
#endif // DEBUG
    Start<false>();
  }
}
References array_index(), check_prototype_chain(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), index_, IsElement(), v8::internal::InstanceTypeChecker::IsInternalizedString(), isolate(), isolate_, v8::internal::JSObject::kMaxElementIndex, lookup_start_object(), name_, and v8::internal::Factory::SizeToString().
LookupIterator() [9/9]
v8::internal::LookupIterator::LookupIterator (Isolate * isolate, Configuration configuration, DirectHandle< JSAny > receiver, DirectHandle< Symbol > name, DirectHandle< JSAny > lookup_start_object) [inline], [private]
Member Function Documentation
ApplyTransitionToDataProperty()
void v8::internal::LookupIterator::ApplyTransitionToDataProperty (DirectHandle< JSReceiver > receiver)
Definition at line 658 of file lookup.cc.
                                       {
  DCHECK_EQ(TRANSITION, state_);
  DCHECK_IMPLIES(!receiver.is_identical_to(GetStoreTarget<JSReceiver>()),
                 name()->IsPrivateName());
  holder_ = receiver;
  if (IsJSGlobalObject(*receiver, isolate_)) {
    JSObject::InvalidatePrototypeChains(receiver->map(isolate_));
    // Install a property cell.
    auto global = Cast<JSGlobalObject>(receiver);
    DCHECK(!global->HasFastProperties());
    DirectHandle<GlobalDictionary> dictionary(
        global->global_dictionary(isolate_, kAcquireLoad), isolate_);
    dictionary =
        GlobalDictionary::Add(isolate_, dictionary, name(), transition_cell(),
                              property_details_, &number_);
    global->set_global_dictionary(*dictionary, kReleaseStore);
    // Reload details containing proper enumeration index value.
    property_details_ = transition_cell()->property_details();
    has_property_ = true;
    state_ = DATA;
    return;
  }
  DirectHandle<Map> transition = transition_map();
  bool simple_transition =
      transition->GetBackPointer(isolate_) == receiver->map(isolate_);
  if (configuration_ == DEFAULT && !transition->is_dictionary_map() &&
      !transition->is_prototype_map() &&
      !transition->IsPrototypeValidityCellValid()) {
    // Only LookupIterator instances with DEFAULT (full prototype chain)
    // configuration can produce valid transition handler maps.
    // Note that it doesn't make sense to prepare a fast property transition
    // handler for prototype maps because they are not going to be reused
    // anyway.
    DirectHandle<UnionOf<Smi, Cell>> validity_cell =
        Map::GetOrCreatePrototypeChainValidityCell(transition, isolate());
    transition->set_prototype_validity_cell(*validity_cell, kRelaxedStore);
  }
  if (!IsJSProxy(*receiver, isolate_)) {
    JSObject::MigrateToMap(isolate_, Cast<JSObject>(receiver), transition);
  }
  if (simple_transition) {
    number_ = transition->LastAdded();
    property_details_ = transition->GetLastDescriptorDetails(isolate_);
    state_ = DATA;
  } else if (receiver->map(isolate_)->is_dictionary_map()) {
    if (receiver->map(isolate_)->is_prototype_map() &&
        IsJSObject(*receiver, isolate_)) {
      JSObject::InvalidatePrototypeChains(receiver->map(isolate_));
    }
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      DirectHandle<SwissNameDictionary> dictionary(
          receiver->property_dictionary_swiss(isolate_), isolate_);
      dictionary =
          SwissNameDictionary::Add(isolate(), dictionary, name(),
                                   isolate_->factory()->uninitialized_value(),
                                   property_details_, &number_);
      receiver->SetProperties(*dictionary);
    } else {
      DirectHandle<NameDictionary> dictionary(
          receiver->property_dictionary(isolate_), isolate_);
      dictionary =
          NameDictionary::Add(isolate(), dictionary, name(),
                              isolate_->factory()->uninitialized_value(),
                              property_details_, &number_);
      receiver->SetProperties(*dictionary);
      // TODO(pthier): Add flags to swiss dictionaries.
      if (name()->IsInteresting(isolate())) {
        dictionary->set_may_have_interesting_properties(true);
      }
      // Reload details containing proper enumeration index value.
      property_details_ = dictionary->DetailsAt(number_);
    }
    has_property_ = true;
    state_ = DATA;
  } else {
    ReloadPropertyInformation<false>();
  }
}
References v8::bigint::Add(), configuration_, DATA, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DEFAULT, v8::internal::Isolate::factory(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), has_property_, holder_, v8::internal::JSObject::InvalidatePrototypeChains(), v8::internal::DirectHandle< T >::is_identical_to(), isolate(), isolate_, IsPrivateName(), v8::kAcquireLoad, v8::kRelaxedStore, v8::kReleaseStore, v8::internal::JSObject::MigrateToMap(), name(), number_, property_details_, state_, TRANSITION, transition_cell(), transition_map(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::Object::TransitionAndWriteDataProperty().
array_index()
uint32_t v8::internal::LookupIterator::array_index () const [inline]
Definition at line 161 of file lookup.h.
                               {
    DCHECK_LE(index_, JSArray::kMaxArrayIndex);
    return static_cast<uint32_t>(index_);
  }
References DCHECK_LE, v8::internal::PropertyKey::index_, and v8::internal::JSArray::kMaxArrayIndex.
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), LookupIterator(), v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), and TransitionToAccessorPair().
CanStayConst()
bool v8::internal::LookupIterator::CanStayConst (Tagged< Object > value) const [private]
Definition at line 957 of file lookup.cc.
                                                            {
  DCHECK(!holder_.is_null());
  DCHECK(!IsElement(*holder_));
  DCHECK(holder_->HasFastProperties(isolate_));
  DCHECK_EQ(PropertyLocation::kField, property_details_.location());
  DCHECK_EQ(PropertyConstness::kConst, property_details_.constness());
  if (IsUninitialized(value, isolate())) {
    // Storing uninitialized value means that we are preparing for a computed
    // property value in an object literal. The initializing store will follow
    // and it will properly update constness based on the actual value.
    return true;
  }
  DirectHandle<JSObject> holder = GetHolder<JSObject>();
  FieldIndex field_index =
      FieldIndex::ForDetails(holder->map(isolate_), property_details_);
  if (property_details_.representation().IsDouble()) {
    if (!IsNumber(value, isolate_)) return false;
    uint64_t bits;
    Tagged<Object> current_value =
        holder->RawFastPropertyAt(isolate_, field_index);
    DCHECK(IsHeapNumber(current_value, isolate_));
    bits = Cast<HeapNumber>(current_value)->value_as_bits();
    // Use bit representation of double to check for hole double, since
    // manipulating the signaling NaN used for the hole in C++, e.g. with
    // base::bit_cast or value(), will change its value on ia32 (the x87
    // stack is used to return values and stores to the stack silently clear the
    // signalling bit).
    // Only allow initializing stores to double to stay constant.
    return bits == kHoleNanInt64;
  }
  Tagged<Object> current_value =
      holder->RawFastPropertyAt(isolate_, field_index);
  return IsUninitialized(current_value, isolate());
}
References v8::internal::PropertyDetails::constness(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FieldIndex::ForDetails(), holder_, v8::internal::Representation::IsDouble(), IsElement(), v8::internal::IsNumber(), isolate(), isolate_, v8::internal::kConst, v8::internal::kField, v8::internal::kHoleNanInt64, v8::internal::PropertyDetails::location(), property_details_, v8::internal::PropertyDetails::representation(), and v8::internal::value.
Referenced by PrepareForDataProperty(), and WriteDataValue().
check_interceptor()
bool v8::internal::LookupIterator::check_interceptor () const [inline], [private]
Definition at line 347 of file lookup.h.
                                 {
    return (configuration_ & kInterceptor) != 0;
  }
Referenced by LookupInSpecialHolder().
check_prototype_chain()
bool v8::internal::LookupIterator::check_prototype_chain () const [inline]
Definition at line 205 of file lookup.h.
                                     {
    return (configuration_ & kPrototypeChain) != 0;
  }
Referenced by GetRootForNonJSReceiver(), HolderIsReceiver(), HolderIsReceiverOrHiddenPrototype(), LookupIterator(), NextHolder(), and Start().
CompareAndSwapDataValue()
DirectHandle< Object > v8::internal::LookupIterator::CompareAndSwapDataValue (DirectHandle< Object > expected, DirectHandle< Object > value, SeqCstAccessTag tag)
Definition at line 1206 of file lookup.cc.
                         {
  DCHECK_EQ(DATA, state_);
  // Currently only shared structs and arrays support sequentially consistent
  // access.
  DCHECK(IsJSSharedStruct(*holder_, isolate_) ||
         IsJSSharedArray(*holder_, isolate_));
  DisallowGarbageCollection no_gc;
  DirectHandle<JSObject> holder = GetHolder<JSObject>();
  if (IsElement(*holder)) {
    ElementsAccessor* accessor = holder->GetElementsAccessor(isolate_);
    return accessor->CompareAndSwapAtomic(isolate_, holder, number_, *expected,
                                          *value, kSeqCstAccess);
  }
  DCHECK_EQ(PropertyLocation::kField, property_details_.location());
  DCHECK_EQ(PropertyKind::kData, property_details_.kind());
  FieldIndex field_index =
      FieldIndex::ForDescriptor(holder->map(isolate_), descriptor_number());
  return direct_handle(holder->RawFastPropertyAtCompareAndSwap(
                           field_index, *expected, *value, tag),
                       isolate_);
}
References v8::internal::ElementsAccessor::CompareAndSwapAtomic(), DATA, v8::internal::DCHECK(), DCHECK_EQ, descriptor_number(), v8::internal::direct_handle(), v8::internal::FieldIndex::ForDescriptor(), holder_, IsElement(), isolate_, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::kSeqCstAccess, v8::internal::PropertyDetails::location(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, number_, property_details_, state_, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
ComputeConfiguration()
LookupIterator::Configuration v8::internal::LookupIterator::ComputeConfiguration (Isolate * isolate, Configuration configuration, DirectHandle< Name > name) [inline], [static], [private]
Definition at line 380 of file lookup-inl.h.
                                                                            {
  return (!name.is_null() && name->IsPrivate()) ? OWN_SKIP_INTERCEPTOR
                                                : configuration;
}
References name(), and OWN_SKIP_INTERCEPTOR.
constness()
PropertyConstness v8::internal::LookupIterator::constness () const [inline]
Definition at line 243 of file lookup.h.
{ return property_details().constness(); }
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), PrepareForDataProperty(), and v8::internal::RUNTIME_FUNCTION().
Delete()
void v8::internal::LookupIterator::Delete ()
Definition at line 748 of file lookup.cc.
                            {
  DirectHandle<JSReceiver> holder = Cast<JSReceiver>(holder_);
  if (IsElement(*holder)) {
    DirectHandle<JSObject> object = Cast<JSObject>(holder);
    ElementsAccessor* accessor = object->GetElementsAccessor(isolate_);
    accessor->Delete(isolate_, object, number_);
  } else {
    DCHECK(!name()->IsPrivateName());
    bool is_prototype_map = holder->map(isolate_)->is_prototype_map();
    RCS_SCOPE(isolate_,
              is_prototype_map
                  ? RuntimeCallCounterId::kPrototypeObject_DeleteProperty
                  : RuntimeCallCounterId::kObject_DeleteProperty);
    PropertyNormalizationMode mode =
        is_prototype_map ? KEEP_INOBJECT_PROPERTIES : CLEAR_INOBJECT_PROPERTIES;
    if (holder->HasFastProperties(isolate_)) {
      JSObject::NormalizeProperties(isolate_, Cast<JSObject>(holder), mode, 0,
                                    "DeletingProperty");
      ReloadPropertyInformation<false>();
    }
    JSReceiver::DeleteNormalizedProperty(holder, dictionary_entry());
    if (IsJSObject(*holder, isolate_)) {
      JSObject::ReoptimizeIfPrototype(Cast<JSObject>(holder));
    }
  }
  state_ = NOT_FOUND;
}
References v8::internal::CLEAR_INOBJECT_PROPERTIES, v8::internal::DCHECK(), v8::internal::ElementsAccessor::Delete(), v8::internal::JSReceiver::DeleteNormalizedProperty(), dictionary_entry(), holder_, v8::internal::is_prototype_map, IsElement(), isolate_, IsPrivateName(), v8::internal::KEEP_INOBJECT_PROPERTIES, mode(), name(), v8::internal::JSObject::NormalizeProperties(), NOT_FOUND, number_, RCS_SCOPE, v8::internal::JSObject::ReoptimizeIfPrototype(), and state_.
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal(), and v8::internal::JSReceiver::DeleteProperty().
descriptor_number()
InternalIndex v8::internal::LookupIterator::descriptor_number () const [inline], [private]
Definition at line 363 of file lookup-inl.h.
                                                      {
  DCHECK(!holder_.is_null());
  DCHECK(!IsElement(*holder_));
  DCHECK(has_property_);
  DCHECK(holder_->HasFastProperties(isolate_));
  return number_;
}
References v8::internal::DCHECK(), has_property_, holder_, IsElement(), isolate_, and number_.
Referenced by CompareAndSwapDataValue(), FetchValue(), GetAccessorIndex(), GetFieldDescriptorIndex(), PrepareForDataProperty(), ReconfigureDataProperty(), SwapDataValue(), and WriteDataValue().
DictCanStayConst()
bool v8::internal::LookupIterator::DictCanStayConst (Tagged< Object > value) const [private]
Definition at line 993 of file lookup.cc.
                                                                {
  DCHECK(!holder_.is_null());
  DCHECK(!IsElement(*holder_));
  DCHECK(!holder_->HasFastProperties(isolate_));
  DCHECK(!IsJSGlobalObject(*holder_));
  DCHECK(!IsJSProxy(*holder_));
  DCHECK_EQ(PropertyConstness::kConst, property_details_.constness());
  DisallowHeapAllocation no_gc;
  if (IsUninitialized(value, isolate())) {
    // Storing uninitialized value means that we are preparing for a computed
    // property value in an object literal. The initializing store will follow
    // and it will properly update constness based on the actual value.
    return true;
  }
  DirectHandle<JSReceiver> holder = GetHolder<JSReceiver>();
  Tagged<Object> current_value;
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    Tagged<SwissNameDictionary> dict = holder->property_dictionary_swiss();
    current_value = dict->ValueAt(dictionary_entry());
  } else {
    Tagged<NameDictionary> dict = holder->property_dictionary();
    current_value = dict->ValueAt(dictionary_entry());
  }
  return IsUninitialized(current_value, isolate());
}
References v8::internal::PropertyDetails::constness(), v8::internal::DCHECK(), DCHECK_EQ, dictionary_entry(), holder_, IsElement(), isolate(), isolate_, v8::internal::kConst, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, property_details_, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by PrepareForDataProperty(), and WriteDataValue().
dictionary_entry()
InternalIndex v8::internal::LookupIterator::dictionary_entry () const [inline], [private]
Definition at line 371 of file lookup-inl.h.
                                                     {
  DCHECK(!holder_.is_null());
  DCHECK(!IsElement(*holder_));
  DCHECK(has_property_);
  DCHECK(!holder_->HasFastProperties(isolate_));
  return number_;
}
References v8::internal::DCHECK(), has_property_, holder_, IsElement(), isolate_, and number_.
Referenced by Delete(), DictCanStayConst(), FetchValue(), GetPropertyCell(), PrepareForDataProperty(), ReconfigureDataProperty(), and WriteDataValue().
ExtendingNonExtensible()
bool v8::internal::LookupIterator::ExtendingNonExtensible (DirectHandle< JSReceiver > receiver) [inline]
Definition at line 291 of file lookup-inl.h.
                                                                             {
  DCHECK(receiver.is_identical_to(GetStoreTarget<JSReceiver>()));
  DisallowGarbageCollection no_gc;
  Tagged<Map> receiver_map = receiver->map(isolate_);
  if (receiver_map->is_extensible()) {
    return false;
  }
  // Extending with elements and non-private properties is not allowed.
  if (IsElement() || !name_->IsPrivate()) {
    return true;
  }
  // These JSObject types are wrappers around a set of primitive values
  // and exist only for the purpose of passing the data across V8 Api.
  // They are not supposed to be ever leaked to user JS code.
  CHECK(!IsMaybeReadOnlyJSObjectMap(receiver_map));
  // Shared objects have fixed layout. No properties may be added to them, not
  // even private symbols.
  if (IsAlwaysSharedSpaceJSObjectMap(receiver_map)) {
    return true;
  }
  // Extending non-extensible objects with private fields is allowed.
  DCHECK(!receiver_map->is_extensible());
  DCHECK(name_->IsPrivate());
  if (name_->IsPrivateName()) {
    isolate()->CountUsage(v8::Isolate::kExtendingNonExtensibleWithPrivate);
  }
  return false;
}
References CHECK, v8::internal::Isolate::CountUsage(), v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_identical_to(), IsElement(), isolate(), isolate_, v8::Isolate::kExtendingNonExtensibleWithPrivate, name_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::JSReceiver::CheckPrivateNameStore(), and v8::internal::StoreIC::LookupForWrite().
factory()
Factory* v8::internal::LookupIterator::factory () const [inline]
Definition at line 187 of file lookup.h.
{ return isolate_->factory(); }
Referenced by v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::Object::GetElement(), v8::internal::JSReceiver::GetElement(), GetName(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::GetProperty(), v8::internal::JSObject::GetPropertyWithFailedAccessCheck(), GetReceiverMap(), v8::internal::JSObject::SetAccessor(), and TransitionToAccessorProperty().
FetchValue()
DirectHandle< Object > v8::internal::LookupIterator::FetchValue (AllocationPolicy allocation_policy = AllocationPolicy::kAllocationAllowed) const [private]
Definition at line 917 of file lookup.cc.
                                              {
  Tagged<Object> result;
  DCHECK_NE(state_, STRING_LOOKUP_START_OBJECT);
  DCHECK(!IsWasmObject(*holder_));
  if (IsElement(*holder_)) {
    DirectHandle<JSObject> holder = GetHolder<JSObject>();
    ElementsAccessor* accessor = holder->GetElementsAccessor(isolate_);
    return accessor->Get(isolate_, holder, number_);
  } else if (IsJSGlobalObject(*holder_, isolate_)) {
    DirectHandle<JSGlobalObject> holder = GetHolder<JSGlobalObject>();
    result = holder->global_dictionary(isolate_, kAcquireLoad)
                 ->ValueAt(isolate_, dictionary_entry());
  } else if (!holder_->HasFastProperties(isolate_)) {
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      result = holder_->property_dictionary_swiss(isolate_)->ValueAt(
          dictionary_entry());
    } else {
      result = holder_->property_dictionary(isolate_)->ValueAt(
          isolate_, dictionary_entry());
    }
  } else if (property_details_.location() == PropertyLocation::kField) {
    DCHECK_EQ(PropertyKind::kData, property_details_.kind());
    DirectHandle<JSObject> holder = GetHolder<JSObject>();
    FieldIndex field_index =
        FieldIndex::ForDetails(holder->map(isolate_), property_details_);
    if (allocation_policy == AllocationPolicy::kAllocationDisallowed &&
        field_index.is_inobject() && field_index.is_double()) {
      return isolate_->factory()->undefined_value();
    }
    return JSObject::FastPropertyAt(
        isolate_, holder, property_details_.representation(), field_index);
  } else {
    result =
        holder_->map(isolate_)->instance_descriptors(isolate_)->GetStrongValue(
            isolate_, descriptor_number());
  }
  return direct_handle(result, isolate_);
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, descriptor_number(), dictionary_entry(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSObject::FastPropertyAt(), v8::internal::FieldIndex::ForDetails(), v8::internal::ElementsAccessor::Get(), holder_, v8::internal::FieldIndex::is_double(), v8::internal::FieldIndex::is_inobject(), IsElement(), isolate_, v8::internal::IsWasmObject(), v8::kAcquireLoad, v8::internal::kAllocationDisallowed, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), number_, property_details_, v8::internal::PropertyDetails::representation(), v8::base::internal::result, state_, STRING_LOOKUP_START_OBJECT, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by GetAccessors(), and GetDataValue().
GetAccessorIndex()
int v8::internal::LookupIterator::GetAccessorIndex () const
Definition at line 1031 of file lookup.cc.
                                           {
  DCHECK(has_property_);
  DCHECK(holder_->HasFastProperties(isolate_));
  DCHECK_EQ(PropertyLocation::kDescriptor, property_details_.location());
  DCHECK_EQ(PropertyKind::kAccessor, property_details_.kind());
  return descriptor_number().as_int();
}
References v8::internal::InternalIndex::as_int(), v8::internal::DCHECK(), DCHECK_EQ, descriptor_number(), has_property_, holder_, isolate_, v8::internal::kAccessor, v8::internal::kDescriptor, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), and property_details_.
Referenced by v8::internal::LoadIC::ComputeHandler(), and v8::internal::StoreIC::ComputeHandler().
GetAccessors()
DirectHandle< Object > v8::internal::LookupIterator::GetAccessors () const
Definition at line 1057 of file lookup.cc.
                                                        {
  DCHECK_EQ(ACCESSOR, state_);
  return FetchValue();
}
References ACCESSOR, DCHECK_EQ, FetchValue(), and state_.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::CallSiteInfo::GetMethodName(), v8::internal::anonymous_namespace{debug-property-iterator.cc}::GetNativeAccessorDescriptorInternal(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Object::GetPropertyWithAccessor(), LookupCachedProperty(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), PrepareTransitionToDataProperty(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::Object::SetSuperProperty(), TransitionToAccessorProperty(), and TryLookupCachedProperty().
GetDataValue() [1/2]
Handle< Object > v8::internal::LookupIterator::GetDataValue (AllocationPolicy allocation_policy = AllocationPolicy::kAllocationAllowed) const
Definition at line 1079 of file lookup.cc.
                                              {
  DCHECK_EQ(DATA, state_);
  return indirect_handle(FetchValue(allocation_policy), isolate_);
}
References DATA, DCHECK_EQ, FetchValue(), v8::internal::indirect_handle(), isolate_, and state_.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::CallSiteInfo::GetMethodName(), v8::internal::Object::GetProperty(), v8::internal::wasm::InstanceBuilder::LookupImportAsm(), and v8::internal::RUNTIME_FUNCTION().
GetDataValue() [2/2]
DirectHandle< Object > v8::internal::LookupIterator::GetDataValue (SeqCstAccessTag tag) const
Definition at line 1085 of file lookup.cc.
                                                                           {
  DCHECK_EQ(DATA, state_);
  // Currently only shared structs and arrays support sequentially consistent
  // access.
  DCHECK(IsJSSharedStruct(*holder_, isolate_) ||
         IsJSSharedArray(*holder_, isolate_));
  DirectHandle<JSObject> holder = GetHolder<JSObject>();
  if (IsElement(*holder)) {
    ElementsAccessor* accessor = holder->GetElementsAccessor(isolate_);
    return accessor->GetAtomic(isolate_, holder, number_, kSeqCstAccess);
  }
  DCHECK_EQ(PropertyLocation::kField, property_details_.location());
  DCHECK_EQ(PropertyKind::kData, property_details_.kind());
  FieldIndex field_index =
      FieldIndex::ForDetails(holder->map(isolate_), property_details_);
  return JSObject::FastPropertyAt(
      isolate_, holder, property_details_.representation(), field_index, tag);
}
References DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::JSObject::FastPropertyAt(), v8::internal::FieldIndex::ForDetails(), v8::internal::ElementsAccessor::GetAtomic(), holder_, IsElement(), isolate_, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::kSeqCstAccess, v8::internal::PropertyDetails::location(), number_, property_details_, v8::internal::PropertyDetails::representation(), and state_.
GetFieldDescriptorIndex()
int v8::internal::LookupIterator::GetFieldDescriptorIndex () const
Definition at line 1022 of file lookup.cc.
                                                  {
  DCHECK(has_property_);
  DCHECK(holder_->HasFastProperties());
  DCHECK_EQ(PropertyLocation::kField, property_details_.location());
  DCHECK_EQ(PropertyKind::kData, property_details_.kind());
  // TODO(jkummerow): Propagate InternalIndex further.
  return descriptor_number().as_int();
}
References v8::internal::InternalIndex::as_int(), v8::internal::DCHECK(), DCHECK_EQ, descriptor_number(), has_property_, holder_, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), and property_details_.
Referenced by v8::internal::StoreIC::ComputeHandler().
GetFieldIndex()
FieldIndex v8::internal::LookupIterator::GetFieldIndex () const
Definition at line 1039 of file lookup.cc.
                                               {
  DCHECK(has_property_);
  DCHECK(!holder_.is_null());
  DCHECK(holder_->HasFastProperties(isolate_));
  DCHECK_EQ(PropertyLocation::kField, property_details_.location());
  DCHECK(!IsElement(*holder_));
  return FieldIndex::ForDetails(holder_->map(isolate_), property_details_);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FieldIndex::ForDetails(), has_property_, holder_, IsElement(), isolate_, v8::internal::kField, v8::internal::PropertyDetails::location(), and property_details_.
Referenced by v8::internal::LoadIC::ComputeHandler(), and v8::internal::StoreIC::ComputeHandler().
GetHolder()
template<class T >
DirectHandle< T > v8::internal::LookupIterator::GetHolder [inline]
Definition at line 283 of file lookup-inl.h.
                                                {
  DCHECK(IsFound());
  // Holder is not initialized in this state and one should use
  // lookup_start_object() instead.
  DCHECK_NE(state_, STRING_LOOKUP_START_OBJECT);
  return Cast<T>(holder_);
}
References v8::internal::DCHECK(), DCHECK_NE, holder_, IsFound(), state_, and STRING_LOOKUP_START_OBJECT.
Referenced by v8::internal::JSReceiver::AddPrivateField(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::ErrorUtils::GetErrorStackProperty(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::JSProxy::GetPropertyAttributes(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::JSObject::GetPropertyWithFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), v8::internal::JSReceiver::HasProperty(), v8::internal::LookupForRead(), v8::internal::StoreIC::LookupForWrite(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), v8::internal::Accessors::ReplaceAccessorWithDataProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::JSObject::SetPropertyWithFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), v8::internal::LoadIC::UpdateCaches(), and v8::internal::StoreIC::UpdateCaches().
GetInterceptor() [1/2]
DirectHandle< InterceptorInfo > v8::internal::LookupIterator::GetInterceptor () const [inline]
Definition at line 409 of file lookup-inl.h.
                                                                          {
  DCHECK_EQ(INTERCEPTOR, state_);
  Tagged<JSObject> holder = Cast<JSObject>(*holder_);
  Tagged<InterceptorInfo> result = IsElement(holder)
                                       ? GetInterceptor<true>(holder)
                                       : GetInterceptor<false>(holder);
  return direct_handle(result, isolate_);
}
References DCHECK_EQ, v8::internal::direct_handle(), holder_, INTERCEPTOR, IsElement(), isolate_, v8::base::internal::result, and state_.
Referenced by v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::JSObject::GetPropertyAttributesWithInterceptor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::JSObject::GetPropertyWithInterceptor(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), and v8::internal::JSObject::SetPropertyWithInterceptor().
GetInterceptor() [2/2]
template<bool is_element>
Tagged< InterceptorInfo > v8::internal::LookupIterator::GetInterceptor (Tagged< JSObject > holder) const [inline], [private]
Definition at line 400 of file lookup-inl.h.
                                   {
  if (is_element && index_ <= JSObject::kMaxElementIndex) {
    return holder->GetIndexedInterceptor(isolate_);
  } else {
    return holder->GetNamedInterceptor(isolate_);
  }
}
References index_, isolate_, and v8::internal::JSObject::kMaxElementIndex.
GetInterceptorForFailedAccessCheck()
DirectHandle< InterceptorInfo > v8::internal::LookupIterator::GetInterceptorForFailedAccessCheck () const
Definition at line 1430 of file lookup.cc.
                                                         {
  DCHECK_EQ(ACCESS_CHECK, state_);
  // Skip the interceptors for private
  if (IsPrivateName()) {
    return DirectHandle<InterceptorInfo>();
  }
  DisallowGarbageCollection no_gc;
  Tagged<AccessCheckInfo> access_check_info =
      AccessCheckInfo::Get(isolate_, Cast<JSObject>(holder_));
  if (!access_check_info.is_null()) {
    // There is currently no way to create objects with typed array elements
    // and access checks.
    DCHECK(!holder_->map()->has_typed_array_or_rab_gsab_typed_array_elements());
    Tagged<Object> interceptor = is_js_array_element(IsElement())
                                     ? access_check_info->indexed_interceptor()
                                     : access_check_info->named_interceptor();
    if (interceptor != Tagged<Object>()) {
      return direct_handle(Cast<InterceptorInfo>(interceptor), isolate_);
    }
  }
  return DirectHandle<InterceptorInfo>();
}
References ACCESS_CHECK, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::AccessCheckInfo::Get(), holder_, is_js_array_element(), v8::internal::Tagged< HeapObject >::is_null(), IsElement(), isolate_, IsPrivateName(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and state_.
Referenced by v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::JSObject::GetPropertyWithFailedAccessCheck(), and v8::internal::JSObject::SetPropertyWithFailedAccessCheck().
GetKey()
PropertyKey v8::internal::LookupIterator::GetKey () const [inline]
Definition at line 254 of file lookup-inl.h.
                                         {
  return PropertyKey(isolate_, name_, index_);
}
References index_, isolate_, name_, and PropertyKey.
Referenced by v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), and v8::internal::Object::SetSuperProperty().
GetName()
DirectHandle< Name > v8::internal::LookupIterator::GetName () [inline]
Definition at line 246 of file lookup-inl.h.
                                           {
  if (name_.is_null()) {
    DCHECK(IsElement());
    name_ = factory()->SizeToString(index_);
  }
  return name_;
}
References v8::internal::DCHECK(), factory(), index_, IsElement(), name_, and v8::internal::Factory::SizeToString().
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::JSReceiver::AddPrivateField(), v8::internal::Object::CheckContextualStoreToJSGlobalObject(), v8::internal::JSObject::CheckIfCanDefineAsConfigurable(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Object::GetProperty(), v8::internal::JSProxy::GetPropertyAttributes(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::JSObject::GetPropertyWithFailedAccessCheck(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), v8::internal::JSReceiver::HasProperty(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), v8::internal::Object::SetDataProperty(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::Object::SetSuperProperty(), v8::internal::LoadIC::UpdateCaches(), v8::internal::StoreIC::UpdateCaches(), v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor(), and v8::internal::Object::WriteToReadOnlyProperty().
GetPropertyCell()
DirectHandle< PropertyCell > v8::internal::LookupIterator::GetPropertyCell () const
Definition at line 1048 of file lookup.cc.
                                                                 {
  DCHECK(!holder_.is_null());
  DCHECK(!IsElement(*holder_));
  DirectHandle<JSGlobalObject> holder = GetHolder<JSGlobalObject>();
  return direct_handle(holder->global_dictionary(isolate_, kAcquireLoad)
                           ->CellAt(isolate_, dictionary_entry()),
                       isolate_);
}
References v8::internal::DCHECK(), dictionary_entry(), v8::internal::direct_handle(), holder_, IsElement(), isolate_, and v8::kAcquireLoad.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::LoadIC::UpdateCaches(), and v8::internal::StoreIC::UpdateCaches().
GetReceiver()
DirectHandle<JSAny> v8::internal::LookupIterator::GetReceiver () const [inline]
Definition at line 188 of file lookup.h.
{ return receiver_; }
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::JSReceiver::AddPrivateField(), v8::internal::Object::CheckContextualStoreToJSGlobalObject(), v8::internal::JSObject::CheckIfCanDefineAsConfigurable(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::Object::GetProperty(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), v8::internal::StoreIC::LookupForWrite(), v8::internal::Object::SetDataProperty(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), v8::internal::Object::SetSuperProperty(), v8::internal::UnscopableLookup(), v8::internal::LoadIC::UpdateCaches(), v8::internal::StoreIC::UpdateCaches(), and v8::internal::Object::WriteToReadOnlyProperty().
GetReceiverMap()
DirectHandle< Map > v8::internal::LookupIterator::GetReceiverMap () const [private]
Definition at line 172 of file lookup.cc.
                                                       {
  if (IsNumber(*receiver_, isolate_)) return factory()->heap_number_map();
  return direct_handle(Cast<HeapObject>(receiver_)->map(isolate_), isolate_);
}
References v8::internal::direct_handle(), factory(), v8::internal::IsNumber(), isolate_, and receiver_.
GetRootForNonJSReceiver()
Tagged< JSReceiver > v8::internal::LookupIterator::GetRootForNonJSReceiver () const [private]
Definition at line 157 of file lookup.cc.
                                                                 {
  // Own property lookup case is handled before calling this method.
  DCHECK(check_prototype_chain());
  Tagged<HeapObject> root =
      Object::GetPrototypeChainRootMap(*lookup_start_object_, isolate_)
          ->prototype(isolate_);
  if (IsNull(root, isolate_)) {
    isolate_->PushStackTraceAndDie(
        reinterpret_cast<void*>((*lookup_start_object_).ptr()));
  }
  return Cast<JSReceiver>(root);
}
References check_prototype_chain(), v8::internal::DCHECK(), v8::internal::Object::GetPrototypeChainRootMap(), v8::internal::IsNull(), isolate_, lookup_start_object_, and v8::internal::Isolate::PushStackTraceAndDie().
Referenced by Start().
GetStoreTarget()
template<class T >
DirectHandle< T > v8::internal::LookupIterator::GetStoreTarget [inline]
Definition at line 387 of file lookup-inl.h.
                                                     {
  DCHECK(IsJSReceiver(*receiver_, isolate_));
  if (IsJSGlobalProxy(*receiver_, isolate_)) {
    Tagged<HeapObject> prototype =
        Cast<JSGlobalProxy>(*receiver_)->map(isolate_)->prototype(isolate_);
    if (IsJSGlobalObject(prototype, isolate_)) {
      return direct_handle(Cast<JSGlobalObject>(prototype), isolate_);
    }
  }
  return Cast<T>(receiver_);
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), isolate_, v8::internal::prototype, and receiver_.
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::StoreIC::ComputeHandler(), v8::internal::StoreIC::LookupForWrite(), and v8::internal::Object::TransitionAndWriteDataProperty().
GetStringPropertyValue()
Handle< Object > v8::internal::LookupIterator::GetStringPropertyValue (AllocationPolicy allocation_policy = AllocationPolicy::kAllocationAllowed) const
Definition at line 1062 of file lookup.cc.
                                              {
  DCHECK_EQ(state_, STRING_LOOKUP_START_OBJECT);
  if (IsElement()) {
    DirectHandle<String> string = Cast<String>(lookup_start_object_);
    // The state guarantees that it's an access within bounds.
    DCHECK_LT(index_, string->length());
    return isolate_->factory()->LookupSingleCharacterStringFromCode(
        String::Flatten(isolate_, string)->Get(static_cast<uint32_t>(index_)));
  }
  // The state guarantees that it's a lookup of "length" property.
  DCHECK_EQ(*name_, ReadOnlyRoots(isolate_).length_string());
  uint32_t length = Cast<String>(*lookup_start_object_)->length();
  static_assert(String::kMaxLength < Smi::kMaxValue);
  return handle(Smi::FromInt(length), isolate_);
}
References DCHECK_EQ, DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::compiler::turboshaft::Get(), v8::internal::handle(), index_, IsElement(), isolate_, v8::internal::String::kMaxLength, v8::internal::Smi::kMaxValue, v8::internal::length, lookup_start_object_, v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), name_, state_, v8::internal::string, and STRING_LOOKUP_START_OBJECT.
Referenced by v8::internal::Object::GetProperty().
HasAccess()
bool v8::internal::LookupIterator::HasAccess () const
Definition at line 177 of file lookup.cc.
                                     {
  // TRANSITION is true when being called from DefineNamedOwnIC.
  DCHECK(state_ == ACCESS_CHECK || state_ == TRANSITION);
  return isolate_->MayAccess(isolate_->native_context(), GetHolder<JSObject>());
}
References ACCESS_CHECK, v8::internal::DCHECK(), isolate_, v8::internal::Isolate::MayAccess(), v8::internal::Isolate::native_context(), state_, and TRANSITION.
Referenced by v8::internal::JSReceiver::AddPrivateField(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), v8::internal::JSReceiver::HasProperty(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), v8::internal::Accessors::ReplaceAccessorWithDataProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSObject::SetAccessor(), v8::internal::Object::SetPropertyInternal(), and v8::internal::Object::SetSuperProperty().
HasInternalMarkerProperty()
bool v8::internal::LookupIterator::HasInternalMarkerProperty (Isolate * isolate, Tagged< JSReceiver > object, DirectHandle< Symbol > marker) [static]
Definition at line 1406 of file lookup.cc.
                                       {
  DisallowGarbageCollection no_gc;
  Tagged<Map> map = holder->map(isolate);
  if (map->is_dictionary_map()) {
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      Tagged<SwissNameDictionary> dict =
          holder->property_dictionary_swiss(isolate);
      InternalIndex entry = dict->FindEntry(isolate, marker);
      return entry.is_found();
    } else {
      Tagged<NameDictionary> dict = holder->property_dictionary(isolate);
      InternalIndex entry = dict->FindEntry(isolate, marker);
      return entry.is_found();
    }
  } else {
    Tagged<DescriptorArray> descriptors = map->instance_descriptors(isolate);
    InternalIndex entry = descriptors->SearchWithCache(isolate, *marker, map);
    return entry.is_found();
  }
}
References v8::internal::InternalIndex::is_found(), isolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::Isolate::is_catchable_by_wasm().
heap()
Heap* v8::internal::LookupIterator::heap () const [inline]
Definition at line 186 of file lookup.h.
{ return isolate_->heap(); }
HolderIsReceiver()
bool v8::internal::LookupIterator::HolderIsReceiver () const
Definition at line 897 of file lookup.cc.
                                            {
  DCHECK_NE(state_, STRING_LOOKUP_START_OBJECT);
  DCHECK(has_property_ || state_ == INTERCEPTOR || state_ == JSPROXY ||
         state_ == TYPED_ARRAY_INDEX_NOT_FOUND);
  // Optimization that only works if configuration_ is not mutable.
  if (!check_prototype_chain()) return true;
  return *receiver_ == *holder_;
}
References check_prototype_chain(), v8::internal::DCHECK(), DCHECK_NE, has_property_, holder_, INTERCEPTOR, JSPROXY, receiver_, state_, STRING_LOOKUP_START_OBJECT, and TYPED_ARRAY_INDEX_NOT_FOUND.
Referenced by v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::Object::SetPropertyInternal(), and v8::internal::Object::WriteToReadOnlyProperty().
HolderIsReceiverOrHiddenPrototype()
bool v8::internal::LookupIterator::HolderIsReceiverOrHiddenPrototype () const
Definition at line 906 of file lookup.cc.
                                                             {
  DCHECK_NE(state_, STRING_LOOKUP_START_OBJECT);
  DCHECK(has_property_ || state_ == INTERCEPTOR || state_ == JSPROXY);
  // Optimization that only works if configuration_ is not mutable.
  if (!check_prototype_chain()) return true;
  if (*receiver_ == *holder_) return true;
  if (!IsJSGlobalProxy(*receiver_, isolate_)) return false;
  return Cast<JSGlobalProxy>(receiver_)->map(isolate_)->prototype(isolate_) ==
         *holder_;
}
References check_prototype_chain(), v8::internal::DCHECK(), DCHECK_NE, has_property_, holder_, INTERCEPTOR, isolate_, JSPROXY, receiver_, state_, and STRING_LOOKUP_START_OBJECT.
Referenced by v8::internal::StoreIC::ComputeHandler(), LookupCachedProperty(), v8::internal::StoreIC::LookupForWrite(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), PrepareForDataProperty(), PrepareTransitionToDataProperty(), ReconfigureDataProperty(), v8::internal::Object::SetDataProperty(), and v8::internal::Object::SetPropertyInternal().
index()
size_t v8::internal::LookupIterator::index () const [inline]
Definition at line 160 of file lookup.h.
{ return index_; }
References v8::internal::PropertyKey::index_.
Referenced by LookupIterator(), and v8::internal::Object::SetDataProperty().
InternalUpdateProtector()
void v8::internal::LookupIterator::InternalUpdateProtector (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name) [static], [private]
Definition at line 192 of file lookup.cc.
                             {
  if (isolate->bootstrapper()->IsActive()) return;
  if (!IsJSObject(*receiver_generic)) return;
  auto receiver = Cast<JSObject>(receiver_generic);
  ReadOnlyRoots roots(isolate);
  if (*name == roots.constructor_string()) {
    // Setting the constructor property could change an instance's @@species
    if (IsJSArray(*receiver, isolate)) {
      if (!Protectors::IsArraySpeciesLookupChainIntact(isolate)) return;
      isolate->CountUsage(
          v8::Isolate::UseCounterFeature::kArrayInstanceConstructorModified);
      Protectors::InvalidateArraySpeciesLookupChain(isolate);
      return;
    } else if (IsJSPromise(*receiver, isolate)) {
      if (!Protectors::IsPromiseSpeciesLookupChainIntact(isolate)) return;
      Protectors::InvalidatePromiseSpeciesLookupChain(isolate);
      return;
    } else if (IsJSRegExp(*receiver, isolate)) {
      if (!Protectors::IsRegExpSpeciesLookupChainIntact(isolate)) return;
      Protectors::InvalidateRegExpSpeciesLookupChain(isolate);
      return;
    } else if (IsJSTypedArray(*receiver, isolate)) {
      if (!Protectors::IsTypedArraySpeciesLookupChainIntact(isolate)) return;
      Protectors::InvalidateTypedArraySpeciesLookupChain(isolate);
      return;
    }
    if (receiver->map(isolate)->is_prototype_map()) {
      DisallowGarbageCollection no_gc;
      // Setting the constructor of any prototype with the @@species protector
      // (of any realm) also needs to invalidate the protector.
      if (isolate->IsInCreationContext(
              Cast<JSObject>(*receiver),
              Context::INITIAL_ARRAY_PROTOTYPE_INDEX)) {
        if (!Protectors::IsArraySpeciesLookupChainIntact(isolate)) return;
        isolate->CountUsage(
            v8::Isolate::UseCounterFeature::kArrayPrototypeConstructorModified);
        Protectors::InvalidateArraySpeciesLookupChain(isolate);
      } else if (IsJSPromisePrototype(*receiver)) {
        if (!Protectors::IsPromiseSpeciesLookupChainIntact(isolate)) return;
        Protectors::InvalidatePromiseSpeciesLookupChain(isolate);
      } else if (IsJSRegExpPrototype(*receiver)) {
        if (!Protectors::IsRegExpSpeciesLookupChainIntact(isolate)) return;
        Protectors::InvalidateRegExpSpeciesLookupChain(isolate);
      } else if (IsJSTypedArrayPrototype(*receiver)) {
        if (!Protectors::IsTypedArraySpeciesLookupChainIntact(isolate)) return;
        Protectors::InvalidateTypedArraySpeciesLookupChain(isolate);
      }
    }
  } else if (*name == roots.next_string()) {
    if (IsJSArrayIterator(*receiver) || IsJSArrayIteratorPrototype(*receiver)) {
      // Setting the next property of %ArrayIteratorPrototype% also needs to
      // invalidate the array iterator protector.
      if (!Protectors::IsArrayIteratorLookupChainIntact(isolate)) return;
      Protectors::InvalidateArrayIteratorLookupChain(isolate);
    } else if (IsJSMapIterator(*receiver) ||
               IsJSMapIteratorPrototype(*receiver)) {
      if (!Protectors::IsMapIteratorLookupChainIntact(isolate)) return;
      Protectors::InvalidateMapIteratorLookupChain(isolate);
    } else if (IsJSSetIterator(*receiver) ||
               IsJSSetIteratorPrototype(*receiver)) {
      if (!Protectors::IsSetIteratorLookupChainIntact(isolate)) return;
      Protectors::InvalidateSetIteratorLookupChain(isolate);
    } else if (IsJSStringIterator(*receiver) ||
               IsJSStringIteratorPrototype(*receiver)) {
      // Setting the next property of %StringIteratorPrototype% invalidates the
      // string iterator protector.
      if (!Protectors::IsStringIteratorLookupChainIntact(isolate)) return;
      Protectors::InvalidateStringIteratorLookupChain(isolate);
    }
  } else if (*name == roots.species_symbol()) {
    // Setting the Symbol.species property of any Array, Promise or TypedArray
    // constructor invalidates the @@species protector
    if (IsJSArrayConstructor(*receiver)) {
      if (!Protectors::IsArraySpeciesLookupChainIntact(isolate)) return;
      isolate->CountUsage(
          v8::Isolate::UseCounterFeature::kArraySpeciesModified);
      Protectors::InvalidateArraySpeciesLookupChain(isolate);
    } else if (IsJSPromiseConstructor(*receiver)) {
      if (!Protectors::IsPromiseSpeciesLookupChainIntact(isolate)) return;
      Protectors::InvalidatePromiseSpeciesLookupChain(isolate);
    } else if (IsJSRegExpConstructor(*receiver)) {
      if (!Protectors::IsRegExpSpeciesLookupChainIntact(isolate)) return;
      Protectors::InvalidateRegExpSpeciesLookupChain(isolate);
    } else if (IsTypedArrayConstructor(*receiver)) {
      if (!Protectors::IsTypedArraySpeciesLookupChainIntact(isolate)) return;
      Protectors::InvalidateTypedArraySpeciesLookupChain(isolate);
    }
  } else if (*name == roots.is_concat_spreadable_symbol()) {
    if (!Protectors::IsIsConcatSpreadableLookupChainIntact(isolate)) return;
    Protectors::InvalidateIsConcatSpreadableLookupChain(isolate);
  } else if (*name == roots.iterator_symbol()) {
    if (IsJSArray(*receiver, isolate)) {
      if (!Protectors::IsArrayIteratorLookupChainIntact(isolate)) return;
      Protectors::InvalidateArrayIteratorLookupChain(isolate);
    } else if (IsJSSet(*receiver, isolate) || IsJSSetIterator(*receiver) ||
               IsJSSetIteratorPrototype(*receiver) ||
               IsJSSetPrototype(*receiver)) {
      if (Protectors::IsSetIteratorLookupChainIntact(isolate)) {
        Protectors::InvalidateSetIteratorLookupChain(isolate);
      }
    } else if (IsJSMapIterator(*receiver) ||
               IsJSMapIteratorPrototype(*receiver)) {
      if (Protectors::IsMapIteratorLookupChainIntact(isolate)) {
        Protectors::InvalidateMapIteratorLookupChain(isolate);
      }
    } else if (IsJSIteratorPrototype(*receiver)) {
      if (Protectors::IsMapIteratorLookupChainIntact(isolate)) {
        Protectors::InvalidateMapIteratorLookupChain(isolate);
      }
      if (Protectors::IsSetIteratorLookupChainIntact(isolate)) {
        Protectors::InvalidateSetIteratorLookupChain(isolate);
      }
    } else if (isolate->IsInCreationContext(
                   *receiver, Context::INITIAL_STRING_PROTOTYPE_INDEX)) {
      // Setting the Symbol.iterator property of String.prototype invalidates
      // the string iterator protector. Symbol.iterator can also be set on a
      // String wrapper, but not on a primitive string. We only support
      // protector for primitive strings.
      if (!Protectors::IsStringIteratorLookupChainIntact(isolate)) return;
      Protectors::InvalidateStringIteratorLookupChain(isolate);
    }
  } else if (*name == roots.resolve_string()) {
    if (!Protectors::IsPromiseResolveLookupChainIntact(isolate)) return;
    // Setting the "resolve" property on any %Promise% intrinsic object
    // invalidates the Promise.resolve protector.
    if (IsJSPromiseConstructor(*receiver)) {
      Protectors::InvalidatePromiseResolveLookupChain(isolate);
    }
  } else if (*name == roots.then_string()) {
    if (!Protectors::IsPromiseThenLookupChainIntact(isolate)) return;
    // Setting the "then" property on any JSPromise instance or on the
    // initial %PromisePrototype% invalidates the Promise#then protector.
    // Also setting the "then" property on the initial %ObjectPrototype%
    // invalidates the Promise#then protector, since we use this protector
    // to guard the fast-path in AsyncGeneratorResolve, where we can skip
    // the ResolvePromise step and go directly to FulfillPromise if we
    // know that the Object.prototype doesn't contain a "then" method.
    if (IsJSPromise(*receiver, isolate) || IsJSObjectPrototype(*receiver) ||
        IsJSPromisePrototype(*receiver)) {
      Protectors::InvalidatePromiseThenLookupChain(isolate);
    }
  } else if (*name == roots.match_all_symbol() ||
             *name == roots.replace_symbol() || *name == roots.split_symbol()) {
    if (!Protectors::IsNumberStringNotRegexpLikeIntact(isolate)) return;
    // We need to protect the prototype chains of `Number.prototype` and
    // `String.prototype`: that `Symbol.{matchAll|replace|split}` is not added
    // as a property on any object on these prototype chains. We detect
    // `Number.prototype` and `String.prototype` by checking for a prototype
    // that is a JSPrimitiveWrapper. This is a safe approximation. Using
    // JSPrimitiveWrapper as prototype should be sufficiently rare.
    if (receiver->map()->is_prototype_map() &&
        (IsJSPrimitiveWrapper(*receiver) || IsJSObjectPrototype(*receiver))) {
      Protectors::InvalidateNumberStringNotRegexpLike(isolate);
    }
  } else if (*name == roots.to_primitive_symbol()) {
    if (!Protectors::IsStringWrapperToPrimitiveIntact(isolate)) return;
    if (isolate->IsInCreationContext(*receiver,
                                     Context::INITIAL_STRING_PROTOTYPE_INDEX) ||
        isolate->IsInCreationContext(*receiver,
                                     Context::INITIAL_OBJECT_PROTOTYPE_INDEX) ||
        IsStringWrapper(*receiver)) {
      Protectors::InvalidateStringWrapperToPrimitive(isolate);
    }
  } else if (*name == roots.valueOf_string()) {
    if (!Protectors::IsStringWrapperToPrimitiveIntact(isolate)) return;
    if (isolate->IsInCreationContext(*receiver,
                                     Context::INITIAL_STRING_PROTOTYPE_INDEX) ||
        IsStringWrapper(*receiver)) {
      Protectors::InvalidateStringWrapperToPrimitive(isolate);
    }
  }
}
References v8::internal::Isolate::bootstrapper(), v8::internal::Isolate::CountUsage(), v8::internal::Bootstrapper::IsActive(), v8::internal::Isolate::IsInCreationContext(), isolate(), name(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by UpdateProtector().
is_dictionary_holder()
bool v8::internal::LookupIterator::is_dictionary_holder () const [inline]
Definition at line 268 of file lookup-inl.h.
                                                {
  return !holder_->HasFastProperties(isolate_);
}
References holder_, and isolate_.
Referenced by v8::internal::LoadIC::ComputeHandler(), and v8::internal::StoreIC::ComputeHandler().
is_js_array_element()
bool v8::internal::LookupIterator::is_js_array_element (bool is_element) const [inline], [private]
Definition at line 310 of file lookup.h.
                                                  {
    return is_element && index_ <= JSArray::kMaxArrayIndex;
  }
References v8::internal::PropertyKey::index_, v8::internal::PropertyKey::is_element(), and v8::internal::JSArray::kMaxArrayIndex.
Referenced by GetInterceptorForFailedAccessCheck(), and LookupInSpecialHolder().
IsCacheableTransition()
bool v8::internal::LookupIterator::IsCacheableTransition () [inline]
Definition at line 321 of file lookup-inl.h.
                                           {
  DCHECK_EQ(TRANSITION, state_);
  return IsPropertyCell(*transition_, isolate_) ||
         (transition_map()->is_dictionary_map() &&
          !GetStoreTarget<JSReceiver>()->HasFastProperties(isolate_)) ||
         IsMap(transition_map()->GetBackPointer(isolate_), isolate_);
}
References DCHECK_EQ, isolate_, state_, TRANSITION, transition_, and transition_map().
Referenced by v8::internal::StoreIC::ComputeHandler(), and v8::internal::StoreIC::LookupForWrite().
IsConfigurable()
bool v8::internal::LookupIterator::IsConfigurable () const [inline]
Definition at line 236 of file lookup.h.
{ return property_details().IsConfigurable(); }
Referenced by v8::internal::JSReceiver::DeleteProperty().
IsElement() [1/2]
bool v8::internal::LookupIterator::IsElement () const [inline]
Definition at line 171 of file lookup.h.
{ return index_ != kInvalidIndex; }
References v8::internal::PropertyKey::index_, and v8::internal::trap_handler::kInvalidIndex.
Referenced by v8::internal::Object::AddDataProperty(), CanStayConst(), CompareAndSwapDataValue(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), Delete(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSObject::DeletePropertyWithInterceptor(), descriptor_number(), DictCanStayConst(), dictionary_entry(), ExtendingNonExtensible(), FetchValue(), GetDataValue(), GetFieldIndex(), GetInterceptor(), GetInterceptorForFailedAccessCheck(), GetName(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), GetPropertyCell(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), GetStringPropertyValue(), IsPrivateName(), LookupInRegularHolder(), LookupIterator(), name(), Next(), NotFound(), PrepareForDataProperty(), PrepareTransitionToDataProperty(), RecheckTypedArrayBounds(), ReconfigureDataProperty(), v8::internal::JSObject::SetAccessor(), v8::internal::Object::SetDataProperty(), v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), SwapDataValue(), TransitionToAccessorPair(), TransitionToAccessorProperty(), UpdateProtector(), and WriteDataValue().
IsElement() [2/2]
bool v8::internal::LookupIterator::IsElement (Tagged< JSReceiver > object) const [inline]
Definition at line 258 of file lookup-inl.h.
                                                              {
  return index_ <= JSObject::kMaxElementIndex ||
         (index_ != kInvalidIndex &&
          object->map()->has_any_typed_array_or_wasm_array_elements());
}
References index_, kInvalidIndex, and v8::internal::JSObject::kMaxElementIndex.
IsEnumerable()
bool v8::internal::LookupIterator::IsEnumerable () const [inline]
Definition at line 238 of file lookup.h.
{ return property_details().IsEnumerable(); }
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), and v8::internal::FastGetOwnValuesOrEntries().
IsFound()
bool v8::internal::LookupIterator::IsFound () const [inline]
Definition at line 179 of file lookup.h.
{ return state_ != NOT_FOUND; }
Referenced by v8::internal::JSObject::AddProperty(), v8::internal::anonymous_namespace{runtime-atomics.cc}::AtomicFieldWrite(), v8::internal::JSObject::CheckIfCanDefineAsConfigurable(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::Genesis::CreateNewGlobals(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal(), v8::internal::anonymous_namespace{api-natives.cc}::DefineDataProperty(), v8::internal::Runtime::DefineObjectOwnProperty(), v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::anonymous_namespace{json-stringifier.cc}::GetBuiltin(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::Object::GetElement(), v8::internal::JSReceiver::GetElement(), v8::internal::ErrorUtils::GetErrorStackProperty(), GetHolder(), v8::internal::anonymous_namespace{debug-property-iterator.cc}::GetNativeAccessorDescriptorInternal(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Object::GetProperty(), v8::internal::JSProxy::GetProperty(), v8::internal::JSReceiver::GetProperty(), v8::Object::GetRealNamedProperty(), v8::Object::GetRealNamedPropertyAttributes(), v8::Object::GetRealNamedPropertyAttributesInPrototypeChain(), v8::Object::GetRealNamedPropertyInPrototypeChain(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::IncludesValueSlowPath(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::IndexOfValueSlowPath(), v8::internal::LoadIC::Load(), Next(), NextInternal(), v8::internal::PropertyAlreadyExists(), ReloadPropertyInformation(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSProxy::SetPrivateSymbol(), v8::internal::Object::SetProperty(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetSuperProperty(), Start(), v8::internal::ErrorUtils::ToString(), TransitionToAccessorProperty(), v8::internal::LoadIC::UpdateCaches(), v8::internal::ValueSerializer::WriteJSArray(), v8::internal::ValueSerializer::WriteJSObject(), v8::internal::ValueSerializer::WriteJSObjectPropertiesSlow(), and v8::internal::Object::WriteToReadOnlyProperty().
isolate()
Isolate* v8::internal::LookupIterator::isolate () const [inline]
Definition at line 155 of file lookup.h.
{ return isolate_; }
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::JSReceiver::AddPrivateField(), ApplyTransitionToDataProperty(), CanStayConst(), v8::internal::Object::CheckContextualStoreToJSGlobalObject(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSObject::DeletePropertyWithInterceptor(), DictCanStayConst(), ExtendingNonExtensible(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Object::GetProperty(), v8::internal::JSProxy::GetPropertyAttributes(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::JSObject::GetPropertyWithFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), HasInternalMarkerProperty(), v8::internal::JSReceiver::HasProperty(), InternalUpdateProtector(), LookupCachedProperty(), v8::internal::LookupForRead(), v8::internal::StoreIC::LookupForWrite(), LookupInRegularHolder(), LookupInSpecialHolder(), LookupIterator(), PrepareForDataProperty(), ReconfigureDataProperty(), v8::internal::Object::SetDataProperty(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::JSObject::SetPropertyWithFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), v8::internal::Object::SetSuperProperty(), v8::internal::Object::TransitionAndWriteDataProperty(), TransitionToAccessorProperty(), v8::internal::UnscopableLookup(), UpdateProtector(), and v8::internal::Object::WriteToReadOnlyProperty().
IsPrivateName()
bool v8::internal::LookupIterator::IsPrivateName () const [inline]
Definition at line 264 of file lookup-inl.h.
                                         {
  return !IsElement() && name()->IsPrivateName();
}
References IsElement(), and name().
Referenced by ApplyTransitionToDataProperty(), Delete(), GetInterceptorForFailedAccessCheck(), v8::internal::Object::GetProperty(), PrepareTransitionToDataProperty(), and v8::internal::LoadIC::UpdateCaches().
IsReadOnly()
bool v8::internal::LookupIterator::IsReadOnly () const [inline]
Definition at line 237 of file lookup.h.
{ return property_details().IsReadOnly(); }
Referenced by v8::internal::anonymous_namespace{runtime-atomics.cc}::AtomicFieldWrite(), v8::internal::JSArray::HasReadOnlyLengthSlowPath(), v8::internal::StoreIC::LookupForWrite(), v8::internal::Object::SetPropertyInternal(), and v8::internal::Object::SetSuperProperty().
location()
PropertyLocation v8::internal::LookupIterator::location () const [inline]
Definition at line 242 of file lookup.h.
{ return property_details().location(); }
lookup_start_object()
DirectHandle<JSAny> v8::internal::LookupIterator::lookup_start_object () const [inline]
Definition at line 198 of file lookup.h.
                                                  {
    return lookup_start_object_;
  }
Referenced by v8::internal::LoadIC::ComputeHandler(), LookupIterator(), and v8::internal::LoadIC::UpdateCaches().
LookupCachedProperty()
bool v8::internal::LookupIterator::LookupCachedProperty (DirectHandle< AccessorPair > accessor) [private]
Definition at line 1468 of file lookup.cc.
                                              {
  if (!HolderIsReceiverOrHiddenPrototype()) return false;
  if (!lookup_start_object_.is_identical_to(receiver_) &&
      !lookup_start_object_.is_identical_to(holder_)) {
    return false;
  }
  DCHECK_EQ(state(), LookupIterator::ACCESSOR);
  DCHECK(IsAccessorPair(*GetAccessors(), isolate_));
  Tagged<Object> getter = accessor_pair->getter();
  std::optional<Tagged<Name>> maybe_name =
      FunctionTemplateInfo::TryGetCachedPropertyName(isolate(), getter);
  if (!maybe_name.has_value()) return false;
  if (IsJSFunction(getter)) {
    // If the getter was a JSFunction there's no guarantee that the holder
    // actually has a property with the cached name. In that case look it up to
    // make sure.
    LookupIterator it(isolate_, holder_,
                      direct_handle(maybe_name.value(), isolate_));
    if (it.state() != DATA) return false;
    name_ = it.name();
  } else {
    name_ = direct_handle(maybe_name.value(), isolate_);
  }
  // We have found a cached property! Modify the iterator accordingly.
  Restart();
  CHECK_EQ(state(), LookupIterator::DATA);
  return true;
}
References ACCESSOR, CHECK_EQ, DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), GetAccessors(), holder_, HolderIsReceiverOrHiddenPrototype(), isolate(), isolate_, lookup_start_object_, name(), name_, receiver_, Restart(), state(), and v8::internal::FunctionTemplateInfo::TryGetCachedPropertyName().
Referenced by TryLookupCachedProperty().
LookupInHolder()
template<bool is_element>
State v8::internal::LookupIterator::LookupInHolder (Tagged< Map > map, Tagged< JSReceiver > holder) [inline], [private]
Definition at line 318 of file lookup.h.
                                                                          {
    return IsSpecialReceiverMap(map)
               ? LookupInSpecialHolder<is_element>(map, holder)
               : LookupInRegularHolder<is_element>(map, holder);
  }
References v8::internal::IsSpecialReceiverMap().
LookupInRegularHolder()
template<bool is_element>
LookupIterator::State v8::internal::LookupIterator::LookupInRegularHolder (Tagged< Map > map, Tagged< JSReceiver > holder) [private]
Definition at line 1348 of file lookup.cc.
                                                            {
  DisallowGarbageCollection no_gc;
  if (interceptor_state_ == InterceptorState::kProcessNonMasking) {
    return NOT_FOUND;
  }
  DCHECK(!IsWasmObject(holder, isolate_));
  if (is_element && IsElement(holder)) {
    Tagged<JSObject> js_object = Cast<JSObject>(holder);
    ElementsAccessor* accessor = js_object->GetElementsAccessor(isolate_);
    Tagged<FixedArrayBase> backing_store = js_object->elements(isolate_);
    number_ =
        accessor->GetEntryForIndex(isolate_, js_object, backing_store, index_);
    if (number_.is_not_found()) {
      return IsJSTypedArray(holder, isolate_) ? TYPED_ARRAY_INDEX_NOT_FOUND
                                              : NOT_FOUND;
    }
    property_details_ = accessor->GetDetails(js_object, number_);
    if (map->has_frozen_elements()) {
      property_details_ = property_details_.CopyAddAttributes(FROZEN);
    } else if (map->has_sealed_elements()) {
      property_details_ = property_details_.CopyAddAttributes(SEALED);
    }
  } else if (!map->is_dictionary_map()) {
    Tagged<DescriptorArray> descriptors = map->instance_descriptors(isolate_);
    number_ = descriptors->SearchWithCache(isolate_, *name_, map);
    if (number_.is_not_found()) return NotFound(holder);
    property_details_ = descriptors->GetDetails(number_);
  } else {
    DCHECK_IMPLIES(IsJSProxy(holder, isolate_), name()->IsPrivate());
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      Tagged<SwissNameDictionary> dict =
          holder->property_dictionary_swiss(isolate_);
      number_ = dict->FindEntry(isolate(), *name_);
      if (number_.is_not_found()) return NotFound(holder);
      property_details_ = dict->DetailsAt(number_);
    } else {
      Tagged<NameDictionary> dict = holder->property_dictionary(isolate_);
      number_ = dict->FindEntry(isolate(), name_);
      if (number_.is_not_found()) return NotFound(holder);
      property_details_ = dict->DetailsAt(number_);
    }
  }
  has_property_ = true;
  switch (property_details_.kind()) {
    case v8::internal::PropertyKind::kData:
      return DATA;
    case v8::internal::PropertyKind::kAccessor:
      return ACCESSOR;
  }
  UNREACHABLE();
}
References ACCESSOR, v8::internal::PropertyDetails::CopyAddAttributes(), DATA, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::FROZEN, v8::internal::ElementsAccessor::GetDetails(), v8::internal::ElementsAccessor::GetEntryForIndex(), has_property_, index_, interceptor_state_, v8::internal::InternalIndex::is_not_found(), IsElement(), isolate(), isolate_, v8::internal::IsWasmObject(), v8::internal::kAccessor, v8::internal::kData, v8::internal::PropertyDetails::kind(), kProcessNonMasking, name(), name_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, NOT_FOUND, NotFound(), number_, property_details_, v8::internal::SEALED, TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
LookupInSpecialHolder()
template<bool is_element>
LookupIterator::State v8::internal::LookupIterator::LookupInSpecialHolder (Tagged< Map > map, Tagged< JSReceiver > holder) [private]
Definition at line 1291 of file lookup.cc.
                                                            {
  static_assert(INTERCEPTOR == BEFORE_PROPERTY);
  switch (state_) {
    case NOT_FOUND:
      if (IsJSProxyMap(map)) {
        if (is_element || !name_->IsPrivate()) return JSPROXY;
      }
#if V8_ENABLE_WEBASSEMBLY
      if (IsWasmObjectMap(map)) return WASM_OBJECT;
#endif // V8_ENABLE_WEBASSEMBLY
      if (map->is_access_check_needed()) {
        if (is_element || !name_->IsPrivate() || name_->IsPrivateName())
          return ACCESS_CHECK;
      }
      [[fallthrough]];
    case ACCESS_CHECK:
      if (check_interceptor() && HasInterceptor<is_element>(map, index_) &&
          !SkipInterceptor<is_element>(Cast<JSObject>(holder))) {
        if (is_element || !name_->IsPrivate()) return INTERCEPTOR;
      }
      [[fallthrough]];
    case INTERCEPTOR:
      if (IsJSGlobalObjectMap(map) && !is_js_array_element(is_element)) {
        Tagged<GlobalDictionary> dict =
            Cast<JSGlobalObject>(holder)->global_dictionary(isolate_,
                                                            kAcquireLoad);
        number_ = dict->FindEntry(isolate(), name_);
        if (number_.is_not_found()) return NOT_FOUND;
        Tagged<PropertyCell> cell = dict->CellAt(isolate_, number_);
        if (IsPropertyCellHole(cell->value(isolate_), isolate_)) {
          return NOT_FOUND;
        }
        property_details_ = cell->property_details();
        has_property_ = true;
        switch (property_details_.kind()) {
          case v8::internal::PropertyKind::kData:
            return DATA;
          case v8::internal::PropertyKind::kAccessor:
            return ACCESSOR;
        }
      }
      return LookupInRegularHolder<is_element>(map, holder);
    case ACCESSOR:
    case DATA:
    case WASM_OBJECT:
      return NOT_FOUND;
    case TYPED_ARRAY_INDEX_NOT_FOUND:
    case JSPROXY:
    case TRANSITION:
    case STRING_LOOKUP_START_OBJECT:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References ACCESS_CHECK, ACCESSOR, BEFORE_PROPERTY, check_interceptor(), DATA, has_property_, index_, INTERCEPTOR, is_js_array_element(), v8::internal::InternalIndex::is_not_found(), isolate(), isolate_, JSPROXY, v8::internal::kAccessor, v8::kAcquireLoad, v8::internal::kData, v8::internal::PropertyDetails::kind(), name_, NOT_FOUND, number_, property_details_, state_, STRING_LOOKUP_START_OBJECT, TRANSITION, TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and WASM_OBJECT.
name()
DirectHandle< Name > v8::internal::LookupIterator::name () const [inline]
Definition at line 240 of file lookup-inl.h.
                                              {
  DCHECK_IMPLIES(holder_.is_null(), !IsElement());
  DCHECK_IMPLIES(!holder_.is_null(), !IsElement(*holder_));
  return name_;
}
References DCHECK_IMPLIES, holder_, IsElement(), and name_.
Referenced by ApplyTransitionToDataProperty(), ComputeConfiguration(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), Delete(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::Object::GetProperty(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), InternalUpdateProtector(), IsPrivateName(), LookupCachedProperty(), LookupInRegularHolder(), PrepareForDataProperty(), PrepareTransitionToDataProperty(), ReconfigureDataProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), TransitionToAccessorProperty(), v8::internal::UnscopableLookup(), v8::internal::LoadIC::UpdateCaches(), UpdateProtector(), and WriteDataValue().
Next()
void v8::internal::LookupIterator::Next ()
Definition at line 75 of file lookup.cc.
                          {
  DCHECK_NE(JSPROXY, state_);
  DCHECK_NE(TRANSITION, state_);
  DCHECK_NE(NOT_FOUND, state_);
  DisallowGarbageCollection no_gc;
  has_property_ = false;
  Tagged<JSReceiver> holder = *holder_;
  Tagged<Map> map = holder->map(isolate_);
  if (IsSpecialReceiverMap(map)) {
    state_ = IsElement() ? LookupInSpecialHolder<true>(map, holder)
                         : LookupInSpecialHolder<false>(map, holder);
    if (IsFound()) return;
  }
  IsElement() ? NextInternal<true>(map, holder)
              : NextInternal<false>(map, holder);
}
References DCHECK_NE, has_property_, holder_, IsElement(), IsFound(), isolate_, v8::internal::IsSpecialReceiverMap(), JSPROXY, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, NOT_FOUND, state_, and TRANSITION.
Referenced by v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), v8::internal::JSReceiver::HasProperty(), v8::internal::LookupForRead(), v8::internal::StoreIC::LookupForWrite(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), v8::internal::Accessors::ReplaceAccessorWithDataProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSObject::SetAccessor(), v8::internal::Object::SetPropertyInternal(), and v8::internal::Object::SetSuperProperty().
NextHolder()
Tagged< JSReceiver > v8::internal::LookupIterator::NextHolder (Tagged< Map > map) [inline], [private]
Definition at line 1251 of file lookup.cc.
                                                             {
  DisallowGarbageCollection no_gc;
  if (map->prototype(isolate_) == ReadOnlyRoots(isolate_).null_value()) {
    return JSReceiver();
  }
  if (!check_prototype_chain() && !IsJSGlobalProxyMap(map)) {
    return JSReceiver();
  }
  return Cast<JSReceiver>(map->prototype(isolate_));
}
References check_prototype_chain(), isolate_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by NextInternal().
NextInternal()
template<bool is_element>
void v8::internal::LookupIterator::NextInternal (Tagged< Map > map, Tagged< JSReceiver > holder) [private]
Definition at line 96 of file lookup.cc.
                                                                            {
  do {
    Tagged<JSReceiver> maybe_holder = NextHolder(map);
    if (maybe_holder.is_null()) {
      if (interceptor_state_ == InterceptorState::kSkipNonMasking) {
        RestartLookupForNonMaskingInterceptors<is_element>();
        return;
      }
      state_ = NOT_FOUND;
      if (holder != *holder_) holder_ = direct_handle(holder, isolate_);
      return;
    }
    holder = maybe_holder;
    map = holder->map(isolate_);
    state_ = LookupInHolder<is_element>(map, holder);
  } while (!IsFound());
  holder_ = direct_handle(holder, isolate_);
}
References v8::internal::direct_handle(), holder_, interceptor_state_, v8::internal::Tagged< HeapObject >::is_null(), IsFound(), isolate_, kSkipNonMasking, NextHolder(), NOT_FOUND, and state_.
NotFound() [1/2]
void v8::internal::LookupIterator::NotFound () [inline]
Definition at line 181 of file lookup.h.
                  {
    has_property_ = false;
    state_ = NOT_FOUND;
  }
Referenced by v8::internal::JSReceiver::GetDataProperty(), v8::internal::Object::GetProperty(), LookupInRegularHolder(), and v8::internal::Object::SetPropertyInternal().
NotFound() [2/2]
LookupIterator::State v8::internal::LookupIterator::NotFound (Tagged< JSReceiver > const holder) const [private]
Definition at line 1262 of file lookup.cc.
                                           {
  if (!IsJSTypedArray(holder, isolate_)) return NOT_FOUND;
  if (IsElement()) return TYPED_ARRAY_INDEX_NOT_FOUND;
  if (!IsString(*name_, isolate_)) return NOT_FOUND;
  return IsSpecialIndex(Cast<String>(*name_)) ? TYPED_ARRAY_INDEX_NOT_FOUND
                                              : NOT_FOUND;
}
References IsElement(), isolate_, v8::internal::IsSpecialIndex(), name_, NOT_FOUND, and TYPED_ARRAY_INDEX_NOT_FOUND.
PrepareForDataProperty()
void v8::internal::LookupIterator::PrepareForDataProperty (DirectHandle< Object > value)
Definition at line 368 of file lookup.cc.
                                                                      {
  DCHECK(state_ == DATA || state_ == ACCESSOR);
  DCHECK(HolderIsReceiverOrHiddenPrototype());
  DCHECK(!IsWasmObject(*receiver_, isolate_));
  DirectHandle<JSReceiver> holder = GetHolder<JSReceiver>();
  // We are not interested in tracking constness of a JSProxy's direct
  // properties.
  DCHECK_IMPLIES(IsJSProxy(*holder, isolate_), name()->IsPrivate());
  if (IsJSProxy(*holder, isolate_)) return;
  if (IsElement(*holder)) {
    DirectHandle<JSObject> holder_obj = Cast<JSObject>(holder);
    ElementsKind kind = holder_obj->GetElementsKind(isolate_);
    ElementsKind to = Object::OptimalElementsKind(*value, isolate_);
    if (IsHoleyElementsKind(kind)) to = GetHoleyElementsKind(to);
    to = GetMoreGeneralElementsKind(kind, to);
    if (kind != to) {
      JSObject::TransitionElementsKind(isolate(), holder_obj, to);
    }
    // Copy the backing store if it is copy-on-write.
    if (IsSmiOrObjectElementsKind(to) || IsSealedElementsKind(to) ||
        IsNonextensibleElementsKind(to)) {
      JSObject::EnsureWritableFastElements(isolate(), holder_obj);
    }
    return;
  }
  if (IsJSGlobalObject(*holder, isolate_)) {
    DirectHandle<GlobalDictionary> dictionary(
        Cast<JSGlobalObject>(*holder)->global_dictionary(isolate_,
                                                         kAcquireLoad),
        isolate());
    DirectHandle<PropertyCell> cell(
        dictionary->CellAt(isolate_, dictionary_entry()), isolate());
    property_details_ = cell->property_details();
    PropertyCell::PrepareForAndSetValue(
        isolate(), dictionary, dictionary_entry(), value, property_details_);
    return;
  }
  PropertyConstness new_constness = PropertyConstness::kConst;
  if (constness() == PropertyConstness::kConst) {
    DCHECK_EQ(PropertyKind::kData, property_details_.kind());
    // Check that current value matches new value otherwise we should make
    // the property mutable.
    if (holder->HasFastProperties(isolate_)) {
      if (!CanStayConst(*value)) new_constness = PropertyConstness::kMutable;
    } else if (V8_DICT_PROPERTY_CONST_TRACKING_BOOL) {
      if (!DictCanStayConst(*value)) {
        property_details_ =
            property_details_.CopyWithConstness(PropertyConstness::kMutable);
        // We won't reach the map updating code after Map::Update below, because
        // that's only for the case that the existing map is a fast mode map.
        // Therefore, we need to perform the necessary updates to the property
        // details and the prototype validity cell directly.
        if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
          Tagged<SwissNameDictionary> dict =
              holder->property_dictionary_swiss();
          dict->DetailsAtPut(dictionary_entry(), property_details_);
        } else {
          Tagged<NameDictionary> dict = holder->property_dictionary();
          dict->DetailsAtPut(dictionary_entry(), property_details_);
        }
        Tagged<Map> old_map = holder->map(isolate_);
        if (old_map->is_prototype_map()) {
          JSObject::InvalidatePrototypeChains(old_map);
        }
      }
      return;
    }
  }
  if (!holder->HasFastProperties(isolate_)) return;
  auto holder_obj = Cast<JSObject>(holder);
  Handle<Map> old_map(holder->map(isolate_), isolate_);
  DirectHandle<Map> new_map = Map::Update(isolate_, old_map);
  if (!new_map->is_dictionary_map()) { // fast -> fast
    new_map = Map::PrepareForDataProperty(
        isolate(), new_map, descriptor_number(), new_constness, value);
    if (old_map.is_identical_to(new_map)) {
      // Update the property details if the representation was None.
      if (constness() != new_constness || representation().IsNone()) {
        property_details_ = new_map->instance_descriptors(isolate_)->GetDetails(
            descriptor_number());
      }
      return;
    }
  }
  // We should only get here if the new_map is different from the old map,
  // otherwise we would have fallen through to the is_identical_to check above.
  DCHECK_NE(*old_map, *new_map);
  JSObject::MigrateToMap(isolate_, holder_obj, new_map);
  ReloadPropertyInformation<false>();
  // If we transitioned from fast to slow and the property changed from kConst
  // to kMutable, then this change in the constness is indicated by neither the
  // old or the new map. We need to update the constness ourselves.
  DCHECK(!old_map->is_dictionary_map());
  if (V8_DICT_PROPERTY_CONST_TRACKING_BOOL && new_map->is_dictionary_map() &&
      new_constness == PropertyConstness::kMutable) { // fast -> slow
    property_details_ =
        property_details_.CopyWithConstness(PropertyConstness::kMutable);
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      Tagged<SwissNameDictionary> dict =
          holder_obj->property_dictionary_swiss();
      dict->DetailsAtPut(dictionary_entry(), property_details_);
    } else {
      Tagged<NameDictionary> dict = holder_obj->property_dictionary();
      dict->DetailsAtPut(dictionary_entry(), property_details_);
    }
    DCHECK_IMPLIES(new_map->is_prototype_map(),
                   !new_map->IsPrototypeValidityCellValid());
  }
}
References ACCESSOR, CanStayConst(), constness(), v8::internal::PropertyDetails::CopyWithConstness(), DATA, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, descriptor_number(), DictCanStayConst(), dictionary_entry(), v8::internal::JSObject::EnsureWritableFastElements(), v8::internal::GetHoleyElementsKind(), v8::internal::GetMoreGeneralElementsKind(), HolderIsReceiverOrHiddenPrototype(), v8::internal::JSObject::InvalidatePrototypeChains(), v8::internal::HandleBase::is_identical_to(), IsElement(), v8::internal::IsHoleyElementsKind(), v8::internal::IsNone(), v8::internal::IsNonextensibleElementsKind(), isolate(), isolate_, v8::internal::IsSealedElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::IsWasmObject(), v8::kAcquireLoad, v8::internal::kConst, v8::internal::kData, v8::internal::PropertyDetails::kind(), v8::internal::kMutable, v8::internal::JSObject::MigrateToMap(), name(), v8::internal::Object::OptimalElementsKind(), v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::Map::PrepareForDataProperty(), property_details_, receiver_, representation(), state_, v8::internal::JSObject::TransitionElementsKind(), v8::internal::Map::Update(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by v8::internal::StoreIC::LookupForWrite(), and v8::internal::Object::SetDataProperty().
PrepareTransitionToDataProperty()
void v8::internal::LookupIterator::PrepareTransitionToDataProperty (DirectHandle< JSReceiver > receiver, DirectHandle< Object > value, PropertyAttributes attributes, StoreOrigin store_origin)
Definition at line 598 of file lookup.cc.
                                                             {
  DCHECK_IMPLIES(IsJSProxy(*receiver, isolate_), name()->IsPrivate());
  DCHECK_IMPLIES(!receiver.is_identical_to(GetStoreTarget<JSReceiver>()),
                 name()->IsPrivateName());
  DCHECK(!IsAlwaysSharedSpaceJSObject(*receiver));
  if (state_ == TRANSITION) return;
  if (!IsElement() && name()->IsPrivate()) {
    attributes = static_cast<PropertyAttributes>(attributes | DONT_ENUM);
  }
  DCHECK(state_ != LookupIterator::ACCESSOR ||
         IsAccessorInfo(*GetAccessors(), isolate_));
  DCHECK_NE(TYPED_ARRAY_INDEX_NOT_FOUND, state_);
  DCHECK(state_ == NOT_FOUND || !HolderIsReceiverOrHiddenPrototype());
  DirectHandle<Map> map(receiver->map(isolate_), isolate_);
  // Dictionary maps can always have additional data properties.
  if (map->is_dictionary_map()) {
    state_ = TRANSITION;
    if (IsJSGlobalObjectMap(*map)) {
      DCHECK(!IsTheHole(*value, isolate_));
      // Don't set enumeration index (it will be set during value store).
      property_details_ =
          PropertyDetails(PropertyKind::kData, attributes,
                          PropertyCell::InitialType(isolate_, *value));
      transition_ = isolate_->factory()->NewPropertyCell(
          name(), property_details_, value);
      has_property_ = true;
    } else {
      // Don't set enumeration index (it will be set during value store).
      property_details_ =
          PropertyDetails(PropertyKind::kData, attributes,
                          PropertyDetails::kConstIfDictConstnessTracking);
      transition_ = map;
    }
    return;
  }
  DirectHandle<Map> transition =
      Map::TransitionToDataProperty(isolate_, map, name_, value, attributes,
                                    PropertyConstness::kConst, store_origin);
  state_ = TRANSITION;
  transition_ = transition;
  if (transition->is_dictionary_map()) {
    DCHECK(!IsJSGlobalObjectMap(*transition));
    // Don't set enumeration index (it will be set during value store).
    property_details_ =
        PropertyDetails(PropertyKind::kData, attributes,
                        PropertyDetails::kConstIfDictConstnessTracking);
  } else {
    property_details_ = transition->GetLastDescriptorDetails(isolate_);
    has_property_ = true;
  }
}
References ACCESSOR, v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NE, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), GetAccessors(), has_property_, HolderIsReceiverOrHiddenPrototype(), v8::internal::PropertyCell::InitialType(), v8::internal::DirectHandle< T >::is_identical_to(), IsElement(), isolate_, IsPrivateName(), v8::internal::kConst, v8::internal::PropertyDetails::kConstIfDictConstnessTracking, v8::internal::kData, name(), name_, v8::internal::Factory::NewPropertyCell(), NOT_FOUND, property_details_, state_, TRANSITION, transition_, v8::internal::Map::TransitionToDataProperty(), TYPED_ARRAY_INDEX_NOT_FOUND, and v8::internal::value.
Referenced by v8::internal::StoreIC::LookupForWrite(), and v8::internal::Object::TransitionAndWriteDataProperty().
property_attributes()
PropertyAttributes v8::internal::LookupIterator::property_attributes () const [inline]
Definition at line 233 of file lookup.h.
                                                 {
    return property_details().attributes();
  }
Referenced by v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::internal::StoreIC::LookupForWrite(), v8::internal::anonymous_namespace{ic.cc}::MaybeCanCloneObjectForObjectAssign(), v8::internal::Accessors::ReplaceAccessorWithDataProperty(), and v8::internal::JSProxy::SetPrivateSymbol().
property_details()
PropertyDetails v8::internal::LookupIterator::property_details () const [inline]
Definition at line 229 of file lookup.h.
                                           {
    DCHECK(has_property_);
    return property_details_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::JSProxy::SetPrivateSymbol(), and TransitionToAccessorProperty().
RecheckTypedArrayBounds()
void v8::internal::LookupIterator::RecheckTypedArrayBounds ()
Definition at line 127 of file lookup.cc.
                                             {
  DCHECK(IsJSTypedArray(*holder_, isolate_));
  DCHECK_EQ(state_, TYPED_ARRAY_INDEX_NOT_FOUND);
  if (!IsElement(*holder_)) {
    // This happens when the index is not an allowed index.
    return;
  }
  Tagged<JSObject> js_object = Cast<JSObject>(*holder_);
  ElementsAccessor* accessor = js_object->GetElementsAccessor(isolate_);
  Tagged<FixedArrayBase> backing_store = js_object->elements(isolate_);
  number_ =
      accessor->GetEntryForIndex(isolate_, js_object, backing_store, index_);
  if (number_.is_not_found()) {
    // The state is already TYPED_ARRAY_INDEX_NOT_FOUND.
    return;
  }
  property_details_ = accessor->GetDetails(js_object, number_);
#ifdef DEBUG
  Tagged<Map> map = holder_->map(isolate_);
  DCHECK(!map->has_frozen_elements());
  DCHECK(!map->has_sealed_elements());
#endif // DEBUG
  has_property_ = true;
  DCHECK_EQ(property_details_.kind(), v8::internal::PropertyKind::kData);
  state_ = DATA;
}
References DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ElementsAccessor::GetDetails(), v8::internal::ElementsAccessor::GetEntryForIndex(), has_property_, holder_, index_, v8::internal::InternalIndex::is_not_found(), IsElement(), isolate_, v8::internal::kData, v8::internal::PropertyDetails::kind(), number_, property_details_, state_, and TYPED_ARRAY_INDEX_NOT_FOUND.
Referenced by v8::internal::Object::SetPropertyInternal().
ReconfigureDataProperty()
void v8::internal::LookupIterator::ReconfigureDataProperty (DirectHandle< Object > value, PropertyAttributes attributes)
Definition at line 494 of file lookup.cc.
                                                                            {
  DCHECK(state_ == DATA || state_ == ACCESSOR);
  DCHECK(HolderIsReceiverOrHiddenPrototype());
  DirectHandle<JSReceiver> holder = GetHolder<JSReceiver>();
  if (V8_UNLIKELY(IsWasmObject(*holder))) UNREACHABLE();
  // Property details can never change for private properties.
  if (IsJSProxy(*holder, isolate_)) {
    DCHECK(name()->IsPrivate());
    return;
  }
  DirectHandle<JSObject> holder_obj = Cast<JSObject>(holder);
  if (IsElement(*holder)) {
    DCHECK(!holder_obj->HasTypedArrayOrRabGsabTypedArrayElements(isolate_));
    DCHECK(attributes != NONE || !holder_obj->HasFastElements(isolate_));
    DirectHandle<FixedArrayBase> elements(holder_obj->elements(isolate_),
                                          isolate());
    holder_obj->GetElementsAccessor(isolate_)->Reconfigure(
        isolate_, holder_obj, elements, number_, value, attributes);
    ReloadPropertyInformation<true>();
  } else if (holder_obj->HasFastProperties(isolate_)) {
    DirectHandle<Map> old_map(holder_obj->map(isolate_), isolate_);
    // Force mutable to avoid changing constant value by reconfiguring
    // kData -> kAccessor -> kData.
    DirectHandle<Map> new_map = MapUpdater::ReconfigureExistingProperty(
        isolate_, old_map, descriptor_number(), i::PropertyKind::kData,
        attributes, PropertyConstness::kMutable);
    if (!new_map->is_dictionary_map()) {
      // Make sure that the data property has a compatible representation.
      // TODO(leszeks): Do this as part of ReconfigureExistingProperty.
      new_map =
          Map::PrepareForDataProperty(isolate(), new_map, descriptor_number(),
                                      PropertyConstness::kMutable, value);
    }
    JSObject::MigrateToMap(isolate_, holder_obj, new_map);
    ReloadPropertyInformation<false>();
  }
  if (!IsElement(*holder) && !holder_obj->HasFastProperties(isolate_)) {
    if (holder_obj->map(isolate_)->is_prototype_map() &&
        (((property_details_.attributes() & READ_ONLY) == 0 &&
          (attributes & READ_ONLY) != 0) ||
         (property_details_.attributes() & DONT_ENUM) !=
             (attributes & DONT_ENUM))) {
      // Invalidate prototype validity cell when a property is reconfigured
      // from writable to read-only as this may invalidate transitioning store
      // IC handlers.
      // Invalidate prototype validity cell when a property changes
      // enumerability to clear the prototype chain enum cache.
      JSObject::InvalidatePrototypeChains(holder->map(isolate_));
    }
    if (IsJSGlobalObject(*holder_obj, isolate_)) {
      PropertyDetails details(PropertyKind::kData, attributes,
                              PropertyCellType::kMutable);
      DirectHandle<GlobalDictionary> dictionary(
          Cast<JSGlobalObject>(*holder_obj)
              ->global_dictionary(isolate_, kAcquireLoad),
          isolate());
      DirectHandle<PropertyCell> cell = PropertyCell::PrepareForAndSetValue(
          isolate(), dictionary, dictionary_entry(), value, details);
      property_details_ = cell->property_details();
      DCHECK_EQ(cell->value(), *value);
    } else {
      PropertyDetails details(PropertyKind::kData, attributes,
                              PropertyConstness::kMutable);
      if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
        DirectHandle<SwissNameDictionary> dictionary(
            holder_obj->property_dictionary_swiss(isolate_), isolate());
        dictionary->ValueAtPut(dictionary_entry(), *value);
        dictionary->DetailsAtPut(dictionary_entry(), details);
        DCHECK_EQ(details.AsSmi(),
                  dictionary->DetailsAt(dictionary_entry()).AsSmi());
        property_details_ = details;
      } else {
        DirectHandle<NameDictionary> dictionary(
            holder_obj->property_dictionary(isolate_), isolate());
        PropertyDetails original_details =
            dictionary->DetailsAt(dictionary_entry());
        int enumeration_index = original_details.dictionary_index();
        DCHECK_GT(enumeration_index, 0);
        details = details.set_index(enumeration_index);
        dictionary->SetEntry(dictionary_entry(), *name(), *value, details);
        property_details_ = details;
      }
    }
    state_ = DATA;
  }
  WriteDataValue(value, true);
#if VERIFY_HEAP
  if (v8_flags.verify_heap) {
    holder->HeapObjectVerify(isolate());
  }
#endif
}
References ACCESSOR, v8::internal::PropertyDetails::AsSmi(), v8::internal::PropertyDetails::attributes(), DATA, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, descriptor_number(), dictionary_entry(), v8::internal::PropertyDetails::dictionary_index(), v8::internal::DONT_ENUM, HolderIsReceiverOrHiddenPrototype(), v8::internal::JSObject::InvalidatePrototypeChains(), IsElement(), isolate(), isolate_, v8::internal::IsWasmObject(), v8::kAcquireLoad, v8::internal::kData, v8::internal::kMutable, v8::internal::JSObject::MigrateToMap(), name(), v8::internal::NONE, number_, v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::Map::PrepareForDataProperty(), property_details_, v8::internal::READ_ONLY, v8::internal::MapUpdater::ReconfigureExistingProperty(), v8::internal::PropertyDetails::set_index(), state_, v8::internal::UNREACHABLE(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::internal::v8_flags, V8_UNLIKELY, v8::internal::value, and WriteDataValue().
Referenced by v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), and v8::internal::Accessors::ReplaceAccessorWithDataProperty().
ReloadPropertyInformation()
template<bool is_element>
void v8::internal::LookupIterator::ReloadPropertyInformation [private]
Definition at line 184 of file lookup.cc.
                                               {
  state_ = BEFORE_PROPERTY;
  interceptor_state_ = InterceptorState::kUninitialized;
  state_ = LookupInHolder<is_element>(holder_->map(isolate_), *holder_);
  DCHECK(IsFound() || !holder_->HasFastProperties(isolate_));
}
References BEFORE_PROPERTY, v8::internal::DCHECK(), holder_, interceptor_state_, IsFound(), isolate_, kUninitialized, and state_.
representation()
Representation v8::internal::LookupIterator::representation () const [inline]
Definition at line 239 of file lookup.h.
                                        {
    return property_details().representation();
  }
Referenced by v8::internal::StoreIC::ComputeHandler(), and PrepareForDataProperty().
Restart()
void v8::internal::LookupIterator::Restart () [inline]
Definition at line 146 of file lookup.h.
                 {
    InterceptorState state = InterceptorState::kUninitialized;
    IsElement() ? RestartInternal<true>(state) : RestartInternal<false>(state);
  }
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), LookupCachedProperty(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), v8::internal::Object::SetSuperProperty(), and v8::internal::StoreIC::Store().
RestartInternal()
template<bool is_element>
template void v8::internal::LookupIterator::RestartInternal< false > (InterceptorState interceptor_state) [private]
Definition at line 117 of file lookup.cc.
                                                                       {
  interceptor_state_ = interceptor_state;
  property_details_ = PropertyDetails::Empty();
  number_ = InternalIndex::NotFound();
  Start<is_element>();
}
References v8::internal::PropertyDetails::Empty(), interceptor_state_, v8::internal::InternalIndex::NotFound(), number_, and property_details_.
RestartLookupForNonMaskingInterceptors()
template<bool is_element>
void v8::internal::LookupIterator::RestartLookupForNonMaskingInterceptors () [inline], [private]
Definition at line 328 of file lookup.h.
                                                {
    RestartInternal<is_element>(InterceptorState::kProcessNonMasking);
  }
SkipInterceptor()
template<bool is_element>
bool v8::internal::LookupIterator::SkipInterceptor (Tagged< JSObject > holder) [private]
Definition at line 1231 of file lookup.cc.
                                                            {
  Tagged<InterceptorInfo> info = GetInterceptor<is_element>(holder);
  if (!is_element && IsSymbol(*name_, isolate_) &&
      !info->can_intercept_symbols()) {
    return true;
  }
  if (info->non_masking()) {
    switch (interceptor_state_) {
      case InterceptorState::kUninitialized:
        interceptor_state_ = InterceptorState::kSkipNonMasking;
        [[fallthrough]];
      case InterceptorState::kSkipNonMasking:
        return true;
      case InterceptorState::kProcessNonMasking:
        return false;
    }
  }
  return interceptor_state_ == InterceptorState::kProcessNonMasking;
}
References interceptor_state_, isolate_, kProcessNonMasking, kSkipNonMasking, kUninitialized, and name_.
Start() [1/2]
template<bool is_element>
template void v8::internal::LookupIterator::Start< false > ()
Definition at line 30 of file lookup.cc.
                           {
  DisallowGarbageCollection no_gc;
  if (V8_LIKELY(IsJSReceiver(*lookup_start_object_, isolate_))) {
    holder_ = Cast<JSReceiver>(lookup_start_object_);
  } else {
    // Strings are the only non-JSReceiver objects with properties (only
    // elements and 'length') directly on the wrapper. Inline the lookup
    // implementation here.
    if (IsString(*lookup_start_object_, isolate_) &&
        ((!is_element && *name_ == ReadOnlyRoots(isolate_).length_string()) ||
         (is_element &&
          index_ < static_cast<size_t>(
                       Cast<String>(*lookup_start_object_)->length())))) {
      has_property_ = true;
      state_ = STRING_LOOKUP_START_OBJECT;
      return;
    }
    if (!check_prototype_chain()) {
      // This is an attempt to perform an own property lookup on a
      // non-JSReceiver that doesn't have any properties.
      DCHECK(!IsJSReceiver(*lookup_start_object_));
      has_property_ = false;
      state_ = NOT_FOUND;
      return;
    }
    holder_ = direct_handle(GetRootForNonJSReceiver(), isolate_);
  }
  // This is a regular JSReceiver lookup.
  has_property_ = false;
  state_ = NOT_FOUND;
  Tagged<JSReceiver> holder = *holder_;
  Tagged<Map> map = holder->map(isolate_);
  state_ = LookupInHolder<is_element>(map, holder);
  if (IsFound()) return;
  NextInternal<is_element>(map, holder);
}
References check_prototype_chain(), v8::internal::DCHECK(), v8::internal::direct_handle(), GetRootForNonJSReceiver(), has_property_, holder_, index_, IsFound(), isolate_, lookup_start_object_, name_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, NOT_FOUND, state_, STRING_LOOKUP_START_OBJECT, and V8_LIKELY.
Start() [2/2]
template<bool is_element>
V8_EXPORT_PRIVATE void v8::internal::LookupIterator::Start () [private]
state()
State v8::internal::LookupIterator::state () const [inline]
Definition at line 156 of file lookup.h.
{ return state_; }
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::JSReceiver::AddPrivateField(), v8::internal::JSObject::AddProperty(), v8::internal::Object::CheckContextualStoreToJSGlobalObject(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal(), v8::internal::Runtime::DefineObjectOwnProperty(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::anonymous_namespace{json-stringifier.cc}::GetBuiltin(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::CallSiteInfo::GetMethodName(), v8::internal::anonymous_namespace{debug-property-iterator.cc}::GetNativeAccessorDescriptorInternal(), v8::internal::Runtime::GetObjectProperty(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::JSObject::GetPropertyWithInterceptor(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), v8::internal::JSReceiver::HasProperty(), v8::internal::JSArray::HasReadOnlyLengthSlowPath(), v8::internal::JSObject::HasRealNamedCallbackProperty(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl(), LookupCachedProperty(), v8::internal::LookupForRead(), v8::internal::StoreIC::LookupForWrite(), v8::internal::wasm::InstanceBuilder::LookupImportAsm(), v8::internal::anonymous_namespace{ic.cc}::MaybeCanCloneObjectForObjectAssign(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), v8::internal::PropertyAlreadyExists(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::Accessors::ReplaceAccessorWithDataProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSObject::SetAccessor(), v8::internal::Object::SetDataProperty(), v8::internal::JSProxy::SetPrivateSymbol(), v8::internal::SetPropertiesFromKeyValuePairs(), v8::internal::Object::SetPropertyInternal(), v8::internal::JSObject::SetPropertyWithInterceptor(), v8::internal::Object::SetSuperProperty(), v8::internal::StoreIC::Store(), v8::internal::Object::TransitionAndWriteDataProperty(), TransitionToAccessorProperty(), TryLookupCachedProperty(), v8::internal::LoadIC::UpdateCaches(), v8::internal::StoreIC::UpdateCaches(), and v8::internal::Object::WriteToReadOnlyProperty().
SwapDataValue()
DirectHandle< Object > v8::internal::LookupIterator::SwapDataValue (DirectHandle< Object > value, SeqCstAccessTag tag)
Definition at line 1184 of file lookup.cc.
                                                                        {
  DCHECK_EQ(DATA, state_);
  // Currently only shared structs and arrays support sequentially consistent
  // access.
  DCHECK(IsJSSharedStruct(*holder_, isolate_) ||
         IsJSSharedArray(*holder_, isolate_));
  DirectHandle<JSObject> holder = GetHolder<JSObject>();
  if (IsElement(*holder)) {
    ElementsAccessor* accessor = holder->GetElementsAccessor(isolate_);
    return accessor->SwapAtomic(isolate_, holder, number_, *value,
                                kSeqCstAccess);
  }
  DCHECK_EQ(PropertyLocation::kField, property_details_.location());
  DCHECK_EQ(PropertyKind::kData, property_details_.kind());
  DisallowGarbageCollection no_gc;
  FieldIndex field_index =
      FieldIndex::ForDescriptor(holder->map(isolate_), descriptor_number());
  return direct_handle(holder->RawFastPropertyAtSwap(field_index, *value, tag),
                       isolate_);
}
References DATA, v8::internal::DCHECK(), DCHECK_EQ, descriptor_number(), v8::internal::direct_handle(), v8::internal::FieldIndex::ForDescriptor(), holder_, IsElement(), isolate_, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::kSeqCstAccess, v8::internal::PropertyDetails::location(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, number_, property_details_, state_, v8::internal::ElementsAccessor::SwapAtomic(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
transition_cell()
DirectHandle< PropertyCell > v8::internal::LookupIterator::transition_cell () const [inline]
Definition at line 277 of file lookup-inl.h.
                                                                 {
  DCHECK_EQ(TRANSITION, state_);
  return Cast<PropertyCell>(transition_);
}
References DCHECK_EQ, state_, TRANSITION, and transition_.
Referenced by ApplyTransitionToDataProperty(), v8::internal::Object::CheckContextualStoreToJSGlobalObject(), and v8::internal::StoreIC::ComputeHandler().
transition_map()
DirectHandle< Map > v8::internal::LookupIterator::transition_map () const [inline]
Definition at line 272 of file lookup-inl.h.
                                                       {
  DCHECK_EQ(TRANSITION, state_);
  return Cast<Map>(transition_);
}
References DCHECK_EQ, state_, TRANSITION, and transition_.
Referenced by ApplyTransitionToDataProperty(), v8::internal::StoreIC::ComputeHandler(), and IsCacheableTransition().
TransitionToAccessorPair()
void v8::internal::LookupIterator::TransitionToAccessorPair (DirectHandle< Object > pair, PropertyAttributes attributes)
Definition at line 847 of file lookup.cc.
                                                                             {
  DirectHandle<JSObject> receiver = GetStoreTarget<JSObject>();
  holder_ = receiver;
  PropertyDetails details(PropertyKind::kAccessor, attributes,
                          PropertyCellType::kMutable);
  if (IsElement(*receiver)) {
    // TODO(verwaest): Move code into the element accessor.
    isolate_->CountUsage(v8::Isolate::kIndexAccessor);
    DirectHandle<NumberDictionary> dictionary =
        JSObject::NormalizeElements(isolate_, receiver);
    dictionary = NumberDictionary::Set(isolate_, dictionary, array_index(),
                                       pair, receiver, details);
    receiver->RequireSlowElements(*dictionary);
    if (receiver->HasSlowArgumentsElements(isolate_)) {
      Tagged<SloppyArgumentsElements> parameter_map =
          Cast<SloppyArgumentsElements>(receiver->elements(isolate_));
      uint32_t length = parameter_map->length();
      if (number_.is_found() && number_.as_uint32() < length) {
        parameter_map->set_mapped_entries(
            number_.as_int(), ReadOnlyRoots(isolate_).the_hole_value());
      }
      parameter_map->set_arguments(*dictionary);
    } else {
      receiver->set_elements(*dictionary);
    }
    ReloadPropertyInformation<true>();
  } else {
    PropertyNormalizationMode mode = CLEAR_INOBJECT_PROPERTIES;
    if (receiver->map(isolate_)->is_prototype_map()) {
      JSObject::InvalidatePrototypeChains(receiver->map(isolate_));
      mode = KEEP_INOBJECT_PROPERTIES;
    }
    // Normalize object to make this operation simple.
    JSObject::NormalizeProperties(isolate_, receiver, mode, 0,
                                  "TransitionToAccessorPair");
    JSObject::SetNormalizedProperty(receiver, name_, pair, details);
    JSObject::ReoptimizeIfPrototype(receiver);
    ReloadPropertyInformation<false>();
  }
}
References array_index(), v8::internal::InternalIndex::as_int(), v8::internal::InternalIndex::as_uint32(), v8::internal::CLEAR_INOBJECT_PROPERTIES, v8::internal::Isolate::CountUsage(), holder_, v8::internal::JSObject::InvalidatePrototypeChains(), v8::internal::InternalIndex::is_found(), IsElement(), isolate_, v8::internal::kAccessor, v8::internal::KEEP_INOBJECT_PROPERTIES, v8::Isolate::kIndexAccessor, v8::internal::kMutable, v8::internal::length, mode(), name_, v8::internal::JSObject::NormalizeElements(), v8::internal::JSObject::NormalizeProperties(), number_, v8::internal::JSObject::ReoptimizeIfPrototype(), and v8::internal::JSObject::SetNormalizedProperty().
Referenced by v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSObject::SetAccessor(), and TransitionToAccessorProperty().
TransitionToAccessorProperty()
void v8::internal::LookupIterator::TransitionToAccessorProperty (DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes)
Definition at line 778 of file lookup.cc.
                                   {
  DCHECK(!IsNull(*getter, isolate_) || !IsNull(*setter, isolate_));
  // Can only be called when the receiver is a JSObject. JSProxy has to be
  // handled via a trap. Adding properties to primitive values is not
  // observable.
  DirectHandle<JSObject> receiver = GetStoreTarget<JSObject>();
  if (!IsElement() && name()->IsPrivate()) {
    attributes = static_cast<PropertyAttributes>(attributes | DONT_ENUM);
  }
  if (!IsElement(*receiver) && !receiver->map(isolate_)->is_dictionary_map()) {
    DirectHandle<Map> old_map(receiver->map(isolate_), isolate_);
    if (!holder_.is_identical_to(receiver)) {
      holder_ = receiver;
      state_ = NOT_FOUND;
    } else if (state_ == INTERCEPTOR) {
      LookupInRegularHolder<false>(*old_map, *holder_);
    }
    // The case of IsFound() && number_.is_not_found() can occur for
    // interceptors.
    DCHECK_IMPLIES(!IsFound(), number_.is_not_found());
    DirectHandle<Map> new_map = Map::TransitionToAccessorProperty(
        isolate_, old_map, name_, number_, getter, setter, attributes);
    bool simple_transition =
        new_map->GetBackPointer(isolate_) == receiver->map(isolate_);
    JSObject::MigrateToMap(isolate_, receiver, new_map);
    if (simple_transition) {
      number_ = new_map->LastAdded();
      property_details_ = new_map->GetLastDescriptorDetails(isolate_);
      state_ = ACCESSOR;
      return;
    }
    ReloadPropertyInformation<false>();
    if (!new_map->is_dictionary_map()) return;
  }
  DirectHandle<AccessorPair> pair;
  if (state() == ACCESSOR && IsAccessorPair(*GetAccessors(), isolate_)) {
    pair = Cast<AccessorPair>(GetAccessors());
    // If the component and attributes are identical, nothing has to be done.
    if (pair->Equals(*getter, *setter)) {
      if (property_details().attributes() == attributes) {
        if (!IsElement(*receiver)) JSObject::ReoptimizeIfPrototype(receiver);
        return;
      }
    } else {
      pair = AccessorPair::Copy(isolate(), pair);
      pair->SetComponents(*getter, *setter);
    }
  } else {
    pair = factory()->NewAccessorPair();
    pair->SetComponents(*getter, *setter);
  }
  TransitionToAccessorPair(pair, attributes);
#if VERIFY_HEAP
  if (v8_flags.verify_heap) {
    receiver->JSObjectVerify(isolate());
  }
#endif
}
References ACCESSOR, v8::internal::AccessorPair::Copy(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::DONT_ENUM, factory(), GetAccessors(), holder_, INTERCEPTOR, v8::internal::InternalIndex::is_not_found(), IsElement(), IsFound(), v8::internal::IsNull(), isolate(), isolate_, v8::internal::JSObject::MigrateToMap(), name(), name_, v8::internal::FactoryBase< Impl >::NewAccessorPair(), NOT_FOUND, number_, property_details(), property_details_, v8::internal::JSObject::ReoptimizeIfPrototype(), v8::internal::setter, state(), state_, TransitionToAccessorPair(), v8::internal::Map::TransitionToAccessorProperty(), and v8::internal::v8_flags.
Referenced by v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes().
TryLookupCachedProperty() [1/2]
bool v8::internal::LookupIterator::TryLookupCachedProperty ()
Definition at line 1460 of file lookup.cc.
                                             {
  if (state() != LookupIterator::ACCESSOR) return false;
  DirectHandle<Object> accessor_pair = GetAccessors();
  return IsAccessorPair(*accessor_pair, isolate_) &&
         LookupCachedProperty(Cast<AccessorPair>(accessor_pair));
}
References ACCESSOR, GetAccessors(), isolate_, LookupCachedProperty(), and state().
TryLookupCachedProperty() [2/2]
bool v8::internal::LookupIterator::TryLookupCachedProperty (DirectHandle< AccessorPair > accessor)
Definition at line 1454 of file lookup.cc.
                                         {
  DCHECK_EQ(state(), LookupIterator::ACCESSOR);
  return LookupCachedProperty(accessor);
}
References ACCESSOR, DCHECK_EQ, LookupCachedProperty(), and state().
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::Object::GetPropertyWithAccessor(), and v8::internal::LoadIC::UpdateCaches().
UpdateProtector() [1/2]
void v8::internal::LookupIterator::UpdateProtector () [inline]
Definition at line 358 of file lookup-inl.h.
                                     {
  if (IsElement()) return;
  UpdateProtector(isolate_, receiver_, name_);
}
References IsElement(), isolate_, name_, and receiver_.
Referenced by v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetSuperProperty(), v8::internal::Object::TransitionAndWriteDataProperty(), and v8::internal::anonymous_namespace{runtime-classes.cc}::UpdateProtectors().
UpdateProtector() [2/2]
void v8::internal::LookupIterator::UpdateProtector (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< Name > name) [inline], [static]
Definition at line 330 of file lookup-inl.h.
                                                              {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kUpdateProtector);
  DCHECK(IsInternalizedString(*name) || IsSymbol(*name));
  // This check must be kept in sync with
  // CodeStubAssembler::CheckForAssociatedProtector!
  ReadOnlyRoots roots(isolate);
  bool maybe_protector = roots.IsNameForProtector(*name);
#if DEBUG
  bool debug_maybe_protector =
      *name == roots.constructor_string() || *name == roots.next_string() ||
      *name == roots.resolve_string() || *name == roots.then_string() ||
      *name == roots.is_concat_spreadable_symbol() ||
      *name == roots.iterator_symbol() || *name == roots.species_symbol() ||
      *name == roots.match_all_symbol() || *name == roots.replace_symbol() ||
      *name == roots.split_symbol() || *name == roots.to_primitive_symbol() ||
      *name == roots.valueOf_string();
  DCHECK_EQ(maybe_protector, debug_maybe_protector);
#endif // DEBUG
  if (maybe_protector) {
    InternalUpdateProtector(isolate, receiver, name);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, InternalUpdateProtector(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::ReadOnlyRoots::IsNameForProtector(), isolate(), name(), and RCS_SCOPE.
WriteDataValue() [1/2]
void v8::internal::LookupIterator::WriteDataValue (DirectHandle< Object > value, bool initializing_store)
Definition at line 1104 of file lookup.cc.
                                                             {
  DCHECK_EQ(DATA, state_);
  // WriteDataValueToWasmObject() must be used instead for writing to
  // WasmObjects.
  DCHECK(!IsWasmObject(*holder_, isolate_));
  DCHECK_IMPLIES(IsJSSharedStruct(*holder_), IsShared(*value));
  DirectHandle<JSReceiver> holder = GetHolder<JSReceiver>();
  if (IsElement(*holder)) {
    DirectHandle<JSObject> object = Cast<JSObject>(holder);
    ElementsAccessor* accessor = object->GetElementsAccessor(isolate_);
    accessor->Set(object, number_, *value);
  } else if (holder->HasFastProperties(isolate_)) {
    DCHECK(IsJSObject(*holder, isolate_));
    if (property_details_.location() == PropertyLocation::kField) {
      // Check that in case of VariableMode::kConst field the existing value is
      // equal to |value|.
      DCHECK_IMPLIES(!initializing_store && property_details_.constness() ==
                                                PropertyConstness::kConst,
                     CanStayConst(*value));
      Cast<JSObject>(*holder)->WriteToField(descriptor_number(),
                                            property_details_, *value);
    } else {
      DCHECK_EQ(PropertyLocation::kDescriptor, property_details_.location());
      DCHECK_EQ(PropertyConstness::kConst, property_details_.constness());
    }
  } else if (IsJSGlobalObject(*holder, isolate_)) {
    // PropertyCell::PrepareForAndSetValue already wrote the value into the
    // cell.
#ifdef DEBUG
    Tagged<GlobalDictionary> dictionary =
        Cast<JSGlobalObject>(*holder)->global_dictionary(isolate_,
                                                         kAcquireLoad);
    Tagged<PropertyCell> cell =
        dictionary->CellAt(isolate_, dictionary_entry());
    DCHECK(cell->value() == *value ||
           (IsString(cell->value()) && IsString(*value) &&
            Cast<String>(cell->value())->Equals(Cast<String>(*value))));
#endif // DEBUG
  } else {
    DCHECK_IMPLIES(IsJSProxy(*holder, isolate_), name()->IsPrivate());
    // Check similar to fast mode case above.
    DCHECK_IMPLIES(
        V8_DICT_PROPERTY_CONST_TRACKING_BOOL && !initializing_store &&
            property_details_.constness() == PropertyConstness::kConst,
        IsJSProxy(*holder, isolate_) || DictCanStayConst(*value));
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      Tagged<SwissNameDictionary> dictionary =
          holder->property_dictionary_swiss(isolate_);
      dictionary->ValueAtPut(dictionary_entry(), *value);
    } else {
      Tagged<NameDictionary> dictionary = holder->property_dictionary(isolate_);
      dictionary->ValueAtPut(dictionary_entry(), *value);
    }
  }
}
References CanStayConst(), v8::internal::PropertyDetails::constness(), DATA, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, descriptor_number(), DictCanStayConst(), dictionary_entry(), holder_, IsElement(), isolate_, v8::internal::IsShared(), v8::internal::IsWasmObject(), v8::kAcquireLoad, v8::internal::kConst, v8::internal::kDescriptor, v8::internal::kField, v8::internal::PropertyDetails::location(), name(), number_, property_details_, v8::internal::ElementsAccessor::Set(), state_, V8_DICT_PROPERTY_CONST_TRACKING_BOOL, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by ReconfigureDataProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Object::SetDataProperty(), v8::internal::JSProxy::SetPrivateSymbol(), and v8::internal::Object::TransitionAndWriteDataProperty().
WriteDataValue() [2/2]
void v8::internal::LookupIterator::WriteDataValue (DirectHandle< Object > value, SeqCstAccessTag tag)
Definition at line 1163 of file lookup.cc.
                                                         {
  DCHECK_EQ(DATA, state_);
  // Currently only shared structs and arrays support sequentially consistent
  // access.
  DCHECK(IsJSSharedStruct(*holder_, isolate_) ||
         IsJSSharedArray(*holder_, isolate_));
  DirectHandle<JSObject> holder = GetHolder<JSObject>();
  if (IsElement(*holder)) {
    ElementsAccessor* accessor = holder->GetElementsAccessor(isolate_);
    accessor->SetAtomic(holder, number_, *value, kSeqCstAccess);
    return;
  }
  DCHECK_EQ(PropertyLocation::kField, property_details_.location());
  DCHECK_EQ(PropertyKind::kData, property_details_.kind());
  DisallowGarbageCollection no_gc;
  FieldIndex field_index =
      FieldIndex::ForDescriptor(holder->map(isolate_), descriptor_number());
  holder->FastPropertyAtPut(field_index, *value, tag);
}
References DATA, v8::internal::DCHECK(), DCHECK_EQ, descriptor_number(), v8::internal::FieldIndex::ForDescriptor(), holder_, IsElement(), isolate_, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::kSeqCstAccess, v8::internal::PropertyDetails::location(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, number_, property_details_, v8::internal::ElementsAccessor::SetAtomic(), state_, and v8::internal::value.
Member Data Documentation
configuration_
const Configuration v8::internal::LookupIterator::configuration_ [private]
Definition at line 363 of file lookup.h.
Referenced by ApplyTransitionToDataProperty().
has_property_
bool v8::internal::LookupIterator::has_property_ = false [private]
Definition at line 365 of file lookup.h.
Referenced by ApplyTransitionToDataProperty(), descriptor_number(), dictionary_entry(), GetAccessorIndex(), GetFieldDescriptorIndex(), GetFieldIndex(), HolderIsReceiver(), HolderIsReceiverOrHiddenPrototype(), LookupInRegularHolder(), LookupInSpecialHolder(), Next(), PrepareTransitionToDataProperty(), RecheckTypedArrayBounds(), and Start().
holder_
DirectHandle<JSReceiver> v8::internal::LookupIterator::holder_ [private]
Definition at line 372 of file lookup.h.
Referenced by ApplyTransitionToDataProperty(), CanStayConst(), CompareAndSwapDataValue(), Delete(), descriptor_number(), DictCanStayConst(), dictionary_entry(), FetchValue(), GetAccessorIndex(), GetDataValue(), GetFieldDescriptorIndex(), GetFieldIndex(), GetHolder(), GetInterceptor(), GetInterceptorForFailedAccessCheck(), GetPropertyCell(), HolderIsReceiver(), HolderIsReceiverOrHiddenPrototype(), is_dictionary_holder(), LookupCachedProperty(), name(), Next(), NextInternal(), RecheckTypedArrayBounds(), ReloadPropertyInformation(), Start(), SwapDataValue(), TransitionToAccessorPair(), TransitionToAccessorProperty(), and WriteDataValue().
index_
const size_t v8::internal::LookupIterator::index_ [private]
Definition at line 374 of file lookup.h.
Referenced by GetInterceptor(), GetKey(), GetName(), GetStringPropertyValue(), IsElement(), LookupInRegularHolder(), LookupInSpecialHolder(), LookupIterator(), RecheckTypedArrayBounds(), and Start().
interceptor_state_
InterceptorState v8::internal::LookupIterator::interceptor_state_ = InterceptorState::kUninitialized [private]
Definition at line 366 of file lookup.h.
Referenced by LookupInRegularHolder(), NextInternal(), ReloadPropertyInformation(), RestartInternal(), and SkipInterceptor().
isolate_
Isolate* const v8::internal::LookupIterator::isolate_ [private]
Definition at line 368 of file lookup.h.
Referenced by ApplyTransitionToDataProperty(), CanStayConst(), CompareAndSwapDataValue(), Delete(), descriptor_number(), DictCanStayConst(), dictionary_entry(), ExtendingNonExtensible(), FetchValue(), GetAccessorIndex(), GetDataValue(), GetFieldIndex(), GetInterceptor(), GetInterceptorForFailedAccessCheck(), GetKey(), GetPropertyCell(), GetReceiverMap(), GetRootForNonJSReceiver(), GetStoreTarget(), GetStringPropertyValue(), HasAccess(), HolderIsReceiverOrHiddenPrototype(), is_dictionary_holder(), IsCacheableTransition(), LookupCachedProperty(), LookupInRegularHolder(), LookupInSpecialHolder(), LookupIterator(), Next(), NextHolder(), NextInternal(), NotFound(), PrepareForDataProperty(), PrepareTransitionToDataProperty(), RecheckTypedArrayBounds(), ReconfigureDataProperty(), ReloadPropertyInformation(), SkipInterceptor(), Start(), SwapDataValue(), TransitionToAccessorPair(), TransitionToAccessorProperty(), TryLookupCachedProperty(), UpdateProtector(), and WriteDataValue().
kInvalidIndex
const size_t v8::internal::LookupIterator::kInvalidIndex = std::numeric_limits<size_t>::max() [static], [private]
Definition at line 282 of file lookup.h.
Referenced by v8::internal::PropertyKey::is_element(), IsElement(), LookupIterator(), v8::internal::PropertyKey::PropertyKey(), and v8::internal::requires().
lookup_start_object_
const DirectHandle<JSAny> v8::internal::LookupIterator::lookup_start_object_ [private]
Definition at line 373 of file lookup.h.
Referenced by GetRootForNonJSReceiver(), GetStringPropertyValue(), LookupCachedProperty(), and Start().
name_
DirectHandle<Name> v8::internal::LookupIterator::name_ [private]
Definition at line 369 of file lookup.h.
Referenced by ExtendingNonExtensible(), GetKey(), GetName(), GetStringPropertyValue(), LookupCachedProperty(), LookupInRegularHolder(), LookupInSpecialHolder(), LookupIterator(), name(), NotFound(), PrepareTransitionToDataProperty(), SkipInterceptor(), Start(), TransitionToAccessorPair(), TransitionToAccessorProperty(), and UpdateProtector().
number_
InternalIndex v8::internal::LookupIterator::number_ = InternalIndex::NotFound() [private]
Definition at line 375 of file lookup.h.
Referenced by ApplyTransitionToDataProperty(), CompareAndSwapDataValue(), Delete(), descriptor_number(), dictionary_entry(), FetchValue(), GetDataValue(), LookupInRegularHolder(), LookupInSpecialHolder(), RecheckTypedArrayBounds(), ReconfigureDataProperty(), RestartInternal(), SwapDataValue(), TransitionToAccessorPair(), TransitionToAccessorProperty(), and WriteDataValue().
property_details_
PropertyDetails v8::internal::LookupIterator::property_details_ = PropertyDetails::Empty() [private]
Definition at line 367 of file lookup.h.
Referenced by ApplyTransitionToDataProperty(), CanStayConst(), CompareAndSwapDataValue(), DictCanStayConst(), FetchValue(), GetAccessorIndex(), GetDataValue(), GetFieldDescriptorIndex(), GetFieldIndex(), LookupInRegularHolder(), LookupInSpecialHolder(), PrepareForDataProperty(), PrepareTransitionToDataProperty(), RecheckTypedArrayBounds(), ReconfigureDataProperty(), RestartInternal(), SwapDataValue(), TransitionToAccessorProperty(), and WriteDataValue().
PropertyKey
friend v8::internal::LookupIterator::PropertyKey [private]
Definition at line 280 of file lookup.h.
Referenced by GetKey().
receiver_
const DirectHandle<JSAny> v8::internal::LookupIterator::receiver_ [private]
Definition at line 371 of file lookup.h.
Referenced by GetReceiverMap(), GetStoreTarget(), HolderIsReceiver(), HolderIsReceiverOrHiddenPrototype(), LookupCachedProperty(), PrepareForDataProperty(), and UpdateProtector().
state_
State v8::internal::LookupIterator::state_ = NOT_FOUND [private]
Definition at line 364 of file lookup.h.
Referenced by ApplyTransitionToDataProperty(), CompareAndSwapDataValue(), Delete(), FetchValue(), GetAccessors(), GetDataValue(), GetHolder(), GetInterceptor(), GetInterceptorForFailedAccessCheck(), GetStringPropertyValue(), HasAccess(), HolderIsReceiver(), HolderIsReceiverOrHiddenPrototype(), IsCacheableTransition(), LookupInSpecialHolder(), Next(), NextInternal(), PrepareForDataProperty(), PrepareTransitionToDataProperty(), RecheckTypedArrayBounds(), ReconfigureDataProperty(), ReloadPropertyInformation(), Start(), SwapDataValue(), transition_cell(), transition_map(), TransitionToAccessorProperty(), and WriteDataValue().
transition_
DirectHandle<UnionOf<Map, PropertyCell> > v8::internal::LookupIterator::transition_ [private]
Definition at line 370 of file lookup.h.
Referenced by IsCacheableTransition(), PrepareTransitionToDataProperty(), transition_cell(), and transition_map().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/lookup.h
/mnt/V8SourceCode/src/objects/lookup-inl.h
/mnt/V8SourceCode/src/objects/lookup.cc