v8::internal::maglev::Float64Round Class Reference
#include <maglev-ir.h>
Public Types
enum class Kind { kFloor
, kCeil
, kNearest
 }
Public Member Functions
Float64Round (uint64_t bitfield, Kind kind)
Input & input ()
Kind kind () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Member Functions
static Builtin continuation (Kind kind)
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::Float64()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kHoleyFloat64}
Private Types
using Base = FixedInputValueNodeT< 1, Float64Round >
Private Attributes
Kind kind_
Additional Inherited Members
Detailed Description
Definition at line 4506 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Float64Round::Base = FixedInputValueNodeT<1, Float64Round> [private]
Definition at line 4507 of file maglev-ir.h.
Member Enumeration Documentation
Kind
enum v8::internal::maglev::Float64Round::Kind [strong]
Enumerator
kFloor
kCeil
kNearest
Definition at line 4510 of file maglev-ir.h.
{ kFloor, kCeil, kNearest };
Constructor & Destructor Documentation
Float64Round()
v8::internal::maglev::Float64Round::Float64Round (uint64_t bitfield, Kind kind) [inline]
Definition at line 4523 of file maglev-ir.h.
: Base(bitfield), kind_(kind) {}
Member Function Documentation
continuation()
static Builtin v8::internal::maglev::Float64Round::continuation (Kind kind) [inline], [static]
Definition at line 4512 of file maglev-ir.h.
                                         {
    switch (kind) {
      case Kind::kCeil:
        return Builtin::kMathCeilContinuation;
      case Kind::kFloor:
        return Builtin::kMathFloorContinuation;
      case Kind::kNearest:
        return Builtin::kMathRoundContinuation;
    }
  }
References kCeil, kFloor, kind(), and kNearest.
GenerateCode()
void v8::internal::maglev::Float64Round::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 649 of file maglev-ir-arm.cc.
                                                              {
  DoubleRegister in = ToDoubleRegister(input());
  DoubleRegister out = ToDoubleRegister(result());
  CpuFeatureScope scope(masm, ARMv8);
  if (kind_ == Kind::kNearest) {
    MaglevAssembler::TemporaryRegisterScope temps(masm);
    DoubleRegister temp = temps.AcquireDouble();
    __ Move(temp, in);
    // vrintn rounds to even on tie, while JS expects it to round towards
    // +Infinity. Fix the difference by checking if we rounded down by exactly
    // 0.5, and if so, round to the other side.
    __ vrintn(out, in);
    __ vsub(temp, temp, out);
    DoubleRegister half_one = temps.AcquireScratchDouble();
    __ Move(half_one, 0.5);
    __ VFPCompareAndSetFlags(temp, half_one);
    Label done;
    __ JumpIf(ne, &done, Label::kNear);
    // Fix wrong tie-to-even by adding 0.5 twice.
    __ vadd(out, out, half_one);
    __ vadd(out, out, half_one);
    __ bind(&done);
  } else if (kind_ == Kind::kCeil) {
    __ vrintp(out, in);
  } else if (kind_ == Kind::kFloor) {
    __ vrintm(out, in);
input()
Input& v8::internal::maglev::Float64Round::input () [inline]
Definition at line 4529 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
kind()
Kind v8::internal::maglev::Float64Round::kind () const [inline]
Definition at line 4530 of file maglev-ir.h.
{ return kind_; }
References kind_.
Referenced by continuation().
options()
auto v8::internal::maglev::Float64Round::options () const [inline]
Definition at line 4536 of file maglev-ir.h.
{ return std::tuple{kind_}; }
References kind_.
PrintParams()
void v8::internal::maglev::Float64Round::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8349 of file maglev-ir.cc.
                                                                          {
  switch (kind_) {
    case Kind::kCeil:
      os << "(ceil)";
      return;
    case Kind::kFloor:
      os << "(floor)";
      return;
    case Kind::kNearest:
      os << "(nearest)";
      return;
  }
}
References kCeil, kFloor, kind_, and kNearest.
SetValueLocationConstraints()
void v8::internal::maglev::Float64Round::SetValueLocationConstraints ()
Member Data Documentation
kind_
Kind v8::internal::maglev::Float64Round::kind_ [private]
Definition at line 4539 of file maglev-ir.h.
Referenced by kind(), options(), and PrintParams().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::Float64Round::kInputTypes {ValueRepresentation::kHoleyFloat64} [static], [constexpr]
Definition at line 4527 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::Float64Round::kProperties = OpProperties::Float64() [static], [constexpr]
Definition at line 4525 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/maglev-ir.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc