v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands Class Reference
Classes
struct Entry
Public Member Functions
DeferredCommands (BytecodeGenerator *generator, Register token_register, Register result_register, Register message_register)
void RecordCommand (Command command, Statement *statement)
void RecordHandlerReThrowPath ()
void RecordFallThroughPath ()
void ApplyDeferredCommand (const Entry &entry)
void ApplyDeferredCommands ()
BytecodeArrayBuilder * builder ()
ControlScope * execution_control ()
Private Member Functions
int GetTokenForCommand (Command command, Statement *statement)
int GetReturnToken ()
int GetAsyncReturnToken ()
int GetNewTokenForCommand (Command command, Statement *statement)
Private Attributes
BytecodeGenerator * generator_
ZoneVector< Entry > deferred_
Register token_register_
Register result_register_
Register message_register_
int return_token_
int async_return_token_
bool fallthrough_from_try_block_needed_
Detailed Description
Definition at line 183 of file bytecode-generator.cc.
Constructor & Destructor Documentation
DeferredCommands()
v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::DeferredCommands (BytecodeGenerator * generator, Register token_register, Register result_register, Register message_register) [inline]
Definition at line 185 of file bytecode-generator.cc.
      : generator_(generator),
        deferred_(generator->zone()),
        token_register_(token_register),
        result_register_(result_register),
        message_register_(message_register),
        return_token_(-1),
        async_return_token_(-1),
        fallthrough_from_try_block_needed_(false) {
    // There's always a rethrow path.
    // TODO(leszeks): We could decouple deferred_ index and token to allow us
    // to still push this lazily.
    static_assert(
        static_cast<int>(TryFinallyContinuationToken::kRethrowToken) == 0);
    deferred_.push_back(
        {CMD_RETHROW, nullptr,
         static_cast<int>(TryFinallyContinuationToken::kRethrowToken)});
  }
References v8::internal::interpreter::kRethrowToken.
Member Function Documentation
ApplyDeferredCommand()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::ApplyDeferredCommand (const Entry & entry) [inline]
Definition at line 265 of file bytecode-generator.cc.
                                                {
    if (entry.command == CMD_RETHROW) {
      // Pending message object is restored on exit.
      builder()
          ->LoadAccumulatorWithRegister(message_register_)
          .SetPendingMessage();
    }
    if (CommandUsesAccumulator(entry.command)) {
      builder()->LoadAccumulatorWithRegister(result_register_);
    }
    execution_control()->PerformCommand(entry.command, entry.statement,
                                        kNoSourcePosition);
  }
References v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::Entry::command, v8::internal::kNoSourcePosition, and v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::Entry::statement.
ApplyDeferredCommands()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::ApplyDeferredCommands () [inline]
Definition at line 282 of file bytecode-generator.cc.
                               {
    if (deferred_.empty()) return;
    BytecodeLabel fall_through_from_try_block;
    if (deferred_.size() == 1) {
      // For a single entry, just jump to the fallthrough if we don't match the
      // entry token.
      const Entry& entry = deferred_[0];
      if (fallthrough_from_try_block_needed_) {
        builder()
            ->LoadLiteral(Smi::FromInt(entry.token))
            .CompareReference(token_register_)
            .JumpIfFalse(ToBooleanMode::kAlreadyBoolean,
                         &fall_through_from_try_block);
      }
      ApplyDeferredCommand(entry);
    } else {
      // For multiple entries, build a jump table and switch on the token,
      // jumping to the fallthrough if none of them match.
      //
      // If fallthrough from the try block is not needed, generate a jump table
      // with one (1) fewer entries and reuse the fallthrough path for the final
      // entry.
      const int jump_table_base_value =
          fallthrough_from_try_block_needed_ ? 0 : 1;
      const int jump_table_size =
          static_cast<int>(deferred_.size() - jump_table_base_value);
      if (jump_table_size == 1) {
        DCHECK_EQ(2, deferred_.size());
        BytecodeLabel fall_through_to_final_entry;
        const Entry& first_entry = deferred_[0];
        const Entry& final_entry = deferred_[1];
        builder()
            ->LoadLiteral(Smi::FromInt(first_entry.token))
            .CompareReference(token_register_)
            .JumpIfFalse(ToBooleanMode::kAlreadyBoolean,
                         &fall_through_to_final_entry);
        ApplyDeferredCommand(first_entry);
        builder()->Bind(&fall_through_to_final_entry);
        ApplyDeferredCommand(final_entry);
      } else {
        BytecodeJumpTable* jump_table = builder()->AllocateJumpTable(
            jump_table_size, jump_table_base_value);
        builder()
            ->LoadAccumulatorWithRegister(token_register_)
            .SwitchOnSmiNoFeedback(jump_table);
        const Entry& first_entry = deferred_.front();
        if (fallthrough_from_try_block_needed_) {
          builder()->Jump(&fall_through_from_try_block);
          builder()->Bind(jump_table, first_entry.token);
        }
        ApplyDeferredCommand(first_entry);
        for (const Entry& entry : base::IterateWithoutFirst(deferred_)) {
          builder()->Bind(jump_table, entry.token);
          ApplyDeferredCommand(entry);
        }
      }
    }
    if (fallthrough_from_try_block_needed_) {
      builder()->Bind(&fall_through_from_try_block);
    }
  }
References DCHECK_EQ, v8::internal::Smi::FromInt(), v8::base::IterateWithoutFirst(), and v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::Entry::token.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally().
builder()
BytecodeArrayBuilder* v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::builder () [inline]
Definition at line 352 of file bytecode-generator.cc.
{ return generator_->builder(); }
execution_control()
ControlScope* v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::execution_control () [inline]
Definition at line 353 of file bytecode-generator.cc.
{ return generator_->execution_control(); }
GetAsyncReturnToken()
int v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::GetAsyncReturnToken () [inline], [private]
Definition at line 378 of file bytecode-generator.cc.
                            {
    if (async_return_token_ == -1) {
      async_return_token_ = GetNewTokenForCommand(CMD_ASYNC_RETURN, nullptr);
    }
    return async_return_token_;
  }
GetNewTokenForCommand()
int v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::GetNewTokenForCommand (Command command, Statement * statement) [inline], [private]
Definition at line 385 of file bytecode-generator.cc.
                                                                   {
    int token = static_cast<int>(deferred_.size());
    deferred_.push_back({command, statement, token});
    return token;
  }
GetReturnToken()
int v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::GetReturnToken () [inline], [private]
Definition at line 371 of file bytecode-generator.cc.
                       {
    if (return_token_ == -1) {
      return_token_ = GetNewTokenForCommand(CMD_RETURN, nullptr);
    }
    return return_token_;
  }
GetTokenForCommand()
int v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::GetTokenForCommand (Command command, Statement * statement) [inline], [private]
Definition at line 356 of file bytecode-generator.cc.
                                                                {
    switch (command) {
      case CMD_RETURN:
        return GetReturnToken();
      case CMD_ASYNC_RETURN:
        return GetAsyncReturnToken();
      case CMD_RETHROW:
        return static_cast<int>(TryFinallyContinuationToken::kRethrowToken);
      default:
        // TODO(leszeks): We could also search for entries with the same
        // command and statement.
        return GetNewTokenForCommand(command, statement);
    }
  }
References v8::internal::interpreter::kRethrowToken.
RecordCommand()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::RecordCommand (Command command, Statement * statement) [inline]
Definition at line 215 of file bytecode-generator.cc.
                                                            {
    int token = GetTokenForCommand(command, statement);
    DCHECK_LT(token, deferred_.size());
    DCHECK_EQ(deferred_[token].command, command);
    DCHECK_EQ(deferred_[token].statement, statement);
    DCHECK_EQ(deferred_[token].token, token);
    if (CommandUsesAccumulator(command)) {
      builder()->StoreAccumulatorInRegister(result_register_);
    }
    builder()->LoadLiteral(Smi::FromInt(token));
    builder()->StoreAccumulatorInRegister(token_register_);
    if (!CommandUsesAccumulator(command)) {
      // If we're not saving the accumulator in the result register, shove a
      // harmless value there instead so that it is still considered "killed" in
      // the liveness analysis. Normally we would LdaUndefined first, but the
      // Smi token value is just as good, and by reusing it we save a bytecode.
      builder()->StoreAccumulatorInRegister(result_register_);
    }
    if (command == CMD_RETHROW) {
      // Clear message object as we enter the catch block. It will be restored
      // if we rethrow.
      builder()->LoadTheHole().SetPendingMessage().StoreAccumulatorInRegister(
          message_register_);
    }
  }
References DCHECK_EQ, DCHECK_LT, and v8::internal::Smi::FromInt().
Referenced by v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally::Execute().
RecordFallThroughPath()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::RecordFallThroughPath () [inline]
Definition at line 253 of file bytecode-generator.cc.
                               {
    fallthrough_from_try_block_needed_ = true;
    builder()->LoadLiteral(Smi::FromInt(
        static_cast<int>(TryFinallyContinuationToken::kFallthroughToken)));
    builder()->StoreAccumulatorInRegister(token_register_);
    // Since we're not saving the accumulator in the result register, shove a
    // harmless value there instead so that it is still considered "killed" in
    // the liveness analysis. Normally we would LdaUndefined first, but the Smi
    // token value is just as good, and by reusing it we save a bytecode.
    builder()->StoreAccumulatorInRegister(result_register_);
  }
References v8::internal::Smi::FromInt(), and v8::internal::interpreter::kFallthroughToken.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally().
RecordHandlerReThrowPath()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::RecordHandlerReThrowPath () [inline]
Definition at line 246 of file bytecode-generator.cc.
                                  {
    // The accumulator contains the exception object.
    RecordCommand(CMD_RETHROW, nullptr);
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally().
Member Data Documentation
async_return_token_
int v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::async_return_token_ [private]
Definition at line 399 of file bytecode-generator.cc.
deferred_
ZoneVector<Entry> v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::deferred_ [private]
Definition at line 392 of file bytecode-generator.cc.
fallthrough_from_try_block_needed_
bool v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::fallthrough_from_try_block_needed_ [private]
Definition at line 402 of file bytecode-generator.cc.
generator_
BytecodeGenerator* v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::generator_ [private]
Definition at line 391 of file bytecode-generator.cc.
message_register_
Register v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::message_register_ [private]
Definition at line 395 of file bytecode-generator.cc.
result_register_
Register v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::result_register_ [private]
Definition at line 394 of file bytecode-generator.cc.
return_token_
int v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::return_token_ [private]
Definition at line 398 of file bytecode-generator.cc.
token_register_
Register v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::token_register_ [private]
Definition at line 393 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc