v8::internal::Call Class Reference
#include <ast.h>
Public Types
enum CallType {
GLOBAL_CALL
, WITH_CALL
, NAMED_PROPERTY_CALL
, KEYED_PROPERTY_CALL
,
NAMED_OPTIONAL_CHAIN_PROPERTY_CALL
, KEYED_OPTIONAL_CHAIN_PROPERTY_CALL
, NAMED_SUPER_PROPERTY_CALL
, KEYED_SUPER_PROPERTY_CALL
,
PRIVATE_CALL
, PRIVATE_OPTIONAL_CHAIN_CALL
, SUPER_CALL
, OTHER_CALL
 }
enum class TaggedTemplateTag { kTrue
 }
using EvalScopeInfoIndexField = IsOptionalChainLinkField::Next< uint32_t, 20 >
Public Member Functions
bool is_possibly_eval () const
bool is_tagged_template () const
bool is_optional_chain_link () const
uint32_t eval_scope_info_index () const
void adjust_eval_scope_info_index (int delta)
CallType GetCallType () const
Private Types
using IsTaggedTemplateField = CallBase::NextBitField< bool, 1 >
using IsOptionalChainLinkField = IsTaggedTemplateField::Next< bool, 1 >
Private Member Functions
Call (Zone *zone, Expression *expression, const ScopedPtrList< Expression > &arguments, int pos, bool has_spread, int eval_scope_info_index, bool optional_chain)
Call (Zone *zone, Expression *expression, const ScopedPtrList< Expression > &arguments, int pos, TaggedTemplateTag tag)
Private Attributes
friend Zone
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1757 of file ast.h.
Member Typedef Documentation
EvalScopeInfoIndexField
using v8::internal::Call::EvalScopeInfoIndexField = IsOptionalChainLinkField::Next<uint32_t, 20>
Definition at line 1827 of file ast.h.
IsOptionalChainLinkField
using v8::internal::Call::IsOptionalChainLinkField = IsTaggedTemplateField::Next<bool, 1> [private]
Definition at line 1824 of file ast.h.
IsTaggedTemplateField
using v8::internal::Call::IsTaggedTemplateField = CallBase::NextBitField<bool, 1> [private]
Definition at line 1823 of file ast.h.
Member Enumeration Documentation
CallType
enum v8::internal::Call::CallType
Enumerator
GLOBAL_CALL
WITH_CALL
NAMED_PROPERTY_CALL
KEYED_PROPERTY_CALL
NAMED_OPTIONAL_CHAIN_PROPERTY_CALL
KEYED_OPTIONAL_CHAIN_PROPERTY_CALL
NAMED_SUPER_PROPERTY_CALL
KEYED_SUPER_PROPERTY_CALL
PRIVATE_CALL
PRIVATE_OPTIONAL_CHAIN_CALL
SUPER_CALL
OTHER_CALL
Definition at line 1780 of file ast.h.
                {
    GLOBAL_CALL,
    WITH_CALL,
    NAMED_PROPERTY_CALL,
    KEYED_PROPERTY_CALL,
    NAMED_OPTIONAL_CHAIN_PROPERTY_CALL,
    KEYED_OPTIONAL_CHAIN_PROPERTY_CALL,
    NAMED_SUPER_PROPERTY_CALL,
    KEYED_SUPER_PROPERTY_CALL,
    PRIVATE_CALL,
    PRIVATE_OPTIONAL_CHAIN_CALL,
    SUPER_CALL,
    OTHER_CALL,
  };
TaggedTemplateTag
enum v8::internal::Call::TaggedTemplateTag [strong]
Enumerator
kTrue
Definition at line 1798 of file ast.h.
{ kTrue };
Constructor & Destructor Documentation
Call() [1/2]
v8::internal::Call::Call (Zone * zone, Expression * expression, const ScopedPtrList< Expression > & arguments, int pos, bool has_spread, int eval_scope_info_index, bool optional_chain) [inline], [private]
Definition at line 1804 of file ast.h.
      : CallBase(zone, kCall, expression, arguments, pos, has_spread) {
    bit_field_ |= IsTaggedTemplateField::encode(false) |
                  IsOptionalChainLinkField::encode(optional_chain) |
                  EvalScopeInfoIndexField::encode(eval_scope_info_index);
    DCHECK_EQ(eval_scope_info_index > 0, is_possibly_eval());
  }
References v8::internal::AstNode::bit_field_, DCHECK_EQ, v8::base::BitField< T, shift, size, U >::encode(), eval_scope_info_index(), and is_possibly_eval().
Call() [2/2]
v8::internal::Call::Call (Zone * zone, Expression * expression, const ScopedPtrList< Expression > & arguments, int pos, TaggedTemplateTag tag) [inline], [private]
Definition at line 1814 of file ast.h.
      : CallBase(zone, kCall, expression, arguments, pos, false) {
    bit_field_ |= IsTaggedTemplateField::encode(true) |
                  IsOptionalChainLinkField::encode(false) |
                  EvalScopeInfoIndexField::encode(0);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::encode().
Member Function Documentation
adjust_eval_scope_info_index()
void v8::internal::Call::adjust_eval_scope_info_index (int delta) [inline]
Definition at line 1775 of file ast.h.
                                               {
    bit_field_ = EvalScopeInfoIndexField::update(
        bit_field_, eval_scope_info_index() + delta);
  }
References v8::internal::AstNode::bit_field_, eval_scope_info_index(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::AstFunctionLiteralIdReindexer::VisitCall().
eval_scope_info_index()
uint32_t v8::internal::Call::eval_scope_info_index () const [inline]
Definition at line 1771 of file ast.h.
                                         {
    return EvalScopeInfoIndexField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by adjust_eval_scope_info_index(), Call(), and v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::VisitCall().
GetCallType()
Call::CallType v8::internal::Call::GetCallType () const
Definition at line 978 of file ast.cc.
                                     {
  VariableProxy* proxy = expression()->AsVariableProxy();
  if (proxy != nullptr) {
    if (proxy->var()->IsUnallocated()) {
      return GLOBAL_CALL;
    } else if (proxy->var()->IsLookupSlot()) {
      // Calls going through 'with' always use VariableMode::kDynamic rather
      // than VariableMode::kDynamicLocal or VariableMode::kDynamicGlobal.
      return proxy->var()->mode() == VariableMode::kDynamic ? WITH_CALL
                                                            : OTHER_CALL;
    }
  }
  if (expression()->IsSuperCallReference()) return SUPER_CALL;
  Property* property = expression()->AsProperty();
  bool is_optional_chain = false;
  if (V8_UNLIKELY(property == nullptr && expression()->IsOptionalChain())) {
    is_optional_chain = true;
    property = expression()->AsOptionalChain()->expression()->AsProperty();
  }
  if (property != nullptr) {
    if (property->IsPrivateReference()) {
      if (is_optional_chain) return PRIVATE_OPTIONAL_CHAIN_CALL;
      return PRIVATE_CALL;
    }
    bool is_super = property->IsSuperAccess();
    // `super?.` is not syntactically valid, so a property load cannot be both
    // super and an optional chain.
    DCHECK(!is_super || !is_optional_chain);
    if (property->key()->IsPropertyName()) {
      if (is_super) return NAMED_SUPER_PROPERTY_CALL;
      if (is_optional_chain) return NAMED_OPTIONAL_CHAIN_PROPERTY_CALL;
      return NAMED_PROPERTY_CALL;
    } else {
      if (is_super) return KEYED_SUPER_PROPERTY_CALL;
      if (is_optional_chain) return KEYED_OPTIONAL_CHAIN_PROPERTY_CALL;
      return KEYED_PROPERTY_CALL;
    }
  }
  return OTHER_CALL;
}
References v8::internal::DCHECK(), v8::internal::CallBase::expression(), GLOBAL_CALL, v8::internal::Variable::IsLookupSlot(), v8::internal::Property::IsPrivateReference(), v8::internal::Expression::IsPropertyName(), v8::internal::Property::IsSuperAccess(), v8::internal::Variable::IsUnallocated(), v8::internal::kDynamic, v8::internal::Property::key(), KEYED_OPTIONAL_CHAIN_PROPERTY_CALL, KEYED_PROPERTY_CALL, KEYED_SUPER_PROPERTY_CALL, v8::internal::Variable::mode(), NAMED_OPTIONAL_CHAIN_PROPERTY_CALL, NAMED_PROPERTY_CALL, NAMED_SUPER_PROPERTY_CALL, OTHER_CALL, PRIVATE_CALL, PRIVATE_OPTIONAL_CHAIN_CALL, SUPER_CALL, V8_UNLIKELY, v8::internal::VariableProxy::var(), and WITH_CALL.
is_optional_chain_link()
bool v8::internal::Call::is_optional_chain_link () const [inline]
Definition at line 1767 of file ast.h.
                                      {
    return IsOptionalChainLinkField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
is_possibly_eval()
bool v8::internal::Call::is_possibly_eval () const [inline]
Definition at line 1759 of file ast.h.
                                {
    return EvalScopeInfoIndexField::decode(bit_field_) > 0;
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by Call(), v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::VisitCall(), and v8::internal::AstFunctionLiteralIdReindexer::VisitCall().
is_tagged_template()
bool v8::internal::Call::is_tagged_template () const [inline]
Definition at line 1763 of file ast.h.
                                  {
    return IsTaggedTemplateField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1801 of file ast.h.
Member Data Documentation
Zone
friend v8::internal::Call::Zone [private]
Definition at line 1802 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc