v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::WriteOutPGOTask Class Reference
Public Member Functions
WriteOutPGOTask (std::weak_ptr< NativeModule > native_module)
void Run () final
Static Public Member Functions
static void Schedule (std::weak_ptr< NativeModule > native_module)
Private Attributes
const std::weak_ptr< NativeModule > native_module_
Detailed Description
Definition at line 1377 of file module-instantiate.cc.
Constructor & Destructor Documentation
WriteOutPGOTask()
v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::WriteOutPGOTask::WriteOutPGOTask (std::weak_ptr< NativeModule > native_module) [inline], [explicit]
Definition at line 1379 of file module-instantiate.cc.
      : native_module_(std::move(native_module)) {}
Member Function Documentation
Run()
void v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::WriteOutPGOTask::Run () [inline], [final], [virtual]
Implements v8::Task.
Definition at line 1382 of file module-instantiate.cc.
                   {
    std::shared_ptr<NativeModule> native_module = native_module_.lock();
    if (!native_module) return;
    DumpProfileToFile(native_module->module(), native_module->wire_bytes(),
                      native_module->tiering_budget_array());
    Schedule(std::move(native_module_));
  }
References v8::internal::wasm::DumpProfileToFile().
Schedule()
static void v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::WriteOutPGOTask::Schedule (std::weak_ptr< NativeModule > native_module) [inline], [static]
Definition at line 1390 of file module-instantiate.cc.
                                                                {
    // Write out PGO info every 10 seconds.
    V8::GetCurrentPlatform()->PostDelayedTaskOnWorkerThread(
        TaskPriority::kUserVisible,
        std::make_unique<WriteOutPGOTask>(std::move(native_module)), 10.0);
  }
References v8::internal::V8::GetCurrentPlatform(), v8::kUserVisible, and v8::Platform::PostDelayedTaskOnWorkerThread().
Member Data Documentation
native_module_
const std::weak_ptr<NativeModule> v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::WriteOutPGOTask::native_module_ [private]
Definition at line 1398 of file module-instantiate.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-instantiate.cc