v8::internal::DateBuiltinsAssembler Class Reference
Public Member Functions
DateBuiltinsAssembler (compiler::CodeAssemblerState *state)
Protected Member Functions
void Generate_IsDateCheck (TNode< Context > context, TNode< Object > receiver)
void Generate_DatePrototype_GetField (TNode< Context > context, TNode< Object > receiver, int field_index)
Additional Inherited Members
Detailed Description
Definition at line 18 of file builtins-date-gen.cc.
Constructor & Destructor Documentation
DateBuiltinsAssembler()
v8::internal::DateBuiltinsAssembler::DateBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 20 of file builtins-date-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
Generate_DatePrototype_GetField()
void v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField (TNode< Context > context, TNode< Object > receiver, int field_index) [protected]
Definition at line 45 of file builtins-date-gen.cc.
                                                                     {
  Generate_IsDateCheck(context, receiver);
  TNode<JSDate> date_receiver = CAST(receiver);
  // Load the specified date field, falling back to the runtime as necessary.
  if (field_index < JSDate::kFirstUncachedField) {
    Label stamp_mismatch(this, Label::kDeferred);
    TNode<Object> date_cache_stamp =
        Load<Object>(IsolateField(IsolateFieldId::kDateCacheStamp));
    TNode<Object> cache_stamp =
        LoadObjectField(date_receiver, JSDate::kCacheStampOffset);
    GotoIf(TaggedNotEqual(date_cache_stamp, cache_stamp), &stamp_mismatch);
    Return(LoadObjectField(date_receiver,
                           JSDate::kYearOffset + field_index * kTaggedSize));
    BIND(&stamp_mismatch);
  }
  TNode<ExternalReference> isolate_ptr =
      ExternalConstant(ExternalReference::isolate_address(isolate()));
  TNode<Smi> field_index_smi = SmiConstant(field_index);
  TNode<ExternalReference> function =
      ExternalConstant(ExternalReference::get_date_field_function());
  TNode<Object> result = CAST(
      CallCFunction(function, MachineType::AnyTagged(),
                    std::make_pair(MachineType::Pointer(), isolate_ptr),
                    std::make_pair(MachineType::AnyTagged(), date_receiver),
                    std::make_pair(MachineType::AnyTagged(), field_index_smi)));
  Return(result);
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), CAST, v8::internal::compiler::CodeAssembler::ExternalConstant(), Generate_IsDateCheck(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::ExternalReference::isolate_address(), v8::internal::compiler::CodeAssembler::IsolateField(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::JSDate::kFirstUncachedField, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::MachineType::Pointer(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::TaggedNotEqual().
Generate_IsDateCheck()
void v8::internal::DateBuiltinsAssembler::Generate_IsDateCheck (TNode< Context > context, TNode< Object > receiver) [protected]
Definition at line 29 of file builtins-date-gen.cc.
                                                                         {
  Label ok(this), receiver_not_date(this, Label::kDeferred);
  GotoIf(TaggedIsSmi(receiver), &receiver_not_date);
  TNode<Uint16T> receiver_instance_type = LoadInstanceType(CAST(receiver));
  Branch(InstanceTypeEqual(receiver_instance_type, JS_DATE_TYPE), &ok,
         &receiver_not_date);
  // Raise a TypeError if the receiver is not a date.
  BIND(&receiver_not_date);
  { ThrowTypeError(context, MessageTemplate::kNotDateObject); }
  BIND(&ok);
}
References v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::TaggedIsSmi(), and v8::internal::CodeStubAssembler::ThrowTypeError().
Referenced by Generate_DatePrototype_GetField().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-date-gen.cc