v8::internal::maglev::Input Class Reference
#include <maglev-ir.h>
Public Member Functions
Input (ValueNode *node)
ValueNode * node () const
void set_node (ValueNode *node)
void clear ()
Private Attributes
ValueNode * node_
Detailed Description
Definition at line 1495 of file maglev-ir.h.
Constructor & Destructor Documentation
Input()
v8::internal::maglev::Input::Input (ValueNode * node) [inline], [explicit]
Definition at line 1497 of file maglev-ir.h.
: node_(node) {}
Member Function Documentation
clear()
void v8::internal::maglev::Input::clear ()
Definition at line 379 of file maglev-ir.cc.
                  {
  node_->remove_use();
  node_ = nullptr;
}
References node_, and v8::internal::maglev::ValueNode::remove_use().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MarkNodeDead().
node()
ValueNode* v8::internal::maglev::Input::node () const [inline]
Definition at line 1498 of file maglev-ir.h.
{ return node_; }
References node_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::InlinedAllocation::allocation_block(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndetectable(), v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), v8::internal::maglev::NodeBase::change_input(), v8::internal::maglev::CheckValueInputIs(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::MaglevPhiRepresentationSelector::FixLoopPhisBackedge(), v8::internal::maglev::MaglevAssembler::FromAnyToRegister(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::InputHint(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::IsStoreToNonEscapedObject(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Map(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MapPhiInput(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::MaglevGraphLabeller::PrintInput(), v8::internal::maglev::TransitionElementsKindOrCheckMap::PrintParams(), v8::internal::maglev::LoopOptimizationProcessor::Process(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::SweepIdentityNodes::Process(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::detail::PushInput(), set_node(), v8::internal::maglev::ValueNode::SetHint(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), v8::internal::maglev::detail::ToRegister(), v8::internal::maglev::NodeBase::TryGetInt32ConstantInput(), v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodeInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNonUntaggingNodeInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi(), v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse(), and v8::internal::maglev::UseFixed().
set_node()
void v8::internal::maglev::Input::set_node (ValueNode * node) [inline]
Definition at line 1499 of file maglev-ir.h.
{ node_ = node; }
References node(), and node_.
Member Data Documentation
node_
ValueNode* v8::internal::maglev::Input::node_ [private]
Definition at line 1503 of file maglev-ir.h.
Referenced by clear(), node(), and set_node().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc