cppgc::internal::CompactionWorklists Class Reference
#include <compaction-worklists.h>
Public Types
using MovableReference = const void *
using MovableReferencesWorklist = heap::base::Worklist< MovableReference *, 256 >
Public Member Functions
CompactionWorklists ()=default
CompactionWorklists (const CompactionWorklists &)=delete
CompactionWorklists & operator= (const CompactionWorklists &)=delete
MovableReferencesWorklist * movable_slots_worklist ()
void ClearForTesting ()
Private Attributes
MovableReferencesWorklist movable_slots_worklist_
Detailed Description
Definition at line 15 of file compaction-worklists.h.
Member Typedef Documentation
MovableReference
using cppgc::internal::CompactionWorklists::MovableReference = const void*
Definition at line 22 of file compaction-worklists.h.
MovableReferencesWorklist
using cppgc::internal::CompactionWorklists::MovableReferencesWorklist = heap::base::Worklist<MovableReference*, 256 >
Definition at line 24 of file compaction-worklists.h.
Constructor & Destructor Documentation
CompactionWorklists() [1/2]
cppgc::internal::CompactionWorklists::CompactionWorklists () [default]
CompactionWorklists() [2/2]
cppgc::internal::CompactionWorklists::CompactionWorklists (const CompactionWorklists &) [delete]
Member Function Documentation
ClearForTesting()
void cppgc::internal::CompactionWorklists::ClearForTesting ()
Definition at line 11 of file compaction-worklists.cc.
{ movable_slots_worklist_.Clear(); }
References heap::base::Worklist< EntryType, MinSegmentSize >::Clear(), and movable_slots_worklist_.
Referenced by cppgc::internal::MarkerBase::ClearAllWorklistsForTesting().
movable_slots_worklist()
MovableReferencesWorklist* cppgc::internal::CompactionWorklists::movable_slots_worklist () [inline]
Definition at line 27 of file compaction-worklists.h.
                                                      {
    return &movable_slots_worklist_;
  }
References movable_slots_worklist_.
Referenced by cppgc::internal::BasicMarkingState::BasicMarkingState().
operator=()
CompactionWorklists& cppgc::internal::CompactionWorklists::operator= (const CompactionWorklists &) [delete]
Member Data Documentation
movable_slots_worklist_
MovableReferencesWorklist cppgc::internal::CompactionWorklists::movable_slots_worklist_ [private]
Definition at line 34 of file compaction-worklists.h.
Referenced by ClearForTesting(), and movable_slots_worklist().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/compaction-worklists.h
/mnt/V8SourceCode/src/heap/cppgc/compaction-worklists.cc