v8::internal::Oddball Class Reference
#include <oddball.h>
Public Member Functions
void set_to_number_raw_as_bits (uint64_t bits)
Tagged< String > to_string () const
void set_to_string (Tagged< String > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Number > to_number () const
void set_to_number (Tagged< Number > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< String > type_of () const
void set_type_of (Tagged< String > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
uint8_t kind () const
void set_kind (uint8_t kind)
Static Public Member Functions
static V8_WARN_UNUSED_RESULT Handle< Number > ToNumber (Isolate *isolate, DirectHandle< Oddball > input)
static void Initialize (Isolate *isolate, DirectHandle< Oddball > oddball, const char *to_string, DirectHandle< Number > to_number, const char *type_of, uint8_t kind)
Static Public Attributes
static constexpr uint8_t kFalse = 0
static constexpr uint8_t kTrue = 1
static constexpr uint8_t kNotBooleanMask = static_cast<uint8_t>(~1)
static constexpr uint8_t kNull = 3
static constexpr uint8_t kUndefined = 4
Private Attributes
UnalignedDoubleMember to_number_raw_
TaggedMember< String > to_string_
TaggedMember< Number > to_number_
TaggedMember< String > type_of_
TaggedMember< Smi > kind_
Friends
struct ObjectTraits< Oddball >
struct OffsetsForDebug
class CodeStubAssembler
class maglev::MaglevAssembler
class compiler::AccessBuilder
class TorqueGeneratedOddballAsserts
Detailed Description
Definition at line 17 of file oddball.h.
Member Function Documentation
Initialize()
void v8::internal::Oddball::Initialize (Isolate * isolate, DirectHandle< Oddball > oddball, const char * to_string, DirectHandle< Number > to_number, const char * type_of, uint8_t kind) [static]
Definition at line 4312 of file objects.cc.
                                                            {
  DirectHandle<String> internalized_to_string =
      isolate->factory()->InternalizeUtf8String(to_string);
  DirectHandle<String> internalized_type_of =
      isolate->factory()->InternalizeUtf8String(type_of);
  if (IsHeapNumber(*to_number)) {
    oddball->set_to_number_raw_as_bits(
        Cast<HeapNumber>(to_number)->value_as_bits());
  } else {
    oddball->set_to_number_raw(Object::NumberValue(*to_number));
  }
  oddball->set_to_number(*to_number);
  oddball->set_to_string(*internalized_to_string);
  oddball->set_type_of(*internalized_type_of);
  oddball->set_kind(kind);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), kind(), v8::internal::Object::NumberValue(), to_number(), to_string(), and type_of().
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
kind()
uint8_t v8::internal::Oddball::kind () const [inline]
Definition at line 47 of file oddball-inl.h.
{ return kind_.load().value(); }
References kind_.
Referenced by Initialize().
set_kind()
void v8::internal::Oddball::set_kind (uint8_t kind) [inline]
Definition at line 49 of file oddball-inl.h.
                                    {
  kind_.store(this, Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), kind_, and v8::internal::value.
set_to_number()
void v8::internal::Oddball::set_to_number (Tagged< Number > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 38 of file oddball-inl.h.
                                                                       {
  to_number_.store(this, value, mode);
}
References mode(), to_number_, and v8::internal::value.
set_to_number_raw_as_bits()
void v8::internal::Oddball::set_to_number_raw_as_bits (uint64_t bits) [inline]
Definition at line 27 of file oddball-inl.h.
                                                     {
  // Bug(v8:8875): HeapNumber's double may be unaligned.
  to_number_raw_.set_value_as_bits(bits);
}
References v8::internal::UnalignedDoubleMember::set_value_as_bits(), and to_number_raw_.
set_to_string()
void v8::internal::Oddball::set_to_string (Tagged< String > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 33 of file oddball-inl.h.
                                                                       {
  to_string_.store(this, value, mode);
}
References mode(), to_string_, and v8::internal::value.
set_type_of()
void v8::internal::Oddball::set_type_of (Tagged< String > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 43 of file oddball-inl.h.
                                                                     {
  type_of_.store(this, value, mode);
}
References mode(), type_of_, and v8::internal::value.
to_number()
Tagged< Number > v8::internal::Oddball::to_number () const [inline]
Definition at line 37 of file oddball-inl.h.
{ return to_number_.load(); }
References to_number_.
Referenced by Initialize().
to_string()
Tagged< String > v8::internal::Oddball::to_string () const [inline]
Definition at line 32 of file oddball-inl.h.
{ return to_string_.load(); }
References to_string_.
Referenced by Initialize().
ToNumber()
Handle< Number > v8::internal::Oddball::ToNumber (Isolate * isolate, DirectHandle< Oddball > input) [inline], [static]
Definition at line 54 of file oddball-inl.h.
                                                              {
  return handle(input->to_number(), isolate);
}
References v8::internal::handle().
Referenced by v8::internal::Object::Equals(), and v8::internal::IntlMathematicalValue::From().
type_of()
Tagged< String > v8::internal::Oddball::type_of () const [inline]
Definition at line 42 of file oddball-inl.h.
{ return type_of_.load(); }
References type_of_.
Referenced by Initialize().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 64 of file oddball.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 66 of file oddball.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 65 of file oddball.h.
ObjectTraits< Oddball >
friend struct ObjectTraits< Oddball > [friend]
Definition at line 57 of file oddball.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 63 of file oddball.h.
TorqueGeneratedOddballAsserts
friend class TorqueGeneratedOddballAsserts [friend]
Definition at line 67 of file oddball.h.
Member Data Documentation
kFalse
constexpr uint8_t v8::internal::Oddball::kFalse = 0 [static], [constexpr]
Definition at line 53 of file oddball.h.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::JsonStringifier::Serialize_(), v8::internal::FastJsonStringifier< Char >::TrySerializeSimpleObject(), and v8::internal::ValueSerializer::WriteOddball().
kind_
TaggedMember<Smi> v8::internal::Oddball::kind_ [private]
Definition at line 73 of file oddball.h.
Referenced by kind(), and set_kind().
kNotBooleanMask
constexpr uint8_t v8::internal::Oddball::kNotBooleanMask = static_cast<uint8_t>(~1) [static], [constexpr]
Definition at line 55 of file oddball.h.
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE().
kNull
constexpr uint8_t v8::internal::Oddball::kNull = 3 [static], [constexpr]
Definition at line 56 of file oddball.h.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::JsonStringifier::Serialize_(), v8::internal::FastJsonStringifier< Char >::TrySerializeSimpleObject(), and v8::internal::ValueSerializer::WriteOddball().
kTrue
constexpr uint8_t v8::internal::Oddball::kTrue = 1 [static], [constexpr]
Definition at line 54 of file oddball.h.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::JsonStringifier::Serialize_(), v8::internal::FastJsonStringifier< Char >::TrySerializeSimpleObject(), and v8::internal::ValueSerializer::WriteOddball().
kUndefined
constexpr uint8_t v8::internal::Oddball::kUndefined = 4 [static], [constexpr]
Definition at line 57 of file oddball.h.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::Heap::CreateReadOnlyObjects(), and v8::internal::ValueSerializer::WriteOddball().
to_number_
TaggedMember<Number> v8::internal::Oddball::to_number_ [private]
Definition at line 71 of file oddball.h.
Referenced by set_to_number(), and to_number().
to_number_raw_
UnalignedDoubleMember v8::internal::Oddball::to_number_raw_ [private]
Definition at line 69 of file oddball.h.
Referenced by set_to_number_raw_as_bits().
to_string_
TaggedMember<String> v8::internal::Oddball::to_string_ [private]
Definition at line 70 of file oddball.h.
Referenced by set_to_string(), and to_string().
type_of_
TaggedMember<String> v8::internal::Oddball::type_of_ [private]
Definition at line 72 of file oddball.h.
Referenced by set_type_of(), and type_of().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/oddball.h
/mnt/V8SourceCode/src/objects/objects.cc
/mnt/V8SourceCode/src/objects/oddball-inl.h