v8::internal::compiler::ScheduleEarlyNodeVisitor Class Reference
Public Member Functions
ScheduleEarlyNodeVisitor (Zone *zone, Scheduler *scheduler)
void Run (NodeVector *roots)
Private Member Functions
void VisitNode (Node *node)
void PropagateMinimumPositionToNode (BasicBlock *block, Node *node)
Private Attributes
Scheduler * scheduler_
Schedule * schedule_
ZoneQueue< Node * > queue_
Detailed Description
Definition at line 1387 of file scheduler.cc.
Constructor & Destructor Documentation
ScheduleEarlyNodeVisitor()
v8::internal::compiler::ScheduleEarlyNodeVisitor::ScheduleEarlyNodeVisitor (Zone * zone, Scheduler * scheduler) [inline]
Definition at line 1389 of file scheduler.cc.
      : scheduler_(scheduler), schedule_(scheduler->schedule_), queue_(zone) {}
Member Function Documentation
PropagateMinimumPositionToNode()
void v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode (BasicBlock * block, Node * node) [inline], [private]
Definition at line 1435 of file scheduler.cc.
                                                                     {
    Scheduler::SchedulerData* data = scheduler_->GetData(node);
    // No need to propagate to fixed node, it's guaranteed to be a root.
    if (scheduler_->GetPlacement(node) == Scheduler::kFixed) return;
    // Coupled nodes influence schedule early position of their control.
    if (scheduler_->GetPlacement(node) == Scheduler::kCoupled) {
      Node* control = NodeProperties::GetControlInput(node);
      PropagateMinimumPositionToNode(block, control);
    }
    // Propagate new position if it is deeper down the dominator tree than the
    // current. Note that all inputs need to have minimum block position inside
    // the dominator chain of {node}'s minimum block position.
    DCHECK(InsideSameDominatorChain(block, data->minimum_block_));
    if (block->dominator_depth() > data->minimum_block_->dominator_depth()) {
      data->minimum_block_ = block;
      queue_.push(node);
      TRACE("Propagating #%d:%s minimum_block = id:%d, dominator_depth = %d\n",
            node->id(), node->op()->mnemonic(),
            data->minimum_block_->id().ToInt(),
            data->minimum_block_->dominator_depth());
    }
  }
References v8::internal::DCHECK(), v8::internal::compiler::BasicBlock::dominator_depth(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Scheduler::GetData(), v8::internal::compiler::Scheduler::GetPlacement(), v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Scheduler::kCoupled, v8::internal::compiler::Scheduler::kFixed, v8::internal::compiler::Scheduler::SchedulerData::minimum_block_, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), queue_, scheduler_, v8::internal::compiler::BasicBlock::Id::ToInt(), and v8::internal::TRACE().
Referenced by VisitNode().
Run()
void v8::internal::compiler::ScheduleEarlyNodeVisitor::Run (NodeVector * roots) [inline]
Definition at line 1393 of file scheduler.cc.
                              {
    for (Node* const root : *roots) {
      queue_.push(root);
    }
    while (!queue_.empty()) {
      scheduler_->tick_counter_->TickAndMaybeEnterSafepoint();
      VisitNode(queue_.front());
      queue_.pop();
    }
  }
References queue_, scheduler_, v8::internal::compiler::Scheduler::tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), and VisitNode().
Referenced by v8::internal::compiler::Scheduler::FuseFloatingControl(), and v8::internal::compiler::Scheduler::ScheduleEarly().
VisitNode()
void v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode (Node * node) [inline], [private]
Definition at line 1408 of file scheduler.cc.
                             {
    Scheduler::SchedulerData* data = scheduler_->GetData(node);
    // Fixed nodes already know their schedule early position.
    if (scheduler_->GetPlacement(node) == Scheduler::kFixed) {
      data->minimum_block_ = schedule_->block(node);
      TRACE("Fixing #%d:%s minimum_block = id:%d, dominator_depth = %d\n",
            node->id(), node->op()->mnemonic(),
            data->minimum_block_->id().ToInt(),
            data->minimum_block_->dominator_depth());
    }
    // No need to propagate unconstrained schedule early positions.
    if (data->minimum_block_ == schedule_->start()) return;
    // Propagate schedule early position.
    DCHECK_NOT_NULL(data->minimum_block_);
    for (auto use : node->uses()) {
      if (scheduler_->IsLive(use)) {
        PropagateMinimumPositionToNode(data->minimum_block_, use);
      }
    }
  }
References v8::internal::compiler::Schedule::block(), DCHECK_NOT_NULL, v8::internal::compiler::BasicBlock::dominator_depth(), v8::internal::compiler::Scheduler::GetData(), v8::internal::compiler::Scheduler::GetPlacement(), v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Scheduler::IsLive(), v8::internal::compiler::Scheduler::kFixed, v8::internal::compiler::Scheduler::SchedulerData::minimum_block_, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), PropagateMinimumPositionToNode(), schedule_, scheduler_, v8::internal::compiler::Schedule::start(), v8::internal::compiler::BasicBlock::Id::ToInt(), v8::internal::TRACE(), use(), and v8::internal::compiler::Node::uses().
Referenced by Run().
Member Data Documentation
queue_
ZoneQueue<Node*> v8::internal::compiler::ScheduleEarlyNodeVisitor::queue_ [private]
Definition at line 1470 of file scheduler.cc.
Referenced by PropagateMinimumPositionToNode(), and Run().
schedule_
Schedule* v8::internal::compiler::ScheduleEarlyNodeVisitor::schedule_ [private]
Definition at line 1469 of file scheduler.cc.
Referenced by VisitNode().
scheduler_
Scheduler* v8::internal::compiler::ScheduleEarlyNodeVisitor::scheduler_ [private]
Definition at line 1468 of file scheduler.cc.
Referenced by PropagateMinimumPositionToNode(), Run(), and VisitNode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/scheduler.cc