v8::internal::WritableJitPage Class Reference
#include <code-memory-access.h>
Public Member Functions
WritableJitPage (Address addr, size_t size)
WritableJitPage (const WritableJitPage &)=delete
WritableJitPage & operator= (const WritableJitPage &)=delete
~WritableJitPage ()
WritableJitAllocation LookupAllocationContaining (Address addr)
WritableFreeSpace FreeRange (Address addr, size_t size)
bool Empty () const
Private Attributes
RwxMemoryWriteScope write_scope_
ThreadIsolation::JitPageReference page_ref_
Friends
class ThreadIsolation
Detailed Description
Definition at line 528 of file code-memory-access.h.
Constructor & Destructor Documentation
WritableJitPage() [1/2]
v8::internal::WritableJitPage::WritableJitPage (Address addr, size_t size) [inline]
Definition at line 267 of file code-memory-access-inl.h.
    : write_scope_("WritableJitPage"),
      page_ref_(ThreadIsolation::LookupJitPage(addr, size)) {}
WritableJitPage() [2/2]
v8::internal::WritableJitPage::WritableJitPage (const WritableJitPage &) [delete]
 WritableJitPage()
v8::internal::WritableJitPage::~WritableJitPage () [inline], [default]
Member Function Documentation
Empty()
bool v8::internal::WritableJitPage::Empty () const [inline]
Definition at line 541 of file code-memory-access.h.
{ return page_ref_.Empty(); }
FreeRange()
WritableFreeSpace v8::internal::WritableJitPage::FreeRange (Address addr, size_t size) [inline]
Definition at line 278 of file code-memory-access-inl.h.
                                                                    {
  page_ref_.UnregisterRange(addr, size);
  return WritableFreeSpace(addr, size, true);
}
References page_ref_, size(), and v8::internal::ThreadIsolation::JitPageReference::UnregisterRange().
Referenced by v8::internal::Heap::CreateFillerObjectAt(), v8::internal::PagedSpaceBase::FreeInternal(), and v8::internal::FreeListCategory::SearchForNodeInList().
LookupAllocationContaining()
WritableJitAllocation v8::internal::WritableJitPage::LookupAllocationContaining (Address addr) [inline]
Definition at line 271 of file code-memory-access-inl.h.
                  {
  auto pair = page_ref_.AllocationContaining(addr);
  return WritableJitAllocation(pair.first, pair.second.Size(),
                               pair.second.Type(), false);
}
References v8::internal::ThreadIsolation::JitPageReference::AllocationContaining(), and page_ref_.
Referenced by v8::internal::Scavenger::ScavengePage(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateTypedOldToNewPointers(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateTypedOldToOldPointers(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedOldToOldPointers(), and v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedTrustedToTrustedPointers().
operator=()
WritableJitPage& v8::internal::WritableJitPage::operator= (const WritableJitPage &) [delete]
Friends And Related Function Documentation
ThreadIsolation
friend class ThreadIsolation [friend]
Definition at line 535 of file code-memory-access.h.
Member Data Documentation
page_ref_
ThreadIsolation::JitPageReference v8::internal::WritableJitPage::page_ref_ [private]
Definition at line 545 of file code-memory-access.h.
Referenced by FreeRange(), and LookupAllocationContaining().
write_scope_
RwxMemoryWriteScope v8::internal::WritableJitPage::write_scope_ [private]
Definition at line 544 of file code-memory-access.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/code-memory-access.h
/mnt/V8SourceCode/src/common/code-memory-access-inl.h