v8::internal::DeoptimizationLiteral Class Reference
#include <deoptimization-data.h>
Public Member Functions
DeoptimizationLiteral ()
DeoptimizationLiteral (IndirectHandle< Object > object)
DeoptimizationLiteral (Float32 number)
DeoptimizationLiteral (Float64 number)
DeoptimizationLiteral (double number)
DeoptimizationLiteral (int64_t signed_bigint64)
DeoptimizationLiteral (uint64_t unsigned_bigint64)
DeoptimizationLiteral (int32_t int32)
DeoptimizationLiteral (Tagged< Smi > smi)
IndirectHandle< Object > object () const
bool operator== (const DeoptimizationLiteral &other) const
DirectHandle< Object > Reify (Isolate *isolate) const
void Validate () const
DeoptimizationLiteralKind kind () const
Static Public Member Functions
static DeoptimizationLiteral HoleNaN ()
Private Attributes
DeoptimizationLiteralKind kind_
xx xx xx xx xx xx xx xx xx
union {
 IndirectHandle< Object > object_
 double number_
 Float32 float32_
 Float64 float64_
 int64_t int64_
 uint64_t uint64_
};
Detailed Description
Definition at line 60 of file deoptimization-data.h.
Constructor & Destructor Documentation
DeoptimizationLiteral() [1/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral () [inline]
Definition at line 62 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kInvalid), object_() {}
DeoptimizationLiteral() [2/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral (IndirectHandle< Object > object) [inline], [explicit]
Definition at line 64 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kObject), object_(object) {
    CHECK(!object_.is_null());
  }
References CHECK, v8::internal::kObject, and object_.
DeoptimizationLiteral() [3/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral (Float32 number) [inline], [explicit]
Definition at line 68 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kWasmFloat32), float32_(number) {}
References v8::internal::kWasmFloat32.
DeoptimizationLiteral() [4/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral (Float64 number) [inline], [explicit]
Definition at line 70 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kWasmFloat64), float64_(number) {}
References v8::internal::kWasmFloat64.
DeoptimizationLiteral() [5/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral (double number) [inline], [explicit]
Definition at line 72 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kNumber), number_(number) {}
References v8::internal::kNumber.
DeoptimizationLiteral() [6/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral (int64_t signed_bigint64) [inline], [explicit]
Definition at line 74 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kSignedBigInt64),
        int64_(signed_bigint64) {}
References v8::internal::kSignedBigInt64.
DeoptimizationLiteral() [7/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral (uint64_t unsigned_bigint64) [inline], [explicit]
Definition at line 77 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kUnsignedBigInt64),
        uint64_(unsigned_bigint64) {}
References v8::internal::kUnsignedBigInt64.
DeoptimizationLiteral() [8/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral (int32_t int32) [inline], [explicit]
Definition at line 80 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kWasmInt32), int64_(int32) {}
References v8::internal::kWasmInt32.
DeoptimizationLiteral() [9/9]
v8::internal::DeoptimizationLiteral::DeoptimizationLiteral (Tagged< Smi > smi) [inline], [explicit]
Definition at line 82 of file deoptimization-data.h.
      : kind_(DeoptimizationLiteralKind::kWasmI31Ref), int64_(smi.value()) {}
Member Function Documentation
HoleNaN()
static DeoptimizationLiteral v8::internal::DeoptimizationLiteral::HoleNaN () [inline], [static]
Definition at line 85 of file deoptimization-data.h.
                                         {
    DeoptimizationLiteral literal;
    literal.kind_ = DeoptimizationLiteralKind::kHoleNaN;
    return literal;
  }
References v8::internal::kHoleNaN, and kind_.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
kind()
DeoptimizationLiteralKind v8::internal::DeoptimizationLiteral::kind () const [inline]
Definition at line 154 of file deoptimization-data.h.
                                         {
    Validate();
    return kind_;
  }
References kind_, and Validate().
Referenced by v8::internal::DeoptimizationLiteralProvider::Get(), and operator==().
object()
IndirectHandle<Object> v8::internal::DeoptimizationLiteral::object () const [inline]
Definition at line 91 of file deoptimization-data.h.
{ return object_; }
References object_.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
operator==()
bool v8::internal::DeoptimizationLiteral::operator== (const DeoptimizationLiteral & other) const [inline]
Definition at line 93 of file deoptimization-data.h.
                                                            {
    if (kind_ != other.kind_) {
      return false;
    }
    switch (kind_) {
      case DeoptimizationLiteralKind::kObject:
        return object_.equals(other.object_);
      case DeoptimizationLiteralKind::kNumber:
        return base::bit_cast<uint64_t>(number_) ==
               base::bit_cast<uint64_t>(other.number_);
      case DeoptimizationLiteralKind::kWasmI31Ref:
      case DeoptimizationLiteralKind::kWasmInt32:
      case DeoptimizationLiteralKind::kSignedBigInt64:
        return int64_ == other.int64_;
      case DeoptimizationLiteralKind::kUnsignedBigInt64:
        return uint64_ == other.uint64_;
      case DeoptimizationLiteralKind::kHoleNaN:
        return other.kind() == DeoptimizationLiteralKind::kHoleNaN;
      case DeoptimizationLiteralKind::kInvalid:
        return true;
      case DeoptimizationLiteralKind::kWasmFloat32:
        return float32_.get_bits() == other.float32_.get_bits();
      case DeoptimizationLiteralKind::kWasmFloat64:
        return float64_.get_bits() == other.float64_.get_bits();
    }
    UNREACHABLE();
  }
References float32_, float64_, v8::internal::Float32::get_bits(), v8::internal::Float64::get_bits(), int64_, v8::internal::kHoleNaN, kind(), kind_, v8::internal::kInvalid, v8::internal::kNumber, v8::internal::kObject, v8::internal::kSignedBigInt64, v8::internal::kUnsignedBigInt64, v8::internal::kWasmFloat32, v8::internal::kWasmFloat64, v8::internal::kWasmI31Ref, v8::internal::kWasmInt32, number_, object_, uint64_, and v8::internal::UNREACHABLE().
Reify()
DirectHandle< Object > v8::internal::DeoptimizationLiteral::Reify (Isolate * isolate) const
Definition at line 23 of file deoptimization-data.cc.
                                                                        {
  Validate();
  switch (kind_) {
    case DeoptimizationLiteralKind::kObject: {
      return object_;
    }
    case DeoptimizationLiteralKind::kNumber: {
      return isolate->factory()->NewNumber(number_);
    }
    case DeoptimizationLiteralKind::kSignedBigInt64: {
      return BigInt::FromInt64(isolate, int64_);
    }
    case DeoptimizationLiteralKind::kUnsignedBigInt64: {
      return BigInt::FromUint64(isolate, uint64_);
    }
    case DeoptimizationLiteralKind::kHoleNaN: {
      // Hole NaNs that made it to here represent the undefined value.
      return isolate->factory()->undefined_value();
    }
    case DeoptimizationLiteralKind::kWasmI31Ref:
    case DeoptimizationLiteralKind::kWasmInt32:
    case DeoptimizationLiteralKind::kWasmFloat32:
    case DeoptimizationLiteralKind::kWasmFloat64:
    case DeoptimizationLiteralKind::kInvalid: {
      UNREACHABLE();
    }
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromUint64(), int64_, v8::internal::kHoleNaN, kind_, v8::internal::kInvalid, v8::internal::kNumber, v8::internal::kObject, v8::internal::kSignedBigInt64, v8::internal::kUnsignedBigInt64, v8::internal::kWasmFloat32, v8::internal::kWasmFloat64, v8::internal::kWasmI31Ref, v8::internal::kWasmInt32, v8::internal::FactoryBase< Impl >::NewNumber(), number_, object_, uint64_, v8::internal::UNREACHABLE(), and Validate().
Validate()
void v8::internal::DeoptimizationLiteral::Validate () const [inline]
Definition at line 150 of file deoptimization-data.h.
                        {
    CHECK_NE(kind_, DeoptimizationLiteralKind::kInvalid);
  }
References CHECK_NE, kind_, and v8::internal::kInvalid.
Referenced by v8::internal::compiler::CodeGenerator::DefineDeoptimizationLiteral(), kind(), and Reify().
Member Data Documentation
union { ... } [private]
float32_
Float32 v8::internal::DeoptimizationLiteral::float32_
Definition at line 165 of file deoptimization-data.h.
Referenced by operator==().
float64_
Float64 v8::internal::DeoptimizationLiteral::float64_
Definition at line 166 of file deoptimization-data.h.
Referenced by operator==().
int64_
int64_t v8::internal::DeoptimizationLiteral::int64_
Definition at line 167 of file deoptimization-data.h.
Referenced by operator==(), and Reify().
kind_
DeoptimizationLiteralKind v8::internal::DeoptimizationLiteral::kind_ [private]
Definition at line 160 of file deoptimization-data.h.
Referenced by HoleNaN(), kind(), operator==(), Reify(), and Validate().
number_
double v8::internal::DeoptimizationLiteral::number_
Definition at line 164 of file deoptimization-data.h.
Referenced by operator==(), and Reify().
object_
IndirectHandle<Object> v8::internal::DeoptimizationLiteral::object_
Definition at line 163 of file deoptimization-data.h.
Referenced by DeoptimizationLiteral(), object(), operator==(), and Reify().
uint64_
uint64_t v8::internal::DeoptimizationLiteral::uint64_
Definition at line 168 of file deoptimization-data.h.
Referenced by operator==(), and Reify().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/deoptimization-data.h
/mnt/V8SourceCode/src/objects/deoptimization-data.cc