v8::internal::wasm::InterpreterHandle Class Reference
#include <wasm-interpreter-runtime.h>
Public Member Functions
InterpreterHandle (Isolate *isolate, DirectHandle< Tuple2 > interpreter_object)
WasmInterpreter * interpreter ()
const WasmModule * module () const
bool Execute (WasmInterpreterThread *thread, Address frame_pointer, uint32_t func_index, const std::vector< WasmValue > &argument_values, std::vector< WasmValue > &return_values)
bool Execute (WasmInterpreterThread *thread, Address frame_pointer, uint32_t func_index, uint8_t *interpreter_fp)
WasmInterpreterThread::State ContinueExecution (WasmInterpreterThread *thread, bool called_from_js)
DirectHandle< WasmInstanceObject > GetInstanceObject ()
std::vector< WasmInterpreterStackEntry > GetInterpretedStack (Address frame_pointer)
int GetFunctionIndex (Address frame_pointer, int index) const
void SetTrapFunctionIndex (int32_t func_index)
Static Public Attributes
static constexpr ExternalPointerTag kManagedTag = kGenericManagedTag
Private Member Functions
InterpreterHandle (const InterpreterHandle &)=delete
InterpreterHandle & operator= (const InterpreterHandle &)=delete
WasmInterpreterThread::State RunExecutionLoop (WasmInterpreterThread *thread, bool called_from_js)
Static Private Member Functions
static ModuleWireBytes GetBytes (Tagged< Tuple2 > interpreter_object)
Private Attributes
Isolate * isolate_
const WasmModule * module_
WasmInterpreter interpreter_
Detailed Description
Definition at line 411 of file wasm-interpreter-runtime.h.
Constructor & Destructor Documentation
InterpreterHandle() [1/2]
v8::internal::wasm::InterpreterHandle::InterpreterHandle (Isolate * isolate, DirectHandle< Tuple2 > interpreter_object)
Definition at line 2844 of file wasm-interpreter-runtime.cc.
    : isolate_(isolate),
      module_(WasmInterpreterObject::get_wasm_instance(*interpreter_object)
                  ->module_object()
                  ->module()),
      interpreter_(isolate, module_, GetBytes(*interpreter_object),
                   direct_handle(WasmInterpreterObject::get_wasm_instance(
                                     *interpreter_object),
                                 isolate)) {}
InterpreterHandle() [2/2]
v8::internal::wasm::InterpreterHandle::InterpreterHandle (const InterpreterHandle &) [private], [delete]
Member Function Documentation
ContinueExecution()
WasmInterpreterThread::State v8::internal::wasm::InterpreterHandle::ContinueExecution (WasmInterpreterThread * thread, bool called_from_js) [inline]
Definition at line 202 of file wasm-interpreter-runtime-inl.h.
                                                        {
  return interpreter_.ContinueExecution(thread, called_from_js);
}
References v8::internal::wasm::WasmInterpreter::ContinueExecution(), and interpreter_.
Referenced by RunExecutionLoop().
Execute() [1/2]
V8_EXPORT_PRIVATE bool v8::internal::wasm::InterpreterHandle::Execute (WasmInterpreterThread * thread, Address frame_pointer, uint32_t func_index, const std::vector< WasmValue > & argument_values, std::vector< WasmValue > & return_values)
Definition at line 2901 of file wasm-interpreter-runtime.cc.
                                         {
  DCHECK_GT(module()->functions.size(), func_index);
  const FunctionSig* sig = module()->functions[func_index].sig;
  DCHECK_EQ(sig->parameter_count(), argument_values.size());
  DCHECK_EQ(sig->return_count(), return_values.size());
  thread->StartExecutionTimer();
  interpreter_.BeginExecution(thread, func_index, frame_pointer,
                              thread->NextFrameAddress(),
                              thread->NextRefStackOffset(), argument_values);
  WasmInterpreterThread::State state = RunExecutionLoop(thread, true);
  thread->StopExecutionTimer();
  switch (state) {
    case WasmInterpreterThread::RUNNING:
    case WasmInterpreterThread::FINISHED:
      for (unsigned i = 0; i < sig->return_count(); ++i) {
        return_values[i] = interpreter_.GetReturnValue(i);
      }
      return true;
    case WasmInterpreterThread::TRAPPED:
      for (unsigned i = 0; i < sig->return_count(); ++i) {
        return_values[i] = WasmValue(0xDEADBEEF);
      }
      return false;
    case WasmInterpreterThread::STOPPED:
      return false;
    case WasmInterpreterThread::EH_UNWINDING:
      UNREACHABLE();
  }
}
References v8::internal::wasm::WasmInterpreter::BeginExecution(), DCHECK_EQ, DCHECK_GT, v8::internal::wasm::WasmInterpreterThread::EH_UNWINDING, v8::internal::wasm::WasmInterpreterThread::FINISHED, v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WasmInterpreter::GetReturnValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, interpreter_, module(), v8::internal::wasm::WasmInterpreterThread::NextFrameAddress(), v8::internal::wasm::WasmInterpreterThread::NextRefStackOffset(), RunExecutionLoop(), v8::internal::wasm::WasmInterpreterThread::RUNNING, v8::internal::sig, v8::internal::wasm::WasmInterpreterThread::StartExecutionTimer(), v8::internal::wasm::WasmInterpreterThread::StopExecutionTimer(), v8::internal::wasm::WasmInterpreterThread::STOPPED, v8::internal::wasm::WasmInterpreterThread::TRAPPED, and v8::internal::UNREACHABLE().
Execute() [2/2]
bool v8::internal::wasm::InterpreterHandle::Execute (WasmInterpreterThread * thread, Address frame_pointer, uint32_t func_index, uint8_t * interpreter_fp)
Definition at line 2940 of file wasm-interpreter-runtime.cc.
                                                         {
  DCHECK_GT(module()->functions.size(), func_index);
  interpreter_.BeginExecution(thread, func_index, frame_pointer,
                              interpreter_fp);
  WasmInterpreterThread::State state = RunExecutionLoop(thread, false);
  return (state == WasmInterpreterThread::RUNNING ||
          state == WasmInterpreterThread::FINISHED);
}
References v8::internal::wasm::WasmInterpreter::BeginExecution(), DCHECK_GT, v8::internal::wasm::WasmInterpreterThread::FINISHED, interpreter_, module(), RunExecutionLoop(), and v8::internal::wasm::WasmInterpreterThread::RUNNING.
GetBytes()
ModuleWireBytes v8::internal::wasm::InterpreterHandle::GetBytes (Tagged< Tuple2 > interpreter_object) [static], [private]
Definition at line 2837 of file wasm-interpreter-runtime.cc.
                                                                             {
  Tagged<WasmInstanceObject> wasm_instance =
      WasmInterpreterObject::get_wasm_instance(interpreter_object);
  NativeModule* native_module = wasm_instance->module_object()->native_module();
  return ModuleWireBytes{native_module->wire_bytes()};
}
References v8::internal::WasmInterpreterObject::get_wasm_instance(), and v8::internal::wasm::NativeModule::wire_bytes().
GetFunctionIndex()
int v8::internal::wasm::InterpreterHandle::GetFunctionIndex (Address frame_pointer, int index) const
Definition at line 2973 of file wasm-interpreter-runtime.cc.
                                                         {
  return interpreter_.GetFunctionIndex(frame_pointer, index);
}
References v8::internal::wasm::WasmInterpreter::GetFunctionIndex(), v8::internal::index, and interpreter_.
GetInstanceObject()
DirectHandle< WasmInstanceObject > v8::internal::wasm::InterpreterHandle::GetInstanceObject ()
Definition at line 2952 of file wasm-interpreter-runtime.cc.
                                                                      {
  DebuggableStackFrameIterator it(isolate_);
  WasmInterpreterEntryFrame* frame =
      WasmInterpreterEntryFrame::cast(it.frame());
  DirectHandle<WasmInstanceObject> instance_obj(frame->wasm_instance(),
                                                isolate_);
  // Check that this is indeed the instance which is connected to this
  // interpreter.
  DCHECK_EQ(this,
            Cast<Managed<InterpreterHandle>>(
                WasmInterpreterObject::get_interpreter_handle(
                    instance_obj->trusted_data(isolate_)->interpreter_object()))
                ->raw());
  return instance_obj;
}
References v8::internal::Cast(), DCHECK_EQ, v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::WasmInterpreterObject::get_interpreter_handle(), isolate_, and v8::internal::Managed< CppType >::raw().
GetInterpretedStack()
std::vector< WasmInterpreterStackEntry > v8::internal::wasm::InterpreterHandle::GetInterpretedStack (Address frame_pointer)
Definition at line 2968 of file wasm-interpreter-runtime.cc.
                           {
  return interpreter_.GetInterpretedStack(frame_pointer);
}
References v8::internal::wasm::WasmInterpreter::GetInterpretedStack(), and interpreter_.
interpreter()
WasmInterpreter* v8::internal::wasm::InterpreterHandle::interpreter () [inline]
Definition at line 417 of file wasm-interpreter-runtime.h.
{ return &interpreter_; }
Referenced by v8::internal::RUNTIME_FUNCTION().
module()
const WasmModule* v8::internal::wasm::InterpreterHandle::module () const [inline]
Definition at line 418 of file wasm-interpreter-runtime.h.
{ return module_; }
Referenced by Execute().
operator=()
InterpreterHandle& v8::internal::wasm::InterpreterHandle::operator= (const InterpreterHandle &) [private], [delete]
RunExecutionLoop()
WasmInterpreterThread::State v8::internal::wasm::InterpreterHandle::RunExecutionLoop (WasmInterpreterThread * thread, bool called_from_js) [inline], [private]
Definition at line 2855 of file wasm-interpreter-runtime.cc.
                                                        {
  // If there were Ref values passed as arguments they have already been read
  // in BeginExecution(), so we can re-enable GC.
  AllowHeapAllocation allow_gc;
  bool finished = false;
  WasmInterpreterThread::State state = thread->state();
  if (state != WasmInterpreterThread::State::RUNNING) {
    return state;
  }
  while (!finished) {
    state = ContinueExecution(thread, called_from_js);
    switch (state) {
      case WasmInterpreterThread::State::FINISHED:
      case WasmInterpreterThread::State::RUNNING:
        // Perfect, just break the switch and exit the loop.
        finished = true;
        break;
      case WasmInterpreterThread::State::TRAPPED: {
        if (!isolate_->has_exception()) {
          // An exception handler was found, keep running the loop.
          if (!trap_handler::IsThreadInWasm()) {
            trap_handler::SetThreadInWasm();
          }
          break;
        }
        thread->Stop();
        [[fallthrough]];
      }
      case WasmInterpreterThread::State::STOPPED:
        // An exception happened, and the current activation was unwound
        // without hitting a local exception handler. All that remains to be
        // done is finish the activation and let the exception propagate.
        DCHECK(isolate_->has_exception());
        return state; // Either STOPPED or TRAPPED.
      case WasmInterpreterThread::State::EH_UNWINDING: {
        thread->Stop();
        return WasmInterpreterThread::State::STOPPED;
      }
    }
  }
  return state;
}
References ContinueExecution(), v8::internal::DCHECK(), v8::internal::Isolate::has_exception(), isolate_, v8::internal::trap_handler::IsThreadInWasm(), v8::internal::trap_handler::SetThreadInWasm(), v8::internal::wasm::WasmInterpreterThread::state(), and v8::internal::wasm::WasmInterpreterThread::Stop().
Referenced by Execute().
SetTrapFunctionIndex()
void v8::internal::wasm::InterpreterHandle::SetTrapFunctionIndex (int32_t func_index)
Definition at line 2978 of file wasm-interpreter-runtime.cc.
                                                               {
  interpreter_.SetTrapFunctionIndex(func_index);
}
References interpreter_, and v8::internal::wasm::WasmInterpreter::SetTrapFunctionIndex().
Referenced by v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
interpreter_
WasmInterpreter v8::internal::wasm::InterpreterHandle::interpreter_ [private]
Definition at line 453 of file wasm-interpreter-runtime.h.
Referenced by ContinueExecution(), Execute(), GetFunctionIndex(), GetInterpretedStack(), and SetTrapFunctionIndex().
isolate_
Isolate* v8::internal::wasm::InterpreterHandle::isolate_ [private]
Definition at line 451 of file wasm-interpreter-runtime.h.
Referenced by GetInstanceObject(), and RunExecutionLoop().
kManagedTag
constexpr ExternalPointerTag v8::internal::wasm::InterpreterHandle::kManagedTag = kGenericManagedTag [static], [constexpr]
Definition at line 413 of file wasm-interpreter-runtime.h.
module_
const WasmModule* v8::internal::wasm::InterpreterHandle::module_ [private]
Definition at line 452 of file wasm-interpreter-runtime.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-runtime.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-runtime-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-runtime.cc