v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container > Class Template Reference
#include <intrusive-set.h>
Classes
class end_iterator
class iterator
Public Member Functions
IntrusiveSet (Container container, GetIntrusiveSetIndex index_functor={})
bool Contains (T x) const
void Add (T x)
void Remove (T x)
iterator begin () const
end_iterator end () const
Private Member Functions
size_t & Index (T x) const
Private Attributes
Container elements_
GetIntrusiveSetIndex index_functor_
Detailed Description
template<class T, class GetIntrusiveSetIndex, class Container>
class v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >
Definition at line 40 of file intrusive-set.h.
Constructor & Destructor Documentation
IntrusiveSet()
template<class T , class GetIntrusiveSetIndex , class Container >
v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::IntrusiveSet (Container container, GetIntrusiveSetIndex index_functor = {}) [inline], [explicit]
Definition at line 46 of file intrusive-set.h.
                                                             {})
      : elements_(std::move(container)), index_functor_(index_functor) {
    static_assert(std::is_same_v<decltype(index_functor(std::declval<T>())),
                                 IntrusiveSetIndex&>);
  }
Member Function Documentation
Add()
template<class T , class GetIntrusiveSetIndex , class Container >
void v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Add (T x) [inline]
Definition at line 56 of file intrusive-set.h.
                {
    DCHECK(!Contains(x));
    Index(x) = elements_.size();
    elements_.push_back(x);
  }
References v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Contains(), DCHECK, v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::elements_, and v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Index().
begin()
template<class T , class GetIntrusiveSetIndex , class Container >
iterator v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::begin () const [inline]
Definition at line 114 of file intrusive-set.h.
{ return iterator{*this}; }
Contains()
template<class T , class GetIntrusiveSetIndex , class Container >
bool v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Contains (T x) const [inline]
Definition at line 53 of file intrusive-set.h.
{ return Index(x) != IntrusiveSetIndex::kNotInSet; }
References v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Index(), and v8::base::IntrusiveSetIndex::kNotInSet.
Referenced by v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Add(), and v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Remove().
end()
template<class T , class GetIntrusiveSetIndex , class Container >
end_iterator v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::end () const [inline]
Definition at line 115 of file intrusive-set.h.
{ return end_iterator{}; }
Index()
template<class T , class GetIntrusiveSetIndex , class Container >
size_t& v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Index (T x) const [inline], [private]
Definition at line 121 of file intrusive-set.h.
{ return index_functor_(x).value; }
References v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::index_functor_.
Referenced by v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Add(), v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Contains(), v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::iterator::operator*(), v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::iterator::operator++(), and v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Remove().
Remove()
template<class T , class GetIntrusiveSetIndex , class Container >
void v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Remove (T x) [inline]
Definition at line 64 of file intrusive-set.h.
                   {
    DCHECK(Contains(x));
    size_t& index = Index(x);
    DCHECK_EQ(x, elements_[index]);
    Index(elements_.back()) = index;
    elements_[index] = elements_.back();
    index = IntrusiveSetIndex::kNotInSet;
    elements_.pop_back();
  }
References v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Contains(), DCHECK, DCHECK_EQ, v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::elements_, v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Index(), v8::internal::index, and v8::base::IntrusiveSetIndex::kNotInSet.
Member Data Documentation
elements_
template<class T , class GetIntrusiveSetIndex , class Container >
Container v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::elements_ [private]
Definition at line 118 of file intrusive-set.h.
Referenced by v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Add(), v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::iterator::operator!=(), v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::iterator::operator*(), v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::iterator::operator++(), and v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Remove().
index_functor_
template<class T , class GetIntrusiveSetIndex , class Container >
GetIntrusiveSetIndex v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::index_functor_ [private]
Definition at line 119 of file intrusive-set.h.
Referenced by v8::base::IntrusiveSet< T, GetIntrusiveSetIndex, Container >::Index().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/intrusive-set.h