v8::internal::TaggedValue Class Reference
#include <tagged-value.h>
Public Member Functions
constexpr TaggedValue ()
constexpr TaggedValue (Tagged_t ptr)
TaggedValue (Tagged< MaybeObject > o)
Static Public Member Functions
static Tagged< MaybeObject > ToMaybeObject (Isolate *isolate, TaggedValue object)
Additional Inherited Members
Detailed Description
Definition at line 33 of file tagged-value.h.
Constructor & Destructor Documentation
TaggedValue() [1/3]
constexpr v8::internal::TaggedValue::TaggedValue () [inline], [constexpr]
Definition at line 35 of file tagged-value.h.
: TaggedImpl() {}
TaggedValue() [2/3]
constexpr v8::internal::TaggedValue::TaggedValue (Tagged_t ptr) [inline], [explicit], [constexpr]
Definition at line 36 of file tagged-value.h.
: TaggedImpl(ptr) {}
TaggedValue() [3/3]
v8::internal::TaggedValue::TaggedValue (Tagged< MaybeObject > o) [inline], [explicit]
Definition at line 42 of file tagged-value-inl.h.
    :
#ifdef V8_COMPRESS_POINTERS
      TaggedImpl(V8HeapCompressionScheme::CompressAny(o.ptr()))
#else
      TaggedImpl(o.ptr())
#endif
{
}
Member Function Documentation
ToMaybeObject()
Tagged< MaybeObject > v8::internal::TaggedValue::ToMaybeObject (Isolate * isolate, TaggedValue object) [inline], [static]
Definition at line 52 of file tagged-value-inl.h.
                                                                   {
#ifdef V8_COMPRESS_POINTERS
  return Tagged<MaybeObject>(
      V8HeapCompressionScheme::DecompressTagged(object.ptr()));
#else
  return Tagged<MaybeObject>(object.ptr());
#endif
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), and v8::internal::TaggedImpl< HeapObjectReferenceType::WEAK, Tagged_t >::ptr().
Referenced by v8::internal::StubCache::Get(), and v8::internal::StubCache::Set().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/tagged-value.h
/mnt/V8SourceCode/src/objects/tagged-value-inl.h