v8::base::Mutex Class Reference
#include <mutex.h>
Public Member Functions
Mutex ()
Mutex (const Mutex &)=delete
Mutex & operator= (const Mutex &)=delete
~Mutex ()
void Lock ()
void Unlock ()
bool TryLock () V8_WARN_UNUSED_RESULT
void AssertHeld () const
Private Member Functions
void AssertHeldAndUnmark ()
void AssertUnheldAndMark ()
Private Attributes
absl::Mutex native_handle_
Friends
class ConditionVariable
Detailed Description
Definition at line 36 of file mutex.h.
Constructor & Destructor Documentation
Mutex() [1/2]
v8::base::Mutex::Mutex ()
Definition at line 54 of file mutex.cc.
             {
#ifdef DEBUG
  level_ = 0;
#endif
}
Mutex() [2/2]
v8::base::Mutex::Mutex (const Mutex &) [delete]
 Mutex()
v8::base::Mutex::~Mutex ()
Definition at line 60 of file mutex.cc.
{ DCHECK_EQ(0, level_); }
References DCHECK_EQ.
Member Function Documentation
AssertHeld()
void v8::base::Mutex::AssertHeld () const [inline]
Definition at line 58 of file mutex.h.
                                    {
    // If this access results in a race condition being detected by TSan, this
    // means that you in fact did *not* hold the mutex.
    DCHECK_EQ(1, level_);
  }
References DCHECK_EQ.
Referenced by v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::WasmEngine::ClearWeakScriptHandle(), v8::internal::wasm::WasmEngine::DisableCodeLogging(), v8::internal::wasm::WasmEngine::EnableCodeLogging(), v8::internal::SharedStructTypeRegistry::EnsureCapacity(), v8::internal::StringTable::EnsureCapacity(), v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(), v8::internal::StringForwardingTable::BlockVector::Grow(), v8::internal::OptimizingCompileInputQueue::HasJobForIsolate(), v8::internal::IsolateGroup::InitializeReadOnlyArtifacts(), v8::internal::OptimizingCompileTaskExecutor::IsTaskRunningForIsolate(), v8::internal::ThreadIsolation::LookupJitPageLocked(), v8::internal::FutexEmulation::NotifyAsyncWaiter(), v8::platform::DefaultForegroundTaskRunner::PopTaskFromDelayedQueueLocked(), v8::platform::DefaultForegroundTaskRunner::PostDelayedTaskLocked(), v8::platform::DefaultForegroundTaskRunner::PostTaskLocked(), v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC(), v8::internal::wasm::WasmEngine::RemoveIsolateFromCurrentGC(), v8::internal::wasm::WasmImportWrapperHandle::set_code(), v8::internal::ReadOnlyHeap::SetUp(), v8::internal::ThreadIsolation::SplitJitPageLocked(), v8::internal::wasm::WasmEngine::TriggerGC(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerOutstandingCallbacks(), v8::internal::ThreadIsolation::TryLookupJitPageLocked(), and v8::platform::DefaultForegroundTaskRunner::WaitForTaskLocked().
AssertHeldAndUnmark()
void v8::base::Mutex::AssertHeldAndUnmark () [inline], [private]
Definition at line 71 of file mutex.h.
                                       {
#ifdef DEBUG
    // If this access results in a race condition being detected by TSan, this
    // means that you in fact did *not* hold the mutex.
    DCHECK_EQ(1, level_);
    level_--;
#endif
  }
References DCHECK_EQ.
Referenced by Unlock(), v8::base::ConditionVariable::Wait(), and v8::base::ConditionVariable::WaitFor().
AssertUnheldAndMark()
void v8::base::Mutex::AssertUnheldAndMark () [inline], [private]
Definition at line 80 of file mutex.h.
                                       {
#ifdef DEBUG
    // This is only invoked *after* actually getting the mutex, so should not
    // result in race conditions.
    DCHECK_EQ(0, level_);
    level_++;
#endif
  }
References DCHECK_EQ.
Referenced by Lock(), TryLock(), v8::base::ConditionVariable::Wait(), and v8::base::ConditionVariable::WaitFor().
Lock()
void v8::base::Mutex::Lock ()
Definition at line 62 of file mutex.cc.
                                                {
  native_handle_.Lock();
  AssertUnheldAndMark();
}
References AssertUnheldAndMark(), and native_handle_.
Referenced by v8::base::RecursiveMutex::Lock(), v8::internal::ThreadManager::Lock(), v8::internal::ObjectLock::Lock(), v8::internal::ParkedMutexGuard::ParkedMutexGuard(), and v8::internal::ParkedMutexGuardIf::ParkedMutexGuardIf().
operator=()
Mutex& v8::base::Mutex::operator= (const Mutex &) [delete]
TryLock()
bool v8::base::Mutex::TryLock ()
Definition at line 72 of file mutex.cc.
                                                   {
  if (!native_handle_.TryLock()) return false;
  AssertUnheldAndMark();
  return true;
}
References AssertUnheldAndMark(), and native_handle_.
Referenced by v8::internal::ThreadIsolation::CanLookupStartOfJitAllocationAt(), v8::internal::ParkedMutexGuard::ParkedMutexGuard(), v8::internal::ParkedMutexGuardIf::ParkedMutexGuardIf(), and v8::base::RecursiveMutex::TryLock().
Unlock()
void v8::base::Mutex::Unlock ()
Definition at line 67 of file mutex.cc.
                                                  {
  AssertHeldAndUnmark();
  native_handle_.Unlock();
}
References AssertHeldAndUnmark(), and native_handle_.
Referenced by v8::internal::ThreadIsolation::CanLookupStartOfJitAllocationAt(), v8::base::RecursiveMutex::Unlock(), v8::internal::ThreadManager::Unlock(), and v8::internal::ObjectLock::Unlock().
Friends And Related Function Documentation
ConditionVariable
friend class ConditionVariable [friend]
Definition at line 89 of file mutex.h.
Member Data Documentation
native_handle_
absl::Mutex v8::base::Mutex::native_handle_ [private]
Definition at line 91 of file mutex.h.
Referenced by Lock(), TryLock(), Unlock(), v8::base::ConditionVariable::Wait(), and v8::base::ConditionVariable::WaitFor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/mutex.h
/mnt/V8SourceCode/src/base/platform/mutex.cc