v8::internal::compiler::turboshaft::BranchEliminationReducer< Next > Class Template Reference
#include <branch-elimination-reducer.h>
Public Member Functions
void Bind (Block *new_block)
V< None > REDUCE() Branch (V< Word32 > cond, Block *if_true, Block *if_false, BranchHint hint)
V< Any > REDUCE() Select (V< Word32 > cond, V< Any > vtrue, V< Any > vfalse, RegisterRepresentation rep, BranchHint hint, SelectOp::Implementation implem)
V< None > REDUCE() Goto (Block *destination, bool is_backedge)
V< None > REDUCE() DeoptimizeIf (V< Word32 > condition, V< FrameState > frame_state, bool negated, const DeoptimizeParameters *parameters)
Private Member Functions
void ResetToBlock (Block *block)
void ClearCurrentEntries ()
void StartLayer (Block *block)
void ReplayMissingPredecessors (Block *new_block)
bool CanBeConstantFolded (OpIndex idx, const Block *cond_input_block, bool has_phi=false, int depth=0)
Private Attributes
ZoneVector< Block * > dominator_path_ {__ phase_zone()}
LayeredHashMap< V< Word32 >, bool > known_conditions_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >
Definition at line 26 of file branch-elimination-reducer.h.
Member Function Documentation
Bind()
template<class Next >
void v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Bind (Block * new_block) [inline]
Definition at line 202 of file branch-elimination-reducer.h.
                              {
    Next::Bind(new_block);
    if (ShouldSkipOptimizationStep()) {
      // It's important to have a ShouldSkipOptimizationStep here, because
      // {known_conditions_} assumes that we perform all branch elimination
      // possible (which implies that we don't ever insert twice the same thing
      // in {known_conditions_}). If we stop doing ReduceBranch because of
      // ShouldSkipOptimizationStep, then this assumption doesn't hold anymore,
      // and we should thus stop updating {known_conditions_} to not trigger
      // some DCHECKs.
      return;
    }
    // Update {known_conditions_} based on where {new_block} is in the dominator
    // tree.
    ResetToBlock(new_block);
    ReplayMissingPredecessors(new_block);
    StartLayer(new_block);
    if (new_block->IsBranchTarget()) {
      // The current block is a branch target, so we add the branch condition
      // along with its value in {known_conditions_}.
      DCHECK_EQ(new_block->PredecessorCount(), 1);
      const Operation& op =
          new_block->LastPredecessor()->LastOperation(__ output_graph());
      if (const BranchOp* branch = op.TryCast<BranchOp>()) {
        DCHECK_EQ(new_block, any_of(branch->if_true, branch->if_false));
        bool condition_value = branch->if_true == new_block;
        if (!known_conditions_.Contains(branch->condition())) {
          known_conditions_.InsertNewKey(branch->condition(), condition_value);
        }
      }
    }
  }
References __, v8::internal::compiler::turboshaft::any_of(), DCHECK_EQ, v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_, v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ResetToBlock(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::StartLayer(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Branch()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Branch (V< Word32 > cond, Block * if_true, Block * if_false, BranchHint hint) [inline]
Definition at line 238 of file branch-elimination-reducer.h.
                                          {
    LABEL_BLOCK(no_change) {
      return Next::ReduceBranch(cond, if_true, if_false, hint);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    if (const Block* if_true_origin = __ OriginForBlockStart(if_true)) {
      if (const Block* if_false_origin = __ OriginForBlockStart(if_false)) {
        const Operation& first_op_true =
            if_true_origin->FirstOperation(__ input_graph());
        const Operation& first_op_false =
            if_false_origin->FirstOperation(__ input_graph());
        const GotoOp* true_goto = first_op_true.template TryCast<GotoOp>();
        const GotoOp* false_goto = first_op_false.template TryCast<GotoOp>();
        // We apply the fourth optimization, replacing empty braches with a
        // Goto to their destination (if it's the same block).
        if (true_goto && false_goto &&
            true_goto->destination == false_goto->destination) {
          Block* merge_block = true_goto->destination;
          if (!merge_block->HasPhis(__ input_graph())) {
            // Using `ReduceInputGraphGoto()` here enables more optimizations.
            __ Goto(__ MapToNewGraph(merge_block));
            return V<None>::Invalid();
          }
        }
      }
    }
    if (auto cond_value = known_conditions_.Get(cond)) {
      // We already know the value of {cond}. We thus remove the branch (this is
      // the "first" optimization in the documentation at the top of this
      // module).
      __ Goto(*cond_value ? if_true : if_false);
      return V<None>::Invalid();
    }
    // We can't optimize this branch.
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::GotoOp::destination, v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), v8::internal::compiler::turboshaft::Block::HasPhis(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_, LABEL_BLOCK, and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
CanBeConstantFolded()
template<class Next >
bool v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded (OpIndex idx, const Block * cond_input_block, bool has_phi = false, int depth = 0) [inline], [private]
Definition at line 560 of file branch-elimination-reducer.h.
                                                                {
    // We limit the depth of the search to {kMaxDepth} in order to avoid
    // potentially visiting a lot of nodes.
    static constexpr int kMaxDepth = 4;
    if (depth > kMaxDepth) return false;
    const Operation& op = __ input_graph().Get(idx);
    if (!cond_input_block->Contains(idx)) {
      // If we reach a ConstantOp without having gone through a Phi, then the
      // condition can be constant-folded without performing block cloning.
      return has_phi && op.Is<ConstantOp>();
    }
    if (op.Is<PhiOp>()) {
      int curr_block_pred_idx = cond_input_block->GetPredecessorIndex(
          __ current_block()->OriginForBlockEnd());
      // There is no need to increment {depth} on this recursive call, because
      // it will anyways exit early because {idx} won't be in
      // {cond_input_block}.
      return CanBeConstantFolded(op.input(curr_block_pred_idx),
                                 cond_input_block, /*has_phi*/ true, depth);
    } else if (op.Is<ConstantOp>()) {
      return true;
    } else if (op.input_count == 0) {
      // Any operation that has no input but is not a ConstantOp probably won't
      // be able to be constant-folded away (eg, LoadRootRegister).
      return false;
    } else if (!op.Effects().can_be_constant_folded()) {
      // Operations with side-effects won't be able to be constant-folded.
      return false;
    }
    for (int i = 0; i < op.input_count; i++) {
      if (!CanBeConstantFolded(op.input(i), cond_input_block, has_phi,
                               depth + 1)) {
        return false;
      }
    }
    return has_phi;
  }
References __, v8::internal::compiler::turboshaft::OpEffects::can_be_constant_folded(), v8::internal::compiler::turboshaft::Block::Contains(), v8::internal::compiler::turboshaft::Operation::Effects(), v8::internal::compiler::turboshaft::Block::GetPredecessorIndex(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::turboshaft::Operation::Is().
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto().
ClearCurrentEntries()
template<class Next >
void v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ClearCurrentEntries () [inline], [private]
Definition at line 472 of file branch-elimination-reducer.h.
                             {
    known_conditions_.DropLastLayer();
    dominator_path_.pop_back();
  }
References v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::dominator_path_, and v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_.
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ResetToBlock().
DeoptimizeIf()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::DeoptimizeIf (V< Word32 > condition, V< FrameState > frame_state, bool negated, const DeoptimizeParameters * parameters) [inline]
Definition at line 399 of file branch-elimination-reducer.h.
                                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceDeoptimizeIf(condition, frame_state, negated,
                                      parameters);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    std::optional<bool> condition_value = known_conditions_.Get(condition);
    if (!condition_value.has_value()) {
      known_conditions_.InsertNewKey(condition, negated);
      goto no_change;
    }
    if ((*condition_value && !negated) || (!*condition_value && negated)) {
      // The condition is true, so we always deoptimize.
      return Next::ReduceDeoptimize(frame_state, parameters);
    } else {
      // The condition is false, so we never deoptimize.
      return V<None>::Invalid();
    }
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_, LABEL_BLOCK, and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
Goto()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto (Block * destination, bool is_backedge) [inline]
Definition at line 296 of file branch-elimination-reducer.h.
                                                             {
    LABEL_BLOCK(no_change) {
      return Next::ReduceGoto(destination, is_backedge);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    const Block* destination_origin = __ OriginForBlockStart(destination);
    if (!destination_origin || !destination_origin->IsMerge()) {
      goto no_change;
    }
    // Maximum size up to which we allow cloning a block. Cloning too large
    // blocks will lead to increasing the size of the graph too much, which will
    // lead to slower compile time, and larger generated code.
    // TODO(dmercadier): we might want to exclude Phis from this, since they are
    // typically removed when we clone a block. However, computing the number of
    // operations in a block excluding Phis is more costly (because we'd have to
    // iterate all of the operations one by one).
    // TODO(dmercadier): this "13" was selected fairly arbitrarily (= it sounded
    // reasonable). It could be useful to run a few benchmarks to see if we can
    // find a more optimal number.
    static constexpr int kMaxOpCountForCloning = 13;
    const Operation& last_op =
        destination_origin->LastOperation(__ input_graph());
    if (destination_origin->OpCountUpperBound() > kMaxOpCountForCloning) {
      goto no_change;
    }
    if (const BranchOp* branch = last_op.template TryCast<BranchOp>()) {
      V<Word32> condition =
          __ template MapToNewGraph<true>(branch->condition());
      if (condition.valid()) {
        std::optional<bool> condition_value = known_conditions_.Get(condition);
        if (!condition_value.has_value()) {
          // We've already visited the subsequent block's Branch condition, but
          // we don't know its value right now.
          goto no_change;
        }
        // The next block {new_dst} is a Merge, and ends with a Branch whose
        // condition is already known. As per the 2nd optimization, we'll
        // process {new_dst} right away, and we'll end it with a Goto instead of
        // its current Branch.
        __ CloneBlockAndGoto(destination_origin);
        return {};
      } else {
        // Optimization 2bis:
        // {condition} hasn't been visited yet, and thus it doesn't have a
        // mapping to the new graph. However, if it's the result of a Phi whose
        // input is coming from the current block, then it still makes sense to
        // inline {destination_origin}: the condition will then be known.
        if (destination_origin->Contains(branch->condition())) {
          if (__ input_graph().Get(branch->condition()).template Is<PhiOp>()) {
            __ CloneBlockAndGoto(destination_origin);
            return {};
          } else if (CanBeConstantFolded(branch->condition(),
                                         destination_origin)) {
            // If the {cond} only uses constant Phis that come from the current
            // block, it's probably worth it to clone the block in order to
            // constant-fold away the Branch.
            __ CloneBlockAndGoto(destination_origin);
            return {};
          } else {
            goto no_change;
          }
        }
      }
    } else if (last_op.template Is<ReturnOp>()) {
      // In case of the following pattern, the `Goto` is most likely going to be
      // folded into a jump table, so duplicating Block 5 will only increase the
      // amount of different targets within the jump table.
      //
      // Block 1:
      // [...]
      // SwitchOp()[2, 3, 4]
      //
      // Block 2: Block 3: Block 4:
      // Goto 5 Goto 5 Goto 6
      //
      // Block 5: Block 6:
      // [...] [...]
      // ReturnOp
      if (Asm().current_block()->PredecessorCount() == 1 &&
          Asm().current_block()->begin() ==
              __ output_graph().next_operation_index()) {
        const Block* prev_block = Asm().current_block()->LastPredecessor();
        if (prev_block->LastOperation(__ output_graph())
                .template Is<SwitchOp>()) {
          goto no_change;
        }
      }
      // The destination block in the old graph ends with a Return
      // and the old destination is a merge block, so we can directly
      // inline the destination block in place of the Goto.
      Asm().CloneAndInlineBlock(destination_origin);
      return {};
    }
    goto no_change;
  }
References __, v8::internal::compiler::begin(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded(), v8::internal::compiler::turboshaft::Block::Contains(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::Block::IsMerge(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_, LABEL_BLOCK, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Block::OpCountUpperBound(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Branch().
ReplayMissingPredecessors()
template<class Next >
void v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors (Block * new_block) [inline], [private]
Definition at line 523 of file branch-elimination-reducer.h.
                                                   {
    // Collect blocks that need to be replayed.
    base::SmallVector<Block*, 32> missing_blocks;
    for (Block* dom = new_block->GetDominator();
         dom != nullptr && dom != dominator_path_.back();
         dom = dom->GetDominator()) {
      missing_blocks.push_back(dom);
    }
    // Actually does the replaying, starting from the oldest block and finishing
    // with the newest one (so that they will later be removed in the correct
    // order).
    for (auto it = missing_blocks.rbegin(); it != missing_blocks.rend(); ++it) {
      Block* block = *it;
      StartLayer(block);
      if (block->IsBranchTarget()) {
        const Operation& op =
            block->LastPredecessor()->LastOperation(__ output_graph());
        if (const BranchOp* branch = op.TryCast<BranchOp>()) {
          DCHECK(branch->if_true->index() == block->index() ||
                 branch->if_false->index() == block->index());
          bool condition_value =
              branch->if_true->index().valid()
                  ? branch->if_true->index() == block->index()
                  : branch->if_false->index() != block->index();
          known_conditions_.InsertNewKey(branch->condition(), condition_value);
        }
      }
    }
  }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::dominator_path_, v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetDominator(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::IsBranchTarget(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::rbegin(), v8::base::SmallVector< T, kSize, Allocator >::rend(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::StartLayer(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Bind().
ResetToBlock()
template<class Next >
void v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ResetToBlock (Block * block) [inline], [private]
Definition at line 454 of file branch-elimination-reducer.h.
                                  {
    Block* target = block->GetDominator();
    while (!dominator_path_.empty() && target != nullptr &&
           dominator_path_.back() != target) {
      if (dominator_path_.back()->Depth() > target->Depth()) {
        ClearCurrentEntries();
      } else if (dominator_path_.back()->Depth() < target->Depth()) {
        target = target->GetDominator();
      } else {
        // {target} and {dominator_path.back} have the same depth but are not
        // equal, so we go one level up for both.
        ClearCurrentEntries();
        target = target->GetDominator();
      }
    }
  }
References v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ClearCurrentEntries(), v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::Depth(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::dominator_path_, and v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetDominator().
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Bind().
Select()
template<class Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Select (V< Word32 > cond, V< Any > vtrue, V< Any > vfalse, RegisterRepresentation rep, BranchHint hint, SelectOp::Implementation implem) [inline]
Definition at line 278 of file branch-elimination-reducer.h.
                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceSelect(cond, vtrue, vfalse, rep, hint, implem);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    if (auto cond_value = known_conditions_.Get(cond)) {
      if (*cond_value) {
        return vtrue;
      } else {
        return vfalse;
      }
    }
    goto no_change;
  }
References v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_, LABEL_BLOCK, and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
StartLayer()
template<class Next >
void v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::StartLayer (Block * block) [inline], [private]
Definition at line 477 of file branch-elimination-reducer.h.
                                {
    known_conditions_.StartLayer();
    dominator_path_.push_back(block);
  }
References v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::dominator_path_, and v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_.
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Bind(), and v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors().
Member Data Documentation
dominator_path_
template<class Next >
ZoneVector<Block*> v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::dominator_path_ {__ phase_zone()} [private]
Definition at line 604 of file branch-elimination-reducer.h.
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ClearCurrentEntries(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ResetToBlock(), and v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::StartLayer().
known_conditions_
template<class Next >
LayeredHashMap<V<Word32>, bool> v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::known_conditions_ [private]
Initial value:
{
      __ phase_zone(), __ input_graph().DominatorTreeDepth() * 2}
Definition at line 605 of file branch-elimination-reducer.h.
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Bind(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ClearCurrentEntries(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::DeoptimizeIf(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Select(), and v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::StartLayer().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/branch-elimination-reducer.h