v8::internal::maglev::StoreTaggedFieldNoWriteBarrier Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreTaggedFieldNoWriteBarrier (uint64_t bitfield, int offset, StoreTaggedMode store_mode)
int offset () const
bool initializing_or_transitioning () const
Input & object_input ()
Input & value_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kObjectIndex = 0
static constexpr int kValueIndex = 1
Private Types
using Base = FixedInputNodeT< 2, StoreTaggedFieldNoWriteBarrier >
using InitializingOrTransitioningField = NextBitField< bool, 1 >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
Definition at line 9011 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::Base = FixedInputNodeT<2, StoreTaggedFieldNoWriteBarrier> [private]
Definition at line 9013 of file maglev-ir.h.
InitializingOrTransitioningField
using v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::InitializingOrTransitioningField = NextBitField<bool, 1> [private]
Definition at line 9061 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreTaggedFieldNoWriteBarrier()
v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::StoreTaggedFieldNoWriteBarrier (uint64_t bitfield, int offset, StoreTaggedMode store_mode) [inline], [explicit]
Definition at line 9016 of file maglev-ir.h.
      : Base(bitfield | InitializingOrTransitioningField::encode(
                            IsInitializingOrTransitioning(store_mode))),
        offset_(offset) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::GenerateCode (MaglevAssembler * , const ProcessingState &)
initializing_or_transitioning()
bool v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::initializing_or_transitioning () const [inline]
Definition at line 9034 of file maglev-ir.h.
                                             {
    return InitializingOrTransitioningField::decode(bitfield());
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::MaxCallStackArgs () const [inline]
Definition at line 9050 of file maglev-ir.h.
                               {
    // StoreTaggedFieldNoWriteBarrier never really does any call.
    return 0;
  }
object_input()
Input& v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::object_input () [inline]
Definition at line 9040 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
int v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::offset () const [inline]
Definition at line 9033 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8234 of file maglev-ir.cc.
                                                               {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::value_input () [inline]
Definition at line 9041 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
VerifyInputs()
void v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 1131 of file maglev-ir.cc.
                                               {
  Base::VerifyInputs(graph_labeller);
  if (auto host_alloc =
          input(kObjectIndex).node()->TryCast<InlinedAllocation>()) {
    if (input(kValueIndex).node()->Is<InlinedAllocation>()) {
      CHECK_EQ(host_alloc->allocation_block()->allocation_type(),
               AllocationType::kYoung);
    }
  }
}
References CHECK_EQ, kObjectIndex, kValueIndex, v8::internal::kYoung, and v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::VerifyInputs().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 9030 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::kObjectIndex = 0 [static], [constexpr]
Definition at line 9038 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput(), and VerifyInputs().
kProperties
constexpr OpProperties v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanWrite() | OpProperties::DeferredCall()
Definition at line 9028 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::kValueIndex = 1 [static], [constexpr]
Definition at line 9039 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput(), and VerifyInputs().
offset_
const int v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::offset_ [private]
Definition at line 9063 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc