v8::internal::compiler::HeapConstantType Class Reference
#include <turbofan-types.h>
Public Member Functions
Handle< HeapObject > Value () const
HeapObjectRef Ref () const
Private Member Functions
HeapConstantType (BitsetType::bitset bitset, HeapObjectRef heap_ref)
BitsetType::bitset Lub () const
Static Private Member Functions
static HeapConstantType * New (HeapObjectRef heap_ref, BitsetType::bitset bitset, Zone *zone)
Private Attributes
friend Zone
BitsetType::bitset bitset_
HeapObjectRef heap_ref_
Friends
class Type
class BitsetType
Detailed Description
Definition at line 633 of file turbofan-types.h.
Constructor & Destructor Documentation
HeapConstantType()
v8::internal::compiler::HeapConstantType::HeapConstantType (BitsetType::bitset bitset, HeapObjectRef heap_ref) [private]
Definition at line 548 of file turbofan-types.cc.
    : TypeBase(kHeapConstant), bitset_(bitset), heap_ref_(heap_ref) {}
Member Function Documentation
Lub()
BitsetType::bitset v8::internal::compiler::HeapConstantType::Lub () const [inline], [private]
Definition at line 650 of file turbofan-types.h.
{ return bitset_; }
New()
static HeapConstantType* v8::internal::compiler::HeapConstantType::New (HeapObjectRef heap_ref, BitsetType::bitset bitset, Zone * zone) [inline], [static], [private]
Definition at line 643 of file turbofan-types.h.
                                                                    {
    return zone->New<HeapConstantType>(bitset, heap_ref);
  }
References v8::internal::Zone::New().
Ref()
HeapObjectRef v8::internal::compiler::HeapConstantType::Ref () const [inline]
Definition at line 636 of file turbofan-types.h.
{ return heap_ref_; }
Referenced by v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::compiler::Typer::Visitor::JSCallTyper(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), and v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode().
Value()
Handle< HeapObject > v8::internal::compiler::HeapConstantType::Value () const
Definition at line 552 of file turbofan-types.cc.
                                                 {
  return heap_ref_.object();
}
References heap_ref_, and v8::internal::compiler::HeapObjectRef::object().
Friends And Related Function Documentation
BitsetType
friend class BitsetType [friend]
Definition at line 640 of file turbofan-types.h.
Type
friend class Type [friend]
Definition at line 639 of file turbofan-types.h.
Member Data Documentation
bitset_
BitsetType::bitset v8::internal::compiler::HeapConstantType::bitset_ [private]
Definition at line 652 of file turbofan-types.h.
heap_ref_
HeapObjectRef v8::internal::compiler::HeapConstantType::heap_ref_ [private]
Definition at line 653 of file turbofan-types.h.
Referenced by Value().
Zone
friend v8::internal::compiler::HeapConstantType::Zone [private]
Definition at line 641 of file turbofan-types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turbofan-types.h
/mnt/V8SourceCode/src/compiler/turbofan-types.cc