v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes Class Reference
Public Member Functions
PathChecksForEffectNodes (Zone *zone)
EffectPathChecks const * Get (Node *node) const
void Set (Node *node, EffectPathChecks const *checks)
Private Attributes
ZoneVector< EffectPathChecks const * > info_for_node_
Detailed Description
Definition at line 57 of file redundancy-elimination.h.
Constructor & Destructor Documentation
PathChecksForEffectNodes()
v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::PathChecksForEffectNodes (Zone * zone) [inline], [explicit]
Definition at line 59 of file redundancy-elimination.h.
: info_for_node_(zone) {}
Member Function Documentation
Get()
RedundancyElimination::EffectPathChecks const * v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get (Node * node) const
Definition at line 350 of file redundancy-elimination.cc.
                                                                   {
  size_t const id = node->id();
  if (id < info_for_node_.size()) return info_for_node_[id];
  return nullptr;
}
References v8::internal::compiler::Node::id().
Referenced by v8::internal::compiler::RedundancyElimination::Reduce(), v8::internal::compiler::RedundancyElimination::ReduceCheckNode(), v8::internal::compiler::RedundancyElimination::ReduceEffectPhi(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::RedundancyElimination::TakeChecksFromFirstEffect(), and v8::internal::compiler::RedundancyElimination::UpdateChecks().
Set()
void v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Set (Node * node, EffectPathChecks const * checks)
Definition at line 356 of file redundancy-elimination.cc.
                                                {
  size_t const id = node->id();
  if (id >= info_for_node_.size()) info_for_node_.resize(id + 1, nullptr);
  info_for_node_[id] = checks;
}
References v8::internal::compiler::Node::id().
Referenced by v8::internal::compiler::RedundancyElimination::UpdateChecks().
Member Data Documentation
info_for_node_
ZoneVector<EffectPathChecks const*> v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::info_for_node_ [private]
Definition at line 64 of file redundancy-elimination.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/redundancy-elimination.h
/mnt/V8SourceCode/src/compiler/redundancy-elimination.cc