v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor Class Reference
Public Member Functions
MaglevCodeGeneratingNodeProcessor (MaglevAssembler *masm, Zone *zone)
void PreProcessGraph (Graph *graph)
void PostProcessGraph (Graph *graph)
void PostProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
template<typename NodeT >
ProcessResult Process (NodeT *node, const ProcessingState &state)
void EmitBlockEndGapMoves (UnconditionalControlNode *node, const ProcessingState &state)
Isolate * isolate () const
MaglevAssembler * masm () const
MaglevCodeGenState * code_gen_state () const
MaglevGraphLabeller * graph_labeller () const
Private Member Functions
template<typename NodeT >
void PatchJumps (NodeT *node)
int ComputeDeferred (Graph *graph)
Private Attributes
MaglevAssembler *const masm_
Zone * zone_
Detailed Description
Definition at line 710 of file maglev-code-generator.cc.
Constructor & Destructor Documentation
MaglevCodeGeneratingNodeProcessor()
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::MaglevCodeGeneratingNodeProcessor (MaglevAssembler * masm, Zone * zone) [inline]
Definition at line 712 of file maglev-code-generator.cc.
      : masm_(masm), zone_(zone) {}
Member Function Documentation
code_gen_state()
MaglevCodeGenState* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::code_gen_state () const [inline]
Definition at line 1005 of file maglev-code-generator.cc.
                                             {
    return masm()->code_gen_state();
  }
ComputeDeferred()
int v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred (Graph * graph) [inline], [private]
Definition at line 1043 of file maglev-code-generator.cc.
                                    {
    int deferred_count = 0;
    // Propagate deferredness: If a block is deferred, defer all its successors,
    // except if a successor has another predecessor which is not deferred.
    // In addition, if all successors of a block are deferred, defer it too.
    // Work queue is a queue of blocks which are deferred, so we'll need to
    // check whether to defer their successors and predecessors.
    SmallZoneVector<BasicBlock*, 32> work_queue(zone_);
    for (auto block_it = graph->begin(); block_it != graph->end(); ++block_it) {
      BasicBlock* block = *block_it;
      if (block->is_deferred()) {
        ++deferred_count;
        work_queue.emplace_back(block);
      }
    }
    // The algorithm below is O(N * e^2) where e is the maximum number of
    // predecessors / successors. We check whether we should defer a block at
    // most e times. When doing the check, we check each predecessor / successor
    // once.
    while (!work_queue.empty()) {
      BasicBlock* block = work_queue.back();
      work_queue.pop_back();
      DCHECK(block->is_deferred());
      // Check if we should defer any successor.
      block->ForEachSuccessor([&work_queue,
                               &deferred_count](BasicBlock* successor) {
        if (successor->is_deferred()) {
          return;
        }
        bool should_defer = true;
        successor->ForEachPredecessor([&should_defer](BasicBlock* predecessor) {
          if (!predecessor->is_deferred()) {
            should_defer = false;
          }
        });
        if (should_defer) {
          ++deferred_count;
          work_queue.emplace_back(successor);
          successor->set_deferred(true);
        }
      });
      // Check if we should defer any predecessor.
      block->ForEachPredecessor([&work_queue,
                                 &deferred_count](BasicBlock* predecessor) {
        if (predecessor->is_deferred()) {
          return;
        }
        bool should_defer = true;
        predecessor->ForEachSuccessor([&should_defer](BasicBlock* successor) {
          if (!successor->is_deferred()) {
            should_defer = false;
          }
        });
        if (should_defer) {
          ++deferred_count;
          work_queue.emplace_back(predecessor);
          predecessor->set_deferred(true);
        }
      });
    }
    return deferred_count;
  }
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::maglev::BasicBlock::ForEachPredecessor(), v8::internal::maglev::BasicBlock::ForEachSuccessor(), graph(), v8::internal::maglev::BasicBlock::is_deferred(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), and v8::internal::maglev::BasicBlock::set_deferred().
EmitBlockEndGapMoves()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves (UnconditionalControlNode * node, const ProcessingState & state) [inline]
Definition at line 883 of file maglev-code-generator.cc.
                                                          {
    BasicBlock* target = node->target();
    if (!target->has_state()) {
      __ RecordComment("-- Target has no state, must be a fallthrough");
      return;
    }
    int predecessor_id = state.block()->predecessor_id();
    MaglevAssembler::TemporaryRegisterScope temps(masm_);
    Register scratch = temps.AcquireScratch();
    DoubleRegister double_scratch = temps.AcquireScratchDouble();
    // TODO(leszeks): Move these to fields, to allow their data structure
    // allocations to be reused. Will need some sort of state resetting.
    ParallelMoveResolver<Register, false> register_moves(masm_);
    ParallelMoveResolver<DoubleRegister, false> double_register_moves(masm_);
    // Remember what registers were assigned to by a Phi, to avoid clobbering
    // them with RegisterMoves.
    RegList registers_set_by_phis;
    DoubleRegList double_registers_set_by_phis;
    __ RecordComment("-- Gap moves:");
    if (target->has_phi()) {
      Phi::List* phis = target->phis();
      for (Phi* phi : *phis) {
        // Ignore dead phis.
        // TODO(leszeks): We should remove dead phis entirely and turn this into
        // a DCHECK.
        if (!phi->has_valid_live_range()) {
          if (v8_flags.code_comments) {
            std::stringstream ss;
            ss << "-- * "
               << phi->input(state.block()->predecessor_id()).operand() << " → "
               << target << " (n" << graph_labeller()->NodeId(phi)
               << ") [DEAD]";
            __ RecordComment(ss.str());
          }
          continue;
        }
        Input& input = phi->input(state.block()->predecessor_id());
        ValueNode* input_node = input.node();
        compiler::InstructionOperand source = input.operand();
        compiler::AllocatedOperand target_operand =
            compiler::AllocatedOperand::cast(phi->result().operand());
        if (v8_flags.code_comments) {
          std::stringstream ss;
          ss << "-- * " << source << " → " << target << " (n"
             << graph_labeller()->NodeId(phi) << ")";
          __ RecordComment(ss.str());
        }
        if (phi->use_double_register()) {
          DCHECK(!phi->decompresses_tagged_result());
          double_register_moves.RecordMove(input_node, source, target_operand,
                                           false);
        } else {
          register_moves.RecordMove(input_node, source, target_operand,
                                    kDoesNotNeedDecompression);
        }
        if (target_operand.IsAnyRegister()) {
          if (phi->use_double_register()) {
            double_registers_set_by_phis.set(
                target_operand.GetDoubleRegister());
          } else {
            registers_set_by_phis.set(target_operand.GetRegister());
          }
        }
      }
    }
    target->state()->register_state().ForEachGeneralRegister(
        [&](Register reg, RegisterState& state) {
          // Don't clobber registers set by a Phi.
          if (registers_set_by_phis.has(reg)) return;
          ValueNode* node;
          RegisterMerge* merge;
          if (LoadMergeState(state, &node, &merge)) {
            compiler::InstructionOperand source =
                merge->operand(predecessor_id);
            if (v8_flags.code_comments) {
              std::stringstream ss;
              ss << "-- * " << source << " → " << reg;
              __ RecordComment(ss.str());
            }
            register_moves.RecordMove(node, source, reg,
                                      kDoesNotNeedDecompression);
          }
        });
    register_moves.EmitMoves(scratch);
    __ RecordComment("-- Double gap moves:");
    target->state()->register_state().ForEachDoubleRegister(
        [&](DoubleRegister reg, RegisterState& state) {
          // Don't clobber registers set by a Phi.
          if (double_registers_set_by_phis.has(reg)) return;
          ValueNode* node;
          RegisterMerge* merge;
          if (LoadMergeState(state, &node, &merge)) {
            compiler::InstructionOperand source =
                merge->operand(predecessor_id);
            if (v8_flags.code_comments) {
              std::stringstream ss;
              ss << "-- * " << source << " → " << reg;
              __ RecordComment(ss.str());
            }
            double_register_moves.RecordMove(node, source, reg,
                                             kDoesNotNeedDecompression);
          }
        });
    double_register_moves.EmitMoves(double_scratch);
  }
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble(), v8::internal::maglev::ProcessingState::block(), v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::EmitMoves(), v8::internal::compiler::LocationOperand::GetDoubleRegister(), v8::internal::compiler::LocationOperand::GetRegister(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::BasicBlock::has_state(), v8::internal::if(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kDoesNotNeedDecompression, v8::internal::maglev::LoadMergeState(), v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::BasicBlock::phis(), v8::internal::maglev::BasicBlock::predecessor_id(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMove(), v8::internal::maglev::MergePointInterpreterFrameState::register_state(), v8::internal::RegListBase< RegisterT >::set(), v8::internal::maglev::BasicBlock::state(), v8::internal::maglev::UnconditionalControlNode::target(), and v8::internal::v8_flags.
graph_labeller()
MaglevGraphLabeller* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::graph_labeller () const [inline]
Definition at line 1008 of file maglev-code-generator.cc.
                                              {
    return code_gen_state()->graph_labeller();
  }
isolate()
Isolate* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::isolate () const [inline]
Definition at line 1003 of file maglev-code-generator.cc.
{ return masm_->isolate(); }
References v8::internal::Factory::isolate().
masm()
MaglevAssembler* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::masm () const [inline]
Definition at line 1004 of file maglev-code-generator.cc.
{ return masm_; }
PatchJumps()
template<typename NodeT >
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps (NodeT * node) [inline], [private]
Definition at line 1016 of file maglev-code-generator.cc.
                               {
    if constexpr (IsUnconditionalControlNode(Node::opcode_of<NodeT>)) {
      UnconditionalControlNode* control_node =
          node->template Cast<UnconditionalControlNode>();
      control_node->set_target(
          code_gen_state()->RealJumpTarget(control_node->target()));
    } else if constexpr (IsBranchControlNode(Node::opcode_of<NodeT>)) {
      BranchControlNode* control_node =
          node->template Cast<BranchControlNode>();
      control_node->set_if_true(
          code_gen_state()->RealJumpTarget(control_node->if_true()));
      control_node->set_if_false(
          code_gen_state()->RealJumpTarget(control_node->if_false()));
    } else if constexpr (Node::opcode_of<NodeT> == Opcode::kSwitch) {
      Switch* switch_node = node->template Cast<Switch>();
      BasicBlockRef* targets = switch_node->targets();
      for (int i = 0; i < switch_node->size(); ++i) {
        targets[i].set_block_ptr(
            code_gen_state()->RealJumpTarget(targets[i].block_ptr()));
      }
      if (switch_node->has_fallthrough()) {
        switch_node->set_fallthrough(
            code_gen_state()->RealJumpTarget(switch_node->fallthrough()));
      }
    }
  }
References v8::internal::maglev::Switch::fallthrough(), v8::internal::maglev::Switch::has_fallthrough(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::BranchControlNode::if_false(), v8::internal::maglev::BranchControlNode::if_true(), v8::internal::maglev::IsBranchControlNode(), v8::internal::maglev::IsUnconditionalControlNode(), v8::internal::wasm::kSwitch, v8::internal::maglev::BasicBlockRef::set_block_ptr(), v8::internal::maglev::Switch::set_fallthrough(), v8::internal::maglev::BranchControlNode::set_if_false(), v8::internal::maglev::BranchControlNode::set_if_true(), v8::internal::maglev::UnconditionalControlNode::set_target(), v8::internal::maglev::Switch::size(), v8::internal::maglev::UnconditionalControlNode::target(), and v8::internal::maglev::Switch::targets().
PostPhiProcessing()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PostPhiProcessing () [inline]
Definition at line 784 of file maglev-code-generator.cc.
{}
PostProcessBasicBlock()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 783 of file maglev-code-generator.cc.
{}
PostProcessGraph()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PostProcessGraph (Graph * graph) [inline]
Definition at line 782 of file maglev-code-generator.cc.
{}
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 786 of file maglev-code-generator.cc.
                                                             {
    if (block->is_loop()) {
      __ LoopHeaderAlign();
    }
    if (v8_flags.code_comments) {
      std::stringstream ss;
      ss << "-- Block b" << block->id();
      __ RecordComment(ss.str());
    }
    __ BindBlock(block);
    return BlockProcessResult::kContinue;
  }
References __, v8::internal::maglev::BasicBlock::id(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::kContinue, and v8::internal::v8_flags.
PreProcessGraph()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessGraph (Graph * graph) [inline]
Definition at line 715 of file maglev-code-generator.cc.
                                     {
    // TODO(victorgomes): I wonder if we want to create a struct that shares
    // these fields between graph and code_gen_state.
    code_gen_state()->set_untagged_slots(graph->untagged_stack_slots());
    code_gen_state()->set_tagged_slots(graph->tagged_stack_slots());
    code_gen_state()->set_max_deopted_stack_size(
        graph->max_deopted_stack_size());
    code_gen_state()->set_max_call_stack_args_(graph->max_call_stack_args());
    if (v8_flags.maglev_break_on_entry) {
      __ DebugBreak();
    }
    if (graph->is_osr()) {
      __ OSRPrologue(graph);
    } else {
      __ Prologue(graph);
    }
    // "Deferred" computation has to be done before block removal, because
    // block removal doesn't propagate deferredness of removed blocks.
    int deferred_count = ComputeDeferred(graph);
    // If we deferred the first block, un-defer it. This can happen because we
    // defer a block if all its successors are deferred (i.e., lead to an
    // unconditional deopt). E.g., if we only executed exception throwing code
    // paths, the non-exception code paths might be untaken, and thus contain
    // unconditional deopts, so we end up deferring all non-exception code
    // paths, including the first block.
    if (graph->blocks()[0]->is_deferred()) {
      graph->blocks()[0]->set_deferred(false);
      --deferred_count;
    }
    // Reorder the blocks so that dererred blocks are at the end.
    int non_deferred_count = graph->num_blocks() - deferred_count;
    ZoneVector<BasicBlock*> new_blocks(graph->num_blocks(), zone_);
    size_t ix_non_deferred = 0;
    size_t ix_deferred = non_deferred_count;
    for (auto block_it = graph->begin(); block_it != graph->end(); ++block_it) {
      BasicBlock* block = *block_it;
      DCHECK(!block->is_dead());
      if (block->is_deferred()) {
        new_blocks[ix_deferred++] = block;
      } else {
        new_blocks[ix_non_deferred++] = block;
      }
    }
    CHECK_EQ(ix_deferred, graph->num_blocks());
    CHECK_EQ(ix_non_deferred, non_deferred_count);
    graph->set_blocks(new_blocks);
    // Remove empty blocks.
    ZoneVector<BasicBlock*>& blocks = graph->blocks();
    size_t current_ix = 0;
    for (size_t i = 0; i < blocks.size(); ++i) {
      BasicBlock* block = blocks[i];
      if (code_gen_state()->RealJumpTarget(block) == block) {
        // This block cannot be replaced.
        blocks[current_ix++] = block;
      }
    }
    blocks.resize(current_ix);
  }
References __, CHECK_EQ, v8::internal::DCHECK(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::BasicBlock::is_dead(), v8::internal::maglev::BasicBlock::is_deferred(), v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), and v8::internal::v8_flags.
Process()
template<typename NodeT >
ProcessResult v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process (NodeT * node, const ProcessingState & state) [inline]
Definition at line 800 of file maglev-code-generator.cc.
                                                                   {
    if (v8_flags.code_comments) {
      std::stringstream ss;
      ss << "-- " << graph_labeller()->NodeId(node) << ": "
         << PrintNode(graph_labeller(), node);
      __ RecordComment(ss.str());
    }
    if (v8_flags.maglev_assert_stack_size) {
      __ AssertStackSizeCorrect();
    }
    PatchJumps(node);
    // Emit Phi moves before visiting the control node.
    if (std::is_base_of_v<UnconditionalControlNode, NodeT>) {
      EmitBlockEndGapMoves(node->template Cast<UnconditionalControlNode>(),
                           state);
    }
    if (v8_flags.slow_debug_code && !std::is_same_v<NodeT, Phi>) {
      // Check that all int32/uint32 inputs are zero extended.
      // Note that we don't do this for Phis, since they are virtual operations
      // whose inputs aren't actual inputs but are injected on incoming
      // branches. There's thus nothing to verify for the inputs we see for the
      // phi.
      for (Input& input : *node) {
        ValueRepresentation rep =
            input.node()->properties().value_representation();
        if (IsZeroExtendedRepresentation(rep)) {
          // TODO(leszeks): Ideally we'd check non-register inputs too, but
          // AssertZeroExtended needs the scratch register, so we'd have to do
          // some manual push/pop here to free up another register.
          if (input.IsGeneralRegister()) {
            __ AssertZeroExtended(ToRegister(input));
          }
        }
      }
    }
    MaglevAssembler::TemporaryRegisterScope scratch_scope(masm());
    scratch_scope.Include(node->general_temporaries());
    scratch_scope.IncludeDouble(node->double_temporaries());
#ifdef DEBUG
    masm()->set_allow_allocate(node->properties().can_allocate());
    masm()->set_allow_call(node->properties().is_call());
    masm()->set_allow_deferred_call(node->properties().is_deferred_call());
#endif
    node->GenerateCode(masm(), state);
#ifdef DEBUG
    masm()->set_allow_allocate(false);
    masm()->set_allow_call(false);
    masm()->set_allow_deferred_call(false);
#endif
    if (std::is_base_of_v<ValueNode, NodeT>) {
      ValueNode* value_node = node->template Cast<ValueNode>();
      if (value_node->has_valid_live_range() && value_node->is_spilled()) {
        compiler::AllocatedOperand source =
            compiler::AllocatedOperand::cast(value_node->result().operand());
        // We shouldn't spill nodes which already output to the stack.
        if (!source.IsAnyStackSlot()) {
          if (v8_flags.code_comments) __ RecordComment("-- Spill:");
          if (source.IsRegister()) {
            __ Move(masm()->GetStackSlot(value_node->spill_slot()),
                    ToRegister(source));
          } else {
            __ StoreFloat64(masm()->GetStackSlot(value_node->spill_slot()),
                            ToDoubleRegister(source));
          }
        } else {
          // Otherwise, the result source stack slot should be equal to the
          // spill slot.
          DCHECK_EQ(source.index(), value_node->spill_slot().index());
        }
      }
    }
    return ProcessResult::kContinue;
  }
References __, v8::internal::maglev::OpProperties::can_allocate(), v8::internal::compiler::LocationOperand::cast(), DCHECK_EQ, v8::internal::wasm::liftoff::GetStackSlot(), v8::internal::maglev::ValueNode::has_valid_live_range(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Include(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::IncludeDouble(), v8::internal::compiler::LocationOperand::index(), v8::internal::maglev::OpProperties::is_call(), v8::internal::maglev::OpProperties::is_deferred_call(), v8::internal::maglev::ValueNode::is_spilled(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::maglev::IsZeroExtendedRepresentation(), v8::internal::maglev::kContinue, v8::internal::maglev::ValueLocation::operand(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::maglev::NodeTMixin< Base, Derived >::properties(), v8::internal::maglev::ValueNode::result(), v8::internal::maglev::ValueNode::spill_slot(), v8::internal::maglev::ToDoubleRegister(), v8::internal::maglev::ToRegister(), and v8::internal::v8_flags.
Member Data Documentation
masm_
MaglevAssembler* const v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::masm_ [private]
Definition at line 1110 of file maglev-code-generator.cc.
zone_
Zone* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::zone_ [private]
Definition at line 1111 of file maglev-code-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-code-generator.cc