v8::PersistentBase< T > Class Template Reference
An object reference that is independent of any handle scope.
#include <v8-persistent-handle.h>
Public Member Functions
void Reset ()
If non-empty, destroy the underlying storage cell IsEmpty() will return true after this call.
template<class S >
void Reset (Isolate *isolate, const Local< S > &other)
If non-empty, destroy the underlying storage cell and create a new one with the contents of other if other is non empty.
template<class S >
void Reset (Isolate *isolate, const PersistentBase< S > &other)
If non-empty, destroy the underlying storage cell and create a new one with the contents of other if other is non empty.
Local< T > Get (Isolate *isolate) const
template<class S >
bool operator== (const PersistentBase< S > &that) const
template<class S >
bool operator== (const Local< S > &that) const
template<class S >
bool operator!= (const PersistentBase< S > &that) const
template<class S >
bool operator!= (const Local< S > &that) const
template<typename P >
void SetWeak (P *parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type)
Install a finalization callback on this object.
void SetWeak ()
Turns this handle into a weak phantom handle without finalization callback.
template<typename P >
P * ClearWeak ()
void ClearWeak ()
void AnnotateStrongRetainer (const char *label)
Annotates the strong handle with the given label, which is then used by the heap snapshot generator as a name of the edge from the root to the handle.
bool IsWeak () const
Returns true if the handle's reference is weak.
void SetWrapperClassId (uint16_t class_id)
Assigns a wrapper class ID to the handle.
uint16_t WrapperClassId () const
Returns the class ID previously assigned to this handle or 0 if no class ID was previously assigned.
PersistentBase (const PersistentBase &other)=delete
void operator= (const PersistentBase &)=delete
Private Member Functions
PersistentBase ()=default
PersistentBase (internal::Address *location)
Static Private Member Functions
static internal::Address * New (Isolate *isolate, T *that)
Friends
class Isolate
class Utils
template<class F >
class Local
template<class F1 , class F2 >
class Persistent
Persistent is a way to create a strong pointer from an off-heap object to another on-heap object.
template<class F >
class Global
template<class F >
class PersistentBase
template<class F >
class ReturnValue
template<class F1 , class F2 , class F3 >
class PersistentValueMapBase
class Object
class internal::ValueHelper
Additional Inherited Members
Detailed Description
template<class T>
class v8::PersistentBase< T >
An object reference that is independent of any handle scope.
Where a Local handle only lives as long as the HandleScope in which it was allocated, a PersistentBase handle remains valid until it is explicitly disposed using Reset().
A persistent handle contains a reference to a storage cell within the V8 engine which holds an object value and which is updated by the garbage collector whenever the object is moved. A new storage cell can be created using the constructor or PersistentBase::Reset and existing handles can be disposed using PersistentBase::Reset.
Definition at line 93 of file v8-persistent-handle.h.
Constructor & Destructor Documentation
PersistentBase() [1/3]
template<class T >
v8::PersistentBase< T >::PersistentBase (const PersistentBase< T > & other) [delete]
PersistentBase() [2/3]
template<class T >
v8::PersistentBase< T >::PersistentBase () [inline], [private], [default]
PersistentBase() [3/3]
template<class T >
v8::PersistentBase< T >::PersistentBase (internal::Address * location) [inline], [explicit], [private]
Definition at line 214 of file v8-persistent-handle.h.
      : IndirectHandleBase(location) {}
Member Function Documentation
AnnotateStrongRetainer()
template<class T >
void v8::PersistentBase< T >::AnnotateStrongRetainer (const char * label) [inline]
Annotates the strong handle with the given label, which is then used by the heap snapshot generator as a name of the edge from the root to the handle.
The function does not take ownership of the label and assumes that the label is valid as long as the handle is valid.
Definition at line 511 of file v8-persistent-handle.h.
                                                                {
  api_internal::AnnotateStrongRetainer(this->slot(), label);
}
References v8::api_internal::AnnotateStrongRetainer().
Referenced by v8::PersistentValueMapBase< K, V, Traits >::AnnotateStrongRetainer(), v8_inspector::InjectedScript::commandLineAPI(), v8::Shell::CreateRealm(), v8_inspector::V8DebuggerScript::Initialize(), v8_inspector::InjectedScript::setLastEvaluationResult(), and v8_inspector::InjectedScript::wrapEvaluateResult().
ClearWeak() [1/2]
template<class T >
template<typename P >
P * v8::PersistentBase< T >::ClearWeak [inline]
Definition at line 506 of file v8-persistent-handle.h.
                                {
  return reinterpret_cast<P*>(api_internal::ClearWeak(this->slot()));
}
References v8::api_internal::ClearWeak(), and P.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback().
ClearWeak() [2/2]
template<class T >
void v8::PersistentBase< T >::ClearWeak () [inline]
Definition at line 167 of file v8-persistent-handle.h.
{ ClearWeak<void>(); }
Get()
template<class T >
Local<T> v8::PersistentBase< T >::Get (Isolate * isolate) const [inline]
Definition at line 115 of file v8-persistent-handle.h.
                                                 {
    return Local<T>::New(isolate, *this);
  }
References v8::Local< T >::New().
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::AddBreakpoint(), v8_inspector::InspectedContext::addInternalObject(), v8::AsyncHooksWrap::after_function(), v8_inspector::V8InspectorImpl::associateExceptionData(), v8::AsyncHooksWrap::before_function(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::InjectedScript::commandLineAPI(), v8_inspector::InspectedContext::context(), v8::Shell::DoHostImportModuleDynamically(), v8_inspector::V8InspectorImpl::exceptionMetaDataContext(), v8::SourceGroup::ExecuteInThread(), v8::Shell::ExecuteModule(), v8::Shell::FinishExecuting(), v8_inspector::V8InspectorImpl::getAssociatedExceptionData(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetFirstWasmInstance(), v8_inspector::InspectedContext::getInternalType(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetModuleName(), v8_inspector::V8DebuggerScript::getPossibleBreakpoints(), v8_inspector::V8DebuggerScript::hash(), v8::AsyncHooksWrap::init_function(), v8::InspectorClient::InspectorClient(), v8_inspector::InjectedScript::lastEvaluationResult(), v8_inspector::V8DebuggerScript::length(), v8_inspector::V8DebuggerScript::location(), v8_inspector::V8Regex::match(), v8::internal::MeasureMemoryDelegate::MeasurementComplete(), v8_inspector::V8DebuggerScript::offset(), v8::anonymous_namespace{d8.cc}::ModuleEmbedderData::ModuleGlobalHash::operator()(), v8::AsyncHooksWrap::promiseResolve_function(), v8_inspector::V8InspectorImpl::regexContext(), v8::internal::wasm::gdb_server::WasmModuleDebug::RemoveBreakpoint(), v8_inspector::V8Debugger::reportTermination(), v8_inspector::V8DebuggerScript::resetBlackboxedStateCache(), v8::Shell::RunMainIsolate(), v8::Shell::RunShell(), v8_inspector::V8DebuggerScript::script(), v8_inspector::V8DebuggerScript::setSource(), v8::internal::MeasureMemoryDelegate::ShouldMeasure(), v8_inspector::V8DebuggerScript::source(), v8_inspector::V8Console::taskInfoKey(), v8_inspector::V8Console::taskTemplate(), v8_inspector::InjectedScript::wrapObjectMirror(), and v8_inspector::V8Debugger::~V8Debugger().
IsWeak()
template<class T >
bool v8::PersistentBase< T >::IsWeak [inline]
Returns true if the handle's reference is weak.
Definition at line 442 of file v8-persistent-handle.h.
                                     {
  using I = internal::Internals;
  if (this->IsEmpty()) return false;
  return I::GetNodeState(this->slot()) == I::kNodeStateIsWeakValue;
}
References I.
Referenced by v8::internal::FutexWaitListNode::AsyncState::AsyncState(), and v8::PersistentValueMapBase< K, V, Traits >::Release().
New()
template<class T >
internal::Address * v8::PersistentBase< T >::New (Isolate * isolate, T * that) [inline], [static], [private]
Definition at line 424 of file v8-persistent-handle.h.
                                                                 {
  if (internal::ValueHelper::IsEmpty(that)) return nullptr;
  return api_internal::GlobalizeReference(
      reinterpret_cast<internal::Isolate*>(isolate),
      internal::ValueHelper::ValueAsAddress(that));
}
References v8::api_internal::GlobalizeReference(), v8::internal::ValueHelper::IsEmpty(), and v8::internal::ValueHelper::ValueAsAddress().
operator!=() [1/2]
template<class T >
template<class S >
bool v8::PersistentBase< T >::operator!= (const Local< S > & that) const [inline]
Definition at line 135 of file v8-persistent-handle.h.
                                                        {
    return !operator==(that);
  }
References v8::PersistentBase< T >::operator==().
operator!=() [2/2]
template<class T >
template<class S >
bool v8::PersistentBase< T >::operator!= (const PersistentBase< S > & that) const [inline]
Definition at line 130 of file v8-persistent-handle.h.
                                                                 {
    return !operator==(that);
  }
References v8::PersistentBase< T >::operator==().
operator=()
template<class T >
void v8::PersistentBase< T >::operator= (const PersistentBase< T > &) [delete]
operator==() [1/2]
template<class T >
template<class S >
bool v8::PersistentBase< T >::operator== (const Local< S > & that) const [inline]
Definition at line 125 of file v8-persistent-handle.h.
                                                        {
    return internal::HandleHelper::EqualHandles(*this, that);
  }
References v8::internal::HandleHelper::EqualHandles().
operator==() [2/2]
template<class T >
template<class S >
bool v8::PersistentBase< T >::operator== (const PersistentBase< S > & that) const [inline]
Definition at line 120 of file v8-persistent-handle.h.
                                                                 {
    return internal::HandleHelper::EqualHandles(*this, that);
  }
References v8::internal::HandleHelper::EqualHandles().
Referenced by v8::PersistentBase< T >::operator!=().
Reset() [1/3]
template<class T >
void v8::PersistentBase< T >::Reset [inline]
If non-empty, destroy the underlying storage cell IsEmpty() will return true after this call.
Definition at line 449 of file v8-persistent-handle.h.
                              {
  if (this->IsEmpty()) return;
  api_internal::DisposeGlobal(this->slot());
  this->Clear();
}
References v8::api_internal::DisposeGlobal().
Referenced by v8_inspector::InspectedContext::addInternalObject(), v8_inspector::V8InspectorImpl::associateExceptionData(), v8_inspector::InjectedScript::commandLineAPI(), v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8::Shell::CreateRealm(), v8::Shell::DoHostImportModuleDynamically(), v8_inspector::V8InspectorImpl::exceptionMetaDataContext(), v8::SourceGroup::ExecuteInThread(), v8::Shell::ExecuteModule(), v8::Shell::ExecuteString(), v8_inspector::V8DebuggerScript::Initialize(), v8_inspector::V8Debugger::installTerminateExecutionCallbacks(), v8_inspector::V8InspectorImpl::regexContext(), v8_inspector::InjectedScript::releaseObjectGroup(), v8::PersistentValueMapBase< K, V, Traits >::RemoveWeak(), v8_inspector::V8Debugger::reportTermination(), v8::Shell::RunMainIsolate(), v8::Shell::RunShell(), v8::AsyncHooksWrap::set_after_function(), v8::AsyncHooksWrap::set_before_function(), v8::AsyncHooksWrap::set_init_function(), v8::AsyncHooksWrap::set_promiseResolve_function(), v8_inspector::InjectedScript::setLastEvaluationResult(), v8_inspector::V8Console::taskInfoKey(), v8_inspector::V8Console::taskTemplate(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8_inspector::V8Regex::V8Regex(), v8_inspector::V8DebuggerScript::WeakCallback(), v8_inspector::InjectedScript::wrapEvaluateResult(), v8::Global< T >::~Global(), and v8::Persistent< T, M >::~Persistent().
Reset() [2/3]
template<class T >
template<class S >
void v8::PersistentBase< T >::Reset (Isolate * isolate, const Local< S > & other) [inline]
If non-empty, destroy the underlying storage cell and create a new one with the contents of other if other is non empty.
Definition at line 461 of file v8-persistent-handle.h.
                                                                     {
  static_assert(std::is_base_of_v<T, S>, "type check");
  Reset();
  if (other.IsEmpty()) return;
  this->slot() = New(isolate, *other);
}
References v8::api_internal::IndirectHandleBase::IsEmpty(), and v8::internal::anonymous_namespace{intl-objects.cc}::New().
Reset() [3/3]
template<class T >
template<class S >
void v8::PersistentBase< T >::Reset (Isolate * isolate, const PersistentBase< S > & other) [inline]
If non-empty, destroy the underlying storage cell and create a new one with the contents of other if other is non empty.
Definition at line 474 of file v8-persistent-handle.h.
                                                              {
  static_assert(std::is_base_of_v<T, S>, "type check");
  Reset();
  if (other.IsEmpty()) return;
  this->slot() = New(isolate, other.template value<S>());
}
References v8::api_internal::IndirectHandleBase::IsEmpty(), and v8::internal::anonymous_namespace{intl-objects.cc}::New().
SetWeak() [1/2]
template<class T >
void v8::PersistentBase< T >::SetWeak [inline]
Turns this handle into a weak phantom handle without finalization callback.
The handle will be reset automatically when the garbage collector detects that the object is no longer reachable.
Definition at line 500 of file v8-persistent-handle.h.
                                {
  api_internal::MakeWeak(&this->slot());
}
References v8::api_internal::MakeWeak().
SetWeak() [2/2]
template<class T >
template<typename P >
void v8::PersistentBase< T >::SetWeak (P * parameter, typename WeakCallbackInfo< P >::Callback callback, WeakCallbackType type) [inline]
Install a finalization callback on this object.
NOTE: There is no guarantee as to when or even if the callback is invoked. The invocation is performed solely on a best effort basis. As always, GC-based finalization should not be relied upon for any critical form of resource management!
The callback is supposed to reset the handle. No further V8 API may be called in this callback. In case additional work involving V8 needs to be done, a second callback can be scheduled using WeakCallbackInfo<void>::SetSecondPassCallback.
Definition at line 484 of file v8-persistent-handle.h.
                           {
  using Callback = WeakCallbackInfo<void>::Callback;
#if (__GNUC__ >= 8) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-function-type"
#endif
  api_internal::MakeWeak(this->slot(), parameter,
                         reinterpret_cast<Callback>(callback), type);
#if (__GNUC__ >= 8) && !defined(__clang__)
#pragma GCC diagnostic pop
#endif
}
References v8::api_internal::MakeWeak(), and v8::internal::tracing::type.
Referenced by v8::internal::anonymous_namespace{futex-emulation.cc}::GetWeakGlobal(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::GetWeakGlobal(), v8_inspector::InspectedContext::InspectedContext(), v8_inspector::V8Debugger::installTerminateExecutionCallbacks(), v8_inspector::V8DebuggerScript::MakeWeak(), v8_inspector::InjectedScript::ProtocolPromiseHandler::ProtocolPromiseHandler(), and v8_inspector::TaskInfo::TaskInfo().
SetWrapperClassId()
template<class T >
void v8::PersistentBase< T >::SetWrapperClassId (uint16_t class_id) [inline]
Assigns a wrapper class ID to the handle.
Definition at line 516 of file v8-persistent-handle.h.
                                                           {
  using I = internal::Internals;
  if (this->IsEmpty()) return;
  uint8_t* addr = reinterpret_cast<uint8_t*>(slot()) + I::kNodeClassIdOffset;
  *reinterpret_cast<uint16_t*>(addr) = class_id;
}
References I.
WrapperClassId()
template<class T >
uint16_t v8::PersistentBase< T >::WrapperClassId [inline]
Returns the class ID previously assigned to this handle or 0 if no class ID was previously assigned.
Definition at line 524 of file v8-persistent-handle.h.
                                                 {
  using I = internal::Internals;
  if (this->IsEmpty()) return 0;
  uint8_t* addr = reinterpret_cast<uint8_t*>(slot()) + I::kNodeClassIdOffset;
  return *reinterpret_cast<uint16_t*>(addr);
}
References I.
Friends And Related Function Documentation
Global
template<class T >
template<class F >
friend class Global [friend]
Definition at line 202 of file v8-persistent-handle.h.
internal::ValueHelper
template<class T >
friend class internal::ValueHelper [friend]
Definition at line 210 of file v8-persistent-handle.h.
Isolate
template<class T >
friend class Isolate [friend]
Definition at line 195 of file v8-persistent-handle.h.
Local
template<class T >
template<class F >
friend class Local [friend]
Definition at line 198 of file v8-persistent-handle.h.
Object
template<class T >
friend class Object [friend]
Definition at line 209 of file v8-persistent-handle.h.
Persistent
template<class T >
template<class F1 , class F2 >
friend class Persistent [friend]
Persistent is a way to create a strong pointer from an off-heap object to another on-heap object.
As long as the Persistent handle is alive the GC will keep the object pointed to alive. The Persistent handle is always a GC root from the point of view of the GC. Persistent must be constructed and destructed in the same thread.
Definition at line 200 of file v8-persistent-handle.h.
PersistentBase
template<class T >
template<class F >
friend class PersistentBase [friend]
Definition at line 204 of file v8-persistent-handle.h.
PersistentValueMapBase
template<class T >
template<class F1 , class F2 , class F3 >
friend class PersistentValueMapBase [friend]
Definition at line 208 of file v8-persistent-handle.h.
ReturnValue
template<class T >
template<class F >
friend class ReturnValue [friend]
Definition at line 206 of file v8-persistent-handle.h.
Utils
template<class T >
friend class Utils [friend]
Definition at line 196 of file v8-persistent-handle.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-local-handle.h
/mnt/V8SourceCode/include/v8-persistent-handle.h