v8::internal::ObjectPostProcessor Class Reference
Public Member Functions
ObjectPostProcessor (Isolate *isolate)
void Finalize ()
void PostProcessIfNeeded (Tagged< HeapObject > o, InstanceType instance_type)
Private Member Functions
Address GetAnyExternalReferenceAt (int index, bool is_api_reference) const
void DecodeExternalPointerSlot (Tagged< HeapObject > host, ExternalPointerSlot slot)
void DecodeLazilyInitializedExternalPointerSlot (Tagged< HeapObject > host, ExternalPointerSlot slot)
void PostProcessAccessorInfo (Tagged< AccessorInfo > o)
void PostProcessInterceptorInfo (Tagged< InterceptorInfo > o)
void PostProcessJSExternalObject (Tagged< JSExternalObject > o)
void PostProcessFunctionTemplateInfo (Tagged< FunctionTemplateInfo > o)
void PostProcessCode (Tagged< Code > o)
void PostProcessSharedFunctionInfo (Tagged< SharedFunctionInfo > o)
Private Attributes
Isolate *const isolate_
const EmbeddedData embedded_data_
Detailed Description
Definition at line 198 of file read-only-deserializer.cc.
Constructor & Destructor Documentation
ObjectPostProcessor()
v8::internal::ObjectPostProcessor::ObjectPostProcessor (Isolate * isolate) [inline], [explicit]
Definition at line 200 of file read-only-deserializer.cc.
      : isolate_(isolate), embedded_data_(EmbeddedData::FromBlob(isolate_)) {}
Member Function Documentation
DecodeExternalPointerSlot()
void v8::internal::ObjectPostProcessor::DecodeExternalPointerSlot (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [private]
Definition at line 253 of file read-only-deserializer.cc.
                                                           {
    // Constructing no_gc here is not the intended use pattern (instead we
    // should pass it along the entire callchain); but there's little point of
    // doing that here - all of the code in this file relies on GC being
    // disabled, and that's guarded at entry points.
    DisallowGarbageCollection no_gc;
    auto encoded = ro::EncodedExternalReference::FromUint32(
        slot.GetContentAsIndexAfterDeserialization(no_gc));
    Address slot_value =
        GetAnyExternalReferenceAt(encoded.index, encoded.is_api_reference);
    DCHECK(slot.ExactTagIsKnown());
    slot.init(isolate_, host, slot_value, slot.exact_tag());
#ifdef V8_ENABLE_SANDBOX
    // Register these slots during deserialization s.t. later isolates (which
    // share the RO space we are currently deserializing) can properly
    // initialize their external pointer table RO space. Note that slot values
    // are only fully finalized at the end of deserialization, thus we only
    // register the slot itself now and read the handle/value in Finalize.
    external_pointer_slots_.emplace_back(slot);
#endif // V8_ENABLE_SANDBOX
  }
References v8::internal::DCHECK(), v8::internal::ExternalPointerSlot::exact_tag(), v8::internal::ExternalPointerSlot::ExactTagIsKnown(), v8::internal::ro::EncodedExternalReference::FromUint32(), GetAnyExternalReferenceAt(), v8::internal::ExternalPointerSlot::GetContentAsIndexAfterDeserialization(), v8::internal::ExternalPointerSlot::init(), isolate_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by PostProcessAccessorInfo(), PostProcessFunctionTemplateInfo(), and PostProcessJSExternalObject().
DecodeLazilyInitializedExternalPointerSlot()
void v8::internal::ObjectPostProcessor::DecodeLazilyInitializedExternalPointerSlot (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [private]
Definition at line 275 of file read-only-deserializer.cc.
                                                                            {
    // Constructing no_gc here is not the intended use pattern (instead we
    // should pass it along the entire callchain); but there's little point of
    // doing that here - all of the code in this file relies on GC being
    // disabled, and that's guarded at entry points.
    DisallowGarbageCollection no_gc;
    auto encoded = ro::EncodedExternalReference::FromUint32(
        slot.GetContentAsIndexAfterDeserialization(no_gc));
    Address slot_value =
        GetAnyExternalReferenceAt(encoded.index, encoded.is_api_reference);
    DCHECK(slot.ExactTagIsKnown());
    if (slot_value == kNullAddress) {
      slot.init_lazily_initialized();
    } else {
      slot.init(isolate_, host, slot_value, slot.exact_tag());
#ifdef V8_ENABLE_SANDBOX
      // Register these slots during deserialization s.t. later isolates (which
      // share the RO space we are currently deserializing) can properly
      // initialize their external pointer table RO space. Note that slot values
      // are only fully finalized at the end of deserialization, thus we only
      // register the slot itself now and read the handle/value in Finalize.
      external_pointer_slots_.emplace_back(slot);
#endif // V8_ENABLE_SANDBOX
    }
  }
References v8::internal::DCHECK(), v8::internal::ExternalPointerSlot::exact_tag(), v8::internal::ExternalPointerSlot::ExactTagIsKnown(), v8::internal::ro::EncodedExternalReference::FromUint32(), GetAnyExternalReferenceAt(), v8::internal::ExternalPointerSlot::GetContentAsIndexAfterDeserialization(), v8::internal::ExternalPointerSlot::init(), v8::internal::ExternalPointerSlot::init_lazily_initialized(), isolate_, v8::internal::kNullAddress, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Finalize()
void v8::internal::ObjectPostProcessor::Finalize () [inline]
Definition at line 203 of file read-only-deserializer.cc.
                  {
#ifdef V8_ENABLE_SANDBOX
    std::vector<ReadOnlyArtifacts::ExternalPointerRegistryEntry> registry;
    registry.reserve(external_pointer_slots_.size());
    for (auto& slot : external_pointer_slots_) {
      registry.emplace_back(slot.Relaxed_LoadHandle(), slot.load(isolate_),
                            slot.exact_tag());
    }
    isolate_->read_only_artifacts()->set_external_pointer_registry(
        std::move(registry));
#endif // V8_ENABLE_SANDBOX
  }
References isolate_, v8::internal::Isolate::read_only_artifacts(), and v8::internal::ReadOnlyArtifacts::set_external_pointer_registry().
Referenced by v8::internal::ReadOnlyDeserializer::PostProcessNewObjects().
GetAnyExternalReferenceAt()
Address v8::internal::ObjectPostProcessor::GetAnyExternalReferenceAt (int index, bool is_api_reference) const [inline], [private]
Definition at line 238 of file read-only-deserializer.cc.
                                                                            {
    if (is_api_reference) {
      const intptr_t* refs = isolate_->api_external_references();
      Address address =
          refs == nullptr
              ? reinterpret_cast<Address>(NoExternalReferencesCallback)
              : static_cast<Address>(refs[index]);
      DCHECK_NE(address, kNullAddress);
      return address;
    }
    // Note we allow `address` to be kNullAddress since some of our tests
    // rely on this (e.g. when testing an incompletely initialized ER table).
    return isolate_->external_reference_table_unsafe()->address(index);
  }
References v8::internal::ExternalReferenceTable::address(), DCHECK_NE, v8::internal::Isolate::external_reference_table_unsafe(), v8::internal::index, isolate_, v8::internal::kNullAddress, and v8::internal::NoExternalReferencesCallback().
Referenced by DecodeExternalPointerSlot(), and DecodeLazilyInitializedExternalPointerSlot().
PostProcessAccessorInfo()
void v8::internal::ObjectPostProcessor::PostProcessAccessorInfo (Tagged< AccessorInfo > o) [inline], [private]
Definition at line 301 of file read-only-deserializer.cc.
                                                       {
    DecodeExternalPointerSlot(
        o, o->RawExternalPointerField(AccessorInfo::kSetterOffset,
                                      kAccessorInfoSetterTag));
    DecodeExternalPointerSlot(o, o->RawExternalPointerField(
                                     AccessorInfo::kMaybeRedirectedGetterOffset,
                                     kAccessorInfoGetterTag));
    if (USE_SIMULATOR_BOOL) o->init_getter_redirection(isolate_);
  }
References DecodeExternalPointerSlot(), isolate_, v8::internal::kAccessorInfoGetterTag, v8::internal::kAccessorInfoSetterTag, v8::internal::kSetterOffset, and USE_SIMULATOR_BOOL.
PostProcessCode()
void v8::internal::ObjectPostProcessor::PostProcessCode (Tagged< Code > o) [inline], [private]
Definition at line 363 of file read-only-deserializer.cc.
                                       {
    o->init_self_indirect_pointer(isolate_);
    o->wrapper()->set_code(o);
    // RO space only contains builtin Code objects which don't have an
    // attached InstructionStream.
    DCHECK(o->is_builtin());
    DCHECK(!o->has_instruction_stream());
    o->SetInstructionStartForOffHeapBuiltin(
        isolate_,
        EmbeddedData::FromBlob(isolate_).InstructionStartOf(o->builtin_id()));
#if V8_ENABLE_GEARBOX
    UpdateGearboxPlaceholderBuiltin(o);
#endif
  }
References v8::internal::DCHECK(), v8::internal::EmbeddedData::FromBlob(), and isolate_.
PostProcessFunctionTemplateInfo()
void v8::internal::ObjectPostProcessor::PostProcessFunctionTemplateInfo (Tagged< FunctionTemplateInfo > o) [inline], [private]
Definition at line 328 of file read-only-deserializer.cc.
                                                                       {
    DecodeExternalPointerSlot(
        o, o->RawExternalPointerField(
               FunctionTemplateInfo::kMaybeRedirectedCallbackOffset,
               kFunctionTemplateInfoCallbackTag));
    if (USE_SIMULATOR_BOOL) o->init_callback_redirection(isolate_);
  }
References DecodeExternalPointerSlot(), isolate_, v8::internal::kFunctionTemplateInfoCallbackTag, and USE_SIMULATOR_BOOL.
PostProcessIfNeeded()
void v8::internal::ObjectPostProcessor::PostProcessIfNeeded (Tagged< HeapObject > o, InstanceType instance_type) [inline]
Definition at line 224 of file read-only-deserializer.cc.
                                                                 {
    DCHECK_EQ(o->map(isolate_)->instance_type(), instance_type);
#define V(TYPE) \
  if (InstanceTypeChecker::Is##TYPE(instance_type)) { \
    return PostProcess##TYPE(Cast<TYPE>(o)); \
  }
    POST_PROCESS_TYPE_LIST(V)
#undef V
    // If we reach here, no postprocessing is needed for this object.
  }
References DCHECK_EQ, isolate_, and POST_PROCESS_TYPE_LIST.
Referenced by v8::internal::ReadOnlyDeserializer::PostProcessNewObjects().
PostProcessInterceptorInfo()
void v8::internal::ObjectPostProcessor::PostProcessInterceptorInfo (Tagged< InterceptorInfo > o) [inline], [private]
Definition at line 310 of file read-only-deserializer.cc.
                                                             {
    const bool is_named = o->is_named();
#define PROCESS_FIELD(Name, name) \
  DecodeLazilyInitializedExternalPointerSlot(\
      o, o->RawExternalPointerField(\
             InterceptorInfo::k##Name##Offset, \
             is_named ? kApiNamedProperty##Name##CallbackTag \
                      : kApiIndexedProperty##Name##CallbackTag));
    INTERCEPTOR_INFO_CALLBACK_LIST(PROCESS_FIELD)
#undef PROCESS_FIELD
  }
References INTERCEPTOR_INFO_CALLBACK_LIST, v8::internal::is_named(), and PROCESS_FIELD.
PostProcessJSExternalObject()
void v8::internal::ObjectPostProcessor::PostProcessJSExternalObject (Tagged< JSExternalObject > o) [inline], [private]
Definition at line 323 of file read-only-deserializer.cc.
                                                               {
    DecodeExternalPointerSlot(
        o, o->RawExternalPointerField(JSExternalObject::kValueOffset,
                                      kExternalObjectValueTag));
  }
References DecodeExternalPointerSlot(), and v8::internal::kExternalObjectValueTag.
PostProcessSharedFunctionInfo()
void v8::internal::ObjectPostProcessor::PostProcessSharedFunctionInfo (Tagged< SharedFunctionInfo > o) [inline], [private]
Definition at line 378 of file read-only-deserializer.cc.
                                                                   {
    // Reset the id to avoid collisions - it must be unique in this isolate.
    o->set_unique_id(isolate_->GetAndIncNextUniqueSfiId());
  }
References v8::internal::Isolate::GetAndIncNextUniqueSfiId(), and isolate_.
Member Data Documentation
embedded_data_
const EmbeddedData v8::internal::ObjectPostProcessor::embedded_data_ [private]
Definition at line 384 of file read-only-deserializer.cc.
isolate_
Isolate* const v8::internal::ObjectPostProcessor::isolate_ [private]
Definition at line 383 of file read-only-deserializer.cc.
Referenced by DecodeExternalPointerSlot(), DecodeLazilyInitializedExternalPointerSlot(), Finalize(), GetAnyExternalReferenceAt(), PostProcessAccessorInfo(), PostProcessCode(), PostProcessFunctionTemplateInfo(), PostProcessIfNeeded(), and PostProcessSharedFunctionInfo().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/read-only-deserializer.cc