v8::base::DiyFp Class Reference
#include <diy-fp.h>
Public Member Functions
constexpr DiyFp ()
constexpr DiyFp (uint64_t f, int e)
void Subtract (const DiyFp &other)
V8_BASE_EXPORT void Multiply (const DiyFp &other)
void Normalize ()
constexpr uint64_t f () const
constexpr int e () const
constexpr void set_f (uint64_t new_value)
constexpr void set_e (int new_value)
Static Public Member Functions
static DiyFp Minus (const DiyFp &a, const DiyFp &b)
static DiyFp Times (const DiyFp &a, const DiyFp &b)
static DiyFp Normalize (const DiyFp &a)
Static Public Attributes
static const int kSignificandSize = 64
Private Attributes
uint64_t f_
int e_
Static Private Attributes
static const uint64_t kUint64MSB = static_cast<uint64_t>(1) << 63
Detailed Description
Definition at line 20 of file diy-fp.h.
Constructor & Destructor Documentation
DiyFp() [1/2]
constexpr v8::base::DiyFp::DiyFp () [inline], [constexpr]
Definition at line 24 of file diy-fp.h.
: f_(0), e_(0) {}
DiyFp() [2/2]
constexpr v8::base::DiyFp::DiyFp (uint64_t f, int e) [inline], [constexpr]
Definition at line 25 of file diy-fp.h.
: f_(f), e_(e) {}
Member Function Documentation
e()
constexpr int v8::base::DiyFp::e () const [inline], [constexpr]
Definition at line 92 of file diy-fp.h.
{ return e_; }
References e_.
Referenced by v8::base::BignumStrtod(), v8::base::DigitGen(), v8::base::DigitGenCounted(), v8::base::DiyFpStrtod(), v8::base::Double::DiyFpToUint64(), v8::base::Grisu3(), v8::base::Grisu3Counted(), Normalize(), and v8::base::Double::NormalizedBoundaries().
f()
constexpr uint64_t v8::base::DiyFp::f () const [inline], [constexpr]
Definition at line 91 of file diy-fp.h.
{ return f_; }
References f_.
Referenced by v8::base::BignumStrtod(), v8::base::DigitGen(), v8::base::DigitGenCounted(), v8::base::DiyFpStrtod(), v8::base::Double::DiyFpToUint64(), Normalize(), and v8::base::Double::NormalizedBoundaries().
Minus()
static DiyFp v8::base::DiyFp::Minus (const DiyFp & a, const DiyFp & b) [inline], [static]
Definition at line 40 of file diy-fp.h.
                                                     {
    DiyFp result = a;
    result.Subtract(b);
    return result;
  }
References v8::base::internal::result.
Referenced by v8::base::DigitGen().
Multiply()
void v8::base::DiyFp::Multiply (const DiyFp & other)
Definition at line 12 of file diy-fp.cc.
                                       {
  // Simply "emulates" a 128 bit multiplication.
  // However: the resulting number only contains 64 bits. The least
  // significant 64 bits are only used for rounding the most significant 64
  // bits.
  const uint64_t kM32 = 0xFFFFFFFFu;
  uint64_t a = f_ >> 32;
  uint64_t b = f_ & kM32;
  uint64_t c = other.f_ >> 32;
  uint64_t d = other.f_ & kM32;
  uint64_t ac = a * c;
  uint64_t bc = b * c;
  uint64_t ad = a * d;
  uint64_t bd = b * d;
  uint64_t tmp = (bd >> 32) + (ad & kM32) + (bc & kM32);
  // By adding 1U << 31 to tmp we round the final result.
  // Halfway cases will be round up.
  tmp += 1U << 31;
  uint64_t result_f = ac + (ad >> 32) + (bc >> 32) + (tmp >> 32);
  e_ += other.e_ + 64;
  f_ = result_f;
}
References e_, and f_.
Referenced by v8::base::DiyFpStrtod().
Normalize() [1/2]
void v8::base::DiyFp::Normalize () [inline]
Definition at line 65 of file diy-fp.h.
                   {
    DCHECK_NE(f_, 0);
    uint64_t f = f_;
    int e = e_;
    // This method is mainly called for normalizing boundaries. In general
    // boundaries need to be shifted by 10 bits. We thus optimize for this case.
    const uint64_t k10MSBits = static_cast<uint64_t>(0x3FF) << 54;
    while ((f & k10MSBits) == 0) {
      f <<= 10;
      e -= 10;
    }
    while ((f & kUint64MSB) == 0) {
      f <<= 1;
      e--;
    }
    f_ = f;
    e_ = e;
  }
References DCHECK_NE, e(), e_, f(), f_, and kUint64MSB.
Referenced by v8::base::DiyFpStrtod(), and v8::base::Double::NormalizedBoundaries().
Normalize() [2/2]
static DiyFp v8::base::DiyFp::Normalize (const DiyFp & a) [inline], [static]
Definition at line 85 of file diy-fp.h.
                                         {
    DiyFp result = a;
    result.Normalize();
    return result;
  }
References v8::base::internal::result.
set_e()
constexpr void v8::base::DiyFp::set_e (int new_value) [inline], [constexpr]
Definition at line 95 of file diy-fp.h.
{ e_ = new_value; }
References e_.
Referenced by v8::base::DiyFpStrtod(), and v8::base::Double::NormalizedBoundaries().
set_f()
constexpr void v8::base::DiyFp::set_f (uint64_t new_value) [inline], [constexpr]
Definition at line 94 of file diy-fp.h.
{ f_ = new_value; }
References f_.
Referenced by v8::base::DigitGen(), v8::base::DiyFpStrtod(), and v8::base::Double::NormalizedBoundaries().
Subtract()
void v8::base::DiyFp::Subtract (const DiyFp & other) [inline]
Definition at line 31 of file diy-fp.h.
                                    {
    DCHECK(e_ == other.e_);
    DCHECK(f_ >= other.f_);
    f_ -= other.f_;
  }
References DCHECK, e_, and f_.
Times()
static DiyFp v8::base::DiyFp::Times (const DiyFp & a, const DiyFp & b) [inline], [static]
Definition at line 50 of file diy-fp.h.
                                                     {
#ifdef __SIZEOF_INT128__
    // If we have compiler-assisted 64x64 -> 128 muls (e.g. x86-64 and
    // aarch64), we can use that for a faster, inlined implementation.
    // This rounds the same way as Multiply().
    uint64_t hi = (a.f_ * static_cast<unsigned __int128>(b.f_)) >> 64;
    uint64_t lo = (a.f_ * static_cast<unsigned __int128>(b.f_));
    return {hi + (lo >> 63), a.e_ + b.e_ + 64};
#else
    DiyFp result = a;
    result.Multiply(b);
    return result;
#endif
  }
References e_, f_, v8::internal::hi, v8::internal::lo, and v8::base::internal::result.
Referenced by v8::base::Grisu3(), and v8::base::Grisu3Counted().
Member Data Documentation
e_
int v8::base::DiyFp::e_ [private]
Definition at line 101 of file diy-fp.h.
Referenced by e(), Multiply(), Normalize(), set_e(), Subtract(), and Times().
f_
uint64_t v8::base::DiyFp::f_ [private]
Definition at line 100 of file diy-fp.h.
Referenced by f(), Multiply(), Normalize(), set_f(), Subtract(), and Times().
kSignificandSize
const int v8::base::DiyFp::kSignificandSize = 64 [static]
Definition at line 22 of file diy-fp.h.
Referenced by v8::base::Double::AsNormalizedDiyFp(), v8::base::DigitGen(), v8::base::DigitGenCounted(), v8::base::DiyFpStrtod(), v8::base::PowersOfTenCache::GetCachedPowerForBinaryExponentRange(), v8::base::Grisu3(), and v8::base::Grisu3Counted().
kUint64MSB
const uint64_t v8::base::DiyFp::kUint64MSB = static_cast<uint64_t>(1) << 63 [static], [private]
Definition at line 98 of file diy-fp.h.
Referenced by Normalize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/numbers/diy-fp.h
/mnt/V8SourceCode/src/base/numbers/diy-fp.cc