v8::internal::ConstructorBuiltinsAssembler Class Reference
#include <builtins-constructor-gen.h>
Public Member Functions
ConstructorBuiltinsAssembler (compiler::CodeAssemblerState *state)
TNode< Context > FastNewFunctionContext (TNode< ScopeInfo > scope_info, TNode< Uint32T > slots, TNode< Context > context, ScopeType scope_type, ContextMode context_mode)
TNode< JSRegExp > CreateRegExpLiteral (TNode< HeapObject > maybe_feedback_vector, TNode< TaggedIndex > slot, TNode< Object > pattern, TNode< Smi > flags, TNode< Context > context)
TNode< JSArray > CreateShallowArrayLiteral (TNode< FeedbackVector > feedback_vector, TNode< TaggedIndex > slot, TNode< Context > context, AllocationSiteMode allocation_site_mode, Label *call_runtime)
TNode< JSArray > CreateEmptyArrayLiteral (TNode< FeedbackVector > feedback_vector, TNode< TaggedIndex > slot, TNode< Context > context)
TNode< HeapObject > CreateShallowObjectLiteral (TNode< FeedbackVector > feedback_vector, TNode< TaggedIndex > slot, Label *call_runtime)
TNode< HeapObject > CreateShallowObjectLiteral (TNode< AllocationSite > allocation_site, TNode< JSObject > boilerplate, Label *call_runtime, bool bailout_if_dictionary=false)
TNode< JSObject > CreateEmptyObjectLiteral (TNode< Context > context)
TNode< JSObject > FastNewObject (TNode< Context > context, TNode< JSFunction > target, TNode< JSReceiver > new_target)
TNode< JSObject > FastNewObject (TNode< Context > context, TNode< JSFunction > target, TNode< JSReceiver > new_target, Label *call_runtime)
void CopyMutableHeapNumbersInObject (TNode< HeapObject > copy, TNode< IntPtrT > start_offset, TNode< IntPtrT > instance_size)
Additional Inherited Members
Detailed Description
Definition at line 14 of file builtins-constructor-gen.h.
Constructor & Destructor Documentation
ConstructorBuiltinsAssembler()
v8::internal::ConstructorBuiltinsAssembler::ConstructorBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 16 of file builtins-constructor-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
CopyMutableHeapNumbersInObject()
void v8::internal::ConstructorBuiltinsAssembler::CopyMutableHeapNumbersInObject (TNode< HeapObject > copy, TNode< IntPtrT > start_offset, TNode< IntPtrT > instance_size)
Definition at line 792 of file builtins-constructor-gen.cc.
                               {
  // Iterate over all object properties of a freshly copied object and
  // duplicate mutable heap numbers.
  Comment("Copy mutable HeapNumber values");
  BuildFastLoop<IntPtrT>(
      start_offset, end_offset,
      [=, this](TNode<IntPtrT> offset) {
        TNode<Object> field = LoadObjectField(copy, offset);
        Label copy_heap_number(this, Label::kDeferred), continue_loop(this);
        // We only have to clone complex field values.
        GotoIf(TaggedIsSmi(field), &continue_loop);
        // TODO(leszeks): Read the field descriptor to decide if this heap
        // number is mutable or not.
        Branch(IsHeapNumber(CAST(field)), &copy_heap_number, &continue_loop);
        BIND(&copy_heap_number);
        {
          TNode<Float64T> double_value = LoadHeapNumberValue(CAST(field));
          TNode<HeapNumber> heap_number =
              AllocateHeapNumberWithValue(double_value);
          StoreObjectField(copy, offset, heap_number);
          Goto(&continue_loop);
        }
        BIND(&continue_loop);
      },
      kTaggedSize, LoopUnrollingMode::kNo, IndexAdvanceMode::kPost);
}
References v8::internal::CodeStubAssembler::AllocateHeapNumberWithValue(), v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::compiler::CodeAssembler::Comment(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::kNo, v8::internal::CodeStubAssembler::kPost, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::StoreObjectField(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by CreateShallowObjectLiteral(), and v8::internal::CodeStubAssembler::FastCloneJSObject().
CreateEmptyArrayLiteral()
TNode< JSArray > v8::internal::ConstructorBuiltinsAssembler::CreateEmptyArrayLiteral (TNode< FeedbackVector > feedback_vector, TNode< TaggedIndex > slot, TNode< Context > context)
Definition at line 571 of file builtins-constructor-gen.cc.
                            {
  // Array literals always have a valid AllocationSite to properly track
  // elements transitions.
  TNode<Object> maybe_allocation_site =
      CAST(LoadFeedbackVectorSlot(feedback_vector, slot));
  TVARIABLE(AllocationSite, allocation_site);
  Label create_empty_array(this),
      initialize_allocation_site(this, Label::kDeferred), done(this);
  GotoIf(TaggedIsSmi(maybe_allocation_site), &initialize_allocation_site);
  {
    allocation_site = CAST(maybe_allocation_site);
    Goto(&create_empty_array);
  }
  // TODO(cbruni): create the AllocationSite in CSA.
  BIND(&initialize_allocation_site);
  {
    allocation_site = CreateAllocationSiteInFeedbackVector(
        feedback_vector,
        // TODO(v8:10047): pass slot as TaggedIndex here
        Unsigned(TaggedIndexToIntPtr(slot)));
    Goto(&create_empty_array);
  }
  BIND(&create_empty_array);
  TNode<Int32T> kind = LoadElementsKind(allocation_site.value());
  TNode<NativeContext> native_context = LoadNativeContext(context);
  Comment("LoadJSArrayElementsMap");
  TNode<Map> array_map = LoadJSArrayElementsMap(kind, native_context);
  TNode<IntPtrT> zero_intptr = IntPtrConstant(0);
  TNode<Smi> zero = SmiConstant(0);
  Comment("Allocate JSArray");
  std::optional<TNode<AllocationSite>> site =
      V8_ALLOCATION_SITE_TRACKING_BOOL
          ? std::make_optional(allocation_site.value())
          : std::nullopt;
  TNode<JSArray> result = AllocateJSArray(GetInitialFastElementsKind(),
                                          array_map, zero_intptr, zero, site);
  Goto(&done);
  BIND(&done);
  return result;
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), CAST, v8::internal::compiler::CodeAssembler::Comment(), v8::internal::CodeStubAssembler::CreateAllocationSiteInFeedbackVector(), v8::internal::GetInitialFastElementsKind(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::CodeStubAssembler::LoadFeedbackVectorSlot(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::base::internal::result, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::TaggedIndexToIntPtr(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::compiler::CodeAssembler::Unsigned(), V8_ALLOCATION_SITE_TRACKING_BOOL, and v8::internal::zero.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
CreateEmptyObjectLiteral()
TNode< JSObject > v8::internal::ConstructorBuiltinsAssembler::CreateEmptyObjectLiteral (TNode< Context > context)
Definition at line 778 of file builtins-constructor-gen.cc.
                            {
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TNode<Map> map = LoadObjectFunctionInitialMap(native_context);
  // Ensure that slack tracking is disabled for the map.
  static_assert(Map::kNoSlackTracking == 0);
  CSA_DCHECK(this, IsClearWord32<Map::Bits3::ConstructionCounterBits>(
                       LoadMapBitField3(map)));
  TNode<FixedArray> empty_fixed_array = EmptyFixedArrayConstant();
  TNode<JSObject> result =
      AllocateJSObjectFromMap(map, empty_fixed_array, empty_fixed_array);
  return result;
}
References v8::internal::CodeStubAssembler::AllocateJSObjectFromMap(), v8::internal::Map::kNoSlackTracking, v8::internal::CodeStubAssembler::LoadMapBitField3(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectFunctionInitialMap(), v8::internal::native_context, and v8::base::internal::result.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
CreateRegExpLiteral()
TNode< JSRegExp > v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral (TNode< HeapObject > maybe_feedback_vector, TNode< TaggedIndex > slot, TNode< Object > pattern, TNode< Smi > flags, TNode< Context > context)
Definition at line 481 of file builtins-constructor-gen.cc.
                                                                     {
  Label call_runtime(this, Label::kDeferred), end(this);
  GotoIf(IsUndefined(maybe_feedback_vector), &call_runtime);
  TVARIABLE(JSRegExp, result);
  TNode<FeedbackVector> feedback_vector = CAST(maybe_feedback_vector);
  TNode<Object> literal_site =
      CAST(LoadFeedbackVectorSlot(feedback_vector, slot));
  GotoIfNot(HasBoilerplate(literal_site), &call_runtime);
  {
    static_assert(JSRegExp::kDataOffset == JSObject::kHeaderSize);
    static_assert(JSRegExp::kSourceOffset ==
                  JSRegExp::kDataOffset + kTaggedSize);
    static_assert(JSRegExp::kFlagsOffset ==
                  JSRegExp::kSourceOffset + kTaggedSize);
    static_assert(JSRegExp::kHeaderSize ==
                  JSRegExp::kFlagsOffset + kTaggedSize);
    static_assert(JSRegExp::kLastIndexOffset == JSRegExp::kHeaderSize);
    DCHECK_EQ(JSRegExp::Size(), JSRegExp::kLastIndexOffset + kTaggedSize);
    TNode<RegExpBoilerplateDescription> boilerplate = CAST(literal_site);
    TNode<HeapObject> new_object = Allocate(JSRegExp::Size());
    // Initialize Object fields.
    TNode<JSFunction> regexp_function = CAST(LoadContextElementNoCell(
        LoadNativeContext(context), Context::REGEXP_FUNCTION_INDEX));
    TNode<Map> initial_map = CAST(LoadObjectField(
        regexp_function, JSFunction::kPrototypeOrInitialMapOffset));
    StoreMapNoWriteBarrier(new_object, initial_map);
    // Initialize JSReceiver fields.
    StoreObjectFieldRoot(new_object, JSReceiver::kPropertiesOrHashOffset,
                         RootIndex::kEmptyFixedArray);
    // Initialize JSObject fields.
    StoreObjectFieldRoot(new_object, JSObject::kElementsOffset,
                         RootIndex::kEmptyFixedArray);
    // Initialize JSRegExp fields.
    StoreTrustedPointerField(
        new_object, JSRegExp::kDataOffset, kRegExpDataIndirectPointerTag,
        CAST(LoadTrustedPointerFromObject(
            boilerplate, RegExpBoilerplateDescription::kDataOffset,
            kRegExpDataIndirectPointerTag)));
    StoreObjectFieldNoWriteBarrier(
        new_object, JSRegExp::kSourceOffset,
        LoadObjectField(boilerplate,
                        RegExpBoilerplateDescription::kSourceOffset));
    StoreObjectFieldNoWriteBarrier(
        new_object, JSRegExp::kFlagsOffset,
        LoadObjectField(boilerplate,
                        RegExpBoilerplateDescription::kFlagsOffset));
    StoreObjectFieldNoWriteBarrier(
        new_object, JSRegExp::kLastIndexOffset,
        SmiConstant(JSRegExp::kInitialLastIndexValue));
    result = CAST(new_object);
    Goto(&end);
  }
  BIND(&call_runtime);
  {
    result = CAST(CallRuntime(Runtime::kCreateRegExpLiteral, context,
                              maybe_feedback_vector, slot, pattern, flags));
    Goto(&end);
  }
  BIND(&end);
  return result.value();
}
References v8::internal::CodeStubAssembler::Allocate(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, DCHECK_EQ, v8::internal::compiler::end(), v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::HasBoilerplate(), v8::internal::compiler::initial_map, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::JSRegExp::kInitialLastIndexValue, v8::internal::JSRegExp::kLastIndexOffset, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::LoadFeedbackVectorSlot(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::LoadTrustedPointerFromObject(), v8::base::internal::result, v8::internal::JSRegExp::Size(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldRoot(), and v8::internal::CodeStubAssembler::StoreTrustedPointerField().
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
CreateShallowArrayLiteral()
TNode< JSArray > v8::internal::ConstructorBuiltinsAssembler::CreateShallowArrayLiteral (TNode< FeedbackVector > feedback_vector, TNode< TaggedIndex > slot, TNode< Context > context, AllocationSiteMode allocation_site_mode, Label * call_runtime)
Definition at line 552 of file builtins-constructor-gen.cc.
                         {
  TNode<Object> maybe_allocation_site =
      CAST(LoadFeedbackVectorSlot(feedback_vector, slot));
  GotoIfNot(HasBoilerplate(maybe_allocation_site), call_runtime);
  TNode<AllocationSite> allocation_site = CAST(maybe_allocation_site);
  TNode<JSArray> boilerplate = CAST(LoadBoilerplate(allocation_site));
  if (allocation_site_mode == TRACK_ALLOCATION_SITE &&
      V8_ALLOCATION_SITE_TRACKING_BOOL) {
    return CloneFastJSArray(context, boilerplate, allocation_site);
  } else {
    return CloneFastJSArray(context, boilerplate);
  }
}
References CAST, v8::internal::CodeStubAssembler::CloneFastJSArray(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::HasBoilerplate(), v8::internal::CodeStubAssembler::LoadBoilerplate(), v8::internal::CodeStubAssembler::LoadFeedbackVectorSlot(), v8::internal::TRACK_ALLOCATION_SITE, and V8_ALLOCATION_SITE_TRACKING_BOOL.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
CreateShallowObjectLiteral() [1/2]
TNode< HeapObject > v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral (TNode< AllocationSite > allocation_site, TNode< JSObject > boilerplate, Label * call_runtime, bool bailout_if_dictionary = false)
Definition at line 630 of file builtins-constructor-gen.cc.
                                                                {
  TNode<Map> boilerplate_map = LoadMap(boilerplate);
  CSA_DCHECK(this, IsJSObjectMap(boilerplate_map));
  TVARIABLE(HeapObject, var_properties);
  {
    TNode<Uint32T> bit_field_3 = LoadMapBitField3(boilerplate_map);
    GotoIf(IsSetWord32<Map::Bits3::IsDeprecatedBit>(bit_field_3), call_runtime);
    // Directly copy over the property store for dict-mode boilerplates.
    Label if_dictionary(this), if_fast(this), done(this);
    Branch(IsSetWord32<Map::Bits3::IsDictionaryMapBit>(bit_field_3),
           &if_dictionary, &if_fast);
    BIND(&if_dictionary);
    {
      if (bailout_if_dictionary_properties) {
        Goto(call_runtime);
      } else {
        Comment("Copy dictionary properties");
        if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
          var_properties =
              CopySwissNameDictionary(CAST(LoadSlowProperties(boilerplate)));
        } else {
          var_properties = CopyNameDictionary(
              CAST(LoadSlowProperties(boilerplate)), call_runtime);
        }
        // Slow objects have no in-object properties.
        Goto(&done);
      }
    }
    BIND(&if_fast);
    {
      // TODO(cbruni): support copying out-of-object properties.
      // (CreateObjectFromSlowBoilerplate needs to handle them, too.)
      TNode<HeapObject> boilerplate_properties =
          LoadFastProperties(boilerplate);
      GotoIfNot(IsEmptyFixedArray(boilerplate_properties), call_runtime);
      var_properties = EmptyFixedArrayConstant();
      Goto(&done);
    }
    BIND(&done);
  }
  TVARIABLE(FixedArrayBase, var_elements);
  {
    // Copy the elements backing store, assuming that it's flat.
    Label if_empty_fixed_array(this), if_copy_elements(this), done(this);
    TNode<FixedArrayBase> boilerplate_elements = LoadElements(boilerplate);
    Branch(IsEmptyFixedArray(boilerplate_elements), &if_empty_fixed_array,
           &if_copy_elements);
    BIND(&if_empty_fixed_array);
    var_elements = boilerplate_elements;
    Goto(&done);
    BIND(&if_copy_elements);
    CSA_DCHECK(this, Word32BinaryNot(
                         IsFixedCOWArrayMap(LoadMap(boilerplate_elements))));
    auto flags = ExtractFixedArrayFlag::kAllFixedArrays;
    var_elements = CloneFixedArray(boilerplate_elements, flags);
    Goto(&done);
    BIND(&done);
  }
  // Ensure new-space allocation for a fresh JSObject so we can skip write
  // barriers when copying all object fields.
  static_assert(JSObject::kMaxInstanceSize < kMaxRegularHeapObjectSize);
  TNode<IntPtrT> instance_size =
      TimesTaggedSize(LoadMapInstanceSizeInWords(boilerplate_map));
  TNode<IntPtrT> aligned_instance_size =
      AlignToAllocationAlignment(instance_size);
  TNode<IntPtrT> allocation_size = instance_size;
  bool needs_allocation_memento = v8_flags.allocation_site_pretenuring;
  if (needs_allocation_memento) {
    DCHECK(V8_ALLOCATION_SITE_TRACKING_BOOL);
    // Prepare for inner-allocating the AllocationMemento.
    allocation_size = IntPtrAdd(aligned_instance_size,
                                IntPtrConstant(ALIGN_TO_ALLOCATION_ALIGNMENT(
                                    sizeof(AllocationMemento))));
  }
  TNode<HeapObject> copy =
      UncheckedCast<HeapObject>(AllocateInNewSpace(allocation_size));
  {
    Comment("Initialize Literal Copy");
    // Initialize Object fields.
    StoreMapNoWriteBarrier(copy, boilerplate_map);
    StoreObjectFieldNoWriteBarrier(copy, JSObject::kPropertiesOrHashOffset,
                                   var_properties.value());
    StoreObjectFieldNoWriteBarrier(copy, JSObject::kElementsOffset,
                                   var_elements.value());
  }
  // Initialize the AllocationMemento before potential GCs due to heap number
  // allocation when copying the in-object properties.
  if (needs_allocation_memento) {
    InitializeAllocationMemento(copy, aligned_instance_size, allocation_site);
  }
  {
    // Copy over in-object properties.
    Label continue_with_write_barrier(this), done_init(this);
    TVARIABLE(IntPtrT, offset, IntPtrConstant(JSObject::kHeaderSize));
    {
      Comment("Copy in-object properties fast");
      Label continue_fast(this, &offset);
      Branch(IntPtrEqual(offset.value(), instance_size), &done_init,
             &continue_fast);
      BIND(&continue_fast);
      TNode<Object> field = LoadObjectField(boilerplate, offset.value());
      Label store_field(this);
      GotoIf(TaggedIsSmi(field), &store_field);
      // TODO(leszeks): Read the field descriptor to decide if this heap
      // number is mutable or not.
      GotoIf(IsHeapNumber(CAST(field)), &continue_with_write_barrier);
      Goto(&store_field);
      BIND(&store_field);
      StoreObjectFieldNoWriteBarrier(copy, offset.value(), field);
      offset = IntPtrAdd(offset.value(), IntPtrConstant(kTaggedSize));
      Branch(WordNotEqual(offset.value(), instance_size), &continue_fast,
             &done_init);
    }
    // Continue initializing the literal after seeing the first sub-object
    // potentially causing allocation. In this case we prepare the new literal
    // by copying all pending fields over from the boilerplate and emit full
    // write barriers from here on.
    BIND(&continue_with_write_barrier);
    {
      Comment("Copy in-object properties slow");
      BuildFastLoop<IntPtrT>(
          offset.value(), instance_size,
          [=, this](TNode<IntPtrT> offset) {
            // TODO(ishell): value decompression is not necessary here.
            TNode<Object> field = LoadObjectField(boilerplate, offset);
            StoreObjectFieldNoWriteBarrier(copy, offset, field);
          },
          kTaggedSize, LoopUnrollingMode::kYes, IndexAdvanceMode::kPost);
      CopyMutableHeapNumbersInObject(copy, offset.value(), instance_size);
      Goto(&done_init);
    }
    BIND(&done_init);
  }
  return copy;
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::CodeStubAssembler::AlignToAllocationAlignment(), v8::internal::CodeStubAssembler::AllocateInNewSpace(), v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::CodeStubAssembler::CloneFixedArray(), v8::internal::compiler::CodeAssembler::Comment(), CopyMutableHeapNumbersInObject(), v8::internal::CodeStubAssembler::CopyNameDictionary(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::DCHECK(), v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::InitializeAllocationMemento(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::CodeStubAssembler::IsJSObjectMap(), v8::internal::CodeStubAssembler::kAllFixedArrays, v8::internal::JSObject::kMaxInstanceSize, v8::internal::kMaxRegularHeapObjectSize, v8::internal::CodeStubAssembler::kPost, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::kYes, v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadFastProperties(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapBitField3(), v8::internal::CodeStubAssembler::LoadMapInstanceSizeInWords(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::LoadSlowProperties(), v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::CodeStubAssembler::TimesTaggedSize(), V8_ALLOCATION_SITE_TRACKING_BOOL, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::internal::v8_flags, and v8::internal::compiler::CodeAssembler::WordNotEqual().
CreateShallowObjectLiteral() [2/2]
TNode< HeapObject > v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral (TNode< FeedbackVector > feedback_vector, TNode< TaggedIndex > slot, Label * call_runtime)
Definition at line 618 of file builtins-constructor-gen.cc.
                         {
  TNode<Object> maybe_allocation_site =
      CAST(LoadFeedbackVectorSlot(feedback_vector, slot));
  GotoIfNot(HasBoilerplate(maybe_allocation_site), call_runtime);
  TNode<AllocationSite> allocation_site = CAST(maybe_allocation_site);
  TNode<JSObject> boilerplate = LoadBoilerplate(allocation_site);
  return CreateShallowObjectLiteral(allocation_site, boilerplate, call_runtime);
}
References CAST, v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::HasBoilerplate(), v8::internal::CodeStubAssembler::LoadBoilerplate(), and v8::internal::CodeStubAssembler::LoadFeedbackVectorSlot().
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), and v8::internal::TF_BUILTIN().
FastNewFunctionContext()
TNode< Context > v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext (TNode< ScopeInfo > scope_info, TNode< Uint32T > slots, TNode< Context > context, ScopeType scope_type, ContextMode context_mode)
Definition at line 391 of file builtins-constructor-gen.cc.
                                                    {
  TNode<IntPtrT> slots_intptr = Signed(ChangeUint32ToWord(slots));
  TNode<IntPtrT> size = ElementOffsetFromIndex(slots_intptr, PACKED_ELEMENTS,
                                               Context::kTodoHeaderSize);
  // Create a new closure from the given function info in new space
  TNode<Context> function_context =
      UncheckedCast<Context>(AllocateInNewSpace(size));
  TNode<NativeContext> native_context = LoadNativeContext(context);
  Context::Field index;
  switch (scope_type) {
    case EVAL_SCOPE:
      index = Context::EVAL_CONTEXT_MAP_INDEX;
      break;
    case FUNCTION_SCOPE:
      index = Context::FUNCTION_CONTEXT_MAP_INDEX;
      break;
    default:
      UNREACHABLE();
  }
  TNode<Map> map = CAST(LoadContextElementNoCell(native_context, index));
  // Set up the header.
  StoreMapNoWriteBarrier(function_context, map);
  TNode<IntPtrT> min_context_slots = IntPtrConstant(Context::MIN_CONTEXT_SLOTS);
  // TODO(ishell): for now, length also includes MIN_CONTEXT_SLOTS.
  TNode<IntPtrT> length = IntPtrAdd(slots_intptr, min_context_slots);
  StoreObjectFieldNoWriteBarrier(function_context, Context::kLengthOffset,
                                 SmiTag(length));
  StoreObjectFieldNoWriteBarrier(function_context, Context::kScopeInfoOffset,
                                 scope_info);
  StoreObjectFieldNoWriteBarrier(function_context, Context::kPreviousOffset,
                                 context);
  // Initialize the varrest of the slots to undefined.
  TNode<Object> undefined = UndefinedConstant();
  if (context_mode == ContextMode::kHasContextCells) {
    TVARIABLE(IntPtrT, offset, IntPtrConstant(Context::kTodoHeaderSize));
    TNode<IntPtrT> local_count = LoadScopeInfoContextLocalCount(scope_info);
    Label extension_field_done(this);
    GotoIfNot(LoadScopeInfoHasExtensionField(scope_info),
              &extension_field_done);
    StoreObjectFieldNoWriteBarrier(function_context, Context::kExtensionOffset,
                                   undefined);
    offset = IntPtrAdd(offset.value(), IntPtrConstant(kTaggedSize));
    Goto(&extension_field_done);
    BIND(&extension_field_done);
    CodeStubAssembler::VariableList vars({&offset}, zone());
    BuildFastLoop<IntPtrT>(
        vars, IntPtrConstant(0), local_count,
        [&](TNode<IntPtrT> index) {
          TNode<Object> init_value =
              GetFunctionContextSlotInitialValue(scope_info, index);
          StoreObjectFieldNoWriteBarrier(function_context, offset.value(),
                                         init_value);
          offset = IntPtrAdd(offset.value(), IntPtrConstant(kTaggedSize));
        },
        1, LoopUnrollingMode::kYes, IndexAdvanceMode::kPost);
    Label done(this);
    GotoIf(IntPtrEqual(offset.value(), size), &done);
    // We store another undefined for function variables that are stored in the
    // last slot of the context.
    StoreObjectFieldNoWriteBarrier(function_context, offset.value(), undefined);
    // Check that this is indeed the last slot.
    CSA_DCHECK(this, IntPtrEqual(
                         IntPtrAdd(offset.value(), IntPtrConstant(kTaggedSize)),
                         size));
    Goto(&done);
    BIND(&done);
    return function_context;
  } else {
    DCHECK_EQ(context_mode, ContextMode::kNoContextCells);
    TNode<IntPtrT> start_offset = IntPtrConstant(Context::kTodoHeaderSize);
    CodeStubAssembler::VariableList vars(0, zone());
    BuildFastLoop<IntPtrT>(
        vars, start_offset, size,
        [=, this](TNode<IntPtrT> offset) {
          StoreObjectFieldNoWriteBarrier(function_context, offset, undefined);
        },
        kTaggedSize, LoopUnrollingMode::kYes, IndexAdvanceMode::kPost);
    return function_context;
  }
}
References v8::internal::CodeStubAssembler::AllocateInNewSpace(), CAST, v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), DCHECK_EQ, v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::EVAL_SCOPE, v8::internal::FUNCTION_SCOPE, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::Context::kExtensionOffset, v8::internal::kHasContextCells, v8::internal::kNoContextCells, v8::internal::CodeStubAssembler::kPost, v8::internal::Context::kPreviousOffset, v8::internal::Context::kScopeInfoOffset, v8::internal::kTaggedSize, v8::internal::Context::kTodoHeaderSize, v8::internal::CodeStubAssembler::kYes, v8::internal::length, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadScopeInfoContextLocalCount(), v8::internal::CodeStubAssembler::LoadScopeInfoHasExtensionField(), v8::internal::Context::MIN_CONTEXT_SLOTS, v8::internal::native_context, v8::internal::PACKED_ELEMENTS, v8::internal::compiler::CodeAssembler::Signed(), size(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::undefined, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::UNREACHABLE(), and v8::internal::compiler::CodeAssembler::zone().
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
FastNewObject() [1/2]
TNode< JSObject > v8::internal::ConstructorBuiltinsAssembler::FastNewObject (TNode< Context > context, TNode< JSFunction > target, TNode< JSReceiver > new_target)
Definition at line 331 of file builtins-constructor-gen.cc.
                                  {
  TVARIABLE(JSObject, var_obj);
  Label call_runtime(this), end(this);
  var_obj = FastNewObject(context, target, new_target, &call_runtime);
  Goto(&end);
  BIND(&call_runtime);
  var_obj = CAST(CallRuntime(Runtime::kNewObject, context, target, new_target));
  Goto(&end);
  BIND(&end);
  return var_obj.value();
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::end(), and v8::internal::compiler::CodeAssembler::Goto().
Referenced by v8::internal::BaseCollectionsAssembler::AllocateJSCollectionSlow(), and v8::internal::TF_BUILTIN().
FastNewObject() [2/2]
TNode< JSObject > v8::internal::ConstructorBuiltinsAssembler::FastNewObject (TNode< Context > context, TNode< JSFunction > target, TNode< JSReceiver > new_target, Label * call_runtime)
Definition at line 348 of file builtins-constructor-gen.cc.
                                                       {
  // Verify that the new target is a JSFunction.
  Label end(this);
  TNode<JSFunction> new_target_func =
      HeapObjectToJSFunctionWithPrototypeSlot(new_target, call_runtime);
  // Fast path.
  // Load the initial map and verify that it's in fact a map.
  TNode<Object> initial_map_or_proto =
      LoadJSFunctionPrototypeOrInitialMap(new_target_func);
  GotoIf(TaggedIsSmi(initial_map_or_proto), call_runtime);
  GotoIf(DoesntHaveInstanceType(CAST(initial_map_or_proto), MAP_TYPE),
         call_runtime);
  TNode<Map> initial_map = CAST(initial_map_or_proto);
  // Fall back to runtime if the target differs from the new target's
  // initial map constructor.
  TNode<Object> new_target_constructor = LoadObjectField(
      initial_map, Map::kConstructorOrBackPointerOrNativeContextOffset);
  GotoIf(TaggedNotEqual(target, new_target_constructor), call_runtime);
  TVARIABLE(HeapObject, properties);
  Label instantiate_map(this), allocate_properties(this);
  GotoIf(IsDictionaryMap(initial_map), &allocate_properties);
  {
    properties = EmptyFixedArrayConstant();
    Goto(&instantiate_map);
  }
  BIND(&allocate_properties);
  {
    properties =
        AllocatePropertyDictionary(PropertyDictionary::kInitialCapacity);
    Goto(&instantiate_map);
  }
  BIND(&instantiate_map);
  return AllocateJSObjectFromMap(initial_map, properties.value(), std::nullopt,
                                 AllocationFlag::kNone, kWithSlackTracking);
}
References v8::internal::CodeStubAssembler::AllocateJSObjectFromMap(), v8::internal::CodeStubAssembler::AllocatePropertyDictionary(), CAST, v8::internal::CodeStubAssembler::DoesntHaveInstanceType(), v8::internal::compiler::end(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::HeapObjectToJSFunctionWithPrototypeSlot(), v8::internal::compiler::initial_map, v8::internal::CodeStubAssembler::IsDictionaryMap(), v8::internal::kConstructorOrBackPointerOrNativeContextOffset, v8::internal::NameDictionary::kInitialCapacity, v8::internal::CodeStubAssembler::kNone, v8::internal::CodeStubAssembler::kWithSlackTracking, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::TaggedIsSmi(), and v8::internal::CodeStubAssembler::TaggedNotEqual().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-constructor-gen.h
/mnt/V8SourceCode/src/builtins/builtins-constructor-gen.cc