v8::internal::JitLogger Class Reference
Public Member Functions
JitLogger (Isolate *isolate, JitCodeEventHandler code_event_handler)
void CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) override
void BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) override
void CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) override
void AddCodeLinePosInfoEvent (void *jit_handler_data, int pc_offset, int position, JitCodeEvent::PositionType position_type, JitCodeEvent::CodeType code_type)
void * StartCodePosInfoEvent (JitCodeEvent::CodeType code_type)
void EndCodePosInfoEvent (Address start_address, void *jit_handler_data, JitCodeEvent::CodeType code_type)
Private Member Functions
void LogRecordedBuffer (Tagged< AbstractCode > code, MaybeDirectHandle< SharedFunctionInfo > maybe_shared, const char *name, size_t length) override
Private Attributes
JitCodeEventHandler code_event_handler_
base::Mutex logger_mutex_
Additional Inherited Members
Detailed Description
Definition at line 833 of file log.cc.
Constructor & Destructor Documentation
JitLogger()
v8::internal::JitLogger::JitLogger (Isolate * isolate, JitCodeEventHandler code_event_handler)
Definition at line 865 of file log.cc.
    : CodeEventLogger(isolate), code_event_handler_(code_event_handler) {
  DCHECK_NOT_NULL(code_event_handler);
}
References DCHECK_NOT_NULL.
Member Function Documentation
AddCodeLinePosInfoEvent()
void v8::internal::JitLogger::AddCodeLinePosInfoEvent (void * jit_handler_data, int pc_offset, int position, JitCodeEvent::PositionType position_type, JitCodeEvent::CodeType code_type)
Definition at line 985 of file log.cc.
                                    {
  JitCodeEvent event;
  event.type = JitCodeEvent::CODE_ADD_LINE_POS_INFO;
  event.code_type = code_type;
  event.user_data = jit_handler_data;
  event.line_info.offset = pc_offset;
  event.line_info.pos = position;
  event.line_info.position_type = position_type;
  event.isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  code_event_handler_(&event);
}
References v8::JitCodeEvent::CODE_ADD_LINE_POS_INFO, code_event_handler_, v8::internal::CodeEventLogger::isolate_, and v8::JitCodeEvent::type.
Referenced by v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent().
BytecodeMoveEvent()
void v8::internal::JitLogger::BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 970 of file log.cc.
                                                            {
  base::MutexGuard guard(&logger_mutex_);
  JitCodeEvent event;
  event.type = JitCodeEvent::CODE_MOVED;
  event.code_type = JitCodeEvent::BYTE_CODE;
  event.code_start = reinterpret_cast<void*>(from->GetFirstBytecodeAddress());
  event.code_len = from->length();
  event.new_code_start = reinterpret_cast<void*>(to->GetFirstBytecodeAddress());
  event.isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  code_event_handler_(&event);
}
References v8::JitCodeEvent::BYTE_CODE, code_event_handler_, v8::JitCodeEvent::CODE_MOVED, v8::internal::CodeEventLogger::isolate_, logger_mutex_, and v8::JitCodeEvent::type.
CodeDisableOptEvent()
void v8::internal::JitLogger::CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 841 of file log.cc.
                                                                             {}
CodeMoveEvent()
void v8::internal::JitLogger::CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 949 of file log.cc.
                                                            {
  base::MutexGuard guard(&logger_mutex_);
  Tagged<Code> code;
  if (!from->TryGetCodeUnchecked(&code, kAcquireLoad)) {
    // Not yet fully initialized and no CodeCreateEvent has been emitted yet.
    return;
  }
  JitCodeEvent event;
  event.type = JitCodeEvent::CODE_MOVED;
  event.code_type = JitCodeEvent::JIT_CODE;
  event.code_start = reinterpret_cast<void*>(from->instruction_start());
  event.code_len = code->instruction_size();
  event.new_code_start = reinterpret_cast<void*>(to->instruction_start());
  event.isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  code_event_handler_(&event);
}
References code, code_event_handler_, v8::JitCodeEvent::CODE_MOVED, v8::internal::CodeEventLogger::isolate_, v8::JitCodeEvent::JIT_CODE, v8::kAcquireLoad, logger_mutex_, and v8::JitCodeEvent::type.
EndCodePosInfoEvent()
void v8::internal::JitLogger::EndCodePosInfoEvent (Address start_address, void * jit_handler_data, JitCodeEvent::CodeType code_type)
Definition at line 1011 of file log.cc.
                                                                    {
  JitCodeEvent event;
  event.type = JitCodeEvent::CODE_END_LINE_INFO_RECORDING;
  event.code_type = code_type;
  event.code_start = reinterpret_cast<void*>(start_address);
  event.user_data = jit_handler_data;
  event.isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  code_event_handler_(&event);
}
References v8::JitCodeEvent::CODE_END_LINE_INFO_RECORDING, code_event_handler_, v8::internal::CodeEventLogger::isolate_, and v8::JitCodeEvent::type.
Referenced by v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent().
LogRecordedBuffer()
void v8::internal::JitLogger::LogRecordedBuffer (Tagged< AbstractCode > code, MaybeDirectHandle< SharedFunctionInfo > maybe_shared, const char * name, size_t length) [override], [private], [virtual]
Implements v8::internal::CodeEventLogger.
Definition at line 870 of file log.cc.
                   {
  DisallowGarbageCollection no_gc;
  PtrComprCageBase cage_base(isolate_);
  JitCodeEvent event;
  event.type = JitCodeEvent::CODE_ADDED;
  event.code_start = reinterpret_cast<void*>(code->InstructionStart(cage_base));
  event.code_type = IsCode(code, cage_base) ? JitCodeEvent::JIT_CODE
                                            : JitCodeEvent::BYTE_CODE;
  event.code_len = code->InstructionSize(cage_base);
  DirectHandle<SharedFunctionInfo> shared;
  if (maybe_shared.ToHandle(&shared) &&
      IsScript(shared->script(cage_base), cage_base)) {
    event.script = ToApiHandle<v8::UnboundScript>(shared);
  } else {
    event.script = Local<v8::UnboundScript>();
  }
  event.name.str = name;
  event.name.len = length;
  event.isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  code_event_handler_(&event);
}
References v8::JitCodeEvent::BYTE_CODE, code, v8::JitCodeEvent::CODE_ADDED, code_event_handler_, v8::internal::CodeEventLogger::isolate_, v8::JitCodeEvent::JIT_CODE, v8::internal::length, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::JitCodeEvent::type.
StartCodePosInfoEvent()
void * v8::internal::JitLogger::StartCodePosInfoEvent (JitCodeEvent::CodeType code_type)
Definition at line 1001 of file log.cc.
                                                                     {
  JitCodeEvent event;
  event.type = JitCodeEvent::CODE_START_LINE_INFO_RECORDING;
  event.code_type = code_type;
  event.isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  code_event_handler_(&event);
  return event.user_data;
}
References code_event_handler_, v8::JitCodeEvent::CODE_START_LINE_INFO_RECORDING, v8::internal::CodeEventLogger::isolate_, and v8::JitCodeEvent::type.
Referenced by v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent().
Member Data Documentation
code_event_handler_
JitCodeEventHandler v8::internal::JitLogger::code_event_handler_ [private]
Definition at line 861 of file log.cc.
Referenced by AddCodeLinePosInfoEvent(), BytecodeMoveEvent(), CodeMoveEvent(), EndCodePosInfoEvent(), LogRecordedBuffer(), and StartCodePosInfoEvent().
logger_mutex_
base::Mutex v8::internal::JitLogger::logger_mutex_ [private]
Definition at line 862 of file log.cc.
Referenced by BytecodeMoveEvent(), and CodeMoveEvent().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/log.cc