v8::internal::Name Class Reference
#include <name.h>
Public Types
enum class HashFieldType : uint32_t { kHash = 0b10
, kIntegerIndex = 0b00
, kForwardingIndex = 0b01
, kEmpty = 0b11
 }
using HashFieldTypeBits = base::BitField< HashFieldType, 0, 2 >
using HashBits = HashFieldTypeBits::Next< uint32_t, kBitsPerInt - HashFieldTypeBits::kSize >
using IsInternalizedForwardingIndexBit = HashFieldTypeBits::Next< bool, 1 >
using IsExternalForwardingIndexBit = IsInternalizedForwardingIndexBit::Next< bool, 1 >
using ForwardingIndexValueBits = IsExternalForwardingIndexBit::Next< unsigned int, kBitsPerInt - HashFieldTypeBits::kSize - IsInternalizedForwardingIndexBit::kSize - IsExternalForwardingIndexBit::kSize >
using ArrayIndexValueBits = HashFieldTypeBits::Next< unsigned int, kArrayIndexValueBits >
using ArrayIndexLengthBits = ArrayIndexValueBits::Next< unsigned int, kArrayIndexLengthBits >
Public Member Functions
bool HasHashCode () const
bool HasForwardingIndex (AcquireLoadTag) const
bool HasInternalizedForwardingIndex (AcquireLoadTag) const
bool HasExternalForwardingIndex (AcquireLoadTag) const
uint32_t raw_hash_field () const
uint32_t raw_hash_field (AcquireLoadTag) const
void set_raw_hash_field (uint32_t hash)
void set_raw_hash_field (uint32_t hash, ReleaseStoreTag)
void set_raw_hash_field_if_empty (uint32_t hash)
uint32_t hash () const
bool TryGetHash (uint32_t *hash) const
bool Equals (Tagged< Name > other)
bool IsArrayIndex ()
bool AsArrayIndex (uint32_t *index)
bool AsIntegerIndex (size_t *index)
bool IsInteresting (Isolate *isolate)
bool IsPrivate ()
bool IsPrivateName ()
bool IsPrivateBrand ()
void NameShortPrint ()
int NameShortPrint (base::Vector< char > str)
uint32_t EnsureHash ()
uint32_t EnsureHash (const SharedStringAccessGuardIfNeeded &)
uint32_t EnsureRawHash ()
uint32_t EnsureRawHash (const SharedStringAccessGuardIfNeeded &)
uint32_t RawHash ()
Static Public Member Functions
static bool Equals (Isolate *isolate, DirectHandle< Name > one, DirectHandle< Name > two)
static bool ContainsCachedArrayIndex (uint32_t hash)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToFunctionName (Isolate *isolate, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToFunctionName (Isolate *isolate, DirectHandle< Name > name, DirectHandle< String > prefix)
static bool IsHashFieldComputed (uint32_t raw_hash_field)
static bool IsHash (uint32_t raw_hash_field)
static bool IsIntegerIndex (uint32_t raw_hash_field)
static bool IsForwardingIndex (uint32_t raw_hash_field)
static bool IsInternalizedForwardingIndex (uint32_t raw_hash_field)
static bool IsExternalForwardingIndex (uint32_t raw_hash_field)
static uint32_t CreateHashFieldValue (uint32_t hash, HashFieldType type)
static uint32_t CreateInternalizedForwardingIndex (uint32_t index)
static uint32_t CreateExternalForwardingIndex (uint32_t index)
Static Public Attributes
static constexpr int kHashNotComputedMask = 1
static constexpr int kEmptyHashField
static const int kMaxCachedArrayIndexLength = 7
static const uint32_t kMaxArrayIndex = kMaxUInt32 - 1
static const int kMaxArrayIndexSize = 10
static const int kMaxIntegerIndexSize
static const int kArrayIndexValueBits = 24
static const int kArrayIndexLengthBits
static const unsigned int kDoesNotContainCachedArrayIndexMask
static const unsigned int kDoesNotContainIntegerOrForwardingIndexMask = 0b10
Private Member Functions
uint32_t GetRawHashFromForwardingTable (uint32_t raw_hash) const
Private Attributes
std::atomic_uint32_t raw_hash_field_
Friends
class V8HeapExplorer
class CodeStubAssembler
class StringBuiltinsAssembler
class SandboxTesting
class maglev::MaglevGraphBuilder
class maglev::MaglevAssembler
class compiler::AccessBuilder
class compiler::WasmGraphBuilder
class TorqueGeneratedNameAsserts
Detailed Description
Definition at line 35 of file name.h.
Member Typedef Documentation
ArrayIndexLengthBits
using v8::internal::Name::ArrayIndexLengthBits = ArrayIndexValueBits::Next<unsigned int, kArrayIndexLengthBits>
Definition at line 178 of file name.h.
ArrayIndexValueBits
using v8::internal::Name::ArrayIndexValueBits = HashFieldTypeBits::Next<unsigned int, kArrayIndexValueBits>
Definition at line 176 of file name.h.
ForwardingIndexValueBits
using v8::internal::Name::ForwardingIndexValueBits = IsExternalForwardingIndexBit::Next< unsigned int, kBitsPerInt - HashFieldTypeBits::kSize - IsInternalizedForwardingIndexBit::kSize - IsExternalForwardingIndexBit::kSize>
Definition at line 144 of file name.h.
HashBits
using v8::internal::Name::HashBits = HashFieldTypeBits::Next<uint32_t, kBitsPerInt - HashFieldTypeBits::kSize>
Definition at line 128 of file name.h.
HashFieldTypeBits
using v8::internal::Name::HashFieldTypeBits = base::BitField<HashFieldType, 0, 2>
Definition at line 127 of file name.h.
IsExternalForwardingIndexBit
using v8::internal::Name::IsExternalForwardingIndexBit = IsInternalizedForwardingIndexBit::Next<bool, 1>
Definition at line 142 of file name.h.
IsInternalizedForwardingIndexBit
using v8::internal::Name::IsInternalizedForwardingIndexBit = HashFieldTypeBits::Next<bool, 1>
Definition at line 141 of file name.h.
Member Enumeration Documentation
HashFieldType
enum v8::internal::Name::HashFieldType : uint32_t [strong]
Enumerator
kHash
kIntegerIndex
kForwardingIndex
kEmpty
Definition at line 120 of file name.h.
                           : uint32_t {
    kHash = 0b10,
    kIntegerIndex = 0b00,
    kForwardingIndex = 0b01,
    kEmpty = 0b11
  };
Member Function Documentation
AsArrayIndex()
bool v8::internal::Name::AsArrayIndex (uint32_t * index) [inline]
Definition at line 281 of file name-inl.h.
                                       {
  return IsString(this) && Cast<String>(this)->AsArrayIndex(index);
}
References v8::internal::index.
Referenced by IsArrayIndex().
AsIntegerIndex()
bool v8::internal::Name::AsIntegerIndex (size_t * index) [inline]
Definition at line 285 of file name-inl.h.
                                       {
  return IsString(this) && Cast<String>(this)->AsIntegerIndex(index);
}
References v8::internal::index.
ContainsCachedArrayIndex()
bool v8::internal::Name::ContainsCachedArrayIndex (uint32_t hash) [inline], [static]
Definition at line 290 of file name-inl.h.
                                                           {
  return (raw_hash_field & Name::kDoesNotContainCachedArrayIndexMask) == 0;
}
References kDoesNotContainCachedArrayIndexMask, and raw_hash_field().
Referenced by v8::internal::String::AsArrayIndex(), v8::internal::String::AsIntegerIndex(), v8::internal::StringHasher::HashSequentialString(), v8::internal::StringHasher::MakeArrayIndexHash(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
CreateExternalForwardingIndex()
uint32_t v8::internal::Name::CreateExternalForwardingIndex (uint32_t index) [inline], [static]
Definition at line 146 of file name-inl.h.
                                                           {
  return ForwardingIndexValueBits::encode(index) |
         IsExternalForwardingIndexBit::encode(true) |
         IsInternalizedForwardingIndexBit::encode(false) |
         HashFieldTypeBits::encode(HashFieldType::kForwardingIndex);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, and kForwardingIndex.
CreateHashFieldValue()
uint32_t v8::internal::Name::CreateHashFieldValue (uint32_t hash, HashFieldType type) [inline], [static]
Definition at line 132 of file name-inl.h.
                                                                     {
  DCHECK_NE(type, HashFieldType::kForwardingIndex);
  return HashBits::encode(hash & HashBits::kMax) |
         HashFieldTypeBits::encode(type);
}
References DCHECK_NE, v8::base::BitField< T, shift, size, U >::encode(), hash(), kForwardingIndex, v8::base::BitField< T, shift, size, U >::kMax, and v8::internal::tracing::type.
Referenced by v8::internal::StringHasher::GetTrivialHash(), v8::internal::StringHasher::HashSequentialString(), and v8::internal::Factory::NewSymbolInternal().
CreateInternalizedForwardingIndex()
uint32_t v8::internal::Name::CreateInternalizedForwardingIndex (uint32_t index) [inline], [static]
Definition at line 138 of file name-inl.h.
                                                               {
  return ForwardingIndexValueBits::encode(index) |
         IsExternalForwardingIndexBit::encode(false) |
         IsInternalizedForwardingIndexBit::encode(true) |
         HashFieldTypeBits::encode(HashFieldType::kForwardingIndex);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, and kForwardingIndex.
Referenced by v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference().
EnsureHash() [1/2]
uint32_t v8::internal::Name::EnsureHash () [inline]
Definition at line 208 of file name-inl.h.
{ return HashBits::decode(EnsureRawHash()); }
References v8::base::BitField< T, shift, size, U >::decode(), and EnsureRawHash().
EnsureHash() [2/2]
uint32_t v8::internal::Name::EnsureHash (const SharedStringAccessGuardIfNeeded & access_guard) [inline]
Definition at line 210 of file name-inl.h.
                                                                             {
  return HashBits::decode(EnsureRawHash(access_guard));
}
References v8::base::BitField< T, shift, size, U >::decode(), and EnsureRawHash().
EnsureRawHash() [1/2]
uint32_t v8::internal::Name::EnsureRawHash () [inline]
Definition at line 175 of file name-inl.h.
                             {
  // Fast case: has hash code already been computed?
  uint32_t field = raw_hash_field(kAcquireLoad);
  if (IsHashFieldComputed(field)) return field;
  // The computed hash might be stored in the forwarding table.
  if (V8_UNLIKELY(IsForwardingIndex(field))) {
    return GetRawHashFromForwardingTable(field);
  }
  // Slow case: compute hash code and set it. Has to be a string.
  return Cast<String>(this)->ComputeAndSetRawHash();
}
References GetRawHashFromForwardingTable(), IsForwardingIndex(), IsHashFieldComputed(), v8::kAcquireLoad, raw_hash_field(), and V8_UNLIKELY.
Referenced by EnsureHash().
EnsureRawHash() [2/2]
uint32_t v8::internal::Name::EnsureRawHash (const SharedStringAccessGuardIfNeeded & access_guard) [inline]
Definition at line 187 of file name-inl.h.
                                                         {
  // Fast case: has hash code already been computed?
  uint32_t field = raw_hash_field(kAcquireLoad);
  if (IsHashFieldComputed(field)) return field;
  // The computed hash might be stored in the forwarding table.
  if (V8_UNLIKELY(IsForwardingIndex(field))) {
    return GetRawHashFromForwardingTable(field);
  }
  // Slow case: compute hash code and set it. Has to be a string.
  return Cast<String>(this)->ComputeAndSetRawHash(access_guard);
}
References GetRawHashFromForwardingTable(), IsForwardingIndex(), IsHashFieldComputed(), v8::kAcquireLoad, raw_hash_field(), and V8_UNLIKELY.
Equals() [1/2]
bool v8::internal::Name::Equals (Isolate * isolate, DirectHandle< Name > one, DirectHandle< Name > two) [inline], [static]
Definition at line 85 of file name-inl.h.
                                          {
  if (one.is_identical_to(two)) return true;
  if ((IsInternalizedString(*one) && IsInternalizedString(*two)) ||
      IsSymbol(*one) || IsSymbol(*two)) {
    return false;
  }
  return String::SlowEquals(isolate, Cast<String>(one), Cast<String>(two));
}
References v8::internal::InstanceTypeChecker::IsInternalizedString(), one, and v8::internal::String::SlowEquals().
Equals() [2/2]
bool v8::internal::Name::Equals (Tagged< Name > other) [inline]
Definition at line 76 of file name-inl.h.
                                    {
  if (other == this) return true;
  if ((IsInternalizedString(this) && IsInternalizedString(other)) ||
      IsSymbol(this) || IsSymbol(other)) {
    return false;
  }
  return Cast<String>(this)->SlowEquals(Cast<String>(other));
}
References v8::internal::InstanceTypeChecker::IsInternalizedString().
Referenced by v8::internal::CheckForName(), v8::internal::Factory::GlobalConstantFor(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), and v8::internal::anonymous_namespace{keys.cc}::NameComparator::operator()().
GetRawHashFromForwardingTable()
uint32_t v8::internal::Name::GetRawHashFromForwardingTable (uint32_t raw_hash) const [inline], [private]
Definition at line 167 of file name-inl.h.
                                                                    {
  DCHECK(IsForwardingIndex(raw_hash));
  // TODO(pthier): Add parameter for isolate so we don't need to calculate it.
  Isolate* isolate = Isolate::Current();
  const int index = ForwardingIndexValueBits::decode(raw_hash);
  return isolate->string_forwarding_table()->GetRawHash(isolate, index);
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::StringForwardingTable::GetRawHash(), v8::internal::index, IsForwardingIndex(), and v8::internal::Isolate::string_forwarding_table().
Referenced by EnsureRawHash(), hash(), RawHash(), and TryGetHash().
HasExternalForwardingIndex()
bool v8::internal::Name::HasExternalForwardingIndex (AcquireLoadTag) const [inline]
Definition at line 163 of file name-inl.h.
                                                          {
  return IsExternalForwardingIndex(raw_hash_field(kAcquireLoad));
}
References IsExternalForwardingIndex(), v8::kAcquireLoad, and raw_hash_field().
HasForwardingIndex()
bool v8::internal::Name::HasForwardingIndex (AcquireLoadTag) const [inline]
Definition at line 157 of file name-inl.h.
                                                  {
  return IsForwardingIndex(raw_hash_field(kAcquireLoad));
}
References IsForwardingIndex(), v8::kAcquireLoad, and raw_hash_field().
hash()
uint32_t v8::internal::Name::hash () const [inline]
Definition at line 228 of file name-inl.h.
                          {
  uint32_t field = raw_hash_field(kAcquireLoad);
  if (V8_UNLIKELY(!IsHashFieldComputed(field))) {
    DCHECK(IsForwardingIndex(field));
    return HashBits::decode(GetRawHashFromForwardingTable(field));
  }
  return HashBits::decode(field);
}
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), GetRawHashFromForwardingTable(), IsForwardingIndex(), IsHashFieldComputed(), v8::kAcquireLoad, raw_hash_field(), and V8_UNLIKELY.
Referenced by CreateHashFieldValue(), set_raw_hash_field(), set_raw_hash_field_if_empty(), and TryGetHash().
HasHashCode()
bool v8::internal::Name::HasHashCode () const [inline]
Definition at line 153 of file name-inl.h.
                             {
  uint32_t field = raw_hash_field();
  return IsHashFieldComputed(field) || IsForwardingIndex(field);
}
References IsForwardingIndex(), IsHashFieldComputed(), and raw_hash_field().
HasInternalizedForwardingIndex()
bool v8::internal::Name::HasInternalizedForwardingIndex (AcquireLoadTag) const [inline]
Definition at line 160 of file name-inl.h.
                                                              {
  return IsInternalizedForwardingIndex(raw_hash_field(kAcquireLoad));
}
References IsInternalizedForwardingIndex(), v8::kAcquireLoad, and raw_hash_field().
IsArrayIndex()
bool v8::internal::Name::IsArrayIndex () [inline]
Definition at line 276 of file name-inl.h.
                        {
  uint32_t index;
  return AsArrayIndex(&index);
}
References AsArrayIndex(), and v8::internal::index.
IsExternalForwardingIndex()
bool v8::internal::Name::IsExternalForwardingIndex (uint32_t raw_hash_field) [inline], [static]
Definition at line 125 of file name-inl.h.
                                                            {
  return HashFieldTypeBits::decode(raw_hash_field) ==
             HashFieldType::kForwardingIndex &&
         IsExternalForwardingIndexBit::decode(raw_hash_field);
}
References v8::base::BitField< T, shift, size, U >::decode(), kForwardingIndex, and raw_hash_field().
Referenced by v8::String::GetExternalOneByteStringResource(), v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::String::GetExternalStringResourceBaseSlow(), v8::String::GetExternalStringResourceSlow(), HasExternalForwardingIndex(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::HasExternalForwardingIndex(), v8::String::IsExternalOneByte(), v8::String::IsExternalTwoByte(), v8::String::VerifyExternalStringResource(), and v8::String::VerifyExternalStringResourceBase().
IsForwardingIndex()
bool v8::internal::Name::IsForwardingIndex (uint32_t raw_hash_field) [inline], [static]
Definition at line 112 of file name-inl.h.
                                                    {
  return HashFieldTypeBits::decode(raw_hash_field) ==
         HashFieldType::kForwardingIndex;
}
References v8::base::BitField< T, shift, size, U >::decode(), kForwardingIndex, and raw_hash_field().
Referenced by EnsureRawHash(), GetRawHashFromForwardingTable(), HasForwardingIndex(), hash(), HasHashCode(), v8::internal::NameDictionaryLookupForwardedString(), v8::internal::NameDictionaryLookupForwardedStringWithHandle(), RawHash(), set_raw_hash_field_if_empty(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), and TryGetHash().
IsHash()
bool v8::internal::Name::IsHash (uint32_t raw_hash_field) [inline], [static]
Definition at line 101 of file name-inl.h.
                                         {
  return HashFieldTypeBits::decode(raw_hash_field) == HashFieldType::kHash;
}
References v8::base::BitField< T, shift, size, U >::decode(), kHash, and raw_hash_field().
IsHashFieldComputed()
bool v8::internal::Name::IsHashFieldComputed (uint32_t raw_hash_field) [inline], [static]
Definition at line 96 of file name-inl.h.
                                                      {
  return (raw_hash_field & kHashNotComputedMask) == 0;
}
References kHashNotComputedMask, and raw_hash_field().
Referenced by v8::internal::String::AsArrayIndex(), v8::internal::String::AsIntegerIndex(), EnsureRawHash(), hash(), HasHashCode(), v8::internal::InternalizedStringKey::InternalizedStringKey(), v8::internal::StringTable::LookupString(), v8::internal::StubCache::PrimaryOffset(), v8::internal::StringForwardingTable::Record::raw_hash(), v8::internal::StringForwardingTable::Record::set_raw_hash_if_empty(), TryGetHash(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
IsIntegerIndex()
bool v8::internal::Name::IsIntegerIndex (uint32_t raw_hash_field) [inline], [static]
Definition at line 106 of file name-inl.h.
                                                 {
  return HashFieldTypeBits::decode(raw_hash_field) ==
         HashFieldType::kIntegerIndex;
}
References v8::base::BitField< T, shift, size, U >::decode(), kIntegerIndex, and raw_hash_field().
Referenced by v8::internal::String::AsArrayIndex(), v8::internal::String::AsIntegerIndex(), v8::internal::AstRawString::IsIntegerIndex(), v8::internal::StringHasher::MakeArrayIndexHash(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
IsInteresting()
bool v8::internal::Name::IsInteresting (Isolate * isolate) [inline]
Definition at line 250 of file name-inl.h.
                                         {
  // TODO(ishell): consider using ReadOnlyRoots::IsNameForProtector() trick for
  // these strings and interesting symbols.
  return (IsSymbol(this) && Cast<Symbol>(this)->is_interesting_symbol()) ||
         this == *isolate->factory()->toJSON_string() ||
         this == *isolate->factory()->get_string();
}
References v8::internal::Isolate::factory().
IsInternalizedForwardingIndex()
bool v8::internal::Name::IsInternalizedForwardingIndex (uint32_t raw_hash_field) [inline], [static]
Definition at line 118 of file name-inl.h.
                                                                {
  return HashFieldTypeBits::decode(raw_hash_field) ==
             HashFieldType::kForwardingIndex &&
         IsInternalizedForwardingIndexBit::decode(raw_hash_field);
}
References v8::base::BitField< T, shift, size, U >::decode(), kForwardingIndex, and raw_hash_field().
Referenced by HasInternalizedForwardingIndex(), v8::internal::StringTable::LookupString(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
IsPrivate()
bool v8::internal::Name::IsPrivate () [inline]
Definition at line 258 of file name-inl.h.
                     {
  return IsSymbol(this) && Cast<Symbol>(this)->is_private();
}
Referenced by IsPrivateName().
IsPrivateBrand()
bool v8::internal::Name::IsPrivateBrand () [inline]
Definition at line 269 of file name-inl.h.
                          {
  bool is_private_brand =
      IsSymbol(this) && Cast<Symbol>(this)->is_private_brand();
  DCHECK_IMPLIES(is_private_brand, IsPrivateName());
  return is_private_brand;
}
References DCHECK_IMPLIES, and IsPrivateName().
IsPrivateName()
bool v8::internal::Name::IsPrivateName () [inline]
Definition at line 262 of file name-inl.h.
                         {
  bool is_private_name =
      IsSymbol(this) && Cast<Symbol>(this)->is_private_name();
  DCHECK_IMPLIES(is_private_name, IsPrivate());
  return is_private_name;
}
References DCHECK_IMPLIES, and IsPrivate().
Referenced by IsPrivateBrand().
NameShortPrint() [1/2]
void v8::internal::Name::NameShortPrint ()
Definition at line 3948 of file objects-printer.cc.
                          {
  if (IsString(this)) {
    PrintF("%s", Cast<String>(this)->ToCString().get());
  } else {
    DCHECK(IsSymbol(this));
    Tagged<Symbol> s = Cast<Symbol>(this);
    if (IsUndefined(s->description())) {
      PrintF("#<%s>", s->PrivateSymbolToName());
    } else {
      PrintF("<%s>", Cast<String>(s->description())->ToCString().get());
    }
  }
}
NameShortPrint() [2/2]
int v8::internal::Name::NameShortPrint (base::Vector< char > str)
Definition at line 3963 of file objects-printer.cc.
                                             {
  if (IsString(this)) {
    return SNPrintF(str, "%s", Cast<String>(this)->ToCString().get());
  } else {
    DCHECK(IsSymbol(this));
    Tagged<Symbol> s = Cast<Symbol>(this);
    if (IsUndefined(s->description())) {
      return SNPrintF(str, "#<%s>", s->PrivateSymbolToName());
    } else {
      return SNPrintF(str, "<%s>",
                      Cast<String>(s->description())->ToCString().get());
    }
  }
}
raw_hash_field() [1/2]
uint32_t v8::internal::Name::raw_hash_field () const [inline]
Definition at line 47 of file name.h.
                                         {
    return raw_hash_field_.load(std::memory_order_relaxed);
  }
References raw_hash_field_.
Referenced by v8::internal::String::AsArrayIndex(), v8::internal::String::AsIntegerIndex(), ContainsCachedArrayIndex(), EnsureRawHash(), HasExternalForwardingIndex(), HasForwardingIndex(), hash(), HasHashCode(), HasInternalizedForwardingIndex(), IsExternalForwardingIndex(), IsForwardingIndex(), IsHash(), IsHashFieldComputed(), IsIntegerIndex(), IsInternalizedForwardingIndex(), RawHash(), and TryGetHash().
raw_hash_field() [2/2]
uint32_t v8::internal::Name::raw_hash_field (AcquireLoadTag) const [inline]
Definition at line 51 of file name.h.
                                                       {
    return raw_hash_field_.load(std::memory_order_acquire);
  }
References raw_hash_field_.
RawHash()
uint32_t v8::internal::Name::RawHash () [inline]
Definition at line 200 of file name-inl.h.
                       {
  uint32_t field = raw_hash_field(kAcquireLoad);
  if (V8_UNLIKELY(IsForwardingIndex(field))) {
    return GetRawHashFromForwardingTable(field);
  }
  return field;
}
References GetRawHashFromForwardingTable(), IsForwardingIndex(), v8::kAcquireLoad, raw_hash_field(), and V8_UNLIKELY.
set_raw_hash_field() [1/2]
void v8::internal::Name::set_raw_hash_field (uint32_t hash) [inline]
Definition at line 55 of file name.h.
                                                {
    raw_hash_field_.store(hash, std::memory_order_relaxed);
  }
References hash(), and raw_hash_field_.
set_raw_hash_field() [2/2]
void v8::internal::Name::set_raw_hash_field (uint32_t hash, ReleaseStoreTag) [inline]
Definition at line 59 of file name.h.
                                                                 {
    raw_hash_field_.store(hash, std::memory_order_release);
  }
References hash(), and raw_hash_field_.
set_raw_hash_field_if_empty()
void v8::internal::Name::set_raw_hash_field_if_empty (uint32_t hash) [inline]
Definition at line 214 of file name-inl.h.
                                                    {
  uint32_t field_value = kEmptyHashField;
  bool result = raw_hash_field_.compare_exchange_strong(field_value, hash);
  USE(result);
  // CAS can only fail if the string is shared or we use the forwarding table
  // for all strings and the hash was already set (by another thread) or it is
  // a forwarding index (that overwrites the previous hash).
  // In all cases we don't want overwrite the old value, so we don't handle the
  // failure case.
  DCHECK_IMPLIES(!result, (Cast<String>(this)->IsShared() ||
                           v8_flags.always_use_string_forwarding_table) &&
                              (field_value == hash || IsForwardingIndex(hash)));
}
References DCHECK_IMPLIES, hash(), IsForwardingIndex(), v8::internal::IsShared(), kEmptyHashField, raw_hash_field_, v8::base::internal::result, USE, and v8::internal::v8_flags.
ToFunctionName() [1/2]
MaybeDirectHandle< String > v8::internal::Name::ToFunctionName (Isolate * isolate, DirectHandle< Name > name) [static]
Definition at line 4087 of file objects.cc.
                                                                        {
  if (IsString(*name)) return Cast<String>(name);
  // ES6 section 9.2.11 SetFunctionName, step 4.
  DirectHandle<Object> description(Cast<Symbol>(name)->description(), isolate);
  if (IsUndefined(*description, isolate)) {
    return isolate->factory()->empty_string();
  }
  IncrementalStringBuilder builder(isolate);
  builder.AppendCharacter('[');
  builder.AppendString(Cast<String>(description));
  builder.AppendCharacter(']');
  return builder.Finish();
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), and v8::internal::name.
Referenced by v8::internal::ExternalLogEventListener::CodeCreateEvent(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Isolate::ReportExceptionPropertyCallback(), v8::internal::JSFunction::SetName(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetter(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetterSetter(), and ToFunctionName().
ToFunctionName() [2/2]
MaybeDirectHandle< String > v8::internal::Name::ToFunctionName (Isolate * isolate, DirectHandle< Name > name, DirectHandle< String > prefix) [static]
Definition at line 4103 of file objects.cc.
                                                                            {
  DirectHandle<String> name_string;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, name_string,
                             ToFunctionName(isolate, name));
  IncrementalStringBuilder builder(isolate);
  builder.AppendString(prefix);
  builder.AppendCharacter(' ');
  builder.AppendString(name_string);
  return builder.Finish();
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendString(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::IncrementalStringBuilder::Finish(), v8::internal::name, and ToFunctionName().
TryGetHash()
bool v8::internal::Name::TryGetHash (uint32_t * hash) const [inline]
Definition at line 237 of file name-inl.h.
                                          {
  uint32_t field = raw_hash_field(kAcquireLoad);
  if (IsHashFieldComputed(field)) {
    *hash = HashBits::decode(field);
    return true;
  }
  if (V8_UNLIKELY(IsForwardingIndex(field))) {
    *hash = HashBits::decode(GetRawHashFromForwardingTable(field));
    return true;
  }
  return false;
}
References v8::base::BitField< T, shift, size, U >::decode(), GetRawHashFromForwardingTable(), hash(), IsForwardingIndex(), IsHashFieldComputed(), v8::kAcquireLoad, raw_hash_field(), and V8_UNLIKELY.
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 230 of file name.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 235 of file name.h.
compiler::WasmGraphBuilder
friend class compiler::WasmGraphBuilder [friend]
Definition at line 236 of file name.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 234 of file name.h.
maglev::MaglevGraphBuilder
friend class maglev::MaglevGraphBuilder [friend]
Definition at line 233 of file name.h.
SandboxTesting
friend class SandboxTesting [friend]
Definition at line 232 of file name.h.
StringBuiltinsAssembler
friend class StringBuiltinsAssembler [friend]
Definition at line 231 of file name.h.
TorqueGeneratedNameAsserts
friend class TorqueGeneratedNameAsserts [friend]
Definition at line 237 of file name.h.
V8HeapExplorer
friend class V8HeapExplorer [friend]
Definition at line 229 of file name.h.
Member Data Documentation
kArrayIndexLengthBits
const int v8::internal::Name::kArrayIndexLengthBits [static]
Initial value:
=
      kBitsPerInt - kArrayIndexValueBits - HashFieldTypeBits::kSize
Definition at line 170 of file name.h.
kArrayIndexValueBits
const int v8::internal::Name::kArrayIndexValueBits = 24 [static]
Definition at line 169 of file name.h.
Referenced by v8::internal::StringHasher::MakeArrayIndexHash().
kDoesNotContainCachedArrayIndexMask
const unsigned int v8::internal::Name::kDoesNotContainCachedArrayIndexMask [static]
Initial value:
=
      (~static_cast<unsigned>(kMaxCachedArrayIndexLength)
       << ArrayIndexLengthBits::kShift) |
      HashFieldTypeBits::kMask
Definition at line 190 of file name.h.
Referenced by ContainsCachedArrayIndex(), v8::internal::CodeStubAssembler::IsUniqueNameNoCachedIndex(), v8::internal::CodeStubAssembler::StringToNumber(), and v8::internal::CodeStubAssembler::TryToName().
kDoesNotContainIntegerOrForwardingIndexMask
const unsigned int v8::internal::Name::kDoesNotContainIntegerOrForwardingIndexMask = 0b10 [static]
Definition at line 197 of file name.h.
Referenced by v8::internal::CodeStubAssembler::IsUniqueNameNoIndex().
kEmptyHashField
constexpr int v8::internal::Name::kEmptyHashField [static], [constexpr]
Initial value:
=
      HashFieldTypeBits::encode(HashFieldType::kEmpty)
Definition at line 133 of file name.h.
Referenced by v8::internal::StringBuiltinsAssembler::AllocateConsString(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::StringBuiltinsReducer< Next >::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateSeqTwoByteString(), v8::internal::StringBuiltinsReducer< Next >::AllocateSeqTwoByteString(), v8::internal::CodeStubAssembler::AllocateSlicedString(), v8::internal::maglev::MaglevAssembler::AllocateTwoByteString(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForConsString(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewConsString(), v8::internal::Factory::NewExternalStringFromOneByte(), v8::internal::Factory::NewExternalStringFromTwoByte(), v8::internal::Factory::NewProperSubString(), v8::internal::FactoryBase< Impl >::NewRawStringWithMap(), v8::internal::ReadOnlyDeserializer::PostProcessNewObjects(), set_raw_hash_field_if_empty(), v8::internal::Factory::SizeToString(), and v8::internal::FactoryBase< Impl >::SmiToString().
kHashNotComputedMask
constexpr int v8::internal::Name::kHashNotComputedMask = 1 [static], [constexpr]
Definition at line 131 of file name.h.
Referenced by v8::internal::AstRawString::Hash(), IsHashFieldComputed(), v8::internal::CodeStubAssembler::LoadNameHash(), v8::internal::CodeStubAssembler::LoadNameHashAssumeComputed(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::StringForwardingTable::Record::set_raw_hash_if_empty(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringHash(), and v8::internal::AccessorAssembler::StubCachePrimaryOffset().
kMaxArrayIndex
const uint32_t v8::internal::Name::kMaxArrayIndex = kMaxUInt32 - 1 [static]
Definition at line 152 of file name.h.
Referenced by v8::internal::StringHasher::HashSequentialString(), and v8::internal::detail::TryParseArrayIndex().
kMaxArrayIndexSize
const int v8::internal::Name::kMaxArrayIndexSize = 10 [static]
Definition at line 155 of file name.h.
Referenced by v8::internal::StringHasher::HashSequentialString(), v8::internal::StringHasher::MakeArrayIndexHash(), and v8::internal::detail::TryParseArrayIndex().
kMaxCachedArrayIndexLength
const int v8::internal::Name::kMaxCachedArrayIndexLength = 7 [static]
Definition at line 150 of file name.h.
Referenced by v8::internal::StringHasher::HashSequentialString(), and v8::internal::StringHasher::MakeArrayIndexHash().
kMaxIntegerIndexSize
const int v8::internal::Name::kMaxIntegerIndexSize [static]
Initial value:
=
      std::min(16, int{10 * (sizeof(size_t) / 4)})
Definition at line 163 of file name.h.
Referenced by v8::internal::StringHasher::HashSequentialString(), and v8::internal::detail::TryParseArrayIndex().
raw_hash_field_
std::atomic_uint32_t v8::internal::Name::raw_hash_field_ [private]
Definition at line 241 of file name.h.
Referenced by raw_hash_field(), set_raw_hash_field(), and set_raw_hash_field_if_empty().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/name.h
/mnt/V8SourceCode/src/diagnostics/objects-printer.cc
/mnt/V8SourceCode/src/objects/name-inl.h
/mnt/V8SourceCode/src/objects/objects.cc