cppgc::subtle::HeapState Class Reference
Helpers to peek into heap-internal state.
#include <heap-state.h>
Static Public Member Functions
static bool IsMarking (const HeapHandle &heap_handle)
Returns whether the garbage collector is marking.
static bool IsSweeping (const HeapHandle &heap_handle)
static bool IsSweepingOnOwningThread (const HeapHandle &heap_handle)
static bool IsInAtomicPause (const HeapHandle &heap_handle)
Returns whether the garbage collector is in the atomic pause, i.e., the mutator is stopped from running.
static bool PreviousGCWasConservative (const HeapHandle &heap_handle)
Returns whether the last garbage collection was finalized conservatively (i.e., with a non-empty stack).
Private Member Functions
HeapState ()=delete
Detailed Description
Helpers to peek into heap-internal state.
Definition at line 19 of file heap-state.h.
Constructor & Destructor Documentation
HeapState()
cppgc::subtle::HeapState::HeapState () [private], [delete]
Member Function Documentation
IsInAtomicPause()
bool cppgc::subtle::HeapState::IsInAtomicPause (const HeapHandle & heap_handle) [static]
Returns whether the garbage collector is in the atomic pause, i.e., the mutator is stopped from running.
This API is experimental and is expected to be removed in future.
Parameters
heap_handle The corresponding heap.
Returns
true if the garbage collector is currently in the atomic pause, and false otherwise.
Definition at line 32 of file heap-state.cc.
                                                             {
  return internal::HeapBase::From(heap_handle).in_atomic_pause();
}
References cppgc::internal::HeapBase::From(), and cppgc::internal::HeapBase::in_atomic_pause().
IsMarking()
bool cppgc::subtle::HeapState::IsMarking (const HeapHandle & heap_handle) [static]
Returns whether the garbage collector is marking.
This API is experimental and is expected to be removed in future.
Parameters
heap_handle The corresponding heap.
Returns
true if the garbage collector is currently marking, and false otherwise.
Definition at line 13 of file heap-state.cc.
                                                       {
  const internal::MarkerBase* marker =
      internal::HeapBase::From(heap_handle).marker();
  return marker && marker->IsMarking();
}
References cppgc::internal::HeapBase::From(), cppgc::internal::MarkerBase::IsMarking(), and cppgc::internal::HeapBase::marker().
IsSweeping()
bool cppgc::subtle::HeapState::IsSweeping (const HeapHandle & heap_handle) [static]
Definition at line 20 of file heap-state.cc.
                                                        {
  return internal::HeapBase::From(heap_handle).sweeper().IsSweepingInProgress();
}
References cppgc::internal::HeapBase::From(), cppgc::internal::Sweeper::IsSweepingInProgress(), and cppgc::internal::HeapBase::sweeper().
IsSweepingOnOwningThread()
bool cppgc::subtle::HeapState::IsSweepingOnOwningThread (const HeapHandle & heap_handle) [static]
Definition at line 25 of file heap-state.cc.
                                                                      {
  return internal::HeapBase::From(heap_handle)
      .sweeper()
      .IsSweepingOnMutatorThread();
}
References cppgc::internal::HeapBase::From(), cppgc::internal::Sweeper::IsSweepingOnMutatorThread(), and cppgc::internal::HeapBase::sweeper().
PreviousGCWasConservative()
bool cppgc::subtle::HeapState::PreviousGCWasConservative (const HeapHandle & heap_handle) [static]
Returns whether the last garbage collection was finalized conservatively (i.e., with a non-empty stack).
This API is experimental and is expected to be removed in future.
Parameters
heap_handle The corresponding heap.
Returns
true if the last garbage collection was finalized conservatively, and false otherwise.
Definition at line 37 of file heap-state.cc.
                                                                       {
  return internal::HeapBase::From(heap_handle).stack_state_of_prev_gc() ==
         EmbedderStackState::kMayContainHeapPointers;
}
References cppgc::internal::HeapBase::From(), cppgc::kMayContainHeapPointers, and cppgc::internal::HeapBase::stack_state_of_prev_gc().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/heap-state.h
/mnt/V8SourceCode/src/heap/cppgc/heap-state.cc