v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor Class Reference
Public Member Functions
ClearWeaknessProcessor (TracedNodeBlock::YoungList &young_blocks, size_t num_young_blocks, Heap *heap, RootVisitor *visitor, WeakSlotCallbackWithHeap should_reset_handle)
template<bool IsMainThread>
void ProcessBlock (TracedNodeBlock *block)
Static Public Attributes
static constexpr auto kMainThreadScope
static constexpr auto kBackgroundThreadScope
static constexpr char kStartNote [] = `ClearWeaknessProcessor start`
Private Attributes
RootVisitor * visitor_
EmbedderRootsHandler * handler_
WeakSlotCallbackWithHeap should_reset_handle_
Detailed Description
Definition at line 525 of file traced-handles.cc.
Constructor & Destructor Documentation
ClearWeaknessProcessor()
v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::ClearWeaknessProcessor (TracedNodeBlock::YoungList & young_blocks, size_t num_young_blocks, Heap * heap, RootVisitor * visitor, WeakSlotCallbackWithHeap should_reset_handle) [inline]
Definition at line 534 of file traced-handles.cc.
      : ParallelWeakHandlesProcessor(heap, young_blocks, num_young_blocks),
        visitor_(visitor),
        handler_(heap->GetEmbedderRootsHandler()),
        should_reset_handle_(should_reset_handle) {}
Member Function Documentation
ProcessBlock()
template<bool IsMainThread>
void v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::ProcessBlock (TracedNodeBlock * block) [inline]
Definition at line 544 of file traced-handles.cc.
                                            {
    const auto saved_used_nodes_in_block = block->used();
    for (TracedNode* node : *block) {
      if (!node->is_weak()) {
        continue;
      }
      DCHECK(node->is_in_use());
      DCHECK(node->is_in_young_list());
      const bool should_reset = should_reset_handle_(heap(), node->location());
      if (should_reset) {
        FullObjectSlot slot = node->location();
        bool node_cleared = true;
        if constexpr (IsMainThread) {
          handler_->ResetRoot(
              *reinterpret_cast<v8::TracedReference<v8::Value>*>(&slot));
        } else {
          node_cleared = handler_->TryResetRoot(
              *reinterpret_cast<v8::TracedReference<v8::Value>*>(&slot));
        }
        if (node_cleared) {
          // Mark as cleared due to weak semantics.
          node->set_raw_object(kTracedHandleMinorGCWeakResetZapValue);
          DCHECK(!node->is_in_use());
          DCHECK(!node->is_weak());
        } else {
          block->SetReprocessing(true);
        }
      } else {
        node->set_weak(false);
        if (visitor_) {
          visitor_->VisitRootPointer(Root::kTracedHandles, nullptr,
                                     node->location());
        }
      }
    }
    DCHECK_GE(saved_used_nodes_in_block, block->used());
    block->SetLocallyFreed(saved_used_nodes_in_block - block->used());
  }
References v8::internal::DCHECK(), DCHECK_GE, heap(), v8::internal::kTracedHandleMinorGCWeakResetZapValue, v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::location(), v8::internal::TracedNodeBlock::SetLocallyFreed(), v8::internal::TracedNodeBlock::SetReprocessing(), and v8::internal::TracedNodeBlock::used().
Member Data Documentation
handler_
EmbedderRootsHandler* v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::handler_ [private]
Definition at line 586 of file traced-handles.cc.
kBackgroundThreadScope
constexpr auto v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::kBackgroundThreadScope [static], [constexpr]
Initial value:
=
      GCTracer::Scope::SCAVENGER_BACKGROUND_TRACED_HANDLES_RESET_PARALLEL
Definition at line 530 of file traced-handles.cc.
kMainThreadScope
constexpr auto v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::kMainThreadScope [static], [constexpr]
Initial value:
=
      GCTracer::Scope::SCAVENGER_TRACED_HANDLES_RESET_PARALLEL
Definition at line 528 of file traced-handles.cc.
kStartNote
constexpr char v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::kStartNote[] = `ClearWeaknessProcessor start` [static], [constexpr]
Definition at line 532 of file traced-handles.cc.
should_reset_handle_
WeakSlotCallbackWithHeap v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::should_reset_handle_ [private]
Definition at line 587 of file traced-handles.cc.
visitor_
RootVisitor* v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::visitor_ [private]
Definition at line 585 of file traced-handles.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/traced-handles.cc