v8::internal::JSRegExpResultIndices Class Reference
#include <js-regexp.h>
Static Public Member Functions
static DirectHandle< JSRegExpResultIndices > BuildIndices (Isolate *isolate, DirectHandle< RegExpMatchInfo > match_info, DirectHandle< Object > maybe_names)
Static Public Attributes
static constexpr int kGroupsIndex = 0
static constexpr int kInObjectPropertyCount = 1
static constexpr int kGroupsDescriptorIndex = 1
Detailed Description
Definition at line 353 of file js-regexp.h.
Member Function Documentation
BuildIndices()
DirectHandle< JSRegExpResultIndices > v8::internal::JSRegExpResultIndices::BuildIndices (Isolate * isolate, DirectHandle< RegExpMatchInfo > match_info, DirectHandle< Object > maybe_names) [static]
Definition at line 18 of file js-regexp.cc.
                                      {
  DirectHandle<JSRegExpResultIndices> indices(
      Cast<JSRegExpResultIndices>(isolate->factory()->NewJSObjectFromMap(
          isolate->regexp_result_indices_map())));
  // Initialize indices length to avoid having a partially initialized object
  // should GC be triggered by creating a NewFixedArray.
  indices->set_length(Smi::zero());
  // Build indices array from RegExpMatchInfo.
  int num_indices = match_info->number_of_capture_registers();
  int num_results = num_indices >> 1;
  DirectHandle<FixedArray> indices_array =
      isolate->factory()->NewFixedArray(num_results);
  JSArray::SetContent(isolate, indices, indices_array);
  for (int i = 0; i < num_results; i++) {
    const int start_offset =
        match_info->capture(RegExpMatchInfo::capture_start_index(i));
    const int end_offset =
        match_info->capture(RegExpMatchInfo::capture_end_index(i));
    // Any unmatched captures are set to undefined, otherwise we set them to a
    // subarray of the indices.
    if (start_offset == -1) {
      indices_array->set(i, ReadOnlyRoots(isolate).undefined_value());
    } else {
      DirectHandle<FixedArray> indices_sub_array(
          isolate->factory()->NewFixedArray(2));
      indices_sub_array->set(0, Smi::FromInt(start_offset));
      indices_sub_array->set(1, Smi::FromInt(end_offset));
      DirectHandle<JSArray> indices_sub_jsarray =
          isolate->factory()->NewJSArrayWithElements(indices_sub_array,
                                                     PACKED_SMI_ELEMENTS, 2);
      indices_array->set(i, *indices_sub_jsarray);
    }
  }
  // If there are no capture groups, set the groups property to undefined.
  FieldIndex groups_index = FieldIndex::ForDescriptor(
      indices->map(), InternalIndex(kGroupsDescriptorIndex));
  if (IsUndefined(*maybe_names, isolate)) {
    indices->FastPropertyAtPut(groups_index,
                               ReadOnlyRoots(isolate).undefined_value());
    return indices;
  }
  // Create a groups property which returns a dictionary of named captures to
  // their corresponding capture indices.
  auto names = Cast<FixedArray>(maybe_names);
  int num_names = names->length() >> 1;
  DirectHandle<HeapObject> group_names;
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    group_names = isolate->factory()->NewSwissNameDictionary(num_names);
  } else {
    group_names = isolate->factory()->NewNameDictionary(num_names);
  }
  DirectHandle<PropertyDictionary> group_names_dict =
      Cast<PropertyDictionary>(group_names);
  for (int i = 0; i < num_names; i++) {
    int base_offset = i * 2;
    int name_offset = base_offset;
    int index_offset = base_offset + 1;
    DirectHandle<String> name(Cast<String>(names->get(name_offset)), isolate);
    Tagged<Smi> smi_index = Cast<Smi>(names->get(index_offset));
    DirectHandle<Object> capture_indices(indices_array->get(smi_index.value()),
                                         isolate);
    if (!IsUndefined(*capture_indices, isolate)) {
      capture_indices = Cast<JSArray>(capture_indices);
    }
    InternalIndex group_entry = group_names_dict->FindEntry(isolate, name);
    // Duplicate group entries are possible if the capture groups are in
    // different alternatives, i.e. only one of them can actually match.
    // Therefore when we find a duplicate entry, either the current entry is
    // undefined (didn't match anything) or the indices for the current capture
    // are undefined. In the latter case we don't do anything, in the former
    // case we update the entry.
    if (group_entry.is_found()) {
      DCHECK(v8_flags.js_regexp_duplicate_named_groups);
      if (!IsUndefined(*capture_indices, isolate)) {
        DCHECK(IsUndefined(group_names_dict->ValueAt(group_entry), isolate));
        group_names_dict->ValueAtPut(group_entry, *capture_indices);
      }
    } else {
      group_names_dict =
          PropertyDictionary::Add(isolate, group_names_dict, name,
                                  capture_indices, PropertyDetails::Empty());
    }
  }
  // Convert group_names to a JSObject and store at the groups property of the
  // result indices.
  DirectHandle<FixedArrayBase> elements =
      isolate->factory()->empty_fixed_array();
  DirectHandle<Null> null = isolate->factory()->null_value();
  DirectHandle<JSObject> js_group_names =
      isolate->factory()->NewSlowJSObjectWithPropertiesAndElements(
          null, group_names, elements);
  indices->FastPropertyAtPut(groups_index, *js_group_names);
  return indices;
}
References v8::bigint::Add(), v8::internal::RegExpMatchInfo::capture_end_index(), v8::internal::RegExpMatchInfo::capture_start_index(), v8::internal::DCHECK(), v8::internal::PropertyDetails::Empty(), v8::internal::Isolate::factory(), v8::internal::FieldIndex::ForDescriptor(), v8::internal::Smi::FromInt(), v8::internal::InternalIndex::is_found(), kGroupsDescriptorIndex, v8::internal::name, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::Factory::NewJSObjectFromMap(), v8::internal::Factory::NewNameDictionary(), v8::internal::Factory::NewSlowJSObjectWithPropertiesAndElements(), v8::internal::FactoryBase< Impl >::NewSwissNameDictionary(), v8::internal::PACKED_SMI_ELEMENTS, v8::internal::JSArray::SetContent(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::internal::v8_flags, v8::internal::Tagged< Smi >::value(), and v8::internal::Smi::zero().
Referenced by v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
kGroupsDescriptorIndex
constexpr int v8::internal::JSRegExpResultIndices::kGroupsDescriptorIndex = 1 [static], [constexpr]
Definition at line 366 of file js-regexp.h.
Referenced by BuildIndices(), and v8::internal::Genesis::InstallABunchOfRandomThings().
kGroupsIndex
constexpr int v8::internal::JSRegExpResultIndices::kGroupsIndex = 0 [static], [constexpr]
Definition at line 362 of file js-regexp.h.
Referenced by v8::internal::Genesis::InstallABunchOfRandomThings().
kInObjectPropertyCount
constexpr int v8::internal::JSRegExpResultIndices::kInObjectPropertyCount = 1 [static], [constexpr]
Definition at line 363 of file js-regexp.h.
Referenced by v8::internal::Genesis::InstallABunchOfRandomThings().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-regexp.h
/mnt/V8SourceCode/src/objects/js-regexp.cc