v8::internal::maglev::CheckedIntPtrToInt32 Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckedIntPtrToInt32 (uint64_t bitfield)
Input & input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kIntPtr}
Private Types
using Base = FixedInputValueNodeT< 1, CheckedIntPtrToInt32 >
Additional Inherited Members
Detailed Description
Definition at line 4315 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckedIntPtrToInt32::Base = FixedInputValueNodeT<1, CheckedIntPtrToInt32> [private]
Definition at line 4317 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckedIntPtrToInt32()
v8::internal::maglev::CheckedIntPtrToInt32::CheckedIntPtrToInt32 (uint64_t bitfield) [inline], [explicit]
Definition at line 4320 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::CheckedIntPtrToInt32::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 170 of file maglev-ir-arm.cc.
                                                                      {
  // On 32-bit platforms, IntPtr is the same as Int32.
}
input()
Input& v8::internal::maglev::CheckedIntPtrToInt32::input () [inline]
Definition at line 4328 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by SetValueLocationConstraints().
PrintParams()
void v8::internal::maglev::CheckedIntPtrToInt32::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 4332 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::CheckedIntPtrToInt32::SetValueLocationConstraints ()
Definition at line 165 of file maglev-ir-arm.cc.
                                                       {
  UseRegister(input());
  DefineSameAsFirst(this);
}
References v8::internal::maglev::DefineSameAsFirst(), input(), and v8::internal::maglev::UseRegister().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckedIntPtrToInt32::kInputTypes {ValueRepresentation::kIntPtr} [static], [constexpr]
Definition at line 4326 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckedIntPtrToInt32::kProperties [static], [constexpr]
Initial value:
= OpProperties::Int32() |
                                              OpProperties::ConversionNode() |
                                              OpProperties::EagerDeopt()
Definition at line 4322 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc