v8::internal::Variable Class Reference
#include <variables.h>
Public Types
enum ForceHoleInitializationFlag { kHoleInitializationNotForced = 0
, kHasHoleCheckUseInDifferentClosureScope = 1 << 0
, kHasHoleCheckUseInSameClosureScope = 1 << 1
, kHasHoleCheckUseInUnknownScope
 }
using HoleCheckBitmap = uint64_t
using List = base::ThreadedList< Variable >
Public Member Functions
Variable (Scope *scope, const AstRawString *name, VariableMode mode, VariableKind kind, InitializationFlag initialization_flag, MaybeAssignedFlag maybe_assigned_flag=kNotAssigned, IsStaticFlag is_static_flag=IsStaticFlag::kNotStatic)
Variable (Variable *other)
Scope * scope () const
void set_scope (Scope *scope)
Handle< String > name () const
const AstRawString * raw_name () const
VariableMode mode () const
void set_mode (VariableMode mode)
void set_is_static_flag (IsStaticFlag is_static_flag)
IsStaticFlag is_static_flag () const
bool is_static () const
bool has_forced_context_allocation () const
void ForceContextAllocation ()
bool is_used ()
void set_is_used ()
MaybeAssignedFlag maybe_assigned () const
void clear_maybe_assigned ()
void SetMaybeAssigned ()
bool requires_brand_check () const
int initializer_position ()
void set_initializer_position (int pos)
bool IsUnallocated () const
bool IsParameter () const
bool IsStackLocal () const
bool IsStackAllocated () const
bool IsContextSlot () const
bool IsLookupSlot () const
bool IsGlobalObjectProperty () const
bool IsReplGlobal () const
bool is_dynamic () const
InitializationFlag initialization_flag () const
bool binding_needs_init () const
ForceHoleInitializationFlag force_hole_initialization_flag_field () const
bool IsHoleInitializationForced () const
bool HasHoleCheckUseInSameClosureScope () const
void ForceHoleInitialization (ForceHoleInitializationFlag flag)
void ResetHoleCheckBitmapIndex ()
void RememberHoleCheckInBitmap (HoleCheckBitmap &bitmap, ZoneVector< Variable * > &list)
bool HasRememberedHoleCheck (HoleCheckBitmap bitmap) const
bool throw_on_const_assignment (LanguageMode language_mode) const
bool is_this () const
bool is_sloppy_function_name () const
bool is_parameter () const
bool is_sloppy_block_function ()
Variable * local_if_not_shadowed () const
bool has_local_if_not_shadowed () const
void set_local_if_not_shadowed (Variable *local)
VariableLocation location () const
VariableKind kind () const
int index () const
bool IsReceiver () const
bool IsExport () const
void AllocateTo (VariableLocation location, int index)
void MakeParameterNonSimple ()
void RewriteLocationForRepl ()
Static Public Member Functions
static InitializationFlag DefaultInitializationFlag (VariableMode mode)
Static Public Attributes
static constexpr uint8_t kUncacheableHoleCheckBitmapIndex = 0
static constexpr uint8_t kHoleCheckBitmapBits
Private Types
using VariableModeField = base::BitField16< VariableMode, 0, 4 >
using VariableKindField = VariableModeField::Next< VariableKind, 3 >
using LocationField = VariableKindField::Next< VariableLocation, 3 >
using ForceContextAllocationBit = LocationField::Next< bool, 1 >
using IsUsedField = ForceContextAllocationBit::Next< bool, 1 >
using InitializationFlagField = IsUsedField::Next< InitializationFlag, 1 >
using MaybeAssignedFlagField = InitializationFlagField::Next< MaybeAssignedFlag, 1 >
using IsStaticFlagField = MaybeAssignedFlagField::Next< IsStaticFlag, 1 >
using HoleCheckBitmapIndexField = base::BitField16< uint8_t, 0, 8 >
using ForceHoleInitializationFlagField = HoleCheckBitmapIndexField::Next< ForceHoleInitializationFlag, 2 >
Private Member Functions
void set_maybe_assigned ()
uint8_t HoleCheckBitmapIndex () const
void AssignHoleCheckBitmapIndex (ZoneVector< Variable * > &list, uint8_t next_index)
Variable ** next ()
Private Attributes
Scope * scope_
const AstRawString * name_
Variable * local_if_not_shadowed_
Variable * next_
int index_
int initializer_position_
uint16_t bit_field_
uint16_t hole_check_analysis_bit_field_
friend List
Detailed Description
Definition at line 21 of file variables.h.
Member Typedef Documentation
ForceContextAllocationBit
using v8::internal::Variable::ForceContextAllocationBit = LocationField::Next<bool, 1> [private]
Definition at line 351 of file variables.h.
ForceHoleInitializationFlagField
using v8::internal::Variable::ForceHoleInitializationFlagField = HoleCheckBitmapIndexField::Next<ForceHoleInitializationFlag, 2> [private]
Definition at line 359 of file variables.h.
HoleCheckBitmap
using v8::internal::Variable::HoleCheckBitmap = uint64_t
Definition at line 210 of file variables.h.
HoleCheckBitmapIndexField
using v8::internal::Variable::HoleCheckBitmapIndexField = base::BitField16<uint8_t, 0, 8> [private]
Definition at line 358 of file variables.h.
InitializationFlagField
using v8::internal::Variable::InitializationFlagField = IsUsedField::Next<InitializationFlag, 1> [private]
Definition at line 353 of file variables.h.
IsStaticFlagField
using v8::internal::Variable::IsStaticFlagField = MaybeAssignedFlagField::Next<IsStaticFlag, 1> [private]
Definition at line 356 of file variables.h.
IsUsedField
using v8::internal::Variable::IsUsedField = ForceContextAllocationBit::Next<bool, 1> [private]
Definition at line 352 of file variables.h.
List
using v8::internal::Variable::List = base::ThreadedList<Variable>
Definition at line 320 of file variables.h.
LocationField
using v8::internal::Variable::LocationField = VariableKindField::Next<VariableLocation, 3> [private]
Definition at line 350 of file variables.h.
MaybeAssignedFlagField
using v8::internal::Variable::MaybeAssignedFlagField = InitializationFlagField::Next<MaybeAssignedFlag, 1> [private]
Definition at line 354 of file variables.h.
VariableKindField
using v8::internal::Variable::VariableKindField = VariableModeField::Next<VariableKind, 3> [private]
Definition at line 349 of file variables.h.
VariableModeField
using v8::internal::Variable::VariableModeField = base::BitField16<VariableMode, 0, 4> [private]
Definition at line 348 of file variables.h.
Member Enumeration Documentation
ForceHoleInitializationFlag
enum v8::internal::Variable::ForceHoleInitializationFlag
Enumerator
kHoleInitializationNotForced
kHasHoleCheckUseInDifferentClosureScope
kHasHoleCheckUseInSameClosureScope
kHasHoleCheckUseInUnknownScope
Definition at line 172 of file variables.h.
                                   {
    kHoleInitializationNotForced = 0,
    kHasHoleCheckUseInDifferentClosureScope = 1 << 0,
    kHasHoleCheckUseInSameClosureScope = 1 << 1,
    kHasHoleCheckUseInUnknownScope = kHasHoleCheckUseInDifferentClosureScope |
                                     kHasHoleCheckUseInSameClosureScope
  };
Constructor & Destructor Documentation
Variable() [1/2]
v8::internal::Variable::Variable (Scope * scope, const AstRawString * name, VariableMode mode, VariableKind kind, InitializationFlag initialization_flag, MaybeAssignedFlag maybe_assigned_flag = kNotAssigned, IsStaticFlag is_static_flag = IsStaticFlag::kNotStatic) [inline]
Definition at line 23 of file variables.h.
      : scope_(scope),
        name_(name),
        local_if_not_shadowed_(nullptr),
        next_(nullptr),
        index_(-1),
        initializer_position_(kNoSourcePosition),
        bit_field_(MaybeAssignedFlagField::encode(maybe_assigned_flag) |
                   InitializationFlagField::encode(initialization_flag) |
                   VariableModeField::encode(mode) |
                   IsUsedField::encode(false) |
                   ForceContextAllocationBit::encode(false) |
                   LocationField::encode(VariableLocation::UNALLOCATED) |
                   VariableKindField::encode(kind) |
                   IsStaticFlagField::encode(is_static_flag)),
        hole_check_analysis_bit_field_(HoleCheckBitmapIndexField::encode(
                                           kUncacheableHoleCheckBitmapIndex) |
                                       ForceHoleInitializationFlagField::encode(
                                           kHoleInitializationNotForced)) {
    // Var declared variables never need initialization.
    DCHECK(!(mode == VariableMode::kVar &&
             initialization_flag == kNeedsInitialization));
    DCHECK_IMPLIES(is_static_flag == IsStaticFlag::kStatic,
                   IsImmutableLexicalOrPrivateVariableMode(mode));
  }
References v8::internal::DCHECK(), DCHECK_IMPLIES, initialization_flag(), is_static_flag(), v8::internal::IsImmutableLexicalOrPrivateVariableMode(), v8::internal::kNeedsInitialization, v8::internal::kStatic, v8::internal::kVar, and mode().
Variable() [2/2]
v8::internal::Variable::Variable (Variable * other) [explicit]
Definition at line 16 of file variables.cc.
    : scope_(other->scope_),
      name_(other->name_),
      local_if_not_shadowed_(nullptr),
      next_(nullptr),
      index_(other->index_),
      initializer_position_(other->initializer_position_),
      bit_field_(other->bit_field_) {}
Member Function Documentation
AllocateTo()
void v8::internal::Variable::AllocateTo (VariableLocation location, int index) [inline]
Definition at line 295 of file variables.h.
                                                        {
    DCHECK(IsUnallocated() ||
           (this->location() == location && this->index() == index));
    DCHECK_IMPLIES(location == VariableLocation::MODULE, index != 0);
    bit_field_ = LocationField::update(bit_field_, location);
    DCHECK_EQ(location, this->location());
    index_ = index;
  }
References bit_field_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, index(), index_, IsUnallocated(), location(), and v8::internal::MODULE.
Referenced by v8::internal::Scope::AllocateHeapSlot(), v8::internal::ModuleScope::AllocateModuleVariables(), v8::internal::DeclarationScope::AllocateParameter(), v8::internal::Scope::AllocateStackSlot(), v8::internal::ClassScope::ClassScope(), v8::internal::Scope::LookupInScopeInfo(), v8::internal::ClassScope::LookupPrivateNameInScopeInfo(), and v8::internal::Scope::NonLocal().
AssignHoleCheckBitmapIndex()
void v8::internal::Variable::AssignHoleCheckBitmapIndex (ZoneVector< Variable * > & list, uint8_t next_index) [private]
Definition at line 50 of file variables.cc.
                                                              {
  DCHECK_EQ(next_index, list.size() + 1);
  DCHECK_NE(kUncacheableHoleCheckBitmapIndex, next_index);
  DCHECK_LT(next_index, kHoleCheckBitmapBits);
  hole_check_analysis_bit_field_ = HoleCheckBitmapIndexField::update(
      hole_check_analysis_bit_field_, next_index);
  list.push_back(this);
}
References DCHECK_EQ, DCHECK_LT, DCHECK_NE, hole_check_analysis_bit_field_, kHoleCheckBitmapBits, kUncacheableHoleCheckBitmapIndex, v8::internal::ZoneVector< T >::push_back(), and v8::internal::ZoneVector< T >::size().
Referenced by RememberHoleCheckInBitmap().
binding_needs_init()
bool v8::internal::Variable::binding_needs_init () const [inline]
Definition at line 150 of file variables.h.
                                  {
    DCHECK_IMPLIES(initialization_flag() == kNeedsInitialization,
                   IsLexicalVariableMode(mode()) ||
                       IsPrivateMethodOrAccessorVariableMode(mode()));
    DCHECK_IMPLIES(IsHoleInitializationForced(),
                   initialization_flag() == kNeedsInitialization);
    // Always initialize if hole initialization was forced during
    // scope analysis.
    if (IsHoleInitializationForced()) return true;
    // If initialization was not forced, no need for initialization
    // for stack allocated variables, since UpdateNeedsHoleCheck()
    // in scopes.cc has proven that no VariableProxy refers to
    // this variable in such a way that a runtime hole check
    // would be generated.
    if (IsStackAllocated()) return false;
    // Otherwise, defer to the flag set when this Variable was constructed.
    return initialization_flag() == kNeedsInitialization;
  }
References DCHECK_IMPLIES, initialization_flag(), IsHoleInitializationForced(), v8::internal::IsLexicalVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), IsStackAllocated(), v8::internal::kNeedsInitialization, and mode().
clear_maybe_assigned()
void v8::internal::Variable::clear_maybe_assigned () [inline]
Definition at line 91 of file variables.h.
                              {
    bit_field_ = MaybeAssignedFlagField::update(bit_field_, kNotAssigned);
  }
References bit_field_, and v8::internal::kNotAssigned.
Referenced by v8::internal::ParserBase< Impl >::ParseFormalParameter().
DefaultInitializationFlag()
static InitializationFlag v8::internal::Variable::DefaultInitializationFlag (VariableMode mode) [inline], [static]
Definition at line 311 of file variables.h.
                                                                         {
    DCHECK(IsDeclaredVariableMode(mode));
    return mode == VariableMode::kVar ? kCreatedInitialized
                                      : kNeedsInitialization;
  }
References v8::internal::DCHECK(), v8::internal::IsDeclaredVariableMode(), v8::internal::kCreatedInitialized, v8::internal::kNeedsInitialization, v8::internal::kVar, and mode().
Referenced by v8::internal::VariableDeclarationParsingScope< Types >::Declare(), v8::internal::ParameterDeclarationParsingScope< Types >::Declare(), v8::internal::Parser::DeclareAndBindVariable(), v8::internal::Parser::DeclareBoundVariable(), and v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
force_hole_initialization_flag_field()
ForceHoleInitializationFlag v8::internal::Variable::force_hole_initialization_flag_field () const [inline]
Definition at line 179 of file variables.h.
                                                                           {
    return ForceHoleInitializationFlagField::decode(
        hole_check_analysis_bit_field_);
  }
References hole_check_analysis_bit_field_.
Referenced by HasHoleCheckUseInSameClosureScope(), and IsHoleInitializationForced().
ForceContextAllocation()
void v8::internal::Variable::ForceContextAllocation () [inline]
Definition at line 81 of file variables.h.
                                {
    DCHECK(IsUnallocated() || IsContextSlot() || IsLookupSlot() ||
           location() == VariableLocation::MODULE);
    bit_field_ = ForceContextAllocationBit::update(bit_field_, true);
  }
References bit_field_, v8::internal::DCHECK(), IsContextSlot(), IsLookupSlot(), IsUnallocated(), location(), and v8::internal::MODULE.
Referenced by v8::internal::DeclarationScope::AllocateParameterLocals(), v8::internal::Parser::CreateSyntheticContextVariableProxy(), v8::internal::ClassScope::DeclareBrandVariable(), v8::internal::Scope::DeclareHomeObjectVariable(), v8::internal::Scope::DeclareStaticHomeObjectVariable(), v8::internal::Scope::Lookup(), v8::internal::Scope::LookupWith(), v8::internal::ParserBase< Impl >::ParseClassLiteral(), v8::internal::Scope::ResolvePreparsedVariable(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForVariable(), and v8::internal::ParserBase< Impl >::UseThis().
ForceHoleInitialization()
void v8::internal::Variable::ForceHoleInitialization (ForceHoleInitializationFlag flag) [inline]
Definition at line 197 of file variables.h.
                                                                 {
    DCHECK_EQ(kNeedsInitialization, initialization_flag());
    DCHECK_NE(kHoleInitializationNotForced, flag);
    DCHECK(IsLexicalVariableMode(mode()) ||
           IsPrivateMethodOrAccessorVariableMode(mode()));
    hole_check_analysis_bit_field_ |=
        ForceHoleInitializationFlagField::encode(flag);
  }
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, hole_check_analysis_bit_field_, initialization_flag(), v8::internal::IsLexicalVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), kHoleInitializationNotForced, v8::internal::kNeedsInitialization, and mode().
Referenced by v8::internal::DeclarationScope::DeclareThis(), and v8::internal::anonymous_namespace{scopes.cc}::SetNeedsHoleCheck().
has_forced_context_allocation()
bool v8::internal::Variable::has_forced_context_allocation () const [inline]
Definition at line 78 of file variables.h.
                                             {
    return ForceContextAllocationBit::decode(bit_field_);
  }
References bit_field_.
Referenced by v8::internal::Scope::MustAllocate(), v8::internal::Scope::MustAllocateInContext(), and v8::internal::PreparseDataBuilder::SaveDataForVariable().
has_local_if_not_shadowed()
bool v8::internal::Variable::has_local_if_not_shadowed () const [inline]
Definition at line 268 of file variables.h.
                                         {
    return local_if_not_shadowed_ != nullptr;
  }
References local_if_not_shadowed_.
Referenced by local_if_not_shadowed(), and SetMaybeAssigned().
HasHoleCheckUseInSameClosureScope()
bool v8::internal::Variable::HasHoleCheckUseInSameClosureScope () const [inline]
Definition at line 189 of file variables.h.
                                                 {
    return force_hole_initialization_flag_field() &
           kHasHoleCheckUseInSameClosureScope;
  }
References force_hole_initialization_flag_field(), and kHasHoleCheckUseInSameClosureScope.
HasRememberedHoleCheck()
bool v8::internal::Variable::HasRememberedHoleCheck (HoleCheckBitmap bitmap) const [inline]
Definition at line 240 of file variables.h.
                                                            {
    uint8_t index = HoleCheckBitmapIndex();
    bool result = bitmap & (HoleCheckBitmap{1} << index);
    DCHECK_IMPLIES(index == kUncacheableHoleCheckBitmapIndex, !result);
    return result;
  }
References DCHECK_IMPLIES, HoleCheckBitmapIndex(), index(), kUncacheableHoleCheckBitmapIndex, and v8::base::internal::result.
HoleCheckBitmapIndex()
uint8_t v8::internal::Variable::HoleCheckBitmapIndex () const [inline], [private]
Definition at line 341 of file variables.h.
                                       {
    return HoleCheckBitmapIndexField::decode(hole_check_analysis_bit_field_);
  }
References hole_check_analysis_bit_field_.
Referenced by HasRememberedHoleCheck(), and RememberHoleCheckInBitmap().
index()
int v8::internal::Variable::index () const [inline]
Definition at line 281 of file variables.h.
{ return index_; }
References index_.
Referenced by v8::internal::Scope::AllocateNonParameterLocal(), AllocateTo(), v8::internal::ScopeInfo::Create(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedStoreICSlot(), HasRememberedHoleCheck(), IsExport(), RememberHoleCheckInBitmap(), and v8::internal::ScopeIterator::VisitLocalScope().
initialization_flag()
InitializationFlag v8::internal::Variable::initialization_flag () const [inline]
Definition at line 144 of file variables.h.
                                                 {
    return InitializationFlagField::decode(bit_field_);
  }
References bit_field_.
Referenced by binding_needs_init(), ForceHoleInitialization(), v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck(), and Variable().
initializer_position()
int v8::internal::Variable::initializer_position () [inline]
Definition at line 121 of file variables.h.
{ return initializer_position_; }
References initializer_position_.
Referenced by v8::internal::ParserBase< Impl >::ParseFormalParameter(), and v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck().
is_dynamic()
bool v8::internal::Variable::is_dynamic () const [inline]
Definition at line 138 of file variables.h.
{ return IsDynamicVariableMode(mode()); }
References v8::internal::IsDynamicVariableMode(), and mode().
Referenced by v8::internal::Scope::Lookup(), v8::internal::Scope::LookupSloppyEval(), v8::internal::Scope::LookupWith(), v8::internal::VariableMap::RemoveDynamic(), and v8::internal::Scope::ResolvePreparsedVariable().
is_parameter()
bool v8::internal::Variable::is_parameter () const [inline]
Definition at line 256 of file variables.h.
{ return kind() == PARAMETER_VARIABLE; }
References kind(), and v8::internal::PARAMETER_VARIABLE.
Referenced by v8::internal::DeclarationScope::DeclareParameter(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), MakeParameterNonSimple(), and v8::internal::DeclarationScope::MakeParametersNonSimple().
is_sloppy_block_function()
bool v8::internal::Variable::is_sloppy_block_function () [inline]
Definition at line 257 of file variables.h.
                                  {
    return kind() == SLOPPY_BLOCK_FUNCTION_VARIABLE;
  }
References kind(), and v8::internal::SLOPPY_BLOCK_FUNCTION_VARIABLE.
Referenced by v8::internal::Scope::DeclareVariable(), v8::internal::Scope::DeclareVariableName(), and v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
is_sloppy_function_name()
bool v8::internal::Variable::is_sloppy_function_name () const [inline]
Definition at line 252 of file variables.h.
                                       {
    return kind() == SLOPPY_FUNCTION_NAME_VARIABLE;
  }
References kind(), and v8::internal::SLOPPY_FUNCTION_NAME_VARIABLE.
is_static()
bool v8::internal::Variable::is_static () const [inline]
Definition at line 76 of file variables.h.
{ return is_static_flag() == IsStaticFlag::kStatic; }
References is_static_flag(), and v8::internal::kStatic.
Referenced by v8::internal::ClassScope::ResolvePrivateNamesPartially().
is_static_flag()
IsStaticFlag v8::internal::Variable::is_static_flag () const [inline]
Definition at line 73 of file variables.h.
                                      {
    return IsStaticFlagField::decode(bit_field_);
  }
References bit_field_.
Referenced by is_static(), set_is_static_flag(), and Variable().
is_this()
bool v8::internal::Variable::is_this () const [inline]
Definition at line 251 of file variables.h.
{ return kind() == THIS_VARIABLE; }
References kind(), and v8::internal::THIS_VARIABLE.
Referenced by v8::internal::Scope::MustAllocate(), and v8::internal::VariableProxy::VariableProxy().
is_used()
bool v8::internal::Variable::is_used () [inline]
Definition at line 86 of file variables.h.
{ return IsUsedField::decode(bit_field_); }
References bit_field_.
Referenced by v8::internal::ScopeInfo::Create(), and v8::internal::Scope::MustAllocate().
IsContextSlot()
bool v8::internal::Variable::IsContextSlot () const [inline]
Definition at line 130 of file variables.h.
{ return location() == VariableLocation::CONTEXT; }
References v8::internal::CONTEXT, and location().
Referenced by v8::internal::DeclarationScope::AllocateParameter(), v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalCatchContext(), v8::internal::Scope::ContextLocalCount(), v8::internal::ScopeInfo::Create(), and ForceContextAllocation().
IsExport()
bool v8::internal::Variable::IsExport () const [inline]
Definition at line 289 of file variables.h.
                        {
    DCHECK_EQ(location(), VariableLocation::MODULE);
    DCHECK_NE(index(), 0);
    return index() > 0;
  }
References DCHECK_EQ, DCHECK_NE, index(), location(), and v8::internal::MODULE.
Referenced by v8::internal::ModuleScope::AllocateModuleVariables(), and v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck().
IsGlobalObjectProperty()
bool v8::internal::Variable::IsGlobalObjectProperty () const
Definition at line 25 of file variables.cc.
                                            {
  // Temporaries are never global, they must always be allocated in the
  // activation frame.
  return (IsDynamicVariableMode(mode()) || mode() == VariableMode::kVar) &&
         scope_ != nullptr && scope_->is_script_scope();
}
References v8::internal::Scope::is_script_scope(), v8::internal::IsDynamicVariableMode(), v8::internal::kVar, mode(), and scope_.
Referenced by v8::internal::Scope::LookupSloppyEval(), and v8::internal::Scope::MustAllocate().
IsHoleInitializationForced()
bool v8::internal::Variable::IsHoleInitializationForced () const [inline]
Definition at line 184 of file variables.h.
                                          {
    return force_hole_initialization_flag_field() !=
           kHoleInitializationNotForced;
  }
References force_hole_initialization_flag_field(), and kHoleInitializationNotForced.
Referenced by binding_needs_init().
IsLookupSlot()
bool v8::internal::Variable::IsLookupSlot () const [inline]
Definition at line 131 of file variables.h.
{ return location() == VariableLocation::LOOKUP; }
References location(), and v8::internal::LOOKUP.
Referenced by ForceContextAllocation(), and v8::internal::Call::GetCallType().
IsParameter()
bool v8::internal::Variable::IsParameter () const [inline]
Definition at line 127 of file variables.h.
{ return location() == VariableLocation::PARAMETER; }
References location(), and v8::internal::PARAMETER.
Referenced by v8::internal::DeclarationScope::AllocateParameter(), v8::internal::ScopeInfo::Create(), IsReceiver(), and IsStackAllocated().
IsReceiver()
bool v8::internal::Variable::IsReceiver () const [inline]
Definition at line 283 of file variables.h.
                          {
    DCHECK(IsParameter());
    return index_ == -1;
  }
References v8::internal::DCHECK(), index_, and IsParameter().
IsReplGlobal()
bool v8::internal::Variable::IsReplGlobal () const
Definition at line 32 of file variables.cc.
                                  {
  return scope()->is_repl_mode_scope() &&
         (mode() == VariableMode::kLet || mode() == VariableMode::kConst ||
          mode() == VariableMode::kUsing ||
          mode() == VariableMode::kAwaitUsing);
}
References v8::internal::Scope::is_repl_mode_scope(), v8::internal::kAwaitUsing, v8::internal::kConst, v8::internal::kLet, v8::internal::kUsing, mode(), and scope().
IsStackAllocated()
bool v8::internal::Variable::IsStackAllocated () const [inline]
Definition at line 129 of file variables.h.
{ return IsParameter() || IsStackLocal(); }
References IsParameter(), and IsStackLocal().
Referenced by binding_needs_init().
IsStackLocal()
bool v8::internal::Variable::IsStackLocal () const [inline]
Definition at line 128 of file variables.h.
{ return location() == VariableLocation::LOCAL; }
References v8::internal::LOCAL, and location().
Referenced by v8::internal::ScopeInfo::Create(), v8::internal::interpreter::BytecodeGenerator::IsLocalVariableWithInternalizedStringHint(), and IsStackAllocated().
IsUnallocated()
bool v8::internal::Variable::IsUnallocated () const [inline]
Definition at line 124 of file variables.h.
                             {
    return location() == VariableLocation::UNALLOCATED;
  }
References location(), and v8::internal::UNALLOCATED.
Referenced by v8::internal::Scope::AllocateNonParameterLocal(), v8::internal::DeclarationScope::AllocateParameter(), AllocateTo(), ForceContextAllocation(), v8::internal::Call::GetCallType(), v8::internal::Expression::IsUndefinedLiteral(), and v8::internal::Scope::LookupWith().
kind()
VariableKind v8::internal::Variable::kind () const [inline]
Definition at line 279 of file variables.h.
{ return VariableKindField::decode(bit_field_); }
References bit_field_.
Referenced by is_parameter(), is_sloppy_block_function(), is_sloppy_function_name(), is_this(), and throw_on_const_assignment().
local_if_not_shadowed()
Variable* v8::internal::Variable::local_if_not_shadowed () const [inline]
Definition at line 261 of file variables.h.
                                          {
    DCHECK((mode() == VariableMode::kDynamicLocal ||
            mode() == VariableMode::kDynamic) &&
           has_local_if_not_shadowed());
    return local_if_not_shadowed_;
  }
References v8::internal::DCHECK(), has_local_if_not_shadowed(), v8::internal::kDynamic, v8::internal::kDynamicLocal, local_if_not_shadowed_, and mode().
Referenced by SetMaybeAssigned(), and v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck().
location()
VariableLocation v8::internal::Variable::location () const [inline]
Definition at line 276 of file variables.h.
                                    {
    return LocationField::decode(bit_field_);
  }
References bit_field_.
Referenced by AllocateTo(), v8::internal::ScopeInfo::Create(), ForceContextAllocation(), IsContextSlot(), IsExport(), IsLookupSlot(), IsParameter(), IsStackLocal(), IsUnallocated(), v8::internal::Scope::MustAllocate(), RewriteLocationForRepl(), and v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck().
MakeParameterNonSimple()
void v8::internal::Variable::MakeParameterNonSimple () [inline]
Definition at line 304 of file variables.h.
                                {
    DCHECK(is_parameter());
    bit_field_ = VariableModeField::update(bit_field_, VariableMode::kLet);
    bit_field_ =
        InitializationFlagField::update(bit_field_, kNeedsInitialization);
  }
References bit_field_, v8::internal::DCHECK(), is_parameter(), v8::internal::kLet, and v8::internal::kNeedsInitialization.
Referenced by v8::internal::DeclarationScope::MakeParametersNonSimple().
maybe_assigned()
MaybeAssignedFlag v8::internal::Variable::maybe_assigned () const [inline]
Definition at line 88 of file variables.h.
                                           {
    return MaybeAssignedFlagField::decode(bit_field_);
  }
References bit_field_.
Referenced by v8::internal::PreparseDataBuilder::SaveDataForVariable(), and SetMaybeAssigned().
mode()
VariableMode v8::internal::Variable::mode () const [inline]
Definition at line 66 of file variables.h.
{ return VariableModeField::decode(bit_field_); }
References bit_field_.
Referenced by binding_needs_init(), v8::internal::DeclarationScope::CheckConflictingVarDeclarations(), v8::internal::DeclarationScope::DeclareArguments(), v8::internal::Scope::DeclareVariable(), v8::internal::Scope::DeclareVariableName(), DefaultInitializationFlag(), v8::internal::Scope::FindVariableDeclaredIn(), ForceHoleInitialization(), v8::internal::Property::GetAssignType(), v8::internal::Call::GetCallType(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), is_dynamic(), IsGlobalObjectProperty(), IsReplGlobal(), local_if_not_shadowed(), v8::internal::Scope::LookupInScopeInfo(), v8::internal::Scope::MustAllocateInContext(), v8::internal::Scope::Snapshot::Reparent(), requires_brand_check(), v8::internal::ClassScope::ResolvePrivateNamesPartially(), RewriteLocationForRepl(), set_mode(), SetMaybeAssigned(), v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck(), and Variable().
name()
Handle<String> v8::internal::Variable::name () const [inline]
Definition at line 64 of file variables.h.
{ return name_->string(); }
References name_, and v8::internal::AstRawString::string().
Referenced by v8::internal::ScopeInfo::Create(), and v8::internal::ScopeIterator::VisitLocals().
next()
Variable** v8::internal::Variable::next () [inline], [private]
Definition at line 362 of file variables.h.
{ return &next_; }
References next_.
raw_name()
const AstRawString* v8::internal::Variable::raw_name () const [inline]
Definition at line 65 of file variables.h.
{ return name_; }
References name_.
Referenced by v8::internal::VariableMap::Add(), v8::internal::VariableProxy::BindTo(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::ParserBase< Impl >::CheckConflictingVarDeclarations(), v8::internal::Parser::CreatePrivateNameVariable(), v8::internal::Parser::Declare(), v8::internal::Scope::MustAllocate(), v8::internal::SloppyBlockFunctionStatement::name(), v8::internal::ParserBase< Impl >::ParseTryStatement(), v8::internal::VariableProxy::raw_name(), v8::internal::VariableMap::Remove(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForVariable(), and v8::internal::PreparseDataBuilder::SaveDataForVariable().
RememberHoleCheckInBitmap()
void v8::internal::Variable::RememberHoleCheckInBitmap (HoleCheckBitmap & bitmap, ZoneVector< Variable * > & list) [inline]
Definition at line 225 of file variables.h.
                                                              {
    DCHECK(v8_flags.ignition_elide_redundant_tdz_checks);
    uint8_t index = HoleCheckBitmapIndex();
    if (V8_UNLIKELY(index == kUncacheableHoleCheckBitmapIndex)) {
      index = list.size() + 1;
      // The bitmap is full.
      if (index == kHoleCheckBitmapBits) return;
      AssignHoleCheckBitmapIndex(list, index);
    }
    bitmap |= HoleCheckBitmap{1} << index;
    DCHECK_EQ(
        0, bitmap & (HoleCheckBitmap{1} << kUncacheableHoleCheckBitmapIndex));
  }
References AssignHoleCheckBitmapIndex(), v8::internal::DCHECK(), DCHECK_EQ, HoleCheckBitmapIndex(), index(), kHoleCheckBitmapBits, kUncacheableHoleCheckBitmapIndex, v8::internal::ZoneVector< T >::size(), v8::internal::v8_flags, and V8_UNLIKELY.
requires_brand_check()
bool v8::internal::Variable::requires_brand_check () const [inline]
Definition at line 117 of file variables.h.
                                    {
    return IsPrivateMethodOrAccessorVariableMode(mode());
  }
References v8::internal::IsPrivateMethodOrAccessorVariableMode(), and mode().
ResetHoleCheckBitmapIndex()
void v8::internal::Variable::ResetHoleCheckBitmapIndex () [inline]
Definition at line 220 of file variables.h.
                                   {
    hole_check_analysis_bit_field_ = HoleCheckBitmapIndexField::update(
        hole_check_analysis_bit_field_, kUncacheableHoleCheckBitmapIndex);
  }
References hole_check_analysis_bit_field_, and kUncacheableHoleCheckBitmapIndex.
RewriteLocationForRepl()
void v8::internal::Variable::RewriteLocationForRepl ()
Definition at line 39 of file variables.cc.
                                      {
  DCHECK(scope_->is_repl_mode_scope());
  if (mode() == VariableMode::kLet || mode() == VariableMode::kConst ||
      mode() == VariableMode::kUsing || mode() == VariableMode::kAwaitUsing) {
    DCHECK_EQ(location(), VariableLocation::CONTEXT);
    bit_field_ =
        LocationField::update(bit_field_, VariableLocation::REPL_GLOBAL);
  }
}
References bit_field_, v8::internal::CONTEXT, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Scope::is_repl_mode_scope(), v8::internal::kAwaitUsing, v8::internal::kConst, v8::internal::kLet, v8::internal::kUsing, location(), mode(), v8::internal::REPL_GLOBAL, and scope_.
Referenced by v8::internal::Scope::RewriteReplGlobalVariables().
scope()
Scope* v8::internal::Variable::scope () const [inline]
Definition at line 58 of file variables.h.
{ return scope_; }
References scope_.
Referenced by v8::internal::Scope::AllocateNonParameterLocal(), v8::internal::DeclarationScope::AllocateParameterLocals(), v8::internal::PreParser::DeclareVariableName(), IsReplGlobal(), v8::internal::Scope::Snapshot::Reparent(), v8::internal::Scope::RewriteReplGlobalVariables(), v8::internal::SloppyBlockFunctionStatement::scope(), set_scope(), and v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck().
set_initializer_position()
void v8::internal::Variable::set_initializer_position (int pos) [inline]
Definition at line 122 of file variables.h.
{ initializer_position_ = pos; }
References initializer_position_.
Referenced by v8::internal::Parser::CreateForEachStatementTDZ(), v8::internal::PreParser::DeclareAndBindVariable(), v8::internal::Parser::DeclareAndBindVariable(), v8::internal::ClassScope::DeclareBrandVariable(), v8::internal::Parser::DeclareClass(), v8::internal::DeclarationScope::DeclareParameter(), v8::internal::Parser::DeclarePrivateClassMember(), v8::internal::Parser::DesugarLexicalBindingsInForStatement(), v8::internal::Parser::ParseExportDefault(), v8::internal::ParserBase< Impl >::ParseFormalParameter(), and v8::internal::Parser::RewriteClassLiteral().
set_is_static_flag()
void v8::internal::Variable::set_is_static_flag (IsStaticFlag is_static_flag) [inline]
Definition at line 70 of file variables.h.
                                                       {
    bit_field_ = IsStaticFlagField::update(bit_field_, is_static_flag);
  }
References bit_field_, and is_static_flag().
Referenced by v8::internal::ClassScope::DeclareBrandVariable().
set_is_used()
void v8::internal::Variable::set_is_used () [inline]
Definition at line 87 of file variables.h.
{ bit_field_ = IsUsedField::update(bit_field_, true); }
References bit_field_.
Referenced by v8::internal::DeclarationScope::AllocateParameterLocals(), v8::internal::Scope::AnalyzePartially(), v8::internal::VariableProxy::BindTo(), v8::internal::ClassScope::DeclareBrandVariable(), v8::internal::Parser::DeclareFunction(), v8::internal::Scope::DeclareHomeObjectVariable(), v8::internal::Scope::DeclareLocal(), v8::internal::DeclarationScope::DeclareParameter(), v8::internal::Scope::DeclareStaticHomeObjectVariable(), v8::internal::Scope::DeclareVariable(), v8::internal::Scope::DeclareVariableName(), v8::internal::Scope::LookupWith(), v8::internal::Scope::MustAllocate(), v8::internal::ParserBase< Impl >::ParseClassLiteral(), v8::internal::Scope::ResolvePreparsedVariable(), v8::internal::ClassScope::ResolvePrivateNamesPartially(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForVariable(), and v8::internal::ParserBase< Impl >::UseThis().
set_local_if_not_shadowed()
void v8::internal::Variable::set_local_if_not_shadowed (Variable * local) [inline]
Definition at line 272 of file variables.h.
                                                  {
    local_if_not_shadowed_ = local;
  }
References local_if_not_shadowed_.
Referenced by v8::internal::Scope::LookupSloppyEval(), and v8::internal::Scope::LookupWith().
set_maybe_assigned()
void v8::internal::Variable::set_maybe_assigned () [inline], [private]
Definition at line 337 of file variables.h.
                            {
    bit_field_ = MaybeAssignedFlagField::update(bit_field_, kMaybeAssigned);
  }
References bit_field_, and v8::internal::kMaybeAssigned.
Referenced by SetMaybeAssigned().
set_mode()
void v8::internal::Variable::set_mode (VariableMode mode) [inline]
Definition at line 67 of file variables.h.
                                   {
    bit_field_ = VariableModeField::update(bit_field_, mode);
  }
References bit_field_, and mode().
set_scope()
void v8::internal::Variable::set_scope (Scope * scope) [inline]
Definition at line 62 of file variables.h.
{ scope_ = scope; }
References scope(), and scope_.
Referenced by v8::internal::Scope::Snapshot::Reparent().
SetMaybeAssigned()
void v8::internal::Variable::SetMaybeAssigned () [inline]
Definition at line 94 of file variables.h.
                          {
    if (IsImmutableLexicalVariableMode(mode())) {
      return;
    }
    // Private names are only initialized once by us.
    if (name_->IsPrivateName()) {
      return;
    }
    // If this variable is dynamically shadowing another variable, then that
    // variable could also be assigned (in the non-shadowing case).
    if (has_local_if_not_shadowed()) {
      // Avoid repeatedly marking the same tree of variables by only recursing
      // when this variable's maybe_assigned status actually changes.
      if (!maybe_assigned()) {
        local_if_not_shadowed()->SetMaybeAssigned();
      }
      DCHECK_IMPLIES(
          (!IsImmutableLexicalVariableMode(local_if_not_shadowed()->mode())),
          local_if_not_shadowed()->maybe_assigned());
    }
    set_maybe_assigned();
  }
References DCHECK_IMPLIES, has_local_if_not_shadowed(), v8::internal::IsImmutableLexicalVariableMode(), v8::internal::AstRawString::IsPrivateName(), local_if_not_shadowed(), maybe_assigned(), mode(), name_, set_maybe_assigned(), and SetMaybeAssigned().
Referenced by v8::internal::DeclarationScope::AllocateParameterLocals(), v8::internal::Scope::AnalyzePartially(), v8::internal::VariableProxy::BindTo(), v8::internal::VariableDeclarationParsingScope< Types >::Declare(), v8::internal::Scope::DeclareLocal(), v8::internal::Scope::DeclareVariable(), v8::internal::Scope::DeclareVariableName(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::Scope::LookupWith(), v8::internal::Scope::MustAllocate(), v8::internal::Scope::NewTemporary(), v8::internal::ExpressionScope< Types >::NewVariable(), v8::internal::Scope::ResolvePreparsedVariable(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForVariable(), v8::internal::VariableProxy::set_is_assigned(), and SetMaybeAssigned().
throw_on_const_assignment()
bool v8::internal::Variable::throw_on_const_assignment (LanguageMode language_mode) const [inline]
Definition at line 247 of file variables.h.
                                                                   {
    return kind() != SLOPPY_FUNCTION_NAME_VARIABLE || is_strict(language_mode);
  }
References v8::internal::is_strict(), kind(), and v8::internal::SLOPPY_FUNCTION_NAME_VARIABLE.
Member Data Documentation
bit_field_
uint16_t v8::internal::Variable::bit_field_ [private]
Definition at line 334 of file variables.h.
Referenced by AllocateTo(), clear_maybe_assigned(), ForceContextAllocation(), has_forced_context_allocation(), initialization_flag(), is_static_flag(), is_used(), kind(), location(), MakeParameterNonSimple(), maybe_assigned(), mode(), RewriteLocationForRepl(), set_is_static_flag(), set_is_used(), set_maybe_assigned(), and set_mode().
hole_check_analysis_bit_field_
uint16_t v8::internal::Variable::hole_check_analysis_bit_field_ [private]
Definition at line 335 of file variables.h.
Referenced by AssignHoleCheckBitmapIndex(), force_hole_initialization_flag_field(), ForceHoleInitialization(), HoleCheckBitmapIndex(), and ResetHoleCheckBitmapIndex().
index_
int v8::internal::Variable::index_ [private]
Definition at line 332 of file variables.h.
Referenced by AllocateTo(), index(), and IsReceiver().
initializer_position_
int v8::internal::Variable::initializer_position_ [private]
Definition at line 333 of file variables.h.
Referenced by initializer_position(), and set_initializer_position().
kHoleCheckBitmapBits
constexpr uint8_t v8::internal::Variable::kHoleCheckBitmapBits [static], [constexpr]
Initial value:
=
      std::numeric_limits<HoleCheckBitmap>::digits
Definition at line 217 of file variables.h.
Referenced by AssignHoleCheckBitmapIndex(), and RememberHoleCheckInBitmap().
kUncacheableHoleCheckBitmapIndex
constexpr uint8_t v8::internal::Variable::kUncacheableHoleCheckBitmapIndex = 0 [static], [constexpr]
Definition at line 216 of file variables.h.
Referenced by AssignHoleCheckBitmapIndex(), HasRememberedHoleCheck(), RememberHoleCheckInBitmap(), and ResetHoleCheckBitmapIndex().
List
friend v8::internal::Variable::List [private]
Definition at line 363 of file variables.h.
local_if_not_shadowed_
Variable* v8::internal::Variable::local_if_not_shadowed_ [private]
Definition at line 330 of file variables.h.
Referenced by has_local_if_not_shadowed(), local_if_not_shadowed(), and set_local_if_not_shadowed().
name_
const AstRawString* v8::internal::Variable::name_ [private]
Definition at line 324 of file variables.h.
Referenced by name(), raw_name(), and SetMaybeAssigned().
next_
Variable* v8::internal::Variable::next_ [private]
Definition at line 331 of file variables.h.
Referenced by next().
scope_
Scope* v8::internal::Variable::scope_ [private]
Definition at line 323 of file variables.h.
Referenced by IsGlobalObjectProperty(), RewriteLocationForRepl(), scope(), and set_scope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/variables.h
/mnt/V8SourceCode/src/ast/variables.cc