v8_inspector::V8ConsoleAgentImpl Class Reference
#include <v8-console-agent-impl.h>
Public Member Functions
V8ConsoleAgentImpl (V8InspectorSessionImpl *, protocol::FrontendChannel *, protocol::DictionaryValue *state)
~V8ConsoleAgentImpl () override
V8ConsoleAgentImpl (const V8ConsoleAgentImpl &)=delete
V8ConsoleAgentImpl & operator= (const V8ConsoleAgentImpl &)=delete
Response enable () override
Response disable () override
Response clearMessages () override
void restore ()
void messageAdded (V8ConsoleMessage *)
void reset ()
bool enabled ()
Private Member Functions
void reportAllMessages ()
bool reportMessage (V8ConsoleMessage *, bool generatePreview)
Private Attributes
V8InspectorSessionImpl * m_session
protocol::DictionaryValue * m_state
protocol::Console::Frontend m_frontend
bool m_enabled
Detailed Description
Definition at line 19 of file v8-console-agent-impl.h.
Constructor & Destructor Documentation
V8ConsoleAgentImpl() [1/2]
v8_inspector::V8ConsoleAgentImpl::V8ConsoleAgentImpl (V8InspectorSessionImpl * session, protocol::FrontendChannel * frontendChannel, protocol::DictionaryValue * state)
Definition at line 19 of file v8-console-agent-impl.cc.
    : m_session(session),
      m_state(state),
      m_frontend(frontendChannel),
      m_enabled(false) {}
 V8ConsoleAgentImpl()
v8_inspector::V8ConsoleAgentImpl::~V8ConsoleAgentImpl () [override], [default]
V8ConsoleAgentImpl() [2/2]
v8_inspector::V8ConsoleAgentImpl::V8ConsoleAgentImpl (const V8ConsoleAgentImpl &) [delete]
Member Function Documentation
clearMessages()
Response v8_inspector::V8ConsoleAgentImpl::clearMessages () [override]
Definition at line 44 of file v8-console-agent-impl.cc.
{ return Response::Success(); }
disable()
Response v8_inspector::V8ConsoleAgentImpl::disable () [override]
Definition at line 37 of file v8-console-agent-impl.cc.
                                     {
  if (!m_enabled) return Response::Success();
  m_state->setBoolean(ConsoleAgentState::consoleEnabled, false);
  m_enabled = false;
  return Response::Success();
}
References v8_inspector::ConsoleAgentState::consoleEnabled, m_enabled, and m_state.
enable()
Response v8_inspector::V8ConsoleAgentImpl::enable () [override]
Definition at line 29 of file v8-console-agent-impl.cc.
                                    {
  if (m_enabled) return Response::Success();
  m_state->setBoolean(ConsoleAgentState::consoleEnabled, true);
  m_enabled = true;
  reportAllMessages();
  return Response::Success();
}
References v8_inspector::ConsoleAgentState::consoleEnabled, m_enabled, m_state, and reportAllMessages().
Referenced by restore().
enabled()
bool v8_inspector::V8ConsoleAgentImpl::enabled ()
Definition at line 56 of file v8-console-agent-impl.cc.
{ return m_enabled; }
References m_enabled.
messageAdded()
void v8_inspector::V8ConsoleAgentImpl::messageAdded (V8ConsoleMessage * message)
Definition at line 52 of file v8-console-agent-impl.cc.
                                                               {
  if (m_enabled) reportMessage(message, true);
}
References m_enabled, and reportMessage().
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage().
operator=()
V8ConsoleAgentImpl& v8_inspector::V8ConsoleAgentImpl::operator= (const V8ConsoleAgentImpl &) [delete]
reportAllMessages()
void v8_inspector::V8ConsoleAgentImpl::reportAllMessages () [private]
Definition at line 58 of file v8-console-agent-impl.cc.
                                           {
  V8ConsoleMessageStorage* storage =
      m_session->inspector()->ensureConsoleMessageStorage(
          m_session->contextGroupId());
  for (const auto& message : storage->messages()) {
    if (message->origin() == V8MessageOrigin::kConsole) {
      if (!reportMessage(message.get(), false)) return;
    }
  }
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::ensureConsoleMessageStorage(), v8_inspector::V8InspectorSessionImpl::inspector(), v8_inspector::kConsole, m_session, v8_inspector::V8ConsoleMessageStorage::messages(), and reportMessage().
Referenced by enable().
reportMessage()
bool v8_inspector::V8ConsoleAgentImpl::reportMessage (V8ConsoleMessage * message, bool generatePreview) [private]
Definition at line 69 of file v8-console-agent-impl.cc.
                                                             {
  DCHECK_EQ(V8MessageOrigin::kConsole, message->origin());
  message->reportToFrontend(&m_frontend);
  m_frontend.flush();
  return m_session->inspector()->hasConsoleMessageStorage(
      m_session->contextGroupId());
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), DCHECK_EQ, v8_inspector::V8InspectorImpl::hasConsoleMessageStorage(), v8_inspector::V8InspectorSessionImpl::inspector(), v8_inspector::kConsole, m_frontend, m_session, v8_inspector::V8ConsoleMessage::origin(), and v8_inspector::V8ConsoleMessage::reportToFrontend().
Referenced by messageAdded(), and reportAllMessages().
reset()
void v8_inspector::V8ConsoleAgentImpl::reset ()
restore()
void v8_inspector::V8ConsoleAgentImpl::restore ()
Definition at line 46 of file v8-console-agent-impl.cc.
                                 {
  if (!m_state->booleanProperty(ConsoleAgentState::consoleEnabled, false))
    return;
  enable();
}
References v8_inspector::ConsoleAgentState::consoleEnabled, enable(), and m_state.
Member Data Documentation
m_enabled
bool v8_inspector::V8ConsoleAgentImpl::m_enabled [private]
Definition at line 43 of file v8-console-agent-impl.h.
Referenced by disable(), enable(), enabled(), and messageAdded().
m_frontend
protocol::Console::Frontend v8_inspector::V8ConsoleAgentImpl::m_frontend [private]
Definition at line 42 of file v8-console-agent-impl.h.
Referenced by reportMessage().
m_session
V8InspectorSessionImpl* v8_inspector::V8ConsoleAgentImpl::m_session [private]
Definition at line 40 of file v8-console-agent-impl.h.
Referenced by reportAllMessages(), and reportMessage().
m_state
protocol::DictionaryValue* v8_inspector::V8ConsoleAgentImpl::m_state [private]
Definition at line 41 of file v8-console-agent-impl.h.
Referenced by disable(), enable(), and restore().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-console-agent-impl.h
/mnt/V8SourceCode/src/inspector/v8-console-agent-impl.cc