v8::internal::JSModuleNamespace Class Reference
#include <module.h>
Public Types
enum { kToStringTagFieldIndex
, kInObjectFieldCount
 }
Public Member Functions
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > GetExport (Isolate *isolate, DirectHandle< String > name)
bool HasExport (Isolate *isolate, DirectHandle< String > name)
Static Public Member Functions
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetPropertyAttributes (LookupIterator *it)
static V8_WARN_UNUSED_RESULT Maybe< bool > DefineOwnProperty (Isolate *isolate, DirectHandle< JSModuleNamespace > o, DirectHandle< Object > key, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
Static Public Attributes
static constexpr int kSize
Detailed Description
Definition at line 125 of file module.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kToStringTagFieldIndex
kInObjectFieldCount
Definition at line 151 of file module.h.
       {
    kToStringTagFieldIndex,
    kInObjectFieldCount,
  };
Member Function Documentation
DefineOwnProperty()
Maybe< bool > v8::internal::JSModuleNamespace::DefineOwnProperty (Isolate * isolate, DirectHandle< JSModuleNamespace > o, DirectHandle< Object > key, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 453 of file module.cc.
                                     {
  // 1. If Type(P) is Symbol, return OrdinaryDefineOwnProperty(O, P, Desc).
  if (IsSymbol(*key)) {
    return OrdinaryDefineOwnProperty(isolate, object, key, desc, should_throw);
  }
  // 2. Let current be ? O.[[GetOwnProperty]](P).
  PropertyKey lookup_key(isolate, key);
  LookupIterator it(isolate, object, lookup_key, LookupIterator::OWN);
  PropertyDescriptor current;
  Maybe<bool> has_own = GetOwnPropertyDescriptor(&it, &current);
  MAYBE_RETURN(has_own, Nothing<bool>());
  // 3. If current is undefined, return false.
  // 4. If Desc.[[Configurable]] is present and has value true, return false.
  // 5. If Desc.[[Enumerable]] is present and has value false, return false.
  // 6. If ! IsAccessorDescriptor(Desc) is true, return false.
  // 7. If Desc.[[Writable]] is present and has value false, return false.
  // 8. If Desc.[[Value]] is present, return
  // SameValue(Desc.[[Value]], current.[[Value]]).
  if (!has_own.FromJust() ||
      (desc->has_configurable() && desc->configurable()) ||
      (desc->has_enumerable() && !desc->enumerable()) ||
      PropertyDescriptor::IsAccessorDescriptor(desc) ||
      (desc->has_writable() && !desc->writable()) ||
      (desc->has_value() &&
       !Object::SameValue(*desc->value(), *current.value()))) {
    RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                   NewTypeError(MessageTemplate::kRedefineDisallowed, key));
  }
  return Just(true);
}
References v8::internal::PropertyDescriptor::configurable(), v8::internal::PropertyDescriptor::enumerable(), v8::Maybe< T >::FromJust(), v8::internal::GetShouldThrow(), v8::internal::PropertyDescriptor::has_configurable(), v8::internal::PropertyDescriptor::has_enumerable(), v8::internal::PropertyDescriptor::has_value(), v8::internal::PropertyDescriptor::has_writable(), v8::internal::PropertyDescriptor::IsAccessorDescriptor(), v8::Just(), v8::internal::key, MAYBE_RETURN, v8::internal::LookupIterator::OWN, RETURN_FAILURE, v8::internal::Object::SameValue(), v8::internal::PropertyDescriptor::value(), and v8::internal::PropertyDescriptor::writable().
Referenced by v8::internal::JSReceiver::DefineOwnProperty().
GetExport()
MaybeDirectHandle< Object > v8::internal::JSModuleNamespace::GetExport (Isolate * isolate, DirectHandle< String > name)
Definition at line 405 of file module.cc.
                                                 {
  DirectHandle<Object> object(module()->exports()->Lookup(name), isolate);
  if (IsTheHole(*object, isolate)) {
    return isolate->factory()->undefined_value();
  }
  DirectHandle<Object> value(Cast<Cell>(*object)->value(), isolate);
  if (IsTheHole(*value, isolate)) {
    // According to https://tc39.es/ecma262/#sec-InnerModuleLinking
    // step 10 and
    // https://tc39.es/ecma262/#sec-source-text-module-record-initialize-environment
    // step 8-25, variables must be declared in Link. And according to
    // https://tc39.es/ecma262/#sec-module-namespace-exotic-objects-get-p-receiver,
    // here accessing uninitialized variable error should be thrown.
    THROW_NEW_ERROR(isolate,
                    NewReferenceError(
                        MessageTemplate::kAccessedUninitializedVariable, name));
  }
  return value;
}
References v8::internal::Isolate::factory(), v8::internal::name, THROW_NEW_ERROR, and v8::internal::value.
GetPropertyAttributes()
Maybe< PropertyAttributes > v8::internal::JSModuleNamespace::GetPropertyAttributes (LookupIterator * it) [static]
Definition at line 428 of file module.cc.
                        {
  DirectHandle<JSModuleNamespace> object = it->GetHolder<JSModuleNamespace>();
  DirectHandle<String> name = Cast<String>(it->GetName());
  DCHECK_EQ(it->state(), LookupIterator::ACCESSOR);
  Isolate* isolate = it->isolate();
  DirectHandle<Object> lookup(object->module()->exports()->Lookup(name),
                              isolate);
  if (IsTheHole(*lookup, isolate)) return Just(ABSENT);
  DirectHandle<Object> value(Cast<Cell>(lookup)->value(), isolate);
  if (IsTheHole(*value, isolate)) {
    isolate->Throw(*isolate->factory()->NewReferenceError(
        MessageTemplate::kNotDefined, name));
    return Nothing<PropertyAttributes>();
  }
  return Just(it->property_attributes());
}
References v8::internal::ABSENT, v8::internal::LookupIterator::ACCESSOR, DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::name, v8::internal::LookupIterator::property_attributes(), v8::internal::LookupIterator::state(), v8::internal::Isolate::Throw(), and v8::internal::value.
Referenced by v8::internal::JSReceiver::GetPropertyAttributes(), and v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty().
HasExport()
bool v8::internal::JSModuleNamespace::HasExport (Isolate * isolate, DirectHandle< String > name)
Definition at line 400 of file module.cc.
                                                                             {
  DirectHandle<Object> object(module()->exports()->Lookup(name), isolate);
  return !IsTheHole(*object, isolate);
}
References v8::internal::name.
Member Data Documentation
kSize
constexpr int v8::internal::JSModuleNamespace::kSize [static], [constexpr]
Initial value:
=
      kHeaderSize + (kTaggedSize * kInObjectFieldCount)
Definition at line 158 of file module.h.
Referenced by v8::internal::Genesis::InitializeGlobal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/module.h
/mnt/V8SourceCode/src/objects/module.cc