v8::internal::compiler::SimplifiedLowering Class Reference
#include <simplified-lowering.h>
Classes
class NodeProperties
Public Member Functions
SimplifiedLowering (JSGraph *jsgraph, JSHeapBroker *broker, Zone *zone, SourcePositionTable *source_position, NodeOriginTable *node_origins, TickCounter *tick_counter, Linkage *linkage, OptimizedCompilationInfo *info, ObserveNodeManager *observe_node_manager=nullptr)
~SimplifiedLowering ()=default
void LowerAllNodes ()
void DoMax (Node *node, Operator const *op, MachineRepresentation rep)
void DoMin (Node *node, Operator const *op, MachineRepresentation rep)
void DoJSToNumberOrNumericTruncatesToFloat64 (Node *node, RepresentationSelector *selector)
void DoJSToNumberOrNumericTruncatesToWord32 (Node *node, RepresentationSelector *selector)
void DoIntegral32ToBit (Node *node)
void DoOrderedNumberToBit (Node *node)
void DoNumberToBit (Node *node)
void DoIntegerToUint8Clamped (Node *node)
void DoNumberToUint8Clamped (Node *node)
void DoSigned32ToUint8Clamped (Node *node)
void DoUnsigned32ToUint8Clamped (Node *node)
Private Member Functions
void ChangeOp (Node *node, const Operator *new_op)
Node * Float64Round (Node *const node)
Node * Float64Sign (Node *const node)
Node * Int32Abs (Node *const node)
Node * Int32Div (Node *const node)
Node * Int32Mod (Node *const node)
Node * Int32Sign (Node *const node)
Node * Uint32Div (Node *const node)
Node * Uint32Mod (Node *const node)
Node * ToNumberCode ()
Node * ToNumberConvertBigIntCode ()
Node * ToNumericCode ()
Node * Ieee754Fp64ToFp16RawBitsCode ()
Operator const * ToNumberOperator ()
Operator const * ToNumberConvertBigIntOperator ()
Operator const * ToNumericOperator ()
Operator const * Ieee754Fp64ToFp16RawBitsOperator ()
Isolate * isolate ()
Zone * zone ()
JSGraph * jsgraph ()
TFGraph * graph ()
CommonOperatorBuilder * common ()
MachineOperatorBuilder * machine ()
SimplifiedOperatorBuilder * simplified ()
Linkage * linkage ()
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker * broker_
Zone *const zone_
TypeCache const * type_cache_
SetOncePointer< Node > to_number_code_
SetOncePointer< Node > to_number_convert_big_int_code_
SetOncePointer< Node > to_numeric_code_
SetOncePointer< Operator const > to_number_operator_
SetOncePointer< Operator const > to_number_convert_big_int_operator_
SetOncePointer< Operator const > to_numeric_operator_
SourcePositionTable * source_positions_
NodeOriginTable * node_origins_
TickCounter *const tick_counter_
Linkage *const linkage_
OptimizedCompilationInfo * info_
ObserveNodeManager *const observe_node_manager_
Friends
class RepresentationSelector
Detailed Description
Definition at line 29 of file simplified-lowering.h.
Constructor & Destructor Documentation
SimplifiedLowering()
v8::internal::compiler::SimplifiedLowering::SimplifiedLowering (JSGraph * jsgraph, JSHeapBroker * broker, Zone * zone, SourcePositionTable * source_position, NodeOriginTable * node_origins, TickCounter * tick_counter, Linkage * linkage, OptimizedCompilationInfo * info, ObserveNodeManager * observe_node_manager = nullptr)
Definition at line 5277 of file simplified-lowering.cc.
    : jsgraph_(jsgraph),
      broker_(broker),
      zone_(zone),
      type_cache_(TypeCache::Get()),
      source_positions_(source_positions),
      node_origins_(node_origins),
      tick_counter_(tick_counter),
      linkage_(linkage),
      info_(info),
      observe_node_manager_(observe_node_manager) {}
 SimplifiedLowering()
v8::internal::compiler::SimplifiedLowering::~SimplifiedLowering () [default]
Member Function Documentation
ChangeOp()
void v8::internal::compiler::SimplifiedLowering::ChangeOp (Node * node, const Operator * new_op) [private]
Definition at line 6011 of file simplified-lowering.cc.
                                                                    {
  compiler::NodeProperties::ChangeOp(node, new_op);
  if (V8_UNLIKELY(observe_node_manager_ != nullptr))
    observe_node_manager_->OnNodeChanged(kSimplifiedLoweringReducerName, node,
                                         node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::kSimplifiedLoweringReducerName, observe_node_manager_, v8::internal::compiler::ObserveNodeManager::OnNodeChanged(), and V8_UNLIKELY.
Referenced by DoIntegerToUint8Clamped(), DoIntegral32ToBit(), DoMax(), DoMin(), DoNumberToBit(), DoNumberToUint8Clamped(), DoOrderedNumberToBit(), DoSigned32ToUint8Clamped(), and DoUnsigned32ToUint8Clamped().
common()
CommonOperatorBuilder* v8::internal::compiler::SimplifiedLowering::common () [inline], [private]
Definition at line 115 of file simplified-lowering.h.
{ return jsgraph()->common(); }
References v8::internal::compiler::MachineGraph::common().
Referenced by DoIntegerToUint8Clamped(), DoJSToNumberOrNumericTruncatesToFloat64(), DoJSToNumberOrNumericTruncatesToWord32(), DoMax(), DoMin(), DoNumberToUint8Clamped(), DoSigned32ToUint8Clamped(), DoUnsigned32ToUint8Clamped(), Float64Round(), Float64Sign(), Int32Div(), Int32Mod(), Int32Sign(), ToNumberConvertBigIntOperator(), ToNumberOperator(), ToNumericOperator(), Uint32Div(), Uint32Mod(), v8::internal::compiler::RepresentationSelector::VisitPhi(), and v8::internal::compiler::RepresentationSelector::VisitSelect().
DoIntegerToUint8Clamped()
void v8::internal::compiler::SimplifiedLowering::DoIntegerToUint8Clamped (Node * node)
Definition at line 5884 of file simplified-lowering.cc.
                                                           {
  Node* const input = node->InputAt(0);
  Node* const min = jsgraph()->Float64Constant(0.0);
  Node* const max = jsgraph()->Float64Constant(255.0);
  node->ReplaceInput(
      0, graph()->NewNode(machine()->Float64LessThan(), min, input));
  node->AppendInput(
      graph()->zone(),
      graph()->NewNode(
          common()->Select(MachineRepresentation::kFloat64),
          graph()->NewNode(machine()->Float64LessThan(), input, max), input,
          max));
  node->AppendInput(graph()->zone(), min);
  ChangeOp(node, common()->Select(MachineRepresentation::kFloat64));
}
References v8::internal::compiler::Node::AppendInput(), ChangeOp(), common(), v8::internal::compiler::MachineGraph::Float64Constant(), graph(), v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::kFloat64, machine(), v8::internal::compiler::Node::ReplaceInput(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoIntegral32ToBit()
void v8::internal::compiler::SimplifiedLowering::DoIntegral32ToBit (Node * node)
Definition at line 5856 of file simplified-lowering.cc.
                                                     {
  Node* const input = node->InputAt(0);
  Node* const zero = jsgraph()->Int32Constant(0);
  Operator const* const op = machine()->Word32Equal();
  node->ReplaceInput(0, graph()->NewNode(op, input, zero));
  node->AppendInput(graph()->zone(), zero);
  ChangeOp(node, op);
}
References v8::internal::compiler::Node::AppendInput(), ChangeOp(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::MachineGraph::Int32Constant(), jsgraph(), machine(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::MachineOperatorBuilder::Word32Equal(), v8::internal::zero, and zone().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoJSToNumberOrNumericTruncatesToFloat64()
void v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64 (Node * node, RepresentationSelector * selector)
Definition at line 5305 of file simplified-lowering.cc.
                                                  {
  DCHECK(node->opcode() == IrOpcode::kJSToNumber ||
         node->opcode() == IrOpcode::kJSToNumberConvertBigInt ||
         node->opcode() == IrOpcode::kJSToNumeric);
  Node* value = node->InputAt(0);
  Node* context = node->InputAt(1);
  Node* frame_state = node->InputAt(2);
  Node* effect = node->InputAt(3);
  Node* control = node->InputAt(4);
  Node* check0 = graph()->NewNode(simplified()->ObjectIsSmi(), value);
  Node* branch0 = graph()->NewNode(
      common()->Branch(BranchHint::kTrue, BranchSemantics::kMachine), check0,
      control);
  Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
  Node* etrue0 = effect;
  Node* vtrue0;
  {
    vtrue0 = graph()->NewNode(simplified()->ChangeTaggedSignedToInt32(), value);
    vtrue0 = graph()->NewNode(machine()->ChangeInt32ToFloat64(), vtrue0);
  }
  Node* if_false0 = graph()->NewNode(common()->IfFalse(), branch0);
  Node* efalse0 = effect;
  Node* vfalse0;
  {
    Operator const* op =
        node->opcode() == IrOpcode::kJSToNumber
            ? (node->opcode() == IrOpcode::kJSToNumberConvertBigInt
                   ? ToNumberConvertBigIntOperator()
                   : ToNumberOperator())
            : ToNumericOperator();
    Node* code = node->opcode() == IrOpcode::kJSToNumber
                     ? ToNumberCode()
                     : (node->opcode() == IrOpcode::kJSToNumberConvertBigInt
                            ? ToNumberConvertBigIntCode()
                            : ToNumericCode());
    vfalse0 = efalse0 = if_false0 = graph()->NewNode(
        op, code, value, context, frame_state, efalse0, if_false0);
    // Update potential {IfException} uses of {node} to point to the above
    // stub call node instead.
    Node* on_exception = nullptr;
    if (NodeProperties::IsExceptionalCall(node, &on_exception)) {
      NodeProperties::ReplaceControlInput(on_exception, vfalse0);
      NodeProperties::ReplaceEffectInput(on_exception, efalse0);
      if_false0 = graph()->NewNode(common()->IfSuccess(), vfalse0);
    }
    Node* check1 = graph()->NewNode(simplified()->ObjectIsSmi(), vfalse0);
    Node* branch1 = graph()->NewNode(
        common()->Branch(BranchHint::kNone, BranchSemantics::kMachine), check1,
        if_false0);
    Node* if_true1 = graph()->NewNode(common()->IfTrue(), branch1);
    Node* etrue1 = efalse0;
    Node* vtrue1;
    {
      vtrue1 =
          graph()->NewNode(simplified()->ChangeTaggedSignedToInt32(), vfalse0);
      vtrue1 = graph()->NewNode(machine()->ChangeInt32ToFloat64(), vtrue1);
    }
    Node* if_false1 = graph()->NewNode(common()->IfFalse(), branch1);
    Node* efalse1 = efalse0;
    Node* vfalse1;
    {
      vfalse1 = efalse1 = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForHeapNumberValue()), efalse0,
          efalse1, if_false1);
    }
    if_false0 = graph()->NewNode(common()->Merge(2), if_true1, if_false1);
    efalse0 =
        graph()->NewNode(common()->EffectPhi(2), etrue1, efalse1, if_false0);
    vfalse0 =
        graph()->NewNode(common()->Phi(MachineRepresentation::kFloat64, 2),
                         vtrue1, vfalse1, if_false0);
  }
  control = graph()->NewNode(common()->Merge(2), if_true0, if_false0);
  effect = graph()->NewNode(common()->EffectPhi(2), etrue0, efalse0, control);
  value = graph()->NewNode(common()->Phi(MachineRepresentation::kFloat64, 2),
                           vtrue0, vfalse0, control);
  // Replace effect and control uses appropriately.
  for (Edge edge : node->use_edges()) {
    if (NodeProperties::IsControlEdge(edge)) {
      if (edge.from()->opcode() == IrOpcode::kIfSuccess) {
        edge.from()->ReplaceUses(control);
        edge.from()->Kill();
      } else {
        DCHECK_NE(IrOpcode::kIfException, edge.from()->opcode());
        edge.UpdateTo(control);
      }
    } else if (NodeProperties::IsEffectEdge(edge)) {
      edge.UpdateTo(effect);
    }
  }
  selector->DeferReplacement(node, value);
}
References code, common(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::RepresentationSelector::DeferReplacement(), v8::internal::compiler::AccessBuilder::ForHeapNumberValue(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), v8::internal::kFloat64, v8::internal::compiler::kMachine, v8::internal::kNone, v8::internal::kTrue, machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceUses(), simplified(), ToNumberCode(), ToNumberConvertBigIntCode(), ToNumberConvertBigIntOperator(), ToNumberOperator(), ToNumericCode(), ToNumericOperator(), v8::internal::compiler::Node::use_edges(), and v8::internal::value.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoJSToNumberOrNumericTruncatesToWord32()
void v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32 (Node * node, RepresentationSelector * selector)
Definition at line 5410 of file simplified-lowering.cc.
                                                  {
  DCHECK(node->opcode() == IrOpcode::kJSToNumber ||
         node->opcode() == IrOpcode::kJSToNumberConvertBigInt ||
         node->opcode() == IrOpcode::kJSToNumeric);
  Node* value = node->InputAt(0);
  Node* context = node->InputAt(1);
  Node* frame_state = node->InputAt(2);
  Node* effect = node->InputAt(3);
  Node* control = node->InputAt(4);
  Node* check0 = graph()->NewNode(simplified()->ObjectIsSmi(), value);
  Node* branch0 = graph()->NewNode(
      common()->Branch(BranchHint::kTrue, BranchSemantics::kMachine), check0,
      control);
  Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
  Node* etrue0 = effect;
  Node* vtrue0 =
      graph()->NewNode(simplified()->ChangeTaggedSignedToInt32(), value);
  Node* if_false0 = graph()->NewNode(common()->IfFalse(), branch0);
  Node* efalse0 = effect;
  Node* vfalse0;
  {
    Operator const* op =
        node->opcode() == IrOpcode::kJSToNumber
            ? (node->opcode() == IrOpcode::kJSToNumberConvertBigInt
                   ? ToNumberConvertBigIntOperator()
                   : ToNumberOperator())
            : ToNumericOperator();
    Node* code = node->opcode() == IrOpcode::kJSToNumber
                     ? ToNumberCode()
                     : (node->opcode() == IrOpcode::kJSToNumberConvertBigInt
                            ? ToNumberConvertBigIntCode()
                            : ToNumericCode());
    vfalse0 = efalse0 = if_false0 = graph()->NewNode(
        op, code, value, context, frame_state, efalse0, if_false0);
    // Update potential {IfException} uses of {node} to point to the above
    // stub call node instead.
    Node* on_exception = nullptr;
    if (NodeProperties::IsExceptionalCall(node, &on_exception)) {
      NodeProperties::ReplaceControlInput(on_exception, vfalse0);
      NodeProperties::ReplaceEffectInput(on_exception, efalse0);
      if_false0 = graph()->NewNode(common()->IfSuccess(), vfalse0);
    }
    Node* check1 = graph()->NewNode(simplified()->ObjectIsSmi(), vfalse0);
    Node* branch1 = graph()->NewNode(
        common()->Branch(BranchHint::kNone, BranchSemantics::kMachine), check1,
        if_false0);
    Node* if_true1 = graph()->NewNode(common()->IfTrue(), branch1);
    Node* etrue1 = efalse0;
    Node* vtrue1 =
        graph()->NewNode(simplified()->ChangeTaggedSignedToInt32(), vfalse0);
    Node* if_false1 = graph()->NewNode(common()->IfFalse(), branch1);
    Node* efalse1 = efalse0;
    Node* vfalse1;
    {
      vfalse1 = efalse1 = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForHeapNumberValue()), efalse0,
          efalse1, if_false1);
      vfalse1 = graph()->NewNode(machine()->TruncateFloat64ToWord32(), vfalse1);
    }
    if_false0 = graph()->NewNode(common()->Merge(2), if_true1, if_false1);
    efalse0 =
        graph()->NewNode(common()->EffectPhi(2), etrue1, efalse1, if_false0);
    vfalse0 = graph()->NewNode(common()->Phi(MachineRepresentation::kWord32, 2),
                               vtrue1, vfalse1, if_false0);
  }
  control = graph()->NewNode(common()->Merge(2), if_true0, if_false0);
  effect = graph()->NewNode(common()->EffectPhi(2), etrue0, efalse0, control);
  value = graph()->NewNode(common()->Phi(MachineRepresentation::kWord32, 2),
                           vtrue0, vfalse0, control);
  // Replace effect and control uses appropriately.
  for (Edge edge : node->use_edges()) {
    if (NodeProperties::IsControlEdge(edge)) {
      if (edge.from()->opcode() == IrOpcode::kIfSuccess) {
        edge.from()->ReplaceUses(control);
        edge.from()->Kill();
      } else {
        DCHECK_NE(IrOpcode::kIfException, edge.from()->opcode());
        edge.UpdateTo(control);
      }
    } else if (NodeProperties::IsEffectEdge(edge)) {
      edge.UpdateTo(effect);
    }
  }
  selector->DeferReplacement(node, value);
}
References code, common(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::RepresentationSelector::DeferReplacement(), v8::internal::compiler::AccessBuilder::ForHeapNumberValue(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), v8::internal::compiler::kMachine, v8::internal::kNone, v8::internal::kTrue, v8::internal::kWord32, machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceUses(), simplified(), ToNumberCode(), ToNumberConvertBigIntCode(), ToNumberConvertBigIntOperator(), ToNumberOperator(), ToNumericCode(), ToNumericOperator(), v8::internal::compiler::Node::use_edges(), and v8::internal::value.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoMax()
void v8::internal::compiler::SimplifiedLowering::DoMax (Node * node, Operator const * op, MachineRepresentation rep)
Definition at line 5834 of file simplified-lowering.cc.
                                                          {
  Node* const lhs = node->InputAt(0);
  Node* const rhs = node->InputAt(1);
  node->ReplaceInput(0, graph()->NewNode(op, lhs, rhs));
  DCHECK_EQ(rhs, node->InputAt(1));
  node->AppendInput(graph()->zone(), lhs);
  ChangeOp(node, common()->Select(rep));
}
References v8::internal::compiler::Node::AppendInput(), ChangeOp(), common(), DCHECK_EQ, graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::ReplaceInput(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoMin()
void v8::internal::compiler::SimplifiedLowering::DoMin (Node * node, Operator const * op, MachineRepresentation rep)
Definition at line 5845 of file simplified-lowering.cc.
                                                          {
  Node* const lhs = node->InputAt(0);
  Node* const rhs = node->InputAt(1);
  node->InsertInput(graph()->zone(), 0, graph()->NewNode(op, lhs, rhs));
  DCHECK_EQ(lhs, node->InputAt(1));
  DCHECK_EQ(rhs, node->InputAt(2));
  ChangeOp(node, common()->Select(rep));
}
References ChangeOp(), common(), DCHECK_EQ, graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InsertInput(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoNumberToBit()
void v8::internal::compiler::SimplifiedLowering::DoNumberToBit (Node * node)
Definition at line 5875 of file simplified-lowering.cc.
                                                 {
  Node* const input = node->InputAt(0);
  node->ReplaceInput(0, jsgraph()->Float64Constant(0.0));
  node->AppendInput(graph()->zone(),
                    graph()->NewNode(machine()->Float64Abs(), input));
  ChangeOp(node, machine()->Float64LessThan());
}
References v8::internal::compiler::Node::AppendInput(), ChangeOp(), graph(), v8::internal::compiler::Node::InputAt(), jsgraph(), machine(), v8::internal::compiler::Node::ReplaceInput(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoNumberToUint8Clamped()
void v8::internal::compiler::SimplifiedLowering::DoNumberToUint8Clamped (Node * node)
Definition at line 5901 of file simplified-lowering.cc.
                                                          {
  Node* const input = node->InputAt(0);
  Node* const min = jsgraph()->Float64Constant(0.0);
  Node* const max = jsgraph()->Float64Constant(255.0);
  node->ReplaceInput(
      0, graph()->NewNode(
             common()->Select(MachineRepresentation::kFloat64),
             graph()->NewNode(machine()->Float64LessThan(), min, input),
             graph()->NewNode(
                 common()->Select(MachineRepresentation::kFloat64),
                 graph()->NewNode(machine()->Float64LessThan(), input, max),
                 input, max),
             min));
  ChangeOp(node, machine()->Float64RoundTiesEven().placeholder());
}
References ChangeOp(), common(), v8::internal::compiler::MachineGraph::Float64Constant(), graph(), v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::kFloat64, machine(), and v8::internal::compiler::Node::ReplaceInput().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoOrderedNumberToBit()
void v8::internal::compiler::SimplifiedLowering::DoOrderedNumberToBit (Node * node)
Definition at line 5866 of file simplified-lowering.cc.
                                                        {
  Node* const input = node->InputAt(0);
  node->ReplaceInput(0, graph()->NewNode(machine()->Float64Equal(), input,
                                         jsgraph()->Float64Constant(0.0)));
  node->AppendInput(graph()->zone(), jsgraph()->Int32Constant(0));
  ChangeOp(node, machine()->Word32Equal());
}
References v8::internal::compiler::Node::AppendInput(), ChangeOp(), graph(), v8::internal::compiler::Node::InputAt(), jsgraph(), machine(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoSigned32ToUint8Clamped()
void v8::internal::compiler::SimplifiedLowering::DoSigned32ToUint8Clamped (Node * node)
Definition at line 5918 of file simplified-lowering.cc.
                                                            {
  Node* const input = node->InputAt(0);
  Node* const min = jsgraph()->Int32Constant(0);
  Node* const max = jsgraph()->Int32Constant(255);
  node->ReplaceInput(
      0, graph()->NewNode(machine()->Int32LessThanOrEqual(), input, max));
  node->AppendInput(
      graph()->zone(),
      graph()->NewNode(common()->Select(MachineRepresentation::kWord32),
                       graph()->NewNode(machine()->Int32LessThan(), input, min),
                       min, input));
  node->AppendInput(graph()->zone(), max);
  ChangeOp(node, common()->Select(MachineRepresentation::kWord32));
}
References v8::internal::compiler::Node::AppendInput(), ChangeOp(), common(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::MachineGraph::Int32Constant(), jsgraph(), v8::internal::kWord32, machine(), v8::internal::compiler::Node::ReplaceInput(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
DoUnsigned32ToUint8Clamped()
void v8::internal::compiler::SimplifiedLowering::DoUnsigned32ToUint8Clamped (Node * node)
Definition at line 5934 of file simplified-lowering.cc.
                                                              {
  Node* const input = node->InputAt(0);
  Node* const max = jsgraph()->Uint32Constant(255u);
  node->ReplaceInput(
      0, graph()->NewNode(machine()->Uint32LessThanOrEqual(), input, max));
  node->AppendInput(graph()->zone(), input);
  node->AppendInput(graph()->zone(), max);
  ChangeOp(node, common()->Select(MachineRepresentation::kWord32));
}
References v8::internal::compiler::Node::AppendInput(), ChangeOp(), common(), graph(), v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::kWord32, machine(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::MachineGraph::Uint32Constant(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Float64Round()
Node * v8::internal::compiler::SimplifiedLowering::Float64Round (Node *const node) [private]
Definition at line 5508 of file simplified-lowering.cc.
                                                       {
  Node* const one = jsgraph()->Float64Constant(1.0);
  Node* const one_half = jsgraph()->Float64Constant(0.5);
  Node* const input = node->InputAt(0);
  // Round up towards Infinity, and adjust if the difference exceeds 0.5.
  Node* result = graph()->NewNode(machine()->Float64RoundUp().placeholder(),
                                  node->InputAt(0));
  return graph()->NewNode(
      common()->Select(MachineRepresentation::kFloat64),
      graph()->NewNode(
          machine()->Float64LessThanOrEqual(),
          graph()->NewNode(machine()->Float64Sub(), result, one_half), input),
      result, graph()->NewNode(machine()->Float64Sub(), result, one));
}
References common(), v8::internal::compiler::MachineGraph::Float64Constant(), graph(), v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::kFloat64, machine(), v8::internal::compiler::TFGraph::NewNode(), one, and v8::base::internal::result.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Float64Sign()
Node * v8::internal::compiler::SimplifiedLowering::Float64Sign (Node *const node) [private]
Definition at line 5524 of file simplified-lowering.cc.
                                                      {
  Node* const minus_one = jsgraph()->Float64Constant(-1.0);
  Node* const zero = jsgraph()->Float64Constant(0.0);
  Node* const one = jsgraph()->Float64Constant(1.0);
  Node* const input = node->InputAt(0);
  return graph()->NewNode(
      common()->Select(MachineRepresentation::kFloat64),
      graph()->NewNode(machine()->Float64LessThan(), input, zero), minus_one,
      graph()->NewNode(
          common()->Select(MachineRepresentation::kFloat64),
          graph()->NewNode(machine()->Float64LessThan(), zero, input), one,
          input));
}
References common(), v8::internal::compiler::MachineGraph::Float64Constant(), graph(), v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::kFloat64, machine(), v8::internal::compiler::TFGraph::NewNode(), one, and v8::internal::zero.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
graph()
TFGraph* v8::internal::compiler::SimplifiedLowering::graph () [inline], [private]
Definition at line 114 of file simplified-lowering.h.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph().
Referenced by DoIntegerToUint8Clamped(), DoIntegral32ToBit(), DoJSToNumberOrNumericTruncatesToFloat64(), DoJSToNumberOrNumericTruncatesToWord32(), DoMax(), DoMin(), DoNumberToBit(), DoNumberToUint8Clamped(), DoOrderedNumberToBit(), DoSigned32ToUint8Clamped(), DoUnsigned32ToUint8Clamped(), Float64Round(), Float64Sign(), Int32Abs(), Int32Div(), Int32Mod(), Int32Sign(), LowerAllNodes(), ToNumberConvertBigIntOperator(), ToNumberOperator(), ToNumericOperator(), Uint32Div(), and Uint32Mod().
Ieee754Fp64ToFp16RawBitsCode()
Node* v8::internal::compiler::SimplifiedLowering::Ieee754Fp64ToFp16RawBitsCode () [private]
Ieee754Fp64ToFp16RawBitsOperator()
Operator const* v8::internal::compiler::SimplifiedLowering::Ieee754Fp64ToFp16RawBitsOperator () [private]
Int32Abs()
Node * v8::internal::compiler::SimplifiedLowering::Int32Abs (Node *const node) [private]
Definition at line 5540 of file simplified-lowering.cc.
                                                   {
  Node* const input = node->InputAt(0);
  // Generate case for absolute integer value.
  //
  // let sign = input >> 31 in
  // (input ^ sign) - sign
  Node* sign = graph()->NewNode(machine()->Word32Sar(), input,
                                jsgraph()->Int32Constant(31));
  return graph()->NewNode(machine()->Int32Sub(),
                          graph()->NewNode(machine()->Word32Xor(), input, sign),
                          sign);
}
References graph(), v8::internal::compiler::Node::InputAt(), jsgraph(), machine(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::sign.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Int32Div()
Node * v8::internal::compiler::SimplifiedLowering::Int32Div (Node *const node) [private]
Definition at line 5555 of file simplified-lowering.cc.
                                                   {
  Int32BinopMatcher m(node);
  Node* const zero = jsgraph()->Int32Constant(0);
  Node* const minus_one = jsgraph()->Int32Constant(-1);
  Node* const lhs = m.left().node();
  Node* const rhs = m.right().node();
  if (m.right().Is(-1)) {
    return graph()->NewNode(machine()->Int32Sub(), zero, lhs);
  } else if (m.right().Is(0)) {
    return rhs;
  } else if (machine()->Int32DivIsSafe() || m.right().HasResolvedValue()) {
    return graph()->NewNode(machine()->Int32Div(), lhs, rhs, graph()->start());
  }
  // General case for signed integer division.
  //
  // if 0 < rhs then
  // lhs / rhs
  // else
  // if rhs < -1 then
  // lhs / rhs
  // else if rhs == 0 then
  // 0
  // else
  // 0 - lhs
  //
  // Note: We do not use the Diamond helper class here, because it really hurts
  // readability with nested diamonds.
  const Operator* const merge_op = common()->Merge(2);
  const Operator* const phi_op =
      common()->Phi(MachineRepresentation::kWord32, 2);
  Node* check0 = graph()->NewNode(machine()->Int32LessThan(), zero, rhs);
  Node* branch0 = graph()->NewNode(
      common()->Branch(BranchHint::kTrue, BranchSemantics::kMachine), check0,
      graph()->start());
  Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
  Node* true0 = graph()->NewNode(machine()->Int32Div(), lhs, rhs, if_true0);
  Node* if_false0 = graph()->NewNode(common()->IfFalse(), branch0);
  Node* false0;
  {
    Node* check1 = graph()->NewNode(machine()->Int32LessThan(), rhs, minus_one);
    Node* branch1 = graph()->NewNode(
        common()->Branch(BranchHint::kNone, BranchSemantics::kMachine), check1,
        if_false0);
    Node* if_true1 = graph()->NewNode(common()->IfTrue(), branch1);
    Node* true1 = graph()->NewNode(machine()->Int32Div(), lhs, rhs, if_true1);
    Node* if_false1 = graph()->NewNode(common()->IfFalse(), branch1);
    Node* false1;
    {
      Node* check2 = graph()->NewNode(machine()->Word32Equal(), rhs, zero);
      Node* branch2 = graph()->NewNode(
          common()->Branch(BranchHint::kNone, BranchSemantics::kMachine),
          check2, if_false1);
      Node* if_true2 = graph()->NewNode(common()->IfTrue(), branch2);
      Node* true2 = zero;
      Node* if_false2 = graph()->NewNode(common()->IfFalse(), branch2);
      Node* false2 = graph()->NewNode(machine()->Int32Sub(), zero, lhs);
      if_false1 = graph()->NewNode(merge_op, if_true2, if_false2);
      false1 = graph()->NewNode(phi_op, true2, false2, if_false1);
    }
    if_false0 = graph()->NewNode(merge_op, if_true1, if_false1);
    false0 = graph()->NewNode(phi_op, true1, false1, if_false0);
  }
  Node* merge0 = graph()->NewNode(merge_op, if_true0, if_false0);
  return graph()->NewNode(phi_op, true0, false0, merge0);
}
References common(), graph(), v8::internal::compiler::MachineGraph::Int32Constant(), jsgraph(), v8::internal::compiler::kMachine, v8::internal::kNone, v8::internal::kTrue, v8::internal::kWord32, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::CommonOperatorBuilder::Merge(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal(), and v8::internal::zero.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Int32Mod()
Node * v8::internal::compiler::SimplifiedLowering::Int32Mod (Node *const node) [private]
Definition at line 5633 of file simplified-lowering.cc.
                                                   {
  Int32BinopMatcher m(node);
  Node* const zero = jsgraph()->Int32Constant(0);
  Node* const minus_one = jsgraph()->Int32Constant(-1);
  Node* const lhs = m.left().node();
  Node* const rhs = m.right().node();
  if (m.right().Is(-1) || m.right().Is(0)) {
    return zero;
  } else if (m.right().HasResolvedValue()) {
    return graph()->NewNode(machine()->Int32Mod(), lhs, rhs, graph()->start());
  }
  // General case for signed integer modulus, with optimization for (unknown)
  // power of 2 right hand side.
  //
  // if 0 < rhs then
  // msk = rhs - 1
  // if rhs & msk != 0 then
  // lhs % rhs
  // else
  // if lhs < 0 then
  // -(-lhs & msk)
  // else
  // lhs & msk
  // else
  // if rhs < -1 then
  // lhs % rhs
  // else
  // zero
  //
  // Note: We do not use the Diamond helper class here, because it really hurts
  // readability with nested diamonds.
  const Operator* const merge_op = common()->Merge(2);
  const Operator* const phi_op =
      common()->Phi(MachineRepresentation::kWord32, 2);
  Node* check0 = graph()->NewNode(machine()->Int32LessThan(), zero, rhs);
  Node* branch0 = graph()->NewNode(
      common()->Branch(BranchHint::kTrue, BranchSemantics::kMachine), check0,
      graph()->start());
  Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
  Node* true0;
  {
    Node* msk = graph()->NewNode(machine()->Int32Add(), rhs, minus_one);
    Node* check1 = graph()->NewNode(machine()->Word32And(), rhs, msk);
    Node* branch1 = graph()->NewNode(
        common()->Branch(BranchHint::kNone, BranchSemantics::kMachine), check1,
        if_true0);
    Node* if_true1 = graph()->NewNode(common()->IfTrue(), branch1);
    Node* true1 = graph()->NewNode(machine()->Int32Mod(), lhs, rhs, if_true1);
    Node* if_false1 = graph()->NewNode(common()->IfFalse(), branch1);
    Node* false1;
    {
      Node* check2 = graph()->NewNode(machine()->Int32LessThan(), lhs, zero);
      Node* branch2 = graph()->NewNode(
          common()->Branch(BranchHint::kFalse, BranchSemantics::kMachine),
          check2, if_false1);
      Node* if_true2 = graph()->NewNode(common()->IfTrue(), branch2);
      Node* true2 = graph()->NewNode(
          machine()->Int32Sub(), zero,
          graph()->NewNode(machine()->Word32And(),
                           graph()->NewNode(machine()->Int32Sub(), zero, lhs),
                           msk));
      Node* if_false2 = graph()->NewNode(common()->IfFalse(), branch2);
      Node* false2 = graph()->NewNode(machine()->Word32And(), lhs, msk);
      if_false1 = graph()->NewNode(merge_op, if_true2, if_false2);
      false1 = graph()->NewNode(phi_op, true2, false2, if_false1);
    }
    if_true0 = graph()->NewNode(merge_op, if_true1, if_false1);
    true0 = graph()->NewNode(phi_op, true1, false1, if_true0);
  }
  Node* if_false0 = graph()->NewNode(common()->IfFalse(), branch0);
  Node* false0;
  {
    Node* check1 = graph()->NewNode(machine()->Int32LessThan(), rhs, minus_one);
    Node* branch1 = graph()->NewNode(
        common()->Branch(BranchHint::kTrue, BranchSemantics::kMachine), check1,
        if_false0);
    Node* if_true1 = graph()->NewNode(common()->IfTrue(), branch1);
    Node* true1 = graph()->NewNode(machine()->Int32Mod(), lhs, rhs, if_true1);
    Node* if_false1 = graph()->NewNode(common()->IfFalse(), branch1);
    Node* false1 = zero;
    if_false0 = graph()->NewNode(merge_op, if_true1, if_false1);
    false0 = graph()->NewNode(phi_op, true1, false1, if_false0);
  }
  Node* merge0 = graph()->NewNode(merge_op, if_true0, if_false0);
  return graph()->NewNode(phi_op, true0, false0, merge0);
}
References common(), graph(), v8::internal::compiler::MachineGraph::Int32Constant(), jsgraph(), v8::internal::kFalse, v8::internal::compiler::kMachine, v8::internal::kNone, v8::internal::kTrue, v8::internal::kWord32, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::CommonOperatorBuilder::Merge(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), and v8::internal::zero.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus().
Int32Sign()
Node * v8::internal::compiler::SimplifiedLowering::Int32Sign (Node *const node) [private]
Definition at line 5736 of file simplified-lowering.cc.
                                                    {
  Node* const minus_one = jsgraph()->Int32Constant(-1);
  Node* const zero = jsgraph()->Int32Constant(0);
  Node* const one = jsgraph()->Int32Constant(1);
  Node* const input = node->InputAt(0);
  return graph()->NewNode(
      common()->Select(MachineRepresentation::kWord32),
      graph()->NewNode(machine()->Int32LessThan(), input, zero), minus_one,
      graph()->NewNode(
          common()->Select(MachineRepresentation::kWord32),
          graph()->NewNode(machine()->Int32LessThan(), zero, input), one,
          zero));
}
References common(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::MachineGraph::Int32Constant(), jsgraph(), v8::internal::kWord32, machine(), v8::internal::compiler::TFGraph::NewNode(), one, and v8::internal::zero.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
isolate()
Isolate* v8::internal::compiler::SimplifiedLowering::isolate () [inline], [private]
Definition at line 111 of file simplified-lowering.h.
{ return jsgraph_->isolate(); }
References v8::internal::compiler::JSGraph::isolate().
Referenced by ToNumberCode(), ToNumberConvertBigIntCode(), ToNumberConvertBigIntOperator(), ToNumberOperator(), ToNumericCode(), and ToNumericOperator().
jsgraph()
JSGraph* v8::internal::compiler::SimplifiedLowering::jsgraph () [inline], [private]
Definition at line 113 of file simplified-lowering.h.
{ return jsgraph_; }
Referenced by DoIntegerToUint8Clamped(), DoIntegral32ToBit(), DoNumberToBit(), DoNumberToUint8Clamped(), DoOrderedNumberToBit(), DoSigned32ToUint8Clamped(), DoUnsigned32ToUint8Clamped(), Float64Round(), Float64Sign(), Int32Abs(), Int32Div(), Int32Mod(), Int32Sign(), LowerAllNodes(), ToNumberCode(), ToNumberConvertBigIntCode(), ToNumericCode(), Uint32Div(), Uint32Mod(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitObjectIs().
linkage()
Linkage* v8::internal::compiler::SimplifiedLowering::linkage () [inline], [private]
Definition at line 118 of file simplified-lowering.h.
{ return linkage_; }
LowerAllNodes()
void v8::internal::compiler::SimplifiedLowering::LowerAllNodes ()
Definition at line 5293 of file simplified-lowering.cc.
                                       {
  SimplifiedLoweringVerifier* verifier = nullptr;
  if (v8_flags.verify_simplified_lowering) {
    verifier = zone_->New<SimplifiedLoweringVerifier>(zone_, graph());
  }
  RepresentationChanger changer(jsgraph(), broker_, verifier);
  RepresentationSelector selector(
      jsgraph(), broker_, zone_, &changer, source_positions_, node_origins_,
      tick_counter_, linkage_, observe_node_manager_, verifier);
  selector.Run(this);
}
References broker_, graph(), jsgraph(), linkage_, v8::internal::Zone::New(), node_origins_, observe_node_manager_, v8::internal::compiler::RepresentationSelector::Run(), source_positions_, tick_counter_, v8::internal::v8_flags, and zone_.
Referenced by v8::internal::compiler::SimplifiedLoweringPhase::Run().
machine()
MachineOperatorBuilder* v8::internal::compiler::SimplifiedLowering::machine () [inline], [private]
Definition at line 116 of file simplified-lowering.h.
{ return jsgraph()->machine(); }
References v8::internal::compiler::MachineGraph::machine().
Referenced by DoIntegerToUint8Clamped(), DoIntegral32ToBit(), DoJSToNumberOrNumericTruncatesToFloat64(), DoJSToNumberOrNumericTruncatesToWord32(), DoNumberToBit(), DoNumberToUint8Clamped(), DoOrderedNumberToBit(), DoSigned32ToUint8Clamped(), DoUnsigned32ToUint8Clamped(), Float64Round(), Float64Sign(), Int32Abs(), Int32Div(), Int32Mod(), Int32Sign(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), Uint32Div(), Uint32Mod(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), and v8::internal::compiler::RepresentationSelector::VisitNode().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::SimplifiedLowering::simplified () [inline], [private]
Definition at line 117 of file simplified-lowering.h.
{ return jsgraph()->simplified(); }
References v8::internal::compiler::JSGraph::simplified().
Referenced by DoJSToNumberOrNumericTruncatesToFloat64(), DoJSToNumberOrNumericTruncatesToWord32(), and v8::internal::compiler::RepresentationSelector::VisitNode().
ToNumberCode()
Node * v8::internal::compiler::SimplifiedLowering::ToNumberCode () [private]
Definition at line 5945 of file simplified-lowering.cc.
                                       {
  if (!to_number_code_.is_set()) {
    Callable callable = Builtins::CallableFor(isolate(), Builtin::kToNumber);
    to_number_code_.set(jsgraph()->HeapConstantNoHole(callable.code()));
  }
  return to_number_code_.get();
}
References v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::compiler::HeapConstantNoHole(), isolate(), jsgraph(), and to_number_code_.
Referenced by DoJSToNumberOrNumericTruncatesToFloat64(), and DoJSToNumberOrNumericTruncatesToWord32().
ToNumberConvertBigIntCode()
Node * v8::internal::compiler::SimplifiedLowering::ToNumberConvertBigIntCode () [private]
Definition at line 5953 of file simplified-lowering.cc.
                                                    {
  if (!to_number_convert_big_int_code_.is_set()) {
    Callable callable =
        Builtins::CallableFor(isolate(), Builtin::kToNumberConvertBigInt);
    to_number_convert_big_int_code_.set(
        jsgraph()->HeapConstantNoHole(callable.code()));
  }
  return to_number_convert_big_int_code_.get();
}
References v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::compiler::HeapConstantNoHole(), isolate(), jsgraph(), and to_number_convert_big_int_code_.
Referenced by DoJSToNumberOrNumericTruncatesToFloat64(), and DoJSToNumberOrNumericTruncatesToWord32().
ToNumberConvertBigIntOperator()
Operator const * v8::internal::compiler::SimplifiedLowering::ToNumberConvertBigIntOperator () [private]
Definition at line 5984 of file simplified-lowering.cc.
                                                                  {
  if (!to_number_convert_big_int_operator_.is_set()) {
    Callable callable =
        Builtins::CallableFor(isolate(), Builtin::kToNumberConvertBigInt);
    CallDescriptor::Flags flags = CallDescriptor::kNeedsFrameState;
    auto call_descriptor = Linkage::GetStubCallDescriptor(
        graph()->zone(), callable.descriptor(),
        callable.descriptor().GetStackParameterCount(), flags,
        Operator::kNoProperties);
    to_number_convert_big_int_operator_.set(common()->Call(call_descriptor));
  }
  return to_number_convert_big_int_operator_.get();
}
References v8::internal::Builtins::CallableFor(), common(), v8::internal::Callable::descriptor(), v8::internal::flags, v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), isolate(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Operator::kNoProperties, to_number_convert_big_int_operator_, and zone().
Referenced by DoJSToNumberOrNumericTruncatesToFloat64(), and DoJSToNumberOrNumericTruncatesToWord32().
ToNumberOperator()
Operator const * v8::internal::compiler::SimplifiedLowering::ToNumberOperator () [private]
Definition at line 5971 of file simplified-lowering.cc.
                                                     {
  if (!to_number_operator_.is_set()) {
    Callable callable = Builtins::CallableFor(isolate(), Builtin::kToNumber);
    CallDescriptor::Flags flags = CallDescriptor::kNeedsFrameState;
    auto call_descriptor = Linkage::GetStubCallDescriptor(
        graph()->zone(), callable.descriptor(),
        callable.descriptor().GetStackParameterCount(), flags,
        Operator::kNoProperties);
    to_number_operator_.set(common()->Call(call_descriptor));
  }
  return to_number_operator_.get();
}
References v8::internal::Builtins::CallableFor(), common(), v8::internal::Callable::descriptor(), v8::internal::flags, v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), isolate(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Operator::kNoProperties, to_number_operator_, and zone().
Referenced by DoJSToNumberOrNumericTruncatesToFloat64(), and DoJSToNumberOrNumericTruncatesToWord32().
ToNumericCode()
Node * v8::internal::compiler::SimplifiedLowering::ToNumericCode () [private]
Definition at line 5963 of file simplified-lowering.cc.
                                        {
  if (!to_numeric_code_.is_set()) {
    Callable callable = Builtins::CallableFor(isolate(), Builtin::kToNumeric);
    to_numeric_code_.set(jsgraph()->HeapConstantNoHole(callable.code()));
  }
  return to_numeric_code_.get();
}
References v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::compiler::HeapConstantNoHole(), isolate(), jsgraph(), and to_numeric_code_.
Referenced by DoJSToNumberOrNumericTruncatesToFloat64(), and DoJSToNumberOrNumericTruncatesToWord32().
ToNumericOperator()
Operator const * v8::internal::compiler::SimplifiedLowering::ToNumericOperator () [private]
Definition at line 5998 of file simplified-lowering.cc.
                                                      {
  if (!to_numeric_operator_.is_set()) {
    Callable callable = Builtins::CallableFor(isolate(), Builtin::kToNumeric);
    CallDescriptor::Flags flags = CallDescriptor::kNeedsFrameState;
    auto call_descriptor = Linkage::GetStubCallDescriptor(
        graph()->zone(), callable.descriptor(),
        callable.descriptor().GetStackParameterCount(), flags,
        Operator::kNoProperties);
    to_numeric_operator_.set(common()->Call(call_descriptor));
  }
  return to_numeric_operator_.get();
}
References v8::internal::Builtins::CallableFor(), common(), v8::internal::Callable::descriptor(), v8::internal::flags, v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), isolate(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Operator::kNoProperties, to_numeric_operator_, and zone().
Referenced by DoJSToNumberOrNumericTruncatesToFloat64(), and DoJSToNumberOrNumericTruncatesToWord32().
Uint32Div()
Node * v8::internal::compiler::SimplifiedLowering::Uint32Div (Node *const node) [private]
Definition at line 5752 of file simplified-lowering.cc.
                                                    {
  Uint32BinopMatcher m(node);
  Node* const zero = jsgraph()->Uint32Constant(0);
  Node* const lhs = m.left().node();
  Node* const rhs = m.right().node();
  if (m.right().Is(0)) {
    return zero;
  } else if (machine()->Uint32DivIsSafe() || m.right().HasResolvedValue()) {
    return graph()->NewNode(machine()->Uint32Div(), lhs, rhs, graph()->start());
  }
  Node* check = graph()->NewNode(machine()->Word32Equal(), rhs, zero);
  Diamond d(graph(), common(), check, BranchHint::kFalse,
            BranchSemantics::kMachine);
  Node* div = graph()->NewNode(machine()->Uint32Div(), lhs, rhs, d.if_false);
  return d.Phi(MachineRepresentation::kWord32, zero, div);
}
References common(), v8::base::div, graph(), v8::internal::compiler::Diamond::if_false, jsgraph(), v8::internal::kFalse, v8::internal::compiler::kMachine, v8::internal::kWord32, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Diamond::Phi(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::MachineGraph::Uint32Constant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal(), and v8::internal::zero.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Uint32Mod()
Node * v8::internal::compiler::SimplifiedLowering::Uint32Mod (Node *const node) [private]
Definition at line 5771 of file simplified-lowering.cc.
                                                    {
  Uint32BinopMatcher m(node);
  Node* const minus_one = jsgraph()->Int32Constant(-1);
  Node* const zero = jsgraph()->Uint32Constant(0);
  Node* const lhs = m.left().node();
  Node* const rhs = m.right().node();
  if (m.right().Is(0)) {
    return zero;
  } else if (m.right().HasResolvedValue()) {
    return graph()->NewNode(machine()->Uint32Mod(), lhs, rhs, graph()->start());
  }
  // General case for unsigned integer modulus, with optimization for (unknown)
  // power of 2 right hand side.
  //
  // if rhs == 0 then
  // zero
  // else
  // msk = rhs - 1
  // if rhs & msk != 0 then
  // lhs % rhs
  // else
  // lhs & msk
  //
  // Note: We do not use the Diamond helper class here, because it really hurts
  // readability with nested diamonds.
  const Operator* const merge_op = common()->Merge(2);
  const Operator* const phi_op =
      common()->Phi(MachineRepresentation::kWord32, 2);
  Node* check0 = graph()->NewNode(machine()->Word32Equal(), rhs, zero);
  Node* branch0 = graph()->NewNode(
      common()->Branch(BranchHint::kFalse, BranchSemantics::kMachine), check0,
      graph()->start());
  Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
  Node* true0 = zero;
  Node* if_false0 = graph()->NewNode(common()->IfFalse(), branch0);
  Node* false0;
  {
    Node* msk = graph()->NewNode(machine()->Int32Add(), rhs, minus_one);
    Node* check1 = graph()->NewNode(machine()->Word32And(), rhs, msk);
    Node* branch1 = graph()->NewNode(
        common()->Branch(BranchHint::kNone, BranchSemantics::kMachine), check1,
        if_false0);
    Node* if_true1 = graph()->NewNode(common()->IfTrue(), branch1);
    Node* true1 = graph()->NewNode(machine()->Uint32Mod(), lhs, rhs, if_true1);
    Node* if_false1 = graph()->NewNode(common()->IfFalse(), branch1);
    Node* false1 = graph()->NewNode(machine()->Word32And(), lhs, msk);
    if_false0 = graph()->NewNode(merge_op, if_true1, if_false1);
    false0 = graph()->NewNode(phi_op, true1, false1, if_false0);
  }
  Node* merge0 = graph()->NewNode(merge_op, if_true0, if_false0);
  return graph()->NewNode(phi_op, true0, false0, merge0);
}
References common(), graph(), v8::internal::compiler::MachineGraph::Int32Constant(), jsgraph(), v8::internal::kFalse, v8::internal::compiler::kMachine, v8::internal::kNone, v8::internal::kWord32, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::CommonOperatorBuilder::Merge(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::MachineGraph::Uint32Constant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal(), and v8::internal::zero.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus().
zone()
Zone* v8::internal::compiler::SimplifiedLowering::zone () [inline], [private]
Definition at line 112 of file simplified-lowering.h.
{ return jsgraph_->zone(); }
References v8::internal::compiler::MachineGraph::zone().
Referenced by DoIntegerToUint8Clamped(), DoIntegral32ToBit(), DoMax(), DoMin(), DoNumberToBit(), DoOrderedNumberToBit(), DoSigned32ToUint8Clamped(), DoUnsigned32ToUint8Clamped(), ToNumberConvertBigIntOperator(), ToNumberOperator(), and ToNumericOperator().
Friends And Related Function Documentation
RepresentationSelector
friend class RepresentationSelector [friend]
Definition at line 109 of file simplified-lowering.h.
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::SimplifiedLowering::broker_ [private]
Definition at line 67 of file simplified-lowering.h.
Referenced by LowerAllNodes().
info_
OptimizedCompilationInfo* v8::internal::compiler::SimplifiedLowering::info_ [private]
Definition at line 87 of file simplified-lowering.h.
Referenced by v8::internal::compiler::RepresentationSelector::Run().
jsgraph_
JSGraph* const v8::internal::compiler::SimplifiedLowering::jsgraph_ [private]
Definition at line 66 of file simplified-lowering.h.
linkage_
Linkage* const v8::internal::compiler::SimplifiedLowering::linkage_ [private]
Definition at line 86 of file simplified-lowering.h.
Referenced by LowerAllNodes().
node_origins_
NodeOriginTable* v8::internal::compiler::SimplifiedLowering::node_origins_ [private]
Definition at line 83 of file simplified-lowering.h.
Referenced by LowerAllNodes().
observe_node_manager_
ObserveNodeManager* const v8::internal::compiler::SimplifiedLowering::observe_node_manager_ [private]
Definition at line 89 of file simplified-lowering.h.
Referenced by ChangeOp(), and LowerAllNodes().
source_positions_
SourcePositionTable* v8::internal::compiler::SimplifiedLowering::source_positions_ [private]
Definition at line 82 of file simplified-lowering.h.
Referenced by LowerAllNodes().
tick_counter_
TickCounter* const v8::internal::compiler::SimplifiedLowering::tick_counter_ [private]
Definition at line 85 of file simplified-lowering.h.
Referenced by LowerAllNodes().
to_number_code_
SetOncePointer<Node> v8::internal::compiler::SimplifiedLowering::to_number_code_ [private]
Definition at line 70 of file simplified-lowering.h.
Referenced by ToNumberCode().
to_number_convert_big_int_code_
SetOncePointer<Node> v8::internal::compiler::SimplifiedLowering::to_number_convert_big_int_code_ [private]
Definition at line 71 of file simplified-lowering.h.
Referenced by ToNumberConvertBigIntCode().
to_number_convert_big_int_operator_
SetOncePointer<Operator const> v8::internal::compiler::SimplifiedLowering::to_number_convert_big_int_operator_ [private]
Definition at line 74 of file simplified-lowering.h.
Referenced by ToNumberConvertBigIntOperator().
to_number_operator_
SetOncePointer<Operator const> v8::internal::compiler::SimplifiedLowering::to_number_operator_ [private]
Definition at line 73 of file simplified-lowering.h.
Referenced by ToNumberOperator().
to_numeric_code_
SetOncePointer<Node> v8::internal::compiler::SimplifiedLowering::to_numeric_code_ [private]
Definition at line 72 of file simplified-lowering.h.
Referenced by ToNumericCode().
to_numeric_operator_
SetOncePointer<Operator const> v8::internal::compiler::SimplifiedLowering::to_numeric_operator_ [private]
Definition at line 75 of file simplified-lowering.h.
Referenced by ToNumericOperator().
type_cache_
TypeCache const* v8::internal::compiler::SimplifiedLowering::type_cache_ [private]
Definition at line 69 of file simplified-lowering.h.
zone_
Zone* const v8::internal::compiler::SimplifiedLowering::zone_ [private]
Definition at line 68 of file simplified-lowering.h.
Referenced by LowerAllNodes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/simplified-lowering.h
/mnt/V8SourceCode/src/compiler/simplified-lowering.cc