v8::EnterV8InternalScope< HandleScopeClass, do_callback > Class Template Reference
#include <api-inl.h>
Public Member Functions
EnterV8InternalScope (i::Isolate *i_isolate, Local< Context > context, i::RuntimeCallCounterId rcc_id)
EnterV8InternalScope (i::Isolate *i_isolate, i::RuntimeCallCounterId rcc_id)
template<typename T >
Local< T > Escape (Local< T > value)
template<typename T >
MaybeLocal< T > EscapeMaybe (MaybeLocal< T > value)
template<typename From >
requires requires (From v)
auto EscapeMaybe (From value)
Private Attributes
HandleScopeClass handle_scope_
CallDepthScope< do_callback > call_depth_scope_
i::VMState< v8::OTHER > vm_state_
Detailed Description
template<typename HandleScopeClass, bool do_callback>
class v8::EnterV8InternalScope< HandleScopeClass, do_callback >
Definition at line 259 of file api-inl.h.
Constructor & Destructor Documentation
EnterV8InternalScope() [1/2]
template<typename HandleScopeClass , bool do_callback>
v8::EnterV8InternalScope< HandleScopeClass, do_callback >::EnterV8InternalScope (i::Isolate * i_isolate, Local< Context > context, i::RuntimeCallCounterId rcc_id) [inline]
Definition at line 261 of file api-inl.h.
      : handle_scope_{i_isolate},
        call_depth_scope_{i_isolate, context},
#ifdef V8_RUNTIME_CALL_STATS
        rcs_scope_{i_isolate, rcc_id},
#endif // V8_RUNTIME_CALL_STATS
        vm_state_{i_isolate} {
    DCHECK(!i_isolate->is_execution_terminating());
    DCHECK_EQ(i_isolate, i::Isolate::TryGetCurrent());
  }
References DCHECK, DCHECK_EQ, and v8::internal::Isolate::is_execution_terminating().
EnterV8InternalScope() [2/2]
template<typename HandleScopeClass , bool do_callback>
v8::EnterV8InternalScope< HandleScopeClass, do_callback >::EnterV8InternalScope (i::Isolate * i_isolate, i::RuntimeCallCounterId rcc_id) [inline]
Definition at line 273 of file api-inl.h.
      : handle_scope_{i_isolate},
        call_depth_scope_{i_isolate},
#ifdef V8_RUNTIME_CALL_STATS
        rcs_scope_{i_isolate, rcc_id},
#endif // V8_RUNTIME_CALL_STATS
        vm_state_{i_isolate} {
    DCHECK(!i_isolate->is_execution_terminating());
    DCHECK_EQ(i_isolate, i::Isolate::TryGetCurrent());
  }
References DCHECK, DCHECK_EQ, and v8::internal::Isolate::is_execution_terminating().
Member Function Documentation
Escape()
template<typename HandleScopeClass , bool do_callback>
template<typename T >
Local<T> v8::EnterV8InternalScope< HandleScopeClass, do_callback >::Escape (Local< T > value) [inline]
Definition at line 285 of file api-inl.h.
                                            {
    return handle_scope_.Escape(value);
  }
References v8::internal::value.
EscapeMaybe() [1/2]
template<typename HandleScopeClass , bool do_callback>
auto v8::EnterV8InternalScope< HandleScopeClass, do_callback >::EscapeMaybe (From value) [inline]
Definition at line 298 of file api-inl.h.
                                         {
    return handle_scope_.EscapeMaybe(Utils::ToMaybeLocal(value));
  }
References v8::Utils::ToMaybeLocal(), and v8::internal::value.
EscapeMaybe() [2/2]
template<typename HandleScopeClass , bool do_callback>
template<typename T >
MaybeLocal<T> v8::EnterV8InternalScope< HandleScopeClass, do_callback >::EscapeMaybe (MaybeLocal< T > value) [inline]
Definition at line 290 of file api-inl.h.
                                                           {
    return handle_scope_.EscapeMaybe(value);
  }
References v8::internal::value.
requires()
template<typename HandleScopeClass , bool do_callback>
template<typename From >
requires v8::EnterV8InternalScope< HandleScopeClass, do_callback >::requires (From v) [inline]
Definition at line 297 of file api-inl.h.
{ Utils::ToMaybeLocal(v); }
References v8::Utils::ToMaybeLocal().
Member Data Documentation
call_depth_scope_
template<typename HandleScopeClass , bool do_callback>
CallDepthScope<do_callback> v8::EnterV8InternalScope< HandleScopeClass, do_callback >::call_depth_scope_ [private]
Definition at line 304 of file api-inl.h.
handle_scope_
template<typename HandleScopeClass , bool do_callback>
HandleScopeClass v8::EnterV8InternalScope< HandleScopeClass, do_callback >::handle_scope_ [private]
Definition at line 303 of file api-inl.h.
vm_state_
template<typename HandleScopeClass , bool do_callback>
i::VMState<v8::OTHER> v8::EnterV8InternalScope< HandleScopeClass, do_callback >::vm_state_ [private]
Definition at line 308 of file api-inl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/api/api-inl.h