v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer Class Reference
Public Member Functions
MachineRepresentationInferrer (Schedule const *schedule, TFGraph const *graph, Linkage *linkage, Zone *zone)
CallDescriptor * call_descriptor () const
MachineRepresentation GetRepresentation (Node const *node) const
Private Member Functions
MachineRepresentation PromoteRepresentation (MachineRepresentation rep)
void Run ()
Private Attributes
Schedule const *const schedule_
Linkage const *const linkage_
ZoneVector< MachineRepresentation > representation_vector_
BasicBlock * current_block_
Detailed Description
Definition at line 22 of file machine-graph-verifier.cc.
Constructor & Destructor Documentation
MachineRepresentationInferrer()
v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::MachineRepresentationInferrer (Schedule const * schedule, TFGraph const * graph, Linkage * linkage, Zone * zone) [inline]
Definition at line 24 of file machine-graph-verifier.cc.
      : schedule_(schedule),
        linkage_(linkage),
        representation_vector_(graph->NodeCount(), MachineRepresentation::kNone,
                               zone) {
    Run();
  }
References v8::internal::kNone.
Member Function Documentation
call_descriptor()
CallDescriptor* v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::call_descriptor () const [inline]
Definition at line 33 of file machine-graph-verifier.cc.
                                          {
    return linkage_->GetIncomingDescriptor();
  }
GetRepresentation()
MachineRepresentation v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::GetRepresentation (Node const * node) const [inline]
Definition at line 37 of file machine-graph-verifier.cc.
                                                                  {
    return representation_vector_.at(node->id());
  }
References v8::internal::compiler::Node::id().
PromoteRepresentation()
MachineRepresentation v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::PromoteRepresentation (MachineRepresentation rep) [inline], [private]
Definition at line 42 of file machine-graph-verifier.cc.
                                                                         {
    switch (rep) {
      case MachineRepresentation::kWord8:
      case MachineRepresentation::kWord16:
      case MachineRepresentation::kWord32:
        return MachineRepresentation::kWord32;
      case MachineRepresentation::kSandboxedPointer:
        // A sandboxed pointer is a Word64 that uses an encoded representation
        // when stored on the heap.
        return MachineRepresentation::kWord64;
      default:
        break;
    }
    return rep;
  }
References v8::internal::kSandboxedPointer, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, and v8::internal::kWord8.
Run()
void v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run () [inline], [private]
Definition at line 58 of file machine-graph-verifier.cc.
             {
    auto blocks = schedule_->all_blocks();
    for (BasicBlock* block : *blocks) {
      current_block_ = block;
      for (size_t i = 0; i <= block->NodeCount(); ++i) {
        Node const* node =
            i < block->NodeCount() ? block->NodeAt(i) : block->control_input();
        if (node == nullptr) {
          DCHECK_EQ(block->NodeCount(), i);
          break;
        }
        switch (node->opcode()) {
          case IrOpcode::kParameter:
            representation_vector_[node->id()] =
                linkage_->GetParameterType(ParameterIndexOf(node->op()))
                    .representation();
            break;
          case IrOpcode::kReturn: {
            representation_vector_[node->id()] = PromoteRepresentation(
                linkage_->GetReturnType().representation());
            break;
          }
          case IrOpcode::kProjection: {
            representation_vector_[node->id()] =
                NodeProperties::GetProjectionType(node);
          } break;
          case IrOpcode::kTypedStateValues:
            representation_vector_[node->id()] = MachineRepresentation::kNone;
            break;
          case IrOpcode::kWord32AtomicLoad:
          case IrOpcode::kWord64AtomicLoad:
            representation_vector_[node->id()] =
                PromoteRepresentation(AtomicLoadParametersOf(node->op())
                                          .representation()
                                          .representation());
            break;
          case IrOpcode::kLoad:
          case IrOpcode::kLoadImmutable:
          case IrOpcode::kProtectedLoad:
          case IrOpcode::kLoadTrapOnNull:
            representation_vector_[node->id()] = PromoteRepresentation(
                LoadRepresentationOf(node->op()).representation());
            break;
          case IrOpcode::kLoadFramePointer:
          case IrOpcode::kLoadParentFramePointer:
          case IrOpcode::kStackSlot:
          case IrOpcode::kLoadRootRegister:
#if V8_ENABLE_WEBASSEMBLY
          case IrOpcode::kLoadStackPointer:
#endif // V8_ENABLE_WEBASSEMBLY
            representation_vector_[node->id()] =
                MachineType::PointerRepresentation();
            break;
          case IrOpcode::kUnalignedLoad:
            representation_vector_[node->id()] = PromoteRepresentation(
                LoadRepresentationOf(node->op()).representation());
            break;
          case IrOpcode::kPhi:
            representation_vector_[node->id()] =
                PhiRepresentationOf(node->op());
            break;
          case IrOpcode::kCall: {
            auto call_descriptor = CallDescriptorOf(node->op());
            if (call_descriptor->ReturnCount() > 0) {
              representation_vector_[node->id()] =
                  call_descriptor->GetReturnType(0).representation();
            } else {
              representation_vector_[node->id()] =
                  MachineRepresentation::kTagged;
            }
            break;
          }
          case IrOpcode::kWord32AtomicStore:
          case IrOpcode::kWord64AtomicStore:
            representation_vector_[node->id()] = PromoteRepresentation(
                AtomicStoreParametersOf(node->op()).representation());
            break;
          case IrOpcode::kWord32AtomicPairLoad:
          case IrOpcode::kWord32AtomicPairStore:
          case IrOpcode::kWord32AtomicPairAdd:
          case IrOpcode::kWord32AtomicPairSub:
          case IrOpcode::kWord32AtomicPairAnd:
          case IrOpcode::kWord32AtomicPairOr:
          case IrOpcode::kWord32AtomicPairXor:
          case IrOpcode::kWord32AtomicPairExchange:
          case IrOpcode::kWord32AtomicPairCompareExchange:
            representation_vector_[node->id()] = MachineRepresentation::kWord32;
            break;
          case IrOpcode::kWord32AtomicExchange:
          case IrOpcode::kWord32AtomicCompareExchange:
          case IrOpcode::kWord32AtomicAdd:
          case IrOpcode::kWord32AtomicSub:
          case IrOpcode::kWord32AtomicAnd:
          case IrOpcode::kWord32AtomicOr:
          case IrOpcode::kWord32AtomicXor:
          case IrOpcode::kWord64AtomicExchange:
          case IrOpcode::kWord64AtomicCompareExchange:
          case IrOpcode::kWord64AtomicAdd:
          case IrOpcode::kWord64AtomicSub:
          case IrOpcode::kWord64AtomicAnd:
          case IrOpcode::kWord64AtomicOr:
          case IrOpcode::kWord64AtomicXor:
            representation_vector_[node->id()] = PromoteRepresentation(
                AtomicOpType(node->op()).representation());
            break;
          case IrOpcode::kStore:
          case IrOpcode::kProtectedStore:
          case IrOpcode::kStoreTrapOnNull:
          case IrOpcode::kStoreIndirectPointer:
            representation_vector_[node->id()] = PromoteRepresentation(
                StoreRepresentationOf(node->op()).representation());
            break;
          case IrOpcode::kUnalignedStore:
            representation_vector_[node->id()] = PromoteRepresentation(
                UnalignedStoreRepresentationOf(node->op()));
            break;
          case IrOpcode::kHeapConstant:
            representation_vector_[node->id()] =
                MachineRepresentation::kTaggedPointer;
            break;
          case IrOpcode::kNumberConstant:
          case IrOpcode::kChangeBitToTagged:
          case IrOpcode::kIfException:
          case IrOpcode::kOsrValue:
          case IrOpcode::kChangeInt32ToTagged:
          case IrOpcode::kChangeUint32ToTagged:
          case IrOpcode::kBitcastWordToTagged:
          case IrOpcode::kTaggedIndexConstant:
            representation_vector_[node->id()] = MachineRepresentation::kTagged;
            break;
          case IrOpcode::kCompressedHeapConstant:
            representation_vector_[node->id()] =
                MachineRepresentation::kCompressedPointer;
            break;
          case IrOpcode::kExternalConstant:
            representation_vector_[node->id()] =
                MachineType::PointerRepresentation();
            break;
          case IrOpcode::kBitcastTaggedToWord:
          case IrOpcode::kBitcastTaggedToWordForTagAndSmiBits:
            representation_vector_[node->id()] =
                MachineType::PointerRepresentation();
            break;
          case IrOpcode::kBitcastWordToTaggedSigned:
            representation_vector_[node->id()] =
                MachineRepresentation::kTaggedSigned;
            break;
          case IrOpcode::kWord32Equal:
          case IrOpcode::kInt32LessThan:
          case IrOpcode::kInt32LessThanOrEqual:
          case IrOpcode::kUint32LessThan:
          case IrOpcode::kUint32LessThanOrEqual:
          case IrOpcode::kWord64Equal:
          case IrOpcode::kInt64LessThan:
          case IrOpcode::kInt64LessThanOrEqual:
          case IrOpcode::kUint64LessThan:
          case IrOpcode::kUint64LessThanOrEqual:
          case IrOpcode::kFloat32Equal:
          case IrOpcode::kFloat32LessThan:
          case IrOpcode::kFloat32LessThanOrEqual:
          case IrOpcode::kFloat64Equal:
          case IrOpcode::kFloat64LessThan:
          case IrOpcode::kFloat64LessThanOrEqual:
          case IrOpcode::kChangeTaggedToBit:
          case IrOpcode::kStackPointerGreaterThan:
            representation_vector_[node->id()] = MachineRepresentation::kBit;
            break;
#define LABEL(opcode) case IrOpcode::k##opcode:
          case IrOpcode::kTruncateInt64ToInt32:
          case IrOpcode::kTruncateFloat32ToInt32:
          case IrOpcode::kTruncateFloat32ToUint32:
          case IrOpcode::kBitcastFloat32ToInt32:
#if V8_ENABLE_WEBASSEMBLY
          case IrOpcode::kI32x4ExtractLane:
          case IrOpcode::kI16x8ExtractLaneU:
          case IrOpcode::kI16x8ExtractLaneS:
          case IrOpcode::kI8x16ExtractLaneU:
          case IrOpcode::kI8x16ExtractLaneS:
          case IrOpcode::kI8x16BitMask:
#endif // V8_ENABLE_WEBASSEMBLY
          case IrOpcode::kInt32Constant:
          case IrOpcode::kRelocatableInt32Constant:
          case IrOpcode::kTruncateFloat64ToWord32:
          case IrOpcode::kTruncateFloat64ToUint32:
          case IrOpcode::kChangeFloat64ToInt32:
          case IrOpcode::kChangeFloat64ToUint32:
          case IrOpcode::kRoundFloat64ToInt32:
          case IrOpcode::kFloat64ExtractLowWord32:
          case IrOpcode::kFloat64ExtractHighWord32:
          case IrOpcode::kWord32Popcnt:
            MACHINE_UNOP_32_LIST(LABEL)
            MACHINE_BINOP_32_LIST(LABEL) {
              representation_vector_[node->id()] =
                  MachineRepresentation::kWord32;
            }
            break;
          case IrOpcode::kChangeInt32ToInt64:
          case IrOpcode::kChangeUint32ToUint64:
          case IrOpcode::kBitcastWord32ToWord64:
          case IrOpcode::kInt64Constant:
          case IrOpcode::kRelocatableInt64Constant:
          case IrOpcode::kBitcastFloat64ToInt64:
          case IrOpcode::kChangeFloat64ToInt64:
          case IrOpcode::kChangeFloat64ToUint64:
          case IrOpcode::kTruncateFloat64ToInt64:
          case IrOpcode::kWord64Popcnt:
          case IrOpcode::kWord64Ctz:
          case IrOpcode::kWord64Clz:
            MACHINE_BINOP_64_LIST(LABEL) {
              representation_vector_[node->id()] =
                  MachineRepresentation::kWord64;
            }
            break;
          case IrOpcode::kRoundInt32ToFloat32:
          case IrOpcode::kRoundUint32ToFloat32:
          case IrOpcode::kRoundInt64ToFloat32:
          case IrOpcode::kRoundUint64ToFloat32:
          case IrOpcode::kBitcastInt32ToFloat32:
          case IrOpcode::kFloat32Constant:
          case IrOpcode::kTruncateFloat64ToFloat32:
            MACHINE_FLOAT32_BINOP_LIST(LABEL)
            MACHINE_FLOAT32_UNOP_LIST(LABEL) {
              representation_vector_[node->id()] =
                  MachineRepresentation::kFloat32;
            }
            break;
          case IrOpcode::kRoundInt64ToFloat64:
          case IrOpcode::kRoundUint64ToFloat64:
          case IrOpcode::kBitcastInt64ToFloat64:
          case IrOpcode::kChangeFloat32ToFloat64:
          case IrOpcode::kChangeInt32ToFloat64:
          case IrOpcode::kChangeUint32ToFloat64:
          case IrOpcode::kFloat64InsertLowWord32:
          case IrOpcode::kFloat64InsertHighWord32:
          case IrOpcode::kFloat64Constant:
          case IrOpcode::kFloat64SilenceNaN:
            MACHINE_FLOAT64_BINOP_LIST(LABEL)
            MACHINE_FLOAT64_UNOP_LIST(LABEL) {
              representation_vector_[node->id()] =
                  MachineRepresentation::kFloat64;
            }
            break;
#if V8_ENABLE_WEBASSEMBLY
          case IrOpcode::kI32x4ReplaceLane:
          case IrOpcode::kI32x4Splat:
          case IrOpcode::kI8x16Splat:
          case IrOpcode::kI8x16Eq:
            representation_vector_[node->id()] =
                MachineRepresentation::kSimd128;
            break;
#endif // V8_ENABLE_WEBASSEMBLY
#undef LABEL
          default:
            break;
        }
      }
    }
  }
References v8::internal::compiler::AtomicLoadParametersOf(), v8::internal::compiler::AtomicOpType(), v8::internal::compiler::AtomicStoreParametersOf(), v8::internal::compiler::CallDescriptorOf(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetProjectionType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::internal::kBit, v8::internal::kCompressedPointer, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kNone, v8::internal::kSimd128, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord32, v8::internal::kWord64, LABEL, v8::internal::compiler::LoadRepresentationOf(), MACHINE_BINOP_32_LIST, MACHINE_BINOP_64_LIST, MACHINE_FLOAT32_BINOP_LIST, MACHINE_FLOAT32_UNOP_LIST, MACHINE_FLOAT64_BINOP_LIST, MACHINE_FLOAT64_UNOP_LIST, MACHINE_UNOP_32_LIST, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ParameterIndexOf(), v8::internal::compiler::PhiRepresentationOf(), v8::internal::MachineType::PointerRepresentation(), v8::internal::MachineType::representation(), v8::internal::compiler::AtomicLoadParameters::representation(), v8::internal::compiler::StoreRepresentation::representation(), v8::internal::compiler::AtomicStoreParameters::representation(), v8::internal::compiler::StoreRepresentationOf(), and v8::internal::compiler::UnalignedStoreRepresentationOf().
Member Data Documentation
current_block_
BasicBlock* v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::current_block_ [private]
Definition at line 320 of file machine-graph-verifier.cc.
linkage_
Linkage const* const v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::linkage_ [private]
Definition at line 318 of file machine-graph-verifier.cc.
representation_vector_
ZoneVector<MachineRepresentation> v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::representation_vector_ [private]
Definition at line 319 of file machine-graph-verifier.cc.
schedule_
Schedule const* const v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::schedule_ [private]
Definition at line 317 of file machine-graph-verifier.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-graph-verifier.cc