v8::internal::LoadGlobalIC Class Reference
#include <ic.h>
Public Member Functions
LoadGlobalIC (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Load (Handle< Name > name, bool update_feedback=true)
Additional Inherited Members
Detailed Description
Definition at line 218 of file ic.h.
Constructor & Destructor Documentation
LoadGlobalIC()
v8::internal::LoadGlobalIC::LoadGlobalIC (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind) [inline]
Definition at line 220 of file ic.h.
      : LoadIC(isolate, vector, slot, kind) {}
Member Function Documentation
Load()
MaybeDirectHandle< Object > v8::internal::LoadGlobalIC::Load (Handle< Name > name, bool update_feedback = true)
Definition at line 465 of file ic.cc.
                                                                   {
  Handle<JSGlobalObject> global = isolate()->global_object();
  if (IsString(*name)) {
    // Look up in script context table.
    DirectHandle<String> str_name = Cast<String>(name);
    DirectHandle<ScriptContextTable> script_contexts(
        global->native_context()->script_context_table(), isolate());
    VariableLookupResult lookup_result;
    if (script_contexts->Lookup(str_name, &lookup_result)) {
      DirectHandle<Context> script_context(
          script_contexts->get(lookup_result.context_index), isolate());
      if (script_context->IsElementTheHole(lookup_result.slot_index)) {
        // Do not install stubs and stay pre-monomorphic for
        // uninitialized accesses.
        THROW_NEW_ERROR(
            isolate(),
            NewReferenceError(MessageTemplate::kAccessedUninitializedVariable,
                              name));
      }
      bool use_ic =
          (state() != NO_FEEDBACK) && v8_flags.use_ic && update_feedback;
      if (use_ic) {
        // 'const' Variables are mutable if REPL mode is enabled. This disables
        // compiler inlining for all 'const' variables declared in REPL mode.
        if (nexus()->ConfigureLexicalVarMode(
                lookup_result.context_index, lookup_result.slot_index,
                (IsImmutableLexicalVariableMode(lookup_result.mode) &&
                 !lookup_result.is_repl_mode))) {
          TRACE_HANDLER_STATS(isolate(), LoadGlobalIC_LoadScriptContextField);
        } else {
          // Given combination of indices can't be encoded, so use slow stub.
          TRACE_HANDLER_STATS(isolate(), LoadGlobalIC_SlowStub);
          SetCache(name, LoadHandler::LoadSlow(isolate()));
        }
        TraceIC("LoadGlobalIC", name);
      } else if (state() == NO_FEEDBACK) {
        TraceIC("LoadGlobalIC", name);
      }
      return Context::Get(script_context, lookup_result.slot_index, isolate());
    }
  }
  return LoadIC::Load(global, name, update_feedback);
}
References v8::internal::FeedbackNexus::ConfigureLexicalVarMode(), v8::internal::VariableLookupResult::context_index, v8::internal::Context::Get(), v8::internal::Isolate::global_object(), v8::internal::if(), v8::internal::VariableLookupResult::is_repl_mode, v8::internal::IsImmutableLexicalVariableMode(), v8::internal::IC::isolate(), v8::internal::LoadIC::Load(), v8::internal::LoadHandler::LoadSlow(), v8::internal::VariableLookupResult::mode, v8::internal::name, v8::internal::IC::nexus(), v8::internal::NO_FEEDBACK, v8::internal::IC::SetCache(), v8::internal::VariableLookupResult::slot_index, v8::internal::IC::state(), THROW_NEW_ERROR, TRACE_HANDLER_STATS, v8::internal::IC::TraceIC(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic.h
/mnt/V8SourceCode/src/ic/ic.cc