v8::internal::StringForwardingTable::Record Class Reference
#include <string-forwarding-table-inl.h>
Public Member Functions
Tagged< String > original_string (PtrComprCageBase cage_base) const
Tagged< String > forward_string (PtrComprCageBase cage_base) const
uint32_t raw_hash (PtrComprCageBase cage_base) const
v8::String::ExternalStringResourceBase * external_resource (bool *is_one_byte) const
Tagged< Object > OriginalStringObject (PtrComprCageBase cage_base) const
Tagged< Object > ForwardStringObjectOrHash (PtrComprCageBase cage_base) const
Address ExternalResourceAddress () const
void set_original_string (Tagged< Object > object)
void set_forward_string (Tagged< Object > object)
void set_raw_hash_if_empty (uint32_t raw_hash)
void set_external_resource (v8::String::ExternalStringResourceBase *resource, bool is_one_byte)
void set_external_resource (Address address)
void SetInternalized (Tagged< String > string, Tagged< String > forward_to)
void SetExternal (Tagged< String > string, v8::String::ExternalStringResourceBase *, bool is_one_byte, uint32_t raw_hash)
bool TryUpdateExternalResource (v8::String::ExternalStringResourceBase *resource, bool is_one_byte)
bool TryUpdateExternalResource (Address address)
void DisposeExternalResource ()
void DisposeUnusedExternalResource (Isolate *isolate, Tagged< String > original_string)
Private Member Functions
OffHeapObjectSlot OriginalStringSlot () const
OffHeapObjectSlot ForwardStringOrHashSlot () const
Private Attributes
Tagged_t original_string_
Tagged_t forward_string_or_hash_
Address external_resource_
Static Private Attributes
static constexpr intptr_t kExternalResourceIsOneByteTag = 1
static constexpr intptr_t kExternalResourceEncodingMask = 1
static constexpr intptr_t kExternalResourceAddressMask
Friends
class StringForwardingTable::Block
Detailed Description
Definition at line 24 of file string-forwarding-table-inl.h.
Member Function Documentation
DisposeExternalResource()
void v8::internal::StringForwardingTable::Record::DisposeExternalResource () [inline]
Definition at line 206 of file string-forwarding-table-inl.h.
                                                          {
  bool is_one_byte;
  auto resource = external_resource(&is_one_byte);
  DCHECK_NOT_NULL(resource);
  resource->Dispose();
}
References DCHECK_NOT_NULL.
Referenced by v8::internal::StringForwardingTableCleanerBase::DisposeExternalResource().
DisposeUnusedExternalResource()
void v8::internal::StringForwardingTable::Record::DisposeUnusedExternalResource (Isolate * isolate, Tagged< String > original_string) [inline]
Definition at line 213 of file string-forwarding-table-inl.h.
                                               {
#ifdef DEBUG
  Tagged<String> stored_original = original_string(isolate);
  if (IsThinString(stored_original)) {
    stored_original = Cast<ThinString>(stored_original)->actual();
  }
  DCHECK_EQ(original, stored_original);
#endif
  if (!IsExternalString(original)) return;
  Address original_resource =
      Cast<ExternalString>(original)->resource_as_address();
  bool is_one_byte;
  auto resource = external_resource(&is_one_byte);
  if (resource != nullptr &&
      reinterpret_cast<Address>(resource) != original_resource) {
    resource->Dispose();
  }
}
References DCHECK_EQ, v8::internal::InstanceTypeChecker::IsExternalString(), and v8::internal::InstanceTypeChecker::IsThinString().
Referenced by v8::internal::FullStringForwardingTableCleaner::TryExternalize().
external_resource()
v8::String::ExternalStringResourceBase * v8::internal::StringForwardingTable::Record::external_resource (bool * is_one_byte) const [inline]
Definition at line 145 of file string-forwarding-table-inl.h.
                                                                      {
  Address address = ExternalResourceAddress();
  *is_one_byte = (address & kExternalResourceEncodingMask) ==
                 kExternalResourceIsOneByteTag;
  address &= kExternalResourceAddressMask;
  return reinterpret_cast<v8::String::ExternalStringResourceBase*>(address);
}
Referenced by v8::internal::StringForwardingTable::GetExternalResource(), and v8::internal::FullStringForwardingTableCleaner::TryExternalize().
ExternalResourceAddress()
Address v8::internal::StringForwardingTable::Record::ExternalResourceAddress () const [inline]
Definition at line 46 of file string-forwarding-table-inl.h.
                                          {
    return base::AsAtomicPointer::Acquire_Load(&external_resource_);
  }
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), and external_resource_.
Referenced by v8::internal::StringForwardingTableCleanerBase::DisposeExternalResource(), and v8::internal::StringForwardingTable::TearDown().
forward_string()
Tagged<String> v8::internal::StringForwardingTable::Record::forward_string (PtrComprCageBase cage_base) const [inline]
Definition at line 30 of file string-forwarding-table-inl.h.
                                                                  {
    return Cast<String>(ForwardStringObjectOrHash(cage_base));
  }
References ForwardStringObjectOrHash().
ForwardStringObjectOrHash()
Tagged<Object> v8::internal::StringForwardingTable::Record::ForwardStringObjectOrHash (PtrComprCageBase cage_base) const [inline]
Definition at line 42 of file string-forwarding-table-inl.h.
                                                                             {
    return ForwardStringOrHashSlot().Acquire_Load(cage_base);
  }
References v8::internal::FullObjectSlot::Acquire_Load(), and ForwardStringOrHashSlot().
Referenced by forward_string(), v8::internal::FullStringForwardingTableCleaner::MarkForwardObject(), raw_hash(), and v8::internal::FullStringForwardingTableCleaner::TryInternalize().
ForwardStringOrHashSlot()
OffHeapObjectSlot v8::internal::StringForwardingTable::Record::ForwardStringOrHashSlot () const [inline], [private]
Definition at line 84 of file string-forwarding-table-inl.h.
                                                    {
    return OffHeapObjectSlot(&forward_string_or_hash_);
  }
References forward_string_or_hash_.
Referenced by ForwardStringObjectOrHash(), and set_forward_string().
original_string()
Tagged<String> v8::internal::StringForwardingTable::Record::original_string (PtrComprCageBase cage_base) const [inline]
Definition at line 26 of file string-forwarding-table-inl.h.
                                                                   {
    return Cast<String>(OriginalStringObject(cage_base));
  }
References OriginalStringObject().
OriginalStringObject()
Tagged<Object> v8::internal::StringForwardingTable::Record::OriginalStringObject (PtrComprCageBase cage_base) const [inline]
Definition at line 38 of file string-forwarding-table-inl.h.
                                                                        {
    return OriginalStringSlot().Acquire_Load(cage_base);
  }
References v8::internal::FullObjectSlot::Acquire_Load(), and OriginalStringSlot().
Referenced by v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner::ClearNonLiveYoungObjects(), v8::internal::FullStringForwardingTableCleaner::MarkForwardObject(), original_string(), v8::internal::StringForwardingTable::TearDown(), and v8::internal::FullStringForwardingTableCleaner::TransitionStrings().
OriginalStringSlot()
OffHeapObjectSlot v8::internal::StringForwardingTable::Record::OriginalStringSlot () const [inline], [private]
Definition at line 80 of file string-forwarding-table-inl.h.
                                               {
    return OffHeapObjectSlot(&original_string_);
  }
References original_string_.
Referenced by OriginalStringObject(), and set_original_string().
raw_hash()
uint32_t v8::internal::StringForwardingTable::Record::raw_hash (PtrComprCageBase cage_base) const [inline]
Definition at line 131 of file string-forwarding-table-inl.h.
                                      {
  Tagged<Object> hash_or_string = ForwardStringObjectOrHash(cage_base);
  uint32_t raw_hash;
  if (IsHeapObject(hash_or_string)) {
    raw_hash = Cast<String>(hash_or_string)->RawHash();
  } else {
    raw_hash = static_cast<uint32_t>(hash_or_string.ptr());
  }
  DCHECK(Name::IsHashFieldComputed(raw_hash));
  return raw_hash;
}
References v8::internal::DCHECK(), ForwardStringObjectOrHash(), v8::internal::Name::IsHashFieldComputed(), v8::internal::IsHeapObject(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::StringForwardingTable::GetRawHash(), and v8::internal::FullStringForwardingTableCleaner::TransitionStrings().
set_external_resource() [1/2]
void v8::internal::StringForwardingTable::Record::set_external_resource (Address address) [inline]
Definition at line 61 of file string-forwarding-table-inl.h.
                                              {
    base::AsAtomicPointer::Release_Store(&external_resource_, address);
  }
References external_resource_, and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store().
set_external_resource() [2/2]
void v8::internal::StringForwardingTable::Record::set_external_resource (v8::String::ExternalStringResourceBase * resource, bool is_one_byte) [inline]
Definition at line 162 of file string-forwarding-table-inl.h.
                                                                    {
  DCHECK_NOT_NULL(resource);
  Address address = reinterpret_cast<Address>(resource);
  if (is_one_byte && address != kNullAddress) {
    address |= kExternalResourceIsOneByteTag;
  }
  set_external_resource(address);
}
References DCHECK_NOT_NULL, and v8::internal::kNullAddress.
set_forward_string()
void v8::internal::StringForwardingTable::Record::set_forward_string (Tagged< Object > object) [inline]
Definition at line 54 of file string-forwarding-table-inl.h.
                                                 {
    ForwardStringOrHashSlot().Release_Store(object);
  }
References ForwardStringOrHashSlot(), and v8::internal::FullObjectSlot::Release_Store().
Referenced by v8::internal::StringForwardingTable::UpdateForwardString().
set_original_string()
void v8::internal::StringForwardingTable::Record::set_original_string (Tagged< Object > object) [inline]
Definition at line 50 of file string-forwarding-table-inl.h.
                                                  {
    OriginalStringSlot().Release_Store(object);
  }
References OriginalStringSlot(), and v8::internal::FullObjectSlot::Release_Store().
Referenced by v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner::ClearNonLiveYoungObjects(), and v8::internal::FullStringForwardingTableCleaner::MarkForwardObject().
set_raw_hash_if_empty()
void v8::internal::StringForwardingTable::Record::set_raw_hash_if_empty (uint32_t raw_hash) [inline]
Definition at line 153 of file string-forwarding-table-inl.h.
                                                                         {
  // Assert that computed hash values don't overlap with heap object tag.
  static_assert((kHeapObjectTag & Name::kHashNotComputedMask) != 0);
  DCHECK(Name::IsHashFieldComputed(raw_hash));
  DCHECK_NE(raw_hash & kHeapObjectTagMask, kHeapObjectTag);
  AsAtomicTagged::Release_CompareAndSwap(&forward_string_or_hash_,
                                         unused_element().value(), raw_hash);
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::Name::IsHashFieldComputed(), v8::internal::Name::kHashNotComputedMask, v8::internal::kHeapObjectTag, v8::internal::kHeapObjectTagMask, v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap(), v8::internal::StringForwardingTable::unused_element(), and v8::internal::value.
SetExternal()
void v8::internal::StringForwardingTable::Record::SetExternal (Tagged< String > string, v8::String::ExternalStringResourceBase * resource, bool is_one_byte, uint32_t raw_hash) [inline]
Definition at line 179 of file string-forwarding-table-inl.h.
                                         {
  set_original_string(string);
  set_raw_hash_if_empty(raw_hash);
  set_external_resource(resource, is_one_byte);
}
Referenced by v8::internal::StringForwardingTable::AddExternalResourceAndHash().
SetInternalized()
void v8::internal::StringForwardingTable::Record::SetInternalized (Tagged< String > string, Tagged< String > forward_to) [inline]
Definition at line 172 of file string-forwarding-table-inl.h.
                                                                               {
  set_original_string(string);
  set_forward_string(forward_to);
  set_external_resource(kNullExternalPointer);
}
References v8::internal::kNullExternalPointer.
Referenced by v8::internal::StringForwardingTable::AddForwardString().
TryUpdateExternalResource() [1/2]
bool v8::internal::StringForwardingTable::Record::TryUpdateExternalResource (Address address) [inline]
Definition at line 197 of file string-forwarding-table-inl.h.
                                                                           {
  static_assert(kNullAddress == kNullExternalPointer);
  // Don't set the external resource if another one is already stored. If we
  // would simply overwrite the resource, the previously stored one would be
  // leaked.
  return base::AsAtomicPointer::AcquireRelease_CompareAndSwap(
             &external_resource_, kNullAddress, address) == kNullAddress;
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::AcquireRelease_CompareAndSwap(), v8::internal::kNullAddress, and v8::internal::kNullExternalPointer.
TryUpdateExternalResource() [2/2]
bool v8::internal::StringForwardingTable::Record::TryUpdateExternalResource (v8::String::ExternalStringResourceBase * resource, bool is_one_byte) [inline]
Definition at line 187 of file string-forwarding-table-inl.h.
                                                                    {
  DCHECK_NOT_NULL(resource);
  Address address = reinterpret_cast<Address>(resource);
  if (is_one_byte && address != kNullAddress) {
    address |= kExternalResourceIsOneByteTag;
  }
  return TryUpdateExternalResource(address);
}
References DCHECK_NOT_NULL, v8::internal::kNullAddress, and v8::internal::StringForwardingTable::TryUpdateExternalResource().
Friends And Related Function Documentation
StringForwardingTable::Block
friend class StringForwardingTable::Block [friend]
Definition at line 128 of file string-forwarding-table-inl.h.
Member Data Documentation
external_resource_
Address v8::internal::StringForwardingTable::Record::external_resource_ [private]
Definition at line 110 of file string-forwarding-table-inl.h.
Referenced by ExternalResourceAddress(), and set_external_resource().
forward_string_or_hash_
Tagged_t v8::internal::StringForwardingTable::Record::forward_string_or_hash_ [private]
Definition at line 104 of file string-forwarding-table-inl.h.
Referenced by ForwardStringOrHashSlot().
kExternalResourceAddressMask
constexpr intptr_t v8::internal::StringForwardingTable::Record::kExternalResourceAddressMask [static], [constexpr], [private]
Initial value:
=
      ~kExternalResourceEncodingMask
Definition at line 90 of file string-forwarding-table-inl.h.
kExternalResourceEncodingMask
constexpr intptr_t v8::internal::StringForwardingTable::Record::kExternalResourceEncodingMask = 1 [static], [constexpr], [private]
Definition at line 89 of file string-forwarding-table-inl.h.
kExternalResourceIsOneByteTag
constexpr intptr_t v8::internal::StringForwardingTable::Record::kExternalResourceIsOneByteTag = 1 [static], [constexpr], [private]
Definition at line 88 of file string-forwarding-table-inl.h.
original_string_
Tagged_t v8::internal::StringForwardingTable::Record::original_string_ [private]
Definition at line 94 of file string-forwarding-table-inl.h.
Referenced by OriginalStringSlot().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string-forwarding-table-inl.h