v8::internal::compiler::RefsMap Class Reference
#include <refs-map.h>
Public Member Functions
RefsMap (uint32_t capacity, AddressMatcher match, Zone *zone)
RefsMap (const RefsMap *other, Zone *zone)
bool IsEmpty () const
Entry * Lookup (const Address &key) const
Entry * LookupOrInsert (const Address &key)
ObjectData * Remove (const Address &key)
Static Private Member Functions
static uint32_t Hash (Address addr)
Additional Inherited Members
Detailed Description
Definition at line 31 of file refs-map.h.
Constructor & Destructor Documentation
RefsMap() [1/2]
v8::internal::compiler::RefsMap::RefsMap (uint32_t capacity, AddressMatcher match, Zone * zone)
Definition at line 15 of file refs-map.cc.
    : UnderlyingMap(capacity, match, ZoneAllocationPolicy(zone)) {}
RefsMap() [2/2]
v8::internal::compiler::RefsMap::RefsMap (const RefsMap * other, Zone * zone)
Definition at line 18 of file refs-map.cc.
    : UnderlyingMap(other, ZoneAllocationPolicy(zone)) {}
Member Function Documentation
Hash()
uint32_t v8::internal::compiler::RefsMap::Hash (Address addr) [static], [private]
Definition at line 34 of file refs-map.cc.
{ return static_cast<uint32_t>(addr); }
Referenced by Lookup(), LookupOrInsert(), and Remove().
IsEmpty()
bool v8::internal::compiler::RefsMap::IsEmpty () const [inline]
Definition at line 39 of file refs-map.h.
{ return occupancy() == 0; }
References v8::base::TemplateHashMapImpl< Address, ObjectData *, AddressMatcher, ZoneAllocationPolicy >::occupancy().
Referenced by v8::internal::compiler::PerIsolateCompilerCache::SetSnapshot().
Lookup()
RefsMap::Entry * v8::internal::compiler::RefsMap::Lookup (const Address & key) const
Definition at line 21 of file refs-map.cc.
                                                      {
  return UnderlyingMap::Lookup(key, Hash(key));
}
References Hash(), v8::internal::key, and v8::base::TemplateHashMapImpl< Address, ObjectData *, AddressMatcher, ZoneAllocationPolicy >::Lookup().
LookupOrInsert()
RefsMap::Entry * v8::internal::compiler::RefsMap::LookupOrInsert (const Address & key)
Definition at line 25 of file refs-map.cc.
                                                        {
  return UnderlyingMap::LookupOrInsert(key, RefsMap::Hash(key),
                                       []() { return nullptr; });
}
References Hash(), v8::internal::key, and v8::base::TemplateHashMapImpl< Address, ObjectData *, AddressMatcher, ZoneAllocationPolicy >::LookupOrInsert().
Remove()
ObjectData * v8::internal::compiler::RefsMap::Remove (const Address & key)
Definition at line 30 of file refs-map.cc.
                                              {
  return UnderlyingMap::Remove(key, RefsMap::Hash(key));
}
References Hash(), v8::internal::key, and v8::base::TemplateHashMapImpl< Address, ObjectData *, AddressMatcher, ZoneAllocationPolicy >::Remove().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/refs-map.h
/mnt/V8SourceCode/src/compiler/refs-map.cc