anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter Class Reference
Public Member Functions
void SetSnapshotFile (const char *snapshot_cpp_file)
void SetStartupBlobFile (const char *snapshot_blob_file)
void WriteSnapshot (v8::StartupData blob) const
Private Member Functions
void MaybeWriteStartupBlob (v8::base::Vector< const uint8_t > blob) const
void MaybeWriteSnapshotFile (v8::base::Vector< const uint8_t > blob) const
Static Private Member Functions
static void WriteSnapshotFilePrefix (FILE *fp)
static void WriteSnapshotFileSuffix (FILE *fp)
static void WriteSnapshotFileData (FILE *fp, v8::base::Vector< const uint8_t > blob)
static void WriteBinaryContentsAsCArray (FILE *fp, v8::base::Vector< const uint8_t > blob)
static FILE * GetFileDescriptorOrDie (const char *filename)
Private Attributes
const char * snapshot_cpp_path_ = nullptr
const char * snapshot_blob_path_ = nullptr
Detailed Description
Definition at line 28 of file mksnapshot.cc.
Member Function Documentation
GetFileDescriptorOrDie()
static FILE* anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::GetFileDescriptorOrDie (const char * filename) [inline], [static], [private]
Definition at line 121 of file mksnapshot.cc.
                                                            {
    FILE* fp = v8::base::OS::FOpen(filename, "wb");
    if (fp == nullptr) {
      i::PrintF("Unable to open file \"%s\" for writing.\n", filename);
      exit(1);
    }
    return fp;
  }
References v8::base::OS::FOpen(), and v8::internal::PrintF().
MaybeWriteSnapshotFile()
void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::MaybeWriteSnapshotFile (v8::base::Vector< const uint8_t > blob) const [inline], [private]
Definition at line 63 of file mksnapshot.cc.
                                                                      {
    if (!snapshot_cpp_path_) return;
    FILE* fp = GetFileDescriptorOrDie(snapshot_cpp_path_);
    WriteSnapshotFilePrefix(fp);
    WriteSnapshotFileData(fp, blob);
    WriteSnapshotFileSuffix(fp);
    v8::base::Fclose(fp);
  }
References v8::base::Fclose().
MaybeWriteStartupBlob()
void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::MaybeWriteStartupBlob (v8::base::Vector< const uint8_t > blob) const [inline], [private]
Definition at line 50 of file mksnapshot.cc.
                                                                     {
    if (!snapshot_blob_path_) return;
    FILE* fp = GetFileDescriptorOrDie(snapshot_blob_path_);
    size_t written = fwrite(blob.begin(), 1, blob.length(), fp);
    v8::base::Fclose(fp);
    if (written != static_cast<size_t>(blob.length())) {
      i::PrintF("Writing snapshot file failed.. Aborting.\n");
      remove(snapshot_blob_path_);
      exit(1);
    }
  }
References v8::base::Vector< T >::begin(), v8::base::Fclose(), v8::base::Vector< T >::length(), and v8::internal::PrintF().
SetSnapshotFile()
void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::SetSnapshotFile (const char * snapshot_cpp_file) [inline]
Definition at line 30 of file mksnapshot.cc.
                                                      {
    snapshot_cpp_path_ = snapshot_cpp_file;
  }
SetStartupBlobFile()
void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::SetStartupBlobFile (const char * snapshot_blob_file) [inline]
Definition at line 34 of file mksnapshot.cc.
                                                          {
    snapshot_blob_path_ = snapshot_blob_file;
  }
WriteBinaryContentsAsCArray()
static void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::WriteBinaryContentsAsCArray (FILE * fp, v8::base::Vector< const uint8_t > blob) [inline], [static], [private]
Definition at line 111 of file mksnapshot.cc.
                                                  {
    for (int i = 0; i < blob.length(); i++) {
      if ((i & 0x1F) == 0x1F) fprintf(fp, "\n");
      if (i > 0) fprintf(fp, ",");
      fprintf(fp, "%u", static_cast<unsigned char>(blob.at(i)));
    }
    fprintf(fp, "\n");
  }
References v8::base::Vector< T >::at(), and v8::base::Vector< T >::length().
WriteSnapshot()
void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::WriteSnapshot (v8::StartupData blob) const [inline]
Definition at line 38 of file mksnapshot.cc.
                                               {
    // TODO(crbug/633159): if we crash before the files have been fully created,
    // we end up with a corrupted snapshot file. The build step would succeed,
    // but the build target is unusable. Ideally we would write out temporary
    // files and only move them to the final destination as last step.
    v8::base::Vector<const uint8_t> blob_vector(
        reinterpret_cast<const uint8_t*>(blob.data), blob.raw_size);
    MaybeWriteSnapshotFile(blob_vector);
    MaybeWriteStartupBlob(blob_vector);
  }
References v8::StartupData::data, and v8::StartupData::raw_size.
WriteSnapshotFileData()
static void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::WriteSnapshotFileData (FILE * fp, v8::base::Vector< const uint8_t > blob) [inline], [static], [private]
Definition at line 99 of file mksnapshot.cc.
                                                                      {
    fprintf(
        fp,
        "alignas(kPointerAlignment) static const uint8_t blob_data[] = {\n");
    WriteBinaryContentsAsCArray(fp, blob);
    fprintf(fp, "};\n");
    fprintf(fp, "static const int blob_size = %d;\n", blob.length());
    fprintf(fp, "static const v8::StartupData blob =\n");
    fprintf(fp, "{ (const char*) blob_data, blob_size };\n");
  }
References v8::base::Vector< T >::length().
WriteSnapshotFilePrefix()
static void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::WriteSnapshotFilePrefix (FILE * fp) [inline], [static], [private]
Definition at line 75 of file mksnapshot.cc.
                                                {
    fprintf(fp, "// Autogenerated snapshot file. Do not edit.\n\n");
    fprintf(fp, "#include \"src/init/v8.h\"\n");
    fprintf(fp, "#include \"src/base/platform/platform.h\"\n\n");
    fprintf(fp, "#include \"src/flags/flags.h\"\n");
    fprintf(fp, "#include \"src/snapshot/snapshot.h\"\n\n");
    fprintf(fp, "namespace v8 {\n");
    fprintf(fp, "namespace internal {\n\n");
  }
WriteSnapshotFileSuffix()
static void anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::WriteSnapshotFileSuffix (FILE * fp) [inline], [static], [private]
Definition at line 85 of file mksnapshot.cc.
                                                {
    fprintf(fp, "const v8::StartupData* Snapshot::DefaultSnapshotBlob() {\n");
    fprintf(fp, " return &blob;\n");
    fprintf(fp, "}\n");
    fprintf(fp, "\n");
    fprintf(
        fp,
        "bool Snapshot::ShouldVerifyChecksum(const v8::StartupData* data) {\n");
    fprintf(fp, " return v8_flags.verify_snapshot_checksum;\n");
    fprintf(fp, "}\n");
    fprintf(fp, "} // namespace internal\n");
    fprintf(fp, "} // namespace v8\n");
  }
Member Data Documentation
snapshot_blob_path_
const char* anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::snapshot_blob_path_ = nullptr [private]
Definition at line 131 of file mksnapshot.cc.
snapshot_cpp_path_
const char* anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::snapshot_cpp_path_ = nullptr [private]
Definition at line 130 of file mksnapshot.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/mksnapshot.cc