v8::internal::maglev::GetIterator Class Reference
#include <maglev-ir.h>
Public Member Functions
GetIterator (uint64_t bitfield, int load_slot, int call_slot, compiler::FeedbackVectorRef feedback)
Input & context ()
Input & receiver ()
int load_slot () const
int call_slot () const
IndirectHandle< FeedbackVector > feedback () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 2, GetIterator >
Private Attributes
const int load_slot_
const int call_slot_
const IndirectHandle< FeedbackVector > feedback_
Additional Inherited Members
Detailed Description
Definition at line 5340 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::GetIterator::Base = FixedInputValueNodeT<2, GetIterator> [private]
Definition at line 5341 of file maglev-ir.h.
Constructor & Destructor Documentation
GetIterator()
v8::internal::maglev::GetIterator::GetIterator (uint64_t bitfield, int load_slot, int call_slot, compiler::FeedbackVectorRef feedback) [inline], [explicit]
Definition at line 5344 of file maglev-ir.h.
      : Base(bitfield),
        load_slot_(load_slot),
        call_slot_(call_slot),
        feedback_(feedback.object()) {}
Member Function Documentation
call_slot()
int v8::internal::maglev::GetIterator::call_slot () const [inline]
Definition at line 5359 of file maglev-ir.h.
{ return call_slot_; }
References call_slot_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context()
Input& v8::internal::maglev::GetIterator::context () [inline]
Definition at line 5355 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
IndirectHandle<FeedbackVector> v8::internal::maglev::GetIterator::feedback () const [inline]
Definition at line 5360 of file maglev-ir.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::GetIterator::GenerateCode (MaglevAssembler * , const ProcessingState &)
load_slot()
int v8::internal::maglev::GetIterator::load_slot () const [inline]
Definition at line 5358 of file maglev-ir.h.
{ return load_slot_; }
References load_slot_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::GetIterator::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::GetIterator::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5365 of file maglev-ir.h.
{}
receiver()
Input& v8::internal::maglev::GetIterator::receiver () [inline]
Definition at line 5356 of file maglev-ir.h.
{ return input(1); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::GetIterator::SetValueLocationConstraints ()
Member Data Documentation
call_slot_
const int v8::internal::maglev::GetIterator::call_slot_ [private]
Definition at line 5369 of file maglev-ir.h.
Referenced by call_slot().
feedback_
const IndirectHandle<FeedbackVector> v8::internal::maglev::GetIterator::feedback_ [private]
Definition at line 5370 of file maglev-ir.h.
Referenced by feedback().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::GetIterator::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 5352 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::GetIterator::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 5351 of file maglev-ir.h.
load_slot_
const int v8::internal::maglev::GetIterator::load_slot_ [private]
Definition at line 5368 of file maglev-ir.h.
Referenced by load_slot().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h