unibrow::Predicate< T, size > Class Template Reference
#include <unicode.h>
Classes
class CacheEntry
Public Member Functions
Predicate ()=default
bool get (uchar c)
Private Member Functions
bool CalculateValue (uchar c)
Private Attributes
CacheEntry entries_ [kSize]
Static Private Attributes
static const int kSize = size
static const int kMask = kSize - 1
Friends
class Test
Detailed Description
template<class T, int size = 256>
class unibrow::Predicate< T, size >
Definition at line 31 of file unicode.h.
Constructor & Destructor Documentation
Predicate()
template<class T , int size = 256>
unibrow::Predicate< T, size >::Predicate () [inline], [default]
Member Function Documentation
CalculateValue()
template<class T , int s>
bool unibrow::Predicate< T, s >::CalculateValue (uchar c) [private]
Definition at line 26 of file unicode-inl.h.
                                                     {
  bool result = T::Is(code_point);
  entries_[code_point & kMask] = CacheEntry(code_point, result);
  return result;
}
References v8::internal::Is(), and v8::base::internal::result.
get()
template<class T , int s>
bool unibrow::Predicate< T, s >::get (uchar c) [inline]
Definition at line 19 of file unicode-inl.h.
                                          {
  CacheEntry entry = entries_[code_point & kMask];
  if (entry.code_point() == code_point) return entry.value();
  return CalculateValue(code_point);
}
References unibrow::Predicate< T, size >::CacheEntry::code_point(), and unibrow::Predicate< T, size >::CacheEntry::value().
Friends And Related Function Documentation
Test
template<class T , int size = 256>
friend class Test [friend]
Definition at line 37 of file unicode.h.
Member Data Documentation
entries_
template<class T , int size = 256>
CacheEntry unibrow::Predicate< T, size >::entries_[kSize] [private]
Definition at line 62 of file unicode.h.
kMask
template<class T , int size = 256>
const int unibrow::Predicate< T, size >::kMask = kSize - 1 [static], [private]
Definition at line 61 of file unicode.h.
kSize
template<class T , int size = 256>
const int unibrow::Predicate< T, size >::kSize = size [static], [private]
Definition at line 60 of file unicode.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/unicode.h
/mnt/V8SourceCode/src/strings/unicode-inl.h