v8::internal::BaseSpace Class Reference
#include <base-space.h>
Public Member Functions
BaseSpace (const BaseSpace &)=delete
BaseSpace & operator= (const BaseSpace &)=delete
Heap * heap () const
AllocationSpace identity () const
virtual size_t CommittedMemory () const
virtual size_t MaximumCommittedMemory () const
virtual size_t CommittedPhysicalMemory () const =0
virtual size_t Size () const =0
Protected Member Functions
BaseSpace (Heap *heap, AllocationSpace id)
virtual ~BaseSpace ()=default
void AccountCommitted (size_t bytes)
void AccountUncommitted (size_t bytes)
Protected Attributes
Heap * heap_
AllocationSpace id_
std::atomic< size_t > committed_ {0}
size_t max_committed_ = 0
Additional Inherited Members
Detailed Description
Definition at line 22 of file base-space.h.
Constructor & Destructor Documentation
BaseSpace() [1/2]
v8::internal::BaseSpace::BaseSpace (const BaseSpace &) [delete]
BaseSpace() [2/2]
v8::internal::BaseSpace::BaseSpace (Heap * heap, AllocationSpace id) [inline], [protected]
Definition at line 52 of file base-space.h.
: heap_(heap), id_(id) {}
 BaseSpace()
virtual v8::internal::BaseSpace::~BaseSpace () [protected], [virtual], [default]
Member Function Documentation
AccountCommitted()
void v8::internal::BaseSpace::AccountCommitted (size_t bytes) [inline], [protected]
Definition at line 56 of file base-space.h.
                                      {
    DCHECK_GE(committed_ + bytes, committed_);
    committed_ += bytes;
    if (committed_ > max_committed_) {
      max_committed_ = committed_;
    }
  }
References DCHECK_GE.
Referenced by v8::internal::LargeObjectSpace::AddPage(), v8::internal::SemiSpace::AllocateFreshPage(), v8::internal::ReadOnlySpace::AllocateNextPage(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), v8::internal::SemiSpace::MoveQuarantinedPage(), and v8::internal::LargeObjectSpace::UpdateAccountingAfterResizingObject().
AccountUncommitted()
void v8::internal::BaseSpace::AccountUncommitted (size_t bytes) [inline], [protected]
Definition at line 64 of file base-space.h.
                                        {
    DCHECK_GE(committed_, committed_ - bytes);
    committed_ -= bytes;
  }
References DCHECK_GE.
Referenced by v8::internal::LargeObjectSpace::RemovePage(), v8::internal::SemiSpace::RemovePage(), v8::internal::SemiSpace::RewindPages(), v8::internal::ReadOnlySpace::ShrinkPages(), and v8::internal::LargeObjectSpace::ShrinkPageToObjectSize().
CommittedMemory()
virtual size_t v8::internal::BaseSpace::CommittedMemory () const [inline], [virtual]
Definition at line 36 of file base-space.h.
{ return committed_; }
Referenced by v8::internal::Heap::CommittedOldGenerationMemory(), v8::internal::SemiSpace::CommittedPhysicalMemory(), v8::internal::LargeObjectSpace::CommittedPhysicalMemory(), v8::internal::ReadOnlySpace::CommittedPhysicalMemory(), v8::internal::ReadOnlyHeap::PopulateReadOnlySpaceStatistics(), v8::internal::Heap::PrintShortHeapStatistics(), v8::internal::SemiSpace::ShrinkCapacityTo(), and v8::internal::SemiSpace::Uncommit().
CommittedPhysicalMemory()
virtual size_t v8::internal::BaseSpace::CommittedPhysicalMemory () const [pure virtual]
Implemented in v8::internal::ReadOnlySpace, v8::internal::LargeObjectSpace, and v8::internal::SemiSpace.
heap()
Heap* v8::internal::BaseSpace::heap () const [inline]
Definition at line 27 of file base-space.h.
                     {
    DCHECK_NOT_NULL(heap_);
    return heap_;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers(), v8::internal::SemiSpace::AdvancePage(), v8::internal::SemiSpace::AllocateFreshPage(), v8::internal::LargeObjectSpace::AllocateLargePage(), v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::Space::DecrementExternalBackingStoreBytes(), v8::internal::ReadOnlySpace::DetachPagesAndAddToArtifacts(), v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), v8::internal::ReadOnlySpace::FinalizeSpaceForDeserialization(), v8::internal::SemiSpace::FixPagesFlags(), v8::internal::NewLargeObjectSpace::FreeDeadObjects(), v8::internal::ReadOnlySpace::FreeLinearAllocationArea(), v8::internal::Space::IncrementExternalBackingStoreBytes(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::Deserializer< IsolateT >::ReadReadOnlyHeapRef(), v8::internal::CodeLargeObjectSpace::RemovePage(), v8::internal::ReadOnlySpace::RepairFreeSpacesAfterDeserialization(), v8::internal::SemiSpace::RewindPages(), v8::internal::ReadOnlySpace::Seal(), v8::internal::ReadOnlySpace::ShrinkPages(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::MainAllocator::space_heap(), v8::internal::LargeObjectSpace::TearDown(), and v8::internal::ReadOnlySpace::TryAllocateLinearlyAligned().
identity()
AllocationSpace v8::internal::BaseSpace::identity () const [inline]
Definition at line 32 of file base-space.h.
{ return id_; }
Referenced by v8::internal::LargeObjectSpace::AllocateLargePage(), v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::MainAllocator::identity(), v8::internal::Heap::IsPendingAllocationInternal(), v8::internal::Heap::NotifyOldGenerationExpansion(), v8::internal::MutablePageMetadata::owner_identity(), v8::internal::WriteBarrier::PageFlagsAreConsistent(), v8::internal::HeapLayoutTracer::PrintHeapLayout(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), and v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run().
MaximumCommittedMemory()
virtual size_t v8::internal::BaseSpace::MaximumCommittedMemory () const [inline], [virtual]
Definition at line 38 of file base-space.h.
{ return max_committed_; }
operator=()
BaseSpace& v8::internal::BaseSpace::operator= (const BaseSpace &) [delete]
Size()
virtual size_t v8::internal::BaseSpace::Size () const [pure virtual]
Implemented in v8::internal::ReadOnlySpace, v8::internal::LargeObjectSpace, and v8::internal::SemiSpace.
Member Data Documentation
committed_
std::atomic<size_t> v8::internal::BaseSpace::committed_ {0} [protected]
Definition at line 74 of file base-space.h.
Referenced by v8::internal::SemiSpace::Swap().
heap_
Heap* v8::internal::BaseSpace::heap_ [protected]
Definition at line 70 of file base-space.h.
Referenced by v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers(), v8::internal::LargeObjectSpace::AllocateLargePage(), v8::internal::ReadOnlySpace::AllocateNextPage(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), v8::internal::ReadOnlySpace::EnsurePage(), v8::internal::ReadOnlySpace::IsDetached(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::ReadOnlySpace::Seal(), and v8::internal::SemiSpace::~SemiSpace().
id_
AllocationSpace v8::internal::BaseSpace::id_ [protected]
Definition at line 71 of file base-space.h.
max_committed_
size_t v8::internal::BaseSpace::max_committed_ = 0 [protected]
Definition at line 75 of file base-space.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/base-space.h