v8::internal::compiler::LinearScheduler Class Reference
#include <linear-scheduler.h>
Classes
struct NodeState
Public Member Functions
LinearScheduler (Zone *zone, TFGraph *graph)
bool SameBasicBlock (Node *node0, Node *node1)
Node * GetEarlySchedulePosition (Node *node)
Private Member Functions
void ComputeControlLevel ()
int GetControlLevel (Node *control) const
void SetControlLevel (Node *control, int level)
void SetEarlySchedulePosition (Node *node, Node *early_schedule_position)
Private Attributes
TFGraph * graph_
ZoneMap< Node *, int > control_level_
ZoneMap< Node *, Node * > early_schedule_position_
Detailed Description
Definition at line 21 of file linear-scheduler.h.
Constructor & Destructor Documentation
LinearScheduler()
v8::internal::compiler::LinearScheduler::LinearScheduler (Zone * zone, TFGraph * graph) [explicit]
Definition at line 16 of file linear-scheduler.cc.
    : graph_(graph), control_level_(zone), early_schedule_position_(zone) {
  ComputeControlLevel();
}
References ComputeControlLevel().
Member Function Documentation
ComputeControlLevel()
void v8::internal::compiler::LinearScheduler::ComputeControlLevel () [private]
Definition at line 21 of file linear-scheduler.cc.
                                          {
  Node* start = graph_->start();
  SetControlLevel(start, 0);
  // Do BFS from the start node and compute the level of
  // each control node.
  std::queue<Node*> queue({start});
  while (!queue.empty()) {
    Node* node = queue.front();
    int level = GetControlLevel(node);
    queue.pop();
    for (Edge const edge : node->use_edges()) {
      if (!NodeProperties::IsControlEdge(edge)) continue;
      Node* use = edge.from();
      if (use->opcode() == IrOpcode::kLoopExit &&
          node->opcode() == IrOpcode::kLoop)
        continue;
      if (control_level_.find(use) == control_level_.end() &&
          use->opcode() != IrOpcode::kEnd) {
        SetControlLevel(use, level + 1);
        queue.push(use);
      }
    }
  }
}
References control_level_, GetControlLevel(), graph_, v8::internal::compiler::NodeProperties::IsControlEdge(), v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::compiler::Node::opcode(), SetControlLevel(), v8::internal::compiler::TFGraph::start(), use(), and v8::internal::compiler::Node::use_edges().
Referenced by LinearScheduler().
GetControlLevel()
int v8::internal::compiler::LinearScheduler::GetControlLevel (Node * control) const [inline], [private]
Definition at line 40 of file linear-scheduler.h.
                                           {
    auto it = control_level_.find(control);
    DCHECK(it != control_level_.end());
    return it->second;
  }
References v8::internal::DCHECK().
Referenced by ComputeControlLevel(), and GetEarlySchedulePosition().
GetEarlySchedulePosition()
Node * v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition (Node * node)
Definition at line 47 of file linear-scheduler.cc.
                                                          {
  DCHECK(!NodeProperties::IsControl(node));
  auto it = early_schedule_position_.find(node);
  if (it != early_schedule_position_.end()) return it->second;
  std::stack<NodeState> stack;
  stack.push({node, nullptr, 0});
  Node* early_schedule_position = nullptr;
  while (!stack.empty()) {
    NodeState& top = stack.top();
    if (NodeProperties::IsPhi(top.node)) {
      // For phi node, the early schedule position is its control node.
      early_schedule_position = NodeProperties::GetControlInput(top.node);
    } else if (top.node->InputCount() == 0) {
      // For node without inputs, the early schedule position is start node.
      early_schedule_position = graph_->start();
    } else {
      // For others, the early schedule position is one of its inputs' early
      // schedule position with maximal level.
      if (top.input_index == top.node->InputCount()) {
        // All inputs are visited, set early schedule position.
        early_schedule_position = top.early_schedule_position;
      } else {
        // Visit top's input and find its early schedule position.
        Node* input = top.node->InputAt(top.input_index);
        Node* input_early_schedule_position = nullptr;
        if (NodeProperties::IsControl(input)) {
          input_early_schedule_position = input;
        } else {
          auto early_pos_it = early_schedule_position_.find(input);
          if (early_pos_it != early_schedule_position_.end()) {
            input_early_schedule_position = early_pos_it->second;
          }
        }
        if (input_early_schedule_position != nullptr) {
          if (top.early_schedule_position == nullptr ||
              GetControlLevel(top.early_schedule_position) <
                  GetControlLevel(input_early_schedule_position)) {
            top.early_schedule_position = input_early_schedule_position;
          }
          top.input_index += 1;
        } else {
          top.input_index += 1;
          stack.push({input, nullptr, 0});
        }
        continue;
      }
    }
    // Found top's early schedule position, set it to the cache and pop it out
    // of the stack.
    SetEarlySchedulePosition(top.node, early_schedule_position);
    stack.pop();
    // Update early schedule position of top's use.
    if (!stack.empty()) {
      NodeState& use = stack.top();
      if (use.early_schedule_position == nullptr ||
          GetControlLevel(use.early_schedule_position) <
              GetControlLevel(early_schedule_position)) {
        use.early_schedule_position = early_schedule_position;
      }
    }
  }
  DCHECK(early_schedule_position != nullptr);
  return early_schedule_position;
}
References v8::internal::DCHECK(), v8::internal::compiler::LinearScheduler::NodeState::early_schedule_position, early_schedule_position_, v8::internal::compiler::NodeProperties::GetControlInput(), GetControlLevel(), graph_, v8::internal::compiler::LinearScheduler::NodeState::input_index, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::NodeProperties::IsControl(), v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::compiler::LinearScheduler::NodeState::node, SetEarlySchedulePosition(), v8::internal::stack, v8::internal::compiler::TFGraph::start(), and use().
Referenced by v8::internal::compiler::SLPTree::GetEarlySchedulePosition(), and SameBasicBlock().
SameBasicBlock()
bool v8::internal::compiler::LinearScheduler::SameBasicBlock (Node * node0, Node * node1)
Definition at line 116 of file linear-scheduler.cc.
                                                             {
  Node* early_schedule_position0 = NodeProperties::IsControl(node0)
                                       ? node0
                                       : GetEarlySchedulePosition(node0);
  Node* early_schedule_position1 = NodeProperties::IsControl(node1)
                                       ? node1
                                       : GetEarlySchedulePosition(node1);
  return early_schedule_position0 == early_schedule_position1;
}
References GetEarlySchedulePosition(), and v8::internal::compiler::NodeProperties::IsControl().
Referenced by v8::internal::compiler::SLPTree::SameBasicBlock().
SetControlLevel()
void v8::internal::compiler::LinearScheduler::SetControlLevel (Node * control, int level) [inline], [private]
Definition at line 46 of file linear-scheduler.h.
                                                 {
    DCHECK(control_level_.find(control) == control_level_.end());
    control_level_[control] = level;
  }
References v8::internal::DCHECK().
Referenced by ComputeControlLevel().
SetEarlySchedulePosition()
void v8::internal::compiler::LinearScheduler::SetEarlySchedulePosition (Node * node, Node * early_schedule_position) [inline], [private]
Definition at line 51 of file linear-scheduler.h.
                                                                           {
    early_schedule_position_[node] = early_schedule_position;
  }
Referenced by GetEarlySchedulePosition().
Member Data Documentation
control_level_
ZoneMap<Node*, int> v8::internal::compiler::LinearScheduler::control_level_ [private]
Definition at line 58 of file linear-scheduler.h.
Referenced by ComputeControlLevel().
early_schedule_position_
ZoneMap<Node*, Node*> v8::internal::compiler::LinearScheduler::early_schedule_position_ [private]
Definition at line 60 of file linear-scheduler.h.
Referenced by GetEarlySchedulePosition().
graph_
TFGraph* v8::internal::compiler::LinearScheduler::graph_ [private]
Definition at line 55 of file linear-scheduler.h.
Referenced by ComputeControlLevel(), and GetEarlySchedulePosition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/linear-scheduler.h
/mnt/V8SourceCode/src/compiler/linear-scheduler.cc