v8::internal::compiler::OtherNumberConstantType Class Reference
#include <turbofan-types.h>
Public Member Functions
double Value () const
Static Public Member Functions
static bool IsOtherNumberConstant (double value)
Private Member Functions
OtherNumberConstantType (double value)
BitsetType::bitset Lub () const
Static Private Member Functions
static OtherNumberConstantType * New (double value, Zone *zone)
Private Attributes
friend Zone
double value_
Friends
class Type
class BitsetType
Additional Inherited Members
Detailed Description
Definition at line 608 of file turbofan-types.h.
Constructor & Destructor Documentation
OtherNumberConstantType()
v8::internal::compiler::OtherNumberConstantType::OtherNumberConstantType (double value) [inline], [explicit], [private]
Definition at line 623 of file turbofan-types.h.
      : TypeBase(kOtherNumberConstant), value_(value) {
    CHECK(IsOtherNumberConstant(value));
  }
References CHECK, IsOtherNumberConstant(), and v8::internal::value.
Member Function Documentation
IsOtherNumberConstant()
bool v8::internal::compiler::OtherNumberConstantType::IsOtherNumberConstant (double value) [static]
Definition at line 542 of file turbofan-types.cc.
                                                                {
  // Not an integer, not NaN, and not -0.
  return !std::isnan(value) && !RangeType::IsInteger(value) &&
         !IsMinusZero(value);
}
References v8::internal::compiler::RangeType::IsInteger(), v8::internal::IsMinusZero(), and v8::internal::value.
Referenced by OtherNumberConstantType().
Lub()
BitsetType::bitset v8::internal::compiler::OtherNumberConstantType::Lub () const [inline], [private]
Definition at line 628 of file turbofan-types.h.
{ return BitsetType::kOtherNumber; }
New()
static OtherNumberConstantType* v8::internal::compiler::OtherNumberConstantType::New (double value, Zone * zone) [inline], [static], [private]
Definition at line 619 of file turbofan-types.h.
                                                                {
    return zone->New<OtherNumberConstantType>(value);
  }
References v8::internal::Zone::New(), and v8::internal::value.
Value()
double v8::internal::compiler::OtherNumberConstantType::Value () const [inline]
Definition at line 610 of file turbofan-types.h.
{ return value_; }
References value_.
Friends And Related Function Documentation
BitsetType
friend class BitsetType [friend]
Definition at line 616 of file turbofan-types.h.
Type
friend class Type [friend]
Definition at line 615 of file turbofan-types.h.
Member Data Documentation
value_
double v8::internal::compiler::OtherNumberConstantType::value_ [private]
Definition at line 630 of file turbofan-types.h.
Referenced by Value().
Zone
friend v8::internal::compiler::OtherNumberConstantType::Zone [private]
Definition at line 617 of file turbofan-types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turbofan-types.h
/mnt/V8SourceCode/src/compiler/turbofan-types.cc