v8::internal::torque::TorqueMacro Class Reference
#include <declarable.h>
Public Member Functions
bool IsExportedToCSA () const
std::string CCName () const override
std::string CCDebugName () const override
Protected Member Functions
TorqueMacro (Declarable::Kind kind, std::string external_name, std::string readable_name, const Signature &signature, std::optional< Statement * > body, bool is_user_defined, bool exported_to_csa)
Private Member Functions
TorqueMacro (std::string external_name, std::string readable_name, const Signature &signature, std::optional< Statement * > body, bool is_user_defined, bool exported_to_csa)
Private Attributes
bool exported_to_csa_ = false
Friends
class Declarations
Additional Inherited Members
Detailed Description
Definition at line 436 of file declarable.h.
Constructor & Destructor Documentation
TorqueMacro() [1/2]
v8::internal::torque::TorqueMacro::TorqueMacro (Declarable::Kind kind, std::string external_name, std::string readable_name, const Signature & signature, std::optional< Statement * > body, bool is_user_defined, bool exported_to_csa) [inline], [protected]
Definition at line 454 of file declarable.h.
      : Macro(kind, std::move(external_name), std::move(readable_name),
              signature, body),
        exported_to_csa_(exported_to_csa) {
    SetIsUserDefined(is_user_defined);
  }
References v8::internal::torque::Declarable::SetIsUserDefined().
TorqueMacro() [2/2]
v8::internal::torque::TorqueMacro::TorqueMacro (std::string external_name, std::string readable_name, const Signature & signature, std::optional< Statement * > body, bool is_user_defined, bool exported_to_csa) [inline], [private]
Definition at line 466 of file declarable.h.
      : TorqueMacro(Declarable::kTorqueMacro, std::move(external_name),
                    std::move(readable_name), signature, body, is_user_defined,
                    exported_to_csa) {}
Member Function Documentation
CCDebugName()
std::string v8::internal::torque::TorqueMacro::CCDebugName () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Callable.
Definition at line 446 of file declarable.h.
                                         {
    // Exported functions must have unique and C++-friendly readable names, so
    // prefer those wherever possible.
    return PrefixNameForCCDebugOutput(IsExportedToCSA() ? ReadableName()
                                                        : ExternalName());
  }
References v8::internal::torque::Callable::ExternalName(), IsExportedToCSA(), v8::internal::torque::Callable::PrefixNameForCCDebugOutput(), and v8::internal::torque::Callable::ReadableName().
CCName()
std::string v8::internal::torque::TorqueMacro::CCName () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Callable.
Definition at line 440 of file declarable.h.
                                    {
    // Exported functions must have unique and C++-friendly readable names, so
    // prefer those wherever possible.
    return PrefixNameForCCOutput(IsExportedToCSA() ? ReadableName()
                                                   : ExternalName());
  }
References v8::internal::torque::Callable::ExternalName(), IsExportedToCSA(), v8::internal::torque::Callable::PrefixNameForCCOutput(), and v8::internal::torque::Callable::ReadableName().
IsExportedToCSA()
bool v8::internal::torque::TorqueMacro::IsExportedToCSA () const [inline]
Definition at line 439 of file declarable.h.
{ return exported_to_csa_; }
References exported_to_csa_.
Referenced by CCDebugName(), CCName(), and v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler().
Friends And Related Function Documentation
Declarations
friend class Declarations [friend]
Definition at line 465 of file declarable.h.
Member Data Documentation
exported_to_csa_
bool v8::internal::torque::TorqueMacro::exported_to_csa_ = false [private]
Definition at line 473 of file declarable.h.
Referenced by IsExportedToCSA().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h