v8::base::debug::StackTrace Class Reference
#include <stack_trace.h>
Public Member Functions
StackTrace ()
StackTrace (const void *const *trace, size_t count)
~StackTrace ()
const void *const * Addresses (size_t *count) const
void Print () const
void OutputToStream (std::ostream *os) const
std::string ToString () const
Private Attributes
void * trace_ [kMaxTraces]
size_t count_
Static Private Attributes
static const int kMaxTraces = 62
Detailed Description
Definition at line 41 of file stack_trace.h.
Constructor & Destructor Documentation
StackTrace() [1/2]
v8::base::debug::StackTrace::StackTrace ()
Definition at line 72 of file stack_trace_android.cc.
                       {
  StackCrawlState state(reinterpret_cast<uintptr_t*>(trace_), kMaxTraces);
  _Unwind_Backtrace(&TraceStackFrame, &state);
  count_ = state.frame_count;
}
References count_, kMaxTraces, trace_, and anonymous_namespace{stack_trace_android.cc}::TraceStackFrame().
StackTrace() [2/2]
v8::base::debug::StackTrace::StackTrace (const void *const * trace, size_t count)
Definition at line 18 of file stack_trace.cc.
                                                             {
  count = std::min(count, arraysize(trace_));
  if (count) memcpy(trace_, trace, count * sizeof(trace_[0]));
  count_ = count;
}
References arraysize, count_, and trace_.
 StackTrace()
v8::base::debug::StackTrace::~StackTrace () [default]
Member Function Documentation
Addresses()
const void *const * v8::base::debug::StackTrace::Addresses (size_t * count) const
Definition at line 26 of file stack_trace.cc.
                                                            {
  *count = count_;
  if (count_) return trace_;
  return nullptr;
}
References count_, and trace_.
OutputToStream()
void v8::base::debug::StackTrace::OutputToStream (std::ostream * os) const
Definition at line 83 of file stack_trace_android.cc.
                                                    {
  for (size_t i = 0; i < count_; ++i) {
    *os << "#" << std::setw(2) << i << trace_[i] << "\n";
  }
}
References count_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and trace_.
Referenced by ToString().
Print()
void v8::base::debug::StackTrace::Print () const
Definition at line 78 of file stack_trace_android.cc.
                             {
  std::string backtrace = ToString();
  OS::Print("%s\n", backtrace.c_str());
}
References v8::internal::Print(), v8::internal::string, and ToString().
Referenced by v8::platform::anonymous_namespace{default-platform.cc}::PrintStackTrace(), v8::base::debug::anonymous_namespace{stack_trace_win.cc}::StackDumpExceptionFilter(), and v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::StackDumpSignalHandler().
ToString()
std::string v8::base::debug::StackTrace::ToString () const
Definition at line 32 of file stack_trace.cc.
                                     {
  std::stringstream stream;
  OutputToStream(&stream);
  return stream.str();
}
References OutputToStream().
Referenced by Print().
Member Data Documentation
count_
size_t v8::base::debug::StackTrace::count_ [private]
Definition at line 90 of file stack_trace.h.
Referenced by Addresses(), OutputToStream(), and StackTrace().
kMaxTraces
const int v8::base::debug::StackTrace::kMaxTraces = 62 [static], [private]
Definition at line 85 of file stack_trace.h.
Referenced by StackTrace().
trace_
void* v8::base::debug::StackTrace::trace_[kMaxTraces] [private]
Definition at line 87 of file stack_trace.h.
Referenced by Addresses(), OutputToStream(), and StackTrace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/debug/stack_trace.h
/mnt/V8SourceCode/src/base/debug/stack_trace.cc
/mnt/V8SourceCode/src/base/debug/stack_trace_android.cc
/mnt/V8SourceCode/src/base/debug/stack_trace_fuchsia.cc
/mnt/V8SourceCode/src/base/debug/stack_trace_posix.cc
/mnt/V8SourceCode/src/base/debug/stack_trace_win.cc
/mnt/V8SourceCode/src/base/debug/stack_trace_zos.cc