v8::internal::MarkingProgressTracker Class Reference
#include <marking-progress-tracker.h>
Public Member Functions
void Enable (size_t size)
bool IsEnabled () const
size_t GetNextChunkToMark ()
size_t TotalNumberOfChunks () const
void ResetIfEnabled ()
size_t GetCurrentChunkForTesting () const
Static Public Attributes
static constexpr size_t kChunkSize = kMaxRegularHeapObjectSize
Private Attributes
size_t overall_chunks_ = 0
std::atomic< size_t > current_chunk_
Detailed Description
Definition at line 30 of file marking-progress-tracker.h.
Member Function Documentation
Enable()
void v8::internal::MarkingProgressTracker::Enable (size_t size) [inline]
Definition at line 34 of file marking-progress-tracker.h.
                           {
    DCHECK(!IsEnabled());
    overall_chunks_ = (size + kChunkSize - 1) / kChunkSize;
    current_chunk_ = 0;
  }
References current_chunk_, v8::internal::DCHECK(), IsEnabled(), kChunkSize, overall_chunks_, and size().
Referenced by v8::internal::FactoryBase< Impl >::AllocateRawArray(), and v8::internal::Factory::TryNewFixedArray().
GetCurrentChunkForTesting()
size_t v8::internal::MarkingProgressTracker::GetCurrentChunkForTesting () const [inline]
Definition at line 57 of file marking-progress-tracker.h.
                                           {
    return current_chunk_.load(std::memory_order_relaxed);
  }
References current_chunk_.
GetNextChunkToMark()
size_t v8::internal::MarkingProgressTracker::GetNextChunkToMark () [inline]
Definition at line 42 of file marking-progress-tracker.h.
                              {
    const size_t new_chunk =
        current_chunk_.fetch_add(1, std::memory_order_acq_rel);
    DCHECK_LT(new_chunk, overall_chunks_);
    return new_chunk;
  }
References current_chunk_, DCHECK_LT, and overall_chunks_.
Referenced by v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArrayWithProgressTracker().
IsEnabled()
bool v8::internal::MarkingProgressTracker::IsEnabled () const [inline]
Definition at line 40 of file marking-progress-tracker.h.
{ return overall_chunks_ != 0; }
References overall_chunks_.
Referenced by Enable(), ResetIfEnabled(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArray().
ResetIfEnabled()
void v8::internal::MarkingProgressTracker::ResetIfEnabled () [inline]
Definition at line 51 of file marking-progress-tracker.h.
                        {
    if (IsEnabled()) {
      current_chunk_ = 0;
    }
  }
References current_chunk_, and IsEnabled().
Referenced by v8::internal::MarkCompactCollector::SweepLargeSpace(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
TotalNumberOfChunks()
size_t v8::internal::MarkingProgressTracker::TotalNumberOfChunks () const [inline]
Definition at line 49 of file marking-progress-tracker.h.
{ return overall_chunks_; }
References overall_chunks_.
Referenced by v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArrayWithProgressTracker().
Member Data Documentation
current_chunk_
std::atomic<size_t> v8::internal::MarkingProgressTracker::current_chunk_ [private]
Definition at line 63 of file marking-progress-tracker.h.
Referenced by Enable(), GetCurrentChunkForTesting(), GetNextChunkToMark(), and ResetIfEnabled().
kChunkSize
constexpr size_t v8::internal::MarkingProgressTracker::kChunkSize = kMaxRegularHeapObjectSize [static], [constexpr]
Definition at line 32 of file marking-progress-tracker.h.
Referenced by Enable(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArrayWithProgressTracker().
overall_chunks_
size_t v8::internal::MarkingProgressTracker::overall_chunks_ = 0 [private]
Definition at line 62 of file marking-progress-tracker.h.
Referenced by Enable(), GetNextChunkToMark(), IsEnabled(), and TotalNumberOfChunks().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/marking-progress-tracker.h